### ISSUE TITLE
room within a room in containers

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1002]
I am running up against the constraint of not being allowed to have rooms within rooms in containers. However, that is exactly what we have. Our slide collection is a room within our dry prep, which is in the "MSB Para"  "room", which is a division of the institution, Museum of Southwestern Biology. This could be avoided if we allowed "MSB Para" to be a "division" as opposed to a "room".

**Comment by dustymc** [comment]
> constraint of not being allowed to have rooms within rooms

The lack of that rule did cause problems (eg, freezer racks in freezer racks), and the existence of that rule has prevented problems (a couple hundred of them, according to a very quick scan of the logs). I think it's a good and useful rule, but it's easy enough to drop if there's a consensus that it's not necessary.

I don't care how many non-functional (eg, do not need special handling, like collection objects or positions) container types exist. Adding "subroom" or "superroom" or whatever has no impact on the code. (It DOES have some impact on usability - http://arctos.database.museum/info/ctDocumentation.cfm?table=CTCONTAINER_TYPE should clearly document non-obvious containers, and anyone with container permissions should be familiar with the code table. I think "division" would be particularly confusing vocabulary.)

Containers are primarily meant to help find specimens, not provide an accurate map of the planet. Scanning a tube into a position in a box in a position in a rack in a position in a freezer is probably all worthwhile - there are lots of items, they all sort of look the same, many of them have tiny or cryptic labels, etc. Having more-precise location information lets you find what you want quickly and get the box back into the freezer.  Scanning an articulated blue whale skeleton into 15 levels of sub-container probably doesn't really add a lot of usability - it's hard to avoid the whale once you find the room, so just scanning it into the room probably gives most users all the information they need.  Does having a "superroom" in the hierarchy help users find the "subroom," or is the situation more whale-like - is scanning the "subroom" directly into the building sufficient information?

**Comment by campmlc** [comment]
If "division" is not consistent terminology across institutions, how about
"collection"? We need something to distinguish "MSB:Mammals" from
"MSB:Para", and using room numbers doesn't work.

**Comment by dustymc** [comment]
>how about "collection"

Probably needs wider discussion, but I don't think I much like that either - collections tend to have stuff scattered all over and don't seem like very good "place types." I've probably just been starting at taxonomy too much lately, but I think I like "super-" and "sub-" - those seem self-documenting/unambiguous, and could be used for more than rooms (eg, @amgunderson 's "big box" is essentially addressing the same problem).

**Comment by campmlc** [comment]
I still think that we need a way to search on all items in a "container"
which is a specific collection, regardless of how the "room" is arranged.
So what if "MSB Para" occupies several rooms of various configurations, or
even buildings? It is distinct from MSB Mamm and other collections and I
would like to be able to find things that are not yet cataloged but located
within MSB Para collection space. Cataloged things are no problem - it is
the large amount of legacy material that is uncataloged that this makes a
huge difference for, because we are using object tracking alone to search
and inventory these items. Right now I'm getting object tracking errors
because I want to scan slide boxes into a slide collection in a room that
is located in the "room" Division of Parasites - the latter is technically
a division or collection, not a room. I don't like "subroom" - how do you
define? MSB Para is already a "subroom" in MSB.

**Comment by campmlc** [comment]
I believe that "collection" should be a valid term as a container because we already use collection on our portals page to specify the divisions of an institution. 

I do not like sub-room, because then we have sub-sub rooms etc. ad infinitum. And "sub" also implies "below" which does not apply in this context.

Here is the current status of the MSB Mamm institution in object tracking. The Wet Collection container was created after the current restrictions on containers were put into place. It belongs in the Division of Mammals, and yet I cannot put it there because MSB Mammals (collection) is a "room" which contains other "rooms" - since this is not 
[Find Containers.pdf](https://github.com/ArctosDB/arctos/files/736376/Find.Containers.pdf)
allowed, nothing can be changed or edited.

I need this issue and the other positions issues resolved. It is causing a huge amount of wasted time, stress, and aggravation for both me and Kyndall.  MSB DGR just added another "room" to the division as part of our remodel/expansion. We are also receiving new freezer tanks which will need all new positions, racks, and boxes. Please help expedite a solution.

**Comment by campmlc** [comment]
I would like to revive this issue as I am having to redo my divisional object tracking after a remodel and expansion. I would like to propose that we add "collection" to be used as a subcategory of "institution".  This would replace the current use of "room" for divisions/collections in an institution, which is problematic because each division in turn may contain multiple rooms or rooms within rooms, as is my situation, which Arctos does not allow. 
I maintain this is the most effective means of locating items in a collection of an institution for those of us having to deal with this issue on a daily basis, despite whatever theoretical constraints it may impose.  My only alternative is to use container type = "not recorded" or make up imaginary "ranges", "shelves", "bays" etc that do not in fact exist.

@ccicero @DerekSikes @jldunnum @aranis@unm.edu @sbrant@unm.edu
