### ISSUE TITLE
bring back BerkeleyMapper on specimen detail page!

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#1004]
Below on the specimen detail page, the map widget is not super useful for really examining its locality interactively as one can do on Berkeleymapper. The WKT polygon can be confusing to public as well as the outlined polygon may be mistaken for the site of the specimen. 

I'd like to request we have a BerkeleyMapper widget or link so you can open a map window and examine interactively, change the basemap, zoom in etc. Clicking on the map interface does not current do anything so having the option of BerkeleyMapper would really be a needed enhancement!

To sweeten the deal, how about using the new BerkeleyMapper logo? (one of the options is at the bottom.... red gradient, gray gradient and multicolor options will be posted on the BerkeleyMapper repo soon)

![screenshot-arctos database museum 2016-12-15 13-33-06](https://cloud.githubusercontent.com/assets/2523089/21242878/49c6e462-c2cb-11e6-8282-b0f1a9b973c5.png)

![berkeleymapper_blue_xbg](https://cloud.githubusercontent.com/assets/2523089/21245266/70792862-c2d6-11e6-85a5-b857c4752a77.png)

**Comment by campmlc** [comment]
I second.

**Comment by dustymc** [comment]
What you see on the map depends on how big the map it. It definitely responds to clicks. It has a couple basemaps available, I think it's pretty easy to add more if you have a specific request.

I'm fine with adding a link to BM, but I think the map(s) on specimendetail are useful, and they provide functionality that's not available from BM.

**Comment by mkoo** [comment]
Can you toggle on or off the polygon-- usually just ends up as a hazy
filter when I zoom in.
Cant draw like on BM and no topo layers!

I know I can make a huge map but it's not my default setting so maybe just
what you're used to.... So maybe just add the BM link then so we can all
have our cake and eat too!

**Comment by dustymc** [comment]
>Can you toggle on or off the polygon

I suppose you could, but it does more than just be a polygon - http://arctos.database.museum/guid/MSB:Bird:17978 will have a red border because there's no overlap in the shapes, for example.

>Cant draw like on BM
>no topo

File an Issue - I think those things are possible under the current GMaps API.

>it's not my default setting

The map should remember your last view.

>So maybe just add the BM link

OK
