### ISSUE TITLE
indicate accepted/not accepted specimen events on locality detail

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#1005]
on locality details like this one: http://arctos.database.museum/editLocality.cfm?locality_id=10260449
it is not distinguishable whether the specimens associated with it are accepted or unaccepted localities. In this case, all these specimens are not accepted. 

Why do we want to keep unaccepted localities at all, one might ask? Track record of previous interpretations especially if they may have been used in previous analysis or checklists. This has proven invaluable when doing 'data forensics' later on.

Ideally, the red box could contain:
This Locality (10260449) [ help ] contains
11 unaccepted MVZ:Bird specimens 
10 accepted MVZ:Herp specimens

(example not the real numbers!) Would be a good indicator too if we can delete an unused (unusable) locality too.

**Comment by dustymc** [comment]
By "accepted" you mean "values from http://arctos.database.museum/info/ctDocumentation.cfm?table=CTSPECIMEN_EVENT_TYPE", correct?

**Comment by mkoo** [comment]
exactly
