### ISSUE TITLE
Attribute not working

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1011]
I tried bulkloading some ES specimens with radiometric dates and I get “Attribute is not valid” when I use “radiometric date”.  Can you check up on this for me?

**Comment by dustymc** [comment]
How do I find them? I'm not seeing anything in the bulkloader.

**Comment by Jegelewicz** [comment]
I moved on to other things.  I'll try again tomorrow and let you know the results.

"Reality is an illusion, albeit a very persistent one." Albert Einstein

**Comment by Jegelewicz** [comment]
OK, the file is in the bulkloader now.

**Comment by dustymc** [comment]
@Jegelewicz - There is,I hope, a comprehensive answer at https://github.com/ArctosDB/documentation-wiki/issues/30.

@ccicero @mkoo - I have no idea what to do with things like this. It's a common question which obviously need to have a documented answer. It's not really a "howto" and it's not really documentation of what an attribute IS (although it contains some of that). Maybe it's more like a blog post. It should be findable from all other documentation - eg, after someone gets the error and searches the docs for "attribute" looking for a solution. Where should this be? Help!

**Comment by Jegelewicz** [comment]
After reading that I would like to use the solution #2.  I guess that means we need the attributes "minimum radiometric date" and "maximum radiometric date".  Thanks.

**Comment by dustymc** [comment]
"radiometric date" hasn't been used, so no problem to change things.

Is "min/max radiometric **age**" a better term? "Date" in there confuses me for some reason....

**Comment by dustymc** [comment]
http://handbook.arctosdb.org/how_to/Understanding-Attribute-Errors.html

I still need terminology to create new attribute(s)

**Comment by Jegelewicz** [comment]
I like your terminology better:

> min/max radiometric age

However, many of these dates are given in the format 

>  3.6 ± 0.05 million years ago (MA)

So maybe we should include the following

Radiometric date - as currently in Arctos
Radiometric date error - a number that represents the +/- error on the Radiometric date
Radiometric age minimum - minimum age derived from radioisotope methodology
Radiometric age maximum - maximum age derived from radioisotope methodology

**Comment by dustymc** [comment]
I don't like "Radiometric date error" - we'll end up with 20 dates and 20 errors and no obvious way to put them back together.

I don't really like min and max either (although that sort of thing is in use for eg fish lot length, and maybe there are reasons to be structurally explicit here). I think that's also going to lead to association problems - given 10 mins and 10 maxes, how do you pair them up?

Why not just...

* radiometric age=3.65 (according to agent using method)
* radiometric age=3.55 (according to agent using method)
* ...

which provides one attribute (users don't have to guess where to find the information) with no pairing necessary and built-in comparative functionality (http://handbook.arctosdb.org/documentation/attributes.html#searching-by-attribute-type)

**Comment by Jegelewicz** [comment]
I hear you, but the problem is that my date looks like this 29 +/-3, which isn't a number and so will not load into the attribute field. No radiometric date is as specific as 3.55, they all include some level of error. Just listing the age without the error is like giving a set of coordinates without an error. Any other ideas about how this could be treated so that it is searchable and useful?

I might be looking for all mammal material with an age between 100,000 and 20,000 years ago - how could we make that possible in Arctos?

**Comment by dustymc** [comment]
"3.6 ± 0.05" is exactly as specific as 3.55 and 3.65, no??

<img width="866" alt="screen shot 2018-05-30 at 1 36 52 pm" src="https://user-images.githubusercontent.com/5720791/40746217-aed86e9e-640e-11e8-8be1-6dd7125a31d0.png">

http://arctos.database.museum/guid/UAM:Mamm:55773

<img width="625" alt="screen shot 2018-05-30 at 1 38 25 pm" src="https://user-images.githubusercontent.com/5720791/40746244-c4f287f0-640e-11e8-8696-d75279f7aaf3.png">


Note that's making conversions - it doesn't rely on the age being given in any specific units.


The same sort of thing with a min/max attribute requires two parameters.

<img width="445" alt="screen shot 2018-05-30 at 1 42 08 pm" src="https://user-images.githubusercontent.com/5720791/40746602-bde7f12e-640f-11e8-825b-54182524a94e.png">

http://arctos.database.museum/guid/MSB:Fish:15551

I think those data are a bit different as well. Fish-length is pretty much determined by the collector and that's it - the specimens get chopped up or pickled and those data can't readily be redetermined. Most specimens have zero or one determinations so there's not much of a pairing problem.

Numeric/isotope age is almost always determined later, there can be many of the things, metadata (technique, agent, date) matters, etc.

I still like plain ol' "radiometric age."

**Comment by campmlc** [comment]
The reality is that if there is no error field users will not do the
calculations or will risk introducing new error if they do. Faced with this
option users will put error in remarks, which isn't helpful and doesn't
solve the search issue.

**Comment by campmlc** [comment]
This is another issue that can be solved with the interface. Provide a
place for 29 +- 3, and let Arctos do the conversion into the actual data
fields.

**Comment by KatherineLAnderson** [comment]
Hi all- I am going to send an email asking a couple researchers who work with our collection and use this data how it would be best stored in Arctos. I will report back.

**Comment by sjshirar** [comment]
We've never used this attribute, but for us it'd work best as a free text attribute. That way we could enter the radiometric age and then researchers could use that to calibrate using the most recent correction.

**Comment by dustymc** [comment]
>free text

I think "age" (http://arctos.database.museum/info/ctDocumentation.cfm?table=CTATTRIBUTE_TYPE) is appropriate-enough for that use.
