### ISSUE TITLE
Part needed in ES collection

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1012]
Please add rattle, shell, shell (fossil) and pharyngeal arch as parts in ES collections.
The rattle is from a snake - if there is some term that you prefer over rattle, please let me know!

**Comment by dustymc** [comment]
>rattle

@jtgiermakowski @atrox10  - you must have this, what do you call it? "tail tip"??

>shell, shell (fossil)

Done, but - please comment on #1020, and @ccicero maybe we should schedule an AWG meeting or etc to talk about parts? 

>pharyngeal arch

done

**Comment by jtgiermakowski** [comment]
Hi,

tail tip and associated taxonomy would extend to "rattle", otherwise we'd
have to specify: "rattlesnake rattle (tail tip)"

T.

2017-01-04 9:52 GMT-07:00 dustymc <notifications@github.com>:

**Comment by Jegelewicz** [comment]
I'm OK with tail tip, but it should probably be tail tip (dry) based upon what is in other collections.

**Comment by dustymc** [comment]
>tail tip (dry)

done
