### ISSUE TITLE
add publication citation to all items in a loan

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1013]
Is there a way to automatically add all items in a loan (or a saved search) to a publication as cited specimens?

**Comment by campmlc** [comment]
I used the manage tool in specimen results to add a new identification based on molecular data to all loan items. Then I created the pub in Arctos, and tried to edit to add the citations. When I clicked on "create citation with this identification" based on the new ID I just added, I get the following Oracle error:

![image](https://cloud.githubusercontent.com/assets/14808196/21575915/58259c34-cedc-11e6-8a18-b0f36023a8f6.png)
![screenshot 2016-12-30 22 05 07](https://cloud.githubusercontent.com/assets/14808196/21575923/6a2b3fe2-cedc-11e6-9bc6-a3b13a4a3570.png)
![screenshot 2016-12-30 22 07 59](https://cloud.githubusercontent.com/assets/14808196/21575928/85ad111e-cedc-11e6-8fdf-fa4b277dbf3a.png)

**Comment by dustymc** [comment]
>Is there a way to automatically add all items in a loan (or a saved search) to a publication as cited specimens?

The best approach is to require those data from the borrower in a useful format (excel sheet, etc.) as part of the loan. I don't think I'd be comfortable building a "cite everything" tool; the underlying assumption would be that everything was used, nothing was mis-transcribed, etc., and that's not really very common in the wild. You should be able to list specimens from the loan, download, and manipulate (or a download-for-citation option there doesn't scare me for some reason, if that makes things easier).

>add a new identification based on molecular data

I think I'm somewhat alone in this, but I maintain that this is the correct/most useful approach (and so the direction in which I'd prefer to develop, if that's where this goes). Minimally, whatever technique they used doesn't reject your IDs, and that's valuable information worth recording.

Citation requires a numeric page number, S1 won't work.

**Comment by campmlc** [comment]
Of course it would be ideal if the borrower would provide us with citation data. But the reality is that they rarely do, despite repeated and multiple requests.  The reason I posted this request is to provide a curatorial tool to allow cms discretion to add bulk add specimens to a publication quickly, without the time-consuming effort of "list specimen, download, manipulate" etc. "Time-consuming" is already the reason we are so very behind in getting specimens linked to publications. This is the last, and most importan step, of curation, and yet we so rarely can find time for it. Anything that could facilitate this process would be of benefit to curatorial staff, to collections, and to Arctos. 
Yes, it could happen that such a tool would result in specimens being cited that were not actually in the paper. On the other hand, if the authors fail to specify which borrrowed specimens were used in the publication (eg, no MSB numbers), then I think it is better to cite link all the loan items to the publication than to link nothing at all.  This is the situation I am currently facing.

If the appendix S1 is in online supplemental material and has no page number, how do we cite?

**Comment by dustymc** [comment]
> the reality is that they rarely do, despite repeated and multiple requests

Collections have wildly variable citations-per-loaned-item rates (see /Reports/UsageData). I don't really have any idea why (loan terms? Incomplete loan data?); figuring that out and writing up best practices or similar might be useful (and fundable?).

Note also the "rank" button on agent records - PLEASE use that to let others know if specific users refuse to comply with (or perfectly follow, etc.) loan terms.

>and most importan step, of curation

I 100% agree! I might argue that maintaining accurate and complete long-term publication<---> voucher links is the most scientifically critical function of a museum.

>then I think it is better to cite link all the loan items to the publication than to link nothing at all.

I strongly disagree, and this is a big part of why projects exist. The presence of citations should be a trustworthy indication that the publication authors documented specimen usage in some sort of useful/believable way.

>how do we cite?

I'm not sure, and I don't find anything in the documentation - https://arctosdb.org/documentation/publications/specimen-citations/#occurs_page_number

**Comment by campmlc** [comment]
In my current situation, the authors borrowed 12 specimens, and they cite
12 specimens, but without providing MSB numbers. Again, it would be useful
to be able to add all 12 specimens directly to the publication with a
single click ("add all loan items to publication") rather than doing this
12 (or 144 or whatever) times.
That is, assuming we can figure out how to cite specimens in a table in
online supplemental material without a page number.

**Comment by dustymc** [comment]
Send me loan/publication info and I'll see if I can figure out a relatively painless pathway.

>figure out how to cite specimens

I opened #1018 - this should be more visible

**Comment by campmlc** [comment]
http://arctos.database.museum/Loan.cfm?transaction_id=21070851&Action=editLoan

**Comment by dustymc** [comment]
From the loan I clicked specimens, then download, deleted the stuff not needed by the citation loader and added the stuff required by the citation loader. "Download citation bulkloader format" or similar could be an option from specimenresults, but this only took a couple minutes and wasn't too painful.

[ArctosData_C52F2130F9.csv.zip](https://github.com/ArctosDB/arctos/files/682940/ArctosData_C52F2130F9.csv.zip)

**Comment by campmlc** [comment]
For those of us using Excel, downloading and re-upload requires conversion
from csv to xlsx, fixing any date and other format issues, reconverting to
csv, eliminating the extra space with a text editor, and re-uploading, then
dealing with any Oracle errors that result from something stupid you just
did. This must be repeated for every edit change. Plus there is the
opportunity to introduce errors working outside of the Arctos environment,
i.e. get up for coffee and cat walks across keyboard and messes up the
spreadsheet. Whenever possible, I prefer to use Arctos tools when they
exist as a more secure alternative.

**Comment by dustymc** [comment]
Someone with Excel-fu should write a how-to.

>conversion from csv to xlsx

Google "associate file type with program {your operating system}" or similar - you should be able to set CSV to just open in Excel.

>eliminating the extra space

I very recently discovered that this is at least sometimes caused by what looks like a bug in Java (or maybe CF) adding extra invisible magic junk to files - I'm working on that now, let me know details if this happens and I may be able to fix it.

>fixing any date

That's what always gets me. There MUST be a way to set default date format in Excel, but I've never been able to find it.

>cats

I'm not sure I can help with that one - I think this will always be something that'll need editing. I can go ahead and add a "download for citation loader" option to specimenresults.

**Comment by campmlc** [comment]
Thanks. And if the opportunity arises to add "manage ->change stuff ->
citations to our specimen results  toolkit, that would also be appreciated.

**Comment by dustymc** [comment]
download option in v7.4.5
