### ISSUE TITLE
creating not-label containers (was: Invalid container_type; this form is a very bad place to experiment)

### ISSUE THREAD

**Issue by KyndallH** [ArctosDB/arctos#1022]
<img width="1067" alt="screen shot 2017-01-04 at 11 26 37 am" src="https://cloud.githubusercontent.com/assets/16887896/21657904/d874ccc4-d270-11e6-9f90-34e9365dcab4.png">

I got this message awhile ago when I was trying to the microplate so I'm thinking it doesn't like microplate in addition to microwell.

I'm also attaching the template in xls since it won't let me attach the csv file. 
[CreateContainerTemplate 2017.xlsx](https://github.com/ArctosDB/arctos/files/685817/CreateContainerTemplate.2017.xlsx)

http://arctos.database.museum/CreateContainersForBarcodes.cfm

**Comment by dustymc** [comment]
Bah!

You can only create "label" container types - I assume because directly creating not-label container types melted something at some point, but I can't remember details. Should we drop that "rule," or ignore it for some users, or ?????????????????

Email me the CSV (or zip it and attach here) and I'll create these while you're figuring that out.

**Comment by KyndallH** [comment]
So we can only create barcodes that are "container label,cryovial label,specimen label or "position"? Hmmm. Trying to think what would be bad if someone created a barcode that is a valid container type in bulk because you can edit it in bulk (except positions). 

I think we should do away with the restriction but others should weigh in before we do so (they may have a good reason for it). Ethno and Arch are going to start barcoding all their objects, trays, cases, etc. and it would be easiest if we can create the barcode for what it is then adding an additional step of changing it.

**Comment by KyndallH** [comment]
Yay! Feels good to be shaking up Arctos right after Christmas break! 🤕

**Comment by dustymc** [comment]
I THINK (maybe...) the rule goes back to big rolls of semi-generic barcodes and stickynotes+sharpies - create a bunch of (unusable) "labels," then as needed peel a thousand off and turn them into "cryovials," another thousand for "vials," etc. Without the forced change, you end up with low-quality data in container type - the kiddos just slap the closest label on whatever they're holding at the moment.

I think that worked pretty well and may be worth somehow maintaining, but it's a pain for what you're doing, and creating cabinets/trays/etc. If we do want to keep it, maybe add some sort of "no srsly I know what I'm doing!" bypass flag that only works for "power users" or something?????????

**Comment by campmlc** [comment]
I second any request to be able to create non-label container types
directly.

**Comment by dustymc** [comment]
merged into #1025
