### ISSUE TITLE
moving barcodes error

### ISSUE THREAD

**Issue by KyndallH** [ArctosDB/arctos#1024]
I went to bulkload move container and received this message:
<img width="1534" alt="screen shot 2017-01-04 at 2 13 20 pm" src="https://cloud.githubusercontent.com/assets/16887896/21662776/50f5bea8-d288-11e6-8254-57901a622b2e.png">

I thought maybe it was just the one barcode that Arctos was getting hung up on so I tried a few more doing it manually one at a time. Nope. 
<img width="1564" alt="screen shot 2017-01-04 at 2 15 11 pm" src="https://cloud.githubusercontent.com/assets/16887896/21662778/55267af8-d288-11e6-9f32-7e0aa8e04886.png">

Is something set on microplates that I can't scan microwells into them?
I'm on a roll today. 👎

**Comment by dustymc** [comment]
Your haven't (properly) claimed them.

Manage/ObjectTracking/BarcodeSeries

If I've guessed the pattern correctly, try

```
regexp_like(barcode,'^CCDB-198[0-9]{0,2}[-]*[A-Z]*[0-9]{0,2}$')
```

which should allow CCDB-189 plus 0 to 2 numbers
optionally plus a dash
optionally plus a letter
optionally plus 0 to 2 numbers

**Comment by KyndallH** [comment]
That worked! 

BUT, now I get this error message:
<img width="1335" alt="screen shot 2017-01-04 at 2 51 09 pm" src="https://cloud.githubusercontent.com/assets/16887896/21663536/4418f146-d28d-11e6-9a47-61befd57d0ea.png">

**Comment by KyndallH** [comment]
Okay, I just looked up the barcodes. Despite the error message, they appeared to be moved.

**Comment by dustymc** [comment]
Blank line in your file, I think - you told it to move nothing to nothing...

I hope to get that fix out tonight.
