### ISSUE TITLE
delete all specimens in an encumbrance

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1031]
is not working.
![screenshot 2017-01-11 05 42 04](https://cloud.githubusercontent.com/assets/14808196/21849756/9caa8f40-d7c4-11e6-8821-191145413aa9.png)
![screenshot 2017-01-11 05 43 24](https://cloud.githubusercontent.com/assets/14808196/21849757/9cac1450-d7c4-11e6-9e0b-10694d97161e.png)

**Comment by dustymc** [comment]
That form is limited to 1K records. You can split it into smaller batches, or let me know the encumbrance_id and I can delete.

**Comment by campmlc** [comment]
Encumbrance to delete all specimens:
Delete MSB Fish records (mask record) by Mariel L. Campbell made
2016-11-27, expires 2017-11-27 Delete for re-upload of edited records

**Comment by dustymc** [comment]
done
