### ISSUE TITLE
Reports

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1033]
Is there any documentation for creating reports in Arctos?  Specifically, I would like to have a loan invoice so that I don't have to re-enter the data into my current Word document invoice.

**Comment by ekrimmel** [comment]
I was just working on the same thing for us at CHAS. Not sure the existing documentation is any more thorough than what's [on here](https://arctosdb.org/how-to/label/), but I will say that I tried to streamline our "CHAS_loan_inventory" [report template and handler](http://arctos.database.museum/Reports/reporter.cfm). So if you create copies from ours it may be a little easier to follow than some of the other more complex handlers...

**Comment by dustymc** [comment]
http://handbook.arctosdb.org/how_to/How-to-Create-Labels.html
