### ISSUE TITLE
Paleontological Resources Preservation Act (PRPA) and the need to designate specimens from Dept of Interior properties

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1035]
Yesterday I attended an iDigBio webinar about new rules for paleontological specimens from DOI sites.  

A recording of the webinar can be found here: https://idigbio.adobeconnect.com/_a1130716096/p4hcf8is01h/?launcher=false&fcsContent=true&pbMode=normal

A summary of the rules can be found here: https://www.blm.gov/sites/blm.gov/files/programs_cultural%20heritage%20and%20paleontology_paleontology_quick%20links_prpa%20fact%20sheet%20II.pdf

I would like to have an easy way to designate which of my specimens are from DOI sites  because we have recently been asked for an inventory of such specimens and the new rules include a locality confidentiality section so we may need to limit the locality data for DOI site specimens in the future.

My first thought was to create a new collector role, perhaps "owner" where I can have the associated agent be Department of the Interior, but others might have better ideas.  In any case, I think this is something we need to be thinking about before the rules go into effect.

**Comment by dustymc** [comment]
>designate which of my specimens are from DOI sites

Projects. @amgunderson could you write something up for http://handbook.arctosdb.org/how_to/?

>limit the locality data

You can do so with http://arctos.database.museum/info/ctDocumentation.cfm?table=CTENCUMBRANCE_ACTION

**Comment by dustymc** [comment]
http://handbook.arctosdb.org/how_to/National-Park-Specimens.html
