### ISSUE TITLE
University of Mississippi specimens

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1039]
I would like to have a coll_other_id_type for the University of Mississippi.

**Comment by ccicero** [comment]
Is it the University of Mississippi Museum (http://museum.olemiss.edu/)?

What's the institutional acronym?

**Comment by Jegelewicz** [comment]
I don't know.  The tags only have a number, but it is identified as a "University of Mississippi" number in our catalog.  The museum you suggested is an art and history museum.  I don't think they have any biological specimens.  I would guess that any biodiversity collections are held in Biology.  I'm happy to just call this an "institutional catalog number" and leave it...

**Comment by dustymc** [comment]
done
