### ISSUE TITLE
Request for "Other ID Number Type"

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1043]
I have multiple specimens with identification numbers from the following institutions, none of which have collection codes.  I feel it would be good to have these numbers associated with the appropriate institution.  Can they be added to the coll_other_id_type list please?  Also, Can you please add the codes for all of our collections?

Audubon Park Zoo (New Orleans)
Baltimore Zoo
Centennial Museum and Desert Gardens
Houston Zoo
Peregrine Fund

**Comment by ccicero** [comment]
Done, with the following modifications:

Audubon Park Zoo (New Orleans) ---> entered under current name Audubon Zoo
Baltimore Zoo ---> entered under current name Maryland Zoo.

See Descriptions and URLs:
http://arctos.database.museum/info/ctDocumentation.cfm?table=CTCOLL_OTHER_ID_TYPE

**Comment by Jegelewicz** [comment]
Thanks!

**Comment by dustymc** [comment]
Base_URL in the code table should be reserved for forming resolvable IDs -  http://audubonnatureinstitute.org/zoo/{whatever_someone_enters_in_other_IDs} should do something, and if it doesn't the URL should be removed.
