### ISSUE TITLE
coll_other_id_type

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1045]
Please add NMMNH: New Mexico Museum of Natural History and Science
http://nmnaturalhistory.org/bioscience/bioscience-collections

**Comment by campmlc** [comment]
Teresa,
This other ID already exists as:

NMMNHS: New Mexico Museum of Natural History and Science.

Can I ask what specimens you have that have this ID?

Mariel Campbell

Collection Manager, Division of Genomic Resources
Museum of Southwestern  Biology

Shipping Address:
Museum of Southwestern Biology
Division of Genomic Resources
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131

(505) 277-7808 office
email: campmlc@unm.edu
