### ISSUE TITLE
Deleting records

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1047]
This worked for me once today, but the second time I went to delete encumbered records I ended up with an error:

![image](https://cloud.githubusercontent.com/assets/5725767/23374835/2c1a4556-fce3-11e6-9c82-0bd97978688e.png)

Any idea what happened?

**Comment by campmlc** [comment]
How many records are you deleting? There is a max limit.

**Comment by Jegelewicz** [comment]
15

"Reality is an illusion, albeit a very persistent one." Albert Einstein

**Comment by Jegelewicz** [comment]
It worked today.
