### ISSUE TITLE
CITES

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1049]
Could we look into the possibility of linking with the CITES listed species so that any of us could easily see which of our specimens are listed?  I recently had to check a list of 250 plant specimens to see if any of them were listed before we sent them off in an exchange.  It seems to me that this is something that could be automated (and maybe it is, but I am just unaware of it!).

Thanks!

**Comment by ekrimmel** [comment]
If/when possible, we would also love this as a feature at CHAS.

**Comment by dustymc** [comment]
Merging into https://github.com/ArctosDB/arctos/issues/1584
