### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1050]
It seems as if I have no Arctos documentation at the moment.  The site https://arctosdb.org/ is not available to me (see attached screenshot) and the Arctos Documentation Wiki is essentially empty (where did all of the pages go?  I swear I created some of them...).  When/where is the new documentation coming and how are we letting end-users know?

I am confused about the many ways communications are happening.  Between GitHub and Google Groups, I do not know who is doing what or how I am supposed to communicate.  I feel like I'm on the outside looking in through a foggy glass. :-(

![screenshot 2017-03-01 08 34 53](https://cloud.githubusercontent.com/assets/5725767/23467110/5cf174d8-fe5a-11e6-97ad-24f9bf61f6fb.png)
![screenshot 2017-03-01 08 39 50](https://cloud.githubusercontent.com/assets/5725767/23467223/b341bdfc-fe5a-11e6-8579-778b2d505c9f.png)

**Comment by dustymc** [comment]
@mkoo @ccicero can we just disable https for arctosdb.org until whatever is going on is properly fixed? It's been over a week now....

@Jegelewicz just use Issues - they work much better than email.

**Comment by dustymc** [comment]
https seems to work now, closing
