### ISSUE TITLE
Arctos acting up?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1051]
Tried Bulk Edit Container just now, and got this message: "HTTP Status 500: No Space Left on Device."  
Any ideas?

![image](https://cloud.githubusercontent.com/assets/14808196/23487150/6902cf6e-fea1-11e6-8228-8e9c6516b56f.png)

[Bulk Edit container error 3-1-17.pdf](https://github.com/ArctosDB/arctos/files/812371/Bulk.Edit.container.error.3-1-17.pdf)

**Comment by Jegelewicz** [comment]
I'm getting the same when I try to upload media or add an agent.

**Comment by campmlc** [comment]
Arctos folks,
Are we migrating to the new webpage? Any reason that we should not be
trying to do any work right now? If so, could we get a heads up when this
is going to happen?

**Comment by mkoo** [comment]
This looks like an Arctos error on the TACC server so is unrelated to the
wordpress site migration...
Dusty? Or should we forward to Chris J (TACC)?
