### ISSUE TITLE
Advice please - Original vs. georeferenced localities

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1053]
I have a large amount of data to migrate into Arctos for which I have the collector's original locality information and then a subsequent georeferenced locality.  What is the best way to get these two bits of information into Arctos and retain all of the information related to the original collecting event?

**Comment by dustymc** [comment]
Load one locality-stack with specimens as usual

Use the specimen-event bulkloader the other(s)

**Comment by Jegelewicz** [comment]
Attempting a test.  Added specimen UTEP:Inv:123 then created georeferenced event which will not load through the Specimen Event Bulkloader.  It appears to load, but tells me I have 0 records in the staging table.
 
I can;t attach a .csv here, so will email.

**Comment by dustymc** [comment]
Closing; reopen if this is still a problem.
