### ISSUE TITLE
Collecting events

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1054]
I just bulkloaded 10 specimen records and although there were three matching collecting events for these 10, I have 10 separate events showing in Arctos.  I cannot see any differences between the events and an attempt to find duplicates and merge them fails with this error:
![image](https://cloud.githubusercontent.com/assets/5725767/23530006/196c162e-ff5d-11e6-8492-b7e7b319b5c9.png)
I don't want to be creating thousands of duplicate collecting events, but for some reason this is happening as I bulkload.  Help!

**Comment by dustymc** [comment]
I need a specimen/locality/something to start with.
