### ISSUE TITLE
Other collection ID Types needed

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1055]
I need the following other collection ID types in order to be able to designate other numbers applied to some of my specimens:

Centennial Museum and Desert Gardens
Los Angeles Zoo
UTEP:Bird
UTEP:Ento
UTEP:ES
UTEP:Fish
UTEP:Herb
UTEP:Herp
UTEP:Inv
UTEP:Mamm

**Comment by dustymc** [comment]
done
