### ISSUE TITLE
age class documentation needed (was: Add attribute type to collection INV)

### ISSUE THREAD

**Issue by ekrimmel** [ArctosDB/arctos#1056]
We have lifestage information in our malacology data that we will be migrating into an Arctos INV collection. I would like to request that attribute type 'age class' be added to the INV collection, with the following values in the ctage_class table: 

- 'larval'
- 'immature' – encompassing juvenile and subadult (e.g., in strombid conchs, nearly adult sized but without final lip development) age classes
- 'adult'
- 'gerontic' – rarely used but fills out the span of ages

**Comment by Jegelewicz** [comment]
Would adding 'juvenile' make sense too?  I have a lot of terrestrial snails labeled 'juvenile' in my data.

**Comment by ekrimmel** [comment]
Perhaps? I'm not a malacologist and so I had asked for advice from some collaborators who are. Their rationale was "if you want to simplify terminology in your collection you can use immature for juvenile, immature and subadult.  If, on the other hand, you want to discern between juvenile and subadult you will have to make an individual assessment of the specimens labeled as immature. In my opinion the latter is definitely not worth it." 

Or else we could add values for 'juvenile' and 'subadult' to capture that specificity when present, but keep 'immature' as a broader term for when the distinction is not specific.

**Comment by Jegelewicz** [comment]
Since you consulted subject-matter experts, I think I can just change all my juveniles to immatures.

**Comment by dustymc** [comment]
>larval

Does "larva" (an existing value) work?

>immature

done

>adult

done

http://arctos.database.museum/info/ctDocumentation.cfm?table=CTAGE_CLASS is in desperate need of documentation. I particularly dislike the "for {some group}, ..." definitions - "term" should mean the same thing everywhere (eg, because cestodes get cataloged in mammal collections), users should not have to guess what arbitrary administrative decisions we've made to accurately search. If cestodes (or whatever) are special, then they need their own vocabulary.

**Comment by ekrimmel** [comment]
@dustymc thank you! And yes, "larva" is fine. Agreed we need more documentation here.

**Comment by Jegelewicz** [comment]
All good for me!

**Comment by ekrimmel** [comment]
Proposed documentation for these CT values:

**larva** – the independent, motile developmental stage of an organism, differing in morphology and ecology from the juvenile or adult stage, and undergoing a metamorphosis to become juvenile/adult

**immature** – the developmental stage in which an organism shares morphology and ecology with the adult stage, but lacks final development and sexual maturity; this term encompasses juvenile and subadult age classes

**adult** – the reproductively capable, fully developed, and usually longest-lived developmental stage of an organism

**gerontic** – the final developmental stage of an organism, post-adult and prior to death; this term is only used occasionally and for specific groups

**Comment by dustymc** [comment]
This is replicated in #1450
