### ISSUE TITLE
Very detailed Ento collections data - looking for collective advice.

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1058]
My ant data includes quite a bit of habitat/nest/climate/BE information:

NestDescription
NestSize
NestStageOfDecomp
NestMiscellaneous
NestManure
NestNotes
NestOther
NestOther2
ActivityDescription
ActivityBehavior
ActivityOther
BehaviorDescription
BehaviorOther
BehaviorOther2
PopulationDescription
DescriptionOther
DescriptionOther2
PopulationGuests (Associated species)
FoodDescription
FoodOther
FoodOther2
AbundanceDescription
AbundanceOther
AbundanceOther2
PositionDescription
PositionOther
PositionOther2
VegetationDescription (Habitat)
VegetationType (Associated species)
VegetationAbundance
VegetationOther
VegetationOther2
ClimateDescription
ClimateSkyOvercast
ClimateRH
ClimateWind
Climate_m_per_sec
ClimateAirTemp
ClimateSurfaceTemp
ClimateTempSiteAir1
ClimateTempSiteAir2
ClimateTempSiteAir3
ClimateTempSiteAir4
ClimateTempSiteSurface1
ClimateTempSiteSurface2
ClimateTempSiteSurface3
ClimateTempSiteSurface4
ClimateTempSiteSurface2_5
ClimateOther1
SoilDescription
SoilTexture
SoilColor
SoilDrainage
SoilMoisture
SoilOrganicContent
SoilOther1

I am curious whether anyone else has dealt with these types of data and how everyone thinks it should be handled.  I can concatenate some of the fields into Habitat, Associated Species, and Collection Event Remarks, but before I go mashing together data that is already in separate fields, I'd like to know if some of these make sense as Ento attributes or perhaps even belong someplace that isn't obvious to a non-entomologist.

All thoughts and comments will be appreciated!

**Comment by dustymc** [comment]
For now, Attributes.

Attributes provide search for "something about SoilOther1 is recorded" and so are inherently more discoverable than remarks, regardless of the values.

Eventually we may add collecting event attributes and some of these may be better stored there - migration should be be fairly straightforward when/if that happens.
