### ISSUE TITLE
Specimen event bulkloader

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1060]
I will be using the specimen event bulkloader quite a bit in the near future as I have several thousand specimens that have been georeferenced and I want to bulkload their original event data, then add the georeference as a new specimen event.

The batch tool for specimen events will help, however it is not at all user friendly.  I would like to see it operate in much the same manner as the specimen bulkloader so that I can easily see and make small tweaks to the data when there are problems (like ft. instead of ft).

**Comment by Jegelewicz** [comment]
Can we use the same datatable solution we are using in the bulkloader?

**Comment by dustymc** [comment]
is now in component loader
