### ISSUE TITLE
Security issues in Firefox

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1061]
What's going on with this?
![image](https://cloud.githubusercontent.com/assets/5725767/23777199/1ed00b1e-04f0-11e7-9874-2fb4d1a0b281.png)

**Comment by dustymc** [comment]
See #1046

**Comment by mkoo** [comment]
I'm currently working on getting a SSL certificate. It's complicated by the
*. museum registration which is legacy for us. But this is a top concern!
