### ISSUE TITLE
Fish question

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1062]
Fish collections.  Does anyone have a problem with changing the class for Cyprinus carpio to Actinopterygii and placing Osteichthyes as the superclass?  This would help me find all of my class Actinopterygii specimens.

**Comment by dustymc** [comment]
Whatever you do, please try to be consistent (eg, get subspecies too). #1000 could help - feedback appreciated.

**Comment by Jegelewicz** [comment]
Dusty,
#1000 is over my technology pay grade, but this is my experience and I would like to know how best to handle the situation.

I bulkloaded my fish data about one year ago.  Recently I was doing some reorganization in the collection and asked Arctos for all of my Actinopterygii.  I discovered that the search results left out Cyprinus carpio, so I checked the Arctos taxonomy.  For this particular species, the class was listed as Osteichthyes, however, my limited understanding of fish taxonomy tells me that this is now the "superclass" and Actinopterygii is the class level for this species.  I made the change to Arctos taxonomy, but the only way to change the tree for my specimens was to individually edit each one, essentially re-identifying them exactly as before.  This wasn't a big deal for three lots of fish, but I can see how it would become a big deal if there were hundreds or thousands of specimens affected.

I know that there are many scientific names in Arctos taxonomy with incomplete or non-existent trees.  When these get updated, how will I know that MY specimens need re-identification?  Or have I totally missed something in this process?

Thanks!

**Comment by dustymc** [comment]
Basically #1000 would make consistency easy and let you avoid the ugly realities of taxonomy while managing limited-scope data. (Hierarchies can't deal with eg http://arctos.database.museum/name/Echidna where the term has a half-dozen "parents," and Arctos can't avoid that sort of data.) 

Changes to classifications should automagically find their way to specimens, but it can take a while (usually 24h).
