### ISSUE TITLE
Creating a borrow

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1063]
When creating a borrow, I would like to be able to attach a copy of the loan agreement.  When I try, I am unable to create the media because there is not drop down available for the media relationship.  Also, this would not be a public document, can we keep such documents private and avoid the need for a license?
![screenshot 2017-03-14 14 25 32](https://cloud.githubusercontent.com/assets/5725767/23921380/131c8f40-08c4-11e7-87e1-04f80fdd0624.png)

**Comment by dustymc** [comment]
>media relationship

I'll add that

>documents private

TACC will only provide hosting for public information, and so Arctos cannot provide document security. You could host the document under whatever security you need and still create Media. Borrows aren't public or visible so attached Media PROBABLY won't be very easy to find, if that's enough "security."

**Comment by Jegelewicz** [comment]
Got it.
