### ISSUE TITLE
Bill length

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1065]
Is there a specific reason that bill length doesn't include measurement units?
![screenshot 2017-03-16 08 37 22](https://cloud.githubusercontent.com/assets/5725767/24001781/adb9ca70-0a24-11e7-8c8b-2ff0b7fb1cd2.png)

**Comment by dustymc** [comment]
Someone made it that way. Anything in http://arctos.database.museum/info/ctDocumentation.cfm?table=CTATTRIBUTE_TYPE and not in http://arctos.database.museum/info/ctDocumentation.cfm?table=CTATTRIBUTE_CODE_TABLES is free-text.

There's only one non-numeric value (UTEP:Bird:3038) so it could be changed - if someone wants to guess at units for all the bare integers.

**Comment by ccicero** [comment]
Bill length, width, and depth should all have units. Width and depth have units, length does not.

Dusty, can you please send a text file with those values and we can take a look?

**Comment by ccicero** [comment]
I just removed the 'mm' from the UTEP Bird 3038 record. Let's assume that all of the units are 'mm' and add those units to the data and code table. 

If most of the values are CUMV, we will be losing them when they pull their data. That will help to make the data cleaner.

**Comment by dustymc** [comment]
done
