### ISSUE TITLE
do we really need portals? (was: Search issue)

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1067]
When not logged in to Arctos, if I select a portal (UTEP:Mamm) to search from, I cannot get back to searching all of Arctos.  I am stuck searching only this portal.

**Comment by campmlc** [comment]
Yes, that is a problem. We do need to add the following link to each of the
individual portals page. Currently, the only solution is to go back to
portals and click on this link:

*You may click [ search all collections ]
<http://arctos.database.museum/all_all> at any time to re-set your
preferences.*

**Comment by campmlc** [comment]
On a similar subject, we need to add a link from arctosdatabase.museum back
to arctosdb.org.

**Comment by dustymc** [comment]
I agree that portals can be confusing, but I need explicit instructions for what you want to see or how you want the forms to behave (keeping in mind that there are a LOT of ways to end up in a portal looking at specimens).

"Portals" are just DB users with specific (eg, "read public stuff") access to specific collections. When you're logged in as an Operator you're in your own personal "portal," and it would be cool to somehow clarify that as well.

@campmlc  I'm not sure what you mean by "individual portals page."

@ccicero  @mkoo The "About/Help" header tab links to arctosdb, but from there it's not very obvious where to find the "help." Can we add a more prominent link to the handbook somewhere - maybe in the green header-bar-thingee?

**Comment by campmlc** [comment]
By "individual portals page" I mean the search page that you get directed
to if you click on "Search xxxx specimens" for each collection on the main
Portals page in arctos.database.museum.  If you are looking at different
collections and you click on a link to a specific collection, there is no
obvious way to get to the * [ search all collections ]
<http://arctos.database.museum/all_all> *link. This creates a functional
dead end. Users may not even realize they are only searching one collection
at that point.

**Comment by dustymc** [comment]
>Users may not even realize they are only searching one collection at that point.

I think that may have been a request - maybe even what lead to the creation of the portals in the first place - but I can't find details hiding in my inbox or old Issues.

If that is no longer desired functionality, we could ditch the portals altogether and /some_portal could just redirect to the search page and pre-select the some:portal collection(s) in the "Collection" select widget. That would also allow users to build their own "portals" from the refine results widget.

That would also fix eg #630 and some other portal-related Issues/points of confusion.

**Comment by campmlc** [comment]
That sounds good to me.

**Comment by ekrimmel** [comment]
I like @dustymc solution of redirecting to pre-selected collections from a portal URL.

**Comment by ccicero** [comment]
Sorry, I'm looking for a different issue and came across this one. We DO need the portals page because I link to it from various places on the website to show our holdings. I also use it for calculating user costs for invoicing. But I agree that there are some functionality issues.

**Comment by dustymc** [comment]
@ccicero  I'm not sure either of those two things require portals. http..arctos..../some_portal would just select the collection "some:portal" (which users could un-select instead of trying to find the /all_all escape route). The portals page (http://arctos.database.museum/home.cfm) doesn't rely on "portal users" and could keep existing. The existing behind-the-scenes code could let /mvz_all select MVZ:Bird + MVZ:Mamm + .... 

I think the only thing you would lose is the ability to lock "your" users to "your" data - a user pointed at MVZ:Bird would be more likely to find other collections (eg, by returning to the now-fully-open search page after doing something else, or by un-selecting "your" collection from the pick list).

**Comment by ccicero** [comment]
@dustymc I'm not sure that I understand the options on what you're suggesting, but as long as there is one place to link to all of Arctos holdings (for the website), and one place to go find total counts by institution (for invoicing), then I'm probably ok with it. Let's discuss at the next AWG meeting.
