### ISSUE TITLE
flickr as an upload service?

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1071]
Can/should we...

upload media to flickr
grab a copy via API for TACC's servers
create a new media record + a 'derived from media' relationship

??

**Comment by ekrimmel** [comment]
I say no, just because TACC is a good option, so why do we need another..?

**Comment by campmlc** [comment]
What about researchers in the field loading photos to Flicker that could be
grabbed later for Arctos? I'm not a Flicker user, but it seems that it
might be good to have different ways of loading media, some more user
friendly than others.

**Comment by ekrimmel** [comment]
Good point @campmlc, I wasn't thinking as broadly! I guess I'd still contend that using Flickr would at best enable inefficient work habits, e.g. if you are capturing photos in the field, shouldn't you also be capturing data? And if you are capturing data shouldn't you be doing it digitally and shouldn't you be using fields that will map directly into Arctos? In the past I've used iNaturalist to record images and data in the field, then exported my observations and pulled them directly into Symbiota to create herbarium records linked to the original photos of the living plant. It'd be cool if future Arctos could make that process, or something similar, more automatic.

You're right though, maybe Flickr can still provide a different, more user-friendly option even if it's not the unicorn of perfect efficiency... :)

**Comment by dustymc** [comment]
Closing - we have access to an S3 API now, this isn't necessary.
