### ISSUE TITLE
scheduled tasks not running correctly

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1072]
check them all

**Comment by dustymc** [comment]
Scheduled tasks is now running. We need a way to monitor when it's not - sent email, leaving this open.

**Comment by dustymc** [comment]
Test and prod are now monitoring each other.

Leaving this open for now - need to finalize email settings, confirm automation is working.

This would still be better with an off-site component.

**Comment by dustymc** [comment]
Finalized for next release; closing.

**Comment by dustymc** [comment]
Nobody is watching the alerts.

Send fewer of them?

Send them to different people?

Make contacts more prominent on arctosdb.org?

@campmlc @ccicero

**Comment by Jegelewicz** [comment]
I agree with Mariel's idea of setting up a "call tree". Alerts go to Dusty/Lam and when they know they won't be available, then to ....not sure who, but whoever that is, they probably need instructions for how to handle the situation.

**Comment by campmlc** [comment]
I suggest that the Arctos WG Chair receive the alerts in the event
Dusty/Lam are not available, and our response should be to communicate with
TAAC and also with the Arctos community to let everyone know there may be
an outage.

**Comment by dustymc** [comment]
I don't know how to make "when they know they won't be available" actionable - I don't trust myself to feed the snakes, lock the doors, change some Arctos code....I'll forget. (Just ask the snakes!)

I will add a link to https://arctosdb.org/arctos-down/ - I think that's the best place to develop/maintain a "call tree." (And it's much more visible now - yay!)

Example alert email below. Please let me know what's missing in the instructions. Perhaps it's just ordering?? Only a few of us probably know what to do with scheduled tasks, but anyone should be able to confirm that Arctos and test are up and responsive or check a gmail account.

I'll also bump the alert schedule up to 4 hours, which is 4 missed checkins. That will not be so good at catching pending problems, but I think it will still be effective for the things that need dealt with immediately.


```

An Arctos monitoring script has detected a problem.

A check-in email was not received from test.
Check the following items:

Check that both arctos.database.museum and arctos-test.tacc.utexas.edu are responsive.

Check that email is being sent from both. The mailserver is very susceptible to disk space issues.

Check that scheduled tasks are running (these alerts come from im_not_dead_yet which should run twice hourly on test and prod). The CF scheduler sometimes spitefully destroys it's own config files (neo-cron.xml), particularly after a crash or near-crash. Patch a bare one in, restart CF, rebuild scheduled tasks.

Check that arctos.is.not.dead@gmail.com is properly receiving email and allowing IMAP connections to Arctos and Arctos Test. The password is available under Global Settings.

Check that the password to arctos.is.not.dead@gmail.com works and matches at test and prod.

If you are logged in to https://arctos.database.museum with manage_collection permissions and you are SURE that the right people are aware of this issue, you may pause the monitoring scripts for 12 hours by visiting https://arctos.database.museum/Admin/pause_monitor.cfm. 

```

**Comment by campmlc** [comment]
That looks good. So we can pause the scripts if we know the issue is being
dealt with?
Also, if 4 hours is too long,can you keep more frequent alerts going to you
but the longer interval going to AWG?

**Comment by dustymc** [comment]
>So we can pause the scripts if we know the issue is being dealt with?

Yes, that's been there for quite a while.

>keep more frequent alerts going to you but the longer interval going to AWG

That is my intention if it proves practical.

**Comment by dustymc** [comment]
Moved to 4 hours, clarified instructions, added link to contacts.

I have no stake in this, and am only trying to act on behalf of those who do. 

If various parts of Arctos are not functioning, alerts regarding permits and loans and changed localities and agent mergers and etc. may not be sent. Those seem like critical infrastructure to me. (The alert also acts as an early-warning system, but downtime is more towards the "annoying" end of the problem spectrum.)

I would never trust any critical system with a single point of failure (eg, chair of AWG). Most of "us" are out of contact at various times, which compounds that.

I can turn this thing off if it isn't useful.

I can adjust the email list.

I can move the email list (currently hard-coded) to the manage/global page so ya'll can adjust it.

I could potentially add complexity (eg, escalate over time), but at that point we're probably better off paying for a commercial service.

How should I proceed?

**Comment by campmlc** [comment]
Let's see how it goes with 4 hour notification.

**Comment by mkoo** [comment]
I agree with Mariel to go with 4 hours. Might be best to move the email
list to the global management tool so people can add emails as appropriate.
If these alerts are fine tuned to avoid the false alerts then they will be
paid attention to!

Also who's got access to arctos.is.not.dead@gmail.com?

**Comment by dustymc** [comment]
> false alerts

If you see an alert, SOMETHING is not being very responsive. Those include dying and will self-recover, dying and won't self-recover, and already dead. The "paranoid" setting lets us stop some of the things that would eventually lead to outages of some sort. The 4-hour setting will very likely only find "dead," (eg, not sending mail) which is what this was originally intended to detect anyway.

>move the email list to the global management tool

Good idea - will do.

>access to arctos.is.not.dead

See the global settings page.

**Comment by dustymc** [comment]
Made adjustments, closing.
