### ISSUE TITLE
Data entry

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1073]
While entering records into our ES collection, Art Harris came up with a dialogue box that says "iframe url does not have permission to interact with you", just after selecting the nature of ID.  We can select OK about three times and then move on to the next field, but I don't think we should have to do that.

Suggestions?

**Comment by dustymc** [comment]
Nature of ID is a static HTML element with no associated events. 

My first guess is that he has something running from his browser or OS (plugin, extension, or malicious code) that is trying to create an iframe for some unimaginable reason. Is there anything in the javascript console? https://developer.mozilla.org/en-US/docs/Tools/Browser_Console

**Comment by dustymc** [comment]
Closing; please reopen and provide screenshots +javascript console dump if this is still an issue.
