### ISSUE TITLE
mentor

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1074]
create report to use collection contact role 'mentor'

**Comment by dustymc** [comment]
See http://arctos-test.tacc.utexas.edu/info/mentor.cfm, linked under My Stuff tab - will push to prod once OKed.

**Comment by ccicero** [comment]
Can we remove the institutution acronym after the institution name - it repeats what's in the GUID prefix. So it would look like 
Museum of Vertebrate Zoology Bird observations (MVZObs:Bird)

Collection description may be long - Add collection web link instead?

**Comment by ccicero** [comment]
Another thought - add a column for collection_cde and sort by code, then agent name. That way, all 'Bird' collections sort together, etc.

**Comment by ccicero** [comment]
I would move 'Find a Mentor' to under 'About/Help'

Also under 'My Stuff' - API is really old and seems out of place - Better under About/Help, and needs to be updated (e.g., remove reference to 'DiGIR')

**Comment by dustymc** [comment]
>remove the institutution acronym after the institution name 

Not easily - it runs....

<img width="576" alt="screen shot 2017-03-30 at 10 46 28 pm" src="https://cloud.githubusercontent.com/assets/5720791/24537909/bb96e99e-159a-11e7-8bfd-e03e02737206.png">

... that thing. Here's what I have to work with:

UAM@ARCTOS> select * from collection where guid_prefix='MVZ:Bird';

COLLECTION_CDE	INSTITUTION_ACRONYM
--------------- ------------------------------------------------------------
DESCR
------------------------------------------------------------------------------------------------------------------------
COLLECTION
------------------------------------------------------------------------------------------------------------------------
COLLECTION_ID
-------------
WEB_LINK
------------------------------------------------------------------------------------------------------------------------
WEB_LINK_TEXT
------------------------------------------------------------------------------------------------------------------------
GENBANK_PRID GENBANK_USERNAME
------------ ------------------------------------------------------------
GENBANK_PWD
------------------------------------------------------------
LOAN_POLICY_URL
------------------------------------------------------------------------------------------------------------------------
INSTITUTION
------------------------------------------------------------------------------------------------------------------------
GUID_PREFIX						     USE_LICENSE_ID
------------------------------------------------------------ --------------
CITATION
------------------------------------------------------------------------------------------------------------------------
PREFERRED_TAXONOMY_SOURCE
------------------------------------------------------------------------------------------------------------------------
CATALOG_NUMBER_FORMAT
---------------------------------------------------------------
Bird		MVZ
The MVZ bird collection is one of the largest in the United States. It houses over 185,000 catalogued specimens, includi
ng 174 holotype and 2 syntypes. The majority of specimens are study skins, but the collection also contains over 21,000
skeletal specimens and 3,200 fluid-preserved specimens. Other types of preparations include flat specimens (wings, skins
) and body skins with skeletons ("schmoos"). Tissues, anatomical parts (e.g., syrinx, stomach contents), and parasites a
re routinely preserved with specimens. Many specimens also are associated with cataloged audio recordings.
Bird specimens
	   29
http://mvz.berkeley.edu/Bird_Collection.html
MVZ Bird Collection
	3849 uam
bU7$f%Nu
http://mvz.berkeley.edu/Access_Loans.html
Museum of Vertebrate Zoology (MVZ)
MVZ:Bird								  1
Museum of Vertebrate Zoology (MVZ), University of California, Berkeley
Arctos
integer


1 row selected.

>Collection description may be long - Add collection web link instead?

done

>add a column for collection_cde

i'm a LITTLE hesitant to do that given the disconnect between collection_cde (="code table data") and guid_prefix and the nature of a collection (eg, "Inv"="random stuff" or "marine inverts" or ....). But I can if you think it's a good idea.

>sort by code, then agent name

done

>move 'Find a Mentor' to under 'About/Help'

done, and I split up "about" and "help" - the handbook is not easy to find from https://arctosdb.org/

> API 

done and #1077

**Comment by ccicero** [comment]
Is "More Information" supposed to be the Web Link? If so, change column heading to be more specific. I added a weblink for MVZObs:Bird and it's not showing after reload - maybe cache issue?

API - still showing the line about DiGIR portal. Also, why not move API to under 'Search' since that's really what it's about - seems out of place under About/Help. 

I think for this purpose, it's fine to have collection_cde in a separate column. The idea is to see who all are the folks who deal with birds and may be able to answer bird-specific questions. So I would have columns labeled:
Name
Email
Collection Type [from collection_cde]
Collection Name [without the GUID prefix, e.g., Museum of Vertebrate Zoology (MVZ) Bird observations
Web Link

I reorganized the footers in arctosdb.org so all of the linkouts incl handbook are on the left side, moved FAQ to the right side. Hopefully that will make the handbook easier to see.

**Comment by ccicero** [comment]
While you're redoing the headers, see issue that I just submitted re: reports:

https://github.com/ArctosDB/arctos/issues/1078

**Comment by dustymc** [comment]
> column heading
>collection_cde

<img width="1159" alt="screen shot 2017-03-31 at 9 33 24 am" src="https://cloud.githubusercontent.com/assets/5720791/24559859/1c2c82d2-15f5-11e7-8340-daa2b0801a12.png">

>cache

Yes, it caches.

>API

I just filed the Issue - #1077 

>not move API to under 'Search' 

"Search" is "get data now" API is "HOW to get data, later, if you can write code" - MAYBE those are the same thing but seems sorta different to me????

>reorganized the footers 

It would never occur to me that after clicking a link labeled "help" I'd have to scroll to a footer to find help! I think I like the two links. Maybe having the bounce to help in the header would work. It might need to be explicitly labeled - not sure "handbook" and "help" are synonyms to most people.

>issue that I just submitted

Thanks!

**Comment by ccicero** [comment]
Better, but move Collection Type column before Collection column.

API comments - will continue this on new issue

**Comment by ccicero** [comment]
I agree that the Help in arctos.database.museum should link out directly to the Handbook. But you mentioned that the handbook was hard to find if you are just on the website. I like having all the linkouts in the footer on one side.

**Comment by dustymc** [comment]
>move Collection Type column before Collection column.

done

>handbook was hard to find

Only if you've just clicked a link labeled "help," in which case I would expect immediate help. If you've clicked a link labeled "about" or are just browsing the website, the links in the footer are good.

**Comment by ccicero** [comment]
Right. Thanks!

**Comment by ccicero** [comment]
One other change:

Under About/Help, order should be:
About
Help

NOT
Help
About

**Comment by dustymc** [comment]
>order

done

**Comment by dustymc** [comment]
This is in prod and seems to be functional, closing. Please reopen if there are additional comments.
