### ISSUE TITLE
checkHelpLinks

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1075]
Tools in /doc/checkhelplinks should be automated to maintain links

**Comment by dustymc** [comment]
Downgrading this to low; it doesn't work great against the autogenerated site, and I'm not sure who would fix.

These are potentially broken:

https://handbook.arctosdb.org/documentation/taxonomy.html#local-sources
 https://handbook.arctosdb.org/documentation/permits.html#issued-by
https://handbook.arctosdb.org/documentation/faq.html#session
https://handbook.arctosdb.org/documentation/taxonomy.html#editing
https://handbook.arctosdb.org/documentation/coordinates.html#maximum-uncertainty-distance
https://handbook.arctosdb.org/documentation/specimen-event.html#verification-by-agent
https://handbook.arctosdb.org/documentation/agent.html#relationships
https://handbook.arctosdb.org/documentation/encumbrance.html#encumbrancer
https://handbook.arctosdb.org/documentation/permits.html#issued-to
https://handbook.arctosdb.org/documentation/address.html#maintenance
https://handbook.arctosdb.org/documentation/coordinates.html#coordinates-1
https://handbook.arctosdb.org/documentation/taxonomy.html#ranked-terms

**Comment by Jegelewicz** [comment]
@dustymc is this still a thing? I am going to make an effort to add as many of these as possible:

![image](https://user-images.githubusercontent.com/5725767/135313540-d595edf1-6f97-4ec5-a9c6-0c4ba02012f7.png)

BUT I added a link for the taxonomy search page ages ago, yet it still says there isn't one...

![image](https://user-images.githubusercontent.com/5725767/135313679-46144e93-7b50-4e09-91a7-8c20071df469.png)

What gives?

**Comment by dustymc** [comment]
>this still a thing? 

Yes, but it's not page help.

>What gives?
<img width="575" alt="Screen Shot 2021-09-29 at 10 02 28 AM" src="https://user-images.githubusercontent.com/5720791/135315536-76abd9d0-46f5-45a1-8069-fbc8c21d77a2.png">

**Comment by Jegelewicz** [comment]
How can I help here?

**Comment by dustymc** [comment]
For helplinks:

<img width="234" alt="Screen Shot 2021-09-29 at 11 31 53 AM" src="https://user-images.githubusercontent.com/5720791/135328108-5f65c70f-15b1-469e-9b6b-d5040cabaaf0.png">
<img width="310" alt="Screen Shot 2021-09-29 at 11 32 16 AM" src="https://user-images.githubusercontent.com/5720791/135328116-8609a5cd-8bbf-48b4-8516-6a08702df7b5.png">

then figure out what it should be and change the link, or change the docs so the links work.

For page help: link to a https://handbook.... url

**Comment by dustymc** [comment]
tools are available, nobody reads reports, closing
