### ISSUE TITLE
API (link in header) needs updated

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1077]
so update it

**Comment by ccicero** [comment]
"Search" is "get data now" API is "HOW to get data, later, if you can write code" - MAYBE those are the same thing but seems sorta different to me????

They are not exactly the same, true. What about under Developer Widgets? Maybe rename that to Developer Tools? And those could be better organized/explained. I have no idea what most of those are.

It's not clear to me what you're supposed to do with those APIs. For example, /api/taxsrch gives you:

![image](https://cloud.githubusercontent.com/assets/967275/24560431/a4474844-15f7-11e7-9da4-ce2137b169fd.png)

Then what?

**Comment by dustymc** [comment]
I moved API to search - that makes sense now, for some reason....

Digir-->http://ipt.vertnet.org

Added a contact link at the top.

Added some (maybe still cryptic!) docs to taxonomy.

>Developer Tools

Renamed. I think I'd prefer to keep public pages under a few tabs, not expose more esp. for limited-use apps (but whatever).

>better organized

Probably? I'm open to suggestions.

> explained

See @ekrimmel's most excellent sitemap (http://handbook.arctosdb.org/documentation/useful_documents.html), which should somehow be more visible and maybe better integrated. (Added comment to https://github.com/ArctosDB/documentation-wiki/issues/38 - we can maybe at least expose users to the map via that - everyone should know it's possible to do that stuff, even if they don't have access.)

>what you're supposed to do with those APIs

You're supposed to use the contact link to tell us what you WANT to do! They're mostly very under-developed, and I make basically no effort to maintain them - I build/use APIs for internal stuff (because it makes my life easier), when someone asks I can usually give them what they want (and do try to maintain that, when it happens). We've had surprisingly little interest in API access - I don't think there's much point in using an API when Arctos is still the only source of comparable data, and people who just want summary data get it (including Arctos) from GBIF-etc. I know of ONE (failed, I think) experiment which used the specimens-as-rdf api, and one (ongoing) which uses specimenresults as JSON. I'm happy to do whatever, I just need some guidance (hopefully from someone's who's actively trying to use data).

Closing for now; please re-open/comment if I missed anything/you have clever ideas/etc.
