### ISSUE TITLE
Organize Reports

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#1078]
At the March 2016 Working Group meeting, there was consensus that we need better organization of reports. The suggestion was made to group reports into three categories:

-- About Arctos
-- Statistics
-- Services

**Comment by dustymc** [comment]
I don't understand the suggested categories, but here's a first-go attempt at what's currently in the Reports tab. Please reorganize/re-label/re-whatever! Please leave the original text (eg, as "was: original") as a map to current code.

* Reports
  * Create or Print Labels and Reports (was: Reporter)
  * Write SQL
  * Statistics
    * Loan/Citation Stats
    * More Citation Stats
    * Usage Stats
    * Download Stats
    * Query Stats
    * Locality Statistics
    * System Statistics
    *  IPT/collection metadata report
    *  Data Entry Stats
    * Georeference Statistics
  * Find low-quality data (was: Funky Data)
    * Publication/Loan/Project/Citation Problems (was: Suspect Data)
    * GenBank Discovery tool (was: GenBank MIA)
    * Undocumented Citations
    * Partless Specimens
    * Catalog Number Gaps
    * Duplicate Agents
    * Part Usage
    * Disposition vs. Remark

  * I have no idea what to call this (new category)
    * Annotations
    * Exit Links
  * Administrative Tools (new category)
    * Audit SQL
    * Oracle Roles
    * Error Logs
  * Data Services
    * Find GUID from Barcode
    * Find higher_geog from specloc
    * Taxon Name Checker
    * Higher Geog Lookup
    * Date Formatter
    * Coordinate Formatter
    * Agent Deconcatenator
    * Agent Namestring Formatter
    * Find and replace nonprinting characters
    * Convert KML to WKT

**Comment by ekrimmel** [comment]
I like this! @dustymc your new categories make sense to me. Could *Exit Links* go under *Statistics* and *Annotations* be it's own thing? My proposed major headings would be:

1. Create/Print Labels and Reports ~Create or Print Labels and Reports~ (was: Reporter)
1. Write SQL
1. View statistics (was: Statistics)
1. Review annotations (new category)
1. Find low-quality data (was: Funky Data)
1. Clean up raw data (was: Data Services)
1. Administrative Tools (new category)

Not sure if *Clean up raw data* is the best phrasing, but I think we should have a header that more accurately reflects what actions a user can expect to accomplish in this section. *Data services* could mean the API or the funky data or lots of other stuff. Actually this whole *Reporter* section could be *Data services.*

**Comment by dustymc** [comment]
Edited. 

I didn't change "Clean up raw data (was: Data Services)" - there are a few things in there (and a lot of ways to categorize them!), not sure if they need somehow separated or not:

- do stuff to text - strip nonprinting characters, look for agent-like strings and add some structure
- transform data - barcode in, GUID out
- do stuff using data - geography-strings in, geography data objects out

I guess I'd be happy with all except the barcode-->GUID thing under "Clean up raw data."

And yea, at some level Arctos is nothing but a big pile of data services....

**Comment by ccicero** [comment]
Revisiting this issue so we can finish it. Sorry, I missed the discussion in April.

I like the idea of calling the tab at the top 'Data Services' instead of Reports. 

What about calling the category 'Data Tools' (was Funky Data) ? Looks to me like what's listed under 'Find low quality data' and 'Data Services' could be mostly combined?

Can we also be more explicit in what the tools do, e.g.,
Find Publication/Loan/Project/Citation Problems (was: Suspect Data)
Find Missing GenBank Relationships (was: GenBank MIA)
etc.

Data Usage doesn't seem to belong there - looks more like stats?

Also, can we be consistent and use 'Statistics' instead of 'Stats' throughout? and consistency in upper vs lower or mixed case.

**Comment by dustymc** [comment]
> top 'Data Services' instead of Reports.

I'm still not crazy about that. There are a few things here:

- reports (eg, print labels)
- "reports" which find potentially-problematic data
- services which do data-stuff (take barcode, return GUID)
- services which do string-stuff (find non-printing characters)

Maybe we need two tabs? Or "Reports and Data Services"? Or ????

I made the easy (I hope!) changes at TEST.

<img width="237" alt="screen shot 2017-12-15 at 12 50 00 pm" src="https://user-images.githubusercontent.com/5720791/34059998-a40e8d68-e196-11e7-983b-ae17b190488b.png">

<img width="384" alt="screen shot 2017-12-15 at 12 50 07 pm" src="https://user-images.githubusercontent.com/5720791/34060001-a8633288-e196-11e7-98b2-6e5be2646523.png">

<img width="428" alt="screen shot 2017-12-15 at 12 50 14 pm" src="https://user-images.githubusercontent.com/5720791/34060004-ae6987f4-e196-11e7-887d-e06d47ee1b8b.png">


<img width="305" alt="screen shot 2017-12-15 at 12 50 19 pm" src="https://user-images.githubusercontent.com/5720791/34060012-b83a8c1a-e196-11e7-8b02-7876eca3ecf2.png">

<img width="389" alt="screen shot 2017-12-15 at 12 50 26 pm" src="https://user-images.githubusercontent.com/5720791/34060019-bd0a9690-e196-11e7-851c-964e05ecd85a.png">

**Comment by ccicero** [comment]
Definitely much cleaner. 

What about "Reports/Services" as the tab header?

Do we need "Create/Print Labels and Reports" ? If you create it, presumably you will also want to print it? Can we just say "Create Labels and Reports" ?

Order alphabetically (and same for the different sub-lists):
Administrative Tools
Create Labels and Reports
Data Services
Find Low-Quality Data (mixed case to match others()
Review Annotations
View Statistics (fix mis-spelling, currently 'View Stastics')
Write SQL

Still need some consistency in case, otherwise looks good with these changes.

**Comment by dustymc** [comment]
>What about "Reports/Services" as the tab header?

done

>Do we need "Create/Print Labels and Reports" ? If you create it, presumably you will also want to print it? Can we just say "Create Labels and Reports" ?

Someone else may have created, but point taken. It's "Labels and Reports" for now, easy to change if you don't like that.

>Order alphabetically (and same for the different sub-lists):

done, I think. I may need remedial Sesame Street....

>consistency in case

Done, I hope. 

Closing - please re-open if I missed anything.
