### ISSUE TITLE
search by Geographic Feature not working

### ISSUE THREAD

**Issue by AdrienneRaniszewski** [ArctosDB/arctos#1080]
searching by Geographic Feature, such as Arches National Park (or any other feature), returns 0 results. even though there should be results.

**Comment by dustymc** [comment]
update attribute "feature" to "archaeological feature"
push attributes to docs
rebuild code, deploy

**Comment by dustymc** [comment]
Updates done, docs and code rebuilt - this should work with next release, confirm and close
