### ISSUE TITLE
More features

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1081]
Can we please add the following features?

Big Bend National Park 
Santa Ana National Wildlife Refuge https://en.wikipedia.org/wiki/Santa_Ana_National_Wildlife_Refuge

Thanks!

**Comment by dustymc** [comment]
>Big Bend National Park

exists at http://arctos.database.museum/info/ctDocumentation.cfm?table=CTFEATURE

>Santa Ana National Wildlife Refuge

added
