### ISSUE TITLE
two geographic features to add

### ISSUE THREAD

**Issue by AdrienneRaniszewski** [ArctosDB/arctos#1085]
we need these two geographic features added. thank you!

Big Bend National Park
https://en.wikipedia.org/wiki/Big_Bend_National_Park

Pinnacles National Park
https://en.wikipedia.org/wiki/Pinnacles_National_Park

**Comment by mkoo** [comment]
I can do these for you, Adrienne.
This brings up an old wish-list item; batch uploading all the NPS holdings.
Is it annoying for us to add in HG without anything attached yet?

**Comment by campmlc** [comment]
Any chance we can batch upload WKT polygons for the national parks as well?

**Comment by dustymc** [comment]
>batch uploading

To Feature/code tables: no problem.

Geography: possible, but it would be some work - some of the checks are application-level, they'd need ported to whatever handles the batch load. If you're thinking of geography, are you wanting a tool you can use whenever or a one-time big batch (which could go through a less user-friendly tool) or ??

Un-used geography is no problem.

Get me WKT data (or something I can make into WKT data) with corresponding higher geog and I'll figure that out - there are no checks on the WKT so it should be fairly straightforward.

**Comment by mkoo** [comment]
Batchloading for NPS would be a one-time thing (I dont see a ton of new NP
in the next 4 years!) Let me put on my to-do list for next week.

And I would be interested in seeing about having the WKTs done at the same
time. So if I send a bunch of KMLs or a link to a Fusion tables of NPS,
that would not be too painful for you Dusty?

Also, the two requested parks are in.

**Comment by dustymc** [comment]
>KMLs or a link to a Fusion

I have scripts that have WKT-ed those things in the past. I do not have any spatial tools - I just run a bunch of regex-replace type stuff and hope to see a map when I'm done. If you have spatial tools, PLEASE use them and send me WKT!

**Comment by mkoo** [comment]
Dusty, I want to help but am a little unclear on the workflow here.
Just send you a bunch of WKTs? Can I post to a central spot and then you
can grab them there for your ingest? Does it make sense to have them in a
github repo so you can grab when new stuff shows up there?

What's this Create Media option? what are the parameters then for a WKT as
media? What do you prefer?

I'm also trying to figure out how we can make this part of our
georeferencing workflow - wouldnt be hard to add wkt for higher geogs that
do not exist in the future!

happy to discuss options that we can document too

**Comment by dustymc** [comment]
There is no workflow!

Something in the software stack (CF?) has limitations on handling LOB data (40K characters or something weird) and some complex WKT shapes plug up the pipes, so Arctos can handle two things in higher_geog.WKT:

1. WKT data
2. "MEDIA::{media_id}"

where  http://arctos..../{media_id}?open is WKT.

Handling LOBs (very large text files) is generally a pain, but I can create media and get the ID easily, and if geog_auth_rec_id in embedded in a filename I can get all I need from that (and set up automation if this becomes a normal thing).

So, can you just upload the WKT to http://corral..../someFolder/WKT/wkt_{geog_auth_rec_id}.wtk? I don't really care where "someFolder" is, but it will need to be accessible to anyone who wants to upload data. I don't really care about the filename format either, as long as it's consistent and geog_auth_rec_id is SOMEWHERE in the URL.

**Comment by dustymc** [comment]
Closing, see also #1201
