### ISSUE TITLE
backing up Arctos data locally

### ISSUE THREAD

**Issue by ekrimmel** [ArctosDB/arctos#1087]
Question--do other collections back up their Arctos data locally? I know we are collaboratively backed up on TACC. We recently had a down server and data loss scare, and so are trying to make sure we have more redundancy in our systems...

**Comment by dustymc** [comment]
I don't think anyone outside of TACC is hosting any backups at the moment. If you can provide some disk space and a decent connection to it we would be thrilled to push a copy of the backups out.

**Comment by campmlc** [comment]
MSB would be interested in hosting a backup of our collections as well.
Mariel

**Comment by dustymc** [comment]
Yay! We should just need access - scp is probably easiest, but other stuff could work.

**Comment by ekrimmel** [comment]
That'd be great--we are currently revamping our server setup so I'll add this to our IT wishlist!

**Comment by ekrimmel** [comment]
@dustymc Do you have a sense of how big the backup would be?

**Comment by dustymc** [comment]
The backups are currently about 100G, much/most of which is probably stuff we don't really need - please comment on #728. We could manually copy stuff over now, but there is understandable resistance to automating giant recurring transfers. If we can trim down the DB size we can revisit automating a backup export. Weekly might be make the most sense - I think that's what's being sent off-site now.

**Comment by Jegelewicz** [comment]
Adding this to AWG agenda as it seems relevant given Naturalis discussions.

**Comment by mkoo** [comment]
main issue is now in internal repo
