### ISSUE TITLE
media attached to a locality is showing up on all records using that locality.

### ISSUE THREAD

**Issue by amgunderson** [ArctosDB/arctos#1090]
An image of Grinnell in Fort Yukon, AK (http://arctos.database.museum/media/10498076) is linked to this locality, http://arctos.database.museum/editLocality.cfm?locality_id=1080, via the collecting event associated with that image. Consequently that image is showing up on the specimen record page for all 318 specimens that use that locality, UAM mammals, UAM ethnology, and MSB parasites are displaying a nice image of Grinnell from 1942 but they have nothing to do with that image. Media linked to a locality (via the collecting event) should not be showing up on all those records that use that locality.

**Comment by dustymc** [comment]
See #860, #876, #869, http://handbook.arctosdb.org/how_to/How-to-understand-locality-media.html for the history of this behavior.

**Comment by amgunderson** [comment]
OK but I say this should just not be the case, the image is linked to the event and be limited to showing up on the specimens that use that event and not be broadcast to the locality also. Wasn't issue 873 supposed to fix that?

**Comment by dustymc** [comment]
#873 only addresses the target of a href-link.

#860 explicitly asks for the broadcast.

The form behavior is easy enough to change, but this looks like something the AWG needs to address - and please include @DerekSikes who originally requested this in any discussions.

FWIW I really like the current broadcast (and the term "broadcast"!) - there's "data" in even the Grinnell picture, pixel-ey and barely-related though it may be - looks like birch trees in the background - are they still there? - different species composition as they've grown/regrown/burned/etc? Is that really robin (http://arctos.database.museum/guid/MSB:Host:13259) habitat, or does that specimen's locality need revisited? Etc. etc. etc.
