### ISSUE TITLE
unformatted measurements and explanation

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1092]
We have a lot of fossil teeth that have measurements that aren't defined.  We entered them all as unformatted measurements, but we can use use a graphic to explain the way the measurements were made.  Dr. Harris made an attempt at this with specimen UTEP:ES:4-2.

I like how this works except that the image relationship is "shows cataloged item", which it doesn't.  Can we add a new relationship that is more appropriate?  Will that cause problems with attaching the image to a bunch of specimens?  We will need to attach this image to a whole slew of specimens.  How many relationships can one image have?  Anyone have a better idea for how to handle this?

**Comment by campmlc** [comment]
Teresa, can you link the media to the accession (if it applies to all)?
Then it will show up on all specimens and relationship will be " documents
accession".

On Apr 10, 2017 12:12 PM, "Teresa Mayfield" <notifications@github.com>
wrote:

We have a lot of fossil teeth that have measurements that aren't defined.
We entered them all as unformatted measurements, but we can use use a
graphic to explain the way the measurements were made. Dr. Harris made an
attempt at this with specimen UTEP:ES:4-2.

I like how this works except that the image relationship is "shows
cataloged item", which it doesn't. Can we add a new relationship that is
more appropriate? Will that cause problems with attaching the image to a
bunch of specimens? We will need to attach this image to a whole slew of
specimens. How many relationships can one image have? Anyone have a better
idea for how to handle this?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ArctosDB/arctos/issues/1092>, or mute the thread

**Comment by dustymc** [comment]
>"shows cataloged item

It's actually "shows cataloged_item" - the string after the last space is always the name of a table with a primary key (which is what media can attach to). Everything before that is functionally irrelevant; "something else cataloged_item" will behave the same way.

>cause problems with attaching the image to a bunch of specimens

Technically, that's fine. From a data modeling perspective, it's (denormalization) almost always going to eventually find a way to cause problems.

>many relationships can one image have

In theory, (10^38) * 2 - although we may experience performance problems well before that....

>Anyone have a better idea for how to handle this?

New Attribute(s). Either create one attribute, use the URL of the image (or the pub from which it came) as description, and feed it structured data (just "A=1; B=2; C=3" would do it), or multiple attributes (one for each "letter") each linked to the image in the attribute's description. The first is maybe a little easier to use, the second is more searchable ("find tooth-thingee A < 3KM" is possible).

Also, geology attributes are hierarchical....

<img width="409" alt="screen shot 2017-04-10 at 9 29 31 am" src="https://cloud.githubusercontent.com/assets/5720791/24871924/3b8379f0-1dd0-11e7-9ca9-0a7f4f43b0d7.png">

... and so "Pleistocene" implicitly asserts Quaternary, Phanerozoic, and Cenozoic. If someone said "this is Cenozoic" and then someone said "this is Phanerozoic" and etc. then you CAN explicitly assert everything, but if someone just said "this is Pleistocene" then the rest are built into the structure of Pleistocene and explicitly re-asserting them doesn't really do anything.

**Comment by Jegelewicz** [comment]
@campmlc not all of the specimens in any accession are applicable.

@dustymc I can't quite imagine how the attribute description idea would look in Arctos (thinking from a bulkloader perspective). Would it look like this?

Attribute_1 unformatted measurements
Attribute_Value_1 a=1; b=2;...
Attribute_Remarks URL of image

**Comment by dustymc** [comment]
That's still denormalized.

The CODE TABLE would be:
```
attribute_type.......description
tooth-thingee.......Measurement of bla bla  bla see {some URL} for more info....
```
(We might need a better name...)

The bulkloader:
```
attribute_1: tooth thingee
attribute_value_1: a=1;b=2 (or JSON or XML or whatever could go here)
attribute_remark_1=remarkable things about how "tooth thingee" applies to this one specimen
```
or alternatively:

The CODE TABLE would be:
```
attribute_type.......description
tooth-thingee A....Measurement of bla bla  bla see {some URL} for more info....
tooth-thingee B....Measurement of bla bla  bla see {some URL} for more info....
```

The bulkloader:
```
attribute_1: tooth thingee A
attribute_value_1: 1
attribtue_unit_1: light year
attribute_remark_1=remarkable things about how "tooth thingee A" applies to this one specimen


attribute_2: tooth thingee B
attribute_value_2: 1
attribtue_unit_2: femtometer
attribute_remark_2=remarkable things about how "tooth thingee B" applies to this one specimen
```
That is normalized - the description of what you mean by "tooth thingee" appears exactly one time in all of Arctos, and anyone using "tooth thingee" for anything else is just wrong. (If you define it elsewhere you've set yourself up for "tooth thingee" to mean "bla" on some specimens and "blah" on others, and if that's the case the data are of negative value - they just confuse people and produce bad results!)

The first approach is a string. If you do a good job of formatting I can download all "tooth thingee" data and unroll your structure (eg, into columns) and filter there. The second approach is natively structured - Arctos can convert everything to common units and search by them, etc. - but it requires everyone sharing the collection_cde to look at your big pile-o-tooth measurements. I don't think that's much of a problem, but you should be able to defend the need if it comes up.
