### ISSUE TITLE
Taxonomy: the big picture

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1094]
This Issue is meant to serve as an index/summary/synthesis of other taxonomy threads, which are difficult to "join" into a cohesive picture (or just find!). This Issue should contain no new information; please comment with specifics on individual Issues (new or existing) and provide a brief summary and link to the Issue here. Consider editing this rather than commenting lest we soon need a summary-summary summary.

# Summary-summary: Next/most critical step

We need well-defined reciprocal terms for http://arctos.database.museum/info/ctDocumentation.cfm?table=CTTAXON_RELATION and a migration path to deal with the existing data before almost anything else can happen. A first-pass attempt is https://docs.google.com/spreadsheets/d/1S9tRAtgJQjCTTYKanxdTTSBouWj3CAZTrBdBh6HwUnE/edit#gid=894404859 (two tabs, anyone can edit). My "suggestions" are driven only by desperation; please do something more useful!

# Problem: Inconsistent data; difficult to be consistent; difficult to eg, move a genus to a new family

## Solutions
* #1000 provides a way to pretend "local" data is hierarchical, and requires a name for every term before repatriation can succeed (#891)
  * Status: in development; functional, continuing to add features
* #1086 provides generated display_name.
  * Status: running at production

# Problem: want accepted/preferred names for various purposes (directional search, pick list, etc.) 

## Solutions

* Develop relationship vocabulary; everything in http://arctos.database.museum/info/ctDocumentation.cfm?table=CTTAXON_RELATION should be reciprocal with exactly one other relationship, and clearly and universally (eg, with no Code limitations or implications) defined. #1079, #756, #735
  * Status: Not started; this seems a required precursor for all other relationship-based functionality. Someone, preferably a coalition of taxonomists representing various Codes, needs to develop vocabulary and create a lookup table
* A migration pathway for existing relationships is needed. 
  * Status: part of above; new terminology doesn't do much good while mixed with existing.
* Relationships must move from names to classifications. Echidna (the snake) and Echidna (the mammal) refer to different "alternate classifications" for different reasons; one relationship (with the name) is insufficient to represent that. #983 provides one possibility. #757
  * Status: Indeterminate. Not completely clear how this might work, who should be able to edit it (nobody??), etc.
* Some names/classifications are nonpreferred independent of relationships. #1079 discusses "taxon status."
  * Status: Exists, but is not actionable - code to prefer names based on status will be developed alongside relationship-based preference.
* Given clear reciprocal relationships and proper usage of taxon status, non-classification term valid_catalog_term_fg becomes redundant and confusing and should go away. A migration pathway to ensure the data are captured elsewhere needs developed.
  * Status: Will revisit after relationships are resolved

# Problem: Performance on "any name" search is not very good

## Solutions: Reciprocal relationships stored in classifications would eliminate the expensive pathways. #983
  * Status: no action needed IF relationships moving to classifications works out

**Comment by ekrimmel** [comment]
I am not a taxonomist by any means, but I am highly in favor of developing reciprocal relationships, and of the well-defined reciprocal terms listed in your google spreadsheet, @dustymc.

**Comment by dustymc** [comment]
Commenting to reemphasize the importance of #1000 (or something like it), particularly in light of recent upgrade requests to the taxonomy edit forms. There are a ridiculous number (hundreds of thousands?? They're very difficult to find; that's the point!) of inconsistent taxa which are missed by most any given query, and they guarantee that any improvement or update (currently #1086) fails to do all of what was intended.

Example: There were ~50K not-plant taxa formatted as "Genus species **subsp.** subspecies" (from ITIS) which were also missing a Kingdom term. (Many of them also missing phylum, class, etc.)

Recommendation: Deprecate all single-record edit forms. Edit taxonomy only in context of other taxonomy (eg, as a hierarchy). This will guarantee we don't create inconsistencies.

Recommendation: Require certain terms (kingdom, minimally) in the classification bulkloader. This will limit the inconsistencies which may be created by that tool. (The tools has consistency checks, but they're suggestions rather than hard rules.)

Problems:

1. I have received very little feedback on the idea or implementation of #1000; I'm not sure if it'll meet curatorial needs or if we need to be looking for another option.
2. #1000 import misses a LOT of inconsistent data; the single-record edit form is critical to bringing in outliers (hopefully without creating different outliers!)

**Comment by dustymc** [comment]
This is mostly (fully?!) implemented; closing.
