### ISSUE TITLE
Add depth to "Pick Locality" description

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#1095]
During data entry, when we have recently started to use the  "pick locality" functionality.
![image](https://cloud.githubusercontent.com/assets/15368365/24931128/4e6cae3e-1ec9-11e7-805f-0e11322adeae.png)
We did not realize picking this locality would override the depth we later enter in the data form with the depth stored in the locality record.  For example: If the locality search term is Mactan Island, this is the list of options already in Arctos.
![mactan island localities](https://cloud.githubusercontent.com/assets/15368365/24930371/82e83172-1ec6-11e7-9dec-cdf3e9768a5b.PNG)

The locality ID of the first entry is 10758895.  It matches our verbatim locality of "Off Mactan Island" so it is the one we would choose.  When we select it, it populates the Higher Geography and Specific Locality.  It does not populate the depth field in the Data Entry form, but the locality includes a depth of 20-30 meters. 

![mactan island with depth](https://cloud.githubusercontent.com/assets/15368365/24930629/54242d68-1ec7-11e7-9cca-0e63b4cf2568.PNG)

We then enter the correct depth (in this case 2-3 meters) in the data entry form thinking it will be used and then save the new record.  Once the record is loaded into Arctos, we reviewed and found the depth listed as 20-30 meters, not the 2-3 meters that we entered.

A SQL search has turned up multiple entries with erroneous depth that we now are correcting.  We will stop using the "Pick Locality" feature for this reason.

We have not yet used elevation but it may have the same problem.

Can ALL fields that are associated with a locality (depth, elevation, coordinates, etc) be listed with the locality in the list when you do Pick Locality.  In addition, back in the data entry form, if you pick a locality, it should populate all fields related to the locality (i.e. populate the depth). 

e.g. this list:
![mactan island localities](https://cloud.githubusercontent.com/assets/15368365/24930371/82e83172-1ec6-11e7-9dec-cdf3e9768a5b.PNG)

In addition, back in the data entry form, if you pick a locality, it should populate all fields related to the locality (i.e. populate the depth).

**Comment by dustymc** [comment]
Hi Phyllis,

Sorry about that!

What browser and OS are you using, and can you try it with any extensions disabled? The pick does properly populate all locality data in my browser, but it does not properly disable those fields - I'll fix that ASAP. (Although, just to be clear, anything that happens in your browser a suggestion, not a rule - you have completely control of how/whether that code executes, all authoritative checks happen server-side at load.)

The documentation, such as it is, is on http://handbook.arctosdb.org/documentation/bulkloader.html#fields:

<img width="890" alt="screen shot 2017-04-12 at 10 17 31 am" src="https://cloud.githubusercontent.com/assets/5720791/24970471/441e7106-1f69-11e7-8bd3-583b1f2d624c.png">

Suggestions on clarifying that or making it more accessible would be very appreciated (or I think you can edit the documentation if that's more useful).

Elevation is part of the same data object (locality) and so will indeed behave the same way as depth.

**Comment by sharpphyl** [comment]
We use Firefox and Microsoft - mostly Windows 7 and 10.   We don't have any extensions listed.  I'll try it in Chrome and in Explorer and see if it makes any difference.  

We'd still benefit from having the locality pop-up show the depth as well as the Higher Geography and the Specific Locality so we don't have to select  multiple ones to figure out of we have a match.  Is that part of the fix you're proposing.  

On the documentation, it would be helpful for us if it mentioned override of depth and elevation but it will be obvious if you disable those fields when a Locality is picked.

**Comment by sharpphyl** [comment]
If it's helpful I can do some screen clips tomorrow if the Pick Locality functionality that we see hasn't changed.  Let me know if that would be helpful.

BTW, if the locality you pick has NO depth, that overrides any depth you insert so disabling that field is really important to communicate whether the locality is suitable for that record. 

Also, the bulkloader shows what you type into the data entry form.  It does not show what will override your data in the depth/elevation fields even though it lists the locality ID.  You don't see the discrepancy until you look at the record after it has been uploaded.

**Comment by dustymc** [comment]
added depth, fixed CSS
