### ISSUE TITLE
Please move create name and classification button up near field

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#1097]
Please move this button up near the field - its current placement requires scrolling down to find it. In general this UI guideline would be good to follow throughout Arctos. use space more efficiently to minimize scrolling...see attached image.

![asdfdfsdsfg](https://cloud.githubusercontent.com/assets/9099827/24975671/fa5ecc96-1f72-11e7-9927-64663be707d5.png)

**Comment by dustymc** [comment]
That is by design: the next form will happily eat your data. I'm happy to try to convey that critical information in some other way, but making it easy to ignore strikes me as dangerous.

**Comment by DerekSikes** [comment]
I ignore it every time I angrily scroll past it wishing I didn't have to scroll past it so often. I just need to make new names and LOTS of them. Why try to force me or anyone to read/learn things (ineffectively) every time they do a repeated action?

**Comment by dustymc** [comment]
Angry scrolling is bad!

I agree, you don't need to see it 500 times/day. You probably do need to see it if you add a taxon every month or something. Clever ideas appreciated, and I bumped priority up.

**Comment by dustymc** [comment]
Form should now be scroll-free in most views; moved scroll to documentation, added "important" style.

<img width="1362" alt="screen shot 2017-04-17 at 8 53 44 am" src="https://cloud.githubusercontent.com/assets/5720791/25094330/81c6254a-234b-11e7-9a0c-2f7fc32f8fe2.png">
