### ISSUE TITLE
enable clone classification as new name to copy author data from prior classification

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#1098]
Often I need to make a new name that is simply the moving of a species from one genus to another. The clone classification as new name tool fails to copy the name's author data with the cloning so I then have to 1) add this field, 2) find the name, 3) copy & paste the name etc.... another good guideline to follow is that the term 'clone' should be closer to what people think it means (ALL data copied).

(Similar problem with the clone specimen record into bulkloader that fails to copy the identification history and ID agents information,.. but that's another issue.)

**Comment by dustymc** [comment]
Flagging "needs discussion" - I think the behavior you describe would lead to an increase in erroneous (for the new taxon) information being inadvertently included, but perhaps I'm just being paranoid or not understanding how the thing is used. (My common usage is encounter new species - find something sorta-similar - clone to get family-and-such - I'd have to delete the authors and subspecies and such - things that are, at least in that use case, unique to a taxon - if they carried over, and I'd probably forget to do so way too often.) 

Whatever the ultimate behavior decision is, I'm happy to change the labels - just let me know what it should be.

Maybe a second button, so users would have both "clone everything" and "clone higher-level probably-the-same" options or similar??

>bulkloader

The specimen bulkloader is only capable of dealing with a small fraction of possible "specimen data." Would a better label (not "clone") sufficiently address this? If so, label suggestions?

**Comment by Jegelewicz** [comment]
Maybe a second button, so users would have both "clone everything" and "clone higher-level probably-the-same" options or similar??

I like that option, because I would definitely clone into a new name but accidentally leave the wrong author or a crazy variety or something else.

**Comment by dustymc** [comment]
Added second button

<img width="1299" alt="screen shot 2017-04-17 at 9 17 44 am" src="https://cloud.githubusercontent.com/assets/5720791/25095057/cb6f386e-234e-11e7-8c43-3e7d597c78a2.png">
