### ISSUE TITLE
Fossils that are also artifacts

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1099]
In our ES collection, we have some items that are both a species and an artifact (worked by people in the past).  We are considering the most appropriate way to denote that in the specimen record and to add specific information.  For instance, in some cases we have an idea of who did this (a tribe name, etc.  not an individual).  I'm thinking an attribute would work.

Can we add "culture of origin" as an attribute in ES collections?

**Comment by dustymc** [comment]
Seems reasonable to me, but let me send email to the ES folks.

EH collections handle that with additional specimen events, so you might have some/all/multiples of....

* event_type=place of manufacture (=place/time it was worked)
* event_type=place of use (=place/time it was used)
* event_type=place of collection (=place/time it was collected, whatever that means)

Depending on HOW worked it is (or something...) you might also want to do something like http://arctos.database.museum/guid/UAM:EH:UA67-133-0001 - the ID is parka, ID tab looks like....

<img width="529" alt="screen shot 2017-04-12 at 3 50 23 pm" src="https://cloud.githubusercontent.com/assets/5720791/24982719/c784f2b2-1f97-11e7-9678-576b8178d024.png">


and so it's findable by searching "parka" or anything from any of the taxa used in IDs - all of....

<img width="642" alt="screen shot 2017-04-12 at 3 51 43 pm" src="https://cloud.githubusercontent.com/assets/5720791/24982753/f72d3844-1f97-11e7-8dc0-fcce3d0edde9.png">

plus anything on any of the taxon pages - eg, "Synapsida" will find it (it's a term in http://arctos.database.museum/name/Canis%20lupus#ThePaleobiologyDatabase) and "dingo" will find it (http://arctos.database.museum/name/Canis%20lupus links to http://arctos.database.museum/name/Canis%20dingo and that's a common name there) etc.

**Comment by Jegelewicz** [comment]
I like that idea, but in the ES collection, it doesn't appear that we have the "associated taxa" capability.
![screenshot 2017-04-12 17 22 44](https://cloud.githubusercontent.com/assets/5725767/24983535/db72dcf0-1fa4-11e7-89b3-3a904279e318.png)

**Comment by dustymc** [comment]
It only works when editing an "A {string}" formula ID.

**Comment by dustymc** [comment]
ES now has access to "culture of origin"
