### ISSUE TITLE
New Encumbrance Request

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ArctosDB/arctos#11]
```
Modify encumbrance of coordinates to include specific locality
```

Original issue reported on code.google.com by `dust...@gmail.com` on 6 Feb 2008 at 11:49

**Comment by campmlc** [comment]
Re-opening, as this is relevant to incoming paleo collections.  We need the ability to encumber specific locality, or alternately, an entire specimen event.  In the latter case, a "public" locality could be visible, but a specific locality with more details could be hidden.  Also, these encumbrances cannot be allowed to expire. @dustymc

**Comment by campmlc** [comment]
#1727

**Comment by dustymc** [comment]
Re-closing; this still isn't acceptable to some collections.

If we need to mask specific locality it needs addressed as a new Issue.
