### ISSUE TITLE
Associated species - how do you edit them?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1100]
I cannot figure out how to edit or add associated species.  I assume it would be a field in the Collecting Event since that is where it appears if anything is entered there in the first place (I think), however when I edit a collecting event, there is no option for entering or editing associated species.  Am I looking in the wrong place?

**Comment by dustymc** [comment]
It's under Attributes, which probably needs a new label....

It needs moved to specimen_event, but we haven't yet found a compelling reason to prioritize that.
