### ISSUE TITLE
Attributes for ES and mammal collections

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1104]
Dr. Harris has some standard measurements that he would like to add as attributes in the ES and mammal collections:

greatest length
proximal width
proximal depth
mid-shaft width
mid-shaft depth
least diaphysis width
alveolar length cheektooth row
diastema length

Any objections?

**Comment by dustymc** [comment]
Definitions please....

**Comment by Jegelewicz** [comment]
greatest length: from most proximal tip of an element to most distal tip of the element

proximal width: from most medial part of an element near the proximal end to the most lateral portion of the element near proximal end

proximal depth: from most anterior part of an element near the proximal end to most posterior portion of the element near the proximal end

midshaft width: from medial side of an element at midway between proximal and distal ends of the element to the lateral side of the element at midway between proximal and distal ends of the element

midshaft depth: from the anterior side of an element at midway between proximal and distal ends of the element to the posterior side of the element at midway between proximal and distal ends of the element

least width of diaphysis: the least distance between the medial and lateral sides of a diaphysis

distal width: from most medial part of an element near the distal end to the most lateral part of the element near the distal end

distal depth: from most anterior part of an element near distal end to the most posterior part of the element near the distal end

alveolar length cheektooth row: from the most anterior alveolus of the most anterior cheektooth to the most posterior alveolus of the most posterior cheektooth

diastema length: the length of a gap from the posterior part of an anterior structure to the anterior part of the structure at the posterior end of the gap

**Comment by dustymc** [comment]
Are these part attributes? At least some of these seem like things that apply to specific physical material rather than "the individual" (or whatever was cataloged).

**Comment by Jegelewicz** [comment]
Yes, they do reference a specific part of a cataloged object, which could be given in the attribute remarks or these could all be "measurement" attributes of the specific part. However, sometimes the measured part isn't a separate part in Arctos. For example, we may have the part "skeleton" but one of these attributes for the femur. Which leads me to lean toward the first option.

Thoughts?

**Comment by amgunderson** [comment]
These are all specific to parts, not standard measurements for mammal specimens, look to be not repeatable, and use subjectively determined landmarks. I don't think any of them should be added as attributes. They would crowd an already overcrowded list of attributes to be used by a negligible few specimens. Aren't these just part of someone's morphometric research project and should be recorded in publications linked to specimens? We should not be transcribing every morphologists' bone measurements into specimen records, those should be published or linked to morphobank or maybe added as media in a table linked to the relevant specimens.

**Comment by dustymc** [comment]
Yea, I'm pretty hesitant to introduce an infinite number of attributes as well, particularly when we don't know what we're doing with the current stuff - https://github.com/ArctosDB/arctos/issues/1450. I don't much use the forms so I'm not sure my opinion should count here, Arctos doesn't have any problem with another million Attributes, but there is some number of "columns" above which users (data entry & researchers) will have difficulties.

I'm not sure how it should be done, but "find seals with a alveolar length cheektooth row of ..." seems useful. Morphbank's API doesn't seem like something we could plug in to.

Other options: 
* Media (CSV or similar) could work
* use "unformatted measurements"
* use "unformatted measurements" but format as JSON (or XML or whatever)
* add a "formatted measurements" Attribute that requires JSON (or XML or whatever)

```
[
 {"midshaft depth": "50 mm"},
 {"least width of diaphysis": "50 mm"}
]
```
or


```
[
 { "attribute":"midshaft depth", "value":"50", "units":"mm" },
 { "attribute":"least width of diaphysis", "value":"50", "units":"mm" }
]
```

or something. None of that's very useful unless it's following some sort of Standard - whatever happens definitely needs documentation.

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/1623

**Comment by Jegelewicz** [comment]
If this comes up again - suggest using unformatted measurements.
