### ISSUE TITLE
geography<-->specimen guidelines

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1107]
ref: http://handbook.arctosdb.org/documentation/higher-geography.html#guidelines-for-assigning-geography-to-specimens

I've been fixing/creating a lot of geography for a new collection and noting problems with existing data when I find them. There are now maps on the geography edit pages, and from those I have spent a ridiculous amount of time chasing what looks like misplaced specimens, but which in fact are specimens which **reference** a place rather than **occurr at** the place.

For example, San Juan Island, WA - with an obvious problem:

<img width="522" alt="screen shot 2017-04-19 at 8 11 24 am" src="https://cloud.githubusercontent.com/assets/5720791/25187435/db361e72-24d7-11e7-96a3-6717ea50846e.png">

A few clicks later, and...

<img width="752" alt="screen shot 2017-04-19 at 8 12 40 am" src="https://cloud.githubusercontent.com/assets/5720791/25187491/06fdf5a2-24d8-11e7-9554-0bad73c3148c.png">

There is no problem, but

1. that's not obvious from many perspectives, and
2. any questions asked of geography cannot return the expected results because the same data can mean (at least) two distinct things

It seems very unlikely that we'll be able to find and fix existing data, but perhaps we can create higher-quality data going forward. I propose we add to the geography<--> specimen guidelines something like "place where the event occurs, use for nothing else." If that isn't acceptable, perhaps we could add a "geog_used_for_some_random_reason_plz_ignore" flag to Locality or similar. (Although I doubt anyone would find it, and I'm not sure how I'd incorporate it into the geog specimen map.)

Thoughts?

@tucotuco

**Comment by ekrimmel** [comment]
@dustymc I see what you mean about this being a point of ambiguity that we could improve, but I don't quite understand your proposed solution. If we add a business rule that geography is a "place where the event occurs, use for nothing else" then would the example specimen you show just be given a higher geography of Pacific Ocean?

This feels very relevant to me because we are cleaning up our malacology data and have a lot of specimens that as I currently have them will fall into this "referenced geography" category. Prior to georeferencing it's helpful for us to have _some_ way to aggregate localities, and for us the higher geography does this well.

**Comment by dustymc** [comment]
>don't quite understand your proposed solution

My proposal is to develop better documentation. I'm not sure if that'll lead to procedural changes or not - I suspect it may not, but perhaps we can SOMEHOW be more clear in documenting why/how we link geography and specimens (ie, in helping users find specimens).

>business rule 

That would only be possible when there's both a georeference for the specimen and a polygon for the geography. I'm thinking more along the lines of documentation/guidelines (for now?).

>just be given a higher geography of Pacific Ocean

There are several ways of spatially defining political bodies (mean high tide, exclusive economic zone, etc.), that would be "Washington" in a few of them. It's probably "in" the island group, but again we have no real (eg polygon) definition. I think there's some interest in redefining "sea" or adding "sub-sea" (for "smaller gulfs" and such) or somehow doing more with water bodies, so perhaps there's a better solution in that. In any case you bring up a good point: given fairly precise coordinate data, we must somehow do better than "the wet half of the planet" in the geography component.

Our current spatial definition of Washington (from data we found in some random spreadsheet) includes San Juan Island.

<img width="275" alt="screen shot 2017-04-24 at 9 23 33 am" src="https://cloud.githubusercontent.com/assets/5720791/25347463/e0c2b37c-28cf-11e7-9c3b-bb5526aec3d4.png">

**Comment by dustymc** [comment]
Re: https://github.com/ArctosDB/arctos/issues/1773#issuecomment-435428173 from @sharpphyl 

>customary

It's also customary to use databases in which geography and coordinates are just random strings that can't do anything!

>not want to use Pacific Ocean as the higher geography

As much as I see any value at all in asserted higher geography - and that's not all that much! - I agree. We should somehow do better than "the wet half of the planet."

>bay

I think there's room for something like that in the model, and maybe this is a good reason to pursue some sort of county-equivalent marine divisions.

> pointer on the center of the island

That's "wrong" too, but I think we're stuck with it until we can find more advanced geospatial tools.

>depth

That's locality, but it's another place where better geospatial capabilities (eg, probability surfaces) would help. Just like "New Mexico, 12000 feet" should be represented as a half-dozen donuts (rather than one giant circle that encompasses mostly stuff nowhere near the given elevation - what we can do now), "Some island, 10-15 fathoms" could also be spatially represented as a "donut" which follows contour lines to encircle the island.

>considered part of the geopolitical area but won't appear within the county boundaries

That's probably a Really Good Thing some of the time and a Really Bad Thing some of the time. Eg, does the county Office Of Invasive Critters care about snails a couple miles offshore? Sometimes...

I think I'm circling around the idea of a "relationship_between_locality_and_geography" concept somewhere (probably in Locality?), which seems like it would more or less solve this Issue by allowing users to discriminate between "IN geography" and "REFERENCES geography." I see no way that REFERENCES localities could be checked in that model so I don't think it's a great solution, but it would provide a way to isolate the things that can be checked, allow us to continue with the customary methods, and not force us to do anything other than set the flag for the many specimens which are entered in this manner.

https://github.com/ArctosDB/arctos/issues/1705

**Comment by sharpphyl** [comment]
Is it possible to add an option that, when creating a locality or geolocating one, allows one to opt out of checking it against the county/country or other pre-set boundaries?  This would enable us to plot marine species just outside terrestrial boundaries and avoid daily annotations for consciously nonconforming localities, but not make any changes for the requirements for localities that we want to be within the boundaries.

**Comment by dustymc** [comment]
@mkoo that is a problem sometimes, but it's not the issue here. These are specimens which are known to be outside of any reasonable spatial definition of the geography, they just reference geography. Everyone agrees that Some County ends somewhere near the coast, even if the details are fuzzy, yet specimens which correctly map halfway to Hawaii reference the county for some reason. 

The "community standard" is free-text, or MAYBE mapping dots through GBIF. I think we're on our own for this. 

FWIW my ideal 'standard' would just be a set of accessible polygons and the ability to interact with them, which would allow USERS to define this stuff as they see fit. Eg, "California" ends where things start getting salty for lichen-people, maybe 100 (or 3 or 12 or 200) miles offshore for commercial fish people, at some legally-defined boundary for the County Invasive Critter Office, etc. Trying to preemptively say "this shalt be California" seems destined to make someone (maybe everyone!) twitchy. That's about what we can do now. It's not ideal, but it's still really useful for finding things that say California and map to Utah.

@sharpphyl that's what I'm asking - should we try to prevent this (eg, by developing marine geography and/or better documentation), or should we add some sort of "we_know_this_makes_no_spatial_sense_plz_ignore" flag, or ??? The flag is easy but doesn't seem like a great solution to me. I'm not sure if there's any useful "marine standard" that we might incorporate into geography or not. Calling something 2 miles offshore of San Diego anything except San Diego may confuse snail-people. I don't have anything in mind and am completely open to most everything.

If we do go the opt-out route, someone should consider proposing the concept to DWC. This directly contradicts the Standard through which we're sharing data, I think it makes sense to give them a heads-up.


https://terms.tdwg.org/wiki/dwc:county

>County: The name of the next smaller administrative region than country (state, province, canton, department, region, etc.) **in which the Location occurs**

**Comment by tucotuco** [comment]
Minor point of information

County: The full, unabbreviated name of the next smaller administrative region than stateProvince (county, shire, department, etc.) in which the Location occurs.

Major point of information: If you populate your county (or other) with something having something other than those semantics, you will have to withhold the value in the shared records in those cases where the meaning does not match.

**Comment by tucotuco** [comment]
... or 2c. Not populate DwC fields inappropriately, add commentary in dataGeneralizations, which is supposed to alert people that things may not be as they seem, and/or in locationRemarks.

**Comment by dustymc** [comment]
I'd probably not want to pollute locality remarks with administrative data, and I certainly can't act upon a free-text field - if we're going to continue this, I think we need the flag (or a better idea of some sort). Portals won't be able to act on a free-text field either - it seems likely that we'll eventually start getting the same sort of thing we get from the Arctos "find specimens which use this geography and aren't in the shape" button from GBIF-and-friends if we don't do SOMETHING.

>dataGeneralizations

Whoa - https://github.com/ArctosDB/arctos/issues/1779

**Comment by dustymc** [comment]
Based on comments in this thread and https://terms.tdwg.org/wiki/mixs:geo_loc_name

>The geographical origin of the sample...

I have updated http://handbook.arctosdb.org/documentation/higher-geography.html#guidelines-for-assigning-geography-to-specimens to include

>Specimens should be linked to their geographical origin. Do NOT use geography as a reference. A specimen with specific locality “20 miles west of Monterey, CA” should be linked to Pacific Ocean, not California.

**Comment by sharpphyl** [comment]
Sorry, but I'm reopening this.  

Are you saying that it's fine to add higher geography for "North Pacific Ocean, North America, United States, California, Monterey County" and a similar entry for every location in our higher geography that borders an ocean in order to accommodate marine species?  That would be a huge undertaking. 
 Currently, only the higher geography for islands and island nations begins with the ocean.

I've spoken to several people involved with marine collections and all agree that traditionally specimens found offshore of Monterey, CA are databased in relationship to Monterey, CA and not in the Pacific Ocean unless California is part of the higher geography as described above.   

Within some iDigBio records, the "water body" is listed as North Pacific Ocean.  This is an option we currently don't have but could be a way to distinguish marine from terrestrial specimens.  We'd be fine with adding this field if that helps.  

Or if we want to set up a separate marine geography that begins with the oceans then the nearest country, state, etc. that would probably work, but we're reluctant to force our marine specimens into the terrestrial geography. It also means changing almost every record in our database which is a daunting thought.

Is this on the agenda for the Geography team or how to we proceed?

**Comment by dustymc** [comment]
DWC/TDWG is saying, and I am strongly agreeing, that a locality which references "Monterey County" (or anything else) should fall within Monterey County. If there's some defensible definition of Monterey County that needs to be in the Pacific Ocean for some reason then OK. Something found 400 miles (or 3 inches) west of Monterey County and referencing Monterey County is just wrong.

>traditionally

Traditionally we didn't have the geospatial capability for any of this to matter. Currently we should support the Monterey County Invasive Critter Department being able to find things that are from Monterey County without having to sort through stuff that just references the county for some reason.

>water body

If that's for things which have no overlap with sea and ocean (I should not have to guess where you've stuffed "Pacific Ocean") and for which there are clear boundaries (I should be able to unambiguously determine if a point is or is not in Monterey Bay) then I have no objections to introducing a new "column."

> separate marine geography

I should not have to guess at your administrative decisions to find your specimens. If this does that then it's evil. If it doesn't then maybe it's useful. 

> how to we proceed

Ideally we'd do all this through services - we'd just throw shapes at some service and accept whatever it returns, which would mean our georeferenced specimens would be 100% discoverable through text searches. (I can't perform any of these checks on specimens without coordinates anyway - those are not useful for anything involving much spatial precision now, and a service-based model wouldn't change that.)

**Comment by Jegelewicz** [comment]
> Within some iDigBio records, the "water body" is listed as North Pacific Ocean. This is an option we currently don't have but could be a way to distinguish marine from terrestrial specimens. We'd be fine with adding this field if that helps.

I think separating Continent/Ocean would be a start. Currently all of Arctos stuff with higher geography in the Pacific Ocean ends up with "Pacific Ocean" in dwcContinent rather than dwcwaterBody.

See a larger discussion of this at https://github.com/tdwg/dwc-qa/issues/128

**Comment by dustymc** [comment]
>separating Continent/Ocean

No particular objection, but that won't do anything for Phyllis and I'd probably want to set up an either-or rule so it won't change anything about existing data either.

**Comment by sharpphyl** [comment]
I now have 440 annotations saying that we have a geolocated specimen that "Does not map to assigned geography."  The ones I've looked at are marine specimens found just "off" the stated location.

It looks like WKTs have been added for South Africa so all our specimen records from there are now generating annotations.  We have geolocated them by dropping the pin just offshore, so it falls outside the WKT.   

In looking at a few records on idigbio to see what other museums are doing, I haven't found any yet that start with the ocean instead of the country.  For example, DMNS:Inv:27162 (Athleta gilchristi) does not map to Africa, South Africa, KwaZulu-Natal Province.  If I look at the 10 records of this species on idigbio, they all start with Africa, not with Indian Ocean or another body of water.  Their localities are "off Durban" or a similar "off" locality.  

Dusty, you must be overriding annotations for most localities since I'm only getting them for San Diego county and South Africa.  (I fixed Bibb County.)  Is there a way to override these?    Right now, I'm ignoring annotations which means I could miss a truly important error.   

One idea in the above conversation was that we could check a box "marine specimen" (or "ignore WKT," etc.) when creating a locality that would indicate that the pin will drop outside the WKT.  Did that get any traction?

**Comment by dustymc** [comment]
>what other museums are doing

"Not spatial things" for the most part!

>overriding annotations 

I'm definitely not! I (and others I think) just push the button when I stumble across something with conflicting data. There's an Issue to change that, but it hasn't floated to the top of the pile yet.

>check a box "marine specimen" (or "ignore WKT," etc.) when creating a locality t

@tucotuco says it's just wrong for the purposes of DWC, and it certainly goes against the grain of what we're trying to do in Arctos (make the data DO STUFF - things the randomly-selected, randomly-paired, uncontrolled strings used by every other CMS of which I'm aware just can't.) It's still something we can do, but (lacking a change to DWC) I think I'd have to withhold those information from GBIF-et-al, and I'd probably want to somehow mark them as low-quality in Arctos. I don't think any of that's quite what anybody wants.

The solution is easy: create and use appropriate geography. I don't really care what terms are used or how it's formatted, as long as its easy to defend. San Diego County (as far as I know) has a (one) real spatial definition, and things that aren't in that shape should not use "San Diego County." "California" has a lot of possible shapes, so something like "California, San Diego Bay" might make sense. ("California, halfway to Hawaii" won't, ever.) Those, like everything else, would be MUCH more useful if they included WKT data. 

Ambiguous edges - something WKT can readily solve - is why we pulled "bay" from feature many years back. Without "edges" marine features are hard to define so eg, San Francisco Bay just sort of tapers off somewhere before you get to Hawaii, which serves only to make those specimens completely undiscoverable by way of geography. We have the tools to address that now, I think we're overdue for a conversation regarding a geographic model that better serves marine specimens.

**Comment by Jegelewicz** [comment]
> The solution is easy: create and use appropriate geography. I don't really care what terms are used or how it's formatted, as long as its easy to defend. San Diego County (as far as I know) has a (one) real spatial definition, and things that aren't in that shape should not use "San Diego County." "California" has a lot of possible shapes, so something like "California, San Diego Bay" might make sense. ("California, halfway to Hawaii" won't, ever.) Those, like everything else, would be MUCH more useful if they included WKT data.

As I was reading this, I wonder if a tweak to higher geography might help here. In keeping with reality, these things were not found in "California", but in the "Pacific Ocean". Perhaps we should think about "Ocean" higher geog a little differently and we shouldn't mix "Ocean" with "Continent". If we had a separate field for Ocean/Waterbody, then we could include an "associated landmass". So for the thing collected off the coast of California, you would have "Pacific Ocean, California", but it would look like this:

Ocean or Waterbody - Pacific Ocean
Continent - North America
Country - United States 
State or Province - California
County - 
Quad - 
Feature - 
Drainage - 
Island Group - 
Island - 

It seems as if "Sea" should be folded into waterbody, but maybe there is more nuance there,

This structure could be used to inform GBIF and other aggregators in the proper DwC format (anything in Ocean/waterbody would go into the appropriate term [dwc:waterBody](https://terms.tdwg.org/wiki/dwc:waterBody) things without would go into [dwc:continent](https://terms.tdwg.org/wiki/dwc:continent). 

Brain is tired....

**Comment by mkoo** [comment]
ack I almost hesitate to bring up some GIS spatial standards. What about
including EEZ zones for each coastal county or state? There could be WKTs
for that which could replace or complement the existing
terrestrial counties. EEZ = Economic Exclusion Zones dictate where you are
fishing and which jurisdiction you fall under. We have used this to
georeference fish and marine collections in the past.

we would create new HG that are appropriate for the localities-- if county
is included then the HG would be specific to the county. yeah we are going
to have to carve up the entire planet into wkts and HG. Overlap is
inevitable and maybe not that terrible.
thoughts?

(BTW, this is pretty specific (and needed) use case for aquatic collections
so should be filed in a new issue soon)

**Comment by mkoo** [comment]
https://en.wikipedia.org/wiki/Exclusive_economic_zone
I have shapefiles for this...

**Comment by dustymc** [comment]
>these things were not found in "California", 

I was just going from "In looking at a few records on idigbio to see what other museums are doing, I haven't found any yet that start with the ocean instead of the country."

>not found in "California"

I think the real answer is "it's complicated" - states do have some influence some distance offshore, hence my 'many Californias' comments. https://govinfo.library.unt.edu/oceancommission/documents/full_color_rpt/03a_primer.pdf

>shouldn't mix "Ocean" with "Continent".

I think those things are pretty ambiguous as well - eg lots of places well offshore are over continental plate - does anyone care? (Geologists might??) Our model is built around the idea that only one can occur at any one place, but I don't think there were any marine folks involved in that either. I don't think I much care and could go either way. 

Attaching shapes to geography removes the ambiguities. "Pacific Ocean" can start where the sand gets wet, or {pick a number} miles offshore, or WHATEVER, and I can immediately tell if a specimen is within that shape or not.

>Overlap is inevitable and maybe not that terrible.

Agreed, especially WRT precision - "Yellowstone" laps three states and a bunch of counties, and you might know any of that (or not) for any specimen. It's not ideal, but we're stuck with it. At the same time we should respect "real" boundaries when they exist. As far as I can tell there's a hard border around San Diego County, and it looks like this:

<img width="381" alt="Screen Shot 2019-11-15 at 1 52 05 PM" src="https://user-images.githubusercontent.com/5720791/68978279-259def00-07af-11ea-8afb-cdd42ac268e6.png">

Something a mile offshore could arguably in California, Pacific Ocean, various finer-scaled marine-things we might add, etc., but it cannot justifiably be in San Diego County.

**Comment by mkoo** [comment]
agreed on the county boundaries and there is precedent for offshore
jurisdiction, which is why we might use a EEZ specific to California State
(12 mi from mean tide shore). then between 12-24 mi is a national
distinction and 24+ is international waters or the "Pacific Ocean". But do
we still need some other distinction in HG or is that stuff for Specific
Locality ("Monterey County", near Pt Conception, etc)?

I feel we need more input from Arctos users on this -- so @Phyllis Sharp
<sharpphyl@gmail.com> I will make a new issue for this specific topic. Can
we get more dissemination to marine collecitons then? If we have a plan I
can help create HG

**Comment by tucotuco** [comment]
Of probable interest:

"Delimitation of maritime boundaries between adjacent States" https://docs.google.com/viewer?url=https%3A%2F%2Fwww.un.org%2Fdepts%2Flos%2Fnippon%2Funnff_programme_home%2Ffellows_pages%2Ffellows_papers%2Fdundua_0607_georgia.pdf

https://www.iho.int/srv1/index.php?lang=en

http://www.marineregions.org/eezmapper.php

**Comment by Jegelewicz** [comment]
Well, that's cool....http://chart.iho.int:8080/iho/main.do

![image](https://user-images.githubusercontent.com/5725767/68983489-75d57b00-07c8-11ea-89f0-280f60de4641.png)

**Comment by dustymc** [comment]
Documentation updated, closing
