### ISSUE TITLE
Georeference protocols

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1109]
Does "Google automated georeference" mean, I used Google Maps?

**Comment by dustymc** [comment]
No, that would mean you used the API, possibly by clicking the "accept suggestion" button on edit locality. If you copy/paste/transcribe (possibility of introducing errors) or edited the API suggestion (eg, somehow recalculated error) you'd need to specify the protocol for that.

I added some documentation to http://arctos.database.museum/info/ctDocumentation.cfm?table=CTGEOREFERENCE_PROTOCOL. It needs more.
