### ISSUE TITLE
when cloning a name in taxonomy the genus sometimes fails to match

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#1110]
One common change to names in taxonomy is the movement of a species from its current genus to another genus.

When I clone a classification in Arctos taxonomy to create a new name for such a situation:

eg I clone Philodromus mysticus into the new name Rhysodromus mysticus

The newly created classification has the new species name Rhysodromus mysticus but the genus field still says Philodromus and I have to notice/remember to change that manually.

Shouldn't Arctos prevent users from creating a new taxon that is self-contradictory? The name in the genus field MUST be the same as the genus name that forms the first half of the binomen.

I could see various solutions - have Arctos auto-detect the genus name change and auto-replace the old genus name with the new one...

or

Have Arctos check for this matching when trying to save the record and throw an error with a helpful note that the genus name differs between the genus field and the species binomen field.

I prefer the former solution but seems like something should be done.

**Comment by dustymc** [comment]
I'm hesitant to accept that ANYTHING is a global taxonomy rule (eg, something that could be implemented at the database level), but this seems like a good form suggestion. Here's what I think I can do:

1. if scientific name (taxon name) contains no spaces, do nothing. (Maybe you're playing with a genus, or maybe it's a new kingdom - I don't see any way to guess at that from only a string, but I'm up for ideas.)
1. If scientific name contains one space
    1. Autosuggest genus as the first element. Add the scary red border if the suggestion doesn't match existing
    1. Autosuggest the string as species. Red borders on nomatch.
1. If scientific name contains two spaces
    1. Autosuggest genus as the first element. Add the scary red border if the suggestion doesn't match existing
    2. Autosuggest first two elements as species. Red border thing
    3. Autosuggest string as subspecies. Red borders.
1. If scientific name contains three spaces
    1. Autosuggest genus as the first element. Add the scary red border if the suggestion doesn't match existing
    2. Autosuggest first two elements as species. Red border thing
    3. Autosuggest string as unranked element below species. Red borders. ("variety" and such are spelled out as ranks and generally abbreviated in names, so I'm hesitant to guess at anything involving ICBN-like infraspecific data.)

Reasonable?

**Comment by DerekSikes** [comment]
Sounds good to me!

**Comment by dustymc** [comment]
Useful in finding and fixing stuff that won't fit into #1000; starting.

**Comment by dustymc** [comment]
creates more suggestions for next release
