### ISSUE TITLE
ES vs. EH

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1113]
Dr. Harris and I have been discussing some of our ES specimens and we have decided that they are actually more appropriate to an EH collection.  How difficult would it be to move records from an ES to an EH collection?  Could I do this just by downloading the ES records, making a few modifications to attributes and possibly parts, re-uploading them to an EH collection, then removing them from the ES collection?

**Comment by dustymc** [comment]
That should work. There's a "...for bulkloader" option at specimenresults/manage, then http://handbook.arctosdb.org/how_to/How-to-Delete-Specimen-Records.html
