### ISSUE TITLE
New other ID number type

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1116]
AVID Pit Tag - https://www.avidid.com/animal-id-system/pit-tag

**Comment by dustymc** [comment]
I don't think how an ID was applied or the manufacturer of a device is important. 

If someone who might have more data in an accessible format (eg, where http://some_agency_or_whatever.org?tagnumber=1234 might return something) applied the tag, I suggest using their ID type. (And carefully formatting the "number" to match what they do/probably will publish.)

If that's not known or the data are unlikely to be usefully published, I suggest using "original identifier." (And perhaps embedding the metadata in the "number" - original identifier = 'USFWS trout project PIT tag number 17.')
