### ISSUE TITLE
Correct "who" in the barcode series list for barcode txt MLFRZ[1-4]

### ISSUE THREAD

**Issue by KyndallH** [ArctosDB/arctos#1118]
Correct "who" in the barcode series list for barcode txt MLFRZ[1-4]. It needs a 1 entered after fskbh so I can make edits to that barcode.

Thanks!

<img width="2233" alt="screen shot 2017-05-02 at 9 16 41 am" src="https://cloud.githubusercontent.com/assets/16887896/25630031/28433f2a-2f18-11e7-81b0-8c1706a96712.png">

**Comment by dustymc** [comment]
done
