### ISSUE TITLE
Llinks to a specific collection

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1120]
How do I create a link that can be used on a website or in an email that will take a non-Arctos user to one of my specific collections? (only UTEP fish, for example)

**Comment by Jegelewicz** [comment]
Found it!

**Comment by Jegelewicz** [comment]
OK, maybe not.  When I put this link ( http://arctos.database.museum/utep_inv ) in a word document and use Ctrl+click I end up searching the 3 million records in Arctos.  If I copy and paste, it seems to work fine.  Why the difference?

**Comment by dustymc** [comment]
>word document 

Word is being "helpful"?

Or if you're logged in you're in your own "portal" which overrides anything else.

**Comment by Jegelewicz** [comment]
Not logged in, thus I get all of Arctos.  Not sure how Word could be "helpful", but I'd like to figure it out should I send links within a Word document.  I'll mess around with some other formats (email, pdf) and see what happens.

**Comment by dustymc** [comment]
The general answer is that most portals are linked from http://arctos.database.museum/home.cfm; go there and copy the links you need.

The default pattern for single-collection portals is replace(guid_prefix,':','_') so you can usually guess at them.

I created http://handbook.arctosdb.org/how_to/understanding-portals.html

I can only respond to HTTP requests to Arctos; I have no control over what requests are made. I gave up on trying to guess how Microsoft products would try to be "helpful" a long time ago.
