### ISSUE TITLE
Collection Header

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1121]
How do I add an image to Arctos so that I can use it in my collection's header?

**Comment by dustymc** [comment]
Send me your image

**Comment by AJLinn** [comment]
Hey, you were going to do this for me too! Now I need to find those photos I send you!

**Comment by AJLinn** [comment]
![header1ua66-006-0002 2](https://cloud.githubusercontent.com/assets/17605945/25648257/9d163434-2f76-11e7-9ea6-95925098e7aa.jpg)
![header_ua2001-013-0282 2](https://cloud.githubusercontent.com/assets/17605945/25648258/9ee3ccc2-2f76-11e7-9c4a-ab06a6f8d848.jpg)
![header_ua64-021-0134](https://cloud.githubusercontent.com/assets/17605945/25648260/a0c5011e-2f76-11e7-93d3-d5105dd59927.jpg)
![header_sled bag](https://cloud.githubusercontent.com/assets/17605945/25648262/a27d4c1e-2f76-11e7-8e91-e1d2601bfdd1.jpg)
HAHA! I found them! Let me know if any will work for UAMEH!

**Comment by dustymc** [comment]
They are....

create mode 100644 images/uameh1.jpeg
 create mode 100644 images/uameh2.jpeg
 create mode 100644 images/uameh3.jpeg
 create mode 100644 images/uameh4.jpeg

Manage Collection, enter eg /images/uameh1.jpeg in HEADER_IMAGE, fill out the rest of that form, and it should work. To set custom headers you need...

header_color
header_image
collection_url
collection_link_text
institution_url
institution_link_text

I pushed the images to test as well, if you want to play with it there first.

http://arctos-test.tacc.utexas.edu
 i_am_tester 
 seekrut.passwerd123

should let you do about anything - I beautified COA:Bird with one of your images - http://arctos-test.tacc.utexas.edu/guid/COA:Bird:1

**Comment by dustymc** [comment]
I updated http://handbook.arctosdb.org/how_to/How-to-Manage-a-Collection-in-Arctos.html

**Comment by ekrimmel** [comment]
Us too! Us too!

![pnnm_logo_fullcolor_horiz_processc-rgb](https://cloud.githubusercontent.com/assets/11165319/25667805/47786a0a-2fea-11e7-92a5-64811f6ef52f.jpg)

Thanks, Dusty

**Comment by dustymc** [comment]
@ekrimmel  please resize to about 60px high. For reference, here's Arctos with your image in my browser:

<img width="1393" alt="screen shot 2017-05-03 at 8 26 20 am" src="https://cloud.githubusercontent.com/assets/5720791/25668021/42559d28-2fda-11e7-9814-d1f1eb022329.png">

And zoomed out as far as it'll let me zoom:

<img width="1391" alt="screen shot 2017-05-03 at 8 26 38 am" src="https://cloud.githubusercontent.com/assets/5720791/25668033/4d68c6ae-2fda-11e7-85a2-16cb4e626099.png">

(I suppose I could resize or etc., but then users would be dragging around unneeded pixels....)

**Comment by ekrimmel** [comment]
![pnnm_logo_fullcolor_horiz_processc-rgb_sm](https://cloud.githubusercontent.com/assets/11165319/25668854/772827ec-2fed-11e7-8800-6cc49a3b0392.jpg)

Better?

**Comment by dustymc** [comment]
<img width="597" alt="screen shot 2017-05-03 at 8 49 28 am" src="https://cloud.githubusercontent.com/assets/5720791/25669102/71bd3afa-2fdd-11e7-8e80-df75ce710d50.png">

Yup!

It's /images/chas.jpeg
