### ISSUE TITLE
unable to link media through accessions

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1122]
When I try to link media, the form does not give clear directions on how to select media once it has been located. The documents accession link does appear under relationships, but this is obscure. We should make it clear with an "accept" button etc. 
However, even when this relationship is saved under the current form, the link to the media does not show up under the collection.  If I go to media details and click on the accession link, I get "data restricted by collection" even though I have access.

**Comment by campmlc** [comment]
http://arctos.database.museum/media.cfm?action=edit&media_id=10566836

**Comment by campmlc** [comment]
The media I loaded this afternoon have now appeared associated with the accession. What is the reason for the lag time?
I think we should add a note to the interface that there may be a lag, and that the accession may not be immediately available through the link.  Also suggest an "accept" button when media are linked.

**Comment by dustymc** [comment]
>"data restricted by collection"

Yea, I didn't anticipate "us" going from Media to transactions. #1123

>reason for the lag time

#1070 

>suggest an "accept" button 

I'm not sure what/where you're talking about.

**Comment by dustymc** [comment]
updated to new media form
