### ISSUE TITLE
 Add two terms to Taxon status Code table

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1126]
@sharpphyl I moved this here from the documentation issues.

```

We use World Registry of Marine Species (marinespecies.org) as our primary authority for valid taxon. WoRMS uses "accepted" and "unaccepted" as the taxon status. It would be helpful if these terms were added to the six in the Documentation for code table TAXON_STATUS.

Example: http://marinespecies.org/aphia.php?p=taxdetails&id=578734 (unaccepted)
http://marinespecies.org/aphia.php?p=taxdetails&id=403707 (accepted)

We do not need to add the reason the term is unaccepted.

Now that the entries we can make in taxon_status are limited to those in the code table, a dropdown listing those terms would be very helpful.

THX!

```

Suggest doing what WORMS seems to be doing and creating a relationship:

<img width="428" alt="screen shot 2017-05-04 at 4 11 09 pm" src="https://cloud.githubusercontent.com/assets/5720791/25728500/5aa40094-30e4-11e7-914f-c24791672ebf.png">

values are http://arctos.database.museum/info/ctDocumentation.cfm?table=CTTAXON_RELATION, but see #1094 (and the Proposed Terminology tab on the linked spreadsheet, https://docs.google.com/spreadsheets/d/1S9tRAtgJQjCTTYKanxdTTSBouWj3CAZTrBdBh6HwUnE/edit#gid=1820071048)

**Comment by ekrimmel** [comment]
We use WoRMS and its sister MolluscaBase a lot as well. They are great. Where in Arctos does it show or can we edit [CTTAXON_STATUS](http://arctos.database.museum/info/ctDocumentation.cfm?table=CTTAXON_STATUS)? It seems like WoRMS "accepted" should equal "valid species" in CTTAXON_STATUS. 

For WoRMS "unaccepted" I think that fits as "nonpreferred variant of" in the [proposed revised terms](https://docs.google.com/spreadsheets/d/1S9tRAtgJQjCTTYKanxdTTSBouWj3CAZTrBdBh6HwUnE/edit#gid=1820071048) for [CTTAXON_RELATION](http://arctos.database.museum/info/ctDocumentation.cfm?table=CTTAXON_RELATION). I am in favor of CTTAXON_RELATION being a universal vocabulary that we can map to specific taxonomic sources' own vocabularies as need be. E.g. perhaps we could reference the original term (from WoRMS or other taxon authorities) by adding to [CTTAXONOMIC_AUTHORITY](http://arctos.database.museum/info/ctDocumentation.cfm?table=CTTAXONOMIC_AUTHORITY) something like:

**SOURCE_AUTHORITY:** World Register of Marine Species
**Documentation:** World Register of Marine Species (WoRMS), accessible at http://www.marinespecies.org. WoRMS term "unaccepted" maps to Arctos term "nonpreferred variant of."

**Comment by sharpphyl** [comment]
I like what Erica is suggesting.

I'm fine with using "valid species" as the Arctos version of "accepted."

I agree that the more universal descriptors being proposed for
CTTAXON_RELATION are much better than the more specific terms that often
aren't quite right.  Whenever I set up a relationship between an accepted
and unaccepted taxa, I either quote the WoRMS Aphia ID or the URL as the
source.  And I definitely would like to see WoRMS added as a
SOURCE_AUTHORITY.

One last question.  Where does the valid_catalog_term_fg field fit into the
taxonomy description?  Even "unaccepted" taxa may be valid to someone -
just not to me.  Is that only for truly awful taxa such as misspellings
that never should have made it into Arctos?

**Comment by dustymc** [comment]
>Where in Arctos does it show or can we edit CTTAXON_STATUS?

It's a taxon term (http://arctos.database.museum/info/ctDocumentation.cfm?table=CTTAXON_TERM) so top of the edit classification form.

And FWIW I have no idea what we're doing with that table.

>ichnotaxon     A name based on indirect evidence of a fossil organism rather than on the fossil remains of the organism itself.

Sounds like just another name to me!

>nomen dubium     A name that is of unknown or doubtful application. Often, the identity of the type material is questionable. Nomen ambiguum is a synonym.
>nomen nudum     A name published without a description or diagnosis or reference to a description or diagnosis.

MAYBE those belong there, but not at all clear what they'd have to do with a specimen database.

>nomen oblitum     A name which has not been used for more than fifty years after its original proposal, and which has been replaced by a more recent name in common use.

If there's another name involved, there can be a relationship. Relationships can get people where they want to be; taxon terms can just inform them that they're lost.

>species for count     a name representing a species not identified to species level within a region of interest

??????? a species that isn't a species and ??????????

>valid species     a name considered a taxonomically valid species

This seems like it would be the default and cover about 99% of our names - not sure why normal stuff would need flagged??

>universal vocabulary

I'm not sure what the official method for closing Issues is (or should be). A bunch of stuff is stuck behind our waffly relationships, it would be good to somehow resolve that. Are we all in agreement and ready to proceed with my vocabulary suggestions? @DerekSikes @ccicero @campmlc

>CTTAXONOMIC_AUTHORITY

Hmmm, I think I forgot that exists....

Should we clean our data up and add a check to that or drop the authority? 

>quote the WoRMS Aphia ID or the URL as the source

You'd have to find someplace else for that if we turn the code table on. Maybe "link" or "external link" or something should be it's own term type? Or Arctos should make Media linked to/from taxonomy (eg, from a URL) on the fly?

>valid_catalog_term_fg

It's just sort of always been there. "Was never valid" names should be deleted; if it's in the taxonomy table then someone at some point should have thought it was valid (for something). "We don't like this anymore" (which is all we can assert from taxon terms) has limited utility - from that, a user can tell that someone didn't or maybe still doesn't like this for some reason, and that's it. Relationships tell the user what we do like, why we like the other thing, and gives them a path to the name we're presumably attaching to specimens. I would like to see this and CTTAXON_TERM submerged into relationships.

**Comment by DerekSikes** [comment]
Since valid is a term in our taxon status table we also need 'invalid'

**Comment by dustymc** [comment]
I intend to move valid_catalog_term_fg data to taxon_status as "valid" and, I suppose, "invalid."

I think all versions of "invalid" (=everything except "valid", I think) should be backed up by better data (eg, relationships) but I can't enforce that.

**Comment by sharpphyl** [comment]
True, but for our database, I'll reference a WoRMS URL when I select "invalid" for a taxon status.  Which raises the request made by Erica above to add World Register of Marine Species as a source authority.  At this time, our only option is put the WoRMS URL in the Remarks column.  Can WoRMS be added to the CTTAXONOMIC_AUTHORITY table?

**Comment by dustymc** [comment]
I have two concerns:

1) Operators should find what they want. If some clam has been called "A" and "B" and a collection prefers "A" for whatever reason, operators (eg, students) should get some indication that they should use "A" instead of "B" (eg, when they search for "B" because that's what's scribbled on the label).
2) Ditto users. If I search for "B" I should find "A" without having to guess at whatever it is that made you label your clams "A" instead of "B."

Relationships (in conjunction with some sort of "currently accepted" flag) support both of those use cases; they're capable of getting users where they need to be. Links to external sites (or some value in some taxon metadata field, or anything else) supports neither.

If worms has some sort of sane ....&taxon_name=A URL (and I can't find it if they do), we can magic links to them. If they don't, and if for some reason you see some value in creating links, we can create a new type of label for the link or something. 

I'm fine with worms as a source, but we can't both control source and use it for URLs. I'm not sure we need to control source either - that's a question for the AWG. The current data have no functional value of which I'm aware.

**Comment by sharpphyl** [comment]
If we have WoRMS as a Source, I have no need to use a URL (or Aphia ID) to reference WoRMS.  I'll just select WoRMS and leave it at that.  

As for searching for current and past name (valid at that time but no longer accepted) we don't eliminate the previous name but just to a taxonomic update so users and operators should be able to search for both names within our database.  Of course, that may not work for other collections.  We use "invalid" only if that is the name of WoRMS comment.  In the attached example, they use "unaccepted" which would be fine if "invalid" isn't good for other collections.  

![unaccepted](https://user-images.githubusercontent.com/15368365/28143886-5ccf6efe-6725-11e7-9c76-0c9960c4bff8.PNG)

**Comment by dustymc** [comment]
>WoRMS as a Source

Done. Can I now restrict term "source _authority" to http://arctos.database.museum/info/ctDocumentation.cfm?table=CTTAXONOMIC_AUTHORITY?

>don't eliminate the previous name 

That is of limited value to users. You'd have to assert IDs using all possible names to all specimens (eg, also give new stuff old names) to get users where they need to be, and that still doesn't help your operators.

I don't much care how we say "use this one," but I would like to avoid any terminology which might lead someone to think we're doing anything other than trying to be internally consistent (eg, let's avoid anything that's used in any capacity by any of the Codes).

**Comment by sharpphyl** [comment]
Thanks for adding WoRMS.  We'll use that daily.

I checked WoRMS for terms they use for Taxon Status and found these:

**accepted**
**unaccepted**
**unaccepted (misspelling)**
**unaccepted (synonym)**
unaccepted (Basionym)
unaccepted (unaccepted combination)
unaccepted (spelling mistake)
unaccepted (subjective junior synonym)

There are probably others, but having the first four in bold available in Taxon Status would be helpful for us.

**Comment by sharpphyl** [comment]
Is anything happening to move forward on the discussion to add terms to the TAXON STATUS table?    I'm ignoring that field for now but the top four above would be helpful when trying to establish relationships since they are used extensively by WoRMS.

**Comment by dustymc** [comment]
I still have reservations about this.

If we say some taxa are "accepted" and some are various flavors of "unaccepted," then what is a user to assume about the rest?? That is, I don't see the need for "accepted." Is it necessary? Maybe a definition would help?

I very strongly suspect users will use these various flavors of "unacceptedness" instead of relationships, and then be shocked when they find that the functionality is entirely different. What are you doing and why is it not better done in relationships? I believe these are relationships on WoRMS, if that's our model.

I do believe we need some sort of "use this one for cataloging" "local" flag, but that's a very different thing than what looks like attempting to assert relationships in a field functionally incapable of holding them.

**Comment by dustymc** [comment]
Clasing; see https://github.com/ArctosDB/arctos/issues/1700
