### ISSUE TITLE
Help with reports

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1128]
Can anyone tell me why my invoice report looks fine on the screen, but prints funky?  See attached.
![img_0072 002](https://cloud.githubusercontent.com/assets/5725767/25760997/6fbd84b6-3196-11e7-8f17-a8987ce43143.JPG)

**Comment by dustymc** [comment]
@AdrienneRaniszewski @KyndallH help?

**Comment by KyndallH** [comment]
Are you printing from your internet browser? If so, download it and open it in Adobe before printing.

**Comment by dustymc** [comment]
Is this resolved?
