### ISSUE TITLE
Collection Code definitions

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1133]
Could we have definitions for the codes at http://arctos.database.museum/info/ctDocumentation.cfm?table=CTCOLLECTION_CDE ?

**Comment by dustymc** [comment]
I don't think they can be defined - they don't MEAN anything, they just make specific code table values available.

**Comment by dustymc** [comment]
Updated http://handbook.arctosdb.org/documentation/catalog.html#collection-code
