### ISSUE TITLE
Publication searches

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1134]
Searches for publications often give odd results.  For instance (from my mammal curator):

A search for author Higgins brings up Higgins and MacFadden 2004, but not Higgins and MacFadden 2009. A search for MacFadden does not bring up the 2009 paper, nor does the complete citation. The complete citation plus 2009 in the date field does bring it up.

Any ideas why this happens?

**Comment by dustymc** [comment]
From the documentation:

```
Agent

Matches any agent who has a role in a project or publication. Note that not all publication authors are necessarily entered as Agents, in which case searching by Agent will not find the publication.
```

The 2009 pub has no authors listed - I found it by searching "higgins" in "title or full citation." 

And the 2004 seems to be entered twice - please consolidate the citations and delete one of them.

**Comment by Jegelewicz** [comment]
Check and thanks!
