### ISSUE TITLE
Deleting a project

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1135]
Dr. Harris needs to delete a project and we cannot figure out how to go about doing so.  Any instructions will be greatly appreciated!

**Comment by dustymc** [comment]
- delete/remove dependencies
- delete the thing you're trying to delete

works almost everywhere in Arctos

**Comment by dustymc** [comment]
http://handbook.arctosdb.org/documentation/projects.html#deleting
