### ISSUE TITLE
Using projects to document collection use

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1140]
Although we like the Google Scholar idea proposed by Andy Bentley, it leaves out grey literature.  Within Arctos, we can add those projects that aren't truly "published" (theses and other student work).  Dr. Harris has created a project that summarizes all of our publications related to our Paleo collection.

http://arctos.database.museum/project/utep-biodiversity-collections-citationspaleobiology

I would love to be able to take this information and put it into a beautiful report to present to my department admin.  How difficult would this be?

**Comment by dustymc** [comment]
>leaves out grey literature

And linking usage to specimens, and documenting usage when there's no publication, and documenting how "transactions" (eg, collecting) support other transactions, and documenting how funding those transactions affects other research, and .....

>created a project

Neat! You might also consider eg, retroactively creating loans for that usage and adding them to the project etc. so it can better tie everything together. (Data Loans are a quick way to do that, and can likely hold all the legacy loan data you might have anyway.) http://arctos.database.museum/project/beringian-coevolution-project-bcp has most of the possible links and is a pretty good example of how projects can link seemingly-unrelated transactions.

I can help with the SQL or data or whatever for your report, but it'll likely be stale before the ink is dry (eg, someone will add a citation/re-id a specimen/borrow a used specimen/etc.) and it'll be of limited scope (you can get to most every dark corner of Arctos with a half-dozen clicks from some projects!). Can we (also?) beautify the project page so you can give them a URL?

**Comment by Jegelewicz** [comment]
> Can we (also?) beautify the project page so you can give them a URL?

I guess that's what I want - not a static report, but a way to have this available in its latest form in a way that looks good to someone unfamiliar with Arctos.

**Comment by dustymc** [comment]
>latest form in a way that looks good to someone unfamiliar with Arctos

Sounds good to me, and feedback on how forms SHOULD look or behave is always appreciated. Could you print out and mark up (or whatever method works for you) a project page?

**Comment by Jegelewicz** [comment]
I'll put it on my list....

**Comment by dustymc** [comment]
Just cleaning up - please reopen if necessary.
