### ISSUE TITLE
Add egg measurement attributes

### ISSUE THREAD

**Issue by droberts49** [ArctosDB/arctos#1143]
We need to include some egg measurements for our oology collection and currently there is only a "total length" option. Would you please add an attribute for the width? 

width = the total width of an egg specimen

@ccicero -- do you have any additional thoughts Carla?

**Comment by dustymc** [comment]
"width" is defined as "Width of the specimen." I can add that attribute to Egg if that works (seems reasonable to me!) or we can create a new "egg width" (or whatever) attribute. 

http://arctos.database.museum/info/ctDocumentation.cfm?table=CTATTRIBUTE_TYPE

**Comment by droberts49** [comment]
Sounds good to me, too! Thank you Dusty!


Dawn

 

Dawn Roberts | Director of Collections

The Chicago Academy of Sciences / Peggy Notebaert Nature Museum

2430 North Cannon Drive, Chicago, IL 60614 | www.naturemuseum.org

 

Collections Facility and Office

4001 N Ravenswood Avenue, suite 201, Chicago, IL 60613 | 773-755-5125

 

The Urban Gateway to Nature and Science

**Comment by dustymc** [comment]
Done - might take an hour or so to clear the cache and find its way to the forms.
