### ISSUE TITLE
Multiple log-ins from one user

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1144]
Would it be feasible to have a class of students have a single log-in to Arctos?  In other words, would two students be able to log in at the same time with the same id?  A group of instructors would like to create a single log-in and password for a class to use so that students can't "forget" their individual log-ins.

**Comment by dustymc** [comment]
Is this a public account or do you intend to make it an Operator account?

If public, I don't care, but it's fairly likely to be a confusing experience - lots of environmental variables (like the cache after a search is performed) are linked to users.

If this is an Operator account, it's a Very Bad Idea (mostly for the above - eg, they could change stuff that someone else found and which they can't see!).

Just have them provide an email in their profile and Arctos will send them a new password whenever they need it, or if this is public they can just create a new account when necessary.

??

**Comment by dustymc** [comment]
Just cleaning up - please reopen if necessary.
