### ISSUE TITLE
archive retention policy

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1147]
Editing to make more general. We currently archive ~~everything that's deleted from the specimen bulkloader~~ a bunch of stuff, and it is taking a LOT of disk space.

We need to develop a retention policy and delete some data.

Please advise, AWG.

## BULKLOADER_DELETES

everything that gets deleted from the specimen bulkloader.

## EXIT_LINK

: Log when anyone clicks on Media. Useful for statistics (who's accessing media?) and finding broken links.

UAM@ARCTOS> desc exit_link;
 Name								   Null?    Type
 ----------------------------------------------------------------- -------- --------------------------------------------
 EXIT_LINK_ID							   NOT NULL NUMBER
 USERNAME								    VARCHAR2(255)
 IPADDRESS								    VARCHAR2(255)
 FROM_PAGE								    VARCHAR2(4000)
 TARGET 								    VARCHAR2(4000)
 HTTP_TARGET								    VARCHAR2(255)
 WHEN_DATE								    DATE
 STATUS 								    VARCHAR2(255)

## QUERY_STATS

Creates an entry with specimen queries. Recent (last couple years) should be redundant with other (more complete) logs, which are stored on the OS (and less accessible).

 desc QUERY_STATS
 Name								   Null?    Type
 ----------------------------------------------------------------- -------- --------------------------------------------
 QUERY_ID							   NOT NULL NUMBER
 QUERY_TYPE								    VARCHAR2(10)
 CREATE_DATE								    DATE
 SUM_COUNT								    NUMBER
 USERNAME								    VARCHAR2(30)

## CF_LOG

Logged coldfusion access before 2009; all in OS logs now

UAM@ARCTOS> desc CF_LOG
 Name								   Null?    Type
 ----------------------------------------------------------------- -------- --------------------------------------------
 LOG_ID 							   NOT NULL NUMBER
 USERNAME								    VARCHAR2(255)
 TEMPLATE								    VARCHAR2(255)
 ACCESS_DATE								    DATE
 QUERY_STRING								    VARCHAR2(4000)
 REPORTED_COUNT 							    NUMBER
 REFERRING_URL								    VARCHAR2(4000)

**Comment by jldunnum** [comment]
I guess I don't see the utility of archiving these data at all so if there are some good reasons it would be useful to hear them. There may be rare occasions when something gets screwed up and it would be good to see what was in the bulkloader but we do have our individual loading files that we save until records are in Arctos and checked. Don't think it would bother us to not have those data archived for long.  Maybe a month at most, that would give folks a chance to discover any need to go backwards.


______________________________________________________________

Jonathan L. Dunnum Ph.D.
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by amgunderson** [comment]
I agree with John. I don't see a need for archiving these and I assume they are gone as soon I delete them.

**Comment by ekrimmel** [comment]
+1 to John and Aren on bulkloader files. I think some short-term archiving (one month seems fine to me).

For exit_link, query_stats, and cf_log I guess I also agree with John--I don't understand how we're using them currently so I don't really have an opinion.

**Comment by dustymc** [comment]
I think cf_log is no longer useful, just want to make sure nobody needs and pre-2009 data for some weird reason.

From my perspective, archiving stuff that goes through the bulkloader has been useful in addressing "Arctos ate my data!" type concerns. (Sometimes it really did!) Lacking further input, I'll plan to purge those at 90 days to match the audit log schedule.

Exit links probably needs some more functionality - I'll start a new issue.

**Comment by dustymc** [comment]
bulkloader_deletes will now be trimmed after 90 days.

I'll CSV cf_log and archive it on Corral, where we have a bit more storage capacity and backups don't seem to care about filesize.

Query stats is now #1161.
