### ISSUE TITLE
Collection GUID issue

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1148]
Our collection "UTEP:HerpOS" appears in the portals but I cannot add an accession to it or manage it from the Manage Collections menu (it is not an option I can select).  I need to get some specimen records loaded into this collection ASAP for a loan.  Let me know what needs to be done to allow me access.

Thanks!

**Comment by dustymc** [comment]
log out, log in, you should have it

**Comment by Jegelewicz** [comment]
Thanks!!
