### ISSUE TITLE
Bulkloader acting up

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1151]
I'm trying to bulkload and it keeps hanging up.  I can get my data in, but when I try to make adjustments in the AJAX grid, it locks up when I try to go to the second page. (Note the whirly circle at the bottom left of the page - it has been spinning for 10 minutes)

![screenshot 2017-05-31 14 29 15](https://cloud.githubusercontent.com/assets/5725767/26652578/9b199574-460d-11e7-9fa8-0c44fe8ef3ea.png)

**Comment by dustymc** [comment]
Something is going on with Arctos connectivity - DNS problems maybe. TACC is aware, hopefully it'll be fixed soon.

**Comment by Jegelewicz** [comment]
It just worked for me.  Thanks!
