### ISSUE TITLE
Loan report help

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1152]
I've played a little with the cold fusion reports and I have a working invoice (yay!) but I would like the records to sort first by taxon name then by catalog number.  Can anyone tell me how to make this happen?

**Comment by dustymc** [comment]
what's the name of the report?

**Comment by Jegelewicz** [comment]
UTEP_Loan_Invoice (UTEP_Loan_Invoice.cfr)

**Comment by dustymc** [comment]
I updated your report with what you had and...

```
ORDER BY 
    flat.scientific_name,
    to_number(flat.cat_num)
```

You can string as many ordering terms as you need together, they're processed in order of occurrence. Cat_num is a VARCHAR datatype (to support collections with non-integer catalog numbers), so will sort bitwise: 1,10,11..2... As long as your query returns only numeric catalog numbers, you can run it through to_number() to convert datatypes and it will sort numerically - 1,2,...11....

**Comment by Jegelewicz** [comment]
That's awesome!  The number thing was messing with me too - appreciate you thinking of it.  Now take a look at issue #1128 .  It's still a problem with this report.

**Comment by dustymc** [comment]
Just cleaning up - please reopen if necessary.
