### ISSUE TITLE
Taxonomy

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1155]
I am migrating our plant data and find that I have to add a few taxa.  I can create the new name and pull in the global classifications, but when I try to clone one of them into the Arctos name, I always get an error.  See screen shots.
![screenshot 2017-06-02 09 51 55](https://cloud.githubusercontent.com/assets/5725767/26733876/6dccaabc-4779-11e7-90d4-045477fa1b88.png)
![screenshot 2017-06-02 09 52 19](https://cloud.githubusercontent.com/assets/5725767/26733877/6df3bfb2-4779-11e7-9a94-032a7b4ca164.png)
![screenshot 2017-06-02 09 52 27](https://cloud.githubusercontent.com/assets/5725767/26733875/6dcbf590-4779-11e7-8e6b-54312ce3b65f.png)

**Comment by dustymc** [comment]
I can fix that, but what are you trying to do? Multiple classifications of the same source on a name will generally cause undesirable behavior. (http://arctos.database.museum/name/Tortula%20atrovirens has 5 at the moment.)

**Comment by Jegelewicz** [comment]
I just want a classification within Arctos - otherwise a search by Family will not bring up my specimens.  I kept trying to make that happen and getting the error - but apparently the classifications were being added every time even though I got the error?  I only want one!

**Comment by Jegelewicz** [comment]
But this wasn't the case with Tortula acaulon - which still has no Arctos classification....

**Comment by dustymc** [comment]
form updated
