### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1156]
I'm working on a tutorial for my students and when I try the "Review some sample searches to learn about the power of Arctos." on the Profile management page I get a 404 error.
![screenshot 2017-06-02 11 51 45](https://cloud.githubusercontent.com/assets/5725767/26738106/1c236c6c-478a-11e7-872c-e14e6388f3e2.png)
![screenshot 2017-06-02 11 53 25](https://cloud.githubusercontent.com/assets/5725767/26738105/1c20bc92-478a-11e7-9579-79cd151825e7.png)

**Comment by campmlc** [comment]
Teresa,
 Are you logged in? Does that make a difference?
Mariel

**Comment by dustymc** [comment]
Thanks - I'll point that to https://arctosdb.org/about/quick-tour/ for next release.

>for my students 

Could you make it for anyone and post it to the handbook?

**Comment by Jegelewicz** [comment]
> Are you logged in? Does that make a difference?
 Logged in as a guest

> Could you make it for anyone and post it to the handbook?
I plan to!  I'm actually working on a video tutorial.  Will post as soon as it's done.
