### ISSUE TITLE
Barcodes

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1158]
I'd like to claim some barcodes, but I don't speak SQL.  Here are the series I am looking for:

UTEPROOM100-UTEPROOM299 (to label my rooms)
UTEPENTOC1-UTEPENTOC100 (to label my insect cabinets)
UTEPENTOD1-UTEPENTOD5000 (to label the drawers in the insect cabinets)

In addition to the SQL assistance, if anyone sees that these sequences are a problem (for me or anyone else) please let me know!

**Comment by dustymc** [comment]
```
regexp_like(barcode,'^UTEPROOM[0-9]{3}$') and to_number(substr(barcode,9)) between 1 and 299
```
```regexp_like```

Use regular expressions in SQL

```barcode```

the thing against which the reqex will run


```^```

"starts with"

```
UTEPROOM
```
just a string - anything that's not "UTEPROOM" won't make it through

```[0-9]```

then some number-character

```
{3}
```

three of them 

- _"{1,3}" would get "1,2,or three occurrences" "{,3}" would include zero in that, "{3,4}" goes the other way)_

That's probably really all you need, but it'll allow for UTEPROOM999 and maybe it's worth it to keep tighter control on that sort of thing, so....

```
 and to_number(substr(barcode,9))
```

From the  9th character of the barcode to the end...

``` to_number```

convert datatype

```between 1 and 299```

and check that, which is just what it sounds like.

**Comment by Jegelewicz** [comment]
Awesome!  Thank you for the tutorial!!!

**Comment by dustymc** [comment]
Glad it was useful - now also at http://handbook.arctosdb.org/documentation/container.html#barcode-series

**Comment by dustymc** [comment]
Just cleaning up - please reopen if necessary.
