### ISSUE TITLE
Search issue

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1159]
I just performed a search for "=Canis lupus" on the main search page in the Any Taxon, ID, Common Name search field (I was not logged in) and the following were included in the results (among others beginning with Canis)

Canis familiaris
Canis lupus nubilis
Canis rufus

Shouldn't the "=Canis lupus" ONLY return Canis lupus?

The addition of the "=" works when I search in the Identification field.  I just want to make sure that it isn't supposed to work in the Any Taxon, ID, Common Name field and if so is there some way to tell people that?

**Comment by dustymc** [comment]
>Shouldn't the "=Canis lupus" ONLY return Canis lupus?

That is what happens.

http://arctos.database.museum/name/Canis%20familiaris

splat-F "Canis lupus"

<img width="608" alt="screen shot 2017-06-06 at 10 25 37 am" src="https://user-images.githubusercontent.com/5720791/26842681-852f4f1c-4aa2-11e7-9600-c70913a81a8b.png">

etc.

That is, someone has asserted through classifications that some taxon is an exact string match with whatever you typed. The = prefix would not match on  **Canis lupus familiaris** (infraspecies) [ more like this term ] [ including rank ] [ from this source ] (but it's already found an exact match so doesn't have to)

**Comment by Jegelewicz** [comment]
Well, I'll be - those damned taxonomists!

**Comment by dustymc** [comment]
Just cleaning up - please reopen if necessary.
