### ISSUE TITLE
Introduction to Arctos screencast

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1160]
This is a very basic introduction to Arctos - I intend it to be the first of many short tutorials that I can use with students.  Take a look and let me know if anything is completely wrong.  It's not perfect, but I hope it will be useful!

https://youtu.be/XQwXw0e9w-E

By the way, one thing that stood out to me as I made this was that the list of codes on the portal page is very cryptic.  Would it be possible to have the name of the institution pop up when you scroll over the code?  Just a thought...

**Comment by ekrimmel** [comment]
This is great! I really like that you started on arctosdb.org.

We also made a short screencast on searching Arctos (mostly to share with our Education and Exhibits departments), and it kind of takes up where yours leaves off. It's not nearly as polished but I'm going to link the video [here](https://vimeo.com/200364461) for posterity, or in case it's useful.

**Comment by Jegelewicz** [comment]
Yes!  That was basically my next step.  I also plan to make one to help people create a login and then delve deeper into the search functions.  I wonder if there is an interest in creating an Arctos YouTube Channel?  Or since yours is on Vimeo is that a better platform?  I plan to share my screencasts with a lot of students both at UTEP and elsewhere as I am working with a team of educators to create classroom modules that make use of biodiversity data.  Those will all be shared as well as part of the Biodiversity Literacy in Undergraduate Education program.
http://biodiversityliteracy.com/

**Comment by ekrimmel** [comment]
Awesome! I would be interested in having an Arctos YouTube channel (and I have no preference for Vimeo over YouTube); I think others would too. I'd be happy to help in whatever way I can with something like this.

@tigerhawkvok / @dustymc Can we embed videos hosted on YouTube in the Arctos Handbook markdown files, for any future videos that are relevant to existing pages?

Theresa, you are working with Anna Monfils on the BLUE stuff? I was just talking to her about it. Will be great to have Arctos-related materials created and shared through that group, and hopefully integrated with/building on the previously created AIM-UP modules.

**Comment by dustymc** [comment]
Nice!

@mkoo can these be added to https://arctosdb.org/ ?

>Arctos YouTube Channel

https://www.youtube.com/channel/UCoSCkXhrjG-mwLFYRqjNyJA

We did a few years back when we first talked about video tutorials, but then everybody got bored and wandered off.  I'm happy to do whatever to help. Having the vids all somehow together seems useful, but I'm not sure its possible across platforms??

> list of codes on the portal 

Issue, I think. Spelling things out is going to require a lot more screen real estate which is probably going to require a redesign. I'm not really attached to anything there, always up for better ideas!

**Comment by ekrimmel** [comment]
> but I'm not sure its possible across platforms??

I'll just move ours to YouTube

**Comment by dustymc** [comment]
>embed videos 

Not really, but https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#videos

[![clickypop](http://img.youtube.com/vi/XQwXw0e9w-E/0.jpg)](http://www.youtube.com/watch?v=XQwXw0e9w-E)

```
[![clickypop](http://img.youtube.com/vi/XQwXw0e9w-E/0.jpg)](http://www.youtube.com/watch?v=XQwXw0e9w-E)
```

**Comment by Jegelewicz** [comment]
@ekrimmel yes! I am part of a Faculty Mentoring Network with Anna.  Spreading the Arctos love!

**Comment by mkoo** [comment]
Sorry late to conversation-- these are great!

yeah maybe cant do so in the handbook but can do so in arctosdb.org-- I
think that was where Carla envisioned it too.

Youtube has a lot of video editing tools now too so that's great to have a
dedicated channel for this sort of thing.

**Comment by Jegelewicz** [comment]
New Arctos tutorial published today on creating an Arctos user account: https://youtu.be/jqREFoV_jI8

Please add to Arctos Channel (if I can do this on my own, just send instructions...)

**Comment by Jegelewicz** [comment]
Also, When I search "Arctos" on YouTube some pretty random stuff shows up and even a search of Arctos Database never turns up the channel in the results.  Anyone know what gives or how we can make that better?

**Comment by mkoo** [comment]
Once I get credentials to that YouTube acct we can set up SEO and other
things to better search results.
