### ISSUE TITLE
parts bulkload/parts to containers issue

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1163]
I need to be able to bulkload thousands of legacy parts to new barcodes. In many cases what is written on the cryovial is not the same part type as what is in the catalog record, so I can't use Parts-->Containers.

Another option is to use the parts bulkloader with the "use_existing" function, so that I create new parts if they don't already exist and are not already in a container. However,  if a part of the same type exists and is in container,  I get an error message that "single-row subquery returns more than one row". 
This may be because: 
1) Parts already exist with this barcode? If so, it would be helpful if parts that already exist that are being put into the same container could be ignored, and the remaining records loaded.  

2) loan subsamples are causing problems? E.g. two parts of the same type, but with different dispostions.  I need to be able to add barcodes to parts that have dispostion "being processed" or "in collection" but excluding any subsamples that have disposition "on loan".

3) In general, since I am having to process so many thousands of records, it would be extremely helpful if the bulkloader would load validated records but return a downloadable csv of problem records. The current scenario is the entire file is rejected and we must sort through to try to figure out problems - needle in a haystack.

Has anyone else tried to do this?

**Comment by campmlc** [comment]
Here is an example file that gives the single row query error.
[parts bulkload use existing-test.xlsx](https://github.com/ArctosDB/arctos/files/1059643/parts.bulkload.use.existing-test.xlsx)

**Comment by dustymc** [comment]
You found a bug - it should be squashed and patched in.

>Parts already exist with this barcode?

Those will be ignored. "NOTE: You can only use existing parts when that part is not in a container." (And "ignored" here may lead to duplicate parts; the part bulkloader is dangerous if you're dealing with might-already-be-barcoded parts.)

>two parts of the same type

That will cause what about you're seeing, but for different reasons. The bulkloader can make no attempt to guess at which of those 17 liver samples you've barcoded.

>load validated records but return a downloadable csv of problem records. 

Certainly possible, but sounds like a recipe for a giant mess to me. Bulkloaders that either entirely fail or entirely succeed just generally cause fewer problems.

I should be able to figure out how to report errors back to individual records and let you download everything including that. Or we can go with the "load what'll load" approach if taking that path seems critical.

This may be a good candidate for a SQL update, so we can deal with the weirdness more individually.

**Comment by campmlc** [comment]
I am still getting the same error message when I click validate. I need a
way to determine which records are causing this problem. This is a
relatively small file, so I can go one by one and try to track down which
parts might be duplicates that could be causing a problem, but if so, I
might as well load all of the barcodes individually using Object+Barcode to
Container.

If a SQL update would help, that would be wonderful. I really need to be
able to use the Part Bulkloader or Part to Container bulkloader to deal
with much larger files to start inputing the 20,000+ parts with new
barcodes we have added over the past two years, and the upcoming additional
50,000+  we expect over the next two years. Both of these tools currently
have issues that make them unusable for my application. And one of the
primary issues is the inability to mark to load valid records and get a
download of problem records. Currently we can do this with the main Arctos
bulkloader.

**Comment by campmlc** [comment]
I used object + barcode to container to add barcodes to possible duplicate
parts individually. This is an updated file with what I believe, but cannot
confirm without looking at each one individally, to contain unique parts.
I'm still getting same error message.

**Comment by dustymc** [comment]
I missed a button - the stuff you had in there last night should work now. But....

>load all of the barcodes individually using Object+Barcode to Container.

Well maybe not THAT form, but whatever happened to stick a barcode on - the time when the tube was RIGHT THERE - might have been/could be part of a process. There are dozens of specialty tools floating around Arctos, they're generally pretty easy to build, and they can save a lot of work (and prevent a lot of frustration).

I'll try to get better error reporting worked in ASAP, but that form was not (and probably cannot be) built to deal with the possibility of being pointed at something that's already in object tracking - it'll just make more duplicates (and trip on them the next go). I think SQL updates are probably better for this situation.

**Comment by dustymc** [comment]
Better error checking patched in
