### ISSUE TITLE
Identifier Prefix -ID spaces

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1166]
When updating identifiers in arctos and saving changes the space between the prefix (BRR) and the ID number is removed. Therefore the record starts as BRR 3571 but then changes to BRR3571. So when I am updating legacy records that are written originally with a space they will not bulk-load to records without a space.

Also, removing spaces or - can be an issue too. We have numbers that are LFA-98-16 and I need to upload them as LFA 98-16. But when I change the record it saves as LFA98-16, which won't load my original identifier.

Even if we had a space in the prefix, the next time someone enters the record and saves Identifier changes, it retroactively removes any spaces from all the identifiers.

**Comment by dustymc** [comment]
Fixed and patched in. #1167
