### ISSUE TITLE
request markdown capabilities

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#1168]
Due to the extensive narrative descriptions used by UAMEH in attributes (specifically in the description attribute and the newly requested user-contributed comments), specimen remarks, and part condition, I would like to request markdown capabilities in these fields. This should help with readability in these fields.

See for example:
Long condition: [https://arctos.database.museum/guid/UAM:EH:2002-0001]()
Long description: [https://arctos.database.museum/guid/UAM:EH:UA2015-018-0001AU]()
Long remarks: [https://arctos.database.museum/guid/UAM:EH:2003-0001]([]())

**Comment by dustymc** [comment]
#1171 also serves as a request for markdown in code table definitions (eg, to include images).

Markdown contains linefeed characters (in our current definition - that may need expanded), which may break DWC consumers (GBIF etc.). The DWC data is extracted through a direct DB connection, so it would be up to whoever's replaced Laura to deal with that.

All of the requested fields are searchable, and allowing .md may interfere with that - "some term" will not match "some{markdown-formatting-here}term" data even though the two values may look the same in most UIs.

Code table definitions are used by various apps which may not be capable of rendering markdown, and local displays (eg, the "define" links scattered throughout the forms) may be overwhelmed by including "large" data (eg, readable-sized map).

Please advise, AWG - how do we balance those costs/concerns with the stated needs?

**Comment by dustymc** [comment]
Tabling pending advice from AWG.
