### ISSUE TITLE
North American culture areas for CT_CULTURE

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#1171]
see #1106 
I've created a table of Cultures with documentation and references for the North American culture areas. Hopefully this will be usable for all EH and ARC collections when we only have a guess about a region. Care to weigh in @ekrimmel @samuelhowes24 @dustymc ?

[CT_CULTURE 2017.06.07 additions.xlsx](https://github.com/ArctosDB/arctos/files/1065462/CT_CULTURE.2017.06.07.additions.xlsx)

![image](https://user-images.githubusercontent.com/17605945/26998090-2db2e69a-4d2c-11e7-89cf-4233892c70ae.png)

**Comment by samuelhowes24** [comment]
For the U.S. and western parts of Canada, this looks good. Are there similar areas you found for cultures in eastern/central Canada or Mexico? At least for our collection, there are objects like animal figurines and mastates which originated in Mexico, but are not yet associated with a specific culture. The Museum of the American Indian's page [http://www.nmai.si.edu/searchcollections/peoplescultures.aspx](url) is one of the few that I have found that effectively uses searchable culture areas for both North and South America. It's definitely worth a look. I'm currently looking into culture areas for Africa, and will get back to this thread when I have more to share.

Also, I'm wondering whether culture area should be a separate attribute. I've been looking at a few searchable museum databases (AMNH is a good example [https://anthro.amnh.org/collections](url) ), and they all seem to sort by continent and country, and then go immediately to culture. Would it be a good idea from a user standpoint if culture area were treated as a totally separate attribute, or maybe a subset of locality that you can pick from a drop-down menu? Then you could just list culture of origin/use as "unknown" and leave it at that. 

It may also be good to include some kind of image or map to go along with all of these descriptions.

**Comment by dustymc** [comment]
>this looks good.

Just let me know when ya'll want it in the code tables - certainly looks fine to me, whatever that's worth....

> separate attribute

Seems confusing. That'd be something like having a separate field for "identified to family" and users would have to guess what we know to find what they want. Like IDs, you can have any number of these assertions, each to any precision, and users can find them all in one place. (We also have three ways of giving age and good reasons for it - wouldn't be hard to convince me I'm wrong on this, that's just my first impression...)

>subset of locality

Only if I can bring you an object from {3d space} and you can unambiguously tell me culture. (Same from 4D space might convince me culture is a child of collecting events. Neither seems likely to align with how people work???)

>culture of origin/use as "unknown"

There is an expected difference between doing nothing and asserting unknown. "Unknown" comes with the implication that someone (should be listed in determiner) has looked at the thing in some reasonable detail (given in method, hopefully) and has no idea what they're looking at. If nobody's gone to that effort - if you just don't know - then just don't create the attribute. 

> image or map 

Put in in the definitions (seems like maybe a good place to markdown-ify....) for now, I think. If you have WKT maybe we could make "countries" or something.... (AHA!, maybe. "Geography" is Arctos' sometimes-political "someone probably called it this at some point" node, [which also has spatial capabilities] while Localities are (mostly) spatial. http://handbook.arctosdb.org/documentation/higher-geography.html#country. There might be "subset of locality" functionality in that.)

**Comment by AJLinn** [comment]
> 

> 
>     subset of locality
> 
> Only if I can bring you an object from {3d space} and you can unambiguously tell me culture. (Same from 4D space might convince me culture is a child of collecting events. Neither seems likely to align with how people work???)

I can think of many scenarios where this wouldn't work in the more modern sense, if we're talking about locking in cultures and locality - many time folks move from the "traditional territory" of their culture but keep making items in the manner of their home. For example, an Iñupiaq baleen basket maker moves from his home in Barrow (Utqiagvik) to Fairbanks, which is Tanana Athabascan territory. If culture/culture area was locked to locality, then I wouldn't be able to properly attribute the Iñupiaq culture (with a home-base in the Arctic culture area) with an object made in Fairbanks (located in the Subarctic culture area).

I can see myself using the culture area as an additional culture of origin/use value, in addition to the more specific cultures. It makes sense for helping to understand the overall distribution of the collection. I agree that I don't think it needs to be a separate attribute.


> 
>     culture of origin/use as "unknown"
> 
> There is an expected difference between doing nothing and asserting unknown. "Unknown" comes with the implication that someone (should be listed in determiner) has looked at the thing in some reasonable detail (given in method, hopefully) and has no idea what they're looking at. If nobody's gone to that effort - if you just don't know - then just don't create the attribute.

Yes, exactly. An important distinction.


> 
>     image or map
> 
> Put in in the definitions (seems like maybe a good place to markdown-ify....) for now, I think. If you have WKT maybe we could make "countries" or something.... (AHA!, maybe. "Geography" is Arctos' sometimes-political "someone probably called it this at some point" node, [which also has spatial capabilities] while Localities are (mostly) spatial. http://handbook.arctosdb.org/documentation/higher-geography.html#country. There might be "subset of locality" functionality in that.)

I agree I would love to have a map of the culture areas for reference.
![image](https://user-images.githubusercontent.com/17605945/27005120-37a88e46-4dc4-11e7-9d52-4bb69b4d754a.png)

I'll work this next week on doing Mexico/Central/South America. I think I remember seeing a graphic like the North American culture area that I can use as a starting point. Central and Eastern Canada are included in the Arctic and Subarctic culture areas.

**Comment by samuelhowes24** [comment]
Ok so here is what I have so far for African culture areas. Most of the sources I read looked pretty similar to the image of the Herskovitz map I attached at the bottom. As will all culture areas, the borders are fuzzy,
 but this should be a good start. Thoughts, @AJLinn ?

[Culture Areas Africa.xlsx](https://github.com/ArctosDB/arctos/files/1072499/Culture.Areas.Africa.xlsx)

![herskovitz_cultureareas_africa](https://user-images.githubusercontent.com/27777501/27098405-00549964-503d-11e7-9a1b-189bc20bd973.gif)

**Comment by AJLinn** [comment]
Looks great to me. Nicely done.
I'll have the Central/South America list done either today or tomorrow.

**Comment by mkoo** [comment]
If someone points me to a shapefile or some kind of GIS data I can make WKT
versions and upload or pass to Dusty in a batch for Arctos.

**Comment by dustymc** [comment]
Has this fallen through the cracks?

**Comment by mkoo** [comment]
this issue evolved into a geography request, which deserves its own issue (and more likely I'll pay attention!) and might be feasible in the mapping work next year.

Is this CT implemented and can be closed @dustymc @AJLinn ?
