### ISSUE TITLE
Request addition of culture for Arc/EH

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1172]
Mogollon -  indigenous peoples from Southern New Mexico and Arizona, Northern Sonora and Chihuahua, and Western Texas - https://en.wikipedia.org/wiki/Mogollon_culture?

**Comment by Jegelewicz** [comment]
Can we get this added or is it problematic?

**Comment by AJLinn** [comment]
Seems fine to me. I have no problem with having it added.

**Comment by AJLinn** [comment]
That being said, we need to be sure it's noted that it's an "archaeological culture" rather than a living group in present time. I would recommend adding the dates noted in the Wikipedia entry for dates when the culture flourished (ca. 200 CE to 1540).

**Comment by Jegelewicz** [comment]
I'm good with that.

Mogollon - archaeological culture (ca. 200 CE to 1540) of indigenous peoples from Southern New Mexico and Arizona, Northern Sonora and Chihuahua, and Western Texas - https://en.wikipedia.org/wiki/Mogollon_culture?

**Comment by dustymc** [comment]
done
