### ISSUE TITLE
Request for some multiple collection portals

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1173]
Can UTEP have the following multi-collection portals added?

UTEP Amphibians and Reptiles (includes UTEP:Herp, UTEP:HerpOS, and UTEPObs:Herp)
UTEP Entomology (includes UTEP:Ento and UTEPObs:Ento)

Thanks!

**Comment by lkvoong** [comment]
I created two new portals for all UTEP Herp collections and all UTEP Ento collections:

http://arctos.database.museum/utep_all_herp
http://arctos.database.museum/utep_all_ento

Let me know if anything is amiss.

Thanks,

Lam
