### ISSUE TITLE
VertNet, SeiNet, GBIF, iDigBio, etc.

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1176]
I want to have our Arctos data published to the sites listed above (and probably others in the future), but I am finding it most frustrating.  Just when I get one thing working, the others will fall off the radar or end up with outdated metadata or record sets.  As a community, can we make this process easier for ourselves?  Does anyone have the secret to making this simple?  Have I missed something in the documentation that will help me publish without updating 10 different websites?

All ideas and help are appreciated.

**Comment by campmlc** [comment]
This would be a good thing to have on the agenda for today's meeting.
Mariel

**Comment by Jegelewicz** [comment]
Agree!  I wanted to add, but didn't have access to the Google Doc.  I am going to try to join remotely.

**Comment by ekrimmel** [comment]
We didn't really cover this at the meeting last week, but it's a pet peeve of mine as well. Currently, I just have a word doc where I keep track of what metadata is where. In the future I think we should consider how Arctos can help us manage this information, because I think it could do so quite well.

Here's an example of how I track our collection-level metadata. I try to always update/copy-and-paste info from this to the IPT/GRBio/etc. Far from perfect, far from efficient, but...

![metadata](https://user-images.githubusercontent.com/11165319/27549685-68579a3c-5a62-11e7-9ed5-a9d25950398c.JPG)

**Comment by ekrimmel** [comment]
Addendum to above: some of this standard collection-level metadata would be better generated by Arctos, e.g. it would be easy for Arctos to automatically add information about size, or the top ten collectors, etc.

**Comment by dustymc** [comment]
Agreed!

There is a report under Reports/IPT.... - I could make that available as a webservice or etc., "IPT" (or the "portals" or something) would just need to use it. 

Related, IPT should be pushing statistics (and annotations, and ...) back to us. I can set up "whateverPortal," populate it with your data (http://ipt.vertnet.org:8080/ipt/), and not tell you what happens from there, or provide you with statistics that don't really line up with anyone else's statistics (what usually happens now), or serve old data, or ....

I could easily set up the infrastructure to accept those data back into Arctos, but nobody's pushing them.

We ("providers") need to somehow work closer with the IPT and/or "portal" folks.

**Comment by Jegelewicz** [comment]
@ekrimmel Do you sleep? I love your organizational ideas!  I agree that something like what you have within Arctos. which includes the "single source of truth" about our collections would be fantastic.  Honestly, if I were to be hit by a bus tomorrow, I don't think anyone would know where/how to publish all of our data. Even if I was as organized as you, there are also different steps to be taken to ensure that each of these publications are up to date (which change almost every time I go to update).  Just keeping up with what has been updated and when is an issue.  And last of all, I get zero response out of VertNet for anything, so nothing is happening there which means that GBIF is also out of date.  It can take a whole day out every month just checking up on these things and correcting any issues.  @dustymc  I am looking for streamlining that means I put it in Arctos and everyone else just picks it up from there! (I know that I dream big....).  I want the push back from IPT and others eventually, but right now I am more concerned that my data is being published in a timely manner and is consistent across all providers without me spending a day of every month following up.

**Comment by Jegelewicz** [comment]
I think we have accomplished this with the EML generator, closing.
