### ISSUE TITLE
unable to connect

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#1177]
Is Arctos broken at 1:33pm Alaska time? "Unable to connect" according to our browsers.

**Comment by Jegelewicz** [comment]
Same in El Paso.

**Comment by mkoo** [comment]
I just sent an email to our TACC contact...

**Comment by AJLinn** [comment]
Yay! it's fixed!!!

**Comment by AJLinn** [comment]
Well... sort of. Still getting some errors and dropped connections.

**Comment by mkoo** [comment]
Yes, it was rebooted by Chris Jordan at TACC!
hooray indeed!

**Comment by AJLinn** [comment]
Looks like the media upload from specimen records is having some hiccups also after the reboot.

**Comment by AJLinn** [comment]
And we're dead in the water again... Friday at 9:45am Alaska time. I'll email Chris Jordan.
