### ISSUE TITLE
Fix Create Taxonomy bug

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#1178]
This is the second week we've had this BUG.  Taxa are created accurately, but each step receives an error message and we have to create every taxon manually. 

1.  Refresh/pull Global Names creates this error message:

coming in loop: jsfail=true

http://resolver.globalnames.org/name_resolvers.json?names=Mesodon altivagus
	An error occurred while processing this page!
Element RESPONSEHEADER.STATUS is undefined in CFHTTP.

This message has been logged. Please contact us with any information that might help us to resolve this problem.
[ Link to home page. ]

    Data Providers
    Report a bug or request support 

2.  After creating the taxon manually and saving, the following error message appears:

An error occurred while processing this page!
Variable TAXON_NAME_ID is undefined.

This message has been logged. Please contact us with any information that might help us to resolve this problem.
[ Link to home page. ]
Data Providers
Report a bug or request support
View in mobile site

​3.  However, a search for the taxon shows that it was correctly created and can be used with a new entry.  So the system works but it's very time consuming and prone to error.

Note:  The error messages don't appear if you clone an existing taxon.

**Comment by dustymc** [comment]
It's working for me, but lots of errors logged - temporary glitch in GlobalNames? Reopen with specifics if this is still a problem.

**Comment by sharpphyl** [comment]
Yep, it's working again.  Must have been a GlobalNames issue as it was not
working for two weeks.

BTW, why doesn't  GN upload the author anymore??
