### ISSUE TITLE
Higher Geography field on specimen search form?

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#1179]
I'm starting to use higher geography to tag National Parks. For instance:

Higher Geography:     North America, United States, Alaska, Denali National Park

for all those from Denali NP.

However, there doesn't appear to be a 'Higher Geography' search field on the search form. There are a lot of search fields I never use (eg Geographic Feature - what is that?)

Searching "any Geographic feature ' for 'Denali National Park' doesn't work - it finds lots of things outside the park.

what am I doing wrong? Or can 'Higher Geography' be added as a search field on the form?

**Comment by dustymc** [comment]
>(eg Geographic Feature - what is that?)

http://handbook.arctosdb.org/documentation/higher-geography.html#geographic-feature

Probably what you're looking for!

You can use Search/Geography to see the components of higher geog - eg, https://arctos.database.museum/geography.cfm?higher_geog=Denali%20National%20Park

>can 'Higher Geography' be added as a search field

It can, but it's redundant with the individual concepts (eg, feature) which are already there.
