### ISSUE TITLE
Give UAM:EH & UAM:Arc ability to create new parts in Object+BC>>Container

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#1180]
We're starting to Move Containers and put collection objects into containers. Currently when I try to make a  New Part, this is what I see:
![screenshot 2017-06-27 13 46 27](https://user-images.githubusercontent.com/17605945/27750273-8f1109aa-5d83-11e7-9e3c-2decbce19a50.png)
This is what I'd like to see:
![screenshot 2017-06-27 13 45 46](https://user-images.githubusercontent.com/17605945/27750277-97580884-5d83-11e7-9736-8c6202090eab.png)
Can you please do whatever needs to be done for both UAM:EH and UAM:Arc to do this?
Thanks,
angie

**Comment by dustymc** [comment]
Looks like a problem with non-numeric catalog numbers.

**Comment by dustymc** [comment]
done for next release
