### ISSUE TITLE
Make "not case sensitive"

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#1181]
Please change the ID Number field on the Object+BC>>Container form to be not case sensitive. It currently is case sensitive and delivers an error message / red border if "ua94-004-0039" is used instead of "UA94-004-0039"

![screenshot 2017-06-30 13 48 27](https://user-images.githubusercontent.com/17605945/27755223-d12dc618-5d9a-11e7-9f57-43d3e051f7df.jpeg)

**Comment by dustymc** [comment]
done for next release
