### ISSUE TITLE
Add "Part Location" to Custom Fields

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#1182]
Would it be possible to add "Part Location" to the list of things that can be checked on/off in the "Customize results and downloads" popup window?

I'd love to be able to "turn off" the Decimal Latitude, Decimal Longitude, Coordinate Error, and Sex (none of these are important for my search results and are just taking up space), while a flattened version of "Part Location" would be extraordinarily valuable in helping us work in the collections range without having to open every record, or to manually add locations to the csv file that we produce from downloading results, or to print the search results.

**Comment by dustymc** [comment]
As an individual thing, not really - in results, it's a denormalization of a denormalization.

I think I can add it to part detail and better format that (eg, as a table) which should (almost?) do what you want, and would address some similar issues elsewhere.

I moved the rest to #1185

**Comment by dustymc** [comment]
Added "container_path" to partdetail, formatted part detail as verbose JSON, "pretty print" formatted that for display - please test (http://arctos-test.tacc.utexas.edu).

About 500 records (mostly fish) require >4K characters to JSONify part details. Making the field CLOB would be a fair bit of work, and would almost certainly break everything involved in sharing via DWC. Those records currently have partdetail of 

```
{"error":"see specimen detail page"}
```

Examples:

<img width="551" alt="screen shot 2017-07-07 at 8 09 46 am" src="https://user-images.githubusercontent.com/5720791/27964033-aeff65dc-62eb-11e7-887d-8fcf94f623b5.png">

<img width="451" alt="screen shot 2017-07-07 at 8 11 03 am" src="https://user-images.githubusercontent.com/5720791/27964074-da1a13ca-62eb-11e7-99ca-4b706d627e95.png">

Pending feedback, this should move to prod next week.

**Comment by AJLinn** [comment]
Interesting! Is it possible for you @dustymc  to put some of the UAM:EH records into the test module so we can see what happens when there is a large amount of text in the condition field? Just curious as to how this will look with the info we currently put in the part fields. I like being able to see the flattened location right there though!

**Comment by dustymc** [comment]
Test was recovered from production data a couple weeks back, so most of your data should be there.

http://arctos-test.tacc.utexas.edu/SpecimenResults.cfm?guid=UAM%3AEH%3A2002-0001 for example.

The "pretty print" thing is native JS (so controlled by your browser) - in my setup it doesn't wrap, which is probably either awesome or evil depending on what you're trying to see at the moment....

<img width="1361" alt="screen shot 2017-07-07 at 3 15 43 pm" src="https://user-images.githubusercontent.com/5720791/27978910-2ef1ce7a-6327-11e7-9887-b0aabc505eda.png">

**Comment by AJLinn** [comment]
here are the records I have access to:
![screenshot 2017-07-07 17 39 52](https://user-images.githubusercontent.com/17605945/27979405-7a814cee-633b-11e7-8726-d25ef5c28de4.png)
Am I doing something wrong in the test site?

**Comment by dustymc** [comment]
I'll give i_am_tester more access. You should be able to log in with your normal/production credentials as well.

**Comment by AJLinn** [comment]
It's lots better than what we have now. But this is what I get in one cell of the spreadsheet when I download results:
![screenshot 2017-07-07 20 07 35](https://user-images.githubusercontent.com/17605945/27981388-e64e01d2-6350-11e7-8283-ea65c6a4d421.png)
Is there any way to "pick out" just the location data? As it stands, I'll need to delete a lot of info in each cell to just show location, BUT it's still 100% faster than going thru and finding the location of each object individually and then entering by hand into the downloaded results.

Overall, I like where its going. If this is what we can do, then I'll take it. If there's any way to pull the location data out, that would be even better.

Thanks for working on this!

**Comment by dustymc** [comment]
>spreadsheet

Yes, JSON is fundamentally just text.

>"pick out" just the location data

You can probably treat JSON as a data object in Excel, somehow. 

I can manipulate it anywhere along the way, but if I do it's very likely to turn in to something that confuses everyone except you. I expect these data to get a lot of use for a lot of reasons by many collections, and I don't think anything except all available data can support that.

I'm starting to suspect that you need a customized something-or-another. What are you trying to do, and what data do you need to do it?

**Comment by AJLinn** [comment]
> I'm starting to suspect that you need a customized something-or-another. What are you trying to do, and what data do you need to do it?

What I'm hoping for with this data is to be able to have the most recent physical location of the object be visible in the search results and to be able to sort the results by that location. When a researcher comes in, we execute a search, then go into the range to pull those objects. By having the most recent location in a column in our search results or downloaded records, we can sort the results by location and more efficiently move through the range to retrieve or view those objects.

[Loan2017-14.EH_List.xlsx](https://github.com/ArctosDB/arctos/files/1146072/Loan2017-14.EH_List.xlsx)
Here's an example of a spreadsheet that I created for a recent research visit. You can see I created a column at the end and had to manually enter the location information by opening each record, copying, and pasting the location data (part attribute : location) into the cell.

So I think the data I need to do the same thing is (or will eventually be) the most recent part location in flattened format. Because our objects have not yet been added to a container barcode, this data is in the part attribute : location field right now.

Is this even possible? Do we need to wait until we get everything barcoded?

Thanks Dusty.

**Comment by dustymc** [comment]
There is a "flatten part location" function that essentially prints directions to barcoded items, so things will get easier/more predictable with barcodes.

As a general solution, this probably isn't practical - predictable data here require context (and that's already in partdetail).  As a not-so-general solution which might occasionally do something weird because it makes a lot of mostly-indefensible assumptions regarding the data, you can now add LastPartLocation to specimenresults. Let me know if it's not useful, you want some other format, or whatever.

That's calling https://github.com/ArctosDB/DDL/blob/master/functions/getLatestPartLocation.sql, which should be available everywhere if that's somehow useful.

**Comment by AJLinn** [comment]
> you can now add LastPartLocation to specimenresults. 

This looks great! I think this will be really useful - thank you. And we're moving forward each day with barcodes, so I think we'll start doing better soon.

Thank you!

**Comment by dustymc** [comment]
http://handbook.arctosdb.org/documentation/parts.html#specimen-results
