### ISSUE TITLE
specimen results - defaults/required fields

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1185]
Split from #1182: 

I'd love to be able to "turn off" the Decimal Latitude, Decimal Longitude, Coordinate Error, and Sex (none of these are important for my search results and are just taking up space), while a flattened version of "Part Location" would be extraordinarily valuable in helping us work in the collections range without having to open every record, or to manually add locations to the csv file that we produce from downloading results, or to print the search results.

**Comment by campmlc** [comment]
I agree that we need a way to download part location from specimen results.
