### ISSUE TITLE
Locality merge duplicates fails

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#1187]
I found all specimens of this accession: 
https://arctos.database.museum/editAccn.cfm?Action=edit&transaction_id=21068920

and then found all localities linked to those specimen records using the manage- locality drop down menu item.

I then searched for duplicates among the localities (over 500 localities) and it found "Found 500 localities, 4 unique "
so I clicked 'merge all' for the first one that had 423 identical duplicate localities and got only a page with '431 - '

on it.

**Comment by dustymc** [comment]
Seems to be an environmental limitation; I'll ask TACC to adjust.

**Comment by dustymc** [comment]
TACC cannot adjust server env to accommodate this, rewriting to bypass those limitations would take ~a day. #865 would make this issue irrelevant (by auto-merging the duplicates), but manual merge to deal with almost-duplicates may be worth retaining as well. I'm unsure how to proceed.

**Comment by jldunnum** [comment]
I vote for auto merge and retaining ability to manually merge others.


______________________________________________________________

Jonathan L. Dunnum Ph.D.
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by dustymc** [comment]
Closing this; starting on #865 (which should make this problem not be a problem).
