### ISSUE TITLE
taxonomy form broken

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#1188]
I created a new name by cloning a classification (clean) and two weird things are happening:

1) I deleted some names in the classification and then added one line, weird thing #1 is columns shift leftward making the open field for editing appear under the term type column rather than the term column.

2) The form auto-suggests a genus name which I don't want because I'm making a suborder name only (no ranks below Suborder in this) so I delete the genus name and then I click save. Upon clicking save, the genus name reappears so I delete it again and press save, at which point it reappears... etc

**Comment by dustymc** [comment]
>columns shift leftward

Screenshot?

**Comment by DerekSikes** [comment]
![screen shot 2017-07-05 at 5 51 12 pm jul 5 17](https://user-images.githubusercontent.com/9099827/27892190-a1f906c8-61aa-11e7-8ebf-4fbaff302373.jpg)

**Comment by dustymc** [comment]
Row-shift thing is fixed for next release.

Re not-actually-genus suggestions: The options seem to be:

1. Do what it does, deal with the slightly-annoying suggestion for the relatively few monomials which are not genera. (And I understand that "relatively few" is still a lot!)
2. Make no suggestions, expect the introduction of inconsistent data which breaks the hierarchical editor.
3. Something clever that I haven't yet discovered - suggestions appreciated.

For context, "breaks the hierarchical editor" is the source of most of the "suggestions" on the single-record edit form. My proposed solution is to deprecate the single-record form and force all updates to the hierarchical editor; the suggestions may have improved the data (or not, I'm not sure) but they certainly have not improved it to the point that it's consistent enough to produce expected results or be predictably transformed into hierarchical data.

As always, comments on #1000 are appreciated.

**Comment by Jegelewicz** [comment]
Pretty sure this is fixed and/or covered by other issues. Closing for now.
