### ISSUE TITLE
slow loading of shapefile? for Arctos specimen record full view

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#1189]
This record:
http://arctos.database.museum/guid/UAM:Ento:352878

and others from the same accession/higher geography all take a long time to load on my setup - the ID and locality frames load fast (but the locality frame has no map) and the frames on the right side of the page (parts, attributes, accession, etc) are not visible. It took 38 seconds for this to load fully.

I'm running up-to-date FireFox 54.0.1 (64-bit) on a Mac with OS 10.10.5, 2.9GHz Intel core i7, 8 GB of 1600 MHz DDR3 Ram.

Maybe users could have a little show/hide preference setting for that google map? If I hide it I expect these pages would load instantly.

**Comment by dustymc** [comment]
Shapefile fetch is asynchronous for next release. The core data should load quickly, on slower connections the map may jump around a bit as it's being incrementally processed.
