### ISSUE TITLE
abandoned media - archived

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1190]
Media which was uploaded to Arctos and has not been used has been removed from the webserver. There is a zip archive on dropbox, https://www.dropbox.com/s/oddolp6v2nj1s99/temp_media_notused.zip?dl=0. Please re-upload (and use in Media) anything you still need, or reply to this issue if I can help with recovery.

**Comment by jldunnum** [comment]
Not sure I understand where these were residing.  Were these linked to accessions or specimen records?  Most appear to be stuff I want linked and accessible.


______________________________________________________________

Jonathan L. Dunnum Ph.D.
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by dustymc** [comment]
They were uploaded to the webserver and not linked to anything. Can you give me an example of something that should be linked?
