### ISSUE TITLE
add CTSex_Cde values to Ento collection

### ISSUE THREAD

**Issue by ekrimmel** [ArctosDB/arctos#1198]
We would like to have the following existing [CTSex_Cde](http://arctos.database.museum/info/ctDocumentation.cfm?table=ctsex_cde&coln=) values added to the Ento collection type:

- not recorded
- recorded as unknown
- sexes mixed

Values would be used as they are for the other collection types that already use them. Thanks!

**Comment by dustymc** [comment]
done

**Comment by ekrimmel** [comment]
thx!
