### ISSUE TITLE
Please add attributes to Teach collections

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1207]
sex
total length
tail length
hind foot with claw
ear from notch
weight
forearm length
mounted skin

Thanks!

**Comment by campmlc** [comment]
Didn't we transfer Host attributes to Teach?

**Comment by Jegelewicz** [comment]
The only one I see there is verbatim collector

**Comment by Jegelewicz** [comment]
Also need mounted skin

**Comment by dustymc** [comment]
@campmlc  no "Teach" is a new collection_cde so it's starting from a blank slate.

@Jegelewicz definition for "forearm length" please?

I assume "mounted skin" is a part? If so see https://github.com/ArctosDB/arctos/issues/1131 - that terminology will change soon, probably Monday, things might be a tiny bit simpler if you can wait for that.

**Comment by campmlc** [comment]
In this case, these attributes already exist for other collections. Can't
new collections just use existing ones for their respective taxonomy groups?

**Comment by dustymc** [comment]
>respective taxonomy groups

There's no such thing - collection_cde is the only control on access to code tables.

FWIW I'm not really sure why the host collection_cde wasn't used, but the discussion is #1157.

**Comment by Jegelewicz** [comment]
@dustymc sorry about mounted skin - yes that's a part.  I can wait until Monday.

forearm length - length of the forelimb between the elbow and wrist
