### ISSUE TITLE
Data entry - C event or Locality ID # not pulling in all data

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#1209]
On the data entry page, in the Pick/Depick Event when you place a Event number in there it doesn't fill up that whole section. All of the collecting event is filled, but only part of the Locality section is filled and nothing happens in the Coordinates section at all. I remember when you used to pick an Event number all of those sections would automatically fill in. Has it been changed so that that is what is supposed to happen now? I think it might not be a display problem, I tried to create a brand new record and entered only a Event number for the locality information. The same thing happened when I picked the Event (only the Collecting event and some of the Locality sections were filled), when I tried saving the record there was a note pop up that said yellow fields couldn't be left blank and that the save was aborted. It works though if you paste a Locality number and Event number into the Pick/Depick Event/Locality, though you have to pick the locality and then the event (in that order) if you want all of the information. 

Seems pasting a locality & then event ID is needed now rather than being able to only paste the event ID and the rest would follow.

**Comment by dustymc** [comment]
Fixed for next release

Added http://handbook.arctosdb.org/documentation/dataentry.html
