### ISSUE TITLE
Add "container type" to Arctos home search page

### ISSUE THREAD

**Issue by KyndallH** [ArctosDB/arctos#1210]
Under the "curatorial" section on the Arctos main search page, we'd like "container type" added.

<img width="794" alt="screen shot 2017-07-24 at 3 45 49 pm" src="https://user-images.githubusercontent.com/16887896/28549720-9aeec5f6-7088-11e7-9841-75ac6b90a8ad.png">

**Comment by dustymc** [comment]
Assigning to GGBN; this is critical to cleaning up parts so we can identify tissues.

**Comment by dustymc** [comment]
<img width="478" alt="screen shot 2017-08-24 at 9 29 29 am" src="https://user-images.githubusercontent.com/5720791/29677046-c01a5bd6-88ae-11e7-8780-914eb0832478.png">
