### ISSUE TITLE
Geography issues

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1212]
Geography search appear not to be working in either Chrome or Firefox, although we can get to localities through specimen detail. Also, some of my students are having trouble with georeferencing in Chrome.

**Comment by AJLinn** [comment]
> Also, some of my students are having trouble with georeferencing in Chrome.

My students were having trouble georefernecing in Firefox from the data entry form as well.

**Comment by campmlc** [comment]
Cancel the former - appears to be student error. I will check again on the Chrome georeferencing problem.

**Comment by dustymc** [comment]
>trouble with georeferencing

What specifically is the problem/how do I re-create it?

**Comment by AJLinn** [comment]
My particular staff's issue was that when she was doing data entry, she filled in the Higher Geography field, she did the specific/verbatim locality, and when she clicked "geolocate" to select the coordinates, the map never loaded.

My student who was working at the computer next to her, however, had no problem with this task. Karinna tried quitting, starting a new record, and it did the same thing. She's not done any additional data entry since then.

**Comment by campmlc** [comment]
Yes, the problem seems to be related to the map not loading.

**Comment by dustymc** [comment]
Thanks. I can't break it but I'll keep trying!

Please grab screenshots (maybe it's some weird combination of/specifics in/etc. the data) and the javascript log (https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Opening_the_Web_Console) if it happens again.

**Comment by campmlc** [comment]
Here are comments from my student on georeferencing in Chrome:

 I cannot get Chrome to work.  Logged in and out to try again - just
spinning - usual pop up page but blank and just spinning.  Firefox so far
ok.  Will try Chome again later.

**Comment by dustymc** [comment]
https://arctosdb.org/faq/

Chrome is not "officially" supported, and in the past we have not had the resources to support all browsers. (I'm happy to change that, but doing so would require more time for developing and re-writing some code.)

**Comment by campmlc** [comment]
We should look into that. Many people are using Chrome preferentially
because of persistent problems with Firefox and Adobe Flah.

**Comment by campmlc** [comment]
Problems with Adobe Flash . . .

**Comment by dustymc** [comment]
There is no Flash in Arctos.

**Comment by campmlc** [comment]
To print loan forms.

**Comment by campmlc** [comment]
Sorry -Shockwave Flash? Anyway, the instability was so severe as to make
using Firefox for anything else unreasonable. Perhaps it is fixed now.

**Comment by dustymc** [comment]
Oh - right. Which loan forms? I can set those to PDF, which needs to happen anyway as Flash is officially being deprecated.

**Comment by campmlc** [comment]
MSB Mammal loan invoice and header, for sure. May be others - I think MSB
Birds was working OK.

**Comment by dustymc** [comment]
>MSB Mammal loan invoice and header

Try it out in test. And we should get those moved to the reporter, so you don't have to rely on changing code to alter your reports.

**Comment by dustymc** [comment]
tentatively closing - please reopen if this continues, there's more info, etc.
