### ISSUE TITLE
code table cleanup: CTAGE_CLASS

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1214]
Definitions are very spotty, arbitrary/overlapping. Not clear what the combined terms are doing in there, why those are not just assigned as multiple attributes.

**Comment by campmlc** [comment]
I think the problem here is that we are really dealing with two separate
but related attributes that are used variably depending on the taxonomic
group and the amount of information available, and the code table isn't
capturing this complexity.  Immature/Mature refers to whether or not an
organism is capable of reproduction, which is usually related to its age
class (but not necessarily consistently in all taxa - some may be
influenced by environmental triggers.)
 Adult/subadult/juvenile/neonate/fetus/embryo usually relate to vertebrate
developmental age classes before and after sexual maturity is reached,
traditionally assessed by morphological, physiological and osteological
characters. Arthropods I assume would have other terms depending on whether
development is incomplete or complete - other taxonomic groups will have
other terms, some of which may or may not overlap with vertebrates.
How we assign an age class or reproductive status to a specimen depends on
the information we have available. We may know that a mouse has embryos,
and therefore can be classed as an adult as well as sexually mature. Or we
may only have dentition to go on. Or we may have some sort of "immature"
but can't assess it's precise age class between juvenile and adult .
 The only way I see to resolve this more fully would be to have "sexual
maturity" as a separate attributte from age class with "mature/immature" as
vocabulary. Thoughts?

**Comment by dustymc** [comment]
http://arctos.database.museum/info/ctDocumentation.cfm?table=CTAGE_CLASS

>"sexual maturity" as a separate attributte from age class

If those data are confounded - if we're doing two things in one place - that's the obvious solution (from a data design standpoint - that doesn't necessarily mean it works when presented with a dead rat!). It's super-easy to spin up new Attributes so let me know if that's where we want to go.

I think we're using the same TERMS for those two things as well. You say an adult "has embryos, and therefore can be classed as an adult", @Jegelewicz says "how do you know a fossil specimen is sexually mature? - by reading the bone structure as detailed above" - using the same term and term-type for both of those things seems very WRONG to me. (Using the same term for two term-types doesn't seem much better!)

I suppose the critical question is, does anyone care? Do people who search the collections looking for reproductive adults want to exclude bone-development adults?

And I think there may be more than two things in here

queen=wandered off from http://arctos.database.museum/info/ctDocumentation.cfm?table=CTCASTE

instar, pupa, larva, chrysalis, cocoon, egg (and, or course, "egg(s)") - weird changey thing (has nothing to do with age/time, at least sometimes)

embryo - weird changey thing that IS related to time (sorta - kangaroos and such might disagree...)

fledgling - feather-stage (??)
over-winter - tooth wear

old adult - arbitrary, same as gerontic?

neonate, nestling, hatchling - same diff?

fourth year - strictly time

not recorded - so don't record it!

sub-adult, subadult - arghh!!

young, immature - seems like a completely arbitrary designation, even if it is probably still useful

I would like to retract my naive "think those are all straightforward and I can figure them out" statement from the other Issue....

**Comment by Jegelewicz** [comment]
Age class is mapping to life stage in DwC.

**Comment by Jegelewicz** [comment]
@ccicero to come back with standards from Bird meeting to help sort these out.

**Comment by dustymc** [comment]
>@Jegelewicz says "how do you know a fossil specimen is sexually mature? - by reading the bone structure as detailed above" 

That should be recorded in https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type&field=skull%20ossification (or something like it), which would need a new name.

I'm elevating priority, if I can figure out how to - we've begun using our messes as an excuse to make more messes, we STILL don't have [documentation](https://github.com/ArctosDB/arctos/issues/1450) for much of this, it's just a mess!

**Comment by dustymc** [comment]
As an easy, obvious, and reversible first step, I propose:

* Create an attribute bulkloader file of the following data, so they can be modified and re-loaded if necessary.
* Move the following data to "age" (which isn't controlled)
* Remove these as authority values
 
 
```
select guid_prefix, attribute_value, count(*) c
arctos-> from
arctos-> attributes
arctos-> inner join cataloged_item on attributes.collection_object_id=cataloged_item.collection_object_id
arctos-> inner join collection on cataloged_item.collection_id=collection.collection_id
arctos-> where attribute_type='age class' and attribute_value in (
arctos(>   'adult, juvenile',
arctos(>   'adult/juvenile',
arctos(>   'adult, pupa',
arctos(>   'adult (queen)',
arctos(>   'adults, larva',
arctos(>   'chrysalis, juvenile shed',
arctos(>   'chrysalis, larva',
arctos(>   'cocoon, larva',
arctos(>   'egg, larva',
arctos(>   'egg(s)',
arctos(>   'exuvium', -- this is a part, no???
arctos(>   'pupal exuvium', -- ditto?
arctos(>   'larva, nymph',
arctos(>   'puparium, larva',
arctos(>   'queen', -- this is caste??
arctos(>   'sub-adult', -- use 'subadult'
arctos(>   'teneral, puparium'
arctos(> )
arctos-> group by guid_prefix, attribute_value
arctos-> order by guid_prefix, attribute_value
arctos-> ;
 guid_prefix |     attribute_value      |   c    
-------------+--------------------------+--------
 CHAS:Ento   | adult, juvenile          |     66
 CHAS:Ento   | adult, pupa              |      1
 CHAS:Mamm   | adult/juvenile           |      2
 DMNS:Herp   | adult/juvenile           |      3
 DMNS:Para   | larva, nymph             |     14
 HWML:Para   | egg(s)                   |      7
 HWML:Para   | larva, nymph             |     44
 KNWR:Ento   | exuvium                  |      4
 KNWR:Ento   | larva, nymph             |      1
 KNWR:Ento   | pupal exuvium            |      1
 KNWR:Ento   | sub-adult                |      6
 KWP:Ento    | adult (queen)            |      1
 KWP:Ento    | pupal exuvium            |      1
 MSB:Mamm    | adult/juvenile           |     11
 MSB:Para    | egg(s)                   |     48
 MSB:Para    | larva, nymph             |     68
 MVZ:Herp    | adult/juvenile           | 234483
 MVZ:Mamm    | adult/juvenile           |     11
 MVZObs:Herp | adult/juvenile           |      1
 NMMNH:Ento  | adults, larva            |      1
 UAM:Ento    | adult, juvenile          |   1942
 UAM:Ento    | adult, pupa              |      5
 UAM:Ento    | adult (queen)            |   1474
 UAM:Ento    | adults, larva            |     57
 UAM:Ento    | chrysalis, juvenile shed |      1
 UAM:Ento    | chrysalis, larva         |      1
 UAM:Ento    | cocoon, larva            |      3
 UAM:Ento    | egg, larva               |     10
 UAM:Ento    | exuvium                  |    133
 UAM:Ento    | larva, nymph             |      5
 UAM:Ento    | pupal exuvium            |      8
 UAM:Ento    | puparium, larva          |      5
 UAM:Ento    | queen                    |      5
 UAM:Ento    | sub-adult                |      5
 UAM:Ento    | teneral, puparium        |      2
 UAMObs:Ento | adult, juvenile          |     10
 UAMObs:Ento | egg, larva               |      1
 UAMObs:Ento | larva, nymph             |      1
 UAMObs:Ento | puparium, larva          |      1
 UAMObs:Ento | queen                    |      1
 UCM:Mamm    | adult/juvenile           |      2
 UTEP:Ento   | queen                    |      5
 UTEP:Ento   | sub-adult                |      7
 UWBM:Herp   | adult/juvenile           |     72
```

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/2881
