### ISSUE TITLE
confirm unique identifier format for Arctor specimen record url

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1216]
I would like to confirm that this is the format to use as the url to create reciprocal linkage to Arctos specimen records:
Taken from the code table documentation for other ID type for MSB Mammals:

 http://arctos.database.museum/guid/MSB:Mamm:

Is http correct or should this be https?

**Comment by dustymc** [comment]
Doesn't matter - they go the same place and there's nothing security-related (eg, no particular reason to prefer https) involved.

**Comment by campmlc** [comment]
Thanks!
