### ISSUE TITLE
add "sexes mixed" value to CTSEX_CDE for Inv collections

### ISSUE THREAD

**Issue by ekrimmel** [ArctosDB/arctos#1218]
Please & thank you!

**Comment by dustymc** [comment]
Done, but...

That's weird and I'm not sure I see the value. Why not just add attributes "male" (and maybe a count/estimate/remark in remarks) and "female" and whatever else you need? A specimen can have any number of attributes. People will find that when they're looking for "female" (and maybe help you sort out the lot). I don't think anyone's ever going to search on "sexes mixed."

@DerekSikes @campmlc ??

**Comment by ekrimmel** [comment]
Agreed that would help searching--I am totally happy to do as you suggest @dustymc

**Comment by campmlc** [comment]
Yes, we have been just adding both sexes as different attributes when we
are dealing with lots, with the number of each sex in remarks. The only
other way to deal with this for lots could be using part attributes, since
the individual organisms become "parts" of a lot. But we would need to add
attributes for this. I think Kyndall and others are putting info on
individuals from a cataloged lot info in part remarks?

**Comment by dustymc** [comment]
Should we get rid of "sexes mixed" or is it useful for something?

```
UAM@ARCTOS> select guid_prefix,count(*) from collection, cataloged_item,attributes where collection.collection_id=cataloged_item.collection_id and cataloged_item.collection_object_id=attributes.collection_object_id and attribute_type='sex' and attribute_value='sexes mixed' group by guid_prefix;

GUID_PREFIX						       COUNT(*)
------------------------------------------------------------ ----------
CHAS:Ento							     97
HWML:Para							    361
MSB:Para							     12

```

@campmlc who's CM at HWML these days?

>lots

I think lots can make sense as "working cataloged items" - they're handy to barcode so you can find stuff and search by taxonomy and all that jazz. As citable items of scientific interest, they have major problems. Arctos can hang whatever off parts via part attributes, but that's a dicey path between eg, citations and the thing that's being cited.

**Comment by campmlc** [comment]
Gabor is at HWML. It would be good to send some of this discussion by Scott.

Lots have a very long history of use, and I can attest that among the fish
community traditional patterns of use are hard to change. Even among
collections that are doing a lot of molecular work, it is the lot that is
cited and the individual remains a part. Then you have parts of parts of
parts, eg liver subsample of liver of fish which is part of a lot.
I insisted in having different catalog numbers to assign to frozen fish
taken from a lot for genetic use, and it caused much grief for all parties
involved. I don't see this as a viable alternative any time soon on a broad
scale. We can provide a workable alternative but entrenched protocol is
difficult to change.

I think in the context of lots that eliminating sexes mixed would help with
searches, certainly, but would require retraining for existing collections
and good communication and documentation for new ones. It is not intuitive
to use two attributes.

Or, allow users to select mixed as an option but actually create two
different attributes. We could benefit greatly from expanded use of this
latter approach - funding to hire a user friendly interface?

**Comment by dustymc** [comment]
>fish

I don't intend to attempt to change traditions or stop supporting whatever anyone wants to cram into part attributes, but we also need to be clear on what those data can and cannot do. The physical material is arranged such that strong identifiers are not possible, and I'm hesitant to build fancy tools on top of that lest someone gets the impression it's equivalent to other data arrangements.

>magic

Always possible, usually pretty simple to write, but also always comes with the possibility of being difficult to debug and bewildering users. Weird bugs being described by bewildered users are the best. (User: "A" is broken. Me: A doesn't exist?!? User: We enter A. Me: ??? User: (ಠ益ಠ) Me, 17 hours later: ..) 

A "mixed sexes" button that made two attributes in the interface (where users can see what it does) might work. Issue if it seems useful...

**Comment by nemataslg** [comment]
Hi, Everyone. Good discussion! In the Manter Lab, we think that the 'mixed sexes' code for vials with dioecious species are useful as we have many vials stored as "lots" that came from a single host animal. This is the case for both ectoparasites and endoparasites (sometimes they are sorted sometimes they are not). This is useful as we then know if we are looking for one vial or two vials per specimen of host collected. This is important these days with specimens distributed between and among different collections (mammals in one collection and parasites in one or more).  SCOTT
