### ISSUE TITLE
Arctos down?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1222]
An error occurred while processing this page! 
Error Executing Database Query. 
[Macromedia][Oracle JDBC Driver][Oracle]ORA-12519 The listener could not find any available service handlers that are appropriate for the client connection. One possible cause for this error is that the server was not configured for the specified server type (shared/dedicated).
This message has been logged. Please contact us with any information that might help us to resolve this problem.

**Comment by dustymc** [comment]
See https://arctosdb.org/join-arctos/contacts-support/ to report outages.

(And @ccicero @mkoo my email should probably be on there as well - arctos.database email skips my inbox/phone along with Issues.)

I'll bounce the front end and email TACC if that doesn't work.
