### ISSUE TITLE
Arctosdb.org and Arctos.database.org portal interface

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1223]
Hi all,
I'd like to suggest that we reduce the size of the photo in the Arctosdb.org main page and supporting pages as well as the portals page in arctos.database.org so that we can see more of the page content from a standard laptop screen. When I log in, I only see about a third of the content and have to scroll down to get to the About and Search and What Makes us Different tabs. Also, in arctos.database.org portals, the Burke info takes up most of the page  - can we reduce the size of the font or make it possible to click on each one to get the supporting info, instead of having to scroll down? 

This is a similar issue in many of our collection management pages - e.g. batch scan - where we continually have to scroll to the bottom of what is sometimes a lengthy results page to get to a button we need to click - e.g. "success - scan more?" Any chance we can move all this content to the top of a results page, rather than the bottom? 
Less scrolling, more viewing!
Thanks!

**Comment by dustymc** [comment]
>arctos.database.org

http://arctos.database.museum/home.cfm ???

Annotated screeshot would be useful - it looks fine in my standard laptop....

<img width="1383" alt="screen shot 2017-07-31 at 8 14 45 am" src="https://user-images.githubusercontent.com/5720791/28784459-5acd971e-75c8-11e7-9cf8-bbb714b2a7f6.png">



>scroll to the bottom of what is sometimes a lengthy results page to get to a button we need to click

If there's a "you need to make sure this is doing what you think it should be doing before you really do it" page, the "do it" widget is probably on the far side of the "what it's doing" info. If that's what you're talking about, I'm reluctant to change it - I end up un-doing a lot of mass edits despite that attempt at forcing review.

If that's not what you're talking about, screenshots please.

**Comment by campmlc** [comment]
This is from a 15" Dell laptop.

**Comment by campmlc** [comment]
In the case of the batch scan results, I still think that the existiing
"success - scan more" vs "see problems below"  info should be at the top of
the page.I'll send a screenshot next time I do one, but I won't be able to
capture it all in one screen since I will have to scroll down about 5 pages.

**Comment by dustymc** [comment]
FWIW, here's my 12" not-so-standard lap-tablet-thingee.

<img width="1065" alt="screenshot_2" src="https://user-images.githubusercontent.com/5720791/28786153-37637820-75cd-11e7-8131-0ee9a30e7e1f.png">

**Comment by campmlc** [comment]
That's not so bad, but it is weird that we should have so much variability.
Is it browser related? Right now even the display for arctosdatabse.org on
my screen is not terrible - at times in the past the Burke text has been
huge and overwhelming, but it is better currently.
However, I think we should do something about arctosdb.org.
Anyone else having a problem with this?

**Comment by campmlc** [comment]
Here is Chrome at default zoom settings, followed by Firefox. What's up
with the access denied for arctosdb.org on Firefox? I thought we fixed that.

**Comment by campmlc** [comment]
Sorry - I guess attaching from email doesn't work. Trying from Github:

![screenshot 2017-07-31 10 12 18](https://user-images.githubusercontent.com/14808196/28787909-6676d7f2-75db-11e7-87f3-b243200a1eab.png)
![screenshot 2017-07-31 10 13 02](https://user-images.githubusercontent.com/14808196/28787915-6cbe5266-75db-11e7-9269-462f8141aa64.png)

**Comment by AJLinn** [comment]
Maybe on the portal page there could be a "see more" button like on the search page, which would drop open the collections and summaries? I rarely scroll thru all but use the collection code at left to go right to UAM and then have to scroll thru all the collection names and summaries to get to my collection.

Maybe the font size for the institution, collection, and summary could be dropped by quite a few sizes to get more on the page?

I agree the arctosdb.org page photo and opening box could be greatly minimized.

**Comment by dustymc** [comment]
Closing; see https://github.com/ArctosDB/arctos/issues/1554
