### ISSUE TITLE
Display order for Other Identifiers

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1224]
Can we please be able to choose the display order for other identifiers, at least for the top 3? I need a secondary institution's catalog number to display at top, but it is currently hidden below 21 GenBank numbers and can only be seen using the scroll bar. Thanks.

**Comment by dustymc** [comment]
Hu?

**Comment by campmlc** [comment]
I would like these identifiers visible above the long GenBank list in
specimen detail. If we could assign an order to the display, that would be
helpful.

NK: 264027
NMMNHS: New Mexico Museum of Natural History and Science: 4348
institutional catalog number: NMMNH 4348
preparator number: DJH 4822

**Comment by dustymc** [comment]
http://arctos.database.museum/SpecimenResults.cfm?&OIDType=NK&OIDNum=264027&oidOper=IS with othercatalognumbers turned on, correct?

It it possible to prioritize/order other IDs, but that is a global setting (and GenBank is often used and so has been prioritized over the stuff you're currently interested in).

And I think it's not working properly there - preparator number should be higher.... I'll fix that now (I hope).

ANYWAY, the two things you want to see for that specimen are "low quality" identifiers and I doubt most users will want them prioritized. "NMMNHS: New Mexico Museum of Natural History and Science" is a "one of the probably-several collections" ID and "institutional catalog number" makes absolutely no sense to me (eg, you know what type it is but have no idea which institution it came from?!?).

You could prioritize one of them by choosing it as your custom ID, but you've probably already used that up for the NK.

I don't have a solution for you. Up for ideas....

**Comment by campmlc** [comment]
These are specimens that were originally cataloged at NMMNHS and then given
to MSB through an MOU agreement and transfer of custody. They have
requested that their catalog number be visible and also cited in loans.
Whether or not that is feasible, it is politically problematic for us to
have the number buried and not obvious in public view. Other collections
won't want to have this displayed at the top -just MSB needs this, and we
need it to show up that way in public searches.
What if we did "same individual as" relationship instead of self? Could be
bump those to the top?

**Comment by dustymc** [comment]
Well, I don't think those quite qualify as "catalog numbers" (they're not linked to a collection) so I'm not sure what to make of that request. I have no way of selectively prioritizing; if they're prioritized then they'll be at the top of every pick list etc.

Using a non-self relationship would split those data out into the "related items" column, which is probably more visible.

In loans - which don't need to play nicely with everyone else - you can use functions to extract whatever you want.

```
UAM@ARCTOS> select ConcatSingleOtherId(flat.collection_object_id,'NMMNHS: New Mexico Museum of Natural History and Science') AS NMMNHS from flat where guid='MSB:Mamm:271075';

NMMNHS
------------------------------------------------------------------------------------------------------------------------
4348
```

would give you a "NMMNHS" variable which you can put wherever you want in your reports.

**Comment by dustymc** [comment]
>And I think it's not working properly there - preparator number should be higher.... I'll fix that now (I hope).

Opening this as it's own Issue - #1225.
