### ISSUE TITLE
SpecimenResults: "othercatalognumbers" display

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1225]
"Othercatalognumbers" does not currently consider sort_order (from the code table) or base_url.

Given our current sort order - note "preparator number"...

<img width="935" alt="screen shot 2017-07-31 at 11 51 06 am" src="https://user-images.githubusercontent.com/5720791/28793055-99334058-75e6-11e7-990d-e32ab03c0268.png">

... the concatenation is by alpha-sort:

<img width="261" alt="screen shot 2017-07-31 at 11 52 07 am" src="https://user-images.githubusercontent.com/5720791/28793090-b4154088-75e6-11e7-83de-6af2742cd8e3.png">

Note preparator number hiding down at the bottom.

In SQL:

```
select replace(ConcatOtherId(flat.collection_object_id),'; ',chr(10)) AS ids from flat where guid='MSB:Mamm:271075';

IDS
------------------------------------------------------------------------------------------------------------------------
GenBank=KX754470.1
GenBank=KX754497.1
GenBank=KX754530.1
GenBank=KX754561.1
GenBank=KX754590.1
GenBank=KX754620.1
GenBank=KX754651.1
GenBank=KX754681.1
GenBank=KX754713.1
GenBank=KX754741.1
GenBank=KX754772.1
GenBank=KX754806.1
GenBank=KX754834.1
GenBank=KX754864.1
GenBank=KX754912.1
GenBank=KX754965.1
GenBank=KX755011.1
GenBank=KX755065.1
GenBank=KX755117.1
GenBank=KX755168.1
GenBank=KX755220.1
NK=264027
institutional catalog number=NMMNH 4348
preparator number=DJH 4822

```

I could just change the sort order - note preparator number now ordered properly:

```
select replace(ConcatOtherId2(flat.collection_object_id),'; ',chr(10)) AS ids from flat where guid='MSB:Mamm:271075';

IDS
------------------------------------------------------------------------------------------------------------------------
GenBank=KX754470.1
GenBank=KX754497.1
GenBank=KX754530.1
GenBank=KX754561.1
GenBank=KX754590.1
GenBank=KX754620.1
GenBank=KX754651.1
GenBank=KX754681.1
GenBank=KX754713.1
GenBank=KX754741.1
GenBank=KX754772.1
GenBank=KX754806.1
GenBank=KX754834.1
GenBank=KX754864.1
GenBank=KX754912.1
GenBank=KX754965.1
GenBank=KX755011.1
GenBank=KX755065.1
GenBank=KX755117.1
GenBank=KX755168.1
GenBank=KX755220.1
NK=264027
preparator number=DJH 4822
NMMNHS: New Mexico Museum of Natural History and Science=4348
institutional catalog number=NMMNH 4348

```

but perhaps we also want to include the link (made from base_url) for those IDs with it

```
select replace(ConcatOtherId3(flat.collection_object_id),'; ',chr(10)) AS ids from flat where guid='MSB:Mamm:271075';

IDS
------------------------------------------------------------------------------------------------------------------------
GenBank=KX754470.1 (http://www.ncbi.nlm.nih.gov/nuccore/KX754470.1)
GenBank=KX754497.1 (http://www.ncbi.nlm.nih.gov/nuccore/KX754497.1)
GenBank=KX754530.1 (http://www.ncbi.nlm.nih.gov/nuccore/KX754530.1)
GenBank=KX754561.1 (http://www.ncbi.nlm.nih.gov/nuccore/KX754561.1)
GenBank=KX754590.1 (http://www.ncbi.nlm.nih.gov/nuccore/KX754590.1)
GenBank=KX754620.1 (http://www.ncbi.nlm.nih.gov/nuccore/KX754620.1)
GenBank=KX754651.1 (http://www.ncbi.nlm.nih.gov/nuccore/KX754651.1)
GenBank=KX754681.1 (http://www.ncbi.nlm.nih.gov/nuccore/KX754681.1)
GenBank=KX754713.1 (http://www.ncbi.nlm.nih.gov/nuccore/KX754713.1)
GenBank=KX754741.1 (http://www.ncbi.nlm.nih.gov/nuccore/KX754741.1)
GenBank=KX754772.1 (http://www.ncbi.nlm.nih.gov/nuccore/KX754772.1)
GenBank=KX754806.1 (http://www.ncbi.nlm.nih.gov/nuccore/KX754806.1)
GenBank=KX754834.1 (http://www.ncbi.nlm.nih.gov/nuccore/KX754834.1)
GenBank=KX754864.1 (http://www.ncbi.nlm.nih.gov/nuccore/KX754864.1)
GenBank=KX754912.1 (http://www.ncbi.nlm.nih.gov/nuccore/KX754912.1)
GenBank=KX754965.1 (http://www.ncbi.nlm.nih.gov/nuccore/KX754965.1)
GenBank=KX755011.1 (http://www.ncbi.nlm.nih.gov/nuccore/KX755011.1)
GenBank=KX755065.1 (http://www.ncbi.nlm.nih.gov/nuccore/KX755065.1)
GenBank=KX755117.1 (http://www.ncbi.nlm.nih.gov/nuccore/KX755117.1)
GenBank=KX755168.1 (http://www.ncbi.nlm.nih.gov/nuccore/KX755168.1)
GenBank=KX755220.1 (http://www.ncbi.nlm.nih.gov/nuccore/KX755220.1)
NK=264027
preparator number=DJH 4822
NMMNHS: New Mexico Museum of Natural History and Science=4348
institutional catalog number=NMMNH 4348

```

That will occasionally be long, but it seems wrong to exclude important data from the place where most otherIDs are encountered. The format could be whatever - just 

```
GenBank=http://www.ncbi.nlm.nih.gov/nuccore/KX755220.1
```
or the URLS wrapped in HTML (nice in your browser, pretty funky in Excel), or WHATEVER.

Thoughts?

**Comment by KyndallH** [comment]
The link doesn't need to be included and is not functional clutter. You can click on it to take you to the linked page, right click to copy the URLs, or search for the Genbank number on the Genbank website. Plenty of ways to get to the linked record/URL. 

I do think that Genbank and BoLD type numbers should be at the bottom with any collector or field numbers moved to the top (above Genbank). Hierarchy of when numbers were assigned to the specimen.

**Comment by dustymc** [comment]
This is on specimenresults; there currently is no link or URL there, just the bare numbers. (And not all of them will be as obvious as GenBank.) I don't think most users click through to specimendetail, where IDsare actually links.

>should be at the bottom

At least three things going on here...

1) Sort order of OtherIDs can be set in the code table (see screenshot above). I don't really care what ya'll work out there. That controls things like dropdowns (and is where this originated - people don't like scrolling through hundreds of types to find 'collector number,' which is used on LOTS of specimens).

2) Sort order in specimenresults - I think it should follow the order set in the code table, but

3) "when numbers were assigned to the specimen" - I suppose we can do that (roughly, but the primary key of the IDs, or really by adding more metadata or something). Seems like that would be unnecessarily hard to read, but whatever...

```
UAM@ARCTOS> select OTHER_ID_TYPE from CTCOLL_OTHER_ID_TYPE where BASE_URL is not null order by OTHER_ID_TYPE;

OTHER_ID_TYPE
------------------------------------------------------------------------------------------------------------------------
BioSample
BoLD barcode ID
BugGuide.net
CHAS:Bird
CHAS:EH
CHAS:Egg
CHAS:Ento
CHAS:Herb
CHAS:Herp
CHAS:Inv
CHAS:Mamm
CHAS:Teach
CRCM:Bird
CUMV:Mamm
DGR:Bird
DGR:Ento
DGR:Fish
DGR:Mamm
DMNS:Bird
DMNS:Herp
DMNS:Mamm
DMNS:Para
GenBank
HWML:Para
KNWR:ENTO
KNWR:Ento
KNWR:Herb
KWP:Ento
MCZ:Mamm
MCZ:Mamm - Museum of Comparative Zoology Mammal Collection
MLZ:Bird
MLZ:Egg
MLZ:Mamm
MSB:Bird
MSB:Fish
MSB:Herp
MSB:Host
MSB:Mamm
MSB:Para
MSBObs:Mamm
MVZ:Bird
MVZ:Egg
MVZ:Herp
MVZ:Hild
MVZ:Img
MVZ:Mamm
MVZ:Page
MVZObs:Bird
MVZObs:Fish
MVZObs:Herp
MVZObs:Mamm
NBSB:Bird
NCBI Biosample
NCBI Sequence Read Archive Run ID
NMU:Mamm
UAM:Art
UAM:Bird
UAM:EH
UAM:ES
UAM:Ento
UAM:Fish
UAM:Herb
UAM:Herp
UAM:Inv
UAM:Mamm
UAMObs:Ento
UAMObs:Fish
UAMObs:Mamm
UAMb:Herb
UC-SCFS:Bird
UC-SCFS:Mamm
UCM:Bird
UCM:Mamm
UCM:Obs
UCMP Locality ID
UCMP: University of California Museum of Paleontology
USNPC:Para
UTEP:Arc
UTEP:Bird
UTEP:ES
UTEP:Ento
UTEP:Fish
UTEP:Herb
UTEP:Herp
UTEP:HerpOS
UTEP:Inv
UTEP:Mamm
UTEP:Teach
UTEP:Zoo
UTEPObs:Ento
UTEPObs:Herp
UWBM:Herp
UWBM:Mamm
UWYMV:Bird
UWYMV:Herp
UWYMV:Mamm
WNMU:Bird
WNMU:Fish
WNMU:Mamm
iNaturalist.org
```

**Comment by campmlc** [comment]
The OtherIdentifiers concatenated field in specimen results is already very
difficult to read without adding urls - If we need to add them, perhaps
have that be a separate column that can be chosen in the tools menu.

It is useful to be able to control the order of identifiers in the code
table for searching and data entry. I don't think that should change.
But for public view in specimen detail, I do agree with Kyndall that we
need to be able to change the order of identifiers.  It would be great if
this were something that could be chosen at the individual
collection/curatorial level based on what we want the public to see first.

Kyndall's idea of going by date added is OK if that is the only way to make
this work. We need GenBank to show up easily for data entry, but we don't
want all the GenBak identifiers ad infinitum at the top of the page above
other more relevant info.

A similar situation exists with specimen event - it is problematic that we
can't choose which to display at top of page and to search on. Currently
the oldest event is the one that shows first and is the only one that is
searchable- but that is another issue.

**Comment by dustymc** [comment]
> individual collection/curatorial level 

The only realistic place I see for that is at the otherID level - something that would need set for every identifier. Eg maybe you want NK first when it was cited and NMMNH first when it needs to be and .....

>specimen event

OtherIDs are "facts" - someone said "this specimen was used to make GenBank ABC123" or they didn't. There's currently no metadata or internal prioritization or anything else - they're all equal facts, that's it.

Event are determinations, and as such have the usual "according to...because..." stuff. We can use that (or anything else we can get to) to prioritize or order or not show or WHATEVER them on specimendetail (or wherever). https://github.com/ArctosDB/DDL/blob/master/functions/getPrioritySpecimenEvent.sql controls which one is displayed in specimenresults, and is easy to adjust. Specimenresults contains only one event because ya'll insist on having something that looks like a spreadsheet there, even though the data require a LOT of massaging to get into a spreadsheet-like format. Search could consider all events, but searching for things you can't see (because ya'll want that table of results) is incredibly confusing. 

Before the recent partdetail panic, I might have suggested displaying all of specimenresults as JSON instead of a table. I did suggest that for events (#755) but nothing has yet happened. DWC handles the problem by treating "Occurrences" as the core data objects - they just repeat the non-event data for every event - which is nice for exchange but would be a horrible data model for specimen-based science. I'm open to suggestions!
