### ISSUE TITLE
deleting duplicate parts with no barcode

### ISSUE THREAD

**Issue by KyndallH** [ArctosDB/arctos#1226]
Is there an easy way to delete duplicated parts? I need to delete the DNA extractions that do not have a barcode in quite a few UAM:Ento: specimens. I can't delete them via "modify parts" because I need to retain the "DNA extractions" that do have a barcode.  I do not need to retain the remarks on the parts that are being deleted.

<img width="1110" alt="screen shot 2017-07-31 at 1 16 16 pm" src="https://user-images.githubusercontent.com/16887896/28798896-8de7c1ea-75f2-11e7-9bdf-fecd16eea05d.png">

**Comment by dustymc** [comment]
Edit parts and get them one by one, or I can zap things if you'll tell me exactly what needs zapping. Data from below SQL attached....

```
create table temp_bugdnaext as
select
  guid
from
  flat,
  specimen_part,
  coll_obj_cont_hist,
  container pc
where
  flat.collection_object_id=specimen_part.derived_from_cat_item and
  specimen_part.part_name='DNA extraction' and
  guid like 'UAM:Ento%' and
  specimen_part.collection_object_id=coll_obj_cont_hist.collection_object_id and
  coll_obj_cont_hist.container_id=pc.container_id and
  pc.parent_container_id=0
order by guid
```


[temp_bugdnaext.csv.zip](https://github.com/ArctosDB/arctos/files/1188912/temp_bugdnaext.csv.zip)

**Comment by campmlc** [comment]
Yes, it would help me also to be able to delete all unbarcoded parts of a
certain type from list. We are going to have to load barcoded parts to
records that have unbarcoded parts already present, and since the part
names are not always equivalent and condition doesn't always match it isn't
possible to use the parts bulkloader with "use existing", which I haven't
yet been able to get to work. We are going to have to do this for tens of
thousands of specimens.

**Comment by KyndallH** [comment]
@campmlc I would love to delete specific parts without barcodes OR ones that are in our "parentless void" barcode.

Dusty - https://arctos.database.museum/saved/duplicateDNAextractions
From this saved search, any specimens with two DNA extraction in parts - the DNA extraction without a barcode needs to be deleted. Thanks!

**Comment by dustymc** [comment]
@KyndallH I think your saved search is the same as the csv above - specimen_part.part_name='DNA extraction' and  guid like 'UAM:Ento%'. Confirm and I can delete them. None of the barcode-free DNA parts are used in loans.

@campmlc not sure I'm following but if so deleting and re-creating parts sounds like a good way to lose loan data, condition history, etc. I can help attach barcodes without deleting/creating.

**Comment by campmlc** [comment]
Yes, attaching barcodes to existing parts is exactly what I need but
couldn't find a tool for. That would replace my need to delete those
without barcodes for now.

**Comment by KyndallH** [comment]
Dusty - confirm! Delete! Thanks!

**Comment by dustymc** [comment]
done
