### ISSUE TITLE
publication DOI not recognized by Arctos

### ISSUE THREAD

**Issue by KyndallH** [ArctosDB/arctos#1228]
Why does Arctos not like this DOI? We've tried variations of the DOI and still a no go.

<img width="718" alt="screen shot 2017-08-02 at 8 43 44 am" src="https://user-images.githubusercontent.com/16887896/28884543-b98887ea-775e-11e7-80a5-f5570437a60f.png">

<img width="732" alt="screen shot 2017-08-02 at 8 31 30 am" src="https://user-images.githubusercontent.com/16887896/28884466-7246002e-775e-11e7-9ab4-bf46a92cf7a4.png">

**Comment by dustymc** [comment]
http://handbook.arctosdb.org/documentation/publications.html#doi

```
Include only the actual IDs rather than a more complete link (which may get changed). The following is a DOI:

    10.1111/j.1365-294X.2005.02461.x

The following are examples of formats that contain DOIs, but are not DOIs:

    dx.doi.org/10.1111/j.1365-294X.2005.02461.x
    DOI:10.1111/j.1365-294X.2005.02461.x.
```

**Comment by KyndallH** [comment]
We have tried using only the numbers for the DOI but as I said earlier - it doesn't like variations either.

Could it be because of the journal (or lack thereof)? It is on bioRxiv [free online archive and distribution service for unpublished preprints in the life sciences]. 

![Uploading Screen Shot 2017-08-02 at 9.30.04 AM.png…]()

**Comment by dustymc** [comment]
Maybe something got stuck in your browser? It worked find for me.

<img width="640" alt="screen shot 2017-08-02 at 10 42 19 am" src="https://user-images.githubusercontent.com/5720791/28886712-49418f02-776f-11e7-82c0-284a4d8a25e8.png">

It doesn't matter where the publication is - that's a very large part of the point of DOIs. The query goes to crossref, the organization that issues DOIs for publication. I can think of only three possibilities for a DOI failing to resolve:

1. You didn't enter something correctly
2. CrossRef is down (it happens...), they'll usually pop back up within a day or so
3. The publication is making up DOIs (also happens...), CrossRef will want to know about it.

**Comment by KyndallH** [comment]
Hmmm.
1. maybe - graduate student was doing it
2. nope since we were doing a bunch
3. not sure what 3 means

But doesn't matter - all entered now. Thanks!
