### ISSUE TITLE
publications add author, same agent name multiple times

### ISSUE THREAD

**Issue by KyndallH** [ArctosDB/arctos#1230]
When entering authors for publications, it is giving the same agent, multiple times. Not sure if it is a big deal but seems like a bug.

<img width="862" alt="screen shot 2017-08-02 at 9 35 10 am" src="https://user-images.githubusercontent.com/16887896/28886736-fa0bc2ac-7766-11e7-8d64-f3b16eccb423.png">

**Comment by dustymc** [comment]
fixed for next release
