### ISSUE TITLE
Need attributes for Arc collections

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1231]
I would like these attributes for the Arc collections, please.

sex
unformatted measurements

Thanks!

**Comment by dustymc** [comment]
Done, but you'll also need sex values (and definitions where they're missing - hopefully that's easy for a change....).

http://arctos.database.museum/info/ctDocumentation.cfm?table=CTSEX_CDE

**Comment by Jegelewicz** [comment]
Can we use the same values and definitions as Herp?  Also, the definition for unknown sex in the ES collections can be the same as that in Herp.

**Comment by Jegelewicz** [comment]
Any chance we can get the sex values into the Teach collections?

**Comment by dustymc** [comment]
Done, except unknown (to which my pathway is blocked at the moment anyway) - #1237.
