### ISSUE TITLE
Force Container Type in Move Container/Batch Scan

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1233]
Can we get dimensions to autopopulate to standard 2" freezer boxes when we force child container to freezer box in batch scan or move container?  Number of positions does not have to be entered automatically but dimensions would be very helpful.  Is anyone using force container with non-standard box sizes?

**Comment by KyndallH** [comment]
I do use non-standard size freezer boxes, but I do not foresee using the force container function. As of right this minute, I say fine by me.

**Comment by campmlc** [comment]
Thanks. We are doing this lots, so it would be a big help.

**Comment by dustymc** [comment]
>autopopulate

If container size and type were linked strongly enough to support auto-anything, we'd just get rid of one of them.

How about a "...and set all child container dimensions to {pick one or fill in the blanks or something}" option instead?

**Comment by campmlc** [comment]
Sure, either of those works. Maybe both? Chose from options or enter your
own?

standard 2" boxes are (W x H x D): 13 x 5 x 13 CM.

3" boxes are 13 x 7 x 13

**Comment by dustymc** [comment]
>Maybe both

I like it. Add W L H "enter a number" fields + some links to populate them with common values.

**Comment by dustymc** [comment]
FYI, here are our 23 "standard" freezer box sizes....

```
select 
	WIDTH || ' x ' || LENGTH || ' x ' || HEIGHT || ' @ ' || count(*) c
from container where container_type='freezer box' group by 
	WIDTH || ' x ' || LENGTH || ' x ' || HEIGHT
order by 
	WIDTH || ' x ' || LENGTH || ' x ' || HEIGHT 
	;
------------------------------------------------------------------------------------------------------------------------
 x  x  @ 2455
 x 13.2 x 4.9 @ 1
13 x 10 x 5.3 @ 1
13 x 12 x 5.3 @ 1
13 x 13 x 5 @ 2477
13 x 13 x 5.2 @ 2
13 x 13 x 5.3 @ 1897
13 x 13 x 5.4 @ 1
13 x 13 x 5.5 @ 2
13 x 13 x 81 @ 1
13 x 13 x 9.4 @ 4
13 x 5 x 13 @ 4
13.2 x 13.2 x 10 @ 1
13.2 x 13.2 x 4.9 @ 978
13.2 x 13.2 x 7.5 @ 10
131 x 13 x 5.3 @ 1
14 x 14 x 73 @ 7
15 x 13 x 5.3 @ 2
15 x 15 x 5.3 @ 5
5 x 5 x 5 @ 2
5.5 x 5.5 x 2 @ 2
7.5 x 7.5 x 5 @ 1055
8.5 x 12.5 x 2.5 @ 1

23 rows selected.
```

**Comment by dustymc** [comment]
for next release

**Comment by campmlc** [comment]
The one on my desk measures 13.2 x 13.2 x 5.1 cm with the lid on. It is
fine with me if we standardize all boxes that are within 1-2 mm of this to
the same size, unless that messes up box positions in racks. 13 x 13 x 5
should work.
