### ISSUE TITLE
Add sex codes for Arc and Teach collections

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1236]
Please add sex codes for Arc and Teach collections as follows:

female - Of or denoting the sex that can bear offspring or produce eggs,  distinguished biologically by the production of gametes (ova) that can  be fertilized by male gametes.

female ? - The examiner believes the specimen to be a female, but is uncertain.

gynandromorph - Having both male and female morphological characteristics.

hermaphrodite - An individual in which reproductive organs of both sexes are present.

male - Physiological sex that produces sperm.

male ? - The examiner believes the specimen to be a male, but is uncertain.

not recorded - There is data in the form of a label or field notes, and there is no mention of sex.

unknown - There are no data in the form of a label or field notes. That is, no determination, or attempted determination is available.

**Comment by dustymc** [comment]
Done, except #1237
