### ISSUE TITLE
sex "unknown"

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1237]
http://arctos.database.museum/info/ctDocumentation.cfm?table=CTSEX_CDE

"unknown" is inconsistently defined, but the implication/partial definition is "no data." We have the option to just say nothing, or not create data. I'm not sure that the fifth (6th if we're counting saying nothing!) way of saying we don't know adds clarity.

Can we just delete sex=unknown?

**Comment by Jegelewicz** [comment]
I am perfectly fine with eliminating sex=unknown - don't know if someone else needs it for some reason though...

**Comment by ekrimmel** [comment]
+1 on deleting sex=unknown

**Comment by amgunderson** [comment]
Sex is a required attribute for mammals so if you delete unknown then make the field no longer required.

**Comment by dustymc** [comment]
> required attribute for mammals s

Ah yes, that's where this comes from. I think the thought process was that forcing students to pick SOMETHING was better than allowing them to just ignore a "field." IF that works, it probably/maybe justifies keeping "unknown." @amgunderson this is your call I think....

**Comment by jldunnum** [comment]
I think I would like to keep "unknown" because it provides more data than a null value, which could mean the sex is unknown or that the data for sex were just not entered.


______________________________________________________________

Jonathan L. Dunnum Ph.D.
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by dustymc** [comment]
@jldunnum no real objections, but there are several options for "we don't know."

1. NULL/no attribute==>we have nothing to say on the matter
2. unknown==>intent same as NULL I think, "we have no information." This needs defined globally if we're to keep it. ("There are no data in the form of a label or field notes. That is, no determination, or attempted determination is available." seems reasonable to me and could just be pushed to all collection types.)
2.  not recorded ==>There is data in the form of a label or field notes, and there is no mention of sex.
2.  recorded as unknown ==>There are data in the form of a label or field notes, and these indicate that the examiner was unable to determine the sex.

That last one may need the definition adjusted, but I think the intent is "we looked, still don't know."

https://arctos.database.museum/info/ctDocumentation.cfm?table=CTSEX_CDE

**Comment by jldunnum** [comment]
Agreed, I guess from my perspective it probably comes down to us doing a better job of training on which terms to use when we are doing our data entry.  To date we certainly have a mix of those terms and they are likely not all applied correctly or consistantly.


______________________________________________________________

Jonathan L. Dunnum Ph.D.
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by dustymc** [comment]
Not to hijack my own thread TOO much, but ideas for getting definitions in front of users ALWAYS appreciated. There are "define" links in most (all?? Let me know if you find one missing!) forms now, but I'm not sure anyone clicks them.

**Comment by Jegelewicz** [comment]
Reviving this given our discussion in AWG today. Here is what is in the code table now:

 term | definition 
-- | --
not recorded | There is data in the form of a label or field notes, and there is no mention of sex. 
recorded as unknown | There are data in the form of a label or field notes, and these indicate that the examiner was unable to determine the sex.
unknown | There are no data in the form of a label or field notes. That is, no determination, or attempted determination is available.

In the AWG meeting, it appeared that there was consensus that we need to remove all but "unknown". Here is what I suggest:

not recorded - change any use of this to "unknown" and add "sex was not recorded" to the method for the attribute
recorded as unknown - change any use of this to "unknown" and add "examiner was unable to determine the sex." to the method for the attribute

**Comment by dustymc** [comment]
Shall we deal with the "... ?" while we're dealing? Not sure if those should be eg ``female ?``-->``female`` + method="uncertain" or ``female ?``-->``unknown`` + method="possibly female"  (or similar). The latter is probably less likely to break someone's analysis.

Data:

```


select guid_prefix,attribute_value,  count(*) c
from
cataloged_item
inner join attributes on attributes.collection_object_id=cataloged_item.collection_object_id and attribute_type='sex'
inner join collection on cataloged_item.collection_id=collection.collection_id
where attribute_value not in ('male','female', 'unknown')
group by guid_prefix,attribute_value
order by attribute_value,guid_prefix
;
 guid_prefix |   attribute_value   |   c   
-------------+---------------------+-------
 ALMNH:Paleo | female ?            |     1
 APSU:Herp   | female ?            |     2
 BYU:Herp    | female ?            |    16
 CHAS:Bird   | female ?            |     8
 DMNS:Bird   | female ?            |    54
 DMNS:Mamm   | female ?            |    70
 MLZ:Bird    | female ?            |    32
 MLZ:Mamm    | female ?            |     3
 MSB:Bird    | female ?            |   151
 MSB:Herp    | female ?            |    18
 MSB:Mamm    | female ?            |   250
 MVZ:Bird    | female ?            |  1514
 MVZ:Herp    | female ?            |    11
 MVZ:Mamm    | female ?            |    27
 MVZObs:Bird | female ?            |     8
 NMMNH:Bird  | female ?            |     1
 NMU:Mamm    | female ?            |     4
 OWU:Rept    | female ?            |     3
 UAM:Bird    | female ?            |   338
 UAM:Mamm    | female ?            |   225
 UCM:Bird    | female ?            |    54
 UCM:Mamm    | female ?            |    20
 UCSC:Bird   | female ?            |     1
 UCSC:Mamm   | female ?            |     3
 UMNH:Mamm   | female ?            |     7
 UTEP:Bird   | female ?            |    44
 UTEP:Herp   | female ?            |     2
 UTEP:HerpOS | female ?            |     5
 UTEP:Mamm   | female ?            |     2
 UWYMV:Bird  | female ?            |     1
 DMNS:Bird   | gynandromorph       |     1
 MSB:Bird    | gynandromorph       |     2
 MVZ:Bird    | gynandromorph       |     1
 MVZ:Herp    | gynandromorph       |     1
 DMNS:Mamm   | hermaphrodite       |     3
 HWML:Para   | hermaphrodite       |  1376
 MSB:Mamm    | hermaphrodite       |    47
 MSB:Para    | hermaphrodite       |    12
 MVZ:Herp    | hermaphrodite       |     1
 MVZ:Mamm    | hermaphrodite       |     3
 UAM:Mamm    | hermaphrodite       |     1
 UWBM:Mamm   | hermaphrodite       |     1
 BYU:Herp    | male ?              |    15
 CHAS:Bird   | male ?              |    13
 CHAS:Mamm   | male ?              |     2
 DMNS:Bird   | male ?              |    29
 DMNS:Mamm   | male ?              |    52
 MLZ:Bird    | male ?              |    28
 MLZ:Fish    | male ?              |     2
 MLZ:Mamm    | male ?              |     1
 MSB:Bird    | male ?              |   151
 MSB:Herp    | male ?              |    12
 MSB:Mamm    | male ?              |    94
 MVZ:Bird    | male ?              |  1134
 MVZ:Herp    | male ?              |    12
 MVZ:Mamm    | male ?              |    19
 MVZObs:Bird | male ?              |     1
 MVZObs:Mamm | male ?              |     1
 NMU:Bird    | male ?              |     2
 NMU:Mamm    | male ?              |     1
 OWU:Rept    | male ?              |     2
 UAM:Bird    | male ?              |   261
 UAM:Mamm    | male ?              |   133
 UAMObs:Bird | male ?              |     2
 UCM:Bird    | male ?              |    29
 UCM:Mamm    | male ?              |     4
 UCSC:Bird   | male ?              |     1
 UMNH:Bird   | male ?              |     1
 UMNH:Mamm   | male ?              |     8
 UMZM:Bird   | male ?              |     1
 UMZM:Mamm   | male ?              |     1
 UNR:Mamm    | male ?              |     1
 UTEP:Bird   | male ?              |    48
 UTEP:HerpOS | male ?              |    17
 UWBM:Mamm   | male ?              |     1
 UWYMV:Bird  | male ?              |     8
 UAM:Mamm    | male 1              |     1
 ASNHC:Bird  | not recorded        |    34
 ASNHC:Herp  | not recorded        |   317
 ASNHC:Mamm  | not recorded        |    67
 BYU:Herp    | not recorded        |     3
 CHAS:Bird   | not recorded        |    60
 CHAS:Ento   | not recorded        | 24813
 CHAS:Inv    | not recorded        | 15127
 CHAS:Mamm   | not recorded        |    15
 CHAS:Teach  | not recorded        |   791
 DGR:Bird    | not recorded        |   159
 DGR:Ento    | not recorded        |     9
 DGR:Mamm    | not recorded        |    38
 DMNS:Bird   | not recorded        |    72
 DMNS:Mamm   | not recorded        |   149
 DMNS:Para   | not recorded        |     1
 HWML:Para   | not recorded        |   988
 MLZ:Bird    | not recorded        |    27
 MSB:Bird    | not recorded        |   619
 MSB:Fish    | not recorded        |   330
 MSB:Herp    | not recorded        |    38
 MSB:Mamm    | not recorded        |  6650
 MSB:Para    | not recorded        |    47
 MVZ:Bird    | not recorded        |   956
 MVZ:Egg     | not recorded        |    28
 MVZ:Herp    | not recorded        | 12103
 MVZ:Mamm    | not recorded        |   683
 MVZObs:Bird | not recorded        |     2
 MVZObs:Herp | not recorded        |     3
 MVZObs:Mamm | not recorded        |    22
 NMMNH:Bird  | not recorded        |   260
 NMMNH:Mamm  | not recorded        |     2
 NMU:Bird    | not recorded        |    86
 NMU:Mamm    | not recorded        |   143
 OWU:Bird    | not recorded        |     6
 OWU:Mamm    | not recorded        |    99
 UAM:Bird    | not recorded        |   190
 UAM:Herp    | not recorded        |   188
 UAM:Inv     | not recorded        |    16
 UAM:Mamm    | not recorded        |  2479
 UAMObs:Mamm | not recorded        |    51
 UCM:Bird    | not recorded        |    15
 UCM:Mamm    | not recorded        |   456
 UCSC:Mamm   | not recorded        |    15
 UMNH:Bird   | not recorded        |    83
 UMNH:Herp   | not recorded        |     3
 UMNH:Mamm   | not recorded        |    17
 UNR:Bird    | not recorded        |    39
 UNR:Mamm    | not recorded        |    20
 UTEP:Bird   | not recorded        |     2
 UWBM:Mamm   | not recorded        |    10
 UWYMV:Bird  | not recorded        |     5
 UWYMV:Mamm  | not recorded        |    24
 WNMU:Fish   | not recorded        |   275
 WNMU:Mamm   | not recorded        |    22
 ASNHC:Bird  | recorded as unknown |    55
 ASNHC:Herp  | recorded as unknown |    60
 ASNHC:Mamm  | recorded as unknown |   666
 BYU:Mamm    | recorded as unknown |     1
 CHAS:Bird   | recorded as unknown |    10
 CHAS:Ento   | recorded as unknown |    17
 CHAS:Mamm   | recorded as unknown |     2
 DMNS:Bird   | recorded as unknown |  2563
 DMNS:Mamm   | recorded as unknown |   511
 KWP:Ento    | recorded as unknown |     1
 MLZ:Bird    | recorded as unknown |    19
 MLZ:Fish    | recorded as unknown |   830
 MSB:Bird    | recorded as unknown |   144
 MSB:Mamm    | recorded as unknown |  2730
 MVZ:Bird    | recorded as unknown |  1579
 MVZ:Mamm    | recorded as unknown |   318
 MVZObs:Mamm | recorded as unknown |     1
 NMMNH:Bird  | recorded as unknown |    77
 NMMNH:Mamm  | recorded as unknown |     8
 NMU:Mamm    | recorded as unknown |     2
 OWU:Mamm    | recorded as unknown |     1
 UAM:Mamm    | recorded as unknown |    18
 UCM:Bird    | recorded as unknown |    43
 UCM:Mamm    | recorded as unknown |   110
 UCSC:Mamm   | recorded as unknown |    85
 UTEP:Bird   | recorded as unknown |     1
 UWBM:Mamm   | recorded as unknown |     4
 UWYMV:Bird  | recorded as unknown |    11
 UWYMV:Mamm  | recorded as unknown |     2
 HWML:Para   | sexes mixed         |  3038
 MSB:Para    | sexes mixed         |     2
 NMMNH:Ento  | sexes mixed         |    11
 UTEP:Ento   | sexes mixed         |    10
```

**Comment by dustymc** [comment]
Merging with https://github.com/ArctosDB/arctos/issues/3516
