### ISSUE TITLE
Add a CTCOLL_OTHER_ID_TYPE

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1240]
I would like to add the following other ID type.

Fort Bliss Curatorial Facility

We have material from several of their collections that were transferred to us.  This will help me keep their catalog numbers searchable.

**Comment by dustymc** [comment]
If you have several collections and you want searchable, you need several identifiers. Please clarify. 

I'll also need a definition (URLs are nice).

**Comment by Jegelewicz** [comment]
This is not a typical museum entity. The Fort Bliss Curatorial Facility does not have named collections or divisions. It has a collection of all kinds of things so there is only one identifier. As a military entity, it doesn't have a web presence. We hold some of their stuff as a long term loan and some was an exchange. I just want to be able to find all of their stuff in all of our collections and I could do that with an other ID type of "Fort Bliss Curatorial Facility".

"Reality is an illusion, albeit a very persistent one." Albert Einstein

**Comment by campmlc** [comment]
Teresa, I added the ID.
