### ISSUE TITLE
project funding

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1241]
deal with 12,345-type values (strip commas before insert?) in funded_usd.

**Comment by campmlc** [comment]
Can we also add field for funding agent and grant number?

**Comment by dustymc** [comment]
> funding agent

Use "Sponsor."

https://arctos.database.museum/info/ctDocumentation.cfm?table=CTPROJECT_AGENT_ROLE

>grant number

Until/unless there's a compelling reason to do otherwise, use PROJECT_AGENT_REMARKS. 

http://handbook.arctosdb.org/how_to/How-to-understand-Project-Funding.html

**Comment by dustymc** [comment]
changed form datatype to numeric for next release
