### ISSUE TITLE
NEON other identifier

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1246]
Hi all,
We need to have a discussion regarding the NEON identifier with any institution(s) that are archiving NEON specimens.  There are multiple identifier types within the NEON system. There are individual IDs for the individual organism, as well as different types of sample IDs based on sample type, e.g. blood, feces, hair,etc. We are requesting clarification from NEON as to which of these will have linkable urls - no response yet. 
Currently in Arctos there is a NEON: National Ecological Observatory Network identifier, that is defined as being "Collection numbers assigned to specimens by the National Ecological Observatory Network" which sounds like the equivalent of Neon individual ID. Is there any objection to merging these two identifiers under the individual ID in order to avoid confusion with sample IDs?

**Comment by dustymc** [comment]
```
select
  other_id_type,
  guid_prefix,
  count(*) c
from
  collection,
  cataloged_item,
  coll_obj_other_id_num
where
  collection.collection_id=cataloged_item.collection_id and
  cataloged_item.collection_object_id=coll_obj_other_id_num.collection_object_id and
  other_id_type in (
    'NEON individualID',
    'NEON: National Ecological Observatory Network'
  )
group by
  other_id_type,
  guid_prefix
;

OTHER_ID_TYPE
------------------------------------------------------------------------------------------------------------------------
GUID_PREFIX							      C
------------------------------------------------------------ ----------
NEON: National Ecological Observatory Network
DMNS:Mamm							     27


1 row selected.

```

You can just delete NEON individualID - it's not being used.

**Comment by campmlc** [comment]
It is the NEON individual ID that we will need to use. So it looks like we
need to talk with Denver.

**Comment by dustymc** [comment]
>It is the NEON individual ID that we will need to use

??? why ???

Is there any reason not to delete all unused identifiers?

**Comment by dustymc** [comment]
Looks like there's little interest from NEON in supporting linked data, but in anticipation of those data ending up in a more research-based system I think we should:

1) Keep "NEON: National Ecological Observatory Network" as-is, for use at the specimen (individual, lot, whatever) level.
2) Move "NEON sample ID" to http://arctos.database.museum/info/ctDocumentation.cfm?table=CTSPECPART_ATTRIBUTE_TYPE either by using "Other ID" or, if there's a reason to, by creating a new specific part attribute type.

@jldunnum

**Comment by campmlc** [comment]
I agree with this approach.
