### ISSUE TITLE
bring back "in-house" loans

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#1248]
I'd like to make a case for keeping "in-house" loan as a good kind of loan type - @dustymc indicated this is a type that is discouraged from use.

I use it regularly to document when visiting researchers come to the museum and examine a whole slew of objects. The objects get handled by me and my staff, by the researcher, get photographed and measured, specimen records examined, accession file contents examined and copied, and a future publication possibly created from that process. Lots of potential for damage and good to track.

I also use them for documenting objects that get used in in-house short-term exhibits.

Lastly, I use them for special events when I pull objects and put them out for the public to view for a one-day event (e.g., Open House, Halloween, Family Days, Military Appreciation VIP tours, etc.).

The current definition listed in the code table seems fine to me (Loaned items did not leave the building, e.g. were used by a visiting researcher) or could be modified to something for encompassing like this:

"Specimens are removed from their curation location and examined or used within the museum by a researcher, visiting group, or class or for temporary viewing by the public (e.g.,  in-house special exhibit or public event)."

**Comment by dustymc** [comment]
I thought we'd deprecated that, but I guess not - https://arctos.database.museum/info/ctDocumentation.cfm?table=CTLOAN_TYPE.

In-house loans are obviously usage and should be documented the same as any other loan, so no argument there, but I think loan type is redundant with other data. An in-house loan from here looks like a normal loan of various types (probably normally returnable, but maybe a researcher removes bits from bones for DNA==>mixed) with no shipment information. Having multiple ways of saying the same thing usually leads to unnecessary complication.

That said, I see no functional reason to get rid of in-house loans and if they're useful to ya'll I have no objections to keeping them.

**Comment by amgunderson** [comment]
Yes, I use in house loans when a visiting researcher is here using the collection rather than a returnable loan that is sent out of house.
