### ISSUE TITLE
bulkloader citation pre-load check (was: error when bulkloading citations)

### ISSUE THREAD

**Issue by KyndallH** [ArctosDB/arctos#1249]
![image 1](https://user-images.githubusercontent.com/16887896/29736700-7162fa7c-89b0-11e7-94ee-448fae139b9a.png)

Kendall Mills is bulkloading citations. She got the "valid" table and hit proceed. She then got this message on a handful of specimens. Not quite sure why we are getting this message.

Thanks!

**Comment by dustymc** [comment]
http://handbook.arctosdb.org/documentation/understanding-errors.html#unique-constraint-iu_table_and_column-violated

You're trying to create something that already exists - that one looks like a dup in the bulkloader file.

**Comment by campmlc** [comment]
Is there a way to allow all the valid records to load and exclude the dups,
so that we don't have try try to sort out duplicates in advance? This is a
difficult and time consuming task. It would be wonderful if this could
happen for all the bulkloaders- load what works, and give us a csv download
of problems?

On Aug 25, 2017 7:24 PM, "dustymc" <notifications@github.com> wrote:

http://handbook.arctosdb.org/documentation/understanding-
errors.html#unique-constraint-iu_table_and_column-violated

You're trying to create something that already exists - that one looks like
a dup in the bulkloader file.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ArctosDB/arctos/issues/1249#issuecomment-325062796>,
or mute
the thread

**Comment by KyndallH** [comment]
The bottom one was a duplicate value (10241) BUT others given in that list are not. If we get rid of the duplicates, does that mean we will get an error message that will tell us why it didn't like the others?

<img width="276" alt="screen shot 2017-08-25 at 5 15 02 pm" src="https://user-images.githubusercontent.com/16887896/29737383-1a33e94c-89b9-11e7-8634-b37834870b07.png">

**Comment by dustymc** [comment]
>load what works, and give us a csv download of problems?

That's possible, but I don't think it's good design. You're asking to do arbitrary things which are in some cases extremely difficult to un-do from input which is known to be bad. Maybe the "duplicate" which gets ignored has important data in something that's not a key-field, and the one which loads is missing that - I think those data would almost inevitably be lost.

I'd rather invest in pre-load checks, but I'm happy to discuss more. I'll add "check duplicate what-will-become-keys" to the loader.

@KyndallH the running list is things that works - it's telling you what it's going to try to do next before it does it, so you'll have a pointer to the problem when something like this happen. Load order isn't necessarily the same as the order in your CSV. Remove the dup and try it again - or send me your data and I'll try it.

**Comment by amgunderson** [comment]
We deleted the duplicates and now 882 of them are getting this error.  We are unsure what this means. 

<img width="2037" alt="screen shot 2017-09-01 at 2 32 52 pm" src="https://user-images.githubusercontent.com/8440698/29989876-7babf778-8f22-11e7-830a-f978ca32c9b7.png">
<img width="917" alt="screen shot 2017-09-01 at 2 33 28 pm" src="https://user-images.githubusercontent.com/8440698/29989884-89f783c4-8f22-11e7-9de4-779dc8977f75.png">

**Comment by dustymc** [comment]
http://arctos.database.museum/info/ctDocumentation.cfm?table=CTCITATION_TYPE_STATUS

You're trying to use referral for a peer-reviewed publication, or something other than referral for a non-peer-reviewed publication.

**Comment by KyndallH** [comment]
When it gave me this error, it listed 800 records. I had to go in and enter them in chunks to locate the singular entry that had this error. Any way to fine tune the error machine? If not, no biggie since we don't enter citations that often but it would be nice.

**Comment by dustymc** [comment]
>fine tune the error machine

Yes, and I'm stealing that phrase.

Add check is_peer_reviewed<-->type_status relationship in pre-load checks.

**Comment by dustymc** [comment]
There's a new citation loader in test, it needs testing.
