### ISSUE TITLE
CRCM - delete collection

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#1251]
CRCM is not using Arctos, which has only 1501 specimens compared to 49,829 occurrences in GBIF and 49,820 records on the VertNet IPT. Delete collection from Arctos (confirm with DB or JRW?).

@dustymc @dbloom @tucotuco

**Comment by tucotuco** [comment]
Confirmed. CRCM manages and publishes independently.

**Comment by ccicero** [comment]
Thanks John. Copying @lkvoong regarding deleting CRCM from Arctos.

**Comment by lkvoong** [comment]
Sorry, Carla --  I completely missed this.  I just checked in with Dusty about this and we'll be deleting the records, and then the collection.

**Comment by lkvoong** [comment]
The records have been deleted and the CRCM:Bird collection has been dropped.
