### ISSUE TITLE
Bulkload error

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1252]
What does this error in the bulkloader mean?

called from b_bulkload_attribute: ORA-06502: PL/SQL: numeric or value error: character string buffer too smallORA-06512: at "UAM.TR_ATTRIBUTES_CT_BUI", line 19ORA-04088: error during execution of  {snip...}

**Comment by Jegelewicz** [comment]
@dustymc can you answer me this?
Thanks!

**Comment by dustymc** [comment]
should be fixed - try the load again

**Comment by Jegelewicz** [comment]
But what caused it? I don't want to repeat the error if possible...

**Comment by dustymc** [comment]
A bad datatype in a trigger which was developed when there were tighter constraints on collection_cde.
