### ISSUE TITLE
error while bulkloading specimen events

### ISSUE THREAD

**Issue by AdrienneRaniszewski** [ArctosDB/arctos#1253]
I am trying to bulkload specimen events using the Batch Tools. I downloaded the template, uploaded a csv file, validated it, then after being told "the data should load" I proceeded to load, and got this error "An error occurred while processing this page! Variable VERBATIMCOORDINATES is undefined." The template I downloaded does not have a column called VERBATIMCOORDINATES, so I'm not sure what this error is trying to tell me.

My file originally only had the LOCALITY_ID, no other locality information (besides verbatim locality). After producing this error, I tried adding DEC_LAT and DEC_LONG, then I added ORIG_LAT_LONG_UNITS, DATUM, GEOREFERENCE_SOURCE, and GEOREFERENCE_PROTOCOL. none of these attempts worked. I read the information in the table carefully and it sounded like none of that stuff is required if I use a localityID. Any idea what I'm doing wrong?

[BulkloadEvent test.xlsx](https://github.com/ArctosDB/arctos/files/1264816/BulkloadEvent.test.xlsx)

**Comment by dustymc** [comment]
patched in
