### ISSUE TITLE
error while modifying parts

### ISSUE THREAD

**Issue by AdrienneRaniszewski** [ArctosDB/arctos#1254]
I did a specimen search, then chose the "modify parts" option in the "Manage..." menu. Under Option 3: Delete parts, I selected the existing part name I wanted to delete, but left the lot count and disposition as "ignore." I got this error: An error occurred while processing this page! Variable EXISTING_LOT_COUNT is undefined. 

Then I tried selecting the lot count and disposition too, but got the same error.

**Comment by dustymc** [comment]
fixed for next release
