### ISSUE TITLE
Moving cryovials from one freezer box to another

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1255]
In dealing with a freezer box of spilled cryovials, we were faced with the prospect of trying to rescan vials into an existing container that virtually still contained the cryovials in a different order.  I tried to move all contents of this container to a virtual Dummy box in order to rescan them back into the existing box, which did not work, probably because that "dummy" box contained other non-position objects.  So the student assigned a new label and rescanned the tubes into the "new" box. However, we tried one last time to move all contents back to the old label, because we had other data referencing that barcode. It worked, sort of - but the old positions were still in the box. So now, we have a freezer box with two sets of positions, one of which is empty and the other which contains collection objects. I'm pretty sure this isn't supposed to happen. I can no longer edit. Dusty, can you remove the empty positions and keep the ones with collection objects?

Box barcode = DGR18043

**Comment by dustymc** [comment]
2 similar use cases:

1) OOPS! a box of vials. Need "move contents of positions to new container" option. Use that (eg, to move vials to a dummy container, leaving positions empty), then re-scan the vials into the now-empty positions.

2) Freezer dies. Need "move contents of positions to corresponding positions in existing identical container" option.

Add check: disallow container having more positions than number_of_positions.

DGR18043 is cleaned up.

**Comment by dustymc** [comment]
There are lots of ways to accomplish this.

The scary red barcode-swapper on edit container is probably simplest. You can also...

Find a container with positions, even if they have stuff in them

<img width="358" alt="screen shot 2018-11-14 at 9 04 44 am" src="https://user-images.githubusercontent.com/5720791/48499171-ac12a000-e7ec-11e8-9c78-a5a1d9fb7277.png">

find an identical empty container

<img width="957" alt="screen shot 2018-11-14 at 9 04 57 am" src="https://user-images.githubusercontent.com/5720791/48499210-c0ef3380-e7ec-11e8-92ea-61cfdb818121.png">

and just use the "move all children" to move the positions (and anything that's in them)

<img width="319" alt="screen shot 2018-11-14 at 9 00 11 am" src="https://user-images.githubusercontent.com/5720791/48499240-db291180-e7ec-11e8-8d93-1ef80b055b32.png">

**Comment by dustymc** [comment]
>moved both the cryovials and the positions they were in to the new box, which already had positions. T

That is no longer possible; there are checks against contents and position layout.

>the recipient freezer will already have positions. 

If they are not used, you can...

<img width="469" alt="screen shot 2018-11-14 at 9 31 54 am" src="https://user-images.githubusercontent.com/5720791/48500656-41636380-e7f0-11e8-8c59-45dc5b351f79.png">

If they are used then nothing else will fit and no form can possibly help.

I'm pretty hesitant to add a great deal of complexity (and so a great many failure points and a great many perhaps-cryptic errors) for something that happens MAYBE once a year. Worst case, I think it's reasonable to throw a sticky-note on the replacement freezer and deal with the clicking of two buttons the next day.

**Comment by campmlc** [comment]
So as long as the new parent container has positions and the positions are
empty, this will work? And if the new parent does not have positions, they
must be created first?  This should depends on
https://github.com/ArctosDB/arctos/issues/1743 being resolved and we have
the form to create freezer rack positions.

**Comment by dustymc** [comment]
>parent container has positions and the positions are empty, this will work?

Yes, there's a button to remove unused positions (which then lets you modify the layout).

There's no reason to create and delete positions. Only the layout needs to match.

**Comment by campmlc** [comment]
Great, thanks!
