### ISSUE TITLE
verbatim preservation date vs. specimen-events (was: Add attribute to Teach Collections)

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1256]
Please add verbatim preservation date to Teach Attributes.

Thank you!

**Comment by dustymc** [comment]
@Jegelewicz : What are you trying to accomplish?

I don't think verbatim preservation date is necessary in the current model - we can just associate multiple events with a specimen.

AWG : Should we move all verbatim preservation date data to events?

**Comment by campmlc** [comment]
I think verbatim preservation date is useful, especially in the context of
student data entry. Far more complicated to add a new specimen event than
an attribute, and in some cases we don't have much info other than the date
of death.

**Comment by Jegelewicz** [comment]
See comment above.  No need for an event with so little data. This is most applicable to specimens from zoos, etc.

**Comment by dustymc** [comment]
Meh, done. I updated the definition to

>The date the specimen ceased to grow and change, as opposed to the date when it was collected.  Often the date of death. Avoid this in favor of additional specimen_event determinations.

I'm still not really sold on the usefulness of this, but maybe it's better than the non-event alternatives. 

Do we need a "capture" event for those specimens which these data are deemed event-worthy? 

Editing title and leaving open.

**Comment by campmlc** [comment]
Verbatim preservation date was used for thousands of Rausch records in
which the host was collected from the wild on a certain date, kept in
captivity as an experimental host for host/parasite life history research,
and then euthanised at some specified later date in some unspecified
captive facility. It may or may not be useful at some point to go back and
create specimen events for all these, with locality "captive", but  that
would take time from other critical things like getting more of his records
cataloged.

**Comment by dustymc** [comment]
@campmlc at least for those with a vaguely date-like value it should be possible to SQL them. They probably wouldn't be very nice events (=lots of "unknowns"), but they'd be searchable in the context of similar data and easier to improve upon when there's a reason to. 

If you really don't know anything beyond "was captive for a while" then maybe there is no reason to invest much in getting these data more organized.



```
select
  guid_prefix,
  count(*) c
from
  collection,
  cataloged_item,
  attributes
where
  collection.collection_id=cataloged_item.collection_id and
  cataloged_item.collection_object_id=attributes.collection_object_id and
  attributes.attribute_type='verbatim preservation date'
group by
  guid_prefix
order by
  count(*) desc
 16  ;

GUID_PREFIX							      C
------------------------------------------------------------ ----------
UAM:Mamm							   4692
DMNS:Bird							   4447
DMNS:Mamm							   4040
CUMV:Bird							   3564
MVZ:Herp							   1785
MVZ:Bird							   1559
MVZ:Mamm							    411
MSB:Para							    166
UTEP:Bird							    159
MSB:Host							     74
UTEP:Herp							     26
UAM:Herp							     14
MSB:Mamm							      4
DMNS:Para							      1


```

**Comment by Jegelewicz** [comment]
Closing for lack of interest
