### ISSUE TITLE
GenBank/loan/part/specimen linkage

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1257]
Split off from another Issue, starting about https://github.com/ArctosDB/arctos/issues/1084#issuecomment-317576055:

>Here are the parts which have been used in loans that resulted in GenBank numbers. It's not perfect - there's no direct part-->loan-->otherID pathway, so two parts from a specimen might have been loaned and only one produced a GenBank number or the GenBank number came from undocumented usage or etc.

>In my ideal world, I would like a direct part-->loan-->otherID pathway. I want to know exactly which part resulted in a Genbank number.

>A GenBank sequence magically appears, now what? All too often we don't have that middle step in the happy pathway because of incomplete loan data or something done before we got the specimen or because some grad student dug something out of a freezer and didn't tell anyone or ... I still like the idea.

>I also like the idea of part -->loan-->otherID to attach Genbank sequences to loans/parts. Could we use a part attribute= relationship?

Part attributes (presumably in conjunction with the normal pathway) would give you "number of times someone felt like doing some obscure extra step for some strange reason" - probably not quite what you're looking for. If we really want those numbers, I think we just have to commit to doing a better job of tracking loans and the products of loans, and adjust the data structure to reflect that commitment.

Somewhat related, there are a bunch of loan and citation tools under Reports which can help find unrecorded data (there are 600+ MSB specimens with genbank numbers and no loan history, for example). There are a bunch of cross-collection loan/usage stats in the same place - recording part-->loan-->results more explicitly is going to require procedural improvements.  Maybe there's a proposal to host a workshop in those stats - I suspect some of that is collections with better loan procedures who are probably willing to share. (I know some of it is just selective data entry - at least one collection exists solely to record citations, we probably all have resource limitations and prioritize specimens which we know have been used, etc.)

**Comment by campmlc** [comment]
I support pursuing this further.

**Comment by Jegelewicz** [comment]
Also seems like part of #3630 ?

**Comment by campmlc** [comment]
So the mechanism in #3630 is to use stable identifiers in part attributes to link GenBank sequences to loans? How is that currently actionable? We have no easy tools, workflows, or documentation . . .
