### ISSUE TITLE
update links in table of user roles

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#1259]
This page needs updated link to the Arctos handbook:
https://arctos.database.museum/Admin/user_roles.cfm

Some do not have a one-to-one match in the new Handbook (https://handbook.arctosdb.org) so this may require some updating or creation of new entries in the handbook.

If we cannot get volunteers from Working Group to tackle before October (I can work on this after Oct) then I suggest Dusty just remove the deadlinks to avoid confusion.

**Comment by dustymc** [comment]
Scary red box is now....

<img width="1061" alt="screen shot 2017-09-07 at 10 07 23 am" src="https://user-images.githubusercontent.com/5720791/30175673-5d589d44-93b4-11e7-9b13-7936fa2c24e5.png">


and required reading links are....

```
ROLE_NAME||':'||REQUIRED_READING
------------------------------------------------------------------------------------------------------------------------
coldfusion_user:
data_entry: http://handbook.arctosdb.org/how_to/Understanding-data-entry.html
dgr_locator:
global_admin:
manage_agents: http://handbook.arctosdb.org/documentation/agent.html
manage_codetables: http://handbook.arctosdb.org/how_to/Code-Tables.html
manage_collection:
manage_container: http://handbook.arctosdb.org/documentation/container.html
manage_documentation:
manage_geography: http://handbook.arctosdb.org/documentation/higher-geography.html
manage_locality: http://handbook.arctosdb.org/documentation/locality.html
manage_media: http://handbook.arctosdb.org/documentation/media.html
manage_publications: http://handbook.arctosdb.org/documentation/publications.html; http://handbook.arctosdb.org/document
ation/projects.html

manage_specimens:
manage_taxonomy: http://handbook.arctosdb.org/documentation/taxonomy.html
manage_transactions: http://handbook.arctosdb.org/documentation/transactions.html
public:
```
