### ISSUE TITLE
bulkloader will not load

### ISSUE THREAD

**Issue by amgunderson** [ArctosDB/arctos#1262]
I am attempting to approve specimen records in the bulkloader. I hit "Mark all to load", the field "LOADED" is cleared but after a few minutes says waiting for approval again.

**Comment by dustymc** [comment]
What tool did you use, and is there a record or a few I can try to load?

**Comment by amgunderson** [comment]
AJAX, just trying to load the one record entered by rapfaff.

**Comment by dustymc** [comment]
I think it must be your browser (Chrome?? Overenthusiastic caching is my first wild guess) or connection (various IT depts have messed with ajax data at various times) or something.

I checked the record....

```
UAM@ARCTOS> select loaded from bulkloader where enteredby='rapfaff';

LOADED
------------------------------------------------------------------------------------------------------------------------
waiting approval

```
used the AJAX tool...

<img width="315" alt="screen shot 2017-09-07 at 5 21 33 pm" src="https://user-images.githubusercontent.com/5720791/30190864-f3b46100-93f1-11e7-8d6a-4bd4c99b915f.png">

checked back...

```

UAM@ARCTOS> select loaded from bulkloader where enteredby='rapfaff';

LOADED
------------------------------------------------------------------------------------------------------------------------


1 row selected.

````

hung out for a while and...

```

UAM@ARCTOS> select loaded from bulkloader where enteredby='rapfaff';

no rows selected

Elapsed: 00:00:00.52
```
it seems to have loaded

http://arctos.database.museum/SpecimenResults.cfm?entered_by=rapfaff&beg_entered_date=2017-09-07&end_entered_date=2017-09-07

???????????????

**Comment by amgunderson** [comment]
OK, thanks. Closed.
