### ISSUE TITLE
Re-adding Georeferencing Calculator to Locality Edit page

### ISSUE THREAD

**Issue by gordonhlau** [ArctosDB/arctos#1267]
A while back when the georeferencing calculator site was down (http://manisnet.org/gci2.html), it was removed from the Locality Edit page. The site has since been fixed for a while now, but still does not appear on the Locality Edit page. Can it be put back up? This is what the Locality Edit page used to look like when it had the link to the georef calculator:

![arctos_georef_calculator](https://user-images.githubusercontent.com/13543587/30493648-ce16527e-99f9-11e7-9fc5-21b2f23f873f.jpg)

Currently it's missing the georef calculator:

![arctos_no_georef_calculator](https://user-images.githubusercontent.com/13543587/30493758-53820494-99fa-11e7-9536-33bd732eea8a.jpg)

**Comment by dustymc** [comment]
Done.
