### ISSUE TITLE
require loan policy URL

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1271]
I'd like to claim that Arctos provides a communication channel to researchers, and could better support that if loan_policy_url was required. I don't care about the contents of any loan policy, I'm just trying to make links.

Unless there are justified objections I'll make wild guesses, update existing collections to something or other, and change the field to NOT NULL sometime soon. 

Manage Collection or send me data to update to something more predictable.

EDIT: fresh data, 20180308

UAM@ARCTOS> select guid_prefix from collection where LOAN_POLICY_URL is null order by guid_prefix;

GUID_PREFIX
------------------------------------------------------------
APSU:Bird
APSU:Fish
APSU:Herp
APSU:Mamm
COA:Bird
COA:Egg
COA:Ento
COA:Herp
COA:Mamm
COA:Rept
CRCM:Bird
DGR:Bird
DGR:Ento
HWML:Para
KWP:Ento
MSBObs:Mamm
MVZ:Egg
MVZ:Hild
MVZObs:Bird
MVZObs:Fish
MVZObs:Herp
MVZObs:Mamm
NBSB:Bird
NMU:Ento
NMU:Fish
NMU:Herb
NMU:Herp
PSU:Mamm
UAM:Arc
UAM:Art
UAM:Bird
UAM:Env
UAM:Fish
UAM:Herp
UAM:Inv
UAMObs:Bird
UAMObs:EH
UAMObs:Ento
UAMObs:Fish
UC-SCFS:Bird
UC-SCFS:Mamm
UCM:Obs
UMNH:Bird
UMNH:Ento
UMNH:Herp
UMNH:Mala
UMNH:Mamm
UNM:ES
UNR:Bird
UNR:Egg
UNR:Fish
UNR:Herp
UNR:Mamm
UTEP:Teach
UWBM:Herp
UWBM:Mamm
WNMU:Bird
WNMU:Fish
WNMU:Mamm

**Comment by dustymc** [comment]
I want to make the field NOT NULL (because I think a communication channel between users and the collection is a step towards "research grade").

A template sounds useful, but I don't think it's completely necessary. "Send email to some@address.org for more information" is sufficient for my immediate needs, and I'm happy to host that if necessary. I don't think this is a burdensome request, but I'm happy to consider alternatives if it turns out to be.

**Comment by AJLinn** [comment]
Looks like about 10 of these collections listed are Obs collections. These are, I assume, not usually viewable by outsiders and by definition, not available for loan. Is there a way to differentiate between Obs and non-obs collections with this NOT NULL requirement? Or does it matter?

**Comment by ccicero** [comment]
Obs collections are viewable to the public, but definitely not available for a loan. Smaller teaching collections also may not be available for loans. Rather than requiring loan policy URL, what about web link (i.e., link to the collection, department, or institution) - is that required?

**Comment by dustymc** [comment]
Like all collections, the "Obs" distinction is arbitrary. Some obs collections catalog things (ear snips) that would just be specimens at other institutions, they may hold hard-copy media, literature, etc. I don't know if that stuff would be available for loan or not - that's why we need loan policies! "We don't have/loan anything" is a workable loan policy, observation collection or not.

I don't think a link to a website has the same sort of implications for research, but I suppose I'll take that I can get.

**Comment by droberts49** [comment]
@ekrimmel and @dustymc  -- I added ours to our collections metadata; had to get it up on our website first! 

It seems reasonable to require terms for use for each collection and this information would certainly be useful for people accessing the data. Could there be a couple of options, like a drop down menu, where you could either insert the URL for your institution's loans/use policies, or select "collection not available for loan" or "coming soon" (and this one sends you an email reminder to "put it up there already!")?

**Comment by campmlc** [comment]
AWG meeting:
Consensus that this field will be required
Send email to Arctos groups to request that they add this if missing
If no response, we link to the website? curator or cm email?

**Comment by dustymc** [comment]
AWG: yes, require

Email group, request policy

If no response, link to SOMETHING (their webpage if possible??)

**Comment by dustymc** [comment]
Put some stuff in and made this NOT NULL. Please review your collection metadata!
