### ISSUE TITLE
Freezer box positions duplicating

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1274]
Box positions are duplicating for no apparent reason during box creation, rendering the barcode unusable. Help!

**Comment by dustymc** [comment]
I found an empty box...

```
select barcode from container where container_type='freezer box' and institution_acronym='MSB' and container_id not in (select parent_container_id from container) and rownum=1;

BARCODE
------------------------------------------------------------------------------------------------------------------------
DGR13272


```

edited,  changed positions to "100", clicked "positions", clicked "create" and...

```
UAM@ARCTOS>  select count(*) from container where parent_container_id=(select container_id from container where barcode='DGR13272');

  COUNT(*)
----------
       100

1 row selected.

```

and cleaned up
```
UAM@ARCTOS> delete from container where parent_container_id=(select container_id from container where barcode='DGR13272');

100 rows deleted.

```

It's working as intended for me. I need specifics to find the problem - what exactly did you do to get there/how do I recreate it?

**Comment by campmlc** [comment]
Here are three barcodes this has happened with - done by students. Here is
what they tell me: they used Edit container to change container label to
freezer box, which caused positions to autofill to 100. They clicked
Update, closed out the edit window, went back to Find container,refreshed
to see the changeover from container label to freezer box, clicked the box
to open Edit Container again, clicked Positions, and got an error about
problem with positions, abort.
When I go back into Edit Container, I see two sets of positions.
Here are three barcodes this has happened. to in the last few days:

DGR18261
DGR13462

**Comment by campmlc** [comment]
DGR18283

**Comment by dustymc** [comment]
That doesn't line up very well with what I see or how I think positions come into existence. I need to know what buttons are actually being clicked.

**Comment by campmlc** [comment]
This is a recent problem. I'll see if they can replicate it taking
screenshots of every step.
