### ISSUE TITLE
Need new Part_Name in Collection==Herp for formalin fixed specimens

### ISSUE THREAD

**Issue by jtgiermakowski** [ArctosDB/arctos#1277]
Hi,

Please, add
"whole organism (formalin 5%)"
"whole organism (formalin 10%)"

to SPECIMEN_PART_NAME

this is mostly for differently fixed and preserved amphibian larvae as well as some legacy USGS specimens

**Comment by dustymc** [comment]
>whole organism (formalin 5%)

Is that the same as "whole organism (5% buffered formalin)"?

If so, can I match with "whole organism (10% buffered formalin)"?

And definitions please ("whole organism preserved and stored in {part_name}" ??)

**Comment by jtgiermakowski** [comment]
yes, "whole organism (formalin 5%)" is "whole organism preserved and stored in 5% buffered formalin"

but that does not apply to Herp collections, only Fish right now,

so actually just add "Herp" collection type to the following:

whole organism (5% buffered formalin) 
whole organism (formalin-fixed, 55% isopropanol)

**Comment by dustymc** [comment]
done
