### ISSUE TITLE
license URL is broken

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1280]
http://arctos.database.museum/info/ctDocumentation.cfm?table=CTMEDIA_LICENSE

The Arctos Data Ownership and Use license points to http://arctosdb.org/home/data/ which redirects to https://arctosdb.org/join-arctos/data-digitization/, which doesn't seem very license-y.

Any specimen records which have been downloaded will point to http://arctosdb.org/home/data/ - it's probably worth reviving that URL rather than updating the code table.

**Comment by dustymc** [comment]
This remains broken.

**Comment by mkoo** [comment]
If I change to the above URL, then Carla cannot change pages again!
Reshuffling of parent/child and URLs was the cause of this breakage. I will
revert back to previous structure but maintain the menus.

**Comment by mkoo** [comment]
OK, I updated the permalink and stuck in a redirect.
 http://arctosdb.org/home/data/  redirects to our data license now at  http://arctosdb.org/data/ 
Top Menu link still works. Fixed!
