### ISSUE TITLE
download citations from specimen results page

### ISSUE THREAD

**Issue by amgunderson** [ArctosDB/arctos#1283]
I am trying to demonstrate to agencies the broader impact of specimen archival and would like to easily generate a list of publications resulting from their specimens. It would be great if I could download citations, full format not short, from a results page. I am attempting to generate that list from a project and it is so far exceedingly difficult.

**Comment by dustymc** [comment]
Are you asking for a "full publication citations" column in specimenresults or ?? Doesn't sound like a problem, I just need to know what you want to see and how you want to get there.

**Comment by amgunderson** [comment]
yes, that would work, put the full citation (comma delimited for specimens with multiples) in the citations column. The list could be easily extracted from that.

**Comment by dustymc** [comment]
Delimiters which occur in data will likely be problematic; I used semicolon, which might be less-common anyway.

It's here:

<img width="641" alt="screen shot 2017-09-29 at 8 10 38 am" src="https://user-images.githubusercontent.com/5720791/31022519-e196ff52-a4ed-11e7-82c4-602e15dc5600.png">

The data are coming from a function, so it's easy to adjust whatever needs adjusting.
