### ISSUE TITLE
Convert parts in 70% ethanol in freezer to (70% ethanol, frozen)

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1289]
For any of the following, please move anything in a cryovial into a new part as (70% ethanol, frozen)", flagged as tissue:

cestode (70% ethanol) = cestode (70% ethanol, frozen)
nematode (70% ethanol) =  "  "
trematode (70% ethanol)  "  "
acanthocephala (70% ethanol) "  "
endoparasite (70% ethanol) ""
ectoparasite (70% ethanol) "
embryo (70% ethanol) "  "
feces (70% ethanol) "  "
whole organism (70% ethanol) " "
 
Or really, anything in 70% ethanol that is in a cryovial in a freezer.

**Comment by dustymc** [comment]
Is this still active or are those data going to part attributes?

**Comment by campmlc** [comment]
still active until we separate parts from their preservation, which we had
agreed to do.

**Comment by dustymc** [comment]
>until we separate parts from their preservation

You can, as always, do that at any time.

**Comment by campmlc** [comment]
globally.

**Comment by dustymc** [comment]
I'd really love to be wrong here, but I don't think that will happen, at least not under anything remotely like the current model. (We have 3+ ways of saying "tissue" - if we can't unify on THAT....)

If you have those data and are willing to record them, you should forge ahead!

**Comment by dustymc** [comment]
merge>https://github.com/ArctosDB/arctos/issues/1460
