### ISSUE TITLE
Add all Archipelagos to Island Groups and Seas to Higher Geography

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#1290]
We've discussed (but I think never followed up on) adding all the Seas to Higher Geography and using Wikipedia as our authority for them:https://en.wikipedia.org/wiki/List_of_seas.  We are frequently forced to link locality to the country on the shore rather than start with a reasonably specific body of water.  For example, specimens from the Red Sea usually end up in the Indian Ocean for lack of a more specific body of water.

Similarly, it would be helpful to have all Archipelagos listed in the Island Group category.

For example, today we are databasing a specimen from the Diego Garcia Island in the Chagos Archipelago.  I can add Diego Garcia as an island but can't add the archipelago. If the archipelago were already in the Island Group, I would database Diego Garcia as the specific locality rather than adding it as a new island which misses the context of the archipelago.

The Chagos Archipelago is in the Wikipedia list:  https://en.wikipedia.org/wiki/List_of_archipelagos.  If we're not ready to add them all, could you add Chagos Archipelago for our use today?

Also, I noted that Wikipedia uses Malay Archipelago for the country of Indonesia while we use Indonesian peninsula.  If Wikipedia is our authority, would we update this and any others to match Wikipedia?

**Comment by dustymc** [comment]
#1102 requests LIMITING what can be a sea; I'm not aware of other discussions.

I can preemptively create geography from CSV - I just need the relevant data (including wiki link as source). For seas, that's probably just continent_ocean, sea, and source.

I could also just preemptively add to http://arctos.database.museum/info/ctDocumentation.cfm?table=CTISLAND_GROUP (or any other code table) - I'd just need a list of values and a definition (the first paragraph of wiki and the wiki URL is usually pretty good).

Or we could discuss dropping the geographic code table requirements (I'm hesitant to embrace that - seems a good way to end up with 85 spellings of "Langkawi Archipelago"), or getting you code table access, or finding a better pathway to adding code table values, or WHATEVER.

>We are frequently forced to link locality to the country on the shore rather than start with a reasonably specific body of water.

I may be alone in this, but I think that's "wrong," or at least not capable of finding quite what a researcher might be requesting. #1107

>Chagos Archipelago

Done.

>Wikipedia is our authority

I don't think it's that authoritative. It's useful in determining that there is in fact a thing called "Indonesia" and that "Indonesia" is not a novel spelling and etc., but I don't think that authoritativeness extends to asserting parentage and such.

I'm not sure what to do with https://en.wikipedia.org/wiki/Malay_Archipelago - it's somewhat similar to #1278 in that it's an awkward size. Maybe it makes sense in continent or something, but stuffing 25 million square kilometers and a half-dozen countries in somewhere below county-level terms doesn't make much sense to me.

**Comment by dustymc** [comment]
I only added to the code table, which makes Chagos available for use in geography. I think you can create the geog, but let me know if you need any assistance with that.

I don't have strong objections to opening up source if there's a compelling reason to do so. Neither of the examples you listed seem to know what to do with "Langkawi Archipelago" so I suspect we would introduce consistency issues, but we can deal with that if we have to.

**Comment by sharpphyl** [comment]
Thanks for explaining how to use the Chagos entry.  I'll let you know if I
have any problem creating the geography.

Let's see how things go with adding Seas/Archipelagos and whatever else
crops up and then we can decide if it's easier on you for me to have more
access.  Right now I'd rather have everything go through you as there are
still lots of questions about the best structure for much of our marine
geography.

For example:  Where do you want what I'll call "sub-island" groups to go?
Tonga has three major island groups: Vava'u
<https://en.wikipedia.org/wiki/Vava%27u>, Ha'apai
<https://en.wikipedia.org/wiki/Ha%27apai>, and Tongatapu
<https://en.wikipedia.org/wiki/Tongatapu>.
https://en.wikipedia.org/wiki/Geography_of_Tonga   Only Tongatapu is in our
higher geography, but it is an island as well as the name of an island
group.  We would like to add the other two groups, but Tonga Island is
already in all the Tonga entries as the Island Group.  Suggestions?

**Comment by dustymc** [comment]
>"sub-island" groups

Ye olde geographic trashcan, of course....

http://handbook.arctosdb.org/documentation/higher-geography.html#geographic-feature

> Feature may also be used to describe recognized sub-groups of islands

I made features

* Vava'u
* Ha'apai
* Tongatapu

so they'll be there when you need them.

**Comment by sharpphyl** [comment]
Thanks.  I set up Vava'u and Ha'apai, but I think Tongatapu would be confusing so I'll think about that one before I set it up as a feature as well as an island.

While we're at it, could you add Great Barrier Reef as a feature?

Is this the best way to add additional features?

**Comment by sharpphyl** [comment]
Sorry.  I forgot the Wikipedia link for the GBR - https://en.wikipedia.org/wiki/Great_Barrier_Reef

**Comment by dustymc** [comment]
>GBR

Seems reasonable, but as island group or feature?? It's not really an island group, I suppose, but that would set you us to use eg https://en.wikipedia.org/wiki/Murray_Islands as feature/sub-group.

???????????

And no problem to have Tongatapu, Tongatapu (island group, feature) - there are many such things of various flavors already, eg Australia, Australia.

Yes, I think Issues is fine for code table requests in general - other folks are (hopefully!) watching/catching problems before they become problems/can do stuff when I'm not around/etc.

**Comment by sharpphyl** [comment]
Hmmm.  The GBR is both islands and reefs and big.  It's even a marine park.  But I like the idea of being able to add sub-groups of islands within the GBR so let's make it an island group.  We'll learn if that works well or not.  I'll add it to several of the islands already in higher geography.

I'll add Tongatapu as a feature too.  Makes sense - well, sort of.

**Comment by dustymc** [comment]
>GBR

done as island group

**Comment by sharpphyl** [comment]
I started on a .csv list of seas to add to higher geography and ran into questions.  In looking at what is currently in Arctos higher geography, there are inconsistencies that would seem worth aligning before we add more bodies of water to our list.  

First, in the Handbook http://handbook.arctosdb.org/documentation/higher-geography.html the Marine oceans split the Atlantic and the Pacific into North and South.  Many of our entries, however, only use Atlantic or Pacific Ocean.  Are we agreed that we should stick with the North and South distinctions of the Atlantic and Pacific and apply them to all new (and possibly all existing) geographies?  By the way, we're missing the Southern Ocean (and the West Indies) in the handbook but not in Arctos.  

Second, we have a combination of bodies of water that are assigned geographically to oceans and ones that are assigned politically to continents and countries.  For example we have both 
- North America, Chukchi Sea, United States, Alaska and
- Arctic Ocean, Chukchi Sea.  

Similarly, the Caribbean Sea is assigned to North America rather than the North Atlantic Ocean.  This may part of the issue in #1291.  Again, the handbook seems to confirm that seas should be subsets of oceans, but is there a need to identify the landmass by the sea that is leading to seas being created in continents? 

I found the images of seas at http://www.marineregions.org/gazetteer.php?p=search helpful.  See http://www.marineregions.org/gazetteer.php?p=details&id=4274 for the boundaries of the Andaman Sea.  Does anyone know the quality of the data on this website?

Before I start to work on archipelagos and islands that we need, do we agree that they are subsets of the ocean they're in or the country they're assigned to.  For example, I see that we've moved Hawaii out of North America and into the Pacific Ocean.  Same for French Polynesia.  But Malta is assigned to Europe, Mediterranean Sea, Malta.  Does it matter how far removed the island is from the mainland it's assigned to?  The Handbook doesn't seem to address this.  Thanks.

**Comment by sharpphyl** [comment]
Clarification (maybe not):  The Handbook reads "Coastal localities should be described with terrestrial descriptors. For offshore localities, the Higher Geography should include at least the ocean in Continent/Ocean and, if applicable, it should also include Sea."  Do we agree that any marine specimen found up to the high tide line should be considered marine and be assigned to a geography beginning with an Ocean?  This will probably duplicate many terrestrial geographies but be more accurate and perhaps more searchable.  Our thousands of Philippine Island specimens would move from Asia, Philippines... to North Pacific Ocean, Philippines.  (Actually, are the Philippines a subset of the Ocean the same way Hawaii is?)

**Comment by dustymc** [comment]
> Do we agree that any marine specimen found up to the high tide line should be considered marine and be assigned to a geography beginning with an Ocean?

What are we trying to do with geography? Under this definition - and it's not too far from what actually happens - we find 10 things all washed up in a pile on the beach and catalog them under 10 geography entries - the fish, the clam, the marine mammal, the marine mammal which is managed by that other agency, the game animal that just really likes to swim, the plant, etc. are each cataloged under a separate set of rules. And a different institution would use a different set of rules!

The system is almost designed to be unsearchable, then we dedicate half our search page to those unpredictable data. No search involving geography can get a user back to the original pile-o-critters.

The Handbook is mostly an attempt to not make duplicates while doing that. 

Is there any way we can decide on a more unified approach before we write new rules and make a bunch of new geography?

**Comment by ekrimmel** [comment]
I would think better to focus on accurately capturing localities for searching rather than for their properness at this point. Many of our marine shells, for instance, have localities like "Florida," and so I wouldn't be able to necessarily tell you if that means the east coast Atlantic or the west coast Gulf of Mexico. I guess it could go up a level to just "North Atlantic" but that's a huge area (even bigger than the entire coastline of the entire state of Florida.....). 

Ideally in the future most specimens can get georeferenced, or geographically bound by WKT, thus mitigating some of the inherent faults of using geopolitical terms.

**Comment by sharpphyl** [comment]
It sounds like we're comfortable (to some extent) with collections suggesting localities and higher geography that meets their collections specific needs.  Within a few days, I'll have a list of Seas that would be helpful for our collection and then Archipelagos.  If you think we're expanding the geography too much with our suggestions, let's discuss further.

**Comment by dustymc** [comment]
made some marine descriptors, closing
