### ISSUE TITLE
project not found

### ISSUE THREAD

**Issue by mgoliver** [ArctosDB/arctos#1292]
I updated the title of a project being led by Nancy Bigelow to "Landscape and vegetation change at the Birnirk site, Barrow, Alaska", and when I search for it by title or PI it still comes up in the results, but if I click on the title to view the project I get a 404: not found error message that the project isn't there. The link to edit the project still works though.
![screen shot 2017-10-06 at 8 16 42 am](https://user-images.githubusercontent.com/28404497/31287723-bbbc899c-aa6e-11e7-8721-882e57a21e83.png)

**Comment by dustymc** [comment]
Maybe your browser is caching?

I see you trying to access /project/sampling-herbarium-specimens-for-reference-material-to-identify-lake-core-sediment-samples  in the logs. https://arctos.database.museum/project/landscape-and-vegetation-change-at-the-birnirk-site-barrow-alaska works for me. (Same project?)

See also http://handbook.arctosdb.org/documentation/projects.html#changing-title

**Comment by mgoliver** [comment]
Yes, /project/sampling-herbarium-specimens-for-reference-material-to-identify-lake-core-sediment-samples is the same project as /project/landscape-and-vegetation-change-at-the-birnirk-site-barrow-alaska. The second one is correct one. 

Creating a redirect fixed the problem. Thanks!
