### ISSUE TITLE
subsamples' dispositions not "on loan"

### ISSUE THREAD

**Issue by mgoliver** [ArctosDB/arctos#1293]
I created a new loan (with items that were subsampled) and added all to the loan with the button "Create SUBSAMPLES for all parts, add them to this Loan." The disposition for each subsample was originally set to "in collection" rather than "on loan."

**Comment by campmlc** [comment]
I second this - would be great to get this fixed.

**Comment by KyndallH** [comment]
Think it something funky with the button.
<img width="598" alt="screen shot 2017-10-06 at 9 46 51 am" src="https://user-images.githubusercontent.com/16887896/31291180-a73869d4-aa7b-11e7-938b-4c818f41b5fa.png">

I tried it and had the same thing happen.

<img width="598" alt="screen shot 2017-10-06 at 9 46 51 am" src="https://user-images.githubusercontent.com/16887896/31291193-ae11539c-aa7b-11e7-8912-faf655539900.png">

**Comment by dustymc** [comment]
Done for next release
