### ISSUE TITLE
Auto-upload extra identifiers, attributes from data entry

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1294]
We are accumulating many other ids, attributes etc added during data entry that need to be added throught the batch tools bulkloaders. Any way to automate or simplify this process?
e.g. UUID: ac15bafc-e22a-45d5-868a-56450b947c07

**Comment by dustymc** [comment]
I think those are all about 3 clicks, so I'm not sure how they could be simplified.

Automation should be technically trivial (although error handling would require some work) but would essentially involve "approving" data which you can't see (because it's in a separate not-parts bulkloader). I'm not sure that's a problem, but it is something which everyone should be aware of if we go this route.

**Comment by campmlc** [comment]
This needs to somehow be incorporated into the record checks of the main
bulkload file before marking to load. Right now we have to wait for the
main file to load and then go back into to several different batch tool
bulkoaders to independently check and load these as separate data, if I
understand correctly. And this us not being done. At the very least we need
clear documentation and instructions to alter our workflow to make this
happen.

**Comment by campmlc** [comment]
Here is an example of a record with data that still needs to be loaded. How do we make this happen? 
http://arctos.database.museum/guid/MSB:Mamm:291916

**Comment by dustymc** [comment]
>How do we make this happen?

You tell me....

You can load the extra bits from the parts/IDs/whatever loaders, I can auto-load it for you when the specimen pops in, I can send you emails when there's stuff hanging out in the individual loaders, or when the specimen pops in for that stuff, or WHATEVER.

My concerns revolve around review/approval - I don't like the idea of magicking in data that you probably haven't seen. The individual loaders are normalized to the specimen record, so there's no limit on the number of times a student may have clicked an "add another..." button etc.

Should we add this to the AWG agenda?

**Comment by campmlc** [comment]
Yes, please.

**Comment by dustymc** [comment]
EnterData/Bulkloader/Browse and Edit now has an "Extras" option which displays linked data.

EnterData/Bulkloader/Browse and Edit -->AJAX has a new column with a count of linked data. Clicking it opens a summary.

**Comment by dustymc** [comment]
New direction: add this stuff to the core bulkloader
- does it break things like excel?
- where's it fit in the data entry screen?

**Comment by dustymc** [comment]
20 parts
20 attributes
2 part attributes for all

make data entry form data-driven - there's one more row for (parts and such) until you run out

**Comment by campmlc** [comment]
How do we deal with the existing backlog of identifiers/parts etc. that are in Arctos with a uuid?
For example: https://arctos.database.museum/guid/MSB:Mamm:299193

When I go to the bulkload identifiers tool, and click "Manage Existing Data", I have zero records. If I click "check for records entered by people in your collection(s)", I see some records but not all these legacy ones.  What am I missing?


![screenshot 2018-05-10 18 42 17](https://user-images.githubusercontent.com/14808196/39900854-f02017cc-5481-11e8-9cf6-9fe500357ddb.png)

![screenshot 2018-05-10 18 51 07](https://user-images.githubusercontent.com/14808196/39901027-22665f4c-5483-11e8-82fa-278c6b458e70.png)

**Comment by dustymc** [comment]
You're not missing anything, that's the correct procedure, that UUID is not used for any otherIDs (or anything else).

As far as what SHOULD happen, you tell me.

This will find any "extras" by UUID. Just replace the UUID with the one you want and paste it in to Reports/WriteSQL.

```
select USERNAME,count(*) c ,'cf_temp_specevent' tbl from  cf_temp_specevent  where UUID='b16caab2-e272-4019-8eec-d6b8461607ee' group by username
union
select  USERNAME,count(*) c ,'cf_temp_parts' tbl from  cf_temp_parts  where other_id_number='b16caab2-e272-4019-8eec-d6b8461607ee' group by username
union
select USERNAME,count(*) c ,'cf_temp_attributes' tbl from  cf_temp_attributes  where other_id_number='b16caab2-e272-4019-8eec-d6b8461607ee' group by username
union
select  USERNAME,count(*) c ,'cf_temp_oids' tbl from  cf_temp_oids  where EXISTING_OTHER_ID_NUMBER='b16caab2-e272-4019-8eec-d6b8461607ee' group by username
union
select USERNAME,count(*) c ,'cf_temp_collector' tbl  from  cf_temp_collector  where other_id_number='b16caab2-e272-4019-8eec-d6b8461607ee' group by username


no rows selected

```

Here's one that finds something.

```
select USERNAME,count(*) c ,'cf_temp_specevent' tbl from  cf_temp_specevent  where UUID='b16caab2-e272-4019-8eec-d6b8461607ee' group by username
union
select  USERNAME,count(*) c ,'cf_temp_parts' tbl from  cf_temp_parts  where other_id_number='b16caab2-e272-4019-8eec-d6b8461607ee' group by username
union
select USERNAME,count(*) c ,'cf_temp_attributes' tbl from  cf_temp_attributes  where other_id_number='b16caab2-e272-4019-8eec-d6b8461607ee' group by username
union
select  USERNAME,count(*) c ,'cf_temp_oids' tbl from  cf_temp_oids  where EXISTING_OTHER_ID_NUMBER='b16caab2-e272-4019-8eec-d6b8461607ee' group by username
union
select USERNAME,count(*) c ,'cf_temp_collector' tbl  from  cf_temp_collector  where other_id_number='b16caab2-e272-4019-8eec-d6b8461607ee' group by username
```

<img width="211" alt="screen shot 2018-05-11 at 9 03 52 am" src="https://user-images.githubusercontent.com/5720791/39934311-41d87582-54fa-11e8-826a-de3aca604e09.png">


here's everything in the temp tables - not all of it will have a UUID, most is probably just pending or completed-and-undeleted loads.

```
create table temp_pending_extras as
select USERNAME,count(*) c ,'cf_temp_specevent' tbl from  cf_temp_specevent  group by username
union
select  USERNAME,count(*) c ,'cf_temp_parts' tbl from  cf_temp_parts   group by username
union
select USERNAME,count(*) c ,'cf_temp_attributes' tbl from  cf_temp_attributes  group by username
union
select  USERNAME,count(*) c ,'cf_temp_oids' tbl from  cf_temp_oids   group by username
union
select USERNAME,count(*) c ,'cf_temp_collector' tbl  from  cf_temp_collector  group by username
;
```

[temp_pending_extras.csv.zip](https://github.com/ArctosDB/arctos/files/1996072/temp_pending_extras.csv.zip)

You can use ManageArctos/DeveloperTools/CSVFromTable to download any table - eg, cf_temp_attributes.

**Comment by campmlc** [comment]
I'm afraid I don't understand any of those options. I realize it would be
very useful for me to learn SQL, but I've resisted because I think the
majority of Arctos operators would highly resist having to learn it, and
the tools need to be able to accommodate everyone.

I'm confused as to why that UUID exists if it isn't used for anything. Are
students entering UUIDs by accident?
There must have been some data someone was trying to link, and if there is
nothing out there to load, something must have gotten lost. We have a lot
of these.

**Comment by dustymc** [comment]
Agreed in principle, but we'll never have an infinite number of tools to do the infinite number of things that can be done in Arctos!

I'm happy to help you SQL-shuffle things around - eg, if you want to "claim" everything from your users in the CSV I provided or whatever.

Or you can just go through the "claim from my users" process for each of the half-dozen things the bulkloader can write to - that's all the SQL is doing.

UUIDs exist because they were or might have been handy for something - they're just a unique(ish) identifier that can be created at any time. They're in specimen records because someone loaded them (eg, to help find stuff in iDigBio) or because something needs to or already has (or was going to but then was deleted) go in asynchronously, or maybe just because someone clicked the button to see what would happen.

**Comment by campmlc** [comment]
Can I claim everything from MSB users, so I can see what is going on and
how to resolve?
 I'm pretty sure no one else has any idea of what to do. MSB Mammals has
had to create these through student data entry to accommodate extra
attributes, parts, and IDs that won't fit in the standard form. They've
been doing this for a couple of years, and I don't think any of the UUIDs
so created have been resolved to link to the corresponding data. It would
be good to figure out what records have these so we can go back and find
out if data were lost and need to be re-entered.

**Comment by dustymc** [comment]
>Can I claim everything from MSB users, so I can see what is going on and how to resolve?

<img width="917" alt="screen shot 2018-05-11 at 10 53 28 am" src="https://user-images.githubusercontent.com/5720791/39939300-b89f3524-550a-11e8-8ec5-c811150f4977.png">

You have manage_collection, so you can claim anything from anyone with access to any of the collections to which you have access. (That includes me and Carla and anyone else who needs that access for various reasons.) Here's everybody with something that MIGHT be your data - let me know what usernames are "yours" and we can go from there.

UAM@ARCTOS> select distinct username from temp_pending_extras;

USERNAME
------------------------------------------------------------------------------------------------------------------------
BIOKIDRICHY
ELAINEPERRY
LEAC
LFREDERICK
RABZ711
TORIVIOLA
TRUCKEY

ACDOLL
ACHINN
KKMILLS
NOCHOA5
SMLADINICH
CAMPMLC
CWITT
DLM
JEGELEWICZ
KATOBLER
LBOLLING
PBHAKTA
SIERRALROMERO
SOMIYADUNNUM
VKOOMSON
ANDY
CWLINKEM
MROBINSON
AJLINN1910
DEMBOSKI
SALTAMIRANO
SARA
SHANNONOBRIEN
EJOHNSON
CCICERO
EBRAKER
FSKBH1
JMALEY1
KGUTIERREZ
KOLSON36
MAVERY
TEAHAMIRKABIRIAN
ALEXANDERO
SLIPHARDT

**Comment by jldunnum** [comment]
Mariel, let me know if there is anything you want me to help with on this.  Most of the MSB users are mammals students.

______________________________________________________________

Jonathan L. Dunnum Ph.D.
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by campmlc** [comment]
Yes, can you and Adrienne respond on which users are mammals/MSB related?
Then we can get a list of what specimens they entered to try to track down
the data.

**Comment by campmlc** [comment]
Taking a different tack on this:
How do we associate UUIDs we find attached to specimens with something in the Extras bulkloader? 
I keep coming across these and don't know how to resolve them. This particular set is 4 years old, from before there was a clear path to upload the extras post data entry.

http://arctos.database.museum/saved/Bradley%20Tank%20Carlsbad%20MLC

**Comment by dustymc** [comment]
That's definitely not a use case I had in mind....

```
select USERNAME,count(*) c ,'cf_temp_specevent' tbl from  cf_temp_specevent  where UUID in (select display_value from coll_obj_other_id_num where other_id_type='UUID' and collection_object_id in (select collection_object_id from flat where locality_id=10713310)) group by username
union
select  USERNAME,count(*) c ,'cf_temp_parts' tbl from  cf_temp_parts  where other_id_number in (select display_value from coll_obj_other_id_num where other_id_type='UUID' and collection_object_id in (select collection_object_id from flat where locality_id=10713310))  group by username
union
select USERNAME,count(*) c ,'cf_temp_attributes' tbl from  cf_temp_attributes  where other_id_number in (select display_value from coll_obj_other_id_num where other_id_type='UUID' and collection_object_id in (select collection_object_id from flat where locality_id=10713310)) group by username
union
select  USERNAME,count(*) c ,'cf_temp_oids' tbl from  cf_temp_oids  where EXISTING_OTHER_ID_NUMBER in (select display_value from coll_obj_other_id_num where other_id_type='UUID' and collection_object_id in (select collection_object_id from flat where locality_id=10713310))  group by username
union
select USERNAME,count(*) c ,'cf_temp_collector' tbl  from  cf_temp_collector  where other_id_number in (select display_value from coll_obj_other_id_num where other_id_type='UUID' and collection_object_id in (select collection_object_id from flat where locality_id=10713310))  group by username
 10  ;

no rows selected

```
probably already loaded, or whoever entered them deleted them.

**Comment by campmlc** [comment]
Can we find all of these that are not associated with any data, so we can
check against original data sheets and see if data need to be re-entered? I
doubt whoever entered them deleted them, but possibly already loaded.

**Comment by dustymc** [comment]
They're all in the daily email.

**Comment by campmlc** [comment]
Request to have the table that displays records pending upload  display an Other Identifiers field or some sort of identifier so that if there are problems we can go back to our original data records to clarify and resolve. Right now there is no way to know what specimen the part uuid is being loaded if it has not already been cataloged. If something did not get cataloged because of some data entry error or other problem, we cannot track the uuid back and figure out what went wrong. At a minimum, we would need to know the GUID prefix of the collection creating the part uuid and some identifier of the specimen in the related bulkloader.

Currently displayed fields at EnterData/Bulkloader/BrowseAndEdit-->Extras or the individual bulkloaders:

delete | STATUS | GUID | Specimen | GUID_PREFIX | OTHER_ID_TYPE | OTHER_ID_NUMBER | ATTRIBUTE | ATTRIBUTE_VALUE | ATTRIBUTE_UNITS | ATTRIBUTE_DATE | ATTRIBUTE_METH | DETERMINER | REMARKS

**Comment by dustymc** [comment]
Example? I think I'm confused.

**Comment by campmlc** [comment]
I don't know if this is possible, but we need some information linking the specimen in the bulkloader or the cataloged specimen with the uuid that is in the extras waiting to be loaded. Otherwise, we don't have any idea what specimen data these extras are tied to in order to track them down if they fail to load, and these data will be lost.
Also, I loaded one but don't see anything showing up in the corresponding specimen record - is there a 24 delay?

**Comment by dustymc** [comment]
The UUID is the link - that's why it exists. Examples would still be very useful.

**Comment by dustymc** [comment]
Resolved via https://github.com/ArctosDB/arctos/issues/3436#issuecomment-912005715
