### ISSUE TITLE
remove brackets from barcode in loan invoice

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#1295]
Barcode field in loan invoice has brackets around the barcode, so when you click on it, the link doesn't return any records. Are brackets needed? If not, please remove so link works properly.

![image](https://user-images.githubusercontent.com/967275/31350739-2acc7944-acdd-11e7-98ab-c3444433e011.png)

![image](https://user-images.githubusercontent.com/967275/31350764-3a354bf4-acdd-11e7-9523-d8f35da61af3.png)

**Comment by dustymc** [comment]
>"Barcode" is the barcode of the container holding the part, or when enclosed in square brackets the barcode of the container holding the part from which the loaned part was subsampled. 

I think we should probably remove the link for those - the barcode of the "parent" part is included for some reason I'm not sure I understand ( @campmlc, @KyndallH  ???) , and linking to the not-quite-correct thing seems potentially confusing - but ????

**Comment by KyndallH** [comment]
I don't need it linked to any record; I just need the barcode so I can download the barcodes, and I can pull up the location to subsample the loan. I have a curator that adds subsampled tissues to a loan before they are subsampled. Without those bracketed barcodes, I have no easy way to get a list of the samples he'd like subsampled. Not ideal, I know, but I've tried to change the way he requests tissues, and it isn't going to happen.

**Comment by KyndallH** [comment]
And I don't find it confusing. It states very clearly at the top that "when enclosed in square brackets the barcode of the container holding the part from which the loaned part was subsampled".
