### ISSUE TITLE
add parts to Teach collection

### ISSUE THREAD

**Issue by ekrimmel** [ArctosDB/arctos#1298]
I also need the following parts added to the Teach collection:

- nest
- object

I'm using *nest* here for insects, but will also use it for birds. I'll propose the following definition as a starting place, since nest does not yet have one in the code tables:

| part_name | documentation|
| --- | --- |
| nest | a structure created or inhabited by an organism for shelter and/or to raise young |

I'm using *object* for models, and I think the existing part definition is fine for now....

**Comment by dustymc** [comment]
done
