### ISSUE TITLE
Failure to delete encumbered records

### ISSUE THREAD

**Issue by jtgiermakowski** [ArctosDB/arctos#1299]
I followed the directions here 
[(http://handbook.arctosdb.org/how_to/How-to-Delete-Specimen-Records.html)]

and when i click on 

> [ delete these specimens ]

I get:

> fail: listlen(catIdList)=12530 

any ideas?

**Comment by jtgiermakowski** [comment]
no records have citations or media associated with them. btw, the pre-bulkloader worked like a charm, i just need to reload the entire 12,530 specimen dataset.

**Comment by campmlc** [comment]
Here is the problem - I remember now! See issue #1031. You can only do 1K at a time, so can you split the records into a couple of encumbrances?

**Comment by dustymc** [comment]
Just send me the encumbrance (ID, or whatever I need to find it) and I can delete them.

I could move the code to a procedure or etc., but I think someone will inevitably delete the wrong thing - I sort of like forcing people to click unnecessary buttons here....

**Comment by jtgiermakowski** [comment]
Got it! It makes sense to have a limit. I edited the how-to webpage to point that out. [http://handbook.arctosdb.org/how_to/How-to-Delete-Specimen-Records.html](http://handbook.arctosdb.org/how_to/How-to-Delete-Specimen-Records.html)

Dusty, can you please delete all specimens added to encumbrance_id=10000294, there are 12530 records to be deleted. Yes, I know, I should've checked...

**Comment by jtgiermakowski** [comment]
Got it! It makes sense to have a limit. I edited the how-to webpage to point that out. [http://handbook.arctosdb.org/how_to/How-to-Delete-Specimen-Records.html](http://handbook.arctosdb.org/how_to/How-to-Delete-Specimen-Records.html)

Dusty, can you please delete all specimens added to encumbrance_id=10000294, there are 12530 specimens records there...

**Comment by dustymc** [comment]
>edited the how-to webpage

Thanks!

>delete all specimens added to encumbrance_id=1000029

Done.

**Comment by jtgiermakowski** [comment]
¡Gracias!
