### ISSUE TITLE
part cleanup: observation

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1302]
And even less when paired with a non-observation event type.

http://arctos.database.museum/info/ctDocumentation.cfm?table=CTSPECIMEN_EVENT_TYPE

What are we trying to do here?

```
select 
  guid_prefix,
  specimen_event_type,
  count(*)
from
  collection,
  cataloged_item,
  specimen_event,
  specimen_part
where
  collection.collection_id=cataloged_item.collection_id and
  cataloged_item.collection_object_id=specimen_event.collection_object_id and
  cataloged_item.collection_object_id=specimen_part.derived_from_cat_item and
  part_name='observation'
group by 
  guid_prefix,
  specimen_event_type
;
GUID_PREFIX
------------------------------------------------------------
SPECIMEN_EVENT_TYPE
------------------------------------------------------------------------------------------------------------------------
  COUNT(*)
----------
MSB:Host
accepted place of collection
     20683

MSBObs:Mamm
accepted place of collection
	 3

UAMObs:Mamm
observation
	 1

MVZ:Herp
accepted place of collection
	 1

UCM:Obs
observation
       236

UAM:Ento
accepted place of collection
	 1

MSB:Herp
accepted place of collection
	 3

UTEPObs:Herp
accepted place of collection
	 1

MSB:Para
accepted place of collection
     13157

UAMObs:Mamm
accepted place of collection
       197

MVZ:Herp
unaccepted place of collection
	 1

UAMObs:Bird
accepted place of collection
       162

MVZObs:Mamm
accepted place of collection
	28

UAMObs:Ento
accepted place of collection
       220

MSB:Mamm
accepted place of collection
	 1

UAMObs:Mamm
unaccepted place of collection
	 1


16 rows selected.
```

**Comment by ebraker** [comment]
I agree. We should consider more specific part names, e.g., “audio recording,” “video,” and “image” (I generally record whether it is digital or a photograph in part_remarks), or any other observation-relevant values.

**Comment by campmlc** [comment]
The problem seems more an issue of the definition of specimen event.  The
current definition "accepted place of collection" is "removal from the
wild", which doesn't really fit cultural or art collections.   Why did we
go away from "accepted" vs "unaccepted"? It seems like we are trying to do
too many things here and they don't fit all uses.

Also, from our own collections perspective, MSB Host and MSB Para
observation records were created from data from the Rausch collection
ledger. In some cases there are no specimens, but we are in the process of
identifying and linking to actual specimens in MSB and in other
collections. These are all records based on specimens that did exist whose
data were recorded by a competent naturalist and systematist.  If  we move
"observation" to "specimen event", then we have to have separate events for
those records that we find a voucher for vs those that we haven't yet found
a voucher for. This means creating a new event everytime we find a voucher?
Not something I want to have to deal with.

Also, I do not want to replace the part type with something completely
uninformative, like "unknown". If we delete observation as a part type,
then I would request that we add "data" as a part type for these types of
records.

**Comment by dustymc** [comment]
>more specific part names, e.g., “audio recording,” “video,” and “image” 

See https://github.com/ArctosDB/arctos/issues/1131 - those have all been replaced with "media."

>accepted place of collection

See https://github.com/ArctosDB/arctos/issues/1023 - the intention is to move 'acceptedness' to verificationstatus. We're currently doing one thing in various places; #1023 will add normalization.

I'm not sure how to precisely define  a cultural "collection" event, but I don't think that's at issue here.

>separate events for those records that we find a voucher for vs those that we haven't yet found a voucher for

The presence/absence of parts is irrelevant. 

* Rausch killed a squirrel--> "collection" event. There should be parts involved, but we may not know what they are or be able to find them. Not entering parts until we can find them, or entering parts with some sort of "we don't have it" disposition are possible approaches. There should be no later events for this animal; it's dead.
* Rausch saw a squirrel-->observation. There may be parts involved, but they should only be of type "media" (eg, print photo, thumb drive containing digital image, audio recording describing squirrel, field notes or a reproduction thereof in some form, etc.). There may be subsequent events for this animal; it survived the experience.
* Rausch took a biopsy and released the squirrel-->encounter. There should be parts involved, as with "collection" event types we may or may not know what they are and/or have them, and we may or may not have entered them as parts. There may be subsequent events for this animal; it survived the experience.

>add "data" as a part type for these types of records.

Part "media" should contain "data."

**Comment by AJLinn** [comment]
> The problem seems more an issue of the definition of specimen event.  The
current definition "accepted place of collection" is "removal from the
wild", which doesn't really fit cultural or art collections.

From the cultural collections perspective, "place of collection" event is "removal from ethnological/archaeological context" -- akin to "the wild" for biological specimens, but yes, different.

For ethno/history that means the place/date where the object transitioned from being a functional piece to being something else (like a souvenir or keepsake for someone outside of the original context, or a museum artifact). 
For archaeology (and @sjshirar can correct me) it's where/when the object was removed from the archaeological site.
Not sure how Fine Art is planning on defining it.

These could be added to #1023 definitions.

**Comment by campmlc** [comment]
That works.

My only other concern is that lumping all different types of "media"
together as a single part type could cause loss of information content. Do
we have a clear, functioning procedure to search for records with just
audio or just video from the main search screen? I don't think we should
require people to go to search media in it's current state. I'd like to be
able to find Rausch records that have images (media part) as well as record
in the ledger (media part), and I guess I'm not at all clear on this
process.

**Comment by dustymc** [comment]
Parts are "things to which one might stick barcodes" so I'd expect part "media" to represent some sort of physical entity. I doubt these are loaned much except by special arrangement (which hopefully produces a much more accessible digital copy), and I don't think much is lost by having a generic part name supported by remarks representing them.

I believe some (most?) collections manage physical media in dedicated systems outside Arctos, and others manage physical media through the related digital copy (eg, by using media label "barcode" and Arctos object tracking).

Media (the data object, not parts) are separate, and a specimen-->digital media record-->physical media relationship probably makes more sense than a physical media (as parts)-->specimen-->digital media association, even though both are capable of answering the same questions.

Including Media has been simplified in specimensearch.

<img width="308" alt="screen shot 2017-10-16 at 6 24 51 pm" src="https://user-images.githubusercontent.com/5720791/31642366-5f365098-b29f-11e7-8dc7-e5dc0a16b32f.png">

**Comment by Jegelewicz** [comment]
See [working document](https://docs.google.com/document/d/10gvsABpVGRlNCUEDA4oeqP2kPO3A-1iH/edit).

**Comment by Jegelewicz** [comment]
I've been pondering this since the AWG meeting yesterday and I think part of the issue is the way we are throwing around "media" to mean two different things, which @dustymc described above:

- part "media" to represent some sort of physical entity

- Media (the data object, not parts) are separate

I think we need to be more specific with our "media" language and refer to 

- objects or physical media (a printed photograph, paper field notes, magnetic tape with sound recordings) which could be a part [Wikipedia](https://en.wikipedia.org/wiki/Physical_object)
and
- digital media (the stuff we have here - https://arctos.database.museum/MediaSearch.cfm) [Wikipedia](https://en.wikipedia.org/wiki/Digital_media)

Not that this is going to solve all problems, but it may make it much more clear what belongs in "media" and what should be a part and guide those looking for digital representations and those looking for physical things to the right spot.

**Comment by mkoo** [comment]
I think Teresa's parsing captures how at least we are using media-- as two different things. One is a part or can be a record but it's physical. The other is the media we attach to these parts or cat_items. 

So to be clear, Media as object can have media as digital manifestation!

**Comment by ebraker** [comment]
I like this. I think any physical manifestation of media should be documented as parts so they can easily play with other nodes (object tracking, condition and preservation history, traditional vs. data loans, etc.). Maybe "Media" becomes "Digital Media"? 

Another concept to throw in the ring that I was mulling over during our meeting yesterday is that of parent media and child/derivative media. Eg. a ct scan (parent) that has been segmented out into various bones (children). These get hierarchically linked which may help with overall organization and sorting of media results. Not sure how much of a need there is for this though...

**Comment by campmlc** [comment]
Of course, that's an argument for treating digital media as parts :)

**Comment by Jegelewicz** [comment]
HAHAHA! yep - I also struggle with the "stuff you can stick a barcode to" as "parts". Dusty has repeatedly stressed to me that parts ARE barcodes and really, we NEVER attach barcodes to parts - we attach them to containers that we put the parts in. Doesn't that exactly describe a file (part) in a directory (container) at TACC? I am kinda unclear on why we treat these two types of evidence differently (other than one is conveniently displayed on my computer).

**Comment by dustymc** [comment]
We can always be more clear, but every language - including Arctosian - has some homonyms. Given a word out of context, you should have an expectation of limited precision in guessing what it means. I don't see any huge conflicts between Media-the-node and media-the-table and media-the-part - you need context to understand any of them - but maybe I'm just a 'native speaker.'

> physical manifestation of media should be documented as parts 

Change "media" to "anything" and yes, that's why "parts" exist, they are the one and only bridge between the digital and physical.

>parent media and child/derivative media

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctmedia_relationship#derived_from_media

>treating digital media as parts 

I cannot see how this is anything but choosing the wrong datatype - explain?

>Dusty has repeatedly stressed to me that parts ARE barcodes

Nope. Parts are **containers**. Those are not interchangeable, especially given that the type of container which is also a part cannot have barcodes.

>we NEVER attach barcodes to parts

Exactly - they're all slimy and keep jamming the printer, hence ^^ that.

>exactly describe a file (part) in a directory (container) at TACC? I

No, I think, but hu?

>unclear on why we treat these two types of evidence differently

There is something in that, but it's somewhere beyond the first layer, where one's "something you can stick a barcode to" and one isn't. Neither are capable of describing their own value as evidence beyond "some sort of depiction" (or something) - "not a hunk of the item itself" (ish). Both the 35mm slide and the TIFF can contain the same evidence, you just need a different mechanism to locate them. (And the TIFF can be on a thumb drive that's cataloged as a part, so "digital" is not a useful distinction.)

**Comment by Jegelewicz** [comment]
> the TIFF can be on a thumb drive that's cataloged as a part, so "digital" is not a useful distinction.)

Again, the thumb drive is just a container...

**Comment by Jegelewicz** [comment]
I think we have to recognize somehow that all of the digital media we have are still "things" we have to account for. The fact that I am unable to explicitly loan digital media as we have it set up now is a bit troubling to me. We spend so much time worrying about attribution, yet we are placing all of the hard work created through "digitization" out in the world for anyone to take and do with as they please. At least with physical objects someone has to ask for the stuff and we know (ostensibly) where it went and when we can expect it back.

With all of the money and time being spent on the creation of these digital objects, our institutions are eventually going to ask us to show how it benefits THEM. I'm not sure we will ever be able to do that, but I also think that we need to make an effort. Just as I complain about the curators of old who sent stuff off willy-nilly to their buddies, future collection managers are going to complain about how loosely we treated this stuff. No answers here, but I think we should be considering this as we pile up huge amounts of digital assets that feel free, but definitely are not. And FWIW, I am pretty sure that most collections don't have all of their expensive digital assets (CT scans, hi-res images, etc) lingering around where anyone can get them.

**Comment by dustymc** [comment]
>"things" we have to account for

Yes, and pay for - digital stuff should be treated more like freezers and cases and bones, and I don't think NSF et al. would argue with the right presentation of that.

>unable to explicitly loan digital media 

Issue; no disagreement (nor clever ideas at the moment) from me. An actual use case would be exceedingly useful.

>take and do with as they please

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctmedia_license is part of that, but it's not quite a replacement for some formal loan-like approach either.

**Comment by campmlc** [comment]
Treat media as parts and loan as we do parts. What breaks?

**Comment by Jegelewicz** [comment]
>     unable to explicitly loan digital media
> 
> Issue; no disagreement (nor clever ideas at the moment) from me. An actual use case would be exceedingly useful.

I don't have a real-world example, but was just thinking about a collection of digital art or NFTs. Such a collection would absolutely need a way to record loans of its digital media.

Speaking of NFTs - https://www.mapress.com/mt/article/view/megataxa.6.2.2

**Comment by mkoo** [comment]
I have lots of examples of 'media loans' or rather license agreements. Once
I have the archives in the Arctos it'll be more obvious (I hope). There are
invoices and correspondence associated with these transactions just like a
regular specific loan.
Meanwhile we made projects to track this :
ex: https://arctos.database.museum/project/10003327

This is one of the use cases when I think being able to associate a project
with a collection or indicate who initiated the project would be useful. At
the moment we just have standardized title prefixes so we can find these
again. I just realized I should link the article since it's published now!

**Comment by campmlc** [comment]
It still concerns me to have two entirely different procedures to track and
loan physical vs digital objects. This makes more work and complicates
workflows, training and documentation. I'd still like to know what breaks
if we treat digital objects in directories as parts with object tracking
which can be tracked via loans. Just need to associate urls with parts?

**Comment by campmlc** [comment]
We discussed yesterday that we'd need to keep media as parts on local
sever. That is problematic. But is there no way around this? What about if
we had a certain amount of private media storage by collection, to eg an
allocation of both public and private media through the mou, and
collections that want to increase their private media can do so through
Arctos?

**Comment by dustymc** [comment]
>collection of digital art

I doubt they have anything quite like dead rat<-->high resolution scan of a small bit of said dead rat relationships, but IDK. Would be good (or necessary) to get some diverse input.

>associate a project with a collection or indicate who initiated the project

That can all happen right now, some if it's even unavoidable.

>different procedures

One involves a change to your collection. I'm not sure what that means for data modeling, but they are different situations.

>keep media as parts on local sever. 

I do not know what this means.

>private

https://github.com/ArctosDB/arctos/issues/1328

**Comment by AJLinn** [comment]
I"m having a hard time following this discussion in written format. Is there a committee meeting coming up that I can attend?(sorry I had to miss the AWG meeting this week - last week before my kid starts school so lots of competing needs) If not, maybe I can have a zoom with you all (@dustymc @campmlc @Jegelewicz @mkoo @ebraker ) so I can understand the problem that is trying to be solved and explain how the UAM cultural collections envision / use media and what the potential implications might be of the proposed changes?

Like Michelle, I make dozens of media loans each year for publications so if there are proposed changes that are going to alter this process I need to be able to fully understand what's happening and the reason why.

And yes, while I don't think our fine art collection has any digital art yet (aka "time based media" - please look it up if you need to acquaint yourself with the concept) it's only a matter of time before we acquire some for our permanent collection.

**Comment by Jegelewicz** [comment]
@AJLinn yes, we are meeting on the 26th at 11AM MDT in the Arctos zoom room - it's on the Arctos calendar too! It would be great to have you there - also, we REALLY need someone to document how they handle media loans.

**Comment by AJLinn** [comment]
Cool, I’ll be there. I can definitely help work out the documentation for media loans!

**Comment by Jegelewicz** [comment]
>  I can definitely help work out the documentation for media loans!

@AJLinn if it makes it easier, you can just write up a Google or Word Doc and I can do the translation to the handbook format.

**Comment by mkoo** [comment]
@Teresa Mayfield ***@***.***> is this the meeting currently
marked as Arctos Karytype on the 8/26? Or another one?

Let us know if there's a media-focused discussion to attend.
Thanks!

**Comment by Jegelewicz** [comment]
> is this the meeting currently marked as Arctos Karytype on the 8/26?

Yep - changed the title to make that more apparent

**Comment by Jegelewicz** [comment]
@dustymc this is a mess of stuff - can we return to the original issue and get rid of "observation" as a part? Step one - who is still using it?

**Comment by Jegelewicz** [comment]
OK so change all disposistions to "not applicable"?

**Comment by campmlc** [comment]
MSB Host and MSB Para will need a different solution. Please do not change observation parts to whole organism for these collections. We need a clear way to distinguish records that were transcribed from observations in the Rausch ledger from records with actual parts. There is too much legacy data in here that can be affected by blanket changes. I'll need to spend some time considering this and don't have bandwidth right now.

**Comment by campmlc** [comment]
@msbparasites

**Comment by ebraker** [comment]
@dusty - I'd prefer "media" vs whole organism for all UCM observations (I'm totally fine with auto-adding "representation" in the part_attribute). Sorry, hadn't made the switch b/c hadn't put in a github request to add part name =  "media" to observation collections.

**Comment by dustymc** [comment]
This can't be active, there's a term that can't make sense and an objection to getting rid of it, going to AWG for help. Suggest this get prioritized; our messes inspire more messes.

**Comment by dustymc** [comment]
@campmlc for MSB: check part remarks for part name, use that when possible. Use unknown when nothing can be found. Change disposition to ??????something????

@ebraker can I just flip UCM to 'media' (I think there was more to that??)

**Comment by dustymc** [comment]
AWG discussion: https://docs.google.com/document/d/1VEUSR-8UK0-9WeFOyiJDRit9UCIDJbq-HMpXUbBRvm8/edit#

Fresh data:

[temp_part_obs.csv.zip](https://github.com/ArctosDB/arctos/files/9932510/temp_part_obs.csv.zip)

Summary:

```

 guid_prefix | nrecs 
-------------+-------
 MSB:Host    | 22716
 MSBObs:Mamm |     3
 MSB:Para    | 14171
 MVZObs:Herp |     1
 MVZObs:Mamm |    28
 UAM:Ento    |     1
 UAMObs:Bird |   162
 UAMObs:Ento |   219
 UAMObs:Mamm |   198
 UCM:Obs     |   303
```

Contacts:


 @ebraker
 @mkoo
 @campmlc
 @amgunderson
 @DerekSikes
 @cjconroy
 @jldunnum
 @msbparasites
 @mlbowser

**Comment by Jegelewicz** [comment]
From AWG today:

> We need something to track? Something that allows for independent verification? 
> See also https://docs.google.com/document/d/10gvsABpVGRlNCUEDA4oeqP2kPO3A-1iH/edit
> Confounding of physical objects and virtual things in the parts table plus distance of parts from event.
> Parts could have, can or could be held in your hand. (involves atoms)
> Not-parts - could not, cannot and probably will never be held in your hand (does not involve atoms)
> Need part modifiers for media parts
> Change observation parts to media with appropriate modifier or the actual part with the disposition “not applicable” - I think this is what will happen, but also use qty = 0
> Definition of unknown - The object was collected at one point but it was never received by the collection and its location is not known.
> Definition of missing -The object was in collection at one point but it cannot be found.  
> Need a media/observation meeting - set a meeting
>

**Comment by Jegelewicz** [comment]
I went for a walk and it occurred to me that the terms in [processing history](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctprocessing_history) may apply AND that some of them may not make sense at the record level (where they currently are).

For example verified presence at the record level only works when there is one part or all parts are in one place but it also seems like a disposition to me.

**Comment by dustymc** [comment]
Discussion: https://docs.google.com/document/d/1hhbQHWXFvO2ax_jzrHLQwYUUAg6F0iH_18XBXqsppec/edit

Data with more details:

[temp_part_obs(1).csv.zip](https://github.com/ArctosDB/arctos/files/10107967/temp_part_obs.1.csv.zip)


Summary

```

 MSB:Host    | deaccessioned        | collection            |     1
 MSB:Host    | unchecked            | collection            | 21230
 MSB:Host    | subsampled           | collection            |     1
 MSB:Host    | discarded            | observation           |    15
 MSB:Host    | discarded            | collection|collection |     1
 MSB:Host    | discarded            | collection            |  1102
 MSB:Host    | not applicable       | collection            |     2
 MSB:Host    | being processed      | collection            |    17
 MSB:Host    | in collection        | collection            |   301
 MSB:Host    | used up              | collection            |    45
 MSB:Host    | unchecked            | collection|collection |     1
 MSBObs:Mamm | in collection        | collection            |     3
 MSB:Para    | missing              | collection            |    35
 MSB:Para    | not applicable       | collection            |     2
 MSB:Para    | on loan              | collection            |     2
 MSB:Para    | in collection        | collection            |   639
 MSB:Para    | discarded            | collection            |     7
 MSB:Para    | unchecked            | collection            | 13433
 MSB:Para    | being processed      | collection            |    53
 MVZObs:Herp | being processed      | observation           |     1
 MVZObs:Mamm | in collection        | collection            |    28
 UAM:Ento    | in collection        | collection            |     1
 UAMObs:Bird | in collection        | collection            |   161
 UAMObs:Bird | being processed      | collection            |     1
 UAMObs:Ento | unchecked            | collection            |    87
 UAMObs:Ento | in collection        | collection            |     1
 UAMObs:Ento | not applicable       | collection            |   131
 UAMObs:Mamm | unchecked            | collection            |     1
 UAMObs:Mamm | being processed      | observation           |     1
 UAMObs:Mamm | in collection        | collection            |   188
 UAMObs:Mamm | being processed      | collection            |     4
 UAMObs:Mamm | in collection        | collection|collection |     1
 UAMObs:Mamm | in collection        | observation           |     3
 UCM:Obs     | in collection        | observation           |   297
 UCM:Obs     | in collection        | collection            |     6

```

If there are no objections or further requests I'll update part_name 'observation' to part_name 'media' about 2022-12-12.

**Comment by cjconroy** [comment]
Sometimes observations are just that, an animal documented by trapping or sight at a place and time. And there is no media to back it up. Why would you change those observations to Media?

**Comment by dustymc** [comment]
See https://github.com/ArctosDB/arctos/discussions/5250 in addition to the linked document. The part name is nonsensical (but if it's available it gets used so here we are). I'm happy to make other changes, or the data provided should be easy to feed to various bulk tools. Part media (intended to track a thumb drive or photo or such) probably isn't correct for most of these, but it's not completely self-conflicting either; it *can* be used defensibly and it was determined that that's what's necessary to escape this situation.

**Comment by Jegelewicz** [comment]
@cjconroy no part is required - it would be fine to just remove those parts if that is an option for you.

**Comment by Jegelewicz** [comment]
> I'll update part_name 'observation' to part_name 'media' about 2022-12-12.

This directive came from the @ArctosDB/observation-interest-group

**Comment by ebraker** [comment]
@dustymc I've updated the 6 UCM outlier records where specimen_event_type=collection to specimen_event_type =observation so everything is consistent. For all UCM:Obs records, basis_of_record can be updated to human observation.

**Comment by dustymc** [comment]
```
 
arctosprod@arctos>> update cataloged_item set cataloged_item_type='human observation' where collection_id=(select collection_id from collection where guid_prefix='UCM:Obs');
UPDATE 303

```

**Comment by dustymc** [comment]
Fresh CSV
 
[temp_part_obs(2).csv.zip](https://github.com/ArctosDB/arctos/files/10210369/temp_part_obs.2.csv.zip)

done

**Comment by ccicero** [comment]
@dustymc @Jegelewicz 

What were the criteria for the records that were changed? Was it where specimen_event_type = 'collection' and/or disposition = 'in collection' I don't see MVZObs:Bird in the temp file so I'm not sure what the criteria was for records that were changed, as we have a lot of observational data.

I'm checking some records and the event type is 'collection' e.g., https://arctos.database.museum/guid/MVZObs:Bird:1000. All MVZObs: records should have an event type of 'observation'

If we're adding a part name of 'media' to observational records, then can you also add part of 'media' to MVZ:Obs records where there is a linked media (image, audio)? Or what is the part 'protocol' for those types of records? Records without a linked media should not have a part of 'media' or any other part.

**Comment by Jegelewicz** [comment]
@ccicero I may be wrong, but this issue only applied to any records that included the part "observation".

**Comment by dustymc** [comment]
>criteria

https://github.com/ArctosDB/arctos/issues/1302#issuecomment-1329836910

``update part_name 'observation' to part_name 'media' ``

>don't see .. in the temp file 

Then they didn't have part=observation (and yay you!)

> can you also 

I'll split this out, no reason to taint anything by being around this mess....
