### ISSUE TITLE
identifications bulkloader can't load A-string IDs

### ISSUE THREAD

**Issue by ekrimmel** [ArctosDB/arctos#1303]
I need to load a handful of identifications that include some of the A-string format, e.g. "Aphrophora {inflata}" and the bulkloader can't deal with them. The bulkloader told me to file an issue, but I'm also happy to just have the help of @dustymc.

I don't want to create new names for identifications like the one above because I can't find a good source to indicate when they were ever valid.

**Comment by dustymc** [comment]
The ID bulkloader will handle A {string} for next release. Try it with a few records first, please.

It will use the same handler as http://handbook.arctosdb.org/documentation/bulkloader.html#taxonomy - you probably want "Aphrophora {Aphrophora inflata}" which will link to taxon Aphrophora and diplay as identification Aphrophora inflata. (Your example would display as "inflata.")

Aphrophora inflata fails "the Google test" so I suspect your caution is justified. Thanks!

**Comment by ekrimmel** [comment]
@dustymc is there a date for this next release so I know when to try bulkloading my identifications again? thx!

**Comment by dustymc** [comment]
I will try to get it out tonight.

**Comment by ekrimmel** [comment]
No rush! I just like making lists and want to know if it should go on my now list or my later list
