### ISSUE TITLE
Request to merge agents

### ISSUE THREAD

**Issue by jtgiermakowski** [ArctosDB/arctos#1305]
Please merge R. B. Bury (21285790) with R. Bruce Bury (10001903). 
Please merge A. L. Fitzgerald (1005) with Austin L. Fitzgerald (21302412).

They are the same persons as far as MSB:Herp (and probably many other collections but I can't tell...)

Thanks, Tom

**Comment by dustymc** [comment]
http://handbook.arctosdb.org/documentation/agent.html#deletingmerging-agents

**Comment by jtgiermakowski** [comment]
Followed handbook. Next time I'll RTFM...

saludos, T.
