### ISSUE TITLE
What's wrong with this record?

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#1308]
@dustymc can you figure out what is wrong with this record to explain why it's not showing up when I copy/paste the URL to share with folks?
http://arctos.database.museum/guid/UAM:EH:UA2017-006-0077AB

It sends you to an Arctos 404: not found page. But I copied the URL from the specimen detail window! It seems to hinge on whether the user is logged in as an operator or not logged in as public user.

![ss_bentwoodbox](https://user-images.githubusercontent.com/17605945/31917773-d0124554-b805-11e7-9969-ce204fb0d7df.jpeg)

**Comment by dustymc** [comment]
> Entered By: Angela Linn on 2017-10-23 

Records generally find their way to the public portal the night after they're entered - it should be there tomorrow.

**Comment by AJLinn** [comment]
Ah ha! Sorry, didn't realize that. Thank you!
