### ISSUE TITLE
view loan status on catalog record

### ISSUE THREAD

**Issue by ekrimmel** [ArctosDB/arctos#1312]
We would love to see the loan status displayed next to the loan number on a catalog record page, e.g. [this](http://arctos.database.museum/guid/CHAS:bird:2016.5.482) bird has been a part of 3 loans and it would be nice to know which of those are currently active vs. closed. It could be something as simple as showing *"[Loan 2017.18]() (open)"*.

Did I miss anything, @droberts49?

**Comment by droberts49** [comment]
No, didn't miss anything! It would make it a easier to see which is the active loan. Additionally, it would be useful as a double check on the specimen record level to make sure loans are properly closed too.

**Comment by dustymc** [comment]
<img width="640" alt="screen shot 2017-11-03 at 11 48 00 am" src="https://user-images.githubusercontent.com/5720791/32390761-e3ac76a4-c08c-11e7-9ff8-017e50338d1d.png">

**Comment by ekrimmel** [comment]
Can we also pretty please add a sort so that the open loan consistently shows up first? For example, see [CHAS:Teach:E2017C.397](http://arctos.database.museum/guid/CHAS:Teach:E2017C.397) vs. [CHAS:Teach:E2017C.398](http://arctos.database.museum/guid/CHAS:Teach:E2017C.398)
