### ISSUE TITLE
How to bulk modify or delete "Other identifiers"?

### ISSUE THREAD

**Issue by jtgiermakowski** [ArctosDB/arctos#1313]
I'd like to get rid of a particular identifier from a group of specimens. For example

http://arctos.database.museum/guid/MSB:Herp:98676

has both 
ID Type="collector number" Prefix=CLL0065
ID Type="collector number" Prefix=CLL ID Number=65

Is there a way to delete the first record (where "collector number"="CLL0065") for a suite of specimens? I have a file with matching MSB:Herp and collector numbers to delete. 

thanks, Tom

**Comment by dustymc** [comment]
Not currently possible. Can you send me CSV of the old? I'll delete, you can bulkload the new.

**Comment by jtgiermakowski** [comment]
Sent file via email. Thanks!
We'll be more diligent with bulkloading collector numbers.
