### ISSUE TITLE
Fiji geography

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#1314]
Fiji is divided first into four Divisions.  https://en.wikipedia.org/wiki/Local_government_in_Fiji
Central, Northern, Western and Eastern.  In Arctos, we have listed Eastern, Western and Northern but as Provinces rather than Divisions.  
The four divisions are divided into 14 provinces.  
We are trying to add the Limaiviti Province which is part of the Eastern  Division.  We also want to add the island Ovalau in that Province.
The current closest entry is Pacific Ocean, Fiji, Eastern Province (state), Island Group: Fiji Islands, Island: Kandavu (island).  
If I enter it correctly, it would be Pacific Ocean, Fiji (country), Eastern Division (state), Lomaiviti Province (county), Lomaiviti Islands (Island Group), Ovalau (Island).  Our specific locality is Naikorokoro, a town on Ovalau.  
To be accurate, the three provinces should be changed to Divisions (and we could add the Central Division). the provinces could be added now or when needed.  Would it be correct to put these under "County" since the Divisions have been entered at the State level?   Then we could add islands as needed within the Provinces.
As noted above, the Lomaiviti Province consists of the Lomaiviti Islands but we've already used the Island Group field with the Fiji Islands.  Is it always necessary to use this field if the Island Group and the Country are identical?  (The Philippines are another example of this.)  With island countries, it's often helpful to identify island subgroups.  I know they could be entered as features if necessary.

**Comment by dustymc** [comment]
Ignore both local "ranks" and Arctos column names. "State" is second-level administrative division, "county" is third.

http://handbook.arctosdb.org/documentation/higher-geography.html#state--province
http://handbook.arctosdb.org/documentation/higher-geography.html#county

>three provinces should be changed to Divisions

My preference is almost always to ignore embedded ranking terms, but that's not always possible or practical. I'd probably use "Fiji, Eastern, Lomaiviti" but understand if you think that's too vague/awkward. Your call - if there's a universal "correct" we haven't found it.

>Island Group

Would a polygon of the island group and a polygon of the country which shares the name be identical? If so, maybe the island group isn't necessary.

**Comment by sharpphyl** [comment]
It looks like Fiji and Fiji Archipelago (or Fiji Islands) are one in the
same so a polygon would be identical.

Source:  Online Encyclopedia Brittanica - https://www.britannica.com/
place/Fiji-republic-Pacific-Ocean

*"Fiji**, *country and archipelago in the South Pacific Ocean
<https://www.britannica.com/place/Pacific-Ocean>. It surrounds the Koro Sea
<https://www.britannica.com/place/Koro-Sea> about 1,300 miles (2,100 km)
north of Auckland <https://www.britannica.com/place/Auckland-New-Zealand>, New
Zealand <https://www.britannica.com/place/New-Zealand>.  The archipelago
consists of some 300 islands and 540 islets scattered over about 1,000,000
square miles (3,000,000 square km)."

I'm fine with omitting "Province" from the current entries which
essentially elevates them to be the Divisions.  Then we can add the
Provinces in the next column (county). I agree we shouldn't use the
descriptor "state," "county," or whatever, but the instructions (see your
links above) states: "Localities should be referenced to county, parish or
equivalent political subdivision when possible."  Doesn't that encourage
the use of the descriptive political subdivision, at least at the lowest
level?

**Comment by mkoo** [comment]
@sharpphyl @dustymc OK, I can help with this. but to make sure I'm clear:

- remove term 'Province' when referencing the four primary divisions
- replace IslandGroup to the next nearest archipelago since 'Fiji Islands' is redundant with Country=Fiji
- the end goal is  Pacific Ocean, Fiji (country), Eastern Division (state), Lomaiviti Province (county), Lomaiviti Islands (Island Group), which has a reference https://en.wikipedia.org/wiki/Lomaiviti_Province
as well as Ovalau (island) https://en.wikipedia.org/wiki/Ovalau_(Fiji)
- in terms of #1316 maybe a note that when a descriptor/ qualifier is in common usage that should take precedence. For example we dont normally say California State so California is the value. Eastern Division is commonly the reference for the Fiji 1st order administration so Eastern Division is acceptable.

**Comment by sharpphyl** [comment]
There are two parts to this issue and I think we've resolved the question around using qualifiers for province, division, region, etc. at least for Fiji and that someone (Michelle?) has that one on a TODO list.  But I don't think our GeoGeekGroup finalized whether or not to eliminate entries under ISLAND GROUP when they are identical to (and contiguous with) the country:  Pacific Ocean, Fiji, Fiji Islands.  

Previously, we identified Fiji's Lomaiviti Islands as an example where it would be helpful to have access to the ISLAND GROUP field.

I'm about to database a number of specimens from the Yasawa Islands in Fiji.  Our current entry in higher geography reads: Pacific Ocean, Fiji, Western Province, Fiji Islands, Yasawa Islands.  Yasawa Islands is entered in the ISLAND field.  (Yes, it should be Western Division if we want to use any qualifier.)

But the Yasawa Islands are an archipelago of 20 islands within Fiji https://en.wikipedia.org/wiki/Yasawa_Islands.  The largest of them is Yasawa Island https://en.wikipedia.org/wiki/Yasawa which could appropriately be placed in the ISLAND field.  But our specimens are from the island chain and not just from that one island.  

I'm proposing that we adjust Fiji to NOT repeat the island group Fiji Islands and ask Dusty to move the Yasawa Islands into the ISLAND GROUP field.  At this time, only our collection DMNS:Inv is using the Yasawa Islands entry.  If this doesn't cause any problems and works well for everyone, then we could consider making similar adjustments in other countries.  This just happens to be the first one with a number of specimens that I would like to database more accurately.

**Comment by dustymc** [comment]
>using qualifiers

I think we're still at the existing guidelines (http://handbook.arctosdb.org/documentation/higher-geography.html#guidelines-for-geographic-terms-in-arctos): 

>Be consistent. At the largest practical scale (usually ~country), do the same thing for all records. For island nations, ensure that the island data are consistent. Ensure all county-level records include qualifiers (County, Parish, etc.) or that none do.

>eliminate entries under ISLAND GROUP when they are identical to (and contiguous with)

I think we're OK in principle, but I'd like to have explicit global guidelines (eg, also apply to things other than country<-->island_group, or guidelines which eliminate any other combination, or SOMETHING) meant to enforce the Prime Directive ("Scrupulous consistency is essential"). 

Fiji seems straightforward - the two things spelled "Fiji" are pretty much interchangeable (at least until the Canadians invade and take over a couple islands in the Fiji Islands group).

Australia-the-country controls the Australian Antarctic Territory, which is nowhere near Australia-the-continent - choosing which "duplicate term" to eliminate isn't completely arbitrary.

Is that all covered by

* Terms which replicate both string and spatial data may be eliminated. For example, "Fiji" (country) and "Fiji Islands" (island_group which contains the string " Islands" only by convention) may be entered only as "Fiji" (country), thereby freeing "island_group" for smaller island groups within the island group which also serves as a country. Always follow the "Scrupulous consistency is essential" guidance in this operation; whatever is done must be done consistently at the largest possible scale. 

?

**Comment by dustymc** [comment]
>Yasawa Islands

I added to CTISLAND_GROUP and added a bullet point to the guidelines:

    ** Do not use Arctos fields for data which are not categorically appropriate. Do not use island for an island group, for example.

Pacific Ocean, Fiji, Western Province, Fiji Islands, Yasawa Islands needs altered to use the island group, which will need to be done in conjunction with updating all Fiji data.

**Comment by sharpphyl** [comment]
Dusty, your guideline addition sounds good to me and I do agree with the “scrupulous consistency” edict, though I’ve probably broken it more than once.

If we want to have a fairly complete Fijian geography, I would suggest that, in addition to Yasawa Islands, we add the three other major archipelagos:

Mamanuca Islands - https://en.wikipedia.org/wiki/Mamanuca_Islands (in the Western Division)
Lomaiviti Islands - https://en.wikipedia.org/wiki/Lomaiviti_Islands  (in the Lomaiviti Province in the Eastern Division)
Lau Islands - https://en.wikipedia.org/wiki/Lau_Islands - (in the Lau Province in the Eastern Division)

Also, in looking at what we currently have, there’s one confusing entry and I’m pretty sure it’s my error.

Pacific Ocean, Fiji, Eastern Province, Fiji Islands, Lomaiviti

Lomaiviti is a province in the Eastern Division and it’s an archipelago known as the Lomaiviti Islands.  It isn’t an island.  I created that entry in a failed attempt to identify the archipelago which contains Ovalau - the island we really want for our specimen.  Again, we’re the only ones using this entry.  If we add Lomaiviti Islands as an island group, it would read Pacific Ocean, Fiji, Eastern Division, Lomaiviti Islands.  We can add Ovalau as the island as a separate entry.  

Re: "Australia, Australia.”  Has there been any consideration of using Oceania instead of Australia as the continent?  https://en.wikipedia.org/wiki/Oceania.  


On Dec 18, 2017, at 10:54 AM, dustymc <notifications@github.com> wrote:

using qualifiers

I think we're still at the existing guidelines (http://handbook.arctosdb.org/documentation/higher-geography.html#guidelines-for-geographic-terms-in-arctos <http://handbook.arctosdb.org/documentation/higher-geography.html#guidelines-for-geographic-terms-in-arctos>):

Be consistent. At the largest practical scale (usually ~country), do the same thing for all records. For island nations, ensure that the island data are consistent. Ensure all county-level records include qualifiers (County, Parish, etc.) or that none do.

eliminate entries under ISLAND GROUP when they are identical to (and contiguous with)

I think we're OK in principle, but I'd like to have explicit global guidelines (eg, also apply to things other than country<-->island_group, or guidelines which eliminate any other combination, or SOMETHING) meant to enforce the Prime Directive ("Scrupulous consistency is essential").

Fiji seems straightforward - the two things spelled "Fiji" are pretty much interchangeable (at least until the Canadians invade and take over a couple islands in the Fiji Islands group).

Australia-the-country controls the Australian Antarctic Territory, which is nowhere near Australia-the-continent - choosing which "duplicate term" to eliminate isn't completely arbitrary.

Is that all covered by

Terms which replicate both string and spatial data may be eliminated. For example, "Fiji" (country) and "Fiji Islands" (island_group which contains the string " Islands" only by convention) may be entered only as "Fiji" (country), thereby freeing "island_group" for smaller island groups within the island group which also serves as a country. Always follow the "Scrupulous consistency is essential" guidance in this operation; whatever is done must be done consistently at the largest possible scale.
?

**Comment by dustymc** [comment]
>broken “scrupulous consistency” edict

Welcome to the club! As long as it eventually gets fixed.... 

Mamanuca Islands, Lomaiviti Islands, and Lau Islands added to CTISLAND_GROUP.

>Oceania instead of Australia

I have no useful opinion. Here are current users:

```

select
  collection.guid_prefix,
  count(*) c
from
  collection,
  cataloged_item,
  specimen_event,
  collecting_event,
  locality,
  geog_auth_rec
where
  collection.collection_id=cataloged_item.collection_id and
  cataloged_item.collection_object_id=specimen_event.collection_object_id and
  specimen_event.collecting_event_id=collecting_event.collecting_event_id and
  collecting_event.locality_id=locality.locality_id and 
  locality.geog_auth_rec_id=geog_auth_rec.geog_auth_rec_id and
  continent_ocean='Australia'
group by 
  collection.guid_prefix
 order by
  collection.guid_prefix
;

GUID_PREFIX							      C
------------------------------------------------------------ ----------
CHAS:Bird							      7
CHAS:Egg							      1
CHAS:Ento							      2
CHAS:Inv							     90
CHAS:Teach							      2
CRCM:Bird							      2
CUMV:Amph							     62
CUMV:Bird							    494
CUMV:Fish							    118
CUMV:Mamm							     46
CUMV:Rept							   1200
DMNS:Bird							    767
DMNS:Egg							      4
DMNS:Inv							   1532
DMNS:Mamm							     57
HWML:Para							    431
MLZ:Bird							      3
MSB:Bird							     18
MSB:Host							     28
MSB:Mamm							     11
MSB:Para							      2
MVZ:Bird							   2003
MVZ:Egg 							     98
MVZ:Herp							   1247
MVZ:Hild							      4
MVZ:Mamm							   2300
UAM:Bird							     85
UAM:ES								      4
UAM:Mamm							      6
UAMb:Herb							    200
UCM:Bird							      9
UCM:Egg 							      1
UCM:Herp							     41
UCM:Mamm							      3
UMNH:Herp							   4423
UMNH:Mamm							      3
UTEP:Bird							     33
UTEP:Herb							    396
UWBM:Herp							      1
UWBM:Mamm							     77
WNMU:Mamm							     17
```

**Comment by ekrimmel** [comment]
CHAS has no preference for Oceania over Australia here; if consensus is to go with Oceania that's fine by us

**Comment by sharpphyl** [comment]
For sure, we would need every current user to agree before making the change.   It’s fine for marine species but it may not be effective for terrestrial species.


On Jan 8, 2018, at 11:55 AM, dustymc <notifications@github.com> wrote:

broken “scrupulous consistency” edict

Welcome to the club! As long as it eventually gets fixed....

Mamanuca Islands, Lomaiviti Islands, and Lau Islands added to CTISLAND_GROUP.

Oceania instead of Australia

I have no useful opinion. Here are current users:


select
  collection.guid_prefix,
  count(*) c
from
  collection,
  cataloged_item,
  specimen_event,
  collecting_event,
  locality,
  geog_auth_rec
where
  collection.collection_id=cataloged_item.collection_id and
  cataloged_item.collection_object_id=specimen_event.collection_object_id and
  specimen_event.collecting_event_id=collecting_event.collecting_event_id and
  collecting_event.locality_id=locality.locality_id and 
  locality.geog_auth_rec_id=geog_auth_rec.geog_auth_rec_id and
  continent_ocean='Australia'
group by 
  collection.guid_prefix
 order by
  collection.guid_prefix
;

GUID_PREFIX							      C
------------------------------------------------------------ ----------
CHAS:Bird							      7
CHAS:Egg							      1
CHAS:Ento							      2
CHAS:Inv							     90
CHAS:Teach							      2
CRCM:Bird							      2
CUMV:Amph							     62
CUMV:Bird							    494
CUMV:Fish							    118
CUMV:Mamm							     46
CUMV:Rept							   1200
DMNS:Bird							    767
DMNS:Egg							      4
DMNS:Inv							   1532
DMNS:Mamm							     57
HWML:Para							    431
MLZ:Bird							      3
MSB:Bird							     18
MSB:Host							     28
MSB:Mamm							     11
MSB:Para							      2
MVZ:Bird							   2003
MVZ:Egg 							     98
MVZ:Herp							   1247
MVZ:Hild							      4
MVZ:Mamm							   2300
UAM:Bird							     85
UAM:ES								      4
UAM:Mamm							      6
UAMb:Herb							    200
UCM:Bird							      9
UCM:Egg 							      1
UCM:Herp							     41
UCM:Mamm							      3
UMNH:Herp							   4423
UMNH:Mamm							      3
UTEP:Bird							     33
UTEP:Herb							    396
UWBM:Herp							      1
UWBM:Mamm							     77
WNMU:Mamm							     17

**Comment by Jegelewicz** [comment]
> Australia-the-country controls the Australian Antarctic Territory, which is nowhere near Australia-the-continent - choosing which "duplicate term" to eliminate isn't completely arbitrary.

In looking at Wikipedia's definition of Oceania, I don't see how that includes Australian Antarctic Territory, but I guess we could have "Antarctica, Australia, Australian Antarctic Territory"? How often does anyone search for "Oceania"? I don't think it would make a huge difference in people finding our things because I would guess people would search for Australia the country over Australia the continent. So I guess it would be fine to change Australia the continent to Oceania from UTEP's perspective.  This is probably going to impact other countries and island groups as well...

**Comment by dustymc** [comment]
I think this has drifted off topic - closing....
