### ISSUE TITLE
Non-compliant agent?

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#1318]
I created two aka entries for this agent, but I want to leave the one with ampersand and "co." as the preferred because that is how they are published. What else can I do to make this compliant?

![ss_towerlyon-agent](https://user-images.githubusercontent.com/17605945/32391597-7bad7382-c087-11e7-8421-cc09fa8d14c6.jpeg)

**Comment by dustymc** [comment]
The checker assumes "Co." is "Company." I can adjust if necessary, but I just added "Tower and Lyon Company" which should make it happy in the meantime. Even if "Co." is unequivocally not "company," that'll probably help someone get where they want to be so I'm tempted to leave the scripts alone. Thoughts??

The preferred name is fine/correct (eg, if they abbreviated it you probably should too, unless there's a reason not to anyway) - these "rules" (suggestions, really) just exist to help search.

**Comment by AJLinn** [comment]
Perfect, thanks Dusty! That works just fine for me. I should have figured on company as another alternative - just had "corporation" in my head having read about their "incorporation date". All is fine.
