### ISSUE TITLE
InvertEBase

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#1319]
Can someone help me understand how our data flows to InvertEBase?  

Our Marine Invertebrates were last updated in December 2015.  (http://www.invertebase.org/portal/collections/misc/collprofiles.php?collid=8).  Do we need to take some action to get fairly frequent updates?  All of the other collections in InvertEBase (including UAM-Inverts) have been updated in 2017.  

Thanks.

**Comment by dustymc** [comment]
@ccicero @dbloom ??

**Comment by ekrimmel** [comment]
Isn't this a problem for Symbiota? The way I understand they (at least for InvertEBase) are supposed to harvest from our stuff on the IPT

**Comment by sharpphyl** [comment]
I'm communicating directly with Rudiger and Petra at the Field Museum who developed Invert E Base and they're working on the issue.  Unless they indicate that some action must be taken by Arctos, we can close my query.

**Comment by ekrimmel** [comment]
@sharpphyl thank you for asking Rudiger and Petra about this--we will have the same problem very soon for CHAS data that needs to go to InvertEBase.

**Comment by sharpphyl** [comment]
Petra, working with Ed Gilbert, has successfully updated our data.  Erica, I'll forward a series of emails to you just FYI.  Everything looks great and Ed has a program in place to update data monthly.  i don't think you'll have any problems once you get your data in place.  We can close this issue as no action is required from Arctos.
