### ISSUE TITLE
loan map

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1325]
New app

- select collection(s) (and maybe add more stuff later if necessary)
- georeference ship_to address
- create map

for @jldunnum

**Comment by amgunderson** [comment]
This sounds interesting, where is it?

**Comment by jldunnum** [comment]
Doesn't exist yet, Dusty is going to work on it.


______________________________________________________________

Jonathan L. Dunnum Ph.D.
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by dustymc** [comment]
Yes interesting and I need a break from taxonomy SO.....

In TEST I added a coordinates field to addresses and ran them through a georeference service. Our address format is a giant mess so I believe they're mostly just georeferenced to some ZIP-equivalent. 

Then I merged those data with minimal loan info and made https://fusiontables.google.com/data?docid=19kJ9olWr9nquZfRIx53mdAsFSMmvdcgNJ8LmBabp#map:id=3

If there are no fatal flaws in that general approach I can pipe the data to berkeleymapper (or whatever), add whatever information ya'll want to see, and set up automated georeferencing on addresses to maintain the data.

Let me know how to proceed.

**Comment by campmlc** [comment]
Cool! Can we map by collection/Institution/year?

**Comment by dustymc** [comment]
>collection/Institution


<img width="274" alt="screen shot 2017-11-09 at 11 16 05 am" src="https://user-images.githubusercontent.com/5720791/32624873-7579ded0-c53f-11e7-853c-66a21bcc230f.png">

>year

Not in this. It's possible (so is anything else I can get to from shipments), but I'll need to know how you want this thing to work (is fusion tables enough? berkeleymapper? local map? KML? Lots of possibilities...) and what data ya'll are OK with making public, or if we need to find a restricted channel, etc.

First question: is this level of georeference useful? Not much sense in talking/building more complexity if the fundamental data aren't of sufficient quality.

**Comment by campmlc** [comment]
I'm happy with zip code level accuracy.

**Comment by dustymc** [comment]
Waiting for help from berkeleymapper. Current intent is to maintain georeferences of shipping addresses, make mapping an option from loan results.

**Comment by dustymc** [comment]
Added link to berkeleymapper from loan search results for next release.

I'll pre-georef used shipping addresses and set up scripts to auto-georeference physical addresses as they're added/modified.
