### ISSUE TITLE
Add "original media number" to media labels

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#1326]
I'm starting to add links to existing media on the web (e.g. http://vilda.alaska.edu/cdm/ref/collection/cdmg11/id/35519) that show objects in our collection in use (http://arctos.database.museum/guid/UAM:EH:0656-0001) or are being talked about in oral history recordings. I would like to cite, as a media label, the holding institution's number for that film clip/audio file/photograph catalog number, etc.

Adding "original media number" to the list of media labels would allow that number to be clearly indicated rather than being embedded in the comments or description.

**Comment by dustymc** [comment]
http://arctos.database.museum/info/ctDocumentation.cfm?table=CTMEDIA_LABEL

"image number" is the same type of data and I'm hesitant to have two ways of doing the same thing (guarantees that some users won't find what they're looking for).

@ccicero is there some more generic vocabulary that works for you?

"media number"?

"media identifier"?

"original" seems overly-specific for about the same reasons as "image."

I don't really care what we call it, I just want to help users get where they want to be.

**Comment by AJLinn** [comment]
Agreed - I think a general "media identifier" would be ideal. But an oral recording shouldn't have a media label of image. Many holding institutions have some sort of code before their number (e.g., AAF-828 is the identifier for the Alaska Film Archive clip I just connected to our artifact). I think DublinCore uses "identifier" as their standard for any ID system.

**Comment by dustymc** [comment]
priority bump - @ccicero ??

**Comment by AJLinn** [comment]
Can we revisit this? I like Dusty's suggestion of "media identifier" to replace the other media label of "image number".

**Comment by dustymc** [comment]
@ccicero ??? @mkoo ??

**Comment by dustymc** [comment]
add to "manage" - link to media linked to all specimens in result
(and publications too)

**Comment by dustymc** [comment]
@ccicero  says OK - "media identifier"

**Comment by dustymc** [comment]
1. Made a new label "media identifier"
2. 
```
UAM@ARCTOS>  update media_labels set MEDIA_LABEL='media identifier' where MEDIA_LABEL='image number';

17390 rows updated.
```
3. delete from CTMEDIA_LABEL where MEDIA_LABEL='image number'
