### ISSUE TITLE
Flatten Part Locations

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1329]
Is not working? 
[remaining uncat tissue barcodes.txt](https://github.com/ArctosDB/arctos/files/1476641/remaining.uncat.tissue.barcodes.txt)

When I search on this barcode list in Find Container, I get the part positions. But Flatten Part Locations does not return any cataloged items. Yet the barcodes are associated with cataloged items, as you can see if you double click the part. What is missing?

**Comment by dustymc** [comment]
It flattens what's visible. If you want those parts, search by "IN barcode" or expand the ones you want to see in the flatten app.

**Comment by campmlc** [comment]
Is there documentation for this? I've been using this tool for several years and never knew about the IN barcode tool - I've never used it, and I still don't understand the difference.  I've never had this happen before when searching on a barcode list. I still don't know how this is different from what I've done many times previously. Any chance we can get links to the documentation from the search tools on this page?

**Comment by dustymc** [comment]
The flatten app can only deal with visible parts - there will usually be lots of things which ultimately hold lots of parts that you don't care about in any search, I have no way of guessing at which of them you might want to see.

There are lots of pathways in - SpecimenResults, Manage/PartLocations for example.

"barcode" finds containers bearing the barcode you enter. "in barcode" finds their children - containers IN the barcode(s) you supply. In some cases those children are (also) parts.

I can add links wherever you want them - I just need a target.

**Comment by campmlc** [comment]
So to revisit this regarding #1764, we need to be able to expand to show all parts that are the result of a search, and then be able to flatten them. In Teresa's example, she needs to be able to search on the term "sangre" in a label and download a list of all cataloged items that have a part with that term in the label.

**Comment by Jegelewicz** [comment]
closing - not sure this is something that can be done without magic.
