### ISSUE TITLE
add parts to Teach collection

### ISSUE THREAD

**Issue by ekrimmel** [ArctosDB/arctos#1330]
May we please have the following added to the parts for Teach collections?

**foot** - terminal portion of an animal limb which typically bears weight and facilitates movement
**hair** - protein filament that grows from skin follicles
**mandible** - lower jawbone of a skull
**pellet (dry)** - *see existing definition in Bird*
**seed** - embryonic plant enclosed in a protective outer covering
**skin, shed (dry)** - *see existing definition in Herp*

Thanks!

**Comment by dustymc** [comment]
done
