### ISSUE TITLE
Add new other ID type

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1332]
Can we add other ID type "trap number"?

**Comment by dustymc** [comment]
I can't evaluate this without a definition.

**Comment by Jegelewicz** [comment]
trap number: the identifier assigned to an apparatus used to capture a specimen.

**Comment by dustymc** [comment]
Is the item of interest the trap itself or is that acting as a proxy for collecting event? Either way, that should be in the definition. If the latter, why not use collecting event nickname (properly-structured actually-unique time-place-ID) or "field number" ("people were involved" attempt at time-place-ID)??

**Comment by Jegelewicz** [comment]
In this particular case, the trap number helps me discriminate between three different micro localities at one collecting event (three traps were placed around a single plant just inches apart and should not be in separate localities). Each trap collected multiple specimens, and for each of these there may also be a separate field number.

**Comment by dustymc** [comment]
Thanks.

That still sort of sounds like "field number" to me, it just involves the usual problem of localities/events having hugely variable precision. 

Without "other side of the plant" spatial precision you can't use locality nickname and without "the time in which THIS specimen was caught" temporal precision you can't use collecting event nickname, and I think that's roughly what "field number" exists to capture. I also suspect people who use "field number" might give three traps around a plant the same field number. Is "sub-field-number" a thing for anyone??

Is "Trapline ID" a synonym of "field number"?

@amgunderson @jldunnum have you dealt with "trap number"? @ccicero do you do similar for nets (#831)?

And see http://arctos.database.museum/info/ctDocumentation.cfm?table=CTCOLL_OTHER_ID_TYPE - we're using the 'fish definition' of Field Number, while a "field-assigned specimen identifier" likely fits under the Arctos concepts of "collector number" or "original identifier."

**Comment by campmlc** [comment]
We have trap number associated with several thousand Sevilleta mammals from
mark recapture grids where the trap number indicated a position in the grid
used through multiple years. All data sheets reference this as "trap
number". As there was no trap number in Arctos when these records were
migrated, this info is in locality but not in a consistent format and so
not searchable. I see no reason not to add trap number if that ties to
data. It is certainly used by mammalogists.

**Comment by dustymc** [comment]
Thanks @campmlc - I knew I'd seen something like this SOMEWHERE....

>this info is in locality

I think that's what's making me twitchy. It IS locality info, it's just not the same precision, or a different kind of precision, or something. A user shouldn't have to guess that you've stashed what is essentially place-data in some not-place cubbyhole, "we" will not type "trap number sixteen" 700 times without a little variation, etc., all leading to more work when something needs corrected and users not finding all of what they're looking for and all the other fun stuff that comes with denormalization.

>no reason not to add trap number

Despite the above, I don't see a better way. Is there a more generic term that might work better with mist nets and individual fish hooks on a line and such? Maybe those are just "traps" and we can clarify in the definition??

How's this?

>"Sub-field number" assigned to traps or other capture apparatus when a locality or event encompasses multiple such devices. Several individuals or cataloged items may share both this identifier and any of field number, collecting event nickname, or locality nickname. The use of more precise locality and/or event data should be heavily preferred when possible.

**Comment by campmlc** [comment]
I don't see that we gain anything by using a generic term that no one uses
and that people have to guess at ("sub-field number")  vs well-understood
terms specific to a discipline. Trap number and net number and field number
are in common use in field biology. Perhaps different  projects and
disciplines use them slightly differently, e.g. a grid vs a trapline vs a
mist net vs a bat net vs a seine, but they are clear terms that tie to
actual datasheets, field notes etc.

**Comment by campmlc** [comment]
I think the key here is that the term entered in Arctos is the same term
that was used in the datasheets and field notes for that project. We should
have identifiers in Arctos that correspond to the commonly used terms that
are likely to occur in datasheets, field notes, etc for each discipline. If
these also reference locality specific data, so much the better, as they
can be used as a double check against the locality fields.

**Comment by dustymc** [comment]
Calling the same thing something different (or using the same term for different things) limits the questions users may readily ask of your data. There may be a compelling reason to have a "bat net number" and a "sparrow net number" and a "butterfly net number" and ..... but that situation should be carefully approached with the usability implications in mind. And "well-understood" doesn't scale - "field number" means at least two things across disciplines, for example.

I can see an argument for various "verbatim thing scribbled on some paperwork" data, but I see absolutely no reason to accommodate that via denormalization.

**Comment by Jegelewicz** [comment]
What @campmlc  said. These are important identifiers, especially to those who completed the research. Having them in a nice searchable place with a recognizable identifier name is needed. I'm not sure that we can easily place these all under some generic term, but I'll sleep on it and see if something comes to me there.

**Comment by jtgiermakowski** [comment]
we have a suite of specimens, from lizards to turtles, that have associated data on 'trap' or 'trap number' 'hoop net number'. perhaps we can expand the definition of 'trap' to include buckets, snake boxes and hoop nets, but accommodating that data would increase the amount of data about the specimen. As is, I think it's relegated to some "notes" or comments...

**Comment by dustymc** [comment]
Done with "trap number" and my flaky definition above.

**Comment by Jegelewicz** [comment]
I don't see "trap number" in the Other ID code table - what am I missing?

**Comment by campmlc** [comment]
It is there.

"Sub-field number" assigned to traps or other capture apparatus when a
locality or event encompasses multiple such devices. Several individuals or
cataloged items may share both this identifier and any of field number,
collecting event nickname, or locality nickname. The use of more precise
locality and/or event data should be heavily preferred when possible.

**Comment by Jegelewicz** [comment]
Oh yes, I see it now at the very bottom of the list. Can we number these so that the generic ones appear at the top? I noticed that "Trapline ID" is just stuffed in with all of the institution types - not exactly easy to find that one either....

**Comment by campmlc** [comment]
Tried to fix this by making "Trapline ID" lower case so it will sort with trap number, but it has children. Dusty, can you fix so we can close the issue?

**Comment by Jegelewicz** [comment]
> Tried to fix this by making "Trapline ID" lower case so it will sort with trap number, but it has children. @dustymc can you fix so we can close the issue?

**Comment by dustymc** [comment]
@Jegelewicz "trapline ID" (yes??) or "trapline id"??

>Perhaps we need a code table for trap types? This would definitely help to normalize that data....

That's collecting method, more or less. There are an infinite number of "trap types" and a lot of levels of precision that one might care about. "Pitfall" vs. '5-gallon plastic bucket pitfall arranged in some-long-description...." or "net" vs some description of length/height/mesh/material/trawl speed/....

I'm not sure how to handle that other than free-text. 

If there are questions you'd ask of the data if you could, this probably needs a new Issue.

**Comment by Jegelewicz** [comment]
trapline ID

**Comment by dustymc** [comment]
done
