### ISSUE TITLE
Loan form create shipment missing expression

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1333]
![screenshot 2017-11-20 17 53 02](https://user-images.githubusercontent.com/14808196/33049150-f0ead314-ce1b-11e7-82c0-b3e07d3fe18a.png)
The loan form returns a missing expression error when I try to create a shipment. I've tried multiple addresses, international yes/no, editing the addresses, checking for valid etc. 
![screenshot 2017-11-20 17 52 49](https://user-images.githubusercontent.com/14808196/33049140-ea465416-ce1b-11e7-8126-e56cf43951e0.png)

**Comment by dustymc** [comment]
```
INSERT INTO shipment ( TRANSACTION_ID ,PACKED_BY_AGENT_ID ,SHIPPED_CARRIER_METHOD ,CARRIERS_TRACKING_NUMBER ,SHIPPED_DATE ,PACKAGE_WEIGHT ,HAZMAT_FG ,INSURED_FOR_INSURED_VALUE ,SHIPMENT_REMARKS ,CONTENTS ,FOREIGN_SHIPMENT_FG ,SHIPPED_TO_ADDR_ID ,SHIPPED_FROM_ADDR_ID ,shipment_type ) VALUES ( 21115462 , ,'Federal Express' ,'' ,'' ,'' ,0 ,NULL ,'' ,'' ,1 , , ,'loan' ) 
```
http://handbook.arctosdb.org/documentation/understanding-errors.html#me

If you can provide enough detail regarding how packed_by and the shipping addresses got there without their identifiers for me to re-create the problem I might be able to make the form a bit better.

**Comment by campmlc** [comment]
I just selected from the dropdown and agent list like I always do several
times a week. Not sure why suddenly it didn't work?

**Comment by campmlc** [comment]
I figured this one out, in case anyone else has similar issues. My browser was autofilling my name in the packed by agent field, and this autofill wasn't being tabbed and recognized by Arctos. I had to go back in and delete the last letter from my name and hit tab in order for Arctos to approve the agent name. The missing name was the missing expression. Dusty, please correct if I've misinterpreted anything here.

**Comment by dustymc** [comment]
yes, that sounds typical

http://handbook.arctosdb.org/documentation/understanding-errors.html#missing-expression
