### ISSUE TITLE
Add parts to Teach Collections

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1335]
bill width - width of the bill measured at the widest point, typically the gape

Note - in Bird collections the definition is "length of the bill measured at the widest point, typically the gape". Change length to width

culmen - measurement taken using calipers with one jaw at the tip of the upper mandible and the other at base of the skull or the first feathers depending on the standard chosen

wing chord - measured from the bend of the wing to the tip of the longest primary feathers. Often the wings and feathers may be flattened so that the measure is maximized but in some cases the chord length with natural curvature is preferred

Also add definition of culmen and wing chord in Bird collections.

**Comment by dustymc** [comment]
>parts

Attributes.

>bill width

done

>culmen

Did you mean, or how is this different than, "culmen length"?

If this is new (and for all new Attributes) I also need a datatype for https://arctos.database.museum/info/ctDocumentation.cfm?table=CTATTRIBUTE_CODE_TABLES. Three things are allowed:

1. free text (=no entry in CTATTRIBUTE_CODE_TABLES)
2. number+units (=I need a code table for CTATTRIBUTE_CODE_TABLES.UNITS_CODE_TABLE)
3. categorical (=I need a code table for CTATTRIBUTE_CODE_TABLES.VALUE_CODE_TABLE)

>wing chord

done

**Comment by ekrimmel** [comment]
Can we please add "fin (alcohol)" as a part option for Teach too? Same definition as in Fish.

**Comment by ekrimmel** [comment]
And also...

**claw** - an appendage, typically made of keratin, found at the end of a toe or finger in most amniotes
**horn** - a permanent projection on the head of an animals consisting of a covering of keratin and other proteins surrounding a core of live bone
**skin, tanned** (same definition as for Mamm)
**skeleton, mounted** (same definition as for Mamm)

Please and thank you!

**Comment by ekrimmel** [comment]
@dustymc And I'm also nagging you about this one, again because it's an easy issue and I have stuff sitting in my bulkloader waiting on it. I probably should not have tacked my wants onto Teresa's issue in the first place...

**Comment by ekrimmel** [comment]
This issue is taken care of except for:

> culmen

> Did you mean, or how is this different than, "culmen length"?

> If this is new (and for all new Attributes) I also need a datatype for https://arctos.database.museum/info/ctDocumentation.cfm?table=CTATTRIBUTE_CODE_TABLES. Three things are allowed:

> - free text (=no entry in CTATTRIBUTE_CODE_TABLES)
> - number+units (=I need a code table for CTATTRIBUTE_CODE_TABLES.UNITS_CODE_TABLE)
> - categorical (=I need a code table for CTATTRIBUTE_CODE_TABLES.VALUE_CODE_TABLE)

@Jegelewicz any thoughts on the above?

**Comment by Jegelewicz** [comment]
culmen length + culmen, I think this is all done.
