### ISSUE TITLE
Georeferencing - sources and protocols

### ISSUE THREAD

**Issue by jtgiermakowski** [ArctosDB/arctos#1337]
It seems that the code table for GEOREFERENCE_SOURCE is MIA. When I click the link from http://handbook.arctosdb.org/documentation/coordinates#reference-sources I get: 
![screenshot 2017-11-29 16 53 27](https://user-images.githubusercontent.com/2381228/33405494-df124d0a-d525-11e7-9020-696ec747140d.png)

Is it an open text field?

On the flip side, GEOREFERENCE_PROTOCOL seems to be the same as GEOREFMETHOD, at least in the list of code tables. Should one be deprecated?

**Comment by dustymc** [comment]
Yes, GEOREFERENCE_SOURCE is open-text and I cleaned up the docs.

ctgeorefmethod is deprecated - I'll clean that up too.
