### ISSUE TITLE
Newsfeed banner and Arctos settings changed after outage?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1340]
We appear to have lost the newsfeed banner since the outage this afternoon.
Also, when Arctos came back up, my profile browse settings had reverted to Block rather than Allow, so I could no see the Try Something Random banner.

**Comment by dustymc** [comment]
The banner is my fault - it needs expiration and the reset cleared a cache. It's fixed, I'll make the form more obvious.

I can't imagine what could have happened with your suggest settings - it's on now, but you probably just turned it on....

**Comment by campmlc** [comment]
Is the default setting for all users to allow the newsfeed and TSR? Most people will not know how to turn this on/off in Profile. I recommend it be on by default.

**Comment by dustymc** [comment]
Newsfeed is not controllable.

TSR defaults on and has a hide this link and instructions for turning it back on.
