### ISSUE TITLE
List taxa for "scientific name does  not exist" in taxonomy bulkloader

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#1344]
I'm able to figure out most of the errors Arctos identifies during the "Flag to run all data checks" stage.  The entry "scientific name does not exist" does not list the relevant taxa.  Is there a way to know which taxa will not be uploaded because of this problem so I can make the corrections and reload the .csv?

![screen shot 2017-12-04 at 9 08 52 am](https://user-images.githubusercontent.com/15368365/33562825-7a7dab4e-d8d3-11e7-8a24-ba6a234ad71b.png)

**Comment by dustymc** [comment]
You can download the CSV with errors from the loader splash page - /tools/BulkloadClassification.cfm

**Comment by sharpphyl** [comment]
Sorry, Dusty, but I don't know what the loader splash page is.  I'm at /tools/Bulkloadclassification.cfm. Can you give me a bit more direction?  

![screen shot 2017-12-04 at 9 31 03 am](https://user-images.githubusercontent.com/15368365/33563706-e387d040-d8d5-11e7-943b-3f6b9b2357d9.png)

**Comment by sharpphyl** [comment]
I found it!  I found it!  Thanks for the help.
