### ISSUE TITLE
creating container series bulkloader

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1346]
I need to either load or delete a series of barcodes from the create container series bulkloader, but I can no longer access the records. I got as far as proceed to validation, the browser hung up on the (excessive - 125,000) number of records, and I was called away from the computer and got logged out. When I later tried to break the file up into smaller chunks and reload, I got an error message saying there are already barcodes in the bulkloader. But I can't access or see these to delete them and start over.

**Comment by dustymc** [comment]
That form autodeletes when it first loads. There's nothing in the table.

**Comment by campmlc** [comment]
I got no success notification - just the spinning browser. But it looks like they all loaded from the attempt with 125,000 labels.

**Comment by dustymc** [comment]
Firefox (and probably others) tends to somehow forget something on long operations (eg, mabye your network is slow-ish and upload takes a while) and never recover from the "working" state.

If it becomes problematic I can load barcodes for you, or you can split them into batches.
