### ISSUE TITLE
Problem with adding multiple permits

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1353]
I want to add more than one permit to an accession, but when I select "add a permit" it also highlights "attach/upload media" and I get the media upload screen instead of the search for a permit. See attached screenshot.
![screenshot 2017-12-08 14 46 37](https://user-images.githubusercontent.com/5725767/33786558-d516ba5e-dc26-11e7-9a7f-084105f4249d.png)

**Comment by dustymc** [comment]
Everything involving permits will be new ~early next week.

**Comment by Jegelewicz** [comment]
Check!
