### ISSUE TITLE
Add to CTTAXONOMIC_AUTHORITY code table

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#1354]
Add EOL - Encyclopedia of Life
Add GBIF - Global Biodiversity Information Facility

These are resources for terrestrial molluscan taxa

**Comment by dustymc** [comment]
That code table does nothing. We can talk about cleaning it up and plugging it back in if you wish.

FWIW, I don't think GBIF adds confidence (if that's the point of a controlled source). They're just an aggregator, and they're fairly famous for aggregating bad taxonomy.

**Comment by sharpphyl** [comment]
OK.  I thought we had to use one of the sources in the table.  GBIF does have a lot of garbage (e.g. museum) taxa, but it's the only place I'm finding some terrestrial mollusks. Adding GBIF as the SOURCE at least tells others where it came from.  OK with me to close this issue.

**Comment by dustymc** [comment]
OK, I'll close.
Yes GBIF taxonomy is certainly USEFUL, just not terribly AUTHORITATIVE. If at some point we do plug in a source authority we should document that sort of thing - what are we trying to do in general, what the expectation of specific sources is, etc.
