### ISSUE TITLE
GGBN DWC data

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1355]
There's a first attempt at GGBN DWC data, one file for Tissues and one for Permits, both keyed to Occurrences, in the DDL/flat folder

https://github.com/ArctosDB/DDL/blob/master/flat/ggbn_flat_tissue.sql 
https://github.com/ArctosDB/DDL/blob/master/flat/ggbn_flat_permit.sql 

What's missing, what should be added, are there any privacy concerns, etc.?

The GGBN Standard is https://terms.tdwg.org/wiki/GGBN_Data_Standard.

Example data:
```
UAM@ARCTOSTE> select * from digir_query.ggbn_flat_tissue where rownum=1;

OCCURRENCEID
------------------------------------------------------------------------------------------------------------------------
MATERIALSAMPLETYPE
------------------
PREPARATIONTYPE
------------------------------------------------------------------------------------------------------------------------
PREPARATIO PRE
---------- ---
PREPARATIONSTAFF
------------------------------------------------------------------------------------------------------------------------
http://arctos.database.museum/guid/MVZ:Mamm:158848?seid=30778
tissue
tissue extract (frozen)
1999-02-04
unknown
```
```

UAM@ARCTOSTE> select * from digir_query.ggbn_flat_permit where rownum=1;

OCCURRENCEID
------------------------------------------------------------------------------------------------------------------------
PERMITTYPE
------------------------------------------------------------------------------------------------------------------------
PERMITSTATUS						     PER
------------------------------------------------------------ ---
PERMITTEXT
------------------------------------------------------------------------------------------------------------------------
http://arctos.database.museum/guid/UAM:Mamm:99528?seid=662612
collect
Permit available
Permit Number 06-051 issued to Link E. Olson by Alaska Department of Fish and Game


```

**Comment by campmlc** [comment]
Tackling tissues first:

- Which agent do we use for preparation staff?  I'm thinking this should be a decision tree and propose the following order: 
 1) preparator is there is one, if not then
 2) attribute agent if this exists, because whoever determines attributes such as sex or weight is presumably dealing with the tissues (this should really be first choice for any parasites as parts, but that may be too much to ask)
 3) collector? 
4) unknown if 1-3 are unknown

Thoughts?

**Comment by campmlc** [comment]
Comments on permits:

Does our new model correspond to the GGBN vocabulary for permit type? Here are there terms:
 Collecting Permit, Import Permit, Export Permit, Intellectual Property Rights, Copyright, Patent, Data use, Phytosanitary, Salvage, Exemption Permit, Material Transfer Agreement, Internationally Recognized Certificate of Compliance, contract, Memorandum of Understanding, Memorandum of Cooperation, Veterinary Certificate, Human Pathogens, Genetically Modified Organism, Other

 Permit status is a mandatory field at GGBN because of Nagoya, and the values are: Permit available, Permit not required, Permit not available, Unknown. Because this is a required field, perhaps it is redundant to have "permit not required" as a permit type in Arctos? 

This will be easier to comment on once the updates have hit production.

**Comment by dustymc** [comment]
>Which agent do we use for preparation staff?

I just grabbed the ONLY agent around parts for now. Part attribute determiner is probably correct or close enough to it when we start recording those data. Eg collector seems confusing - they probably had nothing to do with a DNA extraction - and on that note maybe we should default that to NULL until there's an agent much closer to the preparation?

>correspond to the GGBN vocabulary

The model and vocabulary are separate issues - we can easily change our vocabulary, or translate on the fly, or whatever.

>Permit status

With a "permit not required" type, there are two possibilities:

- we have a permit (or many of them)
- we don't have a permit

where "we have a permit" might include "...that we issued to ourselves explaining why we don't need a real permit." Their vocabulary would be ambiguous in our model (we'd have to guess at what nothing at the end of the specimen-->transaction-->permit pathway means).

>once the updates have hit production.

Count to 500 slowly and check back.....

**Comment by dustymc** [comment]
See also http://wiki.ggbn.org/ggbn/Mandatory_and_recommended_fields_for_sharing_data_with_GGBN#Sample_data_2 for a summary of "fields."

**Comment by dustymc** [comment]
PERMITTEXT: map to "contact collection for information"

**Comment by dustymc** [comment]
permitStatusQualifier: map to NULL

**Comment by dustymc** [comment]
if collected before 2014 and no permits then permit type==>"pre-Nagoya; no permit required."

**Comment by dustymc** [comment]
when permit type is 'permit not required' --> permitStatusQualifier="no requirement for permit at date of access"

**Comment by dustymc** [comment]
Updated structure at 

https://github.com/ArctosDB/DDL/blob/master/flat/ggbn_flat_tissue.sql
https://github.com/ArctosDB/DDL/blob/master/flat/ggbn_flat_permit.sql


```
-- tissue table

UAM@ARCTOSTE>  select * from digir_query.ggbn_flat_tissue where rownum=1;

    UNITID
----------
OCCURRENCEID
------------------------------------------------------------------------------------------------------------------------
MATERIALSAMPLETYPE
------------------
PREPARATIONTYPE
------------------------------------------------------------------------------------------------------------------------
PREPARATIO PRE
---------- ---
PREPARATIONSTAFF
------------------------------------------------------------------------------------------------------------------------
  12113591
http://arctos.database.museum/guid/MVZ:Mamm:158848?seid=30778
tissue
tissue extract (frozen)
1999-02-04
unknown

-- tissue with no permit

select * from temp_ggbn_permit where OCCURRENCEID='http://arctos.database.museum/guid/MVZ:Mamm:158848?seid=30778';
    UNITID
----------
OCCURRENCEID
------------------------------------------------------------------------------------------------------------------------
PERMITTYPE
------------------------------------------------------------------------------------------------------------------------
PERMITSTATUS
------------------------------------------------------------------------------------------
PERMITSTATUSQUALIFIER
------------------------------------------------------------------------------------------------------------------------
PERMITTEXT
------------------------------------------------------------------------------------------------------
  12113591
http://arctos.database.museum/guid/MVZ:Mamm:158848?seid=30778

pre-Nagoya; no permit required

contact collection for information


-- multiple permits
select * from temp_ggbn_permit where OCCURRENCEID ='http://arctos.database.museum/guid/MVZ:Herp:264003?seid=2606988';


    UNITID
----------
OCCURRENCEID
------------------------------------------------------------------------------------------------------------------------
PERMITTYPE
------------------------------------------------------------------------------------------------------------------------
PERMITSTATUS
------------------------------------------------------------------------------------------
PERMITSTATUSQUALIFIER
------------------------------------------------------------------------------------------------------------------------
PERMITTEXT
------------------------------------------------------------------------------------------------------
  24367592
http://arctos.database.museum/guid/MVZ:Herp:264003?seid=2606988
research; collect
Permit available

contact collection for information

  24367592
http://arctos.database.museum/guid/MVZ:Herp:264003?seid=2606988
permit type not recorded
Permit available

contact collection for information


```

**Comment by dustymc** [comment]
Per instructions in "New permit types for research and transfer" email thread, dropped the nagoya-thing.

```
-- tissue with no permit

select * from temp_ggbn_permit where OCCURRENCEID='http://arctos.database.museum/guid/MVZ:Mamm:158848?seid=30778';
    UNITID
----------
OCCURRENCEID
------------------------------------------------------------------------------------------------------------------------
PERMITTYPE
------------------------------------------------------------------------------------------------------------------------
PERMITSTATUS
------------------------------------------------------------
PERMITSTATUSQUALIFIER
------------------------------------------------------------------------------------------------------------------------
PERMITTEXT
------------------------------------------------------------------------------------------------------
  12113591
http://arctos.database.museum/guid/MVZ:Mamm:158848?seid=30778

Permit not available

contact collection for information




-- multiple permits
select * from temp_ggbn_permit where OCCURRENCEID ='http://arctos.database.museum/guid/MVZ:Herp:264003?seid=2606988';

    UNITID
----------
OCCURRENCEID
------------------------------------------------------------------------------------------------------------------------
PERMITTYPE
------------------------------------------------------------------------------------------------------------------------
PERMITSTATUS
------------------------------------------------------------
PERMITSTATUSQUALIFIER
------------------------------------------------------------------------------------------------------------------------
PERMITTEXT
------------------------------------------------------------------------------------------------------
  24367592
http://arctos.database.museum/guid/MVZ:Herp:264003?seid=2606988
research; collect
Permit available

contact collection for information

  24367592
http://arctos.database.museum/guid/MVZ:Herp:264003?seid=2606988
permit type not recorded
Permit available

contact collection for information


2 rows selected.

```

**Comment by dustymc** [comment]
These views now exist in production:

https://github.com/ArctosDB/DDL/blob/master/flat/ggbn_flat_tissue.sql

```
select count(*) from digir_query.ggbn_flat_tissue;

  COUNT(*)
----------
   6188329
```

https://github.com/ArctosDB/DDL/blob/master/flat/ggbn_flat_permit.sql

```
select count(*) from temp_ggbn_permit;

  COUNT(*)
----------
   1188175


```

https://github.com/ArctosDB/DDL/blob/master/flat/ggbn_flat_amplification.sql

```
select count(*) from digir_query.ggbn_flat_amplification;
 COUNT(*)
----------
    454071

```

@ccicero @campmlc I think we're ready to share with GGBN, or at least involve them in this mapping/conversation. How do we do that?

**Comment by campmlc** [comment]
No info on this morning's webcast on how to share with them? I guess we
talk with Kate about the next steps.

**Comment by dustymc** [comment]
Lots of info, but I don't manage or have access to "our" IPT server.

**Comment by campmlc** [comment]
Carla, do we ask David Bloom about this?
This relates to a bigger question of managing the Arctos IPT.

**Comment by campmlc** [comment]
@dbloom 
David, what do we need to do to move forward with publishing Arctos data to GGBN?

**Comment by campmlc** [comment]
Required to have data published in pipeline by July 15, 2018.  Need trial run at least 5 weeks advance to work out any problems.
