### ISSUE TITLE
Project Taxonomy- auto-add picklist of species based on related specimens

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#1358]
Wishlist feature that came up in  4th Webinar: allow the user to see list of species based on the associated specimens and pick the ones for the Project Taxonomy (editProject page)

**Comment by dustymc** [comment]
What is the purpose? I added project taxonomy for "checklist of {whatever} from {wherever}" sorts of uses; seems redundant and confusing to add taxonomy when there are taxonomy-bearing data already attached?
