### ISSUE TITLE
pop up notice on create taxon to alert to create a classification

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#1360]
Currently, one can easily create new taxa (genus + species), but not add a classification. It would be helpful to have something pop up and say, or force, the user to go and make a classification. Or, have to clearly click something to say, naw, I'll do it later. Possible?

**Comment by dustymc** [comment]
Clarified documentation, and there's a FLAT taxonomy gaps report.

**Comment by sharpphyl** [comment]
I learn something new every day.  Am I missing a tutorial/documentation on all the low quality reports?

**Comment by Jegelewicz** [comment]
There isn't any documentation that I am aware of for https://arctos.database.museum/Reports/flat_taxonomy_gap.cfm

However, it is part of data migration - https://github.com/ArctosDB/data-migration/blob/master/.github/ISSUE_TEMPLATE/8--taxonomy--classifications-.md
