### ISSUE TITLE
new columns in geog_auth_rec

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1364]
Should we do this, or come up with guidelines which exclude these things from geography, or ????

for all the junk that's in feature now

- ~~watershed~~ EDIT: not geography after all? https://github.com/ArctosDB/arctos/issues/1273#issuecomment-351863684
- protected area
- sub-island-group
- physiographic area

**Comment by mkoo** [comment]
First need a definition of geography-- what goes in this table versus the locality table

**Comment by sharpphyl** [comment]
For our marine specimens so far, I would not recommend sub-island-group IF we remove duplicates where the COUNTRY is the same as the ISLAND_GROUP.  I know we need to proceed case-by-case but that step should enable us to have sufficient precision with Higher Geography.

**Comment by dustymc** [comment]
#3272 has radically changed my view of this - closing for lack of interest.
