### ISSUE TITLE
geography nerds

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1365]
There is a group of people willing to deal with geography issues. Find a way to facilitate that.  Github groups/teams?

**Comment by mkoo** [comment]
I've started the process by creating a github team called Geo-group
https://github.com/orgs/ArctosDB/teams/geo-group

To start with everyone on our call has been added-- Andrew Doll was invited
as he was not originally part of the Arctos users, so please accept @acdoll
!

For now we will also continue to use the Geography Project to organize
tasks and issues.

Let me know if you want to be added to this Geography-focused team!
