### ISSUE TITLE
define geography

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1366]
Split from #1364 (and others).

What is geography? We need a functional/workable definition.

WHY are we using geography? So far geography is "things Curators said was Geography," which doesn't seem very stable. Geography isn't very useful for finding specimens - we have many ways (some precision-based, others administrative) of describing many/most places; a seach for any of them will find SOME specimens but cannot find all. What are we trying to accomplish? 

I think we also need to clarify what geography is functionally. That's also the answer to "what should WKT look like?' "A geography record" in Arctos is the area defined by the intersection of all data-bearing columns in table geog_auth_rec. WKT is (optionally) attached to geography records. Some components of geography are code-table controlled. Those components should be viewed as vocabulary, not places. If there are 20 things named "Whatever National Park" there should be one CTFEATURE entry (with an expansive definition) used in all of them.

* "Country, State, County" may be a geography entry and may be represented by WKT
*  "Country, State, Quad" may be another geography entry and also may be represented by WKT
*  "Country, State, Park" may be yet another
* **"Country, State, County, Quad, Park"** will be the area of intersection of all "components." This will have a smaller WKT footprint than any geography record with which is shares terms, and has no relationship with nor makes any use of any of the above three entries.

#1364: not clear how we can fix that without a definition.

#1102: geography may NOT include vaguely-defined things like straits and bays. (We once had those in Feature, then we limited Feature to "things with clear edges," but has now drifted back towards vaguely-defined areas.) WKT can make anything no longer "vaguely defined" but most USERS (eg, data entry personnel) don't really know where the ocean-side of a bay stops so it sort of fades away and nobody can find most of the specimens in the transition area.

Also #1102: lakes, or "things that share a string with the column name" or something. "Salton Sea" was once listed as a Sea - it's not a sea, and I don't think we want to allow that sort of thing (there are a LOT of similar-sized water bodies or whatever it might be called.)

#1278 - I don't think we're trying to capture every possible area of *ological interest with geography. 

"Things on wikipedia" isn't a great definition, but it does cover most of what most folks seem to want to call geography. "If it's not on Wikipedia, it's not geography" gets my very tentative support. 

#1309 - it's on Wikipedia, it has clear boundaries, it's a "protected area," it's defined/managed by the Feds, but it's 533 acres. Is it geography?

There are several Parks and similar (in Feature) managed by States. Do we keep them? Do we allow "protected areas" managed by counties/municipalities/school districts - is there an administrative minimum?

**Comment by ekrimmel** [comment]
I think that functionally, geography helps us collections (1) with data quality by forcing us to fit to the standard (or add) vs. just create anew for any unique value, as we can (rightly) do with localities; and (2) by ideally being a bounding box to map specimens prior to their being georeferenced.

To that extent I think we need to keep in mind the [Darwin Core fields](http://rs.tdwg.org/dwc/terms/index.htm#locationindex) that our data will need to get parsed into for publishing. Sub Island Group, for instance, would not fit in well to existing DwC options. Certainly not to say DwC is perfect or even that we should act based on it; at the least our higher geography can always go directly into dwc:higherGeography even if it doesn't get parsed out below that.

I like Dusty's suggestion of "If it's not on Wikipedia, it's not geography" as a starting point. We could also use alternative authorities, e.g. [GADM](http://www.gadm.org/), or some hierarchy of a handful of authorities. The spatial data in GADM is appealing to me.

**Comment by dustymc** [comment]
Just linking some other discussions in....

>bounding box

https://github.com/ArctosDB/arctos/issues/1107

>GADM

https://github.com/orgs/ArctosDB/teams/geo-group/discussions/1?from_comment=1#discussion-1-comment-1

>DwC

DwC should not drive our development, but if we can do whatever "the community" is doing we probably should. I don't have a problem with new "columns," but we should probably have a compelling reason if we're going there.

**Comment by Jegelewicz** [comment]
> if we can do whatever "the community" is doing we probably should.

This may be an aside, but I am working with the iDigBio people to let them know how useful their data flags are and one of the flags that shows up often for me is : 

idigbio_isocountrycode_added | iDigBio ISO 3166-1 alpha-3 Country Code Added.

Is this something we should be thinking about or something that we should tell iDigBio is not useful?

**Comment by dustymc** [comment]
> iDigBio ISO 3166-1 alpha-3 Country Code Added

I think whether that's useful or not depends on what they're trying to do, and I can find no documentation on that. If they're asserting GBR is a standardized-ish way to spell Great Britain then I suppose I don't have much problem with it. I also don't see a lot of value - anyone could add that with a simple webservice.

If they're asserting that GBR is this:

<img width="85" alt="screen shot 2019-02-12 at 9 14 39 am" src="https://user-images.githubusercontent.com/5720791/52654410-c4a35c80-2ea6-11e9-8b0c-d7c39128c377.png">

Instead of this:

<img width="456" alt="screen shot 2019-02-12 at 9 15 21 am" src="https://user-images.githubusercontent.com/5720791/52654420-cb31d400-2ea6-11e9-80f3-52e826ed6372.png">

then they're introducing a conflicting definition which just degrades the data.

**Comment by dustymc** [comment]
#3272 makes this ~irrelevant, closing
