### ISSUE TITLE
Add attribute for Zoo collections

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1369]
Please add the attribute type sex to Zoo collections with the following codes:

female - Of or denoting the sex that can bear offspring or produce eggs, distinguished biologically by the production of gametes (ova) that can be fertilized by male gametes.

female ? - The examiner believes the specimen to be a female, but is uncertain.

male - Physiological sex that produces sperm.

male ? - The examiner believes the specimen to be a male, but is uncertain.

sexes mixed - Lot contains individuals of both sexes.

unknown  - There are no data in the form of a label or field notes. That is, no determination, or attempted determination is available.

**Comment by Jegelewicz** [comment]
@dustymc  I'm sorry to pester, but I need to get this data uploaded for a PhD candidate. Can I get these added please?
Thank you!!!

**Comment by dustymc** [comment]
Done - thanks for the nudge!

**Comment by Jegelewicz** [comment]
Muchas gracias!!!
