### ISSUE TITLE
Duplicate in other collection type code table

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1375]
These two are the same thing:

Centennial Museum and Chihuahuan Desert Gardens | The Centennial Museum and Chihuahuan Desert Gardens is a  cultural history and natural history museum on the campus of the  University of Texas at El Paso in El Paso, Texas. The museum was built  during the 1936 Texas Centennial  http://admin.utep.edu/Default.aspx?tabid=59900 |   |  
-- | -- | -- | --
Centennial Museum and Desert Gardens | https://en.wikipedia.org/wiki/Centennial_Museum_and_Chihuahuan_Desert_Gardens

**Comment by dustymc** [comment]
Thanks!
