### ISSUE TITLE
Editing locality remarks

### ISSUE THREAD

**Issue by droberts49** [ArctosDB/arctos#1379]
Hi Dusty,

I needed to edit something transcribed incorrectly in the 'specimen/event remarks' in the locality section for one of our specimens and was puzzled because the remarks wouldn't show up anywhere in the edit screens. I was able to correct the text by just entering in new information in the 'specimen/event remarks' line. Would it be possible to have the remarks show up in the edit page somewhere?

**Comment by dustymc** [comment]
I do not understand. Screenshots or URLs please?

<img width="571" alt="screen shot 2018-01-04 at 7 03 55 am" src="https://user-images.githubusercontent.com/5720791/34569400-7e3370cc-f11d-11e7-8e36-e45a7d8a2698.png">

<img width="647" alt="screen shot 2018-01-04 at 7 04 10 am" src="https://user-images.githubusercontent.com/5720791/34569414-82db6152-f11d-11e7-8186-e2f3eddeac99.png">

**Comment by ekrimmel** [comment]
Seems like it happens on records where the specimen/event remark contains "

e.g. [CHAS:Bird:3099](http://arctos.database.museum/guid/CHAS:Bird:3099)
![1](https://user-images.githubusercontent.com/11165319/34575644-2394bc60-f141-11e7-8177-89cb67d77fc7.JPG)

vs. [CHAS:Bird:15459](http://arctos.database.museum/guid/CHAS:Bird:15459) (which *does* have content in the specimen/event remarks field)

![2](https://user-images.githubusercontent.com/11165319/34575649-26e66666-f141-11e7-8361-32eb6ffff3ae.JPG)

**Comment by dustymc** [comment]
Thanks, that's what I needed - I'll get it ASAP.

**Comment by dustymc** [comment]
fixed for next release
