### ISSUE TITLE
Don't understand error when attempting specimen event bulkload

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1381]
I am getting the following when attempting to bulkload specimen events:

An error occurred while processing this page!
Error Executing Database Query.
[Macromedia][Oracle JDBC Driver][Oracle]ORA-20372: One of (GUID, UUID) is required. ORA-06512: at "UAM.CF_TEMP_SPECEVENT_KEY", line 7 ORA-04088: error during execution of trigger 'UAM.CF_TEMP_SPECEVENT_KEY'

This message has been logged. Please contact us with any information that might help us to resolve this problem.

upload .xls is attached (cannot attach the .csv)
[HerpOS Specimen Event Bulkloader.xlsx](https://github.com/ArctosDB/arctos/files/1602174/HerpOS.Specimen.Event.Bulkloader.xlsx)

**Comment by dustymc** [comment]
The problem (blank probably-trailing records) won't be in the .xls - you can zip CSV to attach.

The error is the blanks in your INSERT...

```
	insert into cf_temp_specevent (ASSIGNED_BY_AGENT,ASSIGNED_DATE,BEGAN_DATE,COLLECTING_METHOD,COLLECTING_SOURCE,COLL_EVENT_REMARKS,DATUM,DEC_LAT,DEC_LAT_MIN,DEC_LONG,DEC_LONG_MIN,ENDED_DATE,GEOREFERENCE_PROTOCOL,GEOREFERENCE_SOURCE,GUID,HABITAT,HIGHER_GEOG,LAT_DEG,LAT_DIR,LAT_MIN,LAT_SEC,LOCALITY_REMARKS,LONG_DEG,LONG_DIR,LONG_MIN,LONG_SEC,MAXIMUM_ELEVATION,MAX_ERROR_DISTANCE,MAX_ERROR_UNITS,MINIMUM_ELEVATION,ORIG_ELEV_UNITS,ORIG_LAT_LONG_UNITS,SPECIMEN_EVENT_REMARK,SPECIMEN_EVENT_TYPE,SPEC_LOCALITY,VERBATIM_DATE,VERBATIM_LOCALITY,VERIFICATIONSTATUS) values ( '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' ) 
```

http://handbook.arctosdb.org/documentation/understanding-errors.html#cannot-insert-null-into-schematablecolumn

**Comment by Jegelewicz** [comment]
got it, thanks!
