### ISSUE TITLE
Layout on Data Entry page

### ISSUE THREAD

**Issue by ekrimmel** [ArctosDB/arctos#1385]
On the data entry page, the two major columns aren't responsive so don't stack for different screen dimensions/resolutions. And because the browser window (in Chrome and in Firefox) won't scroll left/right, it makes the right hand side of the data entry fields entirely cut off. We need to have the screen magnified for the webinar that @ebraker and @Jegelewicz are presenting next Tuesday, otherwise participants can't read the text on the screen. 

![1](https://user-images.githubusercontent.com/11165319/34582739-a06dd294-f15a-11e7-8c45-0b7928ac0a72.JPG)

Ideas? As a quick-n-dirty fix, Kevin Love (of iDigBio) thought that if the entire right box is contained in a single div then Emily could possibly turn off the absolute formatting style in her browser while she is presenting. We thought you (@dustymc) might have more insight since you probably created this...

**Comment by dustymc** [comment]
neato....

I'll try to make it better, but not sure what that'll take or if I'll be able to get to it before then. 

The right box is #right-col, if that's useful.

I removed the width attribute of #right-col in test - it's still pretty ugly with a lot of zoom, but maybe better and still workable at normal settings??

**Comment by ekrimmel** [comment]
Knowing the name of the div solves our immediate problem--thanks!! @ebraker we can turn off the float styling for the #right-col div just in your browser tab (like Kevin was saying; I can walk you through how to) and it looks like the screenshot below. Not gorgeous, but at least would be functional zoomed in...

<img width="1019" alt="screen shot 2018-01-04 at 8 54 12 pm" src="https://user-images.githubusercontent.com/11165319/34593619-a367f0ce-f191-11e7-8475-3a1122db5bdd.png">

IDK if just removing the width attribute makes the interface better, so while I do think this is something worth improving I'd say hold off on doing that outside test @dustymc... this issue can be de-prioritized now that we have a work-around.

**Comment by ebraker** [comment]
@ekrimmel I think I will probably just leave the screen as is during the webinar and zoom in and out as needed. Since I will be walking through each field in order it should only be an issue when I make the transition from the left stack to the right stack. That way the form will continue to look familiar to new users (and me!).

**Comment by campmlc** [comment]
It would be good to mention to the participants that this can be an issue
depending on your screen or browser, and how to deal with getting to those
extra columns. However, it is much, much better now on my laptop - only
part of the remarks cut off.

**Comment by ekrimmel** [comment]
@ebraker sounds fine, whatever works best for you! Maybe just double check that no pertinent fields are getting cut off when you zoom in (only because I think they were in the *Parts* section when we did our soundcheck). 

For posterity, if you ever need to drop the styling on an element in a web page (e.g. remove the style that tells the stuff on the righthand side of the Data Entry screen to stay right regardless of how wide the browser window is), here is how:

1. Right click anywhere on the web page and click "Inspect."

<img width="294" alt="screen shot 2018-01-08 at 9 39 39 am" src="https://user-images.githubusercontent.com/11165319/34679216-e930c4a2-f45a-11e7-820d-bdf06c9d4b87.png">

2. Look for the name of the element you want to affect, in this case, Dusty told us that it is called "right-col." You can do *cntl-F* to find.

<img width="1221" alt="screen shot 2018-01-08 at 9 40 55 am" src="https://user-images.githubusercontent.com/11165319/34679234-f93138e6-f45a-11e7-8af2-e46e17effebc.png">

3. If you click on the row that has the text "right-col" it will highlight the part of the web page that the code is referring. Click on the "Styles" tab in the righthand bar of the Inspector.

<img width="1220" alt="screen shot 2018-01-08 at 9 40 24 am" src="https://user-images.githubusercontent.com/11165319/34679241-fee3248e-f45a-11e7-8605-0856b48e1697.png">

4. The "Styles" tab shows you the CSS code affecting the element you have selected ("right-col"). In our case, we want to tell it to stop forcing itself against the right edge of the window, and we can do this by unchecking the box that says "float: right."

<img width="1224" alt="screen shot 2018-01-08 at 9 41 04 am" src="https://user-images.githubusercontent.com/11165319/34679247-03ce2250-f45b-11e7-983b-661e0eb3a14a.png">

Anything you change in the Inspector will only affect the browser tab you are in, which means that (1) you can do no permanent damage, and (2) you can have multiple tabs open, e.g. one with the Data Entry screen as normal and a second with the "float: right" style removed. The screenshots above are from Chrome, but any browser should have a similar Inspector interface.

**Comment by campmlc** [comment]
Thanks, Erica!

**Comment by Jegelewicz** [comment]
Add above to documentation? How to...
