### ISSUE TITLE
updating an identifier for all specimens in an accession

### ISSUE THREAD

**Issue by mgoliver** [ArctosDB/arctos#1386]
I've been tasked with correcting an identifier [AHRS (Alaska Heritage Resources Survey)] for a couple UAM Archaeology accessions that have so many specimens it doesn't make sense to go through and do them all manually. Is there a way to either update the AHRS identifier for all specimens in an accession at once (every specimen gets the same AHRS identifier) or is it possible to delete the AHRS identifier from all of the specimens in an accession so that I can then use Batch Tools to bulkload the correct AHRS identifier?

For example: UAMN accession UA74-027 has 7189 specimens that all have AHRS identifier BET-00040 and they all need to be changed to BET-00041.

**Comment by dustymc** [comment]
There is no bulk delete or edit. (Would be easy enough to do, but it's scary.) If you'll send me a list of specimens (by GUID) or some way to find them (accessions including owning collection would work) I can delete and then you can add the correct data.

**Comment by mgoliver** [comment]
Thanks, Dusty. Would "UAM:Arc" be what you mean by owning collection?
UAM:Arc UA74-027
UAM:Arc UA93-114

**Comment by dustymc** [comment]
Yup, that's it.

```
select
  accn_number,
  guid,
  COLL_OBJ_OTHER_ID_NUM_ID,
  OTHER_ID_TYPE,
  DISPLAY_VALUE
from
  accn,
  trans,
  cataloged_item,
  coll_obj_other_id_num,
  flat,
  collection
where
  accn.transaction_id=cataloged_item.accn_id and
  accn.transaction_id=trans.transaction_id and
  trans.collection_id=collection.collection_id and
  cataloged_item.collection_object_id=coll_obj_other_id_num.collection_object_id and
  cataloged_item.collection_object_id=flat.collection_object_id and
  collection.guid_prefix='UAM:Arc' and
  OTHER_ID_TYPE='AHRS (Alaska Heritage Resources Survey)' and
  accn.accn_number in ('UA74-027','UA93-114')
;
```

Please confirm that the attached Other IDs are what you want to delete and I'll zap them.

[temp_arc_id.csv.zip](https://github.com/ArctosDB/arctos/files/1605223/temp_arc_id.csv.zip)

**Comment by mgoliver** [comment]
Yes those are the ones.

**Comment by dustymc** [comment]
7693 rows deleted.
