### ISSUE TITLE
Clarify instructions: Bulkload classifications (taxonomy)

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#1389]
Clarify instructions by adding the following.  Instructions currently read:

When the data checks are complete and accurate, the Status bar will read "go_go_all."

Mark to load: After verifying, click this to flag for loading. Reload this page to check progress.
____________
Add the suggestions in **bold**:

When the data checks are complete and accurate, the Status bar will read "go_go_all."  

**Reload page and Status Bar will begin to list errors or show that checks have passed.  If necessary Download your data, correct errors, delete data and reload corrected data.  Reload page until the Status bar reads "all_checks_passed."  Marking to load when the Status bar reads "go_go_all" will result in errors.** 

Mark to load: **When the Status bar reads "all_checks_passed**, click this to flag for loading. 

**Status bar will read "ready_to_load."  Reload this page until it reads "made_updates_all done."  Delete all of your data using above link.**
____________

**Comment by ekrimmel** [comment]
thank you @sharpphyl! I wholeheartedly agree with your suggested changes--the way the documentation is now is not clear and seeing this issue helped clear it up for me

**Comment by dustymc** [comment]
done for next release

**Comment by sharpphyl** [comment]
Thanks!
