### ISSUE TITLE
Specimen event bulkloader does not recognize higher geography

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1390]
The specimen event bulkloader will not recognize this higher geography: North America, United States, Florida, Saint John's County

I copied it directly from the geography table and still it does not work.

Here is what is in the file:
COLLECTING_SOURCE,VERBATIM_DATE,BEGAN_DATE,ENDED_DATE,GUID,HIGHER_GEOG,SPEC_LOCALITY,HABITAT,VERBATIM_LOCALITY,COLL_EVENT_REMARKS,DATUM,DEC_LAT,DEC_LONG,GEOREFERENCE_SOURCE,SPECIMEN_EVENT_TYPE,ASSIGNED_DATE,ASSIGNED_BY_AGENT,ORIG_ELEV_UNITS,MINIMUM_ELEVATION,MAXIMUM_ELEVATION,GEOREFERENCE_PROTOCOL,LOCALITY_REMARKS,MAX_ERROR_DISTANCE,MAX_ERROR_UNITS,SPECIMEN_EVENT_REMARK,ORIG_LAT_LONG_UNITS,COLLECTING_METHOD,VERIFICATIONSTATUS,LAT_DEG,DEC_LAT_MIN,LAT_MIN,LAT_SEC,LAT_DIR,LONG_DEG,DEC_LONG_MIN,LONG_MIN,LONG_SEC,LONG_DIR
wild caught,1980/08/21,1980-08-21,1980-08-21,UTEP:Herp:9368,"North America, United States, Florida, Saint John's County","N of St Augustine, 4 miles from U. S. Highway 1 on 9-Mile Road",,"USA, Florida, St Johns County, N Of St Augustine, 4 Mi. From Ushy 1 On 9-Mile Rd",,North American Datum 1927,29.98790,-81.45067,"determined by collector from a paper map subsequent to time of collection, USGS 1:24,000 Bakersville Quad",accepted place of collection,2011-08-15,Carl S. Lieb,,,,MaNIS georeferencing guidelines,,1.053,mi,"9-Mile Rd/jct Hwy 1, extent 0.03",decimal degrees,,,,,,,,,,,,

**Comment by dustymc** [comment]
Something (possibly whatever you used to convert whatever you started with to CSV) is HTML-escaping quotes.

```
UAM@ARCTOS> select ':'||higher_geog||':' from cf_temp_specevent where status='HIGHER_GEOG not found';

':'||HIGHER_GEOG||':'
------------------------------------------------------------------------------------------------------------------------
:North America, United States, Florida, Saint John&#39;s County:
```

I updated that one for you while I was in there.

```
UAM@ARCTOS> select ':'||higher_geog||':' from cf_temp_specevent where status='HIGHER_GEOG not found';

':'||HIGHER_GEOG||':'
------------------------------------------------------------------------------------------------------------------------
:North America, United States, Florida, Saint John's County:
```

**Comment by Jegelewicz** [comment]
Well, I had moved on and deleted that from the staging table before I saw this....so I still can't make it work. Can I fix this myself or is it something I would always have to ask help with?

**Comment by dustymc** [comment]
You can edit the CSV in a plain-text editor, or probably somehow tell whatever you're converting from not to HTML-escape.

I re-updated the data in the staging table.

**Comment by Jegelewicz** [comment]
I edited in Notepad and it didn't seem to fix the problem...

**Comment by Jegelewicz** [comment]
Is including the apostrophe in the Higher Geog is not a good thing?

**Comment by dustymc** [comment]
Please attach the CSV.

**Comment by Jegelewicz** [comment]
Here is excel file
[Herp Specimen Event Bulkloader.xlsx](https://github.com/ArctosDB/arctos/files/1613486/Herp.Specimen.Event.Bulkloader.xlsx)

**Comment by dustymc** [comment]
You can zip/compress CSV to attach. In this case the xls had what I needed. All my fault - sorry! A fix should be patched in.

**Comment by Jegelewicz** [comment]
It still isn't working.  Here is .csv
[Herp Specimen Event Bulkloader.zip](https://github.com/ArctosDB/arctos/files/1617139/Herp.Specimen.Event.Bulkloader.zip)

**Comment by dustymc** [comment]
I opened your CSV in a text editor and changed...

<img width="1180" alt="screen shot 2018-01-10 at 7 52 48 am" src="https://user-images.githubusercontent.com/5720791/34781706-66d2df36-f5db-11e7-8b79-5e8ed53ae9d5.png">

to

<img width="1176" alt="screen shot 2018-01-10 at 7 54 12 am" src="https://user-images.githubusercontent.com/5720791/34781728-7924b0a6-f5db-11e7-8554-b1ba6d188bcd.png">

and 

<img width="143" alt="screen shot 2018-01-10 at 7 54 51 am" src="https://user-images.githubusercontent.com/5720791/34781775-92448f0c-f5db-11e7-993b-b07fa36c3e61.png">

It would be very useful for the documentation if you could provide some detail on the path that lead you here.

**Comment by Jegelewicz** [comment]
I don't understand what happened. My original try appeared just as your edited text file and would not work so I added in the html for the apostrophe and that did not work. Now the apostrophe works.
