### ISSUE TITLE
Specimen event bulkoader invalid number message

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1392]
When attempting to load the following I get the message:
An error occurred while processing this page!
Error Executing Database Query.
[Macromedia][Oracle JDBC Driver][Oracle]ORA-01722: invalid number 

Here is the data - I cannot figure out which number is the problem. I have tried changing all of them!!

COLLECTING_SOURCE,VERBATIM_DATE,BEGAN_DATE,ENDED_DATE,GUID,HIGHER_GEOG,SPEC_LOCALITY,HABITAT,VERBATIM_LOCALITY,COLL_EVENT_REMARKS,DATUM,DEC_LAT,DEC_LONG,GEOREFERENCE_SOURCE,SPECIMEN_EVENT_TYPE,ASSIGNED_DATE,ASSIGNED_BY_AGENT,ORIG_ELEV_UNITS,MINIMUM_ELEVATION,MAXIMUM_ELEVATION,GEOREFERENCE_PROTOCOL,LOCALITY_REMARKS,MAX_ERROR_DISTANCE,MAX_ERROR_UNITS,SPECIMEN_EVENT_REMARK,ORIG_LAT_LONG_UNITS,COLLECTING_METHOD,VERIFICATIONSTATUS,LAT_DEG,DEC_LAT_MIN,LAT_MIN,LAT_SEC,LAT_DIR,LONG_DEG,DEC_LONG_MIN,LONG_MIN,LONG_SEC,LONG_DIR
captive,no date,1960-01-01,2015-05-01,UTEP:Herp:20256,"North America, United States, Texas, Hudspeth County","Indio Mountains Research Station, Purple Sage Mine",,"USA, Texas, Hudspeth County, Indio Mountains Research Station, Purple Sage Mine [30 Deg 44'58""N, 105 Deg 01'31""W, Ca. 3860 Ft]",Born in captivity,unknown,,,collector's notes,accepted place of collection,2015-05-01,Carl S. Lieb,ft,3810,3960,not recorded,Indio Mountains,,,IMRS/Purple Sage Mine,deg. min. sec.,,,30,,44,58,N,105,,01,31,W
captive,no date,1960-01-01,2015-05-01,UTEP:Herp:20257,"North America, United States, Texas, Hudspeth County","Indio Mountains Research Station, Purple Sage Mine",,"USA, Texas, Hudspeth County, Indio Mountains Research Station, Purple Sage Mine [30 Deg 44'58""N, 105 Deg 01'31""W, Ca. 3860 Ft]",Born in captivity,unknown,,,collector's notes,accepted place of collection,2015-05-01,Carl S. Lieb,ft,3810,3960,not recorded,Indio Mountains,,,IMRS/Purple Sage Mine,deg. min. sec.,,,30,,44,58,N,105,,01,31,W

**Comment by dustymc** [comment]
Please attach the CSV.

**Comment by Jegelewicz** [comment]
[Herp Specimen Event Bulkloader.txt](https://github.com/ArctosDB/arctos/files/1613401/Herp.Specimen.Event.Bulkloader.txt)

**Comment by dustymc** [comment]
That is tab-delimited text?? I think I may have found the problem (bad datatype in the temp table) but I can't check without the CSV you're using.

**Comment by Jegelewicz** [comment]
I cannot attach a .csv
Here is the excel version
[Herp Specimen Event Bulkloader.xlsx](https://github.com/ArctosDB/arctos/files/1613477/Herp.Specimen.Event.Bulkloader.xlsx)

**Comment by Jegelewicz** [comment]
Here is .csv
[Herp Specimen Event Bulkloader (2).zip](https://github.com/ArctosDB/arctos/files/1617151/Herp.Specimen.Event.Bulkloader.2.zip)

**Comment by dustymc** [comment]
THis works fine for me - what are you seeing?

**Comment by Jegelewicz** [comment]
When attempting to load the following I get the message:
An error occurred while processing this page!
Error Executing Database Query.
[Macromedia][Oracle JDBC Driver][Oracle]ORA-01722: invalid number

**Comment by Jegelewicz** [comment]
@dustymc 
Now I get this error message:

> An error occurred while processing this page!
> Error Executing Database Query.
> [Macromedia][Oracle JDBC Driver][Oracle]ORA-20001: Error and units, datum, and georeference source and protocol must be accompanied by coordinates. ORA-06512: at "UAM.TRG_LOCALITY_BIU", line 38 ORA-04088: error during execution of trigger 'UAM.TRG_LOCALITY_BIU'
> 
> This message has been logged. Please contact us with any information that might help us to resolve this problem.
> 

But there are coordinates. I can't figure out what the problem is! I'm probably just too close to it...

**Comment by dustymc** [comment]
Bah - need to add conversion to DD.d format from others.

**Comment by dustymc** [comment]
This is fixed and patched into production. The DD.d conversion happens on INSERT so you'll need to "delete all of your data from the staging table" and re-load for anything with coordinates in any format other than decimal degrees.
