### ISSUE TITLE
Can't delete specimens that are in encumberance

### ISSUE THREAD

**Issue by mgoliver** [ArctosDB/arctos#1393]
I've tried deleting the specimens in our "duplicated record" encumberance and initially couldn't delete them because two of the records are listed as being part of a data loan. My way around this was to temporarily remove those two records from the encumberance in order to delete the rest of the duplicated records, with the plan being to add them back to the encumberance afterwards so I can get them deleted another time. None of the other specimens are coming up as being in loans but attempts to delete them still result in the "integrity constraint violated" error. Besides checking each specimen individually (there are too many of them) I'm not sure how else to find out which ones are preventing the deletion or how they're being used to cause the error. Do you have any suggestions? Thank you!

![screen shot 2018-01-08 at 1 50 47 pm](https://user-images.githubusercontent.com/28404497/34696544-ba972732-f47b-11e7-9672-64d3a10286d0.png)

![screen shot 2018-01-08 at 2 11 24 pm](https://user-images.githubusercontent.com/28404497/34697063-d7eae47a-f47d-11e7-85eb-eed3861eddb2.png)

**Comment by dustymc** [comment]
FK_TABMEDIARELFKEY_CATITEM is Media relationships.

http://arctos.database.museum/SpecimenResults.cfm?media_type=any&encumbrance_id=10000017

**Comment by mgoliver** [comment]
Aha! I will get to fixing those. Thanks, Dusty.

**Comment by campmlc** [comment]
I am having difficulty deleting a parasite specimen that had the wrong host data pulled and the wrong host relationship created. I have deleted the relationship to the host and the reciprocal relationship from the host back to the parasite. I still get an error message of a child relationship. I then deleted the AF other ID, but still get the child error. What else am I missing?
http://arctos.database.museum/guid/MSB:Para:26430

**Comment by Jegelewicz** [comment]
HMMMM..wonder if GBIF and iDigBio relationships are doing this? @dustymc ?

**Comment by tucojoe** [comment]
I’m having problems deleting a parasite too....

**Comment by dustymc** [comment]
Without the error, I'm going to guess sunspots....
