### ISSUE TITLE
accns and permits

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1395]
from "New permit types for research and transfer" thread

--------------------

* REQUIRE some action (checking box maybe) before saving accns without permit information
* Send "this accn has no permit" emails when someone force-creates an accn without a permit.

Can the notifications be by-request - eg, add a "permit notification contact agent" when you create an accn if you want reminders? I don't think this is something we should force on people.

What event would trigger notifications? (E.g., days before/after/etc. something.)

---------------

Make adding permits easier: https://github.com/ArctosDB/arctos/issues/1394

-------------

Clarify https://arctos.database.museum/info/ctDocumentation.cfm?table=CTPERMIT_TYPE for "permit not required." Perhaps a howto??

There are three possible specimen-->accn-->permit situations (and some details).

1) An accn has no permits attached (which will require an action - eg, checking a box) --> reported (eg, via GGBN) as "permit information not available"
2) An accn has permit(s) NOT of type "permit not required" attached --> reported (eg, via GGBN) as "permit available"
2) An accn has permit(s) of type "permit not required" attached-->an assertion that a permit is not required 
    * No level of specificity is required. A specific permit (e.g., "this activity is permitted on land owned by whatever under statute bla bla bla....") may help with reporting or similar. A super-generic permit ("use this for all Inst:Coll activities not requiring permits") may satisfy Nagoya protocols without adding much work.

--------

Clarify that the current/new model supports any number of agents in any role; it's possible to have a permit "issued by" an agency and multiple contacts at the agency, for example. http://handbook.arctosdb.org/documentation/permits.html#permit-roles-and-agents

-----

**Comment by ccicero** [comment]
This synopsys seems reasonable to me. However, I'm still not clear on where the reason for not requiring a permit would go. Remarks? Can/should we force someone to give a reason when they select such a permit type?

Send "this accn has no permit" emails when someone force-creates an accn without a permit.
---> I thought the idea was that someone can't force create an accn without a permit, at the very least they should have to check the 'permit information not available' box
???

**Comment by AJLinn** [comment]
> Send "this accn has no permit" emails when someone force-creates an accn without a permit.
---> I thought the idea was that someone can't force create an accn without a permit, at the very least they should have to check the 'permit information not available' box
???

Ethnological/history and fine arts accessions rarely have permits associated with the accession. We have Deeds of Gift, Bills of Sale, Transfer Agreements, or some other kind of paperwork transferring ownership from an individual to the institution that would almost always accompany them, but almost never a permit. We must have a "no permit required" option for our accessions, and if I have to "force" the creation of our accessions, that's going to be pretty tiresome.

**Comment by ccicero** [comment]
Interesting point Angela. I would consider a Transfer Agreement or Deed of Gift as some type of permit that authorizes you to have the material. We have similar 'loan agreements' which would have a permit type of 'transfer of custody. How do you enter those now?

**Comment by dustymc** [comment]
>I'm still not clear on where the reason for not requiring a permit would go. Remarks? 

That's the current guidance in https://arctos.database.museum/info/ctDocumentation.cfm?table=CTPERMIT_TYPE, but I think that needs expanded as a how-to or something. I'm not sure we can or should try to _force_ anything here - someone collecting a dandelion from their yard shouldn't have to spend hours justifying why they don't need permits. At the same time, someone collecting something more borderline (invertebrates in a national park maybe) should have an opportunity to document the research that lead them to not needing a permit, and doing that as a permit type provides an opportunity for them to attach documentation (maybe the "you don't need a permit" letter from the Park they're collecting in), link to agents (the person writing that "you don't need a permit" letter), etc.


> I thought the idea was that someone can't force create an accn without a permit, at the very least they should have to check the 'permit information not available' box

"check the 'permit information not available' box" is "force create" - they've done something/made an assertion that they don't have permit info (or don't want to say anything about it at the moment, anyway). It's impossible to forget/not notice permits with the addition of the new proposed button/check/whatever, but also very easy to bypass. I think that's a reasonable compromise between "forcing" people to at least consider permits and not making the process overly burdensome, but I'm totally open to suggestions on all of this.

**Comment by dustymc** [comment]
@AJLinn - I think any sort of "we're allowed to have this" documentation could qualify as a permit. That's not the only path to associating that stuff with specimens, but it may be a useful one because it groups similar types of information, allows links to agents, facilitates reporting, etc.

**Comment by AJLinn** [comment]
> Interesting point Angela. I would consider a Transfer Agreement or Deed of Gift as some type of permit that authorizes you to have the material. We have similar 'loan agreements' which would have a permit type of 'transfer of custody. How do you enter those now?

In terms of the legal requirements for a transfer of ownership, we don't actually technically need a deed of gift (the law says there needs to be 1. an offer, 2. a physical transfer, and 3. an acknowledgement of the receipt). A deed of gift wraps those all up in a handy package with signatures for us, but in terms of our legal requirements, it's not necessary. But if we want to use a Deed of Gift as our "permit" then I'm okay with that.

Loan agreements for cultural collections are not noted in the Loans section but I guess we could add our printed / signed agreement as a permit - this is a good idea. These are kept in files in our lab in hard copy but it's worth adding them as a permit on the loan page - thanks for the suggestion. If we have an international loan that does require an export/import permit or some MMPA affidavit, then we would certainly add that as a permit to the loan.

**Comment by dustymc** [comment]
For next release, users must click thing if there are no permits.
