### ISSUE TITLE
Depick locality in data entry does not void depth data

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#1396]
When we pick a locality or event that has depth for one entry, then depick it for the next entry, the depth remains and we cannot overwrite it.

![pick locality on data entry](https://user-images.githubusercontent.com/15368365/34786224-c1ca2380-f5f0-11e7-9ee5-e97639a4cccd.JPG)

The depth remains and we cannot eliminate it

![depick locality does not eliminate depth](https://user-images.githubusercontent.com/15368365/34786228-c5c73a4a-f5f0-11e7-9aa4-d4ddb5d212d5.JPG)

**Comment by dustymc** [comment]
fixed for next release
