### ISSUE TITLE
add default agent value to identifications bulkloader

### ISSUE THREAD

**Issue by ekrimmel** [ArctosDB/arctos#1401]
The identifications bulkloader does not require an agent to be attached, but adding an identification via the specimen record interface does require an agent in "Identified By." Can we have a default value of "unknown" added to bulkloaded identifications that lack an agent? When we are adding or updating identifications via the specimen record interface it is annoying to have to fill in "Identified By=unknown" on existing identifications (that were bulkloaded) in order to save.

**Comment by dustymc** [comment]
Hey, that is annoying!

I think I vote the other way: remove the "requirement" for an IDBY on the specimendetail/ID form.

Objections?

**Comment by Jegelewicz** [comment]
I prefer that it be required. I want to know who identified stuff! The person doing the identification can be an indicator of how reliable the ID is...

**Comment by dustymc** [comment]
> person doing the identification can be an indicator of how reliable the ID is.

Absolutely, but if you don't know there's no functional difference between "unknown" and NULL. 

"unknown" does require an action which might encourage someone to properly record the data they have, and that may be enough reason to "require" an identifier. (The structure won't REALLY let me require it, but I could make the ID bulkloader reject records without an identifier.)

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/2528
