### ISSUE TITLE
Parent Contains Positions error

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1402]
I would like to use bulk edit container to update the label information for the attached file. When I try, I get the following error. There are probably jars scanned onto shelves that also have positions causing the problem. However, Arctos doesn't give me any info as to which of the barcodes are the problems, and if it did, it wouldn't allow me to correct the problem.  Dusty, can you help with this? These are legacy issues created before we placed constraints on positions. 

An error occurred while processing this page! 
Error Executing Database Query. 
[Macromedia][Oracle JDBC Driver][Oracle]ORA-20000: FAIL: Parent contains positions and cannot contain not-position containers ORA-06512: at "UAM.BULKUPDATECONTAINER", line 79 ORA-06512: at line 1
This message has been logged. Please contact us with any information that might help us to resolve this problem.

[jar label re-upload  9-22-16 edited mlc.zip](https://github.com/ArctosDB/arctos/files/1629000/jar.label.re-upload.9-22-16.edited.mlc.zip)

**Comment by campmlc** [comment]
Here is at least one of the problems: 
jar P294V is scanned into shelf P29TY without a position; please move this to MSBPARAWCR8A

**Comment by campmlc** [comment]
I was able to delete this barcode - will try to see if that fixes it. If so, that would be the only recourse users have in this situation, as a single one of these issues prevents editing the container in question or any of the other associated parent/child containers.

**Comment by dustymc** [comment]
>wouldn't allow me to correct the problem.

This can only come from the parent having problems - I'm not sure why you wouldn't be able to correct it.

I added more to the containerContentCheck error message.

**Comment by campmlc** [comment]
Because the jar was scanned onto a shelf before positions were added and
before the constraints on positions were created, I could not edit either
the jar or the parent shelf or anything else in the same parent. And since
I was trying to load a csv bulk edit container file of several hundred
records, I didn't know which container was causing the problem. I finally
went through each container one by one to find the problem barcode and
deleted it and then recreated it. There should be a better way of finding
what record is causing the Oracle errors.
