### ISSUE TITLE
Refresh/Pull Global Names does not always pull current WoRMS taxon

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#1405]
When adding _Vasticardium wilsoni_ as a new taxon, a refresh of Global Names brought up only GBIF even though the species was accepted on WoRMS.  See screen clips for details.  Any idea what causes this and whether Arctos can correct the problem?

![worms image 1](https://user-images.githubusercontent.com/15368365/35011187-880afee0-fac2-11e7-8dbe-244893e45f8b.JPG)

![arctos image 1](https://user-images.githubusercontent.com/15368365/35011192-8ad8b7c0-fac2-11e7-8d1b-d0c8d6fbadbe.JPG)

**Comment by dustymc** [comment]
Arctos can only access what GN provides. This looks like an issue between GN and Worms.
