### ISSUE TITLE
media attached to collecting events

### ISSUE THREAD

**Issue by amgunderson** [ArctosDB/arctos#1406]
Should this image show up on 319 specimens? http://arctos.database.museum/media/10498076
It is linked to collecting event 10971209 which is used by MSB hosts and parasites and UAM Ethnology. Can I delete the media link to the event so it does not show up on all the Ethnology records assigned to that event?

**Comment by amgunderson** [comment]
Or can we create a new event and add the ethnology records to it enmass?

**Comment by dustymc** [comment]
>Should this image show up 

Structurally yes (because https://github.com/ArctosDB/arctos/issues/860), although I'm not sure what importance the event has to that particular image. (I guess it does show some birch trees.)

The relationship is event (with media)-->locality-->event (with specimens - http://arctos.database.museum/Locality.cfm?action=findCollEvent&locality_id=1080) so messing with the event won't get rid of it - you'd need to move the image's event to a new locality.

https://github.com/ArctosDB/arctos/issues/865 will probably un-do that unless you change spec locality or etc.

@ccicero

**Comment by dustymc** [comment]
>create a new locality

I'll just auto-merge it - https://github.com/ArctosDB/arctos/issues/865 (or http://handbook.arctosdb.org/documentation/locality.html#maintenance for a way to avoid that)

>There's got to be a better way to link images to just the specimens or events where they belong.

I maintain that the linkage is important - photos of a locality enhance the value of other junk using that locality. That of course makes no sense when the locality is "we have absolutely no idea," and that's what this one is. A bunch of them have nothing to do with any locality, one of them apparently shows some unknown bushes, etc. And a bunch are linked to specimens which DO have useful locality data.  

Perhaps we should remove the "% locality" media relationship(s) altogether - media ALWAYS has temporal data (it wasn't created tomorrow....), and localities purposefully avoid that.

@mkoo @ccicero help!

http://arctos.database.museum/MediaSearch.cfm?action=search&media_id=10003217,10003375,10003466,10006377,10008154,10008156,10008157,10008256,10008258,10499100,10004051,10005915,10006281,10006375,10008162,10008170,10008172,10008261,10008262,10008342,10000276,10003467,10007961,10008150,10008153,10008158,10008164,10008166,10008169,10003219,10003573,10004769,10007679,10008151,10008160,10008257,10008266,10008268,10008339,10002977,10004049,10004767,10004834,10007633,10008161,10008171,10008255,10008260,10008264,10008265,10008267,10008269,10008402,10004766,10005391,10006300,10006784,10007310,10008167,10008263,10008338,10002976,10003470,10003572,10004459,10004768,10008159,10008168,10008259,10008382,10004050,10006282,10008152,10008155,10008163,10008165

**Comment by campmlc** [comment]
It would make more sense to have any media associated with the collecting
event, for the reason Dusty described. Localities change over time.

**Comment by sharpphyl** [comment]
Thanks for eliminating these images from our records.  It agree it's great to be able to associate images with the collecting event as long as they're relevant.

**Comment by dustymc** [comment]
Not sure what happened, but thanks to whoever it was that did something for doing whatever you did...

Here are Media currently attached to Localities.

```

UAM@ARCTOS> select media_id from media_relations where media_relationship like '% locality';

  MEDIA_ID
----------
  10000072
  10003221
  10003222
  10003223
  10003228
  10003640
  10003641
  10003839
  10004980
  10004981
  10004982
  10004983
  10004984
  10004985
  10004986
  10004987
  10004988
  10004989
  10004990
  10004991
  10004992
  10004993
  10004995
  10004996
  10004997
  10004998
  10004999
  10005000
  10006911
  10006916
  10006917
  10006919
  10006920
  10006923
  10006924
  10006925
  10006926
  10006927
  10006929
  10006930
  10006931
  10006932
  10007019
  10007020
  10007021
  10007022
  10007023
  10007024
  10007025
  10007026
  10007028
  10007574
  10007746
  10008406
  10008504
  10187280
  10187281
  10187282
  10187283
  10187284
  10187285
  10187286
  10187287
  10187288
  10187289
  10187290
  10187291
  10187292
  10187349
  10187425
  10187426
  10187432
  10187447
  10187450
  10187453
  10187456
  10187457
  10187457
  10187509
  10187534
  10187609
  10187686
  10207228
  10207229
  10207231
  10207232
  10207233
  10207247
  10207274
  10207283
  10207284
  10207297
  10207298
  10207342
  10207346
  10207422
  10207466
  10207470
  10207473
  10207474
  10207475
  10207476
  10207477
  10207502
  10207545
  10207547
  10207574
  10207574
  10207575
  10207576
  10207577
  10207579
  10207586
  10207587
  10207588
  10207595
  10207596
  10207597
  10207598
  10207599
  10207600
  10207601
  10207602
  10207603
  10207604
  10207605
  10207606
  10207607
  10207607
  10207608
  10207608
  10207609
  10207610
  10207611
  10207632
  10207638
  10207663
  10207663
  10207664
  10207664
  10207665
  10207665
  10207666
  10207666
  10207692
  10207765
  10207816
  10207957
  10207957
  10207979
  10208968
  10208987
  10208988
  10208989
  10209017
  10209033
  10209070
  10209072
  10209075
  10209078
  10209992
  10209993
  10209994
  10210005
  10210008
  10210018
  10210021
  10210031
  10210047
  10210048
  10210049
  10210050
  10210068
  10210082
  10210191
  10210202
  10210203
  10210205
  10210233
  10210236
  10210248
  10210249
  10210261
  10210262
  10210367
  10210391
  10210397
  10210410
  10210412
  10210602
  10211633
  10211645
  10211782
  10211789
  10211790
  10211791
  10211792
  10211953
  10211957
  10211958
  10211969
  10211985
  10211987
  10212049
  10212420
  10212424
  10212426
  10212436
  10212438
  10212439
  10212440
  10212443
  10212444
  10212445
  10212446
  10212448
  10212449
  10212461
  10212462
  10212463
  10212464
  10212477
  10212478
  10212729
  10213331
  10213482
  10213733
  10225802
  10225803
  10225814
  10225833
  10225990
  10225993
  10225993
  10225998
  10226032
  10226043
  10226044
  10226045
  10226046
  10226048
  10226060
  10226061
  10257306
  10268796
  10268797
  10268799
  10268803
  10272989
  10304674
  10312587
  10320929
  10320930
  10322360
  10322361
  10322370
  10322371
  10322372
  10322373
  10323151
  10323152
  10323153
  10323185
  10323188
  10323189
  10323190
  10323191
  10323192
  10323193
  10323194
  10323201
  10359499
  10361513
  10361516
  10399486
  10418078
  10418078
  10471783
  10471784
  10471785
  10471786
  10441485
  10441486
  10441487
  10441488
  10435920
  10435921
  10499872
  10499873
  10499874
  10499875
  10499876
  10499935
  10499936
  10499937
  10499942
  10499943
  10499944
  10499945
  10499946
  10499947
  10499948
  10499949
  10499950
  10499951
  10499952
  10499953
  10484644
  10499974
  10499975
  10499976
  10499977
  10499978
  10499979
  10499996
  10499997
  10499998
  10499999
  10500000
  10500001
  10500002
  10500003
  10500004
  10500005
  10500006
  10500007
  10500008
  10500009
  10500010
  10500011
  10500012
  10500013
  10500014
  10500015
  10508447
  10499336
  10499341
  10499342
  10499343
  10499344
  10499345
  10499346
  10499347
  10499348
  10499349
  10499350
  10499351
  10499354
  10499355
  10499356
  10499357
  10499358
  10499359
  10499360
  10499361
  10499362
  10499364
  10499365
  10499370
  10499371
  10499372
  10499373
  10499374
  10499375
  10499376
  10499377
  10499379
  10499380
  10499381
  10499382
  10499383
  10499384
  10499388
  10499390
  10499391
  10499392
  10499393
  10499394
  10499395
  10499396
  10499398
  10499399
  10499400
  10499401
  10499402
  10499403
  10499404
  10499405
  10499487
  10499488
  10499489
  10499490
  10499491
  10499492
  10499493
  10499494
  10499495
  10499496
  10499497
  10499499
  10499500
  10499501
  10499502
  10499505
  10499506
  10499507
  10499508
  10499701
  10499702
  10499703
  10499704
  10499705
  10499706
  10499707
  10499708
  10499709
  10499710
  10499711
  10499712
  10499713
  10499714
  10499715
  10499716
  10499717
  10499719
  10499720
  10499721
  10499722
  10499724
  10499725
  10499726
  10499727
  10499728
  10499729
  10499730
  10499731
  10499732
  10499733
  10499734
  10499735
  10499736
  10499737
  10499740
  10499741
  10499742
  10499743
  10499745
  10499746
  10499747
  10499748
  10499749
  10499774
  10499775
  10499776
  10499780
  10499781
  10499782
  10499783
  10499784
  10499785
  10499786
  10499787
  10499788
  10499789
  10499790
  10499807
  10499808
  10499877
  10499878
  10499879
  10499880
  10499881
  10499882
  10499883
  10499884
  10499885
  10499886
  10499887
  10499888
  10499889
  10499890
  10499891
  10499892
  10499893
  10499894
  10499895
  10484084
  10499438
  10499439
  10499440
  10499442
  10499443
  10499444
  10499445
  10499446
  10499447
  10499448
  10499449
  10499450
  10499451
  10499452
  10499453
  10499454
  10499456
  10499457
  10499458
  10499462
  10499509
  10499510
  10499511
  10499512
  10499513
  10499514
  10499515
  10499516
  10499517
  10499518
  10499519
  10499520
  10499521
  10499522
  10499523
  10499524
  10499547
  10499548
  10499549
  10499550
  10499551
  10499552
  10499553
  10499554
  10499555
  10499556
  10499757
  10499758
  10499759
  10499761
  10499762
  10499763
  10499764
  10499765
  10499767
  10499768
  10499769
  10499771
  10499772
  10499773
  10499406
  10499408
  10499409
  10499410
  10499411
  10499415
  10499416
  10499417
  10499418
  10499419
  10499423
  10499424
  10499425
  10499426
  10499427
  10499428
  10499429
  10499430
  10499431
  10499432
  10499433
  10499437
  10499954
  10499967
  10499968
  10499969
  10499970
  10499971
  10499972
  10499973
  10508032
  10508033
  10508034
  10508045
  10508046
  10508047
  10508048
  10508049
  10508050
  10508052
  10508053
  10508057
  10508058
  10508059
  10508060
  10508061
  10508063
  10508067
  10508076
  10508078
  10508169
  10508184
  10508185
  10508186
  10508188
  10508190
  10508192
  10508194
  10508195
  10508201
  10508203
  10499832
  10499833
  10499835
  10499836
  10499838
  10499839
  10499840
  10499841
  10499842
  10499843
  10499844
  10499845
  10499846
  10499847
  10499848
  10499849
  10499850
  10499851
  10499852
  10499853
  10499854
  10499809
  10499810
  10499811
  10499812
  10499813
  10499814
  10499815
  10499816
  10499817
  10499818
  10499819
  10499820
  10499821
  10499822
  10499823
  10499824
  10499825
  10499826
  10499827
  10499828
  10499829
  10499830
  10484352
  10500096
  10500097
  10500102
  10500104
  10500105
  10500106
  10500107
  10500109
  10508123
  10508124
  10508125
  10508126
  10508127
  10508128
  10508129
  10508130
  10508132
  10508133
  10508134
  10508135
  10508136
  10508137
  10508138
  10508139
  10508141
  10508326
  10508330
  10508331
  10508332
  10508333
  10508334
  10508335
  10508336
  10508337
  10508338
  10508339
  10508340
  10508380
  10499597
  10499598
  10499599
  10499600
  10499601
  10499602
  10499603
  10499604
  10499605
  10499606
  10499607
  10499608
  10499609
  10499610
  10499611
  10499612
  10499613
  10499614
  10499615
  10499616
  10499617
  10499618
  10499619
  10499620
  10499621
  10499622
  10499623
  10499624
  10499625
  10499626
  10499627
  10499628
  10499629
  10499630
  10499631
  10499632
  10499633
  10499634
  10499635
  10499636
  10499637
  10499638
  10499639
  10499640
  10499641
  10499642
  10499643
  10499644
  10499645
  10499646
  10499647
  10499648
  10499649
  10499650
  10499651
  10499652
  10499653
  10499654
  10499655
  10499656
  10499914
  10499915
  10499916
  10499917
  10499918
  10499919
  10499920
  10499921
  10499922
  10499923
  10499924
  10499925
  10499926
  10499927
  10499928
  10499929
  10499930
  10499931
  10499932
  10499933
  10499934
  10499896
  10499897
  10499898
  10499899
  10499899
  10499900
  10499901
  10499902
  10499903
  10499904
  10499905
  10499906
  10499907
  10499908
  10499909
  10499910
  10499911
  10499912
  10499913
  10500051
  10500052
  10500053
  10500054
  10500055
  10500056
  10500057
  10500058
  10500059
  10500060
  10500061
  10500068
  10500069
  10500070
  10500071
  10500072
  10500075
  10500076
  10500077
  10500078
  10500079
  10500080
  10500081
  10500082
  10500083
  10500084
  10500085
  10500086
  10500087
  10500088
  10500090
  10500091
  10500092
  10500093
  10500095
  10508085
  10508088
  10508089
  10508090
  10508091
  10508095
  10508102
  10508106
  10187362
  10187364
  10187366
  10500016
  10500017
  10500018
  10500019
  10500020
  10500021
  10500022
  10500023
  10500024
  10500025
  10500026
  10500027
  10500028
  10500029
  10500030
  10500031
  10500032
  10500033
  10500034
  10500035
  10500036
  10500037
  10500038
  10500043
  10500044
  10500045
  10500046
  10500047
  10500048
  10500049
  10500050
  10484354
  10499557
  10499558
  10499559
  10499560
  10499561
  10499562
  10499563
  10499564
  10499565
  10499566
  10499567
  10499568
  10499569
  10499570
  10499571
  10499572
  10499573
  10499574
  10499575
  10499576
  10499577
  10499578
  10499579
  10499580
  10499581
  10499582
  10499583
  10499584
  10499585
  10499586
  10499587
  10499588
  10499589
  10499590
  10499596
  10564505
  10564506
  10564507
  10564509
  10564510
  10564511
  10564512
  10572815
  10572816
  10575894
  10575895
  10007507
  10566366
  10575654
  10575669
  10564185
  10564513
  10564514
  10564515
  10564516
  10564517
  10564518
  10564519
  10564520
  10564521
  10564522
  10564523
  10564524
  10564525
  10564526
  10564571
  10564572
  10564573
  10564574
  10564575

938 rows selected.
```

**Comment by AJLinn** [comment]
What do I need to do to remove the irrelevant media files associated with my records then?
For example: http://arctos.database.museum/guid/UAM:EH:UA2014-009-0004AB
This is a camera manufactured in Ann Arbor, Michigan but used all over Alaska by the collector. There are two historical photographs (http://arctos.database.museum/media/10497842 and http://arctos.database.museum/media/10207161) associated with some general Alaska collecting event (http://arctos.database.museum/showLocality.cfm?action=srch&collecting_event_id=10266274) that has nothing to do with my object. 

What do I do to remove this kind of mis-attribution? @dustymc are you saying there are 938 other media files that are out there and potentially attached to object records that have nothing to do with the images?

Whatever mechanism is creating this mis-attribution we need to fix...

**Comment by dustymc** [comment]
Those photos DO have something to do with your camera - they're recorded as having an Event in the same place. The place is pretty big in this case, but that can probably be improved from Annie's (and Applegate's?) field notes.

There are ~700K other media objects "attached" via shared nodes - the 938 just happen to be attached to nodes which cannot include temporal data. I think the ability to associate objects by context rather than only including data from explicitly-asserted links is hugely powerful, even if it does start to get a little weird as we lose precision. (And that's exactly where this came from - various users want to see photos from Events which occurred at the same place 5 minutes ago, yesterday, or last year with the current specimen.)

I'll update the media include titles for next release - currently I've got...

Old:Media linked to a Collecting Event which shares the specimen's Locality.
New:Media from the same Place as this Specimen.

Old:Media linked to a specimen's Collecting Event.
New:Media from the same Place and Time as this Specimen.

The only mechanism at work here is the precision of the spatial data - in this case it's a string which has been described spatially as...

<img width="593" alt="screen shot 2018-04-13 at 8 39 14 am" src="https://user-images.githubusercontent.com/5720791/38744473-bc04962a-3ef6-11e8-9c2b-f53f96aa4932.png">

... that.

**Comment by AJLinn** [comment]
Thanks Dusty - I think that will be an improvement.
I agree there is some degree of value to have media associated with locations that are the same as an object/specimen. But I don't agree that it should appear to be linked in some direct way to the object/specimen record (just because those people were working in Alaska during the same time as the person who used the camera in our collection we can't assume there to be any direct connection between them). 

I wish there were a way to have those non-specific media appear to be more like when you're searching in iTunes or on Amazon where they give you "related to your search" options. Then the user could click on those if they want to go down that particular rabbit hole... which they might find interesting. But that's their choice rather than presenting the media as somehow directly tied to the search they just executed.

**Comment by dustymc** [comment]
Yes, agreed that some visual indication of "relatedness" would be useful - I'll see what I can figure out, ideas greatly appreciated. (Then we can discuss what "related" means! These are about as structurally close as eg, Accn Media, but I doubt ya'll see them the same way - unless you're recording Localities to meter-precision and Events to minute-precision, in which case you probably see "related place/time" Media as more relevant than "related transaction" Media....)

I would like to see "place" and "time" user-defined and data-driven (but I don't think we have the tools to pull that off yet). "Show me Media within {meters} and {hours} of this." The current model relies on keys - two specimens from THERE, THEN won't intersect if one of them has something weird in some locality or event remarks field, for example.

**Comment by sharpphyl** [comment]
Are we really closing this? We (and other collections) still have 76 photos
attached to all specimens with no higher geography (locality 10000000) that
are totally unrelated to the specimens. ​

**Comment by dustymc** [comment]
PLEASE reopen anything that's not sufficiently resolved. (I just did.) I'm just trying to categorize Issues without Milestones, definitely not trying to ignore any remaining problems.

**Comment by sharpphyl** [comment]
I asked to reopen this because there are still 76 photos attached to locality 10000000 (no higher geography; no specific locality) which is used by >23,000 records.  These images have nothing to do with our records and significantly slow down Arctos as they must load with every record associated with this locality.  Is the solution to this issue somewhere in the above thread?  

The same is true of locality 10000031 - California; no specific locality. There are 90 images attached to his locality that have nothing to do with our collection. 

I like being able to attach images to localities, but they should relate to the collecting event and/or the specimens.

**Comment by campmlc** [comment]
What about forcing the linkage here to collecting events instead of
locality?

**Comment by dustymc** [comment]
> forcing the linkage here to collecting events 

That would be the alternative if we drop the "... locality" options from http://arctos.database.museum/info/ctDocumentation.cfm?table=CTMEDIA_RELATIONSHIP.

**Comment by campmlc** [comment]
I support dropping the locality option from media and replacing it with
collecting event. Even in the situation of an unknown date, each collection
can assign a separate collecting event to, for example, "California,
1800-01-01-2018-12-31" to load media specific to that collection and
accession. It sounds like that might fix this problem?

On the same subject, I would like to have the option of "documents project"
for media.

**Comment by dustymc** [comment]
>1800-01-01

Google says the first photograph was produced in 1814 - at least some of these probably weren't created before that, and they definitely weren't created tomorrow. They DO have a time component, even if not a very precise one. (And FWIW I'd use "1800-2018" - it's exactly the same thing as what you suggested, but I think it helps users recognize that there is uncertainty involved.)

> documents project

associated with project exists.

>fix this problem

It'll fix the parts I see as a problem, anyway. "This photo is from the same place as this specimen" is important functionality that was introduced by user request (to see habitat shots through and across years - things that probably effect what critters are there and such). That gets weird when media are associated with very large places (like planets and big states). There's really nothing I can do about that, other than pleading for better data, or not linking to data which doesn't seem to add anything of value.

**Comment by campmlc** [comment]
So what is our solution? Do we need to bring this up in the next AWG
meeting, or do we have a consensus here?

**Comment by dustymc** [comment]
I don't want to do anything drastic without talking to the folks who own the affected media - I think it's all MVZ.

**Comment by Jegelewicz** [comment]
I also support dropping the locality option from media and replacing it with collecting event.

**Comment by sharpphyl** [comment]
re: No Higher Geography, no specific locality 10000000.

I guess it's getting a bit better.  There are now 67 images (down from 74 in December) attached to all Arctos 22,980 records with locality 10000000 which includes 2,697 of our records.  They take unnecessary time to load and have nothing to do with our specimen records.  

I've cloned a new locality 10727701 with the same data and the Remark "do not attach media to this locality".  I'm slowly moving our records to this locality.  Is that the only and best solution?  Seems like someone could get those 67 images where they belong - with a collecting event or some specimens.  

Can we also not allow media to be attached to Locality 10000000?  

As for #1608, referenced above, I can't get my one media attached to a locality to move to the collecting event.  Instructions?
