### ISSUE TITLE
specimen images uploaded report

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#1407]
Is there a way for me to find all of the specimen images that were uploaded to my collection during the date range 2016-07-01 thru 2017-06-30? It seems like something that should be recorded in the metadata of a media file? I apparently don't regularly check the "date made" label when uploading media and so Arctos thinks I only uploaded 12 images between those dates... Just trying to do some annual report stats.

**Comment by dustymc** [comment]
No, I don't have those data. Media are shared, not necessarily uploaded, etc.

At least for JPGs I can check EXIF data. Close enough?

If that does sound useful and there's data in EXIF, should I create a made date label from it?

**Comment by AJLinn** [comment]
I think it's valuable for us to know, or at least be able to retrieve, the date a media file came into the system, and hopefully there's a way Arctos could automatically generate that? 

From my googling, it seems like the EXIF data will give us the date the jpeg was taken, which will be a close approximate for many of my images, but we have thousands of images that were taken before we migrated into Arctos and those we could manually change the label "made date" to that earlier date.

I now have a new protocol to add to our media creation process. Hopefully it will help get at this data next year...

**Comment by dustymc** [comment]
I can auto-grab or force you to supply or whatever anything ya'll want, I just need details of the requirements. (And that needs to be aware that most Media get to Arctos via bulkloads, custom scripts, etc. - things not necessarily involving people or the times when a person did something.)

Should I get what I can from the EXIF, and if so what should I do with it?

**Comment by AJLinn** [comment]
> I can auto-grab or force you to supply or whatever anything ya'll want, I just need details of the requirements. (And that needs to be aware that most Media get to Arctos via bulkloads, custom scripts, etc. - things not necessarily involving people or the times when a person did something.)

I guess I'm not totally sure what I want, other than the date when the media was accessed by Arctos - would the date something was assigned a relationship to something else a logical date? It seems that's when it goes from just existing as a file to being something meaningful in relation to the objects, people, or transactions in the CMS.

> Should I get what I can from the EXIF, and if so what should I do with it?

What format will you be extracting in? Can it get dumped into a csv file that I can sort and sum? If so, that would be ideal.

Thank you!

**Comment by dustymc** [comment]
>assigned a relationship

I could add dates to media_relations, but I can't guarantee they won't be oops-ied and re-created or etc.

EXIF date attached.

[temp_uam_eh_img.csv.zip](https://github.com/ArctosDB/arctos/files/1640072/temp_uam_eh_img.csv.zip)
