### ISSUE TITLE
disposition not up-to-date in partdetail

### ISSUE THREAD

**Issue by ekrimmel** [ArctosDB/arctos#1414]
The disposition in **partdetail** is not up-to-date. See [these specimens](http://arctos.database.museum/SpecimenResults.cfm?catnum=E2017D%25) for example. They are "in collection" on the catalog record pages but the disposition that shows up in the partdetail when I find them in search results still says "on loan." I removed them and updated the disposition months ago.

**Comment by dustymc** [comment]
I'm not sure what happened. I rebuilt some triggers and force-updated the CHAS:Teach collection's cache.
