### ISSUE TITLE
Add Media to Agent

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#1417]
Would it be possible to add a button to "Add Media" to the Edit Agent page? The UAMEH workflow includes adding media files to agent records via "Shows Agent" relationship and it would be great to be able to both see those media (thumbnails) as well as add them directly from the edit agent page. It would save a lot of time to be able to have a similar process as in some of the other pages (e.g., specimen detail, loan, accession, etc.).

**Comment by dustymc** [comment]
done for next release
