### ISSUE TITLE
Allow for more characters in Accession Remarks

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#1418]
I'm adding content from my accession proposal forms to my accession records in the remarks field and I just got an error "string literal too long". Can we expand the number of characters/words allowed in the Accession Remarks field? Sometimes these justification rationales can be quite long (the one I'm adding is 3915 (with spaces) and I already had 1177 characters in that field to start.

http://arctos.database.museum/editAccn.cfm?action=edit&transaction_id=21115021

**Comment by dustymc** [comment]
We can, but it would take us into a different datatype which is difficult to sort and query, unlikely to play nicely with reports, etc. I suspect it's worth figuring out how to stay below 4000 characters, but I'm happy to do whatever ya'll want.

If you really have >4K chars worth of accn remarks, you could attach Media to the accn. (And attached text Media is roughly the same "datatype" as a CLOB, the internal "more than 4K characters" option.)

Much of what's in that accn now does not look to me like it belongs in accn remarks. ~2/3s of the text describes an agent, for example. You're not accessioning the agent, and it seems fairly likely that this won't be the only time he's encountered. If those data were in the agent record (and if the mentioned agent has a role in the accession), they'd be just as relevant to this accn, and infinitely more useful to anything else that agent might eventually be blamed for.

"Accession committee approved" might be another transaction role/agent.

"member Ross..." could be a member of a group-agent, or (probably better) directly tied to the accn (eg, as one of many "Accession committee approved...").

"Two additional items..." looks like nature of material.

Etc. I'm not saying you SHOULD do any of that (or that 4K will be enough if you do anyway!), but it looks to me like these data could be partitioned better, which would help with length and make them more generally useful.

**Comment by AJLinn** [comment]
What I'm doing is trying to get an official piece of the accessioning process (our Preliminary Justification Form, example from accession attached here) integrated officially into the record for this collection (and all collections that are accessioned). I guess if it is preferable I'll have to just attach the PDF of the justification to the accession. 

Comments from acquisitions committee members regarding proposals is an important part of the accession record, so it gets integrated as-written/discussed into the accession remarks. I don't know what other collections put in their remarks fields, but that's how we do it in the cultural collections.

> Much of what's in that accn now does not look to me like it belongs in accn remarks. ~2/3s of the text describes an agent, for example. You're not accessioning the agent, and it seems fairly likely that this won't be the only time he's encountered. If those data were in the agent record (and if the mentioned agent has a role in the accession), they'd be just as relevant to this accn, and infinitely more useful to anything else that agent might eventually be blamed for.

I'm still trying to figure out the various ways I want to propose adjusting/messing with the agent page (both the Edit and summary page that is publicly visible). Yes, you're right that moving agent-related info from these justifications is typically something that we do. However, it starts at our acquisition committee meetings/paperwork and then I move it when I have time.
[T2017.006_ONeillPJF.pdf](https://github.com/ArctosDB/arctos/files/1675175/T2017.006_ONeillPJF.pdf)

So... we'll close this and I'll manage the same process by using the media tool.
