### ISSUE TITLE
reporting

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1419]
from @DerekSikes 

>Maybe when an admin logs in there could be a summary of that admin's data and things waiting to attended to like a count of unchecked localities, overdue loans, etc.? Ideally the admin would be able select from a list of items to be presented so they're not getting bothered by things they don't care about? Seems like a slippery slope of nearly infinite things though...

I like the idea of a "report central" and something more fine-grained than the current collection contact based approach. (E.g., a student may deal with {something} and need only reports involving that.)

There are a bunch of existing reports which do not send email, and perhaps some (all??) users would like an occasional email of specimens which have been used and not cited (or anything else that currently lives under the Reports tab).

I can also see value in having a centralized way to access current email reminders. There's an email for overdue loans and another for unreciprocated relationships, it's possible to find both of those things from Arctos, but there's no one "show me active/current problems" place.

A framework which supports "send email when {user-supplied SQL query returns something}" would be useful. (This started from a probably-collection-specific container issue.)

"nearly infinite" doesn't scare me as long as it's by subscription, but depending on implementation might require more resources (eg, a server dedicated to scheduled tasks - which would benefit us now).

Flagging "wish list" - this might require funding (eg, meetings, development, hardware).

**Comment by Jegelewicz** [comment]
> I like the idea of a "report central" and something more fine-grained than the current collection contact based approach

Agree. It would be fabulous if the first time I log in each month (that is 12 times a year) I would be greeted with a page that offered me links to:

Overdue loans
Unresolved annotations
Unreciprocated relationships
Barcodes without attached parts
Barcodes in "The Universe" (that aren't just container labels)
Scientific Names used in my collection(s) with no associated classification
Locality description/coordinate mismatches
Parts with disposition "being processed" for longer than a year
Media I uploaded which are not associated with anything
other?....

The page with links could be available in Reports/Services, but the monthly reminder might help get more things resolved. Or it might not - see my [SPNHC/TDWG presentation on iDigBio data quality flags](https://drive.google.com/open?id=1JDcoQVNe8eVjtgSdXgvzsPa26du_cOnw).  We really don't have time for flags/annotations. We need more staff.

**Comment by dustymc** [comment]
I'll see how far I can get with aggressive caching and simple popup reminders.

**Comment by dustymc** [comment]
>Unreciprocated relationships

Is this necessary? Those send nightly emails which are hard to avoid and contain everything (and it's expensive)

>Barcodes without attached parts

I think this would just be overwhelming - there are hundreds of thousands, and having thousands in any collection (that uses barcodes) at any time is probably "doing it right." What don't I understand?

>Barcodes in "The Universe" (that aren't just container labels)

same as above??

**Comment by dustymc** [comment]
> Locality description/coordinate mismatches

What is meant by this? 

<img width="323" alt="screen shot 2019-01-30 at 2 01 15 pm" src="https://user-images.githubusercontent.com/5720791/52015749-89149580-2497-11e9-8ebf-34cbd7e68222.png">

has the difference between assigned and service coordinates, but the service isn't very good. Anything more robust is probably going to require GIS capability.

**Comment by campmlc** [comment]
I use the unreciprocated relationships notification, but once a month would
be fine.

Barcodes without parts could be a report that I can access - I don't need
an email.

Barcodes in the Universe for my collection (that aren't labels). Same thing
- useful, but at most maybe an annual or semiannual report link to click on?

**Comment by dustymc** [comment]
To clarify: I'm working on something like

>It would be fabulous if the first time I log in each month (that is 12 times a year) I would be greeted with a page that offered me links to:

which seems a useful approach for things that area easy to miss in the normal notifications, or things that are in reports which require user action to view, or maybe things that should be in reports but aren't yet. The relationship email report is cumulative - anything you miss will be in the next one. The loan report goes out something like once a year after the email flurry around the due date - more-frequent lightweight notifications ("you have 59 overdue loans - click for more") might be useful for that. The loan report doesn't go out at all if there's no due date - looking for different ways to view data often uncovers stuff like that, and minimally should make our documentation better.

I'm hoping to build a framework and maybe provide some useful data, and from that we can figure out what individual user customization and user-generated reports and such would take. 

This isn't going to directly change anything existing - file an Issue to do that, or for new reports/forms.

**Comment by Jegelewicz** [comment]
Dusty,

I think we are all envisioning a "dashboard" even though no one has said that term. I am thinking about it because of recent conversations with Deb Paul about collection metrics - a future issue on that, but I am overwhelmed right now.....

**Comment by dustymc** [comment]
>dashboard

Consider that stolen - thanks!

>collection metrics

Definitely all linked - everything I'm looking at messes with those.

**Comment by Jegelewicz** [comment]
Hey @dustymc I was doing other stuff when I stumbled upon this: http://arctos.database.museum/Reports/georef.cfm

This would be awesome on the "dashboard", but I only want to see my collection (or a collection of my choice if I manage many).

**Comment by dustymc** [comment]
There is a basic framework in place for this now, mostly dealing with finding and caching problematic data.

We should be able to add email alerts or personalization or whatever later, if that proves useful.

I'll continue to add reports - please continue to request them here.

I think this could be more effective as small tasks presented often rather than (or perhaps in addition to) one giant list of tasks presented periodically, so I've added a couple things to the Random widget for manage_collection users.

<img width="399" alt="screen shot 2019-02-05 at 10 34 35 am" src="https://user-images.githubusercontent.com/5720791/52295852-aaf79780-2931-11e9-89e2-b75db8cf85b7.png">

That should perhaps be in the header (maybe the announcement area) or something - it's modular so shouldn't be much problem to sprinkle it around.

You can access the giant list here:

<img width="372" alt="screen shot 2019-02-05 at 10 27 41 am" src="https://user-images.githubusercontent.com/5720791/52295879-bfd42b00-2931-11e9-86e2-d05468af0c9a.png">

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/1702

**Comment by Jegelewicz** [comment]
@dustymc this is a start, but a real dashboard looks like this:

![image](https://user-images.githubusercontent.com/5725767/54462703-4ac8f200-4736-11e9-93a0-a82f9969a4fb.png)

Click the button, get the report.

Could we make it pretty? Can I help?

**Comment by dustymc** [comment]
see also https://github.com/ArctosDB/SPNHC-2019/issues/4

I can rename the form-probably-soon-to-be-formerly-known-as-dashboard.

<img width="322" alt="Screen Shot 2019-03-22 at 12 41 24 PM" src="https://user-images.githubusercontent.com/5720791/54849023-2c1bab80-4ca0-11e9-9df0-8ef215326ee2.png">

seems to be more what you're looking for.

**Comment by Jegelewicz** [comment]
Well, really we have two dashboards. The stats, which are great for showing how awesome we are and the low quality data which shows that we still have work to do (job security?) I like the idea of having them both and making them both pretty!

**Comment by dustymc** [comment]
Stats are being gathered, there's a UI, closing.
