### ISSUE TITLE
lost Arctos record?

### ISSUE THREAD

**Issue by mgoliver** [ArctosDB/arctos#1420]
The UAM:Arc record UA77-501-0167 appears in the specimens results for the accession UA77-501 but the link brings up a 404: not found page. If I search for it by catalog number then nothing comes up in the specimens results. I'm assuming the url got changed and a redirect wasn't made but don't know how to go about finding the record now. Any tips?

![screen shot 2018-01-30 at 9 02 20 am](https://user-images.githubusercontent.com/28404497/35583157-72305508-059d-11e8-9e49-4c5f12849f8b.png)

**Comment by dustymc** [comment]
http://arctos.database.museum/guid/UAM:Arc:UA77-501-0167%20

The catnum was entered as UA77-501-0167{space}. The space is just another character as far as Oracle is concerned, but it seems that browsers ignore trailing spaces.

**Comment by mgoliver** [comment]
Thanks very much, Dusty! There's a redirect for it now.

**Comment by dustymc** [comment]
>redirect

If the space isn't intentional, you can edit catnum - I think it's the otherIDs tab.

**Comment by mgoliver** [comment]
The space was certainly not intentional but when I checked under otherIDs it looked like someone had already gotten rid of it. However, when I tried searching for this record again by catalog number (both with a trailing space and without it) Arctos still didn't come up with anything in the results. I'm not sure why that is. You can still find the record by looking up the accession first and the redirect works properly.

**Comment by dustymc** [comment]
Hmm, I don't think the form likes trailing spaces either...

I updated it and a few others.

```
UAM@ARCTOS> select guid from flat where guid != trim(guid);

GUID
------------------------------------------------------------------------------------------------------------------------
UAM:Arc:UA77-501-0167
UAM:Arc:UA80-140-D-30
UAM:Arc:UA80-140-1012
UAM:Arc:UA80-140-1052
UAM:Arc:UA80-140-2119
DMNS:Inv:22933
UAM:Arc:UA2015-068-0011
```
Unless someone stops me very soon, I'm going to disallow spaces in catalog number.

**Comment by dustymc** [comment]
Nobody stopped me; catalog number now cannot contain spaces.

**Comment by AJLinn** [comment]
Agreed, there should not be spaces in catalog numbers. And having just experienced a student worker who put a space after every phrase she typed, I think this is a great modification. Thank you!
