### ISSUE TITLE
media thumbnails not displaying

### ISSUE THREAD

**Issue by amgunderson** [ArctosDB/arctos#1422]
See http://arctos.database.museum/guid/UAMObs:Mamm:207. The thumbnail file exists and can be seen when clicked on from the edit media page but does not display on the specimen record or the media details page.

**Comment by amgunderson** [comment]
The thumbnail was 70kb, I uploaded a 15kb file. Will that solve the problem?

**Comment by dustymc** [comment]
Yep!

<img width="240" alt="screen shot 2018-02-02 at 11 00 23 am" src="https://user-images.githubusercontent.com/5720791/35750005-59e9c58e-0808-11e8-96a1-ea3c750f8945.png">


The current max thumb size is 64K (getMediaPreview at https://github.com/ArctosDB/arctos/blob/master/component/functions.cfc).
