### ISSUE TITLE
Clarification on how to handle new hemihomonyms

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#1423]
It looks like #891 where this was partially discussed has been closed so I'll open a separate issue.  

I am cleaning up the molluscan taxonomy with the Hierarchical Classifications tool.  I need three hemihomonyms added and this may be the place to clarify the preferred procedure.  (The tool is great but with thousands of corrections to be made, the clean-up is a lifetime project so there will probably be more of these.)

Euthyneura (see WoRMS http://www.marinespecies.org/aphia.php?p=taxdetails&id=1057247) is needed in Gastropoda as an Infraclass.  It is already in Arctos (http://arctos.database.museum/name/Euthyneura) as a genus in Arthropoda.  There is no author for the molluscan version.  Should I add (Mollusca) after Euthyneura or should I request a change in the existing version to add the author - _Euthyneura_ Spengel, 1881?

Cepolidae is needed as a family within Helicoidea (Superfamily).  See WoRMS http://www.marinespecies.org/aphia.php?p=taxdetails&id=994705.  It is already in Arctos - http://arctos.database.museum/name/Cepolidae - in Actinopterygii.  Do I add the author and enter it as Cepolidae Ihering, 1909?  I'm fine with that if the public can find our specimens.

Within Mollusca, we need to add Helicina Rafinesque, 1815 (suborder) WoRMS: http://www.marinespecies.org/aphia.php?p=taxdetails&id=994701 and already have Helicina  (genus) WoRMS: http://www.marinespecies.org/aphia.php?p=taxdetails&id=737604.  From the above discussion, it seems I would add Helicina Rafinesque, 1815 as the suborder to distinguish it from the genus.  This would also not impact CHAS and UTEP specimens already identified with the Helicina genus.

So in general, we would add the author to distinguish hemihomonyms from each other.  If there are no authors, we would indicate some higher level taxon (Phylum?).  And in the record somewhere indicate that it is a hemihomonym?  Or is there a better approach?

**Comment by dustymc** [comment]
Arctos works just like the Codes in this respect. Names in different buckets (hemihomonyms; different Codes or different Classifications) aren't really a problem, except when users make them that way (generally by ignoring scale). Names in the same bucket (homonyms: same Code or Classification) are a giant pain and can't really be unambiguous, so we just ignore the inconvenient data.

http://arctos.database.museum/name/Gravenhorstia is a hemihomonym. ICZN and ICBN can both agree to accept it. When a collection that prefers the Arctos Plants classification uses it (eg, in the bulkloader), they unambiguously mean http://arctos.database.museum/name/Gravenhorstia#ArctosPlants (eg Magnoliophyta), and collections which prefer the "Arctos" classification unambiguously mean http://arctos.database.museum/name/Gravenhorstia#Arctos (eg, Arthropoda). Not much of a problem for anyone (until "checklist of plants and bugs" is published...).

You have homonyms. These are a problem for everyone, and there can be no very good solution as long as we're using string-based tools (eg, identifications in specimen bulkloader). Euthyneura is a Dipteran ("controlled" by ICZN) and a mollusc (also "controlled" by ICZN). ICZN will eventually officially notice, declare a winner, and try to pretend the other one never existed. (Stupid literature and type specimen labels anyway...) Arctos just won't do anything that involves picking ONE classification when there are multiple possibilities. 

http://arctos.database.museum/name/Gravenhorstia#GBIFBackboneTaxonomy is an example of this situation. From that name+classification, there's no way to know if I'm talking about a bee, a fly, or a plant. It's unambiguously ambiguous (which may be the least-evil thing we can do!).

Here's at least some of what'll happen if you create a second Arctos classification for http://arctos.database.museum/name/Euthyneura:

1) It will be somewhat difficult to preserve with the hierarchical tool. This simply cannot exist in a hierarchy, I've tried to add some warnings, but it's probably easy to delete 2 classifications and re-add one (which will add a great deal of completely misplaced confidence to specimen IDs).

2) The "any ..." search options will use everything; those things do not prefer classifications. People will generally find specimens.

3) The "specimen taxonomy" in FLAT ("family" on most label reports, the "family" specimen search option, etc.) will be empty. I can't possibly know what you mean by "Euthyneura" so I'll just do nothing. (Users can't possibly know what you mean either, so hopefully there's something in the specimen data which clarifies and will still make some sense in 50 years).

Unlike the Codes, Arctos lets you define your own bucket, so you could start a new classification in which Euthyneura is unambiguous. These can only work at the collection level - there's no way to use the Arctos "bucket" with some names and the "avoiding homonyms" bucket for others. Certainly not a path I'd ever recommend, but it's always a possibility if you're willing to forego the sharing of data with collections using the "Arctos" classification.

Metadata-bearing terms (genus=="Euthyneura Spengel, 1881") are very likely to cause a bigger mess, and I suspect that sort of unpredictable data will find a way to avoid most searches. I would strongly recommend avoiding this, but there are no real rules for classification data so I can't/won't try to enforce anything.

Sorry, I don't really have a solution. The system itself is completely broken and there's not really any way to avoid the fallout from that. I see little evidence that author strings add useful clarity. Not all homonyms are separated enough that "higher taxonomy" is useful - http://arctos.database.museum/name/Gravenhorstia#GBIFBackboneTaxonomy (Arthropoda) is still ambiguous, and if we didn't have data for both arthropods (and who's to say there aren't 30 more somewhere out there??) this leads to misplaced confidence. 

If I had to use this, I'd probably start with...

1) Create a new classification just to maintain homonyms. I wouldn't plan on USING this, but I would want a safe place to stash the data I've dug up with the anticipation that someone is eventually going to oopsie Euthyneura-the-gastropod from the Arctos classification.
2) ADD Euthyneura-the-gastropod to the Arctos classification, being careful to not delete Euthyneura-the-fly data. The normal classification bulkloader can't work for this: 

> This form REPLACES classifications; ALL classifications at the intersection of taxon_name.scientific_name and the source from these data will be DELETED and replaced with these data. 

3) Find my ambiguous specimens, and stuff everything I know into ID Remarks.

That's a lot of work for low-quality data, but I don't really see a better approach.

Any solution/work-around/advice/procedure/etc. that surfaces here should be added to http://handbook.arctosdb.org/documentation/taxonomy.html.

**Comment by sharpphyl** [comment]
So here's an idea, although we know we're just kicking the can down the road.  Let's not worry about Euthyneura and Helicina because they are higher order taxa and I can simply leave them off. 

But we have 50 specimens of the molluscan family Cepolidae so we need a solution to that one.  A quick search shows that the only specimens in Arctos using Cepolidae are from CHAS:Inv which are mollusca (8 lots).  However, these lots are linked to the fish Cepolidae family in Arctos.  Erica, are you aware of this? 

There are no fish lots currently using Cepolidae in Arctos.  Would you consider eliminating the children of Cepolidae and allowing me to change it to the Molluscan version?  Of course, if a new fish collection comes in with Cepolidae, they will need a solution to this problem.  

If that's unacceptable, the only other solution we like is your (2) add Cepolidae (Mollusca) as a new taxon.  We understand that isn't ideal but it would work.  To add another classification system (1) that we don't want to use doesn't work because we really need to use it now.  We don't like (3) because it doesn't help people who are search for our Cepolidae species and it misrepresents our collection.

**Comment by dustymc** [comment]
>kicking the can down the road.

That's been "working" for a couple centuries....

>CHAS:Inv

@ekrimmel @droberts49  - http://arctos.database.museum/SpecimenResults.cfm?family=Cepolidae

>Would you consider

That's fine with me/I have no real stake in the classification data. I can just tell you what'll happen if various things come into play.

>Cepolidae (Mollusca) as a new taxon

If you mean as something in a classification somewhere, see above. If you mean as a NAME, I don't think that's a defensible approach. If you're referring to "ADD Euthyneura-the-gastropod to the Arctos classification" I meant add an entire new second "Arctos" classification to eg http://arctos.database.museum/name/Cepolidae.

>search

Anyone using the "Family" etc. search terms is finding random stuff anyway - there are a lot of valid-according-to-someone alternatives out there for most everything, and who knows how often someone searches for "This" when we use "That" or expect "This" in subfamily but we have it in family or etc. The "any ..." search option bypasses all that - http://arctos.database.museum/name/Cepolidae#GBIFBackboneTaxonomy (2nd classification - and a few more) links Cepolidae (and Stylommatophora , etc.) to snails. A second Arctos classification would do that same, and allow you to eg include stuff GBIF has excluded.

>misrepresents our collection

If we must have multiple "active" (stuff that finds it's way to FLAT) classifications for homonyms, the only viable approach is to get a new bucket - to split the "Arctos" classification. There are big costs to doing that, so I hope we can just find a way to avoid the situation.

**Comment by sharpphyl** [comment]
- Cepolidae (Mollusca) as a new taxon

- If you mean as something in a classification somewhere, see above. If you mean as a NAME, I don't think that's a defensible approach. If you're referring to "ADD Euthyneura-the-gastropod to the Arctos classification" **I meant add an entire new second "Arctos" classification to eg http://arctos.database.museum/name/Cepolidae.**

Dusty, if the above suggestion means that we can have two Arctos classifications for Cepolidae, that's perfect.  I assume we can chose which one we want somehow for the genera in Cepolidae  Arctos won't let me create a second classification so can you do it for us and then I can edit it further?

I also would expect that a search for Cepolidae would list all species in both families which is ok by us.

**Comment by dustymc** [comment]
<blockquote>
Here's at least some of what'll happen if you create a second Arctos classification for http://arctos.database.museum/name/Euthyneura:

  1.  It will be somewhat difficult to preserve with the hierarchical tool. This simply cannot exist in a hierarchy, I've tried to add some warnings, but it's probably easy to delete 2 classifications and re-add one (which will add a great deal of completely misplaced confidence to specimen IDs).

 2.   The "any ..." search options will use everything; those things do not prefer classifications. People will generally find specimens.

3.    The "specimen taxonomy" in FLAT ("family" on most label reports, the "family" specimen search option, etc.) will be empty. I can't possibly know what you mean by "Euthyneura" so I'll just do nothing. (Users can't possibly know what you mean either, so hopefully there's something in the specimen data which clarifies and will still make some sense in 50 years).
</blockquote>

* Create Classification
* Clone Classification
* Clone classification into existing name 

will all create as many classifications as you want.

**Comment by sharpphyl** [comment]
Thanks, Dusty.  Very helpful.  Cepolidae now has two classifications.  And
I understand that I'll have to manually change all the species within
Cepolidae to have the accurate classification hierarchy.  I'll leave
Cepolidae out of the Hierarchy tool.  I've experienced the problem in 3.
when there are two classifications in a taxon - in fact that's a helpful
way to find taxon with (erroneous) multiple classifications.

Erica probably needs to look at her entries as they are using the fish
hierarchy since that was all that was available at the time.

**Comment by dustymc** [comment]
Is this resolved? Tentatively closing.....

**Comment by sharpphyl** [comment]
No problem with closing.  Thanks.

On Mar 13, 2018, at 11:35 AM, dustymc <notifications@github.com> wrote:

Is this resolved? Tentatively closing.....
