### ISSUE TITLE
part bulkloader: save errors [was:Error when bulkloading parts]

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1425]
When attempting to bulkload parts, I am getting this error:

An error occurred while processing this page!
Error Executing Database Query.
[Macromedia][Oracle JDBC Driver][Oracle]ORA-01427: single-row subquery returns more than one row

This message has been logged. Please contact us with any information that might help us to resolve this problem.

I haven't run onto this one before. My data is still in the bulkloader.

**Comment by dustymc** [comment]
That's always "SOMETHING doesn't resolve to a single record, which is needed to proceed."

In this case, a bunch of the NKs don't resolve to a single specimen.

```

declare nci number;
begin
  for r in (select * from cf_temp_parts where username='JEGELEWICZ') loop
     select count(distinct(cataloged_item.collection_object_id)) into nci from 
    cataloged_item,
        collection,
        coll_obj_other_id_num
        WHERE
        cataloged_item.collection_id = collection.collection_id and
        cataloged_item.collection_object_id = coll_obj_other_id_num.collection_object_id and
        collection.guid_prefix = r.guid_prefix and
        coll_obj_other_id_num.other_id_type = r.other_id_type and
        coll_obj_other_id_num.display_value = r.other_id_number
    ;
    if nci!=1 then
      dbms_output.put_line(r.other_id_type || ': ' || r.other_id_number);
      dbms_output.put_line(nci || ' specimens found');
    end if;
  end loop;
end ;
 21  /
NK: 19291
0 specimens found
NK: 19291
0 specimens found
NK: 19291
0 specimens found
NK: 19294
0 specimens found
NK: 19294
0 specimens found
NK: 19301
0 specimens found
NK: 19301
0 specimens found
NK: 19301
0 specimens found
NK: 19304
0 specimens found
NK: 19304
0 specimens found
NK: 19304
0 specimens found
NK: 19316
2 specimens found
```

**Comment by campmlc** [comment]
Dusty, can we add a download with error message tool to the parts
bulkloader so we can troubleshoot this on our own? This is going to be a
recurring problem for a load of about 60,000 parts.

**Comment by dustymc** [comment]
> add a download

Sure

**Comment by dustymc** [comment]
in next release
