### ISSUE TITLE
Arctos acting strange on Firefox

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1426]
![home](https://user-images.githubusercontent.com/5725767/35939909-c38d00d6-0c0a-11e8-8508-8a332fcdf519.jpg)

**Comment by AJLinn** [comment]
Yeah, I'm running it on Chrome an am getting those little "open in new window" arrows all over the top section also. They seem to be connected to a link to idigbio

**Comment by Jegelewicz** [comment]
And when I try to log in I am redirected to https://www.idigbio.org/content/arctos-webinar-series-data-cleaning-tools-use-prior-migrating-arctos

**Comment by dustymc** [comment]
I pulled this...

```
Tuesday, February 13th webinar on data cleaning tools for use prior to migrating data into Arctos <a target="_blank" class="external" href="https://www.idigbio.org/content/arctos-webinar-series-data-cleaning-tools-use-prior-migrating-arctos"</a>. 
```

out of the announcement_text block.

It should be something like

```
Tuesday, February 13th webinar on data cleaning tools for use prior to migrating data into Arctos <a target="_blank" class="external" href="https://www.idigbio.org/content/arctos-webinar-series-data-cleaning-tools-use-prior-migrating-arctos">link text goes here</a>. 
```

# PLEASE TEST ON THE TEST INSTANCE BEFORE CHANGING IN PRODUCTION!!

**Comment by Jegelewicz** [comment]
Thanks!

**Comment by KyndallH** [comment]
Dusty: There was a webinar announcement already in the text box, I simply changed the data but left all the code stuff the exact same. Then updated the expiration date. After I entered it this morning, it looked fine on my computer. It also looked fine when I checked it a few hours later on a different computer.

**Comment by dustymc** [comment]
We should have a staff exorcist....

What was the link text supposed to be? And I think it's too long for the current structure, but that can probably be fixed by replacing https://www.idigbio.org/content/arctos-webinar-series-data-cleaning-tools-use-prior-migrating-arctos with a goo.gl or etc version

**Comment by campmlc** [comment]
Is there a way to have a plugin tool that allows us to hide the background
code and just add the text we want users to see? The many of us who aren't
programmers may not realize we've left out a critical part of the
punctuation. . . just sayin.

**Comment by dustymc** [comment]
>plugin

Certainly possible, but seems like overkill to me for something that's used by perhaps 2 or 3 people at most ~weekly.

**Comment by campmlc** [comment]
OK, I imagine we are trainable. But it is good to know that for critical
functions needed by many that we can develop alternatives to everyone
having to learn code.
