### ISSUE TITLE
other identifier issues

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#1427]
We've had a batch of other identifiers (DZTB: Denver Zoology Tissue Bird) that were duplicated during the bulkloading process (our fault). I was able to use the Bulkload Identifier tool to add the new (correct) number to the specimen I wanted - that tool is quite handy. However, I was hoping it would overwrite the old DZTB numbers but it just adds a second set of DZTB identifiers. Is there an available method to bulk-delete specific types of other identifiers from specific specimen records? I know we have numerous other situations where this would come in handy (e.g. changing from 'original identifier' to 'collector number').

**Comment by campmlc** [comment]
I second this request. Can we add a tool through Specimen Results: Manage:
Change Stuff?

**Comment by dustymc** [comment]
This comes up fairly often, yes we can do it, just need to work out some specifics.

>overwrite

That can't happen - eg, some specimens eventually get dozens of GenBank numbers.

>Specimen Results: Manage

I'm not sure how that would work??

I'm thinking an "un-bulkloader" - upload CSV with something to find the specimen + something to find a specific ID (eg, type+value).

**Comment by acdoll** [comment]
I figured overwriting was out. An "un-bulkloader" would be very useful to rip inaccurate info out of records.
