### ISSUE TITLE
Would like censu citation for change in determination for bulk change

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#1428]
We have the option for a sensu publication when changing one specimen at a time, but we don't have that option when changing a series of specimens from the interface for doing that. I'd like to link a new publication to some taxonomic changes I am making. I'd rather do all at once. Is this a general issue?
 Can that be added? Thanks. 
<img width="376" alt="screen shot 2018-02-07 at 3 21 49 pm" src="https://user-images.githubusercontent.com/5749672/35949650-78b269c6-0c27-11e8-9b91-8021ad3912f0.png">
<img width="459" alt="screen shot 2018-02-07 at 3 21 29 pm" src="https://user-images.githubusercontent.com/5749672/35949651-78cdb53c-0c27-11e8-822e-c3b8175b4f60.png">

**Comment by dustymc** [comment]
in next release
