### ISSUE TITLE
Error when adding barcode to parts

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1430]
I was adding a barcode to a heart, kidney (frozen) part for MSB:Mamm:63349, but when I selected save all changes the barcode was not added to the part and the error I received was:

> An error occurred while processing this page!
Error Executing Database Query.
[Macromedia][Oracle JDBC Driver][Oracle]ORA-20001: Invalid part name: karyotype (dry, slide) (Mamm) ORA-06512: at "UAM.TRG_CMPD_SPECIMENPART", line 37 ORA-04088: error during execution of trigger 'UAM.TRG_CMPD_SPECIMENPART' 

There is a karyotype (dry, slide) part associated with this record and this appears to be a valid part name in the code table search. Any idea what the problem is?

**Comment by dustymc** [comment]
There was a trailing space in the code table - should be cleaned up.
