### ISSUE TITLE
Taxonomy bug (?) when cloning after Refresh/Pull Global Names

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#1432]
In adding Massylaea (source: http://www.marinespecies.org/aphia.php?p=taxdetails&id=996439) to taxon tables, after refresh this appeared for Union 4
![union 4 massylaea](https://user-images.githubusercontent.com/15368365/36074994-0000d6d0-0f05-11e8-849e-9270e10a825d.png)
I selected this over the other two because it's faster to delete rows I don't usually include than to add rows I need.
This is what appeared in the next screen.  

![massylaea after cloning](https://user-images.githubusercontent.com/15368365/36075003-1fd117c2-0f05-11e8-9576-1f1497992e23.png)

So I still had to add a number of rows to complete the classification.  Is this an Arctos bug or a Global Names issue?  Is there a limit to the number of rows Arctos clones?  Typically, on these very extended sources, several levels are eliminated, but not this many.  

Note that WoRMS did not appear in the Global Names refresh, but that's probably because Massylaea was updated in 2017 and there seems to be a long lag between a WoRMS update and Global Names reflecting the update.  I'll ask WoRMS to clarify how frequently and how Global Names gets its updates from WoRMS.

**Comment by dustymc** [comment]
<img width="800" alt="screen shot 2018-02-11 at 8 15 46 am 1" src="https://user-images.githubusercontent.com/5720791/36075429-cbf8cda8-0f03-11e8-9c24-de13e56c1fd0.png">

<img width="142" alt="screen shot 2018-02-11 at 8 16 25 am" src="https://user-images.githubusercontent.com/5720791/36075442-e6966e72-0f03-11e8-8f57-8bf43dd9740b.png">

**Comment by sharpphyl** [comment]
Ah, so I shouldn't use any hierarchy that uses terms like "above family".
Unfortunately, the other sources for this taxon aren't any better.  Thanks
for clarifying.
