### ISSUE TITLE
Allow for search on more than one specimen attribute at a time

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1434]
To get parasite prevalence,  I need to search on all hosts with the following 2 attributes:
1) attribute 1: examined for endoparasites, value = yes
AND
2) attribute 2: endoparasites found, value = yes

Currently, I can only search on one of these at a time, meaning I have to download the results from attribute 1 and try to sort through them. 
Can we add attributes to a search?
![screenshot 47](https://user-images.githubusercontent.com/14808196/36082835-548d953e-0f6a-11e8-8077-750d35ae937b.png)

**Comment by dustymc** [comment]
You can get there from specimenresults:

<img width="652" alt="screen shot 2018-02-11 at 7 50 27 pm" src="https://user-images.githubusercontent.com/5720791/36083187-f066b77a-0f64-11e8-8c28-af3883f77212.png">

http://arctos.database.museum/SpecimenResults.cfm?examined_for_parasites=yes&endoparasites_detected=yes

Arctos can pretend any attribute is a variable, and can handle any number of them that way. I can do something different on specimensearch, but I have no idea how to present that - I can't add all 129 current attributes.

**Comment by campmlc** [comment]
Can we just have an optional "add another attribute and attribute value" to
the search page? I don't think we can explain to researchers how to use the
specimen results page query.

**Comment by AJLinn** [comment]
> Can we just have an optional "add another attribute and attribute value" to
the search page?

I second that - this has been on my wish list since we migrated over from 4D, in which we could do this type of search. We have many attributes that I often use as search criteria and it would really help narrow my searches if we could "add another attribute and attribute value" to the search page as an option so we could search several simultaneously.

**Comment by dustymc** [comment]
Initial search form

<img width="660" alt="screen shot 2018-02-12 at 1 36 40 pm" src="https://user-images.githubusercontent.com/5720791/36121062-f9789186-0ff9-11e8-8f87-fd921ec7c8cf.png">

add any number of attributes

<img width="661" alt="screen shot 2018-02-12 at 1 37 20 pm" src="https://user-images.githubusercontent.com/5720791/36121074-01f5a560-0ffa-11e8-8f02-466853ae7739.png">

documentation (what there is of it...) is pulled from code tables

<img width="564" alt="screen shot 2018-02-12 at 1 37 43 pm" src="https://user-images.githubusercontent.com/5720791/36121100-0e10b722-0ffa-11e8-8b8f-72ec907b3025.png">

Give it a spin at test.

**Comment by campmlc** [comment]
Yay! Thanks, Dusty!

**Comment by AJLinn** [comment]
One quick question: When I do this:

![ss_attributesmulti](https://user-images.githubusercontent.com/17605945/36751948-23ae561a-1bae-11e8-9f9d-64b41f495ffd.jpg)

Am I doing an "and" or an "or" search?
Do we have an option to select one or the other? Can someone educate me on how to do that if it's possible?

**Comment by dustymc** [comment]
That (and everything else) is an AND search.

I could potentially add some sort of "any attribute value" or similar??

**Comment by AJLinn** [comment]
I'm just wondering if it's possible to do an "or" type of search when we have multiple attributes. For example, I was just trying to find Haida baskets. So I've got my Identification box: basket (comma list-substring) and then I wanted to find in a single search effort any basket that had "Haida" listed as the culture of origin OR the culture of use.

So I wanted an AND between the ID and the attribute, but an OR between multiple attributes.
Is that possible?
Maybe your "any attribute value" would accomplish the same thing as it would look across all attributes for that same value, right?

**Comment by dustymc** [comment]
FYI comma list-substring requires more processing than you need - it lets "Phoca, Pusa" find "Phoca vitulina" and "Pusa hispida" and such.

<img width="590" alt="screen shot 2018-02-27 at 12 38 14 pm" src="https://user-images.githubusercontent.com/5720791/36753481-20e5584a-1bbb-11e8-942d-2fc4bf9a5786.png">

is "contains basket" ("Basket, straw" and, because of the leading %, "decorated knob for handle on basket").

I think variable operators would be extremely confusing, but maybe you have a way around that in mind. "Any attribute value" would ALMOST accomplish the same thing - it'll find 'completely irrelevant attribute=Haida' along with the two you want. (Which is always the expected behavior on imprecise searches.)

**Comment by campmlc** [comment]
One last thing - can we add attribute value? I need this for prevalence, e.g. the search would be:
"examined for endoparasites" value = "yes" AND "endoparasites detected" value = "yes

**Comment by dustymc** [comment]
<img width="482" alt="screen shot 2018-03-05 at 10 42 16 am" src="https://user-images.githubusercontent.com/5720791/36993160-ea075e6c-2061-11e8-98d1-191b1ee17531.png">

??

**Comment by campmlc** [comment]
I was thinking that we have a dropdown with the values to select instead of
a blank box that requires someone to know the code table?

**Comment by dustymc** [comment]
New Issue please - that's possible. 

Some concerns/comments:

1) Arctos will deal with things outside code tables (http://handbook.arctosdb.org/documentation/attributes.html#searching-with-attributes)

2) CT values are currently 2 clicks away

<img width="751" alt="screen shot 2018-03-05 at 11 06 59 am" src="https://user-images.githubusercontent.com/5720791/36994242-5a2e8fa0-2065-11e8-985d-15be09b756f1.png">

3) CT values of poorly documented - https://github.com/ArctosDB/arctos/issues/1450
