### ISSUE TITLE
Bulkload loan item sample disposition problems

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1436]
The bulkload loan item form appears to be converting the original sample disposition to on loan when the subsample option is chosen. The parent disposition should not change in this case - only the subample dispositioncreated for this loan should be "on loan". This has happened now for several loans  - not sure I know how many. 
Here are a couple: 
 MSB:Bird 2016.22.Bird
MSB:Mamm 2017.002.Mamm

Can we fix please? Also, any way to fix the parent sample dispositions retoactively? Any parent with a single subsample that is on loan should not also be on loan.

**Comment by dustymc** [comment]
Code fixed for next release, which I'll prioritize.


Data attached. 

[temp_oopsied_part.csv.zip](https://github.com/ArctosDB/arctos/files/1721087/temp_oopsied_part.csv.zip)

There are also a few MVZ and UAM records involved. @KyndallH @amgunderson @ccicero 

Just let me know what disposition should be and I can update them.

**Comment by campmlc** [comment]
For MSB, all parts on list that are not subsamples that do not have a loan associated with them should be "in collection".  All subsamples that do have a loan associated with them should be "on loan". Thanks!

**Comment by dustymc** [comment]
Done for MSB
