### ISSUE TITLE
unable to validate attribute bulkload

### ISSUE THREAD

**Issue by AdrienneRaniszewski** [ArctosDB/arctos#1437]
We can successfully upload a csv version the attached file in the Bulkload Attributes interface. However, when we try to validate the records we get the below error. We have loaded several other files of this kind, including one today, without this issue. I have checked the file for all the normal errors (extra spaces, misspelling, incorrect headers, etc.) and don't see anything. Any ideas?

"Error Executing Database Query. 
[Macromedia][Oracle JDBC Driver][Oracle]ORA-01427: single-row subquery returns more than one row"

[D10 Attributes.xlsx](https://github.com/ArctosDB/arctos/files/1720830/D10.Attributes.xlsx)

**Comment by dustymc** [comment]
http://handbook.arctosdb.org/documentation/understanding-errors.html#single-row-subquery-returns-more-than-one-row

These are the problems:

OTHER_ID_NUMBER
--
NEON.MAM.D10.R0778
NEON.MAM.D10.R0778
NEON.MAM.D10.R0778
NEON.MAM.D10.R0778
NEON.MAM.D10.R0778
NEON.MAM.D10.R0778
NEON.MAM.D10.R0778
NEON.MAM.D10.R1059
NEON.MAM.D10.R1059
NEON.MAM.D10.R1059
NEON.MAM.D10.R1059
NEON.MAM.D10.R1059
NEON.MAM.D10.R1059
NEON.MAM.D10.R1059
NEON.MAM.D10.R1059
NEON.MAM.D10.R1059
NEON.MAM.D10.R1059
NEON.MAM.D10.R1059
NEON.MAM.D10.R1059
NEON.MAM.D10.R1059
NEON.MAM.D10.R1059
NEON.MAM.D10.R1059
