### ISSUE TITLE
"PART_REMARK_19": invalid identifier

### ISSUE THREAD

**Issue by msbparasites** [ArctosDB/arctos#1438]
Thus far I have been unable to upload a bullkload file. I have fixed several errors, but this one I am stumped.... If I remove the part remark 19 column, it then tells me that part_remark_18: invalid identifier. I have cleared for spaces etc... I have retyped the column and deleted the old one, I have counted columns to make sure it was not off by one....

So either I am missing something OR perhaps I cannot upload more than a certain number of parts? Is 19 parts too many?

Thank you.

**Comment by campmlc** [comment]
Sara, Dusty may correct me on this but my understanding is we can only load
10 at a time. . . so I would do the rest using the parts bulkloader, which,
unfortunately, is in a vertical format rather than horizontal.

**Comment by msbparasites** [comment]
Thank you very much. That was the problem, I kept up to 10 Parts, and it loaded......

**Comment by dustymc** [comment]
Bah! Sorry, this didn't post yesterday.

--

The authoritative bulkloader specification is 

<img width="383" alt="screen shot 2018-02-13 at 11 34 52 am" src="https://user-images.githubusercontent.com/5720791/36169740-f3d6ffd4-10b1-11e8-9158-cdca4b371d49.png">

The specimen bulkloader will handle up to 12 parts.

You could load specimens without parts, then...

<img width="481" alt="screen shot 2018-02-13 at 11 36 20 am" src="https://user-images.githubusercontent.com/5720791/36169805-24edbf72-10b2-11e8-96af-fad78611854f.png">

Let me know if I can help shuffle things around.

**Comment by msbparasites** [comment]
Thanks for that. I think for this project, the bulkload parts will be the most efficient - we just have 20-30 slides for one record! Happens a lot, but obviously not when I have been creating a bulkload - so a reminder about the bulkload parts is going to make this SO smoother.
