### ISSUE TITLE
User interface consistency - upload this file button

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1439]
No rush, but I was working on some documentation today and I noticed that the "Upload this file" button changes color depending upon which bulkloader you are working with (see attached photo). For consistency, it would be nice if this button could be the same color no matter where you are uploading a file. I suggest the turquoise color seen in the Bulk Edit Container portion of the photo just because it is almost green, which signals go to me.

![upload this file](https://user-images.githubusercontent.com/5725767/36180939-be6944d2-10df-11e8-9647-e6f4d1c51960.jpg)

**Comment by dustymc** [comment]
Thanks/fixed. (I hope - I'll leave this open for a while, please report any more inconsistencies here.)

The appearance of the buttons is easily controlled. FYI the various button categories (from https://github.com/ArctosDB/arctos/blob/master/includes/style.css) below. I generally treat upload as an insert, but it's not terribly surprising to find I've been less than consistent with the "sorta..." cases. 



```
/* save changes */
	input.savBtn {
	   	
	}
	
	/* link; go somewhere not terribly scary */
	input.lnkBtn {
		
	}
	
	/* search button: finds something */
	input.schBtn {
		
	}
	/* clears or resets a form */
	input.clrBtn {
		
	}
	
	/* insert: makes something new */
	input.insBtn {
		
	}
	
	/* opens a pick list */
	input.picBtn {
		
	}
	
	/* delete: something dies with clicky */
	input.delBtn {
		
	}
	
	/* quit: go somewhere else without saving any changes */
	
	input.qutBtn {
		
	}

```
