### ISSUE TITLE
User interface consistency - use of status

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1440]
No rush, just something I have noticed. When using Bulk Edit Container, I have to assume status is valid as long as there is nothing in the note column while in the Part Bulkloader, I am given more explicit information in the status column (see attached photo for comparison). I suggest a review of all bulkloader validation return tables and consistent use of the status column in all bulkloaders to help users decide what can be loaded and what needs further review.

![status](https://user-images.githubusercontent.com/5725767/36181214-23a4aec6-10e1-11e8-884d-c6f61b5252d3.jpg)

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/2974 will resolve this; merging
