### ISSUE TITLE
image upload process is broken

### ISSUE THREAD

**Issue by amgunderson** [ArctosDB/arctos#1442]
I tried to upload 50 images via the batch tools, upload images page, http://arctos.database.museum/tools/uploadMedia.cfm, it worked until got to the preview files page which showed no image files,
<img width="1381" alt="screen shot 2018-02-16 at 1 49 40 pm" src="https://user-images.githubusercontent.com/8440698/36332973-e2d34226-1320-11e8-9d7b-71b10b5591d6.png">
I then clicked on "download a bulkloader template" hoping that part worked but got a csv file with this,
<img width="754" alt="screen shot 2018-02-16 at 1 49 58 pm" src="https://user-images.githubusercontent.com/8440698/36333025-225d487e-1321-11e8-8bd2-8b4bfd9d1090.png">
I did everything correct, can this be debugged?

**Comment by dustymc** [comment]
Please attach the data.

**Comment by amgunderson** [comment]
You want the .zip file of images? It didn't even confirm that the images loaded correctly much less provide a bulkload media template, so I don't have any data other than a 500mb zip file.

**Comment by dustymc** [comment]
Yes, I suspect the problem is in there somewhere - the tool works fine for me.

**Comment by amgunderson** [comment]
I'll try again with smaller image sizes.

**Comment by amgunderson** [comment]
The request has exceeded the allowable time limit Tag: CFLOOP. With 50 jpgs 3-4 mb each. Why does this never work?! I refuse to spend a week of my life figuring this out: http://handbook.arctosdb.org/how_to/How-to-Upload-Media-to-TACC.html. What is the easiest way to upload specimen images to Arctos?

**Comment by dustymc** [comment]
SSH/SCP is the easiest method from my perspective, and I believe @ccicero  can set that up - Carla??

The tools I have available on that pathway aren't ideal - not too surprising that timed out. It might work with two uploads.

I'm always up for better ideas regarding Media.

Email your zip to data.5xret59ahx21x7na@u.box.com and I can get them somewhere accessible until you get SSH sorted out.

**Comment by amgunderson** [comment]
I'll load these myself through the TACC process I guess. This upload images widget is easy and awesome if it would work. Facebook, Google, Amazon, Instagram, Flickr can take 50 pics at once no problem, Arctos should too.
