### ISSUE TITLE
Please help with information for SPNHC Symposium on Data Quality Feedback

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1443]
Arctos collective,

I have been asked to comment on my experience with iDigBio data quality flags as part of a symposium at SPNHC 2018 titled: Challenges For Implementing Collections Data Quality Feedback

I would like to share the Arctos community experience with iDigBio data quality flags along with my own as I believe it would add to the conversation. If one person from each participating biological collection could please complete this survey, it would help me share our thoughts on this process. The survey is located at 

https://www.surveymonkey.com/r/SCXHWXD

If you have any questions or something specific you would like to share with iDigBio and the biological collections data aggregator community in general, please add it in the comments or email me directly at tmayfield.utepbc@jegelewicz.net

Thanks everyone!!!

**Comment by dustymc** [comment]
Related threads:

 https://github.com/ArctosDB/arctos/issues/1291
- arbitrary "corrections" are still arbitrary
- ISO8601 is NOT so arbitrary


https://github.com/ArctosDB/arctos/issues/1176
- GBIF and whoever else wants it should just find our data

Other random things that may or may not be Issues or relevant:
- clicking the 'funky data' link in GBIF (or "justPoppedUpLike5MinutesAgoNet") should write to the original specimen record in Arctos. (Although we probably do NOT want to add annotations for "these million specimens are in the wrong arbitrary bucket" reports.)
- ditto usage statistics
- if GRBIO does something useful for us, they should pull from Arctos (eg, I suspect GBIF pulls old info from them and sends reports to dead email addresses and etc.)
- I think the IPT metadata-thingee (which seems redundant with GRBIO) is sort of a pain, Arctos should be able to handle that (GBIF-et-al would need to accept whatever Arctos provides)
- The current "publication" pathway involves someone (at VertNet I believe) with a DB connection to the Arctos back end pulling out several million records whenever they remember to push the button. Arctos should be able to push changes as they happen.

**Comment by Jegelewicz** [comment]
Thanks @dustymc I will follow all of these threads and compile the info. I'll probably pester you with questions later....
