### ISSUE TITLE
Wildcard search on part barcode to find records that are not NULL for part barcode

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#1445]
It would be nice to be able to do a wildcard type search that returns all records that have any non-NULL value in their parts barcodes field(s). We have thousands of records without barcodes (from a big data import) and we've been slowly finding these, editing them, adding barcodes etc. It's hard to keep track of this progress, and manage these records because there's no easy way to summarize # of records with vs without barcodes.

**Comment by dustymc** [comment]
added NULL option to part barcode
