### ISSUE TITLE
Automated loan notification emails to loan recipients

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1448]
An arctos feature to add?

---------- Forwarded message ----------
From: <no_reply_loan_notification@mczbase.mcz.harvard.edu>
Date: Sat, Feb 17, 2018 at 10:56 PM
Subject: MCZbase Notification for Loan Number: 2015-27-Cryo
To: 

---------------------------------------------------------------------
MUSEUM OF COMPARATIVE ZOOLOGY
HARVARD UNIVERSITY

LOAN NOTIFICATION REPORT FOR 18-February-2018 

Dear Colleague, 

This is an MCZbase notification report regarding an MCZ Loan due for RETURN to the Cryogenic Collection. 

LOAN DUE TO BE RETURNED: 

Loan Number: 2015-27-Cryo 
Loan Type: consumable 
Loan Date: 19-November-2015 
Due Date: 19-November-2017 

Approved Borrower: xxxxxxx
Shipped to:
xxxxxxxx

For Use By:	xxxx

Nature of Material: 3 dry tissue samples from Citellus eversmanni for use by graduate student xxxxx. Samples shipped to: xxxxxxxxxxx addresss
Original Total Number of Items:	3 
Partial Return of Loaned Items: No 

We request that you please return the above loan or request an extension by the Due Date. For more information on this loan, contact the Cryogenic Collection (bzimkus@oeb.harvard.edu). Your attention to this matter will be greatly appreciated. 

For Cryogenic Collection loans, if you have any remaining material (e.g., tissue, DNA), please email the Collection Manager to discuss whether it should be returned. To officially close this loan, please also provide publication information and NCBI sequence accession numbers to the MCZ-CRYO.

NCBI accessions will automatically link to MCZbase records if information is submitted correctly:
http://www.mcz.harvard.edu/collectionsoperations/downloads/Guidelines_for_submitting_to_GenBank.pdf
http://www.mcz.harvard.edu/collectionsoperations/downloads/NCBI_BioProject_BioSample_Data1.pdf

Thank you.
---------------------------------------------------------------------

**Comment by dustymc** [comment]
http://www.mcz.harvard.edu/collectionsoperations/downloads/Guidelines_for_submitting_to_GenBank.pdf 404s for me, if someone wants to let the Harvard folks know.

I said

>Technically trivial, I'm just a little paranoid about sending automated email to "not us."

then @campmlc  said

>This would be a huge help in getting attribution for specimens. We get virtually no response from researchers when they publish. This way they will get nagged until they give us this info so we can close the loan. This is part of their loan condition, and it is what we need to justify our existence, yet it does not happen.If someone accepts loan terms, they should accept automated emails.

I think there are at least three things involved:

1) What Arctos does (eg, Arctos can send email to whomever and whenever ya'll want), tools (should the "genbank discovery tool" send email?), etc.
2) Loan policies, and how we record usage (or fail to). There are huge variations in things like % of collection loaned, % of loaned specimens with citations, etc. across Arctos collections. Some of that's legacy data, some may be available resources, but I think some of it is also collections not knowing "best practices" for things like when to create loans, or not having clear criteria for when to close loans ("To officially close this loan, please also provide..."), or perhaps not knowing the functional implications of certain data choices - eg, #1412. I suspect we could all learn something from other collections. Perhaps we should try to fund a workshop or similar??
3) Other stuff that perhaps we-the-community could help with - citing specimen guidelines (#1441, #1130), GenBank registration (are all Arctos collections known by GenBank? Do we provide that info to new collections? I don't even know what the process at Genbank is!), etc.

**Comment by ebraker** [comment]
Here's the pdf from the "broken" link (it's just pw protected, and I still remember the credentials...plus I was the one who wrote this pdf way back when at MCZ so I don't feel too bad about it). It is sent to all researchers borrowing tissues and describes how to put in the catalog number and collection code when submitting GenBank sequences taken from MCZ specimens. This may help increase linkages back to Arctos records via GenBank accession #s, but really the auto-prompts for overdue loans will do (and to my knowledge have done) a better job in getting both borrowers to return specimens promptly and/or to submit and link sequence data (a requisite for closing out any MCZ genetic loan). If borrowers don't submit sequence data, they are not approved for subsequent genetic loans so there is added incentive to do so). I can email Brendan and Breda and ask them more about how they set up the loan messages.
[Guidelines_for_submitting_to_GenBank.pdf](https://github.com/ArctosDB/arctos/files/2211654/Guidelines_for_submitting_to_GenBank.pdf)

**Comment by ebraker** [comment]
Here is the code from MCZ. Approved for sharing:

https://github.com/MCZbase/MCZbase/blob/master/ScheduledTasks/longtermreminder.cfm

**Comment by campmlc** [comment]
Harvard code from Paul Morris:

(1) Here's our updates to the loan reminder email code, and our addition of periodic reminders to collection managers for long overdue loans.

https://github.com/MCZbase/MCZbase/blob/master/ScheduledTasks/reminder.cfm

https://github.com/MCZbase/MCZbase/blob/master/ScheduledTasks/longtermreminder.cfm

(2) Here's the list of changes to the code to add warnings to alert collection management staff about potentially problematic loanees when creating loans (along with additions of properties of agents that allow them to be marked as problematic.

https://github.com/MCZbase/MCZbase/search?p=2&q=Redmine+324&type=Commits&utf8=%E2%9C%93

**Comment by campmlc** [comment]
Add to loan creation/loan edit form option to turn on/off  open loan notification form, with notification recipient agent.
Create new agent type.

**Comment by dustymc** [comment]
- new loan status(es) to mark things that need notifications
- new trans agent role for who will get notifications
- "find problem loans" form in Arctos

**Comment by dustymc** [comment]
Harvard doesn't seem to make their authorities public so I have no idea what these are, but the loan agent roles involved are 'in-house contact',  'additional in-house contact', 'additional outside contact', 'for use by', 'received by'

They've added at least loan status 'open under-review' and 'open partially returned,' and seem to send the reports to loan status LIKE 'open%'

The reports are based partially on the disposition of the objects in the loans - do we all change disposition to something other than "on loan" when a loan is returned? What happens with consumables? Close loans before adding an item to another loan? We have a ton of loans with nothing in them (Reports/low-quality.../...loan...), which might mess with this.

I see no references to citations or genbank in the code - I think this relies entirely on a Curator flipping flags.

We can do more, if ya'll want.

You can already access projects with loans and without publications - same report as above.

Reports/low-quality.../...undocumented citations find....


    Project Publications lacking Citations
    Project Publications lacking DOI
    Specimens with GenBank IDs and no citations
    Specimens with GenBank IDs and no loans
    Specimens with Citations and no loans

You can search publications for 'cites no specimens' (339 of them!)

and it should be fairly simple to pull the query from any of those for this.

- how's loan status tie in?
- maybe we need a 'we don't expect publications' loan type
- we do need a 'we expect genbank citations' flag somewhere (part tissue flag isn't sufficient - lots of not-tissues end up on GB)

https://github.com/ArctosDB/arctos/issues/1257 will complicate things - eg, a specimen with a citation didn't necessarily get the citation from the current loan.

**Comment by Jegelewicz** [comment]
Reviving this issue after listening to a talk by Breda Zimkus (Harvard Genomic Collection) on The Effect of the Nagoya Protocol on Biological Collections. Hope the talk will be come publicly available as it was recorded for [Biological Collections: Their Past, Present, and Future Contributions and Options for Sustaining Them](https://www8.nationalacademies.org/pa/projectview.aspx?key=51270). Although focused on genomic samples, NAGOYA applies to everyone and everyone should be thinking about it. 

> A genetic resource is any biological material of plant, animal, microbial or other origin ‘containing functional units of heredity’, of actual or potential value that can be obtained from the wild, domesticated or cultivated; it may be sourced in-situ (where it naturally occurs) or ex-situ (from human-made collections). - [SPNHC NAGOYA Wiki](https://spnhc.biowikifarm.net/wiki/Access_and_Benefit-Sharing_(Nagoya_Protocol_and_the_CBD))

The return of specimens may no longer be the reason for closing a loan. Benefit sharing requirements under NAGOYA mean that the knowledge gained from the use of genetic resources needs consideration and possibly documentation by the lender unless otherwise agreed upon. I would expect that lenders would REQUIRE return of knowledge gained in order to demonstrate relevance.

> Benefit-sharing: requires the fair and equitable sharing of benefits arising from the utilization of genetic resources and/or traditional knowledge, upon mutually agreed terms (MAT) between provider and user. Depending on the Providing Country and domestic legislation, additional agreements with indigenous and local communities that hold rights on genetic resources need to be considered or may be required;

I think we should be expecting more from the borrower community and they should be aware of the document at https://spnhc.biowikifarm.net/wiki/Access_and_Benefit-Sharing_(Nagoya_Protocol_and_the_CBD).

Reminder emails are not a nuisance, they are part of our job as stewards of the collections!

**Comment by dustymc** [comment]
>Reminder emails are not a nuisance, they are part of our job

I agree, with emphasis on "our." Arctos already sends loan notifications to "us" - it's only sending them to "not-us" that I'm hesitant to embrace. Arctos can provide tools, but I think a person needs to actually contact borrowers, follow up on those contacts, etc. It's also really easy to find loan data that doesn't make sense - the people in the collections probably/hopefully know what's going on with that, but I certainly don't see a way to get there from the data.

```
UAM@ARCTOS> select count(*) from loan where transaction_id not in (select transaction_id from loan_item);

  COUNT(*)
----------
      2393

1 row selected.

Elapsed: 00:00:00.34
UAM@ARCTOS> select count(*) from loan where loan_status='open' and transaction_id in (select transaction_id from loan_item,COLL_OBJECT where loan_item.collection_object_id=COLL_OBJECT.collection_object_id and COLL_OBJ_DISPOSITION !='on loan');

  COUNT(*)
----------
       356

```
I can't send anything as long as https://github.com/ArctosDB/arctos/issues/1893 is an option.

```
UAM@ARCTOS> select count(*) from loan where return_due_date is null;

  COUNT(*)
----------
      5540

```

I think we should also expect citations to unambiguously refer to specimens. https://github.com/ArctosDB/arctos/issues/1441, https://github.com/ArctosDB/arctos/issues/1130, https://github.com/ArctosDB/arctos/issues/1895.

**Comment by campmlc** [comment]
Let's add this to the AWG agenda. I agree that this is a critical issue. We
are currently failing at the single most important task we have as
collections and as a research community - getting citations back to
specimens. This is the one thing we could do that would make the most
impact.

**Comment by Jegelewicz** [comment]
Enable or disable by collection for each loan as an option?

**Comment by campmlc** [comment]
Or by loan - this works.

**Comment by mkoo** [comment]
AWG 3/7/2019: We would like to see this implemented where operators can select whether or not loan reminders go out on a loan by loan basis.
@dustymc

**Comment by dustymc** [comment]
Just leave due date NULL for no reminders.

**Comment by ccicero** [comment]
Isn't this issue resolved to the point where it can be implemented? @dustymc

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/1448#issuecomment-461879808

I'm still unclear on the details of what we're trying to do. This seems like a Curator's job; they already receive notifications with emails which can be used to forward.

We have a ton of loans with no specimens. What exactly would the automated email say?!? 

We have tons of active loans where we also claim the material is in the collection.

Those things (and I'm sure there are more) may make perfect sense to Curators, but they make no sense from the data. I don't see how I can possibly use the data to contact outside parties without making some sort of huge mess.

I also can't receive replies, which may not be fatal but will result in frustrated users.

I believe a big part of the effort is to get borrowers to acknowledge usage, and we explicitly do not have those data either - https://github.com/ArctosDB/arctos/issues/1257

**Comment by campmlc** [comment]
And yet Harvard makes this work. What can they do that we cannot?
I think we are making this into a much more complicated thing than it is.
Make the notification optional, at curatorial discretion.
I can't send reminder notifications for 50 loans x past 5 years = 250 loans
every year without some automation.

**Comment by dustymc** [comment]
> What can they do that we cannot?

Better (or much worse!?) loan data perhaps? They're much more homogeneous, I think.

>Make the notification optional, at curatorial discretion.

That makes me less-twitchy, anyway. Add a documented value to http://arctos.database.museum/info/ctDocumentation.cfm?table=CTTRANS_AGENT_ROLE and I could copy them on the normal notifications.

>without some automation.

There's been automation for at least a decade. They go out a several times in the life of every single loan for which I have enough information to send them, and look something like this:

```
 You are receiving this message because you are listed as a contact for loan UAM:ES 484.2017.ESCI, due date 2018-10-05.

The nature of the loaned material is:

    Plant material associated with Blue Babe (UAMES 4588), including one bag labeled "plant material", and one labeled "wood" in a box with a variety of Blue Babe material.

Specimen data for this loan, unless restricted, may be accessed at https://arctos.database.museum/SpecimenResults.cfm?loan_trans_id=21115351

You may edit the loan, after signing in to Arctos, at https://arctos.database.museum/Loan.cfm?Action=editLoan&transaction_id=21115351

Loan Contacts are listed as follows.

    Joshua D. Reuther: (outside contact)
    Joshua D. Reuther: (received by)
    Katherine L. Anderson: klanderson3@alaska.edu (entered by)
    Patrick Druckenmiller: (authorized by)
    Patrick Druckenmiller: (in-house contact)

```

The "everyone's info" bit is on there because someone (@DerekSikes I think) uses it to selectively forward, I hope and presume after checking that the loan wasn't returned but not closed, extended, etc.

(And @KatherineLAnderson looks like UAM:ES doesn't have proper collection contacts and those are going to never-never land.)

The other missing piece from Harvard is the idea of a closed loan - I believe they differentiate between "returned" (material is where it belongs) and "closed" (reprints and GenBank and whatever other requirements were in the agreement have been dealt with). The notifications are for "not closed" so that's just a new value in http://arctos.database.museum/info/ctDocumentation.cfm?table=CTLOAN_STATUS. There's no obvious technical component to that, but it sounds like a really useful thing to me.

**Comment by dustymc** [comment]
@campmlc @Jegelewicz I don't see where either of you are getting the normal reminders. No matter where this ends up, it's only going to end up there for loan request collection contacts.
