### ISSUE TITLE
geography cleanup request: Russia

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1452]
We have Okrugs and Districts and oblasts and raions and republics and probably more scattered randomly across a bunch of columns. Can we be more consistent?

**Comment by dustymc** [comment]
Would also be very useful to find WKT - many Russian "things" (http://arctos.database.museum/Locality.cfm?Action=editGeog&geog_auth_rec_id=35) sort of fade out over large distances, without spatial data it's hard to tell what's going on.

**Comment by mkoo** [comment]
Well, we can only be as consistent as the Russian Federation! We can aim
for admn 1 (oblasts and krais) and their republics  as HG entries with wkts
but there are exceptions to every rule here. I think to prioritize we
should go for the ones we have specimens from since there are something
like 80 of these regional administrations. Unless there are some high
priority ones that someone needs for data entry

**Comment by dustymc** [comment]
> as consistent as the Russian Federation

WKT lets is ignore all that, right?!

There's no urgency to this from my perspective - I just accidentally looked at a map of Magadan according to Arctos this AM.

**Comment by Jegelewicz** [comment]
From [Wikipedia](https://en.wikipedia.org/wiki/Russia#Political_divisions)

> **Federal Subjects**
> According to the Constitution, the country comprises eighty-five federal subjects,[179] including the disputed Republic of Crimea and federal city of Sevastopol.[180] In 1993, when the Constitution was adopted, there were eighty-nine federal subjects listed, but later some of them were merged. These subjects have equal representation—two delegates each—in the Federation Council.[181] However, they differ in the degree of autonomy they enjoy.
> 
>     46 oblasts (provinces): most common type of federal subjects, with locally elected governor and legislature.[182]
>     22 republics: nominally autonomous; each is tasked with drafting its own constitution, direct-elected[182] head of republic[183] or a similar post, and parliament. Republics are allowed to establish their own official language alongside Russian but are represented by the federal government in international affairs. Republics are meant to be home to specific ethnic minorities.
>     9 krais (territories): essentially the same as oblasts. The "territory" designation is historic, originally given to frontier regions and later also to the administrative divisions that comprised autonomous okrugs or autonomous oblasts.
>     4 autonomous okrugs (autonomous districts): originally autonomous entities within oblasts and krais created for ethnic minorities, their status was elevated to that of federal subjects in the 1990s. With the exception of Chukotka Autonomous Okrug, all autonomous okrugs are still administratively subordinated to a krai or an oblast of which they are a part.
>     1 autonomous oblast (the Jewish Autonomous Oblast): historically, autonomous oblasts were administrative units subordinated to krais. In 1990, all of them except for the Jewish AO were elevated in status to that of a republic.
>     3 federal cities (Moscow, Saint Petersburg, and Sevastopol): major cities that function as separate regions.
> 
> Further information: Political status of Crimea and Sevastopol and Annexation of Crimea by the Russian Federation
>
> **Federal districts**
> 
> Federal subjects are grouped into eight federal districts, each administered by an envoy appointed by the President of Russia.[184] Unlike the federal subjects, the federal districts are not a subnational level of government, but are a level of administration of the federal government. Federal districts' envoys serve as liaisons between the federal subjects and the federal government and are primarily responsible for overseeing the compliance of the federal subjects with the federal laws. 

So the "eight federal districts" should be the first order of division below "country" and the "eighty-five federal subjects" should be the second order of division below "state", right?  I think that including the "type" of federal subject makes sense, so in the "county" column you would have "oblasts", "republics", "krais", "okrugs", and "federal cities"?

**Comment by Jegelewicz** [comment]
OR do we ignore the federal districts and include the federal subjects as "states"? This seems like a better idea to me since the districts are "not provisioned by the Constitution of Russia and are not the constituent units of the country, but exist purely for the convenience of governing and operation by federal government agencies."

**Comment by dustymc** [comment]
Tabling - https://github.com/ArctosDB/arctos/issues/3272 would allow Arctos to standardize geography.
