### ISSUE TITLE
Invoice no longer printing

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1453]
I am trying to prepare an invoice for a researcher at UTEP and suddenly my invoice no longer functions. When I select print I get this message:

select flat.collection, flat.collection_cde, flat.scientific_name, flat.cat_num, flat.sex, flat.collection_object_id, specimen_part.part_name as part, coll_object.condition part_condition, CASE WHEN length(coll_object.condition) > 15 or flat.ENCUMBRANCES is not null THEN 'X' end AS has_appendix, higher_geog || '. ' || spec_locality || case when flat.dec_lat is not null then '. ' || round(flat.dec_lat,4) || '/' || round(flat.dec_long,4) || ', ' || flat.datum else ' Not georeferenced.' end as locality, item_instructions, loan_item_remarks, coll_object.coll_obj_disposition, flat.ENCUMBRANCES, loan.loan_number, trans.trans_date, flat.datum, flat.verbatim_coordinates from loan_item, loan, trans, specimen_part, coll_object, flat WHERE loan.transaction_id = loan_item.transaction_id and loan.transaction_id = trans.transaction_id and loan_item.collection_object_id = specimen_part.collection_object_id AND specimen_part.collection_object_id = coll_object.collection_object_id and specimen_part.derived_from_cat_item = flat.collection_object_id and loan_item.transaction_id = 21116555 ORDER BY flat.scientific_name, to_number(flat.cat_num)

Ugh - I don't have time to redesign an invoice, can this be easily fixed?
Thanks to anyone who can help!

**Comment by dustymc** [comment]
I'd need a lot more info to know what's actually going on, but...

>to_number(flat.cat_num)

Are you trying to use the report for a collection with non-numeric catalog numbers?

**Comment by Jegelewicz** [comment]
Yes - is that the problem?

**Comment by Jegelewicz** [comment]
If so, is there some easy fix?

**Comment by dustymc** [comment]
remove the to_number() function

ORDER BY flat.scientific_name, flat.cat_num

**Comment by Jegelewicz** [comment]
That worked. Thank you!!!
