### ISSUE TITLE
yearly (?) collection contacts report

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1454]
Send yearly email to collection contacts.

- Contact(s) + role(s)
- Addresses
- Operators (just active?)

Also include where to find documentation, email lists, github info, ???

What else?

**Comment by campmlc** [comment]
An "unsubscribe" option?

**Comment by dustymc** [comment]
>An "unsubscribe" option?

That doesn't sound very research-grade!

**Comment by campmlc** [comment]
Well, maybe we call it something more research-sounding . . .
e.g. I am no longer involved with Arctos and want my email removed from
collection contacts?

**Comment by dustymc** [comment]
3 changes:

1) Account unlock now has a "unlock only" option which does not require a password change. Use it basically only for Curators who don't log in very often.

2) There is an email report. Lacking further instructions, I'll send it to data quality contacts every 90 days to more or less coincide with the account lock schedule.

3) There is a new report (linked from the email report and Reports tab) which provides info about a collection's contacts and users, and links to tools.

Email:

<img width="639" alt="screen shot 2018-03-02 at 2 35 20 pm" src="https://user-images.githubusercontent.com/5720791/36925281-fb08e18c-1e26-11e8-85b5-ba6517d75748.png">


Details link:

<img width="603" alt="screen shot 2018-03-02 at 2 32 54 pm" src="https://user-images.githubusercontent.com/5720791/36925217-a8555416-1e26-11e8-9065-d18b1333039a.png">

clicking agents scrolls to...

<img width="1013" alt="screen shot 2018-03-02 at 2 34 07 pm" src="https://user-images.githubusercontent.com/5720791/36925247-cbd5518e-1e26-11e8-8411-8fb4e2706a34.png">

**Comment by dustymc** [comment]
This is now set to run on the 10th day of every 4th month
