### ISSUE TITLE
Problems with Reports and Label generation

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1455]
We are having creating new label templates/editing old ones. We are downloading existing reports as templates into Report Builder and altering a single field name. When we upload and clone and edit the handler as described below, we get following message. We've also tried this by copying and pasting the text from another handler. We made this work once . . . but now cannot duplicate.

An error occurred while processing this page! 
Invalid ColdFusion expression in report. 
If the expression is a string, ensure that it is within quotes. Error: replace(LOCALITY,' ,','','all') is not a valid ColdFusion expression.
This message has been logged. Please contact us with any information that might help us to resolve this problem.

We have followed these steps from the documentation:
Click “clone handler” to create a new report. This will create a new report, named Clone_Of_{old_report_name}_{random_integer} – in this case, Clone_Of_DMNS_bat_label_1384379564869.

screen-shot-2013-11-13-at-1-54-29-pm

Locate the clone and click Edit Handler. Rename the report and choose the CFR you just loaded as the Report Template.

screen-shot-2013-11-13-at-2-07-44-pm

Help?

**Comment by dustymc** [comment]
I don't see a DMNS_bat_label or any clones of it.

**Comment by campmlc** [comment]
Here is one that works:
MSB_Para_4dram_Prep

Here is one that doesn't work:
MSB_Para_OrigID2

We can't find the difference between the two, since one was a clone of the
other.

**Comment by dustymc** [comment]
The clone is missing pre_function, which returns the data object containing "locality."

**Comment by dustymc** [comment]
updated cloner
