### ISSUE TITLE
Searching Cultural Collections

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#1457]
Pulled from #1434
@dustymc 
> FYI comma list-substring requires more processing than you need - it lets "Phoca, Pusa" find "Phoca vitulina" and "Pusa hispida" and such.

> screen shot 2018-02-27 at 12 38 14 pm
> 
> is "contains basket" ("Basket, straw" and, because of the leading %, "decorated knob for handle on basket").

When only searching Ethnology & History, we recommend that (non-expert) users do this:
![ss_searchidentification](https://user-images.githubusercontent.com/17605945/36755215-001ffb18-1bb8-11e8-83c9-cba8e528c883.jpeg)

This search reliably returns the objects that I'm looking for from my and archaeology collections. Is your screen shot from the widget at the top of the results page?

Here's the link to my How-To guide also: http://uaf.edu/museum/collections/ethno/search-collections/

You should definitely attend my webinar on the 12th so you can provide pointers from your standpoint to compare to how I"m using the system!

**Comment by dustymc** [comment]
>reliably returns the objects that I'm looking for from my and archaeology collections.

Yes, you'll get to the same place - if you don't time out first. IN is just a more expensive operation which isn't needed here.

>screen shot from the widget at the top of the results page

Yes, the search page is...

<img width="490" alt="screen shot 2018-02-27 at 1 42 39 pm" src="https://user-images.githubusercontent.com/5720791/36756542-23698b32-1bc4-11e8-9a32-774e87da609d.png">

I could add an explicit CONTAINS option, it's just expensive and sometimes crazy with biological names. Eg, the simplest query involving this is...


```
UAM@ARCTOS> select count(*) from taxon_name where upper(scientific_name) like 'MUS%';

  COUNT(*)
----------
      2245

1 row selected.

Elapsed: 00:00:00.01
UAM@ARCTOS> select count(*) from taxon_name where upper(scientific_name) like  '%MUS%';

  COUNT(*)
----------
     40721

1 row selected.

Elapsed: 00:00:01.63
```

Note the execution times (which are multipliers in "normal" queries).

>guide

http://arctos.database.museum/uam_eh is the direct link to your "portal."

"contains" in the default for the current Attribute search - details at http://handbook.arctosdb.org/documentation/attributes.html#searching-with-attributes (which should be linked from the pop-up help on every attribute).

>webinar

I will try to make that, and I always (eventually....) watch the videos.

**Comment by dustymc** [comment]
I added an explicit "contains" option to the ID search

<img width="192" alt="screen shot 2018-03-01 at 9 40 44 am" src="https://user-images.githubusercontent.com/5720791/36859882-a46f63e8-1d34-11e8-93c9-28cfb4f9c982.png">

>(non-expert) users

I threw together a "demo" custom search page: http://arctos-test.tacc.utexas.edu/uam_eh/search.cfm

<img width="775" alt="screen shot 2018-03-01 at 9 35 30 am" src="https://user-images.githubusercontent.com/5720791/36859678-01f834be-1d34-11e8-9071-748938f1c255.png">

It's not very "integrated" and it's just copypasta rather than sharing code etc., but maybe it'll be useful for some of your users or putting the idea that Arctos is an ecosystem rather than a static set of webpages more into practice or something.

**Comment by AJLinn** [comment]
@dustymc this is phenomenal! Exactly the kind of limited and focused custom search screen that our users would LOVE to use. Is this something we can put into practice? What are our options with moving forward with this?

**Comment by dustymc** [comment]
>moving forward

That form will go to production with the next release (which I could expedite - I don't think I have anything torn apart at the moment), and you can use it.

Integration (not maintaining the same code in two places, having a "go back to where I came from" option on results, perhaps piping "your" form to summary and graph and such, etc.) will take discussion and design and all that jazz.

As as alternative to "customizing Arctos," you could also host a search form and pull raw data from Arctos as JSON, which would also take some development (on both ends).

**Comment by AJLinn** [comment]
So for the custom page, once implemented, people would access it directly via a custom address (something like  http://arctos.datebase.museum/uam_eh/search.cfm ), which I could post on my website, signature line, etc.?

> As as alternative to "customizing Arctos," you could also host a search form and pull raw data from Arctos as JSON, which would also take some development (on both ends).
 
I'll need a little help understanding what that would mean, so I think using the above option first would be great.
Thank you!

**Comment by dustymc** [comment]
>access it directly 

Yup.

>JSON

If you wanted to do something which "core Arctos" can't or won't support (force Comic Sans font or something....) or just to have your own thing (which I think we could do as "core Arctos" anyway), or WHATEVER, you could build your own page/app/whatever and basically use Arctos as your back-end/database. That would complicate everything (think usage stats) and I'm certainly not recommending it, but those capabilities (mostly) exist.

**Comment by campmlc** [comment]
This sounds great, Dusty! Having a custom search page would solve a bunch
of issues that came up recently. So these would be tied to the individual
collections portal, but we would have a "search all Arctos collections"
button to go back to the main portal page?

**Comment by dustymc** [comment]
Just cleaning up - form is http://arctos.database.museum/uam_eh/search.cfm

**Comment by campmlc** [comment]
I think this is a great idea - it would be good to have a similar form for
different types of collections, with an "Advanced Search" option built in
that would take you back to the main form. We could link to these from our
collections homepage.  I would like to help develop something similar for
parasites and fish, and perhaps a generic one for "tissues" - most people
searching for tissues do not know to click  "require tissues", and they
frequently get confused as to what collections they are actually searching.

**Comment by dustymc** [comment]
>Advanced Search

<img width="220" alt="screen shot 2018-03-22 at 11 14 45 am" src="https://user-images.githubusercontent.com/5720791/37789883-44df197a-2dc2-11e8-9087-a3c9786a945b.png">

>similar form for different types of collections

New Issue please. Not much of a problem to build these forms, but maintaining them is - I'd want to build a framework for them (including the "normal" search form) so we can keep everything in sync.

>what collections they are actually searching

I think that works both ways. Many (most?) users don't CARE what collections they're searching, they just want squirrel skulls. Those are found in mammal collections, teaching collections, maybe host-of-parasite collections, probably a couple in herp collections (https://github.com/ArctosDB/arctos/issues/1192#issuecomment-333192102), etc. They end up on the "tiny squirrel-free mammal collection" search portal, don't find any squirrels, and go away. (I'm not convinced the users who don't find the "require tissues" option are going to find the "advanced search" option!)
