### ISSUE TITLE
Message when atempting unauthorized access - user interface

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1458]
Occasionally, I am logged out of Arctos for inactivity and when I return and attempt to renew my work on some protected area (say Managing Agents) I am directed to a page that says simply "Go away". I think it might be better to have something a little more helpful, such as "you do not have the required permission to access this functionality in Arctos. Please see your collection administrator if you believe this is an error. If you know you have access, please ensure that you are logged in to Arctos and try the page again."

Also, it would be really nice if Arctos could just tell me I have been logged out due to inactivity.

**Comment by dustymc** [comment]
Oh - sorry! I didn't realize people could get that...I'll do something else.

>logged out 

https://github.com/ArctosDB/arctos/issues/507
