### ISSUE TITLE
Media with bad thumbnail

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1464]
I uploaded this media as a single file a while back and the thumbnail has never shown up.

https://arctos.database.museum/MediaSearch.cfm?action=search&specimen_id=27605412

What's the best thing to do about this?

**Comment by dustymc** [comment]
http://handbook.arctosdb.org/documentation/media.html#media-creation-guidelines

66.03 KB (67,610 bytes)

Reduce filesize.

**Comment by Jegelewicz** [comment]
I am not able to reduce this file to any smaller that 35KB and the thumbnail only accepts 15K. I have cropped and reduced the original to the size of a dot in Paint and it is still just over 35KB. Can anyone suggest to me how to get this file size down? I am not a photo editor!

**Comment by dustymc** [comment]
http://makethumbnails.com/#dropzone exists.

![utep_herp_20972d_tn](https://user-images.githubusercontent.com/5720791/42833089-098c0d1e-89a8-11e8-80af-17912ec6b982.jpg)

Should be about 3K.

Arctos will create thumbs when you load images, and TACC can create them if you go the SCP route, but I don't have a way of doing that for existing images. Probably possible....

**Comment by Jegelewicz** [comment]
I loaded these through TACC, so it bugs me that this particular one came out weird. Thanks!

**Comment by Jegelewicz** [comment]
Added tip to media how-to
