### ISSUE TITLE
Attribute Search to Allow Values in Dropdown

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1466]
I would like to request that we add a dropdown menu to the attribute search that allows searching on attribute values. Currently it is possible (but not clear) to search on values, but the user must know these values in advance to type them in, or know to go looking for the code table values somewhere else.
Also, the message "Click the label after selecting an attribute type for more information. Empty values are ignored" is not clear. Where do we click the label? 

Referencing issue #1434

New Issue please - that's possible.

Some concerns/comments:

Arctos will deal with things outside code tables (http://handbook.arctosdb.org/documentation/attributes.html#searching-with-attributes)

CT values are currently 2 clicks away

screen shot 2018-03-05 at 11 06 59 am

CT values of poorly documented - #1450

**Comment by dustymc** [comment]
>I would like to request that we add a dropdown menu to the attribute search that allows searching on attribute values. 

Do you mean for categorical attributes (those with a value_code_table in http://arctos.database.museum/info/ctDocumentation.cfm?table=CTATTRIBUTE_CODE_TABLES) or something else?

>Currently it is possible (but not clear) to search on values,

it is also possible to search on things NOT entered as values, eg
``Arctos will deal with things outside code tables (http://handbook.arctosdb.org/documentation/attributes.html#searching-with-attributes)``

>somewhere else.

Relevant code tables are linked in the popup documentation.

<img width="563" alt="screen shot 2018-03-06 at 1 34 53 pm" src="https://user-images.githubusercontent.com/5720791/37059858-5937caa6-2143-11e8-8655-0ade7c9ab612.png">



> Also, the message "Click the label after selecting an attribute type for more information. Empty values are ignored" is not clear. Where do we click the label?

Changing...

<img width="275" alt="screen shot 2018-03-06 at 1 32 37 pm" src="https://user-images.githubusercontent.com/5720791/37059699-f1173786-2142-11e8-88d6-9d19cb8ada23.png">


results in...

<img width="136" alt="screen shot 2018-03-06 at 1 32 44 pm" src="https://user-images.githubusercontent.com/5720791/37059708-f5e6970c-2142-11e8-82bd-8c9099a8b794.png">

which works like all other labels on the page - clicking it opens docs (which is generated from code tables from attributes)...

<img width="608" alt="screen shot 2018-03-06 at 1 32 51 pm" src="https://user-images.githubusercontent.com/5720791/37059731-04880566-2143-11e8-8630-b32a5e910857.png">

**Comment by campmlc** [comment]
Also, it would be great if we could have the code table values show up directly as a popup, rather than requiring navigation through multiple links.

**Comment by campmlc** [comment]
Finally, not to ask for too much or anything, it would be good to have a delete option next to each attribute, so the search can be modified if you choose the wrong one.

**Comment by dustymc** [comment]
>explicit instructions for what content to add to the search box?

<img width="559" alt="screen shot 2018-04-20 at 4 22 27 pm" src="https://user-images.githubusercontent.com/5720791/39077490-13e6b470-44b7-11e8-9b3a-5051c794284b.png">

I'm not sure how to make that more explicit. What did you have in mind?

> populated with the name of the attribute

I would (and am, slowly) go the other way and add that to everything. That's an HTML5 "placeholder" (https://www.w3.org/WAI/tutorials/forms/instructions/#placeholder-text) which is intended to make things more accessible, although there's a fairly active group of developers who hate the things. Probably something that deserves dedicated discussion. I'm completely open to suggestions regarding value, should we decide to keep them around. Or you can set that in Manage/Documentation, although Attributes periodically build their own documentation from code tables so we'd need to adjust that if anyone's manually creating attribute documentation.

>click here for more info

Click the title, which works exactly like everything else on the page. I'm certainly up for better ideas, but they'd need implemented consistently.

>code table values

From ^^ up there:

>Do you mean for categorical attributes (those with a value_code_table in http://arctos.database.museum/info/ctDocumentation.cfm?table=CTATTRIBUTE_CODE_TABLES) or something else?

>delete option

I suppose, but again this works like everything else and ignores NULL values - we can do whatever, but we need to do it consistently.

**Comment by dustymc** [comment]
This is do-able in the current UI, going next task, needs prioritized.

**Comment by dustymc** [comment]
in next release, should be tested

**Comment by Jegelewicz** [comment]
This looks good
<img width="960" alt="Screenshot 2021-03-03 07 50 10" src="https://user-images.githubusercontent.com/5725767/109824001-a88dc780-7bf5-11eb-982f-5943ca869935.png">
<img width="960" alt="Screenshot 2021-03-03 07 50 22" src="https://user-images.githubusercontent.com/5725767/109824007-aa578b00-7bf5-11eb-8a8c-203541bdb95d.png">

Ran query using UTEP:Mamm with sex = female and got results

However, testing would be better if we had more current data in test....the code tables there are out of date and stale data means that some newer things are not around to test. Not sure how to remedy, but thought it should be brought up.

**Comment by dustymc** [comment]
>current data in test

https://github.com/ArctosDB/internal/issues/65
