### ISSUE TITLE
Addition of role to Publications?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1467]
I have been entering some publications lately and I wonder if it might be useful to have a role called "publisher". In this way, we could show all of the specimens across collections that contributed to publications by any given publisher.

My other thought was adding a separate field for the journal name to make searches by a journal easier.

**Comment by dustymc** [comment]
>role called "publisher".

No real objections.

>separate field for the journal name

We once had that, it was a giant pain. Could be painlessly (at least for the folks who don't use it!) implemented as another role/agent, I suppose.

For publications with DOIs, you can get that sort of thing on demand, e.g., from http://arctos.database.museum/publication/10007815

```
curl -LH "Accept: text/bibliography; style=bibtex" http://dx.doi.org/10.1139/gen-2015-0203
 @article{
    Sikes_2017, 
    title={Building a DNA barcode library of Alaska’s non-marine arthropods}, 
    volume={60}, 
    ISSN={1480-3321}, 
    url={http://dx.doi.org/10.1139/gen-2015-0203}, 
    DOI={10.1139/gen-2015-0203}, 
    number={3}, 
    journal={Genome}, 
    publisher={Canadian Science Publishing}, 
    author={Sikes, Derek S. and Bowser, Matthew and Morton, John M. and Bickford, Casey and Meierotto, Sarah and Hildebrandt, Kyndall}, 
    editor={Hausmann, AxelEditor}, 
    year={2017}, 
    month={Mar}, 
    pages={248–259}
}

**Comment by Jegelewicz** [comment]
I like the idea of the publisher being an agent. I'll bring it up at next AWG meeting.

The herp journals seem to be particularly bad about offering dois, so I haven't had much success there and I would really like to be able to find ALL the citations from any particular journal.

**Comment by Jegelewicz** [comment]
Closing for lack of interest
