### ISSUE TITLE
Agent preferred names

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1471]
I quite often add agents with a middle initial. While not ideal, the initial can be the difference between John Q. Doe and John B. Doe. When you create such an agent, you are confronted first with the decision to force create the agent (sorry I failed to screen shot that), then when you view the agent you get this:
![image](https://user-images.githubusercontent.com/5725767/37214730-1e057032-2373-11e8-95d2-21173c3c45cb.png)

What does everyone think about modifying the wording on both of these to exempt middle initials? Personally, I would like to exclude middle initials from the need to force create an agent, but I understand if that is not an easy thing to do.

Or are we really of the opinion that middle initials should not be included in preferred name even if it is, for some people, their preferred name?

I am thinking of new users or infrequent Agent creators here who might be discouraged from using that initial, which could really help others know who that agent is and also just of ways to lower the number of clicks required to create an agent that is appropriate.

**Comment by dustymc** [comment]
The thing that forces you to force-create relies on the same code as the "potential problems" notice.

Duplicates in supposedly-unique data leads to unreliable answers. The point of all of the agent "suggestions" (which exist in support of http://handbook.arctosdb.org/documentation/agent.html#creating--maintaining-agents) is to reduce duplicates. There are a couple components to that front.

1) Consistent format. If "Smith, JR" isn't possible then we won't have to guess if it's the same thing as J. R. Smith (or maybe Smith, Jr. or John Robert Smith or Bob Smith or ....).

2) Complete data. A lot (most? all?) of collections traditionally withhold information - they "prefer" "J. R. Smith" even when they know more. (Which is mostly fine if they put the other stuff in other agent names, but I think it's still better as the most visible component.)

I'm always open to HOW we accomplish those goals, but....

1) The current system does work. It used to take me a couple minutes to find an obvious duplicate when I needed one for a talk or something, I can't usually do that now.

2) As above, duplicate agents lead to untrustworthy data. Many things in Arctos rely on consistent agent data; this is important.

3) There's a bulkloader which reduces the necessary clicking.

4) Duplicates often go undetected for a long time, and merging them often involves lots of clicks (eg, responding to the notification).

SO, I think we should retain the "abbreviations bad" notice, but I'm happy to expand on it or somehow indicate why it's there. Perhaps just add a direct link to http://handbook.arctosdb.org/documentation/agent.html#creating--maintaining-agents ???

**Comment by droberts49** [comment]
I think having the "abbreviations bad" notice is a good reminder to people as they are entering data and hopefully it encourages collections to provide as much information as possible so as to contribute to better data overall. There are lots of circumstances where you can have the same (passed down in a family) or similar names and they are only distinguished by the middle name (or initial, if that's all you have), title, or suffix. We have material collected in the 1800s and 1900s that was collected by women, but we only know them by their husband's names (Mrs. John Smith) as that was common practice at that time in society and I haven't been able to discover her given name. I've been trying to add other information to the agent record (birth and death dates, associations, addresses, etc) to help distinguish these individuals when I can.

**Comment by Jegelewicz** [comment]
Direct links to the handbook should be implemented all over the place! :-)

I guess I was just hoping that if you have a complete first and last name, the middle initial shouldn't give you the "you might be creating a bad agent" message. It makes me feel bad every time I do it....but I don't know those middle names or else I would use them and I think that initial is important if you have it. Not a big deal, just trying to make it a little less trouble to enter that middle initial.

**Comment by dustymc** [comment]
For next release:

<img width="832" alt="screen shot 2018-03-14 at 10 31 30 am" src="https://user-images.githubusercontent.com/5720791/37419973-ecc38eec-2772-11e8-88f9-daf6e9e94fad.png">

which links to http://handbook.arctosdb.org/documentation/agent.html#creating--maintaining-agents

Perhaps the docs could be updated to clarify that this is begging for info, NOT trying to exclude some abbreviation when that's all you know.

>add other information to the agent record (birth and death dates, associations, addresses, etc) 

THANK YOU!! I still see that stuff popping up in remarks. Ideas on how to stress...

* Use remarks as a last resort, only when more formal data are not possible. Relationship “student of” will stop an agent merger; remark “student of …” will be ignored by automation (and often, people).

... (and everything else!) always appreciated.

Relationships are especially critical on the "Mrs." thing (which seems common in all collections) - resolving those often involves two bits of data eventually coming together

* Mrs....-->spouse of-->some guy
* some name --> spouse of-->same 'some guy'

When those data are in relationships visible from all of the agents, it's pretty easy to check if "Mrs..." and "some name" tend to be in the same places at the same times. When those data are in remarks scattered across (at least) three records, nobody is very likely to notice.
