### ISSUE TITLE
Install of ColfFusion Report Builder fail

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1472]
I need to modify my loan invoices from a new computer. When I try to install ColdFusion 10 Report Builder, I get the following:
![image](https://user-images.githubusercontent.com/5725767/37216373-d6e6a324-2377-11e8-905d-33eeba5f27cc.png)
Any advice?

**Comment by dustymc** [comment]
Google suggests https://forums.adobe.com/thread/1282941
