### ISSUE TITLE
attempt to add media to loan fails

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1473]
When I attempt to add media to a loan I get this:
<img width="960" alt="screenshot 2018-03-09 10 29 02" src="https://user-images.githubusercontent.com/5725767/37220917-560c6e42-2385-11e8-869a-3a4cc0e21ea3.png">

Searched for loan as:
<img width="960" alt="screenshot 2018-03-09 10 32 33" src="https://user-images.githubusercontent.com/5725767/37220920-5b8d616e-2385-11e8-9f7b-81f594b1bdba.png">

**Comment by dustymc** [comment]
picks/getLoan is having a bad hair day...

Use your collection_id (it's 116 for UTEP:Bird) as a workaround.

select collection_id from collection where guid_prefix='UTEP:Bird';

COLLECTION_ID
-------------
	  116

**Comment by Jegelewicz** [comment]
Thanks!

**Comment by dustymc** [comment]
in next release
