### ISSUE TITLE
Can I bulkload thumbnail images and link them to media?

### ISSUE THREAD

**Issue by amgunderson** [ArctosDB/arctos#1475]
This is related to issue 1446. I have successfully uploaded 246 images to TACC and bulkloaded them to there specimen records but thumbnails are not created in this process. Can anyone tell me how to bulkload thumbnail images and link those to their full size image?

**Comment by dustymc** [comment]
these?

https://web.corral.tacc.utexas.edu/UAF/uam_mamm/Lepusamericanus/tb/

**Comment by amgunderson** [comment]
yeah, those! I didn't know they existed. Now how do I attached them to their fullsize parents since I didn't do it at the media bulkload stage?

**Comment by amgunderson** [comment]
We should edit this, http://handbook.arctosdb.org/how_to/How-to-Upload-Media-to-TACC.html, to inform people thumbnails will be created also and they need to be part of the media bulkload step.

**Comment by dustymc** [comment]
I can magic them in. Leaving this open in hopes of documentation.

**Comment by amgunderson** [comment]
I'll try to figure out how to change the how to.

**Comment by amgunderson** [comment]
I updated the how to.
