### ISSUE TITLE
Bulkload Parts

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1476]
I have a few questions about the [Bulkload Parts](https://arctos.database.museum/tools/BulkloadParts.cfm) tool.

1. When use_existing = 1, is the data in any other field except guid_prefix, other_id_type, other_id_number, part_name, and container_barcode ignored?
2. If that is true, would there be a way to change that? As I am adding barcodes to existing parts, there are times when the part disposition should be changed to "in collection" and/or the part condition should be updated. It would be helpful if I could accomplish both adding a barcode and updating these fields at the same time.

**Comment by dustymc** [comment]
>adding barcodes to existing parts

The part bulkloader is almost certainly not the appropriate tool for that. Send me some data and a description of what you want to do with it please.

**Comment by Jegelewicz** [comment]
I have a freezer full of recently barcoded vials some of which still have a disposition of "being processed". I am not quite finished adding the barcodes to the parts, so maybe we should wait until all of the barcodes and parts have been properly associated in Arctos, then we could magic all of the parts attached to cryovial barcodes in that freezer to be "in collection".

**Comment by dustymc** [comment]
Finding parts without barcodes is pretty much always ugly.

Finding parts with barcodes is super easy and 100% accurate. (The barcode exists or it doesn't.)

That sounds like a good plan to me.
