### ISSUE TITLE
Bulk Edit Container

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1478]
Today it appears that two collections are attempting to use Bulk Edit Container and it is causing problems. Any way we can make someone aware if another collection is using the tool or otherwise prevent data overwrites?

**Comment by Jegelewicz** [comment]
Also, would it be possible to implement whatever magic was performed that lets the Bulkload Parts tool ignore the blank line created by Excel here as well?

**Comment by dustymc** [comment]
* make app multi-user 
* somehow prevent cross-user conflicts/overwrites (table-wide primary key on container data??)
* investigate sprinkleability of de-excel-hates-you-ifier

**Comment by Jegelewicz** [comment]
> investigate sprinkleability of de-excel-hates-you-ifier
Yes!!!!PLeeeeeeeeease!!!

**Comment by Jegelewicz** [comment]
Done?
