### ISSUE TITLE
bulkload mistake

### ISSUE THREAD

**Issue by mgoliver** [ArctosDB/arctos#1479]
I bulkloaded 200 specimen records yesterday afternoon under accession UAMb:Herb 2018.3.Cryp. They all had a bunch of locality data, you can see this with the few records still in the bulkloader waiting for me to fix problems, but the 192 records that successfully went through the bulkloader aren't complete for some reason. All that comes up under specimen results for the accession are their ALAAC and nothing else—you can't even click on the records. I'm wondering why this happened and if I need to delete all of these records and try bulkloading them again? Or if it's something that can be easily fixed?
<img width="1375" alt="screen shot 2018-03-14 at 9 00 44 am" src="https://user-images.githubusercontent.com/28404497/37418140-5d275fea-2766-11e8-8829-7a08c8c95f81.png">

**Comment by dustymc** [comment]
An update which required a cache rebuild is still catching up. Everything should clear up within a couple days.

**Comment by mgoliver** [comment]
Thanks, Dusty!

**Comment by dustymc** [comment]
For next release:

<img width="627" alt="screen shot 2018-03-14 at 11 08 16 am" src="https://user-images.githubusercontent.com/5720791/37422296-1f41c9ba-2778-11e8-816a-143eb1db46b8.png">
