### ISSUE TITLE
search on part condition

### ISSUE THREAD

**Issue by KyndallH** [ArctosDB/arctos#1482]
Can I search on part condition? If so, how?

**Comment by KyndallH** [comment]
Also, search on sex from the main search page? After I do a search, there is a field for it but I can't find it from the main search page. 

Not listed under the long list of attributes. 

<img width="357" alt="screen shot 2018-03-16 at 2 31 37 pm" src="https://user-images.githubusercontent.com/16887896/37547510-ee690a64-2926-11e8-8be3-f7a9905960b3.png">

**Comment by dustymc** [comment]
Added part condition to curatorial pane

**Comment by campmlc** [comment]
Thanks, Dusty!!
