### ISSUE TITLE
specific locality in results & top of detail page

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#1483]
@dustymc 
At one point, I know the event associated with manufacture was the event that would be shown in the search results page for the specific locality column (when we have multiple events). It seems that maybe with the last update, this has changed to one of the other events (looks like it got switched to use)? The manufacture event is the most important one for cultural collections search results. Is it possible to have that changed back to the way we used to have it? Now I get a bunch of "unknowns" in the specific locality column when it should be quite diverse.
Thanks.

**Comment by KyndallH** [comment]
Think this may be related but it appears that all mammal observations records got switched to "collection" instead of "observation". 

Aren - let me know if I'm wrong and you want mammal observations to all to say collection. 

<img width="445" alt="screen shot 2018-03-19 at 5 02 23 pm" src="https://user-images.githubusercontent.com/16887896/37630138-a2c22e7e-2b97-11e8-8315-75438302ed6f.png">

**Comment by dustymc** [comment]
@AJLinn I updated the prioritizer - comments at the top of https://github.com/ArctosDB/DDL/blob/master/functions/getPrioritySpecimenEvent.sql.

I'll set your specimens to refresh - check it out and close this if it's doing what it should, please.

You can also turn on JSON Locality and see all events in specimenresults now.

<img width="360" alt="screen shot 2018-03-19 at 9 50 00 pm" src="https://user-images.githubusercontent.com/5720791/37636443-81605526-2bbf-11e8-95d0-1fc596347f94.png">


@KyndallH I'm pretty sure those were entered that way. http://arctos.database.museum/guid/UAMObs:Mamm:192 is as it (probably-maybe) should be, the migration path is in https://github.com/ArctosDB/arctos/issues/1023

**Comment by AJLinn** [comment]
> I'll set your specimens to refresh - check it out and close this if it's doing what it should, please.

it's perfect - thanks Dusty!
