### ISSUE TITLE
Report of all positions (barcodes) not attached to parts in a container

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1484]
This report might be useful to everyone.

You want cryovials for which...

parent.container_type=position
children=NULL

right?

**Comment by dustymc** [comment]
<img width="436" alt="screen shot 2018-03-26 at 11 13 47 am" src="https://user-images.githubusercontent.com/5720791/37924475-ca94b882-30e6-11e8-9471-32730480db7a.png">

<img width="794" alt="screen shot 2018-03-26 at 11 14 13 am" src="https://user-images.githubusercontent.com/5720791/37924508-e174d406-30e6-11e8-9978-009899d80af2.png">
