### ISSUE TITLE
require email address for loan (received by) agents

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#1488]
There are multiple reasons to require an email address for an agent who receives a loan. Overdue notices, compliance notices, etc. Implement a rule where by any agent who is entered into a loan transaction as the 'received by' agent has a valid email address.

**Comment by dustymc** [comment]
Please note that this is slightly different than shipments, which lock addresses through the relationship shipment.xxxx_address_id-->address.address_id. (IOW, shipments use SPECIFIC addresses.)

This relationship will be trans_agent.agent_id-->agent.agent_id-->address.agent_id - I can ensure that an agent has some SOME email address (and that it's marked valid), but I won't be able to tell WHICH address existed at the time of a loan creation and therefore I won't be able to prevent changes or deletion.

I don't think that's much of a problem; ensuring addresses exist before agents are added to loans seems like a sufficient improvement. If there is some reason to lock a specific email for loan agents (or somehow do more than the current structure can support), we can discuss bringing the model in line with whatever ya'll want to do.

**Comment by dustymc** [comment]
Added trigger on table shipment
