### ISSUE TITLE
delete unused localities?

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1490]
#865 is finding and merging quite a few unused localities (in test) - they're probably from someone moving specimens to a different locality, but I'm not sure where they come from.

Can I just delete any unused localities as I find them?

**Comment by campmlc** [comment]
I agree with that.

**Comment by AJLinn** [comment]
Seems fine to me.

**Comment by dustymc** [comment]
Sounds like consensus to me....I updated documentation and added this to the procedure.
