### ISSUE TITLE
adjust verbatim collector to verbatim agent

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#1492]
Would anyone be opposed to adjusting the CTATTRIBUTE_TYPE "verbatim collector" to "verbatim agent" ? 

More often than not, we're entering the name of the maker/artist who only has a name string signed on the piece and we may or may not be able to figure out the actual agent name. By changing this to  "verbatim agent" everyone could enter the qualifying info in the "remarks" and "det. method" fields 
 to indicate which agent type and then use the preferred "unknown" as the agent.

As it is with verbatim collector it adds confusion and I would not have my staff/students use this field.

**Comment by dustymc** [comment]
There's some discussion at https://github.com/ArctosDB/arctos/issues/1239

I have no strong feelings, but the concept is named after the TABLE (collector) for which it's a text-value (vs. data object) replacement, NOT the role of any "collectors" (http://arctos.database.museum/info/ctDocumentation.cfm?table=CTCOLLECTOR_ROLE)

I sort of think that we should somehow attempt to retain that association - the attribute (whatever it's called) applies to things which with more data would be entered into table collector, and the attribute should not be used for things which with more data might appear as Agents outside that table.

**Comment by campmlc** [comment]
Any reason would couldn't have both?

**Comment by Jegelewicz** [comment]
I am in agreement with @AJLinn . Based upon @dustymc 's comments, I suggest we either have multiple attributes: verbatim collector, verbatim determiner, verbatim preparator, verbatim maker, etc. or we change to an ATTRIBUTE of **verbatim agent**, enter the **agent's name** in ATTRIBUTE_VALUE and make ATTRIBUTE_UNITS required with a controlled vocabulary of collector, determiner, preparator, maker, etc.

**Comment by dustymc** [comment]
>ATTRIBUTE_UNITS required 

Attributes with units (which are always required when they can exist for an attribute) force value to be numeric.

**Comment by Jegelewicz** [comment]
Maybe the solution is to change the TABLE (collector) to TABLE (agent_actor), since the name in that table may be a collector, preparator, maker, etc. Which also brings me to determiners? How do they fit? I've definitely had some determiners that ended up as unknown because all I had were three initials, but they aren't listed in the collector table....

**Comment by dustymc** [comment]
I'm certainly not in love with the table name (and it's far from alone in being poorly-named), but it's also much more structurally-specific than "agent who did something."

If some random person wanders in with a specimen, I think most of us would make them a collector. Most of us would probably not put much value in what they think they have - someone in the collection would identify the material and be recorded as the determiner. From that, I would probably make the 3-letter determiners into agents (with verbose remarks) on the assumption that they're "us" and will eventually be resolved to known agents.

Along with labels, there are thousands of remarks in most every table with the same sort of information - "did something, {date}, ABC." I'm sure those initials make perfect sense to 3 or 4 people for a year or two....

**Comment by campmlc** [comment]
I could support "Verbatim agent" with the type of agent in remarks. That
would be simplest and work for the broadest number of collection types, but
with the understanding that the agent type would not be readily searchable
because it would be an open text field with no controlled vocabulary.
I could also support "verbatim_xxx" with each different type of agent.
Either way, I support making this option usable by other collection types
for maker etc.

**Comment by dustymc** [comment]
> making this option usable by other collection types

One of us isn't understanding something. Maker etc data are in table "collector," as attributes those data are in a thing called "...-collector." It's usable by everyone, and always has been. 

This thing is for probably-low-quality data. Absolutely nothing about it is usefully searchable, and results derived from low-quality data can be nothing but low quality. Anyone searching this for anything except VERY specific reasons (eg, to reverse an agent merger) is basically wasting time.

FWIW, this concept was introduced for the bot who merges agents. Every merger gets a....

>>>'Automated insertion from agent merger process - #escapeQuotes(bads.agent_pref_name)# --> #escapeQuotes(bads.rel_agent_pref_name)# for collector role ' || COLLECTOR_ROLE, sysdate'

with any specimen using the "bad" agent.

Can I somehow make this more clear in the definition??

**Comment by AJLinn** [comment]
@dustymc 
How do I fix this given your recommendation of using the syllabics for the preferred name? We do have the literal translation as an aka.

> Agents which may not comply with the Arctos Agent Creation Guidelines (http://handbook.arctosdb.org/documentation/agent.html#general-agent-creation-and-maintenance-guidelines) have been detected. If you are receiving this email, you have either created a potentially noncompliant agent or have manage_collection roles for a user who has created a potentially noncompliant agent. If you are a collection manager, please ensure that everyone with manage_agents rights in your collection has read and understands the agent creation guidelines.
> Please use the contact link at the bottom of any Arctos form if you believe you have received this mail in error, or if you wish to discuss the Arctos Agent Creation Guidelines.
> 
> Please review the following agents and make corrections or additions as appropriate.
> 
> 
> ᐅᓱᐃᑐ ᐄᐱᓕ ᑭᒐᐅ 
>    CreatedBy: Mahriena Ellanna 
>    Problem: no_ascii_variant 
> ᐸᐅᓗᓯ ᑐᓂᓕ 
>    CreatedBy: Mahriena Ellanna 
>    Problem: no_ascii_variant 
> ᑭᒐᐃ 
>    CreatedBy: Mahriena Ellanna 
>    Problem: no_ascii_variant
> 
>

**Comment by dustymc** [comment]
The funky agent code is mostly looking for diacritics, which isn't relevant here (unlike eg "ñ", there is no "close enough ASCII version" of those characters.)

I don't have the capacity to translate - I have no idea if "Kigai" is a useful representation of ᑭᒐᐃ or not - so in the next version, when preferred name is all non-ASCII and there's something in 'aka', 'alternate spelling', or 'full,' the scripts will assume that whatever's in the AKA is a useful translation and not report a potential problem.

**Comment by AJLinn** [comment]
Perfect, thanks.

**Comment by Jegelewicz** [comment]
From Dusty above:

> So, can we do this in documentation?
> 
> Attribute Type: Ya'll tell me.
> 
> Description: Verbatim text string representing an Agent as associated with a specimen. Usage should generally be limited to low-quality agents (e.g., those not likely to become associated with more data) and to data normally recorded in table Collector (under any role in https://arctos.database.museum/info/ctDocumentation.cfm?table=CTCOLLECTOR_ROLE). When known, Collector Role should be entered in Attribute Remarks.
> 
> Edits and/or better ideas greatly appreciated.
> 
> Please do NOT make any code table changes - this is used by application code, I'll sync everything up when we have an acceptable solution.

AWG asked for the following:

Attribute Type: verbatim agent

Attribute Value: Code table - same values as collector type, but add "determiner" and "unknown"

Description: Verbatim text string representing an Agent as associated with a specimen should be placed in remarks. Usage should generally be limited to low-quality agents (e.g., those not likely to become associated with more data) and to data normally recorded in table Collector (under any role in https://arctos.database.museum/info/ctDocumentation.cfm?table=CTCOLLECTOR_ROLE).

**Comment by mkoo** [comment]
Picking up this issue of allowing an agent for a specimen who is NOT and Arctos Agent.
The proposal seems like it could be straightforward if you go with the proposal to adjust CTATTRIBUTE_TYPE: 
need to change  ATTRIBUTE of "verbatim collector" to "verbatim agent", enter the agent's name in ATTRIBUTE_VALUE and make ATTRIBUTE_UNITS required with a controlled vocabulary of collector, determiner, preparator, maker (basically using CTCOLLECTOR_ROLE. which does not currently have determiner)

Is that the correct interpretation?

**Comment by Jegelewicz** [comment]
I think that would work! Just want to make sure that we don't mess with anything given Dusty's request above that we don't change code tables:

> Please do NOT make any code table changes - this is used by application code, I'll sync everything up when we have an acceptable solution.

**Comment by dustymc** [comment]
I remain hesitant to extend this beyond Agents who would normally be linked to specimens via table Collector, and I think the imperfect but consistent naming convention helps clarify that. 

Attributes with units must be numeric: http://handbook.arctosdb.org/how_to/Understanding-Attribute-Errors.html

The merger-bot adds a remark of the format given in https://github.com/ArctosDB/arctos/issues/1492#issuecomment-378273230. Anything different will make these data even less discoverable, should that be possible.

**Comment by dustymc** [comment]
1. The initial problem has been fixed and wasn't actually related to this attribute.
2. The proposal to make this 'verbatim agent' effectively disables the reason for which this attribute was created; with that change, I can't tell why the attribute exists, it becomes a random string presumably representing some agent-like entity that did something vaguely related to something that was at some point somehow related to the record. 
3. The entire point of this attribute is and always has been centered on "NOT an Arctos Agent."
4. The suggestions regarding units on strings are not structurally feasible.

Tentatively closing.

**Comment by Jegelewicz** [comment]
OH I get it - so if we WANT to add a not in Arctos name as a preparator, then we should add "verbatim preparator" to the attribute code table?

**Comment by dustymc** [comment]
>add "verbatim preparator" to the attribute code table

What would you hope to accomplish by that?

The (initial, anyway) point of this was primarily to log agent mergers. That's really only something you'd be interested in after you'd found a record (eg, you don't think it was actually {collector-roled} by AgentID=12345), and you can get the details of that (if my scripts introduced the attribute) from remarks. I don't think more structure would lead to better usability, it would just lead to very confusing data as http://arctos.database.museum/info/ctDocumentation.cfm?table=CTCOLLECTOR_ROLE evolves.

The concept also been useful for initial import; just throw whatever you've got in the attribute, don't clean up or load "collectors" as agents. Remarks is a perfectly suitable mechanism for recording collector role there as well (although I don't think we've ever used it for data which had more than collector_role=collector).

**Comment by campmlc** [comment]
I'm trying to follow this and failing. Can't this just be an interface issue? Keep the table structure as is, change the UI term to verbatim agent? Define verbatim agent for this use case but keep in the Table collector? The issue here is what people see, not what's under the hood.

**Comment by dustymc** [comment]
>The issue here is what people see, not what's under the hood.

This is a data-driven ultra-normalized part of Arctos; those are one and the same.
