### ISSUE TITLE
Add In Barcode data to See All Collection Objects in Container Results

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1497]
The See All Collection Objects in Container function in Manage: Object Tracking: Find Container generates a list of all cataloged items with a barcode scanned into a particular container. There is a column for "In Barcode" in the result list, but this column is blank. Can we get this populated? I'm assuming that the "in barcode" value will be the barcode of the container housing the part, correct?

**Comment by dustymc** [comment]
>I'm assuming that the "in barcode" value will be the barcode of the container housing the part,

It is.

<img width="1014" alt="screen shot 2018-04-16 at 11 25 50 am" src="https://user-images.githubusercontent.com/5720791/38827820-fdc86720-4168-11e8-8221-5a863574cefe.png">

As always, I need details.

**Comment by Jegelewicz** [comment]
I haven't had the issue described above, but there is this - when editing a freezer box, I can see the list of positions on the right, but the barcode field is blank. Shouldn't that also show the barcode in that position?
<img width="960" alt="screenshot 2018-04-16 15 23 31" src="https://user-images.githubusercontent.com/5725767/38836129-5f6e67d8-418a-11e8-8f60-71af2c65721a.png">

**Comment by Jegelewicz** [comment]
Some thing that would be helpful in the screen that Mariel posted would be the barcode label. Could a column be added to show that as well?

**Comment by dustymc** [comment]
Those positions (=children of the container you're editing) don't have barcodes. Here's edit for a container that does container barcoded children (one of the positions)

<img width="481" alt="screen shot 2018-04-16 at 2 43 42 pm" src="https://user-images.githubusercontent.com/5720791/38836879-b4509d4e-4184-11e8-8124-08176b3de15d.png">

**Comment by campmlc** [comment]
I figured out my issue - I was looking at a box of legacy material that had been converted from our old locator. But I do agree with Teresa about the barcode label. That would be much more useful to us than description.

**Comment by dustymc** [comment]
Label is the first column in my screenshot above. ???

**Comment by campmlc** [comment]
Different screen - from See All Collection Objects:

![show all collection objects in container](https://user-images.githubusercontent.com/14808196/38839502-2a016c7c-4198-11e8-893f-4a377eafff81.png)

**Comment by Jegelewicz** [comment]
That is the specimen label not the barcode label.

**Comment by dustymc** [comment]
>specimen label

That is the container label of a leaf node, which is the containers found by the only query that form performs.

```
select * from container where label='MSB Mammals 123882 liver';

CONTAINER_ID PARENT_CONTAINER_ID CONTAINER_TYPE
------------ ------------------- ------------------------------------------------------------
LABEL
------------------------------------------------------------------------------------------------------------------------
DESCRIPTION
------------------------------------------------------------------------------------------------------------------------
PARENT_INS
----------
CONTAINER_REMARKS
------------------------------------------------------------------------------------------------------------------------
BARCODE
------------------------------------------------------------------------------------------------------------------------
  PRINT_FG	WIDTH	  HEIGHT     LENGTH NUMBER_POSITIONS LOCKED_POSITION
---------- ---------- ---------- ---------- ---------------- ---------------
INSTITUTION_ACRONYM
------------------------------------------------------------
     2922167		18714135 collection object
MSB Mammals 123882 liver

2017-09-18


									   0
MSB


1 row selected.
```

>Well, that's confusing! I have a container in each of those positions that is barcoded and it just feels like those barcodes should show up the positions listed. Could this page also show me the container in each position? 

I don't think I'm following. The form is showing the structure of how the containers have been arranged.

I think maybe you're asking for a special view (eg, that works with box-->position-->vial-->part), but container positions already does that.

???

>The current set-up makes it appear that there is nothing in the box from this view.

There are a bunch of positions?? That form just shows children. There's a "view in tree" link that will show more context.

>Does that also mean that you cannot use "Move all children of this container to scanned barcode" to move all the vials from one freezer box to another?

That just moves children - if the vials are in the box they'll move, if the box contains positions they'll move. Anything that moves brings its children (vials, parts, etc.) with it.

**Comment by campmlc** [comment]
Can you clarify whether move children to a box with pre existing positions
will duplicate positions?

**Comment by dustymc** [comment]
I obviously have no idea what will duplicate positions!

The form moves children, so without anything else in play you could end up with 200 (or more...) positions in a box. It's not been possible to put more than NUMBER_POSITIONS positions in a container for a while, but it WAS possible to put positions into a container with NULL NUMBER_POSITIONS, and since nothing is bigger than (or smaller than, or the same as) NULL I think that may have been part of what was causing the "duplicated" positions thing. You should no longer be able to put any positions into a container without a value in NUMBER_POSITIONS, which should fix that leak.

I don't think that's a problem, but try it out (preferably in test) and let me know how if you manage to make something "interesting."
