### ISSUE TITLE
error when adding media to loans

### ISSUE THREAD

**Issue by AdrienneRaniszewski** [ArctosDB/arctos#1504]
When attempting to upload a pdf to a loan record, we get this message.

UNEXPECTED ERROR: {"PUTFILE":{"ErrorDetail":"I/O Exception: Connection reset","Mimetype":"Unable to determine MIME type of file.","Filecontent":"Connection Failure","Statuscode":"Connection Failure.  Status code unavailable.","Responseheader":{},"Text":true,"Charset":"","Header":""},"MIME_TYPE":"application/pdf","MD5":"ec
bb7cc8b7aba610246d639165c52a07","FILENAME":"19103.pdf","STATUSCODE":"Con","MEDIA
_URI":"https://web.corral.tacc.utexas.edu/arctos-s3/AdrienneR/2018-04-19/19103.pdf","MEDIA_TYPE":"text","PREVIEW_URI":""}

**Comment by AdrienneRaniszewski** [comment]
update: This morning Mariel was able to load media to a loan from her computer (on the MSB network) and from the very same computer and browser that Marissa was using. I was **unable** to load media from my computer or the one that Marissa was using. I got the same error message. Marissa is not here to try again, but the problem started for her on Tuesday. She's been uploading media without a problem for several weeks before this.

**Comment by dustymc** [comment]
That still sounds like MSB/UNM messing with network traffic, although I'm not sure how or why anyone would do that.

Are you using https://arctos.database.museum or http://arctos.database.museum? MAYBE there's some way that the secure connection is related, but I don't think so.

There's a very old probably-unrelated S3 bug involving large files and new buckets - can you try loading a small file?

I can try to upload if you send me the file - there's some chance it's somehow related to an individual file, I suppose, although I can't image how.

Whatever's in your javascript console any time you get an error is likely to be useful as well.

>several weeks

https://github.com/ArctosDB/arctos/issues/1446#issuecomment-382768651

**Comment by campmlc** [comment]
The odd thing is that it is related to my login vs Adrienne's and Marissa's
login. Same computer, same file.

**Comment by dustymc** [comment]
>login

That's the "new buckets...small file" bit above. An S3 bucket is created the first time a user loads a file, and there's some possibility that this is related to the age of "your" bucket+filesize.

You can see buckets (as directories) at https://web.corral.tacc.utexas.edu/arctos-s3/

**Comment by campmlc** [comment]
If it is a bucket issue, then that is a problem TACC would need to resolve?
I looked at the link, and there is no file size data displayed for each
user.

**Comment by dustymc** [comment]
Possibly we'll need to get TACC involved, but it's probably easier to just try it with a smaller file and see what happens. I don't know what the definitions of "new" and "large" are, and nobody who's created a bucket (eg, uploaded their first file to this system) seems to have this problem - I don't see how knowing the size of existing buckets would answer anything. 

Total disk is shared and we have a little over 4000TB free at the moment - this certainly isn't related to absolute filesize.

**Comment by campmlc** [comment]
[19103.pdf](https://github.com/ArctosDB/arctos/files/1933323/19103.pdf)

Here is the file that I was able to load but that Adrienne and Marissa were not.

**Comment by campmlc** [comment]
I guess I don't understand how buckets work. Both Adrienne and Marissa have
previously loaded files with this tool before without any problems,a s
recently as two weeks ago when this problem first started. I don't see
either of their names on the "bucket list".

**Comment by dustymc** [comment]
>  weeks

> #1446 (comment)

If SOMEONE was able to load the file, it's not a problem with the file.

**Comment by campmlc** [comment]
So what is the next step to track this down?

**Comment by dustymc** [comment]
This is fixed for next release.
