### ISSUE TITLE
search attributes for a range of values

### ISSUE THREAD

**Issue by amgunderson** [ArctosDB/arctos#1506]
I would like to find beluga with a numeric age of 5-25, or a vole with a tail length of 20-30, etc. Can I do that already? If not, is that possible to make work?

**Comment by dustymc** [comment]
<img width="663" alt="screen shot 2018-04-20 at 1 10 46 pm" src="https://user-images.githubusercontent.com/5720791/39071532-4be4e38a-449c-11e8-9132-853978a7a099.png">

http://handbook.arctosdb.org/documentation/attributes.html#searching-with-attributes

>numeric_age=3-5 years | {value converted to days} BETWEEN 1095.726 and 1826.21 days


<img width="440" alt="screen shot 2018-04-20 at 1 10 00 pm" src="https://user-images.githubusercontent.com/5720791/39071529-4896daa8-449c-11e8-89cc-80c88f0dbf47.png">



http://arctos.database.museum/SpecimenResults.cfm?scientific_name=Delphinapterus&scientific_name_scope=currentID&scientific_name_match_type=startswith&numeric_age=5-25%20years

**Comment by dustymc** [comment]
This is spillover from https://github.com/ArctosDB/arctos/issues/1466, and I'm still not quite sure what you're suggesting.

**Comment by amgunderson** [comment]
That works for me. I'm no longer confused, thanks.
