### ISSUE TITLE
Markdown in Agent Remark?

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#1508]
The cultural collections uses the Agent Remarks field as a location to put biographical information about agents who are represented in our collections. This can often be quite extensive. As we continue to improve our ability to document the people who make our collections important, it would be really handy to be able to have paragraphs in the Agent Remark field. For example, see the very long single paragraph in this agent record for John E. Thwaites: http://arctos.database.museum/agents.cfm?agent_id=21313700

If we could have the ability to do some formatting in this field, which I think is implemented via Markdown? (sorry for not knowing the proper terminology) it would be really handy. Being able to have paragraphs, maybe even italics if we want to reference a publication someone is known for, would be very useful. Is that something that is possible?

Thanks for considering this enhancement.

**Comment by dustymc** [comment]
No objection/sounds useful from my perspective, except...

>reference a publication

That's best done via relationships. We can add something more formal, or Media works well as relationship duct tape (stick anything to anything....).

Ditto dates - as remarks, they're just text. As "status" dates, we can do stuff with them (eg, "This agent wasn't born yet, are you SURE about the collecting date?" warnings).

**Comment by AJLinn** [comment]
Having just entered a long bit of info in a few agent records, hoping to bring this up again. The issue was moved to the Agents Committee back in 2018 but I'm sorry to say I'm not sure who is on the Agents Committee and I see we have no progress in tasks for that committee. What needs to happen to approve and implement this enhancement?

**Comment by Jegelewicz** [comment]
I'm wondering if remarks is appropriate - maybe we need something more formal for a bio like this? Honestly, it seems that Wikipedia would be a better place for this kind of biographical info with a link to the Wiki page in the url section of the agent page. The only problem there is that apparently url addresses don't show up on the public agent page. You can also add a link back to Arctos from the wiki (I'm gonna do this for Artie tomorrow!) which could drive people to Arctos more often.

[Artie Wiki](https://en.wikipedia.org/wiki/Artie_L._Metcalf)
[Artie Arctos](http://arctos.database.museum/agent.cfm?agent_id=21268299&agent_name=Artie%20L.%20Metcalf)

We currently don't have anyone heading up the Agents Committee - interested?

**Comment by dustymc** [comment]
Wikipedia/wikidata definitely has a much broader impact, if that can be made to work. I could pull content in from there as well.

>url addresses don't show up on

Sure they do, but might be cached.

<img width="326" alt="Screen Shot 2019-09-17 at 5 12 59 PM" src="https://user-images.githubusercontent.com/5720791/65088504-830fee00-d96e-11e9-8814-fe4c7a3b635c.png">

**Comment by Jegelewicz** [comment]
See also https://github.com/ArctosDB/arctos/issues/3918#issuecomment-919247287

**Comment by AJLinn** [comment]
> Wikipedia/wikidata definitely has a much broader impact, if that can be made to work. I could pull content in from there as well.

Not everyone (certainly very few Alaska Native individuals) have Wikipedia pages. Moreoften these are pulled from a random smattering of sites, books, oral history recordings, or interviews. A biography field would be great as an alternative, especially if it has markdown formatting.

**Comment by dustymc** [comment]
>A biography field 

How about media? A link to something like a Google Doc (wikidata page, pastebin, whatever) would provide formatting, a place to share editing, etc., etc.

I'd suggest just creating wikipedia pages, but that community is difficult. I've never tried wikidata, not sure if it comes with the same barrier or not.

And I still don't object to something local, remarks or otherwise, but if this can be somehow "bigger than Arctos" then I think that's worth exploring.

**Comment by campmlc** [comment]
I agree with a biography field with markdown - and the ability to link to Wikipedia pages if they exist.

**Comment by AJLinn** [comment]
> How about media? A link to something like a Google Doc (wikidata page, pastebin, whatever) would provide formatting, a place to share editing, etc., etc.

I've done this for some, but again, it involves clicking another link if you know that it's there (amidst the other media that might be associated with that agent). I really prefer something that is immediately visible on the agent summary page.

**Comment by Jegelewicz** [comment]
I think we can add a "simple HTML" docuement to the handbook and have people use that.  See the remarks in my agent https://arctos.database.museum/info/agentActivity.cfm?agent_id=21300608 go to edit it and you can see the HTML I used to get it to look that way. Line breaks and links are easy, so are headers.

**Comment by acdoll** [comment]
> if that's a typo

It was, thanks.

**Comment by Jegelewicz** [comment]
Needs documentation and a Simple HTML tags cheat sheet.

**Comment by Jegelewicz** [comment]
Added info and links to best practice document. - https://handbook.arctosdb.org/best_practices/Agents.html

**Comment by Jegelewicz** [comment]
@AJLinn I added just a little HTML to Thwaites - https://arctos.database.museum/info/agentActivity.cfm?agent_id=21313700 so you can see what it involves.
