### ISSUE TITLE
Attribute sorting for specimen results view

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1509]
Can we have the attributes in Specimen Results display in order first by 1) attribute name, and then next by 2) attribute date? 
Not sure I can see a pattern in the current display - is it by order in which they were loaded?
This is important tracking age/sex/repro changes for mark/recapture specimens with multiple events.

![image](https://user-images.githubusercontent.com/14808196/39158788-3d710402-471f-11e8-8029-ff544ed73d40.png)

**Comment by dustymc** [comment]
What specimen are you looking at?

**Comment by campmlc** [comment]
https://arctos.database.museum/guid/MSB:Mamm:302257 and

https://arctos.database.museum/guid/MSB:Mamm:302362

as examples

**Comment by dustymc** [comment]
thanks - should be fixed for next release, hopefully tonight.

(FYI, the code was IF mammal THEN huge-complicated-mess ELSE simple table ordered by attribute type then date. The huge complicated mess should be ordered now as well.)
