### ISSUE TITLE
Quirky geolocate message

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#1510]
My student (user: mrellanna) was cataloging an item in the data entry page today. She tried to use the geolocate tool, having entered the Higher Geography and the Specific Locality (Nunivak Island), and when she clicked on the geolocate button, the map wouldn't open (using http), then when trying https:// she got this:
![54628893024__9b1cf80a-8fdd-4902-b764-45a66ba27ca1](https://user-images.githubusercontent.com/17605945/39211417-fd0bc26e-47b7-11e8-9c4c-c4123bec1941.jpeg)
and then this:
![54628895128__7516c028-5126-42c1-aac6-95035fb99456](https://user-images.githubusercontent.com/17605945/39211430-0637921e-47b8-11e8-8ec5-79f90a9705e5.jpeg)
"Intruder Alert"

What is different today from yesterday and last week when she was able to use this tool during data entry? She's using Firefox and tried in both http: and https: 
She also tried Chrome but it gave her the same issue as the https:// error.
Thanks!

**Comment by dustymc** [comment]
Try a hard reload (shift-refresh, probably). GeoLocate moved to a new server, I swapped some things out last night, she's probably got old code cached in her browser.

**Comment by AJLinn** [comment]
Ahh, sounds good. I'll have her try that this afternoon.
Thank you!

**Comment by AJLinn** [comment]
Mahriena cleared the cache in her browser and tried again - geolocate worked. Thanks for the tip!
