### ISSUE TITLE
Add parts to Herp collections

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1511]
Please add the following parts to Herp Collections

brain (frozen)
heart, liver, muscle (frozen)
heart, liver (95% ethanol)
heart, liver, muscle (95% ethanol)
eye (formalin)
heart (95% ethanol)

**Comment by campmlc** [comment]
Added - please verify all OK.

**Comment by Jegelewicz** [comment]
Will pass along to Vicky - thank you!

**Comment by Jegelewicz** [comment]
@campmlc still need brain (frozen) Thank you!!!!
