### ISSUE TITLE
Error when adding media

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1512]
When adding media to some specimen records I am encountering this error:

<?xml version="1.0" encoding="iso-8859-1"?> <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"> <head> <title>500 - Internal Server Error</title> </head> <body> <h1>500 - Internal Server Error</h1> </body> </html> 

Screenshot
![media error](https://user-images.githubusercontent.com/5725767/39277091-56a712a0-48a9-11e8-9e74-80d55fd66563.JPG)

**Comment by dustymc** [comment]
Please send it along if you have a specific file that won't load - the only limitation SHOULD be your network speed.
