### ISSUE TITLE
UK higher geography

### ISSUE THREAD

**Issue by catherpes** [ArctosDB/arctos#1516]
Need to add these counties/higher geography:

https://en.wikipedia.org/wiki/Anglesey
https://en.wikipedia.org/wiki/Bardsey_Island

There is also no option for England, with no lower geography

**Comment by dustymc** [comment]
Europe, United Kingdom, England, British Isles, Britain is "plain ol' England."

I created

Europe, United Kingdom, Wales, British Isles, Anglesey 
Europe, United Kingdom, Wales, Gwynedd, British Isles, Bardsey Island
