### ISSUE TITLE
Plant phenology standard

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1518]
Let’s build this in for plant attributes?

https://www.frontiersin.org/articles/10.3389/fpls.2018.00517/full

**Comment by dustymc** [comment]
There are lots of ways to do this in Arctos -  create attributes (and accompanying code tables) for each property in the standard, create an attribute which accepts XML as data, create an attribute which accepts the URL of an XML file as data, create an attribute which flags the existence of rdf/xml and link via Media, etc. 

Example data, a description of where they came from/how they're created, and some info on how they'd be used is probably a decent starting point.

**Comment by Jegelewicz** [comment]
Closing for lack of interest.
