### ISSUE TITLE
media search is problematic

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#1519]
Trying to search for media by a cataloged_item relationship. 

Here is an audio recording that is related to a cataloged item:
http://arctos.database.museum/media/10303335

In the Media search, I selected 'shows cataloged item' in relationship and MVZObs:Bird:129 as the value. Nothing found. I tried the same but with %MVZObs:Bird:129%, nothing found. I tried in key words as "match phrase" and multiple things found, including this one and 10 others (MVZObs:Bird:1290, MVZObs:Bird:1291, etc.). Preceding that with "=" doesn't find anything.

Dusty wrote: Looks like that's searching catalog number and ID for some weird reason - Issue with better ideas, please....

upper(mr_cataloged_item1.cat_num) || upper(mr_cataloged_item1.scientific_name) like '% MVZOBS:BIRD:129%' 

will find it - eventually - and 2922 more...

I guess that one can click on media details specimen by specimen to get the data, but there has to be a better way. Give me all records with audio for X - cataloged item data and media details. Not sure how that would work, but worth a discussion. Add to the customize results options?

**Comment by campmlc** [comment]
Yes, I had a similar problem searching for all Rausch records with
associated media, specifically with media type "multi-page document" and
keywords "ledger" from the specimen search page.
It would be good to be able to search for all records that have been tagged
in Media from the specimen search page. Is this possible?

**Comment by dustymc** [comment]
There are couple of distinct but related issues here.

1) What should be displayed as summary data from media details, specimen results, etc.? Getting data isn't a problem, but transporting (and perhaps compiling, but we can fix that) them will become one at some point. A Media record can be linked to any number of things - cataloged items, projects, etc. - and there is essentially no limit on what those things may contain. Trying to push everything we know about every cataloged item in a project to a user's browsers is going to clog the pipes. "Basic catalog data" (whatever that is) for 100 specimens (a typical search result) as "media metadata" is probably going to clog the pipes for some users.

2) What should the "relationship" box accept/match with "shows cataloged_item" relationships? (The stuff in (1), maybe.)

I'm glad @campmlc  showed up - host/parasite (and predator/prey and everything else) relationships present a similar situation. We have lots of data, it's all linked together, it's easy enough to get it, but THEN WHAT?

TAGs is probably best addressed as a separate issue. We've talked about auto-creating Media from them (a TAG to a specimen would create a "shows cataloged_item" relationship, and the TAG would essentially refine that relationship), which would at least make this involve one less complicated problem.

**Comment by dustymc** [comment]
add to "manage" - link to media linked to all specimens in result
(and publications too)

**Comment by dustymc** [comment]
add labels to specresults media json

**Comment by acdoll** [comment]
Seems like the 'shows cataloged item' just wants a number w/o GUID prefix. Perhaps simply adding a dropdown to select the collection would solve this problem?

**Comment by dustymc** [comment]
Search now accepts GUID; closing
