### ISSUE TITLE
Add part to Herbarium Collections

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#1520]
Hi there,
Can we add a part for herbarium collections:

thin layer chromatography

Thanks!
Vicky

**Comment by dustymc** [comment]
That sounds like a technique - what is the nature of the material? 

Is there something suitable in https://arctos.database.museum/info/ctDocumentation.cfm?table=CTSPECIMEN_PART_NAME? (I don't see anything)

I will need a definition to add authority values as well.

**Comment by mvzhuang** [comment]
Hi Dusty,
Sorry for the confusion. Teresa and I talked over this and I got
clarification and have confirmed from our herbarium curator that the
"parts" are drawn paper copies of the chromotography plates and not the
actual plates.  In that case, I think I will just have the copies scanned
and added as media instead of having it added as a part. I don't know if
other herbariums will have actual plates or not.

However, I do believe that we should add a new plant attribute instead, to
make the results easily accessible. Teresa suggested "TLC compound" and it
can be defined as "Identified compound present in a given mixture, using
the thin-layer chromatography technique"

I believe this attribute should be a free text value.

I don't see any other attribute types that might be similar in the code
tables.

Thanks,
Vicky

**Comment by Jegelewicz** [comment]
@DerekSikes who from the UAM Herbarium could chime in here?

**Comment by StefanieBond** [comment]
Sounds good to me. I have not come across any actual paper copies of TLC plates here at ALA.   Best, Steffi.

**Comment by campmlc** [comment]
Done 8-6-2018.
