### ISSUE TITLE
iframe url does not have permision to interact with me

### ISSUE THREAD

**Issue by KyndallH** [ArctosDB/arctos#1521]
I'm trying to enter specimens and I keep getting this error message over and over again. I hit okay a few times and it'll let me move forward but then appears on the next screen.

<img width="1227" alt="screen shot 2018-05-09 at 4 13 25 pm" src="https://user-images.githubusercontent.com/16887896/39845832-8c9b3502-53a4-11e8-8bdd-3809ab6e0b06.png">

<img width="1191" alt="screen shot 2018-05-09 at 4 13 51 pm" src="https://user-images.githubusercontent.com/16887896/39845833-8fb89798-53a4-11e8-9ea3-5f085a646095.png">

**Comment by dustymc** [comment]
Chrome? geolocate moved a few weeks ago, you may have old code cached - try a hard reload. If that doesn't work, send me the contents of your javascript console.

**Comment by KyndallH** [comment]
Yup - chrome.
Me speak no computer.

I googled "hard reload" and did the following:
<img width="449" alt="screen shot 2018-05-09 at 4 44 47 pm" src="https://user-images.githubusercontent.com/16887896/39846516-921212fe-53a8-11e8-82ae-c494cb073d5f.png">

It didn't work. Is there a better/another way to do a hard reload.

I'll need more explicit instructions on this "send me the contents of your javascript console" to do that one. 

I have had this problem for awhile BUT it was never this bad. I clicked the okay a few times on that error message and it would go away. Now it won't.

**Comment by dustymc** [comment]
OK, fine, I'll fire up Chrome...

shift-reload seems to work.

alt/option + splat + j should open the console.

Do whatever you do to get the error (I'm not getting it, whatever that's worth), copy whatever's in the console, paste it here or mail it to me.

**Comment by AJLinn** [comment]
Hey @KyndallH you might be able to clear the cache in your browser also... we were having an issue associated with the new geolocate and that fixed it for Mahriena (different issue but possibly same cause?)

**Comment by dustymc** [comment]
@mkoo  that's just Google being creepy. (And where'd you find a 2G network?!?)

This is CORS-like, but it's in my code to sanitize incoming data. This is almost certainly just Chrome being Chrome, and is why the Firefox recommendation exists.

The only other possibility I can see is that someone is actually manipulating network traffic - either on the network (https to arctos should stop it if so) or somewhere on the machine (browser, browser extension, virus, etc.).

**Comment by KyndallH** [comment]
I cleared the cache in the browser - still didn't fix it. 

Here are the results from the alt/option + splat + j should open the console:

<img width="564" alt="screen shot 2018-05-10 at 9 05 48 am" src="https://user-images.githubusercontent.com/16887896/39882817-5f577a64-5431-11e8-98c7-0497787726d0.png">

<img width="1698" alt="screen shot 2018-05-10 at 9 05 43 am" src="https://user-images.githubusercontent.com/16887896/39882853-8164eb78-5431-11e8-9539-cf19ed0ec8e1.png">

<img width="1502" alt="screen shot 2018-05-10 at 9 05 17 am" src="https://user-images.githubusercontent.com/16887896/39882855-83b9047c-5431-11e8-8c33-0b9f2b1e46dd.png">

**Comment by KyndallH** [comment]
Still getting the error message but different note under the results from the alt/option + splat + j console:

<img width="1223" alt="screen shot 2018-05-10 at 10 49 56 am" src="https://user-images.githubusercontent.com/16887896/39888030-3134e770-5440-11e8-8908-50dfe0a9c1c3.png">

<img width="555" alt="screen shot 2018-05-10 at 10 49 38 am" src="https://user-images.githubusercontent.com/16887896/39888059-40d10f1a-5440-11e8-9ee5-f9fafe2e3b99.png">

**Comment by dustymc** [comment]
OK, it looks like the CORS thing was just google being creepy and unrelated then.

Did you try with https://arctos.database.museum/? 

Did you try with FireFox?

If the cache-clearing actually worked and you're not asking for something other than what's specified, this almost has to be network traffic being manipulated. That could be your network (if so you should get this in any browser, but https should work by encrypting the stream), your browser or some extension running in your browser, or something intercepting traffic on your computer.

**Comment by KyndallH** [comment]
It was an extension that was running on chrome. :/ Turned off all the extensions and it stopped.

**Comment by bryansmclean** [comment]
Adding to the thread - I also received this error today but turning off one of my Chrome extensions also fixed the issue (in my case it was the Zotero extension)
