### ISSUE TITLE
tissue sample quality continued

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#1522]
Two questions/issues re: tissue sample quality:

1) Can we add attributes as part of the bulkloader? It would be good if we know the quality to be able to add the attribute at the time that we bulkload specimens with tissue.

2) How/where do we make available the definitions for the different quality values so that they are applied semi-consistently (both for those entering data and those using the samples)?

**Comment by dustymc** [comment]
>bulkloader

<img width="305" alt="screen shot 2018-05-09 at 5 59 38 pm" src="https://user-images.githubusercontent.com/5720791/39846847-c70fb358-53b2-11e8-875d-6a939a316551.png">

See also https://github.com/ArctosDB/arctos/issues/1294

>definitions

http://arctos.database.museum/info/ctDocumentation.cfm?table=CTTISSUE_QUALITY

I can sprinkle the little "define" links around, and always happy to talk in general about getting definitions in front of users.
