### ISSUE TITLE
User Interface - Bulk Edit Container

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1525]
After uploading a file and validating using the Bulk Edit Container tool the user is greeted with a validation table and this message:

> Validation complete. Carefully recheck the data and _click here to finalize the upload_. Pay special attention to the "note" column - these are not "errors" but information here may be an indication that you are about to make a huge mess. 

I suggest that we change this verbiage to the following to make it more user friendly:

> Validation complete
> 
> Please review the data in the staging table below. Pay special attention to the "note" column - these are not "errors" but information here may be an indication that the edit you are about to make is not exactly correct or what you want. Instructions for completing the upload or making changes to this data are found at the bottom of the staging table.

Then at the bottom of the staging table we present the following:

> A green button with "upload data" The data in the staging table appears as expected. The upload can be finalized and the data deleted from the staging table.
> 
> A yellow button with "delete data" The data in the staging table contains errors or does not appear as expected. Delete it from the staging table without uploading.

This allows the user to scroll through the staging table and make a decision after reviewing the data without having to scroll back up to the top.

**Comment by Jegelewicz** [comment]
Oh and pretty please! Can we make this tool ignore the blank line inserted by Excel?

**Comment by dustymc** [comment]
done
