### ISSUE TITLE
User Interface - Bulkload Parts

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1526]
After uploading a file using the Bulkload Parts tool the user is greeted with a validation table and this message:

> Caution: Duplicate existing data cannot be detected from here. This form will create duplicate parts. Make sure the data you are trying to load do not already exist.
> 
> You have 91 records in the staging table.
> 
> Load more records
> 
> validate records
> 
> You have manage_collection, so you can "take" records from people in your collection.
> NOT ALL OF THESE ARE NECESSARILY YOUR SPECIMENS!!
> Use this with great caution. You may need to coordinate with other curatorial staff or involve a DBA. Check for records entered by people in your collection(s)
> 
> delete all of your data from the staging table
> 
> Download as CSV 

I suggest that we change this verbiage to the following to make it more user friendly:

> **Caution:**
> Duplicate existing data cannot be detected from here. This form will create duplicate parts. Make sure the data you are trying to load do not already exist.
> 
>You have manage_collection, so you can "take" records from people in your collection which means that not all of the data in this table are necessarily the records on which you were working.
> 
>You have 91 records in the staging table. If this number is higher than expected, please coordinate with other curatorial staff or involve a database administrator before loading or deleting them. you can delete your records individually by checking the Delete box in the far left column and then selecting the "delete checked records" button at the bottom of the table.
> 
> You must validate your data before it can be loaded. Please review the data. You will be able to validate or delete the data when you reach the bottom of the table.

At the bottom of the table we display:

> green button with "validate records" - The data is mine or I have been given permission to validate others' data.
> 
> yellow button with "exit without action" - There appears to be data other than my own in the table and I need to exit to investigate.

My ideas about this would change if by selecting "delete all of your data from the staging table" I would ONLY delete my data and leave others' in the table. Also - do we need to have this here or can we just go straight to validation? This tool seems to make you do this step twice.

After data validation, the user sees this:

>  Caution: Duplicate existing data cannot be detected from here. This form will create duplicate parts. Make sure the data you are trying to load do not already exist.
> Potential duplicates detected. Sort by collection_object_id 
> 
> You have 91 records in the staging table.
> 
> Load more records
> 
> validate records
> 
> You have manage_collection, so you can "take" records from people in your collection.
> NOT ALL OF THESE ARE NECESSARILY YOUR SPECIMENS!!
> Use this with great caution. You may need to coordinate with other curatorial staff or involve a DBA. Check for records entered by people in your collection(s)
> 
> delete all of your data from the staging table
> 
> Download as CSV 

I suggest we change this to the following:

>  **Caution:**
> Duplicate existing data cannot be detected from here. This form will create duplicate parts. Make sure the data you are trying to load do not already exist.
> 
> Potential duplicates detected. A sort by collection_object_id may help you sort them out. To sort by a column header, just click the column header you wish to sort by. Clicking twice will reverse the order of the sort
> 
> You have manage_collection, so you can "take" records from people in your collection which means that not all of the data in this table are necessarily the records on which you were working.
> 
> You have 91 records in the staging table. If this number is higher than expected, please coordinate with other curatorial staff or involve a database administrator before loading or deleting them. You can delete your records individually by checking the Delete box in the far left column and then selecting the "delete checked records" button at the bottom of the table.
>  
> Please review the records in the staging table. All records must have valid in the status field before the data will load. You can remove records individually  by checking the Delete box in the far left column and then selecting the "delete checked records" button at the bottom of the table. If you wish to delete all of the records the option to do so is found at the bottom of the staging table.
> 
> At the bottom of the staging table we present the following:
> 
> If the upload records button is not here, there are records without the status of valid. You can choose to delete the individual records and proceed to load the remaining records, or you can delete all of the data in the staging table, make changes and try the bulkload again.
> 
> green button with "upload records" - The data appears correct and is mine or I have been given permission to upload others' data. [this would only be visible if all record statuses are valid]
>  
> yellow button with "exit without action" - There appears to be data other than my own in the table or another issue that I need to exit to investigate.
>  
> orange button with "download CSV" - Download a CSV file with this data so that I can review and/or make changes before attempting another upload.
>  
> grey button with "delete all records" - The data is incorrect or does not appear as expected and is mine or I have been given permission to delete others' data.

These suggestions might not be the best as this tool might be modified to be somewhat more like the Bulk Edit Container tool. It would be great if we could make these tools a bit more consistent. If I knew more about how they work, I might make better suggestions, but this is what I've got for now! Thanks!!

**Comment by dustymc** [comment]
>Also - do we need to have this here or can we just go straight to validation? 

That's related to...

>knew more about how they work

There are essentially two classes of these tools: single-user and multi-tenant. 

The bulk edit container thing is single-user - you upload some stuff and it either works or it doesn't, that's it. Those are simple to write, they were all that was necessary when Arctos was smaller, and they (probably!) remain all that's necessary for something like editing containers - that's not something that should be allowed to accumulate, very few people can do it, etc.

Bulkload parts is multi-tenant, which necessitates some other functionality. "All" refers to "stuff you can see" - the verbiage should be clarified. Every operation redirects back to the "splash" screen - there is no logical "when bla happens then auto-do blah" because there's a lot of diversity in how the app is used. (You want to load now I think, I use it to stash "extras" that will eventually need loaded for new collections, students write there via the data entry extras thing, etc., etc., etc.) The multi-user apps also generally can work iteratively - validating 500K parts just can't work through a browser and I deal that that scope occasionally, so those usually have some sort of "do THIS for records where status is THAT" (vs. single-user loaders which again just work or fail).

THANKS for the feedback!
