### ISSUE TITLE
Is there a list of nonprinting characters somewhere?

### ISSUE THREAD

**Issue by amgunderson** [ArctosDB/arctos#1527]
We are trying to bulkload art and got this, check constraint (UAM.CK_BL_ATR_VALUE_6_NOPRINT) violated. I need a list of nonprinting characters to weed them out of bulkload file.

**Comment by amgunderson** [comment]
nevermind, I figured it out.

**Comment by atrox10** [comment]
Can we reopen this, are the two big NOPRINT error characters for the bulkloader these:  tab and paragraph -carriage returns?

**Comment by dustymc** [comment]
>list

The list of non-printing characters may be infinite - I don't really know how the PRINT class is implemented in Oracle, where the check is made.  'Not in POSIX character class “PRINT”' (http://handbook.arctosdb.org/documentation/understanding-errors.html#ck) is the best I can do.

@atrox10 if you're asking about common characters, it depends on the source. From keyboards, TAB and RETURN are probably most common. Anything that's been through Windows editors is likely to have a bunch of linefeeds, and whatever tool you're using may treat them similar to return - or not. Filemaker inserts vertical tabs everywhere; those get ignored, displayed like tabs, displayed like linefeeds, and probably some other stuff in various tools. The thing that's supposed to ring a bell on word processors - ASCII(7) - is a common delimiter in webservices and sometimes gets left behind - it's usually invisible, but sometimes gets displayed as whatever the tool uses for "I can't display this."  If you need to know specifics, send me data (in UTF8 - and converting from unknown character sets sometimes introduces weird stuff) and I can identify them. If you just want to know where they are (or want them gone), the Arctos tools (Reports/DataServices/FindAndReplaceNonprintingCharacters) can help.

And note that things can break characters without breaking this rule. ü goes in to Excel and Ã¼ comes out, for example - the results are PRINT class characters so Arctos is happy, but the data are still busted.
