### ISSUE TITLE
Hide attribute lines in Data Entry screen.  Bug?  

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#1528]
We are able to adjust the number of lines  on the data entry screen by using the "Customize Form" feature for PARTS, OTHER IDs and AGENTS.  But when we use it for ATTRIBUTES, it continues to show 10 lines regardless of how many lines we designate as SHOW or HIDE.  Is this a bug or operator error?

**Comment by dustymc** [comment]
Fixed
