### ISSUE TITLE
Unable to update parts with barcodes

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1531]
When attempting to add a barcode to a part, I receive the following message:

An error occurred while processing this page! 
Error Executing Database Query. 
[Macromedia][Oracle JDBC Driver][Oracle]ORA-01407: cannot update ("UAM"."COLL_OBJECT"."CONDITION") to NULL
This message has been logged. Please contact us with any information that might help us to resolve this problem.

This has happened to me with three different parts in the last two days. The most recent example was with this part: 25864402 attempting to add this barcode:  A2ASV

Interestingly, the part bulkload tool seems to be working just fine....

**Comment by dustymc** [comment]
You're trying to update a condition to NULL - it's a required field.

**Comment by Jegelewicz** [comment]
But all I am doing is adding the barcode as follows:

![capture](https://user-images.githubusercontent.com/5725767/40128766-b0cac582-58ef-11e8-9fd9-212a826215c7.JPG)

I don't have an opportunity to select a condition - one is already there...

**Comment by Jegelewicz** [comment]
Never mind. I don't know how these were entered originally without a condition, but I can add them as I go....

**Comment by dustymc** [comment]
>entered originally without a condition

Click the "history" link.

<img width="573" alt="screen shot 2018-05-16 at 9 01 16 am" src="https://user-images.githubusercontent.com/5720791/40128912-c4216332-58e7-11e8-968f-9a861238521e.png">

"Things you can't see" and "without" aren't synonymous to Oracle. 

I'd have to look at code to be sure, but this is probably an experiment in auto-cleaning. We've talked about doing that everywhere at times, but I generally find "something goes in, something else comes out" more confusing than the alternatives - it seems to be what spawned this Issue, for example.
