### ISSUE TITLE
attribute code table editor and quotes (was:Update CTCULTURE to include art collections.)

### ISSUE THREAD

**Issue by amgunderson** [ArctosDB/arctos#1533]
I tried to make the culture of origin attribute values table, CTCULTURE, accessible to art collections but these values would not respond to clicking "update", I clicked and nothing happened. I updated other values without a problem. These need to be updated to allow art collections, Athabascan, Deg Hit'an; Athabascan, Dena'ina; Athabascan, Gwich'in; Athabascan, Tsilhqot'in; Eskimo, Cup'ig; Eskimo, Cup'ik; Eskimo, Yup'ik; and Nisga'a.

**Comment by dustymc** [comment]
I SQLed that in. Editing title of this.
