### ISSUE TITLE
REQUIRE data quality collection contact with an email?

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1534]
I'm testing https://github.com/ArctosDB/arctos/issues/1529 with recently-created taxonomy. Some of the potentially-problematic names are used by UNM:ES, which isn't getting annotation email for some reason (no contacts or the contacts don't have valid email, probably).

https://github.com/ArctosDB/arctos/issues/1454
https://github.com/ArctosDB/arctos/issues/1347
https://github.com/ArctosDB/arctos/issues/1208

are semi-related.

The annotations are http://arctos.database.museum/info/reviewAnnotation.cfm?action=show&atype=taxon&guid_prefix=&reviewer_comment=&submitter=dlm&reviewer=

The specific problem is an easy fix - @dperriguey can you set up a data quality contact with an email for UNM:ES please? - but in general can/should we somehow require a contact, and if so how?

**Comment by Jegelewicz** [comment]
I think it should be a requirement! As to how - I'm not sure I have the tech savvy to make any kind of informed contribution, but here goes....all user roles for a given collection are frozen unless there is a data quality contact? Yeah, I'm an enforcer....

**Comment by dustymc** [comment]
I like it, but I don't know how to (easily) do it - several of us have access to collections for which we don't have that info, and some of those collections are not active (https://github.com/ArctosDB/new-collections/issues/30). This may be another reason to formalize that status.

Lacking better idea, if you have manage_collection access to a collection without a data quality contact you will see this (instead of the normal redirect back to where you were) after your initial login. I'll leave this issue open for a while in case anyone has better ideas.

<img width="1367" alt="screen shot 2018-05-17 at 10 03 15 am" src="https://user-images.githubusercontent.com/5720791/40192554-8f8717d4-59b9-11e8-8e39-0258ee405e00.png">

**Comment by Jegelewicz** [comment]
Well, I think that works for now!
