### ISSUE TITLE
Project URls and editing titles are way too easy to break

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#1540]
Right now the project URL's are constructed from their title; however, if project titles are changed in the future, then there will be broken links within Arctos. 

Adding to the redirect table is a possibility but seems cumbersome for Projects. What's the best way to handle this for users? Info button  on the project edit page next to the project title box with a link to the redirect table? Or allow editable URLs so users can write smaller urls that will be permalinks?

How hard would programming the latter be?

At the very least, we need to add a note to the Handbook on this. (note to self!)

**Comment by dustymc** [comment]
>broken links within Arctos

MAYBE for an hour/as long as something's cached. There will be broken links TO Arctos, but not so much internally.

>seems cumbersome

How often do project titles change?

>editable URLs

We could do that as a suggestion perhaps, but I can't trust users to provide something that works as a URL.

That would take some programming and structural changes, and I'm not sure what it would solve if users can edit it too.

Perhaps a better method would be what we've done elsewhere, build URLs from something users can't change (primary keys) - http://arctos.database.museum/publication/10006319 or http://arctos.database.museum/media/10277427. The information-bearing URLs seemed like a good idea at the time, but I'm not sure they're really useful (and as you mentioned, some of them are a mite unwieldy - http://arctos.database.museum/project/ancient-ecology-of-mammalian-communities-using-stable-isotopes-destructive-and-dental-microwear-texture-analysis-dmta-nondestructive-assessing-mammal)

**Comment by Jegelewicz** [comment]
Yes to

> Perhaps a better method would be what we've done elsewhere, build URLs from something users can't change (primary keys) - http://arctos.database.museum/publication/10006319 or http://arctos.database.museum/media/10277427.

**Comment by mkoo** [comment]
I like that idea, basically some kind of permalink that can be used without
being dependent on the project title makes the most sense.
thanks

**Comment by campmlc** [comment]
I agree.

**Comment by dustymc** [comment]
multi-page documents should be updated as well

**Comment by dustymc** [comment]
Done for next release. "Old-style" URLs should continue to work, but will 301 to /project/{project_id}.
