### ISSUE TITLE
"Estate of" or "xxx Estate"

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#1541]
I have a few bequests that I'm processing this year and I just noticed that we don't seem to have an agent standard for entering the name of estates. They seem to all be listed as organizations, but some are "Estate of Grace Schaible" while others are "Luther Hess Estate".

Any preferences? If we did "Estate of..." they would all group together while if the Estate went last, the living agent and their estate would be listed sequentially.

Thoughts?

**Comment by mkoo** [comment]
Decision to use "XXX Estate" as the usual format for entry

**Comment by ccicero** [comment]
Agents updated to change those with 'Estate of...' so that the name is first.
