### ISSUE TITLE
Clone handler not working in reports?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1542]
The MSB Bird loan handler stopped working, but it continued to work with the MSB Mamm handler. Tried multiple times to use the Clone Handler tool to create a new bird handler from the mammal one. Nothing worked. After an hour, I gave up and just copied the SQL from the mammal to an older bird handler which wasn't sorting correctly, and that did work. 
Questions:
1) Why do forms that have been working fine for years just stop working? Form has not been edited.
2) Why do we have a Clone Handler option if it doesn't work?
3) If it does work, maybe we could have some documentation on how to make it work, to minimize lost hours and much frustration.

**Comment by campmlc** [comment]
Tried cloning the one I just created that worked (MSB_Bird_loan_list), and made no changes whatsoever.
New report: Clone_Of_MSB_Bird_loan_list_1527554996
When I tried to print the report created using the cloned handler, I get this message:
	An error occurred while processing this page! 
Error Executing Database Query. 
[Macromedia][Oracle JDBC Driver][Oracle]ORA-00923: FROM keyword not found where expected
This message has been logged. Please contact us with any information that might help us to resolve this problem.

But as mentioned in first post, I can correct this by copying and pasting the SQL from a functional report. Is the cloning process introducing an error?

**Comment by dustymc** [comment]
Clone is not handling multiple singlequotes properly - elevating to bug.

If you'll provide enough information that I can re-create whatever you're seeing, I should be able to tell you why something isn't working.

**Comment by campmlc** [comment]
This was a pre-made form in the drop-down  on the loan page. Not accessed
from Reports.

**Comment by dustymc** [comment]
Singlequotes are properly handled in next release
