### ISSUE TITLE
Correct spelling of Sabaramamua to Sabaragamuwa

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#1543]
Higher geography: Asia, Sri Lanka, Sabaramamua, Sri Lanka

The province is misspelled.  It should be Sabaragamuwa.  The reference for the entry has it spelled correctly: http://en.wikipedia.org/wiki/Sabaragamuwa_Province

This impacts multiple collections, so should the correction be made by someone from the working group?

**Comment by dustymc** [comment]
Goferit. That'll send out the authority notification, which everyone should be carefully reviewing. If the bad spelling is somehow useful (eg, we're not the only one to come up with it) you can add it to search terms so it can continue to find specimens.

**Comment by sharpphyl** [comment]
Done.  Thanks.

**Comment by sharpphyl** [comment]
Added the misspelling to the search terms, but the only place Google finds it is Arctos so I'll delete it if no one complains after you send out the authority notification.
