### ISSUE TITLE
where did "Create Media" link go?

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#1544]
I'm trying to add a media from another holding institution that is related to two objects in my collection.
Photo: http://imgzoom.cdlib.org/Fullscreen.ics?ark=ark:/13030/kt7870211v/z1&&brand=oac4
Objects: http://arctos.database.museum/guid/UAM:EH:0656-0001 and http://arctos.database.museum/guid/UAM:EH:0658-0003

Formerly, I would create the media from the Search --> Media/Documents --> [create media] link and then relate the new media & thumbnail to the objects from the edit media page.

But now it's gone with only an option to Attach/Upload media...
![mediass](https://user-images.githubusercontent.com/17605945/40738359-d4002618-63ef-11e8-8d7c-c013de8e7a77.jpeg)

Can we please bring it back or can you explain to me how to so the same thing? This is an important tool for us to link to other holding institutions, driving traffic to other collections and showing connections between organizations. It should work like the video that is attached to the  0656-0001 object detail page, which takes you out of Arctos and to (in this case) Alaska's Digital Archive.

**Comment by dustymc** [comment]
I'll rebuild and replace that option.

**Comment by dustymc** [comment]
There will be a "create Media from URL" option in the next release.
