### ISSUE TITLE
clone record

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#1547]
I'm trying to clone a record (http://arctos.database.museum/guid/UAM:EH:UA91-001-0003) because this catalog number was assigned to an item as a found-in-collection number and I found the actual accession. Rather than just changing the number in the record (the object is numbered with the UA91 number) I wanted to create a copy of the record with the original catalog number and then link between the two.

I went into Other IDs, clicked [clone record] and selected option 2, and all I got was the spinning wheel and the "hold tight" message... for an hour.

Kyndall's worked immediately. What is wrong with my collection or record that I can't clone it?
Please help.
@dustymc

**Comment by dustymc** [comment]
Looks like singlequotes in attributes are not being properly escaped and the error handler is a little fragile.

**Comment by AJLinn** [comment]
I went ahead and just created a new record for the UA71-069-0001 catalog number and made a relationship to the wrong UA91-001-0003 number as "same individual as" and the links aren't working either way. Is this connected or a new issue?
(new record, original number) http://arctos.database.museum/guid/UAM:EH:UA71-069-0001
(old record, incorrect number) http://arctos.database.museum/guid/UAM:EH:UA91-001-0003

**Comment by dustymc** [comment]
The code table was missing a trailing colon - I fixed it, the links should work now.

<img width="708" alt="screen shot 2018-05-31 at 11 12 08 am" src="https://user-images.githubusercontent.com/5720791/40799834-805dbbcc-64c3-11e8-91a2-2e02b2dfba51.png">

<img width="693" alt="screen shot 2018-05-31 at 11 12 14 am" src="https://user-images.githubusercontent.com/5720791/40799840-852bec3c-64c3-11e8-9206-4445d16730dd.png">

The new record will pick up the summary data in a day or two.

You can also redirect by encumbering (they'll both still exist for you) or deleting one record, if that's somehow useful - http://handbook.arctosdb.org/documentation/redirect.html.

**Comment by dustymc** [comment]
fixed in next release

**Comment by AJLinn** [comment]
Hey Dusty - Karinna seems to be having a similar problem.
UA1972-075-070 is the record she's trying to clone. 
When selecting option one:

> ERROR: Error Executing Database Query. - [Macromedia][Oracle JDBC Driver][Oracle]ORA-06550: line 1, column 7:
PLS-00201: identifier 'CLONE_CATALOGED_ITEM' must be declared
ORA-06550: line 1, column 7:
PL/SQL: Statement ignored


When selecting option two, it just spins...

**Comment by dustymc** [comment]
> This option will fail for collections which do not use integer catalog numbers. 

http://handbook.arctosdb.org/documentation/catalog.html#catalog

**Comment by AJLinn** [comment]
I think she has to be logged in in order to see these options, yes?
But if the [clone this record] link only works for integer catalog numbers, that would explain the problem. I think she's going to just create the record in data entry and then link them as "same individual as"
