### ISSUE TITLE
Add depth as a search field in "find locality" function

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#1550]
The "find locality" screen includes three fields to search for specific elevation.  

It would be helpful to have the same fields available for "depth" (water depth):  minimum depth, maximum depth and depth units.

**Comment by sharpphyl** [comment]
Any chance this could happen on the next release or is there an issue around doing this?  Thanks.

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/1705 is blocking this

**Comment by dustymc** [comment]
...but #1705 hopefully won't go quite this deep, so depth should be in the next release (which I hope to get out in the next couple of days).
