### ISSUE TITLE
UUID bulkloader entry

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#1553]
We need a clear path to load additional parts and attributes and identifiers from the data entry page dropdown through the various bulkloaders. Please make a link to search all records across bulkloaders to mark to load.

**Comment by ccicero** [comment]
Also a table in the extras column, and clearer description of what needs to be added, with a check box, also check box at top, and uncheck if you put in twice.

**Comment by ccicero** [comment]
This is from "Extras" in Bulkload Browse and Edit - takes you to all pending objects in bulkloader. But we don't want to see everything - only the extras, please.

**Comment by ccicero** [comment]
Please send email to notify about extras.
Also, move the box for adding and checking extras from data entry up higher so we can see it.

**Comment by dustymc** [comment]
Summary:

- add "pre-approved/autoload" functionality to all bulkloaders linked to specimen data entry via "extras"
- remove all bulkloader info from enter/bulk/B&E-->extras (but indicate if the specimen is still in the bulkloader==won't load)
- remove records that don't have extras from enter/bulk/B&E
- format the "extras" better; make them human-readable
- add 'autoload this' and 'autoload everything' checks to enter/bulk/B&E
- add by-collection 'pending extras' email notifications

**Comment by dustymc** [comment]
BrowseAndEdit-->Extras - is extra data for specimens which are still in the bulkloader - I'm ignoring it for now.

There is a new form in test at...

<img width="285" alt="screen shot 2018-06-20 at 10 01 37 am" src="https://user-images.githubusercontent.com/5720791/41673254-3522f2c2-7471-11e8-97be-1e6d805b74de.png">

which look like...

<img width="1237" alt="screen shot 2018-06-20 at 10 04 15 am" src="https://user-images.githubusercontent.com/5720791/41673277-51e08938-7471-11e8-8747-056d01cd2416.png">

for each "extras" table. 

http://arctos-test.tacc.utexas.edu/Bulkloader/loaded_specimen_extras.cfm

Please review, feedback greatly appreciated.

Next step: do something with status="autoloaod" in each of the "extra" bulkloaders.

**Comment by dustymc** [comment]
Autoload now autoloads, or errors.

A nightly notification will be sent to 

* users who have 'linked to bulkloader' data in any of the component-loaders
* users who have 'autoload%' data in any of the component-loaders (the above, with errors)
* users who have manage_collection for collections of the above users.

Example email:

<img width="1158" alt="screen shot 2018-07-18 at 8 28 37 am" src="https://user-images.githubusercontent.com/5720791/42891617-9bff2a48-8a64-11e8-80a8-0d3f48e133d1.png">

This should go to production tonight.

TODO: 

* ScheduledTasks/dataentry_extras_notification.cfm @ nightly
* ScheduledTasks/autoload_extras.cfm @ hourly

**Comment by dustymc** [comment]
This is in prod at

<img width="329" alt="screen shot 2018-07-26 at 6 33 04 am" src="https://user-images.githubusercontent.com/5720791/43265516-cb739d42-909d-11e8-90c8-a18922dc25ae.png">

https://arctos.database.museum/Bulkloader/loaded_specimen_extras.cfm

**Comment by campmlc** [comment]
Question on this: When the uuids are loaded, does the other identifier go away or stay in the other ID field?
When we find a record like the following, how do we know that all the information has been successfully loaded through the extras tool, vs something still out there?
https://arctos.database.museum/guid/MSB:Mamm:301725

**Comment by dustymc** [comment]
The UUID is permanent unless someone deletes it - I can't know if it's a link to more data in Excel on your desktop or something.

From the email:

> Data for specimens which have been entered are available at EnterData/Bulkloader/ExtrasForLoadedSpecimens or the individual bulkloaders.
