### ISSUE TITLE
Search All on Portals Page

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#1554]
Get rid of lengthy collection descriptions on Portals page and go to basic list of collections with a box that people can type the first few letters of a collection to select which info they want to see.

**Comment by ccicero** [comment]
Create a table that has institution name, number of collections, logo, and total number of records. When you click on the institution name you go to detail page for those collections. Add a map that does the same thing.

**Comment by acdoll** [comment]
The JOIN ARCTOS NOW!! link should be at/near top of page

**Comment by dustymc** [comment]
From #1581 

>We have so many institutions that the list on the left side of the page is longer than one screen. The list doesn't scroll with the page, so no matter how badly I want, I cannot click UTEP...

**Comment by dustymc** [comment]
>Get rid of lengthy collection descriptions on Portals page and go to basic list of collections with a box that people can type the first few letters of a collection to select which info they want to see.

Example? Seems like a kludgy replacement for splat-F but I think it made sense at the meeting...


>add a map 

I need coordinates for that. Should we add that to table collection? If so, as required? 


>get rid of extraneous stuff at bottom of list. Make sure everything is on arctosdb.org first.

Can someone take this on? Maybe just expand https://arctosdb.org/about/details/ecosystem/?

I'll add help wanted.

I'm particularly attached to the statement on vaporware - the lingo can go, but the idea that this stuff exists and is used by a whole bunch of collections for mundane everyday stuff is important (and, frighteningly, rare in this community).

I removed the links from the sidebar, and hopefully convinced the sidebar to resize better on small screens.

>Make content appear in dropdowns to save space.

<img width="1096" alt="screen shot 2018-10-09 at 9 58 54 am" src="https://user-images.githubusercontent.com/5720791/46685291-faa79b80-cba9-11e8-8fc0-8514d6d24757.png">
<img width="931" alt="screen shot 2018-10-09 at 9 59 02 am" src="https://user-images.githubusercontent.com/5720791/46685297-fed3b900-cba9-11e8-90c0-e0975768f531.png">

>Create a table that has institution name, number of collections, logo, and total number of records. When you click on the institution name you go to detail page for those collections. Add a map that does the same thing.

Demo? In the sidebar??


>The JOIN ARCTOS NOW!! link should be at/near top of page

<img width="645" alt="screen shot 2018-10-09 at 10 01 09 am" src="https://user-images.githubusercontent.com/5720791/46685415-4eb28000-cbaa-11e8-92ad-efcb9aa89709.png">

**Comment by acdoll** [comment]
@dustymc simple formatting issue on the Portals Page: every collection that comes alphabetically after MVZ appears to be a sub-collection of MVZ

**Comment by campmlc** [comment]
Dusty, while we are revisiting this issue regarding Carla's request, can we
implement the original issue request? I agree with Carla and Teresa.

**Comment by dustymc** [comment]
@acdoll  no way that'll turn out to be simple.... I'll look at it ASAP.

@campmlc  elaborate please

**Comment by campmlc** [comment]
See first two posts on this issue plus following.

**Comment by dustymc** [comment]
@acdoll simple after all - there was malformed HTML in the collection description of MVV:Bird (half a link to https://arctosdb.org/data/). @ccicero @mkoo
