### ISSUE TITLE
Make the collections list on the specimen search page be auto-fill instead of check-list

### ISSUE THREAD

**Issue by atrox10** [ArctosDB/arctos#1555]
On the http://arctos.database.museum/SpecimenSearch.cfm
Arctos specimen search, can we make it a auto-fill box instead of listing all the collections with check-boxes?
If someone is logged in, then only their collections can appear in the list so I like the list for that. But when you aren't logged in (and for visitors) it would be better if it was auto-fill instead of such a long check list.

**Comment by dustymc** [comment]
This thing.

<img width="626" alt="screen shot 2018-06-08 at 8 19 21 am" src="https://user-images.githubusercontent.com/5720791/41166260-b12c15aa-6af4-11e8-957a-94c68df42c5a.png">

Considerations:

* Whatever's there must support multiple values
* "select all" and "select none" are functionally identical and that's probably confusing (but it saves hundreds of clicks when you need to select all-but-three)
* https://github.com/ArctosDB/arctos/issues/1067 (recently closed, but I'm not sure there was a resolution??) may change something here - probably not
* "select all herp collections" would be neat, or maybe super confusing (parasites are cataloged in parasite and insect collections, snakes are cataloged in herp and reptile collections, etc.)
* do-something-with-type would be great - I scroll more there than in all of the rest of Arctos combined
* I do (mostly...) like the hierarchical institution-->collections arrangement

UI/widget/tool/whatever suggestions, anyone?

**Comment by jtgiermakowski** [comment]
I see this as a way to get everyone to think in terms of institutional
acronym and collection "GUID"... eventually we can condition people to
think and know codes like we all do for airports and airlines, right ? (AA
915 from FRA to SFO anyone?)

So ideally, going along with Carla's suggestion, auto-filter would be
great: type in "MSB" to be able to select from MSB or "Herp" to select from
:Herp collections, or "MSB:Bird" to quickly select just that.

that would be great!

Tom

2018-06-08 9:28 GMT-06:00 dustymc <notifications@github.com>:

**Comment by dustymc** [comment]
going with standard select multiple for lack of better ideas
