### ISSUE TITLE
Publication/Project search page

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1559]
Can we add a search by collection code to this page? I'd like to see all of the publications and/or projects linked to a specific Arctos collection. Is that possible?

**Comment by dustymc** [comment]
<img width="257" alt="screen shot 2018-06-11 at 9 35 24 am" src="https://user-images.githubusercontent.com/5720791/41244743-cff358dc-6d5a-11e8-82a3-4801a958e693.png">


I can change or add to that - what exactly do you mean by "linked"?

**Comment by Jegelewicz** [comment]
Well, there you go - "Cites Collection" just didn't click in my brain, but that is what I was looking for....

Sorry, I've had a cold and I'm a bit foggy.
