### ISSUE TITLE
Arctos PSA - On creating barcodes with MS Word

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1560]
Microsoft tells you how here: https://msdn.microsoft.com/en-us/library/hh745903(v=office.12).aspx

I also used this sarcastic tutorial: https://www.clearlyinventory.com/how-to-print-barcodes-with-excel-and-word

**Comment by KyndallH** [comment]
Those seem much more difficult than what I've done.

You can simply download a barcode font, add it to your font list, and type up whatever barcodes you want. 

<img width="484" alt="screen shot 2018-06-11 at 1 14 26 pm" src="https://user-images.githubusercontent.com/16887896/41257471-70485760-6d79-11e8-83df-a0ae72d05e30.png">

The following directions are under ["How to Start Object Tracking in Arctos"](http://handbook.arctosdb.org/how_to/How-to-start-object-tracking.html)

Printing barcodes using Microsoft Office Word
Download a barcode font
Google Barcode font for office or something along those lines
One place you can find them is at: http://www.fontspace.com/category/barcode
Select a Code39, works best with most barcode scanners

Add barcode font to your Microsoft Office Word:
PC: https://www.wikihow.com/Add-Font-in-Microsoft-Word
Mac: https://www.popsugar.com/tech/How-Install-Fonts-29788862

**Comment by Jegelewicz** [comment]
I tried that and could not get our scanners to read them. With the MS version you can generate QR codes, which our scanners could read just fine.

**Comment by Jegelewicz** [comment]
Did that - still didn't work. Also checked that Word wasn't auto-bolding stuff because of the *

The QRs do not have the human readable text as part of the barcode, but because you are using mail merge you can use the same field twice, once as text and once using the barcode feature. It's cool because you can also size the barcode. We made it pretty small and it still worked great!

[NK_page_BARCODE.pdf](https://github.com/ArctosDB/arctos/files/2092035/NK_page_BARCODE.pdf)

**Comment by Jegelewicz** [comment]
I also like the fact that you don't have to download anything...it's just part of Word.

**Comment by Jegelewicz** [comment]
Added to documentation - https://handbook.arctosdb.org/how_to/Barcode-Supplies.html
