### ISSUE TITLE
Barcodes AND Labels in Specimen Parts and Part Location Download and Add to Loan forms

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1561]
I have a similar issue to #1524 in that our part labels contain the unique part ID, but I need to see both the label and the barcode of the ultimate child container (e.g. cryovial) in order to know which to add to a loan.
When I get an Add to Loan list, I can't see the part label with the part ID - I only see the barcode. And when I download part locations, I only see the label and not the barcode. I need to see both the barcode and the label in all three views.
Is it possible to do this just for the terminal child container?

What I see from Part (Freezer)Location Download:
302171 | NEON.MAM.D14.L1384 | blood | DGR-13][Rack 6][NEON-6   DGR18149][DGR18320][38][SRER.20160922.L1384.B]

What I see in Add to Loan form:
MSB:Mamm:3021715 Events blood (frozen) (in collection) [A4TIX] Remark: Instr.: Subsample?: 

What I see in PLPath in Specimen Record:
Museum of Southwestern Biology←Genomic Resources←326 Freezer Room←DGR-13←Rack 6←NEON-6 DGR18149←DGR18320←38←SRER.20160922.L1384.B

I don't have a way in the loan form to pick the correct part for the loan with just the barcode info.

**Comment by Jegelewicz** [comment]
Yes, please!

**Comment by campmlc** [comment]
We bumped this in priority because it is slowing down a bunch of major loan
requests. This would  speed up the process of locating loan objects and
adding them to a loan and make it easier and more accurate. Thanks.

**Comment by dustymc** [comment]
> Is it possible to do this just for the terminal child container?

Possible, probably, somehow, but I don't think it's very practical.

Adding the whole stack is fairly easy, and contains everything so we won't have to make minor adjustments (which often aren't so minor) forever.

```
UAM@ARCTOS> select getContainerParentage(18925328) from dual;

GETCONTAINERPARENTAGE(18925328)
------------------------------------------------------------------------------------------------------------------------
[ MSB ] Museum of Southwestern Biology (institution):[ DGR ] Genomic Resources (collection):[ DGRCERIA326 ] 326 Freezer
Room -80 (room):[ DGR12750 ] DGR-07-OLD (freezer):[  ] 8 (position):[ DGR18363 ] DGR18363 (freezer rack):[  ] 5 (positio
n):[ DGR18002 ] DGR18002 (freezer box):[  ] 20 (position):[ A4TIX ] SRER.20160922.L1384.B (cryovial):[	] MSB:Mamm:30217
1 blood (frozen) (collection object)
```

You have barcodes - is there some reason you're not using them to add the loan items?

**Comment by campmlc** [comment]
The whole stack might be OK - I have to parse the data out anyway.

Many specimens are barcoded, but some are not.  Currently I have to
download the location path for my students to find the samples, and the
download currently does not include the barcodes if there is also a label.
Students use the spreadsheet to indicate whether or not a sample has been
located, whether there was sufficient content for a loan, and  to scan a
new barcode if one is added. If all the barcodes were included in the
original download along with the label, then it would immediately be
obvious which specimens have already been barcoded, and I could then use
the same spreadsheet, modified, to bulkload the loan items.

**Comment by dustymc** [comment]
>download part locations

Is that..

<img width="261" alt="Screen Shot 2019-04-16 at 6 06 53 PM" src="https://user-images.githubusercontent.com/5720791/56253760-91ca4000-6072-11e9-8f98-d34bbee683aa.png">

<img width="169" alt="Screen Shot 2019-04-16 at 6 08 07 PM" src="https://user-images.githubusercontent.com/5720791/56253764-a1498900-6072-11e9-846e-a8338c540d46.png">

<img width="109" alt="Screen Shot 2019-04-16 at 6 08 15 PM" src="https://user-images.githubusercontent.com/5720791/56253770-a4dd1000-6072-11e9-9e6b-de03ae7b875c.png">

or something else?

**Comment by campmlc** [comment]
Yes. Note that the terminal container has a label but no barcode.

**Comment by dustymc** [comment]
I updated the flatten-thing.

I am not comfortable working on the loan item form on a production box - that code is integrated too deeply, any mistakes are likely to take everything down. Not that I actually make mistakes of course, but in theory...

You should be seeing http://handbook.arctosdb.org/documentation/container.html#display-format in "plpath" and everywhere else similar data are needed. We can change the format as necessary, but there was a lot of discussion involving an unambiguous way to reference containers as strings. That needs a dedicated issue, not hidden back here.

**Comment by Jegelewicz** [comment]
> Not that I actually make mistakes of course, but in theory...

Honestly, do ANY of us make mistakes? ;-)

**Comment by dustymc** [comment]
Loan form done in PG
