### ISSUE TITLE
timeout suggestions

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1564]
Move the stuff in the timeout page to - uhh, somewhere.

**Comment by dustymc** [comment]
Here's the current timeout message.

<img width="1191" alt="screen shot 2018-06-18 at 9 46 45 am" src="https://user-images.githubusercontent.com/5720791/41550088-94b211b4-72dc-11e8-93bd-e3aad7579f8e.png">


How do we make it better?

**Comment by ccicero** [comment]
Adding to this comment the issue of timing out when searching by "Any Geographic Element" and "Any taxon, ID, common name" - people are trying that and it's not working, then they get frustrated and contact us.

**Comment by Jegelewicz** [comment]
> How do we make it better?

Start with this: [How to write a great error message](https://medium.com/@thomasfuchs/how-to-write-an-error-message-883718173322)

> ![capture](https://user-images.githubusercontent.com/5725767/41941752-26c5a1fa-795a-11e8-9cc0-7ec176bef45e.JPG)
> Write an alert message that describes the alert situation clearly and succinctly. An alert message such as “An error occurred” is mystifying to all users and is likely to annoy experienced users. (…) Write informative text that elaborates on the consequences and suggests a solution or alternative. Give as much information as necessary to explain why the user should care about the situation. (…) Informative text is best when it includes a suggestion for fixing the problem. (…) Express everything in the user’s vocabulary. An alert is an especially bad place to be cryptic or to use esoteric language, because the arrival of an alert can be very unsettling. (…) It’s a good idea to avoid using OK for the default button. The meaning of OK can be unclear even in alerts that ask if users are sure they want to do something. For example, does OK mean “OK, I want to complete the action” or “OK, I now understand the negative results my action would have caused”?
> 

And on that note, here is my suggestion:

Get rid of the flaming computer - it is distressing. Instead just put the Arctos bear so that it is easy for a user to see that the alert is coming from Arctos.

Message text:
**Arctos query time is limited and your search has timed out. Please refine your search terms and try again.**

For more information on searching Arctos read [Conducting a Search](http://handbook.arctosdb.org/how_to/How-to-Search-for-Specimens.html).

Suggestions for refining your search include:
 - search for a specific taxon
 - search a more refined geographic area by either drawing a bounding box on the map or adding geographic search terms
 - search by a specific collection or collector

If you are experiencing time out issues after attempting to refine your search, please contact us.

[Return to Arctos Search](http://arctos.database.museum/SpecimenSearch.cfm)

**Comment by dustymc** [comment]
> people are trying that and it's not working, then they get frustrated 

Alternatively, they search for an island group in the obvious place and don't find anything because we did something weird (https://arctos.database.museum/geography.cfm?feature=Rat%20Islands) or search by taxonomy and get part of the woodfrogs (https://arctos.database.museum/SpecimenResults.cfm?scientific_name=Rana%20sylvatica&scientific_name_scope=currentID&scientific_name_match_type=startswith) and never find the rest (https://arctos.database.museum/SpecimenResults.cfm?scientific_name=Lithobates%20sylvaticus&scientific_name_scope=currentID&scientific_name_match_type=startswith).

The "any..." search terms absolutely cause problems, but they also address bigger (to some users, some of the time, anyway) problems.

There was mention (from @campmlc I think??) of somehow providing the timeout info earlier, but I'm not sure how or where we'd do that.

While we're making errors better.....

A search that finds nothing "errors" with...

<div>
			Your query returned no results.
			<ul>
				<li>Check your form input, or use the Clear Form button to start over.</li>
				<li>
					If you searched by taxonomy, consult <a href="/taxonomy.cfm" class="novisit">Arctos Taxonomy</a>.
					Taxa are often synonymized and revised, and may not be consistent across collections. Previous Identifications,
					which are separate from the taxonomy used in Identifications, may be located using the scientific name
					"include all IDs" option.
				</li>
				<li>
					Try broadening your search criteria. Try the next-higher geographic element, remove criteria, or use a substring match.
					Don't assume we've accurately or predictably recorded data.
				</li>
				<li>
					 Not all specimens have coordinates, and the spatial query tool will not locate all specimens.
				</li>
				<li>
					Use dropdowns or partial word matches instead of text strings, which may be entered in unexpected ways.
					"Doe" is a good choice for a collector if "John P. Doe" didn't match anything, for example.
				</li>
				<li>
					Read the documentation for individual search fields (click the title of the field to see documentation).
					Arctos fields may not be what you expect them to be.
				</li>
				<li>
					Check <a href="/info/ctDocumentation.cfm" target="_blank">code table documentation</a> and
					<a href="/info/ctDocumentation.cfm?table=CTATTRIBUTE_CODE_TABLES" target="_blank">attribute data definitions</a> documentation for terms,
					vocabulary, and standards.
				</li>
				<li>
					<a href="/googlesearch.cfm">Try our Google search</a>. Not everything in Arctos
					is indexed in Google, but it may provide a starting point to locate specific items.
				</li>
				<li>
					<a href="/contact.cfm">Contact us</a> if you still can't find what you need. We'll help if we can.
				</li>
			</ul>
		</div>




404 (not found) errors try to find similar forms and offer a "did you mean...", include a Google site search, then



	<p>
		If you followed a link from within Arctos, please <a href="/contact.cfm">Contact Us</a>
	 	with any information that might help us resolve this issue.
	</p>
	<p>
		If you followed an external link, please use your back button and tell the webmaster that
		something is broken, or <a href="/contact.cfm">Contact Us</a> telling us how you got this error.
	</p>

	<p><a href="/taxonomy.cfm">Search for Taxon Names here</a></p>
	<p><a href="/SpecimenUsage.cfm">Search for Projects and Publications here</a></p>
	<p>
		If you're trying to find specimens, you may:
		<ul>
			<li><a href="/SpecimenSearch">Search for them</a></li>
			<li>Access them by URLs of the format:
				<ul>
					<li>
						#Application.serverRootUrl#/guid/{guid_prefix}:{catnum}
						<br>Example: #Application.serverRootUrl#/guid/UAM:Mamm:1
						<br>&nbsp;
					</li>
				</ul>
			</li>
		</ul>
		Some specimens are restricted. You may <a href="/contact.cfm">contact us</a> for more information, or
		<a href="/info/encumbrances.cfm">view a summary of encumbrances</a>.
		<p>
			Occasionally, a specimen is recataloged. You may be able to find them by using Other Identifiers in Specimen Search.
		</p>
	</p>


and failed Media URIs provide a path to search and try to guess intent


	Media are stored on the fileserver only temporarily. Use <a href="/MediaSearch.cfm">MediaSearch</a> to find them
			<cfif pm.recordcount gt 0>
				or try these links:
				<ul>
				<cfloop query="pm">
					<li><a href="/media/#media_id#">#listlast(media_uri,"/")#</a></li>
				</cfloop>
				</ul>
			</cfif>




Errors from portals throw...

<p>
				<cfif len(session.roles) gt 0 and session.roles is not "public">
					If you are an operator, you may have to log out or ask your supervisor for more access.
				</cfif>
				You are accessing Arctos through the #yourcollid.portal_name# portal, and cannot access specimen data in
				other collections. You may
				<span class="likeLink" onclick="changeCollection('/#request.rdurl#')">try again in the public portal</span>.



I don't think we're failing to provide sufficient information.

There's no choice to offer on any of that - this isn't analogous to an OS confirmation. (Eg, that screenshot is not an error message.) The 404 stuff may be approaching an error, but it's closer to "you're lost, maybe this will help." The vast majority of our 404s are from dead inbound links, people bookmarking media URIs (http://handbook.arctosdb.org/documentation/media.html#urls-and-stability), etc.

The timeout "error" is a real error, sorta, but it's "we don't have the resources to provide what you asked for" and not "you did something wrong" or "something unexpected happened."

The "conducting a search" thing (http://handbook.arctosdb.org/how_to/How-to-Search-for-Specimens.html) minimally needs a better title - there are many ways to search Arctos, it covers only one of them. (Maybe 90% of timeouts involve taxonomy - mostly folks clicking the "gimme all Animalia" link and such).

I have emotional attachments to 
![blowup](https://user-images.githubusercontent.com/5720791/41946004-02e34a8e-7965-11e8-9e91-abb40f587faa.gif) even if it is like 9 pixels.

**Comment by Jegelewicz** [comment]
Just leaving it here...
![timeout error](https://user-images.githubusercontent.com/5725767/41990420-9497750a-79ff-11e8-9eb4-d2790b171e59.jpg)

**Comment by dustymc** [comment]
Pretty nice, I guess... can we GIF-melt the bear?

The "turn off those 9000 attributes that you never look at" thing should be included (maybe at the top).

**Comment by Jegelewicz** [comment]
![bear bw oops](https://user-images.githubusercontent.com/5725767/41991266-0e8ebaba-7a02-11e8-8fd3-f6d59703ec6e.gif)

**Comment by Jegelewicz** [comment]
I'm not sure how to word the "turn off those 9000 attributes that you never look at" thing. They haven't completed a successful search yet, so how does this help? Are we telling them to select fewer search terms from the get go? If so, perhaps:

 - limit your search terms to two or three items. Once your results are presented refine them with more advanced terms such as attributes or parts.

**Comment by dustymc** [comment]
Not search terms, results terms.

<li>
									After a <a href="/SpecimenResults.cfm?cat_num=1">successful search</a>, Click "Add/Remove Data Fields" and de-select unnecessary columns. Attributes are particularly expensive.
								</li>



We currently have....

```
UAM@ARCTOS> select count(*) from ssrch_field_doc where SPECIMEN_RESULTS_COL=1;

  COUNT(*)
----------
       208
```

208 possible results columns, including....

```
UAM@ARCTOS> select count( distinct( attribute_type )) from attributes;

COUNT(DISTINCT(ATTRIBUTE_TYPE))
-------------------------------
			    126
```

126 attributes, each of which requires a trip to the DB and a bunch of compiling for every row in the results. Turn them all on, and you can time out most any search. The link provides a results set (I hope! - it's catnum 1) from which they can turn junk off.

And while we're here - can we get rid of any of this mess?

```
UAM@ARCTOS> select distinct attribute_type from attributes order by attribute_type;

ATTRIBUTE_TYPE
------------------------------------------------------------------------------------------------------------------------
NAGPRA category
SNV results
abundance
age
age class
air temperature
appraised value
archaeological feature
axillary girth
bill depth
bill length
bill width
body condition
body width
breadth
brood parasite present
brood patch
bursa
bursa length
bursa width
carapace length
caste
clutch size
clutch size of nest parasite
colors
credit line
crop contents
crown-rump length
culmen length
culture of origin
culture of use
curved carapace length
curvilinear length
depth
description
dimensions
diploid number
ear from crown
ear from notch
ectoparasite examination
ectoparasites detected
egg content weight
eggshell thickness
electrical conductivity
endoparasite examination
endoparasites detected
examined for parasites
exhibit caption
experimental
extension
fat deposition
forearm length
framed
gonad
head length
head width
height
hind foot with claw
hind foot without claw
hind limb length
historical
image confirmed
incubation stage
inscriptions and marks
isotope value
left gonad length
left gonad width
location in host
materials
maximum standard length
maximum total length
middle toe length
minimum standard length
minimum total length
molt condition
neck width
nest description
nest phenology
nottitle
number of labels
numeric age
object title
ovum
parasites found
parts examined
plastron length
provenience
provenience east
provenience north
quadrant
radiometric date
reproductive data
right gonad length
right gonad width
sex
skull ossification
snout-vent length
soft part color
soft parts
square
standard length
stomach contents
straight carapace length
stratigraphic position
tail base width
tail condition
tail length
tarsus length
tested for presence
total length
tragus length
trap identifier
trap type
unformatted measurements
value
verbatim collector
verbatim host ID
verbatim host age
verbatim host sex
verbatim preservation date
water temperature
weight
width
wing chord
wing span
year class

126 rows selected.
```

https://github.com/ArctosDB/arctos/issues/1450

**Comment by Jegelewicz** [comment]
I don't understand - if I am at the Arctos search page, how do I turn them off or on?

**Comment by dustymc** [comment]
Search - fail - click the link - turn stuff off - try your original search (which will return different results because you just turned stuff off) again.

I suppose I could let you customize results before you can see them, but that seems confusing. (Perhaps less confusing than the alternatives though???)

Or allow customize directly from the failed search page??

**Comment by Jegelewicz** [comment]
> Or allow customize directly from the failed search page??

That would probably be the best solution - it gives people a chance to do something instead of reading about stuff they will have to do somewhere else (and by which time they get there they forget what to do).

**Comment by dustymc** [comment]
<img width="801" alt="screen shot 2018-06-27 at 12 54 03 pm" src="https://user-images.githubusercontent.com/5720791/41996283-3e3b6fae-7a09-11e8-9be1-dea4efb3590c.png">

**Comment by dustymc** [comment]
Closing, hopefully this won't be an issue in PG
