### ISSUE TITLE
check value for specimen_event_type when bulkloading

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#1566]
During the bulkloading process, check to make sure that the value for 'specimen_event_type' matches what's in CTSPECIMEN_EVENT_TYPE before pushing to bulkloader.

Data loaded by Cicero 12 Jun 2018 had an old value 'accepted place of collection' and the records got into the bulkloader, then were flagged when trying to load with the following error:

; called from b_bulkload: ORA-02291: integrity constraint (UAM.FK_SPECIMENEVENT_CTSPEVENTTYPE) violated - parent key not found

**Comment by dustymc** [comment]
done
