### ISSUE TITLE
Make data entry screen more efficient

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#1567]
1.  When you first open the data entry screen for a new record, the cursor appears in the seventh Attribute value box.  It would be helpful for the cursor to always start in the first field: Catalog#
2.  It appears that the tab feature only works from the specific field where you first tab - though it's quite inconsistent.  If you move the cursor with the mouse to the next section you need to complete, then hit tab, the tab often returns to field that would have been next before you moved the cursor with the mouse.  So you must either tab constantly or use the mouse exclusively.  Is it possible to tab from whatever field the cursor is in to the next field regardless of whether you tabbed or moused into the first field?
3.  After GeoLocating an entry, when you save the geolocation coordinates and return to the data entry screen, the coordinates don't appear.  The Original Lat/Long Units field changes from blank to the Units you've selected, but the rest of the fields don't open.  You have to select a different Unit, then return to the preferred Units to make all the fields appear.  It would be helpful to have this entire section open so you can see what you've saved.  
4.  If you hit "enter" within any fields, you'll get a hot pink error screen but it won't show you which field has the "enter" in it.  It would be helpful for that field to be highlighted in red so we don't have to check every field.

**Comment by dustymc** [comment]
>When you first open the data entry screen for a new record, the cursor appears in the seventh Attribute value box. It would be helpful for the cursor to always start in the first field: Catalog#

That's from processing Attributes, which seems to usually happen last. I could delay a bit and then focus on catnum or something, but there's some chance that the delay won't be enough and it'll jump back to Attributes, or the delay will be too much and it'll jump to catnum after you start changing things. (Probably both!)

>tab

That works as expected for me. What browser and OS are you on, and can you make it behave by disabling extensions?

>GeoLocating

I gave it a kick - it's working for me now.

>field has the "enter" in it.

<img width="389" alt="screen shot 2018-06-12 at 4 54 38 pm" src="https://user-images.githubusercontent.com/5720791/41323093-57ebc790-6e61-11e8-8f2b-39b3928c0b4f.png">

<img width="766" alt="screen shot 2018-06-12 at 4 54 43 pm" src="https://user-images.githubusercontent.com/5720791/41323095-5b621500-6e61-11e8-86ec-4f1eb8536e5e.png">

http://handbook.arctosdb.org/documentation/understanding-errors.html#check-constraint-uamck_tbl_col_noprint-violated

**Comment by sharpphyl** [comment]
_**TAB** - That works as expected for me. What browser and OS are you on, and can you make it behave by disabling extensions?_ 

The Tab is working better today.  I'll let you know if we have problems again. Today I'm on a Mac on Chrome, but usually I'm on FireFox on Microsoft 7 or 10.  Same problems but slightly different visuals.  The only extension I have on Chrome is AdBlock.  I'll check next week on the Microsoft computers.

_**GEOLOCATING** - I gave it a kick - it's working for me now._
Not for me.  It still doesn't open the Coordinates field and show me what values have been entered per my GeoLocation.  I know something has been entered because the Original Lat/Long Units field has gone from blank to decimal degrees.  I have all the Coordinates field customized to "show."

![screen shot 2018-06-29 at 2 36 28 pm](https://user-images.githubusercontent.com/15368365/42113794-dd6c02a4-7ba9-11e8-827b-d622c161fe58.png)

_**- field:**  has the "enter" in it._

What we need is for Arctos to put a red line around the text field with a RETURN in the body which is causing the error.  For almost all other errors, Arctos highlights the error so it's easy to correct. If the RETURN is in the middle of the sentence, you can find it, but if it's at the end of a sentence, or hidden in a field smaller than the text entered, then it can take ages to find and we frequently give up and reenter the entire record.

Below is a return after "purchased" and "from" in the Specimen/Event remark field.  If I have expanded the field, I can see the text with the error.  

![screen shot 2018-06-29 at 2 18 44 pm](https://user-images.githubusercontent.com/15368365/42113260-e88e312c-7ba7-11e8-8420-d4aaa4c0459e.png)

But here, I can't see the text and all that shows is "bad template" and no red square around the offending field.  

![screen shot 2018-06-29 at 2 31 31 pm](https://user-images.githubusercontent.com/15368365/42114460-5eea28b8-7bac-11e8-9def-0da9c9c555f5.png)

**Your link:**  http://handbook.arctosdb.org/documentation/understanding-errors.html#check-constraint-uamck_tbl_col_noprint-violated

The Find/replace non-printing characters report only works if you know what text to check for violations.  Again, it would be helpful to have the offending field highlighted in red as happens with most other errors.  Thanks!

**Comment by sharpphyl** [comment]
Update
> 1.  When you first open the data entry screen for a new record, the cursor appears in the seventh Attribute value box.  
I don't think this is totally solved but I've deleted several Attribute lines so the issue is diminished for me.  

2.  The tab function is working better now.  Issue closed for me.

3.  The geolocation request been fixed.  Issue closed for me.

4.  The hot pink error screen still doesn't show which field contains a "return" but most of the time we check every open field and eventually find it.  It would be helpful for the offending field to be highlighted in red but we can live with it the way it is. 

There's been enough improvement that I'm tempted to close this issue, but I'll leave it open for a few days if there are others who would benefit from enhancements #1 and #4.

**Comment by dustymc** [comment]
It's been a few days, closing
