### ISSUE TITLE
Part Attribute determiner being erased

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1571]
I have a part with multiple attributes. Upon saving the first, everything looks fine, but when I save the second attribute with a different determiner the determiner disappears from the first attribute I entered.

See attributes for Part 25988963

**Comment by dustymc** [comment]
GUID?

**Comment by dustymc** [comment]
arctos.database.museum/guid/MSB:Mamm:292063

Can't replicate; need more info.

Please delete my test data before closing this.

**Comment by AJLinn** [comment]
This happens to me all the time!

**Comment by dustymc** [comment]
Maybe related to http://handbook.arctosdb.org/documentation/understanding-errors.html#missing-expression? This one won't throw an error - agent isn't required - but this (or some flavors of it) could be caused by your browser being "helpful" and not triggering the agent_id lookup.

More info greatly appreciated!

**Comment by Jegelewicz** [comment]
MSB:Mamm:292063

**Comment by Jegelewicz** [comment]
When I create the part attribute, I have this:
![part attribute determiner entry](https://user-images.githubusercontent.com/5725767/41433168-4ccb4f82-6fd5-11e8-913b-cc908a8cf2ba.JPG)

**Comment by Jegelewicz** [comment]
And it looks fine until I either leave the record and return or enter a second part attribute, at chich point I have this:
![part attributes determiner doesn t save](https://user-images.githubusercontent.com/5725767/41433200-6b16f36a-6fd5-11e8-95e6-cd19d33ca360.JPG)

**Comment by Jegelewicz** [comment]
The determined by fields are blank now....

**Comment by AJLinn** [comment]
exactly what happens with us when editing remarks for part attributes and then save - the last determiner goes blank.

**Comment by Jegelewicz** [comment]
arctos.database.museum/guid/MSB:Mamm:292063

**Comment by dustymc** [comment]
Found it! "Return" was the key word - thanks! Fixed for next release.
