### ISSUE TITLE
attribute/bulkloader error question

### ISSUE THREAD

**Issue by KyndallH** [ArctosDB/arctos#1572]
I'm getting this error when I try to upload my environmental samples.

<img width="1318" alt="screen shot 2018-06-15 at 10 36 00 am" src="https://user-images.githubusercontent.com/16887896/41484099-f371a216-7087-11e8-846e-8dc5122e458e.png">

I'm assuming the problems is with the "absent" or "present" that I have under the attribute "tested for presence". However, when I look at the code table, it should just be a text field that I can enter anything. Do I need to select something other than "none"?

<img width="1133" alt="screen shot 2018-06-15 at 10 35 20 am" src="https://user-images.githubusercontent.com/16887896/41484138-1d67e47c-7088-11e8-9f8f-5bb63124b4b4.png">

**Comment by dustymc** [comment]
I need your data to know what's actually going on, but looks like maybe you're trying to creatively name columns? ONLY things from the bulkloader builder will be accepted.

And http://arctos.database.museum/info/ctDocumentation.cfm?table=CTYES_NO is available, if you'd like to control the values for that attribute.

**Comment by KyndallH** [comment]
[2018_06_14_2016SpanglerCustomBulkloaderTemplate (12).xlsx](https://github.com/ArctosDB/arctos/files/2107226/2018_06_14_2016SpanglerCustomBulkloaderTemplate.12.xlsx)

**Comment by KyndallH** [comment]
Yup - you guessed it. I just checked and the student had "present" added into the column header.

**Comment by KyndallH** [comment]
Is there any way to make it when you download your data with errors that it doesn't put the data headers alphabetically, instead does it like it use to with errors in column A and the rest in order as loaded? 
<img width="2128" alt="screen shot 2018-06-15 at 11 16 03 am" src="https://user-images.githubusercontent.com/16887896/41485591-a6ab9d3c-708d-11e8-846e-9daa193cf269.png">
