### ISSUE TITLE
Labels with geology attributes

### ISSUE THREAD

**Issue by dperriguey** [ArctosDB/arctos#1575]
I'm trying to create a label for our collections. I'm going to be using the DMNS_Marine_Invertebrates (DMNS_conchology_label.cfr) template with some geology attributes.

I was using the UAM_ES_Vial (Earth_Sciences_vial_labels_III.cfr) to use the SQL terminology for geology attributes, but the only thing that I could find was under:

specimen_event,
	collecting_event, 
	locality, 
	geog_auth_rec

I'm thinking that it is under "geog_auth_rec" but I would like a little more information like the Series/Epoch, Stage/Age, and formation. 

Does anyone know the right terminology that I should be using?

**Comment by dustymc** [comment]
I don't understand the question. Geology is related to locality. concatGeologyAttribute calls https://github.com/ArctosDB/DDL/blob/master/functions/concatGeologyAttribute.sql which accepts the cataloged item's collection_object_id and returns a string - you can just include 

concatGeologyAttribute(cataloged_item.collection_object_id) geology_stuff 

to get a "geology_stuff" variable.

**Comment by dperriguey** [comment]
I kinda get what you are saying.
I think I'm really lost though. I was just going to use a template and edit it for our institution. But I don't even see where the institution name is in the templates or where it's being pulled from.

If I use the DMNS_Marine_Invertebrates (DMNS_conchology_label.cfr) template, what would I edit in the SQL to pull our institution name?

**Comment by dperriguey** [comment]
Sorry, I didn't download report builder. Just downloaded it though. 

Its giving me an: 

Installer UI Mode Error. 
The installer cannot run in this UI mode. To specify the interface mode, use the -i command-line option, followed by the UI mode identifier. The valid UI modes identifiers are GUI, Console, and Silent. 

I have no idea what to do with this.

**Comment by dperriguey** [comment]
Ok, I downloaded the Report Builder and got things working. Thanks. Took a while to remember how to do this stuff.

**Comment by campmlc** [comment]
That's great, Dustin. Reports are certainly not user friendly. Glad it is
working!

**Comment by dperriguey** [comment]
So, now I've tried to upload a test that is not working. I used DMNS_Marine_Invertebrates (DMNS_conchology_label.cfr) as my template. Only changed 2 strings in the Report Builder. Uploaded my .cfr and followed the rest of the instructions. Receiving error: scientific_name is not a valid ColdFusion expression. I did not change the expression at all. 

Am I supposed to actually edit the "select 1 from duel" SQL with a copied version of what is in DMNS_Marine_Invertebrates (DMNS_conchology_label.cfr) SQL?

**Comment by dperriguey** [comment]
I keep getting an error that reads: scientific_name is not a valid ColdFusion expression. I'm sure that this is incorrect because I've uploaded a .cfr file that I did not edit the SQL and only edited the file name. This worked fine. When I edited the text in " " such as our institution name, I got that error I just mentioned.

**Comment by campmlc** [comment]
I had this problem when I tried to clone a report, same error. I think I
made it work by not cloning but copying and pasting the SQL into a
different report and renaming it.

**Comment by dperriguey** [comment]
Ok, great! I'll try that. I thought that CF just hated me.

**Comment by dperriguey** [comment]
@campmlc That was what I needed to do. Thank you!

**Comment by dperriguey** [comment]
We should update the instructions for how to do labels. This is not the only deviation from the instructions that I've run into.

**Comment by campmlc** [comment]
Agreed, but should also fix the clone function or get rid of it.

**Comment by dperriguey** [comment]
Now I'm just having trouble getting geology attributes into my label. I tried to use a template that worked fine through the "print any report" that contained geology attributes. I replicated this by downloading and just saving it to a different name, not editing anything else. Same SQL, same CF report setup. I get an error: replace(locality,'USA: ','','all') is not a valid ColdFusion expression.
This kinda makes sense to me given that @dustymc gave me different geology variable, but it works when I do not download and just use the "print any report." 

I thought I would be able to copy paste SQL from a .cfr file into the template I'm using, but it is not working either. I would really like to get geology attributes into the label. It seems that just using concatGeologyAttribute(cataloged_item.collection_object_id) geology_stuff in my SQL does not work either for me. I'm sure that I'm not using it correctly. I keep getting this error: "CATALOGED_ITEM"."COLLECTION_OBJECT_ID": invalid identifier.

I'm guessing that putting concatGeologyAttribute(cataloged_item.collection_object_id) geology_stuff in the SQL just under say higher_geog would be ok because collection_object_id is in the "WHERE" part of the SQL. Then simply adding in the CF report a box that calls the geology_stuff variable would work, but it's not. What am I missing?

**Comment by dustymc** [comment]
What is the report name?

**Comment by dperriguey** [comment]
UNM_ES_label_test_2 (UNM_ES_test_2.cfr)

**Comment by dperriguey** [comment]
Ok, I'll try that. I had trouble inferring how the SQL worked by looking at other handlers and such because they all looked so different from each other.

**Comment by dperriguey** [comment]
Beautiful! Thank you @dustymc ! Really appreciate that. Do you have a link to a very basic introduction and uses for SQL? Everything I found was very complicated and something more basic that incorporates the stuff that I have access to on Arctos would be helpful.

**Comment by dustymc** [comment]
Yes, there are generally a LOT of ways to do most things.

https://www.w3schools.com/sql/sql_intro.asp looks fairly useful.

Arctos has a built-in table browser at

<img width="390" alt="screen shot 2018-07-16 at 1 45 58 pm" src="https://user-images.githubusercontent.com/5720791/42782724-9668e306-88fe-11e8-851f-0ef0650fbec0.png">

and the label docs at http://handbook.arctosdb.org/how_to/How-to-Create-Labels.html link to functions (like concatGeologyAttribute(), which returns "a cell" instead of an unknown number of rows, and generally let you avoid joins and dealing with cardinality and all that fun stuff).

**Comment by dperriguey** [comment]
Great! Thanks @dustymc
