### ISSUE TITLE
Osteichthyes

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1576]
How do I make the genus suggestion go away for the Osteichthyes classification?

**Comment by dustymc** [comment]
Deprecate that form entirely and run everything through the hierarchical editor?! That's what I'd do if I could...

https://github.com/ArctosDB/arctos/issues/1188#issuecomment-314566131

**Comment by Jegelewicz** [comment]
UGH, I can't keep up and I have no idea what the hierarchical editor is...

I ran across this because it messes with stuff at iDigBio. In addition, I just found that our Aves is being turned into the genus avus (an insect) by iDig Bio!

See [my record in Arctos](https://arctos.database.museum/guid/UTEP:ES:36-29)

See [iDigBio](https://www.idigbio.org/portal/records/18805a8a-84d0-4ecd-8e56-013ce3a0b21f)

**Comment by dustymc** [comment]
An insect with a longbone, and they've propercased "Utep" - nice...

The hierarchical editor is...

<img width="307" alt="screen shot 2018-06-20 at 1 07 32 pm" src="https://user-images.githubusercontent.com/5720791/41681914-f3c0f922-748a-11e8-9464-8243b90bbe87.png">

It's sort of a pain to use if you're trying to modify one record. It's a REAL pain to use if you've made one record inconsistent in the one-record form. It will deal only with hierarchical data, where "Arctos proper" has no such limitations (eg, Osteichthyes has a few classifications under the Arctos unbrella.) That probably all requires more discussion before we can seriously consider deprecating anything - but please try to be consistent, just in case!

**Comment by Jegelewicz** [comment]
I don't want to touch that! It sounds super-scary and not being a taxonomist of any sort, I don't want to mess with stuff I don't know anything about....

Any suggestions for correcting the Aves stuff? I honestly don't know WTH iDigBio is thinking there...It looks like we are passing Aves as the class, but somehow they have decided it is the genus.

The lowercase or proper everything - it's so hard for me to look at their site.

**Comment by dustymc** [comment]
Both editors are simultaneously comforting and terrifying. With the single-record thing you're just mucking with one record - which you can make virtually impossible to find by making it inconsistent with everything else. With the hierarchical editor you can't possibly make inconsistent data, but you can make consistently bad data for a million records with a couple clicks.

Taxonomy as a body of literature (and there's no other valid perspective at the scope of Arctos) has basically no "rules," and Arctos has virtually no rules to accurately reflect that "data model." That allows this:

<img width="1205" alt="screen shot 2018-06-21 at 8 28 12 am" src="https://user-images.githubusercontent.com/5720791/41729042-1c7a0c6c-752d-11e8-895c-c240587c92d6.png">

Arctos will do weird things when flattening that, and the the flattened version is what we share via DWC.

I just deleted the funky UCMP data - 99% sure it's just mangled to fit in some overly-simple database and not in indication that there's some taxon that happens to share a string with lots of fish. That should find it's way to specimens in a day or so, and will hopefully help with idigbio-n-friends.
