### ISSUE TITLE
Tanzania

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#1577]
I'll be working on Tanzania higher geography cleanup-- basically will create HG for all Regions (Adm_1) if not there already but will be removing/moving to appropriate Region all the districts (adm_2) and lower. Adm_2 and lower units are not stable enough to have its own HG but regions are; this info should go in specific locality. Other clean-up includes adding wikimedia authority links etc.

So in the end there will be 31 regions for Tanzania for users to pick from.

**Comment by dustymc** [comment]
Tabling - https://github.com/ArctosDB/arctos/issues/3272 would allow Arctos to standardize geography.
