### ISSUE TITLE
Publication Authors

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1578]
When adding a publication, I am only allowed to enter one author on the initial entry screen although there are spaces for five or so. Can we either make it so that I can enter all of the authors on the first try or just have a space for one with a note that the rest should be entered after the publication is initially saved?

**Comment by dustymc** [comment]
You can enter all there's space for (and I can add more of that if needed). I see ORA-00001: unique constraint (UAM.IU_PUBLICATION_AGENT_ONEPER) violated in the logs - that's a unique constraint on (agent_id,publication_id) - an agent can't act as multiple authors on one pub.

**Comment by Jegelewicz** [comment]
Hmmmmm. I didn't think I entered anyone twice, but it's possible. I'll revisit if it happens again.

**Comment by campmlc** [comment]
I'm getting the same error because I am trying to change the order of the authors to match the order in the publication. Authors tend to get upset if they are credited in incorrect order, Arctos is re-ordering them according to some opaque criteria no matter how I enter them. When I try to re-order and save, I get the message:  
"ORA-00001: unique constraint (UAM.IU_PUBLICATION_AGENT_ONEPER) violated"

**Comment by campmlc** [comment]
https://arctos.database.museum/Publication.cfm?action=edit&publication_id=10008582

**Comment by campmlc** [comment]
And if I try to edit the order when creating an identification by just deleting all the out-of-order authors and leaving only the first author, I get this:
ORA-00001: unique constraint (UAM.IU_IDENTIFICATIONAGENT_IID_AID) violated

**Comment by dustymc** [comment]
>getting the same error because I am ...

... trying to add one agent twice. There is no other pathway to that error.

>change the order

That would require a data model change. We can talk about that, but I don't think this is the place to do so.

>IU_IDENTIFICATIONAGENT_IID_AID

That's a similar cause - you're trying to add an agent twice.
