### ISSUE TITLE
Problem with the portals page

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1581]
We have so many institutions that the list on the left side of the page is longer than one screen. The list doesn't scroll with the page, so no matter how badly I want, I cannot click UTEP...
![capture](https://user-images.githubusercontent.com/5725767/41797402-1c6dc84e-7627-11e8-9d76-1425d068a291.JPG)

**Comment by dustymc** [comment]
Merging with #1554
