### ISSUE TITLE
Media Question

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1582]
A researcher came to the collection and took photos of specimens which he passed on to me. I am adding these media to the cataloged items. How do I give the researcher credit for the photos? Can we add a relationship of "maker"? Since "created by" seems to indicate who uploaded the photo and attached it to the object record, I think we need a way to properly credit the photographer. The other way would be to add a label of "maker". Either way, I'd like this to be reflected in the person's Arctos agent profile.

**Comment by Jegelewicz** [comment]
Cool, can we create a relationship of "maker"?

**Comment by dustymc** [comment]
http://handbook.arctosdb.org/documentation/media.html#fields-in-table-media

>Relationships are functional and must be comprised of a string containing at least one space and ending with a table name. 

How would "maker" differ from "created by agent"?

**Comment by Jegelewicz** [comment]
According to the documentation:

> The agent who created the relationship between a media object and a data item. This is a foreign key to the Agent table.

I did that, but I did not take the photograph. I want to be able to distinguish between the two.

**Comment by Jegelewicz** [comment]
"Maker" - The agent who created the media item.

**Comment by campmlc** [comment]
"Created by" is confusing in its current connotation. The definition seems
to fit more to "Relationship Assigned by". If we renamed the current field,
we could reassign " Created by" to " Media created by" for the actual
author of the media.
Or use"Media Author" as a separate field. But we should rename or redefine
"Created by" regardless because it seems likely to lead to
misinterpretation and error.

**Comment by dustymc** [comment]
OH!!

That is "who mashed buttons" - it's metadata, always pulled from your environment, and I'm not sure you can see it anywhere. I'm really not sure why it's in the documentation at all, but I suppose comprehensive is good. Except when it's obviously confusing....

You need "created by agent" from the code table I linked above - http://arctos.database.museum/info/ctDocumentation.cfm?table=CTMEDIA_RELATIONSHIP.

**Comment by dustymc** [comment]
>Relationship Assigned by

Yup, that's exactly it. There's another for Labels.

>renamed the current field

It's internal - the docs should definitely be clarified, but there's not really much to rename.

**Comment by AJLinn** [comment]
I have never looked at the documentation before today (whoops) but I have always used "created by agent" as the person who took the digital photo and likewise, the "date made" is when the photo was taken. Sometimes I confuse myself when I digitize a physical photo into an electronic file. Typically I'll use myself as the created by (I scanned the 35mm slide and did the Photoshop editing) but then list the photographer in the comment label (e.g., "Photo credit: Barry J. McWayne").

**Comment by dustymc** [comment]
>"created by agent" as the person who took the digital photo

As it should be.

>digitize a physical photo

That doesn't fit perfectly - physical things are parts (by definition), media are digital (have a URL), media link to specimens, not parts, etc. 

IF there's some reason to care about the scanner operator (or photoshopper or whatever), I'd just enter them all under 'created by agent' and clarify in remarks. Relationships create data objects - the link from the Agent to the Media - and from there I think remarks are sufficient for the details. 

Or you could credit the original creator for the most unaltered representation (DNG or whatever came out of the digitization device), the folks who made them for any derivatives, and link all the Media together - that should get anyone where they want to go as well.

It would be fairly easy to add various "whatevered by agent" values to the relationship code table, but I suspect that would add more confusion than it removes.

**Comment by dustymc** [comment]
OH! (again, I think...)

Find a single specimen, Media, drag/drop, see this:

<img width="719" alt="screen shot 2018-06-25 at 11 37 50 am" src="https://user-images.githubusercontent.com/5720791/41868926-48aad298-786c-11e8-9154-43eff1bb441e.png">

Correct?

If so, you can just click clear or select the actual creator or WHATEVER. That sort of thing always exists because someone asked for it. I can change it (to do nothing, or click to select yourself, or WHATEVER), but that's probably/maybe deserving of it's own issue to work out the details.

**Comment by Jegelewicz** [comment]
Correct, but even if I change it, when the media loads, my name is there....

**Comment by dustymc** [comment]
Neato - that's a bug, it'll be squished for next release.

**Comment by AJLinn** [comment]
Whoa,.. I never noticed that! @Jegelewicz Thanks for finding that bug and thanks @dustymc for fixing. Sheesh... I guess we'll have to fix those hundreds/thousands retroactively... 😳

**Comment by dustymc** [comment]
> fix those hundreds/thousands retroactively

I can help SQL them.

**Comment by Jegelewicz** [comment]
Great! Now, will I be able to see who loaded the photo? I'd like this to be like the addition of an object record so that I would know who added or last edited the photo as well as who actually took the photo.

**Comment by dustymc** [comment]
>who loaded the photo

We do not currently record that. We do record who made relationships and labels, and that could be more prominent.

Or add a "whatevered by agent" values to the relationship code table.

**Comment by Jegelewicz** [comment]
Created new issue to request enhancement to display entered by and last edited by.
