### ISSUE TITLE
Barcodes and Labels go together....

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1585]
Any time I see a barcode, I would also like to see the label and vice versa. This would be a huge help when doing anything as barcodes are just numbers and without their labels they are pretty meaningless to humans and labels are created by humans which means they are prone to error. If we can see them together it helps locate objects in the collection and know what exactly we are looking for in one simple formula. Can we start with this?

![capture](https://user-images.githubusercontent.com/5725767/41988574-cbbd6f5e-79f9-11e8-8658-e7b28e198b42.JPG)

Rather than individually checking each box and scrolling to the bottom of the page to see its barcode, can we just have the barcode display right next to the label? In this case, we have transcribed the barcode into the label, but recently discovered transcription errors....

**Comment by Jegelewicz** [comment]
Yes you do see them, but only one at a time - it involves clicking through the whole list....

**Comment by campmlc** [comment]
I agree with Teresa. We are continually coming up with conflicts because if
a label exists we cannot see the barcode. Anytime we have both we need to
see both, globally. If people don't care about a label, then they don't
have to  add one. If they do care, they need to see it, but also need the
barcode. This goes for all views, including "show all collection objects in
this container" and "flatten part positions" and loan forms etc.

The only reason you can see the barcode in the view Teresa loaded was
because we had to manually add the barcode to the label in order to both at
once, an untenable solution.

**Comment by dustymc** [comment]
> If people don't care about a label, then they don't have to add one.

They absolutely do - that is a NOT NULL field, and removing that constraint would provide the possibility of creating containers that have no identifiable component.

>This goes for all views

That is what I'm asking for - what can we do that works everywhere?

**Comment by campmlc** [comment]
If they don't want a label that differs from a scannable barcode -
Can we just display both if they differ?

**Comment by Jegelewicz** [comment]
Would it work if we put them in this format, no matter where any one of them appears?

Barcode (Container Type) Barcode Label

I get the screen space problem if labels are too long. Not sure I have an answer for that right now.

**Comment by dustymc** [comment]
>display both if they differ

Probably. That MIGHT get expensive if there are lots, but I think we can do it. It would remove the ability to differentiate "has a barcode" and "just a label" - important? (I think that is important - those are wildly different types of data, see eg http://handbook.arctosdb.org/documentation/container.html#object-tracking-without-barcodes)


>Barcode (Container Type) Barcode Label

```
UAM@ARCTOS> select getContainerParentage_BLT(14848352) from dual;

GETCONTAINERPARENTAGE_BLT(14848352)
------------------------------------------------------------------------------------------------------------------------
MSB (institution) Museum of Southwestern Biology:DGR (collection) Genomic Resources:DGRCERIA324 (room) 324 LN2 Room:DGR-
C01 (freezer) CRYO-01:DGRC1A (bay) CRYO1-A:DGRC1A2 (freezer rack) CRYO1-A2:DGR16903 (freezer box) DGR16903 DGR2-1-9
```

**Comment by campmlc** [comment]
I second this, also for find containers, flatten parts, specimen
parts/path, and parts being selected for loan. We need to be able to see
both the label and the barcode anytime one is displayed.

**Comment by dustymc** [comment]
Maybe I wasn't being clear. 

### I'd really like to have one _thing_ that we can sprinkle around wherever containers are used.

I think we're all on the same page there, but I don't know what ya'll want or how we're going to make it fit. 

Barcode+label+type is probably best, but that gets long fast (and maybe it's just overwhelming==not "best").

I don't know if we have the processors to support showing only one value when barcode=label or not (probably??), and I think it's potentially confusing - there have been a ~half-dozen times when someone changed a label so it didn't match a barcode and the resulting confusion made messes. It's still compact and contains everything-ish, which is nice.

I really need an answer to that before I can go very far, and I'm probably going to need some help making space for it depending on what that answer is.

I'll try to patch something in to that table, although I think that's probably also better done in the "standard" format (if we had such a thing!) - seeing the same thing in multiple views pretty much always leads to fewer mistakes.

**Comment by campmlc** [comment]
It is actually preferable if we can see both barcode and label, even if
they are the same, in our collection, because we have labels without
bacodes and vice versa and it is helpful to see which ones need to be
added. Is this something that different collection could customize, e.g.
choose whether or not to see one or the other? Would that make processing
better or worse?

**Comment by dustymc** [comment]
> barcode and label

OK, agreed - that would have prevented some past problems. I need a format. I think it's probably best if it visually distinguishes them - eg, not

barcode - label

because people (me anyways!) will quickly lose track of the order. It also needs to work when there's no barcode (eg, positions). Maybe something like

[ barcode ] label

which turns in to

[  ] label


Do we include container_type? I can do it if ya'll need it - this certainly isn't a technical problem - but that's a LOT of information to print on a screen or try to absorb.

> different collection 

I can't think of a single legitimate "in MY collection...." argument. Pretty much all of those turn out to be SOMEONE doing it wrong, and it's hard to imagine how this could be different.

If we did do something like that, it would be a fair bit more expensive computationally (an extra join or two for every operation), a significant increase in the complexity of the code, and more or less impossible to maintain. And that would block the more efficient pathways that inevitably come around from sharing data and ideas - some collection would have found a much more efficient way of doing something you do, and you'd never know about it because they're just requesting changes to THEIR code.

**Comment by campmlc** [comment]
This works:

[ barcode ] label

which turns in to

[ ] label


Container type would be helpful. We have a lot of legacy containers that
were scanned in as "Nalgenes" that need to be fixed - this would help
identify those. But I agree we don't want to clutter too much. Can we do
all three - barcode, label, and container - and see a mockup of what it
would look like in test?

**Comment by dustymc** [comment]
There are a bunch of examples above and in linked issues.

**Comment by campmlc** [comment]
From the MSB DGR perspective, yes, it would be very useful to us to see barcode **and** label **and** container, e.g.
MSB (institution) Museum of Southwestern Biology:DGR (collection) Genomic Resources:DGRCERIA324 (room) 324 LN2 Room:DGR-CRYO-01 (freezer) CRYO-01:DGRC1A (bay) CRYO1-A:DGRC1A2 (freezer rack) CRYO1-A2:DGR16903 (freezer box) DGR16903 DGR2-1-9

Yes, it is cluttered, but it has in one place all the information that we currently have to search through multiple forms to find.
@KyndallH 
@amgunderson 
@DerekSikes

**Comment by dustymc** [comment]
That format makes my brain sad. How about this:

```

UAM@ARCTOS> select getContainerParentage_tff(14848352) from dual;

GETCONTAINERPARENTAGE_TFF(14848352)
------------------------------------------------------------------------------------------------------------------------
[ MSB ] (institution) Museum of Southwestern Biology:[ DGR ] (collection) Genomic Resources:[ DGRCERIA324 ] (room) 324 L
N2 Room:[ DGR-C01 ] (freezer) CRYO-01:[ DGRC1A ] (bay) CRYO1-A:[ DGRC1A2 ] (freezer rack) CRYO1-A2:[ DGR16903 ] (freezer
 box) DGR-2-01-09 DGR16903
```

from

```
 select '[ ' || barcode || ' ] (' ||container_type || ') ' || label
```

Let me know if you want to see that from some other container, change anything, whatever. I'm not sure I like : as a separator but I can't find anything I like better...

**Comment by campmlc** [comment]
Can we put it in barcode -label -container type  order? That makes my brain
a lot happier. It helps to see the consistency/relationship between the
barcode and the label of a single container, and to separate the text of
the label of one parent from the barcode of the child.

**Comment by dustymc** [comment]
```
GETCONTAINERPARENTAGE_TFF(14848352)
------------------------------------------------------------------------------------------------------------------------
[ MSB ] Museum of Southwestern Biology (institution):[ DGR ] Genomic Resources (collection):[ DGRCERIA324 ] 324 LN2 Room
 (room):[ DGR-C01 ] CRYO-01 (freezer):[ DGRC1A ] CRYO1-A (bay):[ DGRC1A2 ] CRYO1-A2 (freezer rack):[ DGR16903 ] DGR-2-01
-09 DGR16903 (freezer box)

```

**Comment by campmlc** [comment]
Yes, that looks great, thanks.

**Comment by campmlc** [comment]
This looks great so far. I'll check again when in production.
Thanks!

**Comment by Jegelewicz** [comment]
Is this one of the forms that will eventually display barcode AND label? If not, we need it to.
![image](https://user-images.githubusercontent.com/5725767/46819350-c1556400-cd40-11e8-8e38-5a898bab64fe.png)

**Comment by dustymc** [comment]
Next release:

<img width="1196" alt="screen shot 2018-10-11 at 10 21 44 am" src="https://user-images.githubusercontent.com/5720791/46822128-7b4bd080-cd3f-11e8-8fcd-8f63647f09fd.png">


here too:

<img width="513" alt="screen shot 2018-10-11 at 10 21 00 am" src="https://user-images.githubusercontent.com/5720791/46822093-6111f280-cd3f-11e8-802d-990ce7b532ee.png">

**Comment by KyndallH** [comment]
I'm a bit concerned about this change in regards to how I sort tissue locations for loans. I guess when it is released and it screws up my stuff, I can yell and we can fix it. Right?

**Comment by dustymc** [comment]
Yes, but if we fix it I'd like to do so by changing http://handbook.arctosdb.org/documentation/container.html#display-format - I'm digging the idea of having one THING to sprinkle around.

**Comment by campmlc** [comment]
Re-opening. So far this has helped tremendously, but  I have another form that I need to see the barcode as well as the label for - the flatten part locations form for download.  I use this form to find parts when given a list of catalog numbers; then I need to be able to use the download to bulkload the parts to a loan, which means I need to extract the barcodes for each part, which I can't do if I only see the label.
@dustymc

**Comment by campmlc** [comment]
I agree with the data structure of this, but also agree that we needed a simplified version of the output to use for actually downloading and printing out container locations. I spend easily 30 min per loan massaging the output before I can use it or hand it to students to pull tissues. Sometimes I make mistakes and potentially compromise the data and samples pulled. I could write an excel macro except that the data are not consistent enough for this to work. I'd have to run multiple macros. I haven't tried using last part location. Is that an option?

**Comment by dustymc** [comment]
Last part location does not involve containers.

"Part path" can be different, as long as it's consistent, but I can't see how this could be simpler than a delimited string.

I don't understand why you need any outside tools. Container-->flatten parts, or the tree from which it comes, should be all anyone needs to find anything in a barcoded collection. That doesn't seem to be the case, how can we make it so?

**Comment by campmlc** [comment]
We need to be able to print a report = spreadsheet in a format that allows
all required information to fit on a page, and simple enough that a student
can immediately see the location hierarchy without having to sort out
barcodes and labels and container types.  This format will likely vary by
collection.

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/3578, closing.
