### ISSUE TITLE
Update CTCULTURE

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#1587]
I would like to update the CTCULTURE entry for "Aleut" to instead use the more culturally-sensitive term Unangax̂ and change the documentation to be: "also Unangan. Formerly Aleut; Indigenous peoples of the Aleutian Islands of Alaska; see also http://en.wikipedia.org/wiki/Aleut"

If this change occurs, we would need any of the current uses of "Aleut" to be updated to "Unangax̂"
Is that possible?

**Comment by dustymc** [comment]
I have no opinion on the values. We should absolutely not have two ways of saying "THAT." Is anyone else using this, and if so are they OK with the proposed value?

The non-ASCII characters are somewhat likely to cause difficulties (Excel will probably eat them, I'm not sure users will know how to type "x̂ ", etc.). It's certainly no problem in Arctos, and we SHOULD all be using UTF-compliant tools, but here we are anyway... This isn't an objection, I'm just pointing out problems we've had in the past with similar characters.

Authorities generally can't change (wouldn't be very authoritative if they could!) but I can SQL-shuffle that in without much problem.

**Comment by AJLinn** [comment]
`The non-ASCII characters are somewhat likely to cause difficulties (Excel will probably eat them, I'm not sure users will know how to type "x̂ ", etc.)`

No problem - we can just use a standard x for the term, maybe we can show it in the documentation?

**Comment by krgomez** [comment]
We are currently using this in Art and support the change that you are suggesting Angie.

**Comment by campmlc** [comment]
Just curious, from the standpoint of the general public who like me may not
be aware of the correct term, would this change still allow searches on the
term Aleut to find these records? Does this work like taxonomic synonyms?

**Comment by AJLinn** [comment]
It's a good question Mariel, which I always forget about. How about we follow the lead of the Smithsonian's Arctic Studies Center and do "Unangax (Aleut)". If/when the term becomes more ubiquitous we could remove the parentheses.

![unangaxaleut](https://user-images.githubusercontent.com/17605945/42174102-b0193936-7dcd-11e8-8d31-5c183f4e2683.jpeg)

**Comment by dustymc** [comment]
Should I update Aleut to "Unangax (Aleut)"?

**Comment by AJLinn** [comment]
Yes please! And then if you can find a way to update the existing Aleut attributes that would be amazing...

**Comment by dustymc** [comment]
done
