### ISSUE TITLE
Order of things

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1588]
Why does rack 1 appear at the bottom of the list? How are the items in this list ordered? It doesn't appear to be by either barcode or label....
![capture](https://user-images.githubusercontent.com/5725767/42000386-c03e98dc-7a1d-11e8-9965-53ee7f82c3a0.JPG)

**Comment by dustymc** [comment]
>How are the items in this list ordered

Probably by ROWID. How would you like them to be ordered?

Some limitations in https://github.com/ArctosDB/arctos/issues/104

**Comment by campmlc** [comment]
See #1586 .
Box 1
Box 2
Box 3 etc

Rack A1
Rack A2
Rack A3 
etc

**Comment by campmlc** [comment]
Or, if no label - by barcode.

**Comment by Jegelewicz** [comment]
It appears this has been done, closing
