### ISSUE TITLE
Allow operators to delete taxonomy

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#1591]
On occasion, I have added a taxon with a misspelling or subsequently learned that it isn't valid.  I would like the ability to delete these taxa.  

I would also like to be able to delete taxa others have added that I know are misspellings.  For example: _Conus ebraens_ is a misspelling of _Conus ebraeus_ and a refresh results in a "probably not valid" verdict from the validator.  

![screen shot 2018-06-29 at 1 03 00 pm](https://user-images.githubusercontent.com/15368365/42110179-7b249c0c-7b9d-11e8-9ae2-2d7498ef3a68.png)

And a Google search turns up our Arctos taxonomy as the second entry.  While it's good for Arctos to have more exposure, it would be preferable if it were not for misspelled taxonomy.

![screen shot 2018-06-29 at 1 07 24 pm](https://user-images.githubusercontent.com/15368365/42110187-80c638d2-7b9d-11e8-85e1-5ee88f9c0d29.png)

By valid, I don't mean that it was never valid or accepted. It's fine to keep historic taxa in Arctos.  But, for example,  _Conus stercus muscarium_ was never valid.  The valid, accepted name is _Conus stercusmuscarum_.  A historically valid, but no longer accepted, name would be _Textilia stercusmuscarum_ (Linnaeus, 1758) and ideally it would be linked to the accepted taxon.

I have been periodically sending Dusty a list of misspelled taxa to delete but I find that cumbersome and would like to address it when I see the erroneous taxa.  Having fewer misspelled or invalid taxa would also help our data entry volunteers avoid selecting a misspelled taxon.  

I would suggest the following requirements for deletion:

- The taxon is not being used by any collection.  
- Only operators who are authorized to add taxa can delete taxa.
- And, if you want more control, the taxon was created by the operator and/or the taxon is flagged as invalid by the taxon validator.

I would see the procedure as similar to my ability to delete a locality.  That doesn't keep anyone from adding the locality back in if it's needed and the same would be true for each deleted taxon.

**Comment by Jegelewicz** [comment]
This sounds reasonable to me. Besides that if Dusty is the only one who can delete taxa we have a problem. There shouldn't be anything only one person can do - we should have backup for everything!

**Comment by dustymc** [comment]
I have no problem with this.

Use quotes for" "the Google Test" = "Conus ebraens." That one SORT of passes - https://archive.org/stream/b24757688/b24757688_djvu.txt contains the string. If that has some relationship to specimens (eg, they're somehow mentioned in that publication) I'm fine with keeping it, but if it doesn't I'd also prefer to make it go away.

We don't track who created taxa (Issue if we should); the rest of those criteria are built into the structure.

The validator regularly fails with both false positives and false negatives. I think it's useful, but I also don't think it should be part of a decision process.

There are definitely things that only one of us can do, but there's nothing that couldn't be done by the right flavor of consultant. Everything is documented on GitHub, so it should be pretty straightforward to bring someone in. There will always be lots of things that can't be done via a browser, or can't conveniently be done with a browser. The rules are all in the DB so I have no real problems with anyone having SQL access - you can't do much on the command line that you can't do via browser (but you can do a lot more of it a lot faster, which isn't always a good thing!). I think manage_taxonomy has delete on taxon_name, it's just not in the forms - anyone with that role could SQL in (TACC can set that up) and delete taxon names. 

I'm not sure who all has the sys and owner passwords, which are necessary for some admin stuff. I don't mind sharing them, but they do need to be handled securely.

**Comment by Jegelewicz** [comment]
> I'm not sure who all has the sys and owner passwords, which are necessary for some admin stuff. I don't mind sharing them, but they do need to be handled securely.

We need to document this somewhere - at least the list of who has them. @ccicero  do you know?

**Comment by sharpphyl** [comment]
- _Use quotes for" "the Google Test" = "Conus ebraens." That one SORT of passes - https://archive.org/stream/b24757688/b24757688_djvu.txt contains the string. If that has some relationship to specimens (eg, they're somehow mentioned in that publication) I'm fine with keeping it, but if it doesn't I'd also prefer to make it go away._

It looks like the link for "the Google Test" is a digitization of a book and that there are lots of misspellings as a result.  A bit lower on the same page appears

 Buckrl. a) Strombus gibberulu«;; b) Buccin. gib- 
bosulum; c) Bulla ii,ibbosa.

I suspect that Strombus gibberulu<<;; is Strombus gibberulus and Bulla ii,ibbosa is Bulla gibbosa.  Conus ebraens is probably a similar OCR misreading so I would delete that taxon.

I'm not a SQL user so it would be helpful to have a (for me) user friendly way to delete taxa.  If SQL is the only available approach, Bryan can probably handle it and train me as well.

**Comment by dustymc** [comment]
I think that's most always an "expert" call, and I know of a couple cases where they can't agree. (One involves the author spelling a name a few different ways in the type publication!) My only concern is in not introducing outright garbage - if there's a "someone believed it at some point" publication (maybe not the OCR version!) then the name is probably sufficiently taxonomy-like for me, ya'll can sort out the details.

I can add a button for this, I was just clarifying that if I get abducted by aliens before I can do that it's still not impossible to delete them.

**Comment by Jegelewicz** [comment]
If you get abducted by aliens, please tell them there are others who would like to go.

I have accidentally misspelled a taxon and it would be nice to just delete it right then and there, before it becomes part of the problem....

**Comment by sharpphyl** [comment]
Thanks, Dusty.  We'll be conservative in what we delete.

We'll hope the aliens hold off until the button is complete.

**Comment by dustymc** [comment]
done
