### ISSUE TITLE
ID Dates for Art collection

### ISSUE THREAD

**Issue by krgomez** [ArctosDB/arctos#1593]
When we imported our Art collection records I didn't realize that an ID Date was not required. As we don't know precisely who cataloged much of the Art collection and when, I used unknown for determiner and 1900-01-01 as an obvious unknown flag date. However I don't really want that date there if it doesn't have to be there. Is it possible to strip the ID dates for which the value is 1900-01-01 since it is not required? Almost all Art records have this ID date, with the exception of a few. I also used 1900-01-01 for unknown dates for attributes, but of course want those to stay as they are.

**Comment by dustymc** [comment]
>ID Date

done

>attributes

```
UAM@ARCTOS> desc attributes
 Name								   Null?    Type
 ----------------------------------------------------------------- -------- --------------------------------------------
 ATTRIBUTE_ID							   NOT NULL NUMBER
 COLLECTION_OBJECT_ID						   NOT NULL NUMBER
 DETERMINED_BY_AGENT_ID 					   NOT NULL NUMBER
 ATTRIBUTE_TYPE 						   NOT NULL VARCHAR2(60)
 ATTRIBUTE_VALUE						   NOT NULL VARCHAR2(4000)
 ATTRIBUTE_UNITS							    VARCHAR2(60)
 ATTRIBUTE_REMARK							    VARCHAR2(4000)
 DETERMINATION_METHOD							    VARCHAR2(255)
 DETERMINED_DATE							    VARCHAR2(22)

```

it's NULLable if you change your mind.
