### ISSUE TITLE
Delete CUMV records and collections

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#1594]
CUMV records and collections can be deleted from Arctos per the following email dated May 10, 2018. As discussed in an AWG meeting, no reason to delete localities or agents or other shared data they created. 

******
Hello Carla,

I think you can finally take down Cornell’s data from Arctos.  Dave is very close to having us pushed to VertNet and we have our data up and searchable on a Specify Web Portal.

Sorry for the drawn out and overlong process.

 Charles

Charles M. Dardia
Collections Manager
Cornell Museum of Vertebrates
159 Sapsucker Woods Road
Ithaca, NY 14850
(607) 254-2161
http://www.cumv.cornell.edu/

**Comment by dbloom** [comment]
The CUMV resources were republished this morning outside of the historic Arctos links.

**Comment by dustymc** [comment]
done

**Comment by ccicero** [comment]
Email from Charles Dardia 14 Oct 2019 to Carla and Dusty:

Hi guys,

When you took the CU data off Arctos did you save a copy of the data or did you delete it?  I am finding more discrepancies than you could imagine from my original data (Specify 5) and what I have now.  Example, Specify 5 data had 81 records where county is Tompkins and specific locality is unspecified.  Now I have 4027 records that fit that criteria.  Would really like to figure out where the problem was generated and if possible figure out how to fix it.

I think there are only 2 options, when the data was migrated to Arctos the records were attached to the incorrect locality id or the same happened moving from Arctos back to Specify.

@dustymc @lkvoong Can one of you respond?

**Comment by dustymc** [comment]
I don't have that readily available. It might be in some old backup, but I don't know how we'd find the resources to do anything with that or what TACC's recycle path looks like.

The incoming data was reviewed by CUMV before loading, and was widely available in Arctos for some time. It's hard to imagine something like this would have been missed there, but I suppose it's possible.

The export was just table segments, I can see no way that keys could have been misaligned in that.

**Comment by tucotuco** [comment]
I looked on VertNet's task list to see what I could find about CUMV's
history. @David Bloom <dbloom@vertnet.org>  made a migrator for them coming
out of Specify, but I don't see a history of us having done anything to
help get the original data into Arctos. If we did, maybe there would be a
checkpoint for troubleshooting. There are old VertNet snapshots that would
have CUMV data from before their move to Arctos as another possible
checkpoint.

**Comment by ccicero** [comment]
Didn't they put their data into a Dropbox folder? Can we look there?

**Comment by tucotuco** [comment]
We have data in Dropbox from 2017-09-15 and 2019-11-13 for mammals,
2018-03-22 and 2019-11-19 for Birds, 2017-09-15, 2018-03-22, and 2019-11-12
for Fish, and 2017-09-15 and 2019-11-12 for Herps.

**Comment by ccicero** [comment]
Thanks John! I think we should send those files back to Charles with the information on dates when they were put into Dropbox. That's probably the best we can do. Thoughts?

**Comment by dbloom** [comment]
@ccicero I will do that. I received those datasets from them directly when migrators were built. We did not take anything directly from Arctos. I will Cc appropriate folks.

@tucotuco please note I am @dbloom in GH.

**Comment by ccicero** [comment]
Thanks @dbloom !
