### ISSUE TITLE
AWG Code Table Administrator

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1597]
I propose that we add the position "Code Table Administrator" to the AWG.

It should not take two months to get parts, attributes, or other code table items added. Requests for these types of additions often go unnoticed which means that someone is not getting their data in or they are using less-than-perfect means to do so. I think it would be good to have at least three people responsible for monitoring the GitHub for these kinds of requests and assisting with getting them cleared up. We also need to make sure we have some good guidelines for such additions written in the documentation so that we don't just start adding things willy-nilly without definitions.

**Comment by campmlc** [comment]
I support this.

**Comment by Jegelewicz** [comment]
From AWG meeting:

> Who has access to Code Tables? Add/Change CT info
>         -when issues come up, we know who to ask to follow up
>         -CT Label / Assignment link so folks who can do this can keep track
>         -remove this task from Dusty - CT editors as distinct group
> 
> Shared table monitors who volunteer to help fix problems, review bad/low data reports (e.g., agents, geographies, etc.)
> 

Any opposition to creating a Group Agent in Arctos and adding all who have code table access to it?

**Comment by campmlc** [comment]
No objection to group agent. As Co-Chair I have access and I believe Carla
does too. Anyone else?

**Comment by Jegelewicz** [comment]
I also set up a team on GitHub. @ArctosDB/arctos-code-table-administrators so that people filing issues can tag you all. Please add anyone else who should be on the list.

**Comment by jldunnum** [comment]
I have access to code tables but have refrained from using it.


______________________________________________________________

Jonathan L. Dunnum Ph.D.
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by dustymc** [comment]
See eg https://github.com/ArctosDB/arctos/issues/1451#issuecomment-370029932. I don't think most users can manage Issues enough to properly tag anything, so the new team seems like unnecessary complication.

Alternatively, we could give more people code table access - authority changes are emailed out, we're all carefully reviewing that (right!?!), so maybe it's OK if eg, all active AWG members can create authority values (which are then reviewed via the email).

https://github.com/ArctosDB/arctos/issues/1450 is critical to any approach. We can't possibly tell if a new value is actually new when there are undocumented existing values.

It should not be possible to add or edit values without providing documentation, but it's certainly possible to provide useless documentation.

Code table documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Code-Tables.html

**Comment by dustymc** [comment]
Can github send email when a {project/label/something} issue is filed?

**Comment by campmlc** [comment]
Code Table Committee
Mariel - point, MSB
Carla -MVZ Bird
Aren -UAM Mamm
Angela - Cultural
Michelle- MVZ
Mary Beth: Alabama paleo

**Comment by campmlc** [comment]
Add Emily Braker (needs permissions), Anna Chin (needs permissions)

**Comment by campmlc** [comment]
Code table permissions granted to Emily and Anna

**Comment by AJLinn** [comment]
I also don't have code table permission. Should I have that access added or just rely on Aren to make cultural changes?

**Comment by amgunderson** [comment]
You now have code tables permissions Angie, proceed with caution...

**Comment by AJLinn** [comment]
Thanks. Since i don't even know how or where to go to make changes, I'm pretty safe for now... ;-)

**Comment by mkoo** [comment]
Committee created and CT projct made

**Comment by dustymc** [comment]
We done here? Tentatively closing....
