### ISSUE TITLE
Make "trap" attributes available to all collections

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1600]
These attributes are currently only available for Mamm collections, but it seems they would be useful for all collections. Please add the following definitions to these attributes AND let ALL collections use them. I specifically need them for an Ento collection.

> trap identifier - A value that refers to a specific trap used to capture the specimen.
> 
> trap type - A description of the trap used to capture the specimen. This might include pitfall, hoop net, mist net, etc.

Perhaps we need a code table for trap types? This would definitely help to normalize that data....

**Comment by dustymc** [comment]
>trap identifier

That looks like an otherID to me and I'm not sure why it's in Attributes. Can it be moved? OtherIDs are not collection-type specific.

```

select 
  guid_prefix,
  count(*) 
from 
  collection,
  cataloged_item,
  attributes
where
  collection.collection_id=cataloged_item.collection_id and
  cataloged_item.collection_object_id=attributes.collection_object_id and
  attribute_type='trap identifier' 
group by 
 13    guid_prefix;

GUID_PREFIX						       COUNT(*)
------------------------------------------------------------ ----------
DMNS:Mamm							      1
MVZObs:Mamm							     90
MVZ:Mamm							    576

3 rows selected.
```

@jrdemboski @ccicero 


>all collections

I don't think Art collections do much trapping.

>code table for trap types

We can do that, if we can keep the possible values both finite and useful. Not looking too bad so far...

```

select 
  attribute_value
from 
  attributes
where
  attribute_type='trap type' 
group by 
  8    attribute_value;

ATTRIBUTE_VALUE
------------------------------------------------------------------------------------------------------------------------
Tomahawk trap
Sherman live trap
Victor snap trap
33 KHz sound-baited harp trap
Macabee trap
sound-baited harp trap
Museum Special
tomahawk
sound-baited bat trap
snap trap
Tail length: [72] mm
sherman
Sherman trap
```

**Comment by dustymc** [comment]
>I can see reasons for both other IDs and attributes.

I certainly can't! If those data are only important after you've found the specimen, then putting them somewhere arbitrary in the specimen record (some remarks field maybe) serves the purpose. If they're identifiers by which someone might want to search, they should be in the same place as all other identifiers by which someone might want to search - OtherIDs.

>date and determiner and remarks

Identifying numbers are "facts" - they're scribbled on the datasheet (trap, whatever) or they're not. If you and I "measure" the same number and get different results, at least one of us is just wrong. 

"Same place" is why locality_name exists.

**Comment by campmlc** [comment]
In the context of how these trap identifiers are used, they are closer to a
collecting event identifier or nickname. In fact, at MSB we've replaced
recording trap IDs with GPS unit waypoint numbers, which are still
problematic because, like trap numbers, they recycle and start over
everytime the unit downloads the waypoints. That is why having some
date/time info associated with the ID is useful. Yes, you can get this from
collecting event, having the date directly associated with the ID/attribute
is useful to avoid confusion.

**Comment by dustymc** [comment]
>downloads the waypoints

Are you uploading those data to Arctos? I think I have code to do that somewhere, but AFAIK only I've ever used it so I'm not sure it's public or maintained.

A download should not reset the GPS's incrementing - maybe that's in whatever software you're using? You'll still end up with a "1" from every GPS unit, but that can be dealt with by organizing (eg, make sure a GPS is tied to a single user/dataset/something).

>date/time info

You should be able to include that in the download/upload.

**Comment by campmlc** [comment]
The data are in Garmin GPS units which have proprietary software. Waypoints
get downloaded from the unit to a file. Data from the file are uploaded to
Arctos either in a bulkload file or through copy/paste during locality
creation - ask the mammal folks. I'm sure they'd appreciate anything to
make that easier.  The idea is to avoid manual transcription.

The Garmin software causes the GPS units to reset back to 1 after every
download. We have "named" the units, but there are going to be many, many
"Red 001" waypoints, for example. The difference will be tied to collecting
event.

**Comment by campmlc** [comment]
Also, the waypoints, like trap identifiers, tie into field notes and field
data sheets for a particular collecting trip. So Red 001 could be in field
notes from many different people, localities and dates. Hence the benefit
of a determiner and date field.

**Comment by dustymc** [comment]
I suspect there's some setting in your software - I use Garmin+BaseCamp and it definitely doesn't reset anything.

>field notes

collector number | A value that refers to a person's field catalog.  For this  number to be applied to a specimen, the person has to be the first  collector of a specimen.

http://arctos.database.museum/info/ctDocumentation.cfm?table=CTCOLL_OTHER_ID_TYPE

**Comment by campmlc** [comment]
Ento added to code table 8-6-2018.
