### ISSUE TITLE
Flag bad data when logged in

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1601]
I recently discovered two taxa with bad classifications in Arctos in a collection I don't manage, when logged in, I can correct the classifications, but one of them is a non-existent species name which really should be removed from Arctos. As it is being used by a specimen, I can't just delete it so I had to open another browser and add an annotation to the classification. Would it be possible to add the "report bad data" function to classification pages when logged in and to have any collection using that taxon to be notified of any annotation?

**Comment by dustymc** [comment]
This??

<img width="1402" alt="screen shot 2018-07-16 at 8 20 16 am" src="https://user-images.githubusercontent.com/5720791/42767301-7603a90c-88d1-11e8-9cca-2b88b36b2b63.png">

**Comment by Jegelewicz** [comment]
Yep. I probably wasn't too clear above. What I'd like to know is, if I make an annotation to a taxon, could we have that notice go to all data quality managers with collections using that taxon? If that already happens, awesome!

**Comment by dustymc** [comment]
Yup, it goes to collections.


<img width="751" alt="screen shot 2018-07-16 at 8 49 03 am" src="https://user-images.githubusercontent.com/5720791/42768729-24ae89a6-88d5-11e8-98af-1f5e4d303a84.png">
