### ISSUE TITLE
Classification does not transfer to iDigBio unless it is in Arctos

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1602]
If a taxon does not have an Arctos classification, when the data transfers to iDigBio, it shows up with just a species name and iDigBio adds the rest of the classification. This shows up as hundreds or thousands of data flags in iDigBio related to Arctos provided data. I can go through all the taxa without an Arctos classification and clone one in, but I wonder if we couldn't fix this some other way, either by picking a default classification if there isn't one in Arctos so that we don't just transfer species names without any context or magic-ing in classifications from a default when one is not there. Both of these are possibly dangerous, but right now it looks like we serve up crappy data.

**Comment by dustymc** [comment]
"We don't have this information" is always a defensible position, and most users react appropriately when they encounter a NULL.

"We don't have this information, so we made something up" is evil.

I will not knowingly be the provider of garbage. iDigBio can do whatever the license they get with those data allows.

I can help find names without classifications, but I can't find names with somehow-funky classifications. I think the best approach is generally just to replace classifications at the level of family-or-so with the hierarchical editor.
