### ISSUE TITLE
Encumber Agent information for public searches

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1603]
From GDPR issue #1500 

When a person is not logged in to Arctos, they should only be able to see that an agent exists in Arctos. We need additional discussion about account holders and operators, but between GDPR and FERPA, it seems like it would be a good idea to keep Agent information hidden from those without an Arctos user account.

**Comment by dustymc** [comment]
This just seems paranoid to me, and I'm not anxious to disable a critical feature of Arctos for a rule which doesn't seem to apply to us. Agent information is an increasingly important pathway for accessing specimen data, and I'm not going to remove it without good reason.

I don't think there's anything in the GDPR exempting users who've created an anonymous account...

**Comment by Jegelewicz** [comment]
@mkoo asked to revisit this, so I hope she will chime in here.

Notes from AWG meeting 2018-07-12

> Issue #1500 (GDPR)
>         What are the privacy issues? For public users
>         Ability to encumber info in agent records
>         Privacy policy; opt-in/-out
>         FERPA

I think the FERPA line is important and deserves consideration when we are putting student names on a public website.

**Comment by Jegelewicz** [comment]
Also, all that is requested above is that a person create an Arctos user account in order to see the Agent information. We make people do that to send a "join Arctos" request, I don't think that it is too much to ask in order to get at our Agent details.
