### ISSUE TITLE
Arctos Working Group Membership

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1604]
From AWG meeting:

> Arctos Working Group email list --  MK: right now I have a four other requests to join (I approve Vicky Zhuang since she is an Arctos user at UTEP) but the others are not as far as I know. So what’s the protocol here? Can I invite them to receive our newsletters instead (if they are not Arctos collections and just want to learn more?)? Do we have a subscription link for the newsletter? 
> We need a process to add people to the Working Group first. We need to have people who send the requests add their name and institution and request to join, and then when that is approved they can be added to the email list.
>

**Comment by Jegelewicz** [comment]
I propose that every institution should have at least one person on the AWG. We could have new collections provide the contact info for their AWG member when they complete the collection creation request portion of the new collection process.  Requests for additional members should go through the AWG Membership Chair (yes, I just created a new officer of the AWG).

Membership Chair duties could start with:

1. Maintain the AWG Google Group membership
2. Maintain the AWG Group agent in Arctos
3. Welcome new AWG members
4. Encourage participation in AWG meetings and committees

**Comment by Jegelewicz** [comment]
> So what’s the protocol here? Can I invite them to receive our newsletters instead (if they are not Arctos collections and just want to learn more?)? Do we have a subscription link for the newsletter?

I suggest that anyone not an operator in Arctos should be directed to join the [Arctos Google Group](https://groups.google.com/forum/?hl=en#!forum/arctos). The newsletter should be sent to members of this group as well as the [AWG Google Group](https://groups.google.com/forum/?hl=en#!forum/arctos-working-group).

**Comment by jldunnum** [comment]
Agreed


______________________________________________________________

Jonathan L. Dunnum Ph.D.
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by Jegelewicz** [comment]
> Regarding the non-operator access to the newsletter, should we at least require that they have create a user profile with institutional affiliation in Arctos?

That is fine with me. Who manages the Arctos Google Group?

**Comment by campmlc** [comment]
Carla and I have Arctos Google Groups access. Probably all AWG officers should have it.

I'm reconsidering newsletter access. We have a link at https://arctosdb.org/news/ to the twitter post with the mailchimp address for the July newsletter. I've been thinking we should add newsletter links to the banner, and have an archive of previous newsletters on the arctosdb website. If so, we would not be able to require login access.
Thoughts?
@Jegelewicz 
@ccicero @AJLinn @KyndallH 

Here are the current pending member requests for the AWG: what do we do with these?

![awg join requests 7-20-18](https://user-images.githubusercontent.com/14808196/43030156-9a445f80-8c52-11e8-9deb-967c20266d6d.png)

**Comment by AJLinn** [comment]
> We really need someone to help keep track of current, incoming, and
previous officers as well as AWG members. A historian role.

I set up a spreadsheet for Museums Alaska for our current/former board members that was key in keeping everyone aware of our organizational history as well as the terms for the 9 seats on the board. I'd be happy to set up a similar one for Arctos, just to get us rolling. But of course, I don't have any of the data other than our current setup.

**Comment by dustymc** [comment]
>Berkeley one

Please don't, happy to chat privately re: why.

**Comment by mkoo** [comment]
The Berkeley requester is not an Arctos user (I agree with Dusty), which is
why I brought the whole thing up.

Seems to me the Newsletter is public and so anyone with an interest in
Arctos can be added to that list (wherever it is). AWG should be only the
designated Arctos users for an institution (that seems to be the consensus.

So is the Arctos google group for everyone else using Arctos?

do we have a public signup for the newsletter so that can be for anyone
anywhere (it that its intention)?

I have access to the listserves so I can add what their intended audience
and criteria are in the descriptions to avoid confusion in the future but
I'm still a bit confused.

Can this be top of agenda since this seems easy to agree on if we lay it
all out.

**Comment by Jegelewicz** [comment]
All current AWG members are part of the [AWG group](http://arctos.database.museum/agents.cfm?agent_id=21314876) and when they leave, they are moved to the [AWG Alumni Group](http://arctos.database.museum/agents.cfm?agent_id=21314877)

This way everything is maintained in Arctos. It should be done by the Membership Chair...

**Comment by Jegelewicz** [comment]
> Seems to me the Newsletter is public and so anyone with an interest in Arctos can be added to that list (wherever it is). AWG should be only the designated Arctos users for an institution (that seems to be the consensus.

Arctos Google Group should be this list.

> So is the Arctos google group for everyone else using Arctos?

Should be, but could include anyone interested.

> do we have a public signup for the newsletter so that can be for anyone anywhere (it that its intention)? 

Again, I say it should be the Arctos Google Group

> I have access to the listserves so I can add what their intended audience and criteria are in the descriptions to avoid confusion in the future but I'm still a bit confused.

Arctos Working Group - only members should be Arctos operators who have agreed to participate in the AWG

Arctos Group - anyone else with an interest in Arctos.

All of the above are my opinions, I could be wrong...

**Comment by KyndallH** [comment]
I love the idea of an Arctos Membership Chair.

Links to the two previous newsletters are also on the Arctos webpage (https://arctosdb.org/category/tips/). Right now it is under the tips category - do we want to start a separate page of archived newsletters?  If you click the link to go to any of the newsletters, there is a tab that says past issues where it has all past issues of the newsletter.

I always thought the Arctos Group was for users. The description of the group is listed as "Use this group to discuss issues that affect all Arctos users. Appearance changes, data presentation changes, and functional changes are all fair game. Continue using the bug report form to report site or data errors." Granted, most of the messages have been about the webinars and the newsletter.

**Comment by campmlc** [comment]
I think we should put the public info such as newsletters on the website
and keep the Arctos users group for users.

**Comment by Jegelewicz** [comment]
> I think we should put the public info such as newsletters on the website and keep the Arctos users group for users.

So how do we create a mailing list for non-Arctos users to send out the newsletter? Just posting it on the website isn't enough, we have to drive people to it.

**Comment by campmlc** [comment]
Maybe a public Arctos google group or listserv?

**Comment by dustymc** [comment]
There's a maximum efficient size to the AWG, but we can worry about that when more than ~a dozen folks are regularly showing up to the meetings. Until then, anyone who's more or less acting as a collection manager could be invited. (Eg, I wouldn't want to preemptively exclude long-term students.) The AWG (list and group) should be "core" Arctos users.

Issues should be used for all "how stuff works" discussions. That's what the group was started for, but Issues are much better. We should encourage Arctos users to receive notifications and etc. - http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

I'm not sure what the Arctos group does now. I think it's useful for announcements, but perhaps we should be pulling active Operators from Arctos instead. (Which excludes people who just haven't logged in for a while - not ideal.)

The newsletter should be a bit PR-ish and suitable for anyone.

>how do we create a mailing list

IDK, but it should have subscribe and unsubscribe links.

**Comment by mkoo** [comment]
real fast thought: mailchimp has a signup email function, right? Emails to
public list can be managed there directly I believe.

**Comment by Jegelewicz** [comment]
Closing as superseded by procedures being developed by @lin-fred
