### ISSUE TITLE
Duplicate Agent report

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1606]
@dustymc can you fix the duplicate agent report so that agents that have been marked "not the same as" won't show up on it?

![capture](https://user-images.githubusercontent.com/5725767/42662798-307b4a7c-85f0-11e8-9936-a29244a5686e.JPG)

These two agents had already been marked "not the same as" so we shouldn't be seeing them in low quality data reports.

Thanks!

**Comment by dustymc** [comment]
There is and always has been a "no relationships" option??

**Comment by Jegelewicz** [comment]
Oh, yeah at the bottom of the list. Thanks.
