### ISSUE TITLE
Arctos and iDigBio - my SPNHC presentation will make Arctos look bad, please help

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1607]
I will be making a contribution to the "Challenges for Implementing Collections Data Quality Feedback: synthesizing the community experience symposium" at SPNHC. I was asked to talk about collections' experiences with the iDigBio Data Flags. It seems that no Arctos users have made use of these flags, so I went on a mission to make use of some myself. One thing that I discovered is that ANY classification higher than genus has a "species" inserted into the classification, thus all of UTEP AVES appear to iDigBio as _Aves sp._ As there is no such thing, iDigBio looks for the closest possible real species and I end up with our Aves being turned into the genus avus (an insect) by iDigBio.

See [record in Arctos](https://arctos.database.museum/guid/UTEP:ES:36-29)

See [iDigBio](https://www.idigbio.org/portal/records/18805a8a-84d0-4ecd-8e56-013ce3a0b21f)
.
Apparently UTEP also has a bunch of bats that are being published by iDigBio as stick insects. This is going to look very bad when I make my presentation because we are sending iDigBio bad information. We need to find a solution to this problem. ANYTHING that is not identified to at least genus is subject to this problem. In fossil collections this can be a lot of stuff. I don't want to stand in front of SPNHC/TDWG and say that we can't figure out how to properly present identification of higher taxa. Please help!

#1576

**Comment by dustymc** [comment]
Arctos seems to be providing accurate information in the proper places. What would you like me to do here??

https://github.com/ArctosDB/arctos/issues/1576 was (in part) from NOT providing the intended info - which still isn't Arctos being broken, it's whomever's using classifications with which they don't agree.

A specific bat/insect example would be useful.

**Comment by Jegelewicz** [comment]
I do not believe we are providing accurate information in proper places. iDigBio finds Arctos' Aves as a genus rather than a class because of this:

![capture](https://user-images.githubusercontent.com/5725767/42767402-1e290ce6-88da-11e8-8b9c-18fa5de82e17.JPG)
 
and does its best to figure out what the heck we mean by genus Aves.

iDigBio finds Arctos' Chiroptera as genus rather than an order because of this:

![arctos chiroptera](https://user-images.githubusercontent.com/5725767/42767727-03886bce-88db-11e8-83c2-0641ab004de1.JPG)

and does its best to figure out what the heck we mean by genus Chiroptera.

Here is a Chiroptera specimen in iDigBio:
![utep chiroptera](https://user-images.githubusercontent.com/5725767/42767771-18fd75f8-88db-11e8-9f04-ecdfb376243b.JPG)

I believe that we need a way to get rid of the lower ranking items in higher taxa if we want to provide correct information in proper places.

**Comment by dustymc** [comment]
Those are suggestions, which exist to prevent more common problems, and should be removed before saving. Perhaps we should be tracking who edits classifications??

My suggestion is still to deprecate that form.

"Accurate" maybe isn't the right word - we're accurately providing what someone entered, and the "someones" editing taxonomy should be a short list of vetted users. The data themselves aren't necessarily accurate.

Those both look good to me:

<img width="1324" alt="screen shot 2018-07-16 at 8 40 07 am" src="https://user-images.githubusercontent.com/5720791/42768361-26dcb370-88d4-11e8-9791-090488e630ba.png">

<img width="1266" alt="screen shot 2018-07-16 at 8 42 37 am" src="https://user-images.githubusercontent.com/5720791/42768391-3fcbe8ba-88d4-11e8-9bbf-f2a957f2a514.png">

Maybe iDigBio needs to be refreshed?

**Comment by Jegelewicz** [comment]
My experience is those genus suggestions cannot be deleted. They just pop up when higher taxa are created.

Sure, they look good there, but just go to edit them and that genus suggestion is there and based upon what is happening at iDigBio, they are getting that information no matter what you see above.

> Maybe iDigBio needs to be refreshed?

Maybe - I don't know when or how that happens. Can @dbloom help?

**Comment by dustymc** [comment]
>genus suggestions cannot be deleted

Sure they can - just click "Delete this row."

https://github.com/ArctosDB/arctos/issues/1188#issuecomment-314566131

**Comment by Jegelewicz** [comment]
Did that - go to edit again and there it is.

**Comment by dustymc** [comment]
added another big red warning to the single-record edit form.
