### ISSUE TITLE
Move the scary red box on Edit Container

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1611]
Currently when you use the Edit Container function, you see this:

![image](https://user-images.githubusercontent.com/5725767/42954844-8f0ba056-8b3a-11e8-922c-9aaef9e07a87.png)

I propose that the "scary red box" be moved to the bottom of the page. It isn't used very often and just makes the whole form appear scary rather than something useful for managing barcodes and labels. In fact, it might be better to put the "donor barcode" function somewhere by itself. Maybe add a line here that says "Add donor barcode" or something else that would make sense.

![image](https://user-images.githubusercontent.com/5725767/42955546-f6806ffa-8b3a-11e8-9b0c-707d7b8a5358.png)

**Comment by campmlc** [comment]
That's OK by me. It would help to keep people from using it by accident to
have it at the bottom.
 While we are changing the page, can we make the Update button a Save
Changes button instead and make it large and obvious?
 Right now students looking for save tend to see the Save associated with
container check.

**Comment by dustymc** [comment]
done
