### ISSUE TITLE
LastPartLocation ≠ PLPath ?

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#1614]
This is partially associated to issue #1183 and #1561 and #1585 I think!

Now that we're only adding barcoded locations to newly accessioned materials, my "LastPartLocation" column in my search results is starting to show up blank, and when I've tried to use the "partdetail" column I can't sort my results.

Compare old using LastPartLocation and sorting by that column:
![ss_lplocsort](https://user-images.githubusercontent.com/17605945/43029029-e63da6bc-8c2f-11e8-9a59-edbde7850d08.jpeg)

And the new partdetail:
![ss_partdetail](https://user-images.githubusercontent.com/17605945/43029040-faa4a466-8c2f-11e8-8ac3-fb4d38c6132c.jpeg)

Will the LastPartLocation ever be able to extract that PLPath info the same way the LastPartLocation was able to? That was sooo nice...

**Comment by campmlc** [comment]
Is it possible to have both displays as an option in the tools menu?

**Comment by dustymc** [comment]
Those are very different kinds of data, so I don't think they'll be talking to each other. (Not impossible, just seems weird/inefficient at first glance...).

There's a part map available from the Manage widget on SpecimenResults:

<img width="426" alt="screen shot 2018-07-25 at 8 26 20 am" src="https://user-images.githubusercontent.com/5720791/43210916-3c8cce18-8fe5-11e8-914b-13b091b05fc1.png">

<img width="683" alt="screen shot 2018-07-25 at 8 32 25 am" src="https://user-images.githubusercontent.com/5720791/43210951-49c47946-8fe5-11e8-9f4a-23da911909a7.png">

It has a few view options at the bottom left. That is a "core feature" of Arctos - it works everywhere, it works for specimens with hundreds of parts, most everyone benefits from updates to it, etc. - it's a much more powerful tool than anything that could be injected into a table cell, and it's a better investment than something which only works in specialized cases. Does that work for you/can it be made to work for you?

**Comment by dustymc** [comment]
>both displays as an option in the tools menu

Clarify, please.

**Comment by campmlc** [comment]
If I understand correctly, Angie requested a sortable column with
LastPartLocation. We replaced that with partdetail. I'm just wondering if
she can keep LastPartLocation as an option that can be selected from the
Customize Form menu if she prefers to that field instead of partdetail.

**Comment by dustymc** [comment]
Ah - yes, I don't have any reason to remove LastPartLocation. Partdetail isn't really a replacement, it just contains the same sort of information when barcodes are involved.

**Comment by AJLinn** [comment]
> If I understand correctly, Angie requested a sortable column with
LastPartLocation.

We already have that and it works great. It's just that now we're starting to have BOTH barcoded locations (which either result in no info in the LastPartLocation column or incorrect if the item moved from the time we manually entered the location as a Part Attribute) and manually entered data. It creates some confusion - we still have the majority of the collection not barcoded by location but as we get more done, I'm just trying to figure out what our new system is going to be. The LastPartLocation is such a great tool that Dusty developed for us, I hate to have to learn a new system! :-)

**Comment by dustymc** [comment]
>movements thru the compact mobile storage to be more systematic and efficient

Hierarchies are structurally sorted - "small things" are children of "big things" - so that shouldn't be too difficult to deal with. There's an Issue to sort the tree better somewhere and I think I now know how to do that without linguistic indexes, which should help a bit more.

**Comment by KyndallH** [comment]
I talked to Angie. What she'd like is in LastPartLocation is what is currently there if the part is not barcoded (so what is currently displayed) and IF the part is barcoded, she'd like the parent label for the object barcode. If the part is barcoded, the LastPartLocation should be empty. Any way to merge that information into one field?
