### ISSUE TITLE
Legacy higher geography for Americas

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1615]
I'm looking over data records for the Netherlands Naturalis collections, and they have some older collections that have geographic determination of specimens to the Americas, but no further precision. Can we have higher geography at the level of "North America", or "Central America", with no country assigned? Other ways to deal with these old types of data?

"Amer. Sept."
"Amerique Meridionale"
"Amerique du Nord."
"Amer. Sept."

**Comment by dustymc** [comment]
https://arctos.database.museum/geography.cfm?geog_auth_rec_id=4962

**Comment by campmlc** [comment]
Please add:
Central America
https://en.wikipedia.org/wiki/Central_America
South America
https://en.wikipedia.org/wiki/South_America

and
Americas
https://en.wikipedia.org/wiki/Americas

**Comment by Jegelewicz** [comment]
Central and South America are there.

Americas is interesting because I can see how it might be an actual higher geography in old European collections so I added it.
