### ISSUE TITLE
Requests for new attributes and parts

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1617]
Would it be possible to create a form in Arctos that allows an operator to to request new parts and attributes? This way, we could require the requester to provide:

for Attributes - an attribute name, attribute definition, attribute value type (a list of possible terms with related definitions, a numeric value, agent name, etc), collection type(s) the attribute pertains to

for Parts - a part name, part definition, collection type(s) the part pertains to

There is probably something I've missed above, but I hope it make sense.

I'm trying to think of a way to make such requests more complete from the beginning so that we don't have to spend time on back and forth with "What's the definition?, Which collections might need this? and such. These requests could be sent out in the same way that warnings about duplicate agent mergers are. If anyone has an issue with a request, they could block it and start an issue here, otherwise, the request could go forward.

Ideas appreciated!

**Comment by mvzhuang** [comment]
If it helps, Github can also do issue templates if it can't be done in arctos.

https://blog.github.com/2016-02-17-issue-and-pull-request-templates/

**Comment by dustymc** [comment]
>back and forth 

That's a feature, not a bug!

There are two pathways to new Authorities in Arctos:

1. Someone requests what they actually need, we add it, people use it.

2. Someone requests what they think they need, we implement it, they spend a bunch of time shuffling data around, training students, etc. We realize it won't do what needs done, there are long discussions (which are complicated by "but I've spent months getting here!"), a bunch of stuff gets rebuilt, students get retrained, data in bulkloader format hangs around being a pain for months, etc.

(2) is a giant mess for everybody. Sorting that out beforehand saves a ridiculous amount of work and frustration, and Issues are a useful place for that discussion. I'd not want to give that up.

> issue templates

Neat!

<img width="984" alt="screen shot 2018-07-25 at 6 43 40 am" src="https://user-images.githubusercontent.com/5720791/43204684-690ee32c-8fd6-11e8-9533-c7be3a0715cd.png">

Please try them out.

"Arctos gives me what I need, not what I want."
    -Gordon, I think

**Comment by Jegelewicz** [comment]
YES! @mvzhuang thanks for the heads up and @dustymc for creating the templates!!! I will try one next time I have a request.
