### ISSUE TITLE
Please add collections for Other ID Types

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#1618]
**Table**
http://arctos.database.museum/info/ctDocumentation.cfm?table=CTCOLL_OTHER_ID_TYPE

**Values**
UCM Egg
UCM Herp
UCM Fish

**Definitions**

University of Colorado Museum egg collection catalog number
University of Colorado Museum herpetology collection catalog number
University of Colorado Museum fish collection catalog number

**Context**
I need the above values in the Other_ID_Types table so that I can create relationship links between records. Our other UCM collections are represented, just these collection types are missing.

**Comment by dustymc** [comment]
done
