### ISSUE TITLE
New Attribute

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1619]
**Table**
ATTRIBUTE_TYPE

**Value**
anteroposterior length

**Definition**
In mammal teeth a measurement of the maximum distance between the anterior and posterior surfaces of the tooth. (See [https://doi.org/10.1371/journal.pone.0183045.g003](https://doi.org/10.1371/journal.pone.0183045.g003))

**Collection type**
Mamm, ES

**Attribute data type**
number+units

**Attribute value**
numeric value

**Attribute units**
 LENGTH_UNITS

**Context**
This measurement was provided by a researcher in a publication and should be added to the specimen records. Standard measure for fossil teeth.

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/1620

**Comment by dustymc** [comment]
Does this (and #1620) apply to a specific part?

"anteroposterior tooth length"?

"anteroposterior [M/m/I/i/etc][1-??] tooth length"?

??

**Comment by Jegelewicz** [comment]
I think it could apply to a lot of other parts. As opposed to just length and width, it makes the measurement a bit more defined. In my case it is being applied to teeth, but it might have application elsewhere.

See: [Anteroposterior](https://www.medicinenet.com/script/main/art.asp?articlekey=9281)

**Comment by campmlc** [comment]
I think it makes sense to have it specify the part, to avoid getting a bunch of unrelated search results.
Suggest "tooth length, anteroposterior" to correspond with our other formats.

**Comment by campmlc** [comment]
Discussed with Teresa, OK with "tooth length" as attribute, anteroposterior in definition.
