### ISSUE TITLE
New Attribute

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1620]
**Table**
ATTRIBUTE_TYPE

**Value**
transverse width

**Definition**
In mammal teeth a measurement of the maximum distance between the medial and lateral surfaces of the tooth. (See [https://doi.org/10.1371/journal.pone.0183045.g003](https://doi.org/10.1371/journal.pone.0183045.g003))

**Collection type**
Mamm, ES

**Attribute data type**
number+units

**Attribute value**
numeric value

**Attribute units**
 LENGTH_UNITS

**Context**
This measurement was provided by a researcher in a publication and should be added to the specimen records. Standard measure for fossil teeth.

**Comment by dustymc** [comment]
From https://github.com/ArctosDB/arctos/issues/1597

> good guidelines for such additions written in the documentation 

My reservation here is that we now have ~200 attributes, half-ish undocumented (https://github.com/ArctosDB/arctos/issues/1450). Some (most!?!) of the "documentation" we do have is not useful for any purpose: "measured how?" or "Standard beak measurement for birds". These things have become numerous enough to start causing problems merely by existing.  (Operators and researchers may not find what they're looking for, turning them all on causes serious performance problems, etc.) 

This request is clearly data which can fit in Attributes. There's a good definition. Given enough of it, we could ask Arctos cool questions about horse teeth.

We could also push it to Media or structured data or similar, which would support the same questions but with a lot more work.

A "these things are Attributes" definition from the AWG would be very useful. (I'd probably vote to continue adding anything that fits and looking for solutions to the problems that causes, but I don't think this is my call.)

Here are existing Attributes by frequency of usage. Can anything that's not used much be removed or merged or ??

```

UAM@ARCTOS> select ATTRIBUTE_TYPE || ' @ ' || count(*) from attributes group by ATTRIBUTE_TYPE order by count(*) desc;

ATTRIBUTE_TYPE||'@'||COUNT(*)
------------------------------------------------------------------------------------------------------------------------
sex @ 1869853
age class @ 702644
materials @ 544231
weight @ 383072
square @ 333484
total length @ 287081
stratigraphic position @ 286415
description @ 260740
hind foot with claw @ 259809
tail length @ 257973
reproductive data @ 237416
age @ 221849
verbatim collector @ 198110
ear from notch @ 197547
culture of origin @ 196360
provenience @ 148637
number of labels @ 113028
depth @ 110243
provenience north @ 103976
provenience east @ 92836
quadrant @ 92242
unformatted measurements @ 89757
maximum standard length @ 64538
minimum standard length @ 64538
archaeological feature @ 58124
verbatim host ID @ 50249
fat deposition @ 49126
molt condition @ 45498
location in host @ 34512
soft parts @ 30045
examined for parasites @ 24774
verbatim host sex @ 24171
value @ 21836
clutch size @ 21830
body condition @ 21298
stomach contents @ 20639
standard length @ 19901
ectoparasite examination @ 19864
snout-vent length @ 19117
parasites found @ 18628
endoparasite examination @ 18338
verbatim preservation date @ 18240
incubation stage @ 16923
skull ossification @ 16850
numeric age @ 16575
historical @ 16202
culture of use @ 14400
bursa @ 14339
endoparasites detected @ 11945
ectoparasites detected @ 11503
SNV results @ 8222
wing chord @ 5357
height @ 5039
forearm length @ 4834
framed @ 3741
object title @ 3740
dimensions @ 3374
credit line @ 3242
tragus length @ 3220
colors @ 3172
nest description @ 2760
verbatim host age @ 2528
image confirmed @ 2493
soft part color @ 2482
experimental @ 2372
inscriptions and marks @ 2340
tail condition @ 2174
crown-rump length @ 1858
curvilinear length @ 1753
axillary girth @ 1618
extension @ 1494
ear from crown @ 909
tarsus length @ 906
parts examined @ 770
trap identifier @ 667
gonad @ 608
culmen length @ 584
hind foot without claw @ 509
diploid number @ 469
abundance @ 440
breadth @ 371
tested for presence @ 334
egg content weight @ 314
bill width @ 269
right gonad length @ 216
head length @ 196
water temperature @ 183
air temperature @ 183
electrical conductivity @ 179
head width @ 169
left gonad length @ 150
wing span @ 140
radiometric date @ 133
trap type @ 125
bill depth @ 111
crop contents @ 97
hind limb length @ 83
clutch size of nest parasite @ 79
right gonad width @ 74
eggshell thickness @ 73
left gonad width @ 65
maximum total length @ 64
minimum total length @ 63
ovum @ 62
nest phenology @ 60
NAGPRA category @ 53
bill length @ 50
exhibit caption @ 45
caste @ 35
isotope value @ 30
carapace length @ 25
body width @ 25
neck width @ 19
width @ 17
tail base width @ 17
plastron length @ 15
straight carapace length @ 13
curved carapace length @ 5
year class @ 4
bursa length @ 2
brood patch @ 2

121 rows selected.
```

**Comment by campmlc** [comment]
Created as "tooth width", with "transverse" as part of definition.
