### ISSUE TITLE
No option to see uploads in process in "My Stuff"

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1625]
**Describe the bug**
After uploading a file to the media bulkloader I am told that I can check the status of my upload by visiting "My Stuff", but in the "My Stuff" tab there is no option for reviewing uploads, just managing my profile and saved searches.

If I leave the message page, how am I to get to the upload later?

**To Reproduce**
1. upload a media file
2. get message
3. leave page and go to "My Stuff" - there is no option to review my upload status

**Expected behavior**
I expect that if I have an upload that is processing, I should see an option to review it when I select the "My Stuff" dropdown from the main Arctos menu.

**Screenshots**
![capture](https://user-images.githubusercontent.com/5725767/43419123-5a0513da-93fd-11e8-85a6-7ec987e9a369.JPG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 61.0.1

**Additional context**

**Comment by dustymc** [comment]
Merge https://github.com/ArctosDB/arctos/issues/3298
