### ISSUE TITLE
"Arctos pending data notification" messages

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#1628]
> You are receiving this message because you have data in a bulkloader available from "data entry extras," or because you have manage_collection for a user with data in a bulkloader available from "data entry extras."
> 
> Data for specimens which have not yet been entered are available at EnterData/Bulkloader/BrowseAndEdit-->Extras or the individual bulkloaders.
> 
> NOTE: Records which have been orphaned by deleting from the specimen bulkloader or changing UUID in either the specimen bulkloader or the individual bulkloader will NOT be available at EnterData/Bulkloader/BrowseAndEdit-->Extras. These must be reconciled from the individual bulkloader.
> 
> Data for specimens which have been entered are available at EnterData/Bulkloader/ExtrasForLoadedSpecimens or the individual bulkloaders.

Many of us have been getting this message from Arctos over the past few days. It comes with a handy summary table. I've tried to find and fix data/records that are reflected by my former operator KOLSON36 by going into the Bulkloader extras options indicated in the text. I've been unable to locate this data. @KyndallH  and @amgunderson have also come up empty. We're not sure what we need to do with this information that is provided by the arctos message. Can anyone help us out?

**Comment by dustymc** [comment]
It looks like that record is orphaned - it was deleted from the bulkloader, the UUID was removed from the bulkloader, or the UUID was removed from the specimen record after it was loaded.

```
UAM@ARCTOS> select UUID from cf_temp_specevent where username='KOLSON36';

UUID
------------------------------------------------------------------------------------------------------------------------
473b84e1-a874-44d5-ae55-fa5791fad14e

1 row selected.

Elapsed: 00:00:00.06
UAM@ARCTOS> select count(*) from bulkloader where other_id_num_4='473b84e1-a874-44d5-ae55-fa5791fad14e';

  COUNT(*)
----------
	 0

1 row selected.

Elapsed: 00:00:01.27
UAM@ARCTOS> select count(*) from coll_obj_other_id_num  where display_value='473b84e1-a874-44d5-ae55-fa5791fad14e';

  COUNT(*)
----------
	 0

1 row selected.
```

CSV attached - there's not much there, but hopefully you can make some sense of it! Can I delete the record from cf_temp_specevent?

[temp_KOLSON36_specevt.csv.zip](https://github.com/ArctosDB/arctos/files/2247227/temp_KOLSON36_specevt.csv.zip)

You can also find that sort of thing by going to the specimen event bulkloader (should work for any table with "extras"), then Manage, Check for records entered by people in your collection(s), check the box(es), claim them, then treat them as if you entered them.

**Comment by AJLinn** [comment]
> Can I delete the record from cf_temp_specevent?

yes, please do!

> You can also find that sort of thing by going to the specimen event bulkloader (should work for any table with "extras"), then Manage, Check for records entered by people in your collection(s), check the box(es), claim them, then treat them as if you entered them.

Hmmm, I'm not quite sure I get this process. Maybe I need an in-person tutorial from someone at UAM who does this regularly? I got to that page and it says I have 16 records in the staging table... not sure what to do with those? When I click on "Check for records entered by people in your collection(s)" I only see this:
![ss_pendingdata](https://user-images.githubusercontent.com/17605945/43494978-fbc673aa-94e1-11e8-85e9-6e6b060a7ecf.jpeg)
Is that what I claim and then do something????

**Comment by dustymc** [comment]
http://handbook.arctosdb.org/how_to/How-to-load-Data-Entry-linked-Attributes.html should be similar. PLEASE expand on it!

That's the right place. Looks like you claimed that record:

```
UAM@ARCTOS> select username from cf_temp_specevent where uuid='473b84e1-a874-44d5-ae55-fa5791fad14e';

USERNAME
------------------------------------------------------------------------------------------------------------------------
ajlinn1910
```

so it (and anything else you've claimed, and anything you've entered via data entry extras, and anything you've uploaded via CSV) should be available under the "manage my xxx records" from the loader - http://arctos.database.museum/tools/BulkloadSpecimenEvent.cfm --> http://arctos.database.museum/tools/BulkloadSpecimenEvent.cfm?action=managemystuff. The "don't click here" link should be safe-ish up to a few hundred records, or download CSV should work with about any number of them.

**Comment by acdoll** [comment]
I went and took care of everything of ours in the "Extras for loaded specimens" list, but some of them are still coming up in these notifications (e.g. from ELAINEPERRY and TRUCKEY). The ones that had been attributed to me (ACDOLL) are no longer showing up. So it seems that the ones I've claimed and then loaded are still lingering for some reason. Have I missed a step?

**Comment by dustymc** [comment]
```

UAM@ARCTOS> select count(*) from cf_temp_attributes where upper(username) in ('ELAINEPERRY','TRUCKEY');

  COUNT(*)
----------
	15

1 row selected.

Elapsed: 00:00:00.02
UAM@ARCTOS> select OTHER_ID_NUMBER from cf_temp_attributes where upper(username)in ('ELAINEPERRY','TRUCKEY');

OTHER_ID_NUMBER
------------------------------------------------------------------------------------------------------------------------
09f1fb2f-39f9-4e68-a4d2-ee3c733c0331
a3b98cfc-32a4-4fbd-a42c-edc7764db9fd
7d102e01-97cc-4d46-8c4d-e0c5e0887d9f
0eee2738-eb5e-4f43-aadf-6b60c37fbf96
e3e67462-1ba4-41bd-80ba-ae22c01b4e3b
747af98a-0946-4b7a-abbd-82df2523394d
747af98a-0946-4b7a-abbd-82df2523394d
08e7468a-5d23-4d28-a236-e3ccbc2c89ac
52c3e16b-7613-4b84-88b3-1251603bbd9f
52c3e16b-7613-4b84-88b3-1251603bbd9f
2ea944dd-b38c-45d5-8439-dbf14daf6b77
2ea944dd-b38c-45d5-8439-dbf14daf6b77
a0d6260d-3e15-4b32-b50b-cc98e045e325
08e7468a-5d23-4d28-a236-e3ccbc2c89ac
2ea944dd-b38c-45d5-8439-dbf14daf6b77

15 rows selected.

Elapsed: 00:00:00.02
UAM@ARCTOS> select count(*) from bulkloader where other_id_num_4 in (select OTHER_ID_NUMBER from cf_temp_attributes where upper(username)in ('ELAINEPERRY','TRUCKEY'));

  COUNT(*)
----------
	 0

1 row selected.

Elapsed: 00:00:01.53
UAM@ARCTOS>  select count(*) from coll_obj_other_id_num  where display_value in (select OTHER_ID_NUMBER from cf_temp_attributes where upper(username)in ('ELAINEPERRY','TRUCKEY'));

  COUNT(*)
----------
	 0

1 row selected.

Elapsed: 00:00:00.02
UAM@ARCTOS> create table temp_cf_temp_attributes_ept as select * from cf_temp_attributes where upper(username)in ('ELAINEPERRY','TRUCKEY');

Table created.

```

Those have been orphaned as above. CSV attached; let me know if you want me to clean anything up.

[temp_cf_temp_attributes_ept.csv.zip](https://github.com/ArctosDB/arctos/files/2250107/temp_cf_temp_attributes_ept.csv.zip)

**Comment by acdoll** [comment]
What do you mean they are orphaned? Do you mean that the UUID for these has been removed from the specimen record they belong to? I claimed them and loaded them (or so I thought). What would I have done that orphans these records? 

I also looked to see what I had in "Check for records entered by people in your collection(s)" and saw the same 2 records for DLM (that's you, right Dusty?). Since there is no way to know what those are I claimed them - which I now see that I should _not_ have done as those were UTEP:Herp records. I assume that you are linked to every collections so everyone will always see anything of yours in this utility, right? Can I transfer those back to you? Previously there had been some of Carla's records appearing there as well. Can we limit this to records only for collection which we permissions to?

**Comment by dustymc** [comment]
>orphaned

it was deleted from the bulkloader, the UUID was removed from the bulkloader, or the UUID was removed from the specimen record after it was loaded.

>same 2 records for DLM...linked to every collections so everyone will always see anything of yours in this utility,

Yea, I'm everywhere - sorry! I'll try to do a better job of cleaning up my messes in the future.

>Can we limit this to records only for collection which we permissions to?

It is to the extent possible. There are no(t necessarily) collection identifiers associated with these data - the UUID is the only link (sometimes). Permissions are "folks who have data_entry in collections for which I, the current user, has manage_collection." 

> I claimed them - which I now see that I should not have done as those were UTEP:Herp records

I think there's some warning on the page, but yea - sometimes the only way to see what you're claiming is to claim it. I'm hoping that'll become less problematic as the backlog is dealt with. If it's not, I'll figure something out. Just please let the real owner know if it happens for now - I'm always happy to facilitate. In this case you can just delete them - I was just testing something or another with whatever data I had handy.

**Comment by Jegelewicz** [comment]
@acdoll is it possible for you to tell me what the UTEP:Herp stuff is? Send me a .csv?

**Comment by acdoll** [comment]
Let me know if this works:
[UTEPHerps_BulkloadSpecimenEventData.zip](https://github.com/ArctosDB/arctos/files/2250885/UTEPHerps_BulkloadSpecimenEventData.zip)

**Comment by Jegelewicz** [comment]
Got it! Now that Andy "owns" it can he load it or is it not loadable because it has been orphaned or because he doesn't have access to UTEP:Herp?

I guess I'm asking - should I just re-load (if I can figure out which specimens it belongs with...)?

**Comment by dustymc** [comment]
@Jegelewicz I think I was using those data for debugging - you probably sent them to me, I might have changed something....

They have a GUID - being orphaned should not be a problem for them.

UTEP:Herp records don't exist for users who don't have UTEP_HERP access - trying to load against things that don't exist (from your perspective) will fail.

**Comment by acdoll** [comment]
So I just attempted to load 152 attribute records entered by KShrawder - all but eight went through: 
![image](https://user-images.githubusercontent.com/12507297/43547455-8030e4d4-9598-11e8-9ac6-857450772e32.png)
I don't see why not. When I click on 'validate here' I immediately get this error:
![image](https://user-images.githubusercontent.com/12507297/43547638-09ed27b4-9599-11e8-9a1f-6ae5557ae2e7.png)
Why would the collection code be undefined?

**Comment by Jegelewicz** [comment]
After checking on them, I don't think those are needed. Hopefully they are now gone from any staging tables? If not, they can be deleted.

Thanks!

**Comment by dustymc** [comment]
@acdoll I think that's just a bad error message from the validator - those records seem to be orphaned.  https://github.com/ArctosDB/arctos/issues/1629

```
UAM@ARCTOS> select count(*) from cf_temp_attributes where upper(username) in ('ACDOLL');

  COUNT(*)
----------
	 8

1 row selected.

Elapsed: 00:00:00.01
UAM@ARCTOS> select OTHER_ID_NUMBER from cf_temp_attributes where upper(username)in ('ACDOLL');

OTHER_ID_NUMBER
------------------------------------------------------------------------------------------------------------------------
f4c9977e-5cea-48f5-99ca-c9e4f34b1263
f4c9977e-5cea-48f5-99ca-c9e4f34b1263
f4c9977e-5cea-48f5-99ca-c9e4f34b1263
f4c9977e-5cea-48f5-99ca-c9e4f34b1263
f4c9977e-5cea-48f5-99ca-c9e4f34b1263
f4c9977e-5cea-48f5-99ca-c9e4f34b1263
4bf908eb-59b6-46eb-ab3d-773b8c19d1a1
f4c9977e-5cea-48f5-99ca-c9e4f34b1263

8 rows selected.

Elapsed: 00:00:00.02
UAM@ARCTOS> select count(*) from bulkloader where other_id_num_4 in (select OTHER_ID_NUMBER from cf_temp_attributes where upper(username)in ('ACDOLL'));

  COUNT(*)
----------
	 0

1 row selected.

Elapsed: 00:00:00.83
UAM@ARCTOS>  select count(*) from coll_obj_other_id_num  where display_value in (select OTHER_ID_NUMBER from cf_temp_attributes where upper(username)in ('ACDOLL'));

  COUNT(*)
----------
	 0

1 row selected.

```

**Comment by amgunderson** [comment]
The UUID means nothing to me because I don't create it, can't see, can't search for it. If I delete something from the bulkloader I want it all to go away, I don't want parts lingering around to email me asking for help. I would rather reenter an entire specimen record than try to track down pieces of data and figure out what happened to their parents. 

I was hoping I could ignore this new thing but these emails are annoying me and I can't make them stop because I can't find anything to check or approve or delete. What page shows this data? I can't see it anywhere on Arctos.

**Comment by dustymc** [comment]
>UUID

Before specimens are created, the UUID is just to glue the parts together.

After, it's just another OtherID.

>What page shows this data

From the notification:

```
 Data for specimens which have not yet been entered are available at EnterData/Bulkloader/BrowseAndEdit-->Extras or the individual bulkloaders.

NOTE: Records which have been orphaned by deleting from the specimen bulkloader or changing UUID in either the specimen bulkloader or the individual bulkloader will NOT be available at EnterData/Bulkloader/BrowseAndEdit-->Extras. These must be reconciled from the individual bulkloader.

Data for specimens which have been entered are available at EnterData/Bulkloader/ExtrasForLoadedSpecimens or the individual bulkloaders. 
```

For the one you're looking at, which has been orphaned, ....

```
NOTE: Records which have been orphaned by deleting from the specimen bulkloader or changing UUID in either the specimen bulkloader or the individual bulkloader will NOT be available at EnterData/Bulkloader/BrowseAndEdit-->Extras. These must be reconciled from the individual bulkloader.
```

is the relevant bit.

<img width="268" alt="screen shot 2018-08-10 at 1 14 29 pm" src="https://user-images.githubusercontent.com/5720791/43979392-7ed5be58-9c9f-11e8-99d1-5457124a52f1.png">

<img width="167" alt="screen shot 2018-08-10 at 1 14 36 pm" src="https://user-images.githubusercontent.com/5720791/43979396-82d9535c-9c9f-11e8-96cf-0fb2a8898ce7.png">

<img width="292" alt="screen shot 2018-08-10 at 1 14 45 pm" src="https://user-images.githubusercontent.com/5720791/43979397-84baa270-9c9f-11e8-9d65-36a4ce85ac9e.png">

<img width="162" alt="screen shot 2018-08-10 at 1 14 53 pm" src="https://user-images.githubusercontent.com/5720791/43979404-86be2c7c-9c9f-11e8-9968-62149e7fee28.png">

Want me to delete it?

**Comment by dustymc** [comment]
>Yes delete it. 

done.

>which individual bulkloader 

The "table" column of the table in the notification.

>just delete it

I can't guarantee that - it's a loose join (eg, to things that might live in Excel on your hard drive) - but I can probably get it most of the time. Sound reasonable to everyone else?

>bulkload thousands of things all the time

I think all of the component-loaders delete on load now, so they should not show up in this report.

**Comment by acdoll** [comment]
Yes, @dustymc that sounds reasonable. 
There are apparently records in the notification email that are associated with DMNS collections, but I can't seem to access them. Attribute records entered by ELAINEPERRY and TRUCKEY are ours but I can't get to them to delete. Actually, I thought I had claimed the ones from ELAINEPERRY when these emails first started and deleted them. I don't know why they are still there. When I 'Check for records entered by people in your collection(s)' there is nothing there, so I can't claim these in order to delete them. Would you please delete them for me?

**Comment by dustymc** [comment]
```
UAM@ARCTOS> create table temp_dmns_attrs as select * from cf_temp_attributes where upper(username) in ('ELAINEPERRY','TRUCKEY');

Table created.

Elapsed: 00:00:00.13
UAM@ARCTOS> delete from cf_temp_attributes where upper(username) in ('ELAINEPERRY','TRUCKEY');

15 rows deleted.

Elapsed: 00:00:00.03
UAM@ARCTOS> commit;
```
[temp_dmns_attrs.csv.zip](https://github.com/ArctosDB/arctos/files/2307301/temp_dmns_attrs.csv.zip)

I think that's the last of the orphans.

```
select tbl,uuid from (
select 
'cf_temp_attributes' tbl,
OTHER_ID_NUMBER uuid from
cf_temp_attributes where OTHER_ID_TYPE='UUID'
union
select
'cf_temp_oids' tbl,
EXISTING_OTHER_ID_NUMBER uuid
from
cf_temp_oids where EXISTING_OTHER_ID_TYPE='UUID'
union
select
'cf_temp_parts' tbl,
OTHER_ID_NUMBER uuid
from
cf_temp_parts where OTHER_ID_TYPE='UUID'
) where
uuid not in (select other_id_num_4 from bulkloader where other_id_num_type_4 ='UUID') and
uuid not in (select display_value from COLL_OBJ_OTHER_ID_NUM where other_id_type='UUID')
;

no rows selected

```

**Comment by acdoll** [comment]
Great. Thanks!

**Comment by acdoll** [comment]
I still am doing something wrong with this. My volunteer, KShrawder, entered another 27 attribute records during the manual data entry process. I have checked and loaded the specimen records (ex: http://arctos.database.museum/guid/DMNS:Mamm:19101). I then claimed the attribute records and then attempted to validate. The status for these records is now "specimen not found,invalid attribute". The UUIDs for these attribute records can be found in the respective specimen record. The attributes all seem valid (ex. 'ectoparasite dectected'). What am I missing?

**Comment by dustymc** [comment]
http://handbook.arctosdb.org/how_to/How-to-load-Data-Entry-linked-Attributes.html

Did you "get guid_prefix from UUID"?

**Comment by acdoll** [comment]
Nope. I knew I was missing something simple. Thanks. I will try to make some time to add text to the documentation page.

**Comment by AJLinn** [comment]
New question related to an email message received 2021-04-13 with the same title.

I have apparently 13 offenders in the "cf_temp_oids" table. When I went to the Bulkload Identifiers/Relationships Tool (thanks to @ebraker for the tip) I see a table:
<img width="648" alt="Screen Shot 2021-04-14 at 9 55 52 AM" src="https://user-images.githubusercontent.com/17605945/114756814-9aa88780-9d07-11eb-9fbc-111c05664ab1.png">

When I select "Review" I see this table:
<img width="1532" alt="Screen Shot 2021-04-14 at 9 57 11 AM" src="https://user-images.githubusercontent.com/17605945/114756986-ca578f80-9d07-11eb-9b82-0fb22606d8df.png">

I don't know what to do next here. When I look at the records in question, the reciprocal relationship has been made in both records. Am I supposed to do something here to "load" them? What does that do that's different from entering the relationship in each catalog record?
I also don't know why the same three records (1-1939-0216) are repeated four times in the table (presumably that's what constitutes "local duplicate").

I have not been taught what to do in this process and would appreciate some guidance. And if there's a tutorial to watch to avoid being placed on this list again that would be great.

**Comment by AJLinn** [comment]
@KyndallH or @amgunderson are either of you familiar with the temp_ods issue I listed back in April with feedback? I'd love to get off the offender list and stop getting the "pending data" emails on the regular...

**Comment by Jegelewicz** [comment]
@AJLinn if these already exist in the catalog records, you can delete them from the loader by selecting delete.

**Comment by AJLinn** [comment]
Thanks to @KyndallH for helping me get that content deleted.

**Comment by dustymc** [comment]
Done?
