### ISSUE TITLE
Useability of TEST

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1631]
Trying to play around with object tracking in test and I don't have access to edit labels. Is there a way to make test more friendly to testing? I want to play around here to make sure I don't screw up stuff in real Arctos!

I was changing a label and adding a remark:
![image](https://user-images.githubusercontent.com/5725767/43598967-4eddee1c-9643-11e8-83f5-136ceb40cfe3.png)

I selected "update" and got this:
![image](https://user-images.githubusercontent.com/5725767/43598999-674add02-9643-11e8-9587-89920b4db3f2.png)

**Comment by campmlc** [comment]
Are you logged in as yourself or ad i_am_tester? I am tester probably does
not have object tracking access to DGR?

**Comment by Jegelewicz** [comment]
logged in as i_am_tester

**Comment by Jegelewicz** [comment]
I guess I wonder why in test we wouldn't just have access to any option. I could see limiting to a certain set of records (although I might want to play around with stuff that someone else currently uses), but if I am exploring possibilities for doing new things in Arctos, it doesn't make sense to keep thwarting me with "you don't have access to that".

**Comment by dustymc** [comment]
It's test, I don't really care who has what in there. (I think i_am_tester had everything everywhere at one point but someone asked to remove some of it.) I could set up more tester-users if it's useful.

>make test more friendly to testing?

Despite the name, test is really a dev box. We occasionally break everything, and sometimes it stays that way for days or weeks. We probably need to spin up another instance if we're going to have a user-friendly sandbox. I have no idea how realistic that is, I sorta doubt the benefit is worth the work given our resources, but it would be nice...

**Comment by Jegelewicz** [comment]
> I could set up more tester-users if it's useful.


Can you give my test log in an all-access pass (or at least as all-access as makes sense)? teresa_the_tester

**Comment by dustymc** [comment]
Sure - add an email to your profile (and invite yourself as i_am_tester if you want).

(I can't use scripts from this stage - I need your password in plain-text and it's stored encrypted).

**Comment by dustymc** [comment]
teresa_the_tester has lotsa rights now. I'm curious how one agent having two operator accounts will work - please let me know if something melts!

**Comment by Jegelewicz** [comment]
Yeah - I thought about that one too - I almost deleted jegelewicz, but then figured it might be an interesting thing to leave.

Perhaps this would allow MSB to let Art only have access to some stuff while UTEP lets him have other access?

**Comment by dustymc** [comment]
Interesting - reopening.

Can one Agent have two logins without breaking anything?

Ex:

* oneUser: admin on someCollection (=main login)
* otherUser: media on someCollection AND media on otherCollection (allows cross-collection TAGs/media relationships, without allowing dangerous/internal stuff)

Needs testing. 

Ref: email "Re: Art Harris" regarding TAGging MSB specimens from UTEP images

**Comment by Jegelewicz** [comment]
Well, it looks like Arctos just removed my jegelewicz log in, so I guess you can't have two login IDs...

Let me know if I can help test the idea though...

**Comment by Jegelewicz** [comment]
Didn't know what password my jegelewic log in was using, so tried to get a reset. I requested it as so:
![image](https://user-images.githubusercontent.com/5725767/43743114-c52c3f32-9991-11e8-8b6a-2f8196557c5d.png)
and I get this:
![image](https://user-images.githubusercontent.com/5725767/43743125-d1b57110-9991-11e8-956f-27935c144d18.png)
although my Agent has this:
![image](https://user-images.githubusercontent.com/5725767/43743180-0ad4845e-9992-11e8-9736-e12611815471.png)
So for now, I can't break much!!!

**Comment by dustymc** [comment]
Agent=internal
user account=this

<img width="530" alt="screen shot 2018-08-06 at 3 05 18 pm" src="https://user-images.githubusercontent.com/5720791/43743330-2c9f1d54-998a-11e8-8714-b771c407bd32.png">

**Comment by Jegelewicz** [comment]
Mariel reminded me that it is probably the email associated with the jegelewicz profile that I need - unfortunately, that is my old utep email which I no longer have access to and therefore I will never get the reset email. Dusty can you change my email on that profile?

**Comment by dustymc** [comment]
> change my email 

done

**Comment by Jegelewicz** [comment]
Related to Oracle, closing
