### ISSUE TITLE
Add all gastrointestinal tract to Bird collections

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1632]
**Table**
Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm

**Value**
Proposed new values for **Bird** (already in use for Mamm, please add to Bird) please add all in **bold**

Part Name | Collection |  Is Tissue | Documentation
-- | -- | -- | --
gastrointestinal tract | **Bird**, Mamm | no |  **The large, muscular tube that extends from the mouth to the anus. Partials should be noted in remarks**
gastrointestinal tract (70% ethanol) | **Bird**, Mamm | no |  **The large, muscular tube that extends from the mouth to the anus. Partials should be noted in remarks. Stored in 70% ethanol**
gastrointestinal tract (ethanol) | **Bird**, Mamm | no |  **The large, muscular tube that extends from the mouth to the anus. Partials should be noted in remarks. Stored in ethanol**
gastrointestinal tract (ethanol-fixed) | **Bird**, Mamm | yes |  **The large, muscular tube that extends from the mouth to the anus. Partials should be noted in remarks. fixeded in ethanol**
gastrointestinal tract (formalin) | **Bird**, Mamm | no |  **The large, muscular tube that extends from the mouth to the anus. Partials should be noted in remarks. Stored in formalin**
gastrointestinal tract (frozen) | **Bird**, Mamm | yes | **The large, muscular tube that extends from the mouth to the anus. Partials should be noted in remarks. Frozen**

**Context**
Bird intestines exist in MSB tissue collection.

**Comment by campmlc** [comment]
Done 8-6-2018
