### ISSUE TITLE
Copyright Status Attribute

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1634]
From #1610 

**Table**
CTATTRIBUTE_TYPE

**Value**
copyright status

**Definition**
describes the rights of the copyright holder listed for the object

**Collection type**
If the code table includes a "Collection" column. Ex: ART, EH

**Attribute data type**
controlled vocabulary

**Attribute value**
**In Copyright**: Item is protected by copyright and/or related rights.
**In Copyright - Rights-Holder(s) Unlocatable or Unidentifiable**: Item is protected by copyright and/or related rights. However, for this Item, either (a) no rights-holder(s) have been identified or (b) one or more rights-holder(s) have been identified but none have been located. See also: http://rightsstatements.org/vocab/InC-RUU/1.0/
**Copyright Undetermined**: The copyright and related rights status of this Item has been reviewed by the organization that has made the Item available, but the organization was unable to make a conclusive determination as to the copyright status of the Item. See also: http://rightsstatements.org/vocab/UND/1.0/
**Copyright Not Evaluated**: The copyright and related rights status of this Item has not been evaluated. See also: http://rightsstatements.org/vocab/CNE/1.0/
**Public Domain**: Item is in the Public Domain.
**License Agreement**: Item is in copyright and a license agreement is secured with copyright holder.

We can record the copyright statement specific to the object in the remarks.
**Attribute units**
None

**Context**
Does this work? Does it look okay @AJLinn and @marecaguthrie ? Would anyone else be using this attribute that would find some other value useful?

**Comment by krgomez** [comment]
Are we waiting for more feedback from others before creating this attribute? Also, the copyright holder agent is still not displaying in an agent box when added to a record. In addition, does the media license that we requested also still need more discussion before it can be created?

**Comment by AJLinn** [comment]
> Are we waiting for more feedback from others before creating this attribute?

If so, I'm good with it.

**Comment by campmlc** [comment]
I created the attribute, but I can't or don't know how to create the code table of controlled vocabulary. I didn't find anything in the handbook on this.
@dustymc ?

**Comment by dustymc** [comment]
Table created

**Comment by AJLinn** [comment]
Can you please add this attribute to UAM:EH also?

**Comment by dustymc** [comment]
It should already be available
<img width="339" alt="screen shot 2018-08-09 at 8 08 00 am" src="https://user-images.githubusercontent.com/5720791/43907906-6a749e2e-9bab-11e8-9d84-1ce80be2aa9c.png">

**Comment by AJLinn** [comment]
> It should already be available

You're right! It's there. thanks
