### ISSUE TITLE
Problem Adding or Removing Data Fields for Public User

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1638]
When not logged in, a user who attempts to add or remove data fields from the specimen results page gets the " You must enter some search criteria!" error when clicking "Save and Refresh".

Are public users allowed this functionality? If not, we should give them a different message a la "please log in first" and not allow them to check the boxes in the add or remove data fields tab.

**Comment by campmlc** [comment]
Update - 
I got the same error when logged in, when trying to change attribute displayed. Interestingly, the data field I had added previously did show up, but I had to redo the search to see it.

**Comment by dustymc** [comment]
I can't replicate - details, please.

**Comment by campmlc** [comment]
public search for part attribute = carapace length, value = %
Search Results, Customize Form, Go to Add Remove Data Fields, select attribute = carapace length
Save and Refresh
Get "You must enter some search criteria!" erro

The dropdown does say log in for access, but it allows me to choose to add a new data field. If we don't want to allow this for non-logged in users, we should hide the dropdown or give a "Please login for access to Customize Results" as the big red error instead of the above.

So, my next step after the error is to log in. When I do so, I still get the big red error above, and have to go back and redo my search. It would be nice it it just asked me to "Please re-enter search criteria" or even better, save my search and allow me to continue where I left off.

I go back to redo the search, now logged in (this process is going to discourage a lot of public users, and operators too if they do as I did and log in to their operator account and then realize they have to repeat the entire process with their public user account.)

I go through the exact same process logged into my public account, and get the same error. 

I can't do any of this for my operator account, because I don't have access to any collections that have carapace length ( although I should have access to MSB Herp). When I do this search logged in as operator, I get zero records.

**Comment by dustymc** [comment]
Thanks - it's a "bug" (sorta) with the wildcard-nothing. It works with the suggested _ as value.

http://handbook.arctosdb.org/documentation/attributes.html#searching-with-attributes

**Comment by campmlc** [comment]
In this case, I want to find all records with that attribute, but I don't
know in advance what the values are. It is a numeric attribute. I'm sure
this would be the case for any numeric attribute. Is there a way we can
search for "all" without using the wildcard? I know % should work if it
weren't a bug, but the general public would not know what our wild card is.

Also, this brings up a previous issue of the attribute search field in
Specimen Search. When I select attribute = "carapace length", the blank
space next to the attribute search, which should be where you type in
whatever value you are looking for, also says "carapace length". This is
very confusing. Can we have this space be blank, or have it give
instructions for what to type?

this is what I see:

**Comment by dustymc** [comment]
http://handbook.arctosdb.org/documentation/attributes.html#searching-with-attributes

>All attributes (and most other variables) will accept underbar (_) to mean “require the field; match any value.” For example, “age_class=_” will return specimens for which the attribute “age class” exists.

**Comment by campmlc** [comment]
So, since I didn't know this, and have been working in Arctos for many
years, I would assume that it is also probably not well known by the
general public. Any way we can eliminate the guess work and just tell
people what they need to know? e.g. "To search all values, type "any value"
".

**Comment by dustymc** [comment]
It's in the documentation which is linked from the search term. I'm very open for ideas regarding how we can make it more obvious. (And I notice GH has mucked up the formatting in the copy-paste above.)

**Comment by dustymc** [comment]
isn't relevant in current form, closing
