### ISSUE TITLE
Automated edec generation form from Harvard

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1646]
Code from Paul Morris at Harvard:

(3) eDec generation

Here's Java code that forms a library that can be added to ColdFusion and is used by MCZbase to create eDecs as reports off of a loan, and a java desktop application that alows collection management staff to edit the generated eDec file.

https://github.com/MCZbase/eDecViewer

Invocation from ColdFusion is described in the class comment on: 
https://github.com/MCZbase/eDecViewer/blob/master/src/edu/harvard/mcz/edec/mczbase/EDecBuilder.java

**Comment by dustymc** [comment]
I don't know what this is or why we need it; tentatively tabling.
