### ISSUE TITLE
New Other ID type

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1648]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Table**
CTCOLL_OTHER_ID_TYPE

**Value**
ASK

**Definition**
"Angelo State University Karytoype Number," a frozen tissue collection number for the Angelo State Natural History Collections.

**Collection type**
Mamm, Herb

**Attribute data type**
numeric

**Attribute value**
None

**Attribute units**
None

**Part tissue flag**
N/A

**Other ID BaseURL**
None

**Context**
Needed for collection to track tissues.

**Priority**
I would like to have this resolved by date: 2018-08-15

From documentation wiki issue

> I am part of a new collection coming into Arctos, the Angelo State Natural History Collections (GUID Prefix: ASNHC:Mamm and Herb right now). I am requesting an addition of an attribute to the CTCOLL_OTHER_ID_TYPE code table. Our tissue numbers are ASK, which is defined as "Angelo State Karytoype Number," a frozen tissue collection number for the Angelo State Natural History Collections.
> 
> Thanks,
> Dianna
>

**Comment by campmlc** [comment]
Done.
