### ISSUE TITLE
New Container Type Needed

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#1649]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Table**
http://arctos.database.museum/info/ctDocumentation.cfm?table=CTCONTAINER_TYPE

**Value**
Shelving Unit

**Definition**
Open shelving consisting of multiple shelves. May be static or mobile.

**Context**
There are no current values in the code table that reflect this type of storage furniture. "Shelf" would be the unit within each Shelving Unit that further resolves an object's vertical position.

**Priority**
I would like to have this resolved by date: as soon as possible (8/17 at latest). Needed for SPNHC presentation.

**Comment by dustymc** [comment]
I know that's not the first shelf in Arctos, but I'm not sure how they've been entered. Is this somehow functionally distinct from "range"?

I'm always hesitant to have two values which are used interchangeably, but this is also an internal thing - nobody's going to fail to find specimens because of this vocabulary - so whatever.

http://arctos.database.museum/info/ctDocumentation.cfm?table=CTCONTAINER_TYPE

@campmlc @amgunderson @DerekSikes @KyndallH  help?

**Comment by DerekSikes** [comment]
open shelving is a single unit that could be in a range. Seems good to add this.

**Comment by DerekSikes** [comment]
a shelving unit holds multiple shelves & it would be unwise for the term 'shelf' to mean two different things (in which case one could scan a shelf into a shelf!)

**Comment by AJLinn** [comment]
We use the following hierarchy, all of which are found in the CTCONTAINER_TYPE
Range (aisle of range cases)
   Column (vertical grouping of shelving in compact mobile storage unit)
      Shelf (shelf)

**Comment by AJLinn** [comment]
And this is the hierarchy already in use in thousands of barcoded locations in UAM:Arc and UAM:EH

**Comment by dustymc** [comment]
>scan a shelf into a shelf

That is currently disallowed - people were scanning freezer boxes into freezer boxes, so a container cannot be a child of a container of the same type. There's a "big box" to deal with the fact that boxes really are/should be scanned into boxes, we might want to do something similar here if there are/will be "sub-shelves."

**Comment by dustymc** [comment]
done
