### ISSUE TITLE
something wrong with media?

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#1650]
Are we having a problem with media right now? I just added a couple of jpegs to a record and the thumbnails are showing up with the big red x. I also had to just turn off the media column in my search results because it wouldn't load the search results. And I can't open any existing media files.

**Comment by AJLinn** [comment]
And it's working again. Hmmm, temporary glitch that fixed itself?

**Comment by dustymc** [comment]
Yes, Media (and a bunch of other stuff) caches.
