### ISSUE TITLE
Add media license to media detail view

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1652]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
Add license to detail display of media

**Describe the solution you'd like**
When viewing media, the license should be displayed along with other media details.

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/5725767/44102811-d2d3e6dc-9fa7-11e8-9014-ba3ad1227366.png)

**Priority**
I would like to have this resolved by date: 2018-09-30

**Comment by dustymc** [comment]
That's the MPD view. Click this...

<img width="167" alt="screen shot 2018-08-14 at 9 51 34 am" src="https://user-images.githubusercontent.com/5720791/44105803-acee3594-9fa7-11e8-9106-b8df9bdb681c.png">

for the media detail view.

I can add license to the MPD, but it looks like clutter to me - you can't do anything from that page that might require a license, and the page from which you CAN do things that might require a license has the license info.

More info, please.

**Comment by Jegelewicz** [comment]
It just meant that in order for me to find the pages with different licenses, I had to click that 31 times.

In the spirit of no clutter - remove the MD5 checksum? License would be much more useful I think....

**Comment by campmlc** [comment]
Agree. No need to display content that has no meaning to the user, and is
visually highly intimidating. Anything we can do to normalize clicking and
make it easier and obvious for users to find info is good.

**Comment by dustymc** [comment]
> find the pages with different licenses

That should not be possible. https://github.com/ArctosDB/arctos/issues/1653

Details (in #1653) re: how this happened greatly appreciated.

>remove the MD5 checksum?

https://github.com/ArctosDB/arctos/issues/1654

**Comment by dustymc** [comment]
>visually highly intimidating.

I suppose that's a matter of perspective. It's pretty comforting to me (and I think anyone who's ever transferred very many binaries) - it's an indicator that there's some quality monitoring. So maybe make it tiny and gray or something instead of removing it??

**Comment by Jegelewicz** [comment]
> it's an indicator that there's some quality monitoring. So maybe make it tiny and gray or something instead of removing it??

I'm Ok with that - also can it be at the bottom?

**Comment by dustymc** [comment]
I think we're done here?
