### ISSUE TITLE
control multi-page document data

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1653]
**Is your feature request related to a problem? Please describe.**
It's possible to create MPDs with variable data, which kills the normalization.

It's probably also possible to eg, create nonnumeric page values and etc.

**Describe the solution you'd like**
Force consistency. Don't kill INSERT performance in the process.

**Comment by Jegelewicz** [comment]
I loaded manually and on a few of them I failed to add the license. There was no warning that a different license might cause issues.

**Comment by dustymc** [comment]
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctmedia_relationship#created_by_agent

>Indicates the person who created the media (took a photograph, wrote field notes, etc.). The related term must be an exact match for a unique Agent Name.

Need to enforce "the" and clean up things that don't follow docs

**Comment by dustymc** [comment]
ensure label 'page' can be cast to int (current requirement is numeric)

**Comment by dustymc** [comment]
I don't think I'll be able to control this, but there will be a report. The first problem is that may (most??) MPDs aren't and shouldn't be MPDs.

**Comment by dustymc** [comment]
In next release:

<img width="412" alt="Screen Shot 2021-08-16 at 2 13 19 PM" src="https://user-images.githubusercontent.com/5720791/129630232-b84dd51e-b162-4e0a-a9a3-4da70bcada1f.png">
