### ISSUE TITLE
New Taxon Term

### ISSUE THREAD

**Issue by anna-chinn** [ArctosDB/arctos#1655]
Issue Documentation is http://handbook.arctosdb.org/documentation/taxonomy.html

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=CTTAXON_TERM

**Value**
Term: epifamily
Classification: yes

**Definition**
taxonomic rank below superfamily and above family

**Context**
Epifamily is a classification rank that doesn't yet exist in Arctos.
(https://en.wikipedia.org/wiki/Taxonomic_rank)

**Priority**
I would like to have this resolved by date: 2018-09-14 (low priority)

**Comment by dustymc** [comment]
done
