### ISSUE TITLE
Add sex and unformatted measurements attributes to herbarium collections

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#1656]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Table**
ATTRIBUTE_TYPE

**Value**
add sex and unformatted measurements to herbarium collections

**Collection type**
Herb

**Attribute data type**
categorical and free text

**Context**

We have sexed plants and there are some measurements that are rarely taken that we would like to add in. Also, almost all the other collections have these attributes?

**Priority**
I would like to have this resolved by date: _9/15/2018______

**Comment by dustymc** [comment]
For sex, I need to know what values from http://arctos.database.museum/info/ctDocumentation.cfm?table=CTSEX_CDE you want (and definitions if you need new terms).

**Comment by mvzhuang** [comment]
I think this will cover it. It would be great if any other herbaria could chime in:
female
female ?
male
male ?
hermaphrodite
sexes mixed
recorded as unknown
not recorded

**Comment by dustymc** [comment]
Done except sexes mixed, which no longer exists
