### ISSUE TITLE
Parts>>Containers do not understand results

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1657]
I have been using the bulkload parts tool for months now to get existing parts added to existing cryovial barcodes. Today, everything has changed without any warning!

It appears that now, I should use the Parts>>Containers tool, which seems pretty straightforward, but is not working for me.

I downloaded a template, filled in the information and uploaded the file and get this:

> Fix this and reload - nothing's been saved. 

with all lines displaying "item not found"

However, for at least one of the parts, I can go directly to the record and see the part there.

http://arctos.database.museum/guid/MSB:Mamm:242563
NK 45485, hair (frozen)

Is the error because there is a subsample on loan and Arctos can't know which part I'm talking about? If so, can we get error messages like we used to in Bulkload Parts - duplicate parts, etc?

Here is my file just in case:
[BulkPartContainer_DGR12882.zip](https://github.com/ArctosDB/arctos/files/2291461/BulkPartContainer_DGR12882.zip)

**Comment by dustymc** [comment]
Nothing related to any of that has changed recently.

http://arctos.database.museum/guid/MSB:Mamm:242563 has two "hair (frozen)" parts (neither of which is a subsample) - yes, the lack of an unambiguous part reference is the problem.

And your first container claims to already hold a hair sample from http://arctos.database.museum/guid/MSB:Mamm:242319 - I think the loader will happily shove more in there, which may or may not be what you want to do.

Yes, the errors can be made more descriptive.

**Comment by Jegelewicz** [comment]
Well, SMH - I have no idea why the part bulkload wasn't working for me an hour ago, but it just did what it always does, so I guess I'll chalk that one up to rogue electrons...
