### ISSUE TITLE
upload thumbnail via the edit media page

### ISSUE THREAD

**Issue by amgunderson** [ArctosDB/arctos#1659]
A thumbnail image is not automatically created when adding video as media to a specimen record. And it seems I can't add a thumbnail image after any media has been created from the edit media page.

This video needs a thumbnail image, https://arctos.database.museum/media/10585211, and this image needs a new thumbnail image less than 12kb, https://arctos.database.museum/media/10570045. 

I can't add a thumbnail to the video while creating it and I can't add or change the thumbnail to either via the edit media page.

Can there be an "upload thumbnail" button next the Preview URI field on the edit media page?

**Comment by dustymc** [comment]
done
