### ISSUE TITLE
Formation (geology attribute) query

### ISSUE THREAD

**Issue by KatherineLAnderson** [ArctosDB/arctos#1660]
When the format was standardized and subsequently changed for formation names (ie: "Port Refugio (formation)" was changed to "Port Refugio formation (formation)", the format was not updated in the specimen records so Arctos can't find them.

Example: http://arctos.database.museum/guid/UAM:ES:42095
formation="Port Refugio" 

It isn't returned when formation="Port Refugio formation" is queried. 

I'm not sure how many others are like this.

**Comment by KatherineLAnderson** [comment]
Thanks, Dusty. I will look into those Locat IDs that belong to UAMES specimens and get back to you about how best to manage the data.

**Comment by dperriguey** [comment]
@dustymc what makes these harder to clean? What do you need from me to help? A lot of those are ours.

**Comment by dustymc** [comment]
I just don't know the intent. The data are "Semilla SandstoneFormation" (I'd think that's a formation...) and the authority (http://arctos.database.museum/info/ctDocumentation.cfm?table=CTGEOLOGY_ATTRIBUTE) that looks closest is Semilla Sandstone Member (member) - which doesn't look all that close to me.

I could mass-update them from a lookup table if that helps, I just can't guess the intent from those data.

**Comment by dperriguey** [comment]
Oh ok. I'll just confirm the geologic attributes in that list that are UNM:ES and send you an updated list in the form of "Semilla Sandstone Member (member)". I'll just have your list with duplicates removed in one column and a column with what they should be next to it. Does that work?

**Comment by dperriguey** [comment]
Here is the modified list. 

Please note:

Denton Clay Member  (member)
Denton Shale Member (member)
These are both children of the Bokchito Formation (formation), if you are modifying our records with this just make them all Denton Shale Member (member). We will modify them as needed. 

Emscherian (Stage/Age)
This is a European stage that may cross 2 of the international stages. 

Float Base of Fite  RanchFormation
This is not a formation, only a note in the locality remarks. The 3 records associated with this error can have their formation determinations removed. 
[geology_attributes_modifications.zip](https://github.com/ArctosDB/arctos/files/2341093/geology_attributes_modifications.zip)

Let me know if this does not make sense.

**Comment by KatherineLAnderson** [comment]
I fixed the geological attributes for Locality IDs that belong to UAMES: all Tindir Group listed, the "Late Pre-Cambrian",  Lower Cambrian, Port Refugio, and Schraeder Bluff localities. We should be all set on our end. Thanks Dusty!

**Comment by dustymc** [comment]
OK, I think I got what I could. Here's what was left, I pushed them to locality remarks.

I did __not__ create Emscherien - doesn't seem "formal" to me?? New Issue if we want to pull it back out please.

```

UAM@ARCTOS> select GEOLOGY_ATTRIBUTE,GEO_ATT_VALUE , LOCALITY_ID from geology_attributes where GEO_ATT_VALUE not in (select ATTRIBUTE_VALUE from geology_attribute_hierarchy) order by locality_id;

GEOLOGY_ATTRIBUTE
------------------------------------------------------------------------------------------------------------------------
GEO_ATT_VALUE
------------------------------------------------------------------------------------------------------------------------
LOCALITY_ID
-----------
group
Fredericksburg Group
   10895308

group
Fredericksburg Group
   10895311

group
Fredericksburg Group
   10895312

formation
Bridge Creek Limestone Formation
   10895838

formation
Bridge Creek Limestone Formation
   10895839

formation
Bridge Creek Limestone Formation
   10895840

formation
Bridge Creek Limestone Formation
   10895841

formation
Bridge Creek Limestone Formation
   10895842

formation
Bridge Creek Limestone Formation
   10895845

formation
Bridge Creek Limestone Formation
   10895846

formation
Bridge Creek Limestone Formation
   10895847

formation
Atarque SandstoneFormation
   10895848

formation
Bridge Creek Limestone Formation
   10895849

formation
Bridge Creek Limestone Formation
   10895850

formation
Bridge Creek Limestone Formation
   10895851

formation
Atarque SandstoneFormation
   10895852

formation
Atarque SandstoneFormation
   10895853

formation
Atarque SandstoneFormation
   10895854

Stage/Age
Emscherien
   10897887

formation
Del Rio Clay
   10903211


```
