### ISSUE TITLE
query statistics and performance

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1661]
A SQL statement...

```
SELECT distinct flat.collection_object_id ,concatSingleOtherId(flat.collection_object_id,'NK') AS CustomID, 'NK' as myCustomIdType, to_number(ConcatSingleOtherIdInt(flat.collection_object_id,'NK')) AS CustomIDInt,flat.guid guid,flat.scientific_name scientific_name,flat.country country,flat.state_prov state_prov,flat.spec_locality spec_locality,flat.verbatim_date verbatim_date,flat.dec_lat dec_lat,flat.dec_long dec_long,flat.coordinateuncertaintyinmeters coordinateuncertaintyinmeters,ConcatAttributeValue(flat.collection_object_id,'sex') sex FROM flat WHERE flat.collection_object_id IS NOT NULL and flat.COLLECTION_OBJECT_ID in ( select collection_object_id from identification where upper(scientific_name) LIKE 'RANA SYLVATICA%' union select collection_object_id from identification,identification_taxonomy,taxon_term where identification.identification_id=identification_taxonomy.identification_id and identification_taxonomy.taxon_name_id=taxon_term.taxon_name_id and upper(term) LIKE 'RANA SYLVATICA%' union select collection_object_id from identification,identification_taxonomy,common_name where identification.identification_id=identification_taxonomy.identification_id and identification_taxonomy.taxon_name_id=common_name.taxon_name_id and upper(common_name) LIKE 'RANA SYLVATICA%' ) ;
```
executes in ~2 seconds

```
708 rows selected.

Elapsed: 00:00:02.86
```

The same SQL statement into a table....

```
create table SpecSrch29F9B9A42F199CDD69D6 AS SELECT distinct flat.collection_object_id ,concatSingleOtherId(flat.collection_object_id,'NK') AS CustomID, 'NK' as myCustomIdType, to_number(ConcatSingleOtherIdInt(flat.collection_object_id,'NK')) AS CustomIDInt,flat.guid guid,flat.scientific_name scientific_name,flat.country country,flat.state_prov state_prov,flat.spec_locality spec_locality,flat.verbatim_date verbatim_date,flat.dec_lat dec_lat,flat.dec_long dec_long,flat.coordinateuncertaintyinmeters coordinateuncertaintyinmeters,ConcatAttributeValue(flat.collection_object_id,'sex') sex FROM flat WHERE flat.collection_object_id IS NOT NULL and flat.COLLECTION_OBJECT_ID in ( select collection_object_id from identification where upper(scientific_name) LIKE 'RANA SYLVATICA%' union select collection_object_id from identification,identification_taxonomy,taxon_term where identification.identification_id=identification_taxonomy.identification_id and identification_taxonomy.taxon_name_id=taxon_term.taxon_name_id and upper(term) LIKE 'RANA SYLVATICA%' union select collection_object_id from identification,identification_taxonomy,common_name where identification.identification_id=identification_taxonomy.identification_id and identification_taxonomy.taxon_name_id=common_name.taxon_name_id and upper(common_name) LIKE 'RANA SYLVATICA%' ) 
  2  ;

Table created.

Elapsed: 00:00:52.44
```

takes a minute.

Without logs...

```

UAM@ARCTOS> create table temp_testnolog NOLOGGING  AS SELECT distinct flat.collection_object_id ,concatSingleOtherId(flat.collection_object_id,'NK') AS CustomID, 'NK' as myCustomIdType, to_number(ConcatSingleOtherIdInt(flat.collection_object_id,'NK')) AS CustomIDInt,flat.guid guid,flat.scientific_name scientific_name,flat.country country,flat.state_prov state_prov,flat.spec_locality spec_locality,flat.verbatim_date verbatim_date,flat.dec_lat dec_lat,flat.dec_long dec_long,flat.coordinateuncertaintyinmeters coordinateuncertaintyinmeters,ConcatAttributeValue(flat.collection_object_id,'sex') sex FROM flat WHERE flat.collection_object_id IS NOT NULL and flat.COLLECTION_OBJECT_ID in ( select collection_object_id from identification where upper(scientific_name) LIKE 'RANA SYLVATICA%' union select collection_object_id from identification,identification_taxonomy,taxon_term where identification.identification_id=identification_taxonomy.identification_id and identification_taxonomy.taxon_name_id=taxon_term.taxon_name_id and upper(term) LIKE 'RANA SYLVATICA%' union select collection_object_id from identification,identification_taxonomy,common_name where identification.identification_id=identification_taxonomy.identification_id and identification_taxonomy.taxon_name_id=common_name.taxon_name_id and upper(common_name) LIKE 'RANA SYLVATICA%' ) ;

Table created.

Elapsed: 00:00:12.34
```

takes 12 seconds.

This is likely related to redologs (are they on the same disk?) and/or autoextend size (I'm not sure how to optimize it with the variability we see in queries).

1) An Oracle performance consultation would be very useful

2) We use redologs of user-generated tables to build query statistics (Reports/ViewStats/QueryStats). In addition to this, there's an expensive nightly script that compiles data from user-generated log files. Does anyone use that - can we NOT gather those data? We have the SQL statements in the webserver logs, but they're not very readable and don't include results (eg, how many specimens in which collections were actually returned).

**Comment by mkoo** [comment]
HI Dusty, thanks for asking but I just spent some time digging into
reports/view stats and query stats for the MVZ annual report-- I see what
you mean for costs but i am happy to also think of ways to do it all more
efficiently. I'm not sure I need all of the ones we have but what are
others using?

Which ones are the worst/ most expensive? (aka Which ones do you want to
dump first?)

BTW, Arctos seems to be the most reliable source for any usage stats for
our individual collection data-- GBIF has something now but dependent on
users citing DOIs, Vertnet no longer has anything and I cant see anything
on idigbio (unless its so well hidden)
Agenda item?
MK

**Comment by dustymc** [comment]
I don't know who's using what. If something is there is probably because someone asked for it!

We're basically saving everything forever now. Anything we can do to prune the various logs is probably useful. An AWG discussion seems useful.

- what do we actually use?
- what don't we use?
- what would we use if it was available?
- how long should we keep anything that we decide to keep?

The expensive thing seems to be just creating tables, which happens for every specimensearch query (so we can get these statistics, for pagination performance, and potentially as a way of maintaining state within a session). I really don't think we're going to be able to change this, but if we can it's easy to do so. If not, a consultant might find a way of minimizing the overhead. If that fails, we probably need to talk about throwing hardware at the problem.

For context, I'm working on https://github.com/ArctosDB/arctos/issues/1485. I was able to get a test query from ~a minute (which times out in a browser) to a couple seconds (by normalizing some relationship data), but it still times out due to the overhead in building temp tables.

**Comment by dustymc** [comment]
oracle-centric, closing
