### ISSUE TITLE
Add "liver (70% ethanol)"  and "liver (95% ethanol)" to Herp collections

### ISSUE THREAD

**Issue by jtgiermakowski** [ArctosDB/arctos#1664]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
we need ability to classify "liver (95% ethanol)" and "liver (70% ethanol)" in herp collections

**Describe the solution you'd like**
add above to SPECIMEN_PART_NAME

**Describe alternatives you've considered**

**Additional context**

**Priority**
I would like to have this resolved by date: ASAP

**Comment by dustymc** [comment]
done
