### ISSUE TITLE
Which Georeference code table is in use?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1665]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
In looking at another issue, I realized that there appear to be two code tables for the same thing. If this is the case, we should eliminate the redundancy.

**To Reproduce**
[GEOREFERENCE_PROTOCOL](http://arctos.database.museum/info/ctDocumentation.cfm?table=CTGEOREFERENCE_PROTOCOL)
[GEOREFMETHOD](http://arctos.database.museum/info/ctDocumentation.cfm?table=CTGEOREFMETHOD)

**Expected behavior**
I would expect only one code table to describe the method used to locate coordinates and error for a locality. As we display this as Georeference Protocol in data entry, the code table GEOREFERENCE_PROTOCOL seems to be the best. It also contains definitions of at least a couple of the vocabulary terms.

**Screenshots**
![image](https://user-images.githubusercontent.com/5725767/44993685-ab41d000-af58-11e8-84ed-62ed7cd1c1bb.png)

**Desktop (please complete the following information):**

**Additional context**

**Priority**
I would like to have this resolved by date: 2018-09-30

**Comment by dustymc** [comment]
<img width="246" alt="screen shot 2018-09-03 at 9 30 11 am" src="https://user-images.githubusercontent.com/5720791/44996341-3c667600-af5c-11e8-91d8-7862dc7f9544.png">

<img width="81" alt="screen shot 2018-09-03 at 9 30 21 am" src="https://user-images.githubusercontent.com/5720791/44996349-54d69080-af5c-11e8-964b-e9d547861475.png">

<img width="247" alt="screen shot 2018-09-03 at 9 30 33 am" src="https://user-images.githubusercontent.com/5720791/44996357-6750ca00-af5c-11e8-8a88-bb39e0e5dfff.png">

```
UAM@ARCTOS> drop table CTGEOREFMETHOD;

Table dropped.
```

Thanks!
