### ISSUE TITLE
New attribute - artist statement

### ISSUE THREAD

**Issue by krgomez** [ArctosDB/arctos#1666]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Table**
CTATTRIBUTE_TYPE

**Value**
artist statement

**Definition**
Verbatim statement provided by the artist about their work in general, a project, or a specific object.

**Collection type**
ART

**Attribute data type**
free-text

**Attribute units**
None

**Context**
We need a place to record verbatim artist statements that relate to specific objects. No other attributes are suitable for this and there is no other place to record an artist statement in the object record other than specimen remarks which is not the best place for this.

**Priority**
I would like to have this resolved by: whenever it is convenient to add it

**Comment by dustymc** [comment]
>work in general

That should be stored with the Agent (so it's available anywhere the agent is used).

>project

Project description, for the same reasons.

>specific object

Attribute "description" looks appropriate to me.

**Comment by AJLinn** [comment]
> specific object
> 
> Attribute "description" looks appropriate to me.

Another way you might handle this is through an attached media file (PDF in this case) with a description being called "Artist Statement" that way you could attach as pdf, video file, audio file, or handwritten note as scanned jpg.

**Comment by krgomez** [comment]
> Another way you might handle this is through an attached media file (PDF in this case) with a description being called "Artist Statement" that way you could attach as pdf, video file, audio file, or handwritten note as scanned jpg.

Aha! I think attaching the statements as media to the records will work just fine for now. I was thinking that it would be good to be able to search the text which is why I thought an attribute would be best. However at this point I don't know if that is a priority and so attaching statements as media will work. So in that case, nevermind about this attribute! Thanks for the suggestion, Angie. I will close the issue.
