### ISSUE TITLE
Borrow Media relationship dropdown

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#1667]
**Describe the bug**
The required pick-list for the media pop-up is too small to display the required selections and thus, make a selection.

**To Reproduce**
1. Go to Edit Borrow
2. Click on 'Create or Link Media'
3. Add media by drag/drop
4. See tiny dropdown pick-list for "Media relationship"

**Expected behavior**
Please make it big enough that I can select the relationship.

**Screenshots**
![ss_borrowmedia](https://user-images.githubusercontent.com/17605945/45062023-91d17e80-b053-11e8-842d-f5a1b539d5ce.jpeg)

**Desktop (please complete the following information):**
 - OS: Mac OS10.12.6
 - Browser: Chrome
 - Version 68.0.3440.106 (Official Build) (64-bit)

**Priority**
I would like to have this resolved by ASAP

**Comment by Jegelewicz** [comment]
Please resolve by 2018-09-07.

**Comment by dustymc** [comment]
This is a symptom of https://github.com/ArctosDB/arctos/issues/1668, not a problem.
