### ISSUE TITLE
Add media relationship: documents borrow

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#1668]
**Is your feature request related to a problem? Please describe.**
I need to add media to a borrow record and there is currently no relationship "documents borrow"

**Describe the solution you'd like**
I want to add media files to borrow transaction records and link them as such

**Describe alternatives you've considered**
n/a

**Additional context**
The link to add media to a borrow exists but the relationship dropdown menu is unclickable (see issue #1667 )

**Priority**
I would like to have this resolved by ASAP so I can finalize and document a report I'm filing for this borrow.

**Comment by Jegelewicz** [comment]
Can we get this done by 2018-09-07?

**Comment by dustymc** [comment]
Done. 

https://github.com/ArctosDB/arctos/issues/1597
