### ISSUE TITLE
Can we get disposition added to the 'part location' graphic display?

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#1669]
It would be very helpful to get disposition added to the part location graphic display so one can easily see if a specimen is on loan or in the collection or transferred, deaccessioned, etc. from the part location display.

I often search our database for specimens, see where they are located using the part locations display, go to look for them and only later discover, after failing to find them, that they're already on loan to someone!

**Comment by DerekSikes** [comment]
![screen shot 2018-09-07 at 7 41 08 am sep 7 18](https://user-images.githubusercontent.com/9099827/45229187-a68b5d80-b271-11e8-815d-452f64889ca6.jpg)

**Comment by dustymc** [comment]
Perfect - thanks!

Very preliminary exploration suggests this would roughly double computational cost. A loan with 14149 specimens runs in ~16 seconds with current data, and ~30 seconds with disposition added. (Disposition lives 4 tables away from the current data.) A loan with 40K specimens (biggest non-data loan) takes 40s in the current environment and 56 with disposition - that would probably time out (and eat your browser if it doesn't, so....).

The default timeout is one minute, assuming your browser doesn't get bored and wander off as sometimes happens with long-running queries. The times here are Oracle processing, then CF takes a couple seconds to package the data, then it's up to your network to deliver it and your browser to display it. That's not generally a problem in my environment, for whatever that's worth.

- does anyone experience timeout issues with the current container tree?
- is adding disposition worth the cost of bigger queries potentially timing out?
- is this better dealt with on the query side - eg, would a "disposition [NOT] IN {pick many}" search option meet the need without the constant cost?

**Comment by Jegelewicz** [comment]
@DerekSikes this is part of the part table download now - does that work for you?
