### ISSUE TITLE
Help with reciprocal relationships

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#1673]
Sorry, this issue title sounds like I need a relationship coach!
However I'm just trying to figure out how I stop getting these messages:
![ss_reciprocalrelationshipemail](https://user-images.githubusercontent.com/17605945/45237671-de070380-b28b-11e8-9ffd-fb9e4eb1b297.jpeg)

I went thru the validation, etc. process that got me this screen:
![ss_recipvalidate](https://user-images.githubusercontent.com/17605945/45237695-ef501000-b28b-11e8-9227-1961fc770c90.jpeg)

So I thought I was done... but I keep getting the email notifications each day. What am I not doing to complete the process?

This is one of the records with reciprocal relationship of "same individual as" (one mask cataloged in two collections, housed in UAM:EH)
http://arctos.database.museum/guid/UAM:Arc:1-1939-0214
![ss_recipmask](https://user-images.githubusercontent.com/17605945/45238006-c54b1d80-b28c-11e8-9ce2-aee64c94370d.jpeg)

It shows the relationship in the UAM:Arc record, but because there does not exist a option for UAM:Arc in the "Add new identifier" dropdown list, maybe that's messing up the reciprocal listing for the UAM:EH correlating record?

http://arctos.database.museum/guid/UAM:EH:1-1939-0214

**Comment by dustymc** [comment]
> there does not exist a option for UAM:Arc

I think that's the problem - it's there now, should be in the forms within the hour.

http://handbook.arctosdb.org/how_to/How-to-load-Data-Entry-linked-Attributes.html describes a similar process.
