### ISSUE TITLE
Funky display in Agent Relationships

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1674]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Funky display in Agent Relationships

**To Reproduce**
See [Robert Lloyd Rausch](http://arctos.database.museum/agents.cfm?agent_id=2570) and [Virginia R. Rausch](http://arctos.database.museum/agents.cfm?agent_id=3978)

**Expected behavior**
Expect to see the spouse's name that is clickable to their agent record as is the case with the students. It seems to work nicely from Virginia's side...

**Screenshots**
![image](https://user-images.githubusercontent.com/5725767/45243463-21279d80-b2b1-11e8-9e87-e32cc6cc7f8e.png)

![image](https://user-images.githubusercontent.com/5725767/45243481-43b9b680-b2b1-11e8-8071-2972b85d9832.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox Quantum
 - Version 61.0.2 (64-bit)

**Additional context**

**Priority**
I would like to have this resolved by date: 2018-09-30

**Comment by dustymc** [comment]
Hu? What's funky? If you mean the wrap, that's just your browser/resolution - I could force it, but it'll just do something else weird.

<img width="815" alt="screen shot 2018-09-07 at 2 46 17 pm" src="https://user-images.githubusercontent.com/5720791/45244492-e3287a80-b2ac-11e8-9b1d-b1cb6027076e.png">




(And were Bud and Virginia really married??)

**Comment by Jegelewicz** [comment]
Yes they were really married. Why does this relationship display differently from "student of"?
