### ISSUE TITLE
"possible duplicate of" message on Agent page shouldn't appear when there is a "not the same as" relationship

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1675]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Although I have added the "not the same as" relationship, I keep getting the "potential problems" red box on [Robert L. Rausch](http://arctos.database.museum/agents.cfm?agent_id=2570)

**To Reproduce**
See [Robert L. Rausch](http://arctos.database.museum/agents.cfm?agent_id=2570)

**Expected behavior**
I would expect that the relationship would mean no more "potential problem"

**Screenshots**
![image](https://user-images.githubusercontent.com/5725767/45243647-ed00ac80-b2b1-11e8-8252-bac3261cf2e3.png)

![image](https://user-images.githubusercontent.com/5725767/45243668-0144a980-b2b2-11e8-9ece-c3d9bf5b9756.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox Quantum
 - Version 64.1.1

**Additional context**

**Priority**
I would like to have this resolved by date: 2018-09-30

**Comment by dustymc** [comment]
I sort of think I like the information (it's not really an error - maybe it should be less red??) there even with relationships. Maybe whoever created the Robert L./Robert A. relationship didn't know what they were doing (in this case they did!), and I don't think it makes sense to completely trust the relationship and hide the data.

**Comment by campmlc** [comment]
I think we should get rid of the box as too much annoying visual clutter,
which is excessive in Arctos already. If it is absolutely necessary to keep
reminding people that there is a potential duplicate that really isn't
because someone has already investigated it and concluded that this
individual is "not the same as", then perhaps we need to record
determination history. Who said it wasn't the same as? remarks?

**Comment by dustymc** [comment]
We introduced "who said" in ~2014.

Remarks are never a good substitute for relationships.

http://handbook.arctosdb.org/documentation/agent.html#creating--maintaining-agents

**Comment by campmlc** [comment]
Then no reason to keep the red box.

**Comment by Jegelewicz** [comment]
Trying to close stuff and I am returning to this:

I propose that the "not the same as" relationships SHOULD NOT trigger the "possible duplicate of" message. What is the point of establishing that these two people are not the same with the "not the same as" relationship if it doesn't stop this message?

**Comment by Jegelewicz** [comment]
![image](https://user-images.githubusercontent.com/5725767/145288736-b62518b2-21b5-4668-8472-a881b0116c95.png)

should mean I DON"T see this

![image](https://user-images.githubusercontent.com/5725767/145288893-cfe2d810-95d0-4b1c-b470-84d72f3b2158.png)

**Comment by ewommack** [comment]
Agents Committee Agrees - Ready to present to AWG

**Comment by Jegelewicz** [comment]
Need priorities for the Agent "low quality data" messages/methods.

**Comment by ewommack** [comment]
Discussed at the Agents Committee Meeting - and agree that there should be error messages should be revamped.

Could there be a possible solution of the nocase first and last name match solution with allowing a verified status for Agents that gets rid of the error completely when you check a the Not a the Same As agent relationship? Committee is still not convinced that keeping the error appearing after you create a Not the Same As relationship for an agent.

**Comment by ewommack** [comment]
Additional thought is that verification status in locality/events does not produce an error that you may need to double check this locality. 
But when you add your "Not the Same As" Relationship in Agents it does approach an error still?

Should we treat localities and agents the same for verification?

**Comment by ewommack** [comment]
We want a green box for agents

**Comment by lin-fred** [comment]
Yellow box around the relationship that says "not same as" to draw attention to it, but not have an error any longer. 

Also ok with a pop up when you try to save the agent and have it say something like "make sure meta data for agents clearly denotes why these agents are not the same"

Would we also want this warning to come across email the same way agent merges do?

We seem to be overly protective of agents but not locality, even though this is a similar type of verification to the unverified/accepted system.

**Comment by ewommack** [comment]
Added to the March 2022 AWG Issues meeting for discussion

**Comment by dustymc** [comment]
Box is less red, contains better documentation.
