### ISSUE TITLE
Higher Geography - TDWG suggested vocabulary resource

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1680]
**Is your feature request related to a problem? Please describe.**
We are always looking for ways to create better Higher Geography

**Describe the solution you'd like**
There is a geography resource available: [Getty Thesaurus of Geographic Names](http://www.getty.edu/research/tools/vocabularies/tgn/) that has been recommended by [TDWG](https://github.com/tdwg/dwc-qa/wiki/Controlled-Vocabularies#darwin-core-terms-that-are-recommended-to-use-controlled-vocabularies)

Could we link to this directly? If not, could we make this our standard for approval rather than Wikipedia links?

**Describe alternatives you've considered**
Using Wikipedia as a "source" for Higher Geography confirmation.

**Additional context**

**Priority**
I would like to have this resolved by date: no date, but we should be looking at this.
Will add to Geography Committee project.

**Comment by dustymc** [comment]
Linking is easy, but doesn't DO much. What I'd really like to have is a source that we can INTEGRATE - something like we do for GenBank. A user provides {GEOG_SOURCE_IDENTIFIER}, Arctos does the rest through webservices.

Wikipedia isn't integrated (although it's much more than a link - the "TERM doesn't appear in source..." things and etc.), and it's not really an authority - it's just a tool which attempts to add some degree of standardization, mostly through the "{source} is used, are you sure this isn't a duplicate?" thing. It's certainly made our data better, but it's not an ideal solution either. (Among other things, all of the warnings can be - and often are - ignored by users.)

Getty is a very different thing that Arctos Geography. Ours aims to be some sort of higher-level authority, Getty includes things that we'd clearly consider specific locality - http://www.getty.edu/vow/TGNFullDisplay?find=mexico&place=&nation=&prev_page=1&english=Y&subjectid=2247970 for example. An authority that includes things we clearly don't want included isn't a very good authority - and Wikipeddia does this as well, of course.

That said, see https://github.com/ArctosDB/arctos/issues/1366, https://github.com/ArctosDB/arctos/issues/1278, https://github.com/ArctosDB/arctos/issues/1107, and many others - I'm not clear on what we're trying to do with geography, and I don't think we're doing it, whatever it is. I'm not fundamentally opposed to a major shift in how see geography (or place data in general).

**Comment by Jegelewicz** [comment]
Getty does have things that we would consider specific locality, but it also has things we would call Higher Geography [North and Central America, United States, Alabama, Dallas County](http://vocab.getty.edu/page/tgn/2000023)

Could we integrate that somehow? It seems like we are re-inventing the wheel with Higher Geography. If we could pick a hierarchy from Getty instead of creating our own table based on Wikipedia that allowed us to fill the [TDWG recommended fields](https://github.com/tdwg/dwc-qa/wiki/Controlled-Vocabularies#ListDwCtermsRecommendCV) we would be doing ourselves a favor.  Getty gives each record an ID - that's all we would need in Arctos to connect....

**Comment by dustymc** [comment]
>re-inventing the wheel 

Ours is rounder....

I don't think we're duplicating anything. If I did I'd have already plugged in to it. 

I see two major problems with how the Getty data line up with our current idea of geography.

http://arctos.database.museum/SpecimenResults.cfm?geog_auth_rec_id=1001487 and 
http://vocab.getty.edu/tgn/2000038 are a pretty good match. Getty has some weird ideas about continents that don't quite line up with our weird ideas about continents, but that doesn't seem fatal to me.

http://vocab.getty.edu/tgn/2133029 (some town or something) doesn't line up very well with anything in Arctos; it's something we'd stuff into specloc, and I'm not sure what we'd do to share that via DWC. Perhaps I could somehow filter - don't accept/allow things that aren't IN ({list of ranks we do want to deal with}) or something.

https://arctos.database.museum/geography.cfm?geog_auth_rec_id=10008654 doesn't line up with anything in Getty - their data are apparently hierarchical, the world (and our data) are not. ("Some National Park" is in a country, 3 states, 15 counties, is crossed by 5 drainages, etc.) This seems like the biggest obstacle.

That's all a social problem. If ya'll want to run with it, I can absolutely take "2334735" (from http://vocab.getty.edu/tgn/2334735) and turn it into some stuff for DWC and some stuff that'll help users find specimens.

**Comment by Jegelewicz** [comment]
I'm returning to this because I had a discussion with a Getty Semantic Architect at MCN. I'd like to contact them and see if we can create a 

> source that we can INTEGRATE - something like we do for GenBank. A user provides {GEOG_SOURCE_IDENTIFIER}, Arctos does the rest through webservices.

Even if this can't be done, we could use Getty as our authority (instead of or along side Wikipedia) and link to that via their IDs: "Authority (pattern: http://vocab.getty.edu/page/tgn/{ID})" no need to "be specific" because the ID should be stable. I would like to explore the possibility of enriching their thesaurus with things like https://arctos.database.museum/geography.cfm?geog_auth_rec_id=10008654 so that they would be useful not only to us, but to other biological and ethnology collections as well.

Anyone opposed to me reaching out to them?

**Comment by sharpphyl** [comment]
Not quite related to Getty, but I'm wondering of those of you working on Geography have looked at http://www.marineregions.org/ and whether it would help with some of the issues we're running into when a marine specimen is attached to a land-based name (like California or Bohol Island) but is geolocated outside the WKT.

**Comment by Jegelewicz** [comment]
Closing for lack of interest - also pretty sure this info is repeated in multiple issues.
