### ISSUE TITLE
TAGs should create Media Relations

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1682]
PROBLEM

TAGs currently provide an independent path between Media and related objects (like specimens). It's not reasonable to expect users to find both pathways; TAGs aren't as useful for finding specimens (and Media from specimens) as they should be.

SOLUTION

Creating a TAG should auto-create a media relationship between the Media being tagged and the related object if such a relationship doesn't already exist. This should all happen behind the scenes; nothing will change for users, nothing about the data structure will change, this will just provide a more general pathway in addition to the specific pathways created by TAGs.

COMPLICATION

How do we view this? We should be checking for TAGs on all Media view requests and redirecting to a viewer that can display TAGs. That'll add some processing requirements, and may break idigbio-n-such (which generally wants binaries - something TAGged Media cannot be easily reduced to).

https://github.com/ArctosDB/arctos/issues/1635

https://github.com/ArctosDB/arctos/issues/1537

https://github.com/ArctosDB/arctos/issues/1519#issuecomment-387620667

There are 15 Media TAGged to Localities. Can we address https://github.com/ArctosDB/arctos/issues/1608 ASAP? 

```
select media_id  from tag where LOCALITY_ID is not null;


  MEDIA_ID
----------
  10040399
  10242730
  10242726
  10242729
  10242735
  10242725
  10242734
  10242711
  10242710
  10242727
  10268799
  10268803
  10294550
  10268796
  10268797

15 rows selected.
```

**Comment by campmlc** [comment]
Will this make it possible to search for records with tagged media from
main search page?

**Comment by dustymc** [comment]
Yup, that's one of the primary use cases.

**Comment by dustymc** [comment]
prioritizing re: AWG meeting

**Comment by dustymc** [comment]
This is implemented in prod, but currently ignores locality. I left a note on https://github.com/ArctosDB/arctos/issues/1608
