### ISSUE TITLE
Bulk Updload Media How To

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1684]
Write documentation
Media Committee
@Jegelewicz

**Comment by Jegelewicz** [comment]
Started by adding to the [How to Upload Media to TACC](https://github.com/ArctosDB/documentation-wiki/pull/58). Needs review. I need a refresher on creating internal links and a tutorial on adding media (screenshots). @mkoo ? @dustymc

**Comment by Jegelewicz** [comment]
Edited [How to Upload Media to TACC](http://handbook.arctosdb.org/how_to/How-to-Upload-Media-to-TACC.html), [How to Create Media (Images)](http://handbook.arctosdb.org/how_to/How-to-Create-Media-Images.html) and How to Bulkload Media Metadata. Added How to Edit Media. But the last two do not appear in the index...

**Comment by Jegelewicz** [comment]
Yay! All edited How-Tos are now published. PLEASE review and suggest any edits (or make them yourself).

[Media](http://handbook.arctosdb.org/documentation/media.html)
[How To Edit Media](http://handbook.arctosdb.org/how_to/How-to-Edit-Media.html)
[How To Create Media](http://handbook.arctosdb.org/how_to/How-to-Create-Media-Images)
[How To Upload Media to TACC](http://handbook.arctosdb.org/how_to/How-to-Upload-Media-to-TACC.html)
[How To Bulkload Media Metadata](http://handbook.arctosdb.org/how_to/How-to-Bulkload-Media-Metadata.html)
[How To Understand Locality Media](http://handbook.arctosdb.org/how_to/How-to-understand-locality-media.html)

**Comment by mkoo** [comment]
Just got through these-- looking good!
I just added these links as a Resource bundle (http://handbook.arctosdb.org/resources/) since you so nicely organized the links here. Thanks! Let's close this issue
