### ISSUE TITLE
Collections Interface

### ISSUE THREAD

**Issue by jcabbott13** [ArctosDB/arctos#1685]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Priority**
I would like to have this resolved by date: _______

**Comment by jcabbott13** [comment]
I would be interested in seeing the ability to create a front end for a collection within the collections actual website rather than having to go to the Arctos domain. My understanding in talking with Dusty is that it would likely not be difficult to use the APIs already in place to accomplish this.

**Comment by Jegelewicz** [comment]
I would be interested in this as well. We are getting many requests for customization. An example would be fabulous! Any prospects for making it happen?

**Comment by AJLinn** [comment]
Dusty made this custom search entry page for our collection and it's been really handy for new users:
http://arctos.database.museum/uam_eh/search.cfm
is this what you're thinking of?

![searchscreen_uameh](https://user-images.githubusercontent.com/17605945/45720459-d596ae80-bb50-11e8-83a9-ab7f376ac6cc.jpeg)

**Comment by dustymc** [comment]
Flagging this infrastructure-limited.

There's an API (search tab), but it's aimed more towards downloading than acting as a back-end.

Depending on the scope this could involve rewriting a lot of code, probably more processors or some way to load balance, and some administrative decisions regarding access and such.

The API+rebuild is pretty simple - the code all more or less exists, it's just optimized for performance now. Many things already exist as APIs - they would need some discussion (eg, do we try to make one do-all API, or somehow unify the bits-n-pieces, or just write documentation, or ???).

I think the performance problem just needs hardware tossed at it, although that's really dependent on access. If this is completely open it could lead to orders of magnitude more traffic, if there's some key or something and we just allow "us" to use it there's potentially not much impact.

My biggest concern is presentation. We do a TON of stuff to make the data contextual in the UI - inject related event count, make links to related data, test spatial fit, etc. Without acknowledging that depth, Arctos probably sort of looks like any other glorified-spreadsheet CMS, and I am extremely hesitant to do anything which could paint us in that light. That's similar to what happens at GBIF-and-friends, but we provide them with data we know will be used in that manner (eg, anything that can be made a link has been transformed into HTML) and we license it accordingly. This isn't really an obstacle (and may not be something we should try to influence anyway, depending on "local" licensing), but I think it is something we should approach as a community. This also comes back to access - if we only let "us" in it's likely not much of a problem.

/uam_eh/search.cfm targets /SpecimenResults.cfm - anyone could write something like that and put it wherever they want. (almost - we'd need to provide JSON for authorities.)

**Comment by jcabbott13** [comment]
Sorry for the delay in responding to these emails…I’ve been swamped! I was hoping for something that truly integrated into our current website (https://collections.museums.ua.edu/ <https://collections.museums.ua.edu/>). Not just a link to another page. Our site is built around Word Press. Is that possible?

Thanks,
John
-- 

John C. Abbott 
http://www.abbottnaturephotography.com <http://www.abbottnaturephotography.com/>
 <http://www.abbottnaturephotography.com/>http://www.flickr.com/abbottnaturephotography <http://www.flickr.com/abbottnaturephotography>
http://www.facebook.com/AbbottNaturePhotography <http://www.facebook.com/AbbottNaturePhotography>
http://jcabbottnaturephotography.blogspot.com/ <http://jcabbottnaturephotography.blogspot.com/>
http://www.odonatacentral.org <http://www.odonatacentral.org/>

**Comment by jcabbott13** [comment]
Dusty,

I certainly understand the potential/real issues with having flexibility in the interface, but I think it is worth exploring. In the mean time, did you get the details I sent to change the logo, etc.. for the ALMNHH search page?

Thanks!
John

John C. Abbott, Ph.D.

Chief Curator & Director of Museum Research and Collections

University of Alabama Museums
The University of Alabama<https://www.ua.edu>
357 Mary Harmon Bryant
Box 870340
Tuscaloosa, AL 35487
Phone 205-348-0534<tel:205-348-0534> | Fax 205-348-9292<tel:205-348-9292>
jabbott1@ua.edu<mailto:jabbott1@ua.edu> | http://collections.museums.ua.edu

[The University of Alabama]<https://www.ua.edu>

Twitter<https://twitter.com/uamnh> | Facebook<https://www.facebook.com/ALMNH/?fref=ts> | Instagram<https://www.instagram.com/alabamamnh/>

Managing Editor, International Journal of Odonatology
Associate Editor, Odonatologica

Author of Dragonflies of Texas<https://utpress.utexas.edu/books/abbott-dragonflies> & Damselflies of Texas<https://utpress.utexas.edu/books/abbdap>

On Oct 2, 2018, at 10:32 AM, dustymc <notifications@github.com<mailto:notifications@github.com>> wrote:


Flagging this infrastructure-limited.

There's an API (search tab), but it's aimed more towards downloading than acting as a back-end.

Depending on the scope this could involve rewriting a lot of code, probably more processors or some way to load balance, and some administrative decisions regarding access and such.

The API+rebuild is pretty simple - the code all more or less exists, it's just optimized for performance now. Many things already exist as APIs - they would need some discussion (eg, do we try to make one do-all API, or somehow unify the bits-n-pieces, or just write documentation, or ???).

I think the performance problem just needs hardware tossed at it, although that's really dependent on access. If this is completely open it could lead to orders of magnitude more traffic, if there's some key or something and we just allow "us" to use it there's potentially not much impact.

My biggest concern is presentation. We do a TON of stuff to make the data contextual in the UI - inject related event count, make links to related data, test spatial fit, etc. Without acknowledging that depth, Arctos probably sort of looks like any other glorified-spreadsheet CMS, and I am extremely hesitant to do anything which could paint us in that light. That's similar to what happens at GBIF-and-friends, but we provide them with data we know will be used in that manner (eg, anything that can be made a link has been transformed into HTML) and we license it accordingly. This isn't really an obstacle (and may not be something we should try to influence anyway, depending on "local" licensing), but I think it is something we should approach as a community. This also comes back to access - if we only let "us" in it's likely not much of a problem.

/uam_eh/search.cfm targets /SpecimenResults.cfm - anyone could write something like that and put it wherever they want. (almost - we'd need to provide JSON for authorities.)

**Comment by dustymc** [comment]
>Word Press

My intention was to build an API that returns JSON, and I have no idea if WP can deal with that. Perhaps a simple iframe would work? (I don't know if that's possible in WP either.)

I found your message regarding the header hiding in my inbox - sorry! - but it does not have an attachement. Other than loading the logo to the webserver, you should be able to make those changes under manage collection.

**Comment by jcabbott13** [comment]
Try downloading the logo from this link, https://www.dropbox.com/s/q9jhb33brnz6uph/ALMNH_Logo_Arctos.jpg?dl=0 <https://www.dropbox.com/s/q9jhb33brnz6uph/ALMNH_Logo_Arctos.jpg?dl=0>
I’ll work on the other items and let you know if I have any questions. Thanks!
John
-- 

John C. Abbott 
http://www.abbottnaturephotography.com <http://www.abbottnaturephotography.com/>
 <http://www.abbottnaturephotography.com/>http://www.flickr.com/abbottnaturephotography <http://www.flickr.com/abbottnaturephotography>
http://www.facebook.com/AbbottNaturePhotography <http://www.facebook.com/AbbottNaturePhotography>
http://jcabbottnaturephotography.blogspot.com/ <http://jcabbottnaturephotography.blogspot.com/>
http://www.odonatacentral.org <http://www.odonatacentral.org/>

**Comment by jcabbott13** [comment]
Dusty,

I don’t believe my Arctos account (jcabbott) has admin privileges. Is that something set? Thanks,
John
-- 

John C. Abbott 
http://www.abbottnaturephotography.com <http://www.abbottnaturephotography.com/>
 <http://www.abbottnaturephotography.com/>http://www.flickr.com/abbottnaturephotography <http://www.flickr.com/abbottnaturephotography>
http://www.facebook.com/AbbottNaturePhotography <http://www.facebook.com/AbbottNaturePhotography>
http://jcabbottnaturephotography.blogspot.com/ <http://jcabbottnaturephotography.blogspot.com/>
http://www.odonatacentral.org <http://www.odonatacentral.org/>

**Comment by dustymc** [comment]
The logo will be at arctos.database.museum/images/TTg6AyPQ.jpeg after next release (hopefully tonight). I sent email regarding the user account.

**Comment by dustymc** [comment]
Closing - we now have a fully-functional JSON API.
