### ISSUE TITLE
Change documentation please

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1690]
On the [Media Documentation Code Table](http://arctos.database.museum/info/ctDocumentation.cfm?table=CTMEDIA_RELATIONSHIP&field=created%20by%20agent) please change the Documentation for "created by agent" from

> Person who pushed the button on a camera. Not the person who e.g., scripted a million JPGs (nobody cares). Related term must be an exact match for a unique agent name.

to

Indicates the person who created the media (took a photograph, wrote field notes, etc.). The related term must be an exact match for a unique Agent Name.

We need to be more professional in our documentation.

**Comment by Jegelewicz** [comment]
I cannot change the definition - I get this error:

An error occurred while processing this page!
Message: ERROR: column "tbl" does not exist Where: PL/pgSQL function trigger_fct_media_relations_ct() line 13 at RAISE
Detail:
Check the Arctos Handbook for more information on errors.

This message has been logged as DE26FF7D-D76D-4730-83EA164A6A61167E Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue.

**Comment by dustymc** [comment]
trigger rebuilt

**Comment by Jegelewicz** [comment]
Done
