### ISSUE TITLE
Ignore terminal blank from csv files created with Excel

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1691]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
For some bulkloading tools, the terminal blank generated by Excel makes no difference (specimen data bulkloader and part bulkload tool), for others the operator needs to open the .cvs in notepad, delete the terminal blank, and re-save the file as a .csv before the bulkload will complete.

**To Reproduce**
1. Go to 'Manage Data>Object_Tracking>Bulk_Edit_Container'
2. Click on 'Browse'
3. Select attached csv

**Expected behavior**
If we can bulkload specimen data that includes the Excel terminal blank, we should be able to do so with **ANY** bulkload tool. This would include all tools listed at Enter_Data>Batch_Tools as well as the Batch Edit Container Tool in the demo above.

**Screenshots**
Screen where file has been added:
![image](https://user-images.githubusercontent.com/5725767/45698644-b7678900-bb25-11e8-8a04-81177e16c872.png)

Error message:
![image](https://user-images.githubusercontent.com/5725767/45698669-c3ebe180-bb25-11e8-8eb5-1c18287f5ada.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 64.1.1

**Additional context**
This is a huge time sink for those of us using the tools on a daily basis and should be a relatively easy fix.

**Priority**
I would like to have this resolved by date: 2018-09-30
[Bulk_Edit_Labels_DGR14087.zip](https://github.com/ArctosDB/arctos/files/2393431/Bulk_Edit_Labels_DGR14087.zip)

**Comment by dustymc** [comment]
> relatively easy fix

Sorta/maybe, but with costs. Right now, you pass in CSV (which you can make with most anything), I pass it off to a third-party library (eg, it's reviewed by a LOT of users, not just "us"), and get back a data object. It's all a very well-understood process, easy to debug, etc.

You're asking to replace that library process with something non-standard; something that takes CSV, unrolls it, evaluates every line, and I suppose tosses out everything that looks like all blanks. There are a few potential problems:

1) we're no longer dealing with (de-facto in the case of CSV) Standards - we're doing something weird on top of the standard.
1) "lines" are sometimes malformed CSV (eg unescaped linefeed/break/enter chars); this would make that much harder to debug. I see this as the most likely confusing, but it's fairly rare too.
1) The unrolling is the expensive part (computationally - the source of timeout errors). Evaluating for all blanks is going to add some expense. Hard to quantify that - I expect it to be fairly minimal, but some things that work now probably won't work with changes.

Excel (I presume) occasionally tacks on a bunch of columns as well, so I get...

```
insert into table (realcolumn,secondcolumn,,,,,,,,,,,) values ('value','secondvalue',,,,,,,,,,)
```

which also fails.

Is there's some sort of "plz stop" setting in Excel, or version/plugin/something that does/doesn't do this, or other easy way to stop this at the source?

If not, are the costs worth paying?

**Comment by campmlc** [comment]
We've already done this for most forms - there are still just a few
outliers. Why are these any different?

**Comment by campmlc** [comment]
Again, this is just a request to allow a file to be bulkloaded that may
have an additional blank on the last line inserted by Excel. This has been
fixed with the main bulkloader.

Otherwise,  we  have to save the Excel file, reopen in a text editor and
manually delete the extra space. That's assuming that people understand
that's what the obscure Oracle error message is telling them to do.

**Comment by dustymc** [comment]
>Why are these any different?

The stuff we've done so far has been piecemeal - it's in the form which uploads, not the csv-->object library. That's more stuff to maintain/debug/etc., more code which I forget to include, etc. If we're trying to make this "how Arctos works" (instead of "how that form on which I remembered to strip out blank lines works") then we need a slightly different approach.

I'm pretty OK with that, just want to make sure we're aware of the costs. And I suppose I'm looking for a simple way to avoid them, if this is Excel (I think so) and there's a "don't be crazy" option (I don't think there is).

If we're rebuilding a library, we might as well do it right. Does "this is just a request to allow a file to be bulkloaded that may have an additional blank on the last line inserted by Excel." mean we DO NOT want to deal with blank columns?

>obscure Oracle error

http://handbook.arctosdb.org/documentation/understanding-errors.html#cannot-insert-null-into-schematablecolumn

**Comment by Jegelewicz** [comment]
> Does "this is just a request to allow a file to be bulkloaded that may have an additional blank on the last line inserted by Excel." mean we DO NOT want to deal with blank columns?

No. It means that I just want that LAST LINE to be ignored when it is EMPTY (there are no commas for ALL of the expected fields). Anything else should drop an error. There is no way to make Excel create a CSV without that final return which results in a line with only one field like the one attached
[Bulk_Edit_Labels_DGR14848.zip](https://github.com/ArctosDB/arctos/files/2597379/Bulk_Edit_Labels_DGR14848.zip)

**Comment by dustymc** [comment]
>there are no commas for ALL of the expected fields

I'm not sure what this means. 

>no way to make Excel create a CSV without that final return 

That is not my experience, and possibly the source of my confusion here. I opened your file in Excel, did some stuff, saved...

<img width="437" alt="screen shot 2018-11-19 at 3 35 51 pm" src="https://user-images.githubusercontent.com/5720791/48741683-d6ab9100-ec10-11e8-8253-8855e4e29efb.png">

and didn't get the new line.

<img width="437" alt="screen shot 2018-11-19 at 3 35 57 pm" src="https://user-images.githubusercontent.com/5720791/48741698-e32fe980-ec10-11e8-9a4d-8bad4e27684f.png">

I can even hit ENTER and TAB a bunch of times and get the same thing...

<img width="602" alt="screen shot 2018-11-19 at 3 38 08 pm" src="https://user-images.githubusercontent.com/5720791/48741777-3b66eb80-ec11-11e8-9bb4-7d2cae8d3e00.png">


<img width="403" alt="screen shot 2018-11-19 at 3 39 03 pm" src="https://user-images.githubusercontent.com/5720791/48741782-46218080-ec11-11e8-92c3-5c2a4689ed50.png">


I have to do something like this to get all-NULL rows, and even then the last one is fine.

<img width="331" alt="screen shot 2018-11-19 at 3 39 27 pm" src="https://user-images.githubusercontent.com/5720791/48741823-749f5b80-ec11-11e8-8b19-70a0bd26bf24.png">

<img width="574" alt="screen shot 2018-11-19 at 3 39 53 pm" src="https://user-images.githubusercontent.com/5720791/48741826-7832e280-ec11-11e8-932f-0194ec48674b.png">

deleting that trims everything back to where it should be

<img width="416" alt="screen shot 2018-11-19 at 3 40 50 pm" src="https://user-images.githubusercontent.com/5720791/48741868-9ac4fb80-ec11-11e8-94d3-fb0400cb0896.png">

<img width="488" alt="screen shot 2018-11-19 at 3 41 05 pm" src="https://user-images.githubusercontent.com/5720791/48741858-9567b100-ec11-11e8-9713-5b734aeb5492.png">

IDK, I can't replicate this, which makes me suspect there's something more going on here.

Can anyone else replicate?

**Comment by Jegelewicz** [comment]
Did you try to upload any of those files? When you open mine in notepad it looks like this:

![image](https://user-images.githubusercontent.com/5725767/48742202-31e28100-ec1b-11e8-8cd9-5efbbca234b2.png)

Notice that the cursor is one line below the last line of the file (there is a carriage return). I can delete this by pressing back space once and saving IN NOTEPAD. If I re-open in Excel and save, the return will be there again and requires me to open in Notepad and backspace.

**Comment by Jegelewicz** [comment]
BTW in Excel, the file looks like this:

![image](https://user-images.githubusercontent.com/5725767/48742271-80901b00-ec1b-11e8-9797-f6fdeb4b58cc.png)

**Comment by dustymc** [comment]
Yes, I uploaded your original, Just In Case, although my editor and Arctos should be seeing the same thing. Maybe notepad is adding the line? IIRC notepad is not UTF (and eats some UTF characters, not that that's likely to be a problem with containers) - could be it's doing something janky with line terminators.

**Comment by campmlc** [comment]
For awhile Excel for Mac was not adding the line but Excel for Windows was.
Maybe a platform issue?

**Comment by Jegelewicz** [comment]
Before opening in notepad and deleting the backspace, the file WILL NOT LOAD and I get the error above. After opening in Notepad and deleting the backspace then re-saving it loads just fine.

**Comment by Jegelewicz** [comment]
Yes, Windows 10.
[Bulk_Edit_Labels_DGR14848.zip](https://github.com/ArctosDB/arctos/files/2600841/Bulk_Edit_Labels_DGR14848.zip)

**Comment by Jegelewicz** [comment]
I just attempted to load that and got this
![image](https://user-images.githubusercontent.com/5725767/48791071-14aac280-ecae-11e8-8a6b-fda8baa0a4cd.png)

**Comment by dustymc** [comment]
Thanks!

FWIW it seems like really specific version of Excel, I think all on Windows, have that "feature" (or not), and it seems to come and go with updates and such. Yay Microsoft...

That's not quite what I thought was happening, and at least for that form I think I've found a clever (cheap, anyway) way to get rid of the extraneous linefeed. That'll be in the next release. Please let me know if it works/doesn't break something else - if so I can push it to the other uploads. I'll leave this open until we've tested that with some more data.

**Comment by campmlc** [comment]
Bulkloaders that still cannot deal with terminal space:

Bulkload Loan Items

**Comment by campmlc** [comment]
Nevermind - there was actually a space in the data!

**Comment by dustymc** [comment]
This shouldn't be an issue in PG, and uploading is now modular so similar problems will be easy to deal with if they come to exist.
