### ISSUE TITLE
Add entered by/last edited by to media

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1692]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

From #1582 - we need information about who created media relationships.

> We do record who made relationships and labels, and that could be more prominent.

**Describe the solution you'd like**

Publish entered by and last edited by on the media detail page, just like we do on the specimen detail page (see purple rectangles).

![image](https://user-images.githubusercontent.com/5725767/45701598-ea614b00-bb2c-11e8-9e10-e7b30d440af2.png)

![image](https://user-images.githubusercontent.com/5725767/45701527-b423cb80-bb2c-11e8-8d1e-94ff29bf64c7.png)

**Describe alternatives you've considered**

**Additional context**

**Priority**
I would like to have this resolved by date: _______

**Comment by dustymc** [comment]
Are you asking for relationships only?

If you want edited, I'll need to know what exactly constitutes an edit.

**Comment by Jegelewicz** [comment]
I'd like it to be any change to the media record, but understand if that would require too much up-keep. Could you let me know how feasible that scenario would be and what alternatives would work better if it's too much?

Could we go ahead with the "entered by" part?

**Comment by dustymc** [comment]
>entered by

I'm still not clear - are we talking relationships or something else?

>any change to the media record

Defining "the record" is the problem here (and https://github.com/ArctosDB/arctos/issues/579). I don't really see an approach that doesn't involve a specific list of things that cause edits (eg, are considered "part of the record").

**Comment by Jegelewicz** [comment]
To me the media "record" means this stuff:

![image](https://user-images.githubusercontent.com/5725767/45720348-3c23c880-bb61-11e8-9369-a6ceb5e687ec.png)

**Comment by dustymc** [comment]
done
