### ISSUE TITLE
do more with CrossRef API

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1693]
**Is your feature request related to a problem? Please describe.**
1) We need to plug existing calls into crossref's updated API
2) The API now offers a lot more information. We should pull and display funding, citations, etc. with publication. (Start with Projects?)

**Describe the solution you'd like**
do it

**Describe alternatives you've considered**
there are none

**Additional context**
Check publication title while we have it handy; do something if the match isn't good

**Comment by dustymc** [comment]
This is implemented at a basic level (click the "CrossRef Data" links) - publications now actively pull crossref data, and preemptively display reference and referenced by count.

Some of the data comes from http://opencitations.net/ which is down right now - it may be worth exploring alternate sources of those data (eg, paid crossref subscription).

Many publications have limited or unpredictable data which limits their utility. I don't really know how this works, but perhaps we could provide guidelines (eg, with loans) or build publication submission tools (extension of the genbank submission form?) or work with CrossRef or something similar.

- References by DOI lead to other publications, which lead to more publication/author/funding/etc. data. Many references are strings, and some of them are completely useless ("1984"). 

- NSF funding data is apparently by string. http://arctos.database.museum/publication/10008279 includes funding data, but the award number is entered as "DEB-1745267" (which 404s on NSF's site) - "1745267" successfully pulls NSF data (which lets us get at things like the financial impact of collecting specimens and the research supported by those specimens).

- A few authors have ORCID data, and Arctos now supports an ORCID address type. When those data coincide, we can ask deep questions of Agents.

**Comment by campmlc** [comment]
Do we need to do something with NSF awards, e.g. treat them as other IDs so
that we can have an  ID of "NSF:DEB" ?

**Comment by dustymc** [comment]
The comments above are regarding crossref data - click the link above, click view data, https://api.crossref.org/v1/works/http://dx.doi.org/10.1002/ar.23752

<img width="644" alt="screen shot 2018-10-04 at 9 54 25 am" src="https://user-images.githubusercontent.com/5720791/46489943-85a82080-c7bb-11e8-8b51-e403e27ae06b.png">

I have no idea where that comes from, but if it's provided by authors and we can provide better instructions to those authors, then we should ultimately get data which can DO STUFF (eg, quantify the financial impact a specimen in a research-grade system has on scientific research).

Arctos funding data belongs in projects, not OtherIDs. We should probably be doing something there, and that "something" should be driven by what allows us to access services. The NSF bit comes from Agents. NSF's system doesn't care about the "DEB-" bits, so that should not be included. I'll worry about it when someone enters one!
