### ISSUE TITLE
Deep-linking projects, publications, and funding

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1694]
There's been an option to record funding to a little over 2 years now (https://github.com/ArctosDB/arctos/issues/826). 8 projects currently have funding data, one of them has associated award numbers, but the one with award data has no publications in Arctos.

I can do little more than we're doing to demonstrate the impact of museum collections without these data. (I could also use them to eg, find publications which probably should be, but are not, in Arctos, possibly link those to loans which may need followthrough, etc.)

"Fundref" has become a reality, so my part of this is to create a more formal place for the NSF#s, which can in fact now "do something." (https://search.crossref.org/?q=DEB-1557053 / http://api.crossref.org/works?filter=award.number:DEB-1557053).

Is there anything else I can do to encourage/simplify/etc. creating projects, supplying funding data with those projects, and including DOIs with publications?

I also added an agent address type "ORCID" - providing those data would allow unambiguously linking eg, authors of papers which don't cite specimens to loans.

**Comment by dustymc** [comment]
I'm responding to https://github.com/ArctosDB/arctos/issues/826#issuecomment-422870687 here.

A dedicated place for award number will be in next release. It doesn't really do anything useful unless someone uses it. Please let me know if those data have been recorded anywhere other than project_agent_role=Sponsor's remarks and I can probably recover them.

I can't overstress the "impact factor" implications of recording these data.

CrossRef is linking funding to publications (and vise-versa).

Crossref supplies a list of references used from publications.

http://opencitations.net provides a list of publications which reference a publication (via a paid CrossRef subscription). 

From that information and a citation, it should be possible to paint a multidimensional picture of the true impact of a specimen cataloged in a research-grade database. We can get at the activity (eg, research and funding) which lead to the specimen being collected, the activity it supported directly (what we can do now with citations), and all activity that activity supported. We can do this at any "depth" - citations link directly to publications, but those publications are also linked to publications which they referenced and which referenced them, those in turn are linked to more publications in both directions, some of those are linked to awards, etc. With the inclusion of ORCID, we can also do that from the perspective of agents, organizations, etc. 

There are of course a million dependencies - older publications sometimes lack DOIs (although those are being rapidly added), references are sometimes provided as text rather than DOIs (although those are becoming resolvable as DOIs are added), many/most authors do not have ORCIDs, etc. There's little we can do about that, but perhaps we can do a better job of encouraging those things (eg, via loan agreements) going forward, and we can certainly do a better job of recording the data which provides access to this system (publication DOIs, specimen DOIs for citations, ORCID for agents, and award numbers for projects).

**Comment by dustymc** [comment]
There are lots of publications which are not in Arctos (or not in Arctos with a DOI - effectively the same thing) which reference or are referenced by Arctos publications. I'm tempted to add an "add to Arctos" button to the developing form. I can auto-create them from the DOI using the crossref-provided title. I probably wouldn't try to grab agents, which are an unpredictable mess in both crossref and Arctos (excepting those with an ORCID). These would then be findable with the "cites no specimens" search option (and I could add a "auto-inserted" remark).

- ~75% of the publications in Arctos already cite nothing (data below) so I'm not actually sure if this will make them more findable or not
- this would probably create some duplicates, but they'd be duplicates of low-quality (no DOI) data
- title formatting from crossref is pretty horrible, so this is likely to be ugly, although functional

What should I do?

```
UAM@ARCTOS> select count(*) from publication;

  COUNT(*)
----------
      7641

1 row selected.

Elapsed: 00:00:00.02
UAM@ARCTOS> select count(distinct(publication_id)) from citation;

COUNT(DISTINCT(PUBLICATION_ID))
-------------------------------
			   2488

```

**Comment by campmlc** [comment]
These would get auto added to Arctos? I dont see any problems, but we might
want to know what might be related to different collections. If a paper
cites a paper citing specimens, especially. Another notification once or
twice a year? "The following pubs cite papers related to your collection"?

**Comment by dustymc** [comment]
>These would get auto added to Arctos? 

Well not auto, but one-click. I was just noticing a LOT of familiar names while browsing around, there's no way most of them avoided looking at specimens.

>we might want to know what might be related to different collections.

There's a limit to the magic. A lot of loaned material isn't documented at all (eg, "undocumented citations" report), perhaps most loans never result in anything (seems incredibly unlikely), etc. We have to figure out a way of doing a better job with that. (Providing DataCite DOIs with loans would help - I can find them, even if everything else fails).

>"The following pubs cite papers related to your collection"

I think the average is around 50 citations per publication (based on some random clicking), there are literally hundreds of thousands of the things. We can certainly do more with the data via services, but I'm not sure it's going to involve emailing giant lists.

**Comment by campmlc** [comment]
Reviving this - do we need to find any funding to revive this? How can we enable the linkage between citations, catalog records, publications, and projects so that publications can get auto-added to projects when a citations are linked to catalog records?
@dustymc

**Comment by dustymc** [comment]
>do we need to find any funding to revive this?

Only if you want to document the true impact factor of your collection.

>publications can get auto-added to projects when a citations are linked to catalog records

Hu?


* loan Specimen1 and create a project
* loan Specimen1 and create a project
* loan Specimen1 and create a project
* find a citation for Specimen1 in some publication

there's no way of knowing where the citation came from - maybe none of those projects cited anything and this is a typo or based on a piece of tissue that a grad student smuggled out of a freezer ('[undocumented genbank](http://arctos.database.museum/info/undocumentedCitations.cfm?action=genbanknocite&collectionid=14)' records come from SOMEWHERE!) or ....

If I'm vaguely understanding the question, I'm not sure there's a natural relationship there.

https://github.com/ArctosDB/arctos/issues/1257 might get us a bit closer to something like that, but I think it would require the community to commit to a different level of documentation.

**Comment by campmlc** [comment]
Here is the question I'm trying to resolve - there may not be a problem, so
I'm hoping for clarification.
1) specimens are collected and entered into an accession
2) accession is linked to a project - "contributed items"
3) cataloged items in the accession then are loaned for various projects
4) these loans are linked to projects to document usage; "used items"
5) The loans result in publications, which cite the specimens
6) How do the publications resulting from the use of these specimens get
added to the original project linked to the accession?
7) If the answer is  that we have to manually enter publications not only
to cited vouchers, but to projects, its not happening in any consistent way.

**Comment by dustymc** [comment]
Gotcha - that's just a UI problem, those data are all there (under 'projects contributing...' and such). I think there's ALWAYS a better way to display ANYTHING, but I don't have a clue what it might be in this case - I think it's pretty easy to hop around between usage-linked projects as-is.

In Arctos projects, it's easy to go from a a project that produced a publication to the project that contributed the specimen. 

If they have funding data, you can say things like 'this $xx that collected dead rats directly supported that $yyy worth of research."

Add in the data from Crossref, and you can say the above PLUS "... and that research was cited by another $zzzz dollars worth of research, all of which was ultimately supported by the funding that got the dead rat into a museum and accessible to the scientific community."

**Comment by dustymc** [comment]
Tabling for apparent lack of interest.
