### ISSUE TITLE
classification bulkloader notifications

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1696]
The hierarchical taxonomy editor writes to the classification bulkloader, which overwrites classification data potentially affecting specimens in many collections. 

Add some sort of notification BEFORE load to the loader, but don't let it become a huge bottleneck. (Maybe allow load 24 hours after the notification goes out??)

**Comment by sharpphyl** [comment]
I just want to support moving forward on this project.  I'm sitting on a complete redo of a large superfamily because I don't want to spend the time figuring out who has a record in that superfamily and contact them for agreement.

Dusty, if we all agree to go forward with an update of mollusca or all marine species through WoRMS, would you be able to identify the taxa that will change genus or family from the current Arctos classification?

**Comment by Jegelewicz** [comment]
Agree, but we need a written protocol for managing taxa in this way. I might have time to write something up this week - if anyone else has time, please jump in...

**Comment by sharpphyl** [comment]
Here's an example of the problem we may have when using the hierarchical tool to manage our taxonomy. We need a communication system that will decide which collection is responsible for a taxon in Arctos and deal with errors. 

One of the errors that was listed when I uploaded Littorinimorpha (http://arctos.database.museum/tools/taxonomyTree.cfm?action=seedMIA&dataset_name=Littorinimorpha) was _Lunatia subcrassa_.  Our collection isn't using this taxon.  Our new taxon validator tool says it's probably not valid.  I would propose deleting it so it doesn't reappear on the error list, but it turns out that it's being used by UNM.

![screen shot 2018-09-24 at 2 13 02 pm](https://user-images.githubusercontent.com/15368365/45976925-4e8c7f00-c005-11e8-8682-60c2bdaee090.png)

Is there anyway to assign some taxa to just one collection if they want to use it?  This is a fossil taxa and not in WoRMS.  The scientific name and the display name do not match but only UNM can correct this problem in the way that best fits their collection.  When these issues are uncovered by one Arctos user who is using the hierarchical tool, can there be a automatic redirect to the appropriate user for correction?

**Comment by dustymc** [comment]
>decide which collection is responsible for a taxon in Arctos and deal with errors.

Whoever prefers the classification has a stake in that. I'm happy to try to work out notifications and such, and the intent should always be to avoid stepping on toes, but ultimately there's a mechanism for sharing these data or avoiding that, and collections using shared data should expect - hope for! - others to fix "their" bad data.

>taxon validator tool says it's probably not valid.

That thing is unfortunately just one tool, and it's far from perfect. Yay taxonomy...

>deleting

It very easily passes "the Google test" - I have no idea if it's "real" or not, but it's certainly in widespread use so I think it's good enough for Arctos.

> The scientific name and the display name do not match 

The classification just doesn't fit the taxon name. I should really maintain the list of reasons to push this all to the hierarchical editor....

> only UNM can correct this problem in the way that best fits their collection.

Anyone (with manage_taxonomy) can edit the classification. I have no idea what they're trying to do, but these data aren't capable of doing it! Edit away....

> can there be a automatic redirect to the appropriate user for correction

Just "Report Problem" from the taxon page (but https://github.com/ArctosDB/arctos/issues/1679).

@dperriguey  can you fix the classification data at http://arctos.database.museum/name/Lunatia%20subcrassa please?

**Comment by dustymc** [comment]
Next release will have a link which returns 'data quality' emails.

**Comment by dperriguey** [comment]
@sharpphyl I edited our record

**Comment by dustymc** [comment]
http://arctos.database.museum/name/Lunatia%20subcrassa still has some random classification attached.

<img width="918" alt="screen shot 2018-09-27 at 1 30 58 pm" src="https://user-images.githubusercontent.com/5720791/46172898-9d325700-c259-11e8-8ddb-a273188abc36.png">

**Comment by dperriguey** [comment]
I see that. But when I go to edit the classification the only thing available is nomenclatural_code. What should I do?

**Comment by sharpphyl** [comment]
Can't you add rows?

![screen shot 2018-09-28 at 8 40 00 am](https://user-images.githubusercontent.com/15368365/46215284-3f098080-c2fa-11e8-8056-544e3dadfebc.png)

**Comment by dperriguey** [comment]
Sure I can add rows. I hope that won't mess something up since there is already something in there.

**Comment by dperriguey** [comment]
Oh, actually I don't have those options when I add new rows. Not sure why??? I'm guessing because they are already assigned?

**Comment by sharpphyl** [comment]
Not sure I totally understand what you're trying to do.  Are you saying that you don't get these options when you click on the down arrow?  

![screen shot 2018-09-28 at 8 48 10 am](https://user-images.githubusercontent.com/15368365/46215715-4e3cfe00-c2fb-11e8-8c8c-27717bb9edd5.png)

**Comment by dperriguey** [comment]
No I totally get those options. There are no options to change the display_name or scientific_name in there. Regardless, that taxon just needs to be deleted. I put Euspira subcrassa in yesterday and Lunatia sucrassa is just acting as a weird duplicate. Done.

**Comment by sharpphyl** [comment]
Ah, I see that the scientific name and the display name don't match.  Both are autogenerated.  Per WoRMS, Lunatia isn't an accepted genus anymore.  But WoRMs also doesn't list Euspira subcrassa as a valid species.  Maybe it's more of an identification problem than an Arctos taxonomy problem.

**Comment by sharpphyl** [comment]
Sorry, our messages crossed midair.  Looks like you've taken care of the problem.

**Comment by dperriguey** [comment]
I need to have this specimen in the database. I get that WoRMS doesn't have it as a valid species, but what am I supposed to do if the taxonomy has changed, I have papers from the 90's that designate the old taxonomy. I'm willing to bet that it is in the Euspira genus. I trust WoRMS, but I have had this problem a few times now. I have something I want to use the updated WoRMS taxonomy, but they haven't looked at the species level. I know that not all species follow some genus taxonomic update. What should I do? Should I just leave it at the genus level with the tacked on legacy identification for someones reference?

**Comment by dustymc** [comment]
This should all be spelled out in http://handbook.arctosdb.org/documentation/taxonomy.html - PLEASE let me know what's not clear and I'll update.

>accepted

That's irrelevant, although it might control taxon_status.

Lunatia sucrassa fails 'the google test' (eg, it looks like something we just made up rather than a valid taxon that's somehow fallen out of favor)

>No results found for "Lunatia sucrassa".

so lacking other evidence I'd support deletion.

If you can (even theoretically) come up with a publication that someone might have considered to be part of the body of literature that is taxonomy at some point, then it's taxonomy-ish enough for Arctos.

The A {string} ID formula exists for things which are clearly not taxonomy but do appear on labels.

The autogeneration is doing strange things in response to the inconsistent data; there's just no obvious relationship between the name and the classification.

**Comment by sharpphyl** [comment]
Dusty, Can you reload "clams."  I would expect that to be Kingdom: Animalia, Phylum: Mollusca but when I try to seed it, I get 0 taxa.  I worked on Littorinimorpha most of the day but forgot that when I moved several superfamilies into that order, they don't have the updated Taxon Status, so I'm getting hundreds of error messages when I create the csv.  I might as well start from scratch with whatever is in Mollusca right now.  Thanks.

BTW all day when I tried to move a taxon to a new parent I got this error message.  It worked fine if I did a drag and drop.  

![screen shot 2018-09-28 at 11 37 39 am](https://user-images.githubusercontent.com/15368365/46237768-fb3b6900-c343-11e8-9fa2-9f8a5863edb6.png)

**Comment by sharpphyl** [comment]
OK, I got it to find 37,036 Mollusca taxa by leaving Kingdom blank.  But when I try to seed them, I get this error message.  

![screen shot 2018-09-29 at 9 51 55 am](https://user-images.githubusercontent.com/15368365/46247774-7b59e100-c3cd-11e8-831d-b418e1292112.png)

Looks like I still need to help to get all the taxa reloaded.

**Comment by dustymc** [comment]
The unique constraint error is from this:

> You can also delete what you've seeded. This removes the seeded data only, and does not affect anything already in the hierarchy. This can be handy when trying to import data which overlaps with existing data. 

The scripts can't reliably tell when you've dealt with the import errors you want to deal with and such, so making that step an explicit action seemed the safest way to prevent mystery-data.

I'll get the parent thing in next release, hopefully tonight.

**Comment by sharpphyl** [comment]
Just to confirm, I should delete Mollusca before I reload it?  I don't want to delete everything you uploaded since you included (I think) other phyla in our collection.

**Comment by sharpphyl** [comment]
OK, I deleted the last upload and it worked this time.  Still learning.

**Comment by dustymc** [comment]
>Still learning

Me too! Please consider updating http://handbook.arctosdb.org/how_to/How-to-Manage-Taxonomy-Hierarchically.html with any relevant discoveries - I'm happy to help with formatting or whatever.

**Comment by sharpphyl** [comment]
Can you help me better understand the Import Error details.  I don't see them in the Handbook.  Do I need to do anything about them?

import_missed_term - I have a ton of these and checked two by clicking on "Arctos Taxonomy" and "tree" and in both cases the term is there and looks ok.   

"inserted term" - again I checked a few and everything looks ok.

"missed taxon name" - these look like the only ones I actually need to correct (some look ok, others don't).  What are the reasons that Arctos skips a name?  I see some (subgenera) and a few true errors and others look fine.

Thx.

**Comment by dustymc** [comment]
>import_missed_term - I have a ton of these and checked two by clicking on "Arctos Taxonomy" and "tree" and in both cases the term is there and looks ok.

Did you alter the tree? These are terms which appear in the Arctos data and not in the import. They're often cryptic - an extra space or something. If there's nothing obvious missing and no weird terms hanging out in the middle of nowhere in the tree, it's probably safe to ignore. Give me a specific term and I'll track it down in a fresh hierarchy.

>"inserted term" - again I checked a few and everything looks ok.

That's "stuff's still running, haven't got around to importing nonclassification data yet" - they should go away by themselves.

>"missed taxon name" - these look like the only ones I actually need to correct (some look ok, others don't). What are the reasons that Arctos skips a name? I see some (subgenera) and a few true errors and others look fine.

Subgenera (as they're typically used/entered in Arctos, anyway) are not hierarchical/don't follow the pattern and don't really fit into the hierarchical editor. They cause other problems as well, I'd like to get rid of them - https://github.com/ArctosDB/arctos/issues/1704

Otherwise, this is generally just complete confusion by the import scripts. http://arctos.database.museum/name/Isselia looks like...

<img width="889" alt="screen shot 2018-10-01 at 8 24 45 am" src="https://user-images.githubusercontent.com/5720791/46298265-79218f00-c553-11e8-9e55-a519fc8a1c2a.png">

for example - the name (Isselia) doesn't appear anywhere in the classification, that's can't possibly be represented hierarchically, so something unpredictable happens. (See https://en.wikipedia.org/wiki/Gigo).

**Comment by sharpphyl** [comment]
Thanks.  I'll work through them and let you know if more issues come up.  Yes, it would be helpful to have this information in the Handbook or also on the page where they appear.
