### ISSUE TITLE
Email about open flags added on data entry

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1702]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

From Taxonomy Committee Notes: On entering new records, when two identifications are available, it is difficult to remember to go back and add the second after data is loaded. Dusty suggests adding a flag, but that might be forgotten as well. Mariel suggests a notification of outstanding flags

**Is your feature request related to a problem? Please describe.**
Flags to remind operators that additional data needs to be entered for a record can be overlooked.

**Describe the solution you'd like**
Add "you have Needs additional data flags to review" to monthly notification email.

**Describe alternatives you've considered**
Get a bigger brain - Remember you have entered flags (or gather through some mysterious method that those entering data for you have entered them)

**Additional context**

**Priority**
I would like to have this resolved by date: 2018-10-31

**Comment by dustymc** [comment]
I think two things came up at about the same time.

1) There are too many emails, we don't have time, they don't get read.
2) Please send more email.

If we're getting overwhelmed - and we probably are - I'm hesitant to add to the pile with low-priority/non time-sensitive notifications.

https://github.com/ArctosDB/arctos/issues/1419

**Comment by Jegelewicz** [comment]
Closing for lack of participation.
