### ISSUE TITLE
Could not access "neotoma" dataset during Taxonomy meeting

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/arctos#1703]
I was having great difficulties in our meeting yesterday, as I was unable to access ANY of the datasets in the list created by Dusty once I was unblocked.  Every one I clicked on said, "0 Records." How does one get around this???  There appears to be so many undisclosed layers in Arctos that it takes a personal guide to show us newbies how it all works.  I haven't really had the opportunity to experiment with Arctos because I am trying to clean our data for the migration...which pretty much consumes what little available time I have.  

Sorry if I sound frustrated, but I am!  I wasted an hour and a half yesterday not being able to see what was going on.  Thanks, Mary Beth

**Comment by campmlc** [comment]
I'm sorry, Mary Beth. I just checked your taxonomy access and that looks
OK. I agree absolutely that we need more helpful error messages that
provide suggestive content to troubleshoot when we try to do something that
doesn't work. Dusty, any ideas on what went wrong?

**Comment by dustymc** [comment]
Just a guess, but that sounds like your browser to me. My second guess is your network.

<img width="264" alt="screen shot 2018-09-20 at 6 48 55 am" src="https://user-images.githubusercontent.com/5720791/45822993-8744f500-bca1-11e8-8659-0df1b470e79f.png">

is Arctos form permissions

<img width="848" alt="screen shot 2018-09-20 at 6 49 18 am" src="https://user-images.githubusercontent.com/5720791/45823007-92982080-bca1-11e8-98b9-b8198ad6862d.png">

Your permissions:

<img width="306" alt="screen shot 2018-09-20 at 6 53 59 am" src="https://user-images.githubusercontent.com/5720791/45823185-00444c80-bca2-11e8-9073-7386ecac4fb1.png">

and from there

<img width="361" alt="screen shot 2018-09-20 at 6 54 37 am" src="https://user-images.githubusercontent.com/5720791/45823222-16eaa380-bca2-11e8-8044-ffd21a492096.png">


then

[ Def ]

provides CRUD info

<img width="542" alt="screen shot 2018-09-20 at 6 55 28 am" src="https://user-images.githubusercontent.com/5720791/45823319-47cad880-bca2-11e8-9ea3-2525fea52af8.png">

If you can see the form, you should be able to use it. I can't really imagine this could be happening on anything I control.

As far as the personal guide, I think you may have come in right before we came to the same conclusion. 

<img width="137" alt="screen shot 2018-09-20 at 7 01 06 am" src="https://user-images.githubusercontent.com/5720791/45823662-025adb00-bca3-11e8-888a-dd0676efe30e.png">

should find someone willing to help.

**Comment by mbprondzinski** [comment]
Okay, Dusty.  I went back and went through all this but inadvertently  deleted my “Collections” (ALMNH)  administration!  How do I get that back???!  Sorry, but I needed to click a lot of buttons to go through all this and didn’t know I couldn’t get my “collections” back.

As for a “mentor;”  there is nobody listed, but Teresa has been kind enough to offer me assistance if and when I need it.   I also used GitHub for the first time as I understand that is where I am supposed share my “issues.”  So I’m still in experimental mode… please bear with me!

Thanks for your help…

Mary Beth

**Comment by dustymc** [comment]
You should have your collection back. You may need to log out and back in for that to fully stick.

Please let us know if you have any problems - we're always trying to make the process better.

**Comment by mbprondzinski** [comment]
Thank you!

**Comment by campmlc** [comment]
Yes, Mary Beth, you did come in right before we implemented our mentor
system . So please feel free to reach out to either me or Teresa, and also
to the Github issues site which allows you to ask questions and suggest
improvements to Dusty and the community at large. Please let us know
anytime you find something confusing so we can update the documentation and
get things clarified, as that benefits everyone. Thanks!

**Comment by mbprondzinski** [comment]
Thanks, Mariel!
