### ISSUE TITLE
change recipients of "Arctos Pending Data Notification" emails

### ISSUE THREAD

**Issue by AdrienneRaniszewski** [ArctosDB/arctos#1711]
If nobody minds, I'd like to have this email (below) changed so it only goes out to the usual "data quality" people for each collection. My student staff (and even some former student staff) have been receiving this email daily and there is nothing they can actually do about it. I'm just slow to clean up those "data entry extras" that have gotten separated from their records.

Thanks.

------------
You are receiving this message because you have data in a bulkloader available from "data entry extras," or because you have manage_collection for a user with data in a bulkloader available from "data entry extras."

Data for specimens which have not yet been entered are available at EnterData/Bulkloader/BrowseAndEdit-->Extras or the individual bulkloaders.

NOTE: Records which have been orphaned by deleting from the specimen bulkloader or changing UUID in either the specimen bulkloader or the individual bulkloader will NOT be available at EnterData/Bulkloader/BrowseAndEdit-->Extras. These must be reconciled from the individual bulkloader.

Data for specimens which have been entered are available at EnterData/Bulkloader/ExtrasForLoadedSpecimens or the individual bulkloaders.

**Comment by campmlc** [comment]
I agree with this. There is no reason students or anyone who does not have permission to load records should be receiving these emails.

**Comment by dustymc** [comment]
I need to know exactly what ya'll want.

"data quality" is (in my view, anyway) more aimed at external stuff (like annotation). The documentation at http://arctos.database.museum/info/ctDocumentation.cfm?table=CTCOLL_CONTACT_ROLE could use help. Collection contacts are not tied to any permissions.

manage_collection role is "has permission to load"

**Comment by campmlc** [comment]
We need to delete emails to people who* "have data in a bulkloader
available from "data entry extras,"*
and only send emails to people who  " *have manage collection for a user
with data in a bulkloader available from "data entry extras."*

**Comment by dustymc** [comment]
Alerts will go to manage_collection users only in next release.
