### ISSUE TITLE
Red Box tweak to reduce eye-searing

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#1712]
Specifically this is referring to the Geography Edit page where a large red box lists the impacted localities of any edits to Higher Geography.

Currently the text on the red background is blue so really hard on the eyes if there are a large list of them. Examples below.
Current:
![screen shot 2018-10-01 at 4 54 35 pm](https://user-images.githubusercontent.com/2523089/46321899-e3a9ed80-c59a-11e8-8153-15f4e729eae2.png)

Suggested:
![screen shot 2018-10-01 at 5 04 05 pm](https://user-images.githubusercontent.com/2523089/46322128-0dafdf80-c59c-11e8-96e8-090779d5eb44.png)

CSS snippet for above if it helps:
<style>
body {    
    background-color: red;    
}    
h1, a {    
    color: white;      
    text-decoration:none;    
}   
p {    
    font-family: verdana;    
    font-size: 20px;    /*large font for the example purposes only!*/
}    
</style>    

I dont know if that will be better until we try it!

**Priority**
I would like to have this resolved by date: __upcoming webinar is Oct 9th but otherwise med-low priority_____

**Comment by Jegelewicz** [comment]
This needs a larger discussion about red boxes.  We have one on pretty much every page and I'm not sure that they are super-effective. 

But for this, I agree that the blue text is difficult to read and makes it more likely that it will be ignored.

**Comment by dustymc** [comment]
Agreed. I'll switch the locality forms to the "importantNotification" class and we can discuss how that works in general.

Those things exist for about 2 reasons.

1) Like this one, there's something about the specific content that has consistently caused problems in the past. (Someone's trying to fix ABC:XYZ:123's locality but they don't really understand how things work and have way too much access and suddenly thousands of specimens claim to be from Kenya but map to Oklahoma.) I think these should stay in some form.

2) There's something static that gets consistently mucked up and the box is just inline documentation. These shouldn't really need to exist as we should all know where to find documentation. We could get rid of these, or make them less-red, or whatever.

I think the redstuff does help, at least in some situations, but we also get "I scrolled past the big red thing that says don't do THAT and did THAT and now Arctos is broken..." fairly often.

https://github.com/ArctosDB/arctos/issues/745

**Comment by mkoo** [comment]
OK I can live with the Red box Outline=ImportantNotification; that helps the retina-burn and legibility, and may be more appropriate-- thanks.

I agree that there are other issues on user interface and management-- the red boxes should stay as reminders that button-pressing has consequences!

Closing this issue but not the discussion topic!
