### ISSUE TITLE
WoRMS Taxonomy link

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1713]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
WoRMS has taxonomy that would be useful to invert collections in Arctos. It would help us with the maintenance of invert taxonomy in general and why create our own wheel when a good one is already there for us to use?

**Describe the solution you'd like**
It has been suggested that we add WoRMS taxonomy to Arctos.

**Describe alternatives you've considered**
Regular csv imports of WoRMS taxonomy or direct connection.

**Additional context**

**Priority**
I would like to have this resolved by date: _______

**Comment by Jegelewicz** [comment]
Response from WoRMS on direct connect:

> Dear colleague,
> 
> Thanks a lot for your interest in WoRMS and sorry for the delayed reply.
> 
> For applications such as yours we typically propose to set up a MoU that regulates the data exchange between WoRMS and any users that intend to redistribute WoRMS data within their Software/Apps/Services etc.
> 
> Typically this a is a two-way collaboration with the other party providing marine species data or images collected by their software/users or a percentage of their revenue in exchange for the data provided by WoRMS. This helps to expand WoRMS and make it more complete. From your website it seemed you offer a commercial service and are charging your users for your database services, but I did not have the time to really delve into all details.
> 
> Maybe you can briefly summarize what Arctos is doing, and inform us if a MoU would be of interest for you and what you could offer to WoRMS in exchange.
> 
> Kind regards
> 
> Andreas
> ---------------------------------------------------------------------------------
> Dr. Andreas Kroh
> Head of the NHM Vienna Publishing House
> Annalen des Naturhistorischen Museums in Wien, Serie A, Editor-in-Chief
> Zootaxa, Subject Editor for Echinodermata
> Natural History Museum Vienna
> Geological-Paleontological Dept.
> Burgring 7 – 1010 Vienna – Austria – EU
> Tel: 0043-1-52177-576
> Fax: 0043-1-52177-459
> www.nhm-wien.ac.at/kroh.html
> 
> World Register of Marine Species
> Steering Committee Member & Taxonomic Editor for Echinoidea
> http://www.marinespecies.org/echinoidea/
> 
> OeTyp - Online-Database of palaeontological type specimens in Austrian collections
> http://www.oeaw.ac.at/oetyp/palhome.htm

**Comment by Jegelewicz** [comment]
Comments from AWG members:

@campmlc 

> Sounds like a collobaration would be in order. Dusty, how did you go about working with Berkeley Mapper and Geolocate? Maybe it would be better to integrate directly with them and opt to use their (continually updated) taxonomy, rather than download a static data set, and add our new taxa to their portal in return. I don't want to have to pay them.
> 
> This is the same situation with geological attributes formation, group etc.  Wouldn't it be better to partner than to have to continually import data from others?

@dustymc 

> >Berkeley Mapper and Geolocate [and GloblNames, Google Maps, GenBank, EOL, WikiData, etc., etc., etc.]
> 
> Us: Oo, nice.
> Them: Thx, here's the API.
> 
> >integrate directly with them a
> 
> That's always my preference, and the taxonomy model has been aimed at that idea for a very long time.
> 
> "Directly" seems like unnecessary work, for the same reasons we don't provide specimen data in dozens of formats to the dozens of portals - DWC provides a consistent exchange format and IPT provides a consistent exchange mechanism. GlobalNames has done about the same thing for taxonomy. Still probably possible with some development (and maintenance) if they have a usable API and absolutely can't/wont go through GN for some reason.
> 
> I think the problem here is that they don't have the taxonomy potential users need, and they don't feed to GN very often (although maybe that's been fixed recently?). I'm certainly willing to discuss collaborating with them in any way.
> 
> >geological attributes
> 
> There's a very different model on our end, so that would take some discussion and development. Certainly possible, might even be trivial, but it's not all been built with the idea of just plugging in to an external service.

**Comment by Jegelewicz** [comment]
Who should lead the process of negotiating with them?

**Comment by Jegelewicz** [comment]
Also see #1686

**Comment by dustymc** [comment]
any news on this?

**Comment by Jegelewicz** [comment]
> Who should lead the process of negotiating with them?

**Comment by campmlc** [comment]
A question related to our steering committee meeting this afternoon.

**Comment by Jegelewicz** [comment]
Added to Steering Committee Agenda

**Comment by sharpphyl** [comment]
WoRMS may refer us to MolluscaBase to help with mollusca fossil taxonomy - see http://molluscabase.org/ - which is trying to do all mollusca including fossil taxa and has many of the same editors.  I don't know if WoRMS is working with anyone else on other fossil phyla.

![screen shot 2018-10-25 at 7 30 26 am](https://user-images.githubusercontent.com/15368365/47503677-edd0ac00-d827-11e8-9305-3e346ac76a8e.png)

**Comment by Jegelewicz** [comment]
2018-10-24 Response to WoRMS

> Andreas,
> 
> Hello! Dusty McDonald forwarded your email to me so that I can clarify our status as an entity and perhaps move the conversation about a potential collaboration forward.
> 
> Arctos is not a commercial entity. We are a group of natural and cultural history collections jointly developing and using a collection management solution. The financial contributions of the members are used only for the purpose of paying a contract programmer (Dusty) as our system is under continued development. Everyone who represents Arctos does so on volunteer time, including myself. We are familiar with the use of an MoU and would be open to creating such a document to clarify the terms of any agreement we might reach to collaborate.
> 
> Arctos has been developed with a mission of linking and sharing data. Taxonomy and classifications are shared by all collections in the Arctos community. We have several invertebrate collections that rely on WoRMS taxonomy when creating classification information in Arctos. Rather than creating a duplicate set of taxonomy/classifications in Arctos, it would be wonderful if we could simply link to WoRMS because as your website says, "if something good already exists, the effort should not be duplicated". This would save a lot of duplication of effort and allow us to benefit from your managed taxonomy. We could download the information periodically and ingest it, but we are interested in a real-time sharing application that would allow Arctos to use the most current version of WoRMS taxonomy as our invertebrate taxonomic backbone.
> 
> As to what we could offer you in return, the one thing we do not have to offer is financial support. We are building our membership, but are still quite small (about 30 institutions) and the funds we currently raise do not pay for a full time programmer much less anything else. We do have invertebrate data that could be shared including type specimen data, extinct invertebrate taxa, photographs, publications, GenBank records, and hosts where parasites are concerned that would add to the diversity of information in WoRMS. Collaboration could be mutually beneficial as we could share the effort going into the creation and improvement of classifications and taxonomic updates.
> 
> It might be best if we could set up a call to talk about a potential collaboration. Please let me know if this is something that would interest you and we can set a time and date to talk.  We would like to let you hear from some of the WoRMS users in the Arctos community and provide a demonstration of how they use WoRMS now and how we envision working with WoRMS and its contributing databases in the future.
> 
> I look forward to speaking with you.
> 
> Adios,
> 
> Teresa J. Mayfield-Meyer
> Arctos Treasurer

**Comment by Jegelewicz** [comment]
Second attempt at contact 2018-11-11

> Andreas,
> 
> I am making a second attempt to contact you regarding a potential collaboration between Arctos and WoRMS. We are very interested in creating linked data and the WoRMS taxonomy (along with your working partners) would help Arctos toward one of its ultimate goals, which is not managing our own taxonomic classifications but rather relying upon experts to do that for us. Please let me know if you would be interested in speaking with us and if you have a preferred day and time send that as well.
> 
> I look forward to speaking with you!
> 
> Teresa J. Mayfield-Meyer
> Arctos Treasurer

**Comment by Jegelewicz** [comment]
> Dusty,
> 
> I haven't received a reply to this email after two attempts and I am wondering if it has been lost in SPAM. Because you successfully corresponded with WoRMS, perhaps if you forward the message it will get a response. Please copy me when you forward.
> 
> Thanks!

Teresa

**Comment by Jegelewicz** [comment]
> Dear WoRMS,
> 
> We have not received a reply to this message, and are wondering if perhaps it had ended up in your spam folder?
> 

Thx-D

> Hi, it did, apparently. Good that you resent it.
> Am traveling right now and replying from my phone, but am bach in the office on monday
> Cheers Andreas

---------------------------------------------------------------------------------
Dr. Andreas Kroh
Annalen des Naturhistorischen Museums in Wien, Serie A, Editor-in-Chief
Natural History Museum Vienna
Geological-Paleontological Dept.
Burgring 7 – 1010 Vienna – Austria – EU
Tel: 0043-1-52177-576
Fax: 0043-1-52177-459
www.nhm-wien.ac.at/kroh.html

**Comment by Jegelewicz** [comment]
> Dear Dusty,
> Dear Teresa,
> 
> We briefly discussed you request via email. One thing that is not clear yet is if your usage would include some sort of redistribution of the data. And if so in what way.
> We can clarify this in a Skype call on Monday. I am available before 10 am CET or after 2 pm CET (maybe better for you).
> My skype name is kroh.andreas but i am not online usually, so it would be good to set an appointment

All the best Andreas

**Comment by Jegelewicz** [comment]
> Andreas,
> 
> 2PM CET is 6AM my time and 5AM Dusty's time. If you have to be done by 2PM your time, that probably will not work for us. I am available any day next week if you can meet us later during the afternoon your time. I cannot speak for Dusty, but he is generally pretty flexible so if you can offer us a time that is after 7AM his time (4PM for you) that would be very helpful.
> 
> We do not intend to use the information for any commercial means. It would be used by our participating collections to improve our shared taxonomic information. Currently a volunteer is spending a great deal of time manually copying information from WoRMS into Arctos classification tables, potentially introducing errors and omissions. This "copy" of WoRMS information is also susceptible to becoming stale as experts update WoRMS but we have no simple way of knowing what has changed and what has not. Arctos participants are managing biological collections but often have no taxonomic expertise in house to keep up with changes in taxonomy. Our time would be better spent getting our data into digital formats to facilitate its sharing and use rather than re-creating a resource that is already available.
> 
> We would be very happy to provide attribution for the information you would serve us and we would also be happy to work with WoRMS in any way possible to improve the taxonomic resource you are providing, but we have to be honest that the majority of us are under-resourced and may not have any taxonomic expertise to contribute. We do have rich stores of data, primary source information, and specimens and the potential for collaboration in seeking funds through grants.
> 
> We are looking forward to discussing the opportunities with you!
> 
> Adios,

Teresa J. Mayfield-Meyer
Arctos Treasurer

**Comment by dustymc** [comment]
I now have a download which we can minimally use to create names that are in WoRMS and not Arctos.

There's a new link in edit taxonomy that pulls from worms and translates to Arctos terminology, and it's written in such a way that it can be used for things like automation. 

PLEASE test this out, and let me know how it could be better ASAP. I may just use it to get WoRMS classification data instead of trying to unroll their DWCa.

I'm pretty much not going to automagically over-write "Arctos" classification data, and I'm not thrilled with the idea of checking ~2.5 million records in WoRMS knowing that most of them won't resolve.

We can't just use WoRMS - they have gaps in coverage, and users want to have data in FLAT (for labels, to support the "family" specimen search term, etc.).

Lacking better ideas, here's a proposal.

1) Import the WoRMS download as a new classification
1) Add automation using the new tool to keep that classification current(ish) with WoRMS. Collections using this classification would need to be aware that anything that can be over-written from WoRMS will be overwritten from WORMS, that WoRMS is incomplete so some things will need manually added (and then might be overwritten when WoRMS gets new data), etc.
1) Switch any collections that are willing to the new WoRMS-based classification
1) Try to somehow address gaps. I can definitely find names used by collections which aren't in a classification, I can probably copy something (eg, Arctos classification) over to them, but I might make messes. Our classification data is a mess, if the collection is using _Some species_ (not in WoRMS) I'm somewhat likely to miss _Some otherspecies_ and include _Some homonym_. The manual tools (copy classification, hierarchical editor, bulkloader) all still work, so there are ways to address anything I might miss.

An alternative would be to do only the first two steps above, which would make the full WoRMS data available for searching, to clone into other classifications, etc. without changing anything regarding how collections manage their data. Given the new tool this sort of seems like a lot of work for not much benefit, but ??

Better ideas?

Anyone willing to play? @sharpphyl @campmlc

**Comment by Jegelewicz** [comment]
Could we play with a collection in test? I would be willing to mess around with a collection's data in test using 3. If we can figure out a way to use WoRMS, but also allow some way to fill in stuff not included in WoRMS, that would be taking it to the next level.

In the mean time, I cloned in the WoRMS (via Arctos) classification for [Acanthocepola](http://arctos.database.museum/name/Acanthocepola) and the url and citation don't come over, can we make that happen? (Maybe we need two new terms "source url" and "citation")

The source authority could be filled in with "WoRMS".

The WoRMS classification for [Acanthocepola](http://www.marinespecies.org/aphia.php?p=taxdetails&id=206264) lists two names in the field "Superclass", Pisces and Gnathostomata, both of which are "accepted" although Pisces with the caveat "Fish are a now paraphyletic group. So Pisces will no longer be part of the formal classification."

I suppose I can leave both in "Superclass" to increase discovery (which seems to be the tack WoRMS is taking?), but what would that do to other stuff in Arctos? If I create the appropriate relationships between Pisces and Gnathostomata and delete Pisces from the Acanthocepola calssification would that accomplish the same end?

I have left the Acanthocepola classification just as it imported from WoRMS (via Arctos) except I added the nomenclatural code. Also note, that I would need to delete the previous classification (which I haven't done just to be safe for now....)

The cloning tool is a big improvement, but the local classification still means a lot of work re-creating relationships (and maintaining them as WoRMS changes....

**Comment by Jegelewicz** [comment]
Can we pull over the relationships? "Synonymised Names" in WoRMS-speak?

**Comment by dustymc** [comment]
>test

I don't think we want to hammer their webservice (or our little test box!) for test data. We could do something in prod and then replace test with a prod backup, but that takes some time and scheduling. I don't think switching classifications is dangerous - just switch back if you don't like it. What are you wanting to test? Maybe I can find a way to help visualize something.

>Maybe we need two new terms "source url" and "citation"

If you want something from WoRMS we need a place for it in http://arctos.database.museum/info/ctDocumentation.cfm?table=CTTAXON_TERM (and we should discuss format and such, so Issue please).

>Acanthocepola

The data I'm pulling in to Arctos come from two places:

http://www.marinespecies.org/rest/AphiaRecordsByName/Acanthocepola?like=false&marine_only=false&offset=1

http://www.marinespecies.org/rest/AphiaClassificationByAphiaID/206264

A relationship between high-level taxa doesn't propagate down. It could in a hierarchical model, but those things won't both FIT in a hierarchical model.... I don't really have a solution - this seems like a clear case of "taxonomy is broken." If you're using the WoRMS classification it shouldn't matter - we can just do whatever they've done.

>classification still means a lot of work re-creating relationships

I'm not following - this is (part of) why relationships are hooked to names, even though that's just wrong. And I can pull more from WoRMS - if you can see it from http://www.marinespecies.org/aphia.php?p=taxdetails&id=206264 I think I can get it. ("Then what?" is probably the next question....)

**Comment by dustymc** [comment]
>Or maybe we need TAXON_TERM "AphiaID"?

Yes, let's do that. There are a ton of duplicates in their download - I think that's their way of handling synonyms. When I pass in a string I think I get something fairly arbitrary back, and I have to pass in a string to get the AphiaID before I can get the classification. When I pass in the AphiaID I get a specific classification back. Storing the ID will save a call and let users decide exactly what data to associate with a name.

Objections?

**Comment by sharpphyl** [comment]
I found the WoRMS definitions for their taxon terms and prepared the attached chart comparing WoRMS terms with Arctos terms.  It's fine to map "accepted" to "valid" and "unaccepted" to "invalid" if you want, or we could add the WoRMS terms to the taxon table with the definitions WoRMS uses and indicate that they are used only in the WoRMS (via Arctos) source (my preference).  Nomen dubium and nomen nudum are the only ones with an identical match.  Committee member comments??


[Taxon Status Table Suggestions.xlsx](https://github.com/ArctosDB/arctos/files/2658455/Taxon.Status.Table.Suggestions.xlsx)

**Comment by campmlc** [comment]
I support Phyllis's suggestion to add all of WoRMS terms and definitions to
our table (with "source =WoRMS " in definition), and to combine valid and
accepted and invalid and unnaccepted as has been previously proposed
"valid/accepted" and "invalid/unaccepted".

**Comment by dustymc** [comment]
>add the WoRMS terms

I think we should have one way of saying "someone likes this." 

https://github.com/ArctosDB/arctos/issues/1700

Alternate approaches need to address how some collections will be directed to one synonym and others to another.

>indicate that they are used only in the WoRMS (via Arctos) source

We don't currently have the capacity to limit terms to sources, and users should not have to guess at our administrative decisions to find things. I don't think users will be consistent without enforcement. I think this is an inevitable form of denormalization - two ways of providing identical information, used interchangeably, leading to results which cannot be trusted.

My current translations are https://github.com/ArctosDB/arctos/blob/v7.11.0.1/component/taxonomy.cfc. More or less....

authority==>author_text
isExtinct==>taxon_status extinct/extant
accepted==>valid
unaccepted==>invalid
other stuff==>ignore
unacceptreason==>remark
valid_name==>ignore pending relationship stability
valid_authority==>ditto
wild guesses==>nomenclatural_code
classification ranks==>ignore if not LOWER() in http://arctos.database.museum/info/ctDocumentation.cfm?table=CTTAXON_TERM

https://github.com/ArctosDB/arctos/issues/1841

**Comment by sharpphyl** [comment]
I probably don't understand all your code above, but since we already have nomen dubium and nomen nudum in our table, shouldn't we map those to WoRMs use of the identical term?

**Comment by dustymc** [comment]
>nomen dubium and nomen nudum 

It'll now take anything that's in http://arctos.database.museum/info/ctDocumentation.cfm?table=CTTAXON_STATUS (after translating accepted & unaccepted)

**Comment by Jegelewicz** [comment]
authority==>author_text

> isExtinct==>taxon_status extinct/extant
> accepted==>valid
> unaccepted==>invalid
> other stuff==>ignore
> unacceptreason==>remark
> valid_name==>ignore pending relationship stability
> valid_authority==>ditto
> wild guesses==>nomenclatural_code
> classification ranks==>ignore if not LOWER() in http://arctos.database.museum/info/ctDocumentation.cfm?table=CTTAXON_TERM

These seem like fine translations to me.  I would still like to combine valid and accepted and invalid and unnaccepted: "valid/accepted" and "invalid/unaccepted".  I think this would stop future requests to add accepted and unaccepted...

As for relationships, I'll repeat my question here. Can they be part of the Non-Classification Terms? Could Common names be there as well?

**Comment by campmlc** [comment]
The Taxonomy Committee supports this:

 I would still like to combine valid and accepted and invalid and
unnaccepted: "valid/accepted" and "invalid/unaccepted". I think this would
stop future requests to add accepted and unaccepted...
