### ISSUE TITLE
Media Uploader Stalling

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#1717]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
When I drag an image into the Add Media box ("Option 1: Upload Media") in a specimen record, it fails to auto-create a URL (seems to load the image but does not progress to next step where I would fill in the image metadata and add the images to the record)

**To Reproduce**
Record UCM:Obs:AC-280

**Screenshots**
![image](https://user-images.githubusercontent.com/11336485/46419992-4959bf00-c6ec-11e8-8ff2-a57804751e12.png)

**Desktop (please complete the following information):**
 tried both Firefox and Chrome

**Priority**
I would like to have this resolved by date: Nov 1, 2018

**Comment by ebraker** [comment]
Hmmm. Here is the info from the console:

Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.  (unknown)
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified  (unknown)
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified  (unknown)
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified  (unknown)
Content Security Policy: Couldn’t parse invalid host 'report-sample'  (unknown)
Empty string passed to getElementById(). upLinkMedia.cfm
Empty string passed to getElementById(). upLinkMedia.cfm
An error occurred executing the cmd_copy command: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIController.doCommand]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://global/content/globalOverlay.js :: goDoCommand :: line 84"  data: no]  globalOverlay.js:86
Empty string passed to getElementById(). upLinkMedia.cfm
Empty string passed to getElementById(). upLinkMedia.cfm
Empty string passed to getElementById(). upLinkMedia.cfm
Error: Could not establish connection. Receiving end does not exist.  h0-main.js:1:763

**Comment by dustymc** [comment]
Is this still a problem?

**Comment by AJLinn** [comment]
I've been uploading media from the object detail page all week and haven't had any troubles. Maybe a bit on the slow side, but all images have been uploaded fine.

**Comment by Jegelewicz** [comment]
I uploaded one image today and it was a little slow, but it worked.

**Comment by ebraker** [comment]
Yes, still buggy. I have tried to upload media for 7 records this morning. Two worked successfully after ~4 minutes. My other 5 are still stalled after ~20 minutes.

**Comment by dustymc** [comment]
https://web.corral.tacc.utexas.edu/arctos-s3/ebraker/2018-11-06/

It's not terribly surprising if 6M files are timing something out - I tried to reload one and it timed out for me as well. I'll see if I can figure out how to extend the timeout. In the meantime, you might try the ZIP loader or SCP.

**Comment by ebraker** [comment]
Ok. Thanks. Even the <3M are timing out as well. I can try the ZIP loader.

**Comment by dustymc** [comment]
Tagging this as infrastructure limited, although I suspect the limitations are between users and TACC. It's not clear to me what we can do from here, other than recommend SCP for "large" files (where "large" is likely highly variable and dependent on user environment).

**Comment by acdoll** [comment]
@dustymc , I'm having the same issue. I drag and drop, the status bar quickly fills to the right, I briefly see a checkmark, and then it just sits there. It's a small file (636KB), so it doesn't seem like a timeout issue. I know I've had this problem in the past (pre-PG). Is this the console info you want to see?:
![image](https://user-images.githubusercontent.com/12507297/89448911-8ababb80-d715-11ea-93cb-87c31293118f.png)

**Comment by dustymc** [comment]
It works for me, even in Chrome, but at test.

Yes that's the console but your image is pretty fuzzy.

Did your initial filename have a comma? Seems to be a chrome bug with similar behavior around that.

I think there's some potential for this to be related to https://github.com/ArctosDB/arctos/issues/2889 but I can't confirm.

Can you find your file on https://web.corral.tacc.utexas.edu/arctos-s3/?

If you want to send the file and enough info for me to recreate I can try to do so.

**Comment by acdoll** [comment]
Sorry I tried to copy and paste the console, but it wasn't catching everything. 

DMNS:Mamm:19749:1 Failed to load resource: the server responded with a status of 404 (Not Found)
ajax.js?v=10.3266:71 Uncaught DOMException: Blocked a frame with origin "https://arctos.database.museum" from accessing a cross-origin frame.
    at HTMLDocument.<anonymous> (https://arctos.database.museum/includes/ajax.js?v=10.3266:71:24)
    at k (https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js:2:16920)
    at Object.fireWith [as resolveWith] (https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js:2:17707)
    at Function.ready (https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js:2:12438)
    at HTMLDocument.D (https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js:2:9843)
upLinkMedia.cfm?ktype=collection_object_id&kval=28541664:1 [DOM] Found 2 elements with non-unique id #ktype: (More info: https://goo.gl/9p2vKq) <input type=​"hidden" id=​"ktype" name=​"ktype" value=​"collection_object_id">​ <input type=​"hidden" id=​"ktype" name=​"ktype" value=​"collection_object_id">​
upLinkMedia.cfm?ktype=collection_object_id&kval=28541664:1 [DOM] Found 2 elements with non-unique id #kval: (More info: https://goo.gl/9p2vKq) <input type=​"hidden" id=​"kval" name=​"kval" value=​"28541664">​ <input type=​"hidden" id=​"kval" name=​"kval" value=​"28541664">​
upLinkMedia.cfm?ktype=collection_object_id&kval=28541664:1 [DOM] Found 2 elements with non-unique id #picklink: (More info: https://goo.gl/9p2vKq) <form id=​"picklink" method=​"post" action=​"upLinkMedia.cfm">​…​</form>​ <form id=​"picklink" method=​"post" action=​"upLinkMedia.cfm">​…​</form>​
DMNS:Mamm:19749:1 Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by acdoll** [comment]
It is in that TACC directory: https://web.corral.tacc.utexas.edu/arctos-s3/acdoll/2020-08-05/ZM_19749_Mormoops_megalophylla.jpg 
but I can't find it through Arctos media search. 

[ZM.19749_Mormoops megalophylla.zip](https://github.com/ArctosDB/arctos/files/5030737/ZM.19749_Mormoops.megalophylla.zip)
Trying to attach to: https://arctos.database.museum/guid/DMNS:Mamm:19749

**Comment by dustymc** [comment]
I was able to attach that - the Media probably needs edited.

Do you have any extensions installed, and what's in the sources tab of your console? This is something like an issue Carla was having, where some extension was doing crazy things.

**Comment by acdoll** [comment]
Not much for extensions - maybe the Norton Security Toolbar? The only others are: Google Docs Offline, Docs, Sheets, Slides, and Gliffy Diagrams. 

In sources:
arctos.database.museum
Norton Security Toolbar
code.jquery.com
fonts.googleapis.com
fonts.gstatic.com
maps.googleapis.com
maps.gstatic.com
www.google-analytics.com
about:blank
dialog (upLinkMedia.cfm)
placeholder.html
