### ISSUE TITLE
Search for non-printing characters

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1720]
Is there an easy way to search for non-printing characters like the &ntilde; in [this specimen's](http://arctos.database.museum/guid/UTEP:Herp:19697) locality information?

I want to fix a bunch of these, but I need to review them to see which unicode character they need.

**Comment by dustymc** [comment]
That's just a character, you can search for it like any other character, eg http://arctos.database.museum/SpecimenResults.cfm?verbatim_locality=%EF%BF%BD

If there's something consistent I can help update them. I don't really see that here - Do�a and TR�s are probably different intended characters.

**Comment by dustymc** [comment]
I think this is done, tentatively closing.
