### ISSUE TITLE
Unable to Delete Taxon

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#1724]
**Describe the bug**
 I get this error message when I try to delete Cepolis cesticulus.  

![screen shot 2018-10-06 at 8 03 50 am](https://user-images.githubusercontent.com/15368365/46572348-8b2f7300-c941-11e8-8e88-05c68ec66001.png)

**To Reproduce**
 I have checked for other collections using this taxon by checking Arctos when I'm not logged in and also following the link to see if we have any of this species.

![screen shot 2018-10-06 at 7 53 47 am](https://user-images.githubusercontent.com/15368365/46572363-bd40d500-c941-11e8-824a-c4cc048fcde6.png)

![screen shot 2018-10-06 at 7 54 20 am](https://user-images.githubusercontent.com/15368365/46572364-c16cf280-c941-11e8-94f8-21c321e6093e.png)

There is NO Arctos classification for this taxon which I think would be necessary for someone to use it unless they are using a different source.  Also, it means there's no classification to delete.

![screen shot 2018-10-06 at 7 54 50 am](https://user-images.githubusercontent.com/15368365/46572372-de092a80-c941-11e8-8794-0f9ebe903578.png)

What is the best way to check to see if any collection is using a taxon before deleting it?  A search for this taxon online shows that it should be Hemitrochus cesticulus.  The majority of the links on the first search screen are to the Arctos taxonomy which frequently occurs when we have an invalid taxon in our tables.

**Desktop (please complete the following information):**
I'm on my Mac at home on Chrome.

**Priority**
Not urgent but I'd like to understand the delete process better. I don't find anything in the Handbook.

**Comment by dustymc** [comment]
PLEASE include links - without them I'm typing and guessing (and dups tend to be minor misspellings).

There are situations where you can't see how a taxon is used - it's encumbered, maybe. The referential integrity rules protect used names whether you can see them or not.

For this one, assuming I'm not lost, 

<img width="185" alt="screen shot 2018-10-06 at 7 43 55 am" src="https://user-images.githubusercontent.com/5720791/46572509-db0b3b80-c93b-11e8-8fef-75a7dca961f7.png">

leads to http://arctos.database.museum/guid/DMNS:Inv:15504

>Arctos classification for this taxon which I think would be necessary for someone to use 

Not at all - names without metadata work just fine (and usually pick up some metadata from GN anyway).

>don't find anything in the Handbook

Feel free to write some docs or file a request at https://github.com/ArctosDB/documentation-wiki/issues. I'm happy to help however I can.

**Comment by sharpphyl** [comment]
Aha!  Choosing "include unaccepted ID's" pulled up the problem.  Thanks for the hint.

I'll try to write up some docs.  I looked at editing on the GitHub wiki and am unfamiliar with the markup language used.  Would a training session on that be worthwhile?  Or should we just send edits to you as it would be best for someone at Arctos to review any suggested changes.

**Comment by sharpphyl** [comment]
Back to the first problem.  Now when I try to delete Cepolis cesticulus (http://arctos.database.museum/taxonomy.cfm?taxon_name=Cepolis+cesticulus&taxon_term=&term_type=&source=&common_name=), I'm told there is a child taxon.  

![screen shot 2018-10-06 at 9 28 41 am](https://user-images.githubusercontent.com/15368365/46572870-452add00-c94a-11e8-8cd8-615bf15660af.png)

And when I try to delete Cepolis morbida (http://arctos.database.museum/name/Cepolis%20morbida), I get the same message.  But when I search taxonomy for all Cepolis, no subspecies show up.  Same in the hierarchical tool.  Where are the children hiding?


![screen shot 2018-10-06 at 9 31 44 am](https://user-images.githubusercontent.com/15368365/46572892-af438200-c94a-11e8-840d-5e1373deffc5.png)

There's no Arctos classification for either one and I'm reluctant to create an invalid taxonomic record for them just to clean up the Cepolis.  I'd prefer to delete them and add the correct, accepted name when we need it.  They were created in Sept (hopefully, I didn't do it) but in the hierarchical tool it says that neither one has a record attached to it.

**Comment by sharpphyl** [comment]
And, yes, it would be great to cover editing the Handbook in GitHub in a webinar.  Most of it looks easy but I wanted to link to an Arctos table and that required a bit more code that I wasn't familiar with.

**Comment by sharpphyl** [comment]
It happened again this morning so maybe it's a bug.

When I upload all Mollusca to the hierarchical tool, I'm told that a "missed taxon name" is Aegista theobaldiana.  Sure enough, the Arctos record (http://arctos.database.museum/name/Aegista%20theobaldiana)
doesn't include the species and it's considered probably invalid.  

So I clean up the record (add ICZN, pull the species into the correct order, etc.)  It looks like no one is using it and it's not valid, so I tried to delete it and again am told that there is a child taxon.  But when I search for all Aegista, I don't see any subspecies.

**Comment by dustymc** [comment]
yea, it's a bug - I'll get it in the next release

**Comment by Jegelewicz** [comment]
>  I looked at editing on the GitHub wiki and am unfamiliar with the markup language used. Would a training session on that be worthwhile? Or should we just send edits to you as it would be best for someone at Arctos to review any suggested changes.

Feel free to send me the text and I will add it to the Handbook!

**Comment by dustymc** [comment]
fixed for next release
