### ISSUE TITLE
Customized Form: Entered By and list of Last Edited By

### ISSUE THREAD

**Issue by dperriguey** [ArctosDB/arctos#1726]
Can we have "Entered By" and possibly a list of "Last Edited By" added to the Customize Form in the first drop down of the Specimen Results page? 

I would like to have this data downloadable from our end as Arctos data entry users. This data is useful for a number of reasons. It's useful to know who entered or made changes to data/who to ask questions about strange records, data entered by a student can be regarded as higher priority records for future review, and it is similar to having paper records for legacy data and keeping up with that legacy is just a part of standard record keeping. 

This data is already searchable from the search page.

I personally want this data downloadable for backing up our data from Arctos. 

It would be nice to get this issue attention sooner than later, but it's not highest priority.

**Comment by dustymc** [comment]
Seems to have been done at some point

**Comment by dperriguey** [comment]
Great! Thanks!
