### ISSUE TITLE
encumbered specimens behavior

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1727]
Currently Encumbered specimens do not exist in any capacity for public users. Those records do not appear in any way, shape, or form in any structure which any public user has any access to, and public accounts all exclusively use public users.

https://github.com/ArctosDB/arctos/issues/1725 suggests that we should do something else - maybe inform users that we do in fact have the specimens, but that they aren't allowed to see them.

That's doable, but would introduce a fair bit of complexity (we'd have to switch users to check if something exists without creating security holes, or include some data in the public views, or something), and depending on how it's implemented might allow a user to deduce encumbered data.

Note that a 404 is not the only response to a "mask record" encumbrance - eg, https://arctos.database.museum/guid/KNWR:Ento:1888 is encumbered but simply redirects to another record (due to a transfer of custody). Would this proposal change that behavior?

There are essentially two classes of "mask record" encumbrances - those which hide specimens that will eventually be deleted (the encumbrance will never be removed == GUID will never resolve), and those which hide specimens for various administrative reasons (eg, the encumbrance might be removed == the GUID may resolve at some future time). Would this attempt to make some distinction between those? And of course the KNWR example above is something of a hybrid.

What should we do, if anything?

**Comment by AJLinn** [comment]
I don't know about the other circumstances but I think I have either encumbered or considered implementing an encumbrance like this: 

> those which hide specimens for various administrative reasons (eg, the encumbrance might be removed == the GUID may resolve at some future time).

Certain cultural items might be marked by source communities as being improper for outsiders to view, for whatever cultural reasons they have. This includes the information about the objects as well as images/drawings of the items as well. In these cases we would mask the entire record for non-operators, but it's true, it would be nice to have a message that indicated something more like "you don't have permission to view this" rather than "it doesn't exist". Is it possible to make two different kind of "mask record" encumbrances?

> include some data in the public views,

Maybe we could just show the catalog number (GUID) and "IDed as" field? They'd have to get blocked out of the search results view also.

**Comment by dustymc** [comment]
>make two different kind of "mask record" encumbrances?

I think I like that, although I can't really say I'm looking forward to writing the code!

I like how mask record works now from a technical perspective - ya'll are saying "pretend this doesn't exist (except for us)" so we do. I'm hesitant to mess with that, and users don't need to know that the giant mess you just cleaned up is still hanging around behind an encumbrance JUST IN CASE. (Maybe I'm the only one with those...)

Introducing a new "mask everything except {stuff}" encumbrance makes more sense, I think. Users DO need/want to know that a citation (or genbank sequence or link) isn't just orphaned because you've failed to maintain primary identifiers, and you're probably willing to share more information with certain people in certain situations. We'd just put GUID and whatever else ya'll want to share under this encumbrance in FILTERED_FLAT and those specimens would be discoverable by those fields (eg, minimally links would work).

Can we display encumbrance summary data (" Encumbrances: mask coordinates by Katherine L. Anderson on 2018-02-21. Expires 2023-02-21. ") on the public page? That seems fairly critical if we're potentially serving up what's otherwise close to a blank page.

Sorta-related in that this isn't a problem when mask record encumbrances aren't used, I think many (most?) current 'mask record' encumbrances should be 'restrict usage.'

**Comment by campmlc** [comment]
We should consider not displaying encumbrance summary data in so many
words. I think it sends the wrong message to the public and to funding
agencies if we explicitly state that we are hiding locality and collector
data, for example, and when we give the name of the person hiding those
data. I know the bird folks would rather be fairly discrete about what is
available and what is hidden and by whom, and I imagine that relates to
cultural collections as well. That information should be available to
operators, but perhaps for the public we could summarize as "This record
contains non-public data.  Please contact the collection for more
information" or something of the sort.

**Comment by dustymc** [comment]
That suits me, I just think we should say SOMETHING about why we're serving up (mostly) blank pages if this leads to serving up (mostly) blank pages.

FWIW I'm fairly certain the UAM:ES encumbrance that popped up above is required by funding agencies. Other systems do SOMETHING evil, we can store sensitive accurate data without causing any privacy concerns. I would think a "no, we haven't lost the data you paid us to collect, we just don't share it publicly" statement would be welcomed by all funders, but who knows.

**Comment by campmlc** [comment]
Reviving this thread as important for bringing in NMMNHS Paleo. They need to encumber specific locality information and coordinates but would be helpful to have some sort of public data viewable and searchable.
#11

**Comment by dustymc** [comment]
I don't understand how this and NMMNHS are related.

**Comment by campmlc** [comment]
It relates in that they need to encumber parts of records, and we had discussed what wording would be used to indicate that parts of records are encumbered.
I like  AJLInn's suggestion:
It would be nice to have a message that indicated something more like "you don't have permission to view this" rather than "it doesn't exist". Is it possible to make two different kind of "mask record" encumbrances?

**Comment by campmlc** [comment]
We could change the timing on the notifications for encumbrances?  Send emails to agents that have created the encumbrance and also manage collection contact. Include encumbrance type and name, so users/collections can review their encumbrances weekly
Dusty will send out as a distinct email so it can be filtered by those not interested.  
Get TACC advice on security issues.  Problem with use of Postgres vs Oracle.
Let's bring up with TACC.

**Comment by campmlc** [comment]
Possibly include legal counsel in SABI proposal.

**Comment by campmlc** [comment]
see #2268

**Comment by dustymc** [comment]
AWG: keep VPD intact

**Comment by Jegelewicz** [comment]
This is a technical fix IMO. Offering the ability to create a redirect at the time of encumbrance would be extremely helpful. The redirect would be to a single page that says something like.

For further information about this catalog record, please contact the collection.
