### ISSUE TITLE
All permissions for me have been removed

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1728]
I suddenly have no access to anything in Arctos, including addition of roles/permissions.

**Comment by Jegelewicz** [comment]
Actually appears to be limited to geography and roles/permissions

**Comment by Jegelewicz** [comment]
OK, will check with them.

**Comment by Jegelewicz** [comment]
OK, I think they fixed that on their end, but I now am not able to manage classifications and that doesn't seem to be a "role" option.

**Comment by srobson4** [comment]
Sorry

**Comment by Jegelewicz** [comment]
It's OK - We are still friends....
