### ISSUE TITLE
Update Agent Activity report

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#1733]
**Describe the bug**
Agent summary page displays agent activity report as:
"Collected or Prepared Specimens"

Now that we have expanded our CTCOLLECTOR_ROLE, this provides slightly misleading info. It does not include "maker" or "copyright holder".
Perhaps it should read:
"Collected, prepared, made, or holds copyright to:"

or something equally inclusive.

**Priority**
I would like to have this resolved by date: 2018-12-31

**Comment by dustymc** [comment]
Added roles and code table link
