### ISSUE TITLE
New part name: tissue block (paraffin)

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#1734]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Table**
CTSPECIMEN_PART_NAME

**Value**
tissue block (paraffin)

**Definition**
Processed tissue sample embedded in wax matrix which can be sectioned, stained and mounted for histological examination

**Collection type**
Herp

**Part tissue flag**
No

**Context**
We sometimes get tissue blocks back with histology slides - many more thin sections can be made from the block

**Priority**
I would like to have this resolved by date: soonish

**Comment by campmlc** [comment]
Done
