### ISSUE TITLE
Arctos is broken?

### ISSUE THREAD

**Issue by amgunderson** [ArctosDB/arctos#1739]
Every page I attempt to open gives me this error...
![screen shot 2018-10-12 at 9 29 40 am](https://user-images.githubusercontent.com/8440698/46884470-85360800-ce01-11e8-985d-1aaf00860fa9.png)

**Comment by amgunderson** [comment]
Others at UAM are getting the same thing.

**Comment by Jegelewicz** [comment]
Me too

**Comment by amgunderson** [comment]
It's working now, I fixed it ;)

**Comment by dustymc** [comment]
Definitely wasn't @lkvoong 's fault....

**Comment by mkoo** [comment]
definitely not suspicious now...

**Comment by lkvoong** [comment]
Sorry everyone! I gave someone too many roles. 😥
