### ISSUE TITLE
Add DMNS:Egg to ctcoll_other_id_type

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#1740]
I am trying to add relationships between specimens in our Bird and Egg collections, but the DMNS:Egg type is not in the 'ctcoll_other_id_type' code table. Could we get that added please? 
Thanks
Andy

Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Table**
Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm

**Value**
Proposed new value

**Definition**
Clear, complete, non-collection-type-specific definition of the new value.

**Collection type**
If the code table includes a "Collection" column. Ex: Mamm, Herp, ES

**Attribute data type**
free-text, categorical, number+units

**Attribute value**
For categorical attributes, code table controlling value

**Attribute units**
For number+units attributes, code table controlling units

**Part tissue flag**
For new parts, is the part a tissue?

**Other ID BaseURL**
For OtherIDs, URL with which to prepend value (resolvable identifiers only)

**Context**
Describe why this new value is necessary and existing values are not.

**Priority**
I would like to have this resolved by date: _______

**Comment by ccicero** [comment]
Done.
