### ISSUE TITLE
Geolocated coordinates fail to appear on all records

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#1741]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
DMNS:Inv: 426 has been geolocated and the map appears on the specimen record.
____________
![screen shot 2018-10-15 at 8 04 25 am](https://user-images.githubusercontent.com/15368365/46959027-51085480-d058-11e8-9636-1dd2bce66749.png)
____________
But when searching for all records in this accession that have not been geolocated, this record is listed.  Checking the locality for the record shows that no coordinates appear for the locality record 10479082.  Usually the coordinates/depth etc appear with the locality record attached to the specimen record.
_____________
![screen shot 2018-10-15 at 8 04 40 am](https://user-images.githubusercontent.com/15368365/46959254-d8ee5e80-d058-11e8-94fe-3f1011bfa0a4.png)
_____________
But if you go to the locality record you see coordinates - first image is the upper portion of the record followed by the lower portion with the coordinates.

_____________
![screen shot 2018-10-15 at 8 04 54 am](https://user-images.githubusercontent.com/15368365/46959066-6bdac900-d058-11e8-834e-d31cee42125f.png)

![screen shot 2018-10-15 at 8 05 01 am](https://user-images.githubusercontent.com/15368365/46959145-9462c300-d058-11e8-9667-b4af20566403.png)
_____________
The update was done yesterday so it would appear that by now the record should be complete.  Is this a bug or operator error?  This has happened on other locality records as well.

Also if you click on the three specimens that are associated with this locality, only two show coordinates.
_________

![screen shot 2018-10-15 at 9 06 48 am](https://user-images.githubusercontent.com/15368365/46959657-c45e9600-d059-11e8-891d-2688d3c780a6.png)

On an iMac on Chrome - does that make any difference for this issue?

Low priority as long as someone can find all our records.

**Comment by dustymc** [comment]
I updated FLAT. Details about what happened - anything that might have caused the crack this apparently slipped through - are greatly appreciated.

**Comment by sharpphyl** [comment]
I geolocated a lot of localities yesterday and don't remember anything unusual about this one but I'll pay more attention in the future.  I did try to reload the locality to the specimen record a second time but it didn't have any effect.  Thanks for taking care of this.  Shall we close the issue?
