### ISSUE TITLE
Add endoskeleton and byssus to Invertebrate parts

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#1744]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

The "skeleton" of echinoderms and sponges is an endoskeleton.  
https://en.wikipedia.org/wiki/Endoskeleton
While the term "test" is also appropriate for urchins, we need endoskeleton for sponges.

We have a specimen with the associated byssus (https://en.wikipedia.org/wiki/Byssus) and would like to add the part to the record.

**Describe the solution you'd like**
Add "endoskeleton" and "byssus" for Inv.

**Priority**
I would like to have this resolved by date: 31 Oct 2018

**Comment by Jegelewicz** [comment]
Phyllis,

Can you please provide me with definitions of these parts?  Aslso, when requesting additions to a code table, please use the "Authority request" form.

Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Table**
Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm

**Value**
Proposed new value

Thanks!!

**Comment by dustymc** [comment]
These terms will get used in other collections (eg, teach) - the definition should make a clear distinction between "skeleton" and "endoskeleton" if such a thing exists, and should (probably) not be added if there is no such distinction.

**Comment by Jegelewicz** [comment]
I would prefer spicule skeleton over spicule/skeleton. I don;t really want to get in to the skeleton vs. endoskeleton discussion with all the vertebrate collections.....

**Comment by Jegelewicz** [comment]
I would prefer spicule skeleton over spicule/skeleton. I don;t really want to get in to the skeleton vs. endoskeleton discussion with all the vertebrate collections.....

Would both of these be considered tissue?

Should they be added to Inv collections?

**Comment by dustymc** [comment]
In the interest of sorting, "skeleton, spicule"??

**Comment by sharpphyl** [comment]
"skeleton, spicule" would be fine.  

No, there is usually no tissue with the specimen.

Yes, "skeleton, spicule" should be an option for Inv collections.  We are just starting to database our sponges which is what raised the question.  

Thanks.

**Comment by Jegelewicz** [comment]
Done!
