### ISSUE TITLE
Adding Agents to Projects Limitation

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1751]
Is there a reason you can only add three agents to a project at a time? It would be nice if instead of having to save after three there was an "add another agent" button.

**Comment by dustymc** [comment]
Only simplicity - static forms are quick and easy to write, easy to debug/maintain, don't require client-side programming, and work well enough for some things.

If you have a number of agents that would work most of the time (without being too annoying the rest of the time) I can very quickly bump the three up to whatever, if you want dynamic I'll need to refactor the form.
