### ISSUE TITLE
Missing Create Media fxn/ broken link

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#1752]
**Create Media** seems to be hiding or truly deprecated.

Here's what you get when you click on a Create Media link (I am trying to upload a largish WKT from Higher Geog edit page but this link is probably elsewhere)

https://arctos.database.museum/media.cfm?action=newMedia

Error message is: _deprecated - please file an Issue_

Might have been like this awhile but need it now! Thx

**Comment by dustymc** [comment]
I'll fix the link. In the meantime you can search/media and upload.

**Comment by mkoo** [comment]
Yes I see the workaround but not as much fun. I'm following your directions for larger wkt's so let you know if it works!

**Comment by mkoo** [comment]
OK I broke it!
https://arctos.database.museum/Locality.cfm?Action=editGeog&geog_auth_rec_id=10009074
Can you please remove the media link in the wkt? What is the nonfatal format for linking a wkt as media? My wkt as media is https://arctos.database.museum/media/10586706

thanks!

**Comment by dustymc** [comment]
update geog_auth_rec set island='*'||island,WKT_POLYGON=to_clob('MEDIA::10586706') where geog_auth_rec_id=10009074;

**Comment by dustymc** [comment]
good timing; I was working on something that works here too, it'll be in next release.
