### ISSUE TITLE
Identifiers Integer Cuts Off Leading 0

### ISSUE THREAD

**Issue by KyndallH** [ArctosDB/arctos#1756]
**Is your feature request related to a problem? Please describe.**
I need to link specimens to NCBI BioSample. The number is SAMN03223085. However, when I enter it into identifiers integer, it cuts off my leading 0.

**Describe the solution you'd like**
I'd like it not to cut off my leading 0.

**Describe alternatives you've considered**
None.

**Additional context**
<img width="1258" alt="screen shot 2018-10-23 at 3 21 25 pm" src="https://user-images.githubusercontent.com/16887896/47396458-578d7080-d6d7-11e8-98a7-dca999c92c7b.png">

**Priority**
I would like to have this resolved by date: 2018-10-26

**Comment by dustymc** [comment]
Just use prefix for the whole thing - integers are integers, there's no way to "fix" this short of creating a datatype. The integer-bit really only exists for eg, sorting by field number - I don't think it will DO anything with that ID anyway.

**Comment by KyndallH** [comment]
Huh - it actually does create the link when separated out. But I'll go ahead and stuff it all as prefix.

**Comment by KyndallH** [comment]
side question, does NCBI BioSample do a reciprocal link like NCBI GenBank records do?

**Comment by dustymc** [comment]
Yes, but it was broken because the ID name was changed.

I revived it, something should happen after next release.
