### ISSUE TITLE
new identifier type

### ISSUE THREAD

**Issue by mgoliver** [ArctosDB/arctos#1757]
The ALA herbarium has lots of specimens from the now inactive herbarium at the UA Experimental Station in Palmer (AES) and we're ready to start databasing and integrating them into our collection. They already have accession numbers for the AES herbarium so we would like to include this with the specimens when they're databased. Could it be added as another identifier type? Here's a link to the AES herbarium on Index Herbariorum ([http://sweetgum.nybg.org/science/ih/herbarium_details.php?irn=126581](url)).
It would probably be something like — AES: Agricultural and Forestry Experimental Station Herbarium, University of Alaska

We would like to start databasing the specimens ASAP, so if it could be added by this Friday or next Monday that would be ideal. Thank you!

**Comment by campmlc** [comment]
Done.

**Comment by mgoliver** [comment]
Wonderful! Thanks!!
