### ISSUE TITLE
Taxon relationships

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1758]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
When adding relationships between taxa in non-classification data, the definitions of the relationships would be helpful.

**Describe the solution you'd like**
A link to the Taxon_relation code table from the create (or edit) non-classification data page. The current documentation link is not that helpful.  Taxonomy Committee will work to get appropriate definitions for the terms in the code table.

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/5725767/47462987-2fb70f00-d7a2-11e8-9b48-3d4681e2b9bf.png)

Selecting the "Related Taxa hotlink takes you to
![image](https://user-images.githubusercontent.com/5725767/47463028-48272980-d7a2-11e8-882c-be285bfd7d95.png)

Which makes you click [More Information] to then get
![image](https://user-images.githubusercontent.com/5725767/47463074-642acb00-d7a2-11e8-89c0-6106148049a3.png)
 Too much information! We really need definitions of the terms you can choose from to be more visible.

Perhaps along with [More information] there could be a link to [[relationship term definitions](http://arctos.database.museum/info/ctDocumentation.cfm?table=CTTAXON_RELATION)]

**Priority**
I would like to have this resolved by date: _______

**Comment by dustymc** [comment]
Done, but https://github.com/ArctosDB/arctos/issues/1136 

And http://arctos.database.museum/info/ctDocumentation.cfm?table=CTTAXON_RELATION is a little sparse.

**Comment by Jegelewicz** [comment]
We know, but we would like to get this done when that is done. I will press the other to priority in our next meeting. Leaving this open for after that so we don't forget.
