### ISSUE TITLE
Add author to display name (and possibly to name)

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1759]
Reviving this idea from issues such as #1423 and #1700 

Make author part of the scientific name OR the classification. This would clarify differences between hemi-homonyms and should limit the possibility of multiple classifications associated with a given name.

**Comment by Jegelewicz** [comment]
From Taxonomy Committee meeting 2018-10-24

> Worms has identical name that is ambiguous - have to choose which author.
> We need to bring this up to Dusty again.
> For homonyms - we should have the author on the display name.
> Or, have required for all names.
>

**Comment by Jegelewicz** [comment]
But it isn't USED for anything. We envision using that data to distinguish between ambiguous names.

**Comment by dustymc** [comment]
Display name is sprinkled around a bit. I'm happy to sprinkle it more (if I have the processors) - where would you like to see it?

**Comment by Jegelewicz** [comment]
> Display name is sprinkled around a bit. I'm happy to sprinkle it more (if I have the processors) - where would you like to see it?

On the specimen record - apparently it doesn't appear there (have not confirmed this myself...)

**Comment by dustymc** [comment]
It's not terribly prominent, but...

<img width="561" alt="screen shot 2018-10-24 at 7 47 37 pm" src="https://user-images.githubusercontent.com/5720791/47473025-b6311800-d7c5-11e8-912e-38c5e02f1565.png">

**Comment by Jegelewicz** [comment]
OK, that means the one we were looking at with the UNE peeps just didn't have an author assigned. Adding to #1761 for Taxonomy Committee.
