### ISSUE TITLE
Inconsistent data message

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1763]
What does this message mean?

![image](https://user-images.githubusercontent.com/5725767/47518614-b292a500-d848-11e8-960c-eae44f880649.png)

**Comment by dustymc** [comment]
```
UAM@ARCTOS> select * from ctage_class where age_class='larva' order by description;

AGE_CLASS
------------------------------------------------------------------------------------------------------------------------
COLLECTION_CDE
---------------
DESCRIPTION
------------------------------------------------------------------------------------------------------------------------
larva
Herp
A tadpole or juvenile salamander with gills.

larva
Para
Includes metacestode forms of various groups, e.g., plerocercoid, procercoid, cysticercoids, cysticercus, strobilocercus
, polycephalic, coenurus, or tetrathryridia.

larva
Ento


larva
Fish


larva
Host


larva
Inv


larva
Amph



7 rows selected.
```
Provide a consistent definition and I'll SQL it in.

**Comment by Jegelewicz** [comment]
From https://en.oxforddictionaries.com/definition/larva

> The active immature form of an insect, especially one that differs greatly from the adult and forms the stage between egg and pupa, e.g. a caterpillar or grub. OR An immature form of other animals that undergo some metamorphosis, e.g. a tadpole.

**Comment by dustymc** [comment]
Done for consistency, but I'm not sure I like the insect part of that - there are a bunch of other insecty-things, it should be clear where "juvenile" stops and "deutonymph" starts (just pulling random terms, I have no idea if those actually overlap) - I'm not really seeing that in the definition.

https://arctos.database.museum/info/ctDocumentation.cfm?table=CTAGE_CLASS

@DerekSikes ??

**Comment by Jegelewicz** [comment]
A more expert definition would definitely be welcomed!
