### ISSUE TITLE
How to handle historic, not currently valid, taxa

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#1765]
I'm moving an email exchange that started with me reporting a bug when I tried to delete a taxon and morphed into a discussion about legacy/historic and currently not accepted taxonomy.

On Thu, Oct 25, 2018 at 6:28 AM <contact@arctos.database.museum> wrote:
Name: sharpphyl 
Email: sharpphyl@gmail.com 
Message: When will this bug leave us? Trying to delete unused invalid taxa on the list with no kingdom etc. Started with Cypraea spurca acicularis An error occurred while processing this page! Error Executing Database Query. [Macromedia][Oracle JDBC Driver][Oracle]ORA-02292: integrity constraint (UAM.FK_COMMONNAME_TAXONNAME) violated - child record found This message has been logged. Please contact us with any information that might help us to resolve this problem. 
Referring page: /editTaxonomy.cfm
________________
Dusty's response:

That's a constraint, not a bug.

http://handbook.arctosdb.org/documentation/understanding-errors.html#integrity-constraint-schematablecolumn-violated

You're apparently trying to delete a taxon which has common names. They should probably be copied over to the "replacement" name, if there is one, and must be removed before the current name can be deleted.

Why are you trying to delete that name? It easily passes "the google test" and seems to be used by several major collections including MCZ and AMNH.

http://handbook.arctosdb.org/documentation/taxonomy.html

-D
______________

This is probably a good question for the taxonomy committee.  Do we want to spend time cleaning up the higher classification of taxa that are no longer valid and are not being used by any collections in Arctos?  

The taxon I tried to delete, _Cypraea spurca acicularis_, is on our list of taxa without a kingdom.  The Arctos classification (which I deleted in order to delete the taxon then rewrote) didn't have anything higher than family.  Refresh Global Names brings up entries for ITIS and GBIF which classify it as _Erosaria acicularis_.  WoRMS now classifies _Erosaria acicularis_ as _Naria acicularis_.  GBIF taxonomy classifies it as _Naria acicularis_ but shows the historic name as _Cypraea spurca acicularis_ and lists multiple specimen entries from various museums.

Should we spend our time adding (or correcting) the higher classification of unused, invalid taxa that might have historical value to future collections but are of no value to current Arctos users?  Or should we delete these taxa and if they are needed in the future, they can be added at that time with the correct classification and with links to the accepted taxa?  

Another option is to change the Taxon Status to "invalid" or add a new status of "historic" and have Dusty write SLQ that excludes any "invalid" taxa so we don't worry about correcting them (and don't count them as incomplete taxa) but we keep them in the taxonomical table.  That would at least mean that I can spend my hours updating taxa that we are using and that are currently accepted rather than chasing down older, out-of-date taxa.  

Dusty, do you want me to file this as a GitHub question or are you committed to one approach or the other?
______________

Yea, I think Issue. Creating names is a pain, I don't see any reason to delete an unused name if it's "taxonomy." I suppose I feel fairly strongly about that just because of the work I've put into taxonomy, but it's not really a technical issue so I'm happy to discuss.

I care much less about classifications, but it seems to me that something is better than nothing.

There are ~160 specimens in the genus, so it should be no extra work at all to update subgeneric names while updating the stuff that is used.

"invalid" is an option in http://arctos.database.museum/info/ctDocumentation.cfm?table=CTTAXON_STATUS, although I'm not sure that's specific enough to be useful - if we're going towards "accepted (by someone, for some purpose)" perhaps we should do the same thing with unaccepted. (Or maybe "not accepted by someone for some purpose" should be read as unaccepted??)

I added http://handbook.arctosdb.org/documentation/taxonomy.html#deleting

Thx-D
___________________

Mariel Campbell | Mariel Campbell | 3:15 PM (3 hours ago) |   |  
I think it is valuable to have older invalid names in Arctos in order to import legacy specimens and document the original name assigned to them. But this points to our needing a really good way to indicate which names are valid/accepted etc and by whom on what date, as we have previously discussed. 
_________________

**Comment by sharpphyl** [comment]
It's fine to keep "historic but now invalid" taxa in our database though they typically are incomplete and cause problems in the hierarchy tool and end up on "no kingdom" lists.  I have no problem with adding taxon status to these taxa, but if we're all going to take the time to identify "invalid" or "unaccepted" taxa, it needs to be for some purpose.  So far, I feel like I'm just talking to myself as the taxon status and taxon relationships aren't used in any helpful way.

One suggestion made in another issue (sorry I can't find it right now) is that we be able to search for invalid/unaccepted taxa and be able to see the link to the valid/accepted taxa.  That would be very helpful.

For our volunteers, it would be helpful if, when they try to enter an invalid taxon in the data entry screen, a pop-up would flag the name as invalid and require them to consciously overwrite it if they really want to use it.

**Comment by campmlc** [comment]
I agree with these suggestions.

**Comment by dustymc** [comment]
Relationships are used in the taxon pick and in searching. Accessing that functionality elsewhere is fairly trivial. Relationships don't appear capable of getting to "use that one" - there's legitimate disagreement about what to call some common things among Arctos collections, and literature-supported relationships go both ways (maybe a few times over the years). I think taxon_status makes sense to clarify that at the collection level, but we don't have the vocabulary to support that: https://github.com/ArctosDB/arctos/issues/1700 (E.g., both Rana and Lithobates are preferred by different collections.) Taxon status does NOT make sense as a replacement for relationships - the functionality is very different. (Relationships can DO STUFF - taxon_status is just a string/flag.)

* With directional and reciprocal relationships, I might be able to get at preference. With what we have now, all I can get at is "these have something to do with each other." https://github.com/ArctosDB/arctos/issues/1136

* Given vague or conflicting relationships I could fall back to taxon_status, but if I'm going to write code to it we should solidify the terminology first. https://github.com/ArctosDB/arctos/issues/1700 

* Documentation - does the above make sense, and what's missing? (I'm still pretty fuzzy on taxon status - do we really need both "this is good" and "this is bad"? Do we need one of each for every collection?!?)

**Comment by Jegelewicz** [comment]
Closing as covered by #1136 and #1761
