### ISSUE TITLE
can't download ALA labels :(

### ISSUE THREAD

**Issue by mgoliver** [ArctosDB/arctos#1768]
When I try to download ALA labels from the specimen results page I get this error message (first screen shot). I ruined something but don't know how to fix it myself. I promise I will never touch Reports again if someone helps me fix it. It should be Report Template alaLabel.cfr
![screen shot 2018-10-29 at 3 26 55 pm](https://user-images.githubusercontent.com/28404497/47686258-0a097b80-db8f-11e8-93d2-fb056460d60c.png)
![screen shot 2018-10-29 at 3 32 15 pm](https://user-images.githubusercontent.com/28404497/47686397-cbc08c00-db8f-11e8-8b12-2a40214fea57.png)

**Comment by dustymc** [comment]
Looks like the hardcoded shortcut has issues - I'll fix that. You can always...

<img width="333" alt="screen shot 2018-10-29 at 4 44 13 pm" src="https://user-images.githubusercontent.com/5720791/47686748-0c250780-db9a-11e8-9e95-2110c2063a04.png">

<img width="488" alt="screen shot 2018-10-29 at 4 44 33 pm" src="https://user-images.githubusercontent.com/5720791/47686753-10e9bb80-db9a-11e8-9a09-0f33e4255580.png">

but the report looks like it's been deleted and re-created without SQL??

**Comment by dustymc** [comment]
Actually it looks like the shortcut is only broken because the label name has changed from ala_label - change it back and that should work again.

**Comment by mgoliver** [comment]
Thank you, Dusty! That was my fault.

**Comment by mgoliver** [comment]
Ok, I don't think I fixed it. Now this is the error that appears. I'm afraid to mess with it any more.
<img width="1040" alt="screen shot 2018-10-29 at 4 05 35 pm" src="https://user-images.githubusercontent.com/28404497/47687305-818dd980-db94-11e8-8b52-379ccdb37eb6.png">

**Comment by dustymc** [comment]
I've got a not-too-old local copy of the report table so maybe we can avoid asking for a backup or starting from scratch. Does this do what you need?

```
UAM@ARCTOS> select * from BAK_CF_REPORT_SQL_20180828 where report_name like '%ala%';

 REPORT_ID
----------
REPORT_NAME
------------------------------------------------------------------------------------------------------------------
REPORT_TEMPLATE
------------------------------------------------------------------------------------------------------------------
SQL_TEXT
------------------------------------------------------------------------------------------------------------------------
PRE_FUNCTION
------------------------------------------------------------------------------------------------------------------------
REPORT_FORMAT
------------------------------------------------------------------------------------------------------------------------
LAST_ACCES
----------
   4732633
ala_label
alaLabel.cfr
select
case flat.state_prov when 'Yukon Territory' then 'YUKON T.'
else
upper(flat.state_prov) end
 ||
case flat.country when 'United States' then
', USA'
else
', ' || upper(flat.country) end as geog,
flat.FORMATTED_SCIENTIFIC_NAME	sci_name_with_auth,
flat.IDENTIFIEDBY identified_by,
 flat.family,
flat.scientific_name tsname,
flat.author_text auth,
flat.attributes,
trim(ConcatAttributeValue(flat.collection_object_id,'abundance')) abundance,
identification.identification_remarks,
flat.made_date,
flat.cat_num,
flat.state_prov,
flat.country,
flat.quad,
flat.county,
flat.island,
flat.island_group,
flat.sea,
flat.feature,
flat.spec_locality,
flat.verbatim_coordinates Coordinates,
		flat.MAXIMUM_ELEVATION,
		flat.MINIMUM_ELEVATION,
		flat.ORIG_ELEV_UNITS,
		 flat.collectors,
		 flat.OTHERCATALOGNUMBERS,
		concatsingleotherid(flat.collection_object_id,'original identifier') fieldnum,
		concatsingleotherid(flat.collection_object_id,'U. S. National Park Service accession') npsa,
		concatsingleotherid(flat.collection_object_id,'U. S. National Park Service catalog') npsc,
		concatsingleotherid(flat.collection_object_id,'ALAAC') ALAAC,
		flat.verbatim_date,
		flat.habitat,
		flat.associated_species,
		project_name
	FROM
		flat,
		identification,
		project_trans,
		project,
#session.SpecSrchTab#
	WHERE
		flat.accn_id = project_trans.transaction_id (+) AND
		flat.identification_id=identification.identification_id (+) and
		project_trans.project_id = project.project_id (+) AND
		flat.collection_object_id =#session.SpecSrchTab#.collection_object_id
order by concatsingleotherid(flat.collection_object_id,'original identifier')
format_ala
PDF
2018-07-12


1 row selected.
```

**Comment by mgoliver** [comment]
Yeah that looks pretty good to me, from what I can tell.

**Comment by mgoliver** [comment]
Am I supposed to copy and paste that somewhere?

**Comment by mgoliver** [comment]
Dusty, I'm not sure what to do with your last post. It looks like it _should_ supply the information for ALA labels, but I really have no idea because I don't have experience with code. I tried "Editing Handler" for the ALA_label report, pasted the code in, and clicked "Test SQL" and got the message "The SQL you supplied did not properly execute." So I didn't save it. My last day with the ALA herbarium is this Friday and Carolyn Parker has been patiently waiting to print ALA labels for specimens she's entering in — could you please help me out a bit more with this?

**Comment by dustymc** [comment]
I pasted it in and SOMETHING happens now. It needs the pre_function to execute properly.
