### ISSUE TITLE
Swab part name changes

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1771]
AWG - We have several 'swab' parts that are of different types, e.g., buccal, cloacal, etc.

Any objections to changing the part name as follows:

buccal swab (RNAlater) ---> swab, buccal (RNAlater)
buccal and cloacal swab (RNAlater) ---> swab, buccal and cloacal (RNAlater)
dorsum swab ---> swab, dorsal
nasal swab (frozen) ---> swab, nasal (frozen)
oral swab (frozen) ---> swab, oral (frozen)
oral swab (formalin) ---> swab, oral (formalin)

This will make it easier to see all of the swab parts together in the code table.

If no objections, Dusty can you make these changes?

Thanks,
Carla

**Comment by Jegelewicz** [comment]
> Certainly no objections from me. Can you just add the parts whenever you're ready - I'll swap them and delete the unused.

Thx-D

**Comment by Jegelewicz** [comment]
> That makes sense to me.
> 
> cheers,

Beth

**Comment by Jegelewicz** [comment]
> Also for the AWG: is there a difference between 'oral' and 'buccal' swab? Can we combine those?

Carla

**Comment by Jegelewicz** [comment]
> No objections. OK to combine oral and buccal - under "oral". 

Mariel

**Comment by jldunnum** [comment]
No objections


______________________________________________________________

Jonathan L. Dunnum Ph.D.
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by ccicero** [comment]
New part names added - @dustymc needs to change specimens to the new part name and remove old name from code table:

buccal and cloacal swab (RNAlater) ---> swab, oral and cloacal (RNAlater)
dorsum swab ---> swab, dorsal
nasal swab (frozen) ---> swab, nasal ---> change to "swab, nasal (frozen)"
oral swab (frozen) ---> swab, oral (frozen)
oral swab (formalin) ---> swab, oral (formalin)

Also added swab, oral (RNAlater) - no corresponding part in CT to be changed

**Comment by dustymc** [comment]
This failed:

```
UAM@ARCTOS> update specimen_part set part_name='swab, nasal (frozen)' where part_name='nasal swab (frozen)';
update specimen_part set part_name='swab, nasal (frozen)' where part_name='nasal swab (frozen)'
       *
ERROR at line 1:
ORA-20001: Invalid part name: swab, nasal (frozen) (Mamm)
ORA-06512: at "UAM.TRG_CMPD_SPECIMENPART", line 37
ORA-04088: error during execution of trigger 'UAM.TRG_CMPD_SPECIMENPART'
```

The rest are done.

**Comment by dustymc** [comment]
done

**Comment by ccicero** [comment]
Sorry, one more to fix:

cloacal swab (RNAlater) ---> swab, cloacal (RNAlater)

**Comment by dustymc** [comment]
done again
