### ISSUE TITLE
Geography mis-spelling

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#1772]
**Describe the bug**

Quetzaltenango Department in Guatemala is mis-spelled: http://arctos.database.museum/Locality.cfm?Action=editGeog&geog_auth_rec_id=10000636

Also, it would be useful if the geog_auth_rec_id was displayed on the Edit page for easier reference.

**Comment by dustymc** [comment]
Yay for the Big Red Box!

<img width="885" alt="screen shot 2018-10-31 at 10 48 56 am" src="https://user-images.githubusercontent.com/5720791/47808000-af8d2e00-dcfa-11e8-9335-6ff6a1c4ce63.png">

It's gone now.

I can add geog_auth_rec_id easy enough (and it's in the URL), but I generally try to NOT display internal IDs. Those can change at any time, and that tends to lead to confusion. I of course fail miserably at that goal and they're scattered all over the place, so whatever - if it makes something easier at some point....

**Comment by acdoll** [comment]
I did realize it was in the url but imagine not everyone would see that.  However, if they can change, I agree with not displaying them.
