### ISSUE TITLE
Annotation 

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#1773]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Just received email: An Arctos user (dlm - dustymc@gmail.com) has created an Annotation concerning 18 specimen record(s) potentially related to your collection(s).

    Does not map to Santa Barbara County 

View details at http://arctos.database.museum/info/reviewAnnotation.cfm?ANNOTATION_GROUP_ID=3427 

The record in question - http://arctos.database.museum/guid/DMNS:Inv:17354 - is a marine invertebrate, therefore, we placed the coordinates pin in the waters off Chula Vista and therefore, outside the county itself.  

**Expected behavior**

Is there a way to distinguish marine specimens from terrestrial specimens where the coordinates should be within the county boundaries?

**Screenshots**
![snip](https://user-images.githubusercontent.com/15368365/47874780-4da3f580-ddda-11e8-883e-a19f3773cfc3.PNG)

**Desktop (please complete the following information):**
 - OS: Microsoft 7? 6?
 - Browser Firefox

**Additional context**
I appreciate knowing when we have an error in geolocation but want to focus on actual errors.  

**Priority**
I would like to have this resolved by date: before the next email about geolocation errors.

**Comment by dustymc** [comment]
This is more or less a duplicate of https://github.com/ArctosDB/arctos/issues/1107. 

1. Do we want to continue using geography as a reference rather than an enclosing entity? 
2. If we are not going to use geography as a reference point, what should we use? "Pacific Ocean" doesn't seem terribly useful here, but it may be the smallest "correct" value.
2.  If we are going to use geography as a reference point, are there limits to that? (E.g., is "29899 miles east of Santa Barbara County" equally valid?)
2. If we are going to use geography as a reference point, should we somehow flag that use?

**Comment by Jegelewicz** [comment]
At first blush, this specimen seems to have inappropriate Higher Geography as it is not IN the county or even the state. It may be in "United States" if it isn't far enough out to be considered in international waters. If it is in international waters, "Pacific Ocean" seems appropriate for higher geography as Dusty noted. That, with the associated coordinates should make the specimen find-able. Yes, there are limits to using geography as a reference point and if the specific locality were "29899 miles east of Santa Barbara County" that would be more useful than "Oceanside". Does that mean a city in Santa Barbara county? Maybe "29899 miles east of Oceanside, Santa Barbara County" would be even better.

**Comment by sharpphyl** [comment]
In my experience, it's customary to use the nearest geographical landmass as the location of shells that are found anywhere from the high tide line to a few miles offshore by diving or dredging.  Since it's a marine species, I avoid dropping the pin on land so it will always be outside the land mass boundaries.  Often the location is a bay that is probably considered part of the geopolitical area but won't appear within the county boundaries.  See Locality 10479543.  I would not want to use Pacific Ocean as the higher geography for this specimen. 

![screen shot 2018-11-02 at 9 52 37 am](https://user-images.githubusercontent.com/15368365/47926001-1b9b9d80-de85-11e8-94e3-6cfeac92073d.png)


An exception is an island where we drop the pointer on the center of the island and draw the uncertainty circle to include a sufficient amount of water for the depth (if any) though that is always an estimate.  See locality 10895750 


![screen shot 2018-11-02 at 9 55 16 am](https://user-images.githubusercontent.com/15368365/47926147-78975380-de85-11e8-971a-ba37056f0857.png)


If the shell (or other marine invertebrate) is found well into international waters, then the Ocean would be the higher geography.  See, for example, locality 10880275.

![screen shot 2018-11-02 at 9 57 27 am](https://user-images.githubusercontent.com/15368365/47926248-bd22ef00-de85-11e8-8258-0ffc71362406.png)
  

Similarly, if the entire geography is listed in an Ocean (such as Hawaii or New Caledonia), then the Ocean leads the higher geography.  

For many of our specimens, we have nothing more than the name of a town, such as Oceanside, California.  It was probably found beach combing as there is no depth, but we don't have documentation.  I will probably continue to geolocate them just off shore and expect them to generate an annotation.  BTW, the annotation system is very helpful as two of the notices today spotlighted errors in geolocation unrelated to this issue.

Since this issue is similar to #1107, I'll close it so we don't have multiple issues addressing the same question.
