### ISSUE TITLE
Bulkloading Parts Error

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1774]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Was bulkloading parts and got this error
![image](https://user-images.githubusercontent.com/5725767/47882341-cb71fc00-ddee-11e8-9c06-0273cc02e1b5.png)

Decided to try them one at a time and got the identical error.

**To Reproduce**
1. Load the attached file through Enter Data>>Batch Tool>>Bulkload Parts or
2. Go to http://arctos.database.museum/guid/MSB:Bird:45747 and try to add barcode MSB1025174 to heart, liver, muscle (frozen)

**Expected behavior**
Have never had this issue. Just expect parts to load (or not if they are duplicates or otherwise ambiguous)

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 64.1

**Additional context**

**Priority**
I would like to have this resolved by date: 2018-11-05
[BulkPartContainer_DGR16562.zip](https://github.com/ArctosDB/arctos/files/2540273/BulkPartContainer_DGR16562.zip)

**Comment by AJLinn** [comment]
My volunteer was trying to modify parts and got the same error. Seems to have been going on for the past 10 minutes or so. Anyone got any ideas to fix?

**Comment by lkvoong** [comment]
Added additional space to SYSTEM tablespace. Please let me know if you're
still getting this error.

Thanks,

Lam

**Comment by AJLinn** [comment]
All good for our work now. Thanks Lam!
