### ISSUE TITLE
Taxonomy not included on Documentation page in Handbook

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#1778]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

Searching (control F on a Mac) for Taxonomy on the Documentation page returns nothing.

**To Reproduce**

Go to http://handbook.arctosdb.org/documentation/.  Taxonomy is not listed anywhere on this page.  If you search for Taxonomy in the box at the left, the first choice is within the Documentation page:  http://handbook.arctosdb.org/documentation/taxonomy.html

**Expected behavior**

It would be beneficial to have TAXONOMY listed as one of the topics on the Documentation page.

**Screenshots**

![screen shot 2018-11-04 at 3 23 18 pm](https://user-images.githubusercontent.com/15368365/47970644-9d3a2980-e045-11e8-9eab-42356ba060a3.png)

_____________________

![taxonomy in documentation](https://user-images.githubusercontent.com/15368365/47970614-46cceb00-e045-11e8-811d-9b6f83d4e8c5.png)

____________________

**Desktop (please complete the following information):**
 - Mac on Chrome 

**Priority**
I would like to have this resolved by date: low priority but shouldn't be a big fix.

**Comment by Jegelewicz** [comment]
Added.
