### ISSUE TITLE
dwc:dataGeneralizations (and DWC fields in general)

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1779]
https://terms.tdwg.org/wiki/dwc:dataGeneralizations exists.

We "generalize" most everything for most everything we share. Should we put something general in that field, or develop some sort of "things we squish for DWC" document and put the URL in that field, or ??

To finalize this, should we do something, we'll need to coordinate remapping with @dbloom - that is apparently a ridiculous amount of work.

I've copied https://github.com/tdwg/dwc/blob/master/vocabulary/term_versions.csv to https://docs.google.com/spreadsheets/d/1Urs3iE3t2U1v-VR4yuPOHR8-sy3V5iVUW9M1ud9jikU/edit#gid=1128776658 - is there anything else we should be sharing via DWC that could be remapped at the same time?

**Comment by Jegelewicz** [comment]
> We "generalize" most everything for most everything we share. Should we put something general in that field, or develop some sort of "things we squish for DWC" document and put the URL in that field, or ??

I am personally lacking knowledge about what fields in Arctos end up in what dwc fields. I think this would be important information for all of us to know before we can make any contribution to the discussion.

**Comment by dustymc** [comment]
https://github.com/ArctosDB/DDL/blob/master/flat/ipt_view.sql builds the IPT view.

Procedure UPDATE_FLAT in https://github.com/ArctosDB/DDL/blob/master/flat/flat_procedures.sql builds the flat table which IPT mostly pulls from.

Sorry, I'm not sure how to put that in any language other than SQL - it's just complicated. I'm happy to answer any questions.

FWIW, I think the act of flattening, which removes context, is where we lose most information.  Determining if the "John Smith" who determined an attribute is the same "Smith, J." who authored a publication just isn't possible in text-based data but is obvious in Arctos, for example.

**Comment by Jegelewicz** [comment]
OK, this is a start, but I need clarification. When I see:

>     OTHERCATALOGNUMBERS otherCatalogNumbers,
> 	'http://arctos.database.museum/guid/' || GUID individualID,
> 	CATALOGNUMBERTEXT catalogNumber,
> 	GENBANKNUM associatedSequences,
> 	COLLECTORNUMBER recordNumber, -- I think this is a very incomplete mapping
>      FIELD_NUM fieldNumber, -- also incomplete/incorrect

Are the ALL CAPS names the Arctos fields and the lowercase the dwc field names or the other way around or does that not apply at all?

**Comment by dustymc** [comment]
Not a problem under https://github.com/ArctosDB/internal/issues/168
