### ISSUE TITLE
Add pit depth as searchable attribute

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#1780]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Pit depth was added as an attribute for UAM:Arc in data entry. It does not appear, however, in CTATTRIBUTE_CODE_TABLES.
It is on the CTATTRIBUTE_TYPE code table.

**Expected behavior**
Add pit depth to attributes on search page
Add pit depth to customize pop-up to enable sorting
(This is probably accomplished by adding to CTATTRIBUTE_CODE_TABLES)

**Priority**
HIGH!
I would like to have this resolved by date: ASAP (visiting faculty researcher needs this info this week!)

**Comment by dustymc** [comment]
CTATTRIBUTE_CODE_TABLES just controls datatype (and vocabulary for categorical attributes) - there's some sorta-documentation at http://handbook.arctosdb.org/how_to/Understanding-Attribute-Errors.html. Pit depth is a free-text attribute - it contains string-data and could not easily be converted to numeric, so should not have an entry in CTATTRIBUTE_CODE_TABLES.

https://github.com/ArctosDB/arctos/issues/1403 also exists - those data may be scattered around a bit.

I think this got kicked out when https://github.com/ArctosDB/arctos/issues/1730 happened. I'll try to get it patched back in tonight.
