### ISSUE TITLE
Legacy Nalgene container types in positions

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1783]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Legacy "Nalgene" containers that ended up in slide boxes (as slides) or freezer boxes (as cryovials) because of default Nalgene setting in Object+Barcode->Container.

**To Reproduce**
1. Go to Find Container
2. Click on Container Type = Nalgene + In Container Type = position
4. See: "Nalgenes" in places they shouldn't be

Please convert as appropriate: All Nalgenes in slide box positions should be converted to slides; All Nalgenes in freezer box positions should be converted to cryovials.

**Screenshots**

[Find Containers Nalgenes in positions.pdf](https://github.com/ArctosDB/arctos/files/2554577/Find.Containers.Nalgenes.in.positions.pdf)

**Additional context**
This should be fixed for the future because of the reset of Parent Container Type to Null from Nalgene.

**Priority**
I would like to have this resolved by date: __reasonably soon_____

**Comment by campmlc** [comment]
I'm still finding these problems. Nalgenes should not be able to be scanned into slide boxes. Can all items in slide boxes in MSB Para that show up as Nalgenes please be converted to slides. Also, please give me access to these - I get the message I do not have access to the parent container.
Example: P1FKU

**Comment by dustymc** [comment]
>Nalgenes should not be able to be scanned into slide boxes

That's a new Issue - happy to entertain the idea, but I think we've found some sort of fatal flaw in that kind of logic before. Dimensions should do it, but of course doesn't help much if nobody's recorded those data.

I flipped some positions to MSB - you should have access to the stack now.

I converted 37 nalgenes to slides and 16 to cryovials.

**Comment by campmlc** [comment]
Thanks!

**Comment by campmlc** [comment]
I think this problem dates to when Object+Barcode+Container had "Nalgene"
as the default container type. That is fixed now (deault is null), so
hopefully problem be avoided in the future.
