### ISSUE TITLE
taxon id picklist fails to find name

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#1784]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

Using the bulk specimen ID change form. Enter Apidae and hit tab. A window appears as normal which should show me a list of the taxa that match this search term but there is no list. See screenshot. I've confirmed the name exists in taxonomy.

**To Reproduce**

1) search UAMObs:Ento for id= Xylocopa
2) click menu: manage->change stuff->identification
3) enter Apidae in the taxonA field and hit return
4) watch a window pop up that has nothing found

**Expected behavior**

Normal list of matched terms 

**Screenshots**

see screenshot

**Desktop (please complete the following information):**
 - OS: Mac OS 10.13.6
 - Browser Firefox
 - Version 63.0.1

**Additional context**

I use this form more than almost any other. Super high priority!

**Priority**
I would like to have this resolved by date: _6 Nov 2018_____
![screen shot 2018-11-06 at 9 53 04 am nov 6 18](https://user-images.githubusercontent.com/9099827/48086930-7c3f1900-e1aa-11e8-98f8-33d1548ec59d.jpg)

**Comment by dustymc** [comment]
patched
