### ISSUE TITLE
MCN in Denver

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1785]
I think we should have someone go to this conference, even if just to poke around and occasionally speak up. Any Denver people who can go?

http://conference.mcn.edu/2018/about.cfm

**Comment by campmlc** [comment]
There are sessions on DAMS and on Opensource code on Thursday am that could
be valuable. It would also be good to do some networking with people who
specialize in dealing with interactive media and user interfaces at the
public level.

Also this is relevant to Arctos right now:
Unconferencing Org Culture: Let's Teach Each Other about Organization
Design and Change (UNCONFERENCE)

**Comment by jrdemboski** [comment]
yes, several people from DMNS, including those familiar with databases like Arctos and Emu, are going to this conference.  I have talked to them about attending many of the sessions that appear relevant.  Like:

“We’re Open Sourcing It”: Mapping the Creation and Reuse of Open Source Code within the Museum Sector

Real Museum, Real Science: Evolving the Citizen Science User Experience

Collections Management in Context: Museum Perspective

etc.

A lot of the sessions center more around digital interfaces for the public, exhibits, AR, website, etc.

_____________________
John R. Demboski, PhD
Director, Zoology and Health Sciences
Curator of Mammals
Denver Museum of Nature & Science
2001 Colorado Blvd
Denver, CO 80205
E: john.demboski@dmns.org<mailto:john.demboski@dmns.org>
P: 303.370.6443
________________________________
