### ISSUE TITLE
Add Island to Bohol, Samar and other islands

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#1786]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
Our volunteers doing data entry find it confusing when the same name is used for the province and an island within or the same as the province.  Examples:
Asia, Philippines, Samar, Philippine Islands, Samar 
Asia, Philippines, Bohol, Philippine Islands, Bohol
Asia, Philippines, Siquijor, Philippine Islands, Siquijor

**Describe the solution you'd like**
Add Island to the island name whenever it is the same as the province/state.  If I do this, I will impact other museum's records.  What is the procedure to approve of and make such changes?

**Describe alternatives you've considered**
We are very inconsistent in using "Island" as part of the higher geography.  The Handbook Geo_Auth_Rec . Island VARCHAR(50) null seems to say that adding Island is appropriate if it is in the name of the island.  Can this be done by anyone with authority to edit Higher Geography or do all users of that higher geography have to sign on?

**Additional context**

![bohol geography](https://user-images.githubusercontent.com/15368365/48148079-29cb2e80-e276-11e8-85da-faafcd36e53f.JPG)

![bohol impact](https://user-images.githubusercontent.com/15368365/48148086-2e8fe280-e276-11e8-9a04-19e22bac0798.JPG)

**Priority**
I would like to have this resolved by date: Whenever the geography committee meets.

**Comment by dustymc** [comment]
http://handbook.arctosdb.org/documentation/higher-geography.html#island

The key there is the __proper__ name. "Bohol Island" is not a common usage; it's just "Bohol." 

https://en.wikipedia.org/wiki/Bohol

"Bay Farm Island" is correct.

https://en.wikipedia.org/wiki/Bay_Farm_Island,_Alameda,_California

This change would complicate data cleanup by introducing unexpected terms in names. As long as the term is just "island" I can probably deal with that anyway, if I have to.

I think this would be a bit confusing to users as well - nobody expects 'Bohol Island.'

If the issue is in the geography pick, we could probably make that look more like...

<img width="237" alt="screen shot 2018-11-07 at 9 30 07 am" src="https://user-images.githubusercontent.com/5720791/48148939-ca6a2000-e26f-11e8-80f4-2f21eaaba41b.png">

... and less like ...

<img width="211" alt="screen shot 2018-11-07 at 9 30 55 am" src="https://user-images.githubusercontent.com/5720791/48148968-d950d280-e26f-11e8-8e3c-bb3d6163fb55.png">

which, if I'm understanding this correctly, should address the problem without introducing confusing terminology (and ultimately tripping GBIF's flags and etc.).

And the example instructs us to do exactly the opposite of what we've been discussing in https://github.com/ArctosDB/arctos/issues/1107.

>100 yds off of the beach, Bay Farm Island

**Comment by sharpphyl** [comment]
Yes, if you could make the Geography Pick show the levels as displayed above, that would solve the problem we have.

**Comment by sharpphyl** [comment]
Not sure which of the topics listed above needs discussion.  Instead of adding "Island" as originally requested, I like Dusty's suggestion that he makes the Higher Geography Pick screen show the levels of each term.  That would solve the problem without changing any of the terms.  Does that require the approval of a specific group?

**Comment by dustymc** [comment]
I think it's a useful discussion.

* Are we OK with a larger, harder to read pick?
* Are we OK with displaying one thing for data entry and something else for everything else?
* Are we attempting to duct-tape over some problem with the data/structure/guidelines/whatever?

**Comment by Jegelewicz** [comment]
>     Are we OK with a larger, harder to read pick?

I am - who says it is harder to read?

>     Are we OK with displaying one thing for data entry and something else for everything else?

Probably not a good idea and if you think about it, anyone unfamiliar with Arctos will wonder what the heck "Asia, Philippines, Bohol, Philippine Islands, Bohol" is supposed to mean.

>     Are we attempting to duct-tape over some problem with the data/structure/guidelines/whatever?

Possibly. I do feel like features, islands, and continent/ocean create inconsistencies and perhaps confusing information.

**Comment by dustymc** [comment]
>who says it is harder to read

Me! But I'd seldom use the pick so whatever. 

Also of concern: The bulkloader does (and I think always will) work with the (or a) concatenation.

>what the heck "Asia, Philippines, Bohol, Philippine Islands, Bohol" is supposed to mean

Yup. Bohol Island, Bohol State Park? Bohol State-or-whatever, Bohol Island? Bohol State-or-whatever, Bohol State Park? ???

IDK, I think we've all flip-flopped a few times in various contexts, maybe tossing a " ... Island" in there IS the least evil. But that suggests we should also be doing "Continent of Australia, Country of Australia, ...." er sumthin.

**Comment by Jegelewicz** [comment]
Well if we display it in the "hard to read" table, it's pretty obvious.....

**Comment by sharpphyl** [comment]
And if you Search/Geography for Bohol, you do get the table in the hard and easy to read forms, so it's consistent with those results.

![Bohol](https://user-images.githubusercontent.com/15368365/62980304-6880ad00-bde3-11e9-90bf-8e6058ad2aad.JPG)

**Comment by Jegelewicz** [comment]
Question - do all of those other islands have "island" in their official name? I'm guessing there might be some inconsistencies in how the island rules are being applied (no one reads the documentation...).

**Comment by sharpphyl** [comment]
https://en.wikipedia.org/wiki/Panglao_Island
https://en.wikipedia.org/wiki/Mahanay_Island
Balicasag - no wikipedia entry.  

![Balicasag](https://user-images.githubusercontent.com/15368365/62982157-90264400-bde8-11e9-99ac-e09ae49f2a50.JPG)

On the other hand, under Bohol, Wikipedia lists all these islands and the word Island doesn't appear with any of them, so I'm not sure Wikipedia is consistent either.  

![Bohol Islands](https://user-images.githubusercontent.com/15368365/62982358-235f7980-bde9-11e9-9c20-8f4a4c1f27e3.JPG)

I'm happy to drop the word Island if the complete Higher Geography structure above is shown during data entry.

**Comment by dustymc** [comment]
> Wikipedia is consistent 

The world isn't consistent, but that doesn't mean we have to follow - lots of our rules are "ignore reality in favor of consistency, so we don't end up with duplicates." I'm not morally opposed to more of that.

Are we settled on a grid in geog pick?

**Comment by Jegelewicz** [comment]
I'm good with the grid.

**Comment by sharpphyl** [comment]
Yes, and thank you.

**Comment by dustymc** [comment]
The pick is all griddy now.
