### ISSUE TITLE
Agent summary "roles" and sharing with ORCID

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1790]
From David Shorthouse at ORCID regarding this summary on the agent summary page:

![image](https://user-images.githubusercontent.com/5725767/48276705-e6072f00-e405-11e8-8b70-aaf5cbce96df.png)

> That's awesome! Noticed you've called these "role". Is this synonymous with action verbs "collected", "prepared", etc.? I find role to be a loaded term because it invokes duties of employment. **Would you/could you share via a DwC-A extension if one existed**? 

As for the term "role" he suggested:

> What about Activities or Actions? Expressing it as less about the person (ie Does role = capacity? Are some roles better than others?) and more like their classes of accomplishments helps flatten the unintended power dynamic. And, probably simplifies the presentation.

Seems like he may have a point here. Can the table just say "Activity" instead of "role"?
![image](https://user-images.githubusercontent.com/5725767/48276916-6cbc0c00-e406-11e8-9df2-ae12ef7e9416.png)

**Comment by dustymc** [comment]
>Would you/could you share via a DwC-A extension if one existed?

"Could" is easy enough - "would" is up to ya'll.

>synonymous with action verbs "collected", "prepared", etc.?

The terminology is the usual thing where the data structure is correct but the names no longer make a lot of sense. These data come from table Collector.

```
UAM@ARCTOS> desc collector


 Name								   Null?    Type
 ----------------------------------------------------------------- -------- --------------------------------------------
 COLLECTION_OBJECT_ID	-- this points to collection objects of type cataloged_item
 AGENT_ID	-- this points to agents
 COLLECTOR_ROLE  -- this points to CTCOLLECTOR_ROLE

```

So the assertion is structurally "agent who did thing in http://arctos.database.museum/info/ctDocumentation.cfm?table=CTCOLLECTOR_ROLE to specimen."

I don't think there's any sort of "power dynamic" implied anywhere, it's just a description of how an agent interacted with an item. (And of course any item may have any number of those for any number of agents.)

I don't much care how things are labeled in interfaces, as long as it's not too confusing when paired with things like user expectations and DWC vocabulary.

**Comment by campmlc** [comment]
I've never liked the naming of the code table "Collector" and the
"Collector Role" because it doesn't make sense to have a preparator tracked
in a collector table.

Isn't this more of an agent "relationship" to the specimen?

**Comment by dustymc** [comment]
It's one of a few hundred (depending on how you want to count) potential agent relationships to specimens.

**Comment by Jegelewicz** [comment]
closing as duplicate of #4112
