### ISSUE TITLE
Data entry form changing date in "Specimen/Event" detr. date

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#1791]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
When using the data entry form, after using the geolocate tool, the "Detr. Date" changes the date by moving forward one day.

![ss_detr date](https://user-images.githubusercontent.com/17605945/48295104-3b0e6980-e435-11e8-802c-668c5df78190.jpeg)

**Expected behavior**
Dates in data entry form should not spontaneously change.

**Desktop (please complete the following information):**
 - OS: Mac OS 10.12.6
 - Browser Chrome Version 70.0.3538.77

**Priority**
I would like to have this resolved by date: 2018-11-16

**Comment by dustymc** [comment]
Uh - neato...

I think it's using UTC, so it's only tomorrow if it's tomorrow in Greenwitch.

**Comment by dustymc** [comment]
This is fixed and will be in next release.
