### ISSUE TITLE
Using Part Bulkload for Samples with Loan Subsamples

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1792]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
When trying to use the parts bulkloader to add barcodes to samples, any parts that have been subsampled for loan cause the bulkloader to give a "duplicate parts" error. However,I only want to add the barcode to the part that is NOT a subsample and that is not on loan.  

**Expected behavior**
Have Arctos add barcodes to parts using "use existing" in the parts bulkloader even if the part has been subsampled. Add an option to include or exclude subsamples, or include/exclude samples on loan?

**Priority**
I would like to have this resolved by date: _soon - causing lots of extra time and money to be spent by staff having to do this one by one by hand

**Comment by campmlc** [comment]
A corollary to all this would be to have an easy way to download existing
part condition and disposition. Perhaps this already exists? I have a hard
time extracting this info from the JSON string in specimen results.

**Comment by dustymc** [comment]
That form has been stretched to ridiculous lengths and needs, minimally, split into add and edit apps. Both need a clear distinction between the data used to find parts and that used to create/modify them.

I can't imagine that tool is a reliable way to add barcodes to parts - we probably need better documentation as well.

I think it's another Issue, but what would you like to see in the download?

**Comment by campmlc** [comment]
Happy to have the tool split or modified, but we would need this ASAP.   We
are using it heavily as currently our only option to get tens of thousands
of legacy barcodes added to their respective parts with time limitations
due to grant funding. And we are having to manually enter anything with a
loan subsample, so it is a very time consuming process. Anything that would
make this easier would be an improvement.

Ideally part dispostion and condidtion could be downloaded from Specimen
Results as separate fields - perhaps by choosing these as separate fields
in "add more data" so they would appear in separate columns? In fact, if we
could do this with any concatentated column (eg identifiers) through the
add more data tool, that would be more broadly helpful. It would be nice to
get an identifier split out into its own column without having to change
our profiles.

**Comment by campmlc** [comment]
Alternatively, we could just add "condition" to the flatten parts location
view and make it downloadable.

Can you tell us how to parse the JSON string in part detail into columns
post-download?

**Comment by dustymc** [comment]
>separate fields 

These data can't be represented as separate fields in a spreadsheet-like view in any sort of sane way that I can see.

https://github.com/ArctosDB/arctos/issues/1460 is going to add another level of complexity - everything with those data will (eventually, we hope) start to look like http://arctos-test.tacc.utexas.edu/guid/CHAS:Bird:17187.

<img width="676" alt="screen shot 2018-11-13 at 9 28 16 am" src="https://user-images.githubusercontent.com/5720791/48431411-7c00c980-e726-11e8-8982-b7e39a49cfec.png">

JSON and XML exist for this sort of thing. I don't think there's any useful way of representing those data beside "normal" specimen data in anything that looks like a spreadsheet.

How you parse the JSON will depend on what you're trying to do with it. I suppose you could denormalize, or we could add some sort of "download flattened parts" button somewhere, but for the CHAS example you'd end up with a couple hundred rows that vary only by part or attribute, and I have absolutely no idea how you'd tell which "skin" part an attribute applies to.

OtherIDs have less structure so it might be slightly easier to split them out, but http://arctos.database.museum/guid/MSB:Mamm:268048 has 6 NKs so you'd end up SOMETHING that's not standard - a concatenation or some sort in one column (sometimes) or a variable number of columns or some sort of weird and cryptic column naming or SOMETHING that's almost certainly much harder to work with than complex datatypes stored as strings.

>flatten parts location

https://github.com/ArctosDB/arctos/issues/1460 may add the same sort of complexity problems to that.

If you're just trying to add barcodes to parts, my offer to SQL that in stands. Barcodes can serve as unique part IDs (or not, if you add multiple parts to one barcode-bearing container) so whatever else you're doing is probably fairly simple with barcodes.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/2027
