### ISSUE TITLE
Order of Taxonomic Terms and cloned terms

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#1794]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

The terms in the CTTAXON_TERM table are given in the taxonomic order from highest to lowest.  The same terms are listed at the point when a user clones a classification into a new or existing taxon, but are listed in alphabetical order.  

Also, the “create cloned classification” screen list includes NOMENCLATURAL_CODE, but this is not cloned and must be entered by the user and is a mandatory field. 

**Describe the solution you'd like**
Make both the order of the taxonomic terms the same in the CTTAXON_TABLE and on the "create cloned classification screen."  Remove NOMENCLATURAL_CODE as an item that is transferred from the cloned webservice source to the Arctos local source.

**Describe alternatives you've considered**
Leave it the way it is.  No one else has noticed it.

**Additional context**

![arctos nomenclatural code issue](https://user-images.githubusercontent.com/15368365/48420110-e27deb80-e716-11e8-8caa-b17618b46261.png)

**Priority**
I would like to have this resolved by date: whenever the Taxonomic Committee finishes editing the handbook sections on taxonomy.

**Comment by Jegelewicz** [comment]
@dustymc can this be done easily (seems like it could be)? It would make more sense to see the terms in the order of the taxonomy "tree".

Thanks!

**Comment by Jegelewicz** [comment]
UM, I applied the next task milestone - don't want to seem like I am dictating, but wasn't sure how else to make sure you saw it?....

**Comment by sharpphyl** [comment]
Thanks for reviving this.  Now that we're using WoRMS (via Arctos) I seldom enter new taxa so I'm not right on top of these issues anymore.

**Comment by Jegelewicz** [comment]
Suggest this get done!

**Comment by Jegelewicz** [comment]
Put them in this order

![image](https://user-images.githubusercontent.com/5725767/64900736-43849180-d650-11e9-8429-726bd5b3c8e7.png)
![image](https://user-images.githubusercontent.com/5725767/64900740-5008ea00-d650-11e9-87c9-b31c807c2ca8.png)

**Comment by dustymc** [comment]
This should be addressed as part of https://github.com/ArctosDB/arctos/issues/2695

**Comment by sharpphyl** [comment]
Agree.  We can make this part of the whole group of suggested modifications to the Taxonomic module.

**Comment by sharpphyl** [comment]
I have posted suggested revisions to the Clone Classification pages on our [Google Docs UI section](https://drive.google.com/drive/folders/1gQdI-qWCDFAe6yJSkWkUKlXLAX5KYwLp).  I'm recommending that we eliminate the list of items in the [CTTAXON_TERM](https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxon_term) table so we don't have to update these screens whenever a term is changed.  If the Committee agrees with the suggestions (at tomorrow's meeting?) we can close this issue as it will disappear with the suggested modifications.
