### ISSUE TITLE
UAM:Mamm citation miscalculation

### ISSUE THREAD

**Issue by amgunderson** [ArctosDB/arctos#1798]
On the usage statistics page, http://arctos.database.museum/info/MoreCitationStats.cfm the value for Citations/Loaned Specimen for UAM:Mamm is shown as 0 but should be 0.7.

**Priority**
I would like to have this resolved by date: whenever

**Comment by dustymc** [comment]
UAM:Mamm should be 1.08 - it'll be fixed for next release, somehow I never considered the possibility of having more citations than loans.

<img width="717" alt="screen shot 2018-11-16 at 11 05 29 am" src="https://user-images.githubusercontent.com/5720791/48641720-92f62480-e98f-11e8-9eae-811f096f01b6.png">

Some of that is probably stuff that was used but not formally loaned - you can find some of those here:

<img width="919" alt="screen shot 2018-11-16 at 11 09 18 am" src="https://user-images.githubusercontent.com/5720791/48641902-1b74c500-e990-11e8-8c69-177244bfdee3.png">

Some of it may come from the waffly relationship between loans and citations - there's the start of a discussion at https://github.com/ArctosDB/arctos/issues/1257.

**Comment by amgunderson** [comment]
This Citations/Loaned Specimen number is still showing 0.00 on the Usage Statistics page, https://arctos.database.museum/info/MoreCitationStats.cfm. I would like to show this page at my demo at SPNHC next Thursday.

**Comment by dustymc** [comment]
Gave it a kick

<img width="946" alt="Screen Shot 2019-05-23 at 6 40 55 PM" src="https://user-images.githubusercontent.com/5720791/58296871-5f56e580-7d8a-11e9-87d0-58c56fa2b270.png">
