### ISSUE TITLE
Add Wiki links to Agents

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1800]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
No problem, just an idea

**Describe the solution you'd like**
A new Agent address of "Wikipedia Article" (https://en.wikipedia.org/wiki/)

**Describe alternatives you've considered**
I have been putting links to Wikis in Remarks, but it would be nice if we made this more formal and searchable. We can create reciprocal links by putting a link to the Agent url in the Wikipedia article (not automatic and not sure it ever could be, but something we could have students work on)

**Additional context**
![image](https://user-images.githubusercontent.com/5725767/48675105-eabc9900-eb11-11e8-84f0-1ea609dab6c2.png)

**Priority**
I would like to have this resolved by date: January 31, 2019

**Comment by dustymc** [comment]
<img width="171" alt="screen shot 2018-11-18 at 8 27 13 am" src="https://user-images.githubusercontent.com/5720791/48675312-3a986180-eb0c-11e8-834b-3ff5bc9385a1.png">

http://handbook.arctosdb.org/documentation/agent.html#creating--maintaining-agents

>    Use Addresses when possible. A partial address (“Ohio”) or link to a biography (e.g., Wikipedia – these may be made via Address Type “URL”) is very likely to be useful. Avoid using remarks for address information.


>create reciprocal links by putting a link to the Agent url in the Wikipedia article (not automatic and not sure it ever could be, but something we could have students work on)

There's an API and a huge amount of WP is maintained by bots. But...

There's no reason to believe an Arctos agent URL will exist tomorrow - they get split and merged almost every day, and I might just change them all at some point if it's convenient. Maintaining stable identifiers for dynamic data is a lot of work. If we want to really support incoming links, we should address that. The best way to do so is usually to make the hard stuff someone else's problem, but....

>Per ORCID's terms and conditions , you may only register for an ORCID iD for yourself.

**Comment by AJLinn** [comment]
@Jegelewicz this is something I've been doing too, using the Address Type URL, for as long as we've been in Arctos. It's particularly important when dealing with historical manufacturers who go thru many mergers and name changes, and allows us to track the history of those names. I try to follow the reciprocal link in the Wikipedia articles when relevant, as an "external link" but have admittedly not been good about it. 

One thing we may consider for a future grant proposal idea is a "Wikipedian in residence" (yes, there are such things) who mine our data to make relevant links and new pages in Wikipedia as a way of spreading the collections we all curate. Just an idea!

**Comment by Jegelewicz** [comment]
> One thing we may consider for a future grant proposal idea is a "Wikipedian in residence" (yes, there are such things) who mine our data to make relevant links and new pages in Wikipedia as a way of spreading the collections we all curate. Just an idea!

LOVE this and we should put together a group of institutions to write a grant for such a position.

**Comment by Jegelewicz** [comment]
> Use Addresses when possible. A partial address (“Ohio”) or link to a biography (e.g., Wikipedia – these may be made via Address Type “URL”) is very likely to be useful. Avoid using remarks for address information.

Got it.

**Comment by dustymc** [comment]
>Wikipedian in residence

There are a ton of things that could be done efficiently at the level of Arctos - data cleanup (https://github.com/ArctosDB/arctos/issues/1679), tracking down citations (some low-hanging fruit in the GenBank MIA app), tracking down usage not documented by loans (often pops up after tracking down citations), general outreach (wikipedia, orcid, etc.), very specific outreach ("Wikipedian in residence"), etc.

A huge amount of the stuff in agent remarks could be more useful if stored in a more-structured field. I did...

```
create table temp_agnt_rmk as
select 
AGENT_REMARKS,
PREFERRED_AGENT_NAME,
'https://arctos.database.museum/agents.cfm?agent_id=' || agent_id editlink
from 
agent 
where 
AGENT_REMARKS is not null
order by 
AGENT_REMARKS,
PREFERRED_AGENT_NAME
 12   13  ;

Table created.

-- get rid of the most redundant

UAM@ARCTOS> delete from temp_agnt_rmk where AGENT_REMARKS in (select AGENT_REMARKS from temp_agnt_rmk having count(*) > 20 group by  AGENT_REMARKS );

10327 rows deleted.
```

CSV attached.

[temp_agnt_rmk(1).csv.zip](https://github.com/ArctosDB/arctos/files/2596686/temp_agnt_rmk.1.csv.zip)

**Comment by Jegelewicz** [comment]
My question was answered, closing
