### ISSUE TITLE
PLEASE! Ignore blank line inserted by Excel in the "Bulk Edit Container" tool

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1801]
I thought I saw that this had been done, but I still get this
![image](https://user-images.githubusercontent.com/5725767/48721281-ce3a6280-ebde-11e8-8e39-b2f327f5c8ea.png)

unless I open the file in Notepad, scroll to the bottom and delete the final blank line.

Can we PLEASE get this corrected. I spend way too much time on this repetitive task.

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/1691
