### ISSUE TITLE
Wikispecies a viable taxonomy to link with?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1804]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
Not a problem, just exploring the use of open source taxonomy.

**Describe the solution you'd like**
Could a collection use Wikispecies as its taxomony? See https://meta.wikimedia.org/wiki/Wikispecies/FAQ

**Describe alternatives you've considered**
Just wondering if we couldn't be contributing to a resource that would benefit those beyond Arctos since we seem to be in the business of creating classifications.

**Additional context**
A typical Wikispecies page
![image](https://user-images.githubusercontent.com/5725767/48815268-1cdd1f00-ecfb-11e8-84ee-1a5ed04faa46.png)

**Priority**
I would like to have this resolved by date: _______

**Comment by sharpphyl** [comment]
Just looked briefly at it for mollusca (Conidae) and it is significantly out of date vs. WoRMS.  Might work for other collections but doesn't look useable for us.

**Comment by sharpphyl** [comment]
Supposedly, this is one of the resources that Global Names uses.  Is it just a matter of adding it as a non-local classification?

https://resolver.globalnames.org/data_sources

**Comment by dustymc** [comment]
I'm not seeing those data in GN - maybe something's stuck. @dimus?

In general, figuring something out with GN is always going to be my preference for getting taxonomy data into Arctos. I suspect they're resource-limited like everyone else so I wouldn't expect this to always be as easy as just asking, but they're also probably more efficient than Arctos at pulling data from random formats and once it's in GN it will find its way to Arctos.

**Comment by dimus** [comment]
@dustymc, @Jegelewicz @sharpphyl Looks like last harvest of wikispecies got corrupted, I did not notice that, thank you for letting me know. I will try to rerun it. Wikispecies are tricky, because they are entered by hand, and as a result have many inconsitant pages. Hopefully I will make it working: https://github.com/GlobalNamesArchitecture/dwca_hunter/issues/46

**Comment by Jegelewicz** [comment]
So I think the answer to my original question is no.....
