### ISSUE TITLE
Remove column VALID_CATALOG_TERM_FG from taxonomy bulkloader

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#1808]
**Describe the bug**
When we replaced the VALID_CATALOG_TERM - which was to be a 0 (invalid) or 1 (valid) - this data moved to the TAXON_STATUS column.  Is there any need for the column VALID_CATALOG_TERM?

**To Reproduce**
Create csv from the Hierarchy Tool.

**Expected behavior**
Remove this column if it's no longer needed.

**Screenshots**
![screen shot 2018-11-22 at 9 24 05 am](https://user-images.githubusercontent.com/15368365/48921929-65fab380-ee60-11e8-8d38-75c21cf08fa9.png)

**Desktop (please complete the following information):**
 -Both Mac and Windows - Firefox and Chrome

**Priority**
I would like to have this resolved by date: not urgent but clutter if it's not needed.

**Comment by Jegelewicz** [comment]
Also, what is TAXON_RELATION. I can't find a definition.
