### ISSUE TITLE
Suggest revision of how classifications are labeled

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1813]
Currently a classification has two sections, each consisting of one or more terms, plus a potential list of relationships to other classifications. The two parts are labeled "Non-Classification Terms" and "Classification Terms". This is confusing given that we call the relationships "Non-Classification Data" as seen in the "Edit Non-Classification Data" option on the classification page.

![image](https://user-images.githubusercontent.com/5725767/48987684-4a9cdc00-f0de-11e8-9a4d-0a564a506aae.png)

@sharpphyl  and I suggest the following changes to these sections so that things are more clearly identified.

Change "Edit Non_Classification Data" to "Edit Classification Relationships"
Change "Non-Classification Terms" to "Non-Hierarchical Classification Terms"
Change "Classification Terms" to "Hierarchical Classification Terms"

We would like to get this done before the Taxonomy webinar 2018-01-10

**Comment by dustymc** [comment]
See also https://github.com/ArctosDB/arctos/issues/1819 and https://github.com/ArctosDB/arctos/issues/1698

>each consisting of one or more terms

zero or more


>Edit Classification Relationships
>relationships to other classifications

https://github.com/ArctosDB/arctos/issues/1819#issuecomment-441864792, and relationships are NOT hooked to any of the things I call "classifications" - they're linked directly to names. (And doing so creates "classifications" for the purpose of discoverability.)

>Non-Hierarchical Classification Terms

That is not quite correct - you can add 500 terms all ranked "Animalia" to a single classification, so while the "non-hierarchical" terms cannot be hierarchical, the "hierarchical" terms are not necessarily hierarchical either. I'm not completely opposed to this and maybe it gets the idea across, but I don't want to write the documentation....

>Change "Classification Terms" to "Hierarchical Classification Terms"

Ditto ^^ that


>in the Hierarchical Classification Editor, we call this metadata

That's "correct" in that those are not hierarchical data so they can't possibly be data in a hierarchical editor - they're just sort of hanging off the side there. That's not true in "real Arctos" - taxon_term "remark" and taxon_term "kingdom" are structurally-equivalent. Semantics aside, objections to officially adopting "classification metadata" for data in taxon_term with NULL position_in_classification?

**Comment by Jegelewicz** [comment]
> We need to be consistent with our terms and use ones that are as meaningful as possible. 

I would add "to the users" to that. I'll change my request to:

Change "Edit Non_Classification Data" to "Edit Taxon Name Relationships"
Change "Non-Classification Terms" to "Non-Hierarchical Classification Terms"
Change "Classification Terms" to "Hierarchical Classification Terms"

I don't want to argue about whether people might do crazy stuff like add 5 kingdom terms to a classification, I think we can all agree that a classification generally represents a "hierarchy" and the other related terms are not part of that hierarchy, but they are important.

**Comment by Jegelewicz** [comment]
working in #1819
