### ISSUE TITLE
What is the Code Table TAXONOMIC_AUTHORITY used for?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1814]
There is a code table called [TAXONOMIC_AUTHORITY](https://arctos.database.museum/info/ctDocumentation.cfm?table=CTTAXONOMIC_AUTHORITY) that I would assume to be the controlled vocabulary for Source_Authority in the Non-Classification section of a classification. But it is not used that way as I have definitely been putting stuff like the WoRMS citation below in that field and it takes it just fine.

> Schuchert, P. (2018). World Hydrozoa Database. Abietinaria elsaeoswaldae Stechow, 1923. Accessed through: World Register of Marine Species at: http://www.marinespecies.org/aphia.php?p=taxdetails&id=285360 on 2018-11-24

![image](https://user-images.githubusercontent.com/5725767/48988499-09f39180-f0e3-11e8-8afd-f42369107465.png)

If we are going to use a controlled vocabulary for authority, I am all for that, but we should make the field "source_authority" limited to that vocabulary. If we aren't and the TAXONOMIC_AUTHORITY table isn't being used anywhere else, then I suggest we get rid of it as it causes confusion.

**Comment by sharpphyl** [comment]
Agreed.  I thought for a year or so that I could only use what was in the table.  I don't see anything in the Handbook about it, so may be could move the list of names into an article giving them as examples of Authorities that have been used or recommended by other collections.

**Comment by Jegelewicz** [comment]
Agree.

**Comment by Jegelewicz** [comment]
AWG approved deletion of the table.

> [Remove taxonomy authority table to replace with authority citation/ref](https://docs.google.com/document/d/1dlt4GeEHd6a1fIpcoBLo8HWFBLeXXcqDZzH3OezkUqA/edit#)

**Comment by dustymc** [comment]
[CTTAXONOMIC_AUTHORITY.csv.zip](https://github.com/ArctosDB/arctos/files/2792760/CTTAXONOMIC_AUTHORITY.csv.zip)
