### ISSUE TITLE
Change GO_GO_ALL to RUNNING_DATA_CHECKS in the Hierarchical Classification Editor

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#1818]
I'm always initially confused by the GO_GO_ALL status.  The system is still running the data checks.  I think it means that you passed the upload stage but it's easy to interpret it as "time to go go!" and upload the data - despite the directions that say to wait.

![screen shot 2018-11-22 at 7 09 12 pm](https://user-images.githubusercontent.com/15368365/48952644-22f01d00-ef00-11e8-9258-f95879b98041.png)

**Describe the solution you'd like**
Change this status to RUNNING_DATA_CHECKS

**Additional context**
We'll need to change the instructions to match the status if we do this.  Currently they read:

![screen shot 2018-11-22 at 9 52 04 am](https://user-images.githubusercontent.com/15368365/48952614-0358f480-ef00-11e8-8ea3-d959ecd62ecd.png)
 
They would read: When your data have been uploaded, the data checking process will begin.  The status bar will read "RUNNING_DATA_CHECKS."  Reload the page and the Status Bar will begin to list errors or show that checks have passed.  If necessary, download your data, correct errors, delete data and reload corrected data.  Reload page until the Status bar reads "ALL_CHECKS_PASSED."  Marking to load when the Status bar reads "RUNNING_DATA_CHECKS" will result in errors.

If we do this, I'll change the draft edits on "How to Manage Taxonomy Hierarchically."

**Priority**
I would like to have this resolved by date: December 1 ?

**Comment by campmlc** [comment]
This makes much more sense to me. I support the language change.

**Comment by Jegelewicz** [comment]
I agree as well.

**Comment by dustymc** [comment]
no longer relevant
