### ISSUE TITLE
New collection at UAM/UAF

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#1824]
I am working on a proposal to UAF to catalog all of the public art, historical monuments, and historic buildings (on the National Register of Historic Places) on the UAF campus into Arctos as a way of keeping track of the information about their artists, the funding used to install the works, the historical documents associated with the items, and the physical location of them on our campus.

I'd like some input as to the best way to do this. Should this be a new institution (we're probably talking ~100-150 pieces total to be cataloged)? Can we just add this as a new collection under UAM (e.g., UAM:Pub = public art and monuments) with me as the contact as I'll be working with an intern to create all the records & will be the point of contact for managing the collection? The description would clearly indicate the items are owned by UAF and located on the UAF campus rather than within the walls of the museum. We also have no obligation of care over the objects, but I'm trying to help the university figure out their own plan for "managing" this collection of art and historic monuments. These are all items that are "permanently" affixed around the grounds of the university (in quotes because it's technically possible for them to move, but with a great deal of effort).

I don't think any of our other institutions have handled this type of collection yet, but our Master Planning Committee is really excited about the prospect of getting them into Arctos since they've been trying to figure out how to do it for 25+ years! I think it's a great way to extend the visibility of Arctos on our own campus.

I welcome all ideas and would be happy to talk more about it at the next AWG meeting.

**Comment by Jegelewicz** [comment]
> Should this be a new institution (we're probably talking ~100-150 pieces total to be cataloged)? Can we just add this as a new collection under UAM (e.g., UAM:Pub = public art and monuments) with me as the contact as I'll be working with an intern to create all the records & will be the point of contact for managing the collection?

I think the collection works best and UAM:Pub is OK with me too.

This is exciting!!!!

**Comment by dustymc** [comment]
Sounds reasonable, sounds possible (seems pretty close to what botanical gardens do, minus the collecting and propagating and such), and I think the administrative stuff is more or less arbitrary.

**Comment by dustymc** [comment]
Does this still need to be discussed?

**Comment by Jegelewicz** [comment]
> UAF:PubArt would work better, as it would be best to have UAF-owned/managed items not confused with UAM collections.

"Pub" worries me a little because of potential confusion with Published or Publication. Is UAF:PublicArt too long? Are we messing with the proper case codes that were discussed in some issue I cannot locate @mkoo ?

**Comment by dustymc** [comment]
>potential confusion

That's a little like finding your birthday in a UUID - it's just an identifier....

>too long

[No.](https://handbook.arctosdb.org/documentation/catalog.html#guid-prefix)

**Comment by Jegelewicz** [comment]
@AJLinn @krgomez we now have a procedure for this. When you guys are ready to do this [file an issue](https://github.com/ArctosDB/new-collections/issues/new?assignees=&labels=&template=exisiting-institution-requesting-a-new-collection.md&title=Arctos+Institution+Name+request+to+add+a+new+collection) in the new collections repo.
