### ISSUE TITLE
WoRMS link

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1828]
I'm splitting this off from https://github.com/ArctosDB/arctos/issues/1713#issuecomment-442634502

1) add taxon_term "AphiaID"
    * Definition: World Register of Marine Species identifier. Must be numeric. Classifications with this ID are subject to automated replacement.
1) Limit datatype to numeric
1) For display, wrap with href to ``http://www.marinespecies.org/aphia.php?p=taxdetails&id={AphiaID}``

I'll refresh data by AphiaID when it exists, NOT by name. This will allow users to select a classification (at WoRMS) in the case of homonyms or other ambiguity.

I could also limit that automation to "WoRMS-driven" classifications, if there's some reason to do so.

Should I add this to the classification bulkloader as well? I can see wanting to load these data, but records with it will be replaced by an automated pull from WoRMS so there's not much point of ever having them in eg, the hierarchical tool (which feeds the classification bulkloader).

**Comment by Jegelewicz** [comment]
> I'll refresh data by AphiaID when it exists, NOT by name. This will allow users to select a classification (at WoRMS) in the case of homonyms or other ambiguity.

Yes!!!

> Should I add this to the classification bulkloader as well? I can see wanting to load these data, but records with it will be replaced by an automated pull from WoRMS so there's not much point of ever having them in eg, the hierarchical tool (which feeds the classification bulkloader).

I think we might need it. New AphiaIDs will be created constantly, unless we have a way to keep populating our classifications with them, we will need a tool to do that with.

**Comment by dustymc** [comment]
I'd probably call that outright sabotage...

**Comment by Jegelewicz** [comment]
Be that as it may, the snail people do not want their specimens classified as fish and the fish people do not want theirs classified as snails.

**Comment by sharpphyl** [comment]
I see no reason to add the WoRMS taxa to the hierarchical classification tool as a dataset for our collection.  As long as WoRMs is updating the taxa, we don't need to do it.  This is especially true if we add WoRMS as a local classification in addition to Arctos and Arctos Plants.  Our biggest challenge will be knowing what changes WoRMS has made so we aren't searching all over for revised taxa.

**Comment by sharpphyl** [comment]
And I like using the AphiaID as the control point for the taxa and especially for updating them.  I doubt WoRMS would change any of these ID's.
