### ISSUE TITLE
Cannot delete freezer positions

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1829]
Just trying to create my first freezer with the new tool and of course, I made a mistake. I haven't scanned anything into it and I tried using the "Delete all positions" button

![image](https://user-images.githubusercontent.com/5725767/49245081-91d0e880-f3ce-11e8-89d9-9b8c32ad660f.png)

but when I click it, I just get this screen

![image](https://user-images.githubusercontent.com/5725767/49245117-a4e3b880-f3ce-11e8-9266-b034eaa0261a.png)

and when I return to the freezer, the positions are still there.

I have also reset the magic box and tried to delete the positions with no luck.

http://arctos.database.museum/EditContainer.cfm?container_id=14844252

**Comment by dustymc** [comment]
woops! fixed for next release.

Want me to nuke the positions for now?

**Comment by Jegelewicz** [comment]
Yes, please! and Thank you!

**Comment by dustymc** [comment]
done
