### ISSUE TITLE
Cloning Records from UAM to MSB

### ISSUE THREAD

**Issue by KyndallH** [ArctosDB/arctos#1830]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
UAM are deaccessioning 2000.050 since we no longer have any of the parts. MSB have the parts so hoping we could clone the records for MSB before we remove them from UAM.

**Describe the solution you'd like**
Clone all the records in UAM accession 2000.050 for MSB.

**Describe alternatives you've considered**
I can pull collecting event and collector number, or download the specimen data with collecting event ID to re-upload, or you can clone them all as MSB:Mamm?

**Additional context**

**Priority**
I would like to have this resolved by date: 12/5

**Comment by campmlc** [comment]
Reviving this. @KyndallH are there transactions attached to any of the UAM records? Any other children of the records?
If not, I could use a csv download of the accession, with collecting event ID, to re-upload.
Or we could clone - but I haven't done this before on such a scale. @dustymc  what is preferable?

**Comment by dustymc** [comment]
You can't direct-clone across VPDs.

@lkvoong has scripts to lock down and MOVE things across VPDs, but not replicate.

The download for bulkloader option is probably best.

**Comment by Jegelewicz** [comment]
We did just that very recently at NMMNH. It was super easy. Just get search results that have what you need, make sure you have as many fields as possible, download csv, change a few things (primarily other ids, guid prefix, catalog numbers), upload new records.

**Comment by campmlc** [comment]
Yes, happy to do that as long as we aren't trying to document loan history etc, which would be great if possible during transfer of custody. But that is another issue.

**Comment by campmlc** [comment]
@KyndallH do you need to send me a download that includes curatorial info, or can get all relevant data as a public user?
I'll need a list of the specimen numbers if the later.

**Comment by KyndallH** [comment]
Doesn't look like there is any loan history but used on project Nuclear and mitochondrial perspectives on a contact zone of marten (Martes americana).
