### ISSUE TITLE
Empty containers not listed in "Find empty containers in this container which have positions as parents"

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1832]
Recently, freezer boxes have been created and cryovials scanned into them. One such box is [DGR19768](http://arctos.database.museum/EditContainer.cfm?container_id=14851217)

When I select "Positions" for this box, I see the box template with the barcodes and their related labels as expected.

![image](https://user-images.githubusercontent.com/5725767/49246741-e1b1ae80-f3d2-11e8-9323-663272b05081.png)

but when I select "Find empty containers in this container which have positions as parents"
I get nothing

![image](https://user-images.githubusercontent.com/5725767/49246837-0dcd2f80-f3d3-11e8-87e2-fc7f9f8504f2.png)

Even though I know all the vials are "empty", which is confirmed by "See all collection objects in this container"

![image](https://user-images.githubusercontent.com/5725767/49246901-3523fc80-f3d3-11e8-9aa9-9c585605bf5d.png)

I think this is related to the new positions functionality, but I'm not sure how or what I have done incorrectly...

**Comment by dustymc** [comment]
Fixed for next release.

Note that in general "See all collection objects in this container" is NOT the same thing - if the vials contained non-part-containers (rooms or something) the two queries would produce different results.
