### ISSUE TITLE
deleting taxonomy: annotations

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1836]
Annotated taxonomy will not delete. For http://arctos.database.museum/name/Alycaeus%20kelanianensis the annotation is just me wondering if the taxon is valid; in other cases it may be something of importance.

Should I cascade taxon deletion to annotations? If not, what should happen with this?

**Comment by sharpphyl** [comment]
Oh, I'm quite certain it's not valid.  It totally fails the  Google test and I tried to delete it.  It probably should be _Alycaeus kelantanensis_ Sykes, 1902 which is in "Arctos."  How do annotations get made?  And what does "cascade taxon deletion to annotations" mean?


![screen shot 2018-12-03 at 9 11 59 am](https://user-images.githubusercontent.com/15368365/49385887-9b629500-f6db-11e8-8cb7-6357bbd94a18.png)

**Comment by sharpphyl** [comment]
Ah, so I probably made the annotation when I reported it as a possible bug. The change would be fine with me.  Can you go ahead and delete this taxon?  Thx.

**Comment by Jegelewicz** [comment]
> Should I cascade taxon deletion to annotations? If not, what should happen with this?

I think I would prefer if someone reviewed the annotation and had the ability to remove it before the name was deleted. Make sense? Possible?

**Comment by sharpphyl** [comment]
I'm the one who initiated the annotation by reporting a bug and it's not a problem anymore so I'll close this issue.
