### ISSUE TITLE
Add ISBN in publications?

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#1837]
Just starting to use publications more and I'm wondering if it would be useful for us to have a field for ISBN of books?

**Comment by dustymc** [comment]
Can it DO anything? If so, maybe...

I can get ISBN (and lots more) from DOI, but many books probably don't have a DOI. (Yet?)

**Comment by Jegelewicz** [comment]
The ISBN can definitely DO something, especially when it comes to libraries and Amazon.

> The purpose of the ISBN is to establish and identify one title or edition of a title from one specific publisher and is unique to that edition, allowing for more efficient marketing of products by booksellers, libraries, universities, wholesalers and distributors. 

So yes, I believe that

> having the unique number associated with that publication would be valuable for distinguishing between editions, etc. when we use a particular one for citations.

**Comment by dustymc** [comment]
DOI is

- issued
- actionable
- leads to a bunch of other information (authors, funding, cited by, cites, etc.)

I can use all that to create publications, and to KNOW that the strings entered in DOI are in fact DOIs (those that are resolve, those that are not do not).

I was thinking of _do_ (and datatype) in that context. I can't find anything similar for ISBN. There are some resolvers, but it's not clear to me if any of them are authoritative/complete/etc. If such a thing exists, ISBN can be much more trustworthy (and actionable) than if we're just typing strings.

Publication also includes PubmedID, which I don't think is used much in light of what can now be done with DOIs. (It leads to a publication, if someone entered the ID correctly.) Depending on how much ISBN can _do_ in the context of DOI capabilities, we might somehow generalize the pubmed ID to include ISBN (as "external ID type" and "external ID value" or something, maybe), or we could add something that works more like DOIs.

How often is there useful ISBN data and no DOI? Media is always an option to link to external things - maybe a Media link to something like https://isbnsearch.org/isbn/0387963316 is sufficient if this isn't a common use case?

**Comment by Jegelewicz** [comment]
I use a site called [Bookcrossing](https://www.bookcrossing.com/). When I want to register a book, I enter the ISBN. The service doesn't always work, but generally after I enter the ISBN

![image](https://user-images.githubusercontent.com/5725767/49487525-f5f51180-f7ff-11e8-8626-58cd9728e6dc.png)

I get back the book's basic information

![image](https://user-images.githubusercontent.com/5725767/49487534-060cf100-f800-11e8-98a0-0ed9431c416b.png)
 
I don't know how this is working between Bookcrossing and Amazon, but it definitely does SOMETHING that could help one complete publication information rather than typing it all in. (and possibly lead to book sales for Amazon? - Can we get some kind of royalty for that?)

**Comment by campmlc** [comment]
When I google a book, I usually get the ISBN number, e.g. through google
books. I can find the doi's if I go to academic publishers websites, but
the first google result seems to be the marketing outlets and libraries
showing the ISBN.

**Comment by dustymc** [comment]
ISBN still doesn't seem to be quite the same sort of THING - or provide the same sort of services, anyway - that CrossRef DOIs offer to me. Suggest Media ( Option 2: Create Media from URL. ) and/or storage location (which could possibly be made public and/or clickable?). I added this for https://arctos.database.museum/publication/10010547

Very tentatively tabling - please reopen, recategorize, and enhance if this needs more immediate attention.
