### ISSUE TITLE
Locality record links to specimen

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#1838]
In a Locality record (e.g., http://arctos.database.museum/editLocality.cfm?locality_id=10124551) there is a link to all specimens tied to this locality.  In the example, there are 34 specimens linked to this locality. However, when I click on the link to view these specimens, only 25 show up. In the Verification Status box of the locality record, I can see that there are 9 birds where the verification status is 'unaccepted'. This must be why the search results are 9 short. How do I find out which specimens these 9 are? 
I could record the 25 that show up as unverified, update the status of all records to 'unverified' and then the link would presumably show all 34. But I want to see if I can determine why they were marked as 'unaccepted' before I make any changes. It was likely just a data entry error, but I'd like to confirm that first. 
In the Verification Status box, can we have links to the specimens of each status type? That would allow me to check the specimens with 'unaccepted' status. But it is still weird that the link to 34 specimens only returns 25 specimens. 

![image](https://user-images.githubusercontent.com/12507297/49467986-eacec100-f7c0-11e8-9b1f-bda9fb160557.png)

**Comment by dustymc** [comment]
The top box should read "xxx specimen-events" (or ?? - suggestions appreciated).

I can add links to the event-box. You can also alter the locality URL - terms are http://arctos.database.museum/api/specsrch

http://arctos.database.museum/SpecimenResults.cfm?locality_id=10124551&verificationstatus=unaccepted

I'm not sure any of that will reliably give a specimen count - any specimen can hold any number of events of any type.

Here's how that locality is used.

```
select flat.guid, specimen_event.verificationstatus from flat,specimen_event,collecting_event
where flat.collection_object_id=specimen_event.collection_object_id and
specimen_event.collecting_event_id=collecting_event.collecting_event_id and
collecting_event.locality_id=10124551
order by 
specimen_event.verificationstatus;


GUID
------------------------------------------------------------------------------------------------------------------------
VERIFICATIONSTATUS
------------------------------------------------------------------------------------------------------------------------
DMNS:Bird:13764
unaccepted

DMNS:Bird:12648
unaccepted

DMNS:Bird:12667
unaccepted

DMNS:Bird:13120
unaccepted

DMNS:Bird:42709
unaccepted

DMNS:Bird:13119
unaccepted

DMNS:Bird:13719
unaccepted

DMNS:Bird:13118
unaccepted

DMNS:Bird:13718
unaccepted

DMNS:Bird:42709
unverified

DMNS:Bird:13120
unverified

DMNS:Bird:6067
unverified

DMNS:Bird:38685
unverified

DMNS:Bird:12911
unverified

DMNS:Bird:40772
unverified

DMNS:Bird:544
unverified

DMNS:Bird:13655
unverified

DMNS:Bird:40591
unverified

DMNS:Bird:40546
unverified

DMNS:Bird:39313
unverified

DMNS:Bird:40813
unverified

DMNS:Bird:42346
unverified

DMNS:Bird:49361
unverified

DMNS:Inv:19162
unverified

DMNS:Bird:13719
unverified

DMNS:Bird:13764
unverified

DMNS:Bird:13718
unverified

DMNS:Bird:12648
unverified

DMNS:Bird:13119
unverified

DMNS:Bird:12667
unverified

DMNS:Bird:13118
unverified

DMNS:Mamm:16651
unverified

DMNS:Bird:13200
unverified

DMNS:Bird:40445
unverified


34 rows selected.
```

**Comment by AJLinn** [comment]
> The top box should read "xxx specimen-events" (or ?? - suggestions appreciated).

I like this suggestion. I just had one that said 389 specimens, but it actually was more likely 193 actual objects.

<img width="478" alt="screen shot 2018-12-04 at 11 10 43 am" src="https://user-images.githubusercontent.com/17605945/49469964-4dba5b00-f7b5-11e8-8cbc-5abba2a97cbb.png">

**Comment by Jegelewicz** [comment]
I totally get this because I am in the process of adding a bunch of records with an unaccepted event without coordinates, followed by an accepted one with coordinates, but both events use the same locality. Therefore the number of "specimens" attached is doubled. I think putting number of events would be more accurate.

**Comment by Jegelewicz** [comment]
So much good stuff going on! Thanks for handling these!!!!
