### ISSUE TITLE
Add lung (frozen) to herp collections

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#1839]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Table**
http://arctos.database.museum/info/ctDocumentation.cfm?table=CTSPECIMEN_PART_NAME&coln=

**Value**
add lung (frozen) to herp collections

**Definition**
frozen lung
**Collection type**
Herp

**Part tissue flag**
not a new tissue

**Context**
have lung tissues in the herp collections.

**Priority**
I would like to have this resolved by date: _______12/15/2018

**Comment by ccicero** [comment]
I just tried adding Herp to the part 'lung' but can't update because it says "Inconsistent data;contact a DBA."

Under description it says "description inconsistency!!! ,lung (frozen)"

Not sure what is inconsistent about this??? @dustymc

**Comment by dustymc** [comment]
```
UAM@ARCTOS> select description from ctspecimen_part_name where part_name='lung (frozen)';

DESCRIPTION
------------------------------------------------------------------------------------------------------------------------


lung (frozen)

3 rows selected.
```

I updated them all to "lung (frozen)" so the editor should work. Not useful, but I don't have better ideas. We should discriminate between organs and samples too, somehow. "sample of frozen lung tissue"??

https://github.com/ArctosDB/arctos/issues/1450

**Comment by campmlc** [comment]
I added Herp to "lung (frozen)". Please do not change to "sample of frozen lung tissue", as that will cause endless confusion between the "sample of" and the "subsample of".  The distinction of sample vs subsample would have to be made at the individual sample or organism level, based on the size of the organism and the size of the vial, and whether all or part would fit at the particular event when the part was collected.

**Comment by campmlc** [comment]
Another reminder that we need to split part and preservation. This should be "lung" with "frozen" as the preservation field.

**Comment by dustymc** [comment]
>sample of frozen lung tissue",

That suggestion was for documentation, not part names.

**Comment by ccicero** [comment]
I agree with Mariel about sample vs subsample, but don't really  understand the issue of organ vs sample. What's the problem Dusty?

**Comment by dustymc** [comment]
>What's the problem 

Find whole lungs, or chunks of lung big enough to dig for parasites, or similar for any of the "tissue types" in Arctos. Pretty low-priority, but it's something that we've been looking for a solution to for a while.
