### ISSUE TITLE
Classification spaces in specimen record

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1845]
I was working on webinar stuff and noticed this:

![image](https://user-images.githubusercontent.com/5725767/49819401-908aae80-fd32-11e8-8214-ed48cc82becc.png)

In the classification terms below the name it appears as:

> Plantae ; Tracheophyta ; Magnoliopsida; Apiales; Apiaceae; Zizia cordata W.D.J. Koch ex DC. 

I'm being picky, but why the spaces after the kingdom and phylum names?

**Comment by dustymc** [comment]
>but why the spaces after the kingdom and phylum names

The usual - someone put them there.

```
UAM@ARCTOS> select ':'||term||':' from taxon_term where term_type='kingdom' and source='Arctos Plants' and taxon_name_id=(select taxon_name_id from taxon_name where scientific_name='Zizia cordata');

':'||TERM||':'
------------------------------------------------------------------------------------------------------------------------
:Plantae :

```

**Comment by Jegelewicz** [comment]
In the classification? I checked to make sure that there weren't any spaces after "Plantae" in the classification because I assumed that was the problem, but there weren't any.....

**Comment by dustymc** [comment]
Yes, taxon_term is classification data.

```
UAM@ARCTOS> select ':'||term||':' from taxon_term where term_type='kingdom' and source='Arctos Plants' and taxon_name_id=(select taxon_name_id from taxon_name where scientific_name='Zizia cordata');

':'||TERM||':'
------------------------------------------------------------------------------------------------------------------------
:Plantae :

```

<img width="176" alt="screen shot 2018-12-11 at 4 03 57 pm" src="https://user-images.githubusercontent.com/5720791/49838234-8da5b300-fd5e-11e8-8c21-07fc88c9ca70.png">

<img width="115" alt="screen shot 2018-12-11 at 4 04 15 pm" src="https://user-images.githubusercontent.com/5720791/49838239-926a6700-fd5e-11e8-8964-3d8593d5c9fa.png">

backspace...

<img width="93" alt="screen shot 2018-12-11 at 4 04 21 pm" src="https://user-images.githubusercontent.com/5720791/49838250-97c7b180-fd5e-11e8-95fb-90fd27cdcc09.png">

save

```
UAM@ARCTOS> select ':'||term||':' from taxon_term where term_type='kingdom' and source='Arctos Plants' and taxon_name_id=(select taxon_name_id from taxon_name where scientific_name='Zizia cordata');

':'||TERM||':'
------------------------------------------------------------------------------------------------------------------------
:Plantae:
```

**Comment by Jegelewicz** [comment]
Hmmmm, I didn't find a space there when I checked (before I posted this). That's nuts, but then technology has not been my friend lately.
