### ISSUE TITLE
Merge Container is automatic

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1847]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
When using the merge containers function, as soon as a barcode is scanned into the Donor Barcode field, the container is updated, you never have to select "Merge Containers". This doesn't allow for checking the barcode that has been scanned before saving the merge.

**To Reproduce**
1. Go to any container
2. Click on Edit Container
3. Scroll down to "scary red" merge container box
4. Enter a barcode and it merges, no waiting for the user to select "Merge Containers"

**Expected behavior**
After the donor barcode is entered the user should have the opportunity to review the barcode before merging by selecting "Merge Containers".

**Screenshots**
![image](https://user-images.githubusercontent.com/5725767/49882998-06ece680-fdef-11e8-8c92-d273b91b683a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome (also tried with Firefox)
 - Version:  

**Additional context**

**Priority**
I would like to have this resolved by date: 2018-12-15

**Comment by dustymc** [comment]
That's just a normal "submit" form. It's not tied to anything which could possibly cause this behavior. You have something in your system (browser extension?) causing this, or perhaps your scanner is transmitting a post-data ENTER?

**Comment by Jegelewicz** [comment]
I'll check on the enter tomorrow - it was a student who was experiencing the issue, so that may be it...
