### ISSUE TITLE
Geology field behavior in data entry has a bug

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#1849]
We have a group of fossil shells we are databasing and want to add formation, epoch etc.  The handbook doesn't address how to get Geology Attributes available for a collection.  Despite selecting "Show" for Geology Attributes in the Customize Form tool on Data Entry, we can't see them.  Is there some authorization that we need to see these fields?  I see that other collections are able to do this - see http://arctos.database.museum/guid/UNM:ES:13067.

**Priority**
I would like to have this resolved by date: 17 Dec 2018 when we start databasing these specimens

**Comment by dustymc** [comment]
Sorry, I missed this.

Geology is hard-coded by collection type - it works for ES collections. I think I can probably hard-code your guid_prefix in too but I'll have to look closer to be sure.

Alternatively, we could just allow it for any collection - it's possible to customize and turn it off, after all.

In the meantime you can always pre-create localities with geology data and use them in for data entry.

**Comment by dustymc** [comment]
Also: I am developing taxonomy-stuff in production for various reasons, which greatly complicates code management. I don't think it's possible that this will happen today.

**Comment by sharpphyl** [comment]
Ok, I didn't know I could pre-create locality with geology data.  I'll work on that later today.  That may be enough - certainly for today.

**Comment by sharpphyl** [comment]
That will work ok.  But if I need an additional "member" do I make the request on GibHub?

**Comment by dustymc** [comment]
Yes, that's just a code table (albeit a hierarchical one).

**Comment by Jegelewicz** [comment]
@campmlc can you do this? I haven't added one of these and I'd rather learn from you before I do!

**Comment by Jegelewicz** [comment]
Done - sorry for the huge delay!

**Comment by sharpphyl** [comment]
This was closed after a specific member was added to the GEOLOGY_ATTRIBUTE table - Thanks - but the original question remains.  Can you add Geology Attributes as fields that can be accessed for Invertebrates during data entry.  Right now, we have to create localities, then link to them rather than creating them within the specimen record.  Dusty said he could enable that for all collections and let them turn it on and off as needed or just add it for Invertebrates.  Either works for our collection.

**Comment by dustymc** [comment]
Yes, here's the question for everyone:

>Alternatively, we could just allow it [geology] for any collection - it's possible to customize and turn it off, after all.

Is there any need for that, or some sort of control, or should I hard-code collections in as necessary?

**Comment by Jegelewicz** [comment]
I think everyone should be able to access them.

**Comment by campmlc** [comment]
I agree.

**Comment by sharpphyl** [comment]
When will this be discussed?

**Comment by Jegelewicz** [comment]
I don't know why this was blocked - access to geology isn't going to hurt anyone is it?

**Comment by dustymc** [comment]
>give access to inverts

I can do that, there was some mention of just giving it to everyone above. (Individual users can of course hide geology, like anything else.)

**Comment by sharpphyl** [comment]
What do we need to do to get approval to move forward with adding this as an option to the data entry form?  We all seem to be in agreement that it won't hurt anything and individual users can turn it on or off as needed.

**Comment by Jegelewicz** [comment]
I'm not sure. I don't know why @mkoo blocked it and until she comments, the best I can say is add it to the next issues agenda or email her directly. I don't see any reason it shouldn't be available to Inv collections.

**Comment by dustymc** [comment]
> available to Inv collections

I'm still unclear on the current state of the request - is this for inv or everyone?

**Comment by Jegelewicz** [comment]
For now, just Inv - that was the original issue. If someone else wants it we can talk then, but @sharpphyl needs it now!

**Comment by sharpphyl** [comment]
Thanks, Teresa.  Yes, the request is just for Inverts unless the AWG thinks it should be open to everyone.  Only a few of our volunteers will be using these fields.  Can it be set up so that we have to turn it on when we customize the data entry form and that way it won't disturb the other invert collections and our volunteers who don't deal with fossil specimens.

**Comment by dustymc** [comment]
Geology should be on for Inv collections - hard-reload to see it.

**Comment by sharpphyl** [comment]
Yes, thank you.  Geology is turned on for Inv collections.  We had to turn it off in "customize" data entry for our volunteers who don't need it.  

 @mvzhuang @anna-chinn may need to also turn it off if they don't need it.

**Comment by sharpphyl** [comment]
I'm reopening this issue because we're running into a bug.  We appreciate having access to Geology.  It's very helpful for the volunteers who are databasing fossil specimens.  We have turned it to "hide" in the "customize" feature of the data entry form for those who only deal with extant species.  This closes the fields although it's still visible which is fine.

If we complete and save an entry, then reopen it from the bulkloader to make changes, the locality fields start out ok although it seems to reopen Geology.  We can make small changes in the locality and save them without a problem but if we depick the locality to make edits or change the geolocation, we get this

![Screen Shot 2019-10-20 at 10 59 51 AM](https://user-images.githubusercontent.com/15368365/67163622-46009800-f32e-11e9-9c6f-5deefa07599d.png)

 and when we save it, we get this

![Screen Shot 2019-10-20 at 11 00 05 AM](https://user-images.githubusercontent.com/15368365/67163608-29fcf680-f32e-11e9-9d03-48c0a19d5cc5.png)

then it demands that we complete all the geology fields.  

![Screen Shot 2019-10-20 at 11 00 30 AM](https://user-images.githubusercontent.com/15368365/67163641-7e07db00-f32e-11e9-9b51-97a4a2b83217.png)

There are various workarounds but I hope the bug can be eliminated so that when we "hide" the geology fields they don't reopen from the bulkloader and require content.

**Comment by sharpphyl** [comment]
It's been almost a month and I know this probably isn't high priority, but is it possible to address this bug?  Right now, if we open a record from the bulkloader, depick the locality to make changes, we can't save it without filling in all six Geol. Att. fields, then delete them all one-by-one.  It works but it's an irritation to all our data entry volunteers - mostly me.

**Comment by Jegelewicz** [comment]
@dustymc can you take a look at this - it is slowing down data entry.

**Comment by Jegelewicz** [comment]
@sharpphyl - Sorry about this! When stuff like this happens, it is better to open a new issue. Dusty probably never even looked at this because of the issue title and associated labels. I edited the title and pinged him so that it will jump up to the top of his list.

**Comment by dustymc** [comment]
>new issue

Yes, this is a separate thing.

>edited the title 

I ignore that too....

>pinged

I'm on it!

@sharpphyl I created a DMNS:Inv record (please delete it when we're done here, I'll probably forget) and I can't replicate the behavior you describe. 

http://arctos.database.museum/DataEntry.cfm?action=edit&ImAGod=yes&CFGRIDKEY=96826713

Break it and let me know how to do so, please.

**Comment by sharpphyl** [comment]
Thanks for catching this, Teresa.  Next time, I'll open a new issue.

> Break it and let me know how to do so, please.

I couldn't do it with your record, Dusty, (I deleted it) so I created ZC.45000 to show you.  It only happens under very specific conditions.  Here I created a record by choosing a locality 

![Screen Shot 2019-11-16 at 1 07 31 PM](https://user-images.githubusercontent.com/15368365/68998656-9eb24a80-0872-11ea-9a88-609f5128aaa6.png)

I save the record then realize that the address is slightly different from the one on the picked locality.  So I reopen the record from the bulkloader.  I depick the locality and correct the address. 
 
![Screen Shot 2019-11-16 at 1 08 32 PM](https://user-images.githubusercontent.com/15368365/68998672-cd302580-0872-11ea-905f-91d92151b298.png)

In this case, I also changed the geolocation error, but the problem occurs even if I don't change the geolocation.  Before I go to save it, it highlights all the geology fields (even though I have them hidden).  

![Screen Shot 2019-11-16 at 1 08 47 PM](https://user-images.githubusercontent.com/15368365/68998678-f18c0200-0872-11ea-87d7-8a4b71d6b061.png)

When I try to save it, it demands that I enter data into the geology fields.

![Screen Shot 2019-11-16 at 1 08 56 PM](https://user-images.githubusercontent.com/15368365/68998693-16807500-0873-11ea-82b3-34350314f5e6.png)

and highlights the required fields  

![Screen Shot 2019-11-16 at 1 09 06 PM](https://user-images.githubusercontent.com/15368365/68998696-1bddbf80-0873-11ea-9494-98a43a9efa2e.png)

So I have to enter something in each field.

![Screen Shot 2019-11-16 at 1 17 01 PM](https://user-images.githubusercontent.com/15368365/68998732-80991a00-0873-11ea-9532-1b89320b596d.png)

![Screen Shot 2019-11-16 at 1 17 16 PM](https://user-images.githubusercontent.com/15368365/68998743-90b0f980-0873-11ea-857e-d67b0af12503.png)

then I have to delete it


![Screen Shot 2019-11-16 at 1 17 34 PM](https://user-images.githubusercontent.com/15368365/68998745-93abea00-0873-11ea-992a-c6b0e4c29f75.png)

Now it will save the record.

![Screen Shot 2019-11-16 at 1 17 47 PM](https://user-images.githubusercontent.com/15368365/68998748-99a1cb00-0873-11ea-8498-e15c6d5657f1.png)

Let me know if you still can't replicate this.  We occasionally have to correct (depick and redo) localities before I approve and upload records, so I run into this fairly often as do other volunteers.

Thanks!

**Comment by sharpphyl** [comment]
@dustymc Has this fallen behind the invisible cloak again?  Or maybe it's a bigger issue to correct than I thought it might be.  Is the above explanation sufficient?

**Comment by dustymc** [comment]
@sharpphyl if "occasionally" can wait for postgres, it'll be a lot easier for me to deal with. If it can't then this needs AWG prioritization and I can figure it out in the current split environment.

**Comment by sharpphyl** [comment]
What is the postgres ETA?  We can certainly live with the bug since it only happens under specific circumstances and usually I'm the one who deals with it.

**Comment by dustymc** [comment]
Geology is out, locality attributes are in - closing
