### ISSUE TITLE
Add abundance attribute to Herp Collections

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#1850]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Table**
Attribute_type

**Value**
Add Herp to abundance

**Definition**
A subjective description of the abundance of organisms, conspecific with the cataloged item, at the collecting locality.

**Collection type**
Herp

**Attribute data type**
free-text

**Attribute value**
For categorical attributes, code table controlling value

**Attribute units**
For number+units attributes, code table controlling units

**Part tissue flag**
For new parts, is the part a tissue?

**Other ID BaseURL**
For OtherIDs, URL with which to prepend value (resolvable identifiers only)

**Context**
We have some abundance descriptions of herps in our collections that we'd like to add.

**Priority**
I would like to have this resolved by date: _______12/21/2018

**Comment by Jegelewicz** [comment]
@dustymc can we clear the "inconsistent data" on this term? Let me know what you need.

**Comment by dustymc** [comment]
```
UAM@ARCTOS> select * from ctattribute_type where attribute_type='abundance';

ATTRIBUTE_TYPE
------------------------------------------------------------------------------------------------------------------------
COLLECTION_CDE
---------------
DESCRIPTION
------------------------------------------------------------------------------------------------------------------------
abundance
Bird
A qualitative description of the abundance of birds at a locality, typically used for observational data (e.g., common,
uncommon, very common, etc.).

abundance
Herb
A subjective description of the abundance of organisms, conspecific with the cataloged item, at the collecting locality.


2 rows selected.

Elapsed: 00:00:00.02
UAM@ARCTOS> update ctattribute_type set DESCRIPTION='A subjective description of the abundance of organisms, conspecific with the cataloged item, at the collecting locality.' where attribute_type='abundance';

2 rows updated.
```

**Comment by Jegelewicz** [comment]
Done
