### ISSUE TITLE
Can summarize by include 'count of collection events' and 'count of localities'?

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#1853]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

I use 'specimen summary' taxon searches a lot.

I'd love to be able to get the # of collection events and the # of localities each species/taxon is known from *within the found set*

**Describe the solution you'd like**

One of the fields we can include in the summarize list is 'individual count', which is super useful. A count for collection event and locality would appear/behave in the same manner.

**Describe alternatives you've considered**

Very tedious one-taxon-at-a-time searches & compilation of results.

**Additional context**

**Priority**
I would like to have this resolved by date: ___Jan 1, 2018____

**Comment by ccicero** [comment]
Revising an old topic... I also use this feature a lot, and it would also be very useful to have a specimen summary count by part name (e.g., count of skins or skeletons or whole organisms by taxon).

Also @DerekSikes you can get a summary count by locality, not by events.
