### ISSUE TITLE
Add Agent Activity to Agent Summary view

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#1856]
**Describe the solution you'd like**
When a public user executes a search for Agents and they get the summary page they don't see under Media the "created by agent". Could we get that added to the public agent summary?

So this:
<img width="571" alt="screen shot 2018-12-13 at 12 18 55 pm" src="https://user-images.githubusercontent.com/17605945/50019801-76461000-ff80-11e8-993a-7c9939213342.png">

Will look like this:
![screen shot 2018-12-14 at 9 18 14 am](https://user-images.githubusercontent.com/17605945/50020050-3c293e00-ff81-11e8-9428-aab1e0086a42.png)

Any issues/problems that might raise?

**Comment by dustymc** [comment]
No objections from me.

**Comment by Jegelewicz** [comment]
I like it too.

**Comment by dustymc** [comment]
done
