### ISSUE TITLE
address type: Wikidata

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1859]
**Table**
http://arctos.database.museum/info/ctDocumentation.cfm?table=CTADDRESS_TYPE

**Value**
Wikidata

**Definition**
Wikidata.org URL, e.g., https://www.wikidata.org/wiki/Q927582

**Context**
I talked with Anne Thessen about semantically attribution of Arctos data today. They're working with ORCID, but it doesn't seem likely that ORCID will serve as a universal "agent identifier" - the agent is the only one who can add themselves to the system. Our agent identifiers are not stable. Wikidata does not have those limitations and could serve as a way of unambiguously referencing Agents (and aggregating links to other sources of information about the agent - see the Identifiers section). This could be useful for anything that links to Arctos (like the recent IMLS grant - @mkoo ).

1) add to code table
2) HTML-wrap wikidata links for agent activity
3) add HTML5 datatype control to edit page

**Comment by Jegelewicz** [comment]
Could this also be applied to Taxonomy? Higher Geography?

**Comment by dustymc** [comment]
>also be applied to Taxonomy

Probably not usefully - taxa are anything but individual discrete things, and identifications are hypotheses. 

>Higher Geography

Maybe, but it's implicitly agreeing to let them influence some things. "North America, United States, Wyoming, Park County, Yellowstone National Park" isn't in there (same as Getty). The little seasonal creek behind the farm is. If that's geography (and it sort of has to be if it's in our "authority"), then what precisely isn't? "Something people who use wikidata haven't found yet" isn't really something I'd want to run statistics on. If there's no useful distinction between geography and specloc, then why do we have both?

https://github.com/ArctosDB/arctos/issues/1680

**Comment by dustymc** [comment]
done - someone do something awesome with it please...

**Comment by Jegelewicz** [comment]
Just asked for help with awesoming: https://twitter.com/TJegelewicz/status/1100795175310286850
