### ISSUE TITLE
duplicate items in loan invoice

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1860]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html
When printing an MSB loan invoice, I'm getting one item printed twice on the loan form.

**Describe the bug**
See 2018.26.Bird

**To Reproduce**
Go to Edit Loan, Print MSB Bird Item Invoice from dropdown list.

**Expected behavior**
Not to have duplicate items on the invoice.
![screenshot 2018-12-18 14 51 34](https://user-images.githubusercontent.com/14808196/50185312-ae2cba80-02d4-11e9-8f72-bda547e70a06.png)

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Priority**
I would like to have this resolved by date: _______

**Comment by campmlc** [comment]
Note that the item is not duplicated on the review loan items form:
![screenshot 2018-12-18 14 55 41](https://user-images.githubusercontent.com/14808196/50185492-27c4a880-02d5-11e9-8fb9-62abf3452b93.png)

**Comment by dustymc** [comment]
That is an antique built-in report that isn't being maintained anymore. It really needs moved to the reporter and removed from the codebase.

**Comment by campmlc** [comment]
These duplicates are still happening. How can I get this form moved to the reporter? Is this something you can do, @Dusty? I can't spend a day trying to re-create this form from scratch. 

And just curious, why? Is it because these specimens have more than one occurrence?

**Comment by campmlc** [comment]
OK - found the new report. Can we please delete the MSB Bird Loan Invoice on the loan page dropdown? 
Once that is done I will close the issue.

**Comment by dustymc** [comment]
>delete
Done
>more than one occurrence
yes
