### ISSUE TITLE
New "author role"

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#1863]
**Table**
http://arctos.database.museum/info/ctDocumentation.cfm?table=CTAUTHOR_ROLE

here's another quirk that I'm wondering about that is connected to Agents & to Publications.
I'd like to link this publication (http://arctos.database.museum/publication/10008578) to this agent (http://arctos.database.museum/agents.cfm?agent_id=21280577) because the article is about him. It would be nice to be able to see publications that are written about important people who are part of Arctos. Many of the artists in the UAM:EH and UAM:Art collections (and undoubtedly all of our other collections) are prominent enough to have been written about and we should be able to link to those through the agent record. As of right now, I think we can only do that if they are listed as an author.

Can we create a new Author Role that would be something like "Subject" to indicate they are the subject matter of a publication?

**Comment by Jegelewicz** [comment]
I think this is a good idea.

**Comment by dustymc** [comment]
Sounds reasonable to me.

There is potentially some denormalization or overlap with Media, but Media can replicate most everything so meh/whatever.

This is a very different use of the agent-publication link so a quick AWG discussion to ensure that we're all on the same page could be useful - or just add to the CT and we can discuss if something melts....

**Comment by AJLinn** [comment]
I'll be happy to introduce the topic at the next AWG meeting in case anyone has any comments they'd prefer to discuss live.
Thanks!

**Comment by AJLinn** [comment]
new agent role completed; added documentation, nominally

**Comment by dustymc** [comment]
https://arctos.database.museum/info/ctDocumentation.cfm?table=CTAUTHOR_ROLE would be better renamed to ctpublication_agent_role, but very low priority with no functional implications - closing....
