### ISSUE TITLE
another type of relationship?

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#1864]
**Value**
"compared with" or something simiilar?

**Definition**
Refers to a cataloged item that was compared with another cataloged item for comparison, e.g., for taxonomic identification.

**Collection type**
N/A

**Attribute data type**
free-text

**Attribute value**
N/A

**Attribute units**
N/A

**Part tissue flag**
N/A

**Other ID BaseURL**
N/A

**Context**
I just cataloged two tail feathers from different turkeys collected in different events (New Mexico, Mexico) - and related them to a letter in which the author sent the feathers to Starker Leopold for comparison.  The two feathers were taped together and we kept them that way.  The author of the letter wanted Leopold to compare them and see the one from Mexico was the same subspecies. We currently don't have a way of relating these - closest is "collected with" but they weren't, so something like "compared with" would be comparable but for cases where the objects are from different events.
http://arctos.database.museum/guid/MVZ:Bird:191213
http://arctos.database.museum/guid/MVZ:Bird:191214

**Priority**
I would like to have this resolved by date: next AWG meeting - requires discussion?

**Comment by Jegelewicz** [comment]
I don't see a problem. It would make it easy for the the same comparison to be made by others at a later date.

**Comment by dustymc** [comment]
How (other than the tape) is this different than everything else that's been used together?

Create a loan, a publication for the letter, and optionally a project?

Everything else in http://arctos.database.museum/info/ctDocumentation.cfm?table=CTID_REFERENCES describes the specimen. I'm not thrilled with the idea of introducing something completely different.

**Comment by Jegelewicz** [comment]
> Create a loan, a publication for the letter, and optionally a project?

That would work, just not as direct of a link. How about:

identified by comparison with - Refers to a cataloged item that the specimen was compared with to determine taxonomic identification of the specimen.

if needed, the reciprocal could be

provided comparison for identification of - Refers to a cataloged item that was compared with the specimen for taxonomic identification of the cataloged item.
