### ISSUE TITLE
SPNHC 2019 - Seeking co-presenter(s)

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1865]
I would like to put together a talk for the SY-03 Interconnectedness Of Data Symposium at [SPNHC](https://www.spnhcchicago2019.com/abstract-submission)

> The talks/demos in this series will be about the importance of interconnectedness of collections, and how data can inform connections and uncover relationships.

I'd like to demonstrate how Arctos connects related specimens and is making connections with outside data (GenBank, WoRMS, ORCID?) and to let others know that if they have the ability, they can link to our specimens as well.

I have emailed the symposium organizers for more information.

**Comment by Jegelewicz** [comment]
> Hi Teresa,
> Many thanks for getting in touch -- and keen to hear how you connect those db's!
> 
> Individual talks have 20 minutes (+ time for discussion).  I'm not sure the Data Interconnectedness symposium has a specific day yet, but Janeen Jones (cc'ed) is organizing it.
> 
> Take care,

Kate Webbink

**Comment by Jegelewicz** [comment]
> Hi Teresa,
> 
> The Symposium will probably be either Wednesday or Thursday (May 29-30).  Right now, all Symposiums are scheduled for those 2 days but, if we get an abundance of submissions  we may also add days on Tuesday and Friday of that week.  The talks are 20 minutes, with about 5 minutes for questions.
> 
> I look forward to reading your abstract and if I can provide you with additional information or assistance let me know.
> Best,

Janeen JOnes

**Comment by Jegelewicz** [comment]
> (And abstract submissions are open now through February 9th -- Further info is on the submission form but let us know if you need other details)
> 
> Many thanks!

Kate Webbink

**Comment by KyndallH** [comment]
Emily Braker too! 

Started a google doc folder for this on Arctos shared drive:
https://drive.google.com/drive/folders/1y8WoyTnwys0XD9dykiEtEbxRHBqZmnD3?usp=sharing

**Comment by Jegelewicz** [comment]
Yay! I'll get to work on this next week and schedule a meet-up or two once we have a draft going.

**Comment by Jegelewicz** [comment]
@KyndallH and @ebraker I have sketched out the beginnings of the abstract for this presentation in the Google drive that Kyndall created. I changed the names of the documents, because we are going for the Interconnectedness of Data Symposium. Please take a look and edit/add to it.

Are you two available to meet up Friday, February 1 at 1PM MST to finalize?

**Comment by campmlc** [comment]
Yes

**Comment by KyndallH** [comment]
Thanks for adding that! I can meet on Feb. 1st. I started to edit and will do more next week - looks really good btw!

**Comment by KyndallH** [comment]
Aren is going to join us on this!

**Comment by KyndallH** [comment]
I was just looking at the registration and I realized that this is in a regular session. Do we want it instead in the DemoCamp? And/or do a DemoCamp demonstration on top of this (cause we don't have anything else to do)? :)

**Comment by campmlc** [comment]
If we can do a demo camp, that might be really good for recruiting new
collections.

**Comment by Jegelewicz** [comment]
I would love it if someone would take on a demo camp. It would be nice for us to have more than one Arctos presentation at SPNHC. I chose to try for the connected data symposium because I think we have a lot to offer the community when it comes to "connected-ness". We have other stuff that would be great to demo - publications, projects, tagged field notes, controlled vocabularies. Any of those would make a great demo camp.

**Comment by amgunderson** [comment]
I am going to take on the demo camp, my first thoughts are this, Advanced Collection Management Using Arctos. I would cover media, publications, projects, if there is time I would go over bulk editing features, saved searches/archive results and other functions available from a search result. I'll have a abstract to review at the end of next week.

**Comment by campmlc** [comment]
Yay, Aren! Relationships too?

**Comment by ebraker** [comment]
Apologies! Just now seeing this thread. I've added some edits to the abstract. Happy to help with anything else. I am able to meet Feb 1 any time.

**Comment by amgunderson** [comment]
I have my first draft abstract for the Democamp here, https://drive.google.com/open?id=1qhwFX_HNU3D4n3S5v41Cb806Rex4neoQYkK5g4xFlwA. Make comments or corrections if you you please. It seems ambitious for 20 minutes, I may cut out the media component and go with publications and projects only. Media could be it's own demo I am sure. Any co-authors?

**Comment by KyndallH** [comment]
Still meeting tomorrow Friday, February 1 at 1PM MST? Meet you on Zoom?

**Comment by Jegelewicz** [comment]
Yep!

**Comment by ebraker** [comment]
yes, see you all soon

**Comment by Jegelewicz** [comment]
@amgunderson I made a few suggestions. I do think you will have way too much to cover and I suggest that you really limit the media and just hit on projects, which media can be a part of.

**Comment by ebraker** [comment]
@amgunderson agreed on the step-by-step demo of Media being too much content, but its super easy to point out linked media in records during the presentation. I added edits as well.

**Comment by Jegelewicz** [comment]
https://berkeley.zoom.us/j/363481382 in case anyone needs it!

**Comment by Jegelewicz** [comment]
Thanks everyone for meeting up today! If you need Harvard info: https://mczbase.mcz.harvard.edu/SpecimenSearch.cfm

Also, when possible, I'd like to see us use "**collaborative collections management solution**" rather than "database" or "collection management system". It's on our website, and it is what sets up apart!

**Comment by KyndallH** [comment]
Just went in to correct database to collaborative collections management solution on one of the abstracts and you beat me to it! :)
