### ISSUE TITLE
save fails - edit ID by deletion of 2nd identifier agent

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#1868]
Specimen record with an ID with 2 ID agents. When editing there is a red x next to the 2nd which allows one to delete the 2nd agent. Clicking save after doing this does not save. The 2nd agent is not deleted.

**Comment by campmlc** [comment]
I had a similar problem trying to edit author order in a publication imported using a doi - Arctos randomly re-arranged the order despite the order they were entered in. When I tried to edit the order, it failed. Then when I used this publication to create an ID (as a voucher), and tried to rearrange the author order or delete one in the manage citations tools iwth "no, use author info below", Arctos would not accept the changes and reverted back to the same inappropriate order. 
See https://arctos.database.museum/guid/MSB:Mamm:124820 and 
https://arctos.database.museum/Publication.cfm?action=edit&publication_id=10008582
On the latter page, can we have a way to change author order?

**Comment by dustymc** [comment]
@DerekSikes the problem seems to be a broken JS check, which should be relatively straightforward once I get a development environment.

@campmlc you should file an issue if you want to change something about that.

**Comment by dustymc** [comment]
ref: https://github.com/ArctosDB/arctos/issues/1871 - add drag-drop ordering, replace the JS checks with HTML5 controls.

**Comment by dustymc** [comment]
also: remove ID of Kin as "default"

**Comment by dustymc** [comment]
fixed the critical problem - pushing off complete rebuild to https://github.com/ArctosDB/arctos/issues/2170
