### ISSUE TITLE
Add intestine to to herp collections

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#1869]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Table**
part_name

**Value**
intestine for Herp collections
**Definition**
Clear, complete, non-collection-type-specific definition of the new value.

**Collection type**
Herp and HerpOS

**Attribute data type**
free-text, categorical, number+units

**Attribute value**
For categorical attributes, code table controlling value

**Attribute units**
For number+units attributes, code table controlling units

**Part tissue flag**
yes

**Other ID BaseURL**
For OtherIDs, URL with which to prepend value (resolvable identifiers only)

**Context**
Intestine exists for mammal collections. We have a few specimens where intestine tissue was taken

**Priority**
I would like to have this resolved by date: __01/22/2019_____

**Comment by dustymc** [comment]
The Mamm is flagged as not tissue. Do we want to change it @jldunnum @amgunderson ?

**Comment by campmlc** [comment]
This is not clearcut. Mammals has "gastrointestinal tract (frozen)" or
"gastrointestinal tract (94% ethanol) as a tissue. But "intestine" by
itself may not be. Vicky, were these intestines not preserved first in
formalin?

**Comment by mvzhuang** [comment]
It was tissue taken from the intestine before preservation for a genetic study

**Comment by Jegelewicz** [comment]
How is (was) it preserved? freezing? ethanol? It will be best to record this too if possible.

**Comment by mvzhuang** [comment]
thanks!
