### ISSUE TITLE
Media upload drag and drop not working 

### ISSUE THREAD

**Issue by krgomez** [ArctosDB/arctos#1870]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
When I drag the media I want to upload into the green drag and drop box, the image file is pulled in, looks like it's loading and then nothing happens. It doesn't load. Times out.

**To Reproduce**
1. Go to media - attach/upload media.
2. Drag image file into green upload media box.
3. Nothing happens.

**Expected behavior**
Image should upload but it does not.

**Desktop (please complete the following information):**
 - Mac OS High Sierra 10.13.6
 - Firefox

**Priority**
I would like to have this resolved by date: as soon as possible

**Comment by AJLinn** [comment]
Still not working today.

**Comment by dustymc** [comment]
No, something that I can't readily diagnose until I get the test server back (it melted, TACC is experimenting with an upgrade) is broken.

**Comment by krgomez** [comment]
Any sense of when it might get fixed? Days, weeks?

**Comment by dustymc** [comment]
TACC is trying to minimally provide an update this week. I'll post here when I know more.

**Comment by AJLinn** [comment]
Any news from TACC re: the status of the media tool? We're not going to be able to do our Media webinar on Feb. 12 without being able to show how to upload the files.

**Comment by dustymc** [comment]
I just pinged TACC.

If this isn't resolved by ~the first I'll find an alternate solution for the webinar.

**Comment by dustymc** [comment]
The media loader should now be fixed and patched in.
