### ISSUE TITLE
Mentors (and anyone willing to see lots of email)

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1872]
The quarterly collection reports are going out today, and many of them aren't getting where they need to be.

<img width="642" alt="screen shot 2019-01-10 at 9 58 51 am" src="https://user-images.githubusercontent.com/5720791/50987390-60176b00-14be-11e9-9d98-2e241f212b83.png">

If you are serving as a mentor for new collections, please help them set up collection contacts with good contact information.

If you have appropriate permissions and wish to receive these kinds of notifications, you can add yourself to the DATA_REPORT_EMAIL list under...

<img width="301" alt="screen shot 2019-01-10 at 10 00 09 am" src="https://user-images.githubusercontent.com/5720791/50987498-a4a30680-14be-11e9-910e-54a745279bdd.png">

<img width="342" alt="screen shot 2019-01-10 at 10 03 14 am" src="https://user-images.githubusercontent.com/5720791/50987640-0cf1e800-14bf-11e9-86d4-b16288925426.png">

Or just let me know your email if you'd like to be on the list and I can add it.

**Comment by Jegelewicz** [comment]
I'll try to check in with most recent new collections over the next couple of weeks.

**Comment by Jegelewicz** [comment]
@dustymc is this still an issue or can we close?
