### ISSUE TITLE
tissue flag

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1875]
"Tissueness" is currently built in to part name.

In https://github.com/ArctosDB/arctos/issues/1084 we were unable to define "tissues," and instead reverted to flagging individual parts.

```
whole organism (frozen) - 1
whole organism (glutaraldehyde) - 0
```

https://github.com/ArctosDB/arctos/issues/1460 is going to reduce that to one part name, which will not leave a place for the flag.

https://arctos.database.museum/info/ctDocumentation.cfm?table=CTPART_PRESERVATION has been created for #1460, but I'm not sure it contains the information we used to determine "tissueness" - a subfossil (probably) isn't tissue but might be stored "frozen" for stability reasons, for example. 

https://arctos.database.museum/info/ctDocumentation.cfm?table=CTTISSUE_QUALITY is intended for use on "tissues" (https://github.com/ArctosDB/arctos/issues/1384) and seems the logical place to find this information, but it doesn't seem to get much use.

```
UAM@ARCTOS> select count(*) from specimen_part_attribute where attribute_type='tissue quality'
  2  ;

  COUNT(*)
----------
	 1

1 row selected.
```

If we're going to keep the ability to search for "tissues" (and share only "tissues" with GGBN and etc.), we need a way to define "tissue." Help!

**Comment by Jegelewicz** [comment]
"tissue-ness" is often determined by a combination of part and preservation. How difficult will it be to say that "body" with the preservation "cleared and stained" is not a tissue, but "body" with the preservation "ethanol, 95%" is one?

As for where it should go CTTISSUE_QUALITY might be OK, but maybe what we would probably need is

TISSUE_QUALITY | Documentation
-- | --
not tissue | either the specimen or preservation prevents the part from being used as tissue
0 - unknown | tissue quality has not been assessed
1 - poor | decomposed or very rotten
2 - fair | degraded from decomposition
3 - good | no obvious degradation, multiple freeze thaw events
4 - very good | no obvious degradation, one freeze/thaw event
5 - excellent | no obvious degradation, no freeze/thaw events

**Comment by dustymc** [comment]
I think that's the same thing I suggested. I'm without a test box and not thrilled with doing that "small bit of extra work/complexity" in production, but we may get there...

We're already caching the tissue flag (at the specimen level), so (most) performance shouldn't be a problem.

Lacking better ideas, let's go with things having at least one positive and no negative CTPART_PRESERVATION.is_tissue flags being considered tissues.

I'll need data - I've made a spreadsheet at https://docs.google.com/spreadsheets/d/1vLB4G4tRISqqz--O0RPsAC3r-R_KiDzZpMwHehyZMx0/edit?usp=sharing if anyone wants to provide the flag. 

Values:

1: makes tissue
0: forces not-tissue (overrides (1))
NULL: nothing to do with tissue
anything else: ignored/dropped on import

**Comment by dustymc** [comment]
@campmlc are subsamples tissues?

**Comment by dustymc** [comment]
TODO: UAM@ARCTOS> select part_name from ctspecimen_part_name where part_name not like '%(%' and is_tissue=1 group by part_name order by part_name;

with collection and count

**Comment by Jegelewicz** [comment]
After above, collections need to add preservation method to the parts.

**Comment by campmlc** [comment]
Yes, subsamples of tissues are tissues.

**Comment by dustymc** [comment]
Here are parts flagged as tissues which don't have any parenthetical/preservation data.

```

set linesize 100 
column part_name format a50 
column guid_prefix format a30 
column c format 99999 

select
  specimen_part.part_name,
  guid_prefix,
  count(distinct(specimen_part.COLLECTION_OBJECT_ID)) c
from
  collection,
  cataloged_item,
  specimen_part,
  ctspecimen_part_name
where
  collection.collection_id=cataloged_item.collection_id and
  cataloged_item.collection_object_id=specimen_part.derived_from_cat_item and
  specimen_part.part_name=ctspecimen_part_name.part_name and 
  is_tissue=1 and
  ctspecimen_part_name.part_name not like '%(%' 
group by
  specimen_part.part_name,
  guid_prefix
order by
    specimen_part.part_name,
    guid_prefix
;

PART_NAME					   GUID_PREFIX			       C
-------------------------------------------------- ------------------------------ ------
DNA						   MSB:Mamm			     797
DNA						   MVZ:Herp			       2
DNA						   MVZ:Mamm			     526
DNA						   UAM:Mamm			      37
DNA extraction					   KWP:Ento			     412
DNA extraction					   MSB:Bird			      44
DNA extraction					   MSB:Mamm			     803
DNA extraction					   UAM:Ento			    4260
DNA extraction					   UAM:Env			     335
DNA extraction					   UAM:Mamm			      18
blood						   MSB:Herp			      25
blood						   MSB:Mamm			    1906
blood						   MVZ:Herp			      16
blood						   UAM:Mamm			     255
blood						   UTEP:Herp			     101
blood plasma					   MSB:Mamm			       1
brain						   MSB:Mamm			       4
brain						   UTEP:Herp			      34
cheek pouch					   MSB:Mamm			       2
cyst						   MSB:Mamm			       4
ear clip					   DMNS:Mamm			       1
ear clip					   MSB:Mamm			      64
filter paper					   UAM:Env			     383
fin clip					   MSB:Fish			      18
fruit						   UTEP:Herb			      10
heart						   DMNS:Bird			       4
heart						   DMNS:Mamm			       8
heart						   MSB:Bird			     546
heart						   MSB:Mamm			     429
heart						   MVZ:Bird			       1
heart						   UAM:Bird			       2
heart						   UAM:Mamm			      10
heart						   UTEP:Herp			      66
heart						   UWYMV:Bird			       1
heart, kidney					   DMNS:Mamm			      38
heart, kidney					   MSB:Mamm			      21
heart, kidney, liver				   DMNS:Mamm			       6
heart, kidney, liver				   MSB:Mamm			       2
heart, kidney, liver, lung, spleen		   DMNS:Mamm			       1
heart, kidney, liver, lung, spleen		   MSB:Mamm			       6
heart, kidney, liver, spleen			   MSB:Mamm			       2
heart, kidney, liver, spleen			   UAM:Mamm			       2
heart, kidney, lung				   MSB:Mamm			     117
heart, kidney, lung, spleen			   MSB:Mamm			     337
heart, kidney, lung, spleen			   UAM:Mamm			       1
heart, kidney, spleen				   MSB:Mamm			       4
heart, liver					   MSB:Mamm			       4
heart, liver					   UTEP:Herp			      14
heart, liver, muscle				   UTEP:Herp			      61
heart, lung					   MSB:Mamm			       4
heart, lung, spleen				   MSB:Mamm			       7
heart, lung, spleen				   UAM:Mamm			       4
heart, spleen					   DMNS:Mamm			      37
heart, spleen					   MSB:Mamm			      15
heart, spleen					   UAM:Mamm			       5
kidney						   DMNS:Mamm			      10
kidney						   MSB:Mamm			     394
kidney						   UAM:Mamm			      11
kidney						   UTEP:Herp			      19
liver						   DMNS:Bird			       6
liver						   DMNS:Mamm			      47
liver						   MSB:Bird			      27
liver						   MSB:Mamm			     792
liver						   UAM:Bird			       2
liver						   UAM:Mamm			      19
liver						   UTEP:Herp			      62
lung, kidney, spleen				   MSB:Mamm			     693
mammary tissue					   UAM:Mamm			       1
muscle						   DMNS:Mamm			      44
muscle						   MSB:Mamm			    2261
muscle						   UAM:Mamm			      37
muscle						   UTEP:Herp			      32
muscle, spleen					   MSB:Mamm			       1
pinned tissues					   KNWR:Ento			       1
pinned tissues					   KWP:Ento			       2
pinned tissues					   UAM:Ento			       2
seed						   CHAS:Teach			      12
seed						   UAM:ES			      28
seed						   UTEP:Herb			     950
skin clip					   DMNS:Mamm			      10
skin clip					   MSB:Mamm			     962
skin clip					   MVZ:Mamm			      28
skin clip					   NMU:Mamm			     422
spleen						   MSB:Mamm			     370
spleen						   UAM:Mamm			      11
spleen, lung					   MSB:Mamm			     122
swab, dorsal					   MSB:Herp			       1
swab, dorsal					   MVZ:Herp			       8
swab, dorsal					   UWBM:Herp			     135
tissue						   DMNS:Bird			      20
tissue						   DMNS:Mamm			      76
tissue						   KNWR:Ento			      30
tissue						   KNWRObs:Fish 		       2
tissue						   MLZ:Bird			     306
tissue						   MSB:Bird			     149
tissue						   MSB:Fish			      10
tissue						   MSB:Mamm			      75
tissue						   MVZ:Bird			       1
tissue						   MVZ:Mamm			      58
tissue						   NMU:Bird			       1
tissue						   UAM:Ento			      17
tissue						   UAM:Mamm			     182
tissue						   UCM:Mamm			       2
tissue						   UMZM:Bird			       1
tissue						   UMZM:Mamm			      16
tissue						   UTEP:Herp			     326
tissue						   UTEP:HerpOS			       1
tissue						   UWBM:Herp			       1
toe						   UTEP:Herp			      21
toe pad 					   DMNS:Bird			       5
toe pad 					   MVZ:Bird			       1

111 rows selected.


```

**Comment by dustymc** [comment]
Summary for tissue-ness:

- parts without preservation data, or with preservation data without a tissue flag, are not tissues.
- parts with one or more preservation terms marked as tissue-causing (1) are tissues, except...
- parts with one or more preservation terms marked as tissue-preventing (0) are never tissues

If any part of a specimen is a tissue under those criteria, the specimen will be marked as having tissues in FLAT and searches for tissues will locate it. 

Our old/current definition involves "collected with genetics in mind" - we have not found a way to incorporate that here.

There was some discussion regarding whether subsamples are tissues. I don't think that can be a consideration in a model where any part can be divided for any reason - eg, splitting a tube to insure against freezer failure would produce a "subsample."

**Comment by campmlc** [comment]
I will tackle the MSB samples without preservation.
We need subsamples of tissues to be tissues because in many cases they are
returned and re-loaned, and in some cases subsampled again (DNA
extractions).

**Comment by KyndallH** [comment]
So if we have subsampled tissue flagged as a tissue, it comes up on a search when someone clicks the "requires tissue" even if it is not available to loan out? Are tissues with the disposition of "used up" or "on loan" come up on a tissue required search?

Yes on Mariel's "We need subsamples of tissues to be tissues because in many cases they are
returned and re-loaned, and in some cases subsampled again (DNA
extractions)." 

This came up today hence why I looked and found this thread. The current way we have it is subpar. For example, this muscle was loaned and extracted for loan 2010.005. Those DNA extractions were loaned out for loan 2013.001 but it doesn't reflect it - it looks as if we re-sampled from the tissue vial a DNA extraction. The only reason I know the hierarchy is because I have it in a spreadsheet.

<img width="1542" alt="Screen Shot 2019-03-22 at 10 07 39 AM" src="https://user-images.githubusercontent.com/16887896/54844031-b22cf780-4c8a-11e9-9b60-ec8b8fd080c4.png">

**Comment by dustymc** [comment]
I can add disposition - is it only those two that prevent "tissueness"?

http://arctos.database.museum/info/ctDocumentation.cfm?table=CTCOLL_OBJ_DISP

I think unlimited levels of subsamples is fairly new, so that may be a symptom of the old UI. The current forms allow subsampling sumsamples.

**Comment by KyndallH** [comment]
I can't seem to subsample a subsample. When I click to add parts to a loan I get:
<img width="828" alt="Screen Shot 2019-03-22 at 11 27 11 AM" src="https://user-images.githubusercontent.com/16887896/54848214-9b3fd280-4c95-11e9-958b-59ccdfd7ac3e.png">


Though I have more parts:
<img width="1559" alt="Screen Shot 2019-03-22 at 11 28 04 AM" src="https://user-images.githubusercontent.com/16887896/54848217-9da22c80-4c95-11e9-8760-14667d69ec74.png">

**Comment by KyndallH** [comment]
Those dispositions make it still tissueness, just changes it loaneness.

For that, I'd say: discarded missing, on loan, transfer of custody, used up.

But while I don't want someone to request something that is on loan, I need to be able to loan what is "on loan". As in researcher X is done and wants another researcher to have their extractions so I create another loan and loan out that subsample/DNA extraction.

**Comment by dustymc** [comment]
New issue - the loan-adder-thing probably needs an update. https://github.com/ArctosDB/arctos/issues/1999

I have a function that determines if a specimen has tissues or not. It feeds....

<img width="176" alt="Screen Shot 2019-03-22 at 12 37 34 PM" src="https://user-images.githubusercontent.com/5720791/54848712-499c4580-4c9f-11e9-91da-e38093de7a40.png">

and that's it.

There is no "available for loan" (and probably can't be - that's between borrowers and curators).

**Comment by KyndallH** [comment]
So requires tissue includes anything we call a tissue regardless of disposition. And if you don't care about loan ability, then it is pointless to include disposition in "tissueness". BUT that means I'm going to continue to get requests for tissues that are "missing", "used up", or "on loan". It really isn't between the borrowers and curators but falls on the shoulder of the collection managers to sort through loan requests, notify all parties involved that the tissue they requested actually is "used up" and suggest alternatives. At least, that is my reality.

**Comment by campmlc** [comment]
Agree. Samples with these dispositions shouldn't go to GGBN. Possible?

**Comment by dustymc** [comment]
>equires tissue includes anything we call a tissue regardless of disposition. 

Currently yes. It's easy to change, but will take a couple days to update.

"Curators" implicitly includes "... or their representatives." I know who's actually digging through freezers....

WAY back in the dark ages we had a "shopping cart." Not much technical problem to bring it back, but someone (everyone?!) didn't like it.

>GGBN

That's not related to this, but yea we can filter whatever there. (And why not send 'on loan' to GGBN?)

**Comment by KyndallH** [comment]
Totally off topic but since you brought it up - the UAM mammal folks have talked about "shopping cart" and how that would make it easier for us. The people could create their loan request in Arctos with the project information, add the specimens they are interested in (like a saved search), and we could approve/modify it as needed. Roll right into the actual loan. Right now, all the request forms are saved a separate drive but would be awesome to have all the data in one place. One day maybe.

**Comment by campmlc** [comment]
Agree. I currently have to have a separate Dropbox to manage all the loan
requests which were generated by Arctos searches and then downloaded and
usually transformed into a pdf. Then I have to translate/copy the list back
into csv and reupload to Arctos to find the specimens to add to the loan.

**Comment by dustymc** [comment]
There's a new column which needs data in CTPART_PRESERVATION.

TODO:

- complete https://github.com/ArctosDB/arctos/issues/1460
- add the new column to the viewer
- remove tissue_fg from specimen part
- switch code in getIfTissues to implement
- somehow trigger changes in tissue_fg to FLAT

**Comment by dustymc** [comment]
@ccicero @ArctosDB/arctos-working-group-officers https://github.com/ArctosDB/arctos/issues/1875#issuecomment-473036290 is what will determine "tissueness" whenever we change to that model. (It's currently the arbitrary flag in https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name.) So given any part - part name is not completely irrelevant for "tissueness" - and some example values from https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_preservation


```

     part_preservation     | tissue_fg 
---------------------------+-----------
 sectioned                 |          
 arsenic                   |         0
 frozen                    |         1
```

This will happen:


|part|preservation|result|explanation|
|--|--|--|--|
|anything|sectioned|not tissue|no part is "natively" tissue; only preservation can cause "tissueness," and this one has no effect on "tissueness"|
|anything|frozen|is tissue|has a tissue-causing preservation and nothing that denies "tissueness"|
|anything|arsenic|not tissue|arsenic denies "tissueness" - a part in arsenic has DNA destroyed or something of the sort|
|anything|arsenic<br>frozen|not tissue|arsenic denies "tissueness" - a part in arsenic has DNA destroyed or something of the sort, no matter what else has happened|
|anything|frozen<br>sectioned|is tissue|has a tissue-causing preservation and "sectioned" does not negate|
|anything|frozen<br>frozen<br>frozen<br>frozen<br>arsenic<br>frozen<br>frozen<br>frozen<br>frozen|not tissue|Order isn't important, the number of determinations isn't important, the only consideration is the presence of a tissue-denying preservation|

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_preservation should be updated for this to function correctly. Eg DMSO/EDTA claims to be neutral, but I suspect it's actually a decent indicator of "tissueness."

Note also that "tissueness" is a derived attribute of the catalog record; it is (or should/could be) possible to search preservation directly without considering our interpretation.

I think there are probably legacy values that come from trying to do too much in a part string in the code table as well - eg, I don't see how "ethanol-fixed" is useful, when both "ethanol" and "whatever comes next" are possible.

Suggestions regarding the vocabulary are appreciated as well - the model is above, it's functionally a nullable binary, I'm not sure that current terminology does a good job of expressing the functionality.

**Comment by campmlc** [comment]
Please see google doc for updated tissue was from yesterday. EDTA/DMSO and
other buffers are definitely tissueness.
https://docs.google.com/spreadsheets/d/1L5VA3E75u4GFMNHbtHNCmb-3CLJLpQ2GBQBtp3CmDz4/edit?usp=drivesdk

**Comment by dustymc** [comment]
See https://github.com/ArctosDB/arctos/issues/3667#issue-921798361 - are there objections to allowing disposition

`` deaccessioned, discarded, missing, transfer of custody, and used up``

to deny tissueness?

**Comment by campmlc** [comment]
The only one that gives me pause is transfer of custody, in case we want to
refer people to the transferred to institution.

**Comment by KyndallH** [comment]
@campmlc The only institution that has our tissues, is you. :) And we all know, they'll just request them from you and me without realizing they are the same specimen. 

But I'm okay with leaving the transfer of custody as tissuey.

**Comment by Jegelewicz** [comment]
> Please see google doc for updated tissue was from yesterday. EDTA/DMSO and
> other buffers are definitely tissueness.
> https://docs.google.com/spreadsheets/d/1L5VA3E75u4GFMNHbtHNCmb-3CLJLpQ2GBQBtp3CmDz4/edit?usp=drivesdk

Changes made to the code table - suggest any new changes be made there.

**Comment by dustymc** [comment]
https://github.com/ArctosDB/PG_DDL/blob/master/function/has_tissue.sql will calculate tissueness in next release.
