### ISSUE TITLE
Ability to download .csv of container leaf nodes

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1876]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
I would like to be able to download a .csv of the parts found in a container.

**Describe alternatives you've considered**
Copy/paste, but when there are a lot of parts, it isn't feasible.

**Additional context**
http://arctos.database.museum/allContainerLeafNodes.cfm?container_id=18189047

**Priority**
I would like to have this resolved by date: 2019-02-01

**Comment by dustymc** [comment]
Suggest we add a "find all parts in barcode" option to http://arctos.database.museum/findContainer.cfm and download from there.

**Comment by Jegelewicz** [comment]
This spins but never seems to offer any results. What do we need and what alternatives are available?

**Comment by Jegelewicz** [comment]
It probably takes so long because it is also looking up the identification - if we left that off, would it run faster? Would it make this less useful? (IDs can be looked up with record search if needed) Or could we offer the addition of identifications as an option rather than a requirement?

**Comment by Jegelewicz** [comment]
Also this report doesn't show the barcodes? Seems like that would be good to have....

**Comment by dustymc** [comment]
It's more than identification. The query you're trying to run takes 28 seconds in the DB, would probably take at least that to transmit, and then will probably eat your browser. Once that's done, it's running 72589 more queries to get other stuff that's been requested, which of course has little hope of completing.

I still sorta think there's a need for two forms, but I'm also not clear on what you're trying to do so I can't know how it can best be done.

We need a plan; arbitrarily changing arbitrary things is not sustainable.

https://github.com/ArctosDB/arctos/issues/3632

**Comment by campmlc** [comment]
The plan is to have useable tools that enable users to figure out what is
in a container, what is linked to parts and what isn't. This is a
fundamental need.

**Comment by campmlc** [comment]
Any way we can request this information be sent via email once the search completes so we are not dependent on the browser? Having sci name is helpful, and helps resolve problems at a glance, but I could live without it if necessary. We used to have this functionality in Oracle. What broke?
I still need to be able to download a csv of all barcodes from a container, with parts or not.

**Comment by dustymc** [comment]
> via email once the search completes

I don't currently have any mechanism that could support that, but like everything else if you'll let me know what you want and how you want to get there in sufficient detail I can build you a file, and maybe even turn that into something in the UI.

>in Oracle. What broke

https://github.com/ArctosDB/internal/issues/27#issuecomment-512071298

Oracle having very good recursive capabilities vs. postgres having more rudimentary was brought up very early in the discussions that lead to where we are now. Nothing broke, we're not paying for Oracle and so we don't have some of the magic that paying for Oracle provides.

That said, there's no way Oracle on the hardware we had would have done what's now being asked either. We're still continually increasing the demands (which is awesome) but without increasing the resources (which isn't so great).

**Comment by Jegelewicz** [comment]
Closing as duplicate of #4140
