### ISSUE TITLE
Add parts to Herp collection

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#1877]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Table**
specimen_part_name

**Value**
Proposed new value
new storage conditions:
brain (lysis buffer)
head (formalin)

existing parts in Mamm:
karyotype

**Definition**

brain (lysis buffer) - brain tissue preserved in unknown concentration of lysis buffer for the purpose of breaking open cells for use in molecular biology experiments that analyze the compounds of the cells

head (formalin) - decapitated head stored in unknown concentration of formalin

karyotype - slide of cells arrested after cell division for the study of the number and appearance of chromsomees

**Collection type**
Herp

**Part tissue flag**
tissue flags needed:
brain (lysis buffer)

**Context**
part storage conditions currently in the UTEP herp collections that aren't in the code tables.

**Priority**
I would like to have this resolved by date: _______1/28/2019

**Comment by Jegelewicz** [comment]
Done.

However, I added your definition of karyotype to "karyotype (slide)" and for "karyotype" used only "cells arrested after cell division for the study of the number and appearance of chromsomes" and added both parts to Herp collections.
