### ISSUE TITLE
search on attribute fails

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#1879]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

I entered search criteria for specimen attribute and the search fails to find specimens with those attributes

**To Reproduce**

Specimen record search form -> 'specimen record' section

choose 'total length' & then enter '3'

in attribute remarks enter 'greater'

**Expected behavior**

This should find this record (among many others) http://arctos.database.museum/guid/UAM:Ento:288536

**Screenshots**

![screen shot 2019-01-16 at 12 18 37 pm jan 16 19](https://user-images.githubusercontent.com/9099827/51279107-e2a19e00-1988-11e9-8ba5-af3d67a979b8.jpg)

**Desktop (please complete the following information):**
 - OS: mac os 10.13.6
 - Browser: Firefox

**Additional context**

**Priority**
I would like to have this resolved by date: __asap, need these data _____

**Comment by dustymc** [comment]
You are entering "greater than" in part remarks, which doesn't match anything.

There's no way to search attribute remarks in the UI. There's still some old semi-deprecated code hanging around, so this should work:

http://arctos.database.museum/SpecimenResults.cfm?accn_number=osf&attribute_remark=greater%20than&attribute_type_1=total%20length&attribute_value_1=3

In general, searches against free-text data cannot be trusted. In particular, there's a "lesser" in these data.

```
UAM@ARCTOS> select distinct ATTRIBUTE_REMARK from attributes where COLLECTION_OBJECT_ID in (select collection_object_id from flat where accession like 'UAM-2014.17-OSF-Ento');

ATTRIBUTE_REMARK
------------------------------------------------------------------------------------------------------------------------

less than
greater than
Automated insertion from agent merger process - Julie Hagelin --> Julie C. Hagelin for collector role collector
lesser than (actually >3mm but trap method confusion requires we mark these as <3mm so they are skipped for OSF data)
```

Maybe these data would be better entered like the fish-folks do, "minimum total length" and "maximum total length" or similar.

http://arctos.database.museum/info/ctDocumentation.cfm?table=CTATTRIBUTE_TYPE&coln=Fish
