### ISSUE TITLE
genbank contact

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1881]
I am currently the only active Arctos GenBank contact, and I think things fall through the cracks in my inbox. Would anyone like to receive emails from them? It's mostly monthly reports (which don't line up very well with our traffic patterns...), but there are occasional problem alerts and such.

**Comment by campmlc** [comment]
Yes, please add me in.
Mariel

**Comment by Jegelewicz** [comment]
Could you add in the arctos.treasurer@gmail.com account? Then if there are reports I can save them to the Google Drive and notify people....

**Comment by dustymc** [comment]
Added by GB.
