### ISSUE TITLE
Error - no access to child container

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1885]
I am trying to add barcodes to parts and get this error:

An error occurred while processing this page!
Error Executing Database Query.
[Macromedia][Oracle JDBC Driver]ORA-20000: FAIL: You do not have access to the child container ORA-06512: at "UAM.MOVEPARTTOCONTAINER", line 73 ORA-06512: at line 1

The record number is MSB:Bird:25300, the part is "heart, liver (frozen)"

I should have access to all MSB Bird records as well as the barcode, which is A5E6G

What gives?

**Comment by dustymc** [comment]
The part-container was UAM, which makes me suspect someone with scary access had a cat wandering around on their keyboard or similar...

It's MSB now.

**Comment by campmlc** [comment]
Dusty, any way we can find all UAM part-containers at MSB and convert them? 

Are there DGR part-containers?

**Comment by Jegelewicz** [comment]
There's a whole list, cause I just came across another A6J4C

**Comment by Jegelewicz** [comment]
I left my data in the part bulkload tool. I'm guessing all of these have the same problem.

**Comment by Jegelewicz** [comment]
BTW that barcode (A6J4C) says it belongs to MSB, but I get the same error when attempting to add it to MSB:Bird:25293

**Comment by Jegelewicz** [comment]
I'm guessing that these were uploaded by someone with supreme power back in 2006 who placed the parts in UAM when they should have been MSB. Can you find and fix all such problems?

![image](https://user-images.githubusercontent.com/5725767/51565014-06178d80-1e4e-11e9-8452-56874a16628f.png)

**Comment by dustymc** [comment]
>barcode (A6J4C) 

That's the parent - the child is the part-container (in your screenshot).

There were 32240 of these - I flipped them to MSB.
