### ISSUE TITLE
update global settings

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1887]
the UI is missing at least s3 info - add it, make sure everything else is there.

**Comment by dustymc** [comment]
UI needs GMAP_API_KEY_INTERNAL,GMAP_API_KEY_EXTERNAL

Other google stuff (exc. analytics) can be dropped from the table and UI

**Comment by dustymc** [comment]
Done - @mkoo you can manage API keys in manage/meta/global now

**Comment by mkoo** [comment]
thanks!
