### ISSUE TITLE
Add Inv to the collections using Part Name "fossil"

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#1888]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Table**
Add to code table https://arctos.database.museum/info/ctDocumentation.cfm?table=CTSPECIMEN_PART_NAME

Specifically the line:   fossil | Fish | no

**Value**
Add Inv to the list of collections using the name "fossil."

**Definition**
"Fossil" exists as a part name already for Fish.  Add Inv to the list of collections using this name

**Collection type**

fossil | Fish | no

**Context**
We have a variety of Invertebrate fossils (corals, barnacles, tests) that don't fit the "shell (fossil)" definition.  

**Priority**
I would like to have this resolved by date: January 29, 2019

**Comment by Jegelewicz** [comment]
Done

**Comment by sharpphyl** [comment]
Thanks.
