### ISSUE TITLE
Report clone handler not working

### ISSUE THREAD

**Issue by dperriguey** [ArctosDB/arctos#1891]
I'm using the Arctos report builder. I haven't used it in a while. I am just trying to use our old label "UNM_ES_label_1 (UNM_ES_test_2.cfr". I used this before with no problem. Now I get this error:

![image](https://user-images.githubusercontent.com/32556913/51944736-109bcf00-23da-11e9-94b0-e3ef61ff48be.png)

I'm attributing this to cloning a handle in the SQL and not having any idea what the code really meant or not using it in a while. There are a few things in the SQL that look possibly unnecessary, but I remember trying to manipulate things last summer and not getting it to work properly. So, I left most of the handle alone and made sure I could get geology attributes in the report with success. Now when I try to clone any handle I get this error:

![image](https://user-images.githubusercontent.com/32556913/51945108-ee568100-23da-11e9-94d5-859329a5ace0.png)

 - Using Windows 10
 - Chrome Browser
 - Version 72.0.3626.81

**Priority**
I would like to have this resolved by date: 2019-02-1
Or at least looked at by this date. I'm sure it's just my SQL illiteracy.

**Comment by campmlc** [comment]
Hi Dustin,
Did you copy the sql from somewhere else? Any modifications to the label
since the last time you used it?

**Comment by dperriguey** [comment]
Hey Mariel, 
I did copy the SQL from somewhere else within Arctos from: DMNS_Marine_Invertebrates.
I didn't make any modifications since I used it last July. 
If I try to clone any handler, I get that second error.

**Comment by campmlc** [comment]
Yes, I remember having similar problems with cloning handlers last time I
used it.. Dusty?

Dustin, try copying and re-pasting the SQL from the same source? Don't
clone.

**Comment by dperriguey** [comment]
Ok. So it doesn't like anything to do with date_ended_date or date_began_date and neither do I. It's not a useful thing for me anyway. I just got it to work by deleting that stuff. 

The Test SQL is calling those "invalid identifiers". Maybe the language got modified in Arctos or it doesn't like something else I'm doing. Anyway, I got it to work without the redundant stuff.

**Comment by dustymc** [comment]
Yea, that was a "temporary" field that should not have been used in a report. It's a good idea to try the thing you intend to borrow from before cloning it.
