### ISSUE TITLE
SELECT default option should be NULL

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1892]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
The Part Attribute preservation table defaults to Alsever's solution. Can we have the default for this and for any dropdown in Arctos be null? Having a set default that must be changed results in repeated error.

**To Reproduce**
1. Go to '...' Add part attribute in Edit parts from Specimen detail
2. Click on '....'create new part attribute
3.  See error: Alsever's solution is autofilled

**Expected behavior**
All dropdowns should have null value as default

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] chrome

**Additional context**

**Priority**
I would like to have this resolved by date: ____asap___

**Comment by dustymc** [comment]
edited title from Remove Alsever's solution as default part attribute preservation
