### ISSUE TITLE
loan: NULL return_due_date

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1893]
Loan return due date is null, which for the sake of eg, overdue loan reports I can only interpret as "never" - those loans will never be reported as being overdue. Is that by design? Here's NULL return date by collection.

```
select
	guid_prefix || ' @ ' || count(*)
from
	loan,
	trans,
	collection
where 
	loan.transaction_id=trans.transaction_id and
	trans.collection_id=collection.collection_id and
	loan.RETURN_DUE_DATE is null 
group by
	guid_prefix
order by
	guid_prefix
;
GUID_PREFIX||'@'||COUNT(*)
------------------------------------------------------------------------------------------------------------------------
CHAS:Mamm @ 14
DGR:Bird @ 62
DGR:Mamm @ 592
DMNS:Bird @ 14
DMNS:Mamm @ 31
KNWR:Ento @ 86
KNWR:Herb @ 3
KWP:Ento @ 1
MLZ:Bird @ 14
MLZ:Mamm @ 6
MSB:Bird @ 128
MSB:Fish @ 5
MSB:Herp @ 8
MSB:Mamm @ 828
MSB:Para @ 12
MVZ:Bird @ 475
MVZ:Egg @ 10
MVZ:Herp @ 987
MVZ:Hild @ 2
MVZ:Mamm @ 720
NMU:Mamm @ 10
UAM:Arc @ 158
UAM:Art @ 7
UAM:Bird @ 2
UAM:EH @ 36
UAM:ES @ 151
UAM:Ento @ 21
UAM:Fish @ 26
UAM:Herb @ 98
UAM:Herp @ 10
UAM:Inv @ 5
UAM:Mamm @ 938
UAMb:Herb @ 7
UCM:Bird @ 3
UCM:Fish @ 1
UCM:Herp @ 4
UCM:Mamm @ 8
UMNH:Herp @ 2
UMNH:Mamm @ 7
UTEP:Bird @ 1
UTEP:ES @ 8
UTEP:Ento @ 1
UTEP:Herb @ 1
UTEP:Herp @ 5
UTEP:Mamm @ 1
UTEP:Teach @ 1
UWBM:Herp @ 3
UWYMV:Bird @ 1

48 rows selected.
```

**Comment by anna-chinn** [comment]
Most of ours are either tissue consumable loans or in-house loans for specimens on permanent exhibit. How are others dealing with these kinds of things? Are folks using due dates as a prompt to ask borrowers for sequences, or as a reminder to check in on specimens on exhibit?

**Comment by dustymc** [comment]
A consumable loan should result in something being "returned" - identifications, citations in publications, an explanation from the borrower regarding the lack of those things, whatever. When that happens, status should be changed to not-open.

A long-term loan might require some sort of periodic communication, which might prompt resetting the due date.

With a due date, I can send notifications for that sort of thing.

I don't see a use case where a forever-open loan would be appropriate, but it's in the model so someone may have at some point.

**Comment by campmlc** [comment]
Is there a way to close a loan and have the option of choosing to set
disposition back to "in collection" or "used up" from within the main loan
page? That would be awesome. I know we can do that from review loan items,
but that is an extra step that is never done. If I click "closed", can we
have a pop up to choose what disposition to set for all specimens in the
loan?

**Comment by dustymc** [comment]
Technically not much problem, although I'm always a little hesitant to change things you can't see. I'm not sure how that relates to requiring (or not) due date though?

**Comment by campmlc** [comment]
For consumable tissue loans, we have never included a due date. I do,
however, leave the loan open until we hear back regarding citations. I
suppose having a reminder once a year of outstanding loans might be
helpful, but I don't want to have to waste time going in and extending due
dates to avoid annoying emails.

**Comment by AJLinn** [comment]
> For consumable tissue loans, we have never included a due date. I do,
however, leave the loan open until we hear back regarding citations.

This is the same approach I use for media loans, where I'm documenting the transfer of a digital photo file for publication that I do not expect back. I keep it open usually until I get my complimentary copy of the publication, which is a standard condition of use for images of objects in our collection. I would also not want to extend those, though a once a year notice could be helpful for jogging my memory to check in with authors.

**Comment by dustymc** [comment]
>avoid annoying emails

You could close the loan, or we could add a "partially closed" status that doesn't trigger notifications. Not supplying a due date seems like a very cryptic approach to this.

The "meh, maybe they'll send something eventually" outlook here seems to strongly contradict https://github.com/ArctosDB/arctos/issues/1448 - I'm not understanding something important. (Is it related to "maybe we need a 'we don't expect publications' loan type" on that thread?)

I'm not quite getting how this is related to indefinite due dates, maybe for the same reasons I'm not understanding why we seem to have two very different outlooks on loans. Should we add this to the AWG agenda?


Here's a slightly different view of the data. 

```

UAM@ARCTOS> select substr(TRANS_DATE,0,4) || ' - ' || loan_type || ' @ ' || count(*) from loan,trans where loan.transaction_id=trans.transaction_id and LOAN_STATUS='open' and RETURN_DUE_DATE is null group by loan_type,substr(TRANS_DATE,0,4) order by substr(TRANS_DATE,0,4);

SUBSTR(TRANS_DATE,0,4)||'-'||LOAN_TYPE||'@'||COUNT(*)
------------------------------------------------------------------------------------------------------------------------
1973 - consumable @ 1
1974 - returnable @ 1
1975 - returnable @ 1
1980 - in house @ 3
1980 - returnable @ 1
1981 - legacy @ 1
1984 - legacy @ 1
1985 - legacy @ 1
1985 - returnable @ 2
1986 - consumable @ 1
1986 - returnable @ 1
1987 - consumable @ 1
1988 - returnable @ 1
1990 - returnable @ 1
1991 - legacy @ 5
1991 - returnable @ 1
1992 - returnable @ 1
1993 - consumable @ 1
1993 - returnable @ 2
1994 - consumable @ 1
1994 - legacy @ 2
1994 - returnable @ 2
1995 - consumable @ 9
1995 - returnable @ 4
1996 - consumable @ 23
1996 - returnable @ 3
1997 - consumable @ 21
1997 - returnable @ 1
1998 - consumable @ 11
1998 - returnable @ 3
1999 - consumable @ 12
1999 - mixed @ 1
1999 - returnable @ 9
2000 - consumable @ 2
2000 - returnable @ 7
2001 - consumable @ 2
2001 - returnable @ 5
2002 - consumable @ 2
2002 - returnable @ 3
2003 - returnable @ 7
2004 - returnable @ 4
2005 - consumable @ 6
2005 - returnable @ 8
2005 - transfer of custody @ 1
2006 - consumable @ 6
2006 - legacy @ 6
2006 - returnable @ 2
2006 - transfer of custody @ 2
2007 - consumable @ 3
2007 - mixed @ 1
2007 - returnable @ 6
2008 - consumable @ 11
2008 - in house @ 3
2008 - legacy @ 2
2008 - returnable @ 7
2009 - consumable @ 17
2009 - in house @ 1
2009 - legacy @ 3
2009 - return of loan @ 1
2009 - returnable @ 4
2009 - transfer of custody @ 1
2010 - consumable @ 18
2010 - in house @ 1
2010 - returnable @ 9
2010 - transfer of custody @ 2
2011 - consumable @ 14
2011 - returnable @ 8
2011 - transfer of custody @ 8
2012 - consumable @ 14
2012 - data @ 4
2012 - returnable @ 15
2012 - transfer of custody @ 9
2013 - consumable @ 14
2013 - return of loan @ 1
2013 - returnable @ 5
2013 - transfer of custody @ 4
2014 - consumable @ 28
2014 - return of loan @ 6
2014 - returnable @ 12
2014 - transfer of custody @ 1
2015 - consumable @ 44
2015 - data @ 2
2015 - in house @ 3
2015 - legacy @ 1
2015 - returnable @ 11
2015 - transfer of custody @ 6
2016 - consumable @ 45
2016 - data @ 3
2016 - in house @ 1
2016 - returnable @ 17
2017 - consumable @ 109
2017 - data @ 6
2017 - in house @ 6
2017 - media @ 2
2017 - return of loan @ 1
2017 - returnable @ 11
2017 - transfer of custody @ 1
2018 - consumable @ 122
2018 - data @ 135
2018 - in house @ 4
2018 - legacy @ 1
2018 - media @ 4
2018 - mixed @ 1
2018 - return of loan @ 3
2018 - returnable @ 28
2018 - transfer of custody @ 4
2019 - consumable @ 11
2019 - returnable @ 2

108 rows selected.
```

**Comment by dustymc** [comment]
Doesn't seem to be any interest in this, added to search, closing.
