### ISSUE TITLE
Bulkload Part Subsamples Problem

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1896]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Attempting to us the Bulkload Part Subsamples tool. Load csv file following template. Get the following error: 
Table or view does not exist

**Expected behavior**
No error, subsamples (new barcode) load to existing parts (existing barcode).

**Screenshots**
![screenshot 2019-01-31 21 35 08](https://user-images.githubusercontent.com/14808196/52103158-8dc57080-25a1-11e9-99d8-e317a7f927f3.png)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] chrome

**Additional context**

**Priority**
I would like to have this resolved by date: __asap - need this for already shipped loan_____

**Comment by campmlc** [comment]
fixed two barcode issues with previous file, stil
[Subsample bulkload 1-31-19 2018.007 2018.048 only.txt](https://github.com/ArctosDB/arctos/files/2820151/Subsample.bulkload.1-31-19.2018.007.2018.048.only.txt)
l same error.

**Comment by dustymc** [comment]
rebuilt synonyms

**Comment by campmlc** [comment]
I tried this now and got it to work. However, there are the following problems:

1) The original part is subsampled into two duplicate parts with identical barcodes. What I need, and what I imagine most people would need, is  to subsample the original part by adding one new part with a new barcode, while keeping the original part with it's barcode. This is the case for both tissue subsampling and, in this case, subsampling of a vial of ectoparasites to remove only the fleas into a new vial.  I'd like this to work just like the loan subsample tool works. 

2) The tool also changes the location of the barcoded subsample to be identical with the original vial. These subsamples in my current upload had already been scanned into position in new boxes. Now all that work is undone.  Can we make it so that the position of the new barcode label does not change as it is being assigned to a subsample?
Given that programming changes may take awhile, any way to remove the second identical subsample for this load and restore the subsample barcodes to their former scanned positions so I can go ahead and get this loan paperwork out the door today?

**Comment by dustymc** [comment]
Please attach data.

**Comment by campmlc** [comment]
Cancel #2: looks like the new barcodes are still  in their scanned positions, but they are in duplicate positions. Both new subsamples occupy the same position. So we just need to eliminate the second subsample and all should be good.
[Subsample bulkload 1-31-19 2018.007 2018.048 only.txt](https://github.com/ArctosDB/arctos/files/2822464/Subsample.bulkload.1-31-19.2018.007.2018.048.only.txt)

**Comment by dustymc** [comment]
That can't be the data which loaded so I'm guessing at what happened, but I don't see any way a single load can create two parts in the code.

**Comment by campmlc** [comment]
I can't attach a csv in Github, but here is what I loaded. Also, here is
one of the records:
https://arctos.database.museum/guid/MSB:Mamm:322140

**Comment by dustymc** [comment]
You can attach ZIP or just email it to me.

Any chance you loaded it twice? The tool is built on the assumptions that any part can have any number of children, and that any number of containers can reside in a single parent - duplicates is not something I can prevent.

**Comment by campmlc** [comment]
I suppose there is a chance I could have clicked more than once on the continue button? My internet connection has been running very slowly.
If that is the case, can you please just undo my load and I'll try again?

**Comment by campmlc** [comment]
Barcode has been undone, I've re-barcoded the samples. This time it worked.
