### ISSUE TITLE
Duplicate but not identical higher geography - Madagascar

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#1897]
I added a number of regions to the higher geography for Madagascar based on Wikipedia: https://en.wikipedia.org/wiki/Regions_of_Madagascar.  

One of them, Alaotra-Mangoro, was already in but as a subdivision of the former province Toamasina (10004618).  It is now one of the regions, so I created a "duplicate" entry (10009479) that is consistent with the other regions for our specimen record (http://arctos.database.museum/guid/DMNS:Inv:26287).  

There are 40 specimens using the entry with Toamasina (40 MVZ:Mamm specimens ) so I didn't want to disrupt their records.  But now, during data entry, a search for Alaotra-Mangoro turns up two records without noting that one is "historic" and the other is current.  Would it be helpful to others to add a column for "remarks" and to clarify which entry is current in that column?

Is there a better way to handle this?  I checked the handbook which reads: **"Try not to mix older terms; use modern geography.** We have no idea how to do that when, e.g., one Province of Kenya becomes 6 Counties."

There is also an entry for Toamasina (http://arctos.database.museum/Locality.cfm?Action=editGeog&geog_auth_rec_id=10000088) in the same column with the regions with specimens:  
3 MLZ:Bird specimens
20 MVZ:Bird specimens
29 MVZ:Herp specimens
43 MVZ:Mamm specimens 
That makes sense as they may not have more detailed information that would enable them to update the record to the new regions and it is noted in the record that Toamasina is a former province.  Can I add the same comment to 10004618 although it's used only by another collection?

**Comment by Jegelewicz** [comment]
When I look at this, Toamasina old and Toamasina new can be very easily distinguished and Alaotra-Mangoro IS NOT IN Toamasina Province. It is a REGION (State) of Madagascar that includes a DISTRICT (County) called Toamasina (which is actually just a city, but lots of countries make cities their own political district). I believe that the Higher Geography for Alaotra-Mangoro is incorrect and should be:

Africa, Madagascar, Alaotra-Mangoro, Madagascar

And that most likely, the specimen you are looking at - if it was collected prior to 2007 belongs in the higher geography

Africa, Madagascar, Toamasina, Madagascar

because that is what was on the maps at that time....

**Comment by sharpphyl** [comment]
Per Wikipedia https://en.wikipedia.org/wiki/Regions_of_Madagascar, on 4 Oct 2008, Madagascar dissolved its six provinces and elevated the 22 second-tier administrative districts as regions.  

So perhaps at the time that the MVZ specimens were collected it was correct to state the locality as Africa, Madagascar, Toamasina, Alaotra-Mangoro, Madagascar.  Any specimens collected after 2008 would have been from Africa, Madagascar, Alaotra-Mangoro, Madagascar.  

Does our geography policy enable us to distinguish between the former provinces and the new regions?  They are NOT spatially identical.  How should this be done?  Just a remark?  At one time, the handbook said to use current geographical (political) terms, but that has been crossed out.  With our specimens, I am using the current regions regardless of when the specimen was collected to ensure search capability.  

The reason for my question is to assist our volunteers to choose the correct higher geography in countries where these changes have occurred.  I don't see anything in the data entry process that alerts them to historic but no longer valid higher geography (somewhat like "invalid" but formerly accepted taxonomy).

Yes, this needs more discussion.  Thanks.

**Comment by dustymc** [comment]
>Toamasina old and Toamasina new can be very easily distinguished and Alaotra-Mangoro IS NOT IN Toamasina Province

We often won't have that data - there will just be a label that says "Toamasina, date uncertain." (One of the very many reasons Arctos pushes the "you know it's not tomorrow!" model.) If we had the date, we'd still have to guess at the date on the collector's map.

I'm not sure getting students to the correct thing is a technical problem, and it's not a new problem. There are a dozen "Logan County" in Arctos, for example.

http://arctos.database.museum/geography.cfm?higher_geog=Logan%20County

<img width="426" alt="screen shot 2019-02-02 at 7 31 01 am" src="https://user-images.githubusercontent.com/5720791/52165987-9c547a80-26bc-11e9-9048-c4eba01d1a78.png">

If they don't have the information to pick one - if the label says "Logan County" and no more - they'll just have to go "up" to the convergence (US in that case) and add what they do know in remarks. The same approach should be used for all ambiguous but controlled data.
