### ISSUE TITLE
Merge Localities

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1899]
Our documentation for merging localities is out of date.

When I come across this:

![image](https://user-images.githubusercontent.com/5725767/52166704-e1cd7380-26cd-11e9-8b50-cf1475684654.png)

How do I merge these localities? (They are all my specimens and they should all be in one place....)

**Comment by dustymc** [comment]
Locality Name will prevent those from auto-merging. Moving the events is one alternative - from event results, there's a Move These Collecting Events to new Locality button.

**Comment by dustymc** [comment]
>Our documentation for merging localities is out of date.

And I would like to make it much more out of date with https://github.com/ArctosDB/arctos/issues/1357, but things like https://github.com/ArctosDB/arctos/issues/1705 keep popping up and then never getting resolved.
