### ISSUE TITLE
Please update Media_License code table link for UCM

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#1905]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Table**
http://arctos.database.museum/info/ctDocumentation.cfm?table=CTMEDIA_LICENSE

**Value**
https://www.colorado.edu/cumuseum/research-collections/vertebrates/image-reproduction-policy

**Context**
Our website was reformatted, current link to UCM Image Reproduction Policy is broken

**Priority**
I would like to have this resolved by date: as soon as convenient

**Comment by dustymc** [comment]
done
