### ISSUE TITLE
Parts limited by collection type?

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#1907]
In the 'specimen_part_name' code table, can I get the part "heart, kidney, muscle (frozen)" approved for use in Mamm collection types? It is currently restricted to Bird collection types. 

I would be happy to join the Code Table Management team to help clean and define the tables, though I don't believe I have the appropriate permissions for editing. Just looking at the 'specimen_part_name' table, there is a lot of work to do (though a lot of that will go away when we separate out preservation type). 

**Table**
Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm

**Value**
Proposed new value

**Definition**
Clear, complete, non-collection-type-specific definition of the new value.

**Collection type**
If the code table includes a "Collection" column. Ex: Mamm, Herp, ES

**Attribute data type**
free-text, categorical, number+units

**Attribute value**
For categorical attributes, code table controlling value

**Attribute units**
For number+units attributes, code table controlling units

**Part tissue flag**
For new parts, is the part a tissue?

**Other ID BaseURL**
For OtherIDs, URL with which to prepend value (resolvable identifiers only)

**Context**
Describe why this new value is necessary and existing values are not.

**Priority**
I would like to have this resolved by date: _______

**Comment by dustymc** [comment]
done
