### ISSUE TITLE
Return to attempted access page after log in

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1914]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

> Every time I receive an Arctos Authority Notification, I cannot access whatever the changes are through the link associated!  If I’m an authority, then I would expect I have the credentials to access the page through the link.  Instead, I get an error message saying I am “not authorized to access this form” and then I have to log in, which only sends me to the ALMNH home page, not the link.  How do I rectify this?

**Describe the solution you'd like**
It is understandable that you are not authorized to access the authority changes if you are not logged in, but it would be nice if, after logging in, you would be returned to the link you were attempting to access rather than elsewhere in Arctos.

**Describe alternatives you've considered**
One can log in and then return to email and re-try the link, but why all the extra clicking?

**Additional context**
Just trying to make life easier for overworked collection managers.

**Priority**
I would like to have this resolved by date: 2019-02-28

**Comment by Jegelewicz** [comment]
And BTW, this is actually what I get when I click this link

![image](https://user-images.githubusercontent.com/5725767/52577135-ba1d9000-2dde-11e9-9814-c9b4aa46eb12.png)

Can we PLEASE be more friendly?

How about:

> You must log in to see this report. Please log in and try again. If you are still unable to access the report, contact the person who manages your Arctos collection to request appropriate privileges.

**Comment by Jegelewicz** [comment]
Then after logging in I see this

![image](https://user-images.githubusercontent.com/5725767/52577383-3a43f580-2ddf-11e9-8afc-85fad97c650d.png)

I am not even sure what most of this stuff does and I'm pretty sure that a new collection manager wouldn't know which report to choose to get to the info discussed in the email without returning to view the link.

![image](https://user-images.githubusercontent.com/5725767/52577464-65c6e000-2ddf-11e9-897b-705dfde979ac.png)

**Comment by campmlc** [comment]
I second this request. Anything we can do to minimize exposure to awful red
error messages will help everyone's work experience - especially if you are
being asked to fix something and then get "yelled" at for it. Let's make
this easy and user friendly by asking nicely for a login and then going
straight to the link.

**Comment by dustymc** [comment]
Changing the messages is easy enough.

Trying to carry session information to restricted forms across a login sounds like a really great way to open up a giant security hole; I can't think of any safe way to approach that, but I'll keep staring at it for a while more. 

I could set the index pages up to redirect to the hope page - that one is a list of scheduled tasks, I think the others are just a 403 error. I'm not sure if that's more or less confusing.

**Comment by Jegelewicz** [comment]
> Trying to carry session information to restricted forms across a login sounds like a really great way to open up a giant security hole; I can't think of any safe way to approach that, but I'll keep staring at it for a while more.
> 
> I could set the index pages up to redirect to the **hope** page - that one is a list of scheduled tasks, I think the others are just a 403 error. I'm not sure if that's more or less confusing.

We have a HOPE page! Why did I not know about this?!

JK - I'm down for changing the message to be nice, but get it about security. Maybe in the email that goes out there could be a warning to log in before clicking the link?

 

> Authority values have changed.
> 
> You are receiving this report because you are a collection "data quality" contact, or because you are receiving forwarded email from arctos.database@gmail.com. **Before attempting to view the report via the link below, sign in to Arctos. You must be logged in to view the report.**
> 
> This report is available at

**Comment by dustymc** [comment]
>HOPE page!

I usually use http://arctos.database.museum/random for that...and I'm not sure what to think about my current result.

<img width="163" alt="screen shot 2019-02-14 at 3 10 15 pm" src="https://user-images.githubusercontent.com/5720791/52823676-af772b00-306a-11e9-9845-89a0c43f1fb5.png">

403 now comes with...

<img width="1014" alt="screen shot 2019-02-14 at 3 08 50 pm" src="https://user-images.githubusercontent.com/5720791/52823627-80f95000-306a-11e9-9e84-c4125dc6c95b.png">

>**Before attempting to view the report via the link below, sign in to Arctos. You must be logged in to view the report.**

Done.

**Comment by Jegelewicz** [comment]
> I usually use http://arctos.database.museum/random for that...and I'm not sure what to think about my current result.
> 
> <img alt="screen shot 2019-02-14 at 3 10 15 pm" width="163" src="https://user-images.githubusercontent.com/5720791/52823676-af772b00-306a-11e9-9845-89a0c43f1fb5.png">
> 

HAHAHAHAHA!!! It was meant for you!

That's probably the best we can do for now. Thanks!
