### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1915]
We have a request to work in the test environment from the people in Australia. Any word on when we might have it back?

**Comment by dustymc** [comment]
TACC is reportedly dealing with some huge flux of people getting kicked out of iDigBio so we've been prioritized below that. When test does come back it'll be a major version upgrade so we'll probably want a week or two to deal with that before letting anyone in.

https://github.com/ArctosDB/arctos/issues/1631#issuecomment-410148903 - if we need a sandbox, we should probably build a sandbox. Under the best of circumstances, test isn't a very good introduction to Arctos.

**Comment by campmlc** [comment]
Let's build a sandbox. Our lack of one has probably cost us already. What
do we need to make it happen?
Also, what is TAAC doing for iDigBio? Why are folks getting kicked out? And
can we help in any way?

**Comment by dustymc** [comment]
>What do we need to make it happen?

Another box, another CF license, another Oracle license, all the normal activity to maintain a box. (Unless TACC has some magic - eg, maybe it's possible to just clone production every now and then or something, I have no idea.)

>what is TAAC doing for iDigBio?

>apparently UFlorida/iDigBio is kicking off a bunch (all?) of the RCNs that had been hosted on their infrastructure

That's all I know, and it's not first-hand so take it for what it's worth.

>can we help

I already volunteered us.
