### ISSUE TITLE
Container Labels should not accept positions

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1916]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
A student added positions to a container label and scanned cryovails into the positions.

**To Reproduce**
1. Find a container label barcode
2. Use the table to create positions as in a 100 position freezer box
3. Click positions
4. scan in vial barcodes

Now you have a container label full of cryovials. That container label cannot be scanned into a rack that holds freezer boxes, nor can it be changed to "freezer box" now that it has positions.

**Expected behavior**
Container labels should never hold positions.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
Can we add the constraint to "container label" that excludes creation of positions?

**Priority**
I would like to have this resolved by date: 2019-02-15

**Comment by dustymc** [comment]
done
