### ISSUE TITLE
Failure to upload media metadata

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1920]
From http://arctos.database.museum/tools/BulkloadMedia.cfm

I completed one upload of media metadata, but when I attempt to load my second file I get this:

![image](https://user-images.githubusercontent.com/5725767/52673104-fdf6bf00-2edc-11e9-84ad-f0cb5a784e42.png)

**Comment by dustymc** [comment]
A disk was full and I missed the notification.

https://github.com/ArctosDB/arctos/issues/1872

Should be cleared up now.

**Comment by dustymc** [comment]
And FYI anything NOT involving the melting computer should probably go to https://arctosdb.org/arctos-down/
