### ISSUE TITLE
Add Gatun Formation to CTGEOLOGY_ATTRIBUTE

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#1921]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Table**
CTGEOLOGY_ATTRIBUTE

**Value**
Gatun Formation (Miocene)

**Collection type**
https://en.wikipedia.org/wiki/Gat%C3%BAn_Formation

**Context**
We have specimens from this formation to database.  

**Priority**
I would like to have this resolved by date: _17 Feb 2019______

**Comment by Jegelewicz** [comment]
Done.

Lithostratigraphy (Gatun Formation) is separate from chronostratigraphy (Miocene). If you want the Gatun Formation from the Miocene, you should have two geology attributes:

formation = Gatun Formation
Series/Epoch = Miocene
