### ISSUE TITLE
Default Child in Geology relation ship table entry to NULL

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1927]
Please set default for the Child Term in geology hierarchy creation to NULL. It currently defaults to "Meridian Sand Member (member)" and that is just bound to cause errors. Thanks!

![image](https://user-images.githubusercontent.com/5725767/52867987-6a510880-30ff-11e9-8138-9fda5cec6447.png)

**Comment by dustymc** [comment]
Duplicate of #1892
