### ISSUE TITLE
New Repository - Presentations

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1928]
Does anyone object to the creation of a new repository under ArctosDB specifically for group work on presentations that aren't webinars (ArctosDB/presentations? I could just work with an issue in ArctosDB/arctos, but I think it makes sense to move those conversations elsewhere.

This would allow our work on the presentations to be public and perhaps invite feedback and comments from other AWG members.

**Comment by campmlc** [comment]
Do we want our discussions on presentations to be public? If no one objects
to that, I have no objections to the repository.

**Comment by Jegelewicz** [comment]
HMMMM good point. Does it matter if someone from elsewhere can monitor our planning for SPNHC presentations? Maybe requires a less-public discussion tool? I am not a fan of that. I prefer to stick with the free tool we have and assume that no one has the time or inclination to creep on our presentation development. But I could be wrong about that...

I also like to keep it simple - GitHub seems to be serving us well. The fewer places to communicate the better so that stuff doesn't start happening in the dark somewhere.

**Comment by mkoo** [comment]
I agree about sticking with the tools at hand but also with the need for a
closed discussion space. So private repo? Time to look into Github for
education and nonprofits? I'll take a look into the application. We fit the
criteria!

**Comment by Jegelewicz** [comment]
Thanks @mkoo !

**Comment by Jegelewicz** [comment]
Complete.
