### ISSUE TITLE
genbank - upload frequency

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1929]
GenBank is unable to process our daily uploads due to the size of the files involved. (And it's a fair bit of server load as well). It sounds like they could possibly be talked into weekly uploads. They are willing to try to accommodate bi-weekly. They strongly prefer monthly.

The daily uploads create linkouts from GB to Arctos. Links from Arctos to GB are instantaneous when the OtherID is created, and properly-submitted records should link via specimen_voucher when they're submitted to GenBank.

Does anyone have strong objections to moving the uploads to a monthly schedule?

**Comment by campmlc** [comment]
If we upload monthly, how long before the reciprocal linkages are created
from them to us, vs how long does it take now?

**Comment by dustymc** [comment]
>how long before the reciprocal linkages are created from them to us

At most, a month plus whatever processing time they require (generally a couple days, I think).

>how long does it take now?

In theory the current schedule is <24H plus their processing time. In reality, I think their scripts have been choking on our data for a while.

**Comment by campmlc** [comment]
So, that is a month in addition to the month before we send to them?

**Comment by campmlc** [comment]
Or, they are able to put up the link within a few days of whenever we send?

**Comment by dustymc** [comment]
few days

**Comment by campmlc** [comment]
I would prefer more frequently, but a month is acceptable.

**Comment by Jegelewicz** [comment]
We have to play well with others. Better a month or two than never....

**Comment by dustymc** [comment]
schedule updated to monthly
