### ISSUE TITLE
Create Container Error

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1931]
I had to delete a barcode and re-create to donate it to an existing barcode-less label.

When I try to create the container with this form:
![image](https://user-images.githubusercontent.com/5725767/52970562-7217e380-3371-11e9-95d2-0843f77cdce2.png)

I get this error:
![image](https://user-images.githubusercontent.com/5725767/52970573-8065ff80-3371-11e9-813f-c9d4eb5e1077.png)

Not sure why Arctos thinks there is no data in the form?

**Comment by dustymc** [comment]
Should be fixed
