### ISSUE TITLE
Do multiple occurences pushed to GBIF and iDigBio make sense?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1932]
This specimen record:

![image](https://user-images.githubusercontent.com/5725767/52972624-b5298500-3378-11e9-9887-b229b1c26e3d.png)

has two specimen events because it was georeferenced. However, two occurrences are being pushed to GBIF and iDigBio, which is not a proper representation of what transpired. As it appears in GBIF and iDigBio, this animal was captured (and preserved) twice.

![image](https://user-images.githubusercontent.com/5725767/52972940-b27b5f80-3379-11e9-9df9-b71e8d4414b3.png)

![image](https://user-images.githubusercontent.com/5725767/52972955-bb6c3100-3379-11e9-89a2-ce766b4a0da8.png)

In fact, the UTEP invertebrate collection has 4,059 occurrences in GBIF but only 2,921 records in Arctos - all due to secondary events because of georeferencing. Are we certain that anyone using GBIF or iDigBio data will understand what is going on? I assume that I could fix this by assigning the accepted, georeferenced event to the parts, but do I now need to do that for over 2,000 records in this collection (never mind all the others)?

I think this also plays in with #1705 and #1913 

@campmlc

**Comment by anna-chinn** [comment]
I think it makes sense to push multiple specimen events for a given Arctos record to GBIF (not sure about iDigBio), because they aggregate all sorts of occurrences, including observations.

Specimen events set to unaccepted do not get served to the aggregators. We had this same problem for our birds and were getting requests from researchers who assumed we had twice the birds than we actually had. Dusty was able to automate some stuff for me and now all of our records show up like this on Arctos: http://arctos.database.museum/guid/CHAS:Bird:1000.

**Comment by Jegelewicz** [comment]
But this specimen has an event that is verified and locked, yet two events are showing up at GBIF.....

and

> I think it makes sense to push multiple specimen events for a given Arctos record to GBIF (not sure about iDigBio), because they aggregate all sorts of occurrences, including observations.

To me, this just doubles occurrences and means anyone doing abundance work using GBIF or iDigBio data is going to be mislead unless they do a search for duplicate catalog numbers. Assuming they do that (making assumptions about what people will do is usually bad), they still won't know which occurrence is "correct". I feel like anyone outside of Arctos would think we are doing something wrong or that datasets are being published twice (which in a sense they are).

**Comment by anna-chinn** [comment]
In cases where there are two unverified events, and no one has laid eyes on the data, it seems just as misleading to arbitrarily choose one to send to the aggregators over the others.

In cases where one event is accepted and locked, maybe we need more programmatic logic to send stuff to aggregators? If there are more than one event related to a specimen record, only send events that are verified+locked.

Then again, is there any reason not to set the second event to unaccepted? I think that Dusty could probably easily distinguish between verified+locked and unverified events associated to the same specimen and programmatically change those unverified events to unaccepted.

**Comment by anna-chinn** [comment]
Is there any reason not to set the second event to unaccepted? In cases where there are two events both set to unverified but no one has laid eyes on the data, it seems just as misleading to arbitrarily choose one to send to GBIF.

Maybe in this kind of case, it’s just a matter of increasing the logic involved in passing data to aggregators- like if there are more than 2 events, when one if verified and locked, don’t push the others to GBIF.

**Comment by Jegelewicz** [comment]
> In cases where there are two unverified events, and no one has laid eyes on the data, it seems just as misleading to arbitrarily choose one to send to the aggregators over the others.

I agree in principle, but I contend that no one viewing the data from GBIF will understand what it means that there are two (or that they will even notice the two relate to the same animal) AND they have even less arbitrary means of choosing between the two (or four or eight as the case may be...). While curation could solve this problem, I doubt there will be a rush by anyone to curate localities. We should be explicit about what is going on in some way that the non-Arctos community can understand.

**Comment by dustymc** [comment]
Yes if there's some pattern I can help update. That specimen looks like one should be "unaccepted"==>"...or less correct or complete than...."

http://arctos.database.museum/info/ctDocumentation.cfm?table=CTVERIFICATIONSTATUS

There are a few tens of thousands of specimens with (at least) two events: one "correct" but minimal and one from some TCN or something, which is occasionally just wildly wrong (http://arctos.database.museum/guid/UAMb:Herb:31405). I'd hate to hide potentially-useful information (many have good georeferences), and I'd hate to assert that something which hasn't been reviewed is anything other than what it is. Two Occurrences is the only DWC path I see to that.

Multiple unreviewed hypotheses regarding a single event is but one scenario. Many specimens have multiple events of various types with various levels of verification.

This is also a bit confounded by the fact that many (legacy, I think/hope) specimen events that are entered incorrectly. http://arctos.database.museum/guid/MSB:Mamm:292063 claims to have been "killed, found dead, or removed from functional cultural, biological, ecological, or archeological context" 5 times, for example.

I'm not sure how this would affect the two linked Issues - can you elaborate?

**Comment by campmlc** [comment]
I fixed http://arctos.database.museum/guid/MSB:Mamm:292063. A list of
similar examples would be useful.

**Comment by dustymc** [comment]
>list
```
create table temp_m_c_e as select guid from flat where collection_object_id in (
  select collection_object_id from specimen_event where specimen_event_type='collection' and verificationstatus !='unaccepted' having count(*) > 1 group by collection_object_id
);
```
[temp_m_c_e.csv.zip](https://github.com/ArctosDB/arctos/files/2880673/temp_m_c_e.csv.zip)

**Comment by Jegelewicz** [comment]
> Yes if there's some pattern I can help update. That specimen looks like one should be "unaccepted"==>"...or less correct or complete than...."
> 
> http://arctos.database.museum/info/ctDocumentation.cfm?table=CTVERIFICATIONSTATUS

I think that "verified and locked" should be the only occurrence going out to aggregators if it exists for a specimen. Which will fix part of what I see as a problem, but perhaps no one else thinks it's problematic to have one specimen appear multiple times at the aggregators. If ind the possibility for misuse troublesome.

**Comment by dustymc** [comment]
>"verified and locked" should be the only occurrence going out to aggregators if it exists for a specimen.

That is one use case. http://arctos.database.museum/guid/MSB:Mamm:292063?seid=3175067 might be "verified and locked" (or anything else) while the other 4 events have some other status.

**Comment by Jegelewicz** [comment]
None of those are "verified and locked" and they never will be because that is a mark re-capture animal and all of the events are equally "accepted". In that case, all of the events make sense as occurrences (except that each one of them is probably showing ALL the parts at GBIF, which will still be misleading as only some of the parts belong with each event). In my case, a georeference provided coordinates that have been curatorially (Lieb is the curator) accepted and the other event, although less accepted, I don't want to label as "unaccepted" because it documents the collector's original assignment of locality. The appearance of both in places like GBIF and iDigBio is very likely to make for poor science and in a wierd way so will the example you gave unless users at those sites understand what is happening. This really requires a discussion of a larger community.

**Comment by dustymc** [comment]
>None of those are "verified and locked" and they never will be because that is a mark re-capture animal and all of the events are equally "accepted".

I don't know what this means. You could verify and lock any, all, or none of the events. It doesn't matter what happened at the event or any other event, verificationstatus is just an indication of verifiedby's confidence in the accuracy of the event.

**Comment by Jegelewicz** [comment]
> verificationstatus is just an indication of verifiedby's confidence in the accuracy of the event\

OK, but we are using it to DO stuff, at least that is my understanding - any event marked as "unaccepted" will not generate an occurrence in GBIF. While that makes sense, I do not think it always makes sense for ALL non-"unaccepted" events to generate an occurrence. I would like to be able to say - the location of this object has been enhanced, but it was only collected ONCE so publishing two "occurrences" is misleading as there are really two versions of the same occurrence, just with small variations in the description of the location. How can we facilitate this without me saying the collector's description (before GPS was universally available) is just wrong (unaccepted).

If the georeference was recorded at the locality level, rather than through a second collection event, there would be only one event and the locality would reflect the addition of coordinates by whomever, whenever. #1705

**Comment by dustymc** [comment]
"unaccepted" is NOT "just wrong" - that term encompasses "or less correct or complete than" as well. I suppose we could split that into two values or something, but I don't see a real distinction and without one we're just saying the same thing in two ways.

http://arctos.database.museum/info/ctDocumentation.cfm?table=CTVERIFICATIONSTATUS

Adding a georeferencer would in fact handle that one use case. It will not handle any of the very many others.

**Comment by Jegelewicz** [comment]
From https://github.com/ArctosDB/arctos/issues/1705#issuecomment-429419768

> What about managing geocoordinates & their associated metadata incl. who & when the same way we track identifications of specimens. The specimen is a fact but it's ID is an opinion. The locality name "Fairbanks" is a fact but the geocoordinates (& assoc metadata) are an opinion because different people may disagree on things like how much error to use etc.

This has been bugging me for a while now. If we are publishing multiple occurrences because of changes in locality, why aren't we publishing multiple occurrences because of changes in identification? The answer for now is that we only allow one "accepted" identification. Why is this any different than the multiple opinions about locality? 

I understand (perhaps incorrectly) that if I make all the events for any specimen "unaccepted" they will not create an occurrence at the aggregators. Because there are cases where multiple events ARE individual occurrences (mark recapture) we can't just automate this as we do with identifications and it takes a long time to go through thousands of specimens with multiple events to pick which should be "unaccepted". Also, when bulkloading, everything has to go in as "unverified", which just creates more work later. How can we make it easier to keep using the model we have, but stop creating duplicate records at the aggregators?

**Comment by dustymc** [comment]
>why aren't we publishing multiple occurrences because of changes in identification?

https://terms.tdwg.org/wiki/dwc:previousIdentifications

DWC saw that coming. (Probably doesn't hurt anything that it's easy to distill multiple identifications down to simple strings either.)

>stop creating duplicate records at the aggregators

Even for the case of multiple opinions regarding the same Occurrence, that is not a universally desirable objective. Some collections simply want to publish what they know (and that looks like a least-evil approach to me).

In "the old model" (and AFAIK everything else that's not current-Arctos) when given multiple opinions regarding a single locality, you'd have no choice but to pick one as either accepted or the singular assertion, no matter how arbitrary that selection process was. From that, it doesn't seem completely unreasonable for collections that don't wish to share multiple hypotheses regarding single events to make the same choice and hide n-1 of them via "unaccepted." 

I'm happy to help find and update if you want to go there.

>if I make all the events for any specimen "unaccepted" they will not create an occurrence at the aggregators.

Correct. DWC is Occurrence-based. If you "unaccept" all the Occurrences then there's nothing to share with them.

**Comment by Jegelewicz** [comment]
> Yes if there's some pattern I can help update. That specimen looks like one should be "unaccepted"==>"...or less correct or complete than...."

@dustymc can you help me with the UTEP:Inv events? I'm trying to get them all set up so that there is only one occurrence showing up at GBIF and iDigBio.

For any record with an event marked "verified and locked" I would like to mark the other event as "unaccepted".

After that is done, I would like to be able to find all of the records that have more than one event with verification status other than "unaccepted" so that I can work through them ad decide which event I should mark as unaccepted.

BTW - I will probably want to run these queries on other UTEP collections eventually, so if we can post the SQL somewhere, that would be nice.

**Comment by campmlc** [comment]
Yes, MSB would like access to the same report, and I'm sure other
collections as well.

**Comment by dustymc** [comment]
```


-- these have multiple events
create table temp_mul_evt_r as select flat.guid,flat.collection_object_id from 
  flat , 
  specimen_event
where
  flat.collection_object_id=specimen_event.collection_object_id and
  flat.guid like 'UTEP:Inv:%'
having count(*) > 1 
group by flat.guid,flat.collection_object_id;

alter table temp_mul_evt_r add evts varchar2(4000);

-- get the events
declare
  se varchar2(4000);
  s varchar2(2);
begin
  for r in (select * from temp_mul_evt_r) loop
    se:='';
    s:='';
    for e in (select specimen_event_type,verificationstatus from specimen_event where collection_object_id=r.collection_object_id order by specimen_event_type,verificationstatus) loop
      se:=se||s||e.specimen_event_type||'='||e.verificationstatus;
      s:=';';
      update temp_mul_evt_r set evts=se where collection_object_id=r.collection_object_id;
    end loop;
  end loop;
end;
/


UAM@ARCTOS> select distinct evts from temp_mul_evt_r order by evts;

EVTS
------------------------------------------------------------------------------------------------------------------------
collection=accepted;collection=accepted;collection=unverified
collection=accepted;collection=unaccepted
collection=accepted;collection=unverified
collection=unaccepted;collection=unverified
collection=unaccepted;collection=verified and locked
collection=unverified;collection=unverified
collection=unverified;collection=verified and locked
collection=unverified;collection=verified and locked;collection=verified and locked

UAM@ARCTOS> select guid from flat where collection_object_id in (select collection_object_id from temp_mul_evt_r where evts='collection=unverified;collection=verified and locked;collection=verified and locked');

GUID
------------------------------------------------------------------------------------------------------------------------
UTEP:Inv:2302
UTEP:Inv:2832
UTEP:Inv:2468
UTEP:Inv:5426
UTEP:Inv:2453
UTEP:Inv:13327
UTEP:Inv:766
UTEP:Inv:2031
UTEP:Inv:2517
UTEP:Inv:267
UTEP:Inv:3602
UTEP:Inv:6959
UTEP:Inv:2956

13 rows selected.

```

I think the stuff I could deal with has mostly already been dealt with??

**Comment by Jegelewicz** [comment]
Thanks! When I run that SQL I get the error: The code you submitted contains illegal characters

**Comment by dustymc** [comment]
Some of it's not SQL. What interface are you trying to use?

**Comment by Jegelewicz** [comment]
I was just using "write SQL" in Arctos, but if it isn't SQL, then of course that won't work.

**Comment by dustymc** [comment]
Yea that thing goes through JDBC and won't understand this. I can probably rewrite it in SQL if you really need it, this just seemed easier at the moment. The first block should run and find the really critical bits - just drop the ending semicolon.

I think you can get to pl/sql if you have a TACC account and are feeling brave too, but you might need to coordinate that with Chris.

I don't mind running/rerunning/whatever either.

**Comment by Jegelewicz** [comment]
closing for lack of interest - also expected changes in GBIF model
