### ISSUE TITLE
new Nature of ID type for Paleo Ichnotaxa

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1933]
From #1900 
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Table**
http://arctos.database.museum/info/ctDocumentation.cfm?table=CTNATURE_OF_ID

**Value**
trace evidence

**Definition**
Identification has been made upon examination of evidence left by an organism such as a track, scat, or imprint rather than observance of the actual organism.

**Collection type**
ES

**Attribute data type**
N/A

**Attribute value**
N/A

**Attribute units**
N/A

**Part tissue flag**
For new parts, is the part a tissue?

**Other ID BaseURL**
For OtherIDs, URL with which to prepend value (resolvable identifiers only)

**Context**
Describe why this new value is necessary and existing values are not.

**Priority**
I would like to have this resolved by date: 2019-02-28

**Comment by dustymc** [comment]
I dislike this for the same reasons I dislike our current terminology: there's a world of difference between "looks like rabbit poop to me" and "here's the full nuclear sequence on GenBank (or CT scan on Morphosource, or datasheet of diagnostic attributes, or...), it has 99.999% alignment with 84000 rabbits on GenBank." I think nature of ID should be functional, and I don't see how linking that to available material changes anything.

**Comment by Jegelewicz** [comment]
Any recommendation for making clear what @dperriguey says in #1900 ? Personally, I think that the part (trace fossil) makes it clear enough, but from what I can tell, he doesn't feel that is true.

**Comment by Jegelewicz** [comment]
Never mind, seems he is good with the part designation.

**Comment by dustymc** [comment]
I can't claim to fully understand the taxonomy, but I _think_ Dimetropus = Dimetrodon is just wrong. The former describes a trace fossil, the latter describes something else.
