### ISSUE TITLE
New container type

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1934]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Table**
http://arctos.database.museum/info/ctDocumentation.cfm?table=CTCONTAINER_TYPE

**Value**
building

**Definition**
A structure with a roof and walls standing more or less permanently in one place.

**Collection type**
N/A

**Attribute data type**
N/A

**Attribute value**
N/A

**Attribute units**
N/A

**Part tissue flag**
N/A

**Other ID BaseURL**
N/A

**Context**
A collection may be housed in multiple buildings. Helps with finding stuff.

**Priority**
I would like to have this resolved by date: 2019-02-22

If no one objects - I will add this.

**Comment by campmlc** [comment]
No objection.

**Comment by Jegelewicz** [comment]
Added
