### ISSUE TITLE
Classification Metadata

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1937]
@DerekSikes suggested that we change the title for this section from "Non-Classification Terms" to "Classification Metadata"

![image](https://user-images.githubusercontent.com/5725767/53131666-a4207580-352a-11e9-9195-e66b91ed00d1.png)

@ArctosDB/taxonomy agrees!

**Comment by Jegelewicz** [comment]
From Taxonomy Committee today:

@dustymc 

Let's change this.

**Comment by Jegelewicz** [comment]
![image](https://user-images.githubusercontent.com/5725767/56098365-0f4c4f80-5ebd-11e9-9972-c674d574bd47.png)

Please!

**Comment by sharpphyl** [comment]
Oops!   I need to change several of the How-tos where I put it in as Non-classification Metadata.  You're correct.  It should be Classification Metadata.

**Comment by Jegelewicz** [comment]
@dustymc 

Can we get this change please?

![image](https://user-images.githubusercontent.com/5725767/56098365-0f4c4f80-5ebd-11e9-9972-c674d574bd47.png)

**Comment by Jegelewicz** [comment]
Please?

**Comment by dustymc** [comment]
Done - not sure how this fell off my radar....
