### ISSUE TITLE
Ability to download all names and their classifications used by my collection as csv

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#1940]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

I'd like to periodically be able to find inconsistency in the taxonomic classifications/names associated with my collection.

**Describe the solution you'd like**

If I can download all these taxon names (the sciname and the corresponding classification) I can manipulate them off line to search for inconsistencies etc. and then I can fix them. Perhaps I can prepare a file that can be bulkloaded via the hierarchical tool. 

**Describe alternatives you've considered**

asking Dusty to download these names for me.

**Additional context**

**Priority**
I would like to have this resolved by date: _1/4/2019______

**Comment by dustymc** [comment]
CSV - flattening - would likely be somewhere between difficult and lossy - maybe both!

We have a tool to pull to hierarchies (and deal with the stuff that falls out), and it can push _clean_ hierarchies to CSV/back to Arctos.

Does adding a "seed all taxa used by {collection}" option to the hierarchical editor sufficiently address this?

**Comment by campmlc** [comment]
Can we download a csv from the hierarchical editor? I need some training on using that - it's not obvious how or where to access.

**Comment by dustymc** [comment]
>Can we download a csv from the hierarchical editor?

>it can push _clean_ hierarchies to CSV

So yes, with limitations - eg, Arctos can handle 500 terms ranked "Kingdom" within a classification, SOMETHING will choke and die if you try to push that to CSV via the hierarchical editor.

**Comment by dustymc** [comment]
I could export tables, https://github.com/ArctosDB/arctos/issues/3498 might provide this, the hierarchical editor can do this to some capacity, I don't think there are other realistic options - tentatively closing.
