### ISSUE TITLE
New Collecting Source #2

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1943]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Table**
http://arctos.database.museum/info/ctDocumentation.cfm?table=CTCOLLECTING_SOURCE

**Value**
fabricated

**Definition**
Created by art or skill and labor.

**Collection type**
N/A

**Attribute data type**
N/A

**Attribute value**

N/A

**Attribute units**
N/A

**Part tissue flag**
N/A

**Other ID BaseURL**
N/A

**Context**
"captive" not appropriate for paleo collections

**Priority**
I would like to have this resolved by date: 2019-02-28

**Comment by mbprondzinski** [comment]
This works for me.

**Comment by campmlc** [comment]
Agree.

**Comment by campmlc** [comment]
Possibly add "human art, skill, or labor".  Nests are fabricated.

**Comment by mbprondzinski** [comment]
Would "man-made" suffice or is "human art, skill, or labor" already in place in Arctos?

**Comment by Jegelewicz** [comment]
@mbprondzinski I think Mariel means to make the definition:

Created by human art or skill and labor.

**Comment by mbprondzinski** [comment]
Okay.  That works.

**Comment by dustymc** [comment]
I think we're mixing concepts, but I'm not sure it matters.

Collecting Source applies to events, and is intended to answer questions like "is this a useful point for a range distribution map?" Fabricated (whatever it's called) implies something physical, and parts are physical things in Arctos.

A specimen ("something someone felt like giving a catalog number") could have an event (which may or may not have produced something physical that we can put our hands on) to the place it was "removed from nature" and another for the place a reproduction (which again we may or may not be able to put our hands on) was created. Many users wouldn't make the second event, some probably would.

"This is a cast made in a lab, and here are the coordinates for the lab" isn't something you'd want on your range map. "This is a cast made in a lab, it's a replica of a specimen from these coordinates" might be something you'd want on your range map. We can link events and parts. I'm not sure this is exactly "correct" but I do think it's capable of conveying the information.

Soft "yes" vote from me, I think.

**Comment by campmlc** [comment]
I like this clarification, and like this approach.

**Comment by KatherineLAnderson** [comment]
Agree with Dusty! I think it's better to record this data (replica, or not) as the preservation attribute we discussed in the other thread, and keep the collecting source (and event and locality) the data for the original specimen that the replica was created from. Second event for fabrication data, if necessary.

**Comment by Jegelewicz** [comment]
@KatherineLAnderson there isn't always a record for the thing the specimen was created from (at least not in Arctos).

ALMNH has a replica of the Archyopterx in the British museum. Should my collection source be "captive"? I guess it works for what is intended, but it seems silly.

**Comment by KatherineLAnderson** [comment]
> @KatherineLAnderson there isn't always a record for the thing the specimen was created from (at least not in Arctos).
> 
> ALMNH has a replica of the Archyopterx in the British museum. Should my collection source be "captive"? I guess it works for what is intended, but it seems silly.

Do you mean that there isn't a specimen record for the original specimen in Arctos? For example, the original Archaeopteryx your replica was created from is not databased on Arctos? We have in that case used data from other databases, publications, etc to acquire the data and enter in on Arctos. The replicas usually have a catalog number for the institution where the original is housed, so we reference whatever database they use. 

Or do you mean that the original specimen the replica was created from is unknown/has no data?

**Comment by dustymc** [comment]
Yes, that's my "not sure this is exactly "correct" but I do think it's capable of conveying the information."

You could have two events - one "This is a cast made in a lab, and here are the coordinates for the lab" (which might be useful when trying to track down the original or something) and you'd have some sort of flag that prevents mapping Archyopterx to London, and one "This is a cast made in a lab, it's a replica of a specimen from these coordinates" that WOULD be useful for mapping the distribution of Archyopterx. (And a reciprocal "same individual as" relationship to the BM specimen would be nice...)

**Comment by campmlc** [comment]
But currently our specimen events are treated as new collections in
iDigBio. We wouldn't want people to think we had a newly collected
Archaeopteryx specimen, when we were just trying to point to the original
source specimen outside of Arctos. We could use relationships for that:
"cast of" British Museum #12345 etc

**Comment by KatherineLAnderson** [comment]
Ah yes, that's problematic and misleading. A "cast of" relationship would be great. Also include the original catalog number in identifiers. I think the 2 events makes the most sense, although we still need to clearly convey it's not a new collecting event.

**Comment by dustymc** [comment]
Well you DO have a new Archaeopteryx specimen - someone apparently cataloged something, which is the threshold for "specimenness." Specimen_event_type and parts should should clarify what you have, and things like this and https://github.com/ArctosDB/arctos/issues/1942 should help clarify what the are suitable for. It's still useful for lots of things (esp. if the BM data aren't accessible).

"cast of" seems way too specific, but I think I get the idea. "replica of"??

**Comment by Jegelewicz** [comment]
> We could use relationships for that: "cast of" British Museum #12345

That's how I have it set up.

**Comment by Jegelewicz** [comment]
> "cast of" seems way too specific, but I think I get the idea. "replica of"??

I like "replica of" for the relationship

Returning to the crux of this issue, I think it is moot if we go with in situ, ex situ for our collecting source choices. For the case we have been using here - AL's Archaeopteryx replica, it would be ex situ.

We probably need to discuss the "cast" part stuff in #1912
