### ISSUE TITLE
Part attributes bulkload error

### ISSUE THREAD

**Issue by krgomez** [ArctosDB/arctos#1944]
**Describe the bug**
I'm getting an error message when trying to upload a part attributes csv to the part attributes bulkloader. See screenshot.

**To Reproduce**
Upload csv to part attributes bulkloader.

**Screenshots**
![screen shot 2019-02-20 at 5 40 14 pm](https://user-images.githubusercontent.com/40579515/53194293-7a655e00-35bf-11e9-813c-871e3da44ffb.png)

**Desktop (please complete the following information):**
Mac High Sierra 10.13.6, Firefox

**Priority**
I would like to have this resolved by date: 2019-02-28

**Comment by dustymc** [comment]
data please
