### ISSUE TITLE
container updates aren't propagating to FLAT

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1945]
See email from @DerekSikes "some with and some without labels" 2019-02-21 - changes to the container stack (new container type) are not propagating to flat.partdetail

**Comment by dustymc** [comment]
I can't find a realistic way to do this. We're over-caching for performance reasons and there's nothing that can link a container type change (for example) to a part without adding a great deal of expense/complexity. Suggest we periodically auto-rebuild flat, find the processors to directly address containers, or ???????

**Comment by campmlc** [comment]
How do we get more processors? Is this a discussion with TACC? A grant?

**Comment by dustymc** [comment]
This problem occurs at the many:many intersection of...

```
UAM@ARCTOS>  select count(*) from specimen_part;

  COUNT(*)
----------
   5026559
```
and...
```
UAM@ARCTOS> select count(*) from container;

  COUNT(*)
----------
   9224840
```

two large tables that have cruddy index stats because they're updated constantly, and both are optimized in favor up update rather than query.

Container relates to itself, so the numbers of rows is a simpler picture than the number of things the optimizer actually has to sort through as well.

TACC is into "big data" and might be interested in working on a solution to things like this, but I certainly wouldn't know what to put in a request or grant. I'd guess something like striping the data across many solid-state drives would be the most likely to pay off, but that's best addressed by an Oracle performance expert. Maybe paying someone for a system tune-up is a sellable proposal. I don't know if that would fix this or not, but it should improve overall performance.

This seems to be a relatively rare problem - it only happens when an upstream container type changes, and we don't seem to do that very much. There are probably other things that should trigger FLAT to refresh and don't - that's sort of expected when trying to squish a complex system into an overgrown spreadsheet. It's not exactly a fix, but just refreshing FLAT when we have spare processors would probably make this unnoticeable, and would fix anything else that should have been recached but wasn't. TACC is moving us to Oracle 12 now, and it has some additional priority settings that we can probably use to get at "when we have spare processors."

If that's not sufficient, I can take a closer look at the "great deal of expense/complexity" option. Oracle 12 should make that easier as well - it "speaks" the language in which we store the cached data, which minimally should make it easier to tell when something's out of sync.

**Comment by campmlc** [comment]
OK - you had mentioned needing more processors before, so I'm happy to
start that conversation with TACC if we have a clear need and direction.
And we should add it to our list  of things to budget for if there will be
an associated cost.

**Comment by dustymc** [comment]
> more processors

Yea, I'm probably too sloppy with that terminology. Throwing hardware at things is almost always the cheapest and easiest option, and sometimes it works. The last time we paid for an Oracle consultation, and that was a LONG time ago, it turned out what we needed was more, smaller disks that could be read simultaneously (and adding them was like flipping the "go fast" switch). I suppose my perspective flops around depending on what's causing problems at the moment, but if we were going to spend $$ on one performance-related thing, an Oracle consultant is probably the single best place to do so.

**Comment by Jegelewicz** [comment]
@dustymc is this still a problem?

**Comment by Jegelewicz** [comment]
@dustymc can we close this?

**Comment by dustymc** [comment]
No, I still don't have a solution.

**Comment by Jegelewicz** [comment]
Can I get a better description of the problem?

**Comment by dustymc** [comment]
Calling this next release - I don't have a real solution, but Arctos should now be using extra CPU to process the oldest records in flat, which will (hopefully) result in things like this being picked up before they are noticed.
