### ISSUE TITLE
remove ephemeral IDs from specimen bulkloader

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1947]
LOCALITY_ID and COLLECTING_EVENT_ID are ephemeral and cause problems when they get auto-merged before they can be used. Remove them from the specimen bulkloader. Locality/Event name are stable; make sure they're available.

**Comment by campmlc** [comment]
Will this affect the ability to download Collecting Event ID to use to link
parasites and host Collecting Events?

Is there some constraint to force nicknames to be unique? We get repeated
samples from the same locality. We should have some standardized or better
yet, automated way to generate unique collecting event names.

**Comment by dustymc** [comment]
> affect the ability to download Collecting Event ID to use to link parasites and host Collecting Events

Yep - good catch. We may have to keep this, and we need some sort of time-sensitive warning or something.

>force nicknames to be unique

Yes, like all IDs they couldn't possibly be functional without that.

>standardized ... way to generate

Various forms will generate a UUID. Beyond that, I'm not sure there's any reason to attempt to force any standardization.

> automated way to generate

I'm up for ideas, but this is really a way for humans to AVOID automation.

**Comment by campmlc** [comment]
I'm concerned about the ballooning lack of standardization and the inevitable overlap. For example, there is a locality nickname in Arctos of "Site 002". That is not particularly informative. What if someone else uses "Site 002-1" for a totally unrelated location? How do we keep track of all this?  Maybe  Arctos doesn't care, but it is going to become increasingly difficult for human beings to figure all this out. If we want parasite specimens to link to hosts, or any related items, they need to share collecting events, and we need to be able to find the correct one to match too. An autogenerated event ID/name (like the current "unstable" number) would be very helpful. How about providing the option for Arctos to autogenerate a stable, unique ID? How about having the unstable identifiers autoconverted to a stable name behind the scenes, and we use that default "name" for future downloads? We could allow users to change the "label" field of the name in the same way we change the label on a barcode; but there would still be a second, autogenerated unique value?

**Comment by Jegelewicz** [comment]
My solution was to make my "unique" names "UTEP:ES:Site_XXXX"

**Comment by campmlc** [comment]
Yes, but how do we enforce that? If we had some sort of automation, we
could enter "site 002" as the label and arctos could generate "MSB:Mamm:
Locality ID" - but then, that locality gets shared among multiple
collections, so then what?
Anyway to make the "unstable" temporary numbers part of the permanent name
as default, and then let people add some sort of label text if they choose?

**Comment by dustymc** [comment]
>Site 002". That is not particularly informative.

Presumably it's informative-enough to whoever made it, and that's the only point - it's a way to re-find specific localities/events (in part by ensuring they can never be altered or deleted by automation). Others' locality/event names should not concern you (even if they are inconvenient - we all seem to start these things at "1") - just don't use them. There should be no assumption that Site 002 and Site 002-1 have any relationship - those are just unique strings. (They MIGHT have some relationship that makes sense to whoever created them, but that's something a user has done and not something that will necessarily make any sense to any other user.)

Adding an autogenerated name would have exactly the same effect as dropping all of the auto-merge scripts; it would lead to a huge number of duplicates, make updates much more expensive, effectively block https://github.com/ArctosDB/arctos/issues/1357, etc.

I don't think it's much problem to find an equally-stable workaround for data entry, it's just going to take a bit of development before I can remove the ID fields from the bulkloader.

**Comment by Jegelewicz** [comment]
> but then, that locality gets shared among multiple collections, so then what?

I don't think that is a huge problem, although the collections using "my" location might not like it. They could create a duplicate and give it their own name - but that sort of defeats the purpose of sharing. Anyone searching all of Arctos by the locality (not a name) would still find everything.

**Comment by Jegelewicz** [comment]
BTW, make sure Locality/Event name are available in the Specimen Event Bulkload Tool.

**Comment by campmlc** [comment]
How will we be notified if we are trying to give a locality a name that
already exists? How can we avoid this ahead of time, and what kind of error
messages are we going to see? What if I try to pre-create 100 localities
with names "Site-001" to "Site 100", but a few of those names have already
been used?

**Comment by dustymc** [comment]
http://handbook.arctosdb.org/documentation/understanding-errors.html#unique-constraint-iu_table_and_column-violated
