### ISSUE TITLE
Add parts to Herp collections

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#1950]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Table**
Specimen_part_name

**Value**

heart (lysis buffer)
liver (lysis buffer)
heart, liver (lysis buffer)
heart, liver, muscle (lysis buffer)
muscle (lysis buffer)
kidney (95% ethanol) - already exists in Mamm
skin (frozen) - already exists in Mamm and Bird
pancreas (frozen) - already exists in Mamm and Bird

**Definition**
tissues preserved in unknown concentration of lysis buffer

**Collection type**
Herp

**Part tissue flag**
Yes to all

**Context**
We have these parts in our herp collections.

**Priority**
I would like to have this resolved by date: _____02/28/2019__

**Comment by Jegelewicz** [comment]
All done except

pancreas (frozen)

@dustymc can you give this one the definition: frozen pancreas tissue and add to Herp?

**Comment by dustymc** [comment]
done

**Comment by mvzhuang** [comment]
Thanks everyone!
