### ISSUE TITLE
Names stuck in name bulkloader

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1952]
There are 21 names in the scientific name bulkload tool that have already been loaded - not sure why they are stuck in there. Can we add a "delete data" option to the tool so that we can get rid of stuff when necessary?

**Comment by Jegelewicz** [comment]
After completing a second load, it looks like I can just keep re-loading and it will work through everything? I'd like this to be a bit more transparent, but low priority for now as long as it seems to be working...

**Comment by dustymc** [comment]
Name-loader needs moved into the component loader ecosystem.
