### ISSUE TITLE
Taxonomy search results taxon status etc only displays partially

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#1956]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

When I search on a taxon name in the taxonomy table the results appear with boxes below each name inside of which are source, display name, and taxon status. However, these boxes only appear for the taxa in view in the browser window, those that are below the view & need to be scrolled down to see, don't have these boxes. This seems wrong - they should all have these boxes of extra information. See screenshot

**To Reproduce**

**Expected behavior**

**Screenshots**

This screen shot shows what the list looks like when I scroll down.  The names without boxes were not visible until after I scrolled down.

![screen shot 2019-02-28 at 12 22 41 pm feb 28 19](https://user-images.githubusercontent.com/9099827/53599582-fe858b80-3b53-11e9-8553-1ba1e57b6be0.jpg)

**Desktop (please complete the following information):**

**Additional context**

**Priority**
I would like to have this resolved by date: _______

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/1821#issuecomment-451501436

**Comment by DerekSikes** [comment]
I now realize that these boxes only display for names that have Arctos classifications - it's got nothing to do with the visible area of the web browser window. I withdraw my report.

**Comment by DerekSikes** [comment]
I was wrong, even names with Arctos classifications fail to show these boxes of extra data. Reopening.

**Comment by Jegelewicz** [comment]
@DerekSikes I think this is an infrastructure issue, but I'll let Dusty confirm...
