### ISSUE TITLE
Missing comma error

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1957]
[UTEP ENT 2017_07_27 Media.zip](https://github.com/ArctosDB/arctos/files/2920202/UTEP.ENT.2017_07_27.Media.zip) 

I am attempting to bulkload this  media metadata using a file format I used just a week or so ago and I get this error:

![image](https://user-images.githubusercontent.com/5725767/53650235-49a9a800-3c01-11e9-8fb8-f2a4d1d01226.png)

I've searched the file for unwanted commas and tried eliminating the trailing blank line and checked to see that there are commas between each field of each line. I'm stumped.

**Comment by dustymc** [comment]
It's your header:

MEDIA:RELATED:TERM:2,

SQL: insert into cf_temp_media (MEDIA_LABEL_1,MEDIA_LABEL_VALUE_1,MEDIA_LICENSE,MEDIA_TYPE,MEDIA_URI,MIME_TYPE,PREVIEW_URI,MEDIA_RELATIONSHIP_2,MEDIA:RELATED:TERM:2,MEDIA_LABEL_2,MEDIA_LABEL_VALUE_2,MEDIA_LABEL_3,MEDIA_LABEL_VALUE_3,MEDIA_RELATIONSHIP_1,MEDIA_RELATED_TERM_1,username) values ('MD5 checksum','dec2e91d097ad2cbbddbea49d29373ab','CC BY','image','https://web.corral.tacc.utexas.edu/arctos-s3/jegelewicz/2019-02-25/UTEP_ENTO_100289.JPG','image/jpeg','https://web.corral.tacc.utexas.edu/arctos-s3/jegelewicz/2019-02-25/tn/tn_UTEP_ENTO_100289.jpg','shows cataloged_item','UTEP:Ento:100289','description','dorsal view of specimen from top of pin','made date','2017-07-27','created by agent','Luis Amezcua','jegelewicz')

**Comment by Jegelewicz** [comment]
DOH! Thanks man!
