### ISSUE TITLE
Geography not real

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1958]
http://arctos.database.museum/Locality.cfm?Action=editGeog&geog_auth_rec_id=1005762

Coronino is not a county in AZ and all specimens associated with this should probably be in Cococino County, AZ.

Can we have a way to mark these like we do bad/duplicate Agents?

**Comment by dustymc** [comment]
I don't think we necessarily need a procedure - this should be very rare. I have scripts and can merge this stuff. I'll just move them to AZ (no county) and put the old stuff in verbatim locality if they don't get cleaned up before I get to them.

@acdoll these are mostly DMNS - @Jegelewicz  can you ping Andy about the MSB specimen?

**Comment by Jegelewicz** [comment]
I annotated the MSB record and it looks like it has already been corrected.
