### ISSUE TITLE
View Edit Archive- Reword to avoid confusion

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#1960]
Current wording of "View Edit Archive" on Collecting Event edit pages could be seen as 3 verbs in a row....

One suggestion to make more clear: **View Edit History**

But open to others! (an easy one to tweak!)

![screenshot-arctos database museum-2019 03 08-14-08-58](https://user-images.githubusercontent.com/2523089/54059404-e0e89f80-41ad-11e9-8a6d-2cb1abdd011e.png)

**Comment by campmlc** [comment]
I agree with this change.

**Comment by Jegelewicz** [comment]
Agree
