### ISSUE TITLE
Tool to bulk upload media relationships and/or labels

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1961]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
I have media that exist in Arctos with labels and relationships, however, I need to add a relationship to a new project.

**Describe the solution you'd like**
A bulkload tool that will allow me to add labels and relationships to existing media.

**Describe alternatives you've considered**
Manually adding the new relationship to over 500 images with the "edit Media" function. (UGH)

**Additional context**
I am attaching a file that I think might be a start for creating the tool.

**Priority**
I would like to have this resolved by date: 2019-03-31
[Project Media.zip](https://github.com/ArctosDB/arctos/files/2954447/Project.Media.zip)

**Comment by dustymc** [comment]
If this is for ADD only, it's not much of a problem. If it's for something else it's likely more of a problem.

Does adding media-stuff work for everyone, or is there a need for something more complicated?

Media_URI should be more or less stable now that we're using the S3 mechanism and it's probably OK to use that for this, but media_URI would be easier to work with/less likely to have random typos/etc. Can you easily get media_id or should this be built around the URI?

**Comment by Jegelewicz** [comment]
I think it is pretty easy to get media ID from a specimen search and download with media - that's how I got them for the upload I sent that you already loaded.

I only need to add for now, but I can also see where delete might be useful. If it's better to create a multi-purpose tool now, then I'm OK with it - I'd just like to get some of this done so that I can present some projects to the world...

**Comment by dustymc** [comment]
>better to create a multi-purpose tool now,

I always prefer simple, but only if that's useful.

>delete

Anyone use the otherID unloader yet? At least in theory I like the idea of two simple tools (loader, unloader) but some practical experience would be useful.

**Comment by Jegelewicz** [comment]
> At least in theory I like the idea of two simple tools (loader, unloader) but some practical experience would be useful.

I agree with the loader, unloader tool option. It helps to keep things simple.

**Comment by Jegelewicz** [comment]
I want to finish up a project page. @dustymc can you add the relationship for these media to this project?
[Project Media.zip](https://github.com/ArctosDB/arctos/files/3563983/Project.Media.zip)

**Comment by dustymc** [comment]
New pair of loaders, completely untested, in test.

**Comment by Jegelewicz** [comment]
Working on testing - observation

For agents, could we be able to use preferred name - looking up a bunch of Agent ID's might make some people bummed. Same goes for loans (Guid prefix + Loan number).

Also, unable to load a file with "describes taxon_name" relationship to "Tachytes"

Here is error:

An error occurred while processing this page!
Message: Error invoking external process
Detail: psql:/usr/local/webroot/temp/excopy_jegelewicz_20200804060857395_109.sql:7: ERROR: invalid input syntax for integer: "Tachytes" CONTEXT: COPY cf_temp_media_relations_ldr, line 5, column related_key: "Tachytes"
Check the Arctos Handbook for more information on errors.

This message has been logged as 10E2CD34-C4D0-449A-A46BAEE76303296A Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue. 

How do you get the "numeric identifier" for a taxon name? I was under the impression this wasn't a thing....

**Comment by dustymc** [comment]
>agents

Sure, but Phase Two I think - I'm still trying to figure out how these can replace/be used by/complement/something the "main" media loader...

>loans

Not until https://github.com/ArctosDB/arctos/issues/1598, but yea

>error

Check your headers.

>"numeric identifier" for a taxon name? 

http://test.arctos.database.museum/editTaxonomy.cfm?action=editnoclass&taxon_name_id=1916012

**Comment by Jegelewicz** [comment]
OK - I was looking at the classification - which is where you are when you search on a taxon name so this requires the extra step of going to "name and related"....so being able to just use the name would be ideal.

**Comment by Jegelewicz** [comment]
Suggest we call this Bulkload Media Relationships Tool - Media Relations sounds like a marketing/political thing

Also a couple of spelling things - well, I just boldly changed them and committed....tell me if you don't want me to do that.

**Comment by Jegelewicz** [comment]
Loaded and set to autoload - do I need to kick it in the pants to make it load?

**Comment by dustymc** [comment]
>ideal

Yup, but I think still Phase Two unless there's some immediate pressing need.

>Suggest we....
>committed

My favorite kind of "suggestion"! I pulled to the server, we should figure out how to get you access or automate the pull or something if you want to make a habit of that...

Yes still no automation on test, same link as before.

**Comment by Jegelewicz** [comment]
> we should figure out how to get you access or automate the pull or something if you want to make a habit of that...

Whatever we need to do and I'll gladly correct spelling errors or modify text and do my very best to not mess around with anything that is calling a function or doing anything beyond my limited capabilities!

**Comment by Jegelewicz** [comment]
OK looks like the relationships thing worked for me:
![image](https://user-images.githubusercontent.com/5725767/89356895-344d6e80-d67c-11ea-9e51-3d6e1b2f3974.png)

But would be nice if they also linked back to the agent/loan...

**Comment by Jegelewicz** [comment]
Just de-relashionshipped the media label bulkload tool stuff and committed.

**Comment by dustymc** [comment]
>linked back to the agent

Just needs an Issue prioritized - there's probably some other stuff that could be linked as well.

>/loan

That's a bit more complicated - it'll just 404 for the vast majority of users. I actually don't think that's ever really useful from the media end of the relationship, not that that's illuminating....

>committed

I pulled and sent Chris email re access.
