### ISSUE TITLE
Project Titles

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1962]
I created a bunch of projects this weekend and noticed that project titles are aligned left, but associated agents are aligned center:

![image](https://user-images.githubusercontent.com/5725767/54162441-18a84f00-441b-11e9-881f-b93d6aec6f80.png)

Which makes the project pages look funny. I figured out that I can use markdown to center the project title:

![image](https://user-images.githubusercontent.com/5725767/54162491-3f668580-441b-11e9-8a4d-beb140c8aa8f.png)

Which looks nice on the project page, but crappy on the Agent pages:

![image](https://user-images.githubusercontent.com/5725767/54162543-6cb33380-441b-11e9-9483-86b7c65c3885.png)

Is there a way that the title can appear centered on the project page, but left aligned on the Agent pages?

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/2570
