### ISSUE TITLE
Changes to the Publication/Project Search/Edit pages

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1970]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
Publication and Project numbers are hidden.

**Describe the solution you'd like**
I'd like to be able to search on publication and project numbers AND to see the publication or project number on the publication/project page/edit page. Also, to have the "Title or full citation" field be larger.

**Describe alternatives you've considered**
I can find these number by searching for the project title and looking in the url, but I'd like to use them more often as they are shorter than the full publication/project citations.

**Additional context**
![image](https://user-images.githubusercontent.com/5725767/54386047-b5f2c580-465d-11e9-9ca8-33c6fac6b732.png)

![image](https://user-images.githubusercontent.com/5725767/54386233-1e41a700-465e-11e9-9bc0-859943c011c1.png)

![image](https://user-images.githubusercontent.com/5725767/54386470-a2942a00-465e-11e9-8a0d-932966652ccb.png)

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/3468
