### ISSUE TITLE
Add "managed by" to non-classification terms

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1972]
Could we add a field in the classification metadata:

Managed by

Arctos Agent who is managing the taxon (we should add WoRMS as an agent for stuff being updated by WoRMS)

This would help everyone understand which taxa are being actively managed and provide a point of contact for anyone who has questions about the taxon. Stuff with "unknown" or no Managed_by agent are up for grabs if someone wants to manage them.

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/arctos/issues/1939#issuecomment-466394356_

>with the ability to add more than one agent name? date?

I think one is sufficient. If someone managing a taxon leaves Arctos, they either need to pass it on to someone else or it will be up for grabs again. This isn't going to stop anyone from editing, but it will be socially unacceptable if someone does...

I don't think a date is necessary.

>I'd recommend just adding last_edit_by FKEY(agent) to taxon_term and populate with from user environment

I don't like this - I want it to be an intentional choice. Last edited by means EVERY taxon will have a "manager" which isn't necessarily true. Just because I edited a classification, doesn't mean I want to own it or that I care if someone with more knowledge decides to make it better. This should be a field we have to intentionally complete (or not - it is not required), and should be a controlled by the Arctos Agent names list. It should be part of the taxonomy bulkloader and hierarchical tool.

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/arctos/issues/1939#issuecomment-466475220

**Comment by Jegelewicz** [comment]
Values would be controlled by Arctos Agent table (can we limit to operators?).

Before altering a classification, it will be polite to contact the manager of the taxon.

Rather than using "WoRMS" as the agent managing any taxon with an aphiaID, the agent should be the person who decided to use WoRMS.

Providing an aphiaID would allow the classification to auto-update from WoRMS.

Anything else?

**Comment by sharpphyl** [comment]
> Rather than using "WoRMS" as the agent managing any taxon with an aphiaID, the agent should be the person who decided to use WoRMS.

Are you asking us to take ownership of a taxon name or just a classification within that taxon name?  Now that our collection is using WoRMS (via Arctos) as our source, all of our taxa are "managed" by the WoRMS aphiaID autoupdate.  But the Arctos classification within the same taxon name isn't unless someone added the aphiaID and Dusty has a program to update classifications wherever there's a aphiaID.  (Again, everyone using that taxon should be notified that it's now on autoupdate and the classification could change without notice.)

I think simply having an edit record with the agent name is sufficient without taking "ownership" and adding another field and layer of complexity.  Anyone who adds a taxon is listed as the creator and automatically owns it.

The exceptions to the autoupdate in WoRMS (via Arctos) are taxa that I've added because they are not yet in WoRMS (mostly terrestrial snails).  I should already be listed as the one who created the taxon so anyone with questions about it can contact me.  

A link to my email would make that easier and I would support adding that feature.  I seldom know who people are or how to contact them without bugging Dusty.

**Comment by dustymc** [comment]
We can easily add string-terms.

>Values would be controlled by Arctos Agent table (can we limit to operators?).

That is much less trivial.

>everyone using that taxon should be notified

That should be another Issue. I'm not keeping those data at this time, it would be a fair bit of processing, and the notifications have the potential to be large. I'd suggest that adding an AphiaID to a "WoRMS (via Arctos)" classification is an explicit agreement to do accept whatever they do.  You can use their API to find things that have changed.

**Comment by Jegelewicz** [comment]
> Are you asking us to take ownership of a taxon name or just a classification within that taxon name? 

The classification

> Now that our collection is using WoRMS (via Arctos) as our source, all of our taxa are "managed" by the WoRMS aphiaID autoupdate. But the Arctos classification within the same taxon name isn't unless someone added the aphiaID and Dusty has a program to update classifications wherever there's a aphiaID. (Again, everyone using that taxon should be notified that it's now on autoupdate and the classification could change without notice.)

Yes, so if a collection is using the "WoRMS (via Arctos)" source, then they understand that the classifications are maintained by WoRMS. IF a collection is using the "Arctos" or "Arctos Plants" sources, and an aphiaID is assigned to a taxon, then there should also be a "managed by" agent - the person who chose to let WoRMS manage the classification.



>     Values would be controlled by Arctos Agent table (can we limit to operators?).
> 
> That is much less trivial.

OK, just checking - just the Agent table should be fine anyway.

>     everyone using that taxon should be notified
> 
> That should be another Issue. I'm not keeping those data at this time, it would be a fair bit of processing, and the notifications have the potential to be large. I'd suggest that adding an AphiaID to a "WoRMS (via Arctos)" classification is an explicit agreement to do accept whatever they do. You can use their API to find things that have changed.

This is a social issue, just as with localities we should be aware that others are or could be using any given classification and take care when making changes. I agree that the addition of an aphiaID is an agreement to accept whatever they do and that's why for Arctos and Arctos Plants, I'd like to be able to see WHO made that decision (managed by) so that if I want to have a conversation about the choice, I know who to contact.

**Comment by Jegelewicz** [comment]
I'd like the committee to move on to managing sections of taxonomy - with this functionality we could track what's happening and let users know if a taxon is being actively managed or not.

**Comment by Jegelewicz** [comment]
Added term in classification metadata "managed_by" for entry of names as strings.

Wish list to link field to Agents after migration to PostGRESQL.

**Comment by Jegelewicz** [comment]
@dustymc do you need to do something special to make this field available in the taxonomy bulkloader? :-)

**Comment by dustymc** [comment]
Yes and I need a way to test it - please send CSV, one record should be plenty.

**Comment by Jegelewicz** [comment]
I hope this will give you enough to work with.
[Taxonomy Classification Test Upload.zip](https://github.com/ArctosDB/arctos/files/3631725/Taxonomy.Classification.Test.Upload.zip)

**Comment by sharpphyl** [comment]
Where does this stand?  I'm working on WoRMS (via Arctos) classifications without an aphiaID and I add myself as the person who manages the classification, but it's an open field rather than being linked to my agent record.

**Comment by dustymc** [comment]
>Where does this stand?

Nowhere very actionable - it's some sort of functional redesign, and I'm still not quite sure I imagine it working.

https://github.com/ArctosDB/arctos/issues/2231 should solve this, along with a bunch of other stuff. Suggest we prioritize it instead.

**Comment by dustymc** [comment]
Suggest

* remove this term
* document who's managing sources via https://github.com/ArctosDB/arctos/issues/3019
* use via https://github.com/ArctosDB/arctos/issues/2231 to get "your" classifications to "your" records

**Comment by sharpphyl** [comment]
I'd vote to keep it in but it doesn't have to link to the "agent" record if that's a big deal.

**Comment by dustymc** [comment]
Merging with https://github.com/ArctosDB/arctos/issues/3121; this can/should be done at the source now.
