### ISSUE TITLE
Integration with Zoo ZIMS database

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1977]
I am filing this issue to document the process of integrating zoo specimen identifiers and ZIMS database records with Arctos. As part of this process, I will be adding a new identifier, GAN (Global Accession Number)  used internationally to identify zoo organisms. Each individual zoo also assigns a local ID in addition to the GAN number. This information is relevant to our discussion of assigning global organism IDs at #1966..

Documentation for ZIMS database http://training.species360.org/Documents/Modules/Best%20Practices%20in%20Animal%20Record%20Keeping.pdf

**Comment by Jegelewicz** [comment]
So, do the Mex Wolves at zoos also have one of these IDs?

**Comment by campmlc** [comment]
Good question. I'm sure the Abq wolves do. But not all Mexican wolves are
at zoos.

**Comment by Jegelewicz** [comment]
@mkoo @campmlc the ZIMS Best Practices is quite nice. A lot of it is just as applicable to Arctos....

**Comment by campmlc** [comment]
It would be nice if ZIMS and Arctos could form some sort of linkage -maybe
to our entity page?

**Comment by dustymc** [comment]
Seems to be done to the extent currently possible.
