### ISSUE TITLE
Report modifications needed for loan form

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1979]
I need the following loan form to be duplicated as a new form in Arctos reports, called "MSB Zoo Loan Invoice" with the following changes:
1) replace NK as the identifier with the ID "Albuquerque Biopark Zoo Local ID", and call the column "Local ID / RIO GRAND"
2) Add a column for the data of collection

**Comment by dustymc** [comment]
http://handbook.arctosdb.org/how_to/How-to-Create-Labels.html

**Comment by Jegelewicz** [comment]
I'm working on this.

**Comment by Jegelewicz** [comment]
@campmlc which form do you want duplicated?

**Comment by campmlc** [comment]
This is the MSB Mamm loan invoice form.  Thanks!

**Comment by Jegelewicz** [comment]
I'll look at it when I have a bit of down time tomorrow...

**Comment by Jegelewicz** [comment]
@campmlc I modified the report: Albuquerque_BioPark_Zoo_Specimens.cfr but I don't think the handler is pulling the date of collection so I can't add it to the report. @dustymc can you confirm that?

**Comment by dustymc** [comment]
Looked like flat is hooked in - you can just add began_date and/or ended_date if those are sufficient.

**Comment by Jegelewicz** [comment]
@dustymc here is the error that I am getting:

![image](https://user-images.githubusercontent.com/5725767/57104867-a9e2c600-6ce6-11e9-9e75-046af71ddf7c.png)
 Report Handler is ABQ_Biopark_Loan

**Comment by dustymc** [comment]
Albuquerque Biopark Zoo Local ID,

isn't a valid alias. (Sorta - you can double-quote it and make it work, but then it'll break coldfusion.)

**Comment by Jegelewicz** [comment]
OK - I got that to work. Now, how do I get the date of collection (began date is fine) into the report?

**Comment by dustymc** [comment]
added to handler - began_date should work in the report.

**Comment by Jegelewicz** [comment]
Woo hoo! I think we did it! @campmlc can review and close...

**Comment by campmlc** [comment]
Yay! It works!!
Thanks, Teresa and Dusty!
Now maybe I can try to figure out what you did . . .
