### ISSUE TITLE
ASNHC label

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1980]
I modified MSB_mamm_small_label.cfr for Angelo State (see ASNHC_mamm_small_label.cfr ) and I get the following error when I try to use the new report:

![image](https://user-images.githubusercontent.com/5725767/54545015-6581ad80-4966-11e9-9521-589aa1dff65b.png)

I don't see NMMNH anywhere in the handler or the pre-function. @dustymc can you help me out?

**Comment by dustymc** [comment]
It's probably in the report itself. I can scrounge up a Windows machine later this week if necessary.

**Comment by Jegelewicz** [comment]
OK, got it working.
