### ISSUE TITLE
Donate Barcode not working?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1981]
We are trying to use the scary red box to donate barcodes to labels and the process never completes.

We have attempted with several different cryovials and barcodes and it seems that Arctos never completes the donation. I used the tool for an entire box this morning and it worked fine.

Example we have been trying is donating barcode A6S3Z to label NK 197200 KX and we get this:

![image](https://user-images.githubusercontent.com/5725767/54565726-a690b680-4994-11e9-926e-f1741d884cd4.png)

**Comment by dustymc** [comment]
Basically everything was tangled up with everything else. Should be happy when I bring it up in a few minutes....
