### ISSUE TITLE
Locality nicknames - TEMP::10478780

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#1983]
Are locality nicknames (see TEMP::10478780) being added?  Edit archive shows "unknown" as having made the last change 2019-03-15.  

**To Reproduce**
Check out locality 10478780 - Sri Lanka, no specific locality recorded.  
Same with locality TEMP::10000000 so it must be throughout Arctos.

I would prefer to not have a nickname on this locality for our specimens.  Do I need to create a new locality without a nickname and move them or is this a temporary nickname?

**Comment by dustymc** [comment]
It is temporary for @anna-chinn.

**Comment by Jegelewicz** [comment]
What do people have against the nicknames? They make a locality stable for future use by anyone. I get it when they are something like "My House", but how about the generated ones, which are just gibberish? I'm just curious....

**Comment by sharpphyl** [comment]
Thanks.  No problem if it's temporary.  I seldom use nicknames so I may be missing the opportunity.

**Comment by dustymc** [comment]
>just gibberish

It's an identifier that serves a purpose at the scope of Arctos. "My house" doesn't mean anything useful to anyone except the person who created it (and probably not to them in the long term), it's just a convenient way to access a locality and to keep that locality from being script-maintained.

This particular gibberish exists (also temporarily) in some data which will be used to create new events.

**Comment by Jegelewicz** [comment]
I prefer the just gibberish nicknames (assigned by Arctos) unless I have a good reason to create an understandable (by humans) name for one (like the UTEP Paleo Sites).

> a convenient way to access a locality and to keep that locality from being script-maintained.

That's why I'm trying to understand the opposition to their use.
