### ISSUE TITLE
Arctos Mark to load not working?

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#1984]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Marked to load yesterday and records still not loading into the database or kicking back with error messages

**To Reproduce**
Mark to load?

**Expected behavior**
records to load every hour or so?

**Screenshots**
![image](https://user-images.githubusercontent.com/38706617/54633950-cbddfd00-4a46-11e9-95ca-44f6b9020787.png)

**Desktop (please complete the following information):**
 Chrome / Windows 10

**Additional context**
not sure if this is just mine being funky because I marked it to load before maintenance yesterday?
**Priority**

**Comment by dustymc** [comment]
Thanks Vicki - it was caught up in the logjam yesterday, it should be happy now and things are loading.
