### ISSUE TITLE
Tissue controlled vocabulary

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1985]
May be useful some day

https://www.uniprot.org/docs/tisslist.txt

**Comment by campmlc** [comment]
This is interesting and useful, but I disagree with putting the adjective
first.

**Comment by dustymc** [comment]
It also confounds parts with other stuff, like age class. 

>Fetal astrocyte.

**Comment by Jegelewicz** [comment]
closing for lack of interest
