### ISSUE TITLE
Additions to code table GEOLOGY_ATTRIBUTE

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#1986]
Add Ladd Formation https://en.wikipedia.org/wiki/Ladd_Formation
Add Holz Shale as a Member

![Holz Shale in Ladd Formation](https://user-images.githubusercontent.com/15368365/54640504-97257200-4a55-11e9-85df-dc1505f88ef1.JPG)

need by next Tuesday March 26

**Comment by Jegelewicz** [comment]
Done.
