### ISSUE TITLE
Is duplicate event/locality automerging working?

### ISSUE THREAD

**Issue by anna-chinn** [ArctosDB/arctos#1987]
I've noticed that some duplicate events/localities that I created during a specimen event bulkload last month are still around, though I would have expected them to be automatically merged. Am I missing something that's preventing them from merging?
e.g. https://arctos.database.museum/duplicateLocality.cfm?locality_id=10985279

Edit: Also, how frequently do the maintenance scripts run?

**Comment by dustymc** [comment]
It looks like it is failing on dates which don't pass the triggers.

https://github.com/ArctosDB/arctos/issues/1716

I'll comment there, and if nothing useful happens I can add better "error" handling or similar to the merge procedure.

**Comment by dustymc** [comment]
elevating this - I'll add error handlers, I don't think we're going to clean up the data now prevented by triggers anytime soon.

@anna-chinn the scripts run constantly after a 30-day pause when localities are created. How long it takes them to find a particular record is wildly variable depending on what's happened in that 30 days. I think everything probably gets found within a couple months of being created, but no promises.

**Comment by dustymc** [comment]
rebuilt event data validation triggers so the scripts can bypass them; "invalid" events should no longer cause blockage and everything seems to be happily running again.
