### ISSUE TITLE
minimum elevation greater than maximum elevation

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1989]
```
create table temp_elevation_problem as
select
  guid_prefix,
  guid_prefix || ':' || cat_num guid,
  locality.locality_id
from 
  collection,
  cataloged_item,
  specimen_event,
  collecting_event,
  locality 
where
  collection.collection_id=cataloged_item.collection_id and 
  cataloged_item.collection_object_id=specimen_event.collection_object_id and
  specimen_event.collecting_event_id=collecting_event.collecting_event_id and 
  collecting_event.locality_id=locality.locality_id and
  to_meters(MINIMUM_ELEVATION,ORIG_ELEV_UNITS) > to_meters(MAXIMUM_ELEVATION,ORIG_ELEV_UNITS)
 18  ;

UAM@ARCTOS> select guid_prefix, count(*) from temp_elevation_problem group by guid_prefix;

GUID_PREFIX						       COUNT(*)
------------------------------------------------------------ ----------
CHAS:Ento							      1
UAM:Herb							    135
MSB:Bird							     53
UAMb:Herb							      2
UNR:Mamm							      4
UTEP:Herb							      6
UTEP:Inv							     45
DMNS:Mamm							    118
MLZ:Mamm							     31
UTEP:Herp							     14
MSB:Para							     20
UTEP:HerpOS							     14
DMNS:Bird							     91
MLZ:Bird							    156
UTEP:Bird							      4
MSB:Mamm							    135
MSB:Herp							      2
MVZ:Mamm							     21
MVZ:Herp							     20
UWBM:Herp							      1
MSB:Host							     40

21 rows selected.

```
[temp_elevation_problem.csv.zip](https://github.com/ArctosDB/arctos/files/2985644/temp_elevation_problem.csv.zip)

These are breaking the locality merge scripts so I'm filing this with priority critical.

Let me know how I can help...

**Comment by Jegelewicz** [comment]
I got the UTEP stuff fixed.

**Comment by Jegelewicz** [comment]
HMMMM, this one is technically correct, but the location is below sea level (not under water).

http://arctos.database.museum/editLocality.cfm?locality_id=10470219

**Comment by Jegelewicz** [comment]
Also got the MSB:Para (and a few MSB:Mamm that were in the same locations)

**Comment by dustymc** [comment]
@Jegelewicz 10470219 is backwards - -175 is "above" -185

**Comment by Jegelewicz** [comment]
Yeah, realized that when I woke up this am...

**Comment by Jegelewicz** [comment]
@dustymc I suggest another trigger - elevation can't be higher than 8,900 m or29,200 ft. Some of the above problems were caused by both elevations being placed in one (min or max) field, so we had min elevation of 21622212!

**Comment by dustymc** [comment]
Done, without the coordinates. Elevation references the planet's surface. If someone's sampling at height we could introduce 'altitude' (or maybe use negative depth...). I'm actually a little surprised that people mist-netting birds haven't brought that up yet.

**Comment by Jegelewicz** [comment]
@atrox10 locality 10478192 has:

Min Elevation: 7935
Max Elevation: 7035

I'm not sure if it should have both Min/Max as one or the other or if it should be Min 7035, Max 7935

**Comment by Jegelewicz** [comment]
@dustymc the remaining MSB:Mamm records with this problem are all "locked and verified" which makes it a pain to correct them. They just need to have the min and max switched. Can you do that for me?

**Comment by dustymc** [comment]
Yep, just confirm that this is them and that they just need switched:

select locality_id,MINIMUM_ELEVATION,MAXIMUM_ELEVATION,ORIG_ELEV_UNITS from LOCALITY where LOCALITY_id in (
select locality_id from temp_elevation_problem where guid_prefix='MSB:Mamm' and LOCALITY_id not in (select locality_id from temp_elevation_problem where guid_prefix != 'MSB:Mamm')
  3  );

LOCALITY_ID MINIMUM_ELEVATION MAXIMUM_ELEVATION
----------- ----------------- -----------------
ORIG_ELEV_UNITS
------------------------------------------------------------------------------------------
   10485967		   30		     10
m

   10485965		  680		    660
m

   10485914		  720		    700
m

   10485956		  680		    660
m

   10485936		  690		    670
m

   10485942		  710		    690
m

   10485951		  720		    700
m

   10485896		   20		      0
m

   10485902		   40		     20
m

   10485947		  720		    700
m

   10485962		  710		    690
m

   10485920		  900		    880
m

   10485964		  680		    660
m

   10485946		  720		    700
m

   10485940		  690		    670
m

   10485921		  910		    890
m

   10485912		  730		    710
m

   10485929		  720		    700
m

   10485932		  680		    660
m

   10485913		  720		    700
m

   10485972		  670		    650
m

   10485943		  710		    690
m

   10485937		  690		    670
m

   10485938		  690		    670
m

   10485959		  690		    670
m

   10485904		  680		    660
m

   10485930		  720		    700
m

   10485968		   30		     10
m

   10485899		  690		    670
m

   10485906		  720		    700
m

   10485897		  670		    650
m

   10485911		  740		    720
m

   10485953		  710		    690
m

   10485939		  690		    670
m

   10485944		  710		    690
m

   10485949		  720		    700
m

   10485935		  710		    690
m

   10485952		  680		    660
m

   10485958		  680		    660
m

   10485927		  860		    840
m

   10485918		  520		    500
m

   10485945		  720		    700
m

   10485941		  680		    660
m

   10485917		  520		    500
m

   10485926		  710		    690
m

   10485971		  670		    650
m

   10485961		  680		    660
m

   10485963		  670		    650
m

   10485908		   30		     10
m

   10485916		   40		     20
m

   10485919		  670		    650
m

   10485950		  720		    700
m

   10485928		  720		    700
m

   10485931		  720		    700
m

   10485960		  690		    670
m

   10485954		  690		    670
m

   10485898		  680		    660
m

   10485934		  700		    680
m

   10485922		  870		    850
m

   10485910		   20		      0
m

   10485969		  730		    710
m

   10485933		  700		    680
m

   10485905		  680		    660
m

   10485948		  720		    700
m

   10485955		  680		    660
m

   10485903		  730		    710
m

   10485925		  720		    700
m

   10485915		   40		     20
m

   10485909		   20		      0
m

   10485923		  720		    700
m

   10485957		  680		    660
m


71 rows selected.

**Comment by Jegelewicz** [comment]
Yep! Thanks!

**Comment by dustymc** [comment]
More fun:

```

create table temp_more_elevation_problem as
select
  guid_prefix,
  guid_prefix || ':' || cat_num guid,
  locality.locality_id
from 
  collection,
  cataloged_item,
  specimen_event,
  collecting_event,
  locality 
where
  collection.collection_id=cataloged_item.collection_id and 
  cataloged_item.collection_object_id=specimen_event.collection_object_id and
  specimen_event.collecting_event_id=collecting_event.collecting_event_id and 
  collecting_event.locality_id=locality.locality_id and
  (
    to_meters(MINIMUM_ELEVATION,ORIG_ELEV_UNITS) < -413 or to_meters(MAXIMUM_ELEVATION,ORIG_ELEV_UNITS) > 8900 
  );

Elapsed: 00:00:00.03
UAM@ARCTOS> select guid_prefix,count(*) from temp_more_elevation_problem group by guid_prefix;

GUID_PREFIX						       COUNT(*)
------------------------------------------------------------ ----------
MSB:Fish							      1
UAM:Herb							      3
UTEP:Herb							      3
UAM:Ento							     15
MSB:Para							      4
MVZ:Bird							     20
DMNS:Bird							      1
MSB:Mamm							     16
MVZ:Mamm							      3
MVZ:Herp							     21

10 rows selected.

```
[temp_more_elevation_problem.csv.zip](https://github.com/ArctosDB/arctos/files/2989830/temp_more_elevation_problem.csv.zip)

**Comment by dustymc** [comment]
MSB is done except the one which is shared. Here's what's left re:min>max

GUID_PREFIX						       COUNT(*)
------------------------------------------------------------ ----------
UAM:Herb							     83
UAMb:Herb							      2
DMNS:Mamm							    112
MSB:Para							      1
DMNS:Bird							     69
MSB:Mamm							      1
MVZ:Mamm							     20


[temp_elevation_problem(1).csv.zip](https://github.com/ArctosDB/arctos/files/2989853/temp_elevation_problem.1.csv.zip)

**Comment by Jegelewicz** [comment]
I'm working my way through those. The too high ones probably need people from those collections to check them because it could be they just have the wrong units (11,000 m is not valid, but 11,000 ft is...)

**Comment by dustymc** [comment]
Here's the data with elevation in original and meters.

```
drop table temp_more_elevation_problem;

create table temp_more_elevation_problem as
select
  guid_prefix,
  guid_prefix || ':' || cat_num guid,
  locality.locality_id,
  MINIMUM_ELEVATION,
  MAXIMUM_ELEVATION,
  ORIG_ELEV_UNITS,
  to_meters(MINIMUM_ELEVATION,ORIG_ELEV_UNITS) minInMeters,
  to_meters(MAXIMUM_ELEVATION,ORIG_ELEV_UNITS) maxInMeters
from 
  collection,
  cataloged_item,
  specimen_event,
  collecting_event,
  locality 
where
  collection.collection_id=cataloged_item.collection_id and 
  cataloged_item.collection_object_id=specimen_event.collection_object_id and
  specimen_event.collecting_event_id=collecting_event.collecting_event_id and 
  collecting_event.locality_id=locality.locality_id and
  (
    to_meters(MINIMUM_ELEVATION,ORIG_ELEV_UNITS) < -413 or to_meters(MAXIMUM_ELEVATION,ORIG_ELEV_UNITS) > 8900 
  );
```
[temp_more_elevation_problem(1).csv.zip](https://github.com/ArctosDB/arctos/files/2990264/temp_more_elevation_problem.1.csv.zip)

**Comment by Jegelewicz** [comment]
I got the MSB and UTEP higher than you can gos...

**Comment by Jegelewicz** [comment]
OK, all of the higher than Everest elevations are fixed except:

![image](https://user-images.githubusercontent.com/5725767/54722675-a62a2400-4b2a-11e9-9ee0-2eea1d0b9cd7.png)

I don't know if there happens to be an extra digit in them or if it should be ft instead of m

**Comment by Jegelewicz** [comment]
Man, I'm beat. Any chance you could send me what's left in this format: https://github.com/ArctosDB/arctos/issues/1989#issuecomment-474997823

I think I could probably look through them and have you switch most of them like you did the MSB stuff rather than me going one-by one through them and doing it manually.

**Comment by dustymc** [comment]
Here's a merged view; I can't keep up with myself in here...

```

create table temp_merge_elevation_problem as
select
  guid_prefix,
  guid_prefix || ':' || cat_num guid,
  locality.locality_id,
  MINIMUM_ELEVATION,
  MAXIMUM_ELEVATION,
  ORIG_ELEV_UNITS,
  to_meters(MINIMUM_ELEVATION,ORIG_ELEV_UNITS) minInMeters,
  to_meters(MAXIMUM_ELEVATION,ORIG_ELEV_UNITS) maxInMeters,
  'out_of_bounds' cause
from 
  collection,
  cataloged_item,
  specimen_event,
  collecting_event,
  locality 
where
  collection.collection_id=cataloged_item.collection_id and 
  cataloged_item.collection_object_id=specimen_event.collection_object_id and
  specimen_event.collecting_event_id=collecting_event.collecting_event_id and 
  collecting_event.locality_id=locality.locality_id and
  (
    to_meters(MINIMUM_ELEVATION,ORIG_ELEV_UNITS) < -413 or to_meters(MAXIMUM_ELEVATION,ORIG_ELEV_UNITS) > 8900 
  )
  union
select
  guid_prefix,
  guid_prefix || ':' || cat_num guid,
  locality.locality_id,
  MINIMUM_ELEVATION,
  MAXIMUM_ELEVATION,
  ORIG_ELEV_UNITS,
  to_meters(MINIMUM_ELEVATION,ORIG_ELEV_UNITS) minInMeters,
  to_meters(MAXIMUM_ELEVATION,ORIG_ELEV_UNITS) maxInMeters,
  'min_more_max' cause
from 
  collection,
  cataloged_item,
  specimen_event,
  collecting_event,
  locality 
where
  collection.collection_id=cataloged_item.collection_id and 
  cataloged_item.collection_object_id=specimen_event.collection_object_id and
  specimen_event.collecting_event_id=collecting_event.collecting_event_id and 
  collecting_event.locality_id=locality.locality_id and
  to_meters(MINIMUM_ELEVATION,ORIG_ELEV_UNITS) > to_meters(MAXIMUM_ELEVATION,ORIG_ELEV_UNITS)
  ;
```

Let me know if you want something else.

[temp_merge_elevation_problem.csv.zip](https://github.com/ArctosDB/arctos/files/2990483/temp_merge_elevation_problem.csv.zip)

**Comment by dustymc** [comment]
I can't easily avoid these in the merger scripts.

I convinced them they've been recently checked, which should keep the scripts running for a couple of weeks. If this hasn't been resolved by then I'll do something - move the offending data to remarks maybe? I dislike doing that, but not as much as I dislike impossible data. AWG, can we develop some sort of policy or ???

/remind 2019-04-04

**Comment by dustymc** [comment]
/remind me to check Issue 1989 in 2 weeks

**Comment by Jegelewicz** [comment]
I suggest we flip max and min for all of the attached (can you magic that, please?). This will leave the few that I have commented on separately above, which I don't feel confident changing.
[elevation errors.zip](https://github.com/ArctosDB/arctos/files/2992875/elevation.errors.zip)
