### ISSUE TITLE
Help with loan invoice form

### ISSUE THREAD

**Issue by srobson4** [ArctosDB/arctos#1993]
Dusty, can you help us create a loan invoice header?  Attached is the layout in ColdFusion report writer (pdf) that we'd like and now just need help making it "work".  We are using the MSB Mammal Invoice Header as the basic template and would like our Museum logo in the upper left corner of the document.  Thank you.

[UMNH VZ loan form.pdf](https://github.com/ArctosDB/arctos/files/2989617/UMNH.VZ.loan.form.pdf)

![NHMU Black Rio Tinto Logo](https://user-images.githubusercontent.com/18356742/54710047-7d933180-4b0c-11e9-9816-d013c681830d.jpg)

**Comment by Jegelewicz** [comment]
@srobson4 do you have this report in a .cfr format? If so, can you send it to me? Email is fine. If not, I'll work on creating it.

**Comment by srobson4** [comment]
I do!  Github doesn't support .cfr files so I'll email it to you.  Thanks Teresa.

**Comment by Jegelewicz** [comment]
@dustymc I have the image in the report, but when I try to print in Arctos, I get:

![image](https://user-images.githubusercontent.com/5725767/54833276-675bb180-4c83-11e9-86ad-984f235ec2f2.png)

I'm thinking we can put the image in Arctos and reference it in the report? I have no idea what a BLOB is, but if we can figure that out, maybe we can make this work?

![image](https://user-images.githubusercontent.com/5725767/54833365-8fe3ab80-4c83-11e9-9dc7-859bf1892460.png)

**Comment by Jegelewicz** [comment]
BTW - I could not get a JPG to appear properly in the report. The PNG looks good in CF Report Builder, but Arctos doesn't like it.

**Comment by dustymc** [comment]
I'm not sure what half that means, but maybe it's the space - they break everything else, why not this!

What's the image-toolbox-thing look like? Is there am embed option? Can you provide a full URI or is it looking for a relative path?

Try /images/54710047-7d933180-4b0c-11e9-9816-d013c681830d.jpg

**Comment by Jegelewicz** [comment]
Report Builder weirdly saves it as text?

![image](https://user-images.githubusercontent.com/5725767/54835791-7c870f00-4c88-11e9-84fb-7c09b474a4d7.png)

**Comment by Jegelewicz** [comment]
When I first put the image in, it looks like this:
![image](https://user-images.githubusercontent.com/5725767/54835871-a17b8200-4c88-11e9-9fc7-80fd3f81044b.png)

**Comment by Jegelewicz** [comment]
No space makes no difference:

![image](https://user-images.githubusercontent.com/5725767/54836001-eef7ef00-4c88-11e9-854a-16bb7082eaf2.png)

**Comment by Jegelewicz** [comment]
I think that once the report is loaded to Arctos, it doesn't know where to find the image. I'm wondering if the image is uploaded and we can reference it from within Arctos, maybe that would work? But I can't upload the image... #1998

**Comment by dustymc** [comment]
See email to Chris - I think that image is corrupted.

**Comment by anna-chinn** [comment]
I think you can just use a URL as an image path. Ours look like this:
![Capture](https://user-images.githubusercontent.com/40321380/54837708-15238c00-4c95-11e9-8732-9da4dad59f3e.PNG)

**Comment by Jegelewicz** [comment]
@anna-chinn Thanks! @dustymc did you already load the image? If so, how can I find it? If not, I'll try your save as PNG, save as JPG to see if I can make it work.

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/1993#issuecomment-475666574 but https://github.com/ArctosDB/arctos/issues/1993#issuecomment-475683421 - you should probably get a new image, and looks like you can host it anywhere.

**Comment by Jegelewicz** [comment]
@srobson4 can you email a clean JPG image of your logo to me?

**Comment by Jegelewicz** [comment]
The report works now, but it is using the image from GitHub. Not sure if that is stable enough and I would prefer to upload to Arctos, so once I get a clean image, I'll do that and change the image reference.

WooHoo!

**Comment by Jegelewicz** [comment]
Apparently the field "authAgentName" no longer exists or has been changed. All the invoice headers that I can find use this field name to indicate who authorized the loan, which means none of them ever have any information when they are printed.

@dustymc what field name should we be referencing in order to get the name of the person who authorized the loan to print on the loan form?

**Comment by dustymc** [comment]
Thanks for taking this on!

Link the report edit page and I can be more specific, but most loan-things pull from https://github.com/ArctosDB/arctos/blob/master/CustomTags/getLoanFormInfo.cfm which maps authorized by to authAgentName. 

I found some random loan, dumped data for http://arctos.database.museum/Reports/reporter.cfm?action=edit&report_id=5601044, and

<img width="279" alt="Screen Shot 2019-03-22 at 4 13 21 PM" src="https://user-images.githubusercontent.com/5720791/54857598-78291900-4cbd-11e9-91a0-6b8f2e3642a4.png">

**Comment by Jegelewicz** [comment]
@srobson4 I uploaded the logo to Arctos and associated with the [UNMH agent record](http://arctos.database.museum/agents.cfm?agent_id=21274490) so that you can find it when you need it.
