### ISSUE TITLE
Creating How To documents with images for Markdown

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#1994]
Per our discussion at the Taxonomy Committee meeting yesterday, I'm attaching a draft of the How To "Edit a taxon in Arctos."  I'm doing this as an issue so everyone @ArctosDB/taxonomy can benefit from Dusty's instructions.  

The attached draft is from December before we changed our synonym structure so all those screen clips and instructions will need to be changed.  And I'll wait until we change Non-Classification Data to Metadata so I don't have to redo that again.

Dusty, if you can provide some instructions (in my kind of English) on how to  prepare this type of document for the Handbook, I'll go back to the other four I started and try to get them ready - unless we think there are too many changes coming for it to be worthwhile.

While we're about it, is there a font standard we should be using for the text, headings, etc.?

[How to Edit Taxonomy in Arctos 9 Dec 2018.docx](https://github.com/ArctosDB/arctos/files/2992140/How.to.Edit.Taxonomy.in.Arctos.9.Dec.2018.docx)

**Comment by dustymc** [comment]
Font shouldn't matter.

This left some \# hanging around, wild guess because Word has more kinds of headers than MD. You could play around with that in Word (or maybe by saving a rtf or something) or by using a different converter, but honestly I think we're all fine with imperfect formatting - and anyone who isn't can help fix the issues.

Here's what I did. It's certainly not the only way.

----------------

Google

<img width="207" alt="Screen Shot 2019-03-21 at 6 26 30 AM" src="https://user-images.githubusercontent.com/5720791/54755425-2a1ff280-4ba3-11e9-80ce-730e48732848.png">

first result - other things may work better, I don't know?

<img width="368" alt="Screen Shot 2019-03-21 at 6 26 42 AM" src="https://user-images.githubusercontent.com/5720791/54755450-3310c400-4ba3-11e9-864a-e74dac747bf4.png">

upload, convert

<img width="240" alt="Screen Shot 2019-03-21 at 6 27 37 AM" src="https://user-images.githubusercontent.com/5720791/54755463-3906a500-4ba3-11e9-9882-bebd24d54557.png">

front matter

<img width="420" alt="Screen Shot 2019-03-21 at 6 30 19 AM" src="https://user-images.githubusercontent.com/5720791/54755477-3efc8600-4ba3-11e9-8dbc-3c979bb28259.png">

copy

<img width="670" alt="Screen Shot 2019-03-21 at 6 30 37 AM" src="https://user-images.githubusercontent.com/5720791/54755485-4328a380-4ba3-11e9-9f02-aa7f8793380c.png">

paste



<img width="734" alt="Screen Shot 2019-03-21 at 6 31 11 AM" src="https://user-images.githubusercontent.com/5720791/54755522-52a7ec80-4ba3-11e9-97c0-b5a5728a605c.png">

commit

<img width="151" alt="Screen Shot 2019-03-21 at 6 36 07 AM" src="https://user-images.githubusercontent.com/5720791/54755678-b500ed00-4ba3-11e9-8be1-5c5037c15d53.png">


http://handbook.arctosdb.org/how_to/markdown-test.html

images

<img width="576" alt="Screen Shot 2019-03-21 at 6 43 28 AM" src="https://user-images.githubusercontent.com/5720791/54756097-bda5f300-4ba4-11e9-8ab1-9b148760b0b8.png">

**Comment by Jegelewicz** [comment]
> While we're about it, is there a font standard we should be using for the text, headings, etc.?

Font is part of the standard layout.

**Comment by sharpphyl** [comment]
I cleaned up that document (How to Edit Taxonomy in Arctos) to reflect recent changes in those screens and now when I try to convert it to Markdown (same website) no images show.  When I copy everything into the GitHub thingie to create a how_to document, it crashes from too much data.  Learning Markdown wouldn't seem to be the best use of my time.  Can you try again and go ahead and upload it, Dusty, (even though the formatting did need some editing which I couldn't seem to do) or should I rewrite it without any images?  I can deal with Markdown without images but I don't think the document is as valuable without the screen clips.  

Another idea is to save the document as a PDF and just link to it. That way it's easy for me to make changes as needed.  We lose some of the "subtitle" outline in the markdown version but I think the images are more important.  Also, I expect to continue to see constant changes in the taxonomy screens so making it easy to update the "how to" documents is important.
 
What's best??   I have drafts of more taxonomy pages that could be ready early next week.

Here's a PDF and a doc.

[How to Edit Taxonomy in Arctos.docx](https://github.com/ArctosDB/arctos/files/3031681/How.to.Edit.Taxonomy.in.Arctos.docx)

[How to Edit Taxonomy in Arctos.pdf](https://github.com/ArctosDB/arctos/files/3031683/How.to.Edit.Taxonomy.in.Arctos.pdf)

**Comment by dustymc** [comment]
>no images show

They're in the source - look for ![](data:image/*;base64 - they just don't show in the preview.

I don't think PDF is searchable there, which I see as fatal in a documentation system. Yours also has no links, but that may be my viewer.

http://handbook.arctosdb.org/how_to/markdown-test.html is new - let me know if you want me to push it somewhere else.

@mkoo any suggestions re: easy to update the "how to"

**Comment by sharpphyl** [comment]
Thanks.  It looks good except for some of the text formatting which is making (for example) the first two sentences into topic headers.  Is there a place where I (or someone else) can edit it?  The images look good except that we lose the black border which would make them easier to read.  As always, it would be good for a pair of fresh eyes to read through this before posting.

**Comment by sharpphyl** [comment]
Dusty, despite spending most of the morning with GitHub and Brackets and the markdown converter, I can't get anything like what you got with your version of "How to Edit Taxonomy in Arctos."  Rather than going into lots of detail, can you tell me how to get from your link (http://handbook.arctosdb.org/how_to/markdown-test.html) to where I can edit it to get the formatting correct and then publish it?  I don't find it in the Wiki available for editing.

For me it's most expedient to ask you to continue to convert the Word documents I write - at least until we have a Webinar or other visual to follow.  (I have read through all the handbook and it sounds great, but I'm not getting the same results.)  @Jegelewicz we'll need to discuss how to weave these in with the work you did to start "How to Create a new Taxon."  I think you got about half way before getting very tired of creating URLs for all the images.  If it's ok with you, I'll overwrite your version, if I can figure out how.  We may need to spend sometime on Facetime or whatever to do that.  

My intent is to add the following How to's for Taxonomy.

How to Create Taxonomy  
[How to Create Taxonomy in Arctos 7 Apr 2019.docx](https://github.com/ArctosDB/arctos/files/3055314/How.to.Create.Taxonomy.in.Arctos.7.Apr.2019.docx)

How to Edit Taxonomy (partially done by Teresa - overwrite?)
[How to Edit Taxonomy in Arctos 1 Apr 2019.docx](https://github.com/ArctosDB/arctos/files/3055315/How.to.Edit.Taxonomy.in.Arctos.1.Apr.2019.docx)

How to Search for Specimens with Taxonomy
[How to Search for Specimens with Taxonomy 7 Apr 2019.docx](https://github.com/ArctosDB/arctos/files/3055316/How.to.Search.for.Specimens.with.Taxonomy.7.Apr.2019.docx)

Coming Soon - How to Maintain Taxonomy so Users can Find your Specimens (add to Managing Taxonomic Classifications).  This would take this section out of the Taxonomy Article in Documentation.   I think it too long and some of it belongs in a How To.  Also, Dusty, whatever happened to the links that the little red thingies used to link to?  Are they still needed and used?

![Screen Shot 2019-04-08 at 10 31 51 AM](https://user-images.githubusercontent.com/15368365/55741040-92673480-59e9-11e9-8714-572ec3e24bf5.png)


I've done several versions of Managing Taxonomy Hierarchically but with all the changes now and potentially coming, I've let that drop.

And this morning I did a small edit of the Taxonomy in Documentation as a test of how to do that.  After I "commit" do you review and upload?

@Jegelewicz will this get us where we want to be before SPNHC?

**Comment by dustymc** [comment]
I guess you can't edit it online with the base64 images included, which I presume is what you're looking for? I use git to manage the repo and a text editor in Eclipse for the content - I'm happy to walk you through that, but I don't think it's what you're looking for.

For really quick-n-dirty stuff I sometimes compose in an Issue (which has some GUI tools and lets you drag-n-drop images) and then copy-paste to the documentation.

Where are you seeing the red not-links?

**Comment by sharpphyl** [comment]
Aha!  Creating an issue and copying it into the documentation is definitely worth a try.  I'll go that way before trying another software (Eclipse) solution for adding images.  

> Where are you seeing the red not-links?

I can't get anything to pop up in Taxonomy in Documentation (http://handbook.arctosdb.org/documentation/taxonomy.html#overview).

  Here's the second paragraph:

Arctos taxonomy consists of two tables: taxon_name is a list of “base names” (genera, species, kingdoms) and taxon_term contains metadata regarding a taxon_name, optionally organized in various ways. Informal terms, such as “Sorex sp.” or “Sorex cinereus or Sorex ugyunak” are Identifications, not taxonomy. (Identifications are generally drawn from and linked to taxonomy in various ways.)

![Screen Shot 2019-04-08 at 12 56 13 PM](https://user-images.githubusercontent.com/15368365/55749264-bb91c000-59fd-11e9-94f5-d587ba7c193f.png)

Nothing happens when I click on the red links throughout the document.

**Comment by dustymc** [comment]
Ah - I think those are intended as "these are code-thingee-names" highlighting - I just reused the markers from Gordon's structure-snippets

>Common_Name . Common_Name VARCHAR2 (20) null

&etc.

If I have any control over it, links will always be blue.

**Comment by sharpphyl** [comment]
So if I'm editing that document (if that's ok) do I leave them in or edit them out?

**Comment by dustymc** [comment]
Yea, absolutely, edit away, just please try to keep /documentation closer to 'this is what it is' than 'this is how you use it' (not that I'm very good at that!).

I have no useful opinion on the red text - do whatever you think best.

**Comment by Jegelewicz** [comment]
> After I "commit" do you review and upload?

Once you hit commit - it's the new document. No one reviews it!

**Comment by sharpphyl** [comment]
Hey, you're right.  It worked.  

As for the red text - if it doesn't go anywhere - I'd omit it - but I'll see if I can substitute a hyperlink.

**Comment by Jegelewicz** [comment]
For the hyperlink, put the text you want in the document inside brackets with the url for the link in parens directly after the closing bracket [ ]( )

**Comment by sharpphyl** [comment]
Thanks @Jegelewicz for the "how to" on hyperlinks.

**Comment by sharpphyl** [comment]
> For really quick-n-dirty stuff I sometimes compose in an Issue (which has some GUI tools and lets you drag-n-drop images) and then copy-paste to the documentation.

WHOOHO!  It works!  Thanks for the suggestion.

I'm updating the Taxonomy Documentation (and moving the last part which is mostly "How to" to new How to documents.

Under FAQ is this:

**Q: Why does the editing interface not ….. ?**

A: The editing interfaces are designed to get us by until
[someone](http://gnite.org) does a better job, and are a reflection of
the model in being very generic (and therefore also very limited and
scary in terms of multi-record updates). We hope that most taxonomy will
eventually be managed in remote, limited-scope applications (that is,
applications that do not have to worry about historical names and
homonyms and all the other reality that is taxonomy at the scale of
Arctos) rather than in Arctos (which can now leverage any number of
those services to compile a complete picture).

Is this still valid?  I thought gnite was defunct.  Not sure if we need this but will leave it in if it's helpful.  With all the discussion about "concepts" I thought we might wait for a while to add this content.

**Comment by dustymc** [comment]
The idea that the data structure support more complexity than any single interface is probably still true.

The idea that we aren't limited to a single interface remains true.

The idea that we aren't limited to a single classification remains true.

The hope that some external tools would exist seems to have gone the usual way.

**Comment by sharpphyl** [comment]
I stumbled across another approach to integrating images into GitHub Documentation for the Handbook.    I like the images to be outlined in black so the article is easier to read.  Yesterday, I wrote How to Search for Specimens with Identification and Taxonomy and I put a gray line between the copy and the images - not great but better than nothing.

Today I worked from copy in Word for [How to Edit Taxonomy](http://handbook.arctosdb.org/how_to/How_to_Edit_Taxonomy.html) in Word.  The images of each step were outlined in black.  I copied the image and pasted it into a "new issue" in GitHub, checked the way it would appear, then copied the link into the GitHub How To editor.  Voila!  It shows the black outline around each image and it goes quite fast compared to other approaches.

**Comment by sharpphyl** [comment]
Last question for Dusty.  I edited the Taxonomy section in Documentation and moved much of it into new "How-to" sections.  I omitted this paragraph .  I think the Hierarchical Classification Editor is a bulk tool and there is now a bulk-loader for taxon names.  Is that correct or were you talking about something else?

![image](https://user-images.githubusercontent.com/15368365/56098946-b92eda80-5ec3-11e9-8429-3b7834d9fbc0.png)

**Comment by dustymc** [comment]
Correct on all counts - thanks!

**Comment by sharpphyl** [comment]
Do you want to delete http://handbook.arctosdb.org/how_to/markdown-test.html.  And I'll close this issue for now.

**Comment by dustymc** [comment]
>delete http://handbook.arctosdb.org/how_to/markdown-test.html.

done
