### ISSUE TITLE
Geology from PBDB

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2000]
Is it possible for us to use PBDB geology terms?

https://paleobiodb.org/data1.2/strata_doc.html

**Comment by dustymc** [comment]
Possible, but the data look like a mess to me so would require significant cleanup by someone who understands both the Arctos model and the data themselves.

[pdbdgeo.csv.zip](https://github.com/ArctosDB/arctos/files/3023195/pdbdgeo.csv.zip)
