### ISSUE TITLE
Delete a name

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2001]
Attempting to delete Amphidonte texana as it is not used and is a misspelling (no sense letting someone accidentally use it).

BUT

It has annotations that prevent me from deleting it...

http://arctos.database.museum/name/Amphidonte%20texana

Please delete

**Comment by dustymc** [comment]
Annotations now cascade-delete and http://arctos.database.museum/name/Amphidonte%20texana is no more.
