### ISSUE TITLE
When names aren't really synonyms

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2002]
Adding some classifications today and came across this:

![image](https://user-images.githubusercontent.com/5725767/54858256-56359380-4cc9-11e9-8f27-7ad4c3d3a14d.png)

Yes, Proboscidea in mammals is an invalid synonym of Pisania

BUT

Proboscidea in plants is NOT

Here is a real-world example for #1852

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/983 et al. - this is a known "problem," but I don't understand what it has to do with taxon concepts?

**Comment by Jegelewicz** [comment]
**Concept 1**

> nomenclatural_code: ICZN
> remark: Imported from ITIS 6 Feb 2007
> source_authority: ITIS
> taxon_status: valid
> 
> Classification:
> Animalia (kingdom) 
> Mollusca (phylum) 
> Gastropoda (class) 
> Caenogastropoda (subclass) 
> Neogastropoda (order) 
> Buccinoidea (superfamily) 
> Pisaniidae (family) 
> Pisania (genus) 

**Concept 2**

> nomenclatural code: ICZN
> author text: Bivona-Bernardi 1832
> 
> Classification:
> Eucarya (unranked clade) 
> Opisthokonta (unranked clade) 
> Metazoa (subkingdom) 
> Eumetazoa (unranked clade) 
> Triploblastica (unranked clade) 
> Bilateria (unranked clade) 
> Eubilateria (unranked clade) 
> Protostomia (unranked clade) 
> Spiralia (unranked clade) 
> Schizocoela (unranked clade) 
> Mollusca (phylum) 
> Gastropoda (class) 
> Prosobranchia (subclass) 
> Caenogastropoda (superorder) 
> Neogastropoda (order) 
> Buccinoidea (superfamily) 
> Buccinidae (family) 
> Pisania (genus) 

**Concept 3**

> aphiaid: 137711 [refresh]
> author_text: Bivona e Bernardi, 1832
> nomenclatural_code: ICZN
> source_authority: MolluscaBase (2018). Pisania Bivona e Bernardi, 1832. Accessed through: World Register of Marine Species at: http://www.marinespecies.org/aphia.php?p=taxdetails&id=137711 on 2018-12-18
> taxon_status: extant
> taxon_status: **valid**
> **synonym of Concept 5**
> 
> Classification:
> Animalia (kingdom) 
> Mollusca (phylum) 
> Gastropoda (class) 
> Caenogastropoda (subclass) 
> Neogastropoda (order) 
> Buccinoidea (superfamily) 
> Pisaniidae (family) 
> Pisania (genus) 

**Concept 5**

> nomenclatural code: ICZN
> author text: Möller, 1832
> taxon status: **invalid**
> **synonym of: Concept 4**
> 
> Classification:
> Animalia (kingdom)
> Mollusca (phylum) 
> Gastropoda (class) 
> Neogastropoda (order) 
> Buccinidae (family) 
> Proboscidea (genus) [ more like this term ] [ including rank ] [ from this source ] 

**Concept 6**

> nomenclatural code: ICZN
> author text: Spix, 1824
> 
> Classification:
> Animalia (kingdom) 
> Chordata (phylum) 
> Mammalia (class) 
> Chiroptera (order) 
> Emballonuridae (family) 
> Rhynchonycteris (genus) 

**Concept 7**

> nomenclatural code: ICBN
> author text: Schmidel
> 
> Classification:
>  Plantae (kingdom) 
> Tracheophyta (phylum)
> Equisetopsida (class) 
> Magnoliidae (subclass) 
> Asteranae (superorder) 
> Lamiales (order) 
> Martyniaceae (family) 
> Proboscidea (genus)

Several concepts for two names (Pisinia and Proboscidea), but not all concepts are "synonyms" (see my addition in bold). At any rate, I could choose my classification from any of the above, correct?

**Comment by dustymc** [comment]
The "problem" (it is, but I'm not sure it's very important) is that relationships are between names, not classifications.

**Comment by Jegelewicz** [comment]
> The "problem" (it is, but I'm not sure it's very important) is that relationships are between names, not classifications.

It IS important for the way things are set up now, but maybe not so much if we are using taxon concepts?

**Comment by dustymc** [comment]
See #983 and https://github.com/ArctosDB/arctos/issues/1852#issuecomment-453713712 - concepts would not inherently change how relationships are handled. They would perhaps add stability to classifications (one of the "details" we'd need to work out) which could facilitate moving relationships to where they really belong. In the meantime, relationships get people to where they might want to be and preferred name can clarify the intent.

**Comment by Jegelewicz** [comment]
closing for lack of interest
