### ISSUE TITLE
arctosdb.org is a broken

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#2008]
from https://github.com/ArctosDB/arctos/issues/1841#issuecomment-474032382

1. the gold standard page (https://arctosdb.org/learn/gold-standard-records/) is broken
1. we need a "gold standard" taxon

@ccicero @mkoo

**Comment by mkoo** [comment]
it's working for me--- what's specific wrong with that page on arctosdb.org?

Also should the Gold std taxon be linked to this page:
http://arctos.database.museum/name/Oedipina%20kasios

**Comment by sharpphyl** [comment]
In the webinar, we used Amazona amazonica.  

One that also shows a WoRMS (via Arctos) aphiaID and has images and geolocation would be Eulima flexuosa or Ersilia stancyki.  Lots of others if you're looking for other features.

**Comment by dustymc** [comment]
hmmm, seems to work in Chrome - firefox looks like this:


<img width="916" alt="Screen Shot 2019-03-26 at 7 58 36 AM" src="https://user-images.githubusercontent.com/5720791/55007651-07278100-4f9d-11e9-939d-17a98a2bd9cc.png">

**Comment by mkoo** [comment]
FF has some gnarly (in a good way!) security blockers-- you have to allow
something somewhere but my FF works.
I have given the Arctos domain free range in FF and it works.

I'll add a few Taxon exemplars

**Comment by mkoo** [comment]
just looked through Oedipina kasios-- what happened to AmphibiaWeb External
links????

http://arctos.database.museum/name/Oedipina%20kasios

**Comment by dustymc** [comment]
Looks like amphibiaweb got commented out when the URLs broke. Do you have a URL that uses the name?

**Comment by mkoo** [comment]
yes any name can be used like this:

https://amphibiaweb.org/cgi/amphib_query?where-genus=Agalychnis&where-species=callidryas

https://amphibiaweb.org/cgi/amphib_query?where-genus={genus}&where-species={species}

but does not handle subspecies. Note it's now HTTPS (not sure when we
switched over, a year ago?!)
thanks

**Comment by dustymc** [comment]
Yea, that's the broken thing! I don't have that structure for those links - I just have a name.

**Comment by dustymc** [comment]
>I have given the Arctos domain free range in FF and it works.

That's not the problem - I think it's google. Can we find a way that doesn't break our recommended browser or add a "click here if this doesn't work" to something that does work or ???

**Comment by mkoo** [comment]
Add a direct link to the Table to view our Gold Standard Specimens. Broken page issue seems to be a FF - client with some sort of  blanket security measure blocking the Google Doc embedded in the page.
