### ISSUE TITLE
Create a Template for Agent Bulkload

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2009]
Instead of this in the Bulkload Agents tool:

![image](https://user-images.githubusercontent.com/5725767/55116938-adaf7700-50ae-11e9-8408-4f2b3df1fa91.png)

Can we get the usual "get CSV template"?

![image](https://user-images.githubusercontent.com/5725767/55116980-cddf3600-50ae-11e9-8b5a-4eaa41c5c192.png)

I am updating documentation and this change would create more regularity in the tool appearance as compared with other tools.

**Comment by dustymc** [comment]
done
