### ISSUE TITLE
flatten part locations is not working

### ISSUE THREAD

**Issue by amgunderson** [ArctosDB/arctos#2010]
from https://arctos.database.museum/findContainer.cfm, find a container then click Flatten Part Locations. The table headers show up but the table that should have parts locations is empty.

Happens with chrome and safari on my iMac.

**Comment by dustymc** [comment]
<img width="1381" alt="Screen Shot 2019-03-27 at 5 18 19 PM" src="https://user-images.githubusercontent.com/5720791/55120719-59a79100-50b4-11e9-98ad-66c946c76391.png">


Maybe https://github.com/ArctosDB/arctos/issues/1329?

**Comment by campmlc** [comment]
It was working for MSB earlier this afternoon?

**Comment by amgunderson** [comment]
Ah, yes it is that problem, the collection objects were not visible. Thanks

**Comment by dustymc** [comment]
I'm gonna hijack your issue - this keeps happening.

Add documentation to the top of https://arctos.database.museum/loanFreezerLocn.cfm

**Comment by dustymc** [comment]
done
