### ISSUE TITLE
google map says oops on specimen records

### ISSUE THREAD

**Issue by amgunderson** [ArctosDB/arctos#2011]
See any specimen record. Happens for me in chrome and safari.
![Screen Shot 2019-03-28 at 9 45 49 AM](https://user-images.githubusercontent.com/8440698/55180349-480acb80-513e-11e9-8dc8-fb1fc177cba5.png)

**Comment by KyndallH** [comment]
Same here.

**Comment by mkoo** [comment]
We know. Looking into the new requirements of using the API, mainly a
credit card.

**Comment by amgunderson** [comment]
I have a credit card, how much is it?

**Comment by dustymc** [comment]
@mkoo any news? Do I need to start looking for another solution?!?

**Comment by DerekSikes** [comment]
same here

**Comment by sharpphyl** [comment]
I have a credit card too.  What gives??

**Comment by dustymc** [comment]
@mkoo @ccicero anybody?

**Comment by dustymc** [comment]
@mkoo @ccicero? Do I need to start looking for another solution?

**Comment by Jegelewicz** [comment]
Do we need to email them - not sure they monitor GitHub like we wished they did....

**Comment by ccicero** [comment]
MK email 4/26:

Honestly the best solution is to opt for a new geo service like through leaflet (open source, FREE). We are moving BerkeleyMapper from google api to leaflet and hopefully will have something for people to test soon.

Even with the Google Geo-grant, they are not making it easy to manage, almost as if they would like everyone to pay! It's honestly the worst customer support ever.

Dusty, I've sent you the Leaflet API link before and while I think it may not have ALL the lookup services you are using it at least as the map viz (quick start guide). We could request a Mapbox tile key and have some cool basemaps!

What do you think?

Meanwhile I will write Google grants AGAIN

**Comment by ccicero** [comment]
Dusty email 4/26:

I'm not morally opposed to moving away from Google, but it's going to take quite a bit of coding/time and I am likely to be completely comsumed by Oracle over the next few weeks. We've been pushing TACC on this upgrade, things started happening yesterday, the map stuff REALLY needs to happen in a dev environment, and overall doing the stuff I've been doing in prod is just dangerous and dumb. I feel like prioritizing the upgrade over all else is corect, but I'm not really thrilled about pushing Arctos with broken maps either.

Getting a functional API key, even if it's somewhat limited and even if it's somewhat short-term, seems critical to me at this point.

https://developers.google.com/maps/documentation/javascript/get-api-key

I suspect we'll lose some functionality with a not-Google solution too, but I'm not sure - leaflet does seem to have a fair number of plugins to do random stuff.

**Comment by ccicero** [comment]
So can we do a short-term solution and then work toward the longer-term solution/switch? 

It's hard to figure out how much the Google Maps API licensing would cost.

How easy would it be to embed a BerkeleyMapper map onto the detail pages instead of a Google Maps, so we have something. It does't do the geocoding that we have now, but at least the detail page would show a map rather than an 'oops' !

I agree that with SPNHC and other meeting presentations coming up, we can't show Arctos the way it is now.

**Comment by campmlc** [comment]
How much would it cost us to pay it ourselves for 6 months or a year, without the grant?

**Comment by ccicero** [comment]
That's what's hard to figure out. It looks like it's based on map credits, usage limits, and quotas, and can vary depending on your plan.

We have a previous license:
https://developers.google.com/maps/premium/previous-licenses/

Pricing plans vary depending on usage:
https://cloud.google.com/maps-platform/pricing/
https://developers.google.com/maps/premium/overview

Their website is very confusing.

**Comment by dustymc** [comment]
Thanks to @mkoo we again have basic mapping capability. Please leave a comment here if you find any undocumented broken map-related functionality.

After Oracle is upgraded and the dust settles we need to revisit this. It would be very useful if ya'll could check out https://leafletjs.com/ and we could come out of the upgrade with a longer-term plan. I'd rather not fix the remaining stuff and then immediately abandon it for a different solution!

* I've turned off maps for Media - enabling that needs a client_id (and how to get one is anything but clear) or a different authentication method (requires significant coding).
* internal stuff (eg, edit locality) can just stay broken for the time being
* all service calls (elevation suggestions, distance-from-suggested reports, locality suggestions and automation, search terms, etc.) are broken for now

**Comment by mkoo** [comment]
ok, I've applied a newly minted api key to global settings on Arctos
(thanks for pointing me to that, dusty). I also enabled billing on my card
while I send yet a fresh round of emails to Geogrants or whatever they are
called now. (I have gotten nothing but abandoned emails or auto-replies to
resend to another email, which are appended addresses with noreply! I
already did this a month ago and got nothing) If I dont hear back from a
warm body, I will email individuals I know at Geo out of desperation (but
grants are not their job technically).

Meanwhile I hope I'm not stuck with a billing crisis next! (BM, Symbiota
and other Berkeley projects have been humming along under credit but they
do not offer embedded GM like Arctos does so a different beast altogether!)

Dusty said to wait a bit for the key to propagate through the site... but
how long (over an hour so far)?

**Comment by campmlc** [comment]
Thank you, Michelle and Dusty! That's a relief.
Can we switch the billing to Rauthiflor, to keep all finances consistent?

**Comment by mkoo** [comment]
I'm still researching but I hope that wont be necessary (besides we would
need a credit card; does R have that?!) Having applied this new key under
the Berkeley enterprise organization, we have a jump in quotas:

eg. Maps JS api (everytime a map thumbnail loads on your screen)--> limit
is 50,000 map loads per minute, unlimited per day.
the other services that Arctos uses are basically unlimited too (like
geocoding and elevation, yay!)

I have not gotten rejected since I made this request so I dont think I
will.
I will have to seek a little guidance about the new credentialling and
other issues that Dusty pointed out but we're nearly there now!
MK

**Comment by mkoo** [comment]
since the basic Bug is fixed, I'm closing this issue (and related ones). I will create a new one for the background services we need, which is really just a matter of more learning how the enterprise Google cloud console works so will assign to myself!
