### ISSUE TITLE
"authAgentName" blank in all invoice headers reports

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2013]
Apparently the field "authAgentName" no longer exists or has been changed. All the invoice headers that I can find use this field name to indicate who authorized the loan, which means none of them ever have any information when they are printed.

@dustymc what field name should we be referencing in order to get the name of the person who authorized the loan to print on the loan form?

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/arctos/issues/1993#issuecomment-475804448_

**Comment by Jegelewicz** [comment]
See the UMNH_Herp_Loan_Header.cfr report.

The item is question is in the red rectangle
![image](https://user-images.githubusercontent.com/5725767/55246758-83bf9700-520b-11e9-89f8-ee3438c7850c.png)

**Comment by dustymc** [comment]
http://arctos.database.museum/Loan.cfm?transaction_id=21121065&Action=editLoan

<img width="214" alt="Screen Shot 2019-03-29 at 9 26 17 AM" src="https://user-images.githubusercontent.com/5720791/55247400-be720100-5204-11e9-958b-3a82822210e3.png">

<img width="610" alt="Screen Shot 2019-03-29 at 9 27 10 AM" src="https://user-images.githubusercontent.com/5720791/55247460-e8c3be80-5204-11e9-9148-954b262c34b5.png">

Dump to see the data that'll be handed to the report.

<img width="268" alt="Screen Shot 2019-03-29 at 9 27 18 AM" src="https://user-images.githubusercontent.com/5720791/55247464-ecefdc00-5204-11e9-8de5-20177f668f2f.png">

I still haven't dug out a Windows machine (and THANK YOU for taking this on!) but the box in the report should include ``#AUTHAGENTNAME#``

If it does, check the options and size - I think there's an option (perhaps default) to discard data which doesn't fit, or to truncate or overflow or something.

**Comment by campmlc** [comment]
Dusty, could I get the SQL for the MSB Mamm loan header and invoice from
the build in dropdown in the loan form? We don't seem to have any
functional loan forms in reports for any of the MSB divisions. I just use
the one that appears in the dropdown, which works, but I can't clone or
edit it.  Thanks.

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/blob/master/Reports/MSBMammLoanInvoice.cfm

You don't need SQL - it just calls https://github.com/ArctosDB/arctos/blob/master/CustomTags/getLoanFormInfo.cfm, same thing...

<img width="162" alt="Screen Shot 2019-03-29 at 10 06 21 AM" src="https://user-images.githubusercontent.com/5720791/55249877-54f4f100-520a-11e9-8c4a-6a3bfbbc7e4f.png">


does.

**Comment by Jegelewicz** [comment]
This is what I see:

![image](https://user-images.githubusercontent.com/5725767/55253191-4f070c00-521a-11e9-96f7-cbfe40e874a7.png)

![image](https://user-images.githubusercontent.com/5725767/55253215-60501880-521a-11e9-82ec-79ab98328788.png)

![image](https://user-images.githubusercontent.com/5725767/55253237-6b0aad80-521a-11e9-8da6-9a22e6bdf09c.png)

 Can you tell anything from that?

**Comment by dustymc** [comment]
``"someVariable"`` is a string.

``someVariable`` is a variable and (at least there) should print the value of the variable

``#someVariable#`` = ``"#someVariable#"`` is a variable (and can be included in strings, but IIRC that gets weird in the reporter)

Drop the quotes and I think that'll work.

**Comment by Jegelewicz** [comment]
Success!! Thanks!

![image](https://user-images.githubusercontent.com/5725767/55265308-63a8cb80-523d-11e9-8dbc-459e1c509b0d.png)
