### ISSUE TITLE
Agent Name Type "generational suffix"

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2014]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Table**
http://arctos.database.museum/info/ctDocumentation.cfm?table=CTAGENT_NAME_TYPE

**Value**
generational suffix

**Definition**
post-nominal alphanumeric characters used to distinguish persons who share the same name within a family

**Collection type**
N/A

**Attribute data type**
free-text

**Attribute value**
N/A

**Attribute units**
N/A

**Part tissue flag**
N/A

**Other ID BaseURL**
N/A

**Context**
Currently this value is part of the last name (mostly?). When present, it trips up the Namestring Formatter Tool. Suffixes should be included in preferred name, especially when Agent names will otherwise be exact duplicates. Splitting this out from the last name seems more appropriate.

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
[Been there](http://arctos.database.museum/info/ctDocumentation.cfm?table=CTPREFIX), [done that](http://arctos.database.museum/info/ctDocumentation.cfm?table=CTSUFFIX).

http://handbook.arctosdb.org/documentation/agent.html#creating--maintaining-agents

>Consider pushing prefix, suffix, title, etc., to nonpreferred names; limit preferred name to things that do not change in confusing ways. John Smith has a son and becomes John Smith Senior; John Smith Junior has a son and becomes John Smith II; Captain John Smith gets promoted to Major John Smith: avoid potential confusion when possible. If you must create a preferred name with a prefix or suffix, ensure there also exists a “bare” alternate name.

I'm not opposed to adding "prefix" and/or "suffix" to https://arctos.database.museum/info/ctDocumentation.cfm?table=CTAGENT_NAME_TYPE, but that gets weird when one agent with an interesting life ends up wearing a few dozen of them. 

There's code behind http://handbook.arctosdb.org/documentation/agent.html#abbreviation-exemptions. It can be expanded, as long as we do so with the above in mind. A specific example of what you're trying to do would be very useful.

**Comment by Jegelewicz** [comment]
Use suffix in preferred name - add to documentation.

**Comment by Jegelewicz** [comment]
I hope the documentation is clear that these should be added to preferred name.
