### ISSUE TITLE
Agent Name Type "aka"

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2015]
When did we decide that so many of our agent name types are not to be used?

![image](https://user-images.githubusercontent.com/5725767/55252754-3a764400-5219-11e9-8755-a1b1a290e1c5.png)

If this is really what we want, we should change the designation on anything defined as "use aka" to aka and get rid of these values. If this is not what we want, we should define these other name types appropriately.

Which is it?

**Comment by AJLinn** [comment]
It's been at least 2-3 years. Presumably they're still there because there is data in those fields that haven't been fixed.

**Comment by dustymc** [comment]
Let's just do this if nobody has a reason not to. Is a week enough time for discussion?

/remind me to check back in a week

**Comment by sharpphyl** [comment]
Is there a reason we capitalize some and not others?
And why do we use the term "old person"?
It can be helpful to know "maiden" (or "nee") more specifically than just aka.

**Comment by dustymc** [comment]
Kew is a proper noun.

There's a table we no longer use which was called person, and I'm biased by Oracle's built-in :OLD and :NEW bind variable naming convention.....

If that's somehow important, can we use "birth name" or similar to avoid the whole mess around multiple marriages and how 80% of the world does things and etc?

**Comment by sharpphyl** [comment]
So "old" means "former name" or something similar?

Birth name is fine with me.  Just something to help people understand how the "aka" relate to the "preferred" or "agent" name.

**Comment by dustymc** [comment]
Done, with a "backup" as bak_agent_name20180505.
