### ISSUE TITLE
WKT: move to text files

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#2017]
WKT of length >64K are being truncated, probably by browsers.

http://arctos.database.museum/editLocality.cfm?locality_id=10819659 seems to be the only affected locality at this time.

Probably best to move **all** WKT data to media so we can just avoid the many pitfalls of passing very large strings around, and shrink backups and such while we're there.

**Comment by dustymc** [comment]
Moving all WKT to Media would also greatly simplify comparisons - I'd just have to look at Media_ID instead of attempting to compare very large strings in which some characters aren't terribly important. Changing title and planning on that as a general approach to all WKT data, unless someone has a compelling reason to store any WKT as LOB.

**Comment by dustymc** [comment]
With Media as the primary way to storing spatial data, I think it makes sense to formalize the relationship instead of the MEDIA::{id} hack. Unless someone has a better idea, I'll plan on 'spatially defines geog_auth_rec' and 'spatially defines locality' relationships.

**Comment by mkoo** [comment]
any way to store as a geometry object ? or is that an expensive extension
thing in oracle?
also were we not storing wkt as media already?

As long as I can keep searching for wkt's in geog_auth fine with me.
Eventually it would be great to search via wkt's selected on a map so
whatever gets us closer to that would be best

**Comment by dustymc** [comment]
>geometry object

Not that I know of - that's Oracle Spatial territory.

>storing wkt as media already

Only very large ones, which confuse the JDBC connectors (or something in the pipeline - and eat browsers and etc.)

This should not affect Arctos UIs (except creating WKT) in any way. It will shrink downloads, make it easier to deal with large data objects, and make the WKT data publicly accessible.

It also exposes a pathway to multiple spatial files, if that becomes useful for some reason. (Eg perhaps we need low-res and hi-res, or creating geojson from WKT for leaflet is expensive so it might make sense to store them, or ....)
