### ISSUE TITLE
Add Live Links from Scan Positions form back to Find Containers

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2018]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the solution you'd like**
On the Scan Positions forms, e.g. for cryovials, we see the label and barcode of the object being scanned. I would like to ask if it is possible to make the barcode and/or label a live link that can be clicked to go back to the Find Container view.

**Additional context**
For example, in the form below, I would like to click on the barcode in position 1, 
![Screenshot 2019-04-01 10 22 59](https://user-images.githubusercontent.com/14808196/55343592-a8fd1100-5468-11e9-9365-941625886ed6.png)

and go to the following:

![Screenshot 2019-04-01 10 25 29](https://user-images.githubusercontent.com/14808196/55343629-b9ad8700-5468-11e9-903e-254fa64bc678.png)

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
@campmlc prioritize this
