### ISSUE TITLE
Unable to merge duplicate collecting events

### ISSUE THREAD

**Issue by gordonhlau** [ArctosDB/arctos#2019]
The following two specimens are currently in the same locality ID. They are in separate collecting events and should be in the same collecting event:

http://arctos.database.museum/guid/MVZ:Bird:184825
http://arctos.database.museum/guid/MVZ:Bird:184826

All the information is the same, however I keep getting the message "No duplicates detected - try merging localities first." every time I try to merge the two events even though they are in the same locality ID. If you go to the bottom of the specimen page, you will notice that for 184826 on the bottom of the page it says "Coordinates: Verbatim Coordinates: /" whereas for 184825 it says "Coordinates:" and I think this is where the difference could be that prevents the merging of the events. However, not sure how to edit this part to make it the same for both so that we can merge the events together. I am currently using Arctos in Google Chrome.

**Comment by dustymc** [comment]
I updated the function that builds verbatim coordinates to return NULL when there's no actual coordinate data, and updated events that had strings without coordinate data in verbatim coordinates. These events should now auto-merge.

**Comment by gordonhlau** [comment]
Great, thanks Dusty.
