### ISSUE TITLE
Item not found error with Part to Container bulkloader

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2020]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Cannot use parts to containers bulkload tool with NK number? Please help find any error in this file that I am missing.

[2018.060 Colfax Co Aug 2018 barcode upload.txt](https://github.com/ArctosDB/arctos/files/3031843/2018.060.Colfax.Co.Aug.2018.barcode.upload.txt)
[2018.060.Mamm barcode upload NK.xlsx](https://github.com/ArctosDB/arctos/files/3031846/2018.060.Mamm.barcode.upload.NK.xlsx)

**To Reproduce**
Attempt to load attached file )as csv) with Data Entry -> Batch Tools -> Parts ->Container.
Get error that item not found for all parts. Yet when I replace the NK number with the catalog number, it works. 

**Expected behavior**
The barcodes to load to their respective parts, assuming the part exists. Get "item not found" error if the part actually does not exist in Arctos. 

![Screenshot 2019-04-01 18 22 08](https://user-images.githubusercontent.com/14808196/55367707-a66fdb00-54ab-11e9-925a-f80a1c62c88e.png)

*Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
I can't break it.

 304039 has two parts so I can't know which one you want. 303926 has one matching part and it works. Give me a specific example of one you think isn't working correctly. 

PLEASE attach CSV - a significant chunk of these issues are problems with the file you loaded, and I can't diagnose those if I don't have the file you loaded.

**Comment by campmlc** [comment]
I can't attach csv through Github, so I attached a text and an xls file.
Here is csv through my gmail. All of the parts in the file were throwing
the error - see screenshot.

If there are problems with parts not mapping, this is an ongoing
aggravation caused by those who record field data not accurately capturing
what they actually collect,so the catalog record does not match the
barcoded samples. I would like to know that if so.
There are definitely some with two identical parts. It doesn't matter which
gets which barcode - just assign the first one the first barcode and the
second part the second barcode. Until they are assigned the barcode, they
can be any part since none of these have yet been loaned.

**Comment by dustymc** [comment]
You can zip CSV (or most anything else).

I can't get what I asked for from the screenshot.

My offer of SQL stands, but I am not going to provide a "do something to some random part" form.

**Comment by campmlc** [comment]
[2018.060 Colfax Co Aug 2018 barcode upload.zip](https://github.com/ArctosDB/arctos/files/3092737/2018.060.Colfax.Co.Aug.2018.barcode.upload.zip)

Here is the zipped file. Some are definitely problems - part is missing, record is missing. But I can't find the problem with some, for example http://arctos.database.museum/guid/MSB:Mamm:325900 has a heart, kidney, lung, spleen (frozen) part, but the barcode won't load to it because of the item not found error. Whatever is wrong is not obvious.
As an additional request, it would be helpful to be able to download the results from this tool to try to troubleshoot the problems.

**Comment by dustymc** [comment]
>MSB:Mamm,NK,303985,"heart,kidney,lung,spleen (frozen)",A6WO7,

> heart, kidney, lung, spleen (frozen) 

Check the spaces.

**Comment by campmlc** [comment]
That's interesting, because this is what shows up in my file when I open
it:
heart, kidney, lung, spleen (frozen)
Looks like something got messed up between the xlsx and the csv.

So, I fixed that, and it dropped the number of unresolved items from over
400 to 127. Some of these appear to be uncataloged birds, others are still
missing parts. I'd really, really like to be able to load the barcodes to
the parts that do match, and then download the ones that do not to work on
them individually.
Possible?

**Comment by campmlc** [comment]
new file
[2018.060.Mamm barcode upload NK.zip](https://github.com/ArctosDB/arctos/files/3095211/2018.060.Mamm.barcode.upload.NK.zip)

**Comment by dustymc** [comment]
>something got messed up between the xlsx and the csv.

Yes, that's one reason I need original data to diagnose problems. 

The form now adds a count with mismatched parts, and has a download option.
