### ISSUE TITLE
geog cleanup request: Ireland

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#2022]
It's a mess, including one variation that has Northern Ireland as a county. That was created by @ccicero - I'm not sure if it's an oops or intentional for some reason. Everything else could use a review - eg only one of the components of the country of Ireland is listed as being on the island of Ireland, which seems unlikely....

http://arctos.database.museum/geography.cfm?higher_geog=Ireland

The Ulster/Irish/etc. spellings offered on wikipedia are very useful too - please include them if possible.

**Comment by Jegelewicz** [comment]
I noticed all of this while adding a few higher geogs for OWU, just didn't have time to work on it...hitting up geography committee.

**Comment by dustymc** [comment]
Tabling - https://github.com/ArctosDB/arctos/issues/3272 would allow Arctos to standardize geography.
