### ISSUE TITLE
authority edit history

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#2023]
We collectively change a lot more authorities than when the system was developed, very few of us have access to the logs, and they're not trivial to piece together.

Build a form which exposes log data in sufficient detail to track the origin of our data, sprinkle it around nodes with logs.

Maybe: There seems to be a consensus that FKEY(agent) is better than login name; consider changing the logs to use agent_id.

**Comment by Jegelewicz** [comment]
> There seems to be a consensus that FKEY(agent) is better than login name; consider changing the logs to use agent_id.

login names aren't always as easy for us humans to read as Agent names...

**Comment by dustymc** [comment]
done (sometime in the past...)
