### ISSUE TITLE
clarify "age" attribute definition

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#2026]
ref: https://arctos.database.museum/ScheduledTasks/authority_change.cfm?start=2019-04-02&stop=2019-04-03 (log in before clicking)

'Age' was just added to ES collections. 

>General description of the age. See also age class and numeric age.

The attribute age refers to time since birth or something of the sort. I think paleontologists generally think of something different when they hear 'age.' Can we clarify the definition please?

**Comment by Jegelewicz** [comment]
Two possibilities:

1. add the following to the definition: for fossil material, the age of a fossil in MYA units as per the [geologic time scale](https://en.wikipedia.org/wiki/Geologic_time_scale)

2. add a new attribute: geologic time scale age = the age of a fossil in MYA units as per the [geologic time scale](https://en.wikipedia.org/wiki/Geologic_time_scale)

Preference? Other idea?

**Comment by Jegelewicz** [comment]
Probably relates to #1975

**Comment by dustymc** [comment]
>for fossil material

That would lead to fun things like age determinations of "30 million years" (rock in which it's found) and "17 years" (number of rings) for the same specimen, or an assertion that bison live for 34000 years. It's exactly what I'm trying to prevent here, although I didn't realize it was the intent!

http://arctos.database.museum/info/ctDocumentation.cfm?table=CTATTRIBUTE_TYPE&field=radiometric%20date and parts of http://arctos.database.museum/info/ctDocumentation.cfm?table=CTGEOLOGY_ATTRIBUTE are 'time before present.' Age, age class, and numeric age are time between birth and death (or some observation/encounter, but I don't think those are possible for fossils).

At least in theory I don't have much problem with firing up another way of saying "time before present" if the current ones are somehow insufficient. I have a huge problem with confounding existing data with some other type of thing.

Are your "age" data from rocks, some direct measurement, or something else?

**Comment by Jegelewicz** [comment]
> Are your "age" data from rocks, some direct measurement, or something else?

Presumably rocks - these are a field from ALMNH that generally says "approximately 80 million years"

**Comment by dustymc** [comment]
>age...rocks

How does the stuff under Chronostratigraphy in http://arctos.database.museum/info/ctDocumentation.cfm?table=CTGEOLOGY_ATTRIBUTE relate to "approximately 80 million years"? (Not that I suspect you really want to count the hashmarks on https://en.wikipedia.org/wiki/Geologic_time_scale to turn that into Cretaceous for these....)

Unless @dperriguey @Nicole-Ridgwell-NMMNHS @KatherineLAnderson has some clever suggestion, I suppose I'd recommend a new "geologic age" er sumthin free-text attribute, which should at least act as a safe place for the data until someone has a better idea.

**Comment by dperriguey** [comment]
Well I would say that whatever is approximately 80 million years old (or better written ~80Ma) to mean that it is Campanian in age. Look at the chronostratigraphic chart ca. 2017. Anything from 83.6 to 72.1 Ma is Campanian in age.

**Comment by campmlc** [comment]
Maybe just change the ES attribute to " geologic age"?

**Comment by campmlc** [comment]
And use time before present?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Where this information should go depends on the origins of the estimate. Without any context, I think it should just go into the verbatim locality field (or if we added a verbatim geology it could go there), and then you check to see if the locality is assigned to the Campanian. If it is from radioisotopes, it should go into that attribute. If it from some sort of stratigraphic measurement or observation, then that needs to go into some sort of stratigraphy field in the locality.

I don't think some sort of geologic age field on it's own is very useful. If you don't know the origin of that age estimate, it's not very helpful because you don' know how reliable the estimate is. There's a big difference between 'this formation is Campanian so we'll call the fossil ~80 million years old' and 'this bed is between two beds that have been dated to 80.5 Ma and 79.5 Ma' and 'this bed has been isotopically dated to 80.1 Ma plus or minus .5 Ma"

So, no origin = not reliable = just put in verbatim
origin know = can be put in a more specific field

From my understanding, it looks like there is more work to be done on how to enter fine scale stratigraphy and information on other dating methods into the localities.

**Comment by Jegelewicz** [comment]
For context - most of these have actually been assigned geology attributes - I was just looking for an appropriate place to store the estimate that someone decided to record in their data at some time...

Maybe I should put that information in Collection Event Remarks (=verbatim?)

**Comment by dustymc** [comment]
Attributes do provide for metadata, so you could record determiner and method with "geologic age."

The values of Attribute "age" (free-text) aren't usefully searchable, but the existence of the attribute itself is an indication that there's some sort of age data available to anyone who's willing to dig for it (and that it's probably low-quality, or it would be in age class/numeric age). If this seems similar, a 'geologic age' attribute might make some sense even if the data themselves aren't very trustworthy. If it seems more like something that someone derived from other data (or pulled out of thin air...) then some remarks field may be a better choice. That's probably a question for the collection.

@Nicole-Ridgwell-NMMNHS please open an Issue for any "how to enter..." questions. Just knowing that problems exist can be very useful in modeling even seemingly-unrelated stuff.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks @dustymc, still learning, forgot that you could attach metadata to the attributes. And I will start another issue for those geology questions.

I guess the other problem I see with "geologic age" is that it is a specimen attribute, whereas, unless you are doing isotopic dating of the bone itself, then this age is actually an age of the locality and should be associated with the locality.

**Comment by dustymc** [comment]
>specimen attribute

Yes, agreed - context==locality, measured from the specimen==specimen attribute.

Attributes are also a handy "trashcan," which is what I think the 'geologic age' (which probably needs a better name) is.

I was trying to carefully avoid your 'this bed has been isotopically dated to 80.1 Ma plus or minus .5 Ma" example, which is clearly rocks so should be in locality but doesn't fit in the geology model that we have hanging off of locality. https://github.com/ArctosDB/arctos/issues/1270 might be close enough, or maybe we need something like that off locality as well. (Perhaps just a generalization of the existing geology model.) The ideal is probably just relationships - "THIS bone is 80.1 Ma plus or minus .5 Ma because we chipped it off of THAT rock, which has details on how age was determined." In any case, it's very useful to document any shortcomings - occasionally they do add up to robust solutions!

**Comment by Jegelewicz** [comment]
I am going to put this in Specimen remarks for ALMNH. I don't think it  is particularly important as it is mostly made redundant by geology attributes that will load to the localities.

**Comment by ccicero** [comment]
So does that resolve the issue? Can this be closed?

**Comment by dustymc** [comment]
Yep, looks like age was removed from ES tables.
