### ISSUE TITLE
bulkload loan items should accept GUID

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#2027]
it should

**Comment by srobson4** [comment]
Resolved.  Thanks @dustymc

**Comment by dustymc** [comment]
Needs rebuilt into the Component Loader model

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/2696 - unresolvable parts - needs SOMETHING (probably just documentation)

https://github.com/ArctosDB/arctos/issues/1792  (and email from @ccicero ) - we need a "ignore subsamples when finding the initial part" flag

**Comment by dustymc** [comment]
Need a replacement for ``<br><a href="/tools/loanBulkload.cfm?action=downloadForBulkSpecSrchRslt&transaction_id=#transaction_id#">Download in loan bulkloader format</a>``

**Comment by dustymc** [comment]
In production, old data is https://github.com/ArctosDB/arctos-assets @ccicero
