### ISSUE TITLE
Loan search needs some field titles

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2028]
When searching for a loan this is the search page:

![image](https://user-images.githubusercontent.com/5725767/55559917-675ca800-56ac-11e9-813f-70390571f5f7.png)

Can we have labels on the top two fields?

![image](https://user-images.githubusercontent.com/5725767/55560043-a3900880-56ac-11e9-8e3e-4aafc95dee8f.png)

**Comment by dustymc** [comment]
<img width="349" alt="Screen Shot 2019-04-05 at 8 49 25 AM" src="https://user-images.githubusercontent.com/5720791/55640080-be7f7d00-577f-11e9-8ea8-edf30d778ac6.png">
