### ISSUE TITLE
Change all loan item conditions in bulk

### ISSUE THREAD

**Issue by acoconis** [ArctosDB/arctos#2029]
It is really convenient to be able to change all the loan item dispositions at once. Could there be a similar feature for the condition of loan items? Often we have a large number of loan items and changing each condition individually is really time consuming, especially since usually their condition is checked together, as we send or receive loans.

**Comment by dustymc** [comment]
This is not a technical problem, but I don't understand the use case - I'd think it would be very rare for any two items ever have quite the same condition??

**Comment by acoconis** [comment]
I see what you're saying. We've been changing most of our items from unchecked to checked. And if there were any reportable problems, we would add that as well.

**Comment by dustymc** [comment]
Thanks!

https://github.com/ArctosDB/arctos/issues/1908 is related - eg, perhaps we should limit "condition" to things like "checked" and "broken" (in which case bulk updates might make more sense) and push "small chip on anterior surface of 3rd upper premolar (according to AGENT on DATE)" to a different place.

**Comment by acoconis** [comment]
Ah yes. This could work for us. Thank you.
