### ISSUE TITLE
Best method to record prey/diet description

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2032]
From Vicky at UTEP as she prepares to catalog their ants

> Prey / diet description ?? – I need something like the stomach contents attribute. The food description variable describes food that was found being carried or in the nest of the ants; can be prey or seeds

I think of at least three ways this could be done.

Catalog the prey/food as an observation, then using the relationship "ate/eaten by" relate the prey/diet to the ant record(s)

OR

Create a new attribute: food = food being carried by or found in conjunction with the collected species ( I don't like the attribute name, but can't think of anything better at the moment)

OR

reference prey/diet in "Associated species" (my least favorite option)

**Comment by campmlc** [comment]
Catalog the prey/food as an observation, then using the relationship
"ate/eaten by" relate the prey/diet to the ant record(s)
This is the most powerful option, because you can then associate the food/
prey using real taxonomic terms in a searchable taxonomic hierarchy. This
is what we do for parasite / host.
These relationships are searchable.

**Comment by dustymc** [comment]
>Catalog the prey/food as an observation, then using the relationship "ate/eaten by" relate the prey/diet to the ant record(s)

That's best.

>"Associated species"

Our documentation is pretty sparse (http://handbook.arctosdb.org/documentation/catalog.html#associated-species), but that's generally for "grows under oak trees."

>new attribute

It's the same-ish idea as https://arctos.database.museum/info/ctDocumentation.cfm?table=CTATTRIBUTE_TYPE&field=stomach%20contents even if the details are different. I think it's better to generalize that (maybe to "food") than to fire up a new attribute for ALMOST the same thing. https://arctos.database.museum/info/ctDocumentation.cfm?table=CTATTRIBUTE_TYPE&field=crop%20contents is weird too.

**Comment by mvzhuang** [comment]
OK plan 1 sounds like a plan. Thanks guys!
