### ISSUE TITLE
Behavior attribute

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2033]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Table**
http://arctos.database.museum/info/ctDocumentation.cfm?table=CTATTRIBUTE_TYPE

**Value**
behavior

**Definition**
behavior of specimen when alive (I think most people have been putting things like this in specimen event remarks?)

**Collection type**
Ento

**Attribute data type**
free-text

**Attribute value**
N/A

**Attribute units**
N/A

**Part tissue flag**
N/A

**Other ID BaseURL**
N/A

**Context**
Need to record information related to ant colonies.

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
example data?

**Comment by Jegelewicz** [comment]
@mvzhuang

**Comment by mvzhuang** [comment]
Ok I pulled the behavior data out for this issue. I've highlighted it in green on the right side of the sheet. The actual sheet has too many variables with confusing names.

My plan is to concatenate all of these activity and behavior variables into one. We have things like "non-aggresive, aggressive", "active, sluggish, normal" . Please ignore the abundance values that are in ActivityOther because I'll move that over to abundance.

[Behavior.xlsx](https://github.com/ArctosDB/arctos/files/3045764/Behavior.xlsx)

**Comment by dustymc** [comment]
I think as an immediate solution I support a new free-text attribute.

For longer-term, things like http://www.obofoundry.org/ontology/sibo.html exist (although I'm not absolutely sure anyone's ever really USED any of them...) - maybe we need a new JSON or RDF attribute "datatype."

**Comment by Jegelewicz** [comment]
I will work with @mvzhuang to see if the social insect ontology will be useful, in the mean time, I will also add a free text attribute of "behavior".

**Comment by Jegelewicz** [comment]
I have created the attribute "behavior". The social insect ontology did not seem very useful and contained nearly zero definitions.

@mvzhuang just looking at your data, I think it might be good to create a controlled vocabulary for behaviors - at least for these:

active - moving or tending to move about vigorously or frequently
immobile - not moving; motionless
normal - as expected given environmental conditions
inactive - slow-moving or sluggish (these are "sluggish" in Bill's data)
nest building - actively constructing a nest
foraging - searching for or obtaining search food or provisions
aggressive - ready or likely to attack or confront
escape - eluding capture
feign death - pretending to be dead
brood rescue - attempting to save eggs, larvae, or juveniles
mating flight - phase in the reproduction of most ant, termite, and some bee species in which virgin queens mate with males and then land to start a new colony, or, in the case of honey bees, continue the succession of an existing hived colony
docile - easily managed or handled (=non-aggressive)

The modifiers (very, etc.) could be added in the attribute remarks. If we do this and have "behavior" be controlled vocabulary limited to these items, then we probably should also add:

behavior data - general description of behavior beyond controlled vocabulary of the behavior attribute

Thoughts?

**Comment by Jegelewicz** [comment]
@mvzhuang can we close this?

**Comment by Jegelewicz** [comment]
closing for lack of interest
