### ISSUE TITLE
Population description attribute

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2034]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Table**
http://arctos.database.museum/info/ctDocumentation.cfm?table=CTATTRIBUTE_TYPE

**Value**
Population description

**Definition**
description of population where specimen was found (i.e. brood and males and females) (may need discussion)

**Collection type**
Ento

**Attribute data type**
free-text

**Attribute value**
N/A

**Attribute units**
N/A

**Part tissue flag**
N/A

**Other ID BaseURL**
N/A

**Context**
Looking for proper place to record data related to nests of ants.

**Priority**
Please assign a priority-label.

**Comment by Jegelewicz** [comment]
I'm wondering if recording an observation of the nest might be a better way to do this, then relate the specimens from a given observed nest to the nest

**Comment by mvzhuang** [comment]
I don't think the nests are actually catalogued for most of them. There may be a few but I can't tell from the data I have right now.

This could also be under nest description but currently nest description is defined as "what the nest is made out of" for birds

Here's the data that shows this: I have values like "brood, males and females, lots of workers, brood and females, number of female queens"

[PopulationDescription.xlsx](https://github.com/ArctosDB/arctos/files/3045774/PopulationDescription.xlsx)

**Comment by dustymc** [comment]
>nest description is defined

I think that can be changed.

>brood, males and females, lots of workers, brood and females, number of female queens"

If anyone might ever care to search that, then cataloging that would give you access to https://arctos.database.museum/info/ctDocumentation.cfm?table=CTAGE_CLASS, https://arctos.database.museum/info/ctDocumentation.cfm?table=CTCASTE, etc. in the expected places. Individuals could be linked to/from the 'lot.'

So what Teresa said, but "the nest" could also carry attributes of observed individuals. If there's no physical material cataloged then there are just no parts. (It could be in an observations collection as well, but that's administrative and arbitrary.)

**Comment by mvzhuang** [comment]
Ok I think that works then.

--
Sorry I just understood your last paragraph right as you posted it. Here's the file again just in case.
[PopulationDescription.xlsx](https://github.com/ArctosDB/arctos/files/3045790/PopulationDescription.xlsx)

Here's the data that shows this: I have values like "brood, males and females, lots of workers, brood and females, number of female queens"

**Comment by dustymc** [comment]
And to clarify, I think cataloging "the nest" is ideal. If you don't have the resources to do so, or don't think the data you have justifies the work, I don't have much problem with a new Attribute.

**Comment by mvzhuang** [comment]
I think I'm going to have to just test out these things to see how much time it takes, but I think it will work.
