### ISSUE TITLE
New loan status - returned

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2035]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Table**
http://arctos.database.museum/info/ctDocumentation.cfm?table=CTLOAN_STATUS

**Value**
returned

**Definition**
all loaned objects are returned and accounted for

**Collection type**
N/A

**Attribute data type**
N/A

**Attribute value**
N/A

**Attribute units**
N/A

**Part tissue flag**
N/A

**Other ID BaseURL**
N/A

**Context**
From #1645 

> The other missing piece from Harvard is the idea of a closed loan - I believe they differentiate between "returned" (material is where it belongs) and "closed" (reprints and GenBank and whatever other requirements were in the agreement have been dealt with). The notifications are for "not closed" so that's just a new value in http://arctos.database.museum/info/ctDocumentation.cfm?table=CTLOAN_STATUS. There's no obvious technical component to that, but it sounds like a really useful thing to me.

**Note** along with this new term, the definition of "closed" in this code table should be changed to "all loaned objects are returned and accounted for and resulting products such as reprints and measurements have been documented"

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
Definition
all loaned objects are returned and accounted for **but other requirements of the loan have not been met** (er sumthin...)

**Comment by Jegelewicz** [comment]
That's fine with me.

**Comment by campmlc** [comment]
But loan is not closed because other loan requirements have not been met.

**Comment by dustymc** [comment]
done

**Comment by dustymc** [comment]
@campmlc @KyndallH

**Comment by campmlc** [comment]
That works for me, as all my loan items are consumable, non returnable. So notifications would go out for open or returned loans but not closed loans? This should be made clear, as the words themselves don't imply that.
