### ISSUE TITLE
Bulk load loan items problem: unique constraint (UAM.PK_LOAN_ITEM) violated

### ISSUE THREAD

**Issue by acoconis** [ArctosDB/arctos#2036]
I am trying to bulk load loan items. I have successfully done this with other similar documents. Using the attached document(in csv format)
[BulkLoanItem1988.4.xlsx](https://github.com/ArctosDB/arctos/files/3048573/BulkLoanItem1988.4.xlsx)
, I have tried to load but I am getting this error message:

unique constraint (UAM.PK_LOAN_ITEM) violated

I get all the way through the steps (everything looks spiffy), but it won't let me proceed.

Thanks for the help!

[BulkLoanItem1988.4.xlsx](https://github.com/ArctosDB/arctos/files/3048567/BulkLoanItem1988.4.xlsx)

**Comment by dustymc** [comment]
That is the unique key on (loan, item). You are trying to re-add an item that's already in the loan, either because you're trying to add an item that's already in the loan or because there are duplicates in the bulkloader.

At least these are in there twice:


16275
16276
16277
16278

**Comment by acoconis** [comment]
Thank you. Resolved.
