### ISSUE TITLE
Last name triggers are going too far

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2037]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Attempting to add agent W. Langston

after click "force create because of initial, get this error
![image](https://user-images.githubusercontent.com/5725767/55684588-d3881780-5909-11e9-879b-fa846592f0f3.png)

Last name is NOT all lower OR upper case. What's going on?

**To Reproduce**

**Expected behavior**
I expect the agent name to load

**Screenshots**

** Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by Jegelewicz** [comment]
This is blocking bulkloading for ALMNH

**Comment by dustymc** [comment]
fixed
