### ISSUE TITLE
/info/sysstats.cfm - now taking requests

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#2040]
UAM@ARCTOS> select count(*) from taxon_relations;

  COUNT(*)
----------
   1029555

**Comment by dustymc** [comment]
add open/reviewed annotations

Should we also break the stats down by collection and/or Institution?

**Comment by Jegelewicz** [comment]
> Should we also break the stats down by collection and/or Institution?

Both would be awesome, but if we have them by collection, we can add up what belongs in an institution...right?

**Comment by dustymc** [comment]
http://arctos.database.museum/info/sysstats.cfm is new, fast, and scheduled to rebuild itself weekly.

The UI is a little dense, but there's a CSV option....

I'll leave this open a bit in case anyone wants to request additions or changes.

/remind me to check back in a week

**Comment by sharpphyl** [comment]
Impressive table but what does #taxonrelations mean?

**Comment by dustymc** [comment]
That's the number of relationships between taxa in Arctos.

**Comment by ccicero** [comment]
Also add other taxonomic counts: # families, # genera, # species

Useful for tours, but also grant proposals.

**Comment by Jegelewicz** [comment]
Can we make the headers remain visible as you scroll down? When I get down to UTEP I can't see what these numbers mean.

**Comment by campmlc** [comment]
Can we add CITES info?

**Comment by dustymc** [comment]
change specimen label to - uhh, something. Cataloged items?

**Comment by ccicero** [comment]
Visually, would it be better to right justify the institution:collection, rather than centered? Might be easier on the eyes.

**Comment by Jegelewicz** [comment]
> change specimen label to - uhh, something. Cataloged items?

I like that vs. objects

**Comment by dustymc** [comment]
>right justify the institution:collection

done

Specimens is now CatalogedItems  - but see http://handbook.arctosdb.org/documentation/catalog.html

>The term “specimen” is used synonymously with “cataloged item” throughout Arctos.

@ccicero is ``count(distinct(genus)) from FLAT`` (eg, number of genera used in accepted IDs from the collection's preferred classification) suitable for " taxonomic counts: # families, # genera, # species" etc?

@campmlc what exactly do you want for "CITES info"?

@Jegelewicz static headers are non-trivial. I've tried to mitigate that somewhat with titles - mouseover and you should get a popup, so it's not COMPLETELY impossible to figure out what's going on.

We can do that (probably by using the specimenresults UI), but I question whether a table is the best way to show these data (esp. given that you can get CSV and see it in any UI you want). If we're going to invest in UI (and again see CSV option - I'm not 100% sure we should) maybe we should back WAY up and talk big-picture - eg, would that be better if it looked a bit more like https://www.gbif.org/network/1f2c0cbe-40df-43f6-ba07-e76133e78c31/metrics, or expando-tiles, or ??????????

**Comment by Jegelewicz** [comment]
> @Jegelewicz static headers are non-trivial. I've tried to mitigate that somewhat with titles - mouseover and you should get a popup, so it's not COMPLETELY impossible to figure out what's going on.

How easy to limit the table to an institution or collection(s)? So if I go check it I can say, "only show me UTEP"....

**Comment by Jegelewicz** [comment]
> I question whether a table is the best way to show these data (esp. given that you can get CSV and see it in any UI you want). If we're going to invest in UI (and again see CSV option - I'm not 100% sure we should) maybe we should back WAY up and talk big-picture - eg, would that be better if it looked a bit more like https://www.gbif.org/network/1f2c0cbe-40df-43f6-ba07-e76133e78c31/metrics, or expando-tiles, or ??????????

Tables and graphs are both good - depends on the intended use. Agree that this is a big picture want and that for now, what you have done is great!

**Comment by dustymc** [comment]
>limit the table to an institution 

Pretty weird since I didn't include those data (and a bunch of them are nonsensical anyway).

>collection

done
