### ISSUE TITLE
We need a UI to update cf_ctuser_roles.

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2042]
@dustymc can we make the links on the [User Role](http://arctos.database.museum/Admin/user_roles.cfm) page click through to the documentation?

Also, instead of showing the link, can we have text as follows:

Role Name | Access Description | Required Reading | DB Definition
-- | -- | -- | --
coldfusion_user | Access to bulkoader tools. Required for ALL Operators. |   | [ Def ]
data_entry | Data entry and specimen bulkloader | [Understanding Data Entry](http://handbook.arctosdb.org/how_to/Understanding-data-entry.html) | [ Def ]
dgr_locator | DGR personnell ONLY |   | [ Def ]
global_admin | Invite users to become operators; grant and revoke rights from users and Operators, create clones of catalog items, create DOIs. | [Sharing Data and Resources](http://handbook.arctosdb.org/documentation/sharing-data-and-resources.html)  | [ Def ]
manage_agents | Create, delete and edit Agents | [Arctos Agent Documentation](http://handbook.arctosdb.org/documentation/agent.html) and [How to Create Agents](http://handbook.arctosdb.org/how_to/How-to-Create-Agents.html) | [ Def ]
manage_codetables | Create, delete and edit Code Table values | [Arctos Code Table Documentation](http://handbook.arctosdb.org/how_to/Code-Tables.html) | [ Def ]
manage_collection | Manage Collection metadata, DELETE cataloged items and and identifications, mark  records in bulkloader to load. | [How to Manage a Collection](http://handbook.arctosdb.org/how_to/How-to-Manage-a-Collection-in-Arctos.html)  | [ Def ]
manage_container | Create, delete and edit containers. Note: manage_specimens can update container (ie, to associate a specimen with a container) | [Arctos Container Documentation](http://handbook.arctosdb.org/documentation/container.html) and [How to Start Object Tracking in Arctos](http://handbook.arctosdb.org/how_to/How-to-Start-Object-Tracking.html) | [ Def ]
manage_documentation | manage popup documentation |   | [ Def ]
manage_geography | Create, delete and edit Higher Geography. **Should be very limited access** | [Arctos Higher Geography Documnetation](http://handbook.arctosdb.org/documentation/higher-geography.html) and [Understanding the Arctos Locality Model](http://handbook.arctosdb.org/how_to/How-to-understand-the-Arctos-Locality-Model.html) | [ Def ]
manage_locality | Create, delete and edit locality and coordinates | [Arctos Locality Documentation](http://handbook.arctosdb.org/documentation/locality.html) and [Understanding the Arctos Locality Model](http://handbook.arctosdb.org/how_to/How-to-understand-the-Arctos-Locality-Model.html) | [ Def ]
manage_media | Create, delete and edit media | [Arctos Media Documentation](http://handbook.arctosdb.org/documentation/media.html) and [How to Create Media](http://handbook.arctosdb.org/how_to/How-to-Create-Media-Images.html) | [ Def ]
manage_publications | Create, delete and edit publications and projects | [Arctos Publication Documentation](http://handbook.arctosdb.org/documentation/publications.html) and [Arctos Project Documentation]( http://handbook.arctosdb.org/documentation/projects.html) | [ Def ]
manage_specimens | Manipulate most things at Specimen detail level including manage Citations **Appropriate access for most "Good Students"** | [How to Enter Data for a Single Specimen](http://handbook.arctosdb.org/how_to/How-to-Enter-Data-for-a-Single-Record.html)  | [ Def ]
manage_taxonomy | Create, delete and edit taxon names, classifications and relationships. **Should be limited access (note: this is NOT identification)** | [Arctos Taxonomy Documentation](http://handbook.arctosdb.org/documentation/taxonomy.html) and [How to Create Taxa](http://handbook.arctosdb.org/how_to/How-to-Create-Taxa.html) | [ Def ]
manage_transactions | Create, delete and edit accessions, loans, borrows, and permits | [Arctos Transaction Documnetation](http://handbook.arctosdb.org/documentation/transactions.html); [How to Create an Accession](http://handbook.arctosdb.org/how_to/How-to-Create-an-Accession.html); [How to Create a New Loan](http://handbook.arctosdb.org/how_to/How-to-Create-a-New-Loan.html); [How to Create a Publication](http://handbook.arctosdb.org/how_to/How-to-Create-a-Publication.html); and [How to Create a Permit](http://handbook.arctosdb.org/how_to/How-to-Create-a-Permit.html) | [ Def ]
public | Allows users to download data |   | [ Def ]

**Comment by dustymc** [comment]
Probably not without mangling the copypasta...

I've started https://docs.google.com/spreadsheets/d/1bI7c7nXmt2EOee3ZJshJ0NvhtDzDmfRUv9KSR9L3PJM/edit#gid=0 from which I can just update - feel free to jump in

**Comment by Jegelewicz** [comment]
OK - I added stuff the way it looks in the table I created above but the ";"s and "and"s may not be right - I don't speak the language...

**Comment by dustymc** [comment]
Thanks/done/give it a whirl.

Now I'm going to hijack your thread...

We need a UI to update cf_ctuser_roles.

**Comment by Jegelewicz** [comment]
Nice. Thanks!

**Comment by dustymc** [comment]
UI is available from http://arctos.database.museum/Admin/user_roles.cfm
