### ISSUE TITLE
New collector role

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2045]
From #2044 
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Table**
http://arctos.database.museum/info/ctDocumentation.cfm?table=CTCOLLECTOR_ROLE

**Value**
subject

**Definition**
person depicted in a work of art

**Collection type**
All

**Attribute data type**
agent name

**Attribute value**
Agents

**Attribute units**
N/A

**Part tissue flag**
N/A

**Other ID BaseURL**
N/A

**Context**
However, I wonder if it would be useful for our Art collections to have an agent role "subject" for portraits? I know they do something with locality regarding what place is depicted in landscapes. Maybe @marecaguthrie or @krgomez could weigh in on the usefulness of that as a new agent role? It's sort of related to that author role I brought up in #1863 .

**Priority**
Please assign a priority-label.

**Comment by Jegelewicz** [comment]
> What we have done for images depicting agents is to use the "shows agent" media relationship for the media that shows the collection object.

But if there is no media related to the object, this is not useful. I like the idea of placing the "subject", when it is a person, right up front with the maker/collector.

**Comment by campmlc** [comment]
I agree with this.

**Comment by AJLinn** [comment]
Yes yes, a thousand times yes.

**Comment by Jegelewicz** [comment]
Added.

**Comment by dustymc** [comment]
@AJLinn  how do you really feel about this?!

My only objection is in the definition - it should be more generic so it can cover field photos and such. "Agent depicted in the cataloged item."?

**Comment by Jegelewicz** [comment]
done

**Comment by AJLinn** [comment]
> "Agent depicted in the cataloged item."?

100% agree - cataloged item could be things other than art
