### ISSUE TITLE
Organism ID Resolver Collection

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2047]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
We have parts of a single organism cataloged in multiple collections (including some which are not in Arctos). We can use other ID's and relationships to present this information in Arctos, but there is difficulty in translating this to aggregators via the dwcorganismID field as there is no single place to resolve the multiple identifiers. See #1966 

**Describe the solution you'd like**
An organism ID resolver collection in Arctos (Guid Prefix = OID.XXX, where XXX is the appropriate collection 'type' ie. Mamm, Herp, Herb, etc.). Using Arctos capabilities, the catalog number created in this collection would connect to all of the other identifiers associated with a single organism (which might be an animal, plant, colony, nest, etc.) via the other ID and relationship model currently in use. However, this record would not be considered an "occurrence", nor would it be sent to aggregators. It would just supply the dwcOrganismID needed to link the associated parts at the aggregators AND would be another marketing tool for Arctos with the potential for becoming THE organismID resolver with very little up-front work on our part. (Managing this is probably the biggest challenge - who should manage it and how should it be managed?)

**Describe alternatives you've considered**
ARKs (not as permanent as we might like) and DOIs (cost money and require every institution with parts from an organism to be able to use them?)

**Additional context**
See the recently released [Extended Specimen Report](https://www.aibs.org/home/assets/BCoN_March2019_FINAL.pdf).

> Work  with  data  creators  and  providers  to  extend  biodi-versity specimens to create stable data linkages.

**Priority**
Please assign a priority-label. - Marking critical because now is the time to strike.

**Comment by campmlc** [comment]
Absolutely agree with this. It would solve many issues we currently have
tracking parts of the same organism across collections within Arctos, and
it would put us ahead of everyone else in being able to link out across
institutions, e.g between AMNH and SI (EMU institutions) and Arctos
collections.

**Comment by dustymc** [comment]
Completely agreed with the idea.

I think this particular approach is overkill, too much work, too much structure, too confusing, and too likely to be seen as "an Arctos thing" instead of "a global thing."

I'm about 99% sure I know how to build this so it's seamless for stuff in Arctos (eg, I can use relationships to magic stuff in), accessible for anyone (we can grant access to not-Arctos 'collaborators' without needing to give them scary access to other stuff or make them go through the Operator procedure), portable, Arctos-agnostic, etc.

I can probably build a demo faster than I can explain the details, but basically I think this would just be a list of identifiers under a GUID. (The GUID could then be used as an ID in Arctos records.)

From that, we could (maybe with funding) eg, pull data from the identifiers (so we can detect outliers, flag non-functional identifiers, etc.), add ARKS (er sumthin) so it's not Arctos-centric (or maybe that's basic functionality??), build services to make integration with other stuff easier, notify 'collaborators' of random stuff, etc., etc. etc.

Shall I?

**Comment by campmlc** [comment]
Will your solution solve the AMNH/Arctos problem?

**Comment by dustymc** [comment]
Define "solve."

I can't add a field to their database, populate it, or get them to think outside their collection. I can provide a good identifier that, should they ever have a place for it and the inclination to use it, would let them link to (or pull data from) related specimens, bring things together on GBIF, etc.

I can also provide tools that'll let GBIF (and friends) do much of that even if AMNH can't. I can't force them to use it either.

So no, but I think it can do everything that's technically possible from outside of their collection.

**Comment by dustymc** [comment]
https://n2t.net/ark:/99999/fk4sx7j29k (https://arctos.database.museum/demo) is a QnD hard-coded demo of what I have in mind.

Those data could be made available to eg, GBIF so they could build Organisms from any of the listed IDs.

GBIF has a decent service, so we could go looking through GBIF using those IDs to find related stuff (if it contains IDs in some recognizable format - I still can't alter AMNH's data).

The "OrganismID" is neutral and the UI is potentially just one of many (eg, I think this would be primarily service-based).

Note the OrganismID in the "results" table - this can tie organisms (maybe 2 sets of 'Occurrences') together (eg, when someone notices a common number). That could be automated (with resolvable IDs) or provide suggestions (eg, NK=12 might be a unifying ID or just an artifact of a printer jam).

**Comment by Jegelewicz** [comment]
> I can probably build a demo faster than I can explain the details, but basically I think this would just be a list of identifiers under a GUID. (The GUID could then be used as an ID in Arctos records.)

We need more than a list of IDs. There needs to be metadata so that anyone looking at the OrganismId record can tell WHAT it is and add their IDs if known.

**Comment by dustymc** [comment]
>WHAT

That's "We can eventually pull stuff from a service" - at least Arctos and GBIF provide services to access data, and an exchange standard exists.

> cataloged item has everything we need

It does, but there's about 0% chance someone from GBIF or AMNH will go through the process of becoming an Operator to add something, there's an absolute 0% chance we're going to give them access to any shared Roles, and there's probably about 0% chance anyone will find the time to enter or maintain the data. It's there if you want it, but I don't see the point.

>Agents table 

Decent analogy - preferred name:

<img width="307" alt="Screen Shot 2019-04-18 at 12 30 52 PM" src="https://user-images.githubusercontent.com/5720791/56386109-d5898a80-61d5-11e9-9bbf-5c6bb8c40104.png">

other names and addresses:

<img width="884" alt="Screen Shot 2019-04-18 at 12 31 16 PM" src="https://user-images.githubusercontent.com/5720791/56386130-e3d7a680-61d5-11e9-8c36-e17963f8166b.png">

>A particular organism or defined group of organisms considered to be taxonomically homogeneous.

That definition seems so crazy to me, but you can certainly catalog whatever you want. (All identifiers are not capable of the same precision and do not subscribe to the same taxonomic hypotheses, and 'defined group' could be absolutely anything.)

**Comment by campmlc** [comment]
I think what Teresa is getting at is that people from outside of Arctos
could find the relationships between their specimens and our organism IDs.
So would AMNH be able to search GBIF to find that their AMNH 12345 actually
shares an NK with MSB:Mamm:67890 and then know to add the organism ID below
to their records? Or would GBIF resolve the two for everyone?

[image: image.png]

**Comment by Jegelewicz** [comment]
GBIF could resolve if we can give them an OrganismID that has both our catalog number and AMNH's catalog number associated with it.

**Comment by dustymc** [comment]
>people from outside of Arctos could find the relationships

Yes, in both models. In something dedicated to this they could create relationships as well.

>AMNH be able to search GBIF to find that their AMNH 12345 actually shares an NK with MSB:Mamm:67890

The answer is the same in both models, although understanding what you've found might be easier in a dedicated service.

>add the organism ID below to their records

That's the same answer too. What I'm proposing would use some neutral ID as the primary identifier, but it's possible to abstract Arctos URLs through various services so call it a wash.

>Or would GBIF resolve the two for everyone?

From specimen records, that's probably possible if they really want to, and if we've added all the bits-n-pieces to whatever record they find. From data designed to do that in a service designed to support that it might be harder for them to find an excuse not to, and all of the information should be in one place.

**Comment by Jegelewicz** [comment]
>>WHAT

> That's "We can eventually pull stuff from a service" - at least Arctos and GBIF provide services to access data, and an exchange standard exists.

I don't know where it's supposed to come from or why we should "eventually pull it" when we have it right now.

We know that 

MSB:Mamm:233254
MSB:Mamm:233261
MSB:Mamm:233262
MSB:Mamm:232673
MSB:Mamm:268079
MSB:Mamm:270001
Mexican Wolf Recovery Studbook Number 1216

are all from a single female Mexican Wolf (_Canis lupus baileyi_)

So why not enter the metadata we know now to help guide others who might have other specimens related to this wolf?

>>cataloged item has everything we need

>It does, but there's about 0% chance someone from GBIF or AMNH will go through the process of becoming an Operator to add something, there's an absolute 0% chance we're going to give them access to any shared Roles, and there's probably about 0% chance anyone will find the time to enter or maintain the data. It's there if you want it, but I don't see the point.

I think you missed my point here - I mean that a standard Arctos catalog record would include the metadata we would need for the Organism (identification, traits, other identifiers). We would need to figure out if events would be needed at all (although in the case of this wolf, birth and death events would probably be appropriate?) and parts would also be unnecessary (?). So if we had an Arctos collection (GUID prefix OID:Mamm) and our first organism was this wolf, it would have the GUID **OID:Mamm:1** with an identification of **_Canis lupus baileyi_**, an attribute **sex=female**, and 7 other IDs: **MSB:Mamm:233254, MSB:Mamm:233261, MSB:Mamm:233262, MSB:Mamm:232673, MSB:Mamm:268079, MSB:Mamm:270001, Mexican Wolf Recovery Studbook Number 1216**

> That definition seems so crazy to me, but you can certainly catalog whatever you want. (All identifiers are not capable of the same precision and do not subscribe to the same taxonomic hypotheses, and 'defined group' could be absolutely anything.)

I don't think it is really so crazy. It is intended to be broad in order that a single mouse can be considered an organism or a colony of mice can be considered one. And maybe that should be a special attribute for records in this collection. It could follow the dwcorganismscope field:

organismScope Property
--
Identifier | http://rs.tdwg.org/dwc/terms/organismScope
Definition | A description of  the kind of Organism instance. Can be used to indicate whether the  Organism instance represents a discrete organism or if it represents a  particular type of aggregation.
Comments | Recommended best  practice is to use a controlled vocabulary. This term is not intended to  be used to specify a type of taxon. To describe the kind of  dwc:Organism using a URI object in RDF, use rdf:type (http://www.w3.org/1999/02/22-rdf-syntax-ns#type) instead.

**Comment by dustymc** [comment]
>where it's supposed to come from 

Arctos, GBIF, AMNH, whatever's at the end of the URL (if it'll talk to us).

>why we should "eventually pull it" when we have it right now.

We can invest some time into building something that'll pull/maintain data from various places, or we can use existing tools and try to remember to update two things in Arctos when something changes, hope we somehow notice changes in GBIF, etc., etc., etc.

>missed my point

Could be. FWIW most of my point is above: I'd rather build a service than try to replicate pieces of multiple systems (which almost certainly all contain variations in the data) with a keyboard. A service-based approach would have the benefit of making the answers to your questions about parts and events and such irrelevant as well: the data are there if and when you want them.
