### ISSUE TITLE
Donate barcodes for an entire freezer box

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2050]
@dustymc as you know, we have A LOT of barcode-less labels here at MSB. I am trying to get barcodes on these containers, but the process of donating barcodes to the labels one by one is time-consuming using the scary red box. I have attached a CSV that includes the labels (already in Arctos) and the new barcodes that have been added to the containers as well as the positions in the box for each combination for a single freezer box. Can you create a tool for us to donate these barcodes in bulk? This is going to be happening a lot and I don't want to have to bother you every time we need a box done.

Thanks!
[Donate barcodes DGR13517.zip](https://github.com/ArctosDB/arctos/files/3104347/Donate.barcodes.DGR13517.zip)

**Comment by dustymc** [comment]
Does anyone have a compelling reason to use this for something other than nuncs in positions in freezer boxes?

If we can limit this to that, it should be pretty straightforward.

If it needs to be more flexible, not so much.

This is sort of a terrifying form - it does something that violates some fundamentals of a defensible tracking system (but for good reason!) to lots of stuff at once - so I'm very happy to keep it constrained if possible.

**Comment by Jegelewicz** [comment]
> Does anyone have a compelling reason to use this for something other than nuncs in positions in freezer boxes?

I don't, and I would recommend getting rid of the tool when we have completed our barcoding. I think we are the only crazy people who have done this en masse and I will probably go freezer box by freezer box so that I can check the results and make sure everything has been completed properly for each box. Also, I was thinking about this in my sleep and I guess I should have added a column to that CSV - Freezer Box Barcode, which for that file would be DGR13517.

FWIW - I would never recommend using unbarcoded labels to anyone.

**Comment by dustymc** [comment]
That works for me.

**Comment by campmlc** [comment]
Agree.

**Comment by dustymc** [comment]
@Jegelewicz I'm close to ready to "test" this, without a dev environment. Can I use your attachment above for that?

**Comment by Jegelewicz** [comment]
YUP

Then I can see how it worked...

**Comment by dustymc** [comment]
There's a local pre-button-smashing backup in container_bak20190424 and a scary new form at....

<img width="366" alt="Screen Shot 2019-04-24 at 6 01 08 PM" src="https://user-images.githubusercontent.com/5720791/56702842-f876db80-66ba-11e9-8294-a6804861bc1a.png">

**Comment by campmlc** [comment]
Before we close this issue, I need @dustymc to "scary red box" in bulk new barcodes for three freezers worth of freezer boxes. We'll be needing this again intermittently.  Priority high because of freezer failure and we need to shift things around.
[DGR_8_9_11_box_barcodes_for_Dusty.zip](https://github.com/ArctosDB/arctos/files/3377440/DGR_8_9_11_box_barcodes_for_Dusty.zip)

**Comment by campmlc** [comment]
Belay that - Teresa has already done DGR8. Here is amended file for upload:
[DGR_9_11_box_barcodes_for_Dusty.zip](https://github.com/ArctosDB/arctos/files/3377524/DGR_9_11_box_barcodes_for_Dusty.zip)

**Comment by dustymc** [comment]
There are "donor" containers that aren't labels, and some that are parents. I can't deal with either.


UAM@ARCTOS> select distinct container_id ,barcode, container_type from container where barcode in (select NEW_BARCODE from temp_mc_b) and container_type not like '%label';

CONTAINER_ID
------------
BARCODE
------------------------------------------------------------------------------------------------------------------------
CONTAINER_TYPE
------------------------------------------------------------------------------------------
    14845786
DGR14290
freezer rack

    14850257
DGR18808
freezer box

    14850258
DGR18809
freezer box

    14850259
DGR18810
freezer box

    14850260
DGR18811
freezer box

    14850261
DGR18812
freezer box

    14850262
DGR18813
freezer box

    14850263
DGR18814
freezer box

    14850264
DGR18815
freezer box

    14850265
DGR18816
freezer box

    14850266
DGR18817
freezer box

    14850267
DGR18818
freezer box

    14850268
DGR18819
freezer box

    14850269
DGR18820
freezer box

    14850270
DGR18821
freezer box

    14850271
DGR18822
freezer box

    14850272
DGR18823
freezer box

    14850273
DGR18824
freezer box

    14850274
DGR18825
freezer box

    14850275
DGR18826
freezer box

    14850276
DGR18827
freezer box

    14850277
DGR18828
freezer box

    14850278
DGR18829
freezer box

    14850279
DGR18830
freezer box

    14850280
DGR18831
freezer box

    14850281
DGR18832
freezer box

    14850282
DGR18833
freezer box

    14850283
DGR18834
freezer box

    14850284
DGR18835
freezer box

    14850285
DGR18836
freezer box

    14850286
DGR18837
freezer box

    14850287
DGR18838
freezer box

    14850288
DGR18839
freezer box

    14850289
DGR18840
freezer box

    14850290
DGR18841
freezer box

    14850291
DGR18842
freezer box

    14850292
DGR18843
freezer box

    14850293
DGR18844
freezer box

    14850294
DGR18845
freezer box

    14850295
DGR18846
freezer box

    14850296
DGR18847
freezer box

    14850297
DGR18848
freezer box

    14850298
DGR18849
freezer box

    14850299
DGR18850
freezer box

    14850300
DGR18851
freezer box

    14850301
DGR18852
freezer box

    14850302
DGR18853
freezer box

    14850303
DGR18854
freezer box

    14850304
DGR18855
freezer box

    14850305
DGR18856
freezer box

    14850306
DGR18857
freezer box

    14850307
DGR18858
freezer box

    14850308
DGR18859
freezer box

    14850309
DGR18860
freezer box

    14850310
DGR18861
freezer box

    14850311
DGR18862
freezer box

    14850312
DGR18863
freezer box

    14850315
DGR18866
freezer box

    14850316
DGR18867
freezer box

    14850317
DGR18868
freezer box

    14850318
DGR18869
freezer box

    14850319
DGR18870
freezer box

    14850320
DGR18871
freezer box

    14850321
DGR18872
freezer box

    14850322
DGR18873
freezer box

    14850323
DGR18874
freezer box

    14850324
DGR18875
freezer box

    14850325
DGR18876
freezer box

    14850326
DGR18877
freezer box

    14850327
DGR18878
freezer box

    14850328
DGR18879
freezer box

    14850329
DGR18880
freezer box

    14850330
DGR18881
freezer box

    14850331
DGR18882
freezer box

    14850332
DGR18883
freezer box

    14850333
DGR18884
freezer box

    14850334
DGR18885
freezer box

    14850335
DGR18886
freezer box

    14850336
DGR18887
freezer box

    14850337
DGR18888
freezer box

    14850338
DGR18889
freezer box

    14850339
DGR18890
freezer box

    14850340
DGR18891
freezer box

    14850341
DGR18892
freezer box

    14850342
DGR18893
freezer box

    14850343
DGR18894
freezer box

    14850344
DGR18895
freezer box

    14850345
DGR18896
freezer box

    14850346
DGR18897
freezer box

    14850347
DGR18898
freezer box

    14850348
DGR18899
freezer box

    14850349
DGR18900
freezer box

    14850350
DGR18901
freezer box

    14850351
DGR18902
freezer box

    14850352
DGR18903
freezer box

    14850353
DGR18904
freezer box

    14850354
DGR18905
freezer box

    14850355
DGR18906
freezer box

    14850356
DGR18907
freezer box

    14850357
DGR18908
freezer box

    14850358
DGR18909
freezer box

    14850359
DGR18910
freezer box

    14850360
DGR18911
freezer box

    14850361
DGR18912
freezer box

    14850362
DGR18913
freezer box

    14850363
DGR18914
freezer box

    14850364
DGR18915
freezer box

    14850365
DGR18916
freezer box

    14850366
DGR18917
freezer box


109 rows selected.


UAM@ARCTOS> select container_id ,barcode, container_type from container where parent_container_id in (select container_id from container where barcode in (select NEW_BARCODE from temp_mc_b));

CONTAINER_ID
------------
BARCODE
------------------------------------------------------------------------------------------------------------------------
CONTAINER_TYPE
------------------------------------------------------------------------------------------
    19741047

position

    19741048

position

    19741049

position

    19741050

position

    19741051

position

    19741052

position

    19741053

position

    19741054

position

    19741055

position

    19741056

position

    19741057

position

    19741058

position


12 rows selected.

**Comment by campmlc** [comment]
If you can tell me which one(s) have positions, I can deal with those. This
one:  DGR14290 is a problem because it should be a box, not a rack. I'll
deal with that. Can you magic the remainer that are just boxes without
positions back to labels?

**Comment by Jegelewicz** [comment]
I returned DGR14290 to container label status.

**Comment by Jegelewicz** [comment]
@dustymc If you can tell me which one(s) have positions, I can deal with those. Can you magic the remainer that are just boxes without positions back to labels?

I really don't want to have to do this one by one...

**Comment by dustymc** [comment]
I think whatever you cleaned up fixed all of the position problems.

All of your NEW_BARCODE should now be 'container label' and the tool should be capable of handling them.

Yay??

**Comment by campmlc** [comment]
Agree- this is holding up a freezer move.

**Comment by Jegelewicz** [comment]
@dustymc so these labels are freezer boxes NOT cryovials in a box - with the tool work on that?

**Comment by Jegelewicz** [comment]
Related to this - here is another project. All of the barcodes scanned into freezer Box DGR10076 should NOT have been scanned in! Can you undo that and return all of those barcodes to labels?

**Comment by dustymc** [comment]
Derp...

So they're already all boxes

UAM@ARCTOS> select container_type from container where label in (select label from temp_mc_b) group by container_type;

CONTAINER_TYPE
------------------------------------------------------------------------------------------
freezer box

I just need to dump the container using NEW_BARCODE and give that barcode to the container using LABEL - correct?

**Comment by Jegelewicz** [comment]
> I just need to dump the container using NEW_BARCODE and give that barcode to the container using LABEL - correct?

Yep - all of them should have been donated to the associated labels, but instead were just created as separate freezer boxes.

**Comment by dustymc** [comment]
done

**Comment by Jegelewicz** [comment]
Thanks man!
