### ISSUE TITLE
Catalogue of Life Plus

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2053]
https://github.com/Sp2000/colplus

> Many large institutional users (i.e. GBIF, EOL, ALA, Lifewatch) extend their copy of the catalogue with additional names and species to complete it to serve their own specific purpose. These disconnected efforts result in ‘taxonomic inconsistencies’ and cause confusion amongst users.
> 
> The CoL+ project seeks to replace these efforts with a shared, extended catalogue and complete the reviewed name coverage without sacrificing quality. Creating an open, shared, and sustainable consensus taxonomy to serve the proper linking of data in the global biodiversity information initiatives is the ultimate goal the project contributes to.
> 
> The goals for the Catalogue of Life Plus (CoL+) project are:
> 
>     creating both an extended and a strictly scrutinized taxonomic catalogue to replace the current GBIF Backbone Taxonomy and Catalogue of Life
>     separating nomenclature (facts) and taxonomy (opinion) with different identifiers and authorities for names and taxa for better reuse
>     providing (infrastructural) support to the completion and strengthening of taxonomic and nomenclature content authorities
>     ensuring a sustainable, robust, and more dynamic IT infrastructure for maintaining the Catalogue of Life.
> 
> Specifically the project will establish a clearinghouse for taxonomy and nomenclature and rebuild all existing infrastructure of the Catalogue of Life including webservices, the portal and the software for the assembly of the catalogue and its editorial work.

**Comment by Jegelewicz** [comment]
@dustymc and @ArctosDB/taxonomy maybe the answer is coming to us?

**Comment by dustymc** [comment]
As always, if they build something useful we can use it.

**Comment by Jegelewicz** [comment]
https://github.com/orgs/ArctosDB/teams/taxonomy/discussions/22/comments/16

**Comment by dustymc** [comment]
Thanks @Jegelewicz  - here's the CSV of names used in Arctos and not in CoL (via GlobalNames).

[temp_nnign.csv.zip](https://github.com/ArctosDB/arctos/files/3303867/temp_nnign.csv.zip)

**Comment by Jegelewicz** [comment]
@dustymc see https://github.com/Sp2000/colplus/issues/53#issuecomment-503748117

**Comment by sharpphyl** [comment]
I've tried to run your SQL above to see just what's being used by DMNS:Inv that isn't in CoL.  4743 taxa seems like a lot.  Can you explain what I have to modify in the SQL to get just our used taxa?

**Comment by dustymc** [comment]
@sharpphyl  that's specimens (and the SQL will almost certainly time out in the UI). Here are your names.

```
create table temp_dmnsinv_n_col as select
taxon_name.scientific_name,
count(*) spcnt
from
collection,
cataloged_item,
identification,
identification_taxonomy,
taxon_name
where
guid_prefix='DMNS:Inv' and
collection.collection_id=cataloged_item.collection_id and
cataloged_item.collection_object_id=identification.collection_object_id and
identification.identification_id=identification_taxonomy.identification_id and
identification_taxonomy.taxon_name_id = taxon_name.taxon_name_id and
taxon_name.taxon_name_id not in (
select taxon_name_id from taxon_term where source='Catalogue of Life'
)
group by taxon_name.scientific_name order by taxon_name.scientific_name
;
2249 rows selected.

```
[temp_dmnsinv_n_col.csv.zip](https://github.com/ArctosDB/arctos/files/3343176/temp_dmnsinv_n_col.csv.zip)

**Comment by campmlc** [comment]
Interesting that MSB:Mamm has forty thousand names not in COL when there are only 5000 species of mammals. What is causing this discrepancy?

**Comment by campmlc** [comment]
Or are these catalogued items? Dusty, can you send the list for MSB?

**Comment by dustymc** [comment]
>catalogued items
>that's specimens 

yes

```
create table temp_msbmamm_n_col as select
taxon_name.scientific_name,
count(*) spcnt
from
collection,
cataloged_item,
identification,
identification_taxonomy,
taxon_name
where
guid_prefix='MSB:Mamm' and
collection.collection_id=cataloged_item.collection_id and
cataloged_item.collection_object_id=identification.collection_object_id and
identification.identification_id=identification_taxonomy.identification_id and
identification_taxonomy.taxon_name_id = taxon_name.taxon_name_id and
taxon_name.taxon_name_id not in (
select taxon_name_id from taxon_term where source='Catalogue of Life'
)
group by taxon_name.scientific_name order by taxon_name.scientific_name
 20  ;

Table created.

Elapsed: 00:00:28.65
UAM@ARCTOS> select count(*) from temp_msbmamm_n_col;

  COUNT(*)
----------
       915

1 row selected.

```

[temp_msbmamm_n_col.csv.zip](https://github.com/ArctosDB/arctos/files/3343235/temp_msbmamm_n_col.csv.zip)

**Comment by campmlc** [comment]
Looks like a very large number of these are subspecies.
@Jon Dunnum <jldunnum@unm.edu>

**Comment by jldunnum** [comment]
Yes that is correct, many are subspecies


______________________________________________________________

Jonathan L. Dunnum Ph.D.
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________
