### ISSUE TITLE
Add "valve" part to Inv collections?

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#2055]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Table**
Specimen part name
**Value**
valve

**Definition**
one half of a shell, specifically for bivalves

**Collection type**
Inv

**Part tissue flag**
no

**Context**
Some of parts are listed specifically as "valves" in our collections and others are listed as "shells". Does anyone have an opinion on this? Would it be better to have this as a separate part or just simply placed in the part remarks?

**Priority**
Please assign a priority-label.

**Comment by Jegelewicz** [comment]
I would place it in the part remarks, otherwise we will end up with many ways of saying "shell".

**Comment by mvzhuang** [comment]
Ok will do. Thanks!
