### ISSUE TITLE
part/container institution mismatch

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#2063]
ref:https://github.com/ArctosDB/arctos/issues/2048

These part-->container institution mismatches exist

```
select 
	part_inst || '-->' || ctr_inst
from (
	select 
		p.institution_acronym part_inst,
		c.institution_acronym ctr_inst,
		c.container_type,
		c.container_id 
	from 
		container p, 
		container c 
	where 
		p.parent_container_id=c.container_id and 
		p.container_type='collection object' and 
	c.institution_acronym!=p.institution_acronym
)
group by
	part_inst,
	ctr_inst
;
PART_INST||'-->'||CTR_INST
------------------------------------------------------------------------------------------------------------------------
KWP-->UAM
DMNS-->MSB
DMNS-->UAM
KNWR-->UAM
DGR-->MSB
MVZ-->UAM
MSB-->MVZ
UAM-->MSB
UAMb-->UAM
UAM-->UAMb
UAM-->MVZ
UAM-->KNWR
UAMObs-->UAM
```

Here are the ones I think are problematic.

```
--- MVZ parts in UAM containers
create table temp_mvz_p_uam_c as
select
	flat.guid,
	c.barcode,
	getContainerParentage(c.container_id) partCtrStk,
	specimen_part.collection_object_id partID,
	c.container_id part_container_id,
	specimen_part.part_name
from
	flat,
	specimen_part,
	coll_obj_cont_hist,
	container p,
	container c
where
	flat.collection_object_id=specimen_part.derived_from_cat_item and
	specimen_part.collection_object_id=coll_obj_cont_hist.collection_object_id and
	coll_obj_cont_hist.container_id=p.container_id and
	p.parent_container_id=c.container_id and
	c.institution_acronym='UAM' and
	p.institution_acronym='MVZ' 
;
```
[temp_mvz_p_uam_c.csv.zip](https://github.com/ArctosDB/arctos/files/3132500/temp_mvz_p_uam_c.csv.zip)

```
--- UAM parts in MVZ containers
create table temp_uam_p_mvz_c as
select
	flat.guid,
	c.barcode,
	getContainerParentage(c.container_id) partCtrStk,
	specimen_part.collection_object_id partID,
	c.container_id part_container_id,
	specimen_part.part_name
from
	flat,
	specimen_part,
	coll_obj_cont_hist,
	container p,
	container c
where
	flat.collection_object_id=specimen_part.derived_from_cat_item and
	specimen_part.collection_object_id=coll_obj_cont_hist.collection_object_id and
	coll_obj_cont_hist.container_id=p.container_id and
	p.parent_container_id=c.container_id and
	c.institution_acronym='MVZ' and
	p.institution_acronym='UAM' 
;
	
```
[temp_uam_p_mvz_c.csv.zip](https://github.com/ArctosDB/arctos/files/3132510/temp_uam_p_mvz_c.csv.zip)

```
--- UAM parts in MSB containers
create table temp_uam_p_msb_c as
select
	flat.guid,
	c.barcode,
	getContainerParentage(c.container_id) partCtrStk,
	specimen_part.collection_object_id partID,
	c.container_id part_container_id,
	specimen_part.part_name
from
	flat,
	specimen_part,
	coll_obj_cont_hist,
	container p,
	container c
where
	flat.collection_object_id=specimen_part.derived_from_cat_item and
	specimen_part.collection_object_id=coll_obj_cont_hist.collection_object_id and
	coll_obj_cont_hist.container_id=p.container_id and
	p.parent_container_id=c.container_id and
	c.institution_acronym='MSB' and
	p.institution_acronym='UAM' 
;
	
```
[temp_uam_p_msb_c.csv.zip](https://github.com/ArctosDB/arctos/files/3132516/temp_uam_p_msb_c.csv.zip)

```

--- MSB parts in MVZ containers
create table temp_msb_p_mvz_c as
select
	flat.guid,
	c.barcode,
	getContainerParentage(c.container_id) partCtrStk,
	specimen_part.collection_object_id partID,
	c.container_id part_container_id,
	specimen_part.part_name
from
	flat,
	specimen_part,
	coll_obj_cont_hist,
	container p,
	container c
where
	flat.collection_object_id=specimen_part.derived_from_cat_item and
	specimen_part.collection_object_id=coll_obj_cont_hist.collection_object_id and
	coll_obj_cont_hist.container_id=p.container_id and
	p.parent_container_id=c.container_id and
	c.institution_acronym='MVZ' and
	p.institution_acronym='MSB' 
;
```
[temp_msb_p_mvz_c.csv.zip](https://github.com/ArctosDB/arctos/files/3132521/temp_msb_p_mvz_c.csv.zip)

```

--- DMNS parts in UAM containers
create table temp_dmns_p_uam_c as
select
	flat.guid,
	c.barcode,
	getContainerParentage(c.container_id) partCtrStk,
	specimen_part.collection_object_id partID,
	c.container_id part_container_id,
	specimen_part.part_name
from
	flat,
	specimen_part,
	coll_obj_cont_hist,
	container p,
	container c
where
	flat.collection_object_id=specimen_part.derived_from_cat_item and
	specimen_part.collection_object_id=coll_obj_cont_hist.collection_object_id and
	coll_obj_cont_hist.container_id=p.container_id and
	p.parent_container_id=c.container_id and
	c.institution_acronym='UAM' and
	p.institution_acronym='DMNS' 
;
```
[temp_dmns_p_uam_c.csv.zip](https://github.com/ArctosDB/arctos/files/3132530/temp_dmns_p_uam_c.csv.zip)

Let me know how I can help.

**Comment by Jegelewicz** [comment]
@dustymc is this still a problem? If so, has it grown?

**Comment by Jegelewicz** [comment]
@dustymc still an issue or can we close?

**Comment by dustymc** [comment]
AWG:

- how to allow this when its legit and catch it when it's not?

create a yearly (?) report, send it to notifications

**Comment by ccicero** [comment]
Two MVZ birds fixed (moved from UAM to MVZ container) 3/24/2022.

**Comment by ccicero** [comment]
@dustymc @mkoo @cjconroy 

There were some mammal parts in a UAM parentless void which got moved to the container 21609971 (barcode MVZ). They got created as their own containers (ids 11565455, 14059683, 14059687).

These are not barcoded parts and should not be in that container. MVZ legacy data are in container "Museum of Vertebrate Zoology (institution)" without a barcode. More recent specimens without barcodes aren't in any container. 

I tried deleting the container but can't because of container history. Dusty, can you move those to our legacy "Museum of Vertebrate Zoology" with no barcode? Or how best to address these so that they aren't in barcoded 'MVZ' container?

![image](https://user-images.githubusercontent.com/967275/161159606-b49b976c-fed4-49a5-a38b-b09611c4482f.png)

**Comment by dustymc** [comment]
>They got created as their own containers (ids 11565455, 14059683, 14059687).

All parts are containers. You can't delete them because they're (also) parts, not because they have a history. (That cascades and won't prevent deletion.)

>MVZ...Museum of Vertebrate Zoology


```
arctosprod@arctos>> select count(*) from container where parent_container_id=(select container_id from container where label='Museum of Vertebrate Zoology');
 count  
--------
 911452
(1 row)
```

Oh my! That breaks everything. Why's that exist and how'd that all get there?!? (I did it while we were still trying to figure out the model?) My first impression is that these should all be moved to the actual void (parent_container_id=0) but ???

You also have https://arctos.database.museum/findContainer.cfm?barcode=1, to which you can easily move those parts (edit them, edit the record, probably other ways) because it has a barcode.

I can move whatever, but some consolidation seems like a useful thing.

**Comment by dustymc** [comment]
Can I move mvz parts that are in

https://arctos.database.museum/findContainer.cfm?container_id=21609971
https://arctos.database.museum/findContainer.cfm?container_id=10053150

to parent_container_id=0 ("the universe") - which is where all parts are initially created, and where "not tracked" parts would be expected to be found?

@atrox10 @ccicero 

Then we should see what else is in https://arctos.database.museum/findContainer.cfm?container_id=10053150, move them somewhere better, and get rid of that container

**Comment by dustymc** [comment]
Also: can I move the three (MVZ) parts in barcode=MVZ to parent_container_id=0 ("the universe")?

**Comment by Jegelewicz** [comment]
@atrox10 @ccicero see https://github.com/ArctosDB/arctos/issues/2063#issuecomment-1086356569
