### ISSUE TITLE
Error on Accession Bulkload

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2064]
Using this tool: http://arctos.database.museum/tools/BulkloadAccn.cfm
[Accessions 2000-2017.zip](https://github.com/ArctosDB/arctos/files/3135149/Accessions.2000-2017.zip)

Get this error:
![image](https://user-images.githubusercontent.com/5725767/57027796-965a3100-6bfa-11e9-9dfb-984920591af3.png)

With attached file.

Not sure what number the error is referring to....

**Comment by dustymc** [comment]
Try removing the last (blank) row.

**Comment by Jegelewicz** [comment]
HAHAHAHAHA!!!!! Why didn't I immediately think of that?

**Comment by Jegelewicz** [comment]
Welp, that didn't work - same error.

**Comment by dustymc** [comment]
the error finally came in so I can give you a real answer...

>IS_PUBLIC_FG (1=yes; anything else=no)

That's obviously not quite correct - it's a numeric field; 1==public, any other NUMBER is treated as zero==not-public.

**Comment by campmlc** [comment]
Too bad. Very funny. Don't worry, I'm sure our friend the extra space error
hasn't gone away.

**Comment by Jegelewicz** [comment]
OK, now how about this error:
![image](https://user-images.githubusercontent.com/5725767/57032236-256d4600-6c07-11e9-92de-d8c8eb44d63a.png)

[Accessions 2000-2017.zip](https://github.com/ArctosDB/arctos/files/3135409/Accessions.2000-2017.zip)

**Comment by dustymc** [comment]
agent roles
http://arctos.database.museum/info/ctDocumentation.cfm?table=cttrans_agent_role

**Comment by Jegelewicz** [comment]
Thanks!
