### ISSUE TITLE
semicolon in part name prevents delete

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#2065]
https://github.com/ArctosDB/arctos/issues/1460 will remove the offending part name, but seems to have stalled.

Not sure how to prioritize this.

**Comment by ccicero** [comment]
What about apostrophe? The example that Dusty helped with had an apostrophe in the part name, not a semi colon.
http://arctos.database.museum/guid/MVZ:Bird:191728

**Comment by dustymc** [comment]
Derp, yes it's an apostrophe, thanks!
