### ISSUE TITLE
data entry: depick locality

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#2066]
Should depicking a locality clear everything? If yes I can adjust; if not I can add another 'clear locality-stuff' button.

@ccicero

**Comment by sharpphyl** [comment]
No, for us we would not want it to clear everything.  When we depick a locality during data entry, we want to change some field in the locality but retain most of the data.  Most frequently, we need to change the depth at which the marine specimen was found but we want to keep all the other data intact.  Occasionally we only keep the higher geography and modify everything else.  But we would hate to lose the ability to depick the locality and still see, then modify, the original data.
