### ISSUE TITLE
Add Locality ID as a searchable field

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#2073]
I would be helpful if Locality ID were a data field that can be added to appear in a search.  

![Screen Shot 2019-05-08 at 7 19 38 AM](https://user-images.githubusercontent.com/15368365/57378328-c1480600-7161-11e9-9d1d-49eecbc0ba98.png)

Verbatim locality, Specific Locality and Locality nickname are available fields but not Locality ID.

![Screen Shot 2019-05-08 at 7 21 04 AM](https://user-images.githubusercontent.com/15368365/57378789-c35e9480-7162-11e9-9e26-ec19241b3b18.png)

We can add Collecting Event ID which helps to find inconsistencies but Locality ID would also we helpful.

Average priority unless others would find it helpful too.

**Comment by dustymc** [comment]
The 'priority' Locality_ID is in FLAT, you can add it to results if you want.

Unlike Verbatim locality, Specific Locality and Locality nickname, locality_id is an ephemeral field - they can literally change from minute to minute. I'd prefer not to encourage anyone to treat that like anything it can't be - maybe we just need some accompanying documentation??

**Comment by acdoll** [comment]
I think I'm following you @dustymc, but could you explain what you mean by 'priority' Locality_ID? Does that mean the Locality_ID that is associated with the most recent collecting event? The actual number of a Locality_ID for a specific place never changes, but the Locality_ID tied to a specimen may change as additional collecting events are added to a specimen record or if we just pick a new locality, correct? Is that what you mean by ephemeral? In that sense, the collection_event_ID is also ephemeral so the Results list is similarly displaying a 'priority' collecting_event_ID, right?

Having the option for 'priority' Locality_ID to display in the results list could be useful for data validation and cleanup activities. I believe what Phyllis is trying to do is generate a list of currently accepted Locality_ID's for a particular collector to facilitate the entry of new specimens and reduce the creation of unnecessary duplicate localities.

**Comment by dustymc** [comment]
> 'priority' Locality_ID

https://github.com/ArctosDB/DDL/blob/master/functions/getPrioritySpecimenEvent.sql

>The actual number of a Locality_ID for a specific place never changes

That is not correct. Identical localities are constantly merged, and mergers don't favor any particular ID. So "there" might be locality_id 1 today, 2 tomorrow, and 3 by next week.

Collecting_event_id works the same way.

Using those IDs for data entry is very likely to cause problems (eg, when they disappear between the time you enter data and load specimens). "Nickname" (locality or event) is a much better identifier for that purpose.

http://handbook.arctosdb.org/documentation/locality.html#maintenance
