### ISSUE TITLE
COLLECTING_SOURCE definition

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2077]
Maybe we should start with defining COLLECTING_SOURCE. I don't see a definition at http://handbook.arctosdb.org/documentation/specimen-event.html and this is probably why we are having so much trouble with it. 

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/arctos/issues/2075#issuecomment-491971269_

**Comment by Jegelewicz** [comment]
Here is my stab at it, at least in the way we seem to be using it.

COLLECTING_SOURCE = a broad description of where the specimen was collected meant to indicate relative research usefulness as opposed to locality

**Comment by dustymc** [comment]
A broad categorization of how the specimen came to be at the associated event. 

????????

**Comment by dustymc** [comment]
I updated http://handbook.arctosdb.org/documentation/specimen-event.html#collecting-source.
