### ISSUE TITLE
spatial browse: Google hates us part two

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#2081]
http://arctos.database.museum/spatialBrowse.cfm is old data, Fusion Tables is dead, and the API to use existing data in Fusion is being deprecated later this year.

Even with only 'preferred' event coordinates rounded to ~1KM precision, there are around 200K points involved. I think that's probably more than we can handle 'natively,' and it's much less precision than ideal.

The obvious more-or-less drop-in replacements that 5 minutes of Googling found cost $$.

The not-so-drop-in options likely require a significant amount of coding.

Does anyone use that thing, or should we just get rid of it?

If we should keep it, does anyone know of a suitable replacement?

@mkoo

**Comment by Jegelewicz** [comment]
I have no idea what you are talking about, so I probably don't use this?

**Comment by dustymc** [comment]
<img width="148" alt="Screen Shot 2019-05-15 at 10 48 52 AM" src="https://user-images.githubusercontent.com/5720791/57797338-0ee2e680-76ff-11e9-99b8-f9527b1f4885.png">

**Comment by Jegelewicz** [comment]
Nope, don't use it. Maybe it would do something cool for me, but I haven't explored it and as such, probably won't miss it. Let those who might weigh in!

**Comment by mkoo** [comment]
As Dusty knows, I love Spatial Browse! Let me think on that but for now
let's remove the link as Fusion Tables is dead now -- I think a combo of
preprocessed localities binned into some grid would work -- scraped from
the GBIF API? a combo of js and interactive map would get us a better
version than our BETA version, which needs to Rest in Peace.

thanks for bringing this up.

**Comment by mkoo** [comment]
Let's close this issue as functions specific to Spatial Browse is dead; we can open a new ticket or pin onto #2082 for a new interface of browsing georeferenced data.

**Comment by campmlc** [comment]
We should have a webinar/tutorial on "Cool things in Arctos that no one
knows about" for stuff like this.
