### ISSUE TITLE
TDWG Paleo GitHub

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2083]
@ArctosDB/paleontology 

Anyone interested in Paleo stuff have time to read through this? They are discussing much of what we are!

https://github.com/tdwg/paleo/issues

**Comment by Jegelewicz** [comment]
closing

**Comment by Jegelewicz** [comment]
@Nicole-Ridgwell-NMMNHS @aklompma you may want to follow that repo.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
done

**Comment by aklompma** [comment]
Thanks!
