### ISSUE TITLE
Dealing with uncertainty in relationships?

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#2085]
We have a few instances in which collectors lost track of who gave birth to who, but have some idea of the individuals that might be the parents.
i.e. what it looks like.
UTEP 9354 is offspring of either UTEP 9353 or UTEP 9352

My solution right now is to just put a remark under that offspring specimen clarifying the uncertainty, but creating offspring relationships with both potential parents. 

This is a problem though when I have a whole series belonging to one or another since there isn't a remarks section for bulkloading relationships?

**Comment by dustymc** [comment]
Neat!

I think your solution is as good as it gets without major surgery. Identifiers are "facts" - there's no opinion-component. Relationships are structurally extensions of identifications, but I can see how they could be less-factual.

I don't think I'm morally opposed to treating IDs (and relationships) more like Attributes, but I don't think it's trivial either.

Please feel free to help iron out and prioritize https://github.com/ArctosDB/arctos/issues/1938, and I can load remarks for you while that's in the works.

**Comment by mvzhuang** [comment]
ok thanks!

**Comment by campmlc** [comment]
Cool - so does this mean IDs and relationships will now have determined by and determined date ?
 treating IDs (and relationships) more like Attributes

**Comment by dustymc** [comment]
Could be - still major surgery, we should be pretty certain of what we're going to be whacking on and who might benefit from it before we dive in.

**Comment by campmlc** [comment]
I like that approach.

**Comment by campmlc** [comment]
That way we can record the mangled ID that person x submitted to GenBank on y date, making it searchable by the incorrect ID and helping resolve erroneous citations.

**Comment by dustymc** [comment]
>GenBank

I think those are (near) "facts" - it's the correct identifier or it ain't, and it's not too hard to tell those situations apart. It doesn't really matter **who** says that (for research - it might for things like deciding if your student gets to keep their powers). I'm not saying this wouldn't be useful there, but I'm not sure that's compelling enough to start cutting either. 

This would be useful for 

* THIS is probably THAT's parent, according to whoever didn't do a great job with the paperwork
* THIS is probably THAT's "organism," according to someone who's sorta-sure they're the actually same critter
* THIS is probably THAT's co-parasite, according to the potentially-wonky scripts which might have picked up on woopsy data 3 milliseconds before it was deleted
* potentially, THIS is reciprocal of THAT according to those same scripts, if ya'll would like to skip those notifications

It would be useful to sort organisms out before tackling this. I'm pretty focused on the idea that they're just more cataloged items, but there's some potential for the identifier itself to serve as the Organism data object, and if we're SURE that's what we want to do (I still don't think it is, but I might be convinced) then this would need to handle whatever's required there.

**Comment by campmlc** [comment]
Yes, so this "NK 12345"in Arctos is probably that "NK12345" at GBIF
which is supposedly AMNH:Mamm:678910.
In this case, the NK number, or the GBIF occurrence, are the best proxies
we have for organism, as inaccurate as that could potentially be. I think
the NK needs to be designated as the organism identifier, because that is
what ultimately will be traced back to specimen tags and field notes - not
the derivative assertions at GBIF or even AMNH.
We need to be able to designate any type of identifier - NK, AF, collector
number, zoo number - as the organism ID. If this is also treated as an
assertion, not a fact, then it can be open to interpretation and
correction, and documenting who and when said what and why.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/4101
