### ISSUE TITLE
Report Problems with a direct link to the DB contacts page

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2086]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I am trying to add citations, and Arctos is running extremely slowly.  

**To Reproduce**

**Expected behavior**

**Screenshots**

** Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
Issues are good for tracking, but https://arctosdb.org/arctos-down/ is the path to getting things fixed. (And are those current?)

**Comment by campmlc** [comment]
I'd like to request that we add a link to report slowdowns to the main
interface. Operators shouldn't have to go searching on arctosdb.org for how
to report.

**Comment by dustymc** [comment]
I suppose we could do that, but we don't have a CDN so it's going to be part of the thing that's not working - it won't be there when you really need it.

**Comment by campmlc** [comment]
Well, that makes sense if Arctos is totally down, but I still think a link
that would take you to the arctosdb.org page would be helpful.

**Comment by dustymc** [comment]
Its not just totally down.

Here's a contact message from yesterday.

<img width="920" alt="Screen Shot 2019-05-18 at 6 20 11 AM" src="https://user-images.githubusercontent.com/5720791/57970353-30c5ae80-7935-11e9-9ded-f3526ef9d3ca.png">

It took about 9 hours to find its way to my inbox. (MAYBE that's just my inbox, but I think everything gets plugged up.)

The 'About/Help' tab or 'About' or 'Help' and one more click from withing it gets you to https://arctosdb.org/. From there, it's...

<img width="262" alt="Screen Shot 2019-05-18 at 6 23 42 AM" src="https://user-images.githubusercontent.com/5720791/57970381-87cb8380-7935-11e9-8e2b-a8a54cbc03e1.png">

I'm not sure that can be made much better without fundamental changes in how things work?

**Comment by campmlc** [comment]
Just add a tab in the operator menu that says Report Problems with a direct
link to the DB contacts page. I have to guess where to go, and and I'm
certain it's worse for others. Make it explicit and obvious. Interface
issue only.

**Comment by dustymc** [comment]
Added a link to the [contact issue template](https://github.com/ArctosDB/arctos/issues/new?assignees=&labels=contact&template=contact-arctos.md&title=%5BCONTACT%5D).
