### ISSUE TITLE
locality services

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#2092]
@mkoo lets get this public.

Here's how Locality Services work. You will need to be logged in to Arctos with manage_locality access to open all of the links.

I think 3 major points:

* are we syncing stuff too often? That is most of the API usage. 
* should we be doing more with the data from the services?
* this needs documentation

Example locality: http://arctos.database.museum/editLocality.cfm?locality_id=10195166

Webservice-stuff is in the gray box off to the right.

<img width="462" alt="Screen Shot 2019-05-20 at 3 54 26 PM(1)" src="https://user-images.githubusercontent.com/5720791/58189061-9932c980-7c6e-11e9-9c66-2104eab92cff.png">

Clicking the Pull/Debug link will run the service call function in verbose debug mode.

http://arctos.database.museum/component/functions.cfc?method=getLocalityCacheStuff&locality_id=10195166&debug=true

The service does this:

* try to grab coordinates from geolocate using various geography components and spec_locality. geoLocate is very good at this __IF__ given something it can understand, and usually just fails when fed garbage.
* if fail, grab coordinates from google using various geography components and spec_locality. Google is sort of hit-or-miss - pretty good given "urban" data, not so much with lots of the stuff we record - and usually returns SOMETHING, even if it's crazy.
* stuff coordinates into S$DEC_LAT,S$DEC_LONG
* grab elevation for user-assigned coordinates from Google
* If fail, grab elevation for service-derived coordinates from Google 
* grab place-name data for service-derived coordinates
* grab place-name data for curator-supplied coordinates

Elevation goes in the gray box, it's there if you want to copy it into the record.

You can click the link to use Google's coordinates, and there a diff(km) value so you can tell if your georeference is a mess (or Google's is, which isn't uncommon).

<img width="377" alt="Screen Shot 2019-05-20 at 4 05 18 PM(1)" src="https://user-images.githubusercontent.com/5720791/58189368-3a218480-7c6f-11e9-9f3c-98db938a51d5.png">

does some stuff with elevation (and the rest of this) too.

The place-name data gets distinct-term coalesced and stuffed into S$GEOGRAPHY for "any geog" to use.

That's about it, I think. It would be super-easy to eg, stuff some "curatorial" coordinates in when a locality without them is created. That would get...

UAM@ARCTOS> select count(*) from locality;

  COUNT(*)
----------
    556729

1 row selected.

Elapsed: 00:00:00.34
UAM@ARCTOS> select count(*) from locality where dec_lat is null;

  COUNT(*)
----------
    142807

...another 140K dots on the map and specimens in front of users. Some of them would be ugly and probably make people twitchy, but it's still technically trivial. I would personally take obviously wrong and easy to find over a complete lack of quantifiable data any day, but that's just me.

The service refreshes data when edit locality is opened, and every 6 months if nothing else triggers the call. I'm not sure how that syncs up with changes in google's data but they do change fairly often.

Here's what's stored for the example above.
```
UAM@ARCTOS> select * from locality where locality_id=10195166;

LOCALITY_ID GEOG_AUTH_REC_ID
----------- ----------------
SPEC_LOCALITY
------------------------------------------------------------------------------------------------------------------------
   DEC_LAT   DEC_LONG MINIMUM_ELEVATION MAXIMUM_ELEVATION
---------- ---------- ----------------- -----------------
ORIG_ELEV_UNITS                                         MIN_DEPTH  MAX_DEPTH
------------------------------------------------------------------------------------------ ---------- ----------
DEPTH_UNITS                                           MAX_ERROR_DISTANCE
------------------------------------------------------------------------------------------ ------------------
MAX_ERROR_UNITS
------------------------------------------------------------------------------------------
DATUM
------------------------------------------------------------------------------------------------------------------------
LOCALITY_REMARKS
------------------------------------------------------------------------------------------------------------------------
GEOREFERENCE_SOURCE
------------------------------------------------------------------------------------------------------------------------
GEOREFERENCE_PROTOCOL
------------------------------------------------------------------------------------------------------------------------
LOCALITY_NAME
------------------------------------------------------------------------------------------------------------------------
S$ELEVATION
-----------
S$GEOGRAPHY
------------------------------------------------------------------------------------------------------------------------
 S$DEC_LAT S$DEC_LONG S$LASTDATE WKT_POLYGON
---------- ---------- ---------- --------------------------------------------------------------------------------
LAST_DUP_C
----------
   10195166        4891
El Rosario area
 22.993252 -105.85863             55            55
ft
                                                     3036
m
World Geodetic System 1984

GeoLocate
GeoLocate

     17
Sinaloa El Dorado-El Tule,Sin.,Mexico,MX,Culiacán
 24.255556 -107.18278 2019-05-20
2019-05-10

```

**Comment by mkoo** [comment]
Thanks, D
I think this is too much on an auto- trigger basis. Should be on a
user-initiated basis, then with the option to push to input fields for
saving as values (similar to Geolocate's push function to load values to
save). For example, I assume that every 6-mo refresh does NOT happen wtih
locked localities? Also, I am not sure we need to redo every 6 mos if no
one has had time to vet and validate.

I would prefer to see this as an option to google geocode on batchloaded
accessions then let curators sort through the mapped coordinates, because
that's when they will be able to validate not on the 140k old stuff.

A couple of reasons to make users click on something-- users will then be
aware of value of these services and can apply as appropriate.
Second, will limit the geocoding and elevation api traffic which is now 28
times more than our visualization traffic (dynamic and static maps
combined). I know those will fluctuate but getting a bit of control on
those will help us scale up as we add more localities, collections etc.
Otherwise I will spend a lot of time making credit requests when I could be
doing other geography issues!

just some quick thoughts-- open to further discussion at next AWG meeting!

**Comment by dustymc** [comment]
The service is now disabled.

>locked localities?

Yes, it runs on locked localities - the service data is completely segregated from "real" data so it doesn't make "changes," and it's pretty easy to find a verified and locked locality with nonsensical data; they need help too.

>user-initiated 

A big part of this is to help users find specimens when operators haven't done a very good job of recording "curatorial data." I'd guess that 90% of text-based geography queries don't find everything a user is looking for because even our higher-level (eg, geography) data are so incredibly inconsistent (and inconsistently applied to specimens). Try it - draw a box most anywhere on the map and see how many ways we say the same thing! The services get some of that back, although geolocate can provide some of that functionality. (But see https://github.com/ArctosDB/arctos/issues/2084#issuecomment-494894953 - GL is great when it understands, but it's also easily confused.) Running the pull on demand would completely lose that functionality.

A by-request approach would also completely disable the georeference report - at least @dperriguey uses it, I'm not sure how, maybe the service-data could be removed?

SOMEONE asked for elevation, I'm not sure who and I don't do anything with it, maybe it's an easy (and I think fairly expensive??) thing to get rid of.

I can drop one of the reverse georeference calls without giving up TOO much - that would very roughly halve the number of calls and sorta-usually gets about the same result, I think. 

This stuff all seems like a fairly critical component of what separates Arctos from the rest of the crowd to me, and giving any of it up seems like a major step away from being connected to everything else on the Internet. That said, if we can't afford it then we can't afford it.

Yes I think let's put this at the top of the AWG agenda.

**Comment by mkoo** [comment]
a little more context from the api dashboard so the curious can see what I
mean by heavy traffic on the service calls (just the last 2 days since we
started making geocoding automatic):

Bottom line: we need to request a lot more service credit so we can
continue to do this at this rate. (so far we (me) have not been
anticipating our needs very well at all! so we need to understand what we
need and what we get, and thus what we need to request.
[image: screenshot-console.cloud.google.com-2019.05.22-15-41-19.png]

**Comment by campmlc** [comment]
This sounds reasonable.

**Comment by dustymc** [comment]
This has caught up, so things should be relatively calm for a while. The refresh is set to yearly, so if nothing else changes there will be a big pull from these same localities in about a year, and eg, bringing a new collection with lots of new localities in could cause a surge, albeit probably a minor one unless it's a very large collection. I will try to tweak the refresh rate to smooth that out as much as possible, and will continue to look for alternative services. 

Both geolocate and google are pretty horrible for oceanic data - anyone know of anything that'll put coordinates to marine descriptors and vice-versa?
