### ISSUE TITLE
Counts differ between Arctos and CrossRef

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2093]
Info per Arctos:
![image](https://user-images.githubusercontent.com/5725767/58257130-87fcc200-7d2d-11e9-8c7f-456f0e5aa961.png)

Info per CrossRef:
![image](https://user-images.githubusercontent.com/5725767/58257188-ae226200-7d2d-11e9-803b-2ab03cd2aa09.png)

Any idea why the difference?

**Comment by dustymc** [comment]
Probably lag time in the cache.

<img width="505" alt="Screen Shot 2019-05-23 at 7 04 59 AM" src="https://user-images.githubusercontent.com/5720791/58259308-1fabe180-7d29-11e9-8ef0-49d318a2d427.png">
