### ISSUE TITLE
Need mapping of GeologicalContext from Arctos to other publishers

### ISSUE THREAD

**Issue by dperriguey** [ArctosDB/arctos#2094]
I was made aware that our mapping was not done correctly for basis of record and missing for geological context in iDigBio. The basis of record was Preserved Specimen when it should have been Fossil Specimen. This was taken care of, just wanted to make the note for other earth science/paleo/archaeo collections. 

The problem that needs work is mapping our geological attributes to iDigBio/GBIF geological context. Our method for mapping looks correct, but it is not showing up on the other end correctly.

Let me know if I need to give more information or if I even posted this in the correct place.

**Comment by Jegelewicz** [comment]
> The basis of record was Preserved Specimen when it should have been Fossil Specimen. 

Also see https://github.com/ArctosDB/arctos/issues/2075#issuecomment-491976353

**Comment by dustymc** [comment]
It's not that our mapping is incorrect, it's that it does not exist.

DWC fields are this:

https://terms.tdwg.org/wiki/Darwin_Core_GeologicalContext

By concept name: dwc:bed • dwc:earliestAgeOrLowestStage • dwc:earliestEonOrLowestEonothem • dwc:earliestEpochOrLowestSeries • dwc:earliestEraOrLowestErathem • dwc:earliestPeriodOrLowestSystem • dwc:formation • dwc:geologicalContextID • dwc:group • dwc:highestBiostratigraphicZone • dwc:latestAgeOrHighestStage • dwc:latestEonOrHighestEonothem • dwc:latestEpochOrHighestSeries • dwc:latestEraOrHighestErathem • dwc:latestPeriodOrHighestSystem • dwc:lithostratigraphicTerms • dwc:lowestBiostratigraphicZone • dwc:member

Arctos "fields" are

```
UAM@ARCTOS> select distinct GEOLOGY_ATTRIBUTE from CTGEOLOGY_ATTRIBUTE order by GEOLOGY_ATTRIBUTE;

GEOLOGY_ATTRIBUTE
------------------------------------------------------------------------------------------------------------------------
Eon/Eonothem
Erathem/Era
Series/Epoch
Stage/Age
System/Period
bed
block
field
formation
group
member
suite
unspecified

13 rows selected.

```

The authority is hierarchical, so we can also pull "parentage" for terms which are in a hierarchy - https://arctos.database.museum/info/ctDocumentation.cfm?table=CTGEOLOGY_ATTRIBUTE

Any locality can carry any number of geology attributes.

How should I transform Arctos data into something suitable for DWC?

http://arctos.database.museum/guid/UAM:ES:38746 is an example of a specimen with geology.

And can we get rid of "unspecified"?!

**Comment by dperriguey** [comment]
I'm not sure what unspecified is. It's not useful. If you don't specify (i.e. don't assign a geology attribute to it) then it is unspecified. 

It seems that the structure is to bracket for level of uncertainties. Looks like there are two methods: default for using dwc:earliest(chronoterm), or putting both in e.g. dwc:earliestEraOrLowestErathem=Mesozoic dwc:latestEraOrHighestErathem=Mesozoic.

less redundant method:
https://www.idigbio.org/portal/records/5c2dffb0-f6e4-4b9e-b4ab-1f14ad84c449
![image](https://user-images.githubusercontent.com/32556913/58269742-6dcede00-7d45-11e9-9437-a0f3e0e83a73.png)

more redundant method:
https://www.idigbio.org/portal/records/66487417-aff4-4bc3-9527-507329c17652
![image](https://user-images.githubusercontent.com/32556913/58269823-9060f700-7d45-11e9-8ecd-318de4ed02a5.png)

I'm comfortable with the less redundant method. All our lithostratigraphy should be easy. All the group, formation, member, bed terms are the same. Call everything else might fit into dwc:lithostratigraphicTerms. Probably a good thing that we control the vocabulary to have the lithostratigraphic term along side the attribute (e.g. Kakertok Suite).  

Our group will have biostratigraphic terms that would be great to have in our hierarchy (dwc:lowest/highestBiostratigraphicZone) too.

**Comment by dustymc** [comment]
https://arctos.database.museum/guid/UNM:ES:10288

How would that map? I don't see anything in our data that would lead me to eg, Albian being either earliestAgeOrLowestStage or latestAgeOrHighestStage and Cenomanian being presumably the other - they are at the same relative position in the hierarchy. (I think it's in the parent term, but I'm not sure how I could write code to that??)

What if there were 30 more Stage/Age determinations? https://arctos.database.museum/guid/UAM:ES:38714 has multiple formation data - can I concatenate them using some separator, or ???

What if they were all the same - eg, 30 people looked at the specimen and all agree "X"? Should I somehow repeat X 30 times in a probably-futile attempt to express certainty in a model which doesn't allow for uncertainty, of can I just deal with DISTINCT(term, value) for this? 

I need answers that I can write code to using only the data I can access from Arctos. Hopefully this is all blindingly obvious to ya'll, but it's not for me so maybe type slowly and use small words....

@dbloom assuming we eventually figure out the details, how should this be structured - more columns in the flattened view, another 'table' with OccurrenceID as fkey, ???

**Comment by dustymc** [comment]
"unspecified" is used for https://arctos.database.museum/guid/UNM:ES:5884


unspecified | Main Street Limestone | https://macrostrat.org/sift/#/strat_name_concept/9156 | 5340202 | 1 | unspecified | Main Street Limestone | https://macrostrat.org/sift/#/strat_name_concept/9156 |   | 1 | JEGELEWICZ | 2019-02-04 07:14:17.0
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --



@Jegelewicz ??

**Comment by dperriguey** [comment]
I say we just keep it simple. Make our own protocol for dealing with the weirdness of Darwin Core. That's why I'm saying use the less redundant method and just use earliest. 

I don't know what to do with the multiple formations. If the data are that uncertain (that someone pulled a fossil out and just said, "well maybe it came from one of these two formations"...the Poul Creek Formation is about 1600m thick the Yakataga Formation is at least 4000m thick. It's pretty hard to mess that up unless you're at a boundary between formations, but even then you have to make a decision and then make the notes. Boundaries are not always easy to find, so especially if its found somewhere in between it needs to be noted as such) then that needs to go into notes and not hard data like our hierarchy. That record even says "Sample collected from Yakataga Reef. Exact locality not recorded. Note: Additional information in museum files." Really there is no ambiguity in that. If it came from the Yakataga Reef, it came from the Yakataga Formation as per multiple, good resources (https://ngmdb.usgs.gov/Geolex/UnitRefs/YakatagaRefs_12311.html).  

"unspecified" 
That record should be Main Street Limestone Formation (child) of the Washita Group (parent)

**Comment by dustymc** [comment]
> multiple formations

I don't think that can come only from uncertainty - maybe the name changed, a feature was split or adjusted, there are 20 specimens and 20 sources of data all sharing an identifier, ... We (and DWC) have invested a lot of unnecessary work if this is really all unambiguous and static. If we truly don't need that complexity then let's get rid of it.

> just use earliest.

Given Albian and  Cenomanian on a locality, send out 
``earliestAgeOrLowestStage="Albian; Cenomanian"``
??

**Comment by dperriguey** [comment]
multiple formations
Don't need the complexity.  

just use earliest
good point, maybe we can still use both but default to earliest if simple. I have no idea how you map that. We would have to designate what is earliest or latest on our collections end right or can that be in the code? If we can easily search for multiple designations (two chronostratigraphic attributes), then we could clean that up in a sort of less time consuming way. If DWC had earliest and latest formation, we could do the same with the lithostratigraphy. If you have the lithostratigraphy in chronological order we could map that, or can you have multiple dwc:formation?

**Comment by dustymc** [comment]
>Don't need the complexity.

@tucotuco do you happen to know the history leading to DWC having the earliest/latest thing? I think I'm hearing that that doesn't make sense.

>If you have the lithostratigraphy in chronological order 

That is explicitly what we removed when the chrono and litho data were separated!?

>earliest or latest on our collections end right or can that be in the code

Well I'm less and less certain that I understand these particular data, but if "Mesozoic" means something in one collection (or when attached to one specimen, or as asserted by some agent, or...) and something else in some other context then the only place to express that is in the data itself (and we probably need to stop pretending that ambiguous terms can be authoritative), and if it means something that can be universally defined then good database design demands we do so in the authority.

**Comment by dperriguey** [comment]
Don't need the complexity.
It makes sense in the context of uncertainty. You gave a perfect example. Our data associated with a particular formation without someone being specific about the chronostratigraphy gives us the ability to say, "because this formation spans the Albian to the Cenomanian, we can say this fossil specimen can be narrowed down to have come from this same age interval". We may just need to throw out that method but as you mentioned there are data that span multiple formations. All meaning the complexity may be necessary. 

If you have the lithostratigraphy in chronological order
They can be separated but also put into some chronological order. My thought was that it would help with the mapping. If formation B is older and formation A is younger, can your code distinguish between those. Older and younger being actual time (e.g. 83.6+/-0.2 - 72.1+/-0.2; all available through Macrostrat and the International Chronostratigraphic Chart. 

we probably need to stop pretending that ambiguous terms can be authoritative
If someone says Mesozoic, it means Mesozoic. If someone says Mesozoic through the Cenozoic, it means Mesozoic through the Cenozoic. I just wish DWC had earliest/latest/exactly. My point was again just about uncertainty you pointed out with our lithostratigraphy. Some rock spans the Albian through the Cenomainian. If we have a better way to deal with the uncertainty, I'm all for it.  That is, if a record is specific about Chronostratigraphy to the level of e.g. Late Cretaceous, then it should only be recorded as such in Arctos. 
In this scenario: https://arctos.database.museum/guid/UAM:ES:38714 should only be Cenozoic. 
In this scenario: http://arctos.database.museum/guid/UNM:ES:15572 should only be Upper Cretaceous.
Add notes if whoever is putting in the data really wants to get specific about uncertainties.  
If the data was originally recorded with the uncertainties, the person putting in the data can reduce to the least ambiguous chronostratigraphic term. 
The Chronostratigraphy is not ambiguous (however, it changes every new release of the Chronostratigraphic chart=less uncertainty), but lithostratigraphy is very ambiguous. Lithostratigraphy spans different time depending on where you are in geographic space.

**Comment by dustymc** [comment]
Thanks, I think that helps. We (and DWC) do need the uncertainty - correct?

>I just wish DWC had....

There is, or was, a process for that.

> can your code distinguish between...all available through Macrostrat and the International Chronostratigraphic Chart.

If I can get those data from an external source, there's no need to replicate that. That comes back to https://github.com/ArctosDB/arctos/issues/1642 - I'm still not sure what you're trying to DO, what data we read directly from stuff in the collection and what's just derived from that, etc.

I threw something together that might satisfy our immediate needs.

https://github.com/ArctosDB/DDL/blob/master/functions/getGeologyForDWC.sql

```
create table temp_g_d as
select
  concatGeologyAttribute(collection_object_id) concatsrt,
  guid,
  getGeologyForDWC(collection_object_id,'Erathem/Era') as earliestEraOrLowestErathem,
  getGeologyForDWC(collection_object_id,'Eon/Eonothem') as earliestEonOrLowestEonothem,
  getGeologyForDWC(collection_object_id,'Series/Epoch') as earliestEpochOrLowestSeries,
  getGeologyForDWC(collection_object_id,'Stage/Age') as earliestAgeOrLowestStage,
  getGeologyForDWC(collection_object_id,'System/Period') as earliestPeriodOrLowestSystem,
  getGeologyForDWC(collection_object_id,'formation') as formation,
  getGeologyForDWC(collection_object_id,'group') as geo_group,
  getGeologyForDWC(collection_object_id,'member') as member
from
  flat 
where 
  guid in (
    'UAM:ES:38714',
    'UNM:ES:15572',
    'UAM:ES:38746',
    'UNM:ES:10288',
    'UNM:ES:5884'
  )
;

```
[temp_g_d.csv.zip](https://github.com/ArctosDB/arctos/files/3214243/temp_g_d.csv.zip)

* Does that melt DWC?
* Is that close enough to what we want to share for now?

**Comment by dperriguey** [comment]
We (and DWC) do need the uncertainty. How to relate those to our unspecified uncertainties, I don't know. If we had them specified, I think we could use the DWC more efficiently. 

I'm guessing the Macrostrat API will be able to help us with the lithostratigraphy (but we had problems with that before and I don't know what to do). I'll go back and comment at #1642 later to be more specific about my ideas. 

threw something together
That LOOKS fine to me. But will it break when we have multiple formations and chronostrat stuff when it gets pulled into iDigBio? I would really prefer it if the code is set up to be less specific (i.e. not earliest or latest). What is or was the DWC process? For immediate needs, it looks fine to me. It's not as correct as I/someone downloading from iDigPaleo wants it, but if it gets the data in great.

**Comment by Jegelewicz** [comment]
Main Street Limestone should be a formation, not sure what happened there...I can't change it because it is being used - guessing @dustymc can. Should be:

Main Street Limestone Formation (formation)

**Comment by Jegelewicz** [comment]
>    If you have the lithostratigraphy in chronological order
> 
> That is explicitly what we removed when the chrono and litho data were separated!?

Because litho ARE NOT chronological.

> The Chronostratigraphy is not ambiguous (however, it changes every new release of the Chronostratigraphic chart=less uncertainty), but lithostratigraphy is very ambiguous. Lithostratigraphy spans different time depending on where you are in geographic space.

**Comment by Jegelewicz** [comment]
See also https://github.com/tdwg/dwc-qa/issues/136 ?

**Comment by dperriguey** [comment]
Lithostratigraphy
Each lithological unit spans some amount of time see macrostrat.org and search any name (say Main Street https://macrostrat.org/sift/#/strat_name_concept/9156).
![image](https://user-images.githubusercontent.com/32556913/58341882-86ee9200-7e0c-11e9-8903-ae6dfd468950.png)

Litho, chrono, chemo, and biostratigraphy (as well as others) all have a primary focus in geochronology. As geologists, we are usually concerned with when something happened. You cannot mix your different stratigraphies in a weird hierarchy saying the rock unit spans exactly all of the Albian and all through the Cenomanian (you only can in a relative sense). Lets discus this more in #1642. 

My idea was to help Dusty with the code for determining earliest and latest in a litho sense but that's not even available in DWC. It seems to complicated to explain my idea in Github though. Maybe a Skypeing might help. Regardless, I think what Dusty's come up with might work for now. I just need to see how it looks on the other end in iDigBio. Will it look just like your zip file @dustymc?

**Comment by dustymc** [comment]
IDK that (and if it'll melt DWC) is a question for @dbloom. I _think_ it will be more columns on the big flat view.

**Comment by dustymc** [comment]
Main Street Limestone Formation (formation) should be happy now - thanks!

**Comment by dperriguey** [comment]
Does it take a while for it to show up in the geology attribute code table?

**Comment by Jegelewicz** [comment]
It's in there:
![image](https://user-images.githubusercontent.com/5725767/58387402-248fc000-7fcb-11e9-851a-af9b13655fbb.png)

**Comment by dperriguey** [comment]
I just noticed that it wasn't in there verbatim as Dusty stated in the comment above. 

@dbloom How is it looking for this? Do you know if Dusty's basic format above will look the same in iDigBio or if it will "melt" DWC?

**Comment by dustymc** [comment]
>verbatim

I know this has come up before, but can we standardize on either always including the "rank" ("Main Street Limestone Formation") or never doing so ("Main Street Limestone")? Along with being less confusing locally, I think that's going to be absolutely necessary if we ever want to plug in to a service.

We have no control over iDigBio. "Is this suitable for DWC?" is really as far as we can go with that.

**Comment by dperriguey** [comment]
I understand the point of standardizing. At least there is perhaps a reason of distinguishing between Main Street Formation and Main Street Limestone formation given their geography and named history:
https://ngmdb.usgs.gov/Geolex/Units/MainStreet_9156.html
https://macrostrat.org/sift/#/strat_name/71995
![image](https://user-images.githubusercontent.com/32556913/58649398-4473fc00-82c9-11e9-82b3-4ddb651a7418.png)

If we standardize it makes it clean. However, all the old data is not clean like this and we are then renaming the data. And honestly it's not wrong. The Main Street Limestone is a formation. It's not in the literature with the name "Formation" https://ngmdb.usgs.gov/Geolex/UnitRefs/MainStreetRefs_9156.html
But I'm totally ok with standardizing. What is the advantage of standardizing by rank? By plug into a service do you mean like Macrostrat?

> no control
So do we just wait and see after the next pull of data from iDigBio and GBIF?

**Comment by dustymc** [comment]
I need to hear back from @dbloom before I can send geology data out with the DWC.

**Comment by Jegelewicz** [comment]
He was traveling today - it might be next week before he gets to this....

**Comment by dperriguey** [comment]
Ok, thanks, good to know

**Comment by dustymc** [comment]
From tuco:

- this won't melt DWC
- add columns, do it at any time

Future consideration: Should we do something different for collections that don't have geology data?

**Comment by dustymc** [comment]
New IPT view with live geology data:

```

UAM@ARCTOS> desc digir_query.ipt_view;
 Name								   Null?    Type
 ----------------------------------------------------------------- -------- --------------------------------------------
 COLLECTION_ID							   NOT NULL NUMBER
 LANGUAGE								    CHAR(2)
 RIGHTS 								    VARCHAR2(4000)
 TYPE									    VARCHAR2(20)
 BASISOFRECORD								    VARCHAR2(20)
 COLLECTIONCODE 							    VARCHAR2(5)
 RECORDEDBY								    VARCHAR2(4000)
 INFORMATIONWITHHELD							    VARCHAR2(4000)
 INDIVIDUALCOUNT							    NUMBER
 INSTITUTIONCODE							    VARCHAR2(20)
 MODIFIED								    DATE
 ASSOCIATEDOCCURRENCES							    VARCHAR2(4000)
 REFERENCES								    VARCHAR2(102)
 OCCURRENCEREMARKS							    VARCHAR2(4000)
 TYPESTATUS								    VARCHAR2(4000)
 ASSOCIATEDTAXA 							    VARCHAR2(4000)
 OTHERCATALOGNUMBERS							    VARCHAR2(4000)
 INDIVIDUALID								    VARCHAR2(102)
 CATALOGNUMBER								    VARCHAR2(67)
 ASSOCIATEDSEQUENCES							    VARCHAR2(4000)
 RECORDNUMBER								    VARCHAR2(4000)
 FIELDNUMBER								    VARCHAR2(4000)
 SEX									    VARCHAR2(4000)
 LIFESTAGE								    VARCHAR2(4000)
 DYNAMICPROPERTIES							    VARCHAR2(4000)
 IDENTIFICATIONREMARKS							    VARCHAR2(4000)
 FAMILY 								    VARCHAR2(4000)
 HIGHERCLASSIFICATION							    VARCHAR2(4000)
 GENUS									    VARCHAR2(4000)
 IDENTIFICATIONREFERENCES						    VARCHAR2(255)
 IDENTIFICATIONQUALIFIER						    VARCHAR2(25)
 IDENTIFIEDBY								    VARCHAR2(4000)
 TAXONRANK								    VARCHAR2(255)
 KINGDOM								    VARCHAR2(4000)
 DATEIDENTIFIED 							    VARCHAR2(22)
 IDVERIFICATIONSTATUS							    VARCHAR2(255)
 NOMENCLATURALCODE							    VARCHAR2(4000)
 PREPARATIONS								    VARCHAR2(4000)
 PCLASS 								    VARCHAR2(4000)
 PORDER 								    VARCHAR2(4000)
 PHYLUM 								    VARCHAR2(4000)
 SCIENTIFICNAME 							    VARCHAR2(255)
 SPECIFICEPITHET							    VARCHAR2(4000)
 INFRASPECIFICEPITHET							    VARCHAR2(4000)
 PREVIOUSIDENTIFICATIONS						    VARCHAR2(4000)
 ASSOCIATEDMEDIA							    VARCHAR2(121)
 OCCURRENCEID								    VARCHAR2(130)
 SPECIMENEVENTTYPE							    VARCHAR2(60)
 SAMPLINGPROTOCOL							    VARCHAR2(4000)
 ESTABLISHMENTMEANS							    VARCHAR2(60)
 LOCATIONACCORDINGTO							    VARCHAR2(4000)
 GEOREFERENCEDBY							    VARCHAR2(4000)
 GEOREFERENCEDDATE							    DATE
 HABITAT								    VARCHAR2(4000)
 GEOREFERENCEVERIFICATIONSTATUS 					    VARCHAR2(60)
 EVENTREMARKS								    VARCHAR2(4000)
 GEODETICDATUM								    VARCHAR2(55)
 VERBATIMEVENTDATE							    VARCHAR2(60)
 VERBATIMLOCALITY							    VARCHAR2(4000)
 VERBATIMCOORDINATESYSTEM						    VARCHAR2(20)
 EVENTDATE								    VARCHAR2(88)
 EVENTTIME								    VARCHAR2(45)
 DAY									    VARCHAR2(8)
 MONTH									    VARCHAR2(8)
 YEAR									    VARCHAR2(16)
 ENDDAYOFYEAR								    NUMBER
 VERBATIMCOORDINATES							    VARCHAR2(255)
 COORDINATEUNCERTAINTYINMETERS						    NUMBER
 DECIMALLATITUDE							    NUMBER
 DECIMALLONGITUDE							    NUMBER
 LOCALITY								    VARCHAR2(255)
 GEOREFERENCEPROTOCOL							    VARCHAR2(255)
 GEOREFERENCESOURCES							    VARCHAR2(4000)
 MINIMUMDEPTHINMETERS							    NUMBER
 MAXIMUMDEPTHINMETERS							    NUMBER
 MINIMUMELEVATIONINMETERS						    NUMBER
 MAXIMUMELEVATIONINMETERS						    NUMBER
 LOCATIONREMARKS							    VARCHAR2(4000)
 CONTINENT								    VARCHAR2(50)
 COUNTRY								    VARCHAR2(50)
 COUNTY 								    VARCHAR2(50)
 ISLAND 								    VARCHAR2(50)
 ISLANDGROUP								    VARCHAR2(50)
 QUAD									    VARCHAR2(30)
 WATERBODY								    VARCHAR2(50)
 FEATURE								    VARCHAR2(50)
 STATEPROVINCE								    VARCHAR2(75)
 HIGHERGEOGRAPHY							    VARCHAR2(255)
 INSTITUTION								    VARCHAR2(60)
 COLLECTION								    VARCHAR2(50)
 EARLIESTERAORLOWESTERATHEM						    VARCHAR2(4000)
 EARLIESTEONORLOWESTEONOTHEM						    VARCHAR2(4000)
 EARLIESTEPOCHORLOWESTSERIES						    VARCHAR2(4000)
 EARLIESTAGEORLOWESTSTAGE						    VARCHAR2(4000)
 EARLIESTPERIODORLOWESTSYSTEM						    VARCHAR2(4000)
 FORMATION								    VARCHAR2(4000)
 GEO_GROUP								    VARCHAR2(4000)
 MEMBER 								    VARCHAR2(4000)
 OCCURRENCEID2								    VARCHAR2(148)

```

**Comment by dperriguey** [comment]
Update

Things look like they mapped correctly! Thank you Dusty for getting mapping things out! Thanks everyone for their input. I'm really stoked about how good things look so far. Really appreciate the help!

Examples:
Below are a couple records. I noticed an error with one of these.

Regular/less weird record:
Looks great, but the Cretaceous is System/Period not Erathem/Era
http://arctos.database.museum/guid/UNM:ES:15635
https://www.idigbio.org/portal/records/a13c1d88-730b-4245-ac96-767b98aed48c
![image](https://user-images.githubusercontent.com/32556913/61392901-219fa600-a87d-11e9-83e7-9380a1e7f6ee.png)


Irregular record:
Looks great. The poorly determined formation seemed to map correctly with the appropriate Event Remark at the bottom clarifying the determination. 
http://arctos.database.museum/guid/UNM:ES:15633
https://www.idigbio.org/portal/records/0ec77035-6b3a-4561-9933-906f70c07b89
![image](https://user-images.githubusercontent.com/32556913/61393261-d89c2180-a87d-11e9-87c8-455c37199073.png)

I should probably make sure that there are not more issues. I'm currently hard copying our data and refining localities. Whenever I encounter a strange record or one with geological information I haven't seen in iDigBio yet, I'll make note of it here.

**Comment by dustymc** [comment]
>Cretaceous is System/Period not Erathem/Era

Here's what we're sending out.

```

select
  'earliestEraOrLowestErathem: ' || earliestEraOrLowestErathem,
  'earliestPeriodOrLowestSystem: ' || earliestPeriodOrLowestSystem
from
digir_query.ipt_view_too
where
"dcterms:references"='http://arctos.database.museum/guid/UNM:ES:15635'
  8  ;

'EARLIESTERAORLOWESTERATHEM:'||EARLIESTERAORLOWESTERATHEM
------------------------------------------------------------------------------------------------------------------------
'EARLIESTPERIODORLOWESTSYSTEM:'||EARLIESTPERIODORLOWESTSYSTEM
------------------------------------------------------------------------------------------------------------------------
earliestEraOrLowestErathem:
earliestPeriodOrLowestSystem: Cretaceous


1 row selected.
```

**Comment by dperriguey** [comment]
Is that the fix? Or is that what you've mapped and its not being ingested by iDigBio correctly?

**Comment by dustymc** [comment]
That's what's in Arctos right now. I suppose there's some chance I fixed something since the last export, but I don't think so. VertNet is the next logical place to check. http://ipt.vertnet.org:8080/ipt/resource?r=unm_es

So this is either something I've recently fixed or the fault of @tucotuco.

**Comment by tucotuco** [comment]
I don't understand. Can you give me an example of what you see versus what you expect, then I can track it down. To me everything looks as it should following the last publication a couple of weeks ago.

**Comment by dperriguey** [comment]
Regular/less weird record:
Looks great, but the Cretaceous is System/Period not Erathem/Era
http://arctos.database.museum/guid/UNM:ES:15635
https://www.idigbio.org/portal/records/a13c1d88-730b-4245-ac96-767b98aed48c
image

Irregular record:
Looks great. The poorly determined formation seemed to map correctly with the appropriate Event Remark at the bottom clarifying the determination.
http://arctos.database.museum/guid/UNM:ES:15633
https://www.idigbio.org/portal/records/0ec77035-6b3a-4561-9933-906f70c07b89
image

Both of these say Earliest Era or Lowest Erathem - Cretaceous
They need to say Earliest Period or Lowest System - Cretaceous 

Dusty's point above is that he has mapped them as Earliest Period or Lowest System, meaning the switch seems to have happened outside of Arctos.

**Comment by tucotuco** [comment]
OK, Perfect. Yes. There were three mis-mapped fields in the IPT. I have
just corrected those and republished the resource. I don't know how long it
will take for iDigBio to renew that. For GBIF it takes about 15 minutes
usually.

Good eye.

**Comment by dperriguey** [comment]
@tucotuco 
It looks like they mapped correctly in GBIF. Just one point of nuance I guess; Earliest period or lowest system should be above Earliest epoch or lowest series, and Group should be above Formation when displayed. This is hierarchical, just like Linnaean hierarchy.

**Comment by tucotuco** [comment]
The sensible ordering would be a nice improvement. It is curious that no
one has told GBIF this before. I recommend sending them feedback from the
GBIF portal on a page where the issue is apparent.

**Comment by dperriguey** [comment]
Ok, great! Thanks @tucotuco
