### ISSUE TITLE
Is Gulf of Mexico a drainage?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2096]
Doing other stuff and came across this:

![image](https://user-images.githubusercontent.com/5725767/58339329-936fec00-7e06-11e9-883c-95c2d5113d9e.png)

Pretty sure Gulf of Mexico isn't a drainage?

See https://en.wikipedia.org/wiki/Drainage_system_(geomorphology)

**Comment by dustymc** [comment]
Yes - https://www.epa.gov/gulfofmexico - but the drainage and the "sea" are (I think!) mutually exclusive.

Specimens are http://arctos.database.museum/SpecimenResults.cfm?geog_auth_rec_id=10008358

@campmlc @jtgiermakowski I'm not sure who's managing MSB:Fish - help?

Is my interpretation correct, and if so can we change sea to continent=North America?

And http://arctos.database.museum/geography.cfm?geog_auth_rec_id=10008340 just needs to go away.

/remind me to check back in 2 weeks

**Comment by campmlc** [comment]
Ooh, that's lovely. I particularly like Gavleston being in New Jersey.
The higher geography for that one was originally Atlantic Ocean, Gulf of
Mexico, Offats Bayou
So should be changed to  North America, United States, Texas, Galveston
County, Galveston Island, Gulf of Mexico, Offats Bayou
or ?
I'm still confused by the land/sea higher geography. But this bayou is
essentially inshore.
http://wikimapia.org/2102460/Offats-Bayou

No one is currently managing MSB Fish - but that should change over the
next few months. I can be responsible for fixing issues until then.
Attaching the list of MSB Fish drainage terms.
Perhaps we need "watershed" in addition to cover bays = river + ocean

**Comment by dustymc** [comment]
>still confused by ... geography.

So say we all. https://github.com/ArctosDB/arctos/issues/1795. In my happy little world, everything would be shapes (which are unambiguous - at least when we have sufficient resolution), and anything that doesn't have a shape would somehow be treated as second-class data.

http://arctos.database.museum/Locality.cfm?Action=editGeog&geog_auth_rec_id=1004026 will provide a map of the county, at least. Deciding where the continent ends and the ocean begins seems fairly arbitrary to me, and of course arbitrary data makes discovering the specimens using it difficult or impossible.

The distinction between "watershed" and "drainage" (what we have now) seems too subtle to be useful to me, but perhaps it's there anyway.

I hope https://github.com/ArctosDB/arctos/issues/1102 will preclude the bayou being a sea.

There's some discussion of Feature in https://github.com/ArctosDB/arctos/issues/1273 - I still think it should be limited to political things (National Parks etc.).

I'd push the bayou to specloc, but I'm open to better ideas.

**Comment by Jegelewicz** [comment]
> Deciding where the continent ends and the ocean begins seems fairly arbitrary to me

At the edge of the continental shelf - but that isn't some kind of forever line - it changes every day....

**Comment by dustymc** [comment]
>edge of the continental shelf

I'm sure the geologists would agree (and they're not wrong), but that would make it basically impossible to search oceans - their shallow "seas" (and maybe margins altogether??!?) would be "children" of the nearest continent....

I maintain we have two options:

1) do something arbitrary
2) do something involving spatial data

**Comment by sharpphyl** [comment]
How about the Maritime limit set by each country?

https://nauticalcharts.noaa.gov/data/us-maritime-limits-and-boundaries.html

"The Office of Coast Survey depicts on its nautical charts the territorial sea (12 nautical miles), contiguous zone (24nm), and exclusive economic zone (200nm, plus maritime boundaries with adjacent/opposite countries)."

**Comment by dustymc** [comment]
@sharpphyl I have no real opinion on the specifics - from my perspective, ANYTHING that we can define spatially ceases to be an arbitrary string and becomes a data object that I can DO STUFF with. If you can get KML from that, or anything else, I'm happy to load it to geography and report on specimens that claim to be from there but don't map there. (You can do all of that too.)

**Comment by Jegelewicz** [comment]
> In my happy little world, everything would be shapes (which are unambiguous - at least when we have sufficient resolution), and anything that doesn't have a shape would somehow be treated as second-class data.

The problem is, humans don't search on shapes, they search on terms. We just need to be able to forge a set of terms that humans use and add shapes to them. So easy! Right!?

**Comment by dustymc** [comment]
>humans don't search on shapes, they search on terms

Shapes can have names. (And humans can very much search on shapes, although taking that very far past round shapes would require access to tools I don't have.) 

I think you have it backwards, but the idea that strings are simply metadata of shapes (or perhaps vise-versa, although that would be fatal to any temporal component) is an idea we've been discussing for a very long time. It's largely implemented in the 'any geog' search, but only as a discovery tool and not as "data." Pulling names from shapes and treating "higher geography" as verbatim would solve a huge number of geography problems.

**Comment by dustymc** [comment]
Done here? Tentatively closing....
