### ISSUE TITLE
cloning failed

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#2100]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

Tried to clone this record
http://arctos.database.museum/guid/UAM:Ento:395136

 into the bulkloader and got this error:

cloning failed: fail: Error Executing Database Query. [Macromedia][Oracle JDBC Driver][Oracle]ORA-00904: "PART_CONTAINER_LABEL_1": invalid identifier

**To Reproduce**
1. Go to '...' http://arctos.database.museum/guid/UAM:Ento:395136
2. Click on '....' other IDs -> clone this record -> option Two: Click here to create a record in the bulkloader,

cloning failed: fail: Error Executing Database Query. [Macromedia][Oracle JDBC Driver][Oracle]ORA-00904: "PART_CONTAINER_LABEL_1": invalid identifier

**Expected behavior**

**Screenshots**

** Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label. high

**Comment by Jegelewicz** [comment]
> cloning failed: fail: Error Executing Database Query. [Macromedia][Oracle JDBC Driver][Oracle]ORA-00904: "PART_CONTAINER_LABEL_1": invalid identifier

HMMM - something weird when cloning stuff with a barcode?

**Comment by dustymc** [comment]
fixed
