### ISSUE TITLE
Batch update Other Identifiers

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#2104]
Is there anyway to add a Prefix to our collector numbers in existing records?  I don't see it in the list of "manage" options or in the handbook.

![Screen Shot 2019-06-03 at 8 29 56 AM](https://user-images.githubusercontent.com/15368365/58809806-dafe3100-85d9-11e9-8b78-1a5d46d67985.png)

Here is a record without a Prefix.

![Screen Shot 2019-06-03 at 8 28 22 AM](https://user-images.githubusercontent.com/15368365/58809832-e8b3b680-85d9-11e9-85b7-ed129109587e.png)

I can add the prefix to the individual record

![Screen Shot 2019-06-03 at 8 28 35 AM](https://user-images.githubusercontent.com/15368365/58809849-f1a48800-85d9-11e9-843e-71647d97b33b.png)

and get what I want

![Screen Shot 2019-06-03 at 8 28 50 AM](https://user-images.githubusercontent.com/15368365/58809859-f79a6900-85d9-11e9-8033-28c16bbb19d0.png)

Is there a way to do this as a batch for each prefix we want to add?

**Comment by acdoll** [comment]
I have used this bulkloader several times (it works great!) and can help Phyllis with this. Related question: what is the point of splitting these into prefix, number and suffix? I imagine this is to help with searches. However, in both the data entry page and in the bulkloader, there isn't the option to separate these components out. You just put in the number with any associated character identifiers (ex. collector number: JRD1233) and all of that ends up in the prefix field. Would it be useful to have prefix and suffix fields on the data entry page and as options in the bulkloader? I have never had problems searching for these other_IDs regardless of how they were entered, so maybe this is a non-issue?

**Comment by sharpphyl** [comment]
Ah, the bulkloader.  I'll work with Andy to modify our other catalog numbers.  

It does seem like the fields should be the same whether you're entering a new record or modifying one.  Some of our identifiers originally entered in the ID Number field were split into a Prefix field and a Number field if there was a space between the alpha and numeric, but it didn't work with any quirk such as multiple identifiers.

One advantage of splitting the ID Number field into a Prefix and Number field during data entry is that we should be able to customize the form to carry forward the Prefix which is convenient.  Would that cause problems for anything or anyone else?

![Screen Shot 2019-06-03 at 8 09 57 AM](https://user-images.githubusercontent.com/15368365/58828906-b7e87700-8603-11e9-9dd6-4a862effc716.png)

![Screen Shot 2019-06-03 at 8 10 23 AM](https://user-images.githubusercontent.com/15368365/58828922-bfa81b80-8603-11e9-9a5d-151752b672b1.png)

**Comment by campmlc** [comment]
I would like the ability to enter prefix and integer via all forms. It
would be useful to be able to search on a range of collector numbers, for
example.

**Comment by dustymc** [comment]
>a Prefix field and a Number field if there was a space between the alpha and numeric, but it didn't work with any quirk such as multiple identifiers.

Space is in the list at http://handbook.arctosdb.org/documentation/other-identifying-numbers.html#bulk-loading-rules

It works the same everywhere - not sure what "multiple identifiers" means??

> Would that cause problems for anything or anyone else?

It would take away the magic - eg, I suspect people who deal with typed IDs (NK) would hate it. Probably worthy of a new issue, but again its not much of a technical problem. (It would be a screen real estate problem, but ya'll can figure that out!)

> enter prefix and integer via all forms. I

You've always been able to.

> search on a range of collector numbers

You've always been able to.

<img width="616" alt="Screen Shot 2019-06-03 at 12 48 08 PM" src="https://user-images.githubusercontent.com/5720791/58829931-ec593480-85fd-11e9-938e-9296a5175d39.png">

<img width="442" alt="Screen Shot 2019-06-03 at 12 48 36 PM" src="https://user-images.githubusercontent.com/5720791/58829941-f11de880-85fd-11e9-9535-60332bb596bd.png">

**Comment by sharpphyl** [comment]
> It works the same everywhere - not sure what "multiple identifiers" means??

In our initial upload, we put multiple other identifiers in one field, e.g. PMC 123; WS S-72.  Everything (as we should have known) ended up in the Prefix field.  As we deal with these entries, we're separating them into two entries with two fields each, but so far we've been able to search for them ok.

Is the decision whether or not to split out the three "Other ID" fields for data entry an AWG question or just a separate issue?

**Comment by campmlc** [comment]
I don't see why this would be a problem:
One advantage of splitting the ID Number field into a Prefix and Number
field during data entry is that we should be able to customize the form to
carry forward the Prefix which is convenient. Would that cause problems for
anything or anyone else?
How would that be difficult for those of us using numeric values?

**Comment by dustymc** [comment]
>AWG question or just a separate issue?

I think just separate - I'd like input from the folks who might use it.

>How would that be difficult for those of us using numeric values?

In the current DE form, there's one field. You put your value in there and the parser deals with it - at least I never see errors. In the single-record edit form there are three fields, and I see a "NK must be numeric" error at least a few times per week.

**Comment by Jegelewicz** [comment]
> In our initial upload, we put **multiple other identifiers in one field**, e.g. PMC 123; WS S-72. 

That might be the first problem. Other ID Numbers ARE split!

Those two should have been split and loaded as follows:

Other ID 1 entered as:
Other_ID_Type_1: collector number
Other_ID_Number_1: PMC 123

Other ID 2 entered as:
Other_ID_Type_2: original identifier
Other_ID_Number_2: WS S-72

**Comment by sharpphyl** [comment]
You're right Teresa, but that was years ago and the data that came from our old system didn't always map into the Arctos fields and we were blissfully unaware of that.

I'll start a separate issue and get input from others

**Comment by sharpphyl** [comment]
Now that I've tried the bulkload tool, I'm reopening this enhancement, although it's in bulkload now rather than a "manage collection" tool.

In order to REPLACE an Other ID, I have to add the ID through the bulkload tool https://arctos.database.museum/tools/BulkloadOtherId.cfm.  Then I have to delete the original Other ID by using the tool https://arctos.database.museum/tools/BulkDeleteOtherId.cfm.  This is both time consuming and prone to error.  

I would still like to be able to update Other IDs the way we do Collecting Events etc., under "Manage" but if that isn't feasible, can we at least add a REPLACE function to the bulkload Other ID tool so I can tell it what Other ID to add and what Existing Other ID to delete at the same time.

For example, I want to change Other ID (integer) "1" to be Other ID (prefix and integer) "Isle 1".

**Comment by Jegelewicz** [comment]
I agree that a replace with tool would help reduce errors and the one-step process would save time. This seems like it would be a useful tool.

**Comment by dustymc** [comment]
> REPLACE function to the bulkload Other ID tool so I can tell it what Other ID to add and what Existing Other ID to delete at the same time.

I think it's possible, but this seems like a huge increase in complexity for a tiny decrease in clicking to me.

**Comment by sharpphyl** [comment]
> I think it's possible, but this seems like a huge increase in complexity for a tiny decrease in clicking to me.

Ok, if we can't "manage" Other IDs and have to work through two bulkloader processes, can we at least make the headings the same so it isn't necessary to modify the data just to add a Prefix to the Integer that's already in the record?  Having different headings requires separating and combining data for each bulkload. 

The headings for adding an ID are: 

GUID_PREFIX | EXISTING_OTHER_ID_TYPE | EXISTING_OTHER_ID_NUMBER | NEW_OTHER_ID_TYPE | NEW_OTHER_ID_NUMBER | NEW_OTHER_ID_REFERENCES

The headings to delete an ID are: 

guid | other_id_type | other_id_number | other_id_references

The process and verbiage around each bulkload is also different.  It can be followed, but since we try for consistency in our data, it would be nice to have consistency in our procedures if possible. 

Again, it would be really nice to have a bulkloader that (as an option, not a requirement - same as with search) has headings for the three components of the Other IDs allowing users to modify just the section needed such as add a Prefix or suffix to an integer.  

[Bulkload inconsistency to add _Isle _ before each _other id number_.xls.zip](https://github.com/ArctosDB/arctos/files/3365780/Bulkload.inconsistency.to.add._Isle._.before.each._other.id.number_.xls.zip)

**Comment by sharpphyl** [comment]
I understand the need for discussion if the two bulkloader forms are to be combined or allow for  three-part ID modification, but can we at least normalize the headings on the two separate forms or is there a reason they are different?

**Comment by dustymc** [comment]
I think only GUID is precise enough for deletion.

I wrote the other form to load GenBank numbers from AF (or whatever random things users can be convinced to return). I still use it for that sort of thing, but I have other tools so I suppose we can simplify if this is a major concern. 

Removing what looks to me like significant capability should be discussed under a dedicated Issue so it's visible to anyone who might care.

**Comment by sharpphyl** [comment]
Either I'm not explaining my request well or it raises more issues than I expected, so I'm going to just work with the forms that we already have and close this issue.

**Comment by sharpphyl** [comment]
Either I'm not explaining my request well or it raises more issues than I expected, so I'm going to just work with the forms that we already have and close this issue.
