### ISSUE TITLE
Documentation GitHub Vulnerabilities

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2109]
![image](https://user-images.githubusercontent.com/5725767/58903690-4243e000-86c3-11e9-8199-7ca2a61ddf04.png)

I don't know what to do with this.
@mkoo ?

**Comment by mkoo** [comment]
these are alerts to update code libraries. I can turn off notifications for now and will work on getting them updated. these will happen for all our code sites if we allow github to screen for us.
