### ISSUE TITLE
Three part Other IDs "ID Number" data entry

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#2112]
In the Data Entry Screen (and the bulkloader) there is one field for the "ID Number."

![Screen Shot 2019-06-05 at 7 01 22 AM](https://user-images.githubusercontent.com/15368365/58959386-365b2b00-8762-11e9-817b-900aa2ed34df.png)

Data entered here is parsed by Arctos into three fields (Prefix, Integer, Suffix), then recombined.

Within a specimen record, modifications to Other IDs use a form with the three fields.

![Screen Shot 2019-06-05 at 7 02 38 AM](https://user-images.githubusercontent.com/15368365/58959496-78846c80-8762-11e9-83cb-b79ef2d1e254.png)

**Is your feature request related to a problem? Please describe.**
There's no problem with this, but it would be helpful if we had the ability to customize the data entry screen so it shows the three fields and we enter the data as appropriate.  This would enable us to carry forward the Prefix or other fields as needed.

**Describe the solution you'd like**

Ideally, similar capability as when searching.  Choose whether or not to split the Other ID into three fields or leave it in one.  

![Screen Shot 2019-06-05 at 7 03 21 AM](https://user-images.githubusercontent.com/15368365/58959630-b97c8100-8762-11e9-8f3e-5059e076896d.png)

**Describe alternatives you've considered**
1.  Leave it as it is, but several others have expressed interest in this.
2. Don't have an option; just make the ID Number field the three-part version for the Data Entry Screen for everyone.

**Additional context**
See #2104 for some additional information about how the Other IDs fields work.  Also, why is there a difference in the fields provided within an existing record and when entered a new record?

**Priority**
Medium.  This is an enhancement, not a problem.

**Comment by dustymc** [comment]
> Also, why is there a difference in the fields provided within an existing record and when entered a new record?

Someone asked for it, probably. It has caused a lot of problems, although it is a bit more obvious to use once understood.

* Datatyped identifiers must be entered correctly; entering NK in prefix throws an error. 
* The number component is numeric, and therefore eats leading zeros.
* The number component is numeric, and kinda everybody will instinctively try to provide "number" ``S`` for ``WS S-72``.
* ``WS 72-S`` will be entered as ``WS`` ``72`` ``S`` fairly often, producing a display value of ``WS72S``.

To clarify, it's all the same underlying data structure, this is just a matter of explicitly providing values (and the carry-over thing) vs. letting the parser figure it out. (For the data entry screen, unless someone has reasons not to, I'd probably just merge the three fields into an explicit-format single value and feed it back to the parser, which would not require modifying the bulkloader structure.)

I have no problem with this, but I suspect it's slightly more work, will produce a few more load errors, and will be slightly more prone to mangling data. That may be a cost worth paying for the carryover capability.

http://handbook.arctosdb.org/documentation/other-identifying-numbers.html#bulk-loading-rules

**Comment by sharpphyl** [comment]
Is it possible to allow data entry users to choose whether to use a three-part field or the current one-part field when they customize the form?  That would allow the carryover capability without disrupting the way other collections use the form.

**Comment by sharpphyl** [comment]
If the parser is pretty good at figuring out what goes in each field, why do we occasionally get this after using the data entry form for the entire collector number.  The parser only divided up the first entry correctly.  

![Screen Shot 2019-09-05 at 6 50 19 AM](https://user-images.githubusercontent.com/15368365/64343335-9784db80-cfa9-11e9-9262-fca1c8e35cb8.png)

![Screen Shot 2019-09-05 at 6 50 10 AM](https://user-images.githubusercontent.com/15368365/64343340-9b186280-cfa9-11e9-8720-eb0c8af0dc9f.png)

If we had entered the data into the three fields, we would have created this:

![Screen Shot 2019-09-05 at 6 54 22 AM](https://user-images.githubusercontent.com/15368365/64343637-22fe6c80-cfaa-11e9-9a37-5fe3ec1bba7b.png)

**Comment by dustymc** [comment]
http://handbook.arctosdb.org/documentation/other-identifying-numbers.html

The parser doesn't consider multiple delimiters.

There's a documented pathway to providing the parser guidance; you don't need three fields to enter that however you want....

**Comment by sharpphyl** [comment]
Thanks, but I've read through that handbook section several times.  I still don't know how to get ".A" into the suffix.  The exact collector number is "12294.A".  The prefix is the name of the collector.  Can you advise how to enter it in the data entry field "ID number" so that each section goes into the correct field?   "Schaake 12294.A" doesn't seem to be working.

**Comment by dustymc** [comment]
>Square brackets ( [ and ] ) may be used to explicitly define the numeric portion of an identifier.

``Schaake [12294].A``

**Comment by sharpphyl** [comment]
Thanks.

**Comment by sharpphyl** [comment]
Hmmm.   This is what I got when I used the square brackets to identify the "integer" portion of the collector number.  

![integer issue](https://user-images.githubusercontent.com/15368365/64721542-f2c33c00-d489-11e9-9abe-b9e948da22c5.JPG)

This is what I wanted

![snip ArctosDB/arctos#2](https://user-images.githubusercontent.com/15368365/64721628-22724400-d48a-11e9-881f-01f43016b27f.JPG)

What did I do wrong?

**Comment by dustymc** [comment]
Oh...blargh.

It's trimming the space, so the components can't be reassembled as the ID, and the catch on that is to toss everything into prefix. We could get rid of that, but it'd open up a whole 'nuther can of (very nasty) worms.

You could do...

```
Schaake&nbsp;[12294].A
```

which looks correct, but will fall out of some searches. I'd probably (if I had some compelling reason to break the integer out, and I've personally never found one...) ignore their uber-weird format and use something like..

```
Schaake.[12294].A
```

but that's not entirely correct either.

**Comment by sharpphyl** [comment]
Guess what.  If you put a space between the three fields you want, it works ok, e.g. 

Schaake 6566 .A

At least it did this time. I'll keep experimenting.

![snip 3](https://user-images.githubusercontent.com/15368365/64741556-3cc21700-d4b6-11e9-92aa-44302b7b4409.JPG)
