### ISSUE TITLE
Error when using tools in Agent Name Splitter Tool

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2113]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
At the bottom of the results after uploading a list of names to the Agent Name Splitter tool there are some options:

![image](https://user-images.githubusercontent.com/5725767/58973351-fce3e900-877c-11e9-9fc4-4e6980da1256.png)

**To Reproduce**
From those options, I selected "[ delete all "found one match" records ]"

and got this:
![image](https://user-images.githubusercontent.com/5725767/58973405-1f760200-877d-11e9-9b15-22c2ebc74b96.png)

**Expected behavior**
I expected all of the stuff in the results that included the status: "FATAL ERROR: duplicate of" to be removed from the results.

**Screenshots**
see above

** Data**
The tool itself worked fine, so I don't think data would make a difference?

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 67.01.01

**Additional context**
N/A

**Priority**
Please assign a priority-label.

**Comment by Jegelewicz** [comment]
Note: same error occurs with the "[ delete all "probably not a person" records ]" option.

**Comment by dustymc** [comment]
fixed
