### ISSUE TITLE
Add 5x5 freezer box to Edit Container Magic Drop-Down

### ISSUE THREAD

**Issue by KyndallH** [ArctosDB/arctos#2116]
Currently, under Edit Container,  9x9 and 10x10 freezer box listed but would like the 5x5 freezer box added to drop down. 

<img width="636" alt="Screen Shot 2019-06-06 at 2 07 27 PM" src="https://user-images.githubusercontent.com/16887896/59069750-9a661800-8864-11e9-82a9-1211552af01a.png">

Is there a way to bulk enter this information? I have a ton of freezer boxes and the idea of having to do this one by one for all of them is daunting to create positions. I know this is a recent change but I swear, the old way I didn't have to do this and I'm not remembering why. Yet it was easier.

**Comment by campmlc** [comment]
I am still playing with this new tool, but can't we just create these
ourselves? This should be customizable, so fill in the appropriate blanks:
5 rows, 5 columns, horizontal, holds container type cryovial?

**Comment by Jegelewicz** [comment]
You can totally do that, but it takes more time than the "magic"!

**Comment by Jegelewicz** [comment]
> Is there a way to bulk enter this information? I have a ton of freezer boxes and the idea of having to do this one by one for all of them is daunting to create positions. 

Use the [Bulk Edit Container](http://arctos.database.museum/tools/bulkEditContainer.cfm) tool. It's super easy.

**Comment by KyndallH** [comment]
Yes, we have been doing in manually, but magic is faster.

Faster yet is to go back when I already had all this data entered. My biggest peeve is that I had all these boxes already loaded and then when we changed the position things to help you guys, it screwed up all my boxes so now I have to go in for all my freezer boxes that do not have positions created and enter them manually (or use the magic). Before I would hit create positions and it would know it was a 5x5 freezer box and give me my grid because I had already entered that data. Now I have to do it again!?!?! And I'm not sure if I have all the bulkloader files from when I did this three years ago. So basically, it deleted the information I had already put in that it was an 81, 100, or 25 well box. :/ 
<img width="905" alt="Screen Shot 2019-06-07 at 8 35 09 AM" src="https://user-images.githubusercontent.com/16887896/59119395-317fae00-88ff-11e9-9604-e73ed1ee8cf3.png">

**Comment by campmlc** [comment]
Dusty, any way to recover this for Kyndall and automagic it back in?

**Comment by dustymc** [comment]
I can easily add to the magic, I just need details - what values do you want where?

I have an archive of the pre-change data. I don't see anything that didn't get migrated. I can look closer if you'll provide details or an example or something.

https://arctos.database.museum/EditContainer.cfm?container_id=17328538 is a 5x5 container.

The Issue that made the change is https://github.com/ArctosDB/arctos/issues/1743

**Comment by dustymc** [comment]
I can easily add to the magic, I just need details - what values do you want where?

I have an archive of the pre-change data. I don't see anything that didn't get migrated. I can look closer if you'll provide details or an example or something.

https://arctos.database.museum/EditContainer.cfm?container_id=17328538 is a 5x5 container.

The Issue that made the change is https://github.com/ArctosDB/arctos/issues/1743

**Comment by Jegelewicz** [comment]
@dustymc Welcome back!

Looking at the above, the magic should be:

magic = 5x5 freezer box
# rows = 5
# columns = 5
orientation = vertical
positions hold container type = cryovial

position height, length, width, and number of are given in Kyndall's post.

@KyndallH should confirm.

**Comment by KyndallH** [comment]
Example: C89018

The number of positions were bulkloaded. Before the changes, all I had to do was hit "create positions" but now I have to go into "edit contatiner" and add more information. 

When I received all the boxes and racks for the last upgrades, I (students) barcoded and uploaded all the information so I have no idea which boxes have been used and which ones have not. I can't simply edit the bulkloader files from before (and I may not have them all). :/ 

<img width="767" alt="Screen Shot 2019-06-20 at 9 30 49 AM" src="https://user-images.githubusercontent.com/16887896/59868733-20db2900-933e-11e9-846d-8644dc467b0f.png">
<img width="1125" alt="Screen Shot 2019-06-20 at 9 30 00 AM" src="https://user-images.githubusercontent.com/16887896/59868756-29336400-933e-11e9-80c2-c49e922835fd.png">
<img width="442" alt="Screen Shot 2019-06-20 at 9 30 14 AM" src="https://user-images.githubusercontent.com/16887896/59868763-2afd2780-933e-11e9-9daf-1d72af8fab11.png">
<img width="686" alt="Screen Shot 2019-06-20 at 9 30 30 AM" src="https://user-images.githubusercontent.com/16887896/59868768-2df81800-933e-11e9-82d7-25f04e10aa25.png">

**Comment by dustymc** [comment]
```
create table temp_25pfb as select *  from bak_container20181127 where DESCRIPTION='25-place freezer box';

UAM@ARCTOS> select POSITIONS_HOLD_CONTAINER_TYPE, count(*)  from container where container_id in (select container_id from temp_25pfb) group by POSITIONS_HOLD_CONTAINER_TYPE;

POSITIONS_HOLD_CONTAINER_TYPE						      COUNT(*)
--------------------------------------------------------------------------- ----------
										   173
cryovial									   300
freezer box									     7


UAM@ARCTOS> alter table temp_25pfb add real_container_holds_psntyp varchar2(255);

Table altered.

Elapsed: 00:00:00.09
UAM@ARCTOS> update temp_25pfb set real_container_holds_psntyp = (select POSITIONS_HOLD_CONTAINER_TYPE from container where container.container_id=temp_25pfb.container_id);

480 rows updated.

```
Data from the archive is attached, with "real_container_holds_psntyp" pulled from current container data. The freezer boxes in freezer boxes probably killed the migration scripts, and those will need dealt with individually - I think we cleaned some of that up somewhere, the funky data may be gone but those can't function like that. The 300 that hold cryovials are probably fine. There should be enough info in the attached to use the bulk-editor on the 173 - lemme know if you need more.

>Before the changes, all I had to do was hit "create positions" but now I have to go into "edit contatiner" and add more information.

https://github.com/ArctosDB/arctos/issues/1743#issuecomment-431104536 - it was apparent that flexibility was going to come with some setup costs very early.

There's now a 5x5 magic option that uses parameters from https://github.com/ArctosDB/arctos/issues/2116#issuecomment-502753695. Is it really vertical?

**Comment by Jegelewicz** [comment]
@KyndallH is this resolved?

**Comment by KyndallH** [comment]
Can I get it switched from "vertical" magic to "horizontal" magic? Otherwise, it is resolved.

**Comment by dustymc** [comment]
done in PG
