### ISSUE TITLE
We cannot scan "cryovial" barcodes into a 5x5 freezer box. 

### ISSUE THREAD

**Issue by KyndallH** [ArctosDB/arctos#2117]
We cannot scan "cryovial" barcodes into a 5x5 freezer box. Works fine for the 9x9 or the 10x10 but not the 5x5. 
<img width="1273" alt="Screen Shot 2019-06-07 at 1 07 03 PM" src="https://user-images.githubusercontent.com/16887896/59133773-86361f80-8925-11e9-8aaa-f84466446bbb.png">

**Comment by Jegelewicz** [comment]
Is the box set to hold cryovials?
![image](https://user-images.githubusercontent.com/5725767/59134962-6d843480-893a-11e9-8dd7-687e6bdbecf4.png)

**Comment by KyndallH** [comment]
Nope! It was set to freezer box - student must of thought it was "box type". Fixed! Thanks!
