### ISSUE TITLE
Add Ogallala formation to geology attributes

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#2120]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Table**
Geology Attributes

**Value**
Ogallala Formation

**Definition**
The Ogallala Formation is a Miocene to Pliocene geologic unit in the High Plains of the western United States and the location of the Ogallala Aquifer. see: https://en.wikipedia.org/wiki/Ogallala_Formation

**Collection type**
all collections?

**Attribute data type**
formation

**Context**
need formation for geology attribute

**Priority**
Please assign a priority-label.

**Comment by Jegelewicz** [comment]
Done
