### ISSUE TITLE
MVZ using same barcodes as UAM

### ISSUE THREAD

**Issue by KyndallH** [ArctosDB/arctos#2123]
Not sure what has happened but MVZ has two tissues (that I've found) that are using the same barcodes as UAM. Mistake? Missing a prefix? Unsure who to contact at MVZ. 

<img width="1822" alt="Screen Shot 2019-04-25 at 10 27 29 AM" src="https://user-images.githubusercontent.com/16887896/56759270-0d984c80-6745-11e9-8491-72e941285806.png">

**Comment by dustymc** [comment]
See also https://github.com/ArctosDB/arctos/issues/2063

**Comment by ccicero** [comment]
@KyndallH Sorry, I missed this issue but found it when looking through those requiring user action.

Kyndall, these look ok now on my end - are you still seeing that or can we close this issue? Sometimes the barcode reader mis-scans and leaves off the 'MVZ' which I always tell students to check before they save.
