### ISSUE TITLE
VertNet duplicates records by collecting event.

### ISSUE THREAD

**Issue by amgunderson** [ArctosDB/arctos#2126]
VertNet is showing 3 records for this 1 UAM:Mamm specimen, UAM 22218, https://arctos.database.museum/guid/UAM:Mamm:22218. It has 1 record for each collecting event even though 2 of those events are unaccepted. http://portal.vertnet.org/search?q=catalognumber:22218+institutioncode:UAM

**Comment by dustymc** [comment]
The data in the feed do not contain unaccepted events - VN probably just needs refreshed.

```
UAM@ARCTOS> select count(*) from digir_query.ipt_view where references like '%UAM:Mamm:22218';

  COUNT(*)
----------
	 1

1 row selected.
```

@tucotuco @dbloom ?

**Comment by tucotuco** [comment]
I have looked over the full path of data to see where this might be coming
from. The published data look good, but I think VertNet has retained old
collecting events from before the query filtered out unaccepted ones. This
could affect any of the Arctos data sets, so I will purge them and reload
for the next harvest pass. I have created an issue for this in VertNet
tasks.

**Comment by tucotuco** [comment]
Confirmed. I purged the old data and reharvested. Now only one UAM:Mamm:22218 appears in search results.
