### ISSUE TITLE
Part_Container_Label_1 got removed from Bulkloader - Please put back!!

### ISSUE THREAD

**Issue by atrox10** [ArctosDB/arctos#2128]
Recently the specific term: Part_Container_Label_1 was removed from the Bulkloader Builder. I think this was removed in the last 2 months as of June 2019 ( I uploaded date with this field recently). We use this field A LOT for MVZ Herpetology, because that field we use to describe what the side of our tubes say, which is usually the field number. If this is missing from the Buikloader, then we have to edit each cryotube container label by hand. Sometimes this is for over 4000 tissues samples. So I would MUCH prefer to have Part_Container_Label_1  as any option in the Bulkloader.

**Comment by dustymc** [comment]
This came from https://github.com/ArctosDB/arctos/issues/2048#issuecomment-485487104

**Comment by dustymc** [comment]
Solved in https://github.com/ArctosDB/arctos/issues/2048
