### ISSUE TITLE
Require tissue error

### ISSUE THREAD

**Issue by frederikseersholm** [ArctosDB/arctos#2129]
** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **

** Arctos Documentation is http://handbook.arctosdb.org/ **

** Learn more about Arctos at https://arctosdb.org/ **

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **

**Comment by frederikseersholm** [comment]
Hi, 
I'm getting an error when using the Arctos DB browser version. When ticking 'Require tissue' the search freezes. When 'require tissue' is unticked everything works fine... 
Best, Frederik

**Comment by dustymc** [comment]
Hi Frederik,

What were you searching for when you encountered this problem?

Thanks - D

**Comment by frederikseersholm** [comment]
Hi,

I tried a couple of different species under ‘Any taxon, ID, common name’… Everything gave the same result. Also when all search boxes were empty.

This is the link: 
https://arctos.database.museum/SpecimenSearch.cfm

Cheers,

**Comment by campmlc** [comment]
Hi Frederik,
The "Any Taxon, ID etc" search can time out when the possible search
results or parameters are very large. You can get a better result by
clicking "Show more options" on the right side of the Identification and
Taxonomy search box and then using the Identification query box instead.
Try that and let us know how that works.
Also, if you can give us the specific search query you used, e.g. which
species, that would help us trouble shoot as well.
Thanks,
Mariel Campbell
Arctos Working Group
