### ISSUE TITLE
UMNH Barcodes staked but get "barcode_not_found" error messages

### ISSUE THREAD

**Issue by srobson4** [ArctosDB/arctos#2130]
UMNH has successfully staked a claim on barcode series UMNH000001-UNMH100000 but attempt to bulk edit container with barcode series UMNH010333-UMNH010412 resulted in status column that reads "barcode_not_found".  We have successfully bulk edited containers recently with our staked barcode series, so not sure what's wrong.

**Comment by campmlc** [comment]
Shannon, did you create the container series  yet?

**Comment by campmlc** [comment]
Shannen, look at create container here.
http://handbook.arctosdb.org/how_to/How-to-Start-Object-Tracking.html

**Comment by Jegelewicz** [comment]
That's probably it. You have those barcodes assigned to you, but before they can be used, you have to create them in Arctos.

[This](http://handbook.arctosdb.org/how_to/How-to-Create-and-Edit-Containers.html) is the How-To you need.
