### ISSUE TITLE
Temporary event/locality nicknames

### ISSUE THREAD

**Issue by anna-chinn** [ArctosDB/arctos#2134]
To reference existing collecting events and localities in a bulkloader, these events/localities require nicknames and adding nicknames one by one is time intensive.

**Describe the solution you'd like**
A user tool that could automatically add/remove nicknames for existing collecting events and localities (like [this](https://github.com/ArctosDB/arctos/issues/1898#issuecomment-473323444)!). Maybe even nicknames that have an expiration date (like encumbrances)?

This would make referencing existing events/localities in a bulkloader much easier and would prevent folks from unintentionally creating redundant events/localities during the 30 day grace period before Dusty's scripts merge them with existing localities/events. Plus, in light of the new event attribute bulkloader from #1270 , being able to easily reference existing events is important.

**Describe alternatives you've considered**
Dusty batch updating nicknames ad hoc.

**Comment by dustymc** [comment]
If you're actually reading my thoughts, sorry for the jumble in there.....

I don't like auto-expire; the primary purpose of event names is stability, I'm not crazy about anything that might accidentally break that. "Really easy to get rid of when you're done" (eg, an un-loader) seems doable/useful/etc - it should just be one column in CSV, event_name_to_remove.

How would you find the events to name? Can it just be a list of collecting_event_ids, with the resulting name something like "temp_{collecting_event_id}"?

**Comment by anna-chinn** [comment]
> sorry for the jumble in there.....

Ha! No worries!

> "Really easy to get rid of when you're done"

How easy would it be to build/integrate an opt-in reminder that would email us at a specified time interval and tell us to delete our nicknames?

> Can it just be a list of collecting_event_ids, with the resulting name something like "temp_{collecting_event_id}"?

That sounds good to me.
In general, I get events/localities through this tool, then download CSV:
![Capture](https://user-images.githubusercontent.com/40321380/60352464-81e1ad00-998d-11e9-8ef4-6fd594c81973.JPG)
Integrating the tool into a specimen results drop down menu would be awesome.

**Comment by dustymc** [comment]
>opt-in reminder

Can we do something predictable - "temp_{collecting_event_id}"? If so it should be possible.

>Integrating the tool into a specimen results drop down menu would be awesome.

So 

1. name unnamed events in this result
2. un-name temp_{collecting_event_id}-named events in this result

?? This can't possibly be that simple....

**Comment by Jegelewicz** [comment]
> ?? This can't possibly be that simple....

I can't think of a wrench in there...yet

**Comment by anna-chinn** [comment]
> Can we do something predictable - "temp_{collecting_event_id}"? If so it should be possible.

Works for me!

**Comment by dustymc** [comment]
However you get there - specimenresults/manage works - there's now a manage names button at the top of localities and events.

todo: notifications

**Comment by dustymc** [comment]
Monthly notifications at tempLocEventNotification
