### ISSUE TITLE
How to deal with "mask year collected"

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#2145]
Currently: 8888-01-22

Yay: you can partially search - "collected in January" is possible.

Not-so-yay: it's weird.

**Comment by ewommack** [comment]
So this would allow us to search for anything where we have a month of collection but no year?

**Comment by dustymc** [comment]
>where we have a month of collection

http://handbook.arctosdb.org/documentation/dates.html

ISO8601 has no capacity to store month-only data. You always know more than month anyway (wasn't collected NEXT April) so the best you could do for "some random April" would be ~began_date=1800-04; ended_date=2019-04.

You can search that by month=04.

For 'mask year collected' records, public users currently see 8888-04 and 8888-04 as the pair of dates. They can still locate those specimens by month=04. They can't locate them by year=2012; 2012 is not between 8888 and 8888. (Encumbrances both mask data and prevent queries that would allow deducing masked data.)

That all works fairly well - that's why we did it this way! - but users finding year=8888 (in Arctos, on GBIF-n-friends, etc.) may not understand what they're looking at.

Anything that's not an ISO8601 date is going to break things. I don't really see a solution that doesn't involve withholding all date information, breaking forms and parse scripts everywhere, or "obvious"  fake dates. Hopefully someone sees something I don't....

**Comment by ewommack** [comment]
> For 'mask year collected' records, public users currently see 8888-04 and 8888-04 as the pair of dates. They can still locate those specimens by month=04. They can't locate them by year=2012; 2012 is not between 8888 and 8888. (Encumbrances both mask data and prevent queries that would allow deducing masked data.)

Thanks Dusty, now I get it!

Next question:
> Anything that's not an ISO8601 date is going to break things. I don't really see a solution that doesn't involve withholding all date information, breaking forms and parse scripts everywhere, or "obvious" fake dates. Hopefully someone sees something I don't....

This sounds similar to a problem with a mystery error message, except you don't get a handy pop up when the 8888 date comes up with a data search. Could this be solved by adding a definition of what the 8888 date means? It's not a code so you can't put it in a code table, but it seems like it is approaching that type of information...

**Comment by dustymc** [comment]
http://handbook.arctosdb.org/documentation/dates.html#restricted-data

??

**Comment by ewommack** [comment]
Yes that exactly!
Is there a place we can put that where people can find the info if they're not reading the Arctos hand book? Maybe has a little question mark link on the specimen information page like are in the cataloging interface that links back to the handbook? Or does that open a new can of worms?
![Screen Shot 2019-07-15 at 6 24 17 PM](https://user-images.githubusercontent.com/18562884/61257361-f490ad80-a72d-11e9-80c4-8f006973ad81.png)
