### ISSUE TITLE
Symbiotype reference

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2151]
Currently, symbiotype is in the Citation Type Status code table with definition 
"Host from which the type of a new parasite species is described. ​Frey et al. 1992, http://www.jstor.org/stable/3283335"

However, if this type status is chosen for a host individual, the citation reads, for example:
"symbiotype of Urocitellus undulatus , page 470 in Durden et al. 2019 DOI:10.1645/18-198"

But really, it should read:
symbiotype of (insert parasite taxon name here) , page 470 in Durden et al. 2019 DOI:10.1645/18-198

This is critical because hosts may have multiple relationships to different parasites, and there is no way currently to distinguish which parasite taxon or specimen record the symbiotype is described from, without using remarks. 
see http://arctos.database.museum/guid/MSB:Mamm:289043
Ideas?

**Comment by campmlc** [comment]
Better example of host with multiple associated parasites, only one of which is the type specimen for which the host is the parasite:
http://arctos.database.museum/guid/MSB:Mamm:288931

**Comment by dustymc** [comment]
Can you attach one of the publications?

**Comment by campmlc** [comment]
https://www.journalofpa
[Mongolian lice new sp Durden et al 2019.pdf](https://github.com/ArctosDB/arctos/files/3370829/Mongolian.lice.new.sp.Durden.et.al.2019.pdf)
rasitology.org/doi/full/10.1645/18-198

**Comment by campmlc** [comment]
https://www.journalofparasitology.org/doi/full/10.1645/18-198
Mongolian lice new sp Durden et al 2019.pdf

**Comment by campmlc** [comment]
grrr. 
[Mongolian lice new sp Durden et al 2019.pdf](https://github.com/ArctosDB/arctos/files/3370830/Mongolian.lice.new.sp.Durden.et.al.2019.pdf)

**Comment by dustymc** [comment]
There are an exceptional number of holotypes in https://arctos.database.museum/SpecimenResults.cfm?publication_id=10008865...

That's a really fuzzy association - they don't use the word symbiotype nor explicitly identify the hosts. I definitely see the value of trying to get at these data, and I suppose it's all in between the lines, but I think maybe we're stretching what was said??

ANYWAY...

1) citations use identifications, and they can be strings - "Urocitellus undulatus as symbiotype of Linognathoides urocitelli" (er sumthin) does what needs done, however kludgily

2) a new "symbiotype of" relationship is weird too (and what's the reciprocal?), but also more or less conveys the information

I think (1) is closer to "structurally correct" but (2) may be more explicit. I'm not crazy about either - hopefully someone else has better ideas.

**Comment by campmlc** [comment]
We are stretching what was said because they did not say what they were
supposed to say. They did not explicitly give the symbiotypes, instead
saying they "examined" the following hosts without clarifying which type
specimen was associated with which host. Fortunately, these are MSB
specimens, and we have these data in Arctos, linked by the shared collector
(NK) number (which should be an organism ID) of the host and parasite. So I
have created the symbiotypes from that linkage.
Yes, there is a male holotype, a female allotype, and 3 paratypes. Each has
a different MSB:Para catnum. There is no specific designation for allotype
that I could find, so I created a second holotype and put "allotype" in
remarks.

**Comment by dustymc** [comment]
>did not say what they were supposed to say

I'm no taxonomist, but I'm not so sure there can be symbiotypes without that....

>organism ID

Assigning an OrganismID to two distinct Organisms could not possibly result in anything good?!?!?

>no specific designation for allotype
`Recommendation 72A. Use of the term "allotype". The term "allotype" may be used to indicate a specimen of opposite sex to the holotype; an "allotype" has no name-bearing function.`

I think the lack of the word "syntype" in that context very explicitly means you don't have a Type. I suppose we could add allotype, but from here it sort of looks like a synonym to 'voucher'???

I think this has to be a taxonomy problem before it can be an Arctos problem; I can't see that what you're trying to solve exists, but I can't see lots of things in taxonomy-land. I do think we should be more careful with the usage of Code terms; eg, if someone comes to examine your holotypes they are seriously not going to want to discover you actually have an "honorable mention." I don't think there are any technical implications to that yet, but perhaps someday ICZN will build something awesome at which time careful use of the terms would become important. (Not really holding my breath, but maybe....)
