### ISSUE TITLE
Short title of publication does not find publication

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2152]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
When I create a publication, I can give it a short title which is then used as the link in the specimen record to the citation. However, clicking this link goes nowhere, and it isn't possible to search on the short citation.

**To Reproduce**
See  https://arctos.database.museum/guid/MSB:Para:28815 and click link to Durden et al. 2019 under citations

**Expected behavior**
The link should find the publication.

**Priority**
soon.

**Comment by campmlc** [comment]
Durden et al 2019 is the short citation, which should be able to link to the full citation.

**Comment by dustymc** [comment]
deborked
