### ISSUE TITLE
Label report is pulling Part ID instead of Part Count

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#2153]
We have made no changes to our label report (DMNS Marine Invertebrates by ZC), but last week it started to occasionally pull the first three digits of the Part ID as the Part Count.  It is not consistent on all lots.  Some lots pull the Count correctly.

The appearance of the search results that are used to create the label report also look different on the ones with the Count issue and appear to be the cause.  We find nothing unusual about the Part Detail content.  

![Screen Shot 2019-07-09 at 12 10 36 PM](https://user-images.githubusercontent.com/15368365/60912986-a8340200-a243-11e9-9395-bbc1d41a80f4.png)

The labels show the Part ID instead of the Part count

![Screen Shot 2019-07-09 at 12 10 03 PM](https://user-images.githubusercontent.com/15368365/60913023-c39f0d00-a243-11e9-94b5-3c23387d1669.png)

This occurs with Chrome and Firefox and with PCs and Mac.

**Comment by dustymc** [comment]
See http://handbook.arctosdb.org/documentation/json.html for the Arctos JSON Standard (and https://github.com/ArctosDB/arctos/issues/2131 for origins).

I just flagged your entire collection to refresh, so you should have consistent data in a couple hours.

The SQL is best updated by whomever wrote it - it should just need some offset adjustments. Or let me know what it's trying to do and I might be able to provide an alternative.

**Comment by sharpphyl** [comment]
Thanks for refreshing.  We'll wait a few hours before we try to print again.  If adjustments are needed in the label report, we may need your help as Bryan Johnson wrote the SQL and is out for another week or two.  More later.

**Comment by sharpphyl** [comment]
Is Arctos down or is it just our collection?  As of yesterday, changes made to individual specimen records are not showing up in the search list; none of the records approved to upload from the bulkloader have moved; we can't even see our label report to figure out how to correct the Lot Count, etc. etc.   It all started yesterday but we though Arctos was just having a problem but now it seems to be just our collection.

**Comment by dustymc** [comment]
The processes to bulkload and refresh FLAT are temporarily disabled while I deal with some administrative stuff, which didn't finish last night. I'll kill that and find another way if it doesn't finish soon-ish.

That shouldn't have any effect on labels or "etc." - I can investigate if you want to share details.

**Comment by sharpphyl** [comment]
Ok, now we can get labels and Andy is working with me to straighten out the "count" issue.  Still a few other glitches but we'll hold tight for a while.  Thx.
