### ISSUE TITLE
Positions form is locking up

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2157]
I am trying to create positions in a container and the form just hangs.

![image](https://user-images.githubusercontent.com/5725767/61008683-7ac38300-a32d-11e9-95ae-df46f5ce072f.png)

I've been doing this ALL day with no problem, so I'm not sure what has happened (maybe I've done too much today...)

**Comment by dustymc** [comment]
Looks like things are just busy - hopefully it'll clear up in a bit, if not all I know to do is pull the plug for a while.....

**Comment by Jegelewicz** [comment]
Wah wah. :-(
