### ISSUE TITLE
Arctos is down?

### ISSUE THREAD

**Issue by anna-chinn** [ArctosDB/arctos#2158]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I'm getting this screen at arctos.database.museum:
![Capture](https://user-images.githubusercontent.com/40321380/61068675-2f15e580-a3d0-11e9-97a3-96f8739f994f.PNG)

**Desktop (please complete the following information):**
Windows 7, Chrome Browser

**Additional context**
Refreshed and got this error:

> An error occurred while processing this page! 
ORA-12519 The listener could not find any available service handlers that are appropriate for the client connection. One possible cause for this error is that the server was not configured for the specified server type (shared/dedicated).

EDIT: I first got the error when I was trying to bulkload specimens. I went back to the first bulkload specimens screen after validating my records and this error showed up.

**Comment by anna-chinn** [comment]
Oh, I just saw your comment on Phyllis' last issue, Dusty. Hopefully I didn't break anything further by trying to use the bulkloader.

**Comment by dustymc** [comment]
No that's not it - there was another probable DDOS attack, the DB seems to be plugged up, I secured what I can and emailed Chris.

**Comment by dustymc** [comment]
Should all be happy now.

**Comment by campmlc** [comment]
Arctos is down this morning 7/29/19
@dustymc
