### ISSUE TITLE
make DWC better

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#2160]
1) It's currently a view, that's slow - try to recompile as MV or table+scripts or something
2) @tucotuco will send a field list - try to comply with it so mapping can be automated

**Comment by tucotuco** [comment]
There are several mappings. One for the Occurrence Core, and some for extensions. Here is the mapping for the Occurrence Core:

ipt_view | DwC
-- | --
COLLECTION_ID | not mapped
LANGUAGE | LANGUAGE
RIGHTS | dcterms:license
TYPE | not mapped
BASISOFRECORD | not mapped
COLLECTIONCODE | not mapped
RECORDEDBY | RECORDEDBY
INFORMATIONWITHHELD | INFORMATIONWITHHELD
INDIVIDUALCOUNT | INDIVIDUALCOUNT
INSTITUTIONCODE | not mapped
MODIFIED | dcterms:modified
ASSOCIATEDOCCURRENCES | ASSOCIATEDOCCURRENCES
REFERENCES | dcterms:references
OCCURRENCEREMARKS | OCCURRENCEREMARKS
TYPESTATUS | TYPESTATUS
ASSOCIATEDTAXA | ASSOCIATEDTAXA
OTHERCATALOGNUMBERS | OTHERCATALOGNUMBERS
INDIVIDUALID | organismID
CATALOGNUMBER | CATALOGNUMBER
ASSOCIATEDSEQUENCES | ASSOCIATEDSEQUENCES
RECORDNUMBER | RECORDNUMBER
FIELDNUMBER | FIELDNUMBER
SEX | SEX
LIFESTAGE | LIFESTAGE
DYNAMICPROPERTIES | DYNAMICPROPERTIES
IDENTIFICATIONREMARKS | IDENTIFICATIONREMARKS
FAMILY | FAMILY
HIGHERCLASSIFICATION | HIGHERCLASSIFICATION
GENUS | GENUS
IDENTIFICATIONREFERENCES | IDENTIFICATIONREFERENCES
IDENTIFICATIONQUALIFIER | IDENTIFICATIONQUALIFIER
IDENTIFIEDBY | IDENTIFIEDBY
TAXONRANK | TAXONRANK
KINGDOM | KINGDOM
DATEIDENTIFIED | DATEIDENTIFIED
IDVERIFICATIONSTATUS | identificationVerificationStatus
NOMENCLATURALCODE | NOMENCLATURALCODE
PREPARATIONS | PREPARATIONS
PCLASS | class
PORDER | order
PHYLUM | PHYLUM
SCIENTIFICNAME | SCIENTIFICNAME
SPECIFICEPITHET | SPECIFICEPITHET
INFRASPECIFICEPITHET | INFRASPECIFICEPITHET
PREVIOUSIDENTIFICATIONS | PREVIOUSIDENTIFICATIONS
ASSOCIATEDMEDIA | ASSOCIATEDMEDIA
OCCURRENCEID | not mapped
SPECIMENEVENTTYPE | not mapped
SAMPLINGPROTOCOL | SAMPLINGPROTOCOL
ESTABLISHMENTMEANS | ESTABLISHMENTMEANS
LOCATIONACCORDINGTO | LOCATIONACCORDINGTO
GEOREFERENCEDBY | GEOREFERENCEDBY
GEOREFERENCEDDATE | GEOREFERENCEDDATE
HABITAT | HABITAT
GEOREFERENCEVERIFICATIONSTATUS | GEOREFERENCEVERIFICATIONSTATUS
EVENTREMARKS | EVENTREMARKS
GEODETICDATUM | GEODETICDATUM
VERBATIMEVENTDATE | VERBATIMEVENTDATE
VERBATIMLOCALITY | VERBATIMLOCALITY
VERBATIMCOORDINATESYSTEM | VERBATIMCOORDINATESYSTEM
EVENTDATE | EVENTDATE
EVENTTIME | EVENTTIME
DAY | DAY
MONTH | MONTH
YEAR | YEAR
ENDDAYOFYEAR | ENDDAYOFYEAR
VERBATIMCOORDINATES | VERBATIMCOORDINATES
COORDINATEUNCERTAINTYINMETERS | COORDINATEUNCERTAINTYINMETERS
DECIMALLATITUDE | DECIMALLATITUDE
DECIMALLONGITUDE | DECIMALLONGITUDE
LOCALITY | LOCALITY
GEOREFERENCEPROTOCOL | GEOREFERENCEPROTOCOL
GEOREFERENCESOURCES | GEOREFERENCESOURCES
MINIMUMDEPTHINMETERS | MINIMUMDEPTHINMETERS
MAXIMUMDEPTHINMETERS | MAXIMUMDEPTHINMETERS
MINIMUMELEVATIONINMETERS | MINIMUMELEVATIONINMETERS
MAXIMUMELEVATIONINMETERS | MAXIMUMELEVATIONINMETERS
LOCATIONREMARKS | LOCATIONREMARKS
CONTINENT | CONTINENT
COUNTRY | COUNTRY
COUNTY | COUNTY
ISLAND | ISLAND
ISLANDGROUP | ISLANDGROUP
QUAD | not mapped
WATERBODY | WATERBODY
FEATURE | not mapped
STATEPROVINCE | STATEPROVINCE
HIGHERGEOGRAPHY | HIGHERGEOGRAPHY
INSTITUTION | institutionCode
COLLECTION | collectionCode
EARLIESTERAORLOWESTERATHEM | EARLIESTERAORLOWESTERATHEM
EARLIESTEONORLOWESTEONOTHEM | EARLIESTEONORLOWESTEONOTHEM
EARLIESTEPOCHORLOWESTSERIES | EARLIESTEPOCHORLOWESTSERIES
EARLIESTAGEORLOWESTSTAGE | EARLIESTAGEORLOWESTSTAGE
EARLIESTPERIODORLOWESTSYSTEM | EARLIESTPERIODORLOWESTSYSTEM
FORMATION | FORMATION
GEO_GROUP | group
MEMBER | MEMBER
OCCURRENCEID2 | occurrenceID

And here are Darwin Core fields that are currently filled in manually with constants. Any that could be provided in the view would be helpful:

DwC | Constant provided
-- | --
institutionID | grbio_institution_id
collectionID | grbio_collection_id
dcterms:type | "PhysicalObject" or "Event"
basisOfRecord | "PreservedSpecimen" or "HumanObservation" or "FossilSpecimen" (would be best to get standard values in BASISOFRECORD and just map that, as it can vary within a data set)
accessRights | "http://vertnet.org/resources/norms.html "

**Comment by tucotuco** [comment]
And here is the mapping for the Audubon Media Description extension:

ipt_better_media | DwC
-- | --
COLLECTION_ID | not mapped
OCCURRENCEID | not mapped
GUID | not mapped
IDENTIFIER | accessURI
OLD_IDENTIFIER | not mapped
REFERENCES | dcterms:identifier, furtherInformationURL
SOURCE | dc:source
FORMAT | dc:format
TYPE | dctype:type
TITLE | dcterms:title
DESCRIPTION | dcterms:description
SPATIAL | not mapped
LATITUDE | not mapped
LONGITUDE | not mapped
CREATED | CreateDate
CREATOR | dc:creator
LICENSE | WebStatement
LAST_UPDATED | dcterms:modified
OCCURRENCEID2 | occurrenceID

**Comment by dustymc** [comment]
There's a temporary view - @tucotuco can you try it, make sure the quoted identifiers don't eat JDBC drivers or something?

Some of my mappings are probably a bit precarious, and this is a really tiny slice of what's in Arctos - seems like we could be sharing more, if anyone would use it. Requests, anyone?

Once that's all happy I can find a way to make this perform, then work on the media.

```
create or replace view digir_query.ipt_view_too as select
	--------------------------- "specimen gunk" ---------------------------
	filtered_flat.collection_id grbio_collection_id,
	'en' language,
	use_license_url "dcterms:license", -- not sure this is the right dwc concept
	--CATALOGED_ITEM_TYPE type, -- what is this again?
	decode(CATALOGED_ITEM_TYPE,
		'specimen','PreservedSpecimen',
		'observation','HumanObservation',
		NULL) basisOfRecord,
	-- 20190611: If we ever get preservation out of parts and into part attributes we might be able to use it here
	--CATALOGED_ITEM_TYPE basisOfRecord, 
	--COLLECTION_CDE collectionCode,
	decode(collectors,
		null,'',
		'Collector(s): ' || collectors ||
		decode(preparators,
			null,'',
			'; Preparator(s): ' || preparators
		)
	) recordedBy,
	ENCUMBRANCES informationWithheld,
	INDIVIDUALCOUNT individualCount,
	--INSTITUTION_ACRONYM institutionCode,
	LASTDATE "dcterms:modified",
	RELATEDCATALOGEDITEMS associatedOccurrences,
	'http://arctos.database.museum/guid/' || GUID "dcterms:references",
	REMARKS occurrenceRemarks,
	TYPESTATUS typeStatus,
	ASSOCIATED_SPECIES associatedTaxa,
	--------------------------- identifiers ---------------------------
	OTHERCATALOGNUMBERS otherCatalogNumbers,
	'http://arctos.database.museum/guid/' || GUID organismID,
	filtered_flat.guid catalogNumber,
	GENBANKNUM associatedSequences,
	COLLECTORNUMBER recordNumber, -- I think this is a very incomplete mapping
	FIELD_NUM fieldNumber, -- also incomplete/incorrect
	--------------------------- attribute-like gunk ---------------------------
	SEX	 sex,
	AGE_CLASS lifeStage,
	ATTRIBUTES dynamicProperties,
	--------------------------- taxonomy and identification ---------------------------
	IDENTIFICATION_REMARKS identificationRemarks,
	FAMILY family,
	trim(replace(full_taxon_name,scientific_name)) higherClassification,
	GENUS genus,
	ID_SENSU identificationReferences,
	TAXA_FORMULA identificationQualifier,
	IDENTIFIEDBY identifiedBy,
	taxon_rank taxonRank,
	--INFRASPECIFIC_RANK taxonRank,
	KINGDOM kingdom,
	MADE_DATE dateIdentified,
	NATURE_OF_ID IDVerificationStatus, -- toobookoo: "identificationVerificationStatus",
	NOMENCLATURAL_CODE nomenclaturalCode,
	PARTS preparations,
	PHYLCLASS "class",
	PHYLORDER "order",
	PHYLUM phylum,
	SCIENTIFIC_NAME scientificName,
	trim(replace(species,genus)) specificEpithet,
	trim(replace(subspecies,species))  infraspecificEpithet,
	previousidentifications previousidentifications,
	--------------------------- media ---------------------------
	IMAGEURL associatedMedia,
	-- event stuff
	-- we have to apply encumbrances here because this is NOT from filtered_flat
	-- we are getting ALL specimen_event-->geog_auth_rec here
	-- we are NOT getting geology here. We should be.
	--------------------------- specimen_event -------------------------------
   -- 'urn:occurrence:Arctos:' || filtered_flat.guid || ':' || specimen_event.specimen_event_id occurrenceID,
	--specimen_event.SPECIMEN_EVENT_TYPE SpecimenEventType, -- I'm asking
	decode(specimen_event.SPECIMEN_EVENT_TYPE,
		'collection','PhysicalObject',
		'encounter','PhysicalObject',
		'Event') "dcterms:type",	
	specimen_event.COLLECTING_METHOD samplingProtocol,
	specimen_event.COLLECTING_SOURCE establishmentMeans,
	getPreferredAgentName(specimen_event.ASSIGNED_BY_AGENT_ID) locationAccordingTo,
	getPreferredAgentName(specimen_event.ASSIGNED_BY_AGENT_ID) georeferencedBy,
	specimen_event.ASSIGNED_DATE georeferencedDate,
	specimen_event.HABITAT habitat,
	specimen_event.VERIFICATIONSTATUS georeferenceVerificationStatus,
	----------------------------concat -----------------------------------------
	decode (specimen_event.SPECIMEN_EVENT_REMARK || collecting_event.COLL_EVENT_REMARKS,
		null,null, -- both are null - move on
		decode (specimen_event.SPECIMEN_EVENT_REMARK,
			null,collecting_event.COLL_EVENT_REMARKS,
			specimen_event.SPECIMEN_EVENT_REMARK || decode(
				collecting_event.COLL_EVENT_REMARKS,
				null,'',
				'; ' || collecting_event.COLL_EVENT_REMARKS
			)
		)
	) eventRemarks,
	--------------------------- collecting_event -------------------------------
	collecting_event.DATUM geodeticDatum,
	collecting_event.VERBATIM_DATE  verbatimEventDate,
	collecting_event.VERBATIM_LOCALITY verbatimLocality,
	collecting_event.ORIG_LAT_LONG_UNITS verbatimCoordinateSystem,
	-- check for encumbrances
	CASE WHEN encumbrances LIKE '%mask year collected%'
		THEN replace(collecting_event.began_date,substr(collecting_event.began_date,1,4),'8888')
	ELSE 
		case when
			collecting_event.BEGAN_DATE=collecting_event.ENDED_DATE 
			then collecting_event.BEGAN_DATE
		else
			collecting_event.BEGAN_DATE || '/' || collecting_event.ENDED_DATE
		end 
	END eventDate,
	-- no encumbrance check necessary at time
	case when collecting_event.BEGAN_DATE=collecting_event.ENDED_DATE
		then substr(collecting_event.began_date,12)
	else
		collecting_event.BEGAN_DATE || '/' || collecting_event.ENDED_DATE
	end eventTime,
	case when collecting_event.BEGAN_DATE=collecting_event.ENDED_DATE 
		then substr( collecting_event.BEGAN_DATE, 9, 2 )
	end day,
	case when collecting_event.BEGAN_DATE=collecting_event.ENDED_DATE 
		then substr( collecting_event.BEGAN_DATE, 6, 2 )
	end month,
	CASE WHEN encumbrances LIKE '%mask year collected%'
		THEN '8888' -- deal with it....
	ELSE 
		case when collecting_event.BEGAN_DATE=collecting_event.ENDED_DATE 
			then substr( collecting_event.BEGAN_DATE, 1, 4 )
		end 
	END year,
	case when collecting_event.BEGAN_DATE=collecting_event.ENDED_DATE 
		then case when isdate(collecting_event.BEGAN_DATE)=1
			then to_number(to_char(to_date(collecting_event.began_date,'YYYY-MM-DD'),'DDD'))
		end
	end endDayOfYear,
	CASE WHEN encumbrances LIKE '%mask coordinates%'
		THEN NULL
	ELSE 
		collecting_event.VERBATIM_COORDINATES
	END verbatimCoordinates,
	--------------------------- locality -------------------------------
	to_meters(locality.MAX_ERROR_DISTANCE,locality.MAX_ERROR_UNITS) coordinateUncertaintyInMeters,
	CASE WHEN encumbrances LIKE '%mask coordinates%'
		THEN NULL
	ELSE locality.DEC_LAT
	END decimalLatitude,
	CASE WHEN encumbrances LIKE '%mask coordinates%'
		THEN NULL
	ELSE locality.DEC_LONG
	END decimalLongitude,
	locality.SPEC_LOCALITY locality,
	locality.GEOREFERENCE_PROTOCOL georeferenceProtocol,
	locality.GEOREFERENCE_SOURCE georeferenceSources,
	to_meters(locality.MIN_DEPTH,locality.DEPTH_UNITS) minimumDepthInMeters,
	to_meters(locality.MAX_DEPTH,locality.DEPTH_UNITS) maximumDepthInMeters,
	to_meters(locality.MINIMUM_ELEVATION,locality.ORIG_ELEV_UNITS) minimumElevationInMeters,
	to_meters(locality.MAXIMUM_ELEVATION,locality.ORIG_ELEV_UNITS) maximumElevationInMeters,
	locality.locality_remarks locationRemarks,
	--------------------------- geog_auth_rec -------------------------------
	geog_auth_rec.CONTINENT_OCEAN continent,
	geog_auth_rec.COUNTRY country,
	geog_auth_rec.COUNTY county,
	geog_auth_rec.ISLAND island,
	geog_auth_rec.ISLAND_GROUP islandGroup,
	--geog_auth_rec.QUAD Quad,
	geog_auth_rec.SEA waterBody,
	--geog_auth_rec.FEATURE Feature,	
	geog_auth_rec.STATE_PROV stateProvince,
	geog_auth_rec.HIGHER_GEOG higherGeography,	
	replace(replace(INSTITUTION_ACRONYM,'Obs'),'UAMb','UAM') institutionCode,
	collection collectionCode,
	getGeologyForDWC(locality.locality_id,'Erathem/Era') as earliestEraOrLowestErathem,
	getGeologyForDWC(locality.locality_id,'Eon/Eonothem') as earliestEonOrLowestEonothem,
	getGeologyForDWC(locality.locality_id,'Series/Epoch') as earliestEpochOrLowestSeries,
	getGeologyForDWC(locality.locality_id,'Stage/Age') as earliestAgeOrLowestStage,
	getGeologyForDWC(locality.locality_id,'System/Period') as earliestPeriodOrLowestSystem,
	getGeologyForDWC(locality.locality_id,'formation') as formation,
	getGeologyForDWC(locality.locality_id,'group') as "group",
	getGeologyForDWC(locality.locality_id,'member') as member,
	'http://arctos.database.museum/guid/'  || filtered_flat.guid || '?seid=' || specimen_event.specimen_event_id occurrenceID,
	replace(replace(INSTITUTION_ACRONYM,'Obs'),'UAMb','UAM') grbio_institution_id,
	'http://vertnet.org/resources/norms.html' accessRights
	--taxon_rank taxonRank
from
	filtered_flat,
	specimen_event,
	collecting_event,
	locality,
	geog_auth_rec
where
	filtered_flat.collection_object_id=specimen_event.collection_object_id (+) and
	--specimen_event.specimen_event_type != 'unaccepted place of collection' and
	specimen_event.verificationstatus != 'unaccepted' and
	specimen_event.collecting_event_id=collecting_event.collecting_event_id (+) and
	collecting_event.locality_id=locality.locality_id (+) and
	locality.geog_auth_rec_id=geog_auth_rec.geog_auth_rec_id (+)
;
```

Here are the first few rows in case that's somehow useful.

```
create table temp_iptv2 as select * from digir_query.ipt_view_too where rownum<1000;
```
[temp_iptv2.csv.zip](https://github.com/ArctosDB/arctos/files/3384280/temp_iptv2.csv.zip)

**Comment by Jegelewicz** [comment]
We need to have a talk about these for paleo collections:


EARLIESTAGEORLOWESTSTAGE | EARLIESTEONORLOWESTEONOTHEM | EARLIESTEPOCHORLOWESTSERIES | EARLIESTERAORLOWESTERATHEM | EARLIESTPERIODORLOWESTSYSTEM
-- | -- | -- | -- | --


And what about the "latest" part of these terms? I think this points out that we could be doing geology a bit better in Arctos.

LATESTAGEORLOWESTSTAGE | LATESTEONORLOWESTEONOTHEM | LATESTEPOCHORLOWESTSERIES | LATESTERAORLOWESTERATHEM | LATESTPERIODORLOWESTSYSTEM
-- | -- | -- | -- | --

**Comment by Jegelewicz** [comment]
>         SEX	 sex,
> 	AGE_CLASS lifeStage,
> 	ATTRIBUTES dynamicProperties,

Are these things going into [MeasurementorFact](https://dwc.tdwg.org/terms/#measurementorfact)?

**Comment by Jegelewicz** [comment]
I really need to dedicate a day to this...

**Comment by dustymc** [comment]
>talk

That's https://github.com/ArctosDB/arctos/issues/2094

>doing geology a bit better in Arctos.

I don't think so; these (like much of DWC) are summary data. Arctos can have much more detailed information, and we don't have to confound what someone said with the latest geo chart and etc. We can definitely do a better job of summarizing what's in Arctos as DWC (or request revisions to DWC is we can't), but I don't think the Arctos model is missing anything or could be simplified without losing anything.

**Comment by Jegelewicz** [comment]
This earliest and latest are ranges, which may not exist in a lot of cases, but sometimes do. The example given in https://github.com/ArctosDB/arctos/issues/2094#issuecomment-495293051 contains a range in the Stage - it is between Hauterivian and Barremian, why wouldn't we pass it that way?

**Comment by dustymc** [comment]
Ping @tucotuco - can you talk to digir_query.ipt_view_too?

**Comment by tucotuco** [comment]
Yes, sure can. I made a fake resource and looked at what gets mapped
automatically. It looks like the IPT doesn't understand dcterms:x, but does
understand and map the x part, so better if the SQL contains those field
names without the namespace.

Two other fields didn't map, GRBIO_COLLECTION_ID and GRBIO_INSTITUTION_ID.
Did you name them that so we wouldn't map them to collectionID and
institutionID. If not, can you change the names to match DwC? We need the
collection ID at least to construct the SQL for distinct collections.

**Comment by dustymc** [comment]
>dcterms

Gone

>GRBIO_...

I probably just read your table backwards - I try not to activate my brain too close to that stuff anyway....

filtered_flat.collection_id is now mapped to collectionID,

replace(replace(INSTITUTION_ACRONYM,'Obs'),'UAMb','UAM') was mapped to institutionCode - it's now just  INSTITUTION_ACRONYM, the bad translation is from the old days and can be changed by the collections (who should all be reviewing their metadata anyway) as desired.

Try the map one more time please.

**Comment by tucotuco** [comment]
Mapping tried again and works beautifully. One one term doesn't map
automatically - IDVERIFICATIONSTATUS. Should we transition to use
ipt_view_too? Maybe test a small dataset by publishing it anew?

**Comment by dustymc** [comment]
>IDVERIFICATIONSTATUS

Yea, I could find no way around the current character limit, sorry.

No don't map yet - I'll somehow make it faster first.

**Comment by dustymc** [comment]
Built three new tables which refresh themselves the night of every 26th/morning of 27th.

```
UAM@ARCTOS> select count(*) from digir_query.oldoccurrenceIDs;

  COUNT(*)
----------
   3722187

UAM@ARCTOS> desc  digir_query.oldoccurrenceIDs;
 Name								   Null?    Type
 ----------------------------------------------------------------- -------- --------------------------------------------
 OCCURRENCEID								    VARCHAR2(148)
 RELATEDRESOURCEID							    VARCHAR2(130)
 RELATIONSHIPOFRESOURCE 						    CHAR(6)
 COLLECTIONID							   NOT NULL NUMBER

UAM@ARCTOS> select count(*) from digir_query.occurrence;

  COUNT(*)
----------
   3722198


UAM@ARCTOS> desc digir_query.occurrence;
 Name								   Null?    Type
 ----------------------------------------------------------------- -------- --------------------------------------------
 COLLECTIONID							   NOT NULL NUMBER
 LANGUAGE								    CHAR(2)
 LICENSE								    VARCHAR2(4000)
 BASISOFRECORD								    VARCHAR2(17)
 RECORDEDBY								    VARCHAR2(4000)
 INFORMATIONWITHHELD							    VARCHAR2(4000)
 INDIVIDUALCOUNT							    NUMBER
 MODIFIED								    DATE
 ASSOCIATEDOCCURRENCES							    VARCHAR2(4000)
 REFERENCES								    VARCHAR2(102)
 OCCURRENCEREMARKS							    VARCHAR2(4000)
 TYPESTATUS								    VARCHAR2(4000)
 ASSOCIATEDTAXA 							    VARCHAR2(4000)
 OTHERCATALOGNUMBERS							    VARCHAR2(4000)
 ORGANISMID								    VARCHAR2(102)
 CATALOGNUMBER								    VARCHAR2(67)
 ASSOCIATEDSEQUENCES							    VARCHAR2(4000)
 RECORDNUMBER								    VARCHAR2(4000)
 FIELDNUMBER								    VARCHAR2(4000)
 SEX									    VARCHAR2(4000)
 LIFESTAGE								    VARCHAR2(4000)
 DYNAMICPROPERTIES							    VARCHAR2(4000)
 IDENTIFICATIONREMARKS							    VARCHAR2(4000)
 FAMILY 								    VARCHAR2(4000)
 HIGHERCLASSIFICATION							    VARCHAR2(4000)
 GENUS									    VARCHAR2(4000)
 IDENTIFICATIONREFERENCES						    VARCHAR2(255)
 IDENTIFICATIONQUALIFIER						    VARCHAR2(25)
 IDENTIFIEDBY								    VARCHAR2(4000)
 TAXONRANK								    VARCHAR2(255)
 KINGDOM								    VARCHAR2(4000)
 DATEIDENTIFIED 							    VARCHAR2(22)
 IDVERIFICATIONSTATUS							    VARCHAR2(255)
 NOMENCLATURALCODE							    VARCHAR2(4000)
 PREPARATIONS								    VARCHAR2(4000)
 class									    VARCHAR2(4000)
 order									    VARCHAR2(4000)
 PHYLUM 								    VARCHAR2(4000)
 SCIENTIFICNAME 							    VARCHAR2(255)
 SPECIFICEPITHET							    VARCHAR2(4000)
 INFRASPECIFICEPITHET							    VARCHAR2(4000)
 PREVIOUSIDENTIFICATIONS						    VARCHAR2(4000)
 ASSOCIATEDMEDIA							    VARCHAR2(121)
 TYPE									    VARCHAR2(14)
 SAMPLINGPROTOCOL							    VARCHAR2(4000)
 ESTABLISHMENTMEANS							    VARCHAR2(60)
 LOCATIONACCORDINGTO							    VARCHAR2(4000)
 GEOREFERENCEDBY							    VARCHAR2(4000)
 GEOREFERENCEDDATE						   NOT NULL DATE
 HABITAT								    VARCHAR2(4000)
 GEOREFERENCEVERIFICATIONSTATUS 				   NOT NULL VARCHAR2(60)
 EVENTREMARKS								    VARCHAR2(4000)
 GEODETICDATUM								    VARCHAR2(55)
 VERBATIMEVENTDATE							    VARCHAR2(60)
 VERBATIMLOCALITY							    VARCHAR2(4000)
 VERBATIMCOORDINATESYSTEM						    VARCHAR2(20)
 EVENTDATE								    VARCHAR2(88)
 EVENTTIME								    VARCHAR2(45)
 DAY									    VARCHAR2(8)
 MONTH									    VARCHAR2(8)
 YEAR									    VARCHAR2(16)
 ENDDAYOFYEAR								    NUMBER
 VERBATIMCOORDINATES							    VARCHAR2(255)
 COORDINATEUNCERTAINTYINMETERS						    NUMBER
 DECIMALLATITUDE							    NUMBER
 DECIMALLONGITUDE							    NUMBER
 LOCALITY								    VARCHAR2(255)
 GEOREFERENCEPROTOCOL							    VARCHAR2(255)
 GEOREFERENCESOURCES							    VARCHAR2(4000)
 MINIMUMDEPTHINMETERS							    NUMBER
 MAXIMUMDEPTHINMETERS							    NUMBER
 MINIMUMELEVATIONINMETERS						    NUMBER
 MAXIMUMELEVATIONINMETERS						    NUMBER
 LOCATIONREMARKS							    VARCHAR2(4000)
 CONTINENT								    VARCHAR2(50)
 COUNTRY								    VARCHAR2(50)
 COUNTY 								    VARCHAR2(50)
 ISLAND 								    VARCHAR2(50)
 ISLANDGROUP								    VARCHAR2(50)
 WATERBODY								    VARCHAR2(50)
 STATEPROVINCE								    VARCHAR2(75)
 HIGHERGEOGRAPHY							    VARCHAR2(255)
 INSTITUTIONCODE							    VARCHAR2(20)
 COLLECTIONCODE 							    VARCHAR2(50)
 EARLIESTERAORLOWESTERATHEM						    VARCHAR2(4000)
 EARLIESTEONORLOWESTEONOTHEM						    VARCHAR2(4000)
 EARLIESTEPOCHORLOWESTSERIES						    VARCHAR2(4000)
 EARLIESTAGEORLOWESTSTAGE						    VARCHAR2(4000)
 EARLIESTPERIODORLOWESTSYSTEM						    VARCHAR2(4000)
 FORMATION								    VARCHAR2(4000)
 group									    VARCHAR2(4000)
 MEMBER 								    VARCHAR2(4000)
 OCCURRENCEID								    VARCHAR2(148)
 INSTITUTIONID								    VARCHAR2(60)
 ACCESSRIGHTS								    CHAR(39)



UAM@ARCTOS> select count(*) from digir_query.audubonmedia;

  COUNT(*)
----------
    724012

UAM@ARCTOS> desc digir_query.audubonmedia;
 Name								   Null?    Type
 ----------------------------------------------------------------- -------- --------------------------------------------
 COLLECTIONID							   NOT NULL NUMBER
 OCCURRENCEID								    VARCHAR2(148)
 IDENTIFIER								    VARCHAR2(76)
 TYPE								   NOT NULL VARCHAR2(255)
 TITLE									    VARCHAR2(4000)
 MODIFIED								    DATE
 WEBSTATEMENT								    VARCHAR2(255)
 SOURCE 								    VARCHAR2(76)
 CREATOR								    VARCHAR2(4000)
 DESCRIPTION								    VARCHAR2(4000)
 CREATEDATE								    VARCHAR2(4000)
 ACCESSURI								    VARCHAR2(76)
 FORMAT 							   NOT NULL VARCHAR2(255)
 FURTHERINFORMATIONURL							    VARCHAR2(76)

```
