### ISSUE TITLE
please add "horn" to part_name (Mamm)

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#2162]
**Table**
http://arctos.database.museum/info/ctDocumentation.cfm?table=CTSPECIMEN_PART_NAME

**Value**
horn

**Definition**
permanent projection on the head consisting of bony core surround by a keratin sheath, found in various ruminant artiodactyls of the families Bovidae and Antilocapridae 

**Collection type**
Mamm

**Part tissue flag**
no

**Priority**
whenever you get around to it

**Comment by Jegelewicz** [comment]
@ebraker when you have a horn, do you have the "bony core surround by a keratin sheath" or just the "keratin sheath"?

**Comment by ewommack** [comment]
Oooh good question @Jegelewicz! What are you thinking of for them @ebraker ? I have a number of _Antilocapra americana_ skulls with keratin sheaths that accompany the skull.

**Comment by Jegelewicz** [comment]
Yep.

We have these two parts already:

Part Name | Collections | Is Tissue? | Definition
-- | -- | -- | --
horn | ES 						 							Mamm 						 							Teach | no | a permanent projection on the head of an animals consisting  of a covering of keratin and other proteins surrounding a core of live  bone
horn core | ES | no

Which I think we should change to:

Part Name | Collections | Is Tissue? | Definition
-- | -- | -- | --
horn | ES 					 							Mamm 						 							Teach | no | a permanent projection on the head of an animals consisting of a sheath of keratin and other proteins that once surrounded a core of live bone
horn core | ES 					 							Mamm 						 							Teach | no | a permanent projection on the head of an animals consisting of a core of bone that was once surrounded by a sheath of keratin and other proteins

Other suggestions?

**Comment by ebraker** [comment]
In our case it would be either a horn sheath or a bone core with a sheath on it. We don't have any bone cores without a sheath that aren't attached to a skull. I think your proposed verbage works @Jegelewicz but if it were up to me I would probably just simplify and use "horn" and then in part_remarks state if it were only a sheath rather than using two parts, "horn" and "horn core", to describe a single specimen (but I also tend towards simplifying all of our skeletal parts and don't itemize by bones by name unless I have to). I'm open to anything, as long as we get some form of "horn" in Mamm collections!

**Comment by Jegelewicz** [comment]
> I also tend towards simplifying all of our skeletal parts and don't itemize bones by name unless I have to

Paleo collections can have the horn core detached from the skull, so I think I'll stick with this.
