### ISSUE TITLE
Specimen event bulkload error

### ISSUE THREAD

**Issue by anna-chinn** [ArctosDB/arctos#2164]
**Describe the bug**
I just for this error as I was trying to bulkload specimen events and I am not sure what is going wrong:

> trigger 'UAM.TRG_CF_TEMP_SPECEVENT_BIU' is invalid and failed re-validation

![Capture](https://user-images.githubusercontent.com/40321380/61175338-17c32d80-a573-11e9-9e7d-a1064300f61a.JPG)

Any help is very appreciated!

** Data**
[Baker 1911 Dates2.xlsx](https://github.com/ArctosDB/arctos/files/3389117/Baker.1911.Dates2.xlsx)

**Desktop (please complete the following information):**
 - Windows 10, Google Chrome

**Additional context**
I just used the temporary locality naming tool for the first time and it works great.

**Comment by dustymc** [comment]
Should be fixed - I missed a bit when moving WKT to Media.
