### ISSUE TITLE
Another new Low Quality Data report

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2166]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html
From last Taxonomy Committee Meeting

**Is your feature request related to a problem? Please describe.**
Name in names list doesn't match scientific name in classification

**Describe the solution you'd like**
Low quality data report when name in names list doesn’t match appropriate name in classification?

**Describe alternatives you've considered**
Stumble upon them

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
This should be impossible now - a report isn't needed. ("display_name" took over the 'type taxon_term.scientific_name' functionality.)

Here are the few stragglers.

```
Diaperia verna var. verna
Diaperia verna var.verna
Arctos Plants

Anastrophyllum donnianum
Anastrophyllum donianum
Arctos Plants

Eurhynchiastrum pulchellum
Eurhynchium pulchellum
Arctos Plants

Taraxacum antarctica
Taraxacum Antarctica
Arctos Plants

Taraxacum borealia
Taraxacum Borealia
Arctos Plants

Kobresia simpliciuscula subsp. subholarctica
Kobresia simpliciuscula subsp. subholarctic
Arctos Plants

```

**Comment by Jegelewicz** [comment]
Did you already fix them?

**Comment by dustymc** [comment]
No but I can. It's not 100% clear to me if eg Eurhynchium pulchellum is a typo or some attempt at a correction or reidentification. I suppose the history is documented here now....I'll just update them all to taxon_name.scientific_name.

**Comment by Jegelewicz** [comment]
Thanks.
