### ISSUE TITLE
unaccepted events

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#2169]
From ABJ:

- stuff gets loaded in bits-n-pieces
- 'multiple events' in various places is confusing (and hopefully mostly unnecessary) when n-1 are just unaccepted variants of The One True Event

> i dont' like having in the Specimen Results page a link that says '2 Events' beneath the catalog number link in the GUID column

Suggestion: add a ".. and verificationstatus != unaccepted" clause to the event-counter query, so specimens with one not-unaccepted event won't get anything special on that page. That may not be perfectly accurate depending on what happens below, but I think it's close enough for there.

>Instead of having in the location box of the specimen record page: Location (2 Events) [ expand ]

>Have Location, the Berkeley mapper link, then the event information of the most recent event, and beneath that a link that says something like 'This specimen has been previously associated with other events.' Clicking on that link could expand the box so that it scrolls the way it does now.

>At the very least, the most recent event associated with that record should be at the top of the list in the location box. 

It's not quite that simple for some specimens - events can be much more than just hypotheses regarding The One True Event, and a specimen can have any number of not-unaccepted relevant-for-some-users events. Events are sorted by a fairly complicated formula that includes verificationstatus, event type, etc. That stuff all has to keep working, but I don't think it has to control what happens for a 'got better locality data' specimen either.

* We could add ".. and verificationstatus != unaccepted" to that counter as well, but that might be weirder than specimenresults, depending on what else happens here.
* We could remove unaccepted events from that view altogether (I think we have before), but that'll remove any possibility of a user reporting an obvious error and make it a bit more difficult for "us" to find legacy data.
* We could (as suggested) somehow default-collapse unaccepted events, but the 'previously...' vocabulary probably isn't quite waffly enough to encompass all the reasons an event may be unaccepted.

Help!

https://github.com/ArctosDB/arctos/issues/1006 is semi-related.

**Comment by anna-chinn** [comment]
> We could add ".. and verificationstatus != unaccepted" to that counter

I find it a little confusing to see the unaccepted events in tally and wouldn't miss them if they were omitted from the counter. What was the original impetus for displaying the counter on specimen results?
Would adding qualifiers to the event counter in specimen results help clarify things (e.g. '1 accepted event, 1 unverified event')?

Personally, I like being able to see the unaccepted events side by side with the other events on a specimen record page. It helps me ground my understanding of how the locality stack got to where it is now and helps me pin point errors/discrepancies that exist between events. For that reason, I don't like the idea of hiding the unaccepted events altogether.
Default collapsing unaccepted events seems like a good way to avoid confusion for non-operator users. We could use more general language like "Click to view all events associated with this specimen"?

**Comment by campmlc** [comment]
I agree that the most recent accepted event should be the one displayed,
and agree with Anna about default collapsing unaccepted events with an
option and general language to view. Ditto for part attributes and other
visually confusing aspects of the specimen record page. I can also do
without the unaccepted event counter.

**Comment by dustymc** [comment]
>adding qualifiers to the event counter

That's a little more expensive query (I don't think we have to care), a little more likely to melt browsers (most of the processing happens there), and potentially a lot more cluttered. Looks like we currently have 6 event-types, and who knows what the future is going to hold.

**Comment by AJLinn** [comment]
> We could (as suggested) somehow default-collapse unaccepted events, but the 'previously...' vocabulary probably isn't quite waffly enough to encompass all the reasons an event may be unaccepted.

As long as we don't pull the "unverified" events into this hide/don't hide/collapse scenario (nearly all ~16,000 records of UAM:EH are unverified - I'm working on it!).

And a reminder that cultural objects _should_ always have at least 2-3 kinds of events with each object (manufacture/collection/use) and please don't do anything that further minimizes the appearance of these distinct locations & dates. This is how we track the "social life of the object," otherwise known as the provenance. It is also important for the fine art collections, which may have a number of "use" locations over the life of an artwork.

AFWIW, I like seeing the multiple events note on the search results view as it gives me an immediate snapshot if I need to go into that record and update the events to add missing ones (which is a bit of a task in some cases so I like to be mentally prepared for that).

**Comment by Jegelewicz** [comment]
> i dont' like having in the Specimen Results page a link that says '2 Events' beneath the catalog number link in the GUID column

> AFWIW, I like seeing the multiple events note on the search results view as it gives me an immediate snapshot if I need to go into that record and update the events to add missing ones (which is a bit of a task in some cases so I like to be mentally prepared for that).

It seems like more information is better, even if it is confusing. Can that link go anywhere else?

**Comment by dustymc** [comment]
@AJLinn I think "unverified" is safe - it should be everyone's default state.

Cultural data are a large (not the only) part of the reason the sort is much more complex than 'last not-unaccepted at top.'

>immediate snapshot if I need to go into that record and update the events to add missing ones

I think that's an argument for removing 'unaccepted' events from the count??

> Can that link go anywhere else?

Yes, it's asynchronously injected after the page loads, I can do about anything with it.

**Comment by Jegelewicz** [comment]
>     Can that link go anywhere else?
> 
> Yes, it's asynchronously injected after the page loads, I can do about anything with it.

Would it make ABJ any happier if it was under locality (I think that makes some sort of sense?) or had it's own column (is that even possible?)?

Or would just removing "unaccepted" events from the count be the best solution?

**Comment by dustymc** [comment]
>under locality 

I don't think there's an always-on locality-column, and the initial request (from @jldunnum I believe) was to alert users that there's more locality data than they can see in this table. I think **most** users have specloc on and that might be close enough anyway....

>own column

It would have to be an always-on thing that would eat a lot of screen for no reason for most specimens.

>removing "unaccepted" events from the count 

I think that's what I'm hearing.
