### ISSUE TITLE
A {string} at GBIF

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2172]
Using http://arctos.database.museum/guid/CHAS:Inv:1909.2954.1 as an example, when the A {string} formula is used, this is what shows up at GBIF:

![image](https://user-images.githubusercontent.com/5725767/61412216-866ef680-a8a5-11e9-9202-c5d358cf8828.png)

DWC for Identification Qualifier is "A brief phrase or a standard term ("cf.", "aff.") to express the determiner's doubts about the Identification."

No one is going to know what A {string} means. When the A {string} formula is used, then the string should be the qualifier, or given the record from which the above was taken, the whole identification (the entire A {string}) might even be better. So while this item is identified as the genus Galba, it has the qualifier of species name Galba umbilicata.

Possible? what other considerations should be made for A {string}?

**Comment by Jegelewicz** [comment]
Related to #2160

**Comment by Jegelewicz** [comment]
See also https://github.com/ArctosDB/arctos/issues/1304#issuecomment-492349155

**Comment by dustymc** [comment]
>No one is going to know what A {string} means.

That's why it exists!

This one is weird (or not weird, which is weird); the string looks like (might even be) a name, but they chose this approach instead of potentially adding garbage to taxonomy.

This should not be represented as a "species" even if it looks like one. It is very explicitly just a string with a sorta-fuzzy relationship taxa (one of which isn't really a taxon).

I can do whatever in DWC, but this should never be viewed as anything except an identification string only peripherally involving taxonomy.

**Comment by anna-chinn** [comment]
We went with A-string identifications where taxon names didn't exist in Arctos and we couldn't validate the names with some external service. The idea is to (eventually...) go through all the A-strings systematically, add the names that are legit, and update where we can.

Not all of our A-strings are actually species names (some sub-genera got misinterpreted among other things). Is there a way we could say 'A-string' that might clarify identifications to folks downloading data from GBIF? Something like 'Text-based identification'? It's hard to imagine something concise but functionally more clear than 'A-string'...

**Comment by dustymc** [comment]
>Text-based identification

Works for me!

**Comment by Jegelewicz** [comment]
> DWC for Identification Qualifier is "A brief phrase or a standard term ("cf.", "aff.") to express the determiner's doubts about the Identification."

We use these and they all appear odd at GBIF:

http://arctos.database.museum/guid/UTEP:Mamm:1140 uses A sp., which to me would indicate the qualifier should be "sp.", but instead it is "A sp." 

![image](https://user-images.githubusercontent.com/5725767/65191437-2f1a0d80-da31-11e9-99eb-b7bdbc994450.png)

No one outside of Arctos will get the "A" part of that.

Ditto for any cf.
http://arctos.database.museum/guid/UTEP:ES:1-1022 begets "A cf."

![image](https://user-images.githubusercontent.com/5725767/65191581-a8b1fb80-da31-11e9-815d-4e8a25a67aae.png)

Even a normal taxon name like that in http://arctos.database.museum/guid/UTEP:Mamm:300 ends up with the qualifier "A" at GBIF.

![image](https://user-images.githubusercontent.com/5725767/65191743-355cb980-da32-11e9-92f7-9b41d32cceda.png)

Can we lose the "A " in the qualifier for the following when passed to aggregators? Or perhaps pass the definition instead of the formula. It seems that information would be far more useful.

Formula | Definition
-- | --
A | The normal, single-taxon determination. This could be a  high-level taxon (e.g., Canidae), a genus (e.g, Canis), a binomen e.g.,  Canis lupus), or a trinomen (e.g., Canis lupus baileyi).
A ? | A single-taxon determination with a space and question mark  appended to it. For example, "Canis ?" indicates that the organism is  questionably assigned to the genus Canis. (Compare the formula "A sp.")
A aff. | A "species affinis." Related to, but NOT identical to the  species named.  This is generally (if not always) used with a binomen.  And this would generally be a fine-grained, expert determination. It is  NOT the species named, it is not "approximately" the species named.
A cf. | A determination based on comparison to another specimen.  It  implies that that the two specimens are the same taxon, but that the  determiner has no other basis for the determination. This determination  is only as good as the other determination. (Not the same as the formula  "A ?".)
A sp. | A single-genus determination with a space and "sp." appended  to it.  For example, "Canis sp." indicates that the specimen is some  unknown species of the genus Canis. (Compare the formula "A ?")
A ssp. | A genus+species determination (binomen) with a space and  "ssp." appended to it.  For example, "Canis lupus ssp." indicates that  the specimen is some unknown subspecies of Canis lupus. (Compare the  formula "A sp.")
A {string} | Allows the user to supply a namestring. To be used only when no better formal taxon name is available.

The definition would also be helpful for "A / B intergrade", "A or B", and "A x B"

**Comment by Jegelewicz** [comment]
AWG agrees that what ends up at aggregators is odd. Would prefer that the modifier is what shows up. For most, this is easy, just remove the A and return the rest. For A {string} however, it would be preferable to return the actual string.

**Comment by dustymc** [comment]
>modifier is what shows up

That's not really what we have and I don't think it's appropriately mapped. If there a better way to share these data with DWC? What do we get by sharing them at all?

>For A {string} however, it would be preferable to return the actual string.

The identification modifies itself?

There are few of these, they could just be a CASE statement.

 A x B --> IDK, there's nothing I'd consider a modifier here
 A or B --->one of two? Still not a modifier....
 A-->NULL
 A ? --> questionable (this should be removed in favor of https://arctos.database.museum/info/ctDocumentation.cfm?table=ctidentification_confidence)
 A cf. --> conferatur
 A {string} --> IDK, not really a modifier, could be any kind of modifier
 A ssp. --> evil denormalizer
 A aff. --->affinis
 A / B intergrade--->hybrid (which also isn't a modifier, it's just complexity)
 A and B -->IDK, not a modifier

**Comment by Jegelewicz** [comment]
see also https://github.com/tdwg/dwc/issues/244

**Comment by Jegelewicz** [comment]
closing as duplicate/related to #2680
