### ISSUE TITLE
A {string} within Arctos

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2173]
While looking at how A {string} identification appear in GBIF, @campmlc also questioned their appearance in Arctos. Using the same record as an example: http://arctos.database.museum/guid/CHAS:Inv:1909.2954.1

![image](https://user-images.githubusercontent.com/5725767/61412777-f92ca180-a8a6-11e9-8b5b-f45dd98d43c2.png)

I knew that the part of the identification in black was the string, but that probably isn't apparent to anyone outside of Arctos (or even those Arctos users who have never used A {string}). If you select the highlighted text you are taken to the classification for the genus Galba, but you might be expecting to get the species _Galba unbilicata_.  Perhaps we need to signify the identification qualifier in a more formal way? See #2172

**Comment by dustymc** [comment]
The ID is a string loosely built on a data object. If the ID string shares the namestring of the data object, I build a link. I'm not sure how else that could be handled??

There's absolutely no such thing as "identification qualifier" in Arctos - the formulae just make it easy to pass around complex data involving possibly-multiple related data objects as compact strings. They could almost be discarded once the ID is formed; they've (almost) done their job. (They're still useful for making links and such, I'm not actually suggesting we get rid of anything, but they should not be given too much value either.)
