### ISSUE TITLE
Searching on identification vs. taxonomy

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2174]
Using an A {string} identification as an example: http://arctos.database.museum/guid/CHAS:Inv:1909.2954.1

A search for the identification _Galba unbilicata_ gets the expected results (all 7 specimens with this identification), but a search for the species _Galba unbilicata_ does not (zero results). I know why this is true, but someone from outside of Arctos may not. Should we have some sort of explanation of the difference in searching by identification and taxonomy? Just a sentence or two between Id Remarks and Kingdom on the search page might help or maybe we just split searching by identification and taxonomy into two separate boxes?

**Comment by dustymc** [comment]
http://handbook.arctosdb.org/how_to/How_to_Search_for_Specimens_with_Identification_and_Taxonomy.html

**Comment by sharpphyl** [comment]
I agree that we don't need to take action but I don't understand why anyone would use A {string} if they want their specimens to be as discoverable as possible.  Maybe we should make a stronger caution about using A {string} in data entry.  Currently at "build" it reads:

A {string} | Allows the user to supply a namestring. To be used only when no better formal taxon name is available.

Should we caution that namestrings may not be discoverable under a species search if that's the problem?

**Comment by dustymc** [comment]
>why anyone would use A {string}

The identification isn't a taxon name.

**Comment by AJLinn** [comment]
> why anyone would use A {string}
> 
> The identification isn't a taxon name.

This is precisely how all cultural items are currently entered into the ID field. Our collections are consistently discovered by our users. I would prefer to not have another warning to confuse my students for yet another workaround needed by the cultural collections.

**Comment by dustymc** [comment]
"Use the most precise/controlled/structured data/value/approach possible" could be in some sort of "intro to Arctos (and anything else of which involves data that you might eventually want to interrogate)," but scattering variations of it around everywhere seems unnecessary to me as well.

The "A {string}" formula was introduced primarily to deal with "working names" - a user has sorted specimens into piles which might eventually be described under new names, for example. Once we get cultural taxonomy into Arctos - and I believe the barriers to that are solely administrative - it should be used for only the same sorts of things regarding cultural items as well (perhaps a new sub-category of item which hasn't yet been formalized to taxonomy).
