### ISSUE TITLE
Error cloning classification

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2177]
Trying to clone a classification into an exisiting name and get this:

![image](https://user-images.githubusercontent.com/5725767/61494278-fe572280-a972-11e9-8e8f-f58ac9c8b368.png)

Name was Lepidostrobus
Cloning from Arctos Plants source

**Comment by Jegelewicz** [comment]
Happens with anything...

**Comment by dustymc** [comment]
@lkvoong can you take a look at this?

**Comment by Jegelewicz** [comment]
It seems to be working when cloning from GBIF

**Comment by lkvoong** [comment]
I added another datafile to the UAM_IDX_1 tablespace.  Can you try again?
