### ISSUE TITLE
redesign specimen bulkloader

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#2178]
* get rid of all parts, attributes, etc. in the specimen bulkloader
* figure out how to seamlessly integrate various 'component loaders'

This would solve all of the "we need one more .... " issues, and the various points of confusion around 'data entry extras.'

Probably needs funding - minimally ~few months of work - would need to move all loaders to common environment, figure out cross-app transactions, build fully dynamic forms, etc. Perhaps good opportunity to rebuild data entry (maybe as something that can run locally and unconnected), etc., etc.

**Comment by campmlc** [comment]
This sounds promising. Can we justify UI / data entry improvements under sustainability? E.g. We've gotten so good at incorporating very diverse data types that we need to adjust the user environment to accommodate new data from new collections, and our old form doesn't work anymore?

**Comment by dustymc** [comment]
>Can we justify UI / data entry improvements 

I think that's something ya'll would have to sell, but it doesn't sound entirely unreasonable to me.

>our old form doesn't work anymore?

I definitely wouldn't put it that way!

If I had to sell this, I'd probably mention the UI as sort of passing details and focus on the implications of scanning barcodes into a controlled environment in the field, or attaching all 397 parasite records to the host, or etc. Not sure how I'd spin that into sustainability though - might be easier as some smaller innovation grant or something??

**Comment by campmlc** [comment]
@Michelle Koo <mkoo@berkeley.edu>

**Comment by Jegelewicz** [comment]
> might be easier as some smaller innovation grant or something??

A PEN to the parasite TCN?

**Comment by campmlc** [comment]
PENs may be defunct now . . . deadline was last Friday.

**Comment by Jegelewicz** [comment]
Dang it!

**Comment by campmlc** [comment]
Yes to this:
general idea of normalizing/modularizing the "loader bits" and just calling
them dynamically to handle whatever sort of crazy comes in

**Comment by dustymc** [comment]
Mostly implemented, closing
