### ISSUE TITLE
Get "entered by" with search results

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2179]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
@dperriguey would like to know who entered data that he is downloading.

**Describe the solution you'd like**
Would it be possible to add an "entered by" field to the options for customizing the search results form?

**Describe alternatives you've considered**
He can download data for each person from their individual agent pages, but that isn't really what he want to do. He wants to look at a set of data and figure out who entered which records.

**Additional context**
<img width="960" alt="Screenshot 2019-07-19 15 49 20" src="https://user-images.githubusercontent.com/5725767/61567505-0aa7b200-aa3d-11e9-99c6-41a23bec6611.png">

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
Technically - sure, you can do it, it's in flat/fitered_flat as ENTEREDBY, just add it to the documentation.

Socially - that's something we've always treated as "internal" and there should probably be a discussion before making it public.

**Comment by Jegelewicz** [comment]
> Socially - that's something we've always treated as "internal" and there should probably be a discussion before making it public.

Possible to make it available only when you have certain permissions?

**Comment by dustymc** [comment]
uhhhh - yea, actually, I think so - but it'll take rebuilding the stuff that rebuilds filtered_flat.

**Comment by Jegelewicz** [comment]
Need a test platform?

**Comment by dustymc** [comment]
Not really - just a couple hours to rewrite some code then 3 or 4 days to grind on FILTERED_FLAT - nobody SHOULD notice, but it never completely works out that way.... 

Just say "go".

**Comment by campmlc** [comment]
I say go as this will help multiple collections and make our data more
awesome :)

**Comment by Jegelewicz** [comment]
Go.

**Comment by dustymc** [comment]
I (sorta...) need something to put in filtered_flat.enteredby.  How about "withheld"?

**Comment by Jegelewicz** [comment]
Encumbered? What do we say when a locality or other stuff is hidden from the public view?

**Comment by dustymc** [comment]
various things - this is slightly different in that we'll always withhold it.

I'll run with "Encumbered" unless someone comes up with a better idea soonish.

```
        CASE WHEN encumbrances LIKE '%mask collector%' THEN 'Anonymous' ELSE collectors END , --collectors

  CASE
            WHEN encumbrances LIKE '%mask part attribute%'
            THEN 'not available'
            ELSE partdetail

  CASE
            WHEN encumbrances LIKE '%mask year collected%'
            THEN replace(ended_date,substr(ended_date,1,4),'8888')
```

**Comment by dustymc** [comment]
This is grinding away.

/remind me to check back in 2 days.

**Comment by dustymc** [comment]
Scrips are done early.  Here's how to add things to specimenresults

<img width="133" alt="Screen Shot 2019-07-24 at 2 24 30 PM" src="https://user-images.githubusercontent.com/5720791/61829909-ce9a9580-ae1e-11e9-946e-54371c1400be.png">

<img width="1345" alt="Screen Shot 2019-07-24 at 2 25 28 PM" src="https://user-images.githubusercontent.com/5720791/61830028-13bec780-ae1f-11e9-934c-85d573be776c.png">
<img width="346" alt="Screen Shot 2019-07-24 at 2 26 25 PM" src="https://user-images.githubusercontent.com/5720791/61830033-15888b00-ae1f-11e9-927f-f9a88d9bd51f.png">

**Comment by Jegelewicz** [comment]
@dperriguey this one's for you - let me know if it is what you need!
