### ISSUE TITLE
What's "Fork-Edit" ???

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#2180]
![Screen Shot 2019-07-19 at 2 33 51 PM](https://user-images.githubusercontent.com/17605945/61569128-6456af00-aa32-11e9-90bb-172502f584fc.png)
What's up with this new feature? Does it mean I can edit this event without having to clone and add new info? Will I be editing the 17 specimens or does this auto=magically pull this off from the others and create all new info?

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/1357#issuecomment-497880332

http://handbook.arctosdb.org/documentation/specimen-event.html#fork-edit-method

>auto=magically

Yup, no scary red warnings==no danger to anything except the current specimen.

**Comment by AJLinn** [comment]
Okay, so looking at the instructions in the documentation, if I use the save option "edit the current specimen_event" I remove the object from the current specimen_event (in this case, 10 other specimens), the link to those other 10 specimens goes away and the new event (date changed, possibly place changed, notes about the new event added) becomes the new collection event and locality - nice and clean?  

The last one I changed I used the "unaccept..." option and see that I now have a dark grey box on the record surrounded in red. That's not what I want to do most of the time.

**Comment by dustymc** [comment]
All yes.

It all really comes down to your curatorial policies, but if you're fixing something minor "edit" is probably safe enough. If you're changing something fundamental (in which you could oopsy the meaning of the data), 'unaccept' leaves a trail.

If you're changing something that affects all 10 of those specimens then the "old" tools are best for the job.

**Comment by AJLinn** [comment]
I love it and fully understand. Thank you!

**Comment by Jegelewicz** [comment]
@AJLinn maybe add to the [How-To](http://handbook.arctosdb.org/how_to/How-to-Create-a-New-Collecting-Event-for-a-Locality.html)?
