### ISSUE TITLE
Write some SQL for me?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2181]
@dustymc can you write me some SQL that will let me pull the following for a given freezer box?

 position, label, barcode (if any)

You can use DGR18808 as a test case.

**Comment by dustymc** [comment]
UAM@ARCTOS> select * from container where barcode='DGR18808';

**Comment by Jegelewicz** [comment]
Got this:
![image](https://user-images.githubusercontent.com/5725767/61571386-6e87a600-aa50-11e9-81a6-229b0e9736d1.png)
Want this:

Position | Barcode | Label
-- | -- | --
1 |   | NK 35994 HY
2 |   | NK 35917 HY
3 |   | NK 35925 HY
4 |   | NK 35991 HY
5 |   | NK 35923 HY
6 |   | NK 35989 HY
7 |   | NK 35928 HY
8 |   | NK 35947 HY
9 |   | NK 35948 HY
10 |   |  
11 |   | NK 35966 HY
12 |   | NK 35936 HY
13 |   | NK 35935 HY
14 |   | NK 35998 HM
15 |   | NK 35883 HY
16 |   | NK 35973 HY
17 |   | NK 36000 HM
18 |   | NK 35954 HY
19 |   | NK 35919 HY
20 |   |  
21 |   | NK 35902 HY
22 |   | NK 35900 HY
23 |   | NK 35929 HY
24 |   | NK 35963 HY
25 |   | NK 35933 HY
26 |   | NK 35977 HY
27 |   | NK 35995 HY
28 |   | NK 35893 HY
29 |   | NK 35879 HY
30 |   |  
31 |   | NK 35978 HY
32 |   | NK 35904 HY
33 |   | NK 35980 HY
34 |   | NK 35881 HY
35 |   | NK 35931 HY
36 |   | NK 35993 HY
37 |   | NK 35946 HY
38 |   | NK 35958 HY
39 |   | NK 35907 HY
40 |   |  
41 |   | NK 35878 HY
42 |   | NK 35895 HY
43 |   | NK 35945 HY
44 |   | NK 35997 HM
45 |   | NK 35880 HY
46 |   | NK 35866 HY
47 |   | NK 35951 HY
48 |   | NK 177429 HY
49 |   | NK 177443 HY
50 |   |  
51 |   | NK 177436 HY
52 |   | NK 177455 HY
53 |   | NK 177445 HY
54 |   | NK 177411 HY
55 |   | NK 177466 HY
56 |   | NK 177430 HY
57 |   | NK 177438 HY
58 |   | NK 177428 HY
59 |   | NK 177461 HM
60 |   |  
61 |   | NK 177405 HY
62 |   | NK 177419 HY
63 |   | NK 177465 HY
64 |   | NK 177444 HY
65 |   | NK 177409 HY
66 |   | NK 177410 HY
67 |   | NK 177435 HY
68 |   | NK 177451 HY
69 |   | NK 177440 HY
70 |   |  
71 |   | NK 177453 HY
72 |   | NK 177434 HY
73 |   | NK 177454 HY
74 |   | NK 177425 HY
75 |   | NK 177404 HY
76 |   | NK 177439 HY
77 |   | NK 177464 HY
78 |   | NK 177401 HY
79 |   | NK 117463 HY
80 |   |  
81 |   | NK 177446 HY
82 |   | NK 177417 HY
83 |   | NK 177432 HY
84 |   | NK 177423 HY
85 |   | NK 177427 HY
86 |   | NK 177403 HY
87 |   | NK 177442 HY
88 |   | NK 177407 HY
89 |   | NK 177462 M
90 |   |  
91 |   |  
92 |   |  
93 |   |  
94 |   |  
95 |   |  
96 |   |  
97 |   |  
98 |   |  
99 |   |  
100 |   |  

Possible?

**Comment by Jegelewicz** [comment]
I wasn't clear - I want that stuff for all of the cryovials in that box...

**Comment by dustymc** [comment]
easy but ONLY works with predictable data:

```
select
  c.barcode vial_bc,
  c.label vial_lbl,
  p.label position_lbl
from
  container b,
  container p,
  container c
where
  b.container_id=p.parent_container_id and
  p.container_id=c.parent_container_id and
  b.barcode='DGR18808'
;
```

**Comment by Jegelewicz** [comment]
Thanks!
