### ISSUE TITLE
Public cannot view recently entered specimens.

### ISSUE THREAD

**Issue by KyndallH** [ArctosDB/arctos#2182]
I entered records on Friday. Saved the results and sent them to the collector who responded this morning that she cannot see them. As of this morning, you cannot see the records unless you are signed in. What gives?

Saved search: https://arctos.database.museum/saved/2019%2E016

View not logged in:
<img width="2082" alt="Screen Shot 2019-07-22 at 12 20 30 PM" src="https://user-images.githubusercontent.com/16887896/61662730-79724e80-ac7b-11e9-8e69-054f29da2086.png">

View logged in:
<img width="2062" alt="Screen Shot 2019-07-22 at 12 22 06 PM" src="https://user-images.githubusercontent.com/16887896/61662737-7e370280-ac7b-11e9-8f9c-6c94900f44a1.png">

**Comment by dustymc** [comment]
You recycled or changed or somehow eviled catalog numbers, right??

Procedure is rebuilt, these should clean themselves up soon if they haven't already.

**Comment by dustymc** [comment]
Oh - and you can always check the flat processing at


<img width="520" alt="Screen Shot 2019-07-22 at 3 34 12 PM" src="https://user-images.githubusercontent.com/5720791/61669791-340f4a80-ac96-11e9-80fb-b95e485a4de2.png">

**Comment by KyndallH** [comment]
Awesome! Yes, the folks gave me crappy lat/longs which I uploaded on Thursday then on Friday after I entered, gave me better ones. So I deleted the records, updated, and re-loaded. They can view them now! Thank you!
