### ISSUE TITLE
Media link for no locality specimens

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#2183]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
When "no locality" localities are merged together, then all the specimens using these localities suddenly get linked to the media that is also listed as having "no locality", even when that media is not related to the specimen. 
![Screen Shot 2019-07-22 at 4 20 06 PM](https://user-images.githubusercontent.com/18562884/61669232-85bad380-ac9c-11e9-867a-3f0e75af43fc.png)
![Screen Shot 2019-07-22 at 4 20 15 PM](https://user-images.githubusercontent.com/18562884/61669235-89e6f100-ac9c-11e9-9190-9316e615bf28.png)

**Describe the solution you'd like**
This seems similar to #1735. Perhaps media should have a separate "no locality" locality that they use that is separate from specimen localities?

**Additional context**
Mostly what I'm worried about is a searcher thinking that the specimen has media associated with it, but it turns out that the link is for completely unrelated information/images/videos/recordings. 

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
Link?? I'm not sure what you're seeing. http://arctos.database.museum/guid/uwymv:bird:1785 looks like this for me.

<img width="688" alt="Screen Shot 2019-07-23 at 7 20 08 AM" src="https://user-images.githubusercontent.com/5720791/61719751-5480e880-ad1a-11e9-8eba-0cc760ecfdb8.png">

**Comment by ewommack** [comment]
I'm talking about the search field that first comes up with the basic list of specimens, and the media links that pop up for them before you click and go into the specimen specific information page:

![Screen Shot 2019-07-22_2png](https://user-images.githubusercontent.com/18562884/61747195-93cf2980-ad5a-11e9-8e19-63df63b2b855.png)

If I do not go to the specimen information page, and instead just click the media link I get taken to a page that looks like this:
![Screen Shot 2019-07-22 at 4 20 15 PM](https://user-images.githubusercontent.com/18562884/61747382-faecde00-ad5a-11e9-8662-139c80e2f443.png)

Is there any way to stop that media link from popping up with the specimen on the basic search spread sheet?

**Comment by dustymc** [comment]
Thanks/got it. Yes it's the same as  #1735, I'll add the same precision-filter.

FWIW it's not "completely unrelated" - they share the same locality data, and in both cases that looks to be unnecessarily imprecise - Google suggests your specimen is probably from North America, the MVZ Images are mostly from California, but they're both recorded as being from "somewhere on the planet, probably."


See also http://handbook.arctosdb.org/documentation/locality.html#specific-locality

>in records for which appropriate data are missing, the correct value for Specific Locality is, “No specific locality recorded.”

**Comment by dustymc** [comment]
precision-filter added

<img width="161" alt="Screen Shot 2019-07-25 at 11 14 28 AM" src="https://user-images.githubusercontent.com/5720791/61898091-6656bd00-aecd-11e9-9323-7a7bf2ab2d4f.png">
