### ISSUE TITLE
Help with a few freezer boxes

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2184]
@dustymc I have three freezer boxes that I need a little help with.

DGR16966
DGR17156
DGR17922

Each of these has a barcode scanned into the box positions. I need to have all of those barcodes (the cryovials) removed from the positions and returned to container label status. None of these cryovial barcodes are associated with parts.

Let me know if you need more info.

**Comment by dustymc** [comment]
I don't see anything in DGR17922

The other 2 are de-tubed.

Here's the code I used, in case it's needed again.

```
--containers in positions in box
select container_id, barcode from container where parent_container_id in (
  select container_id from container where parent_container_id in (
      select container_id from container where barcode='DGR17156'
    )
);

-- containers in containers in positions in box; die if this finds anything
select * from container where parent_container_id in (
  select container_id from container where parent_container_id in (
    select container_id from container where parent_container_id in (
        select container_id from container where barcode='DGR17156'
      )
  )
);

-- move positions in box to parentless 'container label'
update container set parent_container_id=0,container_type='container label' where container_id in (
  select container_id from container where parent_container_id in (
    select container_id from container where parent_container_id in (
        select container_id from container where barcode='DGR17156'
      )
  )
);

```

**Comment by Jegelewicz** [comment]
It's strange, but DGR17156 still has stuff in it even though the positions all appear to be empty?

**Comment by dustymc** [comment]
Oh what the hell.....that transaction is hung up for some reason, I'll dig out my scary password if it doesn't fix itself soon.

/remind me to check back in 3 hours

**Comment by dustymc** [comment]
The lock seems to have got bored and wandered off, so DGR17156 should actually be empty now.

**Comment by Jegelewicz** [comment]
Yay! Thanks!
