### ISSUE TITLE
New Other ID relationship

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#2185]
**Is your feature request related to a problem? Please describe.**
I'm trying to find a good way to direct users to see other items either in our collection or other museum collection databases that are similar to the object record they are viewing or directly associated with that object.

**Describe the solution you'd like**
It seems analogous to the way people are using the field "Associated Species". However, in looking at issues like #2095 or #1100, it seems like when this field is populated it shows up in a specimen event box? I don't want this information over there, I would like it near the specimen remarks, which is where I typically put this info. As you can see below in my screenshot for http://arctos.database.museum/guid/UAM:EH:0236-4079 the remarks field ends up getting really busy and that info gets buried with other content.

**Describe alternatives you've considered**
Maybe we need a new free-text field for cultural collections for "Associated Items" that would be displayed on the object detail page right below the Remarks field? 

Maybe it's a new way to use the other identifiers (without adding every single museum in the world in that dropdown list) with a new relationship that is more to this idea of associated or affiliated item.

Ideally I'd like to directly link to other objects in our collection or other online databases, like we do with media. Sometimes objects come in as an assemblage (e.g. ceremonial items that are used together like masks, headdresses, fans, drums, etc) and there's no real way to indicate these items are used as a unit other than describing them in the remarks field (see http://arctos.database.museum/guid/UAM:EH:UA64-007-0028 and http://arctos.database.museum/guid/UAM:EH:UA64-064-0010).

**Additional context**
![Screen Shot 2019-07-23 at 11 06 04 AM](https://user-images.githubusercontent.com/17605945/61739916-e3512d80-ad39-11e9-9d1c-d75d35ba0f70.png)

![Screen Shot 2019-07-23 at 9 56 44 AM](https://user-images.githubusercontent.com/17605945/61739649-54441580-ad39-11e9-842a-1288e798c7ad.png)

**Priority**
No rush but an enhancement that I think could be used by many.

**Comment by Jegelewicz** [comment]
> Ideally I'd like to directly link to other objects in our collection or other online databases, like we do with media. Sometimes objects come in as an assemblage (e.g. ceremonial items that are used together like masks, headdresses, fans, drums, etc) and there's no real way to indicate these items are used as a unit other than describing them in the remarks field (see http://arctos.database.museum/guid/UAM:EH:UA64-007-0028 and http://arctos.database.museum/guid/UAM:EH:UA64-064-0010).

For things in Arctos, this should be an other id relationship (see the red box in relationships):
![image](https://user-images.githubusercontent.com/5725767/61740225-50b98a00-ad4b-11e9-99c5-753f007171a2.png)

which you assign here:
![image](https://user-images.githubusercontent.com/5725767/61740253-6464f080-ad4b-11e9-89e4-dc67a9abb988.png)

Although, there currently doesn't seem to be an appropriate relationship in the [code table](arctos.database.museum/info/ctDocumentation.cfm?table=ctid_references&field=).

Maybe we need a relationship of "associated object" (need a definition)

This same relationship could be used with stuff outside of Arctos, but it will mean adding appropriate identifiers to the Other ID code table....

**Comment by dustymc** [comment]
Associated species are those noted at a time-place in reference to a specimen - it belongs with specimen-event, and putting it elsewhere would be confusing.

>directly link to other objects in our collection 

That's why http://arctos.database.museum/info/ctDocumentation.cfm?table=CTID_REFERENCES exists. The definition needs generalized, but I think "collected with" might be what you're looking for.

IDs can also link to external resources, IF they have a predictable URL. See for example http://arctos.database.museum/guid/DMNS:Mamm:10169 and https://arctos.database.museum/info/ctDocumentation.cfm?table=CTCOLL_OTHER_ID_TYPE&field=GenBank.  GenBank: AY598242 is entered into the specimen record, the code table knows what to do with that ID type, so the link is magicked from the identifier.

>like we do with media.

"Media" is "something with a URL." Linking a specimen to an external DB that can't be accessed via other identifiers is well within current capabilities.

Dangit @Jegelewicz you beat me to it!

**Comment by AJLinn** [comment]
> Maybe we need a relationship of "associated object" (need a definition)

Yup, I know how to do that but we don't have an appropriate relationship ("associated or similar items") for items cataloged in Arctos. I'd like to create one if people are okay with that. 

> IDs can also link to external resources, IF they have a predictable URL.

So maybe I'd use "institutional catalog number" and then drop in the number, for example, "VI-Q-171" from the Canadian Museum of History? Doesn't seem like that would work in this case since maybe it's not a "predictable URL"? 

> "Media" is "something with a URL." Linking a specimen to an external DB that can't be accessed via other identifiers is well within current capabilities.

Again, we'll need to create an appropriate media relationship that indicates we're showing a "similar or associated" item, not actually the cataloged item, etc. The problem I see here is the reference-out would be buried in the multiple media files and not be a clear reference to "similar items held by other institutions," which is what I want to make obvious. 

> That's why http://arctos.database.museum/info/ctDocumentation.cfm?table=CTID_REFERENCES exists. The definition needs generalized, but I think "collected with" might be what you're looking for.

Yes, maybe, in some cases when we know a collector obtained the mask pair or ceremonial items all at the same time from the same place. Sometimes these things get split up and sold to various people and donated to museums in Russia, England, Alaska, or Washington and we want to reunite them virtually via their records. We might be making assumptions that we can't prove with documentation, but are really just trying to say, "Gee look at these items that look really similar - I wonder if they go together? Or maybe they were made by the same culture group or even by the same artist? Maybe this item with an unidentified function is the same as this piece I found at AMNH or NMAI?" without having documentation to prove it. We can use those other items as backup for our "educated guess" about cultural attribution or geographic attribution for our manufacture event. See what I"m getting at?

**Comment by dustymc** [comment]
>"associated or similar items"

I have no problem with that as long as it can be clearly distinguished from existing relationships. Open a new Issue once everything is finalized and I'll add it to the reciprocal relationship notifications.

>"institutional catalog number" 

That's a garbage can; it can never do anything useful. Do you have an example link to a specimen in an external collection? See also http://handbook.arctosdb.org/documentation/other-identifying-numbers.html

>appropriate media relationship

Note that those are functional - they must end with space-tablename. "associated with cataloged_item" could work. As above, it would need to be clear when to use that vs. other "% cataloged_item" relationships.

>buried in the multiple media files 

That's "just" a UI problem - it should be dealt with separate from the data organization issue(s).

>See what I"m getting at?

Isolated bad. Linked good. https://arctosdb.org/about/details/ecosystem/. Close?

**Comment by Jegelewicz** [comment]
Create new relationships for [Other IDs relationship code table](http://arctos.database.museum/info/ctDocumentation.cfm?table=CTID_REFERENCES)

associated objects: objects that are associated with this object as part of a pair or other grouping

@AJLinn how's this?

**Comment by campmlc** [comment]
Perhaps some clarification that this is primarily for non-biological
relationships? Technically, this definition would apply to a mated pair of
flycatchers, or twin siblings, . .  and we have other relationships for
biological associations, e.g. mate of, sibling of, same lot as, etc.

**Comment by Jegelewicz** [comment]
non-biological specimen objects that are associated with this object as part of a pair or other grouping

**Comment by dustymc** [comment]
@Jegelewicz needs elaboration. It's not "pair" as in "in amplexus with" or "mate of" and not as associated as "collected with" etc.

And less critical I think that needs a preposition for consistency - 'associated with'??

@campmlc I don't think that's necessary - 2 critters that have SOMETHING vague to do with each other might use this, although I can't think of a hypothetical at the moment....

**Comment by campmlc** [comment]
Associated with would work, but I want to make sure it doesn't become a
garbage basket category that could potentially replace or be confounded
with other categories of biological relationships. Restricting it to
non-biological relationships would force people to use more explicit
biological context. How associated? collected with? Why not use that?

**Comment by dustymc** [comment]
>garbage basket category 

Well it sort of would be, as the least specific relationship. But yea, it should not be used when something more specific is appropriate - same as all other relationships.

>Why not use that?

Documentation, which should be very clear regarding the usage of the most specific available term (everywhere, not just here).

**Comment by Jegelewicz** [comment]
associated with - objects that are associated with this object (do not use this if a more refined relationship is more applicable)

**Comment by campmlc** [comment]
How about "more explicit relationship".

**Comment by AJLinn** [comment]
> Do you have an example link to a specimen in an external collection?

Keeping with this spoon example, i found this item at CMH:https://www.historymuseum.ca/collections/artifact/37452/?q=sheep+horn+spoon&page_num=4&item_num=11&media_irn=47952.

Referencing this spoon helps give more weight to the added ID of this UAMN spoon: http://arctos.database.museum/guid/UAM:EH:0236-4079 as having a culture of origin of Southern Tutchone vs. Ahtna Athabascan (helps clarify why I have 2 cultures of origin in attributes).

Another example:
http://arctos.database.museum/guid/UAM:EH:UA2019-014-0001
was cited as being similar to this piece by the donor at the Smithsonian:
http://n2t.net/ark:/65665/3d5c7fb75-2b8d-4ebe-967e-0d3d2acf3f43
This connection helps us figure out the possible function of the piece, a cultural tradition of making human forms into useful items, etc.,  and might help give weight to a provenience of similar location (e.g., Bering Strait, as opposed to Arctic Slope, etc) and links the donor's attempt at IDing the piece prior to donation.

For the other ID relationship, how about this:
"associated with" - cultural item that is associated with or to this object; possibly part of an original assemblage (do not use if a more explicit relationship is applicable, e.g., "collected with")

**Comment by Jegelewicz** [comment]
For the first example, you can also get to this item with: https://www.historymuseum.ca/collections/artifact/37452

If you create an other ID = CMH:Canadian Museum of History and add https://www.historymuseum.ca/collections/artifact/ to the base uri, then on the appropriate specimen add the Other ID CMH: Canadian Museum of History = 37452 with the relationship we decide on, then there will be a hot link between the records.

> "associated with" - cultural item that is associated with or to this object; possibly part of an original assemblage (do not use if a more explicit relationship is applicable, e.g., "collected with")

I'm good with that!

**Comment by Jegelewicz** [comment]
Wait! Perhaps you should have two different relationships?

"associated with" - cultural item that is associated with or to this object (do not use if a more explicit relationship is applicable, e.g., "collected with")

"same assemblage as" - cultural item that is part of an original assemblage

**Comment by AJLinn** [comment]
> For the first example, you can also get to this item with: https://www.historymuseum.ca/collections/artifact/37452

How did you find that direct link? I couldn't figure it out!

> "associated with" - cultural item that is associated with or to this object (do not use if a more explicit relationship is applicable, e.g., "collected with")

"same assemblage as" - cultural item that is part of an original assemblage

Again, these would be great if we know for sure... but we might be making assumptions by using this.

**Comment by Jegelewicz** [comment]
I just figured the cat number would be enough - it was a wild guess!

**Comment by dustymc** [comment]
> item at CMH

That's probably a job best done by Media. I think 37452 is just some random number (maybe a DB key) and not a real identifier so the link would probably eventually rot. If that's actually an identifier then what Teresa said.

The SI link is also weird, but in a good way - ARKs are persistent identifiers (eg, if they get a new URL they can just point the ARK to it). There's some structure to ARK so it's possible to do it the normal way, but I'm tempted to just enter the whole thing as the ID with no base_url and I'll adjust the UI to HTML-wrap. Otherwise you're going to be guessing where the 'base' stops and the 'identifier' starts, and that's not really accurate anyway - ARKs ARE identifiers, not components of identifiers.

>"associated with" - cultural item 

I'd still lose the 'cultural.'

>"same assemblage as" 

How's that not 'same individual as' (other than working better for plants and corals and such...)?

**Comment by Jegelewicz** [comment]
For Canadian Museum you could also weasel it out of their search:

https://www.historymuseum.ca/collections/search-results/?q=VI-Q-171

So base uri could be https://www.historymuseum.ca/collections/search-results/?q=

Other ID = VI-Q-171

VI-Q-171 is the object number. You don't get to the object page, but you get a search result that gets you there with one click....

**Comment by Jegelewicz** [comment]
>     "same assemblage as"
> 
> How's that not 'same individual as' (other than working better for plants and corals and such...)?

Honestly, I thought it was more akin to "same lot as"

**Comment by Jegelewicz** [comment]
> The SI link is also weird, but in a good way - ARKs are persistent identifiers (eg, if they get a new URL they can just point the ARK to it). There's some structure to ARK so it's possible to do it the normal way, but I'm tempted to just enter the whole thing as the ID with no base_url and I'll adjust the UI to HTML-wrap. Otherwise you're going to be guessing where the 'base' stops and the 'identifier' starts, and that's not really accurate anyway - ARKs ARE identifiers, not components of identifiers.

We already have the ARK Other ID. Could @AJLinn just add that to the record to make the connection? What does it do?

**Comment by AJLinn** [comment]
> "same assemblage as"
> 
> How's that not 'same individual as' (other than working better for plants and corals and such...)?

A cultural assemblage could be a pair of boots and a parka made by the same person to be worn as an outfit. It might be a group of masks that look nothing alike but are part of a story told during a ceremony. It could be a headdress and dance gauntlets worn by a dancer during a particular dance. It could be a seal oil lamp plus it's stand and other associated items.

We generally use "lot" to describe a bunch of the exact same things that i don't want to catalog individually (eg., a group of 5 pens that are identical).

**Comment by dustymc** [comment]
>weasel

Assuming VI-Q-171 is something like a persistent unique ID, that is a better approach in that should they get sane URIs at some point we can just change base_URL and everything will work as it should.

>same lot as

Depends if it was collected on the same day. I suppose some things should be both. Getting the feeling that we're eventually going to need to clean-slate all of our relationships....

>ARK Other ID

Yep, that'll work, it just comes with the "where's this end and that start" thing - not sure if that's an actual issue or no. An ID of type ARK value 65665/3d5c7fb75-2b8d-4ebe-967e-0d3d2acf3f43 will get you there though.

**Comment by dustymc** [comment]
>pair of boots and a parka

That sounds like the vague new relationship that we probably need.

One boot of a pair might be closer to "same individual" (which would need a better name).

>bunch of the exact same things

That's the same thing the (mostly fish) biologists do, and where the term came from in Arctos. The "same lot as" relationship exists to maintain the connection when "exact" turns out to wrong and good science demands recataloging one or more of the specimens. It's a wholly administrative relationship; things like 'same individual as' should have some sort of more real connection.

**Comment by AJLinn** [comment]
> One boot of a pair might be closer to "same individual" (which would need a better name).

We take care of this relationship by using letters to designate the various elements (sometimes as actual parts in ARctos, but normally not): http://arctos.database.museum/guid/UAM:EH:0596-0001AB

**Comment by Jegelewicz** [comment]
> 
>     pair of boots and a parka
> 
> That sounds like the vague new relationship that we probably need.

Which is same assemblage as.....

**Comment by dustymc** [comment]
>letters

Note that those are impenetrable to machines. If I want to ask deep questions of Arctos I can follow relationship to bring most anything together, but things like probably-meaningful-to-the-right-human 'relationships' buried in various places are 100% dead ends.

Cataloged items are completely arbitrary - I think cataloging them as one item with two parts is perfectly justifiable, as is cataloging them as two items with some sort of resolvable relationship linking them.

I was thinking more about one boot cataloged in Russia and one in your collection - those would require some sort of relationship to link. (Or Media, which is sort of a soft-link - I MIGHT be able to programmatically follow it to bring everything back together, but it's not really intended for that.)

@Jegelewicz yes that's what I was aiming for, just not sure if we're solid on the name. If so add it to the code table and let me know....

**Comment by Jegelewicz** [comment]
>  cultural item that is part of an original assemblage

How about

part of a machine or object made of pieces fitted together or a work of art made by grouping found or unrelated objects

**Comment by AJLinn** [comment]
> letters
> 
> Note that those are impenetrable to machines

I get that - it's the way we do things in cultural collections world-wide.
We catalog pairs as one record, physically number them with 596-1A and 596-1B. If one piece goes on loan or exhibit, we'd separate them out as two separate parts and barcode / object track accordingly.

> I was thinking more about one boot cataloged in Russia and one in your collection 

YES! Exactly how I'd like to do things! You're exactly right that should be "same individual as" (and yes, we'd appreciate a more culturally-sensitive way of documenting those items, but I get that we can't have it all. :-)

> How about
> part of a machine or object made of pieces fitted together or a work of art made by grouping found or unrelated objects

Sure, that sounds good to me, especially if those works were then sold separately to different people, and later 2 or 3 donated their pieces to the museum and we realized they were originally a single assemblage. What do you think of that example @marecaguthrie and @krgomez?

**Comment by dustymc** [comment]
>loan 

That's precisely why Arctos pioneered loaning (and tracking) parts (=physical THINGS) instead of cataloged item (random thing(s) someone felt like cataloging). 

In any case there's no reason you HAVE to make explicit linkages, but you can if you want and if you do your data will be more capable of answering more questions.

>culturally-sensitive

Yea, the word "individual" just isn't appropriate for much of what's in Arctos - cultural material, colonial organisms, a bunch of weird plant-stuff, ....

**Comment by Jegelewicz** [comment]
>     I was thinking more about one boot cataloged in Russia and one in your collection
> 
> YES! Exactly how I'd like to do things! You're exactly right that should be "same individual as" (and yes, we'd appreciate a more culturally-sensitive way of documenting those items, but I get that we can't have it all. :-)

So what would you normally call them? I would say these AREN'T the same individual. Each boot is separate and might even be constructed of materials from different animals/manufacturing events. I'll make the argument that they too are an "assemblage".....

**Comment by AJLinn** [comment]
> So what would you normally call them? I would say these AREN'T the same individual. Each boot is separate and might even be constructed of materials from different animals/manufacturing events. I'll make the argument that they too are an "assemblage".....

That's not how the makers consider them. They are viewed as a pair, one can't do their job without the other, functionally-speaking. In our universe, it doesn't matter if they're made from different individual animals - each item is made up of multiple different animals (beaver, moose, caribou potentially on a pair of Dene/Athabascan moccasins; cow/calfskin, seal, caribou, hare on a pair of Iñupiaq mukluks) - it's about the people who make them and how they conceive of the items. 

In my view, an assemblage, culturally-speaking, are individual items that can functionally fulfill their individual roles (pair of boots, pair of mittens, a coffee pot, a tea cup, a fork), but are used collectively for synergistic effects (a matched pair of boots, parka, mittens; a tea cup and tea pot; a matched table setting).

> part of a machine or object made of pieces fitted together

I think this previous example would not be an assemblage, as the individual components can't function alone without being part of the whole. Those cogs, wheels, levers would all be considered elements of the whole. Together they make the machine work ("same individual") - alone they're just pieces of interesting shapes. This is how we catalog things like kerosene lamps (http://arctos.database.museum/guid/UAM:EH:UA2013-009-0012AD) for example.

**Comment by Jegelewicz** [comment]
HMMMM - but I feel like no one would call a pair of boots an individual? What would be a better description of that situation?

I see your point on the machine - I just took that straight from the [definition of assemblage](https://www.google.com/search?client=firefox-b-1-d&q=assemblage+definition) to give us a jumping off point. I agree that those would be part of "same individual as".

So how about this:

same assemblage as - an individual item that can functionally fulfill its individual role (e.g. a boot, mitten, tea pot, tea cup, or fork), but is used collectively with other objects for synergistic effects (a matched pair of boots or mittens; a tea cup and tea pot; a matched table setting, or a work of art made by grouping found or unrelated objects)

**Comment by AJLinn** [comment]
> same assemblage as - an individual item that can functionally fulfill its individual role (e.g. a boot, mitten, tea pot, tea cup, or fork), but is used collectively with other objects for synergistic effects (a matched pair of boots or mittens; a tea cup and tea pot; a matched table setting, or a work of art made by grouping found or unrelated objects)

good for me.

**Comment by dustymc** [comment]
I think I'm hearing that we (eventually) need a lot more relationships.

* same individual as --> limited to biological individuals
* same colonial organism-->same tree, different stem (maybe from miles away)
* collected with --> whatever we're doing now, plus things like botanical duplicates (which includes 'same individual as' and 'growing sorta-nearby' and etc.)
* same lot as --> limited to administrative situations (eg, recataloging)
* the boot thing -->similar to "sibling" but no implications of eg, behavior or shared DNA. 
* same assemblage-->not sure I can usefully define this, but one teacup out of a set - I think this should exclude "one boot" which isn't terribly functional by itself, while a teacup is still fully functional even when it's removed from the set.
* associated with--->same-ish sort of something, but not as specific as eg, one teacup of a set and definitely not one boot of a pair

????

**Comment by campmlc** [comment]
I agree with using "same assemblage as". I don't see any reason why we
can't have appropriate terminology for different collection types. We
wouldn't want to force "parasite of" on collections that would normally use
"offspring of", even though technically those could be considered the same
thing . . . :)

**Comment by dustymc** [comment]
>appropriate terminology for different collection types

We can (and should) definitely have SPECIFIC terminology, and that may (or not) fall out more or less along collection/discipline/"traditional" lines. I don't think we have functional "collection types" - all kinds of stuff gets cataloged in all kinds of places for all kinds of reasons, and users should not have to care - they shouldn't have to anticipate our administrative decisions to get what they want. If parasites in a 'parasite collection' are related to hosts via 'bla' and those cataloged in an insect collection are related via 'blaugh' and those cataloged in a mammal collection..... then users can't find them; denormalization/destandardization is evil at any scale. If there's some useful distinction - something users might care about and want to filter on - between 'parasite' and 'offspring' then they should be two non-overlapping terms, and if not they should be merged.

>technically those could be considered the same thing

Easy distinction: Parasites don't feed marbles to the Roomba....

**Comment by AJLinn** [comment]
> same individual as --> limited to biological individuals

yes, but how do we deal with those parts (two boots, or pieces of a Chilkat robe that got cut up and given out at a potlatch, then made into new items which are then accessioned at two different museums?) from a whole that got separated to different museums? Maybe "same individual/original unit as" ?
If we're okay making sub-categories by type of collection, I'd propose: "Refers to a cataloged item that is part of the same original object or unit as the current record. For example, a lamp shade designed to fit onto a kerosene lamp body; elements of a pair of moccasins separated from the original and re-used in a new object; or a pair of individual elements intended to be used as a set (pair of boots, pair of mittens)."

> same colonial organism-->same tree, different stem (maybe from miles away)
> collected with --> whatever we're doing now, plus things like botanical duplicates (which includes 'same individual as' and 'growing sorta-nearby' and etc.)

Yes. Add to definition, "For cultural collections, possibly a group of items purchased from a single artist or culture-bearer at the same time."
 
> same lot as --> limited to administrative situations (eg, recataloging)
> the boot thing -->similar to "sibling" but no implications of eg, behavior or shared DNA.

(See note under same individual)

> same assemblage-->not sure I can usefully define this, but one teacup out of a set - I think this should exclude "one boot" which isn't terribly functional by itself, while a teacup is still fully functional even when it's removed from the set.

Agreed. The "matched pair" that I refer to above means a pair (of boots or of mittens) that is matched with a parka, not to one another (the pair); the lamp with it's pieces and parts. Those are a "functional set" that have to work together to be useful and fulfill their functional intent. 

From Teresa's attempt to define but removing the "pairs" concept: "Refers to an individual item that can functionally fulfill its individual role (e.g. mask, drum, tea pot, tea cup, or fork), but is used collectively with other objects for synergistic effects (a tea cup and tea pot; a matched table setting, a mask and pair of dance fans, or a work of art made by grouping found or unrelated objects). Reciprocal relationship is "same assemblage as"."

> associated with--->same-ish sort of something

Maybe this? "Refers to an item so similar in construction or design to indicate possible direct connection by maker, culture of origin, or place of manufacture. Reciprocal relationship is "associated with"."

**Comment by dustymc** [comment]
>two boots

"same original object as" works for me. I may have flip-flopped in this thread, but "bones from the animal that wore this skin" and "the other half of this pair of boots" (or "a doll made from what used to be the other half of this pair of boots") now seem like two THINGS, whatever we call them.

>collected with... definition..."For cultural collections,

Maybe "cultural items," but the idea works for me.

>same assemblage as
>associated with

Bueno.

**Comment by Jegelewicz** [comment]
>  I think this should exclude "one boot" which isn't terribly functional by itself, 

Sure it is. There are many reasons a person might only need one foot covered... :-)

**Comment by Jegelewicz** [comment]
See #2440
