### ISSUE TITLE
Add multiple Accessions to a Project

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2187]
I'm working on a project and want to add a whole bunch of accessions:

![image](https://user-images.githubusercontent.com/5725767/61836452-7fb02880-ae3d-11e9-9774-5e9c317509a1.png)

Adding them one at a time will take me forever. Can we have check boxes next to each accession in a search and a "select all" option here instead of only being able to pick one?

**Comment by dustymc** [comment]
No technical issues with that, but I'm not sure who would use it?

Maybe a bulkloader would work better?

**Comment by Jegelewicz** [comment]
> No technical issues with that, but I'm not sure who would use it?

Um, me....

> Maybe a bulkloader would work better?

Fine with me - anything so I don't have to click "add" over 400 times....

**Comment by dustymc** [comment]
If it's a one-ish time thing, just send me

project_id, accn_guid_prefix, accn_number

and I'll load it. If it'll get more use I can roll that into a tool.

**Comment by Jegelewicz** [comment]
/remind me to create this file and sent to Dusty on Monday

**Comment by Jegelewicz** [comment]
Here you go.
[VP Project accessions.zip](https://github.com/ArctosDB/arctos/files/3444351/VP.Project.accessions.zip)

**Comment by dustymc** [comment]
465 rows created.

**Comment by Jegelewicz** [comment]
Thanks!
