### ISSUE TITLE
autolink to vertnet

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#2188]
alongside gbif et al in specimen records

**Comment by dustymc** [comment]
@tucotuco @dbloom I need a way to detect Arctos records in VN to make this happen. These didn't find http://portal.vertnet.org/o/msb/mammal-specimens?id=http-arctos-database-museum-guid-msb-mamm-190481-seid-1789413

http://api.vertnet-portal.appspot.com/api/search?q={%22q%22:%22organismid:http://arctos.database.museum/guid/MSB:Mamm:190481%22}

http://api.vertnet-portal.appspot.com/api/search?q={%22q%22:%22http://arctos.database.museum/guid/MSB:Mamm:190481%22}

http://api.vertnet-portal.appspot.com/api/search?q={%22q%22:%22MSB:Mamm:190481%22}

Halp!

**Comment by tucotuco** [comment]
Sorry this is obtuse. Here is a query to search the API for a particular
identifier. Note that the real identifier is sluggified to work with a rest
API:

http://api.vertnet-portal.appspot.com/api/search?q={%22q%22:%22id:http-arctos-database-museum-guid-msb-mamm-190481-seid-1789413%22}

**Comment by dustymc** [comment]
I don't necessarily have that ID - we make it up on the fly for DWC.

http://api.vertnet-portal.appspot.com/api/search?q=%7B%22q%22:%22id:http-arctos-database-museum-guid-msb-mamm-190481-seid-1789413%22%7D  finds some random frog?!?


http://api.vertnet-portal.appspot.com/api/search?q={%22q%22:%22id:http-arctos-database-museum-guid-msb-mamm-190481-%22} finds the same frog, so perhaps that could work?

If there's no way to search "individualID" (or something like it) I can try with a current SEID and just not build the links when that's changed without too much extra work.
