### ISSUE TITLE
Project enhancements

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2190]
I just created a project that has a large group of students. With only 5 categories to sort with when editing a project, it is difficult to get this bunch in a decent order. Can we start with alphabetizing by last name all of the agents listed under one of the sorting numbers?

So, for a list of agents that looks like this:
![image](https://user-images.githubusercontent.com/5725767/61996572-cd51ae80-b052-11e9-99e4-761570c2df61.png)

all the 1's would be in alpha order and so on?

**Comment by Jegelewicz** [comment]
Also, would it be possible to make the dates participating more formal? It would be great if the sorting could be by "current participants" and "past participants".

**Comment by dustymc** [comment]
We can definitely talk about the UI - eg, it could be more dynamic.

I'm not very interested in mixing behind-the-scenes ordering and explicit ordering.

I think the dates thing is firmly in 'major revision' territory and requires much more information/discussion. Whatcha trying to do?

**Comment by Jegelewicz** [comment]
Just make stuff awesome!

Actually, I'd like a Project so cool and tight that I feel comfortable giving it a DOI and trying to publish it to an eJournal....see http://journals.oregondigital.org/index.php/CatalogOSAC/issue/archive

Why are you working?....

**Comment by dustymc** [comment]
>make stuff awesome

Yes, projects are long overdue for a major revision/discussion/proposal. Eg I'm not crazy about adding localities to projects - they're dynamic and arbitrary and I'm not sure why they couldn't just be pulled from linked specimens - but adding lots more spatial capability sounds fun. (Taxonomy exists for things like checklists - there aren't necessarily specimens to draw from - and may not work very well for even that under the current model.) Projects are all about interactions, and I think we're just tapping the surface of the possibilities.

I'll have a look at the agent component.

We're all sick! Why are YOU working!?

**Comment by Jegelewicz** [comment]
Work is what I do.

Get well! All of you!

These will be named localities - so maybe only those? They are an important component of this particular project, however, I see your point. At first I thought of just adding higher geography, but in this case the specific localities will mean more to the project participants.

**Comment by dustymc** [comment]
Added secondary sort
