### ISSUE TITLE
Agent Page enhancement

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2193]
It would be nice if we could have a photo show up on our agent pages. Adding a "shows agent" photo just adds a link to the page and we probably need something different anyway since some agents may have a lot of photos that show them.

Maybe a "is avatar" or something like it? This could pretty-up the agent page if it were displayed at the top.

**Comment by AJLinn** [comment]
I would LOVE the "shows agent" links to actually display a thumbnail, like the "shows cataloged item" on the object detail pages.

**Comment by dustymc** [comment]
Done.

>lot of photos that show them.

http://arctos.database.museum/agent.cfm?agent_id=10009180&agent_name=James%20L.%20Patton currently has the most; it's just ~3 pages as it's currently set up.

I have no particular objections to more relationships, but I'm not sure it's necessary either. (Note that relationships are functional - they must end with 'space-tablename'.)

**Comment by mkoo** [comment]
I dont think Jim's agent page is long enough...
but it's nice to see show_agent!
