### ISSUE TITLE
Canada geography

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#2194]
Are we using both census divisions and regional districts for Canada's geogrpahy? We have things under census divisions and also regional districts/other things, but it seems census divisions aren't administrative divisions and are used for statistical purposes. My data also contains both census divisions and regional districts, so it sounds like census divisions might also be useful?

**Comment by Jegelewicz** [comment]
Seems OK to me. They are all pretty well documented in Wikipedia and would definitely narrow down your higher geography if that is all you have.

**Comment by anna-chinn** [comment]
FWIW, census division boundaries are subject to change every 5 years along with the Canadian census. A municipality could be in one division in 2011 and another in 2016 (then again, US counties change in shape and size over time, too). BC's regional districts feel more static than census divisions, but I could be wrong.
Here's a page about the changes to census divisions from 2011 to 2016 censuses: https://www12.statcan.gc.ca/census-recensement/2016/ref/dict/geo008-eng.cfm

**Comment by Jegelewicz** [comment]
I thought about that, but the date of collection would tell you which map to use. Complicated, but still I think including the census division in a methodical way (higher geography) is preferred over the million different ways it could be placed in specific locality.

**Comment by dustymc** [comment]
Census districts are used in Alaska for about the same reasons - there's not always a county-equivalent, or at least not one that's smaller than Montana. I don't know if they're as dynamic, but it would not be surprising.

We should probably have a temporal component to geography, but I don't think anyone could use it - we'd end up with 10 things that are all spelled "Bla County, Kenya" and a bulkloader that no longer bulks.

@Jegelewicz that still includes the possibility that the asserted geography came from a map printed 20 years after the specimen was collected. I might still use that path if I had to, but I'd not trust it too far.

I think the only thing I'm really sure of is that coordinates are very important when there's waffly or dynamic descriptive data involved. With them, we can go ask any number of webservices about names. Without, something arbitrary will happen.

I don't see anything about this that directly conflicts with http://handbook.arctosdb.org/documentation/higher-geography.html#guidelines-for-geographic-terms-in-arctos; go for it....

**Comment by mvzhuang** [comment]
Alrighty. Thanks everyone. At least our ant data in Canada is georeferenceble or has coordinates.
