### ISSUE TITLE
summarize by year & link to specimens of that year fails

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#2195]
I did a summarize by year search for order = Plecoptera in UAM:Ento

This produces the expected list of years with # of specimens for each.

However, the links to specimens are supposed to bring one to just the specimens collected in that year and fail to do so. For example this link fails:

http://arctos.database.museum/SpecimenResults.cfm?guid_prefix=UAM:Ento&phylorder=plecoptera&scientific_name_match_type=exact&year==2019

Instead of finding the 2 specimens from 2019, it finds ALL the specimens, regardless of year.

-Derek

**Comment by dustymc** [comment]
Thanks - should be fixed - got oopsied with https://github.com/ArctosDB/arctos/issues/2097
