### ISSUE TITLE
names without aphiaid used by WoRMS collection

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#2196]
from @sharpphyl via https://github.com/ArctosDB/arctos/issues/2175

>Dusty, how would I modify your SQL to find new taxon names added only to the source WoRMS (via Arctos)? I'm assuming - and I think we've discussed this before - that whenever WoRMS adds a taxon name, we'll pick it up along with the entire classification and metadata. I've had to add a lot of land snail names and, if and when, WoRMS adds them I'd want to switch to their entry with the alphiaID - or would that magically happen by itself and overwrite what I added?

Those are not names, those are classifications.

If something that isn't in Arctos pops up in WoRMS, I grab it - there can be no ambiguity in the classification, I just created the name milliseconds ago, I can do whatever I want without breaking anything. If something is already in Arctos and it pops up in WoRMS, I can see no path to action that does not involve the risk of fundamentally and silently changing the nature of the data in Arctos. Once a name has been used, I think this becomes 100% unscriptable.

Here are names used by DMNS:Inv without an aphiaid.

```
create table temp_dmns_inv_no_wrms as
select
  taxon_name.scientific_name
from
  taxon_name,
  identification_taxonomy,
  identification,
  cataloged_item,
  collection
where
  taxon_name.taxon_name_id=identification_taxonomy.taxon_name_id and
  identification_taxonomy.identification_id=identification.identification_id and
  identification.collection_object_id=cataloged_item.collection_object_id and
  cataloged_item.collection_id=collection.collection_id and
  collection.guid_prefix='DMNS:Inv' and
  taxon_name.taxon_name_id not in (
    select 
      taxon_name_id
    from
      taxon_term
    where
      source='WoRMS (via Arctos)' and
      term_type='aphiaid'
  )
group by
  taxon_name.scientific_name
order by 
  taxon_name.scientific_name
;
```
[temp_dmns_inv_no_wrms.csv.zip](https://github.com/ArctosDB/arctos/files/3447378/temp_dmns_inv_no_wrms.csv.zip)

There's an API - http://www.marinespecies.org/rest/AphiaRecordsByName/Alveolina%20fusiformis?like=true&marine_only=true&offset=1 for example - but I have absolutely no idea what I'd do with the results.  Doing anything is going to require someone who knows the collection and taxonomy to look at the possibilities and select an AphiaID. I could probably build some sort of specialized tool to make that a bit easier, but I think it would be a huge amount of work for a tiny payoff - I could spent a week and then you could do this with clicking in one tab, or you could do this now by copy-pasting across two tabs with an extra 2 seconds per record. (All that's necessary is to add an aphiaid to the Arctos record.)

I am certainly up for better ideas, but I'm not seeing a way around that idea that using a remote taxonomy source is going to involve a human maintaining the identifiers used by that source.

**Comment by sharpphyl** [comment]
I've made a note to annually run the above script to get all the WoRMS (via Arctos) taxon names without an aphiaID.  They are probably land snail taxa that I've added.  Then I'll run them again the WoRMS Match tool and if they now have an aphiaID, I'll add that.  Otherwise, they stay the same for another year.  If the committee agrees, I'll close this issue.

**Comment by sharpphyl** [comment]
@dustymc 
I tried to run the SQL above (from 7/30/2019) and got the message that it contains illegal characters.  This is for the names used by DMNS:Inv without an aphiaid.  Can you help?

**Comment by Jegelewicz** [comment]
Try leaving off the last semicolon?

**Comment by dustymc** [comment]
The SQL writer doesn't allow DDL.

Here's fresh data.

[temp_dmns_inv_no_wrms(1).csv.zip](https://github.com/ArctosDB/arctos/files/4653205/temp_dmns_inv_no_wrms.1.csv.zip)

**Comment by sharpphyl** [comment]
Thanks!

**Comment by sharpphyl** [comment]
@dustymc  Can you give me the revised SQL you used to create the above report temp_dmns_inv_no_wrms(1).csv.zip?  I'm about halfway through updating the taxon names and I'd like to occasionally run that report without needing to ask you for it each time.  Thanks.

**Comment by dustymc** [comment]
```
select
  taxon_name.scientific_name
from
  taxon_name
  inner join identification_taxonomy on taxon_name.taxon_name_id=identification_taxonomy.taxon_name_id 
  inner join identification on identification_taxonomy.identification_id=identification.identification_id 
  inner join cataloged_item on identification.collection_object_id=cataloged_item.collection_object_id
  inner join collection on cataloged_item.collection_id=collection.collection_id
where
  collection.guid_prefix='DMNS:Inv' and
  not exists (
    select 
      taxon_name_id
    from
      taxon_term
    where
      source='WoRMS (via Arctos)' and
      term_type='aphiaid' and
      taxon_term.taxon_name_id=taxon_name.taxon_name_id
  )
group by
  taxon_name.scientific_name
order by 
  taxon_name.scientific_name
```

**Comment by sharpphyl** [comment]
Thanks.
