### ISSUE TITLE
Specimen media on GBIF

### ISSUE THREAD

**Issue by anna-chinn** [ArctosDB/arctos#2197]
**Describe the bug**
The most recent media that I bulkloaded to Arctos isn't showing up on GBIF:
e.g.
https://arctos.database.museum/guid/CHAS:Inv:7402
https://www.gbif.org/occurrence/1802545559

![Capture](https://user-images.githubusercontent.com/40321380/62162357-b70b5300-b2dd-11e9-98a0-ebe6c853c71b.JPG)

Am I missing metadata fields that prevent the images from being ingested properly?

**Comment by dustymc** [comment]
The gray box is linked - they're getting SOMETHING.

Might be GBIF's problem??

https://www.gbif.org/occurrence/896551685 has images, and also the weird box.

@tucotuco ??
