### ISSUE TITLE
Add "nest description" attribute to Ento collections

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#2198]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Table**
attribute type

**Value**
Proposed new value

**Definition**
description of what the nest looks like and what it's made out of (i.e. mount of soil), already exists in Birds

**Collection type**
Ento

**Attribute data type**
free text

**Part tissue flag**
For new parts, is the part a tissue?

**Other ID BaseURL**
For OtherIDs, URL with which to prepend value (resolvable identifiers only)

**Context**

**Priority**
Please assign a priority-label.

**Comment by Jegelewicz** [comment]
Done!
