### ISSUE TITLE
UAM.PK_LOAN_ITEM violated

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#2200]
I'm getting the same error as noted in #2036 but I'm trying to add a group of objects (part=object) from a SavedSearch to a loan. Is it possible for @dustymc to figure out which object has already been added to my loan 2019-33.EH and is duplicated on my saved search "GutAll" (https://arctos.database.museum/saved/GutAll). This search has 230 items and I'm not sure how to find the duplicates to the items I already added to the loan. Can you help with some super fun easy tool that doesn't make me go thru item-by-item to find the duplicate?
Thanks for any suggestions.

**Comment by dustymc** [comment]
>fun
>easy

Wheee!!


```

 SELECT guid from  flat INNER JOIN v_attributes tbl_description ON (flat.collection_object_id = tbl_description.collection_object_id) WHERE flat.collection_object_id IS NOT NULL AND flat.collection_id IN ( select collection_id from collection where upper(guid_prefix) IN ('UAM:EH') ) AND flat.collection_object_id NOT IN (23832947,23818026,23839350,23815681,23815039,23818109,23844948,23818237,23837646,23834912,23818787,23819216,23845941,23843742,23817685,23810266,23817692,23819126,23839422,23829773,23840022,23841807,23829779,23839821,23817994,23838087,23817777,23810362,23841579,23818980,23839818,23823896,28143511,28143540,23815714,23817530,28044537,23836559,28031815,23835782,28030217,23831060,23817688,23834642,28031821,28031818,23818189,23827565,23804525,23803247,23803253,23804855,23818261,23818267,23844056,23805257,23813851,23845653,28178288) AND tbl_description.attribute_type = 'description' AND upper(tbl_description.attribute_value) like '%GUT%' 
 and guid in (
select guid from flat,specimen_part,loan_item,loan where flat.collection_object_id=specimen_part.derived_from_cat_item and specimen_part.collection_object_id=loan_item.collection_object_id and
loan.transaction_id=loan_item.transaction_id and loan.transaction_id=21123234 
  );
GUID
------------------------------------------------------------------------------------------------------------------------
UAM:EH:UA84-022-0012
UAM:EH:UA71-069-0001
```

**Comment by AJLinn** [comment]
Hooray!!! You are magical. Thank you.

**Comment by Jegelewicz** [comment]
Can this be placed in the user SQL cheat sheet? I took a stab at [copying it there](https://docs.google.com/document/d/1tkpikzS9XqPDz8jmPkq8Hj7g1bQtl_iB7WmLKRWM5wk/edit?pli=1#heading=h.3ct1ynwql4aa), but a little instruction on what needs to be changed for re-use would help.

**Comment by dustymc** [comment]
added with annotations

**Comment by Jegelewicz** [comment]
HAHAHA! Not sure I understand it, but I'd figure it out if I needed it. Thanks!
