### ISSUE TITLE
Report of taxonomy issues in collection

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#2201]
Create a new report of taxonomy issues like misspellings, invalid names, etc so curators can address and fix up for their collection. This could be added to Low Quality Data menu.

**Is your feature request related to a problem? Please describe.**
Problem is bad taxonomy for a specimen, for example unused names, synonymies, etc

**Describe the solution you'd like**
Show a report of names that have CTTAXON_RELATION values (https://arctos.database.museum/info/ctDocumentation.cfm?table=CTTAXON_RELATION)

**Priority**
Normal

**Related to #2122 **

**Comment by dustymc** [comment]
I need more information - I have no idea how I could find that??

For scale, there are currently 1,088,035 taxon relationships.

**Comment by Jegelewicz** [comment]
I think this is all part of needing a taxonomy strategy. I can't say I am focused on that right now, but it is percolating in my brain. I need to do more research on what others are doing.

**Comment by sharpphyl** [comment]
Teresa, should we target our next T. committee meeting (August 21??) to start on the taxonomic plan?  If we all brought (preshared would be best) our overall concepts and topics to include, we could at least take the first steps toward an overall plan.

**Comment by dustymc** [comment]
>start on the taxonomic plan

I think most taxonomy-related development has ground to a halt without that; I'd definitely support that being the highest/only priority of the Committee. I added the start of Functional Requirements to https://docs.google.com/document/d/1ZB-65Xo5NQjkcxfSVu8MQn1SHAouoYUQvXsnCa2J4Ks/edit#

**Comment by Jegelewicz** [comment]
@sharpphyl yes! I have sent out a message and I hope we can get the party started.
