### ISSUE TITLE
Add "methods" part attribute

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2202]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Table**
http://arctos.database.museum/info/ctDocumentation.cfm?table=CTSPECPART_ATTRIBUTE_TYPE

**Value**
preservation methodology

**Definition**
Method by which the part was prepared

**Collection type**
N/A

**Attribute data type**
free-text

**Attribute value**
N/A

**Attribute units**
N/A

**Part tissue flag**
N/A

**Other ID BaseURL**
N/A

**Context**
Currently this information is being mashed into other fields:

![image](https://user-images.githubusercontent.com/5725767/62320512-979b3400-b45d-11e9-8a04-2b4016d94e76.png)

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
Should this be a separate attribute (in which case you can just add it to the code table), or is this a request for a method column in table specimen_part_attribute?

**Comment by Jegelewicz** [comment]
I'd say just a new attribute, but I will let others weigh in. @campmlc ?

**Comment by mkoo** [comment]
Definitely a separate attribute.
Is there a DwC term for this?
Sorta related to https://dwc.tdwg.org/terms/#measurementMethod or will that
encompass all our parts?

**Comment by Jegelewicz** [comment]
https://dwc.tdwg.org/terms/#measurementMethod seems like it would go with attributes such as "total length".

**Comment by dustymc** [comment]
>would go with attributes such as ...

That's why I think maybe this is a new column (eg, part attributes aren't as factual as we thought when we built this model). Given 50 attributes where one of them is 'method,' how do you know which of the 49 tail length measurements used the given method?

**Comment by Jegelewicz** [comment]
> how do you know which of the 49 tail length measurements used the given method?

This has nothing to do with those attributes, but goes with part preservation in a like manner.  "preservation methodology would cover what is in the example above and expresses how the part was "created".

preservation methodology = Blood drawn from wing in field shortly after capture and spun in heparinized microcapillary tube(s) in portable centrifuge, then placed in 2 ml tube and flash-frozen in LN2

is this a part attribute or something that should be part of a part attribute (preservation)?

preservation = flash frozen
methodology (as a column of "preservation" along with date, authority, and remarks) = Blood drawn from wing in field shortly after capture and spun in heparinized microcapillary tube(s) in portable centrifuge, then placed in 2 ml tube and flash-frozen in LN2

**Comment by Jegelewicz** [comment]
I think this is accomplished

![image](https://user-images.githubusercontent.com/5725767/140540632-0c41400b-a5ba-4186-b7d4-2373353f147c.png)
