### ISSUE TITLE
GUI upgrade for Parts

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#2203]
**Is your feature request related to a problem? Please describe.**
Parts table is currently confusing especially for parts with extended attributes and/or attribute history (spawned from #1460 and will deal with  #2202 )

[See current screenshot and Ideas](https://docs.google.com/drawings/d/1rLci2GKNbayYaOWEtXNvN51Gn_bJH67dJQT0LzTc13g/edit)

**Describe the solution you'd like**
AWG would like to retain Parts Table but display their Attributes as a simplified list wtih option to expand or as concatenated list.

**Describe alternatives you've considered**
1) simplified list with option to expand. Could display latest value only with a link "Expand for history" to show rest. Possibly pop-up window or added to Parts table

2) OR display as concatenated list but then the order is debatable (by date, alphabetically (which seems least favorable, or other)

We also dont want to see Attributes as a table within a table (the current structure which is confusing). Can they be listed as:
```
 {attribute} is {value} ({date})
```
example:
```
Preservation is frozen (date)
```
etc

Dusty will now accept suggested mockups in crayons!

@AJLinn should weigh in as she typically uses and has a lot of attributes per object!

All:[ Parts Drawing is editable by all so please add crayon drawings here](https://docs.google.com/drawings/d/1rLci2GKNbayYaOWEtXNvN51Gn_bJH67dJQT0LzTc13g/edit)

**Comment by dustymc** [comment]
FYI the current longest part attribute is 486 characters, and the most attributes assigned to a single part is 6.

Also mentioned: @ccicero doesn't like the indent to denote "samples." Samples may be of any 'depth' - whatever we do must accommodate a sample of a sample of a sample of a ....

"samples" are also just parts - they can have any number of attributes, and that must be accommodated.

The max number of parts is currently 125.

I'm up for anything, but any solution will need to be capable of dealing with fairly complex/verbose data.

>option to expand

My understanding is that these data are critical; they're necessary to understanding things like suitability for usage. If they're not, maybe we don't need such a complex model - why not stuff them into remarks? If they are, then I think users need to see them.

>latest value

This seems 100% fatal to me. Eg latest value is "liquid nitrogen" so we [do|do not] get loan requests, but other attributes might include rnalater, formalin, etc - users need the whole picture, not just the latest, to understand what they're looking at.

A concatenation of distinct values might be functional and compact enough. Date is probably a useful sort, but unlike eg, georeferences or identifications these are not necessarily 'current opinions' - they are things that cumulatively affect what the specimen is useful for. A previous identification or georeference is a hypothesis that may secondarily affect current usability in some few cases; an older preservation action is a fact that fully affects current usability. (There's some variability in that by type - only one "location" should be current, for example.)

Sorting by eg, a list of terms (so "blaugh" always appears before "bla") is possible, and may be what the discussion was circling around.

**Comment by Jegelewicz** [comment]
>     option to expand
> 
> My understanding is that these data are critical; they're necessary to understanding things like suitability for usage. If they're not, maybe we don't need such a complex model - why not stuff them into remarks? If they are, then I think users need to see them.

The issue is with different types of users. A teacher looking for data to present to an elementary school class might not be so interested in all that stuff, but someone looking to do molecular research definitely will be. For me, that is a whole grant to be written by someone who can and for right now, we should present everything because I think we are currently focused on the research community.

**Comment by dustymc** [comment]
>whole grant

Agreed, and I think it starts with a full-fledged API. If we had that, then we could just...

* get_parts(super-simple)
* get_parts(default)
* get_parts(full-human-formatted-data)
* get_parts(full-machine-formatted-data)
* ....

on demand, or by user, or by 'portal,' or whatever.

That logic would actually be fairly trivial to implement now, but I don't think we have the resources to feed it - it would require more connections and be more DB intensive.

**Comment by mkoo** [comment]
Since this was originally filed we have more than one option to view parts: full , summary, string.

I think the next step may be collection-type specific (eg. birds vs. archives) but that's an new issue so closing for now
