### ISSUE TITLE
Two different fields by the same name: Locality ID

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#2206]
"Locality ID" is used in two ways
1.  As an "Other ID."  This is a searchable field under Other Identifier Type

![Locality ID attribute](https://user-images.githubusercontent.com/15368365/62427488-fad0d480-b6b0-11e9-8619-c1a0e09bc78a.png)

It is defined in the code table http://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type:

Locality ID | Number given to a site. In paleontology, often referred to as "site number". Roughly corresponds with collecting event.
-- | --

This Locality ID is user generated and controlled.  It can be alpha-numeric.

One benefit of using this Locality ID to describe a group of specimens from the same event is that anyone searching Arctos can find all specimens that have been assigned to this Locality ID with one click from within one specimen record with that Locality ID.

![Locality Name](https://user-images.githubusercontent.com/15368365/62427607-a6c6ef80-b6b2-11e9-9662-424ee823a237.png)

![Screen Shot 2019-08-04 at 12 16 06 PM](https://user-images.githubusercontent.com/15368365/62427536-b134b980-b6b1-11e9-9c06-52f220483fcd.png)

2.  The other Locality ID is a number automatically assigned to a locality as it is created.  It can be searched through Search/Places if you have the locality number.  As Dusty pointed out in #2073, locality IDs are not stable but can change over time.

![Locality ID](https://user-images.githubusercontent.com/15368365/62427593-7da65f00-b6b2-11e9-958d-56f7bb538075.png)

I suggest that we modify the name of the Locality ID within the Other Identifier 
Type list so that it is distinct from the Locality IDs automatically assigned as localities are created.  If anyone is a big user of this feature and has a suggestion, I'm open to it.  Some ideas would be Locality name or Site name or Event Name.

**Priority**
Medium Priority

**Comment by dustymc** [comment]
I'm up for changing (ideally by revoking all views to...) how we represent locality.locality_id. 

OtherID "Locality ID" is legacy data that's fairly central to a normalized rapid digitization process, and is used in various external forms and original data. Changing it just isn't practical.

The only "advantage" to using it involves having no alternative - there was no other Arctos data structure capable of preserving these data as they were actually organized.

Locality.locality_name is what "Locality ID" was intended to be. Collecting_event.collecting_event_name is closer to, but still very much not, what it actually is. Either of those are, unlike any no-URL OtherID, capable of holding specimens from the same place and/or time together.

**Comment by sharpphyl** [comment]
Actually, it doesn't matter what the data fields are called behind the scenes, but distinguishing them on the Search screens seems sensible.  It would probably be sufficient for one to be Locality Identifier instead of Locality ID.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I would like to see locality nickname changed to something a bit more intuitive. I will be migrating our institutional locality numbers into this field and I anticipate our users having a lot of difficultly understanding why the loc # is in a field called nickname. To me, a locality nickname is something like Larry's Last Gasp (actual example of a locality name in our collection). In addition, I don't see a way to specifically query locality nickname from the search page.

> ideally by revoking all views to...
I agree, If locality.locality_id is a behind the scenes number that can change, I don't see a reason to display it at all and then perhaps Locality.locality_name could display as Locality Identifier while Other ID "Locality ID" stays the same.

I would also like to have a field in locality for alternate locality names/identifiers. For example, I have a locality, NMMNH L-6260, that has other identifiers:
UALP 75106 (University of Arizona Laboratory of Paleontology #) 
LLJ 13-75 (Field Number - our institution assigns field numbers to localities, not collecting or specimen events. Each locality has a single field number)
Taylor's Mound (a name given to the site)

**Comment by dustymc** [comment]
>nickname

I agree - that's why I wrote the code I wrote! - but see https://github.com/ArctosDB/arctos/issues/2105

>search

That's fairly trivial, but I'd like to get the terminology worked out first.

>alternate locality names

I'd probably argue for verbatim locality, if that's what they are. Some similar data have been made into OtherIDs, which can be actionable - see the UCMP Locality ID on https://arctos.database.museum/guid/UAM:ES:29632 for example.

If they are something else please send details/examples.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I will move my alternate locality names question into another thread so as not to derail this one.
