### ISSUE TITLE
Clarify procedure to delete media

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#2207]
After I deleted the image http://arctos.database.museum/media/10584145, I got the following message.

http://arctos.database.museum/media/10584145
after deleting:
-you deleted media 10584145-
The files
https://web.corral.tacc.utexas.edu/arctos-s3/sharpphyl/2018-07-03/ZC_27428_Acteon_traskii_Ventral.jpg and https://web.corral.tacc.utexas.edu/arctos-s3/sharpphyl/2018-07-03/tn/tn_ZC_27428_Acteon_traskii_Ventral.jpg are unaffected. You should delete them if you don't need them around anymore. 

If I just search for the files on line, they are still there.  

When I try to find the media at Search/Media and enter
https://web.corral.tacc.utexas.edu/arctos-s3/sharpphyl/2018-07-03/tn/tn_ZC_27428_Acteon_traskii_Ventral.jpg
into the URI, nothing is found.

![Screen Shot 2019-08-04 at 1 06 46 PM](https://user-images.githubusercontent.com/15368365/62428001-f3152e00-b6b8-11e9-8030-e1ec572611bc.png)

I cannot find any entry for "delete media" in the Handbook.  Where do I find instructions if I need to delete these files?  If they eventually disappear on its own, should the 'alert' be modified?

**Comment by dustymc** [comment]
Yup, all correct. Arctos controls - and can therefore delete - the metadata. We at best sometimes sorta control whatever's at the Media_URI. 

In this case I actually have access to the server and could (with a fair bit of work) delete that file - which I think wouldn't actually delete the file, which has been replicated into TACC's infrastructure. If someone's going to die or something I'm sure TACC can help. If not, meh, disk is cheap, whatever....

**Comment by sharpphyl** [comment]
Ok, I'll ignore the alert in the future.  Could we add some instructions on how to substitute a new (and improved) image for an existing one?  So far, I haven't been successful in doing that but it would eliminate stray, unused images floating around.

**Comment by dustymc** [comment]
> instructions on how to substitute a new (and improved) image for an existing one?

I'd probably just add, but I'm an avowed data hoarder...

You can edit the Media data object with a new URL. That will CREATE strays, unless they're on a server from which you can delete them. 

I could try to periodically delete any unused files from the S3 slice or something, but I don't think that's a problem worth acknowledging at this time. AFAIK there are MAYBE megabytes of orphaned data (some of which someone probably plans to use at some point), and we have petabytes of disk. If it does become an issue, I don't think deleting a decade-or-whatever's worth of orphans would be any more work than if we'd have done that yearly-or-whatever. Now watch the universe find a way to make me regret typing that....

**Comment by sharpphyl** [comment]
Ok, I'll just delete and replace.  We'll see what the universe thinks in 2030.
