### ISSUE TITLE
brief outage in one hour

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#2208]
All,

We need to briefly take Arctos down at 10 AM. It should last no more than 15 minutes. Please let me know ASAP if that isn't possible and we'll try to keep things limping along a bit longer.

I apologize for the short notice.

Thx-D

**Comment by Jegelewicz** [comment]
Is Arctos still down?

![image](https://user-images.githubusercontent.com/5725767/62491274-a13bd900-b788-11e9-838a-9443c45a772f.png)

**Comment by dustymc** [comment]
No, works for me and there's a fair bit of activity

**Comment by AJLinn** [comment]
I've been logged in and actively manipulating data for the past hour at least.
