### ISSUE TITLE
Determined by unknown at bottom of location panel

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#2211]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

When viewing a specimen record in the location panel after the data there is a series of lines, then a colon, and on another line the words "determined by unknown"

This is odd and looks buggy / unprofessional.

**To Reproduce**

**Expected behavior**

**Screenshots**

See screenshot
![Screen Shot 2019-08-08 at 11 25 36 AM Aug 8, 19](https://user-images.githubusercontent.com/9099827/62731869-92933300-b9cf-11e9-9b93-fb28e7cf6847.jpg)

** Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label. medium

**Comment by dustymc** [comment]
Thanks!
