### ISSUE TITLE
Fork-edit specimen events feedback

### ISSUE THREAD

**Issue by anna-chinn** [ArctosDB/arctos#2212]
I just used the fork-edit specimen event from https://github.com/ArctosDB/arctos/issues/1357#issuecomment-497880332 for the first time. It worked great overall. Here's some feedback:

I couldn't figure out how to un-require coordinate data. I tried setting Datum to null, but that wasn't an option for some reason:
![Capture](https://user-images.githubusercontent.com/40321380/62970285-c1951480-bdd4-11e9-96da-705a92be3b2b.PNG)

Is it possible to add 'Georeference using GeoLocate' and 'Modify Coordinates using GeoLocate' buttons/functionality to the form? Also, a drop down picklist for Georeference Protocol would be great.

In addition to the two edit options at the bottom of the form, it might be nice to have the option to maintain the current verification status of the old event and set new event to unverified:
<img alt="Screen Shot 2019-05-31 at 7 37 52 AM" width="474" src="https://user-images.githubusercontent.com/5720791/58713267-10571480-8377-11e9-9df6-874c8f806318.png">
I just used this form to record two different localities for a specimen with two different original labels, so I wanted both events to be unverified. It's not difficult to go back and change the status of the old event from unaccepted to whatever it was before fork editing, but this option could save time for a larger project using the tool.

**Comment by dustymc** [comment]
I'm seeing some of this in the logs, upping priority.

**Comment by AJLinn** [comment]
I agree, I love the new fork edit option for items when there are confirmed coordinates. Unfortunately, when I have an item with no known location associated with the event I have to go back and make the new event the old way. I echo the desire to have coordinates as non-required.

**Comment by dustymc** [comment]
>un-require coordinate data. 

Added this

<img width="313" alt="Screen Shot 2019-08-16 at 10 02 50 AM" src="https://user-images.githubusercontent.com/5720791/63184788-086d4f00-c00d-11e9-9f45-cd4e89b750d8.png">


>'Georeference using GeoLocate' and 'Modify Coordinates using GeoLocate' 

They're on the webservice tools box

<img width="506" alt="Screen Shot 2019-08-16 at 9 51 57 AM" src="https://user-images.githubusercontent.com/5720791/63184116-816ba700-c00b-11e9-8d30-e0d5adb7c1e4.png">

> drop down picklist for Georeference Protocol 

derp/done/thanks

>addition to the two edit options 

There's now a "Add, change no existing data" option which should cover your request and some other stuff.

@AJLinn as an aside given free reign I'd probably require coordinates for everything. "Alaska" (and being able to find that spatially) is immensely more informative than "North America" (again, ideally defined spatially) and if you really only know "somewhere on the planet, probably" 0,0+/-40Mm (or anything else that includes everything...) is always available.
