### ISSUE TITLE
Add San Pedro  Beds to geologic Formations

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#2213]
Add San Pedro Sand as a formation

https://en.wikipedia.org/wiki/San_Pedro_Formation

Geological Society of America. Cordilleran Section, Decade of North American Geology Project, 
Geological Society of America, 1987, Volume I, page 175-178

Thanks!

**Comment by Jegelewicz** [comment]
@sharpphyl Should it be San Pedro Formation or San Pedro Sand Formation? Also, is there any information about what group it belongs in?

**Comment by sharpphyl** [comment]
None of the GSA documents we found say anything but Pleistocene.  It's all in the Palos Verdes Hills but I don't think that's a geologic term.  

Our sources say San Pedro Sand is the correct name of the Formation.  FYI, the other two formations listed with it are the Lomita Marl and the Timms Point silt.  Below it is the Palos Verdes Sand.  None of them seems to be in our tables yet, but we may not need them so noting them here isn't a request to add them unless someone else may need them too.


![San Pedro Sand Formation](https://user-images.githubusercontent.com/15368365/62981924-d6c76e80-bde7-11e9-9544-09b375951707.JPG)

**Comment by Jegelewicz** [comment]
Added all four!
