### ISSUE TITLE
Arctos down

### ISSUE THREAD

**Issue by snknts** [ArctosDB/arctos#2215]
Arctos appears to be down.
I was trying to do a table to csv at the time....

Hopefully I didn't kill it :(

**Comment by sharpphyl** [comment]
Down for us too.

**Comment by Jegelewicz** [comment]
@snknts I think it was you. Why were you trying to download all agents?

**Comment by Jegelewicz** [comment]
Arctos is down, Chris should be in to revive it in ~20 minutes. I'm not 100% sure this (downloading all agents) is what killed it, but it is the last thing that happened.

Any idea why they might be trying to do this?


---------- Forwarded message ---------
From: <logs@arctos.database.museum>
Date: Wed, Aug 14, 2019 at 6:27 AM
Subject: The cause of this output exception was that: org.apache.catalina.connector.ClientAbortException: java.net.SocketException: Broken pipe.
To: <arctos.database@gmail.com>, <arctoslogs@mail.com>

**Comment by snknts** [comment]
We're looking at what options we have to get a local backup of our data.
(i.e. export functionaiity, API calls, table downloading etc..)

I assumed downloading that table would get us a list of our agents... right now that should be very few people.  
I didn't realize it was a self-destruct link ;)

**Comment by Jegelewicz** [comment]
You don't have a list of Agents. Agents are shared by everyone in Arctos. Please read http://handbook.arctosdb.org/documentation/agent.html

A download of your specimen records will also provide a list of your agents. If you want everything there is to know about "your" agents, maybe we can work with Dusty to create that.

**Comment by snknts** [comment]
Are there docs detailing the correct way to download our specimen records?
It also might be wise to restrict/disable the table download functionality too.. at least until it can be fixed.

**Comment by dustymc** [comment]
See also http://handbook.arctosdb.org/documentation/sharing-data-and-resources.html; anyone with access to any shared data should be familiar with that document. It is listed as required reading and linked prominently on the form which provides access to shared data.

I added http://handbook.arctosdb.org/documentation/catalog.html#understanding-specimen-records as an attempt to describe "specimen records."

Suggestions or edits to both appreciated.

**Comment by Jegelewicz** [comment]
A learning experience for everyone! I am adding these to the start of the data migration project template. Thanks!
