### ISSUE TITLE
Relationships to non-Arctos identifiers

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2216]
Results from the recent GlOBi collaboration show that we have relationships to non-Arctos specimens. In some cases this is fine, because the related specimen is not in Arctos. In others, the relationship is made to a non-Arctos identifier even when the related specimen is in Arctos.

Here is one example: http://arctos.database.museum/guid/MSB:Para:27076

Which is parasite of NK215110, but would work much better outside of Arctos if it were related as parasite of MSB:Mamm:259318

Can we get a report by collection of relationships to non-Arctos Ids? This would help us correct items like the one above.

**Comment by dustymc** [comment]
I can do stuff with specific identifiers, but they are both very much "Arctos identifiers" at this point.

FWIW I think the search base_url that was recently added to everything (was there a discussion??) is implying something we can't back up. "THAT specimen, can't be anything else" and "one of the 30 things with this NK scribbled on it, all of which may or may not yet be entered into Arctos, probably" cannot answer the same questions with the same confidence, yet we've made them indistinguishable.

Here's the SQL to find some stuff

```
select guid,display_value,ID_REFERENCES from flat,coll_obj_other_id_num where flat.collection_object_id=coll_obj_other_id_num.collection_object_id and other_id_type='NK' and ID_REFERENCES!='self';
```

**Comment by Jegelewicz** [comment]
> FWIW I think the search base_url that was recently added to everything (was there a discussion??) is implying something we can't back up. "THAT specimen, can't be anything else" and "one of the 30 things with this NK scribbled on it, all of which may or may not yet be entered into Arctos, probably" cannot answer the same questions with the same confidence, yet we've made them indistinguishable.

That is true in the case of these relationships, but not true when the NK is just added as an other ID (self). THAT search base_url lets us find all of the stuff collected together under the NK and is very useful. It is just that the NK should NOT be used with any other relationship than self...which means we need some procedures and documentation here at MSB.

**Comment by dustymc** [comment]
>search

I could build that into the form. "Make the UI do stuff" and "make the data do stuff" are being confounded here. We control the UI, anyone can pull the data and this sort of thing severely limits usage.

http://handbook.arctosdb.org/documentation/other-identifying-numbers.html#general-guidelines contains the guidance - "Be as specific and complete as possible...." Those definitely SHOULD be cleaned up, but I suspect reality will get in the way - you don't know catalog numbers when you're entering embryos-or-whatever, or the printer jammed and who knows which of these 54 "NK 1" is the correct one, or someone scribbled "NK1" on a mother, 18 embryos, and 56 parasites, or ....

**Comment by Jegelewicz** [comment]
closing as duplicate of #4123
