### ISSUE TITLE
Upload Media Metadata - errors stuck

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2217]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I uploaded a csv to the Media Metadata Bulkload Tool that had incorrectly formatted dates. This information appears to be stuck in the tool and although I was able to correct and load the metadata, the stuff with errors is still there. I have tried using the Delete "anything with status" on these and it doesn't work.

**To Reproduce**

**Expected behavior**
Either the data could be over-written upon loading something new or I should be able to use the Delete "anything with status"=whatever the error is in the status column.

**Screenshots**
![image](https://user-images.githubusercontent.com/5725767/63106984-4735d300-bf41-11e9-9cb7-1f6433db0e2f.png)

** Data**
N/A

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser Firefox
 - Version 68.0.1

**Additional context**
Not a huge problem, mostly just annoying.

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
I can't immediately see why Delete "anything with status" shouldn't work. I can test it out if you'll attach some data.

**Comment by Jegelewicz** [comment]
Yeah, just take those.

**Comment by dustymc** [comment]
update cf_temp_media set username='dlm';

10 rows updated.

<img width="191" alt="Screen Shot 2019-08-15 at 11 38 25 AM" src="https://user-images.githubusercontent.com/5720791/63117768-4f960a00-bf51-11e9-9c30-49b790078fb8.png">

<img width="166" alt="Screen Shot 2019-08-15 at 11 38 34 AM" src="https://user-images.githubusercontent.com/5720791/63117782-53c22780-bf51-11e9-9972-c27aa1e5cd1a.png">

clicky...

<img width="186" alt="Screen Shot 2019-08-15 at 11 38 42 AM" src="https://user-images.githubusercontent.com/5720791/63117789-5755ae80-bf51-11e9-8c16-28840c59db46.png">

<img width="431" alt="Screen Shot 2019-08-15 at 11 38 49 AM" src="https://user-images.githubusercontent.com/5720791/63117800-5ae93580-bf51-11e9-8ae1-a1bd67c982da.png">

UAM@ARCTOS> select * from cf_temp_media;

no rows selected

????????

This seems excessive for even it, but Chrome?!?

**Comment by Jegelewicz** [comment]
So you used the "anything" and it still didn't work? I see the stuff is gone now. What should I do the next time this happens?

**Comment by dustymc** [comment]
I used anything and it DID work - I went from 10 to zero records with a click (and return).

**Comment by Jegelewicz** [comment]
OK, thanks,
