### ISSUE TITLE
cloning into the bulkloader captures accepted sci name but not determiner

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#2219]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

When we clone into the bulkloader Arctos creates a clone with the accepted scientific name if a specimen has multiple identifications, but it fails to capture the agent who made that ID with the error (for example) & see screenshot
![Screen Shot 2019-08-15 at 9 53 15 AM Aug 15, 19](https://user-images.githubusercontent.com/9099827/63115158-0b9c0880-bf43-11e9-8f80-80ca6df35618.jpg)

cloned from KWP:Ento:26797; too many identifiers: Derek S. Sikes,Kenelm W. Philip

If Arctos can "know" which Sci name to use for the clone then it should know which agent did the ID of that name and capture that as well.

Currently I have to do this manually in the bulkloader and it's frustrating.

**Describe the solution you'd like**

The agent who made the ID of the sci name that is used for the clone should be in the agent ID field, obviously! 

**Describe alternatives you've considered**

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
Yea that should just be pulling from acceptedID - fixed.
