### ISSUE TITLE
Georeferencing Protocol Question [CONTACT]

### ISSUE THREAD

**Issue by alexkrohn** [ArctosDB/arctos#2220]
I have a question about best practices for georeferencing. We're currently in the process of uploading our legacy collections to Arctos. I'm hoping to georeference specimens as we bulkload them, to avoid having to go back through and georeference them one by one later (very few share the same locality). 

I was following the protocols from the very helpful [georeferencing webinar.](https://www.youtube.com/watch?v=YuP-hr6yvCU&feature=youtu.be) The process that Andy Doll describes seems pretty straight forward: convert addresses to GPS points using GPS Visualizer (or Google Earth?), then verify the accuracy of those points in Google Earth, and then assign an error to those localities. Andy put this down as the [Google automated georeference for georeference_protocol](https://arctos.database.museum/info/ctDocumentation.cfm?table=CTGEOREFERENCE_PROTOCOL), but it looks like he did in fact copy and paste in the locations, error and elevation from Google Earth.

Andy's procedure makes intuitive sense, and would be much quicker than having to go back to our specimens to georeference again once we've bulkloaded them to Arctos. However, [according to the code table](https://arctos.database.museum/info/ctDocumentation.cfm?table=CTGEOREFERENCE_PROTOCOL), we shouldn't be copying/pasting GPS information. If not, what protocol should we be using, or should we be adding georeferences into the bulkloader in a different way?

Thanks,

Alex

**Comment by dustymc** [comment]
I am absolutely positive that there is a functional difference between GPS downloads and GPS transcriptions - I would handle one very differently than the other in analyses and such.

Copy-paste gone wrong, Excel rounding coordinates, the "Excel Shuffle" mixing coordinates up among records, etc. is common enough that I think there **may be** a functional difference between that and doing secondary georeferencing with something that avoids those problems (eg, by being plugged in to Arctos). I think I could also be convinced that stuff doesn't matter - one more source of error on derived data isn't worth splitting out.

Should we relax the definitions, or add a series of "same thing, but transcribed" definitions to the authority?

**Comment by Jegelewicz** [comment]
@dustymc I am in agreement - maybe we just need another protocol?

Google georeference - Coordinates+error determined by a Google API (eg, the "suggestion" from Edit Locality). Data were not fed directly from the Google API and may have been copy/pasted, transcribed, or edited.

**Comment by alexkrohn** [comment]
I am OK with creating another definition for the protocol that I described.

It also seems that there isn't a good way to simultaneously bulkload new
specimens while also geolocating them, unless the location already exists
in Arctos. The best way that I can think of relies on copying/pasting
coordinates+error from another source. Do you all have any suggestions on
the best way to simultaneously bulkload new specimens while also doing
geolocation, or do you just always prefer to do the gelocation separately
with the built in functionality of Arctos?

**Comment by dustymc** [comment]
> simultaneously bulkload new specimens while also geolocating them

You can access geolocate from the single-record entry screen. The bulkloader is designed for no/minimum human involvement, and there is not a place to insert data in the Arctos side of things. You could georeference (maybe by geolocate's batch mode) before loading to Arctos, or we could talk about automated georeferences in Arctos.

**Comment by Jegelewicz** [comment]
Could they bulkload, then edit the records before accepting them into Arctos and use the tool at that point?

**Comment by dustymc** [comment]
> bulkload, then edit

Sure. Probably not what I'd do, but if it works with those particular data that's available.

Sorta-related, we've long had fantasies of plugging various tools, including spatial, somewhere into the approval process. Something to think about, definitely needs a dedicated Issue...

**Comment by ewommack** [comment]
I had my students use the Geolocate webpage (https://www.geo-locate.org/web/WebGeoref.aspx), and then they entered that georefenced data into the bulkload file.

That's not automated in any sense, but it seems to be working.

**Comment by mkoo** [comment]
I'd use Geolocate for georeferencing post-bulkload so that copy/paste
errors are minimized AND you get a method and uncertainty estimate all at
once.

But this is a good use case we should definitely reach out to Geolocate
(Nelson Rios) about incorporating a batch geolocate georeferencing function
into Arctos (I think Specify has something batch-georeferencing fxn). This
could be a service prior to uploading to Arctos or post-upload; like maybe
grab all ungeoreferenced localities in an Accession service? Then once
passed through Geolocate, a person could vet and accept or not accept (I
would not want to dismiss the human checking step).
New issue for new service/function if interested in pursuing??

**Comment by dustymc** [comment]
Everything gets auto-georeferenced when it's in Arctos Proper - you can access the data from Edit Locality. I preferentially use geolocate for that, then fall back to some other tools. I could very easily make those data more available, and it wouldn't be too hard to grab error (and etc.) from anything that provides it if there's a use.

**Comment by dustymc** [comment]
tentatively closing
