### ISSUE TITLE
Adding "OTHER_ID_RELATIONSHIP" to Bulkload Builder Template

### ISSUE THREAD

**Issue by acoconis** [ArctosDB/arctos#2221]
I need to add this relationship status to my ID's when bulkloading. I couldn't figure out if this was the OTHER_ID_REFERENCES" listed at the very bottom of the bulkload builder. Just to clarify, in the single-entry form under the Other ID's section, under Relationship, there is a drop-down menu, of which I need to select "same individual as".

**Comment by dustymc** [comment]
Yes same thing

http://handbook.arctosdb.org/documentation/bulkloader.html


Other_Id_References_x | text; ctid_references | Establish relationships to other specimens. (Code-table controlled.)
-- | -- | --

**Comment by acoconis** [comment]
Thank you. One more question... I have never created links in a specimen record. I noticed that you can't edit these once they are created, and then I read in the GenBank Links How-To that links are maintained by Arctos staff. So my question though is what exactly do I enter into the Other_Id_Num_x for GBIF records? Do I put the url to the record or do I just put the number associated with the occurrence? Additionally, since the bulkloader Other_Id_Num_x begins with Other_Id_Num_5, is this where I input this? or should I start with Other_Id_Num_1? I noticed in the Bulkloading Specimen Data How-To, the Other_Id_References_x starts with Other_Id_References_1.

**Comment by Jegelewicz** [comment]
> So my question though is what exactly do I enter into the Other_Id_Num_x for GBIF records?

Links to the GBIF record for the specimen itself are auto-created. If you want to link to some other GBIF record it's a bit more complicated. Can you give me an example?

**Comment by Jegelewicz** [comment]
> Additionally, since the bulkloader Other_Id_Num_x begins with Other_Id_Num_5, is this where I input this? or should I start with Other_Id_Num_1? I noticed in the Bulkloading Specimen Data How-To, the Other_Id_References_x starts with Other_Id_References_1.

You can use Other_Id_Num_5, the numbers are just for the bulkloading process to keep the otherID, OtherIDType and OtherIDReferences together. They won't matter once the other IDs are in Arctos. (Let me know if that doesn't answer your question!).

**Comment by acoconis** [comment]
Yes. For example, For example, in this observation 
(https://www.gbif.org/occurrence/1990632481)
Would I put this whole web address or just the occurrence number (1990632481) in the ID Number column?

**Comment by Jegelewicz** [comment]
Actually, I think it would be better to link to the original iNaturlaist record:

Other ID Type = iNaturalist.org
Other ID Number = 19993923
Other ID Relationship = same individual as

I say this because I'm not sure I have complete confidence that GBIF occurrence numbers will remain constant. Perhaps @dustymc knows for sure...

**Comment by acoconis** [comment]
Okay, thank you for specifying. And linking to iNat totally makes sense since it is the original source. However, the reason we were using GBIF is that it is the aggregator of all the "research grade" observations on iNat. Let me know what's best. Thanks!

**Comment by Jegelewicz** [comment]
I'd stick with the iNat and here is why.

GBIF will be able to see that your "occurrence" is the same as the one from iNat and so will everyone else in the world. The reference to iNat will also give iNat and the person who made the observation direct credit for the use you are making of their data. I prefer this over giving aggregators information that may never reach the original source of the information.

FWIW, iNat is the actual aggregator of all iNat research grade observations. All you have to do is search only for "research grade". Don't get me wrong, GBIF is a great discovery tool, but it does NOT hold all of the information that the primary sources do and I think that as much as we can link to primary source data, the better our data (and theirs) will be.

**Comment by Jegelewicz** [comment]
I also suggest that you contact iNat about your project and see if reciprocal links can be generated. If you do the work of creating a project in Arctos, then iNat can demonstrate how their cit sci data is being used in a very effective manner.

**Comment by acoconis** [comment]
Sounds great. And yes, I will contact someone from iNat, once I input some observational data on Arctos.

**Comment by dustymc** [comment]
>can't edit these once they are created

Sure you can.

>GenBank Links How-To that links are maintained by Arctos staff

Arctos automagically creates links from the identifier itself (and base_url from the code table),  and shares data with GenBank. We could do that with other sources. Maintaining the Other ID value is up to the collections.

>Do I put the url to the record or do I just put the number associated with the occurrence?

Generally, the identifier + base_URL (when available) is much easier to work with and maintain. If you must use URLs somewhere I'd recommend doing so through Media, which would make them a bit easier to maintain.

> link to the original 

Absolutely, always. GBIF is an aggregator and should not be viewed as anything else.

**Comment by dustymc** [comment]
tentatively closing
