### ISSUE TITLE
add a new row when edting a taxon name fails

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#2222]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

I cloned a classification to make a new name in taxonomy. I made this name:
Ancistrocerus catskillensis albophaleratus

I tried to add a row to the classification to make this species:

Ancistrocerus catskillensis

but the term type drop down menu is broken and won't let me specify it's a species. Thus I can't save.

**To Reproduce**

**Expected behavior**

**Screenshots**

** Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
<img width="618" alt="Screen Shot 2019-08-19 at 12 32 09 PM" src="https://user-images.githubusercontent.com/5720791/63293673-7324c180-c27d-11e9-853c-116678d69182.png">


??????????

**Comment by DerekSikes** [comment]
weird, I refreshed the page and then the menu became active.
