### ISSUE TITLE
Plug in spatial tools to data entry approval process

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2223]
Sorta-related, we've long had fantasies of plugging various tools, including spatial, somewhere into the approval process. Something to think about, definitely needs a dedicated Issue...

_Originally posted by @dustymc in https://github.com/ArctosDB/arctos/issues/2220#issuecomment-522778922_

**Comment by dustymc** [comment]
Thanks @Jegelewicz 

Browse/Edit-->filter for [something|nothing]-->new form--> then what?

* map stuff (need to check when coordinate conversion happens, possibly rebuild workflow)
* auto-georeference??
* suggest georeferences??
* ??????????????

**Comment by dustymc** [comment]
Merge-->https://github.com/ArctosDB/arctos/issues/4289
