### ISSUE TITLE
non-integer lot count

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#2224]
UAM@ARCTOS> select guid from flat,specimen_part,coll_object where flat.collection_object_id=specimen_part.derived_from_cat_item and specimen_part.collection_object_id=coll_object.collection_object_id and lot_count!=round(lot_count);

GUID
------------------------------------------------------------------------------------------------------------------------
DMNS:Mamm:9326
DMNS:Mamm:8415
DMNS:Mamm:8416
DMNS:Mamm:8417
DMNS:Mamm:8418
DMNS:Mamm:8419
DMNS:Mamm:8421
DMNS:Mamm:8422
DMNS:Mamm:8423

9 rows selected.

I will at some point be forced to ROUND() those if they are not manually fixed before.

@acdoll

**Comment by dustymc** [comment]
Below are the records that will be updated as part of next release.

```

select guid,lot_count,round(lot_count) from flat,specimen_part,coll_object where flat.collection_object_id=specimen_part.derived_from_cat_item and specimen_part.collection_object_id=coll_object.collection_object_id and lot_count!=round(lot_count);


       guid        | lot_count | round 
-------------------+-----------+-------
 DMNS:Mamm:8415    |       2.5 |     3
 DMNS:Mamm:8417    |       1.5 |     2
 DMNS:Mamm:9326    |       1.5 |     2
 DMNS:Mamm:8416    |       1.5 |     2
 DMNS:Mamm:8418    |       1.5 |     2
 DMNS:Mamm:8422    |       3.5 |     4
 DMNS:Mamm:8419    |      2.75 |     3
 DMNS:Mamm:8421    |       1.5 |     2
 NMMNH:Paleo:35052 |       2.5 |     3
 DMNS:Mamm:8423    |      1.75 |     2


```

**Comment by acdoll** [comment]
This is fine with me. The part remarks clearly capture what they were trying to represent here. Thanks
