### ISSUE TITLE
[CONTACT]

### ISSUE THREAD

**Issue by jtgiermakowski** [ArctosDB/arctos#2226]
Trying to create a login for new student. I created a new person / agent but we cannot create a regular Arctos user account. see screenshot.

** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **

** Arctos Documentation is http://handbook.arctosdb.org/ **

** Learn more about Arctos at https://arctosdb.org/ **

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **
![newlogin](https://user-images.githubusercontent.com/2381228/63456690-b7929780-c40c-11e9-9827-54310cf0dcac.png)

**Comment by dustymc** [comment]
Click Sign In not Create Account
