### ISSUE TITLE
geography cleanup request: South Africa

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#2227]
It's a mess, someone help please!

**Comment by mkoo** [comment]
I will take that on... we have significant So Africa holdings.

**Comment by mkoo** [comment]
Update: The 9 current provinces of South Africa are fixed up with WKTs.
-- have not done anything for lower admin than state/prov. We have two municipalities
-- have not done anything for SA islands; we have two islands
-- have not done anything with obsolete state/prov (prior to 1994)

For the last one, I am inclined to keep obsolete references so they match their verbatim locality for now. Perhaps just a note in Remarks that this province/ HG designation is obsolete?

**Comment by Jegelewicz** [comment]
> For the last one, I am inclined to keep obsolete references so they match their verbatim locality for now. Perhaps just a note in Remarks that this province/ HG designation is obsolete?

I'm good with that - but we need to add this treatment to documentation so we don't do something different next time!

**Comment by mkoo** [comment]
I agree-- do we need to discuss at the AWG or can I just propose here and
now?

OK, ok, I'll file an issue actually!

**Comment by dustymc** [comment]
>add this treatment to documentation

That's 

~~Use current definitions. Yugoslavia no longer exists, so use Slovenia, Croatia, or whichever country the locality is now in. If Yugoslavia was used in the original data, it now belongs in verbatim locality, not in Higher Geography. If you are editing specimen records, append the old higher geography to verbatim locality in the following order: verbatim_locality, state, country.~~

Could probably use some elaboration, but the history is that we agreed to use "modern" geography and immediately figured out there's just no practical way to do that detective work.

**Comment by Jegelewicz** [comment]
Just do it.

**Comment by dustymc** [comment]
>WKTs

And we now have a few hundred more annotations....
