### ISSUE TITLE
Map Citations for Localities

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#2229]
I am trying to figure out where to put the map data that is in our locality files. Our locality records have fields for USGS 7.5' Topo maps and a second field for another map, usually filled in with a USGS 1:100,000 Topo map. These map references have a triple function in our collection:

1. Reference Source, particularly for older localities
2. Higher Geography - the 7.5' quads are used as sub-county level geography throughout our collection, including in the physical organization of our specimens. I need to be able to search for localities by 7.5' quad name.
3. Publication - Maps are publications and I'd love to be able to treat them as a publication in Arctos and link out to a url where the map can be accessed, downloaded, etc. ex. [San Juan, NM 7.5' Quad](https://catalog.data.gov/dataset/usgs-us-topo-7-5-minute-map-for-san-juan-pueblo-nm-20130a188)

There are not currently any Locality fields that would make these map names usable for all of these purposes. I could put it in Reference Source, but that would limit it's function as Higher Geography and Publication.

Would it be possible to add some sort of citation field into Locality? This would allow me to both link out to localities and search for localities based on map name. I would then separately put the map name into reference source as appropriate. A locality citation field would also be useful for journal articles, etc. about a locality, especially if specimens are not cited.

I suppose it might be added to the higher geography hierarchy, but that seems like it could make things really difficult (maps that cross borders, maps of different scales, etc.)

**Comment by Jegelewicz** [comment]
> Would it be possible to add some sort of citation field into Locality?

I like this idea.

**Comment by Jegelewicz** [comment]
> I would then separately put the map name into reference source as appropriate.

Or what about specific locality? Perhaps your spec_loc could always begin with the map title. Not perfect as there is the possibility for inconsistent naming of specific localities, but once you had them in, you could find and merge them.

**Comment by dustymc** [comment]
>Reference Source

Localities are modeled as spatial facts (and some metadata hanging awkwardly off the side). We've talked about denormalizing at various times, but it's major surgery and a major change in how we'd see spatial data. Is this better in specimen-event perhaps?

>quads

http://handbook.arctosdb.org/documentation/higher-geography.html#map-name-quad

>link

That's why Media exists - add "something or another geog_auth_rec" to the code table and it'll work (although I'll probably need to do something with the UI).

>hierarchy...maps that cross borders

Geography is not hierarchical, for just that reason.

**Comment by Jegelewicz** [comment]
OK cool - @Nicole-Ridgwell-NMMNHS I think you should add the quads as needed. If you want to see how they look just search geography for state = Alaska.

@dustymc could she put the link to the map in as an additional geography search term? It would be great if she could put it in the Authority, but currently we are limiting that to Wikipedia?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Currently the quads in higher geography are limited to 1:250,000 maps. If we changed that, or could included another level for 7.5' 1:24,000 quads that could work.

I didn't think about attaching it as media, which doesn't seem very different than a citation would function. However, since it seems like it would be possible to include the 7.5' quads as higher geography, that solution seems like it would be the most functional solution for us.

> Localities are modeled as spatial facts (and some metadata hanging awkwardly off the side). We've talked about denormalizing at various times, but it's major surgery and a major change in how we'd see spatial data. Is this better in specimen-event perhaps?

I would only put the map in as the locality reference source if the coordinates we upload to locality originate from that map. Say 30 years ago, someone found this locality and used a topo map to find the coordinates of the site, and those coordinates are still the main coordinate we have in our locality file. We're not georeferencing yet, so that map is still the reference source for that locality. If we did georeference that locality, the reference source would change. Is that correct usage of that field?

**Comment by dustymc** [comment]
>quads

I don't think I care, as long as there's some "official" name - eg, we can't have "Fairbanks Quad" meaning 17 different THINGS. "Fairbanks" and "Fairbanks D3" (or whatever) seems usable, I think. They'd be different sizes, but so it everything else in geography.

@amgunderson ??

>locality reference source

I think that's http://handbook.arctosdb.org/documentation/locality.html#reference-source, although there may be some (unjustified?) coordinate implications somewhere in there.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> I don't think I care, as long as there's some "official" name - eg, we can't have "Fairbanks Quad" meaning 17 different THINGS. "Fairbanks" and "Fairbanks D3" (or whatever) seems usable, I think. They'd be different sizes, but so it everything else in geography.

So we're proposing to expand how we use quad in higher geography. We would need to change the description in the handbook, I propose the following:

"The name of the U. S. Geological Survey topographic map quadrangle. The name of the quad must include the map scale. Ex. 'Ambler River 1:250,000 Quad' vs 'Ambler River A-4 SW 1:25,000 Quad. The 1:250,000 series has been used because Alaska lacks anything as inclusive counties; “quads” have been used extensively in organizing collections and interrogating data (Although note that a combination of Borough and Census Area is all-inclusive and mutually exclusive and therefore serves as a suitable if large-scale “county substitute.”). Finer scale quads are used by other collections as sub-county level geography."

Unfortunately then all the AK quads would need to be renamed to include the map scale.

Alternatively we could add new levels to the higher geography for 1:100,000 and 7.5 minute quads (these are usually 1:24000, but sometimes 1:25000).

Finally, it would be great to be able to put the .gov reference into the source field, for example:
https://www.sciencebase.gov/catalog/item/5a8a39bde4b00f54eb3e23fe
and 
https://catalog.data.gov/dataset/usgs-us-topo-7-5-minute-map-for-ambler-river-a-4-sw-ak-2015

**Comment by Jegelewicz** [comment]
Updated documentation. Leaving open for pending addition of other quads

**Comment by Jegelewicz** [comment]
Higher Geography Bulkload

@dustymc Here are the higher geography with map quads we need loaded for NMMNH Paleo. Let me know if anything seems crazy.

[Quad Maps.zip](https://github.com/ArctosDB/arctos/files/3970091/Quad.Maps.zip)

**Comment by dustymc** [comment]
It all seems crazy right now!

Worst case, this looks easy enough to recover if we do something drastic in https://github.com/ArctosDB/arctos/issues/1366. Want me to SQL them in?

**Comment by Jegelewicz** [comment]
> Want me to SQL them in?

Yes please!

**Comment by dustymc** [comment]
Rules caught these in source:

```
https://ngmdb.usgs.gov/ht-bin/tv_browse.pl?id=3562fa30270bc90707afe571bfa165e5
https://ngmdb.usgs.gov/ht-bin/tv_browse.pl?id=559d0ac47d00e0b4f5eede6af09bbc89
```

And I noticed some UTF fail:

```
https://en.wikipedia.org/wiki/Do%C3%B1a_Ana,_New_Mexico
https://en.wikipedia.org/wiki/Do%C3%B1a_Ana_County,_New_Mexico
https://en.wikipedia.org/wiki/Do�a_Ana_County,_New_Mexico
```

<img width="1185" alt="Screen Shot 2019-12-16 at 3 09 46 PM" src="https://user-images.githubusercontent.com/5720791/70950669-22985780-2016-11ea-800e-ae8cd3fe194e.png">

**Comment by Jegelewicz** [comment]
What do I need to do?

**Comment by dustymc** [comment]
Provide wiki source for those few without it, fix the broken URL, try to confirm that there are no other UTF conversion failures (I didn't see any, but more eyes is better...), resend.

**Comment by Jegelewicz** [comment]
OK try this.

[Quad Maps.zip](https://github.com/ArctosDB/arctos/files/3974474/Quad.Maps.zip)

**Comment by dustymc** [comment]
ORA-00001: unique constraint (UAM.IU_GEOGAUTHREC_HIGHERGEOG) violated

Did you already create some of these? If so, can you remove them from this file?

**Comment by Jegelewicz** [comment]
One more time.

[Quad Maps.zip](https://github.com/ArctosDB/arctos/files/3975022/Quad.Maps.zip)

**Comment by dustymc** [comment]
Got
```
ORA-20370: Detected double spaces.
```
so

```

update temp_ng set CONTINENT_OCEAN=replace(CONTINENT_OCEAN,'  ',' ');
update temp_ng set COUNTRY=replace(COUNTRY,'  ',' ');
update temp_ng set STATE=replace(STATE,'  ',' ');
update temp_ng set COUNTY=replace(COUNTY,'  ',' ');
update temp_ng set QUAD=replace(QUAD,'  ',' ');
```

but then..


```
ORA-00001: unique constraint (UAM.IU_GEOGAUTHREC_HIGHERGEOG) violated
```

There's still a duplicate somewhere.

**Comment by Jegelewicz** [comment]
URG! I checked them all against the quads in Arctos. Is there any way to figure out which one is the problem other than me trying them all in search?

**Comment by Jegelewicz** [comment]
OK - I found one dupe in the file itself. Let me review it and send another version.

**Comment by Jegelewicz** [comment]
Try this

[Quad Maps.zip](https://github.com/ArctosDB/arctos/files/3975527/Quad.Maps.zip)

**Comment by dustymc** [comment]
That one had a trailing NULL column so I did this:

<img width="287" alt="Screen Shot 2019-12-17 at 1 34 48 PM" src="https://user-images.githubusercontent.com/5720791/71036209-0f4ac200-20d2-11ea-9331-b9e5a9724950.png">

then

```
PL/SQL procedure successfully completed.
```
