### ISSUE TITLE
Geog cleanup: Major islands of Africa edition

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#2233]
Cleanup all the island higher geography in Africa -- about 23 in Arctos, includes cleaning up Seychelles. This will require island shapefiles -- highest res version for the WKT's

**Comment by sharpphyl** [comment]
Buried in issue #1314 (now closed) was a discussion of whether we should remove the entry under ISLAND GROUP if it is the same and contiguous with the COUNTRY itself.  The example was Fiji (COUNTRY) and Fiji Islands (ISLAND GROUP) which are identical.  Same for the Bahamas, Tonga, Cape Verde and more.

Also true for the COUNTRY Seychelles - officially Republic of Seychelles per https://en.wikipedia.org/wiki/Seychelles - and the ISLAND GROUP Seychelles Islands.  As a result, the Amirante Islands (a group of 29 islands) was not entered as an ISLAND GROUP in the Seychelles, but instead is listed under ISLAND even though there's no such island in the Seychelles.  

We have very few specimens from the Seychelles (all marine so outside terrestrial boundaries) but I'd love to see us continue to move away from the duplicate entry of the country name and island group.  Dusty's comment (Dec 18, 2017 in Issue #1314) does not seem to have made it into the Handbook (http://handbook.arctosdb.org/documentation/higher-geography.html#island-group):

> Is that all covered by
> 
> Terms which replicate both string and spatial data may be eliminated. For example, "Fiji" (country) and "Fiji Islands" (island_group which contains the string " Islands" only by convention) may be entered only as "Fiji" (country), thereby freeing "island_group" for smaller island groups within the island group which also serves as a country. Always follow the "Scrupulous consistency is essential" guidance in this operation; whatever is done must be done consistently at the largest possible scale.

Is this the time to begin to institute this approach (and update the Handbook)?  I certainly support doing so.  I've only updated Fiji where it didn't impact other collections but if we're ALL in agreement, I'd be happy to update more of the HG entries.

**Comment by campmlc** [comment]
I support this approach.

**Comment by Jegelewicz** [comment]
Sounds good to me.
