### ISSUE TITLE
Please remove 'ID by kin' as default for data entry form

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#2241]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

We now no longer have 'ID of kin' as default when creating a new identification for a record but it remains default in the data entry screen. I just had to tell a new lab tech to go back and change 60 odd records he made with 'id of kin' by mistake. 

**Describe the solution you'd like**
Please set the default to NULL and require a value.

**Describe alternatives you've considered**

**Additional context**

**Priority**
Please assign a priority-label. high

**Comment by dustymc** [comment]
done
