### ISSUE TITLE
[CONTACT] Photo upload error

### ISSUE THREAD

**Issue by starkchris** [ArctosDB/arctos#2242]
In attempting to upload photos I get the following error:

unique constraint (UAM.IU_MEDIA_MEDIAURI) violated

[Macromedia][Oracle JDBC Driver][Oracle]ORA-00001: unique constraint (UAM.IU_MEDIA_MEDIAURI) violated
Error Executing Database Query.

I was able to upload several images earlier in the day prior to getting this error. The naming convention for the images remains the same and I don't think it's anything I've done because I've double checked my process and nothing has changed on my end.  

** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **

** Arctos Documentation is http://handbook.arctosdb.org/ **

** Learn more about Arctos at https://arctosdb.org/ **

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **

**Comment by dustymc** [comment]
See http://handbook.arctosdb.org/documentation/understanding-errors.html#unique-constraint-iu_table_and_column-violated - you'll get that if the URI (which may or may not be the image you're trying to load) exists.

You can browse uploads from https://web.corral.tacc.utexas.edu/arctos-s3/
