### ISSUE TITLE
Scrolling for geology terms in search is limited

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2246]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
When I enter "series/epoch" in the geology attribute search field, I am presented with ALL geology terms in alphabetical order as a dropdown in the geology attribute value field, however, I can only scroll down through the first 25 or so terms, meaning I can never get to "pleistocene"

**To Reproduce**
1. Go to main search page
2. In Geology Attribute, select "Series/Epoch"
3. Place cursor in Geology Attribute Value
4. See all possible attributes in ABC order (I think?)

**Expected behavior**
I expect to see only those values that are "Series/Epoch" attrtibues or at least be able to scroll through the entire geology attribute list (ugh).

**Screenshots**
<img width="960" alt="Screenshot 2019-09-04 09 36 01" src="https://user-images.githubusercontent.com/5725767/64270223-70220600-cef8-11e9-9bb5-ef28e55a794d.png">

** Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**
 - OS: WIndows 10
 - Browser Firefox
 - Version 69.0

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
That's a suggestion, not a pick, it (like everything else) is not coupled to anything, and it is responsive.

<img width="485" alt="Screen Shot 2019-09-04 at 8 45 21 AM" src="https://user-images.githubusercontent.com/5720791/64270458-6a282700-cef0-11e9-9b47-d010b810cc23.png">

**Comment by Jegelewicz** [comment]
I figured that out, but I'm not sure that the 6th grade teacher would. Something to consider if we work on UI. Lowering priority.

**Comment by dustymc** [comment]
I think it's pretty common UI. If you're limited to something then there's a way to pick it, and no way to enter other stuff. If you're not limited then you can type whatever you want. In some cases we can suggest values that might do something useful, but they're just suggestions and can be ignored.
