### ISSUE TITLE
Search for a UTEP record with the geology attribute "Holocene" times out.

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2247]
When I go to search, all of the attributes are checked and I cannot "uncheck all". Clicking that option just does nothing.

<img width="960" alt="Screenshot 2019-09-04 14 16 51" src="https://user-images.githubusercontent.com/5725767/64288272-ecc7db00-cf1e-11e9-8fa3-88172687ccb0.png">

**Comment by dustymc** [comment]
That all runs in your browser....

**Comment by Jegelewicz** [comment]
So how do I uncheck them? One by one?

**Comment by ewommack** [comment]
Hmm works in my browser. Maybe try clearing your cache?

**Comment by Jegelewicz** [comment]
That worked. Thank you!!!
