### ISSUE TITLE
error feedback: bad username

### ISSUE THREAD

**Issue by soteropoulosd2** [ArctosDB/arctos#2248]
I was attempting to add the fish curator as an operator and assign him appropriate roles to manage the collections at Arkansas State University and received the following error:

A user that does not meet requirements was invited to become an operator.

I attempted to add the following user name: bfluker@astate.edu

Thank you!

**Comment by Jegelewicz** [comment]
The user name cannot be an email address for operators (the @ is not an allowed character).

See http://handbook.arctosdb.org/how_to/How-to-Create-your-Arctos-Team-Users-and-Operators.html#how-to-create-your-arctos-team-users-and-operators

**Comment by soteropoulosd2** [comment]
Thank you! I have asked the curator to login and change his username. Could we please add the unallowed characters (email addresses, @) to the documentation in "1. Have each team member create an Arctos user account?" I had referred to this documentation and only saw that periods are not allowed:

Do not include periods in your username (e.g., carla.cicero is not a valid username)

**Comment by dustymc** [comment]
This...

<img width="212" alt="Screen Shot 2019-09-05 at 6 28 31 AM" src="https://user-images.githubusercontent.com/5720791/64346116-68b93600-cfa6-11e9-9102-1596268d2e8e.png">

... links to this....

http://handbook.arctosdb.org/documentation/users.html, which should be authoritative.

How-tos are guidance. Perhaps we should be more explicit in that, and/or instruct authors not to denormalize (eg, just link to /documentation, don't try to replicate it). There are approximately 1,114,000 Unicode characters which are not allowed in usernames, and the howto lists one of them...

**Comment by soteropoulosd2** [comment]
Maybe there can be an error warning when a new user creates an account if the username violates these characters?

Can the username be changed after the fact? The curator just notified me that he only has the option to change his password.

**Comment by dustymc** [comment]
>error

There's an issue for that somewhere, but ~99% of users won't ever become Operators and I REALLY don't like the idea of burdening them will silly Oracle limitations. Reading the documentation is critical to this process.

Usernames cannot be changed - just create a new account.

**Comment by soteropoulosd2** [comment]
Thank you. I have asked him to create a new account to remedy this. I guess this documentation was not carefully read by all members when accounts were created. Not everyone sent me their account information during the initial setup to catch these errors.

**Comment by dustymc** [comment]
A second account will be handy anyway - eventually they'll want to download data from other collections and etc. I think most Operators have a few!

**Comment by srobson4** [comment]
@dustymc  - I'm having a similar problem, not allowed to invite a student as an operator.  I checked all of the documentation and not sure what the problem is: junelee; AgentID 21321583.  Thanks.

**Comment by dustymc** [comment]
>They must have an email address in their Profile. 

<img width="496" alt="Screen Shot 2019-10-02 at 11 32 51 AM" src="https://user-images.githubusercontent.com/5720791/66071683-6fd15680-e508-11e9-82fe-c522ad7394fe.png">

We semi-recently made it so you can just add it for them, or you can direct them to the "My Stuff" tab (or https://arctos.database.museum/myArctos.cfm).

**Comment by dustymc** [comment]
Aha! They have no user-data at all; that form can't deal with that. There's a hopefully-better error now.

```
 This form cannot create user data. Direct the user to http://arctos.database.museum/myArctos.cfm. 
```

**Comment by Jegelewicz** [comment]
@srobson4 I think they need to add info to their user profile. My stuff>Profile
