### ISSUE TITLE
Move create DOI to manage collection

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2249]
Need new issue to move create DOI to manage collection

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/arctos/issues/745#issuecomment-528503970_

**Comment by dustymc** [comment]
This should be documented first. Pulling DOIs comes with an implicit forever-commitment, and the manage_collection role is likely over-assigned.

To clarify, is this a request to grant INSERT on table DOI to manage_collection, or to move all roles on DOI to manage_collection?

**Comment by Jegelewicz** [comment]
Don't look at me...I just moved this here based on AWG discussion! I'll have to go see what all those roles are...

**Comment by Jegelewicz** [comment]
closing for lack of interest
