### ISSUE TITLE
Add Lake Cahuilla Formation to CTGEOLOGY_ATTRIBUTE

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#2254]
https://en.wikipedia.org/wiki/Lake_Cahuilla#Geography

Holocene and Pleistocene Epochs

Thanks.

**Comment by Jegelewicz** [comment]
This isn't a proper geology term as far as I can tell. I think it should just be part of your specific locality. @Nicole-Ridgwell-NMMNHS @dperriguey  thoughts?

**Comment by dperriguey** [comment]
@sharpphyl This doesn't look like a proper formation. I can't find anything on it anywhere. Do you have a picture of the card or page the original data came from?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Looks like the Lake Cahuilla deposits, like most holocene deposits, are not formally categorized as Formations.

You can find references to these deposits by searching google scholar for "salton sea lake cahuilla" and on the Salton Sea geology map it is grouped under Quarternary Lake Deposits.

I'll do a little more digging to find out if there is a way we could include deposits like this in our lithostratigraphy without calling them formations. This issue is likely to pop up again as we get more Quaternary localities in the database.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Apparently this article might reference it as a formation:
[Tectonic evolution of the Salton Sea inferred from seismic reflection data](https://www.researchgate.net/publication/252865695_Tectonic_evolution_of_the_Salton_Sea_inferred_from_seismic_reflection_data)

**Comment by dperriguey** [comment]
Here is a link to the full article where they reference the Cahuilla Formation in the second paragraph. Whether that is the same thing or not is for you to decide. Let me know if the link doesn't work. 
https://www.nature.com/articles/ngeo590.pdf

I think this brings up an important point of whether something is a fossil or not. This is another black hole for us to go down. It doesn't have to be, though. Just have to decide what is a fossil or not based upon some threshold (I'm guessing usually if it is in your collection as a fossil then it is). I'm not sure I would call things from Holocene deposits fossils given both the deposits and the fossils have undergone little to no lithification. It really is going to depend on the institution and the original data.

**Comment by dustymc** [comment]
Is there no way to know what's a formation-or-whatever and what's not?!?

There's absolutely no need to pigeonhole anything into "fossil" in Arctos. Preservation method is available for things that don't depend on random unrelated things, and "fossilness" (however you want to define it) could be extracted from that.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> Here is a link to the full article
Behind a paywall for me, waiting for a digital copy to come through on an ILL request.

> There's absolutely no need to pigeonhole anything into "fossil" in Arctos
Agreed. I think this is one paleo-debate we can step away from. Clearly 'not fossil' -> subfossil -> fossil is a continuum. Anyone pulling specimens from within this continuum knows that and will look for other clues (geology, preservation, carbon-dating results, etc.) to discern whether to include that specimen in their dataset.

**Comment by Jegelewicz** [comment]
[Wikipedia](https://en.wikipedia.org/wiki/Fossil): A fossil (from Classical Latin fossilis; literally, "obtained by digging")[1] is any preserved remains, impression, or trace of any once-living thing from a past geological age

If we are now in the Anthropocene, pretty much everything is a fossil.... :-)

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
The arbitrary cut-off point I've usually been given in paleo classes is 10,000 years old.

**Comment by dustymc** [comment]
If we can agree on some comprehensive definition of fossil, then I don't mind claiming that things are or are not fossils.

Depending on how the definition of Anthropocene works out, I'm guessing there's going to be some objections to calling everything that died before 1945 a fossil. The "living fossils" among us might have something to add to that conversation as well!

https://arctos.database.museum/guid/uam:es:4588 is well outside the 10K yr test and reportedly didn't taste particularly fossil-ey.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
[Definition of a Fossil](http://npshistory.com/publications/paleontology/fossil-definition.pdf) is a good summary of the issues that come up when trying to define a fossil. it concludes with the definition "Fossil: evidence of life preserved in a geological context. "

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Got the pdf for the 2009 Nature article referencing Cahuilla Formation. My opinion is now that we can add it as a formation.

> Is there no way to know what's a formation-or-whatever and what's not?!?

For the more obscure lithology you just have to dive into the literature to see if someone has described and defined it. Lithology is similar to taxonomy in this respect.

**Comment by sharpphyl** [comment]
Sorry to be late to give you feedback.  The formation name came from the label the shell dealer supplied with the shell to the purchaser who then donated it to us.  None of us has special knowledge of geologic formations, so we appreciate your review and assessment.  We can do it as a formation (which your research seems to support) or a specific locality.

**Comment by Jegelewicz** [comment]
Added Cahuilla Formation. Thanks everyone!

**Comment by Jegelewicz** [comment]
BTW @Nicole-Ridgwell-NMMNHS that article is enlightening! This passage:

> As  most  paleontologists  recognize  and  advocate,  the  geologic  context  in  which  fossils  occur  provides  some  of  the  most  important  information  regarding the  fossil.  Fossils  removed  from  strata  without  docu-mentation  of  the  associated  geologic  and  stratigraphic   data  have  limited  value  to  science.  The  associated  geologic  informa-tion  can  yield  valuable  information   rel-evant to the fossil  including: climate, sedi-mentary  environment,  age,  contemporary  organisms  and  other  data.  

especially so. Could we use the fact that geological context is provided to determine what is "fossil" and what is not? (Not that it would be perfect, but it would make those "fossils" more valuable from a scientific perspective....)

**Comment by dustymc** [comment]
I am 100% certain that pigeonholes make EVERYTHING less valuable from ALL perspectives, except perhaps from within the pigeonhole for users who fully understand the boundaries.

If some user thinks "things with geology" are fossils, they can just search for things with geology.

If another user thinks "things preserved by mineralization" are fossils, they can search for that.

Etc. Providing the data we know in a discoverable format and letting users decide what to do with it lets them ask the questions they want to ask, not just those we've anticipated.


>limited value to science.

Perhaps, but they do have value. A user might want to know if there are dinosaurs from Alaska, for example. There are currently...

```
select count(distinct(cataloged_item.collection_object_id)) from cataloged_item,identification,identification_taxonomy,taxon_term,specimen_event,collecting_event where 
cataloged_item.collection_object_id=identification.collection_object_id and
identification.identification_id=identification_taxonomy.identification_id and
identification_taxonomy.taxon_name_id=taxon_term.taxon_name_id and
taxon_term.term='Dinosauria' and
cataloged_item.collection_object_id=specimen_event.collection_object_id and
specimen_event.collecting_event_id=collecting_event.collecting_event_id and
collecting_event.locality_id not in (select locality_id from geology_attributes)
  9  ;

COUNT(DISTINCT(CATALOGED_ITEM.COLLECTION_OBJECT_ID))
----------------------------------------------------
					      341673

````
a lot of non-fossil dinosaurs. (That number is crazy because NCBI thinks birds are dinosauria - not wrong, but not terribly useful here either...). Someone searching in the context of a 'fossil yes/no' flag is fairly likely to use it without fully understanding the implications, and not find what they want.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> If some user thinks "things with geology" are fossils, they can just search for things with geology.

> If another user thinks "things preserved by mineralization" are fossils, they can search for that.

Agreed!
