### ISSUE TITLE
Do we need anything from TACC staff??: One on One appointments at TACCSTER 2019

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#2257]
Sorry for procrastinating on this!! Diana and I are going to the TACCSTER meeting at the end of the month. I just noticed on their website that they are offering one on one meetings with TACC staff. Is there anything we need from them that could benefit from a one on one appointment from their staff? I figured I would ask, but I need to know by **Sept 13th**

Details here: https://www.tacc.utexas.edu/taccster

**Comment by Jegelewicz** [comment]
I don't know if we need to speak to anyone besides Chris Jordan right now? @dustymc ?

**Comment by dustymc** [comment]
No, I'm pretty happy with everything, don't have any specific requests.

**Comment by mvzhuang** [comment]
Ok thanks everyone
