### ISSUE TITLE
carapace: orphaned attributes

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#2259]
curved carapace length
straight carapace length

are somehow not in the code table, but are in the data.

UAM@ARCTOS> select guid from flat where collection_object_id in (select collection_object_id from attributes where attribute_type  not in (select attribute_type from ctattribute_type ));

GUID
------------------------------------------------------------------------------------------------------------------------
MSB:Herp:95597
MSB:Herp:78221
MSB:Herp:95583
MSB:Herp:95611
MSB:Herp:95592
MSB:Herp:78220
MSB:Herp:95598
MSB:Herp:98879
MSB:Herp:99475
MSB:Herp:99476
MSB:Herp:99473
MSB:Herp:99472
MSB:Herp:99474

@jtgiermakowski  do we need those attributes added or can I update them to something else or ???

http://arctos.database.museum/info/ctDocumentation.cfm?table=CTATTRIBUTE_TYPE&coln=Herp

**Comment by mkoo** [comment]
Mariel will add the attributes 
carapace length, curved 
carapace length, straight 

- but will need to review all attributes before migration to Postgresql

**Comment by campmlc** [comment]
Added 10-3-19
