### ISSUE TITLE
Help retrieving archived data?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2263]
@dustymc I added a publication about a month ago and have been editing records to get them corrected according to the publication. I want to create a comparison of Arctos records before and after this process, unfortunately, I did not perform a download before I started making corrections.  The publication is http://arctos.database.museum/publication/10008480

Can you get me the data from before I entered that publication for all records that are vouchers in the publication? Specifically, identifications, collection/specimen event info, parts, other identifiers, relationships (with other identifiers), and attributes?

Let me know if this isn't clear!

**Comment by dustymc** [comment]
I think we have those data so yes in theory, but it's probably a ~week of work (for Lam).

See also http://handbook.arctosdb.org/documentation/catalog.html#understanding-specimen-records - you would need to be a lot more specific. Do identifications include agents? As they were then or now? Do agents include addresses and ...? Etc.

**Comment by Jegelewicz** [comment]
Never mind then - I'll just write a paper on the next bunch of poor quality data.
