### ISSUE TITLE
Fork-edit event + georeferencing bug

### ISSUE THREAD

**Issue by anna-chinn** [ArctosDB/arctos#2265]
**Describe the bug**
When I hit use the GeoLocate API within the Fork-edit specimen event tool, the entire event editing window closes when I hit 'Save to Application' and I lose my coordinates and event edits.

**To Reproduce**
Steps to reproduce the behavior from a specimen record page:
Edit locality --> Fork-edit --> Georeference with GeoLocate --> Select coordinates --> Save to Application

**Expected behavior**
The fork-edit specimen event window should stay open and the coordinates/error should have been saved from GeoLocate to the corresponding Arctos fields.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome version 76.0.3809.132

**Comment by dustymc** [comment]
woops....fixed

**Comment by anna-chinn** [comment]
Thanks!
