### ISSUE TITLE
Create attribute fields for Time Stamp data? (incoming collections)

### ISSUE THREAD

**Issue by diannakrejsa** [ArctosDB/arctos#2266]
I'm investigating what to do with already existing time stamps on records as they are migrated into Arctos from another database (in our case, Specify). 

Can we add attributes like "Original DB Create Date" and "Original DB Last Modified Date" and "Original DB Last Modified By Agent" to Arctos? Or, are there too many attributes as it is and these data should be concatenated into the COLLECTION_OBJECT_REMARKS field if retained?

Looking for input from database programmer & managers of Arctos as well as new members migrating data in.

**Comment by dustymc** [comment]
Moving this to the main repo.

See https://github.com/ArctosDB/arctos/issues/1623 especially https://github.com/ArctosDB/arctos/issues/1623#issuecomment-530457331

I think this is just the usual question: who cares; what would someone want to DO with these data? From there, we can discuss how best to structure them.

**Comment by diannakrejsa** [comment]
To me, these data are useful simply for tracking errors, when they were made, by whom, and when the record was last examined semi-closely. When were updates really last done. 

If the new time stamp will be 2019 by Dianna M. Krejsa, it's a little misleading since I won't have looked at every piece of data on that record carefully on that date (if that is implication of last modified and by what agent).

**Comment by dustymc** [comment]
I think a remarks field fully supports that use case, and structured data in a remarks field would be easy to extract for closer examination if we find a reason to do so.

I'm not sure anyone ever looks at every piece of data on a record carefully. (Is the specimen-->citation-->publication-->third author-->agent-->address[home phone number] really correct? It's definitely "part of the record," at least from some perspectives...) 

The person bulkloading likely has much more ability to muck up a few thousand records than any previous person did, and I think having that is the most critical "whodunit" field. That aside, I could potentially sql-update entered or edited agent and date after the load, if that better addresses your concerns.

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/new?assignees=&labels=Function-CodeTables&template=authority-request.md&title=Code+Table+Request+-+ if this is still an issue.
