### ISSUE TITLE
Arctos down?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2269]
Is Arctos down, or is my internet connection just bad? (I'm traveling, so it could be the second...)

**Comment by dustymc** [comment]
Yes, google got a little excited and took down the web layer. It should be back in a few minutes.

**Comment by lin-fred** [comment]
Good to hear!

**Comment by Jegelewicz** [comment]
Great Google-y Moogly!

**Comment by dustymc** [comment]
it's up
