### ISSUE TITLE
GBIF links to Arctos

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#2273]
The occurrence records in GBIF are not linking to our DMNS specimens correctly. If I am not logged into Arctos, the Reference link on GBIF goes to a 404 page (e.g. https://www.gbif.org/occurrence/2273764897). If I am logged into Arctos it takes me to the specimen record as expected. I tested a few MVZ specimens also (while not logged in to Arctos) and some worked fine (https://www.gbif.org/occurrence/2273776942) while others didn't (https://www.gbif.org/occurrence/2382391770).

**Comment by acdoll** [comment]
After further investigation, I see that our DMNS:Inv and DMNS:Egg specimens are linking properly. These are the two collections of ours that I did not mess with the collection Metadata to generate EML's for GGBN. Did I screw something up while doing that?

**Comment by dustymc** [comment]
My fault - should be fixed, but will take a few hours to rebuild. Thanks!

**Comment by dustymc** [comment]
Looks like everything rebuilt, closing
