### ISSUE TITLE
locality attributes

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#2274]
ref: https://github.com/ArctosDB/data-migration/issues/75

Should we generalize geology to "locality attributes"? 

If we do, should we also better normalize the core locality model by pushing everything that's not necessary to define shapes (with standardized units) to the attributes table?

This seems like a much better "compromise model" - it would allow completely normalized localities while also allowing anyone to add any number of denormalizers if they wish to treat localities more like specimen metadata and less like spatial facts.

**Comment by campmlc** [comment]
I agree with this. What would be pushed to attributes?

**Comment by dustymc** [comment]
>e pushed to attributes?

I'm hoping you'll tell me, or tell me what you want to DO with locality data and we'll go from there. Here are the spatial data:


UAM@ARCTOS> desc locality
 Name								   Null?    Type
 ----------------------------------------------------------------- -------- --------------------------------------------
 LOCALITY_ID							   NOT NULL NUMBER
 GEOG_AUTH_REC_ID						   NOT NULL NUMBER
 ~~SPEC_LOCALITY								    VARCHAR2(255)~~
 DEC_LAT								    NUMBER(12,10)
 DEC_LONG								    NUMBER(13,10)
 MINIMUM_ELEVATION							    NUMBER
 MAXIMUM_ELEVATION							    NUMBER
~ORIG_ELEV_UNITS							    VARCHAR2(30)~
 MIN_DEPTH								    NUMBER
 MAX_DEPTH								    NUMBER
~~DEPTH_UNITS								    VARCHAR2(30)~~
 MAX_ERROR_DISTANCE							    NUMBER
~~MAX_ERROR_UNITS							    VARCHAR2(30)~~
~~DATUM									    VARCHAR2(255)~~ 
~~LOCALITY_REMARKS							    VARCHAR2(4000)~~
~~GEOREFERENCE_SOURCE							    VARCHAR2(4000)~~
~~GEOREFERENCE_PROTOCOL							    VARCHAR2(255)~~
 LOCALITY_NAME								    VARCHAR2(255)
WKT_MEDIA_ID								    NUMBER


I'm not sure there's any particular reason to store data that way - eg, maybe storing spatial data as "locality data" makes more sense if we have a place for the text. Converting everything to spatial would also open up the possibility of things like irregular shapes ("within 3 miles of here, but on this side of the road"), probability surfaces ("New Mexico, 10,000 feet" should map like a half-dozen squished donuts that fade in somewhere below 10K' and out somewhere above), and generally make things like "halfway down the pit we dug in the lake floor inside the submerged cave" easy and unambiguous. @tucotuco might even make it all easy for us....

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Having locality attributes would go a long way for NMMNHS Paleo in trying to get our locality data to fit within Arctos's structure.

**Comment by Jegelewicz** [comment]
> If we do, should we also better normalize the core locality model by pushing everything that's not necessary to define shapes (with standardized units) to the attributes table?

This makes sense to me.

Should we consider "locality" as a representation of the 2D surface area of planet Earth? Then anything that doesn't contribute to that becomes an attribute? Oddly, (or not?) that would make elevation and depth attributes. Correct?

**Comment by dustymc** [comment]
There you go again, I was just headed over here to say that...

Yes! "500 feet above Asia" is just about useless from a spatial standpoint, and therefore may belong in some non-spatial place. When possible it could be converted into elevation (which needs better defined - we probably need a vertical datum) and used to make shapes, with the original 'references' data in attributes.

**Comment by dperriguey** [comment]
I'm comfortable with generalizing geology to locality attributes.

**Comment by campmlc** [comment]
What is required for implementation?

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/2274#issuecomment-534349023
https://github.com/ArctosDB/arctos/issues/2282#issuecomment-540648398

I think essentially

* discussion - anyone see a reason not to do this, or to do it radically different than the various other kinds of attributes, or ???
* prioritization
* maybe finer-scaled prioritization - eg, if we're going now can/should we put off rebuilding the bulkloader, or perhaps build this as an addition to instead of a replacement for geology until we're in PG, or should we fully implement, or ???????

**Comment by campmlc** [comment]
sounds like folks are having difficulty with the bulkloader now because of
the nature of ID issue. Perhaps we should resolve that first, so we don't
hang up data entry further. I would not want to add another bulkloader
rebuild if it will cause further delays for data migration.

**Comment by campmlc** [comment]
On the other hand, NMMNHS data migration may depend on resolution of this.
Can we resolve in theory, and then set up to bulkload locality attributes
at a later time so Teresa and Nicole can move forward?
@Teresa Jegelewicz Mayfield <jegelewiczt@unm.edu>

**Comment by Jegelewicz** [comment]
> 
    discussion - anyone see a reason not to do this, or to do it radically different than the various other kinds of attributes, or ???

I had hoped to bring this up at issues meeting, but was unable to attend due to being in Alabama. I hate to wait another month.

>  prioritization
>    On the other hand, NMMNHS data migration may depend on resolution of this.

It does. I am under a time crunch to get as much of their data into Arctos as possible and these attributes are one thing holding up the works.

>     maybe finer-scaled prioritization - eg, if we're going now can/should we put off rebuilding the bulkloader, or perhaps build this as an addition to instead of a replacement for geology until we're in PG, or should we fully implement, or ???????

There are two ways I could handle this for now.

1. The way I did in [NMMNH:Paleo:1](http://arctos.database.museum/guid/NMMNH:Paleo:1) which is put them in a logical order in locality remarks. My argument against this is that it does not facilitate search in the way NMMNH staff is used to. This means they will develop bias against Arctos and I don't want that!

2. What Dusty suggested - I could just add stuff to the Geology table. This will create a whole bunch of weird geology attributes, but that might be easier to port to locality attributes later and they will be searchable in the way NMMNH staff is used to (I think - there might be some funky things - I would need to think about all of the various attributes (and maybe just try them out in the Geology Code Table to see if they work the way I would expect).

I'm open to being flexible, but I also want these guys to like their data. If they aren't happy, word will get around the paleo community and we might lose out on more paleo collections....

**Comment by dustymc** [comment]
>add stuff to the Geology 

Sorry I wasn't clear, and particularly in light of your comments (which sound about right), here's the seed of a hopefully-clear expansion/clarification/proposal:

1) build a new table
2) add data
3) don't even set up data controls yet (I don't think this stuff gets edited much - can they be really careful for a few weeks??)
4) Really simple UI to edit it on editlocality
5) add really simple search capabilities
6) add simple display in the minimum number of places

That's it for now. We'd have to come back later to add more control (and perhaps clean the data more), merge the current geology data in (and eliminate that table once it's done), rebuild the bulkloader, spiffy up the UI, sprinkle access around, etc.

I could do that pretty quickly. It provides a safe place for the data AS LONG AS THEY'RE CAREFUL, string-match search capability, and display in the "core" places.

That's based on the assumption that this will be a bulkload of named localities, and they'll load specimens against it using the locality name (for now). If that's not the case this may not be viable. If they don't want to deal with primitive-but-functional forms this absolutely isn't a viable proposal. If there's any indication that anyone will judge Arctos on these explicitly-primitive and very temporary forms then let me know ASAP and I'll delete this comment (or you can, I'm about to disappear for the weekend).

IDK, maybe it's better to do it right or not at all. Just throwing out ideas....

**Comment by Jegelewicz** [comment]
> That's based on the assumption that this will be a bulkload of named localities, and they'll load specimens against it using the locality name (for now).

That is exactly the plan - about 12,500 of them!

I think this will be OK for now. Primitive data entry forms are fine - it's the search capability that concerns me (can we get this stuff into the main search page in some sorta pretty way?).

> IDK, maybe it's better to do it right or not at all. Just throwing out ideas....

I think doing it right the first time is always the BEST option, but it isn't always the easiest or most convenient. I think your idea above could work for now. What you created for Specimen Event attributes would be perfectly fine. Can you create that, but not add it to the bulkloader? Only allow data entry to those things via create locality? That would allow me to fill in the attribute vocabularies and then you could load our named localities along with their attributes?
