### ISSUE TITLE
whole organism for herbarium = tissue

### ISSUE THREAD

**Issue by KyndallH** [ArctosDB/arctos#2275]
The code table currently has "whole organism" definition as "enitre organism in ethanol-glycerin mixture" which is the wrong definition. Beyond that, it is listed as not a tissue which is fine for most collections EXCEPT for herbarium. For herbarium, Steffi counts the whole organism as a tissue sample and is what she often loans out for tissue. The issue is that those samples are not getting pushed to GGBN since it is flagged as not a tissue. Is there a way to have TWO "whole organism" in the code table. One for all the other collections that is not a tissue and one that is tissue for the three UAM herb collections? 

<img width="1209" alt="Screen Shot 2019-09-24 at 10 08 38 AM" src="https://user-images.githubusercontent.com/16887896/65538496-e7253b80-deb3-11e9-8490-bd50158d2dc4.png">

Need this resolved soonish as we are trying to get this data published on GGBN.

**Comment by dustymc** [comment]
>definition

Yikes. Maybe "Entire organism; preparation and preservation information not given." ??

>TWO "whole organism" in the code table

No, that's evil....

Maybe just flip the tissue flag?

**Comment by KyndallH** [comment]
That definition works for me.

Really, can't have the same name on the code table with the collection and flag different? 
Flipping the flag screws up all the other collections. :/ We could just leave as is and simply not push that data to GGBN - not ideal but more ideal then changing the flag on all the other collections. At least, my opinion.

**Comment by dustymc** [comment]
>same name on the code table with the collection and flag different?

That would absolutely guarantee that nobody could find what they want.

>other collections

There are 49 variations of "whole organism" at the moment. I think you're only talking about the most vague (plain ol' "whole organism"). Tissue-ifying that doesn't seem too evil to me, but ???

```

select
  guid_prefix,
  count(*) c
from
  collection,
  cataloged_item,
  specimen_part
where
  collection.collection_id=cataloged_item.collection_id and
  cataloged_item.collection_object_id=specimen_part.derived_from_cat_item and
  part_name='whole organism'
group by
  guid_prefix
order by
    guid_prefix
 16  ;

GUID_PREFIX							      C
------------------------------------------------------------ ----------
CHAS:Ento							      1
CHAS:Herb							    151
DMNS:Bird							     55
DMNS:Mamm							     38
DMNS:Para							      3
KNWR:Ento							     39
KNWR:Herb							   2402
KNWR:Inv							      2
KWP:Ento							  24014
MLZ:Herb							     15
MSB:Bird							      1
MSB:Fish							    313
MSB:Herp							   2771
MSB:Mamm							    685
MSB:Para							   6209
MVZ:Herp							    891
MVZ:Mamm							      2
OWU:Fish							     22
OWU:Mamm							      6
OWU:Para							      5
OWU:Rept							    210
UAM:Alg 							   4639
UAM:Ento							    839
UAM:Fish							    217
UAM:Herb							 200549
UAM:Inv 							    117
UAM:Mamm							    213
UAMObs:Ento							    854
UAMObs:Fish							      2
UAMb:Herb							  59573
UCM:Fish							     10
UCM:Herp							      5
UCM:Mamm							      1
UNR:Fish							     44
USNPC:Para							      1
UTEP:Ento							    362
UTEP:Herb							  84103
UTEP:Herp							    159
UTEP:Inv							     21
UWBM:Herp							    253
WNMU:Mamm							      1

41 rows selected.
```

**Comment by campmlc** [comment]
This could be solved by separating part from preservation, which we have
started but not yet completed.

**Comment by Jegelewicz** [comment]
>  "Entire organism; preparation and preservation information not given."

Agree

Whole organism seems like it is the ultimate tissue to me. I am in favor of flipping the tissue flag for whole organism. If someone using it doesn't want their stuff to be flagged as tissue, then they could say why by selecting one of the other "whole organism" parts that definitely should not be called tissue. For instance, "whole organism, formalin-fixed".

**Comment by Jegelewicz** [comment]
> This could be solved by separating part from preservation, which we have started but not yet completed.

Anyone CAN do this right now, but no one is making use of it and it will require a change to how we choose tissues now for GGBN because we would now need to look at both the part name AND the preservation attribute(s) to determine which should be considered "tissue".

**Comment by campmlc** [comment]
Agree, but that should be the model we move towards. How can we bridge the
gap?

**Comment by dustymc** [comment]
>bridge the gap?

See https://github.com/ArctosDB/arctos/issues/1875 - "tissueness" will require a 'tissue-giving' attribute. These could be immediately moved to 'whole organism (something that causes tissueness)." https://arctos.database.museum/info/ctDocumentation.cfm?table=CTPART_PRESERVATION

Maybe "dry" should cause tissues, or we need a new 'pressed' or ???

**Comment by Jegelewicz** [comment]
I think we have had the "pressed" discussion already and technically, aren't all herbarium specimens on a sheet really "whole organism (dry)"? (Even if they are only a branch and NOT the whole tree....but I believe that is also a discussion we have had.)

**Comment by Jegelewicz** [comment]
Maybe that would help @KyndallH feel better - if we made all herbarium sheets "whole organism (dry)" and flagged that part as "yes" for tissue? Who is using that?

Also, that definition seems more appropriate for herbarium specimens:

> Entire organism (or representative portion thereof), preserved by drying.

**Comment by dustymc** [comment]
Yes, sorry, I wasn't clear.

Bare parts will not be tissues in the model we're moving towards; tissues require some tissue-giving preservation attribute (and no tissue-killing attributes).

If "dry" can cause tissueness then this is easy; we can update now, which will make the eventual migration easy.

If there's some form of "dry" that doesn't cause tissues then we need two non-overlapping terms.

Here are users.

```
select
  guid_prefix,
  count(*) c
from
  collection,
  cataloged_item,
  specimen_part
where
  collection.collection_id=cataloged_item.collection_id and
  cataloged_item.collection_object_id=specimen_part.derived_from_cat_item and
  part_name='whole organism (dry)'
group by
  guid_prefix
order by
    guid_prefix
 16  ;

GUID_PREFIX							      C
------------------------------------------------------------ ----------
CHAS:Bird							      7
CHAS:Ento							     63
CHAS:Fish							      3
CHAS:Inv							  16421
CHAS:Teach							    163
DMNS:Inv							    350
DMNS:Mamm							      1
KWP:Ento							  15935
MSB:Bird							    114
MSB:Fish							    112
MSB:Herp							    254
MSB:Host							     14
MSB:Mamm							      4
MVZ:Bird							      1
MVZ:Herp							     40
MVZ:Hild							     28
UAM:Ento							   3442
UAM:Fish							     67
UAM:Herp							      1
UAM:Inv 							   8154
UAM:Mamm							      2
UAMObs:Ento							      2
UCM:Bird							     12
UCM:Fish							     23
UCM:Herp							    101
UCM:Mamm							      3
UMNH:Bird							      1
UMNH:Herp							     11
UMNH:Mamm							     20
UNR:Fish							     49
UNR:Herp							      1
UWBM:Herp							      9

32 rows selected.
```

**Comment by dustymc** [comment]
Merge-->https://github.com/ArctosDB/arctos/issues/1875#issuecomment-834722169
