### ISSUE TITLE
ambiguous relationships

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#2278]
https://www.globalbioticinteractions.org/2019/07/10/associating-with-natural-history-collections/ exists, and I was recently asked about interactions in Arctos on behalf of potential users. There are a bunch of base_urls that lead nowhere, or to ambiguous sets, in http://arctos.database.museum/info/ctDocumentation.cfm?table=CTCOLL_OTHER_ID_TYPE, and they make asking interaction/relationship questions difficult or impossible.

http://arctos.database.museum/SpecimenResults.cfm?oidtype=AMNH%3A%20American%20Museum%20of%20Natural%20History finds 780 specimens, all of them presumably linked to related specimens in GBIF. I clicked on a couple dozen and could not find anything in GBIF.

The NK on any of http://arctos.database.museum/SpecimenResults.cfm?oidtype=NK&oidoper=IS&oidnum=279667 links to the search result (currently 15 specimens).

Etc.

I also found a bunch of nonresolvable data in what should be resolvable identifiers - http://arctos.database.museum/guid/UTEP:Inv:7092 for example.

I propose a four-pronged approach

1. develop documentation clarifying that base_url in otherIDs should resolve to a single record
2. drop all base_urls that start with http://arctos.database.museum/SpecimenResults.cfm or https://www.gbif.org/
3. add a mechanism to check URLs formed by otherIDs with base_url.
4. add links in Arctos as necessary; it may somehow be useful to link eg, http://arctos.database.museum/guid/MSB:Para:27859 to all 15 specimens that share the NK number, but we should do so without degrading other data

(3) will fail for two reasons:

* things like https://www.gbif.org/occurrence/search?institution_code=amnh&catalog_number=DOT%2020778 return an "everything's happy" status code without finding specimens
* these are entered asynchronously; a reference to arctos.../some_guid may fail at the time it's created, but then work when another specimen is entered.

I think a real solution comes back to documentation and us not creating low-quality data, but perhaps we can catch some hopefully-few problems as well.

**Comment by Jegelewicz** [comment]
> I also found a bunch of nonresolvable data in what should be resolvable identifiers - http://arctos.database.museum/guid/UTEP:Inv:7092 for example.

I fixed that one - just caused by data entry error (I suspect we are never gonna stop that).

A report might help.

"You have relationships that are not resolvable"

Then we could fix stuff that is fixable.

**Comment by Jegelewicz** [comment]
Until we have a way to do this:

> add links in Arctos as necessary; it may somehow be useful to link eg, http://arctos.database.museum/guid/MSB:Para:27859 to all 15 specimens that share the NK number, but we should do so without degrading other data

We really need this:

> base_urls that start with http://arctos.database.museum/SpecimenResults.cfm

Otherwise it is a pain to find all of the parasites and their related host in a single search result.

**Comment by Jegelewicz** [comment]
> http://arctos.database.museum/SpecimenResults.cfm?oidtype=AMNH%3A%20American%20Museum%20of%20Natural%20History finds 780 specimens, all of them presumably linked to related specimens in GBIF. I clicked on a couple dozen and could not find anything in GBIF.

I don't even see that OID or that "base url" listed in the code table? I changed the AMNH: American Museum of Natural History base url to refer to a GBIF search a while back and it works perfectly. See http://arctos.database.museum/guid/MSB:Mamm:235237

I did just change the OID description, because if you don't use the appropriate catalog number, it will fail. I've also made a note to fix the AMNH numbers that I can.

**Comment by dustymc** [comment]
>report

Yea, I think that's about as good as it can get.

>find all of the parasites and their related host 

Do you want that, or "find random things that share some identifier"? The random ID thing is trivial, but sorta random. Including relationships in search probably isn't trivial (and needs a dedicated issue), but should be powerful.

>AMNH

At least one out of 780 doesn't seem that perfect to me....

**Comment by Jegelewicz** [comment]
>     AMNH
> 
> At least one out of 780 doesn't seem that perfect to me....

Agree - so I created a new OID "AMNH: GBIF" with instructions for what it does, moved the base url there and fixed the three records I had using the base url to use the new OID so it won't futz with any of the other AMNH things. Good enough?

**Comment by Jegelewicz** [comment]
>     find all of the parasites and their related host
> 
> Do you want that, or "find random things that share some identifier"? The random ID thing is trivial, but sorta random. Including relationships in search probably isn't trivial (and needs a dedicated issue), but should be powerful.

Yes, I want that as well as to be able to find a parent and all its offspring, or all the related siblings, or every specimen that has the "same individual as" relationship to the record I am looking at (we have wolves with a dozen different collecting events due to catch and release).

**Comment by dustymc** [comment]
>AMNH

Better - it's not making hundreds of "this looks like Arctos is broken links" - but it's still not checkable.

Current link:

curl -I https://www.gbif.org/occurrence/search?catalog_number=M-264072
HTTP/2 200 

Broken link of that format:

 curl -I https://www.gbif.org/occurrence/search?catalog_number=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
HTTP/2 200 

Direct link to one of the Occurrences

curl -I https://www.gbif.org/occurrence/859506757
HTTP/2 200 


Broken link to an Occurrence

curl -I https://www.gbif.org/occurrence/859506757XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx
HTTP/2 404 


Note that the last thing returns a 404, which I could use for a 'your stuff is broken' report. Everything else is happy, even when there's nothing useful there.

"GBIF occurrence ID" is set up to do that now, and can do it for any collection without adding thousands of "Something else in GBIF" IDs.

>parent and all its offspring

https://github.com/ArctosDB/arctos/issues/2280

**Comment by campmlc** [comment]
Agree with Teresa on the need for being able to find all related items in a single search. What she has done with identifiers has been extremely useful in making all the parasites of a host discoverable. Otherwise we are stuck with trying to track through reciprocal linkages, which is not functional or viable.

**Comment by dustymc** [comment]
@campmlc that's #2280; this implementation of the functionality is useful in a very limited capacity, and breaks things everywhere else.

I don't think I understand anything in your last sentence. Elaborate please?

**Comment by jhpoelen** [comment]
Perhaps GloBI can help with features like https://github.com/globalbioticinteractions/globalbioticinteractions/issues/440 . Since GloBI indexes across many platforms (including Arctos), references to Arctos records in other platforms can be found and linked.

**Comment by dustymc** [comment]
@jhpoelen I don't think Arctos is missing any capability here, it's just that the ability to build allegedly-resolvable identifiers is being mis-used (at least from my viewpoint).

Arctos is pretty good at discovering links from GenBank (although sometimes not so good with doing something with the results - https://github.com/ArctosDB/arctos/issues/2413), but less so from other resources. I would LOVE to have a periodic report of 'this links to Arctos, Arctos doesn't links back' types of things if those data happen to fall out of something.

**Comment by dustymc** [comment]
The ambiguous links have also apparently melted fetchRelatedInfo, which caches data for cross-collection search and display.

**Comment by jhpoelen** [comment]
@dustymc not quite sure I understand. Could you please elaborate?

**Comment by dustymc** [comment]
@jhpoelen links to datasets (eg, a from non-unique numbers that get used for a bunch of random things) being mixed in with non-random identifiers is breaking some internal functionality.

**Comment by Jegelewicz** [comment]
@dustymc is it the NKs causing the problem?

**Comment by dustymc** [comment]
I think it's a combination of all otherIDs whose baseURL starts with http://arctos.database.museum/SpecimenResults.cfm?

**Comment by Jegelewicz** [comment]
Welp, I say remove them and see who yells about it.

**Comment by dustymc** [comment]
OK.

```
UAM@ARCTOS> select OTHER_ID_TYPE from CTCOLL_OTHER_ID_TYPE where BASE_URL like '%/arctos.database.museum/SpecimenResults.cfm%';

OTHER_ID_TYPE
------------------------------------------------------------------------------------------------------------------------
Locality ID
IF: Idaho Frozen Tissue Collection
vessel identifier
toe clip number
AF
Mexican wolf studbook number
NK
NEON sample ID
trap number
ALMNH PaleoBotany Collection
ALMNH PaleoVertebrate Collection
ALMNH: Museum Staff Trip
ear tag
MSB Fish Lot ID
GAN
Albuquerque Biopark Zoo Local ID
trapline ID
MSB Para Lot ID
New Mexico Hantavirus Survey Ear Tag Number
ALMNH: Museum Expedition


UAM@ARCTOS> update CTCOLL_OTHER_ID_TYPE set BASE_URL=null where BASE_URL like '%/arctos.database.museum/SpecimenResults.cfm%';

```

**Comment by dustymc** [comment]
Reopening - still need to develop tests to attempt detection of less-systematic failures.
