### ISSUE TITLE
search relationships

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#2280]
ref: https://github.com/ArctosDB/arctos/issues/2278#issuecomment-536134809

We need a way to search related specimens, or include them in results, or something. It's not clear to me what the scope of this is, how it could work, how related records could be grouped, etc.

Simplest use case, a search for "same individual as UTEP:Inv:7092" should return http://arctos.database.museum/SpecimenResults.cfm?guid=UTEP:Inv:7092,UTEP:Inv:7094

Is a single "root" specimen and (optionally) a relationship to it sufficient to get this started?

Help....

**Comment by Jegelewicz** [comment]
"Show me all specimens related to UTEP:Inv:7092"

or

"Show me all specimens related by 'same individual as ' to UTEP:Inv:7092"

Where UTEP:Inv:7092 is the specimen record I am currently viewing.

**Comment by dustymc** [comment]
Simple use case is implemented.

See http://arctos.database.museum/guid/MVZ:Herp:240587

<img width="657" alt="Screen Shot 2019-10-01 at 9 42 51 AM" src="https://user-images.githubusercontent.com/5720791/65982292-dcc4ed80-e42f-11e9-9e0e-a5189f27be24.png">

**Comment by campmlc** [comment]
This is great!

**Comment by Jegelewicz** [comment]
@campmlc enough to convince you all to catalog those wolves separately and use the "same individual as" relationship instead of the multiple event/ event link duct tape?

**Comment by campmlc** [comment]
Works for me.
