### ISSUE TITLE
Convert roman numeral months

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2283]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
Insect collections traditionally use dates in the following formats:

07 VIII 99
07.VIII.99
07-VIII-99

When using the single record data entry form, these are not auto converted to 1999-08-07 by using the --> conversion tool.

![image](https://user-images.githubusercontent.com/5725767/66043985-cc6b4c00-e4dd-11e9-834f-bd2bb8189b80.png)

**Describe the solution you'd like**
Would it be possible for Arctos to understand this date format and make the appropriate conversion?

![image](https://user-images.githubusercontent.com/5725767/66044115-15230500-e4de-11e9-880d-75dc5cfd4225.png)

**Describe alternatives you've considered**
These dates can be manually typed, but a tool that would auto enter them would save lots of time!

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by tucotuco** [comment]
This one is a great idea, and kudos to entomologists for a concisecand
unambiguous date format!

**Comment by dustymc** [comment]
>unambiguous

Is it?

07 VIII 06

**Comment by tucotuco** [comment]
Not that one, but the four digit one, yes.

**Comment by Jegelewicz** [comment]
> 
> 
>     unambiguous
> 
> Is it?
> 
> 07 VIII 06
> 

It may appear ambiguous, unless you know the country of origin of the collector :-)

In any case, being US-centric at this point, making the conversion assume an order of DD MM YY, would be nice. Do you convert 07/08/06 to 2006-08-07? So let's just be consistent in our assumptions?

**Comment by dustymc** [comment]
>Do you convert 07/08/06 to 2006-08-07

Not very confidently...

There's a data services date converter-thingee - I'm pretty comfortable with something like this there, where it's obviously a conversion attempt that requires some human review. 

Anything closer to magic makes me more twitchy, but maybe that's just a documentation/notification/UI issue. In any case this doesn't look very technically challenging, I guess I'm up for whatever.

**Comment by Jegelewicz** [comment]
> There's a data services date converter-thingee

Is that what I screen shot-ed above? If so, then that's all I'm asking for.

**Comment by dustymc** [comment]
No, that uses CF's built-in date functionality.

**Comment by Jegelewicz** [comment]
I figured as much, just wishing for something a little more to help speed up data entry.

**Comment by Jegelewicz** [comment]
closing for lack of interest
