### ISSUE TITLE
Convert Seasonal Dates

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2284]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
Collection dates are often listed as "Fall 99", "Summer 99", etc. These dates need to be converted manually when entering records via single record data entry as the --> conversion tool does not understand them.

![image](https://user-images.githubusercontent.com/5725767/66044415-b9a54700-e4de-11e9-8411-6de10ca27930.png)

**Describe the solution you'd like**
Could we have Arctos understand and convert these "seasonal" dates? So that "Fall 99" would convert to Begin=1999-09-22 and End=1999-12-21 (although these dates can be different each year, I think we could agree on an appropriate range for each "season"?)

![image](https://user-images.githubusercontent.com/5725767/66044589-1f91ce80-e4df-11e9-8006-1281badbdac0.png)

**Describe alternatives you've considered**
Dates can be entered manually, but it slows data entry significantly.

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by tucotuco** [comment]
Are you sure that's a good idea? Fall isn't the same everywhere.

**Comment by dustymc** [comment]
See also https://github.com/ArctosDB/arctos/issues/2283

I'm not sure it's just a hemisphere-thing either. ("Fall" starts with caribou season - August 1st!)

I can probably make suggestions, but users WILL blindly accept them, and they WILL occasionally (at best) be wrong, at which point we'll be very confidently asserting garbage. If this was just a conversion problem we (and ISO/the world) wouldn't need date Standards. I don't think that's the case - I think this is an interpretation problem, and one which requires something smarter than the processors on which Arctos lives for useful success rates.

https://xkcd.com/1179/

**Comment by Jegelewicz** [comment]
OK that all makes sense, but it is sure a pain.

> requires something smarter than the processors on which Arctos lives for useful success rates.

I hope you aren't talking about humans....
