### ISSUE TITLE
Can we get GUID as a column for the bulkload identifiers template

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#2292]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

Other bulkloader templates have a column for GUID but this one

http://arctos.database.museum/tools/BulkloadOtherId.cfm

requires we break GUIDs up into 'GUID_Prefix', 'Existing_other_ID_type', and "existing_other_ID_number"

It would be much easier to just be able to paste a list of GUIDs directly into the bulkloader template, like we can do with many of the others.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Priority**
Please assign a priority-label. low

**Comment by sharpphyl** [comment]
Thanks for asking.  I referenced at the very end of #2104.  It's just extra work and opportunity for error to break up the GUIDs on one bulkload form and combine them on the other one.  Having identical fields/headings would be helpful.

**Comment by sharpphyl** [comment]
@dustymc  Has this fallen off the radar?  It doesn't look like there was a major issue with making the change.  I'm working through changes to a few thousand catalog records to update the other_id type.  

First I add the revised ID and I have to separate our guid_prefix (DMNS:Inv:) from the catalog number

<img width="1573" alt="Screen Shot 2020-08-14 at 10 57 16 AM" src="https://user-images.githubusercontent.com/15368365/90274143-4b7b2180-de1d-11ea-97c1-93b6f0acc1a3.png">

<img width="711" alt="Screen Shot 2020-08-14 at 11 03 20 AM" src="https://user-images.githubusercontent.com/15368365/90274450-d2c89500-de1d-11ea-9135-144659c1539f.png">

Then I delete the old ID I wanted to replace and I have to recombine the guid_prefix with the catalog number

<img width="980" alt="Screen Shot 2020-08-14 at 10 56 55 AM" src="https://user-images.githubusercontent.com/15368365/90274280-867d5500-de1d-11ea-959a-766f638bf90b.png">

<img width="452" alt="Screen Shot 2020-08-14 at 11 03 11 AM" src="https://user-images.githubusercontent.com/15368365/90274463-da883980-de1d-11ea-90fa-b7ef4d5c3889.png">

I know we've had extensive discussions about the three-part numbers, etc. but is there a reason why the headings to add and to delete other identifiers don't use the same headings as Derek requested? I don't care which way, but I'd vote with Derek for GUID.   

BTW from a (non-database professional) UI perspective, it would be great if the instructions were more similar in structure such as the order of the columns.  That's probably a whole other can of worms.

**Comment by dustymc** [comment]
>fallen off the radar

No, if there's a milestone it's on the radar, but it hasn't floated to the top yet either. Please feel free to add it to the AWG Issues agenda (or do whatever we do to prioritize....).

>don't care which way

It's an addition, not a replacement. I need the non-GUID for various reasons, but the GUID is more reliable and easier and etc. when it's available.

>instructions were more similar

https://github.com/ArctosDB/arctos/issues/2974 - working on it, all needs prioritized.

**Comment by sharpphyl** [comment]
Ok, but I don't deal with AWG issues so I'll leave that to @DerekSikes to determine if the priority warrants it.

**Comment by dustymc** [comment]
Blocked by https://github.com/ArctosDB/arctos/issues/2974#issuecomment-693522569

1. Develop the template
2. Confirm it's satisfactory
3. Proceed with this
