### ISSUE TITLE
Bulkload terms and relationships for Geology

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2295]
@dustymc can you magic in these terms and relationships to the Geology code table please? Trying to save some clicks on my part.

Thanks!

Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Table**
http://arctos.database.museum/info/ctDocumentation.cfm?table=CTGEOLOGY_ATTRIBUTE

**Value**
[Geology Terms Bulkload.zip](https://github.com/ArctosDB/arctos/files/3704593/Geology.Terms.Bulkload.zip)

[Geology Relationships Bulkload.zip](https://github.com/ArctosDB/arctos/files/3704594/Geology.Relationships.Bulkload.zip)

**Definition**
Definitions are provided in the CSV files for new terms to be added to the code table.

**Collection type**
N/A

**Attribute data type**
N/A

**Attribute value**
N/A

**Attribute units**
N/A

**Part tissue flag**
N/A

**Other ID BaseURL**
N/A

**Context**
New values needed by NMMNH ES collection

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
Not with this - there's a unique index.

UAM@ARCTOS> select term from dlm.my_temp_cf where term in (select ATTRIBUTE_VALUE from geology_attribute_hierarchy);

TERM
------------------------------------------------------------------------------------------------------------------------
Rancholabrean

I did this:

delete from dlm.my_temp_cf where term='Rancholabrean';

If those are different THINGs we'll need to back way up. If they're not, what's going on??

Your fault...


2019-02-04 17:51:42.0 | Stage/Age | Rancholabrean | https://en.wikipedia.org/wiki/Rancholabrean |   | 1 |   |   |   |   |   | JEGELEWICZ
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
2019-02-04 17:51:52.0 | Stage/Age | Rancholabrean | https://en.wikipedia.org/wiki/Rancholabrean | 1684456 | 1 | Stage/Age | Rancholabrean | https://en.wikipedia.org/wiki/Rancholabrean |   | 1 | JEGELEWICZ

I couldn't decipher the attached relationships - the rest should be done.

[temp_fail.csv.zip](https://github.com/ArctosDB/arctos/files/3704706/temp_fail.csv.zip)

**Comment by Jegelewicz** [comment]
DOH, I though I had removed those dupes! Can you delete that one and then load the rest?

**Comment by Jegelewicz** [comment]
OK,
