### ISSUE TITLE
Can't view specimen record

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2297]
I entered this record today (several hours ago) and Arctos knows it is there, but I can't view it. What gives?
![image](https://user-images.githubusercontent.com/5725767/66444822-f5ba3980-ea01-11e9-910c-5639f0f4d64f.png)

**Comment by dustymc** [comment]
<img width="383" alt="Screen Shot 2019-10-08 at 6 35 20 PM" src="https://user-images.githubusercontent.com/5720791/66445079-68271b80-e9fa-11e9-8476-339950df50aa.png">

I updated a couple million records, it's been chewing on them for a while. Should catch up tomorrow-ish.

**Comment by Jegelewicz** [comment]
Dang-it, you work too much....

**Comment by Jegelewicz** [comment]
Any chance I will see my record today? Just trying to decide where to put my time...

**Comment by dustymc** [comment]
I think I bumped you to the front of the line, but I don't have access to that collection so ?????????

**Comment by Jegelewicz** [comment]
YOU don't have access? How is that even possible!?

**Comment by dustymc** [comment]
I'm like a vampire (except for the garlic thing) - I have to be invited in....
