### ISSUE TITLE
Make new friends and keep the old as part of the Arctos New Collections Committee!

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2299]
The Arctos Working Group decided in our meeting today that we need to form a New Collections Committee. This committee will be responsible for reviewing Arctos join requests, managing incoming collections from join request to portal creation, and assisting new collections with learning Arctos and data migration. Procedures for all of these responsibilities are in place, we just need people to manage them. Participation in this team can be really rewarding - especially when an incoming collection teaches you something about Arctos...

I have created the [team in GitHub](https://github.com/orgs/ArctosDB/teams/arctos-new-collections-committee), but now we need some committee members. If you are interested, please comment as such in this issue and I will add you to the team. Once we have a few members, I'll schedule a meeting for us to talk about how the team should function.

**Comment by acdoll** [comment]
I'll make time for this one.

**Comment by ccicero** [comment]
I'm interested.

**Comment by campmlc** [comment]
I'm interested but time limited, so it would be great to have new members
willing to learn this process!

**Comment by ewommack** [comment]
If you don't need a ton of experience, I'm willing to learn and help.

**Comment by ebraker** [comment]
i'm interested

**Comment by anna-chinn** [comment]
I'm interested too.
