### ISSUE TITLE
On defaults in data entry/search

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2304]
There has been discussion about this in https://github.com/ArctosDB/arctos/issues/2170#issuecomment-512000981 and #1892 

![image](https://user-images.githubusercontent.com/5725767/66762041-6b8b2e80-ee62-11e9-9c42-66ad4aa6a837.png)

![image](https://user-images.githubusercontent.com/5725767/66762286-f10ede80-ee62-11e9-85cb-25372ad9687d.png)

In this case, perhaps "Just DON"T do it" should be our motto?

**Comment by dustymc** [comment]
This isn't done purposefully, it's just the default state of some tools. There is an active issue and I can usually just fix these when they're identified - I don't think we need another issue??
