### ISSUE TITLE
[CONTACT]

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/arctos#2308]
I am trying to create a "loan" and I keep getting told "...something BAD happened."  What????
![image](https://user-images.githubusercontent.com/43214224/66860067-0878c500-ef52-11e9-8758-b21f8d8add5e.png)

**Comment by Jegelewicz** [comment]
Try taking the "ALMNH:ES " out of the loan number?

**Comment by dustymc** [comment]
I'm not seeing anything in the logs - I need to see the bad to know what it might be.

The loan number is just a string and should be happy with whatever you want to stuff in there.

**Comment by mbprondzinski** [comment]
It wasn’t there the first time I did it, so I added it.  I can’t figure out what the problem is!

**Comment by mbprondzinski** [comment]
Okay.

**Comment by Jegelewicz** [comment]
The loan is there: http://arctos.database.museum/Loan.cfm?transaction_id=21123731&Action=editLoan

closing
