### ISSUE TITLE
UMNH Bulkload Attribute file error

### ISSUE THREAD

**Issue by srobson4** [ArctosDB/arctos#2311]
@dustymc   Can you help us decipher this error message when bulkloading an attributes file?

An error occurred while processing this page!

Query Of Queries syntax error.
Encountered "OTHER_ID_NUMBER. Incorrect Select Statement, Expecting a 'FROM', but encountered 'OTHER_ID_NUMBER' instead, A select statement should have a 'FROM' construct.

Query Of Queries syntax error.
Encountered "OTHER_ID_NUMBER. Incorrect Select Statement, Expecting a 'FROM', but encountered 'OTHER_ID_NUMBER' instead, A select statement should have a 'FROM' construct.
Error Executing Database Query.

Sent csv file by email.  Thank you!

**Comment by dustymc** [comment]
I'm not sure that that is, but it's not CSV! (TSV maybe?)

<img width="1085" alt="Screen Shot 2019-10-16 at 1 06 40 PM" src="https://user-images.githubusercontent.com/5720791/66954758-dcbf1300-f015-11e9-8af7-3e59f855ceed.png">

You can just zip csv (or "csv"!) to attach here.

**Comment by srobson4** [comment]
[UMNH attribute upload.zip](https://github.com/ArctosDB/arctos/files/3736337/UMNH.attribute.upload.zip)

**Comment by dustymc** [comment]
One problem is the lack of units.

<img width="626" alt="Screen Shot 2019-10-18 at 8 54 26 AM" src="https://user-images.githubusercontent.com/5720791/67109278-0185c880-f185-11e9-9d16-12e31aad2603.png">

See http://arctos.database.museum/info/ctDocumentation.cfm?table=CTATTRIBUTE_CODE_TABLES for attribute datatype control and links to the value/units tables.

So EFN...
<img width="629" alt="Screen Shot 2019-10-18 at 8 56 04 AM" src="https://user-images.githubusercontent.com/5720791/67109352-2bd78600-f185-11e9-8479-3ec754735511.png">

 needs a numeric VALUE and UNITS from http://arctos.database.museum/info/ctDocumentation.cfm?table=CTLENGTH_UNITS

**Comment by srobson4** [comment]
Thank you!
