### ISSUE TITLE
Add users to TACC project allocation for Arctos media

### ISSUE THREAD

**Issue by srobson4** [ArctosDB/arctos#2312]
UMNH has a separate directory under the Arctos Project on the TACC Portal and we have two new user who have registered in the TACC portal that need access.  @ccicero or @dustymc can you approve ckesmay  and  awilkins to access the TACC project allocation for Arctos media?  

Thanks!

**Comment by dustymc** [comment]
I added them to the  Arctos Uploads - Other Collections project - give it a try....

**Comment by srobson4** [comment]
Thank you - both were able to access/upload files.

**Comment by srobson4** [comment]
@dustymc  -- as in Oct 2019 can you add new user mathhc who has registered in the TACC portal and needs access to transfer Arctos media files? Also can you remove ckesmay?  Thanks

**Comment by dustymc** [comment]
done & done
