### ISSUE TITLE
Bird record lost in limbo

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#2315]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
A bird record loaded via data entry yesterday is not findable (UCM 16217).

**To Reproduce**
http://arctos.database.museum/guid/UCM:Bird:16217 gives 404: Not Found Error, however, I was able to add the specimen to a loan yesterday immediately after the record was bulkloaded (which admittedly may be why things are wonky...). Yet, I still cannot view the specimen record and the printed loan invoice only lists the cat_num, part_name, part_condition and is not pulling in taxon_name or locality.

**Screenshots**
Specimen query finds the record, though displays as blank line:
![image](https://user-images.githubusercontent.com/11336485/67023975-e0f43a80-f0c0-11e9-93f2-38158dd111b4.png)

**Desktop (please complete the following information):**
 - Windows
 - Chrome

**Priority**
This specimen is going on loan tomorrow so I need to be able to add/view its information on the loan invoice (plus we need the record to display properly in Arctos)

**Comment by dustymc** [comment]
It's processing. You can check that here.

<img width="361" alt="Screen Shot 2019-10-17 at 8 00 39 AM" src="https://user-images.githubusercontent.com/5720791/67027220-06cc1000-f0be-11e9-9796-0ec65454bf31.png">

things are really slow for some reason right now. I have most jobs shut down, and the critical stuff (just this at the moment) heavily throttled.

I tossed https://arctos.database.museum/guid/UCM:Bird:16217 on top of the pile - it's probably refreshed by now.

**Comment by ebraker** [comment]
Ah, thank you so much! The record has surfaced.
