### ISSUE TITLE
Update Georeference Report

### ISSUE THREAD

**Issue by dperriguey** [ArctosDB/arctos#2316]
@dustymc I couldn't figure out where to put this issue. 

We need the georeference report updated regularly at about every 3 months. I was supposed to make this request in GitHub a while back, but forgot. 

**To Reproduce**
The georeference report does not accurately reflect what we've entered in Arctos unless we ask for it to be updated.

**Expected behavior**
Updated regularly.

**Additional context**
The georeference report is in: Reports/Services > View Statistics > Georeference Statistics

**Comment by dustymc** [comment]
<img width="476" alt="Screen Shot 2019-10-17 at 10 54 45 AM" src="https://user-images.githubusercontent.com/5720791/67034459-94166100-f0cc-11e9-841c-986ca9dc0554.png">

**Comment by dperriguey** [comment]
Where is that documentation?

**Comment by dustymc** [comment]
http://arctos.database.museum/Reports/georef.cfm

**Comment by dperriguey** [comment]
Oh duh, thanks!
