### ISSUE TITLE
Add Delete option for Bulkloader Extras page

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2317]
The specimen bulkload extras page has option to check all, uncheck all, and claim and mark all checked records to autoload. 
Please add an option to delete checked records.
This is necessary because it is possible to add duplicate extras through the data entry page, and it is not possible to view or edit extras from data entry because only the existence of a uuid is visible from that interface.

**Comment by campmlc** [comment]
![Screenshot 2019-10-17 15 33 00](https://user-images.githubusercontent.com/14808196/67049332-38130300-f0f3-11e9-9408-f53b495ad04e.png)

**Comment by Jegelewicz** [comment]
In the mean time, can you delete the dupes from the part bulkload tool before you load them?

**Comment by dustymc** [comment]
Closing - this is part of the component loader ecosystem
