### ISSUE TITLE
I got a "unique constraint"error feedback trying to add new collections types!

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/arctos#2329]
** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **

** Outages should be reported to the contacts listed at https://arctosdb.org/arctos-down/ **

** Arctos Documentation is http://handbook.arctosdb.org/ **

** Learn more about Arctos at https://arctosdb.org/ **

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **

**Comment by Jegelewicz** [comment]
UGH - OK I'll just request them for you.

**Comment by Jegelewicz** [comment]
Let me make sure I have them all

Herp
Mamm
Bird

Is that all of them?

**Comment by mbprondzinski** [comment]
I think so.  These are the ones I use, but Fishes may come up once we get the Paleo Curator.  I don’t want to create that in anticipation, so just do those three.  Thank you.
