### ISSUE TITLE
New Part Attributes for Paleo

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2330]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Table**
http://arctos.database.museum/info/ctDocumentation.cfm?table=CTSPECPART_ATTRIBUTE_TYPE

**Proposed new values**

anatomical direction reference
tooth order
tooth set
tooth abbreviation

**Definition**

Attribute | Definition
-- | --
anatomical direction reference | 
tooth order | Used for mammals, the numerical order of the tooth from anterior to posterior counting from the first tooth of the same type (ex. molar 1, molar   2, molar 3).
tooth set | for diphyodont mammals - deciduous (milk/baby teeth) or permanent
tooth abbreviation | abbreviation used to describe mammal teeth, typically in paleontology

**Collection type**
N/A

**Attribute data type**

Attribute | Allowed values
-- | --
anatomical direction reference | categorical
tooth order | categorical
tooth set | categorical
tooth abbreviation | free-text

**Attribute value**

Attribute | Controlled Values
-- | --
anatomical direction reference | left, right, upper, lower, dorsal, ventral, lateral, medial, caudal, cranial, proximal, distal, superficial, deep
tooth order | 1, 2, 3, 4
tooth set | deciduous, permanent

**Attribute units**
N/A

**Part tissue flag**
N/A

**Other ID BaseURL**
N/A

**Context**

Paleo specimens are often a single bone or tooth with information such as to which side of the body the bone belongs or to which jaw the tooth belongs. Teeth are numbered according to their placement in the jaw and may also be deciduous or permanent. We would like to add these part attributes and associated controlled vocabularies to allow for more refined searching of paleo specimens.

**Priority**
Please assign a priority-label.

Attribute value definitions (need to research a few):

- ventral Describes the front or direction toward the front of the body. The toes are anterior to the foot.
- dorsal Describes the back or direction toward the back of the body. The popliteus is posterior to the patella.
- cranial describes a position above or higher than another part of the body proper. The orbits are superior to the oris.
- caudal describes a position below or lower than another part of the body proper; near or toward the tail (in humans, the coccyx, or lowest part of the spinal column). The pelvis is inferior to the abdomen.
- lateral describes the side or direction toward the side of the body. The thumb (pollex) is lateral to the digits.
- medial describes the middle or direction toward the middle of the body. The hallux is the medial toe.
-proximal describes a position in a limb that is nearer to the point of attachment or the trunk of the body. The brachium is proximal to the antebrachium.
- distal describes a position in a limb that is farther from the point of attachment or the trunk of the body. The crus is distal to the femur.
- superficial describes a position closer to the surface of the body. The skin is superficial to the bones.
- deep describes a position farther from the surface of the body. The brain is deep to the skull.
- upper
- lower
- left
- right
- deciduous
- permanent

**Comment by Jegelewicz** [comment]
@mvzhuang do you have any thoughts on this? I think I may email to Art for his opinion too.

The one that has been bothering me is left/right. I think we should call this "anatomical directional reference" which would also allow use of the following terms in the controlled vocabulary for the value: dorsal, ventral, frontal, proximal, and distal (see [Wikipedia]https://en.wikipedia.org/wiki/Anatomical_terms_of_location#Main_terms))

**Comment by Jegelewicz** [comment]
> The one that has been bothering me is left/right. I think we should call this "anatomical directional reference" which would also allow use of the following terms in the controlled vocabulary for the value: dorsal, ventral, frontal, proximal, and distal (see Wikipedia)

@Nicole-Ridgwell-NMMNHS as I work on parts for locality 1, there are a lot of "dorsal", "distal", etc. and I'd like to decide if we want these in attributes or just thrown in part remarks. What do you think?

**Comment by Jegelewicz** [comment]
Also wonder if "upper" and "lower" should also be part of "anatomical direction reference"?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> I'd like to decide if we want these in attributes or just thrown in part remarks.

I think putting that in part remarks and broadening left/right to anatomical direction reference is a great idea.

**Comment by campmlc** [comment]
Couldn't we have left, right, dorsal, distal etc all be values in a single
attribute of anatomical directional reference? That is what you are
proposing, correct? So why the need for putting anything in part remarks?
Why not have a code table of values, and be allowed to use the attribute
more than once for, say, "distal" and "right" e.g. femur?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Sorry, mistyped. meant to say putting in attributes is a great idea.

**Comment by campmlc** [comment]
OK, that sounds like a good idea then!

**Comment by ebraker** [comment]
It's worth mentioning that PART_ATTRIBUTES cannot be added from Data Entry (only via bulkloading), so it would be good to add this capability

**Comment by dustymc** [comment]
>PART_ATTRIBUTES cannot be added from Data Entry (only via bulkloading)

Yes but no...

You can add them from data entry ("add more"), but it's currently a separate process to load them. (It's just a click or two and Arctos will send email, but it's still separate.) https://github.com/ArctosDB/arctos/issues/2178 might change that.

**Comment by Jegelewicz** [comment]
Instead of tooth order, recommend "numeric order" for use in multiple areas where things are given an order in a series.

**Comment by Jegelewicz** [comment]
@dustymc AWG has agreed to the addition of these part attributes. I need to set up the controlled vocab for anatomical direction reference, which means I need a new code table. Suggest CTANATOMICAL_DIRECTION with the following terms/definitions to start.

[Anatomical direction.zip](https://github.com/ArctosDB/arctos/files/3855785/Anatomical.direction.zip)

Also, for "numeric order" can we limit this to integers?

**Comment by dustymc** [comment]
Can it wait for postgres? I don't think there's a lot of risk of directly breaking the DB, other than time catching up to us, but it requires a fair bit of code and almost none of it's directly cross-platform. Can you use this as free-text for the (very, I hope) immediate future and clean up as necessary in PG?

>numeric order

Add to http://arctos.database.museum/info/ctDocumentation.cfm?table=CTCOUNT_UNITS - like http://arctos.database.museum/info/ctDocumentation.cfm?table=CTATTRIBUTE_CODE_TABLES&field=numeric%20abundance

**Comment by Jegelewicz** [comment]
Let's do this https://github.com/ArctosDB/arctos/issues/2330#issuecomment-554761641

**Comment by dustymc** [comment]
@Jegelewicz 

new table: CTANATOMICAL_DIRECTION, column: ANATOMICAL_DIRECTION (and description)

tooth set - seems like a boolean (eg is [not] adult) - can that be phrased to use https://arctos.database.museum/info/ctDocumentation.cfm?table=ctyes_no?

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcount_units should work for the rest

What'd I miss?

**Comment by Jegelewicz** [comment]
See https://github.com/ArctosDB/arctos/issues/2354

> tooth set - seems like a boolean (eg is [not] adult) - can that be phrased to use https://arctos.database.museum/info/ctDocumentation.cfm?table=ctyes_no?

Maybe? is there anything other than deciduous and adult? @Nicole-Ridgwell-NMMNHS

**Comment by dustymc** [comment]
Edited https://github.com/ArctosDB/arctos/issues/2330#issuecomment-660181579

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> Maybe? is there anything other than deciduous and adult?

Not for mammals, which is what we are really talking about here since I don't think there are any other groups where you can actually keep track of tooth set.

We could phrase it "deciduous tooth set" yes/no.

**Comment by Jegelewicz** [comment]
Done.

**Comment by Jegelewicz** [comment]
@Jegelewicz need to create code tables for:

anatomical direction reference
tooth type

**Comment by Jegelewicz** [comment]
@dustymc we still need to do [this](https://github.com/ArctosDB/arctos/issues/2330#issuecomment-660181579).

**Comment by dustymc** [comment]
@Jegelewicz missing attachment

**Comment by Jegelewicz** [comment]
[Anatomical direction reference cleanup.zip](https://github.com/ArctosDB/arctos/files/5153224/Anatomical.direction.reference.cleanup.zip)

**Comment by Jegelewicz** [comment]
@dustymc in the file the last two headers are attribute_value_old and attribute_value_new These changes need to be made before I associate the code table with the attribute so that stuff already in Arctos matches the code table. Clear as mud?

**Comment by Jegelewicz** [comment]
PS - many of them don't look functionally different because the "old" values have a trailing space...

**Comment by dustymc** [comment]
>many

I can't see any.  I did this:

```
arctosprod@arctos>> update specimen_part_attribute set attribute_value=trim(attribute_value) where attribute_value!=trim(attribute_value);
UPDATE 44162
```

Anything left?

**Comment by Jegelewicz** [comment]
Looks like that did it. I have associated the attribute with the code table.

Thanks!
