### ISSUE TITLE
Firefox 70.0

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2332]
Firefox pushed a new version last night. Immediately after that, certain things in Arctos get me the Windows Blue Screen of Death.  So far AJAX grid view in bulkloader and adding terms to search in search results have done this to me. Don't know what FF did, but thought I would pass this along...

**Comment by dustymc** [comment]
71.0b3 works for me, but I haven't tried on Windows - that sounds a lot like an extension.
