### ISSUE TITLE
error feedback

### ISSUE THREAD

**Issue by jldunnum** [ArctosDB/arctos#2333]
Getting timeout error when just searching for 20 NK numbers in MSB mammals.

An error occurred while processing this page![Macromedia][Oracle JDBC Driver]Execution timeout expired.[Macromedia][Oracle JDBC Driver]Execution timeout expired.Error Executing Database Query.
--

**Comment by Jegelewicz** [comment]
@jldunnum do you have a bunch of attributes checked (or maybe all of them)? That has caused me trouble.

![image](https://user-images.githubusercontent.com/5725767/67506778-eb777c80-f64a-11e9-9ad6-3422a382d747.png)

**Comment by jldunnum** [comment]
Just measurements and sex, not a crazy number by any means.

______________________________________________________________

Jonathan L. Dunnum Ph.D.
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by Jegelewicz** [comment]
That's all I've got. I just searched all of ALMNH:ES and had not trouble. Want me to try them for you? send the list and I will!

**Comment by jldunnum** [comment]
Its sped up recently and seems to be working better at the moment.  Go figure

______________________________________________________________

Jonathan L. Dunnum Ph.D.
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by Jegelewicz** [comment]
We (and bots) can bog it down...Can I close this?

**Comment by jldunnum** [comment]
Yeah please

______________________________________________________________

Jonathan L. Dunnum Ph.D.
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________
