### ISSUE TITLE
Error loading Specimen Events

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2334]
I loaded some specimen events using the [Specimen Event Bulkloader](http://arctos.database.museum/tools/BulkloadSpecimenEvent.cfm). The records are still there. They all validate but when I select to load I get this:

![image](https://user-images.githubusercontent.com/5725767/67527806-11b21200-f675-11e9-952d-3a288ee136a1.png)

I even made sure there wasn't a blank line at the end of my csv. Any help is appreciated!

**Comment by dustymc** [comment]
I need data which I can load. One record should be plenty.

**Comment by Jegelewicz** [comment]
[33 Events.zip](https://github.com/ArctosDB/arctos/files/3779362/33.Events.zip)

**Comment by dustymc** [comment]
thanks - those are loaded and the loader should be happy

**Comment by Jegelewicz** [comment]
Thanks!
