### ISSUE TITLE
Need Part for Mineral collection

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2335]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Table**
http://arctos.database.museum/info/ctDocumentation.cfm?table=CTSPECIMEN_PART_NAME

**Value**
geosample

**Definition**
sample of material from the Earth's crust

**Collection type**
ES

**Attribute data type**
N/A

**Attribute value**
N/A

**Attribute units**
N/A

**Part tissue flag**
no

**Other ID BaseURL**
N/A

**Context**
non-biological material specific to geology collections

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
There are thousands of similar things cataloged, albeit mostly for different reasons. Would be good to find some unity; I don't think users will care WHY you've cataloged a rock, they'll just want to find rocks.

I would see collections "preferring" a single taxonomy source as a compelling reason to catalog this in a geology collection, where I could access geological taxonomy, as well.

http://arctos.database.museum/guid/UAM:ES:14480
http://arctos.database.museum/guid/UAM:Arc:0206-2090
http://arctos.database.museum/guid/UAM:Arc:0505-5098

**Comment by Jegelewicz** [comment]
The only part available now that seems close is "sediment" and that is not quite right. There is a difference between rocks and minerals:

> A mineral is a naturally occurring, inorganic solid with a definite chemical composition and a crystalline structure formed by geological processes. A rock is an aggregate of one or more minerals whereas a rock may also include organic remains and mineraloids. Some rocks are predominantly composed of just one mineral.

Because these are the commonly used terms, I suggest that instead of geosample, we add:

rock: an aggregate of one or more minerals, or a body of undifferentiated mineral matter. Common rocks include granite, basalt, limestone, and sandstone.

mineral: a naturally occurring inorganic element or compound having an orderly internal structure and characteristic chemical composition, crystal form, and physical properties. Common minerals include quartz, feldspar, mica, amphibole, olivine, and calcite.

**Comment by dustymc** [comment]
There are two potential places for these data - parts and identifications (which use taxonomy, which could contain minerals).

These things seem "part-like" to me, despite my inability to articulate exactly why.

* worked flake
* "rock" (eg, hunk of the stuff in no particular form)
* cut gem
* projectile point
* sediment (or not -maybe this is just 'rock')

These things seem "name-like" to me:

* granite
* limestone
* quartz
* olivine

That would allow users to find...

* granite, in any form (hunks-of, worked into points, etc.)
* points, regardless of what they're made from
* granite points

Actually that may take me back to what you suggested - "mineral sample" would signify "this is pure quartz, it's not mixed up in granite" or "'rock'" ==>"this is granite, it contains quartz" or something. (Or maybe that can be pulled from the taxonomy?????????)

@sjshirar might have something to add.

This also seems somewhat likely to loop us back around to taxon concepts (or something like them) as a way of pointing to various specific classifications - a "cultural object" (which might use Getty's taxonomy) might be made of 'rock' (which could use a mineral taxonomy) and contain fossils (which might need both plant and animal taxonomies).

**Comment by mbprondzinski** [comment]
Isn't this getting kind of nit-picky?  I just want to know where the "specimen" in this record is located!  I don't care if it's a rock or a mineral...I may not even know which it is, but I do know it is a geo specimen.  Arctos doesn't have specific "teeth" listed as parts, only "tooth".  But there are certainly many different kinds of teeth.  Perhaps I don't understand the relationship you are trying for, but I would prefer simple as opposed to nit-picky.

**Comment by dustymc** [comment]
If you just need a physical thing, [unknown](http://arctos.database.museum/info/ctDocumentation.cfm?table=CTSPECIMEN_PART_NAME&field=unknown)  might make the most sense. It's certainly appropriate if you don't know what's there.

Finding a real answer would involve knowing what users (including curatorial users) want to query. If they need all of ^^ that stuff, then we need the data structured to support that. If not, maybe there's no reason to complicate this just yet.

**Comment by Jegelewicz** [comment]
Isn't this getting kind of nit-picky?

Yep, but I want people to be able to find stuff and we need to think about other incoming collections.

geosample added, we can always change stuff later.
