### ISSUE TITLE
Can we drop the font size for the PLPath text in specimen record view

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#2337]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

The font is the same size as most of the fonts on the specimen record view page and fitting all the object tracking container path information in that field requires a lot of space & thus scrolling to see it all.

**Describe the solution you'd like**

Use of a smaller font, perhaps 3 point smaller for that text.

**Describe alternatives you've considered**

**Additional context**

**Priority**
Please assign a priority-label. low

**Comment by dustymc** [comment]
done in PG
