### ISSUE TITLE
Mineral Classifications

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/arctos#2338]
[Standardized Mineral Group Hierarchy.pdf](https://github.com/ArctosDB/data-migration/files/3768904/Standardized.Mineral.Group.Hierarchy.pdf)

I'm creating "taxonomic" names of minerals that I am entering individually into our collection...without any hierarchical schema.  Just the name: i.e. Beryl.  However, these get more complicated when they are "Beryl with Sphalerite" or some such moniker.  Does Arctos have a plan for dealing with Geology specimens?   I don't plan on uploading our entire Geology collection at this time, but I would like to be able to enter individual specimens "out-on-loan" or newly acquired.  ( I have four records I've created waiting to be uploaded.)

**Comment by Jegelewicz** [comment]
See also #2501

**Comment by Jegelewicz** [comment]
@Jegelewicz to check with mindat to see if we can use it like WoRMS.

**Comment by Jegelewicz** [comment]
@mbprondzinski will send me her list of "taxon" names

**Comment by Jegelewicz** [comment]
See [Beryl](http://arctos.database.museum/name/Beryl) in Arctos for an idea of what we might be able to do.

It would be awesome to have a mineral taxonomy that allowed you to find everything in Arctos that is in the "Beryl Group" - the family in this classification. But also, that would allow you to find all minerals within a hardness range, or that include a specific element or combination of elements.

**Comment by Jegelewicz** [comment]
@mbprondzinski I added an identification to your [Calcite w/Sphalerite record](http://arctos.database.museum/guid/ALMNH:ES:20148) - see if you like that method better...

**Comment by Jegelewicz** [comment]
Sent email to info@hudsonmineralogy.org

> Greetings,
> I work with a consortium of museum professionals who use and develop a collection management system called Arctos.
> Arctos is a web-based, open source system and all collections using it can be searched on our data portal at https://arctos.database.museum.
> Although the majority of our collections are biological, we do host data for historical, ethnological, archaeological, geological, and art collections. Our geological collections are interested in linking to your data for use as "taxonomy". You can see a very rough version of how this might work in this mineral record.
> I would like to set up a meeting with you and our programmer to discuss the possibility of a link through your API. We may also be interested in adding our specimen records to your occurrence database.
> I hope that you see the potential in such a collaboration!
> Adios,
> Teresa J. Mayfield-Meyer
> It's not dead if it has data!
>

**Comment by dustymc** [comment]
I don't think I see any problem with adding these, but PLEASE very carefully keep them somehow marked (``source_authority: https://www.mindat.org/min-859.html`` is perfect) until https://github.com/ArctosDB/arctos/issues/2499 can be implemented.


@Jegelewicz the easy solution is the usual - get mindat to talk to globalnames. (Let's see how global GN really wants to be!) There's a hugely powerful mechanism that lets Arctos talk to things like this, using it should be our first option for a whole bunch of reasons. If that can't meet some compelling need, then we can talk about things like APIs.

**Comment by Jegelewicz** [comment]
> I don't think I see any problem with adding these, but PLEASE very carefully keep them somehow marked

I also plan to add Kingdom = Mineral to all of them so they can be easily found.

**Comment by mbprondzinski** [comment]
> @mbprondzinski I added an identification to your [Calcite w/Sphalerite record](http://arctos.database.museum/guid/ALMNH:ES:20148) - see if you like that method better...

My only reservation is why was it recorded "with Sphalerite"?  Is it because the amount is minimal compared to the Calcite?  "Calcite and Sphalerite" (is that an A definition?) implies they are equally represented...at least that is how I interpret it...but then, I'm not a geologist!

**Comment by mbprondzinski** [comment]
Here is our Geology Taxonomy!  Have fun with it...
[Geology Taxonomy.xlsx](https://github.com/ArctosDB/arctos/files/4355916/Geology.Taxonomy.xlsx)

**Comment by Jegelewicz** [comment]
Response from mindat:

> Hi,
> 
> I have passed along your request to our programming site managers. I am doubtful we can assist without funding, but they will look over your database and evaluate the request. I tried the “this mineral record” link, but it was not operational.
> 
> Tony Nikischer, Chairman
> Hudson Institute of Mineralogy dba Mindat.org
> An IRS recognized not-for-profit organization

Doesn't seem very promising....

**Comment by dustymc** [comment]
>Calcite and Sphalerite
>is that an A definition

It definitely shouldn't be - that would require denormalized taxonomy.

If there's some compelling reason not to catalog this as two records, http://arctos.database.museum/info/ctDocumentation.cfm?table=CTTAXA_FORMULA&field=A%20and%20B is probably the "correct" formula.

>Geology Taxonomy

That looks more like identification and such.

>Doesn't seem very promising.

No, and I don't see any indication that they have anything resembling an API.

I know little about minerals, but I'm not sure we need an API. The taxonomy of living things is whatever someone convinces everyone else it is, an infinitely complex and ever-changing mess, and keeping up requires interaction. The taxonomy of minerals seems a LOT simpler - it's CaSO4 · 2H2O or it ain't - so I suspect just a clean download would get us a long way, and should be technically simpler for someone like mindat to provide if they're inclined to cooperate.

**Comment by Jegelewicz** [comment]
> My only reservation is why was it recorded "with Sphalerite"? Is it because the amount is minimal compared to the Calcite? "Calcite and Sphalerite" (is that an A definition?) implies they are equally represented...at least that is how I interpret it...but then, I'm not a geologist!

That is a "taxon and taxon" which means that a search under either will find this record. It in no way implies they are "equally represented" it just implies they are both present and the ID remark "Minor Sphalerite on bottom" makes it pretty clear they are not equally represented.

> It definitely shouldn't be - that would require denormalized taxonomy.
> 
> If there's some compelling reason not to catalog this as two records, http://arctos.database.museum/info/ctDocumentation.cfm?table=CTTAXA_FORMULA&field=A%20and%20B is probably the "correct" formula.

What Dusty said - the way you had it made it seem like w/Sphalerite is somehow another "species" of or another way of saying Calcite.

**Comment by mbprondzinski** [comment]
Yeah, I get that.  I'm just wondering why they were recorded the way they were.  Some say "and" some say "with" some say "on" some say "in", etc.  I figure they were labeled as such by a geologist for some idiosyncratic reason (!)

**Comment by dustymc** [comment]
>some idiosyncratic reason

Yup, that's why Arctos has formally separated taxonomy and identification, and why taxa_formula exists. "A and B" isn't a taxon so it can't possibly carry different metadata than "A" and/or "B," and the identification formula means there's one predictable way to spell "these two things." Specimens bearing those data are completely discoverable by taxonomy and mostly discoverable by identification strings as well. Anything with less structure - which as far as I know is everything - just can't answer the same questions.

**Comment by Jegelewicz** [comment]
>  I'm just wondering why they were recorded the way they were. Some say "and" some say "with" some say "on" some say "in", etc. I figure they were labeled as such by a geologist for some idiosyncratic reason (!)

Agree with Dusty - put the idiosyncratic statement in ID Remark.

**Comment by Jegelewicz** [comment]
Closing this. Will start a new issue for creating appropriate terms for mineral classifications.
