### ISSUE TITLE
"Extras" in the Bulkloader can't be edited

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/arctos#2339]
I wanted to edit the location on a couple of the specimen parts extras and can't figure out how to do it.  
![image](https://user-images.githubusercontent.com/43214224/67698112-b5523980-f977-11e9-8f3b-8f238a63e91f.png)

If you try to edit them in the record itself, you have to keep recreating the parts extra!  This becomes very confusing when all you want to do is see what you entered prior to trying to make an edit.

**Comment by Jegelewicz** [comment]
@mbprondzinski I suggest you load the extras as they are, then edit the record after they are in.

**Comment by mbprondzinski** [comment]
I will wait.  However, I still need to wait for the specimen part "geosample" to be created.  I figured out how to do the Calcite w/Sphalerite according to Dusty's explanation so that worked okay (A {text string}.

**Comment by Jegelewicz** [comment]
See #2335

**Comment by dustymc** [comment]
https://github.com/ArctosDB/documentation-wiki/issues/132#issuecomment-540178125

<img width="263" alt="Screen Shot 2019-10-29 at 7 25 24 AM" src="https://user-images.githubusercontent.com/5720791/67777376-e0439880-fa1e-11e9-8efc-3d9a0fa5e739.png">

<img width="113" alt="Screen Shot 2019-10-29 at 7 37 15 AM" src="https://user-images.githubusercontent.com/5720791/67777434-f5b8c280-fa1e-11e9-8cad-ab52ba52d20c.png">

**Comment by campmlc** [comment]
@Prondzinski, Mary Beth <mbprondzinski@ua.edu>  I agree with Teresa that
you should mark those extras to load, first making a note of their ID
numbers so you can find the catalog record. Then go and make your edits
from the individual specimen record page. Geosample has been added,
according to #2235.

**Comment by mbprondzinski** [comment]
Yes, I see that, thank you, Mariel.  I just received some cryptic git hub message from Dusty so I was responding to that.  I had followed his instructions to the letter, so I wanted him to know that. ☺
