### ISSUE TITLE
Agent email error

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#2344]
**Describe the bug**
I was trying to add an email to an agent and got the following error:

![Capture](https://user-images.githubusercontent.com/47402809/67723341-586b7900-f9a1-11e9-853a-bb9234145931.JPG)

It wouldn't let me save it as an email, I don't see anything wrong with the formatting though.

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: chrome

**Comment by dustymc** [comment]
That's a browser-thing; not much I can do from here. It could either be Chrome being Chrome, or something is wrong with the address itself - there are non-printing characters or that's some period-like character that's not actually a period or something. If you want to send a link to the agent and the address as text I can give it a try.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks! I typed instead of copy-paste and it worked.
