### ISSUE TITLE
issue lifecycle

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#2346]
ref: https://github.com/ArctosDB/arctos/issues/2323#issuecomment-547433242

> @campmlc : most users don't know and have not had the time to figure out what is going on.

> @dustymc : You're obviously right, and that needs fixed - we need to find some sort of clear proposal-->discussion-->finalize-->prioritize-->implement pathway.

> @campmlc : announce via the newsletter prior to implementation.

-----------------------

We need a formal issue lifecycle (for more than just bulkloader-things).

I would like to do more with milestones, https://github.com/ArctosDB/arctos/milestones

The current "clean" path is 
1. Needs Discussion
1. Next Task
1. Active Development

 I'd go for 

1. Needs Discussion
1. initial discussion complete, needs announced in the newsletter
1. announced in the newsletter
1. last chance to comment, open for some set amount of time
1. Next Task; comments are closed, this only needs prioritized
1. Active Development

Most issues probably don't need that level of scrutiny, but I'm not sure how we'd make that decision.

Some sort of formal prioritization process would be very useful. At some point we were going to count 👍 reactions as a vote.

I'd also like to reiterate the importance of assigning milestones to Issues; I use them to filter what I see.

**Comment by Jegelewicz** [comment]
I am on board with this and we should make our next AWG non-issue meeting about this and SABI.

I am always hesitant to add a milestone because I feel like I do not have the authority to say what should be "next task".

I think this is a good place to start:

>     Needs Discussion
>     initial discussion complete, needs announced in the newsletter
>     announced in the newsletter
>     last chance to comment, open for some set amount of time
>     Next Task; comments are closed, this only needs prioritized
>     Active Development

but this should apply to things that require @dustymc to complete. Some of our discussions about controlled vocabularies or procedures need a different kind of path.

**Comment by dustymc** [comment]
>do not have the authority to say what should be "next task".

I use that for "I'm pretty sure I know how to do this" - never occurred to me that it might also carry "priority" implications....

I think all issues could have one of three initial milestones:

* Needs Discussion=="here's an idea/proposal/etc., and we might be able to do something about it"
* Wish List=="here's an idea/proposal/etc., we probably can't do anything about it now but it should stay on the radar"
* Announcement=="here's something cool, it can probably be closed after a while"

>controlled vocabularies 

That's probably a DIFFERENT path, but I think those need some formal pathway more than most.  https://github.com/ArctosDB/arctos/issues/2326

>procedures

Example?

**Comment by Jegelewicz** [comment]
> 
>     procedures
> 
> Example?

See #2320 - related to documentation, but also just need help with how Arctos works.

**Comment by dustymc** [comment]
Thanks. I'd probably file that one under 'needs discussion' - those have a way of turning into better code, better documentation, etc. Or maybe we need a "help request" - we can always upgrade it to 'needs discussion' if it goes that way.

**Comment by mkoo** [comment]
We discussed this in today's AWG meeting. We will draft a document for the Arctos DB and Handbook to clear outline steps for users and distinguish the responsibilities with the main one being discussing, deciding and prioritizing tasks FOR Dusty so he can focus on implementation and input on those tasks.

We did decide that we need to get these issues and decisions (especially those impacting day to day activities) more in front of users so we will use the Arctos banners to highlight public blog posts and handbook updates and other changes to Arctos. We can also direct Arctos users to the milestones as Dusty suggested to direct people to the main issues we need attention on. Repetition will not be avoided! 

This will require people to actively participate more, even a little bit will help (whether editing grammar for clarity or just outlining salient points). Starting with this meeting and this issue of lifecycle of decisions/issues.

**Comment by dustymc** [comment]
* need better tagging in github - @Jegelewicz is on it
* Phase One: link to issues (by new label-or-whatever) from certain forms
* Phase Two: crawl around in GH's API, make better links, maybe popups for certain users

**Comment by Jegelewicz** [comment]
Added tags in the form Tool- Bulkload... that include a link to the Arctos tool. Let me know what I've missed. I'll try to go tag obvious stuff.

**Comment by dustymc** [comment]
I'm working on categorizing the hundreds of issues without milestones, many of which seem to still be of interest, and I can try to keep up with that going forward. (Or we could just mark them abandoned and move on, I don't know....)

I still don't feel like I'm who should be prioritizing, and I don't know what to do with a huge jumble of unprioritized Issues. DWC requires two independent parties to express support before considering changes, perhaps something somewhat like that could somehow fit into our workflow?

**Comment by Jegelewicz** [comment]
I think it would help to write down a process. Something like I tried to do with [code table changes](https://docs.google.com/document/d/19kYccaxwRW4c0PxE7EddFTpzNqmp-gTC_W-lilBYzUo/edit?usp=sharing). Clearly [that was intended](https://github.com/ArctosDB/arctos/issues/2346#issuecomment-554113221), but no one ever had the time or inclination to do it or if they did I don't know where it is.

**Comment by campmlc** [comment]
Has there been an announcement that we should be using milestones? I
remember some discussion about it with the answer being "only Dusty uses
them. . . "

**Comment by dustymc** [comment]
>write down a process.

https://handbook.arctosdb.org/how_to/How-to-organize-Issues.html

>announcement

https://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html can probably always be made more clear.

>"only Dusty uses them. . . "

And implements, if I can find them.....

**Comment by ewommack** [comment]
Article on GitHub Labels and Milestones just went out in Jan 2021 Newsletter (https://github.com/ArctosDB/newsletter/issues/47)

**Comment by Jegelewicz** [comment]
@dustymc can we discuss during your office hour next week? I think some tweaking is in order as we start to manage SABI stuff.

**Comment by dustymc** [comment]
That doesn't seem like quite the right forum to me, but whatever.

**Comment by Jegelewicz** [comment]
I want to get your take first - what will be helpful/not, then we can take it to the community. I just feel like we haven't come to a satisfactory resolution....

**Comment by dustymc** [comment]
>satisfactory resolution

I'm having a great deal of difficulty imagining one that doesn't involve users watching GitHub, yet we seem to be heading towards creating more ways to avoid GitHub. 

The login page currently contains...

```
if ... "manage_collection" ... and not hasGithubAddr....
```
.. then fire up a plea for a github address.

I wonder if manage_collection should be changed to "is operator" as a start? (But not all operators can edit their agent record, so maybe manage_agents is a more workable target.)

Part of the issue is that we have 642 issues open at the moment, and I don't think anyone can be expected to sort through that. The Issues Committee was formed to organize, but mostly doesn't focus on that. Perhaps we should - first x minutes of every meeting (or every nth meeting or whatever) dedicated to organizing without getting into the details would go a long way.

**Comment by Jegelewicz** [comment]
> yet we seem to be heading towards creating more ways to avoid GitHub.

Not if I can help it!

> Part of the issue is that we have 642 issues open at the moment, and I don't think anyone can be expected to sort through that. 

Agree

> The Issues Committee was formed to organize, but mostly doesn't focus on that. Perhaps we should - first x minutes of every meeting (or every nth meeting or whatever) dedicated to organizing without getting into the details would go a long way. 

We have an Issues Committee?

Seriously though, I hope to dedicate some time to getting issues under control and making it less daunting.

> The login page currently contains...

Do we have any "manage collection" people who don't have a GitHub addy in their agent profile? I can target them directly if you can give me a list of names. Then we should move on to those with taxonomy/agent access.

**Comment by dustymc** [comment]
> "manage collection" people who don't have a GitHub 

```
select
  get_address(agent_id,'GitHub'),
  getPreferredAgentName(agent_id)
from
  agent_name 
where
  agent_name_type='login' and
  lower(agent_name) in (
  SELECT
          r.rolname as username
        FROM
          pg_catalog.pg_roles r
          JOIN pg_catalog.pg_auth_members m ON (m.member = r.oid)
          JOIN pg_roles r1 ON (m.roleid=r1.oid)
        WHERE
          r1.rolname='manage_collection'
            and r.rolvaliduntil > current_date
            );
                        get_address                        |     getpreferredagentname     
-----------------------------------------------------------+-------------------------------
                                                           | Link E. Olson
                                                           | Emily S. DeArmon
                                                           | Carolyn L. Parker
                                                           | Aren M. Gunderson
                                                           | Lam Voong
                                                           | Adrienne L. Raniszewski
 https://github.com/jandreslopez                           | Andres Lopez
                                                           | Sara V. Brant
 https://github.com/bryansmclean                           | Bryan S. McLean
                                                           | Gabor R. Racz
 https://github.com/cjconroy                               | Christopher J. Conroy
                                                           | John Watts
                                                           | John E. McCormack
                                                           | Christopher C. Witt
 https://github.com/ewommack                               | Elizabeth A. Wommack
 https://github.com/mkoo                                   | Michelle S. Koo
                                                           | Mareca Guthrie
 https://github.com/mvzhuang                               | Mingna Zhuang
 https://github.com/ccicero                                | Carla Cicero
 https://github.com/atrox10                                | Carol L. Spencer
                                                           | Alyson Wilkins
                                                           | Christopher H. Martin
 https://github.com/kmkocot                                | Kevin M. Kocot
                                                           | James L. Patton
                                                           | Katherine Latham
                                                           | Taylor Kane
 https://github.com/campmlc                                | Mariel L. Campbell
 https://github.com/mlbowser                               | Matt Bowser
                                                           | Jeffrey T. Stephenson
                                                           | Meghan L. Truckey
                                                           | Jack J. Withrow
 https://github.com/lin-fred                               | Lindsey Marie Frederick
                                                           | Eric A. Rickart
                                                           | Jayce Williamson
 https://github.com/sharpphyl                              | Phyllis Sharp
 https://github.com/AJLinn                                 | Angela Linn
 https://github.com/catherpes,https://github.com/catherpes | Andrew B. Johnson
 https://github.com/kyndallh                               | Kyndall Hildebrandt
                                                           | Steffi Ickert-Bond
 https://github.com/jtgiermakowski                         | J. Tomasz Giermakowski
                                                           | John R. Demboski
 https://github.com/dssikes                                | Derek S. Sikes
 https://github.com/byuherpetology                         | Alison Whiting
 https://github.com/keg34                                  | Kurt Egan Galbreath
                                                           | Maxwell Lucas Greenleaf
                                                           | Margaret A. Nelson
                                                           | Adam Haberski
 https://github.com/krgomez                                | Karinna Gomez
 https://github.com/adhornsby                              | Angela D. Hornsby
 https://github.com/ebraker                                | Emily Braker
 https://github.com/droberts49                             | Dawn R. Roberts
                                                           | Garth M. Spellman
 https://github.com/jldunnum                               | Jonathan L. Dunnum
                                                           | Renee Nowicki
 https://github.com/dustymc                                | Dusty L. McDonald
 https://github.com/sjshirar                               | Scott Shirar
 https://github.com/hippyherpdude                          | Peter S. Miller
 https://github.com/ehalverson26                           | Emily K. Halverson
                                                           | Dianna M. Krejsa
 https://github.com/camwebb/                               | Cam Webb
                                                           | Michael L. Moody
                                                           | Kevin Huo
                                                           | Lynn Walker
                                                           | Kelly A. Meierotto
                                                           | Jeffrey E. Bradley
                                                           | Lisa N. Barrow
                                                           | Jessie L. Williamson
 https://github.com/mbprondzinski                          | Mary Beth Prondzinski
                                                           | Michael J. Andersen
                                                           | Bryan B. Johnson
                                                           | Andrea Marie Carrillo
                                                           | Kari Megan Harris
 https://github.com/crcarter00                             | Colleen Carter
                                                           | Jason Wurtz
 https://github.com/marszulo                               | Madeline Arszulowicz
                                                           | Serina S. Brady
                                                           | Olivia Irons
                                                           | Lisa M. Tabak
                                                           | Dillon McIntire
                                                           | Alexandra Cecilia Coconis
                                                           | Ashley Lownsdale
 https://github.com/aklompma                               | Adiel A. Klompmaker
                                                           | Josh R. Pletcher
                                                           | Colleen Filipek
                                                           | Sharon M. Birks
                                                           | Zoe Scholz
                                                           | Paige Berends
 https://github.com/Nicole-Ridgwell-NMMNHS                 | Nicole Marie Volden
 https://github.com/acdoll                                 | Andrew Charles Doll
                                                           | Robert C. Dowler
 https://github.com/Jegelewicz                             | Teresa J. Mayfield-Meyer
 https://github.com/itzuecs@gmail.com                      | Itzue Wendolin Caviedes Solis
 https://github.com/kderieg322079                          | Katrina M. Derieg
 https://github.com/{gradyjt}                              | Jessica Grady
                                                           | Zack Perry
                                                           | Sarah Dempsey
(96 rows)
```

**Comment by dustymc** [comment]
In next release the portals/details page has github links

<img width="695" alt="Screen Shot 2021-07-12 at 1 50 28 PM" src="https://user-images.githubusercontent.com/5720791/125354161-55045680-e318-11eb-887d-d66741187925.png">

and the login thing will pick on anyone with manage_agents and no GitHub address.

**Comment by mkoo** [comment]
looks good!

**Comment by Jegelewicz** [comment]
We still need to work on this. I think that #3750 and its related issues make it clear that we did not communicate enough with the broader community about a significant change in functionality.

**Comment by dustymc** [comment]
>did not communicate enough 

I don't have time to go through that and the related threads it spawned and count, but I'm pretty sure that this is not the case - there were several (a dozen?) extra-GitHub announcement and solicitations, I don't think "we" have any chance of communicating **more**.

We might not have communicated **effectively** - I have no idea how many people see those notifications. Why are we not just telling people  how we communicate through the one document they can't avoid, the MOU, and then doing whatever we say we're going to do?

This really looks like a case of not having a time machine - the conversation happened in between Jon learning Arctos and coming back in with a different role. I don't (yet!) have a solution for that.

**Comment by Jegelewicz** [comment]
I think we did a lot of communicating here on GitHub, but very little announcing to the community. No newsletter article or even announcement on the Artcos listserve that I could find.

> We might not have communicated effectively - I have no idea how many people see those notifications. Why are we not just telling people how we communicate through the one document they can't avoid, the MOU, and then doing whatever we say we're going to do?

I think it might be a good idea to add something to the MOU about GitHub. The reality is that if you purchase some software, it is subject to change at the whim of the seller - at least here everyone has a chance to participate in a discussion BEFORE the change occurs. But I really do feel like we are not presenting that fact forcefully enough.

Either way - there can never be too much communication, because apparently we still are not reaching people.

> the conversation happened in between Jon learning Arctos and coming back in with a different role. 

I disagree, they were in Arctos and using it effectively, or they wouldn't have noticed the change. The issue is that people only start to participate when they have a problem. How can we get participation as an expected part of joining Arctos? (Or the understanding that lack of participation means you get what you get?)

**Comment by dustymc** [comment]
>disagree

Are you disputing the timeline of events or ??????

>- there can never be too much communication, because apparently we still are not reaching people

For many of us, that's a self-conflicting statement. 

And on that note, we could and should be much better at staying focused, which might at least allow people to keep up on the issues they care about without being inundated with details and tangentials. I'm not sure I have a solution, but perhaps we should try aggressively spinning comments which aren't obviously and intimately related to the core issue into their own issues or something.

**Comment by Jegelewicz** [comment]
> perhaps we should try aggressively spinning comments which aren't obviously and intimately related to the core issue into their own issues or something.

I'm starting to work on just that, but I am not sure I can do it alone....

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/2769
