### ISSUE TITLE
Geology attribute: private and taxon maps

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2347]
The specimens with the private (access) geology attribute that include coordinates are mapped on the taxon name page and they shouldn't be.

We can't migrate NMMNH paleo specimens until this is corrected.

**Comment by dustymc** [comment]
This situation should be added to https://github.com/ArctosDB/arctos/issues/2346. It doesn't (immediately) affect functionality for most users, but...

* it affects global performance, and
* it needs prioritized in the context of everything else.

I need an example - a quick glance suggests that map doesn't pull from these.

**Comment by Jegelewicz** [comment]
@Nicole-Ridgwell-NMMNHS can you give an example?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
[Ectoconus ditrigonus](http://arctos.database.museum/name/Ectoconus%20ditrigonus)

I double checked - the location it is showing on the map is exactly the same as what I pull up on google earth when I enter the UTMs for that locality.

**Comment by dustymc** [comment]
That's a cache - I believe that one stickies for a month. 

-bash-4.1$ ls -latr Ectoconus-ditrigonus.kml 
-rw-r--r-- 1 nobody nobody 622 Oct  9 12:51 Ectoconus-ditrigonus.kml


I flushed it.
