### ISSUE TITLE
agent exact name search

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#2348]
Can we get an option to search for an exact agent name? For example, I was trying to find possible variants for Bill Ma by searching last name "Ma" but I end up with a zillion search results to sort through because it pulls up everything with the letters "ma" anywhere in the last name. I was able to work around this by relying on the "potential problems" that came up when I tried to upload the agent, but It would be useful to have an exact search option.

**Comment by Jegelewicz** [comment]
I would expect a search by agent last name with "=Ma" in the search term would return "Bill Ma", but it doesn't return anything.

![image](https://user-images.githubusercontent.com/5725767/72945020-e4d6cf00-3d37-11ea-88ea-d0185576e7ed.png)

Bill Ma is definitely in there though:

![image](https://user-images.githubusercontent.com/5725767/72944958-c07af280-3d37-11ea-9f47-ad85521c9441.png)

@dustymc are we using the wrong method to get an exact match?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks!
