### ISSUE TITLE
More options for [Pull] feature in data entry

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2350]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
We have parts of a specimen housed at another Arctos institution. We are using the [pull] function with the catalog number of the specimen at the other institution, which is awesome! Currently this function only pulls locality, collection event information and collectors. 

**Describe the solution you'd like**
We would also like the option to pull identification and attributes which are helpful for "same individual as" relationships.

**Describe alternatives you've considered**
We are pulling what we can and entering the rest.

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
>same individual as

Just clone it?
