### ISSUE TITLE
error feedback/help

### ISSUE THREAD

**Issue by galedisler** [ArctosDB/arctos#2351]
Hi! I have been trying to search ARCTOS for records, and I keep getting an error message "execution timeout expired". I have done this same search (and similar searches) multiple times without any issue (only getting this error message a few times), but for the last week I keep getting this message. I've other searches, and I keep getting the same error message - whether I am on my home computer or at work/UAA. 

My search: "Ixodes" or "Ixodes angustus" in the identification and taxonomy section. I have also tried searching for specific records (i.e., UAMObs:Ento:85358), which also doesn't seem to work anymore. 

Thanks, 

Gale

**Comment by galedisler** [comment]
Using the identification search bar worked! Thanks. This is the error message that I have been getting. Do you have any idea why the “Any taxon, ID, common name” search bar is giving me the error message?

Again, thank you for your help.

Gale

**Comment by campmlc** [comment]
Gale, if you have a lot of data fields selected for download in your search
results page (Tools: Add/Remove Data Fields), it can slow down this search
to the point where you can get a timeout. Try removing some data fields and
see if that helps. Alternately, just don't use the ANY search feature for
IDs or Geography. We are trying to get that removed from the search bar as
it has been causing timeout problems in our current version of Oracle.
