### ISSUE TITLE
Petrified Wood

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2355]
When ALMNH paleobotany data was migrated to Arctos, all records identified as "petrified wood" in their Access database were migrated to Arctos with the identification Trachyophyta, the part name "unknown". Somewhere along the way, the common name "Petrified Wood" has been added to Trachyophyta.

While the addition of "Petrified Wood" as a common name for Trachyophyta means that ALMNH can find all of their petrified wood using a common name search, it also means that they may get unexpected results because there will be a lot of Trachyophyta that are not "petrified" in Arctos. While common names can be problematic, they are also path that non-research folk use to interact with our collections, so they need to be useful somehow. In this case I don't think using the common name attached to the TAXON_NAME is useful.

I suggest the following treatment for "petrified wood" in Arctos

For object identification use the A{string} formula "Trachyophyta{petrified wood}" (if a more refined taxon name can be presented, then change Trachyophyta to whatever that name is).

Part = "wood"
Part preservation = "petrifaction"

@Nicole-Ridgwell-NMMNHS @dperriguey @mbprondzinski @mvzhuang  please chime in.

**Comment by mbprondzinski** [comment]
This will work for me.  Hopefully the “A {string}” will work for this.  It was problematic using it with the geology specimens.  Thanks.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
That seems ok to me.

**Comment by Jegelewicz** [comment]
@mbprondzinski all records with identification "Tracheophyta" and part name "unknown" in ALMNH:ES have been updated to this format. Search the identification field for "Petrified Wood" to find them all. If any of these should not have been changed, please let me know and I will correct them.

**Comment by Jegelewicz** [comment]
[Documentation](http://handbook.arctosdb.org/how_to/How-To-Catalog-Fossil-Material.html#petrified-wood) has been added.

**Comment by Jegelewicz** [comment]
Closing as resolved
