### ISSUE TITLE
Removing 2 UT Higher Geog records that appear erroneous

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#2356]
I would like to delete the following Higher Geog records:
let me know if there's a reason to keep but I suspect they are just legacy mistakes. 

- North America, United States, Utah, Freemont County https://arctos.database.museum/Locality.cfm?Action=editGeog&geog_auth_rec_id=1005533

 - North America, United States, Utah, Park County https://arctos.database.museum/Locality.cfm?Action=editGeog&geog_auth_rec_id=1005534

If dont hear from anyone, I will do so in a week! 
/remind @mkoo  in a week

**Comment by dustymc** [comment]
I'd say just nuke 'em - they're obviously wrong and not being used.

If you find funky geography that is being used, I have merger scripts.

**Comment by mkoo** [comment]
YES I have. I sent annotations to the collection (UAM, MSB)
North America, United States, Utah, Ham County - https://arctos.database.museum/Locality.cfm?Action=editGeog&geog_auth_rec_id=1119
and annotation here-- https://arctos.database.museum/guid/UAM:Mamm:6828

North America, United States, Utah, Unitah County--> should be Uintah County
https://arctos.database.museum/Locality.cfm?Action=editGeog&geog_auth_rec_id=1005832
https://arctos.database.museum/guid/MSB:Mamm:278558

**Comment by mkoo** [comment]
Done!
