### ISSUE TITLE
Can we make Bloodhound Tracker work for us?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2357]
Currently, [Bloodhound](https://bloodhound-tracker.net) picks up specimens from GBIF, associates them with a possible ORCID and then someone has to authenticate them: https://bloodhound-tracker.net/help-others/0000-0003-0536-5044

I can sit and click the hundreds of these that are there for Mariel, but for the Arctos stuff, her ORCID is already associated, it just doesn't make it to GBIF. See https://www.gbif.org/occurrence/1058377084

How do we just pass Mariel's ORCID so that all of this can happen magically?

**Comment by dustymc** [comment]
>pass Mariel's ORCID

https://github.com/ArctosDB/arctos/issues/2141
