### ISSUE TITLE
Arctos down?

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#2358]
Is Arctos down? I can't access the specimen search page. 
I keep getting the following error:
This site can’t be reachedarctos.database.museum took too long to respond.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_TIMED_OUT

**Comment by Jegelewicz** [comment]
It is working for me now.

**Comment by ewommack** [comment]
It is for me now this morning as well. Yeah for random fixes!
