### ISSUE TITLE
Please correct link to Arctos MOU template

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2359]
The link to an MOU template on the Arctos website goes to an outdated version of the MOU which has recently caused a potential new collection and myself some issues. Can we PLEASE correct this ASAP?

Arctos Page = https://arctosdb.org/join-arctos/

Section of page =" Arctos will work with new collections to develop a Memorandum of Understanding (**download sample template**)"

MOU template links should be to  = https://drive.google.com/file/d/1GXNMdXxtf-SMgWW0ilzSxL7jDdAhG0jj/view?usp=sharing

**Comment by mkoo** [comment]
updated
