### ISSUE TITLE
Bulk delete or modify attributes

### ISSUE THREAD

**Issue by jtgiermakowski** [ArctosDB/arctos#2360]
Guess that this came up before as #595 : 

I need the ability to modify attributes in bulk, similar to bulk delete identifiers. We accidentally uploaded wrong information in the "Attribute Remark" field but have no way to modify it (save for individual specimen screens and a list from a different file) because subsequent uploads just add more attributes (same ones except for the remarks field).

One way this could be solved is similarly to the "bulk delete identifiers", by essentially 'clearing the attributes' for a specimen and then uploading new information. As of now, I'd have to do it specimen-by-specimen and attribute-by-attribute

This is also linked to #2318 because we need the ability to search and download certain attribute information.

**Comment by jtgiermakowski** [comment]
How do I add labels to this issue?? it's an issue in itself :-)

**Comment by jtgiermakowski** [comment]
Thanks for adding labels! @jldunnum had a similar issue a while back with attribute editing

**Comment by dustymc** [comment]
Attribute bulkloader and unloader can be implemented in component loader ecosystem.

**Comment by dustymc** [comment]
Next release contains

* SpecimenResults-->download attributes
* Rebuilt attribute bulkloader
* New attribute unloader
