### ISSUE TITLE
Part Name defintions added - some notes

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2363]
A volunteer at NMMNH created definitions for all of the undefined part names used by ES collections. While transferring them to the code table I noticed the following:

malar = zygomatic
Zygomatic is not in the code table, but I could see it being added. These two terms apparently refer to the same bone? Do we need them both? Could we relate them if we do to facilitate searches?

chevron =  haemal arch
haemal arch is not in the code table. See above.

magnum = capitate
capitate is not in the code table. See above.

unciform = hamate
hamate is not in the code table. See above.

scute is a specific type of osteoderm, but also "A scute or scutum (Latin scutum, plural: scuta "shield") is a bony external plate or scale overlaid with horn, as on the shell of a turtle, the skin of crocodilians, and the feet of birds. The term is also used to describe the anterior portion of the mesonotum in insects as well as some arachnids (e.g., the family Ixodidae, the scale ticks)." Here is another instance of the "foot" problem. Nicole has suggested a different treatment for osteoderm/scute - will put in a separate issue.

pes=foot
Perhaps this is the answer to #2328 vertebrates should use "pes" and inverts "foot".

podial
Unable to edit definition. Suggest definition to be: 
Unspecified bones of the wrist and ankle. In digitigrade and unguligrade animals the podials form the second joint in the limb after the elbow or knee.

sternal
Any bone which is associated with the sternum.
Is this necessary?

Apologies in advance if there are any misspellings in the definitions recently added. If any of them are totally incorrect, please either correct them or let me know.

@dustymc I thought I would be cool and place links from the definitions to Wikipedia, but my attempt at that with "angular" just messed up that line of the code table. Can you fix that one for me? Thank you!!!

**Comment by dustymc** [comment]
You had mismatched parens, and that code is sanitized only by access. I did this:

```
update 
    ctspecimen_part_name 
set 
  description='A bone of the mandible connected to all other jaw bones. In advanced therapsids, including mammals, the tympanic bone is a modified angular. <a target="_blank" class="external" href="https://en.wikipedia.org/wiki/Angular_bone">Wikipedia</a>' 
where 
  part_name='angular';

```

http://handbook.arctosdb.org/how_to/developer-guide.html#urls

>podial

I just synced them - you can edit now.

**Comment by Jegelewicz** [comment]
Great! Now I need to go back and add all of those wiki links.....

**Comment by Jegelewicz** [comment]
Wiki links that volunteer provided have been added. Thanks @dustymc 

but I still cant edit podial.

![image](https://user-images.githubusercontent.com/5725767/68440121-4484fb80-0187-11ea-8ac5-d9384bce1885.png)

**Comment by dustymc** [comment]
Apparently I'm not as bilingual as I'd like to be...

Maybe for real this time.
