### ISSUE TITLE
Does anyone know how to set-up Cold Fusion for creating reports?

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/arctos#2366]
Do I need an IT person or can I set up the RDS server myself?
![image](https://user-images.githubusercontent.com/43214224/68706912-5e8f5700-0556-11ea-99e6-249e9d4ec46e.png)

**Comment by Jegelewicz** [comment]
Mary Beth,

I'm not sure what you are doing here - I've never dealt with this?

**Comment by mkoo** [comment]
HI Mary Beth, you do not need this to edit and work on reports!
You just need the free  ColdFusion Report Builder -- let me check that the
Handbook has a working link.
Be right back!
(now all your recent issues make sense if that's all you want to do!)

**Comment by mkoo** [comment]
*ColdFusion Report Builder*
The ColdFusion Report Builder enables developers to design structured,
repeating region reports for ColdFusion (2016 release) applications.

   - Download ColdFusion Report Builder
   <http://download.macromedia.com/pub/coldfusion/updates/12/reportbuilder/ColdFusion_ReportBuilder_WWEJ.exe>
(EXE,
   52.8 MB)
   MD5 Checksum: 4C63F5E98020D2F5EBAF415A49960042

**Comment by mkoo** [comment]
If during installation, CF Report Builder asks for all sorts of remote
server details, ignore it. You can download reports from Arctos and work
locally. Make sure you have a renamed test version of the report to upload
on Arctos where some edits are easier to do (SQL handler); others are
easier to do offline (eg., format)

Hope that helps!

**Comment by mbprondzinski** [comment]
Oh, okay!  I wondered how I would get the appropriate field names without the RDS server.  So anything I need to add extra to  a template I “borrow,” can be set up once I’ve uploaded the file to Arctos.

Thanks, Michelle

**Comment by campmlc** [comment]
Hi Mary Beth, you'll need to download a template from reports and open it
in the CF Reports Builder, edit it there to your requirements, save as new
file and re-upload it to Reports. Then you copy and paste a header from
another report.  If I remember correctly, there is a webinar on this? Happy
to do a call to help walk you through it.

**Comment by mbprondzinski** [comment]
Hi Mariel,

Thanks, I did all that.  I have a loan report that I am working on, which I may need some help with once I upload it to Arctos.  I also watched Andrew Doll’s webinar, but there was no information on the RDS server, which I now understand I don’t need to define.  I am trying to recreate our Loan report.

I will keep you posted on my progress.

Thanks, Mary Beth
