### ISSUE TITLE
Agent J. Thompson

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2367]
See [How To Create Agents](http://handbook.arctosdb.org/how_to/How-to-Create-Agents.html)

Agent [J. Thompson](https://arctos.database.museum/agents.cfm?agent_id=10012023) needs some disambiguation.

It includes an AKA of [John Thompson](https://arctos.database.museum/agents.cfm?agent_id=1012019) - this agent name already exists. Anyone using J. Thompson in place of John Thompson, should change the agent affiliation and we should remove that AKA from J. Thompson.

It also includes a remark "James Thompson?" - as this is a generic "we don't know what the "J" stands for" agent name, this comment is inappropriate. Anyone using J. Thompson to stand for James Thompson?, should add the verbatim collector attribute to the affected records with "James Thompson?" as the value.

I have assigned people who I think might be using this agent name. I would like to remove the remark and the AKA from the J. Thompson agent next month - let me know if anyone objects.

**Comment by Jegelewicz** [comment]
/remind me to clean this up on December 12, 2019

**Comment by atrox10** [comment]
@ccicero J. Thompson this has old MVZbirds herps and mammals - we should figure out which name it really is (I have no idea and no time to do this now).

**Comment by acdoll** [comment]
We've got an associated collector I can get a good name from - that should
take care of ours.

**Comment by Jegelewicz** [comment]
@atrox10 @acdoll let me know once you have yours cleaned up so I can fix this. Thanks!

**Comment by Jegelewicz** [comment]
I removed the John Thompson aka's.
