### ISSUE TITLE
Request addition of new subspecies: Rallus longirostris berryorum

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#2368]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

Could I please get the subspecies: _Rallus longirostris berryorum_ added to the Arctos taxonomy?

Reference for the new name:
[http://sites.oxy.edu/mccormack/McCormack/picks/Maleyetal2016.pdf](url) 
[https://doi.org/10.1642/AUK-17-72.1](url)

**Context**
I have specimens I need to catalog from the series that describes the new subspecies. 

**Priority**
Please assign a priority-label.

**Comment by Jegelewicz** [comment]
Added.
