### ISSUE TITLE
New Nomenclatural Code - ICPN

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2372]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=CTNOMENCLATURAL_CODE

**Value**
ICPN

**Definition**
The International Code of Phylogenetic Nomenclature, known as the PhyloCode for short, is a developing draft for a formal set of rules governing phylogenetic nomenclature. Its current version is specifically designed to regulate the naming of clades, leaving the governance of species names up to the rank-based Nomenclature codes (ICN, ICZN, ICNB, ICTV).

**Collection type**
N/A

**Attribute data type**
N/A

**Attribute value**
N/A

**Attribute units**
N/A

**Part tissue flag**
N/A

**Other ID BaseURL**
N/A

**Context**
We will be dealing with many fossil taxa at NMMNH that DO NOT have a rank as they are clade names under the ICPN.

**Priority**
Please assign a priority-label.

@ArctosDB/paleontology please comment.

**Comment by dustymc** [comment]
no objection

**Comment by Jegelewicz** [comment]
added
