### ISSUE TITLE
New Taxon Terms for ICPN Clades

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2373]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=CTTAXON_TERM

**Value**
unranked clade

**Definition**
Also known as monophyletic group, is a group of organisms that consists of a common ancestor and all its lineal descendants, and represents a single "branch" on the "tree of life". 
<a   target="_blank" class="external"   href="https://en.wikipedia.org/wiki/Clade">Wikipedia</a>

**Collection type**
N/A

**Attribute data type**
N/A

**Attribute value**
N/A

**Attribute units**
N/A

**Part tissue flag**
N/A

**Other ID BaseURL**
N/A

**Context**
We will be dealing with many fossil taxa at NMMNH that DO NOT have a rank as they are clade names under the ICPN.

**Priority**
Please assign a priority-label.

@ArctosDB/paleontology please comment.

**Comment by Jegelewicz** [comment]
Related to #2372

**Comment by Jegelewicz** [comment]
For an example of how this would be used see [Archosauromorpha](https://arctos.database.museum/name/Archosauromorpha)

This name is NOT a family name, but we have no other way of adding it to the classification. For this classification, the only thing that would change would be that instead of family = Archosauromorpha, we would have unranked clade = Archosauromorpha.

**Comment by dustymc** [comment]
1) I hate it - seems like an unnecessarily complicated way of saying "we have nothing to say"==NULL. (But maybe this can be justified as something like 'official phylocode terminology'????)

1) Despite the above, while the data structure is perfectly happy with NULL as a rank the UI isn't. I'm not going to get to changing that immediately, so some temporary 'NULL, eventually' string value might make some sense.

1) I'm not sure about that particular example, but for at least some of these family=Bla and phylocode-term=Bla are different THINGS (at least in subtle ways). These classifications should probably NOT be mixed in with the "Arctos" source (where they'll inevitable get caught up in some mass update).

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Archosauromorpha is a group of reptiles that contains dinosaurs, crocs, and a few other obscure groups.

Here are examples of what I ideally would like to be able to do:
-Search on class Reptilia and find things under Archosauromorpha
-Search for Archosauromorpha and find Dinosauria (which I notice in incorrectly in Arctos as an order)

**Comment by dustymc** [comment]
It is important to note that the core Arctos taxonomy structure is NOT hierarchical; making it that way is left to those who want it that way (and there are tools to facilitate). That's necessary to deal with eg, whatever comes from GlobalNames, but it also means that SOME Reptilia might be recorded as Archosauromorpha while others aren't. (There's also no reason to suspect Archosauromorpha hasn't been used as a genus of slime mold or something; there are at least tens of thousands of homonyms and hemihomonyms in Arctos.)

Dinosauria is recorded as lots of things; which is "correct" depends on context. (What's just wrong may be a bit less subjective!)

```
UAM@ARCTOS> select distinct  term_type  from taxon_term where term='Dinosauria';

TERM_TYPE
------------------------------------------------------------------------------------------------------------------------

display_name
unranked clade
order
family
canonical name
no rank
scientific_name
name string

9 rows selected.

```

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
That clears things up a little. Still trying to learn this taxonomy model!

**Comment by Jegelewicz** [comment]
Wait, we can leave rank null? Not in my world.

![image](https://user-images.githubusercontent.com/5725767/68977806-559cc080-07b6-11ea-8121-8f956ee66208.png)

When I attempt that I get

![image](https://user-images.githubusercontent.com/5725767/68977582-cc858980-07b5-11ea-9e62-8dc5d00c8172.png)

Besides - an unranked clade is a THING that people use (aka "[official phylocode terminology](https://en.wikipedia.org/wiki/Phylogenetic_nomenclature#Ranks)"). If we could add these terms to the classifications, then Nicole should be able to do what she asks for above (as long as we maintain the classifications). No?

Another suggestion is to add these as "common names", but that seems demeaning to those who view the clades as more important and useful than the Linnean terms.

**Comment by dustymc** [comment]
>leave rank null?

``while the data structure is perfectly happy with NULL as a rank the UI isn't.``

>unranked clade is a THING

See the Dinosauria comment above - there are three ways of saying the same thing (nothing) in that tiny little slice of our data. Best case, it's not a very predictable THING.

I don't think these are common names.

I think you'll somehow come to regret mixing phylocode-like stuff and "traditional" stuff in the same classification or source, but (aside from the UI's handling of NULL, which some "we ain't sayin'" term can compensate for) nothing's stopping that.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Ok, I think we have this figured out for ourselves at least. We found a classification with ranks for our vertebrate paleo material that I think will work for us to get the right level of detail and consistency that I'd like. If any material is identified as an unranked clade, we can put it in A {string} linking the unranked clade to the next highest ranked taxon.

**Comment by Jegelewicz** [comment]
@Nicole-Ridgwell-NMMNHS can you post the name of the book this info came out of? Then I'll work on some documentation.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Vertebrate Paleontology, 3rd ed. by Michael J. Benton
