### ISSUE TITLE
Add BHL to options for adding publications

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2375]
Any chance that we can add BHL to the options for completing publication info?

For instance, see https://github.com/ArctosDB/data-migration/issues/148#issuecomment-555530748

This publication is available on BHL (The DOI there doesn't do anything) Could it? or could we use the BHL ID https://www.biodiversitylibrary.org/itemdetails/20521

**Comment by dustymc** [comment]
If they have an API that does something useful, sure - but https://iphylo.blogspot.com/2012/09/bhl-is-duplicating-dois-because-it.html

**Comment by Jegelewicz** [comment]
closing for lack of interest
