### ISSUE TITLE
South America, Ecuador, Francisco de Orellana is incorrect and should be deleted

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2376]
See https://github.com/ArctosDB/data-migration/issues/149#issuecomment-555547909

South America, Ecuador, Francisco de Orellana is NOT a Province of Ecuador. All specimens assigned to this higher geography should be moved to either South America, Ecuador, Orellana or South America, Ecuador, Orellana, Francisco de Orellana

Once all specimens have been assigned to one of the correct higher geographies, South America, Ecuador, Francisco de Orellana should be deleted.

**Comment by Jegelewicz** [comment]
@mkoo MVZ Mammals are using the incorrect Higher Geog as are MLZ Birds (don't know who to contact there).

**Comment by Jegelewicz** [comment]
/remind me to follow up on this on December 20, 2019

**Comment by dustymc** [comment]
@fsjmm1 

I have scripts to clean and merge geography if there are still any hangers-on in December.

**Comment by Jegelewicz** [comment]
There's still stuff in here, but I'm not really inclined to change MVZ stuff. I'm just gonna leave this open.
