### ISSUE TITLE
locality/event archives

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#2377]
1. Localities are archived on insert, events are not - do we need to grab initial events?

2. Add 'restore' button which will re-create versions of deleted localities/events.

3. Add 'replace' button to make 'versions' the current data for still-existing data.

@ccicero

**Comment by campmlc** [comment]
Will this allow us also to delete events? We need to be able to replace
events with updated ones, if possible, deleting the old. Or at least,
delete unaccepted events from a series.

**Comment by ccicero** [comment]
I like Dusty's suggestion. We've repeatedly run into issues where we pre-created localities and events, didn't create nicknames, didn't load within the month that they were created, and they disappeared. So YES on grabbing events as well as localities, and adding a restore button would be awesome!

Not sure I understand what the replace button would do. If you have archived localities/events that still exist, and you want to replace with archived versions?

**Comment by campmlc** [comment]
Our bird collection wants to load a temporary event that only has an
approximate locality, then re-load later with cleaned up localities and
coordinates. The original event is not based on actual data, just a
shorthand version for temporary tracking purposes. They want to delete this
shorthand version once the second, accepted event is loaded.

**Comment by dustymc** [comment]
@campmlc you can delete things now, or just leave them unused and Arctos will clean up.

@ccicero every now and then (usually when someone changes geography for a shared locality or similar) we need to "un-edit." Being able to click a button would avoid some copy-paste errors and such. Hopefully it wouldn't be used much, but it should be easy to add if we're pulling back from the archives anyway.

**Comment by mkoo** [comment]
High-five for RESTORE button!

**Comment by dustymc** [comment]
I'm aware of two instances of needing undo in the last ~4 years, and both of them were complicated enough that a button probably would not have been useful. Tentatively closing as unnecessary complication.
