### ISSUE TITLE
Accession Bulkload Agent Bug

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#2378]
**Describe the bug**
The accession bulkloader checks transaction agent 1 to make sure these match an agent in Arctos. However, it does not check transaction agents 2-6. If one of these transaction agents does not match, then it will not add those agents at all. There is no warning in either the bulkloader or the documentation that says these will not upload.

**To Reproduce**
1. Prepare an accession bulkload file
2. Introduce a typo into one of the transaction agents 2-6.
3. Load the accessions
4. Go to the accession where you put the typo and see that the agent has not loaded.

**Expected behavior**
When you upload the accession file, it should catch the errors in transaction agents 2-6 and not let you upload until they are resolved. Or, at minimum, there should be a clear warning that those agents won't load unless spelled correctly.

**Screenshots**

Agent misspelled in CSV

The Transaction agent in the CSV misspelled.
![Weber Snip 3](https://user-images.githubusercontent.com/47402809/69184323-e1be2900-0ad1-11ea-8659-da8ea22e9f5a.jpg)

The Transaction agent in the accession bulkloader misspelled. This is the screen where it has not found any more errors and gives you the option to go ahead and load everything.
![Weber Snip](https://user-images.githubusercontent.com/47402809/69184360-f4d0f900-0ad1-11ea-86e8-72b41bc1c7b4.jpg)

The accession record after loading with the misspelled agent not entered.
![Weber Snip 2](https://user-images.githubusercontent.com/47402809/69183668-a0794980-0ad0-11ea-8112-603ee66614b4.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: ?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Anyone have any ideas on this?

**Comment by dustymc** [comment]
Its definitely a bug, but I don't think it's fatal - you can just check that agents have a corresponding agent_id in the dump (purple table) - so I'm inclined to call this low priority. AWG can of course change my mind....

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Can we add a line of text somewhere on the bulkload accessions tool that says something like "bulkload tool will not verify transaction agents 2-6, transaction agents 2-6 will not load if they do not match an agent" so that people know to double-check?

**Comment by campmlc** [comment]
This is relevant for new collections who are migrating data. There should
at least be a warning or notification.

**Comment by dustymc** [comment]
>warning

done

**Comment by Jegelewicz** [comment]
We should fix in PG.

**Comment by dustymc** [comment]
> fix in PG.

Yes

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I will test this on my next batch of accession bulk uploads.

**Comment by Jegelewicz** [comment]
@dustymc any chance this is a quick fix? https://github.com/ArctosDB/arctos/issues/2378#issuecomment-565247131

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
This is still an issue in post-gres. I just tested with our mineral accessions bulkload, deliberately leaving a transaction agent 2 misspelled. The agent was not flagged during the bulkloading process and when I checked after, the agent was not added to the accessions.

This needs to be fixed or at least a warning attached so people know to manually double check transaction agents 2-6.

**Comment by dustymc** [comment]
I updated https://handbook.arctosdb.org/how_to/How-to-organize-Issues.html

This is basically not on my radar. I know how to deal with it so I'll set it to next task, then it needs prioritized.

**Comment by dustymc** [comment]
Should be checking all agents in next release, looks like we're on track to rebuild all bulkloaders, we can deal with the rest of the issues there.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thank you!

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I tested, it is now checking agents 2-6.
