### ISSUE TITLE
Need Delete Function for Loan Shipments

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2383]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Cannot delete shipment from loan; therefore cannot delete loan

**To Reproduce**
Go to a loan, remove dependencies such as projects etc. ; try to delete - get error that a child dependency is found, e.g. shipment, but there is no way to delete a shipment

See #498

**Expected behavior**
Click on delete loan button and have the loan deleted.

**Screenshots**

** Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by campmlc** [comment]
Trying to delete https://arctos.database.museum/Loan.cfm?Action=editLoan&transaction_id=21123621

**Comment by dustymc** [comment]
This needs discussion. Not being able to delete shipments is very much by design and not a bug. Protecting data that might explain things like a specimen's existence or condition seems central to a research-grade CMS. If we're going to change that, we should approach it as a community.

**Comment by campmlc** [comment]
This was a duplicate loan caused by the use of .019 in the first loan which
did not show up in a subsequent Oracle sort with only 2 digit loan numbers.
This is problematic when more than one person is assigning loan numbers and
numbering standards are inconsistent - and Arctos does not enforce
consistency. Given this, we need to be able to delete duplicates.

**Comment by dustymc** [comment]
Lam and I are both happy to help sort out accidents. Want this gone?

Arctos does not enforce consistency because there's none to enforce - everybody's got their own idea of how loan numbers should work. Force-feeding rather than suggesting a 'next' loan number for those collections who have (or want) predictable data might be possible, but I doubt if I could then prevent it being changed.

Loan numbers are strings, I can't see any reason they'd sort as anything else; I think I'm not understanding something about that comment.

**Comment by campmlc** [comment]
Yes, please, delete this one.
As a tissue manager, I work across 4+ divisions, each with its own
procedures. Not easy to keep straight. I always assign three digit loan
codes, but this division sometimes but not always assigns two digits.
Because loan numbers are strings and not numbers, the loans do not sort
sequentially between 2019.019 and 2019.20. So searching for existing loans
is non-trivial, and duplicates sometimes occur.

**Comment by dustymc** [comment]
Gone.

We can definitely talk about things like sorting - I just need details eg what you're trying to sort.

Datatype is likely less trivial - I don't think we can require any sort of number-component (and it wouldn't hold leading zeros if we could).

**Comment by campmlc** [comment]
Here is another loan to delete, please, since I cannot delete the fake shipment. This was created for today's Kew demo.
MSB:Mamm 2020.013.Mamm

**Comment by campmlc** [comment]
@dustymc

**Comment by dustymc** [comment]
gone
