### ISSUE TITLE
Return attribute remarks

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2384]
@dustymc can you write me some sql that would return the following for all MSB:Mamm records with the attribute ectoparasites detected = "yes"

CAT_NUM
for all attributes in the record:
ATTRIBUTE_TYPE
ATTRIBUTE_VALUE
ATTRIBUTE_UNITS
ATTRIBUTE_DETERMINER
ATTRIBUTE_DET_DATE
ATTRIBUTE_DET_METHOD
ATTRIBUTE_REMARK

**Comment by dustymc** [comment]
This is the best I can do right now - it'll be one attribute per row.

```

create table temp_msbattrs as
select guid,
a.ATTRIBUTE_TYPE,
a.ATTRIBUTE_VALUE,
a.ATTRIBUTE_UNITS,
getPreferredAgentName(a.DETERMINED_BY_AGENT_ID) as ATTRIBUTE_DETERMINER,
a.DETERMINED_DATE,
a.DETERMINATION_METHOD,
a.ATTRIBUTE_REMARK
from
flat,
attributes a,
attributes s
where
flat.collection_object_id=a.collection_object_id and
flat.collection_object_id=s.collection_object_id and
s.attribute_type='ectoparasites detected' and
s.attribute_value='yes'
;
```

https://arctos.database.museum/Admin/CSVAnyTable.cfm?tableName=temp_msbattrs should return CSV if writesql won't handle this (it should).

**Comment by Jegelewicz** [comment]
The SQL threw an error

![image](https://user-images.githubusercontent.com/5725767/69655543-fe0f1800-1033-11ea-9c22-aab0c99dab41.png)

but the link worked great.  Can we get stuff like this using Manage Arctos > Developer Tools > CSVFromTable ?

**Comment by campmlc** [comment]
Yes, thank you!

**Comment by dustymc** [comment]
For write sql, drop the 'create table as' bit and select csv as output.

CSVFromTable does what it sounds like, but will eat the server on 'large' tables. You'd need SQL access (which you're welcome to, as far as I'm concerned) to create the tables first.
