### ISSUE TITLE
Who did what

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2389]
We are working under a grant and it would be nice if we could consistently figure out the following for specific operators over a specific period of time (or since October 1, 2019)

Taxon names added by
Classifications added/edited by
Higher Geography added by
Agents added/edited by
Part Names added/edited by
Geology Attributes added by

@dustymc Can we do this with existing tools or can we get some SQL to help us out?

**Comment by dustymc** [comment]
See eg https://github.com/ArctosDB/PG_DDL/issues/17 (which is a little specific for this, but we do need an overall strategy).

You can get the structure of a table by eg

<img width="698" alt="Screen Shot 2019-12-02 at 7 49 45 AM" src="https://user-images.githubusercontent.com/5720791/69973412-55036a00-14d8-11ea-9f0c-1e8f52e1cc0f.png">


and from there you could do something like

```
select count(*) c from taxon_name where CREATED_BY_AGENT_ID=21300608
```

Agents and taxa have created data; we don't keep much edit data. I think it's in audit logs, but digging it out of them isn't trivial (ping Lam if you want to try anyway).
