### ISSUE TITLE
Agent info disappeared?!

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#2390]
In 2018 the UAM:EH collection received a donation associated with Larry Allan Beck, Alaska's "Ambassador of Good Will." http://arctos.database.museum/guid/UAM:EH:UA2018-003-0001
At the time, I distinctly remember adding a great deal of biographical information to his agent record, including his birth/death dates, references to a couple of Facebook groups relating to his Anchorage-based television show Mother Moose (which I just added back)

Today something popped up on Facebook and I wanted to create a link to our object to share the fact that we had this piece. When I clicked on Larry's name as the collector (http://arctos.database.museum/agents.cfm?agent_id=21276015) I was taken to an agent record completely devoid of content -- and created by @dustymc  on 2014-02-17... four years prior to our accessioning of this parka.

I would have never let an agent merge notice go by for him if someone had marked his record as a 'bad duplicate of' and I would highly doubt an agent record with so much content would have been intentionally removed or merged with another record. @dustymc  is there any way to find out what happened? I know I filled out this agent record and spent a good deal of time doing that research and data entry... I guess it's possible my editing process timed out if I got distracted by something else before I hit save, but I'm worried that something else happened. Any way to search the editing history of agent records?

**Comment by Jegelewicz** [comment]
It looks like there is TONS of stuff there: https://arctos.database.museum/agents.cfm?agent_id=21276015

**Comment by dustymc** [comment]
I don't have anything very useful and readily available - there's nothing very suspicious in the last month-and-change of access data. TACC might have older access logs, or Lam might be able to dig through audit logs and older backups. Both are fairly resource-intensive processes, and I'm not sure how much the backup schedule covers or how deep the audit logs go.

Going forward, see eg https://github.com/ArctosDB/PG_DDL/issues/17 - we as a community need to develop realistic backup (or audit, or whatever ya'll want) strategies, including plans to provide the resources such things need.

**Comment by AJLinn** [comment]
Thanks Dusty. No worries, I just repopulated the agent file.
Your link sent me to a 404, but yes, I agree, backup strategies are key to moving up to the "Big Dog" category.

**Comment by dustymc** [comment]
https://github.com/orgs/ArctosDB/teams/arctos-users should now have access to https://github.com/ArctosDB/PG and https://github.com/ArctosDB/PG_DDL
