### ISSUE TITLE
KNWR records not being updated on GBIF

### ISSUE THREAD

**Issue by mlbowser** [ArctosDB/arctos#2391]
I would like for records from KNWR collections to be available via GBIF.  This used to work properly, at least for the KNWR:Ento collection.  Now the older GBIF occurrences still exist, but they no longer provide a link back to the original collection records on Arctos.  One example is provided below.

<https://www.gbif.org/occurrence/412580833>

<http://arctos.database.museum/guid/KNWR:Ento:7331>

I would very much like to have records from KNWR:Ento and KNWR:Herb updated on GBIF and I would like to see data from recently added collections KNWRObs:Herb and KNWRObs:Bird also appear on GBIF. All of our collection data should be publich domain (CC0). Do I need to register the new collections with GBIF?

**Comment by Jegelewicz** [comment]
@dustymc and @dbloom are these guys set up for monthly push (or pull, whichever one it is)?

**Comment by tucotuco** [comment]
That Ento resource on GBIF is an orphaned data set. There is no public
equivalent on the VertNet IPT. I can't log in to the IPT right now to see
if there is a non-public one that just hasn't been exposed. Working on
that.

**Comment by dbloom** [comment]
@tucotuco This is a collection, along with several others, that I have been working on for some time and have b. At the moment there is are no resources on the VertNet IPT for any of the resources on the old Arctos DiGIR (https://www.gbif.org/installation/5fe0e056-f762-11e1-a439-00145eb45e9a). This DiGIR server has failed and is no longer serving to GBIF.

I will continue this process with @mlbowser to bring KNWR:Ento and KNWR:Herb onto the VN IPT and into GBIF.

**Comment by Jegelewicz** [comment]
Thanks!

**Comment by campmlc** [comment]
Hi Dave,
The most important collection to bring back up besides KNWR is HWML. They
are one of the Arctos partners that just received NSF TCN funding for
digitization of ectoparasites, and the SCAN network needs to be able to
harvest their data from the VertNet IPT to add to the project portal.
Thanks,
Mariel

**Comment by dbloom** [comment]
Moving forward here. Submitted an endorsement request from the US Node for KNWR. Creating 7 new resources on the VN IPT for all KNWR datasets in Arctos. Matt Bowser is on board and prepared to review metadata when they are ready.

**Comment by dbloom** [comment]
All 7 KNWR resources have been published to GBIF, iDigBio has been notified, and VertNet has received a harvest request (for the vert datasets).

I have requested that GBIF remove the old versions of the KNWR Herb and Ento datasets. That should happen with 24-48 hours.

https://www.gbif.org/publisher/3492d3bb-0ca5-4605-851a-82e4edbc6acd

**Comment by dbloom** [comment]
In addition: These new publications should solve the initial reason for this issue and may be closed at Arctos' discretion.

STAMP is next.

**Comment by mlbowser** [comment]
Thanks, @dbloom!

**Comment by mlbowser** [comment]
Is there a way to obtain the links from Arctos records to GBIF in bulk? For example, if I want to obtain a list of all the GBIF occurrence records from a project, is there a way to obtain the GBIF occurrence records from the results of a specimen search? Alternatively, could we write a query to obtain these relationships? I failed to find which table these relationships are stored in.

**Comment by dustymc** [comment]
Those links are not stored - they're pulled from GBIF's API on the fly. (There's a cache, but it won't be very useful for this.) I just look for eg

http://api.gbif.org/v1/occurrence/search?organismId=http://arctos.database.museum/guid/KNWR:Ento:7331

Note the http NOT https in the URL-GUID.

I'm not sure what all GBIF's API supports, but let me know if you want something built into Arctos or help with code or whatever.
