### ISSUE TITLE
Inconsistency in name for Specimen_Event_Remark

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#2392]
On data entry, the bulkload title "SPECIMEN_EVENT_REMARK" is "Specimen/Event Remark":

![Screen Shot 2019-11-29 at 8 00 58 AM](https://user-images.githubusercontent.com/15368365/69877279-0313d780-127f-11ea-814f-e393f30f7f87.png)

In the catalog record, it is "Specimen/Event Remarks:"

![Screen Shot 2019-11-29 at 8 00 03 AM](https://user-images.githubusercontent.com/15368365/69877342-30608580-127f-11ea-8629-14d6b73f591c.png)

On the Search Screen it is "Record/Event Remark:"

![Screen Shot 2019-11-29 at 8 00 31 AM](https://user-images.githubusercontent.com/15368365/69877385-4b32fa00-127f-11ea-9126-7099e8e03072.png)

On the Search Terms it is "specimen-event remark"

![Screen Shot 2019-11-29 at 8 00 11 AM](https://user-images.githubusercontent.com/15368365/69877478-8cc3a500-127f-11ea-9f8e-2c9fdf3e6020.png)

 Can we make them all identical?

**Comment by sharpphyl** [comment]
Ok. That probably explains #2408 too.

**Comment by dustymc** [comment]
Merge-->#772
