### ISSUE TITLE
Invitation to Join Git Hub

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/arctos#2393]
Our new Paleo Curator started today and I wanted to set him up on Git Hub, but I am not able to invite him to join.  Can someone please do this for me?  Thanks.

Please invite Adiel Klompmaker:  aaklompmaker@ua.edu

**Comment by campmlc** [comment]
Hi Mary Beth,
Have him follow instructions here first if he hasn't already done so:
https://handbook.arctosdb.org/how_to/How-to-Use-Github-for-Arctos.html
He should be able to post and respond to issues without permissions. Once
he is set up and comfortable with using github, he can request further
access as described in the handbook.
