### ISSUE TITLE
Move claim button to top of load extras page

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/arctos#2397]
I have to add my parts under "specimen part extra" because I need to record the storage location.  Inevitably, I get the same error message (see below):
![image](https://user-images.githubusercontent.com/43214224/70092617-4f934600-15e4-11ea-908c-192e5fe7a511.png)

There is nothing really invalid about this entry, but I have to try everything under the sun to get it to validate, until finally (one day) it validates!  Then it goes through to Arctos.  It's as if it needs to think about if before it will commit to accepting it!

**Comment by Jegelewicz** [comment]
@mbprondzinski Do you know how long it takes between the data entry and when this works?

**Comment by dustymc** [comment]
The part "extras" rely on information that's in the bulkloader. It can't validate until the specimen loads and that information becomes available. Specifically, the cataloged item is currently invalid because it doesn't exist (except in the bulkloader), and the part is invalid because it has no idea what collection code to use without a specimen to check. That should all sort itself out once the core record loads.

**Comment by Jegelewicz** [comment]
Oh, so she's trying to validate these BEFORE the record has been loaded? Is that the case @mbprondzinski ?

**Comment by mbprondzinski** [comment]
Well how long must I wait for it to load?  I've certainly told it to load.  I waited over two weeks for the last one to validate so I finally deleted the part and then I guess the specimen loaded so then I was able to add the part as an edit.

**Comment by dustymc** [comment]
>Well how long must I wait for it to load? 

Variable, but <20 minutes around 99% of the time.

> I've certainly told it to load.

<img width="187" alt="Screen Shot 2019-12-04 at 6 01 52 AM" src="https://user-images.githubusercontent.com/5720791/70148803-be5fb600-165b-11ea-8300-21f801a4c896.png">

**Comment by mbprondzinski** [comment]
i don't care what IT says, I know I approved it.  I've hit every highlighted word in all the bulkloader drop downs.

**Comment by campmlc** [comment]
Mary Beth, the question is whether the primary record had loaded. Can you
search Arctos and find the record that this "extra" attaches to?  The extra
parts won't load until the primary record loads. If a record is hung up in
the main bulkloader ( check Bulkload : Browse and Edit), then the extras
will hang out in the extras bulkloader no matter how many times you mark
them to load.
If the main record is online in Arctos and the extras still won't load,
that is some other problem.
@dusty

**Comment by mbprondzinski** [comment]
Okay, I now see what the problem is…that little blue box way down at the bottom of the page does not appear anywhere as a reminder that IT needs to clicked!  Can’t it be in a more accessible place in the document, like up in the right hand corner with a disclaimer?  It’s not like I add new records on a daily basis and I can’t remember what and where everything is on a page if I can’t see it.  I click everything that is highlighted because I can’t tell from looking at the page what exactly needs to be done.  Sorry, but I’m not a programmer so this all looks very foreign to me.

**Comment by mbprondzinski** [comment]
Yes, Mariel, I understand, and I also figured out where the problem is, which keeps on alluding me when I enter a record:  the little blue “claim” button way down at the bottom of the page!  I never scroll that far down because I don’t remember it is there!  It really should be somewhere up high where it is noticeable and people are aware it needs to be “hit” to load their records.  I know I will forget after another week goes by and I haven’t entered a record by hand.

**Comment by campmlc** [comment]
Agree that important buttons should be obvious and at top of page. I know
the idea is to force users to scroll through long text tables to the bottom
looking for problems, but it would be better to have some notification at
the too, eg " please scroll to bottom to review potential errors and
approve to load".

**Comment by mbprondzinski** [comment]
Yes!  I never remember it’s down there and needs to be hit.  That’s why I’m hitting every highlighted word I see in the hopes I’m loading/approving/validating…whatever all is required!
