### ISSUE TITLE
New Taxon Ranks for ichnofossils

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2400]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Table**
[CTTAXON_TERM](http://arctos.database.museum/info/ctDocumentation.cfm?table=CTTAXON_TERM)

**Values**
ichnofamily  
ichnogenus  
ichnospecies  

**Definition**
ichnofamily - Any family known only from trace fossils, such as footprints, coprolites or nests. Superordinate to ichnogenus. [Wiktionary](https://en.wiktionary.org/wiki/ichnofamily)

ichnogenus - Any genus known only from trace fossils, such as footprints, coprolites or nests. Superordinate to ichnospecies. [Wiktionary](https://en.wiktionary.org/wiki/ichnogenus#English)

ichnospecies - Any species known only from trace fossils, such as footprints, coprolites or nests. A two-part name, a "binomial". The first part of the binomial is the ichnogenus to which the ichnospecies belongs. A primary subdivision of a taxonomic ichnogenus. [Wicktionary](https://en.wiktionary.org/wiki/ichnospecies#English)

**Context**
See https://github.com/ArctosDB/arctos/issues/2394#issuecomment-561876570

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
Adding these could break the classification bulkloader, but that can be fixed ~easy enough if it becomes critical. Otherwise seems reasonable to me.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Yes to this. Also as an FYI, ichnofamily, ichnogenus, and ichnospecies are explicitly governed by the ICZN.

**Comment by Jegelewicz** [comment]
Added ichnospecies, no problem. Tried to add ichnogenus and get:

![image](https://user-images.githubusercontent.com/5725767/71918190-02544800-313f-11ea-866a-e67db9ad11b7.png)

 @dustymc ?

**Comment by dustymc** [comment]
You need to order the new term in the list (using the "drag" column) before adding another.

**Comment by Jegelewicz** [comment]
I was going to leave these at the bottom rather than put them mixed in with the other ranks....

**Comment by dustymc** [comment]
Just drag it up then back down I think.

**Comment by Jegelewicz** [comment]
That worked. Thanks!

**Comment by Jegelewicz** [comment]
I am reopening this because it has caused problems.

Would like to either make what we have a workable solution or see if we can do something like

> [We could also just declare that taxon_status=ichnotaxon term ranks are implicitly prepended with 'ichno' or something - not (explicitly) correct, but I don't think it would have any usability fallout either.](https://github.com/ArctosDB/arctos/issues/2394#issuecomment-561241836)

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
What is the problem that is happening?

**Comment by Jegelewicz** [comment]
I can't check it right now, but I don;t think the bulkloader includes the new fields.
