### ISSUE TITLE
Patagonia

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2401]
We have stuff from "Patagonia". This is a [recognized "region"](https://en.wikipedia.org/wiki/Patagonia) of South America that spans a couple of countries. A few questions:

Should this be included in Higher Geography?

if so, 

Should I create it as a FEATURE? It seems incorrect to put it anywhere else since it isn't a formal governmental entity.

**Comment by dustymc** [comment]
I want to enthusiastically vote "no," but we do somehow have a precedent for vague regional data - eg, https://arctos.database.museum/geography.cfm?FEATURE=Interior - and we seem to have only vague ideas regarding what we're trying to accomplish with geography. This would be a significant step away from what _I_ think we should be attempting - providing a consistent way of locating specimens - but if the community is OK with that, I can be too.

**Comment by tucotuco** [comment]
Patagonia is actually well defined. Everybody here knows exactly what it is.

But there are features that are named and vague, and those that are named
and definitive.

**Comment by dustymc** [comment]
So is Dixie, but it still leads to a bunch of potential ways of naming a place, which I (and perhaps I alone) see as something that should be avoided.

**Comment by campmlc** [comment]
Do we use wkts for higher geography?

**Comment by tucotuco** [comment]
I want to say, "No" right away, but I think I had better understand what
you mean first.

**Comment by Jegelewicz** [comment]
> Do we use wkts for higher geography?

No - if we did, we wouldn't need the solution we arrived at in #2353

**Comment by dustymc** [comment]
>wkts

Sometimes - it's always an option, we don't always have the data. Spatial data clarifies exactly where the boundaries of "US, Dixie, TX, Whatever County" are, but it still provides multiple ways of saying "Whatever County, Texas" and from that it should be expected that some (most, perhaps) users will find only part of what they're looking for. I see that as A Bad Thing, our data suggests this is not the only outlook.

**Comment by Jegelewicz** [comment]
I change my answer because:
![image](https://user-images.githubusercontent.com/5725767/70252010-dc054c00-173d-11ea-92ad-0c815a07c403.png)

**Comment by campmlc** [comment]
It seems like a potential solution, especially for older localities that do
not  reflect current accepted geopolitical boundaries.

**Comment by Jegelewicz** [comment]
We could use a WKT for Patagonia (one exists somewhere because it is on the Wiki page...). And if Patagonia is a feature and ALL possible higher geographies that might fall in that WKT are created, then Patagonia should work perfectly.

But

No one is going to create all of those higher geographies and inevitably, someone will create a higher geography that falls inside the Patagonia WKT but doesn't include Patagonia (sometimes it will be inevitable as only one feature per Higher Geog is allowed, so a national park in Patagonia only gets one or the other).

So it is definitely imperfect. Now I am kinda leaning toward just putting it in Spec Loc

**Comment by dustymc** [comment]
> if we did, we wouldn't need the solution we arrived at in #2353

For those, the locality spatial data and the geography spatial data are just identical.

>It seems like a potential solution

What does?

> especially for older localities that do not  reflect current accepted geopolitical boundaries.

I think that comes back to what we're trying to do with geography. I can definitely see reasons to include or exclude "Ottoman Empire," and they'd all be MUCH more useful with both spatial and temporal components.

**Comment by Jegelewicz** [comment]
> all be MUCH more useful with both spatial and temporal components.

Agree! But none of us is ever going to get to all of that. Like Taxonomy, I feel the solution requires a much larger team of participants to create something useful for everyone.

**Comment by tucotuco** [comment]
The famous Locality Service John has been talking about forever. I am
actually making headwah on that, and would like to circulate the proposal
when it is ready. Maybe January.

**Comment by dustymc** [comment]
>someone will create a higher geography that falls inside the Patagonia WKT but doesn't include Patagonia

http://handbook.arctosdb.org/documentation/higher-geography.html#guidelines-for-geographic-terms-in-arctos

>Be consistent. At the largest practical scale (usually ~country), do the same thing for all records. For island nations, ensure that the island data are consistent. Ensure all county-level records include qualifiers (County, Parish, etc.) or that none do.

I think Patagonia would bisect a couple Argentine provinces, so even if we're as consistent as we can be we'd end up with some weird overlap.

>larger team of participants 

Arctos is normalized and built to talk to the world. I've reserved our place in line in case some sort of rodent aficionado happens to build some sort of service that can deal with all or some of this....

**Comment by Jegelewicz** [comment]
> rodent aficionado

Tee hee

**Comment by Jegelewicz** [comment]
> http://handbook.arctosdb.org/documentation/higher-geography.html#guidelines-for-geographic-terms-in-arctos
> 
>     Be consistent. At the largest practical scale (usually ~country), do the same thing for all records. For island nations, ensure that the island data are consistent. Ensure all county-level records include qualifiers (County, Parish, etc.) or that none do.

I don't know whether to laugh or cry.

**Comment by Jegelewicz** [comment]
How about this as a solution. If we are all being consistent, "Patagonia" could be a SrcTerm in every Higher Geog enclosed in "Patagonia"! I'll get on that....

**Comment by dustymc** [comment]
>"Patagonia" could be a SrcTerm 

Definitely useful, whatever else happens. 

Search terms came out of the geography-magicker-cleaner-upper thing and are useful for more than might be obvious to most users. And there's a rule...

>DO include any equivalent data excluded by these “rules” in “search terms.” These are becoming increasingly valuable in automated mapping to Arctos (and reducing duplicates); please MINIMALLY copy all of the “alternate names” (such as Spanish place names containing diacritics or “local” names given in Arabic or Thai characters) from Wikipedia into individual search terms fields.

**Comment by Jegelewicz** [comment]
I'm over this - closing
