### ISSUE TITLE
Search for geography by Island Group

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2402]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Searching for geography with the Island Group field always yields no results

**To Reproduce**
1. Go to [Find Higher Geography](https://arctos.database.museum/geography.cfm)
2. Select an Island group to search by "Capricorn and Bunker Group"
3. Click Find Matches
4. See no results (except you don't even get a "your search returned no results", it just looks like nothing happened)

![image](https://user-images.githubusercontent.com/5725767/70265552-e6344400-1757-11ea-804e-97cc5039e171.png)

**Expected behavior**
I expect all of this to show up:

![image](https://user-images.githubusercontent.com/5725767/70265674-23003b00-1758-11ea-8418-a000401d48df.png)

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Firefox 
 - Version 70.0.1

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
it was something simple so I patched it in
