### ISSUE TITLE
Add group agent not working

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2403]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
When adding agent names to a group agent, the first name adds without issue. Clicking add a row creates a new row with suggestion of "new group member". But when a new agent name is added and I hit tab, nothing happens.

**Expected behavior**
I should be able to enter an entire or partial agent name and hit tab to have the agent name accepted. 

**Desktop (please complete the following information):**
chrome

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
What's the group name and what agents are you trying to add?

**Comment by campmlc** [comment]
CIIBA Crew 2014 agent_id=21282281
all the agents listed in media
https://web.corral.tacc.utexas.edu/UAF/arctos/mediaUploads/AdrienneR/2014_062_field_datasheets.pdf

**Comment by dustymc** [comment]
Thanks - patched.
