### ISSUE TITLE
Duplicate Locality/ Collecting Event question

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2404]
I'm trying to understand how duplicate localities and collecting events are identified and merged. We have parasite events that were created from host events, which appear to be identical, but which have different collecting event IDs. How does this happen, what distinguishes these two events, and why does a search on duplicates return no results? Why don't these merge automatically?
Finally, what can we do to ensure that parasites and hosts share collecting events, if we are using the CE ID to bulkload host event data to the parasites?

Collecting Event ID 11146683 for MSB parasite records
Collecting Event ID 30884 for UAM host record

**Comment by dustymc** [comment]
http://arctos.database.museum/tools/userSQL.cfm
select * from collecting_event where collecting_event_id in (11146683,30884)
<img width="211" alt="Screen Shot 2019-12-05 at 1 24 20 PM" src="https://user-images.githubusercontent.com/5720791/70275233-90b16480-1762-11ea-8713-9c594fb21260.png">

If they share the ID they share the data object - there's not any way I know of for them to get separated from that.

**Comment by campmlc** [comment]
Thanks, this is helpful to figure out the appropriate workflow on our end
to avoid this in the future.
