### ISSUE TITLE
Geography Cleanup "Palau Islands"

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2405]
Currently, islands in Palau are in Higher Geography under the Island Group "Palau Islands". This doesn't appear to be a valid island group. According to the Wiki page, these should be part of the Caroline Islands group. I have added some new higher geography and used Caroline Islands for them, but I would like to edit all islands in Palau to reflect the appropriate group. Any oppositions to this? @ccicero @mkoo MVZ is using these.

**Comment by dustymc** [comment]
See also http://handbook.arctosdb.org/documentation/higher-geography.html#geographic-feature - island "subgroups" have traditionally been stuffed into feature.

**Comment by mkoo** [comment]
I would like to review these first. I think this is an attempt to identify
the sovereignty and as such would be part of the Palau Republic which is a
distinct part of island chain. But I may be ok with this change depending
on how the specimens and their collections are described. We are not
consistent about geography and administrative boundaries but I have been
trying to keep admin distinctions reflected in HG  and geographic
distinctions as arctos features.

**Comment by sharpphyl** [comment]
We have specimens from Palau.  I have no problem changing from Palau Islands to Caroline Islands, of which the Republic of Palau is a part.

**Comment by Jegelewicz** [comment]
@sharpphyl @mkoo any progress here? Shall I make changes or do we just drop this?

**Comment by sharpphyl** [comment]
I'm no longer so sure that Palau is in the Caroline Islands.  Per Wikipedia https://en.wikipedia.org/wiki/Palau "The nation has approximately 340 islands and **connects** the western chain of the Caroline Islands with parts of the Federated States of Micronesia."  (My emphasis).  

Maps of the Caroline Islands are inconsistent but most start east of Palau.  I found one that put Kayangel Island in the Carolines (as a birding location) but directions from Kayangel to Caroline Islands on Google Earth show the Carolines starting with the Nygulu Atoll.  Is there an official WKT for the Caroline Islands?

<img width="1567" alt="Google Map - Palau to Caroline Islands" src="https://user-images.githubusercontent.com/15368365/144750294-d601da18-af7f-46f8-ab40-3bfd628d5d26.png">

I also agree that Palau Islands is not geographic or political entity and should be eliminated.  This is the same issue we had with [#1315](https://github.com/ArctosDB/arctos/issues/1315) and we still have with Fiji and Tonga.  Perhaps we could resolve that issue at the same time?  Eliminating a redundant Island Group enables addition of subisland groups.  In the case of Palau those could be the [Rock Islands](https://en.wikipedia.org/wiki/Rock_Islands) or [Southwest Islands](https://en.wikipedia.org/wiki/Southwest_Islands_(Palau)).

While we're about it, could we add the rest of the Palau states so we know they are all consistent?  https://en.wikipedia.org/wiki/States_of_Palau

**Comment by Jegelewicz** [comment]
@sharpphyl I don't know how to add them in order to make things consistent - was hoping to clear this off the issue list, but it needs consensus from others - I'm going to drop it for now.

**Comment by Jegelewicz** [comment]
Closing - this is a very low priority and maybe whatever is going on with geogrpahy/spatial stuff will take care of it anyway.
