### ISSUE TITLE
replace 'specimens' in summary results with 'catalog records'

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#2408]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

The search menu to choose 'summarize results' has been edited to change 'specimens' to catalog records' but not the results. See below. All instances of the word 'specimens' are misleading and should be replaced with 'catalog records'.

![Screen Shot 2019-12-09 at 10 20 07 AM Dec 9, 19](https://user-images.githubusercontent.com/9099827/70465570-b2b22c00-1a6d-11ea-83b6-fe350d69ff6d.jpg)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
Merge-->#772
