### ISSUE TITLE
weird loan behavior

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2410]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Adding two specific catalog items to a loan (as subsamples) duplicates the part added to the loan, so that two parts of the same catalog number show up in the Review Loan form and the  loan csv download. However, only one part subsample on loan shows up in the specimen record. Deleting the extra part subsample in Review Loan deletes both subsamples, and the part is then missing from the loan.
 
**To Reproduce**
1. Go to https://arctos.database.museum/loanItemReview.cfm?transaction_id=21124396
2. Click on Review Loan Items
3. Scroll down to  MSB:Mamm:89866 and MSB:Mamm:90845
4. See duplicates

**Expected behavior**
When I add one part subsample, there should only be one part subsample in Review Loan Items.

**Screenshots**
![Screenshot 2019-12-09 20 32 12](https://user-images.githubusercontent.com/14808196/70493148-f172d100-1ac3-11ea-8eda-0d1b6557090a.png)
![Screenshot 2019-12-09 20 37 03](https://user-images.githubusercontent.com/14808196/70493164-fd5e9300-1ac3-11ea-89f2-2e3c81dd8e95.png)
![Screenshot 2019-12-09 20 33 39](https://user-images.githubusercontent.com/14808196/70493169-00f21a00-1ac4-11ea-8b3c-899ec9555843.png)
![Screenshot 2019-12-09 20 34 25](https://user-images.githubusercontent.com/14808196/70493173-02bbdd80-1ac4-11ea-9e71-48072b6ae9a5.png)

** Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**
 - Browser chrome

**Additional context**
Didn't happen on other parts or previous loan. Only these two catalog records, these two barcodes, and has happened repeatedly over 4 attempts.

**Priority**
Please assign a priority-label.

**Comment by campmlc** [comment]
[2019.094.MSB_Mamm_loan_invoice.pdf](https://github.com/ArctosDB/arctos/files/3942904/2019.094.MSB_Mamm_loan_invoice.pdf)

Loan invoice report does not show the duplicate parts.

**Comment by dustymc** [comment]
I think this is related to trying to turn ancient Oracle into JSON with ancient CF; it should fix itself in PG.
