### ISSUE TITLE
genbank crawler

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#2413]
The genbank crawler is timing out, I think mostly due to irrelevant searches. (E.g., "Obs" collections return huge and likely entirely unrelated datasets.)

Suggest we add 'genbank_collection' to table collection and search genbank only for registered collections, rather than all guid_prefix.

We need to ensure that 'register with genbank' is somewhere in new collections instructions, and will need to work with existing collections to get the prefix before full implementation.

The report is here:

<img width="486" alt="Screen Shot 2019-12-12 at 9 46 55 AM" src="https://user-images.githubusercontent.com/5720791/70736073-5dbc2300-1cc4-11ea-90ef-5a40dd257332.png">

"specimen_voucher:collection" entries are almost certainly correct ("almost" because authors do cite random things as catalog numbers - human review is still needed); the table can be sorted by any column. @atrox10 @mkoo  there are ~5K unlinked MVZ herps.

"specimen_voucher:institution" is a little flakier, but I clicked a few  and they mostly look plausible - another 50K genbank links would be nice to have @fsjmm1 @mkoo  @amgunderson

**Comment by campmlc** [comment]
This sounds reasonable. FWIW, MSB Mamm is willing to delete MSB:MammOBs.

**Comment by Jegelewicz** [comment]
> We need to ensure that 'register with genbank' is somewhere in new collections instructions

Added as an item in the [data migration project template](https://github.com/ArctosDB/data-migration/projects/1), but need instructions for how to register. @campmlc ?

**Comment by dustymc** [comment]
Crawler is rebuilt to ignore collections without genbank_collection, to deal with a large number of collection, and is simplified. Timeout errors are gone and server load is significantly reduced.

TODO:

* reshedule to run aggressively under the new format
* flush existing cache
* relax the schedule when caught up

**Comment by dustymc** [comment]
I believe the last of the bugs (inaccurate found count) is resolved; closing.
