### ISSUE TITLE
reports

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#2414]
**SABI Goal**
Replace collection reporting and labeling functions currently using Adobe ColdFusion Reporter with JasperReports, an open-source, java software library.

1. Eventually, figure out how to host cfrs on github and integrate with arctos

2. Now, clean up junk

https://docs.google.com/spreadsheets/d/1Y5vpJ9bkV4pwn8FeFv0QfZ7G_19ZJXdSmsROTaz5Qy4/edit?folder=1INXyJj_QLOovtzAuFjTXIFPsOI_H8CyS#gid=0

**Comment by dustymc** [comment]
CFRs

[reports.zip](https://github.com/ArctosDB/arctos/files/3957481/reports.zip)

**Comment by dustymc** [comment]
@mkoo templates attached above

**Comment by dustymc** [comment]
Reports have been deprecated by ACF and are not supported by Lucee. We're running a very old version of ACF for reporting. It's running on an OS which has been deprecated, and may or may not run on something else. Suggest we focus on https://github.com/ArctosDB/internal/issues/37 rather than investing more in this system.

**Comment by Jegelewicz** [comment]
SABI Goal:

Replace collection reporting and labeling functions currently using Adobe ColdFusion Reporter with JasperReports, an open-source, java software library.
