### ISSUE TITLE
Help with SQL and cat_num order on report for container label

### ISSUE THREAD

**Issue by jtgiermakowski** [ArctosDB/arctos#2417]
We spent a bunch of hours trying to get a container label with items ordered by cat_num to no avail. Everything else works well EXCEPT the sorting of cat_num. Can someone help?

Should the .cfr file the the report contain data expression, e.g.: ""MSB:Herp:" & ListSort(catnumlist, "Numeric", "Asc")? zipped cfr file at the end of message

Pre-Function:
catnum_to_list
SQL:
select 
flat.scientific_name, 
  flat.family, 
  flat.country,
  flat.state_prov,
  flat.spec_locality, 
  flat.county, 
  flat.cat_num,
  case
  when part_name='whole organism (formalin-fixed, 70% ethanol)' then '70% Ethanol'
  when part_name='body parts (ethanol)' then '70% Ethanol'
  when part_name='whole organism (formalin-fixed, 95% ethanol)' then '95% Ethanol'
  when part_name='whole organism (50% isopropanol)' then '50% isopropanol'
  else part_name
  end part_name,
  contains_part_container.label container_label 
FROM 
  flat,
  specimen_part,
  coll_obj_cont_hist,
  container part_container,
  container contains_part_container
WHERE 
  flat.collection_object_id=specimen_part.derived_from_cat_item and
  specimen_part.collection_object_id=coll_obj_cont_hist.collection_object_id and
  coll_obj_cont_hist.container_id=part_container.container_id and
  part_container.parent_container_id=contains_part_container.container_id and
 contains_part_container.container_id in (#container_id#)
ORDER BY
cat_num

This zip archive contains the .cfr file
[MSB_JAR_country_LARGE_barcode_TEST.zip](https://github.com/ArctosDB/arctos/files/3975608/MSB_JAR_country_LARGE_barcode_TEST.zip)

**Comment by dustymc** [comment]
How can I re-create? I need a container_id and a report name.

I'm guessing catnum_to_list isn't doing what you want because 

https://github.com/ArctosDB/arctos/blob/master/Reports/functions/label_functions.cfm

OUTPUT:
			
			* cat_num as range-containing list in variable catnumlist

which isn't going to re-sort well.
