### ISSUE TITLE
Collection causing timeout at search

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#2418]
I'm having MAJOR problems with timeouts when working with one particular collection.
UA2018-012 is a collection of ivory carvings. Right now I'm seeing 210 catalog records. I have a custom search result window that adds the following columns: maker, media, and collectors.

I finally just got all 210 records to show up when changing row count to 250. When set to row count 100 (which is what i normally show) it would get stalled out going to the second page.

I also have one record (http://arctos.database.museum/guid/UAM:EH:uA2018-012-0080) that I'm trying to fix the catalog number to have upper case UA and when I edit in the 'other ids' screen it won't save my change.

@dustymc do you see anything wrong with this collection of records that would be causing me such problems? Thank you for any help you or others might provide.

**Comment by AJLinn** [comment]
And BTW, it seems to not be a local problem as I've tried in Chrome, Safari, and Firefox, on wifi or ethernet, and on a different computer and the same thing is happening.

If it's a problem associated with the media column, this is an issue that should be looked at as this is an important / essential column for our collection to use.

**Comment by dustymc** [comment]
I'm not seeing anything like that in the logs.

The initial query is expensive, paging is (almost) irrelevant as far as database performance goes.

Assuming I'm understanding this, a search for...

<img width="272" alt="Screen Shot 2019-12-18 at 12 31 38 PM" src="https://user-images.githubusercontent.com/5720791/71121007-64e6a380-2192-11ea-8957-ca2f2034944b.png">

loads and renders in about 3 seconds for me.

Wild guess: There are around 800 Media thumbnails in there, they're all reasonable sized (<~5K), but that's still eating your browser. That SHOULD only happen after the text stuff has loaded, but that's really up to your environment. Is everything happy when you set the page size to the smallest available value?

I can dig deeper if you'll provide the information requested in the issue template - https://github.com/ArctosDB/arctos/issues/new?assignees=&labels=&template=bug_report.md&title=

**Comment by AJLinn** [comment]
> Is everything happy when you set the page size to the smallest available value?

Not sure what that means? Drop the magnification of the page? Doesn't seem to matter.

Just got this doing a record search using Accession
![Screen Shot 2019-12-18 at 11 49 35 AM](https://user-images.githubusercontent.com/17605945/71122211-86449100-218c-11ea-9745-a6d2b9f99a3d.png)

Using Chrome Version 79.0.3945.79 (Official Build) (64-bit)

Turning off the media column for search results certainly does make things work happier. BUT the fact is I often need the media column when working with these collections in order to do the tasks I'm doing (like easily figuring out which records still need photos uploaded).

**Comment by AJLinn** [comment]
**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac OS 10.14.5
 - Browser [e.g. chrome, safari] Google Chrome
 - Version [e.g. 22]  79.0.3945.88 (Official Build) (64-bit)

> Wild guess: There are around 800 Media thumbnails in there, they're all reasonable sized (<~5K), but that's still eating your browser. That SHOULD only happen after the text stuff has loaded, but that's really up to your environment. Is everything happy when you set the page size to the smallest available value?

The collection loads in seconds without the media column on. I understand that this creates a processing problem when there are so many thumbnails... what can I do to fix that? Can we have only one thumbnail display in the search results? Being able to have the media column turned on for search results is quite possibly the second most important column for us so I'd really like to figure this out. Could there be a box to check in the media details page to select that one photo to be seen in the search results instead of all of the media files? Some of my records have over 10 media files (usually photos) and I certainly don't need to be able to see all those at the search results page.

**Comment by dustymc** [comment]
>what that means?

Bottom of the table

<img width="425" alt="Screen Shot 2019-12-18 at 1 01 08 PM" src="https://user-images.githubusercontent.com/5720791/71122952-834e9e00-2196-11ea-8a1a-92e26dc849b2.png">

That error strongly suggests that your browser/machine/etc. is in fact running out of resources. Chrome is apparently doing something wonky with the order of processing, but that's not much surprise. https://arctosdb.org/faq/

I don't really have a great solution to offer. We could not show thumbnails, or require better-optimized thumbnails (which would probably affect quality at this point), or ??????????????, but the root of the issue seems to be requesting more data than your machine can process. There are lots of libraries that do things like only request the images when they'd be visible and destroy them when they're not, but those have other costs.

I don't see any realistic way to implement showing a pre-chosen thumbnail.

I could potentially not process the JSON into thumbs until the user requests it, but that would be pretty annoying to most users most of the time. Eg my laptop happily loads all ~800 thumbs.

I think the best solution is to somehow recommend small page sizes for machines with limited resources when Media is turned on. Not a clue how we'd do that either....

**Comment by Jegelewicz** [comment]
> Can we have only one thumbnail display in the search results? Being able to have the media column turned on for search results is quite possibly the second most important column for us so I'd really like to figure this out. 

When a cataloged item has media, that is presented in the GUID column:
![image](https://user-images.githubusercontent.com/5725767/71128217-f8779e80-21a9-11ea-8b30-2d8544f4d24d.png)

So you can turn off the media column, but still know whether there is media or not which will help with

> (like easily figuring out which records still need photos uploaded).

> Could there be a box to check in the media details page to select that one photo to be seen in the search results instead of all of the media files?

This seems like a reasonable enough solution if instead, you could check something from the search that limits media presented to just one thumbnail AND you don't expect any particular photo to show up in the results. Would that help with the resource issue @dustymc ?

**Comment by dustymc** [comment]
>Would that help with the resource issue

Hard to say. If you're doing this on your watch, have 5000 rows on, and all of the thumbnails are as big as they can be (http://handbook.arctosdb.org/documentation/media.html#media-creation-guidelines), then no, that's very likely still plenty of data to eat all of your memory. If whatever you're doing just BARELY eats your browser now and involves multiple thumbs, then maybe....

>don't expect any particular photo 

I REALLY dislike  "... and then something random happened!"

**Comment by AJLinn** [comment]
> I think the best solution is to somehow recommend small page sizes for machines with limited resources when Media is turned on. Not a clue how we'd do that either....

Got it. I will go forward with that in mind, choosing 10 rows rather than 250 and see if my admittedly very old iMac (late 2012 2.7 GHz i5 machine with 8GB 1600 MHz DDR3) is happier.
Thanks for thinking about possible solutions.
