### ISSUE TITLE
Can't change catalog number value

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#2420]
**Describe the bug**
I am trying to fix a catalog number that inadvertently has a lower case "UA" instead of capital (http://arctos.database.museum/guid/UAM:EH:uA2018-012-0080) and my edit won't save.

**To Reproduce**
1. Go to http://arctos.database.museum/guid/UAM:EH:uA2018-012-0080
2. Click on "Other IDs"
3. Edit UAM:EH catalog number so reads: UA2018-012-0080
4. Click "Save Changes"
5. See no change get saved. :-(

**Expected behavior**
This how I always fix catalog numbers that are wrong and I've never had a change not save.

**Screenshots**
![Screen Shot 2019-12-18 at 1 58 15 PM](https://user-images.githubusercontent.com/17605945/71130592-c14fc000-219e-11ea-910e-46e3c32153af.png)

**Desktop (please complete the following information):**
 - OS: OS 10.14.5
 - Browser: Chrome
 - Version: Version 79.0.3945.88 (Official Build) (64-bit)

**Priority**
Regular - the catalog record will not sort properly because of this inconsistency. But it's not going to break anything any time soon.
![Screen Shot 2019-12-18 at 2 02 49 PM](https://user-images.githubusercontent.com/17605945/71130704-1a1f5880-219f-11ea-8025-dfecda807d6c.png)

**Comment by dustymc** [comment]
CF's compare is case-insensitive - it's not smart enough to know you've changed anything. You could change it to something random and then back to whatever it should be, or ...

```
UAM@ARCTOS> update cataloged_item set cat_num='UA2018-012-0080' where cat_num='uA2018-012-0080';

1 row updated.
```

I think lucee will handle this properly.

**Comment by AJLinn** [comment]
> CF's compare is case-insensitive - it's not smart enough to know you've changed anything. You could change it to something random and then back to whatever it should be, or ...

YES! That worked. Thanks - good trick to know about!
