### ISSUE TITLE
UI not handling quotes when links added in Geography remarks

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2422]
>    60 characters
>>GEOG_REMARK								    VARCHAR2(4000)
>??

When I put this: "<a target="_blank" class="external" href="https://ngmdb.usgs.gov/ht-bin/tv_browse.pl?id=10dfd8129c815a34b05169c401e59731">USGS Topo Map</a>" in the remark. I get this:

![image](https://user-images.githubusercontent.com/5725767/71197815-a9844480-224f-11ea-829a-cddbfcfcc10c.png)

and after I save. The remark looks like this:

![image](https://user-images.githubusercontent.com/5725767/71197860-c4ef4f80-224f-11ea-8ebe-05de7f4aaa67.png)

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/data-migration/issues/130#issuecomment-567599687_

**Comment by Jegelewicz** [comment]
Also in Geology description.
![image](https://user-images.githubusercontent.com/5725767/72207055-20c58680-3452-11ea-95ba-075f91f768e0.png)

**Comment by Jegelewicz** [comment]
Can this get done before PG?

**Comment by dustymc** [comment]
Needs done as part of https://github.com/ArctosDB/arctos/issues/2916
