### ISSUE TITLE
Inconsistency in "ammonites"

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2424]
UAM has ammonites cataloged with the part name "exoskeleton" and DMNS has used "shell (fossil)".

As I am about to migrate in a bunch from NMMNH, I'd like to see if we can make a recommendation and perhaps more consistent use across Arctos. What does everyone prefer?

@Nicole-Ridgwell-NMMNHS @dperriguey @sharpphyl

**Comment by dperriguey** [comment]
Exoskeleton is very specific. However, it is also a shell in this case. It would be scientifically more accurate to call it exoskeleton (maybe), but shell is also accurate and used in the literature just as much if not more. I am only really concerned for when we didn't have trace fossil as a part name. Even in our collection we need to go back and fix a lot of these. If I knew there was an exoskeleton option, I would have used that instead of shell (fossil).

**Comment by Jegelewicz** [comment]
@dperriguey that is super-easy to change using the modify parts tool in search results!

**Comment by dperriguey** [comment]
Cool! That will be helpful. Just have to go through everything and make sure it is what we say it is. 

I think having both of them is redundant. The cool thing about shell (fossil) is that it indicates that it is not a modern exoskeleton.

**Comment by Jegelewicz** [comment]
> indicates that it is not a modern exoskeleton

This is probably a whole other issue. Invert collections will use "shell (fossil)" for any empty shell found lying around in a place that might be other than where the animal was living (aka from "float" or "drift"). So, not necessarily from a "not modern" or "not extant" species!

**Comment by dperriguey** [comment]
That's horrible.

**Comment by Jegelewicz** [comment]
I'm leaning toward using "shell (fossil)" for now just to keep some consistency with DMNS. Also, I think most everyone associates "shell" with ammonites and "exoskeleton" with insects, crabs and the like.

**Comment by dperriguey** [comment]
But that's still kind of like the polyphyletic grouping of invertebrates. What makes a chitinous exoskeleton any more of an exoskeleton than calcite? I definitely won't (as a personal choice) say that a cockroach has a shell though, haha. So in my opinion, either is correct. Maybe a merger between the two is actually more appropriate: exoskeleton/shell.

**Comment by Jegelewicz** [comment]
The more I work with fossils, the more I think we need relationships between part names so that if someone searches for "exoskeleton" Arctos can understand that they may also want "shell" and make an appropriate suggestion. As for 

> polyphyletic grouping of invertebrates

the part name has nothing to do with that! Taxonomy is where those decisions are made (not that taxonomy is any better at it...)

**Comment by Jegelewicz** [comment]
FWIW, the Wiki on exoskeleton calls insect exoskeletons "true" exoskeletons...and honestly, I'm pretty sure no one goes "exoskeletoning" when visiting the beach. :-)

**Comment by Jegelewicz** [comment]
Don't even get me started on turtle "shell"....

**Comment by dustymc** [comment]
Consistent->good
Inconsistent-->bad

I don't know where the split should be, or if there should be one, but it should be very clearly defined; users should have a way to find what they want. The data strongly suggests that's not currently the case.

Can't say I love "crunchier than a cockroach" for a definition...

>relationships between part names 

Maybe...

>may also want 

... but not to mask our sloppy use of terminology. If there's some difference between two parts it should be spelled out somewhere, and if there's not we shouldn't have them both.

>"shell (fossil)" for any empty shell found lying around in a place that might be other than where the animal was living

Oh my!

```

select 
	phylum,
	guid_prefix,
	count(*) c
from
	collection,
	flat,
	specimen_part
where
	flat.collection_object_id=specimen_part.derived_from_cat_item and
	flat.collection_id=collection.collection_id and
	part_name like 'shell%'
group by 
	phylum,
	guid_prefix
order by 
	phylum,
	guid_prefix
;
PHYLUM			       GUID_PREFIX	      C
------------------------------ --------------- --------
Annelida		       CHAS:Teach	      1
Annelida		       DMNS:Inv 	      5
Annelida		       UNM:ES		     11
Arthropoda		       DMNS:Inv 	      4
Arthropoda		       UAM:Inv		      4
Arthropoda		       UNM:ES		      7
Arthropoda		       UTEP:Inv 	     22
Brachiopoda		       DMNS:Inv 	      7
Brachiopoda		       OWU:ES		      2
Brachiopoda		       UNM:ES		      7
Bryozoa, Mollusca	       DMNS:Inv 	      1
Chordata		       ALMNH:ES 	    184
Chordata		       OWU:ES		      1
Cnidaria		       DMNS:Inv 	      1
Cnidaria		       OWU:ES		      1
Cnidaria		       UNM:ES		     10
Cnidaria, Mollusca	       DMNS:Inv 	      2
Echinodermata		       ALMNH:ES 	      1
Echinodermata		       DMNS:Inv 	      6
Echinodermata		       UNM:ES		     43
Echinodermata, Mollusca        DMNS:Inv 	      1
Foraminifera		       DMNS:Inv 	      9
Mollusca		       ALMNH:ES 	     20
Mollusca		       CHAS:Inv 	     93
Mollusca		       CHAS:Teach	     68
Mollusca		       DMNS:Inv 	  29198
Mollusca		       KNWR:Inv 	      3
Mollusca		       MSB:Host 	     36
Mollusca		       OWU:ES		      6
Mollusca		       UAM:ES		      5
Mollusca		       UAM:Inv		      4
Mollusca		       UNM:ES		   1327
Mollusca		       UTEP:ES		      7
Mollusca		       UTEP:Inv 	  11516
Porifera		       UNM:ES		      1
Porifera, Mollusca	       UNM:ES		      3
Sarcomastigophora	       UTEP:Inv 	      1
Tracheophyta		       UNM:ES		      1
			       ALMNH:ES 	     41
			       DMNS:Inv 	      5
			       MSB:Host 	      2
			       OWU:ES		     53
			       UAM:ES		      4
			       UAM:Inv		      4
			       UNM:ES		     83
			       UTEP:ES		      1
			       UTEP:Inv 	    154

47 rows selected.



select 
	phylum,
	guid_prefix,
	count(*) c
from
	collection,
	flat,
	specimen_part
where
	flat.collection_object_id=specimen_part.derived_from_cat_item and
	flat.collection_id=collection.collection_id and
	part_name like 'exoskeleton%'
group by 
	phylum,
	guid_prefix
order by 
	phylum,
	guid_prefix
;
PHYLUM			       GUID_PREFIX	      C
------------------------------ --------------- --------
Annelida		       UAM:ES		      7
Arthropoda		       CHAS:Teach	      4
Arthropoda		       DMNS:Inv 	      5
Arthropoda		       OWU:ES		      2
Arthropoda		       UAM:ES		    148
Brachiopoda		       UAM:ES		    906
Bryozoa 		       UAM:ES		     65
Chordata		       UAM:ES		     15
Cnidaria		       DMNS:Inv 	     11
Cnidaria		       UAM:ES		    496
Coelenterata		       UAM:ES		     10
Echinodermata		       DMNS:Inv 	      5
Echinodermata		       UAM:ES		    177
Mollusca		       DMNS:Inv 	      1
Mollusca		       UAM:ES		   4094
Mollusca		       UTEP:ES		      2
Porifera		       DMNS:Inv 	      9
Porifera		       UAM:ES		    305
Sarcomastigophora	       UAM:ES		     19
			       OWU:ES		     66
			       UAM:ES		    793

```

**Comment by Jegelewicz** [comment]
I think that proves this is a problem, I'm just not sure how to resolve it. This will be a great example for our [SPNHC workshop](https://github.com/ArctosDB/SPNHC/projects/4) though!

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
My preference is shell. If shell is used for other modern mollusks, it does not make sense to use exoskeleton for ammonites.

**Comment by dperriguey** [comment]
I have the same preference as well, but it seems that there are others with different preferences that are not technically wrong. Depending on what dictionary you use, you can argue either way. However, if you think about how the outer structure of an arthropod (crustacean) forms, there are variable amounts of calcium carbonate used to enhances the strength of their skeleton. Mollusks use protein and chitin as a base layer for the subsequent layers of minerals to form their exoskeleton. So, there are some differences and similarities, compositionally and in formation, but exoskeletons/shells serve the same basic function in both arthropods and mollusks. The fact is that some organisms have skeletons, some are inside (endo), and some outside (exo). I can argue either way. They should just both come up through a search and let the user know what else was included based on their selection, or a question should pop up asking the user if they want to enhance their search using either word, if they so choose.

**Comment by Jegelewicz** [comment]
> They should just both come up through a search and let the user know what else was included based on their selection, or a question should pop up asking the user if they want to enhance their search using either word, if they so choose.

Yep, we are going to need to be more flexible - this will definitely be an after PG conversation.

**Comment by dustymc** [comment]
>They should just both come up 

I think there are two ways we can solve this.

1) Normalize, standardize, and define. This is a matter of deciding to do so and making some simple updates.
2) Magic.

We might make some progress towards (2) by creating some sort of cross-link capability, and doing so might make some sense in some contexts (eg, returning 'whole organism' vertebrates on a search for 'rib'), but I'm not seeing a need here, and I think there's about zero chance that even a wildly successful attempt to resolve our arbitrary data would help users in eg GBIF find Arctos data. 

This is a very simple problem with a very simple solution.

**Comment by Jegelewicz** [comment]
> This is a very simple problem with a very simple solution.

Except - humans....

**Comment by dustymc** [comment]
>humans

There are two parts to that.

1) We as a community (or maybe a sub-community; this seems within the purview of the AWG) can decide to be unambiguous with our authority data. 

2) Given unambiguous authority data, we might do more with making sure it's used correctly. "Ammonites don't generally have feathers, are you really sure about this?" becomes possible once our authorities are clear, but not while we're giving different names to the same THING.

https://github.com/ArctosDB/arctos/issues/1450

**Comment by sharpphyl** [comment]
I've been watching this thread and we'll continue to use "shell" for Nautilus specimens (a relative of the Ammonites) and "shell (fossil)" for Ammonites.  

I appreciate seeing Dusty's list of names used.  It helped me catch some part name errors.

**Comment by Jegelewicz** [comment]
I fixed the UTEP:ES shells - not sure where to go with this from here , but it seems like it is part of #3708

**Comment by Jegelewicz** [comment]
Seems like all "Mollusca" exoskeletons should be changed to shell?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
That would be my preference, but looks like we should check with at least UAM:ES first.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Are there any other invert folks we should tag to look at this issue?

**Comment by Jegelewicz** [comment]
Probably need to run the sql again, but when I tried I got

> ERROR: column reference "guid_prefix" is ambiguous Position: 21

@dustymc new sql please?

**Comment by dustymc** [comment]
```
select 
    phylum,
    guid_prefix,
    count(*) c
from
    flat
    inner join specimen_part on flat.collection_object_id=specimen_part.derived_from_cat_item 
where
    part_name like 'shell%'
group by 
    phylum,
    guid_prefix
order by 
    phylum,
    guid_prefix
```

**Comment by Jegelewicz** [comment]
Here is new "exoskeleton" list

<html><body>


  | phylum | guid_prefix | c
-- | -- | -- | --
1 | Annelida | UAM:ES | 7
2 | Arthropoda | CHAS:Teach | 4
3 | Arthropoda | DMNS:Inv | 5
4 | Arthropoda | NMMNH:Paleo | 13
5 | Arthropoda | OWU:ES | 2
6 | Arthropoda | UAM:ES | 148
7 | Brachiopoda | NMMNH:Paleo | 1
8 | Brachiopoda | UAM:ES | 906
9 | Bryozoa | NMMNH:Paleo | 100
10 | Bryozoa | UAM:ES | 65
11 | Chordata | NMMNH:Paleo | 2
12 | Chordata | UAM:ES | 16
13 | Cnidaria | DMNS:Inv | 148
14 | Cnidaria | NMMNH:Paleo | 2
15 | Cnidaria | UAM:ES | 496
16 | Coelenterata | UAM:ES | 10
17 | Echinodermata | CHAS:Inv | 1
18 | Echinodermata | DMNS:Inv | 4
19 | Echinodermata | OWU:ES | 1
20 | Echinodermata | UAM:ES | 177
21 | Mollusca | DMNS:Inv | 1
22 | Mollusca | UAM:ES | 3966
23 | Mollusca; Cnidaria | DMNS:Inv | 2
24 | Mollusca; Mollusca | UAM:ES | 128
25 | Porifera | DMNS:Inv | 9
26 | Porifera | NMMNH:Paleo | 1
27 | Porifera | UAM:ES | 305
28 | Rhodophyta | NMMNH:Paleo | 11
29 | Sarcomastigophora | UAM:ES | 19
30 | Tracheophyta | NMMNH:Paleo | 1
31 |   | NMMNH:Paleo | 48
32 |   | OWU:ES | 66
33 |   | UAM:ES | 792


</body>
</html>

@sharpphyl is that one DMNS record correct?

**Comment by sharpphyl** [comment]
> @sharpphyl is that one DMNS record correct?

Nope.  A typo that I just corrected.  Good catch.

**Comment by Jegelewicz** [comment]
@DerekSikes we need a contact at UAM to agree to change all Mollusca "exoskeleton" parts to "shell". I'd love to clear this up and close this issue.

**Comment by Jegelewicz** [comment]
Suggest the following updates to term definitions:

**exoskeleton**

current - The external skeleton that supports and protects an animal's body, in contrast to the internal skeleton (endoskeleton) of, for example, a human. In usage, some of the larger kinds of exoskeletons are known as "shells". [Wikipedia](https://en.wikipedia.org/wiki/Exoskeleton)

updated - The external skeleton that supports and protects an animal's body, in contrast to the internal skeleton (endoskeleton) of, for example, a human. In Arctos, exoskeletons of the phylum Mollusca are referred to as "shell", for all other phyla use "exoskeleton". [Wikipedia](https://en.wikipedia.org/wiki/Exoskeleton)

**shell**

current - For invertebrates, typically a calcareous exoskeleton which encloses, supports and protects the soft parts of an animal in the phylum Mollusca, which includes snails, clams, tusk shells, and several other classes. [Wikipedia](https://en.wikipedia.org/wiki/Mollusc_shell)

updated - For invertebrates, typically a calcareous exoskeleton which encloses, supports and protects the soft parts of an animal in the phylum Mollusca, which includes snails, clams, tusk shells, and several other classes. In Arctos for phyla other than Mollusca, the appropriate part name is exoskeleton. [Wikipedia](https://en.wikipedia.org/wiki/Mollusc_shell)

Feel free to make these better!

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
snails, clams, **cephalopods**, tusk shells, and several other classes

explicitly adding them in since ammonites are so common in paleo collections. Otherwise I'm happy with the definitions.

**Comment by dustymc** [comment]
Done?

**Comment by Jegelewicz** [comment]
Nope - will bring up in Code table Working hour.

**Comment by Jegelewicz** [comment]
Suggest the following updates to term definitions:

**exoskeleton**

current - The external skeleton that supports and protects an animal's body, in contrast to the internal skeleton (endoskeleton) of, for example, a human. In usage, some of the larger kinds of exoskeletons are known as "shells". [Wikipedia](https://en.wikipedia.org/wiki/Exoskeleton)

updated - The external skeleton that supports and protects an animal's body, in contrast to the internal skeleton (endoskeleton) of, for example, a human. In Arctos, exoskeletons of the phylum Mollusca are referred to as "shell", for all other phyla use "exoskeleton". [Wikipedia](https://en.wikipedia.org/wiki/Exoskeleton)

**shell**

current - For invertebrates, typically a calcareous exoskeleton which encloses, supports and protects the soft parts of an animal in the phylum Mollusca, which includes snails, clams, tusk shells, and several other classes. [Wikipedia](https://en.wikipedia.org/wiki/Mollusc_shell)

updated - For invertebrates, typically a calcareous exoskeleton which encloses, supports and protects the soft parts of an animal in the phylum Mollusca, which includes snails, clams, cephalopods, tusk shells, and several other classes. In Arctos for phyla other than Mollusca, the appropriate part name is exoskeleton. [Wikipedia](https://en.wikipedia.org/wiki/Mollusc_shell)

Feel free to make these better!

**Comment by Jegelewicz** [comment]
Code table update is complete - do we need to update UAM stuff still.

**Comment by Jegelewicz** [comment]
As we seem to have no contact at UAM, I am closing this. there is no action for the community to take at this time.
