### ISSUE TITLE
New part name - corralum

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2425]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=CTSPECIMEN_PART_NAME

**Value**
corallum

**Definition**
the skeleton of a coral, composed of individual corallites.

**Collection type**
ES, Inv

**Attribute data type**
free-text, categorical, number+units

**Attribute value**
For categorical attributes, code table controlling value

**Attribute units**
For number+units attributes, code table controlling units

**Part tissue flag**
no

**Other ID BaseURL**
For OtherIDs, URL with which to prepend value (resolvable identifiers only)

**Context**
Describe why this new value is necessary and existing values are not.

**Priority**
Please assign a priority-label.

**Comment by dperriguey** [comment]
Just discovered this same problem. 
I need this too!
However, the definition needs to extend to solitary corals. It is still called a corallum for solitary corals, as well.  

https://www.digitalatlasofancientlife.org/learn/cnidaria/anthozoa/rugosa/

**Comment by Jegelewicz** [comment]
> A solitary coral individual is called a corallum (plural = coralla), while an individual within a colony is called a corallite.

Added to code table.

**Comment by dperriguey** [comment]
I think that's misspelled:
![image](https://user-images.githubusercontent.com/32556913/71856351-dedac000-30a0-11ea-9451-11d2a8e6a72d.png)

**Comment by Jegelewicz** [comment]
Dang it! That's what I had in the issue and I didn't notice the different spelling in the paper you sent.
I added the correct spelling, but I can't delete the incorrect one. When I try to remove the collections from it I get a message "Please select an item in the list". @dustymc please help.

![image](https://user-images.githubusercontent.com/5725767/71859272-8b21a400-30ab-11ea-91e3-5a8a357d9742.png)

**Comment by dustymc** [comment]
SQL> delete from ctspecimen_part_name where part_name='corralum';

fixed in PG
