### ISSUE TITLE
Arctos records with event dates in the future

### ISSUE THREAD

**Issue by jhpoelen** [ArctosDB/arctos#2426]
Hi! 

In improving GloBI's record validation methods (see https://github.com/globalbioticinteractions/elton/issues/11), I stumbled across the suspicious event dates in following records: 

$ cat validation.tsv | grep "is in the future" | cut -f2,3 | sort | uniq
date [8888-01-22T00:00:00Z] is in the future	http://arctos.database.museum/guid/MSB:Bird:25342
date [8888-02-26T00:00:00Z] is in the future	http://arctos.database.museum/guid/MSB:Bird:26700
date [8888-03-08T00:00:00Z] is in the future	http://arctos.database.museum/guid/MSB:Bird:26739
date [8888-03-15T00:00:00Z] is in the future	http://arctos.database.museum/guid/MSB:Bird:25358
date [8888-03-18T00:00:00Z] is in the future	http://arctos.database.museum/guid/MSB:Bird:26688
date [8888-03-22T00:00:00Z] is in the future	http://arctos.database.museum/guid/MSB:Bird:25337
date [8888-03-25T00:00:00Z] is in the future	http://arctos.database.museum/guid/MSB:Bird:24284
date [8888-03-25T00:00:00Z] is in the future	http://arctos.database.museum/guid/MSB:Bird:24348
date [8888-03-25T00:00:00Z] is in the future	http://arctos.database.museum/guid/MSB:Bird:24425
date [8888-04-06T00:00:00Z] is in the future	http://arctos.database.museum/guid/MSB:Bird:24264
date [8888-04-06T00:00:00Z] is in the future	http://arctos.database.museum/guid/MSB:Bird:24279
date [8888-04-12T00:00:00Z] is in the future	http://arctos.database.museum/guid/MSB:Bird:24278
date [8888-04-12T00:00:00Z] is in the future	http://arctos.database.museum/guid/MSB:Bird:24280
date [8888-04-12T00:00:00Z] is in the future	http://arctos.database.museum/guid/MSB:Bird:24281
date [8888-04-12T00:00:00Z] is in the future	http://arctos.database.museum/guid/MSB:Bird:24283
date [8888-04-12T00:00:00Z] is in the future	http://arctos.database.museum/guid/MSB:Bird:24347
date [8888-04-12T00:00:00Z] is in the future	http://arctos.database.museum/guid/MSB:Bird:24671
date [8888-04-12T00:00:00Z] is in the future	http://arctos.database.museum/guid/MSB:Bird:24873
date [8888-04-12T00:00:00Z] is in the future	http://arctos.database.museum/guid/MSB:Bird:24874
date [8888-04-12T00:00:00Z] is in the future	http://arctos.database.museum/guid/MSB:Bird:25170
date [8888-04-12T00:00:00Z] is in the future	http://arctos.database.museum/guid/MSB:Bird:25171
date [8888-04-20T00:00:00Z] is in the future	http://arctos.database.museum/guid/MSB:Bird:25288
date [8888-04-20T00:00:00Z] is in the future	http://arctos.database.museum/guid/MSB:Bird:25289
date [8888-05-21T00:00:00Z] is in the future	http://arctos.database.museum/guid/MSB:Bird:26803
date [8888-06-08T00:00:00Z] is in the future	http://arctos.database.museum/guid/MSB:Bird:25280
date [8888-08-18T00:00:00Z] is in the future	http://arctos.database.museum/guid/MSB:Bird:26329
date [8888-09-09T00:00:00Z] is in the future	http://arctos.database.museum/guid/MSB:Bird:24771
date [8888-09-09T00:00:00Z] is in the future	http://arctos.database.museum/guid/MSB:Bird:24772
date [8888-09-15T00:00:00Z] is in the future	http://arctos.database.museum/guid/MSB:Bird:24833
date [8888-11-03T00:00:00Z] is in the future	http://arctos.database.museum/guid/MSB:Bird:26611

A quick glance at a single record http://arctos.database.museum/guid/MSB:Bird:24264 (see screenshot attached) support that the event dates have not been completely transcribed. 

![Screenshot from 2019-12-20 06-54-40](https://user-images.githubusercontent.com/1084872/71262912-a9d71b00-22f5-11ea-8ad4-34352eb6705d.png)

**Comment by dustymc** [comment]
http://handbook.arctosdb.org/documentation/dates.html#restricted-data

**Comment by jhpoelen** [comment]
@dustymc thanks for pointing our that year "8888" has a special meaning (aka a [magic number](https://en.wikipedia.org/wiki/Magic_number_(programming)#Unnamed_numerical_constants)) 

From the example I shared, I don't understand why the date would be restricted: the verbatim date clearly documents the year.

**Comment by jhpoelen** [comment]
I've updated the validation message for the 8888 years to be:

```
date [8888-11-03T00:00:00Z] appears to be restricted, see http://handbook.arctosdb.org/documentation/dates.html#restricted-data
```

**Comment by dustymc** [comment]
Yea nothing about those encumbrances make sense, I just write the code and try not to think about it...

I am not fond of that convention and up for better ideas, but it does

- fit in an ISO8601 datatype model
- fall far enough outside 'normal' for most people to notice, probably, we hope....

FYI and while we're on the subject, we do have data with second-precision (and year, going the other way) - I think your zero-padding is adding precision that doesn't exist.

**Comment by jhpoelen** [comment]
I do appreciate pragmatism and thanks for your date precision comment. Please see https://github.com/globalbioticinteractions/globalbioticinteractions/issues/439 .
