### ISSUE TITLE
 record cannot be accessed: http://arctos.database.museum/guid/DMNS:Para:46006 but is linked by http://arctos.database.museum/guid/DMNS:Para:1375 

### ISSUE THREAD

**Issue by jhpoelen** [ArctosDB/arctos#2428]
According to a GloBI report, http://arctos.database.museum/guid/DMNS:Para:46006 is linked by http://arctos.database.museum/guid/DMNS:Para:1375 but cannot be accessed for some reason.

This prevents DMNS:Para:1375 from being indexed by GloBI.

Am noticing other Arctos record links with 404s, so I am wondering: are there access restrictions for some linked records?

![Screenshot from 2019-12-20 11-20-30](https://user-images.githubusercontent.com/1084872/71285746-ccc7f600-231a-11ea-8aa7-af7cca921b31.png)

![Screenshot from 2019-12-20 11-21-18](https://user-images.githubusercontent.com/1084872/71285775-e2d5b680-231a-11ea-9773-96e5d34c47b5.png)

**Comment by dustymc** [comment]
There are fully restricted records, but this isn't one of them.

```
UAM@ARCTOS> select * from flat where guid='DMNS:Para:46006';

no rows selected

```

I'd guess it's just another typo.

https://github.com/ArctosDB/arctos/issues/2278 still complicates things, and https://github.com/ArctosDB/arctos/issues/1725 discusses encumbered records in the context of linked data.

@jrdemboski

**Comment by Jegelewicz** [comment]
It is also possible that DMNS:Para:46006 has not yet been cataloged even though the linked host has been.

**Comment by dustymc** [comment]
Normally yes, and that's a bit part of why the model works as it does, but this is a new collection with around a thousand items cataloged.

**Comment by Jegelewicz** [comment]
Also, it seems VERY suspicious that a parasite is a parasite of a parasite....

**Comment by jhpoelen** [comment]
Perhaps a hyper-parasite? 

Also, a question that comes up for me is: how to best (and systematically/automatically) document suspicious or unexpected links?

**Comment by Jegelewicz** [comment]
> how to best (and systematically/automatically) document suspicious or unexpected links?

If you only mean Arctos stuff, then posting an issue in our GitHub is great! If you mean all suspicious links, then maybe a "questionable link" marker or a page that lists them all?

**Comment by dustymc** [comment]
It's parasites all the way down....

For now, if you want to email me something I can get into..


```

UAM@ARCTOS> desc annotations;
 Name								   Null?    Type
 ----------------------------------------------------------------- -------- --------------------------------------------
 ANNOTATION_ID							   NOT NULL NUMBER
 ANNOTATE_DATE							   NOT NULL DATE
 CF_USERNAME								    VARCHAR2(255)
 COLLECTION_OBJECT_ID							    NUMBER
 TAXON_NAME_ID								    NUMBER
 PROJECT_ID								    NUMBER
 PUBLICATION_ID 							    NUMBER
 ANNOTATION							   NOT NULL VARCHAR2(4000)
 REVIEWER_AGENT_ID							    NUMBER
 REVIEWED_FG							   NOT NULL NUMBER(1)
 REVIEWER_COMMENT							    VARCHAR2(255)
 ANNOTATION_GROUP_ID						   NOT NULL NUMBER
 EMAIL									    VARCHAR2(255)
 MEDIA_ID								    NUMBER
```
 ...that - basically just something I can use to find a specimen and a remark is sufficient  - I'll SQL it in, and it'll become a visible and permanent part of the catalog record.

Going forward, we can discuss throwing up an Annotation API.

**Comment by campmlc** [comment]
This appears to have been fixed. The DMNS:Para:46006 link has been changed to DMNS:Bird:46006, so a typo. Can we close the issue?

**Comment by jhpoelen** [comment]
Thanks for addressing the typo! Closing issue.

Please see https://github.com/ArctosDB/arctos/issues/2427 for similar suspicious links. Note that the GloBI Review Report for Arctos records can be accessed / regenerated using https://travis-ci.org/globalbioticinteractions/vertnet .
