### ISSUE TITLE
WKTs for Canadian provinces?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2430]
I have a request for WKTs for Novia Scotia and other Canadian provinces. Have we decided to use these as specific locality if there is nothing for locality except higher geography?

**Comment by mkoo** [comment]
working on these but ran into issue of many many islands for some Provinces making the files quite large (e.g., BC is 19MB which is ridiculous for a wkt)! work in progress....

**Comment by dustymc** [comment]
WKTs are just a spatial component of geography; http://handbook.arctosdb.org/documentation/locality.html and http://handbook.arctosdb.org/documentation/higher-geography#guidelines-for-assigning-geography-to-specimens remain correct.

**Comment by mkoo** [comment]
Update: GIS assistant is simplifying borders of BC, NS, Nunavut etc to include all small coastal islands and land masses. I can send/post maps for review if you would like @campmlc  

Landlocked provinces are complete and will be uploaded soon.

**Comment by campmlc** [comment]
Thanks, @Michelle Koo <mkoo@berkeley.edu> . Let me know when these are
ready to use.

**Comment by dustymc** [comment]
Done?
