### ISSUE TITLE
Need Permissions for new ALMNH Paleo Curator

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/arctos#2431]
** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **

** Outages should be reported to the contacts listed at https://arctosdb.org/arctos-down/ **

** Arctos Documentation is http://handbook.arctosdb.org/ **

** Learn more about Arctos at https://arctosdb.org/ **

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **

**Comment by mbprondzinski** [comment]
Adiel is requesting a loan to take specimens to a Paleo Society Meeting in Birmingham.  He is an agent, but he has no permissions.  I want him to be able to create his own loans.

Thanks!

**Comment by campmlc** [comment]
Hi Mary Beth, what is his agent name? Has he had any Arctos training yet?

**Comment by mbprondzinski** [comment]
Hi Mariel,

Adiel Klompmaker is the agent name.  He hasn’t had any real Arctos training because I was going to show him how to create an in-house loan before he took the specimens to Bham.  I thought that would be simple enough to start with.  I can’t get people here to do their homework, I’m afraid, but I sure as heck don’t want to be doing everything for them, as I am already up to my neck with too much to do.

I think he has looked at Git-hub, but we haven’t sat down and talked about it either.

Thanks, Mariel

**Comment by campmlc** [comment]
He needs to get set up as an operator, with some basic information provided
so he understands his permissions and how his actions might affect others.
Do you want to do that, or do you want to set up a call so we can go over
the process together?

**Comment by mbprondzinski** [comment]
Hi Mariel,

Why don’t we set up a call?  Adiel will be back tomorrow.  If you are available then, we can set a time.  I will be available from 8:00 to 4:00 pm Central Standard time.

I would like him to be there with me when we do this, is that okay?  Just let me know when you are available.

Thanks!
Mary Beth

**Comment by campmlc** [comment]
I'm pretty flexible. How about sometime after 11 am your time?

**Comment by mbprondzinski** [comment]
Okay, sounds good.  Call me here at 205-348-5625 at 11:15 my time.  I will have Adiel in here with me and put you on speaker phone.

Thanks, and talk with you tomorrow!

MB

**Comment by campmlc** [comment]
Ok, talk to you soon.

**Comment by dustymc** [comment]
Sounds like a great opportunity for a (video?) how-to!

**Comment by mbprondzinski** [comment]
How would you suggest this be videoed?  On my end?  Recorded from speaker phone with videos of the computer screen?  Not really sure how to do this, Dusty.

**Comment by mbprondzinski** [comment]
Hi Mariel,

Did you forget about us here at ALMNH?  We had a fire alarm at 11:00 am but we were back in the office around 11:20.

Let me know when you are available…

MB

**Comment by Jegelewicz** [comment]
> How would you suggest this be videoed? On my end? Recorded from speaker phone with videos of the computer screen? Not really sure how to do this, Dusty.

We can record Zoom meetings, if we get the permissions set up ahead of time. Did you guys meet up?

**Comment by campmlc** [comment]
Yes, we did the call. I suggested the Zoom meeting for next time. Do we
have a sign up mechanism for Zoom?

**Comment by mbprondzinski** [comment]
Yes, we did.  We had a few snafus but we got him set up.   I guess we could have used Zoom.  Next time!

**Comment by Jegelewicz** [comment]
> Do we have a sign up mechanism for Zoom?

Just put it on the AWG calendar.
