### ISSUE TITLE
Part bulkload help needed

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2433]
@dustymc @jldunnum 
We need some assistance at MSB to correct problems related to  a very difficult legacy set of several thousand tissues and specimen records, many with duplicate NK numbers. This ongoing project to resolve duplicates and match tissues to specimens is ongoing by two collection managers and a graduate student in museum studies as a thesis project. 
During this process we will be using the parts bulkloader to upload new barcoded parts to specimen records, using the "use existing" option to match barcodes to parts if a similar part already exists.
Problems we have identified that we need admin assistance in resolving include:
1)	Delete any MSB duplicate parts with identical barcodes, e.g. MSB:Mamm:298766
2)	Heart, kidney (frozen) are combined in barcoded cryovials; however, these parts exist in Arctos as separate parts (not combined), so a new part is created by "use existing:. We request deletion of all separate heart and kidney parts that have no barcode IF "heart, kidney (frozen) with barcode" exists.
3)	Some parts were originally entered as "part name" with no preservation; the new part is "part name (frozen)". Please delete any “part (no preservation) with no barcode" IF identical “part (frozen)” with barcode exists.
4)	Delete “tissue (frozen)” or “tissue” if any other of the following tissue type parts exist with barcodes (liver", "heart", "kidney", "heart, kidney", "lung", "spleen")
5)	Finally, after my first attempted parts bulkload, I validated the loaded records, downloaded the csv output to remove problem records, deleted my records from the Parts Bulkloader staging table,  and re-upload valid only records. In the process, many of the parts were duplicated on the re-upload. These parts are not duplicated in my original file, but are duplicated in the csv output. What is up with that, and how can that be prevented in the future?

**Comment by jldunnum** [comment]
Uugghh, I’ll come by tomorrow to get an update on the situation.

Sent from my iPhone

On Jan 7, 2020, at 5:54 PM, Mariel Campbell <notifications@github.com<mailto:notifications@github.com>> wrote:

  UNM-IT Warning: This message was sent from outside of the LoboMail system. Do not click on links or open attachments unless you are sure the content is safe. (2.3)

@dustymc<https://github.com/dustymc> @jldunnum<https://github.com/jldunnum>
We need some assistance at MSB to correct problems related to a very difficult legacy set of several thousand tissues and specimen records, many with duplicate NK numbers. This ongoing project to resolve duplicates and match tissues to specimens is ongoing by two collection managers and a graduate student in museum studies as a thesis project.
During this process we will be using the parts bulkloader to upload new barcoded parts to specimen records, using the "use existing" option to match barcodes to parts if a similar part already exists.
Problems we have identified that we need admin assistance in resolving include:

  1.  Delete any MSB duplicate parts with identical barcodes, e.g. MSB:Mamm:298766
  2.  Heart, kidney (frozen) are combined in barcoded cryovials; however, these parts exist in Arctos as separate parts (not combined), so a new part is created by "use existing:. We request deletion of all separate heart and kidney parts that have no barcode IF "heart, kidney (frozen) with barcode" exists.
  3.  Some parts were originally entered as "part name" with no preservation; the new part is "part name (frozen)". Please delete any “part (no preservation) with no barcode" IF identical “part (frozen)” with barcode exists.
  4.  Delete “tissue (frozen)” or “tissue” if any other of the following tissue type parts exist with barcodes (liver", "heart", "kidney", "heart, kidney", "lung", "spleen")
  5.  Finally, after my first attempted parts bulkload, I validated the loaded records, downloaded the csv output to remove problem records, deleted my records from the Parts Bulkloader staging table, and re-upload valid only records. In the process, many of the parts were duplicated on the re-upload. These parts are not duplicated in my original file, but are duplicated in the csv output. What is up with that, and how can that be prevented in the future?

**Comment by dustymc** [comment]
I don't believe the part bulkloader is the tool for this job.

1. Data attached. Please confirm and I'll delete by either part1_id or part2_id. I know there are multiple parts in one container for other reasons - you will need to confirm that these are not them, and only include things that need deleted.

```

create table temp_msb_dup_one as
select
	flat.guid,
	p1.collection_object_id part1_id,
	p2.collection_object_id part2_id,
	p1.part_name partname,
	pbc.barcode
from
	flat
	inner join specimen_part p1 on flat.collection_object_id=p1.derived_from_cat_item
	inner join coll_obj_cont_hist on p1.collection_object_id=coll_obj_cont_hist.collection_object_id
	inner join container pc on coll_obj_cont_hist.container_id=pc.container_id
	inner join container pbc on pc.parent_container_id=pbc.container_id 
	inner join specimen_part p2 on flat.collection_object_id=p2.derived_from_cat_item
	inner join coll_obj_cont_hist pch2 on p2.collection_object_id=pch2.collection_object_id
	inner join container pc2 on pch2.container_id=pc2.container_id
where
	flat.guid like 'MSB:%' and
	p1.part_name=p2.part_name and
	p1.collection_object_id!=p2.collection_object_id and
	pbc.barcode is not null and
	pc.parent_container_id=pc2.parent_container_id
group by 
	flat.guid,
	p1.collection_object_id,
	p2.collection_object_id,
	p1.part_name,
	pbc.barcode
;
```
[temp_msb_dup_one.csv.zip](https://github.com/ArctosDB/arctos/files/4036181/temp_msb_dup_one.csv.zip)

We can deal with the rest one at a time. If you think a form isn't acting predictably I'll need the data that caused the problem - I don't see a reason the parts bulkloader would make duplicates unless it's provided duplicated.

**Comment by campmlc** [comment]
Here is the original data file, plus the downloaded csv from the parts bulkloader and the edited re-upload file which contained duplicates. I think I see the problem now. In addition to records with status errors (invalid catalog number), which I deleted for the reupload, and "valid" status records, which I wanted to load, there are some status = loaded records, which I missed and included on the reupload. I'm not sure how they got in there, especially since it is not a complete set of duplicates. I'm wondering if there was some delay in the browser from a previous delete of items from the staging table - perhaps the delete wasn't complete when I did the download. 
Anyway, it would be helpful if you can execute the cleanup I initially requested just on these records, for now, to make sure this is working. Eventually we will need a cleanup for the entire project, and beyond that, a cleanup for MSB, but I can't go one by one and figure out the 825 problems in the list that are outside the scope of this project right now.  Thanks!

[BulkloadSpecimenPartData_with_errors.zip](https://github.com/ArctosDB/arctos/files/4036519/BulkloadSpecimenPartData_with_errors.zip)

**Comment by dustymc** [comment]
I can't identify "just these records" beyond what I've done in the attached, and I'm very hesitant to delete maybe-random things without confirmation. I can add things to this file if that makes it easier to identify any outliers, but I don't think I can proceed to any irrevocable actions without some sort of confirmation from someone who can identify the proper records.

**Comment by campmlc** [comment]
I guess I'm confused - can we just fix the records that I modified yesterday in the attached files? There shouldn't be Bird records in that list, but there are Bird records in the file you have sent to me.
Here is an example of one of the problem records, showing both the exact part duplicated (liver (frozen)) and the separate heart and kidney parts with no barcodes that should be deleted given there is now a combined heart, kidney (frozen) part with barcode.

**Comment by campmlc** [comment]
https://arctos.database.museum/guid/MSB:Mamm:264761

**Comment by campmlc** [comment]
Note that liver, lung, and spleen are all duplicated parts in this record.

**Comment by dustymc** [comment]
What I attached is "MSB duplicate parts with identical barcodes, e.g. MSB:Mamm:298766"

I deleted everything not modified by you yesterday

```
delete from temp_msb_dup_one where guid not in (
	select guid from flat where collection_object_id in (
		select collection_object_id from flat_edit_history where to_char(EDIT_DATE,'YYYY-MM-DD')='2020-01-07' and USER_P_NAME='Mariel L. Campbell'
	)
);

```

remainder attached - please confirm that the part identified by part1_id can be deleted.

[temp_msb_dup_one(1).csv.zip](https://github.com/ArctosDB/arctos/files/4037754/temp_msb_dup_one.1.csv.zip)

**Comment by campmlc** [comment]
Thanks. Looks like there is still an issue here, in that both duplicates
are included. Since the original and the duplicate are each included on
separate rows, if I understand correctly, deleting part1_id for both rows
will delete both parts entirely. Anyway to just delete one of them?
e.g.

A37R1 MSB:Mamm:264586 22720800 28796869 liver (frozen)
A37R1 MSB:Mamm:264586 28796869 22720800 liver (frozen)
A37R3 MSB:Mamm:264586 22720801 28796853 lung (frozen)
A37R3 MSB:Mamm:264586 28796853 22720801 lung (frozen)
A37R0 MSB:Mamm:264586 22720798 28796903 spleen (frozen)
A37R0 MSB:Mamm:264586 28796903 22720798 spleen (frozen)

**Comment by dustymc** [comment]
Good catch, thanks!

How's this one?

[temp_msb_dup_one(3).csv.zip](https://github.com/ArctosDB/arctos/files/4041717/temp_msb_dup_one.3.csv.zip)

**Comment by campmlc** [comment]
This looks good, thanks!

**Comment by dustymc** [comment]
OK, (1) is done. Here's (2) for review

```

create table temp_msb_dup_two as
select distinct 
	guid,
	p1.collection_object_id keep_pid,
	p2.collection_object_id hrt_id,
	p3.collection_object_id kid_id
from 
	flat,
	specimen_part p1,
	specimen_part p2,
	specimen_part p3,
	coll_obj_cont_hist,
	container pc,
	container bc
where
	flat.guid like 'MSB:%' and
	flat.collection_object_id=p1.derived_from_cat_item and
	flat.collection_object_id=p2.derived_from_cat_item and
	flat.collection_object_id=p3.derived_from_cat_item and
	p1.part_name='heart, kidney (frozen)' and
	p1.collection_object_id=coll_obj_cont_hist.collection_object_id and
	coll_obj_cont_hist.container_id=pc.container_id and
	pc.parent_container_id=bc.container_id and
	bc.barcode is not null and
	p2.part_name in ('heart','heart (frozen)') and
	p3.part_name in ('kidney','kidney (frozen)') 
;

```
[temp_msb_dup_two.csv.zip](https://github.com/ArctosDB/arctos/files/4041992/temp_msb_dup_two.csv.zip)

**Comment by campmlc** [comment]
Thanks - that looks like it took care of the identical parts with identical
barcodes. The next step would be to eliminate the duplicate parts, one of
which has a barcode or position and one of which does not.
For example: https://arctos.database.museum/guid/MSB:Mamm:130469
and
https://arctos.database.museum/guid/MSB:Bird:25768  for reference.
However, we can wait to do this until all the remaining barcodes are loaded
to the part for this project.

**Comment by dustymc** [comment]
OK, I'll pause until I hear back from you.

**Comment by campmlc** [comment]
Ready to do some cleanup:
For Country = Panama only
1)	Find any duplicate parts with identical barcodes – please send temp file
2)  Find any barcodes of container type = cryovial containing more than one part - please send temp file
3)	Find any “part”  with no barcode and no label (e.g. no part location) if identical “part (frozen)” with barcode or label exists, see https://arctos.database.museum/guid/MSB:Mamm:130518
4)	Heart, kidney (frozen) were loaded as new combined barcoded part; need to find  all separate heart and kidney parts that have no barcode or label (including heart and heart (frozen), kidney and kidney (frozen)),  if part = heart, kidney (frozen) with barcode exists. 
3)	Change all part dispositions for parts with a part location in DGR to in collection
4)	Find unbarcoded “tissue (frozen)” or “tissue”parts if other tissue type part exists with barcode
