### ISSUE TITLE
IRMNG for taxonomy

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2434]
I've been adding a lot of classifications today and find that the Interim Register of Marine and Non-marine Genera (IRMNG) is very useful. They operate much like WoRMS and I wonder if we can set up a Taxonomy Source in Arctos that is IRMNG via Arctos? This would make cloning classifications into the Arctos source a bit easier. I don't know if we can work with these guys the same way, but there is info here: http://www.irmng.org/aphia.php?p=webservice

It appears that they are also using aphiaid.

> If you know the taxon exists, lookup the IRMNG_ID, via the search interface, and link to this URL: http://www.irmng.org/aphia.php?p=taxdetails&id=IRMNG_ID
> i.e. the IRMNG_ID for Solea solea is 10150800: http://www.irmng.org/aphia.php?p=taxdetails&id=10150800

**Comment by dustymc** [comment]
A very quick glance suggests they'd plug in about like WoRMS (might even be able to re-use some code), BUT....

WoRMS is a LOT of work, and takes a significant amount of resources. I think that's justifiable due to the use case, but I'm less anxious to bite off something similar for less-specific reasons. IRMNG is already feeding GN so the classifications are in Arctos - eg, http://arctos.database.museum/name/Solea%20solea#TheInterimRegisterofMarineandNonmarineGenera. What would explicitly adding them as a source do beyond what can be done now?

**Comment by Jegelewicz** [comment]
> so the classifications are in Arctos - eg, http://arctos.database.museum name/Solea%20solea#TheInterimRegisterofMarineandNonmarineGenera. 

They are available to clone, but none of the meta stuff is there. I have to go to IRMNG to get author name, valid or no, extinct or no, and to get the citation for the source authority.

> What would explicitly adding them as a source do beyond what can be done now?

Somehow, all this stuff comes over in the WoRMS via Arctos source and when cloning from something that is a taxonomy source ALL the stuff comes over.

**Comment by dustymc** [comment]
Are they sharing everything they have with globalnames? If not, why not - can they be convinced to do so, and/or can GN be convinced to provide what they need to do so?

Beyond any standardizing and sharing we might convince them to do, we could talk about 'translating.' Eg., ``replace(name string,scientific_name,NULL)`` yields the author string in this case, and that could then be used in seeding the local classification.

I don't think GN is something we can realistically replicate a little bit at a time, and then maintain, without a similar level of funding. I have no idea what the administrative picture there looks like, but the lead programmer has been great at working with us. NSF has invested a ton of $$ in GN, and perhaps could somehow be convinced to invest a bit more to make it more usable.

**Comment by Jegelewicz** [comment]
I just happened to have this one open: https://arctos.database.museum/name/Pseudohypolophus%20mcnultyi

I cloned the IRMNG for Pseudohypolophus to that name, then when I got to the species, I cloned the genus record from Arctos and added the author name that is provided by GBIF. [Pseudohypolophus](https://arctos.database.museum/name/Pseudohypolophus0 shows a bit of what is NOT in GN but can be found at the source (valid, extinct)

[Pseudohypolophus mcnultyi](https://arctos.database.museum/name/Pseudohypolophus%20mcnultyi) shows some more (synonym of...) and for some reason the classification in GN for this species is just the classification for the genus - not sure what's up there.

Anyway, this particular species had me creating classifications for the genus and the species. I should have also done the synonym and the one remaining Pseudohypolophus species, but it takes up a lot of time and all I am doing is copy-pasting. There must be a better way!

**Comment by dustymc** [comment]
>better way

Not perfect, but after the first you can re-use whatever's shared with...

<img width="396" alt="Screen Shot 2020-01-08 at 5 10 09 PM" src="https://user-images.githubusercontent.com/5720791/72029109-be923900-3239-11ea-9c0b-280089f60676.png">

**Comment by Jegelewicz** [comment]
That is what I used, but it still requires me manually copying stuff from the source for the particular taxon in question. That's why I was asking for IRMNG as an Arctos Source. When I use the cloning functionality from anything in an Arctos source, all the meta stuff clones right over. So, for the first one; Pseudohypolophus all I would have had to do would be clone it over and add the extinct and valid values instead of also needing to copy the author and source.

FYI I have spent the last three days adding/editing classifications for just about 150 taxa. Granted, a lot of that is research (finding a taxon name mispelled, etc.) but there is no way we can expect even just "good" taxonomy in Arctos when it takes that long. There are some good, reliable resources like WoRMS and IRMNG and we can pull them in (with more info than supplied via GN) which makes stuff easier for those of us trying to build and maintain taxonomy.

Currently, I have a list of over 2,600 taxon names used in the NMMNH Access database but not in the names list in Arctos. Some of these are misspellings to be corrected before data migration, but experience so far suggests that about 1/3 are names that need to be added and that most likely 2/3 need to have classifications added. I could spend a year getting those all done properly. And that doesn't even count all the taxa that are in Arctos so that data will migrate smoothly, yet those names have no related classification....

**Comment by sharpphyl** [comment]
This might be worth discussing at our meeting Wednesday.  When I looked at IRMNG, they show that they uploaded the WoRMS database in 2013 and, if I read their website correctly, they haven't updated anything from WoRMS since.  That leaves out a ton of changes for marine species, but perhaps the species you're interested in have the accurate higher classification and taxon name.

For the land snails species that I have to add to WoRMS (via Arctos), I have recently being using a lot of the taxonomy in GBIF for the accurate name and author, but I do copy the WoRMS higher classification at the genus level, then add the species and author detail.  Would GBIF be worth considering?

**Comment by Jegelewicz** [comment]
> Would GBIF be worth considering?

Potentially, but I'm not completely confident as much of the GBIF backbone is created from stuff that collections submit and I don't know how much review is going into it on the GBIF side. I use it too when all else fails.
