### ISSUE TITLE
Media thumbnails from external URI not displaying

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#2436]
I know media thumbnail display has been a past issue, but this may or may not be related to the specific image repository CalPhotos, or just linked images in general.

Here's the bug:
Please see this record: https://arctos.database.museum/guid/MVZ:Herp:258415 where there are two photos associated with this type specimen. One thumbnail is visible, the other is not.

The broken media thumbnail is this one: https://arctos.database.museum/media/10257311
where it is linked to this preview URI: https://calphotos.berkeley.edu/imgs/128x192/0000_0000/0809/1561.jpeg

When you clink on Open for either URI it works; however, the catalog record page cannot display it. As I test I manually downloaded the JPEG thumbnail and uploaded for the other image at https://arctos.database.museum/media.cfm?action=edit&media_id=10257310 and voila it appears as desired on the record detail page (it's the thumbnail that works)

Additionally: when you click on the Red X thumbnail (https://arctos.database.museum/media/10257311?open) you receive a 500 error. So what is the misconfiguration?

OK, so is it just a problem to have linked images appear or specific to Calphotos link? Can we just take that Preview URI and toss some `<img src=https://calphotos.berkeley.edu/imgs/128x192/0000_0000/0809/1561.jpeg>` tags on it so it will appear? <img src=https://calphotos.berkeley.edu/imgs/128x192/0000_0000/0809/1561.jpeg>

What is the solution to allow externally linked images to appear on Arctos?

FYI, I am giving a presentation on this topic in 1.5 weeks! thanks

**Comment by dustymc** [comment]
See http://handbook.arctosdb.org/documentation/media.html#media-creation-guidelines

>previews larger than 48K will NOT be displayed

The thumb is 49.27 KB (50,449 bytes) so isn't being displayed - those eat browsers.

The 'something is broken' page is just a precheck of the media_uri -  calphotos is timing out, blocking requests from Arctos, doesn't respond properly to HEAD, or similar.

**Comment by mkoo** [comment]
OK, thanks.
I will check on the CalPhotos side of things by asking Joyce about allowing connection requests. 

But I think CP thumbnails are all about 50 kb -- some a little more or less so the ones that will break will be scattershot throughout Arctos. Can we not increase this threshold to 51kb to accommodate CP? Or is there something magical about 48k?

Again, I can work with Joyce to see about matching this limit for the future

**Comment by dustymc** [comment]
Na, nothing magical, it's just about 10 times the size needed to look good at that scale.

Cumulatively those do become magical - not the good kind - https://github.com/ArctosDB/arctos/issues/2418

Increasing the threshold isn't TOO bad, but I'd have to do it in two places at this point and it will lead to more browsers being eaten (although a couple K per thumb may or may not be noticeable).

**Comment by mkoo** [comment]
OK, having checked with Joyce, it would be far easier overall and for the user experience (reducing redX's in Arctos) to increase the threshold on the Arctos side. Can you please increase from 48 to maybe 52 or 55KB? That would take care of a lot of red X's!

FYI, Number of CP images in Arctos as media is about 15,430; CP images linked to a specimen, ca. 4,000 (including those in prep to be linked to a cat_item) So it's a lot.

Thanks for accommodating quickly!

**Comment by dustymc** [comment]
I think this needs more discussion - are red Xs less evil than potentially-eaten browsers? - but I don't know how to facilitate that.

@AJLinn

**Comment by mkoo** [comment]
The delicate browsers have work arounds to limit the images shown, yes? (#2418)

CP thumbnails do too, but it is a massive undertaking in a 3rd party repo and would be easier to increase from 48 kb to even 51 kb threshold in Arctos instead. I also think this will mostly impact mvz images for the moment.

There's an appearance issue having redX's on Arctos that despite its origin (ie. not Arctos' fault) still gives an undesirable look to our interface. A third option would be to replace the default image I suppose.

If we had tons of development funds, another workaround would be an easy online app to reduce large thumbnails to Arctos-happy levels.

**Comment by dustymc** [comment]
>The delicate browsers have work arounds to limit the images shown, yes? (#2418)

Practically, probably. You could kill about any browser with enough thumbs on one record, but I don't think that's terribly likely. When it does happen, it's cryptic and looks like Arctos is broken for no good reason - at least the behavior around huge thumbnails is documented.

If users CAN do something, they generally will. I'm also somewhat concerned about creating a lot of large thumbs, and then needing to clean them up later.

I could definitely use a thumbnail service - https://github.com/ArctosDB/PG/issues/4. If we find something it should come with 'Arctos may alter your suggested thumbnail' documentation.

**Comment by dustymc** [comment]
I bumped the limit to 64K, it's still not working - CP is rejecting the request for some reason.

You can run the checker and get a dump here:

https://arctos.database.museum/component/functions.cfc?method=getMediaPreview&media_type=image&preview_uri=https://calphotos.berkeley.edu/imgs/128x192/0000_0000/0809/1561.jpeg&debug=true

**Comment by JoyceGross** [comment]
How exactly are you accessing/embedding the image in your code, and from what IP is the request coming? View source shows me no details as to what you are doing.

**Comment by dustymc** [comment]
```
<cfhttp method="head" url="#ftgt#" timeout="1">
```
It should be a standard HEAD request, but not unimaginable that CF is doing something crazy instead!

```
nslookup arctos.database.museum
Name:	arctos.database.museum
Address: 129.114.52.171

-bash-4.1$ curl -I https://calphotos.berkeley.edu/imgs/128x192/0000_0000/0809/1561.jpeg
curl: (35) SSL connect error

-bash-4.1$ curl -I http://calphotos.berkeley.edu/imgs/128x192/0000_0000/0809/1561.jpeg
HTTP/1.1 302 Found
Date: Fri, 24 Jan 2020 20:31:40 
```

**Comment by JoyceGross** [comment]
Hmmm, I'm getting better results. I tried curl from both a remote (non-UC) server, and from a BNHM server. The results were the same (see below). Can you run 
  curl --version
and let me know what version you have?

With SSL (https);

[joyceg6@biz211 ~]$ curl -I https://calphotos.berkeley.edu/imgs/128x192/0000_0000/0809/1561.jpeg
HTTP/1.1 200 OK
Date: Fri, 24 Jan 2020 20:43:38 GMT
Server: Apache/2.2.15 (CentOS)
Last-Modified: Sat, 22 Aug 2009 22:17:09 GMT
ETag: "b1ff1-c511-471c2587ca340"
Accept-Ranges: bytes
Content-Length: 50449
Content-Type: image/jpeg


[joyceg@louise ~]$ curl -I https://calphotos.berkeley.edu/imgs/128x192/0000_0000/0809/1561.jpeg
HTTP/1.1 200 OK
Date: Fri, 24 Jan 2020 20:40:40 GMT
Server: Apache/2.2.15 (CentOS)
Last-Modified: Sat, 22 Aug 2009 22:17:09 GMT
ETag: "b1ff1-c511-471c2587ca340"
Accept-Ranges: bytes
Content-Length: 50449
Content-Type: image/jpeg

Without SSL (http):

[joyceg6@biz211 ~]$ curl -I http://calphotos.berkeley.edu/imgs/128x192/0000_0000/0809/1561.jpeg
HTTP/1.1 302 Found
Date: Fri, 24 Jan 2020 20:45:39 GMT
Server: Apache/2.2.15 (CentOS)
Location: https://calphotos.berkeley.edu/imgs/128x192/0000_0000/0809/1561.jpeg
Content-Type: text/html; charset=iso-8859-1

[joyceg@louise ~]$ curl -I http://calphotos.berkeley.edu/imgs/128x192/0000_0000/0809/1561.jpeg
HTTP/1.1 302 Found
Date: Fri, 24 Jan 2020 20:41:46 GMT
Server: Apache/2.2.15 (CentOS)
Location: https://calphotos.berkeley.edu/imgs/128x192/0000_0000/0809/1561.jpeg
Content-Type: text/html; charset=iso-8859-1

**Comment by dustymc** [comment]
-bash-4.1$ curl --version
curl 7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.19.1 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
Protocols: tftp ftp telnet dict ldap ldaps http file https ftps scp sftp 
Features: GSS-Negotiate IDN IPv6 Largefile NTLM SSL libz 

Not terribly surprising is its our crypto - that box is old...

**Comment by JoyceGross** [comment]
Well that's weird because it's the same version that's on louise (also running an old OS etc.).  A newer version is on the non-BNHM server I tried. Both work.

I'll see if I can think of something else.


[joyceg@louise ~]$ curl --version
curl 7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.44 zlib/1.2.3 libidn/1.18 libssh2/1.4.2
Protocols: tftp ftp telnet dict ldap ldaps http file https ftps scp sftp
Features: GSS-Negotiate IDN IPv6 Largefile NTLM SSL libz


[joyceg6@biz211 ~]$ curl --version
curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.45.0 OpenSSL/1.0.1e zlib/1.2.7 libidn/1.28 libssh2/1.8.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile NTLM NTLM_WB SPNEGO SSL libz unix-sockets

**Comment by JoyceGross** [comment]
Dusty, what is the output is you run this from your server?

curl -I https://essig.berkeley.edu/wp-content/uploads/sites/5/2018/01/Trex.jpg

**Comment by dustymc** [comment]
-bash-4.1$ curl -I https://essig.berkeley.edu/wp-content/uploads/sites/5/2018/01/Trex.jpg
curl: (35) SSL connect error

**Comment by JoyceGross** [comment]
What happens if you try this?

curl -I --tlsv1.2 https://calphotos.berkeley.edu/imgs/128x192/0000_0000/0809/1561.jpeg

**Comment by dustymc** [comment]
-bash-4.1$ curl -I --tlsv1.2 https://calphotos.berkeley.edu/imgs/128x192/0000_0000/0809/1561.jpeg
HTTP/1.1 200 OK
Date: Fri, 24 Jan 2020 21:32:06 GMT
Server: Apache/2.2.15 (CentOS)
Last-Modified: Sat, 22 Aug 2009 22:17:09 GMT
ETag: "b1ff1-c511-471c2587ca340"
Accept-Ranges: bytes
Content-Length: 50449
Content-Type: image/jpeg

**Comment by JoyceGross** [comment]
OK! The "--tlsv1.2" specifies the SSL protocol to use. Can you use that command instead? It seems that curl was not using the right protocol.

**Comment by JoyceGross** [comment]
BTW, CalPhotos and all the BNHM sites support these two protocols:

TLSv1.1 
TLSv1.2

I think they are fairly standard. I don't know why your curl needs the exact protocol specified but my (same version of) curl doesn't.

**Comment by dustymc** [comment]
Thanks @JoyceGross 

@mkoo this seems to be related to our version of java, which is related to our version of CF. It's apparently possible to upgrade java under this CF release, but it's not something I'd be especially comfortable doing on a production server. We could try to sucker Chris into doing it or just wait for the new VM.

**Comment by mkoo** [comment]
ok probably not worth swapping out tires while on a roadtrip to buy a new car...
thanks @JoyceGross for getting some of this issued explored however.

Can we go with my option 3? a different icon for missing thumbnails which is often not really missing and removes my allergy to red X's?

Are you using bootstrappy things yet? can I suggest a font awesome icon like this?
```
<i class="fas fa-image"></i>
```
https://fontawesome.com/icons/image?style=solid

or I can download/send something else

**Comment by dustymc** [comment]
>different icon 

Sure, just work it out with the community and push to https://github.com/ArctosDB/arctos/blob/master/images/noThumb.jpg. (And to the PG repo too please...)

No magic UI tools here.
