### ISSUE TITLE
New Part Name thorax - for ento/ES collections

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2437]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Table**
http://arctos.database.museum/info/ctDocumentation.cfm?table=CTSPECIMEN_PART_NAME

**Value**
thorax

**Definition**
The middle section of the body of an insect, between the head and the abdomen, bearing the legs and wings

**Collection type**
Ento, ES, Teach

**Part tissue flag**
No

**Context**
In ES collections we often have only the thorax of an insect or the impression of one.

**Priority**
Please assign a priority-label.

**Comment by Jegelewicz** [comment]
@DerekSikes @mvzhuang @dperriguey @Nicole-Ridgwell-NMMNHS please weigh in.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I am fine with this.

**Comment by Jegelewicz** [comment]
Done.
