### ISSUE TITLE
New part for ES collections

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2439]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Table**
http://arctos.database.museum/info/ctDocumentation.cfm?table=CTSPECIMEN_PART_NAME

**Value**
rib, cervical

**Definition**
Ribs that attach lateroventrally to the cervical vertebrae and are are lost in some groups.

**Collection type**
ES

**Part tissue flag**
no

**Context**
Important term for some dinosaurs

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
I suggest 'cervical' (and the existing caudal and dorsal) would make better part attributes, but also no objection to just adding this now and dealing with that in PG.

**Comment by Jegelewicz** [comment]
> I suggest 'cervical' (and the existing caudal and dorsal) would make better part attributes, but also no objection to just adding this now and dealing with that in PG.

Totally planning on that, but figured I would be consistent with what we have right now.

**Comment by Jegelewicz** [comment]
@Nicole-Ridgwell-NMMNHS @dperriguey please weigh in.

**Comment by mbprondzinski** [comment]
Our collection has a dearth of dinosaurs so it really is not an issue for us.  I found no reference to it in our database.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Sounds good to me. Agree that it is best to follow the status quo now and move it over to part attributes along with the others later.

**Comment by Jegelewicz** [comment]
Added
