### ISSUE TITLE
Citation Bulkloader template and documentation

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2442]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
In the documentation for the Citations Bulkloader at https://arctos.database.museum/tools/BulkloadCitations.cfm
1) We are given info that a pre-populated template can be downloaded from specimen results. But this template is not the same as the template available in the bulkloader; need to update order and column headers so both are consistent.
2) The accepted_id_fg documentation gives 0/1 options but needs to specify what each of the options corresponds to in terms of the accepted identification.
3) Can we make dois an acceptable option for publication id, assuming the dois have been added to Arctos?

**To Reproduce**

**Expected behavior**

**Screenshots**

** Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by campmlc** [comment]
We need to clarify the documentation on publication ID. The current documentation says:

publication-id: find in URLs - eg, http://arctos.database.museum/publication/1 - use either this or full_citation, not both"
However, we need to explicitly state whether you need to use the entire url for the id (No), or just extract the terminal number (Yes), :
"for example, for the url https://arctos.database.museum/publication/10009052 - enter only the terminal number, 10009052. Use either this format for publication-id,  or use the full_citation, but not both"
--

**Comment by dustymc** [comment]
>The accepted_id_fg documentation gives 0/1 options but needs to specify what each of the options corresponds to in terms of the accepted identification.

I don't know what this means. The flag does what the documentation says it does.

>doi

when https://github.com/ArctosDB/arctos/issues/2419 is fixed, sure

**Comment by dustymc** [comment]
citation loader needs rebuilt in component loader format

**Comment by dustymc** [comment]
blocked by https://github.com/ArctosDB/arctos/issues/2974#issuecomment-779986500

**Comment by dustymc** [comment]
New citation loader in test, it needs tested. DOI added. confirmed that the download-->edit-->upload path works
