### ISSUE TITLE
New event attribute - associated taxon

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2443]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Table**
http://arctos.database.museum/info/ctDocumentation.cfm?table=CTCOLL_EVENT_ATTR_TYPE

**Value**
associated taxon

**Definition**
Taxonomic name of organism which was not collected, but which was associated with the organism at the time of collection. 

**Attribute data type**
categorical

**Attribute value**
TAXON_NAME

**Attribute method**
This field should be tied to [ID_REFERENCES](http://arctos.database.museum/info/ctDocumentation.cfm?table=CTID_REFERENCES) with new terms added as necessary (in the case of this example, I could see the need for a term such as "resting on". It will also probably mean we will need the relationship "unknown" as some legacy data can be hard to decipher.

**Context**
We record relationships such as "eaten by" and "host of" when there are two vouchers - demonstrating some sort of relationship between two species. However, these relationships are also observed and recorded in the "Associated species" field in a far less rigorous manner. 

See [UTEP:Ento:100057](http://arctos.database.museum/guid/UTEP:Ento:100057) as an example.

**Describe alternatives you've considered**
Observations for related species can be recorded - but that costs money for the collection creating and managing them.

If we go this way - it will require a clean-up and I suggest removal of the "associated species" field.

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
>CTCOLL_EVENT_ATTR_TYPE

That will isolate hosts and parasites

>TAXON_NAME

I don't think your browser will like 3-million-item picks lists, and even if it did I couldn't know it you were talking about Echidna-the-viper or ...

>method...be tied to 

The model does not currently support that capability.

>costs money 

I suppose I'm willing to let administrative decisions drive modeling at some point, but I don't think this is there.

>removal of the "associated species" field

This does not do what it's designed for.

I tentatively suggest flagging this 'won't fix' and, in order of preference:

1) Let's first discuss the cost issue; hopefully well have some $$ to talk about that sort of thing in the near future. (The MSB:Hosts catalog does just this and would work for this use case - perhaps we can find something clever with some sort of shared host dumpsite or ????)
2) Arctos can make relationships to external resources; you could load (minimal) DWC to GBIF-er-sumthin and link to it.
3) I'm not sure I see significant functionality beyond associate_species in this.

**Comment by Jegelewicz** [comment]
closing for lack of interest
