### ISSUE TITLE
Trouble creating a project

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/arctos#2446]
** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **

** Outages should be reported to the contacts listed at https://arctosdb.org/arctos-down/ **

** Arctos Documentation is http://handbook.arctosdb.org/ **

** Learn more about Arctos at https://arctosdb.org/ **

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **

![image](https://user-images.githubusercontent.com/43214224/72351059-41d1e580-36a5-11ea-8d4d-f3c556b79f41.png)

Can't figure out what is wrong with my project name.

**Comment by Jegelewicz** [comment]
There is a blank space at the end or some other non-printing character in the project name.

**Comment by Jegelewicz** [comment]
Maybe a hard return if you copy and pasted from somewhere...

**Comment by mbprondzinski** [comment]
Yeah, I figured it out.  I entered a hard return after the <br>!  Thanks…
