### ISSUE TITLE
New Agent role in publications - subject

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2447]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=CTPROJECT_AGENT_ROLE

**Value**
Subject

**Definition**
Agent name of a person documented in the publication.

**Context**
From #2135

> Would it be possible to add a new author role in publications, possibly called “Subject”? This would give us a way of keeping track of artist bibliographies, artist interviews, exhibition reviews, maybe even artist statements?. Sometimes the Agent is both the subject AND the author and it would be great to be able to make that clear.

~~Not sure if this could facilitate the following, but I think "Quoted" is clearer than "Subject" which makes it seem as if the subject of the publication is the person making the quote.~~

From http://libraryfaqs.cu-portland.edu/faq/8555

>     If you are quoting a quote within the article (not your author’s words), then there are two options:
> 
> You quote the quote and your author’s thought about it. Note the single quote marks around the quotation within my quote:
> 
> “The underlying concept proposed by the Knapp project centers on ‘the intellectual processes involved in retrieval of information and ideas’ (Lindgren, 1981, p.28)” (Kuhlthau, 2004, p. 10-11).
> 
> You only quote the quote:
> 
> “We must concentrate on uniting the processes of gathering information with the uses of information” (Lindgren, 1981 as cited in Kuhlthau, 2004, p. 11)

**Priority**
Please assign a priority-label.

**Comment by Jegelewicz** [comment]
@marecaguthrie @AJLinn please weigh in and let me know if this isn't what you were after!

**Comment by krgomez** [comment]
Thanks for getting this issue started Teresa! While there would be publications where a quoted agent would be useful to reference, I’m not sure Quoted would work perfectly. Quoted would work for some publications such as artist interviews, artist statements, and anywhere else an artist is quoted directly. However, there would be many cases where Quoted wouldn’t be accurate. For example, an article discussing the work of an artist may not actually quote that artist in the text. We still need a way to tag the artist in order for the article to appear under publications in the agent summary. Subject still seems like the right term for this new role over Quoted, in that it is broader and would be applicable in all the above examples whereas Quoted would I think only apply to some. It also relates to the subject agent role we have already created for use when an artwork depicts a specific agent. There may still be a better role name but I can’t think of it now.

Maybe there is another way to tag an agent in a publication outside of adding them along with the authors and editors? Some way through the agent record itself?

**Comment by dustymc** [comment]
Is this still active? (If so, the suggested table doesn't match the title.)
