### ISSUE TITLE
New part name - root

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2448]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=CTSPECIMEN_PART_NAME

**Value**
root

**Definition**
The part of a plant which attaches it to the ground or to a support, typically underground, conveying water and nourishment to the rest of the plant via numerous branches and fibers.

**Collection type**
ES, Herb

**Part tissue flag**
No

**Context**
In paleo, we have parts of plants. Just as with skeletons, it would be nice to be able to be a bit more precise about the part of the plant we have.

**Priority**
Please assign a priority-label.

**Comment by Jegelewicz** [comment]
@mvzhuang @Nicole-Ridgwell-NMMNHS @dperriguey @mbprondzinski please weigh in.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Sounds good to me.

**Comment by Jegelewicz** [comment]
@ArctosDB/arctos-code-table-administrators nad @dustymc any reservations?

**Comment by dustymc** [comment]
Sounds good to me.

**Comment by mbprondzinski** [comment]
Ditto

**Comment by Jegelewicz** [comment]
Done.
