### ISSUE TITLE
"No space left" when uploading Images

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#2449]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
When UAM:Fish curator Andres Lopez attempted to use the "Upload Images" tool for Small Batch Upload and received an error message:

> I tried loading a zip file through the Arctos Upload Images interface but kept getting a 'no space left' message.

@Jegelewicz thought perhaps @dustymc needed to clear out space for others to add photos? (Is there a cache that needs to be cleared?

**Comment by dustymc** [comment]
I cleaned what I can. Reason Number 9652 to prioritize PG...

**Comment by AJLinn** [comment]
Thanks - I'll tell Andres and suggest he attempt this process again.

**Comment by campmlc** [comment]
I'm getting the same error when trying to bulk edit container in object tracking.
@dustymc

**Comment by campmlc** [comment]
[FreezerRackBulkContainerEdit _C4_C5.zip](https://github.com/ArctosDB/arctos/files/4079960/FreezerRackBulkContainerEdit._C4_C5.zip)
Trying to load this file

**Comment by dustymc** [comment]
Looks like my cleaning bots did their thing and there's some space again. It's not much, and it's shared by all sorts of thing

Have I mentioned lately how critical getting to a bigger system seems from here?!

**Comment by campmlc** [comment]
I got the file uploaded while space was available. Thanks.

**Comment by Jegelewicz** [comment]
> shared by all sorts of thing

Can we get a comprehensive list of what these sorts of thing are? Maybe we can help prioritize and keep this space clean.

**Comment by dustymc** [comment]
>comprehensive list

Not anytime soon! Uploading, downloading, mapping makes a temp file, a bunch of internal stuff makes text-file caches, etc., and those all have to be deleted eventually. The new VM should have ~6 times the disk and this shouldn't be a problem for a few more years. We've just outgrown the current system.
