### ISSUE TITLE
Regional Chronostratigraphy

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2453]
For the most part chronostratigraphy has stuck to the international terms, but we have things at NMMNH that use regional terms. In some cases, these terms can be useful and a few of them have made their way into the code table. But this can be confusing and cause search issues in the hierarchy of the code table.

We propose to create a sub-category of Chronostratigraphy where we will place the regional terms with instructions to add the appropriate term(s) from the International table as we  so that cataloged items using regional terms will also be found using the international terms (which are generally accepted).

> @Nicole-Ridgwell-NMMNHS I have placed a spreadsheet that list Chronostratigraphy terms that I am unable to confirm in N:\GeoScience\Arctos\Locality\Chronostratigraphy Problems.xlxs
> 
> Let me know how you want to handle each of these. Some of them appear to be old terms or just not included in the International terminology but are regional terms. Not sure about adding regional terms to Arctos - so let me know your thoughts!

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/data-migration/issues/175#issuecomment-574933007_

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
List of Terms currently in Geology Attributes/Chronostratigraphy stage/age that are not in the [International Chronostratigraphic Chart](http://www.stratigraphy.org/ICSchart/ChronostratChart2019-05.jpg)

Ionian
Virgilian
Morrowan
Chesterian
Lower Cambrian
Precambrian

Also, some mistakes I noticed:
Rancholabrean should be a NALMA
Famennian should be stage/age and Upper Devonian
Eifelian should be Middle Devonian

**Comment by Jegelewicz** [comment]
@dustymc can you male these changes please?
Rancholabrean (Stage/Age) change to Rancholabrean (Land Mammal Age)
Famennian (Series/Epoch) change to Famennian (Stage/Age)

**Comment by Jegelewicz** [comment]
Ionian
Virgilian
Morrowan
Chesterian
Lower Cambrian
Precambrian

@Nicole-Ridgwell-NMMNHS can you tell me which International strata these fall in?

**Comment by Jegelewicz** [comment]
I have organized the geology table according to the above for now.
@dperriguey @mbprondzinski please weigh in.

**Comment by Jegelewicz** [comment]
@Jegelewicz to add all terms from [International Chronostratigraphic Chart](https://en.wikipedia.org/wiki/Geologic_time_scale#Table_of_geologic_time) to code table.

Could we use this instead? - A service providing a Resource Description Framework/Web Ontology Language representation of the timescale is available through the Commission for the Management and Application of Geoscience Information GeoSciML project as a service and at a SPARQL end-point.

I think this is it? http://resource.geosciml.org/vocabulary/timescale/

**Comment by dustymc** [comment]
I don't think those belong in the table, but perhaps I don't understand what a "regional term" is.

If this is more like taxonomy, the data should be (at least theoretically) backed up by some authority.

If it's more like identification, then the code table is of limited utility.

I recommend moving them into their own category for now, and we can revisit once we're in Locality Attributes. That should be a lot cleaner than mixing them in with the authoritative terms.

@Jegelewicz just add new values to the code table, I can make updates to the data if necessary, then you can delete whatever's not needed.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> I don't think those belong in the table, but perhaps I don't understand what a "regional term" is.

To try to explain this succinctly - Chronostratigraphy units are rocks deposited during a certain time interval. An effort to internationally standardize these has been happening from ~ 1970's through to today, partly by standardizing the names, partly by using GSSP points to define their bases and tie the chronostratigraphy with the geochronology. Prior to this, a lot of regions had their own chronostratigraphy because the rock layers are different in, say, New Mexico and New Zealand.  Thus, a lot of older localities will have this regional chronostratigraphy. In some places, those regional units are still being used because they describe the rock in a useful way. Delving into the literature on this was a rabbit hole of controversy on whether the regional stuff should still be used.

@Jegelewicz 's solution looks like it will work.

**Comment by dustymc** [comment]
Thanks!

I'd definitely treat that exactly like the taxonomy model. If the term is something you made up, it's not a valid term (but we can find a place for it in the Attributes model). If it's something that was published in something that someone might conceivably call "the chronostratigraphy literature" then it's acceptable and can (not necessarily should - I think that's your call) be mixed in with "current" (or accepted or however you want to view them) terms, no matter how wrong it might look from the present or if it's in current use.

**Comment by Jegelewicz** [comment]
Added all terms in the [International Chronostratigraphic Chart](http://www.stratigraphy.org/ICSchart/ChronostratChart2019-05.jpg) from Panerozoic to present with links to Wikipedia.

**Comment by Jegelewicz** [comment]
@dustymc can you fix these for me. They have been used so I cannot change them.

Rancholabrean (Stage/Age) change to Rancholabrean (Land Mammal Age)
Famennian (Series/Epoch) change to Famennian (Stage/Age)

**Comment by dustymc** [comment]
Add the new values to the CT please.

```
UAM@ARCTOS> update geology_attributes set GEOLOGY_ATTRIBUTE='Land Mammal Age',GEO_ATT_VALUE='Rancholabrean' where GEOLOGY_ATTRIBUTE='Stage/Age' and GEO_ATT_VALUE='Rancholabrean';

ORA-20001: Invalid geology_attribute: Land Mammal Age=Rancholabrean

```

**Comment by dustymc** [comment]
Ah, right, I'll have to dig out the scary password and lock down for that.

/remind me to check back on the 28th

**Comment by dustymc** [comment]
/remind me to check back next tuedsay

**Comment by Jegelewicz** [comment]
Resolved in https://github.com/ArctosDB/arctos/issues/2498
