### ISSUE TITLE
Add Cryotank to Container Type

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2454]
I would like to add "cryotank" to container type in object tracking to distinguish samples in LN2 from traditional freezer storage. This storage system also differs in terms of dimensions and positions from rectangular freezers. 
@KyndallH

**Comment by KyndallH** [comment]
Only if the definition is "really cold thing".  
<img width="385" alt="Screen Shot 2020-01-17 at 2 54 46 PM" src="https://user-images.githubusercontent.com/16887896/72653845-575f3d80-3939-11ea-9d6d-e2d229d95926.png">

It doesn't really matter to me unless it screws up my stuff.

**Comment by campmlc** [comment]
Sure. "really cold thing for vapor-phase nitrogen storage". This way I can
keep track of how many parts are in LN2 vs -80C.
It should be optional by collection.

**Comment by Jegelewicz** [comment]
This has been added - closing
