### ISSUE TITLE
Reducing length of part container path

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2455]
Looking for ways to shorten part container path so fits better in the specimen record and have it be easier to modify into a usable path for students in Excel.
It is helpful to have both the barcode and the label display when they are different. Is it possible to have only the barcode display when the label is the same as the barcode?

**Comment by campmlc** [comment]
Alternately, can this be a setting we can select? E.g. choose to display barcode, label, or both?

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/1183 should be revived and this should be discussed in context there, if your questions haven't already been answered.

We've invested a ton of work into making those data clear, purposefully making them arbitrary again is not something I'd be happy to embrace.
