### ISSUE TITLE
Barcode Request - JSNM

### ISSUE THREAD

**Issue by cefilipek** [ArctosDB/arctos#2456]
Issue Documentation is at http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html 
Barcode Series Documentation is at http://handbook.arctosdb.org/documentation/container.html#barcode-series

Please supply the following so that we can evaluate your barcode series request. If the series is available, it will be claimed and created for you. If it is not, a response will be posted to this issue and we will work to get you a suitable barcode series.

First barcode in series: 0010000JSNM

Last barcode in series: We aren't 100% sure exactly how many objects we have in the research collection, but the final barcode we have printed is 0017200JSNM.

Rules for creating random letters or digits (i.e. I would like all barcodes to have 5 places, start with an A, and the remaining 4 places can be any combination of capital letters A-Z or numbers 0-9): We don't need it to be random, we have the barcodes printed already and the numbers range from 0010000JSNM to 0017200JSNM in what we currently have on hand. Each has seven number spaces and ends in JSNM.

Additional context Add any other context or screenshots about the feature request here.

Here is an example of our barcode sheet if it is helpful.

![Barcodes](https://user-images.githubusercontent.com/56844074/72739902-3d587180-3b6a-11ea-9338-d34600d7f06f.jpg)
**Priority**

Please assign a priority-label.

**Comment by Jegelewicz** [comment]
@cefilipek do these correspond to your catalog numbers? If so, read the FAQ in the [How To Start Object Tracking](http://handbook.arctosdb.org/how_to/How-to-Start-Object-Tracking.html) about using catalog numbers as barcodes for object tracking. If the barcodes above won't be used in Arctos Object Tracking, then you don't need to "claim" them.

Also, read the section on [developing your barcode series](http://handbook.arctosdb.org/how_to/How-to-Start-Object-Tracking.html#develop-your-barcode-series). Let me know if you want to schedule a call to discuss this!

**Comment by cefilipek** [comment]
Oh! I guess I misunderstood that! Our barcodes and catalog numbers are the same. I believe we discussed leaving off the JSNM at the end for the catalog numbers, so that they would auto-populate in Arctos.

Thanks!
