### ISSUE TITLE
Arctos Gold Standard Record doesn't operate as expected

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2458]
One of our Gold Standard Records is http://arctos.database.museum/guid/UAM:EH:UA67-133-0001

And our narrative about it says:

> We like this record because a search for caesium 137-free large mammal fur or the distribution of mink in 1930 might lead a researcher to it.

BUT a search for American Mink between 1930-01-01 and 1939-12-31 does not have this record in the results.

![image](https://user-images.githubusercontent.com/5725767/72764805-c42b3f80-3ba6-11ea-8401-a4f303bc25db.png)

Pretty sure this is because there is no "collecting" event for this object. We might want to change our statement here and think about how to facilitate search when we are talking about dates other than "collected". How would I find everything "manufactured" in 1930?

**Comment by Jegelewicz** [comment]
BTW - tried this with common name "American Mink" and timed out. Neovison vison returns 144 records, none of which are UAM:ES

**Comment by dustymc** [comment]
First search is for current ID, which is a string-match against the ID.

Event type isn't considered unless you specify.

<img width="422" alt="Screen Shot 2020-01-21 at 8 14 46 AM" src="https://user-images.githubusercontent.com/5720791/72821960-1f504700-3c26-11ea-8e40-015eb9a879c4.png">

I'm working on the performance issues.

**Comment by Jegelewicz** [comment]
This still doesn't work as expected - we shouldn't be holding up as a gold standard for 

>  a search for caesium 137-free large mammal fur or the distribution of mink in 1930 might lead a researcher to it.

because they wouldn't find it.

@mkoo

**Comment by dustymc** [comment]
>doesn't work as expected

You searched this:

<img width="749" alt="Screen Shot 2021-12-02 at 2 28 29 PM" src="https://user-images.githubusercontent.com/5720791/144513495-ec0b8fe9-c15c-49a9-86af-24db289b90dd.png">

It did precisely what's expected - failed to match the thing it doesn't match!

This finds the parka:

<img width="769" alt="Screen Shot 2021-12-02 at 2 27 24 PM" src="https://user-images.githubusercontent.com/5720791/144513609-902dc0c7-fd71-46e5-a9da-b39843fda5ce.png">

**Comment by Jegelewicz** [comment]
Here is one of the three different searches I tried

![image](https://user-images.githubusercontent.com/5725767/144518460-382085cb-02db-4852-ab30-b716049a299e.png)

Which I would have expected to work given

![image](https://user-images.githubusercontent.com/5725767/144518546-01cc8fb5-b54a-4a02-ae12-d8273614e7a5.png)

**Comment by dustymc** [comment]
https://handbook.arctosdb.org/documentation/collecting-event.html#specimen-search
https://github.com/ArctosDB/arctos/issues/3864

**Comment by Jegelewicz** [comment]
Sheesh what a black hole of weirdness. But it doesn't change the fact that I would NOT have found this using something is apparently a reasonable search....

**Comment by Jegelewicz** [comment]
And this doesn't find it either

![image](https://user-images.githubusercontent.com/5725767/144520844-79b7dc63-4818-4115-b380-7b992916627f.png)

**Comment by Jegelewicz** [comment]
This does - but the search above is more likely to be what will happen, so I still say the assertion in the Gold Standard documentation is misleading.

![image](https://user-images.githubusercontent.com/5725767/144521065-0bad63a7-46c6-43aa-ac0e-98cc4499329b.png)

**Comment by dustymc** [comment]
>weirdness

[I agree!](https://github.com/ArctosDB/arctos/issues/3864#issuecomment-902283864) (But someone probably asked for it at some point....)

>doesn't find it either

``1930`` is not greater than or equal to ``1930-01-01`` - maybe there's a better way to search that, but I don't know what it might be.

**Comment by Jegelewicz** [comment]
> 1930 is not greater than or equal to 1930-01-01 - maybe there's a better way to search that, but I don't know what it might be.

Yep - so 

> a search for caesium 137-free large mammal fur or the distribution of mink in 1930 might lead a researcher to it.

Will be pretty hard to replicate unless someone tries a lot. (See results above!). It took me almost a year and about five different ways of searching to actually find this thing (and I didn't even include the "caesium 137-free" part....)

The thing that bothers me is that we put this assertion out there but I couldn't easily replicate it without a bunch of back and forth here. I don't want to have to explain that to someone who is trying to demonstrate how Arctos doesn't do what it says it can. If someone can create the search that matches

> a search for caesium 137-free large mammal fur or the distribution of mink in 1930

and has this record in the results, then we can say that and show someone how to do it, otherwise I cannot say this actually works with confidence.
