### ISSUE TITLE
How can I eliminate certain fields in my download that I removed in the initial search parameters?

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/arctos#2459]
** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **

** Outages should be reported to the contacts listed at https://arctosdb.org/arctos-down/ **

** Arctos Documentation is http://handbook.arctosdb.org/ **

** Learn more about Arctos at https://arctosdb.org/ **

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **

**Comment by mbprondzinski** [comment]
Another question:  Is it possible to get the date the record was entered to download?

**Comment by anna-chinn** [comment]
Hi Mary Beth, you can choose which fields appear in your download by adding/removing fields from your search results:
Select 'Add and Remove Data Fields' in the drop down menu:
![capture1](https://user-images.githubusercontent.com/40321380/72847070-6c084200-3c67-11ea-99f5-e018b5c897f8.png)
Hit save after selecting or deselecting the desired fields:
![capture2](https://user-images.githubusercontent.com/40321380/72847081-70345f80-3c67-11ea-96cf-c3c5ecb6eeb5.png)

There are certain basic fields that you cannot remove from your download, e.g. catalog number, locality, etc.

I took a quick look through the list of fields available to download, and it doesn't look like we have the option of adding date entered to the download (yet!).

**Comment by mbprondzinski** [comment]
Hi Anna,

Yes I do know that, but thanks.  However the fields I omitted in the search were the standard fields, which do show up in the download, ie. the coordinates fields, the country field, etc.  In this particular search I had hoped to eliminate those fields for downloading.  Can’t have everything!  Also, I discovered the person who did the search could not see who entered the record.  I presume one needs special permissions to see that?  His graduate student did the entry on some of the records, so I suppose that was what he was interested in knowing.

He also wanted the date of entry, but like you said, “we don’t have that capability YET!” ☺

Thank you for your response…

**Comment by campmlc** [comment]
Search on the grad student's agent name and go to agent activity. It will
show what records he's entered.
You can also do a search logged in on the bottom curatorial tab and search
for records entered by an agent. This can also be done for a certain date
or date range

**Comment by anna-chinn** [comment]
> Also, I discovered the person who did the search could not see who entered the record. I presume one needs special permissions to see that? His graduate student did the entry on some of the records, so I suppose that was what he was interested in knowing.

I believe that you need to be an Arctos operator to see and search on those data.

**Comment by mbprondzinski** [comment]
I see, okay, this is very helpful.  Thanks!

**Comment by campmlc** [comment]
And public users can search on agents using the Search drop-down at top
left of Arctos header.
