### ISSUE TITLE
Why can't I search on a common name? i.e. shark, ray, etc. 

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/arctos#2460]
** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **

** Outages should be reported to the contacts listed at https://arctosdb.org/arctos-down/ **

** Arctos Documentation is http://handbook.arctosdb.org/ **

** Learn more about Arctos at https://arctosdb.org/ **

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **

**Comment by campmlc** [comment]
Right now common names must be entered manually to each classification. We
had a committee at one point with the task of doing that. . .
We should prioritize some common taxa to enter. Perhaps in the Taxonomy
Committee?

**Comment by mbprondzinski** [comment]
I'll bring it up at the next meeting.  We had a "common name" field in our records before they were loaded into Arctos.  I've got an unhappy user who can't pull what he wants this way.

**Comment by Jegelewicz** [comment]
@mbprondzinski as discussed previously - those common names are currently in the identification remarks field because I haven't had time to add all of the to the taxon names.

See https://github.com/ArctosDB/data-migration/issues/61#issuecomment-510138530

**Comment by mbprondzinski** [comment]
Well, why can't there just be a dedicated field for common names?

**Comment by Jegelewicz** [comment]
There is! I just don't have the time to get all of your common names in right now...

**Comment by campmlc** [comment]
Have your upset researcher use Show More Options in Search and put "shark"
in ID remarks. I just got 2647 records.

**Comment by Jegelewicz** [comment]
I have to go to each taxon with a common name and edit to add it.

![image](https://user-images.githubusercontent.com/5725767/72824245-339a4100-3c32-11ea-95e2-2aee7e31d5ae.png)

**Comment by mbprondzinski** [comment]
Ha-ha-ha!  Well now that I know where to find it, I can tell him where to find it!  The confusing part of this is that the search page says search for "other identifiers, common names, etc." but that's not where he can find them by searching.  Instead he has to go to ID remarks...  I can't remember all this from month to month myself!

**Comment by mbprondzinski** [comment]
This is a good project for a volunteer!

**Comment by Jegelewicz** [comment]
> This is a good project for a volunteer!

Except that volunteer will have access to the SHARED taxonomy tables with the potential to make messes of a lot of data....they would need to be a VERY TRUSTED volunteer.

**Comment by mbprondzinski** [comment]
Don't worry, I only have two volunteers at the moment, and neither one of them will touch Arctos with a ten foot pole! ;-)

**Comment by campmlc** [comment]
One thing you could have volunteers do is compose a list of common names
matched to scientific names in Excel, especially those related to your
collections. Unless Teresa already has such a list . . .
Anyway, this would be the first step towards getting these loaded to the
taxon names.

**Comment by mbprondzinski** [comment]
That would be a good idea.  I'll see if Teresa has the list.

**Comment by Jegelewicz** [comment]
[ALMNH_Vert_Paleo_Common_Names.xlsx](https://github.com/ArctosDB/arctos/files/4093916/ALMNH_Vert_Paleo_Common_Names.xlsx)

Here is the list

@dustymc any chance you could add these common names to the taxa?

**Comment by mbprondzinski** [comment]
Great...thank you!

**Comment by dustymc** [comment]
Sure, but CSV please, and it would make it a bit easier if you could smoosh the columns down to one and repeat the taxon as necessary.

**Comment by Jegelewicz** [comment]
[ALMNH_Vert_Paleo_Common_Names.zip](https://github.com/ArctosDB/arctos/files/4094042/ALMNH_Vert_Paleo_Common_Names.zip)

No guarantee that these make a ton of sense. I am pretty sure that some don't. I was entering them manually because one of them was Canis = coyote which I don't think is a good idea (it has been removed from this file).

**Comment by dustymc** [comment]
Oh...

Glyptodon
armadillo

I don't have terribly strong opinions on this, but introducing that sort of data doesn't seem like a good idea to me either.

AWG agenda?

http://handbook.arctosdb.org/documentation/taxonomy.html#common-names

**Comment by campmlc** [comment]
We have a Taxonomy meeting tomorrow - add to that agenda?
