### ISSUE TITLE
Common Names

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2462]
"Common names" are a useful tool in the world of Paleontology.  All of our common names were lost when migrating into Arctos.  We need those to simplify searches.  I'm not a Paleontologist, so I don't know the taxonomy for sharks, but at the very least, I can search on the common name and pare it down...

**Comment by Jegelewicz** [comment]
See also #2460

**Comment by dustymc** [comment]
http://handbook.arctosdb.org/documentation/taxonomy.html#common-names

It would be good to have some direction/documentation here - what are we, or should we be, doing? 

People searching for coyotes probably don't want dogs and jackals. People searching armadillo probably don't want Glyptodon. People searching bird probably don't want turtles (the data that brought this up contains Reptilia|bird).

I'm not sure the current data are any less closely-associated, but I think/hope they might be. 

>..sharks, but at the very least, I can search on the common name and pare it down

You can do that if and only if "shark" is attached to every shark-term (Class to subspecies). If you don't have that, then you can search on common name to find the random things that DO carry that common name, and probably leave without finding most of what you want.

**Comment by Jegelewicz** [comment]
Everything that @dustymc said. I really don't have a solution here, but I will show everyone some concrete examples.

When I search taxonomy for the common name "shark" I get 86 taxa. The list includes these:

 Carcharodon auriculatus
Carcharodon carcharias
Carcharodon hastalis
Carcharodon hubbelli
Carcharodon megalodon 

but if I search taxonomy for the Taxon Name "Charcharodon" I get 56 taxa. If all of the species of Carcharodon are "sharks", then that common name should be added to them all if anyone is going to get anything meaningful when searching "Carcharodon". This is a simple enough fix IF we all agree that anything with the generic name "Carcharodon" is indeed a "shark", but I will pretty much guarantee that when a new species of Carcharodon is added, the common name "shark" won't be and we will be right back where we started with inconsistent data.

**Comment by Jegelewicz** [comment]
Now let's look at another side of this issue.

The ALMNH data includes 4 common names for Attenosaurus subulensis:

Taxon Name | Common Name
-- | --
Attenosaurus   subulensis | attennosaurus track
Attenosaurus subulensis | reptile tracks
Attenosaurus subulensis | tracks
Attenosaurus subulensis | vertebrate tracks

In the old database, it wasn't that all of these common names were attached to every instance of Attenosaurus subulensis, rather some records had the common name "vertebrate tracks" and some the common name "attennosaurus track". While all four common names may make sense, as with "shark" they need to be consistently applied if they are going to be useful.

**Comment by Jegelewicz** [comment]
Then there are the common names that are just not proper, as "coyote" = Canis and "armadillo" = Glyptodont.

In my humble opinion, the issue of common names needs to be worked on by a human who can consider the consequences of their application. That is why when I migrated the ALMNH data I did not put most of the common names in the "common name" field of the associated taxon, but instead left them in identification remarks. It is my bad that I just didn't do this for all of them and left a hodgepodge of some common names in ID remark and some in the "common name" field of the taxon, but I had hoped to get the common names in their proper place over time through a process of careful review and (hopefully) consistent application.

This may indeed be a job for a volunteer, but they must understand the taxonomy model and the implications for search and discoverability. I have volunteered a lot of time with this data and I just don't have the free time right now to give it the appropriate attention. It would be nice if we could pay someone to do this work - we should always be thinking of ways to pay people for their effort, especially when we expect decent results.

Sorry for the long-winded comments.

**Comment by Jegelewicz** [comment]
@dustymc here is a file I feel comfortable loading with a bunch of shark common names. I'll be working on these as time permits.
[ALMNH_shark_thru_D.zip](https://github.com/ArctosDB/arctos/files/4101149/ALMNH_shark_thru_D.zip)

**Comment by dustymc** [comment]
Done, here's the code, and it's in my 'taxonomy crusade'

```
-- insert common names, but only when everything works...
create table temp_ins_cn as select * from dlm.my_temp_cf;
alter table temp_ins_cn add tid number;
update temp_ins_cn set taxon_name=trim(taxon_name),common_name=trim(common_name);
update temp_ins_cn set tid=(select taxon_name_id from taxon_name where taxon_name.scientific_name=temp_ins_cn.taxon_name);
--made-up taxa
select * from temp_ins_cn where tid is null;
/*
TCarcharhinus melanopterus
Blacktip reef shark


Carcharhinus obsolerus
Lost shark
*/
delete from temp_ins_cn where tid is null;
-- already got one
select * from temp_ins_cn where (tid,common_name) in (select taxon_name_id,common_name from common_name);
--48 rows selected.
delete from temp_ins_cn where (tid,common_name) in (select taxon_name_id,common_name from common_name);
-- duplicates - ugh
select tid,common_name from temp_ins_cn having count(*)>1 group by tid,common_name;

insert into common_name (
  TAXON_NAME_ID,
  COMMON_NAME,
  COMMON_NAME_ID
) (
  select
    tid,
    common_name,
    sq_common_name_id.nextval
  from
    temp_ins_cn
    -- bah duplicates in the file!!
    where (tid,common_name) in (select tid,common_name from temp_ins_cn having count(*)=1 group by tid,common_name)
);

1223 rows created.

```

**Comment by Jegelewicz** [comment]
Added SQL to Write SQL Cheat Sheet.
