### ISSUE TITLE
Where to put Agent "received from" category?

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/arctos#2463]
** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **

** Outages should be reported to the contacts listed at https://arctosdb.org/arctos-down/ **

** Arctos Documentation is http://handbook.arctosdb.org/ **

** Learn more about Arctos at https://arctosdb.org/ **

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **

**Comment by campmlc** [comment]
It is in the Accession form:
[image: image.png]

**Comment by mbprondzinski** [comment]
This accession has hundreds of specimens attributed, but only 8 of them were given by this one particular agent.  Do I just put it in the record under specimen remarks or should I create a new accession?  They were already given the wrong original identifier that were given to other unrelated specimens.

**Comment by campmlc** [comment]
Accessions are up to curatorial discretion. You can either add a second
agent to the accession form ( or multiple agents), or you can choose to
move the specimens for a particular agent to a new accession. This is easy
to do - just search on the specimens you want to move, go to manage,
accessions, and move all to new accession number (must create the new
accession first.)
http://handbook.arctosdb.org/how_to/How-to-Batch-Update-Accessions.html

**Comment by mbprondzinski** [comment]
Thanks, I'll have to think about this one.
