### ISSUE TITLE
Select parts for Bulk Modify Part tool - exclude subsamples

### ISSUE THREAD

**Issue by KyndallH** [ArctosDB/arctos#2465]
I have a jar full of frogs - no barcode on frogs. I want to add them to the jar - jar has a barcode. How do I go about that in bulk? I thought I could do it under Bulk Modify Parts but apparently, I can't. 

<img width="1033" alt="Screen Shot 2020-01-23 at 9 18 59 AM" src="https://user-images.githubusercontent.com/16887896/73011778-6c1c5500-3dc1-11ea-8433-c5c88255ff33.png">
<img width="1895" alt="Screen Shot 2020-01-23 at 9 17 21 AM" src="https://user-images.githubusercontent.com/16887896/73011783-6d4d8200-3dc1-11ea-8d21-1b2e855728ea.png">

**Comment by KyndallH** [comment]
Figured it out! Found a bulkloader that may work.

**Comment by KyndallH** [comment]
Flaw to all of this. 
A handful of them say "item not found".
<img width="2459" alt="Screen Shot 2020-01-23 at 9 56 20 AM" src="https://user-images.githubusercontent.com/16887896/73014509-c9ff6b80-3dc6-11ea-93e6-340c8975cf30.png">

I'm assuming that is because some of them have been subsampled for a loan.
<img width="1201" alt="Screen Shot 2020-01-23 at 9 57 22 AM" src="https://user-images.githubusercontent.com/16887896/73014522-ce2b8900-3dc6-11ea-867c-90d074c8855c.png">

Is there another way to do this? Could we add "barcode" to modify parts since it has the disposition there? Or disposition onto the Parts >> Container bulkloader file?

**Comment by Jegelewicz** [comment]
Whenever there are two parts with the same name, Arctos doesn't know which one to assign the barcode to. I always just did those manually.

**Comment by campmlc** [comment]
If there are two parts with the same name, and one is a subsample, can we
have the option of only adding barcodes to parts that are not subsamples?

**Comment by Jegelewicz** [comment]
A lot of this won't apply to your situation, but it might be useful anyway.
[Conversion Bulkload Parts to Barcodes.docx](https://github.com/ArctosDB/arctos/files/4109056/Conversion.Bulkload.Parts.to.Barcodes.docx)

**Comment by KyndallH** [comment]
@campmlc  YES! So somehow exclude subsamples.

I was trying to think of other times beyond subsamples that you'd duplicate parts from one record that needs to get moved into one container. 

@Jegelewicz Yeah, I'll do it manually this time but in the future, it would be AWESOME if I didn't have to do it manually. We also need to get these kinds of documents in the handbook - I have some that I should share too. I really find it helpful to workflows from other institutions.

**Comment by campmlc** [comment]
@Dusty <dustymc@gmail.com>

**Comment by Jegelewicz** [comment]
@dustymc the problem here started with the fact that subsampling for loans creates a part with exactly the same name as the existing part, when @KyndallH subsamples muscle from a frog it creates a subsample that is "whole organism" when all she sent was muscle. It would be nice to be able to give subsampled parts a new part name at the time the loan is created.

**Comment by dustymc** [comment]
I think this is all in the current loader
