### ISSUE TITLE
Get bad username  	Unable to add ktetamore_dmns as an Arctos User

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#2467]
Unable to figure out what's wrong with the agent and user profile for Katarzina Tetamore, Arctos Username ktetamore_dmns.

**Comment by Jegelewicz** [comment]
Username must inlcude only letters and numbers (ASCII characters A-Z, a-z, and 0-9), and cannot begin with a number.

The underscore is the problem.

**Comment by sharpphyl** [comment]
All of our volunteers have had underscores for several years.  When did the underscore become a problem?

**Comment by sharpphyl** [comment]
Ok, can you delete the profile for ktetamore_dmns so I can create a new one without the "_dmns."
--

**Comment by Jegelewicz** [comment]
I cannot - just create a new one!

**Comment by sharpphyl** [comment]
I did but it won't let me add her name and email.  They are in her Arctos agent, but I think she needs to add them in her profile, so let's wait for a few days and see if it resolves itself.  Thanks!

**Comment by campmlc** [comment]
Yes, she needs to add her name and email. The other option is for you to
create a username for her using your email in the profile, add the new
login to her agent profile, set her up as an operator, and then just have
her go in and change the email and her password when all is set up.

**Comment by sharpphyl** [comment]
Good suggestion.  I'll use that if I have trouble in the future.  She just updated her profile on the new login (without an underscore) so we're all set.  I'll close this.  Thanks for your help.
