### ISSUE TITLE
Can't do a "Keyword" Media search for linked records.  First I tried it without logging in.  Then I tried it logged in.  What exactly is considered a "Keyword"?  Title, Author, Journal?

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/arctos#2468]
** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **

** Outages should be reported to the contacts listed at https://arctosdb.org/arctos-down/ **

** Arctos Documentation is http://handbook.arctosdb.org/ **

** Learn more about Arctos at https://arctosdb.org/ **

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **

**Comment by Jegelewicz** [comment]
Can you provide a screen shot or something to help me understand what you are trying to do?

**Comment by mbprondzinski** [comment]
![image](https://user-images.githubusercontent.com/43214224/73078378-ad773800-3e87-11ea-8bb7-1f28e7523512.png)

I know there are at least a hundred records attached to a particular publication, none of which I can pull up.

**Comment by Jegelewicz** [comment]
Do all these media have the keyword "Chondrichthyes" associated with them? This form is searching the media.

I think you would have better luck finding the publication, which should then show you the associated media (assuming the media have been associated).

What is the publication?

**Comment by Jegelewicz** [comment]
Keywords are words in any of the media fields:
![image](https://user-images.githubusercontent.com/5725767/73078897-6cc7f080-3e80-11ea-9d6e-cac75d1e7353.png)

It is a bit like searching "any taxonomy" an probably likely to time out because it is searching everything. A more targeted search will hlep.

**Comment by mbprondzinski** [comment]
I am trying to pull all the records that I have spent DAYS linking to the Ebersole J et al 2019 publication in the European Journal of Taxonomy.  I need to have their location in the collection so I can match their count numbers with the data sheet that was given to me by Ebersole.

**Comment by Jegelewicz** [comment]
https://arctos.database.museum/publication/10008972

**Comment by Jegelewicz** [comment]
Click on the "87 specimens"
![image](https://user-images.githubusercontent.com/5725767/73079256-1ad39a80-3e81-11ea-8d7d-1a9b75a0444e.png)

**Comment by mbprondzinski** [comment]
I tried words from the title of the article, the author, the Journal name.

**Comment by mbprondzinski** [comment]
That will work, as long as it pulls up all the records.  But I was trying it from the search page because I thought it would be easy to pull all those records if I was someone who wasn't familiar with Arctos.

**Comment by Jegelewicz** [comment]
It would help you to create a project for this.

All of these should be added to a loan (because they were borrowed for use in creating this pub - whether or not they ever left your facility), then you create a project from the loan.

I also recommend that in the future you don't need to add the publication text media to every record. Just attach it to the publication. Because these are all cited in the pub, they are linked to the media through the citation.

**Comment by Jegelewicz** [comment]
Watch this! [Projects, Publications, and Citations in Arctos](https://www.youtube.com/watch?v=aLCC-SI1-RI&feature=youtu.be)

**Comment by mbprondzinski** [comment]
Oh Teresa, you missed the whole thing with Dusty telling me that the publication was not cited properly and couldn't be linked!  I had to do it manually.  I did create a loan.  Many of the specimens were never entered into the database but were given numbers.  I have yet to deal with those.  These are only the few specimens that ARE in the database.   They are cited with dropped leading zeros, so Arctos couldn't find them.  Jun also created new numbers which I have no idea if they are associated with the "new" specimen IDs or if it something that only exists in his spreadsheet.

**Comment by Jegelewicz** [comment]
> easy to pull all those records if I was someone who wasn't familiar with Arctos

A project will REALLY help with that because you can just give people a link to the project page.

> I did create a loan

But these things aren't in the loan as far as I can tell. https://arctos.database.museum/guid/ALMNH:ES:1947 shows no loan history.

If you go to that record and select the citation hot link:
![image](https://user-images.githubusercontent.com/5725767/73080271-cb8e6980-3e82-11ea-8943-deca797de97c.png)

it takes you to the publication and from there you can see the media.
![image](https://user-images.githubusercontent.com/5725767/73080348-e9f46500-3e82-11ea-9790-02cdff8d181c.png)

You don't need to attach that media to every specimen, just the citation.

**Comment by Jegelewicz** [comment]
> I tried words from the title of the article, the author, the Journal name.

Some of that would work in the search project/publication form. This brought me right to it:

![image](https://user-images.githubusercontent.com/5725767/73080709-83bc1200-3e83-11ea-991a-7fe2a2f0cf69.png)

**Comment by mbprondzinski** [comment]
Right, but it doesn't work on the search page!  There needs to be a manual on what works where and what doesn't.  As for adding the media to each record, I didn't know I didn't have to do that. ..how would I?!

**Comment by mbprondzinski** [comment]
I created a loan, but I haven't added anything to it.  It's been challenging enough wading through the spreadsheet I received after -the-fact.  Some of the assigned numbers had already been assigned to other specimens.

**Comment by Jegelewicz** [comment]
I just added the labels "shark" and "Chondrichthyes" to the media.

![image](https://user-images.githubusercontent.com/5725767/73080954-ef9e7a80-3e83-11ea-9eb3-878016a36bd5.png)

Now search media label "subject" for Chondrichthyes.

![image](https://user-images.githubusercontent.com/5725767/73081368-b581a880-3e84-11ea-88fa-13ad190de098.png)

**Comment by Jegelewicz** [comment]
> Right, but it doesn't work on the search page! There needs to be a manual on what works where and what doesn't. As for adding the media to each record, I didn't know I didn't have to do that. ..how would I?!

Probably no way to just "know". Reading documentation or asking here is a great way to start. Let me help you out with this. Give me an hour to set it up and hopefully that will help.

Here is a helpful video.

[Projects, Publications, and Citations in Arctos](https://www.youtube.com/watch?v=aLCC-SI1-RI&feature=youtu.be)

**Comment by mbprondzinski** [comment]
Thanks Teresa, but I have to spend the next three hours with a volunteer who is going to help me go through these specimens in the collection to figure out what "Ebersole" was doing!!

I DO read all the documentation I can find, but it isn't always available where you might expect it to be.  There is just A LOT, and I can't remember everything that I've read, especially when I don't use that feature regularly.  For example:  I still don't understand how the bulk-loader works.  I'm clicking buttons and hoping stuff will validate, but as for the exact order of things...that is elusive.  The explanation is not straightforward enough.  Eventually, my stuff gets through, but I never can tell if there is some other button I need to click!

I probably won't get back to this until next week...or later today.

**Comment by Jegelewicz** [comment]
Here is your [project](https://arctos.database.museum/project/10003313). I added all specimens with the part "tooth" to the loan, but you can remove any that shouldn't be there. Just let me know if you need help with that. You can also add the rest of the stuff as you figure it out.

I am very sorry that you are getting frustrated and I wish I could do more to make the documentation better and easier to find. I try to do what I can when I can. Always feel free to ask questions here.

**Comment by mbprondzinski** [comment]
Thanks so much for doing that, Teresa!  Yes, I am frustrated.  The “new volunteer” didn’t show up so I’m still waiting for someone to physically help me go through the collection to figure out those teeth.  I now have a “computer on wheels” in the collection which will help me expedite all the corrections in Arctos. … it’s just finding the time to do it all.

**Comment by dustymc** [comment]
The guidance at http://handbook.arctosdb.org/documentation/media.html#media-creation-guidelines - "Create only necessary relationships; allow the relational nature of Arctos to work for you." - is relevant everywhere.

The publication<--->identification relationship is the critical component of this; that creates citations.

The publication<-->media relationship makes the publication text readily available, but for this one the publication<---->DOI relationship provides a PDF copy. I'd have added the Media if I had a copy handy, just in case the publisher decides to be weird, but that's a convenience and not critical or something that changes the nature of the data.

The publication should be explicitly added to the project (and that'll bring along the publication media - there's no reason to explicitly add it). I added the publication to the project.

There are no other necessary or desirable links in this.

The Media will round up certain keyworks from attached objects and those MIGHT provide a way to find stuff, but that's very secondary. Most Media are metadata, not data, from almost all viewpoints in Arctos. 

My earlier comments were only that I couldn't automate the citations - specimens weren't cited in some format (URL-GUID, DOI, Archive as URL or DOI, etc.) that could be used in automation, it's going to take a person to "translate" them. That's normal - I think we've had a couple publications where things like copy-pasting from a table was possible, but I'm not aware of a single publication containing unambiguous (and therefore automatable) references to specimens.
