### ISSUE TITLE
Request for Public Comment on Draft Desirable Characteristics of Repositories

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#2469]
I am writing to direct your attention to a new Request for Public Comment (RFC) on Draft Desirable Characteristics of Repositories for Managing and Sharing Data Resulting from Federally Funded Research: https://www.federalregister.gov/documents/2020/01/17/2020-00689/request-for-comments-draft-desirable-characteristics-of-repositories-for-managing-and-sharing-data.

 

The White House Office of Science and Technology Policy is issuing this RFC on behalf of the multi-agency Subcommittee on Open Science of the National Science and Technology Council’s Committee on Science. The proposed set of desirable characteristics is part of the Subcommittee’s efforts to improve the consistency of information that Federal agencies provide to the scientific community about the long-term preservation of data resulting from Federally funded research. The characteristics could apply to repositories operated by government or non-governmental entities.

 

Feedback will help the Subcommittee refine and develop a common set of characteristics that Federal research funding agencies can use to support ongoing efforts to improve the management and sharing of data from Federally funded research.  To ensure your comments will be considered, please submit your response before 11:59 PM ET on Friday, March 6, 2020.

 

Thank you.

 

Best,

 

Dina N. Paltoo, Ph.D., M.P.H.

Assistant Director for Policy Development

Office of the Director, U.S. National Library of Medicine, National Institutes of Health

8600 Rockville Pike

Building 38, Room 2N21

Bethesda, MD 20894

 

Office: 301.827.4377│Mobile: 240.383.7817│FAX: 301.496.4450

Email:  dina.paltoo@nih.gov

**Comment by dustymc** [comment]
The comment period for this is closing.

/remind me to close this in two days

**Comment by Jegelewicz** [comment]
I wish that we had the time and bandwidth to have sent in an Arctos response. I think all of the recommendations are great, but as always the issue of how any given repository will fund managing the data in perpetuity is not considered.
