### ISSUE TITLE
Help: account locked after password change! 

### ISSUE THREAD

**Issue by jtgiermakowski** [ArctosDB/arctos#2470]
Help! 

I changed my **password** and now the account is **locked**. Can someone please unlock it?

Thanks,
Tom

** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **

** Outages should be reported to the contacts listed at https://arctosdb.org/arctos-down/ **

** Arctos Documentation is http://handbook.arctosdb.org/ **

** Learn more about Arctos at https://arctosdb.org/ **

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **

**Comment by jtgiermakowski** [comment]
OK, Mariel helped, thanks!

**Comment by jtgiermakowski** [comment]
Didn't work!

after changing password the screen shows conflicting info, see attached.
![Password-woes](https://user-images.githubusercontent.com/2381228/73282059-2a6b2000-41ae-11ea-9856-8eadb477117e.png)

**Comment by dustymc** [comment]
It's unlocked and you should have a new password in your email.

**Comment by campmlc** [comment]
Sorry - I unlocked a different account under your name.

**Comment by jtgiermakowski** [comment]
Thanks @dustymc but I don't see anything in my email. I checked spam and other accounts.

**Comment by campmlc** [comment]
I see that the account says open and active. What is the login?

**Comment by dustymc** [comment]
>email

Gmail seems to delay messages from Arctos for some reason - I forwarded the copy from the logs.

@campmlc I always go through the agent for this sort of thing, after having tried to manage various user's OTHER accounts a few times....

**Comment by jtgiermakowski** [comment]
OK, Thanks @dustymc and @campmlc ! I think it is working fine now. After updating the password I got the strange message above (logged in but had profile info with account locked). 

@dustymc UNM email filtering might be responsible too, we miss messages often. Thanks.
