### ISSUE TITLE
China higher geography needs review and clean-up

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2471]
> My data say, simply, "Menglun, Yunnan, China" on the tag and I believe Menglun is a town within Xishuangbanna Prefecture, but it is also within the County of Mengla. Would you think that is the same higher geography as above, or provide a level of specificity further?

I would use "Xishuangbanna Dai Autonomous Prefecture" and put Mengla County in specific locality. 

China looks like a bit of a mess - three of the Yunnan geographies were spelled "Yunaan"! I corrected those, but the higher geography in China really has 4 levels instead of three and all of their "counties" are prefectures or "cities" (meaning city prefectures). I'm going to put this in the main repository for consideration when someone working in China has time to take a good look at it.

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/data-migration/issues/149#issuecomment-579327965_

**Comment by sharpphyl** [comment]
I agree China can be a mess, partly because translating from Chinese characters to Pinyin to English often results in multiple interpretations.  If anyone has special knowledge of Chinese geography, that would be great.

**Comment by Jegelewicz** [comment]
I cleaned up provinces/municipalities/autonomous regions closing for lack of interest
