### ISSUE TITLE
Rousettus leschenaulti should be Rousettus leschenaultii

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2473]
An update:
Rousettus leschenaulti (on Arctos) should have two i's (Rousettus leschenaultii), Desmarest 1820. https://en.wikipedia.org/wiki/Leschenault%27s_rousette

_Originally posted by @diannakrejsa in https://github.com/ArctosDB/data-migration/issues/98#issuecomment-578377500_

@dustymc can you fix this as well as Rousettus leschenaulti leschenaulti which should be Rousettus leschenaultii leschenaultii

**Comment by dustymc** [comment]
I don't think there's anything to fix. My scripts will eventually find these and create a "potential alternate spelling" relationship.

Collections can indication preferences using preferred_name.

The one-i variation is in the literature - https://www.ncbi.nlm.nih.gov/pubmed/8655399

http://handbook.arctosdb.org/documentation/taxonomy.html#overview

**Comment by Jegelewicz** [comment]
OK we will just keep perpetuating the problem!

Rousettus leschenaultii created with potential alternate spelling relationship added.

**Comment by diannakrejsa** [comment]
I'm basing my species spellings off of ASM's mammal database, published under Burgin et al. 2018 (https://academic.oup.com/jmammal/article/99/1/1/4834091), but it is continually updated here (https://mammaldiversity.org/) and says to cite it at time of download, which is 2020 for now. Are newer pubs dictating what the spelling should be?

<img width="526" alt="Screen Shot 2020-01-28 at 10 48 27 AM" src="https://user-images.githubusercontent.com/36166607/73285636-ef6fe900-41bb-11ea-93e3-7cba8de7caeb.png">
That aside, I get an error for spelling it with two i's, so I would have to change records to one i, then go in and indicate the preferred name? Seems like extra work for a flexible/potentially outdated spelling, can alternate spellings be acceptable to the bulkloader without errors? 

I noticed this on agents as well; even if the Arctos agent had an aka that matched my bulkload record, it errored and I had to change records to the preferred name displayed on Arctos, even if it has an aka that may have more data (a complete first name, for example).

**Comment by Jegelewicz** [comment]
I added the correct spelling - see your issue in data migration.

**Comment by diannakrejsa** [comment]
Apologies! Rousettus leschenaultii through when I submitted again, I'd just tried it too soon.

**Comment by dustymc** [comment]
>Are newer pubs dictating what the spelling should be?

In Arctos, no (at least not from my perspective). A user coming from a publication/web page/whatever that uses the "bad" spelling should still find specimens, if possible. That is, we're addressing the reality, not perpetuating the problem.

>can alternate spellings be acceptable to the bulkloader without errors?

Yes, the big question is if it SHOULD work that way (probably not), and if not how do we get there (not a clue!). New Issue.....

>agents

Agents are a very different type of data and therefore have been modeled very differently. Arctos should accept any name that unambiguously identifies a single agent record.
