### ISSUE TITLE
What is the "clone" feature on the Part Table

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#2474]
We were wondering what the clone feature is used for in the Parts table and how it is differentiated from subsample. Initially we thought it might be a "carry over" input tool, but it seems to do the same task as the subsample button, e.g. create a new subsample child part from a parent. There does not seem to be any documentation regarding this option.

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
"Subsample" populates SPECIMEN_PART.SAMPLED_FROM_OBJ_ID with the ID of the "source" part. "Clone" does not; that remains NULL, the parts are independent. Otherwise they're identical.

**Comment by ebraker** [comment]
Thanks. To clarify, populating of SPECIMEN_PART.SAMPLED_FROM_OBJ_ID with the source part ID happens/is stored somewhere on the back end? Front end clone vs. subsample creation look identical:
![image](https://user-images.githubusercontent.com/11336485/73312282-90bf6500-41e5-11ea-943f-19f91bb22872.png)

**Comment by dustymc** [comment]
You could have made the first part in your table by 'clone' - it's attached only to the catalog record, not attached to any other parts, is in no hierarchy. It's just a part.

You could have made the second two by 'subsample' from the first. They're both children of the first row, can't be deleted without deleting their parent first, define a relationships between parts, are in a hierarchical relationship with the 'donor' part, etc.

IF you'd have clicked 'subsample' from the second part, the third would be derived from it (and so inset under it in the UI), and all of the above would apply directly to the relationship between (3) and (2), and indirectly between (3) and (1). There's no limit to the hierarchy, or the number of parts which can be sampled from samples of samples of ... In that case, your table would look like...

--(1)
----(2)
------(3)

I'm guessing by the remark that you cloned (3) from (2), which also cloned parentage. If you'd have made (3) by cloning (1) your table/hierarchy would look like...

--(1)
----(2)
--(3)

**Comment by ebraker** [comment]
That makes sense. Given this, I think the display is not properly depicting the hierarchy. In my example above, (1) is my preexisting part, (2) I cloned from (1), and (3) I subsampled from (1). I also replicated your last example scenario and reproduced the same hierarchy. Cloning prompts a child relationship to the Part and creates a subpart with the "subsampled from ####" text, so I believe it is doing the exact task of subsample rather than creating a separate non-heirarchical part.

**Comment by dustymc** [comment]
Oh nice...

**Comment by ebraker** [comment]
:) Thus explains my confusion...

**Comment by dustymc** [comment]
fixed and patched in

**Comment by ebraker** [comment]
Thanks!
