### ISSUE TITLE
Pulling Related Specimen Data into Specimen Record

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2477]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
The pull function to bring in related IDs taxon name, locality, and date fields across collections into the specimen page via other Ids is not working. We have  a conference in February that will require demo of this feature.  Is this waiting for PG?

**Priority**
Please assign a priority-label.
[MSB_Para_29361_ Phthiraptera.pdf](https://github.com/ArctosDB/arctos/files/4131362/MSB_Para_29361_.Phthiraptera.pdf)

**Comment by dustymc** [comment]
Please see https://github.com/ArctosDB/arctos/issues/new?assignees=&labels=&template=bug_report.md&title=

I don't know what's going on from the information you've provided. AFAIK this works fine so I'm guessing something about your browser??

Assigning priority is The Community's job.

**Comment by Jegelewicz** [comment]
> We have a conference in February that will require demo of this feature.

Makes it High Priority

**Comment by dustymc** [comment]
I may have just accidentally discovered what you're talking about! The related cache in specimenresults, not the pull from data entry, correct?

I believe https://github.com/ArctosDB/arctos/issues/2278 has broken that as well; I'll comment there.

**Comment by dustymc** [comment]
Assuming this is all happy now....

**Comment by campmlc** [comment]
Yes, thank you!!
