### ISSUE TITLE
GloBI data review - unresolved links

### ISSUE THREAD

**Issue by jhpoelen** [ArctosDB/arctos#2480]
Hey Arctos community - 

I am trying to figure out how GloBI can help provide useful data review reports. The idea is for GloBI to be a friendly neighbor that provides some review notes about collections, in this case, Arctos. 

Just today, a review report was generated via https://travis-ci.org/globalbioticinteractions/vertnet (note that only Arctos related collections are extracted from Vertnet for now). See attached. 

[arctos-review-2020-01-31.tsv.gz](https://github.com/ArctosDB/arctos/files/4140431/arctos-review-2020-01-31.tsv.gz)

From that, I created the attached list of 747 unresolved links applying the linux command-line magic:

```zcat arctos-review-2020-01-31.tsv.gz | grep "target taxon name missing" | cut -f15 | jq -c '.context | { sourceOccurrenceId, targetOccurrenceId}' | jq -r '(map(values) | @csv)' | gzip > arctos-review-2020-01-31-unresolved-links.csv```

[arctos-review-2020-01-31-unresolved-links.csv.gz](https://github.com/ArctosDB/arctos/files/4140463/arctos-review-2020-01-31-unresolved-links.csv.gz)

At a quick glance, I was able to see that GloBI should support to resolve links to iNaturalist (e.g., http://www.inaturalist.org/observations/9523714 see related issue https://github.com/globalbioticinteractions/globalbioticinteractions/issues/455) and NCBI (e.g., http://www.ncbi.nlm.nih.gov/nuccore/HQ189781.1 related issue https://github.com/globalbioticinteractions/globalbioticinteractions/issues/440) .

However, some 339 Arctos-to-Arctos links remain unresolved (
[arctos-review-2020-01-31-unresolved-arctos-arctos-links.csv.gz](https://github.com/ArctosDB/arctos/files/4140515/arctos-review-2020-01-31-unresolved-arctos-arctos-links.csv.gz) ). The first 50 of those are listed below. 

Please let me know:
1. whether these unresolved links are expected
2. if/how to best keep reporting on this to you, ideally in an automated fashion? 

Note that you can regenerate the full review using https://github.com/globalbioticinteractions/elton , a command-line tool, using the command: ```elton update globalbioticinteractions/vertnet && elton review --type note globalbioticinteractions/vertnet```.  Also, reports are available via https://travis-ci.org/globalbioticinteractions/vertnet .

source arctos record | target arctos record
-- | --
http://arctos.database.museum/guid/UAM:Mamm:79858?seid=614516 | http://arctos.database.museum/guid/UAM:Ento:277936
http://arctos.database.museum/guid/UAM:Mamm:80352?seid=1693847 | http://arctos.database.museum/guid/UAM:Ento:281979
http://arctos.database.museum/guid/UAM:Mamm:84035?seid=1531210 | http://arctos.database.museum/guid/UAM:Ento:281350
http://arctos.database.museum/guid/UAM:Mamm:93035?seid=1750634 | http://arctos.database.museum/guid/UAM:Ento:281845
http://arctos.database.museum/guid/UAM:Mamm:80313?seid=1235592 | http://arctos.database.museum/guid/UAM:Ento:280227
http://arctos.database.museum/guid/UAM:Mamm:79842?seid=1464923 | http://arctos.database.museum/guid/UAM:Ento:280410
http://arctos.database.museum/guid/UAM:Mamm:79854?seid=784846 | http://arctos.database.museum/guid/UAM:Ento:278192
http://arctos.database.museum/guid/UAM:Mamm:84195?seid=222804 | http://arctos.database.museum/guid/UAM:Ento:276639
http://arctos.database.museum/guid/UAM:Mamm:80387?seid=398665 | http://arctos.database.museum/guid/UAM:Ento:277250
http://arctos.database.museum/guid/UAM:Mamm:80385?seid=198632 | http://arctos.database.museum/guid/UAM:Ento:276509
http://arctos.database.museum/guid/UAM:Mamm:80381?seid=348603 | http://arctos.database.museum/guid/UAM:Ento:277124
http://arctos.database.museum/guid/UAM:Mamm:80376?seid=1771065 | http://arctos.database.museum/guid/UAM:Ento:282116
http://arctos.database.museum/guid/UAM:Mamm:80621?seid=1781406 | http://arctos.database.museum/guid/UAM:Ento:282002
http://arctos.database.museum/guid/UAM:Mamm:80622?seid=979490 | http://arctos.database.museum/guid/UAM:Ento:279524
http://arctos.database.museum/guid/UAM:Mamm:84053?seid=248987 | http://arctos.database.museum/guid/UAM:Ento:276686
http://arctos.database.museum/guid/UAM:Mamm:84413?seid=370528 | http://arctos.database.museum/guid/UAM:Ento:276787
http://arctos.database.museum/guid/UAM:Mamm:80625?seid=1630998 | http://arctos.database.museum/guid/UAM:Ento:282086
http://arctos.database.museum/guid/UAM:Mamm:84409?seid=498798 | http://arctos.database.museum/guid/UAM:Ento:277819
http://arctos.database.museum/guid/UAM:Mamm:83859?seid=686517 | http://arctos.database.museum/guid/UAM:Ento:278467
http://arctos.database.museum/guid/UAM:Mamm:84308?seid=1786101 | http://arctos.database.museum/guid/UAM:Ento:281803
http://arctos.database.museum/guid/UAM:Mamm:84310?seid=1502608 | http://arctos.database.museum/guid/UAM:Ento:281132
http://arctos.database.museum/guid/UAM:Mamm:83759?seid=165657 | http://arctos.database.museum/guid/UAM:Ento:276275
http://arctos.database.museum/guid/UAM:Mamm:84305?seid=392098 | http://arctos.database.museum/guid/UAM:Ento:276978
http://arctos.database.museum/guid/UAM:Mamm:12188?seid=531643 | http://arctos.database.museum/guid/USNPC:Para:346
http://arctos.database.museum/guid/UAM:Mamm:80628?seid=686668 | http://arctos.database.museum/guid/UAM:Ento:277901
http://arctos.database.museum/guid/UAM:Mamm:84390?seid=420415 | http://arctos.database.museum/guid/UAM:Ento:276919
http://arctos.database.museum/guid/UAM:Mamm:83764?seid=1716216 | http://arctos.database.museum/guid/UAM:Ento:282148
http://arctos.database.museum/guid/UAM:Mamm:83861?seid=280077 | http://arctos.database.museum/guid/UAM:Ento:276889
http://arctos.database.museum/guid/UAM:Mamm:80404?seid=1310213 | http://arctos.database.museum/guid/UAM:Ento:280839
http://arctos.database.museum/guid/UAM:Mamm:80418?seid=894994 | http://arctos.database.museum/guid/UAM:Ento:278989
http://arctos.database.museum/guid/UAM:Mamm:80405?seid=1519366 | http://arctos.database.museum/guid/UAM:Ento:281046
http://arctos.database.museum/guid/UAM:Mamm:80408?seid=610321 | http://arctos.database.museum/guid/UAM:Ento:277970
http://arctos.database.museum/guid/UAM:Mamm:80399?seid=75328 | http://arctos.database.museum/guid/UAM:Ento:276109
http://arctos.database.museum/guid/UAM:Mamm:80402?seid=774806 | http://arctos.database.museum/guid/UAM:Ento:278187
http://arctos.database.museum/guid/UAM:Mamm:80421?seid=1603912 | http://arctos.database.museum/guid/UAM:Ento:281212
http://arctos.database.museum/guid/UAM:Mamm:80406?seid=1603913 | http://arctos.database.museum/guid/UAM:Ento:281213
http://arctos.database.museum/guid/UAM:Mamm:84287?seid=824088 | http://arctos.database.museum/guid/UAM:Ento:279043
http://arctos.database.museum/guid/UAM:Mamm:84263?seid=865608 | http://arctos.database.museum/guid/UAM:Ento:278735
http://arctos.database.museum/guid/UAM:Mamm:88461?seid=702772 | http://arctos.database.museum/guid/UAM:Ento:278407
http://arctos.database.museum/guid/UAM:Mamm:84371?seid=1656782 | http://arctos.database.museum/guid/UAM:Ento:281760
http://arctos.database.museum/guid/UAM:Mamm:84370?seid=206225 | http://arctos.database.museum/guid/UAM:Ento:276418
http://arctos.database.museum/guid/UAM:Mamm:84374?seid=544441 | http://arctos.database.museum/guid/UAM:Ento:277460
http://arctos.database.museum/guid/UAM:Mamm:84341?seid=648357 | http://arctos.database.museum/guid/UAM:Ento:277988
http://arctos.database.museum/guid/UAM:Mamm:84330?seid=883755 | http://arctos.database.museum/guid/UAM:Ento:279512
http://arctos.database.museum/guid/UAM:Mamm:84338?seid=669703 | http://arctos.database.museum/guid/UAM:Ento:278168
http://arctos.database.museum/guid/UAM:Mamm:84189?seid=380160 | http://arctos.database.museum/guid/UAM:Ento:276903
http://arctos.database.museum/guid/UAM:Mamm:84065?seid=563126 | http://arctos.database.museum/guid/UAM:Ento:277798
http://arctos.database.museum/guid/UAM:Mamm:84178?seid=1823584 | http://arctos.database.museum/guid/UAM:Ento:282301
http://arctos.database.museum/guid/UAM:Mamm:84104?seid=1132275 | http://arctos.database.museum/guid/UAM:Ento:280219
http://arctos.database.museum/guid/UAM:Mamm:84096?seid=154623 | http://arctos.database.museum/guid/UAM:Ento:276387

fyi @seltmann

**Comment by dustymc** [comment]
@DerekSikes
