### ISSUE TITLE
WKT's for New Mexico Counties

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2481]
I have a request for WKTs for New Mexico counties. Specific localities are

XXX County (no specific locality) with HG = North America, United States, New Mexico, XXX County

would love to have a lot of NMMNH Paleo public records mappable!

**Comment by mkoo** [comment]
I thought that this sounded familiar... do you mean like this?
https://arctos.database.museum/editLocality.cfm?locality_id=10148106  for
Bernalillo Co?

I searched on Localities where HG = New Mexico and SpecLoc= (no specific
locality)
and came up with a bunch. Please let me know if I missed any counties!

**Comment by Jegelewicz** [comment]
These are all using our agreed-upon spec loc for wkts

> XXX County (no specific locality)

Where the XXX is the county name. So not just (no specific locality)

**Comment by Jegelewicz** [comment]
I was expecting to see this one mapped: https://arctos.database.museum/guid/NMMNH:Paleo:10095

**Comment by Jegelewicz** [comment]
So Guadalupe County
also Quay County

**Comment by Jegelewicz** [comment]
UGH - there are probably a lot of new ones because of geology! Any way that these can get the wkts automatically?

**Comment by mkoo** [comment]
https://arctos.database.museum/editLocality.cfm?locality_id=11056554 -
Guadalupe

https://arctos.database.museum/editLocality.cfm?locality_id=11056555 -Quay

Sorry I dont know how I missed these for NM!

this was easy since the wkts are already in Arctos-- are there any without
wkt/ good higher geography?

**Comment by mkoo** [comment]
note: just added the same coordinates+error to the paleo locality since the
Geology info is additional info not in the other locality for the county

**Comment by Jegelewicz** [comment]
/remind me to check this on Monday

**Comment by Jegelewicz** [comment]
Also Rio Arriba County

**Comment by Jegelewicz** [comment]
I think we need to discuss this at a Geography Team meeting - I'm not sure I understand how this is working and I want to make sure I know what I need to do in order to be able to make use of the "county wkts".

**Comment by mkoo** [comment]
yes, we can have one of those-- we're also uploading the Canada provinces
soon too

**Comment by campmlc** [comment]
Do you guys know about VertNets verified localities? Includes higher geog
From Dave Bloom

**Comment by Jegelewicz** [comment]
I'm closing this because of #3272
