### ISSUE TITLE
Is there a report for "total # images in collection"?

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#2483]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
I'm compiling my annual report data. Is there a way to query how many total image files I have uploaded for my collection?

** Describe what you're trying to accomplish** 
A data reporter that would allow me to easily find the total number of images (or media files) I have created over a designated date range.

In years past I simply search media by agent to see how many each person has created... getting harder to get a decent number.

**Priority**
Medium (I need to post annual report data by 2020-02-14 but can guess if there's not an easy way to create this tool by then).

**Comment by dustymc** [comment]
Short answer: no, we don't track "uploads," and Media doesn't necessarily involve uploading. (There's an Issue involving what we SHOULD be tracking out there somewhere...)

Probably close enough answer: reports/writeSQL, then

```
select media_type,count(distinct(media.media_id)) from media, media_relations where media.media_id=media_relations.media_id and media_relations.CREATED_BY_AGENT_ID=21248712 and CREATED_ON_DATE between '2010-01-01' and '2020-12-12' group by media_type


text
			     30

video
			      2

image
			   1037

```

**Comment by AJLinn** [comment]
thank you - close enough
