### ISSUE TITLE
New event attributes - weather, etc.

### ISSUE THREAD

**Issue by anna-chinn** [ArctosDB/arctos#2486]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=CTCOLL_EVENT_ATTR_TYPE
https://arctos.database.museum/info/ctDocumentation.cfm?table=CTCOLL_EVENT_ATT_ATT

**Value**

attribute type | documentation | data type | units
------------ | ------------- | ------------ | -------------
air temperature | The temperature of the air, as measured during a collecting event. | number | TEMPERATURE_UNITS
relative humidity | Relative humidity of the air, as measured during a collecting event. | number or free text? Free text would allow people to enter a ratio, but not sure if that's common RH notation |
weather | A general description of the weather during a collecting event. | free-text |
tree girth | For events where an individual tree represents a collecting locality. Circumference measurement around a tree trunk perpendicular to the axis of the trunk, measured at 1.4m above ground level (breast height). | number | LENGTH_UNITS

^As for tree girth, we have a few invertebrate specimens that were collected from trees, where the collectors recorded a circumference measurement for the tree (and possibly collected more than one invert per tree). This is an on-going student project, so we will likely get similar specimens in the future. Definitely open to suggestions of other places to put these data!

**Priority**
Normal

**Comment by dustymc** [comment]
>air temperature

Yes

>relative humidity

I very strongly suggest numeric data, which requires units. Maybe add "percent" to http://arctos.database.museum/info/ctDocumentation.cfm?table=CTCOUNT_UNITS and use it as the units? (That also matches the RH data in container environment.) I suppose that would allow RH==8456 individuals, but we of course don't have any users who'd do such a thing. I think the alternative is firing up another overly-specialized code table just for this, which I'm not crazy about.

>weather

Seems reasonable.

>tree girth

No objections, but a little weird. Cataloging the tree would be best, but probably isn't practical. It's sort of habitat data, but wouldn't be "extractable" from there. Do it, I think....

**Comment by Jegelewicz** [comment]
I agree with everything Dusty says with these exceptions:

> relative humidity

Relative humidity of the air, as measured during a collecting event expressed as a percentage.

Then we add add "percent" to http://arctos.database.museum/info/ctDocumentation.cfm?table=CTCOUNT_UNITS and use it as the units.

> tree girth

Seems like we could use something a little more generic? I can see something like this being used for any "resting structure". Also " measured at 1.4m above ground level (breast height)" seems very specific and maybe would belong in the method of the attribute? (Others might use some other method). How about:

resting structure girth = Circumference measurement around a resting structure perpendicular to the axis of the structure.

Then also perhaps add

resting structure = description of the substrate on which the specimen was resting when collected (free text)

So you would have resting structure = tree and resting structure girth = 10 with measured at 1.4m above ground level (breast height) in the method for this attribute.

**Comment by anna-chinn** [comment]
> No objections, but a little weird. Cataloging the tree would be best, but probably isn't practical.

Hm interesting. I do have tree species + images for each of these localities. That said, most of these are cultivated landscaping trees in a public park...

> Seems like we could use something a little more generic?

Could it even be as generic as 'sampling substrate' as a free-text attribute that could encompass both the tree species and its girth? Do people record data about the circumference of other kinds of resting structures other than trees?

Tree girth has an article on [Wikipedia](https://en.wikipedia.org/wiki/Tree_girth_measurement), so I figured that the measurement might be more general than I initially thought. Apparently it's used in forestry, but I have no clue how often it's recorded in specimen-based research.

**Comment by Jegelewicz** [comment]
> tree species + images for each of these localities.

Cataloging them as observations would make the data soooooo much richer! Then the tree girth would just be an attribute of the tree. It would also play well with GloBI interactions - adding to the wealth of information about species interactions.

**Comment by Jegelewicz** [comment]
And think of how you would inadvertently collect growth info on the trees as the study continues over time...

**Comment by Jegelewicz** [comment]
You could write a whole paper on how this works in Arctos - or make a presentation at SPNHC about it (hint hint)

**Comment by dustymc** [comment]
>'sampling substrate' 

Is that somehow not "habitat"? I'm not suggesting anything, other than good documentation if there is some difference.

>richer

Yup - cataloging the tree would let you eg, hook in to taxonomy (data objects) rather than just strings, maybe attract experts who'll verify/refute your IDs, etc. 

>cultivated landscaping trees

Even better! Do those influence nearby critters? Kill off the local mycorrhizae? Affect downstream water ph? Become invasive? Nobody's ever going to know until someone catalogs enough of them in some accessible format....

**Comment by anna-chinn** [comment]
Cool! This student group collects a bunch of observation data that, previously, we have never meaningfully interfaced with. It would be rad to make it publicly accessible more formally, especially given that some of these observations are related to specimens.

Does this mean that CHAS needs separate Obs collections (maybe one for animal observations and one for plants)? How have other institutions dealt with this kind of thing? Would there be any reason not to separate plant observations from the herbarium as a whole, for example?

**Comment by anna-chinn** [comment]
I'll go ahead and add temp, RH, and weather to code tables.

**Comment by dustymc** [comment]
>separate

From my perspective, that's 100% administrative.

**Comment by Jegelewicz** [comment]
> Does this mean that CHAS needs separate Obs collections (maybe one for animal observations and one for plants)? How have other institutions dealt with this kind of thing? Would there be any reason not to separate plant observations from the herbarium as a whole, for example?

Totally up to you! Observations end up in "specimen" collections, they just use the specimen event type "observation" instead of "collection".

**Comment by campmlc** [comment]
We have both observations and specimens in the same collections. We use
observations for related specimens that may or may not actually exist in
other collections; if we find them, then we can turn the observation into a
specimen. And of course, this works for all "cataloged records" not just
"specimens", for the cultural folks! Old habits are hard to break.

**Comment by anna-chinn** [comment]
Thank you everyone for the great feedback. Tree observations to come!

**Comment by Jegelewicz** [comment]
@anna-chinn for plants, collection doesn't need to mean destruction of the organism. A collection from these plants over time could also make for some interesting environmental analyses.....

OH the POSSIBILITIES!!!

**Comment by dustymc** [comment]
>collection doesn't need to mean destruction

Plants are weird, but it SORTA does - http://arctos.database.museum/info/ctDocumentation.cfm?table=CTSPECIMEN_EVENT_TYPE

If you're pulling a leaf, I'd call it 'encounter.' If you're sawing a tree off at the ground I'd probably call it 'collection' - even though it'll grow back from the stump, because plants are still weird....

>We have both observations and specimens in the same collections.

I think we're all more or less on the same page with this, but I'll expand on my comment above. "Observations" and "Specimens" with lost parts are functionally identical. Ear snips (hair samples, etc.) are cataloged as observations or specimens depending on local administrative whims. Etc. There's nothing in the term which might help users find what they want, so the collection in which any particular "Occurrence" is cataloged is entirely arbitrary for anyone outside of the collection.

**Comment by Jegelewicz** [comment]
Every herbarium sheet says it was "collected". Just because you only collected part of a thing doesn't mean it wasn't collected!
