### ISSUE TITLE
New Part Preservation - Nobuto Strip

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2487]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=CTPART_PRESERVATION

**Value**
Nobuto Strip

**Definition**
Made from high-purity cellulose fibers, Nobuto strips are structured for uniform sampling. Each strip holds approximately 1 mL of blood or 0.04 mL serum and requires no refrigeration or pretreatment for sampling, storage, or analysis.

**Part tissue flag**
yes

**Context**
Provides a standardized description of a preservation method. Nabuto Strips may also be stored frozen or dry so parts with this preservation should also include a preservation of frozen or dry.

**Priority**
Please assign a priority-label.

**Comment by jldunnum** [comment]
Correct spelling is "Nobuto"

______________________________________________________________

Jonathan L. Dunnum Ph.D.
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by campmlc** [comment]
I agree with this.

**Comment by Jegelewicz** [comment]
Done
