### ISSUE TITLE
UUID duplication

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#2489]
When my volunteer was adding additional attributes, two specimens were assigned the same UUID. That's not supposed to happen, right? I can't say if the volunteer did something strange to make this happen; but I thought you should be aware.
here are the offenders:
http://arctos.database.museum/saved/UUID%20Issue

Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

** Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by acdoll** [comment]
Here's another pair:
http://arctos.database.museum/guid/DMNS:Mamm:20856
http://arctos.database.museum/guid/DMNS:Mamm:20857

could this have something to do with the 'carry' function in the form customization on the data entry page?

**Comment by dustymc** [comment]
It's mathematically possible that I provided a duplicate, but exceedingly unlikely.

I suspect it's from the 'carry' functionality.

**Comment by acdoll** [comment]
I figured that was the case. I will refresh our training on using those customize functions. Is there anyway to prevent that specific type of other ID from carrying over? I would imagine not without some significant changes.

**Comment by dustymc** [comment]
>prevent that specific type of other ID from carrying over

Yes that's "significant changes" - and would very likely eventually be frustrating for someone trying to split a lot or similar.

**Comment by acdoll** [comment]
Roger that. I will rely on proper training. Thanks.

**Comment by Jegelewicz** [comment]
Probably also needs better documentation?
