### ISSUE TITLE
Closing loan and disposition

### ISSUE THREAD

**Issue by aklompma** [ArctosDB/arctos#2491]
After closing a loan, the now previously loaned specimens still appear as "in loan" under "disposition".
Would it not be great if disposition could be changed automatically to "in collection" when a loan is closed? This would save time, particularly for large loans. 

Priority: medium?

**Comment by dustymc** [comment]
There is little link between disposition of parts and loan status - parts may be lost, returned before a loan is closed (eg, waiting on publications), etc. I don't think a clean path to full automation exists.

There is a one-ish click tool to update disposition of all loaned items:

<img width="1144" alt="Screen Shot 2020-02-10 at 11 56 20 AM" src="https://user-images.githubusercontent.com/5720791/74184930-89905200-4bfc-11ea-848f-05bb4552c2d9.png">

**Comment by aklompma** [comment]
Great! This will work well for many returned loan.
