### ISSUE TITLE
New Part Attribute - object complement type

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2492]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Goal**
In Paleo collections we often have part/counterpart pieces or rock slabs with specimens on both the "top" and "bottom". Ideally, everything would be cataloged separately and associated with the "same assemblage as" relationship, but the world is not always ideal. In order to demonstrate the various pieces of a cataloged item in the parts section, I wonder if a new part attribute would help.

**Context**
I have considered putting the terms in condition or remarks, which may be good enough, but thought I would pass this around for comments/ideas. One record that includes this scenario is https://arctos.database.museum/guid/ALMNH:ES:8394

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=CTSPECPART_ATTRIBUTE_TYPE

**Value**
object complement type

**Definition**
Describes the complementary relationship of the part to which the attribute is applied to another part in the catalog record.

**Attribute data type**
categorical

**Attribute value**
part
counterpart
obverse
reverse

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
The usual question: who cares?

If the answer is an enthusiastic-enough "somebody!" then it may be worth NOT providing an alternative to proper cataloging, which people may erroneously see as being functionally equivalent. 

If the answer is "people who've found the specimen" then remarks is sufficient.

If the answer is somewhere in between then this may make some sense, but I'm not sure the definition does. E.g., "complementary relationship" makes me wonder which part gets what, whereas something like "impression" would make it clear that the part bearing the attribute is the "counterpart" (if I'm understanding this...).

That takes me to the idea that this may not be a separate THING, but something that could be mixed in with other vocabulary - https://arctos.database.museum/info/ctDocumentation.cfm?table=CTPART_PRESERVATION perhaps.

https://arctos.database.museum/info/ctDocumentation.cfm?table=CTPART_ATTRIBUTE_PART was a sorta-similar attempt to quantify the bits mixed in with eg "tissue" - "sub-parts," kinda. I'm not sure that anyone's ever used it.

**Comment by Jegelewicz** [comment]
> If the answer is somewhere in between then this may make some sense, but I'm not sure the definition does. E.g., "complementary relationship" makes me wonder which part gets what, whereas something like "impression" would make it clear that the part bearing the attribute is the "counterpart" (if I'm understanding this...).

It is the "which part gets what" that is unsure until someone goes to look at the stuff (I think). For now, I am going to add part/counterpart to the part remark. Eventually, someone who has time to check the stuff can add an attribute to the part giving details such as "impression".
