### ISSUE TITLE
Too specific definition of a part attribute? (or Part Attribute Emergency...)

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2493]
The part attribute code table includes the following term and related definition:

Term | Definition
-- | --
surface area | Measurement of surface area **occupied by food items under stereo microscope**.

This definition seems far too specific for such a generic term. I'm not sure when this was added or who is using the term, but perhaps we need something more specific so that "surface area" could be used as "the measure of the total area that the surface of the object occupies" - [Wikipedia](https://en.wikipedia.org/wiki/Surface_area)

**Comment by dustymc** [comment]
@ccicero added it - there's a changelog link at the top of the editor, this one goes to http://arctos.database.museum/info/ctchange_log.cfm?tbl=CTSPECPART_ATTRIBUTE_TYPE.

Yes agreed that needs either a better term or a better definition.

**Comment by dustymc** [comment]
Elevating priority because authority data are involved; this should be resolved ASAP if we're to change the meaning of a term.

**Comment by Jegelewicz** [comment]
@ArctosDB/arctos-code-table-administrators please weigh in.

**Comment by ccicero** [comment]
I have no recollection. I've never used that part attribute. Maybe someone asked me?

In any case, I agree. who is using that part attribute? I can't figure out how to search where value is not null.

**Comment by dustymc** [comment]
It wasn't used, I took the easy route and deleted it.
