### ISSUE TITLE
No clear connection between Arctos and NCBI SRA

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#2495]
Need to find the best number for links between Arctos and SRA, and back again. Already have OtherID nums of "NCBI Sequence Read Archive Run ID" and "NCBI Biosample". There is nothing in Arctos for the first number type, but one specimen, MVZ mammal 216768. A Rattus rattus I collected. It has and NCBI biosample number that leads to NCBI. It does show "specimen voucher | MVZ:Mamm:216768" but is not a hyperlink. That would be ideal.

**Comment by dustymc** [comment]
http://arctos.database.museum/guid/MVZ:Mamm:216768

links to

https://www.ncbi.nlm.nih.gov/biosample/SAMN05822323

which links...

<img width="534" alt="Screen Shot 2020-02-11 at 2 25 45 PM" src="https://user-images.githubusercontent.com/5720791/74285369-8bc8de00-4cda-11ea-9e35-4bd70fb06bf0.png">

to

https://www.ncbi.nlm.nih.gov/bioproject?LinkName=biosample_bioproject&from_uid=5822323

and

https://www.ncbi.nlm.nih.gov/sra?LinkName=biosample_sra&from_uid=5822323

and through the linkouts Arctos pushes to GB, back to the specimen

<img width="419" alt="Screen Shot 2020-02-11 at 2 29 35 PM" src="https://user-images.githubusercontent.com/5720791/74285570-fed25480-4cda-11ea-839c-99b2afe4e604.png">

I don't know why they're not linking the specimen_voucher there - it looks correct, I think that's a question for genbank.

Is there some reason to link the bioproject and SRA from Arctos explicitly, or is the NCBI link from the biosample sufficient? I think that's the same as question as "can bioproject and/or SRA exist without a biosample?" - if they can then we probably need all three, if they can't then the one seem sufficient (and easier to maintain).

**Comment by dustymc** [comment]
Happy?
