### ISSUE TITLE
Other ID field number - definition is too specific

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2497]
IDType | Description | Base URI | Sort
-- | -- | -- | --
field number | Field number, aka station number (typically applied to  ship/marine collections) is a unique number assigned to a collecting  event---at a minimum: where, when, who OR the place, date and time of  collection, and collectors (names). Also included are field conditions  at time of collection, method of collection, and list of collections.  Fish collections/collectors use the standard for field numbers set by  Hubbs and Lagler, 1947--- i.e., an alphanumeric with collector's  initials, last two digits of year, and 001 to infinity...then start  again next year (001 to ?). E.g., AMS17-021. This number relates to a  collection/effort that either results in fish capture or none; it  relates to the capture of multiple species or a single species. | | 2

This long and drawn out definition seems much to specific for such a generic term and also seems more appropriate as a specimen event attribute? I suggest that whatever collection is using this definition create a more specific term and that field number should be changed to the following:

IDType | Description | Base URI | Sort
-- | -- | -- | --
field number | An identifier assigned to an object in the field. Use this when a second collector has assigned a number or a general number is assigned in addition to a collector number. | | 2

**Comment by dustymc** [comment]
The concept has always been "whatever fish people do" (which I believe generally involves species at place-time, so doesn't work well at the event). That definition was written by MSB:Fish.

I'm sorta-certain it's NOT "assigned to an object" but (usually) a group of them.

"second collector has assigned a number"-->second collector number

"general number "-->original identifier

FWIW I think we have WAY too many nonresolvable identifiers; in general, I'd be fine with some consolidation. The Community has generally gone the other way, towards more and more specific IDs, however.

**Comment by Jegelewicz** [comment]
"general number "-->original identifier

> Other values that link a specimen with its data. For example, label values applied by an agency project, or various values that are not known to be of a more defined identifier type.


This is not at all useful without the addition of a description of what the number means to whoever put it in which is why we have so many very specific other IDs. They may not be "resolvable", but the specificity means I can understand exactly what they mean and perhaps one day they can become "resolvable" when the rest of the world includes a way for us to link up.

**Comment by campmlc** [comment]
As Dusty says, "field number" is used and searched on by our one fish
collection. We added it, with their definition, to accommodate their needs.
My opinion is that if a specific discipline uses a specific term, we should
be able to accommodate that in Arctos, rather than trying to educate an
entire discipline's worth of collection's staff and researchers to learn to
use some other,  less specific term just for Arctos management and
searches. I think broadening the definition is fine, but it should include
the full text of this definition as a subset.

**Comment by dustymc** [comment]
>perhaps one day they can become "resolvable" 

Those I completely agree should be separate. There's some semi-realistic possibility that "DNHM: Delaware Natural History Museum" is going to be online and providing additional data some day, so they should be a type. (Something like "Delaware Natural History Museum fish collection" is a lot more realistic, but still.) 

AF/NK/etc. should be separate - they have local usefulness.

We need a "trashcan" for the really weird.

In between, I'm not so sure. I can't figure out why "Dennison Manufacturing Company" (just the first thing that caught my eye) is a type; I don't think it's locally useful, it doesn't seem like the kind of entity that might ever put up more data, and it's not clear what those specimens might have to do with that number. How is having it an a type more functional than ``trashcanID: Dennison Manufacturing Company Number 12345``?

**Comment by Jegelewicz** [comment]
> In between, I'm not so sure. I can't figure out why "Dennison Manufacturing Company" (just the first thing that caught my eye) is a type; I don't think it's locally useful, it doesn't seem like the kind of entity that might ever put up more data, and it's not clear what those specimens might have to do with that number. How is having it an a type more functional than trashcanID: Dennison Manufacturing Company Number 12345?

I see your point with that one.  This would be a good thing for @ArctosDB/arctos-code-table-administrators to review and maybe make a list of other IDs that belong in "miscellaneous identifier" = An identifier of unknown origin or that is unlikely to resolve to another collection object.

**Comment by Jegelewicz** [comment]
> As Dusty says, "field number" is used and searched on by our one fish collection. We added it, with their definition, to accommodate their needs. My opinion is that if a specific discipline uses a specific term, we should be able to accommodate that in Arctos, rather than trying to educate an entire discipline's worth of collection's staff and researchers to learn to use some other,  less specific term just for Arctos management and searches. I think broadening the definition is fine, but it should include the full text of this definition as a subset.

I agree with you in principle and I was not around for the discussion that accompanied the addition of this term. I think we should also expect that new collections may find terms with definitions that don't match their usage and so we may have continued discussions about their use.

Suggest adding

> An identifier assigned to an object in the field.

to the definition of "field number"

**Comment by Jegelewicz** [comment]
closing for lack of interest
