### ISSUE TITLE
taxonomy: cultural terms

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#2499]
Arctos taxonomy terms are currently limited to "Linnean" strings - there are a bunch of rules which require certain structure in order to keep taxonomy clean. There's now a need to introduce cultural taxonomies to Arctos, but we need to do so without the possibility of polluting the formal taxonomy used by NH collections.

Suggestion: Add taxon_name.name_type IN (Linnean, cultural, mineral)

For Linnean, keep the current rules.

For others, develop rules as possible.

Objections?

**Comment by Jegelewicz** [comment]
LOVE IT!!!!

**Comment by mkoo** [comment]
:heart:

**Comment by Jegelewicz** [comment]
Possible to have a cultural and a biological classification for a single catalog item?

**Comment by dustymc** [comment]
No problem with a full-blown taxon concepts model.....

Certainly no problem as far as the names go.

To really get the classification you'd probably need to eg, clone http://arctos.database.museum/name/Alces%20alces#Arctos into your collection's preferred "cultural classification." 

This change would NOT do anything to classifications or any relationship between taxa, classifications, and catalog records. It would just provide a mechanism for allowing "parkas" (from http://www.getty.edu/vow/AATFullDisplay?find=parka&logic=AND&note=&page=1&subjectid=300046185) without also allowing "shrews" (which is all lower-case so doesn't meet the "Linnean pattern" logic).

**Comment by Jegelewicz** [comment]
> Suggestion: Add taxon_name.name_type IN (Linnean, cultural, mineral)

We discussed this in taxonomy committee today and talked about just having three different "name" tables: taxon_name, object_name, mineral_name . Could we also have multiple types of identifications of a cataloged item (biological, cultural, mineral)?

So the [fur parka](https://arctos.database.museum/guid/UAM:EH:UA67-133-0001) would have:

Identifications
Biological - Parka, fur{Rangifer tarandus (Linnaeus, 1758), Canis lupus Linnaeus, 1758, Gulo gulo (Linnaeus, 1758), Neovison vison (Schreber, 1777)}
Cultural - [Parka](https://www.nomenclature.info/parcourir-browse.app?id=2576&lang=en&ws=INT&wo=I)

Just throwing out ideas - we will have mineral "taxonomy" ready soon for NMMNH:Geol.

**Comment by mkoo** [comment]
This is a fantastic development for identifications. Will be useful for
archive collection too!

**Comment by dustymc** [comment]
At least the basics of this will be in the next release; it will immediately solve some major issues.

@Jegelewicz I'm not seeing what denormalizing everything would accomplish, other than replicating a huge amount of code and possibly making referential integrity difficult/impossible to maintain. What functionality is that attempting to gain?

**Comment by Jegelewicz** [comment]
We currently are allowed only 1 accepted ID - that parka has two.

**Comment by dustymc** [comment]
>allowed only 1 accepted ID

That's been bouncing around on the edge of my radar for a while; it deserves its own discussion.

>that parka has two

I'm not sure that's true, but I'm definitely not sure it's false either. We need to flesh out the idea of what we mean by "accepted" - eg, if it means "what the collection wants to call it" then allowing one accepted ID is probably correct, if we mean "we reject the minkness of this mink coat" then we need different approach. MAYBE this is just a documentation problem....

In any case the current model is fully capable of multiple accepted IDs, but we currently actively prevent that state.

**Comment by Jegelewicz** [comment]
> We need to flesh out the idea of what we mean by "accepted" - eg, if it means "what the collection wants to call it" then allowing one accepted ID is probably correct.

FWIW - I have assumed "accepted" to mean "this is what the collection is currently calling this thing".

If so, I think we would need to mash together:

Parka, fur{Rangifer tarandus (Linnaeus, 1758), Canis lupus Linnaeus, 1758, Gulo gulo (Linnaeus, 1758), Neovison vison (Schreber, 1777)} [Parka](https://www.nomenclature.info/parcourir-browse.app?id=2576&lang=en&ws=INT&wo=I)

as a single ID. I would assume that is what Alaska would say is their "accepted" ID for the parka.

**Comment by Jegelewicz** [comment]
Maybe we just need multiple types of "acceptance"

accepted biological ID
accepted cultural ID
accepted mineral ID

which could be useful when deciding what to send to aggregators (depending upon the type of aggregator).

**Comment by dustymc** [comment]
>need to mash together

We've been doing that for some time - https://arctos.database.museum/guid/UAM:EH:0610-5898

**Comment by Jegelewicz** [comment]
Nowhere is that linked to https://www.nomenclature.info/parcourir-browse.app?id=2576&lang=en&ws=INT&wo=I we have no classification for "Parka" and when we add one - how will that work in this format?

**Comment by dustymc** [comment]
>Nowhere is that linked to...

That's Phase Two - should be possible to add cultural terms ~tomorrow.

>how will that work

Phase Three, I suppose! 

The "just works" solution would be to pull terms into "their" classification. 

Some flavor of https://github.com/ArctosDB/arctos/issues/2231 would effectively allow that without the denormalization. I'll add an alterntive half-baked idea there.....

**Comment by AJLinn** [comment]
I feel like I should be weighing in here, but as a newbie to "taxonomy" in it's structured sense, I'm not sure what to contribute.
