### ISSUE TITLE
sharing data

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ArctosDB/arctos#250]
```
Email 3 Apr 2009 from Jason Malaney: Seems like we can certainly share the
parts but not the data on ARCTOS.  Hmmm, seems fishy to me!  Bottom line...
at the end of the day, we as the users have to have utilization of the
database (including the data), otherwise it's just a fancy toy that a few
people get to monkey around with.  I get a bit perturbed whenever I go out
and collect a critter, stick it in the museum, load it up, then can't even
look at the silly thing or have access to it's data.  I collected it after
all! and put the data in the system... who's better than I to determine if
its correct!  Maybe I get a bit lost at times but generally I think I have
a better idea of the circumstances that I collected a specimen than someone
else behind a computer screen which clearly wasn't there, especially
whenever I've entered that data too.  Can you tell my soap box is getting
bigger?

Dusty reply:
This is something that we can talk about more.

Here's the techie stuff:

"Collection roles" own rows in tables (msb_mamm is an example)
"Privileges roles" grant things to users (manage_locality is an example)
Users ("jmalaney") are granted these roles by the collections.
Roles are additive.
So, we give jmalaney msb_mamm and manage_locality and he can manage all
that locality data owned by msb_mamm. Spiffy.
However, if we also give jmalaney uam_mamm, he can do anything to uam_mamm
records that he can do to msb_mamm, and that won't fly politically.

I'm up for suggestions, as long as 1) they're technically feasible, and 2)
they're OK with all the curators. At least some of the curators and Lam
("VPD Chick") will be in Berkeley later this month. That would be a good
time to talk about this. It's obviosuly something that needs to be handled
better, or at least more understood by users.

```

Original issue reported on code.google.com by `carla...@gmail.com` on 7 Apr 2009 at 7:44

**Comment by dustymc** [comment]
I now believe we're asking for a user interface nightmare.

"The airlines use VPD" (it's true) comes up a lot as an example of why this should be easy (maybe not so much).

* There is no place, ever, where one can see AirlineA (AA) and AirlineB (AB) restricted data. Kayak etc, is an abstraction/transformation of the data (like vertnet), the only way to see (much less change) actual tables is to be an employee of A and B (and unlike Arctos, you'd get 2 logins for that).
* "Private"  data (eg, seating assignments - think Attributes) is not shared.
* Cross-company data (eg, luggage tracking - think Locality) is shared.
* UIs are developed privately. When you feed your credit card to AA's system (as a public user or as an employee) there's no indication that it's actually going into the same data structure AB uses.

The technical stuff is still completely doable, but I no longer think this is practical, at least not with our current resources (eg, lacking a usability expert).

**Comment by mkoo** [comment]
Consensus from AWG 2016-08-01: barring any elucidation about airlines, Dusty says "yes" to allowing logged in users to see the publicly available specimen details from other Arctos collection.

**Comment by dustymc** [comment]
Bad: I don't think this level of granularity is currently practical in PG.

Good: Most all browsers have a 'private' tab nowadays, which makes accessing public data easy.

Closing.
