### ISSUE TITLE
New Other ID type - field jacket

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2502]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Goal**
Make it possible to find stuff from the same jacket.

**Context**
Field jackets are common in paleo where a "jacket" is made in the field to bring objects safely back to the museum for further preparation.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=CTCOLL_OTHER_ID_TYPE

**Value**
field jacket number

**Definition**
Identifier assigned to a a plaster covering placed over and around a fossil or fossils while in the field, to protect the fossil as it is removed and transferred safely back to the lab or museum for further study.

**Attribute data type**
free-text

**Other ID BaseURL**
N/A - but would like to be able to "find more like this".

**Priority**
Please assign a priority-label.

**Comment by campmlc** [comment]
I support this.

**Comment by dustymc** [comment]
This seems overly specific to me IF it's something like a collector number - an identifier that might be scrawled on multiple parts. That is however the way we've been going, and I suppose 462 IDs isn't all that much more of a mess than the current 461....

If this is something for which eg institutions maintain a dedicated 'catalog' - something above and beyond yet another collector-number-like ID - then it may make more sense as a dedicated identifier.

**Comment by Jegelewicz** [comment]
> If this is something for which eg institutions maintain a dedicated 'catalog' - something above and beyond yet another collector-number-like ID - then it may make more sense as a dedicated identifier.

I wish. These are collector-like, but our definition of collector number

> A value that refers to a person's field catalog. For this number to be applied to a specimen, the person has to be the first collector of a specimen.

has no relationship to a field jacket number, which is generally assigned by a crew of people at a specific site during a specific collecting event. Ideally, field jackets would be cataloged, but that is a fight I'll be taking up at a later date. I had intended to use "field number", but that definition seems inappropriate (and too specific) as well. See #2497

**Comment by Jegelewicz** [comment]
@ArctosDB/arctos-code-table-administrators any opposition to this?

@ArctosDB/paleontology thoughts?

**Comment by campmlc** [comment]
Ok with me.

**Comment by AJLinn** [comment]
Seems pretty specific, and I tend to agree that the "field number" should have been a better catch-all... is there are reason why we don't just update the field number definition to include numbered field jackets?

**Comment by ccicero** [comment]
I agree that it makes more sense to adjust the 'field number' definition to cover field jacket.

**Comment by dustymc** [comment]
Put me down as "concerns, but no outright objections."

It's still not clear to me how this doesn't overlap with eg "original identifier." I also don't think otheridtype usefully supports search; the non-URL-having ones almost all seem arbitrary. I think we should discuss that in general, but this doesn't seem like much of a contribution to the mess and I don't think it needs blocked.

"field number" means something specific in fish collections (and I don't think it's usable outside that tradition). I can more or less see the value in that, not so much in the 'typically written on certain substrate' split that we seem to be accumulating.

**Comment by mbprondzinski** [comment]
I've been assigning "field number" to other identifiers that are a hybrid of the site and collector number (See ALMNH Museum Expedition 41).  It seemed like a good enough catchall.

**Comment by Jegelewicz** [comment]
I'm leaning toward Dusty here. I think I will just put "jacket" with the number and call it original identifier. Although I still think "field number" is poorly defined.
