### ISSUE TITLE
Need to add Geology Attribute Code

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/arctos#2503]
Caloosahatchee Bed

**Comment by Jegelewicz** [comment]
/remind me to check this on Monday

**Comment by Jegelewicz** [comment]
@mbprondzinski are you sure this is different from [Caloosahatchee Formation](https://macrostrat.org/sift/#/strat_name/61076)? I can't find any documentation for Caloosahatchee Bed.

**Comment by aklompma** [comment]
Most likely, Caloosahatchee bed was used prior to this unit being proposed as a formation.

**Comment by Jegelewicz** [comment]
Caloosahatchee Formation is already in the code table, so using that is OK?

**Comment by mbprondzinski** [comment]
It seems to be referenced in the early 1900's so formation is probably used now.
