### ISSUE TITLE
Media OCR

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#2504]
There was mention of OCR capabilities for media at a recent working group meeting. I am in need of a transcription of a transcription. I have a typewritten volume representing a transcription of a field note series (1883-1901) that relate to UCM specimens. We aren't dealing with cursive, but OCR may still prove complex given the typewritten volume is somewhat faded (c. 1907) and has occasional handwritten annotations.

Can we test some pages? Here's a couple examples of the quality.

![image](https://user-images.githubusercontent.com/11336485/74573060-51ab4680-4f3d-11ea-9f60-6bd230502ff8.png)

![image](https://user-images.githubusercontent.com/11336485/74573943-5a048100-4f3f-11ea-8965-b89511c6ae73.png)

**Comment by dustymc** [comment]
@ebraker I can check to see if the OCR stuff is still around next week. It was just a really basic (and very old at this point) install of https://github.com/tesseract-ocr/.

Good OCR is something like a full-time job - there are all sorts of extensions and training modules and etc. that we never really had the resources to get very deep into. It might make more sense to plug in to something like https://cloud.google.com/vision/docs/ocr. https://cloud.google.com/vision/pricing - looks like the first 1K requests/month are free, but Google's pricing is always more cryptic than it first appears.

@mkoo somehow manages to wrangle free location API access for us....

/remind me to check back next Tuesday

**Comment by ebraker** [comment]
Ok thanks. It's worth a try with the tesseract - maybe straightforwardish scans won't pose much of a problem. The Google plug in (if free) would be great as we incorporate archives in Arctos.

**Comment by dustymc** [comment]
Sent TACC email.

**Comment by dustymc** [comment]
The OCR install apparently didn't survive some hardware upgrade a few years back. I asked if anyone at TACC might be looking for a project or already running something we could plug into  - I'll report back if I hear anything.

If that doesn't work, we could install something or use some API. Looks like Microsoft has an API as well as the Google option I mentioned above. They both have free tiers, but I think they both require a form of payment as well.

Should we add this to the AWG agenda?

**Comment by dustymc** [comment]
@ebraker how many of these are there?

**Comment by ebraker** [comment]
Yes, let's add to the AWG agenda. I have a complete pdf of the full document (280 pp) or scans of individual pages available. All our other scanned archives are handwritten so probably an OCR no-go.

**Comment by dustymc** [comment]
tabling - it seems that reviving OCR is going to take some sort of dedicated resources (build and train a server, pay Google, etc.)
