### ISSUE TITLE
Camera used and film used

### ISSUE THREAD

**Issue by krgomez** [ArctosDB/arctos#2505]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Goal**
We have data about the cameras and film used in the creation of many photographs in the UAM:Art collection, but don’t currently have a great place to record it. We think this data may be well suited to collection event attributes.

**Context**
Alternatives we've considered are event remarks or as new catalog record attributes.

**Table**
COLL_EVENT_ATTR_TYPE

**Value**
camera used
film used

**Definition**
camera used -- The brand and model of the camera used.
film used -- The brand and film format used.

**Attribute data type**
free-text

**Priority**
Normal

**Comment by Jegelewicz** [comment]
I think this should be in the media metadata as labels, but maybe more than two?

https://arctos.database.museum/info/ctDocumentation.cfm?table=CTMEDIA_LABEL
label | definition
--- | ---
camera brand | The brand of the camera used.
camera model | The model of the camera used.
film brand | The brand of film used.
film format | The film format used.

Also, it seems like these lend themselves to controlled vocabularies so that we don't get Nikon and nikon, 35mm and 35MM and 35 mm, etc.

**Comment by Jegelewicz** [comment]
BUT if these are related to actual photographs that ARE the collection item, then it seems like they belong in Attributes.

https://arctos.database.museum/info/ctDocumentation.cfm?table=CTATTRIBUTE_TYPE

with the same terms/definitions and comment about controlled vocabulary as above.

**Comment by krgomez** [comment]
The data we have about cameras and film are for photographs that are cataloged into the collection, not for media representations of artworks. (Though, it wouldn't hurt to have a place to record this kind of information in the media metadata as well). Regular attributes would work fine. Not sure I understand what kinds of information could be event attributes. If we make these as attributes I think we would really want to use "camera used" and "film used" as that's the format in which the information is documented in collection data sheets filled out by the photographers. My definitions might be off. We would just want to record verbatim whatever is on these data sheets we have for camera and film.

**Comment by Jegelewicz** [comment]
> Though, it wouldn't hurt to have a place to record this kind of information in the media metadata as well

Agree! and think that they should be media metadata,

>  I think we would really want to use "camera used" and "film used" as that's the format in which the information is documented in collection data sheets filled out by the photographers. My definitions might be off. We would just want to record verbatim whatever is on these data sheets we have for camera and film.

Verbatim information is good and could go in the attribute remark, but standardized information will be better in the long run for discoverability. Always assume that you will not be the only collection using this attribute. The next art collection may have different data sheets with the same information recorded in a different way. Standardizing will make it easier for everyone to use.

**Comment by dustymc** [comment]
Who's the audience - who cares, and why might they care?

>record this kind of information in the media metadata as well)

It should be in the metadata of the Media itself, unless someone has purposefully stripped it out (eg by converting to TIFF - I think I saw that posted as guidance somewhere recently...).

I don't think these data are event - changing the camera or cataloging something else doesn't change place-at-time data.

They might be part attributes if you were cataloging the camera.

In this case I they're just attributes of the cataloged item, but....

This seems overly-specific to me. It's the same sort of thing as brand of brush/ batch number of paint, etc., etc., etc., as nauseum. It's "materials," almost-but-maybe-not-quite - it was used to create the main component of the cataloged item, but there's no "kodachrome 35mm ISO400" available for sampling either.

**Comment by Jegelewicz** [comment]
Yeah, but you might want to find all photographs "taken on Kodak 35mm film".

**Comment by Jegelewicz** [comment]
> It should be in the metadata of the Media itself, unless someone has purposefully stripped it out (eg by converting to TIFF - I think I saw that posted as guidance somewhere recently...).

But you cannot readily find that in Arctos?

**Comment by dustymc** [comment]
> find all photographs "taken on Kodak 35mm film"

And you might want to find all metal sculptures welded with a Miller Synchrowave 250 on DC using ER70S2 rod, but at the same time adding everything that was used in creating anything that anyone's ever considered "art" as a code table isn't very practical. Materials (or almost-but-maybe-not-quite-materials) covers all of that. Optionally structuring materials would let you ask pointed questions. That is, materials can be entered in two ways:

```
taken on Kodak 35mm film
```
or 
```
[
  {
  "film": {
    "brand":"Kodak",
    "size":"35mm",
    "ISO":"400"
  }
]
```

The former is string-match, the latter lets you get at "materials.film.brand==Kodak" without firing up 27 new code tables to deal with charcoal on birch bark drawings tomorrow.

This seems to be a really common thing, surely someone in "the cultural community" has thought about how to handle it?

>cannot readily find that in Arctos

There are a near-infinite number of things you can't find in Arctos (and any other highly-normalized system). If the data are organized properly, that's "just" a UI problem.

**Comment by Jegelewicz** [comment]
Getty AAT materials - [photographic materials](http://www.getty.edu/vow/AATHierarchy?find=&logic=AND&note=&subjectid=300127358)

**Comment by dustymc** [comment]
Getty has a really clever way of stopping just about where we want to start, don't they!

http://vocab.getty.edu/aat/300127382 is a useful way to say "film" - we could eg start with http://vocab.getty.edu/aat/300127382.json and extend it to the details.

**Comment by Jegelewicz** [comment]
> Getty has a really clever way of stopping just about where we want to start, don't they!

This may be true for a lot of things because down in the weeds, where a lot of us work, we need more refined details than the broader community (as far as the broader community knows). Over time, maybe we can have Getty dig deeper....

**Comment by krgomez** [comment]
> This seems overly-specific to me. It's the same sort of thing as brand of brush/ batch number of paint, etc., etc., etc., as nauseum. It's "materials," almost-but-maybe-not-quite - it was used to create the main component of the cataloged item, but there's no "kodachrome 35mm ISO400" available for sampling either.

I see what you mean. I don't expect that we would start asking artists to name all the tools, brushes, machines, etc that were used to create their work and then index them, but since we do have the camera and film used for many of our collection objects, I think it makes sense for us to add them in somewhere. And camera and film are something that I could see potentially being searched, whereas brushes used is far too specific.

> Verbatim information is good and could go in the attribute remark, but standardized information will be better in the long run for discoverability. Always assume that you will not be the only collection using this attribute. The next art collection may have different data sheets with the same information recorded in a different way. Standardizing will make it easier for everyone to use.

So each of these could be an attribute with controlled entry for all the variations of what film and cameras could have been used and the verbatim can go into the remarks? What I was hoping for is to have a place to add this into records when I come across it, as opposed to turning this into its own project. This is low priority for us, so maybe if controlled entry is the solution, we can just put this aside until sometime in the future when that or something like it can be created.

**Comment by Jegelewicz** [comment]
> So each of these could be an attribute with controlled entry for all the variations of what film and cameras could have been used and the verbatim can go into the remarks? 

They could be.

> What I was hoping for is to have a place to add this into records when I come across it, as opposed to turning this into its own project. This is low priority for us, so maybe if controlled entry is the solution, we can just put this aside until sometime in the future when that or something like it can be created.

Then how about just creating a free text attribute for each? We can always standardize later if it becomes a thing. I'd still suggest that it be a little more generic so that it could be used for scanners, etc.

Imaging equipment: brand, model and other details about the imaging equipment used in the production of the collection object.

Film: brand, type, speed, size and other details about the film used in the production of the collection object.

**Comment by krgomez** [comment]
> I don't expect that we would start asking artists to name all the tools, brushes, machines, etc that were used to create their work and then index them

This comment turns out to be inaccurate the more I have thought about this today. We actually may want to have a way of recording tools, machines and materials involved in art making, not just the materials that make up the object and the techniques used in making it.

You guys are totally right that what we have proposed here is probably too specific. We need to find a broader field that can accurately encompass this information and work for other collections. I have realized that maybe camera and film can be considered implements involved in creation. We have already identified needing a way to index materials and techniques and I realized today that techniques actually encompasses implements in the CDWA. Mareca and I will continue to think about this and look at examples from other institutions. Thanks for your help thinking through this!

**Comment by dustymc** [comment]
Structured data using external vocabularies sounds like a fun experiment!

**Comment by Jegelewicz** [comment]
I LOVE you guys!!!

**Comment by campmlc** [comment]
Adding to this: metadata on magnification, lenses, scope make and model etc
for microscope images.
