### ISSUE TITLE
Common Names Field

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/arctos#2506]
It recently occurred to me:  why can't we use "common names" as an "other Identifier" instead of putting it in with taxonomy?  Since common names appear to be subjective, they still are valuable to respective institutional users.

**Comment by Jegelewicz** [comment]
This would mean that common names are associated with specimens rather than taxa.

**Comment by mbprondzinski** [comment]
Is that a problem?  Why couldn't they be linked some way?

**Comment by Jegelewicz** [comment]
You will have

some Dasyatis = shark
some Dasyatis = ray
some Dasyatis = shark, ray
some Dasyatis = stingray

So if you search "shark", you will likely not get all Dasyatis.

right now in Arctos ALL Dasyatis = 

    fintail stingrays
    ray
    shark
    stingray
    stingrays
    whiptail stingray

so no matter which common name you search, you will get all Dasyatis.

**Comment by mbprondzinski** [comment]
But will I get all the other genera, or should I say taxon of sharks?  Shark is all encompassing.  I'm asking because we are running into the bivalve versus valve versus gastropod with the Invertebrates.

**Comment by Jegelewicz** [comment]
> But will I get all the other genera, or should I say taxon of sharks?

Yep, and then some - because anything that is in any of these orders are "sharks", which is why common names are not super-useful.

Carcharhiniformes
Heterodontiformes
Hexanchiformes
Lamniformes
Orectolobiformes
Pristiophoriformes
Squaliformes
Squatiniformes
† Cladoselachiformes
† Hybodontiformes
† Symmoriida
† Xenacanthida (Xenacantiformes) † Elegestolepis 

>  I'm asking because we are running into the bivalve versus valve versus gastropod with the Invertebrates.


Those are just like "shark". With a list of taxa to which those common names should be applied, we can accomplish the same thing.

**Comment by Jegelewicz** [comment]
BTW, if you only want Dasyatis, searching the common name that is particular to them "whiptail stingray" will only get you Dasyatis (well Dasyatidae, because the whole family are "whiptail stingrays").

**Comment by mbprondzinski** [comment]
If I know what I'm looking for, that is one thing, but common names are useful in pulling a group or "lumping" and then can be whittled down to specifics or "splitting" once a person knows what is there.

**Comment by Jegelewicz** [comment]
But Dasyatis are also "lumped" with rays and sharks and can be whittled from there...

**Comment by mbprondzinski** [comment]
Technically, there is no VISIBLE place to add "shark" in the record.  Since I have not added common names, I do not remember off-hand where and how they are added.  Are they automatically added?  You originally told me to put them in remarks.

**Comment by dustymc** [comment]
>Why couldn't they be linked some way

They are linked in very carefully designed ways, but it's a downhill flow.

Current design: Create a taxon name, add a common name to it, catalog a million specimens and find them all, every time, by the common name. If you need to add a common name, you do it in one place and immediately find all million specimens by it.

What you're proposing: attempt to type "shark" a million times. If you need to add a new common name, use your assuredly imperfect previous attempt to find those million records, then attempt to type the new thing a million times.

>where and how they are added

http://arctos.database.museum/name/Dasyatis

<img width="252" alt="Screen Shot 2020-02-18 at 7 39 34 AM" src="https://user-images.githubusercontent.com/5720791/74751275-de961e80-5221-11ea-8f9e-23d4bd7adde5.png">

<img width="351" alt="Screen Shot 2020-02-18 at 7 39 44 AM" src="https://user-images.githubusercontent.com/5720791/74751349-f8376600-5221-11ea-9132-aed9322657dc.png">

**Comment by Jegelewicz** [comment]
For many of your vertebrates, the common name was added to the identification remark.

![image](https://user-images.githubusercontent.com/5725767/74751499-90d1e400-522a-11ea-9737-2104d4566c9f.png)

 For those that I have worked into taxonomy, they are visible in the classification just under the identification.

![image](https://user-images.githubusercontent.com/5725767/74751552-a21af080-522a-11ea-99c0-2f88e0aa2e8b.png)

**Comment by mbprondzinski** [comment]
I know that, but I am asking if that is the only option.

**Comment by Jegelewicz** [comment]
Currently, yes.

**Comment by Jegelewicz** [comment]
Perhaps if you can give me the data you are working with I can offer up a solution.

**Comment by mbprondzinski** [comment]
Now that we have an Invertebrate Paleontologist, he would like more "parts":  bivalve, valve, gastropod, probably others, which we formerly used as common names in the invertebrate spreadsheet.

**Comment by Jegelewicz** [comment]
>  bivalve, valve, gastropod,

Those are all "shell".

**Comment by mbprondzinski** [comment]
I know.

**Comment by mbprondzinski** [comment]
So if I have to differentiate between a clam and a snail shell, as Dusty said, I will have to write into remarks 1,000,000,000 times “gastropod” or “bivalve.”  Correct?

**Comment by Jegelewicz** [comment]
So if I have to differentiate between a clam and a snail shell, as Dusty said, I will have to write into remarks 1,000,000,000 times “gastropod” or “bivalve.”  Correct?

Clam shell = identification Bivalvia plus part = shell
Snail shell = identification Gatropoda plus part = shell

**Comment by mbprondzinski** [comment]
Currently, we have bags of mixed lots, which we haven’t had the time to separate out.  We have single valves and bivalves and maybe one gastropod.  I just entered the record 20177 which is just one of many to come.

**Comment by Jegelewicz** [comment]
@mbprondzinski the way you have done that is awesome! The only thing I would suggest is to create two parts, one with shell (fossil), quantity 26 and the remark bivalves and the second with shell (fossil), quantity 1 and the remark gastropod.

Eventually, the gastropod should just be given its own catalog number and the two records should be related with the "same lot as" relationship.

**Comment by Jegelewicz** [comment]
Please note addition of "gastropod" and "bivalve" to common names for Mollusca.

**Comment by mbprondzinski** [comment]
All right...thanks.
