### ISSUE TITLE
WoRMS (via Arctos) or DMNS WoRMS?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2507]
I've been away (vacation) from this thread.  I was unaware anyone else was adding taxa to WoRMS (via Arctos) and I really want to keep it as pristine as possible.   

_Eutrochatella regina_ was abundant in 1914 (per the source you quote) but the odds are that the genus has changed.  Eutrochatella is in the family Helicinidae.  Is it possible that your specimens are _Viana regina_ (Morelet, 1849)?  (You can find this by doing an "advanced search" in WoRMS.  Remember that terrestrial species are less well represented in WoRMS so not all valid taxa are included - but every week more and more are added.  I think most of the species in this thread are terrestrial which is why they are not yet in WoRMS (via Arctos) which is why any collection with terrestrial mollusks will frequently need to add taxa.  Also, there is much less agreement on terrestrial taxonomy so we need to decide who (what institution or sources) we think are most valid and try to stick with them.  

I would like to make a request that no taxon name be added
1) without a valid source authority
2) without an author
3)  if it is invalid unless there is a flaming reason to add it.

For example, there is no author on the _Eutrochatella regina_ entry.  If it is Morelet, then it's likely that the current genus is Viana.  If it's some other author, then Viana is unlikely and we need to do more research.  

I'd also like to have procedures that we always add a new species by cloning the WoRMS (via Arctos) genus so that the higher classification is always the same.

@Jegelewicz Teresa, can we add this to our agenda for Wednesday and set up some guidelines?  I'm paranoid about WoRMS (via Arctos) slowly acquiring the same problems that Arctos and Arctos Plants have and that I spent months of my life trying to clean up before we were able to switch over to WoRMS (via Arctos).

Also, Teresa, what do you mean by _Euhadra quaesita {Eulota quaesita}_.

@dustymc Dusty, now that multiple institutions are adding and modifying WoRMS (via Arctos), can we get a daily report (like we get for new Higher Geography) that lists the taxon classifications added. to WoRMS (via Arctos).  I can decide if I want to look over the entry or not, but at least I know what's being added and the other users of WoRMS (via Arctos) can see what I add as well.

_Originally posted by @sharpphyl in https://github.com/ArctosDB/data-migration/issues/39#issuecomment-587245628_

**Comment by Jegelewicz** [comment]
Perhaps DMNS needs their own version of WoRMS (via Arctos)?

**Comment by dustymc** [comment]
>DMNS needs their own version of WoRMS (via Arctos)

WoRMS (via Arctos) is theirs, and I think it's reasonable for the founding collection to set rules. @sharpphyl if you want to write up something I can add it (or a URL to it) to https://arctos.database.museum/info/ctDocumentation.cfm?table=CTTAXONOMY_SOURCE.

Perhaps NMMNH needs a new classification, but maintaining that would be quite a bit of overhead.

**Comment by Jegelewicz** [comment]
> Perhaps NMMNH needs a new classification, but maintaining that would be quite a bit of overhead.

But we also want the functionality of WoRMS (via Arctos). I have no problem with ground rules, but also need to have some flexibility.

**Comment by Jegelewicz** [comment]
> I would like to make a request that no taxon name be added
> 
>   1. without a valid source authority
>   2. without an author
>   3. if it is invalid unless there is a flaming reason to add it.

1. Agree, except what is considered a valid source authority?
2. Some taxa do not have an author (orders and such often do not include one)
3. Invalid taxa were often valid at one point in time but have been synonomised, these should be able to be used to indicate an original identification as long as the appropriate synonym relationships are created.

**Comment by dustymc** [comment]
>what is considered a valid source authority?

@sharpphyl ??

>Some taxa do not have an author

I think they do, even if it's not commonly used. 

>used to indicate an original identification

That does not require a classification in the preferred source. (@sharpphyl are you deleting things from WoRMS (via Arctos) as they fall out of favor, or ?????)

**Comment by Jegelewicz** [comment]
> 
>     Some taxa do not have an author
> 
> I think they do, even if it's not commonly used.

But I can't spend forever trying to track it down!

**Comment by Jegelewicz** [comment]
> For example, there is no author on the Eutrochatella regina entry. If it is Morelet, then it's likely that the current genus is Viana. If it's some other author, then Viana is unlikely and we need to do more research.

I can find nothing that demonstrates that Eutrochatella regina is a synonym of Viana regina. I often see Eutrochatella in works that also discuss Viana regina, but I have yet to find text that states the two are synonyms. I can't find an author for Eutrochatella regina, just the single Google book which references the species name. We can always use Eutrochatella {Eutrochatella regina} if this one is bothersome but that does lead to some restraints.

If someone eventually finds the source for the synonomy of the two names, it can easily be added if the two names exist in Arctos, if I go with A {string}, Eutrochatella regina will not exist in taxon names and it is unlikely that anyone will ever add the synonomy.

> I'd also like to have procedures that we always add a new species by cloning the WoRMS (via Arctos) genus so that the higher classification is always the same.

That is exactly what I did for Eutrochatella regina. I think it is what we should suggest for any species classification added in any taxonomy source, however, if someone is cloning from GBIF they are unlikely to check to see if the classification is different from the genus already in Arctos since GBIF will provide the entire classification.

**Comment by Jegelewicz** [comment]
> 
>     DMNS needs their own version of WoRMS (via Arctos)
> 
> WoRMS (via Arctos) is theirs, and I think it's reasonable for the founding collection to set rules. @sharpphyl if you want to write up something I can add it (or a URL to it) to https://arctos.database.museum/info/ctDocumentation.cfm?table=CTTAXONOMY_SOURCE.

Theirs? How would anyone possibly know that?

**Comment by sharpphyl** [comment]
> DMNS needs their own version of WoRMS (via Arctos)

>WoRMS (via Arctos) is theirs, and I think it's reasonable for the founding collection to set rules. @sharpphyl if you want to write up something I can add it (or a URL to it) to https://arctos.database.museum/info/ctDocumentation.cfm?table=CTTAXONOMY_SOURCE.

I don't think we need our own version.  I'm being terribly protective, I know, but WoRMS (via Arctos) is a good test of our ability to link to a source curated outside of Arctos and maintain the quality and consistency as we add needed taxa.  I've added hundreds of taxa (almost all terrestrial or fresh water mollusks) and some of them have the same problems of source and author and it's taken me hours to try to clarify them, so I do understand that it can be a hassle to add taxa.

After our meeting today, I'll try to come up with some "rules" that  maximize the quality of the WoRMS (via Arctos) source without overburdening those who use this taxon source.

**Comment by Jegelewicz** [comment]
Also is it possible to flag taxon names of classifications with an aphiaID?

**Comment by Jegelewicz** [comment]
We should also email everyone with taxonomy access with a reminder of the "rules". @sharpphyl will draft an email. I will get list of Taxonomy peeps from @dustymc

**Comment by Jegelewicz** [comment]
@dustymc can you write SQL to find all classifications in the WoRMS (via Arctos) source that don't have an aphiaID?

**Comment by dustymc** [comment]
>being terribly protective

FWIW I absolutely don't see that as a problem! I think the only problem is the lack of documentation in the code table, for which you can all fully blame me. Oh well, now we know.

>without overburdening those who use this taxon source

I also don't see this as much of a problem. You can create the name, catalog specimens, and add classification data when you can, or split off your own classification if you don't like the "rules" in some other Source. (Disagreeing over the "rules" - or goals or something - is a very large part of where all this complexity came from. I'm surprised this sort of thing hasn't been more common.)

>Also is it possible to flag taxon names of classifications with an aphiaID?

Hu? If you're asking about creating "WoRMS (via Arctos) classifications, the best way to do that is to just provide the aphiaid - Arctos will figure it out from there (or you can click the button).

> list of Taxonomy peeps

<img width="420" alt="Screen Shot 2020-02-19 at 1 24 31 PM" src="https://user-images.githubusercontent.com/5720791/74878007-4ed49b00-531b-11ea-9f78-4dfb0af2d702.png">

MANAGE_TAXONOMY

    ACDOLL (OPEN)
    ACHINN (OPEN)
    ACOCONIS (OPEN)
    ACOTTER (LOCKED)
    AECARRIER (LOCKED)
    AEROCHILD (OPEN)
    AGOROPASHNAYA (LOCKED)
    ALANBATTEN (OPEN)
    ALISONWHITING (OPEN)
    ANDRES_LOPEZ (OPEN)
    AREN (OPEN)
    ARGASTALDI (LOCKED)
    ATROX (OPEN)
    BJOHNSON_DMNS (OPEN)
    CAMPMLC (OPEN)
    CAMWEBB (OPEN)
    CANTRELL (OPEN)
    CARLSLIEB (OPEN)
    CAROLYN (OPEN)
    CCICERO (OPEN)
    CDARDIA (LOCKED)
    CEMYERS (LOCKED)
    CFILIPEK (OPEN)
    DEMBOSKI (OPEN)
    DGSTEWART (OPEN)
    DHUNT (OPEN)
    DLM (OPEN)
    DPERRIGUEY (OPEN)
    DROBERTS (OPEN)
    EBRAKER (OPEN)
    EJBROCK (OPEN)
    EKRIMMEL (LOCKED)
    FFDSS (OPEN)
    FISHSPECIATION (OPEN)
    FRIEL (LOCKED)
    GARTHSPELLMAN (OPEN)
    GORDON (LOCKED)
    HKBERRIOS (LOCKED)
    JBWILLIAMSON (OPEN)
    JDWITTS (LOCKED)
    JEGELEWICZ (OPEN)
    JEMA9330 (OPEN)
    JLDUNNUM (OPEN)
    JLUNDQUI (LOCKED)
    JMALANEY_1 (LOCKED)
    JMALEY1 (OPEN)
    JMETZGAR (LOCKED)
    JOSECOOK (LOCKED)
    JTGIERMAK (OPEN)
    JULIANCHAVEZ449 (LOCKED)
    JWURTZ01 (OPEN)
    KATHERINELANDERSON (LOCKED)
    KMDALY (OPEN)
    LAM (OPEN)
    LBROSKEY (LOCKED)
    LINDSEYFREDERICK (OPEN)
    LJMULLEN2 (LOCKED)
    MAKAYLAMQZ (LOCKED)
    MBOWSER (OPEN)
    MBPRONDZINSKI (OPEN)
    MJANDERSEN (OPEN)
    MKOO (OPEN)
    MLMOODY (OPEN)
    MONA (OPEN)
    NICOLERIDGWELL (OPEN)
    OPHIS (OPEN)
    PATTON (OPEN)
    PDRUCKEN (LOCKED)
    RROVELLI (LOCKED)
    SARA (OPEN)
    SHARPPHYL (OPEN)
    SKANIE (LOCKED)
    STEFFI (OPEN)
    TIMO_SP (LOCKED)
    VOLEGUY (OPEN)
    VTHILL (OPEN)

>SQL

```
create table temp_wrmnaid2 as select scientific_name from taxon_name,taxon_term where taxon_name.taxon_name_id=taxon_term.taxon_name_id and source='WoRMS (via Arctos)' and not exists (
		select tt.taxon_name_id from taxon_term tt where tt.taxon_name_id=taxon_name.taxon_name_id and term_type='aphiaid' and source='WoRMS (via Arctos)'
	);

UAM@ARCTOS> select count(*) from temp_wrmnaid2;

  COUNT(*)
----------
     24074

```

[temp_wrmnaid2.csv.zip](https://github.com/ArctosDB/arctos/files/4227647/temp_wrmnaid2.csv.zip)

**Comment by Jegelewicz** [comment]
> 
> 
>     Also is it possible to flag taxon names of classifications with an aphiaID?
> 
> Hu? If you're asking about creating "WoRMS (via Arctos) classifications, the best way to do that is to just provide the aphiaid - Arctos will figure it out from there (or you can click the button).

Was thinking more of a way for users to easily see that a classification came from WoRMS (and therefore might inspire more confidence. Like a gold star or something...

**Comment by sharpphyl** [comment]
I have updated several of our "how to" documents to clarify the different way that the source WoRMS (via Arctos) is managed (vs. Arctos and Arctos Plants) and how we would like to maintain its classification consistency when new taxa are added.

1.  ADDED.  In How to Manage Taxonomy Hierarchically.
Using the Hierarchial Editor
Overview
"Note that the Hierarchical tool can only be used to structure classifications in Arctos and Arctos Plants.  It cannot be used to clean up classifications in the source WoRMS (via Arctos) which is managed externally by the World Register of Marine Species. "

2.  I added a new "how to" section at https://handbook.arctosdb.org/how_to/How-to-Create-Taxa-in-Externally-Managed-Sources.html.  Comments and corrections are invited.  There's nothing in here that wouldn't be ideal if we all followed it (or had in the past) for Arctos and Arctos Plants.  I just emphasized our goal of keeping this source as accurate as possible until that magical day when WoRMS contains all the taxa we ever want to use.  

Teresa, I thought instead of emailing "rules" it might be easier to remind everyone with taxonomic authority that we have "how to" sections on almost all taxonomic tasks and we just added this new one and ask them to read it before adding taxa to WoRMS (via Arctos).

@dustymc Is it possible to add a pop-up when a user choses to add a taxon name to WoRMS (via Arctos) 

![Screen Shot 2020-03-01 at 6 11 01 PM](https://user-images.githubusercontent.com/15368365/75639006-f12e3180-5beb-11ea-91be-c56327be3d5f.png)

that would read: You are creating a taxon name to an externally-managed taxonomic source.  Review the requested procedures [here](https://handbook.arctosdb.org/how_to/How-to-Create-Taxa-in-Externally-Managed-Sources.html) before proceeding.  

I'll get to close that pop-up hundreds of times, but it might prevent some inadvertent errors.

**Comment by sharpphyl** [comment]
Ideally the pop-up would have a "close" button and a "do not show this warning again" button.

**Comment by dustymc** [comment]
>pop-up 

Not much technical problem with that, just makes the UI a bit more complicated.

I keep hearing that those don't get read, so I'm not sure how effective it would be.

It won't do anything for the bulkloaders or any UIs built on APIs.

This is probably something that should be in the documentation - 'various Sources exist for various reasons, read https://arctos.database.museum/info/ctDocumentation.cfm?table=CTTAXONOMY_SOURCE before....'

We might even do something with VPDs - only allow users who have access to a collection that prefers SOURCE to manage SOURCE or something.

**Comment by sharpphyl** [comment]
Let's see if the others on the Taxonomic committee think the pop-up would help.  

> It won't do anything for the bulkloaders or any UIs built on APIs.

I understand a pop-up won't do anything for bulkloaders, but I don't understand why anyone using WoRMS (via Arctos) would  have enough taxon names and classifications to add that they would need a bulkloader.  Every week, I find I need to add fewer and fewer terrestrial and freshwater species because WoRMS now includes them.  Perhaps someone with an extensive list of needed taxa can clarify the type of taxa missing in WoRMS.

> This is probably something that should be in the documentation - 'various Sources exist for various reasons, read https://arctos.database.museum/info/ctDocumentation.cfm?table=CTTAXONOMY_SOURCE before....'

DONE

I think limiting those who can create taxa in externally-managed sources to those who use that source might be a good idea.  On the other hand, although I don't use Arctos, I do occasionally correct entries when I see a problem and others might do the same on a WoRMS (via Arctos) entry (without an aphiaID) that is incorrect.

**Comment by dustymc** [comment]
>don't  understand why anyone 

Because they can! Why **wouldn't** someone choose WoRMS (via Arctos) for their termite collection and bulkload a million mostly-synonyms, overwriting the aphiaids while they're at it?

I'm probably not going to lose any sleep over that idea just yet, but it is the sort of thing we need to be thinking about as Arctos grows and we add more ways to access the data. Documentation is an easy first step; what we do beyond that should probably be discussed somewhere more visible than here. (I don't think any of that would stop me from making a simple change to the UI, just being paranoid on your behalf....)

**Comment by sharpphyl** [comment]
Yikes!  Yes, let's limit access to making changes/additions to WoRMS (via Arctos) if you ever think it wise to do so.

**Comment by Jegelewicz** [comment]
>  On the other hand, although I don't use Arctos, I do occasionally correct entries when I see a problem and others might do the same on a WoRMS (via Arctos) entry (without an aphiaID) that is incorrect.

This is exactly why we shouldn't limit access. We are here to help each other!

> Why wouldn't someone choose WoRMS (via Arctos) for their termite collection and bulkload a million mostly-synonyms, overwriting the aphiaids while they're at it?

Because we guide incoming collections choices on taxonomy source. I would not advise an arthropod collection to use WoRMS (via Arctos) unless I really understood their need for it and I was sure they understood how the source works.

I added a single name that is uncertain and I have offered to take it out if it is offensive. Has anyone besides me done something drastically incorrect in WoRMS (via Arctos)? Has anyone bulkloaded classifications to that source? I think we might be getting all worked up with very little reason. @sharpphyl has added documentation and I'm OK with the pop-up (but I'm not sure that people will read either of these as people don't read). I think the most impactful thing we can do is to properly train everyone with taxonomy access.

Again, if this source needs to "belong" to Denver, I don't have a problem with that, but then we need to create an equivalent that we can use here in New Mexico. If this is going to be a perk of using Arctos (as we have been saying in our presentations and "marketing") then it needs to be available to anyone who wants to make use of it. Otherwise, we need to stop touting it.

**Comment by dustymc** [comment]
>Because we guide incoming collections choices on taxonomy source

We should do better by making https://arctos.database.museum/info/ctDocumentation.cfm?table=CTTAXONOMY_SOURCE much more descriptive

>most impactful thing we can do is to properly train everyone with taxonomy access

Given the current situation, agreed, that's sufficient. We still need to be thinking about the difference between rules and UI suggestions, even if it just turns into a "thou shalt..." clause on whatever paperwork comes with an API key.

I don't think we can decide if we need to duplicate WoRMS without that detailed documentation.

(FWIW I'm still not quite understanding the objections, particularly those around "acceptedness." I'm pulling maybe-unaccepted names from WoRMS every day. Should I not be?!?)

**Comment by Jegelewicz** [comment]
> (FWIW I'm still not quite understanding the objections, particularly those around "acceptedness." I'm pulling maybe-unaccepted names from WoRMS every day. Should I not be?!?)

I agree here - there are plenty of published "unaccepted" names and things have been identified with them. We want to record that!

**Comment by sharpphyl** [comment]
> Again, if this source needs to "belong" to Denver, I don't have a problem with that, but then we need to create an equivalent that we can use here in New Mexico. If this is going to be a perk of using Arctos (as we have been saying in our presentations and "marketing") then it needs to be available to anyone who wants to make use of it. Otherwise, we need to stop touting it.

I see no reason have any externally managed source belong to just one collection.  I agree having them available to everyone is one of the assets of Arctos.  If everyone is ok with the documentation and there is good training (which I know new collections are getting today), then I think we're fine.  
And I don't have a huge issue with adding invalid terms as long as they are linked to the valid term and have a consistent classification.  

> (FWIW I'm still not quite understanding the objections, particularly those around "acceptedness." I'm pulling maybe-unaccepted names from WoRMS every day. Should I not be?!?)

Can you tell me what you're pulling?  I'm not adding anything that I don't think is valid or that doesn't have a source, but the source may not be among those that you query.  I've added a lot of terrestrial species that aren't yet in use but will be as we start to database them so I'd hate to have to add them again.

**Comment by dustymc** [comment]
>Can you tell me what you're pulling?

Anything that pops up in WoRMS and meets our "isValidTaxonName" test.

Those should all be my idea of "valid" - they look like a Linnean namestring and hopefully WoRMS isn't adding much that can't at least theoretically be traced back to something that someone at some point considered to be "taxonomy literature." (They couldn't safely be integrated with Arctos if they did, so let's hope that never changes!)

They're definitely not all any particular flavor of "you should use this for THAT" "valid," which is what I think you mean.

**Comment by sharpphyl** [comment]
Actually, @dustymc I'm asking if you have a list of what you've pulled because of the Validator Results. 
 Theoretically, there shouldn't be anything in WoRMS (via Arctos) that doesn't meet our validator search, so I'm curious what doesn't meet our "isValidTaxonName" test to see if they are taxon names that I added.

Theresa, I have no problem with the taxon you added: _Eutrochatella regina_.  Hope you don't mind that I did add a comment that it may be a synonym of _Viana regina_ to help our volunteers who might run across that name and an additional remark:  "appears to be an earlier (1916) name for Viana regina used by John B. Henderson in his book The Cruise of the Tomas Barrera and in a Nautilus article XXVII."

Overall, I think the WoRMS (via Arctos) source will be fine, but it's a good opportunity to reiterate what are ideal standards for taxonomy records.

**Comment by dustymc** [comment]
No I don't have a list. I can approximate from the things added by the DB user - that'll be mostly worms, with a couple big slugs from paleobiodb and such mixed in.

Here's what was created by scripts in the last month - I'm sure these are mostly from WoRMS.

```
UAM@ARCTOS> select count(*) from taxon_name where CREATED_DATE>sysdate-30 and CREATED_BY_AGENT_ID=0;

  COUNT(*)
----------
      4232
```

Here's the last year by user:

```
UAM@ARCTOS> select getPreferredAgentName(CREATED_BY_AGENT_ID) cb,count(*) c from taxon_name where CREATED_DATE>sysdate-365 group by getPreferredAgentName(CREATED_BY_AGENT_ID) order by getPreferredAgentName(CREATED_BY_AGENT_ID);


CB									C
------------------------------------------------------------ ------------
Alison Whiting							       77
Andrew Charles Doll						       10
Anna Chinn							       62
Carol L. Spencer							3
Christopher J. Conroy							5
Colleen Filipek 							4
Collin McCord								1
Derek S. Sikes							       61
Dustin Perriguey						       16
Dusty L. McDonald							2
Emily Braker							       71
Erika J. Brock							      143
Hannah Cantrell 						      221
J. Tomasz Giermakowski						       10
James L. Patton 							6
James M. Maley								3
Jessica Mailhot 							6
Jonathan L. Dunnum							6
Lindsey M. Frederick						      213
Mariel L. Campbell							5
Mary Beth Prondzinski						       16
Matt Bowser							       24
Michael J. Andersen							2
Mingna Zhuang							      313
Phyllis Sharp							      287
Sara V. Brant							       19
Teresa J. Mayfield-Meyer					      723
unknown 							  378,468

28 rows selected.
```

I can unroll user/date/name however you want.

isValidTaxonName is a hard rule - it rejects things like WoRMS subgenus format.

The "validator service" is a suggestion; it might make a user click another button or something, but that's it.

>reiterate what are ideal standards for taxonomy records.
 
Yes, I'd like to see some sort of documentation come out of this before it finds a way to become some sort of huge problem.

I think we're pretty solid on "what's taxonomy?" - http://handbook.arctosdb.org/documentation/taxonomy.html

The answer to "should I add THIS classification to THAT source?" is still a great mystery. WoRMS is a great place to explore that - we all more or less know what we're doing with that, it's just a little fuzzy around the edges. Adding plants to Arctos (because it's used by paleo collections) is potentially a much bigger deal - we pulled plants out of there because there are thousands of hemihomonyms, are we really sure we want to slowly un-do that? What's it mean for paleo classifications if the answer is no? Are "paleotaxa" actually problematic, or is that just extant plants? Who gets yelled at when all the paleo-spiders are suddenly claiming to be paleo-ferns (again)? (Not it!) Etc. 

I still think a good first step is detailed and extensive documentation in https://arctos.database.museum/info/ctDocumentation.cfm?table=CTTAXONOMY_SOURCE.

**Comment by sharpphyl** [comment]
@dustymc, I totally misunderstood what you meant when you said you were "...pulling maybe-unaccepted names from WoRMS every day."  

I thought you were deleting the WoRMS (via Arctos) classification and the taxon name.  But I think you mean that you are downloading (pulling) "unaccepted" (by WoRMS) names  ("invalid" in Arctos lingo) into WoRMS (via Arctos) which is exactly what I would hope you are doing.  

I'm fine with where we are on this issue if you two and the committee members are.   We can always make adjustments as need.

> I still think a good first step is detailed and extensive documentation in https://arctos.database.museum/info/ctDocumentation.cfm?table=CTTAXONOMY_SOURCE.

Teresa, should we add this to our next meeting agenda?

**Comment by Jegelewicz** [comment]
> Teresa, should we add this to our next meeting agenda?

Probably, but now @anna-chinn is heading up the taxonomy committee! :-)

**Comment by sharpphyl** [comment]
You've done a great job, Teresa, but I know you already have more than enough to do.  Congratulations, Anna.  Let me know how I can help.

**Comment by sharpphyl** [comment]
@dustymc Can you explain to me exactly what this SQL in your post above of February 19th reports?  Thanks.  

>  SQL
> 
> create table temp_wrmnaid2 as select scientific_name from taxon_name,taxon_term where taxon_name.taxon_name_id=taxon_term.taxon_name_id and source='WoRMS (via Arctos)' and not exists (
> 		select tt.taxon_name_id from taxon_term tt where tt.taxon_name_id=taxon_name.taxon_name_id and term_type='aphiaid' and source='WoRMS (via Arctos)'
> 	);
> 
> UAM@ARCTOS> select count(*) from temp_wrmnaid2;
> 
>   COUNT(*)
> ----------
>      24074

**Comment by dustymc** [comment]
It's WoRMS (via Arctos) that don't have aphiaid.

**Comment by sharpphyl** [comment]
@dustymc 
I ran the SQL in your May 19th post and get this error message: The code you submitted contains illegal characters.

Can you confirm how I should enter that SQL to find out what taxon entries in WoRMS (via Arctos) don't have aphiaIDs?  Thanks.

**Comment by dustymc** [comment]
```

select scientific_name from taxon_name,taxon_term where taxon_name.taxon_name_id=taxon_term.taxon_name_id and source='WoRMS (via Arctos)' and not exists (
select tt.taxon_name_id from taxon_term tt where tt.taxon_name_id=taxon_name.taxon_name_id and term_type='aphiaid' and source='WoRMS (via Arctos)'
) group by scientific_name order by scientific_name

```

**Comment by Jegelewicz** [comment]
Added to SQL Cheat Sheet https://docs.google.com/document/d/15e3b8WNErFPqg1SW-QNq0nI_RjiEEZjWQDznxIJNFHE/edit#heading=h.ws2jj3kd36ng

**Comment by sharpphyl** [comment]
Perfect.  Thanks, Dusty.

@Jegelewicz I ran the SQL and got 1452 taxon names without an aphiaID.  Interestingly, I ran them through the WoRMS Match tool and 580 of them have an aphia ID, so I'll try to figure out why the aphiaID isn't coming through the WoRMS (via Arctos) and add it, then work on the remaining ones.  We can rerun this SQL each year and see if there are new WoRMS entries for the names without and aphiaID.

I think we're close to closing this issue.  I've written recommended procedures for adding taxa to WoRMS (via Arctos) and don't see any issues with that.  

We do have this suggestion pending (from March 6) that we could address tomorrow in the committee meeting:   

> I still think a good first step is detailed and extensive documentation in https://arctos.database.museum/info/ctDocumentation.cfm?table=CTTAXONOMY_SOURCE.

**Comment by sharpphyl** [comment]
With the new dynamic classifications, we should be able to avoid adding anything to WoRMS (via Arctos) without an aphiaID.  That will result in a huge modification (almost a deleting) of the how-to https://handbook.arctosdb.org/how_to/How-to-Create-Taxa-in-Externally-Managed-Sources.html.  Once we get everything cleaned up in WoRMS (via Arctos) this issue should be compete for our collection.

**Comment by Jegelewicz** [comment]
Closing as I think making WoRMS (via Arctos) "clean" resolves the issue.

**Comment by sharpphyl** [comment]
@Jegelewicz   Shall we move this to the Implemented column?  I think it's all resolved.

**Comment by Jegelewicz** [comment]
Done, thanks!
