### ISSUE TITLE
Need more deatils when selecting loan parts

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2508]
When selecting parts for loans, the only information provided is the part name, but in paleo we often have multiple parts with the same name and only one was loaned. If I could also see the part attributes during the add parts to loan process, then I could identify which molar was actually loaned out.

**Comment by dustymc** [comment]
Done in PG

<img width="473" alt="Screen Shot 2020-02-21 at 11 04 16 AM" src="https://user-images.githubusercontent.com/5720791/75063517-efe96000-5499-11ea-990a-149f717b194b.png">
