### ISSUE TITLE
Are we still updating WoRMS (via Arctos)?

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#2510]
Recently, I've had to add taxon names and classifications that are in WoRMS but haven't been added to WoRMS (via Arctos).

See, for example, Caledomelanella frustulum http://www.marinespecies.org/aphia.php?p=taxdetails&id=1314211 which is in WoRMS but not in WoRMS (via Arctos). I also just added Caledomelanella mariei as we needed it for an identification.

**Expected behavior**
In the past, it seemed that our WoRMS (via Arctos) reflected almost everything in WoRMS at that time.

We can add these easily, but I just need to know if (perhaps because of PG) we're not updating the taxon names/classifications as frequently.

Please assign a priority-label.
Medium priority.

**Comment by dustymc** [comment]
It's still running, but it's possible that the scripts have choked on something from time to time. That one seems to have been added about the time we were working things out, so it probably fell through the crack in between the initial import and the daily check being established.

**Comment by sharpphyl** [comment]
Thanks for the clarification.  Is it of any value to you to have a list of taxa that are missing as I come across them?
