### ISSUE TITLE
Add accessions to a project

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2511]
@dustymc I need to add several hundred accessions to a project. I have attached a csv that I think you can use to do this for me. Let me know if this won't work.

Thanks!
[Project Accessions.zip](https://github.com/ArctosDB/arctos/files/4221184/Project.Accessions.zip)

**Comment by dustymc** [comment]
done

**Comment by Jegelewicz** [comment]
I have a few more to
[Project Accessions.zip](https://github.com/ArctosDB/arctos/files/5300052/Project.Accessions.zip)
 add to this project. @dustymc can you do this please?

**Comment by dustymc** [comment]
```

arctosprod@arctos>> select * from temp_prjl where tid is null;
 collection | accn_number | project  | tid 
------------+-------------+----------+-----
 NMMNH:Geol | 1987.01     | 10003251 |    
 NMMNH:Geol | 1990.04     | 10003251 |    
 NMMNH:Geol | 1991.01     | 10003251 |    
 NMMNH:Geol | 1991.02     | 10003251 |    
 NMMNH:Geol | 1995.02     | 10003251 |    
 NMMNH:Geol | 1998.12     | 10003251 |    
 NMMNH:Geol | 1999.03     | 10003251 |    
 NMMNH:Geol | 2001.02     | 10003251 |    
 NMMNH:Geol | 2002.01     | 10003251 |    
(9 rows)
```

need something

**Comment by Jegelewicz** [comment]
Try this
[Project Accessions.zip](https://github.com/ArctosDB/arctos/files/5300139/Project.Accessions.zip)

**Comment by dustymc** [comment]
INSERT 0 121

**Comment by Jegelewicz** [comment]
Thanks!
