### ISSUE TITLE
I'm locked out of Arctos.  I can't log in

### ISSUE THREAD

**Issue by gmward** [ArctosDB/arctos#2514]
I haven't used it in awhile so I forgot my password and now my IP address is locked!

Milt Ward, ALMNH

**Comment by Jegelewicz** [comment]
@gmward what is your Arctos username? @mbprondzinski can you unlock for him?

**Comment by gmward** [comment]
My user name is gmward.

Mary Beth does not believe she has that authority or does not realize that she can unlock me

It appears that my desktop computer, through its IP address, is locked. I could log in on Mary beth’s computer but not mine. Too many failed tries to log in. I got a temp login from the “loss password” function. But bEfore I could create a new password I was locked out from using my desktop.
Thanks for helping out with this issue.
Milt ward

Sent from my iPhone

On Feb 20, 2020, at 7:48 PM, Teresa Mayfield-Meyer <notifications@github.com> wrote:

﻿

@gmward<https://github.com/gmward> what is your Arctos username? @mbprondzinski<https://github.com/mbprondzinski> can you unlock for him?

**Comment by dustymc** [comment]
gmward is not an Operator, and there is no mechanism for locking public accounts.

I can confirm if you'll provide your IP, but any blocks you're likely to encounter (unless you're on a VPN or something) should have a self-service unlock option.

Screenshots and URLs might be useful in figuring out what's going on.

**Comment by campmlc** [comment]
Thanks to all that helped me. I used the password recovery function to
change my password. I used my home computer to do so. So my public user
access is restored. One test will be to attempt a login at my office desk
top.
Milt Ward
Emeritus curator of insects
Alabama Museum of Natural History
