### ISSUE TITLE
New Container Type - trap

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2515]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Goal**
We are going to use object tracking for pest management so we want to barcode our traps and enter container environment information for them that includes information about what was captured.

**Context**
traps are set up in a room so we would like to put the trap containers in the room containers we have set up.

**Table**
http://arctos.database.museum/info/ctDocumentation.cfm?table=CTCONTAINER_TYPE

**Value**
trap

**Definition**
a device or enclosure designed to catch and retain animals, typically by allowing entry but not exit or by catching hold of a part of the body.

**Priority**
We have submitted an abstract to SPNHC2020 where we plan to discuss the potential of object tracking for IPM - we need to have some data!
Please assign a priority-label.

**Comment by campmlc** [comment]
I suggest a more specific term, such as IPM monitor or sticky trap or pest
control station or something other than trap, or it will inevitably be used
for trap numbers for field collection of mammals and arthropods and fish
etc. Then searching for this particular container type will become very
complicated.

**Comment by Jegelewicz** [comment]
I don't care if it gets used in that way - still a trap!

**Comment by dustymc** [comment]
And IPM is but one potential use of the trap, and the trap is but one tool in your IPM toolkit. Agree, it's just a trap, someone scanning a trap into a conveniently-barcoded bush won't affect anything.

**Comment by Jegelewicz** [comment]
I can use the barcode description to indicate it is a sticky trap or whatever...

**Comment by campmlc** [comment]
I just suggest that you use something to filter results out in the future
so you are not getting timeouts in overly broad part location searches.

**Comment by campmlc** [comment]
I think this will work fine if you just make sure you always write "IPM sticky trap", or even better: "NMMNH IPM sticky trap" in remarks when you create the container series and use bulk edit container. I recommend making it possible to use the remarks field to search on particular container types for a given institution. The institution field only works for containers that contain cataloged items, so there needs to be an alternate way of searching containers by institution or collection.

**Comment by dustymc** [comment]
>remarks....search

That's not a reliable path.

>searching containers by institution 

That's just UI.

I'm still not seeing where ``container_type=trap CONTAINED BY {this building/room/etc}`` fails.

**Comment by campmlc** [comment]
The search container_type=trap CONTAINED BY {this building/room/etc} does
not work in this case, because contained_by only allows for a container
type, not a specific barcoded container. I've tried the same search using
In_Barcode, to get all cryotanks or cryovials or freezers in DGR, and it
fails.

 I wish that "just UI" were that simple. I spent 6 hours yesterday trying
to use the UI to get at the number of cyrovials in DGR.  For project
management and end of year reporting we need to be able to search by
institution and by dollection, to get both containers that contain
cataloged items and those that do not and given the limitations of the UI
it is helpful to have multiple paths. Remarks is one of them.

**Comment by dustymc** [comment]
>I wish that "just UI" were that simple.

Me too!

It is important to understand the functional implications of design choices. 

* "Just UI" problems do have a findable answer, even though it may require more resources than we can come up with at the moment. That is, given some sort of structurally-predictable data there's a path to finding all of what you want and nothing that you don't want, and sound reasons to trust the answer.
* Not "just UI" problems do not necessarily have a findable answer, and you can't realistically use the data to know if they do. Maybe you found what you want, maybe you missed some stuff, maybe what you found contains things you don't want. The only way to be sure is to look at everything, and there are currently just under 10 million containers in Arctos. There's no realistic way of knowing what you're looking at.

We've been stuck in a place where UI changes are difficult and dangerous, and things like adding more computing power just aren't possible for quite some time, and I do understand the frustrations that causes. I think we've got a solid solution to all of that, hopefully we can get it implemented soon and I can start to actually do something about "just UI" problems again. Using remarks until that happens is fairly understandable, but that should not be seen as a real solution either.

**Comment by Jegelewicz** [comment]
NMMNH IPM sticky trap will be part of the label - hopefully that will make search easier.

**Comment by Jegelewicz** [comment]
Added trap

**Comment by ebraker** [comment]
I think there is real opportunity to flush out an IPM module for managing IPM tasks - either a separate table that can link to containers, media, taxonomy(?), and charts(?), or if kept as an environmental parameter, a series of linked code tables. 

A checklist of common pest species with a count field is probably easiest when dealing with traps (e.g., we maintain 28 sticky monitors that pick up dozens of bugs each, so typing in names could quickly become cumbersome), though perhaps the check boxes could magically relate to taxonomy.

common museum pests: 

Common | Scientific
-- | --
Webbing Clothes Moth | Tineola bisselliella
Casemaking   Clothes Moth | Tinea pellionella
Brown-dotted Clothes Moth | Niditinea fuscella
unknown Clothes Moth | Tineidae
Angoumois   Grain Moth | Sitotroga cerealella
Indian Meal   Moth | Plodia sp.
unknown Grain   Moth | Pyralidae
Museum Beetle | Anthrenus museorum
Vodka Beetle | Attagenus smirnovi
Black Carpet   Beetle | Attagenus unicolor
Common Carpet   Beetle | Anthrenus   scrophulariae
Varied Carpet   Beetle | Anthrenus verbasci
Furniture Carpet Beetle | Anthrenus flavipes
Dermestid   Beetle | Dermestes maculatus
Larder Beetle | Dermestes lardarius
Odd beetle | Thylodrias contractus
Cigarette   Beetles | Lasioderma serricorne
Drugstore   Beetles | Stegobium paniceum
Sawtoothed   Grain Beetle | Oryzaephilus surinamensis
Foreign   Grain Beetle | Ahasverus advena
Powder-post   Beetle | subfamily: Lyctinae
Shiny spider   beetle | Gibbium aequinoctiale
unknown beetle | Order: Coleoptera
Silverfish | Lepisma saccharina
Firebrat | Thermobia domestica
Springtail | Order: Collembola
Book Lice | Liposcelis sp.
American   Cockroach | Periplaneta americana
Oriental   Cockroach | Blatella orientalis
Western Drywood Termite | Incisitermes minor
Subterranean   Termite | Rhinotermitidae
House Mouse | Mus domesticus
Norway Rat | Rattus   norvegicus
Other |  
Unknown |  

**IPM Attributes** (in addition to tracking **trap location** and **pest name**):

- **Life Stage**

Life   Stage | Definition
-- | --
egg | age_class code table
larva | age_class code table
adult | age_class code table
unknown | age_class code table



- **Risk Category**

risk   category | definition
-- | --
incidental/low | no direct damage but may be a food   source for damaging pests
predator/medium | no direct damage but   feeds on dead insects and may indicate presence of damaging pests
indicator/high | traditional museum   pest that may signal a problem (leaks, unsealed entry points) or cause direct damage to collections
unknown | risk level unknown




We may also want to add pests detected and treatments that link directly to **parts** (via part attributes?) for those pests or signs of pests found directly on objects and not in traps:

- **Pests Detected** (also include related fields for pest_species, detected_date and detected_notes)

Pests Detected | Definition
-- | --
frass | excrement
eggs | eggs
casings | shed larval skins
clippings | fur or feather
exit holes | bore holes
webbing | silken structure
live | live larva or adults found
damage | grazing marks or areas of loss on object(s)


- **Treatment** (also include fields for treatment_begin_date, treatment_end_date, treatment_agent, treatment_notes)

Treatment | Definition
-- | --
low   temperature | use of lethal cold temperatures, freezing
high   temperature | use of lethal warm temperatures, such as solar bagging
anoxic | use of a low-oxygen environment to kill pests, such as  oxygen scavengers or a controlled   atmosphere (CO2, nitrogen, argon chambers)
chemical | pesticides, fumigation
mechanical | lethal trapping

I'm just dumping thoughts...not a request at this point would like to discuss.

**Comment by campmlc** [comment]
Great idea, happy to discuss.

**Comment by Jegelewicz** [comment]
Created a new issue.
