### ISSUE TITLE
Institution Acronym for object tracking different from collections - problem?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2516]
@dustymc I probably made this happen somehow, but the institution acronym available for New Mexico Museum of Nature and Science in object tracking is NMMNHS while all of the collections are under NMMNH. Is this going to cause problems down the road? Can we make the object tracking acronym NMMNH before I get to far along creating stuff for them?

Sorry for being a problem!

**Comment by dustymc** [comment]
There no technical problem with random strings matching up or not, but it might confuse users. Did you create containers? If not you should be able to change whatever you need to. If you did, I can delete the old if they're not used. Used containers would complicate things, but we can deal with it if we have to.

**Comment by Jegelewicz** [comment]
I've created a few containers, but haven't done anything, so they could be deleted. I think it would be good to make the acronym consistent with the collections. Let me know what needs to be done.

**Comment by dustymc** [comment]
I see only one container - you can just delete it in the UI.

```
UAM@ARCTOS> select count(*) from container where barcode like 'NMMNHS%';

  COUNT(*)
----------
	 1

```

**Comment by Jegelewicz** [comment]
I know I have created more than one:

![image](https://user-images.githubusercontent.com/5725767/75069116-c3d7da00-54ad-11ea-8a7a-d1468803858e.png)

It is the Institution acronym that is the problem.

**Comment by dustymc** [comment]
OH! I was out in left field...

The collection creation request was made that way.

```
UAM@ARCTOS> select INSTITUTION_ACRONYM from pre_new_institution where institution_acronym like 'NMM%';

INSTITUTION_ACRONYM
------------------------------------------------------------
NMMNHS


UAM@ARCTOS> select GUID_PREFIX from pre_new_collection where guid_prefix like 'NMM%';

GUID_PREFIX
------------------------------------------------------------
NMMNH:Herp
NMMNH:Inv
NMMNH:Fish
NMMNH:Bird
NMMNH:Mamm
NMMNH:Ento
NMMNH:Herb
NMMNH:Paleo
NMMNH:Geol

```
and the collections were created accordingly.

```
UAM@ARCTOS> select institution_acronym,guid_prefix from collection where institution_acronym like 'NMM%';

INSTITUTION_ACRONYM
------------------------------------------------------------
GUID_PREFIX
------------------------------------------------------------
NMMNHS
NMMNH:Bird

NMMNHS
NMMNH:Fish

NMMNHS
NMMNH:Herb

NMMNHS
NMMNH:Ento

NMMNHS
NMMNH:Herp

NMMNHS
NMMNH:Inv

NMMNHS
NMMNH:Paleo

NMMNHS
NMMNH:Mamm

NMMNHS
NMMNH:Geol


9 rows selected.

```
I believe that would be difficult to change at this point.

**Comment by campmlc** [comment]
So I'm confused. What is the correct acronym? Because we also have this
issue with Other IDs.

**Comment by Jegelewicz** [comment]
For the love of Pete - I've done this for how many collections and it is still clear as mud. I screwed this one up because at some point it was decided that although the actual acronym for this museum is NMMNHS, the collections would be using NMMNH. I guess the only wierdness now will be that their acronym for barcodes won't match their acronym portion of their GUID prefix? Also, when generating stuff for GBIF et al, it will come out incorrect? That one is a problem. Can we fix that when we generate the EML files for VertNet?

**Comment by dustymc** [comment]
>What is the correct acronym? 

Whatever they say it is.

>clear as mud

collection.collection_cde drive code tables
collection.institution_acronym is there BECAUSE, and acts as a sort of "VPD Lite" for containers
collection.guid_prefix is used to form identifiers, and can be a handy human-readable proxy to collection.collection_id

None of those things have any other relationship to each other.

I think the EML-maker pulls guid_prefix apart rather than using data because things like GBIF have unrealistic expectations of "the DWC triplet," but I'm not 100% sure of that.

**Comment by Jegelewicz** [comment]
> I think the EML-maker pulls guid_prefix apart rather than using data because things like GBIF have unrealistic expectations of "the DWC triplet," but I'm not 100% sure of that.

I'll be on the lookout when we get to that.
