### ISSUE TITLE
Higher Geography Russia, Ulyanovsk Oblast

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2517]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Goal**
I need to add this "State" level higher geography.

**Context**
But Russia is split between Asia and Europe. How do I decide if this should be Asia, Russia, Ulyanovsk Oblast or Europe, Russia, Ulyanovsk Oblast?

**Table**
https://arctos.database.museum/geography.cfm

**Value**
See above.

**Definition**
https://en.wikipedia.org/wiki/Ulyanovsk_Oblast

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
Option A:

<img width="613" alt="Screen Shot 2020-02-21 at 7 13 15 AM" src="https://user-images.githubusercontent.com/5720791/75046278-aab53600-5479-11ea-9bfe-95974e5e933c.png">

Option B:

https://en.wikipedia.org/wiki/Eurasia

https://www.youtube.com/watch?v=3uBcq1x7P34

**Comment by Jegelewicz** [comment]
We do have some stuff listed as "Eurasia" - Eurasia, Kazakhstan, but I think I'll go with Europe here. Thanks and now I know what to Google!
