### ISSUE TITLE
Add multiple collection and date range search capability for Loan Search map

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2518]
We need to be able to map all loans from our tissue collection for a date range corresponding to grant funding. Since this is a genomic collection, we issue loans from multiple divisions. Can we request to add functionality to the loan search form to both allow selection of more than one collection, and also to allow a range of dates?

Pending this, for the immediate future grant report, @dustymc can I get this info pulled and mapped for DGR to include all loans from 2014-2019 for all MSB loans with Mariel Campbell as in-house contact?

Priority high

**Comment by dustymc** [comment]
Just search without collection

<img width="725" alt="Screen Shot 2020-02-21 at 8 10 12 AM" src="https://user-images.githubusercontent.com/5720791/75050863-aee55180-5481-11ea-82d2-9bd008c33906.png">

**Comment by campmlc** [comment]
That works! But it still would be helpful to specifically select groups of
collections to map, or alternately, to be able to select and eliminate from
the results list those that we don't want to map.

**Comment by dustymc** [comment]
done
