### ISSUE TITLE
GloBI has links for http://arctos.database.museum/guid/UAM:Herb:141946 however, no link to GloBI is provided

### ISSUE THREAD

**Issue by jhpoelen** [ArctosDB/arctos#2519]
Hi!

I was just doing some testing and stumbled across some unexpected behavior. For instance, GloBI known about http://arctos.database.museum/guid/UAM:Herb:141946 (see [globi searchpage](https://www.globalbioticinteractions.org/?accordingTo=http%3A%2F%2Farctos.database.museum%2Fguid%2FUAM%3AHerb%3A141946&interactionType=interactsWith) )however, no link is provided on the Arctos record page. Is this expected?

**Comment by dustymc** [comment]
Yes it's expected - associated species is free-text, but I guess they spell it right sometimes!

**Comment by jhpoelen** [comment]
@dustymc I was trying to say that the links from Arctos to GloBI no longer seem to appear, even through GloBI has information that relate to records in Arctos. Please confirm.

**Comment by campmlc** [comment]
@Jorrit Poelen <jhpoelen@xs4all.nl> I believe Dusty is referring to the
fact that there is no explicit relationship between the two taxa using
other identifiers/urls, as we usually do in Arctos to create linkages
between records. In this case, the related taxon is not a specimen record
but a taxon name entered into the associated species field in the event
table. Somehow you are pulling from that, but since there is no url
relationship, the GloBi link is not created.

**Comment by jhpoelen** [comment]
@campmlc Thanks for confirming that links to GloBI are only generated when Arctos already established explicit relations. Perhaps this issue is turning more into a feature request. 

As you probably figured, the links that GloBI established for http://arctos.database.museum/guid/UAM:Herb:141946 record and corresponding [GloBI search](https://www.globalbioticinteractions.org/?accordingTo=http%3A%2F%2Farctos.database.museum%2Fguid%2FUAM%3AHerb%3A141946&interactionType=interactsWith)   
are created from the carefully assembled (by the collection manager/curator) associatedTaxa field values ```Empetrum nigrum, Salix pulchra, Carex pluriflora, Carex aquatilis, Dupontia fisheri ssp. psilosantha, Equisetum arvense ``` . GloBI interprets these as individual biotic associations and attempts to link the names to established taxonomic name sources. In effect, GloBI is spell checking the names available through your associatedTaxa fields.

However, I can imagine cases where external collections, lets say some collection hosted by Naturalis in Leiden, the Netherlands, are linking to individual Arctos specimen. GloBI would find this link by indexing the Naturalis collection, and point straight into Arctos. If you would enable linkages to GloBI beyond your records with explicit Arctos-native relations, you'd make it easier to find unknown biotic relation and learn more about how your records are used an linked.

I'd be curious to learn more about concerns you have about enabling more links between Arctos records and GloBI. 

@campmlc please note my github handle is @jhpoelen . the ```@jorrit``` handle is some other Dutch person. Also, I tend to not use my email address in github issues.

**Comment by jhpoelen** [comment]
fyi @seltmann

**Comment by dustymc** [comment]
Aha/derp! 

I'm just checking for links if we have...

eaten by,ate,host of,parasite of

relationships.

Let me know what all you're currently building relationships from and I'll add that, or I can just check everything.

**Comment by campmlc** [comment]
I certainly would support broader linkages to Arctos from external
resources via GloBi, as that is what we are aiming to do from within
Arctos. I will let @Dusty <dustymc@gmail.com> address the issues of linking
to free text entries in associated species. I would think if they are
resolvable (which depends on taxon authority, concept, etc), then a linkage
would be valuable, even if just as a means to resolve potential conflicts.

**Comment by dustymc** [comment]
@campmlc I'm @dustymc 

Arctos is a CMS, and as such I'm REALLY hesitant to get all Clippy and start doing random things which could be misinterpreted as "real data." There are at least three mechanisms in Arctos with which you can form "associations," in descending order of specificity:

1. Relationships link to a specific record
2. Media can link to specific taxon name/classification/concept (OK maybe not the latter but it would be simple to enable)
3. associated species provides a place for hopefully-roughly-typed text, but I can't be sure it's not "definitely didn't see any TAXON today."

I don't think attempting to elevate any of those is appropriate in Arctos.

Attempting magic in something that's not an authoritative source of specimen data is awesome, and hopefully Curators will use some of those data to create more specific relationships.

**Comment by jhpoelen** [comment]
@dustymc @campmlc  thanks for sharing your respective takes on the topic of which GloBI links to expose on Arctos specimen pages.  

My takeaway is that establishing links between projects should be meaningful and add value. And to determine what is meaningful and add value is somewhat subjective. I think our discussion on what GloBI links to make visible through Arctos is particularly of interest to ongoing work as part of the [terrestrial parasite tracker project](https://parasitetracker.org) (cc-ed @seltmann @zaspelj @juliema @neilcobb), particularly the added value to specify the type of association on taxon level  (e.g., ```"associatedTaxa": "has host: Homo sapiens"```) or on the occurrence level (e.g., ```"associatedOccurrences": "(parasite of) MVZ http://arctos.database.museum/guid/MVZ:Mamm:225321"```) and the need to check free-range taxonomic names. 

Note that GloBI can be queried in various ways, so I'd imagine that you can include your criteria (e.g., basis of record, or taxonomic identification) to narrow the kinds of links your prefer to show.

I am looking forward to continued conversations on the topic, perhaps in person at the upcoming Parasite tracker workshop in Chicago 24-25 https://www.idigbio.org/wiki/index.php/Terrestrial_Parasite_Tracker_Workshop:_Best_Practices_and_Standardization_of_Digital_Data_Capture#General_Information .

**Comment by campmlc** [comment]
@jhpoelen  @dustymc apologies on the incorrect tags - I responded from gmail rather than github, and my browser inserted inappropriate values and emails.
I am interested in learning more about this topic and will look forward to our conversations in Chicago. Specifically, I would need to know what specifically is required to "enable linkages to GloBI beyond your records with explicit Arctos-native relations" before bringing this to our community for discussion.

**Comment by juliema** [comment]
agreed and thanks for tagging me in, I am looking forward to discussing
this at the workshop.

Julie

**Comment by dustymc** [comment]
To be clear, I (and I think we-the-community) would like to link to anything for which GloBI has data. I'm currently just trying to be polite to us both by limiting the pre-fetch calls. If you can provide some means by which I can mostly predict that I'll expand my criteria, if you can't, don't want to, are continually changing things, whatever, and are OK with more traffic, then I can just test everything and display the link when I find one.

I don't think most Curators are going to find time to preemptively sift through some free-text field and make links. If GloBI can do the sifting, Arctos can almost certainly pull those data into a 'click to load' format, which is something that might actually become "core data." Any iterations leading to that point are very likely to be useful for everyone involved - you might improve your magic which could lead to unanticipated coolness, we might develop better structure or documentation, change mapping to DWC, etc. Links that absolutely won't ever make it to "specimen data" can be meaningful as well - "gee, this doesn't usually grow near oak trees, someone should check the ID" could be incredibly useful even if we don't end up making any explicit links or claiming it as "data." Etc. etc. etc. Arctos talks to a lot of stuff, and something cool always seems to come from that. I - and again, I believe the Arctos community - see plenty of value in the link itself, and I hope I haven't inadvertently implied something else.

**Comment by jhpoelen** [comment]
Please note that http://arctos.database.museum/guid/UAM:Herb:141946 is now showing the "GloBI" link even though there's no explicit specimen<->specimen relation defined in Arctos. 

See attached screenshots and https://www.globalbioticinteractions.org/?accordingTo=http%3A%2F%2Farctos.database.museum%2Fguid%2FUAM%3AHerb%3A141946&interactionType=interactsWith 
![Screenshot from 2021-05-25 15-13-51](https://user-images.githubusercontent.com/1084872/119575546-14eb1380-bd6c-11eb-86e9-d8f8e05957e9.png)
![Screenshot from 2021-05-25 15-17-06](https://user-images.githubusercontent.com/1084872/119575724-524fa100-bd6c-11eb-9f23-9f03de988a9c.png)

@dustymc thanks for making this happen and please comment/ re-open if issues/questions remain.
