### ISSUE TITLE
Issue with G. Milton Ward as an Agent

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/arctos#2523]
I cannot give Milt Ward permissions because it doesn't recognize him as an Agent.  Teresa entered him as Grover Milton Ward, but it keeps saying "Agent not found."  I have tried editing his information to reflect his name preference (G. Milton Ward), but nothing works.

![image](https://user-images.githubusercontent.com/43214224/75166699-e3f3dd00-56e9-11ea-99ee-6a2de84241e9.png)

I can't figure out how to resolve this.  Needless to say, I spent two hours Saturday evening with an audience (including Milt), trying to get him accepted as an agent without any luck.  Can someone please help???  Thanks.

**Comment by dustymc** [comment]
http://handbook.arctosdb.org/documentation/users.html

>New operators must be agents. Under the Agents tab, locate them if they are an existing agent or, after carefully checking, create them as a new agent. Make sure they have a name-type of “login,” and that their login name exactly matches their Arctos username. These are case sensitive.

**Comment by mbprondzinski** [comment]
Okay, so giving him Agent Name Type of "login" is what was missing!  Thanks
