### ISSUE TITLE
Trouble bulkloading same set as relationships 

### ISSUE THREAD

**Issue by krgomez** [ArctosDB/arctos#2527]
Sorry to bother you with this as I'm sure there's something obvious that I'm doing wrong here. I'm trying bulkload these new "same set as" relationships for some catalog records. Could someone tell me what is wrong with my spreadsheet? 

[tuttle_same set as import.xlsx](https://github.com/ArctosDB/arctos/files/4258016/tuttle_same.set.as.import.xlsx)

**Comment by Jegelewicz** [comment]
Existing other ID type should be "catalog number" - I think that will get it.

**Comment by dustymc** [comment]
CSV please.

(A lot of problems happen in the conversion step.)

**Comment by Jegelewicz** [comment]
Oh! Other ID type should be catalog number too.

**Comment by krgomez** [comment]
GitHub said CSV isn't a supported file type when I tried to upload it.

![Screen Shot 2020-02-26 at 11 45 36 AM](https://user-images.githubusercontent.com/40579515/75386079-813b4680-588d-11ea-8def-07be1ddcf521.png)

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/new?assignees=&labels=&template=bug_report.md&title=

>You may ZIP most formats to attach, or request a Box email address for very large files.

**Comment by krgomez** [comment]
Okay I made a zip file and I changed the existing other ID type to catalog number. But doesn't my new other ID type need to be the UAM:Art so Arctos can find the catalog record? Or am I supposed to add the guid prefix onto the new other id numbers? 

[tuttle_same set as import.zip](https://github.com/ArctosDB/arctos/files/4258128/tuttle_same.set.as.import.zip)

**Comment by dustymc** [comment]
That looks like it should load to me!

**Comment by krgomez** [comment]
Okay thanks! I'll try it again now.

**Comment by krgomez** [comment]
It worked, thanks for your help Teresa and Dusty!
