### ISSUE TITLE
CETAF ISTC Stable Identifier Initiative

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2530]
Just came across this in a Twitter discussion and thought we should be aware (maybe we are and I just don't know it). Anyway, for future reference:

[CETAF ISTC Stable Identifier Initiative](https://cetafidentifiers.biowikifarm.net/wiki/)

**Comment by dustymc** [comment]
> identified by stable HTTP-URIs that will never change. 
>The URI Syntax for the objects is chosen and maintained by the institution 

The Internet doesn't work that way!

``http://herbarium.bgbm.org/object/B100277113`` can in fact be a stable identifier.

Someone can in fact buy http://bgbm.org/ 5 seconds after they forget to pay their bill and redirect it (along with all pages and subdomains) to advertisements for trashcan lids. The identifier is fine, the HTTP-URI not so much.

We will almost certainly stop using the http protocol sometime this side of "never."

Things like DOI are essentially attempts to mitigate those facts. (And some DOIs - like those issued by CrossRef - have some extra magic built in, but that's just icing.)

The good news is, Arctos has apparently been a Level 3 CETAF-thingee for a decade or so.

**Comment by campmlc** [comment]
It was reinforced to me at this iDigBio conference by several people that
we absolutely need to have a "we are Arctos, this is how we do things"
paper out as soon as possible. They need to cite us, and until we publish
we can present posters forever and no one will believe us.

**Comment by Jegelewicz** [comment]
Where - where do we publish?

**Comment by campmlc** [comment]
Biodiversity Data Journal  https://bdj.pensoft.net/

**Comment by Jegelewicz** [comment]
OK, I'll start writing in my massive amounts of free time!

**Comment by campmlc** [comment]
Also, Symbiota published somewhere - find that journal.

**Comment by campmlc** [comment]
I think we just get the grant in and then start modifying it for the paper.

**Comment by dustymc** [comment]
There's been talk of an Arctos publication for many years - https://github.com/ArctosDB/arctos/issues/1463 is perhaps the latest.


I don't know how we effectively communicate what Arctos is, but a LOT of the content of most any conference is people planning to do things that Arctos has been doing forever. It would be pretty awesome to (1) get some recognition for that, and (2) have those people working on something awesome that we haven't already solved (and which Arctos will almost certainly be able to plug into).

**Comment by Jegelewicz** [comment]
Sheesh - that issue was started almost 2 years ago! What we need is a two day retreat to JUST WRITE THE DAMN THING!

**Comment by dustymc** [comment]
The last "Arctos retreat" was certainly a useful event.

**Comment by Jegelewicz** [comment]
closing as paper is in progress - thanks Carla!
