### ISSUE TITLE
Need for Project Search on Main Search Page

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2531]
I would like to request that we add the ability to search on a specific project on the main search page. We currently can search by accession. Perhaps add the project name or ID?
In the meantime, I need results for the following search:

For the following project: https://arctos.database.museum/project/10003273, find number of parts and part locations for all parts with parent container = cryovial.

I can search on all specimens linked to this project, and use the Manage tool in search results to find part locations, but the search times out.

**Comment by dustymc** [comment]
<img width="577" alt="Screen Shot 2020-02-27 at 10 15 41 AM" src="https://user-images.githubusercontent.com/5720791/75473498-23206900-594a-11ea-8a1e-d624d0ba420b.png">

Part locations times out for me as well. We can probably find a way to address that post-PG migration.

**Comment by campmlc** [comment]
Duh, thanks.
