### ISSUE TITLE
No part = "teeth" in Arctos

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#2533]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

MVZ mammals has parts like boxes with a handful of teeth. We do not have part = teeth in arctos, but we do have "tooth" and also specific tooth type. It seems that "teeth" would be a good description of what we have. Agreed?

**Comment by Jegelewicz** [comment]
No - that would create two ways to search for tooth. Use tooth and enter the number of teeth in the part lot count field. If you don't want to count the teeth, make a guess and add that fact to the part remark.

FWIW - this discussion was had a very long time ago!

**Comment by cjconroy** [comment]
I only brought it up because some folks here thought it was worth
bringing to the community. I've since made the change you suggested. It is
better than "skull", which is what we had in there before.
Chris
