### ISSUE TITLE
Need better control on search for tissues in collection in Arctos

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#2534]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

I need to find how many California voles have preserved tissues. Simply clicking on the tissues box and searching by taxon brings up a certain number. However, it is too large because it also brings up tissues that have disposition of discarded. This becomes an issue when tissue requestors request tissue from these kinds of specimens. For my limited skills, my only workaround is to download everything into Excel and filter by part detail column including string "discarded". Surely there is a better way. 
Also, on the query screen, there is a box for querying by part. However, you cannot simultaneously ask for a certain disposition for that part, e.g. "tissue" that is "in collection". 

Near the bottom of the search page, 6 lines up, there is an option for part disposition, but it is not clear to what part that refers!  We might have a specimen parts that are in collection, discarded, and on loan. 

First, I think clicking on the tissue box should mean tissues that have disposition of "in collection".  But, under the part query, we should also be able to select part type, and disposition. That would also be useful to find how many skulls are on loan, etc. 

I suggest this to be a HIGH priority 

Chris

**Comment by ewommack** [comment]
That might be helpful.
Being able to search for disposition could help find parts that are listed:
Being processed

**Comment by dustymc** [comment]
We've been back and forth on what a "tissue" is a few times. It's currently set to just 'some part is flagged as tissue' - easy enough to adjust that, but difficult (and not terribly safe) to update in the current environment. We really need to do something stable, whatever that is.

Part "=tissue" and disposition=in collection treats the part like a data object - that'll return "tissue" (exact match) with disposition=in collection. Without the = it does what you describe. Maybe that's a useful workaround until we can get somewhere that this can easily be changed, or I can help you SQL things.

https://github.com/ArctosDB/arctos/issues/1563 happened; we should probably consolidate part-things instead of leaving bits and pieces in Curatorial.

@ewommack that's always been there - it's in the curatorial pane - but it's only linked to specific parts as described above.

**Comment by ewommack** [comment]
So I would log in and could search/differentiate through the info?

**Comment by dustymc** [comment]
From @cjconroy

**Comment by ccicero** [comment]
@dustymc @cjconroy I understand the issue about the tissue flag, but that's no the only issue.

I just tried searching for part_name contains 'tissue' and part_disposition='in collection' and that is better. Now only 3 'discarded' ones get returned, so e.g., 148058 is excluded which it should be (was returned when using the flag). However, it returns two "tissue extract (frozen)" and one "tissue (frozen)" that were discarded - MVZ:Mamm 156533, 156534, 156557.  Why are those being returned? 

I'm still not sure what all of the text is in part details. Example for MVZ:Mamm:148058:

[{"ID":"13113198","SF":"","PN":"skin, study","LC":"1","DP":"in collection","CD":"unchecked","BC":"","CP":"[  ] Museum of Vertebrate Zoology (institution)","RK":"","PA":[]},{"ID":"15113198","SF":"","PN":"skull","LC":"1","DP":"in collection","CD":"unchecked","BC":"","CP":"[  ] Museum of Vertebrate Zoology (institution)","RK":"","PA":[]},{"ID":"12113198","SF":"","PN":"tissue (frozen)","LC":"1","DP":"discarded","CD":"unchecked","BC":"","CP":"[  ] Museum of Vertebrate Zoology (institution):[  ] 148058.1 (not recorded)","RK":"","PA":[]}]
--

**Comment by dustymc** [comment]
>Why are those being returned?

The form isn't designed to find specific parts, just specimens. This issue will change that.

>not sure what all of the text is

JSON, a way of representing complex data in simple formats. Arctos (and many other tools) will format it for you...


<img width="691" alt="Screen Shot 2020-05-13 at 8 39 20 AM" src="https://user-images.githubusercontent.com/5720791/81834017-498b8480-94f5-11ea-8ee9-4a036abaaadc.png">


... and the key is here:http://handbook.arctosdb.org/documentation/json.html#parts

**Comment by campmlc** [comment]
Yes, I've been needing this too!
"The form isn't designed to find specific parts, just specimens. This issue
will change that. "

Is there some JSON viewer we are supposed to use to convert the csv mess we
get on Arctos download into something readable like the above? Some means
of converting it to multiple columns without having to parse using
character delimiters in Excel?

**Comment by dustymc** [comment]
@campmlc that's probably another issue.

The purpose of downloading is to use tools that aren't available in Arctos - the system is designed so that I have no control over that!

I avoid Excel, but I believe the CSV is valid. I just tried, Google Sheets successfully imports it as text.

I use JSON primarily BECAUSE there's no unavoidable "columns" mapping; if the data can readily be treated as a column, I do so.

**Comment by campmlc** [comment]
I will file another issue ( I think there is one). The csv does download
the JSON string, but as a string in a single column which is very difficult
to parse into anything human readable. I need to be able to extract
barcodes and part remarks out of this string for multiple parts, which can
take significant amount of time and result in error.

**Comment by Jegelewicz** [comment]
I think @acdoll was going to try using Google Refine on the JSON. Maybe he will find a way?

**Comment by acdoll** [comment]
OpenRefine seems to have the same issue as Excel  - because it is a .csv, it splits all of the commas in the JSON string into separate columns. So for a specimen with one part you get 11 columns of part detail info, but if the next specimen has four parts you get 44 columns of part detail.  This results in the column headers not lining up and each row has a different number of columns. 
I can download just the PartDetail column (with SQL), format and save as JSON, and that OpenRefine can open and parse appropriately. However, there's nothing in the JSON string that ties these part to the cat_num; you'd need a separate index table with all the part numbers for each catalog record.

**Comment by dustymc** [comment]
>splits all of the commas in the JSON string into separate columns.

Is that perhaps a setting or something? CSV isn't quite that simple - it should look like...

<img width="653" alt="Screen Shot 2020-05-18 at 8 31 46 AM" src="https://user-images.githubusercontent.com/5720791/82231533-2a6c6880-98e2-11ea-8f4b-d33fb341e585.png">

... with the "column" enclosed in double quotes, and any double quotes in the data escaped by doubling.

I again had no problem importing that to GSheets - https://docs.google.com/spreadsheets/d/1UFZDBupvhje8K8s2fegQ9REA8AZ67FXH-y6QnT3m9K8/edit?usp=sharing - and it successfully unescaped the quotes.

<img width="365" alt="Screen Shot 2020-05-18 at 8 37 32 AM" src="https://user-images.githubusercontent.com/5720791/82232038-e6c62e80-98e2-11ea-81bf-d37468d421b7.png">

I pulled a cell out of gsheets and it validates

<img width="442" alt="Screen Shot 2020-05-18 at 8 38 47 AM" src="https://user-images.githubusercontent.com/5720791/82232132-0cebce80-98e3-11ea-96d9-2a09a040fa16.png">

**Comment by campmlc** [comment]
I see that in the Gsheets, part detail is still concatenated. Aren't we
trying to find a way to unconcatenate this? I need to be able to isolate
part barcode and part remarks into individual columns that are lined up
between records.

**Comment by Jegelewicz** [comment]
So, OPenRefine would work if the ENTIRE line were JSON - it is the mixing of JSON into a csv that confounds us?

**Comment by dustymc** [comment]
>into individual columns 

That's probably another issue, but...

Each part has 10 "columns" in the JSON. A specimen can have any number of parts; we know there are 40-something in use.

Each part can have any number of attributes, we've got various projects underway to more or less guarantee a couple under most parts, and each of those is 6 "columns" in the JSON.

Once we get to preservation method in attributes, that 40-some part specimen would require a minimum of 400 parts-columns, and if each part has two attributes that'd be another thousand-ish columns. From the active issue about the bulkloader viewer I have to assume that you'd not be thrilled with side-scrolling through 1500 columns (plus whatever non-part stuff's in there).

It may be technically plausible to somehow treat parts as columnar, but I think it'd be the least-usable thing we could do by a very wide margin.

> if the ENTIRE line were JSON

I'm not sure it makes sense to talk about "lines" and JSON in the same sentence, but I could provide JSON as a download option (I think, in PG).

I believe the take-home is that the file is CSV; at this stage nothing should care that some of the CSV unrolls to JSON, it's just CSV, and anything that can't consume it should make you a little nervous for all CSV operations.

**Comment by acdoll** [comment]
I don't know what I'm doing wrong because eveytime I try, I get something like:
![image](https://user-images.githubusercontent.com/12507297/82237557-13824200-98f3-11ea-82bf-1bf558a2aa48.png)
https://docs.google.com/spreadsheets/d/1bR5RkMK2O2drSZwmk38aVUkxzi3Bxr7TI6ppGSCtt3k/edit#gid=666413246

**Comment by dustymc** [comment]
Oh! I can't access your spreadsheet, but I see the problem in the screenshot.

I downloaded another file, from production this time.

[ArctosData_21D6E87211.csv.zip](https://github.com/ArctosDB/arctos/files/4645448/ArctosData_21D6E87211.csv.zip)


New blank spreadsheet.

File/Import

Upload-->select

<img width="339" alt="Screen Shot 2020-05-18 at 9 40 33 AM" src="https://user-images.githubusercontent.com/5720791/82238136-a5864c80-98eb-11ea-9567-99394c9da311.png">

accept defaults

and...

<img width="529" alt="Screen Shot 2020-05-18 at 9 40 59 AM" src="https://user-images.githubusercontent.com/5720791/82238180-b767ef80-98eb-11ea-95ff-bd46ec521e99.png">

https://docs.google.com/spreadsheets/d/1gNtlHSMcQD2YtAHcDKDOkDNgcTqJK9zXAKeGIRZ-k-I/edit?usp=sharing

**Comment by campmlc** [comment]
My concern is whether I can actually get usable data out of the JSON
string. It is a useless field to me if I can't parse it into columns. This
has been my objection to JSON previously. Surely someone knows how to use
it, otherwise what's the point?
If this isn't possible, then we need an alternative, some way of
downloading the specific fields with the regular Arctos specimen results
data. So if I want all part barcodes, or part remarks, I can extract that
into unique columns. Will that be more feasible in PG?

**Comment by dustymc** [comment]
The technology stack has very little to do with the feasibility of munging vertical data into horizontal. https://github.com/ArctosDB/arctos/issues/2534#issuecomment-630284418 describes the problem; the source of the data is close to irrelevant.

Part detail used to be a concatenated string. I won't suggest we return to that, but it could be an additional "column" if unstructured data is somehow more desirable. New Issue, I'd need specifics.

**Comment by campmlc** [comment]
Created new issue for the JSON parsing. #2693 
Back to @cjconroy  is there a solution to the original issue?

**Comment by dustymc** [comment]
>solution to the original issue?

Yes - rebuild the parts search pane and background code post-migration.

**Comment by acdoll** [comment]
@dustymc - I think I found the issue:  the csv I get from the SQL does not have double quotes in the JSON string. 

[ArctosUserSql_BD96C48230.zip](https://github.com/ArctosDB/arctos/files/4651715/ArctosUserSql_BD96C48230.zip)

this was the query:
select cat_num,partdetail
from flat
where phylclass = 'Mammalia'

**Comment by dustymc** [comment]
Whoa - that's some OLD code, and a great example of why libraries are cool! It's updated (in test).

**Comment by cjconroy** [comment]
I wonder if this issue is still being worked on. I still have the issue that I am trying to use Arctos mapping to find mammal tissues. But, by clicking on the tissue box, I am still getting tissues that have been discarded. Imagine my emotional roller coaster as I see potential samples, then look closer at the record to see it was discarded many years ago. Any hope to improve this?  I know the other method is to download all the records, filter in Excel, remap in QGIS or something, but am still hoping I'll be able to do this in Arctos.

**Comment by campmlc** [comment]
I support making this a priority. Especially the ability to find parts with
a specified disposition. Right now the search doesn't link these two fields.

**Comment by dustymc** [comment]
>still being worked on

It's still "needs discussion" so not firmly on my radar. We need to better keep issues focused (although the wandering leads to useful places sometimes), and we need to better get things to the AWG for discussion.

Would the existing fields all searching one part do what you're trying to do, or is the form missing something? Clarify and I think I can make that much happen.

Whatever's left can be opened in new issues as necessary.

**Comment by cjconroy** [comment]
For MVZ, we have all our tissues as "tissue". If there was an interface to search for both a part= tissue and a disposition for THAT part = in collection, plus all the other criteria, that would be swell. There is a disposition button, but it is not tied to any single part.

**Comment by campmlc** [comment]
I agree.

**Comment by dustymc** [comment]
All part-stuff "ANDing" is done for next release.

I think everything else in here needs a new Issue if it still needs consideration.

* "Tissueness" is still an attribute of a catalog record, not a specific part. 
* How things like disposition affect "tissueness" (or search, or whatever ya'll do or don't want linked) has not changed.
* Part-bits are still split; some stuff's in the Curatorial pane.

**Comment by ccicero** [comment]
"Tissueness" is still an attribute of a catalog record, not a specific part.

I guess that I don't understand this, since the 'is tissue' flag is tied to individual part names in the code table. So why is it hard to make the 'require tissues' box search to return just those parts with disposition = 'in collection' ?

**Comment by jldunnum** [comment]
There are likely a large number of parts that were never updated to "in collection" and may be listed as "unknown" or "unchecked". Don't want to lose those do we?

______________________________________________________________

Jonathan L. Dunnum Ph.D.
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by dustymc** [comment]
>'is tissue' flag is tied to individual part names in the code table. 

I suppose we could add that to the search, but it doesn't do much checking the CT can't do - it's just part of the definition of "liver (frozen)" and not something that's added to *some* frozen liver-bits.

> 'require tissues' box search to return just those parts with disposition = 'in collection' ?

That's a separate issue. "Tissueness" is calculated for the cache; it can include/exclude anything, that just needs agreement and documentation (and then an expensive cache rebuild, so it's worth getting right before we do anything).

**Comment by Jegelewicz** [comment]
> never updated to "in collection" and may be listed as "unknown" or "unchecked". Don't want to lose those do we?

But also, this may end up disappointing people when the stuff is ACTUALLY missing...(I know there was a recent post about this, but I am failing to find it.)

**Comment by jldunnum** [comment]
People need to get used to disappointment...

______________________________________________________________

Jonathan L. Dunnum Ph.D.
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by campmlc** [comment]
I would like to be able to exclude parts from searches - e.g. subsamples or
parts already "on loan".

**Comment by dustymc** [comment]
>parts already "on loan".

Not sure I get that. I's out, it'll be back eventually, I'd like to have it when it's available - why prevent that?

**Comment by Jegelewicz** [comment]
tissues "on loan" probably are never coming back...

**Comment by campmlc** [comment]
No - for tissues, these subsamples and sometimes entire parts are
consumable. We don't get them back - they should not be in the public
search results.

**Comment by dustymc** [comment]
>tissues "on loan" probably are never coming back...

Then disposition should be "used up" or "missing."

**Comment by campmlc** [comment]
This might be the way to go for "missing" or "discarded" specimens as well
- just exclude these from public searches - or again, preferably, allow the
collections themselves to decide whether or not these should be allowed to
show in public searches.

**Comment by campmlc** [comment]
No, they are "on loan" with loan left open until a publication results. And
altering dispositions is the very last thing I will ever have time for.

**Comment by campmlc** [comment]
exclude transfer of custody
INCLUDE: in collection, being processed, unknown

**Comment by campmlc** [comment]
See decision in #3067
