### ISSUE TITLE
Fix MaNIS calculator link in edit locality page

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#2537]
on the Edit Locality page, the MaNIS calculator link broke. Can we get this fixed? Here's  the new link: http://georeferencing.org/georefcalculator/gci3/source/gci3.html

**Comment by dustymc** [comment]
done in PG

**Comment by tucotuco** [comment]
That's not the correct permanent URL for the georeferencing calculator. The new one (with very updated Calculator) is at http://georeferencing.org/georefcalculator/gc.html.
