### ISSUE TITLE
[CONTACT]

### ISSUE THREAD

**Issue by AlanBatten** [ArctosDB/arctos#2540]
On the search project/publication page (http://arctos.database.museum/SpecimenUsage.cfm), when I search for "Clegg" as a Participant I can't understand why his publication (The Holocene 15) shows up but his project (Herbarium ILL Betula Pollen Study) does not. I can get to the project by following a link from the publication, but why doesn't it come up in the original search?
Thank you. Alan

** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **

** Outages should be reported to the contacts listed at https://arctosdb.org/arctos-down/ **

** Arctos Documentation is http://handbook.arctosdb.org/ **

** Learn more about Arctos at https://arctosdb.org/ **

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **

**Comment by AlanBatten** [comment]
I have no idea what [CONTACT] means. I hope this is going to the right place.

**Comment by campmlc** [comment]
See #2541. Same problem with <100 characters in description.
