### ISSUE TITLE
Project and Agent Search Problems

### ISSUE THREAD

**Issue by AlanBatten** [ArctosDB/arctos#2541]
How come a project/publication search for "Fowell" and a separate one for "Mongolia" failed to turn up the Project titled "Mongolian Paleoclimate Project" with PI "Sarah J. Fowell"????? Similarly I searched for a loan with "Fowell" as either "Received by" or "Associated with Agency" and it failed to turn up loan 1997.001.Herb? Are a lot of these projects, loans, publications not linked right somehow? This is a bit frustrating. You will note that in all this thrashing around I created a project "Mongolian Paleoclimate" that is spurious and needs to be deleted (though I don't seem to have the perms to do it).

It's frustrating that this is the 2nd project that I've been unable to find by searching on one of the agents involved (the other one is Ben Clegg). I don't understand why those searches don't work.

Thanks!
Alan

** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **

** Outages should be reported to the contacts listed at https://arctosdb.org/arctos-down/ **

** Arctos Documentation is http://handbook.arctosdb.org/ **

** Learn more about Arctos at https://arctosdb.org/ **

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **

**Comment by campmlc** [comment]
Hi Alan,
This has been a recurring problem for projects that have fewer than 100
characters in the description, which is the default. I have argued strongly
against the 100 character requirement, the point of which is supposedly to
make people enter a more detailed project description, but in actuality it
just leads to inability to find the project and frustration. I agree with
the goal of having a sufficiently informative project description, but
perhaps there are other ways to enforce this, for example, through a pop-up
message requiring a longer description prior to save. Worth a GitHub issue
to the community for discussion on this topic.

In the meantime, you can find these hidden projects by setting the project
description minimum length to zero and searching on either Mongolia in the
title or Fowell in the participant field.
https://arctos.database.museum/project/10000343
 To delete a project, there is a red delete project button below the agents
next to Save Project. I deleted your duplicate.

As for the loans, I don't have access to UAM loans to check, but when I go
to Sarah J. Fowell's agent page and check on agent activity, she is shown
as both received by and outside contact for the loan in question. If you
have access to UAM, you should be able to follow the agent activity link to
those loans and perhaps see why they aren't showing up in a standard search
of received by agent?
Sarah J. Fowell (person)
created by unknown, 2013-12-16 21:49:31.0

Agent Names:

   - Sarah J. Fowell (preferred)
   - Fowell (last name)
   - J. (middle name)
   - Sarah Fowell (aka)
   - Sarah (first name)


   - outside contact for Loan UAM:Herb 1997.001.Herb
   <https://arctos.database.museum/Loan.cfm?action=editLoan&transaction_id=21063562>
   - received by for Loan UAM:Herb 1997.001.Herb
   <https://arctos.database.museum/Loan.cfm?action=editLoan&transaction_id=21063562>

**Comment by dustymc** [comment]
AWG suggestion

* make 100-character description hard requirement
* autopopulate created by, last edited by - "require" them in the forms to the extent possible
* eventually rebuild UI to sorta-maybe-hide admin agent roles

**Comment by dustymc** [comment]
merging into https://github.com/ArctosDB/arctos/issues/2570
