### ISSUE TITLE
Bulk Edit Container to Create Positions does not create positions

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2542]
The Bulk Edit Container csv has fields for the number of rows, columns, orientation, and container type for creating positions. However, there are no fields for the dimensions of the containers held in these positions, and so the bulkload process is not able to create positions? 
We need some means of doing this in bulk - can we add fields for container dimensions to the form?
I have 157 x 2 = 314 freezer racks that need these positions, and I really don't want to do each of these one at a time in Container Details/Positions.
In the meantime, prior to PG, @dustymc can you please create positions with the following specs:
Dimensions (W x H x D): 13.5 x 5.5 x 13.5 CM
Institution: MSB
To each of the freezer racks contained in the attached file?
[FreezerRackBulkContainerEdit _C4_C5 - Copy.zip](https://github.com/ArctosDB/arctos/files/4308072/FreezerRackBulkContainerEdit._C4_C5.-.Copy.zip)

**Comment by dustymc** [comment]
>the bulkload process is not able to create positions?

correct, that's a bulk-edit form, not bulk-create.

>dimensions of the containers held in these positions

To be clear:

* rows, columns, orientation, and container type are attributes of the parent container. Those data are used to create positions, but are not themselves positions.
* positions **are** containers; they would bear the dimensions and control what "fits" individually.

I suppose it could make some sense to add a 'oh yea and magic positions in' option, but that also has the potential of very quickly making VERY large messes. For example, the comment and the layout in the attached seem to conflict. Am I misunderstanding something, or is this a request to make almost 2000 (314*6) containers which would then need tracked down and deleted? That's not a trivial thing to do in the best of cases, if they've been used it can move into "nightmare" territory.

Clicking the "yep, this looks right, do it" button means that only 6 funky positions can be created at a time, and then only after a second review.

**Comment by campmlc** [comment]
So I have no option to enter dimensions and click yes 314 times? There goes
my day.

**Comment by dustymc** [comment]
I don't understand your comment.

I can SQL stuff in, but I need you to confirm that the stuff that looks conflicting to me is correct.

We can rebuild the loader to auto-create positions, but we somehow need to mitigate the scary parts.

**Comment by Jegelewicz** [comment]
Mariel,

I have done this before - let me look for my instructions in the dropbox.

**Comment by Jegelewicz** [comment]
Well, I guess I never wrote instructions. Are you trying to convert all the racks in a freezer from the old barcoded positions to the new mapped ones? What I did was use the virtual freezer (barcode = DGR19831) and moved all the boxes from the racks I needed to convert into it so that the racks that need to be changed are "empty". Then I deleted all of the "position" barcodes", then the racks, then re-created them with the positions and dimensions, then moved all the boxes back into them.

I did this a rack at a time - but you could certainly do a whole freezer.

**Comment by campmlc** [comment]
No, just adding positions to racks for our two new cryotanks. I need each
rack in the previously attached file to have 6 positions as one row, six
columns, horizontal, holding freezer boxes as containers, (as currently
bulkloaded) with position dimensions as follows:
Dimensions (W x H x D): 13.5 x 5.5 x 13.5 CM
Institution: MSB
And I was hoping this could be done this morning so I can start moving
boxes this afternoon.

**Comment by dustymc** [comment]
<img width="740" alt="Screen Shot 2020-03-09 at 11 36 03 AM" src="https://user-images.githubusercontent.com/5720791/76246156-66a48e00-61fa-11ea-894e-49f4a60d4721.png">

**Comment by campmlc** [comment]
Yes, the racks are vertical when installed, but horizontal when we lift
them out and add in boxes.

**Comment by dustymc** [comment]
OK - and you want container type "position" not "freezer rack position" - correct?

**Comment by campmlc** [comment]
Yes, please. The positions will be inside the freezer rack to hold freezer
boxes. Can we get these dimensions added as a a default choice when we
select freezer box as containers type held by position?

**Comment by dustymc** [comment]
Take a look at DGRC5H157 - if it's spiffy I can run the rest.

**Comment by campmlc** [comment]
Yes, that works. The following rack barcodes also already have these
positions:
DGRC4A1
DGRC4A2

**Comment by dustymc** [comment]
done

**Comment by campmlc** [comment]
Thanks!!!

**Comment by Jegelewicz** [comment]
DO we need a tool for future such things?

**Comment by campmlc** [comment]
We are trying to get funds for five more cryotanks, so in our case
potentially yes. I'm not sure why it would be a problem to enable position
creation with bulkload.

**Comment by dustymc** [comment]
>not sure why it would be a problem 

Just the potential for very large messes - I think that should be balanced against the need, which currently seems extremely minimal. Having DBA eyes on the data before something painful can happen seems pretty useful too.
