### ISSUE TITLE
I am authorized to enter data but I receive an error when I attempt to add data

### ISSUE THREAD

**Issue by gmward** [ArctosDB/arctos#2544]
** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **

** Outages should be reported to the contacts listed at https://arctosdb.org/arctos-down/ **

** Arctos Documentation is http://handbook.arctosdb.org/ **

** Learn more about Arctos at https://arctosdb.org/ **

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **

**Comment by campmlc** [comment]
You should have access to ALMNH Ento for data entry. I just added public
and cold fusion user roles, so please log out and re -log in again, and see
if it works.

**Comment by gmward** [comment]
Mariel:
Thanks, that solved the problem.

Milt Ward
