### ISSUE TITLE
New part for calcareous worm tubes

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#2545]
**Goal**
New part name: calcareous worm tube

**Context**
There are two part names that could be used for this structure, however neither are considered correct in current scientific usage.

Exoskeleton:
From [Written in stone: history of serpulid polychaetes through time](https://www.researchgate.net/publication/269704428_Written_in_stone_History_of_serpulid_polychaetes_through_time)

>While a tube is important for protection, it is not integrated with the animal body, and thus, does not constitute a genuine exoskeleton (Regenhardt, 1964; Weedon, 1994; Seilacher et al., 2008).

Trace Fossil:

A trace fossil is defined as:

> a morphologically recurrent structure resulting from the life activity of an individual organism (or homotypic organisms) modifying the substrate.

From [Names for trace fossils: a uniform approach](https://onlinelibrary.wiley.com/doi/abs/10.1080/00241160600787890)

Calcareous worm tubes do not represent a particular activity, but rather are secretions forming a structure around the animal. Although there is some gray area around what is a trace fossil and what is not, paleontologists do not consider calcareous worm tubes to be in that gray area. Worm tubes also differ considerably from burrows in that burrows are created by an animal creating a passageway through the substrate.

**Code Table**
CTSPECIMEN_PART_NAME

**Value**
calcareous worm tube

**Definition**
A tube formed by the calcareous secretions of polychaete worms.

**Collection type**
ES, Inv

**Comment by dustymc** [comment]
The idea seems sound, the vocabulary seems like something that'll get misused. 

"Calcareous worm tube"?

**Comment by Jegelewicz** [comment]
or just "calcareous tube"? would anything besides worms make such a thing?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> the vocabulary seems like something that'll get misused.

I'm fine with using something more nuanced to prevent misuse

> would anything besides worms make such a thing?

Well - there are some mollusks that do some weird things things ([worm snails](https://en.wikipedia.org/wiki/Vermetidae) and [tusk shells](https://en.wikipedia.org/wiki/Tusk_shell)), so maybe calcareous worm tube is better.

**Comment by Jegelewicz** [comment]
> Well - there are some mollusks that do some weird things things (worm snails and tusk shells), so maybe calcareous worm tube is better.

Would those things made by the mollusks also be called "calcareous tubes"? If so, I suggest we leave out the "worm" so that the term would be more broadly applicable.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> Would those things made by the mollusks also be called "calcareous tubes"?

No, since they are mollusks, they should be called shells.

**Comment by Jegelewicz** [comment]
Changed the request above to "calcareous worm tube"

**Comment by Jegelewicz** [comment]
@aklompma thoughts?

**Comment by aklompma** [comment]
These tubes are part of the animal and not a trace of some sort. 

There are multiple marine animals that make a calcareous tube, including annelids (worms), rare bivalves (_Kuphus_, a mollusk), and scaphopods (a mollusk group). Particularly the tubes of annelids and scaphopods can be hard to tell apart.

**Comment by Jegelewicz** [comment]
> These tubes are part of the animal and not a trace of some sort.

Hmmmm - dissent in the paleo ranks? If they are part of the animal, then are they an exoskeleton? A shell? what part name would you recommend?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
To be clear - I agree that they are not traces, I was just preempting some counterpoints that had already been voiced on our data migration repository.

**Comment by aklompma** [comment]
The tubes of worms could be called an exoskeleton informally I guess, but shell may work better imo.

**Comment by sharpphyl** [comment]
We used "shell" for our polychaete worm tubes but I'm fine with "calcareous worm tube" if that's the consensus opinion.

**Comment by campmlc** [comment]
I support calcareous worm tube. This is not an exoskeleton, which has very
specific connotations in other phyla.

**Comment by Jegelewicz** [comment]
@ArctosDB/arctos-code-table-administrators any opposition to the addition of this part name?

Value
calcareous worm tube

Definition
A tube formed by the calcareous secretions of polychaete worms.

Collection type
ES, Inv

**Comment by anna-chinn** [comment]
Fine by me.

**Comment by campmlc** [comment]
OK by me too.

**Comment by dustymc** [comment]
Is "polychaete" intentional? I'd take https://github.com/ArctosDB/arctos/issues/2545#issuecomment-597726775 (particularly the 'hard to tell apart' bits) to mean that this could require more information than might exist.

I lean towards something like "A tube formed by the calcareous secretions of certain invertebrates," but the more specific definition is fine as well if that's what's desired.

**Comment by Jegelewicz** [comment]
@ArctosDB/arctos-code-table-administrators any opposition to the addition of this part name?

Value
calcareous worm tube

Definition
A tube formed by the calcareous secretions of certain invertebrates.

Collection type
ES, Inv

**Comment by AJLinn** [comment]
ok by me

**Comment by campmlc** [comment]
ok

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
fine with me.

**Comment by Jegelewicz** [comment]
Part name added.

**Comment by Jegelewicz** [comment]
Note - lost in spring Arctos crash, re-added today
