### ISSUE TITLE
Add trace types to the part table and get rid of part trace fossil if possible

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2546]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Goal**
A simplified version of a separate classification of trace fossils based on behavior. It is sort of in a gray area between parts and taxonomy. 

**Context**
It is sort of in a gray area between parts and taxonomy. But really it is just a conceptual framework used to think about trace fossils and not all of these categories are commonly used to describe what I would call a part.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=CTSPECIMEN_PART_NAME

**Value**
trace (remove "trace fossil" and convert those parts to the new name with the "fossil" attribute)

**Definition**
    a morphologically recurrent structure resulting from the life activity of an individual organism (or homotypic organisms) modifying the substrate.

From Names for trace fossils: a uniform approach

**Collection type**
ES (but probably would apply to all animal groups...)

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=CTSPECPART_ATTRIBUTE_TYPE

**Value**
trace activity

**Definition**
descriptive term to describe the activity the trace represents

**Attribute data type**
categorical

**Attribute value**
For categorical attributes, code table controlling value - add part attributes
A new code table = CTTRACE_ACTIVITY

trail: horizontal (along the bedding plane) mark left by the movement of an animal in sediment. Excludes footprints (tracks) made by vertebrate animals.

burrow: hole or tunnel excavated into sediment by an animal.

resting: mark left by an animal coming to rest on sediment.

track: mark left by the manus or pes of a vertebrate animal.

coprolite: the fossilized excrement of an animal.

predation: bite or other mark left on the skeleton of one organism by the feeding behavior of another organism.

There may be others that come up as we're entering data such as gastrolith, regurgitite, etc.,

**Part tissue flag**
For new parts, is the part a tissue? No

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
I like it in general; it sets up the possibility of finding things like tracks, no matter if they're fossilized, reproductions, etc. 

Coprolite won't be found with http://arctos.database.museum/info/ctDocumentation.cfm?table=CTSPECIMEN_PART_NAME&field=feces, which is far from ideal.

predation should be closer to 'infested with parasites' (interaction) than 'stepped there' (evidence of existence).

I like "modifying the substrate" much more than "mark ... in sediment" - the latter doesn't work very well for the (very sciencey) tracks in the sidewalk in front of my house.

**Comment by Jegelewicz** [comment]
> Coprolite won't be found with http://arctos.database.museum/info/ctDocumentation.cfm?table=CTSPECIMEN_PART_NAME&field=feces, which is far from ideal.

The definition of trace really doesn't support coprolite does it? Is fossilized feces really "modifying the substrate"?

I suggest we leave coprolites out of this for now and leave the discussion of feces, regurgitations, etc. out of traces unless we modify the definition of trace.

> predation should be closer to 'infested with parasites' (interaction) than 'stepped there' (evidence of existence).

Again, predation is not a "modification of substrate" is it? Unless substrate can be defined as another living being. (a bite mark is trace evidence of whatever animal did the biting, just as worm holes are trace evidence of the worms who ate the wood). If we are OK with predation inside of this definition of trace, then maybe we also need a term to indicate parasitic infestation. If we are not OK with predation in this definition of trace, we should consider what "part" this type of thing should be represented by.

**Comment by dustymc** [comment]
>need a term to indicate parasitic infestation

There are like 10 of them scattered around. They desperately need consolidated and I'm incredibly hesitant to support spawning more options, but maybe there is a subtle difference between "this individual..." and "this part is evidence that this individual...."

I'd like to somehow unify the ideas of predator/browser/micropredator/parasite/phoretic/etc. - not necessarily a merger, but some way to say (or just search) "there's something beyond this individual here."

**Comment by aklompma** [comment]
Predation attempts, whether successful or not, surely do leave traces behind on many substrates including shells. Many trace fossil names have been erected (search for _Oichnus_ for example). 

Parasitic traces have been named as well (and can sometimes be hard to distinguish from predation traces). One clear example of parasitic trace is _Kanthyloma crusta_.

Coprolites are also trace fossils by the way, as are regurgitaliths.

**Comment by dustymc** [comment]
Sounds like we need a better definition for "trace." 

Does "indirect evidence of the behavior and activities of life" (some random google result, slightly modified) cover all the bases?

So a coprolite would be 
* part=feces
    * preservation=fossil
    * whatever this thing is=trace

and a regurgitalith would be the same thing with part 'stomach contents.'

BUT those sorts of things are so common I'm tempted to suggest we need yet another part attribute "common name" or something of the sort (might even be able to magic it out of the data).

Life was so much simpler when this was all a free-text cell in a spreadsheet!

**Comment by Jegelewicz** [comment]
> I'd like to somehow unify the ideas of predator/browser/micropredator/parasite/phoretic/etc. - not necessarily a merger, but some way to say (or just search) "there's something beyond this individual here."

Agree - that would be good. Associated species seems appropriate, but it's placement and lack of depth at this point make it hard to work with.

**Comment by Jegelewicz** [comment]
> Does "indirect evidence of the behavior and activities of life" (some random google result, slightly modified) cover all the bases?

I like that

> So a coprolite would be 
> * part=feces
>     * preservation=fossil
>     * whatever this thing is=trace


I was thinking more like this:

* part=feces
    * preservation=fossil
    * trace type = coprolite

then a track would be

* part=trace
   * preservation=fossil
   * preservation=compression (found in silt or clay, like the mold or impression fossils, but they leave behind just a two-dimensional imprint) see https://github.com/ArctosDB/arctos/issues/1976#issuecomment-584738602
   * trace type=track

See also https://github.com/ArctosDB/arctos/issues/2394#issuecomment-561868012

**Comment by Jegelewicz** [comment]
> Many trace fossil names have been erected (search for Oichnus for example).
> 
> Parasitic traces have been named as well (and can sometimes be hard to distinguish from predation traces). One clear example of parasitic trace is Kanthyloma crusta.

but those names would be the identification of the specimen, not the part description, correct?

**Comment by dustymc** [comment]
>part=feces,  preservation=fossil,  trace type = coprolite

That might be more clear - it still allows predictable results from a 'find the poo' query so I'm fine with it.

>those names would be the identification of the specimen (taxonomy), not the part description, correct?

This is another place where "what we call it" and "what it is" are confounded in weird ways (much like everything in cultural collections). Whatever we do, it should support finding trace fossils with one query regardless of whether some taxonomist was involved or not. That's probably going to be a little redundant at times and needs explicit documentation. ("Of course it has {part-thing} - that's what the name means!")

**Comment by dustymc** [comment]
"Associated species" includes everything from "this mushroom was growing on Quercus alba" to "there's a corn field a couple miles down the road." It is what it is, and I don't think there's any making it something else. (Extracting some data into something else might be possible.)

Specific data are easy - "this was {whatevered} by THAT, here's a link."
Super-vague data fit in associated species.

I could be convinced that we need a slightly-less-vague concept in between, or I could be convinced that anything that doesn't link to another specimen is by lack of that link "super-vague" and should be shoved into associated species.

**Comment by aklompma** [comment]
> > Many trace fossil names have been erected (search for Oichnus for example).
> > Parasitic traces have been named as well (and can sometimes be hard to distinguish from predation traces). One clear example of parasitic trace is Kanthyloma crusta.
> 
> but those names would be the identification of the specimen (taxonomy), not the part description, correct?

Many of these traces are found within another fossil. So you essentially would have two sets of names for a single specimen, one for the fossil itself and one (or multiple) trace fossil names found on/within the specimen.

**Comment by dustymc** [comment]
>two sets of names for a single specimen

That's possible, but cataloging the items of scientific interest separately and adding relationships is much more powerful.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> A simplified version of a separate classification of trace fossils based on behavior

A classification for traces based on behavior is actually different from what we are talking about, there is a defined classification for that which I don't think we need to tackle yet. What we are talking about is more just general categories or types of trace fossils. 

> Coprolite won't be found with http://arctos.database.museum/info/ctDocumentation.cfm?table=CTSPECIMEN_PART_NAME&field=feces, which is far from ideal.

It would be nice if there was a way to cross-reference these or something. Having coprolites come up under feces would be useful.

> The definition of trace really doesn't support coprolite does it? Is fossilized feces really "modifying the substrate"?

> Again, predation is not a "modification of substrate" is it?

Actually, both coprolite and predation come under this definition. Here is a definition for substrate:

> the surface or material on or from which an organism lives, grows, or obtains its nourishment

For coprolites, the substrate is whatever the animal is eating, which gets modified by mastication and digestion and then deposited somewhere else. For predation, the substrate is the prey.

> Sounds like we need a better definition for "trace."

I disagree. The definition that Teresa gives is from a peer-reviewed scientific article that is the summation of decades of paleontologists working out the definition of a trace.

**Comment by campmlc** [comment]
If we can cite a peer-reviewed pub for a definition that sounds ideal.

**Comment by dustymc** [comment]
Different definition of trace, different definition of substrate, whatever....

>decades of paleontologists 

Arctos is bigger than paleontology. Whatever we do should work for tracks, regardless if they're dinosaur in sediment or cat in concrete. If avoiding confusion means avoiding "paleo terminology" then so be it.

>cross-reference

A different angle on the above (and as mentioned elsewhere) I think there are two immediate possibilities:

1. Agree on and define terminology that works for dinosaurs and cats.
2. Something that looks a lot like magic from here.

(Longer-term some sort of part equivalency functionality would be awesome, but I think that's a major project - unless someone's sitting on a clever idea....)

Calling the poo poo is easy. Calling special cases of poo something else isn't. Relegating "coprolite" (common and important terminology) to some secondary structure or something may not be ideal, but it's **functional** and I think that's vastly more important (and better exposing "coprolite" might be a simple UI issue, depending on where it ends up).

**Comment by Jegelewicz** [comment]
> better exposing "coprolite"

preservation = coprolite

?

**Comment by dustymc** [comment]
>preservation = coprolite

Not if "find the fossils" is important.

**Comment by Jegelewicz** [comment]
Can also have

preservation=fossil

!

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Is there a reason that definition does not also work for for modern traces?

**Comment by dustymc** [comment]
I don't even know anymore - there was a "sediment" somewhere... 

I think we're agreed "trace" covers things like tracks, modern or otherwise, and that's what's really important. Please just be careful that the attributes don't get paleo-centric definitions and I'm good.

That leaves things with fancy names, like 'coprolite,' where I assume the name is useful but also makes discovery difficult. It would be nice to find some universal solution, but whatever - they have fancy names, it's easy to find them later and make things better.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
What about making feces a trace and including feces as a trace type attribute (definition can include something like "fossil feces are called coprolites". Of course, this would require support from any other collections already using feces.

**Comment by dustymc** [comment]
At first glance I think that's overly disconnected from the expected usage - people want to find feces (and not tracks etc) so they can eg look for parasites, and moving that one more "layer" away from the specimen seems like an unnecessary complication.

It's also a simplification in that it results in one less part, and all the information would still be there. I don't think there's any solid technical argument against this, so I don't have much of an opinion.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> people want to find feces (and not tracks etc) so they can eg look for parasites, and moving that one more "layer" away from the specimen seems like an unnecessary complication.

At the same time, something similar could be said about paleo stuff. Researchers will be looking for burrows or coprolites or tracks, etc. and not just generally for trace fossils.

**Comment by Jegelewicz** [comment]
> At the same time, something similar could be said about paleo stuff. Researchers will be looking for burrows or coprolites or tracks, etc. and not just generally for trace fossils.

OK, so now I am having a trace fossil existential crisis.

Is it better to go with https://github.com/ArctosDB/arctos/issues/2546#issue-578911593
 or instead:

Table
https://arctos.database.museum/info/ctDocumentation.cfm?table=CTSPECIMEN_PART_NAME

Value
Remove "trace fossil" and convert those parts to the **appropriate** part name with the appropriate "fossil" preservation attribute (fossil; fossil cast; fossil imprint; fossil mold, external; fossil mold, internal)

**New part names will need to be added**

trail: horizontal (along the bedding plane) mark left by the movement of an animal in sediment. Excludes footprints (tracks) made by vertebrate animals.

burrow: hole or tunnel excavated into sediment by an animal.

track: mark left by the manus or pes of a vertebrate animal.

regurgitite: need a definition

I bring this up because we also have a lot of shell impressions, leaf impressions, etc. which I am inclined to call "shell", "scute" and "leaf" with "impression" in an attribute since those parts already exist in the part name code table rather than calling them "trace fossil" with "leaf" in an attribute somewhere (two places to look for leaves...).

The two that give me grief under this method are:

resting: mark left by an animal coming to rest on sediment.

predation: bite or other mark left on the skeleton of one organism by the feeding behavior of another organism.

and others we haven't mentioned:

swim trace
tail drag
feeding trace
grazing trail
invertebrate trace
hopping traces
tool marks
microbial mat signature (and probably others that I am just not seeing right now).

These don't seem to be appropriate "parts" for them, I think maybe "trace" makes more sense, with a code table for trace types.

Now that I have made a mess of this - thoughts?

**Comment by dustymc** [comment]
>existential crisis

We need T-shirts or something.

>...sediment.

I hate it - whatever we do should work for slugs on a freshly-poured sidewalk in addition to anything paleo-ish. The behavioral people should love us, not get lost in some artificial paleo-vs-not pigeonhole. (I think broad definitions of "substrate" may fix all that.)

I still lean towards "trace" as the part and all the details in a part attribute. Parts are "things to which one might stick a barcode" and "tool marks" don't seem like that. The next researcher saying "those definitely are not tool marks" should be an additional opinion, not something that requires a change of vocabulary or a curatorial coin-toss. I'm not sure that's a reason to throw all of this into "trace," but it is evidence that this isn't entirely an arbitrary decision.

The split between eg swim trace and tail drag are similar. As parts, we need to pick one and make sure there's no overlap to avoid denormalization (and therefore nobody being able to find anything). As attributes, we can have any number of opinions on the same part, either because various researchers see various evidence or because everybody agrees that those things are both present.

BUT, https://github.com/ArctosDB/arctos/issues/2546#issuecomment-601898334 - what's important to some degree depends on who's asking what questions. The logical conclusion to my "trace" stance might be to catalog everything in paleo collections as "rock" with a bunch of attributes, which is obviously ridiculous (or is it?!). There's that existential crisis again....

I'm not sure "something was hopping here" (behavioral-ish) and "a leaf was here" (indirect evidence of a DWC:Occurrence) are the same THING, but I'm not sure where that split is either. Maybe there are even more THINGS embedded in this - coprolites are parts, shell impressions are evidence of existence, hopping traces are evidence of existence and behavior, ????

**Comment by Jegelewicz** [comment]
Dang it! All you did was make my existential crisis worse! I'm going to pour myself a drink.

When do we have Arctos Happy Hour Zoom?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> The`` next researcher saying "those definitely are not tool marks" should be an additional opinion, not something that requires a change of vocabulary or a curatorial coin-toss.

Except that 1) tool marks aren't traces because they don't result from the life-activity of an organism (same for leaf and shell impressions, and 2) In paleo, this scenario can happen with pretty much any part name. Researcher A identifies a poorly preserved limb bone as a femur, then another researcher B comes along and identifies it as a tibia. Moving all paleo part data to attributes seems like it would be terribly confusing for anyone trying to find stuff. At the same time I agree that for paleo parts we need a way to show if the part ID has changed.

**Comment by dustymc** [comment]
>Arctos Happy Hour Zoom

Oh my!

>they don't result from the life-activity of an organism

What exactly is wielding the tool then?! I'm having a hard time seeing how 'an orangutan was waling on this with a rock, probably yesterday' and 'some long-dead critter was gnawing on this' are fundamentally different THINGS.

It might be useful to have a list of things that need solved immediately to help scope this. Something that could be quickly extracted from your data?

>In paleo...

It ain't just paleo, although the reasons may be slightly different.

>terribly confusing for anyone trying to find stuff

That's "just" a UI problem; Arctos could provide a "find part-stuff" search option if this gets complex enough to need one. (And it probably is.) I don't think I'm actually (yet?!) suggesting we attribute-ify everything, I just want to avoid arbitrarily tossing some stuff in one bucket and some other stuff in another, at least without carefully documenting doing so.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
"Tool marks' is a term used in geology for when things like sticks are being washed along by water and the end of the stick makes a scratch-like mark in the sediment. Sorry for the confusion, I should have clarified that.

**Comment by dustymc** [comment]
Well that's definitely not confusing terminology....

So they're useful for comparison I'm guessing - THIS is some critter doing critter-things, THAT is a stick and some gravity? And that's all subject to decades of study and interpretation and argument?

**Comment by Jegelewicz** [comment]
OK this makes me feel better

> tool marks aren't traces because they don't result from the life-activity of an organism (same for leaf and shell impression

and I think really solidifies the definition of "trace fossil" in my brain and maybe suggest a little tweak to the definition in the code table.

Currently we have

> trace fossil = The fossilized remains of a track, trail, footprint, burrow, etc, of an organism

How about we update to

trace fossil = The fossilized remains that result from the life-activity of an organism such as a track, trail, footprint, burrow, etc.

THEN we could use part attributes to describe these traces:

> For categorical attributes, code table controlling value - add part attributes
> A new code table = CTTRACE_ACTIVITY
> 
> trail: horizontal (along the bedding plane) mark left by the movement of an animal in sediment. Excludes footprints (tracks) made by vertebrate animals.
> 
> burrow: hole or tunnel excavated into sediment by an animal.
> 
> resting: mark left by an animal coming to rest on sediment.
> 
> track: mark left by the manus or pes of a vertebrate animal.
> 
> predation: bite or other mark left on the skeleton of one organism by the feeding behavior of another organism.

For now, we leave coprolite as a part name because I don't want to fight that battle. And after the PG move, we change ALL "trace fossil" to "trace" and add the preservation=fossil part attribute to those parts.

My anxiety is mostly relieved, except for "tracks" that are described as manus and/or pes. These parts actually exist in the part name table. Is it OK to call these things "trace fossil" and put the "manus/pes" in part remark or do we need a way to find all of the "manus tracks"? should we create the "track" attributes as follows:

track: mark left by the manus or pes of a vertebrate animal.
track, manus: mark left by the manus of a vertebrate animal.
track, pes: mark left by the pes of a vertebrate animal.
?

Thanks for indulging me....

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> trace fossil = trace fossil = The fossilized remains that result from the life-activity of an organism such as a track, trail, footprint, burrow, etc.

I would add "trace fossil = The fossilized remains that result from the life-activity of an organism such as a track, trail, footprint, burrow, etc.**in substrate**"

> For now, we leave coprolite as a part name because I don't want to fight that battle.

I am ok with this for now, but it is a battle I want to take on later.

**Comment by aklompma** [comment]
Here's yet another slight expansion because there so very many traces found within shells:
"trace fossil = The fossilized remains that result from the life-activity of an organism such as a track, trail, footprint, burrow, **bore hole, drill hole** etc. in substrate"  

A coprolite may also be added at some point because it is a trace fossil.

**Comment by Jegelewicz** [comment]
> >manus and/or pes
> 
> It would be nice to have an attribute for this. If it will add a lot of extra time to your preparing the bulkloading files, I am also ok with just leaving this in remarks for now and creating those attributes later.

My problem with that attribute is that then there will be two places to look for manus and pes....

**Comment by dustymc** [comment]
>problem with that attribute

I think the attribute is a workable solution, and it'll standardize the vocabulary so it's easy to make adjustments if we come up with something better later. There's still some subtle distinction between "is thing" and "is evidence of/was made by thing" (same with eg shell imprints, maybe even casts/molds) that I don't think I've fully internalized. I say proceed with something that's reversible and revisit later.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
From a book _Life Traces of the Georgia Coast_ by Anthony Martin who is a leading neoichnologist.

![image](https://user-images.githubusercontent.com/47402809/82935740-c6354e80-9f4a-11ea-8190-22426b8c0d67.png)

**Comment by Jegelewicz** [comment]
See also https://github.com/ArctosDB/arctos/issues/2394#issuecomment-561868012

**Comment by Jegelewicz** [comment]
Issue summary

1. New part_name = trace with definition = Any mark left on a medium of some sort (sand, mud, shells, bone, flesh) caused by the behavior of a living organism. Examples include tracks, trails, burrows, nests, feces, borings, and tooth marks. _Life Traces of the Georgia Coast_ by Anthony Martin. Trace parts should include more descriptive detail in a "trace type" part attribute.

2. New specpart_attribute_type = trace type with definition = Describes the type of mark left on a medium of some sort (sand, mud, shells, bone, flesh) by the behavior of a living organism. This is a categorical attribute controlled by code table cttrace_type.

3. cttrace_type new table with values as follows:

trace type | definition 
 -- | -- 
track | a single imprint made by the appendages of an animal on the surface of the substrate
trail | a continuous trace made on the surface of a substrate
burrow | a continuous trace made within a substrate
boring | an excavation produced by an organism in a hardground
coprolite | Fossilized excreta. A type of ichnofossil or a trace fossil.
feces | Intestinal excrement, droppings, scat.
gastrolith | Also called a stomach stone or gizzard stone, is a rock held inside a gastrointestinal tract. Gastroliths in some species are retained in the muscular gizzard and used to grind food in animals lacking suitable grinding teeth. In other species the rocks are ingested and pass through the digestive system and are frequently replaced.
regurgitalith | the fossilized remains of stomach contents that have been regurgitated by an animal
nest | a structure created or inhabited by an organism for shelter and/or to raise young
web | a thin, silken material spun by spiders and the larvae of some insects
cocoon | the silky envelope spun by the larvae of many insects, serving as a covering while they are in the pupal stage
case | a protective covering made by caddisfly larvae from organic or inorganic detritus
predation mark | a mark on an organism created by the predation of another organism. Includes bite and gnaw marks.

4. Remove the following parts from ctspecimen_part_name, for any records using these part names, replace with "trace" and the appropriate trace_type attribute.

coprolite
feces 
feces (70% ethanol)
feces (95% ethanol)
feces (dry)
feces (ethanol)
feces (formalin)
feces (frozen)
feces (K2Cr2O7)
feces (RNAlater)
 - All feces parts will need appropriate preservation attributes added
gastrolith
nest
pinned nest (need preservation attribute "pinned")

5. Replace the part name "trace fossil" with the part name "trace" and add the part attribute "preservation" with the value "fossil" to those parts that were previously "trace fossil". Use part remarks to generate appropriate trace_type attributes.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I agree with this. Excellent summary @Jegelewicz !

**Comment by Jegelewicz** [comment]
Well, should this also be a part of #3708 ?

**Comment by Jegelewicz** [comment]
Moving this to the top of the Code Table Committee work.

**Comment by Jegelewicz** [comment]
Discussed today in @ArctosDB/arctos-code-table-administrators meeting. This hangs up between normalization and what humans look for. We need some use case testing. Maybe we can have a better discussion next month.

**Comment by Jegelewicz** [comment]
Code Tables says let's do this for all but coprolite - that is a larger issue and may get fixed by #4773

**Comment by ccicero** [comment]
YES! Do not get rid of parts like 'nest' or 'feces' !!!

**Comment by Jegelewicz** [comment]
Reading this it seems like we have decided to do nothing and this should be closed? @Nicole-Ridgwell-NMMNHS @aklompma

**Comment by Jegelewicz** [comment]
There are some "trace fossil" parts that contain no details about the kind of trace they are. See attached workbook for all of the trace fossil parts found with a search (not logged in as me...). I am not sure that we can ever

> get rid of part trace fossil

so I guess this will just remain open until new code table terms are requested and things start to get changed over. I am changing the title of this issue to reflect the decision.

[trace_fossil_parts_2023_02_20.xlsx](https://github.com/ArctosDB/arctos/files/10786978/trace_fossil_parts_2023_02_20.xlsx)

**Comment by dustymc** [comment]
@Jegelewicz should this be closed based on [2023-09-21 AWG Code Table Committee](https://docs.google.com/document/d/1eZ_S8VTp-m5Wrbb6cAK96ODPZpt2-Hvnvt6yfU9qVwg/edit#heading=h.rortzr5prqrj) discussion?

**Comment by Jegelewicz** [comment]
yes
