### ISSUE TITLE
Change Events in a locality to verification status = "accepted"

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2547]
I need to change all specimen events associated with this locality to "accepted"

https://arctos.database.museum/SpecimenResults.cfm?locality_id=11025908

There are more than 1000 events, so I cannot use the tool in specimen results.

@dustymc can you do this one for me? I'd like to get these changed before I add the public events.

**Comment by dustymc** [comment]
I don't have access to whatever that is so I'm working blind, but if this looks like them I can do that.

```
select verificationstatus,guid_prefix, count(*) from collection,cataloged_item,specimen_event,collecting_event where collection.collection_id=cataloged_item.collection_id and cataloged_item.collection_object_id=specimen_event.collection_object_id and specimen_event.collecting_event_id=collecting_event.collecting_event_id and collecting_event.locality_id=11025908 group by verificationstatus,guid_prefix
  2  ;

VERIFICATIONSTATUS
------------------------------------------------------------------------------------------------------------------------
GUID_PREFIX						       COUNT(*)
------------------------------------------------------------ ----------
unverified
NMMNH:Paleo							   3210


1 row selected.

```

**Comment by Jegelewicz** [comment]
Yep, that's them.

**Comment by dustymc** [comment]
Done, and I realized that you can do this yourself somewhere along the way.

http://arctos.database.museum/editLocality.cfm?locality_id=11025908

<img width="798" alt="Screen Shot 2020-03-11 at 1 02 02 PM" src="https://user-images.githubusercontent.com/5720791/76458912-87a2e580-6398-11ea-9bf4-a170e3eb9968.png">
