### ISSUE TITLE
Agent relationship reciprocal for "student of"

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2549]
There does not appear to be a relationship for "advisor of" or "mentor of" that we can use to clarify the reciprocal of "student of" in agent relationships. 
A graduate advisor's agent page shows "student of" from " xxxstudent name"

**Comment by dustymc** [comment]
If this is a request for a new code table value, it will need the information requested in https://github.com/ArctosDB/arctos/issues/new?assignees=&labels=Function-CodeTables&template=authority-request.md&title=
