### ISSUE TITLE
Search on specimens with media tags

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2551]
Request to be able to search on particular specimens that are tagged in media from Specimen Search. This will allow us to find what specimens have a tag, what does not, and be able to locate tagged specimens that may be linked to many many pages of a multipage document, which can be difficult to search a page at a time.

**Priority**
This would be very useful,

**Comment by dustymc** [comment]
TAGS create media relationships, which are already searchable. Is there some other functional purpose to this?

**Comment by campmlc** [comment]
To make it possible to find specimens with media tags directly from the
main search page. I wouldn't inflict the media search page on my worst
enemy, much less a student or public user.

**Comment by campmlc** [comment]
Currently there is no way to distinguish a search for specimens with tagged media vs other media (e.g. an image of a specimen) via the main search page. Also, it is not possible to use media keywords, e.g. Rausch ledger, as a public user (assuming you know what those keywords are . . . ).  I am requesting the addition of a search for specific media relationship, e.g. tagged media, so that operators and public users can find which records are tagged (and which remain to be tagged).
