### ISSUE TITLE
Agent Bad Duplicate Relationship Error

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2555]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I am trying to flag W. L. Goodpaster as a bad duplicate of Woodrow Goodpaster.
When I save, I get an error message.

I believe that W. Goodpaster is also a bad duplicate. Same problem.

**To Reproduce**
1. Go to Agent Search
2. Search on Goodpaster
3. Select W. L. Goodpaster
4. Go to Edit Agent
5. enter "bad duplicate of" in relationships, and "Woodrow Goodpaster" in agent name.
6. See error message: "An error occurred and your changes were not saved . . ."

**Expected behavior**
For duplicate relationship to be created.

High priority.
Needed for collection migration.

**Comment by dustymc** [comment]
The actual error and links are very useful.

Not 100% sure I'm seeing what you're seeing, but in the logs...

>First name cannot be all upper or lower case.

and

https://arctos.database.museum/agents.cfm?agent_id=1017511

has

<img width="189" alt="Screen Shot 2020-03-19 at 2 06 48 PM" src="https://user-images.githubusercontent.com/5720791/77115075-e694da00-69ea-11ea-9177-4ab85c6fe72c.png">

I know it's a little weird to have to fix things before you can delete them, but there's no other realistic way of maintaining sufficient data quality.

If that's the right thing, fix the name, save, then you can create the relationship.

**Comment by campmlc** [comment]
But that means we shouldn't enter weird spelling and spacing variants, or we can't merge records? Maybe we could get a popup that indicates what needs to be done, instead of just "error"?
![Screenshot 2020-03-19 15 24 50](https://user-images.githubusercontent.com/14808196/77116455-d9c9b380-69f5-11ea-8516-b0da565de864.png)

**Comment by campmlc** [comment]
Changing the spacing worked. However, we should update the  documentation below to say that name variants cannot include spacing variants, or some such thing.  But why not? 
We need some way to direct people to the source of a problem without requiring they read a 5 page document of mostly irrelavant info to find the one small piece of relevant info in the fine print.  That goes against human nature, and no amount of nagging and red boxes will fix that. Ideas?

**Comment by dustymc** [comment]
This is a complex thing and we've developed complex rules to avoid the thousands of duplicates that existed before the rules came about; I don't think there's much avoiding the complexity if we want defensible agent data.

The short version and immediate solution is in the error.

You shouldn't (now can't) enter weird variations in certain name fields. You can enter whatever you want in things like AKA.

"Why not?" pretty much always comes around to preventing duplicates.

You can't do ANYTHING - including merge - to records which don't meet the data quality standards. The unrealistic alternative I alluded to above would be to preemptively fix anything that's not up to par.

**Comment by campmlc** [comment]
I guess I am confused. The weird name variants with odd spacing that I had
to fix before I could merge the records were in the AKA fields. It isn't a
problem to fix these before merging. But I do think we need some additional
clarification in the documentation on the form and in the error message to
make this obvious to people. I would not have known without filing this
issue.

**Comment by dustymc** [comment]
See my screenshot above - it was in first name when I got there.

>clarification in the documentation on the form and in the error message 

From your screenshot:

<img width="300" alt="Screen Shot 2020-03-19 at 2 46 53 PM" src="https://user-images.githubusercontent.com/5720791/77118035-83a64180-69f0-11ea-9b2b-82a3c0114010.png">

**Comment by campmlc** [comment]
Well, now I am confused because I don't remember editing the preferred
name. Just please realize that my confusion is representative of what the
vast majority of users experience when dealing with these types of Arctos
errors and problems, and I do not believe we serve our user community well
by refusing to create user-friendly interfaces. The error text is not
easily human-readable -I did not even try to read past the 'error - your
changes were not saved, try again" jist of the message, and I do not think
I am at all unusual in this. Such message are not the solution.  Perhaps we
need to hire a UI consultant.

**Comment by dustymc** [comment]
The problem wasn't preferred name, it was first name.

The error is all important and more or less in order of things that have caused problems. I'd be thrilled to make it shorter, but I'm not sure how to do so. 

We've had a couple usability experts over the years, but we've never figured out how to pay for one. That would be most welcome, although it should be considered in light of the API plans.

Not knowing how to better convey information isn't a refusal to create user-friendly interfaces!

**Comment by campmlc** [comment]
How different will this error message look in PG? Perhaps we can eliminate the "Error Executing Database Query: [Macromedia][Oracle JCBC driver][Oracle] ORA-200001  UAM_AGENT_NAME_BIU and other language which appears gibberish to the unititated, and we replaced that with " Changes not saved.  First name cannot be all upper or lower case. Please fix the agent name and try again."
