### ISSUE TITLE
Bulkload/Remove/Append specimen remarks

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2556]
Is there a way to bulkload specimen remarks?

![image](https://user-images.githubusercontent.com/5725767/77121669-5a41e180-6a01-11ea-92ab-521b89f756e9.png)

**Comment by dustymc** [comment]
Nope. I can SQL for you, a loader/unloader might be useful once we get to PG.

**Comment by Jegelewicz** [comment]
OK, I'll gather mys stuff and send a csv.

**Comment by campmlc** [comment]
Isn't this Collection Object Remarks?

**Comment by Jegelewicz** [comment]
Yes

**Comment by campmlc** [comment]
Another one we should fix the terminology on.

**Comment by Jegelewicz** [comment]
@dustymc will this work?
[Collection Object Remarks Bulkload.zip](https://github.com/ArctosDB/arctos/files/4361646/Collection.Object.Remarks.Bulkload.zip)

**Comment by dustymc** [comment]
@Jegelewicz yes looks like that'll work - can I just replace or do I need to check for existing and append as necessary?

"Specimen remarks" is one instance of coll_object_remark.coll_object_remarks.

**Comment by Jegelewicz** [comment]
Just in case, check for existing and append please. Thanks!

**Comment by dustymc** [comment]
A bunch of these look like "duplicates" - see eg http://arctos.database.museum/guid/NMMNH:Paleo:54689

Remarks: J-55 

and from the file

NMMNH:Paleo:54689,J-55

append will result in ``J-55; J-55``

Is that intentional?

[temp_nm_cor.csv.zip](https://github.com/ArctosDB/arctos/files/4383567/temp_nm_cor.csv.zip)

**Comment by Jegelewicz** [comment]
Nope. Can you remove the dupes or do I need to make a new file?

BTW - you're the best!

**Comment by dustymc** [comment]
UAM@ARCTOS> delete from temp_nm_cor where COLL_OBJECT_REMARKS=CURENTREM;

1426 rows deleted.

NMMNH:Paleo:36065
Spoil pile
  28937396
spoil pile


UAM@ARCTOS> delete from temp_nm_cor where trim(upper(COLL_OBJECT_REMARKS))=trim(upper(CURENTREM));
7 rows deleted.

these were the obvious leftovers.


NMMNH:Paleo:57107
J-81 N. trench
  28939225
J-81 North trench

NMMNH:Paleo:40297
Jacket 2 Screenwash
  28937960
Jacket 2

PL/SQL procedure successfully completed.

**Comment by Jegelewicz** [comment]
Leaving this open as a request for a load/append/unload tool in PG.

**Comment by dustymc** [comment]
I'm digging the bulk unload/load mechanism/idea. "Append" is (in my brain...) just another step in the process; download, manipulate, delete, then load using the "original" data you downloaded mixed in with whatever you're trying to add. That also gives you a chance to make sure you're not appending the same thing, lets you control "delimiters," etc. 

If that's not sufficient - if we want to add 'append' somewhere in the process - this is a great time to iron that out.

**Comment by Jegelewicz** [comment]
> "Append" is (in my brain...) just another step in the process; download, manipulate, delete, then load using the "original" data you downloaded mixed in with whatever you're trying to add. That also gives you a chance to make sure you're not appending the same thing, lets you control "delimiters," etc.


That sounds like a good idea!

**Comment by campmlc** [comment]
I agree!

**Comment by dustymc** [comment]
Can be done in component loader ecosystem.

**Comment by campmlc** [comment]
Great! Sounds like we need an internal webinar on how to use the component
loader system?

**Comment by dustymc** [comment]
>how to use the component loader system

https://github.com/ArctosDB/arctos/issues/2974

**Comment by dustymc** [comment]
blocked by https://github.com/ArctosDB/arctos/issues/2974#issuecomment-779986500

**Comment by campmlc** [comment]
This would be hugely helpful. I vote high priority, especially given we are migrating data for so many new collections.

**Comment by wellerjes** [comment]
@dustymc could you please bulkload the attached specimen remarks? I downloaded all the applicable catalog records (and pulled some of the remarks out so I could bulkload them as attributes instead) and formatted the remaining remarks to fit in with our new notes. That way you can overwrite the current remarks without losing any information. Thanks!
[CHAS_SpecimenRemarksBulkload_2022-02-15.xlsx](https://github.com/ArctosDB/arctos/files/8073685/CHAS_SpecimenRemarksBulkload_2022-02-15.xlsx)

**Comment by dustymc** [comment]
I'll just go active on this, should be pretty quick.

I can load data for you, and something to test with would be very useful, but I need CSV for that.

**Comment by wellerjes** [comment]
Here's the CSV version; please let me know if you need any additional information besides the catalog/guid and updated remarks.
[CHAS_SpecimenRemarksBulkload_2022-02-15.csv](https://github.com/ArctosDB/arctos/files/8075294/CHAS_SpecimenRemarksBulkload_2022-02-15.csv)
Thanks!
