### ISSUE TITLE
Crinoid Parts

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#2557]
**Goal**
Add parts for crinoids. 

**Context**
In the process of preparing some new data for Arctos I came across crinoid columnals, and realized that while we have some part names that could be used for crinoids, they are not defined as such. See https://en.wikipedia.org/wiki/Crinoid#/media/File:Crinoid_anatomy.png although there are some variations on this, the arboreal cup is often also called the calyx, the stalk is often called the stem.

**Table**
http://arctos.database.museum/info/ctDocumentation.cfm?table=CTSPECIMEN_PART_NAME

**Value**

At minimum, I think we should add:
Stalk: the element of a crinoid that extends from the base of the calyx and anchors the crinoid to the sea floor. The individual skeletal elements of the stalk are called columnals.

Calyx is already in the table with a definition that covers several different types of organisms.

Arm; the appendages of a crinoid that branch off the top of the calyx and are used for movement and filter feeding.

I'm sure both "stalk" and "arm" could end up getting used for other things, but I'm not sure how to avoid that other than the definitions.

**Collection type**
ES

**Comment by dustymc** [comment]
The values seem reasonable to me.

I'm not sure about the definitions - eg, does "arm" apply to all echinoderms, or more, or just crinoids, or ????

> I'm not sure how to avoid that other than the definitions.

In general, I don't think you can. Arctos is a very diverse thing, English is a crazy language, it's not possible to safely make assumptions, definitions and documentation are part of the experience.

**Comment by Jegelewicz** [comment]
> I'm not sure about the definitions - eg, does "arm" apply to all echinoderms, or more, or just crinoids, or ????

Pretty sure it won't be long before someone uses it for a primate :-)

However, I think the definition is good. When someone wants to use "arm" for a starfish, we can add to the definition?

> The individual skeletal elements of the stalk are called columnals.

Should we also add columnal as a part?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> However, I think the definition is good. When someone wants to use "arm" for a starfish, we can add to the definition?

How about if we change to Arm: one of the appendages of an echinoderm that branch off the central calyx or disk and are used for movement or feeding.

I think this would also cover sea stars.

**Comment by dustymc** [comment]
>primate

We can't entirely stop that (yet!), but the documentation should make it very clear that no arm-ologist is likely to find the part either. (We-the-community CAN stop "arm" being added to Mamm code tables - https://github.com/ArctosDB/arctos/issues/2326.)

>add to the definition

Yes, but I think things usually go smoother if we can figure that out ahead of time. Does someone searching for "arm" actually want those orangutans? Do they want to go WAY towards the other end of the spectrum and avoid even starfish? I think we're almost always guessing at that, but sometimes these discussions do identify potential problems before fixing them involves changing existing data.

>also add columnal 

Or alternatively, is "arm" just "columnal" with a lot count? (Probably not??)

**Comment by aklompma** [comment]
Not all echinoderms have arms, for example sea urchins and Holothuroidea don't have them.
Arm is probably the best term to use for those that have arms.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> Should we also add columnal as a part

If we do, it should be stalk, columnal: one of the individual bony plates that stack to form the stalk of a crinoid or blastoid.

**Comment by Jegelewicz** [comment]
@ArctosDB/arctos-code-table-administrators any objections to adding these parts?

stalk: the element of a crinoid that extends from the base of the calyx and anchors the crinoid to the sea floor. The individual skeletal elements of the stalk are called columnals.

arm:  one of the appendages of some echinoderms that branch off the central calyx or disk and are used for movement or feeding.

**Comment by campmlc** [comment]
No objection.

**Comment by anna-chinn** [comment]
Fine by me.

**Comment by AJLinn** [comment]
This is outside my expertise... I have no objections if the specialists agree.

**Comment by aklompma** [comment]
Look good to me.

**Comment by Jegelewicz** [comment]
arm and stalk added.
