### ISSUE TITLE
Search on Part Holding Container by Part Type

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2558]
I'm trying to identify a search tool that will allow me to search on all specimen records that have a particular part type in a particular container type. For example, I would like to search for a MSB:Mamm records that have a part type = cestode (and nematode and trematode and acanthocephala . . . ) which is contained by container type cryovial.
If I use Specimen Search for this and select part = cestode and part container type = cryovial, I get all records that have both a cestode part and any part part that is in a cryovial. This is not obvious from the search page. How can I get the more restrictive search results?

**Comment by dustymc** [comment]
Should be done with https://github.com/ArctosDB/arctos/issues/2534
