### ISSUE TITLE
Issue with Saving New Records

### ISSUE THREAD

**Issue by cefilipek** [ArctosDB/arctos#2559]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
When attempting to save a new record I get a notice saying "edit template - bad"

**To Reproduce**
1. Go to data entry
2. Click on Enter a New Record
3. Insert information
4. Click Save as A New Record

**Expected behavior**
I would expect it to save or tell me what I did wrong.

**Screenshots**
![Screen Shot 2020-03-23 at 10 56 07 AM](https://user-images.githubusercontent.com/56844074/77336221-362e1b00-6cf5-11ea-8ef0-0cbf7f2a64d7.png)

** Data**
N/A

**Desktop (please complete the following information):**
 - OS: iOS
 - Chrome
 - Version 80.0.3987.149

**Additional context**
N/A

**Priority**
High

**Comment by dustymc** [comment]
Can you give me (dlm) access to one of your collections?

**Comment by cefilipek** [comment]
Absolutely. Right now we're working only on the JSNM:Paleo collection. I'm pretty sure I've given you access, but let me know if you can't get in.

**Comment by dustymc** [comment]
I'm not seeing it after a log out/in, and I don't _think_ that caches. Are you seeing me in http://arctos.database.museum/AdminUsers.cfm?Action=edit&username=dlm?

<img width="394" alt="Screen Shot 2020-03-23 at 9 19 25 AM" src="https://user-images.githubusercontent.com/5720791/77338318-6ec6f800-6ce7-11ea-8473-cec8d28330ab.png">

**Comment by cefilipek** [comment]
I clicked that link and it says I'm not authorized to access the form. Perhaps that's why you're not seeing access? Let me try giving you access again on the manage collections page.

**Comment by dustymc** [comment]
That's weird - you seem to have the right roles:

<img width="298" alt="Screen Shot 2020-03-23 at 9 29 04 AM" src="https://user-images.githubusercontent.com/5720791/77339322-d3cf1d80-6ce8-11ea-8bf5-5fde0774ee89.png">

Can you screenshot the error?

**Comment by cefilipek** [comment]
![Screen Shot 2020-03-23 at 11 31 30 AM](https://user-images.githubusercontent.com/56844074/77339531-e6058780-6cf9-11ea-9b30-5e4d91af3264.png)

**Comment by dustymc** [comment]
AHA! - apparently manage_agents is necessary for that, which I suppose makes sense. You have that now, Agents are globally shared so please be careful, see http://handbook.arctosdb.org/documentation/sharing-data-and-resources.html.

You'll probably need to log out/in, then you should be able to give me access.

**Comment by cefilipek** [comment]
Great! Just to make sure I don't mess something up, how do I give you the access. I was doing it under Manage Collection, but that may not be correct.

**Comment by dustymc** [comment]
<img width="380" alt="Screen Shot 2020-03-23 at 9 43 45 AM" src="https://user-images.githubusercontent.com/5720791/77340680-e5192980-6cea-11ea-8053-6c132b78887d.png">

From "me" just select your collection there and click grant.

**Comment by cefilipek** [comment]
Got it! Thank you!

**Comment by dustymc** [comment]
Got it - but the next part DOES cache, I'll get back to you in ~90 minutes!

**Comment by cefilipek** [comment]
No problem! Thank you!

**Comment by dustymc** [comment]
OK, the cache cleared but I was not able to replicate.



Did you get to the form via...

<img width="107" alt="Screen Shot 2020-03-23 at 10 23 12 AM" src="https://user-images.githubusercontent.com/5720791/77344409-59a29700-6cf0-11ea-8a6b-268d80ef0f46.png">

then...

<img width="241" alt="Screen Shot 2020-03-23 at 10 23 48 AM" src="https://user-images.githubusercontent.com/5720791/77344461-6e7f2a80-6cf0-11ea-9313-4d08eeacf9ab.png">


And are you sure you clicked this to save?

<img width="150" alt="Screen Shot 2020-03-23 at 10 18 49 AM" src="https://user-images.githubusercontent.com/5720791/77344002-c701f800-6cef-11ea-9da8-81638c7cf6cd.png">

My record is https://arctos.database.museum/DataEntry.cfm?action=edit&ImAGod=yes&CFGRIDKEY=97068483 - I'll try to remember to delete it when we're done here, feel free to do so or experiment with it or whatever.

**Comment by cefilipek** [comment]
Yes, that's how I got to the form. I'm definitely certain I clicked that button to save. The first record I entered saved just fine, though I haven't cleared it to load yet. I must have tried 5 or 6 times to get the one I was working on to save before requesting help; I even tried logging out, logging back in, and re-entering.

**Comment by cefilipek** [comment]
It seems to be working now. Perhaps it was a temporary issue? Thank you for all your help!

**Comment by dustymc** [comment]
Yay magic!

I think I have a rough idea of what's happened ("seed" identifiers aren't big enough) - I'll make sure we have some room to grow in the next version of Arctos.

**Comment by cefilipek** [comment]
Thanks again!
