### ISSUE TITLE
error feedback, attempting to bulkload media

### ISSUE THREAD

**Issue by jebrad** [ArctosDB/arctos#2560]
Hello - I got this error when trying to load my CSV of Media Metadata to the media bulkloader. Here is an example of one of "invalid" PREVIEW_URIs:  https://web.corral.tacc.utexas.edu/UWBM/Test/tb/tn_35813_D.jpg 

 "PREVIEW_URI": invalid identifier
[Macromedia][Oracle JDBC Driver][Oracle]ORA-00904: "PREVIEW_URI": invalid identifier 

** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **

** Outages should be reported to the contacts listed at https://arctosdb.org/arctos-down/ **

** Arctos Documentation is http://handbook.arctosdb.org/ **

** Learn more about Arctos at https://arctosdb.org/ **

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **

**Comment by dustymc** [comment]
The errors I'm seeing are from the specimen bulkloader. Are you here?

<img width="311" alt="Screen Shot 2020-03-23 at 11 14 58 AM" src="https://user-images.githubusercontent.com/5720791/77349164-d5541200-6cf7-11ea-81d3-3eddb1b06c41.png">

**Comment by jebrad** [comment]
Yes that is me, there -

Do I need to make my GitHug repository public?


Jeff

**Comment by dustymc** [comment]
Errors can take a while to filter in. Can you post a screenshot of the error including URL, and attach the CSV (you can zip it)? Maybe I can find what I need in that.

**Comment by jebrad** [comment]
[media_from_url-1.csv.zip](https://github.com/ArctosDB/arctos/files/4371500/media_from_url-1.csv.zip)
[bulkloader error grab.pdf](https://github.com/ArctosDB/arctos/files/4371509/bulkloader.error.grab.pdf)

**Comment by dustymc** [comment]
You need to be here

http://arctos.database.museum/tools/BulkloadMedia.cfm

https://github.com/ArctosDB/arctos/issues/2560#issuecomment-602772235

**Comment by jebrad** [comment]
OK.  Just added it.  Thanks.

**Comment by ccicero** [comment]
Looks like you guys are dealing with this, but let me know if there's anything I can do to help.

**Comment by jebrad** [comment]
OK - for those 10 images in the Test folder, their status shows "Cataloged Item matched 0 records."  Do I need to add something like "UWBM:Mamm" so it links the catalog number with the correct record?

**Comment by campmlc** [comment]
Yes, you will need the entire guid (institution code, collection code,
catalog number) in the related item field.

**Comment by jebrad** [comment]
Also, Dusty- I think I am close to figuring out how to have the bulkloader tool help me build a CSV that will work.   Still need help on that question from 6 minutes ago, but close. 
However: these instructions from your email this morning make very little sense to me (pasted below) - I am unsure what you mean by "link" here.  Please advise.
"You could link these as

specimen-->jpg--->archive

or

specimen-->jpg
and
specimen-->archive

I like the former - I think a lot of users inadvertently download huge files with the latter - but it's your call. Most UAM:ES specimens use the former, UAM:Herb the latter if you want to see it in action."

**Comment by jebrad** [comment]
Thanks Mariel.  Is that easiest to do in excel?  (merge cells so institution code and collection codes are included with catalog number).   That seems easier for me to do than trying to get the bulkloader tool to do it.

**Comment by campmlc** [comment]
Yes, easier to do in Excel. There is a SQL search and replace tool, but not
sure if it accessible via the media bulkloader.

**Comment by dustymc** [comment]
See http://arctos.database.museum/guid/UAM:Herb:106966

It has the DNG (original "everything that came out of the camera") and the JPG (built from the DNG) both linked to the specimen. (There's also a HTML link to morphbank - ignore it.) Everything's right there which is nice, but a lot of users click the big file when they really want the small.

vs https://arctos.database.museum/guid/UAM:ES:22253

only the JPGs are linked directly, click one of them...

https://arctos.database.museum/media/10254518

and you can get to the DNG from it

The plant was created with 

jpg --> shows cataloged_item
dng --> shows cataloged_item

and caribou with

jpg --> shows cataloged_item
jpg--> derived from (DNG) media

**Comment by jebrad** [comment]
Ahhh, yes very clear now thanks.  I just did the emoji for your response but I will probably not do that any more.

**Comment by jebrad** [comment]
OK this is good to be thinking about.  I had assumed I would only be linking one TIFF for each image I wanted linked to a record (in addition to selecting the thumbnail).  But now I see we are talking about linking both a TIFF and the decent-quality JPG for each image (plus the thumbnails).  I should have realized that when the JPG folder was created as part of Chris Jordan's processing (I guess I had considered them a second set of thumbnails).  Can you recommend a way to bulkload that in a single step?  Something like: Load all the JPGs, and for each give 2 media relationships: "shows cataloged_record XXX" and "derived from Media YYY"??

**Comment by Jegelewicz** [comment]
This might be useful. http://handbook.arctosdb.org/how_to/How-to-Upload-Media-to-TACC.html#small-batch-uploads

**Comment by dustymc** [comment]
@Jegelewicz the binaries are already at TACC.

@jebrad it will need to be two steps - first create the TIFFs, then use the URLs to create a 'derived from media' relationship to them (and the specimens) with the JPGs. Since TACC made the JPGs the URLs should be predictable; you should be able to extract the TIFF URL (for the relationship) from the JPG URL as you're loading for the second batch.

**Comment by jebrad** [comment]
Ah yeah.  "How to Bulkload media metadata" is so much clearer to me now than it was when I first read it this morning.  I will use that to attempt my plan of assigning 2 media relationships to each JPG to get to this:
jpg --> shows cataloged_item
jpg--> derived from (TIFF) media
Thanks very much!

**Comment by jebrad** [comment]
Thanks Dusty, this is fairly clear and I think will be clear enough when I try.  Will comment here if not.
