### ISSUE TITLE
data entry/bulkloader and "extras"

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#2562]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

The data entry screen writes UUIDs to the specimen bulkloader for later reassociating "extras." There are lots of ways to overwrite or lose those.

** Describe what you're trying to accomplish** 

A way that doesn't mix identifiers and data.

**Describe the solution you'd like**

Probably a new dedicated UUID (loads to otherIDs) column in the specimen bulkloader?

**Describe alternatives you've considered**

Use existing otherIds

**Additional context**
This has caused problems at least twice.

**Priority**
AWG?

refs:
https://github.com/ArctosDB/arctos/issues/2561

**Comment by Jegelewicz** [comment]
Is it impossible to use the GUID? If these extras could go directly into a batch upload tool (whichever one applies to the extra) using the GUID that would be awesome. Not sure how realistic that is....

**Comment by campmlc** [comment]
Problem is that they are created before the guid is created. Any way to
somehow associate them with the guid once that is created? E.g. I find the
uuids from these types of specimens entirely cryptic and have no means of
using or editing them.
High priority because data have been and continue to be lost, and we cannot
backtrack and find out what was lost without going one by one to original
data sheets.

**Comment by dustymc** [comment]
>Is it impossible to use the GUID?

Yes, there's not necessarily any such thing when the data are created.

>somehow associate them with the guid once that is created

That's going to involve some sort of unique-within-scope maybe-temporary identifiers. UUID does that (and some other stuff) and is really easy to produce.

>I find the uuids from these types of specimens entirely cryptic and have no means of
using or editing them.

I don't understand what this means. If you have no use for them, don't create them?!

**Comment by campmlc** [comment]
The uuids that show up in a specimen record cannot be used or interpreted
by human users to link to any data. As a user, I have no idea what
supplemental data were associated with that uuid, or whether the data were
or were not successfully loaded. It would be helpful if, once the
supplemental data are uploaded, the uuid would disappear from the specimen
record, so we don't wonder whether there is or is not some data out there
that hasn't been loaded yet, or whether it was lost or overwritten. The
only way to know whether all data from a record that has such a uuid has
been entered is to go back and look at the original datasheet, which will
never been done for all such entries.

**Comment by dustymc** [comment]
>cannot be used or interpreted by human users to link to any data.

They're not meant to be.

>once the supplemental data are uploaded, the uuid would disappear from the specimen
record,

This cannot be a technical problem. I can't possibly know if you've got some data in Excel on a thumb drive hiding under some grad student's desk that'll turn up in a couple years. CMs *can* (maybe...) know that, and ya'll can delete any identifiers you want to whenever you want.

**Comment by campmlc** [comment]
We now have the pending data alerts - that is helpful. Is there some point
at which pending data that isn't loaded disappears or is overwritten?
My concern is for data in the other bulkloaders that never gets properly
associated with the specimen record via the uuid.

**Comment by dustymc** [comment]
>pending data that isn't loaded disappears or is overwritten

Currently, no.

At some point we'll probably need to talk about that, but I think that would involve archiving a CSV or something. I'm not going to throw anything out, but I may eventually need to stuff it in the attic....

**Comment by campmlc** [comment]
OK, here is the problem I am having with using this tool. I am attaching a csv download of problems from the attributes bulkloader - these are attributes that were entered during single record data entry using the "extras" tool, and assigned a uuid. The error message says "specimen not found" which I assume means that the specimen record the attributes are attached to is somehow hung up waiting approval in a bulkloader somewhere? But these are records from 2015 - they should have been entered long ago. What I would like to do is to go back to the original data record (e.g. field catalog), find the field number, find the specimen, and see why it has not yet been cataloged so I can solve that and get these attributes loaded to the record. Alternately, perhaps the record did get cataloged, but somehow the UUIDs got disassociated with the parent specimen record?
 Regardless, with the current data in this csv file, I have no means of tracking down the original specimen data to solve these problems. What would allow me to do so would be having GUID prefix and any other IDs associated with the record during data entry as part of the download. Possible?
@dustymc 
[BulkloadAttributeData.zip](https://github.com/ArctosDB/arctos/files/4417126/BulkloadAttributeData.zip)

**Comment by dustymc** [comment]
>somehow hung up waiting approval in a bulkloader somewhere

From the daily email:

> Data for specimens which have not yet been entered are available at EnterData/Bulkloader/BrowseAndEdit-->Extras or the individual bulkloaders. 

>no means of tracking down

First one:

```
UAM@ARCTOS> 
UAM@ARCTOS> select count(*) from bulkloader where other_id_num_4='adf8c74c-26cf-41be-9ec4-c58471f3b70b';

  COUNT(*)
----------
	 0

1 row selected.

Elapsed: 00:00:01.14
UAM@ARCTOS> select count(*) from coll_obj_other_id_num where display_value='adf8c74c-26cf-41be-9ec4-c58471f3b70b';

  COUNT(*)
----------
	 0

1 row selected.
```

Someone has done something that should not have been done, or failed to clean up, or something.


```
UAM@ARCTOS> select count(*) from bulkloader_deletes where other_id_num_4='adf8c74c-26cf-41be-9ec4-c58471f3b70b';

  COUNT(*)
----------
	 0

```

That one - and a couple more - is not in the deletes either, so I suspect these were systematically removed from the data before it was loaded.


> What would allow me to do so would be having GUID prefix and any other IDs associated with the record during data entry as part of the download.

That's a major rebuild of a bunch of loaders, and still won't necessarily lead anywhere useful - eg, I don't see how it would help with these, the linking identifier seems to have been removed before anything was loaded.

I think a dedicated place for the linking identifier will help a bit, but that's not going to be magic either - good procedures are a necessary part of the puzzle.

**Comment by campmlc** [comment]
What would have been very helpful, especially now, is to have the other ID
and guid prefix in the display and csv download so we know which records
have lost their extras data. That would be / would have been exceedingly
useful. Now these data are lost for all intents and purposes.

**Comment by dustymc** [comment]
>have the other ID and guid prefix in the display and csv download so we know which records
have lost their extras data.

Can you explain how you envision this working? Someone may have modified something they shouldn't have (and there's no reason to think they didn't change other stuff, including the guid prefix, if they did), or the original specimen data are still in some external file that hasn't been loaded. I think we could add a great deal of complexity to a bunch of tools (and require all future tools to also carry that complexity) and still not actually add much, if any, security to the data. I'm not seeing a technical solution to what looks from here like a social problem.

**Comment by campmlc** [comment]
It isn't a social problem to not be able to see what specimen data record
(via the collector number, field number or what have you) the extras were
meant to be loaded to, in order to track down which specimens were or were
not updated correctly.

**Comment by Jegelewicz** [comment]
@dustymc as I have been loading the NMMNH Paleo data piecemeal, I can see how messy all of this raw data can be. I'm wondering if we can't figure out some way to break up the bulkloader entirely "behind the scenes" as it were.

So, a student enters a record that has 3 identifications, 20 parts, each with 2 attributes, and two specimen events. If the "bulkloader" worked such that these things all went to holding spots for their various bulkload tools (the identifications beyond one to the "bulkload identifications" tool, the parts and their attributes to the "bulkload parts" tool, and the specimen events beyond one to the "bulkload specimen events" tool, then could you use the "temporary UUID" to link them up but have the "mark to load" perform a succession of "loads" where the "basic record" would load, then the parts, then the events with the UUIDs removed at the end of the process?

It probably is crazy and too complicated, but these are the steps I am taking with data right now. I first load a "basic record" with no parts using the main bulkloader, then I load the parts, then I load the "research" events, other IDs, and in some cases specimen attributes. So it got me thinking about this.

I know - it's nuts, but just something creative to think about (because I have NOTHING better to do...)

**Comment by dustymc** [comment]
I'm prioritizing this. It should be fairly quick, should add significant data security, and would be a prerequisite for something like https://github.com/ArctosDB/arctos/issues/2178.

**Comment by campmlc** [comment]
I support this.

**Comment by dustymc** [comment]
done
