### ISSUE TITLE
Object records not showing up?

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#2563]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I just spent the past two days doing data entry for 17 items in the UAM:EH collection, for accession UA2019-025. When I search for this accession, it shows there are 17 records. 
<img width="1184" alt="Screen Shot 2020-03-24 at 1 10 27 PM" src="https://user-images.githubusercontent.com/17605945/77477458-3c91c500-6dd1-11ea-8a91-7c420e8cbf9d.png">

But when I click on the "specimen list" button to see those items I get this strange screen!
<img width="1186" alt="Screen Shot 2020-03-24 at 1 10 53 PM" src="https://user-images.githubusercontent.com/17605945/77477507-5206ef00-6dd1-11ea-9bd7-ad79131ffa30.png">

What have I done wrong???

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac OS10.14.6
 - Browser [e.g. chrome, safari] Chrome Version 80.0.3987.132 (Official Build) (64-bit)

**Priority**
High

**Comment by Jegelewicz** [comment]
I don't have an answer! @dustymc will have to weigh in.

**Comment by dustymc** [comment]
<img width="426" alt="Screen Shot 2020-03-24 at 2 30 40 PM" src="https://user-images.githubusercontent.com/5720791/77478967-250c0980-6ddc-11ea-822a-d6a80f655497.png">

usually explains this sort of thing. Looks like someone changed collection settings and there are still ~100K records processing. It should catch up eventually....

**Comment by AJLinn** [comment]
Thanks Dusty! I knew there must have been a place for me to figure out what was holding things up! I'll just be patient.

**Comment by AJLinn** [comment]
All good now!
