### ISSUE TITLE
Part to Container bulkload issues

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2565]
@dustymc  Please help identify what is wrong with this file. 
I get "item not found".
But the NK exists.
[DGR10270 Barcodes to Part Upload 3-25-20.zip](https://github.com/ArctosDB/arctos/files/4385051/DGR10270.Barcodes.to.Part.Upload.3-25-20.zip)

**Comment by campmlc** [comment]
It appears that some of these exist, but have a barcode already, and others are not yet cataloged. Not clear from the output which is which.

**Comment by dustymc** [comment]
Specifics would be very useful.

I searched a few of those and don't find anything.

I don't see why the form wouldn't move parts out of existing containers, barcodes or not.

**Comment by campmlc** [comment]
I bulkloaded some missing data and retried this, including a sample that was already in the specified container, and it seemed to work this time.
