### ISSUE TITLE
project title and formatting

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#2567]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

Some project titles contain formatting, which makes various things look wonky and hinders discovery/sort/etc.

**Describe what you're trying to accomplish** 

* consistent formatting
* consistent sort
* predictable content
* possibly better accessibility - I'm not sure if this messes with things like screen readers or not

**Describe the solution you'd like**

Possible solutions:

* Prohibit formatting, but that would preclude ``isolation by environment in <i>Sceloporus</i> and  the effect `` 
* Strip HTML for various forms, but that would still do the above, would add some (perhaps significant) computing cost, and would do nothing for APIs.
* Better documentation
* ???????????????????????????

**Describe alternatives you've considered**
Do nothing; this doesn't obviously BREAK anything, I just noticed the offset formatting, I could be convinced that this is a feature and not a bug. If that's the case, recommend documentation.

**Additional context**

<img width="1120" alt="Screen Shot 2020-03-26 at 8 26 34 AM" src="https://user-images.githubusercontent.com/5720791/77664487-8f878b80-6f3b-11ea-8d2e-04fd30ba17ce.png">

<img width="560" alt="Screen Shot 2020-03-26 at 8 27 06 AM" src="https://user-images.githubusercontent.com/5720791/77664525-9d3d1100-6f3b-11ea-910d-1a52973d7f15.png">

1. Also note the extra space in ``isolation by environment in <i>Sceloporus</i> and[this is 2 spaces but markdown makes it pretty!]the effect`` - if we do something, perhaps we should try to deal with things like that.
2. Are there other similar data in Arctos?
2. Are there languages other than HTML used for this?

**Priority**

Probably low, but delaying this will mean more cleanup if we ultimately do something.

**Comment by ewommack** [comment]
I suppose, since projects are intended to be viewed by groups of people outside of Arctos, it might be important to fix the formatting issue and figure out the solution?

**Comment by Jegelewicz** [comment]
See also #1962 #2190 and #2191

**Comment by dustymc** [comment]
Merge to https://github.com/ArctosDB/arctos/issues/2570

**Comment by Jegelewicz** [comment]
Thinking a line break between the annotation thingee and the title will solve this? Made the change, needs to be pulled to find out.

**Comment by dustymc** [comment]
Certainly won't solve discoverability, and I think the annotation thing is css-floating and should be immune to html.
