### ISSUE TITLE
Locality Change Notification down?

### ISSUE THREAD

**Issue by anna-chinn** [ArctosDB/arctos#2569]
I changed a few localities yesterday, but didn't received a Locality Change Notification email. I've been getting Collecting Event Change notification daily, so I don't think they're going to junk mail/whisked away by my institution's spam filter. The last Locality Change Notification I received was March 3rd.

**Comment by dustymc** [comment]
This isn't quite a bug, it's a lack of resources - the queries are timing out, the code would (eventually...) do what it should.

I'm not sure what to do about this. I just don't seem to have the processors to do what's really needed. The expensive thing is also the important thing - calculating changes to collections and getting those to users - so I'm not sure I could trade functionality for performance and still be left with anything useful. We just need to move before this finds a way to turn into a catastrophe.

**Comment by dustymc** [comment]
FYI I changed a couple thousand random localities in test and that was easily handled by the notification service.

<img width="588" alt="Screen Shot 2020-03-28 at 9 51 18 AM" src="https://user-images.githubusercontent.com/5720791/77828623-d14e3880-70d9-11ea-9f5e-3227cb94bbf7.png">

**Comment by anna-chinn** [comment]
Darn... That's unfortunate. So this is awaiting Postgres?

For now, I cobbled together some SQL that's good enough for my purposes. Posting it here in case anyone else relies on the email notification to monitor on-going projects:

```
SELECT distinct locality_archive.changedate,
locality_archive.locality_id,
locality_archive.georeference_source georeference_source_old,
locality_archive.locality_remarks locality_remarks_old,
locality_archive.spec_locality spec_loc_old,
agent.preferred_agent_name changed_by,
locality.spec_locality spec_loc_new,
locality.georeference_source georeference_source_new,
locality.locality_remarks locality_remarks_new,
flat.collection_cde

From locality_archive

left join agent on locality_archive.changed_agent_id = agent.agent_id
left join locality on locality_archive.locality_id = locality.locality_id
right join flat on locality.locality_id = flat.locality_id

where changedate like '2020-03-27'
order by changedate
```

**Comment by dustymc** [comment]
I played with the SQL some more, it's performing a bit better than it was but it's still pretty slow. It seems to be handling small/normal jobs now, but I suspect it'll still fail if there are lots of changes, and that all seems to depend on what else is going on at the time.
