### ISSUE TITLE
Should we also add columnal as a part?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2573]
> Should we also add columnal as a part

If we do, it should be stalk, columnal: one of the individual bony plates that stack to form the stalk of a crinoid or blastoid.

_Originally posted by @Nicole-Ridgwell-NMMNHS in https://github.com/ArctosDB/arctos/issues/2557#issuecomment-602850719_

**Comment by Jegelewicz** [comment]
Revisiting - there are quite a few specimens with part name = "columnal". I am not sure that I like the comma separated suggestion of "stalk, columnal" probably because we don't do this for other things, we just use the given part name (we don't say "skeleton, vertebra"). Also I'd like to get the commas out of part names and move the modifiers to part attributes (see https://github.com/ArctosDB/arctos/issues/2354#issuecomment-558395911).

**Comment by dustymc** [comment]
Yea I don't like the comma either.

In the interest of normalization, either "columnal" + lot count instead of "stalk" or "stalk" + partial instead of columnal should be considered.

In the interest of reality, whatever - I have no real objections to 'columnal.'

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I don't mind reducing to just "columnal"

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
stalk + partial is fine.
