### ISSUE TITLE
Searching for Agents Outside Your Collection

### ISSUE THREAD

**Issue by alexkrohn** [ArctosDB/arctos#2577]
Often when I'm adding (particularly legacy) specimens to Arctos one-by-one in data entry, I want to check if an unknown agent is already in Arctos. So, I open a new tab and do an agent search for that agent. Often, I find a potentially good match (e.g. Myrnal L. Hawes is probably the real collector for a small mammal in British Columbia given to UCSC from the MVZ with the collector as "M. Hawes"). However, when I try to confirm my suspicious by searching the MVZ collections for any specimens by Myrnal L. Hawes collected at the MVZ ([here](https://arctos.database.museum/SpecimenResults.cfm?collector_agent_id=10005395&collection_id=28&coll_role=collector)), I get no results. This is because I'm signed into my account from UCSC.

In order to both search other institutions' collections/agents, and enter my own data, I need to open Arctos in an incognito window. When I do this, I confirm that Myrnal L. Hawes indeed collected shrews in British Columbia at the MVZ at the same time. Our M. Hawes is very likely Myrnal L. Hawes.

That process of switching to incognito mode seems a bit silly and cumbersome for what, at least at UCSC, is a frequent task. Is there a way to disable this restriction on searches when you're logged in? Or could this be a new feature to add? Perhaps, when you  begin to search outside of your collection, there could be a warning at the top that says "These results may include agents from outside your collection." 

Thanks for your help.

**Comment by dustymc** [comment]
This is a feature request.

Read-only access to various VPD slices are (mostly, I think) technically plausible. This would require rethinking the VPD model and addressing any social concerns (eg, how encumbered data interact with 'operator, but not for this collection' users).

Alternatively or additionally, the agent summary page could perhaps contain more data - a taxa+geography+year summary or similar. That would also need to consider encumbrances.

See also http://handbook.arctosdb.org/documentation/agent.html#creating--maintaining-agents and http://handbook.arctosdb.org/documentation/agent.html#deletingmerging-agents specifically

>Do not orphan unused names; flag them as “bad duplicate of” the good name so that they will be reviewed and deleted. (Use “unknown” as the good name if there is no acceptable alternative.)

I went ahead and created that relationship.

**Comment by Jegelewicz** [comment]
VPD enhancement needs funding.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/3659
