### ISSUE TITLE
Add Gilbert Islands to the Island Groups

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#2584]
The Gilbert Islands form the main part of Kiribati. (The Republic of Kiribati to be exact).

Source:  https://en.wikipedia.org/wiki/Gilbert_Islands

Table: https://arctos.database.museum/info/ctDocumentation.cfm?table=CTISLAND_GROUP

**Value**:  Gilbert Islands

Adding Gilbert Islands will make the addition of Tarawa (where the capital is located) more precise.   It will complete the three groups: Line Islands, Phoenix Islands and Gilbert Islands.

Definition:  Formerly Kingsmill or King's-Mill Islands.  A chain of sixteen atolls and coral islands in the Pacific Ocean that form the main part of Kiribati.   "Kiribati" is the Kiribati rendition of "Gilberts."

**Priority**
medium

**Comment by sharpphyl** [comment]
This has "needed discussion" for over a year.  

@dustymc Can you detail what you need to add this island group?

**Comment by dustymc** [comment]
done
