### ISSUE TITLE
Arctos Media Storage Allocation at TACC

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2587]
We need collections with large media storage requirements to budget for short term media storage in grants. But as a community we need to also budget for maintaining this storage at TACC for the long term. How to allocate costs between collections with expensive storage and others with none? 
See #2582

**Comment by campmlc** [comment]
From #2582 discussion:

@anna-chinn "We are proposing to digitize (i.e. scan) our motion picture film collection and, along the way, catalogue the films in Arctos, store both high and low res copies of the video files at TACC Corral, and connect it all using the Arctos media module. When the project is complete, we'll have approximately 130 hours of scanned footage and 1,400 catalog records. Based some preliminary scans we had done this winter, it looks like scanning and preserving the entire collection will require ~20TB (!!) of storage space. "

@jldunnum the storage issue is critical going forward in terms of TACC hosting CT scan data from Artcos collections

**Comment by campmlc** [comment]
@dustymc  I think the current Arctos allocation at TACC is "about 10TB" but I'm not sure where that came from (seemed like a very large number at the time?) or how hard the limit is.

cost to reserve 100TB

https://portal.tacc.utexas.edu/user-guides/corral

~$12K

TACC has some tape archive that is less accessible but significantly cheaper than disk. Tossing 12TB of "hope we never need this" .stl files on there and getting them back with a couple days notice might be feasible. Maybe that could even make sense for "originals" (DNGs and WAVs and such) in Arctos, but it would probably take a fair bit of data for the storage costs to balance the development costs.

From TACC:

The tape archive is available for 1/4 the usual Corral disk cost, so around $30/TB/year at present. I’m not sure quite how we would so a periodic retrieval, but we can figure something out. The other option would be to use the unreplicated Corral storage, which is currently 1/2 of the Corral fee or $60/TB/year. That would at least be simpler to manage.

doesn't have the internal budget ... once the grant period ends,

**Comment by campmlc** [comment]
Current storage rate at TACC: $118/TB 
AWG call 4-9-20

**Comment by dustymc** [comment]
Amazon Glacier was mentioned in AWG meeting - glacier is a bit more expensive than TACC, deep glacier is cheaper, both come with transfer fees that could very quickly get very expensive. Both will almost certainly very happily delete your data if you don't pay them, which I think would ~never happen with TACC. https://aws.amazon.com/glacier/faqs/

The first TB of TACC storage is free. Can we require collections (or users?) to use that before accessing "Arctos" storage, or work out something with TACC to pool that into "Arctos" storage, or somehow better leverage that?

Assuming a compression ratio of 10:1, keeping originals on tape and derivatives (which can be rebuilt at any time) on nonreplicated disk would get total storage costs down to about $40TB/year, vs. $118 for replicated-on-disk (all we're currently using). That would almost certainly require some development, plus some sort of additional complexity and time in accessing originals. That'd very quickly pay for itself if we're talking about hundred-terabyte-scale storage, and _if_ we can live with the restrictions less-accessible originals would bring.

**Comment by campmlc** [comment]
Is this something we need to add in to the TACC SABI budget?

**Comment by dustymc** [comment]
>add in to the TACC SABI budget

Maybe??

Paying for storage doesn't seem very sustainable for anyone. (Quick, find the billion or so photographs of herbarium specimens that were allegedly created when NSF was in to that sort of thing.) Building long-term and accessible file storage that actually is sustainable might be a decent selling point if we can pitch it right. I was thinking we'd use the savings to pay for the development, but earmarking some $$ to do that up front might work as well.

**Comment by campmlc** [comment]
I agree. Worth revisiting the budget if not too late.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/internal/issues/119
