### ISSUE TITLE
Connection refused - error feedback

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2590]
** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **

** Outages should be reported to the contacts listed at https://arctosdb.org/arctos-down/ **

** Arctos Documentation is http://handbook.arctosdb.org/ **

** Learn more about Arctos at https://arctosdb.org/ **

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **

Was going to bulkload records. From the Arctos main menu selected Enter Data > Bulkloader > Bulkload Specimens and immediately got this message:

![image](https://user-images.githubusercontent.com/5725767/79137353-cd741480-7d6f-11ea-88dd-b6d74676cd2d.png)

**Comment by Jegelewicz** [comment]
Now I get it for anything and worse, Googling "Arctos" does not even bring up the search portal!

**Comment by dustymc** [comment]
TACC doesn't monitor our Issues - https://arctosdb.org/arctos-down/. I sent email.

Looks like Oracle melted. We're all tested up and ready to go to PG anyway, right?!

I'm pretty sure an outage doesn't immediately affect Google search.

**Comment by sharpphyl** [comment]
Google search works but this is what you get.

![Screen Shot 2020-04-13 at 10 52 52 AM](https://user-images.githubusercontent.com/15368365/79140281-f8149c00-7d74-11ea-9b11-6a4294c1e12b.png)

**Comment by Jegelewicz** [comment]
So if we cannot get production working, will we at least be able to get data as of yesterday into PG? If not, how how much am I going to need to re-create (months of work?). Just prepping myself....

**Comment by mkoo** [comment]
that's brings up a good point. Can we send AWG to PG-Arctos for at least a
read-only version of Arctos? If so, what is the latest date of mirrored
data?

I just need a search and read-only version of Arctos so we should suggest
that if we have a date-stamp for the data there.

**Comment by campmlc** [comment]
I don't know if it would help, but I can offer local server space for a PG
mirror at UNM.
