### ISSUE TITLE
Add two terms to the CTTAXON_STATUS table

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#2591]
**Goal**
WoRMS "taxon status" terms include _taxon inquirendum_ and _alternate representation_.  This issue requests a  match in the CTTAXON_STATUS table so the "taxon status" field is not omitted.

**Context**
When WoRMS uses the terms "taxon inquirendum" or "alternate representation" there is no match to our CTTAXON_STATUS code table.  In both cases, the metadata omits the Taxon Status.  Note: the links below are in the test area but should be identical when Arctos comes back up.  

An example of "taxon inquirendum" is _Oleacina saccata_ at http://test.arctos.database.museum/name/Oleacina%20saccata#WoRMSviaArctos.  The WoRMS (via Arctos) has no taxon status.  The WoRMS entry is at http://www.marinespecies.org/aphia.php?p=taxdetails&id=1347200  

For an example of "alternate representation" see, see _Murex brevispinia macgillivray_ at http://test.arctos.database.museum/name/Murex%20brevispina%20macgillivrayi#WoRMSviaArctos.  The preferred name is at http://www.marinespecies.org/aphia.php?p=taxdetails&id=527263.   Both names are accepted but the alternate representation is not the preferred name and does not have "accepted" as its taxon status in WoRMS (which becomes "valid" in WoRMS (via Arctos).  

@dustymc will adding these terms allow us to get the taxon status?  

**Table**
CTTAXON_STATUS

**Value**
taxon inquirendum
alternate representation

**Definition**
WoRMS has the following definitions in their manual.

taxon inquirendum = an incompletely defined taxon that requires further characterization, it is impossible to identify the taxon
alternate representation = to link species that are represented twice: once with and once without subgenus. Alternate representation can also be used for a species and its nominal subspecies.

**Priority**
medium

**Comment by dustymc** [comment]
http://test.arctos.database.museum/info/ctDocumentation.cfm?table=cttaxon_status

How's taxon inquirendum !=  nomen dubium?

http://test.arctos.database.museum/info/ctDocumentation.cfm?table=cttaxon_term

How's "alternate representation" not better served by relationship+preferred_name?

I'd have to look at the code, but I don't think it'll pick up on new terms - I believe it's looking for specific values, translating them, and ignoring everything else.

**Comment by sharpphyl** [comment]
> How's taxon inquirendum != nomen dubium?  

See WoRMS definitions below

> How's "alternate representation" not better served by relationship+preferred_name?

That could work but the taxon status metadata doesn't appear, so you have to follow the synonym to see if the other taxon name is valid.  It would be helpful to see that it's an "alternate representation" which means it's accepted but not the preferred name.  

Here's another example of the alternate representation:
Arctos: http://test.arctos.database.museum/name/Abbottellinae#WoRMSviaArctos
WoRMS: http://www.marinespecies.org/aphia.php?p=taxdetails&id=932868

Here are the taxon statuses used by WoRMS from their website under "Change Status of a Name".  
http://www.marinespecies.org/aphia.php?p=manual#topic50.  I'm not tied to explicitly use these (though it would make the WoRMS (via Arctos) source more complete), but it would be helpful if Taxon Status weren't missing when there isn't a match to our code table.  When I was working in the test area, I just happened to come across two taxa without any status and found it was because the WoRMS statuses (alternate representation and taxon inquirendum) aren't in our code table.  

I believe your coding adjusts "accepted" to "valid" and "unaccepted" to "invalid" so I'm ok with a similar adjustment that we can all agree on.  I haven't mentioned the other two that we don't have (Temporary name and Interim unpublished) only because I haven't run across them yet, but it would make sense to consider them as well.  We could indicate in our table that they are WoRMS (via Arctos) terms.

> Possible statuses for a name:

> Accepted: the used name is accepted in the present literature (reads "valid" in Arctos)

> Unaccepted: The used name is NOT accepted in the present literature (reads "invalid" in Arctos)

> Nomen nudum: a name that does not comply with the name requirements of the codes, such as lack of a description or diagnoses or reference to a description or diagnosis or a type specimen is lacking for publications after 1999 (in Arctos CTTAXON_STATUS table)

> Alternate representation: to link species that are represented twice: once with and once without subgenus. Alternate representation can also be used for a species and its nominal subspecies (note: you can only add a subspecies if the species is present in the database). 

> Nomen dubium: a name of uncertain application, because it is not possible to establish the taxon to which it should be referred. A good example is the "Ascothoracida" genus Laocoon. There is a debate whether this is based on a parasite or on a detached piece of the host. It is clearly a dubious name.  (in Arctos CTTAXON_STATUS table)

> Temporary name: to create higher rank taxa to accomodate child taxa for which the classification is not sorted yet

> Taxon inquirendum: an incompletely defined taxon that requires further characterization, it is impossible to identify the taxon

> Interim unpublished: an as yet unavailable name (until in a print issue) which has been published online only, in a work that does not show evidence of ZooBank registration (ICZN Article 8.5)

**Comment by dustymc** [comment]
From my perspective - and it's not the only one, and might not even be valid in this case - WoRMS and Arctos are doing very different THINGs. WoRMS is a taxonomy database - they're concerned with the formalities of the names - and Arctos is primarily a specimen database where taxonomy are metadata. 

That's the most obvious place my perspective could be wildly wrong - Arctos CAN be viewed as a taxonomy database, where the taxa just happen to occasionally have some specimens hanging off them. If that's how someone's using this, then nothing I'm going to say here probably makes sense to them. 

ANYWAY, from the perspective of a specimen database which needs to pick appropriate taxa, this seems overly complicated. We have a "just use this one" pathway to get users to the "correct" (according to someone for some purpose) name (and therefore classification). Complicating that by adding a bunch of other pathways that ultimately all lead to the same place is probably more "interesting" than the average data entry person needs.

I still can't see anything in your definitions that would conclusively lead me to either taxon inquirendum or nomen dubium.

>Nomen nudum

I can't see any reason to allow this into Arctos; the definition precludes use, right?

>Alternate representation

There's why we don't build simple models or allow tradition to control us....

>Temporary name

What?! No!

>Interim unpublished

not very interested unless someone's going to clean these up when they become official-enough

**Comment by anna-chinn** [comment]
From taxonomy committee:
For these kind of taxon statuses, can we capture verbatim taxon status from WoRMS in a remarks field?

**Comment by Jegelewicz** [comment]
and map

taxon inquirendum = nomen dubium

**Comment by Jegelewicz** [comment]
or use "doubtful" and put taxon inquirendum or other in remarks.

**Comment by sharpphyl** [comment]
"Doubtful" would work for the several "miscellaneous" terms as it would at least alert data entry volunteers to double-check their identifications.  Let's see if Carol comes back with a different idea to consider.

**Comment by sharpphyl** [comment]
The more I think about it, I would suggest the taxon status to be "uncertain" rather than "doubtful" unless Carol comes up with something better.  "Uncertain" could substitute for "taxon inquirendum" and anything else from WoRMS that isn't in our table such as "Temporary name" or "Interim unpublished."  That would give us a status for all WoRMS (via Arctos) entries.

The exception would still be "Alternate Representation" which means it is accepted (valid), but not the preferred taxon.  In our collection, we don't use the "Alternate Representation" taxa, but some collections might because of legacy identifications.  I'm not sure most of the taxa with this status actually get into WoRMS (via Arctos) because they are mostly subgenera (in parentheses in WoRMS) which are no longer preferred.  Sometimes I can find them and sometimes I can't.  

> Interim unpublished

> not very interested unless someone's going to clean these up when they become official-enough

Wouldn't they automatically be cleaned up when WoRMS changes the taxon status?

**Comment by sharpphyl** [comment]
BTW we could also use "uncertain" if we add a taxon with limited or somewhat confusing validity.  I've had a few (and I think Teresa has too) where we needed the name and could find very limited (and often very old) references.  Right now we don't have a good way to describe our confidence in the validity of the taxon and "uncertain" would be a good choice.  When I add a taxon name like this, it shows that I added it and I put myself down as the manager, so I hope we could periodically search for them and update the status if we find better information.

**Comment by Jegelewicz** [comment]
> From my perspective - and it's not the only one, and might not even be valid in this case - WoRMS and Arctos are doing very different THINGs. WoRMS is a taxonomy database - they're concerned with the formalities of the names - and Arctos is primarily a specimen database where taxonomy are metadata.
> 
> That's the most obvious place my perspective could be wildly wrong - Arctos CAN be viewed as a taxonomy database, where the taxa just happen to occasionally have some specimens hanging off them. If that's how someone's using this, then nothing I'm going to say here probably makes sense to them.

It is true that WoRMS is a taxonomy database, but IMO it is also true that a taxonomy database (actually databases: Arctos, Arctos Plants, WoRMS (via Arctos)) is essentially what we are building in Arctos Taxonomy (it is redundant work, a waste of precious time, and super frustrating, but that IS what we are doing with a bit of assistance from the ability to clone from Global Names or grab stuff directly from WoRMS). For some groups of taxa, the job is much easier than others, but even there (birds, mammals) there are synonyms, dubious names, etc. I think that @sharpphyl and myself are making efforts to have what shows up in Arctos Taxonomy be  the best it can be, but with the constantly changing landscape of taxonomy and the fact that no one has successfully created a functioning taxonomy database with the added bonus that neither of us are any kind of taxonomic expert makes it really frustrating.

In my dream taxonomy world, we would have a list of taxon names, each with a link to nicely curated (by experts!) taxonomy database. NO CLASSIFICATIONS would need to be stored in Arctos! Wouldn't that be heaven? If the expertly curated database had no classification for a term that one of our rogue curators decided to use - TOO DAMN BAD. They can go request to have the name added to the taxonomy database and argue with other taxonomists about how that should work and we can happily continue to enter collection data, because that is what we are tasked with, not determining the validity of a name used in an identification.

Now that I have ranted - I think this all needs to take a back seat to testing PG and getting actual data we can work with because right now I am having to explain to my employer that we have nothing to show for the last 6 months they have paid me.

**Comment by sharpphyl** [comment]
Yes, let's put this on the back burner for now.

**Comment by Jegelewicz** [comment]
> If the expertly curated database had no classification for a term that one of our rogue curators decided to use - TOO DAMN BAD. They can go request to have the name added to the taxonomy database and argue with other taxonomists about how that should work and we can happily continue to enter collection data, because that is what we are tasked with, not determining the validity of a name used in an identification.

https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.3000736

**Comment by Jegelewicz** [comment]
In order to have some sort of taxon_status for all WoRMS (via Arctos) classifications, we suggest the following mapping of terms from WoRMS to Arctos taxon_status

WoRMs status | Arctos taxon_status 
 -- | -- 
accepted | valid 
unaccepted | invalid 
nomen nudnum | nomen nudum 
alternate representation | invalid (add accepted name in the "preferred name" metadata attribute) 
nomen dubium | nomen dubium 
temporary name | invalid (add "temporary name" to the remark metadata attribute) 
taxon inquirendum | nomen dubium 
interim unpublished | invalid (add "interim unpublished" to the remark metadata attribute) 
uncertain | invalid (add "uncertain" to the remark metadata attribute)

**Comment by sharpphyl** [comment]
Small typo:  WoRMS status is Nomen nudum

For WoRMS "taxon inquirendum" I would suggest that we (add "taxon inquirendum" to the remark metadata attribute) as we have for the others.

**Comment by Jegelewicz** [comment]
Updated - @sharpphyl did you know you can edit the comments? Next time, feel free to just change stuff!

**Comment by sharpphyl** [comment]
I can edit mine but don't see how I can edit yours.

**Comment by sharpphyl** [comment]
Can we discuss at the next meeting and move forward with this or should it be part of our larger project on modifying the taxonomy module #2695?

**Comment by sharpphyl** [comment]
We need to change "alternate representation" from invalid to valid.  It's not the preferred name but it may be accepted.  See, for example, http://www.marinespecies.org/aphia.php?p=taxdetails&id=1395894.  On the page leading to it, it shows it as "accepted, alternate representation."  

Either that or leave exactly what WoRMS says is the status instead of modifying it then having to make a remark to clarify it.  Definitely my preference as some people may only look at the metadata on the search page and never see the remark.

<img width="666" alt="Screen Shot 2020-08-15 at 8 24 41 AM" src="https://user-images.githubusercontent.com/15368365/90314410-cf421600-ded0-11ea-95e1-fa3c4f86ba8f.png">

**Comment by Jegelewicz** [comment]
Discuss in committee

**Comment by Jegelewicz** [comment]
Just use WoRMS terms so that WoRMS can transfer over intact.

**Comment by Jegelewicz** [comment]
Taxonomy Committee suggests adding these terms so that WoRMS (via Arctos) can agree with WoRMS.

**Comment by dustymc** [comment]
>WoRMS (via Arctos) can agree with WoRMS

Dima was insinuating that he's willing to work with WoRMS to get a more complete data pull. We've talked about allowing non-local classifications to be preferred by collection for various reasons at various times, which should be mostly a social problem. Together that would solve this, and let us ditch a bunch of expensive code in the process. Strongly suggest we completely exhaust that possibility before investing more in something that might have a much more elegant solution.

**Comment by Jegelewicz** [comment]
> How's "alternate representation" not better served by relationship+preferred_name?

Agree. As I was working on this I thought exactly the same thing, BUT how do we make this happen automagically? Especially when the "alternate" name isn't in Arctos (most of those with a subgenus aren't). @sharpphyl I don't think this term would really make a difference to your data entry people, would it?

**Comment by sharpphyl** [comment]
For names with a taxon status of "accepted, alternate representation" just having "accepted" appear as the taxon status shouldn't make a difference to our data entry people.  Typically, it's just missing the subgenus since it doesn't look like we're currently capturing them (though I can and do add them where needed).  @Jegelewicz   Does that answer your question?

**Comment by Jegelewicz** [comment]
I think so....

**Comment by dustymc** [comment]
> how do we make this happen automagically?

Encourage GN and WoRMS folks to work a bit closer together. Just using GN would fix that particular issue by not needing the translation. (Then I'd have to figure out how to make "untranslated" terms available for operators in the UI, which shouldn't be too difficult.)

**Comment by Jegelewicz** [comment]
Pending outcome of #3311

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/2926 makes this irrelevant
