### ISSUE TITLE
Make Encumbrance status more obvious in add loan item user interface

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2593]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
Encumbered records that have Restrict Usage should have this encumbrance very prominently displayed, even possibly with a pop-up warning requiring a click, in order to add to a loan.

** Describe what you're trying to accomplish** 
Force curatorial review and acknowledgement of usage encumbrances prior to loan

**Describe the solution you'd like**
more prominent disply, require active acknowledgement 

**Describe alternatives you've considered**
Loan things that should not be loaned and cause a lot of problems for everyone

**Additional context**

**Priority**
High but can wait until PG

**Comment by dustymc** [comment]
>require active acknowledgement

I believe this is functionally a request to disallow bulk-adding loan items. Acceptable?

As this would involve rebuilding the loan add form, it's probably a good place to discuss @campmlc 's

>Strange display interface for adding items to loan - hope we can customize this.

comment from https://github.com/ArctosDB/PG-migration-testing/issues/26#issuecomment-614265419

Here are the issues (that I could quickly find) which lead to the current form.

ArctosDB/arctos#1999
ArctosDB/arctos#1561
ArctosDB/arctos#1413
ArctosDB/arctos#2508
