### ISSUE TITLE
associatedTaxa for host associations

### ISSUE THREAD

**Issue by seltmann** [ArctosDB/arctos#2597]
I am working with Evin Dunn and Neil Cobb for the Parasite Tracker NSF project. We are making some changes to Symbiota (SCAN) to better support species interactions and dwc:associatedOccurrences. Part of this project, we are integrating data from many platforms (Arctos, Specify, KEmu, etc.) One thing I noticed is that Arctos does not fill out the host association information in dwc:associatedTaxa, but does have this information (verbatimHostId) in dwc:dynamicProperties.

My request/question is if you would consider also adding the information to dwc:associatedTaxa? It is the darwin core field that people will most likely look to find associated information, and the data can be included as a key:value, to include the relationship and verbatim host name.

Thank you for your consideration,
Katja

Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

** Describe what you're trying to accomplish** 
An clear and concise overview of the goals; why are you asking for this?

**Describe the solution you'd like**
How might we accomplish your goals?

**Describe alternatives you've considered**

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by campmlc** [comment]
Hi Katja,
We can certainly look into this. Also, please be aware that Arctos
primarily makes associated taxa available through relationships,which go to
GBIF as associated occurrences, as in
https://www.gbif.org/occurrence/1145354227.

**Comment by seltmann** [comment]
Hi @campmlc !
I am aware of that and I am not advocating for replacing any present functionality or pipeline. I do see an opportunity here for the data to be easier to discover by a larger community of folks, especially since the information already exists in other darwin core fields. Thanks for looking into this.

**Comment by campmlc** [comment]
That certainly seems reasonable. We would ideally want to make both
discoverable, with the relationship info taking priority, as the verbatim
host id is not standardized or taxonomically updated, may include
mispellings, outdated or common names, and is much less reliable as a
source of association data than the info coming from
relationships/associated occurrences. Also, not everything that has an
associated occurrence has a recorded verbatim host id. Any way to flag one
source as preferred?

**Comment by campmlc** [comment]
@dustymc @dbloom

**Comment by seltmann** [comment]
Well, it is of course up to what ya'll think is best, but I was thinking:

relationship:verbatimHostName in the dwc:associatedTaxa field. Everything else in the Arctos records would remain exactly the same.

**Comment by campmlc** [comment]
Can you describe how the TPT would deal with a situation where there is
conflict between the verbatim host ID and the relationship to a cataloged
associated occurrence? Would it be possible to prioritize the latter?

**Comment by seltmann** [comment]
We do not prioritize things, rather it would come into SCAN in the associatedTaxa field, and associatedOccurrence would exist in the associatedOccurrence field.

 I attached screenshots and the record is linked below from an MPM arthropod record and how it is being included into SCAN/TPT

<img width="890" alt="Screen Shot 2020-04-17 at 11 56 24 AM" src="https://user-images.githubusercontent.com/1044474/79604835-af761f00-80a3-11ea-8e5d-54201a27308f.png">

![Screen Shot 2020-04-17 at 11 54 52 AM](https://user-images.githubusercontent.com/1044474/79604845-b3a23c80-80a3-11ea-97ed-95c3d81418e5.png)

Example record: https://scan-bugs.org/portal/collections/editor/occurrenceeditor.php?csmode=0&occindex=10&occid=41632648&collid=235)

**Comment by campmlc** [comment]
That's helpful, thanks!

**Comment by campmlc** [comment]
Following up on this, @dustymc @dbloom  what do we need to do to publish values for the verbatim host ID attribute to dwc:associatedTaxa? These data are currently published to dwc:dynamicProperties.

**Comment by Jegelewicz** [comment]
Returning to this since recordedByID is currently a fail.

@dbloom says adding new dwc fields shouln't break anything, and this seems like it might be kinda easy?

**Comment by campmlc** [comment]
This would be good to prioritize - for NSF funded collaborations with SCAN and TPT.

**Comment by Jegelewicz** [comment]
Request:

publish values in the verbatim host ID attribute to dwc:associatedTaxa. These data are currently published to dwc:dynamicProperties.

**Comment by Jegelewicz** [comment]
BUT, other things belong here too? **associated_species**

How do we make it clear what is host and what is just nearby? Maybe that doesn't matter?

**Comment by Jegelewicz** [comment]
This needs to be a concatenation of [associated species](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#associated_species), [verbatim host ID](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#verbatim_host_id), and taxa in identifications of records related through other identifiers?

Added to [working document](https://docs.google.com/spreadsheets/d/1IeqgpGaj7DkzHSNPrbTLpMdWSEx3IlYwu3xAYjRpec8/edit).

**Comment by mkoo** [comment]
in mapping workbook. also issue is over 4 years old so closing
