### ISSUE TITLE
Need better error message for "I don't know which part you mean"

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2600]
This is beyond the scope of this repo; looks to me like it works slightly better than Oracle did. Feel free to open an issue in the main repo if there's not already one.

I stole your data, so you'll have to reload. You have this:

<img width="720" alt="Screen Shot 2020-04-19 at 9 18 43 AM" src="https://user-images.githubusercontent.com/5720791/79693338-cf7e1d80-821e-11ea-92e7-8055c44b22aa.png">

the record looks like this

<img width="291" alt="Screen Shot 2020-04-19 at 9 19 15 AM" src="https://user-images.githubusercontent.com/5720791/79693346-e1f85700-821e-11ea-8e15-fb246c168ed9.png">

so the 'find the part' SQL returns this

   key    | container_barcode | collection_object_id 
-----------+-------------------+----------------------
 265476001 |                   |             28806424
 265476001 |                   |             28806383
 265476001 |                   |             28806342

Three parts match what you've supplied, it can't tell what you're trying to do, so it errors.

_Originally posted by @dustymc in https://github.com/ArctosDB/PG-migration-testing/issues/92#issuecomment-616174551_

**Comment by campmlc** [comment]
Some version of
"Your query matches multiple search items for the following records"
would be useful output for many tools in Arctos as well as this one,
including barcode to container.


Mon, Apr 20, 2020, 7:24 AM Teresa Mayfield-Meyer <notifications@github.com>
wrote:
