### ISSUE TITLE
Accession bulkloader needs rebuilt

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2601]
Maybe change verbiage to "review the data below"?

![image](https://user-images.githubusercontent.com/5725767/79770917-454fbb00-82eb-11ea-8abc-4d9991916487.png)

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/PG-migration-testing/issues/107#issuecomment-616636359_

**Comment by dustymc** [comment]
Accession bulkloader needs rebuilt in the component loader system

**Comment by dustymc** [comment]
@Nicole-Ridgwell-NMMNHS there was some NMMNH:Geol data in the old loader, I stashed it in https://github.com/ArctosDB/arctos-assets

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks! I've downloaded the file, it can be deleted now.
