### ISSUE TITLE
LastPartLocation appears odd in search results

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2604]
OK, woke up and realized I was looking at the wrong thing.  Here is how it appears to me in the search results:

![image](https://user-images.githubusercontent.com/5725767/79879112-84454580-83ab-11ea-850f-a0c8a88728f3.png)

while in the record page it appears like this

![image](https://user-images.githubusercontent.com/5725767/79879418-dedea180-83ab-11ea-8a8d-7cf8e448bd99.png)

It does appear that the JSON is leaving out the date and determiner or something here. Maybe it has something to do with barcodes? I don't know what is supposed to end up here - I have never really used it. Will move to the main repository.

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/PG-migration-testing/issues/111#issuecomment-617223903_

**Comment by Jegelewicz** [comment]
Example is from http://test.arctos.database.museum/guid/ALMNH:ES:4658

**Comment by dustymc** [comment]
Ahhhhh.....

Thanks, fixed.
