### ISSUE TITLE
specimen search timeout handling

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#2606]
**Is your feature request related to a problem? Please describe.**

Some things time out; we can't, and will probably never be able to, respond to all queries in a reasonable amount of time.

** Describe what you're trying to accomplish** 

Give users what they want, but don't add too much overhead either.

**Describe the solution you'd like**

In a meeting it was suggested that a 'your query timed out, enter {something} here and we'll {email or something} a file later' option would be nice.

How do we satisfy legit requests without adding a bunch of overhead responding to exploratory queries that'll never be examined or acting as a personal shopper?

**Describe alternatives you've considered**

There's always been a 'use the contact link to get what you want' message on timeouts. It very seldom gets used, which suggests this isn't much of a problem?

**Additional context**

We may need to change the "We impose no strict limits on the number of records that may be returned" verbiage in the error; test currently does limit results to 50K records.

**Priority**

??

**Comment by Jegelewicz** [comment]
> How do we satisfy legit requests without adding a bunch of overhead responding to exploratory queries that'll never be examined or acting as a personal shopper?

I don't have an answer, but I would think that "personal shoppers" might be deterred by the simple task of making the request? We probably need some data, so trying something like this for a while to see if there are tons of requests or just a few and then making a decision based upon some facts might be a good idea.

> There's always been a 'use the contact link to get what you want' message on timeouts. It very seldom gets used, which suggests this isn't much of a problem?

Yeah - just the extra step probably discourages people who are just messing around. On the other hand, it might also be discouraging people with legitimate questions - people are used to getting what they want, when they want it...

> We may need to change the "We impose no strict limits on the number of records that may be returned" verbiage in the error; test currently does limit results to 50K records.

We should definitely change the verbiage to match whatever limit we set.

Priority - I'm assuming we don't need to ensure this happens until we move to PG, but we should probably get it ironed out now so we can focus on other stuff when migration actually happens.
