### ISSUE TITLE
Part name - pollen

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2607]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Goal**
Properly describe parts

**Context**
Describe why this new value is necessary and existing values are not.

**Table**
http://test.arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name

**Value**
pollen

**Definition** 
A fine to coarse powdery substance comprising pollen grains which are male microgametophytes of seed plants, which produce male gametes (sperm cells). https://en.wikipedia.org/wiki/Pollen

**Collection type**
Herb, ES

**Part tissue flag**
for plants yes, for fossils no?

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
>for plants yes, for fossils no?

I think in the current model all no-parens parts should not be tissue. That will carry over to preservation attributes as well. Without the parenthetical (==>preservation, eventually) information, users should just assume you've prepared and/or stored it in whatever way makes it least suitable for their needs.

If you know more - if you can refine this to "pollen (fossil)" or "pollen (frozen)" or similar - then I suggest doing so, and we can pull that back out when we migrate everything else.

**Comment by Jegelewicz** [comment]
For what I am doing, I can add the preservation = fossil

**Comment by Jegelewicz** [comment]
@ArctosDB/arctos-code-table-administrators any opposition to adding this part? If I hear nothing, I will add it on Friday.

/remind me to check this on Friday.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I support this!

**Comment by campmlc** [comment]
Me too!

**Comment by Jegelewicz** [comment]
Done
