### ISSUE TITLE
Part name - meteorite

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2608]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Goal**
properly name parts

**Context**
Considered geosample, but this isn't material originally from the Earth's crust

**Table**
http://test.arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name

**Value**
meteorite

**Definition**
A solid piece of debris from an object, such as a comet, asteroid, or meteoroid, that originated in outer space and survived its passage through the atmosphere to reach the surface of a planet or moon. https://en.wikipedia.org/wiki/Meteorite

**Collection type**
ES

**Part tissue flag**
no

**Priority**
Please assign a priority-label.

**Comment by Jegelewicz** [comment]
Do we want to be specific? When volcanic rock is collected from Mars, will the classification be different than for volcanic rock collected in NM? I guess the collection locality will give it away? (and I cannot wait to add that locality to Arctos....)

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
If that ever happens then yes, I think the collection locality is where that info would go. I am sad that our moon rock is technically a loan and thus we don't get to add the Moon to our higher geography.

**Comment by campmlc** [comment]
Is "meterorite" currently searchable via A (string) identification? Seems
like that could be useful?

**Comment by dustymc** [comment]
>searchable via A (string) identification

Like all strings, only to the extent that the entry folks can spell. So no....

Google suggests there's a relevant taxonomy eg https://geology.com/meteorites/meteorite-types-and-classification.shtml so should be no reason to spell anything.

**Comment by Jegelewicz** [comment]
> Is "meterorite" currently searchable via A (string) identification? Seems like that could be useful?

Awaiting mineral/rock taxonomy... see https://github.com/ArctosDB/arctos/issues/2338 and https://github.com/ArctosDB/arctos/issues/2231#issuecomment-676476923

**Comment by Jegelewicz** [comment]
Add part meteorite.

**Comment by Jegelewicz** [comment]
added
