### ISSUE TITLE
Part name - spore

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2609]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Goal**
catalog fossilized spores

**Context**
Spores are not seeds, ova or sperm. (The difference between a "spore" and a "gamete" is that a spore will germinate and develop into a sporeling, while a gamete needs to combine with another gamete to form a zygote before developing further. )

**Table**
http://test.arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name

**Value**
spore

**Definition**
A unit of sexual or asexual reproduction that may be adapted for dispersal and for survival, often for extended periods of time, in unfavourable conditions. https://en.wikipedia.org/wiki/Spore

**Collection type**
ES, Herb

**Part tissue flag**
yes, but depends on the preservation

**Priority**
Please assign a priority-label.

**Comment by Jegelewicz** [comment]
@ArctosDB/arctos-code-table-administrators any opposition to adding this part? If I hear nothing, I will add it on Friday.

/remind me to check this on Friday.

**Comment by campmlc** [comment]
I support this.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I support this as well.

**Comment by Jegelewicz** [comment]
Done
