### ISSUE TITLE
Part Name - steinkern

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2610]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Goal**
catalog fossil material

**Context**
Maybe this isn't necessary, but wanted to discuss it. I considered just using the part name "shell" with the preservation "fossil mold, internal", especially because it seems like steinkern could be used for things other than shells given the definition.

Of course, in researching, I stumbled across this conversation about molds and casts - seems there is not real agreement about what they are!

**Table**
http://test.arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name

**Value**
steinkern

**Definition**
A steinkern is a fossil that has formed by sand or mud filling up the inside of a shell and hardening. The shell itself often dissolves away, leaving just the fill behind. https://www.cretaceousmantua.com/category/by-fossil-type/steinkern/

A fossil formed from sediment that filled a hollow structure such as a shell. https://en.wiktionary.org/wiki/steinkern

**Collection type**
ES

**Part tissue flag**
no

**Priority**
Please assign a priority-label.

**Comment by campmlc** [comment]
This doesn't sound functionally different from mold or cast . . .or most
fossils, e.g. bone or wood replaced by minerals in the same shape and
configuration? Maybe we need a part attribute for "discipline specific
terminology" that is also automatically searched along with part name. . . .

**Comment by dustymc** [comment]
>discipline specific terminology

https://github.com/ArctosDB/arctos/issues/2546#issuecomment-597726952

**Comment by Jegelewicz** [comment]
> Maybe we need a part attribute for "discipline specific terminology" that is also automatically searched along with part name. . . .

Agree, but with a different take. Rather than creating yet another attribute, what if we had the term available for searching, but when someone searches for "steinkern", they really just get stuff that is "part name" plus preservation = "fossil mold, internal"? So we have a table of search terms like this:

Part Search Term |  Part Name | Part Preservation 
-- | -- | -- 
coprolite | feces | fossil 
steinkern | % | fossil mold, internal 

We would have to let whoever is searching know that although they have searched "steinkern", Arctos parts will instead display the preservation value of "fossil mold, internal" so they won't be confused by the results.

**Comment by Jegelewicz** [comment]
Need @Nicole-Ridgwell-NMMNHS @aklompma @dperriguey to weigh in.

**Comment by aklompma** [comment]
Steinkern is a German word for internal mold, but sometimes used in papers.

Yeah, there are people who use mold/cast incorrectly, but here it is:
- Internal mold (=steinkern): interior of fossil (usually shell) filled up with sediment/rock (not including actual shell)
- External mold: exterior of fossil (usually shell) surrounded by sediment/rock (not including actual shell)
- Cast: Exact replica of fossil, without any of the shell/bone/tooth. Can happen when shell dissolves and space left behind within the rock is filled up with sediment/rock again to mimic how the animal looked like. Think of plaster casts of teeth, bones, shells, etc., as an analogy. So it is essentially the internal mold + the shell replaced by sediment/rock.

**Comment by dustymc** [comment]
I don't have a good model suggestion and we've been looking for that sort of thing for a while. Ideally a search for "rib" would magic back whole organism (skeleton, etc.) vertebrates - something more sophisticated than a simple synonymy.

**Comment by Jegelewicz** [comment]
So @aklompma you would be willing to find steinkerns by searching for shell with th preservation fossil mold, internal?

How do we tell people that's what they should do when they want steinkerns - make it explicit somewhere like https://github.com/ArctosDB/arctos/issues/2610#issuecomment-619264944

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Agree with what @aklompma says.

> We would have to let whoever is searching know that although they have searched "steinkern", Arctos parts will instead display the preservation value of "fossil mold, internal" so they won't be confused by the results.

Is there a need for a message? The only reason I think they would be confused is if they don't know what a steinkern is.

**Comment by Jegelewicz** [comment]
> Is there a need for a message? The only reason I think they would be confused is if they don't know what a steinkern is.

People are people. They search for part "steinkern" and when they look at results, they don't see that word anywhere. First reaction will be WTH, I didn't get any steinkerns! I'm not suggesting they wouldn't figure it out, but that they will immediately hit the "contact" button and someone will have to respond with

> "Arctos does not store the part name "steinkern". Instead, such objects are referred to by the part represented such as "shell" with the preservation of "fossil mold, internal".

Just trying to head that off at the pass.

**Comment by Jegelewicz** [comment]
NMMNH steinkerns cataloged as shell with preservation fossil mold, internal
