### ISSUE TITLE
No results in Geography search

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2613]
Is it the case in Arctos Oracle that when there are no results you just see this?

![image](https://user-images.githubusercontent.com/5725767/80314718-577c9e00-87b0-11ea-8e47-cdc2bd7077e4.png)

Or is there something to the effect of

"Your search returned no results"?

I think we need the message, especially for public searches.

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/PG-migration-testing/issues/125#issuecomment-619589616_

**Comment by dustymc** [comment]
Should not be relevant under current form, closing
