### ISSUE TITLE
Award number link out to Crossref

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2614]
While testing ArctosPG, I decided to click the link out from an award number in a project and I'm not sure it is doing anything useful.

The project is http://test.arctos.database.museum/project/10002576

When I click on the award number MA-30-15-0392-15 I end up here: https://search.crossref.org/?q=MA-30-15-0392-15

There is nothing relevant about that award there. Ideally, I would end up here: https://www.imls.gov/grants/awarded/ma-30-15-0392-15

I don't see the Award number defined in the documentation, and I may have done this incorrectly, which means it's probably that way for others as well? We need a better process and documentation for Award number in Projects so that links go somewhere that makes sense based upon the funding agency or we should just enter a url.

**Comment by dustymc** [comment]
>not sure it is doing anything useful

It's probably not there; "useful" requires publications to submit with data that leads to https://www.crossref.org/services/funder-registry/

https://github.com/ArctosDB/arctos/issues/1694

>should just enter a url

You can do that with Media. There's a system that can potentially let you get at "the $$ to collect this rat ultimately supported $$$$$$$$$$$$$$$$$$$$$ of research"; this is an attempt to tie into it.

>don't see the Award number defined in the documentation

Yes that needs done.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/3398
