### ISSUE TITLE
suspicious (typo?) reference to http://arctos.database.museum/guid/MSB:Mamm:MSB:Mamm:152843 .

### ISSUE THREAD

**Issue by jhpoelen** [ArctosDB/arctos#2618]
via @qgroom - I wanted to point you to a suspicious  (typo?) reference to http://arctos.database.museum/guid/MSB:Mamm:MSB:Mamm:152843 .

**Comment by campmlc** [comment]
The production database is down for temporary maintenance, it should be up
by end of the week.

**Comment by jhpoelen** [comment]
@campmlc thanks for the update and good luck with completing the maintenance.
