### ISSUE TITLE
Bulkloader error

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2621]
Attempting to get back the last month of work. Loaded a file that previously was loaded to Arctos. Getting this after check and load - stuff is in the temp table.

![image](https://user-images.githubusercontent.com/5725767/80503861-b0267500-892f-11ea-9cdd-82a08e55dd0a.png)
[L-210_299.zip](https://github.com/ArctosDB/arctos/files/4546706/L-210_299.zip)

**Comment by dustymc** [comment]
That's Oracle being Oracle - Lam's on it.

**Comment by lkvoong** [comment]
Should be fixed:
- UAM_IDX_1 is not a bigfile tablespace, so added another 31G datafile UAM_IDX_02.dbf to the tablespace.

While I was there, I also:
- Increased maxsize for users01.dbf to 10G.
