### ISSUE TITLE
Prospective Collections Form Updates

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2622]
I suggest we change the wording on the Prospective Collections Form to be something a bit less abrupt (http://arctos.database.museum/new_collection.cfm)
How about instead of:
You must log in to access the Prospective Collection Form.
Instead:
Please create a user log in to access the Prospective Collection Form.

This whole form could use some work to make it significantly more welcoming and user friendly, but this would be a good start.

**Comment by campmlc** [comment]
From @dustymc 
Yea I hate that form - it's too normalized, which confuses people. Suggest we flatten it (one entry per collection) and maybe mitigate that by pulling "institution" data from previous submissions and existing collections. Lam's going to have to rewrite the scripts that actually create collections for PG anyway, it's a good time to mess with the structure. Issue please!

https://www.crozierfinearts.com/ is interesting - might be pretty cool to have a commercial collection. "Here's the Arctos data for the art you just acquired, there's the join form if you'd like to make it your own...." (And after the nonprofit exists, "there's the donation form...")

**Comment by campmlc** [comment]
Any reason we can't act on @Jegelewicz idea and just direct users to this login page?
http://arctos.database.museum/login.cfm
Then we could update that single page and only have one form to maintain.
Also, once they log in, do potential collections get redirected to the form? Or do they have to log out and in again?

**Comment by dustymc** [comment]
>just direct users to this login page?

Sure, or http://arctos.database.museum/login.cfm?gotopage=new_collection.cfm, but it's a lot more likely to bounce them around if they miss a step.

>update that single page and only have one form to maintain.

I'm all about normalization, but maintaining that isn't much of a problem - and we at some point after much discussion decided on that, I'm not sure what the need to change it now is?

>redirected to the form?

If you mean from the create account option on the form, they never leave.

>Or do they have to log out and in again?

No

**Comment by campmlc** [comment]
We have three forms? Jeez, no wonder I get confused. I think all the forms
should contain the same information, especially regarding how to create an
operator password. And the word "Please".
Any way to make these forms editable and allow operator editing with
permissions?

**Comment by dustymc** [comment]
@campmlc unless someone stops me I'm working on this today - links or screenshots of something would be useful, I'm not sure what you're talking about.

I really don't know what you mean by "allow operator editing with permissions" but if you're suggesting to move this form back out of Arctos that's fine, we just need importable CSV with which to create collections. Please let me know ASAP.

**Comment by campmlc** [comment]
At a minimum, we need to change the first sentence at the login page users reach when they click 
(http://arctos.database.museum/new_collection.cfm)
to read: "Please create a user log in to access the Prospective Collection Form."
Right now, this is what they see:
![Screenshot 2020-05-05 12 02 55](https://user-images.githubusercontent.com/14808196/81099629-7540b600-8ec8-11ea-8d45-28646313c482.png)

Alternatively, we could just provide a more generic, consistent page that could be shared among all login pages, especially by requiring consistent, operator appropriate user names and passwords.
Here are other login pages users encounter:
![Screenshot 2020-05-05 12 01 10](https://user-images.githubusercontent.com/14808196/81099742-9ef9dd00-8ec8-11ea-8e8c-64feec01a79d.png)

**Comment by dustymc** [comment]
>Please create a user log in to access the Prospective Collection Form."

But that's not accurate! If they have a login, they can use it.

>requiring consistent, operator appropriate user names and passwords.

New issue, but I'm not sure how (or why) we'd accomplish that now. I certainly have a few "noncompliant" usernames, and every single one of them is accompanied by a noncompliant password.

**Comment by campmlc** [comment]
"Please log in or create an account  for further access to Arctos interfaces,
downloads, and forms.  You may log in above, or create an account here. To
create a public account, simply supply a username and password here and
click Create Account.

To create an Operator account (recommended for Arctos users) please use the
following to create usernames and passwords:
Account name must use only letters and numbers (ASCII characters A-Z, a-z,
and 0-9), and cannot begin with a number or contain spaces, underscores,
hyphens, or punctuation. (Public users can use any characters.)
Operator passwords must contain at least six characters, starting with a
letter, containing only A-Z, a-z, 0-9, and !$%&()`*+,-/:;?_., not
containing the username, and consisting of at least one letter, number, and
special character.
See http://handbook.arctosdb.org/documentation/users.html for more
information on Arctos Operator Accounts."

**Comment by dustymc** [comment]
Almost perfect.

>cannot begin with a number 

should be

>must begin with a letter


I changed that, it'll be in the revised form.

**Comment by dustymc** [comment]
There is an entirely new form in test. It should be very familiar; it's all copy-paste from the "old" form, but has been rebuilt in light of experience with the old form to have much simpler functionality.

* There's now only one form; it's used to create, edit by the prospective collection, and edit by Arctos staff. 
* There's no separation between institution and collection, which has caused endless confusion. Redundant "institution" data may be cloned from previous requests. TODO: import from existing Arctos collections.
* Submitting email is a separate step, allowing the submitter any amount of time and any number of saves to edit the request before notifying the Arctos community
* Access has been simplified. Anyone with global_admin can access any form, and the initial requestor plus anyone they name in username_access_list can access their requests. There is no longer a step-wise progression (which NEVER worked as intended); the Mentor simply works with the incoming collection until everything is satisfactory then alerts the DBA team in whatever way they find most convenient.

**Comment by ccicero** [comment]
Here is a recommendation for prospective new collections:
https://docs.google.com/document/d/18zZeWIuBvpFjnyGNY-4WDgOVkkOSdZz1or7TVnqKz8Y/edit?ts=5edfea5e

**Comment by ccicero** [comment]
Per discussions with @dustymc and AWG officers, the "Create New Collection" form will be separated from the pre-Arctos admin information (to be done through a Google form with shared access that @mkoo will set up). It was suggested that both of these forms would be under a new Arctos main tab called "Join Arctos" (maybe also move "Find a Mentor" there?) to the right of About/Help.

The new "Create New Collection" form will have the following fields. These will be used to create the new collection. Once the collection is created, the fields in this form can be used to populate corresponding fields in Manage Collection. Additional fields - licensing, DwC for EML exporter, collection contacts - will be filled in manually by the collection working with the mentor.

Table will have the following fields (corresponding form label in parentheses - put in this order in the form)

institution_acronym (Institution Acronym)
collection (Collection Type) - this should be semi-standardized eg "Mammal specimens" (can we make this a drop down list?)
collection_cde (Collection Code)
descr (Collection Description)
guid_prefix (GUID Prefix)
catalog_number_format (Catalog Number Format) - make this a drop down list
preferred_taxonomy_source (Taxonomy Source) - make this a drop down list
loan_policy_url (Loan Policy URL)

Also add?
collection_terms (Collection Terms) - default = Arctos Terms of Use

If this is supposed to be NOT NULL, should it be included here in the form? Or should it be done with the mentor at the same time as the internal_license and external_license?

**Comment by dustymc** [comment]
> collection (Collection Type) - this should be semi-standardized eg "Mammal specimens" (can we make this a drop down list?)

See https://github.com/ArctosDB/arctos/issues/1662

> catalog_number_format (Catalog Number Format) - make this a drop down list

https://github.com/ArctosDB/arctos/issues/2818

> preferred_taxonomy_source (Taxonomy Source) - make this a drop down list

https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxonomy_source

**Comment by dustymc** [comment]
There's a new "final" form in test

<img width="255" alt="Screen Shot 2020-06-26 at 11 42 36 AM" src="https://user-images.githubusercontent.com/5720791/85890422-29acd900-b7a2-11ea-9cb3-87995009880c.png">

And I did this while I was in there:

<img width="142" alt="Screen Shot 2020-06-26 at 11 46 10 AM" src="https://user-images.githubusercontent.com/5720791/85890669-acce2f00-b7a2-11ea-8d89-da04d58862a9.png">


You'll need manage_collection to see it.

<img width="1332" alt="Screen Shot 2020-06-26 at 11 41 59 AM" src="https://user-images.githubusercontent.com/5720791/85890388-1a2d9000-b7a2-11ea-9f7e-192788a3f265.png">

<img width="936" alt="Screen Shot 2020-06-26 at 11 33 12 AM" src="https://user-images.githubusercontent.com/5720791/85889806-059cc800-b7a1-11ea-9d32-502ad2967fa1.png">


@lkvoong table is pre_collection

**Comment by ccicero** [comment]
Looks good. I guess we need optionally re: mentor because some existing collections may want to create another collection for their institution and don't need a mentor.

In the menu, maybe change it to "Finalize new collection request" to make it a little clearer.

I just submitted a test. Went through fine. Once it's submitted, and the new collection is created, who communicates that to the admin_user? Maybe it should say something like:

Submission successful. Contact the DBA team on GitHub to finalize or to correct any errors. Please reference the GUID_Prefix you just submitted.

Once the new collection is created, a DBA will notify you (and the  mentor if one is assigned) so that you can start migrating data into Arctos. 

can we do the latter and automatically send a notification to those users?

**Comment by dustymc** [comment]
I changed the text.

I'm not sure how we'd make "automatically" work but Lam can add it to the create scripts.

**Comment by ccicero** [comment]
That would be good, so we don't have to keep checking to see if it's been done.

Thanks!

**Comment by ccicero** [comment]
Finalizing the process for new collections:

- A new [Prospective Collection form](https://docs.google.com/forms/d/e/1FAIpQLSec0BuRKDGDjqxT1fRI31GbZc0TORLK6DoLjZReQfnl5iIyDA/viewform) is linked from both arctosdb.org and from Join Arctos --> Prospective Collection Request 

**@dustymc please update link from https://arctos.database.museum/new_collection.cfm**

- Submitted form goes to arctos-working-group-officers@googlegroups.com, who then conduct all the usual business, discussion, demo...then ready for MOU.

- new [Arctos MOU form](https://docs.google.com/forms/d/e/1FAIpQLSe5B1RKmrWG9f5OCZ4e3d7U1YB3LeEuBND-zVI7l42mzpzpUQ/viewform) is submitted to help with that process

- Once the MOU is signed, new collections are created by filling out a new [Finalize Collection Creation Request form](https://arctos.database.museum/Admin/pre_collection.cfm  ) for each collection (form is accessible to operators with Manage Collection) - this should be done by the mentor working with the collection/institution and Dusty

- Dusty and Lam use that information t to create the new collection in Arctos. 

@dustymc @lkvoong ideally, notification sent automatically to collection contact (and mentor) when collection is created.

**Comment by dustymc** [comment]
http://test.arctos.database.museum/new_collection.cfm is updated, but maybe it's better to just link....

<img width="204" alt="Screen Shot 2020-07-01 at 1 33 06 PM" src="https://user-images.githubusercontent.com/5720791/86288814-6d875000-bb9f-11ea-9fe5-5165422ab1d9.png">

to the form?

We should be talking to mentors and the new admin through the process, particularly regarding GUID, collection code, and catalog number format.

**Comment by ccicero** [comment]
Yes, just link directly to the form. That's what I was thinking.

@ebraker @campmlc what do you think about having a session (during webinar hour?) devoted to mentoring new collections, sometime this summer?

**Comment by campmlc** [comment]
Great idea on the session.

**Comment by Jegelewicz** [comment]
> a session (during webinar hour?) devoted to mentoring new collections, sometime this summer?

YES - I can definitely help with that one. We have tools to walk collections through the process of [on-boarding](https://github.com/ArctosDB/new-collections) and [migration](https://github.com/ArctosDB/data-migration/issues) to help and I would love to introduce everyone to them.

**Comment by campmlc** [comment]
Good timing too, since we are getting questions from several right now.

**Comment by ccicero** [comment]
Great. Let's add this to the next AWG regular meeting.

**Comment by campmlc** [comment]
Do we have a label for "Add to next AWG meeting"? Some other means of flagging these issues for that purpose?

**Comment by ebraker** [comment]
A new collections session sounds super! It will be great to have a recording of onboarding and migration for future incoming collections to watch as well.
Normal webinar times = July 7, Aug 11, Sept 8 - though I'm open to whenever is convenient.

**Comment by dustymc** [comment]
I snuck a release out (BerkeleyMapper is https - yay!) so this is now in production.

**Comment by ccicero** [comment]
@ebraker next week seems a little soon, but I also hate to wait until August. Maybe we do a special session? Thoughts from others?

**Comment by ccicero** [comment]
Yay @dustymc  for BerkeleyMapper, thanks!

**Comment by Jegelewicz** [comment]
> Do we have a label for "Add to next AWG meeting"? Some other means of flagging these issues for that purpose?

Add to AWG Agenda Project - done

**Comment by mkoo** [comment]
Close?

**Comment by Jegelewicz** [comment]
I think so. So I'll just do it....
