### ISSUE TITLE
Join Arctos Webpage updates

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2623]
We may want to update the first sentence at https://arctosdb.org/join-arctos/ to include cultural collections as well as natural history:

This is an exciting time for natural history museums! Arctos is not just a static data archive, but instead represents a community of museum enthusiasts (curators, collection managers, directors, investigators, and educators) who are committed to pushing the envelope of management, discoverability, and use of digital natural history and cultural to address important questions.

**Comment by mkoo** [comment]
Hi mariel, updated the whole paragraph-- give a read and let me know
I definitely removed 'just' from the second sentence as I dont think that's
what we want to say!
thanks

**Comment by Jegelewicz** [comment]
This is looking awesome! I want to join! Oh wait...

Perhaps a link from  "create an account" in the second paragraph to https://arctos.database.museum/login.cfm?username=&badPW=true&err=Your%20user%20name%20must%20be%20at%20least%20one%20character%20long.&gotopage=/home.cfm

Although, this too needs to be friendlier - Why all the red?

**Comment by Jegelewicz** [comment]
And this belongs on the create an account page too

> Usernames cannot have a period (e.g., carla.cicero is not acceptable). Passwords should be at least 8 characters and contain a combination of letters, numbers, and at least one symbol (e.g., $ @ !).

I know it isn't true for non-operators, but I don't really care. Better to create an operator possible account than have to go create another one later...

**Comment by dustymc** [comment]
>Why all the red?

The link goes to a state of failure.

There's an account create option on the form itself.

**Comment by Jegelewicz** [comment]
The MOU templates work two different ways. The one up in the text opens a word doc and the one at the bottom a Google doc. They should be to the exact same thing to avoid one of them being obsolete or incorrect.

**Comment by Jegelewicz** [comment]
![image](https://user-images.githubusercontent.com/5725767/80611885-72d9ea00-89f8-11ea-920a-90c568e17346.png)

@campmlc said

> Also, I suggest we change the wording on the Prospective Collections Form to be something a bit less abrupt (http://arctos.database.museum/new_collection.cfm)
> How about instead of: (
> You must log in to access the Prospective Collection Form. 
> Instead:
> Please create a user log in to access the Prospective Collection Form.

**Comment by mkoo** [comment]
More updates to arctosdb.org
-- a little friendlier language and explanation about the process.

The other comments pertain to arctos.database.museum (dusty territory)

**Comment by campmlc** [comment]
This looks much better! I'm thinking we should tweak it one more time to include reference to Arctos as a collection management system. We are emphasizing the data portal here, but we need to include both. I imagine art collections will be less interested in Arctos' research applications . . .
How about
This is an exciting time for natural and cultural history museums! Arctos is a both a comprehensive collection management system and a online platform serving natural history, fine arts, and cultural collections data and media to enable a network of biological and cultural knowledge. Arctos represents a community of museum professionals and enthusiasts (curators, collection managers, directors, investigators, and educators) around the world, who are committed to leading the field in the management, discoverability, and use of digital biodiversity and cultural records to address important questions. As new collections are added to Arctos, the community benefits through lower costs and higher data richness. If you are looking for a collaborative collection management system and robust research infrastructure and are interested in being part of this vibrant community, you should consider Arctos.

**Comment by campmlc** [comment]
@mkoo
