### ISSUE TITLE
Search won't display new bulkload

### ISSUE THREAD

**Issue by msbparasites** [ArctosDB/arctos#2624]
I bulkloaded 16 Host records between yesterday and today. When I search for those records, I get the interface that shows the search results, says I have 16 records, but it is not displaying anything, the rows are blank, but there are 16 rows. 14 of the records were bulkloaded and 2 were entered from data entry page. It took a very long time, longer than usual.

I have tried to download them in Firefox, Chrome and Safari
EnteredBy: sara
Date: 2020-04-27 to 2020-04-28
Image below:
![image](https://user-images.githubusercontent.com/16925986/80557866-8f910600-8995-11ea-95ef-ebca8b81c8d7.png)

Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

** Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
<img width="685" alt="Screen Shot 2020-04-28 at 8 21 41 PM" src="https://user-images.githubusercontent.com/5720791/80558101-f27e9f00-898d-11ea-832a-f5f94fdde509.png">


There are ~120K records processing, it can take a while to catch up.

**Comment by msbparasites** [comment]
Hmm, not a surprise, thanks for the screen shot, useful, I will use that now. Thanks to you all for all the effort to get this back up and running.
