### ISSUE TITLE
Bulkloader is working as fast as it can - please be patient

### ISSUE THREAD

**Issue by cefilipek** [ArctosDB/arctos#2625]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I bulkloaded all of the specimen records I lost in the Arctos crash about 2 hours ago. They are gone from the bulkloader and the parts bulkloader allowed me to load the extras, suggesting they have been loaded, but when I went to look at them I am told I only have access to 11 records. When I searched my collection I see the 11 that I didn't lose and then another 89 blank spaces on the page where the other records should go. On my phone, when not signed in, I see that I have 170 records, but when I search a record number that I uploaded today I get a blank box as the result.

**To Reproduce**
Steps to reproduce the behavior: The blank spaces only show up when I'm logged in, so it may not work.
1. Go to Search
2. Click on Collection (Select Options)
3. Scroll down to Jurica-Suchy Nature Museum and select Fossil Specimens and search

**Expected behavior**
I would expect it to show all of my specimens, not blank boxes.

**Screenshots**

Computer:
<img width="748" alt="Screen Shot 2020-04-29 at 6 49 53 PM" src="https://user-images.githubusercontent.com/56844074/80657807-4222a080-8a4a-11ea-8273-3e6116614b47.png">

<img width="1260" alt="Screen Shot 2020-04-29 at 6 19 34 PM" src="https://user-images.githubusercontent.com/56844074/80656553-14882800-8a47-11ea-9d9f-60139878e4a6.png">

Phone:
![IMG_7990](https://user-images.githubusercontent.com/56844074/80660941-dd1f7880-8a52-11ea-948b-2834adf28694.PNG)
![IMG_7989](https://user-images.githubusercontent.com/56844074/80660949-e0b2ff80-8a52-11ea-9a03-c148f1f32669.PNG)

** Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**
 - OS: IOS Catalina 10.15.3; iPhone 11
 - Browser: Chrome; Safari (phone)
 - Version: 80.0.3987.149; unknown (phone)

**Additional context**
I did upload 159 object records at once, but I feel like 2 hours is too long and I also need the records to do work tomorrow, so I wanted to ask tonight just to be safe.

**Priority**
High

**Comment by cefilipek** [comment]
I solved it. Turns out someone else had this problem and it's just because everyone is loading a bunch of records, but I didn't find the issue because I forgot to remove open from the search criteria.

**Comment by campmlc** [comment]
@dustymc 
I think this requires some additional notification to the community, given the prevalence of the problem.

**Comment by Jegelewicz** [comment]
@ewommack can we send out a notification that Arctos will be slow because so many are playing catch-up while it is "learning" to be Arctos again? @dustymc can probably help make that sound better.

**Comment by dustymc** [comment]
This has been slow for years - it's why I had to build that tool!

**Comment by campmlc** [comment]
Is there a way to put a notification box in the bulkload status or
somewhere that if records don't show up in Arctos right away, the delay may
be due to a backlog of records in the cue, please check the following . . .?

**Comment by Jegelewicz** [comment]
Yeah, but you usually never notice because it isn't used as heavily.

How about this:

If you have marked records to load but are unable to see them, please be patient. A lot of users are playing catch-up causing things to be a bit slow at the moment. It may take up to ____ hours before you are able to view the records you have marked to load.

Thank you for waiting!

**Comment by ewommack** [comment]
Maybe this would be better to put as a banner on the Arctos page or somewhere on bulkload browse and edit page?

**Comment by ewommack** [comment]
Do you still want this added to the newsletter?

If we use @Jegelewicz text do we have a number of hours that we can add to the notice or are we just going to leave it open as:
If you have marked records to load but are unable to see them, please be patient. A lot of users are playing catch-up causing things to be a bit slow at the moment. It may _take hours_ before you are able to view the records you have marked to load.

Thank you for waiting!
>

**Comment by Jegelewicz** [comment]
@dustymc might be able to supply the max hours estimate.

**Comment by campmlc** [comment]
Maybe just say give it 24 hrs and try again . . .

**Comment by cefilipek** [comment]
I marked mine to load about 23 hours ago and they haven't loaded yet, but given the number of records waiting to load overall I'm not surprised.

**Comment by dustymc** [comment]
>max hours estimate.

Nope, it's wildly variable and depends on what else is going on. Looks like most of what's left is from collection updates.

**Comment by Jegelewicz** [comment]
Just checking in here. I bulkloaded about 2K records yesterday and I'm still getting this. Paranoia is getting to me.

![image](https://user-images.githubusercontent.com/5725767/81440416-3f503b80-912d-11ea-8e87-392665c0ab9a.png)

**Comment by dustymc** [comment]
Looks like it's still processing, the licensing thing (??) has everyone updating collections which slows things down drastically, and someone's done something to several thousand otherIDs.

>Paranoia

Good!

**Comment by Jegelewicz** [comment]
OOOOPS the other IDs thing was me......

**Comment by dustymc** [comment]
Closing
