### ISSUE TITLE
Finding Media from the lost month of Arctos

### ISSUE THREAD

**Issue by cefilipek** [ArctosDB/arctos#2626]
Hi! In the email from the Arctos Working Group on Monday stated that the media we uploaded between March 15th and the crash was safe, but I am unable to find any of the images I added other than the ones attached to the 11 records that I didn't lose. I went in through the Media/Documents link under Search and entered my username (and then my student's names), is there another way to search for the media I uploaded?

![IMG_7991 copy](https://user-images.githubusercontent.com/56844074/80662188-4785e800-8a56-11ea-88d7-8e932eae0c99.jpg)
![IMG_7992 copy](https://user-images.githubusercontent.com/56844074/80662203-4eacf600-8a56-11ea-9f88-078ce87707f5.jpg)

**Comment by Jegelewicz** [comment]
Thanks!

@cefilipek you can locate yours here: https://web.corral.tacc.utexas.edu/arctos-s3/cfilipek/

You should be able to use those urls to create the appropriate relationships with a media metadata bulkload. You can find a template [here](https://arctos.database.museum/tools/BulkloadMedia.cfm).

**Comment by Jegelewicz** [comment]
BTW - I am working furiously to write good documentation for the media metadata bulkload tool. Give me this morning and I should have something you can use.

**Comment by cefilipek** [comment]
@Jegelewicz Thank you so much! And no worries, my records haven't finished loading to the forward facing part of Arctos yet anyway!

**Comment by Jegelewicz** [comment]
It's in process, but here is the [How-To](http://handbook.arctosdb.org/how_to/How-to-Bulkload-Media-Metadata.html). Also there is a video tutorial link at the bottom that may help.

**Comment by cefilipek** [comment]
Thank you!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dustymc** [comment]
We need a better index, only one how-to (that may be added to by various users), or SOMETHING to organize documentation. I just spent several minutes looking for documentation that I KNOW I wrote years ago, and never found it. Maybe someone overwrote it? Renamed it? It's just lost in the big pile of "media..." things?? Who knows....

ANYWAY, this option

<img width="944" alt="Screen Shot 2020-04-30 at 9 15 22 AM" src="https://user-images.githubusercontent.com/5720791/80733892-2e675080-8ac3-11ea-926b-f79e32387965.png">

should work for media loaded via S3, and given some sort of consistent data in the URL should be able to very quickly build a bulkloader file from directory contents.

**Comment by Jegelewicz** [comment]
WHAAAAAA?

Will incorporate.

**Comment by Jegelewicz** [comment]
So - that was the documentation before the edits I made today. It wasn't written in a way that made any sense to me! I can retrieve from history and hopefully make it so us non-programmer types can figure it out....

Yes - I am that "various user", but GitHub does retain history, so...

BTW, I see how this tool works for the specific demo you had, but I don't see how it can help with adding labels and relationships which most likely will need to be different for every file in the template. Please offer suggestions to my re-work of your first draft.

**Comment by dustymc** [comment]
Awesome, maybe I'm not going quite as crazy as I thought!

>hopefully make it so us non-programmer types can figure it out.

Yes, that would be fabulous - there's definitely a steep learning curve to about anything involving regex, this may be a particularly good example of the whole "don't ever let programmers write documentation" thing.

Ideally you'd create file names in anticipation of using this. Given

``bla_12345_Bob_ventral.jpg``

you could use the regex to filter by bla (if eg you've uploaded various types of files to a directory), pull 12345 out for a "shows cataloged_item" relationship, pull "Bob" out for a "something something agent" relationship, and pull everything after the last underbar out for a "something or another" label value.

It's probably not quite that clean with files uploaded one at a time, but if some of that exists in the file names it's recoverable by this tool. That may or may not be easier in something like Excel.

**Comment by Jegelewicz** [comment]
So, I wrote some stuff, but trying to use this hasn't proved easy for me.  I have this in the form:

![image](https://user-images.githubusercontent.com/5725767/80742548-c7ed2d00-8ad8-11ea-88e1-f68fa4b35742.png)

And when I hit build/rebuild the table, I get zilch...

You can see from what I have written that I probably don't understand what all of these fields do/mean.

**Comment by dustymc** [comment]
<img width="529" alt="Screen Shot 2020-04-30 at 3 31 15 PM" src="https://user-images.githubusercontent.com/5720791/80765348-acdde580-8af7-11ea-9498-7d8f6e394c3e.png">

I added some stuff (.jpg to not show directories and such) and then from 

 A variable [filename] is created from the string between the last slash and the last dot (eg, "bob" in "http://someserver/somedirectory/bob.jpg") of each item in the directory you specify.

You may manipulate this variable by specifying values in regexfind and (optionally) regexreplace. 

build some "between the second and third underbar" regex

``^[^_]+_[^_]+_([^_]+)_.*$``

and appended it (``\1``) to a string (``ABC:ZYX:``) to build a relationship (assuming the stuff between second and third underbars is a catnum in this case).


<img width="1357" alt="Screen Shot 2020-04-30 at 3 34 35 PM" src="https://user-images.githubusercontent.com/5720791/80765539-21188900-8af8-11ea-91f9-f9a586d29e8a.png">

I've used this quite a bit, that's all I've ever really needed to do. AFAIK nobody else has ever used it. I really have no idea if even better documentation would open doors for users, of if it'd get more use if it did more stuff, or if it's just my personal little form....

**Comment by Jegelewicz** [comment]
Thanks!
/remind me to insert this in the document tomorrow

**Comment by Jegelewicz** [comment]
@dustymc if you get a chance - can you look at the [How To](https://github.com/ArctosDB/documentation-wiki/blob/gh-pages/_how_to/How-to-Bulkload-Media-Metadata.markdown) and let me know if anything looks stupid.

**Comment by dustymc** [comment]
I might change 

This process will be facilitated by the use of filenames that include a standard use of GUIDs or barcodes. 

to "carefully constructed filenames" or something but yours is probably more clear to some users.

Everything else looks fine to me. Thanks!

**Comment by Jegelewicz** [comment]
@dustymc so, my file used in the example will not load. I am getting this:

https://arctos.database.museum/tools/BulkloadMedia.cfm?action=myStuff

![image](https://user-images.githubusercontent.com/5725767/81086540-e034c180-8eb5-11ea-83bf-7b748c0685dc.png)

Which I believe is Arctos saying that those urls don't exist? What am I doing wrong here?

**Comment by dustymc** [comment]
I'd do better with something I can copy/paste, but I believe...

<img width="203" alt="Screen Shot 2020-05-05 at 9 30 44 AM" src="https://user-images.githubusercontent.com/5720791/81090829-289eb000-8eb3-11ea-8f65-cd255fdb9614.png">
