### ISSUE TITLE
Lost month: Locality edition

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#2627]
Sorry to AWG folks for extra emails (I should've just opened an issue!)
This is what I wrote: following on the heels of assessing the data loss, Dusty shared some scripts that can be used to generate change logs for the tables that are not amenable to bulkloading specifically the locality related tables. _We discussed this at the last AWG_

[I wrote up a google doc for sharing/editing and can convert to Handbook if useful](https://docs.google.com/document/d/1b8SmGqLr3TKm3yJWJ9kbP5wJotsqDRECQ5BYdfK8xQw/edit?usp=sharing)

I also found in my emails Arctos Locality Change Notifications through April 10th (with a glitch on March 30 #2569 ) which I am going through soon to see if they are helpful in recreating updates. I have an example of them in the doc too.

**Comment by Jegelewicz** [comment]
> scripts that can be used to generate change logs for the tables that are not amenable to bulkloading specifically the locality related tables.

Just to be clear. This is meant for "from now on" so that I could have a record of my work?

> I also found in my emails Arctos Locality Change Notifications through April 10th (with a glitch on March 30 #2569 ) which I am going through soon to see if they are helpful in recreating updates. I have an example of them in the doc too.

If I can actually somehow get any of the work I did re-created and loaded in bulk this will be FABULOUS!
