### ISSUE TITLE
error feedback

### ISSUE THREAD

**Issue by diannakrejsa** [ArctosDB/arctos#2628]
Getting a weird error when I address the last error message for this bulkload file (capitalize 'myotis' in TAXON_NAME). Here is the oracle failure message
![Screen Shot 2020-05-01 at 10 43 33 AM](https://user-images.githubusercontent.com/36166607/80818756-62ad4080-8b99-11ea-89aa-a0a9f75fec2e.png)

I also attached the file before it throws this error (when _myotis_ isn't captialized; 'myotis.csv'), as well as after I capitalize it ('fails.csv')
[data entry files.zip](https://github.com/ArctosDB/arctos/files/4565053/data.entry.files.zip)

I think I've had a "cursed" file before but I can't remember how we solved it?

**Comment by dustymc** [comment]
http://handbook.arctosdb.org/documentation/understanding-errors.html#check-constraint-uamck_tbl_col_noprint-violated

```
Elapsed: 00:00:00.01
UAM@ARCTOS> select regexp_replace(COLL_OBJECT_REMARKS, '[^[:print:]]', '[X]')   from bulkloader_stage where regexp_like(COLL_OBJECT_REMARKS,'[^[:print:]]');

REGEXP_REPLACE(COLL_OBJECT_REMARKS,'[^[:PRINT:]]','[X]')
------------------------------------------------------------------------------------------------------------------------
"61" Front SD[X]71,,diannakrejsa,ASNHC:Mamm,19627,10637,ASK,0000.000,Taxidea taxus,unknown,unknown,2010-11-03,3 Nov 2010
,2010-11-03,2010-11-03,"North America, United States, South Dakota

"6" Front SD[X]93,,diannakrejsa,ASNHC:Mamm,19647,,,0000.000,Conepatus leuconotus,unknown,unknown,2019-09-22,22 Sep 2019,
2019-09-22,2019-09-22,"North America, United States, Texas, Irion County


2 rows selected.

```
