### ISSUE TITLE
Searching Projects for Award Number = %

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2631]
Not sure if this can be a thing, but it would be nice to find all projects that include an award number. Using the typical "%" to mean "anything" search results = nothing found. 

Search:
![image](https://user-images.githubusercontent.com/5725767/80983670-0db43900-8dea-11ea-9123-59134b28aa4b.png)

Results:
![image](https://user-images.githubusercontent.com/5725767/80983732-215f9f80-8dea-11ea-8975-466d38c205e2.png)

**Comment by dustymc** [comment]
Technically, no problem.

Socially, that'd reveal that we're pretty bad at recording this information.....

**Comment by Jegelewicz** [comment]
Which might shame people into doing it?

**Comment by Jegelewicz** [comment]
Discussed today in AWG Issues meeting - we need the % search functionality. Also, thinking that finding all with "NULL" might help get some of that filled in?

**Comment by dustymc** [comment]
Let's merge this into https://github.com/ArctosDB/arctos/issues/3398 to get the structure, then https://github.com/ArctosDB/arctos/issues/3468 for the functionality.
