### ISSUE TITLE
Other ID Relationships for cultural collections

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2633]
We would like to propose adding these as well: 

Value 4
same series as

Definition 4
A conceptual grouping of visual arts works, literary works, or performance art created in succession by the same author, artist, or studio and intended by the creator(s) to be seen together or in succession as a cycle of works. Works in a series typically share the same or related subjects, the same or similar media, or other characteristics, but their defining characteristic is that they were intended to be conceptually related as a series. Individual items in a series may be cataloged separately and linked to the series. http://vocab.getty.edu/page/aat/300027349

Context 4
Useful in linking together works from the same series.

Value 5
same edition as

Definition 5
Groups of multiples of one work issued together, such as of a book, print, photograph, or cast sculpture. All copies of a book, print, etc., produced from substantially the same master, and issued at one time are part of the same edition. http://vocab.getty.edu/page/aat/300121294

Context 5
Useful in linking together works from the same edition. We have a few examples of prints that are from the same edition.

_Originally posted by @krgomez in https://github.com/ArctosDB/arctos/issues/2440#issuecomment-604663419_

**Comment by krgomez** [comment]
Are there any new thoughts on whether these new relationships would be okay to add?

**Comment by AJLinn** [comment]
If it's a standard relationship for art collections it seems fine to me.

**Comment by campmlc** [comment]
This looks OK to me.

**Comment by Jegelewicz** [comment]
added

**Comment by krgomez** [comment]
Thanks!
