### ISSUE TITLE
Code Table Admins - Review Membership and Recruit New Admins

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2634]
See https://github.com/ArctosDB/arctos/issues/2326#issuecomment-614928648

This issue will track a review of current membership in the Code Table Admin Committee and review membership for gaps in collection coverage/expertise.

**Comment by Jegelewicz** [comment]
People with access to manage code tables include:

Anna Chinn
Angela Linn
Aren Gundersen
Mariel Campbell
Carla Cicero
Dusty McDonald
Emily Braker
Kyndall Hildebrandt
Teresa Mayfield-Meyer
Jon Dunnum
Katherine Anderson - no longer an Arctos Operator, but account is locked.
Lam
Michelle Koo

**Comment by campmlc** [comment]
We had the suggestion at one point to provide code table access to only
those operators who are serving on the code table committee. This was
discussed at last issues meeting?

**Comment by Jegelewicz** [comment]
I am trying to work on that!

**Comment by Jegelewicz** [comment]
We could use representation on the committee from people who manage the following collections types either because there is no representation at all or current members with those collections lack discipline expertise:

Algae
Archaelology
Art
Paleo 
Geology
Entomology 
Environmental Samples
Herbaria
Invertebrates
Zooplankton

Need volunteers or names of those who might be able to help.

**Comment by Jegelewicz** [comment]
A few members with code table access do not participate in the AWG much less the Code Table Admin Committee. Suggest we email them the following:

As a Code Table Administrator, you currently have access to edit code tables in Arctos. Code Table Access is considered an essential community activity that comes with responsibility. Participation in the Code Table Administrator Committee, which meets once per month and assisting with code table related GitHub requests are part of your responsibility as a Code Table Admin. If you are willing to participate in Arctos Community Governance at the level required, please respond affirmatively and you will continue to be a Code Table Administrator. If you are not willing or able to participate at the required level, please respond negatively and your access to edit Arctos code tables will be revoked, relieving you of those responsibilities.

Thank you!

**Comment by dustymc** [comment]
Suggest adding a "or if you know someone who will then send them our way..." clause somewhere in there.

**Comment by campmlc** [comment]
I support this.

**Comment by Jegelewicz** [comment]
> Suggest adding a "or if you know someone who will then send them our way..." clause somewhere in there.

As a Code Table Administrator, you currently have access to edit code tables in Arctos. Code Table Access is considered an essential community activity that comes with responsibility. Participation in the Code Table Administrator Committee, which meets once per month and assisting with code table related GitHub requests are part of your responsibility as a Code Table Admin. If you are willing to participate in Arctos Community Governance at the level required, please respond affirmatively and you will continue to be a Code Table Administrator. If you are not willing or able to participate at the required level, please respond negatively and your access to edit Arctos code tables will be revoked, relieving you of those responsibilities. If you choose that later, but know someone else in the community who could provide similar discipline or institutional expertise, please pass along their name to the Code Table Administrator Committee.

Thank you!

**Comment by anna-chinn** [comment]
Sounds good to me.

**Comment by Jegelewicz** [comment]
@ccicero @campmlc @ebraker and myself attended today's committee meeting.

Aren, Katherine and Jon code table access should be revoked per committee agreement.
@dustymc who can do that?

Arctos Code Table Admins Group updated to remove them.

Need to create better on-boarding to help new members get integrated into the community and introduced to how we operate.

Create new issue to add at least one GitHub username to Manage Collection page (required) so that at least one person from each collection is on GitHub. See #2698 

Add brief Code Table Request workflow to documentation - see http://handbook.arctosdb.org/how_to/How-To-Request-A-Code-Table-Change.html

We will attempt to get @Nicole-Ridgwell-NMMNHS  and @marecaguthrie  or @krgomez  to join the team to round out discipline specific knowledge (paleo and art).

**Comment by Jegelewicz** [comment]
/remind me to send an invite to the next meeting and add the new recruits on June 12, 2020.

**Comment by dustymc** [comment]
>who can do that?

I think that's just manage_collection now. You need a role to grant it, but I believe not to revoke.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I'll look for an invitation!

**Comment by Jegelewicz** [comment]
> KatherineLAnderson no longer works for UAM ES.

Yep - this is a concrete example for https://github.com/ArctosDB/arctos/issues/3993

**Comment by Jegelewicz** [comment]
I'm just gonna trust that Aren & Jon are good people - closing
