### ISSUE TITLE
Wikidata entry in Agent record

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2637]
Can we make the Wikidata field work more like an other identifier?

So, for Ecological Society of America the Wikidata entry would be "Q1282045" and Arctos would know that to form the link it should add "https://www.wikidata.org/wiki/" to get https://www.wikidata.org/wiki/Q1282045?

Same goes for ORCiD

**Comment by dustymc** [comment]
Yes and no - addresses don't have the structure to support that so it would happen in the interface (which would make sharing those data slightly more cryptic), or we'd need major surgery somewhere.

Mostly I just figured it would be a lot easier to copy a URL instead of trying to pick it apart.

**Comment by Jegelewicz** [comment]
I get that - on the other hand, that isn't how everyone else treats these. Just take a look at the list of other identifiers for [ESA in Wikidata](https://www.wikidata.org/wiki/Q1282045).

![image](https://user-images.githubusercontent.com/5725767/81012363-a791db00-8e16-11ea-91a3-2d3fc86cd273.png)

**Comment by Jegelewicz** [comment]
Here is [Spencer Lucas's Wikidata](https://www.wikidata.org/wiki/Q3820304)

![image](https://user-images.githubusercontent.com/5725767/81239076-072bea00-8fc1-11ea-87a0-d2f6bb519cdf.png)

What better way to know that this is the Spencer G. Lucas you are looking for?
