### ISSUE TITLE
Can't log in to Test Arctos

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/arctos#2639]
** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **

** Outages should be reported to the contacts listed at https://arctosdb.org/arctos-down/ **

** Arctos Documentation is http://handbook.arctosdb.org/ **

** Learn more about Arctos at https://arctosdb.org/ **

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **

**Comment by campmlc** [comment]
@mbprondzinski  Dusty had to load an updated version, so everyone will need to reset your password using the Operator login link at the top of the page.  Let me know if that works!

**Comment by mbprondzinski** [comment]
Yup, that worked.  Thanks!
