### ISSUE TITLE
GRIIS to integrate with Taxonomy?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2640]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
People want to find "invasive species".

**Describe what you're trying to accomplish** 
Can we facilitate that kind of search in Arctos?

**Describe the solution you'd like**
The [Global Register of Introduced and Invasive Species (GRIIS)](http://www.griis.org/) presents validated and verified checklists (inventories) of introduced (alien) and invasive alien species at the country, territory, and associated island level.

**Describe alternatives you've considered**
none - just saw this and wanted to pass it on. See [GBIF usage on USA page](https://www.gbif.org/dataset/6b64ef7e-82f7-47a3-8ddb-ec6794ea07d6).

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
Someone should encourage them to share their data with globalnames.
