### ISSUE TITLE
Taxonomy Adds/Edits SLOW

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2641]
I have added or edited about 6 taxa since Arctos was brought back from the dead. It takes approximately 5 minutes for the new classification/edits to save each time. Just wanted to make everyone aware.

**Comment by anna-chinn** [comment]
I'm experiencing the same thing. Adding taxa (by cloning or otherwise) works fine for me, but I've been waiting ~10 mins for a classification change to save and Arctos is still spinning its wheels.

**Comment by Jegelewicz** [comment]
I just walk off and do something else - no idea how long it actually takes.....

**Comment by Jegelewicz** [comment]
But it does eventually work.

**Comment by sharpphyl** [comment]
Yes, but I have several hundred taxon names that need editing (to add aphiaID) and each one takes several minutes to load the changes.  Is abandoning the project until after Postgres the only solution?

**Comment by Jegelewicz** [comment]
> but I have several hundred taxon names that need editing (to add aphiaID)

@sharpphyl make a spreadsheet that has the taxon name, the aphiaID, and see if @dustymc can SQL them in for you.

**Comment by dustymc** [comment]
We're scheduled to move in ~a week. Can this wait?

**Comment by sharpphyl** [comment]
Sure.  I have plenty of other things to do.

**Comment by sharpphyl** [comment]
Working ok now, so I'm going to close this issue unless someone else is having problems.
