### ISSUE TITLE
Accession - treat {guid_prefix}:{accn_number} as "the number" everywhere

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2647]
Makes sense, but what format do I use to search for an exact accession? If I want NMMNH:Paleo accession number 9999 what would I put in the search? I already tried NMMNH:Paleo:9999 and got no results when I know there should be some.

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/PG-migration-testing/issues/136#issuecomment-624887202_

**Comment by Jegelewicz** [comment]
> That's not new, but it's probably issue-worthy. I'd certainly be up for treating {guid_prefix}:{accn_number} as "the number" everywhere.
> 
>     select NMMNH:Paleo in the collection
>

**Comment by Jegelewicz** [comment]
Maybe applies to Loans too?

**Comment by campmlc** [comment]
Coming in late to this . . . what about the suffix? Our accessions are
2020.001.Mamm format

**Comment by dustymc** [comment]
There is no suffix, that's just formatting of accn.accn_number.

**Comment by campmlc** [comment]
This is how our accessions are numbered and tracked.  We do not use the  prefix in our internal documents.
2018.001.Bird

**Comment by dustymc** [comment]
>We do not use the prefix in our internal documents.

I'm not 100% sure that's a deal-breaker here - those are designed and printed by you, not "part of Arctos." Getting used to seeing MSB:Mamm:whatever in some places and just "whatever" in others might not be something you're willing to deal with; I can implement if you are, but I can't make that decision.

It should be noted that this is only a problem for users with access to lots of collections. If you only have MSB:Mamm access then "whatever" as an accn number isn't ambiguous even if 50 other collections use it.

**Comment by campmlc** [comment]
Yes, but absolutely critical for users who do have access to multiple
collections, e.g. Genomic Resources. I have to be able to distinguish
2020.001.Bird from 2020.001.Mamm.
Can the search tool accept either format? E.g MSB:Mamm:2020.001.Mamm or
2020.001.Mamm, and then it would only display results for the latter for
the institutions the user has access to?

**Comment by dustymc** [comment]
>access to multiple collections, e.g. Genomic Resources.

MVZ has an accession system which seems to work well in that environment.

>accept either format

It could, that's a little black-boxey for my taste, I think I'd rather add a new "field" if we must and absolutely can't just standardize.

**Comment by Jegelewicz** [comment]
> Coming in late to this . . . what about the suffix? Our accessions are
> 2020.001.Mamm format

I don't get the problem. These accessions will show up as MSB:Mamm:2020.001.Mamm

While the 5 different 9999 accessions I have access to will show up as

NMMNH:Bird:9999
NMMNH:Ento:9999
NMMNH:Inv:9999
NMMNH:Mamm:9999
NMMNH:Paleo:9999

Alternatively - REMOVE Accession from the main search page. I can get the results I need by searching in Transactions and if the results in the main search are going to be different because I cannot get the appropriate parameters, let's take it out.

![image](https://user-images.githubusercontent.com/5725767/81312549-ff615980-9043-11ea-9d78-c12b531e0b95.png)

**Comment by campmlc** [comment]
MSB isn't going to change their accession numbering system. We've also
advised other incoming collections to use the same system. An ideal search
interface would allow for flexibility here since there has been no
standardized format for accessions in Arctos.

**Comment by Jegelewicz** [comment]
I don't get it - I am not asking anyone to change their numbers!

All I want is to be able to search Accession 9999 only for NMMNH:Paleo - which I CAN do in Find Accession, but CANNOT do from the main search page.

**Comment by dustymc** [comment]
Please resolve or close.

**Comment by Jegelewicz** [comment]
> All I want is to be able to search Accession 9999 only for NMMNH:Paleo

Select Collection NMMNH:Paleo and Accession 9999

just in case anyone wants to know how to do this. It takes forever though.
