### ISSUE TITLE
Add Wikidata identifier to classification metadata

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2648]
We can connect taxa with Wikidata using the Wikidata identifier. See https://arctos.database.museum/name/Duchesneodus where I have placed the link in a remark,

It would be really nice to just put the identifier "Q5311279" and have Arctos understand that the rest of the link is https://www.wikidata.org/wiki/

If we want to start linking up with the world, I think we should be doing more of this. We should also have unique identifiers for our taxa that we can match up elsewhere. Note all of the identifiers in the [Duchesneodus Wikidata item](https://www.wikidata.org/wiki/Q5311279).

We don't have to manage all of these identifiers within Arctos - all we need is the link to Wikidata - let the community manage it there.

This also goes for agents - see #2637 and could be applied to publications here is the [paper describing Duchesneodus](https://www.wikidata.org/wiki/Q93454819)

**Comment by campmlc** [comment]
Great idea. Workable?

**Comment by dustymc** [comment]
>just put the identifier "Q5311279" 

I don't fully disagree, the GUID is easier for immediate implementation and might be more "portable," they're predictable so it's easy to go back and forth.

>unique identifiers for our taxa 

We do. https://arctos.database.museum/name/Duchesneodus is one.

>also goes for agents 

Yep cultural collections want some of the stuff in wikidata, getting the community of wikidata's users managing Arctos stuff seems pretty slick to me!

>Workable

Sure, wikidata has a (weird) API, we can talk to them.

**Comment by Jegelewicz** [comment]
Maybe add to the name instead? This is really an alias for the name not the classification.

**Comment by dustymc** [comment]
>name not the classification.

<img width="282" alt="Screen Shot 2021-02-17 at 1 47 41 PM" src="https://user-images.githubusercontent.com/5720791/108272165-bbe56100-7126-11eb-8f21-a6e33e0d53e3.png">


strongly suggests it isn't.

**Comment by dustymc** [comment]
https://www.wikidata.org/wiki/Q17405678
https://www.wikidata.org/wiki/Q2599422

does more than suggest

**Comment by Jegelewicz** [comment]
But doesn't this mean it's the name?
![image](https://user-images.githubusercontent.com/5725767/108273970-898d3100-7131-11eb-83b6-878c22dc24b1.png)

The classification would be all of the associated names (and there could easily be two parent taxa associated).

I mean I get that the definition places it in the the classification (or multiple classifications) and means that "this isn't Duchesneodus the punk band, but still, the entire classification isn't here (and for some terms next to none of it may be).

However, this is cool - https://www.pronouncekiwi.com/Duchesneodus

**Comment by dustymc** [comment]
>The classification would be....

... whatever someone feels like including in Arctos. The model is designed so that I **can't** care what you think "the classification" is. If you consider the plant and the bug two THINGS, great. If you want to include information about both of those and the band too in one object, then rock on. It'll all fit in Arctos.

What doesn't fit is "this name means THAT and nothing else," which is what linking the wikiID to the name would imply.

**Comment by Jegelewicz** [comment]
> "this name means THAT and nothing else,"

But that is exactly what Wikidata is meant to do.

> The Wikidata repository consists mainly of items, each one having a label, a description and any number of aliases. Items are uniquely identified by a Q followed by a number, such as Douglas Adams (Q42).

Look at a search for Cars. Each has a simple definition and none are combinations of things. https://www.wikidata.org/w/index.php?search=Cars&search=Cars&title=Special%3ASearch&go=Go&ns0=1&ns120=1

**Comment by dustymc** [comment]
Wikidata doesn't have anything equivalent to our "name" - it's all "classifications." They might have a bajillion "Douglas Adams" but only one of them's Q42, and they've got nothing to do with each other besides sharing a string (until someone adds a relationship, anyway). If that was Arctos taxonomy we'd have exactly one "Douglas Adams" (which could therefore also serve as an identifier) with a bajillion classifications (one or more of which might carry the identifier "Q42").

**Comment by Jegelewicz** [comment]
OK, so we are back to adding it to the classification.

**Comment by Jegelewicz** [comment]
Reviving this as part of the TPT taxonomy management. To make it easy:

new taxonomy term = "Wikidata identifier"

defintion = URL to the Wikidata identifier associated with this classification.

I would really rather just use the Wikidata Q number and have Arctos understand the rest of the url, but if that is going to take too long, this will suffice.

**Comment by campmlc** [comment]
I support this.

**Comment by Jegelewicz** [comment]
I'm closing this because I don't think it can functionally DO anything.
