### ISSUE TITLE
Add Wikidata identifier to publication (use like Crossref?)

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2649]
Wikidata identifiers can be applied to publications here is the [paper describing Duchesneodus](https://www.wikidata.org/wiki/Q93454819).

Could we use Wikidata the same way we use CrossRef to pull in publication info?

![image](https://user-images.githubusercontent.com/5725767/81241266-0e55f680-8fc7-11ea-8c7e-6bbc6d025520.png)

**Comment by dustymc** [comment]
If there's a shared identifier and an API, the answer is probably some flavor of "yes."

Maybe "yes, but the stuff that comes through the API isn't very useful. (IDK if it is or not here.)

Definitely "yes, but we need to do some internal shuffling" in this case.

Still yes(ish)....

**Comment by dustymc** [comment]
Suggest Media; I don't think WD can **do** much for us, certainly nothing like crossref can, doesn't seem like this needs a structural solution.
