### ISSUE TITLE
login (behind the scenes)

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#2651]
It's an evolved mess, things like https://github.com/ArctosDB/PG-migration-testing/issues/137 are possible. Move to an intelligently-designed API, make sure it's transactional that that everything can talk to it.

**Comment by dustymc** [comment]
also https://github.com/ArctosDB/PG_DDL/issues/85

>postgres has a shady security model; there's no way to limit login attempts, which makes us susceptible to brute force attacks. Need to find a way to fake it.

**Comment by dustymc** [comment]
This is complicated by portals: https://github.com/ArctosDB/arctos/issues/2683

**Comment by dustymc** [comment]
This is testable in test; please attempt to break it. Essentially everything is affected

* public search
* logging in as Operator
* logging in as public user
* logging out as any of the above
* going from any of those states to any other
* everything involving "portals" from all states

and most importantly, that thing I haven't found.

**Comment by dustymc** [comment]
Upping priority; this needs tested.

**Comment by campmlc** [comment]
After we bounce?

**Comment by campmlc** [comment]
Oh, I see it's in test. What are we looking for?

**Comment by dustymc** [comment]
>What are we looking for?

Anything conceivably related to sessions/users/login that doesn't work.

**Comment by Jegelewicz** [comment]
/remind me to do this tomorrow morning

**Comment by Jegelewicz** [comment]
Entered the http://test.arctos.database.museum/ in Firefox and browser spun for a good 20 seconds before the page finally opened.

**Comment by campmlc** [comment]
Got right in as public, but then had to reset password, then change
password, and then when acceptable password was entered, got this.
[image: Screenshot 2020-06-24 08.56.53.png]

**Comment by mkoo** [comment]
I logged in with my old test password and encountered no errors-- logged
in, logged out as mkoo was fine

Created new user as a public account and was fine (kootest). Tried to reset
my password and got an error:


Catch
additional
Struct (ordered)
Detail
string
ErrNumber
number 0
ErrorCode
string 0
Extended_Info
string
ExtendedInfo
string
Message
string No matching function [INITSESSION] found
StackTrace
string lucee.runtime.exp.ExpressionException: No matching function
[INITSESSION] found at
lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:785) at
lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:785)
at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1710) at
changepassword_cfm$cf.call(/ChangePassword.cfm:175) at
lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:945) at
lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:837) at
lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:216)
at
lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:42)
at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2416) at
lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2406) at
lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2381) at
lucee.runtime.engine.Request.exe(Request.java:43) at
lucee.runtime.engine.CFMLEngineImpl._service(CFMLEngineImpl.java:1127) at
lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:1073)
at
lucee.loader.engine.CFMLEngineWrapper.serviceCFML(CFMLEngineWrapper.java:97)
at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:51) at
javax.servlet.http.HttpServlet.service(HttpServlet.java:741) at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at
org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
at
org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
at
org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
at
org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
at
org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
at
org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
at
org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
at
org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
at
org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
at
org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
at
org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
at
org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
at
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at
org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.base/java.lang.Thread.run(Thread.java:834)
TagContext
Array
1
Struct
codePrintHTML
string 173: &lt;cfset session.force_password_change = &quot;&quot;&gt;<br>
174: <br> <b>175: &lt;cfset
initSession('#session.username#','#newpassword#')&gt;</b><br> 176:
&lt;cfinvoke returnVariable=&quot;l&quot;
component=&quot;component.functions&quot;
method=&quot;initUserSession&quot;&gt;<br> 177: &lt;cfinvokeargument
name=&quot;username&quot; value=&quot;'#session.username#&quot;&gt;<br>
codePrintPlain
string 173: <cfset session.force_password_change = ""> 174: 175: <cfset
initSession('#session.username#','#newpassword#')> 176: <cfinvoke
returnVariable="l" component="component.functions"
method="initUserSession"> 177: <cfinvokeargument name="username"
value="'#session.username#">
column
number 0
id
string ??
line
number 175
Raw_Trace
string changepassword_cfm$cf.call(/ChangePassword.cfm:175)
template
string /usr/local/webroot/ChangePassword.cfm
type
string cfml
type
string expression
*An error occurred while processing this page!*
Check the Arctos Handbook
<http://handbook.arctosdb.org/documentation/understanding-errors.html> for
more information on errors.

This message has been logged as 654200FB-03B7-4B98-9EDC0AB0563B1CC6
Please contact
us
<https://github.com/ArctosDB/arctos/issues/new?assignees=&labels=contact&template=contact-arctos.md&title=error
feedback> with any information that might help us to resolve this problem.
For best results, include the error and a detail description of how it came
to occur in the Issue.

**Comment by mkoo** [comment]
hmm, strangely I logged in again and the new password worked! (even though
I got the above error when trying to change it)

**Comment by dustymc** [comment]
thanks! - try that again

**Comment by mkoo** [comment]
New user Koo TEST can change password, update profile, recover password,
and log in and out without errors!

**Comment by campmlc** [comment]
I successfully logged in.
Will continue testing.
General observations so far:
In transactions, Find Loan, the dropdown is really tiny and impossible to
use to select one option. Very difficult to scroll through.
Add items is horrid, as described elsewhere. Could be immediately made
better by turning the box horizontally and allowing collections to
customize what they see.

**Comment by dustymc** [comment]
@campmlc the comments need to be in their own issues, they will be lost here.

**Comment by campmlc** [comment]
In test, tried to go to bulkload data -> browse and edit-> data tables and
got this:
[image: Screenshot 2020-06-24 12.24.58.png]

**Comment by campmlc** [comment]
In Object Tracking, edit container, move all children to of this container
to barcode, got this:
[image: Screenshot 2020-06-24 12.28.15.png]

**Comment by campmlc** [comment]
When editing a bulkloaded record without using tables, which I can't get to
because of above, when I click save in the individual data entry form and
go back to tables, I don't see anything in the results, have to refilter to
find the records I was just editing. It would be helpful to go back to the
table of results I was just working in.
