### ISSUE TITLE
Bulk Edit Container Tool

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2652]
@campmlc posted in migration repo:

This tool needs the following updates:
1) the build csv link is deprecated. Can we remove it?
2) Members is mispelled.
3) Are the last 4 column headers related to creating positions within a container being edited? If so, we need to add some explanation of this. 
4) We need a documentation link. I can work on updating documentation for this, if we can add a link.

Update the following:
NUMBER_ROWS | All-or-none position group memeber. "0" (no quotes) will update to NULL; blank will be ignored (no updates).
-- | --
NUMBER_COLUMNS | All-or-none position group memeber. "0" (no quotes) will update to NULL; blank will be ignored (no updates).
ORIENTATION | All-or-none position group memeber. "0" (no quotes) will update to NULL; blank will be ignored (no updates).
POSITIONS_HOLD_CONTAINER_TYPE | All-or-none position group memeber. "0" (no quotes) will update to NULL; blank will be ignored (no updates). "horizontal" or "vertical"

TO:

POSITION_NUMBER_ROWS | All-or-none position group member. "0" (no quotes) will update to NULL; blank will be ignored (no updates). Use this field to create positions within a container. Numeric value.
POSITION_NUMBER_COLUMNS | All-or-none position group member. "0" (no quotes) will update to NULL; blank will be ignored (no updates). Use this field to create positions within a container. Numeric value.
POSITION_ORIENTATION | All-or-none position group member. "0" (no quotes) will update to NULL; blank will be ignored (no updates). Use this field to create positions within a container. Accepted values are "horizontal" or "vertical".
POSITIONS_HOLD_CONTAINER_TYPE | All-or-none position group member. "0" (no quotes) will update to NULL; blank will be ignored (no updates).  Use this field to create positions within a container. Accepted values are code-table controlled: See [CTCONTAINER_TYPE](https://arctos.database.museum/info/ctDocumentation.cfm?table=CTCONTAINER_TYPE)

**Comment by dustymc** [comment]
This should be moved into the Component Loaders ecosystem.

**Comment by dustymc** [comment]
Include: https://github.com/ArctosDB/arctos/issues/3261

**Comment by dustymc** [comment]
New version in next release, could use testing
