### ISSUE TITLE
Attribute color - code table to control values?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2655]
Initiated by #2564 

Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Goal**
Some have suggested the use of a code table to control values for the "color" object attribute. 

**Context**
Might be a good thing for those who can use it, but there are differing schemes. However, the free text we use now is possibly not the best option for discoverability.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=CTATTRIBUTE_CODE_TABLES

**Value**
not sure - we need a broad discussion of how color is used to determine the best method(s).

**Definition**
Clear, complete, non-collection-type-specific definition of the new value.

**Collection type**
Probably useful for all collection types, also might be related only to specific parts.

**Attribute data type**
categorical

**Attribute value**
This is what art people use: https://www.pantone.com/color-finder

> link is just RGB values - that's pretty standard way to define colors, although constraining it to something like a code table would take some head-scratching. I think spectrophotometers report something that can be expressed as number+units, so that should be pretty easy.

Mammalogists have used the [Munsell system](https://en.wikipedia.org/wiki/Munsell_color_system) in publications

**Attribute units**
N/A

**Priority**
Please assign a priority-label.

**Comment by campmlc** [comment]
Possible to have different code tables for different collection types? E.g. birds uses source A; mammals uses source B?Or allow each collection to choose which code table?

**Comment by dustymc** [comment]
I don't think that's functionally different than free-text; it's all mixed up and so nobody can search it. (And Arctos very purposefully cannot support that arrangement.)

color (method1) [datatype-stuff]
color (method2) [datatype-stuff]
color (method2) [datatype-stuff]

is certainly possible. We've done roughly that with age, age class, numeric age.

**Comment by ewommack** [comment]
Color research changes so quickly, I think if you control the vocabulary you are going to limit the number of people who actually use the attribute to only those who use that rating/binning/identification system.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Once we start importing our minerals, color will be a critical attribute. I think having a controlled vocabulary for this field would be really great for discoverability. On the other hand, having the flexibility of a free text field is also important. For us, if the vocabulary is controlled, I would just put the more nuanced description in remarks, but I can see how that might not work for everyone. Would it be possible to have two attributes? Color - simple and Color - free text?

**Comment by Jegelewicz** [comment]
Honestly, I could see how we might end up with:

color, pantone
color, Munsell
etc.

**Comment by dustymc** [comment]
>two attributes

Yes see https://github.com/ArctosDB/arctos/issues/2655#issuecomment-625886447 and http://arctos.database.museum/info/ctDocumentation.cfm?table=CTATTRIBUTE_TYPE&field=age, http://arctos.database.museum/info/ctDocumentation.cfm?table=CTATTRIBUTE_TYPE&field=age%20class, http://arctos.database.museum/info/ctDocumentation.cfm?table=CTATTRIBUTE_TYPE&field=numeric%20age

**Comment by dustymc** [comment]
Tabling for apparent lack of interest.
