### ISSUE TITLE
agent address maps

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#2657]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
We have mostly-invisible data that should be exposed.

** Describe what you're trying to accomplish** 
Visually verify agent addresses

**Describe the solution you'd like**
Map addresses

**Describe alternatives you've considered**

**Additional context**
Addresses get georeferenced (used to map loans), adding a map to the agent page would provide handy verification

**Priority**
probably low

**Comment by dustymc** [comment]
See https://github.com/ArctosDB/internal/issues/44 - the coordinate data, especially outside the US, is likely to get worse, having a way to see (and perhaps correct) it would be useful, this should be re-prioritized.

**Comment by Jegelewicz** [comment]
> We have mostly-invisible data that should be exposed.

I kinda disagree with this. Have we asked these agents if they WANT us to expose their personal information?

**Comment by dustymc** [comment]
"expose" != public. They asked for a loan (or something), I don't think it's unreasonable to see the destination on a map before you ship stuff to the wrong place.

The only address types exposed publicly are ``('url','ORCID','Wikidata')`` and I see no reason we'd ever change that.

**Comment by campmlc** [comment]
So you are saying this would be internal to Arctos operators who have
access to the agent page.
We do need to be considering EU privacy laws at some point. I believe GBIF
deals with this by requiring users acknowledge some popup?

**Comment by dustymc** [comment]
> internal to Arctos operators 

Yes

>access to the agent page.

No

>EU privacy laws 

Way above my pay grade, but I suppose an EU collection would have to provide whatever we need to figure out what that means before we could seriously consider them joining Arctos.

**Comment by campmlc** [comment]
I'd like to request upping priority. We need this for our dashboard to document global usage and relevance.

**Comment by cjconroy** [comment]
I queried for 63 loans, but only 18 plotted. Some are international, but is there some reason why some north american ones might not work? Does it internally produce a list of "can not map?"

**Comment by dustymc** [comment]
I've done what I can, which isn't much, calling this next release. Addresses with coordinates are now mappable, but with a click. Coordinates are exposed and now editable, the autogeneration now only tries for blank.

The census.gov webservice is still the best tool I've found for this, and it's pretty horrible given what seems to be a typical shipping address. (Not something the census bureau cares about, I suppose.) I don't think I can do much more without access to better tools.

**Comment by ebraker** [comment]
@dustymc does the loan mapping tool exist? I don't see it on a loan search.

**Comment by dustymc** [comment]
Neither data nor tools exist, see https://github.com/ArctosDB/arctos/issues/7410 for a sad reality issue and https://github.com/ArctosDB/BackBurner/issues/4 for something more hopeful which might turn in to a request.
