### ISSUE TITLE
Whitespace in Specific locality

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2661]
Data audit discovered that SPEC_LOCALITY contains

> [1 whitespace]

@dustymc says:

> Issue - I could TRIM() stuff, I generally hate it when things do that for me (remember Clippy?), but maybe we can find a non-evil approach.

**Comment by Jegelewicz** [comment]
Along this vein:

642 localities are .
2 localities are ?, ?
1 locality is ????

@dustymc says:

> I doubt I'll catch that; seems like a documentation/training issue rather than technical, but I could try.

I wonder if we can send out notifications for stuff like this?

Getting rid of whitespace might help with:

> very large proportion of pseudo-replicates,

10 mi S Delta Junction
 10 mi S Delta Junction
Adam Hoague Pond, Mogallon Mountains
 Adam Hoague Pond, Mogollon Mountains

**Comment by mkoo** [comment]
oh goad, please yes on the pseudo-replicate rooting out!

and a flag for ```?``` in localities... we can do better!

**Comment by campmlc** [comment]
Agree.
Also agree: I wonder if we can send out notifications for stuff like this?

**Comment by dustymc** [comment]
>notifications

I can, but I don't think they'll be effective.

I still hate black-boxing input.

I could reject data which doesn't meet some standard (eg ``spec_locality!=trim(spec_locality)``) and could live with that approach.

>whitespace

```
create table temp_funky_locality as SELECT spec_locality,trim(regexp_replace(spec_locality, '\s+', ' ', 'g')) as nsl  FROM locality where spec_locality!=trim(regexp_replace(spec_locality, '\s+', ' ', 'g')) order by nsl;

SELECT 9735

arctosprod@arctos>> select count(distinct(nsl)) from temp_funky_locality;
 count 
-------
  8137

```

[temp_funky_locality.csv.zip](https://github.com/ArctosDB/arctos/files/4610803/temp_funky_locality.csv.zip)

>?

```

arctosprod@arctos>> create table temp_funky_locality_wut as select spec_locality from locality where spec_locality like '%?%';
SELECT 1500
```
[temp_funky_locality_wut.csv.zip](https://github.com/ArctosDB/arctos/files/4610817/temp_funky_locality_wut.csv.zip)

**Comment by Jegelewicz** [comment]
> I could reject data which doesn't meet some standard (eg spec_locality!=trim(spec_locality)) and could live with that approach.

That's good enough for me.

**Comment by campmlc** [comment]
yes

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/2678
