### ISSUE TITLE
Verbatim, began and ended dates in data download

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2663]
Recent download and audit of data commented on Verbatim Locality:

> VERBATIM_DATE contains a variety of date formats, making the dates unusable without cleaning and normalising.

@dustymc suggests:

> Maybe we should pair up verbatim/began/ended in downloads or something? (Would make a very nice JSON object...) Issue.

I think that began and ended date should be part of the "default" download columns because as Bob pointed out, verbatim date (which is the only date in the default right now) is nor very useful as it contains stuff like this:

10 Jan unknown yr
10 Spet. 1997
12 August � 8 September 2014
12 Dec
09 Jan 2025
020830
10 Dec '52
10 enero 2009
10-IX-88
10 XI 50
10JUN2010
10 to 20 Oct 2006

**Comment by dustymc** [comment]
No apparent interest, tabling.
