### ISSUE TITLE
Part Bulkload slow - more paranoia

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2666]
I used the part bulkload tool to load 2,162 parts this morning. It has been doing this for a couple of hours now.

![image](https://user-images.githubusercontent.com/5725767/81603980-72dcd100-938c-11ea-8ed1-840de2d1319d.png)

I haven't tried refreshing the page or exiting and coming back to manage my stuff 'cause I'm paranoid.

@dustymc

**Comment by dustymc** [comment]
Refresh - that's almost certainly your browser wandering off and forgetting to come back.

**Comment by Jegelewicz** [comment]
It's actually still working most say loaded, but there are still some "valid" lines....

**Comment by Jegelewicz** [comment]
@dustymc This stuff still hasn't finished. In fact, nothing has loaded since I last checked two hours ago.

**Comment by dustymc** [comment]
Did you reload?

**Comment by Jegelewicz** [comment]
I was logged out and logged back in. I have left the page and done other stuff - it still seems stuck.

**Comment by dustymc** [comment]
I still can't tell if you reloaded or not; if you didn't you should.

**Comment by Jegelewicz** [comment]
What do you mean by reload? Part of the 2,162 have loaded and part have not.  "Load more records" only offers me the option to load another csv. If I delete everything, I won't know what has already loaded and what hasn't.

![image](https://user-images.githubusercontent.com/5725767/81706590-5a70c300-942d-11ea-8397-704426da035c.png)


I'm not sure what to do at this point.

**Comment by dustymc** [comment]
Oh. 

Can I steal your data? I need to see it. Loaded=happy and can be deleted; valid=stuck, right?

**Comment by Jegelewicz** [comment]
Yes - as far as I know - I haven't checked any of the records, but that is my assumption.

**Comment by dustymc** [comment]
IDK if you make me paranoid or my crappy form makes me paranoid, but I know what you're talking about now.

```
 create table temp_temp_ter_parts as select * from cf_temp_parts where username='JEGELEWICZ';
update  cf_temp_parts set username='DLM' where username='JEGELEWICZ';
-- yup, can't see how to do this in the UI
-- checked a couple, looks like they're doing what they say they did
delete from cf_temp_parts where username='DLM' and status='loaded';
```
Spiffy, all done. See in Specimen Results 

This should be clarified in https://github.com/ArctosDB/arctos/issues/2603

**Comment by Jegelewicz** [comment]
I'm here to make everyone paranoid - it is what accountants do....
