### ISSUE TITLE
Code Table Cleanup - CTCOLL_OBJ_DISP

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2667]
https://arctos.database.museum/info/ctDocumentation.cfm?table=CTCOLL_OBJ_DISP is loaded with "DO NOT USE" terms and contradictory instructions. Let's use this issue for discussing how to make it better.

Some items to consider:

1. This field is defined in the documentation with:

> Disposition describes the status of parts and, as an abstract generality, the status of cataloged items.

2. This field does not have a definition in DwC, so we are free to decide what will be useful to us for now.

3. I think we need to re-define this field. It seems to me that under the current definition and code table terms we are trying to use disposition to tell us WHERE something is - that is meant for a barcode or the part locality attribute.

**Proposed new definition of CTCOLL_OBJ_DISP**

> Disposition describes the availability of an object for use or research.

Currently the code table includes the following:

COLL_OBJ_DISPOSITION | Documentation 
-- | -- 
being processed | Object is in between being accessioned and appearing in the  collection. We don't know exactly where it is right now, but we could  find it. 
deaccessioned | DO NOT USE THIS - use either "discarded" or "transfer of custody" 
discarded | Object has been discarded. Do not use this to mean "used up." 
in collection | Object is where it should be. 
missing | Object cannot be found. 
not applicable | Disposition applied to virtual objects, such as observations.  Also use this for objects that were never received but that we want to  track, e.g., tissue vouchers that are deposited in another collection. 
observation | DO NOT USE THIS - "not applicable" is applicable. 
on exhibit | Object is on exhibit, which hopefully makes some sense in  light of local conditions. 
on loan | Object is currently on an active loan, so is not available in the collections. 
recataloged | DO NOT USE THIS - use either "discarded" or "transfer of custody" 
released | DO NOT USE THIS - parts are "missing" or "used up" and cataloged items do not have disposition, so this is a nonsensical value. 
subsampled | DO NOT USE THIS - it says nothing about the part and just makes no sense. 
teaching collection | DO NOT USE THIS - transfer of custody + a loan is appropriate 
transfer of custody | DO NOT USE THIS - transfer of custody is a loan type. Use "on loan" for the objects which have been transferred. 
unchecked | DO NOT USE THIS - Often misused in lieu of "being processed,"  may also apply to legacy objects which not tracked but are presumably  "in collection." 
unknown | DO NOT USE THIS - "we checked but could think of nothing clever to say after having done so"?? 
used up | the part has been entirely consumed 

Proposed Code table values and definitions

COLL_OBJ_DISPOSITION | Proposed Documentation
-- | -- 
being processed | Object is being processed and may be available for loan or exhibit with some expedited processing. 
~deaccessioned~ | deaccessioned vs. discarded does it matter? Still just "on loan"? 
~discarded~ | deaccessioned vs. discarded does it matter? Still just "on loan"? 
in collection | Object is in the collection and available for loan or research. 
missing | Object cannot be located where it is expected. May be available for loan or research but requires time for a thorough search. 
not applicable | Disposition applied to virtual objects, such as observations.  ~Also use this for objects that were never received but that we want to  track, e.g., tissue vouchers that are deposited in another collection.~ Not sure about struck through text - shouldn't that be "on loan"?
~observation~ | REMOVE change anything using this disposition to "not applicable". 
on exhibit | Object is on exhibit in the collection holding institution, it may or may not be available for use or research. 
on loan | Object is currently on an active loan, so is not available for use or research. 
~recataloged~ | REMOVE change anything using this disposition to "on loan". 
~released~ | REMOVE change anything using this disposition to "on loan".  
~subsampled~ | REMOVE change anything using this to "unknown" and create a subsample for the part. 
~teaching collection~ | REMOVE change anything using this disposition to "on loan". 
~transfer of custody~ | REMOVE change anything using this disposition to "on loan". 
~unchecked~ | REMOVE change anything using this disposition to "unknown".  
unknown | The availability of this object for loan or research has not been established. 
used up | Object has been entirely consumed, so is not available for further loans or research. 

The above are my thoughts on this code table. Feel free to offer up something completely different!

**Comment by campmlc** [comment]
I use transfer of custody for parasite parts in mammals that become
parasite catalog records, cross divisions

**Comment by dustymc** [comment]
> tell us WHERE something is - that is meant for a barcode or the part locality attribute.

Yea I see it as "barcodes lite." Really lite.... 

Strongly agreed that transfer of custody here is a poor substitute for loan type.

**Comment by ewommack** [comment]
Transfer of custody may also be important when you legally donate something to another collection. That doesn't become a loan then...the other museum get's the specimen and can decide what to do with it.

Release is an interesting one - I wonder if it may refer to samples taken of live animals? 

Is deaccessioned more a historical term? I have it in my historic ledgers, but it is not one I use today. Generally I find those specimens in the teaching collection (if I find them at all).

**Comment by dustymc** [comment]
>That doesn't become a loan then

I'd 100% call that a loan (probably of type 'transfer of custody'). Minimally that gets me from "we don't have it" to "...and THEY do."

>deaccessioned

I think it means slightly different things across disciplines (and probably people, time, institutions, etc. - the usual). A transfer of custody loan again provides a single place to unify all the "we don't have it, and we don't expect to get it back" stuff, and a convenient place to elaborate on that (or attach paperwork, etc.) for many items at once.

**Comment by dustymc** [comment]
TODO: Get CSV for each type that needs to go away, use it for a series of "if nobody stops me before {date}" comments.

**Comment by campmlc** [comment]
I'm still using transfer of custody and advocate for keeping it. For a vial of ectoparasites as a mammal part, I create a loan to send the vial off to be sorted,  ID'd, and recataloged as MSB:Para cataloged items. Then I change the disposition on the mammal part to transfer of custody. There is a loan documenting the transfer, and a change in disposition indicating that the mammal part is no longer available. The cataloged items in MSB Para are not the same as the ectoparasite parts in mammals - they have been split into multiple new records with different identifications.

**Comment by adhornsby** [comment]
I changed the single UMZM record of "recataloged" to "transfer of custody" -- for what it's worth, that record was an internal transfer of parasites from Mamm to Para collection, just as Mariel described.  I would also advocate keeping transfer of custody as an option to avoid confusion over ownership, especially between institutions.

(If anything, I see loan as a type of transfer of custody, and not the other way around!  But I think it's simpler and preferable to keep these as separate dispositions.)

**Comment by dustymc** [comment]
There are now issues for all of the problematic terms, closing this.
