### ISSUE TITLE
Error in Accessing Bulkloaded Specimens

### ISSUE THREAD

**Issue by cefilipek** [ArctosDB/arctos#2670]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I loaded my bulkloader file and after checking it in the staging table it was loaded to the bulkloader. When I went to Browse and Edit to upload the records to Arctos I got an error reading "ORA-12519 The listener could not find any available service handlers that are appropriate for the client connection. One possible cause for this error is that the server was not configured for the specified server type (shared/dedicated)." I was able to access the bulkloader by going through the data entry portal, but I have received this error several times attempting to access it through Browse and Edit.

**To Reproduce**
1. Go to Enter Data
2. Click on Bulkloader
3. Scroll down to and click Browse and Edit

**Expected behavior**
For it to take me to the page to select my collection and look at it in the AJAX grid.

**Screenshots**
<img width="1112" alt="Screen Shot 2020-05-11 at 4 25 34 PM" src="https://user-images.githubusercontent.com/56844074/81613797-b04d5880-93a4-11ea-8c4d-64848af4ab30.png">

** Data**
N/A

**Desktop (please complete the following information):**
 - OS: IOS
 - Browser Chrome
 - Version 81.0.4044.129

**Additional context**
N/A

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
its up
