### ISSUE TITLE
Error -- ORA-12519 The listener could not find any available service handlers that are appropriate for the client connection. One possible cause for this error is that the server was not configured for the specified server type (shared/dedicated).

### ISSUE THREAD

**Issue by krgomez** [ArctosDB/arctos#2671]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I am getting this error when trying to use Arctos today: ORA-12519 The listener could not find any available service handlers that are appropriate for the client connection. One possible cause for this error is that the server was not configured for the specified server type (shared/dedicated).

**To Reproduce**
Simple search by agent name trying to access catalog records

**Expected behavior**

**Screenshots**
![Screen Shot 2020-05-11 at 1 25 16 PM](https://user-images.githubusercontent.com/40579515/81613832-95bab580-938b-11ea-84ca-1092975569b0.png)

** Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**
Mac OS 10.15.4 -- Firefox

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
its up
