### ISSUE TITLE
County name change Shannon County, SD is now Oglala Lakota County, SD

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2674]
https://www.naco.org/articles/shannon-county-sd-be-renamed-oglala-lakota-county

How do we handle this?

[Wikipedia](https://en.wikipedia.org/wiki/Oglala_Lakota_County,_South_Dakota)

**Comment by dustymc** [comment]
>How do we handle this?

http://handbook.arctosdb.org/documentation/higher-geography.html#guidelines-for-geographic-terms-in-arctos

Use current definitions, where possible. For example: Yugoslavia no longer exists, so use Slovenia, Croatia, or whichever country the locality is now in, especially if cataloging current material. If Yugoslavia was used in the original data, it now belongs in verbatim locality, not in Higher Geography. If you are editing specimen records, append the old higher geography to verbatim locality in the following order: verbatim_locality, state, country. We will support Higher Geography of deprecated countries, state/provinces for legacy materials but STRONGLY urge curators to view this as a short-term solution and re-assign as appropriate. Any Geography term can have synonyms and alternate names to maximize discoverability. We will support WKT footprints for modern geography only.

I think ideally for a clean name change you'd just change the geog entry and put the "old" in search terms, but that should probably go by anyone using it first Just In Case.

**Comment by mkoo** [comment]
Once we are in a PG environment and start dealing with Features as
extrapolated geography, Deprecated names eventually could become a feature.

**Comment by dustymc** [comment]
Merge-->https://github.com/ArctosDB/arctos/issues/3018
