### ISSUE TITLE
Materials, Techniques, Implements, and Color

### ISSUE THREAD

**Issue by krgomez** [ArctosDB/arctos#2676]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

** Describe what you're trying to accomplish** 
We would like to propose the creation of new attributes using controlled entry for materials, techniques, colors, and implements. We have created lists for what terms would be included in these code tables (see links below). Our hope is that this will be helpful for other collections as well as helping us meet best-practices for our discipline -- see #2478.

The materials, techniques, color, and tools/implements used in art/object making are fundamentally important information to catalog for reasons including artistic intent, conservation, exhibition, teaching, research, as well as physical documentation. The Getty CDWA groups this cataloging metadata together in the “[materials/techniques](http://www.getty.edu/research/publications/electronic_publications/cdwa/8materials.html)” category. In this category, the “materials/techniques description” is considered a core (required) subcategory, described as an “indication of the substances or materials used in the creation of a work, as well as any implements, production or manufacturing techniques, processes, or methods incorporated in its fabrication, presented in a syntax suitable for display to the end-user and including any necessary indications of uncertainty, ambiguity, and nuance”.

We currently document the “materials/techniques description” in the Arctos “materials” attribute. While we therefore are already cataloging this core information, we feel that there is room for enhancement in Arctos for documenting and indexing materials, techniques, color, and implements involved in the making of artworks and objects. Below is a little about each of these areas that could use enhancement based on information from the CDWA. Specifically, we feel controlled entry indexing for each of these sets of information would greatly enhance discoverability. We are curious to hear your thoughts on this and to see if other collections would also find this useful.

**Materials**
Materials are the matter, materials, or substances used to create a work. Encompasses both the medium (material applied to the support) and support (surface upon which media have been applied) of a work. Potentially, if this were to become a controlled entry attribute, we might want to be able to choose medium or support from a dropdown within the attribute in order to be able to distinguish. Also, if we wanted to create a new controlled entry attribute for indexing materials, we would need to either change the name of the current materials attribute or call this one something else. We would use the Getty AAT for terms. [Here is a list we have compiled](https://drive.google.com/open?id=1dfPtgz2Qmwyv5K4pMwhfNPUZd2KmFSEeLQuqghy-K_s) as a starting point for terms the art collection would possibly use.

**Techniques**
Techniques are the activities used in the creation process. We would use the Getty AAT for terms. [Here is a list we have compiled](https://drive.google.com/open?id=19g7T67Etqls1_8Cc5y_eAG_5OECqUKqHeUw2Kq_hAjs) as a starting point for terms the art collection would possibly use.

**Material Color** 
Color is a critical element in visual art, both directly through how we visually perceive a work but also through meaning and intent. There are some great examples of online collections that allow users to search collections by color. See, for example, the [Dallas Museum of Art](https://collections.dma.org/). 

This is very much in line with what is being discussed in #2564 and #2655. Given that the perception of color is subjective, and in order to allow for accurate cataloging and searching, we would like to use a simple range of colors. This is what the DMA does. There are some great examples of collections (see for example [Indianapolis Museum of Art](http://collection.imamuseum.org/) and [Art Institute of Chicago](https://www.artic.edu/collection)) using a swatch system with more complicated color use and is very cool, but obviously not something that can be accomplished at this time. The colors we would like to use at this point include black, blue, brown, gold, green, gray, metallic (technically a color attribute, but we feel it would be useful for the art collection to document this), orange, pink, purple, red, silver, white, and yellow. 

**Implements** 
Implements are the tools used in the creation process. While we would not want to index all implements used in art making, we do think it would be an appropriate place to record, for example, the camera and film used for photographs in the collection, which we were trying to find a solution for in issue #2505. 

**Describe the solution you'd like**
We think this would be best done as new controlled entry attributes. 

**Describe alternatives you've considered**
Continuing to only record the materials/techniques description as free text in the materials attribute.

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by Jegelewicz** [comment]
Addition to ctattribute_type code table:

term | collection | definition | type 
 -- | -- | -- | -- 
material | Art, EH | the matter, materials, or substances used to create a work. Encompasses both the medium (material applied to the support) and support (surface upon which media have been applied) of a work. Potentially, if this were to become a controlled entry attribute, we might want to be able to choose medium or support from a dropdown within the attribute in order to be able to distinguish | categorial 
technique | Art, EH | the activities used in the creation process | categorical 
implement | Art, EH | the tools used in the creation process. | free text 

I am leaving material color out for now, because we already have the attribute "colors", so that one will need a broader discussion.

New code tables for categorical attributes:

ctmaterial - https://docs.google.com/spreadsheets/d/1dfPtgz2Qmwyv5K4pMwhfNPUZd2KmFSEeLQuqghy-K_s/edit#gid=0
cttechnique - https://docs.google.com/spreadsheets/d/19g7T67Etqls1_8Cc5y_eAG_5OECqUKqHeUw2Kq_hAjs/edit#gid=0

How do we handle parent/child relationships in these tables?

**Comment by krgomez** [comment]
Thank you for working on this Teresa! 

Question -- There is a conflict with the new "material" controlled vocab term and the current "materials" free-text term that we use. We definitely need to keep a free text attribute for recording the "materials and techniques description" as this is a [core format for art collections](http://www.getty.edu/research/publications/electronic_publications/cdwa/8materials.html#RTFToC2), in addition to documenting these data with controlled entry. Would we want to change the "materials" attribute name to something else? Could we change it to "materials and techniques description" or would this not work for EH and Arc?

**Comment by AJLinn** [comment]
Sorry I'm not clear what change is happening.  
Is this going to replace the current ctattribute_type - materials...
![Screen Shot 2020-07-16 at 1 42 03 PM](https://user-images.githubusercontent.com/17605945/87725756-597c4a80-c76a-11ea-9332-0dc09c944ca8.png)
...with a new one that is dictated by the controlled vocabulary proposed in the "materials index" google sheet?

If so, we would be expected to add an attribute for each single material type? EH items often are made up of anywhere from 3-20 different materials. Just trying to determine how this will impact the appearance of our catalog record (e.g., https://arctos.database.museum/guid/UAM:EH:UA2002-021-0001).

While I definitely like the idea of standardizing the materials list for improved discoverability, I'm just thinking while writing here and want to be sure we are considering how this and the discussions we're having over at #2499 are being considered in tandem.

**Comment by krgomez** [comment]
Is there a way to change the appearance of attributes maybe? If we begin to use controlled entry for materials, techniques, implements, as well as keywords, it will be quite a few individual attributes. For a record with a number of materials, techniques and keywords, I can imagine it possibly being something like 50 attributes. I don't think that would be the norm, but even for the average record it could be 25 attributes. I have been wondering about how this is going to look as well.

**Comment by dustymc** [comment]
>How do we handle parent/child relationships in these tables?

Emphatic vote for "we don't" from me - flatten them out.

>There is a conflict with the new "material" controlled vocab term and the current "materials" free-text term that we use.

There's no conflict.

>change the appearance of attributes

Short answer "yes." Coordinating that across all collections would be very beneficial from my perspective, but we can probably afford to do it by collection if that's not possible. https://arctos.database.museum/guid/MSB:Mamm:312468 has 93 attributes; this isn't just a "cultural thing."

**Comment by Jegelewicz** [comment]
> There is a conflict with the new "material" controlled vocab term and the current "materials" free-text term that we use. We definitely need to keep a free text attribute for recording the "materials and techniques description" as this is a core format for art collections, in addition to documenting these data with controlled entry. Would we want to change the "materials" attribute name to something else? Could we change it to "materials and techniques description" or would this not work for EH and Arc?

The terms discussed above are additions and so would not affect the current terms. I do agree that changing the current "materials" free text attribute to something more descriptive might be helpful and materials and techniques description seems like a good replacement (although a little long).

**Comment by Jegelewicz** [comment]
> If so, we would be expected to add an attribute for each single material type? EH items often are made up of anywhere from 3-20 different materials. Just trying to determine how this will impact the appearance of our catalog record (e.g., https://arctos.database.museum/guid/UAM:EH:UA2002-021-0001).

That's up to you. You can specify for easier searching or just enter the free text or do both.

**Comment by Jegelewicz** [comment]
> Is there a way to change the appearance of attributes maybe? If we begin to use controlled entry for materials, techniques, implements, as well as keywords, it will be quite a few individual attributes. For a record with a number of materials, techniques and keywords, I can imagine it possibly being something like 50 attributes. I don't think that would be the norm, but even for the average record it could be 25 attributes. I have been wondering about how this is going to look as well.

My first inclination is to use the expand technique we are using with parts and locality. This would be a quick first step, but yes, we should have a larger conversation about the look of the entire record.

**Comment by Jegelewicz** [comment]
> How do we handle parent/child relationships in these tables?

The terms are "nested" and we need a way to facilitate search across the nest (A search for bone, would also turn up all of the antlers).

**Comment by dustymc** [comment]
Is this still active?

FWIW the code tables don't seem appropriate to me - there are a near-infinite number of potential materials, I don't think trying to preemptively list them all is sustainable. https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#materials exists and seems to serve the need?

**Comment by krgomez** [comment]
It's fine to close this for now. The point of this issue was to better conform data fields available to art collections in Arctos with [CDWA (Categories for the Description of Works of Art) best practices](http://www.getty.edu/research/publications/electronic_publications/cdwa/8materials.html#RTFToC2).

We use the _materials_ attribute in Arctos to record our _materials/techniques description_, which is an indication of the substances or materials used in the creation of a work, as well as any implements, production or manufacturing techniques, processes, or methods incorporated in its fabrication, presented in a syntax suitable for display to the end-user and including any necessary indications of uncertainty, ambiguity, and nuance. 

Therefore we are using the _materials_ attribute in a way that goes beyond what it is currently described as: Materials used in the construction of the object. (These data will be normalized and standardized as cultural collection development continues.)

While it seems like it would be more thorough to have controlled entry attributes for materials, techniques, and implements in addition to a free text materials/techniques description, if it doesn't seem useful to anyone else at this time, we can continue using the materials attribute in the way that we are currently.
