### ISSUE TITLE
better check constraints

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#2678]
Ref: https://github.com/ArctosDB/arctos/issues/2675

PG allows check constraints as functions, so it's becoming possible/practical to check for much more than just nonprinting characters. I've built a function that replicates existing checks and will change the constraints to use it.

After we've fully migrated to PG, I'll add  � and  (and whatever else we want to prevent in free-text data) to the function, which will disallow inserting or updating noncompliant data.

This will likely require significant cleanup. (Or I could eg replace � with ``[weird unicode conversion failure diamond thingee]`` or something.) We can deal with that once we're no longer facing a migration, in the meantime please carefully review http://handbook.arctosdb.org/documentation/encoding.html, and ensure that anyone who's working with text data fully understands character encoding.

Please let me know if you discover any other unwanted characters in any context; cleaning them all at the same time will be much easier than re-running this as we discover new problematic data.

I'm marking this critical; we are apparently actively introducing data which has not been properly converted to UTF.

**Comment by dustymc** [comment]
Ref: https://github.com/ArctosDB/arctos/issues/2661#issuecomment-626811228

Is there any reason we shouldn't add 

```
trim(regexp_replace({input}, '\s+', ' ', 'g'))
```

which is "replace multiple occurrences of spaces with one and trim the result" to the check attached to all free-text fields?

**Comment by Jegelewicz** [comment]
I can't think of any reason you would want two spaces next to each other...

**Comment by campmlc** [comment]
This sounds reasonable.

**Comment by dustymc** [comment]
The basic functionality we've always had was implemented as a function when we came up in PG. I built a "preview" function which includes some more weird characters and double spaces. It can be implemented at any time. If we swap it in now

* we won't get any more funky data, yay
* it won't be possible to save with funky data, which is probably not so "yay" - eg, it will prevent a lot of scripts from successfully completing

How to proceed? 

Here's the function. Do we need to test for more patterns, is anything being caught that shouldn't, etc?

```
CREATE OR REPLACE FUNCTION checkfreetext__v2 (inp varchar) RETURNS boolean AS $body$
BEGIN
   if inp ~ '[\cA-\cZ�]' or inp ~ '  +' then
   	return false;
   end if;
   return true;	
  end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 PARALLEL SAFE
 immutable;
```
Here's funky speclocs.

```
 create table temp_cache.locality_with_funky_specloc as select * from locality where  checkfreetext__v2(spec_locality)=false;
```
[temp_cache.locality_with_funky_specloc.csv.zip](https://github.com/ArctosDB/arctos/files/4789443/temp_cache.locality_with_funky_specloc.csv.zip)

**Comment by Jegelewicz** [comment]
Will that also catch trailing spaces? I can't think of anything else right now, but I'm sure that something will come up eventually.

> it won't be possible to save with funky data, which is probably not so "yay" - eg, it will prevent a lot of scripts from successfully completing

The list above has all the currently funky stuff? What can we replace the funky stuff in those with that will allow scripts to run, but still demonstrate an obviuos need for a fix? Suggestion:

"non-conforming character removed"

**Comment by campmlc** [comment]
Agree.

**Comment by dustymc** [comment]
>trailing spaces?

It does now.

```
   if inp ~ '[\cA-\cZ�]' or inp ~ '  +' or inp!=trim(inp) then
```

[temp_cache.locality_with_funky_specloc.csv.zip](https://github.com/ArctosDB/arctos/files/4793528/temp_cache.locality_with_funky_specloc.csv.zip)


>s all the currently funky 

... for one field in one table. This will ultimately apply everywhere there used to be a NOPRINT constraint - very close to all free-text fields. I can round those up if I need to, but I suspect that'd be a little overwhelming for everyone.

>"non-conforming character removed"

I like it, but it's probably verbose enough to break something (especially when there are 40 of them in a row).

**Comment by Jegelewicz** [comment]
HMMMM, what about replacing the non-conforming stuff with "[]", then adding "[]=non-conforming character removed" at the end of the text? Still too crazy?

**Comment by Jegelewicz** [comment]
or is [] non-conforming?!

**Comment by dustymc** [comment]
``[]`` is fine.

The inline-appendix is better, I think, but I can't know if it fits without trying.

There are lots of unicode characters ([𓀠](http://www.fileformat.info/info/unicode/char/13020/browsertest.htm), [🤷](http://www.fileformat.info/info/unicode/char/1f937/index.htm)) that PROBABLY don't appear in scientific data; they're easy to search, which is nice, take up the same number of bytes as whatever they're replacing, which is nice, and are probably impossible to decipher when they pop up somewhere in a decade, which isn't so great. Arctos folks are likely semi-used to my go-to, ``[X]``, but it's 3 characters instead of one (MAYBE not a problem) and probably still cryptic in a decade.

I don't have any good ideas, other than just fixing the problems, and I doubt anyone's got time to jump into that.

Fixing doubled spaces and TRIMming would get ~half of the locality problems; I can easily do that, but I'm generally hesitant to mess with any data without some sort of acknowledgement from the owners. Maybe this is a good time to rope in The Community.

**Comment by dustymc** [comment]
Changing milestone. This is ready to implement, but I can't until I can clean data, which is going to require some sort of action from the collections. 

The problems are going to continue to pile up as long as we let them; strongly suggest either rejecting or prioritizing this as soon as possible.

**Comment by Jegelewicz** [comment]
> require some sort of action from the collections.

Can I get a by-collection idea of the work required?

**Comment by dustymc** [comment]
```
CREATE OR REPLACE FUNCTION checkfreetext__v2 (inp varchar) RETURNS boolean AS $body$
BEGIN
   if inp ~ '[\cA-\cZ�]' or inp ~ '  +' or inp!=trim(inp) then
   	return false;
   end if;
   return true;	
  end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 PARALLEL SAFE
 immutable;
 

select guid_prefix,count(*) c from collection inner join cataloged_item on collection.collection_id=cataloged_item.collection_id inner join specimen_event on cataloged_item.collection_object_id=specimen_event.collection_object_id inner join collecting_event on specimen_event.collecting_event_ID=collecting_event.collecting_event_ID inner join locality on collecting_event.locality_id=locality.locality_id
where 
checkfreetext__v2(spec_locality) is false or
checkfreetext__v2(verbatim_locality) is false
group by guid_prefix order by count(*);


 guid_prefix  |   c   
--------------+-------
 JSNM:Paleo   |     1
 NMU:Bird     |     1
 UAMObs:Fish  |     1
 UCM:Fish     |     1
 COA:Egg      |     1
 UCSC:Mamm    |     1
 KNWR:Inv     |     1
 OWU:Mamm     |     2
 OWU:ES       |     2
 MLZ:Mamm     |     2
 CHAS:Fish    |     2
 MVZObs:Herp  |     3
 UTEP:Zoo     |     3
 MLZ:Fish     |     4
 UAMObs:Mamm  |     4
 WNMU:Bird    |     5
 UCM:Bird     |     6
 WNMU:Fish    |     6
 UTEP:Bird    |     7
 OWU:Fish     |     7
 UCSC:Bird    |     7
 NMU:Mamm     |     8
 KNWRObs:Fish |     8
 UMNH:Bird    |     9
 UMNH:Teach   |     9
 NMMNH:Herb   |    10
 UAM:Herp     |    10
 UAM:Alg      |    10
 UWYMV:Fish   |    11
 UTEP:Teach   |    12
 UWYMV:Bird   |    12
 DMNS:Para    |    12
 ASNHC:Bird   |    12
 MVZ:Egg      |    13
 UWYMV:Mamm   |    13
 UAM:Art      |    13
 CHAS:Herb    |    14
 UAM:Env      |    20
 UTEP:Arc     |    21
 UMZM:Bird    |    23
 USNPC:Para   |    26
 CHAS:Inv     |    27
 CHAS:Teach   |    31
 UNM:ES       |    32
 APSU:Herp    |    33
 UTEP:Fish    |    33
 CHAS:Egg     |    34
 CHAS:Mamm    |    36
 UCM:Obs      |    37
 UTEPObs:Herp |    42
 WNMU:Mamm    |    44
 DGR:Bird     |    47
 UNR:Mamm     |    48
 MVZ:Fish     |    53
 HWML:Para    |    54
 NMMNH:Bird   |    55
 UNR:Fish     |    56
 DGR:Mamm     |    60
 UWBM:Mamm    |    68
 UWBM:Herp    |    77
 UNR:Bird     |    77
 UMZM:Mamm    |    88
 CHAS:Bird    |    89
 MLZ:Bird     |    90
 UAM:Bird     |    96
 UCM:Egg      |   100
 UTEP:HerpOS  |   102
 UCM:Mamm     |   115
 CHAS:Ento    |   119
 ALMNH:ES     |   127
 MVZObs:Bird  |   134
 KNWR:Ento    |   159
 DMNS:Mamm    |   187
 KNWR:Herb    |   191
 UAM:EH       |   236
 NMMNH:Mamm   |   239
 UCSC:Herp    |   252
 DMNS:Egg     |   265
 NMMNH:Ento   |   315
 ASNHC:Herp   |   321
 UTEP:Mamm    |   368
 UNR:Herp     |   386
 NMMNH:Inv    |   401
 UAM:Fish     |   464
 UMNH:Mamm    |   487
 MVZ:Bird     |   528
 MSB:Host     |   551
 UAM:Inv      |   718
 BYU:Mamm     |   728
 BYU:Herp     |   729
 UTEP:Inv     |   779
 MSB:Para     |   814
 MSB:Herp     |   840
 KWP:Ento     |   843
 UAM:ES       |   862
 UAMb:Herb    |   913
 MSB:Bird     |   969
 MVZ:Mamm     |  1002
 DMNS:Bird    |  1066
 UTEP:Ento    |  1197
 DMNS:Inv     |  1253
 UCM:Herp     |  1278
 UTEP:Herp    |  1406
 UAMObs:Ento  |  1542
 MVZ:Herp     |  1657
 NMMNH:Paleo  |  2125
 UAM:Arc      |  2189
 MSB:Fish     |  2271
 UAM:Mamm     |  2900
 UTEP:Herb    |  2954
 ASNHC:Mamm   |  4289
 UAM:Ento     |  5453
 UMNH:Herp    |  6031
 MSB:Mamm     | 11496
 UTEP:ES      | 12359
 UAM:Herb     | 70837

```

**Comment by dustymc** [comment]
From https://github.com/ArctosDB/arctos/issues/3124#issuecomment-698489541 - maybe we need field-specific checks in addition to anything global. No problem to do so, just a bit more code to maintain and perhaps a bit more difficult to understand the rules.

```

arctosprod@arctos>> select verbatim_date, count(*)  from collecting_event where verbatim_date like '%#%' group by verbatim_date;
                    verbatim_date                     | count 
------------------------------------------------------+-------
 ##############################                       |     1
 1910&#39;s                                           |     1
 1914 &#34;probably&#34;                              |     1
 27 APR&#39;.1980                                     |     1
 27 Dec &#39;00                                       |     1
 #5-77                                                |     1
 collection date probably during the 1960&#39;s (CSL) |     1
 Feb &#39;67 or Mar &#39;68                           |     1
 June # 17. 1987                                      |     1
 #N/A                                                 |   134
 #NAME?                                               |     1
(11 rows)

```

https://handbook.arctosdb.org/documentation/encoding.html - ``&#39;`` is (probably) an html-encoded apostrophe, for example.

**Comment by Jegelewicz** [comment]
Any # without an associated & gets a flag?

**Comment by dustymc** [comment]
&encoded aren't searchable, and there's zero(ish, maybe) reason to use them in Arctos (or any other UTF environment). Left to my own devices, I might double-flag them due to the confusion factor....

So maybe there are two things going on here:

1. Hard rules enforced by check constraints, and
2. Some script that periodically adds annotations or something

??

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/2675#issuecomment-729172060

>where else do we have �?


```
create table temp_has_diamond_thingee (tbl varchar,col varchar, cnt int);


CREATE OR REPLACE function whurzajunk () returns void AS $body$
DECLARE
  c bigint;
  r record;
  t record;
BEGIN
  for t in (
      select 
        table_name 
      from 
        information_schema.tables 
      where 
        table_schema='public' and 
        table_name not like 'bak%' and
        table_name not like 'temp%' and
        table_name not like '%flat%' and
        table_name not like 'cct%' and
        table_name not like 'ct%' and
        table_name not like 'cf%' and
        table_name not like 'cache%' and
        table_name not like 'test%' and
        table_name not like 'log%' and
        table_name not like 'bulk%' and
        table_name not like 'v_%' and
        table_name not like 'ds_%'and
        table_name not like 'old%'
      order by table_name
  ) loop
    for r in (select column_name from information_schema.columns where table_schema='public' and table_name=t.table_name  and data_type='character varying') loop
       execute 'select count(*) from '  || t.table_name || ' where ' || r.column_name || ' like $$%�%$$' into c;
      if c>0 then
        insert into temp_has_diamond_thingee (tbl,col,cnt) values (t.table_name,r.column_name,c);
      end if;     
    end loop;
  end loop;
end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
select whurzajunk();
select * from temp_has_diamond_thingee order by tbl;

           tbl            |          col           | cnt  
--------------------------+------------------------+------
 agent_name               | agent_name             |    1
 annotations              | annotation             |    1
 attributes               | attribute_value        |  793
 attributes               | attribute_remark       |    3
 block_phrase             | phrase                 |    1
 citation                 | citation_remarks       |    1
 collecting_event         | coll_event_remarks     |   11
 collecting_event         | verbatim_date          |   45
 collecting_event         | verbatim_locality      | 1211
 collecting_event_archive | coll_event_remarks     |    3
 collecting_event_archive | verbatim_date          |    1
 collecting_event_archive | verbatim_locality      | 1669
 coll_object              | condition              |   35
 coll_object_remark       | coll_object_remarks    |  348
 coll_object_remark       | associated_species     |    2
 coll_obj_other_id_num    | display_value          |   25
 coll_obj_other_id_num    | other_id_prefix        |   25
 container                | label                  |    4
 container                | description            |    1
 exit_link                | http_target            |    1
 exit_link                | target                 |    1
 geology_archive          | geo_att_remark         |   24
 geology_attributes       | geo_att_remark         |   24
 identification           | identification_remarks |  179
 locality                 | spec_locality          |   61
 locality                 | locality_remarks       |  484
 locality                 | georeference_source    | 1639
 locality_archive         | spec_locality          | 1150
 locality_archive         | locality_remarks       |  263
 locality_archive         | georeference_source    |   72
 locality_attributes      | attribute_remark       |   24
 media_labels             | label_value            |   19
 object_condition         | condition              |   39
 project                  | project_description    |    1
 specimen_event           | specimen_event_remark  |  555
 specimen_event           | collecting_method      |   17
 specimen_event           | habitat                |  169
 specimen_part_attribute  | attribute_value        |    4
 taxon_term               | term                   | 1160
 trans                    | nature_of_material     |    8
 trans                    | trans_remarks          |    1
(41 rows)

```

**Comment by Jegelewicz** [comment]
whurzajunk

HAHAHAHAHA!!

Jeez. I don't want it to grow, so I vote we put [?] in the place of the junk, then we can search by that and add to "low quality data"?

I'll work through stuff as time permits - until I get a job.

**Comment by Jegelewicz** [comment]
This would be a good intern project...

**Comment by Jegelewicz** [comment]
@dustymc here is a cleanup item

in verbatim collector change all Ch�vez, Angela to Chávez, Angela

**Comment by dustymc** [comment]
Better function is live, we can deal with whatever melts when it melts.

Ch�vez updated.

**Comment by dustymc** [comment]
function updated to allow two sequential spaces

**Comment by DerekSikes** [comment]
I've had various things rejected/fail recently because of trailing spaces (eg creating a new publication gives an error if there is a trailing space). I just tested the cat record search form and wonderfully a trailing space in the identification field is ignored (yay!) but in the barcode field it's not (boo!). Seems like a problem that we can't safely assume/know which fields ignore and which don't ignore trailing spaces.

**Comment by campmlc** [comment]
Agree that fixing this would be a huge timesaver. I occasionally am working with a list of barcodes with invisible leading or trailing spaces (eg copy/pasted from somewhere else, such as an email or github issue, or converted from a list of "barcode, barcode, barcode" which ends up with spaces where there shouldn't be any.  In any situation where these are a problem, eg. a bulkload file, I have to stop what I'm doing, get utterly distracted trying to find the extra invisible spaces, get called away by a student - and lose my workflow.

**Comment by AJLinn** [comment]
I’ve also noticed that if you are editing a single record and upon save, a non-printing character (usually a trailing space, but sometimes it’s the dreaded double space following a period - 😱 ) is detected sometimes you can go back and recover all the info you just spent time entering and sometimes the info you added is gone and you have to start totally over again… (I think it might be in the attributes where it all goes away).
