### ISSUE TITLE
Quad with unknown County

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2679]
We have a few localities where we have a decipherable quad map, but the quad covers more than one county and the county is not given in the locality:

Suggested Higher Geog | Applicable Counties
-- | --
North   America, United States, Garrison 7.5 minute Quad | Millard County, Utah and White Pine County, Nevada
North America, United States, Arizona, Agate House 7.5 minute Quad | Apache and Navajo Counties
North America, United States, New Mexico, South Garcia SE 7.5 minute Quad | Bernalillo and Valencia Counties
North America, United States, New Mexico, Hembrillo Canyon 7.5 minute Quad | Sierra and Dona Ana Counties

I am wondering if it is better to create the Higher Geog for each county and then offer alternative events in the catalog record OR if I should just create the Higher Geog as referenced above.

Thoughts?

**Comment by Jegelewicz** [comment]
@Nicole-Ridgwell-NMMNHS what would be your preference?

**Comment by mkoo** [comment]
ugh this breaks all sorts of practices we were trying to follow, such as HG
being reserved for administrative boundaries.... (I'm still trying to
recover from the shock of the first suggestion)

what do you mean exactly by 'decipherable quad map'? are the localities
mapped then? or just that the localities are the quads? A locality can be a
quad and a wkt but can you not choose the next best admin polygon for HG?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
To give a concrete example:
NMMNHS 6788
New Mexico, South Garcia SE 7.5 minute Quad

South Garcia Quad SE straddles the boundary between Bernalillo and Valencia counties.

We have coordinates for this locality, but somewhere along the way someone probably made a transcription error and the locality is showing up a long way away from Bernalillo and Valencia counties. In short, we can't tell whether the locality is in Bernalillo or Valencia county.

There is geology and other info associated with the locality, so it isn't just "this locality is the whole quad".

My preference: leave the county out of higher geography until these localities can be georeferenced through field notes, etc.

**Comment by dustymc** [comment]
>HG being reserved for administrative boundaries

I don't think this is realistic as long as one of AK's "counties" is bigger than Utah.

>choose the next best admin polygon

For https://catalog.data.gov/dataset/usgs-us-topo-7-5-minute-map-for-garrison-utnv-2020 that's "United States."

I'm not crazy about the mishmash of junk that's in higher geog, and I really hate the "12 square feet intersection of Bla State, Blah State Mini Golf Course, Blaugh Quad" junk that this sort of thing perpetuates, but I'd also hate for our semi-arbitrary administrative decisions to turn 50 square mile precision into half-a-continent. I don't **like** this, but I think we're stuck with it until we find a better model.

It would be exceptionally useful to find polygons for all of the recently-introduced 7.5' quads.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
The polygons exist, they just need to be extracted from one of the kml or gis files that are out there. I'll see if there is something simple I can do to get those from the kml file that I use regularly.

**Comment by Jegelewicz** [comment]
> what do you mean exactly by 'decipherable quad map'? 

This - https://ngmdb.usgs.gov/ht-bin/tv_browse.pl?id=79b4b1e96fd6eadfcd9db4091d0836bc

Our locality gives the Quad, but not the state or county portion of the quad.

**Comment by Jegelewicz** [comment]
> It would be exceptionally useful to find polygons for all of the recently-introduced 7.5' quads.

I personally would LOVE that!

**Comment by mkoo** [comment]
that can be doable-- maybe we can add them all later if there's a batch
workflow but I can convert anything to anything GIS-wise.
I'm going to make an issue to remind myself post PG (or maybe it's on a
to-do list somewhere) Maybe I can just store the polygons somewhere and you
can grab and make localities as needed as a stop gap measure.

**Comment by Jegelewicz** [comment]
From the [topo map site](https://ngmdb.usgs.gov/topoview/help/#topoview-download):

> Downloading Maps
> 
> TopoView offers the topographic maps in a variety of downloadable file formats, in order to meet a range of user needs. The GeoTIFF, KMZ, and GeoPDF formats are georeferenced file formats. Georeferencing means that the internal coordinate system of a map can be related to a ground system of geographic coordinates. The relevant coordinate transforms are typically stored within the image file and can be accessed using software that can read this information. Simply click any of the download links for the selected record in the map information window to download the map. The following formats are available for download:
> 
> GeoTIFF – The GeoTIFF files are a compressed, TIFF image format, with embedded georeferencing information so that the map can be used directly in a GIS. GeoTIFFs downloadable through topoView are highly compressed 300 dpi TIFF images with georeferencing information embedded in the header. JPEG-in-TIFF compression was used to compress both the tiled TIFF file, and the reduced resolution internal overlays. The GeoTIFFs are generated at true scale, allowing users to plot the map at the intended map scale in cases where a hard copy is needed.
> 
> KMZ – Used for displaying maps in Google Earth, the KMZ format is a compressed form of the KML format. Provided you have Google Earth installed on your computer, simply double-click on the KMZ, or drag it into the Google Earth interface. The KMZ file includes information about the particular map that you downloaded in both the places pane, and in the overlay map popup.
> 
> JPEG – (Browse JPEG) The high-resolution JPEG format is useful for getting a quick view of the map in order to find place names or simply explore the map area without the need for downloading a larger file. The downloadable JPEG is identical to the image you'll see in your browser when you click on the thumbnail image. But to ensure that the JPEG downloads to your computer, we enclose it in a zip file. Alternatively, simply click on the map thumbnail, and download the JPEG from your browser window.
> 
> GeoPDF – A Portable Document Format (PDF) with a geospatial extension, the GeoPDF© is a branded instance of geospatial PDF. GeoPDF's can be viewed and printed with Adobe Reader or comparable PDF viewing software. The geospatial extensions provide limited GIS functionality, such as displaying ground coordinates and measuring distances and areas.

Don't know if we can make use of any of these...

**Comment by Jegelewicz** [comment]
In the mean time, in order to keep moving forward, I am going to create the HGs like this:

North   America, United States, Garrison 7.5 minute Quad  
North America, United States, Arizona, Agate House 7.5 minute Quad  
North America, United States, New Mexico, South Garcia SE 7.5 minute Quad  
North America, United States, New Mexico, Hembrillo Canyon 7.5 minute Quad  

We can keep this issue open so that we do not forget to address the mapping issue when we get down to really working on spatial stuff.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
@mkoo [here](https://catalog.data.gov/dataset/usgs-map-indices-downloadable-data-collection0f236) is the gis file of the map outlines.

**Comment by mkoo** [comment]
@Jegelewicz does this work?
https://arctos.database.museum/editLocality.cfm?locality_id=11138280

locality that IS the topoquad with associated wkt from Nicole's source (thanks for the link!) and a centroid for the georeference. 

I can add the others but wanted to see if that works. If so, future request will be for a media upload link on locality edit page!

**Comment by Jegelewicz** [comment]
I took what you did and copy/pasted into our locality: http://arctos.database.museum/editLocality.cfm?locality_id=11102113

Just wonder if the HG shouldn't be the quad: North America, United States, Arizona, Navajo County, Agate House 7.5 minute Quad

And the specific locality: Agate House, USGS 7.5 minute Topoquadrangle (no specific locality)

as we did with the counties - http://arctos.database.museum/editLocality.cfm?locality_id=11064565

**Comment by mkoo** [comment]
We have this general criteria (see earlier doc on Arctos localities
from prior WG discussions) that HG are administrative boundaries, which
topoquads are not. Plus topoquads come in all different sizes and
authorities, so it seems like a rabbithole to start using them there.

That is why I am suggesting the locality as the quad and using the next
higher administrative boundary that includes the locality. In my view, the
HG that are quads should be removed and replaced as localities. Many quads
are exclusively in county administrative boundaries so only the ones
including 2 or more would be at the state level.

Seems the only way to follow earlier logic on HG, right?

**Comment by Jegelewicz** [comment]
See @dustymc [comment re: Alaska.](https://github.com/ArctosDB/arctos/issues/2679#issuecomment-628932324)

**Comment by Jegelewicz** [comment]
Also see [this discussion](https://github.com/ArctosDB/arctos/issues/2229).

We have created thousands of HG that include quads.

**Comment by mkoo** [comment]
In Alaska, which is a different kettle of fish.... anyway we hashed through
this
<https://docs.google.com/document/d/1phkENaXRR7zuBCp0-t0y2hGW89phOhCgGOdg5cz064A/edit#heading=h.a98v7sdevmkb>
and
I thought we were going to move into what we want ideally with new records
and deal with Features as a concerted clean-up effort post-PG. (just
because we did something poorly in the past is not a good reason to keep
doing it!) -- those 1000's of topoquads in HG should probably be cleaned up
and do not belong there if we're going to be consistent and let people find
things properly. If we want to include then we are back to arguing about HG
and Features and should be in a special meeting (again), yes? Then we also
should probably prepare for a DarwinCore proposed tweak since topoquads are
not implicit in HG right now and we would then be (knowingly)
non-compliant.

**Comment by dustymc** [comment]
>Alaska

```

UAM@ARCTOS> select state_prov,count(*) from geog_auth_rec where quad is not null group by state_prov order by state_prov;

STATE_PROV
------------------------------------------------------------------------------------------------------------------------
  COUNT(*)
----------
Alabama
	 1

Alaska
       835

Arizona
	95

British Columbia
	 7

California
	18

Chihuahua
	24

Colorado
	39

Connecticut
	 6

Florida
	 2

Georgia
	 1

Idaho
	 2

Nebraska
	 3

Nevada
	12

New Mexico
      2561

North Carolina
	 3

Northwest Territories
	 2

Nunavut
	11

Ohio
	 2

Oklahoma
	 5

Oregon
	 3

Pennsylvania
	 1

Sonora
	 4

South Australia
	 1

South Dakota
	 4

Texas
	97

Utah
	38

Washington
	 2

Wyoming
	17

Yukon Territory
	50


	 1


30 rows selected.
```

><https://docs.google.com

No access

>DarwinCore

I don't see anything in https://dwc.tdwg.org/terms/#dwc:higherGeography that limits what we can concatenate - what am I missing?

**Comment by mkoo** [comment]
Ideally you're concatenating geographies that are DwC fields -- so
http://rs.tdwg.org/dwc/terms/continent
http://rs.tdwg.org/dwc/terms/waterBody
http://rs.tdwg.org/dwc/terms/islandGrouphttp://rs.tdwg.org/dwc/terms/island
http://rs.tdwg.org/dwc/terms/country
http://rs.tdwg.org/dwc/terms/stateProvince
http://rs.tdwg.org/dwc/terms/county
http://rs.tdwg.org/dwc/terms/municipality

most of these share the commonality of also having an authority or two to
lean on. but true dat, we could concatenate locality in there, or order by
word length. Again I am calling out our inconsistencies that we should
earmark for clean-up and not create more to clean or build around. What's
missing (apparently) is some clear criteria although it's implicit in our
documentation about the locality model and been more explicit in webinars
and other discussions.

you have access in the shared folder -- it's under Geography in Arctos

I just want to know if structuring a locality based on a topoquad with a
wkt works because that is something we can work on to bulkload or build
documentation around.

**Comment by dustymc** [comment]
> structuring a locality based on a topoquad with a wkt works 

From the specimen, sure, whatever, shapes are shapes.

That doesn't support "Bla County, but doesn't map there."

**Comment by Jegelewicz** [comment]
It doesn't really matter to me how we do this, but I have some people who rely on topomaps and their ability to search based upon a map name. The only thing I really dislike is putting those names in Specific Locality where they can be misspelled and entered in hundreds of differing formats. And they can't BE the specific locality, because we often have even more specifics than the map name.

This just needs to be part of an larger discussion on what belongs in higher geography and how we should treat stuff that probably should be, but is outside of the DwC fields. And perhaps we need to be questioning DwC and encouraging TDWG to take a deeper look at it. For starters, "County" is a very US-centric designation.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> This just needs to be part of an larger discussion on what belongs in higher geography and how we should treat stuff that probably should be, but is outside of the DwC fields.

Agreed. Also, how we make decisions and who needs to approve. We had the discussion about where to put our quads on GitHub last year and everybody seemed ok with our decision.

If we ultimately decide to move the quads over into locality attributes and can do that in one big bulk edit, I think that is ok for NMMNHS Paleo needs.

**Comment by Jegelewicz** [comment]
AS an aside or possible part of the discussion see https://github.com/tdwg/dwc-qa/issues/156#issuecomment-631637340

**Comment by dustymc** [comment]
Seems like we're all about on the same page - doesn't much matter what we do, but lets do it predictably and consistently. Maybe we should turn https://github.com/ArctosDB/arctos/issues/2498 into a blank-slate Localities-v3 discussion.
