### ISSUE TITLE
Taxon name qualifications in Darwin Core

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2680]
From Bob Mesibov:

> Domain schizophrenia - things have been packed into this field that belong in other fields, like qualified names and "doubles" (more than one name). List attached. Qualifications really belong in another field (e.g. Darwin Core identificationQualifier). A Darwin Core parser expecting scientificName won't be able to handle most of these entries.

[domain_schizophrenia.txt](https://github.com/ArctosDB/arctos/files/4618973/domain_schizophrenia.txt)

Should we be passing things like "Alticola barakshin cf.", "Peromyscus maniculatus or Peromyscus leucopus", "Crotalus atrox x Crotalus scutulatus" and "Acari and Siphonaptera" to DwC differently?

[Alticola barakshin cf.] just drops the cf. at [GBIF](https://www.gbif.org/occurrence/1249256663)

[Peromyscus maniculatus or Peromyscus leucopus](https://arctos.database.museum/guid/MSB:Mamm:299270) looks pretty good in [GBIF](https://www.gbif.org/occurrence/1609381340) although it is interpreted to be Peromyscus maniculatus (I am guessing that GBIF just uses the first scientific name it can match to its backbone)

[Crotalus atrox x Crotalus scutulatus](https://arctos.database.museum/guid/MSB:Herp:44709) gets interpreted as just [Crotalus at GBIF](https://www.gbif.org/occurrence/2446750769) which seems fair, but could it be better?

[Acari and Siphonaptera](https://arctos.database.museum/guid/MSB:Para:29435) ends up as a [Butterfly! at GBIF](https://www.gbif.org/occurrence/2453234533) this one seems pretty crappy, especially as it is meant to show a host/parasite relationship.

I think we might need some guidance....

**Comment by dustymc** [comment]
Crotalus atrox x Crotalus scutulatus does seem like [A group of organisms (sensu http://purl.obolibrary.org/obo/OBI_0100026) considered by taxonomists to form a homogeneous unit.](https://dwc.tdwg.org/terms/#taxon) and I think it could be argued that GBIF is broken there.


We should probably be mapping Peromyscus maniculatus or Peromyscus leucopus as "Peromyscus" but that looks a lot like magic from here (the convergence won't always be so convenient) and probably won't happen.

Acari and Siphonaptera is clearly not an [Occurrence](https://dwc.tdwg.org/terms/#occurrence) - we're just stuffing inappropriate data into DWC (because we have wildly different atomic units) and probably shouldn't be too offended if GBIF pretends it's a butterfly.

It could be argued that DWC is missing "identification," which would provide a more appropriate place for the not-taxonomy data that we're shoving into taxonomy.

**Comment by Jegelewicz** [comment]
https://dwc.tdwg.org/terms/#identification

**Comment by dustymc** [comment]
Well look at that! Maybe we should discuss our DWC mapping.

**Comment by Jegelewicz** [comment]
Yup

**Comment by Jegelewicz** [comment]
See also https://github.com/tdwg/dwc/issues/244

**Comment by Jegelewicz** [comment]
See also #2172

**Comment by Jegelewicz** [comment]
> Maybe we should discuss our DWC mapping.

@dustymc I'd like to work on this. I know you have sent me the location of our Darwin Core Mapping, but I can't find the issue - can you point me there?

**Comment by dustymc** [comment]
https://github.com/ArctosDB/PG_DDL/blob/master/shared_data/dwc_occurrence.sql

**Comment by Jegelewicz** [comment]
@dustymc @dbloom this is an opportunity to test adding a term to our DwC output. Seems like we should add

[dwc:Identification](https://dwc.tdwg.org/terms/#identification)
```
A taxonomic determination (e.g., the assignment to a taxon).
```

and it should include just the part of the Arctos identification that matches a taxon_name so that the following occurs

Arctos Identification | dwc:Identification 
 -- | -- 
Cerithiopsis lata   cf. | Cerithiopsis lata 
Strombus {plicatus pulchellus} | Strombus 


I think that "and" identifications should generate two occurrences, but knowing the potential changes coming at GBIF - I say we just leave this as garbage for now.

I think that "or" identifications should generate two identification fields - which means working on #2236 

Finally, for [dwc:scientificName](https://dwc.tdwg.org/terms/#dwc:scientificName)
```
The full scientific name, with authorship and date information if known.
```
We should be passing the "scientific_name" field from the preferred source classification BUT scientific_name should be built as taxon_name" "author_text"

![image](https://user-images.githubusercontent.com/5725767/147947571-5cf0e1e5-68c0-42cf-9f9c-c5ac06ab860f.png)

But after writing this - maybe if we just embrace #2236 we could clear all of this up?

**Comment by Jegelewicz** [comment]
Also - now I see that for dwc:scientificName we could just pass display_name....

**Comment by Jegelewicz** [comment]
Upping priority because of work being done by @sharpphyl and @albenson-usgs 

@dustymc can we put this on the agenda for office hour? Also, it seems office hour has dropped from the calendar. When would you prefer I add it?

**Comment by Jegelewicz** [comment]
Alternatively, if @dustymc can show up at taxonomy committee (2022-01-19 2PM MST) we can work on it then.

**Comment by dustymc** [comment]
>Upping priority

I think that would need to come from the Curators. (I'm still seeing 600 probably-mostly-core issues to get through.)

Last Tuesday at noon still works for me, but I can be pretty flexible.

**Comment by Jegelewicz** [comment]
Who exactly are "the Curators"?

**Comment by Jegelewicz** [comment]
@dustymc any chance you could work on this? Just adding the dwc:identification to our DWC output.

**Comment by Jegelewicz** [comment]
Can this be addressed as part of the GUM work? I don't know how that is progressing, but we should clean this up there while we have an opportunity.

**Comment by tucotuco** [comment]
I suspect much of what you are concerned about is or will be addressed. Right now Darwin Core has the term [verbatimIdentification](https://dwc.tdwg.org/terms/#dwc:verbatimIdentification) where any of the combinations can go comfortably. In the [Unified Model](https://tinyurl.com/diversifying-gbif-data), we have incorporated taxonFormula (sensu Arctos) in the Identification table.

**Comment by Jegelewicz** [comment]
@dustymc have we done this? https://github.com/ArctosDB/arctos/issues/2680#issuecomment-627672145 should we continue talking about it, or should I close this?

**Comment by dustymc** [comment]
One unified/actionable mapping document/issue/whatever would be super-useful if a DWC map adjustment is what needs to happen.

**Comment by Jegelewicz** [comment]
https://docs.google.com/spreadsheets/d/1IeqgpGaj7DkzHSNPrbTLpMdWSEx3IlYwu3xAYjRpec8/edit

**Comment by dustymc** [comment]
Merging into https://github.com/ArctosDB/arctos/issues/7348 as inactionable; please reopen if I've missed something tangible.
