### ISSUE TITLE
Inconsistency between cloning to an existing name or to a new name.

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2682]
OH wait! I see it now - If I "Clone Classification as a new name" I am asked if I want to use the whole thing or a cleaned classification:

![image](https://user-images.githubusercontent.com/5725767/81753018-1652e200-9470-11ea-9d61-42ee8b35a24d.png)

BUT if I Clone Classification into an existing name, I am not:
![image](https://user-images.githubusercontent.com/5725767/81753115-4e5a2500-9470-11ea-9992-b03e784060b2.png)

Interesting that we are not consistent there? Should we be?

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/PG-migration-testing/issues/20#issuecomment-627640209_

**Comment by campmlc** [comment]
Is there a reason for the discrepancy?

**Comment by Jegelewicz** [comment]
Nope - it just developed that way.

**Comment by sharpphyl** [comment]
I suspect that it was assumed that if you're cloning into an existing name, you want all the metadata and the same higher classification.  

But if you're cloning to a new name, you might prefer to enter all the metadata yourself as some or most of it might change.  I usually bring over the entire classification and seldom clean it as I'd rather not have to reopen the metadata fields, but some might rather start from scratch so they don't miss overwriting everything that changes with the new taxon name.  

I'd be fine with having the option on both clone functions but it's never bothered me that cloning into an existing name assumes you want the entire classification.

**Comment by Jegelewicz** [comment]
> it's never bothered me that cloning into an existing name assumes you want the entire classification.

BUT it also brings over all the metadata fields - it is often unlikely that the source and author will be the same for the new name. I think we need to offer the option for both instances.

**Comment by sharpphyl** [comment]
> I think we need to offer the option for both instances.

That's fine.  Your experience may be quite different from mine.

It would be nice if we could incorporate #1816 and/or #1707 at the same time.

**Comment by dustymc** [comment]
@sharpphyl its definitely easier for me to get everything while I'm working on a form instead of doing it in a bunch of bits and pieces, and probably easier to test as well. I thing we have a fairly impressive backlog. Would you be willing to round all the single-record taxonomy form issues up in one place? Hopefully I'll have a dev server in the near future and can do something about them.

**Comment by sharpphyl** [comment]
@dustymc and @anna-chinn 

Anna, at our taxonomy committee meeting next Wednesday, can we pull together all the single-record issues, prioritize them and perhaps consolidate into one issue for Dusty.  It does make sense to not piecemeal enhancements to the taxon cloning/editing process.

**Comment by Jegelewicz** [comment]
This has been resolved in the taxonomy pages re-do
