### ISSUE TITLE
See everything from this locality at specimen record

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2686]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
I was working with a student and we wanted to find everything collected at the locality of the specimen we were viewing (not logged in). 

** Describe what you're trying to accomplish** 
To do this when logged in, it is a bit of a slog, but I can get there. (Edit localities, find the one I'm interested in and click this
![image](https://user-images.githubusercontent.com/5725767/81994639-847cdd80-9605-11ea-95c5-d5eeba922ec5.png)

I can't see a way to do as a public user except to copy the specific locality, then go search it on the main search page. (Which means you probably need the Higher Geography and Specific Locality). Not sure Joe Public would figure that one out!

**Describe the solution you'd like**
"See all specimens collected in this locality" button would be super cool.
![image](https://user-images.githubusercontent.com/5725767/81994478-34058000-9605-11ea-9a8b-ebc27905054a.png)

**Describe alternatives you've considered**
See above

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
Do you want records that share the same (arbitrary and ever-changing) ID, or those from the same place even if there's a bunch of denormalizing data (locality remarks, elevation units, etc.)? If the latter, what's your tolerance for error - can I round to the nearest meter or light year or do you want exact or ??

**Comment by Jegelewicz** [comment]
I think at first, just everything that share the same locality ID, but others may have a different option. I mean, that's what I get with my round-about logged in option...

**Comment by campmlc** [comment]
Maybe that at a minimum, with possibility of adding within specified range
of coordinates? Eg everything within 10 km of locality A?

**Comment by Jegelewicz** [comment]
Honestly, a link that takes me to this would be good enough for now:
![image](https://user-images.githubusercontent.com/5725767/82063408-abc8be80-9688-11ea-89d5-ce9561b0d982.png)

But I do love the exploratory nature of what @campmlc suggests. We should work toward that eventually.

**Comment by Jegelewicz** [comment]
I don't see an option for it....

**Comment by dustymc** [comment]
Maybe we should get this on today's agenda.

This is done at test, where all issues are implemented (now that I have a test box again). I don't want to see it 500 more times; I need some way to get it out of my way, and it needs closed at some point - not necessarily now. How do we do that?

More importantly, I've got two major changes that should address significant problems waiting in the wings. Normally I'd have already pushed them out, but they're potentially very disruptive if they don't work and I think everyone's seen enough of that already. What should I do; what's our protocol for "releases"?

**Comment by Jegelewicz** [comment]
Check - I thought that might be the case, but no way to know unless I ask...

We can close this, but maybe we just need to add a milestone - awaiting push to prod?

**Comment by dustymc** [comment]
I'm not complaining, I'm begging for guidance! How should we release, especially when it's something critical (like what I'm waiting on now)?

> add a milestone

That mostly works for me, I already use them heavily, but someone somehow would need to clean them up.

**Comment by Jegelewicz** [comment]
I can help with that - but I need you to remove/change milestones when you finish stuff too!
