### ISSUE TITLE
CSV download for Accessions not working

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2688]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Accessions csv download does not work

**To Reproduce**
1. Go to Transactions/Accessions
2. Choose a collection
3. Search
4. Click "download csv"
Nothing happens

**Expected behavior**
the file to download

In test, same task gives 500 internal server error

**Comment by dustymc** [comment]
Details in https://github.com/ArctosDB/PG_DDL/issues/77 would be very useful - as always, specifics are necessary if we're to have any hope of doing anything about the problem.

**Comment by dustymc** [comment]
Marking wontfix - this isn't a bug, it's a lack of resources.
