### ISSUE TITLE
summarize results by formatted scientific name has broken URL to specimens

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#2689]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

If I perform a search as follows 

'see results as' -> 'catalog record summary' with the following fields:

scientific name = Bombus
ID formula = A
species = not null
state= Alaska

Here's a saved search for this http://arctos.database.museum/saved/AKBombus2020

the link to specimens within the results works.

But if I do the following the link to specimen results fails

 see results as' -> 'catalog record summary' -> formatted scientific name

with the following fields:

scientific name = Bombus
ID formula = A
species = not null
state= Alaska

Here's a saved search for this http://arctos.database.museum/saved/AKBombus2020formatted

**To Reproduce**

**Expected behavior**

link to specimens should find specimens

**Screenshots**

** Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label.
medium

**Comment by DerekSikes** [comment]
the URL below (from the saved search) does not work:

https://arctos.database.museum/SpecimenResults.cfm?state_prov=Alaska&scientific_name=Bombus&scientific_name_scope=currentID&species=NOTNULL&taxa_formula=A&scientific_name_match_type=exact&formatted_scientific_name==%3Ci%3EBombus%20flavifrons%3C%2Fi%3E%20Cresson%2C%201863

But this does, returning the correct number of records.

https://arctos.database.museum/SpecimenResults.cfm?state_prov=Alaska&scientific_name=Bombus&scientific_name_scope=currentID&species=NOTNULL&taxa_formula=A&formatted_scientific_name==%3Ci%3EBombus%20flavifrons%3C%2Fi%3E%20Cresson%2C%201863

**Comment by dustymc** [comment]
This isn't a problem in PG, but https://github.com/ArctosDB/PG_DDL/issues/72#issuecomment-620673087 still is.

**Comment by dustymc** [comment]
rebuilt (in lucee) to POST, which works with ~1500 records but not ~3000 - still need tomcat adjustments
