### ISSUE TITLE
Firefox doesn't like Arctos anymore

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2692]
Went to start work this morning and got this

![image](https://user-images.githubusercontent.com/5725767/82221282-08241c00-98dd-11ea-9bc8-e6e08390476b.png)

**Comment by campmlc** [comment]
I noticed that we are suddenly getting booted to the http non-secure site,
even when I deliberately type https. This is also where the arctosdb.org
page pushes to. Related?

**Comment by dustymc** [comment]
@mkoo

**Comment by sharpphyl** [comment]
Same here.  Gave up on Firefox but Chrome is giving me fits about security too.  Can't expand any of the sections.

**Comment by sharpphyl** [comment]
Firefox is working in "test" now but very slowly on some actions.

**Comment by dustymc** [comment]
>very slowly on some actions

How do I replicate?

**Comment by campmlc** [comment]
Is this related?
#2691

**Comment by sharpphyl** [comment]
I just tried Firefox again and it worked fine so that problem seems to be ok but Chrome is giving me this.  I'll be ok with Firefox.

![Screen Shot 2020-05-18 at 8 59 28 AM](https://user-images.githubusercontent.com/15368365/82228103-ea0ee980-98e5-11ea-853c-3098535d0bb1.png)

**Comment by Jegelewicz** [comment]
> very slowly on some actions.

https://github.com/ArctosDB/PG-migration-testing/issues/30

**Comment by Jegelewicz** [comment]
I'm still getting this
![image](https://user-images.githubusercontent.com/5725767/82229641-fa27c880-98e7-11ea-8301-fe6caf0b8d80.png)

but apparently @lin-fred is using Arctos like nothing is going on. I really don't like the idea that some of us are getting essentially locked out while others are just working like nothing is wrong. Apparently, something is wrong.

**Comment by lin-fred** [comment]
Interesting, I am using Chrome

**Comment by dustymc** [comment]
Yes something is wrong, @mkoo can fix it.

**Comment by campmlc** [comment]
I've noticed before that Firefox is much more sensitive to http unsecure
sites than Chrome. In Chrome, you just get a very small notification next
to the url that says "not secure".

**Comment by mkoo** [comment]
SSL certificates are currently being renewed.... there's some lag between
requests and I never now exactly when they expire-- ugh
apologies but in the works

**Comment by wdormann** [comment]
No #2691 is not related.   #2691 is simply the CERT/CC attempting to get through to the ArctosDB folks.

**Comment by sharpphyl** [comment]
I'm still getting this.  I'll use Firefox for tomorrow's Webinar but I want to be sure it's still our certificate and not something I'm doing.  I got this when I followed the link out of my Crome - Gmail box for Arctos Collecting Event Change Notification

![Screen Shot 2020-05-25 at 6 42 16 AM](https://user-images.githubusercontent.com/15368365/82813778-ff8a9300-9e52-11ea-862a-a03cdfc5dd77.png)

**Comment by sharpphyl** [comment]
Actually, I can get the results I need in either Chrome or Firefox but I have to remove the red https:// prior to the link.  

![Screen Shot 2020-05-25 at 6 47 48 AM](https://user-images.githubusercontent.com/15368365/82814101-af600080-9e53-11ea-9b6d-659d012ea80d.png)

Once I do that, I get the results.  

In Firefox, I also get a warning and have to go through the same procedure.

![Screen Shot 2020-05-25 at 6 44 59 AM](https://user-images.githubusercontent.com/15368365/82814138-c0a90d00-9e53-11ea-8889-f6562f478fe8.png)

Is that how it's supposed to work?

**Comment by Jegelewicz** [comment]
> Is that how it's supposed to work?

No, but it is all we have until the security certificate is set up properly. The only way to avoid the security risk screen is to use the unsecure http pages. You should get those pages open before the webinar so that you don't end up at one of the warning screens during the live webinar. I wish I could fix this, but it something Michelle and Chris Jordan have to do and with lockdowns, it is taking longer than usual.

**Comment by sharpphyl** [comment]
I did run through the screens I need for the webinar today and on Firefox I'm able to get to all of them after an initial warning.  Chrome pops up the warning screen with every page so I stopped using it.

**Comment by campmlc** [comment]
Yes, maybe worth mentioning during the webinar that if folks want to follow
along during the webinar they should use Firefox for the time being, and
that tomorrow we are migrating to a new platform which will fix the
security certificate and which will be operational next week.

**Comment by mkoo** [comment]
More specifically too for the future of Arctos:
https://security.googleblog.com/2019/10/no-more-mixed-messages-about-https_3.html


Once we go through this transition, things will be smoother to recertify in
the future as it will all be with TACC instead of two institutions.
Hopefully this will be the last rough patch!

**Comment by Jegelewicz** [comment]
Firefox will still give the security warning - the only way around is to enter the http: site. Once you have done that once, it will stick with it.
