### ISSUE TITLE
Parsing JSON or extracting part columns in search results download

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2693]
See #2534
My concern is whether I can actually get usable data out of the JSON
string. It is a useless field to me if I can't parse it into columns. This
has been my objection to JSON previously. Surely someone knows how to use
it, otherwise what's the point?
If this isn't possible, then we need an alternative, some way of
downloading the specific fields with the regular Arctos specimen results
data. So if I want all part barcodes, or part remarks, I can extract that
into unique columns. Will that be more feasible in PG?
…

**Comment by campmlc** [comment]
From Dusty
My concern is whether I can actually get usable data out of the JSON
string. It is a useless field to me if I can't parse it into columns. This
has been my objection to JSON previously. Surely someone knows how to use
it, otherwise what's the point?
If this isn't possible, then we need an alternative, some way of
downloading the specific fields with the regular Arctos specimen results
data. So if I want all part barcodes, or part remarks, I can extract that
into unique columns. Will that be more feasible in PG?
…

**Comment by campmlc** [comment]
From Dusty
The technology stack has very little to do with the feasibility of munging vertical data into horizontal. #2534 (comment) describes the problem; the source of the data is close to irrelevant.

Part detail used to be a concatenated string. I won't suggest we return to that, but it could be an additional "column" if unstructured data is somehow more desirable. New Issue, I'd need specifics.

**Comment by dustymc** [comment]
Here's some background.

* a record can have any number of parts
* a part can have any number of part attributes

Those add up very quickly; representing each component as columns in a spreadsheet or table is somewhere between weird and impossible.

For various "flat" views (SpecimenResults, DWC) we've always merged them into strings.

Recently I've been pushing strings to formatted and self-documented strings that can be understood by various tools, and that don't have inherent problems with things like telling delimiters from data; JSON.

**Comment by Jegelewicz** [comment]
Can we just get a tool to download parts? Supply a list of GUIDs, get all the parts with each part associated with a GUID. Then we creatively think of a way to get them from vertical to horizontal? (Lookup tables might work - I'd just need to play around with it....)

**Comment by dustymc** [comment]
If you mean one part per row, sure.

Adding attributes to the row would lead back to the original problem.

**Comment by Jegelewicz** [comment]
> Adding attributes to the row would lead back to the original problem.

We could do the same thing but associate the attributes with their part number...

Which makes me wonder - what is this intended to be used for? If it is a backup, that sorta makes sense, otherwise it seems like a lot of work to re-create Arctos.

**Comment by campmlc** [comment]
I critically need to be able to access information that is stored in the
parts barcode and parts remarks columns, yes for back and restore (I lost a
months worth of object tracking with the last crash, which is requiring
pulling samples out of nitrogen to recover), but also because we have don't
have a good model for storing parasite data in host records when parasites
are cataloged as host parts (prior to being switched to parasite cataloged
items). We have thousands of legacy records where the only parasite data is
stored in part remarks.

**Comment by campmlc** [comment]
See #3039

**Comment by ccicero** [comment]
Bringing this to high priority again. If we are to make more use of part attributes, which we are doing, we need a way of downloading and easily viewing those as well as other part details. It's impossible now. I just uploaded a bunch of part attributes (type 'representation') for MVZ:Mamm skulls (most with >1 attribute) and wanted to check the data to make sure it looks ok. Not possible. Anyone interested in those attributes can't view them now in a logical way.

**Comment by campmlc** [comment]
Go to Manage from catalog record results and use parts table download.
Dusty tweaked this for this purpose.

**Comment by campmlc** [comment]
But true this doesn't help general public - or can we make this a public
form?

**Comment by dustymc** [comment]
>viewing...impossible.

You're taking them out of a tool where viewing is possible by downloading! 

<img width="746" alt="Screen Shot 2021-09-02 at 6 19 38 PM" src="https://user-images.githubusercontent.com/5720791/131936282-52fec4dc-2cb9-467c-98b9-45351d332602.png">

That's pretty logical to me, but maybe I'm biased. (https://github.com/ArctosDB/arctos/issues/2131 might make it a little more human-friendly.)

And it's CSV - there must be lots of things that support some sort of logical view, although I don't know of anything out of the box that's as nice as the built-in display

>parts table download...public

Probably not, and the container-junk in that form isn't something I'd be very happy to let the neighbors see. 

* I could do something different with the data in the download, although I don't think there's anything more accessible than JSON at this point.
* I could build some sort of container-free public parts viewer, but
    * it's going to have limitations - there's some limit on the number of columns I can flatten, and
    *  it's going to be denormalized in some way (eg one row per part, like ^^ that), and that'll confuse someone

**Comment by campmlc** [comment]
Csv doesn't work because the columns of multiple records can't be made to
align. Not sortable, not usable.

**Comment by dustymc** [comment]
>Csv doesn't work 

>**out of the box**

CSV (like JSON) is a transport mechanism. What it looks like and whether it's sortable and etc. are up to the tool it's imported into.

**Comment by campmlc** [comment]
Can you provide a program that will parse the JSON into separate aligned
columns? That was the reason for this post, and it has never been resolved.
Without it, JSON is nonfunctional for Arctos downloads.

**Comment by dustymc** [comment]
If you can define "columns" - or about anything else - capable of holding parts data, I can probably stuff it into that.

**Comment by campmlc** [comment]
All parts, barcodes, and attributes separated into columns as they appear
in the bulkloader.

**Comment by ccicero** [comment]
The parts table download is sorta better, but...

1) there are lots of columns that are may not be relevant
2) there are a bunch of columns that I have no idea what the headers mean, e.g., BC7, LBL7, etc.
3) It doesn't include part remarks, just coll_object_remarks
4) it doesn't include attribute remarks, also important if not null

If this is a parts table download, can we just limit it to the parts information (i.e., why include dates?). Loan info can be useful but not in this table necessarily (?). Or if it is, maybe after the core parts data including attributes?

[partFlatDownload.csv](https://github.com/ArctosDB/arctos/files/7102938/partFlatDownload.csv)

**Comment by dustymc** [comment]
Parts data doesn't fit back into the bulkloader, that was much of today's discussion topic.

Everything there was relevant to someone.

BC=barcode, LBL=label - should be documented (or expanded or something) if we keep that form.

>doesn't include part remarks

<img width="225" alt="Screen Shot 2021-09-02 at 7 43 43 PM" src="https://user-images.githubusercontent.com/5720791/131942739-f58eb56e-0384-4f15-9cec-e71596ea1e15.png">

>doesn't include attribute remarks

Correct, this is a very limited view.

I think you need something different - that's possible, might even become public - I need a model into which whatever you want to see can fit.

**Comment by ccicero** [comment]
At the very least, only show columns that are not null. And I think attribute remarks are useful as part of this.

Column headings are cryptic - yes, should be expanded if we keep the form.

**Comment by Jegelewicz** [comment]
> Can you provide a program that will parse the JSON into separate aligned columns? 

try OpenRefine I think it does this pretty well

**Comment by Jegelewicz** [comment]
> need a model into which whatever you want to see can fit.

How about the parts section of an individual record as a start? But for download, the attributes need to be on the same row as the part?

The one thing that will probably never be good for everyone is lining up the "attributes". This is just not easy (or maybe even possible) when every part has a different set of attributes.

**Comment by dustymc** [comment]
>only show columns that are not null.

That would mean it's a nightmare to patch CSV files together. 

It's also the opposite of what this form primarily exists to do, find parts in freezers.

I think there are essentially three paths to this data:

* If you can define some container, I can stuff whatever fits into it. You can't define fully functional flat-at-specimen or flat-at-part containers, but (if I have CPU) maybe we can pull enough of those out to be useful to some users. This is the same calculation as the bulkloader - anything semi-useful is going to involve a LOT of cryptically-named columns, and there are practical and functional limitations on that. We could potentially stuff multiple concepts into single column, but that will make the data less usable. There just aren't any good choices in this, and it would be very expensive, but if someone needs these data and just can't work outside of a spreadsheet then we can try.
* We could provide three files for download - catalog records, parts, and attributes. This is fully-functional and computationally cheap, but of course it involves users figuring out what to do with mostly-normalized data.
* We could do something more with the JSON. We're already paying the CPU costs - it's stashed in FLAT, I can do WHATEVER in specimenresults (there's significant CPU involved, but the user pays for it), and maybe some OpenRefine user can be convinced to work up a how-to.

> parts section of an individual record as a start

Hu?

>for download, the attributes need to be on the same row as the part?

Right this minute that is technically plausible. By the time I write the code, if anyone's doing the things they said they'd do in preservation, it might not be. There will always be limitations on this, it's not sustainable.

>lining up the "attributes".

Not even remotely practical. Anyone who wants to do this NEEDS the normalized attributes download, whether they know it or not. (And the same might be true of anyone who needs anything else - who is it that wants to start their analysis with some giant flat-ish mess that looks good in a spreadsheet?? Arctos has a viewer, there's no need to download for that, anyone doing anything else is very likely to be more happy with clean, simple data - or at least I would be!)
