### ISSUE TITLE
bulkload loan items - duplicate parts

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#2696]
Using the Bulkload Loan Items batch tool, I loaded an item where the specimen has two muscle (frozen) parts. When I try the select "Duplicate Parts? You can pick them" link (http://arctos.database.museum/tools/loanBulkload.cfm?action=pickPart) and click on the "part..." link I get a 'deprecated' error box. 
![image](https://user-images.githubusercontent.com/12507297/82604183-21dd9180-9b71-11ea-838b-c851fc08ccfc.png)

probably can wait until PG

**Comment by acdoll** [comment]
@dustymc I believe the above issue is still a problem. I've been trying to bulkload loan items with only 1 part to avoid this problem, but am now getting this error with one of my .csv's:
_An error occurred while processing this page!
Message: ERROR: more than one row returned by a subquery used as an expression
Detail:
Check the Arctos Handbook for more information on errors.
This message has been logged as 27D143B5-2999-4A0E-A12A87B8FA9494C4 Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue._

Here's the file I was working on
[ItemUpload_B1.1_birdtest.zip](https://github.com/ArctosDB/arctos/files/5052455/ItemUpload_B1.1_birdtest.zip)

**Comment by dustymc** [comment]
merge https://github.com/ArctosDB/arctos/issues/2027
