### ISSUE TITLE
Add GitHub username to Manage Collection

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2698]
The @ArctosDB/arctos-code-table-administrators would like to add the requirement for collections to add at least one GitHub username to the Manage Collection page so that at least one person from each collection is on GitHub.

We would like this field to be "required" so that as long as it remains NULL, the person with manage collection will see a message similar to this every time they log in.

![image](https://user-images.githubusercontent.com/5725767/82613000-886aab80-9b81-11ea-96d8-c4165dfbac26.png)

We hope this will help increase participation in the community.

**Comment by ewommack** [comment]
Hmm sounds reasonable to me. 
Maybe add something about GitHub in the description of what and active Operator is?

**Comment by ccicero** [comment]
Yes, that would be helpful.

**Comment by dustymc** [comment]
I think this is a 2-part request.

1. We need a new value for https://arctos.database.museum/info/ctDocumentation.cfm?table=ctagent_name_type, then
2. I can do stuff with it.

(1) should go through the normal CT path. I'm tempted to suggest something more specific than "github username" - eg we really want them to be watching Arctos activity, not just supplying some random github username that doesn't **do** anything for them. I'm also not fond of an overly-specific value - maybe we just need "...linked to https://github.com/ArctosDB/..." somewhere in the documentation or something.

**Comment by Jegelewicz** [comment]
@Jegelewicz add to code table. Then flip to active development for Dusty.

**Comment by dustymc** [comment]
<img width="1347" alt="Screen Shot 2021-03-03 at 7 28 58 AM" src="https://user-images.githubusercontent.com/5720791/109830223-213f5480-7bf3-11eb-91e8-57b2ac15440c.png">

**Comment by Jegelewicz** [comment]
Thanks!
