### ISSUE TITLE
PG Migration Announcement for May 27-29

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2701]
See #2699
Suggested text for arctosdb.org and  arctos.database.museum.org.  Also put on Arctos banner now.

 Arctos will be offline Wednesday, May 27th at 5pm through Friday, May 29th at 5pm, Arctos for our  move to the new Arctos PostgreSQL. 

You will need to create a new password the first time you log in after May 29. Use the Lost Password function to create a new password the first time you log in after the move.

We appreciate your feedback. Please use the Arctos GitHub Repository (https://github.com/ArctosDB/arctos/issues) for error reporting and troubleshooting during this time.

**Comment by mkoo** [comment]
the banner really doesnt allow for a lot of words!
Is the longer notice posted some where with a url I can use?

**Comment by campmlc** [comment]
Feel free to edit!

**Comment by campmlc** [comment]
We can post the longer version at arctosdb.org?
