### ISSUE TITLE
Attribute - fork length

### ISSUE THREAD

**Issue by fsjmm1** [ArctosDB/arctos#2704]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Goal**
Get a new part named fork length added.

**Context**
It's a measurement frequently taken in our collection with no clear substitute in the existing parts.

**Table**
http://test.arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name

**Value**
fork length

**Definition**
Fork length (FL) is the length of a fish measured from the tip of the snout to the end of the middle caudal fin rays and is used in fishes in which it is difficult to tell where the vertebral column ends.

**Collection type**
Fish

**Attribute data type**
number+units

**Attribute units**
CTLENGTH_UNITS

**Part tissue flag**
no

**Comment by Jegelewicz** [comment]
I think this would be an attribute, not a part name? and belongs in http://arctos.database.museum/info/ctDocumentation.cfm?table=CTATTRIBUTE_TYPE

@ArctosDB/arctos-code-table-administrators any opposition to this measurement term?

**Comment by dustymc** [comment]
How does this differ from "standard length" and "total length"? Clarify that (the existing values need better definitions) and I support this.

**Comment by Jegelewicz** [comment]
/remind me to review definitions of other length parts on Monday.

**Comment by Jegelewicz** [comment]
Before I proceed to add this term, can someone please provide definition for "standard length" (Fish) and how "total length" for fish is measured?

@campmlc @fsjmm1

**Comment by Jegelewicz** [comment]
@dustymc can you tell me who created all of these attributes without definitions? I'd like to assign out this work and it might be easier for someone who added the term to add the definition as well.

**Comment by fsjmm1** [comment]
@Jegelewicz I cannot provide definitions or clarity for standard length and total length when it comes to fish, that should definitely be left to an ichtyologist. I'll ask one of our fish people.

**Comment by campmlc** [comment]
Here is from our Fish collection manager:

Standard Length (SL) is the length of a fish measured from the tip of the
snout to the end of the last vertebra or posterior end of caudal peduncle
Total length (TL) is the length of a fish measured from the tip of the
snout to tip of the longest lobe of caudal fin. Measurement done with
caudal fin lobes compressed and measured at midline.

**Comment by Jegelewicz** [comment]
@campmlc can you also get her thumbs up for the "fork length" attribute and definition above?

**Comment by campmlc** [comment]
Fork length definition is good. It's also considered a more suitable
measurement for those with forked caudal fins.

**Comment by Jegelewicz** [comment]
@dustymc I attempted to add this and it never seemed to complete the process (little dot going back and forth in browser window for ages). It doesn't appear in the table, but I don't want to try again and make a mess...

**Comment by dustymc** [comment]
You shouldn't be able to make a mess from there.

I think I know what you're talking about, I think it's happened to me, but I was never able to pin it down or find a way to make it consistent, and TACC wasn't able to see it. I think the proxy (or browser, or DNS server, or SOMETHING in some network-thing somewhere) sometimes wanders off or falls asleep or something. If you can replicate I'm sure TACC would be interested, if not call it a glitch in the matrix and try again....

**Comment by Jegelewicz** [comment]
Well, this is now happening when I am attempting to log in.

Entered my username and password and 10 minutes later still this:
![image](https://user-images.githubusercontent.com/5725767/83464187-4ec15c80-a42d-11ea-9d5f-3a1bb9e83ccb.png)

**Comment by Jegelewicz** [comment]
done.
