### ISSUE TITLE
Duplicate LSU other id num type

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#2705]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Goal**
reduce duplicate other ID num types

**Context**
Arctos has both 
LSU: Louisiana State University Museum of Natural Science

and 

Louisiana State University, Museum of Natural Science

**Value**
Proposed new value - one or the other, but need to merge whatever they are linked to, right?

**Priority**
Low

**Comment by Jegelewicz** [comment]
Thanks for this! I've put it in the Code Table Admin project.

**Comment by dustymc** [comment]
done
