### ISSUE TITLE
Link Identifiers to agent pages

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2708]
Identifier names are not linked to agent pages:

![image](https://user-images.githubusercontent.com/5725767/83367951-43f6c100-a374-11ea-902c-23824b7c00a6.png)

![image](https://user-images.githubusercontent.com/5725767/83367980-64268000-a374-11ea-931d-317a3c7690b1.png)

Has this always been the case?

**Comment by dustymc** [comment]
Yes - you can check old code at https://github.com/ArctosDB/arctos/blob/master/SpecimenDetail_body.cfm

**Comment by Jegelewicz** [comment]
Man, we need to upgrade that!

**Comment by Jegelewicz** [comment]
YES! Thank you!!!!
