### ISSUE TITLE
Publication link appears a aphiaID

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2709]
I hope I didn't do this when I created this classification, but putting this here in case it is something weird that happened during PG migration. The publication link for this taxon appears as aphiaID.

![image](https://user-images.githubusercontent.com/5725767/83368126-f890e280-a374-11ea-85fd-90f4d6f54da3.png)

If it was just me, this is my reminder to fix it.

**Comment by dustymc** [comment]
```
UAM@ARCTOS> select term_type||'='||term from taxon_term where taxon_name_id=11869622 and source='Arctos';

TERM_TYPE||'='||TERM
------------------------------------------------------------------------------------------------------------------------
nomenclatural_code=ICZN
aphiaid=Lyson et al., 2016
source_authority= Neurankylus torrejonensis Lyson et al., 2016 in GBIF Secretariat (2019). GBIF Backbone Taxonomy. Check
list dataset https://doi.org/10.15468/39omei accessed via GBIF.org on 2020-05-26.

taxon_status=valid
taxon_status=extinct
kingdom=Animalia
phylum=Chordata
class=Reptilia
order=Testudines
family=Neurankylidae
genus=Neurankylus
species=Neurankylus torrejonensis

12 rows selected.
```

**Comment by Jegelewicz** [comment]
So it was me?

**Comment by dustymc** [comment]
All I can say is that it's like that in Oracle.

**Comment by Jegelewicz** [comment]
ID10T user error - I'll fix it as soon as you say it's OK to make changes!

**Comment by dustymc** [comment]
That's certainly my favorite error!

Ya'll tell me - I think everything made it and we're good to fully reopen, but don't want to invest a bunch of work and then we end up rolling back or something crazy either.

**Comment by Jegelewicz** [comment]
Probably won't know till we try!

**Comment by Jegelewicz** [comment]
Fixed
