### ISSUE TITLE
Open specimen results from agent page results in error

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2710]
Selected  from
![image](https://user-images.githubusercontent.com/5725767/83368281-88369100-a375-11ea-8b5f-4dd8f4849298.png)

and got

![image](https://user-images.githubusercontent.com/5725767/83368290-9389bc80-a375-11ea-865b-7a5271f312cc.png)

**Comment by Jegelewicz** [comment]
Tried the top link and got
![image](https://user-images.githubusercontent.com/5725767/83368399-e2375680-a375-11ea-9b28-3e930d191f90.png)

**Comment by dustymc** [comment]
<img width="83" alt="Screen Shot 2020-05-31 at 6 38 21 PM" src="https://user-images.githubusercontent.com/5720791/83368524-ebbcc080-a36d-11ea-93c4-8794085e8757.png">

is https://github.com/ArctosDB/internal/issues/58

Not sure about the second - it's definitely up.
