### ISSUE TITLE
Thumbnail shows on catalog record, not on media details

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2711]
View a record with associated media and see thumbnail

![image](https://user-images.githubusercontent.com/5725767/83369031-288db500-a378-11ea-95e7-dd187247d45f.png)

Click view details and get the bear instead of the thumbnail

![image](https://user-images.githubusercontent.com/5725767/83369005-1449b800-a378-11ea-86fe-704595c006ae.png)

Thumbnail shows on "media details"
![image](https://user-images.githubusercontent.com/5725767/83369078-5541cc80-a378-11ea-8ef2-e21cc73dd48b.png)

**Comment by dustymc** [comment]
LInk?

**Comment by Jegelewicz** [comment]
HMMMM,

Went back and there it is...
https://arctos.database.museum/MediaSearch.cfm?action=search&specimen_id=29045435

Strange....

**Comment by Jegelewicz** [comment]
OK, maybe this is just something in process? Cause I open [this record](https://arctos.database.museum/guid/NMMNH:Paleo:47800) that has media and see:
![image](https://user-images.githubusercontent.com/5725767/83369491-c0d86980-a379-11ea-942b-52ae196fc4bc.png)

but hit the [view details](https://arctos.database.museum/MediaSearch.cfm?action=search&specimen_id=29044949) link and get this:
![image](https://user-images.githubusercontent.com/5725767/83369508-d352a300-a379-11ea-99f3-84a8200919ac.png)

**Comment by Jegelewicz** [comment]
So the thumbnails exist, but don't always show up (yet?).

**Comment by dustymc** [comment]
<img width="371" alt="Screen Shot 2020-05-31 at 7 08 11 PM" src="https://user-images.githubusercontent.com/5720791/83369745-20cb1200-a372-11ea-9e89-2162e5266d2f.png">

Without looking, I'd guess there's an intermittent network lag somewhere - thumbs have to respond in a reasonable amount of time (1s??) or the generic no-thumb is displayed. Let's leave this open in case there's some sort of pattern.

**Comment by krgomez** [comment]
Question - do we need to upload our own thumbnails for media now? I haven't had to upload media in a long time but just uploaded an image and there is no thumbnail.

**Comment by Jegelewicz** [comment]
@krgomez It just takes a while for the thumbnails to be created. If you don'ty find it there in a day or so, check in here.

**Comment by krgomez** [comment]
Okay, thanks for the reply Teresa.

**Comment by AJLinn** [comment]
I'm still having problems with thumbnails generated for media I've uploaded.
Four of the records in this saved search had media uploaded a week ago and they still show "media available" bear.
http://arctos.database.museum/saved/LoonBags
This is a major problem for those of us who rely on thumbnails being visible in search results & catalog record view.

**Comment by dustymc** [comment]
I kicked the thumbnail generator - it should catch up in a couple hours.

/remind me to check back tomorrow
