### ISSUE TITLE
Error trying to add annotation to record

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#2715]
**The bug**
Found a record (https://arctos.database.museum/guid/UTEP:Herb:86797) I wanted to comment on, and when clicking on Comment/Bug report link got an error in the pop-up window:

![Screen Shot 2020-06-01 at 9 32 47 AM](https://user-images.githubusercontent.com/2523089/83430837-3597bc00-a3eb-11ea-89df-17385e6316b2.png)

**Expected behavior**
Cannot add a comment

**Conditions**
Was not logged in

**Comment by dustymc** [comment]
Lucee (or our version of java, or something) hates captcha. I see three possible approaches.

1. Fix our captcha generator. I'm not terribly interested in this, I think it'd be a lot of ongoing work (particularly in a clustered environment) for little benefit.
2. Plug in to https://developers.google.com/recaptcha
3. Implement a super-simple 'captcha' with a string, which I've done for the blacklist removal form. i don't see a lot of evidence of bots trying to break our captcha, I think this is sufficient for our needs, I'll get started unless someone has a compelling reason to fall back to (2).

**Comment by mkoo** [comment]
#2 or #3 work!

**Comment by dustymc** [comment]
<img width="619" alt="Screen Shot 2020-06-01 at 10 01 00 AM" src="https://user-images.githubusercontent.com/5720791/83434189-d5a31480-a3ee-11ea-8a3c-fa6e274a2726.png">

Closing - we can change this to recaptcha if we start getting spam in annotations.
