### ISSUE TITLE
Unable to add thumnails to media

### ISSUE THREAD

**Issue by mlbowser** [ArctosDB/arctos#2717]
**Describe the bug**
Unable to add thumbnails to media.

**To Reproduce**

1. Go to When editing media (URL below).

http://arctos.database.museum/media.cfm?action=edit&media_id=10610339

2. Selected an image file. In this case the file name is "Sikes2020atn.jpg", an 11 kb, 116 x 150 pixel jpg file.

3. Click "Save Edits"

4. See error:

An error occurred while processing this page!

The function [getPartsArray] does not exist in the Object, only the following functions are available: [append,clear,copy,count,delete,duplicate,each,every,filter,find,findKey,findValue,insert,isEmpty,keyArray,keyExists,keyList,keyTranslate,len,map,reduce,some,sort,update].

**Priority**
Priority-Low

**Comment by dustymc** [comment]
Can you attach the thumbnail here please?

See also https://github.com/ArctosDB/documentation-wiki/issues/144

**Comment by mlbowser** [comment]
File attached.

![Sikes2020atn](https://user-images.githubusercontent.com/35932110/83454705-11e36e80-a409-11ea-88ff-660852805cdc.jpg)

**Comment by dustymc** [comment]
Thanks - I see the problem (lucee has deprecated a weird coldfusion function) but I don't have an immediate solution. The error should be slightly less cryptic until I can get to this. Here's a workaround.

<img width="118" alt="Screen Shot 2020-06-01 at 2 55 06 PM" src="https://user-images.githubusercontent.com/5720791/83458809-0481b080-a418-11ea-91a7-d4543e24a53f.png">
<img width="137" alt="Screen Shot 2020-06-01 at 2 55 12 PM" src="https://user-images.githubusercontent.com/5720791/83458822-08adce00-a418-11ea-8998-c8d247038a15.png">
drag/drop/create

<img width="240" alt="Screen Shot 2020-06-01 at 2 55 51 PM" src="https://user-images.githubusercontent.com/5720791/83458830-0cd9eb80-a418-11ea-966d-f8394dc5090d.png">

Copy the media_uri, plug it back into the original as preview_uri, save

https://arctos.database.museum/media/10610339

Then I deleted the original media, which doesn't affect the file.

@ArctosDB/arctos-working-group-officers please prioritize

**Comment by mlbowser** [comment]
Thanks, @dustymc! That workaround will work for me.
