### ISSUE TITLE
Trouble Logging In

### ISSUE THREAD

**Issue by fsjmm1** [ArctosDB/arctos#2721]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I'm unable to login. When I try it says there is a fatal error. I changed my password 29 days ago, so it's not expired. Then, when I click on one of the headers it gives me the fatal error message again but says I'm logged in. Once I am "fake" logged in I can't do anything.

**To Reproduce**
1. Go to 'arctos.database.museum'
2. Click on 'login'

**Expected behavior**
That I can log in and use the database.

**Screenshots**
![Screen Shot 2020-06-02 at 10 48 33 AM](https://user-images.githubusercontent.com/5740708/83553364-eec7c600-a4bf-11ea-99c2-521a87d5046e.png)

Note fatal error message, yet I am logged in according to the upper-right of the window.

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.4
 - Browser: both Chrome (version 83.0.4103.61) and Safari (version 13.1)

**Comment by campmlc** [comment]
Do we need to give this link to everyone? Or put a note on the error
message?

**Comment by dustymc** [comment]
Maybe add a notification to the header-news-thing?

**Comment by campmlc** [comment]
Good idea. I am hesitant to go in there until we separate out all the
dangerous stuff.

**Comment by mkoo** [comment]
Adding reminder and link to the global banner....
