### ISSUE TITLE
microbialite - new part name for ES collections

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#2722]
**Goal**
Catalog fossil material

**Context**
Stromatolites, preserved biofilms, etc. don't necessarily fit into trace fossil - some researchers consider them traces, others do not.

**Table**
http://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name

**Value**
Microbialite

**Definition**
a rock or benthic sedimentary deposit made of carbonate mud that is formed with the mediation of microbes (https://en.wikipedia.org/wiki/Microbialite). Includes stromatolite, thrombolite, algal biscuit, microbial mat, microbially induced sedimentary structures (MISS).

**Collection type**
ES

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
@Jegelewicz

**Comment by Jegelewicz** [comment]
OK, I'm going to again say that I like the Wikipedia link. You will see this in my SPNHC presentation, but the fact that we can point to a really detailed definition of what we mean makes this nice.

We have already started the discussion about [part + description with osteoderms](https://github.com/ArctosDB/arctos/issues/2423#issue-540574494) and think that should be applied here as well.

**Comment by campmlc** [comment]
So would microbialite be used instead of stromatolite? Where would
stromatolite go?

**Comment by Jegelewicz** [comment]
> Where would stromatolite go?

My recommendation is to have part microbialite (definition:a rock or benthic sedimentary deposit made of carbonate mud that is formed with the mediation of microbes (https://en.wikipedia.org/wiki/Microbialite) with the part attribute: microbialite type (definition: terms differentiating microbialites by [...] @Nicole-Ridgwell-NMMNHS will have to help me out here) including stromatolite, thrombolite, algal biscuit, microbial mat, microbially induced sedimentary structures (MISS).

**Comment by dustymc** [comment]
>with the part attribute: microbialite type

I don't think that's wrong, but it's not what I'd do - you're setting up a giant list-of-lists in which nobody'll ever find anything. I'd recommend one "sub-part-name" code table (which exists, https://arctos.database.museum/info/ctDocumentation.cfm?table=CTPART_ATTRIBUTE_PART)

**Comment by Jegelewicz** [comment]
That makes sense, but we need a way to associate it via a part attribute? So right now, I could create the part attribute type "what_do_we_want_this_to_be", but I don't see a way to have the values be restricted to https://arctos.database.museum/info/ctDocumentation.cfm?table=CTPART_ATTRIBUTE_PART

**Comment by dustymc** [comment]
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspec_part_att_att

**Comment by campmlc** [comment]
Where will this be searched through the public and operator search
interfaces? How will the public know to search for "stromatolite" in part
attributes? Is there a way to make these terms come up during a general
search on identification?

**Comment by cefilipek** [comment]
I'm having a problem with giving a small vertical algae fossil in a rock a part name, because none of the current ones really fit; it's not a cast because it's not the full body, but it's also more than a trace fossil. Having names like this would be very helpful. I agree with @campmlc though, how would the public know to search part attributes/for a sub-part (or maybe I'm misunderstanding how a sub-part is used)

**Comment by Jegelewicz** [comment]
@Nicole-Ridgwell-NMMNHS @aklompma what are your thoughts on this?

Currently we have 10 records at NMMNH without parts awaiting resolution of this issue.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
We could go ahead and add microbialite as a separate part and then if we get https://github.com/ArctosDB/arctos/issues/2722#issuecomment-638294503 resolved then we can use the part/part attribute model.

**Comment by Jegelewicz** [comment]
Until we can build an ontology, lets add the actual names of microbialites.

**Comment by Jegelewicz** [comment]
@Nicole-Ridgwell-NMMNHS looking at the parts waiting to be loaded, we would need to add:

algal biscuit - Algal Biscuits are a form of stromatolite, which grow on rocks and are often found rolling loose in the sediments at certain times of year. They occur in water up to 1 m deep, and are primarily formed laminated algal hemispheres of Phormidium hendersonii. https://hoopermuseum.earthsci.carleton.ca/Bermuda/recent/ABIS.HTML

FYI - https://www.youtube.com/watch?v=dYX4Zh_d2nc :-)

microbial mat - a multi-layered sheet of microorganisms, mainly bacteria and archaea, and also just bacterial. Microbial mats grow at interfaces between different types of material, mostly on submerged or moist surfaces, but a few survive in deserts. <a href="https://en.wikipedia.org/wiki/Microbial_mat" target="_blank" class="external">Wikipedia</a>

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
microbially induced sedimentary structures (MISS) needs to be added as well, I have a group of these my next batch of new specimens to add.
definition: primary sedimentary structures formed by the interaction of microbes with sediment and physical agents of erosion, deposition, and transportation ([https://en.wikipedia.org/wiki/Microbially_induced_sedimentary_structure](https://en.wikipedia.org/wiki/Microbially_induced_sedimentary_structure))

**Comment by Jegelewicz** [comment]
all added
