### ISSUE TITLE
Repeated IP blocking today

### ISSUE THREAD

**Issue by krgomez** [ArctosDB/arctos#2724]
**Describe the bug**
While using Arctos today, I am repeatedly getting the "Your IP or organization has been blocked" message. I then complete the form and get a message saying "Your IP has been removed from the blacklist". I hit continue and go back to the Arctos interface. After I try a search I am redirected to the IP blocked message. It's happened about 10 times now.

**To Reproduce**
Follow above steps.

**Desktop (please complete the following information):**
 - MacOS Catalina 10.15.4
 - Firefox 76.0.1

**Comment by dustymc** [comment]
Arctos is now allowing restricted word searches for Operators, but throwing a warning.

<img width="776" alt="Screen Shot 2020-06-02 at 3 20 07 PM" src="https://user-images.githubusercontent.com/5720791/83575564-a5d63880-a4e4-11ea-8e12-5586ef51012e.png">

**Comment by krgomez** [comment]
We have an artist named Douglas Char for which I was trying to view the agent record. Why would I not be allowed to search a word/phrase? That does not make sense to me.
