### ISSUE TITLE
leg - new part name for ES collections

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#2728]
**Goal**
Catalog fossil material

**Context**
Needed particularly for individually preserved fossil arthropod legs. In the code table, we already have:

leg (95% ethanol) - Herp
leg (frozen) - Ento

Since we are planning on moving preservation to attributes anyway, it makes sense to just add leg and they can all get reconciled eventually.

**Table**
http://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name

**Value**
leg

**Definition**
each of the limbs on which an animal walks and stands

**Collection type**
Inv, Ento, ES

**Part tissue flag**
no

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
@Jegelewicz

**Comment by Jegelewicz** [comment]
I am OK with this and we can be pioneers in that we can (if @Nicole-Ridgwell-NMMNHS agrees) put "preservation=fossil" on the legs we catalog.

**Comment by campmlc** [comment]
Arthropod leg?

**Comment by dustymc** [comment]
>Arthropod

And chair!

**Comment by campmlc** [comment]
Ooh, fossil chairs . . .
Sounds good!

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> put "preservation=fossil" on the legs we catalog.

absolutely yes

**Comment by Jegelewicz** [comment]
OK as this part name already exists with preparations included, I have added it to the code table and included definitions that EH collections might find useful too (chairs).
