### ISSUE TITLE
permit issued date

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#2732]
I wonder if 'Issued date' is the correct term, or if we need to just clarify the [documentation](https://handbook.arctosdb.org/documentation/permits.html#issued-date).  I just entered two hunting licenses, both issued in May but they are not valid until July of the year in which they were issued (i.e., purchased). We could just clarify the documentation to say:

The day the permit was issued, or the first day that it is valid. This is an Oracle DATE datatype, not ISO8601; only day-precision is allowed.

If folks are ok with that, I'll make the change to the documentation.

**Comment by campmlc** [comment]
I agree.

**Comment by dustymc** [comment]
Seems reasonable. De-Oracle while you're in there, please.

**Comment by ewommack** [comment]
I think that sounds like a good suggestion.

**Comment by Jegelewicz** [comment]
I like it too.

**Comment by ccicero** [comment]
@dustymc - is it sufficient to say 

This is an PostgreSQL DATE datatype... ?

**Comment by dustymc** [comment]
That's correct, but I'd probably just say DATE.
