### ISSUE TITLE
Add new operator role for banner, new collections forms

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2734]
Currently permissions to edit the Arctos banner and to manage prospective collections are in global admin, which also contains sensitive information on the API etc. Suggest separating these out into one or two additional operator roles. Perhaps there should be a new role of "Member Support" that would encompass tasks like the above, or have two new roles, "Arctos Communications" and "Member Support". Mentors for new collections could be given access to the latter. The Arctos Communications team could have access to the former.

**Comment by mkoo** [comment]
That list of proposed separation looks good to me

**Comment by campmlc** [comment]
Looks good to me also. But I'm not seeing the prospective collections
permissions. What role is that?

**Comment by Jegelewicz** [comment]
> prospective collections permissions. What role is that?

It's that role, just not listed on the page - good catch! What else is like that?

**Comment by dustymc** [comment]
There's now a separate form (same access) in test.

<img width="256" alt="Screen Shot 2020-06-09 at 2 32 06 PM" src="https://user-images.githubusercontent.com/5720791/84203285-0e319680-aa5e-11ea-82cd-aecdd741f81b.png">

**Comment by Jegelewicz** [comment]
Just having it in its own place makes it less scary...

**Comment by dustymc** [comment]
The goals of this were accomplished by changing user management; global_admin can be reserved for global admin things. Closing.
