### ISSUE TITLE
Marked to Load taking a while

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2735]
I was working around in the Tables function yesterday. I could do most things I wanted, but I marked a number of Fish specimens to load at the end of the day, and they are still sitting there. 
<img width="1792" alt="Screen Shot 2020-06-03 at 10 11 39 AM" src="https://user-images.githubusercontent.com/18562884/83660978-c1901c00-a582-11ea-8969-3f18bdac286f.png">

Are we running long for time to get things through still?

_Originally posted by @ewommack in https://github.com/ArctosDB/arctos/issues/2733#issuecomment-638300037_

**Comment by dustymc** [comment]
I had an extra zero in the schedule - turns out those are important! It should be back on track now.

**Comment by ewommack** [comment]
Thanks @dustymc!
They still seem to be sitting there. Perhaps I did not mark them correctly to load?

**Comment by dustymc** [comment]
No they're good, I'm working on moving some stuff from the Lucee scheduler to pg_cron. If you don't mind waiting a bit more I'll use them to test, if you are just let me know and I'll kick the job off. Thanks!

**Comment by ewommack** [comment]
I'm good waiting. 
I'll go feed our dermestids and then skin some birds.

**Comment by dustymc** [comment]
They should be loading now; don't have too much fun playing with the bugs.

**Comment by ewommack** [comment]
I didn't even get to the birds yet and they're all ready up!
