### ISSUE TITLE
Specimen bulkload problem

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2737]
[L-2600_2799.zip](https://github.com/ArctosDB/arctos/files/4718202/L-2600_2799.zip)

There are probably taxon issues in this....

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/arctos/issues/2719#issuecomment-637637398_

**Comment by Jegelewicz** [comment]
@dustymc you loaded this for me earlier this week, but something went wrong.

My csv has this:
![image](https://user-images.githubusercontent.com/5725767/83767415-dd56f900-a63a-11ea-8c2f-7d5dab5befa6.png)

But this was loaded to the specimen:
![image](https://user-images.githubusercontent.com/5725767/83767500-f65faa00-a63a-11ea-90c6-aed3a572d48d.png)

See https://arctos.database.museum/guid/NMMNH:Paleo:25619

**Comment by Jegelewicz** [comment]
Parts still not loaded to them - OK to delete anyway?

**Comment by dustymc** [comment]
Yes, the parts will still be in the parts bulkloader when we get back here (I'm I'm understanding)

**Comment by Jegelewicz** [comment]
Specimen search for the 1,363 records spun for a while, then got this:

![image](https://user-images.githubusercontent.com/5725767/83785533-b0acdc80-a64e-11ea-957c-4682b874d225.png)

**Comment by Jegelewicz** [comment]
Check - removed all extra stuff and it worked.

**Comment by dustymc** [comment]
The bulkloader should be fixed, and the encumbrance-deleter should be happy with bigger lists.

**Comment by Jegelewicz** [comment]
Delete worked

/remind me to attempt reload of specimens on Monday

**Comment by Jegelewicz** [comment]
These loaded on Saturday.

**Comment by campmlc** [comment]
Figure out what happened here.  NMMNHS and BYU localities and collecting events were loaded incorrectly as collecting event 1512330

**Comment by dustymc** [comment]
>what happened 

The loader was broken by incorrectly reusing variables across loops.

**Comment by campmlc** [comment]
APSU and MSB records have been removed from this locality and collecting event
