### ISSUE TITLE
rhizome - new part name for ES and Herb collections

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#2738]
**Goal**
Catalog fossil material

**Context**
Rhizomes are modified subterranean stems, because they are so different from a typical stem, a separate part name is warranted.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name

**Value**
rhizome

**Definition**
A modified subterranean plant stem that sends out roots and shoots from its nodes. (https://en.wikipedia.org/wiki/Rhizome)

**Collection type**
ES, Herb

**Part tissue flag**
no

**Comment by campmlc** [comment]
I support this.

**Comment by Jegelewicz** [comment]
@dperriguey @mvzhuang any objections?

**Comment by mvzhuang** [comment]
no objections here

**Comment by campmlc** [comment]
I still agree.

**Comment by Jegelewicz** [comment]
/remind me to check this on Thursday

**Comment by ebraker** [comment]
Agreed to add this part name

**Comment by Jegelewicz** [comment]
part name added
