### ISSUE TITLE
Customize bulkloader (datatables) results in an error

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#2740]
In the  bulkloader, went to datatables and customize. Got this error:

![image](https://user-images.githubusercontent.com/967275/83804892-b95bdd80-a663-11ea-8ba5-0890992b81d0.png)

**Comment by dustymc** [comment]
Should be fixed. You can always control that under manage/roles.

**Comment by ccicero** [comment]
ok, thanks.
