### ISSUE TITLE
move parts using bulk ID change tool

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#2742]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

trying to move specimens using the bulk ID change tool gives this error:

 CF_SQL_VARCHAR, CF_SQL_VARCHAR, CF_SQL_VARCHAR
Parameter types passed (3): CF_SQL_VARCHAR, CF_SQL_VARCHAR, CF_SQL_VARCHAR
ERROR: function movemanyparttocontainer(character varying, character varying, character varying) does not exist Hint: No function matches the given name and argument types. You might need to add explicit type casts. Position: 15

**To Reproduce**

search on these barcodes: UAM100497714,UAM100497715,UAM100497716,UAM100497704,UAM100497705,

click -> manage -> identification

opens new tab, click on 'whole organism (pinned)' and add C74142 to the field 'Move parts to container barcode' and click 'move selected parts for all listed specimens'

and get error above.

**Expected behavior**

no error, just the parts are moved

**Screenshots**

** Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
fixed
