### ISSUE TITLE
No way to get back to Arctos from Datatable

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2743]
Once you have used the datatable to mark stuff to load, there's no way "back" to the Arctos menu.

![image](https://user-images.githubusercontent.com/5725767/83822392-208e8780-a68e-11ea-928c-620014083595.png)

**Comment by dustymc** [comment]
"old form"

**Comment by Jegelewicz** [comment]
Well that's not very intuitive... could it say "return to Arctos tools" or something like that?

**Comment by dustymc** [comment]
done
