### ISSUE TITLE
Review Loan items not working

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#2744]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

Go to a loan and click 'review loan items' then wait for nothing to happen.

I was trying this two different loans: UAM.2020.010.Ento and UAM.2020.009.Ento

As far as I know this is the only form that lets one find & remove records from loans (which I have to do)

**To Reproduce**

**Expected behavior**

Click 'review loan items' get a list of loan items to review.

**Screenshots**

** Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
rebuilt function getnearestpartbarcode, should work now
