### ISSUE TITLE
Arctosdb.org website updates

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2748]
High Priority to update language for the following:
1) referencing Oracle/CF to Postgres.
         https://arctosdb.org/about/details/system/
2) references for specimen record and search to catalog record and search.
3) Update all general text to include paleo and cultural collections as well as biodiversity.
Please use this issue and project to document changes needed/completed.

**Comment by campmlc** [comment]
From @Jegelewicz 
"Arctos is a web-based system" : It is interesting that I can't find anywhere on arctos.db where we say this explicitly. We probably should.

**Comment by mkoo** [comment]
Got it.

**Comment by campmlc** [comment]
For "de-specimen-ing"
https://arctosdb.org/about/details/ecosystem/

**Comment by mkoo** [comment]
https://arctosdb.org/about/details/system/ --  section on database now reflects recent migration to pg; will update with pg-specific changes as we progress and eventually just get rid of any reference to oracle.

updated references to records:      
https://arctosdb.org/about/details/ecosystem/
https://arctosdb.org/about/
https://arctosdb.org/about/details/taxonomy/
https://arctosdb.org/join-arctos/financial-contributions/
https://arctosdb.org/join-arctos/digitization-projects/

**Comment by Jegelewicz** [comment]
THANKS!!!!!!

**Comment by mkoo** [comment]
main updates completed. File new issues for new updates....
