### ISSUE TITLE
Media searches using labels causes IP to be blocked

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#2749]
**Describe the bug**
Doing a variety of media searches for images from home IP and reliably my IP is blocked if I do a search choosing label:Comments and fill in a value

Happened with and without VPN

**Expected behavior**
I expect to not have my IP blocked!

**Desktop (please complete the following information):**
 - OS: MAC
 - Browser FF
 - 76

**Comment by dustymc** [comment]
I've relaxed the check that got you.

This is not a bug, it's security measures set to extra-paranoid. I'm as always up for better ideas.
