### ISSUE TITLE
Arctos not working in Chrome

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2752]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Something not right with Arctos in Chrome? I know you recommend Firefox, but at least we could previously use Chrome and now it is not working at all . . . 

Search on arctos.database.museum in Chrome 
Get the following weirdness: 
![Screenshot 2020-06-05 13 42 48](https://user-images.githubusercontent.com/14808196/83916488-82a0c880-a732-11ea-8e52-9291667080b2.png)

**Comment by acdoll** [comment]
That looks like the mobile site. Click on the Desktop Site link.

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/2726

**Comment by campmlc** [comment]
Interesting. That is what came up under a google search of a guid. Then
even when I rebooted the computer, it is what showed back up again.
