### ISSUE TITLE
error stopping a record from loading - DMS lat/longs

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#2753]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

I entered a record with DMS lat/long data and filled out all the fields correctly but it fails to load  with this error:

Error and units, datum, and georeference source and protocol must be accompanied by coordinates.

This is sitting in the bulkloader entered by me, ffdss 

**To Reproduce**

**Expected behavior**

**Screenshots**

** Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label.
high

**Comment by DerekSikes** [comment]
I need to load this record so I'm going to delete all the Lat/long data & see if it loads, then add the lat/long data back after it's loaded.

**Comment by dustymc** [comment]
I believe this is fixed; please confirm and close if so.

@ebraker

**Comment by ebraker** [comment]
now I'm getting this?:
function dms_to_string(numeric, numeric, numeric, character, numeric, numeric, numeric, character) does not exist

**Comment by dustymc** [comment]
@ebraker Thanks! I loaded one of your records; let me know if there are any problems or I need to undo that.

**Comment by ebraker** [comment]
All loaded! Thank you!
