### ISSUE TITLE
Bulkload Attribute Failure

### ISSUE THREAD

**Issue by awilkins007** [ArctosDB/arctos#2755]
Any attempt at bulk loading attributes fails to load any records from the .csv file into the form. Column header names and content are all properly formatting and uploading form was functioning normally before lastest update.

**Comment by campmlc** [comment]
Is this still not working?

**Comment by awilkins007** [comment]
Yes, it's still happening. I've tried different spreadsheets and switching computers it will link the spreadsheet in the open screen on the form but when the validation screen comes up nothing has been loaded.

**Comment by campmlc** [comment]
@awilkins007 working on this, please keep checking back

**Comment by dustymc** [comment]
Suspect this is related to https://github.com/ArctosDB/arctos/issues/2720; there's a fix, it needs tested before it can be applied.

**Comment by dustymc** [comment]
Assuming https://github.com/ArctosDB/arctos/issues/2720 fixed - please reopen if not
