### ISSUE TITLE
[CONTACT]

### ISSUE THREAD

**Issue by mgoliver22** [ArctosDB/arctos#2756]
I requested a new password and got the email from Arctos with a temporary one to get back into my account. Typing in my username and the temporary password gave me the message that my account is locked and I need to contact my supervisor. I'm not affiliated with a collection on Arctos anymore though so don't have a supervisor to contact, but would still like to log in to save searches, etc. Thanks for the help!
Arctos username: mgoliver
![Screenshot_2020-06-08 https arctos database museum](https://user-images.githubusercontent.com/66650858/84090629-58fcd100-a9c0-11ea-8b73-ee5b17407a9e.png)

**Comment by campmlc** [comment]
I see that you had uam operator access. In order to reactivate this account, we would have to remove your operator access and convert this account to a public user. Or you could just create a new public account.

**Comment by dustymc** [comment]
@mgoliver you can just create a new account.

@campmlc please don't attempt that - it would muddle specimen edit history.

**Comment by campmlc** [comment]
Add to documentation

**Comment by mgoliver22** [comment]
Awwww ok, I guess I'll make a new account :(
Thank you!
