### ISSUE TITLE
ERROR: NK must be numeric!

### ISSUE THREAD

**Issue by AdrienneRaniszewski** [ArctosDB/arctos#2757]
I am correcting the NEON sampleID in MSB:Mamm:313976. Upon saving, I get the following error: 

ERROR: NK must be numeric! Where: PL/pgSQL function trigger_fct_coll_obj_data_check() line 11 at RAISE.

However the NK IS numeric and I didn't make any changes to the NK anyway. I then tried deleting the NK and re-entering it. no luck. I had to enter it as an "original identifier" to avoid losing the data. MSB:Mamm:313958 is having the same issue. Please advice.

**Comment by dustymc** [comment]
Thanks @AdrienneRaniszewski fixed and patched in.
