### ISSUE TITLE
Auto logout / session expires / trouble logging back in

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#2759]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Sorry if this bug has been described already. It seems like the logout / session expiration is very short in PG. 

**To Reproduce**
I am processing a loan, I moved to my word document loan form (yes, sorry, still using a word version... need help making one in Arctos) and by the time I came back to Arctos I'd gotten kicked out. I tried to log back in and the progress indicator just spins (Chrome) or bounces back and forth (Firefox) like its trying to reload. Seems to be inconsistent whether I can gain operator access to the tabs I had open or whether I have to start totally over.

**Expected behavior**
A slightly longer period of inactivity before your session expires (not sure what it's set to now - i see a "Session expires in 29 minutes" alert next to my login. )

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac OS 10.14.6 
 - Browser [e.g. chrome, safari] Chrome 83.0.4103.61 and Firefox 77.0.1

**Priority**
 Normal

**Comment by campmlc** [comment]
Try opening a new tab if the old one just spins. There is an issue
somewhere.

**Comment by dustymc** [comment]
@AJLinn the shorter sessions are an attempt to mitigate https://github.com/ArctosDB/arctos/issues/2719, which is the weird connection behavior.

**Comment by AJLinn** [comment]
Thanks for the explanation. Guess I'll be more diligent about staying in active mode.

**Comment by dustymc** [comment]
I believe we have a way of adjusting for longer sessions now and could safely bump them back to 90 minutes. Needs prioritized; will require

* ~couple days of rebuilding the PG janitor scripts and monitoring
* changes to application file
* Lucee reboot to push the changes out

**Comment by campmlc** [comment]
Agree with this. But I can wait for higher priority items unless this is
causing problems.

**Comment by Jegelewicz** [comment]
I have to log in about 10 times a day - 30 mins is a bit short, 60 would probably help a lot but it isn't a huge deal.

**Comment by campmlc** [comment]
Let's prioritize to see if we can fix #2994

**Comment by mkoo** [comment]
Is this issue blocking the other issue #2994 or the other way around? unclear to me.
At any rate, I am getting flak from users so wanted to see if we have a compromise as @Jegelewicz  suggested? 60 minutes better than 30 minutes!

**Comment by dustymc** [comment]
>blocking

Mostly unrelated. This issue is session expiration, the other involves the events that reset the timer.

I don't think we particularly need to compromise, other than on the usual convenience vs. security. From what I can see (which may or may not be what I need to see!) we could support significantly longer sessions without plugging the tubes. I just need a number (90 minutes seemed to work OK, but I'm not overly attached either) and a priority.

**Comment by Jegelewicz** [comment]
I'd love 90 minutes - I end up logging in a million times a day.....OK not really, but it's a lot.

**Comment by AJLinn** [comment]
90 minutes would be GREAT! I had got caught a couple times today while cataloging a complicated object! Figured out I could reconnect in a different tab and not interrupt my data entry... thank you!!!

**Comment by Jegelewicz** [comment]
AWG says make it 90 minutes.

**Comment by dustymc** [comment]
App code updated. For next release need to

* rebuild flushIdleConnections as root
* update Lucee admin console
* restart Lucee

Tentatively scheduled for 6PM Pacific Monday 7Dec
