### ISSUE TITLE
Reports Not Working?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2762]
Tried to print a loan header, and got the following error messages:
![Screenshot 2020-06-09 19 19 17](https://user-images.githubusercontent.com/14808196/84216423-b65b5580-aa86-11ea-91ab-03c5da237f4e.png)
![Screenshot 2020-06-09 19 19 13](https://user-images.githubusercontent.com/14808196/84216429-b9eedc80-aa86-11ea-8754-7da6fbcd0c57.png)

Priority: High

**Comment by dustymc** [comment]
The template wasn't there, I'm guessing someone deleted the handler.

Here's an archive of all the reports from the old production server.

[templates.zip](https://github.com/ArctosDB/arctos/files/4755720/templates.zip)

**Comment by campmlc** [comment]
got it.

**Comment by AdrienneRaniszewski** [comment]
Jon and I are having this same problem with MSB_Mamm_loan_invoice. I still see the template in the list of existing reports. And there is a handler, which looks fine when I open it.

**Comment by dustymc** [comment]
>same problem 

I think that's just the SQL needing rewritten, which I've done, but without links and specifics I'm not sure I'm in the right place.

Also please make sure any issues I need to see are open.

**Comment by campmlc** [comment]
Just tried MSB Mamm loan invoice template and it worked.
no report? Manage Reports
<http://reports.arctos.database.museum/reporter/reporter.cfm>Print....
      ABQ_Biopark_Loan (Albuquerque_BioPark_Zoo_Specimens.cfr)
   ala_Label
(alaLabel.cfr)            ALMNH_Loan_Invoice_ES_Work_in_Progress
(ALMNH_Loan_Invoice.cfr)            ASNHC_mamm_small_label
(ASNHC_mamm_small_label.cfr)            ASNHC_mamm_small_label_vial
(ASNHC_mamm_small_label_vial.cfr)            CHAS_annualreport
(CHAS_annualreport.cfr)            CHAS_CabinetContents
(CHAS_CabinetContents.cfr)            CHAS_label_adhesive
(CHAS_label_adhesive.cfr)            CHAS_label_EH (CHAS_label_EH.cfr)
      CHAS_label_ento (CHAS_label_ento.cfr)
CHAS_label_ento_catNumOnly
(CHAS_label_ento_catNumOnly.cfr)            CHAS_label_ento_long_locality
(CHAS_label_ento_long_loc.cfr)            CHAS_label_exhibit
(CHAS_label_exhibit.cfr)            CHAS_label_herb (CHAS_label_herb.cfr)
          CHAS_label_vert (CHAS_label_vert.cfr)
CHAS_label_vertLongNames
(CHAS_label_vertLongNames.cfr)            CHAS_label_vial
(CHAS_label_vial.cfr)            CHAS_loan_header (CHAS_loan_header.cfr)
        CHAS_loan_inventory (CHAS_loan_inventory.cfr)
CHAS_PartStorageLoc
(CHAS_PartStorageLoc.cfr)            CHAS_PartStorageLoc_2
(CHAS_PartStorageLoc_2.cfr)            CHAS_PartStorageLoc_3
(CHAS_PartStorageLoc_3.cfr)            CHAS_tag_front (CHAS_tag_front.cfr)
          Clone_Of_DMNS_Loan_Invoice_15506860038 (DMNS_Loan_Invoice.cfr)
        Clone_Of_MSB_Bird_loan_list_1527554996 (MSB_Bird_loan_list.cfr)
        Clone_Of_MSB_Bird_loan_list_by_catnum_ (MSB_Bird_loan_list.cfr)
        Clone_Of_msb_para_4dram_coll_num_15196
(msb_para_4dram_label_origID2.cfr)
Clone_Of_MSB_Para_4dram_label_NK_15560
(msb_para_4dram_label_NK.cfr)            Clone_Of_MVZ_Herps_70etoh_wcat_1578354
(MVZ_Herps_70etoh_wcat.cfr)            Clone_Of_test_delete_at_will_149860605
(test_delete_at_will.cfr)            Clone_Of_UAM_Mammal_Invoice_Attempt_1_
(UAM_Mammal_Loan_Invoice_Attempt1.cfr)
Clone_Of_uam_mamm_loan_invoice_1425572
(loan_invoice.cfr)            Clone_Of_UMNH_Mamm_Vial_Labels_1576178
(UMNH_Mamm_Vial_Labels.cfr)            Clone_Of_UWBM_Herp_tiss_vial_157374174
(uwbm_tiss_vial.cfr)            DMNS_bird_box_label
(DMNS_bird_skel_label.cfr)            DMNS_Bird_Catalog
(DMNS_bird_catalog.cfr)            DMNS_bird_skin_tags
(DMNS_bird_skin_tags.cfr)            DMNS_bird_skin_tags_back
(DMNS_bird_skin_tags2.cfr)            DMNS_bird_skin_tags_front
(DMNS_bird_skin_tags_front.cfr)            DMNS_bird_small_skel_label
(DMNS_bird_small_skel_label.cfr)            DMNS_bird_tinyvial
(DMNS_bird_tinyvial.cfr)            DMNS_bird_V2_V3 (DMNS_bird_V2_V3.cfr)
          DMNS_Loan_Invoice (DMNS_Loan_Invoice.cfr)
DMNS_mamm_box_label
(DMNS_mamm2_label.cfr)            DMNS_mamm_catalog (DMNS_mamm_catalog.cfr)
          DMNS_mamm_ecto (DMNS_mamm_ecto.cfr)            DMNS_mamm_etoh
(DMNS_mamm_etoh.cfr)            DMNS_mamm_genital
(DMNS_mamm_genital_bone.cfr)            DMNS_mamm_longvial
(DMNS_mamm_longvial.cfr)            DMNS_mamm_short_longvial
(DMNS_mamm_short_longvial.cfr)            DMNS_mamm_skintag
(DMNS_mamm_skintag.cfr)            DMNS_mamm_tinyvial
(DMNS_mamm_tinyvial.cfr)            DMNS_mamm_vial (DMNS_mamm_vial.cfr)
        DMNS_Marine_Invertebrates_By_Species (DMNS_conchology_label.cfr)
        DMNS_Marine_Invertebrates_By_ZC (DMNS_conchology_label.cfr)
    DMNS_Marine_Invertebrates_vial (DMNS_Marine_Inverts_tiny_vial.cfr)
      DMNS_Marine_Invertebrates_vialtest
(DMNS_Marine_Inverts_tiny_vial3.cfr)            dmns_para_4dram_viallabel_1556
(dmns_para_4dram_label.cfr)            DMNS_Para_EtOH (DMNS_Para_EtOH.cfr)
          DMNS_skin_tag_front (DMNS_skin_tag_front.cfr)            DZTB
(DMNS_DZTB.cfr)            DZTH (DMNS_DZTH.cfr)            DZTM
(DMNS_DZTM.cfr)            Mammal_Test (DMNS_mamm2_labelTEST.cfr)
 MSB_bird_large_label (MSB_bird_large_label.cfr)
MSB_Bird_Loan_Header
(MSB_Bird_loan_Header.cfr)            MSB_Bird_loan_list
(MSB_Bird_loan_list.cfr)            MSB_Bird_loan_list_by_catnum
(MSB_Bird_loan_list.cfr)            MSB_bird_small_label
(MSB_bird_small_label.cfr)            MSB_Fish_Loan_header
(MSB_Fish_loan_header.cfr)            MSB_Fish_loan_invoice
(MSB_Fish_loan_invoice.cfr)            MSB_Herp_55isoh_wcat
(MSB_Herps_55isoh_wcat.cfr)            MSB_Herp_Loan_Header
(MSB_Herp_Loan_Header.cfr)            MSB_Herp_Loan_Invoice
(MSB_Herp_Loan_Invoice.cfr)            MSB_Herp_Loan_Invoice_20200220
(MSB_Herp_Loan_Invoice_1.cfr)            MSB_Herps_55isoh_TEST
(MSB_Herps_55isoh_wcat_edited.cfr)            MSB_Herp_small_dry_label
(MSB_Herp_small_dry_label.cfr)            MSB_Host_4dram_label
(msb_host_4dram_label.cfr)            msb_host_4dram_origID
(msb_host_4dram_label_origID.cfr)            MSB_Jar_barcode
(MSB_JAR_country_LARGE_barcode.cfr)            MSB_Jar_barcode_TEST
(MSB_JAR_country_LARGE_barcode_TEST.cfr)
MSB_jar_consolidated_country_
(MSB_JAR_consolidated_country_LARGE.cfr)            MSB_Loan_Item_Sticker
(MSB_Loan_Item_Sticker.cfr)            MSB_Mamm_fluid_skin_tag
(MSB_Mamm_fluid_skin_tag.cfr)            MSB_Mamm_fluid_skin_tag_special
(MSB_Mamm_fluid_skin_tag_special.cfr)            MSB_Mamm_jar_label
(MSB_Mamm_jar_label.cfr)            MSB_Mamm_large_label
(MSB_Mamm_large_label.cfr)            MSB_Mamm_large_label_wolf
(MSB_Mamm_large_label_wolf.cfr)            MSB_Mamm_loan_invoice
(MSB_Mamm_loan_invoice.cfr)            MSB_Mamm_NEON_hair
(MSB_Mamm_NEON_hair.cfr)            MSB_Mamm_skin_tags
(MSB_Mamm_skin_tags.cfr)            MSB_Mamm_small_label
(MSB_mamm_small_label.cfr)            MSB_Mamm_small_label_special
(MSB_Mamm_small_label_special.cfr)            MSB_Mamm_UIMNH_skin_tags
(MSB_Mamm_UIMNH_skin_tags.cfr)            msb_para_4dram_coll_num
(msb_para_4dram_label_coll_num.cfr)            msb_para_4dram_label2
(msb_para_4dram_label2.cfr)            MSB_Para_4dram_label_4
(msb_para_4dram_label_4.cfr)            MSB_Para_4dram_label_NK
(msb_para_4dram_label_NK.cfr)            msb_para_4dram_label_Sevilleta
(msb_para_4dram_label_Sevilleta.cfr)
MSB_Para_4dram_Original_151967994
(msb_para_4dram_label_original.cfr)            MSB_Para_4dram_Prep
(msb_para_4dram_label_origID.cfr)            msb_para_4dram_viallabel
(msb_para_4dram_label.cfr)            MSB_Para_4ml_prep_coll_NK (-notfound-)
          MSB_Para_loan_header (MSB_Para_loan_header.cfr)
MSB_Para_loan_invoice
(MSB_PARA_loan_invoice.cfr)            MSB_Para_loan_invoice_2
(MSB_Para_loan_invoice_w_coll_num.cfr)            MSB_Para_loan_invoice_3
(MSB_Para_loan_invoice_w_lot_count.cfr)            MSB_Para_loan_invoice_4
(MSB_Para_loan_invoice_w_barcode.cfr)
MSB_Para_loan_invoice_NK_and_host
(MSB_Para_loan_invoice_NK_and_host.cfr)            MSB_Para_OrigID2
(msb_para_4dram_label_origID2.cfr)            MVZ_Annual_Reporter
(MVZAnnualReporterV1.cfr)            MVZ_Fish_100etoh_nocat
(MVZ_Fish_100etoh_nocat.cfr)            MVZ_Fish_100etoh_wcat
(MVZ_Fish_100etoh_wcat.cfr)            MVZ_Fluid_70etoh_nocat
(MVZ_Herps_70etoh_nocat.cfr)            MVZ_Fluid_95etoh_nocat
(MVZ_Herps_95etoh_nocat.cfr)            MVZ_Fluid_formalin_nocat
(MVZ_Herps_formalin_nocat.cfr)            MVZ_Herps_70etoh_wcat
(MVZ_Herps_70etoh_wcat.cfr)            MVZ_Herps_95etoh_wcat
(MVZ_Herps_95etoh_wcat.cfr)            MVZ_Herps_formalin_wcat
(MVZ_Herps_formalin_wcat.cfr)            MVZ_Ledger (mvz_ledger.cfr)
    MVZ_Loan_Header (MVZ_loan_header.cfr)            MVZ_Loan_Invoice
(MVZ_Loan_Invoice.cfr)            MVZ_Loan_Item_Slip
(MVZ_Loan_Item_Slip.cfr)            MVZ_Narrow_Labels_Bird
(MVZ_Narrow_Labels_Birds.cfr)            MVZ_Narrow_Labels_BlankParts
(MVZ_Narrow_Labels_BlankParts.cfr)            MVZ_Narrow_Labels_DryHerp
(MVZ_Narrow_Labels_DryHerp.cfr)            MVZ_Narrow_Labels_Egg
(MVZ_Narrow_Labels_Egg.cfr)            MVZ_Narrow_Labels_Mamm
(MVZ_Narrow_Labels_Mamm.cfr)            MVZ_Ship_Label (MVZ_Ship_Label.cfr)
          MVZ_Wide_Labels_Bird (MVZ_Wide_Labels_Birds.cfr)
MVZ_Wide_Labels_BlankParts
(MVZ_Wide_Labels_BlankParts.cfr)            MVZ_Wide_Labels_DryHerp
(MVZ_Wide_Labels_DryHerp.cfr)            MVZ_Wide_Labels_Egg
(MVZ_Wide_Labels_Egg.cfr)            MVZ_Wide_Labels_Mamm
(MVZ_Wide_Labels_Mamm.cfr)            New_Report_1398797105857
(MSB_Para_loan_header.cfr)            New_Report_1525459580072
(DMNS_mamm_ecto_TEST.cfr)            New_Report_1582214019712
(MSB_Herp_Loan_Invoice_1.cfr)            New_Report_1582591675316
(DRAFT2_MVZ_Fish_100etoh_nocat.cfr)            NMU_Mamm_Loan_Invoice
(NMU_Mamm_Loan_Invoice.cfr)            NMU_Mamm_Loan_Letter
(NMU_Mamm_Loan_Letter.cfr)            NMZ_mamm_vial (NMZ_mamm_vial.cfr)
        ProjectTemplate (ProjectTemplate.cfr)            PublicationTemplate
(PublicationTemplate.cfr)            ship_label (ship_label.cfr)
     shipping_label
(ship_label.cfr)            test_delete_at_will (test_delete_at_will.cfr)
          uam_earth_science_loan (uam_earth_science_loan_II.cfr)
     UAM_ES_Vial
(Earth_Science_vial_labels_III.cfr)            UAM_Mammal_Invoice_Attempt_1
(UAM_Mammal_Loan_Invoice_Attempt1.cfr)            uam_mamm_box
(uam_mamm_box.cfr)            uam_mamm_loan_head (uam_mamm_loan.cfr)
    uam_mamm_loan_invoice (loan_invoice.cfr)            uam_mamm_vial
(uam_mamm_vial.cfr)            UAM_Vial_labels_II
(Earth_Science_vial_labels_II.cfr)            UCM_cat_num_wet_tag
(UCM_Cat_num.cfr)            UCM_fish_single_lot_label
(UCM_fish_single_lot_label.cfr)            UCM_fish_single_lot_LARGE
(UCM_fish_single_lot_LARGE.cfr)            UCM_Herp_consolidated_LARGE
(UCM_Herp_consolidated_LARGE.cfr)            UCM_Herps_consolidated_MEDIUM_
(UCM_Herps_Consolidated_MEDIUM.cfr)            UCM_Herps_single_label
(UCM_Herps_single_label.cfr)            UCM_Jar_consolidated_country_Large
(UCM_JAR_consolidated_country_LARGE.cfr)
UCM_JAR_consolidated_country_SMALL
(UCM_JAR_consolidated_country_SMALL.cfr)
UCM_JAR_consolidated_state_LARGE
(UCM_JAR_consolidated_state_LARGE.cfr)
UCM_JAR_consolidated_state_SMALL
(UCM_JAR_consolidated_state_SMALL.cfr)            UCM_Loan_Header
(UCM_loan_header.cfr)            UCM_loan_invoice (UCM_loan_invoice.cfr)
        UCM_Mamm_consolidated_label (UCM_Mamm_consolidated_label.cfr)
      UCM_Mamm_consolidated_LARGE (UCM_Mamm_consolidated_LARGE_label.cfr)
          UCM_Mamm_consolidated_MEDIUM (UCM_Mamm_Consolidated_MEDIUM.cfr)
          UCM_Mamm_single_label (UCM_Mamm_single_label.cfr)
UCM_Mamm_single_LARGE
(UCM_Mamm_single_LARGE.cfr)            UCM_TC_single_lot_label
(UCM_TC_single_lot_label.cfr)            UCM_TC_single_lot_LARGE
(UCM_TC_single_lot_LARGE.cfr)            UMNH_Herp_Borrow_Header
(UMNH_Herp_Borrow_Header.cfr)            UMNH_Mamm_Box_Labels
(UMNH_Mamm_Box_Labels.cfr)            UMNH_Mamm_Vial_Labels
(UMNH_Mamm_Vial_Labels.cfr)            UMNH_test_Mamm_loan_invoice_1549661
(MSB_Mamm_loan_invoice.cfr)            UMNH_VZ_Loan_Header
(UMNH_Herp_Loan_Header.cfr)            UNM_ES_label_1 (UNM_ES_test_2.cfr)
          UNM_ES_test (DMNS_conchology_label.cfr)
UTEP_Inv_labels_test
(DMNS_conchology_label.cfr)            UTEP_Loan_Header
(UTEP_Loan_Header.cfr)            UTEP_Loan_Invoice (UTEP_Loan_Invoice.cfr)
          UTEP_Loan_Invoice_ES (UTEP_Loan_Invoice.cfr)
UTEP_shipping_label_1503346808619
(UTEP_ship_label.cfr)            UWBM_Herp_tiss_loan_list
(uwbm_tiss_loan_list.cfr)            UWBM_Herp_tiss_loan_packing_list
(uwbm_herp_tiss_loan_packing_list.cfr)            UWBM_Herp_tiss_vial
(uwbm_tiss_vial.cfr)            UWBM_mammal_tiss_vial
(uwbm_mammal_tiss_vial.cfr)
------------------------------
Report a bug or request support
<https://github.com/ArctosDB/arctos/issues/new?assignees=&labels=contact&template=contact-arctos.md&title=%5BCONTACT%5D>

**Comment by campmlc** [comment]
That isn't what I selected, MSB Mamm loan invoice cfr

**Comment by dustymc** [comment]
@campmlc if there's a problem I don't understand it.

**Comment by AdrienneRaniszewski** [comment]
I can print the loan report that Dusty fixed earlier today. but I just tried a couple others and they don't work. After following the link to the other server, I get the error shown in the attachment.
<img width="1022" alt="Screen Shot 2020-06-16 at 4 49 46 PM" src="https://user-images.githubusercontent.com/23192428/84835707-6a159580-aff1-11ea-972d-bfd78ab614da.png">

**Comment by dustymc** [comment]
I need a handler name if you want me to fix.

If you want to fix it yourself

* DECODE doesn't exist in PG and needs replaced with CASE (you can see an example in the one I fixed), and 
* ``to_number(var)`` doesn't exist and needs replaced with ``var::int`` (or you can try removing that from the ORDER BY - PG has a different sort pattern than Oracle and may natively do what you want)

**Comment by campmlc** [comment]
So does this mean we need to fix the handlers for every report that has
been migrated to PG?

**Comment by AdrienneRaniszewski** [comment]
Here are all our reports. a couple of these I haven't used in a while so I can't guarantee that they were working before the migration. But none of them work now.

MSB_Mamm_fluid_skin_tag
MSB_Mamm_fluid_skin_tag_special
MSB_Mamm_jar_label
MSB_Mamm_large_label
MSB_Mamm_large_label_wolf
MSB_Mamm_NEON_hair
MSB_Mamm_skin_tags
MSB_Mamm_small_label
MSB_Mamm_small_label_special
MSB_Mamm_UIMNH_skin_tags

**Comment by dustymc** [comment]
@campmlc lots of discussion on this in https://github.com/ArctosDB/PG-migration-testing/issues/127 and others

@AdrienneRaniszewski those should all be converted to PG

**Comment by AdrienneRaniszewski** [comment]
Thanks, Dusty. Just ran into another related error though. I searched for specimens and then went up to the "manage..." dropdown and chose "print any report." I get the below error. And it doesn't give me the link to the other server to finish the printing process.

Page /saved/Reports/report_printer.cfm [/usr/local/webroot/saved/Reports/report_printer.cfm] not found
Check the Arctos Handbook for more information on errors.
This message has been logged. Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue.

**Comment by dustymc** [comment]
Fixed for next release - you can just remove /saved from the URL and click enter until I can get that out.

**Comment by AdrienneRaniszewski** [comment]
that worked! thank you.
