### ISSUE TITLE
error feedback

### ISSUE THREAD

**Issue by Mariale12** [ArctosDB/arctos#2765]
Hello, I am receiving this error when I tried to access to Arctos:

FATAL: password authentication failed for user "mcastrof"
Check the Arctos Handbook for more information on errors.

Can you help me with this?

** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **

** Outages should be reported to the contacts listed at https://arctosdb.org/arctos-down/ **

** Arctos Documentation is http://handbook.arctosdb.org/ **

** Learn more about Arctos at https://arctosdb.org/ **

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **

**Comment by campmlc** [comment]
Hello - have you reset your password since the database migration? See the banner instructions at the top of the Search page.

**Comment by Mariale12** [comment]
Hola Mariel! I tried to reset my password but now I account is blocked...?
Can you help me with this?

**Comment by campmlc** [comment]
Can you give me your login?

**Comment by campmlc** [comment]
I think I found it, but if you have operator access I'll need permission
from a curator to unlock. If you just need public access to download, you
can create a new account just for that.

**Comment by Mariale12** [comment]
Hello! I will like to have operator access if that is possible. Thank you!

**Comment by campmlc** [comment]
Sorry, only curators and collection managers of each collection can give
that access, usually to current employees. But you can create a public user
account - and if you have problems with access, it is fine to create a
second account. Most of us have multiple accounts for differing levels of
access.
