### ISSUE TITLE
Edit User Permissions Collection Report Form

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2767]
When I get a collections report email and go to review the collection report of who has access to my collections with the following form:
https://arctos.database.museum/info/collection_report.cfm?guid_prefix=DGR:Bird
There are users who should no longer have access to my collections. What exactly is the process here to remove their access? Or do we not remove it for some reason? 
If the users have locked accounts, I cannot see their existing permissions, or edit to remove their permissions without unlocking them. This is not reasonable. 
Also, we need a way to  remove permissions directly from this report, so I don't have to go to each individual user in roles/permissions.

**Comment by dustymc** [comment]
>What exactly is the process here to remove their access? Or do we not remove it for some reason?

There's an issue requesting documentation somewhere - not in the doc-wiki - this should be addressed there.

>remove their permissions without unlocking them

I'll see what I can do about that.

>way to remove permissions directly from this report, so I don't have to go to each individual user in roles/permissions.

That would limit who can see the report, which mostly defeats the purpose of the report.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/2636
