### ISSUE TITLE
Taxon formula A aff. not loading

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2768]
In the recent bulkload of NMMNH paleo specimens, all identifications using the A aff. formula failed to load with "TAXON_NAME X x aff. not found". Checking the names themselves, they exist in Arctos, so it must be the "aff." that is the problem.

**Comment by dustymc** [comment]
should be fixed

**Comment by Jegelewicz** [comment]
Still doesn't work.

**Comment by dustymc** [comment]
I probably need one I can load in prod then.

**Comment by Jegelewicz** [comment]
[Specimen Records 3000-5399_fixes.zip](https://github.com/ArctosDB/arctos/files/4771212/Specimen.Records.3000-5399_fixes.zip)

**Comment by dustymc** [comment]
Thanks - those should load now.
