### ISSUE TITLE
summarize by 'download csv' not working

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#2770]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

Do a search with the results summarized by sciname,family,order

Click download csv from results and watch spinning ball forever.

**To Reproduce**

**Expected behavior**

**Screenshots**

** Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
Should be patched, closing, need to make sure https://github.com/ArctosDB/arctos/issues/915#issuecomment-643440844 doesn't re-break
