### ISSUE TITLE
Bulkloading records with sensitive data

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#2772]
Is it possible to bulkload records and immediately apply an encumbrance? I ask in preparation for the migration of the UA:Paleo data. They will want to have coordinate information encumbered. As far as I can tell, there isn't an obvious way to do this given what is in the bulkloader template. I assume each encumbrance we create is assigned some kind of identifier number, but I can't see that identifier anywhere. Can we get access to that encumbrance identifier and can we add that as an option to the bulkloader to encumber records in the bulkloading process?
I'd love to hear how other incoming collections have handled this. 

There are probably a number of things about encumbrances I don't understand, but something that is concerning me now:
If two records share the same locality and I add one of them to an encumbrance to hide the coordinates (say that species was added to endangered species list), I can just search on that locality and pull the coordinates off the other record. The only way I see to deal with this would be to clone the locality and change to specific locality to obscure the details to prevent finding those coords from the related specimens. But then specimens can't share a collecting event or be related through 'collected with'. Is it possible to attach the encumbrance to a locality? Is that a bad idea?

**Comment by dustymc** [comment]
>possible to bulkload records and immediately apply an encumbrance? 

No. I think there's a very old issue somewhere, but it's never been implemented.

>possible to attach the encumbrance to a locality

The best way to encumber a locality is via the geology attribute "access." (It'll get migrated to a less-dangly place soon.) That masks the entire locality stack; you can add more specimen-events if you'd like to share some data.

**Comment by campmlc** [comment]
We should have a discussion or even better a committee to discuss sensitive
data. There are a lot of angles to this that need to be considered, rather
than tackling one at a time.

**Comment by Jegelewicz** [comment]
@acdoll I can let you know all about this:

> The best way to encumber a locality is via the geology attribute "access." (It'll get migrated to a less-dangly place soon.) That masks the entire locality stack; you can add more specimen-events if you'd like to share some data.

It is what we are doing at NMMNH. See also http://handbook.arctosdb.org/how_to/How-to-Encumber-Locality.html#encumbering-locality

**Comment by campmlc** [comment]
But that doesn't work for masking entire records, which will have to be
loaded first and then encumbered. But they shouldn't be visible to public
for 24 hrs anyway, if that is still in practice.

**Comment by dustymc** [comment]
Correct, there are two things here

* immediately/preemptively applying encumbrances
* hiding locality information

The 24 hours thing is a "usually within..." **NOT** "at least..." value. Assume anything you upload will immediately be processed, made available, and picked up by search engines and spambots. That's *probably* not true, but it's a safe viewpoint.

**Comment by dustymc** [comment]
Merge-->https://github.com/ArctosDB/arctos/issues/703
