### ISSUE TITLE
Known Catalog Number Gaps

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#2774]
http://arctos.database.museum/tools/findGap.cfm

Can we add a **Known_Gap?** (**Gap_Reviewed?**) field to the catalog number gap tool results page where we can indicate where known gaps occur? Simple Y/N or checkbox would do, and an accompanying Remarks field would be useful.

We have several number gaps in our early catalog series due to shared cross-discipline ledgers (fishes and herps, and birds and mammals respectively) before each collection split off into their own number series. Also the usual mix of numbering errors and unused "reserved" numbers. It would be great if we could annotate these gaps as being known/reviewed with likely no further action needed vs. others where we've simply skipped databasing records in error, and need to go back and capture these records at some point.

**Comment by dustymc** [comment]
The tool is fully dynamic; this would require something new. "Empty" (and potentially encumbered) catalog records would do it, and I'm not sure there's any other defensible approach - two lists of catalog numbers just doesn't seem tenable.
