### ISSUE TITLE
Batch accession editing tool

### ISSUE THREAD

**Issue by anna-chinn** [ArctosDB/arctos#2775]
I was just trying to manage specimen-accession relationships from the search results page via this drop down tool:
![Untitled2](https://user-images.githubusercontent.com/40321380/84450972-547e2580-ac17-11ea-995d-11dde4612f51.png)

and got this error:
![Untitled1](https://user-images.githubusercontent.com/40321380/84450982-59db7000-ac17-11ea-8a8b-d1c5af6c3c6b.png)

I'm fairly sure that this is a bug and not just a permissions issue- I've used this tool before.

**Comment by dustymc** [comment]
I believe I just accidentally fixed this via https://github.com/ArctosDB/arctos/issues/915, please confirm and close if so.

**Comment by anna-chinn** [comment]
It worked! Thanks.
