### ISSUE TITLE
Edit Accession sees non-print characters, makes whole form blank

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#2776]
**Describe the bug**
I opened an accession from 2018 to make some edits. Error messages pop up because of non printing characters in both remark and nature of collection. Says it will put in [NOPRINT] in place of them. After hitting OK on the two popups, the boxes are BLANK!  Fortunately, I just exited. Nothing changed since I did not save. I also just opened the accession, no typing in the boxes, and hit save and same problem. 

**To Reproduce**
1. Go to MVZ Accession 15415
2. Click on Save Change without even editing it. 
3. See popups
4. See screens go blank.

**Expected behavior**
Should see [NOPRINT] where there is offending text, not go blank. 

**Screenshots**
See attached.

**Desktop (please complete the following information):**
 - MAc OS:
 - Chrome
 - Version 83.0.4103.61

**Priority**
High. I cannot do my job with this problem. 
<img width="880" alt="Screen Shot 2020-06-12 at 9 12 21 AM" src="https://user-images.githubusercontent.com/5749672/84524305-9dbd8c00-ac8e-11ea-8b7a-913e04d97dc3.png">
<img width="968" alt="Screen Shot 2020-06-12 at 9 12 09 AM" src="https://user-images.githubusercontent.com/5749672/84524317-a0b87c80-ac8e-11ea-9bc0-d052190c2de8.png">
<img width="924" alt="Screen Shot 2020-06-12 at 9 11 51 AM" src="https://user-images.githubusercontent.com/5749672/84524320-a31ad680-ac8e-11ea-9ac5-a87c15d73e45.png">

**Comment by dustymc** [comment]
Thanks, I disabled that in prod, I'll try to get a fix in the next release.

**Comment by dustymc** [comment]
Code updated in test. Nonprinting characters in transaction fields should be caught; submitting should mark illegal characters, return an error message, and abort submission.

**Comment by cjconroy** [comment]
I look forward to testing it. When is the next release?

**Comment by dustymc** [comment]
>When is the next release?

https://github.com/ArctosDB/arctos/issues/2769

**Comment by dustymc** [comment]
>When is the next release?

About 2 minutes ago....
