### ISSUE TITLE
collection customization

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#2778]
https://github.com/ArctosDB/arctos/issues/2683 (blocking https://github.com/ArctosDB/arctos/issues/2651) seems to have a requirement to maintain some level of customization.

 Arctos currently supports two methods of customizing:

* CSS sheets
* Some options in manage_collection

CSS sheets are easy; I'm confident that I can incorporate them into "portals" (that are just pre-selected collections). The thing in manage collection is neither simple nor portable.

Strongly suggest we convert everything to CSS. I should be able to generate CSS for existing collections from the manage collection customizations; this isn't necessarily disruptive.

Going forward, should we use the manage collection customization form as a CSS generator, or remove that and simply provide a CSS template and help/guidance as necessary?

I'm marking this high priority because of the blocking.

**Comment by mkoo** [comment]
CSS sounds dreamily!

**Comment by dustymc** [comment]
1) See https://github.com/ArctosDB/arctos/issues/2683 - I took a very different path to getting rid of the kludgy parts of portals, this is no longer a blocker
2) The current customization sets links and such, which isn't something CSS can readily handle.

Abandoning this; customization can still involve CSS but there's no longer a compelling reason to allow only CSS.
