### ISSUE TITLE
Downloading catalog records not working

### ISSUE THREAD

**Issue by Hyacynthus** [ArctosDB/arctos#2779]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

_.CSV files of downloaded catalog records are empty, but contain the expected number of rows. This is an issue regardless of looking up records by species or through catalog record summaries._

**To Reproduce**

_1. Do a catalog search. For example, any "Falco peregrinus" tissues at the MVZ._
_2. Under the dropdown menu for "Tools: Map, Customize, or download", select "Download"._
_3. Open resulting .csv file._
_4. Be sad because it's empty. The file has the correct number of rows though._

**Expected behavior**
_Populated .csv file with the catalog records of interest_

**Screenshots**

** Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] _iOS_
 - Browser [e.g. chrome, safari] _Both Safari and Chrome_

**Additional context**

_This is an issue across two browsers (Safari and Chrome) and multiple users (myself and a colleague who replicated the issue on their computer)._

**Priority**
Please assign a priority-label.

**Comment by mkoo** [comment]
OK just tried to download in a few other ways too:

1) download for bulkloading - **does not work**
2) Map in BerkeleyMapper then download - *works!* (there's your temporary workaround, @Hyacynthus)

**Comment by dustymc** [comment]
Standard download should be fixed. The special downloads under manage need checked.

**Comment by dustymc** [comment]
Closing this; everything seems to work, although https://github.com/ArctosDB/arctos/issues/2802 often prevents completion.
