### ISSUE TITLE
download csv for found set not working

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#2780]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

Search, get results, click menu to download results, get csv with no data! I need this asap, thanks!

**To Reproduce**

**Expected behavior**

**Screenshots**

** Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
Duplicate of https://github.com/ArctosDB/arctos/issues/2779; I'm working on it.
