### ISSUE TITLE
Show/Hide Search Terms broken

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2781]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Show/Hide Search Terms Table at top of Search results does not appear; instead, get error:
An error occurred: variable [TABLE_NAME] doesn't exist

**To Reproduce**
1. Search on something
2. See Specimen Results
3.  See error

**Expected behavior**

**Screenshots**

** Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
fxd
