### ISSUE TITLE
Error on adding part

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2782]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Go to Specimen Record, Edit Parts, Add Part. Attempt to add tissue (frozen) with disposition on loan.
Get error.

![Screenshot 2020-06-13 17 21 36](https://user-images.githubusercontent.com/14808196/84581098-a1d6d000-ad9a-11ea-935e-455766cf9001.png)

**Comment by campmlc** [comment]
Same error on adding identifier to specimen record.

**Comment by campmlc** [comment]
Error on adding specimens remarks; but can add part remarks

**Comment by dustymc** [comment]
Your environment isn't set up correctly - could be #2651, I'd guess it's somehow related to #2719 (comment). It's definitely not those forms.

**Comment by campmlc** [comment]
related to #2793 ? similar message
