### ISSUE TITLE
Error searching for Taxon Name

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2783]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Search on "Nematoda" - get:
Taxonomy Search Results
Search terms:
scientific_name STARTS WITH Nematoda
4 results - click results for more information.
Show Metadata
Nematoda
Nematodactylus
Nematodactylus boopis
Nematodactylus flexipes

Click on Nematoda - no content appears
Same response for synonym Nemata

**Comment by campmlc** [comment]
![Screenshot 2020-06-13 17 38 43](https://user-images.githubusercontent.com/14808196/84581316-478b3e80-ad9d-11ea-9017-188731a9ea52.png)

**Comment by dustymc** [comment]
can't replicate, suspect https://github.com/ArctosDB/arctos/issues/2719
