### ISSUE TITLE
Set Loaded to Delete Not Working?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2785]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Setting Loaded to Delete does not delete record from bulkloader

**Priority**
Please assign a priority-label.
High

**Comment by campmlc** [comment]
This is a problem in that every time I enter a new record, the DELETE record which should go away not only stays but gets converted back to Waiting Approval.

**Comment by campmlc** [comment]
When the DELETE record is in the bulkloader, since it won't go away, even if there are other records in the bulkloader, if I choose Data Entry go to last record entered, it is the DELETE record that pops up. If I select it as a template to create a new record, the DELETE goes away in load, and it reverts back to waiting approval. I need this to go away,  please.

**Comment by dustymc** [comment]
fixed

**Comment by campmlc** [comment]
#2782 #2793
