### ISSUE TITLE
Error on editing part attributes

### ISSUE THREAD

**Issue by anna-chinn** [ArctosDB/arctos#2786]
Trying to update the part location's determined date from the future to today for the frozen tissue of this specimen: https://arctos.database.museum/guid/CHAS:Mamm:2019.11.2

Got this error:
<img width="907" alt="Screen Shot 2020-06-14 at 11 52 17 AM" src="https://user-images.githubusercontent.com/40321380/84599224-16ab1800-ae36-11ea-927d-d9019b5fe439.png">
> /usr/local/webroot/WEB-INF/lucee/cfclasses/CF_opt_lucee_tomcat_lucee_server_context_library_tag8224/dump_cfc$cf.txt (No such file or directory)

**Comment by dustymc** [comment]
Fixed and patched.
