### ISSUE TITLE
Edit Location from Specimen Record not working

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2787]
![Screenshot 2020-06-14 17 40 36](https://user-images.githubusercontent.com/14808196/84606801-34907100-ae66-11ea-89f1-38f521c20aeb.png)

**Comment by campmlc** [comment]
Doesn't work from Manage Data Find Locality either
![Screenshot 2020-06-14 17 45 15](https://user-images.githubusercontent.com/14808196/84606922-ff385300-ae66-11ea-8c48-4bcd30e56cf9.png)

**Comment by dustymc** [comment]
Your environment isn't set up correctly - could be https://github.com/ArctosDB/arctos/issues/2651, I'd guess it's somehow related to https://github.com/ArctosDB/arctos/issues/2719#issuecomment-644167112. It's definitely not those forms.
