### ISSUE TITLE
Load events file please

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2788]
@dustymc Can you load the attached [specimen events](https://arctos.database.museum/tools/BulkloadSpecimenEvent.cfm) for me? Thanks!
[Research Events 3000_5399.zip](https://github.com/ArctosDB/arctos/files/4780595/Research.Events.3000_5399.zip)

**Comment by Jegelewicz** [comment]
@dustymc I also have this large batch of catalog records.
[L-5400_12345.zip](https://github.com/ArctosDB/arctos/files/4794792/L-5400_12345.zip)

**Comment by dustymc** [comment]
Did you try? Both loaded fine for me.

<img width="173" alt="Screen Shot 2020-06-18 at 7 10 01 AM" src="https://user-images.githubusercontent.com/5720791/85030830-c6340300-b132-11ea-875c-0cffd1444844.png">
arctosprod@arctos>> update cf_temp_specevent set username='jegelewicz' where username='dlm';

<img width="357" alt="Screen Shot 2020-06-18 at 7 11 41 AM" src="https://user-images.githubusercontent.com/5720791/85031006-00050980-b133-11ea-9f49-437eba0b34ab.png">

**Comment by Jegelewicz** [comment]
I did not try - I can try with the events that go with the second batch of records...

**Comment by Jegelewicz** [comment]
Oh wait - so you didn't load them? I don't see them in Browse and Edit....

**Comment by dustymc** [comment]
They're in the staging area - https://arctos.database.museum/Bulkloader/BulkloadSpecimens.cfm

**Comment by Jegelewicz** [comment]
Can we do the same thing we did before? You take out the ones that have issues and send them to me so I can put the rest in the bulkloader?

**Comment by Jegelewicz** [comment]
I had to reload the events and it worked!

The records you loaded disappeared from the staging table, but never appeared in the bulkloader - before I attempt to load them myself, just want to make sure you don't have them stashed somewhere they will cause trouble.

**Comment by Jegelewicz** [comment]
Events loaded and validated. Got this as events were loading

![image](https://user-images.githubusercontent.com/5725767/85136117-64d86680-b1fc-11ea-8c3f-fa9853760398.png)

Unable to finish loading

**Comment by dustymc** [comment]
>stashed

```
\d: extra argument ";" ignored
arctosprod@arctos>> select username, count(*) from cf_temp_specevent group by username;
   username   | count 
--------------+-------
 jegelewicz   | 14602
 diannakrejsa |     3
(2 rows)

```

The error should be fixed.

**Comment by Jegelewicz** [comment]
@dustymc with regard to stashed - I was talking about these. https://github.com/ArctosDB/arctos/issues/2788#issuecomment-645587038

**Comment by Jegelewicz** [comment]
New error

![image](https://user-images.githubusercontent.com/5725767/85148602-90178180-b20d-11ea-9656-a0966245063f.png)

**Comment by dustymc** [comment]
try again

**Comment by Jegelewicz** [comment]
That worked, thanks!
