### ISSUE TITLE
rename blacklist, whitelist

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#2789]
This has been on my mind for awhile.... I'd like to propose to rename our ```blacklist``` to "blocklist" and ```whitelist``` to "allowlist" following several other prominent code efforts to neutralize commonplace terms which reinforce inherent biases. (see https://9to5google.com/2020/06/12/google-android-chrome-blacklist-blocklist-more-inclusive/)

Plus the added benefit is that it is more descriptive of what those terms actually are!

Simple or not, like our move away from the term "Specimen" (and I'm tagging this similarly), incremental changes to an end goal?!

**Comment by campmlc** [comment]
I support this.

**Comment by Jegelewicz** [comment]
Absolutely.

**Comment by ewommack** [comment]
Sounds good to me

**Comment by dustymc** [comment]
I need to rearrange some blocklist stuff to better deal with a multi-node environment, I'll clean up what I can while in there, the rest just needs prioritized. Some of what I probably won't get immediately (unless someone wants to prioritize this above current tasks) will be fairly simple UI work, some will require significant structural refactoring.

**Comment by dustymc** [comment]
I have a partially tested way (function blocklist_ip) to greatly simplify block handling, reduce the necessary number of DB connections, and make this all easily accessible from multi-node infrastructure or APIs, but it relies on PG12 functionality and my test box is PG11. I don't want to re-write this twice. 

I'm doing the bare minimum to mostly/hopefully avoid potential write deadlocks for now, will revisit this when I have access to a PG12 test DB.

**Comment by dustymc** [comment]
I've made some changes to how blocks work in test - please click/search WITHOUT LOGGING IN if you get a chance, and let me know details if you manage to block yourself.

**Comment by dustymc** [comment]
We have PG12, this would help with the connection situation, reprioritizing

**Comment by Jegelewicz** [comment]
I cringe a bit every day when I get the blacklist email....

**Comment by ewommack** [comment]
What do we need to do to go forward with the renaming?

**Comment by dustymc** [comment]
I'm working on some structural stuff that will make this a bit more approachable, I thought that would be seamless but it looks like I'm going to need a few hours of down time (I'm going to have to temporarily disable some security policies). You could help schedule that - early next week would be good, assuming nothing unexpected happens in the next couple days. I could probably start mid-afternoon or so, I don't think I'll need an entire day.

**Comment by campmlc** [comment]
Mid-afternoon Tuesday, and we give folks heads up now to prepare? Or later
in week in case of complications.

**Comment by dustymc** [comment]
>Mid-afternoon Tuesday

Works for me

>complications

Don't want to jinx myself at this point, but I don't think that's likely.

**Comment by mkoo** [comment]
I would suggest NOT Tuesday, but rather later in the week, say Thu
afternoon, so if there is extended downtime it bleeds into Friday, low
traffic day. Tues-Wed are the generally the busiest times for Arctos

[image: Firefox_Screenshot_2021-08-05T07-33-05.725Z.png]

**Comment by dustymc** [comment]
Thursday's fine too.

**Comment by Jegelewicz** [comment]
File an Arctos Down issue?

**Comment by dustymc** [comment]
Help?? 1PM Pacific Thursday work for everyone?

**Comment by mkoo** [comment]
Oops sorry I thought this was taken care of. Yes, message needs to go out--
how does this look, D?
Arctos needs to be offline for prioritized updates on Thursday 8/12 from 1
PM PT/ 2 PM MT/ 3 PM CT/ 4 PM ET. We will keep you updated on status and
apologize for the inconvenience

**Comment by ewommack** [comment]
Pick a time zone and list one I would think. It took me way to long to figure out that you were only listing one time there and not the start and stop time.

**Comment by ewommack** [comment]
Arctos needs to be offline for prioritized updates on Thursday 8/12 from 1pm PT. We will keep you updated on status and apologize for the inconvenience
