### ISSUE TITLE
Claim Relationships/Manage Agents error

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2790]
I've gotten this error twice this morning, once on Specimen Results-> Manage-> Agents in an attempt to bulk update agents, and just now in trying to claim checked relationships from
https://arctos.database.museum/tools/BulkloadOtherId.cfm?action=getRecip

![Screenshot 2020-06-15 11 54 52](https://user-images.githubusercontent.com/14808196/84690167-47a34f80-aeff-11ea-8bb6-aa1627f5d103.png)

**Comment by dustymc** [comment]
<img width="374" alt="Screen Shot 2020-06-15 at 11 02 19 AM" src="https://user-images.githubusercontent.com/5720791/84690692-be3c4f00-aef7-11ea-9960-023d323ff10f.png">

**Comment by campmlc** [comment]
But In both cases the tool was only clicked once.

**Comment by Jegelewicz** [comment]
Maybe its open in one of the other million tabs you have open?

**Comment by campmlc** [comment]
Nope. Closed out of browser, reopened, went back to email notification,
clicked once to get list of relationships, clicked once to claim all, got
error.
[image: Screenshot 2020-06-15 13.47.12.png]
[image: Screenshot 2020-06-15 13.47.17.png]

**Comment by campmlc** [comment]
Interestingly, I got to these records from the Relationships autoemail
notification sent yesterday, which takes me to
https://arctos.database.museum/tools/BulkloadOtherId.cfm?action=getRecip
However, when I go to directly to the bulkload identifiers tool in Arctos
and go to Manage Existing Records at
https://arctos.database.museum/tools/BulkloadOtherId.cfm?action=managemystuff
  none
of these show up. ?

 When I click the reciprocal record, the reciprocal has not yet been
applied, so I know I or someone else hasn't already approved these.
Eg
https://arctos.database.museum/guid/MSB:Mamm:285990 and
https://arctos.database.museum/guid/NMMNH:Mamm:6046

**Comment by dustymc** [comment]
I PGified the key, I still don't think that's the problem

>none
of these show up. ?

<img width="511" alt="Screen Shot 2020-06-15 at 1 20 48 PM" src="https://user-images.githubusercontent.com/5720791/84702172-0fa20980-af0b-11ea-86b7-a571d9a09d36.png">

>someone else 
```
arctosprod@arctos>> select *  from cf_temp_oids where new_other_id_number='6046';
    key    | collection_object_id | guid_prefix | existing_other_id_type | existing_other_id_number | new_other_id_type | new_other_id_number | new_other_id_references |       status       | username 
-----------+----------------------+-------------+------------------------+--------------------------+-------------------+---------------------+-------------------------+--------------------+----------
 276447262 |                      | MSB:Mamm    | catalog number         | 285990                   | NMMNH:Mamm        | 6046                | same individual as      | claimed reciprocal | JLDUNNUM
(1 row)

Time: 2.061 ms
```

**Comment by jldunnum** [comment]
I tried to claim and approve this series of same individual records a while back and had the same issue.

______________________________________________________________

Jonathan L. Dunnum Ph.D.
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by campmlc** [comment]
This would have been right before the crash. Somehow Arctos thinks they
were approved already but the data were lost?
