### ISSUE TITLE
I am having to renew my password every time I log in.

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/arctos#2792]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

** Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by Jegelewicz** [comment]
@mbprondzinski Is this happening daily? How many times in the past few days?

**Comment by mbprondzinski** [comment]
I’m not in it everyday, but once I try to re-enter I keep seeing Milt Ward’s login on my computer!  I’m not sure what the problem is, but when I delete his login and try mine (it should be saved in Last Pass) it tells me I’m illegal.

**Comment by campmlc** [comment]
Perhaps your browser is saving his settings? Try clearing your cache or
using a different browser?

**Comment by mbprondzinski** [comment]
Thank, Mariel.  I think I got rid of Milt (!)  Fingers crossed it will remember me the next time I sign in!
