### ISSUE TITLE
Error on merging duplicate localities

### ISSUE THREAD

**Issue by anna-chinn** [ArctosDB/arctos#2793]
Trying to merge this locality with its duplicate (locality_id = 11147300): https://arctos.database.museum/duplicateLocality.cfm?locality_id=11147301

and getting this error:
<img width="1246" alt="Screen Shot 2020-06-15 at 2 36 29 PM" src="https://user-images.githubusercontent.com/40321380/84698565-a1af0f80-af15-11ea-9247-6ea438f3b3a7.png">

**Comment by dustymc** [comment]
fixed
