### ISSUE TITLE
Taxon name does not display classification in specimen record

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2795]
I bulkloaded a genus  name - it does not appear we have a way to designate ID formula via the bulkloader, so I could not use A sp. 
In the specimen record, no classification shows up, despite there being a classification in Arctos.
This is also a homonym.
Something else I should have done? A way to designate taxon rank/ID/ID formula in the bulkloader?

**Comment by campmlc** [comment]
![image](https://user-images.githubusercontent.com/14808196/84710522-99f56800-af21-11ea-9465-b29a5caeb261.png)

**Comment by Jegelewicz** [comment]
To use A sp., just enter Hymenolepis sp. in TAXON_NAME

The classification usually takes a day or so to show up. If you just added it, check tomorrow to see if it's there.

**Comment by campmlc** [comment]
I just put in Hymenolepis. Did we decide it is OK to use sp?
Thanks for the heads up on the 24 hr lag!

**Comment by Jegelewicz** [comment]
See #1304 

We haven't cleaned this up or really made a decision. I am discontinuing the use of sp. for all new stuff because it confuses aggregators and IMO it's unnecessary.

**Comment by dustymc** [comment]
>confuses aggregators

This is the same situation as https://github.com/ArctosDB/arctos/issues/1444 - it confuses **machines** and so limits what your data are useful for. Aggregators almost certainly understand this sort of thing better than other machines might; anything less-specialized than GBIF is likely to do worse than GBIF in interpreting this.

**Comment by Jegelewicz** [comment]
@campmlc is this resolved?

**Comment by campmlc** [comment]
Yes, both Hymenolepis and Hymenolepis sp. currently exist, but will clean up later.
