### ISSUE TITLE
Order of taxon names in search results

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2797]
A search for "Lopha" at https://arctos.database.museum/taxonomy.cfm gives the following (exact results returned):

Lopha
Lopha angelica
Lopha aucapitanei
Lopha bellaplicata
Lopha blanfordi
Lophacanthus
Lophacanthus rhabdophorus
Lopha chlamydoides
Lophacme
Lophacme digitata
Lophacme incompleta
Lophacme parva
Lopha costata
Lopha cristagalli
Lophactaea
Lophactaea anaglypta
Lophactaea corallina
Lophactaea cristata
Lophactaea eydouxi
Lophactaea fissa
Lophactaea helleri
Lophactaea maculata
Lophactaea maculatus
Lophactaea multicristata
Lophactaea picta
Lophactaea tomentosa
Lophactaea violacea
Lophactis
Lophactis ornata
Lophactis radiata
Lophactis uniflora
Lopha dageensis
Lopha dichotoma
Lopha dieneri
Lopha diluviana
Lopha engelmanni
Lophaeola
Lophaeola inquinata
Lophaetus
Lophaetus occipitalis
Lopha euzebioi
Lopha falcata
Lopha folium
Lopha forgemolli
Lopha frons
Lopha gibsonsmithi
Lopha gregarea
Lopha gregaria
Lopha hyotis
Lophalia
Lophalia auricomis
Lophalia cribricollis
Lophalia cyanicollis
Lophalia prolata
Lophalia quadrivittata
Lophalix
Lophalix bicolor
Lophalix coccinea
Lophallomys
Lophallomys atavus
Lopha lombardi
Lopha longifolium
Lophalticus
Lophalticus kirki
Lophalticus kirkii
Lophalticus kirkii magnusi
Lopha lugubris
Lopha lunata
Lopha mesenterica
Lopha montiscaprilis
Lophamplexus
Lopha murakamii
Lophandra
Lophandra blanda
Lophandra cubica
Lophandra seriphiifolia
Lophanthera
Lophanthera delphiniifolia
Lophanthera hammelii
Lophanthera kunthiana
Lophanthera lactescens
Lophanthera longiflora
Lophanthera longifolia
Lophanthera pendula
Lophanthera spruceana
Lophanthus
Lophanthus adenocladus
Lophanthus allotrius
Lophanthus anisatus
Lophanthus archibaldii
Lophanthus argyi
Lophanthus chinensis
Lophanthus communis
Lophanthus cusickii
Lophanthus cypriani
Lophanthus depauperatus
Lophanthus dschuparensis
Lophanthus elegans
Lophanthus formosanus
Lophanthus hedgei
Lophanthus iranshahrii
Lophanthus krylovi
Lophanthus laxiflorus
Lophanthus lipskyanus
Lophanthus michauxii
Lophanthus multifidus
Lophanthus nepetoides
Lophanthus obtusifolius
Lophanthus occidentalis
Lophanthus ouroumitanensis
Lophanthus oxyodontus
Lophanthus pinetorum
Lophanthus rugosus
Lophanthus scabridifolius
Lophanthus schrenkii
Lophanthus schtschurowskianus
Lophanthus scrophulariaefolius
Lophanthus scrophulariaefolius var. mollis
Lophanthus scrophularicefolius var. mollis
Lophanthus scrophulariifolius
Lophanthus sessilifolius
Lophanthus subnivalis
Lophanthus tibeticus
Lophanthus tomentosus
Lophanthus tschimganicus
Lophanthus urticifolius
Lophanthus varzobicus
Lophanthus virescens
Lopha pahiensis
Lopha panxiensis
Lopha papieri
Lopha poppei
Lopha posjetica
Lopha posjetica beringi
Lopha posjetica newelskyi
Lopha posjetica zawoikoi
Lopha pulligera
Lopha quadriplicata
Lophar
Lopha radiata
Lopharcha
Lopharcha amethystas
Lopharcha angustior
Lopharcha chalcophanes
Lopharcha chionea
Lopharcha conia
Lopharcha cryptacantha
Lopharcha curiosa
Lopharcha deliqua
Lopharcha ditissima
Lopharcha erioptila
Lopharcha halidora
Lopharcha herbaecolor
Lopharcha iriodis
Lopharcha kopeki
Lopharcha maurognoma
Lopharcha orthioterma
Lopharcha psathyra
Lopharcha quinquestriata
Lopharcha rapax
Lopharcha siderota
Lopharina
Lopharis
Lopharis mediterraneus
Lophar miocaenus
Lopha rouxi
Lopharthrum
Lopharthrum cluysenaeri
Lopharthrum comprimens
Lopha simplexa
Lopha solitaria
Lophaspis
Lophaspis hebardi
Lophaspis scabriuscula
Lopha stefaninii
Lophaster
Lophaster abbreviatus
Lophaster antarcticus
Lophaster asiaticus
Lophaster densus
Lophaster furcifer
Lophaster furcilliger
Lophaster furcilliger vexator
Lophaster gaini
Lophaster levinseni
Lophaster marionis
Lophaster pentactis
Lophaster quadrispinus
Lophaster radians
Lophaster stellans
Lophaster stellans marionis
Lophaster stellans stellans
Lophaster suluensis
Lophaster tenuis
Lophaster validus
Lophaster verrilli
Lophaster vexator
Lopha subovata
Lopha syphax
Lopha teranosawensis
Lopha theca
Lophatherum
Lophatherum annulatum
Lophatherum dubium
Lophatherum elatum
Lophatherum geminatum
Lophatherum gracile
Lophatherum gracile var. gracile
Lophatherum humile
Lophatherum japonicum
Lophatherum lehmannii
Lophatherum multiflorum
Lophatherum pilosulum
Lophatherum sinense
Lophatherum zeylanicum
Lopha tissoti
Lopha travisana
Lophauchen
Lophauchen cristatellus
Lopha ungulata
Lopha vulsa
Lopha wulanwulaensis
Lophaxiopsis
Lophaxius
Lophaxius investigatoris
Lophaxius rathbunae
Lophaxius sagamiensis

While I see WHY this is the order, it is not useful. Expect the following:

Lopha
Lopha angelica
Lopha aucapitanei
Lopha bellaplicata
Lopha blanfordi
Lopha chlamydoides
Lopha costata
Lopha cristagalli
Lopha dageensis
Lopha dichotoma
Lopha dieneri
Lopha diluviana
Lopha engelmanni
Lopha euzebioi
Lopha falcata
Lopha folium
Lopha forgemolli
Lopha frons
Lopha gibsonsmithi
Lopha gregarea
Lopha gregaria
Lopha hyotis
Lopha lombardi
Lopha longifolium
Lopha lugubris
Lopha lunata
Lopha mesenterica
Lopha montiscaprilis
Lopha murakamii
Lopha pahiensis
Lopha panxiensis
Lopha papieri
Lopha poppei
Lopha posjetica
Lopha posjetica beringi
Lopha posjetica newelskyi
Lopha posjetica zawoikoi
Lopha pulligera
Lopha quadriplicata
Lopha radiata
Lopha rouxi
Lopha simplexa
Lopha solitaria
Lopha stefaninii
Lopha subovata
Lopha syphax
Lopha teranosawensis
Lopha theca
Lopha tissoti
Lopha travisana
Lopha ungulata
Lopha vulsa
Lopha wulanwulaensis
Lophacanthus
Lophacanthus rhabdophorus
Lophacme
Lophacme digitata
Lophacme incompleta
Lophacme parva
Lophactaea
Lophactaea anaglypta
Lophactaea corallina
Lophactaea cristata
Lophactaea eydouxi
Lophactaea fissa
Lophactaea helleri
Lophactaea maculata
Lophactaea maculatus
Lophactaea multicristata
Lophactaea picta
Lophactaea tomentosa
Lophactaea violacea
Lophactis
Lophactis ornata
Lophactis radiata
Lophactis uniflora
Lophaeola
Lophaeola inquinata
Lophaetus
Lophaetus occipitalis
Lophalia
Lophalia auricomis
Lophalia cribricollis
Lophalia cyanicollis
Lophalia prolata
Lophalia quadrivittata
Lophalix
Lophalix bicolor
Lophalix coccinea
Lophallomys
Lophallomys atavus
Lophalticus
Lophalticus kirki
Lophalticus kirkii
Lophalticus kirkii magnusi
Lophamplexus
Lophandra
Lophandra blanda
Lophandra cubica
Lophandra seriphiifolia
Lophanthera
Lophanthera delphiniifolia
Lophanthera hammelii
Lophanthera kunthiana
Lophanthera lactescens
Lophanthera longiflora
Lophanthera longifolia
Lophanthera pendula
Lophanthera spruceana
Lophanthus
Lophanthus adenocladus
Lophanthus allotrius
Lophanthus anisatus
Lophanthus archibaldii
Lophanthus argyi
Lophanthus chinensis
Lophanthus communis
Lophanthus cusickii
Lophanthus cypriani
Lophanthus depauperatus
Lophanthus dschuparensis
Lophanthus elegans
Lophanthus formosanus
Lophanthus hedgei
Lophanthus iranshahrii
Lophanthus krylovi
Lophanthus laxiflorus
Lophanthus lipskyanus
Lophanthus michauxii
Lophanthus multifidus
Lophanthus nepetoides
Lophanthus obtusifolius
Lophanthus occidentalis
Lophanthus ouroumitanensis
Lophanthus oxyodontus
Lophanthus pinetorum
Lophanthus rugosus
Lophanthus scabridifolius
Lophanthus schrenkii
Lophanthus schtschurowskianus
Lophanthus scrophulariaefolius
Lophanthus scrophulariaefolius var. mollis
Lophanthus scrophularicefolius var. mollis
Lophanthus scrophulariifolius
Lophanthus sessilifolius
Lophanthus subnivalis
Lophanthus tibeticus
Lophanthus tomentosus
Lophanthus tschimganicus
Lophanthus urticifolius
Lophanthus varzobicus
Lophanthus virescens
Lophar
Lophar miocaenus
Lopharcha
Lopharcha amethystas
Lopharcha angustior
Lopharcha chalcophanes
Lopharcha chionea
Lopharcha conia
Lopharcha cryptacantha
Lopharcha curiosa
Lopharcha deliqua
Lopharcha ditissima
Lopharcha erioptila
Lopharcha halidora
Lopharcha herbaecolor
Lopharcha iriodis
Lopharcha kopeki
Lopharcha maurognoma
Lopharcha orthioterma
Lopharcha psathyra
Lopharcha quinquestriata
Lopharcha rapax
Lopharcha siderota
Lopharina
Lopharis
Lopharis mediterraneus
Lopharthrum
Lopharthrum cluysenaeri
Lopharthrum comprimens
Lophaspis
Lophaspis hebardi
Lophaspis scabriuscula
Lophaster
Lophaster abbreviatus
Lophaster antarcticus
Lophaster asiaticus
Lophaster densus
Lophaster furcifer
Lophaster furcilliger
Lophaster furcilliger vexator
Lophaster gaini
Lophaster levinseni
Lophaster marionis
Lophaster pentactis
Lophaster quadrispinus
Lophaster radians
Lophaster stellans
Lophaster stellans marionis
Lophaster stellans stellans
Lophaster suluensis
Lophaster tenuis
Lophaster validus
Lophaster verrilli
Lophaster vexator
Lophatherum
Lophatherum annulatum
Lophatherum dubium
Lophatherum elatum
Lophatherum geminatum
Lophatherum gracile
Lophatherum gracile var. gracile
Lophatherum humile
Lophatherum japonicum
Lophatherum lehmannii
Lophatherum multiflorum
Lophatherum pilosulum
Lophatherum sinense
Lophatherum zeylanicum
Lophauchen
Lophauchen cristatellus
Lophaxiopsis
Lophaxius
Lophaxius investigatoris
Lophaxius rathbunae
Lophaxius sagamiensis

**Comment by dustymc** [comment]
https://unix.stackexchange.com/questions/252419/unexpected-sort-order-in-en-us-utf-8-locale/252426#252426

What you're suggesting is "wrong" (or unexpected, or non-Standard) and doing something non-standard probably comes with some cost which will eventually build up, but PG has had no problem paying for that sort of thing so far.

Test is now sorting that by byte array.
