### ISSUE TITLE
Arctos Report Printer--error executing database query

### ISSUE THREAD

**Issue by diannakrejsa** [ArctosDB/arctos#2800]
**Describe the bug**
Arctos Report Printer is giving an error. I was attempting to run a report to create labels that worked before (maybe it's a postgres transition issue?). 
If a link works: http://reports.arctos.database.museum/reporter/report_printer.cfm
If a screenshot is better: 
![Screen Shot 2020-06-16 at 12 42 02 PM](https://user-images.githubusercontent.com/36166607/84809280-74bf3300-afcf-11ea-8b02-10bc032f8638.png)

**Comment by dustymc** [comment]
I need to know how you got there (eg, search for ... then click ... - what you're seeing could be tied to specific data) and the "Handler Name" of the report you're trying to print.

**Comment by diannakrejsa** [comment]
I searched for ASNHC data (ASNHC:Mamm:19564 works, but I tried a few), clicked Manage>Print Any Report, followed the link to the Arctos Reporter on a different server, selected ASNHC_mamm_small_label_vial, and hit print report.

**Comment by dustymc** [comment]
Perfect, fixed
