### ISSUE TITLE
Rebuild BerkeleyMapper and KML generator

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#2806]
**SABI Goal**
Restore full mapping functionality. Upgrade plugin for mapping and querying records in PostgreSQL. 

**bug**
Unable to download search results as KML (actual dropdown fxn called
```Map Results in Google Maps/ Download for Google Earth```)
Other mapping functions like BerkeleyMapper works fine

**To Reproduce**
get search results and use the Tools menu to Map the above function

Specific error message:

The key [SCH_TABLE_NAME] does not exist.
Check the Arctos Handbook for more information on errors. 

I have workarounds for now but a drag

**Comment by dustymc** [comment]
That's now functional in test.

Suggest we elevate this to  a full rebuild

* change the dropdown to 'more map options'
* make sure everything there works properly
* add 'customize berkeleymapper' functionality for things like color by species (eg, allow options building the XML)

**Comment by Jegelewicz** [comment]
SABI Goal:

Restore full mapping functionality. Upgrade plugin for mapping and querying records in PostgreSQL.

**Comment by mkoo** [comment]
this is fixed in current version
