### ISSUE TITLE
Unable to view Geology Code Table

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#2810]
I'm not sure if this happened during the post-gres move, but the structure of the Chronostratigraphy Geology attributes has gone wonky. Here is a screenshot to show what I mean:

![image](https://user-images.githubusercontent.com/47402809/85056437-74a06e00-b15c-11ea-9022-f81cfdc57154.png)

Every stage/age is duplicated under each stage/age.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
And now the geology attribute code table won't even open for me to view. The browser spends a minute trying to load it and then sends me a 500 Internal Server Error.

**Comment by Jegelewicz** [comment]
@dustymc I hate to bring this up, but we need to add geology attributes so that Nicole can enter new data. I cannot add any terms manually due to the problem Nicole describes above. I have attached a file with the terms she needs if you can add them for us. We really need to get this table sorted out though....
[Geology Bulkload 3.zip](https://github.com/ArctosDB/arctos/files/4852554/Geology.Bulkload.3.zip)

**Comment by dustymc** [comment]
>get this table sorted out

Probably not going to happen without some assistance. I'd rather prune it - https://github.com/ArctosDB/arctos/issues/2498

ERROR:  duplicate key value violates unique constraint "iu_geolattrhier_value"
DETAIL:  Key (attribute_value)=(USGS 6559) already exists.
Time: 6.707 ms
arctosprod@arctos>> select *  from temp_cache.temp_dlm_uptbl where TERM in (select ATTRIBUTE_VALUE from geology_attribute_hierarchy);
       term       |    attribute    | data_entry |                      description                      
------------------+-----------------+------------+-------------------------------------------------------
 Spencer G. Lucas | Site Found By   | yes        | Agent who discovered a collecting site
 USGS 6559        | Site Identifier | yes        | Alphanumeric identifier assigned to a collecting site
 USGS 6564        | Site Identifier | yes        | Alphanumeric identifier assigned to a collecting site
 USGS D7488       | Site Identifier | yes        | Alphanumeric identifier assigned to a collecting site
 USGS D7492       | Site Identifier | yes        | Alphanumeric identifier assigned to a collecting site
(5 rows)

Time: 15.650 ms
arctosprod@arctos>> delete from temp_cache.temp_dlm_uptbl where TERM in (select ATTRIBUTE_VALUE from geology_attribute_hierarchy);
DELETE 5
Time: 13.164 ms
arctosprod@arctos>> 
arctosprod@arctos>> insert into geology_attribute_hierarchy (
INSERT 0 403
Time: 26.183 ms
arctosprod@arctos>>

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Fixed when new locality attributes created.
