### ISSUE TITLE
New error message: Cannot commit when autoCommit is enabled

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#2811]
I attempted to clone a locality and when I went to save the new locality (first image) I got this error message (second image).

![Screen Shot 2020-06-19 at 7 55 03 AM](https://user-images.githubusercontent.com/15368365/85140472-89cfd800-b202-11ea-8dcf-e341cfa6d68e.png)
11150028

![Screen Shot 2020-06-19 at 7 55 17 AM](https://user-images.githubusercontent.com/15368365/85140585-b08e0e80-b202-11ea-95e0-c3bbb85a6180.png)

So I tried to create a new locality (several times) and got the same error message.  The Handbook (which still references Oracle) doesn't include this error message.  Can you advise how to correct it?  

I've been editing locality all morning without any problem until now.

*Mac/Safari

**Comment by dustymc** [comment]
Does it work now?

**Comment by sharpphyl** [comment]
Yes, thank you!!
