### ISSUE TITLE
Selecting genus in single record data entry returns error message but turns field green

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#2814]
We are moving away from using A sp. when the identification goes only to the genus level.  Thus on several entries, I only entered the genus name and selected it from the pop-up.  I then got this error message.  The error message will not go away when you click "ok" so I closed the pop-up and the field had turned green as though it accepted the name.

![Screen Shot 2020-06-21 at 2 08 23 PM](https://user-images.githubusercontent.com/15368365/85236112-18498280-b3d8-11ea-82ea-3cabed49fc71.png)

This has happened several times today whenever I enter only the genus.  Will the genus load accurately?  Can the error message be removed?

Mac/Safari

**Priority**
As long as they are loading correctly, it's a low priority irritation.

**Comment by dustymc** [comment]
form is no longer using JS
