### ISSUE TITLE
Higher classification does not appear with identification field

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#2815]
**Describe the bug**
Yesterday afternoon I uploaded a single catalog record ZC.31936 with the identification Lirobarleeia lirata.  As of this morning, the higher classification that normally appears with in the identification field still has not appeared.

![Screen Shot 2020-06-22 at 9 05 48 AM](https://user-images.githubusercontent.com/15368365/85303616-f697dc00-b467-11ea-8a2d-1fbcb9456a1d.png)

A similar record made before PostGres with the same identification shows the entire higher classification.

![Screen Shot 2020-06-22 at 9 06 03 AM](https://user-images.githubusercontent.com/15368365/85303730-1e873f80-b468-11ea-8a13-df4a5fb37bc6.png)

**Expected behavior**
Usually the entire classification appears as soon as the catalog record is live.  If you search for the taxon name, the results list the correct family, so the data is there, it's just not appearing with the record.

Taxonomy Source:  WoRMS (via Arctos)
Mac/Safari

**Priority**
Medium.

**Comment by dustymc** [comment]
rebuilt the function; should catch up eventually
