### ISSUE TITLE
Lag Time between logging in and Operator Acccess

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2816]
I just logged in to Arctos, and when my browser refreshed,  the bar at top right showed I was logged in under my operator user name, but I had no access to operator tools from the specimen page or any other. It took several minutes of logging out and logging back in again to get my operator permissions to show up.

**Comment by dustymc** [comment]
This is a symptom of https://github.com/ArctosDB/arctos/issues/2719
