### ISSUE TITLE
catalog number format

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#2818]
**Is your feature request related to a problem? Please describe.**

collection.catalog_number_format is hard-coded and poorly documented

**Describe what you're trying to accomplish** 

Normalization

**Describe the solution you'd like**

New code table with values

* integer
* prefix-integer-suffix
* string

**Comment by ccicero** [comment]
@dustymc Correct, use the same values for the form, those are the ones in Manage_Collection now.

**Comment by dustymc** [comment]
Table built and integrated, documentation updated, forms will use this in next release.
