### ISSUE TITLE
Geography and locality pick tables that include "exact"

### ISSUE THREAD

**Issue by jldunnum** [ArctosDB/arctos#2820]
Can we get a tool added to the Geography and locality pick tables that will allow us to restrict the searches? For example if I want to just pick "North America" or "United States" or "New Mexico" it would be great to not have to scroll and search through the massive numbers of other geography that contain those in the hierarchy

** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **

** Outages should be reported to the contacts listed at https://arctosdb.org/arctos-down/ **

** Arctos Documentation is http://handbook.arctosdb.org/ **

** Learn more about Arctos at https://arctosdb.org/ **

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **

**Comment by Jegelewicz** [comment]
See also #2521

**Comment by dustymc** [comment]
Is this a request for "exact" or "... and everything else IS NULL"?

**Comment by Jegelewicz** [comment]
I guess for this one it would mean country = United States? etc. Can't you do that in the picker?

**Comment by jldunnum** [comment]
Not sure exactly what I'm asking for. I just want to be able to select whatever the most minimal geography i'm interested in without wading through everything else that also contains it. For example, I have a specimen to catalog with no data except "United States". I want to go grab that as higher geography but in order to find it I have to scroll to god knows where. It doesn't come up at the top. This comes up at the top North America, Beaufort Sea, United States, Alaska
and is followed by hundreds of others. How do I just find "North America, United States" quickly?
______________________________________________________________

Jonathan L. Dunnum Ph.D.
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by dustymc** [comment]
Thanks, I think I understand the request now, but I'm not sure how to do it.

"after" is pretty dicey/arbitrary and wouldn't be much fun to maintain as components.

Maybe a "starts with/is/contains/**ends with**" option on higher_geog?? That would still work when we decide to add a new term to the table or shuffle the concatenation around again.

**Comment by jldunnum** [comment]
Yeah that might do the trick!

______________________________________________________________

Jonathan L. Dunnum Ph.D.
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by dustymc** [comment]
Done with https://github.com/ArctosDB/arctos/issues/2916 - will go out as that does.

**Comment by Jegelewicz** [comment]
Also need "EXACT" for Locality nickname, please?
