### ISSUE TITLE
error feedback Bulkload Parts 

### ISSUE THREAD

**Issue by cefilipek** [ArctosDB/arctos#2823]
** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **

I clicked on Bulkload Parts to verify and load my parts data and got an error saying it was Not a Condition. I was able to get into it about 10 minutes ago when uploading the CSV, but I accidentally exited the page while waiting for my main records to load and was unable to return.

<img width="1237" alt="Screen Shot 2020-06-23 at 12 44 07 PM" src="https://user-images.githubusercontent.com/56844074/85437014-8c5a6680-b54f-11ea-8e83-5636fd7cd260.png">

**Comment by dustymc** [comment]
@cefilipek I think I see the problem but your data would be very useful to confirm - can you attach please? (You can zip csv to attach.)

**Comment by cefilipek** [comment]
Sure. Here is my csv. The problem is that I cannot even get into the page to look at what I have loaded, let alone verify or upload them to Arctos.

[Extras for Bulkloader Backup Excel File 0010339-0010382.zip](https://github.com/ArctosDB/arctos/files/4821154/Extras.for.Bulkloader.Backup.Excel.File.0010339-0010382.zip)

**Comment by dustymc** [comment]
Oh I see - I think there's a fix patched into production, if that doesn't work I'll sort this out for the next release.

**Comment by cefilipek** [comment]
That worked. Thank you very much!
