### ISSUE TITLE
Parts>>Container

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#2824]
I'm trying to use the batch tool 'Parts>>Containers' to assign barcodes to parts (i.e. placing tissue samples [parts] into cryovials [containers]) and I get the following error:

An error occurred while processing this page!
Message: ERROR: function moveparttocontainer(real, character varying, bigint, character varying, character varying) does not exist 
Hint: No function matches the given name and argument types. You might need to add explicit type casts. Position: 15
Detail: Parameter types passed (5): CF_SQL_FLOAT, CF_SQL_VARCHAR, CF_SQL_BIGINT, CF_SQL_VARCHAR, CF_SQL_VARCHAR

Does this function need to be recreated or is there actually something wrong with what I'm inputting?
[BulkPartContainer_02-26-2020.3a.zip](https://github.com/ArctosDB/arctos/files/4821603/BulkPartContainer_02-26-2020.3a.zip)

**Comment by dustymc** [comment]
Rebuilt for next release, testing would be greatly appreciated.

**Comment by acdoll** [comment]
I tried it really quick and got this error:

An error occurred while processing this page!Message: Error invoking external process
Detail: /usr/local/webroot/temp/excopy_acdoll_20200623060608598_665.sh: line 1: psql: command not found
--
I'll give it another try with some other data.

**Comment by dustymc** [comment]
Blargh, I swapped in another server, doesn't have postgres. I just installed PG on it but the box is old AND weird so I'm not sure - try again?

**Comment by acdoll** [comment]
I just got a chance to test this - seems to work as expected. Thank you @dustymc !
