### ISSUE TITLE
troubling logging in

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#2826]
From my student:

Message: FATAL: role "enielsen" is not permitted to log in

I've checked and her account is unlocked. She probably logged in once several months ago and used the Lost Password PG prompt...

**Comment by campmlc** [comment]
I think that means she needs to follow the link in the banner to reset her
password since the reset yesterday?

**Comment by ebraker** [comment]
She did (I think a couple times)

**Comment by dustymc** [comment]
Try again - I apparently double-locked some users during the migration.

**Comment by ebraker** [comment]
Success! Thank you!

I just LOLed at your github-moji. Nice!

**Comment by dustymc** [comment]
>github-moji

Thanks for it!

**Comment by campmlc** [comment]
cemeyers is still having the same trouble logging in.

**Comment by dustymc** [comment]
cemyers is unlocked
