### ISSUE TITLE
Cannot add Arctos/EZID-generated DOI to a publication

### ISSUE THREAD

**Issue by mlbowser** [ArctosDB/arctos#2828]
**Describe the bug**
When I try to edit a publication, adding a doi previously generated using Arctos/EZID tools, I get an error.

**To Reproduce**
1. Go to 'http://arctos.database.museum/Publication.cfm?action=edit&publication_id=10009290'.
2. Enter '10.7299/X7GH9J8D' as the Digital Object Identifier (DOI).
3. Click 'save'.
4. See error:
'Message: DOI 10.7299/X7GH9J8D failed validation with StatusCode 404 Not Found'

**Expected behavior**
Previously, I was able to save these kinds of DOIs as expected.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 77.0.1

**Priority**
Priority-Normal

**Comment by dustymc** [comment]
I don't have an easy solution. The checker is crossref, it (despite lots of encouraging noise over the last few years) apparently has no idea that datacite exists.

The DOI is used to pull data, and the DC DOIs have none, so there is limited utility in doing whatever it would take to accept a datacite DOI in publication. That still doesn't mean we shouldn't.

**Comment by mlbowser** [comment]
It seems like we should be able to save a DOI string for a publication even if crossref fails to pull the data.

**Comment by dustymc** [comment]
If we allow alleged DOIs that can't pass the check, then we pollute the data with things that people made up - we lose our "checksum."

We could (I think) validate through datacite's API, but then we have - in publication - publication identifiers, plus whatever someone gave a datacite DOI to. (And more complex code - I use DOIs for a lot of things - and lots more network traffic, both of which can probably be ignored for now.)

What are you trying to accomplish by adding that DOI? Perhaps there's a cleaner path to the goal.

**Comment by mlbowser** [comment]
The goal was to have stable identifiers for Alaska Entomological Society articles that cite specimens. We do plan to maintain stable URLs for these articles, but users requested that we add DOIs, something that our little group does not have capacity or a subscription to generate. I used the criterion that articles generally needed to cite specimens/projects on Arctos for me to use Arctos tools to generate DOIs. This had worked fine for some time.

Similarly, I actually add DOIs for field notebooks, etc. that cite specimens, e.g., the publication at the URL below, then cite these. 

http://arctos.database.museum/publication/10009014

This functionality is not essential, though. I think for now I will not try to add DOIs to publications using Arctos tools.

@DerekSikes, what do you think?

**Comment by dustymc** [comment]
Thanks, got it. 

I'm more or less certain we don't want to allow those into publication.doi.

We can allow them into doi.publication - we already have that structure, but it's never been used.

I manually pulled a new DOI

https://doi.org/10.5072/FK2668J58T (things are a bit slow today, the link doesn't work yet)

https://ezid.cdlib.org/id/doi:10.5072/FK2668J58T

and....

```
insert into doi (doi,publication_id) values ('10.5072/FK2668J58T',10009290);
```

so

https://arctos.database.museum/doi/10.5072/FK2668J58T

should work as well.

Would that do what you need? If so we'd need to

* rebuild our end of the CDL API 
* add the 'get a DOI' thing to publications 
* make sure it's somehow clearly NOT confused with the 'SUPPLY a DOI' but in the publication data
* display Arctos-issued DOIs somewhere on the publication page(s).

**Comment by mlbowser** [comment]
That looks good! This would work well for our purposes. Do you think any one else would use this?

**Comment by Jegelewicz** [comment]
I think it would be used a lot if we document it (please write a how-to) and tell everyone how to use it (suggest a newsletter piece)!

**Comment by dustymc** [comment]
I'm demonstrably not good at predicting use. I think in general the 'get a DOI' thing gets used a lot less than I'd expect, which may not be a bad things - DOIs are expensive, I suspect CDL would cut us off if we got too crazy.

Maybe there should be a "get an ARK" option as well - those are cheap and I don't think there's any real limit.

I'll flip this to next task. It needs prioritized @ArctosDB/arctos-working-group-officers 

I'm happy to manually add more if that's necessary before this can be implemented.

**Comment by mlbowser** [comment]
Thanks, @dustymc!

**Comment by dustymc** [comment]
see also https://github.com/ArctosDB/arctos/issues/3466

Perhaps we should have publication.datacite_doi in addition to publication.[crossref]doi?

**Comment by campmlc** [comment]
Sure!

**Comment by Jegelewicz** [comment]
> Perhaps we should have publication.datacite_doi in addition to publication.[crossref]doi?

That seems like a very good idea. But also, we need documentation!
