### ISSUE TITLE
My operator account is locked and I cannot login. Can someone please let me know how to get my account unlocked? User name is bfluker.

### ISSUE THREAD

**Issue by bfluker** [ArctosDB/arctos#2829]
** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **

** Outages should be reported to the contacts listed at https://arctosdb.org/arctos-down/ **

** Arctos Documentation is http://handbook.arctosdb.org/ **

** Learn more about Arctos at https://arctosdb.org/ **

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **

**Comment by Jegelewicz** [comment]
Please use this link to reset your password.

https://arctos.database.museum/ChangePassword.cfm?action=lostPass

**Comment by Jegelewicz** [comment]
Someone from Arkansas State will need to unlock your account.

**Comment by bfluker** [comment]
Yes, I am the person to do that, but I am locked out. I am new to Arctos, so I apologize for the inconvenience. Also, one of the other operators here is locked out as well.

**Comment by Jegelewicz** [comment]
Who is the mentor for your collection? @campmlc ? They should be able to help.

**Comment by campmlc** [comment]
I'll get it, give me a minute.

**Comment by campmlc** [comment]
OK, should be done. Let me know if it works.

**Comment by bfluker** [comment]
?Mariel,

I just tried to login and I am getting a FATAL ERROR. It says I am not permitted to login.



--
Brook L. Fluker, Ph.D.
Assistant Professor
Dept. of Biological Sciences
Arkansas State University
PO Box 599
State University, AR 72467
bfluker@astate.edu
870-972-3253
________________________________

**Comment by campmlc** [comment]
Try using the banner at the top to create a new password. We had to reboot
the system last week. If that doesn't work, Dusty will need to reset it.

**Comment by dustymc** [comment]
>not permitted to login.

Try now

**Comment by bfluker** [comment]
?All:

It works now, Thank you!

Brook



--
Brook L. Fluker, Ph.D.
Assistant Professor
Dept. of Biological Sciences
Arkansas State University
PO Box 599
State University, AR 72467
bfluker@astate.edu
870-972-3253
________________________________
