### ISSUE TITLE
scheduled tasks

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#2830]
rebuild createIntermediateTaxonomy

review run schedule after next release

/remind me to check this in a week

**Comment by Jegelewicz** [comment]
Does this have anything to do with this?

![image](https://user-images.githubusercontent.com/5725767/85583368-70140380-b5fb-11ea-8157-8d5e53b95958.png)

If there are no identifications using the term, how the heck are things being mapped with it?

**Comment by dustymc** [comment]
No, its the thing that tries to create names for name-looking terms - a probably-mostly-futile attempt to add a little consistency to our hugely inconsistent data.

>how the heck are things being mapped

Magic! (Or A-string identifications...)

**Comment by dustymc** [comment]
log all pg_cron jobs

DONE
cleanTempTables
check_filtered_flat_stale
update_flat_taxonomy
check_flat_stale
set_container_history_stack

TODO


cf_report_cache
auto_merge_collecting_event
auto_merge_locality
bulkloader_autodelete
set_browse
set_media_flat
remove_expired_encumbrance
refresh_dwc_occurrence
bulkload_specimens
refresh_dwc_audubonmedia
refresh_dwc_ggbn_tissue
refresh_dwc_ggbn_permit
pre_bulk_check
pre_bulk_check_all
pre_bulk_repatriate

**Comment by dustymc** [comment]
Tasks are logging, need reporter, which needs synced test.

**Comment by dustymc** [comment]
This isn't tenable, un-blocking, I'll deal with it in prod and try not to melt anything important.

**Comment by sharpphyl** [comment]
> If there are no identifications using the term, how the heck are things being mapped with it?

@Jegelewicz  This is a issue raised in the rewrites of the taxonomy screens.  See https://drive.google.com/file/d/1kKu4MvR2NlvavoyQ3Ga4f_wWHDgiSMoC/view?usp=sharing

<img width="740" alt="Taxon map - fuzzy matches" src="https://user-images.githubusercontent.com/15368365/93903451-e5a07600-fcb5-11ea-9069-f3f99b19a50a.png">



We recommend that instead of the option being to "show matches exactly..." the option should be to "show fuzzy matches."   I have a fair number of taxa I've updated where it says that the name is NOT used in any identifications but it has multiple pins on the map.  Makes it look like we have a some serious errors in our taxonomy pages.

**Comment by campmlc** [comment]
I agree with making the default to show exact and the option to show fuzzy
matches.

**Comment by sharpphyl** [comment]
<img width="1158" alt="Screen Shot 2020-09-22 at 11 34 54 AM" src="https://user-images.githubusercontent.com/15368365/93926591-f0b6ce80-fcd4-11ea-89db-ec9a657f83b7.png">

**Comment by dustymc** [comment]
The taxonomy stuff needs its own issue - I'm just fixing the scheduled tasks reporter here....

**Comment by dustymc** [comment]
jobname?action=.... tasks are difficult to diagnose; do something clever.

**Comment by sharpphyl** [comment]
There's really no need to create a new issue.  The mapping of phantom specimens problem is discussed in #2695.

**Comment by dustymc** [comment]
First iteration is running, patched back to main

* rebuild multi-level tasks so that ?action can stand alone
* rebuild scheduler to use revised action vars as task names
* re-rebuild reporter to use revised task names rather than roots

**Comment by dustymc** [comment]
* ?action-->task_name is planned and (mostly?) implemented
* reporter is running in a probably-mostly-useful fashion

Need to track down tasks that aren't reporting in, make sure logging is enabled - most should be intermittent and just not logging yet

* cf_spec_res_cols
* report_notify_no_used
* speciesplus_cites
* report_delete_unused
* dup_agent_merge
* dup_agent_find
* tempLocEventNotification
* dup_agent_notify
* collection_report
* media_report
* media_cleanup
* stale_users
* annotation_report
* authority_notification_sendemail
* GenBank_build
* GenBank_transfer_name
* GenBank_transfer_nuc
* GenBank_transfer_tax
* GenBank_transfer_bio
* encumbrance_report
* component_loader_notification 
* ScheduledTasksMonitor
* cache_georef_stats
* refresh_dwc_occurrence
* refresh_dwc_audubonmedia
* refresh_dwc_ggbn_permit
* pre_bulk_check
* pre_bulk_check_all
* pre_bulk_repatriate
* temp_primeRelatedPI
* refresh_dwc_ggbn_tissue
* check_and_load

**Comment by dustymc** [comment]
Everything should be logging now.

/remind me to check back in a week

**Comment by dustymc** [comment]
reminder.cfm needs debug::exit code removed when its running consistently
