### ISSUE TITLE
Loan item picking tool is a nightmare now that all those fields are displayed for each part. Old version worked perfectly for us. Maybe give individual collection option for displaying the extra fields?

### ISSUE THREAD

**Issue by jldunnum** [ArctosDB/arctos#2832]
** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **

** Outages should be reported to the contacts listed at https://arctosdb.org/arctos-down/ **

** Arctos Documentation is http://handbook.arctosdb.org/ **

** Learn more about Arctos at https://arctosdb.org/ **

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **

**Comment by dustymc** [comment]
duplicate of https://github.com/ArctosDB/arctos/issues/2741
