### ISSUE TITLE
Bulkloader error message

### ISSUE THREAD

**Issue by bfluker** [ArctosDB/arctos#2833]
I recently tried a test bulk load of specimen data and get this error message when I try to check and load. Please help!

An error occurred while processing this page!
Message: ERROR: query returned no rows Where: PL/pgSQL function bulk_check_one(bigint,text) line 93 at SQL statement SQL statement "SELECT bulk_check_one(rec.collection_object_id,'bulkloader_stage')" PL/pgSQL function bulkloader_stage_check() line 7 at SQL statement
Detail: Parameter types passed (0):

**Comment by dustymc** [comment]
Thanks, should be returning better errors now.

* "enteredby" needs to be your login name - see http://handbook.arctosdb.org/documentation/bulkloader.html
* guid_prefix is case-sensitive
