### ISSUE TITLE
Error when using Scientific name checker

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2834]
Attempted to upload a file to the Scientific Name Checker tool and go this

![image](https://user-images.githubusercontent.com/5725767/85616177-909f8600-b61a-11ea-8567-6a0a4032f451.png)

**Comment by dustymc** [comment]
that's fixed (and unrelated to the tool), we're still adjusting some DB settings

**Comment by Jegelewicz** [comment]
Tried a second time and it worked. What's going on with the above? I've seen it elsewhere in some other issue....
