### ISSUE TITLE
Event Upload error

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2835]
I have 24K+ events in the Event Bulkload tool. They all validated, but after selecting load, a few loaded then I got this:

![image](https://user-images.githubusercontent.com/5725767/85762475-ffd7b180-b6d0-11ea-8e98-c31ee2f81333.png)

Could we put the no-print trigger in validation so it would be caught before this point? I have already spent a lot of time validating these records twice because stuff didn't validate the first time and I had to download and make corrections. If I could just remove the offending record (or better yet remove the non-printing character) that would be preferable to downloading, fixing, re-validating (which takes forever - hit validate and wait 11 times...).

Sorry - I'm just tired...

**Comment by Jegelewicz** [comment]
Also, the non-printing character isn't in the row with GUID = NMMNH:Paleo:13974, which makes me nervous...

**Comment by dustymc** [comment]
```

arctosprod@arctos>> select verbatim_locality from cf_temp_specevent where checkfreetext(verbatim_locality) is false;
                                                               verbatim_locality                                                                
------------------------------------------------------------------------------------------------------------------------------------------------
 United States, NM,                                                                                                                            +
 Mud Springs Mountain
 United States, NM,                                                                                                                            +
 Mud Springs Mountain
 United States, NM, Santa Fe, Cundiyo 7.5' 1953 NM Quad, Sombrillo, Just west of NM highway 503, about 2 km southof Chimayo  BLM Sombrillo ACEC+
 Just west of NM highway 503, about 2 km south of Chimayo  BLM Sombrillo ACEC
 United States, NM, Santa Fe, Cundiyo 7.5' 1953 NM Quad, Sombrillo, Just west of NM highway 503, about 2 km southof Chimayo  BLM Sombrillo ACEC+
 Just west of NM highway 503, about 2 km south of Chimayo  BLM Sombrillo ACEC
 United States, NM, Santa Fe, Cundiyo 7.5' 1953 NM Quad, Sombrillo, Just west of NM highway 503, about 2 km southof Chimayo  BLM Sombrillo ACEC+
 Just west of NM highway 503, about 2 km south of Chimayo  BLM Sombrillo ACEC
(5 rows)

```

You can probably run that from writeSQL as well.

Big-picture, this need an Issue (if there's not already one somewhere) - especially when looking at an API-centric future (if we are), how much "pretty" validation should we invest in, and how much should we leave up to DB rules?

**Comment by Jegelewicz** [comment]
I know what they are, I would like to be able to fix them WHERE they are so all the stuff will load rather than downloading all 24K rows, fixing two, then going through all of the validation again.

**Comment by dustymc** [comment]
That's probably another high-level conversation.

Let me know what you want the nonprints replaced with and I can get them.

**Comment by Jegelewicz** [comment]
They are both hard returns, so just delete them. Thanks!!!!!

**Comment by dustymc** [comment]
```
arctosprod@arctos>> update cf_temp_specevent set verbatim_locality=replaceFreeText(verbatim_locality,'')  where checkfreetext(verbatim_locality) is false;
UPDATE 5
```

**Comment by Jegelewicz** [comment]
@dustymc I'm sorry, but I just had another one - a future date.

replace began date 2020-07-08 with 2008-07-01 and ended date 2020-07-08 with 2008-07-31

Please and thank you so very much!!!!

**Comment by dustymc** [comment]
```
arctosprod@arctos>> update cf_temp_specevent set began_date='2008-07-01' where began_date='2020-07-08';
UPDATE 1
Time: 28.428 ms
arctosprod@arctos>> update cf_temp_specevent set ended_date='2008-07-31' where ended_date='2020-07-08';
UPDATE 1
Time: 12.524 ms
```

**Comment by Jegelewicz** [comment]
Thank you so much for helping me out!!!!!
