### ISSUE TITLE
List of Code Tables needs better decriptions

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2836]
Rather than "ctabundance" it would be good to see "Abundance Values" or something more descriptive.

**Comment by dustymc** [comment]
Given that https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_code_tables is a code table code table, I guess this would be a code table code table code table....


Here are table names - pull it into your favorite tool, add and fill a "description" column, and I'll figure out how to use it.

```
arctosprod@arctos>> select table_name from information_schema.tables where table_name like 'ct%';
          table_name          
------------------------------
 ctpart_preservation
 ctaccn_status
 ctaddr_type
 ctabundance
 ctaccn_type
 ctagent_relationship
 ctagent_rank
 ctagent_name_type
 ctborrow_status
 ctagent_status
 ctattribute_code_tables
 ctauthor_role
 ctcf_loan_use_type
 ctcitation_type_status
 ctcataloged_item_type
 ctconductivity_units
 ctcoll_other_id_type
 ctcoll_object_type
 ctcoll_obj_disp
 ctcollector_role
 ctcontainer_env_parameter
 ctcollection_cde
 ctculture
 ctcount_units
 ctcopyright_status
 ctid_references
 ctflags
 ctgeoreference_protocol
 ctew
 ctencumbrance_action
 ctfeature
 ctkill_method
 ctgeology_attribute
 ctisland_group
 ctinfraspecific_rank
 ctloan_type
 ctloan_status
 ctlength_units
 ctmedia_license
 ctlocation_in_host
 ctnagpra_category
 ctmedia_type
 ctmonetary_units
 ctns
 ctpart_attribute_part
 ctorig_elev_units
 ctpermit_agent_role
 ctpermit_regulation
 ctpart_preservation_need
 ctpermit_type
 ctpublication_type
 ctproject_agent_role
 cttaxon_variable
 ctsuffix
 ctspecimen_event_type
 ctspec_part_att_att
 ctshipped_carrier_method
 cttaxa_formula
 cttaxon_concept_relationship
 ctspecpart_attribute_type
 cttaxon_term
 cttaxonomy_source
 cttaxon_status
 ctverificationstatus
 cttransaction_type
 ctyes_no
 cttrans_agent_role
 cttemperature_units
 ctcoll_event_att_att
 ctmedia_relationship
 ctspecimen_part_name
 ctmime_type
 ctaddress_type
 ctagent_type
 ctattribute_type
 ctcaste
 ctcoll_contact_role
 ctcollecting_source
 ctcontainer_type
 ctdatum
 ctdepth_units
 ctidentification_confidence
 ctmedia_label
 ctnature_of_id
 ctnomenclatural_code
 ctprefix
 ctsex_cde
 ctspecimen_part_list_order
 cttissue_quality
 ctweight_units
 ctage_class
 ctcoll_event_attr_type
 ctdownload_purpose
 ctlat_long_error_units
 ctlat_long_units
 ctnumeric_age_units
 ctshipment_type
 cttissue_volume_units
 cttaxon_relation
```

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Yes, this is definitely needed - speaking as a relative newbie, it can be frustrating trying to find the correct code table to look something up.

**Comment by Jegelewicz** [comment]
Working on a new page set-up [here](https://docs.google.com/spreadsheets/d/1j0zg1AyJ0xkJS79dFLVeMiRo_RpD9hY911GbMXd5zxo/edit?usp=sharing). @ArctosDB/arctos-code-table-administrators feel free to contribute.

**Comment by dustymc** [comment]
Coolness: add category, use it to group things (like age) in the UI

And maybe a "people label" to translate some of our funky names

**Comment by Jegelewicz** [comment]
@dustymc I think we have this started, but just realized we can't use the group column so I need to fix people labels to help with the grouping. I'll try to finish today so we can get this moving.

**Comment by Jegelewicz** [comment]
OK - I think this is good to go. Can we implement?

**Comment by dustymc** [comment]
Data?

**Comment by Jegelewicz** [comment]
https://github.com/ArctosDB/arctos/issues/2836#issuecomment-651411510

**Comment by dustymc** [comment]
Leaving this open - could use some cleanup

**Comment by Jegelewicz** [comment]
What needs cleanup?

I suggest that instead of "Details" we use "Table Name"

**Comment by dustymc** [comment]
>What needs cleanup?

Unhandled tables should be obvious from edit, or they're grouped at the bottom of the public viewer list.

Tables that no longer exist are harder to find, but I think/hope I got those.

**Comment by Jegelewicz** [comment]
> Unhandled tables should be obvious 

Geez - these were all added after I originally set up the Google sheet another consequence of taking MONTHS to get anything accomplished. Can I edit this somewhere, or do I just add to the Google sheet?

**Comment by dustymc** [comment]
Yup, things pile up and feed off of each other.

You can edit in https://arctos.database.museum/Admin/CodeTableEditor.cfm

<img width="459" alt="Screen Shot 2021-04-27 at 8 19 00 AM" src="https://user-images.githubusercontent.com/5720791/116267413-3dfa9300-a731-11eb-9129-65d6683bef0c.png">

**Comment by Jegelewicz** [comment]
OK - will work on it this week.

**Comment by campmlc** [comment]
Looks great!
