### ISSUE TITLE
Doi for Arctos searches for citation purposes

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2837]
From MSB Curator related to data downloaded from Arctos portal and used in a publication without citing a grant-funded project that made these records available:

"We need a disclaimer on our data downloads that the original project funding, the database, the museum, and in this case an actual digitization grant--should all be acknowledged for use of the data. "

Do we have a means of letting users easily generate a doi for searches?

**Comment by dustymc** [comment]
>We need a disclaimer on our data downloads

https://github.com/ArctosDB/arctos/issues/2566 - collections are welcome to put any restrictions they wish in their license (or soon, terms). License information is included in downloads.

>letting users easily generate a doi for searches?

No, and there are lots of good reasons for that. Operators with manage_collection rights can: http://handbook.arctosdb.org/documentation/archive.html

**Comment by campmlc** [comment]
I guess this would kind of be like media licensing showing up on the
thumbnail. It would be interesting to have a way for groups of specimens,
perhaps project-based, have extra info added to the licensing download;
e.g. please cite our collection and also this funding source/project.

**Comment by dustymc** [comment]
>please cite

I suppose the first question is if you're looking for "please cite" or "cite thusly, or meet our lawyers." I'm not sure if that would change the structure or not, but it might.

>extra info added to the licensing download

https://github.com/ArctosDB/arctos/issues/2450

>project-based

I'd think probably accessions (where the additional info could just be a "permit") but about the same idea.

A restrict usage encumbrance (http://test.arctos.database.museum/info/ctDocumentation.cfm?table=ctencumbrance_action) could work as well, and would be a little finer-grained.

**Comment by Jegelewicz** [comment]
> cite thusly, or meet our lawyers

or meet our vapor phase nitrogen storage tank? :-)

This would be cool, but it could get super messy as individual specimens become part of other projects (plus the accession may be associated with various projects, the one that allowed them to be collected, the one that allowed them to be digitized, the one that allowed them to be moved from -80 freezers to vapor phase nitrogen...). Any given download might include stuff from any number of projects, each with it's own funding. A person could spend more time and space writing in citations than actually doing stuff with the specimens....

**Comment by dustymc** [comment]
>super messy

Good point - accession (and/or maybe encumbrances) would be much cleaner.

>spend more time and space writing in citations

I think that's basically GBIF's argument - data with enough hoop-jumping attached won't get used so there's no point in publishing them.
