### ISSUE TITLE
Search results for NK numbers include records of related items

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2839]
Search results for NK numbers include records of related items
=Extra records showing up in search results
What I did:
I did two separate searches for the same specimens, one using a list of the catalog numbers, and one using a list of NK numbers, for a loan request, and compared the results.  This is a good way to detect NK duplicates. 

What happened:
Interestingly, the NK search did reveal extra catalog records, but there were no duplicate NKs. The additional records in the search results were for other individuals that were related via the NK number. For example, the search list included NK 224066, but the search results included NK 224066 and 224067, which share parent/offspring relationships via the NK number. This is problematic, as I need the search results to return the  exact specimens in my list to add to a loan; not the related items (although this latter might be great to have as an option). I did have "related items" selected in the Add/Remove Data Fields. However, this usually just returns an extra column of data for each record, not additional records. 

What I expect to happen
Search on NK should return the catalog records just for those NKs, not for other catalog numbers related to one of the NKs in the submitted list

Priority
Normal for now

**Comment by dustymc** [comment]
I need details - a screenshot of what you searched on and whatever data you searched on should do it.

**Comment by Jegelewicz** [comment]
If you search for the NKs and include the relationship "self" does that work?

**Comment by campmlc** [comment]
[MuseVirome loan NK list.zip](https://github.com/ArctosDB/arctos/files/4838320/MuseVirome.loan.NK.list.zip)
![Screenshot 2020-06-26 11 24 20](https://user-images.githubusercontent.com/14808196/85884298-a4282980-b79f-11ea-9582-0a3e6763355b.png)

**Comment by campmlc** [comment]
There should be 547 records. The search returns 551.

**Comment by dustymc** [comment]
Please paste the list you used to search in here.

And I need an example record that's not supposed to be in the results.

**Comment by campmlc** [comment]
I provided the list and the example above. Here again:

MuseVirome loan NK list.zip

the search list included NK 224066, but the search results included NK 224067, which was not supposed to be in the list.

**Comment by campmlc** [comment]
[MuseVirome loan NK list.zip](https://github.com/ArctosDB/arctos/files/4839335/MuseVirome.loan.NK.list.zip)

**Comment by campmlc** [comment]
192308,192297,272031,223820,192035,192040,192046,192045,192041,192051,192039,192044,223818,223720,192268,192272,270481,224447,224156,224370,224508,224448,224157,224437,224438,224446,224513,224515,224549,224552,224591,224597,224512,224553,224548,224510,224507,224509,224565,224567,224570,224581,224587,224595,224330,224584,224551,224539,224511,224514,224586,224596,192634,192632,192633,192635,192049,192042,192038,192050,192048,192043,192036,272069,289395,223827,223828,223970,223966,223967,223981,223819,223821,223822,223965,289400,289396,289399,289336,289398,224002,224001,223973,223971,289134,289346,289980,289979,289026,289874,166277,289347,289349,289345,289348,223936,223829,223830,223964,223972,223823,223831,223949,223986,223987,223969,192037,166628,192305,192333,192304,223832,192280,192306,192312,192309,192331,192330,192307,192334,192282,270859,272241,272100,272113,272250,289397,192311,192310,192517,192607,192611,192612,192613,192614,192616,192621,192624,192625,192608,192610,192617,192618,192623,192615,192619,192620,192622,192609,192600,194099,194100,224193,223948,223950,166309,166297,166296,166272,166276,194474,166311,270956,272094,272246,272107,272244,272245,272247,272248,272252,272099,272242,289972,289971,289968,289969,289973,289970,192047,192281,192284,192269,192283,192271,192344,100619,272049,272067,272240,272020,224516,289079,166459,166300,166310,166298,166304,166270,166302,166392,289434,289435,270427,166265,223842,270959,270960,289160,289078,289278,289027,289277,289344,224068,192265,192274,192275,192266,192273,192267,192270,166274,166308,166299,192313,192303,166273,166275,192253,192140,192182,272104,270955,270857,272038,270310,270852,270312,272019,270958,270311,272101,270957,270858,272102,272103,272105,272106,272237,270935,270936,270942,270314,270853,270518,272108,272109,272110,272111,272112,272114,166293,100741,100727,100623,100613,100614,100633,100637,100658,100664,100766,100751,100776,100777,100778,100779,100771,100773,100800,100802,100798,100799,100797,100618,100665,100621,100622,100624,100641,100635,100636,100640,100653,100519,100642,224550,224568,224190,224579,224650,224594,224600,224367,224566,224580,224593,224719,224450,224445,224371,224718,224576,224592,224189,224521,224331,224518,224520,224583,223953,270399,270400,224066,223976,223994,223718,223975,289257,289258,224077,223898,224107,223993,224332,223995,270313,223691,223698,289125,223954,223938,223952,270590,166301,166391,166394,166393,166303,192024,194171,193811,193886,193631,193634,270921,270817,270398,270257,270736,270402,270496,270405,270255,270401,166271,192252,194411,100536,100555,193562,194108,193817,270309,192026,192025,166312,270498,270499,100765,100753,100760,224452,224441,224158,224449,224439,224443,224444,224372,224440,224451,224517,224588,224601,224442,224519,224198,224602,224582,289276,272068,272070,224488,272217,270501,223841,223824,223833,223838,223839,223840,223961,223733,223974,223977,223826,223959,223960,223945,192302,289073,289149,289074,289075,289077,289157,289076,289184,289158,223825,223835,223837,223963,223734,223834,223962,223937,224334,272095,272050,272059,272044,272039,272040,272051,272054,272062,272043,272060,272052,272058,272061,272057,272063,272048,270938,270523,270519,272041,272042,270937,272243,272251,270934,272292,272053,272055,272056,272045,270939,270940,272047,272037,272253,272293,272046,272238,192516,192518,270256,270482,270497,270403,270404,270854,272254,224333,224076,194123,194183,270500,194233,194186,194185,194107,100615,100616,193564,194030,193762,193571,193626,193627,193628,192332,100632,100638,100654,100659,100707,100792,100793,100801,100713,100708,100710,100711,100709,100706,100712,100705,100617,100620,100625,100626,100627,100629,100630,100631,100634,100639,100655,100662,100663,100628,193550,193551,193563,193567,193565,193638,193629,193724,270483,272189

**Comment by dustymc** [comment]
@Jegelewicz got the cause, but I'm not sure there's currently a solution. Arctos is simply checking attached identifiers with no consideration of why they're attached.

**Comment by campmlc** [comment]
We can't limit the search to "self" as default?

**Comment by dustymc** [comment]
We could but I suspect it's exactly as confusing as what's happening now, just for a different audience. I think we should be explicit, but that's going to run into screen real estate issues - it's another dropdown in an already-crowded UI.

**Comment by campmlc** [comment]
I don't think it would be more confusing to limit the search to self.  I
searched on 547 records for a specific identifier, with related items
checked.. I got 551 results. I expected 547 results with any related items
showing up in the related items columns for those 547 identifiers. I can
then choose to examine those related items more closely. I do not want to
add them to my loan of 547 objects, and under the current scenario, it
takes a rather significant effort to locate with of the 551 records do not
belong in my search results.
