### ISSUE TITLE
Specimen Results ->Manage ->Part Location Error

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2840]
Searched on 547 records
Went to Manage
Part Location
Got following error:
![Screenshot 2020-06-26 11 10 25](https://user-images.githubusercontent.com/14808196/85883341-0e3fcf00-b79e-11ea-8a41-59c756adb1a5.png)

**Comment by campmlc** [comment]
Tried it with 100 records, same error. This is actively impeding grant funded work on a timeline.

**Comment by campmlc** [comment]
I need to have this addressed before Monday - actively impeding work.

**Comment by campmlc** [comment]
192308,192297,272031,223820,192035,192040,192046,192045,192041,192051,192039,192044,223818,223720,192268,192272,270481,224447,224156,224370,224508,224448,224157,224437,224438,224446,224513,224515,224549,224552,224591,224597,224512,224553,224548,224510,224507,224509,224565,224567,224570,224581,224587,224595,224330,224584,224551,224539,224511,224514,224586,224596,192634,192632,192633,192635,192049,192042,192038,192050,192048,192043,192036,272069,289395,223827,223828,223970,223966,223967,223981,223819,223821,223822,223965,289400,289396,289399,289336,289398,224002,224001,223973,223971,289134,289346,289980,289979,289026,289874,166277,289347,289349,289345,289348,223936,223829,223830,223964,223972,223823,223831,223949,223986,223987,223969,192037,166628,192305,192333,192304,223832,192280,192306,192312,192309,192331,192330,192307,192334,192282,270859,272241,272100,272113,272250,289397,192311,192310,192517,192607,192611,192612,192613,192614,192616,192621,192624,192625,192608,192610,192617,192618,192623,192615,192619,192620,192622,192609,192600,194099,194100,224193,223948,223950,166309,166297,166296,166272,166276,194474,166311,270956,272094,272246,272107,272244,272245,272247,272248,272252,272099,272242,289972,289971,289968,289969,289973,289970,192047,192281,192284,192269,192283,192271,192344,100619,272049,272067,272240,272020,224516,289079,166459,166300,166310,166298,166304,166270,166302,166392,289434,289435,270427,166265,223842,270959,270960,289160,289078,289278,289027,289277,289344,224068,192265,192274,192275,192266,192273,192267,192270,166274,166308,166299,192313,192303,166273,166275,192253,192140,192182,272104,270955,270857,272038,270310,270852,270312,272019,270958,270311,272101,270957,270858,272102,272103,272105,272106,272237,270935,270936,270942,270314,270853,270518,272108,272109,272110,272111,272112,272114,166293,100741,100727,100623,100613,100614,100633,100637,100658,100664,100766,100751,100776,100777,100778,100779,100771,100773,100800,100802,100798,100799,100797,100618,100665,100621,100622,100624,100641,100635,100636,100640,100653,100519,100642,224550,224568,224190,224579,224650,224594,224600,224367,224566,224580,224593,224719,224450,224445,224371,224718,224576,224592,224189,224521,224331,224518,224520,224583,223953,270399,270400,224066,223976,223994,223718,223975,289257,289258,224077,223898,224107,223993,224332,223995,270313,223691,223698,289125,223954,223938,223952,270590,166301,166391,166394,166393,166303,192024,194171,193811,193886,193631,193634,270921,270817,270398,270257,270736,270402,270496,270405,270255,270401,166271,192252,194411,100536,100555,193562,194108,193817,270309,192026,192025,166312,270498,270499,100765,100753,100760,224452,224441,224158,224449,224439,224443,224444,224372,224440,224451,224517,224588,224601,224442,224519,224198,224602,224582,289276,272068,272070,224488,272217,270501,223841,223824,223833,223838,223839,223840,223961,223733,223974,223977,223826,223959,223960,223945,192302,289073,289149,289074,289075,289077,289157,289076,289184,289158,223825,223835,223837,223963,223734,223834,223962,223937,224334,272095,272050,272059,272044,272039,272040,272051,272054,272062,272043,272060,272052,272058,272061,272057,272063,272048,270938,270523,270519,272041,272042,270937,272243,272251,270934,272292,272053,272055,272056,272045,270939,270940,272047,272037,272253,272293,272046,272238,192516,192518,270256,270482,270497,270403,270404,270854,272254,224333,224076,194123,194183,270500,194233,194186,194185,194107,100615,100616,193564,194030,193762,193571,193626,193627,193628,192332,100632,100638,100654,100659,100707,100792,100793,100801,100713,100708,100710,100711,100709,100706,100712,100705,100617,100620,100625,100626,100627,100629,100630,100631,100634,100639,100655,100662,100663,100628,193550,193551,193563,193567,193565,193638,193629,193724,270483,272189

**Comment by campmlc** [comment]
That was the NK list. Here is the MSB list:

[MuseVirome loan MSB list.zip](https://github.com/ArctosDB/arctos/files/4839376/MuseVirome.loan.MSB.list.zip)

**Comment by campmlc** [comment]
Any chance of getting this working? I have three people standing by to do work that depends on this tool being functional.

**Comment by KyndallH** [comment]
I was just logging on to GitHub to complain too! I need this done ASAP - I have a huge loan we need to get out the door. The only reason I actually came into work today was to get this done! :(

**Comment by dustymc** [comment]
I can push my pending release out now?

**Comment by KyndallH** [comment]
YES!!! PLEASE!!! 👯

**Comment by campmlc** [comment]
Does that mean Arctos goes down? We should send out quick notification.

**Comment by dustymc** [comment]
>mean Arctos goes down?

No

**Comment by campmlc** [comment]
OK, go for it!

**Comment by campmlc** [comment]
Please let us know the time frame. I also came to work today just to deal
with this and all is on hold.

**Comment by dustymc** [comment]
>time frame.

30 seconds ago

**Comment by KyndallH** [comment]
Woohoooo!!!!!! THANK YOU!!!!!

**Comment by KyndallH** [comment]
Okay - got too excited.

When you try to filter for parts:
ucee.runtime.exp.DatabaseException: ERROR: relation "my_big_list" already exists at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455) at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155) at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288) at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430) at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356) at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:303) at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:289) at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:266) at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:262) at lucee.runtime.type.util.QueryUtil.execute(QueryUtil.java:319) at lucee.runtime.type.QueryImpl.execute(QueryImpl.java:271) at lucee.runtime.type.QueryImpl.<init>(QueryImpl.java:225) at lucee.runtime.tag.Query.executeDatasoure(Query.java:1091) at lucee.runtime.tag.Query._doEndTag(Query.java:672) at lucee.runtime.tag.Query.doEndTag(Query.java:552) at loanfreezerlocn_cfm$cf$10c.call(/loanFreezerLocn.cfm:73) at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:914) at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:837) at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:216) at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:42) at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2416) at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2406) at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2381) at lucee.runtime.engine.Request.exe(Request.java:43) at lucee.runtime.engine.CFMLEngineImpl._service(CFMLEngineImpl.java:1127) at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:1073) at lucee.loader.engine.CFMLEngineWrapper.serviceCFML(CFMLEngineWrapper.java:97) at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:51) at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587) at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.base/java.lang.Thread.run(Unknown Source)

**Comment by KyndallH** [comment]
Message: ERROR: relation "my_big_list" already exists
Detail:
Check the Arctos Handbook for more information on errors.
This message has been logged as 3FAC301B-04A1-46B6-824D32FDCE7ED168 Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue.

**Comment by KyndallH** [comment]
<img width="1565" alt="Screen Shot 2020-06-29 at 11 36 00 AM" src="https://user-images.githubusercontent.com/16887896/86048365-e26e5480-b9fc-11ea-9d0e-cf2195c421a6.png">

**Comment by KyndallH** [comment]
<img width="1786" alt="Screen Shot 2020-06-29 at 11 37 35 AM" src="https://user-images.githubusercontent.com/16887896/86048411-f44ff780-b9fc-11ea-9da2-6a8150e5b8e2.png">

**Comment by KyndallH** [comment]
When you click on flatten, and then attempt to filter. 

<img width="585" alt="Screen Shot 2020-06-29 at 11 38 11 AM" src="https://user-images.githubusercontent.com/16887896/86048462-0893f480-b9fd-11ea-82fd-9c948155aae9.png">

**Comment by campmlc** [comment]
Beat me to it. Got the same error.

**Comment by dustymc** [comment]
I think that's probably fixed - there was some Oracle workaround code in there, I commented it out. If not I'll need more details - it is and was working for me, so probably something in the data.

**Comment by campmlc** [comment]
It seems to be working.

**Comment by campmlc** [comment]
Thank you!!
