### ISSUE TITLE
Request to add soil or environmental sample as a part name

### ISSUE THREAD

**Issue by mlbowser** [ArctosDB/arctos#2841]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Goal**
More truthfully reflect the nature of environmental samples, soil samples in this case.

**Context**
I am dealing with soil samples for metabarcoding of soil fungi and soil bacteria (one sample of soil per site, one DNA extraction per sample, two amplifications/analyses for each extraction). I would like to be able to enter the soil samples into Arctos as specimens. Currently, the only options available in the code table (<https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name>) for Env collections are "DNA extraction" and "filter paper". I can make "DNA extraction" work in this case, referring to the extractions instead of the original material samples. I would rather use "soil" (specific) or "environmental sample" (general), which would be more appropriate for the original samples.

Also, what would the appropriate identification be for such samples? "Life" is available in Arctos' taxonomy, but this may not be the most appropriate for a sample that might not contain life (even though we are looking for it).

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name

**Value**
"soil" or "environmental sample"

**Definition**
soil: upper layer of the earth's surface
environmental sample: a sample from the environment (e.g., soil, water, air) that is not intentionally associated with any particular organism.

**Collection type**
Env

**Attribute data type**
categorical

**Attribute value**
"soil" or "environmental sample"

**Part tissue flag**
no? May or may not include tissue. It is not a pure tissue sample.

**Priority**
low

**Comment by Jegelewicz** [comment]
We have the part "geosample" does this seem sufficient?

**Comment by Jegelewicz** [comment]
> Also, what would the appropriate identification be for such samples? "Life" is available in Arctos' taxonomy, but this may not be the most appropriate for a sample that might not contain life (even though we are looking for it).

See #2842

**Comment by mlbowser** [comment]
Sure, "geosample" would suffice for this type of sample. I will use it. Thanks!
