### ISSUE TITLE
Identification of soil samples

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2842]
From #2841 

> Also, what would the appropriate identification be for such samples? "Life" is available in Arctos' taxonomy, but this may not be the most appropriate for a sample that might not contain life (even though we are looking for it).

I suggest using the A {string} identification formula and identifying it this way

unidentifiable {soil sample} or unidentifiable {environmental sample}

**Comment by mlbowser** [comment]
Thanks! I used "unidentifiable {soil sample}", which truthfully describes what I have.
