### ISSUE TITLE
Unable to download search results

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2843]
I am getting the 500 Fail when attempting to download [these search results](https://arctos.database.museum/saved/NMMNH%20with%20Research%20Events).

I really just need the catalog numbers.

**Comment by Jegelewicz** [comment]
![image](https://user-images.githubusercontent.com/5725767/86036470-295b4a80-b9fb-11ea-9838-04b89ee65d95.png)

**Comment by dustymc** [comment]
>just need the catalog numbers

Does this work for now?


```
 create table temp_cache.cns as SELECT distinct flat.guid as guid
  FROM flat INNER JOIN cataloged_item ON (flat.collection_object_id = cataloged_item.collection_object_id) 
  INNER JOIN specimen_event ON (flat.collection_object_id = specimen_event.collection_object_id) 
  WHERE flat.collection_object_id IS NOT NULL AND 
  specimen_event.verificationstatus = 'accepted' AND 
  flat.collection_id IN ( select collection_id from collection where upper(guid_prefix) IN ('NMMNH:PALEO') ) 
;
```

[temp_cache.cns.csv.zip](https://github.com/ArctosDB/arctos/files/4847228/temp_cache.cns.csv.zip)


In any case please leave this open - I have more tools now, although it might take some time to figure out how to safely use them for this.

**Comment by Jegelewicz** [comment]
/remind me to try this out tomorrow.

**Comment by Jegelewicz** [comment]
Stuff has changed since you ran this, so I tried using that code in Write SQL and got this:
![image](https://user-images.githubusercontent.com/5725767/86150504-ba452b00-baba-11ea-9f66-d7174f292ff6.png)

**Comment by dustymc** [comment]
Lose the create-bits

**Comment by Jegelewicz** [comment]
Cool, that worked, but now how do I download it?

**Comment by dustymc** [comment]
If you selected table it's probably on your machine - if you didn't, just select table.
