### ISSUE TITLE
Thumbnail description for media

### ISSUE THREAD

**Issue by krgomez** [ArctosDB/arctos#2846]
**Goal**
Describe what you're trying to accomplish.
We need a designated media field that will display below thumbnails on catalog records. See #2813, #1652, #2529.

**Context**
Describe why this new value is necessary and existing values are not.
Currently, media labels (description, comment, and maybe others) unpredictably display below thumbnails. We need the ability to predictably display critical media data to users on catalog records. By calling this media label “thumbnail description”, it allows flexibility for collections to prioritize what type of data they consider to be most important to display.

**Table**
Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm
media_label

**Value**
Proposed new value
thumbnail description

**Definition**
Clear, complete, non-collection-type-specific definition of the new value.
Description that will display below thumbnails on catalog records.

**Attribute data type**
free-text, categorical, number+units
free-text

**Priority**
Please assign a priority-label.
normal?

**Comment by Jegelewicz** [comment]
Taxonomy committee looked at some multi-page documents today that need better "tombstones". How hard to update all of the pages with an appropriate description?

![image](https://user-images.githubusercontent.com/5725767/87606952-7278f300-c6b9-11ea-82cf-f69110700da7.png)

It would be great if these could just display the document title.

![image](https://user-images.githubusercontent.com/5725767/87606993-8d4b6780-c6b9-11ea-98fc-f9fee9a493c4.png)

**Comment by dustymc** [comment]
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctmedia_label&field=description

**Comment by Jegelewicz** [comment]
Any way we can change these in bulk? there are over 4,000 individual pages in this multi-page document....

**Comment by dustymc** [comment]
I can probably shuffle things around if you'll let me know how to find them.

>over 4,000 individual pages in this multi-page document.

That does not seem like a good idea!

**Comment by Jegelewicz** [comment]
It is a catalog with page numbers - that's how it's supposed to work...

They all have the same title and we would just want to add a description label that is the same as the title.

I can find them all, but have no way to easily get their media ids to put together a file for this.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/2813
