### ISSUE TITLE
Other Identifiers and Agents

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2847]
In working through our Identifiers code table, I have noticed that many of these could actually be related to Agents.

We could pare down the Other Identifier list, if instead of creating an identifier for [Sea World, San Diego](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type), we used the Agent [Sea World - San Diego](https://arctos.database.museum/agent.cfm?agent_id=21310187&agent_name=Sea%20World%20-%20San%20Diego).

Not sure how the mechanics of this could work. What if we have an Other ID = "Agent" which then requires the entry of a valid Arctos Agent Name in addition to the value?  

Could we also do this for collector number and preparator number as well? Just thinking out loud here - it seems like we are missing out on linking/duplicating data when we have these two things (agent name and other identifier from that agent) separated. Could we then also have an Agent address that was "identifier base URI" that does just what "base URI" does in the other identifiers code table to facilitate links when they are possible?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I think it would be a very useful feature.

**Comment by dustymc** [comment]
The original model had collector number in table collector. It was indeed tighter link, at least in the very rare case when the explicit number is of the expected type, format, and cardinality. If the "primary" number wasn't what was hard-coded in the table, then something arbitrary must be done. If there were multiple identifiers associated with agent-in-role, then something arbitrary must be done. It was always more difficult to search - you had to query three mostly-arbitrary concepts (otherIDs, collectors, cataloged item) instead of the current two, or abstract that through the UI which brings its own problems. In an ideal world where we know the collector and they're giving us what's expected it's probably better. In the real world where there are 27 numbers and 5 cryptic probably-agent-like strings scribbled around and everybody has a slightly different way of deciding what's important, it wasn't much fun.

Lacking an explicit use case where this could DO something that can't be done with the existing structure/data, I think the costs would outweigh the benefits.

**Comment by Jegelewicz** [comment]
Why not have this?

OTHER_ID_TYPE_1 | OTHER_ID_VALUE_1 | OTHER_ID_RELATIONSHIP_1 | OTHER_ID_AGENT_1

Where OTHER_ID_AGENT_1 could be NULL

**Comment by Jegelewicz** [comment]
OR could we just add the Agent Name in the Other ID table and allow it to be NULL? This won't do anything for "collector number", but it could be helpful for Sea World, San Diego. If an Agent could only be added to one Other ID, it could help control duplicates and also provide a lot more info about the Other ID (the agent holds all kinds of data).

**Comment by campmlc** [comment]
I like this idea as a means of reducing other IDs. We do need a way to link
identifiers to agents, and a way to avoid throwing out useful agent info
contained within undefined identifiers.

**Comment by dustymc** [comment]
I think that would avoid the original problems.

I'm still not clear on the goals. BaseURL would remain attached to IDType - I don't see how any arrangement of "Sea World, San Diego" controls how and if we can exchange data.

This could serve as a "confounder" but without some idea of the goal I'm not sure that matters. Given a bunch of XXX=YYY attached to AgentZ and a bunch of XXX=YYY _not_ attached to AgentZ, any analytical user would decide there's SOMETHING different about the data. Would there be? Could we avoid the difference being "nobody told the data entry people to add this arbitrary value"?

>means of reducing other IDs.

Are you proposing that the "some giant agency" (DNR, some university, etc.) would all get merged into 'original identifier' or similar? Maybe everything without a base_URL shares a type? There's some value in that. 

>avoid throwing out useful agent info

Clarify please.

**Comment by Jegelewicz** [comment]
Right now we have disconnected information. We have agent = [Sea World - San Diego](https://arctos.database.museum/info/agentActivity.cfm?agent_id=21310187) and we have Other ID = Sea World, San Diego which end up in a catalog record like this:

![image](https://user-images.githubusercontent.com/5725767/86139837-6da72300-baad-11ea-9c44-63720a55915a.png)

So we already have two different ways of spelling the same thing and there is no way to connect the agent with the numbers it assigned to the object, except by reading the record and making the connection that Sea World - San Diego and Sea World, San Diego are the same thing (in this case, easy, but it may not always be true...)

I think we are talking past each other a bit because @dustymc sees this table as a way to link out to data elsewhere and we see this as a way to add meaningful information to the other numbers assigned to a thing whether or not those numbers can provide a link out.

What if the links that DO something for Dusty were part of the Agent information? I'll use Museum of Comparative Zoology as my example. First, we would need to create an Agent Museum of Comparative Zoology, Division of Mammalogy, then

add to Museum of Comparative Zoology, Division of Mammalogy an address "Other Identifier Base URI" = http://mczbase.mcz.harvard.edu/guid/MCZ:Mamm:

then structure the Other ID as follows:

OTHER_ID_AGENT_1 | OTHER_ID_VALUE_1 | OTHER_ID_RELATIONSHIP_1

get rid of the Other ID table, for IDs with no specified agent, use unknown.

This will mean that we will need to create some agents that are currently in the Code table, but not in the Agent table, and that code will have to change so that the link is created from the Agent Other Identifier Base URI. For most identifiers (collector numbers) this means that instead of putting "collector number" in an Other ID Type field, you will just copy the collector Agent name into the Other_ID_Agent field.

**Comment by dustymc** [comment]
>way to link out 

More like 'way to exchange information' but yeah - if some complex structure can't DO STUFF then why would we invest the effort into designing and using it, both of which are almost certainly a lot more work, for everyone, forever, than cramming text into some unorganized blurb? 

>get rid of the Other ID table

I think I was leaning the other way, and don't have the attention span to really focus on this right now, but I was wondering if maybe we've got one too many tables and a cure for our '``collector`` has a weird name' issue.

Merging would lead to some semi-weird situations - we'd have

Agent=John Q. Doe identifier=NULL
Agent=unknown identifier=JQD123

for legacy data where we can't confidently merge those, and....

Agent=John Q. Doe role=collector identifier=1
Agent=John Q. Doe role=collector identifier=2
Agent=John Q. Doe role=collector identifier=3

... things that would currently violate unique indexes when the agent-in-role feels like writing a lot for some reason, and I'm sure lots of other weird things - nothing obviously insurmountable, but needs more discussion.

>created from the Agent Other Identifier Base URI

I don't think that's quite so simple - eg MVZ (and probably every other old/big org) has about 50 flavors of "MVZ identifier" that they've used at different times or for different purposes, and I don't think they'd all share a "base." Minor details....

**Comment by ebraker** [comment]
A quick note that we should also consider adding an "agent identifier prefix" or something of the like to the agent names code table to indicate expected collector number (etc.) formats to better link the concepts of agents and other_IDs.

agent: Sea World, San Diego
identifier prefix: SWC

**Comment by Jegelewicz** [comment]
Wouldn't it be sweet to find all catalog items assigned a number by Agent X?

**Comment by dustymc** [comment]
>assigned a number by Agent X

I think that's a request to merge ``coll_obj_other_id_num`` and ``collector``; I'm not seeing another path to those data, anyway.

That seems like it would inevitably lead to a new collector_role, 'identifier issuer' (er sumthin) for use when there's just an "original identifier" scrawled on something, and nobody really knows where it came from. (This probably describes the majority of our identifiers.)

* collector-->AgentA (identifier: maybe something, maybe not)
* preparator-->AgentB (identifier: maybe something, maybe not)
* identifier-issuer-->AgentC (identifier: something found on some label)

where AgentC is "unknown" a fair bit of the time.

So a bit more complexity on https://github.com/ArctosDB/arctos/issues/2847#issuecomment-651896712.

And maybe some more complexity to somehow deal with "SomeOtherAgent cataloged the parasite, assigning it an identifier; I'm cataloging the host, "me" is important data, but I didn't exactly ASSIGN the identifier I'm just USING it" types of situations. 

I think the result (whatever the details) is clearly "better" data which can do more than it can now, but also a fair bit more complexity in assigning identifiers and collectors.

**Comment by ewommack** [comment]
Do you mean assigned a catalog number, or assigned a tissue number, or assigned an accession number, or assigned a prep number, etc?
I love tracking numbers, but what numbers?

**Comment by dustymc** [comment]
All the numbers!

* AgentA minted {identifier_type}={identifier_value} 
* AgentB assigned {identifier_type}={identifier_value}
* AgentC created relationship using {identifier_type}={identifier_value}
* .....

should fit, but I doubt anyone wants to enter a half-dozen agent-identifier-relation-whatever-thingees every time a house sparrow offs itself on your window either.

What's the current model not do, and are we willing to deal with more complexity to capture that, whatever it might be?

**Comment by Jegelewicz** [comment]
Maybe we could create a new address type = Arctos identifier and put a link to the appropriate identifier in the code table.

See [Maryland Zoo](https://arctos.database.museum/agent.cfm?agent_id=21310174&agent_name=The%20Maryland%20Zoo)

I just used "url" so it looks crazy, but it links the agent to the other identifier. (Sort-of, the other ID doesn't get highlighted in any way - see #3528 

The description of the other id also includes a link to the agent, so you can go both ways.

**Comment by dustymc** [comment]
>new address type = Arctos identifier

That should (probably) be more specific - I think all I can really know from that is that the ID was minted by the Maryland Zoo. Maybe it was **applied** by me, and all the associated data are in my possession.

**Comment by Jegelewicz** [comment]
Associated Arctos identifier?

**Comment by Jegelewicz** [comment]
![image](https://user-images.githubusercontent.com/5725767/139691286-9dcc8b4f-1562-456f-bdec-332b08cbf33a.png)

leads to 

![image](https://user-images.githubusercontent.com/5725767/139691361-cbda1444-7bac-4adf-aa6b-771a15319b24.png)

leads to

![image](https://user-images.githubusercontent.com/5725767/139691632-6debdc61-8440-4d94-966c-867c097d832c.png)

**Comment by Jegelewicz** [comment]
closing as duplicate of #4101
