### ISSUE TITLE
Next available loan number pulls last loan number instead

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2850]
In Transactions: Create Loan
Next Available Loan Number for MSB Mamm displays the last used loan, not the next available.
This risks duplication of loan numbers.
Priority High

**Comment by KyndallH** [comment]
I checked for UAM:Mamm since I'm doing a loan right now - we are all good here!

**Comment by dustymc** [comment]
Duplicate of https://github.com/ArctosDB/arctos/issues/1949 with some elements of https://github.com/ArctosDB/arctos/issues/1598
