### ISSUE TITLE
Bulkloader mass editing/delete

### ISSUE THREAD

**Issue by anna-chinn** [ArctosDB/arctos#2851]
Is there currently any way to bulk edit/delete records that are in my bulkloader via the [Browse/Edit](https://arctos.database.museum/Bulkloader/browseBulk.cfm) page? Or plans to bring the SQL editing feature back?
I'm trying to either mass edit records in the bulkloader or, in absence of that possibility, delete everything that I just loaded so that I can reload without errors.

**Comment by dustymc** [comment]
I can revive the SQL editor. 

You can set loaded to "DELETE" or let me know what you want gone for now. Maybe that should be a "mark all..." option?

**Comment by anna-chinn** [comment]
I liked/used the SQL editor! But otherwise, a 'delete all selected rows' that works in the same way as 'load all selected rows' would be great.

**Comment by Jegelewicz** [comment]
I could swear I have used the SQL editor....but maybe that was somewhere else?

**Comment by anna-chinn** [comment]
In the meantime, can you please delete everything where entered by = achinn? Thanks!

**Comment by dustymc** [comment]
arctosprod@arctos>> delete from  bulkloader where enteredby='achinn';
DELETE 140

**Comment by dustymc** [comment]
I've got the SQL option functional if not pretty. I'm happy to do more, or discuss closer integration with the pre-bulkloader, or WHATEVER. I'm glad to hear someone uses that thing!

Also added a DELETE option.


The menu section is getting a little out of control and probably needs some sort of redesign.

<img width="254" alt="Screen Shot 2020-06-30 at 12 44 57 PM" src="https://user-images.githubusercontent.com/5720791/86170207-9f30e600-bacf-11ea-9554-35b0643a94bf.png">

**Comment by Jegelewicz** [comment]
OH - I guess I used the SQL thingee with stuff in the bulkloader staging table....anyway, I used it in the last week or so and it was super helpful except it only shows like 50 records or something.
