### ISSUE TITLE
Bulkloader error function coalesca()

### ISSUE THREAD

**Issue by anna-chinn** [ArctosDB/arctos#2852]
My bulkloader is throwing a strange error that is preventing some of my records from loading:
`function coalesca(character varying, unknown) does not exist`

<img width="679" alt="Screen Shot 2020-06-30 at 12 44 15 PM" src="https://user-images.githubusercontent.com/40321380/86153312-77da1900-bacf-11ea-8c48-6ece7d8263f6.png">

They are all Entered By = achinn. 
From what I can tell, the only data that unites them is that 'unknown' determined some or all of their attributes.

**Comment by Jegelewicz** [comment]
It looks like there might be a space in front of "unknown"?

**Comment by anna-chinn** [comment]
I don't think so? I just downloaded the data directly from the bulkloader and found no instances of ' uknown'.

**Comment by dustymc** [comment]
Woops! Try again.
