### ISSUE TITLE
Request to add KNWR:Env other_id_type

### ISSUE THREAD

**Issue by mlbowser** [ArctosDB/arctos#2853]
**Goal**
I wish to be able to add relationships to catalog records in the Kenai National Wildlife Refuge Environmental samples collection (KNWR:Env).

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type

**Value**
IDType: "KNWR:Env"

**Definition**
Description: "Kenai National Wildlife Refuge, Alaska (KNWR) Environmental samples catalog number"

**Other ID BaseURL**
http://arctos.database.museum/guid/KNWR:Env:

**Priority**
normal

**Comment by Jegelewicz** [comment]
Done.

**Comment by mlbowser** [comment]
Thank you!
