### ISSUE TITLE
Remove loaded parts from part bulkloader please

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2854]
@dustymc I have a bunch of stuff in the part bulkloader - can you delete all of the stuff with status "loaded" so I can load the rest? Thanks a million in advance....

**Comment by dustymc** [comment]
arctosprod@arctos>> delete from cf_temp_parts where username='jegelewicz' and status='loaded';
DELETE 2944

**Comment by Jegelewicz** [comment]
You ARE a wizard - thanks!

**Comment by Jegelewicz** [comment]
@dustymc Sorry! can you do this again? I will load no more than 2,000 parts at a time from now on as that seems to be the max for the form?

**Comment by dustymc** [comment]
DELETE 2200
 There would be no hard-coded max - leave some details and we can rebuild whatever's melting (eventually...).

**Comment by Jegelewicz** [comment]
I've been loading files of exactly 2,000 parts no problem - super quick. I decided to try 2,500 and it looks like it died at 2,200 although the first one died at 2,944, so who knows? I'll keep going with 2,000 at a shot....

**Comment by Jegelewicz** [comment]
@dustymc dang-it - one more time please?

**Comment by dustymc** [comment]
DELETE 2297

**Comment by Jegelewicz** [comment]
Thanks!
