### ISSUE TITLE
Bug? A / B intergrade

### ISSUE THREAD

**Issue by anna-chinn** [ArctosDB/arctos#2855]
I tried to bulkload a bunch of specimens using the 'A / B intergrade' identification formula, but the bulkloader gave me errors when I tried to load them (e.g. invalid: taxonomy (example1 / example2 intergrade) not found). I just tried to enter an intergrade from the single record data entry page's identification builder tool and I'm getting the same error even though both taxa are in Arctos. Is this a bug or am I entering these kinds of data incorrectly?

**Comment by dustymc** [comment]
That's just not there for some reason.

The bulkloader should be happy now.

```

arctosprod@arctos>>  select unwind_bulk_tax_name('Lampropeltis getula floridana / Lampropeltis getula getula intergrade');
                                                                                                                              unwind_bulk_tax_name                                                                                                                               
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 {"taxa_one":"Lampropeltis getula floridana","taxa_two":"Lampropeltis getula getula","l_taxon_name_id_1":1769567,"l_taxon_name_id_2":1767751,"l_taxa_formula":"A / B intergrade","idsciname":"Lampropeltis getula floridana / Lampropeltis getula getula intergrade","err":null}
(1 row)
```

I can look at the builder later.

**Comment by dustymc** [comment]
The ID and data entry builders both seem to be working, tentatively closing.
