### ISSUE TITLE
Handling Media URI changes

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2856]
Thinking about private storage - if we assign a URI that represents a storage location on a local drive, but later move all the media to a different location, how difficult would it be to update those URIs? Assuming we did some work before the move (maybe a download of all media ID's with URIs starting with the root of our directory), could we set up a file with media ID, Old URI, New URI and get them swapped out?

Just trying to plan for this possibility, which I think is pretty likely on a local server....

**Comment by dustymc** [comment]
Keeping the end-user URLs stable is a big part of the design. Given a file of either media_id or media_uri (anything that'll let us find the old) and the new URI, it would be a simple update.

**Comment by Jegelewicz** [comment]
@Nicole-Ridgwell-NMMNHS @lin-fred see above.

**Comment by lin-fred** [comment]
Thanks all, we'll keep it in mind!

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
@dustymc can the media upload be adjusted so it allows us to upload a URI that goes to a local storage location? Also, is it possible to make those local URIs so that when we click on them, they open up in file explorer instead of having to copy/paste the URI into file explorer?

**Comment by dustymc** [comment]
>allows us to upload a URI

Upload - no, I can't access your storage.

"Add as media_uri" yes, but should probably be discussed/announced/something, not buried in here - it opens up a possibility of not doing what you think you're doing, and one which has been prevalent since forever.

 >open up in file explorer 

That's between you and your browser/UI; I don't believe I have any control over it.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
opened a separate issue #3052
