### ISSUE TITLE
Part name whole organism - add to ES

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2857]
I need the part whole organism added for ES collections, but there is a definition inconsistency that requires DBA intervention.

New definition:

A contiguous alive or once living physical entity; entity or being that is or was living; an individual living or once living thing, such as one animal, plant, fungus, or bacterium. https://www.wikidata.org/wiki/Q7239

**Comment by dustymc** [comment]
Old data - this isn't a reasonable definition so I don't think we should let it stop this; anyone using this data in this way should update, and I can help.

```
 whole organism | Amph           | Entire organism in ethanol-glycerin mixture. |         0 | 143265201
 whole organism | Herp           | Entire organism in ethanol-glycerin mixture. |         0 | 143265202
 whole organism | Rept           | Entire organism in ethanol-glycerin mixture. |         0 | 143265203
```

```
update ctspecimen_part_name set description='A contiguous alive or once living physical entity; entity or being that is or was living; an individual living or once living thing, such as one animal, plant, fungus, or bacterium. https://www.wikidata.org/wiki/Q7239' where part_name='whole organism';
UPDATE 13

```
