### ISSUE TITLE
New attribute: copyright notice

### ISSUE THREAD

**Issue by krgomez** [ArctosDB/arctos#2861]
**Goal**
Describe what you're trying to accomplish.
We need a designated place in the catalog record for an object/work's copyright notice. For UAM:Art we currently record the notice as a remark in the copyright status attribute. However, as a remark, this core data is not accessible for download. I propose we create a new free-text attribute for copyright notices. See #2813 and #2450.

**Context**
Describe why this new value is necessary and existing values are not.
As noted above, the copyright status attribute remarks does not work well for this data. A copyright notice attribute will allow for download.

**Table**
Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm
attribute_type

**Value**
Proposed new value
copyright notice

**Definition**
Clear, complete, non-collection-type-specific definition of the new value.
A notation attached to a creative work indicating the copyright owner of a work. The copyright notice may take a variety of forms depending on applicable law. In the United States the most common form is © [year of first publication] [name of copyright holder].

**Collection type**
If the code table includes a "Collection" column. Ex: Mamm, Herp, ES
Art

**Attribute data type**
free-text, categorical, number+units
free-text

**Priority**
Please assign a priority-label.
Normal

**Comment by Jegelewicz** [comment]
I support this. @ArctosDB/arctos-code-table-administrators any objections?

**Comment by dustymc** [comment]
>© [year of first publication] [name of copyright holder].

If that's all that's necessary then we may not need this - '[year of first publication]' could be extracted from copyright status.determined_date and '[name of copyright holder]' from copyright status.determiner. If this needs to be something beyond that then I have no objections.

**Comment by Jegelewicz** [comment]
@krgomez see Dusty's comment above.

**Comment by krgomez** [comment]
If what you are suggesting would work, would this still be a new attribute? If not, where would it display?

In theory this makes sense to me. However I'm not totally convinced that it would result in accurate notices.

> '[year of first publication]' could be extracted from copyright status.determined_date

We are indeed thinking of the copyright status determined date as the published date. We do not record a date here unless the published date is known, so right now most don’t have a determined date. But this part of what you’re suggesting makes sense.

> ‘[name of copyright holder]' from copyright status.determiner

We have used unknown as the determiner when it is not clear who the copyright holder is. However we do NOT want the copyright notice to read © unknown — that is misleading. We are using © artist or artist’s estate and would like to continue to use that. On the other hand, maybe it would be possible to create a new agent called "artist or artist's estate". Also, sometimes a rights holder or another entity that licenses the work specifies a notice be written in a very specific way and we need the flexibility to record it as they wish in those cases. An example of this would be works that are licensed by the Artists Rights Society, such as: © Frank Badur / Licensed by Artists Rights Society (ARS), New York. This actually brings up another issue which is that we need a way to keep track of this kind of relationship in Arctos, which is something I'm hoping we can express in the rights module.

**Comment by dustymc** [comment]
>where would it display?

I haven't completely worked that out, but I'm hoping to extract "virtual columns" from the JSON attribute cache in FLAT, and I don't think those would have to be straightforward - I see no reason (yet, perhaps!) that I couldn't build them up with bits and pieces of other data, as long as I can get it from the Attributes cache.

>not totally convinced that it would result in accurate notices.

Agreed - I think this is more complexity than I can realistically deal with, you're just going to have to add and maintain the data.

>new agent

I would not be enthusiastic about creating another variation of Agent Zero.

>keep track of this kind of relationship in Arctos

Anything that uses agent.agent_id as a foreign key creates very specific relationships between Agents and catalog records. If there are two agents involved, you almost certainly need two data objects in the catalog record.

>express in the rights module

Again, I don't see the rights module being something that you'll write data to - I'm still envisioning a series of scripts and a cache, a way to display some data that might take a few clicks to find now in one place.

**Comment by Jegelewicz** [comment]
> If there are two agents involved, you almost certainly need two data objects in the catalog record.

Or you can create a group agent...

**Comment by Jegelewicz** [comment]
> we do NOT want the copyright notice to read © unknown — that is misleading

Rather than some new agent - couldn't we just display "artist or artist's estate" with no link to the agent whenever the determiner agent = unknown?

**Comment by dustymc** [comment]
>group

Well sure, but "© Frank Badur / Licensed by Artists Rights Society" sounds like two agents doing two things to me - you might want to query them, perhaps in specific roles, independently.

Or not; perhaps the goal is truly only to create a text field with a label, and nobody cares about the details beyond that. 

>display "artist or artist's estate" 

Probably, but that puts us in the position of predicting how this will be used, and that inevitably leads to code looking like data and generally not being sustainable.

**Comment by krgomez** [comment]
> Again, I don't see the rights module being something that you'll write data to - I'm still envisioning a series of scripts and a cache, a way to display some data that might take a few clicks to find now in one place.

In that case, there are a few things that I listed in #2450 that we need to figure out a place for. Right now I use a spreadsheet to keep track of copyright research, restrictions, and contact information. I would really like to be able to add this information to Arctos. If we move the contents of our copyright status remarks (all that's currently there are copyright notices) to a copyright notice attribute, then I could see using the copyright status remarks to record research and restrictions.

**Comment by krgomez** [comment]
> I could see using the copyright status remarks to record research and restrictions

Except that those remarks would need to be encumbered, yet the copyright status value should be visible to public users. Maybe we need to continue to keep any copyright research in a spreadsheet for now. 

Do you have any new thoughts on the proposal of a new copyright notice attribute?

Alternatively, is there a different way of presenting the copyright notice and the copyright status expressed through a statement from rightsstatements.org together in one attribute that would allow for both to be downloaded separately? We need to be tracking and presenting the copyright status and notice as well as tracking copyright research and other rights issues related to a specific object, but this needs to be encumbered.

**Comment by krgomez** [comment]
Just checking in on this issue. I still think it would be best to record the copyright notice as its own attribute so that it can be downloaded.

**Comment by Jegelewicz** [comment]
@krgomez given all of the discussion above, I do think an attribute would be best, just as you created the request above. And maybe you would also like a second attribute "copyright restrictions" or something like that to record the "in house" stuff that could be encumbered in the way "value" can be?

@ArctosDB/arctos-code-table-administrators

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
sounds good to me

**Comment by Jegelewicz** [comment]
Suggest we add as originally proposed.

**Comment by Jegelewicz** [comment]
Code Tables says go

**Comment by Jegelewicz** [comment]
Added to EH collections as well.

**Comment by krgomez** [comment]
Wonderful! Now my question is, how do I go about moving copyright notices from the copyright status attribute remarks to this new attribute? Is this something you might be able to help with @dustymc?

**Comment by Jegelewicz** [comment]
I think I can help you with that. Give me a minute...

**Comment by Jegelewicz** [comment]
Nope - I get a timeout. @dustymc how about some sql that lets me get all attributes of type copyright status along with their GUID for a specified collection (UAM:Art)? I think I can get it done from there.

**Comment by dustymc** [comment]
select guid,attributes.* from flat inner join attributes on flat.collection_object_id=attributes.collection_object_id where flat.guid_prefix='UAM:Art' and attribute_type='copyright status'

**Comment by Jegelewicz** [comment]
Thanks - added to cheat sheet.

**Comment by Jegelewicz** [comment]
@krgomez the attached file has two tabs, the first is a download of all of your copyright status attributes, the second (UAM_ART_copyright) is a start for a file to upload using the [Bulkload Attributes](https://arctos.database.museum/tools/BulkloadAttributes.cfm) tool with the new copyright notice attribute. You'll need to fill in at least the determiner and date fields but you can add information in determined method and remarks too. Once you have the file complete, save it as csv and upload it to the tool. If you have any issues, just let me know here. If it all works as expected, you can close this issue.
[UAM_Art_copyright.xlsx](https://github.com/ArctosDB/arctos/files/9378129/UAM_Art_copyright.xlsx)

**Comment by krgomez** [comment]
This is great, thank you Teresa! Should I unload all of the copyright status attributes and reload them without the notices in the remarks? I've never unloaded an attribute, so just checking. I don't think it hurts to have the notice in the remarks of this attribute, but I would rather it only be recorded in the copyright notice attribute.

**Comment by krgomez** [comment]
I unloaded the copyright status attributes, reloaded them without the notices in the remarks, and uploaded the copyright notice attributes. All went well. Closing issue!
