### ISSUE TITLE
Display/Hide Part Attributes in Catalog Record

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2864]
Request for option to display/hide part attributes in Part Table of Catalog Record, to minimize clutter and simplify display. This could be part of expand/collapse for the current table.

**Comment by campmlc** [comment]
#2848 #2865

**Comment by dustymc** [comment]
Pros: Yay, less clutter

Cons: Part will say "thing you want." "Stuff that makes it totally unusable to you" will be hidden behind a click-or-something.

"Preservation" will roughly correspond with data in parentheses.

For scale there are currently 556 unique used parts that contain parens, 2402284 total parts.

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/1460

**Comment by campmlc** [comment]
Show/hidden option should be an operator decision - we can train our
operators. Perhaps we need a "suitable for tissue, for details contact
collection" flag visible to the public.
As for parts, this - 556 unique used parts that contain parens - is exactly
why the current system is non-functional for data entry or searching, and
why we need to split part from preservation. But we need the most recent
preservation visible without a huge mess of tables within tables in the
public and operator views.

**Comment by dustymc** [comment]
>operator decision 

Also general public - eg, people trying to decide if they want to ask to borrow a part or use data.

>suitable for tissue

I've got a formula to calculate that for the record, I don't think it would be technically difficult to adapt it to individual parts. That would be a fair bit of processing, which can probably be a separate discussion if necessary.

>most recent preservation visible

This is where I keep getting lost; there's nothing about 'most recent' that particularly influences what the part is useful for, so this just seems misleading to me.

**Comment by Jegelewicz** [comment]
> 
> 
>     most recent preservation visible
> 
> This is where I keep getting lost; there's nothing about 'most recent' that particularly influences what the part is useful for, so this just seems misleading to me.

It tells you the current state of the thing - is it in a jar of formalin NOW or has it since been frozen?

**Comment by campmlc** [comment]
One option would be to concatenate preservation history in a separate
display field from the part: "preservation history: (1) formalin, 10% (2)
ethanol, 70% (3) dried" or "(1) ethanol, 95% (2) ethanol, 70%" or "(1)
ethanol, 95% (2) frozen, LN2 (3) frozen, -80C"

**Comment by dustymc** [comment]
>tells you the current state of the thing

I think people are mostly interested in fit for purpose. If they see "frozen" they'll assume it's useful for genetics, then decide Arctos is broken (which would be hard to refute) when they figure out it was in formalin but we're hiding that.

>concatenate preservation history

Displaying a summary seems reasonable and compact. Only distinct values should be sufficient - 30 determinations could get squished down to 'bleach; frozen."

**Comment by campmlc** [comment]
that works!

**Comment by campmlc** [comment]
This could be with the "expand preservation history" option which would
open up part attributes . . .
