### ISSUE TITLE
Concatenate Part Attribute Preservations with Part Name

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2865]
Request to add part attribute preservation to concatenated display with part name in the parts table of Catalog Record, to allow both part and preservation to be visible in current "part name" field when we split part from preservation.

**Comment by campmlc** [comment]
#2848

**Comment by Jegelewicz** [comment]
We discussed this a bit at the code table meeting today as we hope to press forward with #1460 

I think we need to think about preservation as a "special" part attribute. @campmlc pointed out that we do this with Other ID's that include a relationship other than self.

![image](https://user-images.githubusercontent.com/5725767/99737840-64334d00-2a86-11eb-9d22-0f597a2272b2.png)

Currently, preservation is mooshed together with all part attributes, which is not satisfactory if we are really going to separate part and preservation.

![image](https://user-images.githubusercontent.com/5725767/99738571-0869c380-2a88-11eb-8082-06e4eef78177.png)

The way we would like to see preservation in the catalog record would look something like this:

![image](https://user-images.githubusercontent.com/5725767/99739198-7367ca00-2a89-11eb-8914-c2b269014a0e.png)

In addition, we feel that the date and determiner for preservation really should indicate the date the preservation was applied and the agent who did the preserving.

@campmlc @ccicero @ebraker please chime in if this is incorrect or needs modification!

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/3191

I won't argue that the current layout is "correct," but that one has been tried and found to create significant problems for some collections.

>date and determiner for preservation really should indicate the date the preservation was applied and the agent who did the preserving.

What?

**Comment by Jegelewicz** [comment]
> #3191
> 
> I won't argue that the current layout is "correct," but that one has been tried and found to create significant problems for some collections.

This would not be a duplication - preservation would no longer appear in the "Attributes" column.

**Comment by Jegelewicz** [comment]
Also I was thinking about this in my sleep, and it might be good to have the preservation attribute(s) appear in table format just like the rest do so that the information about when and by whom is there.

**Comment by Jegelewicz** [comment]
> 
> 
>     date and determiner for preservation really should indicate the date the preservation was applied and the agent who did the preserving.
> 
> What?

This is probably just documentation. Date and determiner usually imply this person asserted this about the part on this date. For preservation, it would be best to have the date reflect the date the snail was put in formalin or the date it was transferred to ethanol and the determiner would ideally be the agent who performed the preservation action.
