### ISSUE TITLE
Group agents with no members - error viewing agent activity

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2867]
[Royal Ontario Museum Field Party](https://arctos.database.museum/agents.cfm?agent_id=21259276) is a group agent with no members. When you attempt to view the [agent activity](https://arctos.database.museum/info/agentActivity.cfm?agent_id=21259276), this message is displayed:

![image](https://user-images.githubusercontent.com/5725767/86467179-2e1d4880-bcf2-11ea-9a43-900b32dd3843.png)

Also occurred with[ University of California, Davis](https://arctos.database.museum/info/agentActivity.cfm?agent_id=1018111) which I changed to an "organization" and now the error is gone.

I assume the error relates to the fact that the group has no members. Can we create a better error message for this situation?

If my assumption is incorrect, how can we make this better?

Also, how many group agents have no members?

**Comment by dustymc** [comment]
can't replicate
