### ISSUE TITLE
Other Identifiers - merge trapline ID and Trapline ID

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2869]
The [Other ID code table](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type) currently includes:

> trapline ID - Number used to identify a specific trapline.
> Trapline ID - Number used to identify a specific trapline.

Suggest merging these into "trapline identifier" for consistency with capitalization and appearance of other non-specific identifiers (such as collector number and original identifier), then adding a sort number to bring this up to the top of the list.

**Comment by campmlc** [comment]
This sounds like a good idea.
