### ISSUE TITLE
Code Table View Template

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2872]
I would like to make the public view of our code tables consistent and user-friendly. I put together a template for this [here](https://docs.google.com/document/d/1f3oR9MpPwMF3oY2cresakTae-UXjJofQurokL41RJ5U/edit?usp=sharing).

@ArctosDB/arctos-code-table-administrators take a look and comment - we can talk about this at our next meeting.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I like this template. I especially like that there is instruction on how to request a new value.

**Comment by ewommack** [comment]
I like the updated information. That will come in handy when directly students and volunteers there, so they know what they are looking at.

**Comment by Jegelewicz** [comment]
@dustymc is there anything preventing me from doing something like this for a single code table to provide an example?

**Comment by dustymc** [comment]
If the intention is to hard-code the stuff at the top, then defensible data management is a pretty compelling reason not to proceed. Suggest that get added to the CT metadata (if what's there isn't already sufficient?), where it can work in APIs and such.

Arctos is data-driven - there's some 'if weird_table then...' code but mostly it's not realistic to write dedicated code for every CT.

**Comment by Jegelewicz** [comment]
Check - let me see how/what will work - also realized that Page Documentation may be best...

Thanks!
