### ISSUE TITLE
Error when attempting to claim reciprocal identifiers

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2873]
There are a bunch of reciprocal identifiers for MSB:Mamm from NMMNH:Mamm that I want to claim and load. When I select one and try to claim it, I get this:

![image](https://user-images.githubusercontent.com/5725767/86493410-b3265300-bd2e-11ea-8646-5b8e9399d4ae.png)

What gives?

**Comment by Jegelewicz** [comment]
@campmlc says

> I think it is because the relationships got caught in the big crash somehow. So they "exist" but something is missing that would allow the reciprocal to make the connection.

**Comment by dustymc** [comment]
This was designed to prevent duplicates by pulling data into "your" loader 27 times, or 9 people all loading the same data all at once. I think that causes more confusion than it prevents. 

This error is caused by PG just being different than Oracle - I could make it work like it has, but I'd need to rewrite a fair bit of code and I'm pretty deep in locality attributes at the moment.

I think I'd prefer to drop the attempts at "pre-uniqueness" and just insert when you pull, no matter what's happened before. I could patch that in, and I think it's probably less confusing to users. Worst case, it results in duplicates which the bulk-unloader can deal with.

**Comment by Jegelewicz** [comment]
OK, not a super rush and I think duplicates in other IDs can be easy to find and clean up with the tools we have, so I think you could drop "pre-uniqueness".

**Comment by campmlc** [comment]
Agree.

**Comment by Jegelewicz** [comment]
@dustymc all of the NMB:Mamm/NMMNH:Mamm reciprocal ids stuck in [here](https://arctos.database.museum/tools/BulkloadOtherId.cfm?action=getRecip) are already in Arctos. I have tried claiming, then deleting them but they WILL NOT GO AWAY! I don;t know what is going on here. But I would like these to be gone.

![image](https://user-images.githubusercontent.com/5725767/88441877-c083aa00-cdcf-11ea-8e13-2f76a5ea5809.png)

**Comment by dustymc** [comment]
I'm not see it - you figured something out?

```

arctosprod@arctos>> select guid_prefix, count(*) from cf_temp_oids group by guid_prefix;
 guid_prefix | count 
-------------+-------
 MVZ:Herp    |   976
 UAM:Bird    |     4
 MLZ:Egg     |     1
 UWBM:Herp   |   220
 UAMObs:Ento |    15
 UAM:EH      |    13
 UAM:Ento    |    55
(7 rows)
```

**Comment by Jegelewicz** [comment]
No - every time I go to https://arctos.database.museum/tools/BulkloadOtherId.cfm?action=getRecip they are there to be "claimed", but when I claim them and verify, they all come back as "identifier exists". I delete them from the tool, return to https://arctos.database.museum/tools/BulkloadOtherId.cfm?action=getRecip and there they are again!

![image](https://user-images.githubusercontent.com/5725767/88461842-68e34e00-ce64-11ea-8752-dbc0a49e08b3.png)

And they DO already exist
![image](https://user-images.githubusercontent.com/5725767/88461849-84e6ef80-ce64-11ea-907c-b21f8bebd3f6.png)

![image](https://user-images.githubusercontent.com/5725767/88461858-97f9bf80-ce64-11ea-8ebe-f33ca9986e3e.png)

but the MSB:Mamm one doesn't show the related info?

**Comment by campmlc** [comment]
Yes, Jon and I have the same problem when we do the identical task. The not
pulling reciprocal data seems to be a broader problem, not just these
records.

**Comment by dustymc** [comment]
I adjusted the scripts, I think it will catch up in a couple days. This needs rebuild to deal with many more collections than the original design anticipated.

**Comment by Jegelewicz** [comment]
I think I have this one figured out?

Currently the identifiers exist in the MSB records but with the "self" relationship instead of the "same individual as" relationship. So, when we try to load them, Arctos says they already exist, but Arctos also sees a one-sided "same individual as" relationship.

I'll try to get it cleaned up by the end of the week.

**Comment by jldunnum** [comment]
That would be great if that was the problem.

Adrienne and Mariel were clearing some out over the past day (message below).

"This is a fresh batch of number. They hadn’t been claimed, validated, or loaded yet. Which means whatever you did yesterday did finally delete everything. I think we just need to make sure that they are truly deleted each time we load them and then we should continue to get new stuff each day. 1000 must be the daily limit.

I went ahead and loaded today’s batch (all NMMNH), so tomorrow’s should be new again. Hopefully!!"

~ Adrienne

______________________________________________________________

Jonathan L. Dunnum Ph.D.
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by campmlc** [comment]
Well, that would make sense! Fingers crossed that is the problem!
