### ISSUE TITLE
higher geography lookup is slow

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#2874]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
higher geography lookup cleaning tool isn't working

**To Reproduce**
1) Reports/Services
2) higher geography lookup
uploaded higher geography lookup for data cleaning and getting this error
Tried it with old files that worked before and it's still throwing the same error
http://arctos.database.museum/DataServices/geog_lookup.cfm?action=validate

**Expected behavior**
for selection of higher geography to show up

**Screenshots**
![image](https://user-images.githubusercontent.com/38706617/86497466-06080680-bd3f-11ea-87cd-5d6466d6a919.png)

** Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**
[highergeog.xlsx](https://github.com/ArctosDB/arctos/files/4871461/highergeog.xlsx)

**Priority**
Github isn't letting me choose a label right now...

**Comment by mvzhuang** [comment]
@dustymc Dusty, I'm for some reason unable to add labels to issues. Did something change in permissions or something?

**Comment by dustymc** [comment]
@mkoo @Jegelewicz should Arctos Users have Write on ArctosDB/Arctos or is that some other Team (which @mvzhuang should be a part of)?

https://github.com/orgs/ArctosDB/teams/arctos-users/repositories

**Comment by mkoo** [comment]
Vicky, see if you can now!

**Comment by mvzhuang** [comment]
Yay it's fixed! Thanks!

**Comment by mkoo** [comment]
ok then fixed for Arctos Users group then!
thx for the issue

**Comment by Jegelewicz** [comment]
Yes labels work, but @dustymc still needs to resolve the issue....

**Comment by dustymc** [comment]
The original issue is fixed, but stripGeogRanks isn't performing adequately, and it's going to take some time to somehow address that. 

Needs prioritized.

**Comment by dustymc** [comment]
Looks like PG's generated columns would serve this purpose, but that only exists in PG12 and my test box is PG11.

**Comment by dustymc** [comment]
Blocked by https://github.com/ArctosDB/internal/issues/65, going back to needs discussion

**Comment by dustymc** [comment]
Played with this some more, the issue seems to be that geography has grown by a great deal, largely with the addition of "subquad" data in quad, and partially from eg https://github.com/ArctosDB/arctos/issues/1278 ("minor" features are treated as geography). 

I've reduced the defaults on the form so it's more functional, but remains slow, albeit still probably orders of magnitude faster than not having the form.

Two obvious possibilities:

1. Rethink geography - can we resolve https://github.com/ArctosDB/arctos/issues/1366, and will that resolution result in fewer things being treated as geography?
2. Do the heavy lifting at create/update - add "stripped_{thing}" columns (default stripgeogranks() ) for every column, and cache in them the data the service uses to predict intention. (PG12 has a very nice mechanism for this, as above we don't have a PG12 test environment, so "now" is a bit optimistic unless we want to fall back to a more kludgy mechanism.)

**Comment by Jegelewicz** [comment]
@dustymc is this only an issue for the various components? So if I use option 2 and the strings I enter are only compared to the concatenated higher geog strings, would that be less problematic?

**Comment by Jegelewicz** [comment]
I mean, I see the misspelling in California - why is Tehama County the problem?

**Comment by dustymc** [comment]
Merging https://github.com/ArctosDB/arctos/issues/1105 here - if we keep this these need added to stripgeogranks

```
Autonomous
and
Area
Atoll

canton
changwat
County
Counties
Census

Division
District

Hsien

Krai
kray

Municipo
Municipality

Oblast
of

Province
Prefecture

Region
Regional

state

United

Xiàn

accented characters (??)
```

**Comment by Jegelewicz** [comment]
@dustymc can we please make this better? See https://github.com/ArctosDB/data-migration/issues/1147

**Comment by dustymc** [comment]
Yep, the component loader ecosystem gets around my problems, I'll go next task.

**Comment by Jegelewicz** [comment]
Loaded the Bell file at 6PM MDT at 6:04 this was returned

![image](https://user-images.githubusercontent.com/5725767/159816263-313dfadb-e500-4e24-8ff3-83b125c77299.png)


At that rate, it will take me like 20 hours hitting refresh every 4 minutes to check the whole list of higher geography for the Bell mammals....

**Comment by dustymc** [comment]
Next release.

Even the component loader wasn't able to handle the function-manipulated data at a reasonable rate, I rebuilt stripGeogRanks and added generated stripped_{field} terms to geog_auth_rec. It's some junk to store, but I think we can afford that (its tiny compared to spatial data) and processing is now reasonably fast.

The loader returns up to 10 possible matches, and a status value that will hopefully help sort them out. "Just use the first" is probably a mostly-sorta-defensible position for eg, an incoming collection - it likely won't be WRONG most of the time, but it will probably not be of quite the right precision for lots of data.

@Jegelewicz (or anybody else) if you've got any "raw" data - the uglier the better - please pass it along, there's room for lots of tuning.

**Comment by Jegelewicz** [comment]
try this
[geography test.csv](https://github.com/ArctosDB/arctos/files/8961018/geography.test.csv)

**Comment by dustymc** [comment]
thx, script is a little smarter than it used to be.

[cf_temp_geog_lookup_download.csv.zip](https://github.com/ArctosDB/arctos/files/8962302/cf_temp_geog_lookup_download.csv.zip)
