### ISSUE TITLE
Locality Attribute - Drainage

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2875]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Goal**
The goal is to put this somewhere it can be consistently recorded until such time we have the capability to manage drainages spatially.

**Context**
Drainage is an important concept for fish, invert and a few other collections. Right now we have some drainage info in locality remarks and some in higher geography (probably some in object remarks and elsewhere too).

**Table**
What ever the Locality attribute Code table ends up being called

**Value**
drainage basin

**Definition**
Any area of land where precipitation collects and drains off into a common outlet, such as into a river, bay, or other body of water. https://www.wikidata.org/wiki/Q166620

**Attribute data type**
categorical

**Attribute value**
All the stuff found [here](https://w.wiki/V$W) and we add new values there - an opportunity to try using an external source? If not, we can create a code table "Drainage" and add the stuff we need. I think it will be helpful to enforce some consistency so we can find stuff when/if we figure out the spacial use for this.

**Attribute units**
none

**Part tissue flag**
N/A

**Other ID BaseURL**
N/A

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
```
arctosprod@arctos>> \d geog_auth_rec
                                     Table "public.geog_auth_rec"
        Column         |          Type           | Collation | Nullable |           Default            
-----------------------+-------------------------+-----------+----------+------------------------------
 geog_auth_rec_id      | bigint                  |           | not null | 
 continent_ocean       | character varying(50)   |           |          | 
 country               | character varying(50)   |           |          | 
 state_prov            | character varying(75)   |           |          | 
 county                | character varying(50)   |           |          | 
 quad                  | character varying(38)   |           |          | 
 feature               | character varying(50)   |           |          | 
 island                | character varying(50)   |           |          | 
 island_group          | character varying(50)   |           |          | 
 sea                   | character varying(50)   |           |          | 
 valid_catalog_term_fg | smallint                |           | not null | 1
 source_authority      | character varying(255)  |           | not null | 'unknown'::character varying
 higher_geog           | character varying(255)  |           | not null | 
 stripped_key          | character varying(4000) |           | not null | 
 geog_remark           | character varying(4000) |           |          | 
 wkt_polygon           | text                    |           |          | 
 drainage              | character varying(255)  |           |          | 
 wkt_media_id          | bigint                  |           |          | 
```

??

**Comment by Jegelewicz** [comment]
So do we want drainage in Higher Geography or do we want it as an attribute? I thought it was one of the things we had discussed moving out of Higher Geography.

I'm good either way, just want to have the discussion before I go adding a bunch of drainages.

**Comment by dustymc** [comment]
I can't keep up with what we've discussed - there's a plea for a summary somewhere. Currently:

1. The "authority" WKT represents the intersection of all the columns in geog_auth_rec.
2. The "assertion" WKT (locality) represents whatever's described in locality, including attributes (currently only geology) if there are any. It should be within the "authority," a check which would be lost by moving to attributes.
