### ISSUE TITLE
Locality Attribute - waterbody

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2876]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Goal**
The goal is to put this somewhere it can be consistently recorded until such time we have the capability to manage bodies of water spatially. Also to give us a place to properly record [DwC waterBody](https://dwc.tdwg.org/terms/#dwc:waterBody).

**Context**
Waterbody (ocean, lake, river, etc.) is an important concept for fish, invert and a few other collections. Right now we have some waterbody info in locality remarks and some in higher geography (oceans) and (probably some in object remarks and elsewhere too).

**Table**
What ever the Locality attribute Code table ends up being called

**Value**
body of water

**Definition**
Any significant accumulation of water, generally on a planet's surface. https://www.wikidata.org/wiki/Q15324

**Attribute data type**
categorical

**Attribute value**
All the stuff found [here](https://w.wiki/V$X) and we add new values there - an opportunity to try using an external source? If not, we can create a code table "waterbody" and add the stuff we need. I think it will be helpful to enforce some consistency so we can find stuff when/if we figure out the spacial use for this.

**Attribute units**
none

**Part tissue flag**
N/A

**Other ID BaseURL**
N/A

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
>waterbody
>Drainage

Typo?

>when/if we figure out the spacial use 

If there's spatial data, you can pull strings from several sources. I'm not saying consistency isn't important in that case, but it's much more critical without spatial. Spatial authority data is in geog_auth_rec; if these are "geography" then they should be somehow tied tightly to that, not 2 joins away. If they're seen as locality attributes (eg, search terms) then this approach is fine.

**Comment by Jegelewicz** [comment]
> Typo?

Yep, copy pasta - edited

> Spatial authority data is in geog_auth_rec; if these are "geography" then they should be somehow tied tightly to that, not 2 joins away. If they're seen as locality attributes (eg, search terms) then this approach is fine.

They are both spatial information and search terms. Because there was a "Mississippi Sound Project" I can expect that people will look in locality for "Mississippi Sound", but with the current terms in our geography structure, I don't know where they would look. We need better structure for stuff collected on 70% of the planet.

Where should I put "[Mississippi Sound](https://en.wikipedia.org/wiki/Mississippi_Sound)" in our current Higher Geography structure? Sea? Who will search for it there?

**Comment by sharpphyl** [comment]
See https://github.com/tdwg/dwc-qa/issues/128 for a related supporting comment.  It appears that issue is still open and concerns the separation of continent and waterbodies to be consistent with DWC fields used by aggregators..

**Comment by Jegelewicz** [comment]
Important for ALMNH:Inv collection localities.

**Comment by dustymc** [comment]
>70% of the planet.

New geography model:

* first_level_geog_term (continent, ocean, maybe even region - huge natural things)
* second_level_geog (island group, sea, drainage - big natural things)
* third_level_geog (island, waterbody, bay - small(er) natural things)
* first_level_political_term (country)
* second_level_political (state)
* third_level_political (county)
* special_political_thingee (national park, marine reserve)

and maybe quad, because it's pretty integrated into various workflows

Ta-da?

**Comment by sharpphyl** [comment]
How many terms can be at each level?  Both a continent and an ocean (waterbody)?

**Comment by Jegelewicz** [comment]
@dustymc HAHAHAHA!!!! @mkoo and I are getting to this as we work with @Erober45 

The interesting thing we noticed is that we are mixing spacial geography with political boundaries and that maybe we should split those things up. More to come once we have our plan ready for prime time.

**Comment by dustymc** [comment]
>How many 

I'm just throwing crazy ideas out at this point.

>ocean (waterbody)

That's one of the distinctions I'd drop. "Lake Superior" would be a fine waterbody. I don't know if it's on a continent or not - I think I'm hearing from DWC that the answer is a simple "no" but it sorta is (sorta...) so ????????

@Jegelewicz both political things and "geography" can be spatial. I think the spatial component will always be the intersection of everything that's given; the parts of ``special_political_thingee`` that are in ``third_level_political``, ``third_level_geog``, _**and**_ ``maybe quad``, even if that's 2 acres (which leads back to "how small is too small?").

**Comment by Jegelewicz** [comment]
> both political things and "geography" can be spatial

True - but they can serve different purposes for people. The political divisions are important for relating to permits and often as an aid in finding physical objects in the collection, the other special thingees might do that too (Parks and islands for example), but any given location needs to be able to relate to them all.

If HG = Continent/Ocean + political division and all the rest of the things are add-ons (overlays), then geography would probably be  more functional?

**Comment by dustymc** [comment]
>political divisions

The current model and what I've "proposed" do that (almost) - all 9764 things that say "Bla County" are within Bla County, some (probably all but one) of them are just subdivisions.

Stuff from B

**Comment by dustymc** [comment]
Tabling, but see also https://github.com/ArctosDB/arctos/issues/2374 - we might need a place for them should we manage to come up with placenames.
