### ISSUE TITLE
Okinawa - Duplicate higher geography

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2877]
We have two versions of Okinawa Island in Higher Geography that represent the same thing.

![image](https://user-images.githubusercontent.com/5725767/86532779-ac602300-be89-11ea-9477-d5e9f11d9669.png)

[Asia, Japan, Okinawa Island, Okinawa](https://arctos.database.museum/Locality.cfm?Action=editGeog&geog_auth_rec_id=1005103)

and

[Asia, Japan, Okinawa Prefecture, Ryukyu Islands, Okinawa](https://arctos.database.museum/Locality.cfm?Action=editGeog&geog_auth_rec_id=10000370)

As Okinawa Prefecture encompasses all of the Island of Okinawa (see https://en.wikipedia.org/wiki/Okinawa_Prefecture), I suggest we change all localities using Asia, Japan, Okinawa Island, Okinawa as higher geography to Asia, Japan, Okinawa Prefecture, Ryukyu Islands, Okinawa and remove Asia, Japan, Okinawa Island, Okinawa from Arctos.

**Comment by Jegelewicz** [comment]
@lin-fred and @mvzhuang I changed the higher geog for NMMNH and UTEP localities already.

**Comment by lin-fred** [comment]
I agree, looks good to me

**Comment by mvzhuang** [comment]
Sounds good

On Jul 6, 2020 8:45 AM, Lindsey NMMNHS <notifications@github.com> wrote:

I agree, looks good to me

-

**Comment by sharpphyl** [comment]
I'm fine with the change.

**Comment by Jegelewicz** [comment]
Anyone using the Asia, Japan, Okinawa Island, Okinawa higher geography, should change to Asia, Japan, Okinawa Prefecture, Ryukyu Islands, Okinawa.

Here are the affected records https://arctos.database.museum/SpecimenResults.cfm?geog_auth_rec_id=1005103
