### ISSUE TITLE
Google Results on search for Arctos

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2878]
Searched for Arctos this morning and got this

![image](https://user-images.githubusercontent.com/5725767/86591196-50ab9d80-bf4e-11ea-889e-241baa0c4630.png)

![image](https://user-images.githubusercontent.com/5725767/86591238-691bb800-bf4e-11ea-8db3-1e46cf321f6b.png)

**Comment by dustymc** [comment]
Google seem to have wandered out of the corner it trapped itself in, again. Closing.
