### ISSUE TITLE
part name additions

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#2880]
Could we add the following parts to the [part name code table](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name) for the UA data migration (ES collection code)?

zygosphene:  A median process on the anterior part of the neural arch of the vertebrae of most snakes and some lizards, which fits into a fossa called the zygantrum on the posterior part of the arch. (adapted from https://en.wiktionary.org/wiki/zygosphene)

paradiapophysis (=synapophysis): a projection on vertebrae lying lateral to the anterior cotyle; can exhibit separate parapophyseal and diapophyseal facets.

**Comment by Jegelewicz** [comment]
See https://github.com/ArctosDB/arctos/issues/2612#issuecomment-619267468

**Comment by acdoll** [comment]
Thanks @Jegelewicz. So, how did you end up handling this? Early on, I had suggested using vertebra and putting the details in the remarks, but they didn't love that idea. There are so many bone types out there (and in the list already) it seems like they could use their own code table; especially if we're including bone parts. The agenda from the May AWG meeting pushed discussion of this off to the Code Table Admins, was there any consensus about this?

**Comment by Jegelewicz** [comment]
> it seems like they could use their own code table

That's definitely on the list of possibilities: part=bone, attribute=bone name or attribute=bone part

> The agenda from the May AWG meeting pushed discussion of this off to the Code Table Admins, was there any consensus about this?

Nope, we didn't get to it, but I can bump it up for our meeting next week.

> how did you end up handling this? Early on, I had suggested using vertebra and putting the details in the remarks,

If you are itching to get the stuff in, I say go with using vertebra and being as consistent as possible with the more detail name in part condition:

part name = vertebra
part condition = partial, zygosphene only

**Comment by acdoll** [comment]
Thanks - I'll run this by them.

**Comment by dustymc** [comment]
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_attribute_part was designed to help keep the main table clean while providing a place for standardized more-specific "subparts" for those who need it. I don't know if it's ever been used.

part name = vertebra
part condition = partial, zygosphene only

I think that's fairly normal. It doesn't support search for zygosphene (which will be misspelled and abbreviated and etc.), but I've not been very successful at finding that sort of use case either.

**Comment by acdoll** [comment]
I'm not really familiar with using the part attributes; I didn't know there was an option for part subparts. I don't even see where you would possibly enter that. Is it through the part attributes? All I see there is:
![image](https://user-images.githubusercontent.com/12507297/86809694-5f22b380-c039-11ea-84a8-b7da680d356d.png)
Is that collection type specific? Also, is that something that can be part of a bulkload or do records need to be modified after entry?

**Comment by Jegelewicz** [comment]
I don't think anyone has made use of that table. But if you want you can be a pioneer. Here is how I think it would work:

part name = vertebra

part attribute = subpart name
part attribute value = zygosphene

We would need to create the subpart name attribute and associate it with the https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_attribute_part and create zygosphene in that table. @dustymc can confirm this course of action or tell me what really needs to happen.

Part attributes cannot currently be added with the bulkloader. For NMMNH Paleo, I entered all parts separately after the records were loaded as you can bulkload parts with their attributes associated with a catalog item via catalog number using the Part bulkload tool.

**Comment by Jegelewicz** [comment]
relevant to #3044

**Comment by Jegelewicz** [comment]
If we could use the online ontology - here it is - https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_4200190

**Comment by acdoll** [comment]
> if you want to reinstate the original request, we could go with that too.
No need to create that part for now; they agreed that going with the general 'vertebra' and indicating 'zygosphene' in the condition or attribute would allow it to be found in more searches. However, if we were to incorporate that ontology, or something like it, I would probably reconsider. I think this would greatly improve the search results for outside users; as long as the search had the option for 'exact' or 'including all subparts'.

**Comment by Jegelewicz** [comment]
Cool, I'm going to close this - we can get to it from the ontology discussion if necessary.
