### ISSUE TITLE
Bulk Edit Container error

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2882]
Trying to use bulk edit container to change a bunch of legacy research material cryovial labels to cryovials in order to be able to use batch tools -> part to containers to add parts to the cryovials.   I'm attaching the original csv file, a pdf of the data on the screen, and a screenshot of the error message.
[First Cut Research Freezer BulkContainer Edit.zip](https://github.com/ArctosDB/arctos/files/4881233/First.Cut.Research.Freezer.BulkContainer.Edit.zip)
[Bulk Edit Container.pdf](https://github.com/ArctosDB/arctos/files/4881236/Bulk.Edit.Container.pdf)
![Screenshot 2020-07-06 15 08 07](https://user-images.githubusercontent.com/14808196/86644765-0e5c7d80-bf9b-11ea-972d-55ba546e9d18.png)

**Comment by dustymc** [comment]
Rebuilt the function - suggest carefully checking with a couple of records.

**Comment by campmlc** [comment]
Now getting following error:
![Screenshot 2020-07-14 13 07 14](https://user-images.githubusercontent.com/14808196/87466496-919d5500-c5d3-11ea-87de-fb0a96808244.png)
[Fixing CRYO3 May 2020 ABD bulk edit container.zip](https://github.com/ArctosDB/arctos/files/4920813/Fixing.CRYO3.May.2020.ABD.bulk.edit.container.zip)

**Comment by dustymc** [comment]
datatype fixed

**Comment by campmlc** [comment]
Thanks - all containers are now updated to freezer boxes, but the positions were not created. There is another issue somewhere about being able to create positions with this form. I need to be able to create freezer box positions in bulk.  If this form can't be used for that, then we should delete the extra columns from the template.
