### ISSUE TITLE
Parts to Containers - omit subsamples

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2883]
Using the Parts to Containers tool for legacy material that was previously loaned but not barcoded; need a way to designate the part added to a barcode is the parent part, not the subsample on loan. I need this to complete a grant funded project on a short timeline.

**Comment by campmlc** [comment]
Here is the file I am trying to load, and the error:
[Barcode Upload First Cut.zip](https://github.com/ArctosDB/arctos/files/4920872/Barcode.Upload.First.Cut.zip)
![Screenshot 2020-07-14 13 28 20](https://user-images.githubusercontent.com/14808196/87468019-19845e80-c5d6-11ea-8726-5422aa44763e.png)

**Comment by campmlc** [comment]
I really need this tool to work as soon as possible in order to put several hundred legacy parts into containers for a large and important loan. If the tool is too much trouble, please just add the non-subsample parts from the attached file to their respective barcodes.
[Barcode Upload First Cut.zip](https://github.com/ArctosDB/arctos/files/4941074/Barcode.Upload.First.Cut.zip)

**Comment by dustymc** [comment]
done
