### ISSUE TITLE
MSB Bird Loan List Report

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2884]
Please fix the MSB Bird Loan List and MSB Bird Loan List by Catnum reports so that they work. Do we have some clear documentation as to what needs to be done to all these legacy reports to convert them to being functional in PG?

**Comment by dustymc** [comment]
I'd need the handler names to do anything. Most of the problems have been decode needs converted to case, and to_number needs converted to ::int.

**Comment by campmlc** [comment]
Here are some of the handler names for reports we need to be functional:
 MSB_Bird_loan_list
 MSB_Bird_loan_list_by_catnum
MSB_Para_loan_header
MSB_Para_loan_invoice
MSB_Para_loan_invoice_NK_and_host
MSB_Fish_Loan_header
MSB_Fish_loan_invoice
MSB_Herp_Loan_Invoice
MSB_Para_4dram_label_NK

**Comment by dustymc** [comment]
Merging this into https://github.com/ArctosDB/arctos/issues/2729

I put some recipes in there, MSB_Bird_loan_list should be fixed, I'll get to the rest when I can if you don't get there first.

**Comment by campmlc** [comment]
Thanks - MSB_Bird_Loan_list worked.
