### ISSUE TITLE
Request for SQL

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2885]
@dustymc can you write some SQL that will create a table like this?

GUID | COUNT of PART

I'd like to know the number of parts associated with each GUID for a single collection - NMMNH:Paleo

**Comment by dustymc** [comment]
select guid,count(*) ptc from flat left outer join specimen_part on flat.collection_object_id=specimen_part.derived_from_cat_item where flat.guid like 'NMMNH:Paleo:%' group by guid

**Comment by Jegelewicz** [comment]
Thanks! but I got some weird results. [NMMNH:Paleo:1101](https://arctos.database.museum/guid/NMMNH:Paleo:1101) has no parts, but the SQL returned 1 for this record.

[Arctos SQL Count Parts.zip](https://github.com/ArctosDB/arctos/files/4885852/Arctos.SQL.Count.Parts.zip)

**Comment by Jegelewicz** [comment]
Added to [Cheat Sheet](https://docs.google.com/document/d/15e3b8WNErFPqg1SW-QNq0nI_RjiEEZjWQDznxIJNFHE/edit#heading=h.hlju12biq40). Change if above is fixed.

**Comment by dustymc** [comment]
select guid,count(specimen_part.derived_from_cat_item) ptc from flat left outer join specimen_part on flat.collection_object_id=specimen_part.derived_from_cat_item where flat.guid like 'NMMNH:Paleo:%' group by guid

**Comment by Jegelewicz** [comment]
Added new code to cheat sheet.

Thanks!!!!!
