### ISSUE TITLE
Provide possibilities when searching Agents

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2892]
When using https://arctos.database.museum/agent.cfm to search you only get results for EXACT matches. Would like to get possible matches from which you can select the name you want.

**Comment by AJLinn** [comment]
I don't think this is true. If so, how would I get all these? I'm not logged in.

<img width="905" alt="Screen Shot 2020-07-09 at 12 03 13 PM" src="https://user-images.githubusercontent.com/17605945/87085377-40a8ed80-c1dc-11ea-8751-872cebbd1a13.png">

**Comment by Jegelewicz** [comment]
Well, this happens

![image](https://user-images.githubusercontent.com/5725767/87085980-0ba59680-c1ee-11ea-88b3-75c11fed59c3.png)

**Comment by Jegelewicz** [comment]
Maybe this is only returning people, not groups or organizations?

**Comment by dustymc** [comment]
I believe it's looking for any name, but as a "word."

**Comment by AJLinn** [comment]
I think you're onto something! Seems to be only returning people. Except is just gave me this when I searched for "NPS" (which it must have subsequently changed to "United States National Park Service"
<img width="586" alt="Screen Shot 2020-07-09 at 12 14 45 PM" src="https://user-images.githubusercontent.com/17605945/87086296-de50ec80-c1dd-11ea-8814-cd5e63cdb4f6.png">

**Comment by dustymc** [comment]
>searched for "NPS" 

That's an exact-match to a name (although I'm not sure if I believe it's in Kew or not!).

<img width="301" alt="Screen Shot 2020-07-09 at 1 25 16 PM" src="https://user-images.githubusercontent.com/5720791/87087260-a77fd400-c1e7-11ea-87bd-a4afa81ecb78.png">

**Comment by Jegelewicz** [comment]
But what's going on? There are definitely agents with Arctos in their name...

**Comment by dustymc** [comment]
but apparently none where "Arctos" _is_ a name.

**Comment by Jegelewicz** [comment]
So it is only returning matches to some name - all those "Wayne"s have Wayne as a first name somewhere. Does it have to be this way? I mean, I can add "Arctos" as an aka to all those Arctos groups, but this is pretty limiting - people are used to Google. If we can't even find parts of names that is far below people's expectations since Google offers up "did you mean" options....

**Comment by dustymc** [comment]
> Does it have to be this way?

Nope.

**Comment by Jegelewicz** [comment]
Cool. If we could get results that also include whatever was searched I think that would solve my problem. Sorry to be a pain.
