### ISSUE TITLE
Scrolling tables

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2895]
See https://docs.google.com/document/d/1f3oR9MpPwMF3oY2cresakTae-UXjJofQurokL41RJ5U/edit?usp=sharing

Could we set up the tables to show a specific number of rows and include a scroll bar so that the explanatory text at the top is always there? This table isn't a good example, but for long ones, it would help keep the amount of scrolling back to the top to find the filter and "back to list" stuff.

@mkoo suggests a way to make this a thing all over the place. I'm leaving it up to you guys!

**Comment by dustymc** [comment]
There are various tools which can do this, I think they all introduce other problems. (But I'm biased and generally don't like things that mess with native layout; happy to try whatever if there's some specific recommendation/consensus.)

Tentatively tabling.
