### ISSUE TITLE
New Part Preservation Type - fossil, compression

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2899]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Goal**
describe the way a fossil was preserved

**Context**
Compression fossils are formed differently from fossil molds and casts

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_preservation

**Value**
fossil, compression (using this format to aid with sorting in the code table)

**Definition**
A compression fossil is a fossil preserved in sedimentary rock that has undergone physical compression. https://en.wikipedia.org/wiki/Compression_fossil

**Collection type**
ES

**Attribute data type**
N/A

**Attribute value**
N/A

**Attribute units**
N/A

**Part tissue flag**
N/A

**Other ID BaseURL**
N/A

**Priority**
Please assign a priority-label.

Note: denies tissueness

**Comment by Jegelewicz** [comment]
@Nicole-Ridgwell-NMMNHS @dperriguey @mbprondzinski @aklompma @ArctosDB/arctos-code-table-administrators this is our code table update of the week. Any objections to this? If none, I will add on Friday.

/remind me to check this on Friday

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Glad to see this get added!

**Comment by mbprondzinski** [comment]
Never heard of it.  Adiel?

**Comment by mbprondzinski** [comment]
I see it relates to plants...
