### ISSUE TITLE
Need to add whole organism to ES collections - error

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2900]
Trying to add whole organism to ES collections and when I select update this happens:

![image](https://user-images.githubusercontent.com/5725767/87185222-a5c91580-c2a6-11ea-8c37-78a5c2b5499d.png)

**Comment by Jegelewicz** [comment]
Same for adding width attribute

![image](https://user-images.githubusercontent.com/5725767/87199493-5ee41b80-c2b8-11ea-9c10-a2d189808387.png)

I've been able to add other stuff, so this seems kinda random.

**Comment by Jegelewicz** [comment]
@dustymc we really need whole organism added to ES collections - can you help me out with this?

**Comment by dustymc** [comment]
There was an orphaned value, should work now.

**Comment by Jegelewicz** [comment]
Added to ES
