### ISSUE TITLE
Hooray for creating agents within catalog record edit!

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#2903]
I'm not sure how I missed this improvement but I just wanted to have it go on record how friggin' AWESOME the enhancement is of being able to create a new agent from within the catalog record editing page. 
<img width="711" alt="Screen Shot 2020-07-11 at 7 42 49 AM" src="https://user-images.githubusercontent.com/17605945/87227933-6eac4000-c34a-11ea-98d6-93bab364520c.png">

Any time we can increase efficiencies by reducing click-arounds, I say thank you @dustymc ! We're always asking (demanding even) that you to change things and when I happen upon an improvement that I didn't ask for but have been grinding my teeth about without even realizing it, I wanted to acknowledge what an amazing job you do. Happy weekend Dusty!

**Comment by Jegelewicz** [comment]
Needs a newsletter article! @ewommack

**Comment by AJLinn** [comment]
Good idea @ewommack - I can throw a little quick tip together for the next one. :-)

**Comment by ewommack** [comment]
Sounds good! The next one comes out in October, and feel free to add it as an issue to the [Arctos Newsletter Repository](https://github.com/ArctosDB/newsletter/issues). Using the label New Article was really helpful for keeping track for the July newsletter.
If you can't get to it @AJLinn, let me know and I can start the issue.

**Comment by AJLinn** [comment]
done - I'll mark my calendar cuz October is a bit down the road! ;-)
