### ISSUE TITLE
Highlight locality attribute changes.

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2904]
This morning I received this

![image](https://user-images.githubusercontent.com/5725767/87318514-af8c8c00-c4e5-11ea-9c60-bb7a7ff47874.png)

which seems to reflect changes made ages ago!

![image](https://user-images.githubusercontent.com/5725767/87318604-cd59f100-c4e5-11ea-98c8-a6d8ccc57819.png)

![image](https://user-images.githubusercontent.com/5725767/87318677-e5317500-c4e5-11ea-9bc4-7ff1d360fdff.png)

Just passing this on because these need to be sent out in a timely fashion. Also curious why they are just showing up now.

**Comment by Jegelewicz** [comment]
Ohhhhh - it seems like these are geology updates that @dustymc is making? If so, can these be highlighted like the locality stuff? Not an immediate need, but would be nice.

**Comment by dustymc** [comment]
A link and the header from your email would be useful - I can't quite figure out what you're seeing, but I think I know the problem anyway. "Geology" is just sort of dumped in there and could use better UI, especially now that it's in the process of becoming a more "core" component.

**Comment by Jegelewicz** [comment]
https://arctos.database.museum/info/localityArchive.cfm?locality_id=11025908,11029641,11029642,11029643,11029644,11030595,11047064,11047067,11047113,11047148,11047177,11047269,11051660,11051661,11056496,11059871,11059872,11059873,11059976,11061421,11061501,11061770,11061771,11061795,11061797,11061802,11061804,11061827,11061906,11062116,11062150,11145897

**Comment by Jegelewicz** [comment]
Not sure what else to show from the email? This is everything I see:

![image](https://user-images.githubusercontent.com/5725767/87327336-2e3af680-c4f1-11ea-9b1f-8b8ca60f19e5.png)
