### ISSUE TITLE
Parts Table Download - nice! but can't download

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2905]
Was this always available? If so, my bad for not noticing, if not, then THANKS @dustymc !

From a catalog record search results, you can now download all of the parts!

BUT, once I have my results, when I try to download CSV, I get this:

![image](https://user-images.githubusercontent.com/5725767/87320384-1d39b780-c4e8-11ea-8379-0c7d1b059c07.png)

**Comment by Jegelewicz** [comment]
This is cool, but cooler would be a download that would match the part bulkload tool. Parts plus their attributes.

**Comment by dustymc** [comment]
>download that would match the part bulkload tool

That - like basically every other "flattening" operation - is potentially lossy.

**Comment by Jegelewicz** [comment]
Not sure why that would be "lossy". It would have been super useful in the operation I just did, which was to find all turtles with the part "shell", remove those parts and replace with "carapace". The modify parts wouldn't work for me - not sure why, but maybe the fact the stuff with part name "egg shell" also turned up in my search (can you specify an exact match in the part name search?). In order to preserve lot counts, dispositions, conditions, remarks and barcodes I downloaded the search results - modified the JSON parts to get just the "shells", replaced shell with carapace and modified the remarks to include "(shell)", then uploaded the carapace parts. After that, I used the delete part tool to get rid of the "shell" parts, which worked like a charm.

Fortunately, none of the "shell" parts had any part attributes, so the JSON manipulation was pretty easy, however it was complicated by the fact that the various part stuff doesn't always come out in the same order. Some were PN, LC, DP, CD, BC, RK and some were PN, DP, LC, CD, BC, RK and others were in a different order.

**Comment by dustymc** [comment]
>Not sure why that would be "lossy". 

The bulkloader will handle some finite number of attributes per part; the core structure has no limits.

**Comment by Jegelewicz** [comment]
> The bulkloader will handle some finite number of attributes per part; the core structure has no limits.

Makes sense, but a download could include everything, which again would be nice. So maybe not "download for part bulkloader", but "download parts with associated attributes". This is basically part of #2051
