### ISSUE TITLE
Georeference Protocol and Source show vs carry bug?

### ISSUE THREAD

**Issue by lin-fred** [ArctosDB/arctos#2906]
**Describe the bug**
When Data entering, trying to get the "Coordinates (event and locality)" to "show" instead of "carry" for each record, can get all but these options to set to show except for these two:

![image](https://user-images.githubusercontent.com/19802479/87328873-65aaa280-c4f3-11ea-9ab1-a003366bfc15.png)

I don't see an option for Georeference Protocol, and is LAT_LONG_REF_SOURCE the same as Georeference Source? If so, I have it set to show but it isn't working. Or if it isn't, then there isn't an option for georeference source.

**Expected behavior**
Expect to be able to show or carry Georeference Source and Georeference Protocol

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by dustymc** [comment]
should be fixed in next release
