### ISSUE TITLE
Taxonomy update slow?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2907]
@dustymc see discussion at https://github.com/mbprondzinski/ALMNH/issues/5#issuecomment-657751328

**Comment by sharpphyl** [comment]
See also issue #2815 

The higher classification still doesn't show up in the specimen record for https://arctos.database.museum/guid/DMNS:Inv:31936.  It was entered on June 21st.

![Screen Shot 2020-07-13 at 4 41 50 PM](https://user-images.githubusercontent.com/15368365/87360648-d4a1ee80-c527-11ea-866a-d822fe664ec2.png)

Also, yesterday I added the higher classification in WoRMS (via Arctos) which was missing for _Conasprella branhamae_. 

![Screen Shot 2020-07-13 at 4 43 06 PM](https://user-images.githubusercontent.com/15368365/87360748-00bd6f80-c528-11ea-9b5a-496b41f8114f.png)

The higher classification still doesn't show up in the specimen record.  

![Screen Shot 2020-07-13 at 4 49 25 PM](https://user-images.githubusercontent.com/15368365/87361166-da4c0400-c528-11ea-9d8d-26f3ee6dfc65.png)

You can search on it, so it's somewhere in the taxonomic tables.  

Are #2907 and #2815 related?

**Comment by dustymc** [comment]
rebuilt the function; should catch up eventually

**Comment by Jegelewicz** [comment]
This is still not updated.

![image](https://user-images.githubusercontent.com/5725767/87480792-4abb5980-c5eb-11ea-8582-1add1a0619c3.png)

**Comment by sharpphyl** [comment]
My records finally updated but it took about 24 hours.
