### ISSUE TITLE
Having difficulty creating a new species holotype

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/arctos#2908]

**Comment by Jegelewicz** [comment]
It works!

**Comment by mbprondzinski** [comment]
Hooray!  I just had a chance to check on this.  Was it GitHub that was holding it up or did you have to do something?

**Comment by Jegelewicz** [comment]
Dusty did something - GitHub doesn't "do" anything to Arctos - it is how we direct Dusty to do stuff!

**Comment by mbprondzinski** [comment]
Well is this going to be an ongoing problem?  I have another new holotype and I need to know how to deal with it.  Should I go directly to Dusty?  I haven’t entered it yet, so I don’t know if it exists or not in GBIF ( that’s what I meant…NOT “Git Hub”.  Too many acronyms!

**Comment by mbprondzinski** [comment]
Well is this going to be an ongoing problem?  I have another new holotype and I need to know how to deal with it.  Should I go directly to Dusty?  I haven’t entered it yet, so I don’t know if it exists or not in GBIF ( that’s what I meant…NOT “Git Hub”.  Too many acronyms!

**Comment by Jegelewicz** [comment]
GBIF also has nothing to do with what happened - it was apparently just slow updates in Arctos. Try the next one and let's see if it is really fixed.

**Comment by mbprondzinski** [comment]
All right…I’m working on it.  It’s another screwed up citation from 10 years ago.
