### ISSUE TITLE
UTM coords not displaying properly

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#2910]
I entered UTM coords, as seen here (ex: https://arctos.database.museum/guid/MVZ:Bird:192163):

![image](https://user-images.githubusercontent.com/967275/87357508-f9db3080-c518-11ea-9552-0855bbb1f585.png)

These are not displaying properly on the specimen detail or event detail page (numbers cut off):

![image](https://user-images.githubusercontent.com/967275/87357585-19725900-c519-11ea-8b8f-861c1272a9f1.png)

![image](https://user-images.githubusercontent.com/967275/87357624-2f801980-c519-11ea-80be-9181b07b9420.png)

**Comment by dustymc** [comment]
Suggest new Locality Attribute "verbatim coordinates"

https://github.com/ArctosDB/arctos/issues/2498

**Comment by ccicero** [comment]
Here's another place where they are not displaying correctly:

![image](https://user-images.githubusercontent.com/967275/87361341-db793300-c520-11ea-982a-fa06cba0164b.png)

**Comment by Jegelewicz** [comment]
> Suggest new Locality Attribute "verbatim coordinates"

But there are already "verbatim coordinates" in every collecting event....

![image](https://user-images.githubusercontent.com/5725767/87362914-416bb780-c52d-11ea-8e0d-819268c30512.png)

**Comment by Jegelewicz** [comment]
And mine look fine - so not sure what's going on...

**Comment by dustymc** [comment]
>But there are already "verbatim coordinates" in every collecting event....

There's an issue somewhere - those are (or were intended to be) mine, before I convert them to DD.ddd (which I can't do for UTM, but there's an issue for that as well). There's also some UI that lets users do random things with those data, which makes understanding where they came from unnecessarily complicated. This provides a robust solution - collecting_event.verbatim_coordinates can remain "mine," I can remove any editing capability from the UI which lets them serve their original purpose, and locality attributes can deal with whatever YOU think 'verbatim coordinates' should be. Yay everybody!

**Comment by ccicero** [comment]
I don't understand what you're saying. If UTMs are what come with the original data, then they need to go in as verbatim coordinates. Are you suggesting that all coordinates that came with the original data, regardless of type (UTM, decimal degrees, etc.) become locality attributes instead?

**Comment by ccicero** [comment]
and this also doesn't explain why it's showing the full coords for Teresa's record, but not mine?

**Comment by dustymc** [comment]
Big-picture I'm saying two things.

1. "verbatim coordinates" isn't verbatim, isn't capable of handling every coordinate system you might get, and probably isn't what you think it is. (Or only partially is - it's also/primarily me "showing my work" when converting coordinates across formats.)
2. locality attributes can be everything that verbatim coordinates can't.

I can look at display after next release - somethings going on in there but it's all getting rebuilt tonight anyway.

**Comment by dustymc** [comment]
I was able to patch the display fix in, so I guess I'll close this. Still highly recommend we sort out/document precisely what we're doing or trying to do with collecting_event.verbatim_coordinates.
