### ISSUE TITLE
Bulk Edit Container Load Delay

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2914]
Upload of Bulk Edit Container has been spinning for over 30 min? Smaller files work, but larger files get stuck in spin-land.

**Comment by dustymc** [comment]
That almost has to be your network/browser/environment, unless you're fairly serious about "large."

**Comment by campmlc** [comment]
From student:
"I've only been able to get one box at a time to load in Chrome. Nothing in Firefox. Sometimes it kicks back with the 500 error but I refresh the page and it says "all done". I've been checking the boxes as I go to make sure they are loading. "
[Label_TEST.zip](https://github.com/ArctosDB/arctos/files/4921440/Label_TEST.zip)

**Comment by campmlc** [comment]
Only works for under 100 records.

**Comment by dustymc** [comment]
Thanks, those are loaded.

* There was a NULL line on the end of the file.
* I upped the timeout for that form, patched that to prod.
* The update function could be tuned - it's surprisingly slow.
* PLEASE include all of the information requested by https://github.com/ArctosDB/arctos/issues/new?assignees=&labels=&template=bug_report.md&title= - I was a step away from the actual problem.

**Comment by campmlc** [comment]
Thanks! I did attach the file earlier, but I was posting for a student so
that wasn't initially available on first post.
