### ISSUE TITLE
Usage Stats error

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#2917]
Trying to access Usage Stats under Reports/Services, which causes a 500 error
Not sure what's up-- load issue? bug? but filing it  in case it works for others

**Comment by dustymc** [comment]
The form needs rebuilt, somehow - Arctos has outgrown the form/approach.

There's quite a bit of "how does my collection compare to others?" stats in there which I often find useful, I'm not sure how to preserve that and still make the form focused enough to work. We may need multiple forms, perhaps periodic caching.



Here are headers from the various tables included in the form

```

<strong>Publications by type, reviewed status, and citations:</strong>
<th>Publication Type</th>
<th>Count</th>
<th>Percent Peer Reviewed</th>
<th>Citations</th>


<strong>Projects by activity:</strong>
<th>Total</th>
<th>Using</th>
<th>Contributing </th>
<th>Both</th>
<th>Neither</th>


<strong>Results of projects which borrow specimens:</strong>
<th>Total Borrow Projects</th>
<th>Number Pubs Produced</th>
<th>Number Pubs that Cite</th>
<th>Number Cites</th>



<strong>Usage and results by collection:</strong>
<th>Collection</th>
<th>Holdings</th>
<th>%Loaned</th>
<th>Specimens Loaned</th>
<th>Items Loaned</th>
<th>Specimens Cited</th>
<th>Citations/Loaned Specimen</th>

```
