### ISSUE TITLE
add Other ID Type = ARK

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#2918]
**Goal**
Use ARKs to link Arctos records with other datasets (e.g., NMNH records).

**Context**
ARKs are used by museums, archives and libraries as persistent, resolvable identifiers. Even though many natural history records can be linked with corresponding Arctos records via GBIF occurence IDs, ARKs give more flexibility in resolving data across disciplines.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type

**Value**
ARK

**Definition**
Archival Resource Keys (ARKs) are persistent identifiers applied to a variety of data objects across the museum, library and archive fields. ARKs are implemented and supported by the EZID system.

Base URL:
http://n2t.net/ark:/

**Comment by Jegelewicz** [comment]
![image](https://user-images.githubusercontent.com/5725767/87480274-39be1880-c5ea-11ea-90d8-003ea3650363.png)

**Comment by dustymc** [comment]
I have no objections to ARKs in general, but I do have questions.

First, how do ARKs facilitate "Use ARKs to link Arctos records with other datasets (e.g., NMNH records)."?

Second, I believe the actual ARK looks like "ark:87299/x68g8hqw" and one resolver/baseURL is https://n2t.net/ (which come together as https://n2t.net/ark:87299/x68g8hqw).

**Comment by ebraker** [comment]
Thanks @Jegelewicz 

@dustymc - I just meant linking records. Here's an example for a UCM [marmot](https://arctos.database.museum/guid/UCM:Mamm:8166) that we exchanged to NMNH:
http://n2t.net/ark:/65665/38b899482-5997-4b57-8931-4c5dd250a1ed

Smithsonian has the EZID listed as "ark:/" not "ark:" but removing the forward slash still gets me to the record. Perhaps we can include 'ark:' in the base URL so people don't have to type it in? I'm fine either way.

**Comment by Jegelewicz** [comment]
That thing was already there - @dustymc added it ages ago!

**Comment by ebraker** [comment]
Oh! I thought I CTRL-F searched for it but apparently not! Awesome.
