### ISSUE TITLE
Newly created citation not displaying

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#2919]
**Describe the bug**
This could be just a time lag, but two newly created citation are not displaying in the respective records.
https://arctos.database.museum/guid/UCM:Obs:AC-281
https://arctos.database.museum/guid/UCM:Obs:AC-282

**To Reproduce**
I created the citation which displays in the Publication record and in the search results:
![image](https://user-images.githubusercontent.com/11336485/87483197-5a896c80-c5f0-11ea-8656-c74258fe520f.png)
However, no citation shows up in the corresponding record:
![image](https://user-images.githubusercontent.com/11336485/87483227-73921d80-c5f0-11ea-9024-e00bacc50f6c.png)

** Data**
This is happening with two newly created publications and citations:
[AC-281](https://arctos.database.museum/guid/UCM:Obs:AC-281) and [Pub 0009334](https://arctos.database.museum/publication/10009334)
[AC-282](https://arctos.database.museum/guid/UCM:Obs:AC-282) and [Pub 10009335](https://arctos.database.museum/publication/10009335)

**Priority**
normal

**Comment by dustymc** [comment]
Yes bug but I can't diagnose it until https://github.com/ArctosDB/arctos/issues/2498 is through
