### ISSUE TITLE
Media thumbnails search results display

### ISSUE THREAD

**Issue by krgomez** [ArctosDB/arctos#2920]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
Media thumbnails in search results display inconsistently. I just uploaded some PDFs to a group of catalog records and the text icon now appears before the jpeg thumbnail for a number of them (but not all) in the search results. 

**Describe what you're trying to accomplish** 
A clear and concise overview of the goals; why are you asking for this?
It would be much better if the image thumbnail was given priority for display in the media box on search results page. Ideally, it would also be helpful to be able to choose a _primary_ image showing the cataloged item. There may be multiple images showing the cataloged item (including text -- though, "shows cataloged item" doesn't quite describe what the text is doing -- maybe there should be a media relationship called "documents cataloged item"?), and it seems like we should be able to make a determination for which is the primary image showing the cataloged item.

**Describe the solution you'd like**
How might we accomplish your goals?
Is there a way to make sure the image thumbnails appear before the text/other media thumbnails in search results?

**Additional context**
![Screen Shot 2020-07-14 at 5 26 23 PM](https://user-images.githubusercontent.com/40579515/87492553-4006c180-c5f7-11ea-8763-ef51f4c2be68.png)

**Priority**
Please assign a priority-label.
normal

**Comment by dustymc** [comment]
Some sort_by_this label might do what you want, and https://github.com/ArctosDB/arctos/issues/2548 could be reanimated.

**Comment by Jegelewicz** [comment]
For simplicity, would it help if they sorted image, video, audio, text, multi-page?

**Comment by dustymc** [comment]
I can sort by media.media_type, but I don't think that addresses the concern - there's no "main" or even "most relevant 19 audio files" in there, where there is in an explicit "sort_by" label.

**Comment by krgomez** [comment]
Being able to sort by image first would solve the main problem in this issue - that would be great!

I'm pretty sure that being able to designate a primary image is a DAMS function. However for the art collection we have only uploaded our primary images (and small images at that -- our high res images are not in Arctos because we haven't figured out the media encumbrance issue yet), so it's not an issue at this time. But if we wanted to upload multiple photos of an object (older photography of the object, details, installation shots, verso images, etc.) then I think we would need to be able to distinguish which is the primary image. Maybe this could be accomplished with a media label but the primary would also need to sort first. Where I have uploaded multiple images (for example, verso images where relevant), for some reason the primary (front) image has always displayed first, so it's not been a problem.

**Comment by AJLinn** [comment]
>  But if we wanted to upload multiple photos of an object (older photography of the object, details, installation shots, verso images, etc.) then I think we would need to be able to distinguish which is the primary image. Maybe this could be accomplished with a media label but the primary would also need to sort first. Where I have uploaded multiple images (for example, verso images where relevant), for some reason the primary (front) image has always displayed first, so it's not been a problem

We routinely have anywhere from 2-10 images associated with a single catalog record. Their seemingly random order is often perplexing, as our filename structure is very clear which ones come first (eg., https://arctos.database.museum/guid/UAM:EH:UA2019-006-0001AB with 12 images with images following a consecutive numbering sequence embedded into the file name). It seems that sometimes they display in the expected order, but other times not. It would be helpful if they were able to sort by file name after file type.

**Comment by dustymc** [comment]
>perplexing

If there's no explicit sort, the optimizer does whatever it wants to whenever it wants to.

I see two ways (barring "do nothing") forward on this:

* sort by various things that hopefully more or less work for the existing data, hope it works for the next use case, still not be able to get "first(n)" and such
* give you full control and explicitly address everything mentioned here by adding an explicit "sort_by" label and using it

**Comment by AJLinn** [comment]
> sort by various things that hopefully more or less work for the existing data, hope it works for the next use case, still not be able to get "first(n)" and such

The lack of formal order is not such a big deal to me, as long as the image files sort before the PDFs. I'm getting used to scrolling thru the thumbnails at the search results screen (once media is added as a column).

**Comment by Jegelewicz** [comment]
> give you full control and explicitly address everything mentioned here by adding an explicit "sort_by" label and using it

This is ideal, BUT it means work to update all existing stuff, which we would essentially need to do manually, because I don't think we have any way of bulk adding a label to a bunch of media?

**Comment by dustymc** [comment]
>bulk adding a label 

That's easy to write, not sure how easy to use. A bulkloader and a bulk-unloader for every table is somewhere on my wishlist anyway....

I added some sorting to the JSON generator.
