### ISSUE TITLE
Error on search results as Chart Graph

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#2923]
Searched and received 613 results then tried to display as chart with these settings:

![Firefox_Screenshot_2020-07-15T16-09-53 303Z](https://user-images.githubusercontent.com/2523089/87568723-f495f700-c67a-11ea-87a3-d01c0a4e9659.png)

Received unspecified errors when choosing Chart Data by country, by year, by family

**Comment by dustymc** [comment]
Seems to be a lucee "bug" or at least interaction with certain environments (and our is the default Lucee install). 

Test fails in a slightly different way, which adds some credence to the idea that something about the environment is involved.

I don't think I can fix this without messing with fundamental bits of the production environment, which could of course very quickly get "interesting." 

I don't know how to address this. Tentatively suggest we get rid of the graph option until we can implement containerization, which would let me debug in a safe environment.

**Comment by PaulaBarteau** [comment]
I just got this error as well trying to use any of the graph settings for multiple search results (just trying to throw together a presentation on search features, don't actually need specific search results.) If this feature isn't operational I will just omit it from my presentation. 

The error messages I got are as follows:

"
An error occurred while processing this page!
Message: **java.lang.reflect.InvocationTargetException**
Detail:
Check the Arctos Handbook for more information on errors.

This message has been logged as 75D4EF9D-790D-499A-8D536FF83A5E117C Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue. 
"

**Comment by dustymc** [comment]
https://github.com/ArctosDB/internal/issues/64
