### ISSUE TITLE
Higher Geography Change - Pakistan

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2924]
Suggest [Asia, Pakistan, North-West Frontier Province](https://arctos.database.museum/Locality.cfm?Action=editGeog&geog_auth_rec_id=10004511) be changed to [Asia, Pakistan, Khyber Pakhtunkhwa Province](https://en.wikipedia.org/wiki/Khyber_Pakhtunkhwa)

**Comment by dustymc** [comment]
Agreed.

@mvzhuang @atrox10 

Also

Asia, Pakistan, Khyber Pakhtunkhwa, Katlang

(1) is inconsistent, and (2) looks like a "sub-county" equivalent; recommend deletion.

**Comment by Jegelewicz** [comment]
Nope - I'm gonna use that one! and it will be consistent when we get the other one changed.

**Comment by dustymc** [comment]
http://handbook.arctosdb.org/documentation/higher-geography.html#guidelines-for-geographic-terms-in-arctos

>Do not “promote” entities. Cities, vaguely-described districts, 4th-level administrative entities, and things the collector made up are verbatim_locality and should not be stuffed into geography. Chilean Communes, for example, are “real” political entities, but as sub-county-level divisions are not formal geography.

I'm still not seeing how that's anything other than a sub-county equivalent.

**Comment by Jegelewicz** [comment]
OK after review - I changed it!

**Comment by mkoo** [comment]
Try to stick to primary and secondary admin boundaries in HG to maximize
usefulness. If you really need to go tertiary, and lower then it seems like
specific locality is appropriate = rules of thumb

Love to discuss the exceptions!

**Comment by dustymc** [comment]
Tabling - https://github.com/ArctosDB/arctos/issues/3272 would allow Arctos to standardize geography.
