### ISSUE TITLE
Data changes not appearing on results page or reports (labels)

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#2929]
I entered a bunch of new data into existing records two days ago and those changes are not being reflected on the search results page (https://arctos.database.museum/saved/mammal%5Ftags). When you open each record, the data appears as it should. I'm trying to print labels and they get the same old information that appears on the results page. Help please

**Comment by dustymc** [comment]
What was changed?

**Comment by acdoll** [comment]
The only "change" was from whole organism to skin, study (or some other part), but then I added all of the other preparation data: the rest of the parts, preparator, preparator number, and attributes. I actually see now that the measurements, reproductive condition and the otherID are making it onto the label, but not the parts (which is what I was focused on). Oddly none of this appears on the results page except the reproductive condition.

**Comment by dustymc** [comment]
Thanks. I see the problem, at least at a high level, but unfortunately it's confounded with some changed that are stuck in the development cycle. I'll push those out tonight and dig deeper if necessary.

\remind me to check back in 24 hours

**Comment by dustymc** [comment]
fixed and caught up
