### ISSUE TITLE
bulkloader error download only showing one error per record?

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#2931]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Loaded column showing errors in a the bulkloader download is only showing one error per record instead of all the errors of a record. 

**To Reproduce**
1) Upload in bulkloader
2) download records with errors after validation
3) look at loaded column
Example: 
![image](https://user-images.githubusercontent.com/38706617/87808748-80dd2100-c817-11ea-9de3-cf8d2ab4c06d.png)
This record should show "higher geog doesn't match" and "ID made by agent doesn't match" , (Neither Nova Europa or Brandao is in our database yet), but it only shows "id made by agent doesn't match"

**Expected behavior**
all errors to show for a record so I can fix them all at once.
[bulkloader_stage (5).xlsx](https://github.com/ArctosDB/arctos/files/4938930/bulkloader_stage.5.xlsx)

**Screenshots**

** Data**
sample data attached

**Desktop (please complete the following information):**
Chrome Browser

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
CSV please - or maybe @campmlc has some I can use...

**Comment by mvzhuang** [comment]
it's happening ocne the record is in the bulkloader too. 8362 should read that there is a problem with Higher geography and that the taxon name has a problem. It only shows the taxon name problem.
[BulkPendingData_8D30B62543.zip](https://github.com/ArctosDB/arctos/files/5091723/BulkPendingData_8D30B62543.zip)

**Comment by dustymc** [comment]
CSV please!

**Comment by mvzhuang** [comment]
I can't upload a csv directly. It only lets me upload XLSX and jpegs etc. I zipped the csv up?

**Comment by dustymc** [comment]
Well who knows what I clicked then....

Got it, thanks.

**Comment by campmlc** [comment]
I forwarded a csv yesterday.

**Comment by dustymc** [comment]
fixed
