### ISSUE TITLE
Add amber to ento collections

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#2932]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Goal**
add amber part to entomology collections

**Context**
we have fossil ants in amber in the entomology collections

**Table**
in specimen_part name table 

**Value**
amber is already in the ES collections, just need to add to ento
**Definition**
Clear, complete, non-collection-type-specific definition of the new value.

**Collection type**
Ento

**Priority**
Please assign a priority-label.

**Comment by Jegelewicz** [comment]
HMMMMM, this is a special case as the amber really seems to be the preservation method, no? How are you planning to use it?

**Comment by mvzhuang** [comment]
Oops I didn’t read the definition clear enough. So amber in ES is amber produced without an organism in it?

So better to have whole organism (amber) for Ento then? Definition: whole organism preserved in fossilized resin produced by extinct coniferous trees

**Comment by Jegelewicz** [comment]
Hey @dustymc what are your thoughts on this one?

**Comment by dustymc** [comment]
2 parts that happen to share a container?

The bug-people think the bug is neat, probably don't much care about the amber
The pollen-people just care about the amber, even if there's a bug in the way

Whatever's done should facilitate both use cases (and the stuff we haven't thought of), I think 2 parts probably does that better than anything else.

**Comment by Jegelewicz** [comment]
> I think 2 parts probably does that better than anything else.

But how to make it clear that the ant is INSIDE the amber? I suggest that is made clear in the condition for both.

@mvzhuang sound good? I'll add amber to ento.

**Comment by dustymc** [comment]
>made clear in the condition for both.

...and/or remarks or etc. I don't think that much matters for discoverability so the information can be somewhere that's not very searchable but is accessible from the record, eg some text field.

**Comment by mvzhuang** [comment]
I think the two parts will work. If the ento people are specifically looking for fossil ants, they can run a search for amber in the ento collections.
