### ISSUE TITLE
can't make address for loan

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#2933]
I created loan MVZ:Mamm:8990. Upon trying to make the shipping info, found the attached error on the page at the bottom. There is no Save Shipment button. I picked the addresses. There seems to be a lot of markup in the address boxes. 
![Screen Shot 2020-07-17 at 10 50 18 AM](https://user-images.githubusercontent.com/5749672/87816113-a409cf80-c81b-11ea-8c40-35ca784dc983.png)

**Comment by dustymc** [comment]
fixed and patched in
