### ISSUE TITLE
Weirdness when picking items for loan

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#2934]
**Describe the bug**
In picking items for loan, there box for Part Location has things other than MVZ. See attached images. Either UAMXXXXX, or UAM Ento Observation, or University of Alaska Museum. Probably just cosmetic, but needs to be fixed. 

**To Reproduce**
1. Go to loan MVZ:Mamm:9000
2. Add another item. I just tried MVZ mammal 12345. Under part of skull, part location says "[ ] DMNS Marine Invertebrates 15694 whole organism (dry) (collection object)"

**Expected behavior**
It should either be blank or have somewhat accurate info, like MVZ mammal collection. Otherwise, it is just useless noise on the screen.

**Screenshots**
Attached.

![Screen Shot 2020-07-17 at 10 44 43 AM](https://user-images.githubusercontent.com/5749672/87817093-2ba40e00-c81d-11ea-9da3-db9a0ccd0178.png)
![Screen Shot 2020-07-17 at 10 47 18 AM](https://user-images.githubusercontent.com/5749672/87817100-2c3ca480-c81d-11ea-941b-898224820658.png)
![Screen Shot 2020-07-17 at 10 46 00 AM](https://user-images.githubusercontent.com/5749672/87817104-2cd53b00-c81d-11ea-86c8-72fb45253125.png)

**Desktop (please complete the following information):**
 - Mac OS
 - Browser Chrome Version 83.0.4103.106 (Official Build) (64-bit)
 

**Priority**
Medium

**Comment by dustymc** [comment]
typo in function call - fixed and patched
