### ISSUE TITLE
Bulkloading identifications error

### ISSUE THREAD

**Issue by anna-chinn** [ArctosDB/arctos#2936]
I'm using the identification bulkloader and getting this error when I try to validate my records:
<img width="727" alt="Screen Shot 2020-07-18 at 9 38 29 AM" src="https://user-images.githubusercontent.com/40321380/87853774-0e357980-c8db-11ea-86ac-377e7781a98d.png">

`Parameter 3 of function mid which is now [-10] must be a non-negative integer or -1 (for string length)`

The form will intermittently load records when I click validate, but other times will immediately give me the error. Is this the form timing out, a bug, or an error in my dataset that I need to address?

I'm in the process of loading these data: [id_to_load_2020-07-18.xlsx](https://github.com/ArctosDB/arctos/files/4941749/id_to_load_2020-07-18.xlsx)
Currently, nearly 900 IDs are valid, 150 are erroring because of multi-taxa formula, and 200 have status = null.

**Comment by dustymc** [comment]
It was choking on mismatched brackets Coluber {Coluber semilineatus] 

Please leave this open - rebuild to use the function I built for data entry, which should also allow multi-taxa IDs.

**Comment by anna-chinn** [comment]
@dustymc In the mean time, can you load these multi-taxa IDs for me, please?
[CHAS_hyrid_id.xlsx](https://github.com/ArctosDB/arctos/files/4996318/CHAS_hyrid_id.xlsx)

**Comment by dustymc** [comment]
CSV please (you can zip to attach) - I'll find a way to mangle xls....

**Comment by anna-chinn** [comment]
[CHAS_hyrid_id.zip](https://github.com/ArctosDB/arctos/files/4996438/CHAS_hyrid_id.zip)
Thanks!!

**Comment by dustymc** [comment]
This will be in the next release, hopefully early next week. Load these to test.

/remind me to check back in a week

**Comment by dustymc** [comment]
Loaded
