### ISSUE TITLE
revoke delete on taxon_name from everyone

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#2937]
https://github.com/ArctosDB/documentation-wiki/issues/156

Given the new quarantine capability, I propose completely removing any capability for deleting names.

* Quarantined and deleted names aren't functionally different for things like data entry.
* Disallowing deletion would prevent eg, breaking the links from tomorrow's publication which will use the alleged "bad" name. That is, I don't think it's possible to **know** with any certainty that a name is not actually useful.

**Comment by campmlc** [comment]
I think we should wait on this until we see how this quarantine function
works. Still need to be convinced that it will solve our issues. I really,
really do not want to publish our mispellings back out to the universe, and
I don't think that is resolved yet.

**Comment by dustymc** [comment]
I'm fine with waiting for the dust to settle, but let's not forget this or leave it hanging for too long.

If we can somehow demonstrate that they're not about to appear in the literature tomorrow, a DBA can always lock things down and remove our misspellings.

**Comment by campmlc** [comment]
If we could lock down and hide from public view everything that is
"probably not valid" or other obvious mispellings, and require that an
operator requests access from the DBA prior to use, that might work, but we
still have the problem of someone who hasn't done the research asking for a
name to be made available.. I  think that Teresa's idea of requiring
documentation and allowing us to delete through a name merger which is
documented in the extant name (and allows for search on the invalid name?)
is a excellent approach that would save a lot of people time and effort.

**Comment by dustymc** [comment]
>lock down and hide from public view everything that is "probably not valid" 

Hu?

>idea of requiring documentation

That's what quarantine does, but formally and functionally.

>delete through a name merger

We can revisit if necessary, but I think that'll be exceptionally rare. Also

1. agents are not a good analogy to taxonomy, and
2. that would remove any possibility of functionality

>allows for search on the invalid name?

Hu?

**Comment by campmlc** [comment]
lock down and hide from public view everything that is "probably not valid" :
Prevent any of these names from being picked up and used by external
resources such as NCBI and GlobalNames

allows for search on the invalid name?  By merging the invalid name with a
valid one, and labeling it as invalid, and providing documentation as to
why it is invalid and should not be used, but keeping all this
documentation associated with the valid name in a searchable field.

**Comment by dustymc** [comment]
I suspect there are three things being confounded here.

* quarantine names are just what they sound like, quarantined from "actually resembles taxonomy" names
* invalid is a potential classification term - I have no idea what it means (https://github.com/ArctosDB/arctos/issues/2926), but at best that has tenuous connections to the name
* "probably not valid" may refer to my checker-service, which is a (very imperfect) tool and never treated as data.

??

**Comment by Jegelewicz** [comment]
>If we could lock down and hide from public view everything that is "probably not valid"

That would also exclude new names! An emphatic NO to this

**Comment by Jegelewicz** [comment]
Here is the crappy thing about removing everyone's ability to delete a name - I have personally created a name, looked at it after it was created and realized I misspelled it. Making the deletion of that the responsibility of a DBA seems excessive.

I think we need to have both the ability to quarantine and to delete names. If someone deletes a name, it can always be created again, so it isn't like we are losing a whole lot by deleting a name.

**Comment by dustymc** [comment]
Delete option, but with required explanation-->notifications?

**Comment by Jegelewicz** [comment]
If no one is using the name, what's the big deal? If anyone is, it will require coordination. I just don't see this as some huge problem.

**Comment by sharpphyl** [comment]
I agree that if no one is using the name a notification doesn't seem necessary.  The only exception would be if a specific individual created the name as they may have plans to use it even though it's misspelled or in error.  If you're concerned, can you limit the deletion capability to either taxa created by the user or taxa created by "unknown."

**Comment by campmlc** [comment]
Need to make sure that the Nephalomys mispelling just created gets deleted. This came through via email - who will take responsibility to delete? Ideally, the person who created it and has been informed that it is not valid should have the ability to delete it.

**Comment by Jegelewicz** [comment]
Looks like it is already gone.

**Comment by Jegelewicz** [comment]
Deletion of names hasn't caused a whole bunch of grief. Tentatively closing.

**Comment by dustymc** [comment]
"Only negates part of your work!" is not sufficient reason to ignore. Reopening, see https://github.com/ArctosDB/arctos/issues/4268.

**Comment by sharpphyl** [comment]
You referenced #4268.  I haven't deleted any taxon names (although my statement wasn't clear), just the WoRMS (via Arctos) classification that is a mismatch.  I haven't yet linked the two names and it won't happen automatically since WoRMS has deleted the previous name.  If you want to quarantine them as well as mark them invalid, that's fine, but several of them are currently being used by other collections.  Would that cause issues?

No need to reopen this issue for anything I mentioned in #4268.
