### ISSUE TITLE
specimenresults data field cleanup and cache

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#2938]
This is mostly a copy of https://github.com/ArctosDB/internal/issues/58. We seem to agree on the need for caching some data. Moving it here for more visibility, and some details need resolved.

Summary: There are expensive "columns" in specimendetail, they need either cached or removed.

--------------------------------
* ~~json_locality is caching since Locality Attributes were implemented; the software stack seems to be happy enough with large JSON objects (https://arctos.database.museum/guid/MSB:Mamm:320149 is 12K+ characters)~~

--------------------------------
* media - needs cached in flat/filtered_flat
* id_history,id_hist_json - need merged, cached in flat/filtered_flat as JSON, pretty-print option added
--------------------------------
* long_citation - redundant with typestatus, remove?
--------------------------------
* drainage - https://github.com/ArctosDB/arctos/issues/2875, ignoring until there's some resolution on "what's geography?"
--------------------------------
* ~~last_part_location - available from part_detail - remove? No don't remove see below~~ Cached, see https://github.com/ArctosDB/arctos/issues/3535
--------------------------------
* maker - suggest merging all https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcollector_role into a single cached data object

--------------------------------

* event_assigned_date
* day_collected
* month_collected
* specimeneventdeterminer
* elev_in_m
* depth_in_m

What is the use case for these? None of them resolve to a single value, all can be pulled from json_locality. Can they all be removed from FLAT?

--------------------------------

* skull_yn - is there a use case for retaining this?

--------------------------------

* ~~relatedspecimenid was removed - suggest reintroducing as a JSON representation of relevant rows from table cf_relations_cache~~
    * Full cache available as RelatedRecordSummary

**Comment by dustymc** [comment]
PREVIOUSIDENTIFICATIONS is now JSON
need to make sure id_history is mapped to it, not the function, and remove  id_hist_json from resultscols

**Comment by dustymc** [comment]
PREVIOUSIDENTIFICATIONS--> concatAllIdentification(identification.collection_object_id)::varchar is running, but not very fast

/remind me to check back in a week

**Comment by AJLinn** [comment]
If this is open to comments?

> last_part_location - available from part_detail - remove?

Please do not remove this column. I've defended the use of this column multiple times. I get that it's expensive but it's a much cleaner way of displaying the current storage location, plus you can sort by that column when working straight from the search results.
<img width="1354" alt="Screen Shot 2021-01-05 at 8 41 43 PM" src="https://user-images.githubusercontent.com/17605945/103733687-c7296680-4f96-11eb-9a4f-146fa63ef363.png">

There really is no comparison to this...
<img width="1567" alt="Screen Shot 2021-01-05 at 8 47 16 PM" src="https://user-images.githubusercontent.com/17605945/103733890-3606bf80-4f97-11eb-95e1-1f6b1245419a.png">


> maker - suggest merging all https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcollector_role into a single cached data object

Does this mean displaying all agent roles into one column? If so, then this is a hard no from me. That's just not a workable solution for the way we organize & display our data. See image above for doll search results where creator & collector are vastly different, with each role often occupied by multiple agents (to indicate succession of ownership or partnership in creation).

**Comment by dustymc** [comment]
Edited above.

last_part_location is a great example of one part of my conundrum. It's complex to calculate (=expensive), and it makes sense only in a limited scope (eg not in collections with lots of parts-complexity) so investing in caching it (which requires CPU and storage, which adds up to a global performance hit) probably doesn't make sense, at least under the current mechanism for that. It seems to work just fine for what it's designed to do, but then someone (who may have no use for or understanding of the data) ignores the warnings, turns on everything (which includes many similar "fields"), and tells all their friends that Arctos is broken when it inevitably times out.

Maybe that's as simple as changing how we customize, or who can customize, or something of the sort?

>displaying all agent roles into one column

No, the intent is to pull them apart in your browser. That part works reasonably well (or would in a more modern grid), but some other things I was hoping to do with JSON data aren't very practical so I'm ignoring this for now - maybe in some future PG release....

**Comment by campmlc** [comment]
If this is possible with JSON:"  the intent is to pull them apart in your
browser", I would be very happy to see that implemented and used for other
JSON fields such as part detail. Also, could it be used for specimen events?

**Comment by dustymc** [comment]
@campmlc the short answer is "yes" - I can (and do) cache things as JSON, your browser speaks JSON, so I can unroll that data and do WHATEVER with it.

The longer answer is the usual - these data are not flat, and they can't readily be represented as flat. 50 parts each with 50 attributes can be teased out into (50 parts * 9 part-fields) + (50 attributes * 6 attribute-fields * 50 parts)==15450 columns, but that's just about 100% going to eat your browser, and you'd have no chance of understanding it or combining it with different data (which would have a different number of columns), or doing anything else with it, even if you're working with a lot more local resources than I am and can somehow support the unwinding.

Specimen events are just more of the same - they have many more "core" fields, then locality attributes and collecting event attributes.

We have complex data, so we have complex structures to store that complex data, but then we want to squish it into a tabular format that simply cannot deal with the complexity. I don't think that's a technical problem, so I don't think it has a technical solution.

**Comment by campmlc** [comment]
So perhaps we pull those fields out into a separate download, or give the
use the option of a separate download with parsed columns?

**Comment by AJLinn** [comment]
So I take it I lost this battle since LastPartLocation is no longer a column I can add to specimenresults?
![Screen Shot 2021-04-07 at 11 22 27 AM](https://user-images.githubusercontent.com/17605945/113922491-cec5fa80-9793-11eb-852f-76254c87f41e.png)

Can someone tell me how I can get the same smooth functionality I had by adding this column to my search results without having to download the results and do some longwinded table manipulation?

**Comment by dustymc** [comment]
No battles, just https://github.com/ArctosDB/arctos/issues/3535

Reopening and commenting there is probably the best place to discuss. I can add it back, but I'd need to cache (so I can remove it from filtered_flat, what the public sees) and I'm not sure where we as a community are on that sort of thing (ignoring it and hoping we don't run out of resources, maybe!).

Sorry for the unexpected vaporization, I thought you'd gone to barcodes?

**Comment by campmlc** [comment]
Does this discussion relate to enabling complex cached searches to avoid
timeouts?

**Comment by AJLinn** [comment]
>  I thought you'd gone to barcodes?

Locations are barcoded and all new items get barcoded but I don't have the personnel (AKA me) to barcode 17,000 objects right now... we're slowly getting there. But I still don't know how to get this same result even with barcoded items/locations.
