### ISSUE TITLE
New weight unit

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2941]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Goal**
Record the weight of precious stones. Weights for some samples in the NMMNH mineral collection are in carats

**Context**
Gem and mineral people expect this term, however we could use milligrams and display carats with a conversion? Or just use milligrams? @Nicole-Ridgwell-NMMNHS 

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctweight_units

**Value**
carat

**Definition**
a unit of weight for precious stones equal to 200 milligrams

**Collection type**
N/A

**Attribute data type**
N/A

**Attribute value**
N/A

**Attribute units**
N/A

**Part tissue flag**
N/A

**Other ID BaseURL**
N/A

**Priority**
Please assign a priority-label.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I agree that we should add carats, this is the appropriate unit of weight for gems.

**Comment by Jegelewicz** [comment]
Done.
