### ISSUE TITLE
What is status of Taxonomy Classification Bulkloader Rebuild?

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#2943]
Currently, this is the message received upon opening the Taxonomic Classification Bulkloader.

![Screen Shot 2020-07-21 at 9 07 21 AM](https://user-images.githubusercontent.com/15368365/88072087-dbd18980-cb31-11ea-9b6f-33e7b08f4b2e.png)

** Describe what you're trying to accomplish** 

I have about 500 taxon names that don't have an aphiaID in WoRMS (via Arctos), but there is now an aphiaID in WoRMS, so it needs to be added to the record, and the classification refreshed and reloaded.  I can do it manually, but thought it would be faster to start with a group upload, then refresh each one.

**Describe the solution you'd like**
Just need to know the priority of the rebuild so I can decide how to proceed.

**Describe alternatives you've considered**
Ask Dusty to upload them for me, then refresh the entries.

**Priority**
It's been this way for a long time, so it's not high priority if other tools are more urgent.

**Comment by dustymc** [comment]
Marking next task - I know how to do it, I don't think there's anything technical to discuss, just needs prioritized.

**Comment by sharpphyl** [comment]
Thanks!

**Comment by dustymc** [comment]
I'd like to put this off until https://github.com/ArctosDB/arctos/issues/2231 can be addressed. The current (broken, constantly!) loader is complicated for many reasons which might not exist under a tiered preference approach.

Additionally that might mean we can actively prevent loading to service-maintained classifications, which would add a fair bit of (hopefully-theoretical) security.

And the loader is overly complicated for this use case. @sharpphyl if you can send me two-column CSV

scientific_name,aphiaid

I'll SQL those in, hang on to the code, and we can discuss making it a tool if necessary. Arctos should pick up the classifications from that, I think attempting to force anything else in is just a pathway to inconsistent data.

**Comment by sharpphyl** [comment]
Thanks for SQLing these in. All of the data came directly from a recent WoRMS taxon match so it should be valid.  Once we reduce the number of names without an aphiaid, we shouldn't have to repeat this very often.

I've split them into two csv docs.  The first should be no problem as they are exact matches and just need the aphiaid and refresh to overwrite whatever may be in the WoRMS (via Arctos) classification (if anything) now.

[no aphiaID exact matches.csv.zip](https://github.com/ArctosDB/arctos/files/5075607/no.aphiaID.exact.matches.csv.zip)

The second csv may be murkier.  I've left in several columns beyond the two you need to show you what is in WoRMS.  They all have a subgenus that will come up when you refresh the aphiaID, so the species in the WoRMS (via Arctos) won't be an exact match for the taxon name.  Here are two that I've done showing this.  Oddly, the World Register of Marine Species entry doesn't show the subgenus at the species level.  

Examples: 
https://arctos.database.museum/name/Cancellaria%20nodulifera#WoRMSviaArctos
https://arctos.database.museum/name/Trochonanina%20moreleti#WoRMSviaArctos

What is good about adding the aphiaid is that on unaccepted names, it will link to the preferred name.

[No aphiaid with subgenus.csv.zip](https://github.com/ArctosDB/arctos/files/5075608/No.aphiaid.with.subgenus.csv.zip)

The rest of them I'll have to do manually because they're misspellings or weird stuff that I'll have to figure out one by one.  Thanks!!

**Comment by dustymc** [comment]
>species in the WoRMS (via Arctos) won't be an exact match for the taxon name.

That's not a problem at all; there are basically no rules for what's in classifications. That means

* we can handle the crazy "tradition" or whatever lead to this, and
* I'm not going to notice if you gave me the aphiaID for elephants on some clam-name, I'll just pull elephant-data and elephant-seekers will find your clams.

My plan is

* loop through these names and
    * delete any existing WoRMS (via Arctos) classifications
    * create a new WoRMS (via Arctos) with an aphiaID and nothing else
    * let the scripts deal with pulling data from worms

Please confirm that's what you want, and a single merged CSV of only (scientific_name,aphiaid) would reduce the chances of me mucking this up.

>Oddly, the World Register of Marine Species entry doesn't show the subgenus at the species level.

GlobalNames probably has some reason for not wanting to deal with the crazy "tradition" there.

**Comment by sharpphyl** [comment]
Ok, here's the whole list. Your plan sounds fine; don't think we'll have any issues but I'll spot check after the upload.  Thanks!

[no WoRMS aphiaID to upload.csv.zip](https://github.com/ArctosDB/arctos/files/5076791/no.WoRMS.aphiaID.to.upload.csv.zip)

**Comment by dustymc** [comment]
Done, code is https://github.com/ArctosDB/PG_DDL/blob/master/scripts/addAphiaIdToTaxa.sql

**Comment by sharpphyl** [comment]
I checked a few and the aphiaid is there but they didn't refresh.  For example, here is _Pisidium variable_ aphiaid 857203.

Can you command them to refresh or is that a manual step?

<img width="1184" alt="Screen Shot 2020-08-14 at 2 38 31 PM" src="https://user-images.githubusercontent.com/15368365/90290902-f6023d00-de3b-11ea-91d9-bd421310d936.png">

**Comment by dustymc** [comment]
>overnight

Ha!

There's a backlog; WoRMS sometimes changes things faster than we can process them, which before has been a maybe-a-week issue. We're currently at June 21. I suspect a bunch of worms contributors are doing the COVID thing, but who knows. I gave the job all the throttle I think the webserver can reliably bear; hopefully we'll catch up before the next plague....

**Comment by sharpphyl** [comment]
@dustymc   Can you clarify what the holdup is on the scrips refreshing the WoRMS (via Arctos) classifications?  I'm starting to manually refresh each entry, as these are in use by our collection (and some by NMMNH too) so having the classification is helpful.  There are still about 300 that need to be refreshed.  If the system just now refreshing late June, it would be several months before these refresh - correct?  The aphiaIID is in the our system now, so I'm just refreshing which immediately brings up the full classification from WoRMS.

**Comment by dustymc** [comment]
> clarify what the holdup is 

They can write faster than I can read, particularly when I have limited infrastructure and am trying to avoid melting anything important.

>several months

Depends on many things, mostly how much they have been, and will be, writing. I'll see if I can speed things up in some way. I'd expect days or MAYBE weeks, but here we are....

**Comment by dustymc** [comment]
The task was tripping over itself, that's cleaned up, that task is now logging properly, and I gave it more throttle than it can probably bear indefinitely. https://github.com/ArctosDB/arctos/issues/2830 is still difficult to fully implement because https://github.com/ArctosDB/internal/issues/65 so the automation can't watch as closely as I'd like, but I'll keep an eye on this one for a while.

/remind me to reset the scheduler in a week - unless something melts first....

**Comment by sharpphyl** [comment]
Thanks. Every little bit helps.  I'll monitor it too.

**Comment by dustymc** [comment]
Looks like worms caught up, nothing melted, scheduler is reset to more sustainable levels.

**Comment by sharpphyl** [comment]
Hmmm.  Not sure what "caught up" means.

I went to the list you prepared of WoRMS (via Arctos) names without an aphiaID.  You added the aphiaID's for me and I started to refresh them.  I opened the next three and all of them needed to be refreshed.  Is refreshing part of what the scheduler will ultimately do or is that still manual?

As name was opened

<img width="1251" alt="Screen Shot 2020-09-02 at 10 28 30 AM" src="https://user-images.githubusercontent.com/15368365/92010958-a6f74b80-ed07-11ea-96ba-86cb2c2ccc47.png">

After refreshing

<img width="1267" alt="Screen Shot 2020-09-02 at 10 28 44 AM" src="https://user-images.githubusercontent.com/15368365/92010997-b1b1e080-ed07-11ea-9884-eded3e28625e.png">


Also, on #3053 I checked several of the Granulina and they are still in Marginellidae until I refresh them and then they move to Granulinidae.  Again, will WoRMS (via Arctos) eventually catch up or should I refresh them individually?

**Comment by dustymc** [comment]
I need a link to a stale name to diagnose.

**Comment by sharpphyl** [comment]
https://arctos.database.museum/name/Elliptio%20crassidens#WoRMSviaArctos
https://arctos.database.museum/name/Lasmigona%20complanata#WoRMSviaArctos

**Comment by dustymc** [comment]
Thanks @sharpphyl those got an invalid response from WoRMS, I set them to try again, will dig deeper if that doesn't work.

/remind me to check cf_worms_refreshed for refresh_fail in a week

**Comment by sharpphyl** [comment]
So far today everything I've checked today has already been refreshed, so we may be over the hump.  Many had a invalid taxon status, but still have aphiaIDs and should be in WoRMS (via Arctos).

**Comment by dustymc** [comment]
OK, I'll close this - looks like it was just a hiccup.

@sharpphyl you might check out https://github.com/ArctosDB/arctos/issues/3110 but it should work well to manage WoRMS (via Arctos) - just feed the loader name, source, 'aphiaID', and the aphiaID, then let Arctos deal with the rest.
