### ISSUE TITLE
Fix Documentation for Bulk Edit Container

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2946]
If we cannot create freezer box positions in bulk, which I disagree with, then we should update the documentation to say so or delete the extra columns from the bulk edit container template.

![Screenshot 2020-07-21 13 16 18](https://user-images.githubusercontent.com/14808196/88096888-9d00fb00-cb54-11ea-9736-0d15088e2b89.png)

**Comment by campmlc** [comment]
#2542

**Comment by Jegelewicz** [comment]
OK - so to test this, I used the attached file to change DGR10164 from:

barcode | old_container_type | container_type | description | container_remarks | height | length | width | label | number_rows | number_columns | orientation | positions_hold_container_type
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
DGR10164 | freezer rack | freezer rack |  |  | 50 | 13.5 | 13.5 |  | 9 | 1 | vertical | freezer box

to

barcode | old_container_type | container_type | description | container_remarks | height | length | width | label | number_rows | number_columns | orientation | positions_hold_container_type
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
DGR10164 | freezer rack | freezer rack | test rack | testing | 65 | 13.5 | 13.5 | Testing Rack | 12 | 1 | vertical | freezer box

and it worked like a charm

![image](https://user-images.githubusercontent.com/5725767/145069804-1c17fb8e-9bfc-4004-bc32-9ac27bc6f616.png)

@campmlc can you provide the data that was causing your issue?
