### ISSUE TITLE
error on try to download csv of loan history

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#2947]
Searched for MVZ mammal loans with transaction dates 1 July 2019 through 30 June 2020. Got a list of accessions, but when clicking the box for a csv file, got the attached error. 
<img width="721" alt="Screen Shot 2020-07-21 at 2 18 04 PM" src="https://user-images.githubusercontent.com/5749672/88108218-5532a180-cb5d-11ea-9a73-66adc35e49c4.png">

**Comment by cjconroy** [comment]
With same list of loans, the map button has a similar error. See attached. 
<img width="733" alt="Screen Shot 2020-07-21 at 2 22 56 PM" src="https://user-images.githubusercontent.com/5749672/88108487-c70aeb00-cb5d-11ea-890b-7803e4d71dc3.png">

**Comment by dustymc** [comment]
Looks like Lucee being strange/different with scope, form needs rebuilt. Marking next task, needs prioritized.

**Comment by ccicero** [comment]
@dustymc Revisiting this as I need to generate a list of MVZ loans for our CITES COSE application. Can we bump this up in priority? Also, is there a way to flag which ones are foreign loans? That's part of the COSE application form.

**Comment by dustymc** [comment]
>priority

Fine with me, bump away!

>foreign loans

Not that I know of - maybe something in shipping address coordinates. New Issue, probably.

**Comment by ccicero** [comment]
Bumped up priority. I can deal with foreign loans manually, but another thing that would be helpful when doing a search on loan history is to get a count of the # transactions at the top of the search results page. Separate  issue?

**Comment by dustymc** [comment]
Add UI requests to https://github.com/ArctosDB/arctos/issues/3352 - and feel free to prioritize that as well!

**Comment by dustymc** [comment]
If there are no major objections let's just merge this with https://github.com/ArctosDB/arctos/issues/3352 - I think can make a better form in not much more time than I can fix the current mess.
