### ISSUE TITLE
Batch update identification remarks

### ISSUE THREAD

**Issue by anna-chinn** [ArctosDB/arctos#2950]
I accidentally bulkloaded our Dekay's brown snake identification remarks with a non-unicode character... Dusty, can you batch update all instances of 'Dekay��_��__��_��___��_��__��_��____s Brown Snake.' to 'Dekay's Brown Snake.' in CHAS:Herp identification remarks, please? Sorry!!

**Comment by dustymc** [comment]
```

arctosprod@arctos>> update identification set identification_remarks=replace(identification_remarks,'Dekay��_��__��_��___��_��__��_��____s Brown Snake.',$$Dekay's Brown Snake.$$) where identification_remarks='Dekay��_��__��_��___��_��__��_��____s Brown Snake.';
UPDATE 242

```

**Comment by anna-chinn** [comment]
Thanks!
