### ISSUE TITLE
error feedback

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/arctos#2951]
I am unable to create a publication:

Message: ERROR: new row for relation "publication" violates check constraint "ck_full_citation_noprint" Detail: Failing row contains (10009376, 2020, journal article, null, null, 1, Olivia A. King, Matthew R. Stimson and Spencer G. Lucas (2020) T..., King et al. 2020, 10.1080/10420940.2019.1585673, null).
Detail:
Check the Arctos Handbook for more information on errors.

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **

**Comment by Jegelewicz** [comment]
You have a hard return or some other non-printing character in the full citation field.

**Comment by mbprondzinski** [comment]
Hard return was the one thing I didn't look for!  There should be more information as to what the possible errors could be.  I changed the ampersand to "and" that didn't work.  I added the DOI which was in the title, but I left off initially...that didn't work.  There was no visible hard return in the title to begin with!  Big time waster...

**Comment by Jegelewicz** [comment]
The clue is here

> "ck_full_citation_noprint"

any time an error includes **noprint**, there is a non-printing character or hard return somewhere and in this case it tells ya where **full_citation**.

**Comment by Jegelewicz** [comment]
HAHAHAHA - see http://handbook.arctosdb.org/documentation/understanding-errors.html#check-constraint-uamck_tbl_col_noprint-violated

I was going to add this to the "How To", but it's the first thing there!

**Comment by mbprondzinski** [comment]
I know that, but as I said, there was no apparent hard return in the title.  To add to the complexity, there was a new DOI issued in 2020 that included a bunch of corrections to the original publication.  I wasn’t sure if I needed to change the date to reflect the updates or what!

**Comment by mbprondzinski** [comment]
Nothing is ever black or white in Arctos...only gray.

**Comment by mbprondzinski** [comment]
...or red.  Which reminds me, the taxonomy hierarchy was fixed for that new species, but there is still a big red "probably invalid" box to tell me I must be stupid.

**Comment by dustymc** [comment]
>was no apparent hard return in the title

Yes, that's part of the problem - many nonprinting characters are not visible in various interfaces.

>new DOI issued in 2020

I don't think that's quite true - the DOI you were using is (I think) for the correction, not the article, and isn't handled properly by crossref. The article's DOI does work, and Arctos will deal with the complexity - just paste it in, click crossref, add an agent, and save.

<img width="529" alt="Screen Shot 2020-07-22 at 7 00 56 AM" src="https://user-images.githubusercontent.com/5720791/88185925-5e695000-cbe9-11ea-84a7-7ff3e27cc2a6.png">

**Comment by mbprondzinski** [comment]
Fine, thank you, but how would I have possibly known that?!  I had the original DOI but then I saw the update with the new DOI in the article so I was conflicted, especially since I wasn't able to create the publication in Arctos.

**Comment by Jegelewicz** [comment]
> Nothing is ever black or white in Arctos...only gray.

I think that applies to life in general.

**Comment by Jegelewicz** [comment]
> ...or red. Which reminds me, the taxonomy hierarchy was fixed for that new species, but there is still a big red "probably invalid" box to tell me I must be stupid.

See https://github.com/ArctosDB/arctos/issues/2940

Hopefully this will change soon?

**Comment by dustymc** [comment]
>Hopefully this will change soon?

If that's for me, I need links and screenshots.

**Comment by mbprondzinski** [comment]
I went back to check and the red box is finally gone.  But it still says "probably invalid" in the taxon details.
![image](https://user-images.githubusercontent.com/43214224/88207520-88386c00-cc15-11ea-845e-5ccef4fe8d6c.png)

**Comment by Jegelewicz** [comment]
@mbprondzinski once GBIF picks it up from your data, that should eventually change - although it won't be overnight.

Also, note that this is only visible to Arctos operators, any public viewers will not see it.
