### ISSUE TITLE
Printing Error: Error Executing Database Query

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#2952]
I'm unable to print labels from Edit Container. I receive two different error messages depending on the label template selected.

**To Reproduce**
1.  Search for barcode, e.g., UCM_JAR-4485
2.  From Edit Container -> Print
3. Select UCM_JAR_consolidated_country_LARGE

![image](https://user-images.githubusercontent.com/11336485/88185549-4a295100-cbf1-11ea-8947-522d0f9ed4b8.png)
![image](https://user-images.githubusercontent.com/11336485/88185577-53b2b900-cbf1-11ea-8e24-1c26d6362bba.png)
![image](https://user-images.githubusercontent.com/11336485/88185609-5e6d4e00-cbf1-11ea-98d8-6fad36fbcd68.png)
![image](https://user-images.githubusercontent.com/11336485/88185652-6cbb6a00-cbf1-11ea-8d6d-f37ea832bd94.png)

Note, trying to use a different label template (UCM_JAR_consolidated_state_LARGE) gives me a DIFFERENT error:

![image](https://user-images.githubusercontent.com/11336485/88184569-1b5eab00-cbf0-11ea-93d4-eebafcfed335.png)
![image](https://user-images.githubusercontent.com/11336485/88184745-51039400-cbf0-11ea-9c99-3071fbe0f856.png)
![image](https://user-images.githubusercontent.com/11336485/88184787-6082dd00-cbf0-11ea-950c-e0d630f167e1.png)

**Additional context**
Looks like I also get the "The error occurred in /usr/local/httpd/htdocs/internal/reporter/report_printer.cfm: line 130" error when trying to Print Any Report from search results (UCM_TC_single_lot_LARGE). However, I was able to succesfully generate a pdf for my loan header and invoice so not all reports are affected.

Related to #2800 ?

**Comment by dustymc** [comment]
I added the recipe for fixing the first in https://github.com/ArctosDB/arctos/issues/2729

Rebuilding or avoiding the function (lucee doesn't like a CF tag) is going to take more time, I'll get to that as soon as I can.

**Comment by dustymc** [comment]
Patched the custom tag; should be working now.
