### ISSUE TITLE
Agent media link error

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#2953]
When trying to open a link referencing media associated with an agent (from the agent activity page), I receive an error message.

**To Reproduce**
Agent Activity page for G. Morrison: https://arctos.database.museum/agent.cfm?agent_id=21251457&agent_name=G.%20Morrison

Click media link:
![image](https://user-images.githubusercontent.com/11336485/88203107-09d4cd80-cc07-11ea-9a6a-feac10e8127c.png)

See error:
![image](https://user-images.githubusercontent.com/11336485/88203148-1bb67080-cc07-11ea-9238-ba57d6399c6b.png)

**Comment by dustymc** [comment]
thx/patched
