### ISSUE TITLE
Media Viewing Problems

### ISSUE THREAD

**Issue by PaulaBarteau** [ArctosDB/arctos#2955]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

When attempting to view media associated with a specimen in firefox a new window opens with error message "Secure Connection Failed, with URL about:blank.

**To Reproduce**
1. Go to 'https://arctos.database.museum/guid/NMMNH:Inv:4418
 (or any other specimen with media in Arctos in Firefox)'
2. Click on 'one of the media thumbnails '
3. See error: New window opens, no media available.
I have tried this logged in and logged out. I was also having this problem viewing text media as well as images. I /can/ view media, text and images, in Chrome, but my coworker cannot. We're both using windows 10.

**Expected behavior**
Clicking on media thumbnail would open a new window with the media ID URL that displays the image.

**Screenshots**
![image](https://user-images.githubusercontent.com/56838112/88225333-8b3c5800-cc27-11ea-8670-8b4aca642605.png)

** Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Works in Chrome, does not work in Firefox
 - Version [e.g. 22] ?

**Additional context**

**Priority**
Please assign a priority-label.
Not urgent, needs help

**Comment by PaulaBarteau** [comment]
@lin-fred @dustymc

**Comment by dustymc** [comment]
See https://github.com/ArctosDB/arctos/issues/2889
