### ISSUE TITLE
Nearest Barcode Missing from Review Loan Items and Download

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2956]
I sucessfully bulkloaded a loan using barcodes for subsamples, so I know that each loan item is correctly barcoded, but when I review loan items, the barcode column is blank. This column is also blank on loan item download. 

Firefox
[First Cut Loan Download.zip](https://github.com/ArctosDB/arctos/files/4963939/First.Cut.Loan.Download.zip)

![Screenshot 2020-07-22 23 14 37](https://user-images.githubusercontent.com/14808196/88254162-91efbd00-cc71-11ea-9f0e-3eeaf8007308.png)

**Comment by KyndallH** [comment]
Dusty, what more information do you need?

Before for subsampled tissues, it would have the barcode in brackets of the container holding the part. Now it is gone. 

The barcode if it is the whole specimen is still showing up.

""_Barcode" is the barcode of the container holding the part_ (present), or **when enclosed in square brackets the barcode of the container holding the part from which the loaned part was subsampled** (missing)."


<img width="2158" alt="Screen Shot 2020-07-28 at 2 56 37 PM" src="https://user-images.githubusercontent.com/16887896/88730467-8f162180-d0e2-11ea-9ac7-1ded6bae65d9.png">

**Comment by KyndallH** [comment]
Made it high since I can't process a loan till I get this fixed without a lot of pain on my end. I have a curator that adds subsample to loans before I go subsample it (yes, I know it isn't the ideal way to do it but it isn't going to change any time soon).

**Comment by dustymc** [comment]
>what more information do you need?

A link to the loan is ideal - whatever it takes to recreate the problem.

**Comment by dustymc** [comment]
And I could use some input on https://github.com/ArctosDB/arctos/issues/1295

**Comment by KyndallH** [comment]
Loan UAM 2020.004.Fish

https://arctos.database.museum/loanItemReview.cfm?transaction_id=21125667

**Comment by dustymc** [comment]
thanks fixed

**Comment by Jegelewicz** [comment]
Nice to see you @KyndallH !

**Comment by KyndallH** [comment]
Thanks! I've slowly been coming back (working about 3 hours a day) - juggling some childcare issues. Feeling so behind on everything... so much has changed in the last few months!!!

**Comment by campmlc** [comment]
Yes, so glad to hear from you, and thanks for figuring out this barcode
issue! Sorry I missed all this - had a freezer die yesterday; the usual 2
am!
