### ISSUE TITLE
Arctos Blog still accessible/active on internet

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#2958]
In cleaning out some old bookmarks, I found the Arctos Blogspot http://arctosblog.blogspot.com is still searchable and readable.

![Screen Shot 2020-07-23 at 12 39 08 PM](https://user-images.githubusercontent.com/15368365/88324886-9227a100-cce1-11ea-966c-52b8bc2f0a1b.png)

It hasn't been updated since 2011.  Maybe this doesn't matter, but should it disappear or, at least, link to our handbook?

![Screen Shot 2020-07-23 at 12 32 17 PM](https://user-images.githubusercontent.com/15368365/88324188-90111280-cce0-11ea-846a-7316df1ff076.png)

**Comment by dustymc** [comment]
Whoa...

I made it private.
