### ISSUE TITLE
test request

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#2959]
I've replaced all of the code which is used in all specimen-returning queries in test. It's only active on specimensearch/specimenresults at this time, but that will change soon. The changes are technical (better security and performance) and should not be noticeable in the UI. I don't anticipate problems, but some clicking before it goes to production - hopefully early next week - would be appreciated if anyone has time.

http://test.arctos.database.museum

**Comment by Jegelewicz** [comment]
Still noticing some (only some which seems weird) of the NMMNH Paleo private localities showing up in the search results and at the top of the record even though the private locality doesn't show in the locality part of the record.

**Comment by dustymc** [comment]
Unrelated.

(Test is an older version of PG, it's missing some tools, one of which I use to sync the flat cache where those data come from.)

**Comment by Jegelewicz** [comment]
I searched a couple things, added some columns, and it worked as expected. Wouldn't call that extensive testing....

**Comment by dustymc** [comment]
It's appreciated! We're probably overdue for an "only works for Dusty" release, I'd like to keep it that way....
