### ISSUE TITLE
Quarantined Taxon Name Notification

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#2960]
Notifications are going to DATAPROBLEMREPORTEMAIL, which isn't very visible.

How do we do better?

If anyone wants data problem reports, you can add yourself under globals, or let me know and I'll add you to the list.

@sharpphyl I think this one might be yours?

```
to me, ccicero, amgunderson, mkoo, arctoslogs
The following taxon names are quarantined but do not have relationships. Please add a taxon relationship.
https://arctos.database.museum/name/Cerithium trailii
Created By unknown on {ts '2018-09-13 12:36:00'} 
```

**Comment by Jegelewicz** [comment]
I added myself.

**Comment by sharpphyl** [comment]
Thanks.  I took care of _Cerithium trailii_.  If I need to be on the Data Problem Report email list, ok, but is there a way to only get the ones that deal with Marine Invert problems?

**Comment by campmlc** [comment]
Happy to be on the list, but I don't know where to add myself.

**Comment by dustymc** [comment]
Let me know what email you want to use and I'll get it.

**Comment by campmlc** [comment]
Should be the campbell@cara***.org associated with my account.

**Comment by dustymc** [comment]
thx/done

**Comment by Jegelewicz** [comment]
@sharpphyl you'll get them all - If I see marine stuff, I'll clue you in.
