### ISSUE TITLE
Make an external link tool

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2961]
This is kinda dumb, but I can never remember the text required to create an external link (like the Wikipedia links in the part names table). @dusty could you make a tool that lets me enter the link and the text I want to show and turn it into the appropriate external link?

So I enter:
https://en.wikipedia.org/wiki/Riker_mount
and
Wikipedia

and I get back

a   target="_blank" class="external" href="https://en.wikipedia.org/wiki/Riker_mount">Wikipedia</a>

(with < added at the beginning so that the thing works) that I can paste into whatever....

I have an excel sheet that does this, but then I have to go dig it up. This could go with the "make a comma separated list" thingee and would be there for everyone. Yay?

**Comment by dustymc** [comment]
done

**Comment by Jegelewicz** [comment]
You totally deserve that wizard hat and cape...
