### ISSUE TITLE
[CONTACT] Account lock

### ISSUE THREAD

**Issue by jwurtz01** [ArctosDB/arctos#2962]
** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **

** Outages should be reported to the contacts listed at https://arctosdb.org/arctos-down/ **

** Arctos Documentation is http://handbook.arctosdb.org/ **

** Learn more about Arctos at https://arctosdb.org/ **

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **

Hey ARCTOS Team,

I've been trying to get into my account to do some data work and I'm running into a problem. I tried logging in with my username and password but ARCTOS says that those aren't correct. So I attempted to reset the password. I got the email with the password and entered that. But when I attempt to log in with that, ARTOS says that that combination isn't correct. Is there anyway to reset the account without getting stuck in this loop?

Best,
Jason

**Comment by campmlc** [comment]
@jwurtz01 looks like your account is locked after some period of inactivity. I can unlock with supervisor permissions?

**Comment by campmlc** [comment]
We probably need to update the error message to say why the account is locked and what steps are needed to recover access. @dustymc

**Comment by jwurtz01** [comment]
@campmlc I would appreciate that!

**Comment by mkoo** [comment]
I took care of this a week and half ago after contacting curator in charge....

**Comment by campmlc** [comment]
Re-opening this so we can get this fixed: 
We probably need to update the error message to say why the account is locked and what steps are needed to recover access. @dustymc
Users whose accounts are locked get only a notification to reset their password. They reset it, and nothing happens. They get another message that their password is expired. Ad infinitum.  This is, needless to say, very frustrating.  If their account is locked, they should get a message that their account is locked and they must contact their supervisor and/or arctos for approval to reset.

**Comment by dustymc** [comment]
Done

> Authentication failed. Additional Information: The account is locked; contact your superviser or account manager to restore access.

**Comment by campmlc** [comment]
Thanks!
