### ISSUE TITLE
Better Results for Search Places

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#2963]
**Is your feature request related to a problem? Please describe.**
I often need to search for localities. The search places function is not sufficient for the tasks I need to accomplish. Specifically, there is a maximum of 100 results:
![image](https://user-images.githubusercontent.com/47402809/88438607-574b6900-cdc6-11ea-9832-0ad51db6a80d.png)
and the results are just given in a text format with no ability to see the results in a sort-able table format. 

** Describe what you're trying to accomplish** 
I need 100% of search results with the exception of some far-reaching 'all of North America" type of search that will certainly time out.

I need the results in a sort-able, downloadable table format with the ability to include the fields that I want like we have with specimen search.

**Describe the solution you'd like**
Results formatted the same way as specimen search results.

**Describe alternatives you've considered**
Currently my alternative is to resort to our old Access database which is really NOT an alternative.

**Additional context**
This has been in the back of my mind for a while, but now that NMMNHS Paleo is fully migrated to Arctos, the need is more critical. For example, today I got a very, very simple request to pull our locality number for the "Lamy Quarry". I know the quarry name is in specific locality, but I didn't know exactly how it is phrased (its actually Lamy Amphibian Quarry), so I search on specific locality = Lamy, state = New Mexico. I max out the 100 results and my match is not in there. This is complicated by the fact that some localities show up multiple times for some reason:
![image](https://user-images.githubusercontent.com/47402809/88440215-8bc12400-cdca-11ea-9878-d5035372efff.png)

When I get my next 'send me all the localities in this section and range' request, which can be a more complicated search depending on the parameters, I don't see how I'm going to be able to run that search

**Comment by campmlc** [comment]
Are you searching in Catalog Search or searching Locality?

**Comment by Jegelewicz** [comment]
> This is complicated by the fact that some localities show up multiple times for some reason:

@dustymc this is weird - that names locality should only be there once?

**Comment by Jegelewicz** [comment]
> Are you searching in Catalog Search or searching Locality?

Locality

**Comment by dustymc** [comment]
Let's merge this into https://github.com/ArctosDB/arctos/issues/2916
