### ISSUE TITLE
Remove New Hebrides from Island Group for Vanuatu

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#2964]
**Is your feature request related to a problem? Please describe.**
In databasing some specimens collected recently in Vanuatu, I researched the New Hebrides to understand why it was associated with Vanuatu.  https://en.wikipedia.org/wiki/New_Hebrides
This is the colonial name (officially New Hebrides Condominium) that existed from 1906 to 1980 when Vanuatu gained its independence from the British and French.

Per the Handbook (https://handbook.arctosdb.org/documentation/higher-geography.html): 

> Use current definitions, where possible. For example: Yugoslavia no longer exists, so use Slovenia, Croatia, or whichever country the locality is now in, especially if cataloging current material. If Yugoslavia was used in the original data, it now belongs in verbatim locality, not in Higher Geography. 

** Describe what you're trying to accomplish** 
Bring the higher geography for Vanuatu in line with the current name and status of the country.

**Describe the solution you'd like**
Since New Hebrides is a colonial name for the island group that is now Vanuatu, I recommend that it be removed from all the Vanuatu higher geography entries.  It could be included in the main Vanuatu entry as an additional search term.  Do not add Vanuatu as the Island Group but leave that for subgroups if any.  Remove New Hebrides from the list of Island Groups.

**Describe alternatives you've considered**
Ignore it

**Priority**
Normal priority but I'm adding the missing provinces without the Island Group.

**Comment by sharpphyl** [comment]
@Jegelewicz  No one has commented.  Do we need further discussion to remove New Hebrides from these higher geographies?  I can do that unless someone with higher authority should do it or it can be automated.

**Comment by dustymc** [comment]
>higher authority 

You have the power!

>automated

These few can be changed manually faster than I can write scripts, and adding search terms, confirming there's not a dot halfway around the world, etc. would be useful anyway.

I support this.

**Comment by sharpphyl** [comment]
Thanks. I removed New Hebrides from all the higher geography but I can't remove it from 

       Pacific Ocean, Vanuatu, Sanma Province, New Hebrides, Maffia Island

because the current authority - The World Factbook 2003 (online)  - isn't acceptable and I can find nothing online for Maffia Island in Vanuatu to use as an authority.  @Dusty, Can you eliminate New Hebrides with the existing authority and then remove New Hebrides from the list of Island Groups so it doesn't creep back in again?

**Comment by dustymc** [comment]
@mkoo @ccicero https://arctos.database.museum/SpecimenResults.cfm?geog_auth_rec_id=10003595 is a bunch of MVZ stuff from a place Google's never heard of. Help!

**Comment by mkoo** [comment]
Clean-up on aisle higher geography! (there were also issues with wrong
specific localities too)
Completed and New Hebrides deleted.
thanks for alerting me and fixing up Vanuatu
