### ISSUE TITLE
Minerals should have Mineral name type

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2965]
@dustymc now that we have the various name types, can you please change https://arctos.database.museum/name/Beryl to Mineral?

There are probably others - I cannot change them because they are in use. I will post them here as I find them.

**Comment by Jegelewicz** [comment]
Here they are

https://arctos.database.museum/name/Quartz
https://arctos.database.museum/name/Barite
https://arctos.database.museum/name/Calcite
https://arctos.database.museum/name/Goethite
https://arctos.database.museum/name/Hematite
https://arctos.database.museum/name/Gypsum
https://arctos.database.museum/name/Galena

Thanks!

**Comment by Jegelewicz** [comment]
@dustymc can you do this?

**Comment by dustymc** [comment]
done
