### ISSUE TITLE
TACC media Firefox error

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#2968]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
When I try to view TACC media using Firefox as browser I get this error message:

![image](https://user-images.githubusercontent.com/47402809/88581334-3d9a6380-d00a-11ea-9fe8-65a5021bf1a2.png)

**To Reproduce**
1. Go to any specimen with Tacc media using Firefox
2. Click to view the media

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 78.0.2

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Works just fine in Chrome and Edge.

**Comment by dustymc** [comment]
duplicate of https://github.com/ArctosDB/arctos/issues/2889
