### ISSUE TITLE
annotation notifications

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#2969]
Arctos currently sends emails as part of annotation submission, which isn't ideal for various reasons.

Annotations are already summarized daily in cf_report_cache (and available in the not-dashboard at the top of the TSR widget).

Need to

1. remove email call from annotation submission
2. send daily unresolved annotations email to collections

Needs prioritized. I'll set up a no-notification API for https://github.com/ArctosDB/arctos/issues/2059; API will also be available to anyone who wants to use it. Those won't spawn emails until this is implemented.

**Comment by mkoo** [comment]
This isnt really "Blocked" but users should weigh in if they have an opinion-- labels make it visible!

**Comment by dustymc** [comment]
>labels make it visible!

https://handbook.arctosdb.org/how_to/How-to-organize-Issues.html

Moving this back to where I can find it and bumping priority; we're accumulating an impressive backlog.

```
arctosprod@arctos>> select count(*) from annotations where reviewer_comment is null;
 count 
-------
 21587
```

**Comment by dustymc** [comment]
In next release, but need to add to the schedule. Tentatively planning on weekly, suggestions welcome.

**Comment by dustymc** [comment]
scheduled
