### ISSUE TITLE
error feedback--Multiple Catalog # search

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#2970]
repeatedly get error when searching for multiple catalog numbers (comma separated and space separated):

An error occurred while processing this page!
Message: ERROR: syntax error at or near "," Position: 1930
Detail:
Check the Arctos Handbook for more information on errors.
This message has been logged as 70C08119-D2CD-465E-808E9AAE9F69020C

**Comment by dustymc** [comment]
I'll have a patch out tonight

**Comment by Jegelewicz** [comment]
Oh, that's probably #2971 too....
