### ISSUE TITLE
Cannot view specimens from a project

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2971]
From this project - https://arctos.database.museum/project/10003366

when I select the link to objects used

![image](https://user-images.githubusercontent.com/5725767/88723404-07caad00-d0e6-11ea-988f-51e263603195.png)

I get this error

![image](https://user-images.githubusercontent.com/5725767/88723376-f84b6400-d0e5-11ea-9576-e4ef04284364.png)

I was not logged in.

**Comment by dustymc** [comment]
fix
