### ISSUE TITLE
Code table links not working

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2976]
@dustymc I have been working on the [formations code table](https://arctos.database.museum/Admin/CodeTableEditor.cfm?action=editNoCollectionCode&tbl=ctlithostratigraphic_formation) and something weird is happening. The first four links work fine, but after that none of them DO anything. I don't see anything different in the formatting, but maybe another pair of eyes will find something?

![image](https://user-images.githubusercontent.com/5725767/88855903-d1a62f80-d1b0-11ea-9d92-ef52fa97fd24.png)

Can you look at one of the descriptions to see if I have done something dumb?

**Comment by dustymc** [comment]
``<a target="_blank" class="external"https://macrostrat.org/sift/#/strat_name/68521">Macrostrat</a>``

should be

``<a target="_blank" class="external" href="https://macrostrat.org/sift/#/strat_name/68521">Macrostrat</a>``

**Comment by Jegelewicz** [comment]
Thank you - it's so hard to find your own mistakes sometimes!
