### ISSUE TITLE
NK number sort in Search Results

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2979]
The NK number identifiier is a numeric value, but in Search Results the column sorts as if it were alphanumeric. Any way to change this so that I can sort my preferred Other ID column as numeric when I click the header?

**Comment by dustymc** [comment]
In theory: convert othercatalognumbers to json, pull NK::numeric from it as a pseudocolumn

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/2745
