### ISSUE TITLE
Add Wolfcampian to Informal Chronostratigraphy Table

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#2981]
**Goal**
Wolfcampian is an informal chronostratigraphic unit widely used in the Southwest USA.

**Context**
The term is useful for local geologic context. We have localities that have been placed in this unit, that information is currently residing in chronostrat remarks where it is not very useful or searchable.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctchronostrat_informal

**Value**
Wolfcampian (Series/Epoch)

**Documentation**
https://ngmdb.usgs.gov/Geolex/Units/Wolfcampian_11899.html

**Comment by Jegelewicz** [comment]
Done - but now we need to add this locality attribute to all localities that have it in Series/Epoch Cisuralian remarks.

**Comment by Jegelewicz** [comment]
Here are the localities (private and public) that need it

8209
8210
8656
8657
8658
8659
8660
8661
8662
8663
8664
8665
8666
8667
8668
8669
8670
348
837
843
846
869
870
871
1100
1198
1199
1339
1372
1374
1375
1378
1448
1449
1450
1461
2771
2772
2773
2774
2775
2776
2777
2811
2812
2813
2814
2815
2816
2817
2818
2819
2820
2821
2822
2823
2824
2825
2826
2827
2828
2829
2830
2831
2832
2833
2834
2835
2836
2837
2838
2839
2840
2841
2842
2843
2844
2845
2846
2847
2848
2849
2850
2851
2852
2855
2856
2936
2937
2938
2939
3010
3011
3012
3013
3014
3015
3016
3017
3018
3019
3020
3021
3022
3023
3024
3035
3036
3037
3038
3039
3111
3112
3223
3250
3344
3391
3392
3394
3424
3425
3426
3453
3534
3535
3536
3557
3673
3675
3678
3754
3922
3923
3924
3925
3926
3927
3928
4259
4368
4369
4370
4371
4372
4373
4375
4376
4397
4490
4507
4508
4509
4510
4511
4512
4516
4517
4518
4565
4566
4567
4568
4577
4578
4579
4580
4639
4640
4668
4674
4675
4706
4707
4727
4824
4825
4826
4827
4960
4967
4968
4969
4970
4971
4972
4973
4974
4975
4976
4977
4978
4990
4991
4993
4995
4996
4997
4998
4999
5000
5001
5002
5003
5004
5005
5006
5007
5075
5123
5125
5126
5313
5314
5366
5377
5378
5379
5380
5381
5382
5383
5385
5386
5387
5388
5395
5414
5415
5416
5417
5605
5606
5625
5632
5634
5661
5662
5679
5722
5723
5809
5810
5811
5812
5813
5872
5873
6038
6040
6052
6137
6684
6685
6686
6708
6776
6777
6780
6781
6785
6822
6825
6938
7666
7667
7668
7669
7670
7671
7726
7765
7878
7889
7898
7899
7900
7901
7902
7917
7918
7919
7920
7921
7922
7923
7924
7925
7926
7927
7928
7930
7931
7933
7934
7981
7986
7987
8030
8070
8083
8087
8088
8096
8108
8110
8111
8119
8120
8122
8176
8177
8206
8207
8208
8211
8212
8213
8214
8215
8216
8217
8218
8220
8221
8222
8250
8252
8253
8254
8255
8261
8262
8267
8278
8289
8290
8292
8294
8298
8376
8641
8642
8643
8706
8711
8712
8717
8726
8737
8752
8753
8754
8771
8778
8781
8782
8783
8785
8786
8787
8788
8790
8791
8792
8793
8794
8795
8798
8799
8800
8817
8818
8819
8826
8838
8890
9082
9123
9124
9503
9504
9505
9506
9507
9508
9509
9510
9511
9512
9853
10200
10201
10202
10203
10204
10213
10214
12030
8741
632
4363
5721
6117
6118
6119
6120
6121
6122
6123
6124
6125
6126
6127
6128
6129
6130
6131
6132
6138
6842
7055
7056
7057
7058
7059
7060
7061
7062
7903
7904
7905
7906
7907
7908
7909
7910
7911
7912
7913
7914
7915
7916
7929
7935
7936
7937
7938
7939
7940
7941
7942
7943
7944
7945
7946
7947
7948
7949
7950
7951
7952
7953
7954
7955
7956
7957
7958
7959
7960
7961
7962
7963
7964
7965
7966
7967
7968
7969
7970
7971
7972
7973
7974
7975
7976
7977
7978
7979
7980
7982
7983
7984
7985
7988
7989
7990
7991
7992
7993
7994
7995
7996
7997
7998
7999
8000
8001
8002
8003
8004
8005
8006
8007
8008
8009
8010
8011
8012
8013
8014
8015
8016
8018
8019
8020
8021
8022
8023
8024
8025
8026
8256
8257
8258
8259
8260
8291
8526
8527
8528
8529
8530
8531
8532
8533
8534
8535
8536
8537
8538
8539
8540
8541
8542
8543
8544
8545
8546
8547
8703
8704
8705
8709
8710
8713
8714
8718
8719
8720
8721
8722
8723
8724
8725
8727
8728
8729
8730
8731
8732
8733
8734
8735
8736
8796
8797
8801
8843

/remind me to do this

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
@Jegelewicz Thank you! Do we have any other informal chronostrat in remarks?

**Comment by Jegelewicz** [comment]
I don't think so, but I can dig around to see if there are any more.

**Comment by Jegelewicz** [comment]
I have a spreadsheet set up in the dropbox - waiting to see how locality bulkloader works in test before requesting.

**Comment by Jegelewicz** [comment]
Done!
