### ISSUE TITLE
Darwin Core Million Challenge

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2982]
Don't get excited about the "million" - it isn't dollars, but it is a challenge we should be able to accept...

https://iphylo.blogspot.com/2020/07/darwin-core-million-now-twice-year.html

**Comment by ewommack** [comment]
I agree, we should be able to accept this challenge. We should have over a million specimens following Darwin Core standards in an open data repository. Does Arctos count as an open data repository?

**Comment by Jegelewicz** [comment]
> Does Arctos count as an open data repository?

I would say so - however, it isn't necessarily in DwC format. But we could create a DwC download...

**Comment by ewommack** [comment]
I was looking at all of the requirements for the good data. I'm guessing that specimens that have ambiguous localities and dates wouldn't work, so maybe only things with full georefencing?

**Comment by Mesibov** [comment]
Please note that the requested submissions aren't a million *records*, they're to be around a million *data items*, e.g. 20000 records with 50 populated fields.

"I'm guessing that specimens that have ambiguous localities and dates wouldn't work, so maybe only things with full georefencing?"

The challenge isn't about data item *content*, but about record and field structuring, formatting and consistency. You could have the string "We have no idea" in the habitat field, and so long as the string is consistent, that's a valid data item (although leaving the field blank would be better).

Sounds easy? It should be, but in years of auditing DwC datasets I have yet to see that's a clear DwC Million winner.
