### ISSUE TITLE
New attribute - lustre

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2983]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Goal**
Describe mineral parts with searchable terms used by the community.

**Context**
We don't really have mineral stuff in Arctos at the moment.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type

**Value**
lustre

**Definition**
Lustre (luster; US English) or l is the way light interacts with the surface of a crystal, rock, or mineral.

**Collection type**
N/A

**Attribute data type**
categorical

**Attribute value**
New table ctlustre
Term | Definition
 -- | -- 
adamantine | Adamantine minerals possess a superlative lustre, which is most notably seen in diamond. Such minerals are transparent or translucent, and have a high refractive index (of 1.9 or more). <a target="_blank" class="external" href="https://en.wikipedia.org/wiki/Lustre_(mineralogy)#Adamantine_lustre">Wikipedia</a> 
subadamantine | Minerals with a lesser (but still relatively high) degree of lustre than adamantine, some examples being garnet and corundum <a target="_blank" class="external" href="https://en.wikipedia.org/wiki/Lustre_(mineralogy)#Adamantine_lustre">Wikipedia</a> 
dull | Dull minerals exhibit little to no lustre, due to coarse granulations which scatter light in all directions, approximating a Lambertian reflector. An example is kaolinite. <a target="_blank" class="external" href="https://en.wikipedia.org/wiki/Lustre_(mineralogy)#Dull_lustre">Wikipedia</a> 
earthy | Coarser, and having even less lustre than dull minerals. <a target="_blank" class="external" href="https://en.wikipedia.org/wiki/Lustre_(mineralogy)#Dull_lustre">Wikipedia</a> 
greasy | Greasy minerals resemble fat or grease. A greasy lustre often occurs in minerals containing a great abundance of microscopic inclusions, with examples including opal and cordierite, jadeite. Many minerals with a greasy lustre also feel greasy to the touch. <a target="_blank" class="external" href="https://en.wikipedia.org/wiki/Lustre_(mineralogy)#Greasy_lustre">Wikipedia</a> 
metallic | Metallic (or splendent) minerals have the lustre of polished metal, and with ideal surfaces that will work as a reflective surface.  Examples include galena, pyrite and magnetite. <a target="_blank" class="external" href="https://en.wikipedia.org/wiki/Lustre_(mineralogy)#Metallic_lustre">Wikipedia</a> 
pearly | Pearly minerals consist of thin transparent co-planar sheets. Light reflecting from these layers give them a lustre reminiscent of pearls.[9] Such minerals possess perfect cleavage, with examples including muscovite and stilbite. <a target="_blank" class="external" href="https://en.wikipedia.org/wiki/Lustre_(mineralogy)#Pearly_lustre">Wikipedia</a> 
resinous | Resinous minerals have the appearance of resin, chewing gum or (smooth-surfaced) plastic. A principal example is amber, which is a form of fossilized resin, <a target="_blank" class="external" href="https://en.wikipedia.org/wiki/Lustre_(mineralogy)#Resinous_lustre">Wikipedia</a> 
silky | Silky minerals have a parallel arrangement of extremely fine fibres, giving them a lustre reminiscent of silk. Examples include asbestos, ulexite and the satin spar variety of gypsum. <a target="_blank" class="external" href="https://en.wikipedia.org/wiki/Lustre_(mineralogy)#Silky_lustre">Wikipedia</a> 
fibrous | A fibrous lustre is similar, but has a coarser texture. <a target="_blank" class="external" href="https://en.wikipedia.org/wiki/Lustre_(mineralogy)#Silky_lustre">Wikipedia</a> 
submetallic | Submetallic minerals have similar lustre to metal, but are duller and less reflective. A submetallic lustre often occurs in near-opaque minerals with very high refractive indices, such as sphalerite, cinnabar, anthracite, and cuprite. <a target="_blank" class="external" href="https://en.wikipedia.org/wiki/Lustre_(mineralogy)#Submetallic_lustre">Wikipedia</a> 
vitreous | Vitreous minerals have the lustre of glass. (The term is derived from the Latin for glass, vitrum.) This type of lustre is one of the most commonly seen, and occurs in transparent or translucent minerals with relatively low refractive indices. Common examples include calcite, quartz, topaz, beryl, tourmaline and fluorite, among others. <a target="_blank" class="external" href="https://en.wikipedia.org/wiki/Lustre_(mineralogy)#Vitreous_lustre">Wikipedia</a> 
waxy | Waxy minerals have a lustre resembling wax. Examples include jade and chalcedony. <a target="_blank" class="external" href="https://en.wikipedia.org/wiki/Lustre_(mineralogy)#Waxy_lustre">Wikipedia</a> 

**Attribute units**
N/A

**Part tissue flag**
N/A

**Other ID BaseURL**
N/A

**Priority**
Please assign a priority-label. Bumping priority as we will soon be ready to bulkload NMMNH Minerals.

**Comment by dustymc** [comment]
Are these attributes of individual specimens or species? Eg is the intent to add "waxy" to every single jade specimens, or are there unidentified waxy specimens which might be jade, or jade specimens which aren't waxy, or ??????

**Comment by Jegelewicz** [comment]
I had this exact same question as I was creating the table. @Nicole-Ridgwell-NMMNHS can confirm, but I do think these terms are applicable to individual specimens as not ALL jade is "waxy", just most jade?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Many minerals can have a range of possible lustres.

**Comment by Jegelewicz** [comment]
@dustymc good enough answer?

**Comment by dustymc** [comment]
Almost...

>individual specimens

Records or parts?

**Comment by Jegelewicz** [comment]
I think parts, but @Nicole-Ridgwell-NMMNHS should confirm.

Should this be a part attribute or a specimen attribute?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Specimen attribute I think, although as we discussed at the meeting, the line between those two types of attributes is fuzzy.

**Comment by Jegelewicz** [comment]
I'm convinced - so this will be a specimen attribute.

Already added to the https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type code table. @dustymc I just need ctlustre table for controlled vocabulary to be created and I will populate.

**Comment by dustymc** [comment]
Is there some compelling reason to use the British spelling?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I'm fine with using the American spelling. They are both commonly used.

**Comment by Jegelewicz** [comment]
I just used it because it seemed preferred (Wikipedia uses it) https://en.wikipedia.org/wiki/Lustre_(mineralogy) but I will go with what @Nicole-Ridgwell-NMMNHS says!

**Comment by Jegelewicz** [comment]
Changed in attribute code table to luster.

**Comment by dustymc** [comment]
done

**Comment by Jegelewicz** [comment]
Code table terms added. Code table tied to attribute.
