### ISSUE TITLE
New catalog item attribute - crystal habit

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2984]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Goal**
Apply appropriate descriptive terms to minerals

**Context**
New mineral collection coming into Arctos

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type

**Value**
crystal habit

**Definition**
In mineralogy, crystal habit is the characteristic external shape of an individual crystal or crystal group. A single crystal's habit is a description of its general shape and its crystallographic forms, plus how well developed each form is. <a target="_blank" class="external" href="https://en.wikipedia.org/wiki/Crystal_habit">Wikipedia</a>

**Collection type**
N/A

**Attribute data type**
categorical

**Attribute value**
New code table ctcrystal_habit

 Term | Definition 
 -- | -- 
 acicular | Needle-like, slender and/or tapered such as natrolite or rutile. 
 amygdaloidal | Like embedded almonds such as heulandite and subhedral zircon. 
 bladed | Blade-like, slender and flattened such as actinolite and kyanite. 
 botryoidal | globular or grape-like, hemispherical masses such as hematite, pyrite, malachite, smithsonite, or hemimorphite. 
 columnar | Similar to fibrous: Long, slender prisms often with parallel growth such as calcite, gypsum/selenite. 
 coxcomb | Aggregated flaky or tabular crystals closely spaced such as barite and marcasite. 
 cubic | Cube shape such as pyrite, galena or halite. 
 dendritic | Also arborescent. Tree-like, branching in one or more direction from central point such as romanechite, magnesite or native copper. 
 dodecahedral | Rhombic dodecahedron, 12-sided such as garnet. 
 druse | Also drusy or encrustation. Aggregate of minute crystals coating a surface or cavity such as uvarovite, malachite or azurite. 
 enantiomorphic | Mirror-image habit (i.e. crystal twinning) and optical characteristics; right- and left-handed crystals such as quartz, plagioclase or staurolite. 
 equant, stout | Length, width, and breadth roughly equal such as olivine and garnet. 
 fibrous | Extremely slender prisms such as serpentine group, tremolite (i.e. asbestos). 
 filiform | Also capillary. Hair-like or thread-like, extremely fine such as many zeolites. 
 foliated | Also micaceous or lamellar (layered). Layered structure, parting into thin sheets such as muscovite and biotite. 
 granular | Aggregates of anhedral crystals in matrix such as bornite and scheelite. 
hemimorphic | Doubly terminated crystal with two differently shaped ends such as hemimorphite and elbaite. 
hexagonal | Hexagon shape, six-sided such as quartz and hanksite. 
hopper crystals | Like cubic, but outer portions of cubes grow faster than inner portions, creating a concavity such as halite, calcite or synthetic bismuth. 
mammillary | Breast-like: surface formed by intersecting partial spherical shapes, larger version of botryoidal, also concentric layered aggregates such as malachite and hematite. 
massive | Also compact massive Shapeless, no distinctive external crystal shape such as limonite, turquoise, cinnabar or realgar. 
nodular | Also tuberose. Deposit of roughly spherical form with irregular protuberances such as chalcedony. 
octahedral | Octahedron, eight-sided (two pyramids base to base) such as diamond and magnetite. 
platy | Flat, tablet-shaped, prominent pinnacoid such as wulfenite. 
plumose | Fine, feather-like scales such as aurichalcite, boulangerite or mottramite. 
prismatic | Elongate, prism-like: well-developed crystal faces parallel to the vertical axis such as tourmaline and beryl. 
pseudo-hexagonal | Hexagonal appearance due to cyclic twinning such as aragonite and chrysoberyl. 
radiating | Also radial or divergent. Radiating outward from a central point without producing a star (crystals are generally separated and have different lengths) such as stibnite. 
reniform | Also colloform. Similar to botryoidal/mamillary: intersecting kidney-shaped masses such as hematite, pyrolusite or greenockite. 
reticulated | Crystals forming net-like intergrowths such as cerussite. 
rosette | Also lenticular (lens shaped crystals). Platy, radiating rose-like aggregate such as gypsum and, barite (i.e. desert rose). 
sphenoid | Wedge-shaped such as sphene. 
stalactitic | Forming as stalactites or stalagmites; cylindrical or cone-shaped such as calcite, goethite or malachite. 
stellate | Star-like, radial aggregates radiating from a "star"-like point to produce gross spheres (crystals are not or weakly separated and have similar lengths) such as pyrophyllite, aragonite, wavellite and pyrite suns.
striated |Not a habit per se, but a condition of lines that can grow on certain crystal faces on certain minerals such as tourmaline, pyrite, quartz, feldspar and sphalerite. 
tabular | Also stubby or blocky. More elongated than equant, slightly longer than wide, flat tablet-shaped such as feldspar and topaz. 
tetrahedral | Tetrahedra-shaped crystals such as tetrahedrite, spinel and magnetite. 
wheat sheaf | Aggregates resembling hand-reaped wheat sheaves such as stilbite. 

**Attribute units**
N/A

**Part tissue flag**
N/A

**Other ID BaseURL**
N/A

**Priority**
Please assign a priority-label. Bumping priority as NMMNH minerals will soon be ready for bulkload.

**Comment by Jegelewicz** [comment]
@Nicole-Ridgwell-NMMNHS we changed luster to a catalog item attribute - do you want to do the same with this?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Yes

**Comment by Jegelewicz** [comment]
Table terms added.

**Comment by Jegelewicz** [comment]
attribute added to code table and associated with categorical table.
