### ISSUE TITLE
Locality Attributes - Documentation

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#2985]
We need to add documentation for the new locality attributes. We need to update here;

https://handbook.arctosdb.org/documentation/geology.html Maybe update title of this page to Locality Attributes (incl. Geology)

and here:

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlocality_attribute_type

I can work on compiling the definitions for the locality attribute code table.

**Comment by Jegelewicz** [comment]
@Nicole-Ridgwell-NMMNHS I'll work on the handbook page this afternoon. It would be great if you could put together the definitions!

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Here are the definitions I put together:

biostratigraphic zone: A body of rock strata that is defined or characterized on the basis of its contained fossils.

Eon/Eonothem: chronostratigraphic units in the International Chronostratigraphic Chart []((https://stratigraphy.org/chart))

Era/Erathem: chronostratigraphic units in the International Chronostratigraphic Chart []((https://stratigraphy.org/chart))

informal chronostratigraphy: published chronostratigraphic units that are not in the International Chronostratigraphic Chart, for example, regional chronostratigraphies

landholder: the legal landowner or government land administration agency

lithodemic suite: a unit of lithodemic stratigraphy (describes bodies of rock which do not conform to the law of superposition)

lithostratigraphic bed: a named lithostratigraphic bed [](https://en.wikipedia.org/wiki/Bed_(geology))

lithostratigraphic formation: [](https://en.wikipedia.org/wiki/Geological_formation)

lithostratigraphic group: [](https://en.wikipedia.org/wiki/Group_(stratigraphy))

lithostratigraphic member:[]( https://en.wikipedia.org/wiki/Stratigraphic_unit#Member)

locality access: setting this attribute to private makes the locality invisible to anyone without access to your collection

Series/Epoch: chronostratigraphic units in the International Chronostratigraphic Chart []((https://stratigraphy.org/chart))

site found: the date and the agent(s) who originally found and reported the locality to a collecting institution

site identifier: any identifiers assigned to a site or locality that are in addition to locality_name

Stage/Age: chronostratigraphic units in the International Chronostratigraphic Chart []((https://stratigraphy.org/chart))

Substage/Subage: chronostratigraphic units in the International Chronostratigraphic Chart []((https://stratigraphy.org/chart))

System/Period: chronostratigraphic units in the International Chronostratigraphic Chart []((https://stratigraphy.org/chart))

TRS aliquot: quarter sections units of the Public Land Survey System

TRS range: 6 mile east-west units of the Public Land Survey System

TRS section: 1 square mile units of the Public Land Survey System

TRS township: 6 mile north-south units of the Public Land Survey System

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
And - I just realized that biostratigraphy and biochronology ended up lumped together.

**Comment by Jegelewicz** [comment]
Added those definitions to the code table and the documentation. Thanks!!!!

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
https://github.com/ArctosDB/arctos/issues/2987#issuecomment-667401431

> The basic unit of biochronology is the biostratigraphic zone, or biozone, a collection of fossils found together in a rock unit. The following biozone groups are available in Arctos:

Should be The basic unit of biochronology is the biochron, a collection of fossils found together in a rock unit. The following biochron groups are available in Arctos:

> Chronostratigraphy is the branch of geologic stratigraphy in which strata . . .

Should be Chronostratigraphy is the branch of geologic stratigraphy in which units . . .

In the list of Chronostratigraphy units we should switch some around so they are consistantly Chronostrat/Geochron, so:
Eonothem/Eon
Erathem/Era
System/Period
Series/Epoch
Stage/Age
And for definitions of these, we can just link to wikipedia.

> Lithostratigraphy is the branch of geologic stratigraphy in which stata . . .

Should be Lithostratigraphy is the branch of geologic stratigraphy in which units . . .

I think we can entirely remove petrology from the documentation, we don't have any petrology code tables at the moment.

**Comment by Jegelewicz** [comment]
> In the list of Chronostratigraphy units we should switch some around so they are consistantly Chronostrat/Geochron, so:
> Eonothem/Eon
> Erathem/Era
> System/Period
> Series/Epoch
> Stage/Age

but the terms currently in the document reflect how terms are presented in the code table....

otherwise, I made the edits. Thanks!

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> reflect how terms are presented in the code table

Ugh, I hadn't noticed that and I assume that is not an easy change. If so, then lets just leave it like it is for now.

**Comment by mkoo** [comment]
@Nicole-Ridgwell-NMMNHS is this documentation resolved? Please go ahead and close this issue if so!
