### ISSUE TITLE
Linking to Arctos specimen data from Library Sketchfab

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#2986]
The UWYMV is working with the University of Wyoming library to 3D scan skulls in our collection. Eventually we are planning to get the scans onto MorphoSource, but this first push is focusing on providing material for classes and public education. The fastest and easiest method has been to use the University of Wyoming Library's account in Sketchfab to get the material available quickly and easily for people to use:
[https://skfb.ly/6TQTE](https://skfb.ly/6TQTE)

[https://skfb.ly/6TQTJ](https://skfb.ly/6TQTJ)

[https://skfb.ly/6TQTL](https://skfb.ly/6TQTL)

The library has asked us what type of meta data we would like to include with each image, and while specimen number and species name were easy to do, we were trying to figure out if it would be possible to simply supply a link to the specimen page for each animal that people could click on to take them to Arctos where they could get the rest of the information.

So for the above scans that would be:
[https://arctos.database.museum/guid/UWYMV:Mamm:5429](https://arctos.database.museum/guid/UWYMV:Mamm:5429)
[https://arctos.database.museum/guid/UWYMV:Mamm:6529](https://arctos.database.museum/guid/UWYMV:Mamm:6529)

I wanted to double check that those are the easiest links to provide for the objects, and the best way we can go about helping to provide the library with the metadata in an easy to access format.

**Comment by Jegelewicz** [comment]
Thought I was gonna be cool and just create the media for you, but I cannot pick a relationship.

![image](https://user-images.githubusercontent.com/5725767/89081036-b3266c80-d347-11ea-8218-77ac5fb424f0.png)

@dustymc can you figure this out?

**Comment by Jegelewicz** [comment]
I think that creating the media in Arctos with a relationship to the specimen record would be the best metadata on our end. But from their side, yes, I think a link to those urls would be awesome!

**Comment by ewommack** [comment]
Thanks @Jegelewicz! 

So at least we'll have the info right in one direction. It would be great to figure out how to add to them to Arctos, but I just do not know how. They're not images, they're more links to a model that you can download (I think).

**Comment by Jegelewicz** [comment]
I can show you - but Dusty has to fix that relationship thingee first. This is sooooooooo cooooool!!!!!!

**Comment by dustymc** [comment]
Yes https://arctos.database.museum/guid/UWYMV:Mamm:5429 is the GUID and suitable for this. They can use it to pull data from the API (or GBIF if they want to go through an exchange standard), but unless they have the resources to maintain that I'd discourage it - it'll get stale and confusing.

@Jegelewicz see

<img width="755" alt="Screen Shot 2020-07-31 at 3 23 15 PM" src="https://user-images.githubusercontent.com/5720791/89082070-d0f0d300-d341-11ea-976e-ea2529482cf4.png">

**Comment by Jegelewicz** [comment]
I can't create the relationship - when I select the dropdown nothing happens....

**Comment by Jegelewicz** [comment]
And I can't create it from the record - cause I don't have access to it.

**Comment by ewommack** [comment]
No worries. I'll figure it out then. 

Glad you like it! It was a suggestion that came about this summer, and then the library is helping make it possible. 

Apparently teeth are hard to image with 3D camera set-ups, since they are shiny. We're learning about the limits and abilities as we go.

**Comment by mkoo** [comment]
Hey @ewommack please be sure to update with some example records that have sketchfab associated with them!

**Comment by ewommack** [comment]
I will. I'm still waiting to get the final images from the library for specimens. The ones I had before were previews.

**Comment by ewommack** [comment]
/remind me to check on this in a week

**Comment by ebraker** [comment]
@ewommack just reading through some past issues on media and whoa!...these are SO cool.  Are these models produced using photogrammetry? I'd love to learn more about this project as it is something we might pursue for adapting our teaching collections for online learning (a big push for CU, even pre-COVID). Plus, there are many research specimens that supplement our teaching collection that are "no touch" specimens during lab - this would be a cool way to give students a better look.

**Comment by dustymc** [comment]
I linked https://arctos.database.museum/guid/UWYMV:Mamm:6529 - here's how.

<img width="645" alt="Screen Shot 2020-12-15 at 8 22 26 AM" src="https://user-images.githubusercontent.com/5720791/102242373-d5f88e00-3eae-11eb-96b4-da5fd47a1f95.png">

<img width="421" alt="Screen Shot 2020-12-15 at 8 22 59 AM" src="https://user-images.githubusercontent.com/5720791/102242395-da24ab80-3eae-11eb-8c93-fdc8212228d2.png">

**Comment by jldunnum** [comment]
I have a short tutorial on my home desktop I need to post.

______________________________________________________________

Jonathan L. Dunnum Ph.D.
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by ewommack** [comment]
Thanks @dustymc and @jldunnum!

One of the nifty things about this project is that it has been a collaboration between the UWYMV and the UWY Library. I can get you in touch with our library's digital department @ebraker if you want the nitty gritty. My understanding is it is not a scan, but photogrammetry. However with the pandemic I haven't been able to observe the process. It has also limited us by size (muskrat size and larger), and also fiddly things do not work so well. We just got our [pelican skull model up ](https://sketchfab.com/3d-models/uwymv4104-pelecanus-erythrorhynchos-skull-1ff8f0fa61f249fc9262e82d06b0aacf), but were only able to do the individual [upper mandible](https://sketchfab.com/3d-models/uwymv4104-pelecanus-erythrorhynchos-crania-f0cfb6adfd4e4edeb27a2f9f6ea0711b), as the lower kept contorting when not attached to another surface.

**Comment by ewommack** [comment]
@dustymc, I find the URL to use by going to the sketchfab model and clicking the share arrow correct?

**Comment by ewommack** [comment]
Alright, I think I figured it out. Check out: https://arctos.database.museum/guid/UWYMV:Mamm:6529

One last question @dustymc: this may be too complicated, but is there any way to add a thumbnail preview of the model? It looks like you can copy some code from Sketchfab to embed the model....but I'm not sure if that is what we are looking for.

```
<div class="sketchfab-embed-wrapper">
    <iframe title="A 3D model" width="640" height="480" src="https://sketchfab.com/models/87246c6200dd489398e353ff6c7613ae/embed?autostart=0&amp;ui_controls=0&amp;ui_infos=0&amp;ui_inspector=0&amp;ui_stop=0&amp;ui_watermark=1&amp;ui_watermark_link=1" frameborder="0" allow="autoplay; fullscreen; vr" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>
    <p style="font-size: 13px; font-weight: normal; margin: 5px; color: #4A4A4A;">
        <a href="https://sketchfab.com/3d-models/uwymv-6529-puma-concolor-hippolestes-mandible-87246c6200dd489398e353ff6c7613ae?utm_medium=embed&utm_source=website&utm_campaign=share-popup" target="_blank" style="font-weight: bold; color: #1CAAD9;">UWYMV 6529, Puma concolor hippolestes - Mandible</a>
        by <a href="https://sketchfab.com/uwlibraries?utm_medium=embed&utm_source=website&utm_campaign=share-popup" target="_blank" style="font-weight: bold; color: #1CAAD9;">University of Wyoming Libraries</a>
        on <a href="https://sketchfab.com?utm_medium=embed&utm_source=website&utm_campaign=share-popup" target="_blank" style="font-weight: bold; color: #1CAAD9;">Sketchfab</a>
    </p>
</div>
```

**Comment by ebraker** [comment]
@ewommack Looks like you may be able to grab a preview image from the Inspect Elements page (right-click on webpage of model you want previewed).

![image](https://user-images.githubusercontent.com/11336485/102376230-a5812480-3f80-11eb-84b7-2eeaea0c7c0e.png)

Grab any of the static icon links, e.g.:
https://media.sketchfab.com/models/87246c6200dd489398e353ff6c7613ae/thumbnails/84cc67ed43814626b67d4b3c4f59c6cc/806fb00c0f0b490d90e7e65b8a5eda28.jpeg

And yes, if you wouldn't mind putting me in touch with your digital libraries people, that would be great!

**Comment by dustymc** [comment]
@ewommack I just copied from your post above...

I hope we can eventually find the resources to rebuild our thumb-builder so it can handle things like this, but it can't yet - you'll have to make them, ask the library for them, dig them out of source, etc. See also https://handbook.arctosdb.org/documentation/media.html#preview - the link above is 66K, Arctos won't display it as a preview.

**Comment by ebraker** [comment]
Oops. I think there is a smaller Twitter preview link in there somewhere.

**Comment by ewommack** [comment]
I've been adding the media to the Arctos specimens, but when I click on the Media Available bear icon I get the following error:
There may be a problem with the linked resource.
Status: 403 An unknown error occurred

Click the following link(s) to attempt to load the resource manually.

Please Contact Us if you experience additional problems with the link.

Link as provided: https://skfb.ly/6WPPU

When I click the link it takes me straight to the Sketchfab model. @dustymc did I enter the media wrong?

**Comment by ewommack** [comment]
Sorry - example:
https://arctos.database.museum/media/10619052?open
https://arctos.database.museum/guid/UWYMV:Mamm:6529

**Comment by dustymc** [comment]
Arctos pre-fetches external resources (lest we get blamed for random things breaking!), this one seems to be blocking Arctos but letting people in.

**Comment by ewommack** [comment]
@dustymc would it help if I contacted Sketchfab to see if they are the ones blocking us?

**Comment by dustymc** [comment]
Maybe. I'm making a HEAD request, here's the full result.

<img width="1362" alt="Screen Shot 2021-02-04 at 9 27 28 AM" src="https://user-images.githubusercontent.com/5720791/106931294-46f83d00-66cb-11eb-8fa0-2bae307f03fd.png">

**Comment by ewommack** [comment]
For personal education, what is a HEAD request?

**Comment by dustymc** [comment]
>what is a HEAD request?

"Poke it with a stick, see if it's alive." I use it as a way to check a resource without requiring much data transmission from either of us.

https://tools.ietf.org/html/rfc7231#section-4.3.2

**Comment by ewommack** [comment]
Cool! Thanks for the info.
Did the HEAD Request come back with any info.

Let me know if you need me to contact sketchfab.
