### ISSUE TITLE
Arctosdb.org down

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2988]
![image](https://user-images.githubusercontent.com/5725767/89080150-4c07b880-d345-11ea-9bb9-581a839be1c0.png)

**Comment by mkoo** [comment]
how old is this issue? it was temporarily unretrievable Monday early morning when I did the last of the DNS switch but works now for me? (friday PM when I saw this)

 I sent an alert to the AWG about this site and handbook.arctosdb.org as they were both toast for about 15 minutes for me (although it may be longer for others depending on the internet)

Let me know if it's still an issue

**Comment by AJLinn** [comment]
Still dead to me...
<img width="1145" alt="Screen Shot 2020-07-31 at 4 47 39 PM" src="https://user-images.githubusercontent.com/17605945/89090167-9ab95080-d34d-11ea-806b-1d255149c62a.png">

**Comment by Jegelewicz** [comment]
I just put this issue up a couple of hours ago.

**Comment by AJLinn** [comment]
It was down on Wednesday also tho - I accidentally clicked on the bear logo and got the error but didn't have time to file an issue.

**Comment by sharpphyl** [comment]
It's accessible now.

**Comment by mkoo** [comment]
Glad to hear it!
