### ISSUE TITLE
chronostrat_series_epoch term issues

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2989]
Using this thread to document problematic terms in the [chronostrat_series_epoch code table](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctchronostrat_series_epoch).

**Comment by Jegelewicz** [comment]
**Lower Mississippian**

Should be an informal term? = Tournaisian Stage/Age

**Comment by Jegelewicz** [comment]
**Lower Pennsylvanian**

Should be an informal term? = Bashkirian Stage/Age

**Comment by Jegelewicz** [comment]
**Middle Mississippian**

Should be an informal term? = Visean Satge/Age

**Comment by Jegelewicz** [comment]
**Middle Pennsylvanian**

Should be an informal term? = Moscovian Satge/Age

**Comment by Jegelewicz** [comment]
**Upper Mississippian**

Should be an informal term? = Serpukhovian Stage/Age

**Comment by Jegelewicz** [comment]
**Upper Pennsylvanian**

Should be an informal term? = Gzhelian Stage/Age and Kasimovian Stage/Age

**Comment by Jegelewicz** [comment]
For all of the above, see [ICS Chart](https://stratigraphy.org/icschart/ChronostratChart2020-01.pdf)

**Comment by Jegelewicz** [comment]
**Leonardian**

Not in the ICS Chart - move to informal? See https://ngmdb.usgs.gov/Geolex/UnitRefs/LeonardianRefs_11856.html

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
For Mississippian and Pennsylvanian, see this paper: [https://ddd.uab.cat/pub/geoact/geoact_a2006v4n3/geoact_a2006v4n3p403.pdf](https://ddd.uab.cat/pub/geoact/geoact_a2006v4n3/geoact_a2006v4n3p403.pdf)

In short, ICS recognizes Upper, Middle, and Late Mississippian and Pennsylvanian as Series.

Mississippian and Pennsylvanian themselves are subsystems of the Carboniferous, I think we should move them over to the system/period table.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> Leonardian

Yes, move to informal

**Comment by Jegelewicz** [comment]
> 
> 
>     Leonardian
> 
> Yes, move to informal

Done

**Comment by Jegelewicz** [comment]
> Mississippian and Pennsylvanian themselves are subsystems of the Carboniferous, I think we should move them over to the system/period table.

This will be a pretty big undertaking - lots of localities use them currently. Is it worth it, or can we just leave them where they are?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
It doesn't need to be done immediately, but yes we need to plan to move them. Especially in the USA Mississippian and Pennsylvanian are used as System/Period rather than using Carboniferous. Putting them in with Series is just incorrect.

**Comment by Jegelewicz** [comment]
All corrected or proposed changes are in other issues.
