### ISSUE TITLE
Unable to open Specimens in Collecting Event

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#2990]
**Describe the bug**
I opened the items for DMNS:Inv in the Collecting Event Change Lot email, then tried to open the SPECIMENS for that event and got this error message for everything I tried to open.  (BTW, who is "unknown" who made all these changes?  It doesn't look like anything actually changed.)

An error occurred while processing this page!
Message: The key [DAY] does not exist.
Detail:
Check the Arctos Handbook for more information on errors.
This message has been logged as D6878475-6CCF-4679-955461D483BE936E Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue.

Similarly, I tried to open the 11 specimens in the collecting event from the locality field within the specimen record https://arctos.database.museum/guid/DMNS:Inv:21079:

![Screen Shot 2020-08-01 at 2 18 09 PM](https://user-images.githubusercontent.com/15368365/89109825-e6c5cd00-d401-11ea-92af-82301d9a7f6b.png)

and got a similar message:

![Screen Shot 2020-08-01 at 2 19 37 PM](https://user-images.githubusercontent.com/15368365/89109845-09f07c80-d402-11ea-8eb5-a139e819e714.png)

I'm able to get the specimens from within the locality, so it seems to be limited to the collecting event link.

Mac
Safari

**Comment by sharpphyl** [comment]
These are related, I think.  Today I could not open the Collecting Event Change Log.  This is the error message:

> An error occurred while processing this page!
> Message: cannot cast [1 0671941] string to a number value
> Detail:
> Check the Arctos Handbook for more information on errors.
> This message has been logged as B879B457-628C-4BAD-8C385760143DDA1A Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue.

Again today, there are a large number of changes by "unknown"  but today I can't see them.

**Comment by Jegelewicz** [comment]
I also had issues - some of these I could get to and some I could not (MSB:Mamm). It looks like "unknown" just merged matching localities - this should be designated with something other than "unknown". The notification is pretty scary when hundreds of you event have been changed by "unknown" and then you cannot view them.

**Comment by dustymc** [comment]
All fixed for next release.
