### ISSUE TITLE
Format of determination date in locality attribute

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2992]
The determination date in locality attribute is presenting with time format too.

![image](https://user-images.githubusercontent.com/5725767/89191941-dd06ab80-d560-11ea-9a61-ae422dde3cc1.png)

Can we set it so that if no time is given, only the date shows?

**Comment by dustymc** [comment]
link?

**Comment by Jegelewicz** [comment]
https://arctos.database.museum/guid/ALMNH:ES:109

**Comment by dustymc** [comment]
Thanks - old geology dates came across a little weird, they're cleaned and controlled.
