### ISSUE TITLE
> Mississippian and Pennsylvanian should move to the system/period table

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2995]
> Mississippian and Pennsylvanian themselves are subsystems of the Carboniferous, I think we should move them over to the system/period table.

This will be a pretty big undertaking - lots of localities use them currently. Is it worth it, or can we just leave them where they are?

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/arctos/issues/2989#issuecomment-668124817_

**Comment by Jegelewicz** [comment]
> It doesn't need to be done immediately, but yes we need to plan to move them. Especially in the USA Mississippian and Pennsylvanian are used as System/Period rather than using Carboniferous. Putting them in with Series is just incorrect.

**Comment by Jegelewicz** [comment]
Anyone else have an opinion? @dperriguey @aklompma @mbprondzinski @acdoll can you check with Madagascar peeps?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
@dustymc @Jegelewicz will completing #2244 make this more difficult, if so, should we take care of this now?

**Comment by dustymc** [comment]
No, #2244 will just ignore any mismatched data - removing a term from the CT should not melt anything, and metadata can be added to  new terms, wherever they come from.

If this is decided, you can just add the terms, let me know, I'll mass-update, then you can remove the now-unused "old" terms.

**Comment by Jegelewicz** [comment]
@Nicole-Ridgwell-NMMNHS do we still need to do this?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Yes, this still needs to be done. Thank you for bringing it back to my attention.

**Comment by aklompma** [comment]
Well, they seem to fall more under series/epochs than under periods in the official international timescale:
https://stratigraphy.org/ICSchart/ChronostratChart2021-10.pdf
I would leave them where they are now.

**Comment by Jegelewicz** [comment]
That does seem to be true - hierarchy as follows:

Eonothem/Eon - Phanerozoic
Eratherm/Era - Paleozoic
System/Period - Carboniferous
Series/Epoch - Pennsylvanian (when more detail is unknown), Upper Pennsylvanian, Middle Pennsylvanian, Lower Pennsylvanian,  Mississippian (when more detail is unknown), Upper Mississippian, Middle Mississippian, Lower Mississippian

![image](https://user-images.githubusercontent.com/5725767/144451274-1128517d-47bf-4d3c-b412-f2c33f8a9e54.png)

Can we close this then?

**Comment by aklompma** [comment]
Correct, so they are no true periods either. Imo, Pennsylvanian and Mississippian are much more informative as series/epochs in Arctos instead of having epochs like lower Pennsylvanian, middle Mississippian, etc. because each of these epochs has a more meaningful, equivalent name as a stage/age, which is not true for the rest of the geological time scale. 
Besides, as European data gets entered, having Pennsylvanian and Mississippian as periods would become messy.

**Comment by Jegelewicz** [comment]
Right now we have all of these terms in the Seris/Epoch table:

Pennsylvanian (when more detail is unknown), Upper Pennsylvanian, Middle Pennsylvanian, Lower Pennsylvanian, Mississippian (when more detail is unknown), Upper Mississippian, Middle Mississippian, Lower Mississippian

Which provides flexibility, but may impede discovery?

**Comment by aklompma** [comment]
I would keep it as is or remove Upper Pennsylvanian, Middle Pennsylvanian, Lower Pennsylvanian, Upper Mississippian, Middle Mississippian, Lower Mississippian. Probably would go for the 1st option.

**Comment by Jegelewicz** [comment]
So actually a search of Series Epoch = Mississippian also brings up the record that is using "Upper Mississippian", so I think it is fine to have it both ways.

https://arctos.database.museum/guid/ALMNH:Paleo:5395

I'm gonna close this.
