### ISSUE TITLE
Bulkload Error bug "This attribute cannot have units" showing up when no data in units

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#2996]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
The bulkloader won't load my records because it thinks I have units in a behavior attribute but there's no data in it.

**To Reproduce**
1) Created clones of previous record to split lot
2) modified record accordingly
See: https://arctos.database.museum/DataEntry.cfm?action=edit&ImAGod=yes&collection_object_id=278210769
Load record 
> creates error "This attribute cannot have units"
Because it thinks I have data in the units of attribute 1??
It only works if I copy everything into attribute 2
**Expected behavior**
To load records without error

**Screenshots**
![image](https://user-images.githubusercontent.com/38706617/89268716-2523dd80-d5f6-11ea-99bf-2977ce363762.png)
![image](https://user-images.githubusercontent.com/38706617/89268766-34a32680-d5f6-11ea-8098-bfd46485671e.png)

** Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**
 using Chrome browser on Windows

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
I did

```
update bulkloader set attribute_units_1=null where attribute_units_1='';
UPDATE 37

```

and they should load now. Looks like the clone process is inserting '' instead of NULL. (Oracle didn't care, PG does.)

https://github.com/ArctosDB/arctos/issues/2802 should address the cause.

**Comment by mvzhuang** [comment]
Thanks Dusty!
