### ISSUE TITLE
Error when searching for Loan number at catalog record search

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#2997]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I attempted to search for catalog records included in a loan (Loan number 2020-20.EH) and received an error message.

**To Reproduce**
1. Go to 'catalog record search': https://arctos.database.museum/SpecimenSearch.cfm
2. Enter "2020-20.EH" in 'Loan number' field at Curatorial pane.
3. See error

**Expected behavior**
All catalog records included in the loan should be displayed.

**Screenshots**
<img width="1226" alt="Screen Shot 2020-08-04 at 8 09 22 AM" src="https://user-images.githubusercontent.com/17605945/89317624-1820e180-d62a-11ea-97b5-c34a3fd57491.png">

**Desktop (please complete the following information):**
 - Mac OS 10.14.6
 - Firefox
 - Version 79

**Comment by Jegelewicz** [comment]
@AJLinn does this work when you search for the loan in [Loan Search](https://arctos.database.museum/Loan.cfm?Action=addItems)?

**Comment by dustymc** [comment]
patched

**Comment by AJLinn** [comment]
> @AJLinn does this work when you search for the loan in Loan Search? The select the records to see the results..


yes - that's how I'm able to create the archived search results
