### ISSUE TITLE
New other identifier -- Alaska's Digital Archives

### ISSUE THREAD

**Issue by krgomez** [ArctosDB/arctos#2998]
**Goal**
Describe what you're trying to accomplish.
We would like to add links to occurrences of collection objects in Alaska’s Digital Archives. @AJLinn do you have thoughts on this?

**Context**
Describe why this new value is necessary and existing values are not.
Not sure of any other way of linking to these urls other than by an “other identifier”. 

I’m assuming that we would then use the “same individual as” relationship to link to the Alaska’s Digital Archives url for the object. One issue I see with this is that red box that appears around those relationships. It draws quite a lot of attention to that link on the catalog record, and for something like this, which would simply be linking out to another useful and relevant resource for researchers, that red box seems a little much.

In trying to get an idea of how links are working in Arctos, I was looking at some records in scientific collections and have noticed that sometimes there are links in the “links” box (GBIF, iDigBio), sometimes there are links in the “identifiers” box (BioSample), and sometimes there are links are in the “relationships” box, creating that red outline around the box. I’m a bit confused about the different ways these external and internal links are working and what would work best for what we’re trying to do. If I am missing something important about this, please let me know!

**Table**
Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm
coll_other_id_type

**Value**
Proposed new value
Alaska’s Digital Archives

**Definition**
Clear, complete, non-collection-type-specific definition of the new value.
Alaska's Digital Archives presents a wealth of historical photographs, albums, oral histories, moving images, maps, documents, physical objects, and other materials from libraries, museums and archives throughout our state. Its purpose is to provide a single easy to use location for institutions across this state to share their historical resources.

**Other ID BaseURL**
For OtherIDs, URL with which to prepend value (resolvable identifiers only)
https://vilda.alaska.edu/digital/collection/cdmg3/id/

**Priority**
Please assign a priority-label.
normal

**Comment by AJLinn** [comment]
I access vilda records by linking the media URL.

See for example: https://arctos.database.museum/guid/UAM:EH:UA91-014-0001
In particular: https://arctos.database.museum/media/10498124
Doing it this way we redirect to the vilda site rather than just seeing the image in arctos, because the records at Vilda are "stagant copies" of our collections records and shouldn't be considered a "real" database.

**Comment by dustymc** [comment]
>GBIF, iDigBio

Those are automagically generated from shared data

>identifiers

Those are identifiers with a references of "self"

>relationships

Those are identifiers with a relationship of not-self.

>red outline

That's just a "you may not be seeing all of what you want" flag.

>media

Agreed, seems most appropriate for this.

**Comment by krgomez** [comment]
Okay, so there is no real need or benefit to linking over to the Vilda "stagnant copies"? For example, Vilda's record for that parka: https://vilda.alaska.edu/digital/collection/cdmg3/id/796/rec/9 I wasn't sure if this would be helpful in some way to link over to the collection objects that are recorded in Vilda. If it's not worth doing, then I can just close this issue.

**Comment by AJLinn** [comment]
> I wasn't sure if this would be helpful in some way to link over to the collection objects that are recorded in Vilda.

Those records are/were created thru data we sent the managers of Vilda. We could certainly link to those records in arctos but I'm more concerned about getting the managers of vilda to link to Arctos! I've talked with folks at UAA who are managing it now, and it's not clear if they're willing to do that. There should be no additional info at vilda than what folks are getting at arctos, and in fact, there's usually a lot of info missing. I think our efforts would be better used in convincing vilda to create a live link to our Arctos records.

**Comment by krgomez** [comment]
Ah, okay. I'll leave it be then and close the issue. Thanks!

**Comment by AJLinn** [comment]
I'll reach out to Arlene Schmuland at UAA to see if we can get going on the links to arctos! Hopefully that will help folks who find our collections there get over to the actual records!
