### ISSUE TITLE
search by identification remarks not working

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#3001]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
search on "ID Remarks" is not working and throwing error

**To Reproduce**
Go to main search page
search under ID Remarks. I used "paratype"
![image](https://user-images.githubusercontent.com/38706617/89371270-23aeef80-d6a0-11ea-887a-30b646faf5bb.png)

**Expected behavior**
show results 

**Screenshots**

** Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**
microsoft; chrome

**Additional context**
The search will work if you search in the results table search filters instead of the home page

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
fixed in next release
