### ISSUE TITLE
How do I add a record to a particular event?

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/arctos#3003]
I am trying to add another record Catalog #134 to the Locality Nickname: ALMNH:ES:F-7 

I can't figure out how to get it to accept it.  Right now it's a separate event.

Thanks.

**Comment by campmlc** [comment]
Happy to help- zoom before or after issues meeting tomorrow?

**Comment by mbprondzinski** [comment]
How about before?  How much time will we need?  Thanks, Mariel.
________________________________

**Comment by campmlc** [comment]
Hi MB, are you free for zoom now?

**Comment by Jegelewicz** [comment]
Did you guys work this out?

**Comment by campmlc** [comment]
Yep, believe so. MB?

**Comment by mbprondzinski** [comment]
Yes, we did!  Thanks, everyone.
________________________________
