### ISSUE TITLE
Old Names and Acronyms for Collections

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#3004]
Some collections have changed their names over their history. An example is the UWYMV first started out by using the acronym UW, then the University of Wyoming Vertebrate Museum, and then finally the University of Wyoming Museum of Vertebrates (UWYMV). 

The old names pop up in historical publications and tags. 

Is there a place we could record these old names on Arctos in association with each collection? Something similar to the AKA name feature we have for agents?

**Comment by dustymc** [comment]
>similar ... agents

Make an agent with some AKAs?

**Comment by ewommack** [comment]
I've tossed this onto the issue's meeting, because I think it might need more discussion (mostly because I'm not sure exactly of all of the ramifications and way this may affect collections).

Maybe having agents of each collection would work, but is that where we go to find info about collections?

**Comment by dustymc** [comment]
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_contact_role could serve as the link - just need a new term.

Agents would also allow you to make collection --> https://arctos.database.museum/info/ctDocumentation.cfm?table=ctagent_relationship&field=division%20of --> institution and etc.

**Comment by Jegelewicz** [comment]
> https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_contact_role could serve as the link - just need a new term.

collection agent - Agent that describes the collection.

**Comment by dustymc** [comment]
https://arctos.database.museum/agent/21334497 (and similar for most/all collections) exists, closing.

**Comment by Jegelewicz** [comment]
@ewommack I suggest adding the old identifiers in manage collection

![image](https://user-images.githubusercontent.com/5725767/154370406-cb4e2f68-0f0d-4426-82ed-470e894fd0e9.png)

**Comment by ewommack** [comment]
I added the info there for our collections. We'll see how that goes.
