### ISSUE TITLE
MSB Mamm Loan Header report

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3006]
Can we please get the following legacy report transferred over to the new report system and fixed so it will print properly?
https://arctos.database.museum/Reports/MSBMammLoanInvoice.cfm?transaction_id=21125842

**Comment by dustymc** [comment]
You can just modify a report - there's an msb para loan form that looks pretty close. Let me know when you've got that working and I'll pull the cfm and the links to it.

**Comment by amgunderson** [comment]
UAM Mammal box labels, vial labels, and loan invoice need the same. uam_mamm_box, uam_mamm_loan_head, uam_mamm_vial

**Comment by dustymc** [comment]
@amgunderson those are in the reporter system, the SQL just needs adjusted for PG. There are recipes in https://github.com/ArctosDB/arctos/issues/2729; I might get them before you can....

**Comment by campmlc** [comment]
If you can get these fixed first, that would be super helpful. I'm not able
to spend the couple hours I'd need to remember how to deal with these
templates right now. Needing to get a loan out asap and just need the
header to work.

**Comment by dustymc** [comment]
@campmlc that does work, at least for me, but it's not sustainable like that and does need converted. PDF from your link attached.

[MSBMammLoanInvoice-2.pdf](https://github.com/ArctosDB/arctos/files/5059297/MSBMammLoanInvoice-2.pdf)

**Comment by campmlc** [comment]
That report doesn't format correctly - it is too old, and I have no idea how to fix it. The links to the handbook documentation are broken. It is going to take me several hours to try to remember what exactly to do here, as I haven't looked at SQL  or reports in over a year, and #2729;  is like reading a foreign language. Any chance someone can give me a hand with fixing the MSB Mamm Loan Header? @jldunnum and I need this asap.

**Comment by campmlc** [comment]
I tried to copy the MSB:Para Loan Header handler, but I have no idea what to do next.

**Comment by campmlc** [comment]
On a similar note, the MSB:Mamm Loan Invoice form is not pulling specimen locality data into the invoice. What is the fix here? 
This is actively impeding progress on loans.
[MSB_Mamm_loan_invoice_missing_locality.pdf](https://github.com/ArctosDB/arctos/files/5099670/MSB_Mamm_loan_invoice_missing_locality.pdf)

**Comment by dustymc** [comment]
https://handbook.arctosdb.org/how_to/How-to-Create-Labels.html

I edited the sql for MSB_Mamm_loan_invoice and added that to the cookbook in https://github.com/ArctosDB/arctos/issues/2729

**Comment by Jegelewicz** [comment]
> The links to the handbook documentation are broken.

Links from where? They all work for me from the long list of How To's in the Handbook. If I know where you are trying to open them from maybe I can fix it.

**Comment by campmlc** [comment]
Tried invoice again, got this?
[Error Occurred While Processing Request.pdf](https://github.com/ArctosDB/arctos/files/5099774/Error.Occurred.While.Processing.Request.pdf)

**Comment by campmlc** [comment]
I tried again with different report - invoice is working. Thanks!! Now we just have to figure out how to update the 14 year old pdf.

**Comment by campmlc** [comment]
Tried to create the MSB_Mamm_Loan_Header_1.  Downloaded report from MSB_para_loan_header.cfr.  Edited in Cold Fusion, copied handler format from MSB_para_loan_header.cfr.  Tried with a loan - got this:
![Screenshot 2020-08-26 16 48 58](https://user-images.githubusercontent.com/14808196/91364589-55593900-e7bc-11ea-8467-9ce3786e0681.png)

**Comment by dustymc** [comment]
the pre-function is get_loan not get loan, and it's not going to work with stuff in the SQL box. I changed that and it prints.

**Comment by campmlc** [comment]
One more edit please: 
I can't figure out why the description box keeps adding in "<strong>Nature of Material:</strong> "  in the actual printed text. CFR report attached.

[MSB_Mamm_loan_header_1.zip](https://github.com/ArctosDB/arctos/files/5211677/MSB_Mamm_loan_header_1.zip)

**Comment by campmlc** [comment]
Correction, since copy paste didn't work above: the report is adding in the words <strong>Description:</strong> at the start of the Description field - these are part of the cfr file, but they should not appear in the actual text of the report.

**Comment by campmlc** [comment]
Grrr - obviously github thinks what I am pasting is code for bold. Let me try to paraphrase:  string starting with <strong>.... keeps showing up.

**Comment by campmlc** [comment]
the word is strong enclosed in lesser and greater than symbols

**Comment by campmlc** [comment]
See problem here:
[2020.001.MSB_Para_loan_header.zip](https://github.com/ArctosDB/arctos/files/5211750/2020.001.MSB_Para_loan_header.zip)

**Comment by campmlc** [comment]
This problems still needs to be resolved - any ideas why the SQL is printing in the report?

**Comment by dustymc** [comment]
there's probably a 'process as html' property (might be labeled cryptically) in the report builder, or perhaps you're feeding it eg ``&lt;`` (or some unicode character or something) rather than ``<``

**Comment by campmlc** [comment]
None of that makes any sense to me, and I don't know how to fix the sql.
Can you please just fix it?

**Comment by dustymc** [comment]
It's not a SQL problem, it's in the CFR. I don't have a machine that can run the report builder.

**Comment by campmlc** [comment]
OK, that helps. I'll look over the cfr.

**Comment by Jegelewicz** [comment]
@campmlc what do you need from this issue?

**Comment by campmlc** [comment]
I think we can close this since all these reports are no longer valid. But I do need help with modifying [#5245](https://github.com/ArctosDB/arctos/issues/5245) to be used by other MSB Divisions besides mammals?

**Comment by Jegelewicz** [comment]
OK - I can work on that. Closing this.
