### ISSUE TITLE
Can't find user - need to invite as operator

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#3008]
**Describe the bug**
I'm trying to add one of our curators as an operator. They gave me their username, but when I go to Manage Arctos > Roles/Permissions > Arctos Users and type in the username I get no results. He has double checked the username and confirmed he can login with the username.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 79.0

**Additional context**
I'm new to adding operators, but I was able to add our other two curators just fine. I'm not sure if I'm doing something wrong, the curator is doing something wrong (but like I said, he said he can login with the username), or if this is actually some kind of bug.

**Comment by dustymc** [comment]
What's the username?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
abqtom

**Comment by dustymc** [comment]
Nothing like that exists in test or production.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks - maybe he is logging into the wrong thing? I'll check back with him.

**Comment by campmlc** [comment]
You can create it for him and use your email while you set up his account.
That way you can just hand it to him when it is done, and change the email
to the correct one.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I'll probably do that, I really curious now though what he is logging into.
