### ISSUE TITLE
agent address not picking from loan shipment

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#3011]
I tried creating a shipment for a loan, but the agent address wasn't in Arctos. I clicked on "Edit/Add Address" which took me to agents, and I added the address which is now saved. But when I click on "Use this address" from the shipment, nothing happens. It works fine when I select my address as the shipper, and it worked fine today for other addresses that were already entered in Agents.

**Comment by ccicero** [comment]
I put this as high priority because I can't create the loan invoice without the address.

**Comment by ccicero** [comment]
@dustymc What other information do you need? Here are the steps:
1) created a new loan
2) started to create a new shipment
3) recipient's address was not in Arctos
4) from the shipment agent adress picker, clicked on 'Edit/Add Address' 
5) added the address in Agents table
6) went back to loan, tried to select address for the shipment
7) nothing happens, does not populate the address field

---> can't complete/save the shipment or create the loan invoice

**Comment by dustymc** [comment]
Which loan and address?

**Comment by ccicero** [comment]
loan 2020.9004.Egg

Robert Montgomerie (21275355: edit/add address)
shipping (valid) [ use this address ]

Dr. Robert Montgomerie
Department of Biology
Queen's University
Kingston, Ontario
Canada

**Comment by dustymc** [comment]
Thanks. I'll have a fix in the next release, as a workaround you could replace the single quote with  ``′`` or something of the sort

**Comment by ccicero** [comment]
yep, apostrophe in address was the problem. I just removed it for now. thanks.
