### ISSUE TITLE
Can we get Loan dropdown box in Loan Search made larger?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3012]
Problem:
Go to Find Loan https://arctos.database.museum/Loan.cfm?Action=addItems
Go to Find Loan Collection dropdown
Notice it is very tiny and only allows 3 collections to be visible at one time.
The scroll bar is very limited in range and scrolls too quickly past multiple choices.

Solution:
Enlarge dropdown to allow more collections to be visible and to enlarge the scroll bar.
Use template for Create Loan as an example: https://arctos.database.museum/Loan.cfm?Action=newLoan

**Comment by dustymc** [comment]
> very tiny

How big do you want it?

That's a different kind of object - search supports multiple collections, create is single.

**Comment by campmlc** [comment]
The same size as the box I see in Create Loan.

**Comment by dustymc** [comment]
You asked for the multiple!

https://github.com/ArctosDB/arctos/issues/2518

??????????????????????????????????????

**Comment by campmlc** [comment]
Is that a different form? Can't they all be the same size to allow viewing more than 3 collections at a time? No dropdown should be as small as what currently exists in Search Loan.

**Comment by campmlc** [comment]
We need the same drop-down in both forms for operators who have create loan  access and search loan access for multiple collections.

**Comment by dustymc** [comment]
I think this needs added to an agenda or something; it sounds to me like you're asking for conflicting things, and I can't quite figure out where the miscommunication is.

**Comment by campmlc** [comment]
This is really an extremely simple request. No underlying data changes,
just UI - not sure how I can explain it any better. Please see images I
enclosed on previous issue. I have access to multiple collections. When I
create a loan, I get a big scroll bar to see a lot of the collections I
have access to. When I try to find a loan, I get a tiny window and scroll
bar. I just need the pick collections window made bigger so I can use it on
my laptop!

**Comment by dustymc** [comment]
OK, maybe I get it.

I can do bigger, just let me know how big. It was "whatever your browser wants" I just set it to 10 (in test), which is huge on my screen but whatever.

I can't as easily make it the same as create, which is an entirely different sort of control that serves a different purpose (and your browser decides how big that one is).

**Comment by acdoll** [comment]
It does look a little funny when you don't have lots of collections like Mariel, but seems like it should help with her problem.
![image](https://user-images.githubusercontent.com/12507297/99859269-cf475700-2b4c-11eb-9ef4-983be54cd3be.png)

**Comment by campmlc** [comment]
Thank you!! Much better!
