### ISSUE TITLE
Loan invoice print report not working

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#3014]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Loan invoice reporter is not working and is throwing an error
**To Reproduce**
1) Under the edit loan screen, hit print report
2) From the drop down menu, select UTEP_Loan_invoice.cfr

**Expected behavior**
For the pdf link to open up and show a preview of the invoice paperwork

**Screenshots**
![image](https://user-images.githubusercontent.com/38706617/89919096-1752f700-dbb8-11ea-834f-c40e61adbefe.png)

** Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**
windows, browser

**Comment by dustymc** [comment]
merge --> https://github.com/ArctosDB/arctos/issues/2729

**Comment by dustymc** [comment]
@mvzhuang this is fixed and the recipe is in the linked issue

**Comment by mvzhuang** [comment]
Thank you!
