### ISSUE TITLE
query string argument of EXECUTE is null

### ISSUE THREAD

**Issue by phalacrocorax66** [ArctosDB/arctos#3015]
I am attempting to upload a bulkloader csv and when I uploaded it, there were errors returned that said "query string argument of EXECUTE is null" on some of the specimens when all of the columns look very similar. I believe this is an error with postgresql and not my document. I attached the error file below from arctos "bulkloader_stage-3" and the original file I'm trying to upload, "LinebyLine_Bulkloader_next50_removed". I converted both documents below into xlsx files, they were originally csv files.

1. Upload the LinebyLine_Bulkloader_next50_removed document into the Arctos Catalog Record Bulkloader
2. Click "Check and load these records"
3. Click "Download data with errors"
4. A file identical to the bulkloader_stage_3 file will be created
5. Look at the errors in the Loaded column which should say "query string argument of EXECUTE is null" for catalog numbers: 1668, 1669, 1675, and 1676.

![queryerror](https://user-images.githubusercontent.com/63082834/89935813-a287b900-dbc7-11ea-93cb-ace8578b418b.PNG)

**Data**
[LinebyLine_Bulkloader_next50_removed.xlsx](https://github.com/ArctosDB/arctos/files/5058781/LinebyLine_Bulkloader_next50_removed.xlsx)

[Copy of bulkloader_stage-3.xlsx](https://github.com/ArctosDB/arctos/files/5058763/Copy.of.bulkloader_stage-3.xlsx)

**Desktop:**
 - OS: 64 bit Windows 10
 - Browser: Firefox
 - Version 79.0

**Comment by dustymc** [comment]
CSV please - you can zip to attach.

**Comment by phalacrocorax66** [comment]
Here it is
[LinebyLine_Bulkloader_next50_removed.zip](https://github.com/ArctosDB/arctos/files/5059143/LinebyLine_Bulkloader_next50_removed.zip)

**Comment by dustymc** [comment]
Thanks, should be making better errors now. The attributes without units were confusing the checker.

**Comment by phalacrocorax66** [comment]
Oh thank you, I didn't realize I had missed any units.
