### ISSUE TITLE
batch unload citations from the placeholder type publication?

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#3017]
I added some paratype citations for specimens with "unknown type". Is there a way to batch remove specimens from the placeholder publication or do I have to remove it one by one?

**Comment by dustymc** [comment]
I don't think there is, but I believe we've agreed in principle that every loader should have a corresponding unloader. I'm flagging next task, just needs prioritized.

**Comment by dustymc** [comment]
blocked by https://github.com/ArctosDB/arctos/issues/2974
