### ISSUE TITLE
documentation request: TAXONOMY_SOURCE

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3019]
https://arctos.database.museum/info/ctDocumentation.cfm?table=CTTAXONOMY_SOURCE&field=Arctos needs better documentation.

ref: https://github.com/ArctosDB/arctos/issues/2687

**Comment by sharpphyl** [comment]
@dustymc 

Is this at all what you are looking for?  What else should be included?

https://drive.google.com/drive/folders/1gQdI-qWCDFAe6yJSkWkUKlXLAX5KYwLp

**Comment by Jegelewicz** [comment]
@Jegelewicz add this to Manage Collection documentation/video

**Comment by Jegelewicz** [comment]
I'm not sure what else we need here. Closing.
