### ISSUE TITLE
Arctos Users Email List

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3022]
Per AWG meeting 8-13-2020
Need to reconclie arctos google group list with mail chimp list
Find a way to add new members, subscribe/unsubscribe

**Comment by ewommack** [comment]
@dustymc 
This came back up in my to do list.
Here's what we discussed at the last meeting: 
How do we contact everyone in Arctos?
	First steps:
Lets work on comparing and figuring out the overlap between the old arctos@googlegroups.com group and the Mail Chimp Newsletter list.
Lets put this as the agenda for next month.
Work with Dusty and Lam to compare this list to the Arctos list.

How would you like me to send you the lists? I think I can download it as a .csv file.
Not sure who has control of the google groups, @mkoo?

**Comment by dustymc** [comment]
>How do we contact everyone in Arctos?

Put "join the github discussions or live with whatever comes out of them" in the MOUs?

Yes CSV should work - assuming all of those components will have an email address which can act as a link.

**Comment by Jegelewicz** [comment]
> Put "join the github discussions or live with whatever comes out of them" in the MOUs?

Dream on. But I think we should get close to something like that. Any other software would just be released and you would get what you get (Microsoft). I also want to discourage side discussions via email or any other place because that means we are going to miss things and/or people are going to be left out. If we have ONE place for discussion we will be better off. Newsletters and announcements about coming changes are fine via email/mailchimp/whatever, but discussion should happen here.

**Comment by dustymc** [comment]
>ONE place for discussion

Absolutely.

>announcements

Yes, those should be seen as courtesy/secondary/executive summaries.

**Comment by ewommack** [comment]
@dustymc 
Here is the mail chimp list.
[members_July_2020_Arctos_Newsletter_sent_Aug_31_2020.csv.zip](https://github.com/ArctosDB/arctos/files/5152757/members_July_2020_Arctos_Newsletter_sent_Aug_31_2020.csv.zip)

**Comment by dustymc** [comment]
@ewommack here's the code - I'll email you the list, it probably shouldn't be in a public repo

```
-- strip everything except email out of the CSV; can't deal with the weird column names
-- upload it
-- flush
drop table temp_arctos_users;
-- grab a copy of the upload
create table temp_arctos_users as select * from temp_cache.temp_dlm_uptbl ;
-- flag stuff that came in
alter table temp_arctos_users add in_original varchar;
update temp_arctos_users set in_original='yes';
-- arctos username column
alter table temp_arctos_users add username varchar;
-- some emails are apparently shared for some reason, so aggregate username, I guess....
update temp_arctos_users set username=(select string_agg(agent_name,';') from agent_name , address where agent_name.agent_id=address.agent_id and agent_name_type='login' and address_type='email' and address=email);
-- now get users that aren't in the original
insert into temp_arctos_users(username,in_original) (select agent_name,'no' from agent_name where agent_name_type='login' and agent_name not in (select username from temp_arctos_users where username is not null));
-- check account status
-- those with very old, pending, or never finalized accounts will end up NULL 
alter table temp_arctos_users add active varchar;
update temp_arctos_users set active=(select case when rolvaliduntil>current_date then 'yes' else 'no' end from pg_roles where rolname=lower(username));
-- see if we can get email for the ones we added
-- some have multiple so aggregate again
update temp_arctos_users set email=(select string_agg(address,'; ') from agent_name , address where agent_name.agent_id=address.agent_id and agent_name_type='login' and address_type='email' and agent_name.agent_name=temp_arctos_users.username);
-- clean up; blank lines in original
delete from temp_arctos_users where email is null and username is null;

```

**Comment by ewommack** [comment]
Thanks @dustymc!
I suppose the next step is to compare this to the google groups. 
We should probably do that off GitHub?
