### ISSUE TITLE
Edit accession error

### ISSUE THREAD

**Issue by krgomez** [ArctosDB/arctos#3023]
I was trying to view an accession record and got an error.

**To Reproduce**
1. Go to an Art catalog record (I have reproduced this error in every record I've tried today). 
2. Click edit accession.

**Expected behavior**
Never had this error before. Usually edit accession takes me to the accession record.

**Screenshots**
![Screen Shot 2020-08-13 at 10 56 33 AM](https://user-images.githubusercontent.com/40579515/90190383-5f664b00-dd6b-11ea-8507-f664f16c9fa8.png)

**Desktop (please complete the following information):**
 - MacOS Catalina 10.15.6
 - Firefox
 - 79.0

**Priority**
Please assign a priority-label.
normal

**Comment by dustymc** [comment]
I'll have a fix in the next release.
