### ISSUE TITLE
Encumbrance to Cite Funding Source / Grant # in Loan

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3024]
I have a request from curators to require loan recipients to cite NSF grants that contributed specimens used in a loan.  Right now, we don't consistently add NSF#s or other funding numbers to projects - there is no specific field in the project page for a grant number. Instead, we may or may not write the number in the text of the project, and it is not easily searchable. Any chance we can create a specific field for funding source/grant ID #?

To ensure that funding agencies can get acknowledged in loans, or at least, that we can request loan recipients to cite this information, it seems one potential solution would be to create a Restrict Usage encumbrance for projects that contribute specimens and require citation. That way the encumbrance would show up in the Review Loan Items form.  

I have tried to do this as a demo for the Beringian Coevolution Project. (BCP)] (https://arctos.database.museum/project/51). From the project page, I have selected the link for the 19,015 catalog records contributed [(](https://arctos.database.museum/SpecimenResults.cfm?project_id=51). From Catalog Record Results, I went to Manage and selected Encumbrances. And then nothing happens because I assume the system times out.  

Any way to fix this, please, so that I can add all these specimens to the encumbrance I created?

Also, suggestions and feedback on the idea of using encumbrances for funding source citations in loans would be appreciated.

**Comment by campmlc** [comment]
Finally got a 500 Internal Server Error on the Manage Encumbrances tool in Catalog Record Results. Ditto when I tried the 8000 records of CIIBA project.

**Comment by dustymc** [comment]
>there is no specific field in the project page for a grant number.

<img width="712" alt="Screen Shot 2020-08-16 at 10 57 21 AM" src="https://user-images.githubusercontent.com/5720791/90340753-4948cc80-dfaf-11ea-8a90-b293e94fb986.png">

>add all these specimens to the encumbrance 

That's probably best framed as a request for a bulkloader - I doubt we have the resources to make that perform in a UI.

>feedback

Use https://arctos.database.museum/info/ctDocumentation.cfm?table=ctloan_status&field=returned; there's already a "need more information" flag, I see no reason to find another way to do the same thing.

**Comment by dustymc** [comment]
See also https://github.com/ArctosDB/arctos/issues/1694 - there's a bigger-than-Arctos mechanism to track funding, we could do INSANELY cool things (like track long-term impacts of $$ spend on collecting and cataloging) if someone would just use it. Loan agreements requiring that would be a pretty good start.

**Comment by dustymc** [comment]
AWG meeting 20210304: add to loan forms 'magic award numbers from accn projects into loan_item_instructions' button

**Comment by campmlc** [comment]
See #3491

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/3491
