### ISSUE TITLE
Specimen event bulkloader throwing error after validation

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#3031]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I'm trying to upload a specimen event through the batch event loader and it is throwing an error even though I have validated everything.

**To Reproduce**
1) Batch specimen event bulkloader
2.) upload file
3. validate
4. proceed to load
5) See error
https://arctos.database.museum/tools/BulkloadSpecimenEvent.cfm?action=load

**Expected behavior**
load the specimen event.

**Screenshots**
![image](https://user-images.githubusercontent.com/38706617/90691816-380ef280-e231-11ea-9f0c-8f91bf01f36f.png)

[BulkloadSpecimenEvent.zip](https://github.com/ArctosDB/arctos/files/5099447/BulkloadSpecimenEvent.zip)

** Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**
Windows 
chrome

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by mvzhuang** [comment]
@dustymc just following up on this and checking I haven't missed anything obvious that isn't letting the bulkloader work?

**Comment by dustymc** [comment]
Patched in next release, which I hope to get out tonight.

**Comment by mvzhuang** [comment]
Thank you!

**Comment by mvzhuang** [comment]
@dustymc I'm still getting the same error. Are we still waiting on new release for this?

**Comment by dustymc** [comment]
Na, that was a slightly different error...

I stole one of your records and confirmed it works now - https://arctos.database.museum/guid/UTEP:Ento:18168 should have done whatever it was supposed to to.

**Comment by mvzhuang** [comment]
oh! ok great thanks!
