### ISSUE TITLE
Broken Links in Arctos Handbook

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3032]
**Describe the bug**
Links in the Arctos Handbook go nowhere, not actionable

**To Reproduce**
1. Go to "How to create and manage your Arctos Team"  and "How to Create Labels" in the handbook
2. Click on above
3. Nothing happens

**Expected behavior**
The links to the documentation should open

In Chrome on PC

High Priority unless someone can fix a report template for me and others - figuring this out without documentation is difficult.

**Comment by Jegelewicz** [comment]
Links FROM where?

**Comment by Jegelewicz** [comment]
This one works fine for me

![image](https://user-images.githubusercontent.com/5725767/90697177-09961500-e23b-11ea-8f09-61470596e9b9.png)

**Comment by Jegelewicz** [comment]
So does this one
![image](https://user-images.githubusercontent.com/5725767/90697253-35b19600-e23b-11ea-9d9a-ecdbc67994bc.png)

**Comment by campmlc** [comment]
From the Search results
[Arctos Handbook.pdf](https://github.com/ArctosDB/arctos/files/5099721/Arctos.Handbook.pdf)

**Comment by Jegelewicz** [comment]
Where is that? I don't think I have ever seen it?

**Comment by Jegelewicz** [comment]
OK, figured it out. I searched labels, got these results, then clicked right through to the how to...

![image](https://user-images.githubusercontent.com/5725767/90698090-229fc580-e23d-11ea-9476-3b3ffceab75f.png)

**Comment by Jegelewicz** [comment]
But weirdly, when I searched "reporter" as you did, I am unable to click the link. It's not broken, you just can't click it at all. @mkoo any idea why this would be?

![image](https://user-images.githubusercontent.com/5725767/90698229-76aaaa00-e23d-11ea-96d7-d38baa61df3c.png)

**Comment by campmlc** [comment]
https://handbook.arctosdb.org/
search

**Comment by campmlc** [comment]
[Arctos Handbook.pdf](https://github.com/ArctosDB/arctos/files/5099779/Arctos.Handbook.pdf)

**Comment by mkoo** [comment]
I'm checking it out-- but weird, does that page even exist?!

**Comment by mkoo** [comment]
ok not weird, just misconfigured header-- all fixed!

**Comment by campmlc** [comment]
Yay! I'm glad I'm not crazy or hallucinating or in some alternate Arctos
universe  . . . Thanks,@mkoo and @jegelewicz!
