### ISSUE TITLE
Error when openeing test

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3034]
http://test.arctos.database.museum/ took forever to load, then there was this at the bottom of the page:

An error occurred while processing this page!
Check the Arctos Handbook for more information on errors.

This message has been logged as 448B5825-ADF5-44A4-B155B7BDBEDD8C49 Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue. 

![image](https://user-images.githubusercontent.com/5725767/90782812-86b59e80-e2bc-11ea-9570-9911935eb61a.png)

**Comment by dustymc** [comment]
Try holdin' your lip JUST SO....

It's always a little slow on first load (https://github.com/ArctosDB/internal/issues/65 - I don't have DB access to do what fixed prod) but usually comes around. Looks like it was just a bit slower than normal this AM.

```
request /SpecimenSearch.cfm (/usr/local/webroot/SpecimenSearch.cfm) has run into a timeout (timeout: 60 seconds) and has been stopped. The thread did start 62277ms ago.
```
