### ISSUE TITLE
Need to Search and Download Attribute Remarks

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3039]
Problem: MSB has parasite data critical to the conversion of mammal parts to parasite cataloged items stored in part remarks and attribute remarks.
Currently Part Remarks is searchable, but can only be downloaded as JSON, which is difficult to manage in download for more than a single record at a time.  See #2963.
Attribute Remarks are neither searchable or downloadable. 

Request: Add Attribute Remarks to Search options. Include Attribute Remarks in the solution to #2963 to enable separating of these data into functional columns in a csv download.

Priority High because grant-funded projects hinge on access to these data.

**Comment by campmlc** [comment]
#2916

**Comment by krgomez** [comment]
Is there a way to download the remarks of a single attribute? I can only find the "attribute detail" option, which is not usable for my purposes. I know this issue came up for us in #2861 as well.

**Comment by krgomez** [comment]
Is there now a way to search/download attribute remarks? I don't see it as an option.

**Comment by AJLinn** [comment]
I think you have to customize your search options to have the attributes up for your search page and then you can see this:

<img width="1690" alt="Screenshot 2023-01-05 at 11 11 20 AM" src="https://user-images.githubusercontent.com/17605945/210871232-7ffbd354-9697-4a22-a85f-974ec9d3f4e7.png">

**Comment by dustymc** [comment]
... and then ....

<img width="408" alt="Screenshot 2023-01-05 at 12 14 33 PM" src="https://user-images.githubusercontent.com/5720791/210871770-df369a65-dd39-44dc-917d-5dcc3d185f88.png">

... will provide details.

**Comment by krgomez** [comment]
Awesome, thanks!
