### ISSUE TITLE
Lost Data from March Freezer Move 

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3041]
Problem: 
An entire ultralow freezer's worth of freezer boxes was moved in March between Cryotank 2 and Cryotank 5. All info on the move was lost during the crash. 
I have three people on hand to rescan the boxes into their actual positions.
However, none of the boxes will scan. 
Just for these boxes, from just this one former DGR12 freezer moved in March, I get the attached error. I also cannot scan any of these boxes into other freezer racks in other freezers, so it appears something about the freezer boxes themselves that are corrupted, but I see nothing wrong in Edit Container. I am able to scan other boxes into other freezer rack positions in the same cryotank, so the rack and box and tank positions themselves in the rest of the tank seem to be OK.  
![Screenshot 2020-08-20 11 54 42](https://user-images.githubusercontent.com/14808196/90812338-33a31200-e2e3-11ea-8cc7-1d582dd590da.png)

**Comment by campmlc** [comment]
Example rack with boxes in positions: Barcode DGRC2E94

All boxes need to be scanned into same positions in Barcode DGRC5E94

Ditto for all the rest: move all boxes from DGRCO2 from racks E94-H157 to equivalent positions in cryotank DGRC05.

**Comment by Jegelewicz** [comment]
It looks oddly like the 100 positions in the box rather than the box itself are being picked up?

**Comment by dustymc** [comment]
I moved DGR15177 into https://arctos.database.museum/containerPositions.cfm?container_id=20091997

I may have changed something looking at it though - there are some datatype misalignments that may or may not matter. If it's not fixed I need

- a link to the parent position 
- the barcode that you want scanned in

**Comment by campmlc** [comment]
Try the other one I submitted in previous post.

**Comment by campmlc** [comment]
All freezer boxes in positions in https://arctos.database.museum/containerPositions.cfm?container_id=18189823 need to be moved to the same positions in https://arctos.database.museum/EditContainer.cfm?container_id=20091944. And we need to do this for all racks and boxes from rack 94 (6 positions/boxes each) through rack 157 (6 positions/boxes each).

**Comment by dustymc** [comment]
I patched the datatype change in and moved one.

**Comment by campmlc** [comment]
Or, I need the boxes in all of the positions in all of these racks (I have no way to get all these barcodes in the current interface?)  to be fixed so that I can physically scan them into position.

**Comment by campmlc** [comment]
Cool, I'll go try.

**Comment by campmlc** [comment]
Yes, seems to be working! I'll close once the transfer is completely. Thanks!!
