### ISSUE TITLE
West Indies = Continent?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3043]
See https://github.com/ArctosDB/arctos/issues/1291#issuecomment-677929819

Also see [documentation](https://handbook.arctosdb.org/documentation/higher-geography.html#continent--ocean).

I think this needs to be fixed pretty quickly, but that's just my opinion.

![image](https://user-images.githubusercontent.com/5725767/90831962-087beb00-e302-11ea-8cb8-49fba89c9dc1.png)

**Comment by campmlc** [comment]
I agree with moving this to North America.

**Comment by dustymc** [comment]
>North America.

Can we keep greenland too? 

<img width="501" alt="Screen Shot 2020-08-20 at 8 22 53 PM" src="https://user-images.githubusercontent.com/5720791/90848993-1aba5100-e323-11ea-8880-70a390d5b54a.png">
<img width="706" alt="Screen Shot 2020-08-20 at 8 23 28 PM" src="https://user-images.githubusercontent.com/5720791/90849001-1ee66e80-e323-11ea-96a6-e2c1e1423c5f.png">

**Comment by tucotuco** [comment]
And Hawaii in North America? Really? From wikipedia, "Hawaii is a state of
the United States of America located in the Pacific Ocean. It is the only
U.S. state located outside North America,..."

**Comment by campmlc** [comment]
I thought we were going to trade Puerto Rico for Greenland .. .
https://en.wikipedia.org/wiki/West_Indies
https://en.wikipedia.org/wiki/Greenland

**Comment by dustymc** [comment]
Tabling - https://github.com/ArctosDB/arctos/issues/3272 would allow Arctos to standardize geography.
