### ISSUE TITLE
Anatomical Parts Ontology

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3044]
Putting this here for further discussion

https://www.ebi.ac.uk/ols/ontologies/uberon

**Comment by Jegelewicz** [comment]
Just came across this again in this article. [The challenges of digging data](https://www.academia.edu/14261366/The_challenges_of_digging_data?email_work_card=view-paper)

**Comment by campmlc** [comment]
This sounds promising.

**Comment by Jegelewicz** [comment]
@ArctosDB/arctos-code-table-administrators are going to review over the next month to see if this seems like something we could be using.

@dustymc your input would be greatly appreciated as well.

**Comment by tucotuco** [comment]
I would highly recommend it. Darwin Core is going to recommend that when the parts referred to are IRIs that they be from Uberon. The zooarchaeology people are already using it to publish material found.

**Comment by dustymc** [comment]
I'm all in - we've been looking for a better parts solution forever - but have some concerns.

First, how? Has anything like merging a big active ontology into a big active RDBMS been done before?

Second, is The Community actually willing to use it? We appear to have been regressing from the reasons people build ontologies (and RDBMSs) lately; if we can't agree to 

Really plugging into an ontology seems like it would take significant dedicated resources, but perhaps that's just ignorance 
speaking.

Triples (can ontologies be boiled down to triples?) seem much more approachable. 

Finding ANYTHING that covers the breadth of stuff in Arctos doesn't seem likely, and maintaining completely separate structures for arrowheads, teapots, and dead rats sounds like a nightmare, but perhaps if it's just triplets then merging (actually or via views or similar) could work

If we get past the techy bits, then I think there would be lots of translation required - quill==??==>https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0013495 - and my sense is that there would be a lot of resistance to that.

So big picture I think two questions:

1. Would this be accepted by the Arctos Community?
2. Is integrating an ontology (or something that we can pull from an ontology) technically plausible.

**Comment by dustymc** [comment]
I'm all in - we've been looking for a better parts solution forever - but have some concerns.

First, how? Has anything like merging a big active ontology into a big active RDBMS been done before?

Second, is The Community actually willing to use it? I think it's a significant commitment.

Third, can we maintain it? Eg I can't imaging having two part-things, and it's hard to see finding the resources to do whatever it takes to "bridge" the teacups and arrowheads ontologies in.

**Comment by campmlc** [comment]
If this can be implemented in Arctos, I for one am excited to use it. We
have been discussing for years the need to be able to search on all parts
related to a given anatomical feature. I presume this would make that
possible.

**Comment by dustymc** [comment]
You don't need to presume anything, there's a nice viewer linked above. If we are at all serious about this (and can get over the technical bits), then anyone who has the slightest interest in parts should spend at least a couple hours really looking at this, and should be fully prepared to trade "quill" for "barbed keratin-coated spine" and etc.

**Comment by Jegelewicz** [comment]
> First, how? Has anything like merging a big active ontology into a big active RDBMS been done before?

I think we should first consider using it to aid in search - see below.

> should be fully prepared to trade "quill" for "barbed keratin-coated spine" and etc.

unnecessary - search quill and you are asked, which kind? - https://www.ebi.ac.uk/ols/search?q=quill&ontology=uberon
This is the point of an ontology - relationships among the "preferred" names to synonyms means that searching one gets you the other.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
What will we do if a term is not in the ontology? For example, DNA comes up with no results when I search uberon?

**Comment by dustymc** [comment]
Only using the ontology in support of search is probably easier to implement, but would have limited utility.

If we're going to use it for assertions - eg if we're going to stop doing arbitrary things to data - then I believe we'd need to use the "preferred" terms.  "Quill" isn't necessarily unambiguous, "barbed keratin-coated spine" is.

>What will we do if a term is not in the ontology?

That's this:

>Third, can we maintain it? Eg I can't imaging having two part-things, and it's hard to see finding the resources to do whatever it takes to "bridge" the teacups and arrowheads ontologies in.

I don't know what we'd do there - ideally we'd be involved in the ontology community and add it there, less-ideally we could perhaps bridge to some DNA-having ontology, otherwise I suppose whatever the "whole organism" equivalent is plus a remark or something.

**Comment by Jegelewicz** [comment]
This is a vertebrate anatomy ontology, so I wouldn't expect DNA to be there.

This would not BE our part name list, but would allow for the kind of searching we have been discussing with quill/hair and phalanx/foot. DNA would still be a valid part name which might end up appearing in some other ontology. There are lots of them. https://www.ebi.ac.uk/ols/ontologies

**Comment by Jegelewicz** [comment]
This one seems interesting too - https://www.ebi.ac.uk/ols/ontologies/bco

**Comment by dustymc** [comment]
>This would not BE our part name list,

That deserves more than summary rejection. 

Using the ontology to aid search would, under arbitrary circumstances (eg when we've accidentally said something that leads to what we should have said), allow you to find things in Arctos. Neat.

Using the ontology as a "code table" would allow you to fully and unambiguously communicate with anything else that's using the ontology. Revolutionary.

**Comment by Jegelewicz** [comment]
> Using the ontology as a "code table" would allow you to fully and unambiguously communicate with anything else that's using the ontology. Revolutionary.

Agree, but we have more than just anatomical "parts". If we can accommodate both and people can be happy with "barbed keratin-coated spine", then that would be great and I am 100% on board!

**Comment by dustymc** [comment]
>we can accommodate both 

https://link.springer.com/article/10.1007/BF02831652

That might still lead to us building bridges or even ontologies and then bridges to them, but as far as I know it's not a technical barrier.

**Comment by Jegelewicz** [comment]
HEHEHE - I'm not paying $40 to read it, but I kinda get the gist.

Really tho, we could call our parts anything we want, we would just need a new column in the part names table that relates to the appropriate thing in the ontology. For a lot of stuff the two names would be exactly the same and we could potentially have two part names that relate to the same thing in the ontology (which would facilitate search). Something like that?

**Comment by tucotuco** [comment]
There is nothing to stop you from building an ontology for your own
purposes that imports one or more other ontologies. The imported parts you
don't have to maintain, but if you had something to add that belonged in
one of those, you'd want to participate in that ontology's development
rather than just add your exceptions in the for-your-purpose ontology that
imports the others.

**Comment by Jegelewicz** [comment]
I hear you, but that means someone has to participate in another voluntary job - we are struggling with that right now... :-(

**Comment by dustymc** [comment]
>we would just need a new column in the part names table that relates to the appropriate thing in the ontology.

That's still limited scope - nobody without our "translator" can tell what we're trying to say, and absolutely nobody is going to realize that "we're using an ontology" means "we're not actually _using_ an ontology, so you also need a bunch more complexity that doesn't fit into any Standard or expected toolset if you hope to understand our data semantically."

>have two part names that relate to the same thing in the ontology

There's a word for that - starts with "de" and ends with "normalization" but I can't remember what's in the middle....

So the first step is obviously in deciding what we're trying to do here. Are we trying to join a bigger world and fluently talk to cool new kinds of data in previously unlinked communities, or do something potentially-moderately-neat but very, very local?

>has to participate in another voluntary job

I'm not sure that's reasonable. I think this (going all-in, anyway) will in fact be something like a job. It would also completely change the nature of our data, and therefore our position in "the community." There's little question that we - and perhaps uniquely we - can pull it off (if anyone can), given sufficient resources. That seems like something that someone would be very willing to support.

**Comment by tucotuco** [comment]
And, would it actually be more work than what you would propose otherwise?
Or that you do now?

**Comment by Jegelewicz** [comment]
> nobody without our "translator" can tell what we're trying to say

When passing things out - we could pass the ontology term, not "our" term, like DwC files

> And, would it actually be more work than what you would propose otherwise?
> Or that you do now?

Participation in another community - getting "our" terms into another resource will indeed be more work. We have enough trouble among ourselves deciding what "normalized" terms should be. Which is evidenced by our current lack of normalization (MVZ uses tissue with liver in remarks, MSB uses liver). It does deserve a position, even now, but we haven't figured out how to pay anyone so far. Making any community work requires organizers.

**Comment by dustymc** [comment]
> more work 

Yes, almost certainly. We'd get better data, not less work.

>we could pass the ontology term, not "our" term

That would require a 1:1 mapping, at which point we'd greatly simplify our lives by just using the ontology.

Or I suppose a 0-or-1:1 - we'd just not share anything that's ambiguous - but that's probably MOST of the work for limited benefit.

>Making any community work requires organizers.

Yes, and implementers. So maybe that's the place to start - does that community exist, and do they want us to be a part of them, and can we work together to figure out how to pay for it?
