### ISSUE TITLE
Authentication failed after unlock account

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3048]
From operator:
Great, thanks! I received the account unlock email, but using the one-time password still gave this error:  "Authentication failed. Additional Information: authentication failed"

**Comment by dustymc** [comment]
That error comes from no coldfusion_user access.

I can't say anything specific without details.

The "wrong password" thing has turned out to be various types of form-fillers being "helpful" in the past.

**Comment by mkoo** [comment]
ok so we'll add that permission and see if it works now -thx!

**Comment by ebraker** [comment]
We are also getting this error for a student user with coldfusion access

ganderegg

**Comment by dustymc** [comment]
@ebraker can you elaborate?

Nevermind you did - "not receiving a pw recovery email" is, as far as I can determine, usually due to routing somewhere along the way, or sometimes things like spam filters. I can pretend to be them and try a recovery if you want?

**Comment by ebraker** [comment]
that would be great, thanks

**Comment by dustymc** [comment]
I did...

<img width="548" alt="Screen Shot 2020-08-25 at 1 41 56 PM" src="https://user-images.githubusercontent.com/5720791/91225795-071f3980-e6d9-11ea-9d44-15409cb75287.png">

then popped open a private tab and...


<img width="270" alt="Screen Shot 2020-08-25 at 1 42 34 PM" src="https://user-images.githubusercontent.com/5720791/91225832-10100b00-e6d9-11ea-9190-39f911025a65.png">

The email took 2 seconds to get delivered - happy to forward you the headers if that's helpful.

change worked fine

<img width="715" alt="Screen Shot 2020-08-25 at 1 43 37 PM" src="https://user-images.githubusercontent.com/5720791/91225870-1bfbcd00-e6d9-11ea-8d64-febf8efd8b61.png">

<img width="533" alt="Screen Shot 2020-08-25 at 1 43 43 PM" src="https://user-images.githubusercontent.com/5720791/91226179-86ad0880-e6d9-11ea-8715-44653d1dadfc.png">

and I'm in and everything's happy.

I'll email you the new PWD.

I'm not sure what could be going on!

**Comment by ebraker** [comment]
Ok thanks!!!

**Comment by ebraker** [comment]
All resolved here at UCM. Thanks!
