### ISSUE TITLE
Bulkload specimen remarks; associated species

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#3049]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
I need to move something from specific locality to specimen remarks/associated species (Tococa, which is a plant) for 14 specimens. I can take it out of locality because of our locality model, but no way to add it to specimen remarks in bulk. (collector wrote 'Tococa, French Guiana" in verbatim locality and I thought it was a city.   

** Describe what you're trying to accomplish** 
Batch load associated species and things in specimen remarks for some specimens

**Describe the solution you'd like**
create a batchloader for this.

**Describe alternatives you've considered**
Create obs record; but dont' know if these are all from the same Tococa plant or not.

**Additional context**
https://arctos.database.museum/guid/UTEP:Ento:1188

**Priority**
Please assign a priority-label.

**Comment by Jegelewicz** [comment]
> Create obs record; but dont' know if these are all from the same Tococa plant or not.

This would be the most powerful method. The Tococa plant observation should just share a collecting even with the ant, so you aren't necessarily saying it's all the same plant unless they were all collected in the exact same place at the exact same time. Make sense? I would prefer this for biotic interaction details and to let plant people have more data.

> Batch load associated species and things in specimen remarks for some specimens

Really, the next-best thing would be to put Tococa in the "associated species" field in the collecting event. If all 14 share an event, that's easy-peasy. If not, you could just add a second event (using the event loader) that is a clone of the first except with Tococa in associated species.

I would put Tococa in specimen remarks as a last and poorest option for discoverability of interactions.

Let me know if I can help!

**Comment by Jegelewicz** [comment]
@dustymc why don't I see associated species in the collecting event when I go to edit it?

![image](https://user-images.githubusercontent.com/5725767/91052129-44eb6780-e5de-11ea-86f9-275428cdd4bc.png)

![image](https://user-images.githubusercontent.com/5725767/91052180-53d21a00-e5de-11ea-9a3d-543c92265383.png)

but here it's in the bulkloader builder

![image](https://user-images.githubusercontent.com/5725767/91052248-6e0bf800-e5de-11ea-84a6-b9f9cf64adc8.png)

**Comment by Jegelewicz** [comment]
> Something similar in https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_event_attr_type would make more sense to me, and there's a loader if that works.

Agree  - and wish list that you could choose from the taxon names table to select species....

See also 
https://github.com/ArctosDB/arctos/issues/2443
https://github.com/ArctosDB/arctos/issues/2597

**Comment by campmlc** [comment]
Any reason not to create an observation record for the plant, and link via
relationships? That way the plant is searchable via higher taxonomic
categories.

**Comment by Jegelewicz** [comment]
See https://github.com/ArctosDB/arctos/issues/3049#issuecomment-679135750

**Comment by mvzhuang** [comment]
?got it. will do!

________________________________
