### ISSUE TITLE
Object Tracking Sort Problems

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3050]
Any way to have the option of choosing a sort method for object tracking? 
I need at a minimum to have the display sort in order by alphanumeric barcode. Even better would be to be able to choose to sort in alphanumeric order by Barcode or by Label.  I'm not really sure what the order of sort is now, but it appears random. With 157 racks per freezer, and 6 boxes per rack, random order is not very helpful.
?

**Comment by campmlc** [comment]
Maybe not entirely random - racks are sorting in reverse numeric order?
See Barcodes DGRC4F124 and DGRC4F125

**Comment by dustymc** [comment]
Looks alphanumeric to me??

<img width="406" alt="Screen Shot 2021-04-29 at 1 46 30 PM" src="https://user-images.githubusercontent.com/5720791/116616291-66c98680-a8f1-11eb-8541-e2034bdf4e43.png">

**Comment by KyndallH** [comment]
Pretty sure she is talking about A1 then A10 then A2 is after 19.

<img width="364" alt="Screen Shot 2021-04-29 at 2 11 32 PM" src="https://user-images.githubusercontent.com/16887896/116624732-eb69d400-a8f4-11eb-9aef-8d12dd28d33d.png">

**Comment by campmlc** [comment]
Yep

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
It would be really helpful to me to have containers in the object tracking tree sort in alphanumeric order by Label. For example:
![image](https://user-images.githubusercontent.com/47402809/146619317-19d969f9-8169-4b5c-b6e0-100301400a3d.png)

Is really unhelpful and makes it hard to find things.

**Comment by campmlc** [comment]
Agree.

**Comment by campmlc** [comment]
Also the concern from #4207 about why positions sort randomly, given they are numeric. And that barcodes and labels also seem to sort randomly and not even alphanumeric in search results display. See #4207.

**Comment by Jegelewicz** [comment]
Dusty is gonna look into this, but we need to be on the lookout for a way to replace this tree anyway!

**Comment by dustymc** [comment]
Upping priority, sorting may be a limitation of the current library, need to investigate.

**Comment by Jegelewicz** [comment]
@dustymc something like this? https://www.cssscript.com/tree-view-checkboxes/

Am I barking up the wrong tree?

**Comment by Jegelewicz** [comment]
Whoa - this one is COOOOOL https://www.cssscript.com/demo/visualize-hierarchical-tree-d3-mitch/

From https://www.cssscript.com/visualize-hierarchical-tree-d3-mitch/

**Comment by dustymc** [comment]
Next release should be sorting by integer-bits, which I'm sure will look random in some situation but it can be changed if necessary.

I also added the barcode to the view in the usual format - it was only showing up in the first search, not on expansion, I'm not sure why - I can un-do that if necessary.

Calling this next release.

@Jegelewicz cssscript is some blog/click generator/something, https://github.com/daweilv/treejs seems to be the library, it doesn't seem to have async capabilities.

**Comment by dustymc** [comment]
Shift-reload - your browser is still hanging on to old code, somehow.

<img width="360" alt="Screen Shot 2022-04-22 at 7 27 23 AM" src="https://user-images.githubusercontent.com/5720791/164734846-f0039d9a-63f3-4fb3-bb87-8b00b1f775e1.png">

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Got it to update, but still the same sorting problem? Is it sorting by barcode?

![image](https://user-images.githubusercontent.com/47402809/164735760-009a6aa7-b88a-4df0-a367-d4c23942444f.png)

**Comment by dustymc** [comment]
yes barcode then label

```
order by 
NULLIF(regexp_replace(barcode, '\D', '', 'g'), '')::int,
NULLIF(regexp_replace(label, '\D', '', 'g'), '')::int
```

**Comment by dustymc** [comment]
>having the option to sort by different things 

Aha, maybe. I'm not sure - I'll see if I can figure out how to get that to accept a 'sort' argument.

**Comment by dustymc** [comment]
<img width="200" alt="Screen Shot 2022-04-22 at 9 47 59 AM" src="https://user-images.githubusercontent.com/5720791/164758862-0545c1cd-4401-49e8-a247-4790670d569c.png">

There's a sort option (check it out in test), it's a little janky but seems to mostly work. Essentially it seems that the library caches, so 

* search
* expand a node
* collapse the node
* change sort 
* expand the previously-expanded node
 
does nothing, at least most of the time.

* set sort
* search
* expand a node

works, as does

* search
* set sort
* expand a node that hasn't been expanded

I'm not thrilled with that, but that seems to be the extent of control I have. The default works as it does now, I don't think this can be overly disruptive, going back to next release.

**Comment by Jegelewicz** [comment]
I think that changing the order of the sort operation might be more useful to users? Barcodes ar mostly nonsensical things, but labels are meaningful to humans....

label then barcode?

```
order by 
NULLIF(regexp_replace(label, '\D', '', 'g'), '')::int
NULLIF(regexp_replace(barcode, '\D', '', 'g'), '')::int,
```

**Comment by dustymc** [comment]
>label then barcode?

https://github.com/ArctosDB/arctos/issues/3050#issuecomment-1106697435

?? I'll change the default, but users can do whatever they want.

>Barcodes ar mostly nonsensical things

Except when they're not....

**Comment by Jegelewicz** [comment]
Don't change it just because I said so - make sure somebody else agrees...

**Comment by KyndallH** [comment]
I agree! Is that enough! :)

**Comment by campmlc** [comment]
Reopening this issue because of the attached file, produced by entering a csv list of barcodes (for items which are not cataloged) in Find Container, and using Drag/Print to get the result (as there is no other way I'm aware of to find and view locations for a list of noncataloged barcodes -please tell me if I'm wrong?)
[bird barcodes scanned in Arctos 3-21-2023.pdf](https://github.com/ArctosDB/arctos/files/11033731/bird.barcodes.scanned.in.Arctos.3-21-2023.pdf)

 I'm really not sure what kind of order is represented by what is displayed here, but it is not intuitive by human beings.
It isn't sorting by the barcodes of the containers in the csv list, or by the box barcodes, or box positions, or rack positions or ?
What is it sorting on? And can we fix it so that it makes some sort of sense?

I propose:
freezer barcode: freezer position: rack position: box position.
With the positions sorting as humans would expect: 
1,2,3,4,5,....9,10,12,12

**Comment by campmlc** [comment]
Here is the list of barcodes used to generate that file:

[Holloman barcodes_birds 2022.zip](https://github.com/ArctosDB/arctos/files/11033812/Holloman.barcodes_birds.2022.zip)

**Comment by campmlc** [comment]
Reading this previous thread - labels are OK to sort by too, works for me, but how do we deal with positions? Is that the problem here? I honestly can't find any pattern in what appears to be random sort.

**Comment by campmlc** [comment]
I'm still having trouble - not sure what the order of operations is for the results below, but the positions are not sorting correctly, and neither are the barcodes or their labels.
![Screenshot 2023-03-23 10 59 12](https://user-images.githubusercontent.com/14808196/227380042-cee6f8e9-677d-43d7-9c27-84b569bb5cf5.png)
