### ISSUE TITLE
Blank values in code table

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3051]
@dustymc what's going on here?

![image](https://user-images.githubusercontent.com/5725767/91192275-f9ef5400-e6b2-11ea-9ce7-8653f1369011.png)

I deleted two of these and now realize that they perhaps only LOOKED blank? Because when I tried to delete this one, I got an error that it was in use. Any idea which ones I took out so I can replace them?

Sorry.....

**Comment by dustymc** [comment]
Oh boy - looks like case, one of those places the Oracle/PG "just different" likes to burn through. I'll go panic in that general direction....

**Comment by Jegelewicz** [comment]
Let me know if I can help with anything...

**Comment by dustymc** [comment]
Well it wasn't what I thought - there were a bunch of variations of 'carapace...' for some reason. I think those are all cleaned up, form should be happy, I'll check the constraints to make sure that's not possible to create that situation in PG. These are in the CTCT but aren't used - can we get rid of them? Some are new, some seem potentially useful, a couple are just weird denormalizations - a bad replacement for age class or relationships or etc.

```

arctosprod@arctos>> select attribute_type from ctattribute_code_tables where attribute_type not in (select attribute_type from attributes);
     attribute_type     
------------------------
 embryo weight
 numeric abundance
 brood parasite present
 middle toe length
 forewing length
 tooth length
 luster

```

**Comment by Jegelewicz** [comment]
Here are my thoughts on these:

**embryo weight**
if the embryo is cataloged as a part of the parent, I could see how a separate value here would be useful in order to establish it as a separate value from the weight of the parent it is cataloged with. Ideally, it would just be cataloged separately, related to the parent, and use the attribute "total weight". Unfortunately, life is never ideal. Not sure who plans to use it, but I can see why it might be here. How long ago was it created?

**numeric abundance**
Can't find an issue for this, although it seems like I remember the discussion. This was meant for actual counts as opposed to the ctabundance terms. Seems useful.

**brood parasite present**
Seems useful (the parasites are not technically endo or ecto?).

**middle toe length**
Seems overly-specific. Change to "toe length" and put middle in the remark? Again, not sure who requested this, can find no issue. This is one I would say we change and wait for whoever was planning to use it to show up.

**forewing length**
This is an entomology term. Seems like it is useful, but not 100% sure.

**tooth length**
See https://github.com/ArctosDB/arctos/issues/2583 I probably have this attribute sitting around awaiting load because of that open issue.

**luster**
will get used by NMMNH:Geol soon-ish

**Comment by ewommack** [comment]
`middle toe length
Seems overly-specific. Change to "toe length" and put middle in the remark? Again, not sure who requested this, can find no issue. This is one I would say we change and wait for whoever was planning to use it to show up.`
That's a birding measurement, often used as a proxy for size. It's mostly passerines though, and other groups of birds do have other toes measured. 
I'd be comfortable switching it to toe length.

`brood parasite present
Seems useful (the parasites are not technically endo or ecto?).`
I'd use this one if I was doing eggs, and had a clutch with a brood parasite egg in it. It's more common than you would think. I bet old collectors were on the look out for these clutches.

**Comment by dustymc** [comment]
>change

There's nothing to change, we can just delete it. We can keep it to, if there's an imminent use case.

>brood parasite

Again not used, so I question the value - but maybe someone's about to do something awesome. These are best entered as multiple related records, but all of the MVZ egg/nests just use "warbler and cowbird" kinds of IDs.

**Comment by ewommack** [comment]
`Again not used, so I question the value - but maybe someone's about to do something awesome. These are best entered as multiple related records, but all of the MVZ egg/nests just use "warbler and cowbird" kinds of IDs.`
That actually makes more sense. You could search on the cowbird taxonomically, but it would be not as obvious to search under brood parasite. If it isn't used, then perhaps we should just get rid of it. 
Are there other types of brood parasites that are less obvious? Like insects?

**Comment by Jegelewicz** [comment]
@ewommack the identification isn't brood parasite, that's an attribute. Ideally you would have:

Catnum1 identified as warbler with the other ID Catnum2, relationship brood host of
Catnum2 identified as cowbird with the other ID Catnum 1, relationship brood parasite of

Right now they are cataloged like this

Catnum1 identified as "warbler AND cowbird" with and attribute "brood parasite present"

**Comment by dustymc** [comment]
Yes agreed. In general, if you have something important to say then you should find a way to say it, not bury it in some other data and hope users can somehow figure out what you were thinking at the time. "warbler AND cowbird" could indicate nest parasitism because I've collected eggs from a single nest, or nothing useful because I've collected eggs from multiple sources and cataloged them together for some crazy reason. 

``THIS {is relation to} THAT`` carries no ambiguity.

Most users will probably correctly infer what MVZ is up to, and Carla probably has better things to do than recatalog a collection - we're likely stuck with this for now - but it's not something I'd recommend going forward either.

**Comment by ewommack** [comment]
Ok I'm confused. 

Is any one actually using 
brood parasite present
?

**Comment by dustymc** [comment]
@ewommack no

**Comment by ewommack** [comment]
It looks like there are about 10 collections in Arctos that have Egg Collections. 
Is there a thought that we should keep the value just in case one of them may want to use it?

**Comment by Jegelewicz** [comment]
I say we delete it and wait for someone to ask for it again. Then we can point them to this discussion.

**Comment by ewommack** [comment]
That works for me! 

I'd say the same with middle toe length if it is also not being used. There are a ton of passerines on Arctos already, and if we haven't used the value yet then I think we need to hear from someone who really needs it to add it back in.

**Comment by Jegelewicz** [comment]
brood parasite present and middle toe length deleted from code table.

**Comment by Jegelewicz** [comment]
After looking at it, tooth length was probably added at the same time as tooth width (which is apparently being used). So for now, I think it should stay.

**Comment by Jegelewicz** [comment]
@dustymc there is still one of these hanging around blank

![image](https://user-images.githubusercontent.com/5725767/92045621-4c2d1680-ed3e-11ea-83ba-c58e1081175c.png)

**Comment by Jegelewicz** [comment]
Actually, make that two
![image](https://user-images.githubusercontent.com/5725767/92045660-5cdd8c80-ed3e-11ea-9556-1ed6f8fc9411.png)

**Comment by dustymc** [comment]
Thx, cleaned, maybe for real not possible to do this now....
