### ISSUE TITLE
Feature Request - Add media with local URI

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#3052]
** Describe what you're trying to accomplish** 
We'd like to use local URI's for any media we need to keep private. Currently, media can only be added with a functional URL.

**Describe the solution you'd like**
In "Create Media from URL", allow the ability to create media without a functional URL. There should be some kind of warning that the URL is not functional, some version of "don't do this unless you know what you're doing"

**Describe alternatives you've considered**
Currently the only way to add media with a local URI is to upload with a valid URL, then go back in and change the URL to the local URI.

**Comment by dustymc** [comment]
>some version of "don't do this unless you know what you're doing"

This is my concern; this change would allow local paths (eg, your C:// drive). How do we allow that while also avoiding frustrated users and lost media?

>don't do this unless you know what you're doing

I'll add a warning to the form. 

Do we need additional documentation/training/?????????

**Comment by Jegelewicz** [comment]
Do we just need a separate function?

Create Media from local source

**Comment by dustymc** [comment]
>separate function

If you mean a different widget, that would be Major Surgery. A separate pane in the widget is more approachable, but I'm not sure if it's any more or less cryptic. (And I can't really know what "local" means which could get weird - http://127.0.0.1 is "on this computer," many orgs are running their own DNS servers so http://someURL.whatever may or may not be "local," etc.)

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
For documentation, we will need to update:
[Media](https://handbook.arctosdb.org/documentation/media.html)
[How to Create Media](https://handbook.arctosdb.org/how_to/How-to-Create-Media-Images.html)

**Comment by dustymc** [comment]
next release has no URL validation
