### ISSUE TITLE
Mineral Names to load

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3055]
@dustymc I am attaching a file of mineral names to load. I would have done this myself but I think that https://arctos.database.museum/tools/BulkloadTaxonomy.cfm needs to require the name type field.

Also, many of these are going to break the Linnean rules, so I'm thinking you will need to force them in.

Let me know if you have questions (I am sure you will).
[Mineral Names.zip](https://github.com/ArctosDB/arctos/files/5126394/Mineral.Names.zip)

**Comment by dustymc** [comment]
>needs to require the name type field.

I think it's there - it is in test, I can push a release if necessary.

>break the Linnean rules

That's why we added name_type! If there are mineral rules let me know and I'll add them - until then, you can load just about anything - please don't....

**Comment by Jegelewicz** [comment]
Hey man - don't tell me I can do something then tell me not to!

I created a small test file - we need to update the documentation (I can do this). After validation, I get this:

![image](https://user-images.githubusercontent.com/5725767/91334653-83bf2000-e78c-11ea-803a-073e2e73b5e9.png)

So I'm guessing we need to supply rules for the mineral name types.

I'll see what I can do.

**Comment by dustymc** [comment]
You should be able to load those assuming they meet the rules (which is "unique" and nothing else at the moment), that's just a "you're getting no help from us" warning. Probably need better inline docs.

> tell me not to

Sorray! 54 spaces, 𓆏, 13 more spaces, 𓆉, 29 more spaces would make a pretty cool taxon name.....

**Comment by Jegelewicz** [comment]
That would be the best identification ever....

**Comment by Jegelewicz** [comment]
Can we get a reset status to NULL button on https://arctos.database.museum/tools/BulkloadTaxonomy.cfm ?

Also, can cultural and mineral names return "name is unique" if they are unique (the only rule for now...)? I'll change the documentation to say:

> For Linnean names, the validation service queries various sources for the name. It fails, often, with both false positives and false negatives. You are solely responsible for the names you create. Cultural and mineral names will validate if they are unique, so please take care that you are not creating duplicates. Only records with NULL status will be validated. You may need to reload a few times; the external services can be slow.

**Comment by Jegelewicz** [comment]
So there ARE rules because 

![image](https://user-images.githubusercontent.com/5725767/91336847-c9c9b300-e78f-11ea-8303-3aa74e015301.png)

happened at Abenakiite-(Ce)

**Comment by dustymc** [comment]
Hu, so there are. I'm way ahead of me, apparently....

https://github.com/ArctosDB/PG_DDL/blob/master/function/isvalidnonlinneantaxonname.sql

If you're sure that's real, and taxonomy, I can adjust the check.

Then the question would be whether we allow ()- in all non-Linnean names, or just mineral.

**Comment by Jegelewicz** [comment]
I say allow those for just mineral! I don't want people to start putting crazy stuff into Linnean names (unless that gets sanctioned somehow by someone with greater taxonomic knowledge than me).

Let me check to see that those are the only special characters.

**Comment by Jegelewicz** [comment]
mineral names should allow the following:

(
)
-
.

Spaces are allowed as well and the first letter of the term should be capitalized (if that can be checked). Anything else?

**Comment by dustymc** [comment]
https://github.com/ArctosDB/PG_DDL/blob/master/function/isValidMineralTaxonName.sql is hooked in

**Comment by Jegelewicz** [comment]
Cool. Need to add "+" like this?

~ '[^A-Za-z \.üë×ö\-\)\(\+]'

What's up with these? üë×ö (just curious)

**Comment by dustymc** [comment]
That should do it - done and in.

üë×ö are valid(ish) in botanical names - should I remove them from this?

**Comment by Jegelewicz** [comment]
HMMM, there are a bunch of these, but I was just going to remove them and then put the "proper" spelling as a remark in the classification. Will they need to be entered with the unicode equivalent to make them work?

Example:
Alnaperbøeite-(Ce)

I was going to enter the term

Alnaperboeite-(Ce)

I just don't want it to end up looking like
Alnaperb�eite-(Ce)

which is what happens when the csv gets created from Excel....

**Comment by dustymc** [comment]
If a few unicode characters are "valid taxonomy" then we could just list them out.

If more than a few are "valid" we'll probably need to just accept any character, which allows my hieroglyphics (and 54 flavors of dash-like things, and.....). We could also disallow certain characters, but that's going to be orders of magnitude more "fun" than explicitly allowing individual characters.

I have no way of knowing how "valid" transliterating to ASCII might be - that's a question for a mineral taxonomist, if any such thing exists.

>Excel

Yep, that looks like Excel to me....

**Comment by Jegelewicz** [comment]
I am inclined to use the "proper" spelling, but that will likely confound people bulkloading stuff. @Nicole-Ridgwell-NMMNHS what are your thoughts on this?

**Comment by Jegelewicz** [comment]
Maybe I should just enter both spellings with the potential alternate spelling relationship?

**Comment by Jegelewicz** [comment]
> If a few unicode characters are "valid taxonomy" then we could just list them out.

This is my preference.

A "few" will probably end up being somewhere between 10 and 20, but that seems pretty manageable, right?

**Comment by dustymc** [comment]
>enter both

Let's don't voluntarily re-create a system that from here looks like it's very carefully designed to break science. We might get dragged in kicking and screaming, but I'm not volunteering! Common names are designed for discovery, and transliterations are probably common enough. 25 ways of saying "that thing" is just broken.

Yes sorting through a few dozen characters is completely manageable, and will save data entry folks from any "guess the dash-looking thing" games.

**Comment by Jegelewicz** [comment]
OK - what do you think is better. Weird characters in common name or in "scientific" name?

**Comment by dustymc** [comment]
I'd say work with whoever might use this to identify some "official" source and do whatever they do. 

Or I could probably be convinced that ya'll need Excel which is trapped in 1995 and just can't deal with unicode characters for some reason....

**Comment by Jegelewicz** [comment]
We should add ß to the list of approved mineral characters.

**Comment by Jegelewicz** [comment]
"official" source = Mindat

Alnaperbøeite-(Ce) - https://www.mindat.org/min-43577.html

**Comment by Jegelewicz** [comment]
OOOOH - just discovered that the Arial font in Excel makes stuff work properly when converting to csv!

in Excel

![image](https://user-images.githubusercontent.com/5725767/91353688-d4dd0d00-e7a8-11ea-91e7-16fae41400ec.png)

in csv

![image](https://user-images.githubusercontent.com/5725767/91353763-f4743580-e7a8-11ea-82f3-2ac0a4eb6c0c.png)

Needs documentation!

**Comment by dustymc** [comment]
Works for me...

ø and ß added

>Arial font in Excel 

Yea that sounds like Microsoft.....

Or that could be notepad - I don't think it's very UTF-aware either.

**Comment by Jegelewicz** [comment]
characters to add include:

ä
å
Å
è
á
ć
é
ó
ý
ê
š
ž
ç

I have probably missed one or two and this makes me wonder if we shouldn't just include other letters with the same diacritics.

**Comment by dustymc** [comment]
those are added

**Comment by Jegelewicz** [comment]
Found more

í
ã
Č
ż
É
ţ
ň
ñ
ř
Š
ń

well that was a lot more than one or two and I'm sure there will be more...

**Comment by dustymc** [comment]
done

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> Weird characters in common name or in "scientific" name?

"scientific" seems the most logical.

**Comment by Jegelewicz** [comment]
@dustymc since we are "validating" mineral names to ensure they are not dupes and that they don't include any characters other than the ones we have specified, can we change the message received upon validation?

![image](https://user-images.githubusercontent.com/5725767/91761269-d5531a80-eb91-11ea-84cf-eef1e56daaec.png)

Maybe "name will load, no validation available from external resources"?

**Comment by Jegelewicz** [comment]
@dustymc please add to allowed letters for minerals

Á
à
'
1
2
3
4
5
6
7
8
9
0

**Comment by dustymc** [comment]
added

**Comment by Jegelewicz** [comment]
A few more

Ö
č

**Comment by dustymc** [comment]
added

**Comment by Jegelewicz** [comment]
Hope these are the last

ě
Š
α
Ż
ï

**Comment by dustymc** [comment]
added

**Comment by Jegelewicz** [comment]
One last letter

ô

**Comment by dustymc** [comment]
added

**Comment by Jegelewicz** [comment]
Loaded the names I came here with.

**Comment by Jegelewicz** [comment]
@dustymc these special characters aren't working in test? I just tried to add Achávalite and got:

An error occurred while processing this page!
Message: ERROR: Save rejected: Invalid characters. Where: PL/pgSQL function trigger_fct_trg_taxon_name_biu() line 13 at RAISE
Detail:
Check the Arctos Handbook for more information on errors.

This message has been logged as 7D4BFCFA-63CC-4C87-8A66DD0BD9E15184 Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue.

**Comment by dustymc** [comment]
I patched the updated function in, it might work now. Until we do something about https://github.com/ArctosDB/internal/issues/65 this shouldn't be unexpected.

**Comment by Jegelewicz** [comment]
AH, OK, so this should work in production? I want to get mineral taxonomy classifications loaded into Arctos, but was going to load in test first for review. Do you oppose me just working in production? It will be easier since the names are already there. I will just need to create the appropriate taxon terms in the code table.

**Comment by dustymc** [comment]
Doesn't seem like a problem to me - of course I'd like everything to go through test, but that's not as straightforward as it should be right now. If you think something might cause problems or somehow affect existing data or something I'll find a way to get test functional(ish, maybe) for that, but for new and self-siloed data which can easily be bulk-replaced I can't see much problem with just doing it.

The terms do make me a bit twitchy, but I might get over it. Or maybe you don't need them at all now that the loader can deal with NULLs? Anyway should be discussed if possible.

**Comment by Jegelewicz** [comment]
Can we add 
ő
to the approved characters for mineral names?

**Comment by dustymc** [comment]
done

**Comment by Jegelewicz** [comment]
UGH, I don't know what is causing this:

![image](https://user-images.githubusercontent.com/5725767/98267677-dfeeaf00-1f48-11eb-88aa-97d97d9c12e9.png)

An error occurred while processing this page!
Message: ERROR: Save rejected: Invalid characters. Where: PL/pgSQL function trigger_fct_trg_taxon_name_biu() line 14 at RAISE
Detail:
Check the Arctos Handbook for more information on errors.

This message has been logged as 200747E2-DB9E-4010-B05C25131B6F7E6C Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue. 

[Mineral names to add.zip](https://github.com/ArctosDB/arctos/files/5495598/Mineral.names.to.add.zip)

**Comment by dustymc** [comment]
https://github.com/ArctosDB/PG_DDL/blob/master/function/isValidMineralTaxonName.sql

You should be able to csv2table and run this as well.

I added β - not sure about the rest, eg looks like one of the very many apostrophe-like-characters, I don't think we need them all....

```
arctosprod@arctos>> select scientific_name, isValidMineralTaxonName(scientific_name) from temp_cache.temp_dlm_uptbl ;
              scientific_name               |       isvalidmineraltaxonname       
--------------------------------------------+-------------------------------------
 Felsőbányaite                              | valid
 Fergusonite-(Ce)-β                         | Invalid characters.
 Fergusonite-(Nd)                           | valid
 Fergusonite-(Nd)-β                         | Invalid characters.
 Fergusonite-(Y)-β                          | Invalid characters.
 Ferri-annite                               | valid
 Ferri-barroisite                           | valid
 Ferridravite                               | valid
 Ferrierite                                 | valid
 Ferritungstite                             | valid
 Ferri-winchite (of Leake 1978)             | valid
 Ferro-akermanite                           | valid
 Ferro-aluminotschermakite                  | valid
 Fluor-uvite-Uvite Series                   | valid
 Foshallasite                               | valid
 Freibergite Subgroup                       | valid
 Garronit-Ca                                | valid
 Georgiadèsite                              | valid
 Gersdorffite                               | valid
 Girdite                                    | valid
 Gismondine-Ca                              | valid
 Halloysite                                 | valid
 Hastite                                    | valid
 Herschelite                                | valid
 Heulandite                                 | valid
 Hodrušite                                  | valid
 Högbomite                                  | valid
 Hongquiite                                 | valid
 Horsfordite                                | valid
 Hydrohetaerolite                           | valid
 Hydromolysite                              | valid
 Hydrotalcite-2H                            | valid
 Hydroxy-petscheckite                       | valid
 Idrizite                                   | valid
 Imgreite                                   | valid
 Incaite                                    | valid
 Jacobsite-Q                                | valid
 Jeromite                                   | valid
 Johnbaumite-M                              | valid
 Joséite                                    | valid
 Kamacite                                   | valid
 Kennedyite                                 | valid
 Kësterite                                  | Leading or trailing spaces detected
 Keystoneite                                | valid
 Khinite-3T                                 | valid
 Kitaibelite                                | valid
 Kivuite                                    | valid
 Laubmannite                                | valid
 Lehiite                                    | valid
 Lévyne                                     | valid
 Liddicoatite                               | valid
 Madisonite                                 | valid
 Magnesio-anthophyllite                     | valid
 Magnesiocummingtonite                      | valid
 Magnesiogedrite                            | valid
 Magnesioholmquistite                       | valid
 Magnesionigerite                           | valid
 Magnesiosadanagaite                        | valid
 Magnesiotaaffeite-2N’2S                    | Invalid characters.
 Magnesiotaaffeite-6N’3S                    | Invalid characters.
 Magnesiotaramite                           | valid
 Magniotriplite                             | valid
 Mátraite                                   | valid
 Maufite                                    | valid
 Metahalloysite                             | valid
 Mimetite-M                                 | valid
 Molybdenite-3R                             | valid
 Natroalunite-2c                            | valid
 Natrobistantite                            | valid
 Natrofairchildite                          | valid
 Natrokomarovite                            | valid
 Nioboaeschynite-(Nd)                       | valid
 Nováčekite-I                               | valid
 Oboyerite                                  | valid
 Olivine                                    | valid
 Orlite                                     | valid
 Orpheite                                   | valid
 Orthochamosite                             | valid
 Orthochrysotile                            | valid
 Oxy-petscheckite                           | valid
 Oxypyromorphite                            | valid
 Padĕraite                                  | Invalid characters.
 Parabariomicrolite                         | valid
 Parachrysotile                             | valid
 Parajamesonite                             | valid
 Paraspurrite                               | valid
 Paulingite                                 | valid
 Pearceite-T2ac                             | valid
 Pectolite-M2abc                            | valid
 Phillipsite subgroup                       | valid
 Phosinaite                                 | valid
 Platynite                                  | valid
 Plumalsite                                 | valid
 Plumbobetafite (of Hogarth 1977)           | valid
 Plumbomicrolite (of Hogarth 1977)          | valid
 Plumbopyrochlore (of Skorobogatova et al.) | valid
 Polybasite-Tac                             | valid
 Potosíite                                  | valid
 Pseudo-autunite                            | valid
 P-Veatchite                                | valid
 Pyroaurite-2H                              | valid
 Pyrosmalite                                | valid
 Rößlerite                                  | valid
 Sakharovaite                               | valid
 Sapphirine-1A                              | valid
 Scherbinaite                               | valid
 Schirmerite                                | valid
 Shuiskite-(Mg)                             | valid
 Sodium-anthophyllite                       | valid
 Sodium Dachiardite                         | valid
 Sodium Gedrite                             | valid
 Stannomicrolite (of Hogarth 1977)          | valid
 Staringite                                 | valid
 Stibiomicrolite (of Groat et al.)          | valid
 Stilbite subgroup                          | valid
 Strontioborite                             | valid
 Strontio-orthojoaquinite                   | valid
 Strontiopyrochlore (of Hogarth 1977)       | valid
 Strüverite                                 | valid
 Taimyrite                                  | valid
 Tantalite                                  | valid
 Tapiolite                                  | valid
 Taramite Root Name Group                   | valid
 Tennantite Subgroup                        | valid
 Tetrahedrite Subgroup                      | valid
 Tetranatrolite                             | valid
 Tirodite                                   | valid
 Tombarthite-(Y)                            | valid
 Uhligite                                   | valid
 Uranmicrolite (of Hogarth 1977)            | valid
 Uranophane                                 | valid
 Uranophane-β                               | Invalid characters.
 Uranpyrochlore (of Hogarth 1977)           | valid
 Vanuranylite                               | valid
 Veatchite-A                                | valid
 Villamaninite                              | valid
 Viséite                                    | valid
 Vunonnemite                                | valid
 Wellsite                                   | valid
 Wolframite                                 | valid
 Wollastonite-2M                            | valid
 Wollastonite-7T                            | valid
 Yftisite-(Y)                               | valid
 Yttrobetafite (of Hogarth 1977)            | valid
 Yttropyrochlore (of Hogarth 1977)          | valid
 Zhonghuacerite-(Ce)                        | valid
 Zinnwaldite                                | valid
 β-Roselite                                 | Invalid characters.
(148 rows)
````

**Comment by Jegelewicz** [comment]
Got it - I'll see if I can change them to the one's we already have as acceptable. Thanks!

**Comment by Jegelewicz** [comment]
Can you add this one?

ĕ

**Comment by dustymc** [comment]
k

**Comment by Jegelewicz** [comment]
One more - &

This is weird, but the name is Calciobetafite (of   Mazzi & Munno). I tried replacing with "and", but that fails because of linnean stuff. I'd prefer to add the name as it is used, so can we add & to accepted characters for minerals?

**Comment by Jegelewicz** [comment]
Also, β-Roselite will not load because:

> An error occurred while processing this page!
> Message: ERROR: Save rejected: First character must be uppercase Where: PL/pgSQL function trigger_fct_trg_taxon_name_biu() line 14 at RAISE
> Detail:
> Check the Arctos Handbook for more information on errors.
> 
> This message has been logged as BC9CDBE4-5830-49CB-920B168DFED4C462 Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue.

**Comment by dustymc** [comment]
>that fails because of linnean stuff.

Hu? Should be entirely different rules.

>uppercase

I have no idea what to suggest. 

I'm not anxious to introduce the complexity of "upper ascii, or maybe one of these unicode characters from yet another giant and arbitrary list...."

These data looks like random compilations of random characters from here. 1 second after you're done, one which uses some random character that's not in your random list will be published. We can't possibly keep up if that's the situation.

It's not at all clear to me if those apostrophe-looking things are intentional - maybe they're all supposed to be apostrophes, maybe the one we just rejected means something in mineral taxonomy land (if there is such a place).

I'm tempted to suggest we drop the rules and leave it up to the user, but I don't really want to clean up the giant mess if that leads to one either.

??????????????????????????????????????

**Comment by Jegelewicz** [comment]
I fixed the apostrophes - we just need the & and to be able to start a name with β

> 1 second after you're done, one which uses some random character that's not in your random list will be published.

That is true - but these names do not change that often (only when a new edition of the book is published), so we could deal with the changes all at once when that happens....

**Comment by dustymc** [comment]
>need the & 

Not much problem - done

>able to start a name with β

Less not-problem. I can just drop the starts-with rule altogether, or I can come back when I don't have the parts bulkloader torn into tiny bits....

**Comment by Jegelewicz** [comment]
> 
>     that fails because of linnean stuff.
> 
> Hu? Should be entirely different rules.

"and" is still not allowed in mineral names. We are going to need it because a lot of the groups and subgroups are things like: Aluminosilicates of Cs, NH4 and Cu

**Comment by Jegelewicz** [comment]
>     able to start a name with β
> 
> Less not-problem. I can just drop the starts-with rule altogether, or I can come back when I don't have the parts bulkloader torn into tiny bits....

It can wait. I think that perhaps this should be one you just add under the hood? Once it's there, we can use it, no?

**Comment by dustymc** [comment]
>Aluminosilicates of Cs, NH4 and Cu

Sounds a bit like an identification, but I'm not at all sure where that line is - or if it exists - in mineral-land.

**Comment by Jegelewicz** [comment]
It is not an identification (although it could be), a bunch of stuff is classified as part of this subgroup. See https://www.mindat.org/search.php?cim=16.5

**Comment by Jegelewicz** [comment]
We will also need to add 
,
to the approved characters for minerals.

**Comment by dustymc** [comment]
Commas there.

>Only items listed in bold are recognised mineral species.

Mindat suggest that's NOT "taxonomy," if I'm reading that remotely correctly.

A bunch of Linnean stuff was treated as taxonomy until Arctos split identification and taxonomy; "in mindat" doesn't seem like a compelling argument, unless it's somehow a lot more authoritative than I think it probably is.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
It is a group within a mineral classification system, so yes, it is taxonomy, not an identification.

Mindat isn't authoritative in and of itself, but it is the only online "copy" of the authoritative references that are all in physical books out there that we don't have access to.

**Comment by Jegelewicz** [comment]
IT IS TAXONOMY!!!! I know it is weird, but that is only because mineral people haven't made up names for their "families" and such - they just use very literal descriptions.

> Only items listed in bold are recognised mineral species.

That is referring to "acceptedness".
