### ISSUE TITLE
Need SQL for report

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3057]
@dustymc  Is it possible to write SQL for a handler to allow a report template to pull the following conditional information?

"If NK present, display NK; if no NK, then display AF; if no AF, then display IF; if no IF, then display collector number; if no collector number, then display original identifier"

Also need to know if it is possible for a report to pull data across relationships; e.g. for an MSB:Para label to pull in scientific name of related host record.

**Comment by dustymc** [comment]
```
case 
  when concatsingleotherid(cataloged_item.collection_object_id, 'NK') is not null then 
    concatsingleotherid(cataloged_item.collection_object_id, 'NK')
  when  concatsingleotherid(cataloged_item.collection_object_id, 'AF') is not null then 
    concatsingleotherid(cataloged_item.collection_object_id, 'AF')
  when  concatsingleotherid(cataloged_item.collection_object_id, 'IF') is not null then 
    concatsingleotherid(cataloged_item.collection_object_id, 'IF')
  when  concatsingleotherid(cataloged_item.collection_object_id, 'collector number') is not null then 
    concatsingleotherid(cataloged_item.collection_object_id, 'collector number')
  when  concatsingleotherid(cataloged_item.collection_object_id, 'original identifier') is not null then 
    concatsingleotherid(cataloged_item.collection_object_id, 'original identifier')
  else null
end as someAlias
```

>pull data across relationships;

If whoever's running the report has sufficient permissions then yes, at least in theory. I have some related public data cached, but I'd need to know precisely what you want in order to know if they'll do what you need.

**Comment by campmlc** [comment]
Thanks!
I'm going to insert this into:

For the purposes of MSB Para, ideally we would need the host scientific
name pulled into MSB:Para reports when the host is in any other collection;
even more ideally, the option of host sci name and/or guid.  Preferably,
this would be from public cached data, because we may need to pull info
from collections we do not have access to (e.g. pull MVZ host data into and
MSB:Para label).

**Comment by campmlc** [comment]
Insert SQL into report:  msb_para_4dram_label_origID.cfr

**Comment by dustymc** [comment]
>when the host is in any other collection

Elaborate please. Is this an evaluation of Arctos collection, or an indication that this should use something like GBIF's API, or ???

Mostly unrelated, printing things that you can't control nor readily detect changes in on labels seems very strange to me. Perhaps it would be better to cache those data in 'verbatim host ID' so you can also record where they came from, and print that?

**Comment by campmlc** [comment]
One of the main strengths of Arctos - in fact what makes us unique - is
that we can associate cross-collection data for parasites and hosts. It is
precisely the need to have something other than "verbatim host ID" that is
critical here. Some parasitologist jots down "swamp rat" on their field
catalog, and that is what ends up in the parasite collection under
"verbatim host ID". However, the "rat" ends up at MSB and is identified to
species, and the professionals there keep this species identification
updated with the current taxonomy. I would like the option of pulling in to
labels and loan forms the current status of the host identification. We
have this capability. What good is it if we don't make use of it?

**Comment by dustymc** [comment]
I'm not arguing with any of that, but it's still not something I'd print on a label.

https://github.com/ArctosDB/PG_DDL/blob/master/function/getRelatedCacheTerm.sql should do what I think you're trying to do.

**Comment by campmlc** [comment]
We need to send vials out on loan and include loan reports with the current
host identification, in order to get an accurate parasite identification
back in return. I don't see any other option. I certainly don't want to
print "swamp rat" on a label. It is hard being a parasitologist . . . not
only do you have to look at worms all day, but no one understands us. :(
I'll see if I can figure out the SQL, thanks.

**Comment by dustymc** [comment]
>hard being a parasitologist

That's my point!

Make a loan, create a project, print "this is complicated, see {project_url} for current data" as an invoice, now they're looking at the current data and all the complexity it might hold, not just the bits you might print on a label (which could be out of date before the ink is dry).

**Comment by campmlc** [comment]
I'm afraid that my 80-year old nematode expert is not going to go look at
links in a project page to find host data as he is dumping the contents of
a vial into a dish under his dissecting scope. I need that info printed on
a loan form and the vial label. So yes, I need this option - it should be a
curatorial decision whether to use or not, but the option should exist in
Arctos.

**Comment by campmlc** [comment]
So is the conclusion that pulling related host info is not possible? Or requires too many resources? This is an important issue that I do not want to close without further discussion.
