### ISSUE TITLE
Catalog record search using match type=comma list for identification fails

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#3058]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

One should be able to search on a comma separated list of scientific names in the identification field using match type = comma list but this fails

**To Reproduce**
1. Go to Search form
2. paste Badonnelia titei,Trichodectes canis into the identification field & choose match-type = comma list
3. click search
4. nothing found

**Expected behavior**

all records with any match to the current ID names should be found

**Screenshots**

** Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label.

HIGH - need this feature for a manuscript I'm preparing.

**Comment by dustymc** [comment]
will be in next release - maybe tonight
