### ISSUE TITLE
Locality IDs

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3059]
When localities are loaded in a bulkload file, even if the localities are identical (copy/paste down the column) with no transcription variation, it appears Arctos assigns each a unique locality ID. I assume it does the same with CE ID. Is this intentional? It would be much more useful from a curatorial standpoint if shared localities were given a shared ID.
I assume the alternative would be to pre-upload each individual locality prior to bulkload and assign each one a nickname. This would effectively double or triple the effort and time involved in bulkloading. 
Another alternative is to go in after the fact, find and merge duplicate localities. Do we have scripts doing this, so I don't have to worry about it?

**Comment by dustymc** [comment]
https://handbook.arctosdb.org/documentation/locality.html#maintenance
