### ISSUE TITLE
Add amastigote to age class attribute

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3060]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Goal**
Add "amastigote" to age class code table; or come up with a separate code table for age classes of different taxonomic groups. There are going to be many different names that differ by taxon and life cycle as we add in parasites, viruses, etc. 

**Context**
Describe why this new value is necessary and existing values are not. Because Arctos is still very lacking in protist morphological and taxonomic terms. This is a crucial life stage in the biology of the malarial parasite.

**Table**
ctage_class

**Value**
amastigote

**Definition**
An amastigote is a protist cell that does not have visible external flagella or cilia. The term is used mainly to describe an intracellular phase in the life-cycle of trypanosomes.

https://en.wikipedia.org/wiki/Amastigote#:~:text=An%20amastigote%20is%20a%20protist,cycle%20of%20trypanosomes%20that%20replicates.
**Collection type**
Para 

**Attribute data type**
free-text, categorical, number+units

**Attribute value**
For categorical attributes, code table controlling value

**Attribute units**
For number+units attributes, code table controlling units

**Part tissue flag**
For new parts, is the part a tissue?

**Other ID BaseURL**
For OtherIDs, URL with which to prepend value (resolvable identifiers only)

**Priority**
High

**Comment by dustymc** [comment]
I don't think this is age-related. https://github.com/ArctosDB/arctos/issues/2881

**Comment by campmlc** [comment]
Agree, but that's where everything else currently is. Possibly a new code
table for "Life Stage" or "Life Cycle Stage"; or we could flag a particular
stage as being the asexual or sexual form. Perhaps amastigote should be in
the part name. This requires some considerable discussion. Unfortunately,
we need more invert and parasite experts involved.

**Comment by dustymc** [comment]
>where everything else currently is.

https://en.wikipedia.org/wiki/Law_of_holes

>new code table 

I think so, or perhaps generalize to something all-encompassing ("form" or etc.).

>the asexual or sexual 

I think that's likely a different attribute, but ?????????????

**Comment by campmlc** [comment]
Additional terms to add to this same code table or whatever it becomes:

ovum/ova ? Do we need this as option in additon to egg?
--
Oocyst: A hardy, thick-walled stage of the life cycle of coccidian parasites. This is the stage that is shed in the feces of people infected with parasites such as Cyclospora and Cryptosporidium.
We are going to need all of the following - and that is just one taxonomic group:
https://en.wikipedia.org/wiki/Apicomplexan_life_cycle

**Comment by Jegelewicz** [comment]
HMMM, maybe the table is just poorly named? Aren't all of the terms in https://arctos.database.museum/info/ctDocumentation.cfm?table=ctage_class a "life stage"? 

> ovum/ova ? Do we need this as option in addition to egg?

My gut says no - we should change the term to ovum and include those synonyms in the definition.

**Comment by dustymc** [comment]
>poorly named..."life stage"

I think I could live with that, and I could live with "temporarily" dealing with it via documentation/declaration.

>egg

Either a merger or better documentation - 'this isn't that because reasons.'

**Comment by dustymc** [comment]
merge-->[giant mess](https://github.com/ArctosDB/arctos/issues/2881)
