### ISSUE TITLE
Add link to Create Publication from Taxon Edit Name

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3061]
Can we get a direct link or a pop up to add/create a publication related to a Taxon Name from the Taxon Name Edit page Pick Publications link? That way we can directly add a relevant pub without having to exit the Taxonomy page.

**Comment by dustymc** [comment]
Tabling; I can't see how creating publications without first using the full search capability of the publications tools could be safe, but reopen and clarify if I'm not understanding something.
