### ISSUE TITLE
Bulkloader download file not formatted for reupload?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3062]
Problem:
1) I bulkloaded data, loaded OK records, downloaded remaining records with errors and deleted them from the bulkloader.
2) I made edits to the downloaded file. There was no column for collection_object_ID, so I added one back in.
3) Attempted to load - got error that there was something wrong with my column headers.
4) Looked over file in more detail - in the bulkload error download, in addition to the missing collection_object_id column, there are extraneous columns that have to be removed prior to re-bulkload. 
These are:
collection_id | entered_agent_id | enteredtobulkdate | uuid

Can we have the option of downloading a bulkload-ready file from the bulkloader, with the only added column being "loaded" so we can check for errors? Can we also get a field for collection object ID in this download?

Finally, we have discussed a consistent order for columns. Can we get this download file from the bulkloader to display columns in the same order as the bulkload builder (within reason - obviously the builder may have extra or missing columns depending on preferences), and can this be the same order we choose the columns to display in the bulkloader?

**Comment by dustymc** [comment]
removed extraneous columns
