### ISSUE TITLE
Philippine higher geog issues

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3063]
Higher geography for Philippines is confusing. I have a locality that gives only "Luzon", but Luzon is divided among many islands.  Shouldn't this be a political district that occurs farther up in the hierarchy, above the island name?
Request to have a new higher geog available as "Asia, Phllippines, Philippine Islands, Luzon".

**Comment by campmlc** [comment]
Found it - closing.

**Comment by mkoo** [comment]
yes this is confusing (ask Filipinos! for its area it has a huge linguistic
diversity, too)

https://en.wikipedia.org/wiki/Administrative_divisions_of_the_Philippines
https://en.wikipedia.org/wiki/Administrative_divisions_of_the_Philippines#Island_groups

So I think we need at least three islands (groupings): Luzon, Visayas,
Mindanao
And for each there are several regions.

Luzon as an island exist, which I updated with a wikipedia ref:
https://arctos.database.museum/Locality.cfm?Action=editGeog&geog_auth_rec_id=10000450

Given the vagueness of that locality, this would work. We can add wkt as
well.

**Comment by campmlc** [comment]
Thanks!
