### ISSUE TITLE
Add Sarawak higher geog to Malaysia

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3064]
Currently have it in Borneo; are we using political boundaries?

**Comment by dustymc** [comment]
https://arctos.database.museum/info/ctchange_log.cfm?tbl=geog_auth_rec&geog_auth_rec_id=10000425

@mkoo why was this made inconsistent?

https://handbook.arctosdb.org/documentation/higher-geography.html#guidelines-for-geographic-terms-in-arctos

**Comment by sharpphyl** [comment]
Sarawak looks ok to me.  It's on the island of Borneo (as is Sabah, Malaysia).  

<img width="1411" alt="Screen Shot 2020-08-29 at 1 36 07 PM" src="https://user-images.githubusercontent.com/15368365/91644780-ad7e7e00-e9fc-11ea-82e6-f6770f1e70e2.png">


The one that's in error is this one.  There is no country Borneo, just the island which is home to parts of Malaysia, Indonesia and all of Brunei.

<img width="505" alt="Screen Shot 2020-08-29 at 1 30 27 PM" src="https://user-images.githubusercontent.com/15368365/91644719-f124b800-e9fb-11ea-9eef-6bdec64b59c0.png">

The country Borneo should be deleted from this entry.  

We could also reconsider using Indonesian Archipelago which appears to be the same as the Malay Peninsula and, perhaps less politically, Maritime Southeast Asia.  But that's a whole different can of worms.

https://en.wikipedia.org/wiki/Maritime_Southeast_Asia
https://en.wikipedia.org/wiki/Malay_Archipelago
https://en.wikipedia.org/wiki/List_of_islands_of_Indonesia

**Comment by dustymc** [comment]
> It's on the island of Borneo

Which is part of Indonesian Archipelago for all entries except this one.

<img width="418" alt="Screen Shot 2020-08-29 at 1 46 58 PM" src="https://user-images.githubusercontent.com/5720791/91645891-3c3fca80-e9fe-11ea-9a4e-e90c782b9262.png">


I don't know what we should be doing there, if anything (not that different from "Dixie" maybe), but whatever we do we should do it consistently. 

>The country Borneo should be deleted from this entry.

Agree.

https://arctos.database.museum/Locality.cfm?action=editGeog&geog_auth_rec_id=1005131 

https://arctos.database.museum/SpecimenResults.cfm?geog_auth_rec_id=1005131

**Comment by sharpphyl** [comment]
Do we need agreement among the users or can I go ahead and delete the entry for the country Borneo?

**Comment by mkoo** [comment]
Please delete! thanks!

**Comment by sharpphyl** [comment]
Done.
