### ISSUE TITLE
Geography cleanup- remove Eurasia from Continent

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3070]
We currently have 13 HG entries that use Eurasia in the Continent field. Suggest we clean these up and move to either Asia or Europe.

Most of these are Kazakhstan which is also a mish-mash of "Region" and "Province" in the "state" field and should be cleaned up too.

**Comment by Jegelewicz** [comment]
Bumped priority because "Eurasia" does not conform to documentation - https://handbook.arctosdb.org/documentation/higher-geography.html#continent--ocean

**Comment by dustymc** [comment]
>"Eurasia" does not conform to documentation 

>Both are sometimes in Eurasia.

??

**Comment by Jegelewicz** [comment]
> Both are sometimes in Eurasia.

Where is that from?

**Comment by Jegelewicz** [comment]
Because we haven't defined "continent" we also have "West Indies" as a continent....

**Comment by Jegelewicz** [comment]
See also https://github.com/ArctosDB/arctos/issues/3065#issuecomment-683320394

**Comment by Jegelewicz** [comment]
See also https://github.com/ArctosDB/arctos/issues/1291#issuecomment-678287979

**Comment by dustymc** [comment]
Tabling - https://github.com/ArctosDB/arctos/issues/3272 would allow Arctos to standardize geography (but probably not when 'Eurasia' is all that's known).
