### ISSUE TITLE
Menu for Georeference Source Looks Odd

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#3071]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
When entering information into the data entry field: Georeference Source a drop down menu comes up, but it looks like it is displaying the information for one source all in one large vertical line of text.

**To Reproduce**
Go to Data Entry
Enter data into the Georeference Source field. I tried entering both Montana State University Coordinate Converter, and Geolocate, and the same thing happened.

**Expected behavior**
Should there be a specific drop down menu with suggestions written in the horizontal so they are easy to read?

**Screenshots**
![Georeference source funny business](https://user-images.githubusercontent.com/18562884/91881223-641d7100-ec3e-11ea-9ebb-ae78b033222e.jpg)

** Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**
 MacOS, Chrome, Version 84.0.4147.135

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by Jegelewicz** [comment]
Georeference source is a free text field - this means that someone has entered those things in that field.

**Comment by dustymc** [comment]
That was a (failed) attempt to get some standardization in a free-text field. The suggest should be removed.

**Comment by ewommack** [comment]
Ok that works for me. 
I think it was trying to saying Acmemapper at me, but I couldn't really figure it out.

@dustymc Should I close the issue now, or wait until the next task goes live?

**Comment by dustymc** [comment]
Closing would remove it from my to-do list.

**Comment by ewommack** [comment]
Don't want that! Fix away please.
