### ISSUE TITLE
Reports Server is Down?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3073]
![Screenshot 2020-09-01 14 36 15](https://user-images.githubusercontent.com/14808196/91903593-b4a5c600-ec60-11ea-847e-15ffdd0c8add.png)

**Comment by campmlc** [comment]
BTW, I'm logged in. I've been using this over the last few hours with no issues, until now.

**Comment by dustymc** [comment]
It's not down. This isn't enough information for me to find the problem.

**Comment by campmlc** [comment]
Log in - go to Transactions - Find Loan - Edit - Print Any Report - get rerouted to the Reports Server - click link - get error.
All worked fine earlier today.

**Comment by dustymc** [comment]
Still works for me, could be your browser, you might try clearing cookies/cache.

**Comment by campmlc** [comment]
That appears to be the case, as I can open in Firefox, but I've cleared my browsing history in Chrome, closed and reopened browser, logged out and back in, and am still getting the error.

**Comment by campmlc** [comment]
OK, now it's working. Must have been some sort of lag.
That is a really ugly error - any way to pretty it up any? Like - "User not
recognized. Please close browser and try relogging in. You may have to
clear your browser cookies/cache. If this message continues, please Contact
Arctos."
