### ISSUE TITLE
Code Table Request - culture of origin / culture of use = Métis

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#3074]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Goal**
I need to add Métis to the ctculture list.

**Context**
Describe why this new value is necessary and existing values are not.
Métis is the name to describe a multiancestral Indigenous group of people of Western Canada. This value does not currently exist on the ctculture.

**Table**
Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm
ctculture
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctculture

**Value**
Métis

**Definition**
The Métis are a multiancestral indigenous group whose homeland is in Canada and parts of the United States between the Great Lakes region and the Rocky Mountains. The Métis trace their descent to both Indigenous North Americans and European settlers; see also https://en.wikipedia.org/wiki/Métis

**Collection type**
Arc
EH

**Attribute data type**
free-text, categorical, number+units
[I don't know the answer to this - it's a pick list of controlled vocabulary - does that make it categorical?]

**Attribute value**
For categorical attributes, code table controlling value
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctculture

**Priority**
Please assign a priority-label.
High - I have a new donation coming soon that i"ll need this to catalog appropriately.

**Comment by Jegelewicz** [comment]
Added
