### ISSUE TITLE
Code Table Request - New Taxon Terms for mineral taxonomy

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3076]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Goal**
Add taxon classifications for minerals

**Context**
Non-Linnean taxonomy requires different term types

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxon_term

**Value**
Proposed new values with definitions

Term | Definition 
 -- | -- 
supergroup | Two or more mineral groups having identical or closely related structures. 
group | Two or more mineral species having identical or closely related structures; e.g., hematite group or zeolite group. <a target="_blank" class="external" href="https://www.mindat.org/glossary/mineral_group">Mindat</a> 
subgroup | The next level of mineral classification after categorization in groups. <a target="_blank" class="external" href="https://www.minerals.net/mineral_glossary/subgroup.aspx">Minerals.net</a> 
homologous_series | Groups of minerals in each of which the difference between successive members is a simple structural unit. <a target="_blank" class="external" href="https://www.britannica.com/science/homologous-series">Britannica Article</a>

For these terms, which already exist in the code table, the definitions here have been appended to the code table definition.

Term | Definition 
 -- | -- 
family | The basic unit of the clan of igneous rocks. <a target="_blank" class="external" href="https://www.mindat.org/glossary/family">Mindat</a> 
species | Any mineral that can be distinguished from all other minerals by current determinative methods. <a target="_blank" class="external" href="https://www.mindat.org/glossary/mineral_species">Mindat</a>  A mineral distinguished from others by its unique chemical and physical properties; it may have varieties. <a target="_blank" class="external" href="https://www.mindat.org/glossary/species">Mindat</a>
variety | Specimens of a mineral species with distinctive physical properties due to: (1) specific history; e.g., Iceland spar, a coarsely crystalline variety of calcite of optical grade, or (2) small chemical variation; e.g., amalgam, a mercurian variety of native silver. <a target="_blank" class="external" href="https://www.mindat.org/glossary/mineral_variety">Mindat</a>

**Definition**
see above

**Collection type**
N/A

**Attribute data type**
N/A

**Attribute value**
N/A

**Attribute units**
N/A

**Part tissue flag**
N/A

**Other ID BaseURL**
N/A

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
All existing terms can serve as valid-anywhere CSV (or most anything else) headers. What you've proposed cannot. I would prefer you transform them, but I can understand if you don't like eg mineral_homologous_series (in which case we'll probably need to rethink some forms/apps).

**Comment by sharpphyl** [comment]
Can we do a separate table for minerals?

**Comment by Jegelewicz** [comment]
Makes sense - how difficult to use the term mineral_homologous_series, but have it appear in the UI as mineral homologous series (or for this one "homologous series" probably makes more sense)?

I could be persuaded to just drop the "mineral", which fixes them except for the homologous_series term. However, might be confusing sharing terms with Linnean taxonomy (family, species, variety)?

@Nicole-Ridgwell-NMMNHS @sharpphyl @mbprondzinski @dperriguey

**Comment by dustymc** [comment]
>separate table 

Sure - but it's ~months of development and will result in something more than double the amount of code to maintain. The model was designed to accommodate whatever anyone might throw at it, I see little reason to do anything else - what am I missing?

>but have it appear in the UI 

Weeks not months, and without the doubling of the codebase, but still not "insert and use."

>confusing sharing terms with Linnean taxonomy 

Why would anyone care; why not just use the existing terms for this?

**Comment by mbprondzinski** [comment]
Can we do a "trial file" using the Linnean taxonomic system and see if it can be easily adapted or not?

**Comment by Jegelewicz** [comment]
> Why would anyone care; why not just use the existing terms for this?

Possibly no one will notice...I guess there is one way to find out.

I will await comments from @Nicole-Ridgwell-NMMNHS @sharpphyl @mbprondzinski @dperriguey on whether to drop mineral from the term names.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I am ok with just dropping mineral. It seems like it will mostly matter in searching and I don't think it is too difficult to figure out that you can search for both linnean species and mineral species using "species"

**Comment by Jegelewicz** [comment]
See revised request above.
