### ISSUE TITLE
Validation of mineral names

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3077]
@dustymc since we are "validating" mineral names to ensure they are not dupes and that they don't include any characters other than the ones we have specified, can we change the message received upon validation?

![image](https://user-images.githubusercontent.com/5725767/91761269-d5531a80-eb91-11ea-84cf-eef1e56daaec.png)

Maybe "name will load, no validation available from external resources"?

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/arctos/issues/3055#issuecomment-684004943_

**Comment by Jegelewicz** [comment]
Also, the validation table prepared for Linnean names is not useful when viewing mineral names.

![image](https://user-images.githubusercontent.com/5725767/92001754-4e6e8100-ecfc-11ea-91be-2844fe896cf4.png)

**Comment by dustymc** [comment]
"validation" is external as described in the inline documentation

>
	<p>
		You should <a href="BulkloadTaxonomy.cfm?action=validate">validate</a> before loading. The validation service queries various sources
		for the name. It fails, often, with both false positives and false negatives. You are solely responsible for the names you create.
		Only records with NULL status will be validated. You may need to reload a few times; the external services can be slow.
	</p>


>Maybe "name will load

I don't check that at this stage, it just loads or fails a bit later on

>the validation table prepared for Linnean names is not useful when viewing mineral names.

Sure it is - that one found https://www.wikidata.org/wiki/Q2846390

**Comment by Jegelewicz** [comment]
> 
>     the validation table prepared for Linnean names is not useful when viewing mineral names.
> 
> Sure it is - that one found https://www.wikidata.org/wiki/Q2846390

Woah! You are correct! That's pretty cool...

**Comment by Jegelewicz** [comment]
@dustymc for some of the mineral higher classification names we need to be able to include "and" as in "Aluminosilicates of Ca and alkalis" which is a Hey's CIM primary group name. Suggestions on how best to do this and not create havoc later (someone adding "Gold and Hematite" as a name rather than an "and" identification)?

**Comment by Jegelewicz** [comment]
Also, not sure if we included commas in the symbols that will pass in mineral names, but I will need them too....

**Comment by dustymc** [comment]
Those would definitely trip the "looks like identification" checks, which exist because people REALLY like to create identifications as taxonomy. 

A link to a reliable machine-readable source could be used to mitigate, if there is a such a thing.

**Comment by Jegelewicz** [comment]
> A link to a reliable machine-readable source could be used to mitigate, if there is a such a thing.

I wish. I have copied all from Mindat - but they will charge us $ to link.  I will put all with the offending terms aside and perhaps you can load them all at once or will that still break stuff?

**Comment by Jegelewicz** [comment]
Also, in test, this name won't load

Quartz var. Tiger's Eye

I think because of the apostrophe? I thought we added that to the list of acceptable symbols for mineral taxa?

**Comment by dustymc** [comment]
I refreshed the check function in test, that should pass.
```
arctosprod@arctosutf>> select isValidMineralTaxonName($$Quartz var. Tiger's Eye$$);
 isvalidmineraltaxonname 
-------------------------
 valid
(1 row)
```

How certain are you that that's "taxonomy"? Sorta looks like "Canis lupus var. lapdog," which botanists might consider to be taxonomy but mammalogists certainly wouldn't. At the very least we probably need some documentation attempting to draw a line between taxonomy and identifications for minerals.

**Comment by Jegelewicz** [comment]
I was going with this - anyone can help me out if that's a bad choice!

https://www.mindat.org/min-3337.html#autoanchor25
