### ISSUE TITLE
Data download - separators

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#3078]
When I down load data with multiple OTHERCATALOGNUMBERS, they used to (prior to PG?) all be concatenated with a semicolon. Now, each record is different; some are separated with a comma and some are separated with a semicolon. This messes with my post-download data processing procedures. It's not something I can't deal with, but it is annoying. I don't see any pattern that would suggest why some get the comma and some get the semicolon. The PARTS are all concatenated with semicolons, so I'm not sure what's up with OTHERCATALOGNUMBERS. Standardizing this would be greatly appreciated. 

[ArctosData_15CB6924A6.zip](https://github.com/ArctosDB/arctos/files/5163929/ArctosData_15CB6924A6.zip)

**Comment by dustymc** [comment]
The delimiter is currently comma-space. It's not very surprising if I've mucked it up while postgresifying things - sorry! I can change it back to semicolon and/or flag things to rebuild - let me know how I can help.

**Comment by acdoll** [comment]
Either way is fine with me. It's just weird that it was doing both. Thanks
