### ISSUE TITLE
Code Table Request - New part names for ES collection - crystal

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3080]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Goal**
Appropriately describe mineral parts

**Context**
geosample is too vague

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name

**Value**
crystal

**Definition**
a solid material whose constituents (such as atoms, molecules, or ions) are arranged in a highly ordered microscopic structure, forming a crystal lattice that extends in all directions. Excludes polycrystals such as rocks. [Wikipedia](https://en.wikipedia.org/wiki/Crystal)

**Collection type**
ES

**Attribute data type**
N/A

**Attribute value**
N/A

**Attribute units**
N/A

**Part tissue flag**
No

**Other ID BaseURL**
N/A

**Priority**
Please assign a priority-label.

**Comment by Jegelewicz** [comment]
See concern at #3081 

crystal = a solid material whose constituents (such as atoms, molecules, or ions) are arranged in a highly ordered microscopic structure, forming a crystal lattice that extends in all directions. Excludes polycrystals such as rocks.

geosample = sample of material from the Earth's crust

Again, it seems like all crystals are also geosamples.

**Comment by Jegelewicz** [comment]
With regard to the above and #2423, maybe we should treat "crystal" and "rock" (see #3081) as "geosample type" attributes of the part "geosample".

We can make use of existing vocabulary! See http://ldweb.ga.gov.au/def/ont/ga/igsn/igsn.html#MaterialType

Unfortunately, I can't open any of the links on this page, so I cannot find the vocabulary....

**Comment by Jegelewicz** [comment]
Finally got to this: https://app.geosamples.org/reference/materials.php

**Comment by Jegelewicz** [comment]
Other useful lists may be here as well https://www.geosamples.org/help/vocabularies

**Comment by dustymc** [comment]
No input on the terminology, but I do still like the trend of generalDiscoverableThing as part_name and specificMaybeObscureThing as a "sub-part" part attribute. That could be more data in https://arctos.database.museum/info/ctDocumentation.cfm?table=CTPART_ATTRIBUTE_PART or a/several new similar table(s).

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Having geosample as part name and rock/crystal as part attributes would be the biological equivalent to having "organism" as the only part name and everything else as an attribute. I'm not in favor of putting rock/crystal in an attribute. What is the point of having parts in geology if we're going to throw everything under the same part name?

**Comment by dustymc** [comment]
Thanks. I'm thinking closer to ``footbone`` as part with ``3rd`` ``distal`` and ``phalange`` somehow _attributed_. Anything equivalent to ``skull`` ``humerus`` ``organism`` etc. should be "primary."

**Comment by Jegelewicz** [comment]
So should the things listed in that vocabulary be part names?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
We might eventually need to add some of those. Do we add them now, before they are necessary, or wait until someone actually needs them? If we do add them, I would simplify the list slightly:
Gas
Liquid
Mineral
Rock
Sediment
Soil

I've been going back and forth on whether to use mineral or crystal. I think I'm finally convinced to just use mineral because it will be more straightforward for searching.

**Comment by dustymc** [comment]
>wait until someone actually needs them?

Always my preference.

**Comment by Jegelewicz** [comment]
OK, cool. So for now we add the following?

Mineral - A solid chemical compound with a fairly well-defined chemical composition and a specific crystal structure, that occurs naturally in pure form. https://en.wikipedia.org/wiki/Mineral
Rock - Any naturally occurring solid mass or aggregate of minerals or mineraloid matter. https://en.wikipedia.org/wiki/Rock_(geology)

Change all "crystal" parts to "mineral" in the part bulkload, then load remaining parts?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Yes

**Comment by Jegelewicz** [comment]
mineral added

**Comment by dustymc** [comment]
This is lost https://arctos.database.museum/name/Mineral, should not have been created, and needs moved to a disentangled state.

Data:
[temp_min.csv.zip](https://github.com/ArctosDB/arctos/files/14483592/temp_min.csv.zip)

Summary:

```
---------------+-------
 NMMNH:Geol    |  1162
 TCDGM:Mineral |   839
 UAM:ES        |     2
 ALMNH:Paleo   |     2
 ALMNH:Geo     |     8
```

Contacts:


 @Nicole-Ridgwell-NMMNHS
 @ufarrell
 @aklompma

**Comment by dustymc** [comment]
@ufarrell thanks, yes that's very useful.

Because of how the taxonomy is shaped, I think the most consistent approach to that is probably to use https://arctos.database.museum/name/Mineral in the identification, and https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#object (or maybe https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#geosample, or even https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#unknown) as the part. Basically,

1. This is a mineral (because identification)
2. There's something physical (part exists), and
3. Everything we can say about the physical thing is already said by the identification (so generic part name).

There's definitely some blurry (at least for me...) line somewhere between identifications and parts for a lot of nonbiological stuff, I'm not suggesting that any of that's any sort of "how it should be done," I just think it's the most consistent approach (eg one that might provide one path to finding all similar material) - unless someone has a better view of that line, of course.

I'm happy to update things when and if anything starts looking workable.

**Comment by Jegelewicz** [comment]
I would modify @dustymc answer:

use https://arctos.database.museum/name/Mineral in the identification, and https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#geosample

**Comment by ufarrell** [comment]
Ok, sounds good - I updated them all to 'geosample', keeping Mineral as the ID - let me know if any issue. A follow up question - if I have a mineral that IS identified, should the part type also be 'geosample'?

**Comment by Jegelewicz** [comment]
>  if I have a mineral that IS identified, should the part type also be 'geosample'?

Yep!

**Comment by Jegelewicz** [comment]
I changed the two ALMNH:Paleo

https://arctos.database.museum/guid/ALMNH:Paleo:10662
https://arctos.database.museum/guid/ALMNH:Paleo:10711

and removed mineral from their part list, but I don't have access to ALMNH:Geol. @babogan can you change those two or allow me access and I will?

**Comment by Jegelewicz** [comment]
@Nicole-Ridgwell-NMMNHS see https://github.com/ArctosDB/arctos/issues/3080#issuecomment-1976829444

Can we change your part names to geosample?

**Comment by ufarrell** [comment]
> > if I have a mineral that IS identified, should the part type also be 'geosample'?
> 
> Yep!

Ok done!

**Comment by ufarrell** [comment]
> This is lost https://arctos.database.museum/name/Mineral, should not have been created, and needs moved to a disentangled state.
> 

This caused me a bit of confusion - I think you meant  https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#geosample should not have been created? Just in case its confusing anyone else!

**Comment by dustymc** [comment]
No, https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#mineral - created from https://github.com/ArctosDB/arctos/issues/3080#issuecomment-726268552 - but see also https://github.com/ArctosDB/arctos/issues/3080#issuecomment-1989102092, I'm not so sure we don't have three ways of saying "IDK."

**Comment by ufarrell** [comment]
Hah, yes, I edited - having confused myself! In any case....ID fine, part name not fine is what I am taking away and I will go about my business with geosamples!

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I'm mostly on board with this, except that the classification isn't quite there to support this. See https://arctos.database.museum/search.cfm?guid_prefix=NMMNH%3AGeol&part_name=%3Dmineral vs https://arctos.database.museum/search.cfm?guid_prefix=NMMNH%3AGeol&taxon_name=mineral&part_name=%3Dmineral

**Comment by Jegelewicz** [comment]
Updated classifications to include Kingdom = Mineral

- [ ] Heys CIM (via Arctos)
- [ ] Nickel-Strunz 10 (via Arctos)
- [ ] Dana 8 (via Arctos)

**Comment by Jegelewicz** [comment]
@Nicole-Ridgwell-NMMNHS test this again?

**Comment by Jegelewicz** [comment]
Nevermind, I still have to deal with varieties....

**Comment by dustymc** [comment]
@Nicole-Ridgwell-NMMNHS can you help me resolve this? Is there some list of names which need a term added? Does anyone know where the Heys CIM (via Arctos) data came from- eg is there a csv that I might modify and reload? @mkoo know anything about any of this?

**Comment by Jegelewicz** [comment]
> know where the Heys CIM (via Arctos) data came from

https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxonomy_source#heys_cim__via_arctos_

**Comment by mkoo** [comment]
in order to resolve this issue, @Nicole-Ridgwell-NMMNHS @dusty should meet to work out the clean-up issues. New part names is not going to resolve the current state. I can schedule a meeting separate from CT meetings

**Comment by dustymc** [comment]
@Nicole-Ridgwell-NMMNHS here are the taxa which don't have a 'mineral' term in the classification and use a 'mineral' part. I do not have sufficient knowledge to do anything about this. (I suppose I could start yet another 'rocks-n-dirt' classification that just says 'mineral' for these, but that seems somewhere between dumb and evil...) 

[temp_min_tax.csv](https://github.com/user-attachments/files/16642437/temp_min_tax.csv)


Any sort of number in the has_... columns indicates there's something in a classification that your collection uses, NULL==there's no classification. Not sure that's helpful at all...

If you don't have time to deal with this, I'll suggest bulkloading a less-accepted identification of 'mineral' to retain the functionality until someone can make the taxonomy more consistent. Happy to help with that, let me know.

Here's the list of GUIDs in the part search and not taxonomy, in case that's useful.

[temp_mineral_misses.csv](https://github.com/user-attachments/files/16642447/temp_mineral_misses.csv)

**Comment by mkoo** [comment]
@Nicole-Ridgwell-NMMNHS Nudging to see if you wanted DB help as Dusty offered or perhaps you've already taken cared of the taxonomic identifications? 

Please update so we can close or revisit! This issue is about ready to start kindergarten....

**Comment by dustymc** [comment]
This issue is actively creating more data to clean up (wildfire label was appropriate) I'm changing part==mineral to geosample and removing the source of denormalization.

Here are the involved records:

[temp_formerly_mineral.csv.zip](https://github.com/user-attachments/files/18894420/temp_formerly_mineral.csv.zip)
