### ISSUE TITLE
Code Table Request - new part name for ES collections - rock

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3081]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Goal**
Appropriately describe mineral parts

**Context**
geosample is too vague

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name

**Value**
rock

**Definition**
any naturally occurring solid mass or aggregate of minerals or mineraloid matter [wikipedia](https://en.wikipedia.org/wiki/Rock_(geology))

**Collection type**
ES

**Attribute data type**
N/A

**Attribute value**
N/A

**Attribute units**
N/A

**Part tissue flag**
No

**Other ID BaseURL**
N/A

**Priority**
Please assign a priority-label.

**Comment by Jegelewicz** [comment]
My only concern is that people will be confused as to whether they should search for "rock" or "geosample". It seems like all geosamples would also be rocks.

rock = any naturally occurring solid mass or aggregate of minerals or mineraloid matter
geosample = sample of material from the Earth's crust

Do we need to specify "not from the Earth's crust" for rock?

**Comment by dustymc** [comment]
Pandora rocks?!

**Comment by Jegelewicz** [comment]
Moon rocks, silly.

**Comment by Jegelewicz** [comment]
added
