### ISSUE TITLE
catalog results -> manage... -> related / Publications fails

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#3082]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

The drop down menu 'Manage...' for catalog results should allow one to find a list of all the publications that cite those catalog records/specimens but this doesn't work.

**To Reproduce**

Search on identification = Noctua pronuba 

Many of the records have been cited in publications.

Try to find those publications using the 'Manage...' menu item.

**Expected behavior**

**Screenshots**

** Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
fixed in next release
