### ISSUE TITLE
Use of Ampersand in Higher Geography

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3083]
Are we consistently using ampersands in higher geography?
Right now we are using one for Turks & Caicos Islands, all geography.
I suggest replacing with "and".

**Comment by Jegelewicz** [comment]
I agree with this - the ampersand can cause issues as it makes it's way around. Also, https://en.wikipedia.org/wiki/Turks_and_Caicos_Islands says "Turks and Caicos Islands".

**Comment by Jegelewicz** [comment]
Also, These should be on the continent of North America, not "West Indies"

**Comment by campmlc** [comment]
Entering them as in the current code table, but as soon as these load, we should look at all West Indies HG.

**Comment by Jegelewicz** [comment]
See #3043

**Comment by dustymc** [comment]
https://handbook.arctosdb.org/documentation/higher-geography.html#guidelines-for-geographic-terms-in-arctos

**Comment by Jegelewicz** [comment]
> Use the spelling of geographic term that is in the title of the English version of Wikipedia’s entry for that term (but see below). Wikipedia describes most (possibly all) of the world’s current politically-delineated geographic units. Do not use something transcribed from a label or fieldnotes for a new value in Higher Geography. Look it up in Wikipedia. If it doesn’t exist, and you are sure it’s valid, create the article in Wikipedia.

**Comment by mkoo** [comment]
As per usual, doing a search for '&' shows we have quite a few replacements
to make!
I am putting this on the to-do list... but will do Turks AND Caicos first

**Comment by dustymc** [comment]
```
arctosprod@arctos>> select higher_geog from geog_auth_rec where higher_geog ~ $$[^A-Za-z0-9 ,\.\-\']$$ order by higher_geog;
                                                   higher_geog                                                   
-----------------------------------------------------------------------------------------------------------------
 Africa, Sao Tome and Principe, Autonomous Region of Príncipe, Principe
 Asia, Indonesia, Bangka–Belitung, Indonesian Archipelago
 Asia, Indonesia, Bangka–Belitung, Indonesian Archipelago, Bangka Island
 Asia, Indonesia, Bangka–Belitung, Indonesian Archipelago, Belitung Island
 Asia, Taiwan, *Taipei City, Taiwan
 Atlantic Ocean, United Kingdom, South Georgia & South Sandwich Islands, South Sandwich Islands, Kidney Island
 Atlantic Ocean, United Kingdom, South Georgia & South Sandwich Islands, South Sandwich Islands, Kipple Island
 Atlantic Ocean, United Kingdom, South Georgia & South Sandwich Islands, South Sandwich Islands, Saunders Island
 Central America, Costa Rica, Heredia, Belén
 Europe, Hungary, Csongrád County
 Europe, Switzerland, Berne Canton, Biel/Bienne District
 North America, United Kingdom, Turks and Caicos Islands, Turks & Caicos Islands
 North America, United Kingdom, Turks and Caicos Islands, Turks & Caicos Islands, Little Ambergris Cay
 North America, United Kingdom, Turks and Caicos Islands, Turks & Caicos Islands, Providenciales
 North America, United States, Arizona, Coconino County, Cameron 1:100,000 Quad
 North America, United States, New Mexico, Lincoln County, Chihuahua Ranch/Bull Gap 15 mi Quad
 North America, United States, New Mexico, San Juan County, Bisti/De-Na-Zin Wilderness
 North America, United States, Utah, Emery County, San Rafael Desert 1:100000 Quad
 North America, United States, Utah, San Juan County, La Sal 1:250,000 Quad
 South America, Colombia, Amazonas, Puerto Nariño
 West Indies, Dominican Republic, Provincia Monsenor Nouel, Greater Antilles, *Hispaniola
 West Indies, Jamaica, Saint Mary Parish, Greater Antilles, *Jamaica
 West Indies, United Kingdom, Turks & Caicos Islands, Turks & Caicos Islands, North Caicos Island
 West Indies, United Kingdom, Turks & Caicos Islands, Turks & Caicos Islands, Turks Island
(24 rows)
```

**Comment by mkoo** [comment]
Well, the ampersand is also in the Island Group dropdown so cannot edit
that from my end.
We should talk about continents soon too

**Comment by dustymc** [comment]
>Island Group

Add a new island group, edit geography, delete the old now-unused

**Comment by Jegelewicz** [comment]
Not sure what to do about those quad maps....

**Comment by Jegelewicz** [comment]
Also Bisti/De-Na-Zin Wilderness is the actual name https://en.wikipedia.org/wiki/Bisti/De-Na-Zin_Wilderness

I could leave out the "/" and the "-" but that seems really wrong.

**Comment by Jegelewicz** [comment]
Fixed  South America, Colombia, Amazonas, Puerto Nariño

**Comment by dustymc** [comment]
> quad maps

That query is finding the colon - if that's desirable and documented you can just ignore them. I'm tempted to suggest we add a character control trigger but we also REALLY need to emphasize the importance of reading documentation so ????????????

>seems really wrong.

And there's the problem of attempting character control! It's impossible to tell the difference between something officially named "this/that" and someone attempting to assert uncertainty in an inappropriate place.

**Comment by Jegelewicz** [comment]
OK, cool. Maybe this should be a once a year review or something just to check for crazy stuff?

**Comment by dustymc** [comment]
>crazy stuff

https://handbook.arctosdb.org/documentation/higher-geography.html#map-name-quad

Suggest standardizing quad, probably to 1:nnnn. At least one (Soldiers Farewell Hill 7.5 min) is abbreviated as well.

**Comment by Jegelewicz** [comment]
Some quads were abbreviated because they were too long.

**Comment by dustymc** [comment]
>too long

```
arctosprod@arctos>> alter table geog_auth_rec alter column quad type varchar(60);
ALTER TABLE
```

**Comment by dustymc** [comment]
@mkoo you created "Asia, Taiwan, *Taipei City, Taiwan" - the authority suggests it might be a copy of Asia, Taiwan, New Taipei City, Taiwan - what's the intent?


@mvzhuang I fixed Central America, Costa Rica, Heredia, Belén - please see https://handbook.arctosdb.org/documentation/higher-geography.html#guidelines-for-geographic-terms-in-arctos "No accents, umlauts, Cyrillic, Chinese, etc. Do use ASCII-128."

**Comment by Jegelewicz** [comment]
@dustymc thoughts on what needs to be done here?

**Comment by dustymc** [comment]
I'll clean up, update documentation, and close.
