### ISSUE TITLE
Request new menu navigation for Data Services and pre-bulkloader

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#3087]
Under the menubar navigation **Reports/Services**, there's confusion about **Data Services** and its submenu items. This will help new collections (and old users!) find the tools they need for data migration.

Request that the current **Data Services** is split into two: **Data Services** and **Data Clean-up**
with some clean up of the submenu items.

Current submenus and the proposed change:

![Screen Shot 2020-09-03 at 3 18 03 PM](https://user-images.githubusercontent.com/2523089/92179029-bd310480-edf8-11ea-89f3-932ade62656a.png)

Move to **Data Clean-up**:
- Agent Deconcatenator
- Agent Namestring Formatter
- Agent Name Splitter
- Date Formatter
- Find/Replace Nonprinting characters
- Higher Geog Lookup
- Scientific Name Checker
- Taxon Name Validator

Keep the rest under **Data Services** except for the following:

Remove:
- [Coordinate Formatter](https://arctos.database.museum/DataServices/coordinate_splitter.cfm) - goes nowhere fast
- [Find HG from Specific Locality](https://arctos.database.museum/DataServices/getGeogFromSpecloc.cfm) - sounds cool, why is there an error message? If it's not working, remove; if it;s suppose to work, let me know and I will file its own issue!

Also, if PreBulkloader is not really working right now (and these services can functionally replace them) please update the  menubar link and remove the link for the Pre-Bulkloader: Enter Data-> Bulkloader - > Pre-Bulkloader 

Others @Jegelewicz @campmlc weigh in if I missed something

**Comment by dustymc** [comment]
>Find HG

https://github.com/ArctosDB/arctos/issues/2874

>PreBulkloader is not really working right now 

It's not?

>and these services can functionally replace them

They're entirely different things, although pre-bulkloader occasionally provides data that these services can refine and return.

**Comment by mkoo** [comment]
OK, separate issues though from people finding things--  this issue is really about navbar changes. (for the record, I am messenger here!) Let's make the tools easy for people to find/remember

**Comment by Jegelewicz** [comment]
Prebulkloader not working see #3089

**Comment by campmlc** [comment]
Pre-bulkloader is now working enough to do a first run through of bulkload data and provide feedback on agents, geography, sci names, attribute values etc not in Arctos. Needs use and testing. It would also be good to have some of these tools made available separately in Data Services as described above.
