### ISSUE TITLE
New Tool Request: Parts and Attribute Look Up tool! 

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#3088]
Like the Lookup tool for Higher Geography, Agents, etc, we need a Parts and Attribute look up tool! 
The purpose would be to check in bulk whether Arctos already has a code table value for a given part. 

What functional details do you need to know for this?
- collection-type
- part
- attribute

Please add to this barebones description! @Jegelewicz @ewommack @campmlc @ccicero

**Comment by dustymc** [comment]
Parts and attributes are very simple data. Geography and agents aren't. Happy to think about cleaning other stuff, but I'd need some example data or specific details or something.

**Comment by campmlc** [comment]
This tool exists in pre-bulkloader, but it isn't working. Can we fix for PG?

**Comment by campmlc** [comment]
Here is a short test file for the pre-bulkloader.  This file was downloaded directly from the bulkloader - so it has the usual issues that will need to be cleaned up prior to re-bulkload. See #3062. 
[BulkPendingData_CB780FCE00.zip](https://github.com/ArctosDB/arctos/files/5171824/BulkPendingData_CB780FCE00.zip)

**Comment by Jegelewicz** [comment]
I had never ventured into the prebulkloader, but it seems like it was an excellent tool that no one ever explained to me when I was originally migrating data, so I started using the tools in Data Services, some of which only sorta do what is needed for data checking.

@dustymc we don't need to be asking you to clean stuff all the time, we just need tools whereby we can load a list of stuff in our data, have it compared to code tables in Arctos and return results of the term exists, the term doesn't exist. While the addition of a "maybe you mean this" would be nice, it can wait for when we have more programmers and time. Right now, here is what I use:

Agents - [Agent Name Splitter](https://arctos.database.museum/DataServices/agentNameSplitter.cfm) (while this does let me know if the Agent name exists, it also throws a bunch of extended info that I have to parse through to figure out who exists, who might exist and who doesn't - still, it works)

Taxonomy - [Scientific Name Checker](https://arctos.database.museum/DataServices/SciNameCheck.cfm) (tells me if the name is in Arctos or not, yay!)

Higher Geography - I was just eyeballing this stuff, but was made aware of [Higher Geography Lookup](https://arctos.database.museum/DataServices/geog_lookup.cfm) which I intend to try as soon as I have another set of data to work on)

Parts - I've just been relying on my personal knowledge. It would be great to just create a list of unique part names in legacy data and run it past the code table to see if the part name exists.

Attributes - see Parts

We could keep getting into the weeds with all of the other attribute categories (part attributes, locality attributes, event attributes), and we should eventually, but the above tools would make migrating a bunch of legacy data into Arctos much easier and would ease the burden on both you and incoming collection mentors as incoming collections' staff could just do the work themselves (and get comfortable with Arctos more quickly).

**Comment by dustymc** [comment]
Thanks, that helps.

A check if exists tool could be fairly quick, where trying to figure out intention usually isn't, and in this case I don't think would work very well (our parts are weird and arbitrary, everyone else's parts are differently weird and arbitrary), plus most new collections have comparatively few parts so it wouldn't save much time even if it was magic. It'd still be cool, but doesn't seem like something we could prioritize in the next while.

Maybe a generic check_if_exists that takes three columns ``cttable_name, collection_cde, value`` and adds a 4th ``exists(boolean)`` would be a bit more bang for very little extra work.

I have functions that take attribute (of various types) data objects and check validity, they could probably be turned into webservices without too much work.

I think all of that functionality is built into the check all function in the pre-bulkloader; new tools wouldn't add anything, but they'd make just dealing with one thing at a time easier.

Agent Name Splitter is really meant to deal with "you and me" type agents, and it's probably more clutter (and some possibility of introducing new errors) than you need for "you, but spelled 500 ways" agents. The agent bulkloader has a bunch of checking, maybe it should be two tools or something of the sort.

Higher Geography Lookup and Find Higher Geography from Specific Locality (which also seems to not have survived the PG move) have probably saved me actual years of work - and they're a big part of why I'm so paranoid about good geography (and locality), both are useless without consistent and predictable data to back them up.

We clearly need better documentation.

If that sounds reasonable then this can probably go next task, and needs prioritized.

**Comment by Jegelewicz** [comment]
> Maybe a generic check_if_exists that takes three columns cttable_name, collection_cde, value and adds a 4th exists(boolean) would be a bit more bang for very little extra work.

Love it

> I have functions that take attribute (of various types) data objects and check validity, they could probably be turned into webservices without too much work.

Also love this

> I think all of that functionality is built into the check all function in the pre-bulkloader; new tools wouldn't add anything, but they'd make just dealing with one thing at a time easier.

Agree - As I said, I've never used this, but I can only imagine the number of issues in some of the data I have worked with recently and how overwhelming the results would have been....

> Agent Name Splitter is really meant to deal with "you and me" type agents, and it's probably more clutter (and some possibility of introducing new errors) than you need for "you, but spelled 500 ways" agents. The agent bulkloader has a bunch of checking, maybe it should be two tools or something of the sort.

I'd love something just like
> generic check_if_exists that takes three columns cttable_name, collection_cde, value and adds a 4th exists(boolean) 
although I realize Agents are a bit more difficult and a "could be" column would probably be super-useful.

> Higher Geography Lookup and Find Higher Geography from Specific Locality (which also seems to not have survived the PG move) have probably saved me actual years of work - and they're a big part of why I'm so paranoid about good geography (and locality), both are useless without consistent and predictable data to back them up.

Had I used the Lookup even once, I am certain I would have been sold and would make sure everyone uses it!

> We clearly need better documentation.
Hoping to do this with both the steps in the data migration repository and some related How-To's/tutorial bites.

**Comment by dustymc** [comment]
"Find Higher Geography from Specific Locality" is now functional

**Comment by dustymc** [comment]
Under data services in next release.
