### ISSUE TITLE
prebulkloader not working

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3089]
![Screenshot 2020-09-03 17 33 28](https://user-images.githubusercontent.com/14808196/92183477-c7a8c980-ee0b-11ea-828b-5109ae12a031.png)

Sample file to use to test:

[BulkPendingData_CB780FCE00.zip](https://github.com/ArctosDB/arctos/files/5171866/BulkPendingData_CB780FCE00.zip)

**Comment by campmlc** [comment]
Error from: Push to prebulkloader in:
![Screenshot 2020-09-03 17 35 56](https://user-images.githubusercontent.com/14808196/92183548-fb83ef00-ee0b-11ea-82de-d48258f55d46.png)

**Comment by dustymc** [comment]
thx fixed

**Comment by campmlc** [comment]
I now can get file to load, but mark for precheck doesn't seem to do anything. Tried with the test file of 3 records - no status change, nothing in lookup table. I've loaded another test file of 500 records which I know have problems. Still no change in status.
![Screenshot 2020-09-04 10 15 36](https://user-images.githubusercontent.com/14808196/92262359-39c6f000-ee98-11ea-93ca-d2024de2a063.png)

**Comment by Jegelewicz** [comment]
go_go_Gadget! HAHAHAHAHAHA!!!

**Comment by dustymc** [comment]
>Grab a donut. It'll take a while.

You can always check scheduled tasks for a more precise number - it's currently hourly.

**Comment by campmlc** [comment]
Can we state explicitly that the check is hourly? That isn't exactly
conducive to any reasonable workflow, but if that is what it is, it is
important to know. I thought it was based on the number of records, e.g 3
records should be faster than 500. Nothing happened in either case, so I
was concerned.

**Comment by campmlc** [comment]
Can I delete from bulkloader stage while waiting for precheck in prebulkloader? Also a  good thing to clarify in the interface.

**Comment by campmlc** [comment]
Where is check scheduled tasks? Never heard of it.

**Comment by campmlc** [comment]
Another important piece of info to add to UI instructions - to see when data are ready, periodically refresh browser to see change in status; or grab a copy of your data here and look in loaded column.

**Comment by dustymc** [comment]
> state explicitly that the check is hourly?

Not realistically under current resources - I mess with schedules when something's threatening to die or etc all the time, I won't remember to also go change some text in some form. (I could potentially pull that information from the scheduler itself, but that's going to have costs and limitations as well.)

>3 records should be faster than 500.

It is, but not to a point you might notice. Short version is "we have resource limitations" (slightly longer is "and so low-demand things are designed to consume minimal resources") - I can expand on that in /internal if you want to start an issue over there, and perhaps we can eventually find the hardware to do something about that, but a more intensive schedule isn't very realistic now.

>delete from bulkloader stage while waiting for precheck in prebulkloader

They're completely separate things, so yes.

>Where is check scheduled tasks? N

In developer tools with all the other scary admin stuff
