### ISSUE TITLE
Change redirect on delete from bulkloader stage

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3090]
Can we change the language and link at the following prompt:
![Screenshot 2020-09-03 17 43 00](https://user-images.githubusercontent.com/14808196/92183985-1b67e280-ee0d-11ea-82d8-ca80319af16d.png)
![Screenshot 2020-09-03 17 42 56](https://user-images.githubusercontent.com/14808196/92183993-228ef080-ee0d-11ea-9278-367146effb92.png)

So that it directs users to Browse and Edit - which is the next logical step - instead of back to the bulkloader?
There is no other obvious way that we currently have to let operators know what they are supposed to do next after they delete their records from the staging table. 
As another improvement, we also could use an explanation as to what they are doing and why when we ask them to delete from the staging table.

**Comment by Jegelewicz** [comment]
OOOOOH! Yeah! That would be really great! However, students might not have access to Browse and Edit.

How about this:

Deleted
Back to Bulkloader
Approve Records for Load

**Comment by campmlc** [comment]
Sounds good. Little edit - big results!!

**Comment by campmlc** [comment]
Or maybe let's swap the order - we need to clarify that just because you
got to this point, you aren't done. . .

"Records successfully deleted from bulkload stage.
Next step: Go to Browse and Edit
<https://arctos.database.museum/Bulkloader/browseBulk.cfm> to review and
approve records to load to Arctos.
or
Back to Bulkloader
<https://arctos.database.museum/Bulkloader/BulkloadSpecimens.cfm> to
continue bulkloading records.

**Comment by Jegelewicz** [comment]
I edited the above a bit - change if you don't like it!

**Comment by dustymc** [comment]
Bare links would result in a bunch of confused users and even more junk in my error logs. That should be implemented as:

```
<cfif isdefined("session.roles") and listfindnocase(session.roles,"manage_collection")>
	only manage collection users can see this
</cfif>
```

@Jegelewicz feel free to just edit the code, or I'll get it eventually, probably.

**Comment by Jegelewicz** [comment]
See https://github.com/ArctosDB/PG/commit/b8b6b9edb08c839940623dd845f0b9db096d17c2

**Comment by Jegelewicz** [comment]
I think this is working now. @campmlc let me know if it isn't.
