### ISSUE TITLE
Code Table Request - Nomenclatural codes = Getty AAT

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3091]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Goal**
Cultural collections are planning to use classifications from the Getty Art and Architecture Thesaurus. We would like to be able to easily find and distinguish between cultural collection classifications.

**Context**
Designating classifications taken from Getty with a specific nomenclatural code would distinguish those classifications from any that are biological as well as any from Nomenclature 4.0

See an example Getty AAT term in [aventurine glass](https://arctos.database.museum/name/aventurine%20glass)

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctnomenclatural_code

**Value**
Getty AAT

**Definition**
Getty Art & Architecture Thesaurus provides structure and classification schemes that can aid in documentation.

**Collection type**
EH, Arc

**Attribute data type**
N/A

**Attribute value**
N/A

**Attribute units**
N/A

**Part tissue flag**
N/A

**Other ID BaseURL**
N/A

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
I use nomenclatural code to do things like format display name; it's functional. "...and if it's any of these 30 things, do nothing" would be awkward to work around. Recommend source_authority for this purpose, unless there is in fact some Code-equivalent of which I'm not aware.

**Comment by Jegelewicz** [comment]
K - I was waffling on using the two - that makes perfect sense.
