### ISSUE TITLE
Object tracking weirdness

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#3092]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

This container (a slide box, barcode=C78846) shows very different contents between this view:

https://arctos.database.museum/allContainerLeafNodes.cfm?container_id=12421795
![container contents2](https://user-images.githubusercontent.com/9099827/92284286-27f04780-eeae-11ea-8405-d298315ebd5f.png)

why are the labels so different between these views?

and this view
https://arctos.database.museum/EditContainer.cfm?container_id=12421795
![container contents1](https://user-images.githubusercontent.com/9099827/92284514-97fecd80-eeae-11ea-9cd2-f2627e912ead.png)

But the real weirdness involves 2 specimens with barcodes that have been scanned into that slide box container and show up in that container in some searches, but not others.

This barcode is in that container UAM100087361

![UAM100087361](https://user-images.githubusercontent.com/9099827/92283666-db583c80-eeac-11ea-8c12-57a266647453.png)

but it's not in the first of the prior views (but is in the 2nd) and doing a catalog record search with anybarcode = C78846 fails to find it

The same problem occurs with barcode UAM100087358

**To Reproduce**

**Expected behavior**

**Screenshots**

** Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label.
High

**Comment by DerekSikes** [comment]
hmmm... yes, now I'm finding those 2 barcodes... 

But what about the first oddness - why are the 'labels' and 'next2layes' so inconsistent in the first leafnodes view?
-D

**Comment by dustymc** [comment]
Ah - got it, you have list delimiters in your labels - I changed the list delimiter, hopefully that won't break anything else.

**Comment by DerekSikes** [comment]
Thanks!

**Comment by campmlc** [comment]
What is a list delimiter?
