### ISSUE TITLE
Mineral Taxonomy - in Test

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3093]
@dustymc I am playing around with the four kinds of mineral taxonomy in test. When trying to add a taxon term, I get the following error:

term = 1 : Elements and Alloys (including the arsenides, antimonides and bismuthides of Cu, Ag and Au)
![image](https://user-images.githubusercontent.com/5725767/92304761-21a9ac00-ef3e-11ea-8900-3de25c57f72c.png)

Error:
An error occurred while processing this page!
Message: ERROR: is not in CTTAXON_TERM Where: PL/pgSQL function trigger_fct_trg_taxon_term_cts() line 13 at RAISE
Detail:
Check the Arctos Handbook for more information on errors.

This message has been logged as B72047D2-94E1-4B4F-B8D77EFBB4382FA2 Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue.

It seems like we cannot add unranked terms? Because as soon as I add a rank to the terms, it works....

**Comment by Jegelewicz** [comment]
Dang it - thwarted at every step! I tried adding a new taxon term = hey's_cim

then when I go to edit a taxon, I get this

An error occurred while processing this page!
Message: Encountered "s_cim" at line 2, column 31. Was expecting one of: "," ... ")" ... "+" ... "-" ... "*" ... "||" ... "/" ... "**" ...
Detail:
Check the Arctos Handbook for more information on errors.

This message has been logged as 5E249280-43A8-428D-A90EB66B1D028D9D Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue. 

So I try to delete the offending new term and IT WILL NOT GO AWAY!

**Comment by Jegelewicz** [comment]
Dang it! I tried adding a new non-classification term = hey's_cim but when I try to edit a classification I get this error

An error occurred while processing this page!
Message: Encountered "s_cim" at line 2, column 31. Was expecting one of: "," ... ")" ... "+" ... "-" ... "*" ... "||" ... "/" ... "**" ...
Detail:
Check the Arctos Handbook for more information on errors.

This message has been logged as 3A9C0D0C-552E-42FF-842FCCBCAFE1988C Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue. 

So I tried to delete the offending new term and it will NOT GO AWAY!

**Comment by dustymc** [comment]
Yes I think the current UI somehow gets wonky with unranked "local" terms - I'm sure there's an issue somewhere....

Terms are still set up to work as CSV headers - the apostrophe will break lots of interesting things.

**Comment by Jegelewicz** [comment]
> the apostrophe will break lots of interesting things.

Can you get rid of that for me so that I can continue setting up my demo in test?

**Comment by dustymc** [comment]
gone

**Comment by Jegelewicz** [comment]
Trying to add terms to http://test.arctos.database.museum/Admin/CodeTableEditor.cfm?action=editTaxTrm&tbl=cttaxon_term in test to help with the discussion in #3110 but after adding one, now get this error:

An error occurred while processing this page!
Message: ERROR: duplicate key value violates unique constraint "iu_taxonterm_relpos" Detail: Key (relative_position)=(999999999) already exists.
Detail:
Check the Arctos Handbook for more information on errors.

This message has been logged as F13C8EE2-71A9-47BB-9A446B32599FEAD0 Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue. 

attempting to add heys_secondary_group

**Comment by dustymc** [comment]
Note: new classification terms will insert into the bottom of the hierarchy. EDIT THEM AFTER YOU CREATE!

**Comment by Jegelewicz** [comment]
Set up mineral taxonomy terms for heys index, dana and strunz in test. See example for [Copper taxonomy](http://test.arctos.database.museum/name/Copper) and as [identification](http://test.arctos.database.museum/guid/NMMNH:Paleo:1).

> Note - IDs haven't refreshed, so this might look dumb until they do

Only downside to this is that these terms will probably confuse biologists and the biology terms will probably confuse the geologists (maybe?). Also, when adding a new mineral classification, the "requirement" for a Kingdom and that any single term name will also prompt a "required" genus is super-frustrating. Removing these triggers will make biological classification more susceptible to errors, so not sure what to do there.

I also set up "rock" taxonomy using biologic term types (not going to work) for [Fulgurite](http://test.arctos.database.museum/name/Fulgurite) just to demo how a given taxon can have multiple classifications and how it would look in [identification](http://test.arctos.database.museum/guid/NMMNH:Paleo:100000). We can handle this with term types like "rock_group_1" but then we will never want anyone to search for all the "Contact metamorphic glassy rock" in rock_group_3, because in some classifications, that term may fall into rock_group_2. As an example, Shell marl has the following classifications:



ROCK_TERM | TERM_TYPE | ROCK_GROUP_1 | ROCK_GROUP_2 | ROCK_GROUP_3 | ROCK_GROUP_4 | ROCK_GROUP_5 | ROCK_GROUP_6 | ROCK_GROUP_7 | ROCK_GROUP_8
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
Shell   marl | rock species | Rock | Sedimentary rock and sediment | Sediment | Clastic-sediment | Mud | Lime-mud | Marl | Shell marl 
Shell marl | rock species | Rock | Sedimentary rock and sediment | Carbonate sediment | Lime-sediment | Lime-mud | Marl | Shell marl |  
Shell marl | rock species | Rock | Superficial deposit | Biological deposit | Shell marl |   |   |   |  

Anyway, this will give @ArctosDB/taxonomy something to look at and consider as we discuss #3110

**Comment by dustymc** [comment]
>Copper taxonomy

Why put a bunch of classifications under one source? I think that's essentially an end point - you can use it or not, that's about it. Those data would be a lot more flexible if they were organized as three sources.

>refreshed

https://github.com/ArctosDB/internal/issues/65

>confuse biologists 

Only if they're managing in a tool that doesn't produce consistent data anyway - https://github.com/ArctosDB/arctos/issues/1698. I'm hoping the ability to have multiple sources per collection will lead to a better place.

We've had a mix of ICZN and ICBN terms forever, they don't seem to get too much obvious abuse, so maybe these won't either.

>that term may fall into rock_group_2.

That's confusing. Recommend getting rid of the ranks altogether (if we can figure out how to make the necessary tools work without them).

**Comment by Jegelewicz** [comment]
> 
>     Copper taxonomy
> 
> Why put a bunch of classifications under one source? I think that's essentially an end point - you can use it or not, that's about it. Those data would be a lot more flexible if they were organized as three sources.

Just testing here - not trying to create the perfect answer but present possibilities. While to some degree I agree with you, there may be a collection who wishes to make use of more than one source. Combining them provides users with access to all three types of mineral classifications in the catalog record. Dynamic sources will only use the first one as all of these will have classifications for all of the minerals.


> 
>     confuse biologists
> 
> Only if they're managing in a tool that doesn't produce consistent data anyway - #1698. I'm hoping the ability to have multiple sources per collection will lead to a better place.

Yes, but the code table values are all in one place and when creating a classification, all are available to anyone no matter what type of name they are creating a classification for. It will just mean more scrolling through the list of term types when creating a classification manually (probably not many people do this, but it will be an issue).

>     that term may fall into rock_group_2.
> 
> That's confusing. Recommend getting rid of the ranks altogether (if we can figure out how to make the necessary tools work without them).

Yes, it is for Rocks that being able to use some sort of unranked term multiple times would be good - I think we can do that now. I'll play around with it. But will break the classification loader....

**Comment by Jegelewicz** [comment]
@Nicole-Ridgwell-NMMNHS please take a look at this stuff in test. I plan to walk everyone through it during our taxonomy committee meeting on Wednesday at 2PM (Please join us if you can - Arctos Zoom Room).

[Fulgurite](http://test.arctos.database.museum/name/Fulgurite)
[Copper](http://test.arctos.database.museum/name/Copper)

Let me know if something is missing or looks crazy.

**Comment by mbprondzinski** [comment]
What is "quarantine" taxa????

**Comment by Jegelewicz** [comment]
> What is "quarantine" taxa????

They include things like misspellings that are out in the world, but should not be used in identifications.

**Comment by mbprondzinski** [comment]
Ahh, okay thanks!

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Source name should be Arctos Rocks and Minerals.

I would recommend leaving out the unclassified rock categroy that is in Mindat. They define that category as groups that can fit into 2 or more categories, but then they also put them under the individual categories, so it is just another repeat of something that is already repeated. In the case of fulgarite, glassy rocks can be either igneous or metamorphic, so they put a glassy rocks group under igneous, under metamorphic, and under unclassified.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
When we add the dana, I wonder if we work in the old groups the way this website does: http://webmineral.com/danaclass.shtml#.X2DuFIt7nIU

**Comment by Jegelewicz** [comment]
> Source name should be Arctos Rocks and Minerals.

Check! Will do when we get to adding this for real.

> When we add the dana, I wonder if we work in the old groups the way this website does: http://webmineral.com/danaclass.shtml#.X2DuFIt7nIU

We can add both if that will be helpful. So one classification could have the "dana_8th-ed" term and the other could have the dana_7th_ed term (or whatever that "old" version is called). I'll add an example in test.

**Comment by dustymc** [comment]
>Just testing here - not trying to create the perfect answer but present possibilities. While to some degree I agree with you, there may be a collection who wishes to make use of more than one source. Combining them provides users with access to all three types of mineral classifications in the catalog record. Dynamic sources will only use the first one as all of these will have classifications for all of the minerals.

The elegant/most-capable solution would be a whole bunch of sources...

* this thing
* that thing
* other thing, 1st edition
* ...
* other thing, 347½th edition
* this thing plus that thing
* all the things merged together into a big all-encompassing blob

... from which a collection could prefer "this thing" or "this thing plus that thing" or "all the things" (="Arctos Rocks and Minerals"), all in any order.

Managing that (particularly the merge-variants) doesn't sound like too much fun, though.

**Comment by Jegelewicz** [comment]
> Managing that (particularly the merge-variants) doesn't sound like too much fun, though.

Probably not as bad as it sounds since these taxonomies don't change as much as biological ones and they tend to change in one fell swoop, not minute-by-minute.
