### ISSUE TITLE
Attribute won't validate

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3094]
Yesterday I added the "value" attribute to ES collections. I am able to add value attributes to NMMNH:Geol records manually, but the bulkload tool is telling me that "value" is an invalid attribute.

![image](https://user-images.githubusercontent.com/5725767/92305438-9e3f8900-ef44-11ea-94ee-ee035f3c8ca9.png)

**Comment by Jegelewicz** [comment]
![image](https://user-images.githubusercontent.com/5725767/92306112-fd53cc80-ef49-11ea-96c7-4c30c49ebe41.png)

**Comment by dustymc** [comment]
data, link, ??

**Comment by Jegelewicz** [comment]
[Mineral value.zip](https://github.com/ArctosDB/arctos/files/5178268/Mineral.value.zip)

Stuff is still in tool. https://arctos.database.museum/tools/BulkloadAttributes.cfm

**Comment by dustymc** [comment]
need units

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_code_tables&field=value

**Comment by Jegelewicz** [comment]
DOH!!!!! Man, I should not work on Saturday mornings....
