### ISSUE TITLE
Media loader stuck on rename confirmed

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#3096]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Media loader has been stuck on rename confirmed for three weeks

**To Reproduce**
1. load media files in "upload images"

**Expected behavior**
To rename and finish job in a few days

**Comment by dustymc** [comment]
In next release; needs confirmed to work.

**Comment by mvzhuang** [comment]
ok just checked my job and its' now stuck on fatal error. Should I reupload the image batches?

**Comment by dustymc** [comment]
No don't reload yet, I'd like to figure out what's going on.

**Comment by dustymc** [comment]
@mvzhuang can you send me a zip - looks like the janitor cleaned up when things were stuck...

**Comment by mvzhuang** [comment]
ok i think i sent it to your email, because github is getting mad at me

**Comment by dustymc** [comment]
@mvzhuang the zip loader should once again be working. Here's your CSV - it's missing a couple checksums, you can generate them from Arctos after you load if you want, or whatever. There's no thumbs - it was still getting hung up on that - Arctos should magic them in after you create media.

[media_bulk_zip280304129.csv.zip](https://github.com/ArctosDB/arctos/files/5284824/media_bulk_zip280304129.csv.zip)

**Comment by mvzhuang** [comment]
sounds good. thanks! ok so reload stuff not in the CSV and the other job I had in there?

**Comment by dustymc** [comment]
yup

**Comment by mvzhuang** [comment]
Woohoo!

On Sep 25, 2020 2:02 PM, dustymc <notifications@github.com> wrote:

yup
