### ISSUE TITLE
Request to have all CFR files synced to a github branch here

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#3097]
Don't we have git installed on the TACC/Arctos server? Can we have a synced directory on github or a separate branch that has all the currently uploaded reports? That could serve as back up and a way to check out cfr files without downloading each report/label separately. (I know I've brought this up before but I cannot remember why in the Oracle days we didnt do this so I'm filing a reminder as something to make curator life a wee bit easier)

Alternatively, maybe give users a way to download more than one report as a time.

**Comment by dustymc** [comment]
It's a great idea but I think it would be a fair bit of work, and we're running deprecated code under antique software on a server that should have been retired a while back. I'm not sure investing that work in this system is a good use of our limited resources.

https://github.com/ArctosDB/internal/issues/37

>Alternatively, maybe give users a way to download more than one report as a time.

Done.

<img width="245" alt="Screen Shot 2020-09-10 at 3 45 03 PM" src="https://user-images.githubusercontent.com/5720791/92818522-a7818900-f37c-11ea-9631-4dee822a5e21.png">

**Comment by mkoo** [comment]
We can open a fresh issue when we make more widespread upgrades to include git.
Meanwhile I'm using the new download button to populate a new repo for easy storage of files: https://github.com/ArctosDB/arctos-assets
First folder is a download of all the CFR reports! All, feel free to add new folders/ backups but will periodically update with  snapshots from that link.
