### ISSUE TITLE
Make the Taxon Name Validator Tool Better

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3101]
Tool in question - https://arctos.database.museum/DataServices/taxonNameValidator.cfm

MSB and HWML are collaborators in the multi-institutional NSF-funded Terrestrial Parasite Tracker TPT- TCN, and we are in the process of uploading large numbers of ectoparasite records to Arctos.  Many of the taxon names are not yet in Arctos, and many are missing classifications or lacking in taxonomic categories and authorities. The TPT project has provided standardized flea, louse, and tick/mite taxonomic names and classifications available as csv files that could be loaded to Arctos, and MSB and HWML would like to be able to take advantage of these lists. 
Question:
1) Should these be uploaded as a separate source, e.g Arctos (TPT)?
2) Alternately, if HWML and MSB - the two primary parasite collections in Arctos- agree to use these classifications and authorities, can we replace the existing Arctos classification, which in most cases was created entirely ad hoc?
3) Is it better to just load the names separately to meet the needs of pending bulkload efforts, and wait on loading classifications and other metadata, or can all be loaded at once (see 1 above)
4) What is the a) easiest and b) cleanest way to go about the process of getting these names and classifications loaded to Arctos?

[TPT Taxonomy for Arctos.zip](https://github.com/ArctosDB/arctos/files/5197875/TPT.Taxonomy.for.Arctos.zip)

**Comment by dustymc** [comment]
>uploaded as a separate source

Absolutely.

> e.g Arctos (TPT)?

Definitely not the name I'd pick - it's both yet another "Arctos" thing, which seems to confuse everyone, and has a cryptic abbreviation - but it's also just a string, so whatever....

>replace the existing Arctos classification,

There are lots of reasons to avoid using any of the giant "legacy" classifications, and no benefit to doing so - this is a problem easily avoided. If you must, you really need to spend the time to KNOW what you're replacing so we don't end up with a bunch of "parasites" in unrelated marine invertebrate collections or similar. 

> can all be loaded at once 

No, there are separate loaders.

>easiest

Just use the loaders.

>cleanest

That's mostly a human problem - taxonomy itself is a mess, we have a separate role for good reason, this really needs someone familiar with the taxonomy pushing the buttons.

**Comment by campmlc** [comment]
OK, so not sure how to load as a separate source - I'd need instructions. I
see the csv taxon name bulkloader - I can do that. But, how to load to a
separate source? And the classification bulkloader says " This tool
required a re-build and is in the queue for repairs. Sorry for any
inconvenience."
I would prefer to have someone more familiar with Arctos taxonomy tools
pushing the buttons or guiding me through this.

**Comment by dustymc** [comment]
>how to load as a separate source

Create a source, use it in the classification bulkloader.

>taxon name ... separate source

Source is an attribute of classifications, not names. (Maybe that's the major point of confusion?)

>queue for repairs

Yes that issue (and a few hundred more...) needs prioritized.

>guiding

I'm happy to do that. First step is to prepare CSV for the name loader, then you can feed the appropriate bits of it to the name checker and name validator services.

At the same time you can create a new source via the normal CT issue path.

**Comment by campmlc** [comment]
Submitted issue #3103 to request new classification source.
I could not find documentation specifying what the steps are for this
process.

Next steps - do I load names only - after feeding through Taxon Name
Checker first - and then deal with classifications later? If I load names,
how do they end up in the right place?

What does " the appropriate bits " mean?

**Comment by campmlc** [comment]
Additional questions:
1) For the Bulkload Taxon Names tool, what are the terms for Name Type?
Documentation?
2) Do I load all names, including higher classification above genus, with
this tool, or do I wait and load them with the subsequent
classification load?

**Comment by campmlc** [comment]
Found answer to first question :
https://arctos.database.museum/Admin/CodeTableEditor.cfm?action=editNoCollectionCode&tbl=cttaxon_name_type

We should add this to the template form instructions at
https://arctos.database.museum/tools/BulkloadTaxonomy.cfm

Ok to load names of higher taxonomy with this tool?

**Comment by dustymc** [comment]
>2) Do I load all names, including higher classification above genus, with
this tool, or do I wait and load them with the subsequent
classification load?


That's why this needs a taxonomist. It varies wildly across datasets, in most cases some of them will be names (which could be loaded) and some will be garbage made up for some weird reason.

Also depends on your plans for managing classifications. (There's been some talk of using source to control that - probably at least worth adding to the proposed definition.)

I think this is all in https://handbook.arctosdb.org/documentation/taxonomy.html - certainly should be if it's not.

**Comment by campmlc** [comment]
These are all vetted names coming from a supposedly vetted source - TPT.
Unfortunately, there is no mechanism for auto-updates a la Worms.
I would like to load all scientific names as well as higher taxonomy from
this source - and will do so with this tool if that is acceptable.

**Comment by campmlc** [comment]
Ran list through Sci Name Checker. Deleted all valid.
Ran list of all FAIL names through Sci Name Validator (any reason why
header is taxon_name here instead of scientific_name?

For documentation purposes - this tool returns only 90-100 names at a time
- timeout error at bottom says to use browser refresh to go to next set.
Requires user to copy each return and paste to a spreadsheet, as next
refresh will overwrite all but the last returned name from the previous
list. Each refresh takes several minutes. For my 1000 name test file, would
have been good idea to have coffee on hand and a chunk of time set aside.

I plan to filter results for "consensus='might_be_valid' ", load those
using Bulkload Taxonomy Names; and then check any "probably_not_valid"
separately.

**Comment by campmlc** [comment]
Correction - Sci Name Validator only returns results for 40-50 names every
several minutes. Get a really big cup of coffee. . .

**Comment by Jegelewicz** [comment]
> Sci Name Checker. Deleted all valid. Ran list of all FAIL names through Sci Name Validator (any reason why header is taxon_name here instead of scientific_name?

Checker just looks to see if the name is in Arctos

Validator runs the name against the Global Names sources and returns whether it seems to be a "valid" taxon (as opposed to just a name that meets the rules for a biological name) or not...

**Comment by dustymc** [comment]
>vetted names coming from a supposedly vetted source 

Yea, so is eg WoRMS, and I reject tons of their "names." "Taxonomy things" - including Arctos - all seem to have their own ideas of what's taxonomy and how it should be organized, this could be what looks like a giant mess to us even if there's not a single thing they'd consider a mistake. (I scrolled through your CSV, it actually looks really good to me, we'll see if the machines agree!)

>there is no mechanism for auto-updates

http://globalnames.org/ 

> scientific names as well as higher taxonomy

I'm still not sure we're on the same page with that....

>why header is taxon_name here instead of scientific_name

Evolution.

>really big cup of coffee

That (along with most loaders) should be rebuilt so that it can be wired into the scheduler, that just needs prioritized. You'll need even more coffee then, but you won't have to hang around to drink it all at once.

Alternatively you could skip the validation - it's not THAT good under the best of circumstances, this seems to be coming from a reliable source, and GBIF or wikidata having never heard of a parasite name may be close to meaningless here. Your call - I certainly can't evaluate the quality of this, other than the random-to-me strings all seeming to more or less follow the same pattern.

**Comment by campmlc** [comment]
So of the 1000 approx names of fleas I ran through the validator, 7 were
flagged as probably not valid, but I found citations for 5 of those. One
was a misspelling, and one seemed to be a subspecies name attached to the
wrong genus. So at least those two problems won't go back out into the
world from the Arctos direction - I'm sure other TPT partners are loading
them.
When I subsequently loaded all but those two names to Arctos, I found one
with an invalid character - a trailing " ' ", but Arctos seemed to have
caught it and fixed it, because the name loaded, although it broke the
script and I had to start over to find out what names had loaded and what
had not before the break (rerun through Sci Name Checker) - which was a bit
of a pain.

**Comment by campmlc** [comment]
Any way to do a quicker work around of running names through the validator?
I'm happy to use it to catch errors like I described above, but I really
don't want to spend an hour per load clicking refresh every few minutes,
and then having to copy paste and clean up a messy excel file with names
and status on alternate rows that can't be sorted . . .

**Comment by Jegelewicz** [comment]
> Any way to do a quicker work around of running names through the validator? [...] I really don't want to spend an hour per load clicking refresh every few minutes, and then having to copy paste and clean up a messy excel file with names and status on alternate rows that can't be sorted . . .

@dustymc possible to have this run in the background and deliver a csv when it is done?

I ran a list of 73 names. The tool finished up with 45 of them:

![image](https://user-images.githubusercontent.com/5725767/99412061-8f187800-28b1-11eb-8280-0f14e78c48df.png)

Then I ended up with this:

> An error occurred while processing this page!
> Message: request /DataServices/taxonNameValidator.cfm (/usr/local/webroot/DataServices/taxonNameValidator.cfm) has run into a timeout (timeout: 60 seconds) and has been stopped. The thread started 60002ms ago.
> Detail:
> Check the Arctos Handbook for more information on errors.
> 
> This message has been logged as 2AD02D48-9AD6-4712-9F78FC71E486A574 Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue. 

If this could take it's sweet time and then offer up a csv when it was done, that would be much better. See attached example of csv results that would be useful.
[Taxon name checker results example.zip](https://github.com/ArctosDB/arctos/files/5554608/Taxon.name.checker.results.example.zip)

**Comment by dustymc** [comment]
Certainly not until whatever it is that we're waiting on over in https://github.com/ArctosDB/arctos/issues/2974 happens.

Then, sure, but those data are all pretty flaky, and the services are pretty slow, and I hear rumors that GN has something that's NOT slow in the works, so it would need prioritized accordingly.

**Comment by Jegelewicz** [comment]
@campmlc have your TPT names/classifications been loaded? Can I help if not?

**Comment by dustymc** [comment]
@Jegelewicz have you used whatever validator globalnames has? Can we just direct to it or does the current multisource validator need component loader-ized?

**Comment by Jegelewicz** [comment]
I have not used the GlobalNames validator. For simplicity sake - and if it is possible, 

> current multisource validator need component loader-ized?

would be something Arctos users would be familiar with.

If I get some free time this week, I can try toe GlobalNames thing and report back.

**Comment by Jegelewicz** [comment]
GN thing returns a report - not necessarily useful data.

![image](https://user-images.githubusercontent.com/5725767/188751741-029e8b56-e47e-46f5-a0d6-f7a903418dc0.png)

BUT you can limit the review to a single source to make it simpler - still it is a long and verbose report...

**Comment by Jegelewicz** [comment]
@campmlc @dustymc where are we at with this?

**Comment by campmlc** [comment]
I think we were discussing ways to minimize the coffee consumption?
https://github.com/ArctosDB/arctos/issues/3101#issuecomment-690065232

**Comment by dustymc** [comment]
My question is whether we can do "better" than GN, or if we can just use their service. Long and verbose seems good to me - this isn't something that should be approached lightly. On the other hand, the "local" report is known to have passed things like song names - it almost assuredly leads to situations in which a whole bunch of people spend a whole bunch of time fixing something that would have been caught by spending an extra 5 seconds with a more verbose report.

If we do componentloaderify the local report, maybe it should also be a bit more verbose - I'm not sure it'll ever be quite as nice/focused as GN's, but it can report status from the various sources if checks.

**Comment by Jegelewicz** [comment]
Verbose reports lead to the same problems we have had trying to decide if agents match or not. Reading hundreds of lines of not-really-formatted-the-same comments is just not going to be helpful. Not because there is bad information there, but because nobody has time to read all of that. If we can get something structured that offers assistance in decision-making, then let's do it. Otherwise we are just building a toll that will frustrate everyone and will not get used properly.

**Comment by Jegelewicz** [comment]
Here are our choices for this tool as I see them:

1. Use it the way it is - get your coffee and spend the day with it when you really need it.
2. Figure out how to have it run in the background and create a csv that I can get later (or component-loaderize it)
3. Dump it and have people use the [GlobalNames Verifier](https://verifier.globalnames.org/)

I would be curious to know how often this tool gets used. I have pretty-much given up on it. For names that fail in the Taxon Name Checker, I just do my own research, then add them if they are "accepted" with whatever caveats are required (synonym of, etc). If I were being honest with myself, I wouldn't even trust the names that pass the Name Check tool - there are plenty of misspellings and nonsensical things in there already. It really does take some research to decide if a name should be used, but even more to decide if it should be added, so if we keep this tool, I think it should have an output more like the Agent Prebulkload Tool.

This does seem like a situation where a tool exists and we don't have to maintain it. It seems like recommending the [GlobalNames Verifier](https://verifier.globalnames.org/) is a good idea.

**Comment by Jegelewicz** [comment]
I am going to change directions in the data migration tools to use https://verifier.globalnames.org/

I suggest we remove this tool from the Tool Directory as it is currently not working

<html><body>


ERROR_ID | E32E9119-8CBE-403F-AED5EACE63C15E7A
-- | --
ERROR_TYPE | expression
ERROR_MESSAGE | The key [GNI] does not exist, only the following keys are available: [CONSENSUS, EOL, GBIF, WIKI, WORMS, ZOOBANK].
ERROR_DETAIL |  


</body>
</html>

And I don't think we need to maintain it since people can use https://verifier.globalnames.org/

**Comment by Jegelewicz** [comment]
removed from tools - closing

**Comment by Jegelewicz** [comment]
Actually, @dustymc could I add https://verifier.globalnames.org/ to the tools? Make a new tile - "External Tools" or just put that thing in Data Services?

**Comment by Jegelewicz** [comment]
I'd just do it, but I don't want to break anything :-)

**Comment by dustymc** [comment]
>add https://verifier.globalnames.org/ to the tools?

No

>closing

Please don't, unless you've cleaned up the code?!

**Comment by Jegelewicz** [comment]
> cleaned up the code

I'll let you do that

> no

OK - I'll leave it on me to update any documentation. I am already guiding incoming collections to just use https://verifier.globalnames.org/ to figure out if names that aren't in Arctos are "any good".

**Comment by Jegelewicz** [comment]
@dustymc do you want to add something about checking names with https://verifier.globalnames.org/ on https://arctos.database.museum/editTaxonomy.cfm?action=newName before adding them?
