### ISSUE TITLE
inconsistent geography

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3102]
Inconsistent geography means the "get geography from specloc" tool (and probably others) doesn't work as well as it could.

I'm not sure that this can lead to rules - some big localities really do pass through multiple geography, names get re-used, etc., etc., etc. Still, at least thousands of records just don't adhere to documentation. Can we somehow do better?

```
create table temp_specloc_multigeo as
select 
spec_locality,
string_agg(higher_geog,'; ') as geogs
from (select 
  spec_locality, 
  higher_geog
 from
geog_auth_rec inner join locality on geog_auth_rec.geog_auth_rec_id=locality.geog_auth_rec_id
group by spec_locality ,higher_geog) s
group by spec_locality having count(*) > 1;
```

[temp_specloc_multigeo.csv.zip](https://github.com/ArctosDB/arctos/files/5198014/temp_specloc_multigeo.csv.zip)

**Comment by Jegelewicz** [comment]
/remind me to review this on Monday.

**Comment by dustymc** [comment]
More fun

```
select 
  spec_locality,
  higher_geog
from
  geog_auth_rec inner join locality on geog_auth_rec.geog_auth_rec_id=locality.geog_auth_rec_id
where
  upper(spec_locality) like '%NATIONAL PARK%' and
  feature is null
group by
  spec_locality,higher_geog
order by
  higher_geog,spec_locality
  ;
(6451 rows)

```

**Comment by Jegelewicz** [comment]
I'm blowing this off while Erica works on stuff.
