### ISSUE TITLE
Feature Request - cultural taxononomy control

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3104]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
There are two cultural items in test, ``Basket`` and ``bucket``. Can we enforce better consistency?

** Describe what you're trying to accomplish** 
An clear and concise overview of the goals; why are you asking for this?

random Case IS AnnOYing and Not verY SearchablE.

**Describe the solution you'd like**
How might we accomplish your goals?

If authority data allow consistent case, enforce it. If they do not, add documentation.

**Describe alternatives you've considered**

**Additional context**

**Priority**
Please assign a priority-label.

High - if this is a preventable, we should address it before it requires a major cleanup effort.

**Comment by Jegelewicz** [comment]
@AJLinn @marecaguthrie @krgomez

**Comment by AJLinn** [comment]
Remind me - is this the right place to go for test: http://arctos-test.tacc.utexas.edu/

**Comment by dustymc** [comment]
http://test.arctos.database.museum/

There's nothing that really needs testing here, I just need to know if there's any way we might limit what can be entered as a cultural name, or if "some unicode characters" is as good as it gets.

**Comment by Jegelewicz** [comment]
closing - I'm not sure we can do anything about this - but the new taxonomies might help....
