### ISSUE TITLE
Delete part: error feedback

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#3106]
We catalog many/most specimens prior to preparation with a part of 'whole organism (frozen)'. Previously, we had volunteers entering the prep data one record at a time, changing the parts to the resulting skin, skeleton, tissue, etc. Without volunteers, I'm trying to do this in bulk using the batch tools. I added the new parts to about 80 specimens using the batch tool "Bulkload Parts". I then tried to remove the 'whole organism (frozen)' part from the results page using the Manage... -> Modify Parts tool. When I try to delete, I get this error:
_Message: ERROR: triggercaught:::no access to Where: PL/pgSQL function trigger_fct_trg_container_content_control() line 173 at RAISE SQL statement "DELETE FROM container WHERE container_id = OLD.container_id" PL/pgSQL function trigger_fct_tr_collobjconthist_ad() line 3 at SQL statement
Detail:
Check the Arctos Handbook for more information on errors.
This message has been logged as 69ACB314-199D-4E99-A6084F994C165984_ 

I get the same error when I try to delete the part individually from the specimen record page.

**Comment by dustymc** [comment]
Should be patched, thanks.

**Comment by acdoll** [comment]
It works now. Thanks
