### ISSUE TITLE
create container series instititution acronym not recognized

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3109]
Used the create container series tool in object tracking; downloaded template and added data.

[CreateContainerTemplate.zip](https://github.com/ArctosDB/arctos/files/5211887/CreateContainerTemplate.zip)

Tried to load file, got following error. Checked there were no trailing spaces; confirmed this series is reserved for MSB.

![Screenshot 2020-09-11 17 52 53](https://user-images.githubusercontent.com/14808196/92981636-fbad6b80-f457-11ea-8ce9-239ab4a3ee28.png)

**Comment by dustymc** [comment]
<img width="347" alt="Screen Shot 2020-09-14 at 6 56 10 AM" src="https://user-images.githubusercontent.com/5720791/93094971-67a9f280-f657-11ea-9d5e-3d160b916ca2.png">
