### ISSUE TITLE
Browse and Edit in Test

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3111]
Trying to add some test data. Entered record manually, but Browse and Edit gets me this

![image](https://user-images.githubusercontent.com/5725767/93140123-25a49f00-f69f-11ea-9295-2c38a7da1995.png)

**Comment by dustymc** [comment]
works for me....

**Comment by Jegelewicz** [comment]
I get that error as soon as I open http://test.arctos.database.museum/Bulkloader/browseBulk.cfm

![image](https://user-images.githubusercontent.com/5725767/93148101-3f9aad80-f6b0-11ea-8620-b60b7248d124.png)

DataTables warning: table id=bedit - Ajax error. For more information about this error, please see http://datatables.net/tn/7

**Comment by dustymc** [comment]
try customizing - I probably didn't flush test with the last updates. I'll need your JS console dump if that doesn't work

**Comment by Jegelewicz** [comment]
Customizing didn't work. How do I get JS console dump?

**Comment by dustymc** [comment]
Google "javascript console {your browser} {your OS}" - or I could steal your account for a bit if you don't mind resetting your password when I'm done.

**Comment by Jegelewicz** [comment]
> I could steal your account for a bit if you don't mind resetting your password when I'm done.

I'm cool with that.

**Comment by dustymc** [comment]
You're customized to just a couple of columns and it works. It's something about the server environment, but I can't figure out exactly what. I don't think there's an easy fix without something like https://github.com/ArctosDB/internal/issues/64

You'll need to recover your password.
