### ISSUE TITLE
Make "private" localities preferred when user is an Arctos operator with appropriate permissions

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3112]
We held a training for NMMNH curators today and I noticed that search results show the "public" locality even when the searcher is an operator with appropriate access to view the "access private" locality.

![image](https://user-images.githubusercontent.com/5725767/93148768-edf32280-f6b1-11ea-9a76-20c15222a0cd.png)

This information is not useful to the curators who are doing research in the collection. This is also strange to me because the "public" localities are all unverified while the "private" ones are accepted - I would think that accepted localities would be preferred in the search results (assuming one has access to the private localities)?

In any case, is there a way that search results can prefer the "access private" locality when an Arctos operator is searching?

**Comment by dustymc** [comment]
I think that's just about as far from "trivial" as you can get without encountering "impossible"....

Ideally this would be part of a post-SABI discussion about performance and caching in general. We could probably do something less revolutionary, but I think it would be a fair bit of work and carry a significant computational cost.

**Comment by Jegelewicz** [comment]
HMMMM. That really makes searching at the main search by curators next to useless when private localities are used. There are even larger issues as curators will want to search by multiple parts/attributes as well. I think we are going to need a discussion about public vs. curatorial searches. We have all of this fabulously detailed information and no way for those who created it to get at it in interesting ways without being able to write SQL or wait for someone to do it for them.

**Comment by dustymc** [comment]
>discussion about public vs. curatorial searches.

That's welcome, a discussion about smashing things that won't fit into tables into tables might be more productive. (There MUST be a better way of presenting complex data, but I don't know what it is.)

> write SQL

Turn JSON locality on, and we could talk about what that looks like - perhaps even a step in the "stop trying to cram everything into a table" direction.

**Comment by Jegelewicz** [comment]
> Turn JSON locality on, and we could talk about what that looks like

Yeah, that's what I do - but we definitely need to figure out a way to make that more useable in a download situation.

> - perhaps even a step in the "stop trying to cram everything into a table" direction.

But what is that? I agree with the idea that there should be a better way (visual representations - but those are still created from tables...). Could a set of tables be the answer?

**Comment by dustymc** [comment]
>Could a set of tables be the answer?

That's been the answer for organizing/managing complex relational data for the last several decades. I'm not sure if extending that normalization to UI is taboo only because tradition, or because it really does make for cruddy UI.

I also suggest we shouldn't readily dismiss the idea of radical UI redesign. The tradition of using tables for visualization comes (in part) from a time when databases were essentially big tables; we now have radically different data stores, perhaps we need radically different UIs in front of them.

**Comment by Jegelewicz** [comment]
Not disagreeing with that, but don't know how it should look....

**Comment by dustymc** [comment]
tabling - I don't (yet!?) have a technically viable solution to offer
