### ISSUE TITLE
Feature Request - Remarks for Std. Meas. (mamm) 

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#3113]
The display format for standard measurements (Std. Meas.), which I believe is only used in mammal collections (?), hides potentially useful data. Determiner, date, method and remarks are all hidden from any public users and only viewable through the Edit tool for operators. I believe we should leave the display table as it is, but see three ways of making that additional data available:
1) have it appear beneath the table, indented and grayed as with all the other attributes:

total length | tail length | hind foot | efn       | weight
132 mm       | 38 mm     | 18 mm     | 14 mm | 19 g
        _Andrea Marie Carrillo, 2020-08-03
	total length: remark: tail broken
	weight: remark: wet weight_

One problem with this would be if different measurements in the table were taken by different Agents or on different dates. I would suggest that, at the least, any/all remarks be displayed in this manner.

2) have the Std. Meas. table be 'expandable' which would just toggle it to display like the rest of the attributes.

3) have a Details pop-up like in the Parts box that shows all of the Attribute data in a new window.

**Comment by dustymc** [comment]
Can we just get rid of the "if mamm" table?

**Comment by cjconroy** [comment]
I agree that remarks should be shown, but MVZ convention for mammals is to put problem data into the Unformatted Measurements attribute. I think people are just going to download all the standard measures and use for whatever purpose whether they have a remark saying "docked" or whatever. The Unformatted Measurement field can hold anything, so we write things like 'total length: [115], tail: [15]. Tail docked. "  This attribute shows up on the screen.

**Comment by dustymc** [comment]
Prioritizing - this is more than remarks, this...

<img width="379" alt="Screen Shot 2021-04-28 at 12 04 52 PM" src="https://user-images.githubusercontent.com/5720791/116459026-28ad6380-a81a-11eb-81e4-017bc2e5f0c3.png">

displays as....

<img width="674" alt="Screen Shot 2021-04-28 at 12 06 34 PM" src="https://user-images.githubusercontent.com/5720791/116459068-35ca5280-a81a-11eb-9b51-14a719425fe4.png">

any immediate objections to

1. getting rid of the "if Mamm" table, and
2. displaying all attributes in a table with columns (attribute, value+units,determiner,remark, method)

**Comment by campmlc** [comment]
I support this.

**Comment by acdoll** [comment]
We're OK with letting it go. I like the idea of a table view also.

**Comment by Jegelewicz** [comment]
YAY! lose some complexity!!

**Comment by dustymc** [comment]
In next release.

"Normal"

<img width="463" alt="Screen Shot 2021-04-29 at 8 00 29 AM" src="https://user-images.githubusercontent.com/5720791/116572646-04f12880-a8c1-11eb-8a3f-eca2397199f5.png">

Lots of attributes

<img width="698" alt="Screen Shot 2021-04-29 at 8 01 03 AM" src="https://user-images.githubusercontent.com/5720791/116572749-16d2cb80-a8c1-11eb-934b-d37b1021c3b7.png">

verbose remark

<img width="686" alt="Screen Shot 2021-04-29 at 8 01 40 AM" src="https://user-images.githubusercontent.com/5720791/116572864-2ce08c00-a8c1-11eb-944f-2714daab648e.png">

**Comment by Jegelewicz** [comment]
This needs to be applied in data entry as well.
![image](https://user-images.githubusercontent.com/5725767/116594900-f36b4900-a8df-11eb-9d22-474b852ca98e.png)
