### ISSUE TITLE
Unable to delete code table term

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3115]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I accidentally entered "octahedral " in the https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcrystal_habit code table. I have added "octahedral" but I cannot delete the term with the trailing space.

**To Reproduce**
1. https://arctos.database.museum/Admin/CodeTableEditor.cfm?action=editNoCollectionCode&tbl=ctcrystal_habit
2. Click on 'delete' next to "octahedral "
3. Scroll down 
4. See "octahedral " still there.

**Expected behavior**
After deleting, the term should no longer appear in the code table.

**Screenshots**

** Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
I nuked octahedral% - not sure what that was, but not a space.

While we're in there, can you form "equant, stout" without the comma? Those melt various things, but not to the point where I've got around to asking to ban them. I probably will eventually, might save some work then if it can be avoided now.

**Comment by Jegelewicz** [comment]
Deleted it - seemed like a duplicate of cubic anyway....
