### ISSUE TITLE
Locality Pick Bug- empty pick window

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#3116]
I dont see this bug reported anywhere but has anyone else had this problem?! 

**Describe the bug**
When trying to choose a new locality for a Collecting Event, the search pop-up appears, let's you input some parameters, but the resulting window is blank. Evidence below:

<img width="805" alt="Screen Shot 2020-09-15 at 8 46 18 PM" src="https://user-images.githubusercontent.com/2523089/93290623-fe7cc900-f795-11ea-961b-53b2797fa38b.png">

**To Reproduce**
1. Go to 'Edit Collecting Event'
2. Click on 'Pick New Locality for this Collecting Event'
3. See resulting blank pop-up window above

**Testing Clients**
 - Tried in latest versions of Chrome and FF, pop-up windows allowed, with and without other blockers

**Comment by dustymc** [comment]
Works for me - likely need details to reproduce.

**Comment by mkoo** [comment]
ugh dont tell me it's specific to the collecting event (11346331) or locality (locality ID 11026105)?!

https://arctos.database.museum/Locality.cfm?action=editCollEvnt&collecting_event_id=11346331

I'll keep picking at this

**Comment by dustymc** [comment]
https://arctos.database.museum/editLocality.cfm?locality_id=11026105

arctosprod@arctos>> select * from locality where locality_id=11026105;
 locality_id | geog_auth_rec_id | spec_locality | dec_lat | dec_long | minimum_elevation | maximum_elevation | orig_elev_units | min_depth | max_depth | depth_units | max_error_distance | max_error_units | datum | locality_remarks | georeference_source | georeference_protocol | locality_name | s$elevation | s$geography | s$dec_lat | s$dec_long | s$lastdate | wkt_polygon | last_dup_check_date | wkt_media_id 
-------------+------------------+---------------+---------+----------+-------------------+-------------------+-----------------+-----------+-----------+-------------+--------------------+-----------------+-------+------------------+---------------------+-----------------------+---------------+-------------+-------------+-----------+------------+------------+-------------+---------------------+--------------
(0 rows)


There's no such locality

**Comment by mkoo** [comment]
yes I came to the same conclusion too! I see it that 11026104 was made so I think the person didnt save this locality properly. 
Whew!
user error-- closing

**Comment by mkoo** [comment]
Also we need better error messaging-- new issue?

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/3099 - that form has a limited future.
