### ISSUE TITLE
Issues with Use Last Values

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#3119]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
When using the Use Last Values, some things are not retrieved

**To Reproduce**
For example, I am searching MVZ mammals in a map bounding box for all those with an attribute like weight greater than 1. I can do the search. But, today's chore is to do this with total length, ear length. There are 16000+ records, so I am just trying to do the search over with the same values, but swap out the attribute. 

The initial search works fine, but on Use Last Values, the attribute details I used are mostly gone, like the bounding box coordinates. It does show a single lat long in red, but not two of them, and not displayed on the map. So, I have to redraw. 

Also, under Collection, it says Select Options, but when clicking it, it shows that MVZ Mammal collections is already selected. Seems like before it showed something like 1 collection selected. 

**Expected behavior**
That pretty much anything that was search criteria will be re-populated. 

**Screenshots**

**Desktop (please complete the following information):**
 - Mac
 - Chrome
 - 84.0.4147.135

**Priority**
Medium. I can work around this.

**Comment by cjconroy** [comment]
Just did some other searches using MVZ Mamm, state = Alaska, and various attributes. Now, when using Use Last Values, the attribute field does repopulate. I then tried the bounding box again and Use Last Values and the attribute disappears. Maybe that is helpful.

**Comment by dustymc** [comment]
That has always been a bit hack-y, and it's moreso under tomcat (or perhaps just OUR tomcat - https://github.com/ArctosDB/internal/issues/64). Additionally the library that runs the results table is essentially deprecated. There's some chance I could make it work again, for a while, but I'd rather spend that time in pursuit of a more modern solution.

The current "place" search works with datatables  + our API, and does not have any POST actions or back buttons or secondary search forms that mostly-sorta work but require a huge amount of complexity. Can we just do the same thing for catalog records?

**Comment by Jegelewicz** [comment]
AWG wants an update - do we need to do something?

**Comment by dustymc** [comment]
>do something

Better infrastructure - containers for the web environment here - would make a bunch of things easier. This is one of the things that's killed tomcat, but it's not predictable - I think because of some subtlety in the OS or Java or similar - and I'd rather not nuke production.

Otherwise, decide if we should invest more work in a very old environment or update to something more modern, if the former then prioritize if the latter then plan.

**Comment by dustymc** [comment]
Why is this next task? I'm asking what to do and have no idea how to address this without that guidance.
