### ISSUE TITLE
Loan invoice no longer pulling in locality data

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#3120]
**Describe the bug**
Locality data is not displaying on my loan invoice:
UCM_loan_invoice(UCM_loan_invoice.cfr)

**To Reproduce**
1. Loan V-219: https://arctos.database.museum/Loan.cfm?action=editLoan&transaction_id=21126208
2. print...
3. UCM_loan_invoice

**Expected behavior**
Usually locality data appears. These happen to be subsamples, would this present an issue?

**Screenshots**
![image](https://user-images.githubusercontent.com/11336485/93618906-22f2c400-f995-11ea-943c-fadde7dc9818.png)

**Comment by dustymc** [comment]
There's a recipe in https://github.com/ArctosDB/arctos/issues/2729#issuecomment-658359409

A null in a PG pipe-concat returns null, where concat ignores NULLs.

**Comment by ebraker** [comment]
That'll do it, thank you!
