### ISSUE TITLE
taxonomy editor(s)

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3121]
https://github.com/ArctosDB/arctos/issues/2231 provides a means to accomplish https://github.com/ArctosDB/arctos/issues/1698 for certain Sources. A collection no longer requires one all-encompassing classification to cover everything they've cataloged, so managing Sources at smaller scales, which are much more likely to be manageable in "clean" tools (eg, hierarchies), is both possible and practical.

https://github.com/ArctosDB/arctos/issues/3110 provides a mechanism by which mostly-arbitrary data can be managed at large scales. This provides terrifying possibilities; replace all spider taxonomy in Source "Arctos" with their lichen hemihomonym classifications, for example.

The hierarchical classification editor was designed to work against non-hierarchical classifications, such as source "Arctos." Not all of "Arctos" is hierarchical, so it cannot be managed as one hierarchy, and the single-record tool virtually assures that any cleanups are immediately broken by reintroducing nonhierarchical data. This necessitates both very ugly (and not terribly effective) tools to attempt to extract hierarchical data from messy sources, and a "flattening" for human review + using the classification bulkloader to repatriate.

Suggest we add a "editors" column to https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxonomy_source, and use it to

* Disallow bulkloading to Arctos and Arctos Plants; I can see no reason anyone should ever want to do that, and lots of reasons it's a dangerous thing to attempt.
* Specify hierarchically-managed Sources; rebuild the hierarchical editor to manage them natively, and "save" directly to the Arctos taxonomy tables. Disallowing single-record edits to these Sources might make things more understandable, but if the primary data are in the hierarchical tool that would be mostly irrelevant - the probably-inconsistent edits would simply be overwritten at the next push from the hierarchy.
* Specify API-managed sources, although that's a bit like the above - it's possible to mess with single records, but they just get overwritten by the API so there's no particular reason, other than avoiding confusion, to do so.
* Perhaps flag some sources as "classification bulkloader managed" if eg someone wants to periodically replace data with an export from a desktop tool, or something of the sort.

The big functional change would be introducing truly hierarchical Sources to Arctos, and bringing the tools to manage them closer to the core (rather than hanging awkwardly off the side, as the hierarchical editor does now).

Adding assurances that the big kludgy classifications won't receive large batches of fundamentally-different data would be secondary, but we'll thank ourselves if anyone who doesn't fully understand the taxonomy model is ever granted access to the classification bulkloader.

Would anyone manage a classification hierarchically if they could?

Should I hard-code "not Arctos or Arctos Plants" into the classification loader for the time being?

**Comment by Jegelewicz** [comment]
> Disallowing single-record edits to these Sources might make things more understandable, but if the primary data are in the hierarchical tool that would be mostly irrelevant - the probably-inconsistent edits would simply be overwritten at the next push from the hierarchy.

Can we do this ONLY for the classification terms? I could definitely see how single adds to non-classification terms would be useful and necessary (I found the missing author text, or want to add a remark).

> Would anyone manage a classification hierarchically if they could?

I would - although this can be difficult when you are not familiar with the group.

> Disallow bulkloading to Arctos and Arctos Plants; I can see no reason anyone should ever want to do that, and lots of reasons it's a dangerous thing to attempt.

I can see lots of reasons someone would want to do that - they may not be good reasons from the standpoint of data quality, but they would be good reasons from the standpoint of personal efficiency. Even if we view these as the taxonomic sources of last resort, they should still be managed and without good tools to manage them, that won't happen.

> - Specify hierarchically-managed Sources; rebuild the hierarchical editor to manage them natively, and "save" directly to the Arctos taxonomy tables. Disallowing single-record edits to these Sources might make things more understandable, but if the primary data are in the hierarchical tool that would be mostly irrelevant - the probably-inconsistent edits would simply be overwritten at the next push from the hierarchy.
> - Specify API-managed sources, although that's a bit like the above - it's possible to mess with single records, but they just get overwritten by the API so there's no particular reason, other than avoiding confusion, to do so.
> - Perhaps flag some sources as "classification bulkloader managed" if eg someone wants to periodically replace data with an export from a desktop tool, or something of the sort.

This seems like a great idea as then everyone will understand how the info in any particular source is managed. Maybe each should include a link to the "managed" source or an arctos username if they are "classification bulkloader managed" for the person managing them.

**Comment by dustymc** [comment]
>ONLY for the classification terms?

yes

>without good tools to manage them, 

I'm not convinced that a tool which allows you to turn 50K spiders into lichens with a click could conceivably be described as "good." Create a new lichen Source, bulkload your "edits" there, rearrange your collection's preferences, and 

1. You've created something that some "expert" might see as manageable
1. You've taken a step away from the giant mess that we KNOW causes problems
1. You have no chance of inadvertently stepping on anyone's spider-toes

I don't think "Arctos" IS manageable, as a last resort or anything else, and it's a tiny bit of work (file an issue requesting a new Source) to avoid it.

**Comment by sharpphyl** [comment]
> Would anyone manage a classification hierarchically if they could?

I updated thousands of records with the tool when we were using Arctos as our source.  It was clunky but an improvement until we made the move to WoRMS (via Arctos).  If I were still using only the source Arctos, I'd be using the tool constantly.  It would be fine if I could only modify records for the phyla in our collection.    

> Can we do this ONLY for the classification terms? 

No, but I don't really understand what the new system would look like.  

Right now, I spend 15-25 hours a week updating (single entry) Arctos records with terrestrial species that have no WoRMS aphiaID.  I know that the higher classification is inconsistent.  If I could **easily** find all the records (for example) in Urocoptidae or at a higher level, clean up the higher classification, add authors, sources, etc. then reload them, that would be great.  Some day, WoRMS will probably catch up with fossil, terrestrial and fresh water species and we'll want to clone them into Arctos for others to use.  I do that now, but, again, it's single-record editing.  I don't think we're ready to give up that capability yet.

**Comment by Jegelewicz** [comment]
>  we'll want to clone them into Arctos for others to use.

I would never suggest that - instead I would suggest that they choose WoRMS (via Arctos) as their first taxonomy source....

**Comment by dustymc** [comment]
Yea I'm just here to agree with @Jegelewicz - I might go out of my way to avoid that thing, but certainly never to dump something on the pile now that we don't have to.

I think you have a good use case.

* do whatever magic we need to do to get most of what you want to manage more or less hierarchical
* do your thing with the hierarchical editor, at which point inconsistencies should be structurally impossible.
* occasionally push to some new classification in Arctos (which could be a button, although there's some social issues to work out)

If someone wants to use that, they can. 

If you find something in WoRMS, bulkload the 4 columns (name,source, aphiaid-pair) and your records will use that, no reason to eliminate it from "your" source or anything else.

**Comment by sharpphyl** [comment]
Before we had dynamic taxonomy, the Taxonomy Committee requested that WoRMS (via Arctos) names and classifications be cloned into Arctos wherever there wasn't a classification.  See #1936 .  Almost all of the names I'm working with were created from our collection because there was no WoRMS classification at that time.  So I'm essentially overwriting the less-than-ideal classification that I created in both Arctos and WoRMS (via Arctos) when we first changed our preferred source.  I think of it as mostly cleaning up messes I created.  

I agree that, whenever possible, collections should use WoRMS (via Arctos) but in the past Anna (CHAS) couldn't because of the structure of her collections.  That may have changed by now.  I don't change any Arctos data that is used by another collection except to add that the taxon status is now invalid and link it to the valid synonym. 

If you really want me to leave the Arctos classifications exactly as they are, I will, but we'll have more and more of them where Arctos and WoRMS (via Arctos) do not agree on taxon status, let alone the classification details.

**Comment by dustymc** [comment]
If you're checking to see if anyone's using the data at the time - and you are - then I don't see a problem with that.

Changing taxon status or even family is mostly below my radar - I just can't imagine a scenario where that changes the fundamental nature of the data.

Loading a million new jellyfish classifications without any real idea of what they're going to overwrite (probably a bit of everything!) is more what I'm concerned about, on behalf of the folks who might be using not-jellyfish homonyms in the shared source. That could easily (perhaps inevitably) lead to fundamental changes.

That's really all I'm trying to prevent here. I don't think it would change anything for the scenario you describe, you'd still have the single-record editor, you'd just be unable to bulkload to Sources that don't have data consistent enough to safely support bulk operations. (And maybe it would open pathways to better manage more specialized classifications with various tools.)

**Comment by dustymc** [comment]
Closing, source documentation seems sufficient while few are using taxonomy tools.
