### ISSUE TITLE
Why doesn't GBIF know the "occurrence status" of our specimens

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3122]
![image](https://user-images.githubusercontent.com/5725767/93792258-86c5f880-fbf2-11ea-9023-41cfca1fab04.png)

We touched on basis of record in our @ArctosDB/arctos-code-table-administrators meeting last week. I don't understand why this is happening. What field are we not transmitting properly in DwC?

Here is one of the records:
![image](https://user-images.githubusercontent.com/5725767/93792709-1b305b00-fbf3-11ea-8c95-9ade9d023e72.png)

Here it is in Arctos: https://arctos.database.museum/guid/UTEP:Ento:14578?seid=4782989

What are we doing wrong?

**Comment by Jegelewicz** [comment]
Also, why doesn't iDigBio know the datasetid?

![image](https://user-images.githubusercontent.com/5725767/93792980-6f3b3f80-fbf3-11ea-8534-c68351fd26d4.png)

**Comment by dustymc** [comment]
https://dwc.tdwg.org/list/#dwc_occurrenceStatus

AFAIK we never figured out "looked for _Species_ THERE+THEN, didn't find any" and that's what occurrenceStatus seems to be covering. GBIF's inference seems reasonable, and I don't see much reason we should be explicit until we have the ability to say anything other than "here's (an approximation of) an Occurrence."

Bigger picture, I'm not at all convinced that "GBIF did something wonky" is evidence of us doing something wrong.

datasetid might be from one of the alternate identifiers in collection/EML, but I can't find any sort of documentation for those so IDK.

**Comment by tucotuco** [comment]
Matt Blissett answers how GBIF makes the interpretation in this comment on
clarifying the definition the Darwin Core term indifidualCount,
https://github.com/tdwg/dwc/issues/285#issuecomment-696905232.

**Comment by dustymc** [comment]
Thanks @tucotuco. There's some code that "calculates" (strong word for what's happening!) individualCount for Fish and Ento collections, and ignores it for everything else. If there's some desire to do more than approximate for reports in lot-centric collection types, that should be split out as a specimen attribute and asserted by humans.

**Comment by Jegelewicz** [comment]
Thanks guys - closing but it will be here if we need to discuss in the future.
