### ISSUE TITLE
Bulkload files - how wide is too wide?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3123]
There are currently 284 columns in the table, this would add 72 more. Is nearly 400 columns really usable? Or from the other direction, is it really that different than ~800 columns (=6 full part-attributes with 12 parts, plus the other stuff)?

Perhaps this just isn't practical without something like https://github.com/ArctosDB/arctos/issues/2178? Or maybe we can just keep adding columns?? Looks like PG supports 1600 columns per table....

Maybe we need to sort that out in a dedicated issue - how wide is too wide, if anything is? - and then return here.

_Originally posted by @dustymc in https://github.com/ArctosDB/arctos/issues/1460#issuecomment-696267469_

**Comment by dustymc** [comment]
See https://github.com/ArctosDB/arctos/issues/1460#issuecomment-706343782
