### ISSUE TITLE
specimen event bulkloader validation not catching error in datum, protocol and source

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#3125]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Specimen event bulkloader validator isn't catching when there aren't coordinates, but there's data in either datum, georeference protocol and source. It throws an error only after user hits load.

**To Reproduce**
1) batch load file in specimen event bulkloader
2) validate, see precheck pass for all data
3) load -> throws error that there is data in datum, georeference source or protocol

**Expected behavior**
Validation should give user feedback that there shouldn't be data in datum, source or protocol when there isn't any coordinate data or that there should be coordinates with this other locality data.

**Screenshots**

** Data**
sample data attached.
[specimenbulkloader_missingcoordinatetestdata.zip](https://github.com/ArctosDB/arctos/files/5258697/specimenbulkloader_missingcoordinatetestdata.zip)

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
This should also be brought under This should be brought under the "component loader" fold - https://github.com/ArctosDB/arctos/issues/3125, with https://github.com/ArctosDB/arctos/issues/3124

**Comment by dustymc** [comment]
blocked by https://github.com/ArctosDB/arctos/issues/2974

**Comment by dustymc** [comment]
If anyone has any specimen event bulkloader data, including something that's already been loaded, I could use a sample for testing. I don't need many records, diversity would be useful. You can zip and attach it here or email it to me.

**Comment by mvzhuang** [comment]
I probably have something. will get to this tomorrow

**Comment by Jegelewicz** [comment]
Not diverse, but loaded back in the fall.
[L-4600_4999.zip](https://github.com/ArctosDB/arctos/files/5784170/L-4600_4999.zip)

**Comment by mvzhuang** [comment]
[UTEP_Insectgeoreferences_Readyforfinaleventload.zip](https://github.com/ArctosDB/arctos/files/5789456/UTEP_Insectgeoreferences_Readyforfinaleventload.zip)
This one has already been loaded as well
