### ISSUE TITLE
Big Bend National Park

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3127]
Search Localities for Specific Locality =Big Bend National Park and there are 16 localities all with higher geography = North America, United States, Texas, Brewster County; 15 of them with coordinates (no two the same)! Surely we can do better than that for a National Park

![image](https://user-images.githubusercontent.com/5725767/94047532-75feb980-fd8f-11ea-87e2-b51480ccbc1c.png)

Especially since we also include it as a feature in Higher Geography!

![image](https://user-images.githubusercontent.com/5725767/94047720-b827fb00-fd8f-11ea-851d-26b9fa2caf6d.png)

All of the Specific Localities = Big Bend National Park, should have their HG changed to

> North America, United States, Texas, Brewster County, Big Bend National Park

and their specific locality changed to

No specific locality recorded.

Then we need a WKT for the North America, United States, Texas, Brewster County, Big Bend National Park higher geography.

**Comment by dustymc** [comment]
"no two [coordinates] the same" should not be cause for alarm. If I was collecting I'd have recorded whatever my GPS reported, and perhaps begrudgingly added in some descriptive data later if forced to. All agreed on the rest.

See also https://github.com/ArctosDB/arctos/issues/3102#issuecomment-691274902

**Comment by jldunnum** [comment]
Not sure I am up to speed on what is being done to coordinates in these recent email strings. As Dusty said coordinates won't be the same for the many records within a "locality". We georeference each animal collected and simply upload the gps data. So a single locality may have hundreds of slightly varied coordinates associated with it and those should not be rounded or truncated.

______________________________________________________________

Jonathan L. Dunnum Ph.D.
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by Jegelewicz** [comment]
Notice that I never called for changing the coordinates on any of the localities - just making the higher geography consistent and a request for a WKT for the feature.

**Comment by jldunnum** [comment]
Wasn't sure exactly what was being done. These strings get super long very quickly and if you come in late its hard to tell.

______________________________________________________________

Jonathan L. Dunnum Ph.D.
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by campmlc** [comment]
Question on these higher geography WKTS - Berkeley Mapper seems to assign a center point with inappropriately high precision in terms of number of digits in the coordinates field, even though the error is high. When you look at the mapped point in BM, you don't see the error, only the point, and it is misleading. For example, all New Mexico, no specific locality records with a WKT are mapping to a point in the eastern plains which is outside the range of some of species in the associated records.

**Comment by dustymc** [comment]
>WKTS - Berkeley Mapper

Those aren't related - BM accepts point-radius data.

>inappropriately high precision in terms of number of digits in the coordinates field

There's no such thing - 12,34 and 12.000000000000000000000000000000000000,34000000000000000000000000000000000000 are precisely the same information; both are exactly in the same place, and both are exactly the same size, zero.

>don't see the error,

<img width="164" alt="Screen Shot 2020-09-28 at 12 38 40 PM" src="https://user-images.githubusercontent.com/5720791/94478066-96f84d80-0187-11eb-931a-e6d403e09d99.png">
