### ISSUE TITLE
Feature Request - A {string} Identification screen

### ISSUE THREAD

**Issue by lin-fred** [ArctosDB/arctos#3128]
I am working on quarantining taxon names. I add the A {string} identification to the record, and the A {string} and the old name identification look identical, but they technically aren't. I can't tell which one to delete. Is there a way to add something onto the screen to know the identification type?

![image](https://user-images.githubusercontent.com/19802479/94174429-8035bc00-fe52-11ea-81d0-0bdbd0e80c40.png)

I can copy the information somewhere else, delete the old taxon name, and then add the A {string}, but it would be nice to be able to tell the difference from the identification screen on a specimen record.

**Comment by dustymc** [comment]
Link to a record please.

**Comment by lin-fred** [comment]
It is this one

https://arctos.database.museum/guid/NMMNH:Inv:5974

**Comment by dustymc** [comment]
Thanks!

A {string} IDs look like this:

<img width="589" alt="Screen Shot 2020-09-24 at 9 58 33 AM" src="https://user-images.githubusercontent.com/5720791/94176192-980a4180-fe4c-11ea-829b-3a00aa2fcca0.png">

while others look like...

<img width="610" alt="Screen Shot 2020-09-24 at 9 59 19 AM" src="https://user-images.githubusercontent.com/5720791/94176252-aa847b00-fe4c-11ea-89d8-529157e0a229.png">


but apparently only when the A {string} ID is accepted.

I'm not sure why we ended up there, it seems that functionality should be available whether the ID is accepted or not. If I can do that, would that be sufficient? I don't think it would be any problem to explicitly list the formula either or also, just a tiny bit of screen space.

**Comment by lin-fred** [comment]
Ah yes! I was just doing another one and was about to comment that it shows when the A {string} ID is accepted, but not when the other one is accepted.

> If I can do that, would that be sufficient?

Yes I think that would be fine. I would like the A {string} to be indicated even if the ID is not the accepted one on the record, since it is inherently different than the old A ID.

**Comment by dustymc** [comment]
Well now I remember why we did it that way....

That form needs a refresh, until that can happen I did...

<img width="627" alt="Screen Shot 2020-10-02 at 7 19 41 AM" src="https://user-images.githubusercontent.com/5720791/94933755-ade8b980-047f-11eb-91a7-d2dddbb56468.png">

**Comment by lin-fred** [comment]
That works for now! Thanks
