### ISSUE TITLE
Locality search hung up?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3132]
I'm trying to search localities and Arctos is just processing....

![image](https://user-images.githubusercontent.com/5725767/94481395-db3e1a80-0194-11eb-839f-ab2ca4ce8ded.png)

**Comment by Jegelewicz** [comment]
Here was search parameter
![image](https://user-images.githubusercontent.com/5725767/94481463-f90b7f80-0194-11eb-850b-bcb987f40432.png)

**Comment by dustymc** [comment]
I think I broke it trying to multitask - I'll get something out ASAP

**Comment by dustymc** [comment]
deborked

**Comment by Jegelewicz** [comment]
When not logged in, select "See more" next to higher geography.

![image](https://user-images.githubusercontent.com/5725767/94605950-08530180-0257-11eb-9acf-dbd8f6b644e2.png)

Get nothing in results. Shouldn't at least this one thing show up there?

Also, tried entering this exact higher geography into the locality search and get zero results....

**Comment by dustymc** [comment]
Links fixed in next release - I can't recreate the geog search glitch.

**Comment by Jegelewicz** [comment]
> I can't recreate the geog search glitch.

Apparently it eventually worked - it was just reeeeeaaaalllyyy sloooooooow.
