### ISSUE TITLE
Locality Edit out now?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3133]
https://arctos.database.museum/editLocality.cfm?locality_id=11109622

Get me to 

![image](https://user-images.githubusercontent.com/5725767/94490865-565afd00-01a4-11eb-9cd1-9041f227fb86.png)

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/2830#issuecomment-696388620 - that was just me failing to not melt anything important....

**Comment by Jegelewicz** [comment]
OK can edit, but the dropdown for terms available in the code table for attributes isn't updating?

**Comment by dustymc** [comment]
probably cached, or I need more information if that doesn't sound right

**Comment by Jegelewicz** [comment]
Seems to be good now.
