### ISSUE TITLE
Higher Geography Clean Up Korea

### ISSUE THREAD

**Issue by Erober45** [ArctosDB/arctos#3135]
Hi all- Noticed some issues with Korea. Everything in Arctos with the higher geography “Korea” is actually located in South Korea; thus, anything with the higher geography Korea, Kangwon Province I believe is meant to be South Korea, Gangwon Province. I recommend that we clean this up. We also need to discuss whether we should use North and South Korea or if we should use the officially recognized names “Democratic People’s Republic of Korea” (North Korea) and “Republic of Korea” (South Korea) and how we should handle anything from “Korea” collected prior to 1945 when Korea had been a unified political entity.

**Comment by dustymc** [comment]
>names

No real opinion, I can probably SQL update that.

>prior to 1945 

The current guidance is to use current data when possible - if it's not (eg, if "Korea, 1930" is all that's given) then we'll probably end up with three values

* N Korea
* S Korea
* Korea

https://handbook.arctosdb.org/documentation/higher-geography.html#guidelines-for-geographic-terms-in-arctos

>Use current definitions, where possible. For example: Yugoslavia no longer exists, so use Slovenia, Croatia, or whichever country the locality is now in, especially if cataloging current material. If Yugoslavia was used in the original data, it now belongs in verbatim locality, not in Higher Geography. If you are editing specimen records, append the old higher geography to verbatim locality in the following order: verbatim_locality, state, country. We will support Higher Geography of deprecated countries, state/provinces for legacy materials but STRONGLY urge curators to view this as a short-term solution and re-assign as appropriate. Any Geography term can have synonyms and alternate names to maximize discoverability. We will support WKT footprints for modern geography only.

**Comment by acdoll** [comment]
I believe we should use the official names, but people will probably still want to search 'North Korea' or 'South Korea'. Do we need to include those terms parenthetically or, @dustymc, can you make that happen behind the scenes? I imagine users might want to still see North or South on the results/records too.
BTW: do you see any reason why some, but not all, records from 'North America, United States, New Jersey, Bergen County' come up when you do an Any Geography Term search on Korea?
https://arctos.database.museum/saved/Any%5FGeog%5FKorea
--

**Comment by dustymc** [comment]
>want to search 

https://handbook.arctosdb.org/documentation/higher-geography.html#guidelines-for-geographic-terms-in-arctos

>DO include any equivalent data excluded by these “rules” in “search terms.” These are becoming increasingly valuable in automated mapping to Arctos (and reducing duplicates); please MINIMALLY copy all of the “alternate names” (such as Spanish place names containing diacritics or “local” names given in Arabic or Thai characters) from Wikipedia into individual search terms fields.

<img width="301" alt="Screen Shot 2020-10-07 at 9 53 27 AM" src="https://user-images.githubusercontent.com/5720791/95362632-35b93400-0883-11eb-91a0-443822afc5ab.png">


https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=1005118


>still see North or South on the results/records too.

"Just" UI....

**Comment by dustymc** [comment]
>why some, but not all, records from 'North America, United States, New Jersey, Bergen County' come up when you do an Any Geography Term search on Korea?

Arctos automagically reverse georeferences everything; that's picking up...

<img width="587" alt="Screen Shot 2020-10-07 at 10 04 23 AM" src="https://user-images.githubusercontent.com/5720791/95363652-9432e200-0884-11eb-86cc-78d2310f6913.png">


... on https://arctos.database.museum/guid/DMNS:Bird:2192

**Comment by dustymc** [comment]
Tabling - https://github.com/ArctosDB/arctos/issues/3272 would allow Arctos to standardize geography.
