### ISSUE TITLE
Code Table Request - add application/object to MIME Type

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#3136]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Goal**
Add media with wavefront .obj type

**Context**
current file types don't have 3d objects. Trying to attach media that can be viewed with application in browser, i.e. https://www.morphosource.org/Detail/MediaDetail/Show/media_id/84233

**Table**
MIME Type
**Value**
Proposed new value
application/object

**Definition**
object file 

**Collection type**
N/A

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
Is the media file the .obj (in which case you do need a new mime type) or the morphosource page (in which case it's text/html)?

I don't think there's any native .obj handling in browsers, so adding the binary will probably just lead to a download.

See also https://github.com/ArctosDB/arctos/issues/1882 - there are plans to do SOMETHING with MS whenever they get their v2.0 API finalized. Adding https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type&field=Morphosource to the record is likely to be somewhere between useful and critical.

**Comment by mvzhuang** [comment]
Trying to figure that out a little. If you click the Wavefront OBJ in the example link, it opens the model in browser, but the link is the same, but can't figure out what viewer is being used.
yup added Morphosource other ids just now.

**Comment by dustymc** [comment]
>what viewer is being used

Something developed by MS, I believe. They're actually loading a bunch of PNGs and JS libraries - eg I think they're doing some fairly heavy preprocessing.

**Comment by mvzhuang** [comment]
ok in that case, I'll just use the text/html then
