### ISSUE TITLE
Merge part names shell and shell (dry)?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3139]
shell (dry)

Added along with definition

For invertebrates, typically a calcareous exoskeleton which encloses, supports and protects the soft parts of an animal in the phylum Mollusca, which includes snails, clams, tusk shells, and several other classes. <a href="https://en.wikipedia.org/wiki/Mollusc_shell" target="_blank" class="external">Wikipedia</a> Dried.

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/arctos/issues/3137#issuecomment-701028872_

**Comment by Jegelewicz** [comment]
shell is the part name generally used in mollusc collections, however at some point (not sure when) shell (dry) was added to the part name code table. As @sharpphyl has pointed out:

> Can you explain the difference between “shell” and “shell (dry)” which is added here.  We’ve been using “shell” for years.  When would we use “shell (dry)” instead?  Your explanation says that it’s the "dry snail shell only" so I don’t see the difference.

I suggest we pick one of these and merge the names or we change the definition of shell to

For invertebrates, typically a calcareous exoskeleton which encloses, supports and protects the soft parts of an animal in the phylum Mollusca, which includes snails, clams, tusk shells, and several other classes. <a href="https://en.wikipedia.org/wiki/Mollusc_shell" target="_blank" class="external">Wikipedia</a> **Unknown preservation**.

**Comment by dustymc** [comment]
**shell (dry)** is embedded prep/storage data, not ideal but explicit.

**shell**  (without accompanying part attributes) should be interpreted as "...and we have no other information."

One should lead to loan requests, the other should lead to requests for more information, then maybe to loans.

Those should be merged, but only when we have a usable solution to https://github.com/ArctosDB/arctos/issues/1460.

**Comment by sharpphyl** [comment]
Thanks for pursuing this.

> For invertebrates, typically a calcareous exoskeleton which encloses, supports and protects the soft parts of an animal in the phylum Mollusca, which includes snails, clams, tusk shells, and several other classes. Wikipedia Unknown preservation.

Could you clone this definition from "shell (dry)"  into "shell"?  

And as long as we're looking at these tables, could we expand the definition of "test" to be 

A test is the hard shell of some spherical marine animals, notably sea urchins and microorganisms such as testate foraminiferans, radiolarians, and testate amoebae. [Wikipedia](https://en.wikipedia.org/wiki/Test_(biology))

**Comment by lin-fred** [comment]
Thanks for this clarification and update!

**Comment by Jegelewicz** [comment]
This is no longer relevant thanks to https://github.com/ArctosDB/documentation-wiki/issues/204
