### ISSUE TITLE
Code Table Request - New part name head, tail (plus same part with multiple preservations)

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3144]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

Goal
Help a new collection get into Arctos

Context
New terms/combinations of terms.

> Aplacophoran molluscs are honorary worms whose head and tail ends are taxonomically informative whereas the middle region of the body is uniform and boring. We often cut them in thirds and put the head and tail in the same container of formalin / glutaraldehyde and the “midbody” region would just be the middle third or less that would potentially be further divvied out into ethanol, RNAlater, and/or cryo.

Table
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name

Value
head, tail
head, tail (glutaraldehyde-fixed, 70% ethanol)
head, tail (paraformaldehyde-fixed, 70% ethanol)
head, tail (95% ethanol)

Definition
The part of an organism which usually includes the ears, brain, forehead, cheeks, chin, eyes, nose, and mouth, each of which aid in various sensory functions such as sight, hearing, smell, and taste, respectively. Some very simple animals may not have a head, but many bilaterally symmetric forms do, regardless of size. <a target="_blank" class="external" href="https://en.wikipedia.org/wiki/Head">Wikipedia</a> Stored with the tail. The section at the rear end of certain kinds of animals’ bodies; in general, the term refers to a distinct, flexible appendage to the torso. It is the part of the body that corresponds roughly to the sacrum and coccyx in mammals, reptiles, and birds. While tails are primarily a feature of vertebrates, some invertebrates including scorpions and springtails, as well as snails and slugs, have tail-like appendages that are sometimes referred to as tails. <a href="https://en.wikipedia.org/wiki/Tail" target="_blank" class="external">Wikipedia</a> Preservation unknown.

Collection type
Inv

Attribute data type
N/A

Attribute value
N/A

Attribute units
N/A

Part tissue flag
yes
no
no
yes

Other ID BaseURL
N/A

Priority
Please assign a priority-label.

**Comment by dustymc** [comment]
* This is going to create extra work if we ever decide to do something involving rigorous normalization of parts.
* We already have lots of combo-parts, what's a few more?

I don't like this, but I won't oppose it.

This is mostly indistinguishable from eg ``centrum, cervical`` - if we're going to make more combo-parts, maybe we should find a "formula" that separates them from other confounded junk.

I also think in this case the wiki definition isn't terribly useful - I'm not sure we're going to be stuffing the ends of anything with cheeks into tubes....

**Comment by Jegelewicz** [comment]
> stuffing the ends of anything with cheeks into tubes

Do aplacophoran molluscs have cheeks? I have no idea....but they WILL be stuffed into tubes. The definition says "usually"...

I don't like this either, but trying to get a new collection to deal with the loan issue that @campmlc has brought forward when two or more things are stuck in a tube is not what I want to be doing today. I hate that this is rushed, but I cannot control who decides to enter Arctos when.

**Comment by Jegelewicz** [comment]
I am going to split all of this up and record with attributes.

**Comment by Jegelewicz** [comment]
added combo part - use separate preservation.
