### ISSUE TITLE
Create Barcode Series - error feedback

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#3148]
I'm trying to enter the attached series of container barcodes. They uploaded and validated, then when I clicked Proceed to Load, I got this error:

_An error occurred while processing this page!Message: ERROR: Invalid barcodes detected Where: PL/pgSQL function batchcreatecontainer() line 28 at RAISEDetail: Parameter types passed (0):
--_

[DMNS_Container Upload_09-30-2020.zip](https://github.com/ArctosDB/arctos/files/5308450/DMNS_Container.Upload_09-30-2020.zip)

**Comment by dustymc** [comment]
arctosprod@arctos>> select barcode,IS_CLAIMED_BARCODE(barcode) x from temp_cache.temp_dlm_uptbl where IS_CLAIMED_BARCODE(barcode)!='PASS';
   barcode   |  x   
-------------+------
 DMNSZTVFMF6 | FAIL

**Comment by acdoll** [comment]
Thanks. I keep a running list of all the container I create and it's not on there; not sure how it got into Arctos already. I also check my numbers using the 'Find GUID from Barcode' but that won't catch something that hasn't had any parts put into it yet. 

> temp_cache.temp_dlm_uptbl

Is this something you just created (a copy of the file I attached), or is this the residual from my attempt a upload? That is, can I use this same SQL in the future if I have a similar problem?

**Comment by dustymc** [comment]
<img width="290" alt="Screen Shot 2020-09-30 at 3 43 00 PM" src="https://user-images.githubusercontent.com/5720791/94747408-aa481c00-0333-11eb-9783-cefe216ebfba.png">

will load arbitrary data into a temporary table and return the table name - then you should be able to use writeSQL to talk to it.

Create container writes to cf_temp_container - you should be able to use it as well.

**Comment by acdoll** [comment]
Great, thanks! I always wondered what those were for - decided it'd be safer to stay out of the developer tools. How long do those temp files stay there? Until someone adds a new one?

**Comment by dustymc** [comment]
It's currently until you overwrite it, although it's in my "delete at will" schema so no promises. I think we could accommodate if you need something more permanent.

**Comment by acdoll** [comment]
That makes sense. No need to make anything more permanent; I just wanted to know how it works. I can't image anyone but you uses it much, but what do I know.

**Comment by acdoll** [comment]
@dustymc I wanted to try your SQL on another set of barcodes, but the Upload CSV is not working for me. I can 'Choose File' just fine, but when I click 'Upload CSV' nothing happens.

**Comment by dustymc** [comment]
Try the scary option - I need to clean up that form.

**Comment by acdoll** [comment]
The one with the button labeled "reformat you hard drive"??

**Comment by dustymc** [comment]
Yup....

**Comment by acdoll** [comment]
Got it, thanks! (hard drive still seems to be functioning)

**Comment by acdoll** [comment]
Is there a similar way I can check to see if a container has been created for a particular barcode?

**Comment by acdoll** [comment]
or long list of barcodes?

**Comment by dustymc** [comment]
Something like...


select barcode from yourfile where not exists (select barcode from container where container.barcode is not null and container.barcode=yourfile.barcode)

Send me a file with some barcodes if that doesn't work and I'll tune it up.

**Comment by acdoll** [comment]
Thanks, I'll try...

**Comment by campmlc** [comment]
Posting here since this is not closed -
I am trying to create a container series fo 150,000 barcodes. Per instructions I have broken the file down into 3 separate csvs of 50000 barcodes each. Just tried to load the first and got a 500 Internal Server error. Zipped files attached. 
@dustymc can you load these please?
BTW, having to split up a large file with consecutive values into 3 smaller ones introduces quite a large possibility of royally messing something up.
[CreateContainerTemplate_Fall2020series.zip](https://github.com/ArctosDB/arctos/files/5789125/CreateContainerTemplate_Fall2020series.zip)
