### ISSUE TITLE
do not read this

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3149]
Do not click this; it'll block your access to Arctos. It's for the annoying bots that are following all the links from github.

https://arctos.database.museum/dnf.cfm

/remind me to close this in a week

**Comment by Jegelewicz** [comment]
This is not the Arctos you are looking for....

**Comment by KyndallH** [comment]
The only GitHub message I've looked at all week! Note to self, use this title when you want people to read an issue.
