### ISSUE TITLE
Error message appears in raw html PLUS cannot search in place.cfm

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#3155]
Double Error here!
First error: trying to run a search for collecting events in place.cfm (after date=2000-01-01 and Verbatim locality={somevalue})
Then: received an error after some processing time. The pop-up window is not formatted but raw HTML-- see below:

![Capture](https://user-images.githubusercontent.com/2523089/95224361-6def4280-07af-11eb-9f8b-9bed608d9839.PNG)

Doesnt matter which client or OS, the same thing happens

A new search gives me this error message (but same raw HTML):
This message has been logged as 29FAC465-768A-4C27-889131ADD67BBED3

**Comment by mkoo** [comment]
After some more attempts, I think the 500 errors should also include a tip: "Results are too large, try adding some Higher Geography to narrow your search"

**Comment by dustymc** [comment]
Need more info - works for me.

<img width="472" alt="Screen Shot 2020-10-06 at 9 49 32 AM" src="https://user-images.githubusercontent.com/5720791/95232411-5026db00-07b9-11eb-9ba4-e32e5a0685d6.png">

>Results are too large

Doubtful - I can get 300K results in under a second.

<img width="459" alt="Screen Shot 2020-10-06 at 9 50 24 AM" src="https://user-images.githubusercontent.com/5720791/95232487-6a60b900-07b9-11eb-9e13-e1b9c243f851.png">

**Comment by mkoo** [comment]
what more info do you need?-- same parameters as me, doesnt work in chrome,
FF, regardless of OS (cuz I tried PC and Macs). Also, not specific to
my network since I tried, home, office, with and without VPN.. The 500
error seemed to be a timed out issue and I sent you the error # from the
last time. running out of variables....

If you get an error you'll see what i mean by the pop-up window....

**Comment by dustymc** [comment]
Where'd my other answer go?! Can't be user error....

I dug around in the logs, it looks like you weren't logged in and Lucee is being slow to establish a session for the API call. I can intermittently recreate, but I can't really tell what's going on. Lacking better ideas I suggest we schedule a reboot (or I'll just do it the next time the system's not very busy) and go from there. In the meantime logging in first seems to always work.

I think ultimately this goes back to https://github.com/ArctosDB/internal/issues/64

**Comment by mkoo** [comment]
OK, I'll let 'em know. I was purposely trying to search without logging in (and sorry for not mentioning that!) but that can be fixed! Will try again with the search but do check out the pop-up window issue please.

**Comment by dustymc** [comment]
The popup is just the normal error, but Lucee claims it's JSON which apparently confuses some browsers. I suppose we need a JSON/API error, but that's another Issue. I can't make the error again so not sure how mine renders. There are fewer sessions now than when I was first in there, maybe I'll find something useful in that....
