### ISSUE TITLE
Attempting to create an accession; got this error message saving the entry

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/arctos#3156]
![image](https://user-images.githubusercontent.com/43214224/95348147-5b463d80-0883-11eb-9190-3aba627b04bc.png)

**Comment by campmlc** [comment]
Make sure you have an agent name in all required roles? Make sure you tab
the name to accept before saving?

**Comment by mbprondzinski** [comment]
I had made a change to the name spelling and I guess I hadn't tabbed the new entry.  It finally worked... thanks!
