### ISSUE TITLE
Blocked from Arctos

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/arctos#3157]
I've been blocked from Arctos.  At first I was told I was removed from the blacklist, but I am now unable to get into it.

**Comment by dustymc** [comment]
>unable to get into it

Elaborate please

**Comment by mbprondzinski** [comment]
When I click on the url, I get this:
[cid:image001.png@01D69D62.AB220E60]
This occurred after I logged out earlier and was told my IP had been blacklisted.

**Comment by dustymc** [comment]
@mbprondzinski the images are not coming through

**Comment by mbprondzinski** [comment]
![image](https://user-images.githubusercontent.com/43214224/95490942-95d0d880-095e-11eb-977e-19e5e9832cb1.png)

**Comment by dustymc** [comment]
What is the URL where you get that?

**Comment by mbprondzinski** [comment]
![image](https://user-images.githubusercontent.com/43214224/95492022-17753600-0960-11eb-9b6c-10cebef5389d.png)

**Comment by dustymc** [comment]
OK, thanks. It looks like your browser may be in some strange state. Try going to https://arctos.database.museum/login.cfm?action=signOut then signing back in. If that doesn't work, try clearing cookies and cache, then https://arctos.database.museum/login.cfm?action=signOut, then signing in.

**Comment by mbprondzinski** [comment]
Thanks, that worked!
