### ISSUE TITLE
Locality Merge Documentation Needs Update

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3161]
HWML Accession P-2012-015  (14,059 records) was entered in Arctos over a month ago, and there are significant georeferencing errors introduced by an automated georeferencing script used by the collection prior to bulkload. These can be fixed using existing Arctos tools, but only if the shared localities are merged.  Unfortunately, when the data were bulkloaded, each individual catalog record was assigned a unique locality ID by Arctos. I have been waiting for the locality merge scripts, but nothing has happened over the last 6 weeks. I would like to request that this accession be prioritized for locality merge cleanup so that the georeferencing can be corrected. This is affecting progress on a grant funded project.

**Comment by Jegelewicz** [comment]
@campmlc I suggest merging dupes then fixing the georeference. It's pretty easy and you will need to search out the localities to fix the coordinates anyway?

I already merged a few of them myself. Just search localities (not events) for the specific locality that needs correcting. Then select "Check Dupes" on the first one in the list of results. Merge them, then fix the coordinates on that first locality.

**Comment by dustymc** [comment]
There's currently no promise of timeliness in the system; it'll get there eventually. I've increased the schedule to what I think the system can easily bear, but still no promises of when things will happen.

There's nothing about prioritizing specific localities in the system; perhaps it could be added, somehow.

The big obstacle is the 30-day delay. Merging events leads to mergable localities and vice-versa, a lot of entropy can accumulate in a month, cleaning that takes time, more accumulates, .... The scripts were designed with a one-day delay in mind, I think I could keep up if we can get back to that. That's 100% social problem, if anyone wants to tackle it.

"What I think the system can easily bear" is a bit more zen than I'd like - I don't have great monitoring tools, the scripts are very good at plugging things up, I have to be extremely conservative. Such tools do exist for PG. Maybe we could use some of the funding for that, or for an external review of the cache (where those plugs occur), or something of the sort?

**Comment by Jegelewicz** [comment]
@campmlc there is only one other locality to merge with that one, so you only see one result. Check it and merge them.

**Comment by campmlc** [comment]
Oh, that makes sense. I thought the one in the table was the one I searched
on. It might make more sense if all dups appeared in the check for
duplicate results, so we can compare before marking to merge.

**Comment by Jegelewicz** [comment]
Kinda, but the one you searched is the one at the top with all the fields in grey. The ones in the list are the dupes - I'll make it a task for me to add something to that effect to the documentation/results page.

**Comment by campmlc** [comment]
Still, it would helpful if they displayed together so you can see the
different locality IDs
