### ISSUE TITLE
TACC Media notifications

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#3162]
Trying to access some media, everything I have tried so far I get the following:
![image](https://user-images.githubusercontent.com/47402809/95905168-bb425580-0d55-11eb-95dd-c1e804e14e1e.png)

and then this:
![image](https://user-images.githubusercontent.com/47402809/95905265-dca34180-0d55-11eb-954f-0183e50ef0dd.png)

Here is an example of one that is not working for me:
https://arctos.database.museum/media/10612932

**Comment by dustymc** [comment]
https://portal.tacc.utexas.edu/user-news/-/news/106272

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Ok, thanks! It would be useful to have TACC outages like this emailed out to the Arctos group.

**Comment by Jegelewicz** [comment]
Need process for TACC outage notifications - who should be the point person?

**Comment by campmlc** [comment]
I tried to figure out the procedure to sign up and got stymied. Anyone else
actually getting notifications?

**Comment by ewommack** [comment]
I've signed up today, but I'm not sure which ones to sign up for. There were a lot of options. Which ones will give us important info for Arctos?

If you have your TACC log in, you have to go under News -> Subscribe, and then get an email to allow you access.

**Comment by ewommack** [comment]
Like this announcement that just came through: This concerns Arctos I believe. Should I just forward all of them or specific ones?

UPDATE:
Corral maintenance has been extended until October 14, 10 AM CDT
-----------------------
Original Announcement:
Corral Maintenance Tuesday 13 October 2020
From: Matthew Edeker
Corral will be down for hardware maintenance Tuesday October 13 8:00 AM to 5:00 PM CDT. All Corral services, including data transfer nodes, NFS mounts, web access, and iRODS service will be down during this time.

Please submit any questions you may have via the TACC User Portal. 

https://portal.tacc.utexas.edu/tacc-consulting

**Comment by campmlc** [comment]
This one is definitely valuable to forward. I just tried to upload media
and it froze again. I wish we had some way to get a notification that "the
media upload tool is temporarily unavailable. Please try back later." As
is, you get the frozen screen of death.

**Comment by Jegelewicz** [comment]
@ewommack has signed up for notifications and will work on sending notifications.
