### ISSUE TITLE
Scary Box Barcode Swapper Tool not working

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3163]
Getting 505 Internal Server Error. Attached is file I tried to load. Note that one position has a vial that is already barcoded, and this has been removed from the upload file. Two positions are empty.
[DGR18909.zip](https://github.com/ArctosDB/arctos/files/5375658/DGR18909.zip)

**Comment by dustymc** [comment]
505 is busted encryption - I need all of the information from the template to diagnose.

**Comment by campmlc** [comment]
I attached the file to previous post. When I tried to load, the browser
just spun, waiting for Arctos, and then the 505 error. No other error
message.

**Comment by Jegelewicz** [comment]
I assume this is resolved because of #3210 Closing.
