### ISSUE TITLE
Quarantine Taxon Name - Sorex cinereus cincereus

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3165]
Issue Documentation is at http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

Name Quarantine Documentation is at https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxon_name_type

The name suggested for quarantine is: https://arctos.database.museum/name/Sorex%20cinereus%20cincereus

The reason for quarantine is: I think it's a misspelling

The suggested treatment for all identifications currently using this name is: get MSB to deal with them, or develop procedures so I can deal with them

Collections currently using this name in identifications include: MSB:Mamm

Priority
Please assign a priority-label.

**Comment by jldunnum** [comment]
Fixed. Still lack a "Nature of ID" for simply fixing misspelled names.

______________________________________________________________

Jonathan L. Dunnum Ph.D.
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by campmlc** [comment]
If MSB is the only usage, we can delete the IDs and then delete the name.
No point keeping a misspelling  if it doesn't exist elsewhere in universe.

**Comment by dustymc** [comment]
Google's never heard of it (except here), agree with deletion, but it's still used. https://arctos.database.museum/SpecimenResults.cfm?taxon_name_id=10945407

**Comment by campmlc** [comment]
So can we quarantine if it is used? It is flagged as a
misspelling correction. We don't want to propagate to GBIF. Should we
delete the mispelled IDs, and add remarks to the current, correct
identification?

**Comment by dustymc** [comment]
>So can we quarantine if it is used?

No, the only thing quarantined names can participate in is relationships.

I'll leave what you do with IDs up to you, but that's about what I'd recommend - and whatever you come up with would be useful as a how-to.

It's also possible to use "A {string}" IDs to preserve the original spelling without using the not-so-great taxa if that's somehow important, and I'm sure there are plenty of other approaches, but I don't think that's very useful here. I'm not really sure the apparent typo in remarks is useful either, but again totally up to you.

**Comment by dustymc** [comment]
Let's bring this into the new quarantine system - I'll update IDs and DELETE the name about 2022-04-08 unless someone stops me, or sooner if everyone agrees.

Summary: identifications using the nominated name:

```
 guid_prefix | accepted_id_fg | numberids |                              link_to_records                              |        taxon_name        |                        link_to_taxon                         
-------------+----------------+-----------+---------------------------------------------------------------------------+--------------------------+--------------------------------------------------------------
 MSB:Mamm    |              0 |         4 | https://arctos.database.museum/SpecimenResults.cfm?taxon_name_id=10945407 | Sorex cinereus cincereus | https://arctos.database.museum/name/Sorex cinereus cincereus

```


 @campmlc
 @jldunnum

**Comment by dustymc** [comment]
done
[temp_taxon_quarantine_reloader(3).csv.zip](https://github.com/ArctosDB/arctos/files/8419170/temp_taxon_quarantine_reloader.3.csv.zip)
