### ISSUE TITLE
error feedback: Message: not authorized Detail: You are not authorized to access this form.

### ISSUE THREAD

**Issue by cefilipek** [ArctosDB/arctos#3166]
I needed to edit a collecting event, because I noticed that some of the words were doubled up in the Event Remarks, but when I went to edit it I received an error message saying I was not authorized.

This happened previously, but I was given the authorization to access the form then, so I'm unsure why it is an issue now.

I selected Edit next to Location on the catalog record, then selected Edit Event next to Collecting Event.

![Error Message Arctos 10 20](https://user-images.githubusercontent.com/56844074/96599141-3acfa780-12b5-11eb-88af-ddc436dc5408.PNG)

**Comment by dustymc** [comment]
I'm not sure what happened, but I gave you manage_locality. It is a shared node; please read (or re-read!)

https://handbook.arctosdb.org/documentation/sharing-data-and-resources.html
https://handbook.arctosdb.org/documentation/locality.html
https://handbook.arctosdb.org/how_to/How-to-understand-the-Arctos-Locality-Model.html

I'll need more details if that doesn't solve the problem.

**Comment by cefilipek** [comment]
It worked! Thank you very much!


Colleen Filipek

Museum Collections Manager

Jurica-Suchy Nature Museum

Benedictine University


5700 College Rd. l Lisle, IL 60532

Office: (630) 829-1142

Office Fax: (630) 829-6547  l  ben.edu/museum<http://www.ben.edu/museum>

Follow us: facebook.com/JSNMatBU<http://www.facebook.com/JSNMatBU>



________________________________
