### ISSUE TITLE
Permission error on adding project to accession

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3167]
Tried to add a project to an accession logged in as gradyjt, got following error. Operator has manage transaction role, can create and delete accessions, can create projects, but can't add project to accession.

  | An error occurred while processing this page!Message: ERROR: permission denied for table project_transDetail:Check the Arctos Handbook for more information on errors.This message has been logged as 7B7024C9-9E08-454C-A8C0829A26F369E0 Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue.
-- | --

**Comment by dustymc** [comment]
I will be surprised if this doesn't break something somewhere.

<img width="563" alt="Screen Shot 2020-10-20 at 10 44 25 AM" src="https://user-images.githubusercontent.com/5720791/96624195-44f7a300-12c1-11eb-8cfc-18a3d1d008e7.png">

You can see exactly what roles are required for any operation via...

<img width="421" alt="Screen Shot 2020-10-20 at 10 45 04 AM" src="https://user-images.githubusercontent.com/5720791/96624242-55a81900-12c1-11eb-81ec-9085b1d1d990.png">

<img width="77" alt="Screen Shot 2020-10-20 at 10 45 33 AM" src="https://user-images.githubusercontent.com/5720791/96624306-6d7f9d00-12c1-11eb-8c31-62e7d59e581f.png">

<img width="452" alt="Screen Shot 2020-10-20 at 10 45 42 AM" src="https://user-images.githubusercontent.com/5720791/96624325-71132400-12c1-11eb-920a-66c5b67d56ed.png">

That table requires manage_publications.

**Comment by gradyjt** [comment]
Are you advising that I need to make my data entry agent profile name more different to make sure nothing breaks?

**Comment by campmlc** [comment]
Yes, remove the non-operator login from your agent profile.

**Comment by gradyjt** [comment]
Ok, can do, thanks!

**Comment by campmlc** [comment]
If adding two logins breaks things, perhaps we should only allow one login
name per agent?

**Comment by campmlc** [comment]
I added publications to gradyjt roles. Please review the following before
using any tools - pubs and projects are shared.
Arctos Publication Documentation
<http://handbook.arctosdb.org/documentation/publications.html>
Arctos Project Documentation
<http://handbook.arctosdb.org/documentation/projects.html>
https://youtu.be/aLCC-SI1-RI

**Comment by gradyjt** [comment]
Ok, thank you! I'm still trying to figure out how to delete my regular operator profile...says operator cannot be deleted when I'm in manage agents, but I haven't consulted the handbook yet!

**Comment by campmlc** [comment]
Don't delete your operator profile. Just remove the login name from your
agent page. I can go try now. .. .

**Comment by campmlc** [comment]
Hey @dustymc this is one for you - she has two logins associated with her agent profile, but gets an error message when she tries to delete one that an operator login cannot be deleted.

**Comment by gradyjt** [comment]
I'm not really sure how they got linked like that because I remember making two separate profiles, but the names weren't maybe different enough?

**Comment by dustymc** [comment]
>operator login cannot be deleted.

True

>delete one

I can lock down and clean up, which one's extra? They are both authenticated accounts.

>got linked like that

Looks like "ndisotell" did it.

>perhaps we should only allow one login name per agent?

Maybe but 1) that may actually be a feature, and 2) AFAIK this is the first time it's happened so not really at the top of my list.

**Comment by campmlc** [comment]
keep gradyjt

**Comment by gradyjt** [comment]
The extra (my data entry operator profile) is the jgrady1.

**Comment by campmlc** [comment]
I just deleted all operator roles for jgrady1 and locked the account. OK to
delete.
You should now only have one operator account which you should use for all
Arctos functions, including data entry. You can go ahead and create a new
public user account which will let you download data and see all
collections.

**Comment by gradyjt** [comment]
Ok great thanks!
