### ISSUE TITLE
Locality Bulkload Tool - not getting what I expect

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3168]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
When I select "change status" next to the block of NULL status records

![image](https://user-images.githubusercontent.com/5725767/96634023-27353880-12d7-11eb-9dc6-b07f0ad07717.png)

I expect to see only those with NULL status. Instead I see everything.

![image](https://user-images.githubusercontent.com/5725767/96634087-37e5ae80-12d7-11eb-9e70-91508e28ba12.png)

https://arctos.database.museum/tools/bulkloadLocality.cfm?action=table&username=jegelewicz&status=

is the URL

**To Reproduce**

**Expected behavior**

**Screenshots**

** Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
Less "bug" more "cart before horse" - I need to rebuild the things that lead up to https://github.com/ArctosDB/arctos/issues/2974, once that's resolved. Is it?

**Comment by Jegelewicz** [comment]
Well, it is for me - but I don't know if anyone besides myself, @lin-fred and @Nicole-Ridgwell-NMMNHS have looked at it...

**Comment by Jegelewicz** [comment]
I'll close this then - I can work around it.

**Comment by dustymc** [comment]
Let me know if you need SQL or whatever.
