### ISSUE TITLE
[CONTACT]

### ISSUE THREAD

**Issue by JennaMcCullough** [ArctosDB/arctos#3169]
** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **

** Outages should be reported to the contacts listed at https://arctosdb.org/arctos-down/ **

** Arctos Documentation is http://handbook.arctosdb.org/ **

** Learn more about Arctos at https://arctosdb.org/ **

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **

It's not clear if 0 means "yes" or "no" for accepted_id_fg. Could you please make this explicit? 
<img width="1013" alt="Screen Shot 2020-10-21 at 3 30 12 PM" src="https://user-images.githubusercontent.com/8632718/96789395-52408a80-13b2-11eb-9000-53d0d5fd4fdf.png">

**Comment by dustymc** [comment]
>0==require enough information to create a new Identification; 1==use the existing accepted ID and ignore anything about new Identifications

How can that be made more clear?

**Comment by JennaMcCullough** [comment]
For the documentation for “accepted_id_fg”, it is currently "0 or 1”. I think it would be clearer to users if it was “0== yes, 1== no”.

**Comment by campmlc** [comment]
Yes, I agree, and I also support clarifying the documentation on
publication ID to explicitly say to use the numeric value only from the
url.

**Comment by Jegelewicz** [comment]
@JennaMcCullough or @campmlc can you guys tell me WHERE this is happening?
