### ISSUE TITLE
[CONTACT]

### ISSUE THREAD

**Issue by JennaMcCullough** [ArctosDB/arctos#3170]
** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **

** Outages should be reported to the contacts listed at https://arctosdb.org/arctos-down/ **

** Arctos Documentation is http://handbook.arctosdb.org/ **

** Learn more about Arctos at https://arctosdb.org/ **

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **
_________________________________________________________
<img width="1029" alt="Screen Shot 2020-10-21 at 5 04 41 PM" src="https://user-images.githubusercontent.com/8632718/96799223-de0ce380-13bf-11eb-8de9-50ed2d8ba1eb.png">

I received the error while trying to batch upload citations. 
Message: ERROR: duplicate key value violates unique constraint "ix_u_citation_id" Detail: Key (publication_id, identification_id)=(10009616, 11093470) already exists.
Detail:
Check the Arctos Handbook for more information on errors.

10009616 is the ID for the publication I uploaded. I can't find any duplicate publication that has the number 11093470. There should be a place on the search page for publications (https://arctos.database.museum/SpecimenUsage.cfm) for publication ID.

**Comment by dustymc** [comment]
11093470 is the identification ID; you likely have duplicates in the file you're loading, but I can't tell without seeing the CSV.

**Comment by JennaMcCullough** [comment]
I uploaded the publication, which to my knowledge holds the ID 10009616 (https://arctos.database.museum/publication/10009616 <https://arctos.database.museum/publication/10009616>). I can’t find another paper that would be a duplicate of this publication, since I can’t search on publication ID number. When I change out the ID number on the above URL to instead include 11093470 (e.g., https://arctos.database.museum/publication/11093470 <https://arctos.database.museum/publication/11093470>), no publications are found. 
Here is the CSV

Thanks

**Comment by campmlc** [comment]
Can you zip the csv and re-attach? Github doesn't accept csv without
zipping.

**Comment by JennaMcCullough** [comment]
Its attached

**Comment by campmlc** [comment]
I still don't see it? Did you try drag and drop?

**Comment by JennaMcCullough** [comment]
Huh, I was replying via email originally. It's here now
[Book7.csv.zip](https://github.com/ArctosDB/arctos/files/5424356/Book7.csv.zip)

**Comment by dustymc** [comment]
<img width="223" alt="Screen Shot 2020-10-22 at 10 28 38 AM" src="https://user-images.githubusercontent.com/5720791/96908373-67b8c180-1451-11eb-91b8-89bc61f49465.png">

Those cause the error you're seeing. There are several more in the file.

**Comment by JennaMcCullough** [comment]
Ah. Ok. that's my mistake. Thanks Dusty
