### ISSUE TITLE
GloBI indexed https://arctos.database.museum/guid/UTEP:Inv:274 , but Arctos does not link back

### ISSUE THREAD

**Issue by jhpoelen** [ArctosDB/arctos#3172]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
GloBI indexed https://arctos.database.museum/guid/UTEP:Inv:274 , but Arctos does not seem to link back into GloBI. 

**To Reproduce**
1. Visit https://www.globalbioticinteractions.org/?accordingTo=http%3A%2F%2Farctos.database.museum%2Fguid%2FUTEP%3AInv%3A274 and observe that GloBI included https://arctos.database.museum/guid/UTEP:Inv:274 as supporting claim for that _Helicodiscus singleyanus_ interacts with _Yucca elata_ (see attached image below)
2. Link "link" to visit Arctos specimen page at https://arctos.database.museum/guid/UTEP:Inv:274 . Noticed the field "associatedTaxa" with value Yucco elata. Also, notice that GloBI does not occur in the links list.

**Expected behavior**
Expected behavior is the Arctos shows a link to GloBI for every specimen record that is associated with a species interaction claim. 

**Screenshots**
![Screenshot from 2020-10-22 16-09-33](https://user-images.githubusercontent.com/1084872/96939243-62736b00-1481-11eb-8521-28f651ddab95.png)
![Screenshot from 2020-10-22 16-07-47](https://user-images.githubusercontent.com/1084872/96939245-643d2e80-1481-11eb-8f7d-8e74fd00e5d8.png)

** Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
See also https://github.com/ArctosDB/arctos/issues/2519

In the interest of sparking conversation, this will be in the next version of Arctos (early next week, I hope). This decision should really be coming from data managers, not me.

@jhpoelen a 404 response from globi (implementing this would involve many of them, unless you can point me to a better mechanism) takes a very noticeable couple seconds - the page loads, nothing, nothing, nothing, and the link-blurb pops in. Can that be made more performant?

**Comment by jhpoelen** [comment]
@dustymc Thanks for your reply and sorry for repeating myself re: #2519 . Please feel free to close this issue as a duplicate if you'd like. I now remember that we had a similar discussion hundreds of Arctos issues ago (you guys have been busy! wow!) 

About 404 - can you please send an example of the endpoint that you queried so I can reproduce? 

About performance - yes, things can be made faster, I am just trying to optimize when needed. Hope you understand. What do you expect the response time to be?

**Comment by jhpoelen** [comment]
Note that I was unable to reproduce the 404 with:

```
$ curl -I https://api.globalbioticinteractions.org/exists?accordingTo=http%3A%2F%2Farctos.database.museum%2Fguid%2FUTEP%3AInv%3A274
HTTP/2 200 
date: Fri, 23 Oct 2020 17:14:49 GMT
content-type: text/plain;charset=ISO-8859-1
content-length: 2
```

Please confirm.

**Comment by dustymc** [comment]
Currently I'm only checking globi if we've sent explicit relationship data of a few specific types - I don't expect 404s (although they probably happen for new things and such).

If I'm to link to things you've dug out of non-relationship data, I'll just have to check everything when the "guid page" loads (unless you can suggest a better way).

```
-bash-4.1$ curl -I https://api.globalbioticinteractions.org/exists?accordingTo=http://arctos.database.museum/guid/ABC:ZYZ:ItAintThere
HTTP/1.1 404 Not Found
Date: Fri, 23 Oct 2020 17:28:20 GMT
Content-Type: text/html; charset=ISO-8859-1
Connection: keep-alive
Set-Cookie: __cfduid=d0a317ae83acbcb31c53d285199a189b71603474095; expires=Sun, 22-Nov-20 17:28:15 GMT; path=/; domain=.globalbioticinteractions.org; HttpOnly; SameSite=Lax; Secure
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Headers: origin, content-type
Access-Control-Max-Age: 1800
Cache-Control: must-revalidate,no-cache,no-store
CF-Cache-Status: DYNAMIC
cf-request-id: 05f81a163a000027397894c000000001
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?lkg-colo=16&lkg-time=1603474100"}],"group":"cf-nel","max_age":604800}
NEL: {"report_to":"cf-nel","max_age":604800}
Server: cloudflare
CF-RAY: 5e6d2c69e8652739-IAD
```
That's taking ballpark 4 seconds.

Non-404s respond somewhere under a second - they don't *feel* laggy, which is my metric at the moment.

**Comment by jhpoelen** [comment]
@dustymc thanks for pointing out that the lookup for an unknown URIs take 4s (or longer) to respond with 404. That does seem a bit tardy. I opened a separate issue on that here: https://github.com/globalbioticinteractions/globalbioticinteractions/issues/544 . 

I guess I'll have to do some homework before moving forward on a more general linking scheme for our integration. 

I am hoping that we'll figure out a more general linking scheme eventually, because then we'll be able to do stuff like: https://github.com/globalbioticinteractions/globalbioticinteractions/issues/455 . I've also seen arctos URIs being referenced in iNaturalist, but not the other way around.

**Comment by campmlc** [comment]
I believe we approached iNat about referencing/ linking back to museum
vouchers and were told they did not yet have that functionality. If they
can, we should pursue similar reciprocal linkages with them.

**Comment by campmlc** [comment]
To clarify, is the delay occurring only when attempting to create links to
Globi from associated species? We had also discussed making verbatim host
ID a discoverable link through Globi, which would be similar in that this
field would contain free text and common names.

**Comment by dustymc** [comment]
The delay occurs when a link to globi 404s for some reason (in which case I don't want to display it - no reason to send users to never-never land).

If the link comes from data - we're asserting a relationship - then I can (more or less) know what's going to happen at globi so I don't both testing things that probably aren't there. Any weirdness should at least be uncommon.

If globi's digging information out of some unpredictable place - anywhere other than asserted relationships - then I'll have to test everything, most of it will fail, and the obvious delay is sort of annoying. 

The immediate question for ya'll is if we want to deal with "sort of annoying" for the time being. I'll need an answer before ~Monday when the next release goes out, but it's really simple to turn this off and on so whatever.

The bigger question for The Community is if we want to link these data at all - some of them will probably be "this definitely has nothing to do with {species}" types of things, some (perhaps most) will be informative, and might lead to "gee, THIS doesn't usually hang out with THAT, maybe we need to check the ID." I think this is very cool, but it's not my data....

**Comment by campmlc** [comment]
I support trying and seeing if we can find a solution that works.
Hopefully we can resolve any problems that may emerge.  Making these
relationship data discoverable is worth the attempt, and annoying problems
may engage the community to brainstorm a workaround.

**Comment by jhpoelen** [comment]
@dustymc @campmlc re: performance - I can try and work on this today. I am assuming page loading is not affected on your end, just a little more time to finish populating the links. 

What I appreciate about the current Arctos links is that your community curates them, making them high quality. However, other GloBI indexed resource, like iNaturalist or non-Arctos collection management systems, may also include references to Arctos specimen. Wouldn't it be neat to point folks to that? 

I interpret the current Arctos --> GloBI linkages as: "Hey, it looks like GloBI has an interaction claim about this specimen. Click on this link to check it out."

This said, I'd like to more sure that you are comfortable populating links in your carefully curated spceimen pages. So, I am pretty excited about this discussion and eager to hear more of your thoughts on this.

**Comment by jhpoelen** [comment]
> I support trying and seeing if we can find a solution that works. Hopefully we can resolve any problems that may emerge. Making these relationship data discoverable is worth the attempt, and annoying problems may engage the community to brainstorm a workaround.

+1 for soliciting communal wisdom and experimentation

**Comment by dustymc** [comment]
Awesome, thanks!

No there's nothing fatal about the delay, the links just pop in a bit slower than ideal.

>"Hey, it looks like GloBI has an interaction claim about this specimen. Click on this link to check it out."

Good interpretation, and it's in the same "pane" as "Oh, iDigBio has done something crazy with some random thing for some reason" - perhaps we need a better label or something to differentiate from "our" data.

>point folks to that?

This is another conversation we need to have. "This bug has something to do with an alleged willow" is probably something most collections would choose to leave out of the "formal" data. "This bug was living on THAT willow, which is cataloged in some other collection (perhaps including "cataloged" as a photo in iNat) is likely something that some or most collections would be interested in having as "data" (eg vetting and loading as relationships). I'm hoping globi will "suggest" those links at some point, or if I'm going to check everything I could probably do so (but in a bit of a haphazard fashion).

**Comment by campmlc** [comment]
We do currently reference non Arctos cms, for example
https://arctos.database.museum/guid/MSB:Mamm:210452
This is a same individual as relationship, but in this same series we also
have as yet uncataloged relationships between parasites and hosts. But we
can't find a way to link directly to these records, and have considered
linking via FB IF, but that is difficult because of lack of or uncertainty
about shared identifiers. Perhaps GLOBI could help with this?

**Comment by jhpoelen** [comment]
>This is another conversation we need to have. "This bug has something to do with an alleged willow" is probably something most collections would choose to leave out of the "formal" data. "This bug was living on THAT willow, which is cataloged in some other collection (perhaps including "cataloged" as a photo in iNat) is likely something that some or most collections would be interested in having as "data" (eg vetting and loading as relationships). I'm hoping globi will "suggest" those links at some point, or if I'm going to check everything I could probably do so (but in a bit of a haphazard fashion). 

GloBI captures basis of record and information like occurrenceIds for both subject and object of a recorded interaction. So, you could make the distinction of interaction claims based on specimen->specimen (e.g., this bug -> that tree) vs interaction and, weaker claims like specimen->some taxon (e.g., this bug -> some tree of type [taxon]).

**Comment by campmlc** [comment]
GBIF sorry phone autocorrected

**Comment by jhpoelen** [comment]
> We do currently reference non Arctos cms, for example
https://arctos.database.museum/guid/MSB:Mamm:210452
This is a same individual as relationship, but in this same series we also
have as yet uncataloged relationships between parasites and hosts. But we
can't find a way to link directly to these records, and have considered
linking via FB IF (ed. GBIF), but that is difficult because of lack of or uncertainty
about shared identifiers. Perhaps GLOBI could help with this?

Yes, sounds like that fits right into GloBI's mission! Please provide a specific use case and create issue at https://github.com/globalbioticinteractions/globalbioticinteractions/issues/new or elsewhere .

**Comment by dustymc** [comment]
To be clear, Arctos can form relationships to anything with a URL, and there are many of those (although most don't have the explicit relationship component). I believe @campmlc is wanting to link to things that do **not** have a URL - we know the relationship, there's just no way to assert it. (And "know" is a bit optimistic at times - we might know there's a shared identifier, but we generally don't know how unique it is - Collector Number One might "resolve" to thousands of things.)

**Comment by campmlc** [comment]
In the case of AMNH, we do have explicit catalog item to catalog item
relationships via known guids, just not resolvable urls on their end.

**Comment by jhpoelen** [comment]
@dustymc @campmlc I've just confirmed that https://arctos.database.museum/guid/UTEP:Inv:274 now includes a link to GloBI. Hurrah! 

Hoping to discuss ways in our upcoming meeting, and continued github discussions, to help make AMNH record links more explicit, but that is a separate topic discussed in https://github.com/globalbioticinteractions/globalbioticinteractions/issues/546 . 

See attached screenshots and https://globalbioticinteractions.org/?accordingTo=http://arctos.database.museum/guid/UTEP:Inv:274 

![Screenshot from 2021-05-25 15-23-27](https://user-images.githubusercontent.com/1084872/119576233-35679d80-bd6d-11eb-8198-40df3f5cfb94.png)
![Screenshot from 2021-05-25 15-19-27](https://user-images.githubusercontent.com/1084872/119576238-3698ca80-bd6d-11eb-91cb-9a41875a0018.png)
