### ISSUE TITLE
Bulkloader for Media Metadata: "This directory structure is not supported"

### ISSUE THREAD

**Issue by jebrad** [ArctosDB/arctos#3173]
I am attempting to use Enter Data > Batch Tools > Bulkload Media Metadata >
http://arctos.database.museum/tools/BulkloadMedia.cfm

But ever time I enter a Directory URL and Select "go" - the Bulkloader Form shows up with a last line "This directory structure is not reported" (see attached image) and the "build/rebuild the table" button does nothing.
[directory structure is not supported.pdf](https://github.com/ArctosDB/arctos/files/5440415/directory.structure.is.not.supported.pdf)

Trying to use this Directory URL: https://web.corral.tacc.utexas.edu/UWBM/Test/ 

Other TACC directories show the same "...not reported" message, and their structure seems OK.   I attempted to troubleshoot using https://handbook.arctosdb.org/how_to/How-to-Bulkload-Media-Metadata.html.

I was able to use this tool back in March, I am not sure whether I have forgotten how to use it, or if there is a genuine bug. 

Please help, Also please tell me if submitting this Bug report was not the way to do this.
Thanks, Jeff

Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

** Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
Yes this is the proper place for this.

Looks like TACC just isn't serving XML under the hood any more. I'll ping them and ask if that can be revived.

**Comment by jebrad** [comment]
Hi Dusty - Any word from Texas?  Should I start looking into work-arounds?

**Comment by dustymc** [comment]
TACC said they'd look into it, I haven't heard back. I suspect best case is post-pandemic, and who knows what that might mean.

**Comment by jebrad** [comment]
Thanks for looking into this Dusty.  Is there any way for me to do the XML or otherwise find a workaround without the bulkloader?
I assume that images are still to be stored at TACC, this is just a linking issue.
Jeff

**Comment by dustymc** [comment]
It depends on how the data are organized - eg if the image file names contain a catalog number or barcode or something of the sort and you have that in a spreadsheet, you can probably extract what you need to create a bulkloader file from that. If you'll provide whatever you have I can try to figure something out.

@mkoo @ccicero have loaded many thousands of images without using the (maybe-dead) pull feature, they might be able to provide guidance as well.

**Comment by jebrad** [comment]
Thanks - I remember seeing the alternate instructions for extracting that info from a spreadsheet.  I will give a try at that and ask again here when I get stuck, probably early in the process.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/internal/issues/119
