### ISSUE TITLE
bulkloader column order

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3175]
I can't find the issue, but we discussed the order of columns in the bulkloader. I'm trying to do that while I'm dealing with https://github.com/ArctosDB/arctos/issues/1460.

The spreadsheet is https://docs.google.com/spreadsheets/d/1SGbLdsB1RkF8O4nCn-V4dg8gTdSaW_sgobd5zdsu-2c/edit?ts=5ec6f4d8#gid=0

I added the things that have changed since that was developed and an explicit sort column. I'm using the "consensus" column, which was formerly Andy's sort.

Is everyone still OK with that as it is? I noticed that otherIDs are scattered around, which is fine with me if it's intentional. Feel free to rearrange, but let me know here if you do.

For anyone not in the loop, this will control the "default" sort order of the bulkloader table, which is used for things like downloads. The datatables form has an explicit sort option which overrides anything we might do here, and Arctos doesn't care how columns are ordered for things like uploads.

I'll just run with whatever's there if I don't hear otherwise in the very near future.

@Jegelewicz @campmlc @ccicero @acdoll 

Please tag anyone I missed.

**Comment by ewommack** [comment]
Looks good to me. I think I could bulkload with that list just fine.

**Comment by campmlc** [comment]
I believe that the consens is the most recent consensus
