### ISSUE TITLE
 Harold W. Manter Laboratory of Parasitology Collection (HWML)  missing from Vertnet RSS 

### ISSUE THREAD

**Issue by jhpoelen** [ArctosDB/arctos#3176]
Hi!

GloBI uses the Vertnet RSS IPT feed to track all DwC-A that Arctos makes available for their related collections. 

Today, I noticed that a parasite of reference from https://arctos.database.museum/guid/MSB:Mamm:232346 to specimen http://arctos.database.museum/guid/HWML:Para:66271 could not be resolved by GloBI. The bidirectional  link works as expected in the Arctos specimen web pages.

After checking the Vernet RSS IPT , using:

```curl "http://ipt.vertnet.org:8080/ipt/rss.do" | grep HWML```

,  I noticed that the Arctos managed HWML collection does not appear to be listed. 

Is these a reason why the HWML collection is not included in vertnet RSS feed? I am looking in the wrong place?

Thanks in advance for your response.
-jorrit

PS If there's a better way to track all Arctos records than using the Vertnet RSS feed , please let me know.

**Comment by campmlc** [comment]
Yes, we were discussing this in November - should be one of the backlogged collections in progress, @dbloom 
All arctos data for all collections are publicly available through the main Arctos portal https://arctos.database.museum/. But we publish to external resources and aggregators via the VertNet IPT.

**Comment by campmlc** [comment]
@dustymc

**Comment by jhpoelen** [comment]
ok @campmlc thanks for confirming that HWML is waiting to be added to VertNet . Would you like to keep this issue open until the addition to VertNet is complete?

**Comment by tucotuco** [comment]
Yes, please.

**Comment by tucotuco** [comment]
Yes. This process is pending work that Mariel is doing with that
collection. We're ready to make it public via the VertNet IPT as soon as
all of the collection issues have been resolved. Wherever that is.

David Bloom
VertNet Coordinator

Phone: +01 510 859 7773
Email: dbloom@vertnet.org
Skype: dabblepop
Hangouts: dbloom@vertnet.org

**Comment by campmlc** [comment]
This collection should be ready to publish to the IPT. I'll check the
metadata.

**Comment by campmlc** [comment]
Here is the EML metadata. OK to publish @tucotuco @dbloom 

<eml:eml xmlns:eml="eml://ecoinformatics.org/eml-2.1.1"
	xmlns:dc="http://purl.org/dc/terms/"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="eml://ecoinformatics.org/eml-2.1.1 http://rs.gbif.org/schema/eml-gbif-profile/1.1/eml.xsd"
	packageId="f85f5c5c-ce02-4337-9317-23fe54769ff2/v1.3" system="http://gbif.org" scope="system"
	 xml:lang="eng">
<dataset>
	<title xml:lang="eng">Harold W. Manter Laboratory of Parasitology Collection (HWML) Parasite specimens (Arctos)</title>
	<creator>
		<individualName>
			<givenName>Scott</givenName>
			<surName>Gardner</surName>
		</individualName>
		<phone>402-472-3334</phone>
		<electronicMailAddress>slg@unl.edu</electronicMailAddress>
	</creator>
	<creator>
		<individualName>
			<givenName>Gabor</givenName>
			<surName>Racz</surName>
		</individualName>
		<electronicMailAddress>gracz2@unl.edu</electronicMailAddress>
	</creator>
	<metadataProvider>
		<individualName>
			<givenName>Gabor</givenName>
			<surName>Racz</surName>
		</individualName>
		<electronicMailAddress>gracz2@unl.edu</electronicMailAddress>
	</metadataProvider>
	<pubDate>2020-11-03</pubDate>
	<language>eng</language>
	<abstract>
		<para>The Harold W. Manter Laboratory of Parasitology (HWML) at the University of Nebraska-Lincoln represents more than 90,000 cataloged records of parasites collected from every continent and ocean around the world. The parasite collection, which is part of the University of Nebraska State Museum, is the second largest in the Western Hemisphere and is one of the the most important extant centers for the study of systematic parasitology. The Manter Laboratory was established 29 March 1971. In 1981 the HWML was designated one of three National Resource Centers for Parasitology, and many students associated with the lab have been trained in systematics as well as other aspects of parasitology. Three Henry Baldwin Ward Medalists (the highest annual award that is given by the American Society of Parasitologists) were students in Parasitology and in the lab while Professor Mary Hanson Pritchard directed the laboratory (Professor Pritchard is now Curator Emeritus). In the past 5 years, more than 150 publications have resulted from research both in the HWML and from specimens loaned from, or deposited into, the HWML as types or vouchers. On an annual basis we process more than 50 loans outgoing per year and we receive thousands of specimens into the collection from researchers world-wide for archiving and safe storage of valuable voucher specimens. </para>
	</abstract>
	<keywordSet>
		<keyword>Occurrence</keyword>
		<keywordThesaurus>GBIF Dataset Type Vocabulary: http://rs.gbif.org/vocabulary/gbif/dataset_type.xml</keywordThesaurus>
	</keywordSet>
	<keywordSet>
		<keyword>Specimen</keyword>
		<keywordThesaurus>GBIF Dataset Type Vocabulary: http://rs.gbif.org/vocabulary/gbif/dataset_type.xml</keywordThesaurus>
	</keywordSet>
	<additionalInfo>
		<para>
			Arctos Data Ownership and Use: http://arctosdb.org/home/data/
		<para>
	</additionalInfo>
	<intellectualRights>
		<para>
			License Description: Attribution-NonCommercial
			<ulink url="http://creativecommons.org/licenses/by-nc/3.0"><citetitle>CC BY-NC</citetitle></ulink>
		</para>
	</intellectualRights>
	<distribution scope="document">
		<online>
			<url function="information">http://hwml.unl.edu</url>
		</online>
	</distribution>
	<coverage>
		<geographicCoverage>
			<geographicDescription>global</geographicDescription>
			<boundingCoordinates>
				<westBoundingCoordinate></westBoundingCoordinate>
				<eastBoundingCoordinate></eastBoundingCoordinate>
				<northBoundingCoordinate></northBoundingCoordinate>
				<southBoundingCoordinate></southBoundingCoordinate>
			</boundingCoordinates>
		</geographicCoverage>
		<taxonomicCoverage>
			<generalTaxonomicCoverage>Platyhelminthes, Monogenea, Trematoda, Cestoda, Nematoda, Nematomorpha, Acanthocephala, Arthropoda (parasitic mites, ticks, fleas, lice, crustaceans)</generalTaxonomicCoverage>
			<taxonomicClassification>
				<taxonRankName></taxonRankName>
				<taxonRankValue></taxonRankValue>
			</taxonomicClassification>
		</taxonomicCoverage>
	</coverage>
	<purpose>
		<para>For research and education in parasitology.</para>
	</purpose>
	<maintenance>
		<description>
		</description>
		<maintenanceUpdateFrequency>monthly</maintenanceUpdateFrequency>
	</maintenance>
	<contact>
		<individualName>
			<givenName>Gabor</givenName>
			<surName>Racz</surName>
		</individualName>
		<electronicMailAddress>gracz2@unl.edu</electronicMailAddress>
	</contact>
	<methods>
		<methodStep>
			<description>
				<para></para>
			</description>
		</methodStep>
	</methods>
</dataset>
<additionalMetadata>
	<metadata>
		<gbif>
			<dateStamp>2020-11-03THH:11:SS</dateStamp>
			<hierarchyLevel>dataset</hierarchyLevel>
			<citation>Harold W. Manter Laboratory of Parasitology Collection. Individual specimens should be cited as HWML- followed by the integer catalog number in printed papers or as HWML:Para: followed by catalog number in digital databases and links (GBIF, GenBank, etc.)</citation>
			<collection>
				<parentCollectionIdentifier>HWML</parentCollectionIdentifier>
				<collectionIdentifier>HWML:Para</collectionIdentifier>
				<collectionName>Harold W. Manter Laboratory of Parasitology Collection (HWML) Parasite specimens</collectionName>
			</collection>
			<specimenPreservationMethod></specimenPreservationMethod>
			<livingTimePeriod></livingTimePeriod>
		</gbif>
	</metadata>
</additionalMetadata>
</eml:eml>
[HWML EML for VertNet IPT.docx](https://github.com/ArctosDB/arctos/files/5483446/HWML.EML.for.VertNet.IPT.docx)

**Comment by jhpoelen** [comment]
Just stumbled across this issue and confirmed that HWML is still waiting to be added to vertnet by running

```
$ curl "http://ipt.vertnet.org:8080/ipt/rss.do" | grep HWML
```

and finding 0 hits. 

Am assuming that y'all are pretty busy and that adding Harold W. Manter Laboratory of Parasitology Collection (HWML) to vertnet is pending. Thanks for all your hard work!

**Comment by campmlc** [comment]
Yes, my understanding is that it is in the cue. @dbloom @tucotuco 
Thanks for checking!

**Comment by seltmann** [comment]
@tucotuco @campmlc @jhpoelen  Checking back about the HWML collection on vertnet. I am still not seeing it in the RSS feed. We are hoping to include this collection in the next [Terrestrial Parasite Tracker indexed biotic interactions and review summary data publication](http://doi.org/10.5281/zenodo.4070039)

Thanks again for your help,
Katja

**Comment by campmlc** [comment]
I'm not sure why this collection has not been published. There is no holdup
on the Arctos end.

**Comment by dbloom** [comment]
@seltmann @campmlc The loose end is my pending question to Arctos: Who is the publishing organization? As far as I can tell HWML is not a registered publisher with GBIF. Univ or Nebraska is in SciCol but not a registered publisher. The U of Neb State Museum is a publisher (https://www.gbif.org/publisher/9b049850-d958-11da-9047-b8a03c50a862), but nobody has confirmed that this is the correct entity to which I should register this collection.

Clarification is needed - and possibly the registration of a new publisher to GBIF. I can do that, I just need to know where this collection belongs. Otherwise, the collection is ready to go.

**Comment by campmlc** [comment]
I will confirm with the Manter lab right away. To my knowledge they are
part of U N State Museum.

**Comment by dbloom** [comment]
@campmlc Before this fades from memory again, have you heard anything from Manter? This is what happened last time - we asked and then moved on without an answer. Would be good to get this finished. Let me know if I need to deplay an iNag (tm) and I will.

**Comment by dustymc** [comment]
Do we need to add something to the model, and/or pass it on with the EML?

**Comment by dbloom** [comment]
@dustymc No need to change the model. This is a one-off residual of conversations that stems from parasite collection consolidations and uncertainty about whether or not this particular collection wanted to its own "organization" on GBIF because it's acronym is not the expected UNSM that the other collections at Neb use, inkages to Smithsonian, etc... You know, people, politics, blah. Just trying to be certain that how they want to be represented so we don't have to undo and redo a bunch of crap.

If someone wants to make an executive dcn about UNSM I can have them up in a few minutes and that would make @seltmann super happy.

**Comment by campmlc** [comment]
Yes, I heard back via email. @gracz-UNL  was going to try to email you, but in the meantime, the answer is yes, we need to move forward with publishing.  
There are currently University of Nebraska State Museum records for other collections, and also some older Manter lab records at GBIF. The older Manter lab resource should be deprecated in favor of the Arctos data via the VertNet IPT. But this needs to be associated with the other material from the UNSM - possible?
Here is reply from @gracz-UNL:

Thanks Mariel,

There are some "emergency" situations in the lab that I have to deal with. Nothing major but annoying. As you know, we use the green vial caps with teflon lining. I placed an order for them, but the company won't be able to deliver those. Students in the lab are running low on both vials (there is a supply shortage for those too) and caps.

Here is the email that I wrote yesterday.
-------------------------
Hi David,

As you mentioned: "University of Nebraska State Museum" the official name of our institution is a publisher at GBIF.
https://www.gbif.org/publisher/9b049850-d958-11da-9047-b8a03c50a862

According the the short description:

Administrative contact Thomas Labedz ---> still CORRECT (email: tlabedz1@unl.edu)
Description http://www-museum.unl.edu/ (OUT OF DATE) update to -->https://museum.unl.edu/
At this point, GBIF stores 4 collections under Univ. Nebr. State Museum: Mammal, Bird, Herp, and Fish Collection.

As a fifth one, you can add "Parasite Collection - Harold W. Manter Laboratory of Parasitology" and add my name as contact person (Gabor Racz - gracz2@unl.edu). I can be an alternate contact person next to Tom Labedz, our offices are just a few doors apart in the same building.


Here is info on populating the specific page:
Description
The Harold W. Manter Laboratory of Parasitology (HWML) was established 29 March 1971 at the University of Nebraska - Lincoln as a new division in the University of Nebraska State Museum (UNSM). The founding core of the collection was based on Dr. Manter's research collection of parasitic trematodes of oceanic fishes. In 1981 the HWML was designated as one of three National Resource Centers for Parasitology and many students associated with the lab have been trained in systematics as well as other aspects of parasitology. Three Henry Baldwin Ward Medalists (the highest annual award that is given by the American Society of Parasitologists) were students in Parasitology and in the lab while Professor Mary Hanson Pritchard directed the laboratory (Professor Pritchard is now Curator Emeritus). In the past 5 years, more than 150 publications have resulted from research both in the HWML and from specimens loaned from, or deposited into, the HWML as types or vouchers. On an annual basis we process more than 20 outgoing loans per year and we receive thousands of specimens into the collection from researchers world-wide for archiving and safe storage of valuable voucher specimens.  

Temporal scope
January 1, 1909 - present
Geographic scope
Worldwide with approximately 80% of the specimens from North America.

Taxonomic scope
Phylum Platyhelminthes - flatworms Class: Cestoda, Trematoda, Monogenea
Phylum Nematoda, Phylum Nematomorpha, Phylum Acanthocephala
Phylum Arthropoda including Acari (mites and ticks), Siphonaptera (fleas), Phthiraptera (lice).
plus some minor parasitic specialized taxonomic groups: Myxospora, "Protozoa", Pentastomida, etc.


Additional info
http://vertnet.org/resources/norms.html

Contacts
Gabor R. Racz
Originator Metadata author Administrative point of contact
Collection Manager
Harold W. Manter Laboratory of Parasitology, University of Nebraska State Museum
W529 Nebraska Hall
Lincoln 68588-0314 NE
United States of America
gracz2@unl.edu
+01 402-472-3334
http://hwml.unl.edu/

Scott L. Gardner
Administrative point of contact
Curator
Harold W. Manter Laboratory of Parasitology, University of Nebraska State Museum
W529 Nebraska Hall
Lincoln 68588-0314 NE
United States of America
gracz2@unl.edu
+01 402-472-3334
http://hwml.unl.edu/

Data description
Metadata language English
Data language English
GBIF registration

hosted by Arctos (https://arctos.database.museum/SpecimenSearch.cfm?guid_prefix=HWML%3APara)

Citation
Scott L. Gardner and Gabor R. Racz (2021). University of Nebraska State Museum - Parasitology. Harold W. Manter Laboratory of Parasitology. University of Nebraska State Museum.

David: let me know what other information you will need or what needs to be tweaked.

**Comment by campmlc** [comment]
My understanding is that the reason that USNM wasn't used for Manter has to do with misunderstandings during portal creation some many years ago now, so now all the Arctos records have guids as HWML:Para.

**Comment by campmlc** [comment]
And we should be able to use the Arctos generated EML file.

**Comment by dbloom** [comment]
Thanks @gracz-UNL @campmlc et al.

So, as I understand it I need to:

1. update the metadata in the new resource to reflect the changes provided above (I've already used the EML generator for this, but I will confirm that the metadata is correct and update as necessary).
2. notify GBIF that the old "orphaned" dataset (https://www.gbif.org/dataset/8117733e-f762-11e1-a439-00145eb45e9a) can be removed from the index.
3. When cleared by GBIF publish the new Manter collection as a part of UNSM.

Am I missing anything?

**Comment by campmlc** [comment]
Sounds correct to me!

**Comment by dbloom** [comment]
Published.  https://www.gbif.org/dataset/c43384a9-8d9d-40c0-8cda-40ad47d2d69d  60+k records and images indexed.

Updates should occur on the 2nd of each month. @seltmann 

I will let @campmlc or @gracz-UNL confirm the publication and resolve this issue.

**Comment by seltmann** [comment]
@dbloom @campmlc @gracz-UNL Thank you for making this happen! 

What lovely flea photographs. Awesome!

**Comment by campmlc** [comment]
Yes, more host para linkages pending to this collection!

**Comment by jhpoelen** [comment]
@campmlc @dbloom @seltmann @tucotuco @dustymc @gracz-UNL thanks for helping to make Harold W. Manter Laboratory of Parasitology Collection easier to access!

**Comment by jhpoelen** [comment]
I was able to confirm that Manter lab interaction are now being read by GloBI. I've attached a list of interactions to this issue generated by:

```
$ elton update globalbioticinteractions/unl-nsm && elton interactions 
```

So far a little shy of 900 interaction records, and, as @campmlc intuited, these interaction records are linking specimen to specimen into the msb mamm records. Very cool to see this rich data coming out of your collections!

[globi-indexed-manter-interactions-2021-06-02.tsv.txt](https://github.com/ArctosDB/arctos/files/6588017/globi-indexed-manter-interactions-2021-06-02.tsv.txt)

**Comment by jhpoelen** [comment]
And via https://travis-ci.com/github/globalbioticinteractions/unl-nsm/jobs/510571696#L247 

```
   _____ _       ____ _____   _____            _                
  / ____| |     |  _ \_   _| |  __ \          (_)               
 | |  __| | ___ | |_) || |   | |__) |_____   ___  _____      __ 
 | | |_ | |/ _ \|  _ < | |   |  _  // _ \ \ / / |/ _ \ \ /\ / / 
 | |__| | | (_) | |_) || |_  | | \ \  __/\ V /| |  __/\ V  V /  
  \_____|_|\___/|____/_____| |_|  \_\___| \_/ |_|\___| \_/\_/   
 | |           |  ____| | |                                     
 | |__  _   _  | |__  | | |_ ___  _ __                          
 | '_ \| | | | |  __| | | __/ _ \| '_ \                         
 | |_) | |_| | | |____| | || (_) | | | |                        
 |_.__/ \__, | |______|_|\__\___/|_| |_|                        
         __/ |                                                  
        |___/                       
Review of [local] started at [2021-06-03T00:05:53+00:00].

updating [local]... done.
creating review [local]... done.
listing interactions [local]... done.
listing taxa [local]... done.
listing nanopubs [local]... done.

Review of [globalbioticinteractions/unl-nsm] included:
  - 861 interaction(s)
  - 0 note(s)
  - 2 info(s)
Hurray! [globalbioticinteractions/unl-nsm] passed the GloBI review.
```

**Comment by gracz-UNL** [comment]
> Published. https://www.gbif.org/dataset/c43384a9-8d9d-40c0-8cda-40ad47d2d69d 60+k records and images indexed.
> 
> Updates should occur on the 2nd of each month. @seltmann
> 
> I will let @campmlc or @gracz-UNL confirm the publication and resolve this issue.

Hi,
I spotted one mistake that I made: the zip code for Scott Gardner and me (Gabor Racz) has a typo. 
The correct zip code is 68588-0514 NE

Thank you,
Gabor

**Comment by dbloom** [comment]
corrected and republished
