### ISSUE TITLE
 bulkloader stage needs a DELETE option

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3177]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I cannot delete a row from the bulkloader.

**To Reproduce**
https://arctos.database.museum/Bulkloader/BulkloaderStageCleanup.cfm?action=ajaxGrid

I have over 5K rows in the bulkloader - one will not load because it is a duplicate. Tried entering DELETE in LOADED column and refreshing. Row is still there.

**Expected behavior**
Upon refresh the DELETEd roww will be gone

**Screenshots**
![image](https://user-images.githubusercontent.com/5725767/97498817-78c27080-1932-11eb-8269-be9c16ebd50e.png)

** Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
That blurb is just a few things strung together in a confusing way. Delete is hourly. I don't think there's a bug.

<img width="945" alt="Screen Shot 2020-10-28 at 2 32 54 PM" src="https://user-images.githubusercontent.com/5720791/97499159-9db2e580-192a-11eb-838f-7b626baca6f0.png">

**Comment by Jegelewicz** [comment]
But we aren't supposed to leave data in there because it is single user....

This was not how it used to work.

**Comment by dustymc** [comment]
Oh - you're in the stage, that's bad copy-pasta! There's never been a delete from there, as far as I can remember....

**Comment by Jegelewicz** [comment]
I am pretty sure there was! When only one row is a problem, deleting it and moving on is so much easier than starting all over....

**Comment by dustymc** [comment]
I'll see what I can come up with.

**Comment by dustymc** [comment]
Derp - I just added bulkloader_stage to the function, it should now be doing the same thing on the same schedule.

I'm not 100% sure about permissions but you might be able to ``select bulkloader_autodelete()`` in writesql as well if you don't want to wait on the scheduler.
