### ISSUE TITLE
Weird response from Agent Bulkloader

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3178]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Sometimes once a message appears in the agent bulkloader results, it continues to appear on multiple items that follow.

**To Reproduce**
Load a file to the Agent Bulkload Tool and validate. Get some results.
Syd Anderson is flagged as already existing, but then Syd Anderson appears as a possible duplicate in several following rows.

**Expected behavior**
Syd Anderson is clearly not a possible duplicate of W. B. Hendrix...

**Screenshots**
![image](https://user-images.githubusercontent.com/5725767/97502244-5cc1cd80-1938-11eb-9a37-39f1f34b3fca.png)

** Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
@Jegelewicz do you have the data handy? I need something to test with.

**Comment by Jegelewicz** [comment]
[Uploading Teresa splitAgentNames(1).zip…]()

**Comment by dustymc** [comment]
File didn't load

**Comment by Jegelewicz** [comment]
That's odd, because it loaded for me! I'll look at it.

**Comment by Jegelewicz** [comment]
[Copy of Teresa splitAgentNames.zip](https://github.com/ArctosDB/arctos/files/5468125/Copy.of.Teresa.splitAgentNames.zip)
