### ISSUE TITLE
Part Bulkload Tool not accepting agent name

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3182]
Loaded stuff to the Part Bulkload Tool, after validation receive this status:

![image](https://user-images.githubusercontent.com/5725767/97900016-55634100-1cf7-11eb-88fa-b9b9a5e1d3e1.png)

But the date looks OK to me...

![image](https://user-images.githubusercontent.com/5725767/97899988-4a101580-1cf7-11eb-94ed-484584a9eb9e.png)

**Comment by Jegelewicz** [comment]
[Part Bulkloads.zip](https://github.com/ArctosDB/arctos/files/5476894/Part.Bulkloads.zip)

**Comment by dustymc** [comment]
I think duct taped back together for next release - need to prioritize https://github.com/ArctosDB/arctos/issues/2603, it's a mess in there.

**Comment by Jegelewicz** [comment]
OK, dates work and stuff validates, but then this on load:

![image](https://user-images.githubusercontent.com/5725767/98261964-48865d80-1f42-11eb-9766-e281343df6f9.png)

An error occurred while processing this page!
Message: No matching function [GETAGENTID] found
Detail:
Check the Arctos Handbook for more information on errors.

This message has been logged as 75ED7416-E3B8-427C-92624600870A46BA Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue.
