### ISSUE TITLE
part attribute standardization

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3183]
Ref: https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecpart_attribute_type

I'd like to change

* ``Accession`` to ``accession``
* ``Other ID`` to ``part identifier`` (or something that's not abbreviated and is all lower case)

Objections or better ideas?

**Comment by Jegelewicz** [comment]
I'm OK with that. @campmlc is the lowercase to accession OK with you?

**Comment by campmlc** [comment]
Yep, that works!

**Comment by acdoll** [comment]
sounds good to me

**Comment by dustymc** [comment]
Done
```
-- add to code table then
update specimen_part_attribute set attribute_type='accession' where attribute_type='Accession';
UPDATE 51312

-- delete from code table
-- add to code table then
update specimen_part_attribute set attribute_type='part identifier' where attribute_type='Other ID';
UPDATE 8102

-- delete from code table
```
