### ISSUE TITLE
Show all entered parts in the Add More tab in Data Entry

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3184]
Currently, if the "Add More" tool is used to add additional specimen parts with or without part attributes, only the new part being added is visible. Once the part is added, it is no longer visible via Data Entry. In this scenario, there is no way for a student entering data to know whether or not they already entered a particular part, or to catch any errors or duplicates. 
Request: Add pre-entered parts to be visible in this tool, or make this tool resemble the existing Add Part form in Data Entry, so that all entered parts and associated data are visible from a single screen.
This is an interface issue that is impeding adoption of #1460

**Comment by dustymc** [comment]
>no longer visible via Data Entry

<img width="263" alt="Screen Shot 2020-11-03 at 11 27 49 AM" src="https://user-images.githubusercontent.com/5720791/98031647-a6db0100-1dc7-11eb-9617-e99f93a713a5.png">

<img width="293" alt="Screen Shot 2020-11-03 at 11 27 55 AM" src="https://user-images.githubusercontent.com/5720791/98031660-ad697880-1dc7-11eb-9e0f-6b1973f3628d.png">

It kinda is, but I'll add that summary on the new part popup.

>all entered parts and associated data are visible from a single screen

That's a different thing, these data are in two places (which may or may not be saved etc). I can see if I can drag a summary from the bulkloader into the popup if that does what you're asking?

https://github.com/ArctosDB/arctos/issues/2603 needs to happen before this.

**Comment by campmlc** [comment]
Sounds good, and yes, I think that works.
