### ISSUE TITLE
Restructure Higher Geography

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3186]
This issue is related to work being completed by our Arctos intern.

Except for Continent_Ocean, Country (Admin_0), State_Prov (Admin_1), County (Admin_2 - AK Quads), all other HG fields should be attributes of the locality, which includes:

Island - will need to create a code table currently this field is free text

Island group - just direct attribute to [current code table](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctisland_group) see example at http://test.arctos.database.museum/guid/UTEP:Herb:80112. related to https://github.com/ArctosDB/arctos/issues/1362

Sea - suggest transitioning this to "waterbody" - see https://github.com/ArctosDB/arctos/issues/2876

Quad Map - AK Quads transition to "County", all others form a new code table as this is currently a free text field

Drainage - will need to create a code table currently this field is free text see https://github.com/ArctosDB/arctos/issues/2875

Feature -  just direct attribute to [current code table](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctfeature) related to https://github.com/ArctosDB/arctos/issues/1362

May want to add "informal geography" this way - see https://github.com/ArctosDB/arctos/issues/2416

This structure would allow for the addition of multiple island groups, features, and bodies of water (Gulf of Mexico, Mobile Bay) and keep higher geography (other than continent) limited to administrative divisions, which would put our HG more in line with Darwin Core - see https://dwc.tdwg.org/terms/#dwc:higherGeography.

It would also help alleviate issues such as https://github.com/ArctosDB/arctos/issues/1278

**Comment by dustymc** [comment]
What is the goal behind this? This would give up a huge amount of "authoritativeness" and I'm not seeing what we'd get in return.

**Comment by tucotuco** [comment]
It also serms to be a mix of aligning with Darwin Core and not alinging
with it. Little-known fact: Darwin Core has island an islandGroup because
of the data model Arctos from which Arctos is derived.

**Comment by Jegelewicz** [comment]
> It also serms to be a mix of aligning with Darwin Core and not alinging with it.

Because that is how we roll. But I think this would get us a leeeetle more aligned?

> Little-known fact: Darwin Core has island an islandGroup because of the data model Arctos from which Arctos is derived.

LOL

**Comment by Jegelewicz** [comment]
BTW - part of the reason for this is being able to use an outside source for political boundaries like GADM.

**Comment by sharpphyl** [comment]
Just to clarify, are you proposing that we have a field for "waterbody" that would include seas (and lakes and rivers?) but oceans would remain in a different field "Continent/Ocean"?  Is that Darwin core?

What is the difference between a "drainage" and a "waterbody"?  Isn't the Gulf of Mexico both?

Will you link Islands to the Island Group and to the higher geography for consistency?

#1278 is still open.  What are the criteria for island status?  Size?  Population?  Historic status?  Number of specimens from there?

**Comment by dustymc** [comment]
<img width="380" alt="Screen Shot 2020-11-06 at 6 44 33 AM" src="https://user-images.githubusercontent.com/5720791/98378967-91e6b380-1ffb-11eb-9b16-70bd30018b86.png">

Gray squiggly line is a waterbody.

Yellow smudge is a drainage.

>Isn't the Gulf of Mexico both?

The drainage would be mostly dirt, no saltwater, partially in Canada.

I'd be OK with "waterbody" as long as there's a spatial border and we don't just sorta fade off into the Caribbean on one side and the cypress on the other.

>criteria for island status?

In this proposal I don't think there'd be one - they can't be spatial or authoritative in the proposed structure, I can see no reason to limit what might be used. (Nor any great way to disambiguate the homonyms, nor much reason to, and not really much reason for the proposed not-quite-infinite code table.) In any case that would no longer be a geography question.

**Comment by Jegelewicz** [comment]
Everything Dusty said.

> a field for "waterbody" that would include seas (and lakes and rivers?) but oceans would remain in a different field "Continent/Ocean"?

Yes

> Is that Darwin core?

No. I would prefer to see oceans in the waterbody attribute, but it is an argument I'm willing to wait to have after we do all of this unless others want to have it now.

> Will you link Islands to the Island Group and to the higher geography for consistency?

Seems like we should, but not sure the best way to do it, especially since some islands are part of several nesting island groups.

**Comment by sharpphyl** [comment]
No problem with anything.  There's probably always more to be done.

**Comment by dustymc** [comment]
Tabling - https://github.com/ArctosDB/arctos/issues/3272 would allow Arctos to standardize geography.
