### ISSUE TITLE
Error in Data Entry Screen for Part Preservation

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#3187]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
When going back and editing entries in the data entry screen I get the pink screen of doom with an error message of:
record failed checks: part_preservation_1 [ NULL ] is invalid.; part_preservation_2 [ NULL ] is invalid.; part_preservation_3 [ NULL ] is invalid.; part_preservation_4 [ NULL ] is invalid.; part_preservation_5 [ NULL ] is invalid.; part_preservation_6 [ NULL ] is invalid.; part_preservation_7 [ NULL ] is invalid.

Except I did not enter any part preservation, and the option is not available in the Data Entry screen:
![Part preservation error](https://user-images.githubusercontent.com/18562884/98062925-2985af80-1e0c-11eb-8151-a65b09140ee8.jpg)

**To Reproduce**
Open a data record from the Browse/Edit Bulkloader -> click on save edits -> get pink screen with error specific for part preservation

**Expected behavior**
I know we agreed to add part preservation, but is it a required field now? It would be great if NULL was an accepted field instead of one that is unexpected for all parts.

**Desktop (please complete the following information):**
Mac OS, chrome

**Comment by AJLinn** [comment]
Yes me too! (I think we created those issues at about the same moment!)

**Comment by dustymc** [comment]
happy now?

**Comment by ewommack** [comment]
Yeah blue screen of happiness.
Thanks @dustymc!
