### ISSUE TITLE
Data entry error: Part Preservation is null (Excuse me?)

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#3188]
First I was kicked out due to Time out and had to totally recreate the data entry record (it takes us a long time to do data entry sometimes!).
Only to be greeted with the pink-screen of death with no red box and this error:
<img width="906" alt="Screen Shot 2020-11-03 at 5 40 14 PM" src="https://user-images.githubusercontent.com/17605945/98063149-d3a90b80-1dfb-11eb-9536-53534db43e8b.png">

Where pray tell is the part preservation 1 and part preservation 2 in my data entry screen and how do I fix this before it times me out again and I lose this data for a 3rd time?

Help me please!

**Comment by AJLinn** [comment]
#3187 sorry just seeing this now!

**Comment by ewommack** [comment]
No worries! You can tell who is working late tonight ;)

**Comment by dustymc** [comment]
should be fixed SORRY!!!

**Comment by AJLinn** [comment]
yay! Thank you! Saved by our hero! 👍
