### ISSUE TITLE
public search not pulling up records

### ISSUE THREAD

**Issue by droberts49** [ArctosDB/arctos#3190]
I have a volunteer working on collector biographies and she has come across some challenges having Arctos bring up records known to be in the system. The searches she is conducting are for a collector's name, to pull up associated records (collecting date range, geographic localities, taxa) with that collector. She has tried searching when logged in, when not logged in, and on multiple devices. 

I can find the agent and their associated records fine when I'm logged into Arctos as me, but when I do a query not logged in, it results in the same issue. I have run searches with the exact agent name as well as just a last name. Neither the specimen records nor the agent are encumbered, so they should be findable by anyone searching for them. I'm running Windows 10 and have tried searches using Chrome and M-Edge.

For example, searching for "Harriet W. Cory" as collector (as well as nothing selected) -- in our records (and in Arctos) should pull up 265 records. No problem when I'm logged in. When I do the exact same search not logged in, it indicates "Found 0 catalog records."
Another example: Searching for "Kennicott" as a collector just in our (CHAS) collection brings up 313 records, but doing the same search not logged in brings up only 56 records (54 CHAS, 2 DMNS).

I don't recall having this issue before. This potentially impacts what external researchers and the public may experience when searching for data in Arctos.
I appreciate your help!

**Comment by dustymc** [comment]
Looks like Arctos is being overly paranoid with encumbrances - "mask part attribute location" (or anything else) is blocking agent search. I'll see if I can make it a little smarter.

**Comment by dustymc** [comment]
Smarter in next release

**Comment by droberts49** [comment]
Thank you Dusty!
