### ISSUE TITLE
Part attributes displaying double/changed layout to part condition

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#3191]
**Describe the bug**
Things were looking great with the full-screen spread of parts & part-attributes. My condition report text had lots of room to breath. Then I added part attributes to my object part. Now the part attribute is being displayed twice, once of which is embedded inside the table. It also totally messed up the formatting of my condition column... making it  very narrow and hard to read. I'm guessing/hoping this is a bug?

https://arctos.database.museum/guid/UAM:EH:UA2020-008-0001

**Expected behavior**
Don't duplicate information; don't embed attribute inside parts table?

**Screenshots**
<img width="1048" alt="Screen Shot 2020-11-04 at 2 16 51 PM" src="https://user-images.githubusercontent.com/17605945/98178072-74550500-1ea8-11eb-8c89-75f00e0466de.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac 0S 10.14.6
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 86.0.4240.111

**Additional context**
I know there another issue about the parts and part attributes, which I assume this is related to.

**Priority**
High

**Comment by dustymc** [comment]
No, it's not a bug, it's by request from https://github.com/ArctosDB/arctos/issues/3180 (and https://github.com/ArctosDB/arctos/issues/1460).

The table seems necessary to me - I just don't know of another way of displaying eg 20 determinations when things like date, determiner, and/or method are important. I think your location data are like that - "here; there" isn't useful, you need date - correct?

The columns which replicates some of the information from the table (aggregated unique values) is by request. I don't really understand why....

I am very open to better ideas.

**Comment by AJLinn** [comment]
> I think your location data are like that - "here; there" isn't useful, you need date - correct?

Correct. When we don't have barcodes on an object, or we want to use the last part location field in the search results, we have to use this part attribute field for location, and the who/when are important for knowing if something is not where it's supposed to be.

> The columns which replicates some of the information from the table (aggregated unique values) is by request. I don't really understand why....

Bummer... anyone care to help me understand why this info is duplicated? I thought one of the guiding principles of Arctos was to NOT duplicate info?

**Comment by dustymc** [comment]
We're not duplicating information storage, just display - it's eating a lot of screen real estate, not corrupting data.

Suggest putting this on the top of every possible agenda until a better solution is found.

**Comment by dustymc** [comment]
I've removed the by-attribute columns for the next release. This is getting no feedback, and without clear directions to the contrary I think the needs of existing data should win over anticipations of something that might happen in the future.

**Comment by AJLinn** [comment]
Thanks - I think this is a wise choice and appreciate the removal of that additional column. It will be cleaner for our records for sure.
