### ISSUE TITLE
UTM Data Entry

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#3193]
Using the single record Data Entry page - I input UTM with all the necessary info (Error, datum, georeference source, etc). After selecting to load, I get the following 'loaded' status in the bulkloader queue:
"Error and units, datum, and georeference source and protocol must be accompanied by coordinates."
collection_object_IDs: 97450072 and 97450073
What am I doing wrong?

**Comment by Jegelewicz** [comment]
UTM don't take all the other goodies - I think. Just enter them without error, datum, georeference source, etc and see if that works.

**Comment by acdoll** [comment]
I tried that - it wont let me save without them.

**Comment by dustymc** [comment]
I think there are a bunch of issues, https://github.com/ArctosDB/arctos/issues/2930 is one of them.

I have "verbatim" coordinates from which I convert to DD.dd when necessary, UTM got dumped in there at some point, it shouldn't be. I can look at duct taping the duct tape if necessary, I'd rather fire up a 'verbatim coordinates' locality attribute and put UTM (and anything else from which I can't convert, at least) there.

**Comment by acdoll** [comment]
I thought that was the case (UTMs should go in verbatim), but I haven't come across one in so long I thought things might have changed. I'll put them in verbatim and get good decimal degrees. Thanks

**Comment by Jegelewicz** [comment]
> 'verbatim coordinates' locality attribute

For UTM, should we do as we have with TRS? So we would have:

UTM Zone - The UTM system divides the Earth into 60 zones, each 6° of longitude in width.
UTM Easting - a measurement of East-West position, within the Grid Zone, in meters. Using a map with a 1000m grid, the first digits are come from the label for the grid line to the west of the position. The last 3 digits are the distance in meters measured from the western grid line.
UTM Northing - represent a measurement of North-South position, within the Grid Zone, in meters. Using a map with a 1000m grid, the first digits are come from the label for the grid line to the south of the position. The last 3 digits are the distance in meters measured from the southern grid line.

from https://www.maptools.com/tutorials/utm/quick_guide

**Comment by dustymc** [comment]
What you've done with TRS can only be reassembled under a narrow set of circumstances which we don't control for. Suggest treating those as data objects, or strings if that's somehow not possible.

**Comment by jtgiermakowski** [comment]
What's the consensus then on UTM? If we are only using Lat/Long coordinates then UTM in "orig_lat_long_units" should be eliminated. Students are still trying to force feed Arctos with UTM and failing...

**Comment by dustymc** [comment]
See https://github.com/ArctosDB/internal/issues/90 - I have a recipe, I need postgis to use it. @mkoo ??


https://github.com/ArctosDB/arctos/issues/2309 and https://github.com/ArctosDB/arctos/issues/2660 are also relevant.

**Comment by jtgiermakowski** [comment]
> What's the consensus then on UTM? If we are only using Lat/Long coordinates then UTM in "orig_lat_long_units" should be eliminated. Students are still trying to force feed Arctos with UTM and failing...

Can we please eliminate UTM in "orig_lat_long_units"? as @Jegelewicz says above, we've got folks trying to feed it and it's not working...Thanks!

**Comment by Jegelewicz** [comment]
@dustymc can we get rid of this option for now?

**Comment by dustymc** [comment]
UTM needs added to new screen when postgis is on/tested

**Comment by dustymc** [comment]
postgis is running at production, bulkloader needs rebuilt to use convertRawCoords

**Comment by Jegelewicz** [comment]
I'd like to clarify something for myself. Once this is all working, if I enter UTM where will that reside in Arctos? As with PLSS, some people actually use UTM and might search for records in a given Zone, etc. Will we be able to facilitate that or will the UTM as entered be lost for that purpose?

**Comment by dustymc** [comment]
>Once this is all working

Last night...

>where will that reside in Arctos?

Collecting event, with all other "verbatim" coordinate data.

>search

Given an actual and compelling use case, that could be facilitated.
