### ISSUE TITLE
projects/publications not displaying properly when logged in

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#3194]
@ewommack and I both noticed something today. When we're logged in and search on a project, the window frame is such that the projects column is much smaller than the publication column, making it hard to read. Screen shot:
'
![image](https://user-images.githubusercontent.com/967275/98303739-7afc7e80-1f73-11eb-93c5-49303ca5262d.png)

The page looks fine when we're not logged in:

![image](https://user-images.githubusercontent.com/967275/98303778-8ea7e500-1f73-11eb-89e3-ee98cc5ca248.png)

@dustymc can you make the columns equal for logged in users? We are doing a webinar on Tuesday and so it would be great to have fixed by then. Thanks!

**Comment by ccicero** [comment]
Hmmm... Did a different search and now it looks fine logged in for me, but Beth still says it looks the same with a narrow projects column. 

![image](https://user-images.githubusercontent.com/967275/98304075-1f7ec080-1f74-11eb-8f17-49195bc0a902.png)

**Comment by ccicero** [comment]
OK, just tried again and it's doing the same weirdness with a narrow column.

![image](https://user-images.githubusercontent.com/967275/98304290-91efa080-1f74-11eb-9baf-c85fe547de5b.png)

**Comment by dustymc** [comment]
I need your search terms to know what's going on, but that should be your browser doing whatever it wants with a table, nothing I control.

**Comment by ccicero** [comment]
title = 'egg' or 'eggs'
'cites specimens'

it just seems buggy and inconsistent, and I've never seen it behave this way. And Beth is having the same issue.

**Comment by dustymc** [comment]
Thanks. Remarks display when you're logged in, they contain this:

<img width="767" alt="Screen Shot 2020-11-05 at 3 30 54 PM" src="https://user-images.githubusercontent.com/5720791/98308021-f95d1e80-1f7b-11eb-9fc4-343e91e5771a.png">

**Comment by ccicero** [comment]
ah. I don't see any remarks, but it's a very long URL for that pub (and/or a very long title) - Is that what's causing this? Those are wrapping around, so can't the width be controlled so that it wraps more and and columns are more fixed width? It makes everything really hard to read.

**Comment by dustymc** [comment]
The title wraps, it's the URL with no breaking characters that's causing the push. I can control width, I suppose, but that'll be weird sometimes too - eg, a whole lot of nothing beside the squished-up data if you're just looking at publications or projects. I'm always reluctant to mess with "normal" behavior.

The PDF is already attached as media, there's no reason for that "remark," I just deleted it.

**Comment by ccicero** [comment]
Way better, thanks!!!
