### ISSUE TITLE
Mineral classifications not displaying as expected

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3197]
I added classification to the mineral taxa. In the catalog record they do not display as expected:

![image](https://user-images.githubusercontent.com/5725767/98416348-23761580-203c-11eb-9454-cc0ca5014f85.png)

Given the [classification](https://arctos.database.museum/name/Smithsonite), I would expect to see the identification like this:

Smithsonite
Carbonates, Carbonates of Zn and Cd, Smithsonite

**Comment by dustymc** [comment]
I think this is answered in https://github.com/ArctosDB/arctos/issues/3196 - I need to rebuild a function after we deal with some legacy "requirements." I'll dig deeper once that's addressed if it's not the whole problem.

**Comment by dustymc** [comment]
Let's deal with this in https://github.com/ArctosDB/arctos/issues/3231, which is at least the first step
