### ISSUE TITLE
GenBank: broken links do we need a Generic page for encumbrance 404s?

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3198]
Dear Staff at Arctos Specimen Database,

We have checked a sample (3176) of your links on 11/09/2020,
and found 10 (0.31%) problematic links.

In order not to frustrate users with broken links, we will disable those
links. You will receive a separate report on the disabled links. 

Below is a report of errors we found.  Please review them and make
correction as soon as possible.  Please notify us when the errors have
been corrected to restore the links.

Should you have any questions, please write to linkout@ncbi.nlm.nih.gov

Regards,

LinkOut team
NCBI/US NLM

UID    Error code      URL
----    ----------      ---
209401354    404        https://arctos.database.museum/guid/UAM:Bird:24471
209401490    404        https://arctos.database.museum/guid/UAM:Bird:24574
237825046    404        https://arctos.database.museum/guid/UAM:Bird:24509
239508485    404        https://arctos.database.museum/guid/UAM:Bird:21752
239508520    404        https://arctos.database.museum/guid/UAM:Bird:21766
239508553    404        https://arctos.database.museum/guid/UAM:Bird:21320
239508585    404        https://arctos.database.museum/guid/UAM:Bird:24703
379657730    404        https://arctos.database.museum/guid/UAM:Bird:18797
379658630    404        https://arctos.database.museum/guid/UAM:Bird:18797
395318808    404        https://arctos.database.museum/guid/MSB:Bird:27098

**Comment by ebraker** [comment]
oof

**Comment by dustymc** [comment]
Scroll up - that's all of it!

**Comment by mkoo** [comment]
Likely these were misreported by someone uploading bird sequences. It would be helpful if they supplied the reciprocal GEnbank record so you could see the offender's pub at least!

Has this been sent to MSB Bird and UAM Bird contacts yet?

**Comment by dustymc** [comment]
Nah, they're just encumbered.

https://github.com/ArctosDB/arctos/issues/1725

**Comment by Jegelewicz** [comment]
Nah, they're just encumbered.

**Comment by dustymc** [comment]
> instead of a 404

https://github.com/ArctosDB/arctos/issues/1727

**Comment by campmlc** [comment]
I prefer something simple, with no mention of encumbrances: "Please contact the collection for more information".

**Comment by Jegelewicz** [comment]
I guess we decided back in 2019 to let the 404 stand. Seems like a not-very-useful path, but there it is.

**Comment by campmlc** [comment]
I don't think we "decided" - I think the discussion just never resolved.
Anything is better than 404 in this case. "Please contact the collection
for more information".
