### ISSUE TITLE
Upload Box Barcodes for DGRLocator

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3199]
@dustymc Please upload these box barcodes to freezer boxes in the DGR Locator for DGR4.  These urgently need to be scanned into new positions because of infrastructure failure.

[DGR4_BoxReplacement_Barcodes.zip](https://github.com/ArctosDB/arctos/files/5513732/DGR4_BoxReplacement_Barcodes.zip)

**Comment by dustymc** [comment]
So delete https://arctos.database.museum/EditContainer.cfm?container_id=14841967 and use it's barcode for https://arctos.database.museum/EditContainer.cfm?container_id=18383218??

**Comment by campmlc** [comment]
I assume that's what you've done for all the other freezers? DGR11?  Can get this done asap? I've got a crew here on hand standing by to move boxes . . . .

**Comment by campmlc** [comment]
Help please

**Comment by dustymc** [comment]
Done, except for  DGR10641 | DGR-4-5-4 | 18451827 | 18451827
 which wasn't a label.

PG code is https://github.com/ArctosDB/PG_DDL/blob/master/scripts/swapDrgBarcodes.sql if this needs to happen again.

**Comment by campmlc** [comment]
Here is the next file of legacy DGR box barcodes to load to labels. I don't have the skills to load this via SQL on my own, so help please.

[DGR5_boxReplacement_barcodes.zip](https://github.com/ArctosDB/arctos/files/5581204/DGR5_boxReplacement_barcodes.zip)

**Comment by dustymc** [comment]
PLEASE try to keep this clean if you need more updates. I deleted DGR10973, otherwise done.

**Comment by campmlc** [comment]
Pleas let me know how they are not clean so can try to fix. I have students
generating these.

**Comment by dustymc** [comment]
I don't know how to be more clear. You sent me a list of barcodes to reuse, one of them (in both files) was already used for something. I'm not particularly worried about the things I catch, I'm worried about what I might not. Whatever you're doing apparently isn't resulting in predictable data, feeding unpredictable data to scripts doesn't always end well.

**Comment by campmlc** [comment]
I will check for pre-existing in future submissions. However, in this case
the barcode is legit. The "previous" use appears to have come from another
student handcopying a barcode rather than scanning it, which given that we
must rely on successions of different students and other humans rather than
machines to do our labor, is an unfortunately all to common occurrence,
especially in underfunded museums.
