### ISSUE TITLE
error feedback Extras for Loaded Specimens: Parts

### ISSUE THREAD

**Issue by cefilipek** [ArctosDB/arctos#3201]
I am attempting to re-upload a part that had a misspelled part name, but when I upload it I get this error:

An error occurred while processing this page!
Message: Error invoking external process
Detail: psql:/usr/local/webroot/temp/excopy_cfilipek_2020111008113968_534.sql:1: ERROR: column "use_existing" of relation "cf_temp_parts" does not exist
Check the Arctos Handbook for more information on errors.
This message has been logged as D05DF400-7309-4467-A5E83D4ACE28C671 Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue.

I used the same bulkloader template that I downloaded and used yesterday, and it worked fine then.

I went to Extras for Loaded Records, then Bulkload Parts. I then selected Load CSV, added my file, and selected upload this file. I'm unsure what the issue is, I tried to remove "use_existing", but got the same error with a different field. I'm attaching my file here as well.

[Extras fix.zip](https://github.com/ArctosDB/arctos/files/5518043/Extras.fix.zip)

**Comment by dustymc** [comment]
A new loader went out last night - you can just delete

use_existing,container_barcode,change_container_type,change_container_label,

and it should work, but different than before.

https://github.com/ArctosDB/arctos/issues/2603

https://github.com/ArctosDB/arctos/issues/2974

**Comment by cefilipek** [comment]
Thanks!

Colleen

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Jegelewicz** [comment]
@cefilipek did this work for you? If so, you can close the issue.

**Comment by cefilipek** [comment]
Yes! Sorry, it was a busy day and I forgot about this question by the time I got around to fixing it!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
