### ISSUE TITLE
Part bulkload tool - Catalog number not resolved?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3202]
Just attempted to load the parts I had in the tool.

Getting this error
![image](https://user-images.githubusercontent.com/5725767/98695423-d80b8200-232f-11eb-8281-81575220f3a1.png)

But the catalog record is right here:
![image](https://user-images.githubusercontent.com/5725767/98695464-e6f23480-232f-11eb-807d-7028cd5851b6.png)

**Comment by dustymc** [comment]
Yes the "any otherIDType or oh yea some string" thing disappeared last night - but it'll now accept GUID
