### ISSUE TITLE
ants

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3204]
@mvzhuang lets move https://github.com/ArctosDB/arctos/issues/2974#issuecomment-724907819 here

I loaded your CSV and

arctosprod@arctos>> delete from temp_utep_ants where not exists (select scientific_name from taxon_name where taxon_name.scientific_name=temp_utep_ants.scientific_name);
DELETE 6115

9556 remaining names attached, I don't see anything obvious, please take one more look, let me know if it still looks good and I'll load them.

[temp_utep_ants.csv.zip](https://github.com/ArctosDB/arctos/files/5519711/temp_utep_ants.csv.zip)

Do you want a new Source for the classification data? https://handbook.arctosdb.org/documentation/taxonomy.html#taxon-classification-sources

**Comment by mvzhuang** [comment]
OK I think they all look well and good. 

Yes, "AntWiki (via Arctos)" ? 
Data comes from antwiki.org and must be manually updated

**Comment by Jegelewicz** [comment]
I created the new taxonomy source. Do you need help loading classifications?

**Comment by dustymc** [comment]
Sorry, I messed up the previous check, these aren't happy.
```
       scientific_name       |       isvalidtaxonname        
-----------------------------+-------------------------------
 Formica atra Schilling      | Too many uppercase characters
 Formica robusta Chang & He  | Invalid characters.
 Formica wheeleri Creighton  | Too many uppercase characters
 Formica wheeleri Stitz      | Too many uppercase characters
 Messor testaceus Bernard    | Too many uppercase characters
 Pseudolasius emeryi (Forel) | Invalid characters.
 Pseudolasius emeryi Forel   | Too many uppercase characters

```

I deleted them and loaded the rest.

**Comment by Jegelewicz** [comment]
All of those are in Arctos without the authority names.

**Comment by mvzhuang** [comment]
ahh oops ok i'll make sure those weird things aren't in the classification bulkload. I think i have it handled.

**Comment by mvzhuang** [comment]
wait @Jegelewicz did you load the new source in test database or the main one? i'm getting an error that it doesn't exist in test. it's not in the code table either but i was guessing it just hadn't appeared there yet

**Comment by mvzhuang** [comment]
nvm being dumb. i thought we were doing this in test for some reason. It's loading!

**Comment by mvzhuang** [comment]
@dustymc Everything loaded fine. I think I need a cache refresh or something went wonky. Forelius damaini is supposed to pull from the AntWiki classification and says it is, but the subfamily is showing as null in the record. https://arctos.database.museum/name/Forelius%20damiani

also i don't suppose it's possible to show preview of data before loading? like with specimen events batch loading?

**Comment by dustymc** [comment]
I refreshed https://arctos.database.museum/guid/UTEP:Ento:11930 - lemme know if it looks OK and I'll just tell the whole collection to refresh.

Not sure what you mean by preview - possibly something that needs discussed before we do even more (incl. rebuild specimen events) with https://github.com/ArctosDB/arctos/issues/2974

**Comment by mvzhuang** [comment]
Yes looks good and can refresh

meant kind of like in the specimen event bulkloader where you can check the data in browser for limited number of records, but yes agreed on discussion

**Comment by dustymc** [comment]
Refreshing...
