### ISSUE TITLE
globalnames refresh

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3205]
* Push data to a predictable URL in some format GN can understand. 
* Refresh periodically. 
* Somehow separate Sources in anticipation of the possibility that we'll eventually get something we can call "curated."

@dimus is

https://tools.gbif.org/dwca-validator/extension.do?id=dwc:Taxon

your preferred format? I'm not sure I can get there, but I can probably get close...

Here's our classification structure:

```

           Column           |            Type             | Collation | Nullable |                Default                
----------------------------+-----------------------------+-----------+----------+---------------------------------------
 taxon_term_id              | bigint                      |           | not null | nextval('sq_taxon_term_id'::regclass)
 taxon_name_id              | bigint                      |           | not null | 
 classification_id          | character varying(4000)     |           |          | 
 term                       | character varying(4000)     |           | not null | 
 term_type                  | character varying(255)      |           |          | 
 source                     | character varying(255)      |           | not null | 
 gn_score                   | real                        |           |          | 
 position_in_classification | bigint                      |           |          | 
 lastdate                   | timestamp without time zone |           | not null | LOCALTIMESTAMP
 match_type                 | character varying(255)      |           |          | 

```

and https://arctos.database.museum/name/Sorex%20cinereus#Arctos (which is too predictable to be a great example) is built from...

```
arctosprod@arctos>> select term,term_type,position_in_classification from taxon_term where classification_id='181' order by position_in_classification;
               term               |     term_type      | position_in_classification 
----------------------------------+--------------------+----------------------------
 Animalia                         | kingdom            |                          1
 Chordata                         | phylum             |                          2
 Mammalia                         | class              |                          3
 Soricomorpha                     | order              |                          4
 Soricidae                        | family             |                          5
 Soricinae                        | subfamily          |                          6
 Soricini                         | tribe              |                          7
 Sorex                            | genus              |                          8
 Otisorex                         | subgenus           |                          9
 Sorex cinereus                   | species            |                         10
 valid                            | taxon_status       |                           
 Museum of Vertebrate Zoology     | source_authority   |                           
 Kerr, 1792                       | author_text        |                           
 ICZN                             | nomenclatural_code |                           
 <i>Sorex cinereus</i> Kerr, 1792 | display_name       |                           
 Sorex cinereus                   | scientific_name    |                           
```

So there could be 20 terms ranked "family" in there, or no ranks at all, or anything else, and the hierarchy on this individual classification doesn't necessarily carry over to any others - in fact this one dies at https://arctos.database.museum/name/Otisorex#Arctos, which doesn't exist. (There's data from GN there, but nothing local.)

Ideas about how to package that without loss greatly appreciated.

**Comment by Jegelewicz** [comment]
> So there could be 20 terms ranked "family" in there, or no ranks at all, or anything else,

Package like you have it here? Each term has a termtype - GN can do with it what they want?

**Comment by dustymc** [comment]
Certainly simple to just dump parts of the table if @dimus can deal with that. The "local" data is 

* 3156508 names
* 3949979 classifications
* 61833173 rows

at the moment, if that somehow matters.

**Comment by dimus** [comment]
@dustymc last time you supplied 3 files classification.csv, common_name.csv, relationship.csv

what do you think about sending something similar? here are the headers of these 3 fiels:

classification.csv
```
classification,author_text,display_name,scientific_name,source_authority,valid_catalog_term_fg,taxon_status,remark,nomenclatural_code,infraspecific_author,superkingdom,subkingdom,"infrakingdom""",superphylum,phylum,subphylum,subdivision,infraphylum,superclass,class,subclass,infraclass,hyperorder,superorder,phyl_order,suborder,infraorder,hyporder,subhyporder,superfamily,family,subfamily,supertribe,tribe,subtribe,genus,subgenus,species,subspecies,forma,variety
Arctos,(Saussure 1861),<i>Syrbula montezuma</i> (Saussure 1861),Syrbula montezuma,"Nomina Insecta Nearctica, 2002",1,,,ICZN,,,,,,Arthropoda,,,,,Insecta,,,,,Orthoptera,,,,,,Acrididae,,,,,Syrbula,,Syrbula montezuma,,,
```
relationships.csv

```
scientific_name,related_name,TAXON_RELATIONSHIP,RELATION_AUTHORITY
Bos bison,Bison bison,synonym of,ITIS
```

common_name.csv
```
SCIENTIFIC_NAME,COMMON_NAME
Rana sylvatica,wood frog
```

This format worked well for me, so if to keep it similar would mean I can use my old script for harvesting.

Two things that I would love to be improved:
1. Would be nice to have an ID that is not a name. It would help to fight nasty homonyms. To be consistent with my DB schema I concoct an ID, but if during migration to postgres you generate your own id, would be great to have it.

2. Last import had lines that were with wrong number of field. I suspect it was happening when you concatenated different datasets together. Not a big problem, but would be great to skip the cleaning step.

# Identifiers

Identifiers are a little bit messy, and depending on a data source identifiers get placed at GN differently. Here is the description of what I have currently.

```
	// ID from a data source. We try our best to return ID that correspond to
	// global_id of a DataSource. If such ID is not provided, this ID will be
	// auto-generated.  Auto-generated IDs will have 'gn_' prefix.
	ID string `json:"id"`

	// GlobalID that is exposed globally by a DataSource. An example would
	// be LSID, PURL, DOI etc. Usually this kind of ID is able to self-resolve.
	GlobalID string `json:"globalId,omitempty"`

	// LocalID used by a DataSource internally. This ID is used for creation
	// of the record Outlink.
	LocalID string `json:"localId,omitempty"`

	// Outlink to the record in the DataSource. A url that points to the
	// a web page that describes the record. Most likely this ID has two parts:
	// the 'stable' URL that is appended with LocalID.
	Outlink string `json:"outlink,omitempty"`
```
So I guess scientific name like `Sorex%20cinereus` would be a `LocalID` for me, and if you have some `bigint` ID as well, that would go  as `ID`?

**Comment by dimus** [comment]
> Certainly simple to just dump parts of the table if @dimus can deal with that. The "local" data is
> 
>     * 3156508 names
> 
>     * 3949979 classifications
> 
>     * 61833173 rows
> 
> 
> at the moment, if that somehow matters.

I suspect that would work too, especially if DB schema will stay the same for a few years.

**Comment by dustymc** [comment]
I can update the "flattener" scripts, but they can't properly deal with unranked classification terms, or 20 things ranked 'family,' or probably some other stuff. That probably explains any malformed rows as well, but I can probably deal with that. Lot of "probably" in there....

The table dump would be lossless, and I can foresee no reason we'd change the structure. For our current "stuff people use to catalog" data that's "sorta neat" but I think not entirely critical. Arctos does now support smaller classifications that could be curated, a more precise transfer mechanism might be seen as more important if that happens. (That could take the form of something like TPT, or some Curator who's really into a genus of butterfly, or about anything else.) I _think_ we will end up in that scenario, but I'm not great at predicting what people will _actually_ do so ??????????

I can do either. The table dump is "better" but I fully understand if you don't want to change all of your scripts.

We have basically three levels of identifiers.

1. https://arctos.database.museum/name/Echidna is the name, which includes any number (including zero) of classifications. It has a pkey (2060311 in that case) but it's not exposed anywhere, certainly isn't global.

2. https://arctos.database.museum/name/Echidna#Arctos is the intersection of name and Source, and in most - not all - cases it's unique for local data. (Current "local" sources are https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxonomy_source)

3. The second (of three) gray boxes in https://arctos.database.museum/name/Echidna#GBIFBackboneTaxonomy....

<img width="1010" alt="Screen Shot 2020-11-11 at 7 22 24 AM" src="https://user-images.githubusercontent.com/5720791/98830010-bcb37c00-23ee-11eb-8d21-deb4693135b4.png">

...is "Echidna the viper according to GBIF" - it has an ID (that I got from you - ``1%7C44%7C358%7C715%7C5024%7C2444943`` is the urlencoded version) but it's not exposed anywhere, and it's not global ("Sorex cinereus according to Arctos" is ``181``) and it's not particularly stable (that may change when/if we really start using taxon concepts). 

So I think we have all sorts of identifiers, but none of them are exactly what you need! I can pretty easily add handlers for various things to the UI, and happy to share any of them in whatever form you find most useful.

Here's a few rows of a potential table dump - I've denormalized taxon_name.scientific_name to a column, excluded some things I don't think you'll care about, can easily do something else if you want.

```
drop table temp_gn_test_dump;
create table temp_gn_test_dump as 
select 
  taxon_name.scientific_name,
  taxon_term.term,
  taxon_term.term_type,
  taxon_term.position_in_classification,
  taxon_term.classification_id,
  taxon_term.source
from 
  taxon_name
  inner join taxon_term on taxon_name.taxon_name_id=taxon_term.taxon_name_id
  inner join cttaxonomy_source on taxon_term.source=cttaxonomy_source.source
where
  taxon_name.name_type='Linnean' and 
  taxon_name.taxon_name_id < 100
order by
  taxon_name.scientific_name,
  taxon_term.source,
  taxon_term.position_in_classification
;
```
[temp_gn_test_dump.csv.zip](https://github.com/ArctosDB/arctos/files/5525217/temp_gn_test_dump.csv.zip)

**Comment by dimus** [comment]
Let's go with the table dump @dustymc. I do not mind changing scripts one more time, if it gets better results. It is not a big deal to generate IDs for my purposes, and I will keep it obvious that they are not coming from Arctos. I wonder, for outlink, would you prefer me to use https://arctos.database.museum/name/Echidna or https://arctos.database.museum/name/Echidna#Arctos?

**Comment by dustymc** [comment]
I'll get it cooking. 

I will send you multiple sources for some names. The example data above includes eg

https://arctos.database.museum/name/Alopex%20lagopus#Arctos
https://arctos.database.museum/name/Alopex%20lagopus#WoRMSviaArctos

and in both cases the name+source serves as a 'classification identifier.'

The "problem" - if it is a problem - will be when that intersection is not unique, eg for https://arctos.database.museum/name/Echidna#GBIFBackboneTaxonomy. For that (if it was Arctos data - I won't send this at all) I would include....

```
select distinct classification_id from taxon_term where source='GBIF Backbone Taxonomy' and taxon_name_id=(select taxon_name_id from taxon_name where scientific_name='Echidna');

     classification_id     
---------------------------
 1|44|204|495|2953|2404224
 1|44|358|715|5024|2444943
 1|44|359|791|5941|2433377
```

the three classification identifiers, but I don't currently do anything with them. 

Is the solution as simple as making ``https://arctos.database.museum/name/Echidna#1|44|204|495|2953|2404224`` (which should be global, unique, and identifies a single classification) scroll to the correct place on the page? If so I can make it happen.

**Comment by dimus** [comment]
Let's go with the table dump @dustymc. I do not mind changing scripts one more time, if it gets better results. It is not a big deal to generate IDs for my purposes, and I will keep it obvious that they are not coming from Arctos. I wonder, for outlink, would you prefer me to use https://arctos.database.museum/name/Echidna or https://arctos.database.museum/name/Echidna#Arctos?

**Comment by dustymc** [comment]
For clarity, ``1|44|204|495|2953|2404224`` in the currently-nonfunctional example ``https://arctos.database.museum/name/Echidna#1|44|204|495|2953|2404224`` is a "classification_id," and classification_id is a unique-within-name string with no other limitations. I've used whatever's handy (including integers) for various legacy/transport reasons, and there's NO predicting what those IDs might looks like. (They're UUIDs when I can easily generate them from scratch.)


@dimus everything in https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxonomy_source is from us, NOT via GN. (Sorta - ``WoRMS (via Arctos)`` is from WoRMS via their API.) ``Arctos`` and ``Arctos Plants`` are what we mostly use, but hope to be moving away from; ``AntWiki (via Arctos)`` was just added this AM and will be "curated" by periodically uploading their (cleaned) download, ``TPT (via Arctos)`` may or may not eventually get populated and curated, etc. I could dump them all into one table and you can pull them out by Source (as in the example above), or I can dump them into individual tables and zip it all together for you.

**Comment by dimus** [comment]
One thing I would like to have is an `ID` that is not changing from one Arctos harvest to another. For all my name-string IDs I convert name-string to UUIDv5. Such is always the same for the same string. For example 

```
gnparser "Alopex lagopus"
Id,Verbatim,Cardinality,CanonicalFull,CanonicalSimple,CanonicalStem,Authorship,Year,Quality
3d318901-38cc-5af4-8f47-985baf37b1fd,Alopex lagopus,2,Alopex lagopus,Alopex lagopus,Alopex lagop,,,1
```

It does need a 'seed' for which I use the "globalnames.org" DNS domain. When we decide what string to use, it will be simple for me to generate UUIDs that I would always generate consitently. For example all IDs I generated in Ruby, Scala and Go are the same for the same string.

I understood about classifications that come from Arctos. Lets try first shot with a dump. I will try to make sense of it, and if I will have problems, I will ask questions.

**Comment by dustymc** [comment]
@dimus https://arctos.database.museum/temp/gn_merge.gz should feed you a ~650MB file. It's easy to change about anything at this point, so let me know if something could be better.

I will need to move it to a different path - my janitor scripts dump that dir every few days - but I'll get you a stable URL once we get the details sorted.

Vague plan is to just replace the entire thing every now and then (monthly??), but I could add some sort of a date-component (or meta file, or ???) somewhere in there if you think that's necessary.

TODO

* find a stable place for the merged file
* get function refresh_globalnames_cache on a pgcron schedule - takes about 3 minutes to build the cache
* get what's currently in /info/get_gn.cfm on a schedule - copy is fast, writing to local disk is slow, doing this on the fly isn't working great, need to pipe through cfschedule

**Comment by dimus** [comment]
Thank you @dustymc, I downloaded the file, next week I will try to make a conversion script for the dump.

**Comment by dimus** [comment]
hi @dustymc, 
Sorry I disappeared for a while. Life interfered and as a result, I am returning to import of Arctos only now. I look at the data, and I see that you have a "classification_id" field like for example '2021477' in 
```
Thrissocles mystax,Thrissocles,genus,1,2021477,Arctos
Thrissocles mystax,Thrissocles mystax,species,2,2021477,Arctos
Thrissocles mystax,valid,taxon_status,,2021477,Arctos
Thrissocles mystax,ITIS,source_authority,,2021477,Arctos
Thrissocles mystax,"(Bloch and Schneider, 1801)",author_text,,2021477,Arctos
Thrissocles mystax,Imported from ITIS 6 Feb 2007,remark,,2021477,Arctos
```
would it be safe for me to use classification_id as GN's 'taxon_id' (in more recent version 'record_id')?

**Comment by dimus** [comment]
I ran https://github.com/faradayio/scrubcsv and it found ~1 million of rows with a different number of fields in them:

```bash
scrubcsv arctos-2020-11-12.csv > arctos-clean-2020-11-12.csv
63260324 rows (1450013 bad) in 22.29 seconds, 218.00 MiB/sec
```

Here is an example of such rows:

```
scientific_name,related_name,taxon_relationship,relation_authority
Hibiscus poeppigii,Hibiscus pilosus,synonym of,ITIS
Paraleptophlebia associata,Paraleptophlebia compar,synonym of,ITIS
Neoechinorhynchus agilis,Echinorhynchus agilis,synonym of,ITIS
Kahliella acrobates,Kahlia acrobates,synonym of,ITIS
Cyrtandra lessoniana,Cyrtandra elliptisepala,synonym of,ITIS
Calythea crenata,Trichophticus crenatus,synonym of,ITIS
Tautogolabrus adspersus,Tautogolabrus chogset fulva,synonym of,ITIS
Lipogramma regium,Lipogramma regia,synonym of,"ITIS; Former: unavailable, incorrect orig. spelling"
Stictocardia tiliifolia,Stictocardia campanulata,synonym of,ITIS
Donrichardsia macroneuron,Eurhynchium macroneuron,synonym of,ITIS
Ophelina groenlandica,Ammotrypane groenlandica,synonym of,ITIS
Rhodiola integrifolia subsp. integrifolia,Tolmachevia integrifolia,synonym of,ITIS
Euaresta aequalis,Tephritis gemella,synonym of,ITIS
Urophora maura,Trypeta maura,synonym of,ITIS; Former: original name/combination
Carya illinoinensis,Hicoria pecan,synonym of,ITIS
Dinophysis recurva,Dinophysis lenticula,synonym of,CoL 2011 checklist
Aerodramus vanikorensis palawanensis,Aerodramus palawanensis,synonym of,ITIS; Former: subsequent name/combination
Pandanus tectorius,Pandanus menziesii,synonym of,ITIS
Backomyia limpidipennis,Eucyrtopogon limpidipennis,synonym of,ITIS
Arenaria lanuginosa var. saxosa,Arenaria confusa,synonym of,ITIS
Pica pica hudsonia,Pica pica hudsonia,synonym of,"Former: unavailable, other"
Stratiomys constricta,Stratiomys pinguis,synonym of,ITIS
Scaphyglottis behrii,Hexadesmia stenopetala,synonym of,CoL 2011 checklist
Aeluropus lagopoides,Dactylis brevifolia,synonym of,CoL 2011 checklist
Dendrocalamus asper,Arundarbor bitung,synonym of,CoL 2011 checklist
Bauhinia malabarica,Piliostigma malabaricum,synonym of,CoL 2011 checklist
```

**Comment by dustymc** [comment]
Hope it was the good kind of interference!

"Classification_id" is "name-at-source" and I believe it'll do what you need.

I'm not seeing the issue in those relationships eg

scientific_name=Dinophysis recurva,
related_name=Dinophysis lenticula
taxon_relationship=synonym of
relation_authority=CoL 2011 checklist

**Comment by dimus** [comment]
> I'm not seeing the issue in those relationships eg
> 
> scientific_name=Dinophysis recurva,
> related_name=Dinophysis lenticula
> taxon_relationship=synonym of
> relation_authority=CoL 2011 checklist

The data looks fine, the problem that I encounter is that the data has 4 fields, while the rest of the file has 6:

```
scientific_name,term,term_type,position_in_classification,classification_id,source
Phocoenoides dalli,Animalia,kingdom,1,114,Arctos
Phocoenoides dalli,Chordata,phylum,2,114,Arctos
Phocoenoides dalli,Mammalia,class,3,114,Arctos
Phocoenoides dalli,Cetacea,order,4,114,Arctos
Phocoenoides dalli,Odonticeti,suborder,5,114,Arctos
Phocoenoides dalli,Phocoenidae,family,6,114,Arctos
```
Probably dump should contain 2 files?

**Comment by dustymc** [comment]
Oh! That should be 3 files, apparently gz doesn't do that.

https://arctos.database.museum/temp/threefiles.zip should be the one download you were looking for, or 

https://arctos.database.museum/temp/globalnames_commonname.csv.gz

https://arctos.database.museum/temp/globalnames_relationships.csv.gz

https://arctos.database.museum/temp/globalnames_classification.csv.gz

are the parts.

**Comment by dimus** [comment]
Thanks @dustymc , the files look good and generate no CSV errors now. 

I would prefer not to have double layer of uncompressing, because it would make the code for arctos import different from all other resources and more cumbersome. I uncompressed them by hand, placed them in a directory, and then used this command:

```
tar zcvf ../arctos.tar.gz *csv
```
The resulting file `arctos.tar.gz` has all 3 files separate from each other and would fit great into my automatic workflow.

**Comment by dustymc** [comment]
I'll make it zip if that works for you. It's slow, but I'm going to have to schedule this anyway (I was initially hoping I could run it on the fly). I can tar the csv too, but I can't figure out how to do that without including the directory structure (some limitations in how my tools interact with the os, I think), and the zip file is slightly smaller and probably/maybe more future-proof.

**Comment by dimus** [comment]
zip and tar both work for me, and either free files flat, or something like

```
somedir/*csv
```
both are fine.

What is your OS? Files that come from Windows quite often have encoding problems, because UTF-8 support for Windows is a bit funny.

**Comment by dustymc** [comment]
It's centos/linux - I'm making the csv with postgres copy, then wrapping those up with lucee (which probably just calls the OS, but that's a bit abstract) all so this can be automated with my normal tools. I don't think anything in the stack has problems with UTF-8 (which is the native DB encoding).

The zip is https://arctos.database.museum/temp/gn_merge.zip if you want it, should unroll to the same three files.

**Comment by dimus** [comment]
Yes, I never had UTF-8 mishaps with Linux.

**Comment by dimus** [comment]
All files uznipped well, but I do have another problem, they contain a pretty long path to them, while my script is set for either flat files or one dir with files int it.

```
Archive:  gn_merge.zip
  inflating: usr/local/webroot/temp/globalnames_classification.csv
  inflating: usr/local/webroot/temp/globalnames_relationships.csv
  inflating: usr/local/webroot/temp/globalnames_commonname.csv
```
With tar the command would be:

```
cd usr/local/webroot/
tar zcvf arctos.tar.gz temp
```

But thats not a big deal for me to use what you gave and do a bit of manual work with the file.

**Comment by dustymc** [comment]
Bah! Thanks for the patience, but I'd rather find something that works as expected. Unfortunately interacting with the OS via lucee is just sometimes complicated and a bit unpredictable, and I was trying to multitask. I found something that seems to work, and it looks like this approach is going to work in general, so I 

* Scheduled the pgcron cache-builder to run on the 13th of every month
* found a stable-ish place for the file
* dropped back to tar (I can go to zip or otherwise adjust whatever needs it without problem)
* set the file-builder cfschedule job to run on the 14th of every month
 
In theory, you should now always be able to find a less-than-month-old dump at https://arctos.database.museum/cache/gn_merge.tgz

I can easily adjust the schedule if doing so is somehow useful.

The compressed tarball should inflate to the files themselves

```
 tar -xvf gn_merge.tgz 
globalnames_classification.csv
globalnames_relationships.csv
globalnames_commonname.csv


-rw-r-----.   1 root root   10861857 Jan 12 10:21 globalnames_commonname.csv
-rw-r-----.   1 root root   73180513 Jan 12 10:21 globalnames_relationships.csv
-rw-r-----.   1 root root 5010469180 Jan 12 10:22 globalnames_classification.csv
-rw-r-----.   1 root root  646058890 Jan 12 10:25 gn_merge.tgz

```

I just ran everything manually so I have some hope that it's actually doing what I think it's doing this time....

**Comment by dimus** [comment]
Sounds great @dustymc!
I will probably harvest Arctos 2 times a year for some time, but still it is great to have monthly releases, because when I will get to automatic harvester, monthly updates will be very handy

**Comment by dimus** [comment]
The file seem to untar perfectly, so I will point to https://arctos.database.museum/cache/gn_merge.tgz in the
arctos script: https://github.com/GlobalNamesArchitecture/dwca_hunter/blob/master/lib/dwca_hunter/resources/arctos.rb

**Comment by dimus** [comment]
@dustymc, I created a DarwinCore File from your data and it is now importing into the system. For classification data I used the following algorithm:

1. Get a row, and if term_type is empty, ignore the row, otherwise collect the value of "term_type" and associate it with the scientific name.
2. After traversing data, I picked the name, classification fields (type, class, family etc) and the nomenclatural code.
3. Then I added synonymy (picking synonyms only, ignoring lexical variants) and  vernacular names.

The final numbers I got are:

* Names with classification: 3159669
* Synonyms: 3159669
*  Vernacualrs: 299027

Import would probably take a few hours, so tomorrow I will be able to try it with resolver.globalnames.org and gnverifier.

**Comment by dustymc** [comment]
I added a link for "us" to the top of the taxonomy page

```
<cfif isdefined("session.roles") and listfindnocase(session.roles,"coldfusion_user")>
    A taxonomy download is available - see https://github.com/ArctosDB/arctos/issues/3205#issuecomment-758809795 for more information.
</cfif>
```

so hopefully this won't get completely lost.

Looks like everything is working properly, closing.

**Comment by dimus** [comment]
Hi @dusty

I am having trouble accessing https://arctos.database.museum/cache/gn_merge.tgz
 
Looks like it is now behing login, and harvesting script cannot access it anymore
