### ISSUE TITLE
Update definition of Transfer

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#3208]
**Goal**
Broaden documentation definition of Transfer on the ACCN_TYPE code table - right now it is specific to universities. Transfers are common from wildlife rehabilitators, government entities, or other museums and are not technically gifts.

**Context**
current definition: Acquired via a transfer from another University unit or department where ownership at at the University level is already established, however the incorporation into the museum collections is new.

suggested definition: Acquired via transfer of possession from a separate unit within a home institution where ownership is already established, or from another public entity (e.g., museum, government unit, wildlife rehabilitator, university).

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctaccn_type

**Comment by campmlc** [comment]
I agree with this.

**Comment by Jegelewicz** [comment]
Ditto

**Comment by ewommack** [comment]
> from a separate unit within a home institution

This phrase is a little confusing. Do you mean the home institution of the museum receiving the transfer?

**Comment by AJLinn** [comment]
Maybe something more like this?

"Acquired via transfer of possession [from] BETWEEN TWO [separate] unitS within aN [home] institution where ownership is already established, or from another public entity (e.g., museum, government unit, wildlife rehabilitator, university)." (then give an example: "For example, transfer from an academic biology department of a university to the university museum, from an education collection within a museum to a research department of the same museum.")
