### ISSUE TITLE
clone into bulkloader fails

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#3209]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

I attempted to clone this record:

https://arctos.database.museum/guid/KNWR:Ento:10306

into the bulkloader with the relationship as 'self' and into collection UAM:Ento

Upon clicking 'create clone' a window popped up that said 'ERROR' with no other information.

The orignal page has the 'creating clone(s) - hold tight..." indicator with the spinning wheel, doing nothing 

**To Reproduce**

**Expected behavior**

Clone should appear in bulkloader as a UAM:Ento record

**Screenshots**

** Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label.
high

**Comment by dustymc** [comment]
I can do this, and any variation of it, successfully in test and production, and I can't find your error in the logs. Can you try again and report back with the error ID?

**Comment by DerekSikes** [comment]
I think this error resulted from there being 2 buttons to create a clone in the bulkloader - one under the options to select # of records, collection etc. and the other as a text hotlink in the text above that says 'click here' - I suspect I clicked this text hotlink thinking it would behave the same as the other button. This is a clear user interface fail. There should be only 1 button to do any action and if two buttons do different things that appear confusingly similar those should be clearly described so users know which one to use.

**Comment by dustymc** [comment]
Fair enough. Next release will look like this:

<img width="1217" alt="Screen Shot 2020-11-13 at 1 55 18 PM" src="https://user-images.githubusercontent.com/5720791/99124910-ea97ec80-25b7-11eb-82b0-888fb0491b02.png">
