### ISSUE TITLE
new portals page

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3211]
http://test.arctos.database.museum/home2

**Comment by campmlc** [comment]
Can we make it sortable by the column headers? Maybe swap institution and
collection type columns, with  larger, bold font for the institution names?

**Comment by dustymc** [comment]
>sortable

most tables I build are, this one included.

>swap

done

>bold

done

**Comment by Jegelewicz** [comment]
When you select details, how about allowing us to create a header like we do for the individual collections so that the page can include a logo, etc?

**Comment by dustymc** [comment]
Short answer is yes, but it's not as easy as it should be - we really need a framework and a css wizard. Reload.

**Comment by campmlc** [comment]
Looking better and better . . . how about using the same info from the
portal page for the title. I'd be happy replacing the portals page with
this.

Also some up down arrows or text to make it clear that each column header
is sortable? This way we can sort and see all herp collections, for example.

**Comment by dustymc** [comment]
>same info

You're going to have to be more specific, I don't know what this means.

>up down arrows 

That's just a library that I use everywhere - it's pretty minimal, I don't think it has any config options. https://github.com/ArctosDB/arctos/issues/2893 might lead to something with more features.

**Comment by campmlc** [comment]
top <http://test.arctos.database.museum/home.cfm#top>
Collections

ACBC <http://test.arctos.database.museum/home.cfm#ACBC>
ALMNH <http://test.arctos.database.museum/home.cfm#ALMNH>
APSU <http://test.arctos.database.museum/home.cfm#APSU>
ASNHC <http://test.arctos.database.museum/home.cfm#ASNHC>
BYU <http://test.arctos.database.museum/home.cfm#BYU>
CHAS <http://test.arctos.database.museum/home.cfm#CHAS>
COA <http://test.arctos.database.museum/home.cfm#COA>
DMNS <http://test.arctos.database.museum/home.cfm#DMNS>
HWML <http://test.arctos.database.museum/home.cfm#HWML>
JSNM <http://test.arctos.database.museum/home.cfm#JSNM>
KNWR <http://test.arctos.database.museum/home.cfm#KNWR>
KWP <http://test.arctos.database.museum/home.cfm#KWP>
MLZ <http://test.arctos.database.museum/home.cfm#MLZ>
MSB <http://test.arctos.database.museum/home.cfm#MSB>
MVZ <http://test.arctos.database.museum/home.cfm#MVZ>
NBSB <http://test.arctos.database.museum/home.cfm#NBSB>
NMMNHS <http://test.arctos.database.museum/home.cfm#NMMNHS>
NMU <http://test.arctos.database.museum/home.cfm#NMU>
OWU <http://test.arctos.database.museum/home.cfm#OWU>
UAM <http://test.arctos.database.museum/home.cfm#UAM>
UC-SCFS <http://test.arctos.database.museum/home.cfm#UC-SCFS>
UCM <http://test.arctos.database.museum/home.cfm#UCM>
UCSC <http://test.arctos.database.museum/home.cfm#UCSC>
UMNH <http://test.arctos.database.museum/home.cfm#UMNH>
UMZM <http://test.arctos.database.museum/home.cfm#UMZM>
UNM <http://test.arctos.database.museum/home.cfm#UNM>
UNR <http://test.arctos.database.museum/home.cfm#UNR>
USNPC <http://test.arctos.database.museum/home.cfm#USNPC>
UTEP <http://test.arctos.database.museum/home.cfm#UTEP>
UWBM <http://test.arctos.database.museum/home.cfm#UWBM>
UWYMV <http://test.arctos.database.museum/home.cfm#UWYMV>
WNMU <http://test.arctos.database.museum/home.cfm#WNMU>
Arctos is an ongoing effort to integrate access to catalog record data,
collection-management tools, and external resources on the internet. Read
more about Arctos at our Documentation Site <https://arctosdb.org/>,
explore some random content <http://test.arctos.database.museum/random.cfm>,
or use the links in the header to search for catalog records, media,
taxonomy, projects and publications, and more. Sign in or create an account
to save preferences and searches.

Arctos currently serves public data on 3,739,942 catalog records in 171
collections.

*Following the search links below will set your preferences to filter by a
specific collection or portal. You may click [ search all collections ]
<http://test.arctos.database.museum/all_all> at any time to re-set your
preferences.*

Please see https://arctosdb.org/join-arctos/ for information about joining
or using Arctos.

**Comment by campmlc** [comment]
If necessary, we can add a statement to the title:

"Click on each column header below to sort."

**Comment by dustymc** [comment]
The stuff at the bottom of http://test.arctos.database.museum/home.cfm isn't - and probably shouldn't be - on the new page. Can that - or whatever of it's still relevant - be moved to ``https://arctosdb.org/features`` (or something of the sort), so I can link to it from the top of the new page?

**Comment by mkoo** [comment]
Agreed-- let me copy that wad of nonsense at the bottom and add to that new
page (does that need to be linked on a page or menu?) but you can use
https://arctosdb.org/features (be up in a few minutes....)

Anyway, feel free to omit in the new portal page-- which is Fun to sort!

**Comment by dustymc** [comment]
thx/linked
