### ISSUE TITLE
Containers are buggy

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#3215]
**Describe the bug**
1. **Create container series:** When trying to bulkload a small batch of containers, I receive an error when validating my data despite having a correct info (institution code = UCM and container type = jar):
An error occurred while processing this page!
Message: Invalid container_type;Invalid institution_acronym; this form is a very bad place to experiment
So something seems buggy given that I have previously loaded over 4000 containers this route with no issue (and no trailing spaces etc.).
2. After multiple failed attempts to load my container series spreadsheet, I began to enter containers by hand since I only have 18 that I need to create. The one-off process is working, however, after I added environmental data to my first container, it somehow keeps replicating in any subsequent container that I create. For instance, I just created a new container, and upon hitting save, pre-populated environmental history data randomly appears:

![image](https://user-images.githubusercontent.com/11336485/99277938-b0169580-27eb-11eb-80a5-7118c503fbaf.png)

**Comment by dustymc** [comment]
Data please.

I have no explanation for the second thing. I can say that the code looks right, I can't do it, I don't see any series of duplicates in the logs, and "Genevieve" and  "Anderegg" are used only once, for https://arctos.database.museum/EditContainer.cfm?container_id=20738616. Can you replicate that behavior? Can you do so with all of your browser extensions off? I'll keep looking.....

**Comment by ebraker** [comment]
CSV attached. [container_BL.zip](https://github.com/ArctosDB/arctos/files/5548610/container_BL.zip) - though now the first three rows in the sheet are hand-loaded.

Hmmm, I opened Arctos in Explorer (vs Chrome) and am still seeing the same environmental history on three records when I only entered it for one:
http://arctos.database.museum/EditContainer.cfm?container_id=20738615
http://arctos.database.museum/EditContainer.cfm?container_id=20738616
http://arctos.database.museum/EditContainer.cfm?container_id=20738617

**Comment by dustymc** [comment]
Thanks. The initial problem is the blank line in the CSV.

<img width="527" alt="Screen Shot 2020-11-16 at 9 29 40 AM" src="https://user-images.githubusercontent.com/5720791/99286858-58c5f480-27ee-11eb-8f7f-0e69625a928e.png">


I see what you're seeing. It's not real -

```
arctosprod@arctos>> select * from container_environment  where container_id=20738615;
 container_environment_id | container_id | check_date | checked_by_agent_id | parameter_type | parameter_value | remark 
--------------------------+--------------+------------+---------------------+----------------+-----------------+--------
(0 rows)

```

- SOMETHING is caching when it shouldn't be. I'll get on that ASAP.

**Comment by ebraker** [comment]
Ok, thank you much. I'll interpret seeing things that aren't real as acceptable in this circumstance...

**Comment by dustymc** [comment]
>seeing things that aren't real as acceptable in this circumstance

That, as far as I can tell, is EXACTLY how Lucee, Postgres, or perhaps the JDBC drivers, feel about the situation!

It's fixed and patched. Lam found the problem; PG is weirder about datatype then I'd fully internalized. I'll scan the rest of the code for similar conditions.

Thanks!

**Comment by ebraker** [comment]
Cool - thanks to you and Lam!
