### ISSUE TITLE
Reporter Error

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#3216]
I receive an error when trying to access reports (either from Edit Containers->print or from Edit Loans->Print any Invoice):

![image](https://user-images.githubusercontent.com/11336485/99298955-c5012200-2807-11eb-874e-04d0d2d8914c.png)

Seems new?

**Comment by dustymc** [comment]
Do you have a lot of tabs open? The link to the reporter is a big fragile. This works for me:

https://arctos.database.museum/EditContainer.cfm?container_id=20738616

<img width="99" alt="Screen Shot 2020-11-16 at 11 42 05 AM" src="https://user-images.githubusercontent.com/5720791/99299943-d135b100-2800-11eb-80a2-0946dc22d084.png">
<img width="745" alt="Screen Shot 2020-11-16 at 11 42 10 AM" src="https://user-images.githubusercontent.com/5720791/99299950-d3980b00-2800-11eb-815d-e6bf04ab7fdc.png">
<img width="751" alt="Screen Shot 2020-11-16 at 11 42 19 AM" src="https://user-images.githubusercontent.com/5720791/99299960-d692fb80-2800-11eb-8977-cb81d454adc3.png">

**Comment by ebraker** [comment]
Busted. I had a dizzying amount of tabs open..... Thanks!
