### ISSUE TITLE
Annotations - Mapping Errors

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#3217]
Question on annotations...  Most annotations correctly point out coordinate errors. However, a few state that georefs are not falling within a particular county, when it appears that they are fully within the boundaries. Any ideas as to why? Examples below from birds collected in Navajo County, AZ.

![image](https://user-images.githubusercontent.com/11336485/99423365-b70dd880-28bd-11eb-956a-9e4c7b76c0b4.png)
https://arctos.database.museum/guid/UCM:Bird:11223

![image](https://user-images.githubusercontent.com/11336485/99423269-9e9dbe00-28bd-11eb-9255-8a14d456dfa0.png)

https://arctos.database.museum/guid/UCM:Bird:9986
![image](https://user-images.githubusercontent.com/11336485/99424010-6a76cd00-28be-11eb-9fcb-c96dd1c28287.png)

**Comment by dustymc** [comment]
Wild guess: You fixed it?

<img width="673" alt="Screen Shot 2020-11-17 at 9 56 21 AM" src="https://user-images.githubusercontent.com/5720791/99428223-36e67380-28bb-11eb-9614-46da8a6231bf.png">

In any case the map border is green, so it's happy now.

<img width="1104" alt="Screen Shot 2020-11-17 at 9 57 15 AM" src="https://user-images.githubusercontent.com/5720791/99428316-54b3d880-28bb-11eb-8ad3-f5c66e3481b0.png">

**Comment by ebraker** [comment]
Ok gotcha - didn't realize it was an old annotation. Thanks as always!
