### ISSUE TITLE
error feedback

### ISSUE THREAD

**Issue by cefilipek** [ArctosDB/arctos#3218]
I am attempting to upload my bulkload file and I keep getting the same error message.

<img width="777" alt="Screen Shot 2020-11-17 at 2 39 51 PM" src="https://user-images.githubusercontent.com/56844074/99445335-0adee880-28e3-11eb-8247-4199bfef19e6.png">

I have no clue what it means, I included no external processes in my spreadsheet and the error isn't listed in the handbook. I downloaded a new bulkloader file and entered the information again, but nothing changed. I will attach the file below.

[A_Bulkloader Backup Excel File 0010561-0010600.zip](https://github.com/ArctosDB/arctos/files/5556117/A_Bulkloader.Backup.Excel.File.0010561-0010600.zip)

Thank you for any help you can provide.

**Comment by Jegelewicz** [comment]
Its something in the line number 30, but I don't know exactly what. Could be that the agent name should be "unknown" instead of "Unknown"

**Comment by cefilipek** [comment]
I don't have any agent names as unknown. The only time I have unknown capitalized is under Verbatim Date. I thought maybe it was line 42 (maybe it is line 30, the error detail often makes little sense to me, so it's hard to fix upload errors), but it's empty and no amount of deleting fixed it.

**Comment by dustymc** [comment]
It's not valid CSV - whatever you're using to make CSV is broken or confused

>Catalog card reads "#17 F.M.C.F." in addition

should have the quotes escaped, at least. Preview dumps the rest of the file in that cell, so the problems may be deeper than that.

**Comment by cefilipek** [comment]
That's odd. I saved it the exact same way as yesterday. All I do is save as and select CSV. There are about 5 different CSV options, but I've been using CSV UTF-8 (Comma delimited) since I started working with Arctos.

**Comment by cefilipek** [comment]
I removed the apostrophes and it uploaded, so that seems to have been the issue. Thanks for all your help!

**Comment by dustymc** [comment]
Arctos is in fact UTF - https://handbook.arctosdb.org/documentation/encoding.html

I don't use Excel but perhaps someone else can help with that.

Dangit 20 seconds too late!
