### ISSUE TITLE
query compiler

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3219]
AnySciName-->KML is broken; can the query code compiler be modularized?

**Comment by ewommack** [comment]
What does moduralized mean? Breaking it up into independent modules to run interchangeably?

**Comment by dustymc** [comment]
Yup. It would mean that I'm maintaining a single block of code in a single place, then using it in various places, which I'm not 100% sure is possible for this.

**Comment by ewommack** [comment]
Yeah I learned something! Thanks @dustymc

**Comment by dustymc** [comment]
See https://github.com/ArctosDB/arctos/issues/3230; this is breaking expected functionality, going critical

**Comment by dustymc** [comment]
I can't find a global solution; KML thing will be patched in next release.
