### ISSUE TITLE
Error when adding multiple catalog items to media

### ISSUE THREAD

**Issue by AdrienneRaniszewski** [ArctosDB/arctos#3221]
**Describe the bug**
I'm getting an error when attempting to add multiple catalog records at once to media.

**To Reproduce**
I uploaded media and then tried to add relationships using the "Add multiple "shows cataloged_item" records" link. I also tried adding to media that was already uploaded.

I got this error: 

An error occurred while processing this page!
Message: ERROR: for SELECT DISTINCT, ORDER BY expressions must appear in select list Position: 67
Detail:
Check the Arctos Handbook for more information on errors.
This message has been logged as 737FE588-D879-4044-80C672D6F11ECF7D Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue

**Expected behavior**
I expected it to work. like it always has in the past

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7
 - Browser: Chrome
 - Version: 86.0.4240.198

**Comment by dustymc** [comment]
You in a hurry? I could probably get things stuck back together tonight if I need to.

**Comment by AdrienneRaniszewski** [comment]
I was gonna have a student work on uploading some files. but I also didn't want to rush you...

**Comment by dustymc** [comment]
Should be happy.
