### ISSUE TITLE
New Part "blood clot (frozen)" Code Table Request - 

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3222]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Goal**
Add a part that is associated with the collection of blood serum.

**Context**
We currently have blood serum, but not blood clot. Serum is obtained from clotted blood that has not been mixed with an anticoagulant (a chemical that prevents the clotting of blood). This clotted blood is then centrifuged, yielding serum, which contains two types of protein: albumin and globulin. Serum is usually collected in mottled red/gray, gold, or cherry red-top tubes, and red-top tubes are occasionally used.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name

**Value**
blood clot (frozen)

**Definition**
For serological studies, blood clots are obtained from clotted blood that has not been mixed with an anticoagulant which may be centrifuged to separate out and collect serum. The blood serum is typically collected in  mottled red/gray, gold, or cherry red-top tubes, and red-top (gel barrier) tubes which contain clot activator and gel for separating serum from cells, but not anticoagulant. Serum may be removed, and the residual clot may be preserved separately and frozen.

**Collection type**
Mamm

**Attribute data type**
free-text, categorical, number+units

**Attribute value**
For categorical attributes, code table controlling value

**Attribute units**
For number+units attributes, code table controlling units

**Part tissue flag**
yes, tissue

**Other ID BaseURL**
For OtherIDs, URL with which to prepend value (resolvable identifiers only)

**Priority**
high

**Comment by dustymc** [comment]
There's never been a better place to use attributes.

**Comment by campmlc** [comment]
And yet we have the part "blood serum" which is the flip side of this coin.
Both the serum and the clot are collected by the same method and stored
separately.
This is a legitimate part that we receive from veterinary clinics.
Happy to use attributes for "frozen" once that change is made globally.

**Comment by Jegelewicz** [comment]
Ok to add

**Comment by Jegelewicz** [comment]
Done. Agree with @dustymc assessment, but we want to explore #3044
