### ISSUE TITLE
Odd error message when trying to look at Edit for a Locality

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#3223]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I was searching for a locality to use for specimens with no known locality in California, so specific locality unknown, California. I used the Find Locality search window and found several promising possibilities, but when I went to click on the Edit link to find out more about them I got the following error:
An error occurred while processing this page!
Message: ERROR: relation "geology_attributes" does not exist Position: 26
Detail:
Check the Arctos Handbook for more information on errors.

**To Reproduce**
Go to the Find Locality page -> type in California into state or province and unknown into specific locality -> sort by county so you get the ones without county -> go down to the fourth locality:

Catalog RecordsEditCheck DupsDetails✅ Has Spatial Geography |   | North America, United States, California | http://en.wikipedia.org/wiki/California | North America | United States | California |   |   |   |   |   |   |   |   | 10598246 | specific locality unknown |   |   |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

(I can't find the reference number in the table)

**Expected behavior**
I've been able to look at the locality information before, and I would like to double check what the info and specimens that previously selected the locality are before I use it for cataloging. I'm not sure what the error of geology attributes do not exist means....

**Comment by dustymc** [comment]
Neato...

I'll try to get a patch out tonight.

**Comment by alexkrohn** [comment]
Just opened (and then closed when I saw this one) an issue with the same problem editing localities in the UCSC collection. I'd love to  know when you have a patch so I can send my students back georeferencing. Thanks!

**Comment by dustymc** [comment]
I snuck a fix in.

**Comment by ewommack** [comment]
Thanks @dustymc! It works, and I can see that locality was not the one I wanted. Yeah!

**Comment by alexkrohn** [comment]
Works for me too. Thanks @dustymc
