### ISSUE TITLE
Add Part Attributes via Modify Parts Tool

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3227]
We are increasingly using part attributes to deal with preservation and other data fields. Adding the ability to bulk update and add part attributes to multiple records using Catalog Record Search Results -> Modify Parts would greatly enhance our tool kit for using part attributes. I would like to be able to use this tool to bulk add a part with part attributes and/or part attributes only to existing records based on a catalog record search.

Priority: high, given the need to implement this model and move forward with treating preservation as a part attribute.

**Comment by dustymc** [comment]
Please clarify: is this request for add only?

Whatever the answer it's probably not too hard to pull off technically, but it will be sloppy. That's fine in a collection without barcodes, but I can't quite grasp why you'd want to - or be willing to consider allowing anyone to! - use this. Further explanation would be exceedingly useful.

**Comment by Jegelewicz** [comment]
We have the add part attribute tool - BUT when you have two identical part names, the tool cannot add attributes. What kind of solution can we come up with for that scenario?

**Comment by campmlc** [comment]
Add only at a minimum would be necessary, but modify would also be useful. To be clear, I am asking to modify the existing tool below to include part attribute options.  Adding a field for Barcode would also be useful, but in most cases at MSB this form has been used frequently for the many collections that do not use barcodes.  It is a much more efficient and user friendly tool than going through bulkloaders to update records, and would encourage use of part preservation attributes.
[Bulk Modify Parts.pdf](https://github.com/ArctosDB/arctos/files/5574831/Bulk.Modify.Parts.pdf)

**Comment by dustymc** [comment]
>What kind of solution can we come up with for that scenario?

Some sort of unique-within-scope machine-readable part identifiers would do it....

**Comment by Jegelewicz** [comment]
So stuff that is barcoded should be easy-peasy?

**Comment by Jegelewicz** [comment]
Add only at a minimum would be necessary

we have that already - https://arctos.database.museum/tools/BulkloadSpecimenPartAttribute.cfm

**Comment by campmlc** [comment]
This tool is way more user friendly than the bulkloaders. It allows me to do a task in a few minutes - e.g. go to an accession, pull up all records, add or modify parts - which would take an hour or more of complex download, template mapping, editing, reupload using one or more bulkloaders.

**Comment by Jegelewicz** [comment]
I can see how adding a preservation in this way would be useful. Not sure the best way for it to happen though.

**Comment by campmlc** [comment]
Not to mention that I cannot easily download existing part attributes to use to modify a bulkload file.

**Comment by acdoll** [comment]
This would be a useful addition; especially when working with part preservation attributes

**Comment by KyndallH** [comment]
I'd also like to see adding attributes under the "modify parts" on Arctos. I would be more likely to use it especially when editing small number of specimens versus dealing with the bulkloaders. Sometimes you don't need a bulkloader and just want to use the Arctos interface.

Also, is there a way to add more than 3 parts to a specimen at a time on "modify parts"? I had two yesterday that had 30 and 50 parts I needed to add - not enough to warrant the bulkloader. Pain is that when you enter 3, if sends you out of modify parts and sends you back to the specimen. My short-term workaround was I opened 10+ modify parts windows but should be an easier way.

**Comment by Jegelewicz** [comment]
> Not to mention that I cannot easily download existing part attributes to use to modify a bulkload file.

Resolved with Parts/table download

> Some sort of unique-within-scope machine-readable part identifiers would do it....

See #3630 

but, would it be possible to include a check box to remove certain parts from the modification in the way that we can remove records from a catalog search?

**Comment by cjconroy** [comment]
We recently received back a pile of embryos for which the mom is cataloged. I can easily bulk add all the part = embryo to the records. But, what is the current easiest, fastest way to add:


preservation | formalin, 10% buffered |   |   |   |   |  
-- | -- | -- | -- | -- | -- | --
preservation | ethanol, 70%

I don't see anything in the Arctos support documents. Do we have to do this record by record?

**Comment by Jegelewicz** [comment]
Part attributes are part of the part bulkloader.

Just add a preservation attribute to each embryo part. Let me know if you need an example.

**Comment by cjconroy** [comment]
Yes, I would like to see an example. These specimens were preserved in formalin then transferred to 70% ethanol. Can you send screen pics or something? Thanks.

**Comment by Jegelewicz** [comment]
@cjconroy maybe send me a record or two and the data you need to add? I'll format it for you so you can follow the formula to do them all.

**Comment by cjconroy** [comment]
I know how to do it one by one. I am looking to do a bunch at once. Go to the part, manage attributes, add attribute one for the formalin, then add another attribute for the 70% ethanol. 
If there is a faster way, I'd love to hear it. Here are two MVZ records that need part of embryo added. https://arctos.database.museum/guid/MVZ:Mamm:163247
https://arctos.database.museum/guid/MVZ:Mamm:163273

Thanks.

**Comment by Jegelewicz** [comment]
@cjconroy here you go. Add your GUIDs to this and load it to the <a href="https://arctos.database.museum/tools/BulkloadParts.cfm?action=ld" target="_blank>Part Bulkload Tool</a>

You may want to adjust the condition, disposition or add dates/agents to the preservations - that is up to you.

BUT - are you sure that you don't want to catalog the embryos separately and provide relationships to the mother? I'm guessing you've already made that decision, but it never hurts to ask!

Let me know if you have any questions.

[MVZ_Mamm_bulkloadParts.csv](https://github.com/ArctosDB/arctos/files/7262101/MVZ_Mamm_bulkloadParts.csv)

**Comment by cjconroy** [comment]
Thanks. We will give it a shot. 
I would still rather have a part that looks like "embryo (formalin fixed, 70% ethanol)", but I don't think that is going to happen.

**Comment by campmlc** [comment]
The problem with that is that we end up with astronomical numbers of
parts + preservation type 1+ preservation type 2 etc. I agree that the
display interface of embryo (formalin fixed, 70% ethanol)" is much simpler,
but using attributes allows us to capture who applied the preservative on
what date and using what method.  Perhaps we can work on how this info is
displayed.

**Comment by Jegelewicz** [comment]
@cjconroy yep - use this tool

https://arctos.database.museum/tools/BulkloadSpecimenPartAttribute.cfm

Just post here if you have questions!

**Comment by Jegelewicz** [comment]
yes - that is ALL it does, it does not add parts

**Comment by cjconroy** [comment]
My parts now have barcodes. Looks like I need to use either part ID or barcode to identify the particular part. What is a good way to fetch these 52 numbers for one or the other?  In typical download, these values are in field partdetail, but its a mess of stuff in there.

**Comment by atrox10** [comment]
We discussed this at the January Issues meeting - can we add attributes preservation type to the "Modify Parts" tab from the Manage menu? I add parts or modify a lot from here, but right now if I add parts to a bunch of specimens using this (whicjh is great and super easy) then I have to either go back and individual modify their preservation attribute for EACH record or do a separate bulkloader, which is very time consuming (and draws out the process a lot).

**Comment by KyndallH** [comment]
Could we add include or exclude disposition type? I need some way to weed out tissue that is on loan - I don't want to update their preservation attributes.

<img width="1818" alt="Screen Shot 2022-04-22 at 3 46 58 PM" src="https://user-images.githubusercontent.com/16887896/164824005-e0dc67cc-fbf5-4f53-bc2f-2f63dfe9e0fb.png">
