### ISSUE TITLE
Feature Request - funky data tool

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3228]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

We are not good at recording usage

**Describe what you're trying to accomplish** 

Document collections.

**Describe the solution you'd like**

See https://github.com/globalbioticinteractions/globalbioticinteractions/issues/537#issuecomment-730736497

Is it possible to create a report of things that are in globi, and do not have a loan history?

Is it useful? Do collections care?

**Describe alternatives you've considered**

Don't; this would likely result in many "someone downloaded from GBIF and the collections don't care" reports, which could be annoying.

**Additional context**

**Priority**

Please assign a priority-label.

**Comment by campmlc** [comment]
Yes - this would be useful:  Is it possible to create a report of things
that are in globi, and do not have a loan history?

**Comment by campmlc** [comment]
Possibly add to a collections dashboard - have a public dashboard with
basic collections information, loans, pubs, etc - and then have a
curatorial dashboard with more detailed documentation of usage such as the
above.

**Comment by dustymc** [comment]
This would still be cool, but I don't know how practical it is - maybe needs a grant? I'm also not at all convinced it would be used - eg, "undocumented citations" still finds hundreds of similar records for most well-used collections and that doesn't seem to be much changing. Tentatively tabling.
