### ISSUE TITLE
help with Create Container Series

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#3229]
I need some help with Create Container Series. I split up the 42K container barcodes I have into four files to stop the timeouts (probably due to slow connections here). Two of the files loaded fine, the other two keep giving me:

An error occurred while processing this page!
Message: ERROR: Invalid barcodes detected Where: PL/pgSQL function batchcreatecontainer() line 28 at RAISE
Detail: Parameter types passed (0):
--

I've verified that they all conform to our claimed barcode series (I think) and that there are no special characters (I think; Excel has done some unexpected conversions in the past).  @dustymc could you please take a look and push them through?

[Remaining Batch1 upload.zip](https://github.com/ArctosDB/arctos/files/5575379/Remaining.Batch1.upload.zip)

**Comment by dustymc** [comment]
<img width="321" alt="Screen Shot 2020-11-20 at 11 07 06 AM" src="https://user-images.githubusercontent.com/5720791/99840233-0869d200-2b21-11eb-8a66-44be9f5bf7ad.png">
<img width="204" alt="Screen Shot 2020-11-20 at 11 07 34 AM" src="https://user-images.githubusercontent.com/5720791/99840237-0a339580-2b21-11eb-9fdb-fb64ae2240d3.png">

SELECT barcode,IS_CLAIMED_BARCODE(barcode) from temp_cache.temp_dlm_uptbl order by IS_CLAIMED_BARCODE(barcode)




  | barcode | is_claimed_barcode
-- | -- | --
1 | DMNSZT38083 | FAIL
2 | DMNSZT39757 | FAIL
3 | DMNSZT37958 | FAIL
4 | DMNSZT1EKI1 | PASS





<img width="389" alt="Screen Shot 2020-11-20 at 11 11 30 AM" src="https://user-images.githubusercontent.com/5720791/99840391-554da880-2b21-11eb-9c63-12c8df06ef70.png">

barcode~'^DMNSZT[0-9]{1}[A-Z]{1}[A-Z0-9]{3}$'

Those are failing at [A-Z]{1} - 8, 9, and 7 are expected to be capital letters.

Here's the fails from the other file


  | DMNSZT36929 | FAIL
-- | -- | --
2 | DMNSZT37015 | FAIL
3 | DMNSZT0V8TQ | PASS

**Comment by acdoll** [comment]
Ahhh..got it. I forgot about the [A-Z]{1} requirement (why I did that...??). Thank you!
