### ISSUE TITLE
Taxonomy Search "contains" not working

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#3230]
When I search for a taxon name with "%" to include everything that "contains" the string, I don't get everything.  This search is for everything that contains "scalarina" but only brings up "Scalarina."

<img width="435" alt="Screen Shot 2020-11-19 at 8 24 39 AM" src="https://user-images.githubusercontent.com/15368365/99846193-23454200-2b33-11eb-8767-0b1761ae0139.png">

The taxon I was looking for does exist - _Arca scalarina_.

<img width="514" alt="Screen Shot 2020-11-19 at 8 25 10 AM" src="https://user-images.githubusercontent.com/15368365/99846202-26d8c900-2b33-11eb-8cb0-2693d50e8f64.png">

The search "%scalarina" should bring up both Scalarina and _Arca scalarina_.  Also, in the past the results statement would repeat the CONTAINS search term, but it no longer does that.

A search for "gigas" returns nothing but there are many taxon names that contain "gigas" - 350 in WoRMS alone.

It hasn't been working for a long time.

Mac/Safari but it's the same on FireFox.

**Comment by acdoll** [comment]
I tested with some other taxa, got similar results. e.g.:
Search: %tamias --> results: Tamias
Search %eutamias --> results: Eutamias
Search %tamias% --> results: Tamias and all species and subspecies
Search %eutamias% --> results: Eutamias and all species and subspecies

**Comment by dustymc** [comment]
This is a symptom of https://github.com/ArctosDB/arctos/issues/3219

**Comment by sharpphyl** [comment]
> This is a symptom of #3219 

I never would have guessed.  Sounds like you're already working on it.  Should we close this?

**Comment by dustymc** [comment]
This is fixed, but the taxonomy page is very broken - @Jegelewicz there are hard-coded head and body tags in addition to the includes and I've lost a big chunk of my screen and everything melts when I scroll! What I think you're attempting can't (easily, anyway) be done piecemeal, it's easy to do that sitewide but taking away half my screen REALLY needs discussed first.

**Comment by Jegelewicz** [comment]
It doesn't do any of that for me, so I'll work to take all that way tomorrow.

It looks perfectly fine to me....
![image](https://user-images.githubusercontent.com/5725767/100680726-74251980-332f-11eb-8e8c-c6843b198629.png)

**Comment by dustymc** [comment]
Scroll is back, there's still an extra doctype declaration.

Yes browsers are often pretty good at dealing with about anything, malformed HTML will still break things eg screen readers.

**Comment by Jegelewicz** [comment]
@dustymc I think you caught me in the middle of an experiment.

Without the doctype declaration, I cannot "see" the code in Atom (it's just a bunch of text - the doctype highlights the brackets and stuff). How does it screw anything up?

**Comment by dustymc** [comment]
Try moving your code after 

```
<cfinclude template="includes/_header.cfm">
```

which sets doctype, or maybe there's some setting in whatever editor you're using. (I use eclipse+cfeclipse, FWIW.)

I don't know what multiple declarations might break, but it's not valid HTML so the only safe assumption is that it'll break something. I think there were a couple HEAD and BODYs as well, those seem more likely to break something noticeable (like local js).

**Comment by Jegelewicz** [comment]
Also, you said I should experiment in the fix folder, but I am not able to view any of the pages there in test. I'd like to have a sandbox for experimenting, but I need to be able to see how the results appear in test. How can I do that and not get in the way of your progress?

**Comment by Jegelewicz** [comment]
I commented out the head and body tags - but for me they didn't seem to break anything when they were there - Phyllis reviewed the page with them there as well.

**Comment by Jegelewicz** [comment]
moving the template doesn't work in Atom:

![image](https://user-images.githubusercontent.com/5725767/100756932-00285700-33ab-11eb-9beb-e50757210f95.png)

**Comment by Jegelewicz** [comment]
I'll get eclipse+cfeclipse

From here? https://github.com/cfeclipse/cfeclipse/wiki/Installing-CFEclipse

**Comment by dustymc** [comment]
Why can't you see /fix/ stuff - what happens when you try?

**Comment by Jegelewicz** [comment]
![image](https://user-images.githubusercontent.com/5725767/100758359-a9238180-33ac-11eb-8e85-aaf948142655.png)

**Comment by Jegelewicz** [comment]
Also this
![image](https://user-images.githubusercontent.com/5725767/100758518-d5d79900-33ac-11eb-833f-f2b8b00757de.png)

**Comment by Jegelewicz** [comment]
Oh man, there are too many options at https://www.eclipse.org/downloads/packages/

What do I get?

**Comment by dustymc** [comment]
First one needs permissions

<img width="325" alt="Screen Shot 2020-12-01 at 7 18 17 AM" src="https://user-images.githubusercontent.com/5720791/100759401-690cd080-33a5-11eb-9236-e035f0095b42.png">

Second one just doesn't exist.

Eclipse is a giant pain in the butt, I just get the simplest thing I can find (probably the java package), then you can install stuff (egit, cfeclipse) from within eclipse and ignore all the junk that you'll never need. I'm not really _recommending_ it, but it does know CFML and does a decent job with code coloring and I haven't found anything that sucks less, so....

**Comment by Jegelewicz** [comment]
> Second one just doesn't exist.

Why not? What have I done wrong?

![image](https://user-images.githubusercontent.com/5725767/100760468-03bddd00-33af-11eb-995a-ccf33ee4d520.png)

**Comment by dustymc** [comment]
<img width="57" alt="Screen Shot 2020-12-01 at 7 30 17 AM" src="https://user-images.githubusercontent.com/5720791/100760869-146a5500-33a7-11eb-8292-3d821d4e6231.png">
<img width="44" alt="Screen Shot 2020-12-01 at 7 30 30 AM" src="https://user-images.githubusercontent.com/5720791/100760890-1b916300-33a7-11eb-857c-61d122f004c1.png">

**Comment by Jegelewicz** [comment]
OK, I think I have it now - DOH
