### ISSUE TITLE
flat.full_taxon_name

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3231]
It's currently generated from a concatenation of terms in flat - kingdom, phylum, etc. That doesn't work for things like minerals (which may have term types not in flat), it doesn't work for things like phylocode (which may have unranked terms), and it wouldn't include eg subkingdom (which isn't a column in flat).

We've been concatenating the terms themselves for multi-taxa ID (so eg "... Mammalia, Aves; ...." for "bird and mouse" IDs), but multi-taxa IDs can now span Sources so I don't think that makes sense any longer - the expectation of somewhat consistent data on which that was built exists less now than ever.

I've got an approach that concatenates terms for each involved classification, then concatenates those if necessary, running in test. 

"Normal" identifications should look about the same as always, but may contain terms omitted by the previous concatenation.

http://test.arctos.database.museum/guid/UWBM:Mamm:68521

leads to

Animalia, Chordata, Mammalia, Rodentia, Myomorpha, Cricetidae, Neotominae, Peromyscus, Peromyscus maniculatus

http://test.arctos.database.museum/guid/ALMNH:ES:1503

leads to

Animalia, Chordata, Chondrichthyes, Lamniformes, Lamnidae, Squalicorax, Squalicorax pristodontus; Animalia, Chordata, Elasmobranchii, Lamniformes, Lamnidae, Squalicorax, Squalicorax kaupi

and http://test.arctos.database.museum/guid/NMMNH:Paleo:1

leads to

Elements and Alloys (including the arsenides, antimonides and bismuthides of Cu, Ag and Au), Copper; Elements, Metallic and intermetallic compounds, Carbides, Nitrides, Phosphides and Silicides, Copper, Silver and Gold, Copper; Native Elements and Alloys, Metals, other than the Platinum Group, Copper

Timely feedback greatly appreciated. I'll implement this in production in a few days if nobody has a better idea.

**Comment by Jegelewicz** [comment]
Still does not address #3197

![image](https://user-images.githubusercontent.com/5725767/99853444-314d8f80-2b40-11eb-8226-841b7dd3cdd0.png)


Which should have
**Copper**
Elements and Alloys (including the arsenides, antimonides and bismuthides of Cu, Ag and Au), Copper
Cu

**Comment by dustymc** [comment]
>Still does not address #3197

Elaborate please.

**Comment by Jegelewicz** [comment]
http://test.arctos.database.museum/guid/ALMNH:ES:1503
shows the preferred classification

![image](https://user-images.githubusercontent.com/5725767/99854120-74f4c900-2b41-11eb-86fd-0545a8b8db2f.png)

 http://test.arctos.database.museum/guid/NMMNH:Paleo:1
does not
![image](https://user-images.githubusercontent.com/5725767/99854142-8211b800-2b41-11eb-8507-30389a4e24d6.png)

**Comment by dustymc** [comment]
It's not there yet.

```
arctosprod@arctosutf>> select getFlatTaxonomy(collection_object_id) from flat where guid='ALMNH:ES:1503';
{
   "v_kingdom":"Animalia; Animalia",
   "v_full_taxon_name":"Animalia, Chordata, Chondrichthyes, Lamniformes, Lamnidae, Squalicorax, Squalicorax pristodontus; Animalia, Chordata, Elasmobranchii, Lamniformes, Lamnidae, Squalicorax, Squalicorax kaupi",
   "v_phylclass":"Elasmobranchii; Chondrichthyes",
   "v_phylum":"Chordata; Chordata",
   "v_phylorder":"Lamniformes; Lamniformes",
   "v_family":"Lamnidae; Lamnidae",
   "v_genus":"Squalicorax; Squalicorax",
   "v_species":"Squalicorax pristodontus; Squalicorax kaupi",
   "v_subspecies":null,
   "v_author_text":"(Agassiz, 1843)",
   "v_nomenclatural_code":"ICZN; ICZN",
   "v_infraspecific_rank":null,
   "v_formatted_scientific_name":"<i>Squalicorax pristodontus</i>; <i>Squalicorax kaupi</i> (Agassiz, 1843)",
   "v_subfamily":null,
   "v_tribe":null,
   "v_subtribe":null,
   "v_taxon_rank":null
}

arctosprod@arctosutf>> select getFlatTaxonomy(collection_object_id) from flat where guid='NMMNH:Paleo:1';

{
   "v_kingdom":null,
   "v_full_taxon_name":"Elements and Alloys (including the arsenides, antimonides and bismuthides of Cu, Ag and Au), Copper; Elements, Metallic and intermetallic compounds, Carbides, Nitrides, Phosphides and Silicides, Copper, Silver and Gold, Copper; Native Elements and Alloys, Metals, other than the Platinum Group, Copper",
   "v_phylclass":null,
   "v_phylum":null,
   "v_phylorder":null,
   "v_family":null,
   "v_genus":null,
   "v_species":"Copper; Copper; Copper",
   "v_subspecies":null,
   "v_author_text":null,
   "v_nomenclatural_code":"unknown; unknown; unknown",
   "v_infraspecific_rank":null,
   "v_formatted_scientific_name":null,
   "v_subfamily":null,
   "v_tribe":null,
   "v_subtribe":null,
   "v_taxon_rank":null
}
```

**Comment by dustymc** [comment]
It's there now, I updated http://test.arctos.database.museum/guid/ALMNH:ES:1503

<img width="650" alt="Screen Shot 2020-11-30 at 9 19 17 AM" src="https://user-images.githubusercontent.com/5720791/100642075-2982ad80-32ed-11eb-90a3-cddbcd46f892.png">

 and http://test.arctos.database.museum/guid/NMMNH:Paleo:1

<img width="643" alt="Screen Shot 2020-11-30 at 9 19 50 AM" src="https://user-images.githubusercontent.com/5720791/100642132-3a332380-32ed-11eb-93c6-9801cd1d7929.png">

I'll push this to production soonish if there's no other feedback.

**Comment by Jegelewicz** [comment]
HMMMM the copper one looks different to me:
![image](https://user-images.githubusercontent.com/5725767/100653827-3069ea00-3306-11eb-9456-47cc453047f5.png)

**Comment by dustymc** [comment]
Log in - https://github.com/ArctosDB/internal/issues/65 means I can't run automation, you're looking at filtered_flat which hasn't been updated.

**Comment by dustymc** [comment]
Enthusiastic silence accepted; this is in production.
