### ISSUE TITLE
Find Loan pick collection dropdown needs larger display

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3232]
Please change the Find Loan pick collection dropdown to same display parameters as the Create Loan pick collection dropdown.
Currently, Find Loan pick collection only allows 3 collections visible at a time, with a tiny scroll bar.  Very frustrating to use on a laptop. The Create Loan form works much better. Can we just copy over please?
And yes, there is another issue somewhere .
![image](https://user-images.githubusercontent.com/14808196/99853451-33afe980-2b40-11eb-91ea-69e4102c031e.png)

 vs

![image](https://user-images.githubusercontent.com/14808196/99853525-5d691080-2b40-11eb-9263-4306a32c28c6.png)

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/3012

**Comment by campmlc** [comment]
Please see that all I am asking for is for the UI display to be enlarged in the Find Loan tool to display more than 3 collections at a time - just a bigger box, like the colletion dropdown in Create Loan.  No data changes, just display.

**Comment by Jegelewicz** [comment]
@campmlc how does this look? http://test.arctos.database.museum/Loan.cfm?Action=addItems

**Comment by dustymc** [comment]
@Jegelewicz that was multi-collection because someone asked for multi-collection. It needs that functionality.

**Comment by dustymc** [comment]
This seems to have been fixed in https://github.com/ArctosDB/arctos/issues/3012, and the reduced-functionality unfix just went to production. Upping priority.

**Comment by Jegelewicz** [comment]
@dustymc it seems to look fine to me...

<img width="960" alt="Screenshot 2020-12-08 07 20 00" src="https://user-images.githubusercontent.com/5725767/101495492-db416000-3925-11eb-862b-c30a74c2034d.png">

**Comment by Jegelewicz** [comment]
Can we please let @campmlc look at it?

**Comment by campmlc** [comment]
@Jegelewicz fix looks great, exactly what I need, thanks!

**Comment by dustymc** [comment]
I don't care how it **looks**, I care how it **works**. It does less now than it did before you "fixed it!"

@campmlc how are you reconciling "exactly what I need" with https://github.com/ArctosDB/arctos/issues/2518?

**Comment by Jegelewicz** [comment]
Alrighty then - I see now what is going on and I propose that stuff like this needs better documentation in the code since I was completely unaware of WHY this field was different from the exact same one in the create form.

However, @campmlc was still having the same issue apparently, so something else needs to happen. I will revert to the fix and let he review in test to see if this is doing what she wants.

**Comment by Jegelewicz** [comment]
@campmlc please see in test http://test.arctos.database.museum/Loan.cfm?Action=addItems

**Comment by Jegelewicz** [comment]
Hey @dustymc do you think we could make this slicker with [chosen](https://harvesthq.github.io/chosen/)?

Code is [here](https://github.com/harvesthq/chosen).

I've been messing around with it, but I don't have the chops to really understand how to make it work.

**Comment by dustymc** [comment]
<img width="112" alt="Screen Shot 2020-12-10 at 7 40 12 AM" src="https://user-images.githubusercontent.com/5720791/101793745-f98c9480-3aba-11eb-9b94-7ee9d28178d1.png">

**Comment by Jegelewicz** [comment]
OK, I'll keep looking....

**Comment by dustymc** [comment]
Installing libraries is expensive - they eat bandwidth (very expensive for some users), they require maintenance, they require replacement when they're inevitably deprecated, about 99% of them don't do what they're supposed to do on some device, they can conflict with other libraries, etc., etc., etc. Libraries are often the least-evil option anyway, but please carefully consider the alternatives before going there, and reuse (or replace) something that we're already dealing with if at all possible. (We're also deep into jquery - your choice would have looked pretty good, before it was abandoned....)

We do have a library that does weird things to select multiples, used in specimensearch in various places and probably elsewhere. I would prefer a straight select multiple - that thing is less functional than the current native object, mostly by taking over my keyboard when it's open - but it's a familiar evil.....

For this, I don't really understand the core problem so I'm not sure what an acceptable solution might look like. The "tiny" select worked fine on my phone and my kid's tiny chromebook, and I suspect I have more collections to sort through than anyone else. The current iteration works the same, but it's surrounded by acres of empty screen and I have to scroll down to do anything on the smaller devices.

**Comment by Jegelewicz** [comment]
I think I figured something out - just so the form won't look so funky.

**Comment by Jegelewicz** [comment]
Check it out - http://test.arctos.database.museum/fix/TJSandbox.cfm?action=addItems

**Comment by Jegelewicz** [comment]
Don't judge the whole thing yet - I'm still working on it....

**Comment by ewommack** [comment]
I like it. Seems to have a lot of fields that make sense.

**Comment by dustymc** [comment]
Functional, but the multi size (default) is what lead here - need to set size param - and I suggest show/hiding the "active" button.

**Comment by Jegelewicz** [comment]
>  I suggest show/hiding the "active" button.

Done

**Comment by campmlc** [comment]
Looks great from my phone!

**Comment by Jegelewicz** [comment]
Try it now!

**Comment by Jegelewicz** [comment]
@ewommack what do you think?

This form isn't "functional" because it is in my sandbox, but if you guys like how it looks - I'll try to port it over to the functioning form in test.

**Comment by campmlc** [comment]
Looks good to me - again, from my phone!

**Comment by Jegelewicz** [comment]
Just want to make sure you are seeing the test form: http://test.arctos.database.museum/fix/TJSandbox.cfm?action=addItems

**Comment by campmlc** [comment]
Yep

**Comment by Jegelewicz** [comment]
Closing because #3282

**Comment by ewommack** [comment]
Sorry the sun came out so I ran to the field for the afternoon.
I like the select multiple for the parts disposition. That will be fun to try and and make that search field more relatable for those loans where items come from multiple different sources.
