### ISSUE TITLE
One sided Other ID relationships

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3233]
Am I crazy, or don't we have some sort of report of one sided other ID relationships?

![image](https://user-images.githubusercontent.com/5725767/99855087-4546c080-2b43-11eb-9e4a-7248017bbf17.png)

and

![image](https://user-images.githubusercontent.com/5725767/99855111-52fc4600-2b43-11eb-945a-577443667806.png)

are an example.

I'd like to hunt all of these down and add the reciprocal. I thought this would get it for me, but there's nothing there.
![image](https://user-images.githubusercontent.com/5725767/99855193-7921e600-2b43-11eb-8d27-ab4da52de636.png)

**Comment by dustymc** [comment]
There's an email notification. It'll need redone when that bulkloader is redone.

**Comment by Jegelewicz** [comment]
DOH! I knew there was SOMETHING! Shall I leave this open as a reminder? If not necessary, please close.

**Comment by dustymc** [comment]
Yes leave it.

Blocked by https://github.com/ArctosDB/arctos/issues/2974

**Comment by dustymc** [comment]
The review period for https://github.com/ArctosDB/arctos/issues/2974 has passed and this can proceed.

This is blocking https://github.com/ArctosDB/arctos/issues/2292; we have to find another way of handling potential reciprocals before we can simplify the loader. I can figure that out so going next task, needs prioritized.

**Comment by campmlc** [comment]
I support prioritizing this if it can be done relatively easily and doesn't
affect critical items in the list.

**Comment by dustymc** [comment]
Next release will have a new email alert, a new tool to download unreciprocated relationships (which can then be loaded in the Identifiers/Relationships bulkloader, which is also new), and an entire new back-end to gather the data.

The report will filter for relationships which can be reciprocated. Attached is an **unfiltered** report using current production data. Code is in scripts/gatherUnFilteredReciprocalRelations in case anyone needs this in the future. The report contains essentially 4 things:

1. things which will be in the reciprocal report
1. things outside of Arctos ("MSB:Para:28906","USNM: National Museum of Natural History, Smithsonian Institution","602540","host of")
1. data entry problems which could be fixed ("MSB:Para:28497","MSB:Mamm","MSB:Mamm:152843","host of")
1. Ambiguous local references which could perhaps be disambiguated ("MSB:Para:29042","NK","275281","host of")

[temp_recip_oids_nofilter.csv.zip](https://github.com/ArctosDB/arctos/files/5777147/temp_recip_oids_nofilter.csv.zip)

Summary:

```
   g      | count 
-------------+-------
 ALMNH:ES    |     6
 ALMNH:Inv   |    17
 CHAS:Bird   |     2
 CHAS:EH     |     4
 CHAS:Herp   |   793
 CHAS:Mamm   |    16
 DGR:Mamm    |     2
 DMNS:Bird   |     4
 DMNS:Inv    |     3
 DMNS:Mamm   |   131
 DMNS:Para   |    19
 HWML:Para   |     9
 KNWR:Ento   |   325
 KNWR:Herb   |     4
 KNWR:Inv    |     1
 MSB:Bird    |   463
 MSB:Host    |   281
 MSB:Mamm    |  5034
 MSB:Para    |  1832
 MVZ:Bird    |    60
 MVZ:Egg     |    13
 MVZ:Mamm    |     2
 NMMNH:Bird  |     4
 NMMNH:Mamm  |     1
 NMMNH:Paleo |    22
 NMU:Mamm    |     8
 NMU:Para    |     8
 OWU:Fish    |     5
 UAM:Art     |    26
 UAM:EH      |    26
 UAM:Ento    |   246
 UAM:Inv     |     4
 UAM:Mamm    |   274
 USNPC:Para  |     6
 UTEP:Ento   |   147
 UTEP:Herp   |    10
 UWYMV:Egg   |     2
```
