### ISSUE TITLE
Need to modify table on bulkload parts tool?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3235]
@dustymc do we need to modify this?

![image](https://user-images.githubusercontent.com/5725767/99880504-f8a9c680-2bd0-11eb-8a5f-a0d8fcf98b7e.png)

Don't you just have to use GUID now? Or can you still use other numbers, just not the combination of GUID-Prefix and catalog number fields?

Want to make sure we are giving clear instructions...

**Comment by dustymc** [comment]
It'll take

* guid
* msb:mamm--nk---1234
* UUID - biguglything


I think the directions are correct, not so sure about clear.

**Comment by Jegelewicz** [comment]
Yeah, so you can't use

guid_prefix--"catalog number"--12345

although the instructions don't make that super clear. I'll think on this. Maybe we don't need to modify because I am the only crazy person who would try to use that combo?

**Comment by dustymc** [comment]
Correct - that "exception" is a pain to handle, confusing, and can easily be smooshed into guid in excel. (Which might make a good short tutorial??)

**Comment by Jegelewicz** [comment]
Yeah, I had to do the smooshing, which is super easy, just another step. OK, this is assigned to me.

**Comment by Jegelewicz** [comment]
To Do

  [ ] make sure documentation on the page is clear
  [ ] make a tutorial for smooshing guid prefix and catnum in excel

**Comment by Jegelewicz** [comment]
Nobody has complained about this - so I think it was just me? Closing
