### ISSUE TITLE
Color box needs to expand to include locality attributes

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3236]
![image](https://user-images.githubusercontent.com/5725767/99881381-b5525680-2bd6-11eb-870b-261aac5fb3b8.png)

**Comment by Jegelewicz** [comment]
@dustymc what information do you need here?

**Comment by dustymc** [comment]
Links are always useful, but I think I figured it out. That seems to just be your browser trying to deal with really squished pages - there's only so far as table can be collapsed, something weird happens with the right combination of very large font and very small windows and such. I don't think there's a realistic solution.
