### ISSUE TITLE
New agent role in publications - illustrator

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3237]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctauthor_role

**Value**
illustrator

**Definition**
Agent name of a person who illustrated a publication.

**Context**
Just entered a [book as a publication](https://arctos.database.museum/publication/10009671) and would like to credit the illustrator. This is also important for journal papers, where artists get far too little credit for their illustrations.

**Comment by Jegelewicz** [comment]
Do we also need photographer or can these two be combined somehow?

**Comment by dustymc** [comment]
Yes on at least one role, not sure on combining.

**Comment by Jegelewicz** [comment]
Code Table admins say add.

**Comment by dustymc** [comment]
PLEASE USE MILESTONES!!!

**Comment by Jegelewicz** [comment]
It's my task - so no milestone for you?

**Comment by Jegelewicz** [comment]
Code table addition made - still need to update publication after it is available.

**Comment by Jegelewicz** [comment]
@dustymc I am curious. The code table for [author_role](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctauthor_role) includes four options, yet I can only use author and editor when selecting roles for a publication. What gives?

![image](https://user-images.githubusercontent.com/5725767/105532065-870cf800-5ca7-11eb-9bc5-75a615cedf97.png)

**Comment by Jegelewicz** [comment]
Oh I see - this isn't using the code table!

```
<td>
						<select name="n_author_role#i#" id="n_author_role#i#">
							<option value="author">author</option>
							<option value="editor">editor</option>
						</select>
```

**Comment by Jegelewicz** [comment]
@dustymc I can get the edit pub form to use the ctauthor_role code table when adding new "authors", 

![image](https://user-images.githubusercontent.com/5725767/105778046-c302c000-5f28-11eb-89f4-d8e8b6154d56.png)

but once I add an illustrator or subject, they still appear as an "author" when I go back to editing. 

![image](https://user-images.githubusercontent.com/5725767/105778101-ddd53480-5f28-11eb-9499-35afd465211a.png)

I can spend half a day figuring out how to make the existing roles pull from the code table, but maybe you can do that quicker? Also, I am not 100% sure that the appropriate role is being saved to the publication in the first place....

**Comment by dustymc** [comment]
test is using the CT
