### ISSUE TITLE
Cloning record to different collection?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3238]
Is this possible? I want to use option1, clone all including parts, containers, loan history etc, but from DGR:Mamm to MSB:Mamm.

It would also be useful to be able to clone at least parts/container environment and part loan history from MSB:Mamm to MSB:Para.

**Comment by campmlc** [comment]
Here is the DGR Mamm record I need cloned:
https://arctos.database.museum/guid/DGR:Mamm:30783

**Comment by dustymc** [comment]
I don't think this is possible, and would introduce a significant security risk if it is (which is why it's definitely not possible in Oracle).

**Comment by dustymc** [comment]
It's possible that the 'clone to bulk' could use the associated loaders (if we can ever move decisively on https://github.com/ArctosDB/arctos/issues/2974) in addition to the main. That won't be comprehensive, but it might include everything you've mentioned.

**Comment by campmlc** [comment]
Any recommendations on how to solve the issue of tracking loan and part
history, then?
