### ISSUE TITLE
Code Table Request - Add R53W to TRS range code table

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#3240]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Goal**
Add value to locality attribute TRS range code table

**Context**
R53W is a valid TRS range, value needed to upload a new locality dataset

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=cttrs_range

**Value**
R53W

**Definition**
Range 53 West. A measure of the distance west from the referenced principal meridian, generally in units of six miles. https://en.wikipedia.org/wiki/Public_Land_Survey_System#Commonly_used_terms

**Comment by Jegelewicz** [comment]
Done

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks!
