### ISSUE TITLE
Code Table Request - Add Missourian to informal chronostratigraphy

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#3241]
**Goal**
Add Missourian to the informal chronostratigraphy code table.

**Context**
Missourian is a regional chronostratigraphy term for North America, used in many publications.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctchronostrat_informal

**Value**
Missourian (Stage/Age)

**Definition**
A North American subdivision of the Pennsylvanian. [https://en.wikipedia.org/wiki/Pennsylvanian_(geology)#Subdivisions](https://en.wikipedia.org/wiki/Pennsylvanian_(geology)#Subdivisions)

**Comment by Jegelewicz** [comment]
Done

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks!
