### ISSUE TITLE
how do I keep the date format in the CSV file?  I can't bulkload the accessions.

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/arctos#3242]
** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **

** Outages should be reported to the contacts listed at https://arctosdb.org/arctos-down/ **

** Arctos Documentation is http://handbook.arctosdb.org/ **

** Learn more about Arctos at https://arctosdb.org/ **

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **

**Comment by campmlc** [comment]
1) create your file as a xlxs file, use custom format yyyy-mm-dd - you may
need to create it.
2) When you are ready to create the csv, save as csv, but do not open it up
again in Excel, or Excel will reformat all your dates.
3) If you need to look at it, open it in a text editor.
4) If you need to make any edits, open the original xlsx file and make
edits there, then resave, and then resave again as a csv, replacing the old
one.
Isn't Excel fun!

**Comment by dustymc** [comment]
https://handbook.arctosdb.org/documentation/dates.html#excel-hates-me-help

**Comment by mbprondzinski** [comment]
I am well aware of all the above, and have tried using South African English to set the date format, but it still reverts back in some of the cells.  But that is currently the least of my problems!  I finally was able to upload the document, but every record has a problem, including "locality attributes" and the "agent names," which are all entered previously, some as "aka"s but does that matter or do they have to be entered as the "preferred name"?  I also got back some strange "Higher Geography" doesn't exist messages, except it does because I did a search and it's already in Arctos.  So I'm not sure what I need to do next...  Any help would be appreciated.  I have attached the file for perusal...except I had to save it as an excel workbook because github doesn't accept CSV.   
[bulkloader_stage.xlsx](https://github.com/ArctosDB/arctos/files/5617542/bulkloader_stage.xlsx)

**Comment by campmlc** [comment]
Try zipping the csv file and attaching it  here - that way we don't have to
reformat all your dates!

**Comment by mbprondzinski** [comment]
Oh, so that's how you keep the dates from changing!
[bulkloader_stage.zip](https://github.com/ArctosDB/arctos/files/5617789/bulkloader_stage.zip)

**Comment by dustymc** [comment]
All of the agent problems I can see are providing nothing (NULL) where something's required. https://handbook.arctosdb.org/documentation/bulkloader.html#fields

I checked a flagged geography, it's got extra spaces.

For the attribute I checked, Upper Cretaceous is mapped to Stage/Age. https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlocality_att_att

**Comment by Jegelewicz** [comment]
Here is the excel I have.
[Copy of IMLS upload.xlsx](https://github.com/ArctosDB/arctos/files/5618177/Copy.of.IMLS.upload.xlsx)

**Comment by mbprondzinski** [comment]
Okay, thanks, Teresa.  That will help me to make the additional changes.  Do the agent names have to be entered in the records as the "preferred name" or can they be an "aka"?  I got a number of names back that were supposedly not there.
Thanks!

**Comment by Jegelewicz** [comment]
aka should work UNLESS some other agent has the same name. Using preferred name is the safest bet.

**Comment by Jegelewicz** [comment]
@mbprondzinski by the way - all the files I have worked on for you or anybody else at ALMNH are in the dropbox which I just shared with you - I should have done that ages ago!

**Comment by dustymc** [comment]
https://handbook.arctosdb.org/documentation/bulkloader.html#agent-names

**Comment by mbprondzinski** [comment]
Hi Teresa,

Thanks for these files, but I am going to have you share them with the DMRC Dropbox as I have no room left in my personal dropbox.  I will have to get that information to you, but probably not until tomorrow.

Another question:  since half the taxonomy is out-dated, if I want to keep all the old synonymy, how do I do that?  Is there another field I should add?

Thanks!  (Today was supposed to be my day off…as usual, that went by the wayside!)

**Comment by Jegelewicz** [comment]
> since half the taxonomy is out-dated, if I want to keep all the old synonymy, how do I do that?  Is there another field I should add?

My advice would be to add the records with the original (outdated) identification, then bulk add new identifications with the current taxonomy.

**Comment by mbprondzinski** [comment]
Hi Teresa!

Here is our DMRC email:  uadmrc@gmail.com<mailto:uadmrc@gmail.com>

Send the files to me there.  Thanks!

MB

**Comment by Jegelewicz** [comment]
done!

**Comment by mbprondzinski** [comment]
Thank you!

**Comment by atrox10** [comment]
Just as an aside, I do all my bulkloaders in googlesheets and download them directly as CSVs from there. I never make them excel files, thus I don't have all the date formatting (and other) issues.
