### ISSUE TITLE
Can't get past the GUID_Prefix! 

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/arctos#3243]
[Bulkload IMLS Accessions.xlsx](https://github.com/ArctosDB/arctos/files/5599377/Bulkload.IMLS.Accessions.xlsx
![image](https://user-images.githubusercontent.com/43214224/100284055-2d50b180-2f34-11eb-94be-b0dccda8dfc4.png)

**Comment by ewommack** [comment]
I think the error says you are missing something in that column, but it looks like from your file you have AMLNH:Paleo. I checked the [portal page](https://arctos.database.museum/home.cfm) and it doesn't look like that collection is up yet. Maybe Arctos can't recognize it?

**Comment by Jegelewicz** [comment]
There was a weird space in one of the other ID's causing everything to shift.

Try this
[IMLS bulkload.zip](https://github.com/ArctosDB/arctos/files/5599397/IMLS.bulkload.zip)

**Comment by Jegelewicz** [comment]
HAHAHA Oh wait - you are doing accessions!

You need to enter them as ALMNH:ES - the change to ALMNH:Paleo has not been made yet.

**Comment by Jegelewicz** [comment]
Also, there are a bunch of blank lines at the bottom of your file.

**Comment by mbprondzinski** [comment]
OMG!  I know!  Yes, I can't even get past the ACCESSIONS!  I tried Paleo to see if that would work, but ES doesn't work either.  The actual CSV file has ALMNH:ES.  Those blank lines aren't in the CSV file.

**Comment by mbprondzinski** [comment]
I fixed it.  I had to copy and paste it into another worksheet, then save it.  Thank you all!
