### ISSUE TITLE
Public search for a locality fails

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3244]
While not logged in, I attempted this search:
![image](https://user-images.githubusercontent.com/5725767/100357247-a6421e80-2fb1-11eb-8c8b-4699fb67c207.png)

I first encountered an error, that I failed to record that included a box with something like "allow Arctos pop-ups". After checking it, I tried again. The results look like this:

![image](https://user-images.githubusercontent.com/5725767/100357183-90ccf480-2fb1-11eb-8c1b-f468304011de.png)

The page continues to say "Processing" at the bottom, even after I close the pop-up.

When logged in, the search performs perfectly.

**Comment by dustymc** [comment]
Duplicate of https://github.com/ArctosDB/arctos/issues/3155 - sessions don't always "take" for some reason, I don't think I have any real chance of fixing it until I can replicate environments. I'll try to remember to reboot (which may or may not do anything) some late night if I think of it, or we could schedule a bounce.

**Comment by Jegelewicz** [comment]
CLosing as dupe
