### ISSUE TITLE
Suggested Changes to Taxonomy Search Page

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3245]
We're up to 10 documents: https://drive.google.com/drive/folders/1gQdI-qWCDFAe6yJSkWkUKlXLAX5KYwLp?ths=true

_Originally posted by @sharpphyl in https://github.com/ArctosDB/arctos/issues/2695#issuecomment-676623830_

This issue will focus on this: https://drive.google.com/file/d/1Egj161LQDJaXsINA3IxNJoPmqcbnXc5i/view?usp=sharing

**Comment by Jegelewicz** [comment]
From Document re Code Table:

> Current Code Table (a few typos need work).
> 
> Documentation for code table taxon_name_type ~ [ table list ]
> 
> TAXON_NAME_TYPE | Documentation
> -- | --
> cultural | Name is intended for use in a cultural taxonomy source, such as Nomenclature for Museum Cataloging.
> Linnean | Name is controlled under a Linnean Code, such as ICZN, ICBN, or ICTV.
> mineral | Name is intended for use under a mineral taxonomy source.
> quarantine | "Name" is not intended for cataloging, but has historical significance. This is primarily intended for misspellings propagated through publication, which are useful in locating catalog records. All quarantine terms should have relationships to terms which are **avaialble** for cataloging. No name which can be associated with type material, regardless of current "acceptedness," should be quarantined.
> 
> Suggestions for Table Modification
> 
> Note:  Can we rename it Taxonomy Type instead of Taxon Name Type or is it too late?  Teresa, is there a source for minerals we can list?
> 
> Taxonomy | TypeDescription
> --- | --- 
> cultural | Names used to describe cultural items.  They come from a cultural taxonomy source such as Nomenclature for Museum Cataloging.
> Linnaean | Names used to describe biological items.  They are controlled under a Linnaean Code such as ICZN, ICBN or ICTV.
> mineral | Names used to describe minerals and chemical compounds.  They come from a variety of sources.
> quarantine | Names that have been misspelled (or a similar error) in publications that should not be used for identifications but are retained for search capability.  They must be linked to a synonym.
> 
> Note:  There seems to be no agreement on how Linnaean is spelled.  I’m taking this spelling from https://en.wikipedia.org/wiki/Linnaean_taxonomy

**Comment by Jegelewicz** [comment]
> Can we rename it Taxonomy Type instead of Taxon Name Type or is it too late? Teresa, is there a source for minerals we can list?

That ship has sailed and anyway, these terms are being applied to individual names, so I think "taxon name type" is appropriate.

**Comment by Jegelewicz** [comment]
> There seems to be no agreement on how Linnaean is spelled. I’m taking this spelling from https://en.wikipedia.org/wiki/Linnaean_taxonomy

We have been using Linnean since the beginning? I don't really see a need to change it, but if anyone feels very strongly about it, I suggest that it get its own code table issue.

**Comment by Jegelewicz** [comment]
From the document:

> Current Taxonomy Search Results:
> 
> ![image](https://user-images.githubusercontent.com/5725767/100361156-0b4c4300-2fb7-11eb-938f-44abab32df17.png)
> 
> We need to update two of these Search terms and add Taxonomy Type.
> 
> Scientific_name should be Name
> Taxa term should be Term Value

**Comment by Jegelewicz** [comment]
> Scientific_name should be Name

I think it should be Taxon Name to be consistent with the search terms.
![image](https://user-images.githubusercontent.com/5725767/100361897-f7eda780-2fb7-11eb-82d1-43c44c4342c0.png)

**Comment by Jegelewicz** [comment]
https://github.com/ArctosDB/arctos/issues/3245#issuecomment-734326047

Should be true for all results.

**Comment by Jegelewicz** [comment]
Changed results table to be consistent with search terms. Also, fixed CONTAINS results:

From this
![image](https://user-images.githubusercontent.com/5725767/100367933-296a7100-2fc0-11eb-86f9-af1d76808eea.png)
 to this:
![image](https://user-images.githubusercontent.com/5725767/100367985-40a95e80-2fc0-11eb-886a-97adab0dc9c6.png)

**Comment by Jegelewicz** [comment]
@sharpphyl here is a comparison for you!

>**From the suggestions document:**
> ![image](https://user-images.githubusercontent.com/5725767/100361156-0b4c4300-2fb7-11eb-938f-44abab32df17.png)

**In Test now:**
![image](https://user-images.githubusercontent.com/5725767/100368757-350a6780-2fc1-11eb-8de9-975e327cfdc3.png)

**Comment by Jegelewicz** [comment]
From Document:

> Note: Continue to highlight the definition on the right when the cursor is entered into a field on the left.  That’s really helpful!
> 
> Search TaxonomyTaxonomy Search Tutorial
> Taxonomy Documentation
> In Arctos, Taxonomy is any classification system of things or concepts.  The items may be biological, mineral, cultural or other types as proposed by Arctos users. 
> The default for search is STARTS WITH and is case-insensitive.  Search on any combination of one or multiple fields.
>

**Comment by Jegelewicz** [comment]
OK @sharpphyl how is this? http://test.arctos.database.museum/taxonomy.cfm

**Comment by sharpphyl** [comment]
Huge improvement.  We will need to replace the Search Taxonomy Tutorial so it shows the new format and update the Taxonomy documentation.   Maybe you can tell me when to do it since it should probably be after this is out of test.

A typo - should be plural "terms"

<img width="605" alt="Screen Shot 2020-11-27 at 9 15 09 AM" src="https://user-images.githubusercontent.com/15368365/100468140-0e1b6680-3091-11eb-9f37-757d974fd0ae.png">

On this table, can we add the word "LOCAL" to SOURCE since that's what it links to?

<img width="580" alt="Screen Shot 2020-11-27 at 9 06 46 AM" src="https://user-images.githubusercontent.com/15368365/100468183-24292700-3091-11eb-9cfe-729cb4ec5cec.png">

I didn't notice this before, but perhaps our example of **Taxon Term** could be an author's name (such as Linnaeus or Melvil or someone prominent in mammals or birds) rather than "name authors."  We use some words (especially "name") in so many ways that examples are helpful.

<img width="557" alt="Screen Shot 2020-11-27 at 9 28 46 AM" src="https://user-images.githubusercontent.com/15368365/100469341-415ef500-3093-11eb-816f-673c4f25011f.png">

This is trivial, but it's actually "author_text"

<img width="239" alt="Screen Shot 2020-11-27 at 9 48 24 AM" src="https://user-images.githubusercontent.com/15368365/100470586-c3501d80-3095-11eb-9d86-dbee3606237d.png">

I hope you didn't spend all of Thanksgiving on this!

**Comment by Jegelewicz** [comment]
> A typo - should be plural "terms"

fixed

> On this table, can we add the word "LOCAL" to SOURCE since that's what it links to?

That's on another page - can you start a new issue? I want to make sure that will be OK with Dusty - code table stuff might get used in ways that are not immediately apparent, so I don't want to change anything that could cause problems.

> I didn't notice this before, but perhaps our example of Taxon Term could be an author's name (such as Linnaeus or Melvil or someone prominent in mammals or birds) rather than "name authors." We use some words (especially "name") in so many ways that examples are helpful.

See clarification.

> This is trivial, but it's actually "author_text"

changed

> I hope you didn't spend all of Thanksgiving on this!

Nope - I also helped Alabama out with a bulkload file :-)

**Comment by Jegelewicz** [comment]
> We will need to replace the Search Taxonomy Tutorial so it shows the new format and update the Taxonomy documentation. Maybe you can tell me when to do it since it should probably be after this is out of test.

As soon as this makes it to production, I'll assign this to you!

**Comment by sharpphyl** [comment]
> Jegelewicz added a commit to ArctosDB/PG that referenced this issue 17 hours ago 

So that's how it's done!  Everything sounds good.

**Comment by Jegelewicz** [comment]
These changes are in production! Now we need to update documentation.
