### ISSUE TITLE
Clarify that code table CTTAXONOMY_SOURCE refers to LOCAL sources

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#3247]
The Taxonomy Search Page links LOCAL source to
http://test.arctos.database.museum/info/ctDocumentation.cfm?table=CTTAXONOMY_SOURCE

<img width="889" alt="Screen Shot 2020-11-28 at 8 29 34 AM" src="https://user-images.githubusercontent.com/15368365/100519234-e9d48e00-3153-11eb-8fd2-3e91e9d454fe.png">

This table only lists LOCAL sources that are used for classifications within a collection, but the heading just says SOURCE.  

<img width="618" alt="Screen Shot 2020-11-28 at 8 41 12 AM" src="https://user-images.githubusercontent.com/15368365/100519504-82b7d900-3155-11eb-9e12-fdb7ba0ce25c.png">

The table name CTTAXONOMY_SOURCE is fine but could the heading be LOCAL SOURCE instead of SOURCE to match the term it links to?

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/3311

**Comment by sharpphyl** [comment]
#3311 changes everything so I'll close this as long as we're moving forward with that approach.
