### ISSUE TITLE
Relationships queries not working in catalog record

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3248]
The relationships links in catalog record display do not appear to be working. For the record below, the find all link returns only the parasite of related record. Find collected with and Find parasite of separate links return no records.

https://arctos.database.museum/guid/MSB:Para:30172

Relationships [ expand ] [ Find All ] [ Find collected with ] [ Find parasite of ]Edit
(collected with) MSB:Para:30171
(collected with) MSB:Para:30174
(collected with) MSB:Para:30173
(parasite of) MSB:Mamm:151015

**Comment by dustymc** [comment]
The current code uses reciprocal relationships, which don't exist for that example. Should work without those in next release.

**Comment by campmlc** [comment]
Thanks, that will be helpful for making the unidirectional relationships
discoverable.
