### ISSUE TITLE
cleaning up locality-geography mismatches 

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#3249]
It would be helpful to have a report or annotation feature for mismatches between specific locality/coordinates and higher geography, to help with data cleanup. 

Example: I'm working on an accession of birds from New Mexico, and am trying to pick existing localities with coordinates as much as possible. In doing so, I'm coming across localities that are in multiple counties (one correct, others incorrect). Ojo Caliente, for example, is in Arctos in five counties. Taos County is correct. If you click to edit the other localities, it shows that there are problems with the higher geography ("If you're seeing this, users are failing to find your specimens!"). I mapped coordinates for one and they fall in Taos County but the higher geography is given as Rio Arriba County.

Could we add a report (under Find Low Quality Data?) or an annotation feature to locality that would notify data quality contacts for those collections that share that locality?

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/2059

I don't have the tools to preemptively find everything, but that eventually catches most of these, probably. You can find those in various places, including...

<img width="437" alt="Screen Shot 2020-11-30 at 11 47 33 AM" src="https://user-images.githubusercontent.com/5720791/100656705-f26ac700-3301-11eb-8f3d-c09f1fce91e6.png">


>1307 unreviewed annotations refer to MVZ:Bird specimens.

"If you're seeing this, users are failing to find your specimens!" is a direct consequence of not having a standardized geography-locality relationship. Creating the situation that leads to those warnings should not be possible, which probably isn't possible under a "curator says so" geography model.

**Comment by dustymc** [comment]
Suggest: Do whatever's necessary - better archives, more stuff in archives, WHATEVER - to make collections comfortable with others editing shared localities. Then just edit, don't try to split and edit "yours" etc. - better share expertise.

**Comment by dustymc** [comment]
Annotations UI: allow "splitting groups" to eg only see {collection} records.

**Comment by dustymc** [comment]
Do better with annotation emails
