### ISSUE TITLE
Feature Request - Open Accession in new tab?

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#3250]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I do a search for accessions (and loans for that matter - all transactions I guess), receive a list of relevant results, then open (edit) the accession record (which opens in the same window/tab). Once I finish editing that particular accession record, I often want to go back to the search results (like when searching for catalog records) only to remember that I've lost the results of my search and have to go back and re-do it.

**Describe what you're trying to accomplish** 
Open accession record in new tab rather than in same window so I can go back to the results of my search and continue my editing or reviewing my search results without always having to remember to right-click on the accession link (or "edit loan") to open in a new tab.

**Describe the solution you'd like**
Change target of hyperlinked accession number to open in new tab.

**Describe alternatives you've considered**
Right-click on accession number / edit loan to open in new tab. It works but I often (always) forget.

**Priority**
Normal. No rush but would be a nice way to reduce frustrations... 🥇

**Comment by dustymc** [comment]
This is another place where we could use a big-picture discussion. What happens now is pretty much random, and there's no indication of what's going to happen. We do have a style for external links, which always (allegedly!) open in a new tab, but internal - who knows.

I tend to dislike new tabs - my mouse provides that, but I can't easily override it if its baked in to the UI.

Is there something consistent that makes everyone happy, or some way of marking the inconsistencies, or ????????????

I'll change these when I can - a tiny bit more randomness isn't going to hurt anything! - but SOME way of being predictable would be a very good thing.

**Comment by dustymc** [comment]
OK, we have a mechanism (and it's scattered around transactions).

Links of class ``newWinLocal`` should all open in a new tab.

``newWinLocal`` is defined in the css, but as of now has no attributes - if anyone wants to make some styling I can add it to the CSS.

@Jegelewicz I updated https://handbook.arctosdb.org/how_to/developer-guide.html - the ``external`` URLs just got a bit simpler and more predictable.

**Comment by Jegelewicz** [comment]
> is defined in the css

Where is "the css"?

**Comment by Jegelewicz** [comment]
OK - found it.

**Comment by Jegelewicz** [comment]
Not sure what makes sense as a style. Different text color? Something else?

**Comment by dustymc** [comment]
Consistent colors for URLs are nice; I don't recommend messing with that. Maybe some image-widget like ``external`` but I can't come up with anything very clever....

**Comment by Jegelewicz** [comment]
yeah and the Google doesn't come up with anything clever either!

**Comment by Jegelewicz** [comment]
I'm not sure it is really necessary. I know how you feel about new tabs, but I think for most users a new tab for any internal link is useful. At some point, maybe this could be a setting in the user profile? Internal links can all open in the same tab or in new tabs depending on your preference.....

**Comment by dustymc** [comment]
I'm more interested in consistency - I'm not sure I care what's going to happen, but I'd (sorta, sometimes) like some indication. We've got the framework to do that now, if I can remember to use it, so I'm absolutely fine with leaving this as it is until someone with better ideas comes along.

Pushing this off to JS definitely opens up more possibilities (or breaks the internet by abusing JS to override standard HTML functionality, depending on your personal belief system...) - it would be pretty trivial to wrap that little bit of JS link-mangler code in a "if user says..." statement.
