### ISSUE TITLE
[CONTACT] Need help making UAM:Art collection public

### ISSUE THREAD

**Issue by marecaguthrie** [ArctosDB/arctos#3251]
Hi @dustymc-
Could you help us complete the process to make the UAM:Art collection public? I think we have lifted the encumbrances from the masked records and we should have 4,319 catalog records.  But something weird is happening. When I'm logged in to Arctos I only have access to 2,308 records. The collection is also still "invisible" in Arctos. Can you help get it listed as a collection that can be searched?
Thank you!

**Comment by dustymc** [comment]
@lkvoong will set the flag, then it'll take some time to rebuild.

**Comment by lkvoong** [comment]
I've flipped the switch to make it a public portal.  It's not yet showing
up in the list of collections in the search page (may take a day or so due
to caching), but it is showing up in the portals page.

**Comment by dustymc** [comment]
I think everything's cleared - @marecaguthrie please confirm and close if it's happy.

**Comment by marecaguthrie** [comment]
Woooo! Thank you!
