### ISSUE TITLE
I keep getting this error message which I don't understand

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/arctos#3253]
![image](https://user-images.githubusercontent.com/43214224/100773615-bea5a500-33c6-11eb-8606-514cc897e823.png)

**Comment by Jegelewicz** [comment]
There is a non-printing character in one of the otherIDs - one of them has a space at the end. I remember this from looking at the file a while back...

Search for a space in that column.

**Comment by mbprondzinski** [comment]
Interesting… I changed the “other_id_num_type” to 5, and it keeps sending it back as 1 (!)  Also, I couldn’t find any spaces in either other id column.  I have loaded this file about 7 times, and the bulkload error file has come back with other people’s records a couple of times, even though I have deleted my files and made sure there was nothing in the staging platform!

**Comment by ewommack** [comment]
I've had the space appear between columns sometimes when excel does funny things with column placement. I had to open the file in a text editor to see it.
