### ISSUE TITLE
New Error on Bulkloading

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/arctos#3254]
![image](https://user-images.githubusercontent.com/43214224/100776158-d16da900-33c9-11eb-99be-c75cc0f232ff.png)

**Comment by Jegelewicz** [comment]
Can you send the file?

**Comment by mbprondzinski** [comment]
Okay, I will look for a space.  Stay tuned…

**Comment by mbprondzinski** [comment]
Okay, I am attaching the xlsx file here.

**Comment by Jegelewicz** [comment]
@mbprondzinski there isn't a file attached.

**Comment by mbprondzinski** [comment]
[Arctos IMLS.upload.xlsx](https://github.com/ArctosDB/arctos/files/5624683/Arctos.IMLS.upload.xlsx)

**Comment by Jegelewicz** [comment]
there is a hard return in the other ID for catnum 10638

**Comment by campmlc** [comment]
Just curious what the best tool is for screening for such errors?

**Comment by mbprondzinski** [comment]
Me too!  How did you find it???

**Comment by Jegelewicz** [comment]
I opened the csv in Notepad and scrolled down. The crazy space in there gives it away.

![image](https://user-images.githubusercontent.com/5725767/100785736-51960d80-33ce-11eb-9dcc-fbef03aedee7.png)

**Comment by mbprondzinski** [comment]
Well gol darn!  Thanks!  I've made it to the Bulkloader!!!!!

**Comment by dustymc** [comment]
Not sure about the current version, but older copies of notepad are not UTF compliant - it's fine for viewing, but saving can introduce a whole horde of new and interesting errors.

The built-in checker should be able to find and fix these errors.

**Comment by Jegelewicz** [comment]
>  but saving can introduce a whole horde of new and interesting errors.

Yep - so I only use it to troubleshoot. Once I have found the problem, I return to Excel and fix it there!

**Comment by ewommack** [comment]
For those us with Macs I loved TextEdit, and I'm learning about BBEdit now. I do a lot of my .csv editing in there, and it seems to save well.

**Comment by mbprondzinski** [comment]
So I looked at the records and "loaded" them?  There were a bunch of other options, like downloading, SQL, deleting....  Now they are "processing" but what am I supposed to do in the meantime?  Logout?  go back to square one?  There is nothing to tell me what to do next...if anything.  Do I delete them eventually from the bulkloader????

**Comment by Jegelewicz** [comment]
There are 44 records that did not load. You can see these by following this from the main menu: Enter Data > Bulkloader > Browse and Edit. Once there, in the "entered by" column, select your login ID and then click the "filter" button.

You can edit directly in the form - it is clunky, but you can do it - or you can download the records, delete them from the bulkloader and work on them in Excel, then re-load them in the same way you did the first batch.

For this few, I would probably just edit them in the bulkloader.

These are all taxon names that aren't in Arctos. If these are the "old names" you spoke of at some point during this, the question is - are these published names that have just been superseded, or are they misspellings or something that has never actually existed as a valid name?

**Comment by Jegelewicz** [comment]
BTW - anything that passes all the data checks loads and is automatically deleted from the bulkloader.

**Comment by mbprondzinski** [comment]
Those are all the names that are either misspelled or I would presume published long ago.  I’m pretty sure Adiel checked them.  I looked up a couple of the ones that had unsure spelling and couldn’t find anything close but I uploaded them as they were.

So what do I do next?  Or maybe I should have Adiel do it?!

**Comment by mbprondzinski** [comment]
Yeah, I found the records already in Arctos, but had a hell of a time searching for them because I forgot I called the other ID, “original identifier.”  Too confusing to remember…

**Comment by mbprondzinski** [comment]
I thought the taxonomy would all upload, but then I would fix it once it was in Arctos, since we want to save the original taxonomy even if its wrong.

**Comment by Jegelewicz** [comment]
> I thought the taxonomy would all upload, but then I would fix it once it was in Arctos, since we want to save the original taxonomy even if its wrong.

The names have to be in Arctos for them to load. There are plenty of "wrong" names in Arctos, but we would prefer not to keep adding to the problems of taxonomy in the world. However, these don't look like they are all problems...

Take the first one - Astarte isosceles

GBIF says it is an accepted name - https://www.gbif.org/en/species/9120094

I added the name and the classification in Arctos. If you change the status for that one to NULL, it should load.

It seems like someone needs to check each of these to determine the best way to handle them. @aklompma seems like the obvious choice....

**Comment by Jegelewicz** [comment]
And FWIW - here are the options:

If the name is valid - add it to Arctos like I just did.

If the name has been superceded (it is a synonym), then enter the old name in Arctos, but make sure you give it the relationship of "synonym of" to the currently accepted name AND put the currently accepted name in the "preferred name" term in the Arctos classification metadata

If the name is a complete misspelling or something that never existed as a taxon name in the literature, use the A {string} formula and for the "A" part, use the closest name in the tree you can (like the genus if it is a valid one or perhaps the Family if the genus is misspelled).

If you don't know what to do with one of them, post it here and we can discuss it!
