### ISSUE TITLE
Issue with queries returning no results

### ISSUE THREAD

**Issue by ediep6** [ArctosDB/arctos#3255]
I am having an issue with Arctos not showing specimen results.

I am able to search for an agent, and see that they have specimens in the database,
![image](https://user-images.githubusercontent.com/68963861/100780133-9b7af580-33c6-11eb-9c1d-54bdcacbeeb8.png)

but when I click to "open specimen results" there are no results.
![image](https://user-images.githubusercontent.com/68963861/100780244-b9e0f100-33c6-11eb-9233-a1f02c381a3d.png)

I need to see the specimens to do my job, please help! Thank you!

**Comment by dustymc** [comment]
<img width="520" alt="Screen Shot 2020-12-01 at 10 29 19 AM" src="https://user-images.githubusercontent.com/5720791/100781621-1a206480-33c0-11eb-9e33-ce4d5bb3bc9a.png">

You can ask the manager of that collection for access, or you may be able to access the records as a public user.

**Comment by AJLinn** [comment]
This happens to me all the time - I just log on using a different browser as a public user and do a search for that person in the catalog record search. You'll be able to see everything from there.
