### ISSUE TITLE
Increase thumbnail size limit to 150kb?

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#3256]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
Related to #2436

I'm working on an imaging project with Texas and Oklahoma TCN project to image our plant specimens and uploading through that project's TACC storage (and linking media from them). The thumbnails they're producing are about 100-150kb in size. I've already asked them to reduce the size to 50 kb, but they are asking how easy it would be to increase the thumbnail size limit. 

see email below:
Hi, Vicky,

    Thanks for the thorough explanation; yes, I understand what is going on. Quick question, though: how hard would it be to raise Arctos's thumbnail limit to 150 kB? In this day and age, 50 or 100 kB is really a pittance to download. I have forwarded your email below to Jason, so we will discuss, as well.

    Thanks,

    Diego

**Describe what you're trying to accomplish** 
increase thumbnail size limit for external images. 

**Describe the solution you'd like**
How might we accomplish your goals?
increase the size limit or tell TORCH no and figure something else out.

**Describe alternatives you've considered**
Telling TORCH to reduce the sizes of the thumbnails they produce to 50kb
leave all of our thumbnails as default :(
Regenerate thumbnails specifically for Arctos :(

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
Emphatic "NO!" vote from me! 

It's no technical problem to change the limitation, but it's easy to scroll through thousands of thumbs in Arctos and it's EVIL to feed users (especially those of us with bandwidth caps) megabytes of unnecessary data. 

50K is still about an order of magnitude more data than is necessary to make a nice thumbnail.

If the media are images, you can just leave the preview blank and Arctos will make thumbs. If it's not something Arctos can magic thumbs for we can look at services that will. 

(I see the grant funded label - maybe we can use that to explore image service options?)

**Comment by dustymc** [comment]
See https://github.com/ArctosDB/arctos/issues/2418 for another problem caused by excessively large thumbs.

**Comment by mvzhuang** [comment]
Thanks Dusty. I'll try to emphasize that a little more. I figured and sort of tried to tell them that...but yea. I might have to ask you to help me get rid of the preview thumbnail uris that are on there already later. How often does Arctos magic thumbs?

**Comment by mvzhuang** [comment]
I have some project images from a few months ago where the thumbnails haven't magicked in yet.
See: https://arctos.database.museum/project/10002989

**Comment by dustymc** [comment]
Sure, I can nuke previews. The thumb-thing should run constantly; I'll see what I can do about that those.

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/3257 - those should be getting thumbs now

**Comment by dustymc** [comment]
Look at those beautiful 2KB thumbs! Thumb creation claims to be all caught up, the cause should be gone by next release.

**Comment by mvzhuang** [comment]
agreed! OK here's the file of previews associated with the upload you can get rid of!
[BulkMediaBack (1).zip](https://github.com/ArctosDB/arctos/files/5638215/BulkMediaBack.1.zip)

**Comment by dustymc** [comment]
Running
```
create table temp_media_dethumb as select * from  temp_cache.temp_dlm_uptbl ;

alter table temp_media_dethumb add mid bigint;


select loaded_media_id from temp_media_dethumb order by loaded_media_id;


delete from temp_media_dethumb where loaded_media_id='http://arctos.database.museum/media/';

update temp_media_dethumb set mid=replace(loaded_media_id,'http://arctos.database.museum/media/','')::bigint;

select mid from temp_media_dethumb where not exists (select media_id from media where media.media_id=temp_media_dethumb.mid);

select preview_uri from media where media_id in (select mid from temp_media_dethumb);

create table temp_cache.media_20201203 as select * from media;
SELECT 801823


update media set preview_uri=null where media_id in (select mid from temp_media_dethumb);

UPDATE 1078
```

**Comment by mvzhuang** [comment]
cool all done! Thanks again Dusty!!
