### ISSUE TITLE
Change all UI references in "Scientific Name Check" Tool to Taxon Name

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3258]
Definitely better but can we change the heading on the csv to be "taxon_name" instead of "scientific_name" since everything else is shifting that way?  It appears we're changing the name of the tool to be **Taxon Name Check** (or Checker?) so it's parallel to the next service in the menu - **Taxon Name Validator** so can't we make the column headings the same for both reports?  The **Taxon Name Validator** uses the heading "taxon_name."

<img width="451" alt="Screen Shot 2020-11-27 at 10 23 50 AM" src="https://user-images.githubusercontent.com/15368365/100473161-f47f1c80-309a-11eb-9a78-444463984867.png">

Since there's only one column required, do we need the down arrow explanation?  To me, it's just clutter.

<img width="444" alt="Screen Shot 2020-11-27 at 10 29 59 AM" src="https://user-images.githubusercontent.com/15368365/100473425-9272e700-309b-11eb-9705-57ae09a2d781.png">

Similarly, the output should be "taxon_name" as well.

<img width="421" alt="Screen Shot 2020-11-27 at 10 30 57 AM" src="https://user-images.githubusercontent.com/15368365/100473545-dd8cfa00-309b-11eb-95b5-e1ee6dad6d03.png">

Looks like the documentation link may need some work later too.  

It's easier to decode if it says "click "Upload this file" although that's pretty obvious.

<img width="734" alt="Screen Shot 2020-11-27 at 10 44 48 AM" src="https://user-images.githubusercontent.com/15368365/100474349-a0c20280-309d-11eb-9f45-b398b0e34d99.png">

_Originally posted by @sharpphyl in https://github.com/ArctosDB/arctos/issues/2253#issuecomment-734935934_

**Comment by Jegelewicz** [comment]
See also https://github.com/ArctosDB/arctos/issues/2253#issuecomment-731371459

and https://github.com/ArctosDB/arctos/issues/2253#issuecomment-731381909

**Comment by dustymc** [comment]
Is the interest in that one tool or global?

**Comment by Jegelewicz** [comment]
I am only suggesting for this tool, but others may have a different take....

**Comment by campmlc** [comment]
Given the diversity of our collections, global seems reasonable. . .

**Comment by dustymc** [comment]
For just that tool, this seems lowest possible priority to me - you're going to have to change a header somewhere in the normal workflow, which very few people have ever used, and I can't see how it's anything other than entirely arbitrary where that happens. It also wouldn't be overly difficult.

Globally, there's 

* taxon_name.scientific_name (and a couple dozen related tables) are "taxa," and
* identification.scientific_name (and related) are "IDs" which may or may not use or refer to "taxa"

Those get used interchangeably (it's a long story, we ran out of electrons), sorting them out does seem moderately useful.

**Comment by Jegelewicz** [comment]
> Globally, there's
> 
>     taxon_name.scientific_name (and a couple dozen related tables) are "taxa," and
>     identification.scientific_name (and related) are "IDs" which may or may not use or refer to "taxa"

In general, users don't see that - correct? If so, I am not so concerned with it.

**Comment by Jegelewicz** [comment]
All I want to do here is:

- Change the name of the tool to Taxon Name Checker in the menu
- Have the tool accept a file with the column header "taxon_name"
- Have the tool return a file with the column headers: taxon_name, status, suggested_taxon_name, genus, species, inf_rank, subspecies

I think I can make those changes (if you trust me to try).

**Comment by dustymc** [comment]
Changing the structure of the CSV means changing structure of tables, which requires high-level DBA access.

What's now Arctos exists in part due to a bad experience with a middleware client, and from that (and everything since!) Arctos tends to be as "thin" as it possibly can be. Users, particularly Operators, do see table and column names. (I'm not arguing that we should change or prioritize anything, just trying to illuminate some architectural considerations.)

**Comment by Jegelewicz** [comment]
- Have the tool accept a file with the column header "taxon_name"
- Have the tool return a file with the column headers: taxon_name, status, suggested_taxon_name, genus, species, inf_rank, subspecies

Still a goal.

**Comment by Jegelewicz** [comment]
@ArctosDB/taxonomy says bring to working group for prioritization with de-specimening and UI consistency.

**Comment by dustymc** [comment]
Tool is https://arctos.database.museum/DataServices/SciNameCheck.cfm

probably needs converted to component loader?

**Comment by Jegelewicz** [comment]
> probably needs converted to component loader?

YES!
