### ISSUE TITLE
data service request: Download the container types from a list of barcodes

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3261]
I need to be able to use the Bulk Edit Container tool to add labels to 1,000 cryovials, some of which have not been scanned into positions because they are part of a legacy accession of zoo material given to us in non-standard boxes that must be replaced. Consequently, while all vials are barcoded, some of the vials are container type "cryovial label", while others that have been scanned are container type = "cryovial". The Bulk Edit Container tool requires we know a priori the existing container type, but if I search on the barcode list, I cannot download the barcodes and their container types  - Flatten Part Location does not work since these samples are not yet cataloged. 
Either I need a way to download the container types from a list of barcodes (this would be a useful feature for many reasons), or I need the requirement to specify existing container type for Bulk Edit Container to be waived (e.g. no matter what the existing container, please convert to cryovial), or I need @dustymc to magic these labels to these barcodes and convert all to cryovials. 
Here is the file:
[Zoo Accession Label Upload 12-2-20.zip](https://github.com/ArctosDB/arctos/files/5634363/Zoo.Accession.Label.Upload.12-2-20.zip)

Priority High - collaborative research pending outcome

**Comment by campmlc** [comment]
I was able to find  workaround for this by uploading the file to Bulk Edit Container with all container types = cryovial, then copying the results from my browser into a spreadsheet to isolate the non-cryovial containers, then reupload a new file converting those to cryovials, then re-uploading the orginal file to change the labels. To make this process easier, could we get a csv download function for the Bulk Edit Container error output? 
Even easier would be to make the original container type not required, as originally suggested. We could then review the validation results as we are required to do anyway before accepting for load, and see if there are any unusual original container types. 
Another issue is that the "Make changes and delete local data" process timed out both times with a 505 error after about 15 minutes.  After the second round, it appears the changes I submitted were made - but it shouldn't take so long and I should get a success message, I would hope.

**Comment by dustymc** [comment]
That form could be rolled into https://github.com/ArctosDB/arctos/issues/2974, which comes with downloadable errors.

Requiring container type was added in response to a huge mess made by that form. There's no technical reason to require it, but it's almost certainly prevented problems.

"Download the container types from a list of barcodes" would not be a difficult data service to build.

**Comment by campmlc** [comment]
Oh, yes please to both!

**Comment by dustymc** [comment]
next release has a new tool in data services
