### ISSUE TITLE
Suggested Changes to Taxon Details Page

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3263]
From https://github.com/ArctosDB/arctos/issues/2695#issuecomment-676623830

See https://docs.google.com/document/d/1kKu4MvR2NlvavoyQ3Ga4f_wWHDgiSMoC/edit

and https://docs.google.com/document/d/1ZvnPbrk2YsCQ8gDMx9B6ISIyUY0f0VJ5/edit

**Comment by Jegelewicz** [comment]
From the Google Doc:

Overall goal of modifications to the Taxon Page:
 -[ ] Reduce the amount of scrolling necessary to find information or modify taxon records.
 -[ ] Increase consistency of user interface.
 -[ ] Put most important information on the taxon page and supplementary information one-click away.
 -[ ] Reduce the need to update these pages when elements of code tables change.
 -[ ] Modify verbiage so it suits Linnean and non-Linnean terms

Key Recommendations:    
 -[ ] Tighten the structure overall and make everything consistent for users.
 -[ ] Decrease the size of the locality map with an option to increase the size
 -[ ] Limit images to one row and then access the “gallery” for more
 -[ ] Have images of specimens be first – before PDFs of field notes etc.
 -[ ] Reduce the space taken up with synonyms
 -[ ] Easier access to the local sources that can be edited.
         - Arctos
         - Arctos Plants    
         - WoRMS (via Arctos)

**Comment by Jegelewicz** [comment]
@sharpphyl I have done A LOT of work to this in test. Please check it out and let me know what you think so far!

I've been using [this one](http://test.arctos.database.museum/taxonomy.cfm?taxon_name=Delphinus+delphis&taxon_name_type=&taxon_term=&term_type=&source=&common_name=#taxonsearchresults) to test with.

But do try searching stuff from the taxonomy search as well, because I made a few modifications to the search results as well.

The map and media sections need to be modified elsewhere - I'll get to that later.

I'll work on the order of and the way the individual classifications appear later too.

Progress?

Happy holidays!!!!

**Comment by Jegelewicz** [comment]
From the Google Doc:

> It seems that we’re somewhat inconsistent with hyperlinks.  All of them are in blue (which turns purple once you’ve accessed the hyperlink) but some are in brackets and underlined and some aren’t.  Some go to a different page and others just move you around on the page.  Is there a standard format we’re using?

**Comment by Jegelewicz** [comment]
@sharpphyl I set the usage stuff to open, but it can be closed if anyone feels like it. Let me know what you think.

**Comment by sharpphyl** [comment]
@Jegelewicz   I may be looking in the wrong place, but I don't see the "usage stuff" anymore or the external validation.  Can you give me a taxon name that shows the changes?

**Comment by Jegelewicz** [comment]
It's only running in test and you have to be logged in to see it.

http://test.arctos.database.museum/name/Canis%20latrans

**Comment by sharpphyl** [comment]
Thanks.  I found it and it looks great.  We'll have to see if others prefer to have it hidden to start, but it's perfect for my work.

**Comment by Jegelewicz** [comment]
@sharpphyl I changed the list of sources so that the locals are first. Will this work? (Check in test - not in production yet).

![image](https://user-images.githubusercontent.com/5725767/129095995-d76e0805-3798-4a2f-ac74-032bb53c1877.png)

**Comment by Jegelewicz** [comment]
> Have images of specimens be first – before PDFs of field notes etc.

This is a tough nut to crack - it seems like it would mean splitting the media thing into "images" and "not images". I set them to order by media type, hopefully that will be better than the random order they were in. @sharpphyl check it out in test.

**Comment by sharpphyl** [comment]
yes, Yes, YES!

Separating the list of sources into Local and External is a big help and probably sufficient.

As for the media, I checked http://test.arctos.database.museum/name/Achatinella%20apexfulva and it shows the specimens first and then the notes so I think that does it.
