### ISSUE TITLE
Suggested Changes to Edit Classification Page

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3264]
From https://github.com/ArctosDB/arctos/issues/2695#issuecomment-676623830

See https://docs.google.com/document/d/1nGYEnOPxM56Vv2FAQi3iDIrzRFMcjw-c/edit

**Comment by Jegelewicz** [comment]
- [ ] remove all reference to editing a WoRMS (via Arctos) entry
- [ ] Nomenclatural code is mandatory for Linnean names.
- [ ] moving around help text per Google Doc

**Comment by sharpphyl** [comment]
I think it's excellent.  The format consistency is very helpful.  

1.  We don't link to any How To on this page.  Should we link to https://handbook.arctosdb.org/how_to/How_to_Edit_Taxa.html - which, of course, will need a major revision once we publish the changes.  (I hereby self-assign that task.)

2.  Should we add this second sentence even though you go into more detail in the Linnean hints.

**Caution**: there is no enforced order for classification terms.  Drag rows to the correct order for the type of classification.

3.  The last column in the classification says "original."  I tested what this is by adding a row (then deleting it) and it says "original" again.  Is there a reason for this column?  

<img width="953" alt="Screen Shot 2021-08-12 at 7 00 39 AM" src="https://user-images.githubusercontent.com/15368365/129201122-9e18e7a7-2946-4e9b-a548-93de15e001d8.png">

**Comment by Jegelewicz** [comment]
> We don't link to any How To on this page. Should we link to https://handbook.arctosdb.org/how_to/How_to_Edit_Taxa.html 

That is now here.
![image](https://user-images.githubusercontent.com/5725767/129216314-ac76529d-0c8c-4326-8da3-a76a6b15fe44.png)

I added the link to that how to - but it hasn't shown up in the UI yet. Maybe it will be there by the time you look (in production).

@dustymc this one is for you

> 3.  The last column in the classification says "original."  I tested what this is by adding a row (then deleting it) and it says "original" again.  Is there a reason for this column?  

<img width="953" alt="Screen Shot 2021-08-12 at 7 00 39 AM" src="https://user-images.githubusercontent.com/15368365/129201122-9e18e7a7-2946-4e9b-a548-93de15e001d8.png">

**Comment by sharpphyl** [comment]
"create a link"

It hasn't shown up yet but I'll keep checking.

**Comment by Jegelewicz** [comment]
All moved to #2695
