### ISSUE TITLE
Suggested Changes to Create a New Taxon Name Page

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3266]
From https://github.com/ArctosDB/arctos/issues/2695#issuecomment-676623830

See https://docs.google.com/document/d/1GirqaJEyXHiENrRKnQmXvCLMId4rPWOchy4Xuvm_8es/edit

**Comment by Jegelewicz** [comment]
Incorporated suggestions and made consistent with "clone as a new name" page.

**Comment by sharpphyl** [comment]
I'm playing with Create a New Taxon Name in TEST.  I've created _Oliva test_ just to see how it looks.  I'll delete it but leave it in until we close this issue.

Overall, looks much better.

I like having the aphia id field open up when I go to create the classification, but probably don't need it this many times.

<img width="740" alt="Screen Shot 2021-08-18 at 9 41 24 AM" src="https://user-images.githubusercontent.com/15368365/129928940-e0b2d552-a5e5-4ce6-b8d4-aa6afdc27482.png">

It's great when there's a dropdown for the Nomenclatural code that lists what's in the table.  Right now, you have to type it in which can lead to errors.  Same for Taxon Status.  Can the table values be added in that field?  I usually just put in a WoRMS aphiaid, but if I have to create the metadata and classification from scratch, having the table value is very helpful and we do it in a few other places  (I'll search for it - maybe it's in the hierarchical tool) so the code should be somewhere.

If you refresh Global Names - even for a dummy name like I've done - you get a host of external services - but none of them is for the species.  They all are for the genus or related genus.  I find this to be clutter and would rather not have anything.  I can look for the genus if I want to clone a classification.  Do other users find this to be clutter?

<img width="422" alt="Screen Shot 2021-08-18 at 9 49 29 AM" src="https://user-images.githubusercontent.com/15368365/129930321-8537f5f4-1702-44cd-9042-6528d194891f.png">

For example, here's what comes over from WoRMS

<img width="1134" alt="Screen Shot 2021-08-18 at 9 52 16 AM" src="https://user-images.githubusercontent.com/15368365/129930564-76221b57-b124-4fa3-b7d3-9dfaeaf18d45.png">

Lastly, I looked at an existing and valid name _Oliva sericea_. http://test.arctos.database.museum/name/Oliva%20sericea  We have several specimens that have been geolocated and the map comes up but without any pins.  

<img width="1110" alt="Screen Shot 2021-08-18 at 9 57 55 AM" src="https://user-images.githubusercontent.com/15368365/129931491-fc1b530f-6d32-44de-af7c-020dcadef557.png">

The map with our specimens shows these four pins.  Is this a bug or just occuring in test?

<img width="1223" alt="Screen Shot 2021-08-18 at 9 55 35 AM" src="https://user-images.githubusercontent.com/15368365/129931080-d1b8ca74-8b88-4257-b357-74257a6b6f63.png">

**Comment by sharpphyl** [comment]
I found the fields with the options for nomenclatural code and taxon status built in. It's in the edit from the Clone classification.

<img width="845" alt="Screen Shot 2021-08-18 at 10 03 52 AM" src="https://user-images.githubusercontent.com/15368365/129932738-46bbc88a-77bd-477c-8be3-ed2950071878.png">

Can we standardize on the metadata fields we want to prepopulate every time we create a name or edit a name?

This is what it looks like in the Create classification page.

<img width="714" alt="Screen Shot 2021-08-18 at 10 07 54 AM" src="https://user-images.githubusercontent.com/15368365/129933002-149507e9-1a14-4da6-accf-b9ee8d0023c8.png">

Maybe we can discuss at today's meeting exactly what Term Types should be prelisted and which ones should have the options from the code table built in.

**Comment by Jegelewicz** [comment]
Can we populate metadata for new classifications or cleaned classifications with the term types appropriate for the name type?

**Comment by Jegelewicz** [comment]
Moving all the rest of these suggestions to #2695
