### ISSUE TITLE
Suggested Changes to Create a New Taxon Classification Page

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3267]
From https://github.com/ArctosDB/arctos/issues/2695#issuecomment-676623830

See https://docs.google.com/document/d/1PuckXESEx2_iqnSmYaw-7Olp03hDqAEG/edit

**Comment by Jegelewicz** [comment]
I edited this for consistency with the edit classification page and made it so that one is forced to select the Source (rather than defaulting to the first source in the list).

This is currently controlling what rows appear in the non-classification terms:
```
$(function() {
			// suggest some defaults
			$("#ncterm_type_1").val('author_text');
			//$("#ncterm_type_2").val('display_name');
			$("#ncterm_type_3").val('nomenclatural_code');
			$("#ncterm_type_4").val('taxon_status');
			$("#ncterm_type_5").val('infraspecific_author');
			$( "#sortable" ).sortable({
				handle: '.dragger'
			});
```
which is why there was the weird blank in the second row and why other non-class terms weren't showing up. The question is - what do we WANT to show up here? All terms (I think not)? Required terms (none are absolutely required as far as I can tell)? No terms and just select what you need?

This is how it looks in production:
![image](https://user-images.githubusercontent.com/5725767/129377074-2f1e6d8f-4f0e-4f01-b856-0faddc1dffff.png)

Right now test has something a bit different, but still weird because of this list.

@ArctosDB/taxonomy please weigh in.

**Comment by Jegelewicz** [comment]
@dustymc Phyllis asked what this does:

![image](https://user-images.githubusercontent.com/5725767/129381986-346b9e6b-199f-491e-b891-e8a1a3885888.png)

When I select it, after a long time, I get this:

![image](https://user-images.githubusercontent.com/5725767/129382082-3478be3d-d8a1-4ce1-baec-1b5e7b3a2e91.png)

Do we need this? If so, then maybe this isn't the best spot for it and we should include some explanation?

**Comment by dustymc** [comment]
That form just isn't going to produce consistent data, all attempts at doing so can/should be removed. There are now lots of ways to  produce consistent data, suggest adding a warning/link/something. I support anything that can be done to simplify.

IDK what that link was supposed to do, it can go too.

**Comment by Jegelewicz** [comment]
I vote that we just put some blanks because nothing there is required for ALL name types. (Although we say nomenclatural code is - is it?)

**Comment by dustymc** [comment]
Well SOMETHING is required, but there are no rules on what (unless maybe in the form). A remark consisting of one space is a perfectly valid classification (and why I'm not at all convinced that 'has something' is what users really need to know in https://github.com/ArctosDB/arctos/issues/1894).

**Comment by Jegelewicz** [comment]
> SOMETHING is required

Yeah, so we just offer up a blank row (this is for classification metadata) and let people add what they want?

**Comment by Jegelewicz** [comment]
All this is now on hold until I can figure out https://github.com/ArctosDB/PG/issues/14

**Comment by Jegelewicz** [comment]
Taxonomy Committee asks that we present metatdata terms appropriate to the name type - seems doable. Adding to #2695 and closing here.
