### ISSUE TITLE
Suggested Changes to Clone Taxon Classification Page

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3270]
From https://github.com/ArctosDB/arctos/issues/2695#issuecomment-676623830

See https://docs.google.com/document/d/1g2xwbUtbRYAZNlyM-zJi4Wjva3xVBEhO/edit

**Comment by Jegelewicz** [comment]
How do we want to present code table information? See clone classification into a new name page for all three choices

- the "define" method used on the main search page
- As part of "instructions"
- clickable labels for the data entry

**Comment by sharpphyl** [comment]
I'm not sure I understand the question.  Can we look at it at today's meeting?

**Comment by Jegelewicz** [comment]
That's the idea!

**Comment by Jegelewicz** [comment]
Let's go with define and try to use it everywhere

**Comment by Jegelewicz** [comment]
Moving all the rest to #2695
