### ISSUE TITLE
EML generator update

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3275]
* need to escape for XML
* check closing ``para`` tags

for @dbloom 

@lin-fred @Nicole-Ridgwell-NMMNHS is the ampersand in alternateidentifier for NMMNH Herb intentional?

**Comment by lin-fred** [comment]
Intentional in the sense that NMMNH is also known as NMMNH&S (with the ampersand being "official")

**Comment by dustymc** [comment]
@dbloom this should go to production at 6PM tonight, when there's a release (and some downtime) scheduled.

Here's a generated demo file with some strange stuff; it validates in everything I could find.

[ALMNH_ES-5.eml.zip](https://github.com/ArctosDB/arctos/files/5654361/ALMNH_ES-5.eml.zip)

**Comment by dbloom** [comment]
Thank you @dustymc  I will look tomorrow and give it a test using MNNMH Paleo, @Nicole-Ridgwell-NMMNHS

**Comment by dbloom** [comment]
Worked like a charm. Thanks @dustymc
