### ISSUE TITLE
Split up Bulkload Tools menu?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3276]
The Bulkload Tools menu extends beyond the viewscreen - can we group stuff to make it less huge?

<img width="960" alt="Screenshot 2020-12-04 09 21 30" src="https://user-images.githubusercontent.com/5725767/101213556-ca4bd280-3637-11eb-8e3f-434e497e25f4.png">

**Comment by dustymc** [comment]
Added some grouping - it fits on my screen but I still couldn't find anything...

<img width="546" alt="Screen Shot 2020-12-16 at 12 37 32 PM" src="https://user-images.githubusercontent.com/5720791/102403803-a83d4300-3f9b-11eb-9087-f3c960d54b72.png">
