### ISSUE TITLE
Feature Request - Object titles in art collections

### ISSUE THREAD

**Issue by krgomez** [ArctosDB/arctos#3277]
**Is your feature request related to a problem? Please describe.**
The title of a work of art is a critical attribute that needs to be prominently displayed both on the catalog record as well as in the search results. We have been including the object title in the identifications string in order to make that happen, however this presents problems.

The object title should really not be included along with the object type, as they are distinct data that should not be cataloged together in a single string. Including the object title along with object type is also duplicative, as we also record the object title as an attribute, which is where it is probably best suited. As an attribute we have the ability to clearly record remarks, determiner, and dates for the object title (as well as method, which we don't currently record, but I think we should use it to record the title type, such as inscribed, artist's, descriptive, translated, etc.). The problem with only recording the object title using the attribute is that it will not display prominently at the top of the search page and it will not appear clearly and prominently in the search results.

**Describe what you're trying to accomplish** 
An clear and concise overview of the goals; why are you asking for this?
To identify the appropriate place in the catalog record to record the object title of a work of art that will also allow for prominent display in the catalog record and search results. 

**Describe the solution you'd like**
How might we accomplish your goals?
Is it possible to customize what displays at the top of the catalog record? For example, would it be possible for the object title attribute text to display at the top of the catalog record for art collections? Also, is it possible to have more flexibility in bringing an essential attribute like object title over to the left hand side of the search results so that it displays clearly and is not pushed way over out of sight?

**Describe alternatives you've considered**
Continue mashing the object type and object title together as an identification, but this really doesn't seem like the right thing to be doing. 

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.
High

**Comment by dustymc** [comment]
I'm thinking "title" is an Other Identifier. (And you can customize to display those prominently.)

<img width="190" alt="Screen Shot 2020-12-04 at 4 08 20 PM" src="https://user-images.githubusercontent.com/5720791/101226943-f3c22980-364a-11eb-9ea6-02fcb41192f9.png">

That fits with the idea/structure of the data - it's a way to identify that particular ``Painting, Watercolor``, just like "DLM12345" (a potential collector number) is a way to identify that particular ``Sorex cinereus``.

https://handbook.arctosdb.org/documentation/other-identifying-numbers.html#other-identifier-type

**Comment by Jegelewicz** [comment]
That would work EXCEPT, the other identifier can be preferred by your login profile. So, for me, this record looks like this:

![image](https://user-images.githubusercontent.com/5725767/101282387-1dd23380-3792-11eb-824f-6c005b2bdabc.png)

UNTIL I change my preferred identifier to "Title". Then I get this:

![image](https://user-images.githubusercontent.com/5725767/101287344-f472d100-37ac-11eb-9d30-3b644c657bd1.png)

Which is perfect? or maybe just better? Any way we can just make Title appear here any time there is one, no matter what? And perhaps NOT have it show up down in other identifiers where it is a duplication.

**Comment by krgomez** [comment]
Just so it's clear from the screenshot above, for this record I edited the string so that it only included the object type: watercolor. This is how we would want the identification to work. It is so fabulous to see the new cultural taxonomy at work in Arctos! 

I think the idea to record the object title as an Identifier does make sense in that it displays the way we want it to at the top of the catalog record (if we can get it to reliably display that way for public users as well) and would clearly display in the search results as well. However, we would not be able to make remarks or record the determiner, date and method for the object title if we were to record it as an Identifier. It seems we would still need to keep the object title attribute in order to be able to do that. I'm thinking that perhaps entering the object title as both an identifier and as an attribute would be okay, even though it would be entering the same data in two separate places. Perhaps what we could then do is encumber the object title attribute so that the public doesn't see the title in three different places on the catalog record. It doesn't bother me to see the title in the Identifiers box in addition to the top of the catalog record.

**Comment by Jegelewicz** [comment]
@krgomez an alternative would be to also place the title in the remarks of the identification. Then it would be associated with the determiner of the ID and you wouldn't need to create another attribute.

**Comment by krgomez** [comment]
That is nicely simple to get rid of the string altogether!

I don't like having the title in the identification remarks. It's not hurting anything but it doesn't help accomplish the display goals that using the Identifier does and it doesn't allow us to record the metadata about the object title that the attribute does. The determiner for the object title (most often the artist) would often be different that the determiner of the object type (cataloger). For some artworks, we will need to record remarks about the title which we can't do if the title is in the remarks field for identification. I'm also still liking the idea of using attribute method to record the [title type](https://www.getty.edu/research/publications/electronic_publications/cdwa/4titles.html#RTFToC3) from a pick list.

**Comment by Jegelewicz** [comment]
> I'm also still liking the idea of using attribute method to record the title type from a pick list.

I'm not sure that we can assign a fixed set of determination methods. Curently that is a free text field. But we could add an attribute:

title type - The kind of title or name assigned to a work.

the values for this attribute would come from a code table:

cttitletype
value | defintition
-- | --
descriptive | 
repository | 
inscribed | 
artist's | 
former | 
translated | 
constructed | 
original | 
brand name | 
popular | 
published | 
series | 
manuscript designation | 

But if you have more than one "title" value, it wouldn't be possible to link the different titles with their type.

@dustymc any way we can create a "method" code table that only applies to the attribute "title"?

**Comment by dustymc** [comment]
>make sense in that it displays t

This is never a compelling argument. We should be looking for what's capable of accurately reflecting the data, then building UI around that if necessary.

https://www.getty.edu/research/publications/electronic_publications/cdwa/4titles.html#RTFToC3 do not look like methods to me, they are different categories of a thing. They'd be different other identifiers in a mammal collection, but I'm not sure how much that carries over here. In any case adding the ability to CT-control method would take significant development, starting with significant discussion.

>remarks of the identification

I'm not sure it makes sense there, but perhaps Identification is correct in some way - what's happening now, or something new, or ??? I didn't realize there was quite as much subjectivity in titles as there apparently is, maybe it doesn't make sense in otherIds after all.

One possible approach would be to use the title ("Parade Ground of the Fur Seal Pups, Reef, St. Paul Island") as the identification string, attached to the taxonomy (https://arctos.database.museum/name/Watercolor) - I think that could be defensible structurally, but it might not be quite as explicit as you'd like to be with "taxonomy."

**Comment by Jegelewicz** [comment]
> One possible approach would be to use the title ("Parade Ground of the Fur Seal Pups, Reef, St. Paul Island") as the identification string, attached to the taxonomy (https://arctos.database.museum/name/Watercolor) - I think that could be defensible structurally, but it might not be quite as explicit as you'd like to be with "taxonomy."

That's how we originally had it, but the way it displays is not acceptable which is how this thread got started.

**Comment by Jegelewicz** [comment]
OK, I see now that at some point Painting, Watercolor was in the string?

@krgomez look at https://arctos.database.museum/guid/UAM:Art:UA0482-0001 now.

**Comment by dustymc** [comment]
>int Painting, Watercolor was in the string

yes, because there was no formal taxonomy available.

I think you've done in the demo what I was thinking.

**Comment by krgomez** [comment]
> do not look like methods

I agree that title type is not a method precisely, but I was thinking we could make it work if it would allow us to connect a title type code table with the object title. For some reason I thought we had the option to use controlled entry with method but I realize now we can't do that. Finding a way to document title type is a lesser issue here. Our primary goal is to find the right place to record the object title. However, mentioning title type helps show some of the complexity in object titles that we need to be recording in our catalog records.

> OK, I see now that at some point Painting, Watercolor was in the string?

What we currently have in Identifications for everything in the collection is: unidentifiable {object type, "object title"}. We only added title there for display purposes (clarity in the search results and display at top of record). So continuing to use the object title as the Identifications string would continue to accomplish these display goals. For this watercolor we were using: unidentifiable {Painting, Watercolor, "Parade Ground of the Fur Seal Pups, Reef, St. Paul Island"} We had also included painting as that was the only way to find all the paintings in the collection.

Some issues I see:

I LOVE seeing the object type hyperlink and the possibility of discovery from users clicking over there. 

The object type does not display in search results in this structure. 

I'm not sure object title makes sense there, but maybe I'm wrong and it is the right place.

**Comment by Jegelewicz** [comment]
> The object type does not display in search results in this structure.

@dusty could we add as an option for showing more fields in the specimen search results?

**Comment by Jegelewicz** [comment]
> I'm not sure object title makes sense there, but maybe I'm wrong and it is the right place.

I'm not sure either. One advantage to this method is that you can associate any number of taxa with the title. So in addition to the cultural terms, you could also associate Arctocephalinae - the subfamily for fur seals....See also https://github.com/ArctosDB/arctos/issues/3278#issuecomment-740096335

**Comment by dustymc** [comment]
>showing more fields 

Elaborate please, I think I'm lost. (And speaking of identifiers, that's not me....)

>you could also associate Arctocephalinae

Short answer: yes, you can.

Longer answer: please don't unless there are seal-bits involved, you'll further unenlighten those biologists. If that's painted on a seal skin, or involves seal bones, then PLEASE make those links. If it's just a picture of a seal then I think making the links to biology will just serve to complicate the mechanism of exposing your collections to a larger community.

**Comment by Jegelewicz** [comment]
Agree with the long answer - but it is a possibility that things like this could happen as you pointed out.

Elaborate please:

I think they would like to be able to see the associated taxa from the A part of the A {string} in the results:

![image](https://user-images.githubusercontent.com/5725767/101396186-2efd6c00-3888-11eb-9aa0-6fa1defa24d4.png)

So for the first one, you would see "Watercolor"

**Comment by Jegelewicz** [comment]
BUT in addition to your long response - what if I want to find all paintings that contain fur seals? Sure, that might be in the title, but it also might not be....

**Comment by marecaguthrie** [comment]
Thanks so much for all the work on this!
I've just been chatting with Karinna on the phone and as I wanted to
summarize our display needs vs our function needs.
I do think this is an example of something that is very
discipline-specific. I'm not sure if Title is an identifier or not but it
is one of the most important pieces of information that people use to talk
about an art object.

*Object Title display needs: *
We need title to be prominently displayed in the object record page and in
the search page. It seems like how things stand now accomplishes this goal.
It brings me such joy to see it at the top of the page so clearly
displayed. Unfortunately though, in the current iteration, I don't think it
has the functionality that we need.

*Object Title function needs:*
We need to be able to record information about the title (who determined
the title, what previous titles have been, if there is more than one title
then which is the preferred one and why, what reasons it was changed, who
changed it, what it translates to, etc.)

**Comment by dustymc** [comment]
I think I'm back to thinking "object title" is best as a string identification, in no small part because https://github.com/ArctosDB/arctos/issues/3278. It seems that the idea is a bit more than "title," it's what the thing _is_ (for some purpose, according to someone, or something). Having that backed by formal taxonomy makes it less necessary to overload the "title," and the structure of Identifications provides a place for metadata - the creator called it "Parade Ground of the Fur Seal Pups, Reef, St. Paul Island" and asserted that it's a watercolor, the curator calls it "Fur Seal Pups" and thinks it's an example of https://arctos.database.museum/name/Food%20Auger for some reason, one publication is looking at the painting and cites the object as "Parade Ground of the Fur Seal Pups, Reef, St. Paul Island" (the identification), another is looking at it as an example of a watercolor and cites it as https://arctos.database.museum/name/Watercolor, another sequences a sample and comes back with https://arctos.database.museum/name/Arctocephalus%20pusillus, .... 

That also fixes - or at least doesn't make worse - the display; identification is always about the most important thing about the record, and is somehow included prominently in about every view that includes the record.

@Jegelewicz we still suck at naming things, that can be many taxa, "full taxon name" could be included, Issue. (Should be pretty easy...)

>what if I want to find all paintings that contain fur seals? 

According to whom? https://arctos.database.museum/guid/UAM:Art:UA0482-0001 doesn't look like fur seals to me, that's obviously a depiction of {whatever, because art}. Yet another reason to do this all as Identifications, perhaps.

Or my head's all full of mush, I don't know anymore!

**Comment by dustymc** [comment]
Beat by 19 seconds!

>is one of the most important pieces of information that people use to talk
about an art object.

Like identification in a bio collection.

>don't think it
has the functionality that we need.

Elaborate please.

>e able to record information about the title (who determined
the title, what previous titles have been, if there is more than one title
then which is the preferred one and why, what reasons it was changed, who
changed it, what it translates to, etc.)

Identification does that (I think)

**Comment by krgomez** [comment]
I see tremendous value in being able to add associated taxa for materials, but that's not related to title. So if seal skin was used as the support for a drawing (we do have examples of this), that would make sense to me to add that as an associated taxa. But if an artwork depicts a seal (we have lots of those!), that would be a keyword (see #2362). I am working on spreadsheets for keywords with the intention of importing these as attributes.

**Comment by dustymc** [comment]
>keyword

AHA! Makes sense, and so does 2362 now (I hope...).

**Comment by Jegelewicz** [comment]
I also think Title belongs in identification. You can have as many as necessary and every ID includes a determiner and date. What we may need to discuss in only allowing a single "accepted" identification.

**Comment by Jegelewicz** [comment]
Check on the keywords..

**Comment by campmlc** [comment]
Also format for downloading multiple identifications. Same problem as
multiple specimen events. How can we download in usable format?

**Comment by krgomez** [comment]
I went back to the [CDWA](http://www.getty.edu/research/publications/electronic_publications/cdwa/4titles.html) and it groups names and titles together. It does separate the object type from title or name, but sometimes object type is used as the name. We don't currently record the name when there is no title (rather we use _Untitled_), but some collections would do that. Stepping back and remembering the interdisciplinary nature of Arctos helps me see that the title or name should be linked to the object type.

![Screen Shot 2020-12-07 at 11 16 26 AM](https://user-images.githubusercontent.com/40579515/101400633-a8dc2800-387d-11eb-87ff-c5b7c0615c9e.png)
These constitute the information that we should be recording about a title.

The problem that I see with recording the object type and the object title together as an Identification is that we need to be able to keep track of the metadata and revisions for each of these types of data. I have added new identifications for a few objects to demonstrate what I mean. 

This is a temporary change just to demonstrate why we would want to keep track of various titles, title type and maintain clarity about preferred title. In this example for [UA1982-003-093](https://arctos.database.museum/guid/UAM:Art:UA1982-003-093), which has been titled "Untitled", I have gone in and added a new identification that uses a descriptive title "Ceramic bowl with three fish". 
![Screen Shot 2020-12-07 at 12 50 20 PM](https://user-images.githubusercontent.com/40579515/101412775-a2ef4280-388f-11eb-85f3-63345685f31e.png)
Furthermore, let's say we contact the artist and she lets us know that there actually is a title, and she calls it "Abstract Bowl". We would then need to add another identification with the new title and title type recorded as artist's. 

It seems that this would be a great way of recording variations of title, however we also really need to be able to do that for object type. In this example for [UA1982-003-035](https://arctos.database.museum/guid/UAM:Art:UA1982-003-035) I have added a taxonomic revision to specify that this piece of jewelry is a necklace. 
![Screen Shot 2020-12-07 at 1 28 48 PM](https://user-images.githubusercontent.com/40579515/101413196-50625600-3890-11eb-89bc-81b8bc4dc664.png)
Another example would be if an artwork has been incorrectly cataloged as a gelatin silver print but this needs to be revised to platinum print. We need to be able to keep track of this revision in Identifications. Or in the Thule Bird example, perhaps we contact the artist and he says that he considers this work to be a sculpture. We would then need to add a revision to reflect the artist's intent. 

I don't see how we can keep track of the metadata and revisions for both title and object type simultaneously through Identifications.

**Comment by Jegelewicz** [comment]
Another example would be if an artwork has been incorrectly cataloged as a gelatin silver print but this needs to be revised to platinum print.For the Thule Bird change to platinum print, just add an identification of platinum print {Thule Bird}.

**Comment by Jegelewicz** [comment]
OK - that is nuts!

@dustymc when I add an identification of sculpture {"Thule Bird"} to this record, it wipes out the identification necklace {"Thule Bird"}.  Why?

**Comment by krgomez** [comment]
> I don't see how we can keep track of the metadata and revisions for both title and object type simultaneously through Identifications

Now that I have all that written out and posted, I’m thinking that it’s probably fine to keep track of revisions to both title and object type together in identifications. I’m not sure it matters so long as we can be clear about what the metadata is referring to, the title or the object type.

Is there any way to add in a new controlled entry for title type into identifications?

Is there a way to make the taxonomic determination display in the search results, if it is not to be part of the identification string? 

Also, there may be cases where the most recent determination of identification is not the preferred. If that were ever the case, my there be a way to use an older determination as the preferred?

**Comment by krgomez** [comment]
Also, I still think it's a bummer about losing that object type hyperlink. I don't suppose there is any way to still have that but without mashing the object type and title together?

**Comment by dustymc** [comment]
>wipes out the identification 

Hu?

<img width="951" alt="Screen Shot 2020-12-07 at 6 06 56 PM" src="https://user-images.githubusercontent.com/5720791/101429146-15bfe400-38b7-11eb-864b-96150011963b.png">

<img width="951" alt="Screen Shot 2020-12-07 at 6 07 08 PM" src="https://user-images.githubusercontent.com/5720791/101429156-19ec0180-38b7-11eb-9afe-7d2b7aea3c1a.png">

>new controlled entry for title type into identifications?

New Issue, and/or I'm not sure what you're talking about.

>make the taxonomic determination display in the search results

Turn on Full Taxon Name.

Accepted and recent are not confounded in any way.

> losing that object type hyperlink

https://github.com/ArctosDB/arctos/issues/3283

**Comment by Jegelewicz** [comment]
> Is there any way to add in a new controlled entry for title type into identifications?

It seems like these should all be in the "nature of id" table. Then you could use that for something meaningful.

**Comment by Jegelewicz** [comment]
> Also, there may be cases where the most recent determination of identification is not the preferred. If that were ever the case, may there be a way to use an older determination as the preferred?

You can choose any of the available identifications to be the "accepted" one. When you enter a new one, it automatically becomes the accepted, but you can change it. Just scroll down to the one you want to accept and make the change. This won't remove any other identifications, just change the one you pick to the accepted one.

![image](https://user-images.githubusercontent.com/5725767/101500296-843e8980-392b-11eb-8e29-982c072235ef.png)

**Comment by krgomez** [comment]
> It seems like these should all be in the "nature of id" table. Then you could use that for something meaningful.

Okay I think that would work. Using the "nature of ID" to record title type does mean that we cannot use it for indicating the nature of ID for object type. This is what I mean about trying to use the Identification metadata fields for both title and object type. 

> You can choose any of the available identifications to be the "accepted" one. When you enter a new one, it automatically becomes the accepted, but you can change it. Just scroll down to the one you want to accept and make the change. This won't remove any other identifications, just change the one you pick to the accepted one.

Great to know!

> Turn on Full Taxon Name

Perfect!

**Comment by Jegelewicz** [comment]
> Okay I think that would work. Using the "nature of ID" to record title type does mean that we cannot use it for indicating the nature of ID for object type. This is what I mean about trying to use the Identification metadata fields for both title and object type.

That makes sense - but how are (or would) you be using nature of ID as metadata about the object type (taxonomy)? It doesn't seem to me like the options available there now are very good for your collections....

**Comment by krgomez** [comment]
They are not. Using for example fine features or audio/visual feels very awkward and are not useful to us. At this time I cannot think of any terms that would be useful for the nature of ID for object type. I suppose we could just choose to use the nature of ID field specifically for recording title type in art collections.

**Comment by Jegelewicz** [comment]
That's what I was thinking. It won't seem intuitive, but we can write appropriate documentation. If you agree - I will create an issue to add those title types to nature of ID and we can let the community discuss.

**Comment by krgomez** [comment]
Sounds great! The terms that I believe we would want to use are: descriptive title, artist's title, inscribed title, former title and translated title. I add title to the end of each because without that I don't know that the assertion would be clearly linked to the title, as opposed to the object type. And something like descriptive alone might be too vague to add to the code table. But you might argue that using title is too specific to be valuable to other collections, if they would be at all.

**Comment by Jegelewicz** [comment]
I think using title in there makes sense and maybe once this is proposed, everyone will decide that we really just need a separate field.

**Comment by krgomez** [comment]
Should we remove the "object title" attributes once the new Identifications have been added? It doesn't make sense to me to keep them there anymore if the Identification string is going to be the proper place to record the title.

**Comment by Jegelewicz** [comment]
Agree. Once the new usage is settled, we can probably get some help from dusty to remove those attributes in bulk if you like, or if you are going to manually update identifications, you could remove the attributes at the same time. Whichever feels better to you!

**Comment by Jegelewicz** [comment]
I woke up thinking about this and how object title is something like organism ID or a name. I'm not sure it changes my opinion about how to handle this, but just wanted to record my thought about it here. Just as there are multiple identifications for the individual "Mexican Wolf No.1216 (also called "Maya", so multiple "titles") there could be multiple titles given to an artwork or object. Something to consider here?

**Comment by krgomez** [comment]
I believe this issue could be closed, as the identification string is what we decided on using as the place for an artwork/object title. See #2501.
