### ISSUE TITLE
"Synonyms" in Nomenclature 4.0

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3278]
There are instances where Nomenclature 4.0 suggests that one "may" use other terms to refer to something. My first inclination was to treat these as synonyms, but before I add a bunch, I want to get input from actual users.

I added the "synonyms" for [Refrigerator Magnet](https://arctos.database.museum/name/Refrigerator%20Magnet) based upon the remark:

> May also use "Advertisement" from Advertising Media or "Decoration" from Decorative Furnishings if appropriate

![image](https://user-images.githubusercontent.com/5725767/101288996-c5615d00-37b6-11eb-8e16-11994626ba93.png)

1. Is this at all useful?
2. Should I also create the reciprocal "synonyms" on the Advertising Media and Decoration names?

There are about 450 of these that I can easily find in the data, so if this is something of interest, I would probably ask Dusty to load them. I have attached the list (which only includes one side of the relationships) for review.

[Nomenclature 4.0 Synonyms.xlsx](https://github.com/ArctosDB/arctos/files/5649332/Nomenclature.4.0.Synonyms.xlsx)

@krgomez @marecaguthrie @AJLinn @brandon-s-thompson

**Comment by AJLinn** [comment]
Is this something that happens automatically when you assign a term or something we do manually?

There is quite an important scenario that we currently can't take advantage of with our single object type ID. As we know, people often re-use tools and turn them into something else. Could this be used to indicate an item that started out, for instance, as a trap spring and then was disassembled and modified to be a scraper blade?

**Comment by Jegelewicz** [comment]
@AJLinn this has nothing to do with identification - in the example you provide, you would have two identifications, one for the original thing and one for the modified (at least that's how I would do it). This is about when Nomenclature says "you may also use XX for this thing".

**Comment by dustymc** [comment]
This seems like an attempt to take the absolute nastiest part of Linnean taxonomy - the part where it completely fails to do the one thing it exists to do, give a single universal name to a group of like things - and replicate it for no particular reason. I suggest we not do that.

That said, I don't think those are synonyms - they're associations, they'd clearly be associative relationships in a thesaurus. We do not have a thesaurus and therefore aren't capable of expressing the relationships at that depth, but neither apparently is the source. Taxon relationships might be appropriate, if these data can be justified at that level of formality, but let's don't mix that with the existing mess.

**Comment by Jegelewicz** [comment]
> Taxon relationships might be appropriate

Isn't that what "synonym of" is?

**Comment by AJLinn** [comment]
> @AJLinn this has nothing to do with identification

Sorry... up too early this morning and not quite firing on all cylinders. Yes, of course, the Nomenclature category is different from the ID.

We had this come up with a cookie in my collection. https://arctos.database.museum/guid/UAM:EH:UA2011-005-0002
This is clearly a Food Sample
https://arctos.database.museum/name/Food%20Sample

However, it it also an advertising medium for the project (these were given out at a party for the Denali Pipeline project).
https://arctos.database.museum/name/Advertising%20Media

In this case, would I simply create two identifications  (each could be Cookie, "Denali" but they would each get their own taxon?

**Comment by dustymc** [comment]
>Isn't that what "synonym of" is?

Synonym is one kind of relationship. This may make use of the same structure - I'm not sure yet - but it's clearly a different meaning.

@AJLinn identifications can refer to multiple taxa in various ways, and I think that's what you've got going on there - one identification involving multiple taxa. 

That may be decent evidence that A {string} IDs linked to formal taxa are "correct," or necessary. If that was a snake eating a mouse it would be "Crotalus and Mus" (a formulaic ID involving two taxa) but I think your identifications are different. Snake+mouse doesn't result in a new THING, and it takes very few forms. "Food Sample and Advertising Media" IDs don't necessarily result in cookies - could be a commemorative meatloaf. The taxa doesn't necessarily determine the nature of the object (which probably can't be formalized because humans are rapidly creative), but you still want people searching "Food Sample" or "Advertising Media" to find your cookie.

**Comment by Jegelewicz** [comment]
> In this case, would I simply create two identifications (each could be Cookie, "Denali" but they would each get their own taxon?

Just add both taxa to the A {string}:

![image](https://user-images.githubusercontent.com/5725767/101389680-08870300-387f-11eb-8522-74c6d87bd5aa.png)

Sorry for using biological names, but none of the cultural stuff is in test...let me know if this doesn't make sense.

**Comment by Jegelewicz** [comment]
Closing for lack of interest
