### ISSUE TITLE
Adding a new line to a classification appears odd 

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/arctos#3279]
![image](https://user-images.githubusercontent.com/43214224/101364203-edf55f80-3867-11eb-8aef-925a3a35f707.png)

**Comment by Jegelewicz** [comment]
I was able to add it, but it is weird when you do - in the column "term" you actually pick the term type and in the column "delete" you add the term.

![image](https://user-images.githubusercontent.com/5725767/101371391-ec2b9c00-3867-11eb-8abb-708b62220790.png)

@dustymc what's up with the strange "-" column when you add a row?

**Comment by mbprondzinski** [comment]
Thanks, Teresa.  Just wanted to be sure I wasn't about to do something illegal and end up with a big red box around my name :-)
