### ISSUE TITLE
Feature Request - taxon link for complex IDs

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3283]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
Current behavior is to replace the taxon name in the identification string with a link to taxonomy. This doesn't work when the taxon name isn't used in the identification.

**Describe what you're trying to accomplish** 
Link IDs to taxa, even when bad assumptions aren't met.

**Describe the solution you'd like**
Add an explicit "click for taxonomy" link somewhere near identifications - suggestions for text and placement very appreciated.

**Describe alternatives you've considered**
Don't think there are any which work for things which might reference multiple taxa without sharing strings with any of them.

**Additional context**
https://github.com/ArctosDB/arctos/issues/3277

**Priority**
needs prioritized

**Comment by Jegelewicz** [comment]
> Add an explicit "click for taxonomy" link somewhere near identifications - suggestions for text and placement very appreciated.

How about this instead - just add the associated taxa BELOW the string identification in the object "header":

![image](https://user-images.githubusercontent.com/5725767/101500711-12b30b00-392c-11eb-9714-aeb800cbdf3d.png)

**Comment by Jegelewicz** [comment]
So for the above you would see

UAM:Art:UA0482-0001
Parade Ground of the Fur Seal Pups, Reef, St. Paul Island
[Watercolor](https://arctos.database.museum/name/Watercolor)

**Comment by dustymc** [comment]
And for the rest of the identifications?

**Comment by Jegelewicz** [comment]
Do you mean for other collections? Other ID formulas?

**Comment by Jegelewicz** [comment]
I was actually just looking at the stuff at the very top of the page, not the individual identifications. What if for A {string} IDs we just reverse the order in the display so that you get the above. That shouldn't affect any other type of identification formula?

**Comment by Jegelewicz** [comment]
> where your arrow starts

That's where I meant - the end was random...
