### ISSUE TITLE
Arctos Community Engagement Resources FYI

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3285]
Thank you all for your responses to the RECODE community workshop on the 8th Dec. 3pm-5.30pm (UTC).

 

We look forward to hearing from you tomorrow.

Below is a reminder of the workshop details.

 

Date: 3-5.30pm UTC, 8th Dec 2020

Link: https://us02web.zoom.us/j/87562917820?pwd=eUxqS3JFTXlhSm5adXhaMXVKbnUrQT09 (Meeting ID: 875 6291 7820; Passcode: 291462)

Suggested background: https://youtu.be/vLXcJej9Vbw?t=187 (15 mins)

 

Please find the agenda in the shared google doc: https://docs.google.com/document/d/1zVNtnC0Svodytqa2K_oLh8WzWjejzXC95s4E2im17iI/edit?usp=sharing

Please find the workshop notes and comments in the shared google doc: https://bit.ly/recode-workshop

We welcome comments in the workshop notes prior to the meeting tomorrow as these may spur the discussions and pre-empt some of the more challenging discussion. Please remember to include your info in the document if you are commenting, understanding who we get feedback from is very important.

 

Kindest regards

Steen Dupont (RECODE programme manager)

**Comment by Jegelewicz** [comment]
Shared Google Doc from meeting: https://docs.google.com/document/d/1iOn5mCC0CCkj8pZdRR9vDlQQldYlM5ROn_xcnb_VY1A/edit#
