### ISSUE TITLE
tool to see resulting pubs, projects, etc. from a collector, or any query

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#3286]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
Not a problem, just a feature.

**Describe what you're trying to accomplish** 
I am filling out a permit application to trap and make specimens. I thought it would be cool to tell the agency what has resulted from my specimens, e.g. how many pubs they have been used in, how many loans, how many projects, etc. This is just arctos, but in the larger context could help with whole argument as to what specimens are good for. 

**Describe the solution you'd like**
Possibly under Agent, see a link to "see all products related to this agent's specimens". Or, more generally, if you did a query of specimens, under tools, see the same sort of tool. This could allow one to see for example all the specimens someone has prepared and what they have been used for. 

**Describe alternatives you've considered**
described above. 

**Additional context**
will help people argue for collecting permits, give some people pride in their contribution, give museum directors an easy tool to quickly find data worth sharing with donors. 

**Priority**
no idea

**Comment by dustymc** [comment]
This would essentially be "dynamic projects" around an Agent. Seems useful to me!

**Comment by dustymc** [comment]
Going next task; seems do-able and useful, probably needs significant development.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/3000
