### ISSUE TITLE
Bulkloading Taxon Names times out too quickly

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3289]
> Any way to do a quicker work around of running names through the validator?
> I'm happy to use it to catch errors like I described above, but I really
> don't want to spend an hour per load clicking refresh every few minutes,
> and then having to copy paste and clean up a messy excel file with names
> and status on alternate rows that can't be sorted . . .

I am assisting Mariel with loading names for The Parasite Tracker TCN grant. It's not difficult, but when using the Name Bulkload Tool, the validation times out A LOT sometimes after only 5 names. We are going to need to load thousands of names, which really do not need validation against Global Names (in fact they will probably be added to Global Names eventually by the TCN, but we can't wait for that because Mariel needs to get stuff cataloged NOW under the terms of the grant).

I don't want to spend a week or so refreshing the tool to get everything validated before loading. Suggestions for making this task easier would be greatly appreciated!

**Comment by dustymc** [comment]
I could potentially make that report asynchronous, but I'd more or less expect that to violate someone's TOS and get us banned. Given our resources, the size of our legal team, the cumulative quality of those webservices, how often this gets used, etc., I'm not sure that can make too much sense.

I believe @dimus has some sort of validator cooking, and might be looking for a real-world test case....

**Comment by Jegelewicz** [comment]
I have 5,300 names ready to go...
[Mites to add.zip](https://github.com/ArctosDB/arctos/files/5662044/Mites.to.add.zip)

**Comment by dimus** [comment]
there is http://resolver.globalnames.org, that is going to be replaced with new one at https://verifier.globalnames.org/api/v1 (API is https://hub.apitree.com/dimus/gnames/). 

Here is a trial verification of your Mites file with new system https://uofi.box.com/shared/static/xv3u4288h4yglfjqntgf5kkhhy6btjx7.csv

**Comment by Jegelewicz** [comment]
@dimus  thanks for that! @dustymc this doesn't solve my slow validation problem and being able to get the names into Arctos.

**Comment by Jegelewicz** [comment]
@dimus I probably need a little tutorial on what each column contains and what "verification" actually means. This list came from the Parasite Tracker TCN people so mite expert(s) put it together. While these names may not currently appear in any resources, I feel pretty confident that they are mostly good (I cannot say the file is completely free of spelling errors...). Eventually, the Parasite Tracker team will (hopefully) either manage these taxa in WoRMS or at least give you a file of their "approved" taxonomy to include in your validation.

**Comment by dustymc** [comment]
Hu? This is at least as good as what I do. Fix the obviously wrong stuff - I checked a few, close to everything that got flagged is in fact wrong, these data are ROUGH for what they claim to be - and load them.

**Comment by Jegelewicz** [comment]
Load them WITHOUT Arctos validation?

**Comment by Jegelewicz** [comment]
> close to everything that got flagged is in fact wrong, these data are ROUGH for what they claim to be

@campmlc maybe your TPT mite people would like to see this before we proceed any further?

**Comment by Jegelewicz** [comment]
@dustymc how do I determine which are "wrong"?

**Comment by Jegelewicz** [comment]
I'm not sure if I trust Open Tree of Life, GBIF, or the TPT expert....

**Comment by dustymc** [comment]
You're the one elbow-deep in these data, it's your call. Can you get something that was flagged as valid to correctly fail my checks? If so I'm sure @dimus wants to know about it, if not this check is at least as good as what you can get from Arctos.

My idea of "wrong" is about 100% "the google test" - search for it in quotes, if you find a bunch of stuff it's useful for finding specimens and that's close enough for us. (But make sure they're not complete garbage - the "SEO" crowd REALLY likes to scrape taxa.)

The first 'fuzzy' -Trouessartia howeveryouspellit - is spelled both ways in the type publication, which always adds a little excitement.....

**Comment by dimus** [comment]
> @dimus I probably need a little tutorial on what each column contains and what "verification" actually means. This list came from the Parasite Tracker TCN people so mite expert(s) put it together. While these names may not currently appear in any resources, I feel pretty confident that they are mostly good (I cannot say the file is completely free of spelling errors...). Eventually, the Parasite Tracker team will (hopefully) either manage these taxa in WoRMS or at least give you a file of their "approved" taxonomy to include in your validation.

@Jegelewicz verification means that a name was found in one of data-sources aggregated by GlobalNames. I do use a scoring algorithm that finds the "Best Result" out of all matches that were returned.

There is a freshly released https://github.com/gnames/gnverify, a command line 'convenience application'. It does have an option to always return data from a particular source, for example, if you want to use Arktos data (that are ~1 year old):

```bash
gnverify -p -s 170 names.txt
```
Take a note that I still have some bugs I need to fix before releasing new verification system 'officially'.

**Comment by dimus** [comment]
@Jegelewicz I have an explanation (in my Russian English ;) ) of all the fields used in verification at https://hub.apitree.com/dimus/gnames/

Please let me know if it is helpful, and if I need to improve wording for some fields.

**Comment by dustymc** [comment]
I'm probably being overly confident on my assessment. I checked three or something, one's a mess and the other two were "clearly" (which doesn't always mean truly - google can latch on to "incorrect" as easily as correct) wrong.

I'm mostly just appalled that we're having this conversation on the tail end of 2020, 49 years after the virus people eliminated this problem.

**Comment by Jegelewicz** [comment]
> I'm mostly just appalled that we're having this conversation on the tail end of 2020, 49 years after the virus people eliminated this problem.

Amen, brother.

**Comment by dustymc** [comment]
I updated the tool

```

	<p>
		Larger datasets may be validated via GloablNames services. See https://github.com/ArctosDB/arctos/issues/3289 for more information.
	</p>
```

we can look at doing more when things stabilize.

**Comment by Jegelewicz** [comment]
@dimus I am going to be working with the TPT people to validate and load their names into Arctos. I've asked for a little bit of funding for your help. They can't pay for consultants, so I will be their employee, but I will pass along funds for the time that you consult with me, if that makes any sense.

Are [these](https://github.com/gnames/gnverify/commit/f5cb970c2f0ed725c7843ebf054d242532085c47) the best simple written instructions for using your verifier?

**Comment by dimus** [comment]
@Jegelewicz yes, https://github.com/gnames/gnverify/blob/master/README.md is the place to go for the instructions about gnverify
