### ISSUE TITLE
UWYMV:Fish and UWYMV:Egg not forwarding to VertNet or GBIF

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#3290]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Neither the UWYMV:Fish or UWYMV:Egg collections are forwarding to VertNet or GBIF. I added all of the info to the collection metadata pages, and am not sure what else is needed. It has been a while since they have been active.

**Expected behavior**
What more do I need to do to get these two collections to the aggregators?

**Comment by Jegelewicz** [comment]
Please see the linked issues in data migration:

https://github.com/ArctosDB/data-migration/issues/469
https://github.com/ArctosDB/data-migration/issues/470
https://github.com/ArctosDB/data-migration/issues/471
https://github.com/ArctosDB/data-migration/issues/472

**Comment by Jegelewicz** [comment]
Probably need to request publication, but probably also should check the manage collection before you do that. :-)

**Comment by ewommack** [comment]
Yeah I filled that out ages ago when I was beta testing the EML generator. I think we got lost in the shuffle maybe?

**Comment by Jegelewicz** [comment]
Probs

**Comment by dbloom** [comment]
@ewommack As soon as I get those home baked cookies for the last publication, I'll get on this one. I never forget baked goods. No shuffle either.

Two more things:

Data won't go into VertNet until we fix our harvesting protocols. Will be another couple of months. So, what isn't getting into GBIF?

Also, in the future, if you want/need me to look at an issue, please flag me with @dbloom otherwise I am not likely to catch it.

**Comment by ewommack** [comment]
Thanks for the help @dbloom. A couple months will be fine as long as they eventually get there.

According to GBIF we still only have 3 collections (UWYMV:Mamm, UWYMV:Bird, and UWYMV:Herp), so UWYMV:Fish and UWYMV:Egg are not getting there. 

I was also wondering if I could get added as a co-administrator for the UWYMV publisher for GBIF? At the moment I'm not associated with it, and I'm not sure if I'm missing info or things I should be doing to help the data at the aggregator: https://www.gbif.org/publisher/50576fe5-7883-495d-9089-b5dcf5e56098

**Comment by ewommack** [comment]
Thought that maybe we should add a section in the Arctos training that deals with older Arctos institutions adding new collections, and another for changing or adding collection staff? 

Both of those things are happening here:
1. I came in as new collection staff after the UWYMV was already added to Arctos.
2. The UWYMV was already established in Arctos and VertNet, and then we went and wanted to add new collections but didn't have to go through the entire process, so I think we did it piece meal.

**Comment by Jegelewicz** [comment]
@ewommack the process for adding collections now would also involve creating a project in this repository with all the associated steps, so going forward, this should get covered - you just came around before that.

**Comment by Jegelewicz** [comment]
> changing or adding collection staff

We definitely could use some beefing up there - we have "[How to manage a collection](https://handbook.arctosdb.org/how_to/How-to-Manage-a-Collection-in-Arctos.html)" and any new staff should probably be required to read it.

**Comment by ewommack** [comment]
> we have "How to manage a collection" and any new staff should probably be required to read it.

It probably didn't help that I was Arctos trained as a CA. Enough knowledge to be dangerous and let loose, but not everything I needed. I'll try and make some time to take a look.

**Comment by ewommack** [comment]
/remind me to look at the [How to manage a collection](https://handbook.arctosdb.org/how_to/How-to-Manage-a-Collection-in-Arctos.html) documentation in two weeks please

**Comment by ewommack** [comment]
Metadata is complete and has been added to the queue for upload.

**Comment by dustymc** [comment]
https://www.gbif.org/occurrence/897114807 exists, tentatively closing

**Comment by ewommack** [comment]
Thanks @dustymc! Forgot that it was open. Looks like they're all still there.

**Comment by ewommack** [comment]
@dbloom - I was just playing around with checking our metadata in different aggregators and saw that the UWYMV:Fish and UWYMV:Egg collections still aren't up on VertNet. Did I do something funny again?

**Comment by dbloom** [comment]
@ewommack Nope, you did nothing funny beyond your usual funny.  ;-)  VertNet is unable to update. As soon as we move to our new portal system there will not be any updates. The move is a high priority for me. When it happens, the metadata in VN and GBIF will be identical, automatically.
