### ISSUE TITLE
creating thumbnails in TACC

### ISSUE THREAD

**Issue by aklompma** [ArctosDB/arctos#3291]
I was suggested to create an issue for help with making suitable thumbnails for ~750 images. 
I tried but getting the file size below 10k at ~120 pixels width or length but this would not work without rendering the images unusable. Can anyone help here? 

The images can be viewed here:
https://web.corral.tacc.utexas.edu/ALMNH/IMLS2017/

The thumbnails may be created in a folder to be added:
https://web.corral.tacc.utexas.edu/ALMNH/IMLS2017/tn/

**Comment by dustymc** [comment]
The easy way is to just not worry about it (assuming the files are normal-ish images, which they seem to be) - you can load the Media without preview_uri, and Arctos will automagically create and attach previews.

**Comment by aklompma** [comment]
Did not know about this, so this is great!

**Comment by dustymc** [comment]
Added minimal documentation to https://handbook.arctosdb.org/documentation/media.html#preview, tentatively closing.
