### ISSUE TITLE
Error screen when Creating or Searching for Loans

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#3292]
I receive an error message today when trying to navigate to the Create Loan or Find Loan forms:

![image](https://user-images.githubusercontent.com/11336485/101646196-70128f00-39f4-11eb-88a4-93e3245f82e9.png)

pages: https://arctos.database.museum/Loan.cfm?Action=newLoan and https://arctos.database.museum/Loan.cfm?Action=addItems

All other transaction pages are unaffected.

**Comment by Jegelewicz** [comment]
UGH - probably my fault....I'll check it.

**Comment by Jegelewicz** [comment]
OK - it's working in test. @dustymc move to production please.

**Comment by dustymc** [comment]
Nice timing - done.

**Comment by ebraker** [comment]
Thanks!
