### ISSUE TITLE
Can't bulkload my Parts

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/arctos#3293]
![image](https://user-images.githubusercontent.com/43214224/101794675-bc310280-3acc-11eb-938a-0df3f654c704.png)
[IMLS BulkloadSpecimenPartAtt.xlsx](https://github.com/ArctosDB/arctos/files/5673904/IMLS.BulkloadSpecimenPartAtt.xlsx)

**Comment by Jegelewicz** [comment]
I don't see anything wrong with that column. @dustymc ?

**Comment by dustymc** [comment]
I can't say anything useful without CSV.

**Comment by dustymc** [comment]
Actually I can - "dispostion" is not a valid header.

**Comment by Jegelewicz** [comment]
AHA! dang spelling!

@mbprondzinski change that header to:

disposition

**Comment by mbprondzinski** [comment]
Is there no spell check?  Are there no work houses???
