### ISSUE TITLE
Dashboard: duplicates?

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3295]
<img width="474" alt="Screen Shot 2020-12-10 at 1 29 57 PM" src="https://user-images.githubusercontent.com/5720791/101832154-d1695980-3aeb-11eb-81d8-81f1eca89c75.png">

@ccicero sees duplicates:

![image(1)](https://user-images.githubusercontent.com/5720791/101832180-da5a2b00-3aeb-11eb-8e8e-829a25716af4.png)

I don't

<img width="930" alt="Screen Shot 2020-12-10 at 1 30 50 PM" src="https://user-images.githubusercontent.com/5720791/101832276-fa89ea00-3aeb-11eb-9a34-7254429e61ce.png">

Is the form broken, is some browser extension or similar being crazy, ????

**Comment by Jegelewicz** [comment]
Looks weird to me too

![image](https://user-images.githubusercontent.com/5725767/101960157-09dc6680-3bc4-11eb-8ae4-7fc8f437b3bb.png)

the first one is duplicated

Also the UTEP:Zoo overdue loans

![image](https://user-images.githubusercontent.com/5725767/101960330-6d669400-3bc4-11eb-987d-435bc93bb639.png)

but it isn't everything, just random things....

**Comment by ccicero** [comment]
Interesting. All of mine are copied three times.

**Comment by dustymc** [comment]
Fixed for next release, I hope....
