### ISSUE TITLE
name of download file not working

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#3297]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
i did a query. Got results. In the window to download, I typed robertRudd. The file that downloaded was called dl_ss_voleguy_20201210051224406_339.csv

**To Reproduce**
Just did another search for all Sorex from Robert L. Rudd. Typed RuddSorex in the box for what to call the file. Downloaded file is called dl_ss_voleguy_20201210061212822_321.csv

**Expected behavior**
That the downloaded file would have the name specified. 

**Desktop (please complete the following information):**
 - Mac
 - Chrome Version 86.0.4240.80 (Official Build) (x86_64)

**Comment by dustymc** [comment]
This is an artifact of https://github.com/ArctosDB/arctos/issues/3246. Operator downloads are now using a very high-performance environment, but it's a bit fragile. I'll see if I can find a way to sanitize the requested filename sufficiently. If I can't I'll remove the input, which currently does nothing, for operators.
