### ISSUE TITLE
media bulkloader

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3298]
The media bulkloader needs rebuilt in the https://github.com/ArctosDB/arctos/issues/2974 ecosystem.

There's currently partial support for creating collecting events. If there are no major objections, I'll remove that - the current complexity isn't really supported here, and I don't think it gets used anyway. If it's critical to someone we can find a way to bring those two loaders closer together, but I don't think it's realistic to keep down the current path. Very vague plan, the media loader will accept collecting_event_name in some way.

The media bulkloader and the zip loader are mixed up - if we can figure out https://github.com/ArctosDB/arctos/issues/3224 we should be able to deprecate the zip loader, in the mean time I'm not sure if it can survive the separation or not. The SCP path remains available, and I can help load things if necessary.

@ebraker youre seeing some strange errors, I can't diagnose them in the current system. I think something's hung in PG and might clear itself up in a bit, but I'm guessing. Let me know when/if it gets urgent and we'll figure something out.

**Comment by dustymc** [comment]
Blocked by https://github.com/ArctosDB/arctos/issues/3224 - need a way to separate main loader from ziploader before simplifying.

**Comment by ebraker** [comment]
Sounds fine to me (speaking as someone who hasn't tied media to events...). My records were hung up for a couple days but eventually loaded so I'm happy.
