### ISSUE TITLE
Barcode series loader reading empty last line of csv file

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#3299]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
the create barcode series loader thinks there is one more row at the end of the csv, so I have to open it up in notepad to delete it before loading.

**To Reproduce**
1) upload barcode series csv
2) error: invalid institution type, missing data etc.

**Expected behavior**
load records without extra step of opening in notepad if possible

**Screenshots**

** Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**
chrome/windows
**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by Jegelewicz** [comment]
@dustymc please fix this as part of #4010

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/4010
