### ISSUE TITLE
Bulkload Locality 400 error when deleting

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#3300]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I'm trying to delete a set of data from the locality bulkloader and getting a 400 bad request error.

**To Reproduce**
1. Go to Bulkload locality
2. Click on delete
3. Get 400 bad request error

**Expected behavior**
I should get a confirmation screen and then the data should delete.

**Screenshots**
![image](https://user-images.githubusercontent.com/47402809/101938212-32526980-3ba0-11eb-8d68-19f373c0c5d4.png)

![image](https://user-images.githubusercontent.com/47402809/101938281-4d24de00-3ba0-11eb-8bbb-b1632e943e23.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 83.0

**Comment by dustymc** [comment]
I was able to change the status, you should be able to do stuff now. I'll fix the cause in https://github.com/ArctosDB/arctos/issues/2974

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks!
