### ISSUE TITLE
Uploading images using BulkloadMedia .csv file - error message

### ISSUE THREAD

**Issue by aklompma** [ArctosDB/arctos#3302]
While using the .csv template from https://arctos.database.museum/tools/BulkloadMedia.cfm to upload [choose file, then upload this file] multiple images per record to existing ALMNH:ES records (ALMNH:ES:10000 and ALMNH:ES:10001 as a test), I got the following error message:

![errormessage](https://user-images.githubusercontent.com/58599209/101961105-a0ae2080-3bce-11eb-9e69-30e0dfab94af.jpg)

Here is the file I used: 
[BulkMedia_2.zip](https://github.com/ArctosDB/arctos/files/5681907/BulkMedia_2.zip)

I used method two "Bulkload Media Metadata From Scratch" in the following link: 
https://handbook.arctosdb.org/how_to/How-to-Bulkload-Media-Metadata.html

Any idea @dustymc or anyone else?

Software: Windows 10, Chrome 87.0.4280.88
Priority: high

**Comment by dustymc** [comment]
Try just deleting all of the unused locality-like columns (https://github.com/ArctosDB/arctos/issues/3298).

You'll need to move the GUID to a ..._term, not .._key column.

**Comment by aklompma** [comment]
Thanks @dustymc! Looks like it worked because I can find it under "My Stuff" now and did not get an error message.

**Comment by dustymc** [comment]
Merging with https://github.com/ArctosDB/arctos/issues/3298
