### ISSUE TITLE
ARK "not a valid URL"

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#3307]
Pretty sure this is an issue happening due to CU server redirects, but when I try to add an ARK either as an other_ID OR as a media_URI, it does not appear to be valid (for other_IDs it does not have the typical ARK base path, and for media_URI I receive the "not a valid URL" error).

Example:
https://ark.colorado.edu/ark:/47540/6c2x3577w0zp 
gets redirected to 
https://cudl.colorado.edu//luna/servlet/detail/CUB~8~8~916~228953

Problem is... the first URL is the stable link that I'd like to relate.

I think I need to talk to our library server people but wanted to check here first. I'll be linking every page of every ledger to every UCM specimen with these....

**Comment by dustymc** [comment]
For Media, I need context/details. I don't think I have anything that would preemptively reject that URI running, but here we are!

For OtherIDs, 

```https://ark.colorado.edu/ark:/``` is a resolver.


```/47540/6c2x3577w0zp``` is an ark

(Or maybe ark:/47540/6c2x3577w0zp or something else is the ark, nobody seems to know, yay not-so-standard-standards, but anyway....)

Our base_url (https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type&field=ARK, ``http://n2t.net/ark:/``) is just another resolver.

http://n2t.net/ark:/47540/6c2x3577w0zp and https://ark.colorado.edu/ark:/47540/6c2x3577w0zp should in theory lead to the same place. They don't - which is absolutely horrifying! - but they both do SOMETHING and perhaps the CDL resolver does the correct thing?

**Comment by ebraker** [comment]
I will get the scoop from our library people. 

I found this [article](https://n2t.net/e/ark_ids.html) somewhat helpful. CU has minted their own ARKs rather than having them hosted on the n2t.net/EZID service, which means that http://n2t.net/ark:/47540/6c2x3577w0zp and https://ark.colorado.edu/ark:/47540/6c2x3577w0zp won't ever lead to the same place.

I sent them an email asking how the local CU ARK server (stable) relates to the LUNA server (unstable) since I'd like to specify the ARK url in Arctos media over the non-persistent link. Will keep you posted...

**Comment by ebraker** [comment]
Ok, nothing helpful. I was directed to our own [handbook](https://handbook.arctosdb.org/documentation/media.html#urls-and-stability) by the library.

"The ARK is analogous to a DOI in functionality – the ARK link is permanent, while the resource it links to can have the URL change behind it as needed. So it does have the redirect functionality built in. "

Context = the CU digital libraries have scanned all of our ledgers. They have provided me a spreadsheet of the ARK for each page image (as well as the URIs for the non-stable direct links to each scan) and the corresponding GUIDs. I want to attach these as media to the relevant specimen records - up to 40 per ledger page - so that users can view the original hand-written catalog entry. This is a great way to cross-check data and something I am asked to do very frequently by researchers.

In an ideal world, I would provide the stable URI, e.g., https://ark.colorado.edu/ark:/47540/6c2x3577w0zp and not the unstable link (e.g., https://cudl.colorado.edu//luna/servlet/detail/CUB~8~8~916~228953) since the latter is subject to change and could ultimately result in tens of thousands of broken media links down the road. However, since the https://ark.colorado.edu/ark:/ address redirects to the LUNA server, I receive a "not a valid URL" error when attempting to create media.

Not sure how to proceed.

**Comment by dustymc** [comment]
>means that http://n2t.net/ark:/47540/6c2x3577w0zp and https://ark.colorado.edu/ark:/47540/6c2x3577w0zp won't ever lead to the same place.

It's apparently possible to silo yourself outside the resolver system, but I don't think it's unavoidable.

>"not a valid URL" error when attempting to create media.

Elaborate please - I think that's "Arctos is broken" but I need enough info to see what you're seeing to figure it out.

**Comment by ebraker** [comment]
When I try to create media using the ARK URI:
![image](https://user-images.githubusercontent.com/11336485/102392651-97d59a00-3f94-11eb-98e8-7dc17687d524.png)
I get this error:
![image](https://user-images.githubusercontent.com/11336485/102392880-e125e980-3f94-11eb-887a-681a56c9837b.png)

When I enter the non-stable URI (https://cudl.colorado.edu//luna/servlet/detail/CUB~8~8~916~228953), the media will create without issue. But I want option #1 plz.

**Comment by ebraker** [comment]
update: When I create media with the non-stable URI, I can subsequently edit and successfully overwrite and save with the ARK URI. So the "not a valid URL" error is just happening during the media creation process.

**Comment by dustymc** [comment]
Thanks, that's what I needed. Lucee's built-in URL validator is choking on the colon for some dumb reason. I will see if I can find a semi-sane alternative.

**Comment by dustymc** [comment]
The check is removed in next release; see also https://github.com/ArctosDB/arctos/issues/3052

**Comment by ebraker** [comment]
Thanks! Before I close this out...how ill-advised is it to bulkload a media_metadata csv  that is 475 columns wide and 852 rows long? 

Essentially I have URL links to individual ledger pages, so each media record may have (at most) 43 relationships with different specimen records... Figured I'd ask before I load in case it has the potential to break stuff or hangs things up.

[bird_ledger_media_load_2020-12-21.zip](https://github.com/ArctosDB/arctos/files/5725927/bird_ledger_media_load_2020-12-21.zip)
