### ISSUE TITLE
[CONTACT] requesting TACC storage for UTEP-IMLS grant

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#3308]
Dusty, just wanted to run this by you before I email Chris and start requesting allocations. 

We received an IMLS grant (mentioned this a long time ago, but revisiting) recently to image our southwest US (set to start in mid februarish) If we include the DNGs onto the TACC storage, it would be around 1-1.5 TB. and much less (about 26000 images) if only jpegs. The project is set to start mid Februarish

We budgeted storage for the duration of the project (1 yearish), but the corral user guide says that UT system PIs can request 5TB for free. I know you mentioned that generally users get a TB for free and to discuss scooching that into the Arctos allocation. Has someone done this already? I'm just a bit fuzzy on how that works and if there's anything else I should bring up that I'm not thinking about. I know long term storage is a bit of a fuzzy issue in general.

**Comment by dustymc** [comment]
Yea just ping Chris, copy me if you don't mind. What I know is only that storage is not free, and that TACC has continually gone far beyond anything we should expect of them. I suggest just asking Chris what they want - they might need $$, or something official-sounding to justify what they're already doing, or ?????

**Comment by mvzhuang** [comment]
@mkoo 
Michelle do you have an opinion on whether it would be better to have our own allocation vs combining it with Arctos's allocation. We might be limited on funding in the future after this grant. 

Chris said this when I asked him if I should have a separate allocation or could combine it with Arctos. UT PIs can get a few TB for free in allocation:
" 
It’s kind of an either/or situation - you can request a separate allocation as a UTEP PI, in which case we can give you the first few TBs free of cost under the UT System research cyberinfrastructure, OR you can choose to expand the existing Arctos allocation by a couple of TB, in which case you would have to contribute to the costs of the storage since the Arctos allocation is “owned” by a non-UT PI. I don’t think it will make a huge difference how this is done unless you have a lot of transformation or data management work to do on the TACC systems. It may take a little more time to set up a separate new allocation for you vs asking someone to add you to the Arctos allocation.

Do you plan on doing image conversion etc on TACC systems or is this a case where you will just be uploading data to TACC and then linking them to Arctos records?"

**Comment by dustymc** [comment]
merge -->https://github.com/ArctosDB/internal/issues/119
