### ISSUE TITLE
Feature Request - 

### ISSUE THREAD

**Issue by aklompma** [ArctosDB/arctos#3309]
The locality attributes of at least some if not all records in Arctos appear to be arranged alphabetically. This results in a counterintuitive order for the age attributes of fossil data in many cases. 

Here's just one example where the order is off:
https://arctos.database.museum/guid/ALMNH:ES:10608

Is there a way to ensure that the following attributes are _directly_ below one another, following the hierarchy in any geological time scale?
Era/Erathem
System/Period
Series/Epoch
Stage/Age

**Comment by dustymc** [comment]
There will be a simple sort in specimendetail for next release. Anything beyond that likely requires some explicit ordering column in some table or something, and everything rebuilt to use it.

**Comment by aklompma** [comment]
Great!
