### ISSUE TITLE
Form redesign - please read

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3310]
Ref: https://github.com/ArctosDB/arctos/issues/3265

Summary: Edit a taxon name, it should look different. Please provide feedback.

Going priority critical - we've been begging for look-and-feel help for years, @Jegelewicz is providing that, let's expedite.

>I want things clean and simple as possible (HAHAHAHAHA!!! but I also WANT IT ALL)

Yes, there are lots of conflicting requests. We can't meet them all, but we can make everything as CSS-driven as possible, and then when the consensus sways we just change the CSS. Controlling even the existence of the accordion, including on all the forms we haven't written yet, should be entirely (or nearly so) a CSS problem. I haven't looked at your code, it should be doing that if it isn't. This is a good time to check out bootstrap or something like it, which should make that significantly easier.

>I have to scroll way too much

Much of that's inefficient whitespace placement, which you can improve by customizing the view to their viewport. That would also make us much more mobile-friendly, which is increasingly important. Any of the big CSS libraries will help.

>We need consistency in the presentation of buttons and links

Also CSS.

Perhaps most importantly, if you can come up with a "recipe" I can use it when I'm doing other stuff - CSS means you don't have to DO everything in order to CHANGE everything.

>taxonomy committee meeting yesterday. These would be the most likely users of this form 

Those are (hopefully!) the folks who haven't joined Arctos yet, but here's who's been there in the last several months.

```
arctosprod@arctos>> select username,count(*) from logs.request_log where url_path like '%editTaxonomy%' group by username order by count(*);
     username     | count 
------------------+-------
 camwebb          |     1
 Phyllis Sharp    |     1
 andres_lopez     |     1
 mkoo             |     1
 NICOLERIDGWELL   |     6
 voleguy          |     9
                  |    11
 sara             |    12
 dmulford         |    13
 acdoll           |    24
 jldunnum         |    24
 dlm              |    32
 patton           |    44
 mbowser          |    45
 aklompma         |    51
 atrox            |    78
 ebraker          |   141
 alisonwhiting    |   205
 ffdss            |   272
 campmlc          |   276
 achinn           |   328
 cfilipek         |   364
 mbprondzinski    |   489
 jegelewicz       |   595
 lindseyfrederick |   738
 aerochild        |  1221
 sharpphyl        |  6117
```

**Comment by Jegelewicz** [comment]
> Controlling even the existence of the accordion, including on all the forms we haven't written yet, should be entirely (or nearly so) a CSS problem. I haven't looked at your code, it should be doing that if it isn't. This is a good time to check out bootstrap or something like it, which should make that significantly easier.

For the form this came from (editing name and related) I just used the HTML display tag, which is really easy so for me ( a complete novice) it does the simple task of expand and collapse. I have hunted around for methods to "remember" the toggle any time a submit, save or delete function occurs, but I am stumped because I just don't know enough. It definitely needs to happen though or people will get frustrated. I need to walk away from this for a while though because it is making me nuts!

**Comment by dustymc** [comment]
>HTML...complete novice...simple task

We should have a big-picture conversation about that. There's value in "so simple a biologist can do it," and there's an API if someone wants something flashy and is willing to invest in it. I'd be completely open to the idea that the whole CSS and frameworks and such thing just isn't practical with our resources. Perhaps we should be limiting the complexity we allow ourselves in some way, in the name of sustainability. 

>methods to "remember"

Parameters will remember through the next click (and add a bunch of complexity, don't go there), cookies can remember through the session (some libraries will handle that for you), longer than that's going to involve writing to the DB. See above - persistently remembering the state of hundreds/thousands of toggles isn't simple, maybe we need an approach that doesn't require such a thing.

**Comment by Jegelewicz** [comment]
I think the CSS is a MUST if we want to keep some sort of consistency in our look. I just need some more training! OR someone who really knows what they are doing to set things up for us to use later (but that's $ we don't have right now - so it's just me!).

In this particular case, the "remember" only needs to happen once. I don't think that anyone coming to this page for the first time today will mind making one click on whichever option they want.  Part of what makes this one complex is that all of the "saves" and "deletes" on this page refresh the entire page when they are done. I can't decide if the answer is to change that or to somehow instruct the refreshed page to return to the same open or close status of each details element just before the refresh. I think either is possible, but it's a steep learning curve for me and so will probably take me a while to work it out. In the mean time, if it becomes a problem, I could always set all of the details tags to open and we can let the scrolling commence again!

**Comment by dustymc** [comment]
>CSS is a MUST

Yes, but there's a lot of room between "make WIDGET all look the same" (essentially where we are, or are trying to be, now) and "fully embrace something like bootstrap."

**Comment by Jegelewicz** [comment]
Agree - even from the little I have picked up in the last two weeks!

**Comment by dustymc** [comment]
https://groups.google.com/g/arctos-working-group/c/dUnvhmCZHdA

>mobile devices

There's a perhaps-compelling reason to use something like bootstrap (and underlying code that sufficiently lets it do it's thing) - mobile UI is ~an extra FTE without some sort of framework, just magically happens with. (Assuming that code lets it, and ours probably doesn't, but it could.)

I wonder if we could sell an accessibility proposal (that incidentally upgrades our UI) somewhere? https://www.w3.org/WAI/standards-guidelines/mobile/#intro

**Comment by Jegelewicz** [comment]
> accessibility proposal

Pretty sure we could - especially on behalf of the cultural collections via Humanities funding.

You cutting me off?


  | An error occurred while processing this page! Message: Error invoking external process Detail: error: The requested URL returned error: 403 Forbidden  while accessing  https://dustymc:cWC6OlkbYzsN@github.com/ArctosDB/PG.git/info/refs fatal: HTTP request failed   Check the Arctos Handbook for more information on errors.   This message has been logged as 984CDC3B-3FEB-46C1-8C7D1D286A4AE80E Please contact us with any information that might help us to resolve this problem. For  best results, include the error and a detail description of how it came  to occur in the Issue.

**Comment by Jegelewicz** [comment]
From http://test.arctos.database.museum/Admin/gp.cfm

**Comment by dustymc** [comment]
Yes apparently, but not on purpose - that was my old pwd you pasted in, so probably good thing I guess....

its updated

**Comment by Jegelewicz** [comment]
I am stumped! Maybe you have an idea.

After adding a publication on the editTaxonomy page, I am returned to the page:

```
<cflocation url="editTaxonomy.cfm?Action=editnoclass&taxon_name_id=#taxon_name_id#" addtoken="false">
```

But all of the details are closed by default. What I want, is to be returned to the page with the publication details (the situation I had when I hit "save") open, which this script will do:

```
function Openpubview() {
            document.getElementById("pubview").open = true;
        }
```

Can I get that thing to run automagically when I am returned to "editTaxonomy.cfm?Action=editnoclass&taxon_name_id=#taxon_name_id#"  from "newTaxonPub"?

**Comment by dustymc** [comment]
See https://github.com/ArctosDB/arctos/issues/3310#issuecomment-747672672 - somehow you have to set/read/act on a variable of some sort to do that. You might be able to dig referrer out of CGI, but that'll only work if the workflow is what you anticipate (and there are a LOT of access points to most of Arctos). This is one of the many things some sort of framework would simplify.

**Comment by Jegelewicz** [comment]
Ask for more when "viewing metadata" - open next 10? Get a list outside of Arctos? How can we make better use of this for cleanup?

Still wants smaller map

Put link up at top like in edit taxon

@sharpphyl will leave more comments

**Comment by sharpphyl** [comment]
@Jegelewicz   I probably need an update on exactly where we are in this process.  Here's what I recall.

 > Still wants smaller map

Or alternatively have it start closed with a down arrow if I want to see the map.  Or small with the option to make it larger.

Also the external validation chart is not shown if there are no Arctos records using the name as an identification.  Having it available is helpful.

Having the local source classifications grouped first with the non-local would be very helpful pending #3311
