### ISSUE TITLE
Reminder bot not working

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3312]
@mkoo I used to use the /remind function here in Github a lot but as of today it doesn't seem to be working anymore. Have we removed it from our repository?

**Comment by mkoo** [comment]
it's still installed so not sure why it's failing you!

this is their repo: https://github.com/probot/reminders

**Comment by mkoo** [comment]
ok the app has been dead... I'll dig around a little bit more but dont take
it personally!
https://github.com/probot/reminders/issues/51

**Comment by Jegelewicz** [comment]
OK - no worries. If it's dead, we don't need to try to bring it back (no zombies, please...)
