### ISSUE TITLE
Common name cut-off, needs to be expandable

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3313]
When there are a lot of common names associated with a taxon, they get cut off on the taxon page:

![image](https://user-images.githubusercontent.com/5725767/102674279-b8e3e980-4152-11eb-948d-ac4f6e9c15d6.png)

You can see them all when you edit:

![image](https://user-images.githubusercontent.com/5725767/102674258-aa95cd80-4152-11eb-8cce-678d1322217c.png)

We should have a way to expand them on the taxon page.

**Comment by dustymc** [comment]
You can scroll

**Comment by Jegelewicz** [comment]
HA! Who knew - why is the scrolly-thing so far away?

![image](https://user-images.githubusercontent.com/5725767/102674477-60611c00-4153-11eb-93e7-8c4bff32c47d.png)

**Comment by Jegelewicz** [comment]
I changed the width of the common name block to make the scroll bar more visible.
