### ISSUE TITLE
Events in search results

### ISSUE THREAD

**Issue by krgomez** [ArctosDB/arctos#3315]
**Describe the bug**
Event type and its data are displaying inconsistently in search results for me. It used to be that only creation (previously manufacture) events would be included by default. Only if I specified in my search that I wanted depiction events to be included would those display. Now, without specifying any event information, I get a mix of creation and depiction event data (as well as still some manufacture events?). It looks to me like this is happening when there is no locality data for the creation event and there also happens to be a depiction event that does have locality data.

**Expected behavior**
I expect only creation events to be included by default.

**Screenshots**
![Screen Shot 2020-12-22 at 10 27 52 AM](https://user-images.githubusercontent.com/40579515/102926046-d231b200-4440-11eb-8af5-221814eacdc9.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac Big Sur 11.1
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 83.0

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.
?

**Comment by dustymc** [comment]
https://github.com/ArctosDB/PG_DDL/blob/master/function/getpriorityspecimenevent.sql updated
