### ISSUE TITLE
newWinLocal links

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3316]
OK, we have a mechanism (and it's scattered around transactions).

Links of class ``newWinLocal`` should all open in a new tab.

``newWinLocal`` is defined in the css, but as of now has no attributes - if anyone wants to make some styling I can add it to the CSS.

@Jegelewicz I updated https://handbook.arctosdb.org/how_to/developer-guide.html - the ``external`` URLs just got a bit simpler and more predictable.

_Originally posted by @dustymc in https://github.com/ArctosDB/arctos/issues/3250#issuecomment-736719233_

**Comment by Jegelewicz** [comment]
I added some styling to this class of links. They now include an information icon and I'd like to use this styling for links to information (mostly code tables) within arctos.museum

**Comment by Jegelewicz** [comment]
@dustymc I hijacked newWinLocal for internal information. I have created new CSS style for links to the handbook and for links that take you somewhere to DO something. Can we make those two classes (.handbook and .godo) also always open as target="_blank"?

You can see all of the stuff I did at http://test.arctos.database.museum/taxonomy.cfm

I'm also thinking I would like to do something for the "links that auto enter stuff", but maybe they can stay the way they are....

**Comment by Jegelewicz** [comment]
BTW - one thing that has me stumped is the "visited" icons, which do not change to the purple version for any of these. WHY?!

**Comment by dustymc** [comment]
reopening @mkoo @Jegelewicz 

* do we need this?
* when do we use it?
* when do we use ``external``

**Comment by mkoo** [comment]
Closing in favor of new issue in doc-wiki repo https://github.com/ArctosDB/documentation-wiki/issues/306
