### ISSUE TITLE
Code Table Request - Bird Banding Laboratory

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#3317]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Goal**
Should we add the Bird Banding Laboratory (BBL) to the ctcoll_other_id code table? At the moment the only mention of band in the code table is for:
USFWS
![Untitled_BBL Code table](https://user-images.githubusercontent.com/18562884/103049508-2925ad00-454f-11eb-9abd-83105b522c16.png)

The BBL is actually part of the USGS (https://www.usgs.gov/centers/pwrc/science/bird-banding-laboratory?qt-science_center_objects=0#qt-science_center_objects), and their band numbers are unique individual identifiers.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type

**Value**
Bird Banding Laboratory (BBL)

**Definition**
Unique identifier found on bands supplied by the USGS Bird Banding Laboratory. May be metal or colored plastic bands. Information on bands can be found through: https://www.usgs.gov/centers/pwrc/science/bird-banding-laboratory?qt-science_center_objects=0#qt-science_center_objects

**Collection type**
Bird

**Attribute data type**
categorical

**Other ID BaseURL**
https://www.usgs.gov/centers/pwrc/science/bird-banding-laboratory?qt-science_center_objects=0#qt-science_center_objects
and
https://www.pwrc.usgs.gov/BBL/bblretrv/

**Comment by campmlc** [comment]
Sounds reasonable!

**Comment by Jegelewicz** [comment]
Agree

**Comment by dustymc** [comment]
Can you provide an example of a functional URL? I can't make your base do anything interesting.

**Comment by ewommack** [comment]
What type of URL to connect to what? The BBL site, info on banding and permits?
The BBL does not provide access to their digital database except by request, so I'm not sure we could get traceable links to each band number unless we dig deep into a collaboration with the BBL.

**Comment by dustymc** [comment]
>traceable links to each band number 

Yes that - if that's not available then base_url should be NULL. I updated the issue template to hopefully clarify that.

"USGS Bird Banding Laboratory" seems less ambiguous to me, but ?? Would someone from {pick a country} know what "Bird Banding Laboratory (BBL)" means?

**Comment by Jegelewicz** [comment]
> "USGS Bird Banding Laboratory" seems less ambiguous to me

Agree that this would be a better value as there could be other bird banding labs.

**Comment by ewommack** [comment]
Sorry for the confusion on the base_url @dustymc! Someday I would love to get the BBL to help figure out a way to share data between them and museums. I just know that it is going to be a really long-drawn out process, and it would be great to just have a way to save the band numbers in Arctos so that they are easily searchable for that magical day in the future.

I think USGS Bird Banding Laboratory (BBL) is probably the most accurate. It is a bit confusing, because they actually cover both the US and Canada (as repository for data, but I think Canada issues its own permits). If you work in birds with banding in NAmerica I think you will understand the acronym BBL, and tying it to the USGS Bird Banding Laboratory will help clarify that the central organization for NAmerica is what we are referring to.


Fun fact, they just turned 100! Here's the brief history I could dig up (https://www.usgs.gov/news/usgs-celebrates-100-years-bird-banding-lab):

> The Bird Banding Laboratory is part of a network of collaborators. It was created in 1920 after ratification of the Migratory Bird Treaty Act with the United Kingdom and administered by the U.S. Department of Agriculture. The lab was moved under the U.S. Fish and Wildlife Service when the agency was established in 1940, transferred to the National Biological Service in 1993 and moved to the USGS in 1996.

> The U.S. and Canada coordinate their banding work through the North American Bird Banding Program, jointly administered by the USGS lab and the Canadian Wildlife Service Bird Banding Office.

**Comment by dustymc** [comment]
>for that magical day

Yep, that's why I don't object to this, there's realistic potential for coolness.

>clarify ... what we are referring to.

Yep, that's the goal - I just want to avoid anything that might entice Arctos users in Hong Kong to pick the wrong type, which would become important when and if that magical day arrives.

Yes sharing data would be awesome, let me know when they have an API....

Added.
