### ISSUE TITLE
Suggested changes to media widget

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3320]
I made some changes to the media widget while working on the taxon name page. Please go to test and look at stuff with media and let me know if you really dislike something!

For your entertainment, here are before and after:

Media on taxon page
 Before | After 
 -- | -- 
![image](https://user-images.githubusercontent.com/5725767/103107315-46638580-45fa-11eb-80ad-61b5d60a494d.png) | ![image](https://user-images.githubusercontent.com/5725767/103107322-5d09dc80-45fa-11eb-81e7-cbe45f3382c5.png) 

(nothing is missing - one of the images isn't set up in test...

Media on catalog record page
 Before | After 
 -- | -- 
![image](https://user-images.githubusercontent.com/5725767/103107357-a823ef80-45fa-11eb-9117-3bb786da9ab5.png) | ![image](https://user-images.githubusercontent.com/5725767/103107365-b96cfc00-45fa-11eb-9f77-741af8aac07f.png) 

Media on Agent Page
 Before | After 
 -- | -- 
![image](https://user-images.githubusercontent.com/5725767/103107384-f3d69900-45fa-11eb-8619-779653deece9.png) | ![image](https://user-images.githubusercontent.com/5725767/103107398-18cb0c00-45fb-11eb-8947-4b22da492bf4.png) 

Media on a Project Page
 Before | After 
 -- | -- 
![image](https://user-images.githubusercontent.com/5725767/103107423-516ae580-45fb-11eb-9f4f-1516c812d653.png) | ![image](https://user-images.githubusercontent.com/5725767/103107431-6e071d80-45fb-11eb-913d-8a85ed55fda0.png)

Media is also associated with transactions, so please look there too.

**Comment by dustymc** [comment]
The layout is broken.

Prod:

<img width="1212" alt="Screen Shot 2020-12-30 at 12 27 44 PM" src="https://user-images.githubusercontent.com/5720791/103379440-82836400-4a9a-11eb-9935-226375b80aa1.png">

test:
<img width="1103" alt="Screen Shot 2020-12-30 at 12 27 36 PM" src="https://user-images.githubusercontent.com/5720791/103379469-8c0ccc00-4a9a-11eb-8262-198691b264e4.png">

**Comment by Jegelewicz** [comment]
That was on purpose. But I can re-center it. On a not-ginormous screen, it looks like this:

![image](https://user-images.githubusercontent.com/5725767/103384309-31339e80-4ab3-11eb-92ca-2d5764c74413.png)
 
which I prefer as opposed to having all that white space on the left.

**Comment by dustymc** [comment]
>ginormous screen

It's a 7 year old 15 inch laptop....

I just spent way too long looking for the controls on an agent page. I vote to somehow closer associate media and controls.

<img width="1057" alt="Screen Shot 2021-01-07 at 8 49 20 AM" src="https://user-images.githubusercontent.com/5720791/103919751-44eb9000-50c5-11eb-9cb6-184485f830e7.png">

**Comment by Jegelewicz** [comment]
Alignment is center again.

**Comment by dustymc** [comment]
@Jegelewicz see the place-media on eg https://arctos.database.museum/guid/MVZ:Bird:185598 - something in the new layout is not working.

**Comment by Jegelewicz** [comment]
It does look weird, but it is presenting the media. How SHOULD it look?

**Comment by dustymc** [comment]
Not sure - I think maybe a border would help?? Less wrapping (but that'll break something else somewhere, probably)?

**Comment by Jegelewicz** [comment]
OK - I'll mess around a bit and see what I can do.

**Comment by Jegelewicz** [comment]
Adding the border doesn't change anything. The wrapping is the same for ALL media widgets, so yes, that would make other stuff weird. Interestingly enough - I think this has ALWAYS been like this and maybe it is the right-alignment of the map that makes this look funky? I am making the assumption that "locColEventMedia_#specimen_event_id#_#collecting_event_id#_#locality_id#" and "colEventMedia_#specimen_event_id#_#collecting_event_id#_#locality_id#" are the two image galleries.

```<tr>
														<td valign="top" colspan="2">
															<div id="locColEventMedia_#specimen_event_id#_#collecting_event_id#_#locality_id#"></div>
															<div id="colEventMedia_#specimen_event_id#_#collecting_event_id#_#locality_id#"></div>
														</td>
													</tr>
												</table>
											</td>
											<td valign="top" align="right"><!---- map here --->
												<cfif len(dec_lat) gt 0 and len(dec_long) gt 0>
													<cfset coordinates="#dec_lat#,#dec_long#">
													<input type="hidden" id="coordinates_#specimen_event_id#" value="#coordinates#">
													<input type="hidden" id="error_#specimen_event_id#" value="#err_in_m#">
													<div class="#session.sdmapclass#" id="mapdiv_#specimen_event_id#"></div>
													<span class="infoLink mapdialog">map key/tools</div>
												</cfif>
											</td>
										</tr>

**Comment by dustymc** [comment]
> assumption that "locColEventMedia_#specimen_event_id##collecting_event_id##locality_id#" and "colEventMedia_#specimen_event_id##collecting_event_id##locality_id#" are the two image galleries.

Those are containers into which the media are injected.

Stuff's just all sorta jumbled up in there, a border/background/grouping of some sort would help me tell what's what. 

I don't think the table alignment is playing a part.

**Comment by Jegelewicz** [comment]
I agree, stuff is jumbled up and I don't understand why we have so many nested tables. I have added comments to the code to try to sort through it. I think we need to re-organize the way the coordinates, elevation, depth, map and event and locality media are presented in the table. Before I do anything, I'd like your opinion on the existing nested table structure.

``` 
<!---- Event Table Row 19 Associated Species ---->
							<cfif len(one.associated_species) gt 0>
							<div class="detailBlock">
								<tr class="detailData">
									<td id="SDCellLeft" class="innerDetailLabel">Associated Species:</td>
									<td id="SDCellRight">#one.associated_species#</td>
								</tr>
							</div>
						    </cfif>
							<!---- Event Table Row 20 A bunch of stuff mashed together ---->
                            <tr>
								<td colspan="2">
                                    <!--- first cell of event table row 20 is the Coordinates table --->
									<table width="100%">
                                        <!---- Coordinates Table Row 1 Lat Lon ---->
										<tr>
											<td valign="top" align="right"><!---- text stuff here what is this for? ---->
                                                <!--- first cell of Coordinates table row 1 is another table, why? ---->
												<table width="100%">
                                                    <!--- first row of second coordinates table, finally, we present the coordinates --->
													<tr>
														<td align="right" valign="top">Coordinates:</td>
														<td align="left">
															<cfif len(dec_lat) gt 0 and len(dec_long) gt 0>
																#dec_lat# / #dec_long#
																<cfif oneOfUs is 1>
																	<a href="/info/localityArchive.cfm?locality_id=#locality_id#">history</a>
																</cfif>
															<cfelseif
																len(s$dec_lat) gt 0 and
																len(s$dec_long) gt 0 and
																oneOfUs is 1 and
																len(locality_name) is 0>
																<input
																	type="button"
																	class="insBtn"
																	onclick="loadEditApp('specLocality_forkLocStk.cfm?specimen_event_id=#specimen_event_id#&magicCoordinates=true;');"
																	value="Click here then save for Magic Coordinates">
															</cfif>
															<cfif len(verbatim_coordinates) gt 0>
																<div class="detailCellSmall">
																	Verbatim Coordinates: #verbatim_coordinates#
																</div>
															</cfif>
															<cfif len(DATUM) gt 0>
																<div style="font-size:.8em;">
																	Datum: #DATUM#
																</div>
															</cfif>
															<cfif len(MAX_ERROR_UNITS) gt 0>
																<div style="font-size:.8em;">Error: #MAX_ERROR_DISTANCE# #MAX_ERROR_UNITS#</div>
															</cfif>
															<cfif len(georeference_source) gt 0>
																<div style="font-size:.8em;">Georeference&nbsp;Source: #georeference_source#</div>
															</cfif>
															<cfif len(georeference_protocol) gt 0>
																<div style="font-size:.8em;">Georeference&nbsp;Protocol: #georeference_protocol#</div>
															</cfif>
															<cfif len(wkt_media_id) gt 0>
																<div style="font-size:.8em;">WKTMediaID: <a href="/media/#wkt_media_id#" target="_blank">#wkt_media_id#</a></div>
															</cfif>

														</td>
													</tr>
                                                    <!--- second row of second coordinates table, Elevation --->
													<cfif len(orig_elev_units) gt 0>
														<tr>
															<td align="right">Elevation</td>
															<td align="left">#minimum_elevation# to #maximum_elevation# #orig_elev_units#</td>
														</tr>
													</cfif>
                                                    <!--- third row of second coordinates table, Depth --->
													<cfif len(DEPTH_UNITS) gt 0>
														<tr>
															<td align="right">Depth:</td>
															<td align="left">#MIN_DEPTH# to #MAX_DEPTH# #DEPTH_UNITS#</td>
														</tr>
													</cfif>
                                                    <!--- fourth row of second coordinates table, Media --->
													<tr>
														<td valign="top" colspan="2">
															<div id="locColEventMedia_#specimen_event_id#_#collecting_event_id#_#locality_id#"></div>
															<div id="colEventMedia_#specimen_event_id#_#collecting_event_id#_#locality_id#"></div>
														</td>
													</tr>
                                                    <!--- end of second coordinates table --->
												</table>
											<!--- end of first cell of Coordinates table row 1 table ---->
                                            </td>
                                            <!---- Coordinates Table Row 1, column 2 Map ---->
											<td valign="top" align="right"><!---- map here --->
												<cfif len(dec_lat) gt 0 and len(dec_long) gt 0>
													<cfset coordinates="#dec_lat#,#dec_long#">
													<input type="hidden" id="coordinates_#specimen_event_id#" value="#coordinates#">
													<input type="hidden" id="error_#specimen_event_id#" value="#err_in_m#">
													<div class="#session.sdmapclass#" id="mapdiv_#specimen_event_id#"></div>
													<span class="infoLink mapdialog">map key/tools</div>
												</cfif>
											</td>
										</tr>
									</table>
								</td>
							<!---- end of Event Table Row 20 A bunch of stuff mashed together ---->
```

**Comment by dustymc** [comment]
I do a LOT with the identifiers in that table, they need to be very carefully preserved. I don't think it should matter where they are in relation to other stuff.

I recommend saving a copy of the entire file before you start messing with anything, just in case something stops working in some unforeseen use case.

Beyond that, oh please! That table is largely a product of evolution, a little intelligent design would be most welcome.

**Comment by Jegelewicz** [comment]
OK - if time permits, I will look at this next week.

**Comment by Jegelewicz** [comment]
@dustymc I think I've done what I came to do here and I am OK with how the widget looks. Closing. If you see something that needs fixing, please re-open.
