### ISSUE TITLE
DOI error on adding publication

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#3321]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Error returned on a valid DOI when trying to add publication

**To Reproduce**
1. Go to "New Publication"
2. Enter DOI https://doi.org/10.3133/pp101 and click crossref
3. I added in the authors and corrected the publication year
4. clicked "create publication" and got error

**Expected behavior**
The publication should add

**Screenshots**
![image](https://user-images.githubusercontent.com/47402809/103249425-5ea21000-492c-11eb-80bb-beace3f9232c.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 84.0.1

**Additional Context**
The DOI does work and I searched Arctos for the publication name and DOI in Arctos and found no matches before trying to add it.

**Comment by dustymc** [comment]
https://handbook.arctosdb.org/documentation/publications.html#doi

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks! I should know by now to double check the documentation : /
