### ISSUE TITLE
Help with Mammals Bulkload

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/arctos#3322]
I am convinced that Arctos hates me and I will never be able to do anything in it without assistance!  After thoroughly going over my Mammals spreadsheet, the bulkloader refused every last record for a multitude of reasons too long to repeat here.  I have attached the file in excel, which I saved as a CSV for bulkloading.  (I can email that file if necessary.)  

I honestly don't understand what I need to do with this file except that apparently each record has a multitude of problems associated with it.  If someone wants to help me figure this out, I would greatly appreciate it.  I'm sorry to interrupt your holiday, but as you can see, mine is already off to a bad beginning.
[ZV1987.0003 Single record copy.xlsx](https://github.com/ArctosDB/arctos/files/5751418/ZV1987.0003.Single.record.copy.xlsx)

**Comment by campmlc** [comment]
I'll take a look at it and get back to you! Without looking at it, one
thing to check immediately that will throw a ton of errors is if your
accession isn't formatted correctly and so isn't recognized.

**Comment by mbprondzinski** [comment]
Really?  Oh for heavens sake.  I guess everything needs to be left, correct?  Thanks, Mariel...
I'll fix that for now, but let me know what else I've done wrong!  No rush...

Mary Beth

**Comment by campmlc** [comment]
Also, make sure your attribute values are standardized, including
capitalization. You have both adult and Adult for age class, and it should
be adult, I believe. Also don't capitalize Unknown. I like to open a data
entry page and test values there while working in the bulkload file, to
make sure values are correct per the code tables.
Can you send a download of the file with errors?

**Comment by campmlc** [comment]
Also, you have a double entry for catnum 899, with one having a blank in
the catnum field. Arctos will deal with the blank by assigning a number, so
you may want to choose a number in advance to differentiate the duplicates,
while keeping the institutional catalog numbers the same,  if they are
indeed two different records.

**Comment by mbprondzinski** [comment]
Okay, Mariel.  I know that unknown shouldn't be capitalized.  I have since fixed those.  Don't know what is missing from the Accession?  It was left justified, so that's not a problem.  Does it need a guid?
I've attached the errors file.  Good luck!

Mary Beth

**Comment by mbprondzinski** [comment]
Okay, that blank record should have been deleted.  Every record originally had a duplicate:  one for skin and another for skull, but I eliminated all the dupes and moved the skin/skulls to another attributes file.

**Comment by campmlc** [comment]
Try adding the accession to a test record in data entry and see what format
Arctos generates for you to select.

**Comment by mbprondzinski** [comment]
Okay, I figured that out...thanks.
