### ISSUE TITLE
Code Table surprise

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3327]
"Falcon tube" popped in as a new container type, I don't see any discussion, the documentation suggests the term is unnecessarily specific.

https://handbook.arctosdb.org/how_to/How-To-Request-A-Code-Table-Change.html
https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html
https://github.com/ArctosDB/arctos/issues/2326

How do we react to this, and how do we prevent this situation going forward?

**Comment by campmlc** [comment]
I entered it as I critically needed to move materials yesterday, but it was
pointless as the value did not show up after creation and so could not be
used. Falcon tube is a legit container type that should require no
discussion. These are large plastic tubes with a screw top, in common
usage. Calling them test tubes would be misleading. Something this simple
should not require weeks of discussion.

**Comment by ewommack** [comment]
They are a specific type of tube. Annoyingly large tubes...

**Comment by campmlc** [comment]
I had a box of unexpected vials that needed to be scanned and moved
immediately - sandhill crane eyes frozen in falcon tubes in a freezer box.
They are now scanned in as cryovials into a box that has no positions. This
will come back to cause problems later as I may not get back to it - it was
part of a larger set of problems that needed immediate resolution. Stuff
like this happens frequently, and data and samples get lost as a result.

**Comment by Jegelewicz** [comment]
I changed the reference link to <a href="https://ecatalog.corning.com/life-sciences/b2c/US/en/Liquid-Handling/Tubes,-Liquid-Handling/Centrifuge-Tubes/Falcon%25C2%25AE-Conical-Centrifuge-Tubes/p/falconConicalTubes" class="external">Corning</a>

And yes, I think that ALL code table requests should be posted to GitHub. The ONLY exception should be adding an already present term to a collection type. I realize that waiting can be frustrating, but three days is not long compared to the "in perpetuity" of collection management.

In this case, I think that using the container type "unknown" would flag stuff that is "unexpected" and "needs to be moved immediately". Then anyone would know that these containers need to be reviewed and updated when time is available.
