### ISSUE TITLE
outage contact

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3329]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
https://arctosdb.org/ ``Trouble with Arctos? Let us know ASAP!`` is a mailto link that goes to a private group.

**To Reproduce**
* try to report an outage, or
* use gmail rather than a OS client 

**Expected behavior**
Just link to Issue report

@mkoo

**Comment by mkoo** [comment]
Fixed with new arctoscontact@googlegroups.com
Members (officers and programmers) should've gotten a bunch of test emails that can be ignored and deleted. Swapped out the old email link with the new on the Contact page and footer. Sprinkle elsewhere as needed.
