### ISSUE TITLE
"Creator" button needed in Tools-Customize to display at search results

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#3330]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Maker --> Creator resulted in customized search results showing no data for Maker. There is no creator field to add in the customize box. Please change maker to creator in the customize box so we can add this field to search results and see who made our stuff!

**To Reproduce**
1. Go to https://arctos.database.museum/saved/Firearms

2. 
<img width="1196" alt="Screen Shot 2021-01-05 at 2 47 16 PM" src="https://user-images.githubusercontent.com/17605945/103712898-6b93b480-4f67-11eb-9736-157f792ae3b8.png">

3. Open record and see there is a creator listed:
<img width="1173" alt="Screen Shot 2021-01-05 at 2 51 33 PM" src="https://user-images.githubusercontent.com/17605945/103712925-7bab9400-4f67-11eb-89ba-859ddcfafcd8.png">

4. See that there is no creator in customize tool box:
<img width="726" alt="Screen Shot 2021-01-05 at 2 47 02 PM" src="https://user-images.githubusercontent.com/17605945/103712958-8f56fa80-4f67-11eb-8690-49b1aba72cc7.png">

**Expected behavior**
The information that previously displayed in Maker column should be accessible via Creator, which needs to be added to the customize box.

**Priority**
Super high priority! Makes us look like we don't know our stuff!

**Comment by dustymc** [comment]
I just changed maker, https://github.com/ArctosDB/arctos/issues/2938 still needs resolved and this will need - well, something, probably...

FYI all of these people can do this:

manage_documentation

    campmlc (open)
    ccicero (open)
    dlm (open)
    ekrimmel (locked)
    ffdss (open)
    gordon (locked)
    jbwilliamson (open)
    jegelewicz (open)
    lam (open)
    lbroskey (locked)
    mkoo (open)
    sbirks (locked)
    uam (locked)


(But who's jbwilliamson and who gave them rights?? I'll remove some of that...)
