### ISSUE TITLE
Bulkloading relationships

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#3337]
Trying to add new relationships (collected with) between some of our parasites and the load fails with this error:

load fail::ERROR:   permission denied for table cf_temp_oids
--
![image](https://user-images.githubusercontent.com/12507297/103948218-a8da7c80-50f6-11eb-97f6-97dc3dd12eb9.png)

I have used this loader before and not had permission issues. Here's my file:
[DMNS_Para_collectedwith.zip](https://github.com/ArctosDB/arctos/files/5784086/DMNS_Para_collectedwith.zip)

**Comment by dustymc** [comment]
Woops - should be patched.

**Comment by acdoll** [comment]
Quickest fix ever! Thanks

**Comment by acdoll** [comment]
All loaded!
