### ISSUE TITLE
Link parts in record detail page header to parts table at bottom of detail page

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3339]
At the loans are cumbersome meeting yesterday it was noted that those looking for items to borrow don't always check the available parts even though they are listed at the top of the record detail page:

![image](https://user-images.githubusercontent.com/5725767/104043899-bdbc1c00-5199-11eb-9671-e686e6f18c57.png)

and now that parts have been moved to the bottom of the page, this will probably be even more problematic.

It was suggested that the summary part list in the detail page header be prefaced by "Parts" in bold and link to the parts table below.

**Comment by Jegelewicz** [comment]
@dustymc I made an attempt at this, but I can't figure out how to make the link work with the details body template.

However, I wonder if it wouldn't be an even better idea to include a "jump to" bar for non-operators like we do for those with editing power:

![image](https://user-images.githubusercontent.com/5725767/104045464-d5949f80-519b-11eb-9c9c-3affc00a4dc9.png)

The links shown above all go to "edit" forms and this bar is only visible when you are logged in as an operator. How about the same bar for non-operators that just jumps you to the appropriate section of the detail page?

Just a thought - may be overkill since you can usually see most of the sections anyway (unless there is media - that could push locality out of the page).

![image](https://user-images.githubusercontent.com/5725767/104045739-39b76380-519c-11eb-9c89-f03384bb28b9.png)

**Comment by dustymc** [comment]
I made your link work. The idea is to fit everything on an "average" screen - I'd rather mess with the collapse or similar than add more clutter, but sticking something in the other side of that IF wouldn't be difficult.

**Comment by Jegelewicz** [comment]
Cool - what was I doing wrong?

**Comment by dustymc** [comment]
I just added an ID to serve as an anchor - ``<div class="detailCell" id="partsTbl">``

**Comment by Jegelewicz** [comment]
DOH! I see that I didn't add the id I was trying to use - sheesh!
