### ISSUE TITLE
Project page image thumbnails say media isn't available, but shows up on detail page

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#3341]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
My media on the project page is showing "media thumbnail unavailable", but it shows up when you look at the individual media record

**To Reproduce**
On project page:
https://arctos.database.museum/project/10003348

Individual record (thumbnail is showing up): https://arctos.database.museum/guid/UTEP:Herb:4824

**Expected behavior**
For thumbnails to show up on the project detail page.

**Screenshots**
Project page: 
![image](https://user-images.githubusercontent.com/38706617/104066026-ef46de80-51bd-11eb-9ccf-ef3584a1dbc9.png)

individual media record: 
![image](https://user-images.githubusercontent.com/38706617/104066074-05549f00-51be-11eb-8dcb-0c921197b5a8.png)

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by dustymc** [comment]
<img width="1010" alt="Screen Shot 2021-01-08 at 2 29 38 PM" src="https://user-images.githubusercontent.com/5720791/104071402-f4a42900-51bd-11eb-9c47-75909379c7bc.png">

I think it's TACC's firewall - it's been up and down 19574 times today, that's probably making the thumb-tester angry.

**Comment by mvzhuang** [comment]
Ah got it. Thanks Dusty!
