### ISSUE TITLE
Error on Create Container Series

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3344]
I'm getting a 500 Internal Server Error when trying to create containers using Create Container Series. I've broken down the 150,000 barcodes to create as cryovial labels into three bukload files of 50,000 records each, which the what the tool recommends.  I need these created as soon as possible - any chance @dustymc can load for me, please?
[CreateContainerTemplate_Fall2020series.zip](https://github.com/ArctosDB/arctos/files/5793457/CreateContainerTemplate_Fall2020series.zip)

**Comment by dustymc** [comment]
Send the single file please

**Comment by campmlc** [comment]
[CreateContainerTemplate_1.zip](https://github.com/ArctosDB/arctos/files/5796547/CreateContainerTemplate_1.zip)
[CreateContainerTemplate_2.zip](https://github.com/ArctosDB/arctos/files/5796548/CreateContainerTemplate_2.zip)
[CreateContainerTemplate_3.zip](https://github.com/ArctosDB/arctos/files/5796549/CreateContainerTemplate_3.zip)

**Comment by dustymc** [comment]
Do you have an unsplit single file?

**Comment by campmlc** [comment]
[CreateContainerTemplate_Fall 2020 all.zip](https://github.com/ArctosDB/arctos/files/5797430/CreateContainerTemplate_Fall.2020.all.zip)

**Comment by dustymc** [comment]
That failed here:

```

arctosprod@arctos>> select barcode from cf_temp_container where barcode in (select barcode from container where barcode is not null);
 barcode 
---------
 AB8BN
 AB8BO

```

**Comment by campmlc** [comment]
Can you remove those? They were probably created manually by our fish CM.

**Comment by dustymc** [comment]
>remove

Yup, was just worried that they might be an indication of deeper problems. It's done.

**Comment by campmlc** [comment]
Thanks!
