### ISSUE TITLE
Problems viewing media by public user

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#3346]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

A member of the public to whom I sent direct links to catalog records (https://arctos.database.museum/guid/UAM:EH:0697-0001, https://arctos.database.museum/guid/UAM:EH:0697-0002, https://arctos.database.museum/guid/UAM:EH:0697-0003, https://arctos.database.museum/guid/UAM:EH:UA66-064-0001AB, https://arctos.database.museum/guid/UAM:EH:UA67-030-0013) replied saying he got the following error message:

> I tried to look at the photos/drawings, but got this message instead
> "The owner of arctos.database.museum has configured their website improperly. To protect your information from being stolen, Firefox has not connected to this website."

Do we know what the problem is and how I can help him solve it? Is this connected to the earlier problems we were having with media files? I've noticed in the last week or so intermittent problems seeing the thumbnails of my media both at the search results & in the catalog record detail page.

**Priority**
Critical - this is preventing researchers from accessing our media (or more?)

**Comment by dustymc** [comment]
That sounds like someone is manipulating their network traffic. There should be some sort of "advanced" option with more information that might lead to a firmer answer.

The intermittent outage is not likely to be related - TACC replaced some firewall hardware, that should all be finished.

**Comment by AJLinn** [comment]
> That sounds like someone is manipulating their network traffic. There should be some sort of "advanced" option with more information that might lead to a firmer answer.

Thanks Dusty - I'll have him check for that.
