### ISSUE TITLE
Feature Request - verbatim coordinates in Data Entry

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#3348]
When entering records using the Data Entry page, coordinates are automatically entered into the locality it creates and into the collecting event as verbatim coordinates. This is explained in the documentation:
_Data Entry has (for brevity) one place for coordinate information, and these data are stored as both verbatim (in the collecting event) and locality coordinates. Events and localities may be pre-made and selected when these limitations prevent accurately representing the data_
However, somehow I missed this in my thorough reading of the documentation years ago. So, we now have thousands of records with non-verbatim coordinates, determined by staff/volunteers at the time of data entry, inserted into the verbatim coordinates field.
So, I have two questions:
1) is there a way to bulk-edit collecting events (I don't think so; this would require a manual cleanup, right?)
2) can we change the Data Entry form to prevent this? A simple check box for 'include as verbatim coordinates' would probably suffice (default as checked to keep the existing functionality?). But maybe we should add additional fields for entering both verbatim coordinates and the coordinates that go into the locality record?

@sharpphyl brought this to my attention.

**Comment by dustymc** [comment]
This is addressed in https://github.com/ArctosDB/arctos/issues/2930

**Comment by acdoll** [comment]
Sorry, I initially searched and posted in the wrong repository. Then copied this over here without re-searching. I will monitor 2930 - sounds like we just need a new name for these 'Verbatim Coordinates'; 'As Entered' or something...
