### ISSUE TITLE
Object Tracking Issues

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3349]
I am struggling with several problems with Object Tracking since the move to PG. 

1) Can we move "In Barcode" up next to Barcode in the search panel, and add a link to documentation suggesting when one vs the other should be used? Despite my daily use of object tracking, I cannot keep these tools sorted, and I'm sure others are having the same problem. 

2) It would be exceedingly helpful to merge these two tools, as I cannot think of a situation in which I would enter a list of barcodes and NOT want to be able to expand to see what collection objects they contain.  Inevitably I try to use Barcode Search then Flatten Part Container for this, fail, then try to use Show All Collection Objects, which only works for a single, not multiple, barcode, and then have to go to remember to go to "In Barcode"for my list.  I tried to make an example decision tree [here](https://docs.google.com/spreadsheets/d/1Vv55v03BB0nVgoTg8FJrntPeLiisWWVu4PYSoZtjwT0/edit?usp=sharing).)

3) I need to be able to add all collection objects in a freezer box or ideally, multiple freezer boxes, to a loan. We used to be able to do this. I have scanned items into a loan box for this purpose. It seems we can only do this now if we enter a single barcode in Barcode search, e.g. cryovial,  and go to Flatten. This doesn't work for a list, or for barcodes that are in multiple parent containers. Can we get this tool added to Show All Collection Objects results and also to In Barcode?

2) I need to be able to bulk modify dispositions by barcode. We can do this using the Search Barcode field and then Show All Collection Objects in this Container. But if the parts are scattered in different locations rather than in a single parent, I instead have to use their cryovial barcodes in  "In Barcode", where no such tool exists. Can we get the tool added to both places?

**Comment by dustymc** [comment]
I need to know more about what you're doing, how you got to this point. I can't write effective code unless I understand the big picture, and these things do not make sense to me. I think there's something fundamental that at least one of us isn't understanding, and it's worth discovering what that is before proceeding. 

Where or how were you able to add box contents to a loan?

@DerekSikes how about a high volume barcode based loan magic webinar?

**Comment by campmlc** [comment]
I suggest we schedule a call - this is beyond webinars. Can you tell me
which tools currently have code to add items to a loan? Because I can't
find any but the single barcode show all collection objects search since we
migrated.

**Comment by campmlc** [comment]
These tools are highly relevant to my workflows, and they would provide tools for others. I deal with frozen tissues in freezer boxes and racks, and I while I may only loan out several thousand samples per year, the samples are widely scattered in multiple containers and difficult to track - not organized by taxon in an insect tray. I also send these samples out over 50-70 loans, e.g at least one a week - so there is a lot of data processing. I would like to see these tools standardized and implemented.

**Comment by KyndallH** [comment]
If you do schedule a call, please include me. Thursdays work the best for me but I can also do after 2:30 AKST MWF.

**Comment by dustymc** [comment]
>schedule a call 

Agree - next Issues meeting?

>which tools currently have code to add items to a loan?

I'll try to track them down, would be useful documentation.

**Comment by Jegelewicz** [comment]
@campmlc how many of these problems still exist for you? Can we separate them out into individual issues?
