### ISSUE TITLE
Feature Request - unify transaction search

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3352]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

See eg https://github.com/ArctosDB/arctos/issues/1965. This is a request to do the same thing in three places, adding this sort of information inevitably leads to wanting more query terms, then wanting to see query options in results, etc.; better access to data inspires requests for better ways of viewing data. All of that has to be done in multiple places, often with some variation in how it's done. It's a LOT of work and leads to inconsistent forms - loans can be searched by X, accessions cannot, accession results contain Y and loans do not, etc. etc.

Also there's currently no obvious way to get at things like "show me [agent's | collection's | this year's ] transactions" - everything is siloed by transaction type.

**Describe what you're trying to accomplish** 
Make transaction forms easier to maintain and transaction data easier to access.

**Describe the solution you'd like**
One form that searches and displays search results for all transaction types. This would support all current functionality, but add the ability to specify/ignore transaction type.

**Describe alternatives you've considered**
Maintain way too much code, don't get cool functionality.

**Additional context**
This would simplify anything involving transaction search or search results. Creating, editing, etc. would not be effected; the unified form would just link on to eg edit loan.

Going next task - I know how to do this.

**Priority**
Plz help, AWG.

**Comment by ccicero** [comment]
I'm fine bumping this up in priority as well as #2947. It would help with reporting (permits, institutional, etc.).

**Comment by dustymc** [comment]
See https://github.com/ArctosDB/arctos/issues/2947 - make sure download and map works.

Closing https://github.com/ArctosDB/arctos/issues/2947 and carrying @ccicero 's priority over here.

**Comment by ebraker** [comment]
Agreed. This sounds really useful on all fronts.

**Comment by Jegelewicz** [comment]
YES

**Comment by campmlc** [comment]
Agree!

**Comment by dustymc** [comment]
Please have a quick look at http://test.arctos.database.museum/transactionSearch.cfm

For now, I care only about

* The big-picture layout of the search page
* The big-picture layout of the results page

Please ignore the details for now, I'd just like to know if this is the right idea before I get much deeper.

* Minor details (moving things around, adding stuff, etc.) can come later, if necessary.
* The form is still very easy to break, try something else if your search fails.
* There's a low rowlimit, it'll be increased as this thing solidifies
* It currently handles nothing but loans.

I'll interpret silence as enthusiastic approval.

**Comment by Jegelewicz** [comment]
All of my comments would be related to the page layout. I think that all the stuff at the top are things that coulsd be a part of ANY transaction? FWIW, I think the stuff at the bottom should be at the top and the permit stuff should be clustered together in a block of some sort.

I searched loans for MSB:Mamm and got the max of 100 results, which was expected.

I may be wrong, but I think most permits are associated with accessions, so I failed at searching with any permit info since the form is only searching loans?

Agent Name selection needs to get checked against agents. Although I search for loans authorized by Joseph A. Cook and got the limit of 100, then one for loans authorized by Joe Cook and got the same results - it didn't appear that Arctos did its usual "yep this is an agent" after I entered the name though.

Search by loans due for MSB:Mamm between 2020-01-01 and 2020-12-31 returned two results - I'm guessing that's good given that data in test are stale.

Search by MSB:Mamm in house loans returned 79 - again probably reasonable.

Search by loan number "3012%" returned 36 - probs good

Search by part name = "skin, study" returned max of 100 - seems reasonable until I looked at the items for the first one, which only included "skin" - realized then that the comma in the part name is problematic....

Search on loaned part disposition = "transfer of custody" resulted in this:

> An error occurred while processing this page!
> Message: ERROR: missing FROM-clause entry for table "loan_srch_part" Position: 904
> Detail:
> Check the Arctos Handbook for more information on errors.
> 
> This message has been logged as 55DC3EDD-3E0D-4F7B-8232F94798E8CD9F Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue. 

same for "in collection"

Using the "Require media" widget got me the max results - probably makes sense. A review of the first one in the results show an attached document. I could see where adding the type of associated media might be useful (jpg vs txt...)

Hope that helps.

**Comment by dustymc** [comment]
>I think that all the stuff at the top are things that coulsd be a part of ANY transaction? 

Yes, that's why they're at the top and not in one of the specific blocks at the bottom. See "Also there's currently no obvious way to get at things like "show me [agent's | collection's | this year's ] transactions" - everything is siloed by transaction type." up ^^ yonder.

>stuff at the bottom should be at the top

Easy to do - seems backwards to me, but I don't care.

>permit stuff should be clustered together in a block of some sort.

Yes, it will be, "Minor details"

There are lots of permits on loans, but maybe not for "your" collections.

> it didn't appear that Arctos did its usual "yep this is an agent" after I entered the name though.

EVERY agent search works like that. (Agent picks don't.)

>realized then that the comma in the part name is problematic

Uhh - neat... So we can have values with characters that can't be differentiated from delimiters, or we can allow multiple values, but we can't (ish) do both. Not new anyway, I think....

>loaned part disposition = "transfer of custody"

>The form is still very easy to break, try something else if your search fails.

>adding the type of associated media m

"Minor details...adding stuff" (I'm working on that now, not sure I'll use it for this since the injectable widget is more standardized - but there will be a download with media details - in JSON, because I can find no other sane way of representing complex data in a flat structure, if anyone wants to suggest a better way or just lodge a pre-complaint!)

>Hope that helps.

Yes, thanks!

**Comment by campmlc** [comment]
I just tried searching accessions for MSB:Mamm, and I put transaction date
2020. Got nothing. Tried 2017. No results. Tried 2017-01-10 to 2020-12-31.
No results. I'd like to be able to find all accessions for a given year
without having to type out the full Jan - December ISO dates.

**Comment by campmlc** [comment]
Also, when I click search after choosing those values (accn), the page says
"Loans" "0 results".

**Comment by dustymc** [comment]
>searching accessions 

https://github.com/ArctosDB/arctos/issues/3352#issuecomment-784355603

**Comment by campmlc** [comment]
I tried searching "accn" and "MSB:Mamm: with no date entered - which we
used to be able to do in the old form (it returns 3050 accessions).
Got message below. I don't like a 100 result limit.
Query
Template: /transactionSearch.cfm:863
Execution Time: 37.7 ms
Record Count: 0
Cached: No
Lazy: No
SQL:
select
trans.transaction_id,
concatTransactionAgents(trans.transaction_id)::varchar as transagents,
concatTransactionPermits(trans.transaction_id)::varchar as transpermits,
concatTransactionProjects(trans.transaction_id)::varchar as transprojects,
concatTransactionMedia(trans.transaction_id)::varchar as transmedia,
trans.nature_of_material,
trans.trans_remarks,
trans.trans_date,
loan.loan_number,
loan.loan_type,
loan.loan_status,
loan.loan_instructions,
loan.loan_description,
to_char(loan.return_due_date,'YYYY-MM-DD') as return_due_date,
collection.guid_prefix,
count(distinct(loan_item.collection_object_id)) numberItems
from
trans inner join collection on trans.collection_id=collection.collection_id
inner join loan on trans.transaction_id=loan.transaction_id left outer join
loan_item on trans.transaction_id=loan_item.transaction_id
where
trans.transaction_type = 'accn' and
collection.guid_prefix in ('MSB:Mamm')
group by
trans.transaction_id,
concatTransactionAgents(trans.transaction_id),
concatTransactionPermits(trans.transaction_id),
concatTransactionProjects(trans.transaction_id),
trans.nature_of_material,
trans.trans_remarks,
trans.trans_date,
loan.loan_number,
loan.loan_type,
loan.loan_status,
loan.loan_instructions,
loan.loan_description,
to_char(loan.return_due_date,'YYYY-MM-DD'),
collection.guid_prefix
limit 10

**Comment by dustymc** [comment]
Please read https://github.com/ArctosDB/arctos/issues/3352#issuecomment-784355603

**Comment by campmlc** [comment]
I read that, and I couldn't figure out how that relates to what I am
seeing, other than that is just minor UI details?

**Comment by dustymc** [comment]
There's a low rowlimit, it'll be increased as this thing solidifies
It currently handles nothing but loans.

**Comment by dustymc** [comment]
> permit stuff should be clustered 

done

>part disposition

fixed

>media

now included

**Comment by Jegelewicz** [comment]
> So we can have values with characters that can't be differentiated from delimiters, or we can allow multiple values, but we can't (ish) do both.

Can we use a different delimiter?

**Comment by dustymc** [comment]
>different delimiter?

Comma-separators are baked pretty deep into the HTML Standard - we can certainly cheat, but that's very far from ideal. I don't think it's worth getting too crazy here, unless this form gets a lot of use that I don't know about.

**Comment by dustymc** [comment]
Built some indexes, rewrote some SQL, and optimized some functions, this did in fact eat my browser but not before I was able to get a screenshot:

<img width="526" alt="Screen Shot 2021-02-23 at 1 28 56 PM" src="https://user-images.githubusercontent.com/5720791/108910724-1c6b1700-75db-11eb-89fa-03968fcd8076.png">

If there are no layout change requests fairly soon I'll replicate what I have to accns and borrows.

**Comment by dustymc** [comment]
Added shipments - what else is missing?

**Comment by Jegelewicz** [comment]
I like that there is less scrolling, but

I really do thing the stuff at the bottom will be used more than permit, shipment and media when searching. Most transaction searches are going to be for a specific loan or set of loans. I really think these two sections should be flipped:

![Screenshot 2021-02-23 162458_1](https://user-images.githubusercontent.com/5725767/108922322-25b4ad80-75f4-11eb-9cd4-76b010279da6.jpg)

**Comment by Jegelewicz** [comment]
You know what would be REALLY nifty? Once you select the transaction type, you are offered the options available for it.....

**Comment by dustymc** [comment]
>two sections should be flipped:

Anyone else? It's pretty trivial to do that, we'll go with the silence==enthusiastic approval thing if nobody else has input....

>Once you select the transaction type, you are offered the options available for it....

"Just javascript" probably, but I'm not sure I quite get it either. I think this will open up a lot of new use cases, and that would just hide two tiny panes or ?????????

**Comment by Jegelewicz** [comment]
It could be a page of sorts - first page is just "select a transaction type", then depending on selection you get the rest.

But that might be overkill...

**Comment by Jegelewicz** [comment]
One more nitpick - can each block be aligned to the top?

**Comment by dustymc** [comment]
>first page is just "select a transaction type"

But much of the point is to NOT have that! What I've built supports "find foreign shipments" or "find Teresa's transactions" or "map all institution transactions for the last year" or .... Accessibility good, pigeonholes bad. (Unless you like pigeonholes, then you can specify transaction type.)

>aligned

Yea, I'll get there....

**Comment by dustymc** [comment]
cleaned up the UI
shuffled cells
selecting transaction_type fires off some JS
loaned part takes list,=,%

@acdoll @jldunnum @campmlc @AJLinn @DerekSikes @krgomez @atrox10 @ccicero @cjconroy  you all make lots of transactions (but not as many as Joseph Grinnell!)

http://test.arctos.database.museum/transactionSearch.cfm is a new all-transaction search form

only loans are functional; accession and borrow search forms exist, results will look much like loan (once loans are satisfactory)

This is only search and results - creation/editing forms won't change for now.

How could it be better?

**Comment by Jegelewicz** [comment]
> selecting transaction_type fires off some JS

That's NIFTY! - Maybe a green box instead of yellow? A Bigger ask - HIDE instead of greying out?

> How could it be better?

I think the results parameters block should be at the far left of that row.

Instead of "Parameters", just use "Terms"?

Nifty!
![image](https://user-images.githubusercontent.com/5725767/109030953-82aa7500-7681-11eb-9474-5af12dcaa384.png)

Also I like the navigation that helps avid scrolling!

Suggest these look like .godo buttons - they are taking you to places where you can DO stuff. Or at least don't use the information icon?
![image](https://user-images.githubusercontent.com/5725767/109032340-c8b40880-7682-11eb-9d2b-430633a57cc4.png)

**Comment by dustymc** [comment]
>Maybe a green....

It's just CSS - I'll mess around with it, or you can do whatever and let me know (or just change the source).

You're using a developer browser of some sort, right? You can see/do something like this:

<img width="770" alt="Screen Shot 2021-02-24 at 8 34 27 AM" src="https://user-images.githubusercontent.com/5720791/109033122-28a6b100-767b-11eb-8fbe-f897b24efc2c.png">

>HIDE

That sets you up to...

* enter some accn stuff
* oh, wrong box, change transaction type to loan
* get frustrated because you're searching with parameters that you can no longer see or change

I could just blank-and-hide or something, but I think it's fairly useful to see the options, and it's not like a blank cell would save any screen real estate or etc. (It might under a different layout.)

>should be at the far left of that row

I'll move it - I've got it set up so that's easy to do.

>"Parameters", just use "Terms"?

wilco

>like the navigation that helps avoid scrolling!

You can collapse panes as well.

>buttons

We should have some site guidance. Those are hrefs, accessible design would probably/maybe have them being hrefs, we're of course not very consistent with that sort of thing (there are hrefs that act like buttons in this form....), we should be. Easy enough to tweak in any case, I'll see what it looks like.

>don't use the information icon?

Those are newWinLocal - do we need a new href class?

Thanks!

**Comment by Jegelewicz** [comment]
>     don't use the information icon?
> 
> Those are newWinLocal - do we need a new href class?

These seem like the same thing I have on the Taxonomy page:
![image](https://user-images.githubusercontent.com/5725767/109042324-4f6de300-768d-11eb-8dd3-29f7e6145a91.png)

So maybe format them using that css? input.qutBtn

**Comment by dustymc** [comment]
>	/* quit: go somewhere else without saving any changes */

I suppose that's not WRONG, but I'm not crazy about scary-red button-link-thingees.

.lnkBtn ...

>	/* link; go somewhere not terribly scary */

is probably better, if we do in fact want buttons for links.

I changed one...

```
<a  href="/Loan.cfm?action=editLoan&transaction_id=#transaction_id#"><input type="button" class="lnkBtn" value="Edit Loan"></a>
```

but now it's _self - so new class-handler JS and...

```
<a class="newwin" href="/Loan.cfm?action=editLoan&transaction_id=#transaction_id#"><input type="button" class="lnkBtn" value="Edit Loan"></a>
```

is a href (so should work in screen readers and such) that looks like a button (because it seems maybe we like buttons??) that opens in a new window (because replacing my search results with an exploratory click is annoying).

Hard-reload to get the new JS.

Bueno?

**Comment by Jegelewicz** [comment]
Bueno - but I guess I should change the taxonomy stuff to be consistent...

**Comment by dustymc** [comment]
Buttons are there, queries work, nobody's complaining, I'm adding accns and borrows.

**Comment by campmlc** [comment]
Front end template looks good, but I'm running into a problem generating
reports.

**Comment by dustymc** [comment]
>generating reports.

I'm not sure what that means - there's no reporting in the new form (nor in the old that I can find). Should there be or ??????????????????????

**Comment by campmlc** [comment]
Just went to a loan using the new form and tried to print a loan invoice,
and got that error message. No idea if the problem is related to the search
form changes, but timing is suspicious.

**Comment by dustymc** [comment]
I can't break it - going next release.

**Comment by acdoll** [comment]
Late to the party as usual... but I think this looks and works awesome! I like the search's grid layout with the transaction terms on the top - the way it highlights the selected Transaction Type and greys out the others is (to use Teresa's terminology) _super_ nifty.  The expandable dropdowns are a cool addition (though the Loan Status one is not expanding).  CSV's download nicely. The Map Loan Shipments is awesome - if that's not a new feature I can't believe I haven't used it (I now see the button on regular Arctos, did that used to work?). That will be super helpful in showing use and reach of collections. 
Nice work!

**Comment by dustymc** [comment]
>Loan Status one is not expanding

Reload.

Thanks for the feedback!

**Comment by Jegelewicz** [comment]
> expandable dropdowns

ARE super-nifty, it would be even niftier if I could close them when I decide I don't want multiples.... :-)

**Comment by dustymc** [comment]
>if I could close

You can??

**Comment by Jegelewicz** [comment]
OK - seems like yesterday I couldn't...

NICE

**Comment by Jegelewicz** [comment]
Actually...BADASS this is a HUGE improvement!!!!

**Comment by dustymc** [comment]
>yesterday

That was yesterday....

**Comment by Jegelewicz** [comment]
and all my troubles seemed so far away....

**Comment by dustymc** [comment]
"expandoSelect" is now sprinklable, sorta-green with a hopefully-better icon, and a bit niftier with small lists.

```
<span data-ctl="guid_prefix" class="ui-icon ui-icon-arrow-4-diag expandoSelect"></span>
```
after a select with an ID of ``guid_prefix`` should do magic anywhere in Arctos.
