### ISSUE TITLE
Search by Year in Publication/project Search not working

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#3354]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Search throwing error when trying to search by year. 

**To Reproduce**
1. Go to Publication and Project Search
2. type in a year into Year
3.  Hit Search
5.
![image](https://user-images.githubusercontent.com/38706617/104491671-ce043a80-558f-11eb-91bc-fb45bb6b780f.png)

**Expected behavior**
list publications in that year

**Screenshots**

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**
Windows, Chrome
**Additional context**

![image](https://user-images.githubusercontent.com/38706617/104491803-fb50e880-558f-11eb-9c29-29a82ded23cd.png)

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by dustymc** [comment]
Should work now, until someone creates a new project.

This is caused by some oracleish create code, there will be a patch in the next release, need to check that the cleanup stuck after that's out.
