### ISSUE TITLE
error in creating new shipping address (value too long)

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#3355]
I'm  trying to create a new shipping address and am getting an error that the value is too long (character limit 255?). This is a new error. I added lines one by one, and can save part of the address but if I put in the full address, it gives me the error. See attached screen shot. Can we increase the # characters for shipping addresses?
![Arctos_error_ship_address](https://user-images.githubusercontent.com/967275/104507974-63a5c700-559c-11eb-982f-ec70264105ca.PNG)

**Comment by dustymc** [comment]
Should be fixed, but the thing that was catching you is cached for an hour so grab lunch and then try again....

**Comment by ccicero** [comment]
Thanks!
