### ISSUE TITLE
Create Container Series not working

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#3359]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Create Container Series is saying it'd done loading barcodes, but I can't find them in the universe afterwards

**To Reproduce**
1) Create container series
2) upload csv
3) validate
4) window says done instead of any errors

but when I try to find a container I just uploaded, it says no record found

**Expected behavior**
load barcodes

**Screenshots**

**Data**

sample file
[BarcodesC0000-C1000.zip](https://github.com/ArctosDB/arctos/files/5816069/BarcodesC0000-C1000.zip)

**Desktop (please complete the following information):**
windows chrome

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by dustymc** [comment]
<img width="807" alt="Screen Shot 2021-01-14 at 9 43 56 AM" src="https://user-images.githubusercontent.com/5720791/104628417-1170ae80-564d-11eb-8718-7b2da11ef4b7.png">

I can confirm that everything in the file was created....

**Comment by mvzhuang** [comment]
ack sorry Dusty. I swear those barcodes were in there. closing now.
