### ISSUE TITLE
Feature Request - Outsource Agent management?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3360]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
Not a problem, but a potential asset? In today's collections webinar https://portal.snaccooperative.org/about was introduced. 

**Describe what you're trying to accomplish** 
We do a lot of work managing agents in Arctos - what if we did that management at SNAC instead?

**Describe the solution you'd like**
Look at [Joseph Grinnell's profile on SNAC](https://snaccooperative.org/view/38885915#biography). Why not recruit this community to help us make our Agent profiles even better?

**Describe alternatives you've considered**
We just keep our own profiles - it works.

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by dustymc** [comment]
Arctos is built for that sort of thing - if they have a decent API (they have an API, IDK about 'decent') then there's probably no technical barrier. 

There are likely lots of social barriers, but The Community exists in part to help us cross those.

**Comment by Jegelewicz** [comment]
https://portal.snaccooperative.org/node/489

**Comment by ewommack** [comment]
Would this be just for the bio info for agents? I noticed it didn't have any connections to museum specimens or publications.

**Comment by Jegelewicz** [comment]
> Would this be just for the bio info for agents?

Yes.

**Comment by dustymc** [comment]
> just for the bio info 

It doesn't have to be. Pulling some information from a service would be sorta neat, but I'm not sure what it could DO that simple linking can't.

Outsourcing agent management could be revolutionary.

**Comment by campmlc** [comment]
Looks like they are well funded with some major institutions involved,
including the UC system:
From their history tab on their website:  In 2015, the core team, which
included the University of Virginia, Institute for Advanced Technology in
the Humanities; the University of California, Berkeley School of
Information; and the California Digital Library, (part of the University of
California), transformed this research into an international cooperative
hosted by the U.S. National Archives and Records Administration (NARA).
I assume they would be able to integrate with ORCID and Bionomia?

**Comment by dustymc** [comment]
Tabling due to inactivity.

https://snaccooperative.org/download/38885915?type=constellation_json seems to be the most-complete view. If we wish to do something with that, the first step is probably an address type CT request.
