### ISSUE TITLE
botany attribute

### ISSUE THREAD

**Issue by droberts49** [ArctosDB/arctos#3361]
I'm prepping our botany data for migration and have a chunk of data that really can't be parsed out elsewhere that are original textual descriptions from the collectors (E.g. "Beautiful shrub, looks like wax. Flowers like lily-of-the-valley."; "Blossoms all the year."; "9 petals"; "bristle form leaves"). I don't want to put it in the Remarks section as we use that for other purposes. Could the "description" attribute be added to the herb attribute list please? Or is there another place that would be more appropriate?

**Comment by dustymc** [comment]
Sounds like the right place to me - done.

**Comment by droberts49** [comment]
Thank you, Dusty!
