### ISSUE TITLE
Next accession not counting MVZ Obs?

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#3363]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
The "next Accn" number has been working fine. Today went to create an accession for mammals. Arctos said the next number was 15612, but I checked ( and that card was missing), and found that that was already in Arctos as an MVZ Herp Obs Accession. 

**To Reproduce**
Haven't done it yet, but one would enter an obs accession. Then go to add another accn and see what arctos thinks is the next number. I don't want to try this since I don't know how to delete accessions. 

Issue may be obvious from the code?

**Expected behavior**
The expected next number is correct, whether the last one was a specimen accn or obs accn. 

**Priority**
Medium well done.

**Comment by dustymc** [comment]
Yea, looks like it probably is - those data are from when we had a DWC-centric view of the world and thought institution+collection would be unique.

```
arctosprod@arctos>> select guid_prefix,institution_acronym from collection where guid_prefix like 'MVZ%';
 guid_prefix | institution_acronym 
-------------+---------------------
 MVZObs:Bird | MVZObs
 MVZObs:Mamm | MVZObs
 MVZObs:Herp | MVZObs
 MVZ:Bird    | MVZ
 MVZObs:Fish | MVZObs
 MVZ:Fish    | MVZ
 MVZ:Mamm    | MVZ
 MVZ:Herp    | MVZ
 MVZ:Hild    | MVZ
 MVZ:Egg     | MVZ
```

Unless you or @ccicero @lkvoong @mkoo has a reason not to, I can update those and this should work more predictably.

**Comment by cjconroy** [comment]
i trust you to make it work, whatever it takes.

**Comment by mkoo** [comment]
Yes, it should be tracking across all MVZ +MVZObs collections (same
institutionCode) so thanks for fixing the auto-accession numbers!

**Comment by dustymc** [comment]
Bbs-containing institution acronyms (and UAMb) are now standardized with the "core" institution, dependencies are updated. It'll take a few hours for everything to catch up, so marking next release for monitoring.
