### ISSUE TITLE
Trying to clone classification

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#3366]
I've been editing taxonomy all week (actually, all year) but this morning I got this message when I tried to clone a WoRMS (via Arctos) classification.  

An error occurred while processing this page!
Message: not authorized
Detail: You are not authorized to access this form.
Check the Arctos Handbook for more information on errors.
This message has been logged as 4463A4E1-B1E6-44AF-9A88F99F85424282 Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue.

Same message on Safari and on FireFox.

**Comment by dustymc** [comment]
You should have access now.

**Comment by sharpphyl** [comment]
Thanks!
