### ISSUE TITLE
Manage collection does not permit unlock users?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3371]
@bfluker has manage collection permissions, but is not able to unlock accounts for other users in his collections. Shouldn't this be included in the manage collection role?

**Comment by dustymc** [comment]
PLEASE assign milestones! https://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html#managing-issues

**Comment by campmlc** [comment]
Prioritizing  - this is affecting collection management and hindering workflow.
