### ISSUE TITLE
Art and Ethnology Collections - implications to Arctos of VRA Core

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3373]
> The VRA Core is a data standard for the description of works of visual culture as well as the images that document them. The standard is hosted by the Network Development and MARC Standards Office of the Library of Congress (LC) in partnership with the Visual Resources Association External Link. Questions about the standard’s schemas and documentation should be directed to vracore@vraweb.org. Questions about the official Core website or list should be directed to ndmso@loc.gov.

https://www.loc.gov/standards/vracore/schemas.html

Before we continue to tackle all of the open code table issues for art and ethnology collections. It would probably be a good idea to review this schema and make sure that we are not too far removed from it.

Affected issues include https://github.com/ArctosDB/arctos/issues?q=is%3Aopen+is%3Aissue+label%3A%22Collection+Type+-+Cultural+Collections%22

**Comment by AJLinn** [comment]
Here's a bit more of the broader context of the VRA and the VRA Core, to supplement the discussion.
https://en.wikipedia.org/wiki/Visual_Resources_Association

**Comment by krgomez** [comment]
My understanding is that there is no conflict between the VRA Core and the CDWA (which is what we - UAM:Art - have referenced in most of these open issues). I looked through all the VRA Core elements and nothing strikes me as divergent from discussions in open issues. Here is a metadata standards crosswalk from Getty that might be helpful to look at: https://www.getty.edu/research/publications/electronic_publications/intrometadata/crosswalks.html
