### ISSUE TITLE
Emergency Network Maintenance Friday, 22 January 2021

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3374]
Emergency Network Maintenance Friday, 22 January 2021
From: Mark Brueschke
Emergency firewall maintenance is being carried out, the process should be brief with all services restored quickly.

Please submit any questions you may have via the TACC User Portal.
https://portal.tacc.utexas.edu/tacc-consulting

To manage your TACC Announcements subscriptions, please visit https://www.tacc.utexas.edu/news/subscribe

**Comment by ewommack** [comment]
Got it out to the google groups too.

**Comment by acdoll** [comment]
Thanks Beth! Looks like it's back up now.

**Comment by dustymc** [comment]
It's not as undead as it was a minute ago....

**Comment by acdoll** [comment]
I guess I spoke too soon.
