### ISSUE TITLE
Cache delay for loans?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3377]
I just created a loan, and am now trying to bulkload items to it. However, I get the message "loan not found". How much coffee do I need to go drink before this clears the cache? 
See #3376 
This is the current state of FLAT - but we need a way to interpret what these numbers mean. Within next 15 min? Take an hour break? Wait until next week?

Status | NumberRecords
-- | --
current | 4126182
filtered_flat_processing | 31
flat_processing | 25448

**Comment by dustymc** [comment]
There's no cache involving loans.

**Comment by campmlc** [comment]
So what does it mean when the loan exists, has been edited and saved, but
loan bulkload says the loan does not exist? It did eventually load - after
about 30 min.
