### ISSUE TITLE
Search on Other Identifier pulling related items

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3379]
Searching on a list of NK number identifiers is bringing up the catalog records of other records with a different NK that are related to items in the original list as "offspring of" .
This results in a query on Guids yielding the expected list of 547 records, but a query of the same list using other IDs yields 551 records. The extras are not duplicated identifiers, but "offspring of" the queried IDs, each with a different NK identifier than the parent.

Expected behavior: 
A query of other identifiers in list should only return results for records that have the identifier as "self" or "same individual as", not some other relationship (unless we explicitly add the option of choosing to sort  all Other IDs by non-self relationship types).

Why this is problematic:
I need to pull 500+ tissues of the specific organisms in question, not their related items. The unexpected records result in a extra samples in a Part Location search and a discrepancy in results that takes considerable time to sort out, affecting samples sent in loans.

**Comment by campmlc** [comment]
[First Request all 547 records by MSB_1.zip](https://github.com/ArctosDB/arctos/files/5870826/First.Request.all.547.records.by.MSB_1.zip)
[First Request all 551 records by NK.zip](https://github.com/ArctosDB/arctos/files/5870827/First.Request.all.551.records.by.NK.zip)

**Comment by campmlc** [comment]
See the following records and their data download in the attached files.
https://arctos.database.museum/guid/MSB:Mamm:266142
https://arctos.database.museum/guid/MSB:Mamm:266145
They share a parent offspring relationship. In the NK search results download, but not the GUID search, both parent and offspring records show up, even though only the parent NK was in the search list.
--

**Comment by dustymc** [comment]
can't replicate

**Comment by Jegelewicz** [comment]
@campmlc One thing I noticed way back in the day was that relationships are better made with catalog numbers than NKs. I don't know if that is what is going on here, but using the NK as the related identifier doesn't provide the linking between records that using the catalog number does.

**Comment by Jegelewicz** [comment]
I think that what I described above is the problem. I added the relationships to the catalog numbers for the two records above and removed the NK relationships. If I am right, then when you run your queries again, you should find one less duplicate.

**Comment by Jegelewicz** [comment]
Also, Make sure that your query is only for exact match relationship of "self".

**Comment by Jegelewicz** [comment]
OK, wait - why can't you select "self" in the relationship section?

**Comment by Jegelewicz** [comment]
<img width="960" alt="Screenshot 2021-01-26 08 23 42" src="https://user-images.githubusercontent.com/5725767/105865163-e0c73800-5faf-11eb-8a81-cdbc520b95ab.png">

**Comment by campmlc** [comment]
I didn't search on relationship. I searched on a list of NKs. My search results, in the files I attached for @dustymc, included results for cataloged items that were not in my original list of identifiers. I agree that we should always create relationships with cataloged items when possible, but I have no control over what other divisions do at cataloging. However, it shouldn't matter- the extra NKs in my search were linked to records by a non self relationship. These should not pull up in a general search.

**Comment by campmlc** [comment]
Also, interestingly, in the NK search results download, the custom other ID column contains both NKs for parent and for offspring for both parent and offspring records. See the entry for MSB:Mamm:266142 in that file.

**Comment by dustymc** [comment]
You can't select "self" in the relationship section because it could never find anything. The identifiers pane selects self behind the scenes.

@campmlc I need enough information to recreate what you're seeing as requested in the issue template. Results acquired in some unknown way does not lead to an understanding.

**Comment by campmlc** [comment]
I attached above both search results download files, one with the results from searching a list of NKs and the second the results from searching the list of MSB guids for the same records. Note they return different numbers of records. Since @Jegelewicz has now changed the relationships on the affected records, I'm not sure if the results can be duplicated, but the extra NKs are clearly visible in the attached zipped file of  the original search of NKs, e.g.  see the entries for MSB:Mamm:266142 and MSB:Mamm:266145 (only the former was requested) in the "551 records by NK" file. 
I'm attaching here the original file of the 547 NKs requested in the search. There are 551 results returned in the NK results file attached above, when there should only be 547. The extras are all offspring linked to parents by a "parent/offspring" reciprocal relationships on the NK number.

[NK list for search.zip](https://github.com/ArctosDB/arctos/files/5874656/NK.list.for.search.zip)

--

**Comment by campmlc** [comment]
And it appears that "The identifiers pane selects self behind the scenes" is not correct. That is the problem.

**Comment by dustymc** [comment]
>The identifiers pane selects self behind the scenes" is not correct. 

You can confirm by getting the results to URL format and adding ``&debug=true``

```
otherIdSearch.id_references = <cfqueryparam cfsqltype="cf_sql_varchar" value="self" null="false" list="false"> 
```

```
SELECT distinct flat.collection_object_id ,concatSingleOtherId(flat.collection_object_id,$$collector number$$) AS CustomID, $$collector number$$ as myCustomIdType, ConcatSingleOtherIdInt(flat.collection_object_id,$$collector number$$) AS CustomIDInt,flat.guid as guid,flat.scientific_name as scientific_name,concatCollectorAgent(flat.collection_object_id,'creator') as creator,flat.country as country,flat.state_prov as state_prov,flat.spec_locality as spec_locality,flat.verbatim_date as verbatim_date,flat.dec_lat as dec_lat,flat.dec_long as dec_long,flat.coordinateuncertaintyinmeters as coordinateuncertaintyinmeters,flat.full_taxon_name as full_taxon_name from flat INNER JOIN cataloged_item ON (flat.collection_object_id = cataloged_item.collection_object_id) INNER JOIN coll_obj_other_id_num otherIdSearch ON (flat.collection_object_id = otherIdSearch.collection_object_id) WHERE flat.collection_object_id IS NOT NULL and
otherIdSearch.id_references = <cfqueryparam cfsqltype="cf_sql_varchar" value="self" null="false" list="false"> and
otherIdSearch.other_id_type in ( <cfqueryparam cfsqltype="cf_sql_varchar" value="NK" null="false" list="true"> ) and
upper(otherIdSearch.display_value) in ( <cfqueryparam cfsqltype="cf_sql_varchar" value="192308,192297,272031,223820,192035,192040,192046,192045,192041,192051,192039,192044,223818,223720,192268,192272,270481,224447,224156,224370,224508,224448,224157,224437,224438,224446,224513,224515,224549,224552,224591,224597,224512,224553,224548,224510,224507,224509,224565,224567,224570,224581,224587,224595,224330,224584,224551,224539,224511,224514,224586,224596,192634,192632,192633,192635,192049,192042,192038,192050,192048,192043,192036,272069,289395,223827,223828,223970,223966,223967,223981,223819,223821,223822,223965,289400,289396,289399,289336,289398,224002,224001,223973,223971,289134,289346,289980,289979,289026,289874,166277,289347,289349,289345,289348,223936,223829,223830,223964,223972,223823,223831,223949,223986,223987,223969,192037,166628,192305,192333,192304,223832,192280,192306,192312,192309,192331,192330,192307,192334,192282,270859,272241,272100,272113,272250,289397,192311,192310,192517,192607,192611,192612,192613,192614,192616,192621,192624,192625,192608,192610,192617,192618,192623,192615,192619,192620,192622,192609,192600,194099,194100,224193,223948,223950,166309,166297,166296,166272,166276,194474,166311,270956,272094,272246,272107,272244,272245,272247,272248,272252,272099,272242,289972,289971,289968,289969,289973,289970,192047,192281,192284,192269,192283,192271,192344,100619,272049,272067,272240,272020,224516,289079,166459,166300,166310,166298,166304,166270,166302,166392,289434,289435,270427,166265,223842,270959,270960,289160,289078,289278,289027,289277,289344,224068,192265,192274,192275,192266,192273,192267,192270,166274,166308,166299,192313,192303,166273,166275,192253,192140,192182,272104,270955,270857,272038,270310,270852,270312,272019,270958,270311,272101,270957,270858,272102,272103,272105,272106,272237,270935,270936,270942,270314,270853,270518,272108,272109,272110,272111,272112,272114,166293,100741,100727,100623,100613,100614,100633,100637,100658,100664,100766,100751,100776,100777,100778,100779,100771,100773,100800,100802,100798,100799,100797,100618,100665,100621,100622,100624,100641,100635,100636,100640,100653,100519,100642,224550,224568,224190,224579,224650,224594,224600,224367,224566,224580,224593,224719,224450,224445,224371,224718,224576,224592,224189,224521,224331,224518,224520,224583,223953,270399,270400,224066,223976,223994,223718,223975,289257,289258,224077,223898,224107,223993,224332,223995,270313,223691,223698,289125,223954,223938,223952,270590,166301,166391,166394,166393,166303,192024,194171,193811,193886,193631,193634,270921,270817,270398,270257,270736,270402,270496,270405,270255,270401,166271,192252,194411,100536,100555,193562,194108,193817,270309,192026,192025,166312,270498,270499,100765,100753,100760,224452,224441,224158,224449,224439,224443,224444,224372,224440,224451,224517,224588,224601,224442,224519,224198,224602,224582,289276,272068,272070,224488,272217,270501,223841,223824,223833,223838,223839,223840,223961,223733,223974,223977,223826,223959,223960,223945,192302,289073,289149,289074,289075,289077,289157,289076,289184,289158,223825,223835,223837,223963,223734,223834,223962,223937,224334,272095,272050,272059,272044,272039,272040,272051,272054,272062,272043,272060,272052,272058,272061,272057,272063,272048,270938,270523,270519,272041,272042,270937,272243,272251,270934,272292,272053,272055,272056,272045,270939,270940,272047,272037,272253,272293,272046,272238,192516,192518,270256,270482,270497,270403,270404,270854,272254,224333,224076,194123,194183,270500,194233,194186,194185,194107,100615,100616,193564,194030,193762,193571,193626,193627,193628,192332,100632,100638,100654,100659,100707,100792,100793,100801,100713,100708,100710,100711,100709,100706,100712,100705,100617,100620,100625,100626,100627,100629,100630,100631,100634,100639,100655,100662,100663,100628,193550,193551,193563,193567,193565,193638,193629,193724,270483,272189" null="false" list="true"> )

```

**Comment by Jegelewicz** [comment]
@campmlc do you want me to change those back? I will if you want!

Just as a test, I searched the list you gave above and it returned 547 records as expected. I'll investigate further...

**Comment by campmlc** [comment]
I don't understand any of that, and neither will other cms, much less the
public. All I know is what I downloaded, which indicates that a search on
other identifiers is pulling up related identifiers with relationship other
than self/same individual as, which it should not do.
Since the records in my original search have been changed, can you pull up
a search of guids and NK numbers for all records that have a relationship
other than "self" linked to an NK number?

**Comment by AdrienneRaniszewski** [comment]
I agree with everything Mariel has noted. And simply using the GUID instead is not feasible since we don't know what the GUIDs are when we are entering data.

**Comment by campmlc** [comment]
Yes, please - we need to change them back to show what the problem is.

**Comment by campmlc** [comment]
Go ahead and leave the links to the guids though - hopefully just adding
the NK relationship will show the problem.

**Comment by Jegelewicz** [comment]
Done!

**Comment by Jegelewicz** [comment]
For what it is worth, when I search the list of NKs, I still get 547.

**Comment by campmlc** [comment]
So how does that explain my download? I'm not hallucinating, I swear!

**Comment by Jegelewicz** [comment]
I don't know and without your exact search parameters it is hard to say why they are different....

**Comment by dustymc** [comment]
I occasionally think we need an Official Arctos Exorcist....

**Comment by campmlc** [comment]
Here are my exact search parameters, the following list of NKs - I still have the search saved on my desktop. But I can't save and share because of #3378!
192308,192297,272031,223820,192035,192040,192046,192045,192041,192051,192039,192044,223818,223720,192268,192272,270481,224447,224156,224370,224508,224448,224157,224437,224438,224446,224513,224515,224549,224552,224591,224597,224512,224553,224548,224510,224507,224509,224565,224567,224570,224581,224587,224595,224330,224584,224551,224539,224511,224514,224586,224596,192634,192632,192633,192635,192049,192042,192038,192050,192048,192043,192036,272069,289395,223827,223828,223970,223966,223967,223981,223819,223821,223822,223965,289400,289396,289399,289336,289398,224002,224001,223973,223971,289134,289346,289980,289979,289026,289874,166277,289347,289349,289345,289348,223936,223829,223830,223964,223972,223823,223831,223949,223986,223987,223969,192037,166628,192305,192333,192304,223832,192280,192306,192312,192309,192331,192330,192307,192334,192282,270859,272241,272100,272113,272250,289397,192311,192310,192517,192607,192611,192612,192613,192614,192616,192621,192624,192625,192608,192610,192617,192618,192623,192615,192619,192620,192622,192609,192600,194099,194100,224193,223948,223950,166309,166297,166296,166272,166276,194474,166311,270956,272094,272246,272107,272244,272245,272247,272248,272252,272099,272242,289972,289971,289968,289969,289973,289970,192047,192281,192284,192269,192283,192271,192344,100619,272049,272067,272240,272020,224516,289079,166459,166300,166310,166298,166304,166270,166302,166392,289434,289435,270427,166265,223842,270959,270960,289160,289078,289278,289027,289277,289344,224068,192265,192274,192275,192266,192273,192267,192270,166274,166308,166299,192313,192303,166273,166275,192253,192140,192182,272104,270955,270857,272038,270310,270852,270312,272019,270958,270311,272101,270957,270858,272102,272103,272105,272106,272237,270935,270936,270942,270314,270853,270518,272108,272109,272110,272111,272112,272114,166293,100741,100727,100623,100613,100614,100633,100637,100658,100664,100766,100751,100776,100777,100778,100779,100771,100773,100800,100802,100798,100799,100797,100618,100665,100621,100622,100624,100641,100635,100636,100640,100653,100519,100642,224550,224568,224190,224579,224650,224594,224600,224367,224566,224580,224593,224719,224450,224445,224371,224718,224576,224592,224189,224521,224331,224518,224520,224583,223953,270399,270400,224066,223976,223994,223718,223975,289257,289258,224077,223898,224107,223993,224332,223995,270313,223691,223698,289125,223954,223938,223952,270590,166301,166391,166394,166393,166303,192024,194171,193811,193886,193631,193634,270921,270817,270398,270257,270736,270402,270496,270405,270255,270401,166271,192252,194411,100536,100555,193562,194108,193817,270309,192026,192025,166312,270498,270499,100765,100753,100760,224452,224441,224158,224449,224439,224443,224444,224372,224440,224451,224517,224588,224601,224442,224519,224198,224602,224582,289276,272068,272070,224488,272217,270501,223841,223824,223833,223838,223839,223840,223961,223733,223974,223977,223826,223959,223960,223945,192302,289073,289149,289074,289075,289077,289157,289076,289184,289158,223825,223835,223837,223963,223734,223834,223962,223937,224334,272095,272050,272059,272044,272039,272040,272051,272054,272062,272043,272060,272052,272058,272061,272057,272063,272048,270938,270523,270519,272041,272042,270937,272243,272251,270934,272292,272053,272055,272056,272045,270939,270940,272047,272037,272253,272293,272046,272238,192516,192518,270256,270482,270497,270403,270404,270854,272254,224333,224076,194123,194183,270500,194233,194186,194185,194107,100615,100616,193564,194030,193762,193571,193626,193627,193628,192332,100632,100638,100654,100659,100707,100792,100793,100801,100713,100708,100710,100711,100709,100706,100712,100705,100617,100620,100625,100626,100627,100629,100630,100631,100634,100639,100655,100662,100663,100628,193550,193551,193563,193567,193565,193638,193629,193724,270483,272189

**Comment by campmlc** [comment]
Note that NK 223952 is in my list. But my results include NK 223955, its offspring.

**Comment by Jegelewicz** [comment]
I used that and searched NK, in list and got 547....

**Comment by Jegelewicz** [comment]
Screenshot your search params?

**Comment by campmlc** [comment]
Aha, I may have found it - I have "NK" as my customID. I entered the list there, and got the extras. If I instead enter the list as Other Identifier Type = NK, I don't get the extras. Try it with NK 223952.
Speaking of exorcists, please send one my way - in addition to not being able to save searches, my computer now refuses to take a screenshot.

**Comment by Jegelewicz** [comment]
Close some of your tabs.... :-)

**Comment by campmlc** [comment]
Well, that is a good suggestion given the number I have open, but still no
go - likely related to a need to reboot and a dying battery. But if I
reboot, I lose the search :(
Were you able to duplicate the problem using customID?

**Comment by Jegelewicz** [comment]
Use your phone and take a picture of the search parameters..

> Were you able to duplicate the problem using customID?

Yep and it makes sense because that search is just looking for any records that contains those NK numbers - no relationship is implied.

**Comment by campmlc** [comment]
Where is the documentation that choosing an identifier as customID will
result in a different search than using the identifier field?

**Comment by Jegelewicz** [comment]
> Where is the documentation that choosing an identifier as customID will
> result in a different search than using the identifier field?

Looks like you just signed up to write it!

But really, we might just need a warning that using the customID search field doesn't take into account any relationships associated with the ID.

**Comment by campmlc** [comment]
How about making the searches equivalent? That is what users expect, given
the purpose of customid is just to avoid having to use the horrid other Id
drop-down and have the identifier separated out in results, not to be a
different type of search entirely.

**Comment by Jegelewicz** [comment]
But IS that what users expect? I didn't expect that.

**Comment by AdrienneRaniszewski** [comment]
I can't speak for all users, but I would certainly expect the searches to be equivalent.

**Comment by campmlc** [comment]
I certainly had no reason to think they would be different- why would it be
otherwise? I do think we need a very clear warning on My Profile as well as
Search page if that is the case. I use customid for all my searches all day
long for the convenience and frustration reduction of not having to deal
with the other ID list drop-down, and I'm lucky because my other ID is
relatively near the top. On my laptop, that other ID drop-down scroll is
horrendous. As a heavy user, I would prefer to be able to continue to use
customid as my default, but I can't if I can't be certain the results are
precisely what I searched for.
How about a box to check on customid to limit search to exact or self only?

**Comment by Jegelewicz** [comment]
This conversation has made me realize that the ONLY way to get all instances of an other identifier (relationship to self or otherwise) is via the customID (unless you write some SQL).

**Comment by dustymc** [comment]
Custom ID documentation updated, references is explicit via https://github.com/ArctosDB/arctos/issues/3437
