### ISSUE TITLE
Arctos Outage: 3PM Central TODAY

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3381]
We need to restart the DB. The best time is 3PM today. Please let me know ASAP if that would cause major problems, and we can reschedule it for tomorrow morning.

**Comment by jldunnum** [comment]
Personally I'd prefer to wait until tomorrow

______________________________________________________________

Jonathan L. Dunnum Ph.D.
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by campmlc** [comment]
Aren't we doing a new collections orientation in house webinar today at 2pm
Central? I'd also prefer tomorrow morning.

**Comment by dustymc** [comment]
Some critical component of the database aren't operating (see https://github.com/ArctosDB/arctos/issues/3380). This does have some urgency as scheduled tasks aren't being processed, but we can wait until tomorrow if necessary.

If everything goes according to plan, the outage should be less than a minute. Everything does not always go according to plan....

I do need a firm decision as soon as possible so I can coordinate with TACC.

@ArctosDB/arctos-working-group-officers

**Comment by acdoll** [comment]
I have no objections, but defer to anyone with active work in-progress. BTW: I do not see the same problems mentioned in 3388

**Comment by campmlc** [comment]
Then I have no objection to 3pm Central today, or sooner if necessary and
hopefully short.

**Comment by ewommack** [comment]
Good for me to send out a notice?
"Arctos outage at 3pm CT in order to do emergency maintenance. This outage will restart the database."

**Comment by dustymc** [comment]
@jldunnum ? I think its your call if nobody else shows up soonish.

**Comment by jldunnum** [comment]
Yeah go ahead with it, thanks.

______________________________________________________________

Jonathan L. Dunnum Ph.D.
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by ewommack** [comment]
And message sent

**Comment by mkoo** [comment]
Thanks all.

**Comment by dustymc** [comment]
An emergency came up and 3 didn't happen; we'll try at 4 central/2 pacific unless I hear otherwise, in which case we can try again tomorrow morning.

**Comment by dustymc** [comment]
done
