### ISSUE TITLE
Code Table Request - New taxon term parvorder

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3382]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Goal**
Add TPT classifications

**Context**
This is a level in the Lice taxonomy used by TPT

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxon_term

**Value**
parvorder

**Definition**
A subdivision of infraorder. Subordinate to the infraorder; superordinate to the nanorder.

**Collection type**
N/A

**Attribute data type**
N/A

**Attribute value**
N/A

**Attribute units**
N/A

**Part tissue flag**
N/A

**Other ID BaseURL**
For OtherIDs, provide the following *or* explain why the unresolvable ID type is necessary:
1. "Base URL" with which to prepend entered values, and
2. A functional example URL, which should consist of the base URL provided in (1) plus a relevant value.

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
No objections from me, but you may need update the documentation on multiple records - it should refer to things that are in Arctos eg not "nanorder" (unless you're adding that too...).

**Comment by Jegelewicz** [comment]
See next issue....
