### ISSUE TITLE
UAM:EH records not showing up in bulkloader - what am I doing wrong?

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#3384]
What am I doing wrong that my records that I created yesterday thru the data entry form aren't getting loaded in/thru the bulkloader?

1. 
<img width="1205" alt="Screen Shot 2021-01-26 at 12 08 12 PM" src="https://user-images.githubusercontent.com/17605945/105907386-64dde780-5fd1-11eb-9b9b-5ff7902c7e39.png">

2.
<img width="1097" alt="Screen Shot 2021-01-26 at 12 08 43 PM" src="https://user-images.githubusercontent.com/17605945/105907516-83dc7980-5fd1-11eb-8ba4-725b3fe22ad4.png">

3. Then they should be loaded (in a reasonable amount of time) yes?

4. But no.... I did this yesterday for those six records, but they haven't loaded yet. What am I doing wrong?

This is accession [UAM:EH:UA2020-008](https://arctos.database.museum/accn.cfm?action=edit&transaction_id=21126395)

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/3381

**Comment by dustymc** [comment]
Should be all cleared up now.
