### ISSUE TITLE
Search by other identifiers

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3385]
This conversation has made me realize that the ONLY way to get all instances of an other identifier (relationship to self or otherwise) is via the customID (unless you write some SQL).

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/arctos/issues/3379#issuecomment-767866824_

**Comment by Jegelewicz** [comment]
I think we need to add "any" to the options for relationship when searching by other identifier:

<img width="960" alt="Screenshot 2021-01-26 08 23 42" src="https://user-images.githubusercontent.com/5725767/105865163-e0c73800-5faf-11eb-8a81-cdbc520b95ab.png">

**Comment by Jegelewicz** [comment]
We also need to decide how the customID search should function. Options include:

1. only return relationships to "self"
2. Return any relationship (this is apparently how it works now)
3. Add the relationship to this search function to customize 
> How about a box to check on customid to limit search to exact or self only?

**Comment by dustymc** [comment]
>ONLY way to get all instances of an other identifier (relationship to self or otherwise) is via the customID

I think you're right - we should probably have a 'references' (default: self) selector up there somewhere.

>add "any" to the options for relationship when searching by other identifier

That would be precisely the same functionality as leaving that blank.

>need to decide how the customID search should function

New Issue - that's going to mess with a LOT of users, should not be hidden or mixed with anything else.

>How about a box to check on customid to limit search to exact or self only?

I don't see any way that could be practical.

**Comment by Jegelewicz** [comment]
> 
>     add "any" to the options for relationship when searching by other identifier
> 
> That would be precisely the same functionality as leaving that blank.

DOH!

**Comment by campmlc** [comment]
So how can we resolve this? This is holding up curation.
