### ISSUE TITLE
Code Table Request - 

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3386]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Goal**
Need to add parts to Mamm code table without preservation type.

**Context**
per MSB request: "There’s been an option to enter part preservation separately from the part for a while now, but in order to take advantage of that there needs to be a preservation-free part in Arctos. That doesn’t exist for the large intestine parts yet. Can you add them?"

**Table**
Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm

**Value**
large intestine 
large intestine, feces 

**Definition**
https://en.wikipedia.org/wiki/Large_intestine

**Collection type**
Mamm

**Attribute data type**
free-text, categorical, number+units

**Attribute value**
For categorical attributes, code table controlling value

**Attribute units**
For number+units attributes, code table controlling units

**Part tissue flag**
possibly (dependent on preservation attribute)

**Other ID BaseURL**
For OtherIDs, provide the following *or* explain why the unresolvable ID type is necessary:
1. "Base URL" with which to prepend entered values, and
2. A functional example URL, which should consist of the base URL provided in (1) plus a relevant value.

**Priority**
High - holding up data entry.

**Comment by Jegelewicz** [comment]
Seems like a no-brainer. I vote go ahead.

**Comment by campmlc** [comment]
Ok, if no objections in next hour, I will add the parts.

**Comment by dustymc** [comment]
I'm not thrilled with the idea of propagating ``large intestine, feces`` but that's not (quite!) an objection either.

**Comment by campmlc** [comment]
we could globally change to "intestine, large with feces" - but there was a
specific request earlier to add an option of with feces. I suggested having
feces separated, but these will share the same barcode, and there is the
issue of having to add "extras" in data entry.

**Comment by campmlc** [comment]
Done, closing.
