### ISSUE TITLE
error building report data from projects/publications

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#3393]
I'm trying to "Build Report Data" from a publications query, and when I enter the title and click "Build Report Data" I get the following error:

An error occurred while processing this page!
Message: ERROR: type "varchar2" does not exist Position: 53

![image](https://user-images.githubusercontent.com/967275/106186391-122f3780-6159-11eb-8e58-d43332f344b6.png)

**Comment by dustymc** [comment]
What are you trying to do? That will need rewritten and it's used by Reports, which have a very limited future (https://github.com/ArctosDB/internal/issues/37). I'm not sure it makes sense to invest in that. Do you just need the CSV?

**Comment by mkoo** [comment]
Can we please have an export of publications with publication type =
"Field notebook" ? (CSV would be best)
thanks!

**Comment by ccicero** [comment]
Actually, I was searching for pubs with 'Field Notes' in the title. Not sure if there is a 1:1 between that and the pub type.

It was a tool I've never seen before, so I was playing around with it. A CSV export is fine.
