### ISSUE TITLE
Code Table Request - gape width (and modification to bill width definition)

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#3396]
A researcher measured gape width on over 10k specimens in the MVZ. I created a loan (MVZ:Bird 8314), and have the measurement data that I'd like to upload the specimen records. 

There is a field "bill width" which has the definition "width of the bill measured at the widest point, typically the gape"

However, that is not usually how bill width is measured. Typically, width is measured at the anterior margin of the nares, not the widest point at the base of the bill (i.e., the gape). 

So either we modify the definition of bill width and add a new attribute of gape width, or we use bill width for all measurements and I can add an attribute remark that the measurements represent the gape. It's hard to know how the existing bill width measurements were actually taken. Here is a screen shot of collections with 'bill width' measurements.

![image](https://user-images.githubusercontent.com/967275/106203670-a0fb7e80-6170-11eb-9c34-6ce322033379.png)

Alternative (and in my mind preferred) definitions are:

1) bill width -  width of the bill measured at the anterior margin of the nares
2) gape width - width of the bill measured across the widest point at the base

**Comment by ewommack** [comment]
I'd be up for changing the definitions and adding the new attribute. A lot of birds the difference will be very slight, but some (caprimulgiformes etc) this would be a huge difference.

It would also be great to be more specific so there is less confusion when we receive data from banders and observations in the future.

**Comment by ccicero** [comment]
I agree. Plus there is ecological and conservation relevance to studying gape width (i.e., as it relates to frugivory), and researchers are likely going to be interested in just that attribute. We had a whole seminar on that yesterday.

**Comment by dustymc** [comment]
I definitely like better definitions, an additional attribute is fine, existing users should be contacted first. Let me know if I need to shuffle anything around.

@droberts49 @acdoll @ebraker @mvzhuang

**Comment by ccicero** [comment]
Thanks Dusty for tagging folks.

**Comment by ebraker** [comment]
I'm fine with the two separate definitions. I would imagine most existing BW measurements would be at the nares unless otherwise noted (for sure UCM data) .

**Comment by Jegelewicz** [comment]
Done.
