### ISSUE TITLE
Funding Node (was: Link to Award Number in Projects)

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3398]
Currently the award number link searches crossref. I don't know if this works for any NSF awards, but it isn't working for [this one](https://arctos.database.museum/project/10003272).

Could we generate links to awards depending upon the sponsor? I have added the correct link in the description of the award, but the award link at the top is much more prominent and currently doesn't work. Not sure the best path to take to make this better...

![image](https://user-images.githubusercontent.com/5725767/106311151-ea57d680-6221-11eb-85f1-9e1c77a5a294.png)

**Comment by dustymc** [comment]
>works for any NSF awards,

https://github.com/ArctosDB/arctos/issues/1694 is a super-easy path to really strong "lookit how important we really are" data, and I can't quite understand why "thou shalt use fundref" is not a central component of every loan agreement. (It also makes this link work!)

Barring that, I don't know what to do about this. I can accept what people deal with ("NSF DBI 1901932," often with randomized spaces and dashes and hyphens and ....) and hope I can find something useful from it (I can't always, obviously), or I could accept some pkey from some random NSF database (AWD_ID=1901932) which will get mucked up when people touch it and may or may not do anything useful later today when NSF gets new pkeys for some random reason, or ???????????????


I'm certainly very much up for clever ideas.

**Comment by Jegelewicz** [comment]
How about just providing an opportunity for whoever is creating the project to add the link?

**Comment by dustymc** [comment]
>add the link

Media is available and exists for that sort of thing. This was added as an attempt to do something with project funding, and I don't think providing URLs can meet that need (but ???). Removing the "try to guess a URL" thing might be the least-evil thing we can do?

**Comment by Jegelewicz** [comment]
I don't know what fundref is, but this is apparently searching crossref. Currently, there are zero publications resulting from this project and it will probably be a long while before there are any, so if this requires not only a publication, but one that cites this particular funding source, it actually may never happen. This project isn't really about publications - it is an infrastructure grant. Publications will result from the data we create, but there will really be no way for the data users to know about that linkage and report the grant in their publication.

Am I understanding how this works?

**Comment by Jegelewicz** [comment]
>  Removing the "try to guess a URL" thing might be the least-evil thing we can do?

I think so. If the majority of these links go to nowhere, it just looks bad.

**Comment by dustymc** [comment]
>don't know what fundref is

You should! https://www.crossref.org/services/funder-registry/

I guess they got a new name though.

>publications

That's a different thing, but the data gets incredibly cool if they also use fundref - then there's a pathway from 'got some $$ to murder rats' (or buy freezers, or build buildings, or hire students, or ....) to 'used murdered rats for sciencey things, which wouldn't have happened without the $$ that put these things in a museum.' 

>This project isn't really about publications 

Neither is fundref, at least not directly.

>there will really be no way for the data users to know about that linkage and report the grant in their publication.

That's basically why fundref exists.

ANYWAY - yea, I'm not seeing a lot of reason to keep the URL-bits of this. Does anyone else feel otherwise, and can someone write some 'how to link...' documentation if we're giving up on magicking it?

**Comment by Jegelewicz** [comment]
I can write documentation, but let's make sure everyone else in on board first. Also - after the change, could I just put the link as it is in the description into the Award Number field? That would be cool.

**Comment by dustymc** [comment]
>put the link as it is in the description into the Award Number field

That needs discussed. I believe the idea was "show me what projects my grant has funded" and you can't do that from random strings.

The "good" news is, there are eighteen whole projects with funding information at the moment - WHATEVER we do can't break much, and if someone comes up with something clever it should be pretty straightforward to catch up with the existing data.

**Comment by Jegelewicz** [comment]
Asking people to create the link in HTML will probably be mostly a bust - no one reads the documentation. I feel like the most effective method would be to leave the award number where it is, but add a field for an award number website that gets used to create the link.

**Comment by campmlc** [comment]
Agree. Let's add a field for the link.

**Comment by dustymc** [comment]
We need to shuffle the model around a bit (probably) so now's a good time if anyone has radical suggestions.


```
arctosprod@arctos>> \d project
                                          Table "public.project"
       Column        |          Type           | Collation | Nullable |              Default               
---------------------+-------------------------+-----------+----------+------------------------------------
 project_id          | bigint                  |           | not null | nextval('sq_project_id'::regclass)
 ....
 funded_usd          | bigint                  |           |          | 

arctosprod@arctos>> \d project_agent
                                           Table "public.project_agent"
        Column         |          Type          | Collation | Nullable |                 Default                  
-----------------------+------------------------+-----------+----------+------------------------------------------
 project_id            | bigint                 |           | not null | 
 ...
 award_number          | character varying(255) |           |          | 
```

There's no real relationship between award_number and total project funding. We could move funded_usd to project_agent, add a 'project_agent_funding' table, add a project_funding table (but that would probably split up agent roles, which seems sub-par), generalize to some sort of project_attributes, ?????????????? The easy solution is to move the int field, but a new node might allow doing more with award numbers vs links (and ???). What's the ideal use case - what should these data DO, what data should be associated with an award, ????

**Comment by campmlc** [comment]
An award should be associated with a funding agency and with an
institutional or person agent (funding recipient), and by extension with
the accessions that then lead to specimens contributed?

**Comment by dustymc** [comment]
Whatever we do should support https://github.com/ArctosDB/arctos/issues/2631

**Comment by dustymc** [comment]
>An award should be associated with a funding agency 

That's the current model - you can add award only to role sponsor.

>and with an institutional or person agent (funding recipient)

That suggests we need an "award module" - this project happened because A gave $9 to B and C, and D gave $24M to E, and ..... -  I think you're describing something more than we have, and if we're going there we might as well cover the potential complexity of multiple awards each with multiple agents on both ends of them collectively resulting in some project. Recording that data requires more structure than what we have now - I think maybe it's a new "node" (eg something that can produce a primary key) with at least "funding stuff" and "funding stuff agents" tables.

>by extension with the accessions

Yes, but whatever we do should also work for borrows and loans (which could just be different views of the same THING when multiple participants are in Arctos). Maybe more evidence that we need a "node."

Practical consideration: we currently have data for 16 awards (assuming no duplicates). Is this too theoretical to invest in? ("If you build it they will come" vote from me...)

**Comment by campmlc** [comment]
I agree if you build it they will come. I have been adding award info as I
can extract it from PIs for big projects - usually after they complain that
a loan recipient didn't acknowledge the funding source properly. If we have
a good place (node = module sounds good) to put these data, I will
certainly work on populating it with more data.

**Comment by dustymc** [comment]
>if you build it

Can we build a list of everything that anyone might ever care about regarding funding? Here's a potential start.

* award identifier (eg DEB-1457180)
* award link (https://www.nsf.gov/awardsearch/showAward?AWD_ID=1457180)
* award title (Collaborative Research: Unraveling the Deep History of Avian Neurological Complexity: Implications for the Origins of Flight and Organization of the Modern Avian Brain)
* award description (Despite advances in knowledge of brain functio....)
* award amount
* amount units (FK https://arctos.database.museum/info/ctDocumentation.cfm?table=ctmonetary_units)

and some new roles with which agents would be associated - these would be "just data" so don't need to be preemptively perfect, but my example includes:

* agency
* sponsor 
* investigator
* recipient

I'm not sure I know the difference between some of those so good definitions would need developed.

And not entirely unrelated, "PUBLICATIONS PRODUCED AS A RESULT OF THIS RESEARCH" is almost certainly coming from FundRef.

**Comment by Jegelewicz** [comment]
> If you build it they will come

> good definitions would need developed

    award identifier (eg DEB-1457180) - alphanumeric identifier issued by the funding agency
    award link (https://www.nsf.gov/awardsearch/showAward?AWD_ID=1457180) - Funding agency award url
    award title (Collaborative Research: Unraveling the Deep History of Avian Neurological Complexity: Implications for the Origins of Flight and Organization of the Modern Avian Brain) - Title of project for which funding was awarded
    award description (Despite advances in knowledge of brain functio....) - Abstract of project for which funding was awarded.
    award amount - Monetary value of award
    amount units (FK https://arctos.database.museum/info/ctDocumentation.cfm?table=ctmonetary_units) - monetary units of funded amount
    agency - I think this is a repeat of "sponsor"? or did you have something else in mind?
    sponsor - Agency or individual funding the award
    principal investigator - individual(s) to which funding was awarded
    recipient institution - institution handling award funds on behalf of the principal investigator(s)

**Comment by campmlc** [comment]
Looks good -
sponsor is same as agency
Each of these fields should be subfields associated with one award number,
We should allow multiple PIs and multiple institutions for a given award.
We should allow multiple awards for a given project.

**Comment by dustymc** [comment]
>agency - I think this is a repeat of "sponsor"? or did you have something else in mind?

<img width="496" alt="Screen Shot 2021-03-08 at 8 16 23 AM" src="https://user-images.githubusercontent.com/5720791/110348529-98575d00-7fe6-11eb-9314-12619455c231.png">

We need a place for NSF.

We need a place for whatever OSU is in the example I'm using (one of the PI's org?)

**Comment by Jegelewicz** [comment]
> whatever OSU is in the example I'm using (one of the PI's org?)

I would say OSU is "recipient institution".

**Comment by Jegelewicz** [comment]
But maybe we should follow NSF terminology:

sponsor =  institution handling award funds on behalf of the principal investigator(s)
agency = agency or individual funding the award

and drop "recipient institution".

**Comment by campmlc** [comment]
That actually makes more sense in the context of how we use these terms. I
had always understood "funding agency" to be the provider of funds - and
sponsor seemed an awkward and un-intuitive replacement. I vote to go with
NSF to avoid further confusion.

**Comment by dustymc** [comment]
We should keep this more focused.

1. Do we need a dedicated funding node?
2. Is the [model I've laid out ](https://github.com/ArctosDB/arctos/issues/3398#issuecomment-791034970) sufficient? (It's almost certainly not - I just picked a few things from one type of potential data!)


Agent roles are distractions until we know what we're hanging them on (if anything).

How can we encourage participation?

**Comment by Jegelewicz** [comment]
> Do we need a dedicated funding node?

My answer is yes - and in a way it is like a permit (some awards can be extended, etc.)

> Is the model I've laid out sufficient? (It's almost certainly not - I just picked a few things from one type of potential data!)

Probably almost everything included on the NSF page? 

Initial Award Date
Initial Amendment Date:
Latest Amendment Date: 
Additional funds awarded: (may need more than one of these and may need to be associated with an amendment date)
Award Number:
Award Instrument: (eg. Standard Grant) 
Program Manager: maybe this should be "Sponsor Contact"? 
Start Date:
End Date: 
Awarded Amount to Date: (calculate from initial award amount plus any amendments)
Investigator(s):
Sponsor: 
NSF Program(s): (be specific or include some sort of "award attributes"?)
Program Reference Code(s): see above 
Program Element Code(s): see above

**Comment by dustymc** [comment]
>(may need more than one of these and may need to be associated with an amendment date)

If we do then that needs sussed out - "2" could fit in the simple table, "more" would need a different structure (which would require more complex forms and such).

>Program Manager
>Investigator(s):
>Sponsor:

Those are all agent roles (and so can be mostly ignored for now).

>calculate

No need for a field then, particularly if this involves "more" and those data are scattered across multiple rows in multiple tables.

>NSF

I don't think this should be that specific. Whatever we do here should equally well for NSF and however {some other country} funds {anything that might end up in Arctos}. 

I'm not sure I see a need for procedural data (including extensions and amendments and such) at all, I think we just need a summary of the most important and universal characteristics of funding. That is, I think we should focus on things like "how much $$ was involved in collecting the material used for this project?" and Arctos users won't much care about enumerating the obscure hoops jumped through to get there. If we do need gritty details, then we need something other than a simple table to hold them.  It would be good to get more feedback from Curators and CMs.

**Comment by campmlc** [comment]
Prioritize discussion because #3468

**Comment by campmlc** [comment]
Let's revive and prioritize. Another @dustymc office hours conversation?

**Comment by Jegelewicz** [comment]
data here - https://drive.google.com/file/d/1yB_YriA1AwOLmMPoopOfr8BgbV0q2ttZ/view?usp=sharing

**Comment by dustymc** [comment]
I think we have a place for everything in that spreadsheet.

**Comment by dustymc** [comment]
See also https://docs.google.com/spreadsheets/d/1tO9mglPqW8RGth5KzbUwDSXKO3e3kmznD3XQfFy2B7M/edit#gid=0 from merged issue

**Comment by dustymc** [comment]
It seems there's little immediate interest, so tabling.

I changed award number to handle links when provided. So this:

<img width="688" alt="Screen Shot 2021-06-08 at 7 30 01 AM" src="https://user-images.githubusercontent.com/5720791/121203990-68a93280-c82b-11eb-84f3-9b9c542dd526.png">

displays/functions as:

<img width="467" alt="Screen Shot 2021-06-08 at 7 30 14 AM" src="https://user-images.githubusercontent.com/5720791/121204045-72329a80-c82b-11eb-82ce-80158d33342e.png">

Documentation should be updated if we stay with that model.

**Comment by Jegelewicz** [comment]
Nice to have the link, but do we have to SEE it? For a lot of these things I think we need the link and the text you want to see. So for this one:

link | text
 -- | --
https://nsf.gov/awardsearch/showAward?AWD_ID=1901932 | 1901932

which would look like:

Award Number: [1901932](https://nsf.gov/awardsearch/showAward?AWD_ID=1901932)

but with the little arrow in a box after it.

**Comment by dustymc** [comment]
>do we have to SEE it? 

How do you feel about duct tape?

<img width="208" alt="Screen Shot 2021-06-09 at 4 02 30 PM" src="https://user-images.githubusercontent.com/5720791/121440109-215e9700-c93c-11eb-8852-36ebac5949bd.png">

which is ``<a href="https://nsf.gov/awardsearch/showAward?AWD_ID=1901932" class="external">1901932</a>`` results in

<img width="550" alt="Screen Shot 2021-06-09 at 4 03 18 PM" src="https://user-images.githubusercontent.com/5720791/121440163-3c310b80-c93c-11eb-81dd-24a9e45051e6.png">

but also precludes any searching.

If you want more, something like this Issue is going to have to be implemented.

**Comment by Jegelewicz** [comment]
Nope = if we can't find it, it is no good. Which means that https://nsf.gov/awardsearch/showAward?AWD_ID=1901932 is also no good. Nobody searching for an award is going to type that in.
