### ISSUE TITLE
Error on search page

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3402]
I logged in this morning and saw this:

![image](https://user-images.githubusercontent.com/5725767/106617059-7e2fe800-652b-11eb-9c99-1780125f5a50.png)

**Comment by dustymc** [comment]
That's been from running out of connections, but we're running at around 20% of capacity now and that's the only recent occurrence. Glitch in the matrix...

**Comment by Jegelewicz** [comment]
blue or red? I cannot choose...

**Comment by Jegelewicz** [comment]
It did self-correct when I refreshed the page.

**Comment by campmlc** [comment]
I just got the same error. It disappeared when I refreshed. I'd been doing searches, and went back from search results to the search page.
