### ISSUE TITLE
Review of Event block on specimen detail page

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3403]
I agree, stuff is jumbled up and I don't understand why we have so many nested tables. I have added comments to the code to try to sort through it. I think we need to re-organize the way the coordinates, elevation, depth, map and event and locality media are presented in the table. Before I do anything, I'd like your opinion on the existing nested table structure.

``` 
<!---- Event Table Row 19 Associated Species ---->
							<cfif len(one.associated_species) gt 0>
							<div class="detailBlock">
								<tr class="detailData">
									<td id="SDCellLeft" class="innerDetailLabel">Associated Species:</td>
									<td id="SDCellRight">#one.associated_species#</td>
								</tr>
							</div>
						    </cfif>
							<!---- Event Table Row 20 A bunch of stuff mashed together ---->
                            <tr>
								<td colspan="2">
                                    <!--- first cell of event table row 20 is the Coordinates table --->
									<table width="100%">
                                        <!---- Coordinates Table Row 1 Lat Lon ---->
										<tr>
											<td valign="top" align="right"><!---- text stuff here what is this for? ---->
                                                <!--- first cell of Coordinates table row 1 is another table, why? ---->
												<table width="100%">
                                                    <!--- first row of second coordinates table, finally, we present the coordinates --->
													<tr>
														<td align="right" valign="top">Coordinates:</td>
														<td align="left">
															<cfif len(dec_lat) gt 0 and len(dec_long) gt 0>
																#dec_lat# / #dec_long#
																<cfif oneOfUs is 1>
																	<a href="/info/localityArchive.cfm?locality_id=#locality_id#">history</a>
																</cfif>
															<cfelseif
																len(s$dec_lat) gt 0 and
																len(s$dec_long) gt 0 and
																oneOfUs is 1 and
																len(locality_name) is 0>
																<input
																	type="button"
																	class="insBtn"
																	onclick="loadEditApp('specLocality_forkLocStk.cfm?specimen_event_id=#specimen_event_id#&magicCoordinates=true;');"
																	value="Click here then save for Magic Coordinates">
															</cfif>
															<cfif len(verbatim_coordinates) gt 0>
																<div class="detailCellSmall">
																	Verbatim Coordinates: #verbatim_coordinates#
																</div>
															</cfif>
															<cfif len(DATUM) gt 0>
																<div style="font-size:.8em;">
																	Datum: #DATUM#
																</div>
															</cfif>
															<cfif len(MAX_ERROR_UNITS) gt 0>
																<div style="font-size:.8em;">Error: #MAX_ERROR_DISTANCE# #MAX_ERROR_UNITS#</div>
															</cfif>
															<cfif len(georeference_source) gt 0>
																<div style="font-size:.8em;">Georeference&nbsp;Source: #georeference_source#</div>
															</cfif>
															<cfif len(georeference_protocol) gt 0>
																<div style="font-size:.8em;">Georeference&nbsp;Protocol: #georeference_protocol#</div>
															</cfif>
															<cfif len(wkt_media_id) gt 0>
																<div style="font-size:.8em;">WKTMediaID: <a href="/media/#wkt_media_id#" target="_blank">#wkt_media_id#</a></div>
															</cfif>

														</td>
													</tr>
                                                    <!--- second row of second coordinates table, Elevation --->
													<cfif len(orig_elev_units) gt 0>
														<tr>
															<td align="right">Elevation</td>
															<td align="left">#minimum_elevation# to #maximum_elevation# #orig_elev_units#</td>
														</tr>
													</cfif>
                                                    <!--- third row of second coordinates table, Depth --->
													<cfif len(DEPTH_UNITS) gt 0>
														<tr>
															<td align="right">Depth:</td>
															<td align="left">#MIN_DEPTH# to #MAX_DEPTH# #DEPTH_UNITS#</td>
														</tr>
													</cfif>
                                                    <!--- fourth row of second coordinates table, Media --->
													<tr>
														<td valign="top" colspan="2">
															<div id="locColEventMedia_#specimen_event_id#_#collecting_event_id#_#locality_id#"></div>
															<div id="colEventMedia_#specimen_event_id#_#collecting_event_id#_#locality_id#"></div>
														</td>
													</tr>
                                                    <!--- end of second coordinates table --->
												</table>
											<!--- end of first cell of Coordinates table row 1 table ---->
                                            </td>
                                            <!---- Coordinates Table Row 1, column 2 Map ---->
											<td valign="top" align="right"><!---- map here --->
												<cfif len(dec_lat) gt 0 and len(dec_long) gt 0>
													<cfset coordinates="#dec_lat#,#dec_long#">
													<input type="hidden" id="coordinates_#specimen_event_id#" value="#coordinates#">
													<input type="hidden" id="error_#specimen_event_id#" value="#err_in_m#">
													<div class="#session.sdmapclass#" id="mapdiv_#specimen_event_id#"></div>
													<span class="infoLink mapdialog">map key/tools</div>
												</cfif>
											</td>
										</tr>
									</table>
								</td>
							<!---- end of Event Table Row 20 A bunch of stuff mashed together ---->
```

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/arctos/issues/3320#issuecomment-765518885_

**Comment by Jegelewicz** [comment]
> I do a LOT with the identifiers in that table, they need to be very carefully preserved. I don't think it should matter where they are in relation to other stuff.
> 
> I recommend saving a copy of the entire file before you start messing with anything, just in case something stops working in some unforeseen use case.
> 
> Beyond that, oh please! That table is largely a product of evolution, a little intelligent design would be most welcome.

- Dusty

**Comment by Jegelewicz** [comment]
@dustymc before I do a lot, a question:

Is there a reason we don't present any verbatim information other than date and coordinates? As I was looking at a detail page, I wondered if it might even be better to just present a "verbatim event block" for comparison with the various specimen events because nowhere can anyone see what was the locality as recorded by the collector, just the date and coordinates. As specific localities are interpretations, anyone using them to geolocate are really interpreting an interpretation, no? We could present verbatim (collecting event) as it's own block at the bottom of the locality and maybe outline it in blue or purple OR we could just add verbatim locality under specific locality. Maybe no one cares? It just seem like we are hiding valuable information.

**Comment by dustymc** [comment]
Screen real estate, and it is (should be) only hidden when it matches "curatorial." I'd prefer to see verbatim as given - there's obviously some confusion with the magic - but what you see is what The Community decided at some point.

**Comment by Jegelewicz** [comment]
Yeah, I just figured that one out and it makes sense, but I'm not sure anyone would be aware of that...not sure it is a big deal either.

**Comment by Jegelewicz** [comment]
OK, so I moved verbatim locality (whenever it displays) up under specific locality and formatted it in the same manner as verbatim date and verbatim coordinates.

**Comment by Jegelewicz** [comment]
Also put all "locality" stuff except coordinates together and formatted verification agent and date like event assigner and date.

Next up - get coordinates up there too.

**Comment by Jegelewicz** [comment]
I'm getting close with this - have a meeting, but will return to it around 11am

**Comment by dustymc** [comment]
I like it.

You might replace the spaces with ``&nbsp;`` or mess with the CSS for labels:

<img width="137" alt="Screen Shot 2021-02-04 at 9 03 26 AM" src="https://user-images.githubusercontent.com/5720791/106928338-efa49d80-66c7-11eb-8098-d30e20044780.png">

or that might mess with other things.

I think I'd still like borders around the media blocks, but maybe I'm just a border aficionado.

**Comment by Jegelewicz** [comment]
Mr Border Man!

I think what bugs me is the bunch of blank space at the bottom of the media blocks. Also, why are we presenting the same thing twice? One of the media blocks says it is media from the same place and the other says it is media from the same place and time, but they both show media related to the event.

**Comment by dustymc** [comment]
> blank space

Not sure, weird CSS or a weird intersection of the data?

>One of the media blocks says it is media from the same place

Yes, that's critical to how @DerekSikes does things (and very cool for lots of reasons), it needs added back in.

> the other says it is media from the same place and time

Yep, that's collecting event media

> they both show media related to the event.

In some cases. It might make sense to pull locality-events MINUS current-event for the "same place" media, but that would need discussed.

https://handbook.arctosdb.org/how_to/How-to-understand-locality-media.html

**Comment by Jegelewicz** [comment]
Well, I related some media to the locality and it doesn't show up in the Place block...

**Comment by dustymc** [comment]
Because we're getting rid of that relationship - https://github.com/ArctosDB/arctos/issues/1608

**Comment by Jegelewicz** [comment]
OK - I'm feeling like I have something mostly workable (people will probably hate it) BUT

Why have we put locality attributes in a table format and event attributes in a not-table format? Should we pick one method and use it for both or do they really need to be so different?

![image](https://user-images.githubusercontent.com/5725767/106968244-ad01b600-6705-11eb-92de-28b21497218b.png)

**Comment by dustymc** [comment]
>Why

Evolution, probably. I like the table, whatever that's worth.

**Comment by Jegelewicz** [comment]
I think I do too - will change.

Also, just in case - the original for all of this is in the TJSandbox file.

**Comment by Jegelewicz** [comment]
OK - I'd love some people to review this. I've been using http://test.arctos.database.museum/guid/ASNHC:Mamm:5000 for testing - so it should have a little bit of everything, except:

@dustymc how in the heck do I edit "associated species"? I'm stumped and I feel like this has been left off the edit event screen?

@campmlc @mkoo @atrox10 @ccicero @ewommack @acdoll @DerekSikes

**Comment by Jegelewicz** [comment]
I need to work on the event details stuff so that it only takes up space when something is there.

**Comment by dustymc** [comment]
associated species is in coll object remark

**Comment by Jegelewicz** [comment]
OK, that's just nuts. Why is it editable there, but presented as part of the locality stack? Also, I added some to http://test.arctos.database.museum/guid/ASNHC:Mamm:5000 

![image](https://user-images.githubusercontent.com/5725767/107069001-8f345f80-679e-11eb-924c-4d9e055ddd1e.png)

but they do not show up where expected:

![image](https://user-images.githubusercontent.com/5725767/107069079-a96e3d80-679e-11eb-8dc0-ba021a5daaaf.png)

Here is the code from the locality block with the event remark stuff just before it:

```<!---- Event Table Row 10 Collecting Event Remark ---->
							<cfif len(COLL_EVENT_REMARKS) gt 0>
								<tr class="detailData">
									<td></td>
									<td id="SDCellRight" class="detailCellSmall">Remark:&nbsp;#COLL_EVENT_REMARKS#</td>
								</tr>
							</cfif>  
                            <!---- Event Table Row 19 Associated Species ---->
							<cfif len(one.associated_species) gt 0>
							<div class="detailBlock">
								<tr class="detailData">
									<td></td>
									<td id="SDCellRight" class="detailCellSmall">Associated&nbsp;Species:&nbsp;#one.associated_species#</td>
								</tr>
							</div>
						    </cfif>```

**Comment by acdoll** [comment]
I think the Date and Locality need to be at the top of the Event box. Those are the key details that (I think) people need to check first. All the other stuff is important, but ancillary. Personally, I would like to see it organized more like this:
Event Type: collection
	assigned by Cheryl A. Engstrom on 1986-06-27
Event Dates:	1986-06-27 to 1986-06-29
	Verbatim Date: 1986-06-27
Higher Geography:	North America, United States, Minnesota, Lake County more
Specific Locality:	14 mi E Isabella [ more ]
	Verbatim Locality: 14 mi E Isabella; Lake, Minnesota, United States 47.6168270000 -91.0540960000
	Standardized Place Name: United States, Minnesota, Lake County, Lake No. 1
Coordinates:	47.616827 / -91.054096
	Datum: World Geodetic System 1984
	Error: 5000 m
	Georeference Source: GEOLocate
	Georeference Protocol: GeoLocate
	Verbatim: 47.616827/-91.054096
Elevation:	100 to 150 m
Depth:	30 to 30 meters

Locality Attributes:	
Attribute	Value	Determiner	Method	Date	Remark
landholder	BLM	Teresa J. Mayfield-Meyer		2021-02-04	testing

Event Details:
	Collecting Method: by hand
	Collecting Source: wild caught
	Habitat: north slope, wetland
	Remark: this is a collection event remark
Event Attributes:	
	Attribute	Value	Determiner	Method	Date	Remark
	air temperature	75 fahrenheit				
	weather	cloudy	Teresa J. Mayfield-Meyer	sight	2021-02-04	testing
Event Verification:	unverified
	by Teresa J. Mayfield-Meyer on 2021-02-02
	Remark: this is an object Event Remark

**Comment by acdoll** [comment]
Sorry it cut all my nice indentations:

Event Type: collection
---assigned by Cheryl A. Engstrom on 1986-06-27
Event Dates: 1986-06-27 to 1986-06-29
---Verbatim Date: 1986-06-27
Higher Geography: North America, United States, Minnesota, Lake County more
Specific Locality: 14 mi E Isabella [ more ]
---Verbatim Locality: 14 mi E Isabella; Lake, Minnesota, United States 47.6168270000 -91.0540960000
---Standardized Place Name: United States, Minnesota, Lake County, Lake No. 1
Coordinates: 47.616827 / -91.054096
---Datum: World Geodetic System 1984
---Error: 5000 m
---Georeference Source: GEOLocate
---Georeference Protocol: GeoLocate
---Verbatim: 47.616827/-91.054096
Elevation: 100 to 150 m
Depth: 30 to 30 meters

Locality Attributes:
---Attribute Value Determiner Method Date Remark
---landholder BLM Teresa J. Mayfield-Meyer 2021-02-04 testing

Event Details:
---Collecting Method: by hand
---Collecting Source: wild caught
---Habitat: north slope, wetland
---Remark: this is a collection event remark
Event Attributes:
---Attribute Value Determiner Method Date Remark
---air temperature 75 fahrenheit
---weather cloudy Teresa J. Mayfield-Meyer sight 2021-02-04 testing
Event Verification: unverified
---by Teresa J. Mayfield-Meyer on 2021-02-02
Remark: this is an object Event Remark

**Comment by dustymc** [comment]
>Why...associated species

I think we just missed it when we rebuilt localities, and it's (obviously) been low-priority since.

**Comment by Jegelewicz** [comment]
@acdoll thanks for that feedback! I'll try to work on this tomorrow or early next week.

**Comment by Jegelewicz** [comment]
@acdoll how does it look now? - http://test.arctos.database.museum/guid/ASNHC:Mamm:5000

**Comment by ewommack** [comment]
I like the set up of the data. I could find things and it made sense in my brain. @acdoll I liked your ordering system.

Couple nitty gritty picky:
Is the doubling of the "Media from the Same Place" and "Media from the Same Place and Time" supposed to happen? 
![Untitled_1](https://user-images.githubusercontent.com/18562884/108913714-973a2f00-75e7-11eb-8e6f-bff46ea7e08b.jpg)

The titles for all of the Event sections are all on slightly different margins. It looks a little wonky:
![Untitled_2](https://user-images.githubusercontent.com/18562884/108913943-ed0ed700-75e7-11eb-8122-8b95867f39ac.jpg)

**Comment by Jegelewicz** [comment]
I said the same about the media, but @dustymc says it is something "cool"? - https://github.com/ArctosDB/arctos/issues/3403#issuecomment-773652873

> Event sections are all on slightly different margins

These are all aligned to the right - it is how they have always been (note the : all line up...). The tables of attributes cross both columns of the row, so they take up the whole space.

**Comment by acdoll** [comment]
> how does it look now?

Looks great! I can see all that critical information without scrolling - thanks.
