### ISSUE TITLE
Not sure about this error: iu_collector_coid_order_role

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#3404]
I am using the Manage Menu to  add an agent name to several records.

![image](https://user-images.githubusercontent.com/11336485/106664453-527c2480-6562-11eb-952d-f2f9047ff0d0.png)

When I try to add the agent, I receive the following error:
An error occurred while processing this page!
Message: ERROR: duplicate key value violates unique constraint "iu_collector_coid_order_role" Detail: Key (collection_object_id, coll_order, collector_role)=(23923191, 2, collector) already exists.
Detail:
Check the Arctos Handbook for more information on errors.
This message has been logged as 72A03F45-5274-49BD-8B4816B8BA09D3BE Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue.

This agent name is not a duplicate of any agent associated with the records. I have tried to insert the name in the first or last position, and both result in the same error.

**Comment by dustymc** [comment]
PG is handling transactions differently than Oracle - that form needs rebuilt for PG.

**Comment by ebraker** [comment]
Thanks!
