### ISSUE TITLE
Location in Host in nest vs free living stage

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3407]
From gracz:
I have run into a problem with "location in host" field. I have a lots of records that is something like "in nest" or "in active nest", "free living form", "questing" a variety of misc terms. In some cases the nest / den/ hole is identified by "host species", so there is a potential host for the larval flea, mite, or tick that was not removed from the skin of a specific host.

What shall we do? There is no entry in the  location_in_host table that indicate a "loose" or associated connection. At this point all of my entries except "skin" has to be deleted.

Perhaps add two entries:
location_in_host = "associated with" the parasite was collected in the nest, den, burrow, etc. of a species.

location_in_host = "free living form" for parasites that have can have forms or life stages that are free living (e.g. hookworm larva from soil) and in these records there should be no host id associated with the parasite.

The other option is (but still not implemented) is to have
location_in_host = "not recorded" and put some the text "in nest", "in burrow" into the remark field.
These are my ideas, let me know what you think.

**Comment by campmlc** [comment]
Good questions that relate to some current Github discussions. I think we could add "in nest" and "free-living stage" to  the"location in host" attribute, although that terminology of course is not completely accurate. Perhaps we should change "location in host" to "found in/on".  
You can use the "verbatim host ID" attribute for any host identification. I would recommend that you consider setting up a host observation catalog for things that have hosts recorded but no host voucher, and clone the parasite record so that both records share the same collecting event - the advantage of this is that host/parasite relationships become searchable across both host and parasite higher taxonomy, e.g. find all Ceratophyllidae from Sciuridae, regardless of how the verbatim host ID is recorded. 
Then you can set up a relationship between the parasite and host record, with the relationship "parasite of/host of" or "associated with" or "collected with", or as has been recently proposed, "attached to".
See the following github issues: https://github.com/ArctosDB/arctos/issues/1842 and https://github.com/ArctosDB/arctos/issues/3400.

**Comment by campmlc** [comment]
We also may want to consider a "behavior" attribute, e.g. for "questing", but of course this relates to far more than just ticks . . .

**Comment by campmlc** [comment]
from gracz:
There are some good points: for us, the "associated with" would be a good solution, but it opens up a whole new can of worms. One of them is creating an observation data for the host. I have several records that says: "in rodent nest" or "from bird nest". At this point I am inclined to add location_in_host="not recorded" and dump everything else ("in bird nest") in the remark section. 

Does Arctos allow that location_in_host is an empty field, so we only have a remark? My guess would be that it does not.

**Comment by campmlc** [comment]
If you use that attribute, I would say "location in host" is body surface, and put in nest in remarks. You can also put " collected in nest material" under attribute method. The main reason for this would be searchability, so you can find all ectoparasites, free living stages or otherwise.

**Comment by Jegelewicz** [comment]
I suggest we add a term to the location in host table:

undetermined - parasite found in association with the host, but the exact location cannot be determined

Then you could put "in nest" in the remark. If this seems like a good idea - please submit a code table request.

**Comment by dustymc** [comment]
"in nest" seems more like habitat than anything to do with a host to me. 

"behavior" attribute seems tenuous - how could you know it was "questing" when you collected it? Still, seems unlikely that we don't have a bunch of those data in remarks and etc., might be worth a dedicated Issue.

"free-living stage" sounds like a 'life stage' - https://github.com/ArctosDB/arctos/issues/2881

"of a species" is associated_species (which takes things like 'mouse nest')

"of a species" can be done with more precision by creating a relationship to a 'host' 

I think you'd probably find a reason to regret overloading 'location in host,' but I can't put my finger on anything at the moment so I don't think I'd object if you're sure you want to extend that to 'wandering around' or 'in nest' either.

NULL attribute value isn't possible, but 'indeterminate, see remarks' or something like it is.

**Comment by campmlc** [comment]
Nest parasites are important to document, because many species of flea for
example are only found in the nest, and there are soft ticks that do the
same -  they are feeding on the body surface when the animal is sleeping,
but they return to the nest afterwards and are not removed from the host
when it is captured out foraging.  In the nest and in the environment are
free-living detrivirous larval and immature stages of parasitic adults. We
need "found in nest" searchable in the same field as other parasite trait
data - it is already too hard for people to know where to look for specific
information, we need to make it easier, not harder. So for me this is a
discoverabilty issue. We can parse these data into many different fields,
but how does anyone know where to find them?

**Comment by campmlc** [comment]
And I should mention that knowing these "behaviours" or "locations" or
"habitats" or "life stages" is critically important for species
identification and understanding disease ecology and transmission risk of
potential pathogens they may be carrying.

**Comment by campmlc** [comment]
Perhaps we need a search field for "any trait data" which would search
across all attributes/traits/habitats etc, no matter where the data are
placed? But we'd run into the same problems we have now with "any ID" or
"any geography". The searches are all highly useful - how can we make them
actually work?
I support caching some searches needed at curatorial level, and sending an
email of results for searches that will take a long time, to avoid the
search time out.

**Comment by dustymc** [comment]
How you structure the data controls what questions is can answer. I can help you structure things in a way that doesn't lose information, but I can't tell you if that's usable or not. If we do adopt some lossy method, it should be clearly documented so it doesn't surprise the next potential user.

What exactly are 'problems we have now with "any ID" or "any geography".'?

**Comment by campmlc** [comment]
The problems we have had are that they timeout, similar to the problem with
searches on related IDs. Is this now fixed since we moved to PG?

**Comment by campmlc** [comment]
Perhaps we can keep location in host as anatomical terms - ideally to eventually tie in with an anatomical ontology -and add a separate attribute "found in/on".  This could be "nest", "burrow", "body surface", "leaf", "soil",  or maybe even open text, as horrid as that is, or allow for guids here - use attributes for one way relationships? @DerekSikes 
For a search example,  how would we find all larval fleas of family XX found in the nest of host YY  that were tested for plague and found to be positive . . .

**Comment by dustymc** [comment]
> use attributes for one way relationships?

Just use relationships, there is no reason to denormalize this.

> how would we find all larval fleas of family XX found in the nest of host YY that were tested for plague and found to be positive . . .

If you have all the relevant bits normalized and documented then that's a question with an answer, if you don't then it's not.

If I can put 'found in nest' in ``found in/on`` or ``habitat`` or ``relationships`` - if I can denormalize - then the absolute best case scenario involves multiple queries, and close to all users will find one of them, assume they've found everything, and leave. That is possibly as simple as documentation - "found in/on" might be a useful thing to have, but not if it's bleeding over into anything else (like relationships or habitat).

Data structure matters.

**Comment by campmlc** [comment]
So what would you suggest?

**Comment by dustymc** [comment]
>suggest

Probably things that require more work than you're willing to invest and/or information you don't have....

In general, I'd suggest using the most information-dense structure you can. A relationship to a host (which can have things like taxonomy) can do things that a categorical determination cannot, categorical data can do things that free-text can't, and categorized free-text (a "something about parasites" attribute, for example) is more accessible than uncategorized (eg the same information in specimen remarks).

Reality is probably going to force you to use all of that at times, but good published documentation mitigates the impact. If you're doing something random then I'm probably not going to find what I'm looking for in it, but if you have some sort of "when cataloging, use {this} unless {situation} then use {that}, and if you can't even do that you can {something else}" documentation published in the handbook, then maybe I can make sense of the data even if they're not organized ideally.

I suppose "be as consistent as you can" is the take-home, and that starts with good documentation. Eg any attribute that might be confused with habitat should include 'use this instead of habitat when....'

**Comment by Jegelewicz** [comment]
with regard to habitat - meh - this field is a dumping ground and as it is part of collecting event (most of which is "verbatim" stuff) perhaps we should view it in the same way we do "verbatim locality". You put whatever was in the field catalog there, but you parse it out into attributes for discoverability. "found in nest" sounds like a specimen event attribute, but it is probably true that no one will look for it there. I also agree that location in host should be limited to anatomical terms. How about an attribute called "microhabitat" with controlled values such as "nest", "burrow", "body surface", "leaf", "soil"? I think it really should be a specimen event attribute, but I could also see an argument for making it an object attribute....

**Comment by campmlc** [comment]
@gracz and I looked over his data, and what would work for at least the time being with the immediate upload would be to add the following to location in host:
Term: unattached   Definition: parasite is found off of the host, e.g. as a free-living species or life stage, or one that occurs in a nest, burrow, dwelling, or in a free-living environment such as soil.    Specify nest/burrow/dwelling/soil in attribute.        
Term: undetermined           Definition: Used for location in host when a parasite location cannot be accurately determined, e.g. somewhere in the body cavity, or crawling on the lab table
Thoughts?

**Comment by dustymc** [comment]
``Location in host: not in host`` is akin to using a ``county`` field for ocean data - it's going to severely limit what can be done with any data in the obviously-not-what-it-says concept, and make anyone looking at the data suspect you've done similar things elsewhere and so nothing should be trusted.

``undetermined`` MIGHT be defensible, but certainly not when extended to "crawling on the lab table."

That said, these DO seem to be of roughly the same intent so perhaps it's acceptable to add them with the knowledge that "location in host" needs a new name and definition.

**Comment by campmlc** [comment]
How about "location of parasite"? Which makes "unattached" and "in nest" a
bit more defensible.

**Comment by Jegelewicz** [comment]
So a new attribute type = location of parasite?

I think I like that less than location in host = undetermined

But if we stick with

> keep location in host as anatomical terms - ideally to eventually tie in with an anatomical ontology

it does seem like "undetermined" would still leave the impression that it was in/on the host

But now I am thinking that this would also bring into question any host/parasite relationship that might be made. In any case, if two records had a host/parasite relationship, I would expect the parasite to have the "location in host" attribute, correct? And I also think that "in" should include "on", which would cover "body surface" as described above. When the "parasite" is only found nearby, then I would expect a relationship of "collected with" and perhaps a better attribute would add information to that relationship - this could help clear up why just sharing a collection event (10 birds from the same field on the same day) doesn't quite get to the detail of "collected with" (two of the 10 were shot off the same branch together). However, I am struggling to come up with a term for this!

collected with relationship
association
????

Just thinking out loud...

**Comment by campmlc** [comment]
In most legacy cases, we have no host voucher, location in host, or even a
host ID. I've suggested creating a host relationship to a host observation,
but that does double the work and, of course, the cost. I think a
relationship is always preferable, but regardless location in host is a
separate data type.
And we don't always have that info.

We need the flexibility of recording what info we do have in a consistent
fashion, even if we move it later.
My suggestion for location of parasite was as a new name for location in
host, to make adding unattached and undetermined more acceptable.
We can discuss this interminably, but we need to make a quick decision
here, even if temporary, to capture legacy data for a grant funded project
that has been held up for some time.

**Comment by Jegelewicz** [comment]
So, location in host = location of parasite?

That seems so out of place in a huge list of anatomical features. Just go with what you started with but with a little change

Term | Definition 
 --| -- 
unattached | Used for location in host when parasite is found near, but not on the host, e.g. as a free-living species or life stage, or one that occurs in a nest, burrow, dwelling, or in a free-living environment such as soil. Specify nest/burrow/dwelling/soil in attribute remarks. 
undetermined | Used for location in host when a parasite location cannot be accurately determined, e.g. somewhere in the body cavity, or crawling on the lab table.

**Comment by campmlc** [comment]
That works for me! And if we later revise the model it should be easy to
extract those to put somewhere else.

**Comment by dustymc** [comment]
Done via #3411
