### ISSUE TITLE
Cannot edit a collecting event in test

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3408]
In test when attempting to add an event remark, after clicking save I get this:

An error occurred while processing this page!
Message: variable [ORIG_LAT_LONG_UNITS] doesn't exist
Detail:
Check the Arctos Handbook for more information on errors.

This message has been logged as 21996B19-6DE5-4AB5-8D28538B24AEF666 Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue.

**Comment by dustymc** [comment]
THanks, I'm working with https://github.com/ArctosDB/arctos/issues/2930, I'll make sure that's functional before it goes out.
