### ISSUE TITLE
Code Table Addition - new location in host

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3411]
Addition would be to https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlocation_in_host

@gracz and I looked over his data, and what would work for at least the time being with the immediate upload would be to add the following to location in host:
Term: unattached   Definition: parasite is found off of the host, e.g. as a free-living species or life stage, or one that occurs in a nest, burrow, dwelling, or in a free-living environment such as soil.    Specify nest/burrow/dwelling/soil in attribute remarks.        

Term: undetermined

Definition: Used for location in host when a parasite location cannot be accurately determined, e.g. somewhere in the body cavity, or crawling on the lab table

Thoughts?

_Originally posted by @campmlc in https://github.com/ArctosDB/arctos/issues/3407#issuecomment-774187930_

**Comment by campmlc** [comment]
Are there any objections to this? I'd like to move forward with the addition to Location in Host asap if not. Note revised definitions.

1) Term: unattached 

Definition: parasite is found off of the host, e.g. as a free-living species or life stage, or one that occurs in a nest, burrow, dwelling, or in a free-living environment such as soil. Any relevant collection methodology details may be added to the Attribute Collection Method field, and specific habitat details (nest/burrow/dwelling/soil et) should be added to Attribute Remarks. 

2) Term: undetermined

Definition: Used for location in host when a parasite location cannot be accurately determined, for example, if the collector did not record the parasite's location, or if  the collecting method made the correct determination unreliable (e.g. organ rupture). Any relevant collection methodology details may be added to the Attribute Collection Method field, and specific habitat details (nest/burrow/dwelling/soil et) should be added to Attribute Remarks.

**Comment by Jegelewicz** [comment]
Who else has parasites - can we solicit their input directly?

**Comment by dustymc** [comment]
>Who else has parasites 

That's a little personal, don't you think?

https://github.com/ArctosDB/arctos/issues/3407#issuecomment-774200263

**Comment by campmlc** [comment]
MSB and HWML are the primary Arctos parasite collections and the second and
third largest parasite collections in the New World. So I think if we both
agree, that should cover most of the active parties. Happy for anyone else
to pitch in, but we need to have this resolved right away.

**Comment by campmlc** [comment]
Actually, having parasites can be a good thing . . . fewer allergies, for
one!

**Comment by campmlc** [comment]
Here are the main parasite collections according to the American Society of Parasitologist: https://www.amsocparasit.org/parasite-museums
Note Sam Houston makes the list - I wonder what CMS they are using? :)

**Comment by dustymc** [comment]
>having parasites can be a good thing

Parasitologists....

```
select guid_prefix,count(*) c from collection
inner join cataloged_item on collection.collection_id=cataloged_item.collection_id
inner join coll_obj_other_id_num on cataloged_item.collection_object_id=coll_obj_other_id_num.collection_object_id
where id_references in ('host of','parasite of')
group by guid_prefix;


 guid_prefix |   c   
-------------+-------
 CHAS:Bird   |     5
 CHAS:Ento   |     6
 DMNS:Bird   |   326
 DMNS:Mamm   |   628
 DMNS:Para   |   947
 HWML:Para   |   861
 KNWR:Ento   |    26
 KNWR:Herb   |    11
 MSB:Bird    |   210
 MSB:Fish    |     3
 MSB:Host    | 16674
 MSB:Mamm    | 12086
 MSB:Para    | 30496
 MVZ:Bird    |     2
 MVZ:Mamm    |    73
 NMU:Mamm    |    19
 NMU:Para    |    20
 UAM:Ento    |  6696
 UAM:Inv     |     3
 UAM:Mamm    |  7964
 UCM:Mamm    |     2
 UMNH:Mamm   |    11
 USNPC:Para  |    99

```

**Comment by Jegelewicz** [comment]
@acdoll and who should we ask in Alaska?

**Comment by campmlc** [comment]
@DerekSikes 
@acdoll 
I'm going to add the attributes - but we need a parasite discussion group! Or relationships committee . . . . or both.  I'm in - anyone else?

**Comment by campmlc** [comment]
Added.

**Comment by Jegelewicz** [comment]
Better add me to the discussion group for now - I'll be your taxonomy point person.

**Comment by acdoll** [comment]
I'm slow on the draw here, but those terms and definitions look good to me. Thanks for adding them

**Comment by gracz-UNL** [comment]
Thanks for adding them. I have already used some of the new terms.
