### ISSUE TITLE
[CONTACT] 404 from persistent URL

### ISSUE THREAD

**Issue by MattBlissett** [ArctosDB/arctos#3414]
The persistent URL http://arctos.database.museum/guid/CUMV:Amph:16023 or http://arctos.database.museum/guid/CUMV:Amph:16023?seid=2660598 is not resolving.

It's published in GBIF at https://www.gbif.org/occurrence/1852461331 (at the very bottom), and I found it as it happens to be an example used in our [documentation on publishing data](https://github.com/gbif/ipt/wiki/occurrenceData#templates), via  https://github.com/gbif/ipt/issues/1530

Other URLs from the same dataset also fail.

**Comment by mkoo** [comment]
Hello Matt, Cornell is no longer in the Arctos network so I think this is an issue with the Vertnet IPT-- @dbloom can you help update? let us know if we can help otherwise
