### ISSUE TITLE
UTM Zone

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3415]
Ref: https://github.com/ArctosDB/arctos/issues/2660 - I'm converting UTM to coordinates

UTM needs zone information to be converted - https://upload.wikimedia.org/wikipedia/commons/b/b7/Universal_Transverse_Mercator_zones.svg

I don't actually need the letter band, but I do need to know northern or southern hemisphere. I'd like to not make that unnecessarily painful for users, but I'd also not like to lose information. I think there are three viable approaches to this.

1. Just require letter bands on incoming data. This will ensure that Arctos has everything necessary to convert, will not require Arctos to make any assumptions, and will have the information expected by other systems. It's also probably a lot of work for anyone dealing with "legacy" UTM (unless they cheat, which will result in flaky 'as-entered' data).
2. Split the world into two "bands," north and south. This is what PostGIS does, and I think it's probably what's happened in a fair bit of existing UTM data (in which "S" may mean "south" or "Zone S"). This would also require some conversion by users - eg, Zone 13S (New Mexico) would need converted to "13North." I cannot claim to fully understand UTM and therefore I'm not sure if any information would be lost in that, but it doesn't seem to be anything that I can make use of.
3. Allow both, under which Zone 13 would include:

 * 13C (Antarctica)
 * 13D (cold ocean)
 * ...
 * 13M (warmer ocean)
 * 13C-M (everything south of the equator in zone 13)
 * 13N (more ocean)
 * 13P (almost to Mexico!)
 * ...
 * 13X (maybe come Canadian islands?)
 * 13N-X (everything north of the equator in zone 13)

Zone 13 would include only 2 [SRIDs](https://en.wikipedia.org/wiki/Spatial_reference_system), one for north and one for south, in any of those approaches - I don't think there's any technical difference on my end. (1) seems most correct, least likely to lose anything of value, and most likely to work in other systems, but also the most work. (2) would result in relatively few code table values, but would not be capable of carrying all of the information that might come in. (3) is sort of weird - we'd pass that mixed information on to eg GBIF where it might melt things - but might also be the most usable.

Help!

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I'm in favor of 2 or 3. An argument for 2 is that, as far as postgis knows, band zones other than north or south make no difference to the coordinate. Technically, from what I've been reading, I think they're not actually part of UTM, just often used with UTM, and are actually part of the Military Grid Reference System (which may explain some of the odd zones we saw when you pulled the zone data). If someone wanted to record them, they could put it in a verbatim field.

Another option - we have one field for zone #, one field for North/South, and one optional field for band letter.

**Comment by dustymc** [comment]
(3) it is, for now - easy to revisit at any time, I really just need the SRID

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctutm_zone
