### ISSUE TITLE
Error adding barcode using scary red box

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3416]
From student:
"I’m trying to add barcode A8PYN (container label in arctos) to NK 166661 L (position C2:A28:2:17). It has a path in the parts page. I tried using the red box to add barcode. I got the error: 

Message: ERROR: triggercaught:::Changing barcode is not allowed Where: PL/pgSQL function trigger_fct_trg_container_content_control() line 178 at RAISE

I tried to problem solve this error message with multiple samples to no avail."

Same happened to me with my login,
Chrome
Priority High- blocking loans

**Comment by dustymc** [comment]
This is basically the opposite of https://github.com/ArctosDB/arctos/issues/3395 - I'll see if I can find some middle ground, but essentially you can (previously) or can't (currently) do strange things with barcodes so I'm not sure there's much safe space to be had. Can I further restrict access to the scary red thing?

**Comment by campmlc** [comment]
We need this tool at MSB to add barcodes to legacy DGR containers. We also
use it, and I imagine other collections would use it (UAM) to replace
barcodes that have fallen off, for example, without changing the container
history.  It is an important tool. As for access, my students with manage
specimens need to use the tool as we pull legacy formerly DGR Locator
samples for loan and barcode them.

**Comment by campmlc** [comment]
This tool was working in Oracle - so not sure what happened with the PG
migration.

**Comment by dustymc** [comment]
>what happened with the PG migration

A better security model became available.

There's now a hole aimed at the scary-swapper.

**Comment by campmlc** [comment]
OK - we'll try not to misuse it!
