### ISSUE TITLE
Summarize by higher taxon has double duplicate names

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#3417]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

I'm trying to get a summary of the holdings in the UAM Insect collection by Order. However, some specimens are identified using the A or B formula and these are turning up in the summarize by list as duplicate order names.

For example there would be a row for 

Coleoptera

and another row for

Coleoptera, Coleoptera

here's a saved search: http://arctos.database.museum/saved/doubleordernames

I would like this to not happen if the names are identical. I could see the value of this if the names were different (eg. Coleoptera, Hemiptera) but if they are identical this means I have to manually combine all these rows myself externally, and if I wanted to share a saved search with someone they'd also be presented with this weirdness.

**Describe what you're trying to accomplish** 
An clear and concise overview of the goals; why are you asking for this?

**Describe the solution you'd like**
How might we accomplish your goals?

Summarize by should treat formula A or B specimens as formula A specimens for any higher taxa that are identical while summarizing. (in most cases when A or B is used it is because the id of is unknown to species but is known to higher taxonomic levels so forcing A or B to exist at all levels up the classification is greatly exaggerating the uncertainty and of course, if the two choices are the same (Coleoptera or Coleoptera) then it is just silly.

**Describe alternatives you've considered**

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.
Medium

**Comment by dustymc** [comment]
This is best discussed in https://github.com/ArctosDB/arctos/issues/3231
