### ISSUE TITLE
Suddenly unable to create a loan!

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/arctos#3419]
Form looks incomplete...
![image](https://user-images.githubusercontent.com/43214224/107534046-2aee1300-6b85-11eb-9aad-439047cb801d.png)

**Comment by Jegelewicz** [comment]
@mbprondzinski what exactly is the problem?

**Comment by Jegelewicz** [comment]
The loan exists

![image](https://user-images.githubusercontent.com/5725767/107540151-f8431b00-6b82-11eb-8b92-89350a9c8dc4.png)

**Comment by mbprondzinski** [comment]
It wouldn't let me create a loan.  There wasn't any problem on my end.  It kept saying I was missing loan type or number or etc, etc.  which wasn't the case.  I finally had to log out of Arctos and try again, which then it worked.  But I didn't do anything different!

**Comment by mbprondzinski** [comment]
Yeah, now it does, but it didn't after I logged in the second time.

**Comment by campmlc** [comment]
Please take a screenshot if it happens again!

**Comment by mbprondzinski** [comment]
I did and I included it in the Git Hub comment.

**Comment by Jegelewicz** [comment]
I don't know that we can determine what happened - closing for now.

**Comment by mbprondzinski** [comment]
You didn't notice that form looks weird?  That screenshot is not the same form that I used for all the other loan entries.

**Comment by Jegelewicz** [comment]
I don't manage a collection, so I don't create loans - it looks normal to me, but I am no expert.
