### ISSUE TITLE
Code Table Request - Catalog Item Type

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3421]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Goal**
Appropriately describe item types.

**Context**
See discussion in #2432 

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcataloged_item_type

**Value**
**Definition**
Term | Definition 
 -- | -- 
living specimen | A biological specimen that is alive. [TDWG](https://dwc.tdwg.org/terms/#livingspecimen) 
preserved specimen | A biological specimen that has been preserved. [TDWG](https://dwc.tdwg.org/terms/#preservedspecimen) 
fossil specimen | A preserved biological specimen that is a fossil. [TDWG](https://dwc.tdwg.org/terms/#fossilspecimen) 
human observation | An output of a human observation process. [TDWG](https://dwc.tdwg.org/terms/#humanobservation) 
machine observation | An output of a machine observation process. [TDWG](https://dwc.tdwg.org/terms/#machineobservation) 
item | An individual cultural object or work.[Getty AAT](http://www.getty.edu/vow/AATFullDisplay?find=&logic=AND&note=&subjectid=300404024) 

**Collection type**
N/A

**Attribute data type**
N/A

**Attribute value**
N/A

**Attribute units**
N/A

**Part tissue flag**
N/A

**Other ID BaseURL**
N/A

**Priority**
Please assign a priority-label.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I support this.

**Comment by dustymc** [comment]
Minor request: If I need to "translate" these for DWC, please put the translation in the definition.

See https://github.com/ArctosDB/arctos/issues/2432#issuecomment-758818208 for context.

See also https://handbook.arctosdb.org/how_to/How-to-Use-Code-Tables.html - (5) suggests we should just use the DWC values (but I'm not fond of eg "PreservedSpecimen" either).

**Comment by Jegelewicz** [comment]
Term | Definition 
 -- | -- 
living specimen | A biological specimen that is alive. [LivingSpecimen](https://dwc.tdwg.org/terms/#livingspecimen) 
preserved specimen | A biological specimen that has been preserved. [PreservedSpecimen](https://dwc.tdwg.org/terms/#preservedspecimen) 
fossil specimen | A preserved biological specimen that is a fossil. [FossilSpecimen](https://dwc.tdwg.org/terms/#fossilspecimen) 
human observation | An output of a human observation process. [HumanObservation](https://dwc.tdwg.org/terms/#humanobservation) 
machine observation | An output of a machine observation process. [MachineObservation](https://dwc.tdwg.org/terms/#machineobservation) 
item | An individual cultural object or work.[Getty AAT](http://www.getty.edu/vow/AATFullDisplay?find=&logic=AND&note=&subjectid=300404024)

**Comment by Jegelewicz** [comment]
Would you prefer the DwC term come first?

**Comment by dustymc** [comment]
Don't care, that's fine.

**Comment by Jegelewicz** [comment]
new terms added
