### ISSUE TITLE
New Higher Geographies

### ISSUE THREAD

**Issue by AdrienneRaniszewski** [ArctosDB/arctos#3422]
I need a couple higher geographies added. Thank you!

Asia, Japan, Ehime Prefecture, Shikoku
	https://en.wikipedia.org/wiki/Ehime_Prefecture
	https://en.wikipedia.org/wiki/Shikoku
Asia, Japan, Hokkaido Prefecture, Sorachi Subprefecture, Hokkaido
	https://en.wikipedia.org/wiki/Sorachi_Subprefecture
	https://en.wikipedia.org/wiki/Hokkaido

**Comment by AdrienneRaniszewski** [comment]
Hi! Wondering how this is coming along...

**Comment by dustymc** [comment]
These look reasonable to me, but Japan geog is a mess (I'll open an Issue) so ????????? - would be good to get more review.

@ArctosDB/geo-group is there a procedure for handling this?

**Comment by mkoo** [comment]
Sorry-- these slipped through on my emails.

Our general rule of thumb is to limit non-US administrations to admn0 and
admin1 divisions. So for Japan that would be to Prefectures (which are
admin1 divisions according to wikipedia (
https://en.wikipedia.org/wiki/Prefectures_of_Japan)
The subprefectures and municipalities  would go in Specific Localities.

And as usual, anything that hasnt been looked at is a mess from legacy
entries! (It's MVZ!)

Back to your request: I just created Ehime Prefecture--
https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10016063
Hokkaido already exists in Arctos and would suggest that the subprefecture
goes into the Locality field. I suggest the same for the other
subprefectures. (
https://arctos.database.museum/Locality.cfm?action=editGeog&geog_auth_rec_id=10005132
)

I would like to add the rest of the JAPAN prefectures so we will create
WKTs for the prefectures.

Let me know if that works for you!

**Comment by AdrienneRaniszewski** [comment]
I used the subprefecture since that one locality had one and all the other subprefectures I needed were already in Arctos. But if we’re moving away from that, that sounds fine. Thanks!


~ Adrienne




part-time schedule: T W Th
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Adrienne Raniszewski
Collections Associate/Staff Coordinator

Division of Mammals
Museum of Southwestern Biology
University of New Mexico
msb.unm.edu/divisions/mammals<http://www.msb.unm.edu/divisions/mammals/index.html>
aranis@unm.edu<mailto:aranis@unm.edu>
505-277-5369

visit us on Facebook<https://www.facebook.com/MSBDivisionofMammals>
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

On Feb 16, 2021, at 10:05 AM, Michelle Koo <notifications@github.com<mailto:notifications@github.com>> wrote:

  [EXTERNAL]

Sorry-- these slipped through on my emails.

Our general rule of thumb is to limit non-US administrations to admn0 and
admin1 divisions. So for Japan that would be to Prefectures (which are
admin1 divisions according to wikipedia (
https://en.wikipedia.org/wiki/Prefectures_of_Japan)
The subprefectures and municipalities would go in Specific Localities.

And as usual, anything that hasnt been looked at is a mess from legacy
entries! (It's MVZ!)

Back to your request: I just created Ehime Prefecture--
https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10016063
Hokkaido already exists in Arctos and would suggest that the subprefecture
goes into the Locality field. I suggest the same for the other
subprefectures. (
https://arctos.database.museum/Locality.cfm?action=editGeog&geog_auth_rec_id=10005132
)

I would like to add the rest of the JAPAN prefectures so we will create
WKTs for the prefectures.

Let me know if that works for you!

**Comment by Jegelewicz** [comment]
@AdrienneRaniszewski can we close?
