### ISSUE TITLE
data entry: ID references

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3424]
move it left

**Comment by dustymc** [comment]
<img width="696" alt="Screen Shot 2021-02-18 at 8 39 03 AM" src="https://user-images.githubusercontent.com/5720791/108389754-d110cd00-71c4-11eb-9c9b-e8d5d97861cc.png">

**Comment by Jegelewicz** [comment]
I'm guessing this is still going to be confusing, but it is what we came up with!
