### ISSUE TITLE
error when bulkloading parts

### ISSUE THREAD

**Issue by AdrienneRaniszewski** [ArctosDB/arctos#3425]
**Describe the bug**
I'm uploading extra parts using the new batch load interface.  All of my parts produced an error that I've never seen and don't understand. 

load fail::ERROR: null value in column "entered_person_id" violates not-null constraint Detail: Failing row contains (29638407, SP, null, 2021-02-10 00:00:00, null, null, on loan, 1, unknown, null).

**To Reproduce**
1. Go to Enter Data > Batch Tools > Part > Bulkload Parts
2. Click on load csv > choose file > check all and change status to autoload > status status for checked records to the above value
3. wait 
4. See error - load fail::ERROR: null value in column "entered_person_id" violates not-null constraint Detail: Failing row contains (29638407, SP, null, 2021-02-10 00:00:00, null, null, on loan, 1, unknown, null).

**Expected behavior**
I expected the part to load as usual

**Screenshots**
<img width="1413" alt="Screen Shot 2021-02-10 at 4 11 14 PM" src="https://user-images.githubusercontent.com/23192428/107586045-753eb680-6bbc-11eb-8d5c-fa07857ae611.png">

**Desktop**
 - OS: MacOS 10.15.7
 - Browser: Chrome
 - Version: 88.0.4324.150

**Comment by dustymc** [comment]
iTs YouR CrazY userNaME!

``getagentid()`` is no longer case-sensitive - those should load now.

Next release will have a better error handler.
