### ISSUE TITLE
Still Having Problems Creating Loans

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/arctos#3427]
When I try to save a created loan, I get this error message:
![image](https://user-images.githubusercontent.com/43214224/107677676-26e2f380-6c60-11eb-9479-662ec86c0dfb.png)

Here is the loan I'm trying to save:
![image](https://user-images.githubusercontent.com/43214224/107678329-df109c00-6c60-11eb-9042-46ac53cca809.png)

**Comment by dustymc** [comment]
That "nice" error message will be gone in the next release - I can't see what's going on with it there.

It's probably https://handbook.arctosdb.org/documentation/understanding-errors.html#missing-expression (which needs revised for PG)

> common with Agent Picks, remove a character from the end of the data your browser has so helpfully supplied and hit TAB - a popup window should open (and usually immediately self-close) and the selected data should turn green, indicating it is safe to save.

**Comment by campmlc** [comment]
Did you hit tab after entering the agent names, and were they all accepted?
Looks like in house and outside contacts aren't yellow?

**Comment by mbprondzinski** [comment]
I did hit tab and they were yellow until I tried to save it.

**Comment by dustymc** [comment]
If they're not green it's not going to work. https://handbook.arctosdb.org/documentation/understanding-errors.html#missing-expression

<img width="686" alt="Screen Shot 2021-02-11 at 10 27 28 AM" src="https://user-images.githubusercontent.com/5720791/107681360-cea5f480-6c53-11eb-85ea-240fe83f14c1.png">

**Comment by mbprondzinski** [comment]
They were green before I saved it.  The names were already uploaded year(s) ago so they aren't anybody new.

**Comment by campmlc** [comment]
Sounds like something wrong with the agent validation in the form? But I've
had it work recently. Are there hidden popups on your end?

**Comment by mbprondzinski** [comment]
Not that I'm aware of.  I will try it again after the meeting.  It may just be this one loan.  I've been entering quite a number of them, but this one has been giving me probems.

**Comment by campmlc** [comment]
Check those agents and see if there might be an issue with those.
