### ISSUE TITLE
Feature Request - Add handbook How-to page links (documentation handler update)

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#3428]
Please add a link to the How-to handbook page on tool pages (eg. bulkloader pages) in a consistent, friendly button near the top. 

@dustymc will figure out implementation

**Comment by dustymc** [comment]
This needs to be abstracted through some lookup, so that we're not changing code in hundreds of places when something changes with the handbook URL. We have a documentation mechanism, but it's dangerous and scary and complicated and few people have access, and it's probably just overkill for this. 

Can/should we use the redirect mechanism (https://handbook.arctosdb.org/documentation/redirect.html)? It's less-dangerous so more people can access, there's a bulkloader (and could easily be an unloader), and it seems sufficient for this. I made https://arctos.database.museum/handbook/component_loader as a test.

**Comment by mkoo** [comment]
I like using existing tools for solutions (also love that redirect table!)

That seems to work too-- what about overall workflow? Dropping in buttons
on pages? How will we know that
https://arctos.database.museum/handbook/component_loader is on the
Bulkoader cfm page if we need to update?

Also is there an edit option on the redirects page (or do we need to delete
and add new to update any links)?

**Comment by dustymc** [comment]
>edit

Not currently, but that's just UI (to a 2-column table) and it could easily do WHATEVER.


>will we know that https://arctos.database.museum/handbook/component_loader is on the Bulkoader cfm page if we need to update?

git grep works, but I'm not sure how many of us use those kinds of tools.


>workflow

Needs discussed in as much depth as possible so we can identify and problems before we start digging this hole, but in general I think it would be...

* develop some sort of pluggable button-or-whatever that takes a parameter (eg, "component_loader")
* Plug it - it would call a local redirected URL (eg /handbook/component_loader)
* Make sure there's a redirect for that

Missing redirects would just 404 and that ends up in my logs, which is one point in favor of this. I just opened

https://arctos.database.museum/this_is_not_redirected

and got

 404! The page you tried to access does not exist. 

and an entry in the usual place (https://arctos.database.museum/Admin/errorLogViewer.cfm?.cfm?lmt=&btime=&etime=&usr=&lastMins=&ip=&request_id=18FC9C44-A500-411E-AF94122E3371646C&)

<img width="1368" alt="Screen Shot 2021-02-11 at 12 46 17 PM" src="https://user-images.githubusercontent.com/5720791/107696738-2ef26180-6c67-11eb-9db5-73ed498880cc.png">

**Comment by ewommack** [comment]
Could we add a link at the top of the pages like: https://arctos.database.museum/handbook/component_loader that links to the [quick tutorial page](https://arctosdb.org/learn/tutorial-blitz/)? That might help connect some of the different documentation resources we have.

**Comment by dustymc** [comment]
There's the start of a documentation handler in test. It needs testing.

For pages without page help and users without manage_documentation, you should see nothing different.

For pages with page help, you should see a new link on the top-right of the page body.

<img width="334" alt="Screen Shot 2021-02-17 at 10 41 29 AM" src="https://user-images.githubusercontent.com/5720791/108251825-c2ff7580-710c-11eb-8576-6e1bc2795021.png">

For pages without page help and users with manage_documentation, you should see a different link....

<img width="225" alt="Screen Shot 2021-02-17 at 10 42 36 AM" src="https://user-images.githubusercontent.com/5720791/108251913-e0ccda80-710c-11eb-8293-d609c28050f8.png">

... which will dump you on the redirect form, which has some additional instructions (and prefilled values if you linked in)

<img width="1327" alt="Screen Shot 2021-02-17 at 10 44 28 AM" src="https://user-images.githubusercontent.com/5720791/108252185-330dfb80-710d-11eb-9e9c-0e74771cfb64.png">


Provide an appropriate handbook link, click the button....

<img width="497" alt="Screen Shot 2021-02-17 at 10 45 49 AM" src="https://user-images.githubusercontent.com/5720791/108252279-53d65100-710d-11eb-96fd-b93ca4074d53.png">

and after the cache refreshes....

<img width="434" alt="Screen Shot 2021-02-17 at 10 47 21 AM" src="https://user-images.githubusercontent.com/5720791/108252467-897b3a00-710d-11eb-948b-51c13313cd64.png">

... there's page help.

@ewommack in general, yes please, crosslinks are awesome. Anyone writing a /how_to should probably also be adding links to /documentation as well - maybe something for the [how-to-how-to](https://handbook.arctosdb.org/how_to/How-to-Contribute-Content-to-Arctos-Handbook.html).
