### ISSUE TITLE
GloBI dupes with Vertnet

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3429]
See https://github.com/globalbioticinteractions/globalbioticinteractions/issues/602

**Comment by campmlc** [comment]
Is GloBI harvesting from both VertNet and Arctos, or just from VertNet?
Arctos is using the VertNet IPT - is that affecting this? Are these just a
few scattered duplicates? I don't see anything obvious that would make this
one a special duplicate . . .

**Comment by Jegelewicz** [comment]
There are about 150 in just this one genus...

**Comment by campmlc** [comment]
So are all Arctos relationships duplicated?

**Comment by Jegelewicz** [comment]
Nope - it was a bit of a mash-up

**Comment by dustymc** [comment]
GloBI is doing the correct thing. Most data that go to DWC have low-bar licenses, those allow manipulation, and I think we've all seen ridiculous "corrections" from various portals at various times. There are lots of reasons to record what exact data you were considering when dealing with them (preferably by grabbing a DWCa).

Arctos changes as well - tossing a download on something like dryad and mentioning it as supplemental in publications should probably be somewhere on https://handbook.arctosdb.org/how_to/cite-specimens.html. (I think it was at one point...)
