### ISSUE TITLE
Code Table Request - new age class categories for ectoparasites

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3432]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Goal**
Add new age class categories for different tick and mite instars

**Context**
Existing values do not exist

**Table**
Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm

From email request: 
table age_class has only a very few options for "Para" and I am hitting a problem with that.
here are some additional categories

hypopus     The hypopus is a modified juvenile stage of the mite, and is thought to correspond to the deutonymph (the second of up to three nymphal stages). It is heavily sclerotized, heteromorphic, e.g. very different from the preceding and subsequent nymphal stages. It lacks mouth parts but carries ventral suckers or claspers for adhering to arthropods or vertebrates. The hypopus serves to disperse the species.  

protonymph              the second development stage in acarids (second instar) after larva

deutonymph         the third developmental stage in acarids (after protonymph)

tritonymph          fourth developmental stage (of certain) acarids after deutonymph

mixed life stages    is used when there are various larval and adult forms in the container (this can be especially the case with mites, lice, ticks, juvenile and adult acanthocephalans, various stages of nematodes (L1, L2, adult), etc.

**Collection type**
Para, Host

**Priority**
High, need this asap for bulkload to make TPT grant reporting deadline.

**Comment by dustymc** [comment]
I can't tell if these are new values, or new ways of saying old things. These look a lot like "dialects" to me, and if that's the case then they'd be a simple case of denormalization.

Is eg "protonymph" just another way that some folks say "2nd instar" or is it something different? If the latter, how exactly is it different?

I can see no place for "mixed" here - if you know multiple things you can just list them all, if you don't then you can use age (free-text) to say whatever needs said.

**Comment by campmlc** [comment]
The terms are legit, assuming you credit the authors at the University of
Michigan and the USDA in Ft. Collins.
https://idtools.org/id/mites/beemites/bmites_lifestages.php
We really need an ontology here. But for now, we really just need to add
the terms.
I don't see why we can have mixed for age classes when we allow "sexes
mixed". Yes, ideally all the stages would be given separate age class
attributes, but we are limited in the number of attributes to 10, and
legacy datasets may not specify which stages, only that they are "mixed".

**Comment by Jegelewicz** [comment]
I mean, these are in the code table without any definition, so why not sexes mixed?

Term | Collections | Definition 
-- | -- | --
adult, juvenile | Ento |  
adult, pupa | Ento |  
adult/juvenile | Amph Herp Mamm Rept |  
adults, larva | Ento

**Comment by Jegelewicz** [comment]
> The terms are legit, assuming you credit the authors at the University of Michigan and the USDA in Ft. Collins. https://idtools.org/id/mites/beemites/bmites_lifestages.php

I say add them and link the definitions to the above as well as Wiktionary:

Term | Wiktionary | Definition  
 -- | -- 
deutonymph | https://en.wiktionary.org/wiki/deutonymph | The third instar of a mite. 
protonymph | https://en.wiktionary.org/wiki/protonymph | The instar between larva and deutonymph.
tritonymph | https://en.wiktionary.org/wiki/tritonymph | The instar between deutonymph and adult in some organisms.

**Comment by dustymc** [comment]
>terms are legit

So are lots of things, having [189 ways of saying the same thing](https://soyouthinkyoucandigitize.wordpress.com/2013/07/18/data-diversity-of-the-week-sex/) still prevents users from accessing the data.

>ontology

An ontology would not lead to storing equivalent terms.

>mixed for age classes when we allow "sexes mixed".

We don't have three ways of specifying sex; there's a clearly appropriate alternative here. 

>why not sexes mixed

I don't see flaky data as justification for more flaky data.

**Comment by campmlc** [comment]
Making sure we have appropriate taxon specific terms is essential for
discoverability. A mite person looking for deteronymph will not know to
look under second instar - why would they? They will look for the accepted
terms used in their field. We cannot retrain the entire world of
taxonomists to look for Arctos specific terms. We could however, customize
and filter terms by taxon if we had the capacity to do so through our
interface.
This is holding up bulkloading legacy data due for NSF reporting by Feb 26.

**Comment by campmlc** [comment]
Update: One addition: deutonymph is already in the age_class table, but only available to "ento". There is "nymph" available for Ento, but Para can only use "larva, nymph".

**Comment by Jegelewicz** [comment]
> deutonymph is already in the age_class table, but only available to "ento".

just add that to para.

**Comment by campmlc** [comment]
Added nymphal stages.
