### ISSUE TITLE
Can we do more with preparators?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3433]
@ebraker said in an email:
> We should add this MSB record to arctosdb.org as an example of a gold standard record – it’s a good one!:
> 
> https://arctos.database.museum/guid/MSB:Para:176 

I agree, BUT it does point out our deficiencies in giving preparators their due:
![image](https://user-images.githubusercontent.com/5725767/107974826-636e6200-6f74-11eb-948f-d7b8f80682c5.png)
 
Damien is not listed in the "collectors" section, but even if he were, there wouldn't be a real connection between him and the part he prepped (in this case it appears he was only "good" while "unknown" prepared an excellent slide). I really think we could be doing more here, especially for paleo collections where the preparator can really matter.

**Comment by dustymc** [comment]
I don't think this is a need that https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcollector_role can meet - a "preparation" part attribute seems much more capable of handling this information.

**Comment by ebraker** [comment]
Agreed. When collector_role = preparator is used in combination with attibute_determiner, the specimen prep date can be indirectly deduced. Adding preparator and date to part_attributes would be great to make this connection a bit more transparent. A preparator part_attribute would also be useful for slides and subsampling etc. that occur after the initial specimen preparation.

**Comment by campmlc** [comment]
Agree!

**Comment by dustymc** [comment]
specimen_part_attribute has determiner - I think this is happy?

**Comment by Jegelewicz** [comment]
Well we can do this now - but we should make an effort to get the data in the right place? I was going to put Damien Jouet in as determiner for the preservation attribute, but not sure if I should just replace what is there or....
