### ISSUE TITLE
Feature Request -  IIIF capabilities in Arctos

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3434]
From MSB grad student generating CT scans of MSB specimens:
"I was wondering if I could get your permission to talk with TACC about adding IIIF capabilities to Arctos records.  IIIF is how sites like Exhibit.so are storing 3D data so that it can be viewed interactively and remotely.  This would just be for surface information like we are uploading to Sketchfab (not entire CT scan data sets) - so they are fairly small and compact.

In researching who is generating IIIF files, I found that lots of repositories are adding this capability to their records (https://guides.iiif.io/).  So, it shouldn't be an insurmountable hurdle for TACC (if there is time for them to add it and it doesn't impact costs to MSB)."

**Comment by campmlc** [comment]
Hi John, is this just a tool to visualize data? Most current CT scans in Arctos are archived at a designated repository like MorphoSource, and we just link the record. The image is viewed at MorphoSource. Would this tool allow us to visualize 3D within Arctos? Would it require the image files to be stored at TACC? If so, how many terabytes? Am I understanding correctly?

**Comment by campmlc** [comment]
From JKorbin: 
My best understanding is IIIF is a standard that is being developed for collections to all speak the same language.  I believe it is being developed mostly by Europeans.  

The files I would add to a record are typically between 10 and 200 Mb in size.

**Comment by ebraker** [comment]
See #2863 and comment #1785

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/2863
