### ISSUE TITLE
Code Table Request - add dorsal spine as part for fish collections

### ISSUE THREAD

**Issue by zmsch** [ArctosDB/arctos#3438]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Goal**
Add "dorsal spine" as a part name option for fish collections

**Context**
The only appropriate existing part name is "skeletal element" which is too vague and does not convey how part is used (aging fish)

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name

**Value**
dorsal spine

**Collection type**
Fish

**Part tissue flag**
No

**Comment by Jegelewicz** [comment]
Suggest the use of "spine" with the [anatomical direction attribute](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctanatomical_direction) "dorsal".

**Comment by zmsch** [comment]
That works--request that spine be added as a part for fish collections.

**Comment by Jegelewicz** [comment]
Done.
