### ISSUE TITLE
Dangerous URLs in Test?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3439]
I recently installed Bitdefender and now whenever I log into Test, I am confronted with this:

![image](https://user-images.githubusercontent.com/5725767/108246638-e6c3bb00-710e-11eb-92eb-090c6cd518dc.png)

So I tell it to take me there anyway and then I get this:

![image](https://user-images.githubusercontent.com/5725767/108246666-f17e5000-710e-11eb-97a7-a5965b8eb071.png)

What gives?

**Comment by dustymc** [comment]
https://github.com/ArctosDB/internal/issues/68

We don't have a certificate for test so it's running plain-text.
