### ISSUE TITLE
Reviewed Annotation not in the green count

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3440]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I found a record with a reviewed annotation, yet in the "comment or report bad data" section, the annotation still shows up as 1 in the red.

**To Reproduce**
1. Go to https://arctos.database.museum/guid/MSB:Mamm:156731

![image](https://user-images.githubusercontent.com/5725767/108253205-c0098280-7116-11eb-9a2e-ba160f07ebb6.png)

see annotation and that it has been reviewed:
![image](https://user-images.githubusercontent.com/5725767/108253333-e4fdf580-7116-11eb-974b-dfa6cbdb8d8f.png)

**Expected behavior**
I expect to see [1] in green and [0] in red in the "comment or report bad data" section.

**Screenshots**
See above

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**
Trying to put together an annotation tutorial for [GBIF discussion](https://discourse.gbif.org/t/annotating-specimens-and-other-data/2419/12?u=jegelewicz). Want to make sure it makes sense.

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by dustymc** [comment]
thx/fxd
