### ISSUE TITLE
component loader notifications

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3442]
1. Include a link to https://handbook.arctosdb.org/documentation/notifications.html#why-am-i-getting-this (which will need modified if (3) comes to be).
2. Link to the loaders
3. Is there a way to better target notifications, and if so should we? Current is a net-approach that gets all involved manage_collection users, could perhaps be more linear.

**Comment by alexkrohn** [comment]
I will put my hat in the ring for being able to select which notifications you want to get. For example, Carla Cicero helps manage the UCSC collection from afar. She helped us get set up, and sometimes helps us get out of binds when we mess things up. I want to keep her on as a manager of our collection, but would prefer not to get emails associated with changes she makes to agents, code tables, etc.

**Comment by dustymc** [comment]
Next release will link to https://handbook.arctosdb.org/documentation/notifications.html#why-am-i-getting-this and to individual loaders.

<img width="737" alt="Screen Shot 2021-06-24 at 4 33 32 PM" src="https://user-images.githubusercontent.com/5720791/123345011-f8c4c880-d509-11eb-8033-b9ce855b633a.png">

I am not sure what else I can do, so I'm kicking this back down for more discussion.

* Many of these data aren't (yet, sometimes) linked to collections - they're globally-shared taxonomy or an identifier that's not yet been loaded (perhaps through a different loader) or etc. All I can go by is the user.
* I can't tell who a multi-collection agent was working for at the time. Carla (and several of us who fix things, mentor, etc.) has equal access to MVZ and UCSC and even though that access isn't used for the same purposes I don't have any way of telling which hat she was wearing when something was created in a loader; the only safe thing to do is to alert everyone who might be involved.

Using something from https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_contact_role rather than manage_collection might be a bit more specific, but I think it would be mostly the same people, it would be absolutely the same situation as above, and I suspect some collections would miss these altogether.

Clever ideas appreciated!
