### ISSUE TITLE
Feature Request - offer options as typed in taxonomy search fields

### ISSUE THREAD

**Issue by gmfaircloth** [ArctosDB/arctos#3444]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
Misspelling items when searching through the database is a common error when searching scientific nomenclature terms

**Describe what you're trying to accomplish** 
An type-ahead function that attempts to complete a user's search while they are typing in a search box

**Describe the solution you'd like**
An type-ahead function that attempts to complete a user's search while they are typing in a search box

**Describe alternatives you've considered**
A drop box potentially

**Additional context**
It doesn't need to work initially, maybe after 3-4 characters

**Priority**
Would like this feature to be completed within the next month

**Comment by dustymc** [comment]
@ArctosDB/arctos-working-group-officers this is for the ALMNH API - I'll need help prioritizing.

@gmfaircloth I need more information - what exactly would you like your input and results to be?

Alternatively Arctos does offer a taxonomy download - there's a link in https://github.com/ArctosDB/arctos/issues/3205#issuecomment-758809795 - which you could use to build whatever you want.

**Comment by acdoll** [comment]
I'd guess they're looking for something like in SCAN (https://scan-bugs.org/portal/collections/harvestparams.php) where a big list  appears below the search field, narrowing options as you type more characters.

**Comment by dustymc** [comment]
See https://github.com/gmfaircloth/UA-Museums-Capstone-2021/issues/6#issuecomment-814379064

https://github.com/gmfaircloth/UA-Museums-Capstone-2021/files/6241637/Dusty.-.Search.Extras.docx

I'd still need (much) more information to do anything. For example, the idea that all Phylum = “Arthropoda”, are contained within Kingdom = “Animalia” (or that all arthropods carry Phylum = “Arthropoda”) is not necessarily true even within a single Source.

**Comment by campmlc** [comment]
I get a 404 on following those github links.

**Comment by Jegelewicz** [comment]
@dustymc I think this would only apply to taxon names. When I go to search a name in GBIF this is what happens as I type

![image](https://user-images.githubusercontent.com/5725767/146273664-d3b98c4e-7fc6-41fd-acd0-29cab691d7b9.png)

![image](https://user-images.githubusercontent.com/5725767/146273708-f2ee04fb-6dad-4920-a2e3-dd22da752752.png)

![image](https://user-images.githubusercontent.com/5725767/146273739-8eed6193-cbcf-4b7c-9215-661945daaf08.png)

The list of potential names updates with every letter I type (and I can select from the list if I want or just keep typing).

Possible in Arctos? So typing here:

![image](https://user-images.githubusercontent.com/5725767/146273925-5165b15c-fd09-479c-918c-4debf20e0501.png)

would look like

![image](https://user-images.githubusercontent.com/5725767/146274357-1cc0cbf4-1753-4744-be31-c2bf422c72ac.png)

**Comment by sharpphyl** [comment]
Yes, but right now it would also bring up misspelled names.  

Suggestion 1:  Have the list not include quarantined names and move forward with Teresa's Quarantine issue [#4204](https://github.com/ArctosDB/arctos/issues/4204) to get more of these names out of the system or into quarantine. A search starting with "Cominella ads" looking for _Cominella adspersa_ also brings up: _Cominella adsparsa_ and _Cominella adsphersa_ which are misspellings in the taxon database.

<img width="312" alt="Screen Shot 2021-12-18 at 9 08 10 AM" src="https://user-images.githubusercontent.com/15368365/146648004-7f1438c6-d6c7-400b-9924-29cb75838b5e.png">

Suggestion 2:  Show metadata as only the correct spelling has a WoRMS (via Arctos) classification.

<img width="507" alt="Screen Shot 2021-12-18 at 9 23 40 AM" src="https://user-images.githubusercontent.com/15368365/146648238-d38b061a-c39a-4d34-b672-68d8244f23e5.png">

Suggestion 3:  Have the dropdown only show names that have a classification in our preferred source WoRMS (via Arctos).

**Comment by dustymc** [comment]
There's been more discussion via email, I think it's safe to say this just can't happen at the scale of Arctos. If they find something that works - probably some data file, at least initially - I'll open a new (probably API-related) issue.

> When I go to search a name in GBIF 

... you're searching a relatively simple data structure that's presumably organized in a predictable way. Arctos is not that simple. (A limited API perhaps can be - that's what I'm exploring with ALMNH now.)

It would be possible (with some infrastructure support, probably) to suggest names, but that's not what's been requested. (And it's not what some - maybe most - users would want, the relationship between taxonomy and identifications is not simple in Arctos.)

> Show metadata 

I'm not sure how that's related to the original request, but for most users that would need to be something like https://arctos.database.museum/name/Conus - 325 (really) opinions - to be useful. (Again, some more-focused API may be able to ignore 324 of those opinions.)

>which are misspellings 

https://github.com/ArctosDB/arctos/issues?q=is%3Aopen+is%3Aissue+label%3AQuarantine doesn't find them - open a quarantine request, please!

>only show names that have a classification in our preferred source

Most users won't have a preferred source; they're looking for {thing} and may or may not agree with your idea of how {think}'s metadata should be organized.
