### ISSUE TITLE
Question on error report from Data Entry Screen

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#3445]
I am entering info into the Data Entry field for a new UWYMV:Bird collection. I think I got everything added that was required, but I'm getting the following error:

![Arctos error question](https://user-images.githubusercontent.com/18562884/108413142-dcc1bb00-71e7-11eb-91c8-51baa537ad0b.jpg)

ERROR: new row for relation "bulkloader" violates check constraint "ck_part_remark_1_noprt"; ; INSERT INTO bulkloader ( collection_object_id , loaded , enteredby , accn , guid_prefix , cat_num , other_id_num_1 , other_id_num_type_1 , other_id_references_1 , other_id_num_2 , other_id_num_type_2 , other_id_references_2 , collector_agent_1 , collector_role_1 , collector_agent_2 , collector_role_2 , taxon_name , nature_of_id , id_made_by_agent , made_date , identification_remarks , identification_confidence , other_id_num_3 , other_id_num_type_3 , other_id_references_3 , other_id_num_4 , other_id_num_type_4 , other_id_references_4 , other_id_num_5 , other_id_num_type_5 , collector_agent_3 , collector_role_3 , collector_agent_4 , collector_role_4 , collector_agent_5 , collector_role_5 , locality_id , locality_name , collecting_event_id , collecting_event_name , higher_geog , spec_locality , locality_remarks , verbatim_locality , verbatim_date , began_date , ended_date , coll_event_remarks , maximum_elevation , minimum_elevation , orig_elev_units , min_depth , max_depth , depth_units , orig_lat_long_units , dec_lat , dec_long , latdeg , dec_lat_min , latmin , latsec , latdir , longdeg , dec_long_min , longmin , longsec , longdir , datum , georeference_source , max_error_distance , max_error_units , georeference_protocol , utm_zone , utm_ew , utm_ns , specimen_event_type , specimen_event_remark , event_assigned_by_agent , event_assigned_date , verificationstatus , collecting_method , collecting_source , habitat , associated_species , locality_attribute_type_1 , locality_attribute_value_1 , locality_attribute_remark_1 , locality_attribute_determiner_1 , locality_attribute_detr_meth_1 , locality_attribute_detr_date_1 , locality_attribute_units_1 , locality_attribute_type_2 , locality_attribute_value_2 , locality_attribute_remark_2 , locality_attribute_determiner_2 , locality_attribute_detr_meth_2 , locality_attribute_detr_date_2 , locality_attribute_units_2 , locality_attribute_type_3 , locality_attribute_value_3 , locality_attribute_remark_3 , locality_attribute_determiner_3 , locality_attribute_detr_meth_3 , locality_attribute_detr_date_3 , locality_attribute_units_3 , locality_attribute_type_4 , locality_attribute_value_4 , locality_attribute_remark_4 , locality_attribute_determiner_4 , locality_attribute_detr_meth_4 , locality_attribute_detr_date_4 , locality_attribute_units_4 , locality_attribute_type_5 , locality_attribute_value_5 , locality_attribute_remark_5 , locality_attribute_determiner_5 , locality_attribute_detr_meth_5 , locality_attribute_detr_date_5 , locality_attribute_units_5 , locality_attribute_type_6 , locality_attribute_value_6 , locality_attribute_remark_6 , locality_attribute_determiner_6 , locality_attribute_detr_meth_6 , locality_attribute_detr_date_6 , locality_attribute_units_6 , part_name_1 , part_condition_1 , part_barcode_1 , part_lot_count_1 , part_disposition_1 , part_remark_1 , part_preservation_1 , part_name_2 , part_condition_2 , part_barcode_2 , part_lot_count_2 , part_disposition_2 , part_remark_2 , part_preservation_2 , part_name_3 , part_condition_3 , part_barcode_3 , part_lot_count_3 , part_disposition_3 , part_remark_3 , part_preservation_3 , part_name_4 , part_condition_4 , part_barcode_4 , part_lot_count_4 , part_disposition_4 , part_remark_4 , part_preservation_4 , part_name_5 , part_condition_5 , part_barcode_5 , part_lot_count_5 , part_disposition_5 , part_remark_5 , part_preservation_5 , part_name_6 , part_condition_6 , part_barcode_6 , part_lot_count_6 , part_disposition_6 , part_remark_6 , part_preservation_6 , part_name_7 , part_condition_7 , part_barcode_7 , part_lot_count_7 , part_disposition_7 , part_remark_7 , part_preservation_7 , part_name_8 , part_condition_8 , part_barcode_8 , part_lot_count_8 , part_disposition_8 , part_remark_8 , part_preservation_8 , part_name_9 , part_condition_9 , part_barcode_9 , part_lot_count_9 , part_disposition_9 , part_remark_9 , part_preservation_9 , part_name_10 , part_condition_10 , part_barcode_10 , part_lot_count_10 , part_disposition_10 , part_remark_10 , part_preservation_10 , part_name_11 , part_condition_11 , part_barcode_11 , part_lot_count_11 , part_disposition_11 , part_remark_11 , part_preservation_11 , part_name_12 , part_condition_12 , part_barcode_12 , part_lot_count_12 , part_disposition_12 , part_remark_12 , part_preservation_12 , attribute_1 , attribute_value_1 , attribute_date_1 , attribute_det_meth_1 , attribute_determiner_1 , attribute_2 , attribute_value_2 , attribute_date_2 , attribute_determiner_2 , attribute_3 , attribute_value_3 , attribute_date_3 , attribute_determiner_3 , attribute_4 , attribute_value_4 , attribute_date_4 , attribute_determiner_4 , attribute_5 , attribute_value_5 , attribute_date_5 , attribute_determiner_5 , attribute_6 , attribute_value_6 , attribute_units_6 , attribute_date_6 , attribute_determiner_6 , attribute_7 , attribute_value_7 , attribute_remarks_7 , attribute_date_7 , attribute_det_meth_7 , attribute_determiner_7 , attribute_8 , attribute_value_8 , attribute_remarks_8 , attribute_date_8 , attribute_det_meth_8 , attribute_determiner_8 , attribute_9 , attribute_value_9 , attribute_remarks_9 , attribute_date_9 , attribute_det_meth_9 , attribute_determiner_9 , attribute_10 , attribute_value_10 , attribute_remarks_10 , attribute_date_10 , attribute_det_meth_10 , attribute_determiner_10 , coll_object_remarks , wkt_media_id , flags , uuid , cataloged_item_type ) values ( nextval('bulkloader_pkey') , 'waiting approval' , 'ewommack' , '[UWYMV:Bird]1' , 'UWYMV:Bird' , '1455' , '149' , 'UWYMV:Egg' , 'same individual as' , null , null , null , 'A. B. Mickey' , 'collector' , null , 'collector' , 'Megascops asio' , 'features' , 'Elizabeth A. Wommack' , '2021-02-12' , null , 'medium' , null , null , null , null , null , null , null , 'collector number' , null , 'collector' , null , 'collector' , null , 'collector' , null , null , null , null , 'North America, United States, Iowa, Poweshiek County' , 'Grinnell' , null , 'Grinnell, Iowa' , 'no date recorded' , '1800-01-01' , '2012-08-22' , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , 'collection' , null , 'Elizabeth A. Wommack' , '2021-02-12' , 'unverified' , null , 'wild caught' , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , 'egg' , 'unchecked' , null , '2' , 'in collection' , 'unknown if full clutch unknown if full clutch unknown if full clutch' , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , null , 'sex' , 'unknown' , '2021-02-12' , null , 'Elizabeth A. Wommack' , 'age' , null , '2021-02-12' , 'Elizabeth A. Wommack' , 'fat deposition' , null , '2021-02-12' , 'Elizabeth A. Wommack' , 'molt condition' , null , '2021-02-12' , 'Elizabeth A. Wommack' , 'skull ossification' , null , '2021-02-12' , 'Elizabeth A. Wommack' , 'weight' , null , 'g' , '2021-02-12' , 'Elizabeth A. Wommack' , null , null , null , '2021-02-12' , null , 'Elizabeth A. Wommack' , null , null , null , '2021-02-12' , null , 'Elizabeth A. Wommack' , null , null , null , '2021-02-12' , null , 'Elizabeth A. Wommack' , null , null , null , '2021-02-12' , null , 'Elizabeth A. Wommack' , null , null , null , null , null )

Anyone know what I'm doing wrong?

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/3020 - how can I replicate?

**Comment by ewommack** [comment]
Logged in -> Enter Data -> Data Entry -> Enter a new UWYMV:Bird Record -> Enter Data
I was creating UWYMV:Bird:1455, which is the same individual of UWYMV:Egg:149. I was hand entering the data, so I'm not sure how to give you that data. I definitely made sure each of the yellow fields were filled in.

**Comment by Jegelewicz** [comment]
This would be an ideal place for pulling from the Egg record....

**Comment by ewommack** [comment]
Pulling the data?

**Comment by Jegelewicz** [comment]
Want a demo?

**Comment by ewommack** [comment]
Sorry google is suddenly marking all GITHUB emails as spam. I've been loosing some messages.
Sure, is it similar to cloning when splitting lots? I've done that.

And an @dustymc update - I entered some other catalog records through the individual data entry screen for birds on Friday and they went through fine. So I was doing something really weird with that bird record. If it happens again I'll take a screen shot of the data entry screen for you so you can try entering the same data into the field.

**Comment by campmlc** [comment]
Definitely recommend pulling from the Egg data. Use the tiny little "pull"
function next to ID references in the Identifiers table. Put in the catalog
number of the Egg, choose "same individual as", and "pull" - select
collection event, agents, etc as needed.

**Comment by dustymc** [comment]
merge-->#3020
