### ISSUE TITLE
Berkeley Mapper reveals masked coordinates

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3453]
From user:
"I've got a series of specimens for which I've encumbered coordinates for all but one of the records. These are specimens that belong to a researcher who doesn't want the coordinates available, so I want to mask the coordinates.
But when I am logged out and search on them, I can still map them all in Berkeley Mapper under the tools drop down menu at the top of the results. When I click on a point in the map, it gives the coordinates for all the records at that point.
So they're not really encumbered.
Can this be fixed?
Priority: Urgent

**Comment by dustymc** [comment]
The leak was plugged at 530PST, about 3.5 hours before this was filed.

There is now a better solution in test. It needs tested.
