### ISSUE TITLE
[CONTACT]

### ISSUE THREAD

**Issue by aklompma** [ArctosDB/arctos#3455]
Hi Dusty,

Recently, ALMNH:EH was split into ALMNH:Paleo and ALMNH:Geo. Thanks for your help!
Currently, I cannot edit the records anymore because my profile was not reassigned to both. 
Could you assign my profile to the two new collections?

Best wishes,
Adiel

**Comment by dustymc** [comment]
I don't have access either. @mbprondzinski was listed as both the admin and mentor users. Let us know if that doesn't solve your problem and we'll figure something out.

**Comment by mbprondzinski** [comment]
Hey Adiel, I found you!  What is your "username" as opposed to your "agent" name?!  Try that...it works.

**Comment by aklompma** [comment]
My username is: aklompma

**Comment by mbprondzinski** [comment]
try it again.

**Comment by aklompma** [comment]
Unfortunately, I still cannot select a collection after logging in.
