### ISSUE TITLE
Limit to the number of class_term allowed in a classification bulkload?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3456]
I recently loaded a bunch of classifications for the TPT (via Arctos) source and I have discovered that while the file contained 18 class_term and class_term_type columns, only 10 loaded. This leaves all of those classifications truncated. For an example see https://arctos.database.museum/name/Acanthophthirius%20acinipus#TPTviaArctos

Is there a limit of ten class_terms in a classification bulkload file? If so, we need to think about increasing, if not, what happened to my bulkload?

**Comment by dustymc** [comment]
Uh - neat.... 

Will 12 noclass and 20 class work for you?

**Comment by Jegelewicz** [comment]
I think so, but look at the Open Tree of Life classification for this taxon - it has like 22 class_terms. Let's start with 25 class?

**Comment by dustymc** [comment]
The table has 12 and 20 now, it's sort of a pain to change that (as you can tell by the failure). I can get you there by just doing what I failed to do (I think I patched, then forgot to go backwards). 

If we're going to go beyond that, then it would be fairly useful to not have to do so again for a while, but I'm also not thrilled at the idea of the template returning a bajillion columns. Is that number 25, or should we look bigger, or???

https://arctos.database.museum/name/Mustela%20jacksoni#ThePaleobiologyDatabase (first random PBDB thing I found) has 50 classification terms.

Pick a number....

Or number**s** - I can't think of a reason to have more nonclass terms, but if there is one now's a good time.

```
arctosprod@arctos>> select term from taxon_term where classification_id='288516|212579|2|85325|67102|85323|67145|33815|67149|67344|34881|67348|219195|77135|53190|125547|37177|99766|56749|53189|38882|38935|39168|67366|39183|67452|67455|67456|36651|108999|137608|64369|57710|67561|39860|182911|91965|92585|192307|72264|136662|36905|54044|71870|41085|67879|41086|65327|41139|105202' and position_in_classification is not null;
         term         
----------------------
 Eucarya
 Opisthokonta
 Metazoa
 Eumetazoa
 Triploblastica
 Nephrozoa
 Deuterostomia
 Chordata
 Vertebrata
 Gnathostomata
 Osteichthyes
 Sarcopterygii
 Dipnotetrapodomorpha
 Tetrapodomorpha
 Tetrapoda
 Reptiliomorpha
 Anthracosauria
 Batrachosauria
 Cotylosauria
 Amniota
 Synapsida
 Therapsida
 Cynodontia
 Epicynodontia
 Eucynodontia
 Probainognathia
 Mammaliamorpha
 Mammaliaformes
 Mammalia
 Theriamorpha
 Theriiformes
 Trechnotheria
 Cladotheria
 Boreosphenida
 Theria
 Eutheria
 Placentalia
 Laurasiatheria
 Scrotifera
 Ferae
 Carnivoramorpha
 Carnivora
 Caniformia
 Canoidea
 Arctoidea
 Musteloidea
 Mustelidae
 Mustelinae
 Mustela
 Mustela jacksoni
(50 rows)
```

**Comment by Jegelewicz** [comment]
Is infinity an option? :-/

50 is a nice round number, but given PBDB it may not be enough - and soonish if we can actually use PBDB?

For my purposes at this time, 30 would cover it, but 50 could mean we don't need to revisit this for a while and maybe never?

> I can't think of a reason to have more nonclass terms, but if there is one now's a good time.

Maybe go ahead and make it 20 just in case? I'm probably OK with 12, but doing things in groups of 10 just feels a bit nicer...

**Comment by dustymc** [comment]
>Is infinity an option? :-/

Nope, welcome to denormalization. PG claims to handle 1600 columns so ~half that minus (2xnoclass) minus a few is possible, if perhaps not much fun in Excel. That's probably the same as ∞ for all practical purposes.

>if we can actually use PBDB?

If you can get it into CSV - and I think you could - then yup, you can use it.

GN is normalized so if PBDB is coming through there then there are no limitations.

So 50 classifications and 20 non? Anyone have a use case that might exceed that? Maybe 60 and 20 (~160 columns) in anticipation of PDBD-like data??

**Comment by Jegelewicz** [comment]
> Maybe 60 and 20 (~160 columns) in anticipation of PDBD-like data??

Sounds good to me - I'll let anyone else with an opinion weigh in.

**Comment by campmlc** [comment]
I agree with the larger number and accommodating PDBD.  Especially if
people don't realize their classifications are automatically truncated when
they load - we should also add a notification if the upload exceeds the
limit.

**Comment by dustymc** [comment]
>automatically truncated

That's just a bug - https://github.com/ArctosDB/arctos/issues/3456#issuecomment-784326112
