### ISSUE TITLE
Feature Request - Agent Search needs to be more personable

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3458]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
The agent search page doesn't offer users any information about how to search or what agents are.

**Describe what you're trying to accomplish** 
Make this search more accessible and useful

**Describe the solution you'd like**
Add some context to the page to help users know what to do.

**Describe alternatives you've considered**
Just leave it opaque

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by Jegelewicz** [comment]
@mkoo @campmlc I added some text with directions and a definition in test - let me know how it could be better.

http://test.arctos.database.museum/agent.cfm

**Comment by dustymc** [comment]
Seems like a good use case for [page help](https://github.com/ArctosDB/arctos/issues/3428). @Jegelewicz are you seeing this?

<img width="195" alt="Screen Shot 2021-02-23 at 9 12 17 AM" src="https://user-images.githubusercontent.com/5720791/108880569-46aadd80-75b7-11eb-82a2-d9a020d14d7e.png">

**Comment by Jegelewicz** [comment]
Yep - I'll ad that too, but we figured a quick intro would help this page a bit.

**Comment by Jegelewicz** [comment]
BTW - adding this in test won't transfer to prod will it?

**Comment by dustymc** [comment]
no

**Comment by ewommack** [comment]
Looks good to me! 
Are we linking to tutorials? There is one on searching Arctos for Agents: [Agents Search](https://arctosdb.org/learn/tutorial-blitz/#agents)

**Comment by campmlc** [comment]
Looks good - nice simplification!
My only comment would be to consider changing the title of the form and in
general, the persistent use of "AGENTS" in our UI to "PEOPLE,
ORGANIZATIONS" - because when we discuss these terms outside of Arctos,
many people do not understand the term "agents" in the context of our
usage.

**Comment by Jegelewicz** [comment]
> Are we linking to tutorials?

I'll do this once that functionality hits production.

> consider changing the title of the form and in general, the persistent use of "AGENTS" in our UI to "PEOPLE, ORGANIZATIONS" 

I think that needs its own issue. However - I think that "agent" is gaining popularity. See https://discourse.gbif.org/t/attributing-work-done-data-attribution/2422

> Questions to promote discussion
> 
> Group 1 What is an **Agent**, Who are the Actors, What do they Expect?

**Comment by dustymc** [comment]
> once that functionality hits production.

It's been there for a while, just waiting for data.

**Comment by Jegelewicz** [comment]
I don't see it?

![image](https://user-images.githubusercontent.com/5725767/108904438-b763f100-75db-11eb-9ba5-cd03202670d2.png)

**Comment by dustymc** [comment]
Hu. What's https://arctos.database.museum/dumpAll.cfm say about session ROLES?

The check is

```
	<cfif isdefined("session.roles") and listfindnocase(session.roles, "manage_documentation")>
				<cfset r='no pagehelp: you can <a class="newWinLocal" href="/Admin/redirect.cfm?old_path=/handbook/#pg#&create_old_path=/handbook/#pg#&action=search">create a link</a>'>
			</cfif>
```

and https://arctos.database.museum/AdminUsers.cfm?Action=edit&username=jegelewicz says you have manage_documentation. Maybe something interesting in your JS console? Your browser is hoarding an old copy of the JS library?

**Comment by Jegelewicz** [comment]
So what should I do?

**Comment by dustymc** [comment]
first shift-reload then

What's https://arctos.database.museum/dumpAll.cfm say about session ROLES?

if that doesn't work

**Comment by Jegelewicz** [comment]
shift-reload worked, but

> Are we linking to tutorials? 

I think the best help we can offer here is the YouTube tutorial - https://youtu.be/MfXTtQ2A5hY

I added that, but nothing happens.
![image](https://user-images.githubusercontent.com/5725767/108914016-031c9780-75e8-11eb-9fd4-9b1a21ce1818.png)

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/3428
and after the cache refreshes....

**Comment by Jegelewicz** [comment]
> and after the cache refreshes....

How long does that take? I added the Agent link yesterday and this morning it still wasn't showing. Of course, I changed it this morning because I added a How To, but still...

**Comment by dustymc** [comment]
Not that long!

> {some Handbook URL} must be a valid URL which starts with https://handbook.arctosdb.org 

I deleted this:

<img width="322" alt="Screen Shot 2021-02-24 at 7 46 37 AM" src="https://user-images.githubusercontent.com/5720791/109026310-77048180-7674-11eb-9e3d-f624403026cd.png">

Googled "/how_to/How-to-Search-Agent" which lead me to https://handbook.arctosdb.org/how_to/How-to-Create-Agents.html which seems reasonable so...

<img width="327" alt="Screen Shot 2021-02-24 at 7 48 49 AM" src="https://user-images.githubusercontent.com/5720791/109026617-c8147580-7674-11eb-96ac-4b4fe5244f16.png">

and now we wait....

**Comment by Jegelewicz** [comment]
So - enter everything after the domain name instruction is not valid?

**Comment by dustymc** [comment]
Ah - neat, nope, that's not true for external links. I'll change it.

**Comment by Jegelewicz** [comment]
It worked.

**Comment by Jegelewicz** [comment]
But it isn't the right link - how do I change it easily?

**Comment by dustymc** [comment]
>change

Delete and re-create.

**Comment by Jegelewicz** [comment]
Where? How do I know what the old one is?

**Comment by dustymc** [comment]
>Where?

<img width="243" alt="Screen Shot 2021-02-24 at 9 41 22 AM" src="https://user-images.githubusercontent.com/5720791/109041981-7e338b80-7684-11eb-8422-8aed43bece9a.png">

>How do I know what the old one is?

<img width="819" alt="Screen Shot 2021-02-24 at 9 42 16 AM" src="https://user-images.githubusercontent.com/5720791/109042074-9dcab400-7684-11eb-95d2-dc41d8360b52.png">

**Comment by Jegelewicz** [comment]
K - needs documentation or is it written down somewhere?

**Comment by dustymc** [comment]
>needs documentation

And/Or maybe a rebuild - I think that UI is almost old enough to vote....

**Comment by Jegelewicz** [comment]
Yeah - seems like we could streamline this somehow. Could we create something just like https://arctos.database.museum/doc/field_documentation.cfm, but each row would be an Arctos page? I realize that redirect is used for more than that, but this would let us manage links to help more efficiently.
