### ISSUE TITLE
Citations link in Search Results goes to Taxon Page

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3459]
**Describe the bug**
The link to a citation as displayed in Search Results Citations column displays the publication name, but the link goes to the main taxonomy page, regardless of the citation.

**To Reproduce**
1. Go to Search
2. Search on a record with a citation (e.g. MSB:Mamm:101210)
3. Click the citation link in Search Results. You must have Citations selected as an option for display.

**Expected behavior**
The citation link should go to the publication in Arctos.

**Screenshots**
![image](https://user-images.githubusercontent.com/14808196/108911967-34e02f00-75e5-11eb-8fd9-6db5eaa1c277.png)

 - Browser  chrome

**Priority**
High

**Comment by dustymc** [comment]
Bah, postgres...

Function rebuild, we only have about 250K cited records, I'll just set them to refresh. Might take a couple days for everything to catch up.
