### ISSUE TITLE
Component Loaders: v1.1

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3463]
https://github.com/ArctosDB/arctos/issues/2974 is huge, pulling next-version requests here.

Assigning high priority - please adjust as necessary - because the template is used in by many tools, updates should be fairly quick, there's little reason to build more pre-outdated tools.

---------------------------------------------------------------
Maybe we need to think about some way to let people jump to a specific set of data in tools like https://arctos.database.museum/tools/BulkloadOtherId.cfm

Currently there is an extra-long list of errors in there and if my username was after this person alphabetically, I'd have to scroll forever to get to my stuff.

Maybe just a table at the top that lists the usernames and lets you jump to a specific user's stuff?

----------------------------------------------------------------

See ArctosDB/data-migration#450 (comment) - verbose errors 400 lucee, need to POST or truncate errors or something.

---------------------------------------------------------------

 csv download should include this to strip unnecessary columns

```
<cfset flds=mine.columnlist>
<cfif listfindnocase(flds,'key')>
<cfset flds=listdeleteat(flds,listfindnocase(flds,'key'))>	
</cfif>
<cfif listfindnocase(flds,'last_ts')>
<cfset flds=listdeleteat(flds,listfindnocase(flds,'last_ts'))>	
</cfif>
....
<cfset csv = util.QueryToCSV2(Query=mine,Fields=flds)>

```

-------------------------------------------------------------------

Do something less confusing with the buttons. "change" suggests DO STUFF, the blue buttons just save clicking and typing, only the update button changes data. Suggestions greatly appreciated.

**Comment by campmlc** [comment]
I agree with posting just the username with a link to errors.

**Comment by dustymc** [comment]
Please review/break http://test.arctos.database.museum/tools/_BulkloadComponentTemplate.cfm

Suggestions, changes, feature requests, or anything else that'll make component loaders better are appreciated.

I'll interpret silence as enthusiastic support, and begin using this template for component loaders if there's no feedback.


See https://github.com/ArctosDB/arctos/issues/2974 for details, here's the short version:

* all component loaders get built from this template
* feel very free to do whatever you want to any data you find in there, load more data, whatever
* the template form is fully functional, but there's no loader - you'll never get back errors and such.

**Comment by Jegelewicz** [comment]
Is this emoji for "wizard"?
![image](https://user-images.githubusercontent.com/5725767/109660789-7feacc80-7b26-11eb-880c-484a1cd48d56.png)

**Comment by Jegelewicz** [comment]
Just a suggestions, but for readability could we lose the colons?
![image](https://user-images.githubusercontent.com/5725767/109661090-d821ce80-7b26-11eb-9edd-6b9f2a4e43ca.png)

Instead just say
Review all records for user
Get CSV of all records for user
Delete all records for user

**Comment by Jegelewicz** [comment]
Possible to allow clicking and dragging to select a bunch of records in stead of individually clicking each one?

**Comment by Jegelewicz** [comment]
Downloaded CSV, changed stuff, loaded. It all seemed to work.

**Comment by dustymc** [comment]
>emoji

Just making sure it was really handling UTF....

> lose the colons

derp/yes/thx/done

>clarification

That's where it came from, then I rebuilt the table and the buttons are farther apart, maybe it can be shortened again?

>select a bunch of records

<img width="613" alt="Screen Shot 2021-03-02 at 8 20 09 AM" src="https://user-images.githubusercontent.com/5720791/109679129-27203180-7b30-11eb-8888-4a6c78d44e60.png">

**Comment by Jegelewicz** [comment]
> Shift-click

DOH! I KNEW there was a way, but am a failure at reading....
