### ISSUE TITLE
Selecting old years in date dropdowns

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#3464]
Anywhere you find the little pop-up calendars to select a date (e.g., main search page, find accession, data entry page), the year dropdown only goes back 10 years (forward 10 also, so 20 yr span). You can then select that oldest year, and then click on the dropdown and go back another 10 years (and repeat). I think you used to be able to scroll way back in time using this dropdown (into the 1800's?). I know we can just type in the date, but some people prefer to mouse through search forms as much as possible (_typing is so hard_). Was this an intentional change?

**Comment by dustymc** [comment]
Docs say that can be customized, it seems likely that there's some number of years which will start affecting performance (eg by eating your browser) but I have no idea what that might be. 

Suggest a number and we can see what happens....

**Comment by acdoll** [comment]
Can we try 200 in test and see what it does? That should cover most everything in all collections? If that seems like too much, 50 years would probably catch the majority of relevant transactions and many of the search requests.

**Comment by dustymc** [comment]
Hard-reload

**Comment by acdoll** [comment]
Seems to work just fine. Thanks.
One thing, and this is probably a browser issue, but when I go into a date field where I have entered dates before, the list of previous entries covers the pop-up calendar. 
![image](https://user-images.githubusercontent.com/12507297/109214175-bd3e0b80-776e-11eb-814a-c5376c878c55.png)
When I first saw this, there were only two options so I could see that the calendar was beneath it, but for this one it is totally hidden. I can clear my browser cache and this problem goes away temporarily, but is there anything we can do about this? And by 'we' I, of course, mean 'you'

**Comment by dustymc** [comment]
Yea I think that's a browser thing - is that Chrome? Because Chrome likes to do stuff like that....

There's a disable autosuggest attribute but I think it would be fairly painful to apply without disabling the useful (to me anyway!) suggestions.

**Comment by acdoll** [comment]
Yes, Chrome. I thought that was it - not worth disabling the autosuggest. My only other thought was if you can tell it to appear above the field instead of below (but that may be a browser thing too?). Otherwise, forget I mentioned it. Thanks
