### ISSUE TITLE
immediate clone fails

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#3465]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

Try to perform an immediate clone of a record and get this erro

ERROR: ERROR: column "collection_cde" of relation "cataloged_item" does not exist
 Where: PL/pgSQL function clone_cataloged_item(text) line 62 at SQL statement - Parameter types passed (2): CF_SQL_VARCHAR, CF_SQL_VARCHAR

**To Reproduce**

**Expected behavior**

**Screenshots**

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.
medium

**Comment by dustymc** [comment]
thx/fixed
