### ISSUE TITLE
Feature Request - update publication/project search

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3468]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
Transaction unification is a big hit - can we apply some of that to [publication /project search](https://arctos.database.museum/SpecimenUsage.cfm)?

**Describe what you're trying to accomplish** 
Standardize search look and feel

**Describe the solution you'd like**
How might we accomplish your goals?

**Describe alternatives you've considered**

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by dustymc** [comment]
If we're rebuilding - which I think is a good idea - what should change? (The new transaction form is much easier to change than the old, this should follow the same pattern - I don't think this has to be perfect to proceed.)

* https://github.com/ArctosDB/arctos/issues/3466 - needs to include downloads for publications and projects
* https://github.com/ArctosDB/arctos/issues/3466 - needs ability to find publications used in sensu IDs for a specimen recordset

**Comment by Jegelewicz** [comment]
There has been a request at some point to be able to search projects by the agent who created them. That's all that is coming to mind immediately.

**Comment by dustymc** [comment]
>search projects by the agent who created them

That seems vaguely familiar.... 

https://github.com/ArctosDB/arctos/issues/2570

**Comment by campmlc** [comment]
Yes, please!! "Created by Agent" is urgently needed. Also, we had discussed
having an agent type for the institution involved in managing/coordinating
the project. Right now, the only way to know what institutions are involved
is to look at the specimen guids or know the institutions of the person
agents involved.

**Comment by dustymc** [comment]
Add to search: 

contributes stuff in {pick an institution}
uses stuff from {pick an institution}

----------

better award number search handling (but need to resolve https://github.com/ArctosDB/arctos/issues/3398 first)

transaction shipment mapping (maybe need a discussion regarding how public those data are frist??)

user-selectable numberOfMedia value to pass on to the widget

Short/long toggle on potentially-verbose text

Short summary - new field or (my preference) dynamically build from data?

**Comment by dustymc** [comment]
See https://github.com/ArctosDB/arctos/issues/2631 for "better award number search handling"

**Comment by campmlc** [comment]
I vote high priority

**Comment by dustymc** [comment]
"Blocked" might be a bit strong (I'll use it anyway, we can discuss if necessary), but failing to address https://github.com/ArctosDB/arctos/issues/3398 first is likely to result in a very short lifespan of anything we do here.

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/2615 - should projects and publications be un-merged?

**Comment by campmlc** [comment]
Would this make it easier to auto-associate publications with projects from
the catalog record, and to search on publications related to projects?

**Comment by Jegelewicz** [comment]
I think so. I get that they CAN have a relationship, but they don't always, so.....

**Comment by dustymc** [comment]
I think that combo-form was designed when we had like 5 projects and maybe a couple dozen publications, it was nice to find SOMETHING. We have lots of both and the processors to mix stuff up now, I'm leaning towards separation as well.

**Comment by campmlc** [comment]
I move we elevate priority and move forward with whatever will make this feasible, including separating pubs from projects. Is this a long term goal - do we need some shorter term bandaids to make it possible to search on pub/project ID? #3683

**Comment by dustymc** [comment]
>separating pubs from projects

Elaborate (maybe in https://github.com/ArctosDB/arctos/issues/2615) please.


>long term goal

I don't think this is a particularly significant change, but it's probably worth resuscitating https://github.com/ArctosDB/arctos/issues/3585 and making sure we have the structure mostly stable before getting too far ahead of ourselves, and maybe that will turn out to be longer-term.

>bandaids

That one's not a particularly difficult bandaid to apply, but that sort of thing often leads to more requests and cumulatively that tends to add up to more work for less functionality. 

I'm certainly in favor of moving forward with this.

**Comment by Jegelewicz** [comment]
Is this still blocked? If so, by what? If not, can we get this ball rolling again?

**Comment by dustymc** [comment]
>Is this still blocked? If so, by what?

https://github.com/ArctosDB/arctos/issues/3468#issuecomment-828610258

>can we get this ball rolling again?

That's be fabulous, but there's a big decision to be made and we haven't been very decisive lately. Even the [thing that seems to have lead here](https://github.com/ArctosDB/arctos/issues/6303) is stuck in a super-weird state!

**Comment by Jegelewicz** [comment]
> failing to address https://github.com/ArctosDB/arctos/issues/3398 first is likely to result in a very short lifespan of anything we do here.

Well, #3398 is closed - so what over there is causing the issue?

And I really do not see how https://github.com/ArctosDB/arctos/issues/6303 is involved - please explain!

**Comment by mkoo** [comment]
This is issue is stale (and took some meanderings). I am closing in favor of more specific requests. File more if needed but an entire UI makeover will require a new dev (and it's on the radar!)
