### ISSUE TITLE
Need a new formation 

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/arctos#3469]
I need a new formation:  Red mountain formation

https://mrdata.usgs.gov/geology/state/sgmc-unit.php?unit=ALSrm%3B3

I am entering some needed Geology data records... Thanks!
**Priority**
Please choose a priority-label to the right.

**Comment by Jegelewicz** [comment]
Add Red Mountain Formation to https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlithostratigraphic_formation
