### ISSUE TITLE
Unable to claim Extras for loaded records

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/arctos#3471]
** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **
I keep getting an error message:
![image](https://user-images.githubusercontent.com/43214224/109308672-f1b1d600-7807-11eb-9390-8b124dd03992.png)

**Comment by dustymc** [comment]
Thanks - this needs rolled into the component loader system.

I think this form and the notification can simply be deleted.

* manage collection users are getting emails through the component loader process
* it's not necessary to wait for the catalog record to be loaded to take action - 'autoload' can be set at any time
* there is no 'claim' process

Am I missing some use case which would require keeping this?

<img width="275" alt="Screen Shot 2021-02-26 at 8 28 51 AM" src="https://user-images.githubusercontent.com/5720791/109327149-dd240c80-780c-11eb-9a51-348af91ec34a.png">
