### ISSUE TITLE
Code Table Request - New Part "Bud"

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#3474]
**Goal**
Add a new part, bud, to the parts table

**Context**
None of the other plant parts in the code table cover this structure (although I'm not super familiar with plants and would welcome a correction if I am wrong)

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=CTSPECIMEN_PART_NAME

**Value**
bud

**Definition**
An undeveloped or embryonic shoot and normally occurs in the axil of a leaf or at the tip of a stem. [https://en.wikipedia.org/wiki/Bud](https://en.wikipedia.org/wiki/Bud)

**Collection type**
ES, Herb

**Attribute data type**

**Part tissue flag**
For new parts, is the part a tissue? Potentially yes, but not for our fossil stuff?

**Priority**
Please choose a priority-label to the right.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Since no one seems to have any discussion on this, can it get added?

**Comment by campmlc** [comment]
I support this. If we end up with animal buds, perhaps they could be
distinguished as "limb buds".

**Comment by dustymc** [comment]
Can I act as the second CT Admin and DBA at the same time (https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html)? Let's pretend I can/should....

Done.

**Comment by campmlc** [comment]
Yes  - you have my vote! And thanks!
