### ISSUE TITLE
[CONTACT] Account Locked-Again

### ISSUE THREAD

**Issue by jwurtz01** [ArctosDB/arctos#3478]
Hey Arctos Team, 

I am Jason Wurtz (username:jwurtz01). My account keeps getting locked. Can you unlock it for me again?

Best,

Jason 

** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **

** Outages should be reported to the contacts listed at https://arctosdb.org/arctos-down/ **

** Arctos Documentation is http://handbook.arctosdb.org/ **

** Learn more about Arctos at https://arctosdb.org/ **

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **

**Comment by campmlc** [comment]
Done
