### ISSUE TITLE
Encumbered Localities with Public Events Not Mapping in Berkeley Mapper?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3479]
1) To hide sensitive locality data, we have the tools in Arctos to create private localities using the locality access attribute, while creating a second, public specimen event and locality with fuzzy data. However, it would be useful if the public event were mappable, e.g. to county level.  Berkeley Mapper right now  is disabled for either event for public access if any event has the private access locality attribute. Can this be fixed without causing sensitive locality data breaches in Berkeley Mapper?
See for example https://arctos.database.museum/guid/MSB:Bird:49622

2) On a similar subject, what tools exist if any to georeference a locality to county level or above using only WKT boundaries, rather than displaying randomly selected and misleading point coordinates in Berkeley Mapper? For WKTs for higher geography, localities that use them (e.g. "New Mexico, no specific locality recorded") still map to a single point in Berkeley Mapper, rather showing the WKT boundary as uncertainty. This is misleading, as in the above example, New Mexico records get mapped to a point outside of a species range, merely because that point happened to be chosen as the center default for the state "New Mexico".  See https://arctos.database.museum/guid/MSB:Mamm:21317

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> Berkeley Mapper right now is disabled for either event for public access if any event has the private access locality attribute

Our public localities seem to be mapping? [https://arctos.database.museum/guid/NMMNH:Paleo:27469](https://arctos.database.museum/guid/NMMNH:Paleo:27469)

> using only WKT boundaries, rather than displaying randomly selected and misleading point coordinates

This would be nice.

**Comment by campmlc** [comment]
Some of the records in the accession for the above record have a mask coordinates encumbrance. That may be why they aren't mapping properly.  https://arctos.database.museum/guid/MSB:Bird:49641 has encumbrances removed - it should show just the fuzzy county locality mapped to county center point?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Yes, the map on that one is showing up with fuzzy county coordinates.

**Comment by campmlc** [comment]
Good to know mask coordinates works!
I still would like to remove the point marker on the fuzzy county
coordinates and have BM only show the WKT boundaries. Possible?

**Comment by Jegelewicz** [comment]
> have BM only show the WKT boundaries. Possible?

That seems like a questions for Berkeley Mapper? I don't know that we can control the way it maps things. One thing to try would be to associate the county wkt with the generic locality and see how that works in BM.

**Comment by Jegelewicz** [comment]
I added the wkt for county to this record's generic locality:https://arctos.database.museum/guid/NMMNH:Paleo:15001 and Berekely mapper doesn't know how to handle it.
![image](https://user-images.githubusercontent.com/5725767/109665955-f4743a00-7b2b-11eb-8bc2-b57949fb36f5.png)

**Comment by dustymc** [comment]
Arctos has never required point-radius data.

BerkeleyMapper can display more than centroids.

We could pass WKT on to anyone who can use it, but I don't think there are any takers at the moment. That would involve terabytes of data from certain (most, perhaps) viewpoints so it might require more infrastructure from us, and then would probably just plug up the tubes, but it's technically trivial to assemble the data.
