### ISSUE TITLE
MSB Bird Loan invoice header and item invoice doesn't print properly, is not on drop down menu for printing

### ISSUE THREAD

**Issue by catherpes** [ArctosDB/arctos#3480]
in edit loan, https://arctos.database.museum/Loan.cfm?transaction_id=21126881&Action=editLoan
my only option to print documents are not bird documents. Please remove the mammal and earth sciences docs and replace with bird invoice header and item invoice by catnum. 

When I access the MSB Bird documents via the print any report here: http://reports.arctos.database.museum/reporter/report_printer.cfm?auth_key=7254A3C1-6C1A-4EC2-91E81CAD556D97EB&transaction_id=21126881
the loan invoice does not print instructions, only nature of material.

when I try to print the loan list by catnum, i get the error:
select flat.collection, flat.collection_cde, flat.cat_num, flat.scientific_name, decode(trim(flat.sex), 'male','male', 'female','female', '?') sex, concatsingleotherid(flat.collection_object_id,'NK') NK, specimen_part.part_name as part, coll_object.condition part_condition, CASE WHEN length(coll_object.condition) > 15 or flat.ENCUMBRANCES is not null THEN 'X' end AS has_appendix, higher_geog || '. ' || spec_locality || '' || case when orig_lat_long_units is not null then '. ' || verbatim_coordinates end as locality, item_instructions, loan_item_remarks, coll_object.coll_obj_disposition, flat.ENCUMBRANCES, loan.loan_number, trans.trans_date, flat.datum, flat.verbatim_coordinates, sampled_from_obj_id from loan_item, loan, trans, specimen_part, coll_object, flat WHERE loan.transaction_id = loan_item.transaction_id and loan.transaction_id = trans.transaction_id and loan_item.collection_object_id = specimen_part.collection_object_id AND specimen_part.collection_object_id = coll_object.collection_object_id and specimen_part.derived_from_cat_item = flat.collection_object_id and loan_item.transaction_id = 21126881 ORDER BY cat_num

I like the format of the MSB mammal item invoice but it needs to print in order by catalog number and change the header to Birds rather than mammals. 

Windows 10 
second most recent version of Firefox. 

Completion of a loan is contingent on this getting fixed so this is high priority

**Comment by campmlc** [comment]
All of the reports have recently been moved to
http://reports.arctos.database.museum/reporter/report_printer.cfm?auth_key=7254A3C1-6C1A-4EC2-91E81CAD556D97EB&transaction_id=21126881
- the older versions in the dropdown had to be deprecated due to software
issues. Some of the reports in the new list need to be updated in the
Report Builder since the PostGres swap. The two current ones that work for
MSB:Bird are the MSB_Bird_Loan_Header (MSB_Bird_Loan_Header_cfr) and
MSB_Bird_Loan_List (MSB_Bird_Loan_List_cfr).
I can help edit any of the reports to include missing or updated info, but
it may take a few days. Will the above ones work for now?

**Comment by campmlc** [comment]
MSB Bird reports updated and functional as requested.  But @catherpes gets the following error trying to access the updated reports:

Element DBUSER is undefined in SESSION.
--
 
 
The error occurred in /usr/local/httpd/htdocs/internal/reporter/report_printer.cfm: line 63
61 :  62 :     <cfdirectory action="list" directory="#Application.webDirectory#/reporter/templates" name="dirDump" sort="name ASC"> 63 : 	<cfquery name="e" datasource="user_login" username="#session.dbuser#" password="#decrypt(session.epw,session.sessionKey)#"> 64 : 	    select * from cf_report_sql where report_template in ( #QuotedValueList(dirDump.name)# ) order by report_name 65 : 	</cfquery>Below the line: Resources:             Check the ColdFusion documentation to verify that you are using the correct syntax.Search the Knowledge Base to find a solution to your problem.                                   Browser  Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0Remote Address  129.114.52.18Referrer  Date/Time  02-Mar-21 11:28 AM                                                              Stack Trace                                                	at cfreport_printer2ecfm193737824.runPage(/usr/local/httpd/htdocs/internal/reporter/report_printer.cfm:63)                                                    coldfusion.runtime.UndefinedElementException: Element DBUSER is undefined in SESSION. 	at coldfusion.runtime.CfJspPage.resolveCanonicalName(CfJspPage.java:1752) 	at coldfusion.runtime.CfJspPage._resolve(CfJspPage.java:1705) 	at coldfusion.runtime.CfJspPage._resolveAndAutoscalarize(CfJspPage.java:1854) 	at coldfusion.runtime.CfJspPage._resolveAndAutoscalarize(CfJspPage.java:1833) 	at cfreport_printer2ecfm193737824.runPage(/usr/local/httpd/htdocs/internal/reporter/report_printer.cfm:63) 	at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:244) 	at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:444) 	at coldfusion.filter.CfincludeFilter.invoke(CfincludeFilter.java:65) 	at coldfusion.filter.IpFilter.invoke(IpFilter.java:64) 	at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:422) 	at coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:48) 	at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40) 	at coldfusion.filter.PathFilter.invoke(PathFilter.java:112) 	at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:94) 	at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28) 	at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38) 	at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:46) 	at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38) 	at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22) 	at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62) 	at coldfusion.CfmServlet.service(CfmServlet.java:219) 	at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) 	at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42) 	at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:224) 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169) 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168) 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98) 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:928) 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:414) 	at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:204) 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:539) 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:298) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603) 	at java.lang.Thread.run(Thread.java:722) | Resources:             Check the ColdFusion documentation to verify that you are using the correct syntax.Search the Knowledge Base to find a solution to your problem. | Browser  Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0Remote Address  129.114.52.18Referrer  Date/Time  02-Mar-21 11:28 AM | Browser | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0 | Remote Address | 129.114.52.18 | Referrer |   | Date/Time | 02-Mar-21 11:28 AM | Stack Trace | at cfreport_printer2ecfm193737824.runPage(/usr/local/httpd/htdocs/internal/reporter/report_printer.cfm:63)                                                    coldfusion.runtime.UndefinedElementException: Element DBUSER is undefined in SESSION. 	at coldfusion.runtime.CfJspPage.resolveCanonicalName(CfJspPage.java:1752) 	at coldfusion.runtime.CfJspPage._resolve(CfJspPage.java:1705) 	at coldfusion.runtime.CfJspPage._resolveAndAutoscalarize(CfJspPage.java:1854) 	at coldfusion.runtime.CfJspPage._resolveAndAutoscalarize(CfJspPage.java:1833) 	at cfreport_printer2ecfm193737824.runPage(/usr/local/httpd/htdocs/internal/reporter/report_printer.cfm:63) 	at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:244) 	at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:444) 	at coldfusion.filter.CfincludeFilter.invoke(CfincludeFilter.java:65) 	at coldfusion.filter.IpFilter.invoke(IpFilter.java:64) 	at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:422) 	at coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:48) 	at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40) 	at coldfusion.filter.PathFilter.invoke(PathFilter.java:112) 	at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:94) 	at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28) 	at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38) 	at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:46) 	at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38) 	at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22) 	at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62) 	at coldfusion.CfmServlet.service(CfmServlet.java:219) 	at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) 	at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42) 	at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:224) 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169) 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168) 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98) 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:928) 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:414) 	at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:204) 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:539) 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:298) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603) 	at java.lang.Thread.run(Thread.java:722)
Resources:             Check the ColdFusion documentation to verify that you are using the correct syntax.Search the Knowledge Base to find a solution to your problem.
Browser  Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0Remote Address  129.114.52.18Referrer  Date/Time  02-Mar-21 11:28 AM | Browser | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0 | Remote Address | 129.114.52.18 | Referrer |   | Date/Time | 02-Mar-21 11:28 AM
Browser | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0
Remote Address | 129.114.52.18
Referrer |  
Date/Time | 02-Mar-21 11:28 AM
Stack Trace
at cfreport_printer2ecfm193737824.runPage(/usr/local/httpd/htdocs/internal/reporter/report_printer.cfm:63)                                                    coldfusion.runtime.UndefinedElementException: Element DBUSER is undefined in SESSION. 	at coldfusion.runtime.CfJspPage.resolveCanonicalName(CfJspPage.java:1752) 	at coldfusion.runtime.CfJspPage._resolve(CfJspPage.java:1705) 	at coldfusion.runtime.CfJspPage._resolveAndAutoscalarize(CfJspPage.java:1854) 	at coldfusion.runtime.CfJspPage._resolveAndAutoscalarize(CfJspPage.java:1833) 	at cfreport_printer2ecfm193737824.runPage(/usr/local/httpd/htdocs/internal/reporter/report_printer.cfm:63) 	at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:244) 	at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:444) 	at coldfusion.filter.CfincludeFilter.invoke(CfincludeFilter.java:65) 	at coldfusion.filter.IpFilter.invoke(IpFilter.java:64) 	at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:422) 	at coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:48) 	at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40) 	at coldfusion.filter.PathFilter.invoke(PathFilter.java:112) 	at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:94) 	at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28) 	at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38) 	at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:46) 	at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38) 	at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22) 	at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62) 	at coldfusion.CfmServlet.service(CfmServlet.java:219) 	at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) 	at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42) 	at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:224) 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169) 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168) 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98) 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:928) 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:414) 	at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:204) 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:539) 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:298) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603) 	at java.lang.Thread.run(Thread.java:722)

**Comment by dustymc** [comment]
How'd you get there? That's usually from not going through the steps in Arctos.

**Comment by catherpes** [comment]
From Edit loan page, Click on Print -> Any Report -> get to this page:
https://arctos.database.museum/Reports/report_printer.cfm?transaction_id=21126881,
click on link to continue ->receive error message.

**Comment by dustymc** [comment]
Thanks. That's the expected path and it works for me, so it must be something in your local environment - wild guess, your browser doing something weird with the different domains. Can you try it on another machine or with another browser, clear your cache and cookies, etc.?

I clicked your link then clicked that link then....

<img width="679" alt="Screen Shot 2021-03-02 at 10 34 34 AM" src="https://user-images.githubusercontent.com/5720791/109697488-204eea00-7b43-11eb-8e94-4424613db874.png">

...clicked print report and got....

<img width="569" alt="Screen Shot 2021-03-02 at 10 36 27 AM" src="https://user-images.githubusercontent.com/5720791/109697520-2d6bd900-7b43-11eb-99c4-75d3ef2d0e55.png">

**Comment by campmlc** [comment]
It works for me off campus. But others have had similar issues with this
error popping up out of nowhere, even with logging out and logging back in
again. Campus IT? I'll try when I get in.

**Comment by catherpes** [comment]
Okay. Works now. I cleared cookies. logging out and back in wasn't enough.
Thanks.
Andy

**Comment by campmlc** [comment]
Just got same error - first time printing reports in this log in session:

The following information is meant for the website developer for debugging purposes.
--

Error Occurred While Processing Request
Element DBUSER is undefined in SESSION. | Element DBUSER is undefined in SESSION.
Element DBUSER is undefined in SESSION.

**Comment by campmlc** [comment]
Trying to get to reports from loan form.

**Comment by campmlc** [comment]
https://arctos.database.museum/Loan.cfm?Action=editLoan&transaction_id=21126978
