### ISSUE TITLE
Media Gallery not working in ALMNH:Geo

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/arctos#3481]
Link "media gallery" returns this:
![image](https://user-images.githubusercontent.com/43214224/109660929-099e9800-7b2f-11eb-81ab-2955fbd78b3b.png)
![image](https://user-images.githubusercontent.com/43214224/109661260-69953e80-7b2f-11eb-9f44-032ac915ce7b.png)

**Comment by Jegelewicz** [comment]
@mbprondzinski from the record:
![image](https://user-images.githubusercontent.com/5725767/109663132-01435e80-7b29-11eb-98a3-8ec2540df747.png)

When I click that button, I get this:
![image](https://user-images.githubusercontent.com/5725767/109663185-10c2a780-7b29-11eb-9c09-fb13a0a2a735.png)

https://arctos.database.museum/MediaSearch.cfm?action=search&specimen_id=27912449

Is that what you did or were you somewhere else?

**Comment by Jegelewicz** [comment]
It may have something to do with being logged in. I was not and I cannot repeat your steps if you were logged in because I don't have access to that collection.

**Comment by mbprondzinski** [comment]
That's weird because it works in the Paleo collection when I'm logged in.  I will try it without logging in.  Nope, it still doesn't work in the Geology collection when I'm logged out.

**Comment by mbprondzinski** [comment]
Try calling up ALMNH:Geo:18

**Comment by Jegelewicz** [comment]
That is weird! I don't have an immediate answer for this...

**Comment by Jegelewicz** [comment]
The offending address is https://arctos.database.museum/MediaSearch.cfm?action=search&specimen_id=29660850

I see these media were added yesterday - maybe there is some sort of lag?

**Comment by mbprondzinski** [comment]
Maybe...

**Comment by mbprondzinski** [comment]
Take a look at this one: ALMNH:Paleo:14511

I added one new image to that record (now there are three), but when you click on the "media gallery" button, it returns only the two that were there originally.  Maybe it is a lag?  I will check again later...  Thanks, Teresa.

**Comment by Jegelewicz** [comment]
If you don't see it by tomorrow, let me know!

**Comment by dustymc** [comment]
PLEASE include the information requested in the issue templates - in this case, links to the Media would have been exceptionally useful.

documents cataloged_item isn't being caught by specimen_id.

**Comment by mbprondzinski** [comment]
Sorry, I didn't realize that!  I'm not that proficient with GitHub, but at least I use it 🥇

**Comment by Jegelewicz** [comment]
If you don't see it by tomorrow, let me know!

Originally posted by @Jegelewicz in #3481 (comment)

They still aren't showing. I guess it is something Dusty has tasked himself?!
