### ISSUE TITLE
Reporter error

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#3483]
I am trying to print some labels with an older template (DMNS_mamm_vial) and get the following error:

Error Executing Database Query.
--
ERROR: syntax error at or near ","
 
The error occurred in /usr/local/httpd/htdocs/internal/reporter/report_printer.cfm: line 135

133 : 			 
134 : 			<cfquery name="d" datasource="user_login" username="#session.dbuser#" password="#decrypt(session.epw,session.sessionKey)#"> 
135 : 				#preservesinglequotes(sql)# 
136 : 			</cfquery> 
137 : 		</cfcatch>
______________________________
 
I updated the handler to match other working labels. Am I missing something there or is there a problem with my CF template?

**Comment by dustymc** [comment]
<img width="120" alt="Screen Shot 2021-03-02 at 12 34 33 PM" src="https://user-images.githubusercontent.com/5720791/109711413-b68b0c00-7b53-11eb-9c1b-a013ce5ef838.png">

<img width="647" alt="Screen Shot 2021-03-02 at 12 34 50 PM" src="https://user-images.githubusercontent.com/5720791/109711435-bb4fc000-7b53-11eb-9411-c1b794147c2c.png">

**Comment by acdoll** [comment]
Arg. Thanks!
