### ISSUE TITLE
Loan bulkload errors in new loader

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3485]
I'm trying to bulkoad a loan for the first time since the component loader system has been implemented, using barcodes for the loan items. 
One minor bug:  the documentation says that the field "IGNORE_SUBSAMPLE_IN_FINDING" is not required when barcodes are used, but I got an error saying it was required. Error disappeared when I put a value in the field.
However, something more serious is going on - I marked all for autoload, and got "catalog record not found" for all records as the error -see attached file. 
 But if I copy the list of barcodes and search on them in Arctos, all are associated with a catalog item.  
I had hoped to ship this today - but this will cost another delay.
Barcode list for loan: A9K6N,A5NDE,A5NLS,A5NL9,A5NL5,A6EW9,A2OX1,A2JEV,A2JFH,A2PY8,A9K6O,A9K6P,A9K6Q,A9K6R,A9K6S,A9K6T,A9K6U,A9K6V,A9K6W,A9K6X,A9K6Y,A9K6Z,A9K70,A9K71,A4L5U,A9K72,A9K73,A5NLI,A5NLG,A5ND8,A5ND0,A9K74,A9K75,A9K76,A4PMY,A9K77,A5RVH

Catalog Items for loan: https://arctos.database.museum/saved/2021.007.Mamm%20Light

[bulkloadLoanItemData (2)_cat_item_not_found.zip](https://github.com/ArctosDB/arctos/files/6073040/bulkloadLoanItemData.2._cat_item_not_found.zip)

**Comment by dustymc** [comment]
> If part_barcode is given, it serves as the single way to specify the part. If part_barcode is not given, part_name must be. This will only work if there is a single part directly contained by the container bearing the supplied barcode. 

Barcode can be used to identify the part after the cataloged item is found.

I don't see any reason it couldn't also be used to identify the catalog record, so let's call this a feature request. in the meantime, ...

<img width="386" alt="Screen Shot 2021-03-02 at 5 49 40 PM" src="https://user-images.githubusercontent.com/5720791/109740200-c6204a00-7b7f-11eb-893b-6359424693f9.png">

... should get what's missing.

**Comment by campmlc** [comment]
The former loan bulkloader tool used barcode in this way without a problem.
I don't need the guid-- I have a list of those.  I need the barcode to
identify the specific part for subsampling for the loan, the way the
previous loan form worked. I have records with multiple parts of same name,
but they are located in different freezers. Hence barcode is the only way
to unambiguously select which part in exactly which position was subsampled
for the loan.

**Comment by campmlc** [comment]
I am hoping to finalize this loan today, and hoping not to have to add 55 parts one at a time? Any chance of quick resolution, or should I start manually adding parts?

**Comment by campmlc** [comment]
Heads up I have an upcoming loan of 500 parts that will absolutely need the tool to add by barcode.

**Comment by dustymc** [comment]
I'm not sure what isn't clear. There's no need to add 55 parts one at a time.

Next release will have better barcode handling and hopefully-clarified documentation.

**Comment by campmlc** [comment]
Please load my csv then if it is working?

**Comment by campmlc** [comment]
@DerekSikes - are you still able to bulkload loan items using barcodes? The form no longer works the way it used to, and if there is a work around besides adding one at a time manually I am not familiar with it. I can't bulkload without using barcodes because there are multiple parts of the same name.
@Jegelewicz  Can we get the help/documentation link for the component loader loan tool added to the https://arctos.database.museum/tools/BulkloadLoanItem.cfm ?
Thanks

**Comment by campmlc** [comment]
I thought I figured it out - the guid prefix was missing from my file.  I added it - and still can't load. The previous loan bulkload tool allowed us to upload a file with guid prefix and barcode only.  Does this new tool now require the entire guid as well? If so, yes, I would like to request that the new form provide the same functionality as the old form, and allow barcode + guid prefix only.
I will now go and spend more time looking up the actual catalog numbers . . .

**Comment by campmlc** [comment]
Example loan bulkload file from pre-component loader system attached. I highly recommend we don't change the basics of these tools to avoid having every Arctos operator have to go through what I have gone through since yesterday. No need to force operators to re-learn critical tools after every upgrade for no reason. We are better than Microsoft . . . 
[Loan bulkload.zip](https://github.com/ArctosDB/arctos/files/6079925/Loan.bulkload.zip)

**Comment by campmlc** [comment]
Summary - please eliminate the requirement for guid or guid+other identifier if a barcode is used. Barcode + guid prefix is sufficient, and consistent with previous usage.

**Comment by Jegelewicz** [comment]
> Can we get the help/documentation link for the component loader loan tool added to the https://arctos.database.museum/tools/BulkloadLoanItem.cfm ?

I think what we really need is an update to [How To Add Items to a Loan](https://handbook.arctosdb.org/how_to/How-to-Add-Loan-Items.html) which should include a link to the component loader documentation. I added a link to this How To to [Bulkload Loan Item Tool](https://arctos.database.museum/tools/BulkloadLoanItem.cfm)
