### ISSUE TITLE
Reporter issue

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#3487]
It's not an extra comma this time. 
After selecting "Print any report" and clicking on the link to the reporter, I get:
![image](https://user-images.githubusercontent.com/12507297/109867253-83b04900-7c23-11eb-93b9-56ded8d8b073.png)

**Comment by dustymc** [comment]
That's usually from a whole bunch of tabs open, using your back button somewhere, etc. It needs a very linear approach to get the authentication right. SpecimenResults/any report works for me, I don't think anything is broken, it's just twitchy.

**Comment by acdoll** [comment]
Weird. I wasn't doing anything unusual. I closed/reopened the browser without logging out of Arctos and it did the same thing when I tried again. I logged off, closed and reopened, logged on and then it worked. 
BTW the first time I tried it, before I got the error posted above, it just displayed this:
![image](https://user-images.githubusercontent.com/12507297/109873091-87939980-7c2a-11eb-936c-36c036a361f7.png)

**Comment by dustymc** [comment]
"no UA" is "you don't have any credentials"

The error is "you have credentials but they're not any good"

The "good" news is, we are going to be forced into doing something at some point - https://github.com/ArctosDB/internal/issues/37. Might be good to get in front of that before what we have just completely stops working.....

**Comment by acdoll** [comment]
Thanks. I'll let you know if I find anything else weird like that.
