### ISSUE TITLE
catalog record summary not giving expected results by collection

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#3488]
If you search by genus and species for specific collection(s), and view the results as a Catalog Record Summary, you get results for ALL collections, not just the ones you selected.

Same results whether you enter the genus/species in separate fields or in Any Taxon ID or identification.

Note that this is when I'm logged in, and I have access to multiple institutions - not just MVZ.

**Comment by dustymc** [comment]
I can't recreate this behavior.

**Comment by ccicero** [comment]
Here is my search from the main Catalog Records interface:

Collections = MVZ:Bird, MVZ:Egg, MVZObs:Bird

![image](https://user-images.githubusercontent.com/967275/110004256-16a4be00-7ccc-11eb-96fc-e68cf5bf09fb.png)

Searched by a genus and species.

See results as Specimen Record Summary, group by scientific name and collection. Get all records, not just those three MVZ collections.

![image](https://user-images.githubusercontent.com/967275/110004473-54094b80-7ccc-11eb-81f9-47c5fd7bb740.png)

**Comment by dustymc** [comment]
Can you screenshot all of your search parameters? What you describe just errors for me - I'll open another issue for that.

**Comment by ccicero** [comment]
Yep, sometimes I get "sad" on the first try - then I go back and hit "Use Last Values", and make sure that the three collections are still selected as well as the other values before trying again. Not sure if that is triggering something? 

Besides the two screenshots above, the only other search parameters were:
genus:  "Anas"
species: "platy"

I also tried searching by identification, or any taxon ID, and got the same thing.

**Comment by dustymc** [comment]
>as well as the other values b

I'm guessing this just un-checks guid_prefix in groupby, which leads to the data you're seeing and not the error I'm seeing.

**Comment by ccicero** [comment]
Why blocked? So are you saying that by selecting "Use Last Values" it un-checks guid_prefix even though in the list of collections, they're still checked?

**Comment by dustymc** [comment]
>Why blocked?

#3490

>in the list of collections

In the group-by, but probably there too. My JS doesn't interact very well with that multiselect plugin.

**Comment by dustymc** [comment]
@ccicero please try this in test. I'll need to lock the DB for a couple hours to get it to production, I'll try to do that tonight if its working as expected for you.

**Comment by ccicero** [comment]
@dustymc Sorry, I didn't see your request to test th is. It's still not working right. 

Search parameters:
MVZ:Bird
MVZ:Egg
MVZObs:Bird

see results as summary, group by scientific name

Genus='Regulus' and Species='satrapa'

Results:
![image](https://user-images.githubusercontent.com/967275/110369827-c7c69380-7fff-11eb-8f17-f879af1f92af.png)

Click on the two without a subspecies:

![image](https://user-images.githubusercontent.com/967275/110369909-e4fb6200-7fff-11eb-92e6-6d695de5fd75.png)

**Comment by ccicero** [comment]
oh, I forgot mention - I hit 'Use Last Values' and also searched by state = 'California'

If I search without selecting 'Use Last Values' it seems correct (all 157 records from MVZ):

![image](https://user-images.githubusercontent.com/967275/110370321-5dfab980-8000-11eb-8593-1eeb01742b9d.png)

**Comment by dustymc** [comment]
The fancy multiselect does not work predictably with my code. I don't have an immediate solution for this. We could find a better multiselect or better yet rebuild the form so there is no "last" - https://github.com/ArctosDB/arctos/issues/2745

**Comment by dustymc** [comment]
This is marked critical, I don't know what to do with it. The only "fix" I have available is to remove the use last values function. Can someone offer a solution, or re-prioritize, or ???

**Comment by Jegelewicz** [comment]
Well, doesn't it fit the "Arctos is Broken" criteria? At least if we expect "use last values" to be functional? The critical label combined with the need more information milestone SHOULD bring it to the AWG attention, but we have not been able to get through a lot of issues lately.

**Comment by dustymc** [comment]
FYI the real solution for this is to rebuild the UI, that requires an API, that requires SSL, I don't have that in test.

**Comment by Jegelewicz** [comment]
> rebuild the UI, that requires an API, that requires SSL

Projects for another grant?

**Comment by dustymc** [comment]
The UI maybe, the API should come from the current award (and I'd be doing that NOW if I could securely authenticate at test).
