### ISSUE TITLE
500 Error Using Encumbrances in Specimen Results Tools Menu

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3489]
I need to add a restrict usage encumbrance to several projects representing over 5000 specimens each. This encumbrance is merely to request citation of the NSF grants which provided funding for specimen collection - and the encumbrance will show up in the loan forms. 
However, I can't use the Encumbrance tool in Tools menu in Catalog Record Results because it times out ? 500 Internal Server Error. 
Is there some other way to add encumbrances to large numbers of records? A new bulkloader in the component loader, perhaps?

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/3491
