### ISSUE TITLE
add guid_prefix to flat

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3490]
Things that are available in specimensearch/groupby but are not in flat are very difficult to deal with. Add guid_prefix to FLAT, rebuild any relevant code to use it.

Blocking https://github.com/ArctosDB/arctos/issues/3488

I know how to do this so going next task, needs prioritized.

**Comment by dustymc** [comment]
Hey @ArctosDB/arctos-working-group-officers can we establish a policy of inheriting priority? @ccicero has https://github.com/ArctosDB/arctos/issues/3488 marked as critical (correctly, I think), I could maybe hack something together if I really had to, doing this then revisiting that would be a lot less hacky and a lot more broadly useful. Can I just treat this as critical? Can I do so as a general rule?

**Comment by campmlc** [comment]
Yes? I agree from our discussion at the issues meeting today that if
someone somewhere thinks an issue is critical, it is.

**Comment by mkoo** [comment]
Agreed.
