### ISSUE TITLE
Feature Request - Add Sponsor and Award Number from Project to Loan Item Instructions

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3491]
I need to be able to add Sponsor and Award number to Loan Item Instructions to have these cited for specimen collection
We discussed in Issues meeting 3-4-2021. 
Currently using Encumbrances for all catalog records in a Project, but this fails because encumbrances cannot currently be added in bulk to thousands of records (500 Internal Server Error) #3489

**Describe the solution you'd like**
Have Arctos automatically pull Sponsor and Award number from Projects into Loan Item Review/Item Instructions.
Also add Sponsor/Award number as a possible Add/Remove data field from Catalog Record Results.

**Describe alternatives you've considered**
Happy to consider alternatives.

**Priority**
High - having loan recipients cite sponsors who fund specimen collection is a priority of our curators.

**Comment by dustymc** [comment]
Vague idea:

Edit loan gets a new "do magic()" button. Clicking it makes the loan_item-->...-->project join, pulls back Project Sponsors (or whatever ya'll ultimately want), pre-formats some text ('include "sponsored by NSF#12345 in all publications resulting from this loan....') in some widget (probably many of them, actually - one for each involved accn-project with whatever data you're looking for), users can review or change it, clicking some OK button(s) appends to all relevant loan_item.item_instructions.

Note that requiring borrowers to include some text in papers MIGHT find a way to get back to catalog records, with enough work on our part. Requiring borrowers (and everyone else) to use https://www.crossref.org/services/funder-registry/ would do that, and much more, without any additional work on our part. https://github.com/ArctosDB/arctos/issues/1694

Might be useful to round up data license and terms in the same way, although that might be more appropriate in loan.loan_instructions.

>data field from Catalog Record Results.

New Issue I think - that should probably involve more than just accession-projects.

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/3398 needs resolved before this is addressed.
