### ISSUE TITLE
Feature Request - Higher_Geog WKT's for Localities

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#3492]
We have many specimens whose locality data only goes down to the county level (e.g. [DMNS:Mamm:21594](https://arctos.database.museum/guid/DMNS:Mamm:21594)) 
Since we have WKT's associated with the Higher_Geog for those counties, can we apply those WKT's to these localities with no Specific_Locality? I'm not (yet) suggesting that we apply them automatically, but it would be great if we could select them on the Edit Locality page. I thought it might work if I put in the WKTMediaID from the [Higher_Geog for that county](https://arctos.database.museum/Locality.cfm?action=editGeog&geog_auth_rec_id=10001986), but that doesn't seem to do anything (well, it does add a link to that WKT media file; BTW there is no documentation for that WKTMediaID field). 
I guess the minimum I'm looking for is to display a map on the specimen record showing where that county is. A possible next step would be to calculate a centroid and max error from the WKT for exporting to the aggregators since they can't handle WKT data yet.

**Comment by campmlc** [comment]
Agree - see #3479

**Comment by dustymc** [comment]
> thought it might work 

Yep, one of the many reasons WKT is in text files rather than CLOBS or something - it's easy to use them wherever they're handy.

>doesn't seem to do anything

It does, but anywhere (ish, I'm sure we don't have complete WKT handling) in Arctos you're almost certainly looking at the locality data overlaid on the geography data, so it just looks sorta purplish instead of red+blue.

<img width="329" alt="Screen Shot 2021-03-04 at 2 34 57 PM" src="https://user-images.githubusercontent.com/5720791/110039920-d3ac1000-7cf6-11eb-9f7c-4497375beb40.png">


>apply them automatically

I don't think that would fly, but an 'inherit WKT from geography' button somewhere might be close enough.

> display a map on the specimen record showing where that county is.

You should already be getting that through the geography. Note that it's the same SHAPE, but not the same ASSERTION.

>A possible next step would be to calculate a centroid and max error from the WKT for exporting to the aggregators

TACC is supposed to be figuring out PostGIS (when they're not busy trying avoiding death by pandemics and unprecedented weather and such....), I think that's probably possible once I have better tools.

**Comment by acdoll** [comment]
> 'inherit WKT from geography' button

That exactly what I had in mind.

**Comment by acdoll** [comment]
> You should already be getting that through the geography
 We see that in the locality record, but not on the specimen record

**Comment by dustymc** [comment]
>specimen record

You should if there's data eg https://arctos.database.museum/guid/DMNS:Bird:10110 looks like...

<img width="817" alt="Screen Shot 2021-03-04 at 2 49 04 PM" src="https://user-images.githubusercontent.com/5720791/110041327-cdb72e80-7cf8-11eb-95df-2e4f42150402.png">

**Comment by acdoll** [comment]
But that has coordinate data. Can we display a map showing the county boundary for specimens without coordinate data?

**Comment by dustymc** [comment]
Can - sure.

Should - I'm not so sure, that might look more like "data" than can really be justified.

I should have coordinates for 90-some percent of whatever you're thinking about, I could easily do something with that if you want. https://github.com/ArctosDB/arctos/issues/3272

**Comment by campmlc** [comment]
If we have county level data, then adding WKT mapping at the level of
higher geography should be consistent unless the counties have changed
since collection, which is always a possibility. However, collection
managers would have the option of choosing to use the higher geog WKT
mapping or not, correct?

**Comment by acdoll** [comment]
> Should - I'm not so sure

That is a fair point, maybe a 'Show Current County Boarders' button with a popup map would be less suggestive of actual data? I think something like that  would be useful without going as far as adding a set of point coordinates with the 'Click and then save for Magic Coordinates'. 
I now realize that 'Click ... Magic Coordinates' kind of does what I suggested for a next step (cue the face palm). I have noticed some inconsistency with the generated coordinates: it sometimes it selects a spot at/near what appears to be the centroid, for other counties it appears to select the county seat. This may be State dependent. This just comes directly from Google, right? Having read through 3272 more closely, I think you're on the right track there my issues will probably become moot.

**Comment by dustymc** [comment]
>popup

Yea, that doesn't make me twitchy, would just need some work. (And it'd be 'geography' or something, not 'county').

That said, the same number of clicks (one)...

<img width="397" alt="Screen Shot 2021-03-05 at 7 45 57 AM" src="https://user-images.githubusercontent.com/5720791/110138478-e2da9e80-7d86-11eb-8d3d-fb61ef624e72.png">

leads to https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10001986 which includes the spatial data.

<img width="346" alt="Screen Shot 2021-03-05 at 7 47 28 AM" src="https://user-images.githubusercontent.com/5720791/110138702-187f8780-7d87-11eb-968e-c9fd2c3be82c.png">

(And a red dot way over yonder, that just got another annotation.)

>Magic Coordinates

Those are the data, I can save you the clicking any time you want.

>directly from Google

Some of it comes from GeoLocate - not too surprising if they have slightly different ideas. 

Some of them may be on the wrong continent, and none will have complete data. I think that's still much more valuable than no coordinates at all - it gets them into "the system," you'll notice them on maps, my automation will leave annotations, other users will leave annotations etc., etc., etc. It also quality-stratifies your data

* Anything without coordinates (should be relatively few) can't be understood by machines and need a human
* Anything outside the geography will get flagged (eventually now, should be instantly when I get postGIS)
* Anything that doesn't get flagged is as least as good as the geography 

 I really think that should just be "part of Arctos" but I also realize it's probably outright heresy to some. Let me know if you want lots of the magic all at once....

**Comment by Jegelewicz** [comment]
If all of the "No specific locality recorded." localities have the wkt for whatever HG they included added to them, that would be helpful.

**Comment by dustymc** [comment]
>helpful

I'm not seeing how replicating data we KNOW to be a mess would be very helpful, particularly when we have less-confounded data just a click/request away.

**Comment by acdoll** [comment]
What if the 'more' link said 'see map' instead? I know there's more than just the map in there, but I think that might get more clicks. I've found some people are weary of clicking on random links just to see what is there.

**Comment by dustymc** [comment]
>'more' link said 'see map' instead?

I'm not sure that's quite right, but the idea is solid - there are a whole bunch of cryptic links (to the locality, to the geography, to the event, to the geography's source, maybe other stuff) in there. They're quick and easy to change, gimme values and I'll make it happen.

>this solution

Which one?

>County level coordinates are better than no coordinates

I think I'm arguing that ANY coordinates are better than none at the moment. "Bla County Utah [maps to China]" will get someone's attention and get flagged, if not fixed. "Bla County Utah" [there's no Bla County in Utah, sure this isn't supposed to be Florida?]" can and will persist under the radar for decades.

**Comment by dustymc** [comment]
I think https://github.com/ArctosDB/arctos/issues/4289 would make this entirely unnecessary, tabling.
