### ISSUE TITLE
Toggle between Bulkloader Browse view and Data Entry View misplaces collector

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3495]
**Describe the bug**
 When a record in the bulkloader Browse and Edit tool is viewed in the Data Entry view by clicking on the collection object ID, the collector name in the bulkload file populates the second collector agent field, rather than the first. This is a problem because the first agent field is required, and when the record is edited and saved, Arctos throws an error because it doesn't recognize that a required agent has been provided. The work around is to move the agent name from field 2 to field one, and then change the default value from preparator to collector. This is not optimal.

**To Reproduce**
1. Go to Bulkloader -> Browse and Edit
2. Click on collection object ID for one record
3. See the record in the Data Entry View - see the agent name in field 2 instead of the yellow, required field 1 of the agents table.
4. Try to save the record.
5. See error

**Expected behavior**
At least one agent and agent role should populate agent table field #1.

**Priority**
High. This prevents edit and save from Data Entry View.

**Comment by dustymc** [comment]
I need an example - I can't re-create and don't see anything in the code that could possibly cause this.

**Comment by campmlc** [comment]
Filter on Witt in bulkloader - there should be one record left in that
group.

**Comment by dustymc** [comment]
<img width="391" alt="Screen Shot 2021-03-05 at 3 15 29 PM" src="https://user-images.githubusercontent.com/5720791/110184833-ab3f1700-7dc5-11eb-889e-b85a96591b3c.png">
<img width="304" alt="Screen Shot 2021-03-05 at 3 15 37 PM" src="https://user-images.githubusercontent.com/5720791/110184836-ad08da80-7dc5-11eb-8955-3c7691251ac8.png">

**Comment by campmlc** [comment]
That record had been partially edited to move the collector name over to field 1.  I think I see the problem. The original bulkload file had collector agent 1 left blank, and the first collector agent entries were in collector_agent_2. So that is where they loaded in the bulkloader. I don't remember having to worry about what order any of our data were entered in prior to the PG move. If we are requiring data to be entered in a certain order, we should be explicit about this in the documentation. It would be best if Arctos could just populate the required fields in first-come order, as I recall used to happen. Possible?
