### ISSUE TITLE
Feature Request - Add "barcode" to bulkload part attribute to make my parts "unique" so I can use this bulkloader

### ISSUE THREAD

**Issue by KyndallH** [ArctosDB/arctos#3497]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
I need to update part attributes for records that have 30 of the same parts. Therefore, I cannot use the part bulkloader part attributes as is.

**Describe what you're trying to accomplish** 
I want to update attributes for a lot of specimen parts at once. 

**Describe the solution you'd like**
Add barcode to the bulkloader then my parts are not all the same.

**Describe alternatives you've considered**
Not entering the data.

**Additional context**

<img width="774" alt="Screen Shot 2021-03-05 at 12 53 07 PM" src="https://user-images.githubusercontent.com/16887896/110177891-1f6fbf80-7db2-11eb-9c0b-a0ab0d73f402.png">

**Priority**
Slightly above the black hole of despair.

**Comment by dustymc** [comment]
Needs rebuilt in the component loader system. I know how so going next task, needs prioritized.

**Comment by campmlc** [comment]
Priority high, especially if we are using part attributes for preservation.
