### ISSUE TITLE
Catalog Record Summary fails if state is included 

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#3499]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

I searched with results as a catalog record summary

with taxon formula =A
species = notnull
Taxon Term Value (search operator) = Apoidea
Type or Rank = Superfamily
Source(s) = Arctos

State/province = Alaska

This fails.

If I leave State/Province blank it works.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.
High

**Comment by dustymc** [comment]
I think that's just running out of CPU - if I had more I'd be happy to put it to good use!

Let me know what you want in your summary and I'll SQL it.
