### ISSUE TITLE
Species or specific epithet?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3502]
> Besides the two screenshots above, the only other search parameters were:
> genus:  "Anas"
> species: "platy"
> 
> I also tried searching by identification, or any taxon ID, and got the same thing.

_Originally posted by @ccicero in https://github.com/ArctosDB/arctos/issues/3488#issuecomment-790808551_

I am thinking about how taxonomy works in Arctos vs. other systems and this made me wonder about what is actually being searched in "Species". It appears that Carla searched using a part of the specific epithet in the "Species" field, but what is there is actually the binomial. While everything seems to work in her case, I'm wondering if there might be times that this would create unexpected results? Maybe it wouldn't, but in the world of taxonomy, "species" seems to be problematic and sometimes interchangeable with "specificEpithet", the Darwin Core term. I just want to make sure that when entering taxonomy, we aren't getting the binomial in some cases and the specific epithet in others....or maybe it doesn't matter?

**Comment by dustymc** [comment]
https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxon_term
