### ISSUE TITLE
Trying to find the last catalog number for ALMNH:Paleo

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/arctos#3504]
Can't find the last catalog number used.  When I go to find me the gaps, this is what I see: 
![image](https://user-images.githubusercontent.com/43214224/110382897-2a7c5700-8021-11eb-981c-760ba27778b1.png)

Three collections with ALMNH:ES and no ALMNH:Paleo.  Is this the only way I can find the next sequential number?  Thanks...

** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **

** Outages should be reported to the contacts listed at https://arctosdb.org/arctos-down/ **

** Arctos Documentation is http://handbook.arctosdb.org/ **

** Learn more about Arctos at https://arctosdb.org/ **

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **

**Comment by Jegelewicz** [comment]
One of those ES collections is paleo, one is Geol and the other is the old ES. @dustymc any way we can remedy this? I had the same issue with the two ES collections at NMMNH. Use the GUID prefix instead of Institution acronym + collection code?

**Comment by dustymc** [comment]
That form needs a full overhaul.

**Comment by Jegelewicz** [comment]
Thanks!
