### ISSUE TITLE
Specimen event bulkload download error

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#3506]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
When I try to download specimen events for a set of specimens, it throws an error

**To Reproduce**
Search for specimens
Click Manage
Scroll to Print Stuff
Select Download for Specimen Bulkloader 
See Error:
https://arctos.database.museum/SpecimenResultsDownload.cfm?action=bulkloaderFormat&&table_name=temp_cache.ss_aerochild_20210308050354269_890&sort=guid
![image](https://user-images.githubusercontent.com/38706617/110396364-26563680-802d-11eb-8531-e52d5c713fe9.png)

**Expected behavior**
For download to happen

**Screenshots**

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

Happening for the following archive:
https://arctos.database.museum/archive/mexicogeoref1

**Desktop (please complete the following information):**
Windows OS

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by dustymc** [comment]
I need clarification. If this is specimen events, it works for me. If it's specimen bulkloader format, it's just timing out for me - see https://github.com/ArctosDB/arctos/issues/2802
