### ISSUE TITLE
Clean up non-person agent with login name

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#3509]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I was trying to add my GitHub info to my Agent profile, and whenever I tried to save any data on the Agent page I got the following errors:
![Arctos error 1 copy](https://user-images.githubusercontent.com/18562884/110535037-01210100-80dd-11eb-922b-1e8746019c66.jpg)
![Arctos error 2](https://user-images.githubusercontent.com/18562884/110535045-041bf180-80dd-11eb-9dcd-2a5925c213f7.jpg)

I didn't change anything else on the page at all, just opened my agent profile so I'm not sure what is going on. I closed the tab and logged out, then logged in again and it gave me the same error.

It seems to be having a problem with my second login for my public searching, bwommack. I've had that login for several years now so I'm not sure what is going on.

**To Reproduce**
Go to Agent -> search for Elizabeth A. Wommack -> attempt to make any changes and then click save.

**Expected behavior**
I can save changes to other agent profiles, so there seems to be something specifically wrong with mine.

**Desktop (please complete the following information):**
 Mac OS Chrome

**Comment by dustymc** [comment]
Yes, it's not happy about the additional login name. I can get rid of it for you - I'll have to lock some things down so probably after hours - or we can talk about something more complicated than a 1:1 agent/operator relationship.

**Comment by ewommack** [comment]
> I can get rid of it for you

Get rid of the error or get rid of the login?
I'm fine waiting. I can live with ignoring the red box for now.

Why was I getting away with this until now?

**Comment by ewommack** [comment]
> The extraneous 'login' name.

So to keep my public access login does that mean I would need to create another agent for myself, or would it just be a login that isn't associated with a person?

I'd really prefer to keep it if possible and just not have it associated with my agent profile. I have a number of saved searches and I do a bit of work with that public log in. Without it I cannot search and download data from other Arctos collections outside of my own.

**Comment by dustymc** [comment]
>create another agent for myself,

That should just never be done (and it's part of what lead to this rule, https://groups.google.com/g/arctos-working-group/c/-8IMFg_Z0Tk/m/NC-63vPTAQAJ)

>login that isn't associated with a person?

It can be (and is) associated with a person via the user profile, the (potential) problem is with the Agent association. 

The ONLY functional implication of removing "bwommack" as one of your 'login' names is that you'll no longer be able to click from https://arctos.database.museum/agents.cfm?agent_id=21247374 to https://arctos.database.museum/AdminUsers.cfm?action=edit&username=bwommack and back, which does nothing very exciting anyway.

You'd also no longer be able to invite bwommack to become an Operator, a situation which some code isn't currently capable of handling.

You are most welcome to as many public profiles as you'd like to create. If you need multiple logins, then we need some development to support that.

**Comment by dustymc** [comment]
>Ok so solution is to delete the bwommack login from the Agent Profile, but you'll need to do it since it is freezing up now and won't let anything be saved?

Yes, that's the easy solution, assuming we're not missing some kind of functionality.

>updating any handbook material

Yes please, something's obviously ambiguous (or just not being read - see "Operators must be agents of type “person.” Group accounts or shared logins are not permitted." at https://handbook.arctosdb.org/documentation/users.html).

>other

Yikes, and yes.

```

arctosprod@arctos>> select preferred_agent_name from agent where agent_id in (select agent_id from agent_name where agent_name_type='login' group by agent_id having count(*) > 1);
  preferred_agent_name  
------------------------
 Perry F. Pearson
 Rika DeVore
 Shane Armstrong
 Chauncey Gadek
 Alex Krohn
 Katie Nehiba
 Paula Barteau
 Jessica Grady
 Saodi Etheridge-Bullie
 Robert C. Dowler
 Katherine Latham
 Elizabeth A. Wommack
```

**Comment by ewommack** [comment]
Sounds good @dustymc. Let me know if that fix works when you want to give it a try tonight.

@Jegelewicz looks like we need to update some handbook material about Agents and login info. The confusion here was when you need both a curatorial login and a public login. I've got a talk tomorrow evening, so I'm a bit swamped but I can try and get to this later in the week.
I think more this isn't about problems of creating multiple users and agents (though we want to avoid that), but in clearer instructions on what you should do if you have someone who needs to access Arctos through both their collections and the wider search portals. 
Maybe a section on:
**If you are an Arctos User with Access to a Collection, How to Access the Full Arctos Search Portals With a Second Public Non-User Profile/login**
?

**Comment by Jegelewicz** [comment]
@ewommack OK - I'll work on the documentation, but @dustymc any way we can only ALLOW one Arctos username for any given agent? I don't care how much documentation we write, someone is still going to do that....

**Comment by Jegelewicz** [comment]
See additions to documentation:

How to Create Agents - https://handbook.arctosdb.org/how_to/How-to-Create-Agents.html#name-type-login
Agent Documentaion - https://handbook.arctosdb.org/documentation/agent.html#names

Anything else?

**Comment by dustymc** [comment]
> only ALLOW one Arctos username 

That's what caused this error. We also need to deal with these, which should currently be impossible to create.

```

arctosprod@arctosutf>> select preferred_agent_name,agent_type from agent where agent_type!='person' and agent_id in(select agent_id from agent_name where agent_name_type='login');
        preferred_agent_name         | agent_type  
-------------------------------------+-------------
 MSB DOM Volunteer                   | group
 Emerging Infectious Disease Project | other agent
 ASU App Team                        | group

```

I don't think I'd be able to find more like https://arctos.database.museum/agents.cfm?agent_id=21332030, which went through a convoluted path around various rules meant to create predictable data.

>don't care how much documentation

Don't disagree, but I think we should also have an expectation of people not trying to break the system. If we can't, then we need to spend more time on hard rules, or lower our expectations, or something.

**Comment by ewommack** [comment]
> See additions to documentation:
> 
> How to Create Agents - https://handbook.arctosdb.org/how_to/How-to-Create-Agents.html#name-type-login
> Agent Documentaion - https://handbook.arctosdb.org/documentation/agent.html#names
> 
> Anything else?
That looks good to me. Do you think we need a section on public profiles for Users, or word of mouth is still the best? Might be better to keep it under wraps so we do not get this problem more?

@dustymc I checked and my profile still has both logins. Should I get rid of the cache?

**Comment by dustymc** [comment]
>still has both logins

I haven't found time to clean them up yet.

>remove the login names

I can probably deal with everything except https://arctos.database.museum/agents.cfm?agent_id=21332030. There may be a use case that'll cause us to rethink our model, but there's no discussion and I'm not happy with the miscategorized agent nor the denormalization so ???????????????.

**Comment by dustymc** [comment]
I cleaned up what I can.

**Comment by Jegelewicz** [comment]
> I can probably deal with everything except https://arctos.database.museum/agents.cfm?agent_id=21332030. There may be a use case that'll cause us to rethink our model, but there's no discussion and I'm not happy with the miscategorized agent nor the denormalization so ???????????????.

@campmlc @lin-fred we need to resolve this - why exactly does Lindsey need a second Arctos operator account?

**Comment by acdoll** [comment]
I believe Lindsey needed access to the DGR collections, but not the same level of access as she has for the NMMNH collections.

**Comment by lin-fred** [comment]
> I believe Lindsey needed access to the DGR collections, but not the same level of access as she has for the NMMNH collections.

Yes. Is there any other way to do this?

**Comment by Jegelewicz** [comment]
I don't believe so, but also I think that MSB should trust you enough to know that you aren't going to do anything nefarious. I have the same access as Mariel does to all MSB collections and nobody has complained because I know better than to mess with stuff that I shouldn't and Lindsey does too. @campmlc @jldunnum can we just give Lindsey access to the collections she needs with her original login?

**Comment by jldunnum** [comment]
I'm fine with that , let's just be sure Lindsey gives us a heads up if she is planning to do big changes/updates so we can check to see that there aren't any issues.

______________________________________________________________

Jonathan L. Dunnum Ph.D.
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by lin-fred** [comment]
I would only be doing large changes if I was asked by you all to do so? Otherwise, you will need to define "large changes," as you seem to have an idea but I do not. 

Where is this worry coming from exactly? It seems unwarranted. Based off your comments, is there some sort of agreement that you have people sign in general when they get access? I used to have extensive access to MSB records only a few years ago. 

I think we will need to revisit what it is I am doing exactly with MSB. I am having to jump through hoops just to gain any online or physical access.

**Comment by jldunnum** [comment]
Need to bring Mariel into the conversation because I'm not sure exactly what she will have you doing up in DGR. My point is simply that anyone working in the database with that level of access needs to be communicating with the CM of that division so everyone is one the same page. Don't think anyone is deliberately trying to make you go through hoops. Happy to have you working up here again.

______________________________________________________________

Jonathan L. Dunnum Ph.D.
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by ewommack** [comment]
Do you want to create a second issue? 
@dustymc resolved the problem that this issue was written about, and I just checked everything in my Agent Profile is working ok. I could close this one out, but it seems to have wandered into broader another broader issue?
