### ISSUE TITLE
Classification not showing in new ALMNH:Paleo collection

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3511]
from @mbprondzinski 
> Some of our species names don’t have the hierarchal data associated with them.  In the past, I have deleted the name and re-entered it with the hierarchal data.  Is it really necessary for me to have to delete the name and start over?  Also, how many records are like this?  We have discovered that when searching for a family, a number of records that aren’t associated with a hierarchy, are not showing up.  This happened when the Paleo records were bulkloaded apparently.

**Comment by Jegelewicz** [comment]
I'm not sure that I understand. Names are associated with classifications and depending upon which classification you prefer, you may or may not get an associated classification. When you say delete the name, where are you deleting it?

**Comment by Jegelewicz** [comment]
reply from @mbprondzinski 

> I have to edit the scientific name.  I delete it and then re-enter it and attach the hierarchy ( Arctos) I want associated with it.  See ALMNH:Paleo:100.  There is no hierarchical taxonomy associated with it.  When the UI team searched on the family that should be associated with it, it did not show up in the returned records.  Capiche?!

**Comment by Jegelewicz** [comment]
@mbprondzinski is your preferred taxonomy source in manage collections set with Arctos as number 1?

**Comment by mbprondzinski** [comment]
Yes. But ALMNH:Paleo for the most part was bulkloaded way back when, so I can't say we had a "preferred" taxonomy source when it was uploaded.  I don't know who would have been responsible for choosing one.

**Comment by dustymc** [comment]
Yes there's a lag, can be a few days with taxonomy. Let me know if it's not eventually catching up and I can try to investigate. There's also a request refresh button on the record (if you have access, I don't) that you can use to get the current "cache" data.

Taxonomy including classifications is a shared resource. Please be very careful with things like preemptive deletions.

**Comment by mbprondzinski** [comment]
Don't worry, I only delete it from my respective records after I've updated them.

**Comment by Jegelewicz** [comment]
@dustymc I'm wondering if this is happening because of the new collection - any way we can make sure that ALMNH:Paleo and ALMNH:Geol get updated so that Mary Beth doesn't have to go through 10K records one by one to make sure things are updated?

**Comment by dustymc** [comment]
I can't tell without access. There's only 10K records, I just set them all to refresh.

**Comment by Jegelewicz** [comment]
@mbprondzinski please close this is everything looks good.
