### ISSUE TITLE
Code Table Request - add vertebra as a part for fish collections

### ISSUE THREAD

**Issue by zmsch** [ArctosDB/arctos#3513]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

Code Table Documentation is https://handbook.arctosdb.org/how_to/How-to-Use-Code-Tables.html

**Goal**
Allow fish collections to use the existing "vertebra" part

**Context**
The closest existing value for fish collections is "skeletal element" which is vague and the definition isn't a good fit. It would be useful to have vertebra as a distinct part option because they can be used to age fish.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name&coln=Fish

**Value**
vertebra (already exists)

**Definition**
NA - already exists

**Collection type**
Fish

**Comment by campmlc** [comment]
No objections.

**Comment by Jegelewicz** [comment]
Added
