### ISSUE TITLE
Feature Request - taxon relation bulkloader

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3519]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

https://github.com/ArctosDB/arctos/issues/2543

**Describe what you're trying to accomplish** 

Bulkload taxon relationships

**Describe the solution you'd like**

Component loader.

**Describe alternatives you've considered**

SQL - this is apparently rare.

I know how so next task, needs prioritized.

**Comment by Jegelewicz** [comment]
I have also been thinking about this as I work on TPT taxonomy which includes "curated" lists of synonyms and this tool would be useful, but it would also be nice to add "preferred name" to the associated classifications as these relationships are made which seems like a huge ask, so I am not asking for it here, just planting the seed.

**Comment by dustymc** [comment]
Yes that's something different - preferred name might be unique for every Source. (If there's a use case for preferred name in the current model at all - I'm not so sure...)

It should be pretty simple to pull (preferred_name,scientific_name) from your classification CSV and feed it to a relationship loader.
