### ISSUE TITLE
UAM Art taxonomy source term additions

### ISSUE THREAD

**Issue by krgomez** [ArctosDB/arctos#3520]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

Code Table Documentation is https://handbook.arctosdb.org/how_to/How-to-Use-Code-Tables.html

**Goal**
Describe what you're trying to accomplish.
There are five object type terms currently used by the UAM:Art collection that are not in the Getty AAT: Cibachrome print, Ektacolor print, Ektaflex print, Nimslo print and archival pigment print. We are in touch with the Getty vocab program about possibly adding each of these terms into the AAT. In the meantime, we would like to have these available for use in Arctos by adding the terms to the UAM Art taxonomy source. 

**Context**
Describe why this new value is necessary and existing values are not.
The alternative would be to wait to see if these terms end up being added to the official Getty AAT and in the meantime continue to use "unidentifiable" for the ~300 objects that are cataloged as Cibachrome prints, Ektacolor prints, Ektaflex prints, Nimslo prints and archival pigment prints. However, this could take a while, and even if any are not officially added, they are to the best of our knowledge the proper terms for describing these objects. 

**Table**
Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table you are requesting changes to here.
UAM Art taxonomy source

**Value**
Proposed new value
Object --> Visual and Verbal Communication --> Visual Work --> Visual Work (works) --> Photograph --> Positive (photograph) --> Photographic Print --> Silver-dye Bleach Print --> Cibachrome Print
Object --> Visual and Verbal Communication --> Visual Work --> Visual Work (works) --> Photograph --> Positive (photograph) --> Photographic Print --> Chromogenic Color Print --> Ektacolor Print
Object --> Visual and Verbal Communication --> Visual Work --> Visual Work (works) --> Photograph --> Positive (photograph) --> Photographic Print --> Chromogenic Color Print --> Ektaflex Print
Object --> Visual and Verbal Communication --> Visual Work --> Visual Work (works) --> Photograph --> Positive (photograph) --> Photographic Print --> Nimslo Print
Object --> Visual and Verbal Communication --> Visual Work --> Visual Work (works) --> Print --> Digital Print --> Inkjet Print --> Archival Pigment Print

**Definition**
Clear, complete, non-collection-type-specific definition of the new value.
**Cibachrome print** - Photographic print made with an extremely high-gloss paper manufactured by Ilfochrome and first introduced in 1963. Uses a silver dye-bleach process that forms an image by selectively bleaching dyes already existing within the paper. Renowned as one of the most stable, longest-lasting of all color prints. 
**Ektacolor print** - Photographic print produced from a color negative printed on paper coated with a resined plastic. The most commonly produced color print of the modern era.
**Ektaflex print** - Photographic print made through the Ektaflex process.
**Nimslo print** - Photographic print made with a Nimslo camera.
**archival pigment print** - Print made from a digital file using a printer that applies very fine drops of archival pigment ink on paper.

**Collection type**
If the code table includes a "Collection" column. Ex: Mamm, Herp, ES
Art

**Priority**
Please choose a priority-label to the right.
Normal

**Comment by krgomez** [comment]
Awesome, thank you Teresa!

**Comment by Jegelewicz** [comment]
Names are loaded, but when I went to load classifications:

> An error occurred while processing this page!
> Message: ERROR: permission denied for table cf_temp_classification
> Detail:
> Check the Arctos Handbook for more information on errors.
> 
> This message has been logged as 4D2164F8-3E38-4D9C-BEA02CEBDEC8C15A Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue. 

@dustymc

**Comment by dustymc** [comment]
How about now?

**Comment by Jegelewicz** [comment]
@krgomez These have been added.

**Comment by krgomez** [comment]
Thank you!!
