### ISSUE TITLE
Code Table Request - Wildlife Rescue Inc., of New Mexico AND New Mexico Wildlife Center

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#3521]
See latest comments pertaining to issue [2588](https://github.com/ArctosDB/arctos/issues/2588)

Add Wildlife Rescue Inc., of New Mexico as an other_ID_num_type
Add New Mexico Wildlife Center as an other_ID_num_type

This will allow us to enter their rehab numbers as other_ID_num which is better than collector number even though these rehab centers are also entered as agents.

@Jegelewicz Can I just do this, so I can get data uploaded? This is holding me back.

**Comment by dustymc** [comment]
Need definitions - these seem to have websites, that should be part of the definition.

I think for otherIDs we should also evaluate whether there might realistically be a base_url available at some point, and push things where that's unlikely towards some generic type (we have lots to choose from!). I'll add to https://handbook.arctosdb.org/how_to/How-to-Use-Code-Tables.html if there are no objections or better ideas.

These both look reasonable to me, but anyone who actually knows anything should chime in.

**Comment by Jegelewicz** [comment]
Added with links to the websites.

**Comment by ccicero** [comment]
Thanks Teresa! Sorry, should have put defs and URLs in the issue.

@dustymc can you give an example of what you mean by "generic type" ? I think it's unlikely these will have a base_url in the future.

**Comment by dustymc** [comment]
>"generic type"

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type&field=other%20identifier seems as good as any. collector number, field number, original identifier, secondary identifier, and I'm sure a few more look the same from here - I can't see any real reason you'd pick one over any other....

>unlikely these will have a base_url

If they don't have/won't any data that might be accessed through the ID, then I have a hard time seeing a functional distinction between``New Mexico Wildlife Center`` = ``1234`` and ``other identifier`` = ``New Mexico Wildlife Center: 1234``. They'll both get people from the record to the same place, neither are very useful to machines, and with the latter we'd have one less value plugging up the dropdowns.

```
arctosprod@arctos>> select count(*) from ctcoll_other_id_type ;
 count 
-------
   495
```

**Comment by ccicero** [comment]
Yes, I agree. That was my point earlier  (though not made clearly, apparently). No functional difference between using 'other identifier' vs having the number associated with the the name as an other_ID_num_type. That's why I was asking about values that exist both as agents and other_ID_num_type. In this case, the same organization exists in both places, why not just have it as an agent but with an other identifier as the number, rather than duplicating the name again in other_ID_num_type.

**Comment by Jegelewicz** [comment]
> why not just have it as an agent but with an other identifier as the number, rather than duplicating the name again in other_ID_num_type.

That works too https://github.com/ArctosDB/arctos/issues/2588#issuecomment-799659198

I can delete the other ID types if you aren't going to use them.

**Comment by ccicero** [comment]
Exactly, that's my point. That's why I asked about organizations that exist both as an agent and an other_ID_num_type.

Maybe a discussion for our Thursday code table meeting?

**Comment by Jegelewicz** [comment]
> organizations that exist both as an agent and an other_ID_num_type.

One example can occur when the organization assigning the number was NOT the collector.

**Comment by dustymc** [comment]
>Thursday code table meeting?

Fine with me.

>organizations that exist both as an agent and an other_ID_num_type

Those are different THINGs, and I think it's usually a mistake to confound them (at least if machines need to figure it out). There's some potential connection, @Jegelewicz may have it figured out, don't think I do. 

The obvious functional link is that the agent can be used for things like 'find all New Mexico Wildlife Center records' - maybe we really should consider getting rid of most everything without a base_url (excepting "local" stuff - AF, NK, etc. - and I suppose at least one 'random number scribbled on something')? That'd make the dropdowns about half as crowded as they are now, and I'm struggling to see any lost functionality.

```

arctosprod@arctos>> select count(*) from ctcoll_other_id_type  where base_url is not null;
 count 
-------
   245

```

And we should probably review our base_urls periodically 

 FMNH:Zoo Field Museum of Natural History Zoology doesn't seem to do anything very interesting
AMNH: GBIF has some REALLY dicey assumptions behind it (catalog number is unique!) - even though the two I clicked hold up, sorta, for now...

IBUNAM:MEXU: isn't used at all

Naturalis Biodiversity Center BioPortal isn't used

NHMUK: Natural History Museum, United Kingdom - ditto

I'm not sure ANYTHING other than Arctos, baby-Arctos, and GenBank work! Where'd all that come from??

**Comment by Jegelewicz** [comment]
> I have a hard time seeing a functional distinction between New Mexico Wildlife Center = 1234 and other identifier = New Mexico Wildlife Center: 1234. 

The difference is that if you choose

> other identifier = New Mexico Wildlife Center: 1234

you will also end up with

> other identifier = NM Wildlife Center: 1234
> other identifier = NMWC: 1234
> other identifier = New Mexico Wildlife Center 1234
> other identifier = New Mexico Wildlife Center - 1234

and a million other possible ways of saying New Mexico Wildlife Center. Which also means you will probably never be able to find them all if you want to.

**Comment by Jegelewicz** [comment]
> 
>>     organizations that exist both as an agent and an other_ID_num_type
> 
> Those are different THINGs, and I think it's usually a mistake to confound them (at least if machines need to figure it out). There's some potential connection, @Jegelewicz may have it figured out, don't think I do.

There is definitely a connection and we have been discussing it in #2847

I have been making half-hearted attemts to connect things by putting a link to the agent in the definition of the other ID. See

IDType | Description
-- | -- 
MCZ: Museum of Comparative Zoology, Harvard University | Museum of Comparative Zoology, Harvard University. Arctos agent: https://arctos.database.museum/agents.cfm?agent_id=21263691

Which I could be formatting better, but I did this a while back...

**Comment by dustymc** [comment]
>never be able to find them 

The Agent does that, and your (accurate) picture of the data is still good enough for a human to figure it out. I'm still not seeing lost functionality.

**Comment by Jegelewicz** [comment]
What agent? It is very possible that New Mexico Wildlife Center is one of many agents listed in collector or possibly not listed at all because the collector was Jane Doe and the DONOR (listed in the accession) is New Mexico Wildlife Center. There is not always a direct path from a number to an agent with the way we have disengaged numbers from who assigned them.

**Comment by Jegelewicz** [comment]
> IBUNAM:MEXU: isn't used at all
> 
> Naturalis Biodiversity Center BioPortal isn't used
> 
> NHMUK: Natural History Museum, United Kingdom - ditto

I searched GitHub issues to see who requested them, but got zip. I think the Naturalis one came about when we were talking to them about Arctos, they all seem familiar-ish to me, but maybe if we know who added them it will help? (Of course, it could have been me....)

**Comment by dustymc** [comment]
>What agent?

https://github.com/ArctosDB/arctos/issues/3521#issuecomment-799762115 - the one Carla's presumably created for this.

>the DONOR (listed in the accession) is New Mexico Wildlife Center.

I'm still not seeing lost functionality; if someone ever finds a reason to care, which seems remote given https://github.com/ArctosDB/arctos/issues/3521#issuecomment-799735359, a person will still find that.

1. If we have thousands and thousands of structured identifiers, they will be mis-assigned. I will not be able to detect that without a base_url.

2. If we have many fewer less-structured identifiers, they will be easier to enter but more difficult to resolve if that need ever arises.

We're (sorta) doing (1) now. I'm asking if the real usability benefits of (2) outweigh any theoretical organizational benefits of (1).

**Comment by dustymc** [comment]
>who requested them,

Yea that's where I stopped too; if it's not there it's "legacy" and therefore suspect in my view, I guess.... It's so incredibly useful to tie values to discussions, I wonder if we should even have some tighter link - github discussion URL in the definition or even something more permanent/formal? 

>who

https://arctos.database.museum/info/ctchange_log.cfm?tbl=ctcoll_other_id_type, which you can only click to from the CT editor - I wonder if that could/should be made more accessible somewhere/how?

Here's the actually-not-used if you want to chase anything down.

```
arctosprod@arctos>> select distinct ctcoll_other_id_type.other_id_type from ctcoll_other_id_type 
arctos-> left outer join  coll_obj_other_id_num on coll_obj_other_id_num.other_id_type =ctcoll_other_id_type.other_id_type
arctos-> where (ctcoll_other_id_type.base_url is null or  ctcoll_other_id_type.base_url not like 'http://arctos%' ) and 
arctos-> coll_obj_other_id_num.other_id_type is null group by ctcoll_other_id_type.other_id_type order by ctcoll_other_id_type.other_id_type;
                                other_id_type                                
-----------------------------------------------------------------------------
 ALMNH: Alabama Museum of Natural History
 AMNH:Bird
 Brooklyn Museum
 CHIC: Chicago Botanic Garden
 CIB: Chengdu Institute of Biology
 CSU-Fresno: California State University, Fresno
 CSUS: California State University Sacramento
 IBUNAM:MEXU:
 ISM: Illinois State Museum
 Moorea Biocode Project Number
 Naturalis Biodiversity Center BioPortal
 RMNH.RENA
 SASK: W.P.Fraser Herbarium
 Title
 TU:Tulane University
 WIL: Wildlife Investigations Laboratory, CA Department of Fish and Wildlife
 ZMA.AVES: Universiteit van Amsterdam, Zoologisch Museum)
 ZMA.RENA: Universiteit van Amsterdam, Zoologisch Museum
(18 rows)
```

**Comment by Jegelewicz** [comment]
> github discussion URL in the definition or even something more permanent/formal?

I like this idea very much - it adds context to anything that happens. Maybe ALL code tables should have an additional column with the GitHub issue number (link auto-generated)?

**Comment by dustymc** [comment]
>additional column

If we're going to that much work, I'd rather have something that can survive "and then GitHub went away." That's probably Arctos3.0 or something, I'll update https://handbook.arctosdb.org/how_to/How-to-Use-Code-Tables.html for now.

**Comment by Jegelewicz** [comment]
I don't think there is anything to do here? Closing for now.
