### ISSUE TITLE
Code Table Request - crop content (95% ethanol)

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#3523]
Request is to add "crop content (95% ethanol)" to ctspecimen_part_name

The parts code table currently has:
crop content (70% ethanol)
crop content (dry)

I am in the process of bulkloading and have a part that's "crop content (95% ethanol)"

@Jegelewicz @dustymc Can we add this part to the code table?

Definition:
Contents of the crop, preserved in 95% ethanol.

I can do it now if approved, so that I can finish the bulkloading. Thanks!

**Comment by Jegelewicz** [comment]
Ok by me

**Comment by ccicero** [comment]
Done, thanks.

**Comment by ewommack** [comment]
Thanks Carla! We'll have some of these soon.
