### ISSUE TITLE
Unused other identifiers

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3524]
>who requested them,

Yea that's where I stopped too; if it's not there it's "legacy" and therefore suspect in my view, I guess.... It's so incredibly useful to tie values to discussions, I wonder if we should even have some tighter link - github discussion URL in the definition or even something more permanent/formal? 

>who

https://arctos.database.museum/info/ctchange_log.cfm?tbl=ctcoll_other_id_type, which you can only click to from the CT editor - I wonder if that could/should be made more accessible somewhere/how?

Here's the actually-not-used if you want to chase anything down.

```
arctosprod@arctos>> select distinct ctcoll_other_id_type.other_id_type from ctcoll_other_id_type 
arctos-> left outer join  coll_obj_other_id_num on coll_obj_other_id_num.other_id_type =ctcoll_other_id_type.other_id_type
arctos-> where (ctcoll_other_id_type.base_url is null or  ctcoll_other_id_type.base_url not like 'http://arctos%' ) and 
arctos-> coll_obj_other_id_num.other_id_type is null group by ctcoll_other_id_type.other_id_type order by ctcoll_other_id_type.other_id_type;
                                other_id_type                                
-----------------------------------------------------------------------------
 ALMNH: Alabama Museum of Natural History
 AMNH:Bird
 Brooklyn Museum
 CHIC: Chicago Botanic Garden
 CIB: Chengdu Institute of Biology
 CSU-Fresno: California State University, Fresno
 CSUS: California State University Sacramento
 IBUNAM:MEXU:
 ISM: Illinois State Museum
 Moorea Biocode Project Number
 Naturalis Biodiversity Center BioPortal
 RMNH.RENA
 SASK: W.P.Fraser Herbarium
 Title
 TU:Tulane University
 WIL: Wildlife Investigations Laboratory, CA Department of Fish and Wildlife
 ZMA.AVES: Universiteit van Amsterdam, Zoologisch Museum)
 ZMA.RENA: Universiteit van Amsterdam, Zoologisch Museum
(18 rows)
```

_Originally posted by @dustymc in https://github.com/ArctosDB/arctos/issues/3521#issuecomment-800431507_

**Comment by campmlc** [comment]
These can be removed, because we only added them for the Naturalist demo.
Unless we need to show DIsSCO what we can do.

Naturalis Biodiversity Center BioPortal

And both ZMA IDs.

**Comment by Jegelewicz** [comment]
Removed:

Type | Description | Base URL
-- | -- | --
Naturalis Biodiversity Center BioPortal | Naturalis Biodiversity Center BioPortal registration number and citation url, Naturalis Biodiversity Center, Netherlands; registration = catalog number is case sensitive, eg RMNH.AVES.12345 | http://data.biodiversitydata.nl/naturalis/specimen/ 
ZMA.AVES: Universiteit van Amsterdam, Zoologisch Museum) | Zoological Museum Amsterdam, University of Amsterdam (NL) – Herpetology catalog number;  Universiteit van Amsterdam, Zoologisch Museum Registratienummer | http://data.biodiversitydata.nl/naturalis/specimen/ZMA.AVES.
ZMA.RENA: Universiteit van Amsterdam, Zoologisch Museum | Zoological Museum Amsterdam, University of Amsterdam (NL) – Herpetology catalog number; Universiteit van Amsterdam, Zoologisch Museum Registratienummer | http://data.biodiversitydata.nl/naturalis/specimen/ZMA.RENA.

**Comment by Jegelewicz** [comment]
> Unless we need to show DIsSCO what we can do.

Unless we have an actual example to link - not sure we can show them anything.

**Comment by dustymc** [comment]
done
