### ISSUE TITLE
documentation link to data

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3528]
ref: https://github.com/ArctosDB/arctos/issues/2588#issuecomment-802902341

make it better

* make sure it works for "special" CTs
* add something clicky and 'permalink'-like
* investigate better highlighting - the bold is maybe too subtle

**Comment by dustymc** [comment]
In next release

@Jegelewicz http://test.arctos.database.museum/agent/21300608 will work in next release as well.

**Comment by Jegelewicz** [comment]
Thanks man!
