### ISSUE TITLE
Auto-generated annotations

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#3530]
In trying to decide how to handle one of our annotations (https://arctos.database.museum/guid/DMNS:Egg:1113), I ended up creating 12 new annotations (each time I reloaded the page). Is there a way to prevent this or maybe an option to delete auto generated annotations? Or do you have other thoughts? 

For this example, I was trying to capture the fact that the locality was in one county at the time of collection, but borders have changed and it is now in a new county. I thought adding a new event with the current county would work, but leaving the old event with the historical county will result in continued annotations. I should probably remove the old event, but want to check physical records to see if that county was verbatim information or if that was determined at some later time.

**Comment by dustymc** [comment]
>12 new annotations 

I've waffled around on that a bit. It's a (potential) indication of importance (lots of people are looking at this record), but it's also apparently a pain to manage and of course doesn't mean anything useful when it's one person many times. Unless someone has better ideas I'll see if I can stop duplicates and merge existing - it now seems that making your workload more manageable should win out over any theoretical benefits to logging everything.

>remove the old event

Never! Just mark it 'unaccepted' (if that's the case).

And please leave remarks on the geography - not ideal, but it's what we can support at the moment.

**Comment by acdoll** [comment]
So 'unaccepted' will prevent the annotations?

**Comment by dustymc** [comment]
yes

**Comment by Jegelewicz** [comment]
https://github.com/ArctosDB/arctos/issues/3530#issuecomment-802994888

Needs documentation?

**Comment by acdoll** [comment]
I waffled on this too - I like that they are generated when others are looking at the records and it does indicate importance. Maybe we can delete annotations that we created (either manually or autogenerated by visiting page)?

**Comment by dustymc** [comment]
>documentation

Maybe? It's just an annotation, anyone can leave them. I suppose these are a little special in that I can give myself API keys, but that's the only difference between these and any other.

We definitely need better documentation for handling annotations - I think maybe I was supposed to start that....

>waffled on this too

In that case maybe I'll put it off until postgis happens if that works for everyone - I'm only using this way because it's about the only path I have to the tools, once I have better tools this could somehow be more predictable.

>delete

I dislike the idea, particularly after the recent GBIF discussions. We can certainly do something clever with some flag or the UIs or WHATEVER, but "we don't delete" seems much more Research Grade than any form of "we do delete, but...."

**Comment by acdoll** [comment]
> put it off until postgis

That seems reasonable to me. 

> I dislike the idea, particularly after the recent GBIF discussions.

That's a fair point. On the review page, can we possibly group identical annotations so they can all be addressed with a single review comment? Maybe just adding date/time stamps to a single annotation every time it is repeated? Or just display the number of times that annotation has been reported? 
It is functioning as it is designed to, I just want to make the process of resolving issues a little easier.

**Comment by dustymc** [comment]
The next release will have what's necessary to generate spatial problem reports (maybe even the reports) and will no longer be autogenerating annotations, but I still don't know what to do with the existing automated annotations. We could

* delete them (see above, I dislike deleting on principle, but magically created data isn't exactly "data")
* auto-review them ('moved to internal report' or something, will make them green and not appear in annotation reports)
* do something else (I'm up for anything)
* do any of that on a collection-by-collection basis (but I'd rather not if possible)

Help!

Data:

```
select guid_prefix,count(*) c from flat
inner join annotations on flat.collection_object_id=annotations.collection_object_id
where annotation like '%[Detected by automation from specimen detail page.]%'
group by guid_prefix order by guid_prefix;



 guid_prefix  |  c   
--------------+------
 ACUNHC:Mamm  |    2
 ACUNHC:Paleo |    1
 ALMNH:Geo    |    3
 ALMNH:Inv    |   88
 ALMNH:Paleo  |   88
 APSU:Herp    |  490
 ASNHC:Bird   |   30
 ASNHC:Herp   |    7
 ASNHC:Mamm   |  103
 ASUMZ:Fish   |    3
 BYU:Herp     |  478
 BYU:Mamm     |   35
 BYUObs:Herp  |    7
 CHAS:Bird    |   41
 CHAS:Egg     |   30
 CHAS:Fish    |    1
 CHAS:Herb    |    5
 CHAS:Herp    |    7
 CHAS:Inv     |    7
 CHAS:Mamm    |   53
 DMNS:Bird    |  944
 DMNS:Egg     |   20
 DMNS:Herp    |    9
 DMNS:Inv     |  819
 DMNS:Mamm    |  811
 DMNS:Para    |   86
 HMCM:Arthro  |    2
 HMCM:Herb    |   27
 HWML:Para    |   35
 JSNM:Egg     |   31
 JSNM:Herb    |    4
 JSNM:Paleo   |  372
 KNWR:Ento    |   16
 KNWR:Herb    |   47
 KNWR:Inv     |    6
 KNWRObs:Herb |   10
 KWP:Ento     |    7
 MLZ:Bird     |   22
 MLZ:Fish     |   51
 MLZ:Herb     |    4
 MLZObs:Fish  |    2
 MSB:Bird     |  164
 MSB:Fish     |   77
 MSB:Herp     |  593
 MSB:Host     |   75
 MSB:Mamm     | 1221
 MSB:Para     |  418
 MVZ:Bird     |  275
 MVZ:Egg      |  160
 MVZ:Fish     |   15
 MVZ:Herp     |  581
 MVZ:Hild     |    9
 MVZ:Mamm     |  619
 MVZObs:Bird  |   11
 MVZObs:Herp  |    7
 NMMNH:Geol   |    2
 NMMNH:Herb   |    6
 NMMNH:Inv    |    3
 NMMNH:Mamm   |   43
 NMMNH:Paleo  |   33
 NMU:Mamm     |  145
 NMU:Para     |   13
 OWU:Amph     |    3
 OWU:ES       |    3
 OWU:Fish     |   25
 OWU:Rept     |    4
 UAM:Alg      |    2
 UAM:Art      |   24
 UAMb:Herb    |   11
 UAM:Bird     |   36
 UAM:EH       |  147
 UAM:Ento     |  130
 UAM:Env      |    2
 UAM:ES       |  414
 UAM:Fish     |   31
 UAM:Herb     |  435
 UAM:Herp     |    1
 UAM:Inv      |    2
 UAM:Mamm     |  468
 UAMObs:Ento  |   29
 UAMObs:Mamm  |    3
 UCM:Bird     |   33
 UCM:Fish     |    7
 UCM:Herp     |   43
 UCM:Mamm     |    7
 UCM:Obs      |   34
 UCSC:Herp    |    2
 UMNH:Herp    |    1
 UMNH:Mamm    |  225
 UMZM:Bird    |   87
 UMZM:Mamm    |   15
 UNCG:Mamm    |   49
 UNCG:Para    |    1
 UNR:Herp     |    4
 UNR:Mamm     |   16
 UTEP:Bird    |    3
 UTEP:Ento    |  230
 UTEP:ES      |    3
 UTEP:Herb    |  209
 UTEP:Herp    |   70
 UTEP:HerpOS  |    7
 UTEP:Inv     |   32
 UTEP:Mamm    |    8
 UTEPObs:Herp |    1
 UTEP:Zoo     |    4
 UWBM:Herp    |   23
 UWBM:Mamm    |   81
 UWYMV:Bird   |   17
 UWYMV:Herp   |    2
 UWYMV:Mamm   |   55
```


 @jrdemboski
 @keg34
 @kyndallh
 @amgunderson
 @gracz-UNL
 @jldunnum
 @catherpes,@catherpes
 @msbparasites
 @campmlc
 @dssikes
 @StefanieBond
 @leet1984
 @jtgiermakowski
 @mlbowser
 @jandreslopez
 @adhornsby
 @ccicero
 @mkoo
 @cjconroy
 @atrox10
 @jebrad
 @ewommack
 @marecaguthrie
 @mvzhuang
 @AJLinn
 @acdoll
 @bryansmclean
 @crcarter00
 @lin-fred
 @sharpphyl
 @SerinaBrady
 @aklompma
 @ebraker
 @droberts49
 @Jegelewicz
 @kderieg322079
 @wellerjes
 @jrpletch
 @Nicole-Ridgwell-NMMNHS
 @zmsch
 @byuherpetology
 @kmkocot
 @gradyjt
 @cefilipek

**Comment by AJLinn** [comment]
i can't speak for anyone else but I've gone in and dealt with the autogenerated errors for my collection and they keep showing up. I don't know how to fix them, so my vote is for deleting them. They're not preventing anyone from finding the UAM:EH objects in question so they appear to be unhelpful in our case.

**Comment by dustymc** [comment]
>they keep showing up.

That will not be true in next release.

>not preventing anyone from finding the UAM:EH objects in question 

That may be true now (doubt it), it will become more noticeable soon; I'm adding the foundations I need to build spatial tools so things like "Alaska, according to shape" (or "stuff inside this[ file I found somewhere](https://github.com/ArctosDB/arctos/issues/3213)") become possible.

See also https://github.com/ArctosDB/arctos/issues/4289, I hope that we as a Community can come together and just decide to reject bad data rather than continuing to invest huge amounts of work into things that just can't make sense. The data that trigger annotations would not be able to survive that process.

**Comment by DerekSikes** [comment]
On the review annotations page where is says "Review Comment" could this be changed to read 

Review Comment [add text and save review to change Annotation to 'Reviewed']

**Comment by sharpphyl** [comment]
@dustymc 

> they keep showing up.

> That will not be true in next release.

Has that release happened yet?
