### ISSUE TITLE
Code Table Request - Getty AAT taxonomy source additions

### ISSUE THREAD

**Issue by krgomez** [ArctosDB/arctos#3531]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

Code Table Documentation is https://handbook.arctosdb.org/how_to/How-to-Use-Code-Tables.html

Goal
Describe what you're trying to accomplish.
There are two additional Getty AAT terms that we need added to the Getty taxonomy source: Laser Print and Diazotype (Copy)

Table
Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table you are requesting changes to here.
Getty AAT taxonomy source

Value
Proposed new value
Object --> Visual and Verbal Communication --> Information Form --> Information Form (Object) --> Information Artifact --> Reprographic Copy --> Diazotype (Copy)
Object --> Visual and Verbal Communication --> Visual Work --> Visual Work (works) --> Print --> Digital Print --> Laser Print

Definition
Clear, complete, non-collection-type-specific definition of the new value.
Diazotype (Copy) -- Prints produced using a duplicating process in which images are produced by the effect of light on diazonium-sensitized materials, most often architectural or other technical drawings. -- http://vocab.getty.edu/page/aat/300028509
Laser Print -- Prints on photographic materials achieved by controlled exposure to white, red, green, or blue light and processed chemically. Distinguished from 'electrophotographic laser prints' that create images via a beam of light to etch onto a photoconductive drum from which images are transferred by electrostatic copying to paper. -- http://vocab.getty.edu/page/aat/300312248

Priority
Please choose a priority-label to the right.
Normal

**Comment by Jegelewicz** [comment]
Added
