### ISSUE TITLE
Code Table Request - add EBRPD: East Bay Regional Park District

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#3533]
I'm working on bulkloading some Golden Eagle blood samples that have both a USFWS band number and an East Bay Regional Park identifier number. The collector is Douglas A. Bell who works for the EBRPD and banded these birds as part of a study for the park district.

Request is to add "EBRPD: East Bay Regional Park District" to the other_ID_num_type code table.

Definition: "Special district operating in Alameda and Contra Costa counties, California, within the East Bay of the San Francisco Bay Area. It maintains and operates a system of regional parks which is the largest urban regional park district in the United States. https://www.ebparks.org/"

I need this added so that I can proceed with bulkloading, thus the 'High Priority."

**Comment by Jegelewicz** [comment]
I'm OK with this.

**Comment by ccicero** [comment]
Thanks @Jegelewicz 

If there are no objections, I will go ahead and add it.

**Comment by dustymc** [comment]
Does this do something that ``original identifier``=``EBRPD: East Bay Regional Park District: {the identifier}`` cannot? If not, recommend that approach. If so, no objections to adding.

**Comment by ccicero** [comment]
@dustymc YES, it will make it easier to find all EBRPD records.

**Comment by dustymc** [comment]
>easier to find all EBRPD records

Why would I want to do that?

I added https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html#specific-values-considerations, hopefully it's more or less what we've been talking about, PLEASE edit that (or post here and I'll edit, or whatever) if you've got some consideration that's not included. I'm not trying to suggest anything in particular, I'd just like to have some consistent logic behind what's in the code table (so we don't end up spending ANOTHER 4 months fixing it some time in the future!).

**Comment by ccicero** [comment]
I like the idea of distinguishing whether you are likely to get more data through correspondence, or not.

If YES - or if you can create a base URL - then it justifies having an entry as an other ID type.
If NO - then use a generic identifier.

Dusty, is that what you're getting at, as the main criteria in the decision-making?

**Comment by dustymc** [comment]
Yes, mostly. I just don't want to unnecessarily create garbage (nor to refuse something that's somehow useful), and I'm poking around looking for some reasonable interpretation of "unnecessary." I don't think there are going to be any hard-and-fast rules (https://github.com/ArctosDB/arctos/issues/3547 seems to have just turned into good reasons to create not-so-great identifiers!) but I am hoping we can have some sorta-consistent guidelines come out of this.

**Comment by ccicero** [comment]
@Jegelewicz Where is the Google doc we were working on, for other_ID_num_type values? I can't find it - can we add it to this [folder](https://drive.google.com/drive/folders/1Qfs6PF8c7jN75WpgTY1ZyqGNUyY41KdN?usp=sharing)?

It would be worth looking at that list with Dusty's criteria in mind, to see how well we can apply that.

Meanwhile, I'm going to go ahead and add EBRPD: East Bay Regional Park District to the code table unless I hear a serious objection.

**Comment by Jegelewicz** [comment]
@ccicero it is already there, but Dusty changed its name - https://docs.google.com/spreadsheets/d/1Op6g0LTBDBTwFKCNXnFHGugM8Nlbi9z9HFlyeYVgoMc/edit?usp=sharing

**Comment by Jegelewicz** [comment]
FWIW, if we are going to do anything - we should probably make sure that it includes everything CURRENTLY in the code table.

**Comment by ccicero** [comment]
@Jegelewicz thanks! That's confusing under the new name.

After discussion with Doug Bell at EBRPD, and per Dusty's response, I've decided to use 'other identifier' for the EBRPD number because that's not the primary number associated with the samples (USFWS band number is primary). The EBRPD was used for eagles trapped or hand captured in the nest specifically for attaching satellite transmitters, but not all birds received one whereas they all got a USFWS band.
