### ISSUE TITLE
Delete collecting event from catalog record

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#3537]
If I hit "Delete this Specmen/Event" from this catalog record, will it just remove it from being connected to this catalog record OR (gasp) will it really delete the event from those other 85 records? 
I clicked the wrong option when I did a fork-edit of this record and now I have this unaccepted event associated with this object record.
https://arctos.database.museum/guid/UAM:EH:UA2004-010-0012

<img width="1380" alt="Screen Shot 2021-03-23 at 1 07 08 PM" src="https://user-images.githubusercontent.com/17605945/112218879-22074d00-8bd9-11eb-9af7-1ce1d36f0e23.png">

**Comment by dustymc** [comment]
remove it from being connected

**Comment by Jegelewicz** [comment]
HMMMM - maybe the option should just say "Remove event from this catalog record"

**Comment by AJLinn** [comment]
I like that idea since I'm always afraid I'm going to change 85 things with the accidental click!
