### ISSUE TITLE
Code Table Request - new taxonomy source - Modern Herpetology

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3544]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

Code Table Documentation is https://handbook.arctosdb.org/how_to/How-to-Use-Code-Tables.html

**Goal**
Need a new source to manage herp taxonomy differently - see #3538

**Context**
See #3538 we don't want to disrupt those using older taxonomic structure

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxonomy_source

**Value**
Modern Herpetology

**Definition**
Modifications to the herp classification found in Arctos to reflect recent taxonomic changes.

**Collection type**
If the code table includes a "Collection" column. Ex: Mamm, Herp, ES

**Attribute data type**
"Attributes" may apply to catalog records, parts, localities, and collecting events. You must specify a datatype (free-text, categorical, or number+units) if this request involves attributes.

**Attribute value**
For categorical attributes, code table controlling value

**Attribute units**
For number+units attributes, code table controlling units

**Part tissue flag**
For new parts, is the part a tissue?

**Other ID BaseURL**
For OtherIDs, provide the following *or* explain why the unresolvable ID type is necessary:
1. "Base URL" with which to prepend entered values, and
2. A functional example URL, which should consist of the base URL provided in (1) plus a relevant value.

**ID_References**
If the request involves https://arctos.database.museum/info/ctDocumentation.cfm?table=ctid_references, the changes must be coordinated with the DBA team for notifications to function.

**Priority**
Please choose a priority-label to the right.

**Comment by Jegelewicz** [comment]
@atrox10 @jtgiermakowski @mvzhuang this might end up being useful to you. Please comment on the name of the source

**Comment by dustymc** [comment]
Can we do (much) better with the definition? Why would I want to use, or avoid using, this? Where do the data come from - is this following some publication, is it some user's view of the world, ???? Are my contributions welcome, and what editor should I use if so? What's the scope - can my birds be "Herps"? Does "modern" mean "not extinct" or "as we currently understand things" or something else? Etc., etc. etc.

https://github.com/ArctosDB/arctos/issues/3019 - existing definitions are horrible, there's nothing in there that might lead a new collection to decisions they'll be happy with. Let's do better going forward!

**Comment by byuherpetology** [comment]
> Can we do (much) better with the definition? Why would I want to use, or avoid using, this? Where do the data come from - is this following some publication, is it some user's view of the world, ???? Are my contributions welcome, and what editor should I use if so? What's the scope - can my birds be "Herps"? Does "modern" mean "not extinct" or "as we currently understand things" or something else? Etc., etc. etc.
> 
> #3019 - existing definitions are horrible, there's nothing in there that might lead a new collection to decisions they'll be happy with. Let's do better going forward!

How about "Reptile classification based on Reptile Database.  Data can be updated manually by users."

Reptile database does a good job of staying up to date on taxonomy, so although this source wont have the entire reptile classification, they should match up pretty well.  Maybe if I have time I could eventually get everything in there.  IS this more descriptive and inviting for other users?

**Comment by Jegelewicz** [comment]
If you want to use Reptile Database - it might not be too difficult to grab it and upload it to Arctos. If there will be differences between this and Reptile Database, we need to be clear that they are not equal in the definition (what you have may be good enough). Also, if you want to just use Reptile Dtabase - #3311 should be getting another boost....

**Comment by dustymc** [comment]
>can be updated manually by users

That would be all the information I'd need - to run the other way!

Can we put this on hold for a few more days? I'm working on extracting hierarchical data (or close to it) from existing classifications now, if that can be brought to a bearable place these data could be managed hierarchically, which I think would be a big step in the right direction for The Community (along with making your job much easier and your data much more predictable). This scenario would mean the definition should include something like 'managed with the hierarchical editor, single-record edits are discouraged and subject to replacement without notification.' 

Alternatively:

1. Reptile Database doesn't seem to be sharing with GlobalNames - if they are willing, https://github.com/ArctosDB/arctos/issues/3311 would mean you don't have to manage anything. Or,
2. They seem to have some sort of download, you could just manually pull from them, transmogrify into Arctos format, and periodically upload/replace the classification in Arctos. You would need to manage some stuff under this, but just by converting the download to a different format. (A quick glance at their download suggests this won't be very practical, but I didn't look very hard.)

**Comment by byuherpetology** [comment]
Can we put this on hold for a few more days? I'm working on extracting hierarchical data (or close to it) from existing classifications now, if that can be brought to a bearable place these data could be managed hierarchically, which I think would be a big step in the right direction for The Community (along with making your job much easier and your data much more predictable). This scenario would mean the definition should include something like 'managed with the hierarchical editor, single-record edits are discouraged and subject to replacement without notification.'

I am all for this.  I like that definition, it makes the classification changes objective but still controls for the user introduced error that we have right now with the Arctos classification - and it would certainly make things easier on my end.

**Comment by byuherpetology** [comment]
I think I have a handle on extracting data from Arctos, editing it in the hierarchical editor, and entering new names in taxonomy.  I think the last step is just to create a new source so that I can upload the data there.  We can call it Reptile Database, Alternative Reptile taxonomy, reptiles take 2 - I don't really care what the name is if there are suggestions that will make it more accessible.  For the definition, I like Dusty's suggestion: Reptile taxonomy based on Reptile Database.  Data is managed in the hierarchical editor, single record edits are discouraged and subject to replacement without notification.  Would it be wise to say it is managed by me, so someone could contact me with suggested changes?

**Comment by dustymc** [comment]
>don't really care 

Well that makes two of us!

"Reptile Database" is concise and somewhat informative, if nobody has any real opinions...

My questions from above remain:

* ## Why would I want to use, or avoid using, this?

Is this intended to be "current" taxonomy or closer to your shelf labels? I think that's the most critical bit that I'm not yet understanding.

* ## Where do the data come from

"...based loosely on The Reptile Database" - yes?

* ## Are my contributions welcome

Depends on the above, I think?

* ## what editor 

"... data are managed in the Arctos Hierarchical Taxonomy Editor. Contact @byuherpetology [and link to your agent] to contribute."

??

* ## What's the scope

Can/should I use this for my dinosaurs? (I lean towards "no" as a general approach - taxonomy is best managed at about the scales at which it's created - and something like "...focus is on extant reptiles..." or similar in the definition, if that fits with whats in your collection?)

**Comment by byuherpetology** [comment]
> * ## Why would I want to use, or avoid using, this?

This is intended to be "current" classification based on the changes proposed in the literature as opposed to the Arctos classification which in some cases tends more toward a traditional classification and avoids big changes that would be difficult to implement in a large collection.
> 
> * ## Where do the data come from

The data come from the current literature, but Reptile Database does a good job of keeping up to date with the literature, and so if that adds a level of objectivity, that is fine.

> * ## Are my contributions welcome

After looking at the Arctos classification I hesitate to open it up for everyone to edit, but I am happy to have suggestions emailed for consideration.  

> * ## what editor
> 
> "... data are managed in the Arctos Hierarchical Taxonomy Editor. Contact @byuherpetology [and link to your agent] to contribute."
> 
yes!

> * ## What's the scope
> 
This is definitely extant non avian reptiles (In the paraphyletic sense covered by herpetology).  While birds technically fall within reptiles, collections have separate reptile and bird collections, so I don't think this is an issue.  The real issue is that right now it will only cover a portion of reptiles (the clade which I am interested in), but over time I will try to get all of reptiles in there.

**Comment by dustymc** [comment]
How's this:

Current Reptile Classification:  Extant non-avian reptile taxonomy, intended to reflect current literature. Managed in the Arctos Hierarchical Taxonomy Editor by [Alison Whiting](https://arctos.database.museum/agent/21320583) (@byuherpetology on GitHub); please preemptively coordinate any changes or additions, changes made in other editors are subject to replacement without notice.

**Comment by byuherpetology** [comment]
Perfect!

Alison Whiting
Adjunct faculty and Curator of Herpetology
Brigham Young University

**Comment by dustymc** [comment]
Done

https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxonomy_source#current_reptile_classification
