### ISSUE TITLE
Code Table Request - add KWS: Kenya Wildlife Service as other identifier

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3547]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

Code Table Documentation is https://handbook.arctosdb.org/how_to/How-to-Use-Code-Tables.html

**Goal**
Add KWS: Kenya Wildlife Service as an other ID so that specimens collected from Kenya by MSB:Para can be permitted to remain in the United States.

**Context**
The Kenyans are threatening to require destruction of all Kenyan specimens in MSB:Para unless this identifier is added to the records.

**Value**
KWS: Kenya Wildlife Service

**Definition**
Official catalog number of the Kenya Wildlife Service, required for all exported material.

**Priority**
Urgent

**Comment by Jegelewicz** [comment]
Do it.

**Comment by dustymc** [comment]
That's a huge org, they must issue hundreds of kinds of IDs, surely the type and definition can be made a little more specific?

**Comment by msbparasites** [comment]
That is true, but right now that is all I have, and using KWS Kenya Wildlife Service directly identifies who they are and they can find it. It is not ideal, but it is also a problem with permitting. They are not interested in logic, nor oversight etc. I could ask for a better definition, but likely won't get an answer.

**Comment by dustymc** [comment]
Fair enough. Can some of that be incorporated into the definition, so someone who does have a better identifier won't be tempted to use this one?

**Comment by campmlc** [comment]
Add to definition:
 https://en.m.wikipedia.org/wiki/Kenya_Wildlife_Service
And

https://web.archive.org/web/20111031171857/http://www.kws.go.ke/

**Comment by campmlc** [comment]
Interesting - they have over 100,000 records on GBIF - but only as human observations/bird map occurrence data. So they are not publishing any preserved specimen or material sample data. MSB Para would be the only source on GBIF for their museum specimen data, making these discoverable for research - something to mention to them if they quibble over the publication of these records in Arctos or the archive of these specimens at MSB. @msbparasites 
https://www.gbif.org/publisher/5a1a662b-4ec7-4b73-95bd-6356ebde1ba8

**Comment by campmlc** [comment]
Added.
