### ISSUE TITLE
Change menu listing Taxonomy/Identification to Taxonomy

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3549]
Note that the tool for bulkloading Identifications is not in this group of tools - I think it would be better to just call this group "Taxonomy Things".

**Comment by dustymc** [comment]
OK - find a better place for the hierarchical editor while you're in there, please!

**Comment by sharpphyl** [comment]
Can't we leave off "things"?  We don't say "Parts-things" or "Identifiers/Relationships-things."  Just put the ones without a submenu (that begin with "Bulkload") at the beginning and the rest of them alphabetically below them.  But yes, the bulkload for identifications isn't  and shouldn't be in taxonomy.

You could always move the "Manage Classifications Hierarchically" to the Manage Data menu under a new submenu "Taxonomy."

**Comment by Jegelewicz** [comment]
> You could always move the "Manage Classifications Hierarchically" to the Manage Data menu under a new submenu "Taxonomy."

I like that placement - although maybe not with a submenu.

**Comment by Jegelewicz** [comment]
See changes made in test.

**Comment by Jegelewicz** [comment]
No one is complaining.
