### ISSUE TITLE
Identification history extension in DwC

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3553]
Is this something we already take advantage of?

https://github.com/tdwg/dwc-qa/issues/166#issuecomment-785047699

**Comment by dustymc** [comment]
Nope.

**Comment by Jegelewicz** [comment]
K - probably something we should consider when we start to look at mapping of Arctos to DwC as discussed in AWG last week. @mkoo

**Comment by dustymc** [comment]
I don't think it would be much trouble to map to an extension, but 

1. That doesn't fit our data particularly well, and
2. It's pretty limited - lots of "(concatenated and separated)" in there, and
3. I'm not sure anyone uses it; it's not clear that ANYONE, much less "us," would benefit in any way from this.

I think there's only so much that can be had from duct-taping semi-structured data to a fancy spreadsheet. If we really want to be cool, https://dwc.tdwg.org/rdf/ exists. If someone bigger than "we" wanted to be super-double-extra-cool, a DWC-as-JSON Standard would be a neat trick....

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/internal/issues/168
