### ISSUE TITLE
Code Table Request - Add Desmoinesian to Informal Chronostratigraphy

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#3554]
**Goal**
Add Desmoinesian to the informal chronostratigraphy locality attribute table

**Context**
Desmoinesian is a chronostratigraphic unit used in North America for a stage in the Middle Pennsylvanian, but is not in the international chronostratigraphic chart. See [https://en.wikipedia.org/wiki/Pennsylvanian_(geology)#Subdivisions](https://en.wikipedia.org/wiki/Pennsylvanian_(geology)#Subdivisions)

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctchronostrat_informal

**Value**
Desmoinesian (Stage/Age)

**Definition**
A North American subdivision of the Pennsylvanian. [Wikipedia](https://en.wikipedia.org/wiki/Pennsylvanian_(geology)#Subdivisions)

**Comment by dustymc** [comment]
done

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks!
