### ISSUE TITLE
transaction status code table cleanup/merge

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3559]
Followup to https://github.com/ArctosDB/arctos/issues/1444 - we have some code tables that could be merged or renamed. 

------------------------------------
* https://arctos.database.museum/info/ctDocumentation.cfm?table=ctloan_status
* https://arctos.database.museum/info/ctDocumentation.cfm?table=ctaccn_status
* https://arctos.database.museum/info/ctDocumentation.cfm?table=ctborrow_status

merge to cttransaction_status 

-------------------------------

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctnumeric_age_units - rename to cttime_units

----------------------------------

https://arctos.database.museum/info/ctDocumentation.cfm?table=cttissue_volume_units - rename to ctvolume_units

**Comment by acdoll** [comment]
this all sounds reasonable

**Comment by Jegelewicz** [comment]
Agree

**Comment by Jegelewicz** [comment]
Seems like something we could easily get done and close - adding to AWG Issues meeting

**Comment by Jegelewicz** [comment]
Keep in process or use more specific workflow steps with regard to transactions. Do we need transaction attributes? Could they be auto added to transactions? Need a bigger discussion about putting a workflow into Arctos. So this needs a broader discussion.

**Comment by dustymc** [comment]
TODO immediate: new migration proposal with 'processing' option

Maybe-eventually: additional 'tracking' module with more fine-scaled step

**Comment by Jegelewicz** [comment]
Working document for new definitions is here - https://docs.google.com/spreadsheets/d/1WyvrykSBTOQG2cmbGduXZaL83uh0QmudiaVbyVBmrBc/edit#gid=0

**Comment by Jegelewicz** [comment]
Maybe status should be a simple open, closed or denied and the rest are some kind of workflow associated with the transaction. Everyone's workflow will be different - can we accommodate that in some way?

**Comment by Jegelewicz** [comment]
@ArctosDB/arctos-code-table-administrators added definitions to borrow status that reflect loan status. But I think we do need to expand into this

> Maybe status should be a simple open, closed or denied and the rest are some kind of workflow associated with the transaction. Everyone's workflow will be different - can we accommodate that in some way?

because @ccicero talked about wanting to know if something shipped had been received. Perhaps a kind of transaction processing attribute similar to [processing history](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#processing_history)?

**Comment by AJLinn** [comment]
I would support that. I usually just enter all that information in the loan remarks field but would be happy to have more specific fields to enter that info in.

**Comment by dustymc** [comment]
> something shipped had been received

I don't think that can possibly be anything other than an attribute of the shipment (of which a transaction can have any number). 

Is there some situation in which the tracking number can't answer this question?

**Comment by Jegelewicz** [comment]
> attribute of the shipment

Yeah - that is where we thought it should go, but then the loan itself should reflect that staus. We definitely could use a short term task group to work through this. Maybe @ccicero will volunteer to get it going....

**Comment by dustymc** [comment]
Closing as abandoned, see https://github.com/ArctosDB/arctos/issues/5375.
