### ISSUE TITLE
Chronostratigraphy Hierarchy Broken???

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#3560]
**Describe the bug**
I thought when we set up Chronostratigraphy, we retained the hierarchy by using begin and end dates? See https://github.com/ArctosDB/arctos/issues/2498#issuecomment-656334931.

But I've just come across an instance where this isn't working. I had a researcher interested in our Jurassic sauropods, so I sent him search results, but have just realized those results are missing over half our specimens because it only came up with specimens where System/Period=Jurassic and did not include any subunits such as Kimmeridgian or Tithonian.

This seems like it is effecting all of chronostratigraphy, not just Jurassic units? For example, when I search just for any Mesozoic specimens in our collection, I only get one specimen in results, and only two results if I search for Cenozoic - both should have tens of thousands of results.

**To Reproduce**
1. Go to catalog search
2. Select NMMNH:Paleo
3. Enter search parameters:
locality attribute Era/Erathem
value Mesozoic
4. Enter search and get unexpected number of results

**Expected behavior**
My results should include that chronostratigraphy value + any subunits within the date range for that value.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 87.0

**Comment by dustymc** [comment]
The latest-greatest plan for getting more-than-assertion data is https://github.com/ArctosDB/arctos/issues/2244#issuecomment-657807083

I'm not sure I can accurately recreate the swarm of conversations, but I think we'd agreed on that....

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks for pulling out the latest set of comments on this. That issue got closed so I assumed that this was done? This is really, really important for accurate paleo searches and needs to be completed.

**Comment by dustymc** [comment]
I'm certainly not going to question it if https://github.com/ArctosDB/arctos/issues/2244 somehow gets a new priority label....

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Done.
