### ISSUE TITLE
Feature Request - Project enhancements 

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#3561]
1. Can we add individual records to a project (not entire accessions)? I'm creating a project to capture our partnership with the Denver Zoo and we have almost 200 in our legacy accessions.
2. When there is not an End Date, can we check a box so it will display "ongoing" on the detail page? Just having "1903-05-03 - " looks weird. 
3. @mkoo has added a photo to this [Mexican Wolf Project ](https://arctos.database.museum/project/1000071) and I think that adds a lot if you're using projects for fundraising or just general Arctos promotion. Can we add something like this as an option on the 'edit' page? I see that the markdown is not that complicated, but people would be more likely to do it if there is a field to pick/create media. I think it should display at the top to the left of the Project Title rather than down in the Description area.
And finally, 
4. If you are logged in and viewing another collections project, you can't see any of the 'Cataloged Records Used' or the 'Projects using contributed catalog records' (and probably other things). Similarly, if you are logged in and viewing one of your own projects, you can't see contributions from other collections. See https://arctos.database.museum/project/10002283 for example (256 objects when I'm logged in, 326 when I'm not; also 5 additional contributing projects). I assume this is a VPN issue, but is there some sort of work around? Maybe a summary table without active links??

**Comment by acdoll** [comment]
Oh, and: 5. in addition to 1., it would be great if we could add multiple accessions at once with a comma separated list (or something similar).

**Comment by dustymc** [comment]
>add individual records to a project

That would devalue all projects - "did something" (eg transactions) and "added for some arbitrary administrative reason" would be impossible to tell apart.

Data Loans are an easy way to get arbitrary things into transactions.

>check a box 

I'm not crazy about that, but "translating" NULL to some string would not be difficult. 

> field to pick/create media

<img width="262" alt="Screen Shot 2021-04-09 at 11 20 49 AM" src="https://user-images.githubusercontent.com/5720791/114224236-aa9a2300-9925-11eb-9e88-8c7df05033e6.png">

https://arctos.database.museum/project/10000404

>this is a VPN issue, but is there some sort of work around?

Yes, it's a VPN feature - those things don't exist for your user.

I suppose I could pull as a public user, but that would add a fair bit of complication and the links can't work for you - I usually have a private tab or two open for that sort of thing.

**Comment by dustymc** [comment]
I don't think accessions can be reliably distilled down to a list (certainly not while https://github.com/ArctosDB/arctos/issues/1598 exists), and there's no potential separator that couldn't also be in the identifier. There could be a/some project component bulkloader/bulkloaders.

**Comment by acdoll** [comment]
> devalue all projects

I thought that was probably why it's not already in there. I'll look into the data loan suggestion.

> "translating" NULL to some string would not be difficult

that would work for me

Re: Attach/Upload Media - what I'm asking for is in addition to that. A single image that is simply for display purposes - like a logo for the project. The Markdown option works for now

> I usually have a private tab or two open for that sort of thing.

Yeah, me too; but I'm not sure more novice users would know to do that.

> there's no potential separator that couldn't also be in the identifier. There could be a/some project component bulkloader/bulkloaders.

that makes sense- I was just trying to suggest something that might be easier to implement. A bulkloader would be great, but probably not high priority.

**Comment by dustymc** [comment]
If this is blocking https://github.com/ArctosDB/arctos/issues/3585 then the details need worked out. From my perspective:

* Markdown is very flexible and can work in most any UI, anything I do is not. "One image of a certain size displayed THERE" seems limiting enough to preclude use. We could add a how-to to documentation or a widget to the page or something, but this does not seem like something that justifies messing with the model.
* I need details for anything that needs to come across VPD borders - I have access only to filtered_flat for that purpose.

**Comment by dustymc** [comment]
I added a 'recipes' section to the editor.
