### ISSUE TITLE
record failed checks: relation "ctlat_long_error_units" does not exist

### ISSUE THREAD

**Issue by gradyjt** [ArctosDB/arctos#3563]
Hi all, I'm entering some individual records into Arctos today and I filled out the data entry form as I usually do, using the GeoLocate tool within the data entry form to record lat/long, and for the first time ever I'm getting the error message that's in the title of this issue. Not sure where that fits into the automated boxes filled out when you georeference within the data entry form so any directions are greatly appreciated! If you need more information about description of the bug (if it is one) or which parts of this you need to know to reproduce let me know and I'll get you that asap. Thank you!

Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by campmlc** [comment]
What units are you using?
Any relationship to https://github.com/ArctosDB/arctos/issues/1444?

**Comment by dustymc** [comment]
I wiggled the wires - please close this if that did it, or let me know how to find the problematic record if not.

**Comment by gradyjt** [comment]
It works now! Thank you!
