### ISSUE TITLE
Feature Request - accept wkt from GeoLocate

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3564]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
I can create a wkt in GeoLocate, but using it in Arctos requires copying the polygon information into a file, uploading as media and associating the media with the appropriate location.

**Describe what you're trying to accomplish** 
Make it easy to use wkt from GeoLocate

**Describe the solution you'd like**
Create the polygon in Geolocate and use it for the location I went to GeoLocate from

**Describe alternatives you've considered**
Just do the long process

**Additional context**
Talked about this in Arctos Office Hours

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by campmlc** [comment]
I vote this is high priority. Definitely agree and could use this
immediately.

**Comment by dustymc** [comment]
Followup question: can GBIF (and friends) make sense of WKT, and if so how should we be sharing it with them?

**Comment by Jegelewicz** [comment]
![image](https://user-images.githubusercontent.com/5725767/114631267-7d2cdc80-9c79-11eb-87ce-1ce77fdd4916.png)

https://www.gbif.org/data-quality-requirements-sampling-events#dcFootprintWKT

**Comment by sharpphyl** [comment]
This could be very helpful for our marine "near shore" locations.

**Comment by dustymc** [comment]
@dbloom the last column of  ipt_cache.occurrence is now footprintwkt - can you pass that along?

**Comment by dustymc** [comment]
The "polygon" that GL returns is very strange, so there's a fair bit of processing to unroll it and package it back up in a format that something other than GL can work with which made this a bit less straightforward than I'd hoped it would be. I hope that doesn't also mean it's fragile, and so far I haven't managed to break it, but there's plenty of opportunity - timely testing appreciated.

WKT generation is possible from edit locality and fork-edit in test.

https://handbook.arctosdb.org/documentation/geolocate.html needs updated or enhanced with a how-to - its possible to cause interesting errors by eg drawing a polygon and not doing whatever GL needs to produce an error radius, which DOES return coordinates but DOES NOT return error, which causes the update to fail.

**Comment by dustymc** [comment]
baseline:

```
arctosprod@arctos>> select count(distinct(wkt_media_id)) from locality;
 count 
-------
   617
```
