### ISSUE TITLE
Reporting Bad Data; also the link to 'report bad data' doesn't work

### ISSUE THREAD

**Issue by klevan** [ArctosDB/arctos#3566]
The identifiers for this record (http://arctos.database.museum/guid/MSB:Mamm:308115) should be:

NEON sample ID: CPER.20161026.120579.E
NEON sample ID: CPER.20161026.120579.F
NEON: National Ecological Observatory Network: NEON.MAM.D10.120579

The ear and fecal specimens have the corrected name, but the tag ID for the individual is still in error.

I tried using the report bad data link, but when i entered the above comment and clicked create annotation, nothing happened. 

Can you fix the record http://arctos.database.museum/guid/MSB:Mamm:308115 ? And also allow me to use the report bad data link? Thanks!

**Comment by klevan** [comment]
GUID http://arctos.database.museum/guid/MSB:Mamm:308970 has an error.
NEON sample ID: RMNP.20170816.R2484.H belongs to a different individual, "NEON.MAM.D10.R2484" - This sample should be associated with GUID MSB:Mamm:308981 

I am unable to submit this data update request through the report bad data link

**Comment by klevan** [comment]
GUID http://arctos.database.museum/guid/MSB:Mamm:312395 has an error.
NEON sample ID: TALL.20140723.R1029.H belongs to a different individual "NEON.MAM.D08.R1029" - This sample should be associated with GUID http://arctos.database.museum/guid/MSB:Mamm:312396

I am unable to submit this data update request through the report bad data link

**Comment by klevan** [comment]
GUID http://arctos.database.museum/guid/MSB:Mamm:315116 has an error.
NEON sample ID: DSNY.20161130.R0187.E belongs to a different individual "NEON.MAM.D03.R0187" - This sample should be associated with GUID http://arctos.database.museum/guid/MSB:Mamm:315075

I am unable to submit this data update request through the report bad data link
I am unable to submit this data update request through the report bad data link

**Comment by klevan** [comment]
GUID http://arctos.database.museum/guid/MSB:Mamm:314951 has an error.
NEON sample ID: JERC.20160803.R2875.E belongs to a different individual "NEON.MAM.D03.R2875" - This sample should be associated with GUID http://arctos.database.museum/guid/MSB:Mamm:315129

GUID http://arctos.database.museum/guid/MSB:Mamm:315129 has an error.
NEON sample ID: JERC.20160802.R2654.E belongs to a different individual "NEON.MAM.D03.R2654" - This sample should be associated with GUID http://arctos.database.museum/guid/MSB:Mamm:314896

I am unable to submit this data update request through the report bad data link

**Comment by klevan** [comment]
GUID http://arctos.database.museum/guid/MSB:Mamm:317367 has an error.
NEON sample ID: WOOD.20160927.O001E220160927.H belongs to a different individual "NEON.MAM.D09.O001E220160927" 
Please update NEON.MAM.D09.R2436 to NEON.MAM.D09.O001E220160927

I am unable to submit this data update request through the report bad data link

**Comment by dustymc** [comment]
The annotate form bug is fixed for next release, I'll try to get that out later this week.

@campmlc @jldunnum will need to deal with the data issues.

**Comment by jldunnum** [comment]
Yup we will fix

______________________________________________________________

Jonathan L. Dunnum Ph.D.
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by Jegelewicz** [comment]
@jldunnum can we close this?

**Comment by jldunnum** [comment]
Sure thanks

Sent from my iPhone

On Jul 28, 2021, at 4:28 PM, Teresa Mayfield-Meyer ***@***.***> wrote:

﻿
  [EXTERNAL]

@jldunnum<https://github.com/jldunnum> can we close this?
