### ISSUE TITLE
Code Table Request - Add Chibanian to Chronostratigraphy

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#3568]
**Goal**
Add Chibanian to Chronostratigraphy Stage/Age table

**Context**
All of the Phanerozoic stage/ages from [International Chronostratigraphic Chart](https://stratigraphy.org/ICSchart/ChronostratChart2020-03.pdf) are in the table, except this one.

**Table**
[https://arctos.database.museum/info/ctDocumentation.cfm?table=ctchronostrat_stage_age](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctchronostrat_stage_age)

**Value**
Chibanian

**Definition**
[Wikipedia](https://en.wikipedia.org/wiki/Chibanian)

**Comment by dustymc** [comment]
I think perhaps we're not being consistent?

>The Chibanian, widely known by its previous designation of Middle Pleistocene,

lead me to https://arctos.database.museum/info/ctDocumentation.cfm?table=ctchronostrat_stage_age#upper_pleistocene

which links to 

> Late Pleistocene is an unofficial age in the international geologic timescale in chronostratigraphy, also known as Upper Pleistocene 

Are we using multiple "systems" - eg should this be Middle Pleistocene to align with Late Pleistocene? Should Late Pleistocene not be here at all? I don't see it in your PDF.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Upper Pleistocene is in the table 
![image](https://user-images.githubusercontent.com/47402809/114752743-df3a2000-9d13-11eb-90f5-335b7f761bbe.png)

It is in italics, which "indicate informal units and placeholders for unnamed units". Technically Upper Pleistocene (and Cambrian Series 2, Cambrian Stages 2,3,4 and 10) should be in informal chronostratigraphy like we've done with Pre-Cambrian. On the other hand, unlike Pre-Cambrian, these are all placeholders for units that probably will eventually get formalized, so that might be an argument for just leaving them where they are for now.

Chibanian is formalized though so it should be added.

**Comment by dustymc** [comment]
>Upper Pleistocene is in the table

Well that doesn't count, splat-f doesn't find it!

>probably will eventually

I'm not so sure that's a compelling argument, but mañana....

Done.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks! I will add this now to the metadata I'm creating for #2244.
