### ISSUE TITLE
Code Table Request - Move Famennian from Series/Epoch to Stage/Age

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#3569]
**Goal**
Move Famennian from the Series/Epoch table to the Stage/Age table

**Context**
Famennian is a Stage/Age not a Series/Epoch. See [International Chronostratigraphic Chart](https://stratigraphy.org/ICSchart/ChronostratChart2020-03.pdf) and [Wikipedia](https://en.wikipedia.org/wiki/Famennian).

**Table**
[Series/Epoch](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctchronostrat_series_epoch)
[Stage/Age](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctchronostrat_stage_age)

**Value**
stay same

**Definition**
stay same

**Comment by dustymc** [comment]
Only used by you, so done.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks! I will adjust in the metadata for #2244.
