### ISSUE TITLE
Code Table Request - Need a Geology Specimen Part

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/arctos#3570]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

Code Table Documentation is https://handbook.arctosdb.org/how_to/How-to-Use-Code-Tables.html

**Goal**
Describe what you're trying to accomplish.
Need to add specimen part "thin section slide" and "core sample"
**Context**
Describe why this new value is necessary and existing values are not.

**Table**
Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table you are requesting changes to here.

**Value**
Proposed new value

**Definition**
Clear, complete, non-collection-type-specific definition of the new value.

**Collection type**
If the code table includes a "Collection" column. Ex: Mamm, Herp, ES

**Attribute data type**
"Attributes" may apply to catalog records, parts, localities, and collecting events. You must specify a datatype (free-text, categorical, or number+units) if this request involves attributes.

**Attribute value**
For categorical attributes, code table controlling value

**Attribute units**
For number+units attributes, code table controlling units

**Part tissue flag**
For new parts, is the part a tissue?

**Other ID BaseURL**
For OtherIDs, provide the following *or* explain why the unresolvable ID type is necessary:
1. "Base URL" with which to prepend entered values, and
2. A functional example URL, which should consist of the base URL provided in (1) plus a relevant value.

**ID_References**
If the request involves https://arctos.database.museum/info/ctDocumentation.cfm?table=ctid_references, the changes must be coordinated with the DBA team for notifications to function.

**Priority**
Please choose a priority-label to the right.

**Comment by dustymc** [comment]
Hard to say without definitions, but I think those are probably preservation and not parts.

**Comment by Jegelewicz** [comment]
> Need to add specimen part "thin section slide"

[slide, thin section](Rectidigitus glomerospinosus) is a part preservation for these items use part name = geosample, preservation = slide, thin section

> and "core sample"

I think this should be handled similarly, but we need a new preservation

core  - a cylindrical section obtained by drilling with a core drill. - [Wikipedia](https://en.wikipedia.org/wiki/Core_sample)

Then you would use part name = geosample, preservation = core

**Comment by Jegelewicz** [comment]
@Nicole-Ridgwell-NMMNHS your thoughts are appreciated too!

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Agree that core should be part preservation. I would encourage using rock or something more specific than geosample as part name.

**Comment by mbprondzinski** [comment]
All I know is that I have a thin section of a core sample of a meteorite (rock)

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Once core is added as a part preservation, then you can do part = meteorite with part preservation = thin section and part preservation = core

**Comment by mbprondzinski** [comment]
That will work...thanks!

**Comment by mbprondzinski** [comment]
One more thing:  the part "preservation" has its own identifier separate from the meteorite.  Can I add an identifier to a part preservation?

**Comment by Jegelewicz** [comment]
Nope - but for this I suggest that you have two parts - one is NOT preserved as a core and one is, correct?

**Comment by Jegelewicz** [comment]
Then you can add the part attribute Other ID to the part that IS a core.

**Comment by mbprondzinski** [comment]
Okay, thanks.  Just waiting for the core.

**Comment by mbprondzinski** [comment]
After much thought on this, I cannot justify calling a "core" preservation when a "tree core" is considered a part in the code table.  I would like to have it changed to a part so I can assign it the preservation attribute "slide, thin section" and be able to sleep on it.  We have the meteorite and we have a slice of the core sample.  To my way of thinking, the core is a part or piece of the meteorite.

**Comment by Jegelewicz** [comment]
> I cannot justify calling a "core" preservation when a "tree core" is considered a part in the code table.

Tree core should be changed, not the other way around.

> We have the meteorite and we have a slice of the core sample. To my way of thinking, the core is a part or piece of the meteorite.

Yes, so you have two parts for this record:

part name | part preservation 1 | part preservation 2
 --- | --- | --- 
meteorite | | 
meteorite (subsample) | core | slide, thin section

**Comment by mbprondzinski** [comment]
All right.  Where did you get "meteorite (subsample)?

**Comment by Jegelewicz** [comment]
create that part by subsampling the first

https://handbook.arctosdb.org/documentation/parts.html#sampled-from

I don't know if this can be done without creating a loan and I can't go research it right now, but in reality a loan should have been made at some point in order for the core to be taken and that was when the subsample (core) was created.

**Comment by mbprondzinski** [comment]
Aha, that did work!  I had no idea... however, it doesn't say (subsample) it just says "meteorite" with an indent.

**Comment by campmlc** [comment]
Yes, it would be useful if it said subsample.

**Comment by Jegelewicz** [comment]
> it doesn't say (subsample) it just says "meteorite" with an indent.

Create an issue!

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/2848
