### ISSUE TITLE
Unable to Encumber Part Attribute

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/arctos#3571]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
This is the error message I received:

![image](https://user-images.githubusercontent.com/43214224/114774761-233e1c80-9d36-11eb-8fe8-0357a09e2418.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by dustymc** [comment]
I'd need a lot more information to actually know what's going on, but first guess involves agent picks - https://handbook.arctosdb.org/documentation/understanding-errors.html#missing-expression

**Comment by mbprondzinski** [comment]
Okay, I'll check it out.
