### ISSUE TITLE
Code Table Request - Remove Missourian from Series/Epoch

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#3572]
**Goal**
Remove Missourian from the Series/Epoch chronostratigraphy table.

**Context**
Missourian is regional chronostratigraphy, it is not on the [International Chronostratigraphic Chart](https://stratigraphy.org/ICSchart/ChronostratChart2020-03.pdf). It has already been added to the informal chronostratigraphy table (#3241), but at the time I made that request, I did not realize it was in the series/epoch table.

**Table**
[https://arctos.database.museum/info/ctDocumentation.cfm?table=ctchronostrat_series_epoch](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctchronostrat_series_epoch)

**Comment by dustymc** [comment]
done

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks!
