### ISSUE TITLE
Numerical Sorting issues beyond catnum 

### ISSUE THREAD

**Issue by KyndallH** [ArctosDB/arctos#3574]
Beyond catnum, I run into this issue other places and it is frustrating. 

![Screen Shot 2021-01-14 at 11 26 45 AM](https://user-images.githubusercontent.com/16887896/104645357-69aead00-565b-11eb-838f-3be1ff1e9141.png)

_Originally posted by @KyndallH in https://github.com/ArctosDB/arctos/issues/3343#issuecomment-760456756_

**Comment by KyndallH** [comment]
![image](https://user-images.githubusercontent.com/16887896/115089739-71325c00-9ebf-11eb-8931-3b8fb729681a.png)

**Comment by dustymc** [comment]
Both screenshots from the same form? If not I need links.

**Comment by KyndallH** [comment]
Same spot -->  "See all collection objects in this container"
https://arctos.database.museum/allContainerLeafNodes.cfm?container_id=15863666

**Comment by dustymc** [comment]
I can't find any way to sort that like you want. 

I can add some columns, and the tablesorter handles them as numeric when all of the data can be cast to numeric.

<img width="466" alt="Screen Shot 2021-04-19 at 3 57 12 PM" src="https://user-images.githubusercontent.com/5720791/115313456-25362000-a128-11eb-92c6-eea77dd66b97.png">

Close enough?

**Comment by campmlc** [comment]
Anything that will allow numeric sorting is a help, thanks!
