### ISSUE TITLE
Code Table Request - remove tree core from part name

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3576]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

Code Table Documentation is https://handbook.arctosdb.org/how_to/How-to-Use-Code-Tables.html

**Goal**
See issue #3570 

**Context**
core is a part preservation. 

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#wood

**Value**
Suggest transitioning all "tree core" part names to wood, with preservation attribute = core

**Definition**
definitions already exist

**Collection type**
N/A

**Attribute data type**
N/A

**Attribute value**
N/A

**Attribute units**
N/A

**Part tissue flag**
N/A

**Other ID BaseURL**
N/A

**ID_References**
N/A

**Priority**
Please choose a priority-label to the right.

**Comment by dustymc** [comment]
```
select 
  guid_prefix,
  count(*) c from
specimen_part
inner join cataloged_item on specimen_part.derived_from_cat_item=cataloged_item.collection_object_id
inner join collection on cataloged_item.collection_id=collection.collection_id
where part_name='tree core'
group by guid_prefix;

 guid_prefix |  c   
-------------+------
 UAM:ES      | 1391
```

**Comment by Jegelewicz** [comment]
Patrick Druckenmiller is listed as data quality contact, but he's not on Github - sent email today.

**Comment by dustymc** [comment]
Shall we accept the silence as enthusiastic approval and proceed, @ArctosDB/arctos-working-group-officers ?

**Comment by Jegelewicz** [comment]
Yes

**Comment by dustymc** [comment]
```
create table temp_wood as select * from specimen_part where part_name='tree core';

insert into specimen_part_attribute (
  collection_object_id,
  attribute_type,
  attribute_value,
  attribute_remark
) (
  select
    collection_object_id,
    'preservation',
    'core',
    'former part: tree core'
  from
    temp_wood
);

update specimen_part set part_name='wood' where part_name='tree core';

delete from ctspecimen_part_name where part_name='tree core';

  ```
