### ISSUE TITLE
clone records by barcodes clones catnum = errors for dupes

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#3577]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

The clone records by barcode tool now creates duplicate catalog numbers in the bulkloader records that are made. This did not used to occur. They immediately throw an error that there are cat num duplicates and I have to go in and delete them to load the records.

Can this be fixed to return to the former functionality. Clones should have null cat numbers so they don't throw these errors (and of course real, unique catalog numbers are made for each when they load).

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.
high

**Comment by dustymc** [comment]
rebuilt function
