### ISSUE TITLE
Add Barcode and Part Remarks to Flatten Part Locations

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3578]
Potential solutions to problem with extracting data from JSON in Part Detail. Add Barcode and Part Remarks (or any other part field) to Flatten Part Remarks view.  e.g. https://arctos.database.museum/loanFreezerLocn.cfm

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/3067#issuecomment-821323823 and/or

<img width="295" alt="Screen Shot 2021-04-21 at 5 36 37 PM" src="https://user-images.githubusercontent.com/5720791/115638937-403f9600-a2c8-11eb-9ef6-4ff7f183bf9b.png">

... are probably more appropriate than messing with a specialized form.

**Comment by KyndallH** [comment]
Parts table/download doesn't have tissue location.

I think what we are getting at is a merging of "flattening parts" and "parts table/download". :D

**Comment by dustymc** [comment]
Parts table/download is just a table - it's easy enough to add anything that can be stuffed into a cell to it.

"flattening parts" has a bunch of (old) complicated code behind it, and isn't so easy to mess with. I'd be happy to get rid of it, if that's an option!

**Comment by dustymc** [comment]
I flattened some random stuff out for the table/download.

<img width="699" alt="Screen Shot 2021-04-22 at 9 38 30 AM" src="https://user-images.githubusercontent.com/5720791/115752025-90f9d200-a34e-11eb-9869-380e097fcf4e.png">

<img width="742" alt="Screen Shot 2021-04-22 at 9 43 20 AM" src="https://user-images.githubusercontent.com/5720791/115752702-3745d780-a34f-11eb-8533-2b7dd3cc5ca9.png">

**Comment by campmlc** [comment]
This could work? I've honestly never used parts/ table download - didn't
know it was there. I always go through object tracking - flattening parts
to get a part location download, which then has to be heavily massaged -
large time commitment - to put it into a format I can hand off to students
to say - "go find these samples".  So the parts/table download, with part
location, might be feasible, but I haven't used it enough to know. One
thing I would not need from a "find these samples" point of view is the
date info and other columns. Can we have the option of adding/removing data
fields from this form?
If so, then " flattening parts" has a bunch of (old) complicated code
behind it, and isn't so easy to mess with. I'd be happy to get rid of it,
if that's an option!" could be possible - but only if we make the
parts/table download link as a replacement in the object tracking Find
Container form.

**Comment by dustymc** [comment]
>option of adding/removing data fields from this form?

Probably, but that's no longer simple changes. AFAIK everyone who uses that is here, just tell me what you want to see.

> only if we make the
parts/table download link as a replacement in the object tracking Find
Container form.

You can't, that's not an option after all - one starts from catalog records and pulls containers when available, the other starts from containers and pulls catalog records when they exist, there's never any guarantee that those will be paired.

>which then has to be heavily massaged - large time commitment 

The code behind the flatten form exists for that purpose - whatever you're doing is apparently not the same as whatever Brandy was doing when we built that form way back in the dark ages, if you'll let me know some details I might be able to do something about it.

**Comment by KyndallH** [comment]
Could we separate out Container 1 even further to Container 1 Label and Container 1 Barcode? That way it is easier to delete columns we don't need when printing out a location map! 

Could we have the same part filter options? Like only filter out everything that isn't "muscle"?

**Comment by dustymc** [comment]
>separate out Container 1 even further 

Yea, no problem - just 1 or all of them? And 5 just seemed like a nice number - more or less isn't difficult (but it's a static number).

>filter out everything that isn't "muscle"?

I think that's back to "no longer simple" territory but I'll stare at it a bit more.

**Comment by dustymc** [comment]
Figured it out - you can filter now.

**Comment by KyndallH** [comment]
Awesome!
I'd like all labels and barcodes separated out.

**Comment by dustymc** [comment]
<img width="875" alt="Screen Shot 2021-04-22 at 3 13 06 PM" src="https://user-images.githubusercontent.com/5720791/115791462-4774ab80-a37d-11eb-8cdd-c4f914367298.png">

**Comment by dustymc** [comment]
Bueno?

**Comment by KyndallH** [comment]
Can I unclose? I just went to use it and need a smidge more. We were hoping to use this in place of the flatten parts BUT I'm still missing information. Perhaps we need more than 5 barcode spaces. 

I have no idea what freezer these samples are in. 

<img width="2251" alt="Screen Shot 2021-04-30 at 11 21 13 AM" src="https://user-images.githubusercontent.com/16887896/116744171-6f2fc900-a9a6-11eb-961e-0a44c016bc73.png">

Flatten parts look like this:
<img width="2359" alt="Screen Shot 2021-04-30 at 11 21 26 AM" src="https://user-images.githubusercontent.com/16887896/116744198-7656d700-a9a6-11eb-9b9a-5656b7053068.png">

The include/exclude parts is excellent - thanks!

The

**Comment by dustymc** [comment]
>Can I unclose?

Absolutely.

>smidge more

https://github.com/ArctosDB/arctos/issues/3578#issuecomment-825053065 - gimme a number, or I can add the "part stack string", or whatever.

**Comment by dustymc** [comment]
>count down instead of up?

If you mean (1) is the ultimate parent and (2) is a child and etc., I think the short answer is "no" - the flattened partial hierarchy would end 7 (or whatever number we use) steps in, which might be nowhere near the part for especially deep hierarchies (if I could figure out how to write that SQL, and I'm not sure I could in postgres).

If you mean (or could live with) mess with the order/names of the columns, sure no problem.

**Comment by campmlc** [comment]
Mess with order/names of the columns, please - so that the highest rank of the hierachy shows up to the left (ideally labeled as BC1 etc but whatever) and the lowest rank, however far down, is at the far right. That puts in in order of how we need to find an object, eg. Freezer: freezer rack: freezer box: box position (left right, high to low in hierarchy).

**Comment by dustymc** [comment]
<img width="1081" alt="Screen Shot 2021-05-06 at 7 09 25 AM" src="https://user-images.githubusercontent.com/5720791/117312641-0b8c1c80-ae3a-11eb-80b8-04af6d927780.png">

**Comment by campmlc** [comment]
That works! Just curious why we can't number them in the same order, with
LNSFRZR5 as BC1 instead of BC7? It would make it possible to use an Excel
macro to consolidate the fields we actually need to pull samples.
Also, I don't know about anyone else, but I don't need any of the date
fields in this form. I can eliminate them with a macro, but it would be
easier if they were optional to include in the display or not (add/remove
data fields).

**Comment by dustymc** [comment]
I can label whatever however, I'm just concerned that "1" implies "the first" and not "the 7th (for now) up from the root" and that that'll be overly confusing for anyone who's not involved in this conversation.

>consolidate the fields we actually need to pull samples.

I can add the whole stack back in if that's helpful.

>on't need .. fields

Easy to change that if ya'll can work it out. I don't think customization makes much sense for a form that gets accessed less than 50 times per year, but it's not technically implausible either.

**Comment by campmlc** [comment]
Now that I can use this instead of Flatten Part Locations, I will be
accessing this form multiple times weekly to pull samples for loan. So
customization would be useful! And so far for both Kyndall and I, the stack
order goes from top down, not "up from the root", in order to determine
freezer or container hierarchy, so the first container is left to right
starting with number 1. My guess is she and I represent a large percentage
of users. :)

**Comment by dustymc** [comment]
>instead of 

See above, they're not the same thing (but maybe close enough for loans).

>tack order goes from top down, 

This is just another case of flattening. "The stack" is a hierarchy of indeterminate depth, if you really want the ultimate parent container to be (1) then we need a way to deal with the possibility of depth=34356, and that's no longer a minor (or perhaps realistic) change. If we need to do more than shuffle the labels on a static number of columns, we probably also need a new issue.

>large percentage of users

Nope, most usage is someone from MVZ (who doesn't seem to have a github account and may eventually create one just to complain about the changed form - we really need to somehow do better with getting Arctos users over here).

**Comment by campmlc** [comment]
Just to be clear, I have never used this form in the past - but will do so
very frequently from now on because it gives me better tools than Flatten
Part Locations, which requires significantly more data manipulation to
extract a part location to give to a student.
The numbering issue is not that important, just confusing - really, from a
user interface perspective, starting with number 7 or 10 makes it much
harder to manipulate than starting with BC1 as the top down for the
hierarchy. I don't see why that affects underlying data structure - it's
just UI!

**Comment by campmlc** [comment]
See updated previous comment

**Comment by campmlc** [comment]
The parts/table download is still not functional for me to use to locate samples for loan. It is missing key parts of the tree hierarchy needed to find samples. See the difference between the two views below. To find a cryovial, I need to know minimally the freezer, the rack position, the rack barcode, the box position, the box barcode/label, the cryovial position, and the cryovial barcode and label. This is 6 or 7 levels deep, with the cryovial barcode/label (currently displayed first in parts/table download) being at the bottom of the hierarchy.  I need the order of the display reversed, so that the freezer (or room) shows up first, and I need all the levels of the hierarchy included.
Is it possible to reconcile these different tools so that we can get the same information? 

@KyndallH @DerekSikes @dustymc 
Tree View:

![image](https://user-images.githubusercontent.com/14808196/118532723-8390f700-b704-11eb-824d-d034863a0fc0.png)

Flatten Part Location View:
![image](https://user-images.githubusercontent.com/14808196/118532869-ab805a80-b704-11eb-8bb9-06706cb6a1d0.png)


Parts Table Download View: 
![image](https://user-images.githubusercontent.com/14808196/118532458-3c0a6b00-b704-11eb-9c0f-1de3aacbb379.png)

**Comment by dustymc** [comment]
> need all the levels of the hierarchy included.

Not practical.

**Comment by campmlc** [comment]
Then we are back to my original request: Add Barcode and Part Remarks (or any other part field) to Flatten Part Remarks view. e.g. https://arctos.database.museum/loanFreezerLocn.cfm
But see https://github.com/ArctosDB/arctos/issues/3578#issuecomment-824521962

**Comment by dustymc** [comment]
There is no view in which I can stuff a potentially-infinite number of hierarchy steps into a finite number of table columns.

**Comment by campmlc** [comment]
I don't understand. We do not have infinite hierarchy steps. Cryovials in freezers are probably one of the deeper levels.  The parts table download takes me up from cryovial to freezer rack. I need two more levels to go to rack position and Freezer.

**Comment by campmlc** [comment]
Again, why not allow users to specify the number of levels? Same as add remove data fields?

**Comment by campmlc** [comment]
I would gladly get rid of began date end date accessioned date to add the columns I need. @DerekSikes may want this info but with fewer hierarchy columns.  We can customize the search results download. Why not this form?

**Comment by dustymc** [comment]
> We do not have infinite hierarchy steps. 

Nothing prevents it; it's not an assumption that I can safely make. ("Infinite" isn't likely, but "hundreds" isn't unexpected.)

>two more levels

That is something I can handle, I think. (I'm going to run out of CPU at some point, I suspect ~a dozen "steps" is workable with the resources I have, but I don't really have a way to test that.)

Your example looks like 7 levels above the part would get it to the freezer - presumably you know where your rooms are and that's sufficient?

>Same as add remove data fields?

That's plausible (probably), but it's something that would need fleshed out and built; what I've done isn't readily going to get there.

> get rid of began date 

That's irrelevant (for now), I'm just looking at the flattening.

1. I can make some minor adjustments to this form, or
2. We can plan a different kind of form.

**Comment by campmlc** [comment]
For now, let's just make some minor adjustments to this form, and see how
it works. Eventually a different kind of form that allows add/remove would
be great, but let's see if we can make this one work for the few folks
using it now.  And any possibility of changing the display order from
highest to lowest, e.g swap left and right columns so that the higher value
appears first (just UI - no structural change) would help greatly so that I
don't have to reshuffle all the columns after download. Thanks!

**Comment by campmlc** [comment]
And yes, 7 levels - to the freezer - works for me, thank you!

**Comment by dustymc** [comment]
@campmlc I think your recent suggestions were all in test and went to production last night.

<img width="1391" alt="Screen Shot 2021-05-18 at 10 56 08 AM" src="https://user-images.githubusercontent.com/5720791/118700611-b5b75d00-b7c7-11eb-8a80-a4d3d9de5180.png">

**Comment by campmlc** [comment]
This is fantastic! I'm going to go see how this works with part
preservation attributes - THANKS!

**Comment by dustymc** [comment]
Bueno de nuevo?

**Comment by campmlc** [comment]
Almost bueno - can we get the csv download to put the columns in the same
order as they are displayed, with the higher BC and label column values
first?

**Comment by dustymc** [comment]
shuffled
