### ISSUE TITLE
Report needed for number of loans by yr with lat long

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3580]
@dustymc I need help generating a report for a grant of all MSB loans (all divisions) from 2014-2020 that list @campmlc as in-house contact (these should correspond to DGR issued loans)., and I need to be able to map the source coordinates of the loan requestor. Somehow you did this a year ago for our CSBR submission, but I can't find the email thread. We need to make a graph based on the following table data fields:
Collection	Loan Number	Latitude	Longitude	Number of Samples
Help please?

**Comment by dustymc** [comment]
<img width="361" alt="Screen Shot 2021-04-23 at 7 20 00 AM" src="https://user-images.githubusercontent.com/5720791/115885007-58b4cb00-a404-11eb-9ddb-e8b9fc858982.png">

<img width="365" alt="Screen Shot 2021-04-23 at 7 20 25 AM" src="https://user-images.githubusercontent.com/5720791/115885187-8ac62d00-a404-11eb-8033-1e62be204df2.png">

<img width="210" alt="Screen Shot 2021-04-23 at 7 20 40 AM" src="https://user-images.githubusercontent.com/5720791/115885195-8f8ae100-a404-11eb-974d-3270c7a01e26.png">

takes you to...

<img width="645" alt="Screen Shot 2021-04-23 at 7 21 05 AM" src="https://user-images.githubusercontent.com/5720791/115885209-94e82b80-a404-11eb-904f-ec46b11f1721.png">


extract the 'tabfile' variable from the URL - it's also a URL, the file contains coordinates.

[arctos_330.txt.zip](https://github.com/ArctosDB/arctos/files/6365938/arctos_330.txt.zip)

The loan CSV contains the count, it should be easy (I hope, I don't use Excel!) to patch those together.

Or I just added shipped_to_coordinates to the shipment object in the CSV download, if that's easier to access.

**Comment by campmlc** [comment]
Neat, but I don't see the "Map" options on my interface? Also, can we
change the language to "Map Loans" as well as "Map Accessions" - I
certainly would not know to look under accessions. And I'm not sure what
this means:  extract the 'tabfile' variable from the URL - it's also a URL,
the file contains coordinates.

**Comment by dustymc** [comment]
>I don't see the "Map" options on my interface?

Screenshot and URL please.

>can we change the language

Elaborate please - I don't know what you're referring to.

**Comment by campmlc** [comment]
Apologies, I read that too fast - your screenshot highlights Map Accessions, but I see the Map Loans option now on your post. But when I go to Find Transactions, this is what I see. Where is the Mapping tool? Or it is just that I really need coffee?
![Screenshot 2021-04-23 12 22 02](https://user-images.githubusercontent.com/14808196/115914033-9d555c00-a42e-11eb-944a-4c4cc89e7e57.png)

**Comment by dustymc** [comment]
>coffee

Can't ever hurt!

Find something - that's the search form, the tools are in the results.

**Comment by campmlc** [comment]
OK, I see it, but I don't see the coordinates in the csv. Will that take
24hrs to show up?
Could we do the same search with Loan Statistics? Right now,  I have to do
a separate download for every collection in that form. But if we could make
it possible to select an agent/role and multiple collections, and add the
coordinates to that form, I would have what I need.

**Comment by dustymc** [comment]
Which CSV? I provided two paths above. If it's the download from the transaction form, it's part of shipments. If it's from BM, it's a column.

What's "Loan Statistics" - URL?

**Comment by campmlc** [comment]
Loan Statistics under Reports. Can't get the url from my phone.

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/2657 needs completed before this continues, if this needs to continue.

**Comment by Jegelewicz** [comment]
#2657 is done, @campmlc please add a priority label.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/7410
