### ISSUE TITLE
Barcode search needed

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3581]
I'm trying to use Create Container Series to create barcodes to be used for freezer boxes.
When I upload to the tool, I get an error that some of these barcodes exist.
This is a series of 10,000 barcodes ordered last spring. 
These should not have been used or created yet - but I can't figure out the problem without being able to search on the list of 10,000 to find which one(s) supposedly exist.  The tool times out.
I need:
1) immediate help to know which of the following barcodes has already been created
2) the SQL or a tool to allow a long list of barcodes to be run through Arctos with the output ideally being the status of the barcode, e.g. which collection has claimed it, what is the container type, or whether it has not yet been created yet.
Priority: High

**Comment by acdoll** [comment]
see #3148?

**Comment by dustymc** [comment]
Or I can run the SQL, but I need data.

And see https://handbook.arctosdb.org/documentation/container.html#guidelines-for-barcode-containing-labels

**Comment by campmlc** [comment]
The barcode series was given in earlier post. Here is the csv.
And yes, in an ideal world, as soon as a shipment of barcodes arrives at my
door I would immediately create them as labels in Arctos, before someone
(me, a student) grabs them and creates one on the fly during a year of
covid. So errors happen. Some means of detecting what went wrong would be
helpful.

**Comment by dustymc** [comment]
I'm not sure what earlier post you're referring to, and I still don't see anything in this one.

The guideline is to create them **before** they're ordered, which prevents this situation and also uncovers any interpretation problems between the intended series and the actual barcodes.

**Comment by campmlc** [comment]
Very strange. Here it is again:
[March 2020 Box Barcode Series Create Container.zip](https://github.com/ArctosDB/arctos/files/6393757/March.2020.Box.Barcode.Series.Create.Container.zip)

**Comment by campmlc** [comment]
I reserve the barcodes in advance, but I don't create them until I have them in my hands.

**Comment by dustymc** [comment]
>don't create them until I have them in my hands

The guidelines are all from actual problems. I recommend following them.

```
arctosprod@arctos>> select container.barcode from temp_cache.temp_dlm_uptbl inner join container on container.barcode=temp_cache.temp_dlm_uptbl.barcode;
 barcode  
----------
 DGR22501
 DGR22502
 DGR22503
 DGR22504
 DGR22505
 DGR22506
 DGR22507
 DGR22508
 DGR22509
 DGR22510
 DGR22511
 DGR22512
 DGR22513
 DGR22514
 DGR22515
 DGR22516
 DGR22517
 DGR22518
 DGR22519
 DGR22520
 DGR27826
(21 rows)

```

**Comment by campmlc** [comment]
OK, got it and see the problem. Thanks, and I will follow the documentation.
