### ISSUE TITLE
Project agent dates

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3584]
Also, would it be possible to make the dates participating more formal? It would be great if the sorting could be by "current participants" and "past participants".

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/arctos/issues/2190#issuecomment-515693578_

**Comment by dustymc** [comment]
Current structure:

```

arctosprod@arctos>> \d project_agent
                                           Table "public.project_agent"
        Column         |          Type          | Collation | Nullable |                 Default                  
-----------------------+------------------------+-----------+----------+------------------------------------------
 project_id            | bigint                 |           | not null | 
 project_agent_role    | character varying(25)  |           | not null | 
 project_agent_remarks | character varying(255) |           |          | 
 agent_position        | bigint                 |           | not null | 
 project_agent_id      | bigint                 |           | not null | nextval('sq_project_agent_id'::regclass)
 agent_id              | bigint                 |           | not null | 
 award_number          | character varying(255) |           |          | 

```

Suggest: add start_date and stop_date. 

* Names need discussion - "join" and "complete"????
* Datatype needs discussion - DATE somehow feels most right but ISO8601 is more flexible, allows "sometime in 1987" precision.

This would also be nice/critical for https://github.com/ArctosDB/arctos/issues/2570: would provide a mechanism to track who **and when**.

Blocking https://github.com/ArctosDB/arctos/issues/3468

**Comment by campmlc** [comment]
- Names need discussion - "join" and "complete"???? - How about "Join
   Date" and "End date"
   - Datatype needs discussion - DATE somehow feels most right but ISO8601
   is more flexible, allows "sometime in 1987" precision. - ISO works for me.

**Comment by Jegelewicz** [comment]
> Names need discussion - "join" and "complete"????

 join and leave

> Datatype needs discussion - DATE somehow feels most right but ISO8601 is more flexible, allows "sometime in 1987" precision.

ISO8601 because we need the flexibility

**Comment by dustymc** [comment]
AWG says go.
