### ISSUE TITLE
Project Revision Summary

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3585]
This is an attempt to organize, order, and summarize project issues. 

Discuss details in relevant issues, not here. 

Please **do** add any relevant project Issues here.

https://github.com/ArctosDB/arctos/issues/3584 - add dates to agent-in-role. No blockers.

https://github.com/ArctosDB/arctos/issues/2570 - add (automagically) creator, editor. Blocked by dates in agent-in-role.

https://github.com/ArctosDB/arctos/issues/3583 - formalize minimum description. No blockers.

https://github.com/ArctosDB/arctos/issues/3398 - funding node. No blockers.

https://github.com/ArctosDB/arctos/issues/2615 - do we need to somehow separate projects and publications (or ????) in the UI? No blockers, blocks 3468

https://github.com/ArctosDB/arctos/issues/3468 - rebuild UI. Blocked by all of the above.

https://github.com/ArctosDB/arctos/issues/3466 - new links to project/publication; blocked by new UI

TENTATIVE: Would be useful to resolve these before we rebuild, but maybe less-critical

https://github.com/ArctosDB/arctos/issues/3561 - Project enhancements, including adding images easily to project (and not in body of description), adding option to having 'ongoing' instaed of a weird end date, the logged in block to see any other collecrtions records, 

https://github.com/ArctosDB/arctos/issues/1220 - add borrows

**Comment by campmlc** [comment]
Work on Summer 2021 with intern feedback. @mkoo

**Comment by dustymc** [comment]
>intern feedback

https://github.com/ArctosDB/arctos/issues/2570#issuecomment-608037040 (which really needs #3584) seem noncontinuous and might be worth addressing beforehand; it's not ideal to do those in UI that will probably be replaced, but perhaps worthwhile anyway (or maybe we can just avoid UI, or something).

**Comment by dustymc** [comment]
AWG says "go" on bits-n-pieces, then consider the UI. Closing.
