### ISSUE TITLE
Need a part name "capsule, seed"

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/arctos#3589]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

Code Table Documentation is https://handbook.arctosdb.org/how_to/How-to-Use-Code-Tables.html

**Goal**  Need a part name "capsule, seed" for fossil seed capsule with seeds.  Capsule is broken in half with seeds showing in carpels.
Describe what you're trying to accomplish.

**Context**
Describe why this new value is necessary and existing values are not.
"ovary" doesn't include ES
**Table**
Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table you are requesting changes to here.   https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name

**Value**
Proposed new value 
"capsule, seed"

**Definition**
Clear, complete, non-collection-type-specific definition of the new value.

A type of simple, dry, though rarely fleshy dehiscent fruit produced by many species of angiosperms. Wikipedia equivalent to plant ovary Ontobee
**Collection type**
If the code table includes a "Collection" column. Ex: Mamm, Herp, 
Herb, ES

**Attribute data type**
"Attributes" may apply to catalog records, parts, localities, and collecting events. You must specify a datatype (free-text, categorical, or number+units) if this request involves attributes.

**Part tissue flag**
For new parts, is the part a tissue?
No

**Priority**
Please choose a priority-label to the right.

**Comment by Jegelewicz** [comment]
> Whenever I get to the bottom of this list:  "Please choose a priority label at the right"  I just throw up my hands BECAUSE...drum roll, please: there isn't one!

@mkoo can we figure this out? Apparently some people do not have the ability to access the labels and this means they cannot complete the instructions.
