### ISSUE TITLE
Cannot choose a priority label

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3590]
> Whenever I get to the bottom of this list:  "Please choose a priority label at the right"  I just throw up my hands BECAUSE...drum roll, please: there isn't one!

@mkoo can we figure this out? Apparently some people do not have the ability to access the labels and this means they cannot complete the instructions.

**Comment by dustymc** [comment]
Maybe we should just drop that. Anyone who uses Arctos in any capacity can file an Issue, most of them won't have access to set labels. Whatever process we use to bring Issues out of "Needs Discussion" could also set priority.

**Comment by campmlc** [comment]
Just have them write the Priority in the text of the issue.

**Comment by ewommack** [comment]
It's too bad there isn't a robot that come through and pull the labels out of the text.

**Comment by campmlc** [comment]
Yes, true, but if we do it consistently, then we could search issues for
the words high and critical?

**Comment by Jegelewicz** [comment]
> It's too bad there isn't a robot that come through and pull the labels out of the text.

If we had someone with the Github knowledge, we could build one....

**Comment by ewommack** [comment]
So we should be making more friends...maybe we can bribe them with museum stickers?

**Comment by campmlc** [comment]
So I'm still confused as to what has to happen to tag someone in Github.
They need to be added to the repository? And who does that? And where does
this fit in in the workflow when we get new people? And does being able to
be tagged relate to being able to add a non-existent priority label?
Questions, questions . . .

**Comment by Jegelewicz** [comment]
Right now the only people who can invite to the GitHub repo is @mkoo and this is failing way too much. I don't know the difference between the ability to add labels or be tagged, but this needs to get spread around more if we re going to use GitHub for everything. On the agenda for tomorrow...
