### ISSUE TITLE
Data Entry Attributes: table?

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3591]
This needs to be applied in data entry as well.
![image](https://user-images.githubusercontent.com/5725767/116594900-f36b4900-a8df-11eb-9d22-474b852ca98e.png)

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/arctos/issues/3113#issuecomment-829460362_

**Comment by dustymc** [comment]
Can we replace all of the complicated crazy code around collection-type-specific attributes in data entry with the standard table?

<img width="595" alt="Screen Shot 2021-04-29 at 10 46 58 AM" src="https://user-images.githubusercontent.com/5720791/116595509-417c4e80-a8d8-11eb-9a36-daa04d63bfcb.png">

**Comment by ewommack** [comment]
Ah not for birds please! I like our collection-type-specific attributes for teaching students about which attributes are most important.
I suppose we could get use to the other format, but I really like having sex, weight, and molt right there. Yes collect those, important!

**Comment by campmlc** [comment]
I imagine mammals feels the same about the data entry page. If we need to
add date and  determiner for these, we can use add extras?

**Comment by jldunnum** [comment]
Yes the specificity also increases speed and ease of entry.

______________________________________________________________

Jonathan L. Dunnum Ph.D.
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________
