### ISSUE TITLE
Feature Request - Locality attributes: age assignment order

### ISSUE THREAD

**Issue by aklompma** [ArctosDB/arctos#3592]
The locality attributes for geological age assignments are ordered alphabetically, but it would become more intuitive and in line with the geological time scale if they were ordered this way:
1) Era/Erathem
2) System/Period
3) Series/Epoch
4) Stage/Age

Here is an example how it is now:
https://arctos.database.museum/guid/ALMNH:Paleo:13593

Would it be possible to rearrange them automatically for each record?
@dustymc 

Other locality attributes should not be placed in between any of these age assignments. 

Priority: high

**Comment by dustymc** [comment]
Thanks, I see the problem (typo), fixed for next release.
