### ISSUE TITLE
Code Table Request - CT scan

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3593]
EDIT: this is now a code table request

**Goal**
Distinguish CT scan Media from everything else

**Context**
Users want an easy search shortcut

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctmedia_type

**Value**
CT scan

**Definition**
Media representing a computed tomography scan, including derivatives.

----------------------------------------

Original

@jldunnum wants to find only records that have CT scans. To do that we need a way to reliably identify CT scans.

My first thought is a new value in https://arctos.database.museum/info/ctDocumentation.cfm?table=ctmedia_type, but that would require the CT attached directly to the catalog record. We may not want that (https://handbook.arctosdb.org/documentation/media.html#binary-object-creation-guidelines), and we certainly can't require/control it - eg a record could be attached to a JPG (eg collage of views), that could be attached to some web viewer, and that could be attached to the actual raw CT data.

Option Two would be to make the JPG (or whatever sort of web-viewable derivative might be attached to the catalog record) media_type=CT scan. I don't think that's entirely WRONG (as long as it's documented) and I don't think it would break anything, but it may not be entirely obvious either.

Option Three is something new in https://arctos.database.museum/info/ctDocumentation.cfm?table=ctmedia_label, which is about the same functionality as (2) but labels are not required, so probably easier to mess up.

Better options? How can we best designate catalog records as having CT data?

**Comment by campmlc** [comment]
a new identifier or attribute?
CT scan ID = ?url?
Attribute = CT scan yes/no - but this attributes are notoriously bad at
tracking such data, given our track record with using them to find examined
for parasites
Add a "media" part with part name = CT scan?

**Comment by campmlc** [comment]
Why is a link to an external CT media resource via IDs a denormalization?

**Comment by Jegelewicz** [comment]
> Why is a link to an external CT media resource via IDs a denormalization?

That is what media IS - a link to an external resource, right?

> Option Two would be to make the JPG (or whatever sort of web-viewable derivative might be attached to the catalog record) media_type=CT scan. I don't think that's entirely WRONG (as long as it's documented) and I don't think it would break anything, but it may not be entirely obvious either.

The media type is JPG so I don't think we should mess with that. This is a little bit like "tissueness". Maybe we need something like "media derived from" which in this case would be CT scan, but might also be "X-ray"?

**Comment by dustymc** [comment]
>That is what media IS - a link to an external resource, right?

Yes, but with the capacity for more complexity than otherIDs - which is required here.

>media type is JPG

No. "JPG" is https://arctos.database.museum/info/ctDocumentation.cfm?table=ctmime_type, media_type is something we introduced to get at things like "HTML, but it [plays video|displays text|shows an image]".

I could be convinced that X-ray isn't "image." (And bat calls may not be 'audio' and etc.). The idea was to let users/humans know what to expect, I think that's more or less in line with what I'm proposing.

**Comment by Jegelewicz** [comment]
Gotcha - so I think creating a new term in media type = CT scan makes sense, but will it work for what @jldunnum needs?

**Comment by dustymc** [comment]
If CT scans, or whatever derivative of them is linked to cataloged records, use a distinct and predictable value of  https://arctos.database.museum/info/ctDocumentation.cfm?table=ctmedia_type then I can use that to build a 'has CT?" checkbox on specimensearch.

I'll let @jldunnum decide if that's usable/defensible/fits in the workflow, but it sounds workable to me.

**Comment by jldunnum** [comment]
Thanks for thinking through this Theresa and Dusty! Seems reasonable. That said, I am of course not totally sure what is best. Just want ease of findability and one more way to filter things down to make it easier for folks looking for these. We know this is going to be an area of rapid growth and queries by the community as we grow our holdings in this area (anticipate a couple thousand in the next year and MVZ has a bunch already too.

We are getting tons of requests for the CT data on specimens we have uploaded to Morphosource so once we get them findable and linked directly through Arctos and TACC I expect we will be dealing with lots of usage.

I think the bottom line is that as new tech comes along that requires some minimum (of something) to be useable (like omics requiring tissue) its nice to be able to parse those out a bit quicker. CT data is a current and up and coming one but there will be something else tomorrow....

______________________________________________________________

Jonathan L. Dunnum Ph.D.
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by campmlc** [comment]
Yes, I agree with @jldunnum. We have the same need for "has whole genome"?, which could be accessed through data archived in multiple different external repositories, and have multiple different OtherIDs as a result.  Is there a solution what would work for both?

**Comment by campmlc** [comment]
@ccicero @KyndallH

**Comment by Jegelewicz** [comment]
This is also "has tissue". See #1875

> as new tech comes along that requires some minimum (of something) to be useable (like omics requiring tissue) its nice to be able to parse those out a bit quicker. CT data is a current and up and coming one but there will be something else tomorrow....

The question is are we going to end up with a huge laundry list of "requires" or do we do this some other way?

**Comment by dustymc** [comment]
I updated the title and initial request. 

I'm not crazy about "CT scan" - better terminology?

>not totally sure what is best.

I'm not either, but I think what I've proposed is reversible - I don't think there's anywhere to lose data in this, we can do something else later if a better idea comes along.

>parse those out a bit quicker

In general, it's our parsing that annoys me. What we think qualifies as "tissue" and what some researcher thinks is "tissue" aren't always the same thing (and I think the loan/publication data support that) so by asserting "tissue" we're misleading some users. This has a bit of that - "find all images" (assuming something that's going to be linked to catalog records and carrying "CT scan" media type will look like "image" to users) will be more complicated than necessary if this goes forward. Does making access easier for some users justify making it harder for others? Maybe sometimes - I'd guess that this is more useful for more users than what we're doing with "tissues," at least. I certainly don't have any immediate suggestions, but we should keep looking for a better approach. Maybe a short questionnaire for the folks who use these "summary" data would eventually be revealing?

**Comment by Jegelewicz** [comment]
I support the new code table term.

**Comment by campmlc** [comment]
I support also. I understand this has some urgency.

**Comment by jldunnum** [comment]
I support as well. Thanks

______________________________________________________________

Jonathan L. Dunnum Ph.D.
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by dustymc** [comment]
done

**Comment by ebraker** [comment]
Some thumbnail options:
![ct_media](https://user-images.githubusercontent.com/11336485/129279698-cfc84011-3a02-4f5b-be3f-a465224a8490.png)

![ct_media2](https://user-images.githubusercontent.com/11336485/129279711-ea754d35-d1be-4b80-b646-492566a1a8a8.png)

![ct_media3](https://user-images.githubusercontent.com/11336485/129279720-4751da89-a6ff-4fed-8f15-8bc128722135.png)

![3D_volume](https://user-images.githubusercontent.com/11336485/129279734-10bbeeab-edce-46db-8413-604616c380cd.png)

**Comment by campmlc** [comment]
These are great! I like the last one best.
