### ISSUE TITLE
Search for invalid taxa used as current identifications

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#3594]
We used to have a field (the very last one in the Curatorial pane) that allowed me to find all the current identifications that were using an invalid taxon name so I could update them.  I used it regularly even though I had to do it in batches or it would timeout.

It appears that field has been removed and replaced with this search.  

<img width="839" alt="invalid taxa" src="https://user-images.githubusercontent.com/15368365/116787165-dc536500-aa5f-11eb-98a8-c5329c654fbf.png">

The problem is that this searches for current and previous identifications.  I only want the current identifications that are invalid taxa.  Even if "current ID only" is checked under Identification, I get everything which means thousands of records come up that I've already added the valid ID to.  

Is there are way to limit the search to current IDs?  Or use (really easy) SQL to get these?  I doubt you want to give us back the old search field but it worked great.

I'm labeling it normal priority but for me it's high priority and driving me to dark despair.

**Comment by sharpphyl** [comment]
@Jegelewicz 

Since I opened this issue, I'll recommend that I go ahead and close it.  I used the Name Checker today and all the issues I identified appear to have been addressed.  Do we need to also discuss it in committee or can I go ahead and close it?

**Comment by Jegelewicz** [comment]
If it is working for you, feel free to close.

**Comment by dustymc** [comment]
@sharpphyl I removed the box because it was still wired into the single preference in collection, which I also removed since the tiered system seems to be working (and I'm wondering how we got this far without it!).

I'm not sure how to get this, which isn't in FLAT (how I hope to get at other "compiled taxonomy" questions) and could come from any of several Sources. (I can dig deeper if necessary.) I can help check Sources one by one, if that does what you need? Here's a potential start - it's pretty slow, I'm not sure you'll be able to run it in WriteSQL, I'm happy to adjust/run/whatever. This is

* used in accepted DMNS:Inv IDs
* taxon_status= invalid according to WoRMS (via Arctos)


```
select 
  taxon_name.scientific_name
from
  flat
  inner join identification on identification.collection_object_id=flat.collection_object_id and accepted_id_fg=1
  inner join identification_taxonomy on identification.identification_id=identification_taxonomy.identification_id
  inner join taxon_name on identification_taxonomy.taxon_name_id=taxon_name.taxon_name_id
  inner join taxon_term on taxon_name.taxon_name_id=taxon_term.taxon_name_id
where
  flat.guid_prefix='DMNS:Inv' and
  taxon_term.source='WoRMS (via Arctos)' and
  taxon_term.term_type='taxon_status' and
  taxon_term.term='invalid'
group by 
  taxon_name.scientific_name
order by 
   taxon_name.scientific_name
  ;

         scientific_name         
---------------------------------
 Acanthochitona zebra
 Akramovskiella andronakii
 Astriclypeus manni
 Bathymodiolus childressi
 Bursa granularis
 Caecum bahiahondaense
 Caecum dalli
 Caecum eburneum
 Caecum occidentale
 Caecum pygmaeum
 Calliostoma laugieri spongiarum
 Calliostoma selectum
 Calliostoma toshiharui
 Callyspongia vaginalis
 Campeloma crassula
 Canarium fusiforme
 Canarium maculatum
 Cantharidus purpureus
 Cardium indicum
 Cipangopaludina japonica
 Cochlostyla macrostoma
 Colobocentrotus atratus
 Corallium elatius
 Coriophora hungerfordi
 Cribrarula cumingii astaryi
 Cyclonaias asperata
 Dendropoma gregaria
 Diplodon expansus
 Distorsio decipiens
 Fartulum occidentale
 Fusinus michaelrogersi
 Fusitriton murrayi
 Isseliella mirabilis
 Linatella cingulatum
 Lobatus costatus
 Lottia insessa
 Lymnaea exilis
 Mactra discors
 Megalobulimus valenciennesi
 Mitra punctostriata
 Nassarius nitidus
 Nassarius perpinguis
 Neritina gagates
 Neritina turrita
 Nipponotrophon stuarti
 Notoacmea helmsi
 Ocinebrina squamulifera
 Penion fairfieldae
 Physella cubensis
 Pseudolatirus kuroseanus
 Rissoa rosea
 Rissoina expansa
 Rissoina sagraiana
 Sassia parkinsonia
 Septaria borbonica
 Solariella tryphenensis
 Spisula aequilateralis
 Stagnicola exilis
 Stilapex tokii
 Strongylocentrotus franciscanus
 Strophocheilus lutescens
 Sulcoretusa paziana
 Syrinx aruanus
 Tectus conus
 Thapsia thomensis
 Theodoxus luteofasciatus
 Tritia obsoleta
 Turricaspia variabilis
 Umbonium zelandicum
 Viviparus subpurpureus
 Voluta polypleura retemirabilis
 Volutopsion castaneum
 Zafrona idalina
 Zafrona lindae

```

**Comment by sharpphyl** [comment]
@Jegelewicz 

> If it is working for you, feel free to close.

Oops!  I meant to put that on the Name Checker #2253.  No, I want to keep this open.  

Too many issues open at one time...

@dustymc  I'll work with this SQL and your list.  Thanks.  A few days ago, there were almost no invalid taxon names in use, so I'll have to work through this.  The first few I checked have been modified in WoRMS during 2021 so we may not have caught up with the changes.

**Comment by sharpphyl** [comment]
@Jegelewicz Could you add Dusty's SQL to our cheat sheet?  Thanks!

**Comment by Jegelewicz** [comment]
Done.
