### ISSUE TITLE
Code Table Request - Heparin as blood preservative

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3596]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

Code Table Documentation is https://handbook.arctosdb.org/how_to/How-to-Use-Code-Tables.html

**Goal**
Add new preservation value to preservation code table

**Context**
Describe why this new value is necessary and existing values are not. Doesn't exist.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=CTPART_PRESERVATION

**Value**
heparin

**Definition**
Heparin is a blood anticoagulant used as a preservative during blood collection and processing procedures, usually in the form of lithium or sodium salts of heparin.  Test tubes, vacutainers, and capillary tubes that use the lithium salt of heparin (lithium heparin) as an anticoagulant are usually marked with green stickers and green tops. Sodium heparin is collected into royal-blue-topped (and dark green-topped) vacutainers.

**Collection type**
Mamm

**Attribute data type**
"Attributes" may apply to catalog records, parts, localities, and collecting events. You must specify a datatype (free-text, categorical, or number+units) if this request involves attributes.
Part Preservation as an attribute, categorical

**Part tissue flag**
For new parts, is the part a tissue? YES

**Priority**
High

**Comment by Jegelewicz** [comment]
Add it.

**Comment by campmlc** [comment]
Done, closing.

**Comment by campmlc** [comment]
I've found some new information on our vials that indicates whether the salt used was sodium or lithium. So I would like to add new preservation types to incorporate these as follows:
Value: 
heparin, lithium salt
heparin, sodium salt

**Comment by dustymc** [comment]
Can one do anything that the other can't? Having three values is certainly "correct" but if they're not (much) functionally different then maybe only having the generic provides sufficient functionality without adding too much clutter.

**Comment by campmlc** [comment]
Right now, we have some vials that say just heparin, and some that say lithium or sodium heparin. Currently the lithium or sodium are in part remarks. That works for me, as long as we can be consistent in tracking it in part remarks if it ever becomes an issue for fit for purpose. But that is asking a lot!
