### ISSUE TITLE
Feature Request - Specimen Count By Institution

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#3597]
@dusty Can you add a date & time stamp to the [Specimen Count By Institution](https://arctos.database.museum/info/SpecimenCountByInstitution.cfm) report? And when you're in there, can you also change the display to 'Record Count By Institution'? Thanks

**Comment by dustymc** [comment]
>date & time stamp

The data are current/live - not sure I understand what you're asking.

>Record Count By Institution

Done

**Comment by acdoll** [comment]
I'd like the date to show in that purple box so a simple screenshot can indicate when that query was ran.

**Comment by acdoll** [comment]
Thanks!
