### ISSUE TITLE
tube barcode upload

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#3598]
@dustymc Could you please load another batch of cryovial barcodes into freezer box positions as you did in #3181 ?
I think I've got everything set up just like last time; let me know if I'm missing something. 
[BF1_cryovials-freezer_box_positions.zip](https://github.com/ArctosDB/arctos/files/6418418/BF1_cryovials-freezer_box_positions.zip)

**Comment by dustymc** [comment]
The records with NULL ...id have problems.

**Comment by acdoll** [comment]
Thanks - I think I see what's happened for most of these. I'll clean it up and get back to you.

**Comment by acdoll** [comment]
I think I've got that all fixed. Most of the problems were that I did not create the box positions. I also forgot to upload some of the boxes. Then there were just a handful of bad tube barcodes. Could you give it another go, please? 
[bird_dmns_pos.zip](https://github.com/ArctosDB/arctos/files/6429995/bird_dmns_pos.zip)

**Comment by dustymc** [comment]
Should be there.

**Comment by acdoll** [comment]
Excellent! Thank you so much!
