### ISSUE TITLE
Media slow to load in public view (or doesn't load at all...)

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#3600]
I shared a saved search with a researcher: https://arctos.database.museum/saved/Loan202107EH
Normally I also share instructions on how to show the media thumbnail in the search results by adding the media column, saving and refreshing.
From the public interface (not logged in) I'm getting either a super slow load rate or a total hang, depending on what browser I use. Is this a local problem or something bigger? There are only 47 items in this saved search and while some items do have several images per record, it doesn't seem like it should create a log-jam like I'm experiencing.

I've tried multiple browsers and computers with varying amounts of RAM, processor speed, etc.
I'm using Brave as my main browser these days (love it) and have had zero issues thus far. The hang has occurred using Safari, Firefox, and Brave. It has also occurred using an old iMac (2012 with 8 GB RAM and slow processor) and my new MBP (2019, 2.3 GHz 8-core i9 with 16 GB ram). It loads pretty much instantly (~1 sec) without media selected (public or logged in). 

Here's the process I've followed:
1. Log in, enter https://arctos.database.museum/saved/Loan202107EH
2. See media (my login always has media showing at search results).
3. Log out
4. Load saved search: https://arctos.database.museum/saved/Loan202107EH
5. See 47 records
6. Click Tools / Add column / Media / save & refresh
7. Hang...
<img width="1166" alt="Screen Shot 2021-05-04 at 1 22 06 PM" src="https://user-images.githubusercontent.com/17605945/117071568-bd610700-acdb-11eb-85d4-5071de637ec7.png">
8. Pop up window - Page Unresponsive
<img width="1154" alt="Screen Shot 2021-05-04 at 1 22 48 PM" src="https://user-images.githubusercontent.com/17605945/117071647-d4075e00-acdb-11eb-967d-d7d932e9a5d1.png">
9. Click wait & hang...
10. Continue to wait... indefinitely
11. Become frustrated and close tab. Realize there's no way out because now that i've added the media column my browser cookies are telling it to keep using the media column.
12. Try a different browser (Firefox), which then spends lots of time loading the images.
<img width="1119" alt="Screen Shot 2021-05-04 at 1 27 13 PM" src="https://user-images.githubusercontent.com/17605945/117072151-83443500-acdc-11eb-98e9-3337ee8014b4.png">

Not sure what to tell my users who might not know how to get out of the loop or have the fast internet or newish computer or multiple browsers, etc.
Recommend not showing media at search results? That is a major sad face for cultural collection user who are very visually-oriented.
Recommending show fewer results at one time (I have 100 rows showing... maybe only do 25?) BEFORE adding the media column? (Still loads images slowly)
Why does it load faster for an operator vs a public interface? Something to do with the cache?

Sorry for the long question/many questions. Just hoping to make my Indigenous and remote community users understand how to use a system they might not be familiar with.
Thanks for any tips for figuring out this problema.

Priority: Medium (inconvenient mostly)

**Comment by dustymc** [comment]
There might be something interesting in your javascript console, but my first guess is your network. Here's what I get:

<img width="1341" alt="Screen Shot 2021-05-04 at 2 49 57 PM" src="https://user-images.githubusercontent.com/5720791/117074440-2a7a9980-ace8-11eb-9805-cd646adee31a.png">

The page loads for me (with JSON/text in the Media column) in 1.63 seconds, then it takes about 12 more seconds to grab the thumbs and patch them in (which is faster than I scroll, so it more or less looks like the thumbs have always been there). 

Several of your thumbs are pretty huge, which isn't helping anything.

<img width="1166" alt="Screen Shot 2021-05-04 at 2 52 53 PM" src="https://user-images.githubusercontent.com/5720791/117074653-7a596080-ace8-11eb-922b-56d3a5e487b3.png">

https://github.com/ArctosDB/arctos/issues/2863 would be handy about now....

**Comment by dustymc** [comment]
I think this is also related to https://github.com/ArctosDB/arctos/issues/3155#issuecomment-704552664 - the API call that gets thumbs is slow (on a VPN with certain browsers, if I hold my tongue JUST right, sometimes). IIIF would help with that too - I currently have to check thumbs to avoid other flavors of evil, if I had real media tools I'd KNOW I had good thumbs and could just serve them.

Arctos is also getting hammered on by some jerk right now, but I can't see evidence that they're successfully slowing anything down.

**Comment by AJLinn** [comment]
> There might be something interesting in your javascript console, 

Is there something I can share so you can see it?

> but my first guess is your network.

This happened both at the museum and at home (non-VPN connection). Tested again this morning and am getting the same results - total hang in[ Brave](https://brave.com/), very slow in Firefox.

Strangely, I also noticed in Brave when I add the column, save and refresh, it doesn't add the column when the results re-load. I have to do it a second time in order for the new column to get added. Same thing with removing... must be something to do with the Brave browser settings?

**Comment by dustymc** [comment]
>something

Google "{my browser} javascript console" or something of the sort, but see below.

IDK much about Brave, but that sounds like overly-aggressive caching.

I've been watching the logs and running around with my dev tools on, and I now think this is mostly #3155-like behavior - it sometimes (there probably is some related SOMETHING, SOMEWHERE, but I can't find it) takes a ridiculously long time to establish a session, and API calls (in this case to turn the JSON into thumbnails and links and such) each require a session. I can't replicate on test, and I can't see any evidence of this ever happening on test - I'm not confident I'm going to find an actual solution without https://github.com/ArctosDB/internal/issues/64 (or perhaps something like #2863, which might let me skip those calls altogether).

I'm not sure where to go from here. I might find some workaround, but I hate to introduce more complexity in an attempt to mitigate limited resources - that can too easily backfire. Lacking better ideas, I'll keep staring at it and hoping something comes to me....

**Comment by AJLinn** [comment]
Are these helpful? If not, let's just close it and I'll warn folks they might have issues. This is a major bummer, connected to what I see as an essential delivery service for users of cultural collections (i.e., seeing thumbnails in the search results view). And just having access to the Media hyperlink in that screen is not the same for our people.

<img width="1632" alt="Screen Shot 2021-05-06 at 9 37 48 AM" src="https://user-images.githubusercontent.com/17605945/117341859-1a30fe80-ae4f-11eb-890d-c7a82d8ee6ab.png">
<img width="1632" alt="Screen Shot 2021-05-06 at 9 38 29 AM" src="https://user-images.githubusercontent.com/17605945/117341882-20bf7600-ae4f-11eb-89b2-6bde1216c140.png">
<img width="1632" alt="Screen Shot 2021-05-06 at 9 39 06 AM" src="https://user-images.githubusercontent.com/17605945/117341908-27e68400-ae4f-11eb-837f-e323bf667f1f.png">

**Comment by AJLinn** [comment]
here's a few shots as its been attempting to load (I'm at the museum today):
<img width="1560" alt="Screen Shot 2021-05-07 at 9 50 14 AM" src="https://user-images.githubusercontent.com/17605945/117489531-32ba1b00-af1a-11eb-8d3f-be6170c6d8ee.png">
<img width="1596" alt="Screen Shot 2021-05-07 at 9 52 36 AM" src="https://user-images.githubusercontent.com/17605945/117489553-39e12900-af1a-11eb-883d-3c258f3271da.png">
<img width="1596" alt="Screen Shot 2021-05-07 at 9 52 48 AM" src="https://user-images.githubusercontent.com/17605945/117489577-42396400-af1a-11eb-9dff-1d2a1216092c.png">

And after it finally loaded all the images (sorry if it's too many or the wrong info!):
<img width="1596" alt="Screen Shot 2021-05-07 at 9 55 45 AM" src="https://user-images.githubusercontent.com/17605945/117489792-83ca0f00-af1a-11eb-8f45-d7d7a2885110.png">
<img width="1596" alt="Screen Shot 2021-05-07 at 9 55 58 AM" src="https://user-images.githubusercontent.com/17605945/117489827-8e84a400-af1a-11eb-81bf-f3214ecd1bc0.png">
<img width="1596" alt="Screen Shot 2021-05-07 at 9 56 08 AM" src="https://user-images.githubusercontent.com/17605945/117489864-96444880-af1a-11eb-93bb-cce9cb1ef7c4.png">
<img width="1596" alt="Screen Shot 2021-05-07 at 9 56 15 AM" src="https://user-images.githubusercontent.com/17605945/117489898-9cd2c000-af1a-11eb-865a-8a41dc809d9f.png">

**Comment by dustymc** [comment]
Idea: set up a cfschedule to process thumbs in media_flat, use that in UIs

**Comment by dustymc** [comment]
Added calculated/verified thumb to media flat. Update is running in production, should take about a week to complete if the current rate turns out to be sustainable.

Need to rebuild all code to use the cache instead of getMediaPreview()

Check back in a few days, make sure this is going to work before proceeding.

For the list:

1. This behavior does not occur in test, which makes everything more difficult. https://github.com/ArctosDB/internal/issues/64 should fix that.
2. The lack of a synchronized test environment means running scheduled tasks is difficult, which also complicates everything (and provides a great opportunity to melt production - so far so good...). https://github.com/ArctosDB/internal/issues/65 should fix.

**Comment by dustymc** [comment]
Production is now running precalculated thumbnails and no service calls.

A few good thumbs missed, probably for the same reasons the original problem exists, need a way to flag those for reprocessing.

**Comment by dustymc** [comment]
In next release:

<img width="597" alt="Screen Shot 2021-05-24 at 11 18 22 AM" src="https://user-images.githubusercontent.com/5720791/119390376-cf521c00-bc81-11eb-991a-5f4f7a4e1fda.png">

I'm reprocessing all misses, that should finish in a day or two.
