### ISSUE TITLE
SpecimenSummary: better handling of no results

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#3601]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I've returned from a trip to Mendocino County. I wanted to see if the mammals I brought back are well represented in the collection. I searched for Identification Tamias, County Mendocino County, Catalog record summary by Scientific Name. 

We have a lot. Got a table with various taxa and counts. 

I redid all that with the tissue flag checked. Arctos immediately threw up a error box, Arctos.database.museum says sad. Hit OK and the page is mostly blank with a red processing request box. Walked away for half an hour and no change. 

Went back and did search for the same criteria, but **not** sorted by scientific name and quickly got zero results. Yay for me for collecting the first Tamias tissues for MVZ, but Arctos should return 0 no matter how we ask for the results. 

Also, Use Last Values does not re-check the require tissues box. 

Screen grabs attached. 
<img width="485" alt="Screen Shot 2021-05-06 at 8 58 28 AM" src="https://user-images.githubusercontent.com/5749672/117334499-eb1a8d00-ae4e-11eb-8d9c-e92c32b49bd6.png">
<img width="468" alt="Screen Shot 2021-05-06 at 8 58 19 AM" src="https://user-images.githubusercontent.com/5749672/117334505-ec4bba00-ae4e-11eb-9f3e-7b631c05e8c5.png">

**Priority**
medium. Maybe indicative of something else screwy.

**Comment by dustymc** [comment]
This should be incorporated into https://github.com/ArctosDB/arctos/issues/2745

**Comment by dustymc** [comment]
I changed the message to "No results found." I don't think I can realistically do more in the current UI. Merging into https://github.com/ArctosDB/arctos/issues/2745.
