### ISSUE TITLE
Create New Collections Form error

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3603]
Trying to use https://arctos.database.museum/Admin/pre_collection.cfm to request creation of new collections portal for UNCG:Mamm. This is at least the fourth attempt over the past week. 
I get the following error when trying to add mclean as admin contact and campmlc as mentor:

**invalid admin_user; use your back button**

Both user accounts are open and active. However, mclean does not have any admin access because the collections he needs access to have not been created yet.

Priority: High, blocking progress

**Comment by dustymc** [comment]
> An Arctos Operator with manage_collection rights has been created and is fully functional. This will be used for "admin_user" in the next form. (Collection access will be assigned during creation.) 

has been on the form since creation.
