### ISSUE TITLE
Loans Media throwing error

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#3604]
I added a media file as "documents loan" and the loan detail page is not displaying the image, but rather this error: 
<img width="451" alt="Screen Shot 2021-05-18 at 6 42 15 AM" src="https://user-images.githubusercontent.com/17605945/118671731-306e8100-b7a4-11eb-8619-61a4add7b7af.png">

Loan record: https://arctos.database.museum/Loan.cfm?action=editLoan&transaction_id=21127159

I also added the relationship "shows cataloged item" and the media file shows up in the catalog record, though it's still just an Arctos bear for the preview after a few minutes. (Correction, there was a momentary hang notice that the file couldn't be accessed at TACC... maybe an issue there?)

https://arctos.database.museum/guid/UAM:EH:UA80-022-0059AB

**Comment by dustymc** [comment]
woops/thx/fixed - the thumb can take a while, but let me know if it's not there in a day or so.

**Comment by AJLinn** [comment]
It's fixed. Thanks!
