### ISSUE TITLE
Feature Request - Change color of box around same individual as relationships

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3605]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
See https://github.com/ArctosDB/data-migration/issues/506

**Describe what you're trying to accomplish** 
Red is scary - these relationships are GOOD things. We would like to see positive color for reciprocated relationships.

**Describe the solution you'd like**
Change the color of the box around same individual as relationships to green when they are reciprocated to indicate YAY!

**Describe alternatives you've considered**
No box at all except when not reciprocated.

**Additional context**

**Priority**
High because the red box obviously causes confusion.

**Comment by dustymc** [comment]
>these relationships are GOOD things

Yes, except when they lead to "and these two things are REALLY similar so {wildly invalid conclusion}" in a publication. At least, that's what brought about the idea of drawing extra attention to them.

Yellow for caution?

>except when not reciprocated.

I can't know that - the other record can be in some system I can't talk to.

ANYWAY - the marker is just CSS

```
.isDuplicateRecord {
      
      
        			border: .6em solid red;
      
      
        			padding: .2em;
      
      
        		}
```

its easy enough to change color, along with anything else CSS can do to a div.

**Comment by lin-fred** [comment]
I would also be ok with yellow. So that it still draws attention, but isn't "bad" like red.

Is it possible to change the color based on the relationship? or is that excessive?

**Comment by dustymc** [comment]
>change the color based on the relationship

There's only one (same individual as) handled at the moment, but it wouldn't be much problem to add some 'else if' statements.

>yellow

If you want to refine that, you can google "html color picker," drag the doohickeys around, and give me the hex value.

<img width="746" alt="Screen Shot 2021-05-18 at 9 19 40 AM" src="https://user-images.githubusercontent.com/5720791/118687758-396a4d00-b7ba-11eb-9be8-6777f2a42a80.png">

**Comment by lin-fred** [comment]
I would say #eed202
![image](https://user-images.githubusercontent.com/19802479/118690284-2610af00-b7c5-11eb-88ae-46e2e910f778.png)

or #ffff00
![image](https://user-images.githubusercontent.com/19802479/118690375-3d4f9c80-b7c5-11eb-966b-eeaecd3aec98.png)

**Comment by campmlc** [comment]
A happy yellow! Like  the old VW beetles . . .

**Comment by dustymc** [comment]
>Like  the old VW beetles . . .

http://www.cricketseed.com/beetle/colors_1949-79.html

The internet is weird...

**Comment by Jegelewicz** [comment]
e5da8c is a nice yellow...

**Comment by Jegelewicz** [comment]
I tried that VW color and it didn't look so good - so now test is using @lin-fred suggested color #eed202

BUT - maybe we should just stick with "yellow"?

**Comment by Jegelewicz** [comment]
BEWARE: In test, the links to reciprocal records take you to production, so you will see yellow on one record, but it still turns up red on the linked one...

Look here - http://test.arctos.database.museum/guid/MSB:Mamm:121439
