### ISSUE TITLE
Manage Part Attribute "location" in record results

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/arctos#3606]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
I wanted to add the same collection location for a group of specimens in one shot, but there is no option for "Parts attributes."

**Describe what you're trying to accomplish** 
I want to add the same shelf location to a group of specimens in one shot, but Arctos won't let me.

**Describe the solution you'd like**
Make "Parts attributes" accessible for managing in a records search.

**Describe alternatives you've considered**
Individually having to enter the same location in each record

**Comment by Jegelewicz** [comment]
@mbprondzinski you can use the [Bulkload Part Attributes tool](https://arctos.database.museum/tools/BulkloadSpecimenPartAttribute.cfm).
