### ISSUE TITLE
DWC Preservation

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3608]
**Is your feature request related to a problem? Please describe.**

From GGBN via @tucotuco

>Would it be possible to add preservationType to all Arctos GGBN sample datasets? Content would be e.g. “dried”, “silica”, “Ethanol”, “buffer” etc.

>You can use the GGBN preservation extension: http://rs.gbif.org/extension/ggbn/preservation.xml

**Describe what you're trying to accomplish** 

Make GGBN happy

**Describe the solution you'd like**

Probably a new view, but I think we have some crazy superdoubleextradenormalized identifiers for GGBN which might complicate things.

**Describe alternatives you've considered**

Don't.

**Additional context**

Primary data are in https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecpart_attribute_type#preservation (https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_preservation) but https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecpart_attribute_type#tissue_quality (https://arctos.database.museum/info/ctDocumentation.cfm?table=cttissue_quality) (and others??) is sorta-relevant too.

**Priority**

Needs assessed; this is somewhat pointless until https://github.com/ArctosDB/arctos/issues/1460 is completed.

**Comment by campmlc** [comment]
Agree with this in principle on completion of #1460 
At which point - priority high

**Comment by ewommack** [comment]
One question - we talked in the AWG Issues meeting about being allowed to not declare preservation type for some specimen parts. Would this mean we would have to declare them?

**Comment by dustymc** [comment]
No, this is just darwincore.

**Comment by ewommack** [comment]
Ah, okey dokey.

**Comment by dustymc** [comment]
Also of note: no part is natively a tissue (https://github.com/ArctosDB/arctos/issues/1875#issuecomment-834722169), GGBN only deals with tissue, for this use case parts without preservation will not be involved in any way.
