### ISSUE TITLE
Link back to bulkloader table after mark to load fails weirdly

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#3612]
For me, when I am in the bulkloader and mark records to load, some words appear on the screen to suggest you can click to go "Back to table". It does open up what looks like the bulkloader interface, but seems non-functional. It shows "Processing" over the text and I can't pull up any records by selecting and hitting filter. See screen shots. 

Chris

**Expected behavior**
Should be able to hit the link and go back to a functional interface. Currently, have to go to the dropdown under Enter Data and get there again. 

**Screenshots**
attached. 

**Priority**
Medium. Hopefully easy to fix. 
<img width="440" alt="Screen Shot 2021-05-19 at 11 11 32 AM" src="https://user-images.githubusercontent.com/5749672/118863553-e5cc3200-b893-11eb-8e06-edcff733bf36.png">
<img width="415" alt="Screen Shot 2021-05-19 at 11 10 56 AM" src="https://user-images.githubusercontent.com/5749672/118863558-e6fd5f00-b893-11eb-8661-4571659e118a.png">

**Comment by dustymc** [comment]
I can't break it - I need the specific records/filter/details, or perhaps whatever's in your javascript console if that doesn't lead anywhere interesting. I did this:

Found something, load all

<img width="164" alt="Screen Shot 2021-05-19 at 11 52 12 AM" src="https://user-images.githubusercontent.com/5720791/118868231-cf74a500-b898-11eb-8e0e-629092535b29.png">


<img width="237" alt="Screen Shot 2021-05-19 at 11 52 19 AM" src="https://user-images.githubusercontent.com/5720791/118868287-dd2a2a80-b898-11eb-9a11-7fb217663817.png">

<img width="171" alt="Screen Shot 2021-05-19 at 11 52 26 AM" src="https://user-images.githubusercontent.com/5720791/118868303-e0bdb180-b898-11eb-8614-e914b1126cf9.png">

and landed back on the filtered records I started with, with loaded NULL.

**Comment by cjconroy** [comment]
All my mammal records have since loaded, so I can't demonstrate again. Basically, I clicked on an accession, hit filter, got their list, clicked to Load all selected records, hit to proceed link, and got the screen with the Back to table link. It does go back to a table, but nothing works on it. And, immediately going back to the table it has that Processing pasted over the text.

**Comment by dustymc** [comment]
>accession

That did it, fixed in next release.
