### ISSUE TITLE
Weird 'non-replication superuser' error

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#3614]
I was trying to get to the Reporter and was having the same issue as #3487. I saw at least two different error messages: one the same as posted in 3487, the other said something about superuser connections. Tried all the same tricks (logged out/in, different browsers, cleared caches, etc.) still no worky. Gave up and then saw this on a specimen record:
![image](https://user-images.githubusercontent.com/12507297/119048496-8ac23a00-b97c-11eb-9121-33160262d0e4.png)
Am I logged in on more devices than I know about or something?

**Comment by dustymc** [comment]
We're just getting hammered with garbage. I manually booted some of it, hopefully things will be happy for a while.

**Comment by acdoll** [comment]
It's getting closer - I see the header and the link to Manage Reports now: 
![image](https://user-images.githubusercontent.com/12507297/119053166-eabbdf00-b982-11eb-9d39-bdbf152e83e5.png)

Following that link, I again get what would be at the top of the reports list, but not the main content:
![image](https://user-images.githubusercontent.com/12507297/119053303-1fc83180-b983-11eb-9f4a-2fd6e0736607.png)

I'll be patient and wait for things to clear up. (just want you to know what we're seeing)

**Comment by dustymc** [comment]
How'd you get there? The reporter is working for me, that's usually from coming back to a tab after the authentication has expired or similar.

**Comment by AJLinn** [comment]
I got that same message earlier. Forced myself in after about 5 failed attempts. A few other squirrely things with media also.

**Comment by acdoll** [comment]
Sorry I had to run off yesterday. I'm pretty sure I started everything fresh (logged off, new browser). It's working fine today.
