### ISSUE TITLE
font size in drop downs?

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#3615]
Maybe I am just old and blind, but it seems that many drop down menus on Arctos in Chrome have font sizes that are way too small. I work on a laptop, so I don't have the easy ability to have a giant monitor. Safari is much better. Also attached. 

**Screenshots**
Attached

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS 10.14.6, MacBook Pro 15 inch
 - Browser [e.g. chrome, safari] Chrome. Version 89.0.4389.128 
 

**Additional context**
I've tried resizing my screen size, but then the rest of the screen shrinks too much to be useful. Also, zooming in on the screen temporarily with fingers on the mousepad increases the size of most text on the screen, but not the size of the text in the drop downs. Is this fixable with code, or is there something I can do on Chrome?
<img width="709" alt="Screen Shot 2021-05-20 at 2 16 46 PM" src="https://user-images.githubusercontent.com/5749672/119050054-2f8d4900-b976-11eb-80df-b82bf30ef126.png">
<img width="493" alt="Screen Shot 2021-05-20 at 2 16 59 PM" src="https://user-images.githubusercontent.com/5749672/119050063-32883980-b976-11eb-8a9d-0a607ade5222.png">

**Priority**
Medium. 
<img width="528" alt="Screen Shot 2021-05-20 at 2 09 19 PM" src="https://user-images.githubusercontent.com/5749672/119049734-c0aff000-b975-11eb-863e-2e4c7856511c.png">
<img width="639" alt="Screen Shot 2021-05-20 at 2 09 05 PM" src="https://user-images.githubusercontent.com/5749672/119049736-c1488680-b975-11eb-8b66-06d72dc0da74.png">

**Comment by dustymc** [comment]
I'm not messing with it, but I can't guarantee that some library we use isn't. I probably CAN mess with it, but I'm not sure that won't turn into something horrible in some interface/browser/whatever. FWIW mine are about the same size as other text, which makes me suspect your browser is doing something weird.

<img width="751" alt="Screen Shot 2021-05-20 at 2 34 04 PM" src="https://user-images.githubusercontent.com/5720791/119051774-73814d80-b978-11eb-8a4e-0fe54d97ad4d.png">
