### ISSUE TITLE
[CONTACT: Blocked Network]

### ISSUE THREAD

**Issue by VicManRaRa** [ArctosDB/arctos#3616]
restricted IP: 187.190.147.79

**Comment by VicManRaRa** [comment]
Hello, I am interested in corroborating a data that I obtained through Darwin Core, about his collection of records of Artibeus hirsutus, specifically the specimen 214039.
Thank you very much for your time and attention

**Comment by ewommack** [comment]
Hello @VicManRaRa - can you tell us what collection you are trying to search?

Perhaps the record you are trying to find is this one: 
[https://arctos.database.museum/guid/MSB:Mamm:214039](https://arctos.database.museum/guid/MSB:Mamm:214039)

**Comment by dustymc** [comment]
Restriction released.
