### ISSUE TITLE
Code Table Request - sort code table categories alphabetically

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#3618]
We just organized the code tables by category and added descriptions, which is great, but the categories are not alphabetical as I would have expected. Can we list these alphabetically so that all of the code tables for the same category (e.g., locality) are together? The current (random?) sorting makes it harder to find the table you're looking for.

**Comment by dustymc** [comment]
<img width="207" alt="Screen Shot 2021-05-24 at 9 05 57 AM" src="https://user-images.githubusercontent.com/5720791/119375135-4d58f780-bc6f-11eb-8a2e-21e14e69d8b6.png">

???

**Comment by Jegelewicz** [comment]
When you are managing...
![image](https://user-images.githubusercontent.com/5725767/119375577-366ad300-bc78-11eb-9b93-3b6b6bda8595.png)

**Comment by dustymc** [comment]
Merged the public and manage forms. I left the link in the manage menu, it's redundant if we want to remove some clutter.
