### ISSUE TITLE
Feature Request - BulkloadLoanItem needs updated

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3619]
It's an older version, throws 400 errors for longer status messages.

This happens only in production: https://github.com/ArctosDB/internal/issues/64

Needs prioritized.

**Comment by campmlc** [comment]
Can we modify this tool to be able to subsample existing subsamples for loan? And be able to change the subsample name? 
I need to find a way to record via a bulkloader that a DNA extraction (child) resulted from a tissue subsample (parent) when the parent disposition is on loan. The child name is changed from the parent name, but it is derived from it.
I also need to add part attributes to the child record. (DNA extraction has tissue quality X with DNA quantification Y).
Then I need to put this DNA extraction on loan.
Right now, I believe I would have to bulkload the DNA extractions as separate parts - I don't know of any tool that would allow me to add subsamples of loaned subsamples in bulk.  Or allow me to change the name of the subsample.  Or add part attributes to the subsamples.  However, I could do this one at a time from each catalog record . . . but I have 100 samples to add this way.

**Comment by dustymc** [comment]
I don't think any bulk form should be that complicated. The old form tried to be, and ultimately didn't really work for anyone.

Create_subsample could change from BOOLEAN to FKEY-->specimen_part_name.

Bulkload parts (which will create attributes) could have a create_as_subsample_of_part option. 

 Bulkload Part Attributes will add attributes to any part.
