### ISSUE TITLE
weird random passwords with "blockquote" from user unlock

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#3622]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Password generator seems to do something strange occasionally:

**To Reproduce**
Unlock and reset user account

**Expected behavior**
generate a password readable and usable by user

**Screenshots**
![image](https://user-images.githubusercontent.com/38706617/119740967-0d963980-be42-11eb-8c0e-ef681336b503.png)

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**
PC; chrome

**Additional context**
user asked to have account unlocked and I got the "blockquote" password. I've regenerated it for the user because they needed it, but want to make sure it's not happening on the regular. When I copy and pasted the password in, Arctos didn't recognize it as the correct password.

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by dustymc** [comment]
I'll see if I can figure out how to prevent that; your email client is trying to "fix" something in the HTML. You should have some option to see the original - in gmail it's...

<img width="439" alt="Screen Shot 2021-05-27 at 7 03 24 AM" src="https://user-images.githubusercontent.com/5720791/119842075-3a3a6780-bebb-11eb-9f51-b8eca2fe0a67.png">

That version should be unmangled (but will include a bunch of stuff you don't need to care about at the top).

**Comment by mvzhuang** [comment]
ok got it. I see it's normal on the web.
