### ISSUE TITLE
rebuild spatial-service cache

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3625]
Geolocate is nowish our primary source of georeference automation, and Geolocate returns uncertaintyRadiusMeters. We don't currently have a place for that, and the form doesn't use it when the various magics are invoked.

Add an s$error field, do stuff with it

**Comment by Jegelewicz** [comment]
> We don't currently have a place for that,

That isn't this?

![image](https://user-images.githubusercontent.com/5725767/120007820-92469c00-bf97-11eb-93d3-a88e322e0de3.png)

**Comment by dustymc** [comment]
This need to happen before https://github.com/ArctosDB/arctos/issues/4728

We could/should also get data from our local data (eg, geography-with-spatial which encloses derived or asserted spatial), and we already have a couple sources of derived place-type data. 

This should be implemented as a complete refactor rather than an addition to the current overly-flat approach:

* Move the ``s$...`` locality fields to a structure capable of supporting multiple opinions
* Allow shapes
* Track source
* Store datum or convert (or both?)
* Make sure we have a place for whatever we can get from the current services and that whatever we do is normalized so we can grow

**Comment by dustymc** [comment]
Short version

* magic georeference button is smarter
* 'Place Term...' search is smarter

-------------

Long version

Belt-and-suspendered for next release. s$error will be added to locality and populated with "best" georeference, which offloads processing to the cacher rather than when someone tries to magic a georeference.

Alternative georeferences will be stored in cf_temp_georeference, which can be exposed (maybe after a few months when there's some data) when/if there's some reason to.

I'm not adding polygon capability at this time, I don't think the benefit (not sure what that might be) outweighs the cost (potentially terabytes), but the structure should easily accommodate if we find a reason to do so.

Edit locality and fork-edit event (including magic coordinates) will use and display error (as reported by the services) when it becomes available in the cache -or  manual refresh is available as always via "Webservice Lookup Data [Pull/Debug]"

Coordinates (including secondary derived) will be used to grab intersecting Arctos data for the place terms cache, which should make records with bad geography assertions more discoverable (via 'Place Term...' search options). https://github.com/ArctosDB/arctos/issues/4755 would make that a lot more useful; Arctos does not have spatial data for much of the planet, and what does exist is a bit spotty.

GeoLocate should be (slightly, probably) better at handling things like 'idk' when someone ignores [locality documentation](https://handbook.arctosdb.org/documentation/locality.html#specific-locality).

It should be easy to plug other services into the model.
