### ISSUE TITLE
percent as units is a mess!

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3626]
**Goal**
percent exists in two different controlled vocabularies

**Context**
Should it?

**Table**
Percent is in https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcount_units and https://arctos.database.museum/info/ctDocumentation.cfm?table=cttissue_volume_units

**Value**
Should we pick a table for percent or is there a reason this needs to be in two places?

**Definition**
N/A

Setting priority as high so we can avoid excess cleanup if we need to clean up.

**Comment by Jegelewicz** [comment]
for reference
percent = one part in every hundred

**Comment by Jegelewicz** [comment]
I think we should leave this in count units and remove from volume because of the definition:

A number or ratio expressed as a fraction of 100. It is often denoted using the percent sign, "%", although the abbreviations "pct.", "pct" and sometimes "pc" are also used. **A percentage is a dimensionless number (pure number); it has no unit of measurement.** <a href="https://en.wikipedia.org/wiki/Percentage" class="external">Wikipedia</a>

**Comment by Jegelewicz** [comment]
Code table committee says it isn't a problem - closing

**Comment by dustymc** [comment]
Reopening and potentially expanding this.

I think percent is used only by https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_event_attr_type&field=relative%20humidity

Suggest we change that and remove the obviously-inappropriate value from the CT.

 https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecpart_attribute_type#dna_absorbance_ratio_a260_a230 and https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecpart_attribute_type#dna_absorbance_ratio_a260_a280 seem to have been shoehorned through the CT process, are not used, and might benefit from whatever we do with humidity. Both are currently set up for free text and look like wildfires waiting for a spark; suggest we remove them from the CT until they can be properly structured.

**Comment by dustymc** [comment]
Meh, I'm un-panicking. Relative humidity uses https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcount_units, I think that table doesn't have a great name but I don't have a better suggestion at the moment. Names aside, stuffing weird units that don't fit elsewhere into ctcount_units seems reasonable (ish, I think - until they're mis-used, maybe). 

Reclosing this, percent as a volume (https://github.com/ArctosDB/arctos/issues/5718) still needs un-done.

**Comment by campmlc** [comment]
BTW - what happened to https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecpart_attribute_type#dna_absorbance_ratio_a260_a230 and https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecpart_attribute_type#dna_absorbance_ratio_a260_a280 ?
We need these attributes - they are only unused because they took so long to implement that the data were never entered. But the data exist. I don't see the attributes in the code table?

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/3624#issuecomment-1447293019
