### ISSUE TITLE
empty records won't delete in Bulk Edit Container

### ISSUE THREAD

**Issue by keg34** [ArctosDB/arctos#3636]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
My student, Paige (pberends) has been working on correcting barcode assignments from container type "vial" to type "cryovial".  As far as we can tell, all of her (and my) efforts to do this have worked, but somewhere along the line a set of 81 empty records have gotten stuck in the Bulk Edit Container loader under Paige's account.  If you hit "Get CSV" for these you get a file with only headers, no records.  The same goes for the "Review" function. We have both attempted to delete them using both the "Delete all records for this user" and the "Delete for this user/status" buttons.  The pages you are sent to claim the delete is successful, but then the system fails to remove them from the summary screen.  I waited overnight to see if some data cleaning system would clear them out, but that made no difference.  They also showed up in yesterday's "pending data" email (as an aside, I seem to receive this email consistently regardless of whether or not any of the listed users are either myself or people I supervise, but that's a separate issue).  This isn't a huge deal, but it would be nice to remove these ghost records from the loader. 

**To Reproduce**
Couldn't tell you.  Paige did mention that while she was uploading batches of records to fix, some seemed to fail for an unknown reason.  She resubmitted those and they went through on the second try.  

**Expected behavior**
I expect that when I hit "delete" the records will be deleted.  I also expect that when it says that there are 81 records in a set, when I download the csv file there should be 81 records in the file, not zero records.

**Screenshots**
![image](https://user-images.githubusercontent.com/17340466/120643350-0d023200-c444-11eb-8ca4-563eaf033bce.png)

**Data**
Sorry - don't have data.  We aren't sure which, if any, of our original files caused the trouble.

**Desktop (please complete the following information):**
Windows 10, Firefox

**Priority**
Low

**Comment by dustymc** [comment]
Ba, this is more of https://github.com/ArctosDB/internal/issues/64

I managed to delete them by changing the status and then deleting for that status. 

The form needs upgraded to the latest version of the component loader.

**Comment by keg34** [comment]
Thanks, Dusty!
