### ISSUE TITLE
Show the associated Projects on Publication details 

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#3639]
This is an example of a project that has a publication but one would not know it from the publication detail side. (relationship between publication and project should be reciprocal) In other words, under Publication details, show the Projects they are currently linked to

![Firefox_Screenshot_2021-06-03T22-25-00 147Z](https://user-images.githubusercontent.com/2523089/120719872-e366fc00-c47f-11eb-9b95-f854be22d451.png)

**Comment by dustymc** [comment]
Hu? You're seeing projects and publications that matched your search there - they don't necessarily have anything to do with each other, besides sharing whatever matched them both.

**Comment by mkoo** [comment]
Yes, that's the point. They appear to be random except for your search query. It would be valuable to show that the publication is linked in this project. You can see that in the Project, of course, but it is not reciprocally linked from the Publication details.

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/2234 should be resolved first.

Probably need a single-publication view for this - it will be expensive code, especially if we do something interesting in 2234, I don't think we can readily run that for the search results (or maybe we could limit results or something).

**Comment by dustymc** [comment]
In next release, performing OK if not great, https://github.com/ArctosDB/arctos/issues/3468 should fix that.

**Comment by dustymc** [comment]
I messed with the layout a bit - there's just too much information for the old list to make sense, it's all CSS now. Should go out tomorrow night, feedback appreciated.

<img width="689" alt="Screen Shot 2021-06-08 at 5 29 01 PM" src="https://user-images.githubusercontent.com/5720791/121274296-0c6ffe00-c87f-11eb-8007-d31e72e55bdf.png">

**Comment by Jegelewicz** [comment]
We really need someone to look at our aesthetics, but it is nice to have all this info available.

**Comment by dustymc** [comment]
>look at our aesthetics

..preferably via 'thou shalt use these (maybe bootstrap or something) CSS classes thusly' - probably requires funding.

**Comment by Jegelewicz** [comment]
Or a very motivated student looking to pad a resume?

**Comment by mkoo** [comment]
is there a list of the CSS classes? I'd like to know all the CSS classes
for various detail pages in Arctos.  if so, this is the sort of thing for
TEST so people can weigh in on different design options.

**Comment by dustymc** [comment]
Not really - https://github.com/ArctosDB/PG/blob/master/includes/style.css is the main file, these are still being adjusted inline, I'll _probably_ remember to move them over to the main....

It's all a bit haphazard, doesn't always work well on mobile, etc., etc. - some things could be adjusted, but just starting over with bootstrap/jqueryui/similar might turn out to be less work, and would certainly have more long-term benefit. That would also help guide how the code that uses the CSS is developed, which would be very useful from my perspective.

Ideally we'd just let the API consumers worry about layout, but I can't quite see how we'd get there at the moment.

**Comment by mkoo** [comment]
yea what I was afraid of... so overhaul of all selectors is in order.
(class="scrollytextthing" is not super helpful) So would be good to think
about defining specific CSS id for specific detail pages so your request
for an page make-over is actionable.

The details you have now for publications are great but definitely the
first API customer is us or at least we need to figure this out regardless
of the API.

For now, I suggest a little organizational help for the user here:
[image: suggestions for PUB detail page(1).png]
(sorry this is terrible looking too but I am in a rush and google docs are
having a fit )

**Comment by dustymc** [comment]
>first API customer is us 

I think "us" has outgrown any single UI, although that particular one probably isn't too bloated for any user group. That's definitely not an argument against making things better, I just don't want to get too locked into the tunnel.

Your attachment didn't attach.

**Comment by mkoo** [comment]
![suggestions for PUB detail page](https://user-images.githubusercontent.com/2523089/121442934-6d600a80-c941-11eb-84ae-a2f6fdca242e.png)

**Comment by dustymc** [comment]
Moved projects, changed class of local links (to ``newWinLocal``)
