### ISSUE TITLE
> New Other ID - NCBI Assembly.

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3640]
> So we need different "GenBank" urls in addition to nucleotide - we need biosample and assembly.

[NCBI Biosample](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type#ncbi_biosample)  is already in the code table.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type

**Value**
NCBI Assembly

**Definition**
A database providing information on the structure of assembled genomes, assembly names and other meta-data, statistical reports, and links to genomic sequence data. 

**Other ID BaseURL**
Base URL = https://www.ncbi.nlm.nih.gov/assembly/
Functional example =  https://www.ncbi.nlm.nih.gov/assembly/GCF_009829145.1

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/arctos/issues/3068#issuecomment-854237714_

**Comment by campmlc** [comment]
I support this, with request that it be expedited.

**Comment by Jegelewicz** [comment]
Added

**Comment by dustymc** [comment]
Reopening, this seems like denormalization, see https://github.com/ArctosDB/arctos/issues/3068#issuecomment-855460687

(But its NCBI, they're pretty good at maintaining stuff, if there's some compelling reason to link to things built from direct connections then I won't object.)

**Comment by Jegelewicz** [comment]
Sorry - I didn't realize the dependency.

**Comment by dustymc** [comment]
We need some sort of NCBI tour - I __think__ they are subsequent things, but I could be wrong, and I don't really have any clear picture of what a SRA or biosample or .... is or how we should be addressing/using them.

**Comment by Jegelewicz** [comment]
removed from the code table
