### ISSUE TITLE
Code Table Request - project agent role, case

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3643]
**Goal**

make data more consistent

**Context**

Authority values in Arctos are lowercase by default. https://arctos.database.museum/info/ctDocumentation.cfm?table=ctproject_agent_role Is All Proper Case For Some Reason

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctproject_agent_role

**Value**

 co-pi **(not really see below)**
 graduate student
 honors student
 academic advisor
 principal investigator
 sponsor
 volunteer
 research assistant
 post-doctoral associate
 undergraduate student
 research associate
 project coordinator

**Definition**

These need defined; existing data are bare.

sponsor==agent who can be linked with funding (pending something happening in https://github.com/ArctosDB/arctos/issues/3398)

I have no idea why the rest of these exist; help!

I dislike "co-pi" (in any case) - cryptic abbreviations are evil, and multiple principal anything is self-conflicting. Can we clean up whatever's not really necessary while we're defining?

**Priority**

Critical - code table inconsistencies are always high priority, I'm faced with adding to this mess or making this mess more internally inconsistent.

**Comment by Jegelewicz** [comment]
> Authority values in Arctos are lowercase by default. https://arctos.database.museum/info/ctDocumentation.cfm?table=ctproject_agent_role Is All Proper Case For Some Reason

Because they are sorta like titles for people. I think they should stay proper case or at least they need to show up that way on the Project pages.

**Comment by campmlc** [comment]
co-PI is useful because in most cases we do not know who the lead PI(s) are
on a project, but we have multiple names of researchers on a grant or
project. Rather than denigrate one to "research associate" status, co-PI is
more politically viable - especially, for example, if there are co-PIs in
developing countries. We need some sort of "all these names are equally
important in their efforts to contribute to this project" category.

**Comment by Jegelewicz** [comment]
I have added definition for all. The only one that seems extraneous to me is "Honors Student" because a participant could be both a Research Associate and an Honors Student (along with a bunch of other stuff).

**Comment by dustymc** [comment]
@campmlc using one term for them all does exactly what you said and is consistent with other data (eg if there's only one agent or you know all of their roles). If that's the use case, this is adding even more confusion (or taking away accessibility) than I suspected.

>(along with a bunch of other stuff).

That's what I'm saying! This all looks arbitrary, we're just making sure that nobody can use these to query. 

>sorta like titles for people

That's not how we're displaying them nor what they are structurally, but I suppose Undergraduate Student Teresa could work with some changes....

**Comment by Jegelewicz** [comment]
> Undergraduate Student Teresa

Nope - it's pretty much been "Volunteer Teresa"

**Comment by campmlc** [comment]
Yep. And what a volunteer!!

**Comment by mkoo** [comment]
looking over the current list, I agree that Honors Student is anomalous-- can we remove?
I suggest we change ```co-PI```  to ```Co-Principal Investigator``` too which removes the abbreviation and aligns with Principal Investigator.

**Comment by dustymc** [comment]
>Co-Principal Investigator

Why not just Principal Investigator as many times as necessary?

>can we remove?

I need a migration path.

```
arctosprod@arctos>> select project.project_id,project_name from project inner join project_agent on project.project_id=project_agent.project_id and project_agent_role ='Honors Student';
 project_id |                                                                     project_name                                                                      
------------+-------------------------------------------------------------------------------------------------------------------------------------------------------
    1000020 | The stable carbon and nitrogen isotopic composition of East Beringian grasses
    1000039 | Phylogeographic structure of the <i>Zapus princeps</i> complex
          7 | Age determination of <i>Ursus arctos middendorfi</i> using cranial characters.
        101 | Cranial and dental anomalies in otters.
    1000040 | Distribution of the armadillo <i>(Dasypus novemcinctus) </i>in New Mexico
    1000099 | Genetics of leaf hair production in <i>Arabidopsis kamchatica</i>.
    1000100 | Phylogenetic relationships among Alaskan poppies.
   10000321 | Phylogenetic relationships of <i>Ensatina eschscholtzii picta</i>
    1000099 | Genetics of leaf hair production in <i>Arabidopsis kamchatica</i>.
   10000835 | Climate change induced size change in Red squirrels (Tamiasciurus hudsonicus) in interior Alaska.
   10001378 | Genetic Analysis of House Mice (Mus musculus) from Alaska
   10002243 | Quantifying Variation in the Primate Hip: A Morphometric Study of the Proximal Femur & Implications for the Evolution of Primate Locomotor Adaptation
   10001164 | Microsatellite project on <i>Anniella alexanderae</i>.
(13 rows)

```

**Comment by mkoo** [comment]
Honors Student -> Undergraduate Student

If there's exceptions we can clean up.

OK, I could be convinced of getting rid of the distinction of Co-Principal
Investigator; instead, we can add a remark 'lead' to denote the lead PI
because there is a distinction to some, even if not regularly recognized by
others

**Comment by campmlc** [comment]
I do think that "lead" is valid as an option, especially on a project like
BCP where you might have half a dozen or more co-PIs. Who do you contact
with questions? The lead PI.

**Comment by dustymc** [comment]
From @Jegelewicz 's much-appreciated [definition](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctproject_agent_role#co_pi):

> co-investigator (Co-I) assists **the** principal investigator

"Co-PI"-->"Investigator"?

I'm certainly fine with retaining https://arctos.database.museum/info/ctDocumentation.cfm?table=ctproject_agent_role#principal_investigator as "**The** lead PI." 

I'm not trying to change the world here, I'm just looking for clear vocabulary that can be used consistently. (And Proper Case is still silly but whatever...)

**Comment by campmlc** [comment]
a "co-principal investigator", also known as the Co-PI"

**Comment by ewommack** [comment]
Having a lead designation somewhere (either as PI versus Co-PI) would help in figuring out who you should contact to ask questions, for reports, etc.

**Comment by dustymc** [comment]
Closing; we have definitions (thanks @Jegelewicz), I've inserted my new terms, we can revisit when/if our inconsistent vocab/usage stops someone from doing something.
