### ISSUE TITLE
Parts/Table download not filtering for composite parts

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3645]
The parts/table download from catalog record results is not recognizing parts with multiple tissues separate by a comma (e.g. heart, lung) or parts with multiple preservation types separated by a comma (formalin-fixed, 70% ethanol).
When I try to filter for these parts, nothing shows up in the table.

**Comment by campmlc** [comment]
Elevating priority - we've switched to using this tool for loans, and I'm hoping this is a quick fix?

**Comment by dustymc** [comment]
>quick fix

It's not; see linked issue.

The only semi-realistic approach I can think of is changing the delimiters of compound parts, but then this form would be the ONLY place you'd see eg "heart|kidney" and that's lead to confusion before.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/3654
