### ISSUE TITLE
Clone Function Not Working

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3653]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I have twice now tried to clone an MSB:Mamm parasite part into a MSB:Para record using the Other ID Clone this record function from catalog record. Both times the record has cloned as a new record in MSB:Mamm, despite my clearly indicating a preference for MSB:Para.
The second time, I checked the record in data entry to make abolutely sure that the accession and the collection were MSB Para.. But there were signs things were not working, in that I got pink error because my attributes and parts were not recognized. 
I deleted the offending parts and attributes. Then the record loaded as MSB Mamm.

Go to https://arctos.database.museum/guid/MSB:Mamm:293426
Other IDs : [ Clone This Record ]
choose to clone as Schizorchis taxon in MSB:Para
See giant mess in bulkloader
See fixed and loaded attempt #1 at https://arctos.database.museum/guid/MSB:Mamm:335814 which loaded as MSB:Mamm despite saying MSB:Para in data entry (I've encumbered this one)
See second attempt cloned fromhttps://arctos.database.museum/guid/MSB:Mamm:335814; ditto: https://arctos.database.museum/guid/MSB:Mamm:335854

**Expected behavior**
for record to clone into specified collection, and for the parts and attributes to be recognized as Para parts and attributes. 
Also, please change cloning process to not include attributes and parts  across collection types

**Screenshots**
![Screenshot 2021-06-09 15 50 41](https://user-images.githubusercontent.com/14808196/121434483-a648b100-c93a-11eb-8180-3f24a0327b6d.png)

**Priority**
Very high. Trying to ship a loan of this sample asap.

**Comment by dustymc** [comment]
Cross-collection clone bug patched.

The rest of this is beyond the current clone process. That could be improved, but I suspect adjusting the pull options would make more sense.
