### ISSUE TITLE
compound parts

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3654]
## Problem

We have compound parts ([heart, kidney, liver](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#heart__kidney__liver) for example), which seems sub-optimal.

They currently account for about 20% of all parts, which causes considerable clutter in the picks. That generally results in the wrong value being selected from time to time (but how would we really know?).

There doesn't seem to be an end to the growth, see https://github.com/ArctosDB/arctos/issues/3650

There are various ways of saying "multiple parts" - eg  [stomach plus stomach content (70% ethanol)](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#stomach_plus_stomach_content__70__ethanol_)

Using comma as a delimiter probably confuses people and definitely makes things like https://github.com/ArctosDB/arctos/issues/3645 difficult (comma is a "native" delimiter for many languages and situations).

## Solutions

Multiple parts can share a container; these could be programmatically split and inserted into a single container (which might have to be created just for this purpose for some use, but I think most of these are in barcoded collections). This normalizes everything; these would look and work like all other parts, providing one path for users to find what they need, and eliminate code-table redundancy making everything more discoverable. It would also somewhat complicate using barcode as partID (eg for adding to loans - but are we loaning tubes of mixed tissue?) and would make part counts slightly more complicated (this was mentioned elsewhere but I can't find such a report??).

Some collections catalog multiple parts as "tissue" and elaborate in remarks. Doesn't seem ideal to me, but neither does putting multiple parts in a tube, and this approach seems to work surprisingly well "in the wild." I believe this deserves serious consideration. I think this is also the only approach that inherently alerts the user that they're not getting "pure" parts, but I'm not sure how to value that (seems like it should be important to know?).

A part attribute "sub-parts" is possible; this is essentially identical to above, but the specific parts would be listed through a code table rather than in remarks.

We could do nothing. I can't exactly put my finger on anything WRONG with the current system (given that we can't control what collectors cram into tubes), but it does seem to find ways to require significant amounts of our collective attention.

We could change delimiters; this is essentially the "do nothing" approach, but in a format that isn't so easily confused with a list of individually-packaged parts by humans or machines.

**Comment by Jegelewicz** [comment]
> and would make part counts slightly more complicated (this was mentioned elsewhere but I can't find such a report??).

I disagree - I think it would make it EASIER. Right now you have five parts that we can only count as one. If they were separated, but given a single container, one could know there are 5 parts but only a single container to move around.

**Comment by dustymc** [comment]
>have five parts that we can only count as one

Are there 5 THINGS crammed in that tube or is it one THING with some complexity? Maybe an answer - if there is one - would help guide how we progress.

>degradation

Yes, I suspect so, and I also suspect that's influenced by what's in there and how things are packed - being stored with liver probably leads to different suitability for use than being stored alone or even with muscle, big chunks probably fare better than smaller, etc.

I can't quite wrap my head around the entire situation, but note that we don't list the components of other things - a pickled rat (or an embryo in a nunc, if we need a closer but less common comparison) is listed as a pickled rat, even though it might contain similar tissues that can serve some of the same purposes as frozen tubes (perhaps especially of mixed bits-n-pieces).

>barcode indicates a CONTAINER, not a PART 

Parts **are** containers. There's some special handling which precludes them having barcodes (among other things), but I'm not sure if that was a good idea or not - we may have a really handy and entirely defensible place for that sort of information just waiting to be used.

**Comment by dustymc** [comment]
> just semantics

No, it's structure. All parts are containers. No exceptions, no semantics, parts are containers. Many of them don't (and probably won't) have parents (and so aren't terribly useful for object tracking), but they're still containers. https://handbook.arctosdb.org/documentation/container.html

**Comment by acdoll** [comment]
I do support some sort of change here, but not fully sure which one. Just to make sure I'm following, it sounds like there are two options (three if you count 'change nothing'):

1. Enter each tissue in the shared container separately - they would be linked through the parent container (how do non-barcode institutions handle this?) The catalog record UI would have to be redrawn to make it clear to searchers that they are in the same tube (different than multiple parts that are in same cabinet, eg skin and skeleton). Public users don't see the barcode or container path, so that alone doesn't solve this.

2. Enter 'tissues' or something like it and then indicate sub-parts similar to locality attributes. 

Both of these options will make the data entry more cumbersome - lots more typing and/or clicking (also many more columns for bulkloading). For #1 the Data Entry UI could remain essentially the same, but for #2 it would have to squeeze in the sub-part selection fields or have a link (like Pick Locality) to some sort of pop-up selector. Either way, I would request a Sync option (like for attribute determiner and date) for the Condition, Disposition, Preservation and #.

**Comment by Jegelewicz** [comment]
@acdoll I think there is actually one more possibility, which is what MVZ does - use "tissue" as part and list the types of tissue in remark. Apparently this works well for them, so we probably shouldn't discount it unless there's a good reason to. It solves the data entry complexity but does leave room for more human error (misspelling the tissue types, using a different kind of separator than expected, etc) AND it is much less informative/useful over time (at least I think it is).

I think it would be good to set up some records with all three scenarios in test and let everyone have a look?

**Comment by dustymc** [comment]
>how do non-barcode institutions handle this?) 

Containers don't have to have barcodes, but it would be some extra SOMETHING for them, where "barcode institutions" probably already have the containers in place. (Does anyone actually have uncontainerized freezers?)

> make it clear to searchers that they are in the same tube

This is part of what I don't understand: who cares? Is it all the same? Should we be telling researchers (and should they be noting in publications and etc.) that tissues [are|are not] being dug out of shared containers, or does nobody care? Do users (or some users?) need to know this when "shopping" or is this something that only the people who are digging a hunk of liver out of the freezer need to care about? (I think perhaps at least MVZ - and presumably their borrowers - do view these as lesser quality and so needing a less-stringent model, but I'm not at all sure of that.)

> sub-parts similar to locality attributes.

That can go through the "extras" now,  maybe we'll eventually figure out how to make that more integrated. (That might even be a "just UI" problem now, given that component loaders have autoload functionality - https://github.com/ArctosDB/arctos/issues/2178.)

>leave room for more human error 

Yes, what MVZ does isn't something that any designer or engineer would ever come up with, but it does seem to work well.

**Comment by campmlc** [comment]
I need to respond in depth but can't do so immediately. So some background.
Yes, multiple tissues are in same container. This was done for space and
time reasons in field and museum and also because we used to have a limit
of 10 parts to load through data entry and bulkloader.
Splitting them will make both processes more difficult.
We have lots of unbarcoded legacy multi tissue tubes.
We now have researchers needing to search for specific tissue types. We
also need to track extractions back to a tissue type when possible. But
loans from these multi tissue tubes very rarely document which tissue was
pulled, even if it were possible to do so.

**Comment by acdoll** [comment]
> one more possibility

I considered this part of 'change nothing'. Making that a standard practice would simply require documentation.


> what I don't understand: who cares?

Your comment about degradation from the inclusion of liver applies here. We have had researchers comment on this.

> This was done for space and time reasons

Although it may be ideal from a database and even a research point-of-view, asking institutions to split all their parts is completely impractical. A shrew organ takes up 1/50th of a cryovial; putting 4 tissue types into separate vials quadruples your space requirement (not to mention the wasted plastic).

> But loans from these multi tissue tubes very rarely document which tissue was pulled, even if it were possible to do so.

This sounds like a good reason for using 'tissue' and remarks or subparts. We have tons of multi-tissue tubes and when I'm pulling a loan I will note the pulled tissue when possible. Going with option 1 would allow me to indicate the subsample was from a specific part/tissue. With the other options, that would just be another remark (which I could live with). Of course, I'm not sure what I would do when I can't tell which tissue I'm pulling. The ability to differentiate tissues in a tube does decrease over time and with increased usage/degredation.

**Comment by Jegelewicz** [comment]
>     This was done for space and time reasons
> 
> Although it may be ideal from a database and even a research point-of-view, asking institutions to split all their parts is completely impractical. A shrew organ takes up 1/50th of a cryovial; putting 4 tissue types into separate vials quadruples your space requirement (not to mention the wasted plastic).

No one here is suggesting that the parts be PHYSICALLY separated......that is up to the collections maintaining the stuff! We are only suggesting digital separation for better discoverability.

**Comment by Jegelewicz** [comment]
>     But loans from these multi tissue tubes very rarely document which tissue was pulled, even if it were possible to do so.
> 
> This sounds like a good reason for using 'tissue' and remarks or subparts. We have tons of multi-tissue tubes and when I'm pulling a loan I will note the pulled tissue when possible. Going with option 1 would allow me to indicate the subsample was from a specific part/tissue. With the other options, that would just be another remark (which I could live with). Of course, I'm not sure what I would do when I can't tell which tissue I'm pulling. The ability to differentiate tissues in a tube does decrease over time and with increased usage/degradation.

I agree - this seems like an argument for the path MVZ has taken.


>     one more possibility
> 
> I considered this part of 'change nothing'. Making that a standard practice would simply require documentation.

This WOULD be a change, because we would recommend changing all of the "heart, liver, muscle" parts to "tissue", putting that in remark and removing those compound terms form the code table.

**Comment by dustymc** [comment]
>4 tissue types into separate vials 

To be clear, I have no interest in attempting to change that. I suspect we can somehow do better in how we handle the data, we can certainly develop better documentation whether that includes data or model changes or not, that's the limits of my interest.

> track extractions back to a tissue type when possible.

I don't think that's any different with mixed tissues or separate, assuming "I don't think the mixed tissue is ever loaned. " from https://github.com/ArctosDB/arctos/issues/3654#issuecomment-858774813 holds true (and I think it does). If there's a subsample recorded then that information is available, if there's not it's not, the reasons that might happen (or not) aren't relevant for this. (But those reasons might be important for developing local policies or determining who gets a key to your freezer room.)

>can't tell which tissue I'm pulling.

That's currently handled by the model (and recently the parts bulkloader) - you can end up with ``tissue-->heart`` or ``tissue-->tissue``.

**Comment by campmlc** [comment]
Can we add tissue type to part attributes? Then we could have a code table
there instead of in remarks, and we could use tissue as the part name. I'm
hesitant to use remarks for tissue type. I'm going to have to play with
this in test to make sure the idea is workable for us in DGR.

**Comment by acdoll** [comment]
> No one here is suggesting that the parts be PHYSICALLY separated

I believe Mariel suggested it in #3650 in a 'going-forward' sense. I just wanted to be on record that I am not for that; as you said that should be up to the collection.

> digital separation for better discoverability

I am all for that.

> This WOULD be a change, because we would recommend changing all of the "heart, liver, muscle" parts to "tissue", putting that in remark and removing those compound terms form the code table.

Yes, that would be a change (code tables and remarks), but not require much structural change, right?

**Comment by Jegelewicz** [comment]
> Can we add tissue type to part attributes? 

Yes that is one of the solutions @dustymc gave. And A code table was created for this some time in the distant past, but no one ever used it and I believe it was removed when we cleaned up the table of code tables.

**Comment by ewommack** [comment]
The UWYMV uses the MVZ method and we do not have barcodes, but we do have unique Tissue #s, so more info complexity. The single Tissue works well for us, but we are a smaller institution.
Here's my work flow:
Collect one vial of tissue and the organs are stored in a very specific format in the vial. 
On Arctos the part selected is Tissue, preservation Frozen
In remarks I put the Tissue #, and a remark that says how many vials were saved and the types of material in each. Example "Tissue B-1111, saved 1 vial of HKML" or "Tissue M-813, saved 4 vials one each of H, K, M, L"

I've started doing the same for our RNA samples, but we'll see how that works out. Those are a lot more vials, and more interesting types of tissues. Brains...

**Comment by Jegelewicz** [comment]
@ArctosDB/arctos-code-table-administrators discussed this today. Using part = tissue and attributes that indicate the type of tissue work has been suggested and may be a good compromise?

> Can we add tissue type to part attributes? Then we could have a code table there instead of in remarks, and we could use tissue as the part name. I'm hesitant to use remarks for tissue type. I'm going to have to play with this in test to make sure the idea is workable for us in DGR.

The compound parts could be added to the "part modifier" code table, but it is likely we would end up adding individual parts over time...does that make sense?

**Comment by campmlc** [comment]
On thinking this over, I'm opposed to this idea. It may work fine for
collections that have few tissue parts, but MSB has records with dozens.
Going to "tissue" as part name would affect the catalog record and search
pages as well as loan item review and parts table download and object
tracking forms, all of which would have to be modified to make it easier to
search on and select which tissue type attribute to view and select for
loans. This would also affect our loan reports.
I would be more receptive to the idea of splitting compound parts into
separate parts sharing a container, but this would affect the loan add by
barcode and loan bulkload by barcode forms.

**Comment by campmlc** [comment]
And this is occurring just as the technology is advancing to the point
where we are increasingly getting loan requests for specific tissue types.

**Comment by Jegelewicz** [comment]
I have started a summary of this topic in a [Google Doc](https://docs.google.com/document/d/1NPIXpWrh-J4U6dLEekIqb9k-qzDWzndsxZdKzpaChiI/edit?usp=sharing). I think we need to do our best to get all interested parties together for a meeting to hash through the possibilities. Who needs to get a poll for a meeting day/time?

**Comment by dustymc** [comment]
Random points:

* Search could be somehow different than it is now; modeling data around some existing UI is about never a defensible idea.
* A heart in a tube by itself and a heart in a tube of things that are slowly trying to digest it [do not have the same usefulness](https://github.com/ArctosDB/arctos/issues/3654#issuecomment-859762939), that should be recognized somehow.
* Barcodes aren't the only [part handles]( https://github.com/ArctosDB/arctos/issues/3630), I don't think the collections that make heavy use of barcodes as handles are mixing stuff, I don't think the collections that mix stuff loan without subsampling

FWIW I think I've (surprisingly!) become a fan of "tissue" + remark - the collections that actually use this seem to like it, the objections seem entirely theoretical, it can carry [more information than a list of parts in alphabetical order](https://github.com/ArctosDB/arctos/issues/3654#issuecomment-862783719), and it reflects the usability differences.

**Comment by Jegelewicz** [comment]
Above added to Google Doc.

**Comment by Jegelewicz** [comment]
Setting this as priority for the next @ArctosDB/arctos-code-table-administrators meeting.

**Comment by dustymc** [comment]
No disagreement with prioritizing this, but I'm not sure how far that'll get - https://github.com/ArctosDB/arctos/issues/3708 might be more immediately actionable for the committee.

**Comment by Jegelewicz** [comment]
Either we need to add back the part head, tail or we need to get rid of compound parts. This is holding up cataloging. Please see https://github.com/ArctosDB/data-migration/issues/370

@campmlc

**Comment by dustymc** [comment]
For now: round up ways of saying ``part, otherpart`` that aren't in that format, make the mess slightly more consistent.

**Comment by acdoll** [comment]
> ALL other collections in this situation use "tissue"

definitely not true

**Comment by dustymc** [comment]
Tabling. This isn't actionable, doesn't seem likely to become actionable, and there are lots of ways to avoid the problems caused by compound parts.
