### ISSUE TITLE
Feature Request - Being able to view Agent Ranking from Create Loan page

### ISSUE THREAD

**Issue by KyndallH** [ArctosDB/arctos#3656]
**Is your feature request related to a problem? Please describe.****Describe what you're trying to accomplish** 

The time you need to see the ranking is when you are loaning someone a specimen. You can see it on their agent page but it would be great if there was some way to view ranking when creating a loan for an agent. 

**Describe the solution you'd like**

How might we accomplish your goals?
Maybe some way to flag an agent that has a ranking. Even if it is after they create it, have something next to the ranking to indicate they have a ranking. 
<img width="823" alt="Screen Shot 2021-06-10 at 2 35 10 PM" src="https://user-images.githubusercontent.com/16887896/121605583-22a1c980-c9f9-11eb-8883-cefeabe107a1.png">

**Describe alternatives you've considered**
Viewing it on the agent page but you'd have to look up agents separately. 

**Priority**
Somewhat important.

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/3448
