### ISSUE TITLE
Feature Request - Use Publication Bulkloader tools without having mange collection rights

### ISSUE THREAD

**Issue by KyndallH** [ArctosDB/arctos#3657]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.****Describe what you're trying to accomplish** 

We have two interns that are working on publications and projects. They have Arctos publication rights BUT this does not enable them to use the publication bulkloader tools. We'd like them to be able to do this without giving them Manage Collection rights.

**Describe the solution you'd like**
I'd like them to be able to use the Citation and Bulkload Identification bulkloaders.

**Describe alternatives you've considered**
Giving them Manage Collection Rights.

**Priority**
Moderate-High Priority

**Comment by dustymc** [comment]
Maybe https://github.com/ArctosDB/arctos/issues/1721, if someone can come up with a name.

**Comment by campmlc** [comment]
Can we add permissions to Manage Publications?

**Comment by dustymc** [comment]
Introducing inconsistencies into the component loader ecosystem sounds like a huge step backwards to me.

**Comment by KyndallH** [comment]
I'm thinking of it as a small sidestep. :)

There is a huge difference between bulkloading citations and identifiers and DELETING stuff. 
<img width="428" alt="Screen Shot 2021-06-10 at 4 33 36 PM" src="https://user-images.githubusercontent.com/16887896/121613781-bed3cc80-ca09-11eb-94a5-ff3edea44cf8.png">

I don't want to give students manage_collection rights if I don't have to.

**Comment by dustymc** [comment]
>huge difference between bulkloading citations and identifiers and DELETING 

But not from "mark...to load" especially considering https://github.com/ArctosDB/arctos/issues/2178. The citation loader creates identifications, so imagine waking up to your entire collection having 500 new IDs or something equally fun - not as much "fun" as finding your collection gone, but still not a great time for anyone. I don't think there's any existing sub-manage_collection role that should have that level of access.

A new "manage collection but not users or admin stuff" role seems reasonable to me, whether it has INSERT on cataloged item (eg minting GUIDs, so can fulfill the needs of https://github.com/ArctosDB/arctos/issues/1721) or not. The biggest obstacle seems to be picking a name....

I'd like to keep the component loaders consistent, but that's more usability than tech-stuff so it could be open for discussion.

**Comment by Jegelewicz** [comment]
> A new "manage collection but not users or admin stuff" role seems reasonable to me, whether it has INSERT on cataloged item (eg minting GUIDs, so can fulfill the needs of #1721) or not. The biggest obstacle seems to be picking a name....

manage_records

**Comment by dustymc** [comment]
@KyndallH why are you using both of Citation and Bulkload Identification - is the citation loader missing something?
