### ISSUE TITLE
Reports server down?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3658]
Have been getting The web site you are accessing has experienced an unexpected error.
Please contact the website administrator.
for past 40 min?

**Comment by dustymc** [comment]
its not down

**Comment by campmlc** [comment]
I've logged out, back in multiple times. Still get Element DBUSER is
undefined in SESSION.

**Comment by dustymc** [comment]
That's almost always from jumping around tabs, but I'm just guessing without the requested information.

https://github.com/ArctosDB/arctos/issues/new?assignees=&labels=Bug&template=bug_report.md&title=

Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Comment by campmlc** [comment]
Still having problems. This time I get no error, the browser just spins when I click the link to go to the reports server. 
1) Search loan 2021.6.Bird in MSB:Bird
2) Edit loan
3) Print report
5) Any Report
6) click http://reports.arctos.database.museum/reporter/report_printer.cfm?auth_key=8E5F6196-233A-4852-BBF6A0DA019F775F&transaction_id=21127075

Nothing happens. I really need to be able to ship loans at the end of the day. This is preventing that.

**Comment by dustymc** [comment]
Thx, it was dead, now it's less so.
