### ISSUE TITLE
No access to enter/edit agents

### ISSUE THREAD

**Issue by aklompma** [ArctosDB/arctos#3661]
@dustymc 
I used to be able to enter/edit agents, but not anymore.
Dusty, would you mind taking a look at it?

"An error occurred while processing this page!
Message: not authorized
Detail: You are not authorized to access this form.
Check the Arctos Handbook for more information on errors.
This message has been logged as 6DDAE417-973B-4255-BE7DA128A65EFF69 Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue."

**Comment by Jegelewicz** [comment]
@aklompma I just granted you access - if you need a refresher, the agent documentation is here.

Read the documentation about [Agents](http://handbook.arctosdb.org/documentation/agent.html).

**Comment by aklompma** [comment]
Thanks very much!
