### ISSUE TITLE
Difficulty with linking extras back to a data record

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3662]
The following is a problem we have brought up multiple times. We need some way of adding an identifier to the extras bulkloader that will tie a record back to original data to discover what went wrong if an extra fails to load. We now just have the uuid, which is meaningless if a record does not load for some reason. Can we add all the other IDs associated with a record that has a uuid generated added to the component loader system, so we could find and solve these kinds of issues?

From @bryansmclean 
Hoping you can provide quick insight on attributes bulkloading.

We routinely have 1 more attribute (endoparasite exam) that we need to add to our data entry forms. 
I can see this in the attribute bulkloader following data entry.

Can you tell me what order this should be uploaded in? for example, I uploaded some records and now it seems the attribute cant be linked because they arent in the bulkloader queue anymore. Am I interpreting that correctly and is there a better way to do this?

image.png

**Comment by campmlc** [comment]
![image](https://user-images.githubusercontent.com/14808196/121734386-f0a06e00-cab1-11eb-9604-ef5d113969c4.png)

**Comment by Jegelewicz** [comment]
What collection?

**Comment by campmlc** [comment]
UNCG:Mamm

**Comment by campmlc** [comment]
as oschapman Attribute bulkloader

**Comment by Jegelewicz** [comment]
I don't have access to that one, so I can't look at it.

**Comment by dustymc** [comment]
There are two things going on

https://github.com/ArctosDB/arctos/issues/3582, which is becoming the current generation for https://github.com/ArctosDB/arctos/issues/3611 right now adds...
<img width="363" alt="Screen Shot 2021-06-11 at 12 09 53 PM" src="https://user-images.githubusercontent.com/5720791/121737611-f3995f80-caad-11eb-96f2-1969a9174811.png">


And the attribute loader isn't handling notfound properly - it should be automagically retrying, and will be in next release.
