### ISSUE TITLE
error feedback

### ISSUE THREAD

**Issue by StefanieBond** [ArctosDB/arctos#3663]
Trying to create an incoming loan, I do get an error message: value too long for type character varying(255). Not sure what I did wrong, but the form will not let me create this "burrow". Thanks for your help.
<img width="1139" alt="Screen Shot 2021-06-14 at 12 37 10 PM" src="https://user-images.githubusercontent.com/40806258/121956630-d662cc00-cd0d-11eb-9bc0-532ebe363f39.png">
<img width="1139" alt="Screen Shot 2021-06-14 at 12 36 22 PM" src="https://user-images.githubusercontent.com/40806258/121956645-d95dbc80-cd0d-11eb-8e2c-40407f628684.png">

**Comment by dustymc** [comment]
extended to 4000 characters - the save should work now
