### ISSUE TITLE
search for any taxon yields 0 results

### ISSUE THREAD

**Issue by amgunderson** [ArctosDB/arctos#3668]
<img width="728" alt="Screen Shot 2021-06-15 at 1 24 15 PM" src="https://user-images.githubusercontent.com/8440698/122125485-02994e00-cddd-11eb-9fc6-b65a5b549c7e.png">

When searching in the "Any taxon, ID, common name" field for a species name there are 0 results. I know there is a bad reason for this but this is searching at its most fundamental and should work or be removed as an option.

**Comment by Jegelewicz** [comment]
Try using %broweri%

**Comment by amgunderson** [comment]
I already know how to get around it. I just shouldn't have to. It doesn't make sense and will lead people to believe we do not have specimens that we do have.

**Comment by Jegelewicz** [comment]
Maybe we just need better instructions? "broweri" isn't a taxon by Arctos definitions. A taxon must start with a capital letter - so just using a specificEpithet won't ever work (at least not as expected). @dustymc can shoot me down if I am wrong there....

**Comment by dustymc** [comment]
> better instructions?

We've had instructions forever(ish).

<img width="745" alt="Screen Shot 2021-06-15 at 4 21 40 PM" src="https://user-images.githubusercontent.com/5720791/122135680-d1794780-cdf5-11eb-8a8e-7afdd938ad3d.png">

Yes there's unlikely to be anything that starts with "broweri" in anything this considers.

I'm building fancy indexes (or maybe melting the box, IDK), we may now have the CPU to make 'contains' search work as trigrams but I'm not sure yet, and like many other things that's greatly complicated by https://github.com/ArctosDB/internal/issues/65.

**Comment by amgunderson** [comment]
If the field says "Any taxon" no one should have to read anything other than that to search for any taxon. species epithets are taxons. 
Where as this search field does not work as presented and produces more frustration than functional results...
Therefore be it resolved that is should be removed from the Arctos search page leaving

<img width="552" alt="Screen Shot 2021-06-15 at 4 56 07 PM" src="https://user-images.githubusercontent.com/8440698/122141801-988fa180-cdfa-11eb-9701-ac945fdb3d63.png">

as the default Identification and taxonomy search field.
All those is favor respond YES.

**Comment by AJLinn** [comment]
I would support this change - I think others have commented on the level of frustration resulting from hung searches and other unpredictable results?

I (and I'd say most of our users) almost exclusively use the ID box with match type "contains". It _would_ be nice if "contains" were the default match type though, as our users have to be told to use contains or they get nothing or many fewer than they should when they search object name strings.

**Comment by sharpphyl** [comment]
Perhaps make the instructions immediately visible as is done on the Search Taxonomy screen.  Now you have to click on **Any Taxon, ID, common name** to see the instructions.

<img width="522" alt="Screen Shot 2021-06-16 at 7 46 47 AM" src="https://user-images.githubusercontent.com/15368365/122230774-2b6e2180-ce77-11eb-8374-cf11cee18ac7.png">

**Comment by dustymc** [comment]
>species epithets are taxons

None of the 208 sources (including 14 locals that are probably biased) that this search considers provide data compatible with this statement - the search would have found something if they did. I don't see any problem with adding "specific epithet" to https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxon_term if it's useful and someone wants to manage it.

>use the ID box

Those are very different things which do not consider the same data and do not lead to the same records.

>hung searches 

Example? I'm not seeing much evidence of that in the logs.

>unpredictable results?

More example?

126222 searches used this field in the last year, 735 (half a percent) of them didn't find anything (those mostly include other criteria), of those around a dozen look like a CONTAINS search (or having epithet as a term) might have helped.

* chiricahuensis
* grunniens
* bunnelli
* quadrivittatus
* phaeoptila
* abeillei
* leucolia
* groenlandicus
* oeconomus
* innuitus
* broweri


In any case fancy indexes are now compiled, a ``contains`` search is now performing reasonably well (still much slower than a starts with) and the default could be updated, but balancing the usage data, available resources, and the cases where a specific epithet might lead where the user wants to go (for scale, there are about 5,000 taxa containing `vulgaris` in Arctos) I think @sharpphyl 's suggestion is probably the most reasonable path forward.

**Comment by dustymc** [comment]
Found different magic, contains is now about as fast as startswith, I'll leave the UI, update the docs, monitor the logs.
