### ISSUE TITLE
Arctos Ichnology

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3669]
@dustymc can you help me get all of the classifications in the Arctos Ichnology source?

**Comment by dustymc** [comment]
If you're loading from CSV they'll just get replaced - still want them gone?

**Comment by Jegelewicz** [comment]
Not gone, just want a download of what is there so that Adiel can review them.

**Comment by dustymc** [comment]
```
create table temp_ait as select taxon_name.scientific_name,taxon_term.* from taxon_name inner join taxon_term on taxon_name.taxon_name_id=taxon_term.taxon_name_id and source='Arctos Ichnology';
```
[temp_ait.csv.zip](https://github.com/ArctosDB/arctos/files/6670650/temp_ait.csv.zip)
