### ISSUE TITLE
bulkload attributes

### ISSUE THREAD

**Issue by bryansmclean** [ArctosDB/arctos#3670]
We (UNCG:Mamm) are still having issues with bulkloading attributes. Our situation is currently very simple, we tend to have 1-2 attributes beyond what is possible in the default data entry form.

I review records, load, wait until they are loaded, and the attempt to autoload all relevant attributes. And this message is received:
"autoload:catalog item not found"

<img width="516" alt="Screen Shot 2021-06-18 at 9 16 24 AM" src="https://user-images.githubusercontent.com/8601578/122566815-f946f600-d015-11eb-9fb4-283f3b9e1931.png">

**Comment by bryansmclean** [comment]
(Not related to #3413 as far as I can tell)

**Comment by dustymc** [comment]
What's the URL? That user doesn't have anything in the attributes loader.

**Comment by bryansmclean** [comment]
Sorry @dustymc do you mean a sample URL for one of the associated records?

**Comment by dustymc** [comment]
No, for the loader - I'm not seeing that where I think you're saying it should be and I can't know what's wrong without seeing the data.

**Comment by bryansmclean** [comment]
https://arctos.database.museum/tools/BulkloadAttributes.cfm?action=table&username=oschapman

**Comment by dustymc** [comment]
Ah, thanks! I don't have access to your collections so I'm not able to see that user's data in the first page.

I'm also not able to get to your records via the UI so it's difficult to diagnose what might have happened, but the UUID was reused for 24 records in some way.  https://arctos.database.museum/SpecimenResults.cfm?oidnum=9c3a3f4a-ff80-474b-9ff8-63127acc4f81&oidoper=IS should find them, assuming they're in collections to which you have access. If these were entered several months back when UUIDs were just otherIDs then it's likely from the user having that field set to carry and not checking the data. If it's recent (UUIDs are now their own thing) then I need more information and perhaps more access to your collections.

**Comment by dustymc** [comment]
@bryansmclean I found a bug that was probably causing this. The duplicate UUIDs now have a suffix in the bulkloader to make them unique and the hole is plugged. I'll get the corresponding UI patched in today (saving "extras" may cause errors before then).

I'm happy to do whatever I can to help recover the data that was affected by this, but unfortunately that's probably going to require revisiting the original. Let me know if I can help in some way.

**Comment by bryansmclean** [comment]
OK thats great to know. We can work on our end to add attributes to records we just buldloaded. Like I said, these are simple cases for now.

Just to confirm, we were getting duplicate UUIDs assigned during data entry. The fix corrects it at this front end, right?

**Comment by dustymc** [comment]
Yes, that's the situation. Two things have/will change:

1. UUID does not carry across, and 
2. The structure has been updated so a similar UI bug would throw errors instead of happily accepting/creating ambiguous data.

(1) should happen later today. (2) is running in production now, so the existing bug will at worst be annoying until I can get that patch out.

Thanks for the feedback and patience!

**Comment by dustymc** [comment]
I'll update the attribute loader as well, so UUIDs will form links in the review page.

**Comment by bryansmclean** [comment]
@dustymc we just tried a few test records again, and same result....

**Comment by dustymc** [comment]
What did you try? If data entry, there are no duplicates and that seems to be working. If loading, see https://github.com/ArctosDB/arctos/issues/3670#issuecomment-864171944 - the UUIDs in the specimen records are not unique, it's going to require manually chasing them down. If something else let me know and I'll help if I can.

**Comment by bryansmclean** [comment]
The latter - our sequence was 1) data entry, 2) record bulkload, and 3) attribute bulkload. 
3) does not appear to be working

I just want to clarify that fixing this bug is waiting for the next release. Is that correct? 
So until then, we should NOT use the attribute bulkloader for UNCG:Mamm?

**Comment by campmlc** [comment]
What does manually chasing these down require? We may need some help here
both to resolve and to prevent from happening again going forward.

**Comment by dustymc** [comment]
(3) won't work because (1) was broken.

It's all fixed now, UUIDs are being properly generated (and the table can't accept any that aren't), but there are still a bunch of records which share a UUID (link in https://github.com/ArctosDB/arctos/issues/3670#issuecomment-864080072) and the bulkloader is never going to be able to work without a unique identifier.

>What does manually chasing these down require?

You could conceivably update the IDs in the catalog record and bulkloaders - the values don't matter, as long as they're unique - but it's probably easier to pretend that those data were never entered and just enter them in the individual records.

**Comment by bryansmclean** [comment]
We did the latter, for the records on which my first post was based.

However, the same issue happened yesterday with a new round of test records. 
Attributes for those test records ended up in the attribute bulkloader WITHOUT unique IDs. 
So Im wondering whether the issue is actually fixed (which is what I assumed)?

**Comment by dustymc** [comment]
OK, I think I see what's going on, working on a solution now....

**Comment by dustymc** [comment]
I patched a fix in, please carefully test.

**Comment by bryansmclean** [comment]
Finally able to review a new set of test records. 
Prior to testing again with those records, maybe it helps to make sure all looks good on our end.

For a set of 5 test records, only 1 has a UUID in the bulkloader

![image](https://user-images.githubusercontent.com/8601578/123288124-470fa280-d4dd-11eb-815a-12026bfef57f.png)

And a reciprocal search from the attributes bulkloader only links back to one record. 

Does it sound like the patch is working?

**Comment by dustymc** [comment]
It looks right to me - the "linked to bulkloader" record in https://arctos.database.museum/tools/BulkloadAttributes.cfm?action=table&username=oschapman is linked to a single record in the bulkloader.

```
arctosprod@arctos>> select count(*) from bulkloader where uuid='ac0aa3bb-ec59-4e16-bdeb-f983b33d2bb8';
 count 
-------
     1
(1 row)
```
and that identifier isn't used elsewhere

```
arctosprod@arctos>> select * from coll_obj_other_id_num where display_value ='ac0aa3bb-ec59-4e16-bdeb-f983b33d2bb8';
 collection_object_id | other_id_type | other_id_prefix | other_id_number | other_id_suffix | display_value | coll_obj_other_id_num_id | id_references | tempref 
----------------------+---------------+-----------------+-----------------+-----------------+---------------+--------------------------+---------------+---------
(0 rows)
```

**Comment by bryansmclean** [comment]
OK I agree.
I guess my question now is why all records sitting in the bulkloader dont have UUIDs?

**Comment by dustymc** [comment]
It should be because they didn't get "extras" added. If not I'll need enough information to replicate.

**Comment by bryansmclean** [comment]
Two more record sets do not have UUIDs being consistently applied to them. 
This seems to be happening when we enter a record, then enter a new record via cloning. A new UUID is not generated.

Im currently working within these accessions:
UNCG:Mamm_2020_August_30_ColdMountain
UNCG:Mamm_2020_August_30_ColdMountain

Wondering if this behavior is due to the patch?

**Comment by dustymc** [comment]
A UUID is only generated when you add "extras."

**Comment by bryansmclean** [comment]
OK thanks - I think our issues came from the fact that "extras" are not carried over when cloning.
Is that correct?
