### ISSUE TITLE
Feature Request - do more with GloBI

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3672]
**Is your feature request related to a problem? Please describe.**

Records get various interactions noted in text ("verbatim host ID", "associated species", "habitat", etc.), it's hard to do much with that. "Mustela vison" in some text field is not accessible via "Neovison" (updated taxonomy), "mink" (common name), "Mustelidae" (higher taxonomy), or anything else that a more sophisticated structure can expose.

**Describe what you're trying to accomplish** 

Get answers to questions involving multiple objects/taxa/etc. "What parasitizes catfish?"

**Describe the solution you'd like**

GloBI ( @jhpoelen ) is now digging interaction data out of strings. (See https://github.com/globalbioticinteractions/unl-nsm/issues/4#issuecomment-864147364 and https://arctos.database.museum/guid/HWML:Para:49529 for example.) We should somehow do more with that - pull it into the Arctos view, use it to query, add explicit relationships, just send "interaction traffic" to GloBI, ?????????????????

**Describe alternatives you've considered**

Use Host collections and explicit relationships.

**Additional context**

Proposal time? I think there's a LOT of room for collaboration.

**Priority**

Someone would need to take the lead on any further collaboration, priority and direction could be established then.

**Comment by campmlc** [comment]
Happy to do a call regarding next steps -but am traveling through end of
June.

**Comment by jhpoelen** [comment]
@dustymc much like the idea of increased GloBI<>Arctos integration/collaboration! Please let me know what you come up with, happy to help facilitate.

**Comment by Jegelewicz** [comment]
> Use Host collections and explicit relationships.

I think this is the best possible solution and I think we should think about hosting a generic host observation collection that could hold magic records created with the same method @jhpoelen is using.

Any Arctos object record with "verbatim hostID" and no "parasite of" relationship generates an observation record with the same event/locality, identifier(s) and collector(s) as the parasite, with an identification = the verbatim hostID (use A{string} if the name is not in Arctos) and ID by whoever is determiner in the "verbatim host" attribute. A part should be created "unknown" with disposition missing. Then this observation is linked to the parasite with the "parasite of" relationship.

This will help ensure that we aren't doing things two different ways. Currently, anyone wishing to find all the parasites with host of blah have to search relationships and verbatim host ID. Not ideal. If you only had to search relationships, it would be much better and eventually much richer.

**Comment by dustymc** [comment]
>magic records

I think that's clearly better, but it also requires more resources.

>find all the parasites with host of blah 

That also seems like a good place for some collaboration to me. What's an ideal "interaction search" look like? Maybe not much like a good curatorial search, IDK.

**Comment by Jegelewicz** [comment]
Which kinda gets us back to UI? Instead of "search anything" the way we do it now, maybe the fist page should be "what are you interested in searching for?" with search pages more customized to the item(s) of interest. But that sound like a grant....
