### ISSUE TITLE
citation bulkloader not loading?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3673]
Records for cscarr were set to autoload over 5 hours ago. Is this a normal delay?

**Comment by dustymc** [comment]
It was stuck, I gave it a jiggle.

You can check the status here:

<img width="340" alt="Screen Shot 2021-06-21 at 7 02 50 AM" src="https://user-images.githubusercontent.com/5720791/122775208-bf1c6500-d25e-11eb-8f09-258b932da63c.png">

The simplest way to interpret that is SOMETHING should be changing every minute-or-so.
