### ISSUE TITLE
Code Table Request - Add Kansas City Group

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#3680]
**Goal**
Add the Kansas City Group to the Lithostratigraphic Group code table

**Context**
Kansas City Group is not in the code table. It exists and is used by a locality I need to enter ([https://en.wikipedia.org/wiki/Kansas_City_Group](https://en.wikipedia.org/wiki/Kansas_City_Group))

**Table**
[https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlithostratigraphic_group](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlithostratigraphic_group)

**Value**
Kansas City Group

**Definition**
[Wikipedia](https://en.wikipedia.org/wiki/Kansas_City_Group)

If there are no objections I will add it to the code table.

**Comment by Jegelewicz** [comment]
Looks OK to me

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Definition: A Late Pennsylvanian unit in the midwest (from [Geolex](https://ngmdb.usgs.gov/Geolex/Units/KansasCity_9038.html))

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Added
