### ISSUE TITLE
Alternate entity name error

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3684]
Attempting to add an alternate entity name of

> UTEP:Ento:Lot Mackay Access No 6084

and I get this error

![image](https://user-images.githubusercontent.com/5725767/123493363-6be94000-d5d9-11eb-8e9b-8a364362a31b.png)

Do alternate names have to be numeric?

**Comment by dustymc** [comment]
Patched, I think.

**Comment by Jegelewicz** [comment]
Thanks - did we talk about also magic-ing in other IDs when an entity gets created? For this bunch I created a new kind of entity (lot) and it feels like adding these to the entity should generate the "lot" ID in the associated records. Of course, we don't currently have an other ID "lot" sooooo

Anyway, I'm quitting for the day - I'll think on it.
