### ISSUE TITLE
Feature Request - Use Manage in search results to add all results to an entity

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3685]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
today I wanted to add the records in the results of [this search](https://arctos.database.museum/SpecimenResults.cfm?oidtype=other%20identifier&oidnum=Mackay%20Access%20No%206084) to [a new "lot" entity](https://arctos.database.museum/entity/3) - the only way I could see to do it was to copy and paste the GUIDs into the entity form.

**Describe what you're trying to accomplish** 
Make it easy to add records to an entity

**Describe the solution you'd like**
It would have been great to use the Manage function to add them all to the entity or even to create an entity from the results.

**Describe alternatives you've considered**
Copy and paste or perhaps an entity bulkloader.

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by dustymc** [comment]
I can't understand what you're doing here. Lots are going to be cataloged, why is a different kind of data object necessary for some of that? This just looks like arbitrarily doing two things for one situation, and that's never good design. https://github.com/ArctosDB/arctos/issues/1966#issuecomment-832839040 would have provided a path to doing more with certain types of cataloged items - it's not too late to back up....

**Comment by campmlc** [comment]
I support Teresa's request. It is a simple and uncomplicated means of
dealing with entities. We need to make the workflow easier, and this would
allow that. I don't see the problem.

**Comment by Jegelewicz** [comment]
> Lots are going to be cataloged.

This is a case of legacy stuff skipping a step. There was a lot, but it was never cataloged. UTEP got a grant to digitize ants and the individuals were cataloged with their lot number and relationships of "same lot as". This is a pain because there are 18 individuals cataloged from this lot, meaning all 18 records need 17 other identifiers with the "same lot as" relationship if they are to be found that way. (In reality, this is true of any lot, I think)

After creating an entity to summarize these guys, I figured out that I could get them all easily using the other identifier that is the "lot number":

![image](https://user-images.githubusercontent.com/5725767/123709861-fbd1f880-d82a-11eb-8afc-d59ca26a90b2.png)

 So, just thinking about a "lot" there are multiple issues here.

1. If one catalog record from a "lot" gets a georeference - we would like to have that update other members of the lot. I think this would be true for any lot, but maybe there is a time we wouldn't want to do this?
2. Above is possibly NOT true for identifications as lots could be mixed taxa, however, if the lot is NOT mixed, perhaps the ability to update the identification for all records from a lot would be nice too.
3. We need "best practice" for lots because maybe UTEP should have cataloged the lot then "subsampled" to create the individual components of the lot, but even if they had - we would be butting up against the "one million reciprocal relationships" issue.

I was hoping to avoid all of the relationships by using an entity, which lets me see easily that all of the records in this lot share an ID and some identifiers, which in this case is expected and makes me feel good.

![image](https://user-images.githubusercontent.com/5725767/123710746-7fd8b000-d82c-11eb-9252-9a838374ef45.png)

It also made me see that another good component of an entity would be locality and event because for a lot, they should share one.

So, perhaps an entity is NOT useful for a lot, but I don't think we have something really useful without an entity either. In this case, I can find everything in the lot with an other identifier number and ideally that would be true for any lot. Nice to find everything, but it means active searching to see if one record out of a lot has been changed which might mean other records need a change too. This is unlikely to happen and over time I could see how individual records from a lot could end up with different information when there should not be different information. Maybe a new kind of "low quality data" is records with matching other identifiers but mismatched locality and/or identification? Sometimes this would generate false positives, but maybe we could handle that?

This was me thinking out loud - sorry if any of it seems nuts.

**Comment by dustymc** [comment]
>So, perhaps an entity is NOT useful for a lot, but I don't think we have something really useful without an entity either. 

https://github.com/ArctosDB/arctos/issues/1966#issuecomment-832839040 - we have a data object which seems to meet the needs.

>avoid all of the relationships 

I don't think an Entity (of any form) changes that much - it's just one more relationship, no? And instead of a report I could (probably - The Community would need to buy in) just make those, at least if I had more metadata available (eg a way to keep the assertions separated from autogenerated reciprocals).

>reports

I'm not sure any lot can really be expected to be as homogeneous as we pretend they should be (or no taxa traditionally cataloged as lots contains cryptospecies?!), but reports generally aren't difficult to write. 

>georeference - we would like to have that update other members of the lot.

Named localities make that hard to avoid.

>maybe there is a time we wouldn't want to do this?

Yes, I think so - the lot is "that river, this week" and with lots of detective work you get something better for a few of the alleged guppies or something - that sort of thing should not turn into an annoyance. (In other words, reports are often deceptively difficult to design, but the writing's usually easy enough!)

>update the identification for all records from a lot 

Search/Manage/IDs.

>We need "best practice" for lots

https://handbook.arctosdb.org/documentation/catalog.html#understanding-cataloged-items

If this is (accidentally or on purpose) close to what @DerekSikes does, there may be no/little reason to catalog the lot at all - if it was an item of convenience then nobody should care once it's recataloged as individuals. If it was (or might have been) loaned or cited then it probably does need cataloged (or "entity-ified," which I still believe is best accomplished via cataloging - eg that provides a place for things like http://test.arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#maximum_standard_length).

**Comment by Jegelewicz** [comment]
> An occurrence (e.g., each instance of the capture of an individual)
> 
>     This situation inevitably leads to confusing citations and bad science when an individual sampled multiple times at multiple locations is assumed by users to be multiple distinct individuals. Arctos supports cataloging encounters as specimen events under one cataloged item.
> 

All I can say to this is UGH! There is no real way to differentiate which parts came from which events and even with our duct tape method no way to associate parts with their appropriate accession. I DO NOT think this should be recommended.

**Comment by Jegelewicz** [comment]
> Your “share” of an individual (e.g., tissues; the bones being cataloged elsewhere)
> 
>     Similar to occurrences in that this leads to multiple identifiers being assigned to an individual (and potentially the two being compared in a study), this should be avoided when possible. When unavoidable, both systems should support resolvable identifiers and link to each other, and specimen downloads should include the relationship. Arctos also adds a distinctive style to “same individual as” specimens.

HAHAHAHAHA! "this should be avoided when possible"

I also dislike this recommendation

**Comment by Jegelewicz** [comment]
> we strongly recommend cataloging the item of scientific interest: the material that Researcher #2 will ask to borrow for confirmation when they find your citations in GenBank or publications.

Wouldn't that be the liver in some vial? Isn't that the "item of scientific interest"?

**Comment by dustymc** [comment]
There's nothing duct-tapey about the part link, it's a key like everything else, but the administrative data still seems to be a controlling factor for some users. 

There are functional implications to cataloging not-individuals - someone's going to muck up citations or something. Maybe we need to change the recommendation, but we should try to mitigate the effects somehow.

Can you provide an example of this "we looked at some liver, and we don't really care where it came from" paper? I can't find a single publication with citations in Arctos that doesn't hinge on the idea of the individual as representative of a taxon. 

I'm also struggling to find anything that might consider 'same critter, different time' data. Surely that actually exists, but I can't find an example. Are we building data structures to pure theory, or is there some actual user (who might guide the development) out there somewhere?

**Comment by Jegelewicz** [comment]
Here is the deal - when I read all of those recommendations, it seems that the "item of scientific interest" is assumed to be a "biological individual" but the system isn't really set up to do that well unless the individual is only "collected" once and then kept together forever. We have duct tape to make multiple "collections" and "division of the individual" work - other ID relationships and links between parts and events, but they obviously aren't working well, or we wouldn't be having this discussion.

As a collection manager - my concern is with the things we have - where they are and how they are used. The material is of utmost importance. All of the other information - identification, event, locality are important, but they are just information associated with the thing I am trying to keep up with. Centering a collection management system on biological individuals doesn't help me to keep up with all of the things that might come from any given biological individual (which are infinite). This is what we are running up against - natural history collections have historically cataloged "biological individuals" which was fine for a while, but seems to be increasingly problematic as the biological individual gets parsed out over space and time or as biological individuals are collected in stages over their lifetimes. I think we need to take a critical look at how we view "item of scientific interest" vs. "I need to know where things are and who used them for what". Organism IDs seem to make the most sense to me to help us do both better.

**Comment by Jegelewicz** [comment]
> I'm also struggling to find anything that might consider 'same critter, different time' data. Surely that actually exists, but I can't find an example. 

@campmlc has a perfect example where a researcher was looking at hormones for different stages of an animal's life, so the time factor was very important.

I could also see this for looking at environmental toxins, viral loads, etc. over time.
