### ISSUE TITLE
extra blank column in bulkload template csvs after container barcode header

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3686]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
The downloaded templates for various bulkload templates have an extra column with no header following the container barcode header. This creates problems for management in Excel because the blank column is not obvious but if not corrected it will cause major problems in upload and also if the spreadsheet is sorted.

**To Reproduce**
1. Go to https://arctos.database.museum/tools/BulkloadParts.cfm?action=ld for example, but others also
2. Click on  Get a template
3. Open template csv
3. Scroll over to container barcode column
4. See blank adjacent column to right

**Expected behavior**
For there to be no extra blank columns embedded anywhere in the template csv

**Desktop (please complete the following information):**
 - Chrome

**Priority**
High- could cause serious hair loss and teeth gnashing due to difficulty loading or undetected data mismatches

![Screenshot 2021-06-27 10 23 49](https://user-images.githubusercontent.com/14808196/123552095-d4e3cb80-d731-11eb-9711-e2734847213d.png)

**Comment by dustymc** [comment]
patched
