### ISSUE TITLE
Cyberduck connection question

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3688]
Trying to connect to TACC via Cyberduck and it keeps timing out. I think it is because I need to know the path:

![image](https://user-images.githubusercontent.com/5725767/123835272-941cbb80-d8c5-11eb-9523-a1210d75d636.png)

There are no instructions for this in the HowTo. Can anyone help me out?

**Comment by dbloom** [comment]
@Jegelewicz  Everyone must find their own path. To find yours you must calm your mind and become one with the world around you. Only when you have embraced the wisdom that there is only one data point will you find the true path to TACC.

**Comment by dustymc** [comment]
I don't know how cyberduck interprets things and your permissions/defaults will be different than mine, but your default path should be /home/{username} and the upload slice is /corral-tacc/projects/arctos.

You should be able to ssh in and look around if that's easier for you.

You should coordinate any uploads with Chris - that hardware is going to go away "soon" (I'm not sure what precisely that means).

**Comment by Jegelewicz** [comment]
@dbloom I love you man....

**Comment by Jegelewicz** [comment]
> You should be able to ssh in and look around if that's easier for you.

HAHAHAHA! You act like I know what that means...I'll see if I can follow their instructions.

**Comment by Jegelewicz** [comment]
Yeah, no - I have no idea what to do and maybe

> that hardware is going to go away "soon"

was sooner than now? All I know is following the instructions in the HowTo for Cyberduck time out. Is anyone else uploading images who can give me better instructions? I'm talking hundreds of images.

**Comment by Jegelewicz** [comment]
See also https://github.com/ArctosDB/documentation-wiki/issues/200

**Comment by Jegelewicz** [comment]
It was MY firewall!!! HAHAHA!
