### ISSUE TITLE
User role?

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#3689]
I'm trying to figure out what [user role](https://arctos.database.museum/Admin/user_roles.cfm) I need to grant my student to be able to edit identifications, including the taxonomy.
<img width="1071" alt="Screen Shot 2021-06-29 at 8 39 23 AM" src="https://user-images.githubusercontent.com/17605945/123843969-edcdb780-d8be-11eb-9d3b-e1aa40083532.png">

While doing data entry I noticed he had made a few taxonomy assignments that I'd prefer to be adjusted. I thought it would be easier to edit in the catalog record view (above) so he could see the hierarchy from the editor view. But he's getting an error when he tries to edit the existing ID.

![64667699279__61F3C2E7-370E-47E0-B673-08DCD3C97BB4](https://user-images.githubusercontent.com/17605945/123844184-2ec5cc00-d8bf-11eb-8488-0e7028bbbf6f.jpeg)
I'm supervising remotely at this moment so he tells me that he's following the step I'm showing him. What role should he be granted in order to make this adjustment in the catalog record? Is that under manage_record access?

Looking for some advice. I'm about to go to the museum so I can make sure he's following the proper steps but wanted to throw this out there to our collective wisdom first.

**Comment by Jegelewicz** [comment]
I think they need manage_specimens

**Comment by Jegelewicz** [comment]
which - ouch, should be changed to manage_records or something like that for the non-biological collections....

**Comment by AJLinn** [comment]
they have that already. Here's what they have:
<img width="264" alt="Screen Shot 2021-06-29 at 9 59 36 AM" src="https://user-images.githubusercontent.com/17605945/123845489-b829ce00-d8c0-11eb-8588-3f2f884f2c6f.png">

**Comment by Jegelewicz** [comment]
Have they signed out and back in since access was granted?

**Comment by dustymc** [comment]
Manage specimens allows insert and update on identification.

Manage collection allows delete on identification.

Manage taxononomy allows full taxonomy (not identification) access.

**Comment by AJLinn** [comment]
Thanks @dustymc I'm headed to the museum so will see what he's actually doing and see if we're miscommunicating over text message

**Comment by dustymc** [comment]
> changed to manage_records

That's something different, you suggested it. https://github.com/ArctosDB/arctos/issues/1721#issuecomment-859682772

**Comment by Jegelewicz** [comment]
OK, well it needs a different name because of the de-specification we have been trying to get done...maybe manage_object

**Comment by AJLinn** [comment]
Could Arctos be thinking of our edit process as a "delete identification" since we don't just add a new one and are overwriting the incorrect? So I'd need to give him manage collection in order to do that? Seems like he was able to add a new one, just not fix the incorrect one.

**Comment by dustymc** [comment]
I'd need more information to say anything useful, but I don't think there's any UI that allows changing the taxa used in an ID (except maybe A {string}).

**Comment by AJLinn** [comment]
We use the A{string} and just overwrite the existing taxa, then update the IDed by agent (see my screen shot above) - we don't typically keep past IDs unless there is a compelling reason to show multiples because of being unsure or an item has multiple categorizations.

for the sake of this particular circumstance and having my student fix errors that occurred in the data entry process, what role should they have to be able to do the edit ID task as seen in the screen shot - manage collection?

**Comment by dustymc** [comment]
See http://test.arctos.database.museum/Admin/user_roles.cfm?action=defineRole&role_name=manage_collection

Manage_collection has DELETE on identification_taxonomy.
