### ISSUE TITLE
Arctos isn't saving my searches

### ISSUE THREAD

**Issue by atrox10** [ArctosDB/arctos#3690]
This is happening in searches I make while logged in as me (atrox) in Chrome. I do a search and then I hit the save search and nothing happens. The window to save and pick a name doesn't show up and the search isn't saved on My searches.
For example I was searching on MVZ Herps, Taxonomy = Anaxyrus and Locality  = Yosemite. I got multiple results but can't save the search.
But this has happened multiple times for me, with other searches in Chrome.
I was able to get it to work by logging into Safari on Arctos and redoing the search and then it saved.

**Comment by dustymc** [comment]
https://arctos.database.museum/saved/1625061291065

Works fine for me in FF and Chrome, that's usually some extension or setting gone off the rails.

**Comment by mkoo** [comment]
@atrox10 Can you please try again and see if all the recent updates and changes have resolved this?
