### ISSUE TITLE
data entry screen

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3691]
**SABI Goal**
Collection-specific consultation of bulkloading and searching tools (i.e., Earth Sciences, Genomics, etc)

Sorta from https://github.com/ArctosDB/arctos/issues/1460, but the idea has been around for a while: Can we split the data entry screen into two components?

1. Something like (perhaps exactly like) the current screen, which allows customization and etc., and serves purely as an input mechanism (all entry, no edit), and
2. A second static (everyone sees everything) edit screen, which is incapable of creating new records

The current screen does both, which adds a great deal of complexity to the code and the user environment. Two dedicated screens would (probably, I hope) be simpler to manage, and I suspect use.

**Comment by Jegelewicz** [comment]
Sounds like a good idea. Data entry can be customized, but reviewers get to see it all?

**Comment by dustymc** [comment]
"get"-->"need" but yea, there's a bunch of complexity around trying to make that happen now, I'm not sure it always works as it should.

A dedicated edit screen might also open up a more integrated way to see "extras."

**Comment by Jegelewicz** [comment]
Make the parts section look like part extras does now? and build a "dynamic" bulkload builder that lets you get n number of parts with x number of attributes each in the template?

See #3764 and #3758

**Comment by dustymc** [comment]
And https://github.com/ArctosDB/arctos/issues/3748

Maybe we should try the 500-column approach and just add some number of attributes to each part in the core bulkloader, then build the new UIs around that?

**Comment by Jegelewicz** [comment]
Whatever works best for you. Let's see what the community says when they see it...

**Comment by Jegelewicz** [comment]
SABI Goal:

Collection-specific consultation of bulkloading and searching tools (i.e., Earth Sciences, Genomics, etc)

**Comment by campmlc** [comment]
Not sure if this is possible, but it would be super cool if we could go
into the data entry page and click on fields for data that we could then
download as a bulkload template. Currently, the bulkload builder is
unwieldy and incomprehensible to folks who don't know what the data fields
are. And it is complicated by the fact that the bulkloader column headers
do not match the names of the fields in data entry. But the data entry page
is much more comprehensible, so someone could click on the fields they want
plus the fields that are required and get a customized bulkload template. ?

**Comment by dustymc** [comment]
AWG meeting:

 default should be minimal, add when needed rather than removing

customize button should be more unavoidable

**Comment by ewommack** [comment]
Suggestion that during the AWG Issues meeting -> put more Add More Buttons around the Data Entry screen.

Put one at the attributes, put one at the parts, put one at the identifiers, etc.

**Comment by ewommack** [comment]
But also still dealing with Issue #3764

**Comment by dustymc** [comment]
Handle dependencies better: https://github.com/ArctosDB/arctos/issues/3900

"or maybe: kill 'customize' altogether, expand/contract individual panes (so see all or none of eg attributes or parts)" (https://github.com/ArctosDB/arctos/issues/3691#issuecomment-911925764) would handle this by setting the state for entire "panes."

**Comment by dustymc** [comment]
In the current screen, it's possible to add an "extra", save that, then exit the main screen without saving, which does not save the UUID in the bulkloader and therefore orphans the "extra."

Easy and robust but probably unacceptable (see https://github.com/ArctosDB/arctos/issues/2240) solution: create UUIDs on INSERT, then they're impossible to avoid.

Less-easy and less-robust semi-solution: be more aggressive about saving UUID before creating extras.

**Comment by dustymc** [comment]
There's a new edit screen in test. It's nothing too groundbreaking, just the old combined screen's edit mode stripped down and simplified, but it does have an "extras" summary included. I'll leave it linked alongside the old screen (currently as 'new edit') from browse-and-edit until the new entry-only screen is developed.

<img width="341" alt="Screen Shot 2021-09-07 at 11 10 33 AM" src="https://user-images.githubusercontent.com/5720791/132391256-c3216fb9-4de8-4540-9d0b-58f35c61b47a.png">

**Comment by dustymc** [comment]
There's a new data entry screen available. It's fully functional, but I'm still adjusting minor (I hope!) details. I think it's to the point where feedback would be useful.

Note that this is a single-mode screen: It creates records in table bulkloader, nothing else. There is no "it saved but you need to edit it or you can just close the window and deal with the giant mess later" option - records which meet the bulkloader criteria save (and then may be edited from the accompanying single-purpose edit screen - a link is created on successful save), those which don't pass the check are rejected. I am sure that this is a more straightforward and intuitive approach, but it's **different** and some adjustment pains should be expected.

Along with setting a status message, a successful save briefly turns the screen green(ish), a fail red, and a fail will result in an error in a popup.

http://test.arctos.database.museum/enter_data.cfm, or find anything in the grid view at test and "[ enter from seed ]."

It's capable of being very dense. There have been complaints about how the old fixed-column customization interacts with various screen sizes, so this has no constraints. Here's (about) the entirety of the old screen on about 2/3 of my little laptop screen:

<img width="1341" alt="Screen Shot 2021-09-16 at 8 28 35 AM" src="https://user-images.githubusercontent.com/5720791/133641051-39c58da2-afc8-49c4-9f39-fe7b3fa518fb.png">


It's capable of handing "extras" inline (and https://github.com/ArctosDB/arctos/issues/3436#issuecomment-912005715 will make that more seamless for those collections/users that want it to be). So far this is only implemented for parts. The current limits are 20 parts (completely arbitrary number that's easy to change) each with 6 attributes (the limit of the bulkloader - "easy" but not "trivial" to change). 

Both options for comparison. This way is functional, but potentially confusing - highly recommend picking one and sticking with it. (The mix-n-match option will be important for things like identifications, where the primary loader must be supplied with data, but probably should be avoided where the "extras" handler is capable of handling everything.)

<img width="670" alt="Screen Shot 2021-09-16 at 8 33 14 AM" src="https://user-images.githubusercontent.com/5720791/133641532-0e215497-3729-4397-b7b2-d05f6985b399.png">

Note that the new/developing edit screen displays "extras" as well.

<img width="619" alt="Screen Shot 2021-09-16 at 8 37 59 AM" src="https://user-images.githubusercontent.com/5720791/133642394-3318a22c-a374-48f9-a9b2-24f5faa825ce.png">

becomes

<img width="640" alt="Screen Shot 2021-09-16 at 8 38 55 AM" src="https://user-images.githubusercontent.com/5720791/133642441-d9b18213-dac0-44bd-bc8d-f62de79e3548.png">

and the loader is a click away

<img width="1141" alt="Screen Shot 2021-09-16 at 8 39 48 AM" src="https://user-images.githubusercontent.com/5720791/133642564-23f61242-1c66-4848-95d8-ff68d75376b2.png">

It's capable of being very minimalistic. This is a viable customization and somewhat realistic view, and everything can carry (there's a distinctive style applied to "carry" elements) so using this might involve adding data to 2 or 3 fields.

<img width="1312" alt="Screen Shot 2021-09-16 at 9 53 14 AM" src="https://user-images.githubusercontent.com/5720791/133653449-b07ad4c2-ff5a-451e-ba2c-d96b4dcd160e.png">

There's a noncustomizable (positioning - elements can still be customized) "table" view for anyone who can't be bothered to customize (or maybe is using a giant screen). This is about the same situation as the old screen.

<img width="1335" alt="Screen Shot 2021-09-16 at 10 06 46 AM" src="https://user-images.githubusercontent.com/5720791/133655343-305eb17e-2810-4f9f-91b5-87ee660547fd.png">


Points from the AWG meeting (and above):

* default should be minimal, add when needed rather than removing

It's sorta not, but that's easy to change (but requires flushing saved settings, so should be worked out ASAP) - feedback greatly appreciated, what should the initial load look like? The current reasoning is that "I don't use this, maybe the nearby customize button can make it go away" is more accessible and intuitive than "I really need {element} but I can't find it." (And existing data suggest that's often followed by "oh well, I'll just use some arbitrary remark field.")

* customize button should be more unavoidable

I think it is, there's one on every "node"

* or maybe: kill 'customize' altogether, expand/contract individual panes (so see all or none of eg attributes or parts)

Didn't go this way - lots of collections don't need 12 parts (or whatever), there's no need to make them look at it. That is, I'm favoring "customization" over "easy setup."

* show only populated values (possible??)

I have no idea how this might work in an app where the point is to make something from nothing!

* better name for "random junk"

OK

* 'add more' goes to each pane, widget goes away

See above

* move everything to 'extras' - in browse-and-edit, allow load core OR load also extras

See above, just add whatever's needed.

**Comment by AJLinn** [comment]
A couple comments/questions from my perspective:
<img width="607" alt="Screen Shot 2021-09-17 at 7 39 19 AM" src="https://user-images.githubusercontent.com/17605945/133819250-c522793e-c372-4c49-857e-c92a15e66105.png">

<img width="882" alt="Screen Shot 2021-09-17 at 7 40 54 AM" src="https://user-images.githubusercontent.com/17605945/133819278-dbdcad6b-712c-4591-8eb0-6d8010412725.png">

<img width="714" alt="Screen Shot 2021-09-17 at 7 43 43 AM" src="https://user-images.githubusercontent.com/17605945/133819299-75c2ceff-46fe-4fd9-8b14-72c67f5bb374.png">

I'll keep poking to see what I like/don't like.

**Comment by dustymc** [comment]
Customize and scroll right
<img width="477" alt="Screen Shot 2021-09-17 at 9 06 33 AM" src="https://user-images.githubusercontent.com/5720791/133819624-018b0368-ad0c-434d-91ca-9dfc12a0ebcc.png">
<img width="711" alt="Screen Shot 2021-09-17 at 9 06 41 AM" src="https://user-images.githubusercontent.com/5720791/133819635-b472f097-c2a8-43e5-8a45-fd7f536b92f8.png">

**Comment by dustymc** [comment]
Catnum is bigger

We had all textareas with a .3em margin - I removed that, hopefully it wasn't there for a reason....

reload

**Comment by mkoo** [comment]
The only thing I liked about the old one was the pleasant green
background-- so this is an improvement all around!

A few things:
please spell out fields as completely if possible. Example: change "Cat Itm
Typ" to "Cat Item Type" at least or "Catalog Item Type" if it can fit
Also the full name of Accession can fit!

I like "Extras" Parts but might be more helpful if called " "Extras" Add
Part Attributes "

I'll keep poking around, but I would like to use this ASAP!
Thanks, MK

**Comment by dustymc** [comment]
>if it can fit

That's the question! The answer is different on about every browser. They're more verbose now, still fits for me...

>Extras" Add Part Attributes "

It's not just that - you can also use it to add 20 (or 5000 with a very minor change) parts without attributes, and it adds "part with attribute" as a whole, it doesn't add attributes to the other part-thing. I don't much care what it's called, just want it to be clear. (And I've been throwing "extras" around for a while - it's part of **my** vocab now but maybe not anyone else's??)

I do intend to add other "extras" - IDs and etc. - on this form, if that somehow influences the vocabulary.

**Comment by Jegelewicz** [comment]
Will the "extras" be going through the various bulkload tools? How about "Bulkload Tool Extras"?

Whatever we call it, I think the key is to document well how they work and what each one does. Newcomers (all of us at first) will need to get used to it, but I think once you've used it once or twice, it will become familiar.

**Comment by dustymc** [comment]
>Will the "extras" be going through the various bulkload tools? 

Yep, same as always, just slightly different UI.

>"Bulkload Tool Extras"

Seems a little redundant to me but whatever.

>document

Yes - but after https://github.com/ArctosDB/arctos/issues/3436#issuecomment-912005715 (which I hope to get to soon, but I'm probably about to get pulled in another direction).

**Comment by sharpphyl** [comment]
Overall, a big improvement and I expect our data entry volunteers to like it.  Really like the ability to customize each section.  Since the "delete row" is the very last column on the "customize" screen, can you add a second "SAVE SETTINGS" button there?  Or maybe that should be the first column.

I miss the previous distinction between the Specimen Event, Collecting Event and Locality even though they are all Place and Time.  If there aren't going to be sections, can you use Collecting Event Name instead of just Event Name and Collecting Event ID instead of just Event ID?   Also, Verbatim Locality, Date, Higher Geography and other mandatory fields were highlighted in yellow in the previous version which gives visual structure to that section.  If mandatory, can they be highlighted as before?

Can we spell out words whenever possible.  It looks like there's enough room to say "Use Verbatim Location" and "No verbatim locality recorded." instead of "UseVerbLoc" and "No...recorded", etc.

<img width="207" alt="Screen Shot 2021-09-20 at 8 32 34 PM" src="https://user-images.githubusercontent.com/15368365/134102995-8bbe0c71-c5b5-474b-8746-76e50e1bbe3c.png">

Will you be adding links to documentation?

I would put the Tools at the bottom where you save the record instead of halfway through the data entry screen.

Please increase the space available for the specimen count (regardless of issues with count [#3908](https://github.com/ArctosDB/arctos/issues/3908)).  We can have hundreds of specimens in a lot and you can only see the first number in the data entry screen.  

<img width="221" alt="Screen Shot 2021-09-20 at 7 34 02 PM" src="https://user-images.githubusercontent.com/15368365/134100425-84efcdab-f175-44e6-85d4-04ac428bee9e.png">

When you edit the record you see the full number entered.

<img width="223" alt="Screen Shot 2021-09-20 at 7 43 32 PM" src="https://user-images.githubusercontent.com/15368365/134100618-466153ac-eaab-4584-aa5f-67a9fe85cf1f.png">

Can we also use the same term everywhere?  In the data entry, it's #.  

<img width="31" alt="Screen Shot 2021-09-20 at 8 01 04 PM" src="https://user-images.githubusercontent.com/15368365/134100767-6b19fe0f-9ce3-4a70-9a11-d01ee6142295.png">

When you customize this section it's LotCount (header) or Part_Lot_Count (column).

<img width="204" alt="Screen Shot 2021-09-20 at 8 00 09 PM" src="https://user-images.githubusercontent.com/15368365/134100742-63c28e8c-f297-466c-9a4c-a142120fb108.png">

In the final catalog record, it's Qty.

<img width="104" alt="Screen Shot 2021-09-20 at 8 02 25 PM" src="https://user-images.githubusercontent.com/15368365/134100851-ee68eb6e-b8df-4e8a-abf0-1ca16c097da0.png">

Having the exact same term in every place - data entry screen, bulkloader, catalog record and handbook is really helpful for our volunteers as well as for me.  Just as an example, here's Customize Catalog Item Data.  The items to customize should be in the same order and with the same headings: Accession, Catalog Number, Catalog Item Type, etc.  Instead they start with cat_num, accn, etc.  

What are "flags"? or is it Missing?  

Are coll_object_remarks the same as Specimen Remark?  If so are they the Specimen Remarks under Attributes or something else?

<img width="664" alt="Screen Shot 2021-09-20 at 8 15 02 PM" src="https://user-images.githubusercontent.com/15368365/134101745-edb7dd67-f537-4ca3-85b0-d5fdd23228ac.png">

If you want an edit for consistency, I'm happy to do that.  

I can't find "Add more" and we often need to add a second identification.  

<img width="311" alt="Screen Shot 2021-09-20 at 8 50 46 PM" src="https://user-images.githubusercontent.com/15368365/134104435-18d88055-d566-4d32-b031-0b1543cef192.png">

**Comment by dustymc** [comment]
>improvement

Thanks!

> second "SAVE SETTINGS" button 

done (at test, for next prod release)

> just Event ID?

That would take screen real estate on my screen. That's not a "no," it's easy to do, but we need to work out the priorities as a group. (My vote is for "compact" when there's no real loss of clarity, and I don't think there is here.)

"Event Name" is just for consistency; making that move verbose would not take any extra screen.

> If mandatory, can they be highlighted as before?

It's not. Pre-create and name events, just use that, your screen can look like this (or a bit smaller):

<img width="389" alt="Screen Shot 2021-09-21 at 5 44 50 AM" src="https://user-images.githubusercontent.com/5720791/134172827-7330296f-fc4e-4489-94db-4f1a805d4d04.png">

(I can't figure out what to do with the geolocate button, right now I'm drifting back towards disappearing it with coordinate metadata... - input appreciated!)

and if you try to save in that state:
<img width="512" alt="Screen Shot 2021-09-21 at 5 45 19 AM" src="https://user-images.githubusercontent.com/5720791/134172842-885c0352-65a9-4227-b747-87125a81c737.png">

This screen is intended to be a lot more accommodating of that kind of use, and doesn't (I hope!) have a bunch of "appendixes" - things that at some point were "required" but now are just one possible approach. I'm not at all opposed to somehow different than it is now, but I am sure that some users would be better served by things like pre-creating events yet don't because the old screen predates that possibility. (You can still do it there, but you have to get around a bunch of unnecessarily-scary yellow stuff.)



There's fairly extensive documentation on this in a big red box when you customize place-time. (And like all documentation, I'm sure it could benefit from being edited by someone who didn't write the code.)

>spell out words whenever possible. 

In general, yes (but see above, we need to define "possible"). Those don't stretch my screen, so done.

>Will you be adding links to documentation?

I'd honestly never considered the possibility that anyone clicked them... Sure, if there's a reason to do so I can bring them across!

>specimen count 

It's bigger (and unrelated to "individualcount").

>Qty

Needs discussion. The edit screen is a bad comparison, it's meant to be comprehensive and predictable and has few constraints on screen real estate, where this one is meant to be (or be capable of) being very compact and specialized. "Part_Lot_Count" is the most accurate description, but that would take a LOT of screen as a header. Might be new-issue worthy.

>same order 

I can shuffle them, the "nodes" are currently static, but I'm not sure they'll stay that way - positional expectations are probably not entirely realistic.

>I would put the Tools at the bottom where you save the record instead of halfway through the data entry screen.

Put it wherever you want. I assume you're still in "table view"? That's fine, but if positioning is bothering you then maybe it's time to move on to dynamic - you don't need to care where anyone else thinks something should be there. (I added the "table" view as a last-minute addition on the assumption that someone wouldn't be willing to spend a few minutes setting up the dynamic view, and maybe it's fine if you have some wall-sized screen, but I think very close to all users will benefit by taking a few minutes to put stuff where it best works for them and turn off all the junk they never use &etc.)

>What are "flags"? or is it Missing?

Yes... Generally, the actual screen was build from the old form, and the customize UI was built from the data (eg what you see when bulkloading). If there's some conflict in the naming it's because someone's asked for it, and I'm hesitant to just arbitrarily flip that (again, which leads to the original complaint, and around and around we go). I have no idea what to do here...

>coll_object_remarks the same as Specimen Remark? 

Yes, I think so, same situation as above. ("coll_object_remarks" means a few things in the core tables - context matters.)

>I can't find "Add more" 

Its not there - you can check out extra parts to see how it'll work, I intend to add the rest "inline" when I can find time. Shall I consider this a request to prioritize identifications?

**Comment by dustymc** [comment]
>Qty

Don't forget this one!

<img width="241" alt="Screen Shot 2021-09-21 at 8 01 45 AM" src="https://user-images.githubusercontent.com/5720791/134195883-7fa31fbb-0bd7-46df-9d81-1eed719e1bb2.png">

I guess I'll vote for "qty." 

I think we need some Official List Of Arctos Abbreviations and Variations or something - I'd *like* to be consistent, verbose table/columns names just don't always _fit_, some sort of public "sometimes we say bla when we're talking about blaugh" doc seems like maybe it could help.

**Comment by sharpphyl** [comment]
> Pre-create and name events, just use that, your screen can look like this (or a bit smaller):

Our volunteers database specimens with unique events so pre-creating events would be doublework.  So for them, higher geography, verbatim locality and date are mandatory and will remain visible.

> (I can't figure out what to do with the geolocate button, right now I'm drifting back towards disappearing it with coordinate metadata... - input appreciated!)

Please don't!  We use it on almost every data entry record.   Maybe you can give the option to "hide" it.

> Put it wherever you want

Yes, the dynamic view is great and we'll try to get everyone to use that.  And turning off what we don't use is very helpful.

> Its not there - you can check out extra parts to see how it'll work,

As long as it will be available, that's fine.  We have several weeks before we'll have volunteers back databasing, but I need to develop new procedures to match the new screens, so it would be great to have Identifications up toward the top of the priorities unless more collections need something else.

> I think we need some Official List Of Arctos Abbreviations and Variations or something

It would be helpful.  Maybe have a chart with what the field really means then what the name/code is for bulkloading etc.

**Comment by Jegelewicz** [comment]
>  "Part_Lot_Count" is the most accurate description, but that would take a LOT of screen as a header. Might be new-issue worthy.

Get fancy with expand on hover?

**Comment by dustymc** [comment]
>expand on hover?

Nobody liked that last time around, but ??????????

**Comment by Jegelewicz** [comment]
> Nobody liked that last time around, but ??????????

Yeah - I can see that.

**Comment by sharpphyl** [comment]
> Nobody liked that last time around, but ??????????

I'd rather hover than wonder what it is.

**Comment by dustymc** [comment]
"Extra" Identifications is now available.

<img width="595" alt="Screen Shot 2021-09-22 at 12 35 26 PM" src="https://user-images.githubusercontent.com/5720791/134418085-c6d75de6-ec43-4c75-91fd-c91b3f42fc81.png">

And there's some minimal mouseover magic.

<img width="194" alt="Screen Shot 2021-09-22 at 12 27 12 PM" src="https://user-images.githubusercontent.com/5720791/134418092-3b4528b7-141f-4dd6-84eb-34fd26830d23.png">

**Comment by sharpphyl** [comment]
> "Extra" Identifications is now available.

Thanks for pushing this to the top.  Looks great.

**Comment by dustymc** [comment]
Next release has "extra" identifiers, and an [option to request more](https://github.com/ArctosDB/arctos/issues/new?assignees=&labels=Enhancement&template=feature_request.md&title=Feature+Request+-+Bulkloader%20Extras). 

<img width="302" alt="Screen Shot 2021-09-29 at 9 20 17 AM" src="https://user-images.githubusercontent.com/5720791/135309287-9d248c42-332d-4732-88d8-6c5b32f74d59.png">

Please let me know here (or with the tool or the link above) if any additional "extras" are needed.

**Comment by ewommack** [comment]
I like all the options. 
I really like the Lost-n-Found function, where it takes me to the section and highlights it. "look look look"

I wasn't sure what the Missing field does - are we saying this entry is missing agents all together? But the agents window is still present when I select them as missing...
![what is the missing field?](https://user-images.githubusercontent.com/18562884/135504690-c8f2b945-dade-4a8f-979b-35900385159e.jpg)

Playing around in attributes under a bird collection. I'm ok with being able to select the mammal helper under the bird collection, and I liked the options that popped up. These will be really helpful when setting up data entry in a mammal collection.
![mammal helper](https://user-images.githubusercontent.com/18562884/135504887-b713a734-9ac6-4bb5-8fcc-375c4d31d9ee.jpg)

But when I select the bird attribute helper in the bird collection this is what I get:
![bird helper](https://user-images.githubusercontent.com/18562884/135505011-209ed347-2b76-4224-8637-79055ea7d25e.jpg)
Not sure how helpful that would be. Could we make it more like the mammal screen and pull in the old attribute helpers for the bird helper please?
![old bird attritbutes](https://user-images.githubusercontent.com/18562884/135505235-fdbd7661-728a-457d-b0b1-7e27d77f7463.jpg)

**Comment by dustymc** [comment]
"Missing" is https://handbook.arctosdb.org/documentation/catalog.html#flags / https://arctos.database.museum/info/ctDocumentation.cfm?table=ctflags and needs better - well, something! ("Everything"?!) The idea is to flag a record that needs post-entry help, then search on your flags and fix stuff later.

The bird-thing should work (at test) now, copy-paste fail on my part.


>... in a mammal collection

The idea that THING works only in collections of TYPE should be absent from this form - it should work just fine to catalog mammals in your teaching collection, then switch to birds in the same collection. (And you can save those states 
<img width="198" alt="Screen Shot 2021-09-30 at 10 56 00 AM" src="https://user-images.githubusercontent.com/5720791/135506608-edf7bf51-9857-46d6-98da-fdae202998d3.png">)


>pull in the old attribute helpers 

For clarity: the old screen was hugely complicated around those options and saved various fields based on a bunch of complexity that was controlled by code. This one just allows a "subform" that populates the same simple form for everyone, and is controlled by user preferences. Hopefully that's seamless enough that additional documentation isn't needed, but please let me know if that's not the case. This approach also means we could have a "left-handed shrews from Barrow Quad" 'helper' - it's much easier to add the little toolbar-thingees in this architecture, and individual users can use them or not.

**Comment by ewommack** [comment]
Playing around some more:

> The bird-thing should work (at test) now, copy-paste fail on my part.

Found it and it looks good! I like how it automatically populates the below fields with the info I enter. And when I didn't enter a field I could select my own attribute to add.


The Copy - 2 - All button for agents worked, except it did not population the agents name in the Agent box. So maybe Copy-2-almost all? I can't remember if it would do this in the old version.


What does this arrow button do? When I pressed it, it didn't do anything. I went and added the date by hand instead.
![date arrow question](https://user-images.githubusercontent.com/18562884/135683684-e1f763f0-5081-41d2-a696-0c66cc16425a.jpg)


I like the missing flag field, but I think if I wasn't looking for it I would probably just gloss over it. Maybe make it a different color or in bold?
![missing flag field appearance](https://user-images.githubusercontent.com/18562884/135683802-b8591d4c-1101-4bbc-b04d-fc22242f88c1.jpg)

**Comment by dustymc** [comment]
>did not population the agents name i

Interesting problem - you might want one of them populated, but you probably don't want all however-many-are-on (you'd just have to remove n-1 of them). Needs better documentation? 

Verbatim date translator patched - it will do nothing if it can't extract dates from the input, or guess....

<img width="268" alt="Screen Shot 2021-10-01 at 2 00 08 PM" src="https://user-images.githubusercontent.com/5720791/135685628-e99ee46f-6e7c-4400-b795-7c028bbcd54e.png">

... if possible.

>color or in bold? 

I don't think the diversity of Arctos users supports any kind of "THIS IS IMPORTANT!!" - because it's probably not for some, maybe even most.

**Comment by Jegelewicz** [comment]
I do think the missing flag thing is overlooked and poorly understood. It would be great to have someone make a tutorial quick bite about it and to give it some publicity in the newsletter and on social media...

**Comment by dustymc** [comment]
>overlooked and poorly understood

No doubt, I just don't think that can/should control the UI.

>tutorial

How about a whole series of them? How many users really understand the many ways to provide locality data, or how to enter 20 parts, or include a 3rd identification, or set up a profile for students to start with, or ....?

**Comment by Jegelewicz** [comment]
>     tutorial
> 
> How about a whole series of them? How many users really understand the many ways to provide locality data, or how to enter 20 parts, or include a 3rd identification, or set up a profile for students to start with, or ....?

I'm pretty sure @ebraker could coordinate another tutorial blitz....

**Comment by aklompma** [comment]
Just checked it out and fields for locality attributes (as in the old form) would be very helpful for fossils to more easily enter the rock unit and age.

**Comment by dustymc** [comment]
<img width="345" alt="Screen Shot 2021-10-04 at 10 46 04 AM" src="https://user-images.githubusercontent.com/5720791/135899203-e8831d1d-22dd-4008-9bb9-6528eaf29c63.png">
<img width="342" alt="Screen Shot 2021-10-04 at 10 46 14 AM" src="https://user-images.githubusercontent.com/5720791/135899238-d56038e3-f438-43d6-b583-7a84dcdc6555.png">
<img width="345" alt="Screen Shot 2021-10-04 at 10 46 33 AM" src="https://user-images.githubusercontent.com/5720791/135899245-da9d6793-433d-4a23-ada5-930a56ac1c96.png">

<img width="1147" alt="Screen Shot 2021-10-04 at 10 46 51 AM" src="https://user-images.githubusercontent.com/5720791/135899250-19795b01-f843-48c9-a23a-5a370130b5a3.png">

**Comment by aklompma** [comment]
Ah, is that how it works! Thanks!

**Comment by ewommack** [comment]
> How about a whole series of them? How many users really understand the many ways to provide locality data, or how to enter 20 parts, or include a 3rd identification, or set up a profile for students to start with, or ....?

> I'm pretty sure @ebraker could coordinate another tutorial blitz....

I did the tutorial for the data entry screen in the old form, and it was hard to keep it short and sweet. I think a series of them is a great idea! We could do one for each collection type, or for different focuses maybe?
The data entry tutorial blitz
and then
a bulkloading tutorial blitz

**Comment by sharpphyl** [comment]
> "Missing" is https://handbook.arctosdb.org/documentation/catalog.html#flags / https://arctos.database.museum/info/ctDocumentation.cfm?table=ctflags and needs better - well, something! ("Everything"?!) The idea is to flag a record that needs post-entry help, then search on your flags and fix stuff later.

So how about "Flag for follow-up" if that's not too long.

**Comment by dustymc** [comment]
It's just ``flags`` in the bulkloader table - we should start just rejecting significant deviations from column names as a matter of policy.

**Comment by ebraker** [comment]
> How about a whole series of them? How many users really understand the many ways to provide locality data, or how to enter 20 parts, or include a 3rd identification, or set up a profile for students to start with, or ....?

> I'm pretty sure @ebraker could coordinate another tutorial blitz....

Sounds good. I already have a tutorial blitz on the docket for December. Here's the sign-up sheet: https://docs.google.com/spreadsheets/d/1BESoZ0mgRgONfSNziHpeumIIlnAWtoOnXxPISgQy2mU/edit#gid=0

**Comment by ewommack** [comment]
@ebraker 

> Sounds good. I already have a tutorial blitz on the docket for December. Here's the sign-up sheet: https://docs.google.com/spreadsheets/d/1BESoZ0mgRgONfSNziHpeumIIlnAWtoOnXxPISgQy2mU/edit#gid=0

Do you want a notice in the Newsletter?

**Comment by ebraker** [comment]
@ewommack Yes! (assuming this newsletter is the last one before December?). When should I have something by?

**Comment by ewommack** [comment]
Yep! October and then the next Newsletter is January. 

How about October 20th for a due date?
I created an article issue for you: 
https://github.com/ArctosDB/newsletter/issues/112

**Comment by Jegelewicz** [comment]
Can we please do some de-specimen work while we are here?

Suggest changing this title to Collection Object Remark

![image](https://user-images.githubusercontent.com/5725767/137763360-672edc19-3a3b-4d77-8e5d-9456f08e6906.png)

Suggest
Specimen/Event Type ---> Event Type
Specimen/Event Remark ---> Event Remark

![image](https://user-images.githubusercontent.com/5725767/137763518-6c35bc98-c22b-43ed-9880-e4eb601f38cc.png)

**Comment by Jegelewicz** [comment]
@AJLinn I just handle stuff when I run across it - if I have time! There is still stuff hanging around, just post it here if you find something!

**Comment by cjconroy** [comment]
I don't know if it was discussed, but I don't see whether standard mammal specimen measurements will be facilitated as they were with the current old data entry screen. Having them ready to go is a big help for most accessions. With the new screen,  it looks like I have to pick them from the list of attributes.

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/3691#issuecomment-931534526
