### ISSUE TITLE
A path to stable Agent identifiers?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3696]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
Currently, ORCID is hidden under agent address in the edit agents page, and requires the full url.

**Describe what you're trying to accomplish** 
Make it easier to search and find agents by ORCID, including search by the number without url.

**Describe the solution you'd like**
Add a search field for ORCID Catalog Record Search page (Date/Collector) and to Agent Search 
Consider ORCID as alternate names rather than "addresses"

**Describe alternatives you've considered**
do nothing

**Additional context**
This would link to https://orcid.org/orcid-search/search?searchQuery=0000-0003-0536-5044
Also could work for Wikidata

**Priority**
Near future

**Comment by Jegelewicz** [comment]
I wonder if we made ORCiD an aka - would it work? And it did! put my ORCiD in 0000-0002-1970-7044 for either an agent search or publication/project agent and BOOM, there I am!

I really think that ORCiD should be an agent name instead of an address, for the functionality that offers.

**Comment by Jegelewicz** [comment]
The recent request for Library of Congress addition to the address code table made me wonder if we could create stable agent identifiers for any agent with one of the following:

ORCiD
Wikidata Q number
Library of Congress ID

Thoughts?

**Comment by Jegelewicz** [comment]
Also - we have lost track of this - https://github.com/ArctosDB/arctos/issues/3360

**Comment by dustymc** [comment]
>create ... agent identifiers

https://arctos.database.museum/orcid/0000-0003-0536-5044 has been functional for a ~few years, so yes.

>stable

That's another thing entirely, but I don't think there are any insurmountable technical barriers.

**Comment by Jegelewicz** [comment]
> https://arctos.database.museum/orcid/0000-0003-0536-5044

Where is that documented? How would anyone know to build such a url and even if they did know, what good is it?

This seems related to the original ask in this issue - a search field for ORCiD. No public user or even an operator without manage_agent could ever find an Arctos agent using ORCiD because it is an address and most of those with manage_agent won't think to put that ID in the address field to search (where it will work).

See also - https://github.com/ArctosDB/arctos/issues/3761
