### ISSUE TITLE
Loan item pick lacks part preservation

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#3697]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
Now that parts with preservation are split out, you cannot see the preservation type on item loan pick. Thus, our former Tissue (frozen), vs. Tissue (95% ethanol), now just looks like Tissue. So, one has to open up the record, look at the tiny tiny font to see which is which, look at the barcode, close that screen, find that barcode on the pick list, and then pick. 

**Describe what you're trying to accomplish** 
Discern the difference between parts in the loan pick list. 

**Describe the solution you'd like**
How might we accomplish your goals?
Next to part in the loan item pick list I'd like to see the field for preservation. 

**Describe alternatives you've considered**
See above. 

**Additional context**

**Priority**
Medium. Can work around, but this change has made picking tissues for loans harder. 
<img width="1017" alt="part does not show preservation in loan pick" src="https://user-images.githubusercontent.com/5749672/124173875-818ab980-da60-11eb-96bd-48fe68d7e5fd.png">

**Comment by dustymc** [comment]
<img width="1330" alt="Screen Shot 2021-07-01 at 1 50 16 PM" src="https://user-images.githubusercontent.com/5720791/124187941-670e0b80-da73-11eb-8627-1b5589143b0b.png">

**Comment by cjconroy** [comment]
For some reason Arctos font is very small on my laptop so I have to zoom in. That column is off the screen. I vote to have Part Attribute adjacent to part name.

**Comment by dustymc** [comment]
It's not difficult to rearrange columns, but some discussion/consensus beforehand would be useful.

**Comment by campmlc** [comment]
Agree with putting adjacent to part name.

**Comment by ccicero** [comment]
I also agree that it makes sense to put part preservation next to part name.
