### ISSUE TITLE
Agent Loader - make it like the other component loaders

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3698]
Can we make the Agent Bulkloader work like the other component loaders?

**Comment by dustymc** [comment]
I think the short answer is "yes" but the longer answer is more complicated. Everyone gets manage_agents when they join Arctos, but they're often not ready for the power to create a million messes with a click either. Agents are somewhat more "authority-like" than the other stuff that gets bulkloaded, and the current loaders reflect that in requiring elevated permissions to finish. The loaders are also integrated with cleanup tools, while the component loader ecosystem isn't (and probably can't be, it runs asynchronously and currently outside of any permissions). I think this will ultimately require a somehow more complex path than eg loading otherIDs. 

See also https://github.com/ArctosDB/arctos/issues/3700, a very related part of that path.

**Comment by Jegelewicz** [comment]
So something more like the record bulkloader? Permissions to write to the bulkloader are not the same as permissions to write to the Agent table?
