### ISSUE TITLE
Code Table Request - add tooth type "cheek"

### ISSUE THREAD

**Issue by AWildAshAppeared** [ArctosDB/arctos#3704]
**Goal**
Add term to describe tooth type.

**Context**
It isn't always possible to tell premolars and molars apart, especially in fossil teeth.

**Table**
Tooth type code table:
https://arctos.database.museum/info/ctDocumentation.cfm?table=cttooth_type

**Value**
cheek

**Definition**
Cheek teeth comprise the premolar and molar teeth in mammals. https://en.wikipedia.org/wiki/Cheek_teeth

**Priority**

**Comment by Jegelewicz** [comment]
I will second this as I know there are "cheek teeth" in the UTEP:ES collection.

![image](https://user-images.githubusercontent.com/5725767/124312162-1a3a3b80-db2c-11eb-8dce-929c95e6dc73.png)

Also - note to self, need to add attributes to UTEP teeth and change part names...

**Comment by dustymc** [comment]
http://test.arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_modifier

**Comment by Jegelewicz** [comment]
Add as a part modifier. Code table committee says add.

**Comment by Jegelewicz** [comment]
added
