### ISSUE TITLE
BulkloadPartContainer Template issue

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#3707]
Trying to put Parts>>Container
get this error:
Message: Error invoking external process
Detail: psql:/usr/local/webroot/temp/excopy_acdoll_20210702010703742_666.sql:1: ERROR: syntax error at or near "." LINE 1: ...r,guid_prefix,part_name,new_container_type,barcode.ignore_ch... ^

I think it doesn't like the barcode.ignore_child_parts header name.

**Comment by dustymc** [comment]
Needs rebuilt as component loader

**Comment by acdoll** [comment]
If it didn't have the '.ignore_child_part' modifier, would it load? Would the child parts (subsamples) get the same barcode attached to them? There probably are only a few and I could manually fix those. I'm wondering if there is a work around, or if I just need to wait until rebuilt?

**Comment by dustymc** [comment]
>would it load

I think so - just replace the ``.`` with a ``,`` (and proceed with caution, as always).

> child parts (subsamples) get the same barcode 

No, it'll find one part or fail.

https://github.com/ArctosDB/arctos/issues/3630 would be handy here as well.

**Comment by acdoll** [comment]
I'll try with a couple records and see what happens. Thanks

**Comment by acdoll** [comment]
That worked. If I had read the instructions closer I should have realized that ignore_child_part should be it's own column.

**Comment by dustymc** [comment]
This should be done after https://github.com/ArctosDB/arctos/issues/3630

**Comment by campmlc** [comment]
It worked for me once I deleted the ".ignore.child.parts" suffix in the barcode column. Is this supposed to be a separate column in the template? Also the guid_prefix header in the template was throwing errors.
This is now high priority for MSB.

**Comment by Jegelewicz** [comment]
@dustymc is there anything preventing the removal of the ".ignore.child.parts" suffix in the barcode column of the template?
