### ISSUE TITLE
specimens set to load from bulkloader hours ago remain in limbo

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#3711]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

If I search on specimens made today (2021-07-02) two sort-of records are found: there are 2 rows but there are no data & I can't click into the records. See screenshot

![Screen Shot 2021-07-02 at 3 15 21 PM Jul 2, 21](https://user-images.githubusercontent.com/9099827/124335894-609d9380-db48-11eb-9d6f-a0b7ff8ff80e.jpg)

These were set to load 3 or more hours ago and they've not loaded.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by dustymc** [comment]
<img width="432" alt="Screen Shot 2021-07-06 at 7 30 57 AM" src="https://user-images.githubusercontent.com/5720791/124617884-270ca700-de2c-11eb-8a06-c7a9aea729e3.png">
