### ISSUE TITLE
"collector" not being recognized in bulkloader

### ISSUE THREAD

**Issue by SerinaBrady** [ArctosDB/arctos#3712]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
@campmlc @dustymc 

**I receive an error from bulkloaded records stating "null value in column "agent_id" violates not-null constraint"
1.) There is no column "agent_id"
2.) (From Mariel) It looks like the "collector" was not recognized somehow. So there is definitely a glitch, possibly related to your putting preparator first before collector, but that shouldn't be a problem if things are working correctly.

The records are in the bulkloader under agent ssbrady and diannakrejsa for ASNHC:Bird** 

[BulkPendingData_91B18CF808.zip](https://github.com/ArctosDB/arctos/files/6766216/BulkPendingData_91B18CF808.zip)
![NULL_error](https://user-images.githubusercontent.com/86243942/124518493-246a6d00-ddac-11eb-8efa-0f4bad202482.JPG)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by campmlc** [comment]
This is what I see in when I click on collection object ID in browse and edit - somehow the preparator is getting inserted into the required collector agent field, and the actual collector is not being recognized.
It can be fixed if you swap the agents, for whatever reason.
![Screenshot 2021-07-05 14 54 05](https://user-images.githubusercontent.com/14808196/124518977-37c60a00-dda5-11eb-93b8-22938c700f62.png)

**Comment by dustymc** [comment]
I wiggled the wires, try again please.

**Comment by SerinaBrady** [comment]
The record that says "test" (97586614) doesn't have the error. All of the other records still do. So maybe it worked?

Best,
Serina
________________________________

**Comment by dustymc** [comment]
Just set them to load when you're ready.

**Comment by SerinaBrady** [comment]
Wooo!! That seemed to have worked. Thank you!!
________________________________
