### ISSUE TITLE
Centrum part cleanup

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3713]
This seems like an easy bunch to get cleaned up

Part Name | Collection | Documentation
-- | -- | --
centrum, caudal [ link ] | ES | Oval segment of bone forming the main body of a tail vertebra. Consider changing part to centrum and adding anatomical direction reference caudal
centrum, cervical [ link ] | ES | Oval segment of bone forming the main body of a neck vertebra. Consider changing part to centrum and adding anatomical direction reference cervical
centrum, dorsal [ link ] | ES | Oval segment of bone forming the main body of a dorsal vertebra. Consider changing part to centrum and adding anatomical direction reference dorsal

Any parts using the above should be changed to centrum with the appropriate anatomical direction reference part attribute value added. Caudal, cervical and dorsal already exist in the controlled vocabulary.

**Comment by dustymc** [comment]
>what do you need 

Someone to say "go."

**Comment by Jegelewicz** [comment]
Can you tell me which collections are using the centrum, parts?

**Comment by dustymc** [comment]
```

select 
  part_name,
  guid_prefix, 
  count(*) c 
from collection 
inner join cataloged_item on collection.collection_id=cataloged_item.collection_id 
inner join specimen_part on cataloged_item.collection_object_id=specimen_part.derived_from_cat_item 
inner join loan_item on specimen_part.collection_object_id=loan_item.collection_object_id 
where part_name like '%centrum%'
group by part_name,guid_prefix order by guid_prefix,part_name;

    part_name    | guid_prefix | c  
-----------------+-------------+----
 centrum         | UAM:ES      | 34
 centrum, caudal | UAM:ES      | 28
 centrum, dorsal | UAM:ES      |  4
```

**Comment by Jegelewicz** [comment]
So, do I email Patrick Druckenmiller or do we just do this?

**Comment by Jegelewicz** [comment]
@dustymc as we have already done this for vertebra - I think we should complete the change for centrum

**Comment by dustymc** [comment]
This happened as part of https://github.com/ArctosDB/arctos/issues/4026
