### ISSUE TITLE
lithified wood part name cleanup

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3714]
[lithified wood](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#lithified_wood)

suggest changing all parts using this name to **wood** with preservation = petrified

See also #3715

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
We should probably just change preservation to fossil, when I was looking through the specimens that use lithified, some had images and I saw several that had looked like they had fossil preservations other than petrified.

**Comment by dustymc** [comment]
> just change preservation to fossil,

I'll go with that if nobody objects before ~2021-11-26.

Data:

[temp_lw.csv.zip](https://github.com/ArctosDB/arctos/files/7573247/temp_lw.csv.zip)

Proposed Update:

```
   part_name    | new_part_name | new_part_attr_type | new_part_attr_val |        new_part_remk_suffix        
----------------+---------------+--------------------+-------------------+------------------------------------
 lithified wood | wood          | preservation       | fossil            | Original part name: lithified wood
```


Users:

```

 guid_prefix | nrecs 
-------------+-------
 ALMNH:Paleo |     9
 JSNM:Paleo  |   178
 UAM:ES      |    34
 UTEP:ES     |     1
```


 @cefilipek
 @mvzhuang
 @aklompma

**Comment by dustymc** [comment]
done

[temp_lw(1).csv.zip](https://github.com/ArctosDB/arctos/files/7676653/temp_lw.1.csv.zip)
