### ISSUE TITLE
Code Table Request - change part preservation petrifaction to petrified

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3715]
**Goal**
~~Clean up parts by moving preservation terms to part attributes~~
Clean up part preservation and make them consistent

**Context**
~~lithification is a specific form of fossilization~~
Items are not experiencing ongoing petrifiaction, the past tense is more appropriate.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_preservation

**Value**
~~lithification~~
petrified

**Definition**
Object has undergone the process by which organic material becomes a fossil through the replacement of the original material and the filling of the original pore spaces with minerals. <a href="https://en.wikipedia.org/wiki/Petrifaction" class="external">Wikipedia</a>

See also #3714

**Comment by dustymc** [comment]
"Lithified" (state, not process) seems better to me.

**Comment by Jegelewicz** [comment]
Given that we have "petrifaction", perhaps it should be "lithifaction"? Now we have a new can-o-wroms?

**Comment by Jegelewicz** [comment]
@Nicole-Ridgwell-NMMNHS @aklompma

**Comment by dustymc** [comment]
It should certainly be consistent. I'm not quite getting the argument for the process unless something's actively undergoing petrifaction in the collection.

States:

cleared
dry
fluid-preserved
freeze-dried
frozen
mummified

Additional processes: 

carbonization



And of course nothing follows the guidelines at https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html

>Include the GitHub discussion link/URL in the definition. (Reports/DataServices includes a link-builder tool.)

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I'm hesitant to add it at all, at least in the context it is currently being used (to describe fossils). Lithification is the process by which sediment grains are turned into rock. When you are talking about fossils it is really kind of a vague term that could just mean fossilized or could have been used as a kind of synonym for petrified.

My suggestion, if the collections using this agree (looks like ALMNH, JSNM, and UAM), would be to use preservation fossil with lithified in remarks.

BTW we should change petrifaction to petrified.

**Comment by Jegelewicz** [comment]
This came about as a part of "petrified wood" - https://github.com/ArctosDB/arctos/issues/2355

So I have changed the code table request

**Comment by Jegelewicz** [comment]
Yes says code table committee

**Comment by dustymc** [comment]
done
