### ISSUE TITLE
Report Server Permission?

### ISSUE THREAD

**Issue by SerinaBrady** [ArctosDB/arctos#3719]
I can't access the report server when I try to print any report. I get this error: "Element DBUSER is undefined in SESSION."

Thanks!

**Comment by SerinaBrady** [comment]
@dustymc @campmlc

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/3658#issuecomment-859595104

**Comment by campmlc** [comment]
"That's almost always from jumping around tabs, but I'm just guessing
without the requested information.

https://github.com/ArctosDB/arctos/issues/new?assignees=&labels=Bug&template=bug_report.md&title=

Steps to reproduce the behavior:

   1. Go to '...'
   2. Click on '....'
   3. Scroll down to '....'
   4. See error"

**Comment by campmlc** [comment]
If jumping between tabs causes the error, what fixes it?

**Comment by dustymc** [comment]
I just need enough information to re-create the issue.

**Comment by acdoll** [comment]
I think I broke something. Was trying to print some report and it just gave up - continuously spinning loading wheel.

**Comment by dustymc** [comment]
resuscitated

**Comment by acdoll** [comment]
Thanks. I was experimenting with pulling the barcode to put on a label but something wasn't right - that may have been the issue?
