### ISSUE TITLE
Blue Gray Clay Formation should be geology remark

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3721]
There are a lot of references to it I'm finding now, and I'm looking to see if anything really describes it as a coherent unit, but it is really seems to just be used as a facies description at individual sites. So yes, I would suggest moving to geology remarks.

_Originally posted by @Nicole-Ridgwell-NMMNHS in https://github.com/ArctosDB/arctos/issues/2975#issuecomment-871522863_

**Comment by Jegelewicz** [comment]
@dustymc can you help me do this? There are 131 localities with

Locality Attribute Type - lithostratigraphic formation
Locality Attribute Value - Blue Gray Clay Formation

which should be changed to

Locality attribute Type - geology remark
Locality Attribute Value - Blue Gray Clay Formation

Once this is complete, Blue Gray Clay Formation will be deleted from the [lithostratigraphic_formation code table](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlithostratigraphic_formation)

**Comment by dustymc** [comment]
done
