### ISSUE TITLE
Change Arctos Classification for Sigillaria

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3722]
From @aklompma 

> After adding a record ALMNH:Paleo:4708: Sigillaria (arctos.database.museum), it was pointed out to me that the higher classification (Liliaceae family and higher) is mostly incorrect, to which I agree after doing some research.
> 
> Instead, I would like to use the 5th classification down in this list https://arctos.database.museum/name/Sigillaria. 

@Nicole-Ridgwell-NMMNHS @cefilipek your collections are the only others using this name. Anyone mind if we change it?

NOTE: This also goes for all the species of Sigillaria as I would want to update them all for consistency.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Please do update it! I checked our old database and that IRMNG classification matches what we had anyway.

**Comment by cefilipek** [comment]
That’s fine with me!

Thanks!


Colleen Filipek (She/Her)

Museum Collections Manager

Jurica-Suchy Nature Museum

Benedictine University


5700 College Rd. l Lisle, IL 60532

Office: (630) 829-1142

Office Fax: (630) 829-6547  l  ben.edu/museum<http://www.ben.edu/museum>

Follow us: facebook.com/JSNMatBU<http://www.facebook.com/JSNMatBU>


Sent from Mobile Device

________________________________

**Comment by Jegelewicz** [comment]
Sigh - EVERY taxonomy request is a rabbit hole.

I think the classification you are requesting is this one:

![image](https://user-images.githubusercontent.com/5725767/125137346-bb476a00-e0c9-11eb-8d4b-fd30b7cc3de3.png)

BUT

The World Checklist of Vascular Plants and GBIF say this name is actually a synonym of Maianthemum F.H.Wigg.

https://www.gbif.org/species/6658244

And their classification matches this one:
![image](https://user-images.githubusercontent.com/5725767/125137696-74a63f80-e0ca-11eb-8928-c70362850643.png)


Did I count incorrectly and you want the second one? And do I need to also make sure that Maianthemum is all correct AND create the synonym relationships?

@aklompma

**Comment by dustymc** [comment]
> hole

https://en.wikipedia.org/wiki/Law_of_holes

I hear the hierarchical tool is nice...

Don't forget 

<img width="346" alt="Screen Shot 2021-07-09 at 2 32 46 PM" src="https://user-images.githubusercontent.com/5720791/125137959-91d71000-e0c2-11eb-9e71-7ba6610c0bfa.png">

https://arctos.database.museum/taxonomy.cfm?taxon_term==Sigillaria

**Comment by Jegelewicz** [comment]
HAHAHA! No - it is [this](https://the-avocado.org/2021/01/12/building-entertainment-the-films-of-the-walt-disney-studio-holes/).

And I just used the sql you provided in the "ichno" thread to get all the classifications.

Of course, that didn't catch
![image](https://user-images.githubusercontent.com/5725767/125138765-7ec93d80-e0cc-11eb-8cd9-f87fbc7fec36.png)

then again, it probably shouldn't have...

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> rabbit hole

Definitely, particularly fossil plants (there is a resource for this on its way, but it may be a few years).

I can't figure out what happened taxonomically here, but these are DEFINITELY different things. Sigillaria is a lycophyte that's been extinct for 250 million years, Maianthemum is an extant angiosperm.

**Comment by Jegelewicz** [comment]
> these are DEFINITELY different things

That's what I thought just looking at images! The crappy thing is GBIF has decided this is a thing - so anything we send as "Sigillaria" will be "improved" to "Maianthemum"!

But we have to start somewhere, so you guys just tell me exactly which classification to use and I will get it into Arctos.

Next step is a review of all of the species names to make sure we aren't creating any garbage.

Sigillaria acuminata
Sigillaria angustifolia
Sigillaria approximata
Sigillaria biflora
Sigillaria brardii
Sigillaria canaliculata
Sigillaria ciliata
Sigillaria elegans
Sigillaria elliptica
Sigillaria hirta
Sigillaria leptoderma
Sigillaria multiflora
Sigillaria pittstoniana
Sigillaria reniformis
Sigillaria rugosa
Sigillaria sternbergi (I am about 99% sure this isn't a thing)
Sigillaria strobus

**Comment by Jegelewicz** [comment]
BTW - <a href="https://en.wikipedia.org/wiki/Sigillaria" class="external">Wikipedia</a>

**Comment by dustymc** [comment]
>this.

Do I need to see that?

>GBIF

Looks like  http://www.efloras.org/florataxon.aspx?flora_id=1&taxon_id=119474 is probably ultimately to blame, and it's propagated to things like https://www.mindat.org/taxon-6658244.html

Ain't taxonomy GREAT?!

**Comment by Jegelewicz** [comment]
OMG! You MUST see Holes!!! (Although reading the book is better....)

**Comment by Jegelewicz** [comment]
> Ain't taxonomy GREAT?!

It is a sh!t show.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
It looks like only these are used in identifications:

Sigillaria
Sigillaria brardii
Sigillaria elegans
Sigillaria marginata
Sigillaria orbicularis
Sigillaria reniformis
Sigillaria rugosa
Sigillaria tessellata

**Comment by Jegelewicz** [comment]
@aklompma says use the first one from https://github.com/ArctosDB/arctos/issues/3722#issuecomment-877466994

**Comment by Jegelewicz** [comment]
Names from Wikipedia added. Classifications in the bulkloader now.

**Comment by Jegelewicz** [comment]
Added synonym relationships for those that need them.

**Comment by Jegelewicz** [comment]
File for all of the above attached.
[Sigillaria.xlsx](https://github.com/ArctosDB/arctos/files/7635323/Sigillaria.xlsx)
