### ISSUE TITLE
What to do with unranked clades?

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#3725]
@AWildAshAppeared asked for some help getting some newly named (fossil) species names into Arctos. I thought I could do so without causing much trouble, but now I'm stuck on the classifications. The information provided included unranked clades and I'm not sure what to do with all those. I've read through #2589 and #3311, among others, but am still unclear on how you handle things like this.
These are the species they need: 

Adalatherium hui Krause et al. 2020 (https://doi.org/10.1038/s41586-020-2234-8)
Falcatakely forsterae O'Connor et al. 2020 (https://doi.org/10.1038/s41586-020-2945-x)
Sahonachelys mailakavava Joyce et al. 2021 (https://doi.org/10.1098/rsos.210098)

The classifications from the literature that Ashely provided are: 

For Falcatakely forsterae:

(clade) Theropoda
(clade) Paraves
(clade) Avialae
(clade) Ornithothoraces
subclass Enantiornithes
Falcatakely forsterae

For Sahonachelys mailakavava:

order Testudines
suborder Pleurodira
superfamily Pelomedusoides
(clade) Sahonachelyidae
Sahonachelys mailakavava

For Adalatherium hui:

class Mammalia
(clade) Allotheria
suborder Gondwanatheria
family Adalatheriidae

Do clades just go in as concept_*N*??

**Comment by dustymc** [comment]
All of the tools should be happy with NULL ranks.

**Comment by Jegelewicz** [comment]
@dustymc I tried adding the classification:

![image](https://user-images.githubusercontent.com/5725767/125215055-69444700-e277-11eb-821e-658cd7438345.png)

and got this:

![image](https://user-images.githubusercontent.com/5725767/125215076-7eb97100-e277-11eb-8e82-f489497c87a8.png)

**Comment by Jegelewicz** [comment]
Note - I saved all the unranked as "category" just so I wouldn't have to re-do it.

**Comment by dustymc** [comment]
Create with null rank should be better for the next release.

**Comment by acdoll** [comment]
Thanks. For some reason I can't add Sahonachelys mailakavava.
![image](https://user-images.githubusercontent.com/12507297/125320606-1ca15000-e2f9-11eb-9fea-34b67fd57c4d.png)
It did let me add just the genus, but not this species.

**Comment by dustymc** [comment]
Bah thanks - Lucee upgraded, something isn't right, works in test, looks like more of https://github.com/ArctosDB/internal/issues/64, I'm on it....

**Comment by dustymc** [comment]
downgraded lucee, try again....

**Comment by acdoll** [comment]
Got it. Thanks.
