### ISSUE TITLE
Downloading Locality Attribute Data - Parsing JSON takes forever

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#3727]
I regularly field requests for locality data (all your fossil localities within a certain area or other criteria) and for these reports I usually require locality attribute data (particularly landholder, chronostratigraphy, and lithostratigraphy). Locality search gives me the ability to download the data into an excel file, but once I do that I have to 1) import the attributes into open refine to get rid of the JSON 2) move them back into my excel file and use some formulas to realign columns (takes a while depending on how many attributes I need) (maybe I could use skip this step by parsing differently in open refine, but I don't know how?).

Because of this difficultly (and because we still haven't dealt with UTMs) it is normal for it to take me over a half a work day to pull data for a single request.

It would be extremely useful if Arctos could just give me the attribute data in a simple human-readable format.

**Comment by dustymc** [comment]
I think there are two big-picture options

1. Something like results/manage/parts download, where Arctos pulls out some pre-defined structure. That's probably nice from your perspective because it's just a click, but it's also useful only for a narrow range of use cases - do anything that's not predicted by the app and it will fail in some way. (And normalized data can do an infinite number of things that won't be predicted by a flattener app, no matter what the app does.)
2. Build a general-purpose JSON-->columns transmogrifier. This would work for one-dimensional data (eg I can't imagine how it could work for specimen-locality-stacks where there can be many events each with many attributes plus many localities also with many attributes). That would be able to handle any number of things like locality attributes, but it would be on you to piece it back in your "core" file (using some "key" column that you'd upload alongside the JSON, I suppose).

https://github.com/ArctosDB/arctos/issues/2131#issuecomment-800712123 might be relevant, depending on what else happens.

A better (but probably much less likely to happen this week) alternative might be to do more with open refine, somehow. I've never used it and not sure what's possible,  but it doesn't seem entirely implausible that openrefine could accept json+ a schema and do magic, er sumthin.

**Comment by Jegelewicz** [comment]
We could also develop an R or Python script to parse the column. Of course that means someone has to be able to use R or Python....

> it doesn't seem entirely implausible that openrefine could accept json+ a schema and do magic, er sumthin.

It does that, but again requires knowledge of OpenRefine....

> Something like results/manage/parts download, where Arctos pulls out some pre-defined structure.

This seems do-able and the best option for busy collection managers. I suggest we suss it out. What could be the "anything that's not predicted by the app" we need to look out for? Could we get a mock up in test to mess around with and figure that out?

**Comment by dustymc** [comment]
>requires knowledge of OpenRefine

Not necessarily, depending on how things actually work internally (and I don't know how, or even if, they do). I don't think that would be much different than what's possible with python/R/Excel+VBA/whatever.

>What could be the "anything that's not predicted by the app" we need to look out for? 

The app is written to handle one Eon/Eonothem, one Stage/Age, and one lithostratigraphic formation (or 5 attributes of any type like the parts-flattener, or absolutely anything else). The data have 3674 Substage/Subage determinations (or absolutely anything else that we didn't see coming). You click the 'flat download' button, get something random (including nothing at all), and use that incomplete data to make bad conclusions of some sort.

**Comment by Jegelewicz** [comment]
OK, that helps. Is there a reason the app is limited to 5 attributes?

Also, I am probably being super dumb, but this issue is due to getting a download from flat? Can we write an SQL query to get @Nicole-Ridgwell-NMMNHS what she wants?

**Comment by dustymc** [comment]
> limited to 5 

No, I'm just throwing numbers out there, the point is only that WHATEVER we might do, it'll be more limited than the "native" structure. (Realistic numbers will depend on the specs, but it's almost certainly more than 5.)

>download from flat?

Good question, I assumed it was from https://arctos.database.museum/place.cfm?sch=locality but IDK.

>SQL

Maybe, depending on the details, but I sort of suspect SQL won't be the best language to tackle this.

**Comment by Jegelewicz** [comment]
> Good question, I assumed it was from https://arctos.database.museum/place.cfm?sch=locality but IDK

@Nicole-Ridgwell-NMMNHS can you give us a quick run-down of how you are currently getting this data?

.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Yes, I am using [https://arctos.database.museum/place.cfm?sch=locality](https://arctos.database.museum/place.cfm?sch=locality)

If it helps, here is the method I've been using so far for these requests:

[How to do a locality query.docx](https://github.com/ArctosDB/arctos/files/6811944/How.to.do.a.locality.query.docx)

It would be nice for the solution to be something fairly simple because then maybe I could just get our most frequent loc data requestors an Arctos account + permission to see our data and they can run these queries themselves. BUT, if the simple solution will stumble when a locality has, for example, a few different formation determinations, then I'd rather have something that can deal with that.

**Comment by campmlc** [comment]
Ooh, I like this idea:  Something like results/manage/parts download, where
Arctos pulls out some pre-defined structure

**Comment by dustymc** [comment]
@Nicole-Ridgwell-NMMNHS maybe a post-processed example would be useful? 

One easy and complete option I didn't mention is that I could just provide "core" locality data in one file and attributes in another, if that's digestible by whoever's using this.

**Comment by Jegelewicz** [comment]
> a.	When querying, make sure to set locality nickname includes NMMNH:Paleo:

Can you also just get things with the Locality Attribute = private so you don't have to delete public localities?

> d.	Parse out the remarks field into northing, easting, and specimens

Suggest we add attributes for UTM northing and UTM easting to save this step. We already have UTM Zone see also #3193

> 8.	If Datums needed, query the old Access database

Can these not be entered into Arctos so you don't have to do that?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> Can you also just get things with the Locality Attribute = private so you don't have to delete public localities?

I missed the obvious there! That is a helpful suggestion, thank you!

> Suggest we add attributes for UTM northing and UTM easting

I had hoped to wait for #2660 to come through.

> Can these not be entered

Again, waiting on #2660 so I can make sure the datum for the UTM coordinates is actually associated with those coordinates. Any new localities I enter the datum goes in the locality remark with the UTM coordinate.

> maybe a post-processed example would be useful?

Sure, here is one, sensitive data removed:
[Engels_LocRequest_July.xlsx](https://github.com/ArctosDB/arctos/files/6812248/Engels_LocRequest_July.xlsx)

**Comment by dustymc** [comment]
Does one column for each of https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlocality_attribute_type, value only, concatenated if multiple (plus whatever else you want from locality/geography) do what you need?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> Does one column for each . . . do what you need?

Yes, that will be fine!

**Comment by dustymc** [comment]
<img width="245" alt="Screen Shot 2021-07-13 at 4 17 47 PM" src="https://user-images.githubusercontent.com/5720791/125537139-5dcac45d-1559-4c67-8a3b-98ed8c13d00b.png">

break it

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
My test account is locked (username NICOLERIDGWELL).

**Comment by dustymc** [comment]
You're unlocked, your old password should work

**Comment by Jegelewicz** [comment]
@Nicole-Ridgwell-NMMNHS once you have a handle on this, would you be willing to write up a How To or make a video tutorial?

**Comment by dustymc** [comment]
"Click button" doesn't quite seem like the most crucial place to focus our documentation efforts??

**Comment by Jegelewicz** [comment]
But nobody will know about it! We need documentation, then a newsletter article....

The parts thingee is proof of this.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thank you for adding this Dusty! When I tried it out in test I had no issues with it. 

We probably just need a brief general How To Search Localities documentation. I can work on that.

**Comment by Jegelewicz** [comment]
@Nicole-Ridgwell-NMMNHS see https://github.com/ArctosDB/documentation-wiki/issues/222
