### ISSUE TITLE
Can't delete subsample from loan due to preservation attributes

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3728]
Go to: any loan
Go to: Review items
change part disposition to being processed
Click red X to delete part
Select "Delete this subsample"
Get error message below

The only way to delete the item is to select "Remove subsample from Loan, keep as part"
And then go into the catalog record, delete the child part attribute of "preservation" from the subsample
Then delete the subsample.
![Screenshot 2021-07-12 14 06 15](https://user-images.githubusercontent.com/14808196/125501126-27abd268-fc6a-497a-a409-5fedee30abc5.png)
![Screenshot 2021-07-12 14 07 44](https://user-images.githubusercontent.com/14808196/125501163-9f568784-9a77-4b5c-bcc3-7fc1a6284902.png)

**Comment by dustymc** [comment]
Options are

1. Don't allow delete with children, which is always safe (there's necessarily a human involved), or
2. Allow cascade delete, which presents a possibility of deleting things you can't see (eg the DOI you added to part identifier for some publication).

It's technically trivial to change this, but that would come with a potentially huge social impact which would need thorough discussion before proceeding.

If that did cascade you still can't delete loaned parts, and I'm pretty sure we don't want to change that.

**Comment by campmlc** [comment]
This is causing loss of functionality in an important tool I use weekly.
Can we at least allow the pop up from the Review Items to ask if we want to
delete the  subsample and all its attributes? Given that these attributes
were autoassigned when we split part from preservation, there are going to
be thousands of them.

**Comment by dustymc** [comment]
I added attributes to part name for next release.

<img width="441" alt="Screen Shot 2021-07-14 at 11 31 00 AM" src="https://user-images.githubusercontent.com/5720791/125674131-ef2abe02-3a0a-406d-876f-dee1496e61f1.png">

Maybe that should be in another column or something, but this at least makes the "summary" information available.

> thousands of them

Can you elaborate on that? Why would you delete thousands of loaned items? The point of much of this structure is to provide some ability to figure out what happened when eg something that looks a lot like 'your' critter shows up in some publication but not in a form that might be considered a real citation. That can't work if items are being removed from loans. I suspect I'm not understanding something important, but I can't fathom what it might be.

**Comment by campmlc** [comment]
There are thousands of parts and subsamples with preservation attributes,
so the likelihood is that every time I need to delete a loan item, even one
I just created, there will be an attached attribute that will prevent me
from deleting an item from loan without going through the complicated
series of events (including leaving the loan form) that I mentioned
earlier, which makes the embedded delete tool in review loan items
essentially worthless. I would like to find a means to keep that tool
functional. If I create a subsample in adding a part to a loan, either from
the loan form or via the loan item bulkloader, and then I need to delete
that subsample both from the loan and from the parts table later (e.g.
because no actual subsample was taken), I would like to be able to do so
directly from the review loan item form, as I can do now.  Instead, the
delete item from loan tool does not work because the preservation attribute
is automatically added when I create a subsample for loan.

**Comment by Jegelewicz** [comment]
I really believe we need a "Best Practices - Loan Workflow" which might help alleviates some of these issues?

**Comment by campmlc** [comment]
This issue was caused by the separation of part from preservation - which
then created problems with the pre-existing tools for removing items from
loan using Review Items. I'm just asking for these tools to be updated - at
the very least, a user interface tools similar to the existing tool to
delete the subsample and then delete from the loan. I just need the old
tool to be modified to allow "delete the subsample and any associated
attributes" or to show me the dependencies as a popup to confirm I want to
delete them. I don't see how this is any different from deleting the sample
itself - if someone is in that form, they already have permissions to do
all these things. We just need to give them the tools to do so from one
place.
