### ISSUE TITLE
Agent - User issue

### ISSUE THREAD

**Issue by droberts49** [ArctosDB/arctos#3729]
I have a volunteer who already had an agent record (Elizabeth Nelson) in Arctos who I am now training to use Arctos so created a user account (enelson) for them. When I tried to add their name and email to the user profile page (https://arctos.database.museum/myArctos.cfm) it didn't like it because the agent already existed. I added the username and email to the agent record, but it doesn't appear to be properly associated, because the agent information (name, email) still doesn't show up with the username (like when I try to add them as an operator). I seem to be missing something and am not seeing it!  =(  Anybody have any ideas? Thank you!

**Comment by campmlc** [comment]
One possible issue, if I understand correctly, is that you can't have two
different profiles for the name person or username. If you want to turn
enelson into an operator, she should first add her email to her original
user profile. Is this where you are getting the error? That might need to
happen first before her username is added to her agent page?

**Comment by Jegelewicz** [comment]
enelson needs to log in to Arctos and complete her profile (from the main menu My Stuff > Profile). This will then show that she has an email and can be invited as an operator.

![image](https://user-images.githubusercontent.com/5725767/125527302-2424c97d-ed94-4202-aaa4-b48e17dc32b3.png)

**Comment by dustymc** [comment]
The manage app can UPDATE a user's email, but cannot CREATE (email is bundled in with affiliation and name and such). That's not very well reflected in the form; it will be better for next release.

See https://handbook.arctosdb.org/documentation/users.html#creating-operators: 

>They must have an email address in their Profile. 

The user must update their own profile before they may be invited.

**Comment by droberts49** [comment]
@Jegelewicz I've tried several times to update it here but it won't let me.
There is an email on the agent record.

**Comment by droberts49** [comment]
There seems to be a conflict when the name you want to enter in the profile already exists as an agent record.

**Comment by Jegelewicz** [comment]
@droberts49 so Elizabeth cannot add an email to her profile? Not her agent, but her login profile. Just want to make sure this is the issue.

**Comment by droberts49** [comment]
@Jegelewicz We added in her name and email in the profile update and it kept giving an error message. I didn't try just adding an email and can try that once Arctos is up and running again.

**Comment by Jegelewicz** [comment]
Maybe get some screen shots of the error so @dustymc can tell us what is going on. Thanks!!!

**Comment by dustymc** [comment]
Yes, and grab the error ID (as text) too please.

**Comment by droberts49** [comment]
Walking through things now (I'm creating a user account for one of my volunteers who already had an agent record):
Agent record for Elizabeth Nelson has an email and her login listed.
Login, go to profile:
![image](https://user-images.githubusercontent.com/16580148/126513485-efc9a8b8-f358-4dda-ae15-ceece591c5c4.png)
click save (seems to have worked...fingers crossed)
Go into my account > Arctos users > enelson > YAY! It's populated now! Woohoo!

Whatever was going on seems to have corrected itself (time??).
