### ISSUE TITLE
bulkloader assistance - bulkloader in use since 4:27 AM

### ISSUE THREAD

**Issue by cefilipek** [ArctosDB/arctos#3730]
The bulkloader appears to have been in use since 4:27 AM. I tried emailing the contact email 45 minutes ago, but have not received a response.

**Comment by dustymc** [comment]
@jonfonghk here's your data from the bulkloader.

[bulkloader_stage(15).csv.zip](https://github.com/ArctosDB/arctos/files/6818489/bulkloader_stage.15.csv.zip)

@cefilipek it's 3AM there, I grabbed the download, I think you can go ahead and delete.

**Comment by cefilipek** [comment]
Thank you!

**Comment by campmlc** [comment]
The user is in Singapore - so likely asleep now. I downloaded a csv of what
is in the loader, so go ahead and load!
