### ISSUE TITLE
Media uploads

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3732]
What is the status on uploading media? Are we on hold, or can we continue to do media uploads?

**Comment by dustymc** [comment]
Which method?

**Comment by AJLinn** [comment]
I've been adding media every day, one at a time. No problems.

**Comment by ebraker** [comment]
Batch tools >>>Bulkload Media Metadata

I've got a csv ([TACC_media_metadata_2021-07-14.zip](https://github.com/ArctosDB/arctos/files/6819412/TACC_media_metadata_2021-07-14.zip))  with links to all the images Chris moved over to the web accessible space today ready to go, but I'm getting an error when trying to access the bulkloader:

![image](https://user-images.githubusercontent.com/11336485/125705590-7b2089e9-2315-437f-b4e5-783603010cfb.png)

**Comment by dustymc** [comment]
Sorry, I broke the loader - I'm hoping to have a replacement out tomorrow(ish), or I should be able to recover what I broke if that won't work for you.

**Comment by ebraker** [comment]
No problem! I can wait until you've patched it. Thanks!

**Comment by dustymc** [comment]
@ebraker I don't see anything in the bulkloader, the couple I checked seem to be happy, sorry I got a little sidetracked in the ~~apocalypse~~ upgrade - let me know if anything looks broken.

**Comment by ebraker** [comment]
It looks like everything went in smoothly. Thanks for loading!!!
