### ISSUE TITLE
Code Table Request - Dinwoody Formation

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#3733]
**Goal**
Add Dinwoody Formation to the formation code table.

**Context**
Dinwoody Formation exists ([https://macrostrat.org/sift/#/strat_name_concept/7938](https://macrostrat.org/sift/#/strat_name_concept/7938)) and I need to use it for one of our localities.

**Table**
[https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlithostratigraphic_formation](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlithostratigraphic_formation)

**Value**
Dinwoody Formation

**Definition**
A Permian and Early Triassic Unit in the western USA [Macrostrat](https://macrostrat.org/sift/#/strat_name_concept/7938)

If there are no objections I will add it to the code table

**Comment by Jegelewicz** [comment]
Looks OK to me.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Added
