### ISSUE TITLE
Check DOI on Edit Publication page 404s

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3734]
Go to Edit Publication without a doi
Click "Bah! No DOI! Click this!
Select a suggested doi - click "Check 10.xxxxx"
Get 404 Object does not exist error
BUT the doi does actually exist, and can be added directly.

Priority Normal to High - it causes users to think a doi doesn't exist or is invalid, when a valid one actually exists and could be added

**Comment by dustymc** [comment]
**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Comment by campmlc** [comment]
Go to Edit Publication without a doi
Click "Bah! No DOI! Click this!
Select a suggested doi - click "Check 10.xxxxx"
Get 404 Object does not exist error

**Comment by campmlc** [comment]
Here is a publication to try
Hubbard, Clarence Andresen. Fleas of Western North America. The Iowa State College Press, Ames, Iowa, ix+533 pages, 1947.
