### ISSUE TITLE
Redesigning the Publications and Projects Search Page (functionally and visually)

### ISSUE THREAD

**Issue by genevieve-anderegg** [ArctosDB/arctos#3736]
Hello! I’m Genna, one of the Arctos interns this summer, and am currently in the CU Boulder Museum and Field Studies MS program. The internship team has been working on coming up with ideas to redesign the Project and Publication records and search page so that they are more functional. The main ideas are listed below and a visual mock-up is attached. Several ideas will have their own issues but have been incorporated into the discussion below. Feel free to add your thoughts and ideas on how to improve the publications and projects search page!

**Functional Changes**
•Easy searching for projects publications or both at the same time by: general title and description (keywords, parts of sentences), agents (names and rolls), and date ranges. A goal would be to include “collections” as an option in agents so that collections that loaned material could be linked to both project and publication records (right now, can only link individual collections directly to projects through specimen loans attached to project records)
•Allow searching by Arctos-specific “Project ID Numbers” and “Publication ID Numbers”
•Organize the search page to look like the current Arctos specimen search page, organized by General, Publication, and Project sections. Display just the Search, Agent, and Date Range for both Publications and Projects under “Search Publications and Projects”, and have more detailed options for both under a “Show More Options” link (can collapse with “Show Less Options”)
•When searching under the “Cites Scientific Name”, make it possible to search by higher level phylogeny (Family, Order, Class etc.) so that all publications will be retrieved that cite specimens within that higher taxon
•Allow searching for projects by the name of an institution that has specimen records linked to that project, and by the institutional loan number that links a specimen to that project record (user would probably only be able to search for loans they have permission to view and edit when logged in)
•Can search for Publications by the institution/collection of the specimens that a publication has cited (a drop-down menu like general specimen search where you can check boxes for each collection you want)

Issue #3737: **Move the “Try something random” widget from the main search page to the Publications and Projects search page and making a “Community” widget to replace the “Try something random” on the main catalog record search page.** 
Having a Community “Bulletin Board” on the main page will allow Arctos to directly contact it’s users about topics like: welcoming new collections, inviting people to working group and issues meetings, and linking to the newsletter. The pop-up banner that is sometimes on top of the search page can also be moved here, and will improve the look of the main search page so that the page doesn’t “jump around” when you mouse over the banner and it expands.
Please leave your comments and thoughts on this issue: 

Issue #3738 : **Projects and Publications search results improvements**
In addition to making searching for projects and publications more intuitive and specific, we would also like to make the search results more readable, adjustable, and customizable. Ideas are:
•Show results in summary form (like specimens now), and filter search results
•Be able to further filter search results by the same categories as on the search page
•Be able to display search results as either a list of the queried projects/ publications (like it does now), and also as a Summary of the project/publications, similar as how you can currently do that with catalog records. Another drop down menu for the Summary option would allow you to check boxes to group projects/publications by different levels of taxonomy, scientific name, formatted scientific name, year, and agents.
Please leave your comments and thoughts on this issue: 

Issue #3739 **Be able to search by agent ORCiDs for both projects and publications.** 
Because an Agents ORCiD is already in the agent table, allow users to search by that in the Agent Search box. 

![Slide1](https://user-images.githubusercontent.com/83782023/125868358-6d57dcb6-9b56-4121-b96e-1d932e431754.png)
![Slide2](https://user-images.githubusercontent.com/83782023/125868363-8cfaa3f2-22d0-49b7-87aa-fe97a6265638.png)
![image](https://user-images.githubusercontent.com/83782023/127567718-3f74639c-7865-4372-831b-079821f77c36.png)

**Comment by KyndallH** [comment]
@AJLinn @acdoll @amgunderson

**Comment by Cynthia-Carr** [comment]
Hi, just wondering where you were putting the 'Related Collections/Institutions' search box that was mentioned at the meeting yesterday?  In the Advanced Search section?

**Comment by ewommack** [comment]
I like the idea of the community widget. That might help with our discussion on trying to get Arctos alerts and notices to a broader audience too: https://github.com/ArctosDB/arctos/issues/3777

**Comment by genevieve-anderegg** [comment]
> Hi, just wondering where you were putting the 'Related Collections/Institutions' search box that was mentioned at the meeting yesterday? In the Advanced Search section?

I added it in the "Projects" advanced search section (third picture in this post). The idea is to be able to search by what collections may have started a project, so that it is easier for managers to keep track of projects that have used their specimens

**Comment by Cynthia-Carr** [comment]
I wonder if it would also be useful with publications??

Sent from my iPhone

On Aug 1, 2021, at 6:25 PM, Genevieve Anderegg ***@***.***> wrote:

﻿

Hi, just wondering where you were putting the 'Related Collections/Institutions' search box that was mentioned at the meeting yesterday? In the Advanced Search section?

I added it in the "Projects" advanced search section (third picture in this post). The idea is to be able to search by what collections may have started a project, so that it is easier for managers to keep track of projects that have used their specimens

**Comment by genevieve-anderegg** [comment]
Another idea: Be able to search Projects by the collection/institution that created it. This would able searchers to ask "What projects have been created by a specific collection/archive?" and would be useful for managers to easily keep track of different projects they have undertaken in their collection, without having to use other workarounds (like putting the name of the collection in the project title to make it searchable).

**Comment by Jegelewicz** [comment]
Make use of agents! @Jegelewicz to get the agents created/fixed if they are there.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/3468
