### ISSUE TITLE
Move the "Try something random" widget, create new "Community" widget on main search page

### ISSUE THREAD

**Issue by genevieve-anderegg** [ArctosDB/arctos#3737]
This issue related to redesigning the projects and publications search page #3736 

**Move the “Try something random” widget from the main search page to the Publications and Projects search page and making a “Community” widget to replace the “Try something random” on the main catalog record search page.** 
Having a Community “Bulletin Board” on the main page will allow Arctos to directly contact it’s users about topics like: welcoming new collections, inviting people to working group and issues meetings, and linking to the newsletter. The pop-up banner that is sometimes on top of the search page can also be moved here, and will improve the look of the main search page so that the page doesn’t “jump around” when you mouse over the banner and it expands.

**Comment by Jegelewicz** [comment]
See also https://github.com/ArctosDB/arctos/issues/825

**Comment by Jegelewicz** [comment]
I like the idea of letting "Try Something Random" apply to non-operators and creating an alternative Community Bulletin Board for Arctos operators. We could still display the first few rows for operators from https://arctos.database.museum/Reports/dashboard.cfm in hopes that we might be nudging someone to increase their data quality (HAHAHAHA!), but follow that with  welcoming new collections, inviting people to working group and issues meetings, and linking to the newsletter. I think this would end up being a lot more useful and I agree that it

>  will improve the look of the main search page so that the page doesn’t “jump around” when you mouse over the banner and it expands.

**Comment by dustymc** [comment]
I do not support moving the 'look what we can do' widget to a place that accounts for 1.72% of all traffic.

I'm less concerned about operators, but I'm an operator and I've probably fixed a few thousand problems from the TSR widget over the years.

**Comment by Jegelewicz** [comment]
> I'm an operator and I've probably fixed a few thousand problems from the TSR widget over the years.

I SAID we could keep the top part for operators....just replace the bottom (which we also present to the public) with more internal messaging.

**Comment by dustymc** [comment]
The top part contains the problems that I already know about, and I know about much of that from looking at something random from time to time.

**Comment by Jegelewicz** [comment]
So open a private window - it's what I have to do when I need to see stuff from UAM...

**Comment by Jegelewicz** [comment]
Even if we left the Random stuff - I like the idea of losing the banner and putting the community info in this widget.

**Comment by campmlc** [comment]
I like the idea of a community widget for operators if not the public - we
need to emphasize that we ARE a community. If we keep Try Something Random
at all, we should at least rename it to something less ... random.... to
encourage use. Suggestions?  "Browse Our (Your) Data"?

**Comment by campmlc** [comment]
This is where a dashboard for each collection would be useful - to show
operators low quality data that needs attention, and show the public our
good stats.

**Comment by mkoo** [comment]
Discussed in Issue Meeting 2021-08-05: possibly adding a Twitter widget in addition to the renamed 'Try something Random'  on the home page which will allow us to streamline announcement procedures. So instead of posting on home page separately, tweet the alert or status update (possibly add some predictable ```#arctosStatus``` tag) and have it show up here. other times it will show community updates etc. 

Need to check out best way to embed a twitter thingy and send to Dusty for eval
