### ISSUE TITLE
[CONTACT] Can not find information on my species

### ISSUE THREAD

**Issue by trishalmiller** [ArctosDB/arctos#3740]
** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **

** Outages should be reported to the contacts listed at https://arctosdb.org/arctos-down/ **

** Arctos Documentation is http://handbook.arctosdb.org/ **

** Learn more about Arctos at https://arctosdb.org/ **

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **

**Comment by ewommack** [comment]
Hi @trishalmiller - could you give us a bit more info? What species were you looking for, and what steps did you use in Arctos where it didn't come up?

**Comment by Jegelewicz** [comment]
closing for lack of response
