### ISSUE TITLE
Code Table Request - Remove "in house" from Loan Types

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3741]
**Goal**
Create a best practice flow chart of Loans. In our discussion, we decided that "in house" should be indicated through a shipping address.

**Context**
From #2703 
Remove 'in house' as a loan type and create a new shipping method 'in house'. One problem with keeping it as a loan type is that you can have an 'in house' 'consumable' loan but you can't choose both, it has to be one or the other. Moving 'in house' to shipping makes more sense because it pertains to where the loan is being used, not what it is (e.g., consumable, returnable, transfer of custody, media, data).

Hand carried as a shipping method is similar, but the distinction can me made by the agent address.

**Table**
[ Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table you are requesting changes to here. ]

**Value**
All in house loans would get a shipping address equal to the institution address, but what loan type should they be changed to? @dustymc can you tell us how many and where the in house loans are?

**Definition**
N/A - this is for removal of a term.

**Priority**
Setting this as High because it has been hanging around and it is interfering with Best Practice documentation

**Comment by dustymc** [comment]
>Hand carried as a shipping method is similar, but the distinction can me made by the agent address.

Hu?

I don't think we need a fake and redundant shipment type for this, and I don't understand what you're suggesting the address has to do with this. 

I agree that 'in house' is not informative.

> how many and where 

```
arctosprod@arctos>> select guid_prefix,count(*) from collection inner join trans on collection.collection_id=trans.collection_id inner join loan on loan.transaction_id=trans.transaction_id where loan_type='in house' group by guid_prefix order by guid_prefix;
 guid_prefix | count 
-------------+-------
 ALMNH:EH    |     1
 ALMNH:ES    |     7
 ALMNH:Mamm  |     1
 CHAS:Mamm   |    73
 DMNS:Bird   |     2
 DMNS:Mamm   |     6
 MSB:Bird    |     1
 MSB:Mamm    |    84
 MSB:Para    |     5
 MVZ:Bird    |    18
 MVZ:Egg     |     2
 MVZ:Herp    |     2
 NMMNH:Bird  |     1
 NMMNH:Herb  |     1
 NMMNH:Inv   |     2
 NMMNH:Mamm  |     2
 NMMNH:Paleo |     4
 NMU:Bird    |     2
 NMU:Mamm    |    14
 UAM:Arc     |     1
 UAM:Art     |     5
 UAM:EH      |   117
 UAM:ES      |     3
 UAM:Herb    |    21
 UAM:Mamm    |    40
 UCM:Bird    |    24
 UCM:Fish    |    13
 UCM:Herp    |    12
 UCM:Mamm    |    39
 UMNH:Bird   |     6
 UMNH:Herp   |     7
 UMNH:Mamm   |    21
 UMNH:Teach  |     2
 UNR:Mamm    |     1
 UTEP:Arc    |     2
 UTEP:Bird   |     8
 UTEP:Ento   |     2
 UTEP:ES     |    22
 UTEP:Fish   |     1
 UTEP:Herb   |     3
 UTEP:Herp   |     7
 UTEP:HerpOS |     1
 UTEP:Inv    |     2
 UTEP:Mamm   |    20
 UTEP:Teach  |     3
 UWBM:Herp   |    13
(46 rows)
```

**Comment by Jegelewicz** [comment]
Using the "in house" or institution address will indicate that the loaned items remained within the institution, no need for anything further.

The Hand carried thing was I think an extraneous comment - probs could have left it off.

**Comment by Jegelewicz** [comment]
So, the idea would be that for the above loans, we would need to determine if they were consumable or not, then add (if it isn't already there) a shipping address that matches the institution agent address. Make sense? Should we do something else?

I can't look at the code table right now, but I'll update this when I can.

**Comment by AJLinn** [comment]
So... I have 117 in-house loans, so this broad category is vitally important for my documentation processes to describe when researchers access collections in-house and when we place objects on exhibit in-house. 

If you're going to remove in-house as a loan type, please suggest a useful and easily quantifiable proposal for replacing this important category showing how many times I'm physically pulling objects from their storage locations, handling / examining them (and thus introducing the opportunity for damage), that also shows how people are intellectually querying our holdings?

Adding "in-house exhibit" as a type to replace one use of the generic in-house might be useful. What might be an equally useful new category to document an "in-house research" loan?

Returnable is only used for "standard" loans that are packed up and sent outside of the museum so I do not want to be forced to use that type. It describes an additional level of risk introduced to the collection.

**Comment by amgunderson** [comment]
I am creating an in house loan right now. An archaeologist came here to ID bones using our skeletons. I like "in house" loans. They are loans that never left the building. So they aren't consumable, they aren't returnable, they are in house loans. A consumable loan is what it is wherever it was consumed, it's still a consumable loan, so I call it that and don't expect to get anything back. It doesn't make sense to me that I should have to make a bogus shipment to track a loan. I want to keep in house and propose no change be made.

**Comment by Jegelewicz** [comment]
See also https://github.com/ArctosDB/arctos/issues/1248

**Comment by Jegelewicz** [comment]
This needs documented in the code table and it appears we should be keeping this term and we also need to remember we have had the discussion more than once.

**Comment by Jegelewicz** [comment]
Also flowchart needs revision...

**Comment by AJLinn** [comment]
Where is this flowchart?

**Comment by dustymc** [comment]
>flowchart needs revision.

I think more like a footnote. There are almost always multiple paths to everywhere in Arctos, some of them are somehow "traditional," might even have how-tos, but they occasionally lead to places from which only limited questions can be answered. 

I really don't know if this is one of those situations or not - "we have no interest in recording what they did, but they didn't go very far to do it!" doesn't sound that interesting to me, but then neither do most of the [alternatives](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctloan_type). Why do we record this at all; what's it DO? Maybe we need entirely new values, or a new structure, or maybe it just serves some administrative purpose that I don't understand. 

Somehow embedding the idea that we may have some whole thing entirely wrong, and that there's a mechanism to request more information or solicit change, in the decision matrix sounds useful to me.

@AJLinn it's https://docs.google.com/drawings/d/1Zs4IoCzJJ2ymbSrm3NIC6ZzWdmw421mIMTO4HlSpxHY/edit

**Comment by Jegelewicz** [comment]
> Where is this flowchart?

See https://github.com/ArctosDB/documentation-wiki/issues/214

**Comment by Jegelewicz** [comment]
FWIW I am trying to get better documentation around "Loan Type" which is why this has reared its head again. Any and all comments both here and in the documentation issue are appreciated.

**Comment by Jegelewicz** [comment]
Link to this issue added to code table definition. Flowchart modified to include inhouse.

**Comment by Jegelewicz** [comment]
Best Practice Document created. Closing.
