### ISSUE TITLE
Error on download attempt

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#3742]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

Did this cat record search

https://arctos.database.museum/saved/haberskietal2021osfvouchers

tried to download results & got this error

Message: Error invoking external process
Detail: psql:/usr/local/webroot/temp/tcl_AE2AE618-782D-4678-99AB4C8F1389B600.sql:1: ERROR: relation "temp_cache.dl_ss_ffdss_20210719090737132_191" does not exist 

Trying to create citations for these records.

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.
high

**Comment by dustymc** [comment]
I updated the processor, it might take a couple hours to clear the cache.
