### ISSUE TITLE
[CONTACT: Blocked Network]

### ISSUE THREAD

**Issue by MiekeRoth** [ArctosDB/arctos#3743]
Hi Arctos Team, 

My IP is blocked for reasons unknown. Could you lift this block or give me a reason for the block?

restricted IP: 62.194.237.129

Kind regards,
Mieke Roth
https://miekeroth.com

**Comment by dustymc** [comment]
restrictions removed

**Comment by MiekeRoth** [comment]
Thank you very much!

 

Mieke Roth

Communicates complex scientific subjects

in a beautiful, accessible and visual way

Mieke Roth, MSc.

Breehorn 46

8223 CN Lelystad

The Netherlands

+31 (0)6 37 280899

 <https://miekeroth.com> https://miekeroth.com

 

Van: dustymc ***@***.***> 
Verzonden: dinsdag 20 juli 2021 16:55
Aan: ArctosDB/arctos ***@***.***>
CC: MiekeRoth ***@***.***>; Author ***@***.***>
Onderwerp: Re: [ArctosDB/arctos] [CONTACT: Blocked Network] (#3743)

 

restrictions removed
