### ISSUE TITLE
Report Timeout Error

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#3744]
I'm trying to print a loan shipping label, header, and invoice and receive the following error when I click on the reporter server link (http://reports.arctos.database.museum/reporter/report_printer.cfm?auth_key=7097CA9E-0F75-4A37-91B0D4CCC3F0B012&transaction_id=21127440):
-![image](https://user-images.githubusercontent.com/11336485/126359007-e6c16741-f235-4113-a616-0eabbb586dea.png)

**Comment by ebraker** [comment]
Tried again and I received a different error:
![image](https://user-images.githubusercontent.com/11336485/126359919-0cbf71f9-52a6-4597-a06c-36d06a8d3ca7.png)

**Comment by dustymc** [comment]
Updated the report server, added to migration procedures.

The second error is caused by some sort of nonlinear approach - authentication is pretty twitchy on this server.

**Comment by ebraker** [comment]
Thanks. Any idea on when I'll be able to access the server? I'm hoping to send a loan out today.

**Comment by keg34** [comment]
We are getting the same error upon trying to print specimen labels.

**Comment by dustymc** [comment]
It's working for me - I need enough information to re-create the error.

**Comment by ebraker** [comment]
UCM:Mamm V-231 >>> print shipping label (or any report) >>> click http://reports.arctos.database.museum/reporter/report_printer.cfm?auth_key=5AE30493-20AD-482C-9F2A1F7E50DC1CCE&transaction_id=21127440&report=shipping%5Flabel
gives error:
![image](https://user-images.githubusercontent.com/11336485/126370361-ee9515fc-ed59-4a72-aa7d-1a0735d87749.png)

**Comment by dustymc** [comment]
Please try after the restart and let me know if it's still acting up.

**Comment by ebraker** [comment]
It works! Super speedy.
