### ISSUE TITLE
Changes made to code table do not appear in public view

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3745]
I updated definition in the Loan Type code table - https://arctos.database.museum/info/ctDocumentation.cfm?table=ctloan_type and they appear when viewed in "edit", but not in the public view.

**Comment by dustymc** [comment]
there's a cache

**Comment by Jegelewicz** [comment]
Just wanna make sure I get this. I cleared the cache on my end to no avail. If it's on Arctos end, what kind of lag should we be expecting (maybe today is dumb because of recent upgrade?)

**Comment by dustymc** [comment]
It's an hour (and I'm sure that was in the docs at some point but I can't find it now...).

**Comment by Jegelewicz** [comment]
OK - I'm just used to "instantaneous" and maybe that will be more likely once everyone isn't playing catch-up from a couple of days downtime....
