### ISSUE TITLE
IMPORTANT: server restart at 1PM Pacific

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3746]
The database needs to restart, it should be brief (but stuff happens).

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
@dustymc I can't log into the database (I enter my info, hit log in, and then it gets stuck trying to load). My interned is working fine, could this be related to the restart?

**Comment by dustymc** [comment]
Different cause but same result, I think - I'll get Chris to help figure it out.

**Comment by ewommack** [comment]
@dustymc for me I'm having problems logging in because it doesn't recognize my password. I did the lost password link, got my new temporary password, but it doesn't recognize that one either.
I cleared my cache, and it still won't recognize the password.

**Comment by dustymc** [comment]
Gave it a kick.

**Comment by ewommack** [comment]
Thanks @dustymc - I reset my password and I'm on again.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks!
