### ISSUE TITLE
Should Bulkloader Templates include "status" field?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3747]
It is listed in definitions, but not included in the downloaded template. Also - I think this should be the first column of all of the templates since it is the one thing they would all have in common.

**Comment by dustymc** [comment]
Needs discussed?? IDK, I don't think it's in any template, I thought it would be confusing and anyone not confused can add it easy enough but ??????????

**Comment by dustymc** [comment]
This needs resolved and added to next component loader version if we decide to do something different. 

(I'm still not sure I get the need - "power users" who might safely load with actionable status probably don't use the templates, "normal" or occasional users probably need the extra check-step.)

**Comment by Jegelewicz** [comment]
>  probably don't use the templates, 

I download a template every time - I don't want to find that something has changed and I'm using some old template....
