### ISSUE TITLE
Push all parts through the Part Bulkload Tool

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3748]
**SABI Goal**
Collection-specific consultation of bulkloading and searching tools (i.e., Earth Sciences, Genomics, etc)

"Can we just go back to the option when both preservations (formalin-fixed, 70% ethanol) are added as one?"
I agree. I do most of my data entry with the data entry screen, and this new situation is going to make my job harder. Because of the extra steps, it is surely going to lead to mistakes. Maybe it was already suggested, but why not preservation one, preservation two for each part on the data entry screen?

_Originally posted by @cjconroy in https://github.com/ArctosDB/arctos/issues/3708#issuecomment-883040370_

**Comment by Jegelewicz** [comment]
Would this improve the data entry experience? I assume the extra step of setting them to autoload after the rest of the record is loaded would be less painful than the current "extras" step in data entry? Any other ideas?

**Comment by lingnancollection** [comment]
I think moving the parts to a second bulkload will require multiple databases, which increases the chances for errors in collection management. What would be needed to be able to bulkload all at once?

**Comment by campmlc** [comment]
I agree with making it possible to add extra preservation etc to the
current interface even if parts are set to autoload through the component
loader. It would be nice to click directly from any of the parts and
attributes tables to "add more" without having to go into a separate
interface, no matter where the data end up.
Also, could we flag records in the bulkloader that have extras? Right now
all records have an "extras" link, and you have to click each one to see if
there is anything there. Can we just have the link visible only if extras
exist?

**Comment by dustymc** [comment]
We need an actionable and usable plan to resolve this; hacking at the immediately-annoying bits is not likely to lead anywhere we want to be.

We can add stuff to the specimen bulkloader.

- a second preservation is concise, but excludes most attributes and most users/use cases.
- some number of full 'attribute stacks' add a lot(1) of columns, which isn't immediately fatal from a functional standpoint, but there is a limit. These would also have potentially confusing names - "part_12_attribute_determiner_6" or something. I'm not sure 500+ part-columns in a spreadsheet is any form of usable, but I'm not the audience so maybe.


We can better-integrate the loaders (https://github.com/ArctosDB/arctos/issues/2178), somehow. Probably requires dedicated resources.


We can build tools to split things out, which is probably the most immediately-accessible solution (I can usually put one together while I'm waiting on something else to run) but also potentially the most complex from a UI perspective. (Or maybe this plus some way to build templates and good documentation is close enough to #2178, IDK).


We could fall back to "formalin then alcohol" as a preservation, if such a thing can be justified and documented. (I don't see it, but maybe I don't understand something.)


We could do something else entirely, but I can't think of more options....



>even if parts are set to autoload

That will not get resolved here. If there's interest in doing something auto with autoload, there needs to be an Issue which discusses that and nothing else.

-------------------------
1. "A lot" is 12 parts (for now), each of 7 columns, plus each attribute would take about 6 columns, so adding 6 (a number that's worked for the standalone loader) leads to 432 new columns - 516 total part-columns (or 528 if we also keep 'preservation,' which seems like the most confusing thing possible).

**Comment by Jegelewicz** [comment]
I agree with the actionable and usable plan. Here is where we should discuss it.

**Comment by cjconroy** [comment]
I'm glad there might be a bulk loading solution, but I would still like to see a way that I can catalog specimens in one step in data entry, or second best, edit them one by one in specimen detail, or in the modify parts tool for a subset of specimens.

**Comment by Jegelewicz** [comment]
>  I would still like to see a way that I can catalog specimens in one step in data entry, or second best, edit them one by one in specimen detail, 

@cjconroy you can do that now using the "extras" at the bottom of the data entry form. OK, to be fair it isn't "one step", but it does allow you to enter everything in one step. This does require the additional step of visiting the Part Bulkload Tool and setting the parts to autoload after the catalog records have loaded.

Using modifiy parts would be a nice solution as well. I think this should be part of our overall discussion about how to make this more palatable for everyone.

**Comment by dustymc** [comment]
>part of our overall discussion

Yes, I think this can/should be expanded to include edit tools - if that starts to looks like a distraction to the bulkloader/data entry discussion it can be split off.

**Comment by Jegelewicz** [comment]
See also #3755

**Comment by Jegelewicz** [comment]
> some number of full 'attribute stacks' add a lot(1) of columns, which isn't immediately fatal from a functional standpoint, but there is a limit. 

I'd like to start with this. I had an interesting insight during a TDWG meeting about flat files vs. relational and I think we need to help everyone get from one to the other without too much heartache.

> I'm not sure 500+ part-columns in a spreadsheet is any form of usable, but I'm not the audience so maybe.

Maybe we need a more flexible bulkload builder. One that asks "How many parts will you need?" and "How many attributes per part?". This could be expanded to other ids, collectors and catalog record attributes, eliminating the need to give everyone who asks an option for 500+ columns that they have to pare down. Is this do-able?

> These would also have potentially confusing names - "part_12_attribute_determiner_6" or something. 

I agree the names will get weird, but if we don't test something like this we won't know if it is better or worse than what we are asking people to do now. I'd like to give this a shot and perhaps @lingnancollection or @cjconroy would agree to test for us?

**Comment by dustymc** [comment]
>get from one to the other without too much heartache.

That's really only possible in edge cases - it doesn't take much denormalizing to exceed the capabilities the software. Maybe that's really entirely where we live, I'm not so sure....

>flexible bulkload builder.

Yep possible.

**Comment by campmlc** [comment]
Is there a way to broaden the choices of what types of data we can download
into flat from catalog record results and other tables? I'd like to add in
loan numbers, for example, in addition to accessions which we already have.
We can customize the fields we download from catalog record results -
ideally, we could get downloads from other tables in a single flat file. Is
this just a customized SQL query?

**Comment by dustymc** [comment]
From https://github.com/ArctosDB/arctos/issues/3691

>Maybe we should try the 500-column approach and just add some number of attributes to each part in the core bulkloader, then build the new UIs around that?

>Whatever works best for you. Let's see what the community says when they see it...

It's not for me, I don't and won't deal with flattened data, and all options come with some kind of costs - they add complexity to the workflow, or columns to the spreadsheet, or exclude some use cases, or require more screen space, or SOMETHING. (And they all take some time to develop, but I think that's probably fairly equal here, and it seems like something that could be prioritized.) When I'm dealing with this it's usually in the context of a new collection, and the first thing I always do is normalize, which make everything easier (at least for me). I need some indication from the actual users of what's more desirable/tolerable/whatever we're looking for before I can do anything. https://github.com/ArctosDB/arctos/issues/3748#issuecomment-885019354 is still all of the options that come to me.

If I had to pick, I'd probably look at doing more with "extras", and perhaps building tools to separate the core "specimen bulkloader" template plus columns like part_73_attribute_value_6 out into individual loaders because it's more expandable - whatever we do for parts (for example) would also work for things like attributes and citation (and anything else in the component loader ecosystem.) I still don't have a clue if that would work for anyone else or not....

**Comment by Jegelewicz** [comment]
@itzuecs says she would be willing to test the "500-column" approach.

**Comment by lingnancollection** [comment]
@dustymc @Jegelewicz  @itzuecs  will be happy to help testing it when is ready!

**Comment by dustymc** [comment]
OK, unless someone has major objections or better ideas, I'll go next task after the details get worked out.

**Can we get by with fewer than 6 attributes?** 

Each one will add about 70 columns, a minimal but functional approach seems worthwhile. Is there any plausible/normal use case that requires more than 2 attributes per part on initial entry?

**Can we remove the "preservation" column?** 

Having full-blown attributes and a somewhat cryptic shortcut to one special attribute seems unnecessarily confusing to me.

Blocked by https://github.com/ArctosDB/arctos/issues/3629

**Comment by campmlc** [comment]
Two attributes seems reasonable to me. Can we have two attributes and an
optional methods column? Add an "Add more" click option?

**Comment by Jegelewicz** [comment]
> Can we get by with fewer than 6 attributes?

I think so and I agree with @campmlc that two is a good place to start. It was the need for two that set us on this path.

> Can we remove the "preservation" column?

YES - this is just causing confusion.

> an optional methods column?

While we are at this I think we should go ahead and add a method to these attributes #3629

**Comment by dustymc** [comment]
Are we OK to proceed with this?

1. Add to the bulkloader:

    * part_n_attribute_type_m
    * part_n_attribute_value_m
    * part_n_attribute_units_m
    * part_n_attribute_determiner_m 
    * part_n_attribute_date_m
    * part_n_attribute_remark_m
    * part_n_attribute_method_m

where ``n`` is existing parts (1-12) and ``m`` is number of attributes-per-part (2, per https://github.com/ArctosDB/arctos/issues/3748#issuecomment-888331746 - now is a **really** good time to change that if 2 isn't sufficient!).

Note that this will entail 168 new columns, "beginning" with part_1_attribute_type_1 (first attribute type for first part), and "ending" with part_12_attribute_method_2 (second attribute method for 12th part).

2. Remove from the bulkloader all part_preservation_n (which will remove 12 columns)

3. Figure out how to incorporate that into the data entry screen, and I have no idea where that's going to go or what the table (or????) might look like - help greatly appreciated.

**Comment by dustymc** [comment]
AWG: don't proceed, do more with 'extras'

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/3691 first, then revisit

**Comment by lingnancollection** [comment]
**Can we remove the "preservation" column?
 Having full-blown attributes and a somewhat cryptic shortcut to one special attribute seems unnecessarily confusing to me.**

@dustymc by that comment do you mean removing preservation column because preservation is an attribute type? I think the confusing part is that there are two ways to input the same data and it is not clear that is an option.

For example, the code tables for attributes do not list preservation as an option
[](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type)
[](https://arctos.database.museum/info/ctDocumentation.cfm?table=CTATTRIBUTE_CODE_TABLES
)
And part_preservation has its own code table as an independent column and is not intuitive that is an attribute
[](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_preservation)

**Comment by Jegelewicz** [comment]
> the code tables for attributes do not list preservation as an option

Yes they do - http://test.arctos.database.museum/info/ctDocumentation.cfm?table=ctspecpart_attribute_type#preservation

**Comment by Jegelewicz** [comment]
> Can we remove the "preservation" column?
> Having full-blown attributes and a somewhat cryptic shortcut to one special attribute seems unnecessarily confusing to me.

I think we should - it is only going to cause confusion and lead to poor data (incorrect preservation dates and information about preservation ending up in part remark instead of preservation remark).

**Comment by campmlc** [comment]
This should not be done until we make the full switch to a different UI and
to using the parts bulkloader, and get community feedback. Deleting it
right now would mean the parts table in data entry is non-functional - it
would require all part data be entered into "add more". I know there will
be significant community push back on that unless we provide a clear and
easy to use and well documented alternative.

**Comment by itzuecs** [comment]
> > the code tables for attributes do not list preservation as an option
> 
> Yes they do - http://test.arctos.database.museum/info/ctDocumentation.cfm?table=ctspecpart_attribute_type#preservation

Thanks for the ling @Jegelewicz! I was looking at this table that is call  

[ctattribute_type](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type) instead of [ctspecpart_attribute_type](http://test.arctos.database.museum/info/ctDocumentation.cfm?table=ctspecpart_attribute_type#preservation)

And this is the [ctpart_preservation](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_preservation) code table I mentioned before where not intuitive that is an attribute_type.

**Comment by dustymc** [comment]
You can see that in descriptive form from https://arctos.database.museum/info/ctDocumentation.cfm

<img width="949" alt="Screen Shot 2021-09-07 at 7 18 11 AM" src="https://user-images.githubusercontent.com/5720791/132360581-b25b24d9-a2fe-42a4-98da-3980081e1832.png">

Or the data connection is in https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspec_part_att_att

<img width="674" alt="Screen Shot 2021-09-07 at 7 19 24 AM" src="https://user-images.githubusercontent.com/5720791/132360776-2764f002-f0e9-4c18-92e0-8989c2b87b91.png">

(And anything which is in https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecpart_attribute_type and is not in https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspec_part_att_att is free-text.)

**Comment by dustymc** [comment]
New entry screen seems to work well enough even with the redundancy, closing.
