### ISSUE TITLE
uploaded records not showing up?

### ISSUE THREAD

**Issue by AWildAshAppeared** [ArctosDB/arctos#3749]
I uploaded around 9:30 am (MDT) this morning, but my records weren't showing up. I tried again a few minutes ago, and was notified that the catalog numbers were duplicates:
![Screenshot from 2021-07-20 14-19-33](https://user-images.githubusercontent.com/51430579/126390909-e4702ec4-43dc-47f1-a731-2aee15feee7f.png)

So I guess it was uploaded, just not visible yet--can anyone confirm that for me? I figure the delay is probably related to the downtime and everyone else trying to get their stuff uploaded too, but I just wanted to check. 

This is the file I uploaded: 
[UA_holotypes-2021-07-20.zip](https://github.com/ArctosDB/arctos/files/6851065/UA_holotypes-2021-07-20.zip)

**Comment by dustymc** [comment]
https://handbook.arctosdb.org/documentation/bulkloader.html#processing
