### ISSUE TITLE
disallow "inc" in agent name

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3753]
> mhubert7 just force-created agent Patrick Plastics inc. 

I don't think it's unreasonable to require "standard" abbreviations.

Need to check if that "word" appears in any legitimate way.

**Comment by dustymc** [comment]
"Inc." will be recognized as an abbreviation, which spawns the check. 

> If you do abbreviate, include an unabbreviated equivalent (e.g., “aka”) name.

**Comment by AJLinn** [comment]
I'll fix that - it's my student. I'll also teach him that he needs to include the aka of the unabbreviated.

**Comment by Jegelewicz** [comment]
This has been fixed - closing.

**Comment by dustymc** [comment]
>fixed

No....

**Comment by Jegelewicz** [comment]
The individual name has been fixed - what else are we trying to do?

![image](https://user-images.githubusercontent.com/5725767/126840771-fe9e6d75-5485-4efb-9d5b-0d921f57d03a.png)

**Comment by dustymc** [comment]
>trying to do?

Fix a problem rather than a symptom.

**Comment by Jegelewicz** [comment]
BUT what are we supposed to DO?

**Comment by dustymc** [comment]
Best case, new/better rules.

Failing that, new/better reporting.

Worst case, better documentation.

And often similar but different data gets discovered and brought into whatever happens.

**Comment by Jegelewicz** [comment]
I'm stumped and this issue will probably be here a year from now....
