### ISSUE TITLE
Separate Part Name from Part Preservation

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3762]
Proposal to separate part name (e.g. "tissue") from part preservation (e.g. "frozen").
Posting this as new issue related to repeated earlier discussion.

From email string:
These are clearly part attributes - they apply to parts, there can be many of them, they're determinations, they're time-dependent, etc. You can add them with the "add more" widget on data entry. We'll need to set up code table values before you can use them - that's fairly trivial, you can do it under edit code tables.

They can be bulkloaded with the parts bulkloader, and are in partdetail in specimen results/downloads.

I agree that preservation should not be confounded with part name. Getting it out affects lots of things (labels, the "tissues" search, data entry, etc.) so will need some discussion. Issue please.

----------------------------

Current status: https://docs.google.com/spreadsheets/d/1AY1EXQzKUSAg9EvZFjayTXcCBciXd_syCxt0GSX2tww/edit#gid=485619714 will serve as a migration path on 2021-07-01

**Comment by Jegelewicz** [comment]
Transferring back from documentation so we can find it.
