### ISSUE TITLE
Feature Request - Arctos Analytics

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#3766]
It looks like some of the query and usage statistics are deprecated. Is it possible to resurrect them? Additionally, I'd be very interested in tracking media views if possible.

**Comment by dustymc** [comment]
Need more information/specifics.

Media is available from...

<img width="373" alt="Screen Shot 2021-07-26 at 12 13 40 PM" src="https://user-images.githubusercontent.com/5720791/127045470-a41adf4f-5d62-49a9-8f4a-98333905004e.png">

**Comment by ebraker** [comment]
I'm trying to recall what data were previously available under query stats... perhaps monthly breakdown of # queries and # of downloads by country (?). 
The Exit Links gives me this:
![image](https://user-images.githubusercontent.com/11336485/127046252-06c2263c-1184-4b33-8c81-434eb4b530d8.png)
Instead, I'd like to know how many times a specific image is viewed so I can use this stat as a proxy for usage.

**Comment by dustymc** [comment]
> queries

That's...

<img width="419" alt="Screen Shot 2021-07-26 at 12 43 58 PM" src="https://user-images.githubusercontent.com/5720791/127049214-3173150c-fa9f-4562-b3db-2b0ba950f04e.png">


... see also https://github.com/ArctosDB/arctos/issues/2750

I should be getting a workable test environment soon, so that can probably be prioritized. I don't even know what the old UI looks like, a specific idea of what you're looking for would probably be useful.

You can also get archived data from https://arctosdb.org/hoarder/ - that should be documented, somewhere. (And see https://github.com/ArctosDB/arctos/issues/3768.)

The media report UI could be whatever, you can just download big blocks and sort them in a spreadsheet/local DB/whatever, or you can probably SQL something specific out. The table looks like...

```
arctosprod@arctos>> \d exit_link 
                                          Table "core.exit_link"
    Column    |            Type             | Collation | Nullable |               Default                
--------------+-----------------------------+-----------+----------+--------------------------------------
 exit_link_id | bigint                      |           | not null | nextval('sq_exit_link_id'::regclass)
 username     | character varying(255)      |           |          | 
 ipaddress    | character varying(255)      |           |          | 
 from_page    | character varying(4000)     |           |          | 
 target       | character varying(4000)     |           |          | 
 http_target  | character varying(255)      |           |          | 
 when_date    | timestamp without time zone |           |          | 
 status       | character varying(255)      |           |          | 
```

and one possible query:

```

select * from exit_link where target='http://web.corral.tacc.utexas.edu/MVZ/eggs/photos/jpg/127_egg.jpg';

 exit_link_id | username |    ipaddress    |                   from_page                    |                              target                               |                            http_target                            |      when_date      | status 
--------------+----------+-----------------+------------------------------------------------+-------------------------------------------------------------------+-------------------------------------------------------------------+---------------------+--------
           84 |          | 66.249.73.112   |                                                | http://web.corral.tacc.utexas.edu/MVZ/eggs/photos/jpg/127_egg.jpg | http://web.corral.tacc.utexas.edu/MVZ/eggs/photos/jpg/127_egg.jpg | 2013-10-30 21:39:38 | 200
       925508 |          | 66.249.65.197   |                                                | http://web.corral.tacc.utexas.edu/MVZ/eggs/photos/jpg/127_egg.jpg | http://web.corral.tacc.utexas.edu/MVZ/eggs/photos/jpg/127_egg.jpg | 2014-04-21 08:58:01 | 200
       563779 |          | 66.249.73.112   |                                                | http://web.corral.tacc.utexas.edu/MVZ/eggs/photos/jpg/127_egg.jpg | http://web.corral.tacc.utexas.edu/MVZ/eggs/photos/jpg/127_egg.jpg | 2014-02-23 12:40:11 | 200
      1939028 |          | 128.227.185.125 |                                                | http://web.corral.tacc.utexas.edu/MVZ/eggs/photos/jpg/127_egg.jpg | http://web.corral.tacc.utexas.edu/MVZ/eggs/photos/jpg/127_egg.jpg | 2014-11-13 04:14:06 | 200
      1162542 |          | 80.28.65.108    | http://arctos.database.museum/guid/MVZ:Egg:127 | http://web.corral.tacc.utexas.edu/MVZ/eggs/photos/jpg/127_egg.jpg | http://web.corral.tacc.utexas.edu/MVZ/eggs/photos/jpg/127_egg.jpg | 2014-08-09 13:33:55 | 200
      1698012 |          | 128.227.104.28  |                                                | http://web.corral.tacc.utexas.edu/MVZ/eggs/photos/jpg/127_egg.jpg | http://web.corral.tacc.utexas.edu/MVZ/eggs/photos/jpg/127_egg.jpg | 2014-11-07 01:59:16 | 200
      2423760 |          | 128.227.164.225 |                                                | http://web.corral.tacc.utexas.edu/MVZ/eggs/photos/jpg/127_egg.jpg | http://web.corral.tacc.utexas.edu/MVZ/eggs/photos/jpg/127_egg.jpg | 2016-03-18 18:40:09 | 200
(7 rows)
```

**Comment by ebraker** [comment]
Great! Yes, View Statistics > Query Statistics was giving me the "deprecated" message. 

A media statistics csv would be great. For my current purposes, being able to see how many times media connected to an NSF grant [project 10003438] (https://arctos.database.museum/project/10003438 )would be really useful for my annual grant report.

**Comment by dustymc** [comment]
```
create table temp_proj10003438 as
select
  media.media_id,
  exit_link.username,
  exit_link.from_page,
  exit_link.target,
  exit_link.http_target,
  exit_link.when_date,
  exit_link.status
from
  exit_link
  inner join media on exit_link.http_target=media.media_uri
  inner join media_relations on media.media_id=media_relations.media_id
where
  media_relations.media_relationship like '% project' and
  media_relations.related_primary_key=10003438
;
```
[temp_proj10003438.csv.zip](https://github.com/ArctosDB/arctos/files/6888950/temp_proj10003438.csv.zip)

**Comment by ebraker** [comment]
Awesome, thank you! Here's hoping that in time my username won't comprise more than 10% of all views!

**Comment by ebraker** [comment]
@dustymc when I paste the code in the SQL box I get the message 'contains illegal characters'...does everything look right?

create table temp_proj10003438 as
select
  media.media_id,
  exit_link.username,
  exit_link.from_page,
  exit_link.target,
  exit_link.http_target,
  exit_link.when_date,
  exit_link.status
from
  exit_link
  inner join media on exit_link.http_target=media.media_uri
  inner join media_relations on media.media_id=media_relations.media_id
where
  media_relations.media_relationship like '% project' and
  media_relations.related_primary_key=10003438
;

**Comment by dustymc** [comment]
It's complaining about both the terminator/semicolon (not allowed or needed in the web UI) and ``create table`` (use the CSV option instead) but the table has changed and that SQL won't run.

Try this:


```
select
media.media_id,
exit_link.username,
exit_link.from_page,
exit_link.when_date,
exit_link.status
from
exit_link
inner join media on exit_link.media_id=media.media_id
inner join media_relations on media.media_id=media_relations.media_id
where
media_relations.media_relationship like '% project' and
media_relations.related_primary_key=10003438
```

**Comment by ebraker** [comment]
That worked! Thanks!

**Comment by mkoo** [comment]
yea that semicolon is my biggest killer...

**Comment by dustymc** [comment]
Continue as part of https://github.com/ArctosDB/arctos/discussions/4031
