### ISSUE TITLE
bulkload post-reboot?

### ISSUE THREAD

**Issue by bryansmclean** [ArctosDB/arctos#3773]
We (UNCG:Mamm) are having problems loading records that were entered prior/during last week's shuffle.

I just marked them to load again (an hour or so ago), and no luck.
An example is accession [UNCG:Mamm]UNCG:Mamm_2020_August_1_Chattahoochee-Oconee

Is anyone else having similar hang-ups?

**Comment by bryansmclean** [comment]
Ah - ok. Found this in our previous comms. Is this Friday still a reasonable guess for them running again?

**Comment by Jegelewicz** [comment]
I believe so. I'll do my best to make sure we have an announcement if that changes.

**Comment by bryansmclean** [comment]
Staying tuned, then.
