### ISSUE TITLE
table column documentation

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3774]
1. Expand the table browser to non-core tables
1. Review UI and access
1. Add field descriptions for bulkloader
2. Add to bulkloader builder
1. Link to that rather than creating static (and generally immediately out-of-date) copies
1. Provide data via /api/

https://github.com/ArctosDB/documentation-wiki/issues/213

**Comment by Jegelewicz** [comment]
Not sure I get all of that, but let me know what I can/should do once you are done!

**Comment by dustymc** [comment]
I think the core is functional (but still being changed) in test if you want to play with it.

This is a merger of two things

* DDL pulled straight from the DB; if you want to know the current datatype (or indexes/keys/whatever), just click refresh and there's no chance you're looking at outdated documentation.
* The description is user-supplied and stored; it's a completely integrated place to document eg what sort of thing should go into {any_schema}.{any_table}.{any_column}, right beside the structural requirements.

Go here:

<img width="297" alt="Screen Shot 2021-07-28 at 9 09 20 AM" src="https://user-images.githubusercontent.com/5720791/127357853-4ddbbd81-3f1e-4f93-8a9e-6d95198f01ad.png">

Add/refresh as necessary, fill in description....

<img width="416" alt="Screen Shot 2021-07-28 at 9 11 05 AM" src="https://user-images.githubusercontent.com/5720791/127358088-16ebe7ad-4b00-4e8c-9bed-56615e0c2f6c.png">

... scroll down, click save.

All field-level documentation should happen here, and this should be the one authoritative place from which users get field-level documentation.

HOW users get docs from there needs sorted out. I added a CSV download option, so copy-pasting that into some static/markdown/whatever page is better than writing things out there (where it can't be re-used and can conflict with other docs and all that). Grabbing these data live via some sort of API (which would have to be created, but that's generally pretty simple) would be much better, but I'm not sure the current documentation system supports that very well. If we want to include more than table, column, and description we'd need to cache some things, but that should be pretty straightforward. Throwing up a public code-table-like view and just linking to it from the markdown might be a reasonable compromise.

I've removed delete table functionality and I'm working on some other semi-dangerous internal stuff. This should be a relatively safe app once I'm done, I think giving many more users (manage_collection or manage_specimens or something) access would not be much problem - they can mangle or delete field-level documentation, but they won't be able to break the stuff I use (and if this is more public someone will probably notice any manglings fairly quickly).

Where do we take this from here?

**Comment by Jegelewicz** [comment]
> Where do we take this from here?

Mexico?

Seriously though - I need to play a bit, but ti think linking this with the Documentation is what needs to happen once it is all in production.

I'll check it out in test this afternoon.

**Comment by Jegelewicz** [comment]
Just realized you are thinking bulkloader, but I started by looking at part. I'm not sure if what I did there makes sense?

http://test.arctos.database.museum/tblbrowse.cfm?action=tbldetail&tbl=specimen_part

Then I was thinking this could fit nicely into the Part Documentation, but a link to the page gets me 404 whether I am logged in or not. See https://handbook.arctosdb.org/documentation/parts.html

![image](https://user-images.githubusercontent.com/5725767/127386753-258548ad-0549-4dbb-9f32-e2dba7e39e90.png)

and it does weird things to the page...

**Comment by Jegelewicz** [comment]
Clearly, I don't understand the relationship between part and coll_object...

**Comment by dustymc** [comment]
>thinking bulkloader

Just because it seems to be an immediate/perpetual need, and I already had something that ALMOST served the purpose. (I think it fully does now, and it's not dying on some oracleish junk.) Adding docs for other stuff seems pretty useful to me, but I'm not sure it's so critical. (Or it is but nobody realized it was a possibility - that happens fairly often too.)

>embed

See above, not sure that's possible in markdown. Definitely not possible with this page - we'd need to throw a public view up for that. Should be quick, I'll try to sneak it in....

>relationship between part and coll_object

Parts are one kind of collection object. (Cataloged items are the other, there used to be more but I like normalization.)

**Comment by Jegelewicz** [comment]
> Parts are one kind of collection object. (Cataloged items are the other, there used to be more but I like normalization.)

I have no idea what that means....

When I put something in this field, what's that called?

![image](https://user-images.githubusercontent.com/5725767/127390815-b503b75b-316c-4869-8210-4ec05a86937d.png)

**Comment by dustymc** [comment]
specimen_part.part_name

**Comment by Jegelewicz** [comment]
OK - so this?

http://test.arctos.database.museum/tblbrowse.cfm?action=tbldetail&tbl=specimen_part

![image](https://user-images.githubusercontent.com/5725767/127392223-dc06f966-d118-4283-829f-96318b5705d2.png)

I sorta expected to see the part name code table on that page somewhere....how do we tell anyone that what goes in there is supposed to match stuff in http://test.arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name

It's supposed to, right?

**Comment by dustymc** [comment]
> sorta expected to see the part name code table 

That's why https://github.com/ArctosDB/arctos/issues/3452 exists.

>supposed to

Philosophically, sure. (And a trigger tries to make that a little more reality-based, but PG triggers don't impress me much.)

Structurally - there isn't a can't be a unique key on the CT, and so there isn't and can't be a key-based relationship.

**Comment by Jegelewicz** [comment]
Ah ha - I think I get that. So the code table link is buried in the trigger because it is always a combination of collection code and the part name code table?

For the purposes of telling users what they can and cannot put in there, a link to the code table would suffice. No? I put a link in the description, which is OK I think.

**Comment by dustymc** [comment]
>buried

Yes, until I can make some changes.

> users what they can and cannot 

I don't think I care, mostly.  If anyone would see it, I might use this to clarify why something exists, why it's where it is, why it has a particular datatype, etc., but I don't really have grand plans for the description. (I do use the constraints fairly often.)

For tables like the bulkloader (which is meant to accept anything and throw errors at validation rather than being structurally constrained) we might want a slightly different approach/view.

FYI at the moment I'm thinking that what you see can't be simplified much and still be useful, so there's not much reason to throw up a public view - my vague intent is to cache some more stuff (performance reasons), wrap "us stuff" in IF clauses, and make (most of) that view public - your links might work after all.

**Comment by Jegelewicz** [comment]
OK - I'm gonna wait on this for now.

**Comment by dustymc** [comment]
This is functional enough to be be public in next release.

I added a widget

<img width="255" alt="Screen Shot 2021-07-28 at 5 19 06 PM" src="https://user-images.githubusercontent.com/5720791/127412570-80cc44fe-66b1-413e-9bb2-5d9df38390d9.png">

it made the table below with 2 clicks and a splat-f, let me know if you want anything adjusted

|column name|description|data type|null?|length|code table|
|-----------|-----------|---------|-----|------|----------|
|collection_object_id|pkey|bigint|NO|||
|accn_id|fkey accn|bigint|NO|||
|collecting_event_id|IDK?|bigint|YES|||
|collection_id|fkey collection|bigint|NO|||
|cat_num|string, gets unconcatenated into components|character varying|NO|40||
|cataloged_item_type|type|character varying|NO|20|[ctcataloged_item_type](http://arctos.database.museum/info/ctDocumentation.cfm?table=ctcataloged_item_type)|
|cat_num_suffix|suffix, magicked|character varying|YES|10||
|cat_num_prefix|prefix, magicked|character varying|YES|10||
|cat_num_integer|integer, magicked|bigint|YES|||

**Comment by Jegelewicz** [comment]
Nice! Thanks!

**Comment by Jegelewicz** [comment]
I guess the only crappy thing is that this is just a snapshot and documentation would need a new one every time something changed?

**Comment by dustymc** [comment]
Correct. If you can figure out how to use it I could throw up something live pretty quickly, but I don't think that's possible in our doc environment so I don't plan to build anything until there's a solid use case.

**Comment by dustymc** [comment]
This is in production, but it won't run and I melted the front end trying. I'm going to disable it, throw this back to active development, and I'll keep fixing stuff in prod from test data.

**Comment by dustymc** [comment]
This is happy now, but I'll leave the issue open for adjustments - sort (or the lack thereof) is pretty annoying....

**Comment by dustymc** [comment]
This seems to be fully functional, needs documentation.

All "column definitions" should happen in the table browser, that can be copy-pasted (it's easy, there are tools) where it's needed.

https://handbook.arctosdb.org/documentation/bulkloader.html#fields / https://arctos.database.museum/tblbrowse.cfm?tbl=bulkloader seems like a good place to start, I've filled in some blanks.
