### ISSUE TITLE
error feedback

### ISSUE THREAD

**Issue by szaborac** [ArctosDB/arctos#3775]
I was attempting to update location data (verbatim date, verbatim location, specific locality, Georeferencing with GeoLocate, and Higher Geography) for record # UAM:Herb:196548 when I received the following error message.

An error occurred while processing this page! 
Message: /usr/local/webroot/WEB-INF/lucee/cfclasses/CF_opt_lucee_tomcat_lucee_server_context_library_tag8224/dump_cfc$cf.txt (No such file or directory)
Detail: 
Check the Arctos Handbook for more information on errors. 
This message has been logged as 54071BFC-A938-4C3C-979C617AA9EDB2B2 Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue.

**Comment by dustymc** [comment]
I believe that's from the update that's happening, but if the message is repeatable let me know enough detail to get it and I will investigate further.

**Comment by szaborac** [comment]
It just repro'd on another record -  UAM:Herb:194116.  All I did in THIS case was update the Georeference data with GeoLocate. I am unsure what other repro steps you need - could you provide more info, please?  

Here's the error dump:  

An error occurred while processing this page!
Message: /usr/local/webroot/WEB-INF/lucee/cfclasses/CF_opt_lucee_tomcat_lucee_server_context_library_tag8224/dump_cfc$cf.txt (No such file or directory)
Detail:
Check the Arctos Handbook for more information on errors.
This message has been logged as DC7302AB-B53C-4AF7-8E0F54D963A90F06 Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue.

**Comment by szaborac** [comment]
Dusty and all - Should I perhaps NOT be working in Arctos right now, if you
are actively trying to update the system?  I didn't realize you were making
changes, and I feel bad about messing up the records.

**Comment by dustymc** [comment]
>update the Georeference data with GeoLocate

There are a lot of ways to do that - I think I figured it out, but links, screenshots of the specific buttons you've clicked, etc. are immensely useful.

I think I found the problem (https://luceeserver.atlassian.net/browse/LDEV-2354) and it seems to be working for me, assuming I'm following a similar path.

Working is fine, some things may just not be processed into all views.

**Comment by szaborac** [comment]
Ok! Thank you!

**Comment by Jegelewicz** [comment]
Can we close?

**Comment by szaborac** [comment]
Yes - this issue seems to have been resolved as of Wednesday's fixes.

Thank you!
