### ISSUE TITLE
higher taxonomy disconnected

### ISSUE THREAD

**Issue by droberts49** [ArctosDB/arctos#3776]
Hi Dusty @dustymc 
Today as I was working with our teaching collections (CHAS:Teach) I saw that for many of our records, the higher taxonomy has disappeared! The records still contain the specimen identification, but that has become disassociated from the higher taxonomy. If I'm searching for Family, Order, or even Class level, the records aren't getting pulled up. This is only affecting our teaching collection, not our other collections.

Here is a saved search for our teaching collection:  https://arctos.database.museum/saved/teaching%20collection%202019-05-28

You can see that the specimens have identifications, but there is no data appearing in the higher taxonomy fields for the majority of the specimens. 
example:
CHAS:Teach:2003.2.1 -- Aix sponsa, Wood duck -- https://arctos.database.museum/guid/CHAS:Teach:2003.2.1
![image](https://user-images.githubusercontent.com/16580148/127368676-43f1070a-0af0-426c-b96f-4b5e96e787af.png)

CHAS:teach:2020.5.3 -- Euphydryas phaeton, Baltimore checkerspot -- https://arctos.database.museum/guid/CHAS:Teach:2020.5.3

The higher taxonomy was there previously. It is impossible to get some of our cataloguing done without having that taxonomy hierarchy. Help please! 
Dawn

**Comment by dustymc** [comment]
I think this is just a symptom of the service outage. I picked one that doesn't look complete

https://arctos.database.museum/guid/CHAS:Teach:E2013G.2

<img width="628" alt="Screen Shot 2021-07-28 at 10 40 33 AM" src="https://user-images.githubusercontent.com/5720791/127370513-4a628c92-e38b-4c1c-b975-336cc867bc21.png">


and manually refreshed it

```
select update_flat_row(collection_object_id) from flat where guid='CHAS:Teach:E2013G.2';
 update_flat_row 
-----------------
 
(1 row)
```

and that seems to be working properly, it's just not being automated on the temporary server we're using at the moment.

<img width="616" alt="Screen Shot 2021-07-28 at 10 41 41 AM" src="https://user-images.githubusercontent.com/5720791/127370675-d987b7aa-cddc-448c-a5fd-afe61ec8badb.png">

**Comment by droberts49** [comment]
@dustymc  OK, thank you Dusty. Sounds like I can be patient and give it a few more days?

**Comment by dustymc** [comment]
Yes, I don't have a better solution.
