### ISSUE TITLE
How to remove error in bulkloader

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#3779]
# Error Text
Error and units, datum, and georeference source and protocol must be accompanied by coordinates

# Where it happened
Bulkload Browse and Edit

# Problem
If you have one of datum, georeference source, georeference protocol, or coordinates, you must have all of them.

# Solution
Complete all of the fields listed above or remove any data from all of them

Can someone help me get rid of this error in my records?
I did not geolocate these records and I'm still getting this error (I tried to make a polygon in the mapping tool when doing data entry but it didn't work...)

![Screen Shot 2021-04-16 at 2 38 46 PM](https://user-images.githubusercontent.com/17605945/115090916-9aa0b700-9ec2-11eb-90f2-ea789306ed68.png)

**Comment by Jegelewicz** [comment]
closing, but now searchable with label
