### ISSUE TITLE
De-specimening of Arctos (continued)

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#3780]
The Agent Activity page has "specimen" recorded in two places that could be replaced with "count" and "open catalog records":

![image](https://user-images.githubusercontent.com/11336485/127510674-4ab5c579-2c21-438b-aa24-1ae1894f2f95.png)

**Comment by Jegelewicz** [comment]
@dustymc I think I can get that...

**Comment by dustymc** [comment]
You're way too late....

**Comment by Jegelewicz** [comment]
Dang it!
