### ISSUE TITLE
Arctos Outage: July 30 2PM PDT

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3785]
Arctos will be going down for continued upgrades starting at 2PM Pacific tomorrow.

**Comment by ewommack** [comment]
@dustymc - send out to the listservs?

**Comment by campmlc** [comment]
Yes, we should let folks know right away.

**Comment by dustymc** [comment]
Yes please - and https://github.com/ArctosDB/arctos/issues/3777 if you have better ideas for how this should be handled.

**Comment by AJLinn** [comment]
Hmmm, already down now?

**Comment by dustymc** [comment]
Nope, seems pretty zippy to me.

**Comment by AJLinn** [comment]
Okay thanks. I was just endlessly spinning on Brave. Opened in Chrome lickety split.

**Comment by ewommack** [comment]
@dustymc - just took the initiative and sent out an announcement to the listservs.

**Comment by ewommack** [comment]
And just posted on the Slack channel

**Comment by dustymc** [comment]
Arctos is now available. The services will take a couple days to catch up, I'll continue monitoring.

**Comment by mkoo** [comment]
Please send an announcement to that effect. It's zippy for me this morning
for simple searches.... thanks!

**Comment by Jegelewicz** [comment]
Done.

Arctos is now available. Please file an issue if you notice any problems with functionality.
