### ISSUE TITLE
Exploding computers on catalog search page

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#3786]
**Describe the bug**
Just trying to conduct a search that uses a number of criteria, dependent on attributes and I'm getting errors on the search page in the length_units and ctAttributeType. Permit Types are also showing an error.

**Expected behavior**
No errors should occur on the search page

**Screenshots**
<img width="871" alt="Screen Shot 2021-07-29 at 5 40 19 PM" src="https://user-images.githubusercontent.com/17605945/127587124-187c0f83-feb6-4daf-9e09-f04af09081c0.png">

**Desktop (please complete the following information):**
Tried in the following browsers with the same effect, as both a public user or operator:

- Chrome
- Brave
- Firefox
- Safari
- Opera

**Additional context**
Was working fine earlier today...

**Priority**
Critical - actively preventing all users the ability to search for objects using attributes.

**Comment by dustymc** [comment]
I restarted the services - something was very out of sync with itself!

**Comment by AJLinn** [comment]
Yay, all is happy again!
Thank you for the quick attention. :-)
