### ISSUE TITLE
Records won't load

### ISSUE THREAD

**Issue by aklompma** [ArctosDB/arctos#3787]
For days, I have been trying to load 5 new records into Arctos:
collection_object_id: 97589857 to 97589861   (=ALMNH:Paleo:20184 to 20188) but to no avail so far.

I have load all these records multiple times. I do not get an error message.

After clicking click here in "Please review the table below. If all looks correct, click here to proceed to NULL loaded for all listed records." I get "Marked. Back to table" and then nothing happens.

Did I forget to fill out something?

**Comment by Jegelewicz** [comment]
@aklompma none of the loading scripts have been running since last week while TACC is doing some hardware transitioning. We hope to have them running next week. See #3777

**Comment by aklompma** [comment]
Thanks! In that case, I will just continue with entering data the way it was done and wait till the hardware issue is taken care of.

**Comment by Jegelewicz** [comment]
@dustymc is this ok to post on the banner?

You can load data to the main bulkloader and to the bulkload tools, but the background load to Arctos task is currently disabled. We hope to have loading resume next week. Thanks for your patience!

**Comment by dustymc** [comment]
yep
