### ISSUE TITLE
Arctos object tracking find part container not working

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3788]
This has been happening at least since yesterday - hopefully will be restored once we get back onto production server?
Go to: Object Tracking, Find Container
Find barcode or list of barcodes, or alternately, do a search on a list of catalog record and go to Manage: Part Location
From object tracking results - see that none of the parts have locations - they show up in the universe
But: these parts do have positions in the catalog record, and the part location can be found by clicking down through the object tracking tree in Find Container
Priority: high

**Comment by dustymc** [comment]
This seems to be a change in lucee (or perhaps java), which only matters because of the antique library we use for hierarchies.

I'll see if I can find a workaround, but this is not sustainable. If I run out of duct tape or baling wire, reverting to an older version of lucee seems to "fix" this but introduces other issues.

We MUST find a way to acquire/maintain/support software that isn't old enough to vote.

See also https://github.com/ArctosDB/arctos/issues/3460#issuecomment-786340595

**Comment by campmlc** [comment]
Any thoughts on how long this might take to restore functionality? This
seriously affects our day to day workflow.

**Comment by campmlc** [comment]
From MSB staff:
Hey! I’m trying to change container types so I can bulkload some data. (Arctos stopped me from loading an accession because I can’t put stuff in labels!) So, I’m trying to change everything to cryovial. The attached spreadsheet is all the containers that didn’t change because the old container type was wrong (grr). But what’s weird is when I look them up individually to see what the old container type is, I get Genomic Resources as the result instead of the barcode. I didn’t check all of them, but the first several return the same result.

 

Any idea what’s up or how to fix it? Or is this a Dusty question?

**Comment by campmlc** [comment]
upping priority to critical. Actively preventing transactions and object tracking.

**Comment by amgunderson** [comment]
From any search result the "part location" option in the "manage" drop down menu is not working, it does not show all parts  and shows partial locations for some parts. This is a huge hindrance to putting things away in the collection. Apparently the "parts table/download" feature still works for finding part locations. I will use that now. Maybe make that the part locations function and remove the one that does not work.

**Comment by dustymc** [comment]
I'm hoping to have a solution tonight, but everything that can go wrong is doing so today and I'm not yet sure if that will happen.

**Comment by campmlc** [comment]
If you know where in the hierarchy a container is located, you can find it
by going down through the hierarchy. But the point of object tracking is to
find objects without already having to know where they are, and that is not
working.

**Comment by campmlc** [comment]
Whohoo! Thank you!!
