### ISSUE TITLE
create category "lithostratigraphic unit" in locality attributes and add "Blue-gray clay" to it

### ISSUE THREAD

**Issue by aklompma** [ArctosDB/arctos#3789]
When entering locality attributes to a record, I would like to request adding the category "lithostratigraphic unit" and could someone add "Blue-gray clay" as one of the options under this category?
The reason is that not all sedimentary units are assigned to a lithostratigraphic formation, member, bed, or group. We have various records of fossils coming from this clay.

**Comment by dustymc** [comment]
I believe https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlocality_attribute_type#geology_remarks is appropriate for this.

**Comment by aklompma** [comment]
This works, thanks.
