### ISSUE TITLE
Specimen Event Bulkload Tool Error

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3792]
Please close if this is just part of the moves at TACC.

I tried to upload a csv to the [Specimen Event Bulkload Tool](https://arctos.database.museum/tools/BulkloadSpecimenEvent.cfm) today and received this error

An error occurred while processing this page!
Message: Error invoking external process
Detail: psql: error: could not connect to server: could not connect to server: Connection refused Is the server running on host "129.114.52.14" and accepting TCP/IP connections on port 5432?
Check the Arctos Handbook for more information on errors.

This message has been logged as 60EA97F3-931E-42DC-BD1C19037EDD283A Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue.

**Comment by dustymc** [comment]
Try now, attach data if it doesn't work.

**Comment by Jegelewicz** [comment]
worked like a charm.
