### ISSUE TITLE
Arctos Down - authentication failed

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3797]
Please complete to the best of your ability.
Trying to log in with my usual credentials,  I get an authentication failed error. I requested a new password but got the same error with the new password.

## Communication before/during outage
- [x] Pin this issue
- [ ] Banner updated @jegelewicz 
- [ ] Email sent to AWG @ewommack 
- [ ] Email sent to Arctos Google Group @ewommack 
- [ ] Tweet @lin-fred 
- [ ] Update to arctosdb.org @mkoo 

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @jegelewicz
- [ ] Email sent to AWG @ewommac
- [ ] Email sent to Arctos Google Group @ewommac
- [ ] Tweet @lin-fred
- [ ] Update to arctosdb.org @mkoo
- [ ] Close this issue when above are complete

**Comment by Jegelewicz** [comment]
Ditto

**Comment by dustymc** [comment]
I just killed almost all connections, hopefully that's less disruptive than the previous situation.

**Comment by campmlc** [comment]
That worked for me.

**Comment by Jegelewicz** [comment]
@cefilipek let us know if this didn't work for you.

**Comment by cefilipek** [comment]
@Jegelewicz I was able to log in!
