### ISSUE TITLE
Media Upload Outage

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3798]
## Planned Outage
 - 2021-08-04T0000
 - 2021-08-04T2359 
 - Reason for outage: system maintenance
 - Expected behavior during and after the outage:

The individual media loader (and anything else that uses S3) will be down for at least a couple of hours tomorrow, but plan to not use that pathway all day. 

## Communication before/during outage
- [x] Pin this issue
- [x] Banner updated @jegelewicz 
- [x] Email sent to AWG @ewommack  sent by @Jegelewicz 
- [x] Email sent to Arctos Google Group @ewommack  sent by @Jegelewicz 
- [x] Tweet @lin-fred see https://github.com/ArctosDB/newsletter/issues/85
- [x] Update to arctosdb.org @mkoo 

## Communication after outage
- [x] Unpin this issue
- [x] Banner updated @jegelewicz
- [x] Email sent to AWG @ewommack
- [x] Email sent to Arctos Google Group @ewommack 
- [x] Tweet @lin-fred
- [x] Update to arctosdb.org @mkoo
- [x] Close this issue when above are complete

**Comment by amgunderson** [comment]
Is this why all UAM:Mamm specimen records return a 404 page not found error?

**Comment by dustymc** [comment]
@amgunderson no and that should be fixed now

**Comment by amgunderson** [comment]
Thanks, that was scary.

**Comment by mkoo** [comment]
Does this work?
https://arctosdb.org/status/
as a spot for ongoing status notes?

@amgunderson yea I can imagine the fright!

**Comment by ewommack** [comment]
@Jegelewicz was awesome and caught up the notice when I missed this yesterday!

**Comment by dustymc** [comment]
This is complete and back in service.

**Comment by Jegelewicz** [comment]
@mkoo this brings up the need for an update once an outage is complete - thoughts on adding a "All systems go" or something whenever there aren't any issues?

**Comment by Jegelewicz** [comment]
Message to Arctos and Working Group

> The Arctos media loader is up and running. Please file an issue if you experience any problems with it.
