### ISSUE TITLE
Error on Search as Operator

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3800]
Trying to search as an logged in operator on an NK, get the following error:
An error occurred while processing this page!
Message: ERROR: function concatattributevalue(bigint, unknown) does not exist Hint: No function matches the given name and argument types. You might need to add explicit type casts. Position: 1413

Log in to Arctos
Go to: Search Catalog Record
Enter: 269055 in Other Identifier is
Get weird error
BUT
Logged out, this search works

**Comment by dustymc** [comment]
should be cleared up
