### ISSUE TITLE
Bulkloader Browse and Edit feature not working

### ISSUE THREAD

**Issue by AdrienneRaniszewski** [ArctosDB/arctos#3801]
I**Describe the bug**
The Bulkloader Browse and Edit feature stopped working today while I was in the middle of using it

**To Reproduce**
1. Go to Blukloader / Browse and edit
2. without doing anything further, an error pops up in browser "DataTables warning: table id=bedit - [object Object]"
same result when attempting to filter records

**Expected behavior**
I expected to see everything currently in the bulkloader and then be able to filter it based on my selections

**Screenshots**
<img width="1220" alt="Screen Shot 2021-08-03 at 1 39 28 PM" src="https://user-images.githubusercontent.com/23192428/128077327-88552993-763c-4348-ae33-2e6c3e7d14ea.png">

**Desktop (please complete the following information):**
 - OS: Mac OS 10.12.6 & 10.15.7
 - Browser: chrome and safari
 - Version: Chrome 92.0.4515.131 & Safari 14.1.2 

**Priority**
high

**Comment by dustymc** [comment]
jiggled the wires
