### ISSUE TITLE
Relationships Bulkload error

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3802]
Got the following error after downloading the csv bulkload template for unreciprocated relationships from the email, and reloading it to Bulkload Identifications/Relationships:
An error occurred while processing this page!
Message: Error invoking external process
Detail: psql:/usr/local/webroot/temp/excopy_campmlc_20210803020805402_329.sql:1: ERROR: column "new_other_id_type" of relation "cf_temp_identification" does not exist
Check the Arctos Handbook for more information on errors.
![Screenshot 2021-08-03 13 52 01](https://user-images.githubusercontent.com/14808196/128077448-c169884f-2b7b-4ba1-9df0-8fcf56216746.png)
[PendingReciprocalRelations (1).zip](https://github.com/ArctosDB/arctos/files/6926734/PendingReciprocalRelations.1.zip)

**Comment by dustymc** [comment]
Check the title, URL, and error message - you are in the wrong form.

**Comment by bryansmclean** [comment]
Hey @campmlc, this was ultimately related to ensuring reciprocal linkages got created from host - back to -> parasite.
Can we keep thinking about this?

**Comment by Jegelewicz** [comment]
@campmlc I can help - let me see if I can work it.

**Comment by Jegelewicz** [comment]
@bryansmclean go to https://arctos.database.museum/tools/BulkloadOtherId.cfm and look at the stuff under my username (jegelewicz) by selecting review. If everything looks OK, you can set them to load (I think you should have permission, if not let me know here).

**Comment by campmlc** [comment]
So I wasn't in the wrong form?

**Comment by Jegelewicz** [comment]
Yes, you were. You were here https://arctos.database.museum/tools/BulkloadIdentification.cfm

**Comment by Jegelewicz** [comment]
I loaded them here: https://arctos.database.museum/tools/BulkloadOtherId.cfm

**Comment by campmlc** [comment]
That's what I get for trying to do something fast. It's hard to click on the right dropdown when they have the same term and are right next to each other in the tiny display box on my laptop screen. Perhaps separate those two in the interface?

Also, @dustymc reminder that we were to ask you about fixing the records loaded by sara: they are duplicates, but we can't delete them, get 400 Bad Request error.

**Comment by Jegelewicz** [comment]
> Perhaps separate those two in the interface?

We have been sticking (I think) with alphabetical order for the menus...

**Comment by campmlc** [comment]
How about changing it to OtherIDs/Relationships, since that matches the
bulkload header and data entry.

**Comment by Jegelewicz** [comment]
Yeah, just realized that menu is in no way alphabetical either...

**Comment by bryansmclean** [comment]
Sorry I fell off this thread - but just checked and @Jegelewicz I dont see any relationships to approve on that page. Am I missing something?

**Comment by campmlc** [comment]
Can you check the relationships and see if they loaded?

**Comment by bryansmclean** [comment]
@campmlc I checked 3 random host specimens and none had links (but their associated parasites do)

**Comment by Jegelewicz** [comment]
@bryansmclean you don't see this?

![image](https://user-images.githubusercontent.com/5725767/129049736-eddc3caf-4b56-47c4-8101-d72227551694.png)

**Comment by bryansmclean** [comment]
No... 

![image](https://user-images.githubusercontent.com/8601578/129052006-252b9c93-d8ff-4b63-ac50-e3d41151dc14.png)

**Comment by Jegelewicz** [comment]
@dustymc any way I can allow @bryansmclean to see what I loaded for him? I guess I am still not really clear who can see what in these tools....

**Comment by Jegelewicz** [comment]
He has manage collection.

**Comment by campmlc** [comment]
I just looked at the records in the bulkloader loaded by jegelewicz and I
could not see any records for UNCG relationships.

**Comment by campmlc** [comment]
BTW I dealt with a bunch of the unrelated MSB ones.

**Comment by campmlc** [comment]
This is the file of those 391 records. None are UNCG.

[BulkloadOtherIdData (3).zip](https://github.com/ArctosDB/arctos/files/6969439/BulkloadOtherIdData.3.zip)

**Comment by dustymc** [comment]
I don't have access to UNCG - I'm guessing you don't either if you can't see each other's records, but I can't do more than guess from here.

**Comment by Jegelewicz** [comment]
I loaded the file included in the very first post in this issue - which apparently has no UNCG relationships - so I guess there is a file somewhere else....

**Comment by campmlc** [comment]
@bryansmclean do you have a file with these data for UNCG?

**Comment by bryansmclean** [comment]
No, Ive never seen the file generated.
We could just download all the UNCG:Para records (which have the host linkages in them)

**Comment by campmlc** [comment]
You should have gotten a relationships notification with the unreciprocated relationships. @dustymc How often do these go out? And where can we find the pending unreciprocated relationships outside of the email?
We obviously need to clarify this process.
In the meantime, we can download the existing records, but it would be easier if @dustymc could just pull up the list.

**Comment by Jegelewicz** [comment]
Find that here

<img width="960" alt="Screenshot 2021-08-11 10 38 28" src="https://user-images.githubusercontent.com/5725767/129068673-9f2320b2-b1a8-486b-bbc3-00762776b539.png">

**Comment by Jegelewicz** [comment]
@dustymc how about we add a link to that from the bulkload page?

**Comment by dustymc** [comment]
The notification is weekly (I believe because you asked for that).

The component loaders aren't quite built automatically, but they're close - I'm sure that link would not survive the process.

**Comment by campmlc** [comment]
Can we add the link to the OtherID/Relationships bulkload dropdown? That
would be where we'd be looking for it.

**Comment by Jegelewicz** [comment]
Added for next release

**Comment by campmlc** [comment]
Thanks! I'll see if I can download the file for upload later today, or
Bryan can tackle it.

**Comment by bryansmclean** [comment]
OK Ive uploaded the relationship file, and they are marked to load. Will chime back in with results.
