### ISSUE TITLE
attempt to print labels throws an error

### ISSUE THREAD

**Issue by keg34** [ArctosDB/arctos#3804]
# Error Text
function concatattribute(bigint) does not exist 

# Where it happened
# Steps to get there
Tried to print labels for specimens in the search results window via Manage>Print stuff>Print any report.  Went to the report list as directed, selected NMZ_Mamm_vial_label. Hit Print Report and got the error.  I note that if I go to Reports/Services/Labels and Reports>Reporter to get the full list of report templates, click Edit Handler for the template named above, and then click Test SQL, it also throws an error.  I generally handle these problems by borrowing the handler SQL code from another collection, but that isn't working here.  Any advice appreciated.  Apologies if this has been solved elsewhere and I missed it.

Here's a screenshot:
![image](https://user-images.githubusercontent.com/17340466/128080736-4a5f3247-d9ad-4496-92ed-1028b5afb553.png)

**Comment by dustymc** [comment]
Thx, wires jiggled

**Comment by keg34** [comment]
Sweet - thanks!
