### ISSUE TITLE
Search Page Down for Logged Out users

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#3805]
When navigating to the main catalog record search page (https://arctos.database.museum/SpecimenSearch.cfm) while logged out, I get this error:
![image](https://user-images.githubusercontent.com/11336485/128081885-d9759ddd-dae6-4ad7-a0ac-ca0bb3e9f500.png)

However, every other search page (taxonomy, media, etc.) displays. This issue holds true for a student working with me on a different computer.

If I log in, I am able to see the main search page, so it may be an issue associated with permissions?

**Comment by dustymc** [comment]
It's the connection thing, not permissions. I flushed a bunch, let me know if that didn't do it and I can restart the front end.

**Comment by ebraker** [comment]
That worked! Thanks!
