### ISSUE TITLE
Data Entry Error

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3808]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Hi, Teresa. I don’t know what S3 is, but I am staying away from media stuff today. However I’m trying to enter a record in the data entry screen and it’s not working (it was yesterday). Got this message from my browser “SyntaxError: Unexpected token < in JSON at position 0” Is this related to the media loader outage? Or is it something unrelated that I should report in github?
~ Adrienne
 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by dustymc** [comment]
thx/patched

**Comment by AdrienneRaniszewski** [comment]
works great! Thanks!

**Comment by AdrienneRaniszewski** [comment]
uh... except I tried to edit the record I just entered. (forgot to add a remark). save fails and I get this

record failed checks: ERROR: column "collecting_event_id" is of type bigint but expression is of type character varying Hint: You will need to rewrite or cast the expression. Position: 4762DETAIL: SQL: UPDATE bulkloader SET collection_object_id=collection_object_id ,loaded='waiting approval' ,enteredby='AdrienneR' ,accn='[MSB:Mamm]2019.075.Mamm' ,guid_prefix='MSB:Mamm' ,cat_num=null ,other_id_num_1=null ,other_id_num_type_1=null ,other_id_references_1=null ,other_id_num_2=null ,other_id_num_type_2=null ,other_id_references_2=null ,collector_agent_1='Robert A. Nofchissey' ,collector_role_1='collector' ,collector_agent...

**Comment by dustymc** [comment]
derp - try again plz

**Comment by AdrienneRaniszewski** [comment]
still getting the same error

**Comment by dustymc** [comment]
Doublederp - again please

**Comment by AdrienneRaniszewski** [comment]
got it! thanks!
