### ISSUE TITLE
[CONTACT: Blocked Network]

### ISSUE THREAD

**Issue by llparmisana** [ArctosDB/arctos#3810]
restricted IP: 136.158.0.205

Hello! I'd like to request to have my IP Address blocked. I'm a student from Polytechnic University of the Philippines who's checking options that we can field for archiving, preservation, and presentation of herbarium data. Please let me know what I can do to rectify the issue. 
Thanks!

**Comment by dustymc** [comment]
Released.

**Comment by llparmisana** [comment]
Thanks! Really appreciate it!
