### ISSUE TITLE
Can't edit borrow

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#3811]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I'm trying to edit & access my Borrow UAM:EH 1973-002 and when I select "Edit Borrow" I get this error message with accompanying exploding computer:

<img width="1630" alt="Screen Shot 2021-08-05 at 11 37 16 AM" src="https://user-images.githubusercontent.com/17605945/128410755-0e511d2c-c177-4d0a-b037-d3610a06c8d1.png">

**To Reproduce**
1. Search for UAM:EH borrow 1973-002
2. Click Edit Borrow at results list
3. See error

**Expected behavior**
I'd like to be able to edit my borrows.

**Desktop (please complete the following information):**
MacOS 11.4
Brave Browser version 1.27.109 (up to date)

**Priority**
Critical - actively preventing a renewing of a borrow.

**Comment by dustymc** [comment]
Sepelling iz knot ez....

Patched.
