### ISSUE TITLE
change help text at top of Agent Search page

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#3813]
The current text is a wee bit confusing and does not include all the agent types we are now tracking. We suggest to replace the text with the following:

```
Agents in Arctos are either people, entities, organizations or organisms tracked in the database.
```

**Comment by Jegelewicz** [comment]
Well - I am not sure we have actually agreed to use this for entities or organisms......

**Comment by mkoo** [comment]
We're looking at Kianga again and after today's meeting, I am coming around to this idea of a dashboard for agents.... and especially if we add in collections as agents!

**Comment by Jegelewicz** [comment]
BUT - I don't think we want a bunch of "organisms" mixed in? Or maybe we do. Eventually we could have "pocket mouse #1" as an agent.....

The functionality is perfect, but I think we might consider keeping people and organizations separate from other organisms. If everyon is OK with them being together, then we at least need some new agent types....

**Comment by dustymc** [comment]
>don't think we want a bunch of "organisms" mixed in?

Absolutely not, at least without discussion and new agent types, and the existing non-human Agents should be removed.

FWIW the things that have been asked for in Entities are the things that cataloged items have always done; I think we rushed Entity creation (and it's not been much used, but perhaps we'd have not known without doing something), and that we should remove the "entity node" and transfer any useful functionality to https://github.com/ArctosDB/arctos/issues/1966#issuecomment-832839040, both as a matter of "corectness" and of sustainability.

**Comment by Jegelewicz** [comment]
> things that have been asked for in Entities are the things that cataloged items have always done

I am not sure I agree with this assessment - clearly, the things we are seeking in an entity are the things that agents do....

**Comment by mkoo** [comment]
ah, yea, organism is way too vague.

But I would say we may want to track George the pocket mouse if it's an
experimental animal with lots of separately cataloged biopsies (just not
the organism pocket mouse.

I think we need to review the other_agents -- most of those are organisms
or groups, not 'other agents'. Or just badly informed agents (initials
only). What is 'other_agent' if not a non-human agent?

Let's roll this issue into a broader discussion on tracking living
collections

**Comment by dustymc** [comment]
They don't have bulk tools, catalog records do.

https://github.com/ArctosDB/arctos/issues/1966#issuecomment-850725139

They don't have identifications, certainly not those backed by taxa, catalog record do.

They don't have more than "this is me" 'other id' functionality; catalog records do.

They cannot hold attributes; catalog records can.

https://github.com/ArctosDB/arctos/issues/1966#issuecomment-848840982

They don't have mature tools supported by a broad user group: https://github.com/ArctosDB/arctos/issues/3765

More stuff that existing bulk tools handle: https://github.com/ArctosDB/arctos/issues/3685

I'm sure there's more, but I'm having a lot of difficulty nailing down anything in any of the discussions that can happen within Arctos and is not handled by catalog records.

Anything we do to make relationships between or bulk tools for catalog records more functional works for many use cases. (Anything we do with Entities will work for only limited use cases.)

If there's a disadvantage it's that catalog records of type {something new and appropriate} might look like an independent Occurrence, but if we're cataloging critter-at-place-and-time we're already doing that (and relying on users to recognize it) - again, any work towards making that more clear will have broad impacts.

**Comment by dustymc** [comment]
> review the other_agents 

Many can be deleted - https://github.com/ArctosDB/arctos/issues/882 has been hanging around way too long, it needs implemented and documentation needs updated.

Most seem to be miscategorized people, organizations, and groups - https://arctos.database.museum/info/ctDocumentation.cfm?table=ctagent_type



```
 create table temp_other_agent as select preferred_agent_name from agent where agent_type='other agent' order by preferred_agent_name;
```
[temp_other_agent.csv.zip](https://github.com/ArctosDB/arctos/files/6942060/temp_other_agent.csv.zip)

**Comment by mkoo** [comment]
i think you're overthinking this. You're right all those things are cat_items and no issues there. beyond the normal relating of specific records to each other how can people find an individual and all their Arctos records?
https://arctos.database.museum/info/agentActivity.cfm?agent_id=21332262

Here's an example of all this chimpanzee's samples, its wikidata page, all id's in one manageable, query-able, understandable page.

**Comment by dustymc** [comment]
If that's all you want, then there should be (have been) a discussion about agent type - this is clearly a different THING, and Arctos users have complained about finding this there.

If you want to do things that Agents can't do, then it's the wrong data object (and I can't understand the requests to do those things).

**Comment by mkoo** [comment]
how reliable is Agent Activity report?
https://arctos.database.museum/agents.cfm?agent_id=10000002
if there are no data dependencies, ok to delete?
Maybe @***@***.***
***@***.***> or @Cynthia
Carr ***@***.***> could help too?

**Comment by mkoo** [comment]
yep, we should clean up other_agent, discuss a definition for it, possibly
explore a better and new agent type for this use.

No new things that Agents cant do, so might be simply an interface issue
(eg., separate search for people and orgs and another for whatever else is
that those two things)

**Comment by Jegelewicz** [comment]
I like the idea of adding a new agent type and suggest:

organism - any **non human** organic, living system that functions as an individual entity. [Wikipedia](https://en.wikipedia.org/wiki/Organism). Humans should be assigned and agent type of person, group or organization.

Honestly - I have never even looked at other-agents and a bunch of them should be organizations and yes, a bunch really are projects and not agents unless they can be changed to groups and all the person agents who were on the expedition are added. (Even then they probably should have associated projects).

Can we get a list of them so we can put them in a sheet and make bulk decisions about what to do with them?

**Comment by mkoo** [comment]
#3815

**Comment by Jegelewicz** [comment]
> George the pocket mouse if it's an experimental animal with lots of separately cataloged biopsies (just not the organism pocket mouse).

I will also push back on this. An agent could be super useful for unnamed and non-experimental animals that have parts at MSB and other parts at UAM. 

But now as the project discussion proceeds, I wonder if a project might not be a better place for this....Let's see.

**Comment by Jegelewicz** [comment]
No to the projects as stuff for any given organism might come in with lots of other junk in any given accession (no way to associate "contributed by" easily and only get stuff for one organism.

**Comment by Jegelewicz** [comment]
The only issue with the agent model is filling up the agent table with a bunch of Mexican Wolves and eventually unnamed mice and trees. But I think we can work it out with a new agent type ("entity" or "organism") and use the UI to separate them when searching (a search page for all "person" agents and a search page for organisms which are effectively the same page, but you get on or the other depending upon which menu item you pick). The other rub will be, in order to keep this stuff normalized, we will need to get rid of the other id "organism ID" and any time you have a part of something that is also at Smithsonian, we will need an "organism" agent in Arctos to create that "organism ID" kind of linkage when the data goes out to aggregators (the beauty of that is that Smithsonian could put our agent url in their "organism id" and BOOM GBIF knows they are the same organism!). Which means we will need a new "collector" (that really needs renaming) role. Something like entity. And the agent url is what would get passed via DarwinCore as OrganismID.

In a way, this will make us an identifier for organisms which is crazy, but until there is an "organism registry" somewhere, I don't see how we can do any better.

**Comment by lin-fred** [comment]
Discussed during Agent Committee meeting. Although there are currently organisms in agents, with the many discussions about this topic in AWG and the Agent Committee, a solution will come about in which organisms will not be in the agent page. Agents/organizations should be separate from organisms/specimens, and updating the description will not create clarity, but instead confusion.
