### ISSUE TITLE
Agent for each Arctos Collection

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3814]
Set up an Organization Agent for each Arctos Collection.

Make this an automatic when bring in new collections -> update the in coming collection documentation

**Comment by Jegelewicz** [comment]
Bulkload file created. Do we need to add anything else?

[Collection_agents.zip](https://github.com/ArctosDB/arctos/files/6942522/Collection_agents.zip)

**Comment by ebraker** [comment]
This could be accompanied by an institutional agent. That way, Institutions with multiple  Arctos collections could have an institution-wide dashboard for a total view of institutional agent activity metrics across their collections.

**Comment by Jegelewicz** [comment]
Institutional agents are in the list!

**Comment by Jegelewicz** [comment]
All of the institution/collection agents have been added. Now I am working through them and adding urls, emails, addresses and relationships between collections and institutions, institutions and people, and institutions and the [Arctos Consortium](https://arctos.database.museum/agents.cfm?agent_id=21334341). Too bad that couldn't be agent No. 1....

**Comment by Jegelewicz** [comment]
Completed the following

DMNS
ACBC
KWP
ACUNHC
ALMNH

**Comment by Jegelewicz** [comment]
ASNHC
BELL (just the institution, collections not yet created.)
BYU
COA
CHAS

**Comment by Jegelewicz** [comment]
HWML
JSNM
KNWR
LU
MLZ

**Comment by dustymc** [comment]
done?
