### ISSUE TITLE
other_agent entries which need to move to Projects

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#3815]
Ref:[low-data agent issue](https://github.com/ArctosDB/arctos/issues/882), #3813 

Tackling this in chunks (see #882). Several of these are other_agents are better captured as Projects-- see all the Bolivian Expeditions. Or the "class" or "surveys". (i.e., discrete efforts of specific duration) These will never be found in the agent interface.

EG. https://arctos.database.museum/info/agentActivity.cfm?agent_id=21256035
(two MSB collections) but its Project link shows that it does have the cataloged records linked. 

A lot of these are MSB so not sure how you want to tackle. Discuss at intern meeting (could be a good task and aligns with Project focus this summer)? @campmlc ?

I also suggest we delete the other_agents with absolutely no records attached.

**Comment by dustymc** [comment]
>delete the other_agents with absolutely no records attached.

That bar is too high - see https://handbook.arctosdb.org/documentation/agent.html#verbatim-collectors

**Comment by Jegelewicz** [comment]
> suggest we delete the other_agents with absolutely no records attached.

> That bar is too high

Huh? If these are not being used for anything, why not delete them? I feel like many may have been added as part of some bulkloading operation, then never used. Can we get a list of unused agents along with the date those agents were added?

**Comment by campmlc** [comment]
Let's not delete any agents or change them to projects only without bringing in MSB folks. There is a lot of legacy info here that could be cleaned up, but we don't want to lose data in the process.
@jldunnum

**Comment by dustymc** [comment]
"Is used" does not and should not prevent deletion, and deletion does not remove any information for eg https://arctos.database.museum/agent/1010681.

That's actually a good example of the kinds of problems these create - the agent is much older than the usage, that link is almost certainly from some glitch in the APSU upload process, the low-quality data agent is almost certainly affecting the quality of other data objects merely by existing. We should be more aggressive in cleaning up things which don't follow the [guidelines](https://handbook.arctosdb.org/documentation/agent.html) (and adjusting the guidelines as necessary), and less hesitant to isolate questionable Agents to verbatim collector, from which they can't pollute other records.
