### ISSUE TITLE
Code Table Request (maybe) for new agent address

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#3816]
I noticed we just added wikidata as an address (type of one anyway) to Agents. Frankly not a useful authority for our archives, which uses Library of Congress name authority (https://id.loc.gov/). So my question is: should LC Name Authority be added as another address or just use url (which I originally interpreted as a personal website), or use AKA or do we need a new spot for authorities? (namely for historic folks since they wont have ORCids and not all are in wikidata).

Ex. https://arctos.database.museum/agents.cfm?agent_id=10000197
Right now Fred Test has his Library of Congress URI in ```url``` (but I also had it as ```AKA``` so will probably try somewhere else by the time anyone reads this!)

**Comment by Jegelewicz** [comment]
This goes along with the ORCiD functionality for searching agents. Will people come to Arctos and search for Fred as "no2009197237" if so, this needs to be an aka.

I would really appreciate a more streamlined method for adding completely linkable identifiers to agents. These are exactly like other ids for catalog records and allow us to really beef up the credentials for a given agent. Any agent with one of ORCiD, Wikidata Q number, Library of Congress uri, and probably a few others is way more valuable than Fred Test with a physical address or even an email. The identifiers listed above are starting to work like PIDs for people and the first two are already being accepted as such by GBIF. We should follow suit!

We should have a controlled vocabulary for accepted people identifiers that includes base urls as we do in other identifiers for records:

person_Id_type | person_id_definition | person_id_base_url 
-- | -- | -- 
ORCiD | ORCID provides a persistent digital identifier (an ORCID iD) that you own and control, and that distinguishes you from every other researcher. [ORCiD](https://orcid.org/) | https://orcid.org/
Wikidata | Wikidata acts as central storage for the structured data of its Wikimedia sister projects including Wikipedia, Wikivoyage, Wiktionary, Wikisource, and others. [Wikidata](https://www.wikidata.org/wiki/Wikidata:Main_Page) | https://www.wikidata.org/wiki/
Library of Congress |  | http://id.loc.gov/authorities/names/

**Comment by Jegelewicz** [comment]
Then we need some new thing in Agents

Agent Identifier

With type, determiner, and date determined (IMO we need to start adding determiner stuff for everything).

**Comment by mkoo** [comment]
I dont think it's a matter of searchability on Arctos but accessing authorities. The more typical use case probably would be that while viewing Fred Test's agent page a user can see that  Library of Congress Names authority recognizes him, and allows users to visit this authority perhaps for other non-Arctos info for Fred Test. (maybe they just want to check that his last name is real!)

**Comment by Jegelewicz** [comment]
> maybe they just want to check that his last name is real!

HAHAHAHA! yep, cause that's what I did....

**Comment by dustymc** [comment]
>accessing authorities. 

The URL is sufficient for people to do that.

If there's a serious use case for machines (and sufficient data to support such use) then a new type may be justified.

**Comment by mkoo** [comment]
oh we can go on and on about this and other agent authorities, but initial issue about how to add url to agent is addressed by CT additions
