### ISSUE TITLE
rebuild Other ID Bulkloader

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3818]
@dustymc reminder that we were to ask you about fixing the records loaded by sara: they are duplicates, but we can't delete them, get 400 Bad Request error.

Stuff is here - https://arctos.database.museum/tools/BulkloadOtherId.cfm

_Originally posted by @campmlc in https://github.com/ArctosDB/arctos/issues/3802#issuecomment-894386998_

**Comment by dustymc** [comment]
```
arctosprod@arctos>> create table temp_junk_cf_temp_oids as select * from cf_temp_oids where username='sara';
SELECT 776
Time: 13.155 ms
arctosprod@arctos>> delete from cf_temp_oids  where username='sara';
DELETE 776
Time: 4.364 ms
```
[temp_junk_cf_temp_oids.csv.zip](https://github.com/ArctosDB/arctos/files/6962233/temp_junk_cf_temp_oids.csv.zip)

**Comment by dustymc** [comment]
Suggest full rebuild, alter table to use UUID, rebuild specimen bulkloader-bits to use it.
