### ISSUE TITLE
Code Table Request - new collection code Osteo

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#3819]
UWZM would like to create a new collection code: Osteo (UWZM:Osteo). This collection is inclusive of all vertebrate groups.

see discussion: https://github.com/ArctosDB/new-collections/issues/379

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcollection_cde

**Collection type**
Osteo

**Definition**
Collections using this code will have code table terms applicable to vertebrate groups (Bird, Fish, Herp, Mamm) available.

**Comment by dustymc** [comment]
Are you aware that there is absolutely no relationship between guid_prefix and collection_cde? You don't need an Osteo collection code to create a UWZM:Osteo collection.

https://handbook.arctosdb.org/documentation/catalog.html#guid-prefix

If that's all clear and no existing collection types are suitable and this doesn't contain some reason to nudge https://github.com/ArctosDB/arctos/issues/3452 in some unexpected direction, then no objections from me.

**Comment by Jegelewicz** [comment]
@ebraker we should chat about this! Alsdo, it might help to read this - https://handbook.arctosdb.org/best_practices/GUID.html

**Comment by Jegelewicz** [comment]
Because your osteo collection encompasses all vertebrates - we may want to create a new collection code = vert that would provide access to code tables currently accessed by mamm, bird, herp and fish collections. The alternative would be to use Teach as your collection code, which provides access to ALL code table values (I feel like all that insect and plant stuff will just get in the way...)

**Comment by ebraker** [comment]
Ok that was helpful. It seems like 'vert' would be a good collection code to have handy since it may be relevant for other institutions and is a bit more narrow of a category than Teach.

**Comment by Jegelewicz** [comment]
Closing as a code table request issue for vert has been created.
