### ISSUE TITLE
Object Tracking constraint failure: slide box as freezer box

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3820]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
A student who had been working on slides and then was moved to freezer boxes was able to create a freezer box and scan objects into positions, but this freezer box was created in Arctos as a "slide box". I can't scan the box into position in a freezer rack because it isn't a freezer box. But I can't change it back into a freezer box from a slide box because I get the following error:
<html>
<body>

An error occurred while processing this page!Message: ERROR: FAIL: Changing position parameters of used containers is not allowed. Where: PL/pgSQL function updatecontainer(bigint,bigint,character varying,character varying,character varying,character varying,character varying,double precision,double precision,double precision,bigint,bigint,character varying,character varying,character varying) line 54 at RAISEDetail: Parameter types passed (15): CF_SQL_INTEGER, CF_SQL_INTEGER, CF_SQL_VARCHAR, CF_SQL_VARCHAR, CF_SQL_VARCHAR, CF_SQL_VARCHAR, CF_SQL_VARCHAR, CF_SQL_DOUBLE, CF_SQL_DOUBLE, CF_SQL_DOUBLE, CF_SQL_INTEGER, CF_SQL_INTEGER, CF_SQL_VARCHAR, CF_SQL_VARCHAR, CF_SQL_VARCHARCheck the Arctos Handbook for more information on errors.This message has been logged as 84C36874-D9B5-414C-A4894F9C20BB2178 Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue.
--

</body>
</html>

**To Reproduce**
1. Go to Find Container: enter DGR11445
2. Click on Edit Container
3. Try to change container type from slide box to freezer box

**Expected behavior**
I don't know if we need to add more restrictive triggers here, for example, to constrain the types of positions allowed in a slide box, or to make it impossible to add a cryovial to a slide box position. I'd prefer just to have the ability to change the type of the container back into a freezer box from a slide box.

**Screenshots**

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by Jegelewicz** [comment]
@campmlc the first thing you will have to do is empty the slide box. If there is nothing in it, then I think you just need to delete the barcode, re-create it and then turn it into a freezer box.

Let me know if I can help

**Comment by Jegelewicz** [comment]
You need to move all the barcodes out of it, get rid of the positions, change the container type and set it up with new positions, then scan everything back in.

**Comment by campmlc** [comment]
No, this is a freezer box and all objects have been scanned in correctly.
The box is labeled with the correct barcode. I shouldn't have to compromise
the samples by taking them out of the freezer and rescanning into a
different box, and I shouldn't have to try to add a new barcode onto a
frozen box at 196C. I have already paid a student to do this work, and the
barcode is associated with Excel file inventories which would also have to
be changed.  All I need is just to have the container type fixed in the
database to reflect the actual container.

**Comment by Jegelewicz** [comment]
@campmlc you don't need to physically do anything - let me see if I can just do it for you.

**Comment by campmlc** [comment]
We need a way to move positions and their children out of one container
into another, or alternately, move everything out if the positions in one
container and into the same position into another container. There is an
issue for this somewhere. We can move all children from one container to
another from Edit Container, but not if the children are in positions.

**Comment by Jegelewicz** [comment]
Done.

**Comment by campmlc** [comment]
Thanks! But maybe we should weigh in on this at an issues meeting. Should
we add more constraints, or can we leave as is and make the process for
fixing more transparent?

**Comment by Jegelewicz** [comment]
I put a link to this in the uber container issue.
