### ISSUE TITLE
Feature Request - change 'specimens' to 'catalog records'

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#3821]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

When viewing a publication record that has citations, such as this one

https://arctos.database.museum/publication/10010291

it states X-number of "Cited Specimens"

and should say X-number of "Cited Catalog Records"

This is a clear example of misuse of the term specimens in any case since many catalog records are lots that include many specimens so these citation counts are almost certainly wrong for any cat records that include lots. 

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.
Medium

**Comment by Jegelewicz** [comment]
I de-specimened the publication results. Should show up in next code release.

**Comment by Jegelewicz** [comment]
I am reopening this with a new title so that I can document de-specimen activity.

**Comment by Jegelewicz** [comment]
just de-specimend Bulkload page

**Comment by Jegelewicz** [comment]
de-specimened pre-bulkload documentation

**Comment by Jegelewicz** [comment]
de-specimened encumbrances
