### ISSUE TITLE
Bulkload Container Series Error

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#3823]
I get this error message when trying to bulkload a container series [:](https://arctos.database.museum/CreateContainersForBarcodes.cfm)

![image](https://user-images.githubusercontent.com/11336485/128574951-0d87f58a-1a78-462f-bed2-9ec6fffb8bb5.png)

There are no duplicate barcodes in the table, and my barcodes pass validation in the claim barcodes form, institution and container type are correct.

[CreateContainerTemplate_W126.zip](https://github.com/ArctosDB/arctos/files/6948110/CreateContainerTemplate_W126.zip)

**Comment by dustymc** [comment]
There's an empty row at the bottom of your CSV.

**Comment by ebraker** [comment]
Doh! Thanks!

**Comment by campmlc** [comment]
I thought we fixed all those forms so they wouldn't throw this error?
