### ISSUE TITLE
media search by URL doesn't work properly

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3824]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I uploaded a bunch of media individually and they are all OK except one which Arctos sees, but sees twice?

**To Reproduce**
1.Search media
2. Search for media using Description = Triassic New Mexico Page 7
3. See error

ERROR: query returned more than one row Hint: Make sure the query returns a single row, or use LIMIT 1. Where: PL/pgSQL function get_document_media_pageinfo(text,bigint) line 20 at SQL statement: 

**Expected behavior**
I expect to be able to edit the media to fix whatever the issue is

**Screenshots**
![image](https://user-images.githubusercontent.com/5725767/128580020-7718d4dd-2079-431c-9869-2a31040118df.png)

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**
This is a page in a multipage document, so it is making the document paging break when I reach that page. I tried to just re-load the media, but it will not load. It looks like it is loading, but acts like I am "loading media via url"

![image](https://user-images.githubusercontent.com/5725767/128580090-0ba59afc-a90a-4777-baae-adf7dfb6e88c.png)

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by dustymc** [comment]
Attach the file you're trying to upload if you can't find it in/near https://web.corral.tacc.utexas.edu/arctos-s3/jegelewicz/2021-08-06/

There are checks to prevent duplicate uploads, but they should be returning explicit errors.

**Comment by Jegelewicz** [comment]
I see it there - https://web.corral.tacc.utexas.edu/arctos-s3/jegelewicz/2021-08-06/Triassic_New_Mexico_Page_10.jpg and I tried to create media using that url, but get this:

> An error occurred while processing this page!
> Message: ERROR: duplicate key value violates unique constraint "iu_media_mediauri" Detail: Key (media_uri)=(https://web.corral.tacc.utexas.edu/arctos-s3/jegelewicz/2021-08-06/Triassic_New_Mexico_Page_10.jpg) already exists.
> Detail:
> Check the Arctos Handbook for more information on errors.
> 
> This message has been logged as DD59BB1F-2593-44B1-90083293164AC7D9 Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue. 

If I try to search media by that url, I get

> Nothing found

**Comment by dustymc** [comment]
Aha - thanks

https://arctos.database.museum/media/10638542

**Comment by Jegelewicz** [comment]
Got it - Thanks!

**Comment by dustymc** [comment]
This seems to be a matter of the cache catching up, the search now works for me.

There's something wrong with the data itself, that should be dealt with via https://github.com/ArctosDB/arctos/issues/1653
