### ISSUE TITLE
Code Table Request - New collection code

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3826]
**Goal**
Make use of controlled vocabularies for vertebrates

**Context**
Cataloging a skeletal collection that crosses all vertebrate taxa. See https://github.com/ArctosDB/arctos/issues/3819

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcollection_cde

**Value**
vert

**Definition**
Collections using this code will have code table terms applicable to all vertebrates (mamm, bird, fish, herp) available.

**Note**
Could we add this to all terms in parts/attributes/etc. that currently use mamm, bird, fish, herp, amph or rept?

**Collection type**
N/A

**Attribute data type**
N/A

**Attribute value**
N/A

**Attribute units**
N/A

**Other ID BaseURL**
N/A

**ID_References**
N/A

**Comment by ebraker** [comment]
Approved at 2022-01-20 meeting (useful for cataloging and cross-discipline transactions)

**Comment by mkoo** [comment]
is this completed? pls close if so

**Comment by Jegelewicz** [comment]
It is not.

**Comment by ccicero** [comment]
Done 17 Feb 2022.

**Comment by Jegelewicz** [comment]
@dustymc what would you need from me to add "Vert" collections to all parts and attributes that are already used by "Mamm", "Bird", "Herp" and "Fish"?

**Comment by dustymc** [comment]
A compelling reason? That sounds like a horrible experience to which I'd rather not subject anyone, especially a new collection. If they must, and understand what that's going to do for the user experience, I'd just need table names.
