### ISSUE TITLE
Hierarchical Editor in test

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3828]
I tried to load a file to the Siphonaptera hierarchy in test and received this error:

> An error occurred while processing this page!
> Message: Error invoking external process
> Detail: psql: error: could not connect to server: could not translate host name "gs-6.corral.tacc.utexas.edu:5432" to address: Name or service not known
> Check the Arctos Handbook for more information on errors.
> 
> This message has been logged as 39538371-FE9F-4EB5-8EA85D03393FBB9F Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue. 

along with this colorful stuff:

<html><body>
<div id="autoInjectPageDoc"><a href="https://handbook.arctosdb.org/how_to/How-to-Manage-Taxonomy-Hierarchically.html" class="handbook">Page Documentation</a></div>

<div id="x3d" class="-lucee-dump">

Catch
--
additional | Struct (ordered) | Struct (ordered)
Struct (ordered)
Detail | stringpsql:  error: could not connect to server: could not translate host name  "gs-6.corral.tacc.utexas.edu:5432" to address: Name or service not known | string | psql:  error: could not connect to server: could not translate host name  "gs-6.corral.tacc.utexas.edu:5432" to address: Name or service not known
string | psql:  error: could not connect to server: could not translate host name  "gs-6.corral.tacc.utexas.edu:5432" to address: Name or service not known
ErrorCode | string0 | string | 0
string | 0
Extended_Info | string | string |  
string |  
ExtendedInfo | string | string |  
string |  
Message | stringError invoking external process | string | Error invoking external process
string | Error invoking external process
StackTrace | stringlucee.runtime.exp.ApplicationException: Error invoking external process at lucee.runtime.tag.Execute.doEndTag(Execute.java:266) at component.utilities_cfc$cf.udfCall1(/component/utilities.cfc:868) at component.utilities_cfc$cf.udfCall(/component/utilities.cfc) at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106) at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344) at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:207) at lucee.runtime.ComponentImpl._call(ComponentImpl.java:685) at lucee.runtime.ComponentImpl._call(ComponentImpl.java:572) at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1925) at lucee.runtime.tag.Invoke.doComponent(Invoke.java:209) at lucee.runtime.tag.Invoke.doEndTag(Invoke.java:186) at tools.hierarchyeditor_cfm$cf.call(/tools/hierarchyEditor.cfm:1056) at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:1031) at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:923) at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:217) at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:44) at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2457) at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2447) at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2418) at lucee.runtime.engine.Request.exe(Request.java:44) at lucee.runtime.engine.CFMLEngineImpl._service(CFMLEngineImpl.java:1179) at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:1125) at lucee.loader.engine.CFMLEngineWrapper.serviceCFML(CFMLEngineWrapper.java:97) at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:51) at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590) at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.base/java.lang.Thread.run(Thread.java:834) | string | lucee.runtime.exp.ApplicationException: Error invoking external process at lucee.runtime.tag.Execute.doEndTag(Execute.java:266) at component.utilities_cfc$cf.udfCall1(/component/utilities.cfc:868) at component.utilities_cfc$cf.udfCall(/component/utilities.cfc) at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106) at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344) at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:207) at lucee.runtime.ComponentImpl._call(ComponentImpl.java:685) at lucee.runtime.ComponentImpl._call(ComponentImpl.java:572) at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1925) at lucee.runtime.tag.Invoke.doComponent(Invoke.java:209) at lucee.runtime.tag.Invoke.doEndTag(Invoke.java:186) at tools.hierarchyeditor_cfm$cf.call(/tools/hierarchyEditor.cfm:1056) at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:1031) at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:923) at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:217) at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:44) at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2457) at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2447) at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2418) at lucee.runtime.engine.Request.exe(Request.java:44) at lucee.runtime.engine.CFMLEngineImpl._service(CFMLEngineImpl.java:1179) at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:1125) at lucee.loader.engine.CFMLEngineWrapper.serviceCFML(CFMLEngineWrapper.java:97) at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:51) at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590) at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.base/java.lang.Thread.run(Thread.java:834)
string | lucee.runtime.exp.ApplicationException: Error invoking external process at lucee.runtime.tag.Execute.doEndTag(Execute.java:266) at component.utilities_cfc$cf.udfCall1(/component/utilities.cfc:868) at component.utilities_cfc$cf.udfCall(/component/utilities.cfc) at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106) at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344) at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:207) at lucee.runtime.ComponentImpl._call(ComponentImpl.java:685) at lucee.runtime.ComponentImpl._call(ComponentImpl.java:572) at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1925) at lucee.runtime.tag.Invoke.doComponent(Invoke.java:209) at lucee.runtime.tag.Invoke.doEndTag(Invoke.java:186) at tools.hierarchyeditor_cfm$cf.call(/tools/hierarchyEditor.cfm:1056) at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:1031) at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:923) at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:217) at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:44) at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2457) at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2447) at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2418) at lucee.runtime.engine.Request.exe(Request.java:44) at lucee.runtime.engine.CFMLEngineImpl._service(CFMLEngineImpl.java:1179) at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:1125) at lucee.loader.engine.CFMLEngineWrapper.serviceCFML(CFMLEngineWrapper.java:97) at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:51) at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590) at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.base/java.lang.Thread.run(Thread.java:834)
TagContext | Array1StructcodePrintHTMLstring866:  &lt;cffile action=&quot;append&quot;  file=&quot;#Application.webDirectory#/temp/#tempEFileName#&quot;  output=&quot;#x#&quot;&gt;<br> 867: <br> <b>868: &lt;cfexecute name=&quot;sh&quot;  arguments=&quot;#Application.webDirectory#/temp/#tempEFileName#&quot;  timeout=&quot;600&quot; variable=&quot;cfex&quot;  /&gt;</b><br> 869: <br> 870: &lt;!----<br> codePrintPlainstring866: <cffile action="append" file="#Application.webDirectory#/temp/#tempEFileName#" output="#x#"> 867:  868: <cfexecute name="sh" arguments="#Application.webDirectory#/temp/#tempEFileName#" timeout="600" variable="cfex" /> 869:  870: 
</body>
</html>

**Comment by dustymc** [comment]
Probably works now
