### ISSUE TITLE
Arctos Down - 

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3832]
Arctos is down, I emailed Chris, I know nothing else at this time.

Please complete to the best of your ability.

## Unplanned Outage
 - Date and time outage began:
 - Date and time outage is expected to end:
 - Reason for outage:
 - Expected behavior during and after the outage:

## Planned Outage
 - Date and time outage will begin:
 - Date and time outage is expected to end:
 - Reason for outage:
 - Expected behavior during and after the outage:

## Communication before/during outage
- [ ] Pin this issue
- [ ] Banner updated @jegelewicz 
- [ ] Email sent to AWG @ewommack 
- [ ] Email sent to Arctos Google Group @ewommack 
- [ ] Tweet @lin-fred 
- [ ] Update to arctosdb.org @mkoo 

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @jegelewicz
- [ ] Email sent to AWG @ewommac
- [ ] Email sent to Arctos Google Group @ewommac
- [ ] Tweet @lin-fred
- [ ] Update to arctosdb.org @mkoo
- [ ] Close this issue when above are complete

**Comment by Jegelewicz** [comment]
It's working fine for me...

**Comment by cjconroy** [comment]
It is back up for me too.

**Comment by dustymc** [comment]
yup

**Comment by AJLinn** [comment]
Sure, NOW it's working! ;-)
