### ISSUE TITLE
please break test

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3833]
http://test.arctos.database.museum

The webserver is new and different, should look and work as always.

Break it, please.

**Comment by bryansmclean** [comment]
Should collections see a number of specimens different than the actual number? I see ~1/3 of ours as searchable.

**Comment by dustymc** [comment]
That's not unexpected, the data are several weeks old and could have been manipulated to test something out. Functionality is all that needs tested.

**Comment by Jegelewicz** [comment]
I ran this SQL 
```
select distinct
 taxon_name.scientific_name
from
  identification_taxonomy,
  identification,
  cataloged_item,
  collection,
  taxon_name
where
  identification_taxonomy.identification_id=identification.identification_id and
  identification.collection_object_id=cataloged_item.collection_object_id and 
  cataloged_item.collection_id=collection.collection_id and
  identification_taxonomy.taxon_name_id=taxon_name.taxon_name_id and
  collection.guid_prefix='UNM:ES
  (select taxon_name_id from taxon_term where 
    taxon_term.taxon_name_id = taxon_name.taxon_name_id)
```

in prod and it worked fine, but in test:

> Unterminated string literal started at position 472 in SQL select distinct taxon_name.scientific_name from identification_taxonomy, identification, cataloged_item, collection, taxon_name where identification_taxonomy.identification_id=identification.identification_id and identification.collection_object_id=cataloged_item.collection_object_id and cataloged_item.collection_id=collection.collection_id and identification_taxonomy.taxon_name_id=taxon_name.taxon_name_id and collection.guid_prefix='UNM:ES (select taxon_name_id from taxon_term where taxon_term.taxon_name_id = taxon_name.taxon_name_id). Expected char

**Comment by Jegelewicz** [comment]
Doh! fat fingers!

**Comment by Jegelewicz** [comment]
This search
![image](https://user-images.githubusercontent.com/5725767/128957486-f5f00157-1ee9-4b7d-a2c3-f3a4270b7ed5.png)

results
An error occurred while processing this page!
Message: ERROR: canceling statement due to user request Where: PL/pgSQL function getgeographyterm(bigint,text) line 14 at FOR over EXECUTE statement
Detail:
Check the Arctos Handbook for more information on errors.

This message has been logged as D05F1A29-1DFF-4D94-ABE2AC35BDE9C20D Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue. 

Works in Prod
![image](https://user-images.githubusercontent.com/5725767/128957606-8d67e725-b861-429d-83f0-17fb4bcca4c8.png)

**Comment by dustymc** [comment]
Also not unexpected - that's a database timeout, and that DB is running on NAS with minimal memory.

That said, your search executes in 128 milliseconds with default criteria ...

 http://test.arctos.database.museum/SpecimenResults.cfm?guid_prefix=UTEPObs%3AHerp&cat_num=%25&debug=true 

<img width="306" alt="Screen Shot 2021-08-10 at 6 57 41 PM" src="https://user-images.githubusercontent.com/5720791/128957984-d339789d-8b7d-4c03-a789-ad8120c0caeb.png">

... so maybe check what you've got turned on.

**Comment by Jegelewicz** [comment]
yep, turned off a bunch of columns and it works

**Comment by Jegelewicz** [comment]
Set this to load a while ago and it's still just hanging out.
![image](https://user-images.githubusercontent.com/5725767/128958493-cdc44e05-fa22-4db6-8687-a281f5a2efe2.png)

**Comment by dustymc** [comment]
That doesn't really need tested either, but I think we have all the bits in place now so I turned the automation on.

**Comment by campmlc** [comment]
I'm unable to access test with my login? I get the following error
![Screenshot 2021-08-11 09 25 21](https://user-images.githubusercontent.com/14808196/129057806-de32a147-b3ca-48fa-9d32-a07534073945.png)

**Comment by dustymc** [comment]
TACC apparently has a switch dying, keep trying it should work eventually....

**Comment by Jegelewicz** [comment]
I had to try a couple of times yesterday, but it eventually worked.

**Comment by Jegelewicz** [comment]
> That doesn't really need tested either

What exactly DOES need testing?

**Comment by dustymc** [comment]
>What exactly DOES need testing?

That thing I haven't found....

I checked everything I can think of before I made this public, if I knew what was fragile I'd have done something about it. Hopefully I got that right and ya'll are wasting your time, but it doesn't always work out that way.

I'm pretty confident that scheduled tasks are OK.

Bulkloading is a database task, nothing at all will change for it.

Everything involving URLs that don't contain .cfm (/guid/, /name/, /project/, etc.) is being handled differently. That's the biggest functional change, but it's also (I think/hope) fairly straightforward to check and I haven't figured out how to break it.

The whole software stack is new, there could be all sorts of interesting problems in there, but I can't find them. (It SHOULD be a much more stable environment that uses more mainstream software, but that doesn't always pan out either.)

"Do the things you normally do" is about the best I can offer - that should at least uncover anything that might keep you from your core tasks when (and if) this becomes the production environment.

**Comment by Jegelewicz** [comment]
OK - well, my password suddenly doesn't work in test anymore?

**Comment by Jegelewicz** [comment]
nevermind....

**Comment by Jegelewicz** [comment]
Searched places for Locality nickname = NMMNH:Paleo:%

Got some results
![image](https://user-images.githubusercontent.com/5725767/129064836-d7ef0bec-6dd7-4167-8cb0-e65c203895ab.png)


but also a popup with this:

> {"MESSAGE":"ERROR; ERROR: canceling statement due to user request\n  Where: SQL statement \"select \n    array_to_json(array_agg(row_to_json(t)))              from (\n     SELECT\n      attribute_type as TY,\n      concat_ws(' ',attribute_value,attribute_units) as VU,\n      attribute_remark as RK,\n      determination_method as MD,\n      determined_date as DA,\n      getPreferredAgentName(determined_by_agent_id) as DT\n      from\n      locality_attributes\n      where\n      LOCALITY_ID=lid\n  ) t\"\nPL/pgSQL function getlocalityattributesasjson(bigint) line 5 at SQL statement; ; select\t\t\t\tdistinct\t\t\t\t\t\t\t\t\t\t\t\t\tgeog_auth_rec.geog_auth_rec_id,\t\t\t\t\tgeog_auth_rec.CONTINENT_OCEAN,\t\t\t\t\tgeog_auth_rec.COUNTRY,\t\t\t\t\tgeog_auth_rec.STATE_PROV,\t\t\t\t\tgeog_auth_rec.COUNTY,\t\t\t\t\tgeog_auth_rec.QUAD,\t\t\t\t\tgeog_auth_rec.FEATURE,\t\t\t\t\tgeog_auth_rec.drainage,\t\t\t\t\tgeog_auth_rec.ISLAND ,\t\t\t\t\tgeog_auth_rec.ISLAND_GROUP,\t\t\t\t\tgeog_auth_rec.SEA,\t\t\t\t\tgeog_auth_rec.SOURCE_AUTHORITY,\t\t\t\t\tgeog_auth_rec.geog_remark,\t\t\t\t\tgeog_auth_rec.wkt_media_id,\t\t\t\t\tlocality.locality_id,\t\t\t\t\tlocality.spec_locality,\t\t\t\t\tlocality.max_error_distance,\t\t\t\t\tlocality.max_error_units,\t\t\t\t\tlocality.dec_lat,\t\t\t\t\tlocality.dec_long,\t\t\t\t\tlocality.georeference_source,\t\t\t\t\tlocality.georeference_protocol,\t\t\t\t\tlocality.locality_name,\t\t\t\t\tlocality.DATUM,\t\t\t\t\tlocality.LOCALITY_REMARKS,\t\t\t\t\tlocality.MINIMUM_ELEVATION,\t\t\t\t\tlocality.MAXIMUM_ELEVATION,\t\t\t\t\tlocality.ORIG_ELEV_UNITS,\t\t\t\t\tlocality.MIN_DEPTH,\t\t\t\t\tlocality.MAX_DEPTH,\t\t\t\t\tlocality.DEPTH_UNITS,\t\t\t\t\tlocality.wkt_media_id as locality_wkt,\t\t\t\t\tgetLocalityAttributesAsJson(locality.locality_id)::varchar localityAtts,\t\t\t\t\tcollecting_event.collecting_event_id,\t\t\t\t\tcollecting_event.began_date,\t\t\t\t\tcollecting_event.ended_date,\t\t\t\t\tcollecting_event.verbatim_date,\t\t\t\t\tcollecting_event.verbatim_locality,\t\t\t\t\tcollecting_event.Verbatim_coordinates,\t\t\t\t\tcollecting_event.collecting_event_name,\t\t\t\t\tcollecting_event.collecting_event_id,\t\t\t\t\tgetCollEvtAttrAsJson(collecting_event.collecting_event_id)::varchar evtAttrs,\t\t\t\t\tgeog_auth_rec.higher_geog\t\t\t\t from  geog_auth_rec inner join locality on geog_auth_rec.geog_auth_rec_id = locality.geog_auth_rec_id\t\t\t\t\t inner join collecting_event on locality.locality_id=collecting_event.locality_id  where 1=1\t\t\t\t and \t\t\t\t\t\t\t\t\tupper(locality.locality_name)\t\t\t\t\tlike\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'%NMMNH:PALEO:%%'\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\torder by collecting_event_id asc\t\t\t\tlimit 10\t\t\t\toffset 0","STATUS":"fail"}

![image](https://user-images.githubusercontent.com/5725767/129064733-7e31ac95-a0fe-4df8-8368-49ea9d08b493.png)

**Comment by Jegelewicz** [comment]
HMMM - that may be because I hit enter, then "Find matches"?

When you hit enter, the form apparently starts searching, but I can't know that because the "Processing" bar is outside of the view I have at the moment.

**Comment by Jegelewicz** [comment]
http://test.arctos.database.museum/place.cfm?sch=locality
for the same search worked no problem

**Comment by dustymc** [comment]
That's just a DB timeout - it's not new, anyway. I'd probably call it a bug given the expense of the no-criteria query, but the ridiculous resources we have at production might let us get away with it anyway.

**Comment by Jegelewicz** [comment]
This isn't really breaking test, but I decided that working on some UI stuff for the taxonomy people would be a useful test of "doing stuff I normally do" and I ran into this.

I changed the link for "Arctos" to go to the term in the code table. But when I use the link created using the "link" button

https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxonomy_source#arctos

the entire page will not render because of the #arctos ending to the link. So I have left it as just the link to code table page, which works fine. Any idea why the # causes a problem?

![image](https://user-images.githubusercontent.com/5725767/129084097-5d9a6a25-245f-4e42-ba07-c9d785e4c28b.png)

**Comment by dustymc** [comment]
https://helpx.adobe.com/coldfusion/developing-applications/the-cfml-programming-language/elements-of-cfml/special-characters.html

**Comment by Jegelewicz** [comment]
sweet

**Comment by dustymc** [comment]
TEST is now running DB connections through pgpool. Continued efforts to break something are appreciated.

**Comment by Jegelewicz** [comment]
Not a break, but when I select the Edit Name + Related Data button on a taxon page there is a brief popup before I get the edit page. It is so quick I don't have time to read it. Here's the extra weird thing - it pops up with Hymenoptera but not with Mercenaria mercenaria.

**Comment by dustymc** [comment]
I'm not seeing that - there should be something in your browser console if it's somehow coming from Arctos.

**Comment by Jegelewicz** [comment]
This?

> Cookie “_ga” has been rejected for invalid domain.

**Comment by Jegelewicz** [comment]
Currently I can't get anything to happen in test - just the spinning browser.

**Comment by dustymc** [comment]
That was me tweaking some config settings, sorry, I think I'm done now.

**Comment by Jegelewicz** [comment]
I haven't made any changes to the taxon detail page, but suddenly it will not ope. I can search for a name, get results, but when I select a name it just spins.

**Comment by dustymc** [comment]
Good job!

It's back, config should be better.

**Comment by Jegelewicz** [comment]
Nope - still getting the 504 Gateway Time-out, now from test.arctos.database.museum/

**Comment by Jegelewicz** [comment]
Now getting this

> An error occurred while processing this page!
> Check the Arctos Handbook for more information on errors.
> 
> This message has been logged as fail Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue.

**Comment by dustymc** [comment]
Should be back (without pgpool) now.

**Comment by Jegelewicz** [comment]
Returning to a taxon detail page and got this

![image](https://user-images.githubusercontent.com/5725767/130290476-f610508a-6e11-45c1-b4ae-c3fa282f603d.png)

**Comment by Jegelewicz** [comment]
Click OK and seems to work...

**Comment by Jegelewicz** [comment]
I keep getting logged out of test - just me or is something going on?
