### ISSUE TITLE
Feature Request - Media results sorting

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3838]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
When I go to a "media gallery" from a taxon detail page the results appear to be in random order

![image](https://user-images.githubusercontent.com/5725767/129107961-611fdd67-3ca6-4be0-8700-eede2e4132fa.png)

**Describe what you're trying to accomplish** 
Provide a bit of order to the "gallery"

**Describe the solution you'd like**
It would be nice to have the media sorted by type.

**Describe alternatives you've considered**

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

It looks like I could easily break the gallery stuff - otherwise I'd add something in myself!

**Comment by dustymc** [comment]
That's impressively antique code, I don't blame you for being scared!

**Comment by Jegelewicz** [comment]
Good to know it isn't just me! let me know if I can help out.
