### ISSUE TITLE
error feedback

### ISSUE THREAD

**Issue by cefilipek** [ArctosDB/arctos#3839]
My bulkloader keeps coming back with an error. I copied my information line by line to a new file and ended up with a new error, so I'm not sure what the issue is. I will attach both versions here.

This is the initial error:

An error occurred while processing this page!
Message: Error invoking external process
Detail: psql:/usr/local/webroot/temp/excopy_cfilipek_20210811040842636_481.sql:49: ERROR: extra data after last expected column CONTEXT: COPY bulkloader_stage, line 18: "2,,cfilipek,9999.Paleo,JSNM:Paleo,0013273,,,,,Hilary S. Jurica,collector,,,Notogoneus osculus,unknow..."
Check the Arctos Handbook for more information on errors.
This message has been logged as 00C1CD6C-5DB9-4932-B9ACB2FA5E63012C Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue.

[Bulkloader Backup Excel File 0013272-0013317.zip](https://github.com/ArctosDB/arctos/files/6971640/Bulkloader.Backup.Excel.File.0013272-0013317.zip)

This is the second error: 

An error occurred while processing this page!Message: Error invoking external processDetail: psql:/usr/local/webroot/temp/excopy_cfilipek_20210811040843697_254.sql:1: ERROR: syntax error at or near "," LINE 1: ...ot_count_1,part_disposition_1,coll_object_remarks,,,,,,) FRO... ^Check the Arctos Handbook for more information on errors.
--
[A - Bulkloader Backup Excel File 0013272-0013317.zip](https://github.com/ArctosDB/arctos/files/6971637/A.-.Bulkloader.Backup.Excel.File.0013272-0013317.zip)

**Comment by dustymc** [comment]
The first file seems to be missing control characters - it looks like this in my preview-thingee:

<img width="806" alt="Screen Shot 2021-08-11 at 3 01 54 PM" src="https://user-images.githubusercontent.com/5720791/129109296-527d55a7-6a0f-4f43-8939-86ce0770d21b.png">

Nothing jumps out in a text editor, so I'd guess the encoding isn't understandable - https://handbook.arctosdb.org/documentation/encoding.html

The second maybe has too many controls - it gets sideways about here:

<img width="882" alt="Screen Shot 2021-08-11 at 3 04 02 PM" src="https://user-images.githubusercontent.com/5720791/129109535-68108d39-f03d-4842-a0d5-ecf2cfeadcab.png">

In any case, it's not valid CSV - whatever you saved the CSV from did something janky, perhaps even when you imported into it. If that's Excel then I can't be much help. I've had decent luck with Google Sheets for this sort of thing - it's relatively "smart" on the import, and (unlike Excel!) good at actually exporting UTF8 when you ask it to.

**Comment by ewommack** [comment]
If you're using excel here's what I do:
save it as a .csv in excel 
=> open the file in a text editor to double check it looks ok and save it again.
I have a Mac and use BBEdit.

I've never used Google sheets for this, but I'll try next time I'm arguing with Excel and it's habit of changing things on me.

**Comment by cefilipek** [comment]
@dustymc @ewommack 

Now that you mention the special characters, I realized that there might be some quotation marks in there. For some reason, the bulkloader really doesn't like the quotation mark and I forgot to double check for those when editing it today. I removed those and that fixed it! Thank you very much!
