### ISSUE TITLE
Code Table Request - new part attribute: container volume

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3841]
**Goal**
track the size of container in which a part is stored (from @kmkocot )

**Context**
An easy way for those not using object tracking to find all containers of a given volume or in a volume range.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecpart_attribute_type

**Value**
container volume

**Definition**
A numeric value for the volume of the container in which a part is stored.

**Collection type**
N/A

**Attribute data type**
number+units

**Attribute value**
N/A

**Attribute units**
https://arctos.database.museum/info/ctDocumentation.cfm?table=cttissue_volume_units

**Priority**
[  Please choose a priority-label to the right.  ]

**Comment by campmlc** [comment]
I support this.

**Comment by Jegelewicz** [comment]
My only real hesitation in adding this attribute is that the same thing can be done using object tracking and creating two ways of doing something always ends up causing issues at some point. Althouhg, this will just end up in part remark, so there will still be two ways to do this and using an attribute will make it easier to move stuff to object tracking when/if the collection decides to do that. @dustymc thoughts?

**Comment by dustymc** [comment]
Yea about that - it shouldn't be seen as remotely equivalent to anything in object tracking (and that should be part of the documentation), but it's probably/maybe/hopefully less-awful than just tossing the data into remarks or something. 

Any particular reason they're not just using machine-readable container IDs? I

**Comment by Jegelewicz** [comment]
> Any particular reason they're not just using machine-readable container IDs?

Printed barcodes is the issue - https://github.com/ArctosDB/data-migration/issues/370#issuecomment-654452986

**Comment by Jegelewicz** [comment]
Given that @dustymc is not absolutely opposed and that it is holding up cataloging, I am adding.
