### ISSUE TITLE
Code table spelling error - Sergeant

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3843]
Currently we have the prefix [Sargent](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctprefix#sargent) in the code table

I assume this is an incorrect spelling of Sergeant (and created the definition as if it were)

I don't know if this is in use by any agents, but can we change it to the correct spelling?

**Comment by dustymc** [comment]
This is the same situation as https://github.com/ArctosDB/arctos/issues/3844, I can move values into the code (which will make the cleanup forms significantly less usable to anyone without the ability to change the code) if the table is somehow problematic.

This is flagged as stopping work - explain?

**Comment by Jegelewicz** [comment]
> This is flagged as stopping work - explain?

Attempting to accomplish code table cleanup. WHY do we even have these two tables?

**Comment by Jegelewicz** [comment]
Closing as part of #3844
