### ISSUE TITLE
Remove unused code tables: ctprefix and ctsuffix

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3844]
We currently include the term [Sr.](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctprefix#sr_) in the agent prefix code table. This term ia already included in the suffix code table. I propose we remove it from prefixes. No idea if it has been applied to any agents as a prefix.

**Comment by dustymc** [comment]
>This term ia already included in the suffix code table.

One's señor, the other is senior (and maybe some other stuff, IDK).

There is no "correct" here but you can make the data services dumber by removing.

There is no prefix for agents, this is a leftover that turned out to be handy for other uses.

https://handbook.arctosdb.org/documentation/agent.html#creating--maintaining-agents

**Comment by Jegelewicz** [comment]
> There is no prefix for agents, this is a leftover that turned out to be handy for other uses.

Then this table is labeled incorrectly as related to agents. What is it being used for?

**Comment by Jegelewicz** [comment]
If [ctprefix](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctprefix) and [ctsuffix](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctsuffix) are not being used, I suggest we remove them. If they are being used, we need to better document where/how, because currently they are associated with agents, but there is no where to use them in agents.

**Comment by Jegelewicz** [comment]
From the documentation:

> Prefix and Suffix (formerly singular attributes of persons) are now embedded in agent names and should not be viewed as static.

**Comment by Jegelewicz** [comment]
@dustymc uses this for some stuff - it can be removed when he has "free" time.  For now, I am going to change the metadata on the code table list so that they don't appear with Agent stuff.

**Comment by dustymc** [comment]
I'm killing this - I can't see any reason to make maintaining tools more difficult.
