### ISSUE TITLE
CT and Volumetric Media Default Thumbnail

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#3846]
Some thumbnail options:
![ct_media](https://user-images.githubusercontent.com/11336485/129279698-cfc84011-3a02-4f5b-be3f-a465224a8490.png)

![ct_media2](https://user-images.githubusercontent.com/11336485/129279711-ea754d35-d1be-4b80-b646-492566a1a8a8.png)

![ct_media3](https://user-images.githubusercontent.com/11336485/129279720-4751da89-a6ff-4fed-8f15-8bc128722135.png)

![3D_volume](https://user-images.githubusercontent.com/11336485/129279734-10bbeeab-edce-46db-8413-604616c380cd.png)

**Comment by campmlc** [comment]
I vote for the last one.

**Comment by mkoo** [comment]
I'm a little worried about the cross-hairs... how about the last one but the arctos logo in the volumetric cube instead of the bear skull so our non-mammal, non-vertebrate folks dont feel left out?

Thanks for that fast turnaround @ebraker !

**Comment by ebraker** [comment]
they are CT crosshairs! but here you go...

![3D_volume2](https://user-images.githubusercontent.com/11336485/129283258-35def39e-9572-4b33-800a-5ee79f29d0d0.png)

**Comment by mkoo** [comment]
yes, I recognize the CT crosshairs but will any other casual user?!

I like this one a lot!

**Comment by ebraker** [comment]
loaded to Arctos-Shared > Images and Logos > Arctos_Logos

**Comment by dustymc** [comment]
@ebraker if there's a consensus (I like it!), could you shrink that to ~120PX / ~4K and send it my way?

**Comment by Jegelewicz** [comment]
PLEASE load it in the Documentation wiki repo so others can use it if needed - (like for presentations and documentation).

**Comment by ebraker** [comment]
@Jegelewicz done. @dustymc resized thumb: https://github.com/ArctosDB/documentation-wiki/blob/gh-pages/images/icons/arctos/3D_volume_thumb.png

**Comment by dustymc** [comment]
http://test.arctos.database.museum/media/10615061

**Comment by ewommack** [comment]
@ebraker I want some of these for Halloween now!
