### ISSUE TITLE
Error on adding other identifier

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3849]
Trying to add an entity ID to an existing record, but I get this error no matter what identifier I try to add, even just a collector number:
![Screenshot 2021-08-13 11 19 57](https://user-images.githubusercontent.com/14808196/129396515-095c57d8-f5ea-41f9-8830-d1cb6b046dd1.png)

priority: high

**Comment by campmlc** [comment]
Working with record https://arctos.database.museum/guid/MSB:Mamm:326433

**Comment by dustymc** [comment]
Should be working now but please confirm, I'm still tracking some things down, let me know if you find more and I'll prioritize
