### ISSUE TITLE
Need Help with Arctos Error

### ISSUE THREAD

**Issue by msbparasites** [ArctosDB/arctos#3850]
# Error Text
record failed checks: ERROR: column "collecting_event_id" is of type integer but expression is of type character varying Hint: You will need to rewrite or cast the expression. Position: 4762DETAIL: SQL: UPDATE bulkloader SET collection_object_id=collection_object_id ,loaded='waiting approval' ,enteredby='sara' ,accn='[MSB:Para]2021.008.Para' ,guid_prefix='MSB:Para' ,cat_num=null ,other_id_num_1=null ,other_id_num_type_1=null ,other_id_references_1=null ,other_id_num_2=null ,other_id_num_type_2=null ,other_id_references_2=null ,collector_agent_1='Eric Pulis' ,collector_role_1='collector' ,collector_agent_2=null ,collector_role_2='collector' ,taxon_name='Cercocotyla rhodesiensis' ,nature_of_id='fine features' ,id_made_by_agent='Vasyl V. Tkach' ,made_date=null ,identification_remarks=null ,identification_confidence='high' ,other_id_num_3=null ,other_id_num_type_3=null ,other_id_references_3=null ,other_id_num_4=null ,other_id_num_type_4=null ,other_id_references_4=null ,other_id_num_5=null ,other_id_num_type_5='collector number' ,collector_agent_3=null ,collector_role_3='collector' ,collector_agent_4=null ,collector_role_4='collector' ,collector_agent_5=null ,collector_role_5='collector' ,locality_id=null ,locality_name=null ,collecting_event_id=null ,collecting_event_name=null ,higher_geog='Africa, Uganda' ,spec_locality='Kibale National Park' ,locality_remarks=null ,verbatim_locality='Kibale National Park, Mainaro, Uganda' ,verbatim_date='2013-03-13' ,began_date='2013-03-13' ,ended_date='2013-03-13' ,coll_event_remarks=null ,maximum_elevation=null ,minimum_elevation=null ,orig_elev_units=null ,min_depth=null ,max_depth=null ,depth_units=null ,orig_lat_long_units='deg. min. sec.' ,dec_lat=null ,dec_long=null ,latdeg='0' ,dec_lat_min=null ,latmin='21' ,latsec='28.7' ,latdir='N' ,longdeg='30' ,dec_long_min=null ,longmin='22' ,longsec='51.4' ,longdir='E' ,datum='World Geodetic System 1984' ,georeference_source='GPS transcribed' ,max_error_distance=null ,max_error_units=null ,georeference_protocol='not recorded' ,utm_zone=null ,utm_ew=null ,utm_ns=null ,specimen_event_type='collection' ,specimen_event_remark=null ,event_assigned_by_agent='Vasyl V. Tkach' ,event_assigned_date='2021-08-12' ,verificationstatus='unverified' ,collecting_method=null ,collecting_source='wild caught' ,habitat=null ,associated_species=null ,locality_attribute_type_1=null ,locality_attribute_value_1=null ,locality_attribute_remark_1=null ,locality_attribute_determiner_1=null ,locality_attribute_detr_meth_1=null ,locality_attribute_detr_date_1=null ,locality_attribute_units_1=null ,locality_attribute_type_2=null ,locality_attribute_value_2=null ,locality_attribute_remark_2=null ,locality_attribute_determiner_2=null ,locality_attribute_detr_meth_2=null ,locality_attribute_detr_date_2=null ,locality_attribute_units_2=null ,locality_attribute_type_3=null ,locality_attribute_value_3=null ,locality_attribute_remark_3=null ,locality_attribute_determiner_3=null ,locality_attribute_detr_meth_3=null ,locality_attribute_detr_date_3=null ,locality_attribute_units_3=null ,locality_attribute_type_4=null ,locality_attribute_value_4=null ,locality_attribute_remark_4=null ,locality_attribute_determiner_4=null ,locality_attribute_detr_meth_4=null ,locality_attribute_detr_date_4=null ,locality_attribute_units_4=null ,locality_attribute_type_5=null ,locality_attribute_value_5=null ,locality_attribute_remark_5=null ,locality_attribute_determiner_5=null ,locality_attribute_detr_meth_5=null ,locality_attribute_detr_date_5=null ,locality_attribute_units_5=null ,locality_attribute_type_6=null ,locality_attribute_value_6=null ,locality_attribute_remark_6=null ,locality_attribute_determiner_6=null ,locality_attribute_detr_meth_6=null ,locality_attribute_detr_date_6=null ,locality_attribute_units_6=null ,part_name_1='whole organism' ,part_condition_1='good' ,part_barcode_1=null ,part_lot_count_1='1' ,part_disposition_1='being processed' ,part_remark_1='stain alum carmine' ,part_preservation_1='slide' ,part_name_2='whole organism' ,part_condition_2='good' ,part_barcode_2=null ,part_lot_count_2='1' ,part_disposition_2='being processed' ,part_remark_2='stain alum carmine' ,part_preservation_2='slide' ,part_name_3=null ,part_condition_3=null ,part_barcode_3=null ,part_lot_count_3=null ,part_disposition_3=null ,part_remark_3=null ,part_preservation_3=null ,part_name_4=null ,part_condition_4=null ,part_barcode_4=null ,part_lot_count_4=null ,part_disposition_4=null ,part_remark_4=null ,part_preservation_4=null ,part_name_5=null ,part_condition_5=null ,part_barcode_5=null ,part_lot_count_5=null ,part_disposition_5=null ,part_remark_5=null ,part_preservation_5=null ,part_name_6=null ,part_condition_6=null ,part_barcode_6=null ,part_lot_count_6=null ,part_disposition_6=null ,part_remark_6=null ,part_preservation_6=null ,part_name_7=null ,part_condition_7=null ,part_barcode_7=null ,part_lot_count_7=null ,part_disposition_7=null ,part_remark_7=null ,part_preservation_7=null ,part_name_8=null ,part_condition_8=null ,part_barcode_8=null ,part_lot_count_8=null ,part_disposition_8=null ,part_remark_8=null ,part_preservation_8=null ,part_name_9=null ,part_condition_9=null ,part_barcode_9=null ,part_lot_count_9=null ,part_disposition_9=null ,part_remark_9=null ,part_preservation_9=null ,part_name_10=null ,part_condition_10=null ,part_barcode_10=null ,part_lot_count_10=null ,part_disposition_10=null ,part_remark_10=null ,part_preservation_10=null ,part_name_11=null ,part_condition_11=null ,part_barcode_11=null ,part_lot_count_11=null ,part_disposition_11=null ,part_remark_11=null ,part_preservation_11=null ,part_name_12=null ,part_condition_12=null ,part_barcode_12=null ,part_lot_count_12=null ,part_disposition_12=null ,part_remark_12=null ,part_preservation_12=null ,attribute_1='age class' ,attribute_value_1='adult' ,attribute_remarks_1=null ,attribute_date_1='2013-03-13' ,attribute_det_meth_1=null ,attribute_determiner_1='Eric Pulis' ,attribute_2='experimental' ,attribute_value_2='no' ,attribute_remarks_2=null ,attribute_date_2='2013-03-13' ,attribute_det_meth_2=null ,attribute_determiner_2='Eric Pulis' ,attribute_3='location in host' ,attribute_value_3='small intestine' ,attribute_remarks_3=null ,attribute_date_3='2013-03-13' ,attribute_det_meth_3=null ,attribute_determiner_3='Eric Pulis' ,attribute_4='verbatim host ID' ,attribute_value_4='Halcyon malimbica' ,attribute_remarks_4=null ,attribute_date_4='2013-03-13' ,attribute_det_meth_4=null ,attribute_determiner_4='Eric Pulis' ,attribute_5=null ,attribute_value_5=null ,attribute_remarks_5=null ,attribute_date_5=null ,attribute_det_meth_5=null ,attribute_determiner_5=null ,attribute_6=null ,attribute_value_6=null ,attribute_remarks_6=null ,attribute_date_6=null ,attribute_det_meth_6=null ,attribute_determiner_6=null ,attribute_7=null ,attribute_value_7=null ,attribute_remarks_7=null ,attribute_date_7=null ,attribute_det_meth_7=null ,attribute_determiner_7=null ,attribute_8=null ,attribute_value_8=null ,attribute_remarks_8=null ,attribute_date_8=null ,attribute_det_meth_8=null ,attribute_determiner_8=null ,attribute_9=null ,attribute_value_9=null ,attribute_remarks_9=null ,attribute_date_9=null ,attribute_det_meth_9=null ,attribute_determiner_9=null ,attribute_10=null ,attribute_value_10=null ,attribute_remarks_10=null ,attribute_date_10=null ,attribute_det_meth_10=null ,attribute_determiner_10=null ,coll_object_remarks=null ,wkt_media_id=null ,flags=null ,uuid=null ,cataloged_item_type=null where collection_object_id = 97593876

# Where it happened
This happens in records I edit that are sitting in the bulkloader as well as when I save a new record

# Steps to get there
Saving edits to records in bulkload records as well as when I save a finished new record. I created records yesterday afternoon, saved them and then later that night I wanted to add more data to those records. Then I got the above error. So I created a new record, and when I saved it, that same error appeared. This happened in both Chrome and Firefox last night and now continues this morning on 3 different computers, both on and off campus.

# Problem
**Community response to describe the problem that caused the error**

# Solution
**Community response with directions for how to correct the problem**

**Comment by dustymc** [comment]
Should be fixed and patched, please try again.

**Comment by msbparasites** [comment]
Woohoo!!!  The edited record saved. Should work for new records, will work on that now. THANK YOU.
