### ISSUE TITLE
Bulkloader status error

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#3851]
Tried to bulkload a handful of records and got this error in the 'loaded' column:

function mark_flat_stale(name, name, bigint) does not exist

Any idea what I've got wrong?

**Comment by dustymc** [comment]
Bah sorry I'm still chasing some gremlins, should work now.

**Comment by acdoll** [comment]
looks like you fixed that one, but now there's this:
function parse_other_id(bigint, character varying, character varying, character varying) does not exist

**Comment by dustymc** [comment]
Neato...

Try again, or let me know what you're trying to do and I'll do it if you don't want to play guinea pig.

**Comment by acdoll** [comment]
Just loading 8 records - nothing too pressing, I don't mind being a guinea pig.

**Comment by ebraker** [comment]
Maybe related? I'm getting this error in media metadata loader for my second batch of images today (first loaded fine):

<html>
<body>


  | load fail::ERROR: function mark_flat_stale(name, name, bigint) does not exist Hint: No function matches the given name and argument types. You might need to add explicit type casts. Where: PL/pgSQL function trigger_fct_tr_mediarelations_au_flat() line 14 at PERFORM
-- | --



</body>
</html>

**Comment by dustymc** [comment]
@ebraker yes it's related - that one's in my done pile, but I gave it a kick anyway - happy now?

**Comment by ebraker** [comment]
Hmm...getting error but let me delete and reload
![image](https://user-images.githubusercontent.com/11336485/129418027-ca03c93c-bb4a-4a9f-8899-fa3b73e4ebcd.png)

**Comment by ebraker** [comment]
nah...it still isn't happy:
![image](https://user-images.githubusercontent.com/11336485/129418200-2cae80b1-22f4-493e-afeb-781916590985.png)

**Comment by acdoll** [comment]
You did solve my issue - they are successfully loaded now. Thanks!

**Comment by dustymc** [comment]
Data please - not sure what that is....

**Comment by ebraker** [comment]
[sceloporus_media_metadata.zip](https://github.com/ArctosDB/arctos/files/6985391/sceloporus_media_metadata.zip)

**Comment by dustymc** [comment]
Are these the same that's in the loader? I think that last error is from updating nothing by not check any boxes??

**Comment by ebraker** [comment]
Same data as in the loader. I had been checking and setting to autoload and it didn't like it when I clicked "change status," but it just went through.

**Comment by dustymc** [comment]
Stuff's happening, and I took the loader out of low range so stuff should happen slightly faster now. TGIF.

**Comment by ebraker** [comment]
It worked!

> TGIF

Indeed.
