### ISSUE TITLE
Part cleanup - appendicular parts

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3852]
> leg bone
long bone

I think it would be ok to replace these with bone + part modifier appendicular.

_Originally posted by @Nicole-Ridgwell-NMMNHS in https://github.com/ArctosDB/arctos/issues/3708#issuecomment-883726013_

**Comment by dustymc** [comment]
I'll go with this if there are no immediate objections:

```
 part_name | new_part_name |     new_part_remk_suffix      | new_part_attr_type | new_part_attr_val 
-----------+---------------+-------------------------------+--------------------+-------------------
 long bone | bone          | Original part name: long bone | part modifier      | appendicular
 leg bone  | bone          | Original part name: leg bone  | part modifier      | appendicular
```

**Comment by dustymc** [comment]
[temp_leglong.csv.zip](https://github.com/ArctosDB/arctos/files/7572870/temp_leglong.csv.zip)
