### ISSUE TITLE
Error on moving container

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3856]
Trying to move a part from a cryovial barcode
![Screenshot 2021-08-16 14 21 00](https://user-images.githubusercontent.com/14808196/129624976-b1963abe-0bcb-47af-901f-36b38ee9f7c7.png)
 into my DGRNONE container prior to encumbering a duplicate record for deletion. Get the following error
Priority: high, actively impeding a loan
@dustymc

**Comment by dustymc** [comment]
errors should be better now
