### ISSUE TITLE
Arctos Down - maybe

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3859]
Confirmed problem at TACC: "looks like possibly a switch died...we're checking on it now."

>There was a power event in the datacenter - we're trying to bring back the missing components now.

Please complete to the best of your ability.

## Unplanned Outage
 - Date and time outage began: 2021-08-17 about 2PM MDT
 - Date and time outage is expected to end:
 - Reason for outage: Unknown
 - Expected behavior during and after the outage:

## Planned Outage
 - Date and time outage will begin:
 - Date and time outage is expected to end:
 - Reason for outage:
 - Expected behavior during and after the outage:

## Communication before/during outage
- [x] Pin this issue
- [x] Banner updated @jegelewicz 
- [x] Email sent to AWG @ewommack 
- [x] Email sent to Arctos Google Group @ewommack 
- [x] Tweet @lin-fred 
- [x] Update to arctosdb.org @mkoo 

## Communication after outage
- [x] Unpin this issue
- [x] Banner updated @jegelewicz
- [x] Email sent to AWG @ewommack
- [x] Email sent to Arctos Google Group @ewommack
- [x] Tweet @lin-fred
- [x] Update to arctosdb.org @mkoo
- [x] Close this issue when above are complete

**Comment by Jegelewicz** [comment]
No banner to update...

**Comment by mkoo** [comment]
posted on website and twitter since I had it open... still figuring out if I can embed just a status thread on the status page.....

**Comment by mkoo** [comment]
draft page on website which shows tweets with #ArctosStatus 
https://arctosdb.org/tester2/
This is streamlining the checkboxes!
let me know what you think.

**Comment by Jegelewicz** [comment]
Nice! We just need to make sure that someone always has access to the Twitter account.

**Comment by dustymc** [comment]
Arctos is back up.

**Comment by Jegelewicz** [comment]
OK to email this?

> The power event at TACC has been resolved and Arctos is back up.
> 
> Thanks for your patience!

**Comment by mkoo** [comment]
yes!
thanks

**Comment by Jegelewicz** [comment]
@mkoo can you post to Twitter - Lindsey does not have access at the moment.

**Comment by lin-fred** [comment]
Thanks for posting the tweets @mkoo !
