### ISSUE TITLE
Bulkload Collector Tool

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#3860]
I've recently used the Bulkload Collector Tool to add preparator names to collection records (eg. [[https://arctos.database.museum/saved/mamm2021%2D07%2D23](https://arctos.database.museum/saved/mamm2021%2D07%2D23)]; upload file attached below). When I've done so, not only does the 'preparator' not load into the record, but the existing 'collector' names are deleted from the record. Previously, I had used a default value of '9' for coll_order, but setting that to '9999' as suggested in the Definitions and Documentation table did not help get them in. 
This needs fixing before any more data is lost.

[Mamm_PrepData_Agents_2021-07-23.csv](https://github.com/ArctosDB/arctos/files/7009424/Mamm_PrepData_Agents_2021-07-23.csv)

**Comment by dustymc** [comment]
I've disabled that from loading until I can figure out what's going on.

Here are collectors from test - if you've changed something recently they might not be correct, let me know if I need to dig deeper.

[temp_dmns_colls.csv.zip](https://github.com/ArctosDB/arctos/files/7009515/temp_dmns_colls.csv.zip)

**Comment by acdoll** [comment]
Thanks. And thanks for the names from test; those are all correct.

**Comment by dustymc** [comment]
Problem found and fixed for next release.
