### ISSUE TITLE
Bulkload Media Metadata License Issue

### ISSUE THREAD

**Issue by cefilipek** [ArctosDB/arctos#3862]
When I bulkload my media metadata, the license doesn't upload. Although I include it in the bulkloader, each image says None under license. I copied the license name directly from the code table, so I am unsure if I am doing something wrong, or if this is a bug in the uploader.

[Bulkload Images 0012609-0012628.zip](https://github.com/ArctosDB/arctos/files/7010396/Bulkload.Images.0012609-0012628.zip)

**Comment by dustymc** [comment]
Thanks, fix in next release, and I see you've added the license. I'd have been happy to fix that for you!

**Comment by cefilipek** [comment]
Thank you!


Colleen Filipek (She/Her)

Museum Collections Manager

Jurica-Suchy Nature Museum

Benedictine University


5700 College Rd. l Lisle, IL 60532

Office: (630) 829-1142

Office Fax: (630) 829-6547  l  ben.edu/museum<http://www.ben.edu/museum>

Follow us: facebook.com/JSNMatBU<http://www.facebook.com/JSNMatBU>


Sent from Mobile Device

________________________________
