### ISSUE TITLE
Curatorial Search/Data Bulk Change query

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#3863]
**Describe what you are trying to accomplish**
When the UAM:EH collection migrated into Arctos years ago, we had to arbitrarily name a start date for all our collecting events due to the fact that we had never used date ranges before, only calendar. At that time we made a very broad decision to cover all possible dates of our collections by using a date range of 900 (AD) as the start date and whatever the date of deposit was as the end date, if we didn't know better. 

As we've worked in our Arctos records for a number of years, we've been refining these entries, but it's taking a long time to review them individually, especially when we have up to 3 collecting events (date of creation, date of use, date of collection) and related dates associated with each catalog record. Is there a way to find all of those 900 AD start dates in all of our collecting events and move that start date up to 1700 as a more accurate reflection of what we seem to have in our holdings? If not it's fine and I'll continue to update them one event at a time.

**Comment by dustymc** [comment]
Looks like only UAM:EH is using events with a began_date of 0900, so that makes things easy. Do you need any data to confirm/refine/whatever, or can I just update all 0900 to 1700?

**Comment by AJLinn** [comment]
Nope, feel free to do a mass change. Thank you sooooo much! This will greatly improve the accuracy of our data.

**Comment by dustymc** [comment]
@AJLinn there are two with a pre-1700 ended date. Do I need to look for anything similar, or can I continue with these excluded?

```
arctosprod@arctos>> select * from collecting_event where began_date='0900' and ended_date<'1700';
 collecting_event_id | locality_id | verbatim_date | verbatim_locality | coll_event_remarks | began_date | ended_date | verbatim_coordinates | collecting_event_name | lat_deg | dec_lat_min | lat_min | lat_sec | lat_dir | long_deg | dec_long_min | long_min | long_sec | long_dir | dec_lat | dec_long | datum | utm_zone | utm_ew | utm_ns | orig_lat_long_units | caclulated_dlat | calculated_dlong | admin_flag |    last_dup_check_date     
---------------------+-------------+---------------+-------------------+--------------------+------------+------------+----------------------+-----------------------+---------+-------------+---------+---------+---------+----------+--------------+----------+----------+----------+---------+----------+-------+----------+--------+--------+---------------------+-----------------+------------------+------------+----------------------------
            10841226 |    10588568 | pre-1000      | Peru              |                    | 0900       | 1000       |                      |                       |         |             |         |         |         |          |              |          |          |          |         |          |       |          |        |        |                     |                 |                  |            | 2021-06-08 01:40:00.840762
            10845882 |    10588568 | not recorded  | Peru              |                    | 0900       | 1000       |                      |                       |         |             |         |         |         |          |              |          |          |          |         |          |       |          |        |        |                     |                 |                  |            | 2021-07-07 11:20:00.628581
(2 rows)
```

**Comment by AJLinn** [comment]
Boy, I hope those are the only exclusions. I'm sure it's based on the dates of those particular cultures based on my undoubtedly "extensive" research (likely from Wikipedia!). I think you're good to move forward.

**Comment by dustymc** [comment]
Wait- are you suggesting there's knowledge beyond wikipedia?!

Done, might take a while for everything to catch up.

**Comment by AJLinn** [comment]
Thank you! I'll close for now. I appreciate your prompt response on this.
