### ISSUE TITLE
Date Search Issue

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#3864]
If you use the drop downs for a date search from the main page and the day is numerically less than 10:
![image](https://user-images.githubusercontent.com/12507297/130147313-7da1f14f-339d-43bc-8b96-8e7a289777ad.png)
you will get 0 results.
Looking at the search terms widget, it appears that the day dropdown needs zeros before the single digit:
![image](https://user-images.githubusercontent.com/12507297/130147592-38a917c3-ff2a-4a52-b2d7-4971437e4f0d.png)

adding the zero gives me the results I expected:
![image](https://user-images.githubusercontent.com/12507297/130147658-a8abe0ef-8e6e-4497-9e04-366ed9728036.png)

Can we get that patched? Thanks

**Comment by dustymc** [comment]
Question: Can we get rid of that; is there some legitimate use/need, or does it just confuse people? Note that it's not interchangeable with the ISO8601 options: https://handbook.arctosdb.org/documentation/collecting-event.html#specimen-search

**Comment by acdoll** [comment]
I generally use the ISO8601 Date/Time field; not sure why I chose to use the dropdowns this time.
I thought we might want it for searching for specimens within a particular date range regardless of year (e.g. during bird migrations; 15 Mar - 15 Jun); but it doesn't work that way, does it? It seems to kind of work: 
 
![image](https://user-images.githubusercontent.com/12507297/130152987-1eca9a74-06d8-4c4a-b6fd-b217461406ac.png)
However, if the day of the ended date is lower than the day of the began date you get 0 results:
![image](https://user-images.githubusercontent.com/12507297/130153093-166eef8d-ed8f-4b72-8b84-d350b7204165.png)

I believe this kind of search is why we added the Month search option:
![image](https://user-images.githubusercontent.com/12507297/130153174-86ee2503-2a8a-48c5-a838-f8dde9e8f2e4.png)
But I could imagine a researcher wanting to use specific start and end days.

**Comment by dustymc** [comment]
>doesn't work that way, does it? 

Nope, it's a bunch of BETWEENs that don't necessarily have anything to do with each other. I'm not sure if someone actually had a use for this or if it's just a strange leftover from when we had DATE everywhere. If there's no use, I vote we either drop the whole mess, or change the back end to do what you said.

**Comment by Jegelewicz** [comment]
If you can enter 2019 or 2019-06 in the ISO, then I think losing it is fine.

**Comment by acdoll** [comment]
> If you can enter 2019 or 2019-06 in the ISO, then I think losing it is fine.

For these, you would have to enter a began_date 2019-01-01 and ended_date 2019-12-31; or 2019-06-01 to 2019-06-30.
You can use the ISO field in conjunction with the Month selector to find, for example, spring collections between 2000 and 2010: 
![image](https://user-images.githubusercontent.com/12507297/130480502-d527311e-b049-4228-9350-f280a4c0fe05.png)

How much work would it take to reconfigure the back end? Searching for date ranges based on Julian dates would probably be the place to start, but leap years would have to be factored in. I have used this to find things similar to the 'on this day...' option in "Try something random" - which is great for pulling specimens for events. But if the only other use is for seeing what was collected on one's birthday (e.g., https://arctos.database.museum/SpecimenResults.cfm?begmon=07&begday=19&endmon=07&endday=19), then it may not be worth the effort to recode.

**Comment by dustymc** [comment]
>How much work 

Given clear and realistic specifications, probably not too bad (and probably worth some pain if it makes the search better).

Note that these queries are running against collecting_event.began_date and ended_date, which are not standard DATE datatypes and can't reliably be converted to them. So for example while PG has support for [Julian dates](https://www.postgresql.org/docs/10/datetime-julian-dates.html), using that would involve some way of first filtering out  "dates" like "2004" (and then documenting, since that query might return different results than some other which uses apparently-identical values of a different type).

**Comment by dustymc** [comment]
Unless someone provides better direction, let's just remove the component-bits.

**Comment by dustymc** [comment]
They do provide unique functionality (see https://handbook.arctosdb.org/documentation/collecting-event.html#specimen-search), but they also seem to add a lot of confusion. I'm currently leaning towards getting rid of them, which would mean filtering a download or similar to get at "any spring." If we keep them - and my leaning shouldn't much influence this decision! - then they should at least be separated from the ISO dates, and maybe the documentation should somehow be spruced up.

**Comment by dustymc** [comment]
Nuking as part of https://github.com/ArctosDB/arctos/issues/2745
