### ISSUE TITLE
Test down

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3866]
When I Go to test, I get his

> An error occurred while processing this page!
> Check the Arctos Handbook for more information on errors.
> 
> This message has been logged as fail Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue. 

![image](https://user-images.githubusercontent.com/5725767/130246816-826884a6-94c5-4b4a-9bee-752f7c9ecd4a.png)

**Comment by dustymc** [comment]
It's back you already knew that, pgpool settings should be a bit better, thx.
