### ISSUE TITLE
Error Moving part to DGRNONE 

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3867]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I have a part whose barcode was entered as a duplicate for parts of two different catalog records. I need to remove one of the parts from the barcode, which means I need to move it to my wastebasket container, DGRNONE - because I have no idea what if any barcode is the correct barcode for this part. Trying to move it yields the following error:
An error occurred while processing this page!
Message: ERROR: FAIL: unknown and legacy container may not be moved: ; DGRNONE Where: PL/pgSQL function moveparttocontainer(bigint,text,bigint,text,text) line 47 at RAISE
Detail:
Check the Arctos Handbook for more information on errors.
This message has been logged as 792A7596-27F3-4176-8FF96EA227401A7A Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue.

**To Reproduce**
1. Go to https://arctos.database.museum/guid/MSB:Herp:98218
2. Click on Edit parts 
3. Scroll down to part with barcode A4D9S
4. Attempt to Add to Barcode "DGRNONE"
5.See error.

**Expected behavior**
For the part to move to barcode DGRNONE

**Screenshots**

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
High. Impeding loan resolution.

**Comment by dustymc** [comment]
<img width="240" alt="Screen Shot 2021-08-23 at 8 11 28 AM" src="https://user-images.githubusercontent.com/5720791/130471898-2b1cc21a-6734-4d83-9ca1-3ec343639044.png">

**Comment by campmlc** [comment]
Following up on this.
DGRNONE is the same as UAM's parentless void. I need to be able to move containers into this.  If not an unknown or legacy container, what should it be?

**Comment by dustymc** [comment]
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcontainer_type - not those, not herbarium% (which have restrictions) - https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcontainer_type#bucket is pretty nice....

**Comment by campmlc** [comment]
Can't we just create a "wastebasket" or "virtual" container? I don't like
create fake buckets which aren't really buckets.

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/new?assignees=&labels=Function-CodeTables&template=authority-request.md&title=Code+Table+Request+-+

**Comment by Jegelewicz** [comment]
@campmlc I change the DGRNONE container to type = virtual. Can we close this?

**Comment by campmlc** [comment]
Sure - that works, thanks!
