### ISSUE TITLE
Arctos Error on Locality editing

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#3870]
# Error Text
Message: ERROR: function getpreferredagentname(bigint) does not exist Hint: No function matches the given name and argument types. You might need to add explicit type casts. Where: PL/pgSQL function getlastcoordsedit(bigint) line 30 at SQL statement
Detail:

# Where it happened
Happened upon save after editing locality 10580413. All I changed were the lat longs. Subsequently, I cannot even get back to the edit locality page without getting this error to improve the record, e.g. change agent names and such. However, my changes are correctly shown on the specimen page now. 

# Steps to get there
Was editing this locality as followed from the specimen page for mvz mamm 230441 , but now simply cannot get to the page from any direction. 

# Problem
I can't do anything to fix this locality. 

# Solution
you tell me.

**Comment by dustymc** [comment]
thx/patched
