### ISSUE TITLE
Problem with individualCount in UWBM Ornithology Collection

### ISSUE THREAD

**Issue by albenson-usgs** [ArctosDB/arctos#3871]
Per [a ticket](https://github.com/gbif/portal-feedback/issues/3547) that came in to the GBIF portal feedback repo, something seems wrong with `individualCount` in the UWBM Ornithology Collection. I understand from David Bloom that version 10.12 is empty because of issues with the IP change. However, [version 10.11](http://ipt.vertnet.org:8080/ipt/resource?r=uwbm_birds&v=10.11) of this dataset has `individualCount` = 0 for all rows. Is this issue fixed once the database connection is corrected in the IPT?

**Comment by Jegelewicz** [comment]
UWBM Birds are not in Arctos. Only their mammals and herps are.

![image](https://user-images.githubusercontent.com/5725767/130492746-57cededb-a500-41ce-95ca-183a1544a166.png)

**Comment by albenson-usgs** [comment]
Ah! Good to know. I'll check back in with David Bloom. Thanks Teresa!
