### ISSUE TITLE
Should Identification Activity appear on public Agent page?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3872]
Currently Identification activity is only displayed on the "internal" Agent page which means that only Arctos operators with appropriate access can see it. Does making this public make sense?

![image](https://user-images.githubusercontent.com/5725767/130511978-67fde4cb-9350-4abf-ad18-54bc023d5827.png)

**Comment by ewommack** [comment]
I think so. Isn't that the same data that appears in some of the other agent aggregators that are appearing in the web?

**Comment by dustymc** [comment]
I don't see any problems with this.

**Comment by dustymc** [comment]
@Jegelewicz I assume you're doing stuff.

1. It's broken
2. From the error, I suspect the query you're using is both dangerous and expensive - public views of catalog records should go through filtered_flat, not cataloged_item.

**Comment by dustymc** [comment]
sanitized

**Comment by Jegelewicz** [comment]
Thanks man, I got distracted by Steering Committee Meeting!

**Comment by dustymc** [comment]
@Jegelewicz is this done or hanging or ???

**Comment by Jegelewicz** [comment]
I think it is all working changed milestone. Let's see if anyone even notices any of it...
