### ISSUE TITLE
Erron on Data Entry

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#3874]
I haven't really used the single record data entry before, and got this error on the second record.

# Error Text
record failed checks: ERROR: new row for relation "bulkloader" violates check constraint "ck_part_remark_1_noprt"DETAIL: SQL: UPDATE bulkloader SET collection_object_id=collection_object_id ,loaded='waiting approval' ,enteredby='NICOLERIDGWELL' ,accn='[NMMNH:Paleo]9999' ,guid_prefix='NMMNH:Paleo' ,cat_num='81419' ,other_id_num_1='NMMNH P-81419' ,other_id_num_type_1='other identifier' ,other_id_references_1=null ,other_id_num_2=null ,other_id_num_type_2=null ,other_id_references_2=null ,collector_agent_1='Kate E. Zeigler' ,collector_role_1='collector' ,collector_agent_2=null ,collector_role_2='collector' ,taxon_name='Typothorax' ,nature_of_id='unknown' ,id_made_by_agent='unknown' ,made_date=null ,identification_remarks=null ,identification_confidence=null ,other_id_num_3=null ,other_id_num_type_3=null ,other_id_references_3=null ,other_id_num_4=null ,other_id_num_type_4=null ,other_id_references_4=null ,other_id_num_5=null ,other_id_num_type_5=null ,collector_agent_3=null ,collector_role_3='collector' ,collector_agent_4=null ,collector_role_4='collector' ,collector_agent_5=null ,collector_role_5='collector' ,locality_id='11063550' ,locality_name='NMMNH:Paleo:L-3845_public' ,collecting_event_id=null ,collecting_event_name=null ,higher_geog='North America, United States, New Mexico, Rio Arriba County' ,spec_locality='Specific locality encumbered' ,locality_remarks=null ,verbatim_locality='3845' ,verbatim_date='6/2000' ,began_date='2000-06' ,ended_date='2000-06' ,coll_event_remarks=null ,maximum_elevation=null ,minimum_elevation=null ,orig_elev_units=null ,min_depth=null ,max_depth=null ,depth_units=null ,orig_lat_long_units='decimal degrees' ,dec_lat='36.509576' ,dec_long='-106.693075' ,latdeg=null ,dec_lat_min=null ,latmin=null ,latsec=null ,latdir=null ,longdeg=null ,dec_long_min=null ,longmin=null ,longsec=null ,longdir=null ,datum='World Geodetic System 1984' ,georeference_source='New Mexico, Rio Arriba County entered into Geolocate' ,max_error_distance='124747' ,max_error_units='m' ,georeference_protocol='GeoLocate' ,utm_zone=null ,utm_ew=null ,utm_ns=null ,specimen_event_type='collection' ,specimen_event_remark=null ,event_assigned_by_agent='Kate E. Zeigler' ,event_assigned_date='2000-06' ,verificationstatus='unverified' ,collecting_method=null ,collecting_source=null ,habitat=null ,associated_species=null ,locality_attribute_type_1='lithostratigraphic group' ,locality_attribute_value_1='Chinle Group' ,locality_attribute_remark_1=null ,locality_attribute_determiner_1=null ,locality_attribute_detr_meth_1=null ,locality_attribute_detr_date_1=null ,locality_attribute_units_1=null ,locality_attribute_type_2='lithostratigraphic member' ,locality_attribute_value_2='Painted Desert Member' ,locality_attribute_remark_2='bone bed conglomerate (light blue to yellowish) above red mudstones' ,locality_attribute_determiner_2=null ,locality_attribute_detr_meth_2=null ,locality_attribute_detr_date_2=null ,locality_attribute_units_2=null ,locality_attribute_type_3='site identifier' ,locality_attribute_value_3='NMMNH:Paleo:L-3845' ,locality_attribute_remark_3='Original type: Site Identifier' ,locality_attribute_determiner_3='New Mexico Museum of Natural History and Science' ,locality_attribute_detr_meth_3=null ,locality_attribute_detr_date_3=null ,locality_attribute_units_3=null ,locality_attribute_type_4='biochron' ,locality_attribute_value_4='Revueltian' ,locality_attribute_remark_4=null ,locality_attribute_determiner_4=null ,locality_attribute_detr_meth_4=null ,locality_attribute_detr_date_4=null ,locality_attribute_units_4=null ,locality_attribute_type_5='Stage/Age' ,locality_attribute_value_5='Norian' ,locality_attribute_remark_5=null ,locality_attribute_determiner_5=null ,locality_attribute_detr_meth_5=null ,locality_attribute_detr_date_5=null ,locality_attribute_units_5=null ,locality_attribute_type_6=null ,locality_attribute_value_6=null ,locality_attribute_remark_6=null ,locality_attribute_determiner_6=null ,locality_attribute_detr_meth_6=null ,locality_attribute_detr_date_6=null ,locality_attribute_units_6=null ,part_name_1='skeleton, appendicular' ,part_condition_1='unchecked' ,part_barcode_1='NMMNHG000168' ,part_lot_count_1='1' ,part_disposition_1='on loan' ,part_remark_1='borrower: R. Pitore, date out 02/06/2020 "11 pieces, limbs, verts, etc."' ,part_preservation_1='fossil' ,part_name_2='vertebra' ,part_condition_2='unchecked' ,part_barcode_2='NMMNHG000168' ,part_lot_count_2='1' ,part_disposition_2='on loan' ,part_remark_2='borrower: R. Pitore, date out 02/06/2020 "11 pieces, limbs, verts, etc."' ,part_preservation_2='fossil' ,part_name_3=null ,part_condition_3=null ,part_barcode_3=null ,part_lot_count_3=null ,part_disposition_3=null ,part_remark_3=null ,part_preservation_3=null ,part_name_4=null ,part_condition_4=null ,part_barcode_4=null ,part_lot_count_4=null ,part_disposition_4=null ,part_remark_4=null ,part_preservation_4=null ,part_name_5=null ,part_condition_5=null ,part_barcode_5=null ,part_lot_count_5=null ,part_disposition_5=null ,part_remark_5=null ,part_preservation_5=null ,part_name_6=null ,part_condition_6=null ,part_barcode_6=null ,part_lot_count_6=null ,part_disposition_6=null ,part_remark_6=null ,part_preservation_6=null ,part_name_7=null ,part_condition_7=null ,part_barcode_7=null ,part_lot_count_7=null ,part_disposition_7=null ,part_remark_7=null ,part_preservation_7=null ,part_name_8=null ,part_condition_8=null ,part_barcode_8=null ,part_lot_count_8=null ,part_disposition_8=null ,part_remark_8=null ,part_preservation_8=null ,part_name_9=null ,part_condition_9=null ,part_barcode_9=null ,part_lot_count_9=null ,part_disposition_9=null ,part_remark_9=null ,part_preservation_9=null ,part_name_10=null ,part_condition_10=null ,part_barcode_10=null ,part_lot_count_10=null ,part_disposition_10=null ,part_remark_10=null ,part_preservation_10=null ,part_name_11=null ,part_condition_11=null ,part_barcode_11=null ,part_lot_count_11=null ,part_disposition_11=null ,part_remark_11=null ,part_preservation_11=null ,part_name_12=null ,part_condition_12=null ,part_barcode_12=null ,part_lot_count_12=null ,part_disposition_12=null ,part_remark_12=null ,part_preservation_12=null ,attribute_1=null ,attribute_value_1=null ,attribute_remarks_1=null ,attribute_date_1=null ,attribute_det_meth_1=null ,attribute_determiner_1=null ,attribute_2=null ,attribute_value_2=null ,attribute_remarks_2=null ,attribute_date_2=null ,attribute_det_meth_2=null ,attribute_determiner_2=null ,attribute_3=null ,attribute_value_3=null ,attribute_remarks_3=null ,attribute_date_3=null ,attribute_det_meth_3=null ,attribute_determiner_3=null ,attribute_4=null ,attribute_value_4=null ,attribute_remarks_4=null ,attribute_date_4=null ,attribute_det_meth_4=null ,attribute_determiner_4=null ,attribute_5=null ,attribute_value_5=null ,attribute_remarks_5=null ,attribute_date_5=null ,attribute_det_meth_5=null ,attribute_determiner_5=null ,attribute_6=null ,attribute_value_6=null ,attribute_remarks_6=null ,attribute_date_6=null ,attribute_det_meth_6=null ,attribute_determiner_6=null ,attribute_7=null ,attribute_value_7=null ,attribute_remarks_7=null ,attribute_date_7=null ,attribute_det_meth_7=null ,attribute_determiner_7=null ,attribute_8=null ,attribute_value_8=null ,attribute_remarks_8=null ,attribute_date_8=null ,attribute_det_meth_8=null ,attribute_determiner_8=null ,attribute_9=null ,attribute_value_9=null ,attribute_remarks_9=null ,attribute_date_9=null ,attribute_det_meth_9=null ,attribute_determiner_9=null ,attribute_10=null ,attribute_value_10=null ,attribute_remarks_10=null ,attribute_date_10=null ,attribute_det_meth_10=null ,attribute_determiner_10=null ,coll_object_remarks='collector: KEZ, "Type mess"' ,wkt_media_id=null ,flags=null ,uuid=null ,cataloged_item_type='fossil specimen' where collection_object_id = 97602104
Arctos

# Where it happened
Single Record Data Entry

# Steps to get there
I entered the first record and created it just fine (it is in the bulkloader if you want to see it), then I had a second record to enter with similar data. I wasn't exactly sure if I could create another record from that screen with that data (something to add to documentation text??), but based on the end of the data entry video, I assumed I could, so I changed the catalog number and changed a few bits of data, clicked to create a new record, and the background turned pink with the above error. Screenshots below of the second record I tried to create.

![image](https://user-images.githubusercontent.com/47402809/130529774-d91e430b-1c8d-456f-b9e9-492715363b53.png)
![image](https://user-images.githubusercontent.com/47402809/130529819-026da68a-1528-42d6-b028-a85df56d964d.png)
![image](https://user-images.githubusercontent.com/47402809/130529840-bedb2377-ff02-4e5a-910b-e48a140d2806.png)
![image](https://user-images.githubusercontent.com/47402809/130529883-a1e327a7-c965-4325-b96c-06964030f9f3.png)

**Comment by dustymc** [comment]
https://handbook.arctosdb.org/documentation/understanding-errors.html#error-row-for-relation-table-violates-check-constraint-ck_column_noprint

You've got a nonprinting character in part 1 remarks.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks, I found the hard return!
