### ISSUE TITLE
Bulkload Parts - part_preservation

### ISSUE THREAD

**Issue by SerinaBrady** [ArctosDB/arctos#3875]
Hi!

There is no column for part_preservation when I go to bulk upload parts. I had removed (frozen) from the part_name and had a separate column for the preservation type. However, the bulk loader did not like this. I removed the column and have "frozen" in remarks and that loaded.
Should there be a column for preservation type?

Thanks!
Serina
@campmlc @dustymc @Jegelewicz

**Comment by Jegelewicz** [comment]
Serina,

Preservation is now a part attribute.  See the Separation of Parts and Preservation article in the latest [Arctos Newsletter](https://us17.campaign-archive.com/?u=cfe3221343c60fe519031e616&id=8c47ec5ddf)!

As your parts are already loaded, you can now use the [Part Attribute Bulkload Tool](https://arctos.database.museum/tools/BulkloadSpecimenPartAttribute.cfm) to load the preservation attributes.

Let me know if you have questions.

**Comment by acdoll** [comment]
For future reference, you can add preservation at the same time as a part bulkload. You just add the following columns:
PART_ATTRIBUTE_TYPE_1: preservation	
PART_ATTRIBUTE_VALUE_1: frozen
PART_ATTRIBUTE_DATE_1: _if you have it_	
PART_ATTRIBUTE_DETERMINER_1: _if you have it_	
PART_ATTRIBUTE_REMARK_1: _if needed_

If you have multiple part attributes (e.g., in ethanol and frozen), you can add additional sets of these attribute columns, changing the number (e.g. PART_ATTRIBUTE_TYPE_2, PART_ATTRIBUTE_VALUE_2, etc.)

**Comment by SerinaBrady** [comment]
Awesome, thank you both!
________________________________

**Comment by SerinaBrady** [comment]
One more question! I am trying to have all parts loaded with the full record when I use the bulkloader. Is it possible to give the tissues the locations in this step, or do I have to bulkload parts with their locations separately? They do not have barcodes, just Box and Vial locations. 
I believe the bulkloader does not like the "part_attribute_value" (box*, vial*) and "part_attribute_type" (location) in my file.

**Comment by acdoll** [comment]
The links in the table on the Parts loading page will take you to the appropriate code table containing acceptable values (e.g. https://arctos.database.museum/info/ctDocumentation.cfm?table=CTSPECPART_ATTRIBUTE_TYPE).

Physical locations are dealt with using the [Object Tracking](https://handbook.arctosdb.org/how_to/How-to-Start-Object-Tracking.html) tools. Containers (and, ideally, their hierarchy: vail->box->cabinet->room) need to be created prior to placing collection objects into them (digitally). I am not very familiar with using Object Tracking without barcodes, so we may need to solicit additional help with getting that set up. 

So, to answer your question: no, without a barcode, they cannot be assigned to locations during the bulkload. Once you have created both the parts and the containers, you can put the parts into the container with the [Parts>>Container](https://arctos.database.museum/tools/BulkloadPartContainer.cfm) tool. 
![image](https://user-images.githubusercontent.com/12507297/130692478-6f37a679-00d5-4842-b9ed-27eb2c2c070e.png)

**Comment by Jegelewicz** [comment]
@SerinaBrady you can use a second part attribute for that, but if you have more than one attribute for any given part - I recommend that you load your catalog records without parts, then use the part bulkload tool to load your parts and attributes. Let me know if you have questions about doing that!

**Comment by SerinaBrady** [comment]
Okay, thank you both!
