### ISSUE TITLE
Child will not fit into parent error message

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3878]
We are getting repeated but seemingly random "child will not fit into the parent" messages which don't make sense.
For example, we tried to scan DGR11462 freezer box with dimensions 13.2 x 5.2 x 13.2 into rack DGR11410, with dimensions 13.5 x 68.5 x 13.5 CM, 12 positions,  and got this error.
We have other racks and boxes with these dimensions and there is no problem scanning them.
However, the other boxes in this rack have no dimensions
I removed the dimensions from the box DGR11462 and it scanned into position.

Question then, is: Is there some reason why we can't scan containers with dimensions into a parent container with dimensions if there are other child containers with no dimensions already scanned into this parent?
I shouldn't have to remove dimensions if they are known. 
And yes, all containers should be created in advance with dimensions. But, the reality of the situation is that in dealing with multiple operators across multiple divisions within an institution,  sometimes this doesn't happen.
#3632
@dustymc @Jegelewicz

**Comment by Jegelewicz** [comment]
This issue has been fixed with the change to NULL as default size. Adding the need for documentation to the documentation-wiki repo.
