### ISSUE TITLE
Code Table Request - Part Attribute = representation

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3882]
**Goal**
>  3. Add a new part_attribute_type of 'representation' for things like '35 mm negative' or 'cast' or 'drawing' that are representations of the original primary object. e.g., part_name = 'karyotype' and part_attribute_type = 'representation' and value = '35 mm negative'

from https://github.com/ArctosDB/arctos/issues/3164#issuecomment-906724489

**Context**
See above

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecpart_attribute_type

**Value**
representation

**Definition**
A portrayal, likeness, derivative, or reproduction of a primary object. Examples include cast, photograph, 35 mm negative, reproductions, CT scan, etc.

**Attribute data type**
free text

**Attribute value**
N/A

**Attribute units**
N/A

**Comment by ccicero** [comment]
@Jegelewicz Are you thinking that the values would be a controlled list or text format? Is there a reason we shouldn't just add the part_attribute_type = 'representation' and let operators put in the value they want, depending on the context?

I'm not clear why the dependency affects adding the type 'representation' to the code table?

Do we need more discussion, or can we add it? I'd like to work on the Jim Patton data, but it hinges on this.

**Comment by dustymc** [comment]
I'd say add the attribute as free-text and see what happens - maybe we'll want to migrate to controlled if that doesn't do something so try to be consistent (same as always), but the existence of the attribute is the most-functional flag and having some data available would help guide future discussions.

**Comment by ccicero** [comment]
So can we just do it?

**Comment by Jegelewicz** [comment]
added
