### ISSUE TITLE
Modification to or removal of the "Type" dropdown on Search page

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3883]
> Also discussed was what to do with the 'Type' dropdown which is a mix of DarwinCore and Arctos terms, used inconsistently, and applied at the 'Manage Collection' level which is not ideal (e.g., paleo collections may have a type of 'fossil specimen' but not all specimens in paleo collections are necessarily fossils). This requires more discussion with paleo and cultural folks @Nicole-Ridgwell-NMMNHS @AJLinn.

from https://github.com/ArctosDB/arctos/issues/3164#issuecomment-906724489

See also #3881 for new look at observations or not.

**Comment by dustymc** [comment]
I don't know what's being suggested here, but I don't think most collections see [cataloged item type](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcataloged_item_type) as important (I certainly don't, it looks completely arbitrary from here) and therefore I don't think it belongs in such a prominent location. I'll move it somewhere and close this unless someone has a better idea....
