### ISSUE TITLE
Updated definitions for Event Type terms

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3884]
From #3164 

> **Collection**: Event at which an organism or object was removed from its functional cultural, biological, ecological, or archeological context, for archiving in a museum collection.
> 
> **Encounter**: Event at which an organism or object was encountered but not killed or removed from context. Material samples were taken for analysis and cataloged as a part. Organism may be marked or tagged for identification in subsequent encounters/recaptures. Biopsies and other non-vouchered biological items (e.g., feather, hair, scat, tail tip, ear clip, etc.) are appropriate here.
> 
> **Observation**: Event at which an organism or object was detected but not removed from context, and no material samples were taken for analysis. Human sightings, camera traps, and GPS telemetry data are appropriate here.

**Comment by Jegelewicz** [comment]
Can we use the definitions last suggested? 

> **Collection**: Event at which an organism or object was removed from its functional cultural, biological, ecological, or archeological context.
> 
> **Encounter**: Event at which an organism or object was encountered but not removed from functional cultural, biological, ecological, or archeological context, but physical evidence was collected. Biopsies, trace evidence (e.g., feather, hair, scat, tail tip, ear clip,paint chip etc.) are appropriate here.
> 
> **Observation**: Event at which an organism or object was detected but not removed from its functional cultural, biological, ecological, or archeological context, and no physical evidence was collected. Human sightings, camera traps, and GPS telemetry data are appropriate here.

**Comment by dustymc** [comment]
No objections.


For posterity:

```
arctosprod@arctos>> select * from ctspecimen_event_type;
 specimen_event_type |                                                                                        description                                                                                        
---------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 creation            | Event at which an item was created, manufactured, or otherwise made. Generally refers to human creation of art, cultural items, casts, molds, etc., but could be extended to e.g., nests.
 collection          | Event at which an object was collected through removal from functional cultural, biological, ecological, or archeological context.
 depiction           | Visual representation or conceptual portrayal of associated biological subject or locality. Generally used for images or art of people or places.
 use                 | Event at which an item was used. Generally refers to human use of cultural items.
 observation         | Event at which an object was detected but not removed from context or killed. No material samples were taken. Human sightings, camera traps, and GPS telemetry data are appropriate here.
 encounter           | Specimen was encountered and not killed or removed from context; Biological Samples were taken. Biopsies belong here.
(6 rows)

```

**Comment by Jegelewicz** [comment]
@dustymc I cannot update the encounter definition because:

<html><body>


ERROR_ID | A00280FD-0762-410B-A8C19832A7614884
-- | --
ERROR_TYPE | SQL
ERROR_MESSAGE | ERROR: value too long for type character varying(255)
ERROR_DETAIL |  
ERROR_SQL | UPDATE ctspecimen_event_type SET  specimen_event_type = 'encounter' 			 			 				,description='Event at which an organism or object was encountered  but not removed from functional cultural, biological, ecological, or  archeological context, but physical evidence was collected. Biopsies,  trace evidence (e.g., feather, hair, scat, tail tip, ear clip,paint chip  etc.) are appropriate here. Github Issue' 			 			where specimen_event_type = 'encounter'


</body>
</html>ERROR_ID 	A00280FD-0762-410B-A8C19832A7614884
ERROR_TYPE 	SQL
ERROR_MESSAGE 	ERROR: value too long for type character varying(255)
ERROR_DETAIL 	
ERROR_SQL 	UPDATE ctspecimen_event_type SET specimen_event_type = 'encounter' ,description='Event at which an organism or object was encountered but not removed from functional cultural, biological, ecological, or archeological context, but physical evidence was collected. Biopsies, trace evidence (e.g., feather, hair, scat, tail tip, ear clip,paint chip etc.) are appropriate here. [Github Issue](https://github.com/ArctosDB/arctos/issues/3884)' where specimen_event_type = 'encounter'

Can we provide more characters for the definition?

**Comment by dustymc** [comment]
done

**Comment by Jegelewicz** [comment]
Definitions have been updated. Closing.
