### ISSUE TITLE
Code Table Request - new parts and part attribute values for Observation cleanup

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#3885]
I'd like to add the following parts for physical media that I have in the collection to https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name:

- 35mm slide: Square photographic positive image on a transparent base, stored in a cardboard sleeve. Also known as reversal film.

- photograph: A printed image on a photosensative surface

- cassette tape: An analog magnetic tape recording format for audio recording and playback

I'm not sure if we've decided if part_attribute_type 'representation' will have a controlled code table, but I assume it will. If so, I'd like to add 'jpeg':

- jpeg: a lossy image compression technique used for digital images

**Comment by AJLinn** [comment]
> @AJLinn no changes (and your taxonomy is part-like so I don't think you're missing out), just some possibility to say more about "representations" (for now - I suspect that'll lead to more coolness).

So as my students and I continue to add more records and more images of our objects, what is the preferred way to move forward... add a part attribute under the part "object" that is "representation" and then in value state what kind of representation it is?

OR... keep on truckin' as is with part Media, with the number of digital images captured and on file?

**Comment by dustymc** [comment]
done?
