### ISSUE TITLE
Need Help with Arctos Error - accessions

### ISSUE THREAD

**Issue by SerinaBrady** [ArctosDB/arctos#3887]
Hello, 

I am trying to add a bird record (ASNHC:BIRD:3235) from one accession (ASNHC:Bird 0000.000) to another (ASNHC:Bird 2019.020). When I do this I receive this error: 
Message: ERROR: column reference "collection_id" is ambiguous Position: 163

I have made sure the ASNHC:Bird 2019.020 was created and all relevant boxes were filled out. Any help would be appreciated!

Best, 
Serina

**Comment by SerinaBrady** [comment]
Hi there, 
Any updates/progress on the accession bug? I tried to change the specimen's accession again, and it still gives me an error.
Thanks!

**Comment by dustymc** [comment]
Sorry, I should have pushed a release before I started on my current project. I'll figure out how to get something out ASAP.
