### ISSUE TITLE
Get all related records

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3890]
I am looking at one of our Gold Standard records: https://arctos.database.museum/guid/UMNH:Bird:5573

I can get to the offspring using the link to the MVZ record and back here from there, but what about if I would like to see all of the related records together in search results? How can I do that? Apparently they do not share a collecting event...

![image](https://user-images.githubusercontent.com/5725767/131366100-677a0e19-d91e-4f6e-ba0f-709905a35d0b.png)

**Comment by acdoll** [comment]
What do you mean by related? Same species, same collector, same location, same date...?

**Comment by Jegelewicz** [comment]
Parent of and offspring

**Comment by Jegelewicz** [comment]
In other words, I want a search results page from "Find all" that gets me both [MVZ:Egg:14725](http://arctos.database.museum/guid/MVZ:Egg:14725) and [UMNH:Bird:5573](https://arctos.database.museum/guid/UMNH:Bird:5573)
