### ISSUE TITLE
Code Table Request - new agent relationship member of

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3896]
**Goal**
https://github.com/ArctosDB/internal/issues/117#issuecomment-911738853

**Context**
associate of is awkward when relating members to a group

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctagent_relationship

**Value**
member of

**Definition**
Agent belongs or belonged to the related group agent.

**Priority**
[  Please choose a priority-label to the right.  ]

**Comment by lin-fred** [comment]
I like the idea and the definition.

**Comment by dustymc** [comment]
This would need disambiguated from at least ``associate of`` and ``employee of``; the definition needs to be much better.

The definition also suggests this is a functional replacement for ``group_member``; it is not, that needs clarified.

I dislike "group agent" in the definition - there's no such functionality (and probably won't be). (And "group" is being misused in what lead here anyway).

Clarifying the [goals](https://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html#issue-protips) would be helpful - this seems like a slightly different but still entirely ambiguous value.

**Comment by Jegelewicz** [comment]
> "group agent" in the definition - there's no such functionality

What the heck is this? https://arctos.database.museum/info/ctDocumentation.cfm?table=ctagent_type#group

**Comment by Jegelewicz** [comment]
The problem with the "Group" agents is that they don't allow for date range of "membership". However, if I am related to the Arctos Working Group agent as an "associate of" we can easily do that. We need this functionality and it already exists, I suggest that using the regular agent relationships to demonstrate group membership is the way to go.

See the test of this here - https://arctos.database.museum/agent/21314876

**Comment by dustymc** [comment]
There are agents of type group, I just can't restrict certain relationships to them. (https://arctos.database.museum/info/ctDocumentation.cfm?table=ctagent_relationship#division_of makes me twitchy too - it's fine to *recommend* usage, but there are no functional limitations. I'm just asking for clarity.)

>using the regular agent relationships to demonstrate group membership

Agreed, and that functionality exists for precisely this purpose, I'm still just asking for clarity. 

Agents of type group essentially exist as a data entry shortcut - "you and me" requires fewer columns than "you" and "me." I've never been quite sure if I love that or hate it.

I don't think "AWG" should be an agent of type group, it's an organization. The current belt-and-suspenders approach isn't WRONG in any way that I can put my finger on, but it's unnecessary and seems confusing.

This is partially a vocabulary problem - maybe we need to find and make a habit of using a better word for 'bunch of agents linked by relationships.'

**Comment by Jegelewicz** [comment]
I'm over this and think "associate of" works fine. Closing
