### ISSUE TITLE
ColdFusion Help

### ISSUE THREAD

**Issue by SerinaBrady** [ArctosDB/arctos#3897]
Hello!

I have been battling with ColdFusion report builder for a while now. I had a label I wanted to print but it was pulling more attributes than just "sex." I decided to abandon that label and went with a label and report I know work (has printed for the specimens I need). 
I needed to change "Division of Mammals" to "Division of Birds" and "ASNHC" to "ASNHC:Bird: " so I did that in ColdFusion. 
I uploaded the slightly edited cf file into the report builder, copied the handler from the original report (the one I know works) and I get an error! It says "replace(LOCALITY,' ,','','all') is not a valid ColdFusion expression." Yet the report works for the same specimens in the original file (and this phrase is in the functional report). 
The report that works is "ASNHC_mamm_small_label_vial" and the one that doesn't is "ASNHC_Bird_skel_small_2"
Please help! I just want to print labels for my bird skel boxes!
ps- I tried to attach the cf files, but Github doesn't support them.

**Comment by dustymc** [comment]
<img width="140" alt="Screen Shot 2021-09-02 at 9 15 17 AM" src="https://user-images.githubusercontent.com/5720791/131879937-c920e53c-9c43-4766-95cf-f7c46fcf9c39.png">

Try adding that to the other report.

**Comment by SerinaBrady** [comment]
THANK YOU
It works!
