### ISSUE TITLE
Feature Request - unified parts search

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3898]
New specimensearch field,

Name: ??? help??
Searches: part name, part remark

@atrox10

**Comment by dustymc** [comment]
@acdoll @campmlc what's the label for this?

**Comment by Jegelewicz** [comment]
part values
part plus
part + remark
?

**Comment by dustymc** [comment]
>part values

Suggests part_name (to me), which will still be available and should not be confusing.

>part + remark

If we ever do anything semi-sane with https://github.com/ArctosDB/arctos/issues/3654 or get a workable ontology or ... it might be more than that, and I'd not like to change the UI because we shuffled something around behind the scenes.

>part plus

I ain't got no better ideas....

**Comment by Jegelewicz** [comment]
extended part search?
