### ISSUE TITLE
Part seaching

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#3899]
Can we search on parts and part remarks in the same field to get all the different types of tissues?
E.g.:
![image](https://user-images.githubusercontent.com/12507297/131902998-c4a5b66b-a590-4745-a043-50b0d0b3f03d.png)

and get results for both parts that contain heart (e.g. heart, kidney) and parts that mention heart in the remarks (e.g. part_name=tissue and part_remark=eye, heart and brain)

**Comment by campmlc** [comment]
Agree

**Comment by acdoll** [comment]
oops... same as #3898
