### ISSUE TITLE
Is there a way in Arctos to determine # of specimens in a lot based collection?

### ISSUE THREAD

**Issue by KyndallH** [ArctosDB/arctos#3901]
I'm working on the webinar on Fish collections which is a lot based collection.  So I know in mammals, the # of specimen records returned = number of physical animals. In the fish collection, it is under part under qty. Is there a way in Arctos to view the number of actual pickled fish (so number under qty added together)? They say "whole organism" but one of them just has one whole organism and the other has 23.

Challenge is not including tissues in the count. 

<img width="1542" alt="Screen Shot 2021-09-02 at 1 58 12 PM" src="https://user-images.githubusercontent.com/16887896/131921936-d8cdc9b9-25fb-406b-aeae-3268fec0b728.png">

<img width="1647" alt="Screen Shot 2021-09-02 at 1 58 22 PM" src="https://user-images.githubusercontent.com/16887896/131921952-c9f18c2c-fe7b-47f3-97b6-c85c8cefdf32.png">

**Comment by KyndallH** [comment]
@mkoo @ewommack

**Comment by mkoo** [comment]
You know another handy thing to show would be the option to see results as
a Summary (from the dropdown menu) then Group By Country and Individual
Count

here's the results for all MVZ:Fish (the whole collection) which shows
record count vs. individuals in the lot (I also see that there are some
questionable records without countries so on my to do list now! (so maybe
not the best example for a demo)

[image: Firefox_Screenshot_2021-09-02T22-49-00.064Z.png]

**Comment by ewommack** [comment]
Oooh, or for us small regional collections could we group by County and Species? Or have a conversion that we could use in Berkeley mapper that shows where large lots are versus just one collection site? That would be really helpful for sharing with conservation and manager partners like game and fish.

Though that last might be really confusing - localities for fish are generally the river/stream/water body. There are different localities along the water system, but a lot of my localities use known landmarks outside of the river for historic, or distance from tributary/etc. There is a lot of overlap in collection site.

**Comment by sharpphyl** [comment]
I tried to run the SQL above to get the total quantity count for DMNS:Inv as

arctosprod@arctos>> select sum(individualcount) from flat where guid_prefix ='DMNS:Inv';
  sum  

and get this error: ERROR: syntax error at or near "arctosprod" Position: 1 

Help?

**Comment by Jegelewicz** [comment]
Try just this:

elect sum(individualcount) from flat where guid_prefix ='DMNS:Inv';
sum

**Comment by dustymc** [comment]
See https://github.com/ArctosDB/arctos/issues/3901#issuecomment-912094654

"for fish" is the entirety of what's calculated, not a section or something.

```select random();``` is probably more useful....

**Comment by sharpphyl** [comment]
@Jegelewicz   
select sum(individualcount) from flat where guid_prefix ='DMNS:Inv';
sum
 got me ERROR: syntax error at or near "sum" Position: 3 

@dustymc  When I tried 

select random (individualcount) from flat where guid_prefix ='DMNS:Inv';
sum

I got   ERROR: function random(integer) does not exist Hint: No function matches the given name and argument types. You might need to add explicit type casts. Position: 8 

So next I tried
arctosprod@arctos>> select sum(individualcount) from flat where guid_prefix ='DMNS:Inv';
  sum 
and I got   ERROR: syntax error at or near "arctosprod" Position: 1

**Comment by dustymc** [comment]
Sorry, I was trying to be clever. I'll stop.

Those data aren't calculated for anything except Fish collections (and I don't think they're calculated defensibly there). There may be some old data hanging around, but it won't be useful even if it exists and you manage to get it.

If you want those data, some sort of path to them will need to be created. That discussion is https://github.com/ArctosDB/arctos/issues/3908.

Merge-->https://github.com/ArctosDB/arctos/issues/3908
