### ISSUE TITLE
Feature Request - add UUID to cf_temp_identification

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3906]
**Is your feature request related to a problem? Please describe.**

It's currently using more generic approach

**Describe what you're trying to accomplish** 

tighter links between bulkloader/records/extras

**Describe the solution you'd like**

add UUID, rewrite everything to use it

**Describe alternatives you've considered**

don't

**Priority**

low; it's functional now, this would just make it better.

**Comment by Jegelewicz** [comment]
Is this duplicated in #3989 ?
