### ISSUE TITLE
Feature Request - a way to download & edit partlotcounts & re-upload to make mass edits

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#3909]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

Unless I'm wrong I don't think it's possible to make mass edits to partlotcount data across many records - assuming each value will be unique (I know how to change a bunch of records to all the same value using the modify parts tool). 

 The parts bulkloader can add new parts but not edit/change the data in existing parts, am I correct?

**Describe what you're trying to accomplish** 
An clear and concise overview of the goals; why are you asking for this?

Hundreds of records with changes to their part lot counts & a desire to fix these without entering & editing each record one-at-a-time.

**Describe the solution you'd like**
How might we accomplish your goals?

1) find records of interest
2) download part data
3) edit part data
4) upload edited part data that replaces current part data

**Describe alternatives you've considered**

one at a time editing, or emailing Dusty

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.
high

**Comment by dustymc** [comment]
Seems somewhat plausible if it can exclusively use [part identifier](https://github.com/ArctosDB/arctos/issues/3630#issuecomment-877347199)
