### ISSUE TITLE
Arctos Working Group Organization Agent

### ISSUE THREAD

**Issue by lin-fred** [ArctosDB/arctos#3910]
Continuation of discussion in ArctosDB/internal#117

**Comment by lin-fred** [comment]
To clarify,

We are associating everyone to the Arctos Working Group/Officers organization agent, with all the relationships FROM the individual people TO Arctos Working Group and/or Arctos Working Group Officers

**Comment by dustymc** [comment]
I don't know what's being requested.

**Comment by Jegelewicz** [comment]
@dustymc nothing for you - work for membership and agents committee to get this all set up.

**Comment by Jegelewicz** [comment]
@lin-fred I have made a bit of progress as I come across things in data migration/new collection work, but we probably need a more focused effort. Maybe at our next meeting we can split up a list of agents that need to be related to AWG and just do those as a group?

**Comment by lin-fred** [comment]
@Jegelewicz That's a good idea, thanks. It's going to be discussed on the next meeting either way.

**Comment by dustymc** [comment]
>nothing for you -

Then how about we move this (and https://github.com/ArctosDB/arctos/issues?q=is%3Aopen+is%3Aissue+milestone%3AAnnouncement and "committee stuff" and ??????) to https://github.com/ArctosDB/arctos-misc/issues and reserve this repo for things that change core Arctos functionality or need developer attention? I certainly can't keep up here, and I don't think anyone else can either - more focus would help with that.

**Comment by Jegelewicz** [comment]
I think that needs community discussion - this repo has been used for all general community issues and making everyone look around in multiple repos already causes problems. What could we do so that you can easily exclude these from your attention? Add a label or milestone? I figured that "requires user action" would do that, but I am up for whatever and I can try to stay on top of it as new issues come in.

**Comment by dustymc** [comment]
> needs community discussion 

No argument!

>making everyone look around in multiple repos

That's basically what I'm trying to avoid. Ideally a user would be able to pop in and see if they can guide development without first having to find their way through the maybe-hundreds of Issues that don't (or don't *exactly*, probably) do that. I'm not sure another repo does that, but it's hard to see how it could make anything much worse....

>been used for all

And most of the discussion is from very few users, which suggests to me that we're overwhelming the average user. IDK if that's really the case, but 663 issues is a LOT for any purpose.

I've been a big fan of milestones, but most search operations support only one and we've got a bunch of "not really dev stuff" going - I'm not sure that's working for me anymore, and I don't think anyone else will be able to navigate it. Maybe that's as simple as consolidating some milestones???

**Comment by Jegelewicz** [comment]
@dustymc how about using a project - Development Issues and maybe another for Community Issues?

**Comment by lin-fred** [comment]
I like the use of projects. I've never used the milestone function though....

This issues is in the Agents committee project, still under the agents committee discussion, which shows that it still needs some discussion and a decision from the agents committee before moving forward in any official capacity.

**Comment by Jegelewicz** [comment]
@dustymc I agree that we have way too many open issues - I was trying yesterday to clean some up and I will continue that as time permits.

**Comment by dustymc** [comment]
>projects

IDK, I'm willing to try.

**Comment by Jegelewicz** [comment]
https://github.com/ArctosDB/arctos/projects/36

**Comment by lin-fred** [comment]
Although the end result of this issue is for organization of the AWG members in the agent Arctos page, the initial need was for a better understanding of how groups/organizations work in Arctos, and then how that data is seen. I don't see this issue any different from the plethora of requests made in the issues repo - someone wants to change something that has to do with their data (in this case AWG data), and this change will be made across all of Arctos (like adding the dates/remarks onto the agent relationship so it could be seen on both sides).

If you look at the Agent Projects, there a lots of issues that need to be discussed and moved forward with. Most requests for agents come through this arctos issues repository. There has to be a project to organize them all, otherwise I will not be able to get through them.

I don't want to have agent issues spread out across repositories, and it seems all of them are in this repository? So why not have clean up requests in this repo too?

**Comment by dustymc** [comment]
I found myself trying to figure out why this exists (and not for the first time). The answer turns out to be "not for me" but I'm setting milestones and have no idea what to do with that, and it occurs to me that maybe I'm not the only one who gets lost in the sheer volume of issues. As far as I can tell this is some administrative thing so maybe it's a decent example of the kinds of issues that could benefit from a more-focused audience, and maybe there's some way to sort things so that people can focus on what's important to them and not become inundated with what's not. I obviously don't know how to do any of that, even if I am understanding it....

**Comment by Jegelewicz** [comment]
No, he was just a member from I don't know when until 2015, when he became chair and served until 2017

**Comment by lin-fred** [comment]
A comment on the AWG agent for our meeting in two weeks. The AWG organization agent will be based on the google group membership and the dates? This is correct? 

And this information could be bulk-uploaded?

And to do this the organization should probably not have any relationships in it, as there then will be duplicates?

**Comment by Jegelewicz** [comment]
> The AWG organization agent will be based on the google group membership and the dates? This is correct?

I think that makes sense

> And this information could be bulk-uploaded?

We can get Dusty to add it for us

> And to do this the organization should probably not have any relationships in it, as there then will be duplicates?

We can check for dupes first, then load the rest.

**Comment by dustymc** [comment]
in theory, but I'd expect a few in each list and very few overlaps - probably faster to just use the UI, unless the list is a lot bigger than I expect.

**Comment by lin-fred** [comment]
Thanks all for the help!
