### ISSUE TITLE
Value attribute not encumbered?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3911]
It has been my understanding that the value attribute was encumbered from public view. I happened to check an "on this day" item and see that apparently it isn't?

https://arctos.database.museum/guid/UAM:EH:UA2015-024-0077

![image](https://user-images.githubusercontent.com/5725767/132702718-8405d1e2-a8c4-46c8-aa11-dc92bcd6adfa.png)

**Comment by Jegelewicz** [comment]
OK - I see there must be an encumbrance for this to work.

**Comment by AJLinn** [comment]
Thanks for pointing that out - I’ll check that whole collection and make sure it gets encumbered. I sometimes miss that step esp. when someone else is cataloging the collection.
