### ISSUE TITLE
URLs and emails not formatting properly in EML output

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#3912]
I realize that the MVZ:Fish collection is not on the VertNet IPT so the data aren't available to aggregators.

I used the Arctos EML generator tool to generate the EML file.

URLs and emails are not formatting properly. See attached file.
[MVZ_Fish_eml.txt](https://github.com/ArctosDB/arctos/files/7139242/MVZ_Fish_eml.txt)

**Comment by dustymc** [comment]
https://handbook.arctosdb.org/documentation/encoding.html

You need a better text editor!

[mvz_fish.eml.zip](https://github.com/ArctosDB/arctos/files/7139262/mvz_fish.eml.zip)

**Comment by ccicero** [comment]
@dusty, thanks!
