### ISSUE TITLE
Feature Request - show only projects connected to loanees on add project to loan interface. Not the loan creator. 

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#3914]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
There is a box on the form to create or find projects connected to a loan "Projects using this Loan's Agents; check to add." A problem is that I am an agent on the loan, so it pulls up all of the 20+ projects I am associated with. I think the intention here is to quickly show the projects that the loanees are connected to, to speed up adding to a project, and also help avoid creating superfluous projects. Is it possible to have this show only projects associated with the outside contact and received by agents?

**Describe what you're trying to accomplish** 
Quickly and efficiently add projects to a loan

**Describe the solution you'd like**
Show only the projects connected to the outside contact and received by agents 

**Describe alternatives you've considered**
none

**Priority**
low, but hopefully this is an easy fix if agreed upon.

**Comment by campmlc** [comment]
I agree. I create projects for every loan, so that list is essentially
useless to me and takes up valuable screen space. It should only show
projects related to the outside contact and received by agents.

**Comment by dustymc** [comment]
>also help avoid creating superfluous projects.

And avoid functional duplicates, which are often created sequentially by one user. But, I just did a 30-second scrollthrough and didn't see anything obvious so maybe something else is working to prevent that?

**Comment by cjconroy** [comment]
OK, fine. Maybe no one is making superfluous project connections. But, it is still a waste of space on the page. Is it possible to find out if anyone even uses this box?  Maybe no one does. I usually just search in the box at the top of the page as all I see below are my projects.

**Comment by campmlc** [comment]
Agree - it is currently a useless, space-wasting box - it shows projects
I'm associated with as in-house contact,  but it doesn't even show all of
them - just some random subset of projects totally unrelated to the current
loan request. It could be useful if we limited it to projects associated
with the loanees .Please just limit to projects associated with the
researchers requesting and receiving the loan - received by, and outside
contact.

**Comment by Jegelewicz** [comment]
It would probably take me a week and a bunch of mistakes to get what you guys are asking for, but I could just comment out that section and make it go away - then we could see who is using it because they will complain that it is missing.

**Comment by dustymc** [comment]
> complain that it is missing

Yes. We desperately need to find a way to better facilitate discussion, to involve the people who might use this without overwhelming them with less-core issues or making them feel unwelcome, and to avoid making periodic alternating arbitrary changes.

https://github.com/ArctosDB/arctos/issues/2769

**Comment by campmlc** [comment]
Maybe we need a weekly post summary of Arctos changes, with a log and links
to documentation. A weekly digest?

**Comment by campmlc** [comment]
In the meantime, we have two core users in agreement and no dissention on
the public forum. If the current interface cannot be modified to restrict
to only received by and outside contact agents, then this issue can be
closed. I'll just ignore the useless screen clutter.

**Comment by cjconroy** [comment]
I also mainly see it as clutter and useless code. But, I am happy to just ignore it as well.

**Comment by Jegelewicz** [comment]
It really costs very little for me to comment it out. If 20 people immediately complain that it is missing, All I have to do is remove the comment ().

In this case, that seems like an easy way to decide if anyone cares.
