### ISSUE TITLE
Feature Request - bulkloader coordinates are ambiguous

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3916]
**Is your feature request related to a problem? Please describe.**
``latdeg`` is used for dms and dm.m formats. That's no bueno for the new form (or anything really...).

**Describe what you're trying to accomplish** 
reduce complexity

**Describe the solution you'd like**
shuffle some columns

**Describe alternatives you've considered**
struggle

**Additional context**
need to check if anything else that uses this

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by dustymc** [comment]
In new UI

	
	dec_lat_deg varchar default 'show',
	dec_lat_min varchar default 'show',
	dec_lat_dir varchar default 'show',
	dec_long_deg varchar default 'show',
	dec_long_min varchar default 'show',
	dec_long_dir varchar default 'show',

**Comment by DerekSikes** [comment]
Can we get an ETA on this? This should be the highest priority right now as it's interferring with work. I've just started a giant label print job that I now realize is going to be missing a bunch of taxa that are stuck in the bulkloader because of this.

**Comment by DerekSikes** [comment]
If this isn't fixed soon I'm going to have to edit these records to convert their lat/longs into decimal degrees manually, which is, frankly ridiculous.

**Comment by Jegelewicz** [comment]
@DerekSikes we discussed this yesterday in AWG. @dustymc  needs PostGIS to get this going, but perhaps he can help us out with some kind of work-around for now?

From [AWG Agenda](https://docs.google.com/document/d/1N59TdF5zn00zVdYYEXq87lyneN4g3QgnZwOebNYAdRE/edit#heading=h.8n6rpen68cmu)
> The bulkloader had a bunch of things confounded together, so things got split out
> We’re still waiting for PostGIS to handle UTM and other forms of coordinates.
> PostGIS is currently on the 2nd year task for TACC in the grant. Maybe we should bump it to first year? 
> Dusty has discussed it with TACC, had it in test, but it is getting held up before it makes to production - https://github.com/ArctosDB/internal/issues/90
> Code is all ready for handling PostGIS
> First year is devoted to auditing and set up
> Send a big email to Chris Jordan to ask about where TACC is, info we need, can we get PostGIS?

**Comment by dustymc** [comment]
>some kind of work-around for now?

You can pre-create the localities and use them in data entry, or I could spend ~a few days rebuilding code that will be discarded when postgis becomes available.

**Comment by Jegelewicz** [comment]
@dustymc can you help us out with what is already stuck in the bulkloader? I don't know how many records @DerekSikes is looking at - it may be a lot of work for him to create localities and re-do his records....

**Comment by dustymc** [comment]
I don't have any special magic - I could type them in, but I'll introduce errors that I won't recognize and such.

**Comment by DerekSikes** [comment]
I'm just copying and pasting the D DM coordinates into the collection event remark field as verbatim coordinates, then dividing the DM by 60 get the decimal degrees, changing the original units from D DM to DD and copying the coordinates into the DD fields... one record at a time. But thankfully a lot of the records are from the same sites so it's going faster than if each was unique.

**Comment by Jegelewicz** [comment]
I followed @DerekSikes instructions, but we need to get this fixed or we need to remove these fields from the bulkloader as it could turn into a nightmare project for someone who bulkloads a lot of records in this coordinate format.

Also note that we have now lost the "as entered" coordinate functionality for all of the affected locations.
