### ISSUE TITLE
Make eml better and more useful for updates vs. initial publication

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3919]
> I've added Dusty to the Associated Parties.

@dustymc can we get this put into the eml generator? You were added as technical contact, but it doesn't end up in the eml.

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/data-migration/issues/480#issuecomment-917184676_

**Comment by Jegelewicz** [comment]
@dustymc what information do you need?

**Comment by dustymc** [comment]
Big-picture, some conversation with Dave lead me to believe that the EML isn't being used - is it?

If it is in fact useful, then I need to know what exactly you want added - there are a couple of things mentioned here, one's already there, I'm not sure how the other should be handled.

**Comment by Jegelewicz** [comment]
> EML isn't being used - is it?

Yes it is - currently ONLY when collections are first published to the IPT BUT he may be able to use it for updates in future. Needs testing and I am waiting on MOU with Dave to get finished before I ask him to do anything. Once that is done. maybe a meetup would be best.

**Comment by Jegelewicz** [comment]
Met with @dbloom yesterday to discuss eml improvements to make his life easier. See worksheet comparing what we provide, with what ends up (after Dave's and collection review manual changes) in the IPT. There are some things our eml could be doing better. I will see what I can do about it and then ask for help. We will use changes for ASNHC collection manager to test.

**Comment by Jegelewicz** [comment]
Also, note new capability at https://ipt.gbif.org/manual/en/ipt/latest/gbif-metadata-profile#what-changed-in-version-1-1-of-the-gmp-since-1-0-2

- machine readable license. Note instructions on how to provide a machine readable license can be found [here](https://ipt.gbif.org/manual/en/ipt/latest/license). In particular, I think we could provide:

- multiple contacts, creators, metadataProvider and project personnel

- userIds for any agent (e.g. ORCID, Wikidata)

- providing information about the frequency with which changes are made to the dataset

- providing a project identifier (e.g. to associate datasets under a common project) (add [Arctos project](https://www.gbif.org/network/1f2c0cbe-40df-43f6-ba07-e76133e78c31) for all collections)

- The description can be broken into separate paragraphs versus all lumped into one

**Comment by Jegelewicz** [comment]
Suggest adding this per Dave's recommendation (see Google Sheet)

```<cfset eml=eml & chr(10) & chr(9) & chr(9) & chr(9) & chr(9) & '<alternateIdentifier>#application.serverRootURL#/collection/#d.guid_prefix#</alternateIdentifier>'>```

**Comment by Jegelewicz** [comment]
Suggest changing per Dave's recommendation

```<cfset eml=eml & chr(10) & chr(9) & '<additionalInfo>'>
		<cfset eml=eml & chr(10) & chr(9) & chr(9) & '<para>'>
		<cfset eml=eml & chr(10) & chr(9) & chr(9) & chr(9) & '#EncodeForXML(d.collection_terms_display)#: #EncodeForXML(d.collection_terms_uri)#'>
		<cfset eml=eml & chr(10) & chr(9) & chr(9) & '</para>'>
		<cfset eml=eml & chr(10) & chr(9) & '</additionalInfo>'>```

Change to 

```<cfset eml=eml & chr(10) & chr(9) & '<additionalInfo>'>
		<cfset eml=eml & chr(10) & chr(9) & chr(9) & '<para>'>
		<cfset eml=eml & chr(10) & chr(9) & chr(9) & chr(9) & '#EncodeForXML(d.collection_terms_display)#: #EncodeForXML(d.collection_terms_uri)#; VertNet IPT Norms: http://vertnet.org/resources/norms.html'>
		<cfset eml=eml & chr(10) & chr(9) & chr(9) & '</para>'>
		<cfset eml=eml & chr(10) & chr(9) & '</additionalInfo>'>```

**Comment by Jegelewicz** [comment]
Suggest adding for Wikidata IDs

```
<cfquery name="thisQ" dbtype="query">
	select address from aa where  agent_id=#da.agent_id# and address_type='Wikidata'
</cfquery>
<cfloop query="thisQ">
	<cfset x=x & chr(10) & btbs & chr(9) & '<userId directory="https://www.wikidata.org/wiki/">#EncodeForXML(thisQ.address)#</userId>'>
</cfloop>
```

**Comment by Jegelewicz** [comment]
> Add Dave and Dusty as contacts for ALL collections as technical support

Maybe instead of doing this through collection contacts, we just hard code this into the eml? This should be the same for all collections published through Arctos, then we won't have to rely on collections adding the appropriate technical contacts (or can we somehow just add them for all collections?) Hardcoding would mean exactly one thing needs to be changed if either Dave or Dusty's information changes. Suggest adding the following:

```
<associatedParty>
<individualName>
<givenName>David</givenName>
<surName>Bloom</surName>
</individualName>
<organizationName>VertNet</organizationName>
<positionName>VertNet Coordinator</positionName>
<electronicMailAddress>dbloom@vertnet.org</electronicMailAddress>
<onlineUrl>http://www.vertnet.org</onlineUrl>
<role>programmer</role>
</associatedParty>
<associatedParty>
<individualName>
<givenName>Dusty</givenName>
<surName>McDonald</surName>
</individualName>
<organizationName>Arctos</organizationName>
<positionName>Arctos Programmer</positionName>
<electronicMailAddress>dustymc@gmail.com</electronicMailAddress>
<onlineUrl>https://arctosdb.org/</onlineUrl>
<role>programmer</role>
</associatedParty>
```

**Comment by Jegelewicz** [comment]
> Add any dataset that this replaces 

When collections migrate to Arctos, if their data has already been published to aggregators, we have to set up a resource relationship so that those who have downloaded data under the "old" publication can find stuff in the "new". Dave also sets up a relationship at the dataset level and it gets inserted into the eml like this

```
<dc:replaces>2aa02cf8-c402-412c-9ad1-585e1e185bef/v1.38.xml</dc:replaces>
```

It seems like adding these identifiers to the collections would make sense and would be just one more other identifier a collection might have.

**Comment by ewommack** [comment]
> It seems like adding these identifiers to the collections would make sense and would be just one more other identifier a collection might have.

That sounds like a good improvement to me, just thinking of an archive/tracking situation. We have a number of collections that have already been published in old formats, and now are coming on as Arctos material. If this helps with that transition I think it would be a good idea.

**Comment by Jegelewicz** [comment]
> Hey Teresa,
> 
> An FYI that the ALMNH Taxonomic Coverage in the EML lists 25 taxonomic names and defines them all as "phylum". There are two issues: 1. They all wind up in the same line in the IPT and 2. they are not all phyla, there is at least one class and one genus in there.
> 
> I think that's an easy fix if you want things to populate the IPT directly, but it means they need 25 individual lines. I'm sure there are some other collections that do this in Arctos too.
> 
> Just another item to add to the list of things to sync with metadata.

d

1. I don't really see a way to ensure that the taxa selected match the rank - ugh
2. Write eml to parse comma separated taxon names to individual lines?

**Comment by dustymc** [comment]
I don't think there are any action items here, closing.
