### ISSUE TITLE
Update Manage Collection - required collection contacts user interface

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3922]
Problem: Collection reports were just sent out to Arctos collections. These reports give the names and roles of collection contacts, and provide a warning if a collection contact role has no associated agent. The documentation mildly suggests having all collection contact roles filled out. But the user interface does not specify that any of this information is required.

Suggested Resolution: Change the current Add contact interface in Manage Collection from a select-from-dropdown option to fixed fields for each role, highlighted to indicate that all of these are required, not just one.

Current documentation from https://handbook.arctosdb.org/how_to/How-to-Manage-a-Collection-in-Arctos.html
Contacts
The contacts section is the top section on the right side of the manage collection page.

NOTE Changes to this section are saved by selecting the Save button next to the contact that has been edited.

Contact Name
Anyone who is a contact for the collection must first be entered into Arctos as an agent, with a valid email address (see “How to Create Agents”). Add the name of each person who is a contact for the collection: type their last name and hit the tab key to bring up the list of agents with that name, then select the correct agent.

Contact Role
For each contact, specify their Contact Agent Role through the dropdown of choices. It is recommended that every collection have at least one contact for each role with the exception of mentor, which is optional. Technical Support contact should be given as Dusty L. McDonald unless otherwise advised.

Special Note on Contacts
Selected contacts, including associated address information, are used for EML creation. The Formatted JSON address is used for mailing address

**Comment by dustymc** [comment]
>user interface does not specify that any of this information is required.

Because it's not.

>fixed fields for each role

That doesn't align with the data; there's no 1:1 ratio,

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_contact_role needs lots of work before we make any recommendations.

> Formatted JSON 

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctaddress_type should be updated.

>Technical Support contact should be given as Dusty L. McDonald unless otherwise advised.

No real objections (since I don't think I've ever had a singe question from that pipeline...) but it would be good to figure out the intent of that as well.

**Comment by Jegelewicz** [comment]
As discussed in AWG - adding a an annual check-up to the billing process. See https://github.com/ArctosDB/newsletter/issues/117
