### ISSUE TITLE
Results download bug

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#3924]
Downloaded the search results from https://arctos.database.museum/saved/H%2Esparrows%5FSpellman and discovered that for one record, the sex value was actually a concatenation of all the attributes (e.g. "Juvenile;   no fat; feather tracts barely visible; 0%; 2.6; 40; 6; no; no; unknown"). I redid the search and downloaded again to see if it was something I did; this time 9 of the records have the same issue (file attached). 
Something weird is going on here.

[ArctosData_4A0FD305A8 (2).csv](https://github.com/ArctosDB/arctos/files/7155919/ArctosData_4A0FD305A8.2.csv)

**Comment by dustymc** [comment]
Yep, a function got sideways. I'll refresh, it will take some time.

**Comment by dustymc** [comment]
flat is caught up

**Comment by acdoll** [comment]
Seems to be working fine now - thanks!
