### ISSUE TITLE
error feedback - bulkloading data records

### ISSUE THREAD

**Issue by AprilPayne** [ArctosDB/arctos#3925]
[Bulkload_Species_Data_Custom_Field _Herp_CSV.csv](https://github.com/ArctosDB/arctos/files/7156427/Bulkload_Species_Data_Custom_Field._Herp_CSV.csv)
Does this error look familiar to anyone? I'm trying to bulkload specimen data records. They get through to the staging table but when I select "just load these records" I get this error. I feel like I've combed through my files as much as possible but I can't figure this one out. I've been off Arctos for almost a year so I may just be out of touch with how it operates now. I've attached a file with a few of the records I'm trying to bulkload. Any help is much appreciated.

**Message: ERROR: query returned no rows Where: PL/pgSQL function trigger_fct_ti_bulk_cid() line 13 at SQL statement
Detail:
Check the Arctos Handbook for more information on errors.
This message has been logged as 9A858ABE-58A9-45CE-8D5EB9829A99746C Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue.**

**Comment by dustymc** [comment]
That's Arctos not being able to interpret guid_prefix.

You used HMC:Herp, you probably want HMCM:Herp

**Comment by AprilPayne** [comment]
It's always the simple things...
That was the issue. Thank you!!!!

**Comment by campmlc** [comment]
That was a doozy of a message! No wonder you couldn't figure it out.

**Comment by dustymc** [comment]
>doozy

"just load these records" explicitly bypasses the 'make nice messages' step.
