### ISSUE TITLE
bulkloader assistance - stuff in the bulkloader for a long time

### ISSUE THREAD

**Issue by atrox10** [ArctosDB/arctos#3927]
Hi Dusty  - can I delete April Payne's stuff from the bulkloader? It's been in there since 13:00 her time, which is like 12 hours ago.
Carla and I were talking, if someone is in the bulkloader for at least 1 hour, can we just automatically delete their stuff from the bulkloader?

Thanks,
Carol

** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **

** Outages should be reported to the contacts listed at https://arctosdb.org/arctos-down/ **

** Arctos Documentation is http://handbook.arctosdb.org/ **

** Learn more about Arctos at https://arctosdb.org/ **

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **

**Comment by keg34** [comment]
Sorry for that, Carol.  Please go ahead and delete.  I will remind April that she can't leave stuff there.

**Comment by Jegelewicz** [comment]
@atrox10 I usually just email the person with stuff in there - all operators should have an associated email in their profile and their agent.

**Comment by atrox10** [comment]
Yes, I always email folks right away, they just don't always see my email for several hours or until the next day. It's not April's fault, I think folks don't know that things aren't deleted automatically. Lately every time I want to use the bulkloader someone has left stuff in there for a while (once I did too a few years ago), because they just forgot to delete it or didn't know it wouldn't go away. I think we need to automatically clear this bulkloader after 60 minutes if something has been left in there. With so many of us using it, it's pretty busy. For me I often have time at night to try uploading my data and can't do it because no one is responding to their emails by then.

**Comment by campmlc** [comment]
Agree

**Comment by keg34** [comment]
I would support this if it is doable.  Given that I work with a rotating array of students who are in a constant state of learning the ropes, I'm always concerned that one of them will unwittingly do something that messes things up for other people in the network.  Anything that helps protect against that possibility would be appreciated.

**Comment by dustymc** [comment]
I doubt if any time limit is workable - I've used that for things that can take a week of processors. BUT, the pre_bulkloader exists now so maybe....
