### ISSUE TITLE
Collection roles not visible

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3932]
I tried to have a prospective collection review the user roles at https://arctos.database.museum/Admin/user_roles.cfm but they got an access denied message.

I'd like to have a non-editable version of this open to the public for the purposes of explaining levels of access to prospects and to staff who don't have whatever access is required to get to it (what is that?).

> When I click on the link I get "an error occurred processing this page". When I type arctos.database,museum/Admin it says denied.
> 

Steve

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/new-collections/issues/409#issuecomment-919564957_

**Comment by dustymc** [comment]
Given the normal background activity and size of our security team, I'm just going wontfix with this.

>what is that?)

<img width="291" alt="Screen Shot 2021-09-15 at 7 29 45 AM" src="https://user-images.githubusercontent.com/5720791/133453206-83c4f1c7-b4f8-4b00-9df8-e12287286411.png">
