### ISSUE TITLE
When I tried to go to the URL "https://arctos.database.museum/Admin/user_roles.cfm" I got "An error occurred while processing this page! Check the Arctos Handbook for more information on errors. This message has been logged as 15F50FD8-B4CC-4992-AEAACF681408E4BB"

### ISSUE THREAD

**Issue by sginzbar** [ArctosDB/arctos#3933]
** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **

** Outages should be reported to the contacts listed at https://arctosdb.org/arctos-down/ **

** Arctos Documentation is http://handbook.arctosdb.org/ **

** Learn more about Arctos at https://arctosdb.org/ **

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **

**Comment by mkoo** [comment]
Please make sure you were logged in. For security reasons, you need to log
in every 90 min.

**Comment by Jegelewicz** [comment]
@mkoo @sginzbar please see #3932

**Comment by Jegelewicz** [comment]
@sginzbar try using this instead and let me know if it works http://test.arctos.database.museum/Admin/user_roles.cfm

**Comment by sginzbar** [comment]
Teresa,

Yes, when I am logged in as arctostester I can access the page

 http://test.arctos.database.museum/Admin/user_roles.cfm<https://nam11.safelinks.protection.outlook.com/?url=http%3A%2F%2Ftest.arctos.database.museum%2FAdmin%2Fuser_roles.cfm&data=04%7C01%7Csginzbar%40ua.edu%7C2ae0a2a1a4cd43c4f38508d978552e42%7C2a00728ef0d040b4a4e8ce433f3fbca7%7C0%7C0%7C637673129524238693%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=DbuInGpcIcxfGXuTXhwoq6IKkt98xcJyE4NC8nqJew0%3D&reserved=0>


but I cannot access the page

 http://arctos.database.museum/Admin/user_roles.cfm<https://nam11.safelinks.protection.outlook.com/?url=http%3A%2F%2Ftest.arctos.database.museum%2FAdmin%2Fuser_roles.cfm&data=04%7C01%7Csginzbar%40ua.edu%7C2ae0a2a1a4cd43c4f38508d978552e42%7C2a00728ef0d040b4a4e8ce433f3fbca7%7C0%7C0%7C637673129524238693%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=DbuInGpcIcxfGXuTXhwoq6IKkt98xcJyE4NC8nqJew0%3D&reserved=0>


When I am logged in as myself I cannot access the page

 http://arctos.database.museum/Admin/user_roles.cfm<https://nam11.safelinks.protection.outlook.com/?url=http%3A%2F%2Ftest.arctos.database.museum%2FAdmin%2Fuser_roles.cfm&data=04%7C01%7Csginzbar%40ua.edu%7C2ae0a2a1a4cd43c4f38508d978552e42%7C2a00728ef0d040b4a4e8ce433f3fbca7%7C0%7C0%7C637673129524238693%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=DbuInGpcIcxfGXuTXhwoq6IKkt98xcJyE4NC8nqJew0%3D&reserved=0>


Steve

________________________________
From: Teresa Mayfield-Meyer ***@***.***>
Sent: Wednesday, September 15, 2021 9:29 AM
To: ArctosDB/arctos ***@***.***>
Cc: Steven Ginzbarg ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ArctosDB/arctos] When I tried to go to the URL "https://arctos.database.museum/Admin/user_roles.cfm" I got "An error occurred while processing this page! Check the Arctos Handbook for more information on errors. This message has been lo...


@sginzbar<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsginzbar&data=04%7C01%7Csginzbar%40ua.edu%7C2ae0a2a1a4cd43c4f38508d978552e42%7C2a00728ef0d040b4a4e8ce433f3fbca7%7C0%7C0%7C637673129524228701%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2BBkd9k7FoDnSEeubMdXiWWMq7YXHIYFaUahm%2BergSxE%3D&reserved=0> try using this instead and let me know if it works http://test.arctos.database.museum/Admin/user_roles.cfm<https://nam11.safelinks.protection.outlook.com/?url=http%3A%2F%2Ftest.arctos.database.museum%2FAdmin%2Fuser_roles.cfm&data=04%7C01%7Csginzbar%40ua.edu%7C2ae0a2a1a4cd43c4f38508d978552e42%7C2a00728ef0d040b4a4e8ce433f3fbca7%7C0%7C0%7C637673129524238693%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=DbuInGpcIcxfGXuTXhwoq6IKkt98xcJyE4NC8nqJew0%3D&reserved=0>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FArctosDB%2Farctos%2Fissues%2F3933%23issuecomment-920071533&data=04%7C01%7Csginzbar%40ua.edu%7C2ae0a2a1a4cd43c4f38508d978552e42%7C2a00728ef0d040b4a4e8ce433f3fbca7%7C0%7C0%7C637673129524238693%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kan%2Bht4Ap1gt5xBGpKYDEXubz9p0ZWRHyhKZqmenjvs%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALJGOJGFEE4DKRYETTL7BHDUCCUTHANCNFSM5EBIGVFA&data=04%7C01%7Csginzbar%40ua.edu%7C2ae0a2a1a4cd43c4f38508d978552e42%7C2a00728ef0d040b4a4e8ce433f3fbca7%7C0%7C0%7C637673129524248682%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Ec4NaeSbl%2B9mI4estfPPiTjfeorRX5QLZw2X7wNNnuU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Csginzbar%40ua.edu%7C2ae0a2a1a4cd43c4f38508d978552e42%7C2a00728ef0d040b4a4e8ce433f3fbca7%7C0%7C0%7C637673129524248682%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=XYEZrSRk7QfJJohUQNl3ChNDM4eKWKNh12S7CXb5Zr4%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Csginzbar%40ua.edu%7C2ae0a2a1a4cd43c4f38508d978552e42%7C2a00728ef0d040b4a4e8ce433f3fbca7%7C0%7C0%7C637673129524258680%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2Bzk7I6Bgu893w%2Fg94zgInue7cv1cDVqHGgS12gJY%2F7A%3D&reserved=0>.

**Comment by Jegelewicz** [comment]
That is all working as expected. arctostester has permission in the test instance to view that page, but does not have permission to view it in production. Your personal user doesn't have permission in either Arctos instance.
