### ISSUE TITLE
Other Identifier: Not pulling all records, unable to load bulkload citations to Other Identifier

### ISSUE THREAD

**Issue by KyndallH** [ArctosDB/arctos#3936]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
1) I get different results depending on the search field I choose any identifier, original identifier, and other identifier.

<img width="563" alt="Screen Shot 2021-09-15 at 10 49 36 AM" src="https://user-images.githubusercontent.com/16887896/133492715-183adede-df2b-4200-8cbe-3622b388daf7.png">

<img width="467" alt="Screen Shot 2021-09-15 at 10 50 01 AM" src="https://user-images.githubusercontent.com/16887896/133492725-f401ca15-36bf-4e71-8fad-934cadf89716.png">

<img width="486" alt="Screen Shot 2021-09-15 at 10 50 41 AM" src="https://user-images.githubusercontent.com/16887896/133492732-c10f29c9-c45d-44f6-81bd-0f9120c06f8a.png">

2) The original identifier is in Arctos. Yet, it is saying it can't find it to upload the citation.

<img width="1732" alt="Screen Shot 2021-09-15 at 10 48 52 AM" src="https://user-images.githubusercontent.com/16887896/133492890-194ec2f6-1e99-43dc-9c3a-8eca94d47ab6.png">

**To Reproduce**
1) Search in the three different search fields with the same search terms.
<img width="1024" alt="Screen Shot 2021-09-15 at 11 00 34 AM" src="https://user-images.githubusercontent.com/16887896/133493643-14949e4f-b08e-4783-8029-fcfe36713b82.png">

2) Try to bulkload the citations attached.
[BulkloadCitationsData (6).csv](https://github.com/ArctosDB/arctos/files/7172578/BulkloadCitationsData.6.csv)
 

**Expected behavior**
1) Pulls up specimens.
2) Loads citation with other identifier.

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**
 - OS: 10.14.6
 - Browser Chrome
 - Version 93

**Priority**
High.

**Comment by dustymc** [comment]
https://arctos.database.museum/tools/BulkloadCitations.cfm?action=ld

>One of (guid,guid_prefix+other_id_type+other_id_number) is required. 

<img width="418" alt="Screen Shot 2021-09-15 at 12 06 58 PM" src="https://user-images.githubusercontent.com/5720791/133494416-799b537d-4cb5-400d-a238-7caba0ea17be.png">

You need guid_prefix. 

I'm not sure what's going on with your screenshots - wild guess, there's something that's not visible involved. Click requery and grab the URL - should be something like

https://arctos.database.museum/SpecimenResults.cfm?oidnum=REW&oidoper=LIKE 

(614 records for me, but I'll have different collections)

'AnyID' is a different thing - it's looking at other stuff as well.

And to get ahead of your next problem, I grabbed a random ID from your bulkloader and it's not unique.

https://arctos.database.museum/SpecimenResults.cfm?oidnum=KGM725&oidoper=is

<img width="323" alt="Screen Shot 2021-09-15 at 12 19 41 PM" src="https://user-images.githubusercontent.com/5720791/133496018-0ecc9c4c-e9e1-4c7b-a59b-3a165fd7bb86.png">

**Comment by KyndallH** [comment]
Added GUID... now loading. I have 5,000 records so slow going.

However - why does it do this? I searched for REW but then it shows up as looking for 10013 fish. Is that a cache issue?

MY SEARCH:
<img width="610" alt="Screen Shot 2021-09-15 at 12 23 47 PM" src="https://user-images.githubusercontent.com/16887896/133504330-d7679e23-88be-4d0a-a568-c14b847809f3.png">

RESULTS:
<img width="385" alt="Screen Shot 2021-09-15 at 12 23 54 PM" src="https://user-images.githubusercontent.com/16887896/133504352-1766b16d-a092-44ff-a73b-7d29060b0675.png">

**Comment by KyndallH** [comment]
Bulkloader related: Part Attributes

<img width="878" alt="Screen Shot 2021-09-15 at 12 19 36 PM" src="https://user-images.githubusercontent.com/16887896/133504509-79eec425-3611-4033-bb6f-3357e8f1acc2.png">

Why aren't these loading?

<img width="1084" alt="Screen Shot 2021-09-15 at 12 26 38 PM" src="https://user-images.githubusercontent.com/16887896/133504590-9136b275-e074-40da-bdb9-62780e727951.png">

**Comment by dustymc** [comment]
Not sure on the first one - looks like you have a collection selected, if there's not a number somewhere I can't see try restarting your browser. 

Parts checks GUID (and fails because if finds a whole lot of tissue) before barcode - I'll swap that and update docs for next release, you should be able to remove GUID to make them run now.

**Comment by acdoll** [comment]
FWIW I had a similar instance today where previous search terms remained in the widget even while the results were appropriate for my current search.

**Comment by Jegelewicz** [comment]
I have actually noticed that happening as well.

**Comment by KyndallH** [comment]
Exact same search: UAM bird selected and Other ID contains REW

First search:
<img width="688" alt="Screen Shot 2021-09-17 at 11 31 21 AM" src="https://user-images.githubusercontent.com/16887896/133843824-f40f4e5d-03f7-42f3-a68c-b9ad12d03f6a.png">

Second search - pulls up my records:
<img width="654" alt="Screen Shot 2021-09-17 at 11 31 54 AM" src="https://user-images.githubusercontent.com/16887896/133843860-abf41157-acb0-49cb-9718-9e5ff682db64.png">
