### ISSUE TITLE
Need Help with Arctos Error -Unable to Delete Media

### ISSUE THREAD

**Issue by crcarter00** [ArctosDB/arctos#3938]
# Error Text
**ERROR: Exactly one key is required; 0 were provided. Where: PL/pgSQL function trigger_fct_tr_mediarelations_biu_requireonekey() line 101 at RAISE**

# Where it happened
**Attempting to delete media in Edit Media.   
# Steps to get there
**Edit Media.  Successfully deleted labels.  But taken to error page when attempting to delete relationships.**

# Problem
**Media not deleted.  Am I missing a better way to delete media? 

![2021-09-15 13_40_28-Window](https://user-images.githubusercontent.com/84087467/133499833-7cb05c7e-aadd-41c2-ab4e-72ed2fbd1e8e.png)

![2021-09-15 13_41_48-Manage Media](https://user-images.githubusercontent.com/84087467/133499851-31693e3d-58ad-4845-b6ec-c870ab6f43a5.png)

# Solution
**Community response with directions for how to correct the problem**

**Comment by dustymc** [comment]
Woops - try now.

**Comment by crcarter00** [comment]
That did it!  Thanks!
