### ISSUE TITLE
Summer 2021- Carr Summary

### ISSUE THREAD

**Issue by Cynthia-Carr** [ArctosDB/arctos#3939]
[Summer 2021:Cynthia Carr.zip](https://github.com/ArctosDB/arctos/files/7174592/Summer.2021.Cynthia.Carr.zip)
[Summary of Summer Internship.docx](https://github.com/ArctosDB/arctos/files/7174594/Summary.of.Summer.Internship.docx)

**Comment by Cynthia-Carr** [comment]
@campmlc

**Comment by Cynthia-Carr** [comment]
[MSB Mamm papers.docx](https://github.com/ArctosDB/arctos/files/7174635/MSB.Mamm.papers.docx)

**Comment by Cynthia-Carr** [comment]
[QueryProject:Publication mockup.docx](https://github.com/ArctosDB/arctos/files/7175064/QueryProject.Publication.mockup.docx)

**Comment by campmlc** [comment]
Thank you, @Cynthia-Carr for all your hard work this summer! And thanks for documenting everything you have done here!

**Comment by ewommack** [comment]
Thanks for the wrap up @Cynthia-Carr - would you be ok if I used your summary to put together a wrap up article for October newsletter? 
summer intern article #58

**Comment by Cynthia-Carr** [comment]
Yes, let me know if you need anything.
