### ISSUE TITLE
Need Help with Arctos Error

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#3941]
<img width="1409" alt="Screen Shot 2021-09-17 at 7 16 24 AM" src="https://user-images.githubusercontent.com/17605945/133807268-adf61525-6c5f-47c9-9bf2-4dbafd64ae99.png">

# Where it happened
Bulkloader

# Steps to get there
There are no coordinates entered and the specific locality/verbatim locality used the "No specific locality recorded." auto button.

# Problem
Records won't load and I have no idea what to do about it.

# Solution
Please provide assistance - lots of our collections will not be geolocated!

**Comment by dustymc** [comment]
This stuff (coordinate metadata):

<img width="744" alt="Screen Shot 2021-09-17 at 8 22 57 AM" src="https://user-images.githubusercontent.com/5720791/133808164-cf9c9909-af9a-4781-8de5-3c03b6e0fb8d.png">

needs cleared out (or accompanied by coordinates).

FYI there's a ["v2" entry screen ](https://github.com/ArctosDB/arctos/issues/3691#issuecomment-921090957)that should be better about this sort of thing in test....

**Comment by AJLinn** [comment]
So just delete the content of those columns?

This is what the data entry page looks like now:
<img width="607" alt="Screen Shot 2021-09-17 at 7 26 31 AM" src="https://user-images.githubusercontent.com/17605945/133809966-f5a28a44-6c2f-4a6b-ad8e-e510c26a2e88.png">

Does that mean that for every single record that has no coordinate data I'm going to have to go into the bulkloader and fix it?

**Comment by dustymc** [comment]
> every single record

Well probably not, but that sort of thing is why there's about to be a new form....

Lam or I can help if cleaning up becomes a problem.

**Comment by AJLinn** [comment]
Okay, I can deal with a handful at a time... for now!
I'll make notes on screen shots of the new form for things that are wonky for cultural collections.
