### ISSUE TITLE
Quarantine Taxon Name - Equus cumminsi

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#3942]
Issue Documentation is at http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

Name Quarantine Documentation is at https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxon_name_type

The name suggested for quarantine is: Equus cumminsi (correct spelling is Equus cumminsii)

The reason for quarantine is: misspelling, but the misspelling is used in publications

The suggested treatment for all identifications currently using this name is: There are none.

Collections currently using this name in identifications include: There was one NMMNH:Paleo specimen using this name, and I've already changed it.

I've already added the alternate spelling relationship.

**Comment by Jegelewicz** [comment]
Sounds good.

**Comment by dustymc** [comment]
If you're the only one using: Open issue, change, close issue (or someone will use it and then this will drag on forever!).
