### ISSUE TITLE
Summer 2021 Arctos Internship Summary - Genevieve Anderegg

### ISSUE THREAD

**Issue by genevieve-anderegg** [ArctosDB/arctos#3943]
Thank you for a great summer everyone! I learned a lot and loved being a part of the working group discussions every month. I hope I contributed some useful ideas what will enhance Arctos! 
Attached is my internship reflection, and all the citations I gathered this summer. In total, I generated 10,273 specimen citations from 213 publications for 4 institutions, and edited many projects to update their funding information and related publications (not sure on the exact number).
I also contributed ideas to redesigning the Projects and Publications page on issues #3736 #3737 #3738 and #3739.
Thank you to my advisors Michelle Koo, Mariel Campbell, Kyndall Hildebrandt, and fellow intern Cynthia Carr for a fantastic summer! 
[Arctos Internship Summary - Genevieve Anderegg.docx](https://github.com/ArctosDB/arctos/files/7187965/Arctos.Internship.Summary.-.Genevieve.Anderegg.docx)
[MSB Specimen Citations Bulkloader - GCA 2021-09-12.xlsx](https://github.com/ArctosDB/arctos/files/7187966/MSB.Specimen.Citations.Bulkloader.-.GCA.2021-09-12.xlsx)
[MVZ Specimen Citations Bulkloader - GCA - 2021-09-12.xlsx](https://github.com/ArctosDB/arctos/files/7187967/MVZ.Specimen.Citations.Bulkloader.-.GCA.-.2021-09-12.xlsx)
[UAM Specimen Citations Bulkloader - GCA 2021-09-12.xlsx](https://github.com/ArctosDB/arctos/files/7187968/UAM.Specimen.Citations.Bulkloader.-.GCA.2021-09-12.xlsx)
[Pub worksheet Rev2_26 Mar 2021_Judy Miller Tom3 - GCA.xlsx](https://github.com/ArctosDB/arctos/files/7187969/Pub.worksheet.Rev2_26.Mar.2021_Judy.Miller.Tom3.-.GCA.xlsx)
[MaryMoorePubReview11 Tom 6 - GCA.xlsx](https://github.com/ArctosDB/arctos/files/7187970/MaryMoorePubReview11.Tom.6.-.GCA.xlsx)
[Publications Entry Revised Sandra Tom2 - GCA.xlsx](https://github.com/ArctosDB/arctos/files/7187971/Publications.Entry.Revised.Sandra.Tom2.-.GCA.xlsx)
[Publications Entry Revised Sandra Tom 5 - GCA.xlsx](https://github.com/ArctosDB/arctos/files/7187972/Publications.Entry.Revised.Sandra.Tom.5.-.GCA.xlsx)
[Pub worksheet Rev2_2 April 2021 Judy Tom 7 - GCA.xlsx](https://github.com/ArctosDB/arctos/files/7187973/Pub.worksheet.Rev2_2.April.2021.Judy.Tom.7.-.GCA.xlsx)
[Pub worksheet Rev2_30 Mar 2021 Judy Tom 4 - GCA.xlsx](https://github.com/ArctosDB/arctos/files/7187974/Pub.worksheet.Rev2_30.Mar.2021.Judy.Tom.4.-.GCA.xlsx)
[Pub worksheet Rev2_25 Mar 2021__Judy Miller Tom 1 - GCA.xlsx](https://github.com/ArctosDB/arctos/files/7187975/Pub.worksheet.Rev2_25.Mar.2021__Judy.Miller.Tom.1.-.GCA.xlsx)

**Comment by genevieve-anderegg** [comment]
@mkoo @campmlc @KyndallH

**Comment by campmlc** [comment]
Thank you, Genna! This is wonderful. We really enjoyed working with you and
appreciate all your hard work to make these data linkages. Please feel
welcome to attend any of our meetings in the future and keep in touch!

**Comment by ewommack** [comment]
Thanks for the wrap up @genevieve-anderegg! Would you be ok if I used it to write a wrap up article for the October Newsletter?
summer intern article #58

**Comment by genevieve-anderegg** [comment]
@ewommack Yes of course!

**Comment by ewommack** [comment]
Ah I realized I did the referencing to the other issue wrong. Here is the Newsletter issue: https://github.com/ArctosDB/newsletter/issues/58
