### ISSUE TITLE
SQL to get list of agents used by a collection plus Agent Remark and Record Count

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#3945]
We periodically review the agents used by our collection either with the SQL or on the Manage Agent screen.  

Can SQL be added to the Cheat Sheet (List of Agents (Preferred Agent Name) for an Institution) to include data (in order of priority) in the fields Preferred Name, Agent Remark, Record Count (in our collection) and Agent Type?

**Describe alternatives you've considered**
Keep a spreadsheet with this data and maintain manually

**Priority**
Medium

**Comment by dustymc** [comment]
Assuming you mean collectors....

```
  select
  preferred_agent_name,
  agent_remarks,
  agent_type,
  count(distinct(cataloged_item.collection_object_id)) reccount
from
  agent
  inner join collector on agent.agent_id=collector.agent_id
  inner join cataloged_item on collector.collection_object_id=cataloged_item.collection_object_id
  inner join collection on cataloged_item.collection_id=collection.collection_id
where
  guid_prefix='DMNS:Inv'
group by 
  preferred_agent_name,
  agent_remarks,
  agent_type
```
[temp_dmns_colls(1).csv](https://github.com/ArctosDB/arctos/files/7196463/temp_dmns_colls.1.csv)

**Comment by Jegelewicz** [comment]
SQL now placed here - https://github.com/ArctosDB/documentation-wiki/blob/gh-pages/_sql_cheats/collection_agent_search.markdown

**Comment by sharpphyl** [comment]
Woohoo!  That's exactly what we need.  THANKS!
