### ISSUE TITLE
error feedback

### ISSUE THREAD

**Issue by droberts49** [ArctosDB/arctos#3946]
Trying to update accessions listed in catalogue records and am receiving error message:

Example: https://arctos.database.museum/guid/CHAS:Bird:3356
Click edit and add in the correct accession number (chas:mamm 3831), then receive this:
![image](https://user-images.githubusercontent.com/16580148/134034644-de8cf161-9371-439f-aafb-abc26c439fce.png)

**Comment by dustymc** [comment]
There will be a fix tonight.

Merge-->https://github.com/ArctosDB/arctos/issues/3887
