### ISSUE TITLE
Trying to create taxon term 

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#3947]
In the past, I have been able to create a WoRMS (via Arctos) classification by entering the aphiaID and refreshing.

<img width="706" alt="Screen Shot 2021-09-20 at 2 20 09 PM" src="https://user-images.githubusercontent.com/15368365/134069919-fb0ec83a-7501-4d18-94d5-3ef1cf2d5c20.png">

Today, every time I do that and save I get this message:

<img width="1535" alt="Screen Shot 2021-09-20 at 2 23 01 PM" src="https://user-images.githubusercontent.com/15368365/134070226-d1df377f-4955-4f7e-974e-288d8c1f95ea.png">

I don't find NCTERM_7 in the handbook.  

I can create the classification by cloning any taxon classification into the name and then refreshing the correct aphiaID, but why doesn't it work to just add the aphiaID to the classification and refresh?

**Comment by Jegelewicz** [comment]
I think it is a blank classification term "NCTERM_7" feels like non-classification term number 7

**Comment by dustymc** [comment]
I can confirm this is a bug, probably related to recent updates - @Jegelewicz are you going to fix?

**Comment by Jegelewicz** [comment]
I can try!

**Comment by Jegelewicz** [comment]
So, I upped the value in the code back to "10", but I am not 100% sure that is a permanent fix.  @dustymc Can you pull for me?

**Comment by Jegelewicz** [comment]
That works -at least for now!
