### ISSUE TITLE
Add link to Collections Contacts/Operators report to Manage Collection

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3948]
Please add link to or actual report for operators and users for a collection to Manage Collection page.
Currently, that info is in Reports: View Statistics: Collection Contact/Operator report.
Priority: soon would be nice

**Comment by Jegelewicz** [comment]
Any particular place you'd like it to show up?

**Comment by Jegelewicz** [comment]
And just to make sure - you want a link to this? https://arctos.database.museum/info/collection_report.cfm

**Comment by Jegelewicz** [comment]
Maybe here?
![image](https://user-images.githubusercontent.com/5725767/134246378-d326d58a-49e4-4ce3-bc17-8fe4ac9d56ce.png)

**Comment by Jegelewicz** [comment]
I made an attempt in test - @dustymc will need to pull before we can see what it's like.

**Comment by campmlc** [comment]
Yes to the above - thanks!

**Comment by Jegelewicz** [comment]
Link added in test - I just fixed the alignment problem, but @dustymc will have to pull for it to show up.

**Comment by Jegelewicz** [comment]
This is operational.
