### ISSUE TITLE
Agent Activity page doesn't link to collecting event edited records

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3951]
On the agent activity page below, there is no link to the records edited by this agent:
Arctos Activity by Angelo Soto
Catalog Record Events Assigned or Verified by Angelo Soto
Assigned 250 events for 250 catalog records
https://arctos.database.museum/info/agentActivity.cfm?agent_id=21274615

**Comment by dustymc** [comment]
Are you asking for a link to the archives?
