### ISSUE TITLE
Make collection detail page more better

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3956]
>  detail page (which is just "details" from home.cfm

I'm beginning to feel like that page needs some love and also that you should be able to get to it from any record in the collection rather than it being kinda hidden the way it is now.

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/arctos/issues/3953#issuecomment-925900312_

**Comment by Jegelewicz** [comment]
@dustymc I will work on this - I have some stuff started and once you pull, I'll see how it looks.

**Comment by dustymc** [comment]
You gotta commit first....

**Comment by Jegelewicz** [comment]
Sorry - doing three things at once!

**Comment by Jegelewicz** [comment]
Other things that would be cool here:

1. Map of collection objects bounded by coordinates provided
2. Links to agent pages for contacts
3. Link to taxon page when provided

**Comment by Jegelewicz** [comment]
Add gbif powered citation list

https://github.com/ArctosDB/newsletter/issues/109#issuecomment-926781751

**Comment by dustymc** [comment]
>Add GBIF powered citation list

That deserves a dedicated discussion. Eg https://doi.org/10.1016/j.tree.2021.07.009 just downloaded everything in GBIF (https://doi.org/10.15468/dl.3pa1nh), there's no way to know if they actually used anything from https://www.gbif.org/resource/search?contentType=literature&gbifDatasetKey=5a6977c1-ece6-44b8-b71d-43cb1d4e0919 or not. Depending on the circumstances that may all make perfect sense, or be a step backwards from "some rats from Alaska." This has come up a few times, I don't think anyone quite knows what to make of it, at the very least it should be **clearly** contrasted with what Arctos calls "citations."

**Comment by Jegelewicz** [comment]
>  should be clearly contrasted with what Arctos calls "citations.

Agree - and some sort of statement to that effect along with the widget makes sense.

**Comment by Jegelewicz** [comment]
Sent to GRSciColl today:

> I am the project coordinator for Arctos and I would like to discuss how we might directly populate entries in GRSciColl for all of the collections in Arctos. We already hold the information included in GRSciColl  in our system and we would prefer that our users have the ability to maintain their information in their collection management system and not need to duplicate effort by copying it to GRSciColl.
> 
> For example, the University of Texas at El Paso Biodiversity Collections Herbarium:
> 
> Arctos Page
> GRSciColl Page
> 
> There is really no reason these two pages should contain significantly different  information and we would like to see if we can make the process of keeping them in sync easier for Arctos collection managers.
> 
> I'd be happy to meet and discuss possibilities.
> 
> Thank you,

Teresa J. Mayfield-Meyer

**Comment by acdoll** [comment]
Response from GRSciColl:

>Dear Teresa,
>
>Thank you for contacting us. Yes it makes perfect sense to maintain the information in one place whenever possible.
>We are currently working on updating our system to make it possible for institution to choose a primary source for their records. Currently, institutions can already do that to get their records updated by using the information from Index Herabriorum. Once our system is updated, we will progressively enable additional possible sources.
One of those sources will be GBIF datasets metadata. I can see that around 100 Arctos datasets are already available on GBIF. We could link all those datasets to share information with GRSciColl.
>
>In addition to that, we could explore how to make Arctos one of the possible sources of information in the future. I will get back to you next week, after we have a change to discuss whether this is something we can do.
>
>Thanks for helping us improve GRSciColl!
>Let me know if you have any question.
>All the best,
>Marie

**Comment by Jegelewicz** [comment]
> Links to agent pages for contacts

 - tried to get these added. Will see once they show up in test.

**Comment by Jegelewicz** [comment]
It doesn't work - boo hoo!

**Comment by Jegelewicz** [comment]
trying something else

**Comment by Jegelewicz** [comment]
Well, now there is a link, but the page 404s - need to get agent ID

**Comment by Jegelewicz** [comment]
See if this works!

**Comment by Jegelewicz** [comment]
It worked! Yay!

**Comment by Jegelewicz** [comment]
I think that's all I can do here. taxonomy can include comma separated terms and maps can wait.

**Comment by acdoll** [comment]
Nice work @Jegelewicz! One other comment about the display here: for the collections that have their acronym after their institutions name, it displays twice on the collections page:
![image](https://user-images.githubusercontent.com/12507297/153256469-00fdb857-4725-46ab-9a1a-079936e9c05e.png)
Can we standardize this somehow so it doesn't do this? I think the collections page adds the acronym for those collections that don't have it written in with their institution (only the most recent ones). We could each remove the acronym from our manage collection pages, but that seems like a lot of work. Can you edit the code here to see if the name includes the acronym, and if not, then add it? This definitely low priority, but if it's easy to fix it would be nice. If there are plans for a more extensive revamp of these pages (collections and portals) it can wait until then.

**Comment by dustymc** [comment]
@Jegelewicz those agent links are expensive - which probably doesn't matter from that page which gets very low traffic, but in general pulling the ID and building ``/agent/{id}`` links is a much better approach.

>Can we standardize this somehow

No, somewhere we agreed to take whatever's supplied (and it's now editable in the UI, so any standardizations wouldn't last). I can help clean up any weirdness from previous attempts (or whatever that is) though.

>see if the name includes the acronym, and if not, then add it?

"includes" is almost guaranteed to find a way to melt something, "ends with space-paren-string-paren" is probably workable. I'd still rather just figure out why we've done that and un-do it if it's not doing anything useful/is causing problems.

Better yet, can we just standardize the collection header and its usage? I think there's some leftover portal-idea and it's possible to display CollectionA's header over CollectionB's data (eg in specimenresults) so we can't just always display the simple license-n-such-having version. Can we limit header customization to catalog records and simplify, or simplify/standardize in some other way?

**Comment by Jegelewicz** [comment]
@acdoll Go to manage collection and remove the thing in parenthesis

![image](https://user-images.githubusercontent.com/5725767/153272749-6556417b-32e2-472a-ac1b-c3cfdc8a5cdd.png)

There is further discussion of this here - https://github.com/ArctosDB/internal/issues/161#issuecomment-1032929539

**Comment by Jegelewicz** [comment]
> those agent links are expensive - which probably doesn't matter from that page which gets very low traffic, but in general pulling the ID and building /agent/{id} links is a much better approach.

I copied the code from Project pages - which probably gets used quite a bit more and maybe should be less expensive too?

**Comment by dustymc** [comment]
>Project

Thx-changed for next release.

**Comment by acdoll** [comment]
> page which gets very low traffic

This is why I hesitated even mentioning this minor issue. 

> Go to manage collection and remove the thing in parenthesis

Thanks. I knew that, but I can only change our collections - I was looking for a more comprehensive solution for all collections. 

> Can we limit header customization to catalog records and simplify, or simplify/standardize in some other way?

This seems like a reasonable suggestion. 
The only place where I see this Institution Name and acronym appear is here on the collection page.
