### ISSUE TITLE
Bulkloader doesn't display any result

### ISSUE THREAD

**Issue by AdrienneRaniszewski** [ArctosDB/arctos#3959]
**Describe the bug**
browse and edit of the bulkloader does not display any results for me. works for other users though

**To Reproduce**
1. Go to Data Entry
2. Click on Bulkloader
3. Click on Browse and Edit
4. See no results

**Expected behavior**
to see everything in the bulkloader

**Screenshots**
<img width="1025" alt="Screen Shot 2021-09-23 at 2 21 21 PM" src="https://user-images.githubusercontent.com/23192428/134579244-e04320ea-a0fb-464c-81bb-cbb14fc302cb.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: chrome, safari

**Comment by dustymc** [comment]
That's usually from being timed out/logged out - can you confirm that's not the problem before I dig more?

**Comment by AdrienneRaniszewski** [comment]
It’s not. I’m activity entering data. But had tried logging out and logging back in anyway. No luck

**Comment by dustymc** [comment]
What's 

https://arctos.database.museum/component/Bulkloader.cfc?method=getDTRecords&draw=200&enteredby=AdrienneR&length=10

look like?

**Comment by AdrienneRaniszewski** [comment]
oops wrong pic

**Comment by AdrienneRaniszewski** [comment]
<img width="1764" alt="Screen Shot 2021-09-23 at 3 25 00 PM" src="https://user-images.githubusercontent.com/23192428/134586369-1717eb2a-db20-4722-9556-71ceac923a81.png">

**Comment by dustymc** [comment]
Cool, data. Everything seems to be working behind the scenes.

Could be your network, which has happened with UNM a few times, but that would _probably_ be messing with other computers in the area.

If not that, it's probably your browser - restart everything, if that doesn't work turn off all extensions and restart again, and/or try a different browser.

Turn off anything that might be messing with your network stream - anti-virus and VPNs and such.

Hopefully it's one of those, but let me know if not....

**Comment by AdrienneRaniszewski** [comment]
I've tried most of that already. I'm about done for the week, so I'll just let it be for now. Maybe it will fix itself over the weekend! :-)

**Comment by campmlc** [comment]
I just had the same thing happen. I was able to log in and access the
bulkloader. I downloaded some records. Then I went in to edit a single
record, saved the edits, and returned to Table. Once there, I could see no
records, and couldn't filter to make any appear.
I'm at home on my home network, not at MSB.

**Comment by SerinaBrady** [comment]
I also am having this issue. I loaded data into the bulkloader and went to approve records and nothing shows.

**Comment by campmlc** [comment]
I was able to get it to work yesterday partially by exiting and re-entering
the bulkloader, but if I edited a record and tried to go back the records
were gone.

**Comment by dustymc** [comment]
I can't make this happen, I can't find any evidence of it happening elsewhere, and I can't see any problems on the things I control - still seems like network and/or browser. There should be something interesting in browser debug tools, but you might need some kind of hands-on tech support to figure that out. Or grab a copy of https://www.mozilla.org/en-US/firefox/developer/ and we can zoom screen-share.

**Comment by jebrad** [comment]
Yes my #3961 is this same problem, it is still happening to me.  At work and at home, multiple computers and browsers at each.

**Comment by dustymc** [comment]
Should be patched - related to customizing the view.

**Comment by jebrad** [comment]
Fixed now, thank you!
