### ISSUE TITLE
[CONTACT]

### ISSUE THREAD

**Issue by jebrad** [ArctosDB/arctos#3961]
Is the bulkloader broken?  I cannot get it to return anything when I click "filter", and it has a double-list of column headings where I would normally expect the results, which looks wrong.

![Screen Shot 2021-09-25 at 2 09 48 PM](https://user-images.githubusercontent.com/62565118/134786017-d343516a-517e-42a8-be56-801345d6df16.png)

**Comment by keg34** [comment]
Seems to be working for me.

**Comment by jebrad** [comment]
It looks a little better after I clicked "show all columns" -
![Screen Shot 2021-09-25 at 2 47 15 PM](https://user-images.githubusercontent.com/62565118/134786752-9c7662b8-097a-44d7-aa74-8b83f125b1d9.png)
But it still returns nothing regardless of Entered By, Accession, Collection.  (does not "return Zero records", rather it seems to not do anything after I click "filter")

**Comment by campmlc** [comment]
Yes, there is something going on - see #3959 
Try exiting and re-entering. Or you could try using a different browser or incognito window?

**Comment by jebrad** [comment]
This issue is being covered in #3959. Closing this now.
