### ISSUE TITLE
Add units for attribute - gape width

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#3963]
**Goal**
Add units to gape width (it's free text right now)

![image](https://user-images.githubusercontent.com/38706617/134943007-a3843ad4-c7bd-4a0c-af42-7f30f7a95210.png)

**Context**
Gape width is currently free text instead of the standard measurement and units (unless there's something I don't know about gape width?)

**Table**
attribute table - birds

**Collection type**
Birds

**Attribute data type**
number + units

**Comment by mvzhuang** [comment]
Got it. Deleted!

**Comment by dustymc** [comment]
Done, cache should clear within the hour, dropdowns might be weird before then.
