### ISSUE TITLE
Container Series Error feedback

### ISSUE THREAD

**Issue by esdearmon** [ArctosDB/arctos#3972]
I am trying to create a container series but keep receiving this error message:

Message: Invalid container_type;Invalid institution_acronym; this form is a very bad place to experiment

The container_type I am using is "jar" and the institution_acronym is "MSB" (no quotations in the csv file for uploaded file).

![Capture](https://user-images.githubusercontent.com/52967524/135327112-1e732745-008e-4993-9347-4b359c205440.PNG)

**Comment by dustymc** [comment]
[Data please](https://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html#issue-protips) - but that's usually caused by one or more blank trailing lines in the CSV.

**Comment by esdearmon** [comment]
Yes, that was the issue. I completely forgot to delete that extra line, thank you!


Emily S. DeArmon

Sr. Collection Manager: Fishes

Museum of Southwestern Biology

***@***.***

(505) 277-6005

________________________________
