### ISSUE TITLE
Feature Request - taxonomy source anchors should not be split

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3973]
**Is your feature request related to a problem? Please describe.**

This should be one list, not split - it's confusing on an already-busy page, most users probably don't care about the distinction, and my brain refuses to accept the idea that the list isn't all of the list. 

The distinction is also not accurate - Arctos Relationships is "local" but not available for use as a preferred classification.

<img width="381" alt="Screen Shot 2021-09-30 at 9 55 02 AM" src="https://user-images.githubusercontent.com/5720791/135498408-5c615702-c9ad-4bb9-83ba-28f164535495.png">

**Describe what you're trying to accomplish** 

Find stuff

**Describe the solution you'd like**

One list

**Describe alternatives you've considered**

Don't find stuff

**Comment by Jegelewicz** [comment]
This was specifically requested by the Taxonomy Committee and @sharpphyl https://github.com/ArctosDB/arctos/issues/3263#issuecomment-750898772

**Comment by sharpphyl** [comment]
I really like having the distinction.  Do we need a different name for one or both of the sources?  

The table below lists the local sources that collections use for classifications and can edit (although any update overwrites the WoRMS (via Arctos) classification.   According to the [Handbook ](https://handbook.arctosdb.org/documentation/taxonomy.html) the others are Webservice data you can't edit but can clone into a local source.

https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxonomy_source

<img width="776" alt="Screen Shot 2021-10-05 at 3 30 53 PM" src="https://user-images.githubusercontent.com/15368365/136105586-76d21748-e060-473a-84c7-5a9626f47bbb.png">

In this case, only Arctos and WoRMS (via Arctos) contain the taxon name.

Additionally, the taxon page allows users to delete the non-local sources - with lots of cautions.  

<img width="257" alt="Screen Shot 2021-10-05 at 3 45 49 PM" src="https://user-images.githubusercontent.com/15368365/136107390-bff0617c-6140-4c0a-804d-d0e0e87738d8.png">

So we have local and non-local descriptors built into instructions and the taxonomy pages.  I'm not sure why separating the list into the two segments is a problem.

<img width="905" alt="Screen Shot 2021-10-05 at 3 46 09 PM" src="https://user-images.githubusercontent.com/15368365/136107402-d7050db3-95eb-4994-b1bf-86f02aed63c1.png">

Teresa added the jumps to the Classifications which helps reduce the scrolling time - which was significant before.  

Maybe renaming the non-local as "Webservice sources" would help, but I'd like to keep the distinction.  Is this screwing up collections that use the other "local" sources in the taxonomy source table?

**Comment by Jegelewicz** [comment]
> Is this screwing up collections that use the other "local" sources in the taxonomy source table?

I don't think anyone but @dustymc has even noticed this...

BUT

> Do we need a different name for one or both of the sources?

Probably. I was thinking of changing them to

Editable Sources
Non-editable Sources

but we really don't want people editing WoRMS (via Arctos)

Again, I am not really sure anyone else cares. If someone is emailing Dusty with complaints, I'd like to have them comment here so we can discuss as a community.

**Comment by dustymc** [comment]
>why .. problem.

>has even noticed 

^^ that! For most users - those who don't have edit powers (maybe 99.something% of taxonomy traffic) - all THINGS of a kind should be together. I had a need to check a specific source and I couldn't find it - turns out there's a different list and what I needed was over there. Most users wouldn't notice; they'd just never find half the stuff. I'd have never found it if I wasn't also in the DB looking at the data and KNEW it was there, somewhere. It's just not good UI, again unless maybe you're one of the small group of users who can edit.

**Comment by Jegelewicz** [comment]
>  all THINGS of a kind should be together.

I would argue that splitting does just that and even if I go with your definition of these "things", they are all right there. I think we need more than just three opinions.

**Comment by sharpphyl** [comment]
> Why? That's the only thing that's defensibly edited in the single-use form!

But all edits will be overwritten in the next refresh of the WoRMS (via Arctos) classification.  The only change that would be permanent would be to change the aphiaID.  

> all THINGS of a kind should be together. 

But all sources are not the same kind.  The Webservice/non-local sources can't be used as classifications until they are cloned into a local source, so the distinction is significant. 

Can you give an example of not being able to find something on that screen because of the distinction between local and Webservice sources?

**Comment by dustymc** [comment]
[Maybe have two columns then where they are side by side? Also add in some extra italics or extra bit <button> for the ones you can edit](https://docs.google.com/document/d/1eBdty00GvTGsszWXFbqXU9k0KRUSmEkYXUGrkxHx_2c/edit#)

Seems reasonable to me, I don't think my brain would refuse to recognize a two-column layout (and/or differentiated by some styling or whatever) as different parts of the same THING.

**Comment by lin-fred** [comment]
Not sure if it would help, but another addition to this is having the header be Sources, and then local/external be the subheaders

**Comment by Jegelewicz** [comment]
I am a bit disappointed that we agreed that the users should be the ones who decide, but our decision was thrown out. I have been creating and editing A LOT of taxonomy in past few months and this setup has worked great for me and as far as I know for everyone else (nobody has complained except @dustymc and IMO he should not be creating or editing taxa manually EVER - his skills are required elsewhere for things mere mortals are unable to do).

End of rant.

I would be happy with @lin-fred suggestion and I can change it to  that if everyone agrees.

**Comment by campmlc** [comment]
Was it clear yesterday that the Taxonomy Committee had made a
recommendation? I got the impression we were being asked to come up with a
solution.In general, if a Committee makes a recommendation, there should be
good reasons presented before the community overturns the recommendation.

**Comment by Jegelewicz** [comment]
This is a recommendation that had already been implemented and now is being changed.

**Comment by Jegelewicz** [comment]
I don't think this is the fix we had hoped for.

![image](https://user-images.githubusercontent.com/5725767/193049206-bd23f72a-1091-4bec-9413-84f3a4b63404.png)

@sharpphyl

**Comment by sharpphyl** [comment]
I agree that this is not the fix we hoped for.  Putting the two "local" sources in **bold** without any explanation doesn't help anyone not already familiar with the entire taxonomic set-up.  Having the descriptions is fine (although usually we put in a link to a table with that data), but it still doesn't show which classifications are sources used for classifications and which are internet sources that can be cloned.
