### ISSUE TITLE
Code Table Request - Posidonia Shale Formation

### ISSUE THREAD

**Issue by aklompma** [ArctosDB/arctos#3974]
**Goal**
Add Posidonia Shale Formation to the formation code table.

**Context**
Posidonia Shale Formation exists (https://www.sciencedirect.com/science/article/pii/S0031018221001127) and I need to use it for one of the specimens to be cataloged. 

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlithostratigraphic_formation

**Value**
Posidonia Shale Formation

**Definition**
A Jurassic (Toarcian) unit mostly exposed in SW Germany. It is the same as Posidonienschiefer (https://macrostrat.org/sift/#/strat_name_concept/39006), but the international name (Posidonia Shale Formation) is preferred by most. 

Can anyone add it to the code table?

**Comment by Jegelewicz** [comment]
Done. Thanks for the reference to Macrostrat!

**Comment by aklompma** [comment]
Many thanks!
