### ISSUE TITLE
Repeated annotation

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#3975]
This annotation was repeated multiple times [Review Annotations](https://arctos.database.museum/info/reviewAnnotation.cfm?action=show&atype=specimen&guid_prefix=DMNS%3AEgg&institution=&reviewer_comment=NULL&submitter=&reviewer=) . Not sure why I am listed as "Annotation by" (one of then is dlm) when it was "Detected by automation from specimen detail page." I had previously reviewed it, then just did it again before realizing the duplications. Can you delete all of these duplicates so I don't do it again in six months?

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/3530
