### ISSUE TITLE
print label error

### ISSUE THREAD

**Issue by amgunderson** [ArctosDB/arctos#3976]
**Describe the bug**
I get this error when trying to print UAM box labels from a search result.
<img width="1075" alt="Screen Shot 2021-09-30 at 4 40 46 PM" src="https://user-images.githubusercontent.com/8440698/135548837-1b59160b-bbdd-4153-8766-432c8c12a15f.png">

**Comment by dustymc** [comment]
It works for me - that's usually from a bunch of tabs open on the report server, and almost certainly your browser getting confused in some way.
