### ISSUE TITLE
classification editor isn't happy

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3978]
I don't get an error, but I can't save either - something's not right.

>     documentation
> 
> https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxon_term#aphiaid (which isn't correct; source matters)

@dustymc I tried to correct this, but upon save received this error:

An error occurred while processing this page!
Message: The key [ROWID_ROWID_142] does not exist.
Detail:
Check the Arctos Handbook for more information on errors.

This message has been logged as 67A86331-AD1D-4576-97FBC29A1263880F Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue.

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/Arctos-Presentations/issues/44#issuecomment-932298934_

**Comment by Jegelewicz** [comment]
@dustymc classification editor or just this code table? I don't have any problems editing a classification, just editing the Definition for a term in https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxon_term

**Comment by dustymc** [comment]
code table editor for classification data
