### ISSUE TITLE
Are there statistics for how a collection is used?

### ISSUE THREAD

**Issue by AprilPayne** [ArctosDB/arctos#3980]
I just have a general question about looking up information on how a collection is being used by Arctos users/ visitors. For example, how many "hits" or "clicks" a collection gets, how many times a collections' specimen data is being downloaded, etc. 

I apologize if this question doesn't belong here or if the answer is in the Arctos handbook somewhere. I didn't know how to even begin looking up this question so I figured I'd ask here.

**Comment by Jegelewicz** [comment]
@AprilPayne start at the Arctos main menu Reports/Services > View Statistics > Usage Statistics

But also check some of the other reports. If you don't find what you are looking for (or can't interpret what you find - just ask here!

**Comment by AprilPayne** [comment]
Thank you, @Jegelewicz 
It's giving me a 500 internal service error so I'll try again later.

**Comment by Jegelewicz** [comment]
@dustymc any chance we can get ststs back (or just get them for a single collection so that there isn't a timeout)?

**Comment by dustymc** [comment]
Issue, but I don't think this collection has many citations.


https://arctos.database.museum/info/queryStats.cfm --> https://github.com/ArctosDB/arctos/issues/2750 is probably a better place to start.

```

arctosprod@arctos>> select
arctos->         c.guid_prefix, 
arctos->         count(*) as query_count, 
arctos->         c.guid_prefix, sum(c.rec_count) as record_count
arctos-> from logs.stats_search_collection c, logs.stats_search_main m
arctos-> where m.temp_table_name = c.temp_table_name
arctos-> and m.datestring::varchar ~ '^2020'
arctos-> and c.guid_prefix ~ '^HMCM:'
arctos-> group by c.guid_prefix
arctos-> order by c.guid_prefix;
 guid_prefix | query_count | guid_prefix | record_count 
-------------+-------------+-------------+--------------
 HMCM:Arthro |          77 | HMCM:Arthro |         6978
 HMCM:Bird   |          60 | HMCM:Bird   |         1805
 HMCM:Geo    |          15 | HMCM:Geo    |          704
 HMCM:Herb   |         161 | HMCM:Herb   |        16088
 HMCM:Herp   |          26 | HMCM:Herp   |          183
 HMCM:Mamm   |         296 | HMCM:Mamm   |         2259
(6 rows)

Time: 3762.269 ms (00:03.762)
arctosprod@arctos>> select
arctos->         c.guid_prefix, 
arctos->         count(*) as query_count, 
arctos->         c.guid_prefix, sum(c.rec_count) as record_count
arctos-> from logs.stats_search_collection c, logs.stats_search_main m
arctos-> where m.temp_table_name = c.temp_table_name
arctos-> and m.datestring::varchar ~ '^2021'
arctos-> and c.guid_prefix ~ '^HMCM:'
arctos-> group by c.guid_prefix
arctos-> order by c.guid_prefix;
 guid_prefix | query_count | guid_prefix | record_count 
-------------+-------------+-------------+--------------
 HMCM:Arthro |         226 | HMCM:Arthro |        16229
 HMCM:Bird   |         253 | HMCM:Bird   |         4285
 HMCM:Geo    |          59 | HMCM:Geo    |         1480
 HMCM:Herb   |         467 | HMCM:Herb   |        42373
 HMCM:Herp   |         102 | HMCM:Herp   |          569
 HMCM:Mamm   |         553 | HMCM:Mamm   |         3976
(6 rows)

Time: 3701.751 ms (00:03.702)
arctosprod@arctos>> 
```

Downloads stats are

<img width="448" alt="Screen Shot 2021-10-04 at 7 13 16 AM" src="https://user-images.githubusercontent.com/5720791/135867034-b2230a9c-ec15-46eb-b770-eb50512ff283.png">

but there's nothing very collection-specific in there.

**Comment by AprilPayne** [comment]
Thank you @dustymc 
I really just want a quantitative number of the times our collection specimens have been viewed so I could pass that on to my supervisors and the powers that be to show that our collection is being "used" on Arctos.

**Comment by dustymc** [comment]
I think the above numbers are what people generally use for that. 

https://github.com/ArctosDB/internal/issues/50 is probably the best place to request additional/different logging

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/3983
