### ISSUE TITLE
Manage citations uses accepted ID agent for all IDs (thus wrong agent for non accepted IDs)

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#3981]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

Manage citations uses accepted ID agent for all IDs (thus wrong agent for non accepted IDs)

**To Reproduce**
https://arctos.database.museum/Citation.cfm?publication_id=10007265#newCitation

citation type - choose voucher

paste in this GUID: UAM:Ento:358087

three identifications will appear -

Rhantus wallisi (accepted)

    Nature of ID: fine features
    Identified By: Yves Alarie on 2021-10-01
    ID Sensu:
    ID Remark: 

    Dytiscidae (unaccepted)

    Nature of ID: fine features
    Identified By: Yves Alarie on 2013
    ID Sensu:
    ID Remark: 

    Insecta (unaccepted)

Nature of ID: features
Identified By: Yves Alarie on 2017-06-12
ID Sensu:
ID Remark: Former nature_of_id: student.

The problem is that only one of these 3 IDs was identified by Yves Alarie. 

This has happened with all the records I've checked.

**Expected behavior**

The Identified by agent should be the identified agent who made that identification.

**Screenshots**

see screenshot

![Screen Shot 2021-10-01 at 5 15 12 PM Oct 1, 21](https://user-images.githubusercontent.com/9099827/135699440-188c53a0-8a27-4e3a-a933-be4e3644d2dd.jpg)

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.
High

**Comment by DerekSikes** [comment]
This is worse that I at first thought. I'm trying to add citations to non-accepted IDs and this fails. For example in the screenshot above the accepted ID is Rhantus wallisi and I clicked on the non-accepted ID 'Dytiscidae' but the citation was created for the accepted ID instead. Thus the priority is even higher because it seems I can't make citations for non-accepted IDs at all. 

Not just a visual name display confusion but but a broken functionality bug.

**Comment by DerekSikes** [comment]
A workaround is to make these citations from within the catalog record ID panel instead of from within the publication 'manage citations' panel.

**Comment by dustymc** [comment]
There's a fix in next release, which I'll get out ASAP. Please test/confirm at http://test.arctos.database.museum.
