### ISSUE TITLE
Feature Request - Add "Volume" to container dimensions 

### ISSUE THREAD

**Issue by jtgiermakowski** [ArctosDB/arctos#3982]
**### Howdy!**

**Is your feature request related to a problem? Please describe.**
For container type "jar" it would be most useful to have a dimension of volume, only WxHxL is available currently

**Describe what you're trying to accomplish** 
We track and use different jars based on volume, so that's all we need to communicate. Having the volume in the container description makes it very easy to locate jars and estimate their capacity for different specimens

**Describe the solution you'd like**
Add "volume" to container dimensions without requiring input of WxHxL (though still useful). Use liters as the unit (not ml)

**Describe alternatives you've considered**
using WxHxL is not intuitive and much more cumbersome. 

**Additional context**
Remarks is not as useful for volume description

**Priority**
Normal - but the sooner the better :-)

**Comment by dustymc** [comment]
Volume and WxHxL are not interchangeable. WxHxL is used to determine if a child will fit in a parent (and so stop you from scanning a box into a nunc and such). Volume won't do that - a 1ml container may or may not fit into a 1l container, depending on the WxHxL of each.

If there are relatively few values, you might consider new container types.

I could calculate volume from WxHxL, would need to rebuild stuff to display it.

We could add a volume "field" which would provide more flexibility than calculating (eg the actual WxHxL of your 1L jars is not going to add up to 1L), but that might set up some confusion as to what it DOES (ignoring WxHxL can provide no dimension control).

Functionally, I don't think any of that's different than remarks (or description or whatever) - volume just can't DO anything that I can see - so maybe this could be seen as a UI problem (eg make some free-text field more searchable, or suggest values, or ????).

**Comment by Jegelewicz** [comment]
@jtgiermakowski have you figured out a way to handle this - or do we need to work on it?

**Comment by Jegelewicz** [comment]
While it seems that a volume field would, indeed be useful, there has been no response, so I am closing due to lack of interest.
