### ISSUE TITLE
Collections Management Page not showing Collection website

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#3986]
**Describe the bug**
When I go to Manage Collections I see that I have entered a website into the web link data slot.
![Collections website here](https://user-images.githubusercontent.com/18562884/136073010-8f7cfdcc-f477-48a7-9ced-97142385d52b.jpg)

but when I got to the collection's portal page it says that there is no website provided

![But says no website here](https://user-images.githubusercontent.com/18562884/136073166-95ad8d0f-88ed-4d12-afee-909a65e20b18.jpg)

Am I entering the website info in the wrong area? I couldn't see another option, but I could have totally missed something

**To Reproduce**
To Manage Data -> Metadata ->Manage Collections -> selected UWYMV:Bird

**Expected behavior**
It would be great to have the website be accessible on the portals page. I'm just obviously not doing something correct.

**Desktop (please complete the following information):**
Mac OS, Chrome

**Comment by dustymc** [comment]
If you just changed something it's probably cached - check back in an hour. If not let me know and I'll dig.

**Comment by ewommack** [comment]
> If you just changed something it's probably cached - check back in an hour. If not let me know and I'll dig.

Yep I was adding in the new Administrative Contact into the UWYMV:Bird collections, but I see the same problem in my other collections (just checked UWYMV:Egg) and I didn't change anything in there yet.

**Comment by ewommack** [comment]
> relying on "link text" (what's displayed)

Sorry confused...what does that mean? There is no "More Information" text area to fill out under Manage Collections. Purpose and Preservation Method(s) have their own area to fill out. Where do I add in "link text"?

**Comment by dustymc** [comment]
Just below the link itself.

<img width="298" alt="Screen Shot 2021-10-05 at 12 17 32 PM" src="https://user-images.githubusercontent.com/5720791/136088542-c63390be-ddc7-4a5f-8679-e251d4bac0ad.png">

**Comment by ewommack** [comment]
Thanks @dustymc! I updated the UWYMV:Bird collection, and if it works I'll update the others.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/3956

**Comment by ewommack** [comment]
It works! I shall not correct the other collections. Thanks @dustymc !
