### ISSUE TITLE
Code Table Request - Pine Barren Member

### ISSUE THREAD

**Issue by aklompma** [ArctosDB/arctos#3992]
**Goals**
Add Pine Barren Member to the lithostratigraphic member code table.

**Context**
Needed for specimens to be cataloged.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlithostratigraphic_member

**Values**
Pine Barren Member

**Definitions**
Pine Barren Member = a Paleocene (Danian) member of the Clayton Formation exposed in central Alabama, USA. 
https://macrostrat.org/sift/#/strat_name_concept/3290, https://doi.org/10.1093/jcbiol/ruz002

Would it be possible to add these two formations to the code table?

**Comment by Jegelewicz** [comment]
Added, but need to add metadata to Clayton Formation - includes Pine Barren Member? @Nicole-Ridgwell-NMMNHS is this correct?

![image](https://user-images.githubusercontent.com/5725767/136293849-5ee789fd-470f-4d5b-9195-ff71a8b4b738.png)
