### ISSUE TITLE
Survey on use of persistent identifiers in cultural heritage collections

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3995]
From https://discourse.gbif.org/t/survey-on-use-of-persistent-identifiers-pids-in-collections/3063

As part of the UK Towards a National Collection program the Heritage PID project (of which I am a part) is running a survey on the use of persistent identifiers in cultural heritage collections. Natural history collections are considered part of our cultural heritage, so [this survey](https://forms.gle/AkX2XpoB5H9XQ5v17) may be of interest to members of the GBIF community who are exploring assigning persistent identifiers (PIDs) to specimens in their collection.

The survey 5 can be anonymous and takes approximately 20 minutes to complete, depending on your responses. The survey will remain open until 1 November 2021.

@dustymc maybe we could fill this out as a group during office hours if we have time?

**Comment by campmlc** [comment]
I'd like to be involved in this, as I am looking into making drastic
changes in how we assign IDs in DGR.

**Comment by Jegelewicz** [comment]
@AJLinn YES - I think this is going to make it's way through all kinds of collections as we start to aggregate information.

Perhaps this is a good place to start - https://journal.code4lib.org/articles/13427

**Comment by dustymc** [comment]
See also https://handbook.arctosdb.org/how_to/cite-specimens.html and maybe/eventually the last little blurb on https://github.com/ArctosDB/arctos/issues/3630#issuecomment-919271854 will lead to the option of making eg http://test.arctos.database.museum/guid/UAM:EH:UA96-011-0007/PID23840227 persistent.

**Comment by Jegelewicz** [comment]
survey is closed
