### ISSUE TITLE
Collection event bulkload tool - load event attributes at the same time?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3996]
Concerining https://arctos.database.museum/tools/BulkloadCollectingEvent.cfm

When I load parts, I can also load the part attributes at the same time. When I load collecting events, I can't load the associated attributes at the same time - I have to load them separately in a different tool (https://arctos.database.museum/tools/BulkloadEventAttrs.cfm). Possible to make the collecting event bulkload tool more like the part bulkload tool?

**Comment by dustymc** [comment]
>When I load parts, I can also load the part attributes at the same time. 

There's no stable part identifier which you might use as a handle - there is for events.

Multi-function loaders will always have limitations - you can load six part attributes with a part, if you need fewer you still have to look at empty columns, if you need more then it's a code change, and there are practical limits on how far that can go.

If you need one event attribute then add one row, if you need 297445456 then add 297445456 rows - the current loader is normalized and so has no "flat limits."

That all sorta seems like more trouble than it's worth to me, but I could be convinced that dealing with one file is somehow worth the complications (in which case I'll probably suggest a "split combo file into events and event attrs" tool - I don't want to evolve back towards overly-complicated limited-scope less-sustainable loaders unless we REALLY have to).
