### ISSUE TITLE
Code Table Request - Collecting Source = unknown

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3997]
**Goal**
Clean up definitions in the collecting source code table

**Context**
No new value is requested - just a change in definition

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcollecting_source#unknown

**Value**
unknown

**Definition**
 It is unclear whether the collected object was captive or wild

**Priority**
[  Please choose a priority-label to the right.  ]

**Comment by dustymc** [comment]
>So just use NULL?

IDK, what are you trying to say? If it's something like 'no comment' then NULL is appropriate, if it's not that then maybe we do need something more. If we do then I halfheartedly propose some more _active_ value that doesn't look quite so much like a very verbose NULL - "unable to determine" maybe.

**Comment by dustymc** [comment]
>"may be captive".

If "may" ~ "probably" then I might just call it captive and add a specimen event remark.

If "may" ~ "probably not" then I might just call it wild and add a specimen event remark.

If you've really dug around and just can't figure it out then something like "unable to determine" (and the same remark, of course) could save the next person some fruitless research.

Even "may be captive" contains a little more certainty than I'd prefer for NULL, but it will keep the thing out of improper analyses and make it easier to find things that need detective work. 

Flip a 4-sided coin.....

**Comment by Jegelewicz** [comment]
> I have some data, but it is unclear, so I'm going to select unknown because at least I have some info I can add.

Yes - we need NULL for non-biological collections and maybe "unknown" is not the correct term we should be using for what @ewommack said above, but I think we need something that is not misleading. Selecting "captive" just be cause you don't know may mean that you never find anything out because everyone just ignores it. It is when people research the grey areas that we gain more information....

**Comment by gradyjt** [comment]
Sorry, I know you closed this but I want to be sure that your decision:
> I don't think we need "unknown". NULL indicates that no information was given and research is required.
doesn't require me to take any actions with my data? If so I just want to know what it is and add it to my worklist.

**Comment by Jegelewicz** [comment]
@gradyjt I don't think it does - this hasn't ever existed in the code table so you shouldn't have been able to use it. Do you really want it? If so, re-open the issue!

**Comment by gradyjt** [comment]
Haha no I'm good, just trying to make sure I don't need to add something to
my to-do list!
