### ISSUE TITLE
Need Help with Arctos Error - working in test, attempting to load some collection event in the bulkload tool

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3998]
# Error Text
An error occurred while processing this page!
Message: Error invoking external process
Detail: psql:/usr/local/webroot/temp/excopy_jegelewicz_20211008091049977_063.sql:364: ERROR: numeric field overflow DETAIL: A field with precision 12, scale 10 must round to an absolute value less than 10^2. CONTEXT: COPY cf_temp_collecting_event, line 247, column dec_long: "-100.058557"
Check the Arctos Handbook for more information on errors.

This message has been logged as 706B2A4C-E445-4960-B191B402453F33C6 Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue. 

# Where it happened
http://test.arctos.database.museum/tools/BulkloadCollectingEvent.cfm

# Steps to get there
browse for attached file and load it to the tool
[MemphisCollectingEventBulkloadTemplate.csv](https://github.com/ArctosDB/arctos/files/7314276/MemphisCollectingEventBulkloadTemplate.csv)

# Problem
**Community response to describe the problem that caused the error**

# Solution
**Community response with directions for how to correct the problem**

**Comment by dustymc** [comment]
woops - switcharooed
