### ISSUE TITLE
Can't delete duplicate otherIDs

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4000]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
At some point duplicate OTHER IDs were loaded to the following records:
MSB:Mamm:265945
MSB:Mamm:269633
MSB:Mamm:269634
But I cannot fix this problem because when I try to delete one of the duplicates, I get an error saying there can't be duplicates.

**To Reproduce**
1. Go to https://arctos.database.museum/guid/MSB:Mamm:269634
2. Click on Edit OtherIDs
3. Click "delete" in box next to one of the duplicate DMNS:Mamm:13694 Ids
An error occurred while processing this page!
Message: ERROR: duplicate key value violates unique constraint "iu_oidnum_id_typ_disp_refs" Detail: Key (collection_object_id, other_id_type, display_value, id_references)=(23623167, DMNS:Mamm, 13694, same individual as) already exists.
Detail:
Check the Arctos Handbook for more information on errors.
This message has been logged as 6339CED6-0B92-45BD-839D5E67EB6F1A4F Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue.

**Expected behavior**
To be allowed to fix this problem without getting hung up in an never-ending logic loop of doom

**Screenshots**

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
High, because if I don't fix these now, they will never get fixed, and I'm getting ready to bulkload a lot more otherIDs

**Comment by dustymc** [comment]
You can just delete all of the "would be duplicates if not for all the trailing spaces" at once, then add back.
