### ISSUE TITLE
Feature Request - catalog record license/terms display

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4001]
https://github.com/ArctosDB/documentation-wiki/issues/235 made me realize that some information isn't as accessible as it should be, so I added....
<img width="319" alt="Screen Shot 2021-10-12 at 8 48 09 AM" src="https://user-images.githubusercontent.com/5720791/136988563-c90f1ee0-0520-47ed-ba2f-778ed9ebda2f.png">
..... some stuff to the "subheader" of catalog record pages (screenshot from http://test.arctos.database.museum/guid/MVZ:Bird:106079). 

It's getting pretty crowded up there, but I'm not sure what else to do with this. HELP!

Opening in next release - this will go to production and be closed in a few days if nobody has better ideas.

**Comment by dustymc** [comment]
>that info is included in the metadata

So is everything else! I suspect collections will want this included, somewhere, but ???

Might be useful to add loan_policy_url to catrec pages as well, somewhere.

**Comment by dustymc** [comment]
>Add that stuff to the collection header.
<img width="1726" alt="Screen Shot 2021-10-12 at 5 04 10 PM" src="https://user-images.githubusercontent.com/5720791/137044974-8c50cdd7-8747-4dd0-8738-7d8da812bf02.png">


<img width="1717" alt="Screen Shot 2021-10-12 at 5 04 37 PM" src="https://user-images.githubusercontent.com/5720791/137045019-5c877706-c059-42cd-ac8e-61db6cdb7a61.png">


<img width="1698" alt="Screen Shot 2021-10-12 at 5 05 08 PM" src="https://user-images.githubusercontent.com/5720791/137045092-59a07d42-10bf-4b65-9fdc-e34e39cdea87.png">

**Comment by campmlc** [comment]
Yay!
