### ISSUE TITLE
disappearing localities?

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#4007]
I created a bunch of localities 2 days ago and they are all gone from Arctos. They are LocID 11441526-11441538. I realize now that I should have put a nickname in there. But, 2 days seems rather quick. I was going to use them for data entry maybe Friday. Could there be a way to leave localities alone for ~ a month before deleting? Or send the creator a message before hand?

**Comment by dustymc** [comment]
Merge-->https://github.com/ArctosDB/arctos/issues/3617
