### ISSUE TITLE
Arctos Down - 

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#4009]
Please complete to the best of your ability.

## Unplanned Outage
 - Date and time outage began:
 2021-10-15 7:10 am ADT
All my tabs are spinning

 - Date and time outage is expected to end: 
 - Reason for outage:
 - Expected behavior during and after the outage:

## Planned Outage
 - Date and time outage will begin:
 - Date and time outage is expected to end:
 - Reason for outage:
 - Expected behavior during and after the outage:

## Communication before/during outage
- [ ] Pin this issue
- [ ] Banner updated @jegelewicz 
- [ ] Email sent to AWG @ewommack 
- [ ] Email sent to Arctos Google Group @ewommack 
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @jegelewicz
- [ ] Email sent to AWG @ewommack
- [ ] Email sent to Arctos Google Group @ewommack
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by AJLinn** [comment]
<img width="591" alt="Screen Shot 2021-10-15 at 7 16 45 AM" src="https://user-images.githubusercontent.com/17605945/137511741-aa256624-d225-46c7-94ca-dd55ccb199ef.png">

**Comment by lin-fred** [comment]
It is also back for me

**Comment by mkoo** [comment]
OK for me in Berkeley....
