### ISSUE TITLE
rebuild create container

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4010]
There is column in the create container template

PARENT_INSTALL_DATE

for which there is no direction on the [tool page](https://arctos.database.museum/CreateContainersForBarcodes.cfm)

Whatsitdo?

**Comment by campmlc** [comment]
I usually ignore it. Before my time.

**Comment by Jegelewicz** [comment]
Discussed at the object tracking meeting today - can we get this done?

**Comment by dustymc** [comment]
prioritizing - easier to rebuild this than to work out permissions on the old form

**Comment by dustymc** [comment]
Building with kludgy expensive check because https://github.com/ArctosDB/arctos/issues/1747 - revisit this to remove if we can elevate barcode checking to a rule.
