### ISSUE TITLE
Arctos dropping my login?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4012]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
In the middle of data entry for a single record. All is going well until I select a scientific name, then I get 

An error occurred while processing this page!
Message: FATAL: password authentication failed for user "jegelewicz"
Detail:
Check the Arctos Handbook for more information on errors.

This message has been logged as 2D4E980C-AF90-47A3-9DB2FC543B284E2A Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue. 

**To Reproduce**
1. Go to Data entry, start a new catalog record - https://arctos.database.museum/enter_data.cfm?guid_prefix=UNM:MET
2. enter accession and cat num
3. Enter scientific name

**Expected behavior**
The name I chose to appear and move on to next field - or get "that name isn't in Arctos"

**Screenshots**

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by dustymc** [comment]
Arctos was getting hammered by some Swiss server, not a situation for which I have a real-time solution.
