### ISSUE TITLE
Opinions on CT Loans (or any digital media loan really...)?

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#4014]
I am creating some data loans in Arctos for recently requested CT scan downloads for media hosted in MorphoSource. Though MS handles all the approvals and downloading, I want to create data loans in Arctos to track usage/projects/resulting pubs. 

As things stand at the moment, if I were to add items to a loan, I do not have a way to specifically point to the CT scan since it is not a part. 

Potential options:

1. Request new code table value for preservation = media so that I can add a part '**whole organism (media)**', with part_attribute_remark '**CT scan**' . This however would mean that all my records have a bit of duplication since they already have attached media (URLs linked to MS), and adding a CT scan part would be replicating this information. It also means preparing two bulkloaders (media_metadata and parts for every specimen scanned on our project).
2.  Figure out a way to add media records to loans via 'add items' [this feels the most appealing option to me]
3.  Taking other ideas...

@dustymc @jldunnum @atrox10 or any other folks working on media loans - any ideas? How have you documented CT loans? (I of course can just add my whole organism parts but it would be nice to indicate the specific thing being loaned...).

**Comment by dustymc** [comment]
(1) but with https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecpart_attribute_type#representation is what we'd talked about previously. I don't think it's duplication, just being specific - but AFAIK this hasn't been used and it's often difficult to entirely grasp the situation without seeing it in action, so maybe. That would involve one more load, but maybe there's some magic around that too.

(2) would take some work, but doesn't seem technically implausible. This would be a weaker linkage between the loan and the catalog record - the Media would be on loan, nothing would or could prevent removing the link between it and the catalog record. I think that's probably wrong - users care about the critter, not the "representation" (same way most people who borrow liver don't much care about liver, it's just a proxy to the critter) which suggests this may not be an appropriate arrangement.

There might be an undiscovered (3) out there somewhere - neither of the above seems quite as obvious as they could be.

**Comment by dustymc** [comment]
>"Skull (media)", and perhaps "skeleton, post cranial (media)", and "baculum (media)",.........

Yes, that's what https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecpart_attribute_type#representation does.

**Comment by ebraker** [comment]
Thanks @dusty. Yes, (1) would be the representation route (left that piece out of my comment)...I think we still need preservation = 'media' to make it happen, so we can confirm this at the code table admin meeting this week. Also your points to (2) are taken and make sense.

@jldunnum good point.... parts can get a bit gnarly (but I guess that is inevitable/inherent to the process of doing all these value-add products). Thanks!

**Comment by Jegelewicz** [comment]
> "Skull (media)", and perhaps "skeleton, post cranial (media)", and "baculum (media)",.........

We don't do that anymore. Part would be skull and the stuff in parenthesis is a part attribute of some sort.

**Comment by ebraker** [comment]
@Jegelewicz that works. I thought we' had talked about a 'media' value for preservation but we probably threw it out after some discussion ...

**Comment by campmlc** [comment]
I very much support tracking loans through parts. A CT image is essentially
a child part of the whole organism, made when the whole organism was itself
loaned. But regardless, using parts allows us to track how many times an
image or it's child derivative was loaned. This would also enable linking
pubs to parts as was previously discussed.

**Comment by dustymc** [comment]
>flexibility

From a user's perspective, "flexibility" is generally expressed as an inability to find relevant data. Some will search for media parts, some will search for representation parts, few/none will do both. 

@ccicero IIRC the representation attribute was for you, can we somehow reconcile this? @jegelewicz the CT says you made this, but I'm not sure I understand the definition and [Include the GitHub discussion link/URL in the definition.](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html#ctcoll_other_id_type) didn't happen so ???

**Comment by dustymc** [comment]
Merging with https://github.com/ArctosDB/arctos/discussions/5378 - I think the options are

1. Clearly articulate what needs done, come up with some structure that can do that, or
2. Do something that can never be entirely justified and hope it doesn't find a way to bite you
