### ISSUE TITLE
bulkloader assistance

### ISSUE THREAD

**Issue by SerinaBrady** [ArctosDB/arctos#4015]
May I please use the bulkloader?

** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **

** Outages should be reported to the contacts listed at https://arctosdb.org/arctos-down/ **

** Arctos Documentation is http://handbook.arctosdb.org/ **

** Learn more about Arctos at https://arctosdb.org/ **

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **

**Comment by Jegelewicz** [comment]
Nobody is in there as far as I can tell....
