### ISSUE TITLE
Free the Bulkloader

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4017]
You can summon the collection people via the collection contacts.

<img width="728" alt="Screen Shot 2021-10-18 at 3 43 33 PM" src="https://user-images.githubusercontent.com/5720791/137816405-524d10fa-fb78-4dd1-9323-598bb7b20dae.png">

@mkoo @ccicero

_Originally posted by @dustymc in https://github.com/ArctosDB/arctos/issues/4015#issuecomment-946225234_

When your data has issues and you download it to correct them, there is no easy path to clear it from the bulkloader.

![image](https://user-images.githubusercontent.com/5725767/137925254-0301c736-883b-4fe3-b4c4-9610b78b0dfb.png)

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/3927
