### ISSUE TITLE
part cleanup: misplaced condition

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4022]
Split from https://github.com/ArctosDB/arctos/issues/3708.

This issue addresses parts which have embedded condition information, and should not.

Please reply if I **should not** proceed with this. Lacking negative comments, I'll make the update ~2021-10-27.

Here is CSV of all data I'd like to change:

[temp_part_to_clean_condition.csv.zip](https://github.com/ArctosDB/arctos/files/7383187/temp_part_to_clean_condition.csv.zip)

Here is the data summary and my intended migration path. Columns are:

* part_name: existing part name
* new_part_name: what I will update the part name to
* new_condition_prefix: what I will prepend to condition, eg, ``sectioned; {whatever was already there}``
* new_part_remark_suffix: what I will append to part remark, eg ``{whatever was already there}; Original part name: carapace, sectioned`` 

```

         part_name          | new_part_name  | new_condition_prefix |             new_part_remark_suffix             
----------------------------+----------------+----------------------+------------------------------------------------
 carapace, sectioned        | carapace       | sectioned            | Original part name: carapace, sectioned
 carcass, dissected         | carcass        | dissected            | Original part name: carcass, dissected
 carcass, headless          | carcass        | headless             | Original part name: carcass, headless
 carcass, skinned           | carcass        | skinned              | Original part name: carcass, skinned
 femur, sectioned           | femur          | sectioned            | Original part name: femur, sectioned
 humerus, sectioned         | humerus        | sectioned            | Original part name: humerus, sectioned
 skeleton, partial          | skeleton       | partial              | Original part name: skeleton, partial
 testis, sectioned          | testis         | sectioned            | Original part name: testis, sectioned
 tooth, sectioned           | tooth          | sectioned            | Original part name: tooth, sectioned
 whole organism, dissected  | whole organism | dissected            | Original part name: whole organism, dissected
 whole organism, partial    | whole organism | partial              | Original part name: whole organism, partial
 whole organism, skinned    | whole organism | skinned              | Original part name: whole organism, skinned
 whole organism, skull-less | whole organism | skull-less           | Original part name: whole organism, skull-less

```

These are the affected collections:

```

 guid_prefix | nrecs 
-------------+-------
 ASNHC:Bird  |    11
 ASNHC:Mamm  |   105
 CHAS:Bird   |    10
 CHAS:Fish   |     1
 CHAS:Herp   |     1
 CHAS:Mamm   |     2
 CHAS:Teach  |    51
 DGR:Mamm    |     1
 DMNS:Bird   |  1538
 DMNS:Mamm   |  2484
 DMNS:Para   |     8
 MSB:Bird    |  4755
 MSB:Mamm    |  5763
 MSB:Para    |   222
 MVZ:Bird    |   198
 MVZ:Herp    |    22
 MVZ:Mamm    |  3236
 NMMNH:Bird  |    24
 NMMNH:Mamm  |   218
 OWU:Mamm    |     1
 UAM:Bird    |    27
 UAM:Mamm    |  3667
 UCM:Bird    |    35
 UCM:Herp    |     1
 UCM:Mamm    |    47
 UCSC:Bird   |     1
 UCSC:Mamm   |     3
 UMNH:Bird   |     1
 UMNH:Mamm   |    49
 UMZM:Bird   |   256
 UMZM:Mamm   |    13
 UTEP:Bird   |     7
 UTEP:Herp   |     1
 UTEP:Teach  |    14
 UWBM:Mamm   |   271
 UWYMV:Bird  |    18
 UWYMV:Mamm  |    73

```

These are involved data quality contacts with a github address:

(Edit: some intially tagged users are not involved - sorry!)

 @ebraker
 @mkoo
 @campmlc
 @ccicero
 @amgunderson
 @atrox10
 @mvzhuang
 @cjconroy
 @acdoll
 @jldunnum
 @jrdemboski
 @msbparasites
 @ewommack
 @diannakrejsa
 @kderieg322079
 @catherpes,@catherpes
 @lin-fred
 @droberts49

SQL is in https://github.com/ArctosDB/PG_DDL/blob/master/migration/PartCleanupCrusade.sql

**Comment by ewommack** [comment]
@dustymc out of curiosity could I get the UWYMV:Mamms that have these parts please? I think the change should be ok, but I'd just like to double check.

**Comment by dustymc** [comment]
@ewommack it's in the "CSV of all data I'd like to change" attachment above, and here it is by itself:
[temp_part_to_clean_condition_UWYMVMamm.csv.zip](https://github.com/ArctosDB/arctos/files/7383344/temp_part_to_clean_condition_UWYMVMamm.csv.zip)

-----------------

@DerekSikes @itzuecs please update your GitHub address in Arctos.
