### ISSUE TITLE
Code Table Request - new part name

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4024]
**Goal**

Discombobulate parts

**Context**

Need new "bare" part name

**Table**

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name

**Value**

swab

**Definition**

An absorbent device. Should be accompanied by part attribute(s) specifying where and how the swab was used.

**Collection type**

 Fish
 Mamm
 Bird
 Herp

**Priority**
critical; will block part cleanup

**Comment by Jegelewicz** [comment]
I am in favor.
