### ISSUE TITLE
Proposal: Issue Cleanup

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4029]
As ever-so-briefly discussed in today's CT meeting, we have way too many Issues open, that makes it difficult to find things, so we create more issues instead of commenting and etc etc etc.

I tentatively propose we close the following.

All [tabled](https://github.com/ArctosDB/arctos/milestone/7) Issues (they're not going anywhere, just getting a different state, we can re-open if necessary)

All [Announcement](https://github.com/ArctosDB/arctos/milestone/9) issues (auto-close would be nice for these)

All [Needs Documentation](https://github.com/ArctosDB/arctos/milestone/15) issues (unless we have some plan for actually writing documentation!)

All [older 'need more information' ](https://github.com/ArctosDB/arctos/issues?q=is%3Aissue+is%3Aopen+updated%3A%3C%3D2020-01-01+milestone%3A%22Need+More+Information%22)issues, and all ['requires user action' that haven't been updated this year](https://github.com/ArctosDB/arctos/issues?q=is%3Aissue+is%3Aopen+updated%3A%3C%3D2021-01-01+milestone%3A%22Requires+User+Action%22+) (apparently wasn't a problem after all?)

Better ideas - those involving fewer stagnant Issues, anyway - greatly appreciated. HELP!

**Comment by Jegelewicz** [comment]
I think this would be a good kickoff to our issues meeting on November 4. I also think that we might consider moving some things to "discussions" until they are ready for a more formal change in the Arctos code. For example - a broad discussion about object tracking and creating a plan could happen in discussion, then action items to implement that plan can generate issues here.

**Comment by dustymc** [comment]
I don't think I understand how more scatter could help, but I'm up for about anything. 

"Actionable" issues could be kicked over to https://github.com/ArctosDB/PG/issues if that somehow turns out to be useful.

**Comment by mkoo** [comment]
Alternative proposals:
All [tabled](https://github.com/ArctosDB/arctos/milestone/7) Issues (they're not going anywhere, just getting a different state, we can re-open if necessary)
 - close most of these; enhancements can go in future proposals?

All [Announcement](https://github.com/ArctosDB/arctos/milestone/9) issues (auto-close would be nice for these)
 - close most of these; some are worth tracking but should be in internal repo where we can tag/track appropriately

All [Needs Documentation](https://github.com/ArctosDB/arctos/milestone/15) issues (unless we have some plan for actually writing documentation!)
 - do we need a separate repo for all the documentation updates? (I mean we have the handbook repo for that actually) Some dedicated work is needed here and I almost want to see if we can fundraise for parttime help for this or something to make sure it gets done... open for AWG discussion

All [older 'need more information' ](https://github.com/ArctosDB/arctos/issues?q=is%3Aissue+is%3Aopen+updated%3A%3C%3D2020-01-01+milestone%3A%22Need+More+Information%22)issues, and all ['requires user action' that haven't been updated this year](https://github.com/ArctosDB/arctos/issues?q=is%3Aissue+is%3Aopen+updated%3A%3C%3D2021-01-01+milestone%3A%22Requires+User+Action%22+) (apparently wasn't a problem after all?)
- a lot of these can be closed or transferred; I can sort through these so useful to have these listed like this.
- does not github have some new tools for stale issues?

**Comment by mkoo** [comment]
Issues meeting 2/3/2022: agreed to have me review and close above issues as outlined.

Work on plan with officers to pay someone to focus on documentation of the handbook. Which may still include AWG members having scheduled work hour and training on how best to update documentation. This should be a high priority for the next 2 years. Still open for suggestions!
