### ISSUE TITLE
Code Table Request - New attribute: individual count

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4032]
**Goal**
Accurately describe the number of individuals that participated in an occurrence per [dwc:individualCount](https://dwc.tdwg.org/terms/#dwc:individualCount) in order to pass appropriate information to aggregators.

**Context**
https://github.com/ArctosDB/arctos/issues/3908#issuecomment-949698521

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type

**Value**
individual count

**Definition**
The number of individuals represented by this catalog record.

**Attribute data type**
number+units

**Attribute value**
integers

**Attribute units**
[individuals](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcount_units#individuals)

**Priority**
[  Please choose a priority-label to the right.  ]

**Comment by dustymc** [comment]
>If you have 20 lots with a different number of individuals from the same event then they all participated in the event and adding one count of individuals that is the sum of all the lot counts to that event should suffice?

That is not reflective of how the data are structured.

**Comment by campmlc** [comment]
@dustymc is there a solution you can suggest? We do need this resolved.

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/4032#issuecomment-949750557

>catalog record attribute

**Comment by mkoo** [comment]
conceptually count doesnt belong in the collecting event-- I agree with Dusty that it is a attribute of the cataloged record. 

If it's not getting passed on in the DwCA, then that's a mapping issue, not a CT or new thing for collecting event (which is location+date:time)

**Comment by Jegelewicz** [comment]
> If it's not getting passed on in the DwCA, then that's a mapping issue

We don't actually record this in a meaningful way anywhere, "part lot count" is not a usable value since we may have 3 parts from a single individual in a given catalog record.

> conceptually count doesn't belong in the collecting event

Probably not - since multiple taxa can share a collection event, but it also does not belong as part of the catalog record either. The individual count expected at the aggregators is "The number of individuals present at the time of the Occurrence." What we are passing as "occurrences" are actually "specimen" events (please see https://github.com/ArctosDB/arctos/issues/4036 because our terminology is all over the place and is also problematic). As discussed recently, using "specimen" events as an occurrence is problematic because we end up reporting two occurrences when there is only one. Here is an example:

https://arctos.database.museum/guid/DMNS:Mamm:12344
is from the same individual/collection event as
https://arctos.database.museum/guid/MSB:Mamm:233616

BUT they are passed to the aggregators as separate events/individuals

https://www.gbif.org/occurrence/1145096812
and
https://www.gbif.org/occurrence/1145267756

Careful consideration of associated occurrences and organism ID will suss this out, but it is a shame that we pass different organism IDs for each of these records. Even if we cleaned up our act and got them into the same collecting event, we would still be sending conflicting information.

Anyhoo. It is probably true that we have no good way to say how many individuals of a particular taxon took part in any given OCCURRENCE (collecting or observation event). Ideas are welcome because sending 1 when there are 276 is a bit misleading.

**Comment by dustymc** [comment]
>We don't actually record this in a meaningful way anywhere,

Correct - I magic it (poorly, probably) for some special circumstances, and there's some legacy not-quite-data from previous attempts of that hanging around. If we want to pass something meaningful on then we need to record it. (And I can magic - probably still poorly! - the initial values if needed.)

>What we are passing as "occurrences" are actually "specimen" events

No, we are splitting catalog records at collecting events in an attempt to magick Occurrences out of the aether. What we are passing as Occurrences does not exist in Arctos; that's just not what gets cataloged.

**Comment by Jegelewicz** [comment]
> What we are passing as Occurrences does not exist in Arctos; that's just not what gets cataloged.

Mostly - but I think some records with observation type events are pretty close.

> we are splitting catalog records at collecting events

I think we are splitting them at "specimen" events - thus the seid?

Honestly the quoted statement is true for all physical collections in the data aggregators, but after looking at this, I do think there are some things we could be doing better. 

So I guess I can go along with making this a collection object attribute even though it isn't really going to solve the whole problem.

**Comment by dustymc** [comment]
>some records ... are pretty close.

Most are.

> them at "specimen" events 

Same thing from the perspective of a single catalog record.

>think there are some things we could be doing better

Always.

> isn't really going to solve the whole problem

Nope, there are some ragged edges, but I think it does what the collections who seem to care about this want done without adding too much complexity or being too hard to understand in a decade or so.

>The number of individuals represented by this catalog record.

That doesn't seem quite right, or complete, or something, but I'm struggling to come up with anything better. @sharpphyl help??

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I fully support adding this as a collection object attribute. Is there some way we can represent count = unknown in a way that GBIF would ingest correctly?

**Comment by Jegelewicz** [comment]
@dustymc how does "INDIVIDUALCOUNT" get calculated?

```
INDIVIDUALCOUNT   individualCount,
```

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/3901

**Comment by Jegelewicz** [comment]
OK - so we basically pass 1 for everything except Fish collections?

**Comment by dustymc** [comment]
No, I'm not sure where you're seeing that? (And this issue exists because whatever we're doing doesn't work so I'm not sure why it matters?)

**Comment by campmlc** [comment]
MSB Para has lot count, and I use this field; default value of unknown = 1,
but that's not great. I would hope we are passing values to GBIF if they
differ from 1.

**Comment by Jegelewicz** [comment]
> I'm not sure where you're seeing that?

So All I know is this:

```
for fish, INDIVIDUALCOUNT is sum of select part's lot count
    update flat set (INDIVIDUALCOUNT)=(
    select 
        sum(lot_count) 
    from 
        specimen_part 
        inner join coll_object on specimen_part.collection_object_id=coll_object.collection_object_id
    where 
        part_name like '%whole%' and
        coll_obj_disposition  not in ('discarded','used up','deaccessioned','missing','transfer of custody') and
     specimen_part.derived_from_cat_item=cid
    ) where collection_cde='Fish' and collection_object_id=cid;
    ```

What do we do for everything else?

**Comment by sharpphyl** [comment]
> I'm struggling to come up with anything better. @sharpphyl help??

I know our records and individual counts are quite simple in comparison to other collections.  For us the number of individuals in the catalog record and the number of individuals in the collecting event are the same.  Some records do have multiple parts (shell and opercula) and each part is entered in Parts and the count in Qty.  For our purposes, the location of a new attribute for the number of individuals represented in the record could be part of the occurrence or the catalog record as long as it maps to dwc:individualCount in GBIF and other aggregators.  

Am I answering the right question, @dustymc ?

**Comment by dustymc** [comment]
I'm looking for an Arctos definition - "The number of individuals represented by this catalog record." is the current winner yet seems somehow lacking.

>For us the number of individuals in the catalog record and the number of individuals in the collecting event are the same. 

[Nope](https://arctos.database.museum/place.cfm?action=detail&collecting_event_id=10670691)....

>part of the occurrence 

For the sake of clarity: There is no such thing in Arctos.

**Comment by Jegelewicz** [comment]
I think that the number of individuals represented by this catalog record is the only defensible definition if this is a catalog record attribute.

**Comment by dustymc** [comment]
>only defensible definition 

But that's not at all in line with the DWC definition ("there were 10,000 individuals present at the time of the Occurrence, we caught three"), nor what the only user of this in Arctos has done ("...and two of those have since been used up, so 1").

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#abundance seems to fit the DWC idea, but DWC sees to want an incompatible datatype.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I like the suggestion in the tdwg thread to use organism quantity and quantity type. [https://dwc.tdwg.org/list/#dwc_organismQuantity](https://dwc.tdwg.org/list/#dwc_organismQuantity)

**Comment by Jegelewicz** [comment]
@Nicole-Ridgwell-NMMNHS I have been searching all over for that comment! How would you suggest we implement the organism/type thing?

**Comment by Jegelewicz** [comment]
Also leaving the link to the comment here - https://github.com/tdwg/dwc/issues/285#issuecomment-965733231

**Comment by Jegelewicz** [comment]
Also, for some reason the links to the main DwC site never seem to work - so here for reference

https://dwc.tdwg.org/terms/#dwc:organismQuantity

> A number or enumeration value for the quantity of organisms.

https://dwc.tdwg.org/terms/#dwc:organismQuantityType

> The type of quantification system used for the quantity of organisms.

Examples: 27 (organismQuantity) with individuals (organismQuantityType). 12.5 (organismQuantity) with %biomass (organismQuantityType). r (organismQuantity) with BraunBlanquetScale (organismQuantityType).

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
If organism quantity is added as a specimen attribute, could we map quantity type to attribute units and create a new units table?

**Comment by Jegelewicz** [comment]
And attribute remark could help differentiate when the identification on a record is A and B.

**Comment by Jegelewicz** [comment]
I was looking at changing this issue or creating a new one, but I feel like what we have here is fine, except instead of passing the value in this term to ```dwc:individualCount```, we would pass it to ```dwc:organismQuantity``` and we would pass the units value to ```dwc:organismQuantityType```

Does this sound like a good solution?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
If we want to call it individual count, would we default the units value to individuals?

Organism quantity seems like a more flexible term - do we need that flexibility or are things like %biomass covered by other attributes?

**Comment by dustymc** [comment]
>new units table

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcount_units

>default

Nothing currently has a default, but "just UI" (ish, probably).

>other attributes

https://github.com/ArctosDB/arctos/issues/4032#issuecomment-965381448 - if those aren't the same, the definitions would need to reflect the differences.

**Comment by sharpphyl** [comment]
> instead of passing the value in this term to dwc:individualCount, we would pass it to dwc:organismQuantity and we would pass the units value to dwc:organismQuantityType

I'm not sure what the difference is between individual count and organism quantity, but if that solves the problem for our invert collection and makes sense for everyone else, I'm fine with it.  Thanks!

**Comment by sharpphyl** [comment]
> I think that the number of individuals represented by this catalog record is the only defensible definition if this is a catalog record attribute.

Yes, we have no idea how many other individuals were present at the collecting event.  We only know how many (shells) were collected for our catalog record.

> instead of passing the value in this term to dwc:individualCount, we would pass it to dwc:organismQuantity and we would pass the units value to dwc:organismQuantityType

Is this something that can be done for an individual (probably invertebrate) collection or are we waiting for AWG approval or an update or something else?  I'd like to take action so that the number of organisms represented in our catalog records (and recorded under Qty) shows up in GBIF instead of always being 1.

What do we need to do to keep this issue moving forward?

**Comment by dustymc** [comment]
>keep this issue moving forward

Just a focused discussion of how to store the data. Here's a shot, mostly copy-pasta of the edited original, please edit/replace/whatever as necessary.

Goal
Record number of individuals cataloged.

Context
#3908 (comment)

Table
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type

Value
individual count

Definition
The number of individuals represented by the catalog record.

Attribute data type
number+units

Attribute value
integers

Attribute units
[ctcount_units](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcount_units)

(Then, we can talk about DWC Mapping, but we should also make sure the data we set up are compatible with the target so a little chicken-n-eggy, I'm still thinking https://dwc.tdwg.org/terms/#dwc:individualCount.)

**Comment by sharpphyl** [comment]
@dustymc   So you would add [ctcount_units](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcount_units) as an attribute in the code table [code table attribute_type](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type&coln=Inv) for Inv and other collections as needed.  For example, we would enter 5 as the Attribute value and select "individuals" as the Attribute units.   

Would you be able to magic our current number in the Qty field into this new attribute?

As for the DWC mapping, my only concern is that it map to GBIF and iDigBio "Individual Count" which is the field that currently always shows 1.

Sounds good for our collection.

**Comment by sharpphyl** [comment]
@Jegelewicz   Will the Code Table Committee be able to take up this topic at their next meeting?

> Table
> https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type
> 
> Value
> individual count
> 
> Definition
> The number of individuals represented by the catalog record.
> 
> Attribute data type
> number+units
> 
> Attribute value
> integers
> 
> Attribute units
> [ctcount_units](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcount_units)

**Comment by Jegelewicz** [comment]
Definition
The number of individual organisms represented by the catalog record.

**Comment by Jegelewicz** [comment]
Above from AWG Issues meeting. Are we ready to add this with the definition above or is there still "lot" confusion? @acdoll @mkoo @sharpphyl @ccicero @campmlc

**Comment by acdoll** [comment]
Sounds good to me.

**Comment by Jegelewicz** [comment]
Code Table Committee says add!

**Comment by Jegelewicz** [comment]
Need to map to individualCount for aggregators.

**Comment by Jegelewicz** [comment]
Added to code table.

**Comment by Jegelewicz** [comment]
Added ctcount_units

**Comment by dustymc** [comment]
This should be caching properly, and filtering out to things that use the cache, now. 

Weird data - eg, multiple determinations - will break the cache, so there's a status on /guid/ pages in next release.

<img width="268" alt="Screen Shot 2022-02-17 at 3 47 06 PM" src="https://user-images.githubusercontent.com/5720791/154590607-1116490e-0a46-4452-ae84-830626a66e15.png">

The cache is just pulling the attribute values, so using anything other than 'individuals' for units, or any non-integer value with any units, will also do something interestingly fatal.


There is no default; not providing this attribute will result in individualcount=NULL being send out with DWC.

I can help bulkload initial data if necessary, just let me know how to calculate this.

@sharpphyl your collection had nothing, if you'll let me know how to get the initial values I can magic them in.

For collection_cde=Ento collections, the old code was using `` max(lot_count)``


 @mlbowser
 @leet1984
 @campmlc
 @dssikes
 @mvzhuang
 @wellerjes
 @terrymcglynn
 @lin-fred
 @Jegelewicz
 @droberts49
 @jrpletch
 @lmtabak



For collection_cde=Fish collections, the old code was using 
```
 sum(lot_count) 
      where 
        part_name like '%whole%' and
        coll_obj_disposition  not in ('discarded','used up','deaccessioned','missing','transfer of custody') 
```


 @ebraker
 @byuherpetology
 @leet1984
 @mkoo
 @ewommack
 @campmlc
 @ccicero
 @mvzhuang
 @wellerjes
 @lin-fred
 @Jegelewicz
 @gradyjt
 @jandreslopez
 @droberts49
 @zmsch
 @jrpletch
 @lmtabak

**Comment by sharpphyl** [comment]
> @sharpphyl your collection had nothing, if you'll let me know how to get the initial values I can magic them in.

The number of individuals in a catalog record for DMNS:Inv is in the field Qty under Parts.  

<img width="522" alt="Catalog Record Count" src="https://user-images.githubusercontent.com/15368365/154708754-56864fdc-f332-42de-8932-dcc44962f815.png">

If a record has both a shell and an operculum, each part will appear separately but the number of individuals doesn't increase.

<img width="841" alt="Screen Shot 2022-02-18 at 8 11 54 AM" src="https://user-images.githubusercontent.com/15368365/154709346-5217ad43-a3f8-4007-82b0-bcb4ffea11f9.png">

Thanks for magicing them in. 

Is this where we add the individual count attribute for each record? 

<img width="985" alt="Screen Shot 2022-02-18 at 8 16 59 AM" src="https://user-images.githubusercontent.com/15368365/154710289-68935388-d615-41bf-8adc-1067d2ee99a1.png">

I think we still add the count in the Qty field too so it shows as a "shell" or other part.  Does that mess up anything?

**Comment by dustymc** [comment]
@sharpphyl I think that means you want sum(lot_count) - 1 in your first screenshot, 2 in the second?

You should definitely continue to provide [lot count](https://handbook.arctosdb.org/documentation/parts.html#lot-count) - it's a completely different thing (and much more important, in my view).

Yep that's one place to edit Attributes.

@Jegelewicz the frontmatter on the parts doc page seems to be mangled and it's claiming you edited - fix?

**Comment by lin-fred** [comment]
Thanks all for updating this. We don't have a good inventory yet of our specimens, it's all legacy numbers at the moment. I will keep this in mind for when we do an inventory!

**Comment by dustymc** [comment]
@sharpphyl some data for your review:

```

create table temp_dmnsinvic as select
    guid,
    'individual count' as attribute,
    sum(lot_count)::text as attribute_value,
    'individuals' as attribute_units,
    'Phyllis Sharp' as determiner
from
    flat
    inner join specimen_part on flat.collection_object_id=specimen_part.derived_from_cat_item
    inner join coll_object on specimen_part.collection_object_id=coll_object.collection_object_id
where
    flat.guid_prefix='DMNS:Inv'
group by
    guid
;

```

[temp_dmnsinvic.csv.zip](https://github.com/ArctosDB/arctos/files/8098522/temp_dmnsinvic.csv.zip)

Let me know if it is as expected.

**Comment by sharpphyl** [comment]
> @sharpphyl I think that means you want sum(lot_count) - 1 in your first screenshot, 2 in the second?

No, both of these records have only one organism.  The first has only the shell and the second has both the shell and its operculum.  There may be a few records where these aren't the same Qty, but I can adjust them manually.  So if they are the same, that's the number of individuals in the record.

I looked at your csv and see specimens (e.g. https://arctos.database.museum/guid/DMNS:Inv:25570) that show 2 organisms but there should only be one.  Perhaps we should only count the number of shells if there is both a shell and an operculum and they have the same Qty.  

If the part name is exoskeleton, test or whole organism there usually isn't more than one part name in the record but I'll check a few to confirm that.

**Comment by Jegelewicz** [comment]
No sidenav thingee where?

**Comment by dustymc** [comment]
https://handbook.arctosdb.org/documentation/parts.html

**Comment by sharpphyl** [comment]
Let's see if this helps.  

Rule 1 - if there is only one part, use the value in Part Qty
Rule 2 - if there is a shell and an operculum, use the value in Part Qty for "shell" as the default.  Do not add the operculum Qty.
Rule 3 - sum certain part Qty values as listed below

shell - use Qty
test - use Qty
exoskeleton - use Qty
egg case - use Qty
egg - I changed this to egg case
whole organism - use Qty
operculum - use Qty 

operculum|shell - use the shell Qty only
operculum|shell|shell - sum the shell Qtys only
operculum|shell|whole organism - sum the shell and whole organism Qtys only
egg case|operculum|shell - sum the egg case and shell Qtys only

shell|whole organism - sum the Qtys 
shell|shell - sum the Qtys
test|whole organism - sum the Qtys 
shell|test - sum the Qtys
exoskeleton|shell - sum the Qtys
egg case|shell - sum the Qtys

**Comment by campmlc** [comment]
Apologies for not being able to follow this more closely and coming in with
a stupid question, but I thought that individual count could be a field to
use to record all the individuals in a lot, regardless of number of parts?
And ideally could be used for other taxa, eg fish, tadpoles, parasites?

**Comment by dustymc** [comment]
@sharpphyl how's this?

[temp_dmnsinvic.csv.zip](https://github.com/ArctosDB/arctos/files/8102720/temp_dmnsinvic.csv.zip)

**Comment by sharpphyl** [comment]
I corrected the organism count on five odd records that didn't fit my "rules."  Highlighted in yellow.  I also added 10 records at the very bottom uploaded since you ran this report.  If it looks ok to you, let's do it.  

[temp_dmnsinvic-2 - PMS edits.csv](https://github.com/ArctosDB/arctos/files/8104646/temp_dmnsinvic-2.-.PMS.edits.csv)

Thanks for making magic.

**Comment by Jegelewicz** [comment]
> I thought that individual count could be a field to use to record all the individuals in a lot, regardless of number of parts?
> And ideally could be used for other taxa, eg fish, tadpoles, parasites?

That's exactly what it is.

**Comment by leet1984** [comment]
HI Teresa,

Attached is the mammal catalog.  I am sending it to you because of the
misnaming of ACUNHC 1.

All the best
Tom
