### ISSUE TITLE
event terminology

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4036]
But I think this has always been a problem what exactly does specimen/event remark mean? It has never been clear.

Anyway, change this to "Collection Object Remark" to match data entry

![image](https://user-images.githubusercontent.com/5725767/138731748-8b72cd11-26b1-402d-bb89-4cc9bf03ce7f.png)

Change this to "Verbatim Event Details" to match catalog record (but see below)

![image](https://user-images.githubusercontent.com/5725767/138732540-64250e7b-12a5-4f3d-87b0-92b429d46ceb.png)

Change this to "Verbatim Event Details" to match data entry

![image](https://user-images.githubusercontent.com/5725767/138733237-a0928177-3314-4792-ab31-ab7ca033e016.png)

Change this to "Catalog Record Event Remark" on the catalog record

![image](https://user-images.githubusercontent.com/5725767/138733516-5fbea57f-68c0-4a6a-9997-65062db93310.png)

Change this to "Catalog Record Event Remark" in data entry

![image](https://user-images.githubusercontent.com/5725767/138733733-c6cc077f-d840-4089-9a89-089f850931f2.png)

And also make appropriate changes to search. I can do all of this and let everyone see it in test.

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/arctos/issues/3691#issuecomment-951095270_

**Comment by Jegelewicz** [comment]
A revised summary

## Locality
Arctos   Page/What it does | Higher Geography | Locality Name | Locality ID | Specific Locality | Minimum Elevation | Maximum Elevation | Elevation Units | Minimum Depth | Maximum Depth | Depth Units | Locality Remark | Coordinate Units | Decimal Latitiude | Decimal Longitude | Maximum Coordinate Error | Coordinate Error Units | Datum | Georeference Source | Georeference Protocol | WKT Media ID | Locality Attribute | Locality Attribute Value | Locality Attribute Units | Locality Attribute Determiner | Locality Attribute Determined   Date | Locality Attribute Determined   Method | Locality Attribute Remark
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Edit catalog record | Higher Geography | Locality Nickname | N/A | Specific Locality | Min. Elev. | Max. Elev. | Elev. Unit | Min. Depth | Max. Depth | Depth Units | Locality Remarks | N/A | Decimal Latitude | Decimal Longitude | Max Error | Max Error Units | Datum | Georeference Source | Georeference Protocol | WKTMediaID | Type | Value | Units | Determiner | Date | Method | Remark
Catalog record | Higher Geography | Locality Nickname | N/A | Specific Locality | Elevation | (to) Elevation | Elevation | Depth | (to) Depth | Depth | Locality Remarks | N/A | Coordinates | Coordinates | Error | Error |   | Georeference Source | Georeference Protocol |   | Attribute | Value | Units | Determiner | Date | Method | Remark
Data entry (old) | Higher Geog | Locality Nickname | Existing LocalityID | Spec Locality | Elevation (min-max) between | Elevation (min-max) between | Elevation (min-max) between | Depth (min-max) between | Depth (min-max) between | Depth (min-max) between | LocalityRem | Original lat/long Units | Dec Lat | Dec Long | Max Error | Max Error | Datum | Georeference Source | Georeference Protocol | WKTMediaID | Type | Value | Unit | Determiner | Date | Method | Remark
Data entry (new) | Higher Geography | Locality Name | Locality ID | Specific Locality | Minimum Elevation | Maximum Elevation | Elevation Units | Minimum Depth | Maximum Depth | Depth Units | Locality Remarks | Coordinate Units | Dec Lat | Dec Long | Max Error | Max Error Units | Datum | Georeference Source | Georeference Protocol | WKTMediaID | locality_attribute_type | locality_attribute_value | locality_attribute_unit | locality_attribute_determiner | locality_attribute_detr_date | locality_attribute_detr_meth | locality_attribute_remark
Bulkloader builder | higher_geog | locality_name | locality_id | spec_locality | minimum_elevation | maximum_elevation | orig_elev_units | min_depth | max_depth | depth_units | locality_remarks | orig_lat_long_units | dec_lat | dec_long | max_error_distance | max_error_units | datum | georeference_source | georeference_protocol | wkt_media_id | locality_attribute_type | locality_attribute_value | locality_attribute_units | locality_attribute_determiner | locality_attribute_detr_date | locality_attribute_detr_meth | locality_attribute_remark
Bulkload specimen-events | higher_geog | locality_name | N/A | spec_locality | minimum_elevation | maximum_elevation | orig_elev_units | min_depth | max_depth | depth_units | locality_remarks | orig_lat_long_units | dec_lat | dec_long | max_error_distance | max_error_units | datum | georeference_source | georeference_protocol | wkt_media_id | N/A | N/A | N/A | N/A | N/A | N/A | N/A
Bulkload collecting events | higher_geog | N/A | N/A | spec_locality | minimum_elevation | maximum_elevation | orig_elev_units | min_depth | max_depth | depth_units | locality_remarks | N/A | dec_lat | dec_long | max_error_distance | max_error_units | datum | georeference_source | georeference_protocol | N/A | N/A | N/A | N/A | N/A | N/A | N/A | N/A
Bulkload locality | higher_geog | locality_name | N/A | spec_locality | minimum_elevation | maximum_elevation | orig_elev_units | min_depth | max_depth | depth_units | locality_remarks | N/A | dec_lat | dec_long | max_error_distance | max_error_units | datum | georeference_source | georeference_protocol | wkt_media_id | N/A | N/A | N/A | N/A | N/A | N/A | N/A
Bulkload locality attributes | N/A | locality_name | N/A | N/A | N/A | N/A | N/A | N/A | N/A | N/A | N/A | N/A | N/A | N/A | N/A | N/A | N/A | N/A | N/A | N/A | attribute_type | attribute_value | attribute_units | attribute_determiner | determined_date | determination_method | attribute_remark
Search | Continent/Ocean, Sea, Country,   State/Province, USGS Quad Map, County, Island Group, Island, Geographic   Feature, Drainage | N/A | N/A | Specific Locality | Elevation | Elevation | Elevation | N/A | N/A | N/A | Locality Remarks | N/A | N/A | N/A | Coordinate Precision | Coordinate Precision | N/A | Georeference Source | N/A | N/A | Locality Attribute 1 | Locality Attribute 1 Value | Locality Attribute 1 Unit | Locality Attribute 1 Determiner | N/A | Locality Attribute 1 Method | Locality Attribute 1 Remark

## Event
Arctos   Page/What it does | Verbatim Event Location | Verbatim Event Date | Formatted Event Start Date | Formatted Event End Date | Event Remark | Event Name | Verbatim Coordinates | Event Attribute Type | Event Attribute Value | Event Attribute Units | Event Attribute Determiner | Event Attribute Date | Event Attribute Method | Event Attribute Remark | Locality Name | Event ID | Locality ID
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Edit catalog record | Verbatim Locality | Verbatim Date | Began Date/Time | Ended Date/Time | Collecting Event Remark | Collecting Event Nickname | As-entered Coordinates | Event Attribute Type | Event Attribute Value | Event Attribute Units | Event Attribute Determiner | Event Attribute Date | Event Attribute Method | Event Attribute Remark | locality_name | N/A | N/A
Catalog record | Verbatim Locality | Verbatim Date | Event Date | Event Date (to) | Remark | Event Nickname | As Entered | Attribute | Value | included in value if applicable | Determiner | Date | Method | Remark | Locality Nickname | N/A | N/A
Data entry (old) | Verbatim Locality | VerbatimDate | Begin | End | CollEvntRemk | Event Nickname | Coordinates (event and locality) | N/A | N/A | N/A | N/A | N/A | N/A | N/A | Locality Nickname | Existing EventID | N/A
Data entry (new) | Verbatim Locality | Verbatim Date | Began Date | Ended Date | Collecting Event Remark | Event Name | all the coordinate stuff that is not decimal degrees | N/A | N/A | N/A | N/A | N/A | N/A | N/A | Locality Name | Event ID | Locality ID
Bulkloader builder | verbatim_locality | verbatim_date | began_date | ended_date | coll_event_remarks | collecting_event_name | all the coordinate stuff that is not decimal degrees | N/A | N/A | N/A | N/A | N/A | N/A | N/A | locality_name | collecting_event_id | locality_id
Bulkload specimen-events | verbatim_locality | verbatim_date | began_date | ended_date | coll_event_remarks | collecting_event_name | all the coordinate stuff that is not decimal degrees | N/A | N/A | N/A | N/A | N/A | N/A | N/A | locality_name | N/A | N/A
Bulkload collecting events | verbatim_locality | verbatim_date | began_date | ended_date | coll_event_remarks | collecting_event_name | N/A | N/A | N/A | N/A | N/A | N/A | N/A | N/A | locality_name | N/A | N/A
Bulkload collecting event attributes | N/A | N/A | N/A | N/A | N/A | event_name | N/A | event_attribute_type | event_attribute_value | event_attribute_units | event_determiner | event_determined_date | event_determination_method | event_attribute_remark | N/A | N/A | N/A
Search | Verbatim Locality | Verbatim Date | Collected On or After | Collected On or Before | Collecting Event Remark | Search | N/A | Event Attributes | N/A | N/A | N/A | N/A | N/A | N/A | N/A | N/A | N/A

## Event Assignment
Arctos   Page/What it does | Assigned Event Type | Event Assigned By | Event Assigned Date | Event Verification | Event Verified By | Event Verification Date | Event Assignment Remark | Event Habitat | Event Source | Event Method
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Edit catalog record | Specimen/Event Type | Event Determiner | Determined Date | Verification Status | Verified By | Verified Date | Specimen/Event Remark | Habitat | Collecting Source | Collecting Method
Catalog record | Event Type | Event Type: assigned by | Event Date | Event Verification: | Event Verification: verified by | Event Verification: on | Event Details: remark | Event Details: habitat | Event Details: Collecting Source | Event Details: collecting method
Data entry (old) | Specimen/Event Type | Event Determiner | Detr. Date | VerificationStatus | N/A | N/A | Specimen/Event Remark | Habitat | Coll. Src. | Coll. Meth.
Data entry (new) | Event Type | Event Determiner | Det. Date | VerificationStatus | N/A | N/A | Event Remark | Habitat | Collecting Source | Collecting Method
Bulkloader builder | specimen_event_type | event_assigned_by_agent | event_assigned_date | verificationstatus | N/A | N/A | specimen_event_remark | habitat | collecting_source | collecting_method
Bulkload specimen-events | specimen_event_type | assigned_by_agent | assigned_date | verificationstatus | N/A | N/A | specimen_event_remark | habitat | collecting_source | collecting_method
Search | Record/Event Type | N/A | N/A | Verification Status | N/A | N/A | Record/Event Remark | Habitat * in Locality | Collecting Source | Collecting Method
