### ISSUE TITLE
ACUNHC: Bird css style sheet - how do I get it to work?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4045]
@dustymc I added a style sheet for ACUNHC to make the text in their header appear white (like ALMNH), but it isn't working

![image](https://user-images.githubusercontent.com/5725767/138967011-22646a09-dab8-4911-926d-923cc58a9c2e.png)

![image](https://user-images.githubusercontent.com/5725767/138967055-8117a62b-03c6-40f2-a3a2-dedfedb92dcf.png)

What am I doing wrong?

**Comment by Jegelewicz** [comment]
@dustymc I'm back - can I get some help to make the stuff on the right hand side visible?

![image](https://user-images.githubusercontent.com/5725767/140216200-58b9a590-d216-4dfb-bca4-c3116f9e7177.png)

**Comment by dustymc** [comment]
```
#header-collection-data-cell{color:orange;}
#header-collection-data-cell a{color:red;}
#header-collection-data-cell a:visited{color:green;}
```
that or ??????

**Comment by Jegelewicz** [comment]
I had already added the stuff below to the style sheet, but it doesn't seem to change anything?

```
.header-collection-data-cell { color:white }

.headerCollectionLicenseText a:link { color:white }
.headerCollectionLicenseText a:visited { color:white; }
.headerCollectionLicenseText a:hover { color:gray}
.headerCollectionLicenseText a:active { color:white }
```

**Comment by dustymc** [comment]
You need ID selectors - those elements don't have a class.

**Comment by Jegelewicz** [comment]
So using the # like you suggested?

**Comment by Jegelewicz** [comment]
@dustymc I am getting super frustrated with this! Waiting for a pull to get a changed stylesheet means I forget where I left stuff.

But first off, why does this collection header look like this?
![image](https://user-images.githubusercontent.com/5725767/141857486-42fc68cd-03e1-45e5-85f9-379722bdf649.png)

When I have assigned a collection and institution name?
![image](https://user-images.githubusercontent.com/5725767/141857625-7a9ea97a-9983-4ccf-a599-b332851deda0.png)

**Comment by dustymc** [comment]
I pulled. You need access if you're going to be changing code.

>Your settings will be ignored if you don't include enough information.

And that's probably cached as well, I'm not sure at the moment.

**Comment by Jegelewicz** [comment]
> You need access if you're going to be changing code.

I used to have it then I didn't - is this all related to that?

August 13
Chris - can I use useradd tmayfiel to arctos-test, or do you need to do something magical with the TACC account (my one password suggests that's the case) or ???

Thx-D

> Yeah, that has to be a VM admin thing. I can ask to propagate that account, and any others you need, in a batch.

August 17

> Dusty,
> 
> For now - am I the only one in the batch?
> 

Teresa J. Mayfield-Meyer

> Yes.
> 
> Need anything else from us, Chris?

Thx-D

August 18

> I've submitted the request. If you ever want someone added AND given sudo permission just be sure to indicate that.
> 
> Thanks

Chris
