### ISSUE TITLE
part cleanup: skin

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4049]
EDIT: added cape, cheek pouch, ear clip

No longer among the low-hanging fruit, I have no idea what to do with most of these.  HELP!

If all else fails I suppose I'll propose tossing these at [preservation](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_preservation), which is OK (still not terribly informative) for "tanned" but doesn't seem entirely relevant for anything else. At least that will avoid being mixed in with https://github.com/ArctosDB/arctos/issues/3654, which must be some kind of improvement.

Documentation starts about https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#skin, but isn't very illuminating.

Here's everything:

[temp_part_to_clean_skin.csv.zip](https://github.com/ArctosDB/arctos/files/7429995/temp_part_to_clean_skin.csv.zip)

Skin-parts are:

```
 skin, body
 skin clip
 skin, flat
 skin, mounted
 skin, Power
 skin, shed
 skin, shmoo
 skin, study
 skin, tanned
cape
cheek pouch 
ear clip
 
```

Involved collections:
```

 guid_prefix | nrecs  
-------------+--------
 ACUNHC:Bird |     62
 ALMNH:Bird  |      6
 ALMNH:Mamm  |   1741
 ASNHC:Bird  |   2039
 ASNHC:Mamm  |  10842
 BYU:Herp    |      3
 CHAS:Bird   |   1688
 CHAS:Herp   |      8
 CHAS:Mamm   |   4410
 CHAS:Teach  |    194
 DMNS:Bird   |  32550
 DMNS:Herp   |      1
 DMNS:Mamm   |  10592
 HMCM:Bird   |    101
 HMCM:Herp   |      1
 HMCM:Mamm   |     14
 MLZ:Bird    |      6
 MLZ:Mamm    |     15
 MSB:Bird    |    890
 MSB:Herp    |      3
 MSB:Mamm    |   1885
 MVZ:Bird    | 171624
 MVZ:Herp    |   1532
 MVZ:Mamm    | 164267
 NMMNH:Bird  |     16
 NMMNH:Herp  |      1
 NMMNH:Mamm  |     86
 NMU:Bird    |    299
 NMU:Mamm    |    702
 OWU:Bird    |    530
 OWU:Mamm    |    127
 UAM:Bird    |    738
 UAM:Mamm    |    401
 UCM:Bird    |  11755
 UCM:Fish    |      3
 UCM:Herp    |     23
 UCM:Mamm    |  13136
 UCSC:Bird   |     18
 UCSC:Mamm   |    228
 UMNH:Bird   |    124
 UMNH:Herp   |      6
 UMNH:Mamm   |    285
 UMNH:Teach  |    169
 UMZM:Bird   |    105
 UMZM:Mamm   |    372
 UNR:Bird    |    174
 UNR:Mamm    |   2555
 UTEP:Bird   |   1776
 UTEP:Herp   |     40
 UTEP:Mamm   |      5
 UTEP:Teach  |     43
 UWBM:Herp   |      2
 UWBM:Mamm   |  23269
 UWYMV:Bird  |    308
 UWYMV:Mamm  |    232
```

 @ebraker
 @mkoo
 @campmlc
 @ccicero
 @amgunderson
 @atrox10
 @mvzhuang
 @cjconroy
 @jtgiermakowski
 @keg34
 @acdoll
 @jldunnum
 @jrdemboski
 @byuherpetology
 @leet1984
 @ewommack
 @diannakrejsa
 @kderieg322079
 @catherpes,@catherpes
 @lin-fred
 @droberts49

**Comment by dustymc** [comment]
Do we need to take smaller bites - is there anything in the list above which isn't controversial?

**Comment by cjconroy** [comment]
I am not sure of the solution, but having to use TWO fields for an extremely common part type for us (skin, study) adds work. Much like having to add preservation attribute frozen to nearly every part= tissue we add. Making data entry and management more complex, more prone to error, and more prone to being out of date should be part of the equation about what to change in the database.

**Comment by ewommack** [comment]
> is there anything in the list above which isn't controversial?

Have you met us? :D

**Comment by dustymc** [comment]
See https://github.com/ArctosDB/data-migration/issues/1141 - we are still making problematic ("skin, ...") parts, incoming collections should NOT get tossed into the middle of an old mess by way of introduction, if this is still hanging around when I get done with geography I'm going to do something radical.

HELP!!!

**Comment by campmlc** [comment]
We use skin clips and toe clips all the time as subsamples of study skins for DNA work. This goes to the ability to change the part name of a subsample so that it no longer matches the parent sample, whatever we use. We do need to be able to easily distinguish a parent study skin from a toe or skin clip subsample.
We also have ear clips which are usually from mark/recapture study, and consequently there is no parent skin voucher.
Here are MSB loans which have some parts designated as "clip" in them. 

[MSB_skin_clip_loans.zip](https://github.com/ArctosDB/arctos/files/9822819/MSB_skin_clip_loans.zip)

**Comment by dustymc** [comment]
I'm just trying to complete a very long discussion and resulting standardization process. Clean data can't possibly do anything other than make WHATEVER you have, HOWEVER it has been or might be used, more accessible to more people. This is a request for a simple cleanup, to turn part-and-other-stuff parts into simple, accessible, understandable parts, with the 'other stuff' properly filed with the other other stuff. That's it, easy-peasy....

**Comment by campmlc** [comment]
@catherpes @jldunnum

**Comment by Jegelewicz** [comment]
skin, body
 skin clip
 skin, flat
 skin, mounted
 skin, Power
 skin, shed
 skin, shmoo
 skin, study
 skin, tanned
cape
ear clip

@ArctosDB/arctos-code-table-administrators suggest add terms behind comma to preservation also clip and cape. Bring to AWG Issues.

**Comment by Jegelewicz** [comment]
Also need bulkloader modification to stop the shortcut for preparation (more columns). See #5193

**Comment by dustymc** [comment]
revisit after https://github.com/ArctosDB/arctos/issues/5193

**Comment by dustymc** [comment]
The block has been cleared, can we proceed with this?

**Comment by Jegelewicz** [comment]
I am totally on board, but should not be the final say. @ArctosDB/arctos-code-table-administrators ?

**Comment by ccicero** [comment]
If we simplify the various skin options to just 'skin' with the method (study, flat, tanned...) in preparation or preservation, then I agree with other comments that a) we need to made the preservation/preparation more prominent (something that would be more generally useful), 2) we need to make it easier for people to search on specific types of skins (e.g., only study skins; also, skin subsamples should be ignored in searches for 'skin'), 3) we need to make sure that the type of prep is part of the record in data aggregators, and 4) we need to make data entry as simple as possible so it's not extra work to add the prep type. 

I agree with @campmlc and @Jegelewicz that we should discuss this at a CT meeting. Unfortunately I'll miss the next one on 8/17 as I'll be flying to AK; I want to be there for the discussion as that is the bulk of our bird collection, so either we change the date of the meeting or postpone discussion until the Sept one.

**Comment by dustymc** [comment]
@ccicero that should be a separate Issue, and I don't think  it needs to block this.

>simplify

Normalize!

>skin subsamples should be ignored

No, Best Practices would mandate (some) skins be children of whole organisms (so they can inherit preservation, etc.), etc., etc., one use case should not dictate UI.

There's a meeting of some sort [virtually every week](https://arctosdb.org/calendar/), most any of them could be used to address this, or an ad-hoc committee could be formed.

**Comment by ewommack** [comment]
> skin subsamples should be ignored

> 
No, Best Practices would mandate (some) skins be children of whole organisms (so they can inherit preservation, etc.), etc., etc., one use case should not dictate UI.

Then we need a better display in the search results. When you show both the parent and child from the skins, you go from having one Sharp-shinned Hawk to having five. And you really do not have five. You only have one genetic sample, one isotope sample, one bird from one location in place and time.

**Comment by Jegelewicz** [comment]
Move preparation/preservation part of skin to preservation code table.

Change definition of the table to include preparation and preservation.

Remove skin clip, ear clip and toe clip from this issue.

**Comment by dustymc** [comment]
Closing based on [2023-09-21 AWG Code Table Committee](https://docs.google.com/document/d/1eZ_S8VTp-m5Wrbb6cAK96ODPZpt2-Hvnvt6yfU9qVwg/edit#heading=h.rortzr5prqrj) discussion
