### ISSUE TITLE
part cleanup: DNA

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4051]
Is [DNA extraction](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#dna_extraction) somehow distinct from [DNA](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#dna)?

If so, please provide differentiating documentation.

If not, I'd like to merge.

Data:

[temp_dnae.csv.zip](https://github.com/ArctosDB/arctos/files/7435760/temp_dnae.csv.zip)

Collections:

```

 guid_prefix | nrecs 
-------------+-------
 KNWR:Env    |     1
 MSB:Bird    |   131
 MSB:Mamm    |  1038
 MSB:Para    |    30
 UAM:Ento    |  4667
 UAM:Env     |   335
 UAM:Mamm    |    33
 UWBM:Mamm   |     5
```

Contacts:

 @campmlc
 @amgunderson
 @dssikes
 @jldunnum
 @msbparasites
 @catherpes,@catherpes
 @kyndallh

**Comment by dustymc** [comment]
I'll merge to DNA ~Monday if there's no feedback before.

**Comment by campmlc** [comment]
Works for me

**Comment by cjconroy** [comment]
This doesn't effect any MVZ mammals. But, my guess is that some of these might be a tube used in DNA extraction, but also includes the protein pellet, not just cleaned DNA. But, you'd have to hear back from those collections to verify.

**Comment by dustymc** [comment]
[temp_dnae(1).csv.zip](https://github.com/ArctosDB/arctos/files/7500353/temp_dnae.1.csv.zip)

done
