### ISSUE TITLE
Meteorite names - handling named things with data outside of Arctos

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4055]
NOTE-please see https://github.com/ArctosDB/arctos/issues/4055#issuecomment-961052677 for current discussion

**Goal**
Use an identifier to get all the stuff related with "same assemblage as"

**Context**
The related meteorites cataloged at UNM share an identifier that makes it easy to find them all. For example, these three records all share the identifier I43

![image](https://user-images.githubusercontent.com/5725767/139336849-adb27595-3404-4d3e-bb30-f5a90f0b045d.png)

They are related with "same assemblage as", but using "Find same assemblage as" only brings up the two "related" records, not ALL related records. In any case, if all three have the I43 identifier applied, it is easy to get them in search results. Rather than just calling this an "other identifier" I think it would be useful to call it the "assemblage ID" so that it matches up with the relations between the records.

**Table**
[ Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table you are requesting changes to here. ]

**Value**
assemblage ID

**Definition**
An identifier applied to all records sharing a "same assemblage as" relationship.

**Priority**
We need this for an incoming collection

**Comment by Jegelewicz** [comment]
OK - let us revisit this. Here is my dilemma. I can create a new other identifier

Meteoritical Society Identifier
base url = https://www.lpi.usra.edu/meteor/metbull.php?code=
defintion = Unique number assigned by the Meteoritical Society

BUT

NOBODY will search for 23166, people interested in meteors will search for "Santa Luzia". I think this is problematic for a lot of "name" type identifiers. I am not going to spend the next year attempting to convince The Meteoritical Society to change their method for identifying a page and I don't think that should be a part of our workflow. Here is what I would like.

An addition to the other identifier that lets us supply the end to the base url as the number, but also let's me apply a text label to the url that gets created.

So I would have

other_id_type | other_id_value | other_id_relationship | other_id_label 
 -- | -- | -- | -- 
Meteoritical Society ID | 23166 | self | Santa Luzia 

This would also allow Organism Id's like

other_id_type | other_id_value | other_id_relationship | other_id_label 
 -- | -- | -- | -- 
Organism ID | https://arctos.database.museum/info/agentActivity.cfm?agent_id=21332262 | self | Kianga

so that what is presented in the record is [Kianga](https://arctos.database.museum/info/agentActivity.cfm?agent_id=21332262), not https://arctos.database.museum/info/agentActivity.cfm?agent_id=21332262

> Note how we have fudged this already with an extra other identifier. 
![image](https://user-images.githubusercontent.com/5725767/139684496-bfc96cc5-de98-45eb-9da6-ee1414f2d31a.png)

The labels should not be required, and if none is given the identifier will appear as https://arctos.database.museum/info/agentActivity.cfm?agent_id=21332262 or https://www.lpi.usra.edu/meteor/metbull.php?code=23166

This provides both an identifier for machines and one for people. Possible?

Also note that these two things could fit into their own DwC fields:

url version = https://dwc.tdwg.org/terms/#dwc:organismID
text version = https://dwc.tdwg.org/terms/#dwc:organismName

**Comment by dustymc** [comment]
Cryptic identifiers are not something the Arctos Community should support.

**Comment by Jegelewicz** [comment]
This only provides a "cryptic" identifier when associated with one that is not. Also, "cryptic" to who! Meteorite people do not view "santa Luza as cryptic - but they will NOT know what 23166 means.

**Comment by Jegelewicz** [comment]
FWIW - this is the solution we have in object tracking. People do not need to understand the barcode, they can find things using the label associated with the barcode - that is all I am asking for here.

**Comment by campmlc** [comment]
This sounds interesting - I think I like it.

**Comment by dustymc** [comment]
"santa Luza" is cryptic to everyone. If you want something less cryptic, it needs typed somehow. (https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#object_title is my first thought but ?? - that's a "name" intended in part to support searching, which doesn't seem too far off.)

"23166" is probably just ambiguous, no matter how you try to type it. 

``https://www.lpi.usra.edu/meteor/metbull.php?code=23166`` is completely unambiguous - it's a great identifier as of about 30 seconds ago, but I'd bet against persistence and therefore would probably use Media (which has no expectations of persistence) to make that link (but I'm still not sure what you're trying to accomplish so ???).

Where did "I43" come from? The most correct solution might be somewhere in the answer.

I can't decode the analogy you're trying to make to the Arctos container model - I'm fairly certain there's not a single data object (with some handles) involved in meteorite whatever-this-is???

**Comment by Jegelewicz** [comment]
> "santa Luza" is cryptic to everyone.

NO it is not - When Carl Agee, the curator of the Institute of Meteoritics at UNM wants to find a meteorite - he searches by this name. Santa Luzia in the world of meteoritics MEANS something - it is an official name that is summarized on this web page - https://www.lpi.usra.edu/meteor/metbull.php?code=23166 which shows the name was published (aka described - like a species) in Buchwald (1975) [Buchwald, Vagn F. (1975) Handbook of Iron Meteorites. University of California Press, 1418 pp.]

![image](https://user-images.githubusercontent.com/5725767/139857365-59a13d02-0552-4356-9eb3-c19a388976fe.png)

Carl views this name as the identification of the three meteorite pieces I have recorded for UNM:MET. While this "taxonomy" may not match what biologists think of as "taxonomy", it is providing a similar service. Any meteorite identified as "Santa Luzia" indicates that it belongs to the object(s) described in the publication. 

> https://www.lpi.usra.edu/meteor/metbull.php?code=23166 is completely unambiguous - it's a great identifier as of about 30 seconds ago, but I'd bet against persistence and therefore would probably use Media (which has no expectations of persistence) to make that link.

So this is exactly like http://arctos.database.museum/guid/MVZ:Bird:157675?seid=1526959 which could change at any time since it is generated "on the fly". Persistence is something no one can truly offer - even DOI will be gone some day. I don't view that as a reason not to use a workable link right now.

> (but I'm still not sure what you're trying to accomplish so ???)

Carl will come to Arctos to search for a meteorite. Where is the most logical place for him to search for "Santa Luzia" (because that is what he is going to search for)? It is in identification. 

## Alternative 1 A {string} plus Other Identifier
I can use A {string} in order to make his searches productive. 

Iron meteorite {Santa Luzia}

BUT he should also very easily be able to get from any of the records in Arctos identified as "Santa Luzia" to the official meteorite name page. If I use the other identifier as it is meant to be used he will see this:

Meteoritical Society ID: [23166](https://www.lpi.usra.edu/meteor/metbull.php?code=23166) 

which is not very intuitive. I am sure he would get used to it - but what about his fellow researchers or meteorite enthusiasts? I'd like to be able to use text other than the number to represent the link created, so while what creates the link is 23166, what gets displayed is

Meteoritical Society ID: [Santa Luzia](https://www.lpi.usra.edu/meteor/metbull.php?code=23166) 

because the text will be different for every ID added, I suggested adding it as part of the individual identifier. Right now when I add an other ID to a record I add this:

other_id_type | other_id_value | other_id_relationship 
 -- | -- | -- 
Meteoritical Society ID | 23166 | self 

To accomplish what I want, I would need to add this

other_id_type | other_id_value | other_id_relationship | other_id_label 
 -- | -- | -- | -- 
Meteoritical Society ID | 23166 | self | Santa Luzia 

Still - this doesn't jive very well with the way Carl sees this term - as an identification...

## Alternative 2 modified A {string}
I can enter the whole url in the {string} part of the A {string} identification. I did this for kicks in one of the identifications in https://arctos.database.museum/guid/UNM:MET:5045 and it works, but when the society changes it's domain, that will mean A LOT of re-identification...also, are we really going to ask Carl and his team to type that into their ids? Because here is what it looks like.
```
Iron meteorite {<a href="https://www.lpi.usra.edu/meteor/metbull.php?code=23166" target="_blank">Santa Luzia</a>}
```

Pretty sure that wont get found with a search of Santa Luzia as well...

## Alternative 3 Taxonomy
I could make Santa Luzia a taxon name - which would give it a page and link all of the "Santa Luzia" records together neatly, but I would still have the problem of getting from the taxon page to the Meteoritical Society official page using some url that nobody understands. To overcome that in this scenario - I can add a publication for the page and associate it with the name. This works nicely and also allows me to add synonyms. Honestly, I think this would be my preferred method because it covers all of the bases.

See [Santa Luzia](https://arctos.database.museum/name/Santa%20Luzia)

I would suggest a new source - Arctos Meteorites for this taxonomy. I can use the name type "mineral", but I may end up wanting a new name type "meteor" - that would be up to Carl and Beth.

> Where did "I43" come from? The most correct solution might be somewhere in the answer.

I removed everything after the decimal in the UNM:MET other identifier, but this ID is something made up by UNM - it is definitely less global than the Meteoritical Society page/number. UNM has never used this. I plan to remove it from all of the records.

**Comment by Jegelewicz** [comment]
@ArctosDB/taxonomy I'd really like to hear your thoughts on this.

**Comment by AJLinn** [comment]
FWIT, this seems to be the exact same situation as any item in the cultural collections that have an official title (i.e., name).
We use A {string} 
https://arctos.database.museum/guid/UAM:EH:0768-0016 as an example

The UAM:Art collection has gone a slightly different way and made the ID the painting title, then used the {string} part to indicate the format of the art work.
https://arctos.database.museum/guid/UAM:Art:UA0903-0011

There is also an attribute: "Object Title" to reinforce this.

**Comment by Jegelewicz** [comment]
@AJLinn UAM Art uses A {string} in exactly the same way you do: A=painting and {string} = Eskimo Dance #5

> this seems to be the exact same situation as any item in the cultural collections that have an official title (i.e., name).

I totally get this and I actually started with it for the meteorites, BUT a meteorite name string can point to even more information about the object that those who study the object use and are aware of. If "Do thou amend thy face" had its own website where a bunch of scholarly information (the chemical composition of the paint, the material composition of the canvas) was included would you be happy with that plain string? What if the painting were torn into 5 pieces and they were in residence at various institutions and you had two of them - how would you want to represent that?

A named meteorite is NOT one piece of rock. It might be, but typically it is represented by a debris field. Pieces of the field may be discovered all at once or over time and those pieces may end up all over the place and not be initially identified as the named meteorite to which they belong. I want to offer the meteorite community a way to identify their objects that is familiar to them and that can be done with A {string}, but I also want to connect that string with the research applicable to it and right now I have no good way to do that.

**Comment by dustymc** [comment]
>I could make Santa Luzia a taxon name 

Taxa are hypotheses. "We shall name this individual thusly" is not a hypothesis. This is not an arbitrary or subjective thing. Arctos cannot function without properly-organized data, and this is not proper organization. The ability to separate taxa and identifications is one of the most central tenets of the "Arctos philosophy."

**Comment by Jegelewicz** [comment]
OK - so how do you suggest I do this? I am asking for help here and only getting yelled at for doing the wrong thing.

**Comment by campmlc** [comment]
Agree. Teresa has put a lot of thought and effort into this, and proposed multiple solutions. She needs at least one of these solutions to work so she can proceed with this incoming collection. If we can make this work so that it is usable for the meteoritics community, we will have to stop recruiting these types of collections. Personally, I support using taxonomy as it provides the tools needed. Maybe we call it something else - but we use the same data model and interface tools.

**Comment by dustymc** [comment]
>yelled at

I'm very sorry if that's how my answers have come across, it's certainly not my intention!

>suggest

For the "name" I think what UAM:EH does probably makes the most sense. Identifications are perhaps the most-searched thing in Arctos, will always be front-and-center-ish, if "Santa Luzia" is their main THING then "Iron meteorite {Santa Luzia}" is probably the best approach.

I'm not sure that https://www.lpi.usra.edu/meteor/metbull.php?code=23166 is a publication, but maybe there's some way to use citations to make that link - they seem a bit more "sciencey" than simple identifiers, although in this case they may be functionally identical. (Unless lpi.usra.edu is just a digital representation of one publication, which I don't think is the case??)

I dislike anything that leads to multiple ways of saying the same thing, and I think "assemblage id" does that - we'll end up with some lots-and-such that share a certain type of ID and some that carry a relationship and nobody will be able to find all of them. That's sometimes necessary anyway, if it is (I don't think so??) then it should be supported by clear documentation - "when X then do Y, when A then do B, don't get confused."

If none of that works, I think two identifiers may be most palatable:

* Meteoritical Society ID: random-looking number that links to something
* Meteoritical Society Name (or whatever this is): nonlinked string that makes sense to people (or maybe this is better as the [attribute](https://github.com/ArctosDB/arctos/issues/4055#issuecomment-956583227)??)

"santa Luza" just can't be informative; "meteorite name=santa Luza" (where "meteorite name" is some sort of data object - attribute, other ID, whatever) is. I don't think that was clear. (Maybe that's not entirely true within "the world of meteoritics" but I don't think "makes sense to some specialized audience" is ever a very defensible position, and it's certainly not something that Arctos is confined to.)

``http://arctos.database.museum/guid/MVZ:Bird:157675?seid=1526959`` is not intended to be persistent; making it so would require more resources (significantly more, I think). ``http://arctos.database.museum/guid/MVZ:Bird:157675`` and DOIs are as persistent as curators make them. DOIs can remain functional after the deprecation of the HTTP protocol and anyone can make a handler for them so they're a bit "better" than the http identifier, but both are completely persistent with some curatorial commitment (and absolutely nothing can be without).

Want to Zoom?

**Comment by Jegelewicz** [comment]
Yes a Zoom would probably be helpful. How about 1PM your time, Arctos Zoom Room?

**Comment by dustymc** [comment]
I'll be there.

**Comment by dustymc** [comment]
I believe the fundamental desire is for some tripartite data object containing

1. "Their" local identifier eg ``23166``
2. A base URL eg ``https://www.lpi.usra.edu/meteor/metbull.php?code=``
3. "Our" local identifier eg ``Santa Luzia``

which all comes together as ``<a href="{baseURL}{theirID}">{ourID}</a>``

I don't like that as Other IDs - we're already doing a poor job of displaying the identifier (we show ``23166``, the actual identifier is ``https://www.lpi.usra.edu/meteor/metbull.php?code=23166``), adding yet another layer of "not the identifier" - and maybe completely unrelated to the identifier, it would be something someone felt like typing, nothing more - seems like it would inevitably make the data less accessible and more confusing.

The previously mentioned [attribute](https://github.com/ArctosDB/arctos/issues/4055#issuecomment-956583227) would be difficult to use - they'd have to use the link generator (or type HTML), changes would be difficult, etc.

Media is somehow not user friendly, but I think it's the most defensible mechanism for this link. @Jegelewicz would media be more palatable for this purpose if we could find a way to display a text string instead of requiring an image as the preview?

**Comment by Jegelewicz** [comment]
@dustymc when I attempt using media, clicking the link gets me this:

![image](https://user-images.githubusercontent.com/5725767/140190998-b0d84f28-ff2c-4f7b-9f20-1b48e7167e45.png)

I can click through, but that isn't ideal.

Tried putting it in other ID and that fails too. I entered

```
<a href="https://www.lpi.usra.edu/meteor/metbull.php?code=23166 " target="_blank">Santa Luzia</a> and what I see in there is NOT that....

![image](https://user-images.githubusercontent.com/5725767/140191640-a2f8c580-a98d-432c-9bea-79073bb412c8.png)

And I cannot delete that. When I try I get

![image](https://user-images.githubusercontent.com/5725767/140191724-33b6274b-820f-4506-9571-7ecc33173456.png)

**Comment by dustymc** [comment]
I can't do anything about their server response - you can ask them to fix it....

https://github.com/ArctosDB/arctos/issues/4069

**Comment by Jegelewicz** [comment]
> I can't do anything about their server response - you can ask them to fix it....

But this works from other parts of Arctos.

See the identification on this record

https://arctos.database.museum/guid/UNM:MET:5045

Why should they accept the link from there but not from our "media" it seems like that is something on our end?

**Comment by dustymc** [comment]
Media is pre-checked (and anyone with media should be watching the exit links) - it's functional only as links.

Identifiers (or whatever you've done there, I don't have access) are not pre-checked - they're still functional as identifiers even if they look like links which don't happen to work.

**Comment by Jegelewicz** [comment]
But it is the media that doesn't work - the taxon name does.

**Comment by campmlc** [comment]
If I were looking for a meteorite called Santa Luzia, it would never occur to me to search media. How does this address discoverability concerns?

**Comment by dustymc** [comment]
They are refusing a HEAD request (or blocking Arctos or TACC or something), and accepting a GET request (or not blocking you or something).

**Comment by campmlc** [comment]
What about allowing Santa Luzia as a display name linked to an underlying
url? This is what we do with every other platform, eg Gmail, Microsoft etc

**Comment by Jegelewicz** [comment]
I have been convinced that I cannot use taxonomy for this purpose, so all objects in the UNM:MET collection will be identified using A {string}. Here is a current summary of my options for linking up with the information for these objects in the Meteoritical Bulletin Database (MBDB).

## Option 1 - Link in the {string}
I can enter the whole url and related HTMl in the {string} part of the A {string} identification. I did this for kicks in one of the identifications in https://arctos.database.museum/guid/UNM:MET:5045 and it works.

```
Iron meteorite {<a href="https://www.lpi.usra.edu/meteor/metbull.php?code=23166" target="_blank">Santa Luzia</a>}
```

Pros:
 - It does exactly what I want it to do - clicking the blue text of Santa Luzia in the record takes me right to the named item page.
 - It also seems to still work as a search term in "Any taxon, ID, common name:".

Cons:
 - Any time a new record is entered, the HTML for the link will need to be typed out or generated. Not ideal for anyone unfamiliar with HTML and prone to errors.
 - When the society changes it's domain or identifier number, that will mean A LOT of re-identification.
 - Are we really going to ask Carl and his team to type that into their ids?
 - Does not work in the "Identification" search - **this is a deal breaker**

## Option 2 - Enter two other identifiers

One that is the link to MBDB, the other that is the text we want to see for the link. The Meteoritical Bulletin Database ID would include the base url
```
https://www.lpi.usra.edu/meteor/metbull.php?code=
```
So I would have something like this in the catalog record:

Meteoritical Bulletin Database ID: [23166](https://www.lpi.usra.edu/meteor/metbull.php?code=23166) 
Meteroritical Bulletin Database Name: Santa Luzia

Pros:
 - There is a link to the MBDB page
 - When the society changes it's domain, we only need to edit the base url for the Meteoritical Bulletin Database ID to re-create the links.

Cons:
 - The link to the MBDB page is seen as "23166" not "Santa Luzia"
 - Requires double the work and other identifiers
 - Not very intuitive

## Option 3 - HTML in the other id value

I can enter the whole url as the value in the other identifier. I did this for in https://arctos.database.museum/guid/UNM:MET:5045 but the value in the Meteoritical Bulletin Database Name would look like this:
```
<a href="https://www.lpi.usra.edu/meteor/metbull.php?code=23166" target="_blank">Santa Luzia</a>
```
which ends up looking like this on the record page:

Meteoritical Bulletin Database Name: [Santa Luzia](https://www.lpi.usra.edu/meteor/metbull.php?code=23166) 

Pros:
 - There is a link to the MBDB page from the words "Santa Luzia" on the catalog record

Cons:
 - When the society changes it's domain, we will need to create a lot of new HTML to replace all of the Meteoritical Bulletin Database Name values
 - Are we really going to ask Carl and his team to type that into their ids?
 - Not found in a search for other identifier = Santa Luzia **this is a deal breaker**

## Option 4 - Media
I can enter the url for the MBDB page as media. I have done this for Santa Luzia and associated it with all of the appropriate records.

Pros:
 - There is a link to the MBDB page

Cons:
 - Not intuitive. Who is going to look in media for a link to MBDB?
 - Apparently media links work differently than those created in my scenarios above. As "HEAD" requests, they are refused by MBDB. This results in a scary red box with an error message. You can click through to the page, but my guess is that a lot of people will not do that and it makes Arctos appear broken. See https://github.com/ArctosDB/arctos/issues/4055#issuecomment-960048403 **this is a deal breaker**

So - I am pretty much left with the option of creating two separate identifiers and having the link work on the one that includes a value that no person will recognize. It seems like we should be able to do better than that!

I really need other people to help me think about this and its implications for all "named" individuals/objects, especially those where information related to the individual/object might be held in places other than Arctos. I also think this relates to the many-to-many problem of other id relationships, especially for any of the "same as" relationships which can become quite hazardous and unwieldy when there are more than three related items. This is holding up data entry for an incoming collection, but I also think it has a lot of potential benefits/consequences for cultural collections and anyone dealing with multiple sampling from a single biological individual or multiple cataloged items that are structurally connected (fossils).

@campmlc @AJLinn @marecaguthrie @Nicole-Ridgwell-NMMNHS @aklompma @mkoo

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> they've chosen to use "23166" as their identifier

It doesn't seem to me that they have, it is how they have built their urls, not how they are actually identifying the meteorite.

**Comment by dustymc** [comment]
> it is how they have built their urls,

Ah - thanks, maybe I get it a bit. From my perspective, those are completely interchangeable - there's nothing else I can use to identify them from here, URL===identifier. They may have never even considered the possibility of anything other than humans navigating their HTML page in a fairly predictable direction and not have any perspective on this at all.

I'm not sure the *why* helps with anything functional, but if this is something that just happened rather than a choice then maybe they could be convinced to expose their intended identifier - has anyone talked to them about any of this?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I like the idea presented early in the thread of other_id_label. Negotiating with the Meteoritical Society about their urls is not an immediate solution that will allow UNM to load their meteorite data.

**Comment by dustymc** [comment]
>other_id_label

Is there some way we could mitigate the problems I've attempted to outline in https://github.com/ArctosDB/arctos/issues/4055#issuecomment-960039193?

**Comment by campmlc** [comment]
I support this also.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> I don't like that as Other IDs - we're already doing a poor job of displaying the identifier (we show 23166, the actual identifier is https://www.lpi.usra.edu/meteor/metbull.php?code=23166), adding yet another layer of "not the identifier" - and maybe completely unrelated to the identifier

I see it the opposite way around, Santa Luzia is the actual identifier, 23166 + base url is just how we connect the identifier to the external resource.

**Comment by campmlc** [comment]
Yet this is exactly what we do when we insert a web link into an email or
document. There is a label field and an address field. It is widely used
and understood.

**Comment by dustymc** [comment]
>web link into an email 

That's essentially been my point: the data object in question is identifiers, those things are not identifiers, we have Media for linky-non-identifiers. But....

>Santa Luzia is the actual identifier, 23166 ... is just how we connect

AHA/THANK YOU! (I hope.) That is a defensible position. "23166" is still an identifier, it's just not necessarily THE identifier. I don't see any problems with distinguishing between types of identifiers (or types of their components, or something).

SO:

Option One: Duct tape. Arctos could accept something like ``23166|Santa Luzia`` as the 'value' and do some UI magic on it. I hate everything about this, but I could do it quickly and this seems to be an exceedingly rare situation so maybe it's worth considering anyway.

Option Two: Rebuild the model (and UI, of course). There's been occasional mention of doing something more (adding metadata, I think) with otherIDs but it's never become the focus of a conversation. If we're going to have to rewrite everything anyway, we should get what we want while we're in there. If that seems reasonable then I think it needs a dedicated/focused/clean Issue.

**Comment by campmlc** [comment]
Agree. That is how the meteoritics community sees it, and how they will
search on it.
As for the many- to -many identifiers, this has been brought up multiple
times, most recently in the entity discussion. Anything out of a binary
relationship of two objects sharing a relationship becomes a complex
network of reciprocal relationships that is impossible to create linkages
for. How many same individual as or same lot as relationships have to be
created when you have 10+ objects that share the same relationship? ten to
the power of 10?

**Comment by campmlc** [comment]
I very much support adding metadata to identifiers. We've needed this for a
long time.
Perhaps we need both solutions above - as this is holding up data migration.

**Comment by dustymc** [comment]
>impossible to create linkages

Get the email, click down, review, click up, autoload?? I obviously need more info, we need better documentation, SOMETHING.

>adding metadata

Make a proposal! Here's a consideration: IDs are "facts" and so I feel comfortable only doing ^^ that. If I had sufficient metadata, I could just make them instead of sending you notifications. (And the metadata would let us un-make those when it turns out some script has gone off the rails.) I think I'd just need 'asserted_by' and a date to be comfortable with that, but it's really a question for you - what do you need to be comfortable with me magicking data into your collection, if you would consider that at all?

>both solutions above

I think that's probably harder to "unwind" than two (semi-temporary) identifiers that will be merged when that becomes possible, and I'd rather not rebuild the UI and then rebuild the UI (nor figure out how to search twice, share via DWC twice, etc.)

**Comment by campmlc** [comment]
Or we can use agents, like Kianga, which does everything we need. If could use the same model and call it something else as a means to link all information, akas, urls, pubs etc associated with an object, that would be phenomenal.

**Comment by dustymc** [comment]
> agents....which does everything we need

>link all information, akas, urls, pubs etc associated with an object

Agents are structurally incapable of doing those things in a defensible manner, nor do they provide a [stable identifier](https://github.com/ArctosDB/documentation-wiki/issues/250). I hope you can see the point of confusion! 

Cataloged item do all of those things and more - someone/everyone doesn't understand _something_ but IDK what that might be, it could be relevant to the structure of otherIDs.

**Comment by campmlc** [comment]
This is stable: https://arctos.database.museum/agents.cfm?agent_id=21332262
and if we had a "label" field of "Kianga" that would link to that url, it
would do what we need.

**Comment by campmlc** [comment]
This url :
https://arctos.database.museum/info/agentActivity.cfm?agent_id=21332262

**Comment by dustymc** [comment]
>This is stable

Nope!

**Comment by campmlc** [comment]
What we need is an uber catalog record, a dashboard to link all related
"same as" objects, their usage, their media, their varieties of names,
external links, including web addresses such as
https://www.arkansasonline.com/news/2020/apr/02/lr-zoo-welcomes-13-year-old-chimpanzee/#:~:text=Kianga%20is%20a%2013%2Dyear,She%20arrived%20March%203
.

**Comment by campmlc** [comment]
Why not? Do you change agent identifiers the same way as you change
collecting event and occurrence IDs?

**Comment by dustymc** [comment]
>uber catalog record

https://handbook.arctosdb.org/documentation/catalog.html#understanding-cataloged-items

> link all related
"same as" objects, their usage, their media, their varieties of names,
external links, including web addresses 

That does all of that, along with things like recording data which applies to "the whole" if not necessarily the pieces.

**Comment by campmlc** [comment]
But it doesn't work. We can't have a single record that has all collecting
events, specimen events, catalog numbers, accessions, relationships etc. It
cannot be done from a collection management perspective, it is too complex
for students and collection managers.  We've tried and failed.

**Comment by dustymc** [comment]
> We can't have a single record that has all collecting
events,

Let's zoom - that's not at all what I'm suggesting. Using it is precisely as complex as it needs to be!

**Comment by campmlc** [comment]
OK, because this meteorite situation parallels problems with Mexican wolves
and zoo animals that needs resolution.

**Comment by dustymc** [comment]
Maybe:

* identifier_issued_by (eg MSB issues NKs)
* identifier_asigned_by (eg @campmlc applies it to a record)

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Coincidentally, meteorite data standards were briefly discussed at todays TDWG ESP interest group meeting, and they said that the meteorite name is THE most important piece of information about a meteorite specimen.

**Comment by campmlc** [comment]
I like that. Solves ZRC problem.

**Comment by Jegelewicz** [comment]
[This](https://github.com/ArctosDB/arctos/issues/4055#issuecomment-961356350) is exactly what Carl and @beth3ha told me!

**Comment by Jegelewicz** [comment]
I think this sound like a very good idea - but I fail to see how it solves my meteorite problem.

**Comment by dustymc** [comment]
>fail

https://github.com/ArctosDB/arctos/issues/4055#issuecomment-961205817

**Comment by Jegelewicz** [comment]
The value of the identifier is still going to be something like  https://www.lpi.usra.edu/meteor/metbull.php?code=23166 right? That is what I am trying to avoid.

**Comment by dustymc** [comment]
No. There will be no "value of the identifier" there will be - well, something, probably, likely more complex than "value," it needs worked out. Maybe 

* identifier_for_people (Santa Luzia)
* identifier_for_machines (23166)
* current stuff from the CT
* [^^ that junk](https://github.com/ArctosDB/arctos/issues/4055#issuecomment-961292604)

and whatever else belongs in here, all as part of a single data object

**Comment by Jegelewicz** [comment]
I have addressed my need to get this data in. When other ID metadata gets resolved we can add things then. Closing.
