### ISSUE TITLE
Change verification status on a bunch of events - help please

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4059]
@dustymc this file includes a bunch of APSU records that have two event stacks. All of the event stacks are currently "unverified", but @gradyjt would like all of the collection and depiction events changed to "unaccepted". After that, you can see that most of the observation events are to be changed to "accepted" with some exceptions - I am not sure of the best way to make all of this happen. I was going to use the "manage specimen event" tool in search results, but with no way to filter out about half of the events, it would mean a LOT of clicking to get the set of events I want to change.

[SpecimenEventAndCollectingSourceCleanup.csv](https://github.com/ArctosDB/arctos/files/7444424/SpecimenEventAndCollectingSourceCleanup.csv)

**Comment by gradyjt** [comment]
If it can't be done I have students that can do the clicking hahaha

**Comment by dustymc** [comment]
I'll look at this next week - I can definitely save you some clicking.

**Comment by dustymc** [comment]
In the future, please talk to me **before** setting up a spreadsheet - I think I can make this work, but it's not quite as linear as I'd like.

Here's a first pass. Attached are the specimen_events for which I think you want to change verificationstatus to unaccepted - please let me know if that's them, not them, you need more data, whatever. 

I'll make a second pass for the observations once this part has been resolved.

[temp_apsu_evts_col_dep.csv.zip](https://github.com/ArctosDB/arctos/files/7455078/temp_apsu_evts_col_dep.csv.zip)

**Comment by gradyjt** [comment]
Hey @dustymc, did you query the csv that Teresa linked in the first message of this issue? Things aren't quite matching up between what you sent, she sent and what I originally sent to her.

**Comment by gradyjt** [comment]
Yeah, something definitely got off in that file in the first message from Teresa. What would you like from me to help with this?

**Comment by dustymc** [comment]
I used collecting_event_id from that file, and joined on specimen_event_type in ('collection','depiction').

If you want to start over (which is no problem), just tell me what you want to find for update (and what you want to update so I make sure I get the right stuff in the file) - I'll pull some data, you can confirm it's what we're looking for, I'll make some updates when that's all worked out, then we can rinse and repeat as necessary.

Here's the SQL I used in case that's useful

```
create table temp_apsu_evts_col_dep as
select
temp_apsu_updatevt.guid,
temp_apsu_updatevt.collecting_event_id,
specimen_event.specimen_event_id,
specimen_event.specimen_event_type,
specimen_event.verificationstatus
from
temp_apsu_updatevt
inner join collecting_event on temp_apsu_updatevt.collecting_event_id::int=collecting_event.collecting_event_id
inner join specimen_event on collecting_event.collecting_event_id=specimen_event.collecting_event_id and 
 specimen_event.specimen_event_type in ('collection','depiction')
```

**Comment by gradyjt** [comment]
Ok, this is the file that Teresa had originally set up and I filled out for her, where anything that needed changed has the true value in the "new" column. None of the specimen event types should need changed, just most of the verification statuses. Is there a way I can set this up to make it easier for you to do this? Would a list of all collecting event IDs that need verification status changed from unverified to accepted, or from unverified to unaccepted, or from unaccepted to accepted, etc be helpful? I'm happy to just completely start over as well and set things up the way you need. I may have other things like this I need to do in the future so knowing now how to set things up for you properly will probably pay dividends.

Also, if you want something other than an excel file let me know. 

[SpecimenEventAndCollectingSourceCleanup.xlsx](https://github.com/ArctosDB/arctos/files/7461503/SpecimenEventAndCollectingSourceCleanup.xlsx)

**Comment by dustymc** [comment]
> way I can set this up 

From here: I don't think so.

Going forward: just talk to me early in the process. In this case what I need is specimen_event_id, I doubt you can get that from the UI, I could have built the file with that, then you could have added the "changeto" columns, and we'd always have an unambiguous link to the data object.

>how to set things up 

It'll be different every time. Just talk to me early!

>other than an excel file 

I always work in CSV, which is plain text and (very unlike xls!) has no chance of being interpreted differently by various apps.

ANYWAY - I think I was able to get what I need. I extracted the "update" columns along with enough information for me to make the updates, and hopefully enough for you to verify that I'm on the right page with this.

If this is enough for you to confirm that these are the correct specimen events and that I didn't muck anything up, I'll set the specimen_events to the value of ``new_verificationstatus`` when it's not null, and do nothing when it is.

Let me know how to proceed.

[temp_apsu3.csv.zip](https://github.com/ArctosDB/arctos/files/7462545/temp_apsu3.csv.zip)

**Comment by gradyjt** [comment]
All looks good to me! I think you're good to go. Thank you.

**Comment by dustymc** [comment]
done

**Comment by gradyjt** [comment]
Thanks!

**Comment by gradyjt** [comment]
So please don't hate me... but I was going through the database to see how the changes looked and there's many more records with two specimen events that didn't get pulled for Teresa's query ( I think because the ones she and I were looking at had two different specimen event types, but the remaining ones all have the same specimen event types). So I need to do this process again. You want me to set up a file with the specimen event IDs and what the verification status should be? No rush on this if you're busy, just don't want to forget I need to do this. Thank you a million for your help.

**Comment by dustymc** [comment]
Let me know a bit more about what you're looking for and I can set up a file, or if you want to do so and can find a way to include the specimen_event_id (assuming you're just wanting updates to table specimen_event) then that's fine too.

Iterative processes are usually better - doing one thing is about always straightforward, anything more complex often isn't. I definitely don't mind addressing one variation at a time, and this sort of thing often leads to Arctos becoming a bit more capable - please don't hesitate to ask for help!

**Comment by gradyjt** [comment]
I think the first step is to pull everything with two specimen events. From there I need to assess which specimen event should be accepted or unaccepted. There may be a column we can sort on to automate which ones need accepted or unaccepted, but I'll have to look at the file. For example, I wasn't the only one to georeference records so we can't assign any that have my name as the specimen_event_determiner as accepted. Another example, in some cases I had georeferenced something before the bad specimen event was assigned by someone else so choosing a later or earlier date for assigned_date won't work either... 

Is there a way that I can download every record with two specimen events? If so I'll do that and see if there's anything standard that we can sort on and get back with you about options.  

Does that sound right/make sense?

**Comment by gradyjt** [comment]
Probably could largely sort that file by georeference_protocol and assign anything with a protocol of "GeoLocate" as verification_status=accepted and I would just need to go through the list and make sure there wasn't anything that was georeferenced twice (should be very very few if any, and I'll change those manually). 

Then that would just leave all of the older bad specimen events (which I'd assign as verification_status=unaccepted) plus any records that I skipped georeferencing (because there was no specific locality or lat/long given or I was dubious about the info provided) and again, that should be a pretty short list I'd need to go through and manually assign accepted or unaccepted for verification_status.

**Comment by dustymc** [comment]
>everything

Elaborate please - what "columns" do you need?

>download every record with two specimen events? 

Not that I know of, and "record" (thing that gets smooshed into the table view) probably isn't what you want anyway.

There are 7029 APSU:Herp record with multiple events - some have more than two. Here's a start, let me know what else you need.

[temp_apsu4.csv.zip](https://github.com/ArctosDB/arctos/files/7463190/temp_apsu4.csv.zip)


```
create table temp_apsu4 as select
flat.guid,
specimen_event.*
from flat inner join specimen_event on flat.collection_object_id=specimen_event.collection_object_id
where flat.collection_object_id in (
select collection_object_id from (
select flat.collection_object_id,count(specimen_event.specimen_event_id) from
flat inner join specimen_event on flat.collection_object_id=specimen_event.collection_object_id
where guid_prefix='APSU:Herp' group by flat.collection_object_id having count(specimen_event.specimen_event_id) > 1
) a1);


arctosprod@arctos>> select guid, count(*) from temp_apsu4 group by guid having count(*) > 2;
      guid       | count 
-----------------+-------
 APSU:Herp:17850 |     3
 APSU:Herp:17753 |     3
 APSU:Herp:17785 |     3
 APSU:Herp:17906 |     3
 APSU:Herp:17758 |     3
 APSU:Herp:17980 |     3
 APSU:Herp:17783 |     3
 APSU:Herp:17830 |     3
 APSU:Herp:17773 |     3
 APSU:Herp:17966 |     3
 APSU:Herp:17746 |     3
 APSU:Herp:17768 |     3
 APSU:Herp:17920 |     3
 APSU:Herp:17851 |     3
 APSU:Herp:17750 |     3
 APSU:Herp:17905 |     3
 APSU:Herp:17832 |     3
 APSU:Herp:17743 |     3
 APSU:Herp:17978 |     3
 APSU:Herp:17999 |     3
 APSU:Herp:17756 |     3
 APSU:Herp:17782 |     3
 APSU:Herp:17794 |     3
 APSU:Herp:17778 |     3
 APSU:Herp:17775 |     3
 APSU:Herp:17921 |     3
 APSU:Herp:17793 |     3
 APSU:Herp:17987 |     3
 APSU:Herp:17751 |     3
 APSU:Herp:17833 |     3
 APSU:Herp:17998 |     3
 APSU:Herp:17795 |     3
 APSU:Herp:17752 |     3
 APSU:Herp:17745 |     3
 APSU:Herp:17911 |     3
 APSU:Herp:17837 |     3
 APSU:Herp:17970 |     3
 APSU:Herp:17774 |     3
 APSU:Herp:17996 |     3
 APSU:Herp:17977 |     3
 APSU:Herp:17764 |     3
 APSU:Herp:17912 |     3
 APSU:Herp:17761 |     3
 APSU:Herp:17780 |     3
 APSU:Herp:17916 |     3
 APSU:Herp:17985 |     3
 APSU:Herp:17988 |     3
 APSU:Herp:17972 |     3
 APSU:Herp:17744 |     3
 APSU:Herp:17994 |     3
 APSU:Herp:17986 |     3
 APSU:Herp:17975 |     3
 APSU:Herp:17786 |     3
 APSU:Herp:17796 |     3
 APSU:Herp:17979 |     3
 APSU:Herp:17788 |     3
 APSU:Herp:17836 |     3
 APSU:Herp:17789 |     3
 APSU:Herp:17762 |     3
 APSU:Herp:17755 |     3
 APSU:Herp:17852 |     3
 APSU:Herp:17748 |     3
 APSU:Herp:17973 |     3
 APSU:Herp:17976 |     3
 APSU:Herp:17798 |     3
 APSU:Herp:17766 |     3
 APSU:Herp:17993 |     3
 APSU:Herp:17915 |     3
 APSU:Herp:17829 |     3
 APSU:Herp:17968 |     3
 APSU:Herp:17791 |     3
 APSU:Herp:17754 |     3
 APSU:Herp:17913 |     3
 APSU:Herp:17784 |     3
 APSU:Herp:17835 |     3
 APSU:Herp:17843 |     3
 APSU:Herp:17828 |     3
 APSU:Herp:17992 |     3
 APSU:Herp:17995 |     3
 APSU:Herp:17974 |     3
 APSU:Herp:17757 |     3
 APSU:Herp:17772 |     3
 APSU:Herp:17771 |     3
 APSU:Herp:17967 |     3
 APSU:Herp:17797 |     3
 APSU:Herp:17989 |     3
 APSU:Herp:17841 |     3
 APSU:Herp:17981 |     3
 APSU:Herp:17765 |     3
 APSU:Herp:17842 |     3
 APSU:Herp:17760 |     3
 APSU:Herp:17777 |     3
 APSU:Herp:17903 |     3
 APSU:Herp:17840 |     3
 APSU:Herp:17990 |     3
 APSU:Herp:17790 |     3
 APSU:Herp:17917 |     3
 APSU:Herp:17747 |     3
 APSU:Herp:17767 |     3
 APSU:Herp:17914 |     3
 APSU:Herp:17849 |     3
 APSU:Herp:17839 |     3
 APSU:Herp:17792 |     3
 APSU:Herp:17919 |     3
 APSU:Herp:17971 |     3
 APSU:Herp:17831 |     3
 APSU:Herp:17904 |     3
 APSU:Herp:17781 |     3
 APSU:Herp:19784 |     3
 APSU:Herp:17984 |     3
 APSU:Herp:17844 |     3
 APSU:Herp:17770 |     3
 APSU:Herp:17787 |     3
 APSU:Herp:17769 |     3
 APSU:Herp:17838 |     3
 APSU:Herp:17779 |     3
 APSU:Herp:17991 |     3
 APSU:Herp:17982 |     3
 APSU:Herp:17776 |     3
 APSU:Herp:17969 |     3
 APSU:Herp:17983 |     3
 APSU:Herp:17918 |     3
 APSU:Herp:17749 |     3
 APSU:Herp:17763 |     3
 APSU:Herp:17997 |     3
 APSU:Herp:17834 |     3

```

**Comment by gradyjt** [comment]
> what "columns"

Hmm, I think if you add to this file columns assigned_by_agent and georeference_protocol I will be set to evaluate everything.

**Comment by dustymc** [comment]
Let me know if you need something else.


[temp_apsu5.csv.zip](https://github.com/ArctosDB/arctos/files/7463499/temp_apsu5.csv.zip)


```
create table temp_apsu5 as select
flat.guid,
specimen_event.specimen_event_id,
specimen_event.collection_object_id,
specimen_event.collecting_event_id,
specimen_event.assigned_by_agent_id,
getPreferredAgentName(specimen_event.assigned_by_agent_id) assignedby,
specimen_event.assigned_date,
specimen_event.specimen_event_remark,
specimen_event.specimen_event_type,
specimen_event.collecting_method,
specimen_event.collecting_source,
specimen_event.verificationstatus,
specimen_event.habitat,
specimen_event.verified_by_agent_id,
getPreferredAgentName(specimen_event.verified_by_agent_id) verifiedby,
specimen_event.verified_date,
locality.dec_lat,
locality.dec_long,
locality.spec_locality,
locality.georeference_source,
locality.georeference_protocol
from flat inner join specimen_event on flat.collection_object_id=specimen_event.collection_object_id
inner join collecting_event on specimen_event.collecting_event_id=collecting_event.collecting_event_id
inner join locality on collecting_event.locality_id=locality.locality_id
where flat.collection_object_id in (
select collection_object_id from (
select flat.collection_object_id,count(specimen_event.specimen_event_id) from
flat inner join specimen_event on flat.collection_object_id=specimen_event.collection_object_id
where guid_prefix='APSU:Herp' group by flat.collection_object_id having count(specimen_event.specimen_event_id) > 1
) a1);
```

**Comment by gradyjt** [comment]
Looks good, thank you. So do you want me to put in a column for "new verification status" again?

**Comment by dustymc** [comment]
Yep, that'll work.

**Comment by gradyjt** [comment]
Ok, I have fixed all of the verification statuses for these APSU:Herp records with multiple specimen events. These should be good to go up. Let me know if you get flags cuz I missed something.

[AllSpecimenVerificationStatusFixes.zip](https://github.com/ArctosDB/arctos/files/7464105/AllSpecimenVerificationStatusFixes.zip)

But before you do that...I have a "next steps" thing I need help with if you're game. For all of the records from this file we're working with that are or will be "accepted" I need the specimen_event_remark moved to locality_remarks (since they are notes about georeferencing procedure). Is this something that can be done? Thanks for your time!

**Comment by gradyjt** [comment]
I say "before you do that" cuz I don't know if that will affect whether you want to upload these changes yet or not...?

**Comment by gradyjt** [comment]
I may need to check and be sure there are no locality remarks that would be overwritten before you do this...but I really don't think there will be.

**Comment by dustymc** [comment]
There are a few, I can just append. Several are shared by events, so they'll get concatenated too. There are a few shared with other collections, I'll probably skip them and send you CSV.

**Comment by dustymc** [comment]
done

**Comment by gradyjt** [comment]
Awesome! So just to be sure I understand, which ones had null remarks? The ones with existing locality remarks, or the ones that were shared with other collections, or both?

**Comment by gradyjt** [comment]
Ok, so we're all good there? Nothing I need to sort out with that? 

P.S. everything I've seen so far with your fixes look great! Thank you. I'm finishing up the project with Teresa now to update some of the "parts" in this collection. Then I'll be turning my attention to the old "field notes" and "remarks" from our Access database and splitting those into various attributes and remarks. I think with attributes I should be good to bulkload those myself, but remarks I may need some help. Teresa said you may just need the guid and the remark when I'm ready?

**Comment by dustymc** [comment]
Yep I think it's all good.
 
>guid and the remark

Depends on what flavor of remark - if it's something in a 1:1 relationship with the catalog item then yes that should do it.

**Comment by gradyjt** [comment]
That should be the case I believe. Despite what we've been doing here lately, most of our records are single non-shared specimen/collection events. We don't mass kill things much anymore, just scavenge roadkill...haha!
