### ISSUE TITLE
Data Entry Attributes/Bulkload Attributes - a better way?

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#4062]
We've casually talked about this numerous times but I really think we need to be able to add more attributes directly in the Data Entry screen (can be expandable like adding coordinates or customizable by on the form so it doesn't take up too much real estate[?]). 

The problem I'm encountering is that with bird specimens, we record 15 standard measurements and attributes. The "add more" feature can be used by someone with Data Entry permissions, yet they cannot view or edit anything they've input in the Bulkload Attributes staging table (where "add more" data ends up), because they do not have Manage Collection privileges. When I look through the Bulkload Attributes table to approve records, only UUIDs are visible, making it very difficult to QC against our prep log since I need to see cat#. This structure has lead to all sorts of errors and data falling through the cracks (even pre-dating "add more" functionality, when we simply had to load records with a note in the prep log "half-databased" crossing our fingers that someone would go back through and populate all the overflow attribute data at a later point in time). Even if Data Entry permissions were expanded to cover viewing and editing the Bulkload Attributes table and we were able to pull in cat#/GUID for easier QC, the two-step process makes me nervous.

@ccicero @acdoll @ewommack do you feel similar? I'm sure this may have implications for other collection types that are attribute-heavy, or collections with a lot of parts that also may want an in-screen add option.

**Comment by dustymc** [comment]
I can add "extra" attributes to the new form.

I think everything should be visible to the enter-er in the new form and from the new linked edit form.

Bulkloader status autoload_extras will let you bring everything in together (or fail), and anything that's stuck in the component loaders for any reason will send notifications.

There's always something which can be made better, but I think the recent developments address the bulk of this. Let me know what's not covered.

**Comment by ebraker** [comment]
@dustymc This sounds AMAZING and will be a huge improvement. Thank you!

**Comment by dustymc** [comment]
>will be

Minus extra attributes, it's in production - give it a whirl!

**Comment by campmlc** [comment]
Yes, this potentially solves years of concerns about the problem of loading
extras and the loss of these data.

**Comment by dustymc** [comment]
Next release:

Get to the new data entry screen via the big red box at the top of the old:

<img width="339" alt="Screen Shot 2021-11-02 at 12 57 43 PM" src="https://user-images.githubusercontent.com/5720791/139943317-81c0fd2a-ce5d-4328-8fe0-38280bcb60b1.png">

Use the finder:

<img width="316" alt="Screen Shot 2021-11-02 at 12 58 43 PM" src="https://user-images.githubusercontent.com/5720791/139943408-e9afe1bc-7099-493f-beb4-da5577520872.png">

Customize, turn on whatever you want (and now's a really good time to let me know if more than 10 additional attributes are necessary).

<img width="265" alt="Screen Shot 2021-11-02 at 12 59 23 PM" src="https://user-images.githubusercontent.com/5720791/139943561-8ef3e37f-590b-4645-940f-17f74bb12f0a.png">

<img width="886" alt="Screen Shot 2021-11-02 at 1 00 28 PM" src="https://user-images.githubusercontent.com/5720791/139943644-ee32a123-14e9-4411-9dc8-f8d5aece553c.png">

Enter stuff, it works like "normal" attributes:

<img width="754" alt="Screen Shot 2021-11-02 at 1 00 58 PM" src="https://user-images.githubusercontent.com/5720791/139943725-ca976693-a903-4791-94ba-20105ef2b167.png">

The new edit screen (browse your records from data entry, edit last after save on data entry, "new edit" from browse-and-edit) has an "extras" summary at the bottom:

<img width="667" alt="Screen Shot 2021-11-02 at 1 02 50 PM" src="https://user-images.githubusercontent.com/5720791/139943960-79a8e7fc-48b7-48d7-ac0d-353a712824a4.png">

You can click through the the loaders - that part may not be available to students, I'm not sure what to do about that, new Issue if necessary.


<img width="1190" alt="Screen Shot 2021-11-02 at 1 03 53 PM" src="https://user-images.githubusercontent.com/5720791/139944086-da30abe5-3116-4938-9b4c-ea7eae3b4c02.png">

browse and edit,...
<img width="213" alt="Screen Shot 2021-11-02 at 1 04 28 PM" src="https://user-images.githubusercontent.com/5720791/139944167-52b048b1-f8f1-4c93-b403-5d2ad8bee59b.png">
... has an option....

<img width="827" alt="Screen Shot 2021-11-02 at 1 04 53 PM" src="https://user-images.githubusercontent.com/5720791/139944221-36bb00ba-d55d-4ced-8226-135f0a8b6c75.png">

to "autoload" any UUID-linked data when the core record loads.
