### ISSUE TITLE
Code Table Request - Collection Code = Hild

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4067]
**Goal**
Clean up code tables

**Context**
Hild does not have a definition - is any collection using it?

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcollection_cde

**Value**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcollection_cde#hild

**Definition**
If this term is not being used, I suggest we delete it. If it is being used, whoever is using it needs to provide a definition.

Note - this came from questions generated by an incoming collection.

**Comment by cjconroy** [comment]
I don't know what it means to be pending, but this likely refers to the Milton Hildebrand Anatomical Collection in MVZ, which is used.

**Comment by Jegelewicz** [comment]
@cjconroy thanks for that - I'll change the definition.
