### ISSUE TITLE
Cannot review or edit loan items for data loan?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4068]
Problem: I have a data loan where one loan item needs to be removed from the loan.
But when I go to Edit Loan Review Items - nothing shows up.
I can see all specimen results in loan - but that doesn't give me any tools to delete an item from the loan.
Help?
https://arctos.database.museum/loanItemReview.cfm?transaction_id=21121529

**Comment by campmlc** [comment]
![Screenshot 2021-11-03 11 09 10](https://user-images.githubusercontent.com/14808196/140131726-74db11d5-0eda-47cb-80bd-a75c803e4b2d.png)

**Comment by dustymc** [comment]
<img width="532" alt="Screen Shot 2021-11-03 at 10 19 12 AM" src="https://user-images.githubusercontent.com/5720791/140144880-da0de931-f924-4321-97e8-5b30da3a42d1.png">

**Comment by campmlc** [comment]
Perhaps for data loans there should be a link to this tool from Edit Loan?
