### ISSUE TITLE
APSU:Herp - remove leading zeros from catalog numbers

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4070]
The initial part of this issue was to resolve any catalog numbers that had leading zeros. Should we make moves on this so we can close this issue @Jegelewicz ?

_Originally posted by @gradyjt in https://github.com/ArctosDB/data-migration/issues/707#issuecomment-960107138_

**Comment by Jegelewicz** [comment]
@dustymc APSU:Herp wants to use integer catalog numbers, but their records were entered with leading zeros. Can you help us remove leading zeros so we can change over to integers?

**Comment by Jegelewicz** [comment]
Also - should this have happened? They have integer as their catalog number format. How could they enter stuff with leading zeros?

**Comment by gradyjt** [comment]
Just following up on this issue to see if there's anything I can do to help it get resolved. Thanks!

**Comment by dustymc** [comment]
@gradyjt should I make [redirects](https://handbook.arctosdb.org/documentation/redirect.html) for these or is it safe to just change them?

**Comment by gradyjt** [comment]
Seems like from the documentation it's safe to change them. We don't have anything dependent on the Arctos URLs as far as I know. That's the issue right?

**Comment by Jegelewicz** [comment]
Yep - not yet published to aggregators - so a change now is probably pretty safe.

**Comment by gradyjt** [comment]
Ok, sounds good to me!

**Comment by dustymc** [comment]
The update would result in a duplicate catalog number: Please do something to one of these, then I can proceed.

```

 cat_num 
---------
 06215
 6215

```

**Comment by gradyjt** [comment]
Good to go.

**Comment by dustymc** [comment]
Done - it'll take the cache a few minutes to catch up.

**Comment by Jegelewicz** [comment]
Woo hoo!!! Thanks!!!

**Comment by gradyjt** [comment]
Thank you Dusty!
