### ISSUE TITLE
how to find all the gridless tissue boxes?

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#4072]
Not a bug, but maybe helpful for others. 
We have tissues in containers that are not standard and will not fit in gridded boxes. We have un-gridded boxes for these, or the tissues go under the grid. All the ones I have seen are full. I have a few more to install, so I need to either find room, or start another box like this.  I would like to find all of them to check if they are full. If they are, then I will add some text to the box remarks or description to note that, or text to indicate some available room. How would one find all the tissue boxes in, say, MVZ Frz 3 that are blank in the field "rows" or "columns"?
Thanks.

**Comment by dustymc** [comment]
I don't have an immediate UI solution for this, but here's some SQL and CSV that might work until we can do better.

```
select barcode , getcontainerparentage(container_id) from container where institution_acronym ='MVZ' and container_type='freezer box' and number_rows is null;
```

[temp_mvznoposctr.csv.zip](https://github.com/ArctosDB/arctos/files/7489082/temp_mvznoposctr.csv.zip)

**Comment by cjconroy** [comment]
Awesome!  That's about the number of boxes I was hoping for.

**Comment by Jegelewicz** [comment]
Code preserved here - https://github.com/ArctosDB/documentation-wiki/blob/gh-pages/_sql_cheats/find_containers_without_positions.markdown
