### ISSUE TITLE
Find Collecting Events error

### ISSUE THREAD

**Issue by crcarter00** [ArctosDB/arctos#4075]
** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **

** Outages should be reported to the contacts listed at https://arctosdb.org/arctos-down/ **

** Arctos Documentation is http://handbook.arctosdb.org/ **

** Learn more about Arctos at https://arctosdb.org/ **

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **

**Comment by crcarter00** [comment]
Find Collecting Events error:
When opening new tab error message returned.
{"MESSAGE":"authorization failed","STATUS":"fail"}

**Comment by dustymc** [comment]
I need more information to be sure, but I think this was just Arctos being briefly overwhelmed with garbage traffic in which you got caught up. Please provide more information if this is still a problem.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/4078
