### ISSUE TITLE
Code Table Request - virtual container

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4076]
**Goal**
Add "virtual container" to container type

**Context**
All container types except unknown and legacy refer to actual, physical containers. I am requesting a virtual container to move missing or other containers into as a permanent or temporary basis -equivalent to UAM's parentless void, and MSBs DGRNONE. I have previously used legacy container or unknown for this, but new constraints have now made it impossible to scan items into legacy and unknown containers.

**Table**
https://arctos.database.museum/Admin/CodeTableEditor.cfm?action=editNoCollectionCode&tbl=ctcontainer_type

**Value**
virtual

**Definition**
A virtual container is a virtual entity to which objects and other containers can be scanned, generally as a temporary measure until a more permanent position is determined. It is not a physical container, merely serving as a temporary placeholder for containers in transition or containers whose actual location is undetermined.

***Priority**
[  Please choose a priority-label to the right.  ]

**Comment by mkoo** [comment]
looks like this is already added- welcome!
please close @campmlc!
