### ISSUE TITLE
Broken Link in How to Search for Specimens page (Handbook)

### ISSUE THREAD

**Issue by szaborac** [ArctosDB/arctos#4077]
** Arctos Documentation is http://handbook.arctosdb.org/ **
** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **

There is a broken link in the How to Search for Specimens page. 

To Repro:
1) From the Handbook Tutorial page https://handbook.arctosdb.org/how_to/How-to-Search-for-Specimens.html, go down to the Identification and Taxonomy section (just above Locality)
2) Click on the "How to Search for Specimens with Identification and Taxonomy" link
or 
use the URL: https://handbook.arctosdb.org/how_to/How_to_Search_for_Specimens_through_Identification_and_Taxonomy.html

Expected Result:  User should be brought to the appropriate How To page.

Actual Result:  404 error File Not Found.

**Comment by Jegelewicz** [comment]
fixed - thanks!

**Comment by szaborac** [comment]
Thank you!
