### ISSUE TITLE
error on locality search

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#4078]
**Describe the bug**
Cannot search for a locality (https://arctos.database.museum/place.cfm?sch=locality) and getting a weird error.
See below.
Priority high as georeferencers like @juliajchen cannot make tutorials or do her tasks

**To Reproduce**
1. Go to **Location->Find Locality**
2. Enter search terms and hit return
3. See weirdness below!

![Screen Shot 2021-11-04 at 5 15 07 PM](https://user-images.githubusercontent.com/2523089/140437938-a4d0e425-03e1-40cc-9f9c-fe10d22a93ec.png)
![Screen Shot 2021-11-04 at 5 14 58 PM](https://user-images.githubusercontent.com/2523089/140437944-4812c05a-84be-4ed3-98f7-774a22e1327f.png)

**Desktop (please complete the following information):**
PC Mac/ FF 
This was definitely working recently

**Comment by mkoo** [comment]
Also found the same error in #4075 
I dont know if we can blame this all on traffic? if so, then something is not clearing properly..... still an huge usability issue

**Comment by dustymc** [comment]
Thanks, found it! It's fixed, may be caching, should be cleared up within the hour. No, wasn't traffic, I think it was caching for me.

**Comment by mkoo** [comment]
woohoo- fixed!
go eat dinner @dustymc !
