### ISSUE TITLE
nonperson agent cleanup

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4079]
1. Is there any reason to retain the old 'Data Entry...' and 'Data Admin...' agents? These were part of a primitive VPD before VPDs existed in Oracle, they are not functional, I don't think they have any use, I'll delete them whenever I find this again if nobody has reason to keep them.

2. Attached are some non-person agents that a script detected. Most of them don't meet current guidelines and so are a bit likely to lead to duplicates and users not finding what they're looking for, but all non-person agents are relatively low quality. Please check formatting and add any relevant data.

[temp_np_a_p.csv.zip](https://github.com/ArctosDB/arctos/files/7486605/temp_np_a_p.csv.zip)

This can close when (1) is dealt with.

 @ebraker
 @mkoo
 @AJLinn
 @campmlc
 @amgunderson
 @dssikes
 @atrox10
 @cjconroy
 @jtgiermakowski
 @acdoll
 @jldunnum
 @jrdemboski
 @msbparasites
 @mlbowser
 @StefanieBond
 @catherpes,@catherpes
 @jandreslopez
 @zmsch
(18 rows)

**Comment by jtgiermakowski** [comment]
As far as 1. yes, i'd delete the Data Admin and similar. I don't see anything that i can solve or fix in 2.

**Comment by mkoo** [comment]
1. I'm also all for deleting those legacy/ unused data admin, data entry agents. Yes please!
2. thanks for the list and others can clean up or update if needed.

**Comment by jandreslopez** [comment]
On 2, how should we go about improving the agents linked to our
collections?  For UAM Fish and Invert I see a number of boats.  There is
value in preserving links collection holdings have to those boats.


________________________________________
Curator of Fishes / Associate Professor of Fisheries
University of Alaska Museum / College of Fisheries and Ocean Sciences
1962 Yukon Drive
Fairbanks, AK 99775
e-mail: ***@***.***; skype: j_andres_lopez
ph:  907 474 7828
fax: 907 474 1987
________________________________________

**Comment by AJLinn** [comment]
All organization agents listed for UAM:EH have been updated/improved.
I have no opinion on question 1 and so defer to others.

**Comment by mkoo** [comment]
you must mean one of these:
https://arctos.database.museum/agent/21282617

Just go in an edit if there's anything to add but this is clearly a vessel
(no need to tweak in my opinion) Very cool!

@dustymc why does the collection activity not list specific collections or
counts when I'm logged out?

[image: Firefox_Screenshot_2021-11-05T19-34-07.791Z.png]

**Comment by dustymc** [comment]
> improving the agents

That's the goal!

For non-person agents, I think all we're realistically going to get regarding the name itself is better documentation, but if some of that turns into something which can be implemented as rules or reports I'd be thrilled to do so.

Addresses (even eg "Seattle") and relationships are always useful (but I know most of these are legacy) - remarks is much less so.

**Maybe** "vessel" (or something of the sort) should even be a distinct agent type - boats (some of them, anyway) might have logs and such available; they're (sorta...) a different type of data than eg "LGL."

I see that we have things like ``R/V Boatname`` and ``MV Boatname`` and almost assuredly just ``Boatname``. I'd suggest spelling those out - ``Recreational Vehicle Boatname`` - but anything that adds standardization would be useful. If you have recommendations I'd be happy to help add them to the documentation (or you can).

https://handbook.arctosdb.org/documentation/agent.html#creating--maintaining-agents

**Comment by dustymc** [comment]
For https://arctos.database.museum/agent/21282617 

I added


<img width="405" alt="Screen Shot 2021-11-05 at 12 41 00 PM" src="https://user-images.githubusercontent.com/5720791/140569196-7ca578c0-3718-4f51-87b1-1cfe1558d342.png">

(functional data)

from 

<img width="428" alt="Screen Shot 2021-11-05 at 12 40 55 PM" src="https://user-images.githubusercontent.com/5720791/140569236-8da3ed94-16cf-4698-bb3b-e4fbcff26a31.png">

(not something that any script can make sense of).

>collection activity not list specific collections

Looks like the form is just busted - I'll fix it.
