### ISSUE TITLE
Verbatim localities failed to load

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4081]
Hey @Jegelewicz and/or @dustymc , I've looked into this issue now and I see that verbatim locality was included in the initial collecting event bulkload file, but in none of the records for ACCN 0002 in APSU:Herp does it appear. Do you know why this might be the case? How can I get the verbatim locality descriptor to show up? Thanks!

_Originally posted by @gradyjt in https://github.com/ArctosDB/data-migration/issues/1087#issuecomment-962149296_

**Comment by Jegelewicz** [comment]
@gradyjt can you provide the file you loaded?

**Comment by gradyjt** [comment]
This should be the file I initially bulkloaded, though of course I had to go through some iterations of fixes that you'll see come up if you load this file in the bulkloader. Let me know if you need anything else. 

[MemphisCollectingEventBulkloadTemplate3.csv](https://github.com/ArctosDB/arctos/files/7488628/MemphisCollectingEventBulkloadTemplate3.csv)

**Comment by dustymc** [comment]
Neato!

I fixed the event loader for next release and patched these verbatim localities in - let me know if something different needs to happen.

**Comment by Jegelewicz** [comment]
@gradyjt you are a real rock star!!!

**Comment by gradyjt** [comment]
Oh gosh, you're all makin me blush!

**Comment by gradyjt** [comment]
P.S. all looks good so far to me. Can re-open issue if I find something else in my QAQC
