### ISSUE TITLE
What is wrong? The error message was completely unhelpful. I downloaded the file with errors and there was nothing in it but the column headings. Reference: This message has been logged as 6E2300C1-E7F5-40F0-A0DCC6AA400E7994

### ISSUE THREAD

**Issue by hippyherpdude** [ArctosDB/arctos#4083]
** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **

** Outages should be reported to the contacts listed at https://arctosdb.org/arctos-down/ **

** Arctos Documentation is http://handbook.arctosdb.org/ **

** Learn more about Arctos at https://arctosdb.org/ **

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **

**Comment by dustymc** [comment]
I need the data to diagnose.

**Comment by hippyherpdude** [comment]
Peter S. Miller
Herpetology Collections Manager
Biology Collections Interpreter
***@***.***
206.920.9062
Burke Museum 
The Washington State Museum of Natural History and Culture
University of Washington
Seattle, WA 98105
Washington's oldest museum has become Washington's newest museum. www.burkemuseum.orgOn Nov 7, 2021, at 9:10 AM, dustymc ***@***.***> wrote:I need the data to diagnose.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Jegelewicz** [comment]
@hippyherpdude attachments do not work from email - please visit the issue in Github and attach the file. Thanks!

**Comment by hippyherpdude** [comment]
Never mind, I figured out how to work around a very unhelpful system and make it work. 

Peter S. Miller 🐢🐍🦎🐊

**Comment by Jegelewicz** [comment]
@hippyherpdude Maybe we can make it better if we know exactly what happened? What tool were you using? If you can provide the data too - then we can see if there is a way to make the system more helpful.
