### ISSUE TITLE
Code Table Request - new part preservation: acetone

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4085]
**Goal**
add appropriate preservation to ASUMZ:Inv parts

**Context**
They have stuff preserved in acetone

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_preservation

**Value**
acetone

**Definition** 
A colorless, highly volatile and flammable liquid with a characteristic pungent odour. <a href="https://en.wikipedia.org/wiki/Acetone" target="_blank">Wikipedia</a>

**Priority**
[  Please choose a priority-label to the right.  ]

**Comment by Jegelewicz** [comment]
Unsure of the influence on "tissue-ness" of acetone...

**Comment by campmlc** [comment]
Apparently OK?
https://pubmed.ncbi.nlm.nih.gov/10620236/

**Comment by Jegelewicz** [comment]
Code table admins say do it.

**Comment by Jegelewicz** [comment]
added
