### ISSUE TITLE
Code Table Request - New part preservation isopropanol, 70%

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4086]
**Goal**
Catalog ASUMZ:Inv records

**Context**
They have stuff preserved in 70% isopropanol

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_preservation

**Value**
isopropanol, 70%

**Definition**
No Influence | a solution that consists of 70% isopropyl alcohol and 30% water

**Priority**
[  Please choose a priority-label to the right.  ]

**Comment by campmlc** [comment]
I support adding these preservatives.

**Comment by Jegelewicz** [comment]
Code table admins say do it.

**Comment by Jegelewicz** [comment]
Added
