### ISSUE TITLE
Code Table Request - new ctaddress_type of 'Library of Congress'

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#4087]
**Goal**
Import names used in the MVZ Archives

**Context And Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctaddress_type
Currently we have specific fields for "external repositories to verify that we mean this guy and not that guy-- ORCID, Wikidata specifically. This would be another external catalog for names. (```URL``` really is reserved for personal websites and most of the people we want to load are historic)

**Value=**
new value: Library of Congress

**Definition=**
URL of the Library of Congress (LCCN) Permalink for a given person. Example: https://lccn.loc.gov/n50047914 for Barbara DeWolfe

**Action**: If there's agreement, I will add to the CT!

**Comment by dustymc** [comment]
Seems reasonable, but @ me with the final value when/if you add it - the UI has some datatype handling, this needs added to that.

**Comment by mkoo** [comment]
Poking the CT admins @Jegelewicz 
No objections? can I add?! thx for replies!

**Comment by Jegelewicz** [comment]
No objections here.

**Comment by mkoo** [comment]
Great!
Just added this to the CT @dustymc 
```
**Library of Congress**
Definition: URL of the Library of Congress (LCCN) Permalink for a given person. Provides name
 variants and links to known authorities. Example: https://lccn.loc.gov/n85282001 for Barbara DeWolfe
Available in public view.
```
thx

**Comment by dustymc** [comment]
>Available in public view.

That should really be part of the request; maybe we need to revise the template. I don't think this can be problematic, so done and done.

**Comment by mkoo** [comment]
Not sure I understand what you mean by "That should really be part of the request;"
Do you mean just " add to template" because I'm happy to edit the issue template, but also needs to be part of the definition for future users.
thanks!

**Comment by dustymc** [comment]
I just think we should be more explicit/up front for any agent-bits which will be made public. (And that requires some UI change, which is done for this.) I sorta think we should add "for addresses, will this be public?" to the template, but new address types are rare so maybe that's unnecessary clutter. Maybe just add a blurb to https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html??

**Comment by mkoo** [comment]
done and done

**Comment by ccicero** [comment]
@mkoo @dustymc Can this issue be closed? Seems like the only remaining part to the issue is "the UI has some datatype handling, this needs added to that" - has that been done?

**Comment by dustymc** [comment]
I close 'in next release' issues when the code goes out - but there's nothing to do here so whatever.

**Comment by ccicero** [comment]
So ok to close this issue then, correct?

**Comment by mkoo** [comment]
dusty will close when the code is public!
