### ISSUE TITLE
part cleanup: mount

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4091]
Data:
[temp_mnt(1).csv.zip](https://github.com/ArctosDB/arctos/files/7500843/temp_mnt.1.csv.zip)

Proposed Changes:

```
           part_name            | new_part_name | new_part_attr_type_1 | new_part_attr_val_1 | new_part_attr_type_2 | new_part_attr_val_2 |                new_part_remk_suffix                
--------------------------------+---------------+----------------------+---------------------+----------------------+---------------------+----------------------------------------------------
 body mount                     | body          | preservation         | mount               |                      |                     | Original part name: body mount
 skin, mounted                  | skin          | preservation         | mount               |                      |                     | Original part name: skin, mounted
 head mount                     | head          | preservation         | mount               |                      |                     | Original part name: head mount
 skull, mounted                 | skull         | preservation         | mount               |                      |                     | Original part name: skull, mounted
 skeleton, postcranial, mounted | skeleton      | preservation         | mount               | part modifier        | postcranial         | Original part name: skeleton, postcranial, mounted
 skeleton, mounted              | skeleton      | preservation         | mount               |                      |                     | Original part name: skeleton, mounted

```

Summary:

```

 guid_prefix | nrecs 
-------------+-------
 ACUNHC:Bird |    62
 ASNHC:Bird  |   152
 ASNHC:Mamm  |    73
 CHAS:Bird   |  1296
 CHAS:Herp   |     9
 CHAS:Mamm   |   238
 CHAS:Teach  |    69
 DMNS:Bird   |  2790
 DMNS:Herp   |     1
 DMNS:Mamm   |   440
 HMCM:Bird   |    13
 HMCM:Mamm   |     2
 MLZ:Bird    |     2
 MSB:Bird    |    18
 MSB:Mamm    |   106
 MVZ:Bird    |    12
 MVZ:Hild    |     1
 MVZ:Mamm    |     2
 NMMNH:Bird  |     9
 NMMNH:Herp  |     1
 NMMNH:Mamm  |    11
 NMMNH:Paleo |     2
 NMU:Bird    |     2
 NMU:Mamm    |     2
 OWU:Bird    |   532
 OWU:Mamm    |    38
 UAM:Bird    |     1
 UAM:Mamm    |    25
 UCM:Bird    |   533
 UCM:Fish    |     3
 UCM:Herp    |     1
 UCM:Mamm    |   141
 UCSC:Bird   |    52
 UCSC:Mamm   |     8
 UMNH:Bird   |   122
 UMNH:Herp   |     3
 UMNH:Mamm   |     2
 UMZM:Bird   |    67
 UMZM:Mamm   |    37
 UNR:Mamm    |     2
 UTEP:Bird   |     1
 UTEP:Mamm   |     4
 UTEP:Teach  |     1
 UWBM:Mamm   |    88
 UWYMV:Bird  |     1
 UWYMV:Mamm  |     1

```

Contacts:

 @ebraker
 @Nicole-Ridgwell-NMMNHS
 @mkoo
 @AJLinn
 @campmlc
 @ccicero
 @amgunderson
 @atrox10
 @mvzhuang
 @cjconroy
 @keg34
 @acdoll
 @jldunnum
 @jrdemboski
 @leet1984
 @ewommack
 @diannakrejsa
 @kderieg322079
 @catherpes,@catherpes
 @lin-fred
 @droberts49

Dependencies:

https://github.com/ArctosDB/arctos/issues/4090

I'll make this change around 2021-11-15 if there are no objections or better ideas.

**Comment by AJLinn** [comment]
The 52 items in UAM:EH are "exhibit mounts" which are not what I think you are talking about.
<img width="810" alt="Screen Shot 2021-11-08 at 2 33 20 PM" src="https://user-images.githubusercontent.com/17605945/140834902-13cf1a6f-0bec-4fa4-9537-fa8affabbf4e.png">
..
My comment in #4090 should clarify what my concern is with moving the current part name. They certainly would be misrepresented with the recommended action indicated in the code table above.
Please do not implement this change for the 52 exhibit mounts for EH objects. These are essential parts of our objects that are housed near the objects and are re-used for exhibits in house and for loans.

**Comment by Jegelewicz** [comment]
Maybe those part names should be changed to "exhibit mount" and given an appropriate definition.

**Comment by AJLinn** [comment]
I am happy to make that change. I think it would solve our issue/confusion.

**Comment by dustymc** [comment]
Definitely need a useful definition, I don't have much opinion on the part name but clarifying in the name itself seems somewhat useful at the moment.

I'll adjust and edit.

**Comment by mkoo** [comment]
do we have a definition for 'mount'?

**Comment by ewommack** [comment]
> do we have a definition for 'mount'?

I think most of us using it are vertebrate collections for preservation, but I wonder if might be different for plants or insects?
Also, I still do not understand fish mounts that well, but I guess they would fall under body with mount as a preservation?

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/4090
