### ISSUE TITLE
Ideas for literature "records" in Arctos

### ISSUE THREAD

**Issue by gradyjt** [ArctosDB/arctos#4092]
Hi all, setting up this issue to start a conversation based on my previous e-mail:

"...we're gearing up to try to reproduce our (APSU) TN herp biodiversity atlases online, but our original atlases included both specimen records (photos/audio and collections) and literature records. We're brainstorming how best to make our "website" code call data for both specimens (currently calling it from Arctos(!) and others) and literature records. Can I make a catalog number for a literature source in our Arctos database? I know you can link literature records to specimens but I wasn't sure if a publication itself could be a "specimen", if that makes sense."

If any of you have thoughts or questions about this project or want to tag others to contribute to this conversation I would be very grateful. Thank you!

**Comment by mkoo** [comment]
well, the cataloged record itself is just a species observation that happens to be documented in a publication. We have tonnes of those in our field notebooks, which is basically just an unpublished piece of 'literature'. Each of our species occurrences still have the bones (haha) of an occurrence that is vouchered by something physical- identification, observer (or collector), locality, date. 
The observation details are whatever is in the journal and we may cite how they identified the species (by sight, by call, etc)

Is that comparable to what you have in mind? So yes, you could have all your occurrences (specimens or observations from a publication) in Arctos and distinguish by item_type:
(https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcataloged_item_type)

**Comment by campmlc** [comment]
We also have cataloged records based on field ledger observations in our
MSB:Host portal. These are primarily records of host occurrences based on
verbatim IDs by a competent field biologist, associated with examination
for parasites. We record the observation as a cataloged record, which may
or may not have associated parasite records. That way we can search on the
host/ parasite associations across different taxonomic and geographic
parameters, and we can capture negative association and occurrence data as
well.

**Comment by dustymc** [comment]
This isn't enough information to say much. You can [catalog most anything](https://handbook.arctosdb.org/documentation/catalog.html#understanding-cataloged-items), but it's more work and comes with things that [must never be allowed to change or expire](https://handbook.arctosdb.org/documentation/catalog.html#guid-prefix) - there should be some institutional commitment involved.

You can certainly catalog information from Literature - I believe the UAMObs:Ento collection is basically that, because the structure is needed to support some sort of research.

If this is rare books that are important as objects, then cataloging them is almost certainly the best approach.

If it's nothing like any of that then Media or Publications might be most appropriate.

**Comment by gradyjt** [comment]
I think like Michelle and Teresa said these would be observations documented in literature, but I wondered if it would be wierd to catalog an observation that noone associated with our collections made. Should we be getting any kind of permission to catalog observations made by other people? Or is citing them as the "collecting" agent sufficient?

**Comment by Jegelewicz** [comment]
> citing them as the "collecting" agent sufficient

I would think that using the authors as identification agents would make more sense. I wouldn't create any "collectors" in this situation.

This might call for a new event type though and Darwin Core offers a clue - see [MaterialCitiation](https://dwc.tdwg.org/terms/#materialcitation)

**Comment by dustymc** [comment]
>would be wierd to catalog an observation that noone associated with our collections made

If the current data fails to do something you need (like exist!), then what else are you supposed to do?! I think that's essentially the rationale behind all similar catalogs - if the data are published in some useful way then you can just use that, but if they're not and you need them to be then  Arctos can facilitate.

**Comment by gradyjt** [comment]
Ok, Material citation makes sense to me so I think (like I believe Dusty is pointing out) it comes down to whether I want to keep just maintaining an excel file of literature records for each species or if I want a database within Arctos to draw from for our website. Maybe once I know our process a little better the decision will be more clear to me. Though if I catalog those literature records then I could have a link in the webpage to the Arctos page for that cataloged publication where there's a media file of the paper... (Many of the literature records would likely be hard to find online as they're very old or are publications for very small local journals, but someone someday could scan all the hard copies we have and link them in Arctos...). Am I following everyone you think?

**Comment by gradyjt** [comment]
Ok cool, thanks Teresa. I will add that to my to-do list.

**Comment by dustymc** [comment]
>literature records for each species 

That suggests something like https://arctos.database.museum/name/Acanthophthirius%20myotis

<img width="482" alt="Screen Shot 2021-11-09 at 8 09 53 AM" src="https://user-images.githubusercontent.com/5720791/140961085-121761de-d249-461a-af8e-762549a7c020.png">

(And Arctos Publications can carry the scans.)

**Comment by Jegelewicz** [comment]
I think she is actually talking about each species occurrence.

**Comment by AJLinn** [comment]
> If this is rare books that are important as objects, then cataloging them is almost certainly the best approach.

We have over 50 books of different kinds in our collection (https://arctos.database.museum/saved/Books). This might be a new issue or related to this one... but it would be important for us to figure out how we want to standardize their data fields. Anyone want to help me figure this out? Some of them might be useful for other collections (e.g., this book of pressed Alaska flowers https://arctos.database.museum/guid/UAM:EH:0619-5980).

**Comment by gradyjt** [comment]
> each species occurrence.

that is correct, sorry for my bad communication here

**Comment by Jegelewicz** [comment]
> has pages of pressed Alaskan flowers and plants

These could be cataloged as "specimens"!

> This might be a new issue or related to this one... but it would be important for us to figure out how we want to standardize their data fields. 

I think a new issue and perhaps we should be looking to libraries for some of this?

**Comment by gradyjt** [comment]
Good afternoon all, I have, in an awesome turn of events, been told that the reprint collection of our emeritus curator has already been scanned. Our biodiversity atlas reports records based on vouchered specimens and published literature observations so I would like a place that our code can pull both museum specimen data and literature observation data from easily. With my limited knowledge I see two paths: incorporate the literature records into our existing APSU:Herp database as observations and link the scanned publications as media. Or two, make a separate database like UAMObs:Ento did. I'm not sure what the benefits/drawbacks are of doing one over the other, thoughts? Also, my curator is concerned that uploading and making sharable the scanned journal/newspaper articles in Arctos might violate some copyright laws, etc? Anybody have any experience with this? Thanks!

**Comment by Jegelewicz** [comment]
@gradyjt maybe @camwebb at UAM would be someone to check with. It's not the same as his project, but the linking up with things outside of Arctos is something he might be able to help you think about.

**Comment by dustymc** [comment]
>benefits/drawbacks are of doing one over the other,

Essentially, metadata. With Media you have directly available some [relationships](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctmedia_relationship) and [labels](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctmedia_label), and that's about the extent of the model. Catalog records incorporate things like identifications (complex data objects that include things like taxonomy, publications, agents, etc.), and are capable of carrying more, and more structured, data.

Which one is more correct comes back to the usual question, who cares? If you're trying to document "Occurrences" through newspaper articles, you probably need catalog records. (I think this is what UAMOBS:Ento is up to, they're looking for things like species distributions which need place/time and taxonomy and such, and catalog records are the data objects which can carry that information.) If you just need a data object to reference from things like existing catalog records, then Media might be appropriate.

In either case you'll need to create Media; that's the data object which links "things at URLs" to "things in Arctos." From there, I think you might be looking at two paths:

1. for "records based on vouchered specimens" you can create a Publication, link the Media to it, and then link the Publication to the catalog record through a Citation.
2. For "published literature observations" you can create a catalog record and then do all the things you'd do for any other catalog record. This could be in a new collection, that's totally administrative and up to you, and it wouldn't have to happen immediately (eg if you don't have the resources) - you could just "upgrade" Media records when it's useful to do so.

**Comment by dustymc** [comment]
Happy?

**Comment by gradyjt** [comment]
I really don't know. I have so many fires burning right now and haven't had time to learn more about this and make decisions. If it happens it will likely be far down the road and hopefully I'll remember and find this issue...?
