### ISSUE TITLE
add as reference North American Culture map

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#4093]
@AJLinn referenced a Culture map for North America a few years ago. Do you have a source/authority for that, specifically one with GIS data? Preferably one with global coverage? I'm thinking it's a good idea to add as an optional basemap to Berkeley Mapper so you can see records mapped with respect to the geographic culture map. Valuable for the biological as well as cultural collections.

**Comment by AJLinn** [comment]
This is probably the best map that indicates Indigenous lands in North America. I wonder if it might be useful?
https://native-land.ca/

**Comment by mkoo** [comment]
oh yea I saw a presentation last year (or was it 2?) and now I see there's
an API!
thanks for the tip and will check it out more....

**Comment by AJLinn** [comment]
Cool, now I see it's not just North America but all around the world. Awesome...should be useful for contemporary culture collections from everywhere!
