### ISSUE TITLE
add attribute at time of add part

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#4099]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
I used to add single parts like "tissue (frozen)". Now I need to add attribute frozen in separate interface. 

**Describe what you're trying to accomplish** 
Would like to add attribute at same time as add part

**Describe the solution you'd like**
Add attribute in the interfaces in the pictures attached. 

**Describe alternatives you've considered**
There seems to be only 1. bulk load, or 2. go back to the part after adding and edit the attribute. 

**Additional context**
My workflow is not always straightforward. Many times parts like tissues are added after the body has been cataloged and put away. Cleaning up these dribs and drabs would go faster if we could add the attribute at the same time, or even in bulk through the modify parts interface. 

**Priority**
Medium. I can still do my job, but this would speed things up.

**Comment by cjconroy** [comment]
Whoops, forgot attachments. 
<img width="890" alt="Screen Shot 2021-11-09 at 2 36 27 PM" src="https://user-images.githubusercontent.com/5749672/141016828-588c084f-3e1c-4160-869c-bc0b0b083009.png">
<img width="530" alt="Screen Shot 2021-11-09 at 2 36 05 PM" src="https://user-images.githubusercontent.com/5749672/141016830-d11e8828-c77c-47fb-9f4a-807aeb7777ce.png">
<img width="878" alt="Screen Shot 2021-11-09 at 2 32 02 PM" src="https://user-images.githubusercontent.com/5749672/141016832-e5a5f33d-b1cc-4fb7-9c5f-a25694e305a9.png">

**Comment by Jegelewicz** [comment]
@cjconroy you can add part attributes using the Part Attribute Bulkload Tool - https://arctos.database.museum/tools/BulkloadSpecimenPartAttribute.cfm

I have started loading my parts after the rest of the record is loaded, because you can also load the attributes along with the parts in the Part Bulkload Tool - https://arctos.database.museum/tools/BulkloadParts.cfm

**Comment by Jegelewicz** [comment]
See also #3759

**Comment by cjconroy** [comment]
I've used those other interfaces, but wondeing if the current add part interfaces will have attribute options.

**Comment by Jegelewicz** [comment]
That is the thing #3759 is asking for. Please indicate your wish for it there too!

**Comment by cjconroy** [comment]
can anyone see the typo in my attached file?  Struggling just to add preservation of frozen to a set of tissues that we loaded. 
I am using a template of a spreadsheet that was successful a couple of weeks ago. In that file I had a header "attribute_type" but I see the template now only has "attribute". I keep getting the error "Detail: psql:/usr/local/webroot/temp/excopy_voleguy_20211110011147529_614.sql:1: ERROR: column "part_id" of relation "cf_temp_attributes" does not exist"

[15055tissueattributes.csv](https://github.com/ArctosDB/arctos/files/7515558/15055tissueattributes.csv)

**Comment by dustymc** [comment]
I think you're in the wrong form (unless there's a typo somewhere, but I don't think so) - cf_temp_attributes is specimen attributes, you need part attributes.

**Comment by Jegelewicz** [comment]
@cjconroy the template gives me these fields:

part_id | guid | barcode | part_name | attribute_type | attribute_value | attribute_units | determined_date | determiner | remark | attribute_method
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

So I think you still need attribute_type

**Comment by cjconroy** [comment]
OK, got it. Works. The pathway to find the program is not where I expected it. But, found under parts. Maybe the first Attributes under Batch Tools could say Specimen Attributes, not just Attributes?

**Comment by Jegelewicz** [comment]
Changed to "Record Attributes".

**Comment by Jegelewicz** [comment]
Closed as duplicate of #3759
