### ISSUE TITLE
project taxonomy: add enhancements

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ArctosDB/arctos#410]
```
1) Add comment to each taxon name (for things like introduced, etc.)
2) Add display table for
--sort_by (order, family, alpha)
--display_by_sort (list, or blocks with headings)
--include_images_fg
--include_common_fg
--include_author_fg
--include_synonyms_fg
--include_full_taxonomy_fg

```

Original issue reported on code.google.com by `dust...@gmail.com` on 13 Feb 2010 at 2:38

**Comment by dustymc** [comment]
Very low priority - not clear that anyone is using this.

**Comment by Jegelewicz** [comment]
@dustymc I say we close this - all this stuff is probably discussed many times over in other issues or is now not relevant?
