### ISSUE TITLE
[CONTACT: Blocked Network]

### ISSUE THREAD

**Issue by Joshua-Anderson-Molec** [ArctosDB/arctos#4100]
restricted IP: 162.247.87.182

Hello, 
I am a Graduate student at Georgia Southern University working on cestode infections of Sorex shrews with Dr. Stephen Greiman. I need access to the mammal database for UNCG (Dr. McLean) in order to collect the host data for my master's thesis. If you need more information from me please feel free to contact me at anderjos000@gmail.com.

Thank you,
Joshua Anderson

**Comment by dustymc** [comment]
released
