### ISSUE TITLE
Arctos Down - Sunday November 28th 2021

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#4103]
Network Maintenance Sunday November 28th 2021
From: Mark Brueschke
Network maintenance will be carried out between 10:00 AM and 4:00 PM (CST) on Sunday, November 28. Access to all TACC systems will be unavailable during this time. Jobs will continue to run, but users will have no access to TACC services and systems until the upgrade is complete.

## Planned Outage
 - Date and time outage will begin: 1000 CST
 - Date and time outage is expected to end: 1600 CST
 - Reason for outage: TACC network maintenance
 - Expected behavior during and after the outage: not sure

## Communication before/during outage
- [x] Pin this issue
- [x] Banner updated @jegelewicz 
- [x] Email sent to AWG @ewommack 
- [x] Email sent to Arctos Google Group @ewommack 
- [x] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [x] Unpin this issue
- [x] Banner updated @jegelewicz
- [ ] Email sent to AWG @ewommack
- [ ] Email sent to Arctos Google Group @ewommack
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by ewommack** [comment]
I scheduled the email send for 0800 on the 17th of November (before the USA holiday).

**Comment by lin-fred** [comment]
tweet for schedule:

#ArctosStatus Arctos will experience an outage on for TACC network maintenance between 10:00 AM and 4:00 PM (CST) on Sunday, November 28th.

**Comment by lin-fred** [comment]
this will be an interruption in some way?

**Comment by ewommack** [comment]
As far as I understand it all of TACC will be down for maintenance, and so Arctos will be down as well.

**Comment by Jegelewicz** [comment]
@lin-fred suggest the following:

TACC network maintenance will be carried out between 10:00 AM and 4:00 PM (CST) on Sunday, November 28. Arctos will be unavailable during this time.

**Comment by Jegelewicz** [comment]
Banner expires today.

**Comment by Jegelewicz** [comment]
I don't hink we need to email everyone or tweet anything - closing.
