### ISSUE TITLE
Related Record Summary in Catalog Record results not working

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4104]
This has come up again in conversations with GloBI - we have the ability to download related item taxa, but the search results are not working, instead just coming up as "null"
For example, do search on all Family Sciuridae in Arctos with relationship "host of". Attempt to check RelatedRecordSummary in search results add/remove data fields. Value is null even though related records exist.
@dustymc @Jegelewicz @acdoll

**Comment by campmlc** [comment]
This is one of the most important tools we have in Arctos - would be good to make this work.

**Comment by Jegelewicz** [comment]
@campmlc try checking relateditems

**Comment by Jegelewicz** [comment]
But, what is RelatedRecordSummary supposed to do?

**Comment by campmlc** [comment]
Related items gives the urls of the related catnums only. Relatedrecord
summary replaced related item ID, I believe to give the identification of
the related objects. This would likely be a string since there can be more
than one, eg multiple parasite taxa? We never really resolved this
functionality, but it is crucial to get a downloadable column of taxa the
record is related to, eg for host parasites. This used to work in Oracle,
but them the searches started failing due to timeouts and we discussed
building caches.

**Comment by Jegelewicz** [comment]
Who outside of Arctos would know that? relateditems vs. RelatedRecordSummary means nothing at all. I don't have a solution - but I think it is something we should mull over...

**Comment by campmlc** [comment]
Yes, no one knows how to use these tools even when they work. I'd like to
get the search results working before I can do any promotion.

**Comment by dustymc** [comment]
can't replicate
