### ISSUE TITLE
Feature Request - Add address to Agent Bulkloader

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#4109]
Specifically we want to bulkload agents with their address types of wikidata, github, and the new library of congress (basically links to external authorities and other db).

Possible?

**Comment by dustymc** [comment]
I'm hesitant to add that complexity to the agent bulkloader, but a stand-alone address loader would be straightforward. That work for you?

**Comment by mkoo** [comment]
I think that would be fantastic!

**Comment by mkoo** [comment]
That works too. Standalone bulkloader for existing agents!
A critical tool for new and existing collections.

**Comment by ewommack** [comment]
Suggestions from AWG Issue meeting: add the following to the Agent Bulkloader form
Address, 
status dates, 
relationship (but the agent you are creating a relationship to would have to already exist), 
URLs (are addresses)

**Comment by Jegelewicz** [comment]
AWG says add addresses to bulkload tool. Agree that relationships are better left for agents already in Arctos,. So, add addresses to the current agent bulkload tool and then create a second tool for adding information (names, addresses, statuses, and relationships) to existing agents.

**Comment by mkoo** [comment]
What's the status of being able to add address_type to the bulkloading file for creating new agents?
We would like to proceed with adding ca, 100 new agents with the address_type of Library of Congress.

**Comment by dustymc** [comment]
Buried at the moment. Prioritize this, or send me something from which I can find agent_id and enough info to create the address and I can SQL them in.

**Comment by mkoo** [comment]
that works. We will upload and create the agents and send you a csv with
the LOC address.... can be the basis of a bulkloading tool one day

**Comment by dustymc** [comment]
Per Issues meeting added address to the primary bulkloader. New Issue if a dedicated address loader is necessary.
