### ISSUE TITLE
Code Table Request - add IsoBank as another identifier

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#4110]
**Goal**
Connect Arctos records with IsoBank records.

**Context**
IsoBank is now up and running. There is still a lot more work to be done on the backend to make it less clunky (both in terms of uploading and searching data), but there are currently 34 Arctos records in IsoBank (thanks @ewommack for being a tester!). As we receive new requests for specimens to be used in isotopic analyses, we want users to upload their records to IsoBank so that we can link to the isotopic values.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type

**Value**
IsoBank

**Definition**
A project-based data archive (https://isobank.org) that allows researchers to store and organize, share, and distribute isotopic data.

**Collection type**
N/A

**Attribute data type**
N/A

**Attribute value**
N/A

**Attribute units**
N/A

**Other ID BaseURL**
1. "Base URL" with which to prepend entered values, and  
2. A functional example URL, which should consist of the base URL provided in (1) plus a relevant value.  ]

1. https://isobank.tacc.utexas.edu/analyses/analysis_detail
2.  https://isobank.tacc.utexas.edu/analyses/analysis_detail/1447/

**ID_References**
N/A

**Priority**
High - best to implement soon so we don't get too far behind in trying to make these connections

**Comment by campmlc** [comment]
I support this.

**Comment by dustymc** [comment]
Question: Is there (or will there be) only one kind of THING in Isobank? The example URL (https://isobank.tacc.utexas.edu/analyses/analysis_detail/1447/) makes me think that may be one of many - there is/will be something other than "analyses" and/or "analysis_detail" included in Isobank.

I'm trying to avoid what we've done with GenBank: our "GenBank" IDs should really be something like "Nucleotide," and now we have a bunch of other stuff - ``NCBI Biosample`` for example - that are also "GenBank" but not identifier type ``GenBank``.

**Comment by Jegelewicz** [comment]
![image](https://user-images.githubusercontent.com/5725767/141845110-2a08f123-380f-43a5-acb3-874edf6710aa.png)

IsoBank calls it "ISOBank Number. Suggest the ID be

ISOBank Number

I think the definition needs to be about the identifier. Suggest

Number assigned by IsoBank. A project-based data archive (https://isobank.org) that allows researchers to store and organize, share, and distribute isotopic data.

**Comment by dustymc** [comment]
>Number assigned by IsoBank. 

If IsoBank only assigns one number then I'd expect https://isobank.tacc.utexas.edu/1447 to do something more interesting than it does; that might mean they're just complicated URL aficionados, or it might mean they do or plan to assign or resolve other kinds of "numbers" in which case have a more explicit identifier in Arctos probably makes sense.

SAMN05880647 is a "number assigned by GenBank" but that's not enough to get you anywhere useful - you need to know more to make anything happen.

**Comment by ccicero** [comment]
I am fine with Teresa's suggested modification to make it about the IsoBank Number, that makes sense to me.

As far as I know, IsoBank only assigns one number to the products of isotopic analyses (thus the 'analyses' part of the URL) and that is what we want to link. I don't expect that will change, but that is a question to confirm with Chris Jordan. In any case, if we make the identifier 'IsoBank Number' then it doesn't preclude something else.

**Comment by mkoo** [comment]
What Carla said. Who will confirm with Chris J with assumption of 1:1 Isobank Number:analysis?

Otherwise 'IsoBank Number' addition is great

**Comment by dustymc** [comment]
I sent Chris email.

"IsoBank Number" doesn't pair with https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type#genbank very well, but whatever....

**Comment by ccicero** [comment]
Message from Chris J.: "There are two relevant “items” for IsoBank/Arctos collections - the “analysis” and the “dataset”. A “dataset” is just a group of the former that are uploaded as a batch, but I don’t know what the right thing to link from Arctos is - probably just “one or more analyses” and these are the natural items to reference...since really all that IsoBank is doing is collecting a bunch of analyses together with relevant metadata"

Conclusion with which @dustymc agrees: The analysis - which is at the individual specimen level - is what makes sense for linking to/from Arctos. 

Dusty suggests "IsoBank" as the name of the Arctos Other ID (it matches "GenBank" - https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type#genbank).

Create the identifier in Arctos using "https://isobank.tacc.utexas.edu/analyses/analysis_detail/" as the base, and we can change it later if needed.

**Comment by Jegelewicz** [comment]
This has been added.
