### ISSUE TITLE
Marine invert collections - LORAN

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4111]
@kmkocot @sharpphyl just in case you haven't seen this.

Folks,

As part of two NSF TCN programs focusing on digitizing non-mollusk marine invertebrates and mollusks of the US eastern seaboard, we are carrying out a large-scale digitization project involving benthic samples from off South Carolina. These were taken by dredge from a ship moving steadily offshore along a LORAN line. LORAN was a radio-wave-based navigation system (LORAN-A, which developed in to LORAN-C) that allowed navigators to zero in on land-based transmitters and triangulate their position. It pre-dated the widespread availability of satellite data (it predated satellites, to be accurate) and was gradually phased out once GPS came along.
I'm interested to learn how many collection records cite LORAN and thus assessing whether digitizing the entire line network would be worthwhile for georeferencing projects like ours. Chirp up if your databases do or don't mention LORAN.

Paul Callomon
Collection Manager, Malacology and General Invertebrates
________________________________
Academy of Natural Sciences of Drexel University

**Comment by dustymc** [comment]
Most marine GPSs will convert to LORAN - someone like Garmin might have a conversion tool.

**Comment by sharpphyl** [comment]
Where is the original request from Paul?  I can let him know that, to my knowledge, DMNS:Inv does not have any collection records that cite LORAN.

**Comment by Jegelewicz** [comment]
@sharpphyl it was on NHColl
