### ISSUE TITLE
verification status needs clarification - accepted

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4115]
For verification status – who is doing the verifying?  I am confused because the description talks about checking against information available from Arctos and for a new record, what information would be available to check in Arctos?  What would be the difference then between accepted and verified?

_Originally posted by @hkevans in https://github.com/ArctosDB/data-migration/issues/915#issuecomment-970677637_

**Comment by Jegelewicz** [comment]
Currently, the [accepted](https://arctos.database.museum/info/ctDocumentation.cfm?table=CTVERIFICATIONSTATUS#accepted) value in verification status has this definition:

> The place and time information as entered was checked and determined to be correct against the information available from Arctos; original data were not consulted, and transcription or omission errors are possible.

Available from Arctos? I am doing data entry, there is no data available in Arctos!

Suggest we make this definition more consistent with the definition of unaccepted and change it to:

_The place and time information as entered was reviewed and determined to be correct, or more correct or complete than other available data. Transcription or omission errors are possible._

**Comment by dustymc** [comment]
>who is doing the verifying

specimen_event.verified_by_agent_id

The intent behind "in Arctos" does not align with "other available data" - the collector's notes (on an 8" floppy in DB2 allegedly in some file cabinet) is "available" but not necessarily considered for this. That should be consulted before "verified and locked" is used. The specific terminology can be discussed, but the meaning should not change.

**Comment by campmlc** [comment]
Sounds good.

**Comment by Jegelewicz** [comment]
Code Table committee says change to suggested definition.

**Comment by dustymc** [comment]
I don't believe that changing the meaning of existing data is within the purview of the Code Table committee; this should be reviewed by the affected collections.

**Comment by Jegelewicz** [comment]
Will bring to AWG Issue meeting.

**Comment by Jegelewicz** [comment]
Added to AWG issues agenda 2021-12-02

**Comment by Jegelewicz** [comment]
Need to write better definitions for this and verified and locked. @ArctosDB/arctos-code-table-administrators

**Comment by mkoo** [comment]
@mkoo and @ccicero will edit the definition and submit for review

**Comment by mkoo** [comment]
here's our new definitions for verificationstatus:

| ctvalue | definition |
|--------|--------------------|
| **accepted**  |  Information on the place and time of the event was checked by curatorial staff and determined to be correct using the best available resources, including original data. The data have not been verified by the collector or maker. Transcription or omission errors may still be possible. |
| **unaccepted** | Information on the place and time of the event was reviewed and determined to be incorrect or incomplete or represents data that are less correct compared to other available data.|
| **unverified** _(no changes)_ |  No assertion regarding the accuracy of the place and time of the event is made. |
| **verified and locked** |  Information on the place and time of the event was checked with original source material or experts. This may include verifying information with the collector or maker, or checking original labels, field notebooks, collector itineraries, and associated digital data. All information is determined to be correct and accurate. This value LOCKS linked Locality and Event data. (Edits can only be made after changing this status, and should be made only with more authoritative data.) |


File your comments; if everyone approves, I can update the ct table with these new definitions.

**Comment by mkoo** [comment]
updated pending no further objections!
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctverificationstatus
Open a new issue if you want tweaks
