### ISSUE TITLE
Add the Use Agent/Date button for mammal add measurements interface

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#4116]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
Slight time saver. I sometimes add mammal standard measurements to records. There is a button on the attributes screen for adding a single attribute to load in the agent and date for the earlier attribute, e.g. sex. 

**Describe what you're trying to accomplish** 
IF this button were added on the row for the 5 standard mammal measures, it would usually one click to populate two fields. Currently, it means triple clicking on date, copy, paste, triple click on agent, copy, paste. 

**Describe the solution you'd like**
Add that button to next to the row with standard mammal measures. 

**Additional context**
The existing attribute for recent specimens is good, but many thousands of old records have a made up date from ~2005 and agent of Museum of Vertebrate Zoology. In those cases, I put the correct date and agent into that attribute. Would be nice to somehow clean that junk up. The agent should be the collector or preparator if there is one, and the date should be the event date. That would be much closer to reality than 2005 for a specimen from 1908. 
[use agentdate.pdf](https://github.com/ArctosDB/arctos/files/7550448/use.agentdate.pdf)
 

**Priority**
Medium. I can still do my job.

**Comment by lin-fred** [comment]
![image](https://user-images.githubusercontent.com/19802479/184014030-bffb7094-9e96-4da5-aa13-fb18a0779942.png)
Is this what you mean?

**Comment by lin-fred** [comment]
@cjconroy if you could give us a screenshot of where exactly you are wanting a button that would be helpful!

**Comment by cjconroy** [comment]
It looks like it has already been added, as shown in the screenshot. Thanks.
