### ISSUE TITLE
Bulkloader doesn't like my UTMs

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#4118]
In bulkloader, I get this error: Error and units, datum, and georeference source and protocol must be accompanied by coordinates.
[https://arctos.database.museum/DataEntry.cfm?action=edit&ImAGod=yes&collection_object_id=97737272](https://arctos.database.museum/DataEntry.cfm?action=edit&ImAGod=yes&collection_object_id=97737272)

I have entered UTM coordinates and all the required field. 
Note: I entered these through the new data entry form and upon my first save, it didn't save the coordinates - I had to re-enter them after I had first set them to load in the Browse and Edit page. Looking at the data entry form now, I see that upon selecting UTM as the Coordinate Units, I am not given the option to enter the UTM Zone.

**Comment by dustymc** [comment]
See https://github.com/ArctosDB/arctos/issues/2660 (and a few more) - I need tools (and Chris is on vacation this week).

**Comment by acdoll** [comment]
I'll just enter decimal degrees - the UTMs are in the verbatim locality. Just wanted you to know in case it was some other type of issue. Thanks @dustymc
