### ISSUE TITLE
Need condition added to parts table download

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4119]
Request that part condition be added to the parts table download. 
This is useful in general, but especially so since in order to create part subsamples using the new bulkload parts tool, part condition is a required field. I'd like to have the condition of the subsample be the same as the condition of the parent part, but I have no way of knowing this without looking it up one at a time.
Ultimately, we need some way of integrating condition with the check container field in object tracking - currently these are two independent means of recording the condition related to a part. But that is another issue.

Priority: high - I have multiple large loans that need to have subsamples bulkloaded and barcodes assigned to the subsamples.

**Comment by Jegelewicz** [comment]
@dustymc I only added next task to get your attention - seems like this might be fairly straightforward and useful?

> part condition be added to the parts table download.

**Comment by dustymc** [comment]
>next task

Yea, I can do that.

>condition of the subsample be the same as the condition of the parent part

Why not just use the parents? Anything else looks like more work for worse data.

>check container field in object tracking

So just use that instead?

Happy to help with new SQL, or I can just add it to the table.

**Comment by campmlc** [comment]
Not sure what you mean about " use the parents"? I'm creating a barcodes
subsample which should have the same condition as  the parent tube unless I
specify otherwise, but I have no way of getting the parent tube condition
currently in a bulk download.

**Comment by dustymc** [comment]
> what you mean 

There's a relationship that can be queried.

```

select
    coll_object.condition,
    ppco.condition as parent_condition
from
    specimen_part
    inner join coll_object on specimen_part.collection_object_id=coll_object.collection_object_id
    left outer join specimen_part pp on specimen_part.sampled_from_obj_id=pp.collection_object_id
    left outer join coll_object ppco on pp.collection_object_id=ppco.collection_object_id
where specimen_part.sampled_from_obj_id is not null limit 10;


 condition | parent_condition 
-----------+------------------
 3         | 3
 unchecked | unchecked
 2         | 2
 3         | 3
 3         | 3
 4         | 4
 0         | 0
 0         | 0
 0         | 0
 good      | unchecked
(10 rows)

```

> have no way of getting the parent tube condition currently in a bulk download

That's what I'm offering to do, but I'm not sure if it's relevant - https://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html#issue-protips

>should have the same condition as  the parent tube

That's why I'm not sure what you asked for is what's really needed - I suspect this isn't the case, that the tiny piece of meat going into a warm tube is measurably different than the bigger hunk of meat that never leaves the cold tube. (But there is a relationship, the subsample is never going to be better than the parent; using inheritance would serve as a checksum against that being erroneously asserted too.)

Anyway, adding condition isn't difficult and I can just do that if it's what you need.

**Comment by dustymc** [comment]
Added condition, going next release, just toggle that to something else if there's any desire to explore other options.

**Comment by campmlc** [comment]
I agree that the condition should somehow include the change in condition related to the act of subsampling the tube. But unfortunately, the information is currently only available subjectively by looking to see how many times a sample has been loaned. It also requires knowing the original condition of the sample - flash frozen in LN2? dead in trap and then stuck in fridge for three days prior to freezing at -20C?  and also knowing the loan process -e.g. this sample was cut on LN2 and only defrosted for 2 min or the length of time required to chip off a frozen piece, etc.  Our current system fails to capture any of this, and is largely inaccurate and or completely misleading. However, in this case, the information is being required by a tool to create a subsample. So either we use the existing info and just copy over, with the option of making a change or not, or I enter "unchecked" which is equally useless.
Right now we have three different ways of assessing condition - the "condition" field, which is free text, the tissue condition part attribute, which is a numeric field, and the container check condition info that I can record in object tracking check container. It would good to have some way to integrate/standardize this, so that for example if I do a container check on x date, that my remarks show up in the part condition field or under "history" on the catalog record/edit parts screen. But that will require significant community input and discussion, probably a new committee. In the meantime, I would like the existing tools to be modified so that we can streamline existing workflows to make it easier for users to capture these data.

**Comment by dustymc** [comment]
>knowing the original condition of the sample ... dead in trap

I see that as a social problem - containers are anything, you can stick barcodes on your traps and scan them into your (barcoded, of course) local weather station that covers the trapline and writes to container_environment as often as your satphone will let it and start event_date when your trap trip sensor fires, I don't think there's anything fundamental that would need to change in Arctos to accommodate all of that today. (And "sampling environment" could be more of the same.)

More realistically, you could convert field notes to event attributes or something - it's not the same level of information, but it might get at vague ideas of initial potential quality.

I'm definitely not suggesting I think that's remotely feasible, I just don't think it's an Arctos problem at this point. (I suppose that makes it an administrator problem - nothing a whole lot of $$ couldn't fix....)

>the "condition" field

This is the default. Were I managing a bunch of barcoded freezers, I'd like to think that this would contain only "These aren't the ~~droids~~ data you're looking for" unless there was some obvious outlier ("this stinks," "a subsample of this didn't produce DNA," etc.). I'm not sure how that aligns with reality....

>tissue condition part attribute,

Presumably anyone using that has some idea of what it does. 

>container check condition info 

Yes using it for the kinds of things I was imagining when I generalized the "fluid" model needs development, I'm not sure what kind of resource it would take to do that while simultaneously doing all the stuff we decided to do with part attributes, but I'd guess it's closer to "proposal" than "committee."

ANYWAY, I can immediately expose "parent's condition" if that's somehow useful, and part condition is still in the download for next release.
