### ISSUE TITLE
Arctos Media Metadata Error

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#4120]
# Error Text
When trying to load a media metadata bulkloader, I kept receiving the following error:
![image](https://user-images.githubusercontent.com/11336485/142454905-cf64894a-cde7-49a0-94d9-3d6d8c08d8ec.png)

# Steps to get there
https://arctos.database.museum/tools/BulkloadMedia.cfm
I load media regularly, and copy my previously successful bulkloader templates to populate new metadata, so I knew there wasn't a formatting error with the headers indicated in the error message.

# Solution
Turns out "status" column is required to load media bulkloader.  After multiple unsuccessful attempts, adding this column with no other formatting changes allowed upload of my template. Suggest: change documentation to status = yes [required]

![image](https://user-images.githubusercontent.com/11336485/142455840-fc9ff16c-4fea-4d30-a664-6e44aa511022.png)

**Comment by dustymc** [comment]
Data please

**Comment by ebraker** [comment]
It's already loaded.  But here you go.
[TACC_media_metadata_2021-11-17.csv](https://github.com/ArctosDB/arctos/files/7564523/TACC_media_metadata_2021-11-17.csv)

**Comment by dustymc** [comment]
Thanks - I just need something to figure out what's going on in test, using the actual "something" that's being weird is sometimes illuminating.

**Comment by dustymc** [comment]
I can't replicate this. I think perhaps you had a NULL column name (eg header ends with comma, or two commas somewhere in the middle) but that's not in these data and the error logs for uploads are very minimal so I'm not sure of that.

**Comment by ebraker** [comment]
I don't think so - I use a text editor before I load to remove  null columns. Did you try loading without the empty 'status' column? I really think that is it.

**Comment by dustymc** [comment]
Yes, I was able to load with NULL status and without status at all. This loaded fine for me

[TACC_media_metadata_2021-11-17 - Sheet1.csv.zip](https://github.com/ArctosDB/arctos/files/7565583/TACC_media_metadata_2021-11-17.-.Sheet1.csv.zip)

http://test.arctos.database.museum/tools/BulkloadMedia.cfm

**Comment by ebraker** [comment]
Weird. Ah well. Closing.

**Comment by Jegelewicz** [comment]
I experienced this same behavior, but I cannot find the issue where I brought it up. I don't think it was the media bulkloader, but one of the other tools....

**Comment by Jegelewicz** [comment]
Found it! https://github.com/ArctosDB/arctos/issues/3747
