### ISSUE TITLE
URGENT: Arctos isn't working - I haven't been able to connect for at least 15 minutes

### ISSUE THREAD

**Issue by atrox10** [ArctosDB/arctos#4125]
Please complete to the best of your ability.
Arctos stopped working around 2 pm Nov 17 (pacific time).
Queries aren't responding, just keeps trying to connect. I tried this on Safari and Chrome from my MacBook.
Carla and Michelle also tried from their houses (on PC and Macs) and also just get the spinning wheel.
Help!

## Unplanned Outage
 - Date and time outage began: 
 - Date and time outage is expected to end:
 - Reason for outage:
 - Expected behavior during and after the outage:

## Planned Outage
 - Date and time outage will begin:
 - Date and time outage is expected to end:
 - Reason for outage:
 - Expected behavior during and after the outage:

## Communication before/during outage
- [x] Pin this issue
- [x] Banner updated @jegelewicz 
- [x] Email sent to AWG @ewommack 
- [x] Email sent to Arctos Google Group @ewommack 
- [x] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [x] Unpin this issue
- [x] Banner updated @jegelewicz
- [x] Email sent to AWG @ewommack
- [x] Email sent to Arctos Google Group @ewommack
- [x] Tweet @lin-fred (@mkoo backup)
- [x] Close this issue when above are complete

**Comment by Jegelewicz** [comment]
Me too.

**Comment by lin-fred** [comment]
me three

**Comment by Jegelewicz** [comment]
test is fine though.

**Comment by Jegelewicz** [comment]
I sent emails - no banner to update.

**Comment by dustymc** [comment]
I've done what I can, I think the proxy (which I can't reach) is down. I sent Chris email but he's on vacation and I'm not sure how connected he is.

**Comment by dustymc** [comment]
Chris is bad at vacation, Arctos is back.
