### ISSUE TITLE
Fix for Media metadata load that happened without attaching catalog numbers

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#4128]
Dusty, I loaded a set of media metadata before our new bulkloader format (i know a long time ago..) and realized just now that all the media metadata loaded except for the catalog numbers and somehow didn't get notified. I can't figure out how to get the media ids to fix this without a searchable keyword. Here is what I loaded. I was wondering why i thought i had uploaded 4000 media records and only half showed up on GBIF. Anyway to fix this easily? or spit out the media ids for this set of media-uris?

[MediaLoad2.csv](https://github.com/ArctosDB/arctos/files/7568163/MediaLoad2.csv)

**Comment by dustymc** [comment]
>or spit out the media ids for this set of media-uris?

<img width="658" alt="Screen Shot 2021-11-19 at 8 51 06 AM" src="https://user-images.githubusercontent.com/5720791/142660822-54c25d3f-77ce-4d83-bd03-fcaee0b3c0a0.png">

Let me know if you have any problems - I don't think that's been used.

**Comment by mvzhuang** [comment]
Looks like it worked! Closing? or needs more discussion?
