### ISSUE TITLE
Alphabetize dropdown for attribute_code_table picks

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4129]
https://arctos.database.museum/Admin/CodeTableEditor.cfm?action=editAttCodeTables&tbl=ctattribute_code_tables

When I need to add a value or unit constraint for an attribute, the pick list is in random order. Please alphabetize it.

<img width="960" alt="Screenshot 2021-11-19 08 25 17" src="https://user-images.githubusercontent.com/5725767/142648290-3cbd8371-4697-4d70-b30d-638a56ea4c20.png">

**Comment by Jegelewicz** [comment]
I think I did this - waiting for next pull to test to check it.

**Comment by Jegelewicz** [comment]
Nope - added one more order by

**Comment by mkoo** [comment]
have I said please YES yet!

**Comment by Jegelewicz** [comment]
Fix is in test - waiting on pull to production

<img width="960" alt="Screenshot 2021-12-03 08 11 43" src="https://user-images.githubusercontent.com/5725767/144625808-3b42ac18-9457-4fca-a65c-e57c42d5c1c1.png">
