### ISSUE TITLE
Assign part name to subsamples at the time they are created for a loan

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4131]
@dustymc the problem here started with the fact that subsampling for loans creates a part with exactly the same name as the existing part, when @KyndallH subsamples muscle from a frog it creates a subsample that is "whole organism" when all she sent was muscle. It would be nice to be able to give subsampled parts a new part name at the time the loan is created.

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/arctos/issues/2465#issuecomment-974511004_

**Comment by Jegelewicz** [comment]
In this form, be able to re-name the subsample part

![image](https://user-images.githubusercontent.com/5725767/142699865-7068ddad-0d83-4585-b38e-66cf903d2ac9.png)

**Comment by Jegelewicz** [comment]
Also ability to edit subsample condition.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/4124 (for now, I think, maybe....)
