### ISSUE TITLE
Requesting permission to edit localities

### ISSUE THREAD

**Issue by kmkocot** [ArctosDB/arctos#4132]
# Error Text
An error occurred while processing this page!
Message: not authorized
Detail: You are not authorized to access this form.
Check the Arctos Handbook for more information on errors.

This message has been logged as 116CECF5-5876-47CA-91229656433DFB56 Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue. 

# Where it happened
I tried to edit an incorrect locality (from this page: https://arctos.database.museum/guid/ALMNH:Inv:904) and got this error.

# Steps to get there
I clicked "Edit" in the "Location" box.

# Solution
May I be granted permission to edit collecting events? The date is incorrect on this one, for example.

**Comment by Jegelewicz** [comment]
@kmkocot collecting events and localities are shared - please read these.

[Arctos Locality Documentation](http://handbook.arctosdb.org/documentation/locality.html)  

[Understanding the Arctos Locality Model](http://handbook.arctosdb.org/how_to/How-to-understand-the-Arctos-Locality-Model.html) 

[How To Create a Locality](https://handbook.arctosdb.org/how_to/How-to-Create-a-Locality.html)

[How To Create a New Collecting Event for a Locality](https://handbook.arctosdb.org/how_to/How-to-Create-a-New-Collecting-Event-for-a-Locality.html)

You can also watch the locality tutorials - https://arctosdb.org/learn/tutorial-blitz/#locality

Let me know if you have any questions. I'm happy to meet up and walk through edits if you want!

**Comment by kmkocot** [comment]
Thank you! I will give this a read asap. If I'm not confident, I may follow up to ask for supervision to make sure I'm not breaking anything.

**Comment by Jegelewicz** [comment]
@kmkocot You should now be able to edit localities - the main thing here is that you should never edit a shared locality without permission from those sharing it. You can always fork-edit and assign the new locality to your catalog records, but if you can make everyone's localities better - please notify the other collections and get their buy in! You can do this by filing an issue here and I will help get everyone affected notified. If this works for you, please close this issue.

**Comment by dustymc** [comment]
>f you can make everyone's localities better - please notify the other collections and get their buy in!

If that's where we're going then it needs documentation or discussion or something; it's the opposite of what the model is built around. If someone does not want help with their localities they can name them, otherwise we are a Community and there are notifications, just fix what needs fixin'.
