### ISSUE TITLE
Requesting permission to upload media

### ISSUE THREAD

**Issue by kmkocot** [ArctosDB/arctos#4133]
# Error Text
An error occurred while processing this page!
Message: not authorized
Detail: You are not authorized to access this form.
Check the Arctos Handbook for more information on errors.

This message has been logged as C9E22B7A-5F6D-4F3B-9BDE73195256C7F4 Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue. 

# Where it happened / steps to get there
I tried to upload media by clicking Enter Data, Batch Tools, Enter Media, Upload Photos.

# Solution
May I be granted permission to upload Media? I have read this page: https://handbook.arctosdb.org/documentation/media.html

Thanks!

**Comment by Jegelewicz** [comment]
@kmkocot are you currently only planning to attach media one at a time?

**Comment by kmkocot** [comment]
Hi @Jegelewicz! I would like to be able to upload one-off images but to also be able to bulkload media (images). We have a few thousand photos from our NBP 20-10 Icy Inverts cruise (https://arctos.database.museum/project/10003591) that are currently organized in folders by field number but it should (hopefully?) be easy to organize them and the relevant metadata by catalog number to bulkload them. Thanks!

**Comment by Jegelewicz** [comment]
@kmkocot I can grant you access to upload media singly, but for the bulk upload we have a new process. I have opened an issue for you here - https://github.com/ArctosDB/internal/issues/146 PLease read the documents referenced in the third and fourth steps, then create a user account at TACC and put your username in a comment to that issue. Once that is done we can discuss your directory structure and who should have write access to it.

**Comment by Jegelewicz** [comment]
@kmkocot you should now be able to upload media singly. If that works, please close this issue - we will manage the bulk stuff in the other one.
