### ISSUE TITLE
tube position upload

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#4134]
@dustymc When you have a chance, could you please load another batch of cryovial barcodes into freezer box positions as you did in #3181 and #3598?
[DMNS_bird_tube_pos.zip](https://github.com/ArctosDB/arctos/files/7573443/DMNS_bird_tube_pos.zip)

**Comment by dustymc** [comment]
[temp_dmns_pos.csv.zip](https://github.com/ArctosDB/arctos/files/7573554/temp_dmns_pos.csv.zip)


@acdoll I couldn't find positions for some - posid is null for the problematic rows.

**Comment by acdoll** [comment]
I missed that last step of create-positions for the bottom shelves. They should be ready now; can you please try again?

**Comment by acdoll** [comment]
@dustymc just realized I should have mentioned you to get your attention. When you have a chance...

**Comment by dustymc** [comment]
done

**Comment by acdoll** [comment]
Awesome! I did some spot checking and these all look great! THANK YOU @dustymc!
