### ISSUE TITLE
Feature Request - map information in object tracking to catalog records

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4135]
**Is your feature request related to a problem? Please describe.**
There are tissues in a freezer with a lot of environmental history but that history is not reflected in the catalog record. Object tracking is not a public function, so all of this potentially useful information is hidden. Even for those with access, getting to it can be a chore.

**Describe what you're trying to accomplish** 
Create a path for accessing container environment information from the parts in the container.

**Describe the solution you'd like**
We aren't completely sure what would be workable.

**Describe alternatives you've considered**
Creating a new part attribute = "container environment" that includes a summary of container history for the part drawn directly from object tracking (no data entry into this attribute - it just gets created by container environment history)

**Additional context**
We recognize that we could be creating an exponentially huge amount of data, but aren't sure how else to make this work. Other ideas appreciated!

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/1119 ????

**Comment by Jegelewicz** [comment]
Yes - I think that is still what we are discussing. @KyndallH @campmlc I think it would be REALLY helpful to have one or two examples of what you have now vs. what you would like to have. Maybe read through #1119 too.

**Comment by campmlc** [comment]
This issue exists because #1119 was never resolved.  The material is still relevant, although we have finally separated part preservation. But the need for tracking preservation history is still urgent. We can now use part attributes for that, but these require manual entry. What about when a freezer goes down, and all the cryovials within that freezer are subject to elevated temperature? The only place this could be recorded, currently, is in Edit Container -> Container Environment -> Create Environment Record, and as far as I understand, the container environment data do not propagate to child containers.

**Comment by campmlc** [comment]
Nor does this information appear anywhere on the catalog records of the affected parts within containers.

**Comment by Jegelewicz** [comment]
> the container environment data do not propagate to child containers

I think this is something that needs resolving for sure! If it isn't true, we need to understand how to get at the information. If it is true, we need to figure out a way to make container environment data do not propagate to child containers.

**Comment by dustymc** [comment]
> #1119 was never resolved

It was - we had many discussions and decided to "Do something weird and text-based on a part-by-part basis."

>container environment data do not propagate to child containers.

Sorta true, that's just how hierarchical models work. 

I'm not sure what "we need to figure out a way to make container environment data do not propagate to child container" means.

**Comment by Jegelewicz** [comment]
> I'm not sure what "we need to figure out a way to make container environment data do not propagate to child container" means.

What we mean is that "container environment data should propagate to child containers". So, when the freezer goes down, every vial in every box in every rack in the freezer has the notation of temperature change and for how long. The reason nobody bothers to record any freezer information is that it currently means nothing for all the parts located in the freezer, which is really where we want to know "condition".

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/1371
