### ISSUE TITLE
Unexpected Error for Arctos Report

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#4137]
I am trying to pull the data for a report from CHAS_annualreport (CHAS_annualreport.cfr) and am encountering an error that states:

<html>
<body>
<font style="color: black; font: 16pt / 18pt verdana; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">The web site you are accessing has experienced an unexpected error.<br>Please contact the website administrator.</font><span style="color: rgb(0, 0, 0); font-family: Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"></span><br style="color: rgb(0, 0, 0); font-family: Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br style="color: rgb(0, 0, 0); font-family: Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

The following information is meant for the website developer for debugging purposes.
--

Error Occurred While Processing Request
Error Executing Database Query.ERROR: subquery in FROM must have an alias The error occurred in /usr/local/httpd/htdocs/internal/reporter/report_printer.cfm: line 135133 : 			 134 : 			<cfquery name="d" datasource="user_login" username="#session.dbuser#" password="#decrypt(session.epw,session.sessionKey)#"> 135 : 				#preservesinglequotes(sql)# 136 : 			</cfquery> 137 : 		</cfcatch> | Error Executing Database Query. | ERROR: subquery in FROM must have an alias |   | The error occurred in /usr/local/httpd/htdocs/internal/reporter/report_printer.cfm: line 135 | 133 : 			 134 : 			<cfquery name="d" datasource="user_login" username="#session.dbuser#" password="#decrypt(session.epw,session.sessionKey)#"> 135 : 				#preservesinglequotes(sql)# 136 : 			</cfquery> 137 : 		</cfcatch>
Error Executing Database Query.
ERROR: subquery in FROM must have an alias
 
The error occurred in /usr/local/httpd/htdocs/internal/reporter/report_printer.cfm: line 135
133 : 			 134 : 			<cfquery name="d" datasource="user_login" username="#session.dbuser#" password="#decrypt(session.epw,session.sessionKey)#"> 135 : 				#preservesinglequotes(sql)# 136 : 			</cfquery> 137 : 		</cfcatch>

</body>
</html>

Please let me know if you need any additional information for debugging this issue.

**Comment by wellerjes** [comment]
The same error happens when I try to pull the information from CHAS_loan_header (CHAS_loan_header.cfr) and CHAS_loan_inventory (CHAS_loan_inventory.cfr). The issue is in line 135 for all errors.

**Comment by dustymc** [comment]
CHAS_annualreport: I'm not sure what's going on there or how to salvage anything. If you'll let me know what data you need and where you're coming from (there are currently no input parameters at all) I might be able to figure something out.

CHAS_loan_header works for me.

I made CHAS_loan_inventory work by removing some nonsense code, but I'm not sure if it's doing whatever's intended.

**Comment by wellerjes** [comment]
Thanks for the update. I'm still getting the error when I try pulling each of the reports. My process is going to the "Manage" dropdown, then selecting "Print Any Report", which redirects me to a different server via a link. Is this still the correct process? (My reference is the tutorial video from YouTube, I'm not sure if the process has changed since then.

**Comment by wellerjes** [comment]
I found this code that states what was in the Annual Report when it was created:

SELECT col, genera_c, families_c, species_c, accn_records, total_loans, total_cons_loans, total_spec_loans, total_spec_cons_loans, total_accn, '2016' AS year, 'calendar year' AS year_type, 'CHAS' AS institution_name

FROM (SELECT col, genera_c, families_c, species_c, accn_records, total_loans, total_cons_loans, total_spec_loans, total_spec_cons_loans
FROM (SELECT col, genera_c, families_c, species_c, accn_records, total_loans, total_cons_loans, total_spec_loans
FROM (SELECT col, genera_c, families_c, species_c, accn_records, total_loans, total_cons_loans
FROM (SELECT col, genera_c, families_c, species_c, accn_records, total_loans
FROM (SELECT col, genera_c, families_c, species_c, accn_records
FROM (SELECT col, genera_c, families_c, species_c
FROM (SELECT col, genera_c, families_c
FROM (SELECT collection AS col, COUNT(DISTINCT(genus)) AS genera_c FROM flat GROUP BY collection ORDER BY collection)

FULL OUTER JOIN (SELECT COUNT(DISTINCT(family)) AS families_c, collection
FROM flat
GROUP BY collection)
ON col = collection
ORDER BY collection)

FULL OUTER JOIN (SELECT COUNT(DISTINCT(species)) AS species_c, collection
FROM flat
GROUP BY collection)
ON col = collection
ORDER BY collection)

LEFT OUTER JOIN (SELECT collection, SUM(estimated_count) AS accn_records
FROM accn, trans, trans_agent, collection
WHERE collection.collection_id = trans.collection_id
AND trans_agent_role = 'entered by'
AND trans.transaction_id = trans_agent.transaction_id
AND trans_agent.transaction_id = accn.transaction_id
AND accn.received_date BETWEEN '2016-01-01' AND '2016-12-31'
GROUP BY collection)
ON col = collection)

LEFT OUTER JOIN (SELECT collection, count(loan_number) AS total_loans
FROM loan, trans, collection
WHERE loan.transaction_id = trans.transaction_id
AND trans.collection_id = collection.collection_id
AND (loan_number LIKE '2016%')
AND trans_date BETWEEN '2016-01-01' AND '2016-12-31'
GROUP BY collection)
ON col = collection)

LEFT OUTER JOIN (SELECT collection, count(loan_number) AS total_cons_loans
FROM loan, trans, collection
WHERE loan.transaction_id = trans.transaction_id
AND trans.collection_id = collection.collection_id
AND (loan_number LIKE '2016%')
AND trans_date BETWEEN '2016-01-01' AND '2016-12-31'
AND loan_type = 'consumable'
GROUP BY collection)
ON col = collection)

LEFT OUTER JOIN (SELECT COUNT(DISTINCT(specimen_part.derived_from_cat_item)) AS total_spec_loans, collection
FROM loan, trans, collection, loan_item, specimen_part
WHERE loan.transaction_id = trans.transaction_id
AND trans.collection_id = collection.collection_id
AND loan.transaction_id = loan_item.transaction_id
AND loan_item.collection_object_id = specimen_part.collection_object_id
AND (loan_number LIKE '2016%')
AND trans_date BETWEEN '2016-01-01' AND '2016-12-31'
GROUP BY collection)
ON col = collection)

LEFT OUTER JOIN (SELECT COUNT(DISTINCT(specimen_part.derived_from_cat_item)) AS total_spec_cons_loans, collection
FROM loan, trans, collection, loan_item, specimen_part
WHERE loan.transaction_id = trans.transaction_id
AND trans.collection_id = collection.collection_id
AND loan.transaction_id = loan_item.transaction_id
AND loan_item.collection_object_id = specimen_part.collection_object_id
AND (loan_number LIKE '2016%')
AND loan_type = 'consumable'
AND trans_date BETWEEN '2016-01-01' AND '2016-12-31'
GROUP BY  collection)
ON col = collection)

LEFT OUTER JOIN (SELECT collection, COUNT(DISTINCT(accn_number)) AS total_accn
FROM accn,trans,trans_agent,collection
WHERE collection.collection_id = trans.collection_id
AND trans_agent_role = 'entered by'
AND trans.transaction_id = trans_agent.transaction_id
AND trans_agent.transaction_id = accn.transaction_id
AND accn.received_date BETWEEN '2016-01-01' AND '2016-12-31'
GROUP BY collection)
ON col = collection

**Comment by wellerjes** [comment]
closed; will build a new one in the new reporter
