### ISSUE TITLE
Code Table Request - Bone Valley Member + Peace River Formation

### ISSUE THREAD

**Issue by aklompma** [ArctosDB/arctos#4138]
**Goal**
Add Peace River Formation and Bone Valley Member to the formation code table.

**Context**
The Peace River Formation and Bone Valley Member exist. Needed for a specimen to be cataloged.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlithostratigraphic_formation
& 
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlithostratigraphic_member

**Value**
Peace River Formation
Bone Valley Member

**Definition**
Peace River Formation = a (Miocene - Pliocene, Langhian - Zanclean) unit exposed in central and southern Florida. Formation within the Hawthorn Group. See: https://macrostrat.org/sift/#/strat_name/1533
Bone Valley Member = a (Miocene - Pliocene, Langhian - Zanclean) unit exposed in central Florida. Member within the Peace River Formation. See: https://macrostrat.org/sift/#/strat_name/6939

Can anyone add it to the code table?

**Comment by Jegelewicz** [comment]
@aklompma I can do this once I can access Arctos.

**Comment by aklompma** [comment]
Thanks very much @Jegelewicz !

**Comment by Jegelewicz** [comment]
Added Peace River Formation

Bone Valley member is already in the code table - https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlithostratigraphic_member#bone_valley_member

**Comment by aklompma** [comment]
Thanks!
