### ISSUE TITLE
See All Objects in this Container

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4140]
Request: To add any unlinked barcodes - specifically, barcodes with no associated catalog item or child container - to the report generated by 
Object Tracking: Find Container: See All Collection Objects in this Container 

Reason: I need a way to find out whether all cryovials in a freezer box are linked to a catalog record part, and if so, to what catalog record. 
Currently, I can click on See All Collection Objects, and that gives me a list of catalog items in the freezer box and their associated cryovial barcodes. But it does not give me the barcodes that are not linked to a part. I can only tell there are missing parts because there is a discrepancy between the number of "leaf containers" and the number of cryovials in the box. Finding out which ones are not linked involves a rather hugely complicated series of steps to copy paste from the freezer box positions form into Excel to try to get a csv list of the barcodes in the box. 
![Screenshot 2021-11-24 11 18 36](https://user-images.githubusercontent.com/14808196/143295251-62c34970-f9ce-4397-9ef5-b898cb0c3fb6.png)

Alternatives:
1) Provide a way to download the list of barcodes in a container from the freezer box form or any form as csv list. This would be good to have regardless. 

2) Fix the "find empty positions" tools in Find Container: Edit Container and Find:Container as shown below. #4027
![Screenshot 2021-11-24 11 26 50](https://user-images.githubusercontent.com/14808196/143295336-dad238a4-ca68-4338-9c0f-01e877cb69be.png)

![image](https://user-images.githubusercontent.com/14808196/143295487-d7481645-7d32-45e0-9c5c-dae3810fffce.png)

3) all of the above would be ideal

Priority: High, Breaking functionality. Since none of these tools are working, I cannot do my job which requires knowing exactly what is in each container in order to locate and fix missing samples due to errors made in other divisions during cataloging.

**Comment by Jegelewicz** [comment]
I have changed the issue title to focus on the first ask. Is it possible to have an option that lists all positions in a container along with the barcode of the thing in the position or NULL if there is nothing and the link to the part if there is one or NULL if there is no part.

So for the box @campmlc gave as an example, the report would return 100 lines but line 10 would look like this

Label | Description | Next2Layers | Lbl1 | Lbl2 | Remarks | Part Name | Disposition | Cat Num | Scientific Name
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
  |   | [ ] 10 (position):[ ] |  

Then, if one of these cryovials includes a part that is not associated with a catalog record (let's pretend that is position 1) the line would look like this

Label | Description | Next2Layers | Lbl1 | Lbl2 | Remarks | Part Name | Disposition | Cat Num | Scientific Name
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
  |   | [ ] 1 (position):[ ACIX3 ] ACIX3 (cryovial) |  

@campmlc could this be even simpler? Could the output just be csv like this

![image](https://user-images.githubusercontent.com/5725767/144930528-022498f9-0028-4d6e-a92c-68d984488e8e.png)

Absence of a barcode, label and part indicates an empty position (purple) and absence of a part indicates that there is something in the position, but it is not linked to a part.

**Comment by campmlc** [comment]
That works for me. We also need to consider that sometimes a barcode may have more than one part associated. These are errors that need to be caught and corrected. In this case, can the two parts associated with the same barcode show up as a comma separated list in the Part column?

**Comment by campmlc** [comment]
It would still be very useful to get the output as shown in the first forma, but this could be a cached search that could be emailed.

**Comment by dustymc** [comment]
try with table like https://github.com/ArctosDB/arctos/issues/4140#issuecomment-987281163

* start with source container
* show 5 levels of children

**Comment by dustymc** [comment]
"Container Contents" in next release
