### ISSUE TITLE
Arctos project disappeared?

### ISSUE THREAD

**Issue by mlbowser** [ArctosDB/arctos#4141]
# Error Text
> An error occurred while processing this page!
> Message: ERROR: syntax error at end of input Position: 634
> Detail:
> Check the Arctos Handbook for more information on errors.
> This message has been logged as 78D3DAF9-0F3E-4BFF-8DB8A4DDCC7A07B2[...]

# Where it happened
<https://arctos.database.museum/project/10003367>

The project appears to have disappeared. I do not remember deleting it and I do not know why I would do such a thing. If there is something wrong the text in the project description, I cannot edit it to fix it.

# Steps to get there
From blank-looking project URI, click on "Edit Project".

**Comment by mlbowser** [comment]
Looking into this further, I suspect that this project and all ~140 associated catalog records and some images, etc. were lost as part of the data loss event in spring 2020. I still have most of my files, so I think I can recreate the catalog records. It would be ideal if I could retain and edit this project URI because it is referred to in an article.

**Comment by dustymc** [comment]
@mlbowser I created a blank project with that ID, you should be able to edit it however you need to.

**Comment by mlbowser** [comment]
Thank you, @dustymc!
