### ISSUE TITLE
Arctos Down - Saturday 11/27 7:30 pm MDT

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4142]
I understand that we are expecting a planned outage tomorrow, Sunday Nov 28 10am-4pm CST. But Arctos appears to be down currently.

## Unplanned Outage
 - Date and time outage began: 
 - Date and time outage is expected to end:
 - Reason for outage:
 - Expected behavior during and after the outage:

## Planned Outage
 - Date and time outage will begin:
 - Date and time outage is expected to end:
 - Reason for outage:
 - Expected behavior during and after the outage:

## Communication before/during outage
- [ ] Pin this issue
- [ ] Banner updated @jegelewicz 
- [ ] Email sent to AWG @ewommack 
- [ ] Email sent to Arctos Google Group @ewommack 
- [x] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @jegelewicz
- [ ] Email sent to AWG @ewommack
- [ ] Email sent to Arctos Google Group @ewommack
- [x] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by lin-fred** [comment]
I am getting a 503 Service Not Available as well

**Comment by campmlc** [comment]
According to Chris at TACC it is the Lucee server down.

**Comment by lin-fred** [comment]
It's back up for me

**Comment by campmlc** [comment]
Yes, me too - thanks to whoever pulled the magic strings!
