### ISSUE TITLE
Arctos Down - Secure connection failure

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4143]
Please complete to the best of your ability.

## Unplanned Outage
 - Date and time outage began: 2021-11-29 7:30Am MST
 - Date and time outage is expected to end:
 - Reason for outage: Unknown
 - Expected behavior during and after the outage: Unable to open Arctos

> Secure Connection Failed
> 
> An error occurred during a connection to arctos.database.museum. PR_CONNECT_RESET_ERROR
> 
>     The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
>     Please contact the website owners to inform them of this problem.

## Planned Outage
 - Date and time outage will begin:
 - Date and time outage is expected to end:
 - Reason for outage:
 - Expected behavior during and after the outage:

## Communication before/during outage
- [x] Pin this issue
- [ ] Banner updated @jegelewicz 
- [ ] Email sent to AWG @ewommack 
- [ ] Email sent to Arctos Google Group @ewommack 
- [x] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @jegelewicz
- [ ] Email sent to AWG @ewommack
- [ ] Email sent to Arctos Google Group @ewommack
- [x] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by Jegelewicz** [comment]
Not sure if this is everyone or just me for some reason...

**Comment by lin-fred** [comment]
I am also experiencing it

**Comment by campmlc** [comment]
I cannot log in.

**Comment by lin-fred** [comment]
its back up for me
