### ISSUE TITLE
Arctos Down - 11-29-2021 1:44 pm

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4144]
Just lost connectivity via UNM on multiple computers. 505 and 503 errors.

## Unplanned Outage
 - Date and time outage began: 11-29-2021 1:44 pm
 - Date and time outage is expected to end:
 - Reason for outage:
 - Expected behavior during and after the outage:

## Planned Outage
 - Date and time outage will begin:
 - Date and time outage is expected to end:
 - Reason for outage:
 - Expected behavior during and after the outage:

## Communication before/during outage
- [ ] Pin this issue
- [ ] Banner updated @jegelewicz 
- [ ] Email sent to AWG @ewommack 
- [ ] Email sent to Arctos Google Group @ewommack 
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @jegelewicz
- [ ] Email sent to AWG @ewommack
- [ ] Email sent to Arctos Google Group @ewommack
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by lin-fred** [comment]
I am able to get on

**Comment by mkoo** [comment]
I can access Arctos, but it did have an hiccup about 15 minutes ago.
Mariel, is it accessible now?

**Comment by Jegelewicz** [comment]
Working for me.

**Comment by campmlc** [comment]
Yes, seems to be working now. Must have been a hypergalactic space particle.
