### ISSUE TITLE
Quarantine misspelled taxon name

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4146]
I'd like to get the collections using Sceloporus olivaceous to change to the correct spelling of Sceloporus olivaceus so that we can quarantine the misspelled name.

![image](https://user-images.githubusercontent.com/5725767/143948573-267b7598-0142-4ae5-bdb0-9621f465244a.png)

![image](https://user-images.githubusercontent.com/5725767/143948755-5da42197-d406-42f6-a7bf-19493a98b2fa.png)

@leet1984 
@diannakrejsa 
@kderieg322079 

I suggest that you change these identifications to Sceloporus olivaceus. You can place the misspelling in identification remark or record it as Sceloporus olivaceus {Sceloporus olivaceous}

**Comment by dustymc** [comment]
>remove

Please don't, it's in common and [scientific](https://pubmed.ncbi.nlm.nih.gov/3352086/) usage, https://github.com/ArctosDB/arctos/issues/2937, https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxon_name_type#quarantine is the proper treatment.

@DerekSikes

**Comment by leet1984** [comment]
Hi Teresa,

I could only find one misspelled S. olivaceous and I changed it to S.
olivaceus.
Attached is the updated catalog.

All the best
Tom

**Comment by Jegelewicz** [comment]
@leet1984 here are the two records:

https://arctos.database.museum/guid/ACUNHC:Herp:103
https://arctos.database.museum/guid/ACUNHC:Herp:164

All of your data, except for mammals is now in Arctos - please make changes there!

**Comment by Jegelewicz** [comment]
identifications changed and name has been quarantined.
