### ISSUE TITLE
Reports server Element DBUSER is undefined in SESSION.

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4147]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Still getting this random error which refuses to allow me to access the reports server. Have tried from two different browsers and incognito logins, plus log out and in. Very difficult to suddenly lose access to reports when I am trying to get a loan out the door.

**To Reproduce**
1. Go to '...' Be working in a loan
2. Click on '....' Report; any report
3. Scroll down to '....' try to open reports server

**Expected behavior**

**Screenshots**

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/3480#issuecomment-789124068
