### ISSUE TITLE
Catalog record header suggestion

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4148]
When viewing a catalog record, the header appears as follows:

![image](https://user-images.githubusercontent.com/5725767/143958300-8992e98b-0a77-4292-a27d-5a167c80f094.png)

It is quite cluttered. To cut down on a bit of the clutter, I suggest making the following change to this section

![image](https://user-images.githubusercontent.com/5725767/143958406-1edb910a-8fb5-4e15-ade5-bef85d98386e.png)

License: CC BY-NC
Terms: Arctos Data Ownership and Use
[Collection Details](https://arctos.database.museum/collection/ACUNHC:Herp)
[Loan Policy](https://docs.google.com/document/d/1fGNEPX13cFZIXHVgzD2fPubYaE_sM4PdHT9XxkhMoR4/edit?usp=sharing)

**Comment by Jegelewicz** [comment]
@dustymc I would do this in test, but for the life of me I cannot figure out how that section gets built!

**Comment by Jegelewicz** [comment]
I am also wondering if the banner should be moved so that all those links are next to the collection/institution text?

**Comment by mkoo** [comment]
Wow, I came here to file this exact same complaint!
Well, I also want to add that those four lines be right -justified and added to below the log in info at the right margin of the header. (Why is is floating in the middle where it bounces around with the banner?! You are giving me a layout heartattack!)

**Comment by dustymc** [comment]
>below the log in info

I'm 99% sure that would require more space for some headers, and vertical space is a precious resource.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
With Teresa's abbreviated header, could we put the info all on one line like this?

![image](https://user-images.githubusercontent.com/47402809/145308596-d09edb0a-6032-4827-b0ab-53f8b273e0e8.png)

**Comment by dustymc** [comment]
I don't see any obvious issues with that - we might have to vertically squish the unexpanded banner a bit, but that's easy enough and shouldn't cause any problems.

**Comment by mkoo** [comment]
Personally I would like all that right-justified License and terms links to be flush right under all the Login links. It's jarring to see that block of right-justified text floating out in the middle and then bobbing around depending if we have an announcement. I realize it would increase the height of the section (by 4 lines) which I would welcome instead.

**Comment by dustymc** [comment]
Things get wonky with everything stacked on the right

<img width="1670" alt="Screen Shot 2022-05-26 at 11 35 36 AM" src="https://user-images.githubusercontent.com/5720791/170554212-dc7d84e1-e619-4dd3-a8ec-26cee8b9a12c.png">

and I'm not sure why, something is interacting with something else. I backed out of that, the header just needs redesigned as part of https://github.com/ArctosDB/arctos/issues/2893

**Comment by Jegelewicz** [comment]
How about putting the license & stuff just to the right of the collection name, then let the announcement "appear" to the right of that?

Or take @Nicole-Ridgwell-NMMNHS advice? https://github.com/ArctosDB/arctos/issues/4148#issuecomment-989317027

**Comment by ewommack** [comment]
> Things get wonky with everything stacked on the right
I also just saw a couple comments recently about difficult finding the log-in log-out button too, and I imagine stacking everything together might exasperate that.

**Comment by dustymc** [comment]
I think this is basically just stuck until we move on https://github.com/ArctosDB/arctos/issues/2893

I'm up for anything, but I think if I had to do something today it'd look a bit like @Jegelewicz's screenshot in https://github.com/ArctosDB/arctos/issues/2893#issuecomment-1109211642, and login would just be a menu item. That should also make room for things like https://github.com/ArctosDB/internal/issues/176.
