### ISSUE TITLE
Parts to Containers Tool is Broken

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4154]
The Parts to Containers tool needs repair.
The first column in the downloaded template, "guid-prefix", is lower case, and that is throwing a syntax error.
The last two columns are merged in the template as "BARCODE.ignore.child.parts" instead of two columns, "BARCODE" and "IGNORE_CHILD_PARTS".
It also may be getting stuck on the extra row at the bottom of the csv - but I fixed all the above at once so not sure what actually fixed it.
Priority High.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/3707
