### ISSUE TITLE
Add Attribute to Teach Collection 

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#4156]
Can you please add the option in Attributes for "bill length" in "Teach"?

Thanks!

**Comment by Jegelewicz** [comment]
Added - but be sure you wouldn't rather use [culmen length](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#culmen_length).

**Comment by wellerjes** [comment]
It looks like this was made to "Bird" instead of "Teach", I am not seeing it as an option in "Attributes".

I will add culmen length as well. Thanks!

**Comment by Jegelewicz** [comment]
OOPS - it's there now!
