### ISSUE TITLE
Arctos Down - 1 December 2021

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#4158]
Please complete to the best of your ability.

## Unplanned Outage
 - Arctos was working and then stopped 12/1/2021 at ~3:45pm Pacific
 - Reason for outage: ???
 - Expected behavior during and after the outage: ???

## Communication before/during outage
- [ ] Pin this issue
- [ ] Banner updated @jegelewicz 
- [ ] Email sent to AWG @ewommack 
- [ ] Email sent to Arctos Google Group @ewommack 
- [x] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @jegelewicz
- [ ] Email sent to AWG @ewommack
- [ ] Email sent to Arctos Google Group @ewommack
- [x] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by lin-fred** [comment]
It is down for me too

**Comment by acoconis** [comment]
> It is down for me too

me too.

**Comment by dustymc** [comment]
I sent Chris email - that should be somewhere on the list (or I think he gets AWG email, if that could be handled better).

**Comment by ccicero** [comment]
This is my first time trying out this template, which is a bit confusing for unplanned outages. 

We should confirm if Chris got this, and if not, make sure he's tagged or something so that he does receive it.

**Comment by mkoo** [comment]
We can tweak the template but Chris J needs a directly email.

Still down

**Comment by campmlc** [comment]
Chris doesn't check GitHub. It is a difficult  situation. We have to email
him.

**Comment by ewommack** [comment]
Looks like we're up and running again.

Ok to close?

**Comment by mkoo** [comment]
yep working for me now.
go ahead!
