### ISSUE TITLE
Feature Request - Datum Cleanup

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4159]
**Is your feature request related to a problem? Please describe.**

See https://github.com/ArctosDB/arctos/issues/2660 - we need to move to spatial data (rather than strings). 

**Describe what you're trying to accomplish** 

I need to calculate standard coordinates, and for that I need spatial information for [datums](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctdatum).

**Describe the solution you'd like**

Find an appropriate SRID for the datums without,

```

arctosprod@arctos>> select datum from ctdatum where srid is null;
                   datum                    
--------------------------------------------
 European Terrestrial Reference System 1936
 Geocentric Datum of Australia 2000
 GUX 1 Astro
 Ireland 1965
 Indian Thailand
(5 rows)

```

**Describe alternatives you've considered**

Change those without to [unknown](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctdatum#unknown) and add a locality remark. This would affect these records:

```
create table temp_funky_datum_rec as
select
    locality.locality_id,
    locality.datum,
    flat.guid,
    flat.guid_prefix
from
    locality
    inner join ctdatum on locality.datum=ctdatum.datum and ctdatum.srid is null
    left outer join collecting_event on locality.locality_id=collecting_event.locality_id
    left outer join specimen_event on collecting_event.collecting_event_id=specimen_event.collecting_event_id
    left outer join flat on specimen_event.collection_object_id=flat.collection_object_id
;

```

[temp_funky_datum_rec.csv.zip](https://github.com/ArctosDB/arctos/files/7643814/temp_funky_datum_rec.csv.zip)

Summary:

```
select guid_prefix,count(*) c from temp_funky_datum_rec group by guid_prefix;
 guid_prefix | c  
-------------+----
 MVZ:Herp    | 18
 MVZ:Mamm    | 52
 MVZ:Bird    |  6
```

**Additional context**

Let me know if you need a copy of the srids I can deal with, or see table spatial_ref_sys

**Additional additional context**

These don't seem to be used, I'll delete them now-ish if nobody has a reason to keep them around (and can provide an SRID).

```
                   datum                    
--------------------------------------------
 European Terrestrial Reference System 1936
 Geocentric Datum of Australia 2000
 Indian Thailand
```
**Additional additional additional context**

I need to alter ctdatum to set SRID NOT NULL when this is cleaned up; please don't close until that's been accomplished.

**Priority**

High - this will hopefully be preventing progress in the very near future.

@mkoo @ccicero @cjconroy @atrox10

**Comment by mkoo** [comment]
ok I'm going to transfer to our MVZ data issue list and cleanup. We'll either find an alternative datum with  SRID or redo whatever but use a SRID based datum.
are the other two datums not used by any collection? If so let's get rid of them
  - European Terrestrial Reference System 1936
  - Geocentric Datum of Australia 2000

**Comment by mkoo** [comment]
Also, a point of historic note-- these all were actual used datums, just associated with mapping efforts from WW1 and WW2 so pre-digitized standards. Came out of paper map-based georeferencing. We've come a long way baby!

I'll think about this a bit more on two aspects: 1) is it worth keeping these legacy georefs? It may be useful to have these unaccepted coordinates as an historic note since who knows if the data was used or cited somewhere?; 2) if so, these datum details could go remarks as part of the legacy note so we can still keep datum values clean and SRID based.

**Comment by dustymc** [comment]
I deleted the unused.


>datum details could go remarks as part of the legacy note 

Yes, I think so - https://arctos.database.museum/info/ctDocumentation.cfm?table=ctdatum#unknown is documented ("additional unknowable unrecorded amount of error"), someone looking at the stone tablet carved in that datum would probably 1) look in remarks, and 2) find that information useful. It's just not something that our version of postgis can deal with at the moment.

**Comment by mkoo** [comment]
yea that works-- and what I had in mind since it's may be only a historic artefact so who knows its usefulness down the road, but does not belong in a postgis Arctos.

**Comment by dustymc** [comment]
This will block https://github.com/ArctosDB/arctos/issues/4169; @mkoo can I change these to datum unknown and add a locality remark "Original datum: {current value}"?

**Comment by mkoo** [comment]
Yes, please-- students are out this week for finals. So will be another
week at least to finish.

**Comment by dustymc** [comment]
thx/done
