### ISSUE TITLE
Need Help with Arctos Error: Value too long

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#4160]
I'm trying to load a record into Arctos and am getting the following error message:

"value too long for type character varying(60)"

I've tried going back into the record and removing any blank spaces or text in the attributes that amounts to longer than 60 characters, but the error message still appears. Any thoughts on what might be causing this?

Thanks!

**Comment by Jegelewicz** [comment]
@wellerjes can you attach the data?

**Comment by wellerjes** [comment]
![Arctos1](https://user-images.githubusercontent.com/93737929/144500136-1dc8516a-303d-426d-b51f-7c841c83f74e.jpg)
![Arctos2](https://user-images.githubusercontent.com/93737929/144500146-f51e3224-e1b4-4bf9-9107-92f997adedcb.jpg)
![Arctos3](https://user-images.githubusercontent.com/93737929/144500159-c0032f2d-daa9-4c83-9a44-489bed1fc1a1.jpg)
Here's screenshots of the data entry and error message.

**Comment by Jegelewicz** [comment]
@wellerjes I can't do much with that - if you give me access to the collection, I can go look at the data. I don't think attribute values are the problem because they are allowed 4000 characters

**Comment by Jegelewicz** [comment]
It might be your verbatim date - that is only allowed 60 characters

**Comment by dustymc** [comment]
Yep - https://handbook.arctosdb.org/documentation/collecting-event.html#dates

**Comment by Jegelewicz** [comment]
@dustymc how hard is it to make the error more specific (which field is causing the problem)?

**Comment by wellerjes** [comment]
That resolved it. Thank you!
