### ISSUE TITLE
Need to move objects in positions out of a container

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4161]
This issue has been raised before, but I can't find it so starting anew.
In Object Tracking -> Find Container -> Edit Container, we have the ability to "Move all children of this container to barcode xxxx".
But this tool does not currently work if the children of a container are in positions in the container. This is problematic when we lose a freezer, for example, and we just want to move all of the racks from positions in one freezer to identical positions in a second freezer, usually at 3 am on a holiday weekend in a snowstorm. Since nothing is being changed, we should just be able to move everything out of the positions in one container to identical positions in a second container.  
An alternative that would be much more difficult and still cause problems would be to move the positions as well as the child containers at the same time to a new barcode. The problem with this is that my backup freezer already has positions, and so to use this option I'd have to delete the positions from my backup freezer before I could Move all children of the original dying freezer to the barcode of the backup freezer. 
Can we make one of these options work?
Priority: High. Has been causing complications in workflows for the last approx 7 years.

**Comment by KyndallH** [comment]
YES! Plus, we need to ensure the container history stays with the samples even though they are moving to a new container. I remember that at one point, it wasn't doing that.

**Comment by campmlc** [comment]
Still not doing that. See issue being posted next.

**Comment by dustymc** [comment]
>ensure the container history stays with the samples 

It does, but there are complications.

We desperately need a big-picture plan: https://github.com/ArctosDB/arctos/issues/3632

**Comment by campmlc** [comment]
We are working on big picture, but this request has been years in
discussion and it would solve a huge number of problems and is supported by
actual users of object tracking. I don't want to see it die again because
we need endless discussion before implementing real fixes.

**Comment by dustymc** [comment]
>take all containers in given positions in one container and move them (in one fell swoop) to the exact same positions in another container.

No, that much does not seem difficult, I'm just not sure how I'm supposed to interpret the other things mentioned. If that's the scope of this request it can go next task, of not then I need clarification.

**Comment by campmlc** [comment]
Yes, that is the scope! The positions themselves don't need to move. The containers in them move from the positions in container A to the exact same, empty positions in container B. Then container A keeps its now empty positions and its container history. 
That solves this immediate issue.

Beyond that, ideally, all the child containers record this history of change from parent A to parent B as well, as we can see this history of A to B in the history of the child cryovials. But that can be a separate issue.

**Comment by dustymc** [comment]
> and its container history

That's what I'm being thrown by. I'm not sure that works the way you think it should and I don't want to do something that breaks something I don't understand or anticipate. If that can be sorted out separately then I can proceed, if there's still some concern then it needs addressed first.

**Comment by campmlc** [comment]
But the cryovial history currently is not being tracked when we move boxes
or racks between freezers, or if it is, I can't see this history when I
look at the history of the cryovial. So implementing the tool requested
here doesn't break anything that isn't already broken?

**Comment by dustymc** [comment]
No, this tool would not change anything about history.

As far as I know nothing is broken, but it's still a complex relationship. If that needs changed or developed then it also needs a dedicated Issue. (Maybe there is one, seems recently familiar....)

**Comment by dustymc** [comment]
<img width="397" alt="Screen Shot 2021-12-03 at 2 23 18 PM" src="https://user-images.githubusercontent.com/5720791/144682080-32e9cf50-19b4-48c2-9cb1-dc9ba14155d9.png">


@campmlc plz break test

**Comment by Jegelewicz** [comment]
@dustymc I tried this using DGR19890 as the donor and DGR16413 as the recipient. Here are the results.

![image](https://user-images.githubusercontent.com/5725767/145047235-b78c5dd8-753f-45b0-b060-addd48fc1173.png)

I assume the error has to do with the difference in size, which makes sense! One question though, if the recipient size had been larger than the donor, would this have worked? I can see situations where stuff might be moved to a larger box.

I'll continue working on this - gotta find the right size boxes to test.

**Comment by Jegelewicz** [comment]
Successfully completed moving all cryovials from DGR18198 to DGR10476. @campmlc maybe you could use these same boxes and move stuff back? Now I need to test on racks and freezers.

**Comment by campmlc** [comment]
Are you doing this in test? When I look in production, both boxes have
cryovials in position.

**Comment by Jegelewicz** [comment]
In Test! I would never move stuff like this in prod!!!

**Comment by campmlc** [comment]
Yes, I was able to move them! Looks great!

**Comment by Jegelewicz** [comment]
Also successfully moves all racks from freezer DGR12751 to freezer DGR12745

![image](https://user-images.githubusercontent.com/5725767/145052184-3dc270ff-42f4-4abd-b728-f47b7723f63a.png)

Now - how does this affect history of all those cryovials?

**Comment by campmlc** [comment]
Great question - but this tool is phenomenal and I can't wait to have it up and running in production.
Thanks @Jegelewicz and @dustymc !
@KyndallH

**Comment by Jegelewicz** [comment]
Apparently not at all? Here is one of the vials moved in the freezer exchange.

![image](https://user-images.githubusercontent.com/5725767/145052830-4823ddc5-592b-4af9-838b-3c55b2905a9a.png)

All I know is that the cryovial was scanned into the box on this date. How would I also know that it was moved from one freezer to another and how the environmental history of the original freezer contributes to the fitness of the sample in this cryovial?

**Comment by Jegelewicz** [comment]
OK - will worry about environment history in another issue - any concerns about the location history? should a move like this generate something there - or are we relying on the hierarchy to know that this vial was moved to a new freezer today?

**Comment by campmlc** [comment]
The cryovial shows the move in History, but nothing shows up in the box histories of either parent or donor. Perhaps when we do a full container move of all children, something can be recorded in the box? Of course, the immediate parent is the position, so that makes it more complicated.

**Comment by campmlc** [comment]
And I agree that the vagueness of the info - e.g. having to click details just shows you were it is/was - is not very transparent.

**Comment by campmlc** [comment]
Perhaps History should also record "Moved From" as well as "Moved To" on a particular date by particular agent?

**Comment by dustymc** [comment]
> recipient size had been larger than the donor, would this have worked? I

No.

>can't wait to have it up and running in production.

It was when you typed that, but I somehow didn't get the issue updated.

>environment history in another issue -

Yea, seems like we need one.

>something can be recorded in the box?

That's a possibility, but it would require significant resources - it's not something I can do with the tools I have now.

>are we relying on the hierarchy to know that this vial was moved to a new freezer today

Exactly!

> History should also record "Moved From" 

That's just the history before the latest.
