### ISSUE TITLE
Rescanning cryovials back into new positions in original freezer box

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4162]
Problem: A student spilled a freezer box of cryovials, fortunately into a cooler where they could be recovered. 
All the cryovials need to go back into the same original box, but in a different order. 
But they cannot be rescanned into this box, because they still "exist" in the box in their old positions. 
I can physically scan them into a new box, and then physically rescan them into the old box. But this is twice the amount of work of what I actually need to do, which is just scan them once back into their original box. 

My student wanted to scan them once into a new box, and put the new box in the freezer, replacing the old one. But that loses all the container history of the old box, which I want to keep. The container history of the old box unfortunately does not transfer to the history of the child cryovials in that container, so if the parent box is discarded, all of the cryovial history is lost. See recent issue I also can't find.
#4161 if resolved would allow me to move all the cryovials out of this box into identical positions in a temporary virtual box, and then rescan them, a single time, physically back into the old box.

In the meantime, pending #4161, I am requesting that  @dustymc do programming magic to move all the cryovials currently in freezer box DGR22827 back into the same positions in DGR15198, their original box.   Because that is where they physically are located, and that container has all the container history for these vials associated with it.

**Comment by Jegelewicz** [comment]
@campmlc for this I would use the [bulk move](https://arctos.database.museum/moveContainer.cfm) and move all into a position-less box or virtual container then scan them back into the box.

Doesn't solve the container history problem, but does eliminate all the unnecessary scanning.

**Comment by campmlc** [comment]
Using bulk move still requires each tube be scanned out of position and
then rescanned into a new position.

**Comment by Jegelewicz** [comment]
No it doesn't - just move them all to a single position-less box or whatever, then as they are placed back in the (now empty) box they were spilled from?

**Comment by Jegelewicz** [comment]
In other words - barcode the cooler they were spilled into....

**Comment by campmlc** [comment]
But to move them, I still need to scan them into the form, or scan them into a csv.
If I could use "Move all child containers to barcode xxx" in Edit container to move everything at once as in #4161, that would work. But since the cryovials are in positions in DGR15198, that doesn't work.

**Comment by campmlc** [comment]
Just to clarify, I did have the student scan them into a "virtual box", DGR22827. But physically, they were actually placed in those position in the original box, DGR15198, which is the only way I could see to do this with a single scan without the functionality requested in #4161.

**Comment by Jegelewicz** [comment]
I would use this
![image](https://user-images.githubusercontent.com/5725767/144519773-26c80241-66a7-45a0-871a-3740576fe35b.png)

get the barcodes from the position map - use this little doo-dad to make a list
[Box Map Maker.xlsx](https://github.com/ArctosDB/arctos/files/7645743/Box.Map.Maker.xlsx)
 That file is in the DGR Dropbox

**Comment by Jegelewicz** [comment]
Again, not a real solution because you have already scanned this stuff into a new box. Without #4161 I don't think there is a good answer for what you have now. You could remove all positions from the box and delete the barcode then re-create and use scary red box swapper - but then you are definitely losing container history....

**Comment by campmlc** [comment]
It would be faster and more accurate to scan twice that to do all the Excel and pdf manipulation to get the csv. I would like to request again that we fix the functionality of these tools so that operators do not have to do twice the work in the database as is required to physically move the samples. 
If #4161 can be implemented soon, I will wait for that. 
If not, and if @dusty can't magic these things where they are supposed to go, I will have to pull them back out of the cryotanks and rescan. 
Hoping there is a better solution here?

**Comment by dustymc** [comment]
@campmlc I can update those, but not tonight.

https://github.com/ArctosDB/arctos/issues/3632

**Comment by Jegelewicz** [comment]
#4161 has been implemented @campmlc can we close this?
