### ISSUE TITLE
Expand Check Container for AF numbers

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4163]
@KyndallH would really appreciate the same check container functionality for AF numbers that Mariel has for NKs

![image](https://user-images.githubusercontent.com/5725767/144687255-47097e53-7b6a-4c0b-8495-84a0435fe9b6.png)

Any reason we need to reserve this for only specific identifiers?

**Comment by dustymc** [comment]
>reserve this for only specific identifiers

That's built to deal with a specific legacy mess - it's matching label (which isn't necessarily unique). I don't think AF has that problem, but easy enough to add a link if it's useful - @KyndallH ? 

http://arctos.tacc.utexas.edu/findContainer.cfm?container_type=cryovial&container_label=NK%20218568

**Comment by campmlc** [comment]
For IF too? That would help resolve a lot of these legacy tissues.

**Comment by KyndallH** [comment]
Oh AF does!!! A bunch of AF tissues are at MSB. It would be great to be able to easily see what Mariel has scanned in down there.

**Comment by dustymc** [comment]
Sure - would be mildly useful to have a sorta-complete list before I go making changes, so pile on if there are other types...

**Comment by campmlc** [comment]
NEON organism ID? GAN number and ABQ Biopark ID? Collector number?

**Comment by campmlc** [comment]
Also helpful to do the % wildcard after the identifier with no space. Currently NK search is NK 12345 % which misses ones with no following tissue type.

**Comment by campmlc** [comment]
Can you do the collector number as "search anything with the following string of characters with wildcard before and after"?

**Comment by dustymc** [comment]
I can do whatever, but at some point the result is going to be CPU limited.

``NK 2 %`` runs in less than a second, ``NK 2%`` times out (and has the potential to break something, depending on what else is going on). Something like ``%MLC 2%`` sorta works, and might work OK with different indexes, but those have a cost as well. (And it won't find ``MLC2`` and ``MLC{space-space}2`` and ``MLC-2`` and .... so there's some potential for user confusion as well).

It would be useful for you to play with it a bit, see if you can tighten up/clarify the requirements. Eg I presume you don't actually want ''collector number MLC:2", which is the pattern NK is using.

**Comment by campmlc** [comment]
Yes, I understand the issues with space vs no space vs hyphen, which is the
usual combination. That would be very cpu intensive to do as "or"? Would it
be possible to do this search for whatever as written, and users can tweak
search in the find container interface?
I'd be happy with requesting a search that emails me results if it times
out in the UI

**Comment by dustymc** [comment]
>users can tweak

Fair enough, this is "us" and "we" should have some understanding of that sort of thing.

**Comment by Jegelewicz** [comment]
Can we make a good error message for people who click this but don't have manage_container access?

From Slack (sigh)

> What's up with the 'check container' function associated with collector numbers?
> This was bothering Phyllis since there is no explanation and, since she doesn't have manager_container permissions it just goes to an error page.

Maybe - Sorry, this function is only available to Arctos users with manage_container permissions

**Comment by campmlc** [comment]
Sounds good.

**Comment by sharpphyl** [comment]
> Can we make a good error message for people who click this but don't have manage_container access?

That would be nice, but even better would be to get rid of it if the collection doesn't have "manage container" permissions.  It's just clutter for our collection.

<img width="837" alt="Screen Shot 2021-12-15 at 7 17 05 AM" src="https://user-images.githubusercontent.com/15368365/146202875-ff5665db-d8c1-4ac9-a192-576de7261e2d.png">

<img width="599" alt="Screen Shot 2021-12-15 at 7 19 12 AM" src="https://user-images.githubusercontent.com/15368365/146203159-c8147047-023f-4da4-94bb-eef0b68c18d8.png">
