### ISSUE TITLE
Feature Request - Add "verbatim agent" attribute search to Agent Search page

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#4164]
Discussed at the 12/2 AWG Issues Meeting: add a way to search on verbatim agents in the Arctos Search page (https://arctos.database.museum/agents.cfm)

Agent name cleanup efforts often merge initials or last name-only agents to "unknown." However, if an operator subsequently adds a new agent with robust name data, it is difficult for them to know that there may be a low-data variant that was previously merged to "unknown" since the "verbatim_collector" name is saved under Attributes. This is a missed opportunity to fill in information gaps.

Ideally, when someone searches "Any part of any name" or "Agent Name" fields in the agent search page, attribute = "verbatim_collector" should also be queried. There could also be a separate search field for "verbatim_collector," but I think having the attribute searched in the background of all agent searches would be the most useful for cleanup. This functionality should also work when creating new agents (the "force creation" pop-up should indicate potential name matches within attribute = verbatim agent).

Also, we should change "verbatim_collector" to something more general, "verbatim_agent" (or code it to reflect the original value selected, e.g. verbatim_preparator, verbatim_maker).

**Priority**
normal

**Comment by dustymc** [comment]
>change "verbatim_collector" to something more general, "verbatim_agent"

https://github.com/ArctosDB/arctos/issues/1492

https://handbook.arctosdb.org/documentation/agent.html#verbatim-collector-attribute
