### ISSUE TITLE
Changing subsample part name via Bulkload Loan Items

### ISSUE THREAD

**Issue by kderieg322079** [ArctosDB/arctos#4166]
I have a loan of 50 bird skins and each specimen will have 1-2 feathers subsampled for consumptive analysis. When I add the specimens to the loan and subsample all skins, the subsample part name is "skin" but I would like to change the subsample part name to "feather" since that is the specific material being subsampled and ultimately consumed. Is there a way to do this with the Bulkload Loan Items template?

![image](https://user-images.githubusercontent.com/82051765/144929545-41f6617e-b4bc-4c5b-a3e7-86a69c2d6b25.png)

**Comment by Jegelewicz** [comment]
@kderieg322079 this field only accepts true or false and will create a subsample of "skin"

> Create a subsample of the specified part and add it to the loan, rather than adding the specified part itself. Boolean; acceptable values are "true" and "false"; default value is false. NOTE: you may remove this column from the CSV Upload to use the default value. If the column is included then a value must be supplied. 

I suggest that you use the [part bulkloader](https://arctos.database.museum/tools/BulkloadParts.cfm?action=ld) to create the subsamples, then add them to the loan. You can use the parent_part_name field in the template to associate the feather parts with the skin.

![image](https://user-images.githubusercontent.com/5725767/144931889-6a52a05c-05ce-411c-b15f-b1eb9deffccd.png)

**Comment by Jegelewicz** [comment]
Let me know if this makes no sense!

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/4124

**Comment by kderieg322079** [comment]
Yes! That makes sense. Thank you so much.
