### ISSUE TITLE
Arctos Down - Planned Outage TODAY 12/6 at 5 pm CT ( 2 pm AK/ 3 pm PT/ 4pm MT)

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#4167]
Arctos requires approximately one hour of downtime to implement PostGIS-- 

## Planned Outage
 - Date and time outage will begin: TODAY 12/6 at 5 pm CT
 - Reason for outage: to enable PostGIS
 - Date and time outage is expected to end: 6 pm CT
 - Expected behavior during and after the outage: No access to Arctos during outage-- please save all your work before the outage. Once PostGIS is installed then a suite of issues can be resolved. Has been tested.

## Communication before/during outage
- [x] Pin this issue
- [x] Banner updated @jegelewicz 
- [x] Email sent to AWG 
- [x] Email sent to Arctos Google Group 
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [x] Unpin this issue
- [x] Banner updated @jegelewicz
- [x] Email sent to AWG 
- [x] Email sent to Arctos Google Group 
- [ ] Tweet @lin-fred (@mkoo backup)
- [x] Close this issue when above are complete

**Comment by dustymc** [comment]
Arctos is back up.
