### ISSUE TITLE
Log In not functioning?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4168]
When I select the Log In button from the main search page, I get the Log in screen. Enter my username and password and select Sign In and nothing ever happens.

![image](https://user-images.githubusercontent.com/5725767/145087607-b4f2f012-9339-4d28-9845-6b626b035105.png)

**Comment by Jegelewicz** [comment]
OK - cleared cache and it worked?

**Comment by mkoo** [comment]
try again?
there did seem to be some settling needed (also my FF was having some
pop-up complaints
working now for me

**Comment by dustymc** [comment]
<img width="628" alt="Screen Shot 2021-12-07 at 10 44 37 AM" src="https://user-images.githubusercontent.com/5720791/145087925-60bb013f-b075-40ff-991c-4f4eae3b42c3.png">

It's working for me, and apparently a fair number of other users. Arctos is seeing a lot of garbage traffic and there is some network congestion, wild guess you got caught up in that. TACC's aware, I'll see if I can elevate, and I'll poke around a bit more to see if I can recreate.
