### ISSUE TITLE
400 Error - Bulkload specimen review

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#4170]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I get a 404 error trying to review bulkload specimen event data that failed to load.

**To Reproduce**
1. Load CSV to specimen event bulkload tool
2. Review data and load
3. 3 events failed to load
4. Trying to click review, get csv, or delete returns a 404 error.

**Expected behavior**
I shouldn't get a 404 error.

**Data**
Data are still in the tool. [https://arctos.database.museum/tools/BulkloadSpecimenEvent.cfm](https://arctos.database.museum/tools/BulkloadSpecimenEvent.cfm). I've figured out what my mistake was (switched began and end date) and already uploaded the new csv to fix the error, but I can't even delete the old data.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: tried both Chrome and Firefox
 - Version: 96.0.4664.45 and 94.0.2 respectively

**Additional context**

**Comment by Jegelewicz** [comment]
When I try to delete them I get

![image](https://user-images.githubusercontent.com/5725767/145122108-c8188206-71c4-4d19-b21a-9da8c6a0c00c.png)

**Comment by dustymc** [comment]
Form needs rebuilt in a more-current version.

>no georeference because cultivated

Pretty please?

https://github.com/ArctosDB/arctos/issues/2068

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
sorry, typed wrong error number

**Comment by ccicero** [comment]
I too am getting a 404 error when trying to review, get CSV, or delete a record pending in https://arctos.database.museum/tools/BulkloadOtherId.cfm

@dustymc can you please delete my one record there? Thanks!

**Comment by dustymc** [comment]
I'm working on a rebuild of the specimen-event loader which will accept coordinates in any known format and convert/reproject as necessary, along with bringing it into the current version. Any "real" data - stuff that's loaded, stuff that failed, whatever - that might be hanging around would be useful for testing, if anyone is willing to share.

**Comment by Jegelewicz** [comment]
Here are some records with UTM. I loaded them without UTM (it is in verbatim only). Will they help?
[ACUNHC_Mammal Catalog_upload_utm.csv](https://github.com/ArctosDB/arctos/files/7915998/ACUNHC_Mammal.Catalog_upload_utm.csv)

**Comment by dustymc** [comment]
@mvzhuang @Nicole-Ridgwell-NMMNHS @diannakrejsa this required rebuilding the table, here are your data from the old format. Let me know if you need any help getting them where they need to be.

[cf_temp_specevent.csv.zip](https://github.com/ArctosDB/arctos/files/7929900/cf_temp_specevent.csv.zip)
