### ISSUE TITLE
Error on log out

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4173]
When I log out of Arctos I am getting this error

An error occurred while processing this page!
Check the Arctos Handbook for more information on errors.

This message has been logged as FDDE5FF2-E24E-4BAA-9037D36950609CB5 Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue. 

After this, I am unable to log in until I shut down any tabs that are related to Arctos, open a new tab and then log in.

Using Firefox

Does this happen to anyone else?

**Comment by dustymc** [comment]
>error

https://github.com/ArctosDB/arctos/issues/4107#issuecomment-974474810

>shut down any tabs that are related 

That's got to be some extension or similar.
