### ISSUE TITLE
Arctos Down - unplanned 12/8

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#4174]
unplanned outage; Dusty is aware and on it. Messages to TACC in progress. (@dustymc feel free to add details if you want)

## Unplanned Outage
 - Date and time outage discovered: 12/8 2:15 PT
 - Describe the outage (Arctos down or only some part not working?):
Arctos production is offline; test is fine

## Communication before/during outage
- [x] Pin this issue
- [x] Banner updated @jegelewicz 
- [x] Email sent to AWG 
- [x] Email sent to Arctos Google Group 
- [x] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [x] Unpin this issue
- [x] Banner updated @jegelewicz
- [x] Email sent to AWG 
- [x] Email sent to Arctos Google Group 
- [x] Tweet @lin-fred (@mkoo backup)
- [x] Close this issue when above are complete

**Comment by lin-fred** [comment]
tweet sent

**Comment by mkoo** [comment]
Appears Dusty and Chris' efforts paid off....
Removing notice! Please retweet it's back

**Comment by lin-fred** [comment]
done
