### ISSUE TITLE
default data entry screen

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4175]
Currently "old" screen has a big red box link to new.

Reverse that, point links to new screen, add big red box to old.

Needs scheduled.

**Comment by dustymc** [comment]
From https://github.com/ArctosDB/arctos/issues/4376#issuecomment-1050147458

>We should bring it to the AWG to get the final say.
Do you mean to the bulkloader edits as well? I've noticed that swings back to the old form instead of going to the new form?
We've published in the Newsletter and social media.

>edits as well? I've noticed that swings back to the old form

Both are available; the ID is old, the 'new' link is new. The 'old' will stop functioning in this capacity at some point as well; it's the same form as the old entry screen.

<img width="350" alt="Screen Shot 2022-02-24 at 10 41 07 AM" src="https://user-images.githubusercontent.com/5720791/155587065-f3fa6ae5-0f58-41a5-8abe-b70bcae4c35e.png">


@ArctosDB/arctos-working-group-officers   how to proceed?

**Comment by ewommack** [comment]
> Both are available; the ID is old, the 'new' link is new. The 'old' will stop functioning in this capacity at some point as well; it's the same form as the old entry screen.

Oh! I didn't even realize that. I just always click on the ID number to review.

**Comment by ewommack** [comment]
@dustymc do you think we could gather all the open and closed issues about the new data entry screen together somehow in Github, maybe in a project? I feel like there are a bunch of little tips that are peppered through out each issue, but that do not specifically relate to the issue mentioned. It might be really helpful for when we get around to writing up documentation and manuals to be able to gather all the little bits of info together.

**Comment by dustymc** [comment]
If you want to start a project (label, whatever) I'll try to add things as I come across them.

Or https://github.com/ArctosDB/arctos/issues?q=is%3Aissue+label%3AFunction-DataEntry%2FBulkloading+sort%3Aupdated-desc exists, but it's probably too general to be very useful.

**Comment by ewommack** [comment]
I created a project: https://github.com/orgs/ArctosDB/projects/12?add_cards_query=is%3Aopen
My first project! Hopefully this is helpful.
