### ISSUE TITLE
Code Table Request - New Collection Contact Role: Arctos Council Member

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4176]
**Goal**
Easily determine who is the council member for any collection in Arctos

**Context**
From AWG Meeting today

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_contact_role

**Proposed Value**
Arctos Council Member

**Proposed Definition**
The agent who is the Arctos Council Member representative for this collection.

**Priority**
[  Please choose a priority-label to the right.  ]

**Comment by ccicero** [comment]
Approved at CT meeting 20 Jan 2022. Value added to ctcoll_contact_role.
