### ISSUE TITLE
Arctos Down - TOMORROW Friday 8AM CT

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4177]
## Planned Outage
 - Date and time outage will begin: 8 AM central, tomorrow Friday Dec 10
 - Date and time outage is expected to end: ~5 minutes
 - Reason for outage: Increase database resources
 - Expected behavior during and after the outage: May not be noticeable, probably brief outage

# Please let me know ASAP if this is problematic

We can reschedule if necessary.

## Communication before/during outage
- [x] Pin this issue
- [ ] Banner updated @jegelewicz 
- [x] Email sent to AWG 
- [x] Email sent to Arctos Google Group 
- [x] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @jegelewicz
- [ ] Email sent to AWG 
- [ ] Email sent to Arctos Google Group 
- [x] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by Jegelewicz** [comment]
@dustymc done?

**Comment by dustymc** [comment]
Yes done
