### ISSUE TITLE
Difficulty with Log In

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4181]
Ever since the new log in procedure has been implemented I have had a series of frustrations when attempting to log in. I select Log In from the top right of the header, enter my username and password, select Sign In and nothing happens. If I close my browser and repeat two or three times, it eventually works, but I am wasting a lot of time on this.

Has anyone else experienced this issue?

If it is just me, what the heck? Any ideas for what might cause this?

**Comment by Jegelewicz** [comment]
OS = Windows 10
Browser = Firefox Version 95.0 (64 bit)

**Comment by Jegelewicz** [comment]
Also, I seem to be getting kicked off before the 90 minute window is up.

**Comment by jldunnum** [comment]
Also have been having this issue

______________________________________________________________

Jonathan L. Dunnum Ph.D.
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by Jegelewicz** [comment]
Just wen to search geography and

![image](https://user-images.githubusercontent.com/5725767/145612509-4eed6692-b66d-43e0-acca-25a0f8e72162.png)

**Comment by dustymc** [comment]
I don't think it's the form, which is just the old page-form (a fairly normal POST operation) in a modal window.

There is some sort of intermittent issue which might be causing this, I've been working with TACC to localize that, replacing the webserver seems like the obvious next step. The candidate for that is running at http://arctos.tacc.utexas.edu (test.arctos.database.museum should be sending you there, we're working on making that better as well) - testing is greatly appreciated.

The connection termination seems related to some other work, but please let us know if you see it again.

**Comment by krgomez** [comment]
I am having this log in issue too.

**Comment by SerinaBrady** [comment]
I'm also having the log-in issue. I thought it was just my internet, but I guess not! I have to close my tabs and then re-open

**Comment by Jegelewicz** [comment]
I actually haven't had the problem for a couple of days now...so odd!!!

**Comment by sharpphyl** [comment]
I'm still having the problem.  Have to totally clear all data, close Arctos and Chrome (happens on Firefox too), try to login, nothing happens, close that and click Profile which won't let me log in, but sometimes the next try works.  Or it takes me to a welcome page but not the search screen, but on the next click I'm in.  Usually takes several minutes to get in.  If I leave for 5-10 minutes, I'm usually knocked out and have to start the process all over even though it shows 40+ minutes remaining.

**Comment by Jegelewicz** [comment]
Dang - that hasn't happened to me for a while now - @dustymc any ideas?

**Comment by mkoo** [comment]
@dustymc will move to production new framework from test where it has been performing well. This will hopefully address wonkiness with log in popup window. Scheduled for this friday in coordination wtih TACC
