### ISSUE TITLE
Remove requirement for date and determiner on collection object attributes

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4184]
According to the Attribute Bulkloader at https://arctos.database.museum/tools/BulkloadAttributes.cfm?action=ld
the attribute date and determiner are highly recommended but not required. 
But users are getting errors in Data Entry if they leave the date field blank:
![image](https://user-images.githubusercontent.com/14808196/145650469-a85f7074-bfff-4d4f-8b70-e5b53d572d80.png)

We need the option of leaving this blank for no data records. In this case the data may eventually be found, but at the moment all we know if that the record and the attribute were recorded sometime after 1995.  If the actual value is 2007, putting 1995 as the value seems like it introduces confusion. Recommend we only require dates when they are know for everything except verbatim, begin and end dates, because the latter allow for recording the degree of uncertainty.

**Comment by dustymc** [comment]
It's "required" because someone thought it should be at some point, it would be good to decide how to handle this as a Community.

I can confirm that date is *not* required in the table.

I don't have much opinion and this certainly isn't my decision to make, unassigning me.

**Comment by acdoll** [comment]
> option of leaving this blank for no data records

For old specimens or even recent transfers, we often have attribute data, but no information on when they were recorded. I vote this is made optional in data entry. I'm fine with keeping determiner as required because you can always enter unknown - that's not an option for dates.

**Comment by campmlc** [comment]
I agree. We don't require these for part attributes. Let's be consistent.

**Comment by Jegelewicz** [comment]
I just loaded some records earlier this week and was admonished for not including an attribute date - it is currently required.

**Comment by campmlc** [comment]
Interesting - I loaded some without a date with no rejection!

**Comment by Jegelewicz** [comment]
I don't think this needs further discussion. It would be lovely if we all had these dates, but we don't and we shouldn't be required to make up data.
