### ISSUE TITLE
Clone by barcodes fails

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#4185]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

using clone by barcodes and got this error

Message: ERROR: INSERT has more expressions than target columns Position: 38
Detail:
Check the Arctos Handbook for more information on errors.

This message has been logged as 54DF19E5-76C1-4108-A82C5EDF5EFF6301 Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue. 

I had created the seed & saved it in the BL & found it using the clone by barcodes tool. Then I scanned in 8 barcodes to make 8 clones of the seed. I clicked 'finalize clone creation' and got that error.

![Untitled](https://user-images.githubusercontent.com/9099827/145651611-e951cdcf-17aa-4145-85fe-63ad11cc9544.png)

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.
HIGH

**Comment by dustymc** [comment]
Rebuilt the table, should work now.
