### ISSUE TITLE
Code Table Request - new Other_id_type

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#4187]
Please add a new Other_id_type of Volume ID

**Goal**
In preparation for cataloging field notebooks we need to track assigned Volume IDs

**Context**
No other identifier currently fits this definition 

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type#

**Proposed Value**
Volume ID

**Proposed Definition**
An identifier assigned to a collection of original notes, journal or other written material. For example, the MVZ Archives assigns volume IDs to field notebooks, which in turn is a set of notebook sections organized by geography, by author, or by date.

**Collection type**
MVZ Archives (will be MVZ:ARCH)

**Attribute data type**
numerical

**Comment by ccicero** [comment]
@Jegelewicz Can we discuss at our CT meeting on Thursday?

**Comment by ccicero** [comment]
merge #4227
