### ISSUE TITLE
data entry autopopulates original lat long units

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#4191]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I don't know if this is fixed in the new data entry, but a persistent bug in data entry is that it is a game to try to use a non-georeferenced locality without arctos putting "decimal degrees" making the entry fail and turn pink. So, I have to go change it to nothing, sometimes multiple times. 

**To Reproduce**
Enter data and select a LocID that has no georeference, e.g. "no specific locality". 

**Expected behavior**
I expect all the fields in the locality to match those from the LocID table. 

**Screenshots**
Attached. 

**Desktop (please complete the following information):**
 - mac
 - chrome

**Priority**
High, but hoping this is fixed in new entry screen
<img width="382" alt="Screen Shot 2021-12-14 at 3 43 34 PM" src="https://user-images.githubusercontent.com/5749672/146097679-14c9d827-a29c-403d-97ec-060a41cadd14.png">

**Comment by dustymc** [comment]
Don't hope, try the new screen!

https://github.com/ArctosDB/arctos/issues/4175
