### ISSUE TITLE
SQL query needed for report

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4192]
@dustymc  Can you please run a query for how many cryovials were scanned into the MSB Division of Genomic Resources (for first time) by year for last 5 years, representing how many specimens? 
I'm not sure how to get at the "first time" issue here  - what I need is cryovials transferred to DGR, even if they were originally scanned into position in other divisions.
Also possible to break the specimens down by MSB Division, e.g. how many Birds, Mammals, Fish, Herps, Parasites?
Any way I can get such a report tool added to Reports/Services?
Priority: High. Needed for annual report and grant submission.

**Comment by dustymc** [comment]
>MSB Division of Genomic Resources

Elaborate - ideally by providing the container_id.

>not sure how to get at the "first time" 

Me either - I'll see what I can come up with though.

>report tool added to Reports/Services?

I doubt it, I suspect this is going to take ridiculous amounts of CPU, but I'll keep that in mind if it turns out to be possible.

**Comment by campmlc** [comment]
Container barcode is DGR (collection).
Note that we do have cryovials that are scanned into boxes in other divisions, and then boxes are brought up and scanned into DGR freezers.
This metric is an essential component of my division annual report. In the past, I've had to estimate based on number of racks filled per year. I could really use a way to generate this regularly. This could be another query that could be done offline and then just send me a report when it is ready.

**Comment by campmlc** [comment]
container ID: https://arctos.database.museum/EditContainer.cfm?container_id=15300802

**Comment by dustymc** [comment]
Thanks.

So cryovial gets scanned into box in 1970, 2020 box gets scanned into something that's ultimately in DGR for the first time, you want to count the contents of the box - right?

**Comment by campmlc** [comment]
Yes, please!

**Comment by dustymc** [comment]
@campmlc the box-thing is I believe beyond my current abilities. There are a bunch of scattered "what do we need for reports-n-such?" issues, https://github.com/ArctosDB/internal/issues/50 is one of them but I think there's a better one, somewhere, however it works if you want that information then we need to do something different with the data, or I need to find a lot more time to figure out how to traverse history, or something. Maybe that could/should even be dumped in https://github.com/ArctosDB/arctos/issues/3632. Or let me know if you want me to keep flailing around, I've probably not yet exhausted every possibility...

I let the rest run with all the CPU it wanted for about 8 hours last night and it didn't get very far (but it didn't eat the DB, which is nice!). I stopped that this AM, and I now have a revised throttled version running in the background, hopefully unobtrusively - it claims it'll be done in about 90 hours, which probably means I won't get back to this until the new year.

@cjconroy re your email: I can likely modify these scripts to get whatever you need if you'll let me know details.

**Comment by campmlc** [comment]
I thought this was a query you've run for me in the past? No idea would take 90 hours?

**Comment by dustymc** [comment]
Do you happen to have old sql/issue/email/something?

**Comment by campmlc** [comment]
I just forwarded an interesting email thread from 2017 where Carla was
trying to figure this out by counting tissue part growth.
And here is the previous SQL you did for me just looking at cryovials. This
doesn't parse which ones are new to DGR, includes the massive DGR Locator
conversion and legacy barcoding efforts, etc.
It would be nice to compare with the super costly search you are running.
select to_char(PARENT_INSTALL_DATE,'YYYY'),count(*) from container where
container_type='cryovial' and institution_acronym in ('MSB','DGR') group by
to_char(PARENT_INSTALL_DATE,'YYYY') order by
to_char(PARENT_INSTALL_DATE,'YYYY');

**Comment by dustymc** [comment]
Thanks. I'm never sure if I'm being not pedantic enough or too pedantic, looks like maybe I chose the latter for this...

This one's cheap:

```
 select to_char(PARENT_INSTALL_DATE,'YYYY'),count(*) from container where container_type='cryovial' and institution_acronym in ('MSB','DGR') group by to_char(PARENT_INSTALL_DATE,'YYYY') order by to_char(PARENT_INSTALL_DATE,'YYYY');
 to_char | count  
---------+--------
 2003    |      1
 2014    |   4710
 2015    |   7343
 2016    |   5195
 2017    | 258467
 2018    | 154522
 2019    |  21699
 2020    |  23195
 2021    |  39174
(9 rows)

Time: 881.155 ms
```

The other one is a couple orders of magnitude more expensive than it was because calculating "tissueness" takes two complex joins (instead of a flag) - it takes a little over 8 seconds to run.

```
create table temp_tiss_rpt as
select
  case when substr(began_date,1,4) = substr(ended_date,1,4) then
    substr(ended_date,1,4)
  else
    '1234567890'
  end AS  yr,
  guid_prefix,
  count(distinct(specimen_part.collection_object_id)) numberTissueParts,
  count(distinct(specimen_part.derived_from_cat_item)) numberCatalogedItems
from
  coll_object
  inner join flat on coll_object.collection_object_id=flat.collection_object_id
  inner join specimen_part on flat.collection_object_id=specimen_part.derived_from_cat_item 
  inner join specimen_part_attribute on specimen_part.collection_object_id=specimen_part_attribute.collection_object_id and attribute_type='preservation'
  inner join ctpart_preservation on specimen_part_attribute.attribute_value=ctpart_preservation.part_preservation and ctpart_preservation.tissue_fg=1
  left outer join ctpart_preservation notiss on specimen_part_attribute.attribute_value=notiss.part_preservation and notiss.tissue_fg=0
where
   notiss.part_preservation is null and
  specimen_part.SAMPLED_FROM_OBJ_ID is null
group by
   case when substr(began_date,1,4) = substr(ended_date,1,4) then
    substr(ended_date,1,4)
  else
    '1234567890'
  end  ,
  guid_prefix
order by
   case when substr(began_date,1,4) = substr(ended_date,1,4) then
    substr(ended_date,1,4)
  else
    '1234567890'
  end ,
  guid_prefix
;
```

[temp_tiss_rpt.csv.zip](https://github.com/ArctosDB/arctos/files/7736338/temp_tiss_rpt.csv.zip)

@cjconroy this is probably what you want.

The thing that's still grinding away in the background is making 7 joins to get from the tube to the catalog record, but I think the real killer is that PG doesn't have enough memory to pull several copies of container (currently 10,864,129 records) in along with everything else, so has to go to disk for swap space. (There's no actual spinny disk on the system but that's still somehow slow.) Whatever, IDK, maybe the hamsters are getting tired, whatever the reason it takes more resources than I can immediately access to do some stuff, if we need to do that stuff then we need to find some sort of workaround or remodel or something. I'll let the other thing finish, we can compare, it should be different but it might be "disappears in the rounding errors" different.

**Comment by cjconroy** [comment]
This looks great. If I want to split by collection, besides changing MSB to MVZ, can I add some text like collection_code is mamm?

**Comment by dustymc** [comment]
You can get collections from the attachment - let me know if that's not what you need.

**Comment by campmlc** [comment]
@dustymc looks like the best search for what I'm trying to get at is the following, but is there a way to constrain this so that I only see MSB or DGR containers that were scanned into the MSB Division of Genomic Resources (any child of barcode DGR?)

 select to_char(PARENT_INSTALL_DATE,'YYYY'),count(*) from container where container_type='cryovial' and institution_acronym in ('MSB','DGR') group by to_char(PARENT_INSTALL_DATE,'YYYY') order by to_char(PARENT_INSTALL_DATE,'YYYY');
 to_char | count  
---------+--------
 2003    |      1
 2014    |   4710
 2015    |   7343
 2016    |   5195
 2017    | 258467
 2018    | 154522
 2019    |  21699
 2020    |  23195
 2021    |  39174
(9 rows)

**Comment by dustymc** [comment]
```
with recursive subordinates as (
    select
        container.container_id,
        container.container_type,
        container.parent_install_date,
        container.institution_acronym,
        0 lvl
    from
        container
    where
        container.barcode='DGR'
    union
    select
        e.container_id,
        e.container_type,
        e.parent_install_date,
        e.institution_acronym,
        s.lvl + 1 lvl
    from
        container e
        inner join subordinates s ON s.container_id = e.parent_container_id
    -- this prevents infinite recursion
    where lvl<20
) select 
   to_char(parent_install_date,'YYYY'),
   count(*) c
from 
    subordinates 
where 
    container_type='cryovial' and 
    institution_acronym in ('MSB','DGR') 
group by 
    to_char(parent_install_date,'YYYY') 
order by 
    to_char(parent_install_date,'YYYY')
;

 to_char |   c    
---------+--------
 2014    |   4706
 2015    |   6876
 2016    |   4346
 2017    | 253784
 2018    | 153896
 2019    |  19893
 2020    |  16988
 2021    |  29676
 2022    |   4323
```

**Comment by dustymc** [comment]
added to cheatsheet
