### ISSUE TITLE
Report not pulling information

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#4195]
I have a bit of a mystery; I am trying to print tags from a report (CHAS_tag_front) for Accession 2020.9. There are 9 specimens associated with this record, but when I run the report:
- only 7 out of 9 appear to be printed (2020.9.8 and 2020.9.9 do not appear at all)
- one appears with the code for italics and line break still visible (2020.9.6)

![Screenshot 2021-12-15 113401](https://user-images.githubusercontent.com/93737929/146236995-b4bddb79-4cc2-4cd1-851d-7b006cd092f3.jpg)

I tried pulling the report of the individual catalog records for: 2020.9.6, 2020.9.8, 2020.9.9
- 2020.9.6 still shows up with the code
- creating the report for 2020.9.8 and 2020.9.9 (individually) shows a blank page

I also looked at the handler SQL and it's supposed to pull coordinates as well (which most have), but it's not appearing on the tag (it could be because it's outdated?). But the vanishing tags are more of an issue. Has anyone else experienced this? and/or know of a solution?

Thanks!

**Comment by dustymc** [comment]
https://arctos.database.museum/guid/CHAS:Bird:2020.9.8 has no parts, your report is hinged on parts.

**Comment by wellerjes** [comment]
Just updated 2020.9.8 and 2020.9.9 to include parts; thanks!

2020.9.6 and 2020.9.8 have the same issue now of the location showing up with bold and line break code.

**Comment by wellerjes** [comment]
Figured it out! It didn't like the special character & in Noodles & Company; updated it to "and" and it's fixed.
