### ISSUE TITLE
Field in Bulkloader Builder not allowed in Bulkloader

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4197]
Attempting to load degrees decimal minutes using the new fields provided in the bulkloader builder

![image](https://user-images.githubusercontent.com/5725767/146304403-3d03f528-462e-4af4-adac-8a6096cc4a95.png)

And get this error

> An error occurred while processing this page!
> Message: Error invoking external process
> Detail: psql:/usr/local/webroot/temp/excopy_jegelewicz_20211216031244644_605.sql:1: ERROR: column "dec_lat_deg" of relation "bulkloader_stage" does not exist
> Check the Arctos Handbook for more information on errors.
> 
> This message has been logged as 12A6AF4F-DDDB-4C50-82D6B8DC1F4CB3B7 Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue. 

Can we load degrees decimal minutes?

**Comment by dustymc** [comment]
Tables are cleaned up and should be functional, the selector shortcut will work in next release.

**Comment by Jegelewicz** [comment]
@dustymc it looks like this may be working now - at least the bulkloader accepted the columns, BUT now all of my degrees dec. minutes AND deg. min. sec. coordinates are throwing an error.

![image](https://user-images.githubusercontent.com/5725767/146962681-a6607df5-2766-46bd-b4a0-3528463d038f.png)
![image](https://user-images.githubusercontent.com/5725767/146962779-23e93828-a59b-46cc-8426-cd2e8bcee011.png)

**Comment by dustymc** [comment]
>error

Data?

**Comment by Jegelewicz** [comment]
Data is in the bulkloader - ACUNHC:Mamm records

**Comment by dustymc** [comment]
I wouldn't have asked if I could see that....

Should be fixed.

**Comment by Jegelewicz** [comment]
DOH - sorry, I forget you are not all-seeing....

**Comment by Jegelewicz** [comment]
OK - so I am down to about 80 problems which I downloaded so I can fix them, but I cannot change some of them to status=DELETE?

![image](https://user-images.githubusercontent.com/5725767/147974376-21f67db5-075a-4440-bccc-40eb4d7c3e61.png)

**Comment by dustymc** [comment]
Neato....

I'm not sure what I could do about that which wouldn't also eventually result in "my coordinates disappeared." I'm certainly up for clever ideas, but this may just need documented.

The normal path out is to remove the coordinates, or let me know what you want gone and I can just nuke them.

**Comment by Jegelewicz** [comment]
So this particular "status" can never be changed? I just want these gone from the bulkloader so I can re-load them.

**Comment by Jegelewicz** [comment]
@dustymc can you help me get rid of the ACUNHC:Mamm records (there are 30) in the bulkloader?

**Comment by dustymc** [comment]
done
