### ISSUE TITLE
How to bulk name collecting events?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4198]
I need to download collecting event IDs for 1500 host records and use them to populate an upload of parasite records that share the same CE ID. I used to be able to do this with no problem. But my understanding is now the CE Id is unstable, and to ensure permanence in order to map to the correct host event, I should name it. Obviously, I don't want to do this one by one. Is there a tool to bulk assign names to existing collecting events?
It would be really nice to be able to click some sort of button to autoassign the random CE ID Arctos gives at a moment in time as a collecting event name. I certainly don't want to have to "make up" names for these 1500 random events.
Help?
Priority - high. Holding up bulkloading a large series of records for a grant funded project.

**Comment by Jegelewicz** [comment]
I have no idea if this is the best thing, but do a search for the current records. Once you have them, under manage select Related CollectingEvent

Then use the Manage event name button and auto assign them names.

**Comment by Jegelewicz** [comment]
Record yourself doing it so we can have a tutorial!
