### ISSUE TITLE
Bulk load Parts issue

### ISSUE THREAD

**Issue by SerinaBrady** [ArctosDB/arctos#4199]
Hi, 
I am trying to bulk load parts for the ASNHC Mammal catalog records I loaded yesterday (ASNHC 20476-20600). It keeps saying "catalog record not resolved," yet when I search on the catalog record, it exists as a record in Arctos (not stuck in the bulk loader). It says this for all the 268 records. Any help would be appreciated!
Thanks, 
Serina

**Comment by dustymc** [comment]
You need ASNHC:Mamm not Mammal

**Comment by SerinaBrady** [comment]
Thank you!
