### ISSUE TITLE
Preferred Taxonomy Sources

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4201]
@dustymc it was recently brought to my attention that there is at least one collection without a preferred taxonomy source. Can you SQL me a list of all collections that don't have at least one preferred taxonomy source?

**Comment by dustymc** [comment]
```
select guid_prefix,string_agg(source,'|' order by preference_order) from collection left outer join collection_taxonomy_source on collection.collection_id=collection_taxonomy_source.collection_id group by guid_prefix order by guid_prefix;
  guid_prefix  |                                           string_agg                                           
---------------+------------------------------------------------------------------------------------------------
 ACUNHC:Bird   | Arctos
 ACUNHC:Ento   | WoRMS (via Arctos)|Arctos
 ACUNHC:Fish   | Arctos
 ACUNHC:Herp   | Arctos
 ACUNHC:Inv    | WoRMS (via Arctos)|Arctos
 ACUNHC:Mamm   | Arctos
 ACUNHC:Paleo  | WoRMS (via Arctos)|Arctos
 ALMNH:Anc     | Arctos|Arctos Culture|Nomenclature 4.0 (via Arctos)|Getty AAT (via Arctos)|Dana 8 (via Arctos)
 ALMNH:Arc     | Arctos
 ALMNH:Bird    | Arctos
 ALMNH:EH      | Nomenclature 4.0 (via Arctos)|Getty AAT (via Arctos)|Arctos|Arctos Plants
 ALMNH:Ento    | Arctos
 ALMNH:ES      | Arctos|Arctos Plants|WoRMS (via Arctos)
 ALMNH:Geo     | Arctos|Dana 8 (via Arctos)|Heys CIM (via Arctos)|Nickel-Strunz 10 (via Arctos)
 ALMNH:Herp    | Arctos
 ALMNH:Inv     | WoRMS (via Arctos)|Arctos|Arctos Plants
 ALMNH:Mamm    | Arctos
 ALMNH:Paleo   | Arctos|Arctos Plants|WoRMS (via Arctos)|Arctos Ichnology
 APSU:Bird     | Arctos
 APSU:Fish     | Arctos
 APSU:Herp     | Arctos
 APSU:Mamm     | Arctos
 ASNHC:Bird    | Arctos
 ASNHC:Herb    | Arctos
 ASNHC:Herp    | Arctos
 ASNHC:Mamm    | Arctos
 ASNHC:Para    | Arctos
 ASUMZ:Bird    | Arctos
 ASUMZ:Bivalve | Arctos
 ASUMZ:Ento    | Arctos
 ASUMZ:Fish    | Arctos
 ASUMZ:Herp    | Arctos
 ASUMZ:Invert  | Arctos
 ASUMZ:Mamm    | Arctos
 BYU:Bird      | Arctos
 BYU:Fish      | Arctos
 BYU:Herp      | Current Reptile Classification|Arctos
 BYU:Mamm      | Arctos
 BYUObs:Bird   | Arctos
 BYUObs:Herp   | Current Reptile Classification|Arctos
 BYUObs:Mamm   | Arctos
 BYU:Teach     | Current Reptile Classification|Arctos
 CHAS:Art      | Getty AAT (via Arctos)
 CHAS:Bird     | Arctos
 CHAS:Egg      | Arctos
 CHAS:EH       | Arctos
 CHAS:Ento     | Arctos
 CHAS:ES       | Arctos
 CHAS:Fish     | Arctos
 CHAS:Herb     | Arctos Plants
 CHAS:Herp     | Arctos
 CHAS:Inv      | Arctos
 CHAS:Mamm     | Arctos
 CHAS:Teach    | Arctos
 COA:Bird      | Arctos
 COA:Egg       | Arctos
 COA:Ento      | Arctos
 COA:Herp      | Arctos
 COA:Mamm      | Arctos
 COA:Rept      | Arctos
 DGR:Bird      | Arctos
 DGR:Ento      | Arctos
 DGR:Mamm      | Arctos
 DMNS:Bird     | Arctos
 DMNS:Egg      | Arctos
 DMNS:Herp     | Arctos
 DMNS:Inv      | WoRMS (via Arctos)|Arctos
 DMNS:Mamm     | Arctos
 DMNS:Para     | Arctos
 HMCM:Arthro   | 
 HMCM:Bird     | 
 HMCM:Geo      | 
 HMCM:Herb     | 
 HMCM:Herp     | 
 HMCM:Mamm     | 
 HWML:Para     | Arctos|TPT (via Arctos)|WoRMS (via Arctos)
 JSNM:Egg      | Arctos
 JSNM:Herb     | Arctos Plants
 JSNM:Paleo    | Arctos
 KNWR:Ento     | Arctos
 KNWR:Env      | Arctos
 KNWR:Herb     | Arctos Plants
 KNWR:Inv      | Arctos
 KNWRObs:Bird  | Arctos
 KNWRObs:Fish  | Arctos
 KNWRObs:Herb  | Arctos Plants
 KNWRObs:Mamm  | Arctos
 KWP:Ento      | Arctos
 LINGU:Herp    | Arctos
 MLZ:Bird      | Arctos
 MLZ:Egg       | Arctos
 MLZ:Fish      | WoRMS (via Arctos)|Arctos
 MLZ:Herb      | WoRMS (via Arctos)|Arctos
 MLZ:Mamm      | Arctos
 MLZObs:Fish   | Arctos
 MSB:Bird      | Arctos
 MSB:Fish      | Arctos
 MSB:Herp      | Arctos
 MSB:Host      | Arctos
 MSB:Inv       | WoRMS (via Arctos)|TPT (via Arctos)|Arctos
 MSB:Mamm      | Arctos
 MSBObs:Herp   | Arctos
 MSBObs:Mamm   | Arctos
 MSB:Para      | Arctos
 MVZ:Bird      | Arctos|WoRMS (via Arctos)
 MVZ:Egg       | Arctos|WoRMS (via Arctos)
 MVZ:Fish      | Arctos|WoRMS (via Arctos)
 MVZ:Herp      | Arctos|Current Reptile Classification|WoRMS (via Arctos)
 MVZ:Hild      | Arctos|Current Reptile Classification|WoRMS (via Arctos)
 MVZ:Mamm      | Arctos|WoRMS (via Arctos)
 MVZObs:Bird   | Arctos|WoRMS (via Arctos)
 MVZObs:Fish   | Arctos|WoRMS (via Arctos)
 MVZObs:Herp   | Arctos|Current Reptile Classification|WoRMS (via Arctos)
 MVZObs:Mamm   | Arctos|WoRMS (via Arctos)
 NBSB:Bird     | Arctos
 NCWRC:Bird    | Arctos
 NCWRC:Bivalve | WoRMS (via Arctos)
 NCWRC:Crust   | Arctos
 NCWRC:Ento    | Arctos
 NCWRC:Fish    | Arctos
 NCWRC:Gastro  | WoRMS (via Arctos)
 NCWRC:Herp    | Arctos
 NCWRC:Mamm    | Arctos
 NHSM:Arc      | Arctos Culture|Arctos|Getty AAT (via Arctos)|Nomenclature 4.0 (via Arctos)
 NHSM:Bird     | Arctos
 NHSM:Ento     | Arctos
 NHSM:Geol     | Heys CIM (via Arctos)
 NHSM:Herb     | Arctos Plants
 NHSM:Herp     | Arctos
 NHSM:Inv      | WoRMS (via Arctos)
 NHSM:Mamm     | Arctos
 NHSM:Paleo    | Arctos
 NMMNH:Bird    | Arctos
 NMMNH:Ento    | Arctos
 NMMNH:Fish    | Arctos
 NMMNH:Geol    | Heys CIM (via Arctos)|Dana 8 (via Arctos)|Nickel-Strunz 10 (via Arctos)|Arctos
 NMMNH:Herb    | Arctos Plants
 NMMNH:Herp    | Arctos
 NMMNH:Inv     | WoRMS (via Arctos)|Arctos|Arctos Plants
 NMMNH:Mamm    | Arctos
 NMMNH:Paleo   | Arctos Ichnology|Arctos|WoRMS (via Arctos)|Arctos Plants
 NMU:Bird      | Arctos
 NMU:Ento      | Arctos
 NMU:Fish      | Arctos
 NMU:Herb      | Arctos Plants
 NMU:Herp      | Arctos
 NMU:Mamm      | Arctos
 NMU:Para      | Arctos
 OWU:Amph      | Arctos
 OWU:Bird      | Arctos
 OWU:EH        | Arctos
 OWU:Ento      | Arctos
 OWU:ES        | WoRMS (via Arctos)|Arctos|Arctos Ichnology|Arctos Plants
 OWU:Fish      | WoRMS (via Arctos)|Arctos
 OWU:Geol      | Heys CIM (via Arctos)|Dana 8 (via Arctos)|Nickel-Strunz 10 (via Arctos)|Arctos
 OWU:Herb      | Arctos Plants|WoRMS (via Arctos)
 OWU:Inv       | WoRMS (via Arctos)|Arctos
 OWU:Mamm      | Arctos
 OWU:Para      | TPT (via Arctos)|WoRMS (via Arctos)|Arctos
 OWU:Rept      | Arctos|Current Reptile Classification
 PSU:Mamm      | Arctos
 STAR:Alg      | Arctos Plants
 STAR:Herb     | Arctos Plants
 TMCC:Bird     | Arctos
 TMCC:Ento     | Arctos
 TMCC:Fish     | WoRMS (via Arctos)
 TMCC:Herb     | Arctos Plants
 TMCC:Herp     | Arctos
 TMCC:Inv      | WoRMS (via Arctos)
 TMCC:Mamm     | Arctos
 TMCC:Teach    | Arctos
 UAF:Zooarch   | Arctos
 UAM:Alg       | Arctos Plants
 UAM:Arc       | Arctos
 UAM:Art       | UAM Art|Getty AAT (via Arctos)|Nomenclature 4.0 (via Arctos)|Arctos|Arctos Plants
 UAMb:Herb     | Arctos Plants
 UAM:Bird      | Arctos
 UAM:EH        | Nomenclature 4.0 (via Arctos)|Arctos|UAM Art
 UAM:Ento      | Arctos|WoRMS (via Arctos)
 UAM:Env       | Arctos
 UAM:ES        | Arctos
 UAM:Fish      | Arctos
 UAM:Herb      | Arctos Plants
 UAM:Herp      | Arctos
 UAM:Inv       | Arctos
 UAM:Mamm      | Arctos
 UAMObs:Bird   | Arctos
 UAMObs:EH     | Arctos
 UAMObs:Ento   | Arctos|WoRMS (via Arctos)
 UAMObs:Fish   | Arctos
 UAMObs:Mamm   | Arctos
 UA:Paleo      | Arctos
 UCM:Bird      | Arctos
 UCM:Egg       | Arctos
 UCM:Fish      | Arctos
 UCM:Herp      | Arctos
 UCM:Mamm      | Arctos
 UCM:Obs       | Arctos
 UCONN:Bird    | Arctos
 UCONN:Egg     | Arctos
 UCSC:Bird     | Arctos
 UCSC:Fish     | Arctos
 UC-SCFS:Bird  | Arctos
 UC-SCFS:Mamm  | Arctos
 UCSC:Herp     | Arctos
 UCSC:Mamm     | Arctos
 UMNH:Bird     | Arctos
 UMNH:Ento     | Arctos
 UMNH:Herp     | Arctos
 UMNH:Mala     | Arctos
 UMNH:Mamm     | Arctos
 UMNHObs:Mamm  | Arctos
 UMNH:Teach    | Arctos
 UMZM:Bird     | Arctos
 UMZM:Mamm     | Arctos
 UNCG:Mamm     | Arctos
 UNCG:Para     | Arctos
 UNM:MET       | Heys CIM (via Arctos)
 UNM:MIN       | 
 UNM:Paleo     | WoRMS (via Arctos)|Arctos
 UNR:Bird      | Arctos
 UNR:Egg       | Arctos
 UNR:Fish      | Arctos
 UNR:Herp      | Arctos
 UNR:Mamm      | Arctos
 USNPC:Para    | Arctos
 UTEP:Arc      | Arctos
 UTEP:Bird     | Arctos
 UTEP:Ento     | AntWiki (via Arctos)|Arctos
 UTEP:ES       | Arctos
 UTEP:Fish     | Arctos
 UTEP:Herb     | Arctos Plants
 UTEP:Herp     | Arctos
 UTEP:HerpOS   | Arctos
 UTEP:Inv      | WoRMS (via Arctos)|Arctos|Arctos Plants
 UTEP:Mamm     | Arctos
 UTEPObs:Ento  | Arctos
 UTEPObs:Herp  | Arctos
 UTEP:Teach    | Arctos
 UTEP:Zoo      | Arctos
 UWBM:Herp     | Arctos
 UWBM:Mamm     | Arctos
 UWYMV:Bird    | Arctos
 UWYMV:Egg     | Arctos
 UWYMV:Fish    | Arctos
 UWYMV:Herp    | Arctos
 UWYMV:Mamm    | Arctos
 UWZM:Bird     | Arctos
 UWZM:EH       | Arctos
 UWZM:Fish     | Arctos
 UWZM:Herp     | Arctos
 UWZM:Inv      | Arctos
 UWZM:Mamm     | Arctos
 UWZM:Paleo    | Arctos
 UWZM:Teach    | Arctos
 WNMU:Bird     | Arctos
 WNMU:Fish     | Arctos
 WNMU:Mamm     | Arctos
```

**Comment by Jegelewicz** [comment]
Invert collections NOT using WoRMS (via Arctos)

CHAS:Inv - sent email today @wellerjes 
ASUMZ:Bivalve - added
ASUMZ:Invert - added
KNWR:Inv - @mlbowser 
UAM:Inv - @jandreslopez
UMNH:Mala - This collection is not listed in the portal - was it removed?
UWZM:Inv - @campmlc

**Comment by sharpphyl** [comment]
While WoRMS (via Arctos) is the most current and accurate taxonomic source for marine specimens, switching from Arctos to WoRMS (via Arctos) will make significant changes in the higher classification.  That shouldn't be an issue unless your collection is physically organized by family.  @dustymc and @Jegelewicz It might be helpful for managers considering the change to have the following information
1) a list of taxon names that are in different families in the sources Arctos and WoRMS (via Arctos)
2) a list of taxon names that are valid in one source and invalid in the other

**Comment by Jegelewicz** [comment]
Yay - everybody has at least one now...

```
select guid_prefix,string_agg(source,'|' order by preference_order) from collection left outer join collection_taxonomy_source on collection.collection_id=collection_taxonomy_source.collection_id group by guid_prefix order by guid_prefix 
```
  | guid_prefix | string_agg
 -- | -- | -- 
1 | ACUNHC:Bird | Arctos
2 | ACUNHC:Ento | WoRMS (via Arctos)\|Arctos
3 | ACUNHC:Fish | WoRMS (via Arctos)\|Arctos
4 | ACUNHC:Herp | Arctos
5 | ACUNHC:Inv | WoRMS (via Arctos)\|Arctos
6 | ACUNHC:Mamm | Arctos
7 | ACUNHC:Paleo | WoRMS (via Arctos)\|Arctos
8 | ALMNH:Anc | Arctos\|Arctos Culture\|Nomenclature 4.0 (via Arctos)\|Getty AAT (via Arctos)\|Dana 8 (via Arctos)
9 | ALMNH:Arc | Arctos
10 | ALMNH:Bird | Arctos
11 | ALMNH:EH | Nomenclature 4.0 (via Arctos)\|Getty AAT (via Arctos)\|Arctos\|Arctos Plants
12 | ALMNH:Ento | Arctos
13 | ALMNH:ES | Arctos\|Arctos Plants\|WoRMS (via Arctos)
14 | ALMNH:Herp | Arctos
15 | ALMNH:Inv | WoRMS (via Arctos)\|Arctos\|Arctos Plants
16 | ALMNH:Mamm | Arctos
17 | ALMNH:Paleo | Arctos\|Arctos Plants\|WoRMS (via Arctos)\|Arctos Ichnology
18 | APSU:Bird | Arctos
19 | APSU:Fish | Arctos
20 | APSU:Herp | Arctos
21 | APSU:Mamm | Arctos
22 | Arctos:Entity | WoRMS  (via Arctos)\|Arctos\|Arctos Plants\|Arctos Ichnology\|Arctos Culture\|Heys  CIM (via Arctos)\|UAM Art\|Nomenclature 4.0 (via Arctos)
23 | ASNHC:Bird | Arctos
24 | ASNHC:Herb | Arctos
25 | ASNHC:Herp | Arctos
26 | ASNHC:Mamm | Arctos
27 | ASNHC:Para | Arctos
28 | ASUMZ:Bird | Arctos
29 | ASUMZ:Bivalve | WoRMS (via Arctos)\|Arctos
30 | ASUMZ:Ento | Arctos
31 | ASUMZ:Fish | Arctos
32 | ASUMZ:Herp | Arctos
33 | ASUMZ:Invert | WoRMS (via Arctos)\|Arctos
34 | ASUMZ:Mamm | Arctos
35 | BYU:Bird | Arctos
36 | BYU:Fish | Arctos
37 | BYU:Herp | Current Reptile Classification\|Arctos
38 | BYU:Mamm | Arctos
39 | CDSC:ARCH | Nomenclature 4.0 (via Arctos)
40 | CDSC:Ento | Arctos
41 | CDSC:Geol | Heys CIM (via Arctos)
42 | CDSC:Herb | Arctos Plants
43 | CDSC:Herp | Arctos
44 | CDSC:Inv | WoRMS (via Arctos)
45 | CDSC:Mamm | Arctos
46 | COA:Bird | Arctos
47 | COA:Egg | Arctos
48 | COA:Ento | Arctos
49 | COA:Herp | Arctos
50 | COA:Mamm | Arctos
51 | DGR:Bird | Arctos
52 | DGR:Ento | Arctos
53 | DGR:Mamm | Arctos
54 | JFBM:Fish | Arctos
55 | JFBM:Herp | Arctos
56 | JFBM:Inv | WoRMS (via Arctos)
57 | JSNM:Egg | Arctos
58 | JSNM:Herb | Arctos Plants
59 | JSNM:Paleo | Arctos
60 | LINGU:Herp | Arctos
61 | MMNH:Bird | Arctos
62 | MMNH:Mamm | Arctos
63 | MSB:Bird | Arctos
64 | MSB:Fish | Arctos
65 | MSB:Host | Arctos
66 | MSB:Inv | WoRMS (via Arctos)\|TPT (via Arctos)\|Arctos
67 | MSB:Mamm | Arctos
68 | MSB:Para | Arctos
69 | NBSB:Bird | Arctos
70 | NCWRC:Bird | Arctos
71 | NCWRC:Bivalve | WoRMS (via Arctos)
72 | NCWRC:Crust | Arctos
73 | NCWRC:Ento | Arctos
74 | NCWRC:Fish | Arctos
75 | NCWRC:Gastro | WoRMS (via Arctos)
76 | NCWRC:Herp | Arctos
77 | NCWRC:Mamm | Arctos
78 | NHSM:Arc | Arctos Culture\|Arctos\|Getty AAT (via Arctos)\|Nomenclature 4.0 (via Arctos)
79 | NHSM:Bird | Arctos
80 | NHSM:Ento | Arctos
81 | NHSM:Geol | Heys CIM (via Arctos)
82 | NHSM:Herb | Arctos Plants
83 | NHSM:Herp | Arctos
84 | NHSM:Inv | WoRMS (via Arctos)
85 | NHSM:Mamm | Arctos
86 | NHSM:Paleo | Arctos
87 | NMMNH:Bird | Arctos
88 | NMMNH:Ento | Arctos
89 | NMMNH:Fish | Arctos
90 | NMMNH:Geol | Heys CIM (via Arctos)\|Dana 8 (via Arctos)\|Nickel-Strunz 10 (via Arctos)\|Arctos
91 | NMMNH:Herb | Arctos Plants
92 | NMMNH:Herp | Arctos
93 | NMMNH:Inv | WoRMS (via Arctos)\|Arctos\|Arctos Plants
94 | NMMNH:Mamm | Arctos
95 | NMMNH:Paleo | Arctos Ichnology\|Arctos\|WoRMS (via Arctos)\|Arctos Plants
96 | NMU:Mamm | Arctos
97 | NMU:Para | Arctos
98 | OWU:Amph | Arctos
99 | OWU:Bird | Arctos
100 | OWU:EH | Arctos
101 | OWU:Ento | Arctos
102 | OWU:ES | WoRMS (via Arctos)\|Arctos\|Arctos Ichnology\|Arctos Plants
103 | OWU:Fish | WoRMS (via Arctos)\|Arctos
104 | OWU:Geol | Heys CIM (via Arctos)\|Dana 8 (via Arctos)\|Nickel-Strunz 10 (via Arctos)\|Arctos
105 | OWU:Herb | Arctos Plants\|WoRMS (via Arctos)
106 | OWU:Inv | WoRMS (via Arctos)\|Arctos
107 | OWU:Mamm | Arctos
108 | OWU:Para | TPT (via Arctos)\|WoRMS (via Arctos)\|Arctos
109 | OWU:Rept | Arctos\|Current Reptile Classification
110 | STAR:Alg | Arctos Plants
111 | STAR:Herb | Arctos Plants
112 | TMCC:Bird | Arctos
113 | TMCC:Ento | Arctos
114 | TMCC:Fish | WoRMS (via Arctos)
115 | TMCC:Herb | Arctos Plants
116 | TMCC:Herp | Arctos
117 | TMCC:Inv | WoRMS (via Arctos)
118 | TMCC:Mamm | Arctos
119 | TMCC:Teach | Arctos
120 | UAM:Arc | Arctos
121 | UAM:Art | UAM Art\|Getty AAT (via Arctos)\|Nomenclature 4.0 (via Arctos)\|Arctos\|Arctos Plants
122 | UA:Paleo | Arctos
123 | UCONN:Bird | Arctos
124 | UCONN:Egg | Arctos
125 | UMNH:Bird | Arctos
126 | UMNH:Herp | Arctos
127 | UMNH:Mamm | Arctos
128 | UMNHObs:Mamm | Arctos
129 | UMNH:Teach | Arctos
130 | UNCG:Mamm | Arctos
131 | UNCG:Para | Arctos
132 | UNM:MET | Heys CIM (via Arctos)
133 | UNM:MIN | Heys CIM (via Arctos)\|Dana 8 (via Arctos)\|Nickel-Strunz 10 (via Arctos)\|Arctos
134 | UNM:Paleo | WoRMS (via Arctos)\|Arctos
135 | USNPC:Para | Arctos
136 | UTEP:Arc | Arctos
137 | UTEP:Bird | Arctos
138 | UTEP:Ento | AntWiki (via Arctos)\|Arctos
139 | UTEP:ES | Arctos
140 | UTEP:Fish | Arctos
141 | UTEP:Herb | Arctos Plants
142 | UTEP:Herp | Arctos
143 | UTEP:HerpOS | Arctos
144 | UTEP:Inv | WoRMS (via Arctos)\|Arctos\|Arctos Plants
145 | UTEP:Mamm | Arctos
146 | UTEPObs:Ento | Arctos
147 | UTEPObs:Herp | Arctos
148 | UTEP:Teach | Arctos
149 | UTEP:Zoo | Arctos
150 | WNMU:Bird | Arctos
151 | WNMU:Fish | Arctos
152 | WNMU:Mamm | Arctos

**Comment by dustymc** [comment]
```

arctosprod@arctos>> select guid_prefix,string_agg(source,'|' order by preference_order) from collection left outer join collection_taxonomy_source on collection.collection_id=collection_taxonomy_source.collection_id where source is null group by guid_prefix order by guid_prefix ;
 guid_prefix | string_agg 
-------------+------------
 HMCM:Arthro | 
 HMCM:Bird   | 
 HMCM:Geo    | 
 HMCM:Herb   | 
 HMCM:Herp   | 
 HMCM:Mamm   | 
(6 rows)
```

**Comment by Jegelewicz** [comment]
Why didn't hose show up in my results?
