### ISSUE TITLE
Trying to figure out Remarks Search

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#4202]
@Jegelewicz Working on the Arctos/GloBI SPNHC talk data request to look for how many specimens have road kill or window collision in the remarks field, and I'm hitting up against a lack of knowledge on my part. 

I know how to search on parts remarks to find info on parts:
![Parts remark](https://user-images.githubusercontent.com/18562884/146474273-98f7b320-587b-425b-93c4-14e42ee9f0b2.jpg)

But since most of the info on cause of death goes into the general remarks field for the specimen (hitting a window affects more than just one part of the specimen). I'm not sure on how to search that field in the Arctos Search fields. 
![Untitled](https://user-images.githubusercontent.com/18562884/146474410-30ea9a1f-6263-4b8a-89ec-c4bd164eb54a.jpg)

I've tried all the different remarks labeled fields in the search page, but none of them will pull up https://arctos.database.museum/guid/UWYMV:Bird:3132, which I've been using as my test specimen since I know that I put the cause of death in that remarks field.
Help?

**Comment by dustymc** [comment]
<img width="315" alt="Screen Shot 2021-12-16 at 5 58 54 PM" src="https://user-images.githubusercontent.com/5720791/146476407-ba029112-78ff-45c9-998c-9d07e3d302cc.png">

<img width="154" alt="Screen Shot 2021-12-16 at 5 59 16 PM" src="https://user-images.githubusercontent.com/5720791/146476439-c06097d8-8a12-4480-bde6-3a5644282b04.png">

**Comment by ewommack** [comment]
Thanks @dustymc -> is this the same search you could do if you are not logged in?

**Comment by dustymc** [comment]
<img width="662" alt="Screen Shot 2021-12-16 at 6 14 45 PM" src="https://user-images.githubusercontent.com/5720791/146477873-03a60edb-03e9-4bf3-b427-dda7b3b5ffd4.png">
<img width="725" alt="Screen Shot 2021-12-16 at 6 15 33 PM" src="https://user-images.githubusercontent.com/5720791/146477889-94cae04f-ae4a-4882-a22c-1e0e10ae79be.png">

**Comment by ewommack** [comment]
Thanks @dustymc - @jhpoelen played around and figured it out, and also how he can see it in the data on his end.

**Comment by campmlc** [comment]
This search should also include "DOR".
