### ISSUE TITLE
Feature Request - do better recording collecting method

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4203]
**Is your feature request related to a problem? Please describe.**

See https://github.com/ArctosDB/arctos/issues/4202, https://github.com/globalbioticinteractions/globalbioticinteractions/issues/733 

**Describe what you're trying to accomplish** 

Find human interaction in Arctos

**Describe the solution you'd like**

Not scatter cryptically-abbreviated data all over the place, somehow.

**Describe alternatives you've considered**

Maintain the inability to find stuff.

**Additional context**

I poked around a tiny bit, results attached.

[temp_might_be_roadkill.csv.zip](https://github.com/ArctosDB/arctos/files/7735283/temp_might_be_roadkill.csv.zip)

 Of course most of them are not relevant, eg

```
select citation_remarks from citation where citation_remarks ilike '%DOR%';
```
is mostly
```
 Lectotype designated by Dorothea S. Franzen, 1958, 'Types of Mollusks Described by F.C. Baker Part III, Chicago Academy of Sciences', The Nautilus, Vol. 72, No. 1, pp. 30-34. https://biodiversitylibrary.org/page/8521063 [dpiquard 2018-07-13].
```

but the data are scattered enough that not much can be preemptively dismissed, and of course my few terms won't have found everything - eg https://arctos.database.museum/guid/UAM:Mamm:134709 has information in a defensible place, but 'vehicular trauma' somehow wasn't on my keyword list.

Nor was "slavage" on my list - twice. (https://arctos.database.museum/guid/DMNS:Mamm:18739, https://arctos.database.museum/guid/MSB:Bird:41031)

```
s
 salage
 salavage
 salavage 
 salavge
 salbage


 Hit by a car
 HIt by a car--building ops found it
 Hit by a truck - died soon after discovery.
 hit by automobil
 hit by bike
 hit by car
 Hit by car
 hit by car, dying
 hit by car, euthanized >24 hours
 hit by car on flat road to Boulder
 hit by collector's car
 hit by field truck
 hit by Steele's car
 Hit by truck
 hit by vehicle
 Hit by vehicle
 Hit by vehicle?
 hit by vehicle, USFWS

 found injured along road

 found injured on side of hwy; euthanized bird from wildlife rehabilitation center
 found dead on bridge
 found dead in the driveway
 flew into window glass and killed

```

and it goes on forever. 

Can we find a way to capture this, make sure the documentation is useful, something??

**Priority**
???

@jhpoelen

**Comment by Jegelewicz** [comment]
@dustymc I am about to acquire an intern for the spring - I was going to have them work on cleaning up non-printing characters in localities, but this might be more interesting/productive?

**Comment by dustymc** [comment]
Maybe - I can always find weird unicode excel-hates-you diamond-thingees, it's just a matter of doing something about them. These probably need humans, but only if we can identify a useful place for the data first. Might depend on how code-savvy your intern turns out to be.

Big-picture, hindsight and all, I'm a little baffled that we didn't figure this out a long time ago, and that someone's not using it to leverage funding, etc.

(And I recycled the unicode conversion fail scripts to find what I found - weird...)

**Comment by jhpoelen** [comment]
@dustymc Thanks for sharing the examples. I can see much use in building a translation table that relates the verbatim descriptions to more structured interpretations.


E.g.,

struck by car -> _ <interactionType>damaged by </interactionType> <targetTaxon>car</targetTaxon>

struck by car -> _ <interactionType>damaged by </interactionType> <targetTaxon>Homo sapiens</targetTaxon>

struck by car -> _ <interactionType>killed by </interactionType> <targetTaxon>Homo sapiens</targetTaxon>

I am eager to take a stab at writing little tools that help automate the translation process. Then, reviewers (like interns?) can help to identify false positives / false negatives to further improve the method.

I am assuming we'd want keep the verbatim descriptions around to avoid losing information, and allow for fixing translation mistakes.

**Comment by Jegelewicz** [comment]
> And I recycled the unicode conversion fail scripts to find what I found - weird..

Twilight Zone theme plays here

**Comment by dustymc** [comment]
I'm not sure what we should be doing.

I do suspect moving anything is beyond our capabilities, we'd need to add/copy/etc., but we could/should develop documentation so hopefully this ends up less-scattered in the future.

Collecting method was my first thought, but maybe that's confounding other stuff - eg collecting method is some systematic roadcruising thing, finding a pre-smooshed squirrel is secondary to that. That would still involve some level of digging and interpretation, it's a free-text field, this seems like maybe it needs some sort of category/flag/something.

We used to have a 'kill method' attribute intended for insects but seems it was never used so cleaned up at some point, maybe we should resurrect that or something like it (perhaps as a collecting event attribute). 

Actually that's probably not quite right either - the important thing is that it was mangled by some human activity, not that the rehabber gave up and did their thing a week later.

???

**Comment by Jegelewicz** [comment]
> We used to have a 'kill method' attribute intended for insects but seems it was never used so cleaned up at some point, maybe we should resurrect that or something like it (perhaps as a collecting event attribute).

Might be good to consider since - TDWG has the [How Did It Die? Task Group](https://www.tdwg.org/community/osr/how-did-it-die/)

**Comment by dustymc** [comment]
Neat! I'm glad to see they have a botanist onboard, vertebrate people seem to have overly simplistic views of dead/alive.

>express whether the organism was dead or alive at the time of the observation or collection, and what the cause of any death was. 

"It was dead, cause was euthanization" is still missing "because of what happened last week." 

"Most correct" in Arctos might be to add an event for the window/car/whatever encounter, but I'm not so sure that's a hoop most would be willing to jump through, and it would require examining multiple Occurrences in DWC to piece things back together.

"Usable" might just involve a 'human involved: yes/no' flag somewhere - hard to say if that does what someone might eventually want to do with the data or not....

**Comment by Jegelewicz** [comment]
I was thinking about attributes - then collections could get as detailed as they wanted including dates and determiners.

More stuff to potentially use in the task group Github repo - https://github.com/tdwg/how-did-it-die/issues

Maybe a few new attributes:

vitality - An indication of whether the organism was alive or dead at the time of collection or observation [controlled vocabulary: dead, alive, unable to determine, not recorded] A specimen event attribute?

cause of death - The primary or immediate disease or condition resulting in the death of the organism [controlled vocab? see https://docs.google.com/document/d/1Qf-RdsHtUaEb2g1ESBpa4g7vYCwxiovSkj6sUAF0CiM/edit#heading=h.gcyhdus7gli2 or do we free text this or use a very broad vocab with the rest in the attribute remark?

death date - The date the organism died

Seem like simple adds that we might be able to parse data from collecting method and collecting event remarks to create.

Which brings up something we are sort of discussing elsewhere. "Annotation" of records - whereby we add some attributes and the determiner makes it clear that it was added by Jorrit's script. We don't ask permission or try to get everyone to make "updates" we do this for them and everyone is happier?
