### ISSUE TITLE
Feature Request - More automated taxon name quarantine

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4204]
**Is your feature request related to a problem? Please describe.**
I find a misspelled taxon name that continues to accrue use as students are not aware of it being a misspelling or the bulkloader accepts it because it is there. The process for quarantining the misspelled name requires anyone using it to re-identify their objects, which can be a very difficult task to accomplish - see #3165 and #4146 which will eventually lead to a bunch of open quarantine requests that can never get resolved because people continue to add identifications using the misspelled name.

**Describe what you're trying to accomplish** 
Upon discovery of a misspelling, quickly quarantine the name so that it will no longer be inadvertently assigned to more objects.

**Describe the solution you'd like**
A process somewhat like agent merge. When a misspelling is discovered, A request for quarantine would initiate a notification that in some time period (two weeks? a month?), the misspelled name will be quarantined and any identifications using the name at that time will be changed to the A {string} formula with A = correctly spelled name and {string} = misspelled name. Objections can be raised if anyone has them and the process halted if it is discovered that the request is not supported.

**Describe alternatives you've considered**
Leave things as they are and rely on relationships - works inside of Arctos, but not so much when the data is sent out to aggregators.

**Additional context**
This was brought up as a possibility at the Arctos Code Table Committee Meeting 2021-12-16

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by dustymc** [comment]
I don't think this is (yet, hopefully) ready for automation, but my old offer of adjusting identifications stands. Open a quarantine request issue, get the data owners using the name to indicate that they're OK with whatever change is being proposed, I can update. If that turns into some sort of predictable process then we can think about automation. 

Or maybe the issue should be in the form of "if there are no objections by {date} we'll proceed with {whatever's suggested in the issue}" - I'm fine with pushing the buttons on whatever process ya'll want to work out.

The current list is https://github.com/ArctosDB/arctos/issues?q=is%3Aopen+is%3Aissue+label%3AQuarantine.

**Comment by Jegelewicz** [comment]
After discussion with Taxonomy Committee today, we propose the following to make this process smoother.

When a name quarantine is requested, the clock starts ticking. Within one month, if there have been no protests, the quarantine will proceed. All identifications using the quarantined name will be changed to A {string} where the {string} will be the quarantined name and the A will be the correct name as given in the issue. The issue template will be adjusted to the following:

Issue Documentation is at http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

Name Quarantine Documentation is at https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxon_name_type

The name suggested for quarantine is:

The reason for quarantine is:

All identifications using the quarantined name will be changed to A {string}. The taxon name to be used for the A portion of the name is:

Collections currently using this name in identifications include:

**Comment by dustymc** [comment]
AWG: go 

one month wait time
need to rebuild issue template


I can

* leave CSV that the identification loader can eat
* leave an annotation including the issue on the name

**Comment by Jegelewicz** [comment]
Give people a month to respond to a Github quarantine issue, then @dustymc can change identifications and we can quarantine the name. This allows the issue to make it through one AWG and one Taxonomy Committee meeting.

**Comment by Jegelewicz** [comment]
Need a new relationship for names of "quarantine" or the like that lets us describe the name that should be used as an alternate and why the quarantine was suggested.

**Comment by dustymc** [comment]
Quarantine requests are probably never going to be resolved under the current template, this should be resolved ASAP. @Jegelewicz are you going to rebuild the issue template?

**Comment by Jegelewicz** [comment]
I have rebuilt the template.

**Comment by dustymc** [comment]
Thanks, some requests/suggestions:

1. Links to both the funky and replacement names are critical, not just useful. (see eg https://github.com/ArctosDB/arctos/issues/4327#issuecomment-1058524625, anything else is an invitation for spelling variations).
2. A link to the using records (from  [Used in Identifications] on the taxon page eg https://arctos.database.museum/SpecimenResults.cfm?taxon_name_id=10020709 ) would be very useful, every one of these seems to involve some confusion about what constitutes "used." 


Given that, I can pull the using collections and contacts so those parts can be dropped.

Suggest being more explicit with the timeline - "30 days after this issue is submitted...."

I'll use 'Reason for quarantine' as taxon_relations.relation_authority - I think that may require some clarification.

https://github.com/ArctosDB/arctos/issues/4405 seems to have sufficient buy-in, so I'll go try my scripts out over there.

**Comment by Jegelewicz** [comment]
> A link to the using records (from [Used in Identifications] on the taxon page eg https://arctos.database.museum/SpecimenResults.cfm?taxon_name_id=10020709 ) would be very useful, every one of these seems to involve some confusion about what constitutes "used."

That is now requested in the first item?

> Given that, I can pull the using collections and contacts so those parts can be dropped.

Leaving them there with an @ to you

> Suggest being more explicit with the timeline - "30 days after this issue is submitted...."

Sounds good, but who is going to monitor them? There is no easy way to provide a "due date" for any issue except via milestones, and even that is a pain.....

**Comment by dustymc** [comment]
> now requested in the first item?

I don't see it.

>who is going to monitor them

I'll find them eventually, but a reminder would be cool. https://github.com/apps/octo-reminder exists (and probably others), I've been failing to find the time to look at that for months if you're bored....

**Comment by Jegelewicz** [comment]
> I don't see it.

**replace this with the name suggested for quarantine, and provide link to the Arctos taxon page**

That link is  https://arctos.database.museum/SpecimenResults.cfm?taxon_name_id=10020709, no?

> if you're bored....
does not compute

**Comment by dustymc** [comment]
No, we need three links

1. Funky name (eg https://arctos.database.museum/name/Miniopterus%20major)
2. Good name (eg https://arctos.database.museum/name/Miniopterus%20majori)
3. catalog records using the funky name (eg  https://arctos.database.museum/SpecimenResults.cfm?taxon_name_id=10020709)

**Comment by Jegelewicz** [comment]
That's an easy ask for me, but maybe not everyone else. Number 3 can be acquired from number one.

![image](https://user-images.githubusercontent.com/5725767/157346397-ce6f7bb5-672c-4d77-ae19-715631f5497c.png)

Which one of these should a person choose? I think if we can get links to the funky and good names we are doing pretty good?

**Comment by dustymc** [comment]
Fair enough, I can add that to my scripts.

The first - I'm not sure if that's where the confusion stems from or not, but a bunch of these seem to involve not being able to find the records using the nominated name.

**Comment by Jegelewicz** [comment]
@dustymc I woke up with this on my mind and wonder if we could challenge ourselves to make this even easier for people to do.

Imagine a button on the taxon page "Nominate for Quarantine" that opens a form requesting the name of the taxon that should replace the name being nominated and a text box for the reason to quarantine. Once completed, the form would then generate the Github issue using your scripts. Possible?
