### ISSUE TITLE
"SyntaxError: Unexpected token < in JSON at position 0" HELP!

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#4205]
# Error Text
SyntaxError: Unexpected token < in JSON at position 0

One of my staff are cataloging a new record and she received this message when she tried to save using the new data entry screen. She looked for returns and spaces after text and was not able to find any culprits. We're guessing it might have to do with a very long description (word says there are 4,040 characters with spaces in the description field)... but we're not sure. Any ideas from our trusty error code specialists? @dustymc @Jegelewicz 

![IMG_6216](https://user-images.githubusercontent.com/17605945/146598256-8b1a3b54-69e9-479e-80bc-c2e3b44b993f.JPG)

**Comment by Jegelewicz** [comment]
That attribute has a character limit of 4,000 so that may be the problem.

**Comment by dustymc** [comment]
Yep, you got the cause:

<img width="1236" alt="Screen Shot 2021-12-17 at 11 37 34 AM" src="https://user-images.githubusercontent.com/5720791/146598779-71f3dfbf-df49-46da-9daa-20fac925a54b.png">

Going next task - the error should be better/more informative.

**Comment by AJLinn** [comment]
I'll have her try to cut down to 4000. thanks!

**Comment by AJLinn** [comment]
That did the trick. Thanks team!

**Comment by dustymc** [comment]
And maybe you have a reason to spell things out, but if not Arctos is unicode, things like ``-15°C`` should work fine (but see https://handbook.arctosdb.org/documentation/encoding.html, you should use the unicode character not eg ``&#176;`` which looks like &#176; in a browser....

**Comment by dustymc** [comment]
Reopening so I can deal with the error.
