### ISSUE TITLE
Object Tracking Find Containers - allow csv download of container locations

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4208]
Request for the ability to generate a csv download for just containers and their hierarchy from the Find Container results view.
This would generate a hierarchy list like we get when we click Flatten Part Locations or parts table download, but it would not require that a container be associated with a part.
This is necessary not just for barcoded containers without parts - e.g. cryovials with no part associated - but also for containers higher up in the hierarchy. For example, I would like to find a list of freezer boxes, and download their locations. Currently I have no means of doing that unless I use Drag/Print - which is not a very useable format to work with.

Priority: high. All object tracking issues are now becoming critical.

**Comment by Jegelewicz** [comment]
Here is what I think might work.

I search on something in object tracking and get results.

![image](https://user-images.githubusercontent.com/5725767/151469719-a79f151f-a607-48d2-9bf3-a26fa28acafb.png)

Then I ask to "download as csv" and what I would get is this

https://docs.google.com/spreadsheets/d/1iYGj5O6zyVJkxiQdauMqR80aq7h-uzst3fr7wsKKPek/edit?usp=sharing

This would still allow you to see the path to find a container AND containers without parts are available as well. Sorting by container type or part can help remove any parts of the tree you don't need.

**Comment by Jegelewicz** [comment]
@dustymc this is what @campmlc was talking about today - getting a bunch of container locations when the associated parts have not yet been cataloged - possible?

**Comment by Jegelewicz** [comment]
This has never been addressed, but is on my assignment list. I know there is a lot going on - @campmlc is this still something you need?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I was literally talking to @lin-fred about a similar issue minutes ago. Once #5537 is complete, I could use a way to download a list of cavity mounts and cradles. It sounds like this would be a way to accomplish that?

**Comment by lin-fred** [comment]
hivemind confirmed

**Comment by Jegelewicz** [comment]
@dustymc is [this](https://github.com/ArctosDB/arctos/issues/4208#issuecomment-1023810073) possible?

**Comment by campmlc** [comment]
If I understand correctly, this has been implemented. Click on container contents in Find Container, can also download as csv

**Comment by campmlc** [comment]
You see the barcoded containers in their positions. If they are cataloged, the guid also displays. The columns are sortable.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks for letting me know about that. It's not ideal for my purpose, but I can make it work.

**Comment by Jegelewicz** [comment]
Closing then. Object tracking [documentation](https://handbook.arctosdb.org/documentation/container.html) is OVERLOADED and includes stuff that is also in the How-Tos and is probably contradictory in places. FAQ hidden in the documentation probably is never read but I added this there anyway.

**Comment by campmlc** [comment]
It would be useful to have what @lin-fred requested - I've had to abandon using Find Containers for anything other than barcodes for this reason. Flatten/Print only works for cataloged items. If this could be implemented from that tool, it would be helpful, as right now we have two different tools working in different ways to access the same information, and there is some but not complete overlap.

**Comment by Jegelewicz** [comment]
@campmlc would [what I described](https://github.com/ArctosDB/arctos/issues/4208#issuecomment-1023810073) be a workable solution?

**Comment by campmlc** [comment]
Apologies - I was getting myself confused about what form we are talking about - I've been using Parts Download all morning, which is a similar tool in a completely different place, but it doesn't provide locations for uncataloged objects.

In Find Container, the Container Contents download should give you what you want, if I understand correctly. It provides a sortable table of containers and collection objects and guids, in their position hierarchy, very similar to the Parts (Table) Download, but it also includes rows for parts of the hierarchy that have nothing in them, as well as the position hierarchy for barcoded objects that are not cataloged. So you can immediately see any empty positions or any barcodes with no cataloged item attached. This can be downloaded as csv, and easily sorted to find empty columns or filtered in Excel.
See for example the Container Contents for freezer rack DGR18364.

Does that work?

**Comment by campmlc** [comment]
The column headers are BC1 = Barcode1, LBL1=label 1, T1 = container type 1, CID1 = containerID 1, in order from left to right from higher in the hierarchy to lower, all the way to the collection object. The numbers of container in the hierarchy depend on how high up you start - if you started at the room or collection level, you would have many more hierarchy levels than if you started at a shelf or a freezer. 
Right now if the collection object is cataloged, it has the guid in the ultimate label field; but this is currently not a live link. It would be very useful if the guid were a live link here.
![Screenshot 2023-02-20 11 03 15](https://user-images.githubusercontent.com/14808196/220175076-caa36066-e5dc-474c-9cfd-5fe137c31583.png)

**Comment by campmlc** [comment]
Here is a screenshot of the same file, showing two uncataloged objects (red arrows) in positions 28 and 29 (they have labels loaded into object tracking, but have not yet been cataloged), and an empty position (nothing scanned in) in position 30.
![Screenshot 2023-02-20 11 06 20](https://user-images.githubusercontent.com/14808196/220175990-e665df9e-47c7-4131-890d-5d42d65c8959.png)

**Comment by Jegelewicz** [comment]
If you guys are happy, please close this, if we are still in need of something, please provide a mock-up or very thorough description.

**Comment by campmlc** [comment]
@lin-fred does that work?

**Comment by lin-fred** [comment]
its @Nicole-Ridgwell-NMMNHS who is looking for this, not me
