### ISSUE TITLE
Arctos not pulling all taxonomic information

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#4211]
We have a teaching collection with multiple types of specimens. Today, I went to pull a list of the botany specimens in our teaching collection by selecting "Collection: CHAS:Teach" and "Kingdom=Plante", which resulted in 88 records. But I noticed not all of the records were showing up, so I did another search of "Collection: CHAS:Teach" and "Kingdom: NULL", which brought up 70 records.

We tried creating a new identification on CHAS:Teach:E2016A.13 (Solidago ulmifolia) , but it still does not pull the taxonomic information. When you search for "Genus: Solidago" and "Species: Ulmifolia" (without selecting any collections and when selecting "Teach" and "Herb"), only the specimens in the ChAS Herbarium collection are part of the search results. If I try searching for the specimen in just the teaching collection, it brings up 0 results.

On the Search Taxonomy, it shows that there is taxonomic information available in Arctos Plants and ITIS.gov confirms that "Solidago ulmifolia" is the accepted scientific name. I also searched a few other specimens without finding any issues.

This issue is not limited to the Teaching or Herbarium collection. When I search "Kingdom=NULL", there are 3298 records. There are some catalog records where that is to be expected because there isn't taxonomic information associated with the collection (anthropology, scientific history), but it looks like almost every collection has an issue with some of the taxonomic information not being pulled.

![image](https://user-images.githubusercontent.com/93737929/147707808-840f61b5-f2b5-4c70-961d-c1a2ee8532ca.png)

Has anyone else experienced this issue? Is there a way to fix it?  We thought it might be an "Arctos Plants"-specific issue at first, but since it's impacting other collections, I don't think that's the case.

Thank you!

**Comment by Jegelewicz** [comment]
@wellerjes is Arctos Plants one of your taxonomic sources for the CHAS:Teach collection?

**Comment by dustymc** [comment]
```
arctosprod@arctos>> select source from collection_taxonomy_source inner join collection on collection_taxonomy_source.collection_id=collection.collection_id where guid_prefix='CHAS:Teach' order by preference_order;
 source 
--------
 Arctos
```

Please see https://handbook.arctosdb.org/documentation/taxonomy.html

Note that there is no source=Arctos classification: https://arctos.database.museum/name/Solidago%20ulmifolia#Arctos

>ITIS.gov confirms 

You can check that via https://arctos.database.museum/name/Solidago%20ulmifolia#ITIS, and you can search nonpreferred data via...



<img width="716" alt="Screen Shot 2022-01-01 at 7 37 40 AM" src="https://user-images.githubusercontent.com/5720791/147854232-2003a3d0-d276-4f28-9325-5f6ab04a701a.png">

>"Species: Ulmifolia" 

... but note that subspecific data in Arctos are generally multinomials.

```
arctosprod@arctos>> select source, term from taxon_term inner join taxon_name on taxon_name.taxon_name_id=taxon_term.taxon_name_id where scientific_name='Solidago ulmifolia' and term_type='species';
                       source                        |        term        
-----------------------------------------------------+--------------------
 Arctos Plants                                       | Solidago ulmifolia
 WoRMS (via Arctos)                                  | Solidago ulmifolia
 World Register of Marine Species                    | Solidago ulmifolia
 GBIF Backbone Taxonomy                              | Solidago ulmifolia
 GBIF Backbone Taxonomy                              | Solidago ulmifolia
 GBIF Backbone Taxonomy                              | Solidago ulmifolia
 Database of Vascular Plants of Canada (VASCAN)      | Solidago ulmifolia
 NCBI                                                | Solidago ulmifolia
 Union 4                                             | Solidago ulmifolia
 Open Tree of Life Reference Taxonomy                | Solidago ulmifolia
 iNaturalist                                         | Solidago ulmifolia
 Catalogue of Life                                   | Solidago ulmifolia
 ITIS                                                | Solidago ulmifolia
 The Interim Register of Marine and Nonmarine Genera | Solidago ulmifolia
 World Register of Marine Species                    | Solidago ulmifolia
 World Register of Marine Species                    | Solidago ulmifolia
 Arctos Relationships                                | Aster ulmifolius
 Arctos Relationships                                | Aster ulmifolius
(18 rows)
```

**Comment by wellerjes** [comment]
> @wellerjes is Arctos Plants one of your taxonomic sources for the CHAS:Teach collection?
I don't think it is; this is a screenshot from my example and "UsesSource" just says "Arctos" not "Arctos Plants". How do I check / change it?
![image](https://user-images.githubusercontent.com/93737929/148300434-d462a4d1-b3ba-4529-9cc7-661b0334a9fa.png)

**Comment by Jegelewicz** [comment]
Go to [Manage Collection](https://arctos.database.museum/Admin/Collection.cfm) and add it in your source list.

![image](https://user-images.githubusercontent.com/5725767/148302819-f63d23da-144b-4f5c-9c01-c47147446c26.png)

I suggest that you order them Arctos Plants = 1 and Arctos = 2 

Let me know if you need a meet up to walk through it.

**Comment by Jegelewicz** [comment]
@wellerjes let me know if this helps to solve your issue. Once you select the new source, it may take a day or so for it to propagate through your records.

BTW I have also been meaning to tell you that you might want to have WoRMS (via Arctos) as your #1 for your Inv collection. It has curated marine taxonomy that is almost always more up to date than the Arctos source.

**Comment by wellerjes** [comment]
@Jegelewicz Thanks! I updated the source and will let you know if it works (fingers crossed). I've also updated the Inv Collection to pull from WoRMS first, thank you!

**Comment by wellerjes** [comment]
@Jegelewicz That fixed it; thank you so much!
