### ISSUE TITLE
Locality Attribute Request - biota remarks

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#4212]
**Context**
In our paleo collection, at the locality level, we have descriptions of the fossil types found/observed at localities. Internally, this data is useful to us and in the long term I'd like to create observation records for some of them.  BUT the main reason to have them in a dedicated attribute is that I also have to report these data to the Bureau of Land Management who use them for land use decisions such as where to put oil wells, etc. In the locality files we send to them, we are required to report whether a locality has plants/vertebrates/invertebrates/traces and then a short description of the taxa collected and observed. Separating these data out of locality remarks (which is where they currently reside) is difficult, no matter how much I strive to keep that field consistently formatted. I also can't just pull specimen records for this data.

I know this may not seem like the correct way of doing things, but considering BLM's reporting requirements and the current state of our data I think a locality attribute would work best for us.

I'm already working on pulling our UTMs out of locality remarks, if I could pull these data out at the same time, that would be excellent.

**Goal**

Create a new free-text locality attribute called something like biota remarks (I'm open to suggestions on the attribute name)

**Table**
[Code Table is http://arctos.database.museum/info/ctDocumentation.cfm.](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlocality_attribute_type)

**Proposed Value**
biota remarks (or some alternative)

**Proposed Definition**
Description of the biota at the locality.

**Attribute data type**
free-text

**Available for Public View**
Yes

**Comment by dustymc** [comment]
> Description of the biota at the locality.

My only "objection" to this is the same as https://github.com/ArctosDB/arctos/issues/1608 - there's a temporal component of "biota at the locality" that table Locality isn't capable of capturing. Are we talking about yesterday's rainforest or tomorrow's parking lot?

Best would be as you say, catalog everything.

Second would be Collecting Event Attributes, which are more capable of dealing with the inevitable temporal component.

If that's not acceptable for some reason, then I have no real objections to locality attributes (but a better definition would be nice) - that part of the model is easy to avoid, nobody else has to use it, if it makes what you do somehow more approachable and you can accept the limitations then rock on....

**Comment by Jegelewicz** [comment]
> there's a temporal component of "biota at the locality"

Wouldn't that be covered by the stratigraphic locality attributes? They would make a locality different using a temporal component.

**Comment by dustymc** [comment]
> stratigraphic locality attributes

Those also get dozed off for the parking lot.

**Comment by Jegelewicz** [comment]
True, but at the time whatever was collected, the parking lot was not there. Anything collected later should use a locality WITHOUT the stratigraphy or biota attributes.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
In a way I actually agree this would be more appropriate for collecting event, however, the main complication is that I need to be able to pull this data with the locality data. So, if it were in collecting event, I'd need something that would concatenate all the biota attributes for each locality and then join that table to the table I get from download flat attributes in search locality.

**Comment by dustymc** [comment]
A report that concatenates stuff wouldn't be difficult, but keeping that associated with the date-bits would add some sort of complexity - maybe more than just downloading the events (which can be found via locality data).

And for clarity I still don't really object to your original request, the whole "see how stuff changes" use case may be entirely theoretical, if the additional complexity isn't actually useful to you/your users then maybe "simple" should win.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> if the additional complexity isn't actually useful to you/your users

It is not really useful for us, and if we do want that level of complexity we'd go to the trouble of actually going through catalog records and creating observation records.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Ok is this a better definition? "A summary description of biota observed or collected at the locality for use in locality reports"

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Code table admins says to go ahead.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
@dustymc is this as simple as adding biota remarks to https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlocality_attribute_type or are there additional steps?

**Comment by Jegelewicz** [comment]
@Nicole-Ridgwell-NMMNHS that's it! Want to give it a go?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Added! Now just waiting to make sure it shows up.

**Comment by Jegelewicz** [comment]
It takes a bit - maybe up to 24 hours...
