### ISSUE TITLE
Feature Request - last scan timestamp/date on part when viewing catalog record?

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#4213]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

When a loan is returned I use the partlastscanned date/time stamp to help determine if all the parts are back where they belong. If a section of the collection is being curated, I use last scan date to check on the progress and look for any specimens that might have been skipped from scanning.

I would like to be able to see this last scan date on the part info at the bottom of the catalog record itself (rather than go find it in a loan, if the specimen has even been in a loan).

I see in the part attributes there is a field called 'Date' - what is that?

It is not the last scanned date. I checked this using the following specimen

https://arctos.database.museum/guid/UAM:Ento:293688

which has a part attribute date of 2021-07-01 displayed on the catalog record.

but by checking the loan this specimen is in, I see its last scan date is 2017-11-01T11:24:38 

If the 'date' being displayed is something less useful than last scan date, perhaps it could be replaced by last scanned date to save space?

**Describe what you're trying to accomplish** 
An clear and concise overview of the goals; why are you asking for this?

Although last scan date can be seen in 'review items' in a loan, not all specimens are in loans, and in entomology, many loans involve thousands of specimens so it is challenging dealing with loading all those rows of data for review (requires paging through many pages etc.)

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.
medium

**Comment by dustymc** [comment]
>what is that

part attribute date  - the date the part attribute was determined.

I think this probably has to be part of "plpath" (the full container stack, whatever the details). That's easy enough to change, but takes a significant amount of CPU so it's also not something that's trivial to change (and I'd be surprised if someone doesn't have scripts written to it). I don't care whats in there, but it needs a fully-fleshed out plan. https://github.com/ArctosDB/arctos/issues/1183 might be the origin, and there are lots more scattered and overlapping issues. Perhaps this is best part of https://github.com/ArctosDB/arctos/issues/3632; whatever the organization, I can't see how I can do anything without some sort of full-scale plan.

https://github.com/ArctosDB/arctos/issues/4192 is one example of the potential complexity behind "last."

**Comment by Jegelewicz** [comment]
Next object tracking team meeting is on Friday at 3PM MST

**Comment by AJLinn** [comment]
> part attribute date - the date the part attribute was determined.

Please don't remove/change the part attribute date from the "plpath" - this is essential data for many of the part attributes assigned by cultural collections (e.g., condition report and location). I hope there's another way the info Derek is hoping to view can be displayed.

<img width="1330" alt="Screen Shot 2022-01-03 at 7 24 11 AM" src="https://user-images.githubusercontent.com/17605945/147954621-3d87f764-84de-4d6d-92f5-c81fcca91650.png">

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/6028
