### ISSUE TITLE
Code Table Request - ID Type

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#4215]
**Goal**
Add "Denver Zoo" to coll_other_id_type

**Context**
We have lots of specimens from the Denver Zoo and would like to standardize the ID type

**Table**
coll_other_id_type

**Proposed Value**
Denver Zoo

**Proposed Definition**
[Denver Zoo](https://denverzoo.org/) organism identifier. [Arctos Agent](https://arctos.database.museum/agents.cfm?agent_id=21252002) 

**Collection type**
NA

**Attribute data type**
NA

**Attribute value**
NA

**Attribute units**
NA

**Available for Public View**
YES

**Other ID BaseURL**
NA

**ID_References**
NA

**Priority**
Normal

**Comment by Jegelewicz** [comment]
Added as we already have ABQ Biopark.
