### ISSUE TITLE
Feature Request - user creation

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4216]
**Is your feature request related to a problem? Please describe.**

Creating users results in an Operator without coldfusion_user rights, and those can't log in. That confuses people.

**Describe what you're trying to accomplish** 

Somehow be less confusing.

**Describe the solution you'd like**

Better post-authenticate error messages??

**Describe alternatives you've considered**

Rethink the whole mess in some radical way?

Use TACC's oauth service instead of users?

**Comment by Jegelewicz** [comment]
Oops - so this was my bad for not giving @barke042 coldfusion rights? Many apologies! Can we somehow make them automatic for all operator accounts?

**Comment by dustymc** [comment]
>so this was my

Yes, but I think it's pretty safe to blame me, I had to fall down the same hole to see it....

>automatic

Absolutely not, for security reasons.

**Comment by Jegelewicz** [comment]
I'm not sure I understand the process though. Can I give coldfusion user permissions to non-operator account?

**Comment by dustymc** [comment]
>Can I give coldfusion user permissions to non-operator account?

No. Postgres is "roles" all the way down. Users/operators are the central role; there's nothing to which other roles can be attached without that.

I made a slight change to https://handbook.arctosdb.org/documentation/users.html 

>After the user has completed Step 3, you will receive a notification email. You may then assign them appropriate data and collection roles. The COLDFUSION_USER role must be provided for the user to log in. DATA_ENTRY is the minimum additional role to enable data entry. Provide documentation, which can be found from the big red box on the manage users page.

I'm not sure what else can realistically be done here, closing.
