### ISSUE TITLE
Full clone option fails to clone part attributes

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#4219]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

I made a full clone of

https://arctos.database.museum/guid/UAM:Ento:76725

using the 'clone full cataloged item' option

this record has a part attribute of 'preservation'

but the resulting record that the clone process made didn't have any part attribute. (Luckily I noticed and created the missing part attribute).

**Expected behavior**
The clone should have the same part attributes as the original record.

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.
high

**Comment by dustymc** [comment]
patched
