### ISSUE TITLE
Parts Bulkloader Shows phantom record

### ISSUE THREAD

**Issue by cefilipek** [ArctosDB/arctos#4220]
The Parts Bulkloader shows that I have a record waiting, but when I go to look at it there is no record there. I am also unable to delete the phantom record, but I get the pending data notification emails in spite of the fact that there is no record there.
<img width="619" alt="Screen Shot 2022-01-04 at 8 18 04 PM" src="https://user-images.githubusercontent.com/56844074/148150187-f8ec768d-04b9-4724-a985-ffb7428283e3.png">
<img width="1255" alt="Screen Shot 2022-01-04 at 8 18 33 PM" src="https://user-images.githubusercontent.com/56844074/148150230-66fc6976-97b2-4a7e-80df-34ff9282f6fc.png">

**Comment by cjconroy** [comment]
I have the same problem with bulk loading citations. I wasn't successful at bulkloading so I gave up and try to delete the records in the bulkloader, but same issue. It says there are 24 records, but I can't see them. I try to delete them over and over, but it lingers.

**Comment by dustymc** [comment]
I think the problem is with NULL (or something I can't see, not sure yet) status and the "user/status" button. The other button works for the things I can see. 

Needs fixed and versioned.

**Comment by dustymc** [comment]
template and citation loader updated to deal with nullish, parts needs dealt with as part of https://github.com/ArctosDB/arctos/issues/3987
