### ISSUE TITLE
Need Help with Arctos Error:5A5AB6E0-8CE9-4691-9316E2F39D4243F4

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#4221]
# Error Text
Message: ERROR: update or delete on table "trans" violates foreign key constraint "fk_permittrans_trans" on table "permit_trans" Detail: Key is still referenced from table "permit_trans".
Detail:
Check the Arctos Handbook for more information on errors.
This message has been logged as 5A5AB6E0-8CE9-4691-9316E2F39D4243F4 Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue.

# Where it happened
https://arctos.database.museum/accn.cfm?action=deleteAccn&transaction_id=21128477

# Steps to get there
I accidentally created a duplicate accession of UAM:EH UA2021-010, but instead of the UAM:EH collection I accidentally created it in the OWU:EH collection. When i discovered the error I tried to delete that accession record. I then received this error message.
<img width="1520" alt="Screen Shot 2022-01-05 at 10 56 15 AM" src="https://user-images.githubusercontent.com/17605945/148280655-d1572299-54f2-44fb-9acf-2098ae15771b.png">

# Problem
**Community response to describe the problem that caused the error**

# Solution
**Community response with directions for how to correct the problem**

**Comment by dustymc** [comment]
Delete the permit link (and any other "children" of the accn) first.

**Comment by AJLinn** [comment]
When I try to edit the accession now it says:

An error occurred while processing this page!
Message: ERROR: syntax error at end of input Position: 423
Detail:
Check the Arctos Handbook for more information on errors.
This message has been logged as C2A147C0-1062-400C-8436E15EC6B0D670 Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue.

**Comment by AJLinn** [comment]
When I checked the permit type to see what accessions were connected to it, it said there were none.

**Comment by AJLinn** [comment]
And related... when I tried to delete the permit UAM:EH temp receipt (accidentally created as a duplicate) I got an error on that:
An error occurred while processing this page!
Message: ERROR: update or delete on table "permit" violates foreign key constraint "fk_permittrans_permit" on table "permit_trans" Detail: Key (permit_id)=(10001916) is still referenced from table "permit_trans".
Detail:
Check the Arctos Handbook for more information on errors.
This message has been logged as 6236F336-4FBB-4B34-8907BCD41FEA2255 Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue.

**Comment by dustymc** [comment]
Not sure - I logged in, clicked your link, it seems to be happy, the dependencies must have been removed at some point....

[That permit](https://arctos.database.museum/Permit.cfm?action=search&permit_id=10001916) claims to not be used in anything now too - should be deletable, let me know if not and I'll investigate.

**Comment by AJLinn** [comment]
I keep getting the same error:ERROR: update or delete on table "permit" violates foreign key constraint "fk_permittrans_permit" on table "permit_trans" Detail: Key (permit_id)=(10001916) is still referenced from table "permit_trans".

let me log out and log back in

**Comment by AJLinn** [comment]
No change... same error on permit delete attempt.

**Comment by dustymc** [comment]
yea, I see that - I suspect it's related to the back end dropping packets (or just PG being PG...), I'm not seeing anything in the code that should lead to the current situation (the accn seems to be half-deleted). I'll dig around some more and clean up when I'm done.

**Comment by dustymc** [comment]
I'm gonna blame sunspots or something, I still don't see what happened, but the code will be a little cleaner in next release, and the permit and orphaned transaction are gone.
