### ISSUE TITLE
Code Table Request - add wing to Mamm collections

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4225]
**Goal**
Catalog a bat wing

**Context**
I considered using partial skeleton, but I think wing is a better description

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name

**Proposed Value**
wing

**Proposed Definition**
no change

**Collection type**
Mamm

**Comment by Jegelewicz** [comment]
Note - part is hanging out in the parts bulkloader - it is for [ACUNHC:Mamm:849](https://arctos.database.museum/guid/ACUNHC:Mamm:849)

**Comment by ccicero** [comment]
approved at CT meeting 20 Jan 2022. 'Mamm' added to part name wing.
