### ISSUE TITLE
Data Entry Form Error

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#4226]
One of our collections techs is trying to enter new records into the Teaching Collection, but is encountering the following error when he saves the data entry form:
![unnamed](https://user-images.githubusercontent.com/93737929/148455746-9814894a-8f94-440f-b7bd-11b0abb2630e.png)

It appears everything required is filled out properly, but red lines have appeared around the Tools box, which did not have anything changed.
![unnamed (1)](https://user-images.githubusercontent.com/93737929/148455846-bc7c02b5-825b-4abe-b252-63e4723fd0d3.png)

What's in the picture above is the default when the data entry form loads; does it need to be changed?

**Comment by dustymc** [comment]
Can you share a screenshot of the entire screen please?

There's probably some error in the javascript console, that would be useful if that's accessible.

**Comment by wellerjes** [comment]
Here's the full screen: ![image](https://user-images.githubusercontent.com/93737929/148457807-efd636d7-af24-4e8b-a01e-96b55644f108.png)

**Comment by dustymc** [comment]
Thanks, that should be patched. It probably saved, so please be extra careful to clean up any duplicates that might have been created.

**Comment by wellerjes** [comment]
It's working! Thanks for the heads' up on the duplicates.
