### ISSUE TITLE
Code Table Request - make air temperature attribute available for Herp collections

### ISSUE THREAD

**Issue by gradyjt** [ArctosDB/arctos#4228]
Hello, I would like to be able to use the attribute "air temperature" for my herp collection. I see on the code table that Herp is not in the list of collections for that attribute type so I assumed I needed to request that it be so. Also, while I have you, where is the attribute type "weather"? I could have sworn I've uploaded weather attributes at least in a batch tool before but I don't see it in the bulkloading code table. Thanks!

**Comment by dustymc** [comment]
No actual objections, but that was created as a duct tape solution pending Event Attributes, which now exist: https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_event_attr_type

Suggest using those (and migrating then purging the object attributes, if anyone has some extra time just laying around...).

**Comment by gradyjt** [comment]
Ohhh, so I still need to load my event attributes separately from my bulkload data?

**Comment by dustymc** [comment]
Uh - yea, that's probably why we haven't scraped the duct tape off yet.

You can pre-create and use events, but I don't think there is a way to load/create them with new events/catalog records.

I think all adding that would need is a compelling use case, please feel very free to open another Issue!

(But I don't think I could get to adding in the very near future, so maybe go ahead with the catalog record attributes and a plan to move them to events when there's more functionality??)

**Comment by gradyjt** [comment]
Well, I'm not sure where that would leave "weather", probably a free text remark somewhere like specimen_event_remark for now? The thought of moving things around later sounds worse to me than just going ahead and batchloading collection event attributes separately now since my bulkloading needs are far below what the larger collections are doing. Though I should make a case for it. I will be using air temperature and weather relatively frequently in my collection. So what kind of issue and where do you suggest I make it? Thanks for the advice!

**Comment by dustymc** [comment]
> free text remark

Not if you want it to DO STUFF - you could pre-create the events, or request another (temporary) attribute.

>moving things around later sounds worse

I could help with that, but I'd definitely rather avoid the situation if possible. And I'm happy to help preload Events, especially if that means we don't have to shuffle things around later.

**Comment by gradyjt** [comment]
I think I understand what you're saying...except for the "do stuff" part...but I'm comfortable with separately bulkloading collecting event attributes for now I think. I don't think pre-loading events will be necessary in my situation because I will have a new, unique event for nearly every new specimen since most of our herps are individual observations. Rarely have formal surveys with lots of individuals at a single locality these days. (shrug) Does it sound like I'm understanding you?

**Comment by dustymc** [comment]
>do stuff" part

Given an attribute with units, you can ask all sorts of detailed questions and very quickly get trustworthy answers.  

Given a free-text "weather" attribute, you can find records that have something about weather, then try to parse out a single "field" of weather-stuff. Computers MIGHT help, but even slogging through manually probably wouldn't be completely impossible.

Without that, I don't think you can reliably search anything. The data are still useful for humans who've found the record, but not much beyond that.

There are lots of ways to do most everything in Arctos, I'd just recommend trying some small batch of whatever you think might work for you (a tutorial would be awesome if it does), and don't be afraid to speak up if you get stuck. We're all happy to help, and Arctos will get better for it.

**Comment by Jegelewicz** [comment]
@dustymc I'm pretty sure that @gradyjt is talking about the [collecting event attribute bulkload tool](https://arctos.database.museum/tools/BulkloadEventAttrs.cfm), addng the [air temp attribute](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_event_attr_type#air_temperature).

@gradyjt one thing to know is that it will be necessary? to name your events so that Arctos will understand which event you want to add a given attribute to. There is a process for giving a bunch of events temporary names to do this and I think @mvzhuang may have done this. It would be REALLY helpful to the whole community if you could [write documentation](https://handbook.arctosdb.org/how_to/How-to-Contribute-Content-to-Arctos-Handbook.html) or [make a video tutorial](https://github.com/ArctosDB/newsletter/issues/112) if you do this. And if I can help or need to organize meet-ups or anything, just let me know here!

**Comment by mvzhuang** [comment]
I haven't done it. I tried playing around with it a little, but I"m still confused how to do it. I wanted to bulk edit a bunch of collecting events at some point like verbatim localities or something and may still want to do that though. I have a student that might need a remote project this semester.

________________________________

**Comment by Jegelewicz** [comment]
OK then - maybe the three of us should work together to write the workflow? Unless @gradyjt wants to take it on and see what she comes up with?

**Comment by gradyjt** [comment]
> Without that

Pretty often our weather data is things like "hot", "hasn't rained in a while", etc so it would be assinine to try and look up what those things actually meant on that day, in that place to make a standardized attribute with units that is searchable, but I think these things are important to record somewhere because: 
> The data are still useful for humans who've found the record

So maybe free text weather stuff should be ok in specimen_event_remarks for now or always, but I would still definitely like to be able to bulkload all of my data once (so having a column for all--especially air temperature-- collecting event attributes in the bulkload template) someday.  


> it will be necessary to name your events so that Arctos will understand which event you want to add a given attribute to

Well, all of my records I'm loading have unique, new events so I have been just giving them an event name that is the same as the catalog number...I know this has the potential to break or prevent links with other catalog records, but in our case I really don't see this being an issue and I could always reverse it later. What are your thoughts?

> [write documentation](https://handbook.arctosdb.org/how_to/How-to-Contribute-Content-to-Arctos-Handbook.html) or [make a video tutorial](https://github.com/ArctosDB/newsletter/issues/112) if you do this.

At this point then I don't think I'll be doing what you're looking for as far as writing documentation on temporary event names, but I think you and I did something like that this summer where you clustered duplicate collecting events and gave all duplicates the "name" (in our case the catalog number) of the first record in that duplicate cluster.  I don't remember exactly what my part in that was--maybe just qaqc afterward--but I know you did the bulk of the work. Does that ring a bell?

**Comment by Jegelewicz** [comment]
> all of my records I'm loading have unique, new events so I have been just giving them an event name that is the same as the catalog number...I know this has the potential to break or prevent links with other catalog records, but in our case I really don't see this being an issue and I could always reverse it later. What are your thoughts?

IMO not a big deal. Searches will still find any events with exact same or close info depending upon the search parameters. Based on what you are cataloging, it is very (almost absolutely) unlikely that your events would ever merge with anyone else's because surely the collector would have seen/been the person collecting the mammal in the exact same spot on the exact same day/time and you would probably know about it?

Anyway, names can always be removed if needed.

**Comment by Jegelewicz** [comment]
> Does that ring a bell?

Ding dong! yeah - a very faint one. If I remember right, I just made a csv and dusty did the actual work, but I could be wrong about that! Anyway, sounds like you have this under control and won't need the air temp attribute for collection objects for herps?

@mvzhuang when you are ready to work on something, just ping me with an issue!

**Comment by gradyjt** [comment]
> won't need the air temp attribute for collection objects for herps?

If it's a lengthy process or one that noone has time to do right now I'm fine to load collecting event attributes separately. I've put off loading this dataset for too long anyway by my own busy-ness. Just glad to hear I'm doing it right mostly.

**Comment by Jegelewicz** [comment]
It's not lengthy - just a couple clicks, but I think the addition of attributes will serve you better in the long run. Still if you want the attribute, I can add it for you.

**Comment by gradyjt** [comment]
Agreed. I don't want to add a band-aid to what I'm sure is a long list of to-do's for you anyway so we can stick with status quo.

**Comment by gradyjt** [comment]
Thank you all for all the help and advice though!
