### ISSUE TITLE
allow bulkloader browse-and-edit sql tool to refrence column values

### ISSUE THREAD

**Issue by jtgiermakowski** [ArctosDB/arctos#4229]
Happy New Year!

I'm trying to be an effective SQL user here. I followed https://handbook.arctosdb.org/how_to/How-to-Use-Bulkloader-SQL.html  

Is there a way to use a value from one column as an input for another, rather than an actual, expected VALUE for that column (such as date)?  

For example, one of the students forgot to insert values into the column "attribute_date_1" so I'd like to 
UPDATE that column with values from "made_date", after, of course, filtering for just those records (see attached).

Possible or not?

![Screenshot 2022-01-06 at 16-24-31 Browse Edit Bulkloaded Data](https://user-images.githubusercontent.com/2381228/148468356-0bb13427-db63-4846-8b8f-defe2be4268b.png)

**Comment by jtgiermakowski** [comment]
I should add that trying to use "made_date" or 'made_date' or `made_date`  or even MADE_DATE into the Value field in the table above returns either an error or simply inserts that string into the "attribute_date_1" column... 

![Screenshot 2022-01-06 at 16-24-09 https arctos database museum](https://user-images.githubusercontent.com/2381228/148468879-f203e676-54f7-4bb3-b467-151b3bf0fb10.png)

**Comment by dustymc** [comment]
Nope, but maybe there should be - I'll hijack your issue. You can download/change/upload, or I can update if you want - is this them?

```

arctosprod@arctos>> select made_date, attribute_date_1 from bulkloader where enteredby='cxmcdaniels' and attribute_date_1 is null and made_date is not null;
 made_date  | attribute_date_1 
------------+------------------
 2009-08-19 | 
 2008-08-15 | 
 2009-06-03 | 
 2009-06-03 | 
 2008-08-16 | 
 2010-09-08 | 
 2008-08-07 | 
 2008-07-06 | 
 2009-06-22 | 
 2003-08-18 | 
 2008-06-09 | 
 2008-03-25 | 
 2008-06-09 | 
 2008-04-22 | 
 2008-06-06 | 
 2008-03-25 | 
 2010-09-09 | 
 2010-09-10 | 
 2008-03-25 | 
 2008-05-08 | 
 2010-09-09 | 
 2009-06-03 | 
 2008-09-05 | 
 2008-09-14 | 
 2008-06-09 | 
 2008-05-07 | 
 2010-09-10 | 
 2010-09-16 | 
 2008-06-09 | 
 2009-06-22 | 
 2010-06-08 | 
 2008-09-19 | 
 2008-07-25 | 
(33 rows)

```

**Comment by jtgiermakowski** [comment]
Sweet! Yes, that's it... it would be great to be able to do that in the SQL screen, especially when we find a match for collectors or have issues with dates (mostly badly formatted or forgotten values). Thanks @dustymc !

**Comment by dustymc** [comment]
UPDATE 33

**Comment by dustymc** [comment]
see also https://github.com/ArctosDB/arctos/issues/4830 - number of records per page should be user-selectable and default to small values which hopefully won't eat browsers.

**Comment by Jegelewicz** [comment]
Added high priority because of error message label.
