### ISSUE TITLE
clone into bulkloader fails

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#4232]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Tried to use the clone catalog record into bulkloader option and got this error:

cloning failed: fail: ERROR: INSERT has more expressions than target columns
 Where: PL/pgSQL function cat_rec_2_bulkloader(character varying,character varying) line 545 at EXECUTE 

was trying to clone this record: https://arctos.database.museum/guid/UAM:Ento:76726

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.
high

**Comment by dustymc** [comment]
patched
