### ISSUE TITLE
Arctos Down - 9AM Central Friday Jan 7

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4233]
Please complete to the best of your ability.

## Planned Outage
 - Date and time outage will begin: 9AM central time Friday Jan 7
 - Date and time outage is expected to end: 9AM central time Friday Jan 7
 - Reason for outage: server upgrade
 - Expected behavior during and after the outage: Arctos may be down briefly, hopefully there won't be noticeable outage but sessions will probably not survive the move and users will need to log back in.

## Communication before/during outage
- [x] Pin this issue
- [x] Banner updated @jegelewicz 
- [ ] Email sent to AWG 
- [ ] Email sent to Arctos Google Group 
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [x] Unpin this issue
- [x] Banner updated @jegelewicz
- [ ] Email sent to AWG 
- [ ] Email sent to Arctos Google Group 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by Jegelewicz** [comment]
I'm logged in and haven't noticed a thing (I logged in after 9 central...)

**Comment by Jegelewicz** [comment]
Just received this email

> Hi Teresa,
> 
> When I try to go to arctos.database.museum I get "403 error"
> 
> Has our IP address been blocked or something? This is really bad timing because I have someone here today to work in the collections.
> 
> Thanks!

@kmkocot

**Comment by dustymc** [comment]
Arctos is back up

**Comment by mkoo** [comment]
Updated banner-- since the outage happened so early for us west-coasters I left a message to expire today.

**Comment by mkoo** [comment]
ps. if no other messages went out on twitter or group email, this issue can be closed

**Comment by lin-fred** [comment]
closing!

**Comment by Jegelewicz** [comment]
I think something strange happened. Yesterday I created an agent - Cecil Bernard Dudley Garrett

Today he is not there. Was any data lost in whatever happened this morning?

**Comment by Jegelewicz** [comment]
never mind - maybe my bad not hitting save the second time?

**Comment by dustymc** [comment]
<img width="1417" alt="Screen Shot 2022-01-07 at 9 53 47 AM" src="https://user-images.githubusercontent.com/5720791/148585976-e446c440-e55e-4208-83b3-45eb2c887657.png">

https://arctos.database.museum/agents.cfm?agent_id=21336108

Looks like a few dups....


The DB wasn't touched this AM, and the proxy mappings were rolled back. I can't 100% guarantee that nothing spooky happened, but I don't think there's any plausible way that any hauntings could be related to the outage.

**Comment by Jegelewicz** [comment]
> Looks like a few dups....

Not sure because  he was en entomologist and those others didn't collect insects....

**Comment by Jegelewicz** [comment]
I spent like an hour digging up his name - he really is only cited in all collections ad C.B. Garrett or C.B.D. Garrett
