### ISSUE TITLE
Feature Request - pass other identifier uri to DwC when there is one

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4234]
**Is your feature request related to a problem? Please describe.**

> We should be making links from Arctos to MS, and I will do that with Jessie's scans once she sends me the Specimen IDs. There is a plan to automate that at some point, but I don't know how/when so it needs to be manual for now. At least that's my understanding. 
@ccicero 

> what about including something that links each record to MorphoSource so that things go both ways? I see that MorphoSource references the iDB link and the Arctos link, but I don't see anything that would take a data user from the record in iDB, GBIF, VN, or elsewhere back to MorphoSource. Any thoughts to include a link in associatedMedia or associatedReferences or otherCatalogNumbers or another appropriate DwC field? Something that we can include in the monthly publication events.
@dbloom 

> It would be in other catalog numbers if recorded as an "other identifier" type=Morphosource as long as the base url for the identifier is correct.

@Jegelewicz 

> Here's an example of an Arctos herp record that displays the Morphosource number in the "Other Catalog Numbers' field in both iDigBio and GBIF. There is no URL to link it to the MS record, however (i.e., the URL part is getting stripped off).
> 
> If I search the MS number 3745 in MS, I get something totally different:
> https://www.morphosource.org/catalog/media?utf8=%E2%9C%93&search_field=all_fields&q=3745
> 
> The only way to find the record by searching MS is to enter "0000S3745" which is the full MS Specimen ID number, but that is certainly not intuitive. 

@ccicero 

> I know the mechanism is there to link things in both directions, but I'm not sure that the collections always enter the links/IDs correctly, if at all.
> 
> I took a look at the l first record that Carol posted: https://www.morphosource.org/concern/biological_specimens/000410459
> 
> The links back to iDigBio and back to Arctos (occurrenceID) are present on MorphoSource, but I did not see any reference to MS or to the MS SpecimenID in Arctos (https://arctos.database.museum/guid/MVZ:Bird:190924?seid=4084560), GBIF (https://www.gbif.org/occurrence/1888912743) or iDigBio (https://www.idigbio.org/portal/records/b07c77d6-626c-4889-84d2-f4dda2de7624) - it's not in VertNet either - , which suggests that this data is either not in Arctos at all or it is in a field that is not mapped and published via the IPT.
> 
> I believe this is the reason that Cat at iDB contacted me in the first place, I understood this to be a part of what Jessie is trying to accomplish - getting the links/IDs incorporated into the actual occurrence records so that they are present in all of the portals. Please correct me if I am wrong.

@dbloom 

**Describe what you're trying to accomplish** 

> There needs to be a better way of displaying these in the aggregators so that they actually link to the MS record, or else show the full Specimen ID number = 0000S3745.

@ccicero 

> Julie and dusty are supposed working in this but I and maybe Carla need to remind them, or remind dusty, I would like this accomplished BEFORE the official oVert grant ends this August, if possible. And yes yo Carla’s point, many records on MS don’t have the occurrence IDs, Arctos link etc, so those would have to be fixed too. 

@atrox10 

**Describe the solution you'd like**
> We could include identifier prefix in DWC

@dustymc 

**Describe alternatives you've considered**

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/internal/issues/168
