### ISSUE TITLE
Agent Help Request: C.B. Garrett

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4235]
> Looks like a few dups....

Not sure because  he was an entomologist and those others didn't collect insects....

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/arctos/issues/4233#issuecomment-1007615401_

**Comment by dustymc** [comment]
> others didn't collect insects....

... that got cataloged in the museum of vertebrate zoology...

No way https://arctos.database.museum/info/agentActivity.cfm?agent_id=10004306 isn't somehow related to https://arctos.database.museum/info/agentActivity.cfm?agent_id=21336108 - same person, Jr., ?????

@ccicero @mkoo @cjconroy

**Comment by campmlc** [comment]
Hmm, maybe we need a new media relationship = "documents agent". We already
have "created by agent" and "shows agent", but neither of those apply. It
would be great to have the media display with the agent entry.

**Comment by Jegelewicz** [comment]
I would vote that C. B. Garrett is the same person as Cecil Bernard Dudley Garrett.

**Comment by dustymc** [comment]
Thanks @cjconroy !
