### ISSUE TITLE
Help needed to bulk change accession number.

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#4236]
We were recently able to accession a large group of specimens that, before I started, had been cataloged but not accessioned. When we uploaded these specimens we added them to our 9999 placeholder accession (for unknown accession #s). I'd now like the accession numbers for the records to be batch updated to the new accession. There are almost 4,000 specimens, so doing this manually isn't a good option. Below is a csv of the data with the guids and accession number. If I've missed a way I could do this with bulk tools I apologize
[GUMO Accession Bulk Change.csv](https://github.com/ArctosDB/arctos/files/7830682/GUMO.Accession.Bulk.Change.csv)
.

**Comment by dustymc** [comment]
If you can find them all in a search, ...
<img width="298" alt="Screen Shot 2022-01-07 at 10 44 29 AM" src="https://user-images.githubusercontent.com/5720791/148591726-83c20442-c893-4fec-9ff1-2167f954f98f.png">

... might do what you want (or melt something, IDK...)

Or I can swap them for you, just let me know.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
That worked, thank you!
