### ISSUE TITLE
Make object tracking search better

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4240]
In object tracking planning, we decided that placing Collection at the top of the search form would make it more consistent with the main search page.

![image](https://user-images.githubusercontent.com/5725767/148816753-b419dca9-fb97-412c-973f-ec9be6a4e33e.png)

![image](https://user-images.githubusercontent.com/5725767/148816890-c074bbd6-82a5-4bbf-a8d4-cfa7ca53a8de.png)

**Comment by campmlc** [comment]
Also moving "In Barcode" to underneath "Barcode" to show that there are two
options, perhaps with some documentation link that will explain that In
Barcode is needed for a list if you wish to see the actual collection
objects.

**Comment by Jegelewicz** [comment]
Made these changes in test.

**Comment by campmlc** [comment]
From #2209 
1) change 'In Barcode' to 'In (immediate parent container) Barcode' - wordy,
but will eliminate confusions!

& yes, we'd love another field that actually searched 'in (any parent
container)' if that could be done.
@DerekSikes
