### ISSUE TITLE
Code Table Request - Part Attribute: storage temperature

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4242]
**Goal**
Record the various "kinds of frozen" - see https://github.com/ArctosDB/arctos/issues/3649

**Context**
This attribute would allow for more precision and could be populated from container environment in object tracking as needed (perhaps only when a freezer exceeds a temperature threshold?)

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecpart_attribute_type

**Proposed Value**
storage temperature

**Proposed Definition**
The temperature of the environment where the object is stored.

**Collection type**
All collections

**Attribute data type**
number+units

**Attribute value**
N/A

**Attribute units**
https://arctos.database.museum/info/ctDocumentation.cfm?table=cttemperature_units

**Available for Public View**
**Yes** 

**Other ID BaseURL**
[  For OtherIDs, provide the following *or* explain why the unresolvable ID type is necessary:
1. "Base URL" with which to prepend entered values, and
2. A functional example URL, which should consist of the base URL provided in (1) plus a relevant value.  ]

**ID_References**
[  If the request involves https://arctos.database.museum/info/ctDocumentation.cfm?table=ctid_references, the changes must be coordinated with the Database Admin team for notifications to function.  ]

**Priority**
[  Please choose a priority-label to the right.  ]

**Comment by Jegelewicz** [comment]
Could we get container history at the part with a button? It would add attributes at the time we used it.

Move stuff - add an attribute.

So let's add this attribute and work on the magic button from containers in object tracking

**Comment by Jegelewicz** [comment]
New term added

**Comment by Jegelewicz** [comment]
New issue created for transaction magic - closing

**Comment by dustymc** [comment]
Coming from https://github.com/ArctosDB/arctos/issues/6124

This was not implemented as requested, and as free-text I think it's just [condition report](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecpart_attribute_type#condition_report) with extra pointless complexity?? I don't understand why this exists; can we get rid of it?

```
arctosprod@arctos>> select attribute_value from specimen_part_attribute where attribute_type ='storage temperature' group by attribute_value;
 attribute_value 
-----------------
 left M2/
 ambient
 -80C
(3 rows)
```

**Comment by campmlc** [comment]
We actually need to implement this to distinguish between different levels
of " frozen". I didn't know we had it.

**Comment by dustymc** [comment]
>distinguish between different levels of " frozen"

That's what was originally proposed and does seem useful. That is not what's implemented. (Or, it is, but not intentionally and that's incompatible with existing data.)

**Comment by Jegelewicz** [comment]
I would prefer that we implement this as originally intended - this is my fault for not adding the units to the attribute - a year ago seems like decades right now and I apologize for missing this or not following up or whatever happened. Let me know how I can help.

**Comment by Jegelewicz** [comment]
I fixed the left M2/ one

**Comment by dustymc** [comment]
> implement this as originally intended 

Sounds good to me - the -80C is one record, deleting it and adding it back with units is probably simplest, we just need to find a place for the 'ambient' values.

**Comment by Jegelewicz** [comment]
> find a place for the 'ambient' values.

I think you already found it? condition report?

**Comment by dustymc** [comment]
Looks like those are MSB:Herp - @campmlc @jtgiermakowski can I change storage temperature to condition report?

**Comment by campmlc** [comment]
What I need is a part attribute that explicitly records temperature.
Ideally, it should be some part of the preservation = frozen part
attribute. I can put temperature in method - but frozen is a very vague
term, whereas frozen at -20C or -80C or -193C are explicit.
Condition report does not accurately reflect this.
We need to document the difference between something that was collected in
the field directly into LN2 and transferred on nitrogen to cryotanks to
keep the cold chain; vs something that was collected on ice, frozen -20C
for a year, defrosted to prep, and tissues archived first in -80C and then
a year later in -194C. None of our current part attributes can capture
this. At the very least, we could have temperatures recorded at time of
collection and at time of transfer to DGR - anything with more detail than
"frozen" is needed.

**Comment by campmlc** [comment]
So no, please don't change to condition report. What we need is an expanded
usage of temperature ("storage" is misleading).

**Comment by Jegelewicz** [comment]
@campmlc the things that have been recorded are "ambient" NOT some specific temperature. We need to get those out of this attribute so that we can use it as intended value = -80 units = celcius.

**Comment by campmlc** [comment]
I see - Ok to convert.

**Comment by dustymc** [comment]
arctosprod@arctos>> 
arctosprod@arctos>> update specimen_part_attribute set 
arctos-> attribute_value='storage temperature: ambient',
arctos-> attribute_type='condition report'
arctos-> where 
arctos-> attribute_type ='storage temperature' and 
arctos-> attribute_value='ambient' and 
arctos-> attribute_units is null;
UPDATE 158
