### ISSUE TITLE
Feature Request - Add Institution to object tracking search

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4244]
**Is your feature request related to a problem? Please describe.**
When searching object tracking, it is possible to see containers "claimed" by other institutions. This can be helpful or cause confusion.

**Describe what you're trying to accomplish** 
Looking for a way to limit search to only those barcodes which an institution has claimed

**Describe the solution you'd like**
Add a search term  - Institution which provides a drop-down of the institution codes used to claim barcodes.

**Describe alternatives you've considered**
Search for only a given collection - but some tissue managers manage across collections within an institution.

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by Jegelewicz** [comment]
@Nicole-Ridgwell-NMMNHS @campmlc @KyndallH do any of you need this? I asked for it because of something I was doing at some point, but apparently I managed without it. If no one needs it, I'll close this.

**Comment by campmlc** [comment]
Yes, it would be helpful in the context of searching using a % in label and limiting by institution.

**Comment by Jegelewicz** [comment]
This was closed as completed and I see a search field for collection, but not Institution.

**Comment by campmlc** [comment]
Still would be helpful, or allow the option to select multiple collections.

**Comment by dustymc** [comment]
I don't think this can be relevant post- https://github.com/ArctosDB/arctos/issues/6789, closing.
