### ISSUE TITLE
Arctos Down - 1/10/22

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#4245]
Please complete to the best of your ability.

## Unplanned Outage
 - Date and time outage discovered: ~1:45 pm MT
 - Describe the outage (Arctos down or only some part not working?):
![image](https://user-images.githubusercontent.com/47402809/148838513-c9abae08-3398-4104-a006-8e863e11480a.png)

## Communication before/during outage
- [x] Pin this issue
- [ ] Banner updated @jegelewicz 
- [x] Email sent to AWG 
- [ ] Email sent to Arctos Google Group 
- [x] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @jegelewicz
- [ ] Email sent to AWG 
- [ ] Email sent to Arctos Google Group 
- [x] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by lin-fred** [comment]
It also is down for me

**Comment by dustymc** [comment]
I sent Chris email - looks like maybe all of TACC is down

**Comment by lin-fred** [comment]
sent out an arctos status tweet

**Comment by ewommack** [comment]
Chris sent the following email to the AWG:
There is a network hardware issue impacting access to TACC systems across the board at present, including Arctos. We don’t get have an ETA for resolving these issues but, if they are not resolved shortly, we’ll get an update out on when we expect to have them fixed.

Since this is just a network issue at this point, once it is resolved Arctos should immediately be available again.

Thanks

**Comment by ewommack** [comment]
Looks like we're back up? Anyone else getting into the site just fine?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Still down for me.

**Comment by lin-fred** [comment]
Also still down for me

**Comment by ewommack** [comment]
Ah weird! I'm working just fine. Mac, Chrome.

@dustymc do you still see it down?

**Comment by dustymc** [comment]
All channels down from here, which isn't completely unexpected with network issues.

**Comment by ewommack** [comment]
Huh. I'm wandering around all over Arctos for the UWYMV collections. Data entry, projects, specimen info, media. The only thing coming up funny I'm getting a 408 error for our links to the Sketchfab specimens.

**Comment by cjconroy** [comment]
functional here at MVZ, except slow to look maps. Bottom bar said waiting on googlemapapis.com

**Comment by lin-fred** [comment]
it is back up for me

**Comment by ewommack** [comment]
Got the following notice from TACC at 1821 MT:
Network Status 10 January 2022
From: David Littrell
From 2:10 to 6:30 pm CST network disruption prevented users from being able to access TACC systems. The issue has been resolved.
