### ISSUE TITLE
Arctos Down - Arctos isn't working at home or at MVZ 1 pm PST Monday Jan 10

### ISSUE THREAD

**Issue by atrox10** [ArctosDB/arctos#4246]
Arctos isn't working right now!!

## Unplanned Outage
 - Date and time outage discovered:
 - Describe the outage (Arctos down or only some part not working?):

## Planned Outage
 - Date and time outage will begin:
 - Date and time outage is expected to end:
 - Reason for outage:
 - Expected behavior during and after the outage:

## Communication before/during outage
- [ ] Pin this issue
- [ ] Banner updated @jegelewicz 
- [ ] Email sent to AWG 
- [ ] Email sent to Arctos Google Group 
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @jegelewicz
- [ ] Email sent to AWG 
- [ ] Email sent to Arctos Google Group 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by lin-fred** [comment]
oh wow you guys did one at the same time haha! #4245
