### ISSUE TITLE
bulkloader assistance

### ISSUE THREAD

**Issue by cefilipek** [ArctosDB/arctos#4247]
I would like to use the bulkloader, but there is data that has been in there since Sunday night. I contacted them about 45 minutes ago and have received no response.

**Comment by dustymc** [comment]
You can just download the data and stash it somewhere safe if they haven't responded in a reasonable amount of time - an Issue seems to work, but UWBN has no contacts with github addresses so not ideal in this case.

I'll update the inline instructions.

Data attached, delete away....

[bulkloader_stage(3).csv.zip](https://github.com/ArctosDB/arctos/files/7848737/bulkloader_stage.3.csv.zip)

**Comment by cefilipek** [comment]
Thanks
