### ISSUE TITLE
Need Help with Arctos Error - "Collection_ID" is ambiguous"

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#4249]
Error text:
An error occurred while processing this page!
Message: ERROR: column reference "collection_id" is ambiguous Position: 121
![image](https://user-images.githubusercontent.com/11336485/149035288-2dccb50d-19f5-48d8-ba1b-b675ba7df3cc.png)

Where it happened:
https://arctos.database.museum/tools/BulkloadLoan.cfm

CSV (small sample for first pass of what will be a 400+ loan retrocapture):  [loan_retrocapture_test.csv](https://github.com/ArctosDB/arctos/files/7850379/loan_retrocapture_test.csv)

**Comment by dustymc** [comment]
Should be patched up for next release (tonight, I hope) - real solution is https://github.com/ArctosDB/arctos/issues/3799

**Comment by ebraker** [comment]
Awesome, thanks! Onwards and upwards out of ambiguity!

**Comment by ebraker** [comment]
Sort of related(?)...Bulkload Loan Item is not finding catalog records that are indeed in Arctos:

![image](https://user-images.githubusercontent.com/11336485/149583687-25d84553-9e65-4035-b328-a908bd381bcc.png)

https://arctos.database.museum/guid/UCM:mamm:17991
https://arctos.database.museum/guid/UCM:mamm:17992
https://arctos.database.museum/guid/UCM:mamm:17994

I'm doing a large legacy load so I figure there will be a reasonable chunk of catalog number gaps etc., but I'm coming up with 3000+ "catalog item not found." FYI over 1000 did in fact load. Perhaps I need to break csv into smaller bites?

**Comment by dustymc** [comment]
I think you're using an old and unsupported format - 'catalog number' (I assume that's otherIDType) no longer works, you can use GUID.

**Comment by ebraker** [comment]
Ok, I can go ahead and reload by GUID instead, thanks. However, I have a couple hundred records where I need to use GUID prefix + other ID since I'm referencing "UCM Osteology" number and don't know cat_num. Is there a way to search multiple other IDs at once to look up cat#s?

**Comment by dustymc** [comment]
You can still use otherIDs, it's just limited to those in https://arctos.database.museum/info/ctDocumentation.cfm?table=CTCOLL_OTHER_ID_TYPE.
