### ISSUE TITLE
Question about media metadata bulkloader relationships

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4251]
Quick question - in the media metadata bulkloader column "media relationships" = associated with project, what do we put for the value for  media_related_term_1? The project url or just the project number embedded in the url, or ?

**Comment by dustymc** [comment]
``10000356``


<img width="919" alt="Screen Shot 2022-01-12 at 7 44 54 AM" src="https://user-images.githubusercontent.com/5720791/149173047-d524fdde-3bc5-47d6-a2f5-c761f3bb13d5.png">

**Comment by campmlc** [comment]
We should add that to the documentation, which currently only has:
<html>
<body>
<span style="color: rgb(0, 0, 0); font-family: Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Documentation for code table<span> </span></span><strong style="color: rgb(0, 0, 0); font-family: Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">MEDIA_RELATIONSHIP</strong><span style="color: rgb(0, 0, 0); font-family: Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"><span> </span>~<span> </span></span><a href="https://arctos.database.museum/info/ctDocumentation.cfm" style="text-decoration: none; color: blue; font-family: Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px;">[ table list ]</a><span style="color: rgb(0, 0, 0); font-family: Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"><span> </span></span><a target="_blank" href="https://arctos.database.museum/Admin/CodeTableEditor.cfm?action=edit&amp;tbl=CTMEDIA_RELATIONSHIP" style="text-decoration: none; color: blue; font-family: Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px;"><input type="button" class="lnkBtn" value="edit" style="color: rgb(102, 102, 102); font-size: 10pt; font-weight: 700; background-color: rgb(153, 204, 255); border: 1px solid;"></a><span style="color: rgb(0, 0, 0); font-family: Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"><span> </span></span><a target="_blank" href="https://arctos.database.museum/info/ctchange_log.cfm?tbl=CTMEDIA_RELATIONSHIP" style="text-decoration: none; color: blue; font-family: Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px;"><input type="button" class="lnkBtn" value="changelog" style="color: rgb(102, 102, 102); font-size: 10pt; font-weight: 700; background-color: rgb(153, 204, 255); border: 1px solid;"></a><span style="color: rgb(0, 0, 0); font-family: Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"></span><div style="color: rgb(0, 0, 0); font-family: Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="likeLink" onclick="manageCTMeta('CTMEDIA_RELATIONSHIP','media_relationship');" style="cursor: pointer; color: blue;">Manage Metadata</span></div>

MEDIA_RELATIONSHIP | Documentation | Metadata
-- | -- | --
associated with project [ link ] | Media with an association to projects, but one which cannot be expressed more directly, e.g., through involved specimens.


</body>
</html>

**Comment by campmlc** [comment]
Also need to add to documentation here:
https://handbook.arctosdb.org/how_to/How-to-Bulkload-Media-Metadata.html

**Comment by dustymc** [comment]
The code table documentation describes the form and intent of relationships between data objects. The bulkloader documentation describes how to reference data objects for a very specific purpose. Those are different things, and I don't think anything is missing.

How-tos are yet another thing - they're examples of how to use stuff, not strictly "documentation." There are lots of ways to create media relationships, one of them involves a particular bulkloader, the how-to is an overview of some of the ways to use the tools.

**Comment by campmlc** [comment]
I am trying to follow the how-tos to create a media metadata file, and it is missing critical informaton that is only found on the media metadata bulkload load csv page. It would be exceedingly helpful if all the instructions for doing this complex process were in one place- or in multiple places, so we don't have to toggle between so many forms and code tables and bulkloaders just to fill in values in a spreadsheet.

**Comment by campmlc** [comment]
Another question on using media labels - can barcode be used for other containers besides herbarium sheets? If I add a container barcode as a media label, does that break anything? I have images taken from barcoded slides.

**Comment by campmlc** [comment]
And am I allowed to add more than one label per label type? E.g. more than one media_label and media_label_value for description?

**Comment by Jegelewicz** [comment]
@campmlc Please just write the needed documentation. We don't have anyone dedicated to do this and it never gets properly done because nobody takes the time to do it. PLEASE either write down what you think needs added here so that I can add it or just add it yourself. We have way too many issues asking for documentation to be changed or written and nobody following up.

**Comment by campmlc** [comment]
I can't stop in the middle of what I am trying to do to write the documentation, unfortunately - which is why I was posting here.  I'll try to remember to come back to it, but I am deep in the weeds of learning a new and confusing process.

**Comment by campmlc** [comment]
See also #4193 - I can't check to see what others have used for media label value because the search tool is not working.

**Comment by dustymc** [comment]
>instructions for doing this complex process were in one place

I don't really disagree, but I don't think we can realistically expect to maintain that either. I don't want to have to update the bulkloader when a term definition changes, and I don't want to have to update the 37 how-tos when the bulkloader changes. I can get by part of that by pulling/linking bits of Arctos (eg the CT documentation) into other bits (eg bulkloaders), but that doesn't extend to the how-tos (in the current architecture). Lacking a documentation team, I think this really has to be seen as three things:

* how the data/model/guts/core-bits actually work (eg code tables)
* how tools work (usually-inline documentation)
* how someone's used some tool to accomplish some task (how-tos).


[Barcode](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctmedia_label#barcode) is just text; you can do whatever you want with it, as long as that can be done in UTF. It's really handy for processing images, I'd not recommend denormalizing if you're attaching images to some sort of container-related record. There's no relationship between the Arctos container model and media label "barcode."

You can apply any number of media labels, but duplicates can break things like [multi-page documents](https://arctos.database.museum/Reports/mpd_info.cfm) and title/alt tags. Duplicating [description](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctmedia_label#description) will lead to something weird in the UI.

**Comment by campmlc** [comment]
This sounds like a great idea: pulling/linking bits of Arctos (eg the CT documentation) into other bits (eg bulkloaders)

**Comment by dustymc** [comment]
> great idea:

I agree; that's why I've been doing it forever!

<img width="641" alt="Screen Shot 2022-01-12 at 11 09 39 AM" src="https://user-images.githubusercontent.com/5720791/149205990-17bf030f-fc41-4700-ad0c-048f135e699c.png">

Some other format is possible; that would need discussed separately and could be incorporated as the next component loader version.

**Comment by campmlc** [comment]
And if we had the information on what value to use for e.g. the project label in the associated CT, then all would be in one place . . .

**Comment by dustymc** [comment]
>had the information on what value to use for e.g. the project label in the associated CT, then all would be in one place .

That would just be wrong. The relationship - what's described in the code table - is to the data object, not any summary, url-bit, identifier, or any other subset or representation of the data object. (And what "the data object" consists of depends entirely on your viewpoint; there are no hard lines.)

**Comment by campmlc** [comment]
I don't think we are communicating well  - I'm not talking about putting a specific data object in the code table.
