### ISSUE TITLE
Higher Geography field in Data Entry Screen not working

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#4253]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
While using the single data entry screen for a bird catalog entry the Higher Geography field no longer searches and provides options for selecting higher geography for the specimen. Instead I received the following error:
An error occurred while processing this page!
Check the Arctos Handbook for more information on errors.
This message has been logged as F4D2CA74-E654-48E6-95589A7C6511E1E7 Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue..

**To Reproduce**
Go to the Data Entry Screen for a bird catalog record -> go to the Higher Geography Field -> type in Sheridan and hit return -> get a pop up window the with the error message.

**Desktop (please complete the following information):**
Chrome, Mac

Not sure what I am doing wrong, but I'm logged into the regular Arctos set, not test. And the Higher Geography search is just not working at all.

**Comment by dustymc** [comment]
<img width="1036" alt="Screen Shot 2022-01-12 at 6 41 44 PM" src="https://user-images.githubusercontent.com/5720791/149256362-4ecda2e7-537b-4eab-9e03-97242873774f.png">


Log in.

**Comment by ewommack** [comment]
Thanks @dustymc I'll give it a try, but I was logged in. I don't think I could even get to the data entry page without being logged in. I'll try it again

**Comment by ewommack** [comment]
It works now! I don't understand why it is different, but I don't care. I'll call it Dusty magic.
