### ISSUE TITLE
Feature Request - Add UTM and datum to coordinate converter

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#4255]
**Is your feature request related to a problem? Please describe.**
Now that we have postGIS, it would be great to add UTM and datum to the coordinate converter. Since we add our localities independent of specimens/events, this would be really helpful.

**Describe what you're trying to accomplish** 
Speed up locality data entry by not having to go to a third party website for UTM conversion.

**Describe the solution you'd like**
Add UTM and datum to coordinate converter.

**Describe alternatives you've considered**
The alternative is using another program/converter website for UTM conversion, but now that we have postGIS this seems unnecessary.

**Comment by dustymc** [comment]
>the coordinate converter

The what now?!? Link/details plz.

Short answer is "yes" - I'm happy to provide tools and doing so seems pretty easy now that I have the ability, if there's something (which I can't find...) I'm happy to build on it, or let me know what you're looking for.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> Link/details plz.

On the locality edit page

![image](https://user-images.githubusercontent.com/47402809/149396595-ebd47170-b417-40f2-a5ab-a3cae9c33ee4.png)
![image](https://user-images.githubusercontent.com/47402809/149396658-0f74e2a9-5a4f-40cf-8999-5d72be19c3e8.png)

**Comment by Jegelewicz** [comment]
BTW - bulkloader would not accept my UTM data last week - don't know if that is different now.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thank you!
