### ISSUE TITLE
Arctos Down - 9AM Central January 14

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4256]
Please complete to the best of your ability.

## Planned Outage
 - Date and time outage will begin: 9AM Central January 14
 - Date and time outage is expected to end: 9AM Central January 14
 - Reason for outage: upgrade hardware
 - Expected behavior during and after the outage: Arctos will be down, should be brief.

## Communication before/during outage
- [x] Pin this issue
- [x] Banner updated @jegelewicz 
- [x] Email sent to AWG 
- [x] Email sent to Arctos Google Group 
- [x] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [x] Unpin this issue
- [x] Banner updated @jegelewicz
- [x] Email sent to AWG 
- [x] Email sent to Arctos Google Group 
- [x] Tweet @lin-fred (@mkoo backup)
- [x] Close this issue when above are complete

**Comment by mkoo** [comment]
define 'brief' so I can add to the banner notice

**Comment by dustymc** [comment]
Hopefully milliseconds but that didn't work out so well last time. We'll probably roll back if it looks like it might stretch into hours.

**Comment by mkoo** [comment]
banner added. @ewommack do you want me to send a AWG note?

**Comment by ewommack** [comment]
Sent, but you can totally do it as well @mkoo any time you like.

**Comment by ewommack** [comment]
Working just fine for me. I'll send out the follow up email.
