### ISSUE TITLE
Cannot set "status" to "DELETE" when "status"='coordinate value error' - need help

### ISSUE THREAD

**Issue by jtgiermakowski** [ArctosDB/arctos#4260]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

some entries in our bulkloader did not have properly set coordinates so status was automatically updated to 'coordinate value error'  I tried to DELETE these records both through the button ("DELETE all selected Records") and by using the SQL interface (where I tried to update "status" to 'DELETE'). Neither method worked.

**To Reproduce**
see above and attached screenshot of records in question. Issue seems to persist in other instances (with other accessions or usernames)

**Expected behavior**
set "status" to DELETE to delete records from bulkloader

**Screenshots**
![Screenshot 2022-01-13 at 14-12-43 Browse Edit Bulkloaded Data](https://user-images.githubusercontent.com/2381228/149410999-af97fe6a-6454-4fe3-9b5b-68dd70603752.png)

**Desktop (please complete the following information):**
Windows 10 Pro with Firefox 96.0

**Additional context**
Issue survives auto_load. I was able to load properly formatted records from the bulkloader from the same accession.

**Priority**
High! I want to clean this up ASAP.

**Comment by dustymc** [comment]
Yes, this is a bug (that I don't yet have a solution for), I think there's an issue somewhere...

Let me know how to find them and I can delete for you.

**Comment by Jegelewicz** [comment]
Issue somewhere - https://github.com/ArctosDB/arctos/issues/4197#issuecomment-1004322229

**Comment by dustymc** [comment]
fixed
