### ISSUE TITLE
Would like to have spaces between GUIDs in search

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#4261]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
I frequently get lists of GUID's in loan requests or other business. 

**Describe what you're trying to accomplish** 
When I get a list of GUID's, it would be nice to just paste them into the window on Arctos and query for them. Cannot. Must first paste into text editor, replace spaces with comma, then paste over. Or, I find and delete the MVZ:Mamm: part, then paste the numbers into the catalog number box and select my collection. 

**Describe the solution you'd like**
Why not just make it accept spaces between GUID's? You can do that with catalog numbers. 

**Describe alternatives you've considered**
There is no other option. 

**Additional context**
The help links here do not say MUST be comma separated. The popup window says "Search ACCEPTS GUID (UAM:Mamm:12) or comma-separated list (UAM:Mamm:12,UAM:Mamm:34)". There should be a more obvious highlight next to this window that says this is the only way to go 

**Priority**
medium. I can work around it, but it always adds work.

**Comment by Jegelewicz** [comment]
@cjconroy use this nifty little tool - https://arctos.database.museum/DataServices/listerizer.cfm

<img width="960" alt="Screenshot 2022-01-13 15 01 59" src="https://user-images.githubusercontent.com/5725767/149416098-54e631b6-4589-4428-8830-b09a964bd04f.png">

**Comment by cjconroy** [comment]
Thanks. Would still rather just paste into the GUID box. Maybe that's not possible

**Comment by campmlc** [comment]
I support this request. But in the meantime, there is another tool you can
use in Arctos quicker than a text editor for making comma list strings-
well hidden, but useful. Go to Reports/Services ->Data Services-> Make
Comma List from Anything.
We should probably post this one in the newsletter.

**Comment by campmlc** [comment]
Apologies - Teresa beat me to it and I was reading email from the bottom. But that tool is useful also for things like barcode strings etc. 
I do think anything we can do to make it possible to avoid having to leave a form to go into another form or external service to complete a task should be supported.
