### ISSUE TITLE
New Data Entry Screen - help with customizations?

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#4264]
@dustymc is there a good way to customize the new data entry screen? I thought that the bird and mammal screens would have the attributes already selected (sex, age, molt, skull, weight), but when I select to enter a UWYMV:Bird entry it doesn't.

Is it best if collections request these individually, or should they do the customizations themselves?

**Comment by ewommack** [comment]
Never mind! Found it! We definitley need documentation. I keep losing myself.

**Comment by Jegelewicz** [comment]
> We definitley need documentation.

We need, but WE also must write.....
