### ISSUE TITLE
Code Table Request - New container type: floor

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4266]
**Goal**
Make the various floors of a building part of the object location tree

**Context**
I thought about using range - but I am going to need ranges for parts of building that are not rooms

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcontainer_type

**Proposed Value**
floor

**Proposed Definition**
All the rooms or areas on the same level of a building; a story.

**Priority**
Needed for object tracking in ALMNH Gorgas House as part of spring semester student project.

**Comment by ccicero** [comment]
@Jegelewicz 
This was discussed at the CT meeting 20 Jan 2022. The term 'floor' was confusing - several of us thought it referred to a foor (in Dusty's words, 'where gravity takes stuff') versus the level of a building. Suggested term = 'building level' but maybe put 'floor' in the definition.

**Comment by Jegelewicz** [comment]
Great! I had the same thought and thanks you guys for giving me a solution. Plus "building level" will nest nicely within "building".

**Comment by Jegelewicz** [comment]
added to code table
