### ISSUE TITLE
Unanticipated changes in WoRMS taxon name

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#4268]
It appears that WoRMS has changed a number of taxon names without changing the aphiaID or we had taxon names in error that were fuzzy matched to a WoRMS aphiaID.  I found these while working through a list from @albenson-usgs of taxon names used as identifications in DMNS:Inv that are not in WoRMS.

Example is _Dentimargo pumilus_ which we were using as an identification for [DMNS:Inv:33363.](https://arctos.database.museum/guid/DMNS:Inv:33363).  When I opened the taxon page for WoRMS (via Arctos) this was the entry.  

  
<img width="1421" alt="Dentimargo pumilus aphiaID 473764" src="https://user-images.githubusercontent.com/15368365/149636003-32623522-17da-4101-b56e-6db4086a9319.png">

After I refreshed the entry, the species name changed to _Dentimargo pumila_.

<img width="1449" alt="Dentimargo pumila aphiaID 473764" src="https://user-images.githubusercontent.com/15368365/149636010-e4b5189b-6fd4-46c3-b5f8-4051c2605f5b.png">

This is the link to the WoRMS entry showing changes have been made but it does not list what they were.

<img width="1347" alt="WoRMS Dentimargo pumila 473764" src="https://user-images.githubusercontent.com/15368365/149636181-048e8e04-6b4f-42b8-9c54-c27eeac0820c.png">

I have deleted the erroneous WoRMS (via Arctos) entry from the taxon page for _Dentimargo pumilus_ and I added a new taxon page for _Dentimargo pumila_ and reloaded the WoRMS (via Arctos) classification.

**Expected behavior**

I would have expected WoRMS to establish a new aphiaID when they modified the taxon name.  

Has anyone else run across this?  I plan to check with other museums using WoRMS and WoRMS editors I know to see if this is common or unusual for WoRMS.

@dustymc  Is it possible to write SQL that finds the WoRMS (via Arctos) taxon terms that don't match the Arctos taxon term.  For example, before I deleted it, here was the WoRMS (via Arctos) entry with _Dentimargo pumila_ in the classification for _Dentimargo pumilus_

<img width="1300" alt="Dentimargo pumilus after refresh of aphiaID 473764" src="https://user-images.githubusercontent.com/15368365/149636228-60c9e80b-280d-45ee-ae36-e395f1ddbcc5.png">

It may not be possible as you would have to refresh the WoRMS (via Arctos) classification before you compared it to the Arctos taxon name to know if there has been a change and refreshing the entire WoRMS (via Arctos) database is probably not feasible.  

Or it may be that our taxon name was misspelled and WoRMS made a fuzzy match.  Is that possible?

Priority:  Hard to know until I learn more about what WoRMS procedures are.  Partly I wanted to alert others using WoRMS (via Arctos) to this issue.  I can't delete the WoRMS (via Arctos) classification from the invalid name when it's being used by another collection, but it means that the same aphiaID and classification is linked to two different names.

**Comment by albenson-usgs** [comment]
The WoRMS team is very responsive when you contact them. The email is info@marinespecies.org.

**Comment by sharpphyl** [comment]
That was my next step.  I'll email them today.  Thanks.

**Comment by dustymc** [comment]
>fuzzy match. Is that possible?

I don't think so, but I suppose I can't 100% rule it out.

> WoRMS (via Arctos) taxon terms that don't match the Arctos taxon term

I don't think there's any value in that, but here are those used by you in which the lowest taxon term doesn't match the taxon name.

```
drop table temp_used_by_dmnsinv;

create table temp_used_by_dmnsinv as select distinct
    taxon_name.taxon_name_id,
    taxon_name.scientific_name,
    taxon_term.classification_id,
    taxon_term.term,
    taxon_term.term_type,
    position_in_classification
from
    collection
    inner join cataloged_item on collection.collection_id=cataloged_item.collection_id
    inner join identification on cataloged_item.collection_object_id=identification.collection_object_id
    inner join identification_taxonomy on identification.identification_id=identification_taxonomy.identification_id
    inner join taxon_name on identification_taxonomy.taxon_name_id=taxon_name.taxon_name_id
    inner join taxon_term on taxon_name.taxon_name_id=taxon_term.taxon_name_id
where
    collection.guid_prefix='DMNS:Inv' and
    taxon_term.source='WoRMS (via Arctos)'
;


create table temp_used_by_dmnsinv2 as select scientific_name,taxon_name_id from temp_used_by_dmnsinv group by scientific_name,taxon_name_id;

alter table temp_used_by_dmnsinv2 add lct varchar;
create index temp_idx_t_u2 on temp_used_by_dmnsinv2(taxon_name_id);
create index temp_idx_t_upc on temp_used_by_dmnsinv(position_in_classification);
create index temp_idx_t_upt on temp_used_by_dmnsinv(taxon_name_id);


CREATE OR REPLACE FUNCTION temp_junk() RETURNS void AS $body$
declare
  r record;
    mtrm varchar;
BEGIN
    for r in (select * from temp_used_by_dmnsinv2 where lct is null ) loop
        select term into mtrm from temp_used_by_dmnsinv where taxon_name_id=r.taxon_name_id and 
        position_in_classification=(
            select max(position_in_classification) from temp_used_by_dmnsinv where taxon_name_id=r.taxon_name_id
        );
        update temp_used_by_dmnsinv2 set lct=mtrm where taxon_name_id=r.taxon_name_id;
    end loop;
end;
$body$
LANGUAGE PLPGSQL
;

select temp_junk() ;


select scientific_name,lct from temp_used_by_dmnsinv2 where scientific_name!=lct order by scientific_name;


         scientific_name         |                  lct                  
---------------------------------+---------------------------------------
 Ampelita lachesis monacha       | Ampelita lachesis var. monacha
 Ampelita lamarei sakalava       | Ampelita lamarei var. sakalava
 Aylacostoma pulcher             | Aylacostoma pulchrum
 Callyspongia aculeata           | Callyspongia (Cladochalina) aculeata
 Cardita incrassata              | Cardita incrassatus
 Cochlostyla valenciennesii      | Cochlostyla valenciennii
 Colobocentrotus atratus         | Colobocentrotus (Podophora) atratus
 Colobostylus bronnii            | Colobostylus
 Diplodon delodontus             | Diplodon delodonta
 Dryocochlias metaformis rustica | Dryocochlias metaformis
 Eclogavena coxeni hesperina     | Eclogavena hesperina hesperina
 Galeodea echinophora adriatiea  | Cassidaria echinophora var. adriatica
 Niso hizensis                   | Niso hizenensis
 Notocochlis gualtieriana        | Notocochlis gualteriana
 Obba papilla kowanensis         | Obba papilla f. konawensis
 Oospira takagii                 | Oospira (Atractophaedusa) takagii
 Opalia morchiana                | Opalia moerchiana
 Plectopylis clathratula         | Plectopylis (Sykesia) clathratula
 Rolleia soluta                  | Rolleia



```

**Comment by sharpphyl** [comment]
Thanks for the list.  Several of these are subgenera which are never going to match because I can't add subgenera to the taxon name.

Several (e.g. _Notocochlis gualtieriana_, _Niso hizensis_, _Opalia morchiana_) were exactly what I needed.  But the WoRMS classification is manually refreshed, the disparity doesn't show up.  I've removed the disappearing taxon name except where another collection is using it, although I can clean up the default Arctos entry for them.  @Jegelewicz  Let's discuss in tomorrow's committee meeting.    That's why _Notocochlis gualtieriana_ is still in the taxon table, plus it's our original ID and would take time to delete from 30 records.

I emailed WoRMS but no answer yet.

**Comment by dustymc** [comment]
Response from WoRMS Data Management Team:

```
The policy is that the name concept behind an AphiaID will never change.

If the taxon concept changes, we will indeed make it unaccepted and so on…

So subtle changes in the name, spelling fixes & authority improvements are allowed.

 

If the name would never change, there would be no need to an identifier, and you could rely on the name string alone.

Doing this would create a massive amount of entries which become unmanageable by humans, very similar to Google or the Global Names Index.
```

FWIW that makes sense to me, and having an identifier also allows them to unambiguously manage homonyms.

A slight clarification of the original message:

* Everything from WoRMS is "classification data" 
* There is nothing at all about classification data which can change a taxon name, nor the taxon name used in identifications.

Identifications are to name-at-preferred-classification, and WoRMS classifications are managed via supplying an AphiaID. I don't see anything in any side of this that can change the *idea* (concept, whatever you want to call it) behind identifications, but obviously letting WoRMS manage the classification data can result in whatever changes they allow, including how the most precise term is spelled.

**Comment by sharpphyl** [comment]
@Jegelewicz  @dustymc 
Please put this issue on the Taxonomy Committee agenda tomorrow.  I agree that it makes sense that WoRMS uses the aphiaID identifier as the stable control.  But we use the taxon name instead of the aphiaID.  If we typed in the aphiaID as the identification and went with whatever came up, there would be no problem, but we type in a taxon name that we think is a match for the aphiaID, but it isn't always and this can cause lots of search issues.

> removed
> 
> Please please please do not.

I'm not deleting the original, now unaccepted, taxon name.  I'm deleting just the WoRMS (via Arctos) classification which no longer matches the taxon name and is not assigned to a (subtly different) taxon name.  I have a list of them if you want them back in but they are all mismatches.

**Comment by sharpphyl** [comment]
The only strategy to deal with this that I can think of is to regularly refresh a few families so that every family is refreshed at least once a year or more frequently.  Then, if Dusty can share the SQL to find the mismatches used in the collection, we can clean them up.  I don't know what the other collections using WoRMS (via Arctos) will want to do, if anything.

**Comment by Jegelewicz** [comment]
> If the name would never change, there would be no need to an identifier, and you could rely on the name string alone.
> 
> Doing this would create a massive amount of entries which become unmanageable by humans, very similar to Google or the Global Names Index.

So why is it that we only rely on the name?

**Comment by sharpphyl** [comment]
@mvzhuang @wellerjes @lin-fred @Jegelewicz 

Be aware of this issue with WoRMS (via Arctos) taxon names.  We researched several examples such as _Dentimargo pumilus_ which was changed to _Dentimargo pumila_.  We found that the original name was _Marginella pumila_ and when the genus was changed the specific epithet was incorrectly changed to _pumilus_.  WoRMS has corrected that to _pumila_ with no change to aphiaID.  _Dentimargo pumilus_ disappeared from their database even though it was still in the Arctos taxon table.  When I refreshed the WoRMS (via Arctos) entry, it created an inconsistency between our taxon name and name in the WoRMS (via Arctos) classification.

I don't think this is a huge issue, but it's something you should be aware of depending on how your collection is organized and your use of the WoRMS (via Arctos) database.  Where I found these (see Dusty's SQL results above), I have created the new taxon name and attached it to the former aphiaID and left the inaccurate name our database with an Arctos classification and metadata, so you should still be able to get the classification for your records.  You may want to run Dusty's SQL for your collection.  You can ignore the subgenera which will never match.  

Examples:
[Notocochlis gualtieriana](https://arctos.database.museum/name/Notocochlis%20gualtieriana) corrected to _Notocochlis gualteriana_ 
[Opalia morchiana](https://arctos.database.museum/name/Opalia%20morchiana) corrected to _Opalia moerchiana_
[Niso hizensis](https://arctos.database.museum/name/Niso%20hizensis) corrected to _Niso hizenensis_.
[Dentimargo pumilus](https://arctos.database.museum/name/Dentimargo%20pumilus) corrected to _Dentimargo pumila_
[Aylacostoma pulcher](https://arctos.database.museum/name/Aylacostoma%20pulcher) corrected to _Aylacostoma pulchrum_

There may be more.  These are just ones that we were using as an accepted identification.

**Comment by Jegelewicz** [comment]
Sigh - taxonomy troubles..... even the taxonomists can't get stuff right! It is way too complicated.

**Comment by sharpphyl** [comment]
@Jegelewicz 

Shall we add Dusty's SQL to our cheat sheet?  I'd like to occasionally run it.  Thanks.

**Comment by lin-fred** [comment]
I'm updating the ones that you listed @sharpphyl 
Is there anything else I should do? Does the SQL need be run for NMMNHS as well?

**Comment by sharpphyl** [comment]
@lin-fred  I would suggest running the SQL for NMMNHS at least once to see if anything pops up after your update.  I plan to run it a few times a year just to check for more changes of this type.

**Comment by dustymc** [comment]
FYI that's not SQL and won't run in the UI - just let me know if you need a report and I'll run it.

**Comment by sharpphyl** [comment]
@dustymc   OK.  Will let you know.

**Comment by dustymc** [comment]
```

           scientific_name           |                  lct                   
-------------------------------------+----------------------------------------
 Adelomelon brasiliana               | Adelomelon brasilianum
 Alia gouldi                         | Alia gouldii
 Ampelita lachesis monacha           | Ampelita lachesis var. monacha
 Ampelita lamarei sakalava           | Ampelita lamarei var. sakalava
 Ampelita omphalolodes               | Ampelita omphalodes
 Amphidromus poecilochorus           | Amphidromus poecilochrous
 Anodontites patagonicus             | Anodontites patagonica
 Anostoma octodentata                | Anostoma octodentatum
 Aporrhais serresianus               | Aporrhais serresiana
 Argonauta nodosus                   | Argonauta nodosa
 Aulopoma itieri                     | Aulopoma itierii
 Babelomurex tectumsinensis          | Babelomurex tectumsinense
 Bistolida kieneri sneideri          | Bistolida kieneri schneideri
 Bocourtia revinctus                 | Bocourtia revincta
 Bradybaena halpozona                | Bradybaena haplozona
 Caecum farcimen                     | Caecum (Fartulum) farcimen
 Callyspongia aculeata               | Callyspongia (Cladochalina) aculeata
 Campeloma limum                     | Campeloma lima
 Ceratostoma burnetti                | Ceratostoma burnettii
 Clavus nodifera                     | Clavus nodiferus
 Colobocentrotus atratus             | Colobocentrotus (Podophora) atratus
 Colobostylus bronnii                | Colobostylus
 Conus sibogae                       | Conus mucronatus var. sibogae
 Crassispira mesoleuca               | Crassispira (Crassispirella) mesoleuca
 Dentimargo neglectus                | Dentimargo neglecta
 Dentimargo reductus                 | Dentimargo reducta
 Dentimitrella                       | Mitrella (Dentimitrella)
 Doxander campbelli                  | Doxander campbellii
 Dryocochlias metaformis rustica     | Dryocochlias metaformis
 Echineulima toki                    | Echineulima tokii
 Eclogavena coxeni hesperina         | Eclogavena hesperina hesperina
 Fruticicola transbaicalica sayanica | Fruticicola transbaicalia sayanica
 Galeodea echinophora adriatiea      | Cassidaria echinophora var. adriatica
 Helix hispidula                     | Carocolla hispidula
 Latiaxis pagodus                    | Latiaxis (Babelomurex) pagodus
 Limicolaria senaariensis            | Limicolaria sennaariensis
 Megalobulimus chionostomus          | Megalobulimus chionostoma
 Notocochlis gualtieriana            | Notocochlis gualteriana
 Obba papilla kowanensis             | Obba papilla f. konawensis
 Oospira takagii                     | Oospira (Atractophaedusa) takagii
 Ostraea angasi                      | Ostrea angasi
 Pecten radula                       | Pecten (Comptopallium) radula
 Planorbis campanulata               | Planorbis campanulatus
 Plectopylis clathratula             | Plectopylis (Sykesia) clathratula
 Pleurostemma geminata               | Pleurostemma geminata geminata
 Rissoa scopulorum                   | Rissoa (Cingula) scopulorum
 Rolleia soluta                      | Rolleia
 Scholvienia bifasciatus             | Scholvienia bifasciata
 Solen krusensterni                  | Solen krusensternii
 Staphylaea ruvaya                   | Staphylaea (Purperosa) ruvaya
 Strombus campbelli                  | Strombus campbellii
 Synapterpes auratus                 | Synapterpes (Chryserpes) auratus
 Tetrentodon gracillima              | Tetrentodon gracillimus
 Tetrentodon insuflata               | Tetrentodon insuflatus
 Thaumastus achilles                 | Thaumastus (Thaumastus) achilles
 Venerupis philippinarum             | Venerupis (Ruditapes) philippinarum
(56 rows)
```

**Comment by sharpphyl** [comment]
Any idea what might cause a refresh request to not go through?  Trying to clean up these taxonomic changes.  I've never seen this before.  It's probably a glitch in WoRMS but...

<img width="720" alt="Screen Shot 2022-09-23 at 9 49 49 AM" src="https://user-images.githubusercontent.com/15368365/192001401-e0c40b08-a30a-47fb-aa3a-0d32236bb62f.png">

WoRMS page is there

<img width="759" alt="Screen Shot 2022-09-23 at 9 50 26 AM" src="https://user-images.githubusercontent.com/15368365/192001527-9d7d4c26-6184-4553-b5f4-afea4c2e5e87.png">

I can try again tomorrow to refresh if it looks like a WoRMS issue.

**Comment by dustymc** [comment]
Link please...

**Comment by sharpphyl** [comment]
https://arctos.database.museum/name/Dentimargo%20reducta#WoRMSviaArctos

**Comment by sharpphyl** [comment]
Several other refreshes worked just fine this morning so I'm thinking it may be a bug at WoRMS instead of us.

**Comment by dustymc** [comment]
Thanks.

If you click the aphiaid you get the URL

```
https://www.marinespecies.org/aphia.php?p=taxdetails&id= 420138
```

Note the gap - your browser probably doesn't care (and might encode the character), but their API does and they don't have a {space}42.... identifier, so the request is failing.

Normally that would be disallowed by the check constraints, but I have to take whatever GlobalNames (and worms and lots of others) provide so there are no constraints on classifications.

I edited and removed the space (or whatever it was) and it happily refreshed.

**Comment by sharpphyl** [comment]
Weird.  I see the gap now, but would I be able to see that problem when I try to refresh or would I need to have you do the refresh?

**Comment by dustymc** [comment]
The link

<img width="69" alt="Screen Shot 2022-09-23 at 9 52 35 AM" src="https://user-images.githubusercontent.com/5720791/192012433-157c00cb-5360-4a71-b980-d311f000075e.png">

should make it visible. Refresh just fails with an unrecognized identifier. I suppose it could fail in other ways, but I don't think I've even seen it do so - malformed IDs are a good place to start that investigation, if such becomes necessary again.

**Comment by sharpphyl** [comment]
OK.  Thanks.

**Comment by genevieve-anderegg** [comment]
> FYI that's not SQL and won't run in the UI - just let me know if you need a report and I'll run it.

@dustymc Could you please run the above report for DMNS:Inv? It's that time of year! Thanks!

**Comment by dustymc** [comment]
```

           scientific_name           |                   lct                   
-------------------------------------+-----------------------------------------
 Ancistrolepis grammatus             | Ancistrolepis grammata
 Archelix lucasi                     | Archelix lucasii
 Bocourtia aequatorius               | Bocourtia aequatoria
 Buccinum kinukatsugai               | Buccinum kinukatsugi
 Bulimulus hyltonscottae             | Bulimulus (Scansicochlea) hyltonscottae
 Bulimulus saeronius                 | Bulimulus (Naesiotus) saeronius
 Bulimulus willineri                 | Bulimulus (Paracochlea) willineri
 Caecum farcimen                     | Caecum (Fartulum) farcimen
 Calliostoma shinagawaense           | Calliostoma shinagawense
 Callyspongia aculeata               | Callyspongia (Cladochalina) aculeata
 Canarium microurceus                | Canarium microurceum
 Cerithium adansonii                 | Cerithium adansoni
 Chilostoma squamatinum              | Chilostoma (Chilostoma) squamatinum
 Chondrothyra crassa                 | Chondrothyra (Plicathyra) crassa
 Clanculus bathyraphe                | Clanculus bathyrhaphe
 Cochlostoma hidalgoi                | Cochlostoma (Obscurella) hidalgoi
 Cochlostoma pinianum                | Cochlostoma (Auritus) pinianum
 Colobocentrotus atratus             | Colobocentrotus (Podophora) atratus
 Coralliophila abbreviata            | Purpura abbreviata
 Crassispira mesoleuca               | Crassispira (Crassispirella) mesoleuca
 Cypraea depressa                    | Cypraea arabica depressa
 Dentimitrella                       | Mitrella (Dentimitrella)
 Doxander vittatus apicatus          | Doxander operosus apicatus
 Euvola laurenti                     | Euvola laurentii
 Galba diaphana                      | Galba (Pectinidens) diaphana
 Geomitra delphinula                 | Geomitra (Craspedaria) delphinula
 Helicella apicina                   | Helicella (Xerotricha) apicina
 Helicella conspurcata               | Helicella (Xerotricha) conspurcata
 Helix virgata leucozona             | Helix virgata var. leucozona
 Isognomon incisum                   | Isognomon incisus
 Labyrinthus uncigerus chiriquiensis | Labyrinthus uncigerus chiriquensis
 Latiaxis pagodus                    | Latiaxis (Babelomurex) pagodus
 Leonia mamillaris                   | Leonia mammillaris
 Lepidochitona lirulatus             | Lepidochitona (Dendrochiton) lirulata
 Linatella cingulatum                | Linatella cingulata
 Margarites rudis                    | Margarites (Pupillaria) rudis
 Mitrella burchardi                  | Mitrella burchardti
 Murex sallasi                       | Murex (Murex) recurvirostris sallasi
 Mytilus recurvum                    | Mytilus recurvus
 Oospira takagii                     | Oospira (Atractophaedusa) takagii
 Opisthostoma mirabile               | Opisthostoma busauense
 Oxychilus glaber                    | Oxychilus (Morlina) glaber
 Pecten cumingi                      | Pecten cumingii
 Pecten perulus                      | Pecten (Pecten) perulus
 Pecten radula                       | Pecten (Comptopallium) radula
 Pecten raveneli                     | Pecten (Pecten) raveneli
 Plectopylis clathratula             | Plectopylis (Sykesia) clathratula
 Primovula helenae                   | Primovula (Primovula) heleneae
 Pyramidella adamsi                  | Obeliscus adamsii
 Reinia sieboldtii                   | Reinia sieboldti
 Rissoa scopulorum                   | Rissoa (Cingula) scopulorum
 Siphonaria palmata                  | Siphonaria lecanium var. palmata
 Siratus consuela                    | Siratus consuelae
 Staphylaea ruvaya                   | Staphylaea (Purperosa) ruvaya
 Subulophora peasi                   | Subulophora peasei
 Synapterpes auratus                 | Synapterpes (Chryserpes) auratus
 Systrophia zeteki                   | Systrophia (Systrophiella) zeteki
 Terebra panamensis                  | Terebra (Strioterebrum) panamensis
 Thaumastus achilles                 | Thaumastus (Thaumastus) achilles
 Thersites richmondianus             | Thersites richmondiana
 Trochoidea gharlapsi                | Trochoidea (Xeroclausa) gharlapsi
 Venerupis philippinarum             | Venerupis (Ruditapes) philippinarum
 Vitularia sandwichensis             | Vitularia sandwicensis
```

**Comment by Jegelewicz** [comment]
UGH Taxonomy.....

**Comment by genevieve-anderegg** [comment]
Thank you so much Dusty!

**Comment by sharpphyl** [comment]
@lin-fred 

I see that you are using a few of these names with spelling changes so you may want to monitor this issue.  For example, see _Siratus consuela_ which is now _Siratus consuelae_.
