### ISSUE TITLE
Bug on Clear Form on Collecting Event Search Screen

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#4269]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
When I click "Clear Form" on the Collecting Event Search screen, it adds a locality ID so unless the Event uses that locality, I get no results.

**Expected behavior**
It should totally clear the form

**Screenshots**

Before clicking Clear Form
 
<img width="700" alt="Before clicking Clear Form" src="https://user-images.githubusercontent.com/15368365/149671654-9b04b3b2-edb9-44cf-a0ed-cae6a4ad91e3.png">

After clicking Clear Form

<img width="733" alt="After clicking Clear Form" src="https://user-images.githubusercontent.com/15368365/149671685-9511daad-7094-4c86-b912-5043b96e29fa.png">

**Desktop (please complete the following information):**
Chrome on Mac

**Comment by sharpphyl** [comment]
Now it's not happening, so I'll close this and reopen if it continues.

**Comment by sharpphyl** [comment]
I figured out when it happens.  If I get to a list of collecting events by clicking on "Find All Collecting Events" within a locality, then when I try to clear the form, the locality ID doesn't go away.   Let me know if you need another complete example.


<img width="368" alt="Screen Shot 2022-01-19 at 12 45 09 PM" src="https://user-images.githubusercontent.com/15368365/150211617-2514e278-6c6b-4e0e-a143-87d1fecdb99f.png">

**Comment by dustymc** [comment]
That is the expected behavior - it's resetting the form to the initial state, which in this case is limited to children of a locality. 

I'm not sure there's any place that completely makes sense here, so the form should now be stripping all parameters with reset. I can't break it, but that form is used in a lot of places (all place-type searches) and more testing would be very appreciated. 

Calling this next release.

**Comment by sharpphyl** [comment]
I use it a lot so I'll let you know if it continues.  Do you have a date for the next release?

**Comment by dustymc** [comment]
>date for the next release

Tuesday-ish, unless I get distracted.
