### ISSUE TITLE
Look up specimen record by collector number or other id for adding specimen citatations

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#4273]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
Botanists often cite by collector number and institution instead of institutional catalog number. It's an extra step to lookup the catalog number through search and then add that number in by collector number

**Describe what you're trying to accomplish** 
Easily cite specimens from publications for herbarium related collections

**Describe the solution you'd like**
Have a "pull record" function based on other ID's similar to in data entry

**Describe alternatives you've considered**
continue to run searches based on collector and collector number and get catalog number to create citation from there.

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by dustymc** [comment]
Can you just load citations by (other_id_type,other_id_number) instead of GUID?

**Comment by dustymc** [comment]
Happy?
