### ISSUE TITLE
IP address is blocked

### ISSUE THREAD

**Issue by lin-fred** [ArctosDB/arctos#4276]
From Twitter:

>Matthew Shawkey
>@mdshawkey
>Hi @arctosdb I keep getting.a message saying my IP address is blocked form accessing data, whether I use my home or work (VPN) >IP. Any idea >why? Thanks!

How should I respond to this one on Twitter @dustymc 

Do I lead them to this Github issue? I can also reply to the tweet or try a DM to ask for any further information that you need.

**Comment by dustymc** [comment]
Minimally I need the blocked IP. I prefer/watch GitHub, but can deal with whatever works for them.

**Comment by lin-fred** [comment]
Does anyone in Github have permission to the general arctos repo, or do they also need to be invited to use this one?

**Comment by lin-fred** [comment]
I've asked them to email me, and then I'll add you into the email convo. Probably should do it over email as I don't know how much of their information they'd want to be public.

**Comment by Jegelewicz** [comment]
They can also use the report a bug or request support thingee which creates an issue?

![image](https://user-images.githubusercontent.com/5725767/150398088-d164161d-4ff4-4601-a9e7-feead9a5cb92.png)

**Comment by lin-fred** [comment]
Thanks for linking that one,

Im assuming the one on the arctosdb page is also ok?

![image](https://user-images.githubusercontent.com/19802479/150398488-2e50f001-0f71-491e-ac78-2835dbfff3e1.png)

**Comment by lin-fred** [comment]
> They can also use the report a bug or request support thingee which creates an issue?
> 
> ![image](https://user-images.githubusercontent.com/5725767/150398088-d164161d-4ff4-4601-a9e7-feead9a5cb92.png)

Im assuming he might not be able to get to this one as he is getting blocked right? So the arctosdb one would be better

**Comment by Jegelewicz** [comment]
DOH yeah I think they do the same thing. Try it out and make your request humorous. I really need some humor.

**Comment by lin-fred** [comment]
> DOH yeah I think they do the same thing. Try it out and make your request humorous. I really need some humor.

haha the pressure, ill try!

**Comment by lin-fred** [comment]
Ok at this point I've sent them a tweet to either email the membership email or the contact email
