### ISSUE TITLE
Bulk edit container not autoloading

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4278]
**Describe the bug**
Added stuff to https://arctos.database.museum/tools/bulkEditContainer.cfm

marked to load

it's still there marked as autoload

**To Reproduce**
See above

**Expected behavior**
It's possible that I am just being impatient but it doesn't look like Vicky's are loading either? Nothing in the tool has changed since I loaded my records about 15 minutes ago.

**Screenshots**
![image](https://user-images.githubusercontent.com/5725767/150417222-544ac967-a2c1-42ed-8434-42fc5f0d17bd.png)

**Data**
[container_edit.csv](https://github.com/ArctosDB/arctos/files/7908319/container_edit.csv)

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by dustymc** [comment]
<img width="385" alt="Screen Shot 2022-01-20 at 12 39 48 PM" src="https://user-images.githubusercontent.com/5720791/150418605-0e24e95f-e67a-4e2d-b055-1b883ccbb800.png">

**Comment by Jegelewicz** [comment]
I guess this kinda brings up a question. How long is a reasonable wait for any of these things? And can we do anything about it?

When a workflow gets shut down and I have to leave and go work on something else because 60 container edits won't load that seems like a real drag. It also means my work gets disjointed and things don't get done.

That's my complaining for today (sorry).

**Comment by campmlc** [comment]
Agree.

**Comment by campmlc** [comment]
No one knows to go there, and the display is not clearly understandable
even if you do. Can we integrate a user friendly time feature on the
loaders? What do we need from TACC to eliminate these delays?

**Comment by Jegelewicz** [comment]
It still hasn't loaded - I guess parts go first? Not sure but this seems REALLY SLOW. It's been 3 hours.

**Comment by dustymc** [comment]
I adjusted the throttle for the parts loader (next release), I'll try to catch it while it's loading containers and adjust that as well.
