### ISSUE TITLE
agent help request: R. Rausch

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4279]
https://arctos.database.museum/agents.cfm?agent_id=21284731

The UCM stuff looks a lot like https://arctos.database.museum/agents.cfm?agent_id=2570 @ebraker 

The leps all look a bit suspicious, but ?? @DerekSikes @mlbowser 

Can this be merged with or distinguished from the Roberts before the (probable) mess grows?

**Comment by ebraker** [comment]
Fixed UCM agent (bad duplicate)
