### ISSUE TITLE
Changing Locality on Multiple Collecting Events

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#4280]
I am looking at the instructions on the handbook page: https://handbook.arctosdb.org/how_to/How-to-Reassign-Specimens-to-Another-Locality.html and it states that "The first half of this tutorial will teach you how to reassign specimens to a new locality, if your specimen(s) is/are assigned to one collecting event only."

Is there a way to change multiple collecting events at once? I'm trying to georeference several specimens under different collecting events that all have the same general location (Deerfield, Illinois).

I have some instructions written by a predecessor referring to a way to move multiple collecting events to a new locality (see step 5 in the attached document); I've tried following these directions, but I'm not seeing the same screens/options reflected in this tutorial.
[New Locality ID Tutorial.docx](https://github.com/ArctosDB/arctos/files/7916446/New.Locality.ID.Tutorial.docx)
 
Has the process changed? Or is this tutorial no longer valid?

Thanks for your help!

**Comment by dustymc** [comment]
I don't think that's possible at the moment.

I think the manage-bulk form (from specimen search results) only works with simpler data, but I've kept it around in case anyone has clever ideas to resurrect parts of it.

How would you like to do this? Seems like a useful tool/common task. Maybe a 'change locality for all found events' button on https://arctos.database.museum/place.cfm? (And that needs to accept a list of eventIDs, I'll make that change now.)

In the meantime if you'll send me CSV with enough information to figure out what you're trying to do (event_id, desired_locality_id would do it), I can SQL update for you.

**Comment by wellerjes** [comment]
Thanks for the update! We are just starting to georeference our botany collection, which was bulkloaded last year, so I'm not sure at the moment how many records this would impact (and don't have a CSV file readily available yet). We have an intern starting within the next week or so who will be working on this more regularly, so we are updating our workflow tutorials for her.

If we could add "Change Locality for all Found Events" / "Move These Collecting Events to a New Locality" option, as seen in section 5-7 of the "New Locality ID Tutorial" document above, that would be incredibly useful!

Thanks!

**Comment by dustymc** [comment]
Feel free to ask for bulk updates of any kind at any time - I don't mind, and that's the sort of thing that leads to better tools in Arctos.

Mass-moving events **from events** does not seem problematic to me. Mass-moving events **from catalog records** (where you may be seeing only the one accepted and not the 547 previous determinations, or any other flavor of complexity that mostly didn't exist when that form was developed) no longer seems like a viable option, but as above the old form is hanging around and can be resurrected if there's some use case which can be supported. (Manage/CollectingEvent already leads to the event form, where any potential complexity is flattened out and should be obvious.)

Would that work for you?

**Comment by wellerjes** [comment]
> Mass-moving events from catalog records (where you may be seeing only the one accepted and not the 547 previous determinations, or any other flavor of complexity that mostly didn't exist when that form was developed)

I'm not sure I understand. This sounds like it applies to taxonomy more than georeferencing. Can you please provide more detail?

> the old form is hanging around and can be resurrected if there's some use case which can be supported

The instructions I'm working from with the screen shots were created in 2018 by previous assistant collections manager Anna Chinn, if that helps with determining if the old form is still around.

![Screenshot 2022-01-22 102222](https://user-images.githubusercontent.com/93737929/150646928-441dcda5-1e55-4305-86e9-bf627d26369c.jpg)
For example: There are 23 records associated with the locality Waukegan Flats; 19 are from CHAS collections, but there are only 12 with this specific collecting event. 

![Screenshot 2022-01-22 102756](https://user-images.githubusercontent.com/93737929/150647076-e5a202a2-b436-4e02-b436-9c54494e579f.jpg)
Going into the collecting event and editing the locality will only impact 12 specimens, but since there are 7 others from our collection with the same locality, it would be easier/less time consuming to change them all at once by cloning the locality to separate it from the MVZ specimens, then applying the new locality to the 19 relevant records.

I got here by pulling up the 19 specimens "=waukegan flats" in specific locality for CHAS:Herp, then clicking on the Manage dropdown - "Related" - "Collecting Event"
![Screenshot 2022-01-22 103209](https://user-images.githubusercontent.com/93737929/150647396-856ac111-5b51-405a-9acd-141d330bfd72.jpg)
Is there a way to batch edit from from here? Without downloading the record information into a CSV, changing the LOCALITY_ID, and then re-uploading the CSV? I downloaded a CSV to see if this was feasible, but it looks like there's not enough information in the download to re-associate the new locality with the original records -- meaning, the CSV does not contain the catalog numbers. If there's nothing to differentiate which records the new locality is being applied to, I'm worried that it may overwrite the entire location, impacting records from other institutions that use that shared locality.

![Screenshot 2022-01-22 104521](https://user-images.githubusercontent.com/93737929/150647797-3494ae4b-3601-485b-9f56-f69f254cb86c.jpg)
![Screenshot 2022-01-22 104547](https://user-images.githubusercontent.com/93737929/150647800-95350d4b-22b6-46a7-b6a6-b76051593628.jpg)
(there are other columns, but these are the only ones that populate)

Please let me know if you need any additional information about how we're trying to process this. Thanks for your help!

**Comment by dustymc** [comment]
>more detail

https://arctos.database.museum/guid/CHAS:Bird:4271 has two Events, one "original" and one georeferenced. You probably only want to change one of them. Anything starting with catalog records is probably going to bring them both along; you need another filter, tool, path, something.

And my recommendation is always to not change them at all, but rather to add, like has been done here. Some of the changes are likely to be wrong, having the history makes that a lot easier to understand and fix. That's certainly not the only possible view, we can work out forms to just change, but....

>re-uploading the CSV...does not contain the catalog numbers

Suggests the specimen-event bulkloader was used?? (That approach also avoids any possibility of crossing any boundaries into other collections, it's all additive and works only against the catalog records you specify.)

>clicking on the Manage dropdown - "Related" - "Collecting Event"....Is there a way to batch edit from from here? 

That's what I am (or was, if loading specimen events is a better path??)  proposing - some ability to do whatever you need to do from place.cfm - replace locality_ids, link to another form that has more filters or allows some kind of mass-editing, or ?????

**Comment by wellerjes** [comment]
> https://arctos.database.museum/guid/CHAS:Bird:4271 has two Events, one "original" and one georeferenced.

Thank you, this makes more sense. We definitely want to ensure the history of the locality is saved. 

> That's what I am (or was, if loading specimen events is a better path??) proposing - some ability to do whatever you need to do from place.cfm - replace locality_ids, link to another form that has more filters or allows some kind of mass-editing, or ?????

With this streamlining, as long as the locality does not change and can still be cloned and separated from other institutions, the mass editing is something we are interested in, especially for specimens that have broad localities (just a city name) or no locality at all (so we can make a note in the locality remarks that this specimen cannot be georeferenced due to lack of information).

I can pull together more examples; one that I just found is locality 11439541:
![image](https://user-images.githubusercontent.com/93737929/151027755-4eb9dccd-7a2d-40a9-bd01-6c2f4f67c08a.png)

**Comment by dustymc** [comment]
>still be cloned and separated from other institutions

We need better documentation, @ArctosDB/geo-group @ArctosDB/arctos-working-group-officers . My take (reflected in the structure of the data model) is and always has been that those collections would welcome better data; those that don't have named, segregated localities. (And the history model sends them notifications when something's changed and makes reversion/splitting easy when necessary.) Just georeferencing saves work and adds value; yay The Community!

>no locality at all 

Also for the documentation: consider the scope/scale of Arctos. "North America" is vastly more precise than nothing at all, and will be useful for many users. (And https://arctos.database.museum/collection/UNM:MET exists - even the assumption that "nothing"=="somewhere on Earth" may not scale very well.)

> locality 11439541

If https://github.com/ArctosDB/arctos/issues/4289 was enacted, I might suggest that those data already exist in the geography and could be easily (maybe even automagically) pulled into any geography-level localities.

https://github.com/ArctosDB/arctos/issues/4259 would provide a means to be able to access the geography-level data (datatype ``geography``) as point-radius.

>mass editing is something we are interested in

Going next task for this.

**Comment by dustymc** [comment]
Next release has a new button from event detail, however one gets there:

<img width="578" alt="Screen Shot 2022-02-04 at 1 27 33 PM" src="https://user-images.githubusercontent.com/5720791/152605481-c0c92746-1479-499b-903a-4480f76adb29.png">

which leads to a new form with event and usage data


<img width="1704" alt="Screen Shot 2022-02-04 at 1 28 57 PM" src="https://user-images.githubusercontent.com/5720791/152605602-f7e65020-5f25-40df-884c-f387e41de6dc.png">

The form has the ability to remove rows, and then to change event-stuff for whatever's left. 

<img width="1703" alt="Screen Shot 2022-02-04 at 1 30 03 PM" src="https://user-images.githubusercontent.com/5720791/152605713-0c59d541-02e1-4047-a21f-4df8af9ffb11.png">

I was able to ~~make a huge mess~~ _carefully update data across lots of events_ with just a click!
