### ISSUE TITLE
Add wildcard to Barcode search

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4281]
I'd like to be able to locate all barcodes that start with a given string. Can we add the ability to use the % wildcard in the barcode search field?

https://arctos.database.museum/findContainer.cfm

![image](https://user-images.githubusercontent.com/5725767/150613333-3a6fcb18-0b8d-4cd1-bf59-b00ff01d0046.png)

**Comment by Jegelewicz** [comment]
@dustymc would this be a pain?

**Comment by dustymc** [comment]
I don't think it's painful, it's slightly dangerous, the current architecture is fairly resilient, not sure how any of that balances out.

**Comment by Jegelewicz** [comment]
> slightly dangerous

As in my browser will time out or as in it will do something bad to Arctos?

**Comment by dustymc** [comment]
Tabling as a security concern. I don't *think* partial-match containers can melt the database, but they can absolutely kill the front end or any browser.
