### ISSUE TITLE
Bug - Geolocate locality 

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#4282]
Transfer of Issue 134 (https://github.com/ArctosDB/newsletter/issues/134) from the Newsletter Repo to the Arctos Repo. 
Can anyone help @sharpphyl out with the below problem?

When I save a geolocated locality I get this error message.

<img width="1613" alt="Screen Shot 2022-01-21 at 9 34 14 AM" src="https://user-images.githubusercontent.com/15368365/150578360-6e3e1e7f-17ee-4bec-91ca-ce6c3f9c3e11.png">

If I remove the comment in the Geolocate Polygon field, the error message goes away and it saves my geolocated coordinates

<img width="982" alt="Screen Shot 2022-01-21 at 9 34 04 AM" src="https://user-images.githubusercontent.com/15368365/150578395-3e338f55-c9a0-47d8-a78f-5ead2fcb9cbc.png">

Is this something new and should I change my procedures?

**Comment by sharpphyl** [comment]
I get the same error message in FireFox as Chrome.  When I go back to the locality screen and save a second time, the error message doesn't come up, but all the coordinate data from geolocate disappears and nothing is saved.  I have to remove "Unavailable" in the Geolocate Polygon field before I save to keep the coordinates.

I am not clicking on "create polygon."  I'm using the geolocate green pin and adjusting location (if needed) and error radius.  

I've checked all the documentation and tutorials and they don't mention the need to erase "Unavailable" as it's a fairly recent issue.  It's easy enough to do if it's supposed to work this way but it seems like a bug.

**Comment by dustymc** [comment]
I have to turn that on at geolocate:

<img width="438" alt="Screen Shot 2022-01-24 at 8 20 04 AM" src="https://user-images.githubusercontent.com/5720791/150821890-b1f77a38-2abc-411c-8fd2-479dcf60e3f2.png">
<img width="490" alt="Screen Shot 2022-01-24 at 8 20 10 AM" src="https://user-images.githubusercontent.com/5720791/150821910-6314f8af-1117-41d0-b4c9-771d84151652.png">

I don't think that's new, although having a place for the polygon data is relatively recent.

Next release will strip out "Unavailable" before trying to convert.
