### ISSUE TITLE
Collecting event begin and end date corrections

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4284]
@dustymc Can you use the attached to change the begin and ended dates for the associated collecting events? We used the trip dates instead of the more specific actual date of collection for each event.

Also, wondering why these things haven't merged? Many of them are duplicates and I would have expected them to merge by now.

Let me know if this won't work and what I need to get to make it work if it won't. Thanks!
[ALMNH_Inv_date_fixes.csv](https://github.com/ArctosDB/arctos/files/7919202/ALMNH_Inv_date_fixes.csv)

**Comment by dustymc** [comment]
There are invalid dates - 00 as day, at least.

**Comment by Jegelewicz** [comment]
Well, not sure what's going on? Here is what I see

![image](https://user-images.githubusercontent.com/5725767/150835590-0b12a0a0-39f8-443d-aee9-a4d6c6d5fc6a.png)

![image](https://user-images.githubusercontent.com/5725767/150836258-24e7e8fe-f08b-42ad-9f87-6ec99389f238.png)

Try again?

[ALMNH_Inv_date_fixes.csv](https://github.com/ArctosDB/arctos/files/7927681/ALMNH_Inv_date_fixes.csv)

**Comment by dustymc** [comment]
<img width="316" alt="Screen Shot 2022-01-24 at 9 46 52 AM" src="https://user-images.githubusercontent.com/5720791/150836439-a4831676-152a-4d21-8453-984ddea13061.png">

**Comment by Jegelewicz** [comment]
Sheesh, doh. Try now.

[ALMNH_Inv_date_fixes.csv](https://github.com/ArctosDB/arctos/files/7928122/ALMNH_Inv_date_fixes.csv)

**Comment by dustymc** [comment]
done
