### ISSUE TITLE
Arctos allows positions to be created within a cryovial

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4287]
Problem: I had a student accidentally create a freezer box as a cryovial, and then proceed to create 100 positions within it and scan cryovials inside. 
I can't reverse this and turn the cryovial into a freezer box because I get the error message below. Perhaps we need an error message or at least a warning BEFORE doing some irreversible action in Arctos, rather than after the fact?
See "cryovials" DGR11544 and DGR11550.  Request DBA assistance to convert these into the freezer boxes they actually are so we can scan them into their correct position in the freezer rack.
Priority: High. Risk loss of data pending correction.

An error occurred while processing this page!
Message: ERROR: FAIL: Changing position parameters of used containers is not allowed. Where: PL/pgSQL function updatecontainer(bigint,bigint,character varying,character varying,character varying,character varying,character varying,double precision,double precision,double precision,bigint,bigint,character varying,character varying,character varying) line 54 at RAISE
Detail: Parameter types passed (15): CF_SQL_INTEGER, CF_SQL_INTEGER, CF_SQL_VARCHAR, CF_SQL_VARCHAR, CF_SQL_VARCHAR, CF_SQL_VARCHAR, CF_SQL_VARCHAR, CF_SQL_DOUBLE, CF_SQL_DOUBLE, CF_SQL_DOUBLE, CF_SQL_INTEGER, CF_SQL_INTEGER, CF_SQL_VARCHAR, CF_SQL_VARCHAR, CF_SQL_VARCHAR
Check the Arctos Handbook for more information on errors.
This message has been logged as F466FFDB-0C8B-4A3B-AAC60043DE0646FD Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue.

**Comment by Jegelewicz** [comment]
HMMMM I thought it was impossible to put a container into a container of the same type? (No rooms in rooms?) But just adding positions lets you get around the rule?

**Comment by dustymc** [comment]
Updated.

If some rule is being proposed, it should be somehow incorporated into https://github.com/ArctosDB/arctos/issues/3632

**Comment by campmlc** [comment]
@dustymc can you check to see if there are any other cryovials with positions in MSB or elsewhere?

**Comment by dustymc** [comment]
arctosprod@arctos>> select container_type,count(*) from container where number_rows is not null group by container_type order by container_type;
 container_type  | count 
-----------------+-------
 bay             |     3
 box             |   107
 cabinet         |    78
 column          |     1
 container label |     3
 cryovial        |     1
 freezer         |    24
 freezer box     | 14314
 freezer rack    |  1205
 jar             |     2
 shelf           |     1
 slide box       |   502
 specimen label  |     2
(13 rows)

**Comment by campmlc** [comment]
These all have positions? Can we get the barcodes if the cryovial and labels with positions?

**Comment by dustymc** [comment]
I don't know if they do or not, but they're set up for it.

arctosprod@arctos>> select container_id,container_type,barcode from container where number_rows is not null and container_type in 
arctos-> ('cryovial','specimen label','container label','jar') order by container_type,barcode;
 container_id | container_type  | barcode  
--------------+-----------------+----------
     14841938 | container label | DGR10442
     18188682 | container label | DGR17965
     14851274 | container label | DGR19825
     21157608 | cryovial        | DGR22826
     21319792 | jar             | JAR8000H
     21314099 | jar             | JAR8001H
     16335710 | specimen label  | NMU13608
     16335711 | specimen label  | NMU13609

**Comment by campmlc** [comment]
Looks like we can no longer create positions in cryovials and container labels, which is great. But it also looks like we can no longer use the create positions tools in Edit Container to create any positions? Tried to create positions in DGR17965 (which is now a freezer box) and nothing happened. 
?

**Comment by dustymc** [comment]
>can no longer create positions in cryovials 

Sure you can.

>ried to create positions in DGR17965 (which is now a freezer box) and nothing happened.

I need more information - a screenshot and link of every step would be ideal.

**Comment by dustymc** [comment]
>nothing changed

Added tooltip, clarified label

<img width="458" alt="Screen Shot 2022-02-24 at 9 33 54 AM" src="https://user-images.githubusercontent.com/5720791/155577007-5cf4683e-b91c-4922-9f07-4bd12b97109c.png">
