### ISSUE TITLE
can't add loan to project

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#4288]
I'm trying to add a MVZ loan to a [project](https://arctos.database.museum/project/10003578) that Mariel created.

When I click on "Add Loan" I just get a blank screen with the Arctos headers.
![Arctos_addloan_blankscreen](https://user-images.githubusercontent.com/967275/150849043-584c64bd-d8a1-43c7-a3b8-42ada721e31f.PNG)

Also @campmlc, the start date you entered for this project is 1905.

**Comment by dustymc** [comment]
I removed those links from next release - they don't play nice with the new transaction form, if they're necessary from the project we can do something different.

In the meantime, you can add the project from the transaction.

**Comment by ccicero** [comment]
OK, thanks. It is helpful to be able to add from projects directly, but that workaround is ok for now.
