### ISSUE TITLE
WoRMS (via Arctos) data pull

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4293]
Via https://github.com/ArctosDB/arctos/issues/2926 the worms fetch script is no longer translating (sorta). Please check it out in test and let me know what needs changed. What's displayed is (almost) simply [what comes in from WoRMs]( https://www.marinespecies.org/rest/AphiaRecordByAphiaID/137813) and not messing with it is almost certainly the least confusing way forward, but keep reading....

The data from WoRMS comes in without any indication of classification vs. metadata. I'm using https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxon_term to sort them out - terms that are considered classification terms by that code table go in as classification terms, everything else goes in as metadata. So, if WoRMS starts providing supersubunderclass it'll be stuffed into metadata until it's added to our local code table, but it will still be present. (The scripts currently running in production ignore anything they don't explicitly deal with.)

The new code is worlds simpler than the old, but there's still some manipulation (sorting out the classification terms) so there's room for more, if absolutely necessary. (Any manipulation is a potential entry point for a bug, however unlikely that may be.)

Yay, or does anything need adjusted?

Here's a pre-update classification:

<img width="1612" alt="Screen Shot 2022-01-26 at 10 19 22 AM" src="https://user-images.githubusercontent.com/5720791/151223013-e3980461-35de-40bd-97d7-e8f0d4d1b1d2.png">

and post-update:

<img width="1499" alt="Screen Shot 2022-01-26 at 10 20 02 AM" src="https://user-images.githubusercontent.com/5720791/151223089-537e27dc-f12c-4b0d-a3d0-1560da50f5da.png">

@sharpphyl

**Comment by Jegelewicz** [comment]
subclass and superfamily are included in the code table - shouldn't they show up in the classification?

**Comment by dustymc** [comment]
If there's a term coming from WoRMs (check the "what comes in from WoRMs" link above), it should be in the classification, even if it's not in the right place. Do you have an example that's dropping something?

**Comment by Jegelewicz** [comment]
The example is above. In the pre-update the classification has a subclass and superfamily but in the post-update it doesn't.

**Comment by dustymc** [comment]
WoRMS dropped that, it was included in the original data they provided but not in their webservice for some reason, IDK, it's not there now.

**Comment by dustymc** [comment]
I found [a different thing](https://www.marinespecies.org/rest/AphiaClassificationByAphiaID/137813), it's weird in the other direction but whatever. It adds a service call and a bit of complexity, but I think everything's still well within the realm of "manageable."

http://test.arctos.database.museum/name/Conus%20abbas#WoRMSviaArctos

<img width="1409" alt="Screen Shot 2022-01-26 at 12 50 27 PM" src="https://user-images.githubusercontent.com/5720791/151244865-cd84ee9d-0e36-49c9-9283-84b86f39966a.png">

**Comment by Jegelewicz** [comment]
This is NICE

**Comment by sharpphyl** [comment]
Sorry, I just got back to GitHub.  Started on invalid taxa this morning and was blown away by the additional data in each WoRMS (via Arctos) entry.  I'll be working taxonomy for a few hours and will let you know if I see anything missing, but I think this is a big leap forward.  Adding the type (marine, freshwater, etc.) is a great help.  Thanks!

**Comment by sharpphyl** [comment]
It looks like we'll need to add "accepted" and "unaccepted" to our code table and decide if those should replace "valid" and "invalid" in Arctos and other sources, or be used just for WoRMS (via Arctos).  Until everything in WoRMS (via Arctos) is refreshed, we'll have both sets of terms in WoRMS (via Arctos).  It will also impact our Taxonomy Search screen.  I haven't looked at all the other taxon statuses, but having everything exactly as it is in WoRMS is much better.  Thx.

Before refresh

<img width="641" alt="invalid in current WoRMS (via Arctos)" src="https://user-images.githubusercontent.com/15368365/152692045-094c61a8-8f50-4e04-99d9-54fa4e4f0760.png">

After refresh

<img width="944" alt="unaccepted in refreshed WoRMS (via Arctos)" src="https://user-images.githubusercontent.com/15368365/152692043-2f95717c-51eb-44ae-b225-6fb94d093da1.png">


I'm refreshing a few superfamilies each day.  Dusty, how many records can I put in the queue to refresh without impacting Arctos's performance?

**Comment by dustymc** [comment]
>add "accepted" and "unaccepted" to our code table a

https://github.com/ArctosDB/arctos/issues/2926, there is no code table.

>and decide 

https://github.com/ArctosDB/arctos/issues/4293#issue-1115365247; we're just taking whatever WoRMS sends.

> how many records

Shouldn't matter - it should handle anything you can get past the initial insert, but might take a while.

**Comment by sharpphyl** [comment]
> https://github.com/ArctosDB/arctos/issues/2926, there is no code table.

So there's no code table the WoRMS (via Arctos) entries.  If I want to use the SQL you wrote to find catalog records using an unaccepted taxon status as an accepted identification, will the SQL (with adjustments) still work if there is nothing in the code table?  

If I clone a WoRMS (via Arctos) classification/metadata into Arctos, it will show the taxon status as accepted, so collections using that source will probably need both the valid/invalid and accepted/unaccepted terms.

> Shouldn't matter - it should handle anything you can get past the initial insert, but might take a while.

What is "a while"?  I put in a group of taxon names to be refreshed several days ago and another group yesterday.  The previous group failed and yesterday's entries are still sitting there.

<img width="961" alt="Screen Shot 2022-02-07 at 7 52 42 AM" src="https://user-images.githubusercontent.com/15368365/152812381-75e8c142-2dcd-42fb-b005-9be6ad7ea53e.png">

I'm assuming that after the refresh, I'll see the metadata and classification change as in the example below.  That will help me (and other data entry volunteers) know if the record is refreshed or not.

Before
<img width="1350" alt="Screen Shot 2022-02-07 at 7 48 36 AM" src="https://user-images.githubusercontent.com/15368365/152812698-e3a2ad9b-5170-4ca2-954c-bb77d2903efa.png">


After

<img width="1365" alt="Screen Shot 2022-02-07 at 7 48 54 AM" src="https://user-images.githubusercontent.com/15368365/152812709-ebd163e4-cc80-4754-946e-fa7a769ff5ed.png">

**Comment by dustymc** [comment]
>unaccepted taxon status as an accepted identification, will the SQL (with adjustments) still work

That's 100% up to your source. If they're doing something consistent you can use it, if they're not you can't.

>clone a WoRMS (via Arctos) classification/metadata into Arctos

Yes, you can make impressive messes if you wish.

>previous group failed 

That's the sort of thing I need to know about! The bug is patched.

**Comment by dustymc** [comment]
>Arctos only accepts what's in the code table for taxon_status.

Please see https://github.com/ArctosDB/arctos/issues/2926, that is not true.

>give it time to process 

Yep.

**Comment by Jegelewicz** [comment]
@sharpphyl there is no longer a taxon status code table - you can put whatever in there....so now WoRMS can put whatever in there too.

**Comment by sharpphyl** [comment]
So this table https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxon_status just historic suggestions?  or will it be deleted and all references to it?

<img width="640" alt="Screen Shot 2022-02-08 at 6 58 52 AM" src="https://user-images.githubusercontent.com/15368365/153002057-1d9a058b-99cc-4624-9e3d-24826dcc348b.png">

**Comment by Jegelewicz** [comment]
@dustymc how should we handle the above?

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/2926#issuecomment-1022749512

**Comment by Jegelewicz** [comment]
Thanks - I made an issue in the documentation repo and I'll try to get to this soon.

**Comment by sharpphyl** [comment]
> give it time to process
> Yep.

It seems to be working now.  Thanks.

**Comment by sharpphyl** [comment]
The refresh of a portion of the Mytiloidea and Ostreoidea that I requested yesterday failed.  Can you confirm that I should delete everything in the failed refresh and reenter it?  Does it matter what the taxon status is?

<img width="286" alt="Screen Shot 2022-02-11 at 8 14 42 AM" src="https://user-images.githubusercontent.com/15368365/153617698-a1387bd1-8728-45ab-84ce-81269e1ca794.png">

**Comment by dustymc** [comment]
>I should delete everything

I'm not sure what you mean, but if there's a problem I'm probably not going to be able to fix it without seeing what caused it. I'll check back in when what can complete has, unless you know what's causing the problem??

>taxon status

Nope.

**Comment by sharpphyl** [comment]
The instructions say: 
You may [clear all](https://arctos.database.museum/tools/requestWormsRefresh.cfm?action=clearAllByStat&status=refresh_fail) for this status. You may need to then request an additional refresh.

It doesn't say, you must clear and reenter, so I wanted to check and let you know it failed.  I think I can figure out which requests have this status and reenter them.  

I have no idea what would cause this problem vs. other requests that went through ok.  The few that I looked had a taxon status of "invalid" (pre-refresh) which is why I asked.  

If you don't see a reason, I'll do the "clear and reenter" and see if it happens again.

**Comment by dustymc** [comment]
Well of course if there's a link I'll click it, so I just cleared....

Let me know if you get any more fails, I'll try to not muck up figuring out what happened! (Maybe these were related to yesterday's outage?)

**Comment by sharpphyl** [comment]
Ok, I'll reenter them. Thx.
