### ISSUE TITLE
Parts stuck in bulkload tool

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4296]
I loaded these yesterday

![image](https://user-images.githubusercontent.com/5725767/151407127-f39aaefc-4bc4-43d4-acd1-d361082b3a6a.png)

I had also loaded a ton of barcodes to parts and those went off without a hitch. I wouldn't expect this stuff to sit here for so long. We really do need some sort of idea how long these various tasks might take. Is that even possible?

**Comment by dustymc** [comment]
There are incremental adjustments which can be made (I just did, for next release, thanks). Anything more radical is going to require some flavor of significantly more resources.
