### ISSUE TITLE
Need Help with Arctos Error

### ISSUE THREAD

**Issue by gradyjt** [ArctosDB/arctos#4297]
Hello, I was trying to create an encumbrance for locality information (so I chose "encumber coordinates") and I got this error:

An error occurred while processing this page!
Message: ERROR: syntax error at or near "," Position: 206
Detail:
Check the Arctos Handbook for more information on errors.
This message has been logged as A1E561B6-F8BB-4F93-8FA675F5ED937EB0 Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue.

There's really not that many boxes and options to fill in each box for an encumbrance so I can only imagine how I've managed to mess this up, but I look forward to any illumination you all can provide me. Thank you!

**Comment by dustymc** [comment]
https://handbook.arctosdb.org/documentation/understanding-errors.html#missing-expression

Make sure ENCUMBERING_AGENT_ID is green/happy.

**Comment by gradyjt** [comment]
Oh boy, thanks Dusty
