### ISSUE TITLE
Arctos doesn't like tgz?

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4298]
From https://github.com/ArctosDB/arctos/issues/3205#issuecomment-758809795 - the file is being created, permissions are good, the link 404s instead of downloading. Some weird cmdbx setting?

**Comment by dustymc** [comment]
Fix in next release, requires front-end restart to stick.

**Comment by dimus** [comment]
I guess it is related to gn harvesting not being able to reach https://arctos.database.museum/cache/gn_merge.tgz now

**Comment by dustymc** [comment]
Hi Dima - impeccable timing! I hope to have a fix out ~Monday, or I just did `` mv gn_merge.tgz gn_merge.tgz.zip`` and it seems to be happy with that.
