### ISSUE TITLE
Code Table Request - Fill in PLSS Range and Township Values

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#4300]
**Goal**
Add all possible PLSS Range and Township values to their respective locality attribute code tables.

**Context**
Often when I am creating new localities I have to add new range and township values to the code table. It would be easier to just add them all at once.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=cttrs_range and https://arctos.database.museum/info/ctDocumentation.cfm?table=cttrs_township

**Proposed Value**
Maximum values were discovered using this map https://en.wikipedia.org/wiki/Public_Land_Survey_System#/media/File:Meridians-baselines.png and this google earth overlay https://www.earthpoint.us/Townships.aspx

The maximum northern township is 164 N on the northern edge of North Dakota.
The maximum southern township is 99 S in the Aleutian Islands, Alaska.
The maximum western range is 207 W in the Aleutian Islands, Alaska.
The maximum eastern range is 101 E in southeast Alaska.

**Proposed Definition**
Range/Township 30 West/East/North/South. A measure of the distance west/east/north/south from the referenced principal meridian, generally in units of six miles. [Wikipedia](https://en.wikipedia.org/wiki/Public_Land_Survey_System#Commonly_used_terms)

**Comment by Jegelewicz** [comment]
Sounds like a good plan.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
@Jegelewicz Does this need further approval or can I go ahead?

**Comment by dustymc** [comment]
done?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Not yet, still gradually working on it. About 75% done.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Everything added now.
