### ISSUE TITLE
Selectively load records in bulkloader - how to?

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#4303]
I need to selectively load records in the bulkloader that were created by the same individual but we've got some duplicates. How do I selectively do this? Help please!
![Screen Shot 2022-02-02 at 9 33 30 AM](https://user-images.githubusercontent.com/17605945/152216377-ec93d9af-428a-445c-a483-f6bdf90a8d92.jpg)

**Comment by dustymc** [comment]
You can change status (or anything else) in that screen - just click on the value you want to change to get make it editable, then type/paste in one of the [actionable values](https://handbook.arctosdb.org/documentation/bulkloader.html#processing), then leave the cell (tab, click somewhere else, whatever) to save.

**Comment by atrox10** [comment]
We talked about this at the issues meeting Jan (and a previous one last year but I forgot to make the issue) - can we add some kind of check box next to records in the bulkloader and this would allow you to select functions to do, like delete, load,etc so you can do things with specific records.

**Comment by AJLinn** [comment]
>  check box next to records in the bulkloader 

I would find this really useful. Either that or we have a list of "actionable items" that are acceptable for that field in the bulkloader. As someone who manages a collection where all entries are made using the data entry page, I'm terrified of doing something wrong in the bulkloader.

**Comment by dustymc** [comment]
>some kind of check box

Checks don't seem to play particularly well with some other stuff, so I added a 'filter' link and some docs for next release.

<img width="1695" alt="Screen Shot 2022-02-09 at 1 14 11 PM" src="https://user-images.githubusercontent.com/5720791/153291130-458e13d6-7911-4cf7-a254-0c71adbe0837.png">

Also, some of you can see this thing:

<img width="237" alt="Screen Shot 2022-02-09 at 1 15 35 PM" src="https://user-images.githubusercontent.com/5720791/153291310-44f8c740-0160-4350-a629-b21235fa90b2.png">

which is very expensive (computationally) and doesn't get much use - please, use it!
