### ISSUE TITLE
Lycodon is old mammal and current snake name - for taxonomy committee

### ISSUE THREAD

**Issue by atrox10** [ArctosDB/arctos#4306]
This issue that Chris Conroy found with genus names, from Chris's email: Today I searched for all our Mephitidae (skunks) with tissue. Found the expected records, but also found some snakes, Lycodon. Turns out the term Lycodon 1865 is a long out of use synonym of Conepatus, the hog nosed skunk. This is a very minor thing, but wondering if there is anything that needs to be edited in arctos to stop this? Somewhere there must be a list of all terms ever used under Mephitidae, including these old synonyms. I just tried searching for =Mephitidae in the any taxon box, and tissues, and got:
An error occurred while processing this page!
Message: ERROR: canceling statement due to user request
Detail:
Detail:

Again, super minor, very obvious that the snakes are snakes. 

Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by dustymc** [comment]
Homonyms are a very common situation.

The full answer to how Arctos deals with this is in https://handbook.arctosdb.org/documentation/taxonomy.html. Collections should be sure their classification preferences match what they're cataloging.

For collections preferring the [Arctos](https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxonomy_source#arctos) classification, https://arctos.database.museum/name/Lycodon#Arctos are snakes.

GBIF is ambiguous: https://arctos.database.museum/name/Lycodon#GBIFBackboneTaxonomy - a collection preferring that (should such a thing become available) would just end up with a mess.

https://arctos.database.museum/name/Echidna is my usual example, it involves fish and moths and viruses in addition to snakes and mammals.

Hemihomonyms (in which the name can be considered valid by various groups) are even more common. https://arctos.database.museum/name/Iron is a good example involving plants, elements, tools, and insects and fish (which are governed by the same Code so it's also a homonym).
