### ISSUE TITLE
Feature Request - Count field for Loans

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#4316]
I'd like to request a "count" field on the create loan page (akin to the "estimated count" on the accession page). Even though one may add items and get a tally of loaned parts, this doesn't always capture number of individuals loaned. 

For instance, we send out a giant course loan of mammal study skins and skulls each year - there may be 800 parts in the loan that  represent 400 individuals, but we ultimately consider and report out to admins that 400 specimens were loaned. I note the '400'  under nature of material, but it would be nice to have a numeric field so I can easily incorporate these data into an annual report. 

Another example is we have uncataloged material that gets loaned (mounts, teaching collection material, etc.).  It would be nice to manually include these in the overall loan item count (until we migrate our teaching collection to Arctos of course!).

Would this be useful to anyone else? I could see this help for lots, part/counterparts, sets, etc. where parts don't align with entities loaned.

**Comment by ebraker** [comment]
approved @ Arctos Issues Meeting 2022-03-03

**Comment by Jegelewicz** [comment]
So this is one of those issues that seems like it will NEVER get resolved.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/6854
