### ISSUE TITLE
error feedback

### ISSUE THREAD

**Issue by ErinKup** [ArctosDB/arctos#4318]
Hi team,

I am working through the Arctos "How to create and manage your Arctos team..." How to page and ran into an error (718D9983-C6BA-47A6-8736D03EA3EA3486). I logged in to Arctos (ErinKup) and followed this path:

Go to https://arctos.database.museum/
From the Arctos main menu select Manage Data > Agents 

When I navigated to the Agents page I saw the error (screenshot attached). Any guidance would be helpful!

Cheers,
Erin Kuprewicz

<img width="1438" alt="ARCTOS - error screen" src="https://user-images.githubusercontent.com/66339116/153445670-511caa7d-7e89-4c38-971c-8da4e0a16f6c.png">

**Comment by Jegelewicz** [comment]
Please see https://github.com/ArctosDB/data-migration/issues/545
