### ISSUE TITLE
Feature Request - Move 'Create' button for new part attributes next to 'Save Edits'

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#4320]
The current window to create new part attributes is confusing. If you're creating a new part attribute and don't see the entire screen in your window, you have to scroll to the right to hit 'Create.' However, there is a 'Save Edits' button in the middle above the 'Create New Part Attribute.' The inclination is to hit 'Save Edits' but that doesn't actually create the new attribute. My curatorial assistant and I were both confused by that until we realized the need to scroll over to the 'Create' button. 

A simple solution is to move the 'Create' Button next to the 'Save Edits' button to make it more obvious.

**Comment by ccicero** [comment]
OK, I see that issue now. What about putting 'Create' below the fields for 'Create New Part Attribute' (so lined up with 'Save Edits' but below where you enter the new part attribute so it's more obvious? 

If you're creating a new part attribute for a part that doesn't have any attributes (a common scenario), you don't see the stuff above the 'Save Edits' so then you think 'Save Edits' goes with the creation of a new attribute but it doesn't actually save your edits (i.e., new attribute). Make sense?

**Comment by dustymc** [comment]
<img width="1262" alt="Screen Shot 2022-02-10 at 2 05 04 PM" src="https://user-images.githubusercontent.com/5720791/153504472-ae72da2e-c7ac-4ebd-ad28-8bc70e574e04.png">

How's that?
