### ISSUE TITLE
Arctos Down - 10 Feb 2:35 PM Arctos is throwing up a 503 error

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#4321]
Please check out!

## Unplanned Outage
 -10 Feb 2:35 PM Arctos is throwing up a 503 error

## Communication before/during outage
- [x] Pin this issue
- [ ] Banner updated @jegelewicz 
- [x] Email sent to AWG 
- [x] Email sent to Arctos Google Group 
- [x] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [x] Unpin this issue
- [ ] Banner updated @jegelewicz
- [x] Email sent to AWG 
- [ ] Email sent to Arctos Google Group 
- [x] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by dustymc** [comment]
I sent Chris email, looks like TACC's entire network is down from here.

**Comment by lin-fred** [comment]
tweeted

**Comment by ewommack** [comment]
emailed

**Comment by campmlc** [comment]
Thanks for getting notifications out so quickly! That's got to be a record.

**Comment by campmlc** [comment]
Back up for me.

**Comment by lin-fred** [comment]
back up for me too, tweeted update

**Comment by campmlc** [comment]
Does Emily send out the email that it's back up? We should do that before
closing the issue?

**Comment by dustymc** [comment]
service has been restored

**Comment by campmlc** [comment]
We should send out an email announcement to that effect.

**Comment by mkoo** [comment]
sorry I thought I saw an email already-- but it was announcing that it was down!

**Comment by mkoo** [comment]
replied to the group email myself
