### ISSUE TITLE
Browse and Edit SQL tools not working in Bulkloader

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4322]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I tried to use the SQL tool in Browse and Edit to reduce a field that had a remark with too many characters. When I click on the SQL button, the browser spins and eventually gives me a warning that the page is unresponsive. Using Chrome.

**To Reproduce**
1. Go to Bulkloader Browse and Edit
2. Click on filter for my data
3. Click SQL under Controls

**Expected behavior**
To be able to use the SQL tool to fix a consistent error across fields.

**Screenshots**

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by dustymc** [comment]
Can't reproduce without information requested in issue template.

**Comment by campmlc** [comment]
I thought I provided that- Chrome browser, most recent version, 980475882 PC with MS Windows 10?

**Comment by dustymc** [comment]
> Steps to reproduce the behavior:

The tool is working for me, it's either your browser (not unlikely with Chrome) or the specific records (not unlikely with the situation you describe) or something involving the path.

**Comment by campmlc** [comment]
It initially wouldn't even let me click on any of the fields to start filtering. I just got it to allow a filter, but then it froze again. What do you suggest? Some of my records have loaded - it would be much easier to edit the remaining problems in SQL.

**Comment by dustymc** [comment]
Confirmed behavior, the browse-and-edit form is very slow on some systems. Possibly Windows?? Some common browser extension? @ccicero seems to also have very slow loading of this form. (I still see more collections/data than anyone else, and everything seems to complete in <2s for me on mac/firefox.) Reopening, can anyone identify the culprit here?

**Comment by dustymc** [comment]
related: https://github.com/ArctosDB/arctos/issues/9440 would change this form (remove editing capacity).

**Comment by dustymc** [comment]
No further information, closing
