### ISSUE TITLE
[CONTACT] GUID_Prefix for new MLZ collection

### ISSUE THREAD

**Issue by zmsch** [ArctosDB/arctos#4325]
Hello,

I'd like to create a new Moore Lab of Zoology collection for marine invertebrate specimens. I'm proposing to use the GUID_Prefix [MLZ:Inv], does this seem like the right choice? @dustymc 

Thanks,
Zoe

**Comment by dustymc** [comment]
https://handbook.arctosdb.org/best_practices/GUID.html can help you decide if that's the right choice, but MLZ:Inv is technically acceptable and about what I'd expect for such a collection.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/new-collections/issues/493
