### ISSUE TITLE
Bulkloading Specimen Remarks

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#4326]
Two questions tied in with this:
1) Is it possible to bulkload specimen remarks?
2) Is it possible to bulkload specimen remarks without overwriting any information already included in the field?

We have developed a description that we want to include with all specimens in our botany backlog, some of have already been entered into Arctos. These specimens already have notes about inventory, processing, etc. that we want to make sure we keep. Is this possible, or will we need to do it manually?

Thanks for your help!

**Comment by dustymc** [comment]
Merge-->https://github.com/ArctosDB/arctos/issues/2556

Please help prioritize that Issue (just set an appropriate label or leave a comment).
