### ISSUE TITLE
Quarantine Taxon Name - Buteo jamaicensis abeiticola

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4327]
The name suggested for quarantine is:

[Buteo jamaicensis abeiticola](https://arctos.database.museum/name/Buteo%20jamaicensis%20abeiticola)

The reason for quarantine is:

Doesn't appear outside of Arctos; suspect it's a misspelling

The suggested treatment for all identifications currently using this name is:

Unsure; guidance needed.

Collections currently using this name in identifications include:

MSB:Bird

**Comment by Jegelewicz** [comment]
I changed this one to A {string}. name can be quarantined once Arctos recognizes that it is no longer in use.

**Comment by ccicero** [comment]
It looks like that is a synonym for Buteo jamaicensis borealis?
https://avibase.bsc-eoc.org/species.jsp?lang=EN&avibaseid=65613235D0326275

@ewommack do you know anything about this taxon?

**Comment by dustymc** [comment]
avibase is abieticola, the Arctos name is is abeiticola.

Name is not used, now quarantined, closing.

**Comment by Jegelewicz** [comment]
Added relationship to Buteo jamaicensis abieticola
