### ISSUE TITLE
Feature Request - Subsample relationships in pre-created parts

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#4328]
**Is your feature request related to a problem? Please describe.**
All of our parts were created via bulkload without any subsample relationships. As I create loans I often realize that certain parts do need subsample relationships. For example: https://arctos.database.museum/guid/NMMNH:Paleo:70594 is a mandible with teeth. The teeth are articulated in the mandible and should probably be subsamples of the mandible.

**Describe what you're trying to accomplish** 
An easy way to create subsample relationships between parts that already exist.

**Describe the solution you'd like**
Perhaps when clicking the subsample button it will let you choose an existing part or create a new part. Right now it just creates a new part.

**Describe alternatives you've considered**
Using condition or remarks

**Comment by Jegelewicz** [comment]
@Nicole-Ridgwell-NMMNHS can you make a quick tutorial for using this?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I've done this several times now, it is super easy. @Jegelewicz 1 min explanation + screen recording?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Where should I load the video?

**Comment by Jegelewicz** [comment]
Sent you an email.
