### ISSUE TITLE
MVZ accessions not incrementing - showing error

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#4329]
@dustymc I am trying to create a new MVZ:Bird accession and I select the collection but it's not giving me the next accession number. Instead, it's giving an 'error catch'

Same for all the other MVZ collections.

![image](https://user-images.githubusercontent.com/967275/154341308-0df1df14-c0f8-4a9f-baaf-42977d34013d.png)

Can you please fix? Thjanks.

**Comment by dustymc** [comment]
<img width="1687" alt="Screen Shot 2022-02-16 at 11 53 29 AM" src="https://user-images.githubusercontent.com/5720791/154345262-f48c5b23-3e53-4ad7-bf8e-ed97e0240da0.png">

Works for me - glitch in the matrix?
