### ISSUE TITLE
Code Table Request - Add Quemado Formation

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#4331]
**Goal**
Add Quemado Formation

**Context**
Quemado Formation exists (https://nmgs.nmt.edu/publications/guidebooks/downloads/45/45_p0279_p0281.pdf) and I need to use it for one of our localities.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlithostratigraphic_formation

**Proposed Value**
Quemado Formation

**Proposed Definition**
Plio-Pleistocene fluvial deposits of volcaniclastic and siliciclastic sandstone and conglomerate in west-central New Mexico. [New Mexico Geological Society](https://nmgs.nmt.edu/publications/guidebooks/downloads/45/45_p0279_p0281.pdf)

If there are no objections I will add it to the code table

**Comment by Jegelewicz** [comment]
No objections here. May be a crazy question - but how does one get stuff like this into Macrostrat?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> how does one get stuff like this into Macrostrat?

Reading the website and skimming over their publications makes it clear as mud, but it seems to be some sort of mass computer ingestion of literature and geological maps mediated by a team of geologists.

**Comment by Jegelewicz** [comment]
Oh so no effective way for the community to comment...sheesh
