### ISSUE TITLE
TPT Taxonomy from Global Names

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4332]
The current [TPT Taxonomy source](https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxonomy_source#tpt__via_arctos_) contains only a portion of the TPT taxonomy that should now be found in GlobalNames. Although I do not see it as a resource there?

![image](https://user-images.githubusercontent.com/5725767/154366947-440c4cb1-7dfd-4541-ae28-337f1d0233f6.png)

It would be a great test case for using an external source if the TPT source in Arctos could be populated with the data from GlobalNames.

See https://github.com/GlobalNamesArchitecture/dwca_hunter/issues/31

**Comment by dustymc** [comment]
I don't know why this is here, https://github.com/ArctosDB/arctos/discussions/4965 would allow using any remote and doesn't really need a test mule, anything can be imported into local classifications now.
