### ISSUE TITLE
Does not map to message

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4334]
Today I and a lot of other people recieved an annotation from Arctos - https://arctos.database.museum/info/reviewAnnotation.cfm?action=show&atype=specimen&guid_prefix=UTEP:Ento&reviewer_comment=NULL

> does not map to El Paso County 

So I checked one - https://arctos.database.museum/guid/UTEP:Ento:100142

Here is the map for it

<img width="960" alt="Screenshot 2022-02-17 08 28 17" src="https://user-images.githubusercontent.com/5725767/154514703-eaa85d75-2c57-419b-b881-c031681a0060.png">

From my perspective, this is a waste of my precious time. There are plenty of actual problems with localities in Arctos, why are we still doing this? Sorry for the rant, but I have way too much to do and this just got under my skin.

**Comment by Jegelewicz** [comment]
And here is the "does not map to Cibola County" example

https://arctos.database.museum/guid/UNM:Paleo:15578

<img width="960" alt="Screenshot 2022-02-17 08 34 39" src="https://user-images.githubusercontent.com/5725767/154515536-d2c571d0-85cb-4608-b4c8-3334fa33faf5.png">

**Comment by dustymc** [comment]
>waste of my precious time

So block it.

>How can we make this better?

I'd guess the person who fixed the data didn't review the annotation, but that could have happened in lots of orders from lots of angles.

**Comment by dustymc** [comment]
>whole lotta copy pasta 

The notifications provide one path (it's collection-centric) to annotations. You can get there in ways that allow addressing the entire annotation with one entry - https://arctos.database.museum/info/reviewAnnotation.cfm?collection_object_id=28154808 for example.


<img width="718" alt="Screen Shot 2022-02-17 at 10 12 28 AM" src="https://user-images.githubusercontent.com/5720791/154544463-a15d4a49-228f-454c-87a6-795ce5dae637.png">

>Shouldn't these annotations be placed on the localities 

Annotations are placed on whatever data object the user was looking at when they clicked the button.

**Comment by dustymc** [comment]
>don't understand how a user ended up with this collection of things and managed to annotate them all
<img width="157" alt="Screen Shot 2022-02-17 at 10 41 27 AM" src="https://user-images.githubusercontent.com/5720791/154549104-f939f4d7-a788-4975-a7fb-aed61f38337d.png">
<img width="240" alt="Screen Shot 2022-02-17 at 10 42 07 AM" src="https://user-images.githubusercontent.com/5720791/154549122-0563e027-1ebf-44c5-8c0c-4bc10526459a.png">
<img width="485" alt="Screen Shot 2022-02-17 at 10 42 16 AM" src="https://user-images.githubusercontent.com/5720791/154549137-1a43375d-44bb-4a11-9f89-dcc5e80556f8.png">
<img width="245" alt="Screen Shot 2022-02-17 at 10 42 27 AM" src="https://user-images.githubusercontent.com/5720791/154549162-7a34fe6b-88ba-46de-aadc-470408d8ece1.png">

**Comment by dustymc** [comment]
Spatial fit problems are now being handled by a report rather than annotations, I think we're done here, tentatively closing. 

(We can still talk about notification filtering/tools/whatever, but that can be a more general conversation.)
