### ISSUE TITLE
Feature Request - container calculated volume

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4335]
**Is your feature request related to a problem? Please describe.**

See https://github.com/ArctosDB/arctos/issues/2288#issuecomment-1043197530, https://github.com/ArctosDB/arctos/issues/3632, sorta-not-quite https://github.com/ArctosDB/arctos/issues/3982

It would be useful to constrain containers by volume, a convenient proxy to cumulative dimensions. 

**Describe what you're trying to accomplish** 

A 13.5x5.5x13.5 freezer rack position should accept only one 13x5x13 freezer box.

**Describe the solution you'd like**

Add a cumulative dimensions check to the container check trigger.

**Describe alternatives you've considered**

Don't?

**Additional context**

This rule will likely be imperfect, but I think volume is an actionable, simple, and useful approximation of reality, where trying to do something more complicated with dimensions is more likely to cause problems and misunderstandings.

**Priority**

?

@campmlc please confirm if this seems reasonable.

**Comment by dustymc** [comment]
>Can this be an optional 

No, it's a rule or it's not. There could be a report or something for "is not" but those don't seem to get used so I'm not sure what that would do. Dimensions are optional and the rule can't apply without them, so it would not be an absolute rule.

**Comment by campmlc** [comment]
It would be good to know who would be affected by the rule in advance, so
we can reach out. How many collections have multiple objects with the same
dimensions in a single position?

**Comment by dustymc** [comment]
> who would be affected by the rule i

That would be an unavoidable part of the implementation, there's no reason to do that until we're sure this adds value and is something we want to do.

**Comment by dustymc** [comment]
Here's a report of the containers which can't exist under this rule.

Owners:

```

 institution_acronym |  c  
---------------------+-----
 MSB                 | 465
 MVZ                 |   2
 UAM                 |  23
 UMNH                |  20
 UTEP                |  54

```

Data:

[temp_container_no_fit.csv.zip](https://github.com/ArctosDB/arctos/files/8126804/temp_container_no_fit.csv.zip)

Some of these probably aren't fixable by users in the current environment. I can set this up so that I can update from a spreadsheet (I probably can't from this one, so please don't try without talking to me first!), or we could loop back to this after https://github.com/ArctosDB/arctos/issues/4084 (which may or may not make this fixable in the UI).

**Comment by dustymc** [comment]
>what is the problem

The contents have more volume than the parent. https://arctos.database.museum/findContainer.cfm?container_id=14424015 claims to be 21 x 3 x 17 CM (1071) and contains 100 3 x 27 x 78 CM (=631800) positions.

>how do we fix

If there's something that can be predictably magicked in those, let me know and I'll get it. Otherwise, you tell me.

**Comment by cjconroy** [comment]
A slide box could be 21 x 3 x 17 cm. A glass slide could be around 3 x 27 x 78 MILLIMETERS. A slide box could hold 100 slides like that. Is that the issue?

**Comment by dustymc** [comment]
All units are [CM](https://handbook.arctosdb.org/documentation/container.html#width-height-and-length), decimals are permitted. 0.3 x 2.7 x 7.8 * 100 < 1071, so no problem. 

@campmlc does that sound like what happened? I can pull your positions in slide boxes for review if so.

**Comment by campmlc** [comment]
Yes

**Comment by campmlc** [comment]
Thanks!

**Comment by dustymc** [comment]
Here's the summary:

```

arctosprod@arctos>> select width,height,length, count(*) c from temp_msb_sp group by width,height,length;
 width | height | length |   c   
-------+--------+--------+-------
       |        |        |   204
   2.5 |    0.1 |    7.5 |  1173
     3 |     27 |     78 | 50000
(3 rows)
```

I can get the actual data if you need it to make a decision, but it's a mite huge so if this suffices I'll skip that part.

**Comment by campmlc** [comment]
From Wikipedia
A *microscope slide* is a thin flat piece of glass
<https://en.m.wikipedia.org/wiki/Glass>, typically 75 by 26 mm (3 by 1
inches) and about 1 mm thick,

**Comment by dustymc** [comment]
I'm not sure what to make of that. If the slides do or should have measurements they will need to be slightly smaller than the positions. (I checked one, it's 2.5 x 0.1 x 7.5 ) 7.5x2.6x1x100=1950 won't fix in 21 x 3 x 17=1071 box, even without the intermediate positions. 7.6x2.6x0.2x100=395 easily fits, but random numbers that I make up probably aren't the best way to escape a mess....

**Comment by dustymc** [comment]
Done, I removed dimensions from these containers.

[temp_container_no_fit(1).csv.zip](https://github.com/ArctosDB/arctos/files/8210751/temp_container_no_fit.1.csv.zip)
