### ISSUE TITLE
error feedback

### ISSUE THREAD

**Issue by lmtabak** [ArctosDB/arctos#4336]
** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **

** Outages should be reported to the contacts listed at https://arctosdb.org/arctos-down/ **

** Arctos Documentation is http://handbook.arctosdb.org/ **

** Learn more about Arctos at https://arctosdb.org/ **

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **
Logged into Arctos to unlock three locked User accounts, unlocked each, then logged out. I received this Error message when logging out of Arctos: This message has been logged as DC80008B-6AC6-47FF-8078EBAA088AFCC0.

I logged back into Arctos to see if the three User accounts had been successfully unlocked, but they had not.

**Comment by dustymc** [comment]
>received this Error message 

https://github.com/ArctosDB/arctos/issues/4194

>they had not.

Usernames?

**Comment by lmtabak** [comment]
aaamer
slcarlso
emmayle

**Comment by dustymc** [comment]
Thanks, I can confirm that those users are locked. Can you provide screenshots of what all you did? I think maybe you didn't click the second link, at least there's nothing in the logs.

**Comment by lmtabak** [comment]
You are correct. I did not click the second link for any of them. I went back in, did click the second link, checked to make sure that they were indeed no longer locked, had success, then logged out. I did receive another error message, but do not know why. "This message has been logged as 118567A9-D430-42E6-A808A28BB82AC704."
