### ISSUE TITLE
Feature Request - Add general URL to publications

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#4338]
Not all publications have one of the object identifier options that are currently available. I added a [dissertation](https://arctos.database.museum/SpecimenUsage.cfm?action=search&publication_id=10010922) and this is the permalink:

https://search.library.berkeley.edu/permalink/01UCS_BER/s4lks2/cdi_cdl_escholarship_oai_escholarship_org_ark_13030_qt9xn036k9

I put that in 'storage location' which doesn't seem right and also doesn't show when you search on publications. Seems like we need a general URL for these sorts of pubs so that someone can linkout to get the abstract or the actual dissertation if they want it.

**Comment by dustymc** [comment]
Suggest Media - I don't think it's sustainable to have general links (which do need maintenance) scattered around in various places. (That's a great example - I don't believe the "perma" part! And I was able to guess an ARK out of that URL, it goes somewhere else! https://n2t.net/ark:/13030/qt9xn036k9 ARGH!!)


See also https://github.com/ArctosDB/arctos/issues/1837

**Comment by dustymc** [comment]
And in case the how isn't clear:

<img width="169" alt="Screen Shot 2022-02-17 at 4 55 45 PM" src="https://user-images.githubusercontent.com/5720791/154597008-4c65aca8-ec8f-43cd-8a7d-6cbfdb76406c.png">

<img width="524" alt="Screen Shot 2022-02-17 at 4 56 10 PM" src="https://user-images.githubusercontent.com/5720791/154597013-dd7dd713-69e6-48df-9551-1408b7d5ebe1.png">

save and done

**Comment by ccicero** [comment]
OK, that works. Thanks!
