### ISSUE TITLE
Hide media relationship dropdown when creating media unrelated to an object record/agent/etc

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4340]
From the main media search https://arctos.database.museum/MediaSearch.cfm

when I select "Attach/Upload Media" the relationships do not display in the dropdown.

![image](https://user-images.githubusercontent.com/5725767/154746607-b850aec8-fe93-4a3e-ae28-5c99a2029945.png)

**Comment by Jegelewicz** [comment]
Then maybe the thingee should be hidden? Clearly NOBODY reads the red boxes...

**Comment by Jegelewicz** [comment]
I am reopening this and changing the title.

**Comment by dustymc** [comment]
figure out how to move the instructions up when coming from no-relationship land

**Comment by dustymc** [comment]
I'm tabling this, the form was written the way it was for a reason, not reading warnings is not justification for removing them!
