### ISSUE TITLE
Feature Request - overdue loan reminders

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4346]
**Is your feature request related to a problem? Please describe.**

Overdue loan reminders don't go out often enough.

**Describe what you're trying to accomplish** 

Do better with loans.

**Describe the solution you'd like**

Send overdue reminders monthly.

@KyndallH

**Comment by dustymc** [comment]
Well of course this isn't as trivial as I'd hoped.

Attached are summary data for 1694 loans which are overdue by more than 3000 days. That's going to melt the current reminder script, which I think leaves two possible paths:

1. Rebuild the reminder scripts to somehow deal with the possibility of thousands of notifications, send thousands of daily notifications.
2. Just clean this up. I'm hoping we can go this way, but I'll need help from the collections (assuming these data aren't accurate, and maybe they are). Please let me know if I can mass-magic anything.

Here are the data - the filter is loan_status != 'closed and RETURN_DUE_DATE more than 3000 days before now.

[temp_way_overdue_loans.csv.zip](https://github.com/ArctosDB/arctos/files/8125998/temp_way_overdue_loans.csv.zip)

See also https://github.com/ArctosDB/arctos/issues/1893 - these data DO NOT contain anything without a due date.

Let me know if some other data would be useful.

Here are the involved collections:

```

 guid_prefix | count 
-------------+-------
 MSB:Bird    |    60
 MVZ:Mamm    |     5
 UAM:Herb    |   182
 UAM:Mamm    |   260
 UAM:EH      |     5
 UTEP:ES     |    20
 KNWR:Ento   |    30
 UAM:Arc     |   165
 UAM:Inv     |    10
 ALMNH:EH    |     5
 MSB:Mamm    |   150
 UTEP:Mamm   |    10
 UAMb:Herb   |    35
 MVZ:Herp    |   310
 UAM:ES      |   329
 DMNS:Mamm   |     3
 UAM:Ento    |   112
 UMNH:Mamm   |     3
```



 @mkoo
 @AJLinn
 @campmlc
 @amgunderson
 @dssikes
 @atrox10
 @mvzhuang
 @cjconroy
 @brandon-s-thompson
 @acdoll
 @jldunnum
 @jrdemboski
 @mlbowser
 @kderieg322079
 @StefanieBond
 @catherpes,@catherpes
 @sjshirar
 @Jegelewicz
 @jandreslopez
 @dustymc
 @kyndallh


help!

**Comment by dustymc** [comment]
Also: here are 60 loans which are due more than 3000 days from now. Do those need reminders, should there be some hard rule, is someone really working on millennia-long projects and this is fine, ????

[temp_way_underdue_loans.csv.zip](https://github.com/ArctosDB/arctos/files/8126203/temp_way_underdue_loans.csv.zip)

-------------+-------
 UAM:Mamm    |    10
 MSB:Mamm    |    10
 MSB:Bird    |    15
 UAM:ES      |    20
 ALMNH:Paleo |     5

**Comment by Jegelewicz** [comment]
UMMMMM, Find Transactions isn't working for me - it times out. Can't help if I can't find/edit!

Go to Manage Data > Transactions > Find Transactions

Browser spins forever
![image](https://user-images.githubusercontent.com/5725767/155379582-76645e03-35f8-4a79-a0c4-11779734857c.png)

I also see this at the bottom
![image](https://user-images.githubusercontent.com/5725767/155379934-684dc84f-e9c7-4b94-bc38-2a6216bfe689.png)

It literally never stops trying. I don't even get a timeout message!

**Comment by dustymc** [comment]
The entire internet is pretty crazy today, and TACC has some equipment that's being particularly affected. Call it a glitch in the matrix. This works about instantly for me.

<img width="458" alt="Screen Shot 2022-02-23 at 10 14 41 AM" src="https://user-images.githubusercontent.com/5720791/155381619-03fe2100-d109-4798-8ae4-4e230c444277.png">

**Comment by Jegelewicz** [comment]
I eventually ended up with this

> An error occurred while processing this page!
> Message: An I/O error occurred while sending to the backend.
> Detail:
> Check the [Arctos Handbook](http://handbook.arctosdb.org/documentation/understanding-errors.html) for more information on errors.
> 
> This message has been logged as D03F0CB9-E9C2-4AA6-B3AB3C00E46C39D3 Please [contact us](https://github.com/ArctosDB/arctos/issues/new?assignees=&labels=contact&template=contact-arctos.md&title=error%20feedback) with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue.

**Comment by AJLinn** [comment]
>  UAM:EH      |     5

My staff are dealing with these as we speak! Glad we managed the others already!

**Comment by dustymc** [comment]
Going to AWG for help - how do we deal with this?

**Comment by dustymc** [comment]
<img width="1044" alt="Screen Shot 2022-03-03 at 11 17 29 AM" src="https://user-images.githubusercontent.com/5720791/156636550-5cba6248-2054-488a-8cc3-51034bd8ce0e.png">

**Comment by dustymc** [comment]
TODO: 
redo the list, it has duplicates
better search tools - "overdue loans" button

revisit

**Comment by dustymc** [comment]
Better CSV for loans more than a year overdue:

[temp_way_overdue_loans(1).csv.zip](https://github.com/ArctosDB/arctos/files/8200475/temp_way_overdue_loans.1.csv.zip)

Summary:


```

 guid_prefix |  c  
-------------+-----
 NMU:Mamm    |   1
 ALMNH:Inv   |   1
 UAM:Inv     |   1
 UMNH:Herp   |   1
 NMMNH:Bird  |   1
 MLZ:Bird    |   1
 UWBM:Herp   |   1
 UTEP:Teach  |   1
 KNWR:Herb   |   1
 ALMNH:EH    |   1
 KWP:Ento    |   1
 UMNH:Teach  |   1
 MVZ:Bird    |   2
 UMNH:Mamm   |   2
 UCM:Bird    |   2
 UWYMV:Bird  |   2
 UTEP:Inv    |   2
 MSB:Para    |   3
 UAM:Fish    |   3
 UTEP:Bird   |   4
 UTEP:HerpOS |   5
 UTEP:Mamm   |   5
 UCM:Herp    |   5
 MVZ:Mamm    |   5
 UCM:Mamm    |   6
 UAM:EH      |   6
 UTEP:Ento   |   9
 KNWR:Ento   |  10
 CHAS:Mamm   |  10
 UAMb:Herb   |  11
 UTEP:Herb   |  12
 UTEP:ES     |  13
 DMNS:Mamm   |  14
 DMNS:Bird   |  17
 UTEP:Herp   |  23
 UAM:Arc     |  33
 MSB:Bird    |  34
 MSB:Mamm    |  47
 UAM:Mamm    |  51
 UAM:Herb    |  62
 MVZ:Herp    |  69
 UAM:ES      | 120
 UAM:Ento    | 139

```

data quality and loan request contacts of involved collections:

 @ebraker
 @msbparasites
 @mlbowser
 @mkoo
 @AJLinn
 @ewommack
 @campmlc
 @ccicero
 @kderieg322079
 @StefanieBond
 @catherpes,@catherpes
 @amgunderson
 @dssikes
 @atrox10
 @mvzhuang
 @cjconroy
 @sjshirar
 @wellerjes
 @lin-fred
 @keg34
 @brandon-s-thompson
 @Jegelewicz
 @kmkocot
 @jandreslopez
 @droberts49
 @dustymc
 @acdoll
 @jldunnum
 @jrdemboski
 @kyndallh

Due date documentation seems OK to me. 

Added a search helper button for next release:

<img width="1052" alt="Screen Shot 2022-03-07 at 12 01 25 PM" src="https://user-images.githubusercontent.com/5720791/157108965-b11b9d03-48ae-48cd-b4ed-1f11a5edeb18.png">

Going back to AWG Agenda for advice.

**Comment by dustymc** [comment]
Next release: loan reminders are separated from other things and moved to the notification system, which happily deals with 800 overdue loans.
