### ISSUE TITLE
Questions regarding media uploads

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#4348]
I'm getting into media uploads via TACC for the first time and have come up with some questions.

1) Special character clarification
Are periods considered special characters in file names? I'm looking at an internal document from May 2019 that says "Do not use periods or other special characters in image filenames." The [handbook mentions](https://handbook.arctosdb.org/how_to/How-to-Upload-Media-to-TACC.html) that filenames starting with a period will be ignored, but does not say periods are not permitted. I want to clarify because we use trinomials and name the image files with periods between the numbers. I tried attaching an individual jpeg to a catalog record and it automatically replaced the periods with underscores. Does this happen in the TACC upload as well?

2) TACC directory
After I have uploaded files to TACC, the handbook says the files are "immediately available on the web and available for use in the Media Bulkloader." Where do I find the files? When I started, we set up a new directory with a folder for each collection (see [#144](https://github.com/ArctosDB/internal/issues/144)). I can find the directory where the the images I [uploaded individually](https://web.corral.tacc.utexas.edu/arctos-s3/jweller/) are saved and the old directory that does not have the individual collections ([CAS](https://web.corral.tacc.utexas.edu/CAS/)), but I can't find the CHAS directory with the images I bulkloaded on Friday, February 18. Is it not visible until I receive an email from TACC with the CSV for metadata? Or do I need to contact someone to let them know that there are images in TACC to be processed?

3) Associate one image with multiple catalog records
I have an image of container notes that apply to more than one specimen. I was able to use the _Add multiple "shows cataloged_item" records_ on the edit media page in order to associate the image with all specimens/catalog records in the container.
![image](https://user-images.githubusercontent.com/93737929/154810180-ea8e8bda-836b-4f92-ba39-a6abca7d14bc.png)
However, the image should be categorized under "documents cataloged_item" rather than "shows cataloged_item". When I try to change the dropdown to "documents", a popup prompts me to re-enter the catalog number:
![image](https://user-images.githubusercontent.com/93737929/154810227-3cdcca79-0b1f-46f8-87ad-f9b9a15570ea.png)
Is there another way to associate an image with multiple records that does not involve individually modifying each record?
I also tried bulkloading media metadata to associate the image with more than one record, but received the following notification:
![image](https://user-images.githubusercontent.com/93737929/154810529-d6552ef8-9d27-43cf-8954-04eb14942267.png)
Here's the CSV I used to test; do I need to delete one of the columns?
[bulkloadMediaTemplate_CSV.csv](https://github.com/ArctosDB/arctos/files/8102626/bulkloadMediaTemplate_CSV.csv)

Thank you in advance for your help!

**Comment by dustymc** [comment]
>Are periods considered special characters in file names? 

Yes; if you (or anyone else) might ever want these involved in some kind of scripting, stick with the [guidelines](https://handbook.arctosdb.org/documentation/media.html#media-uri).

>automatically

There is no magic/sanitization/anything else in the SCP upload process; if you can stuff it through whatever client you're using, it'll probably end up on the internet. ("Probably" because you might be able to find a character combination that can melt TACC's mapping; please don't try!)

>Where do I find the files? 

https://web.corral.tacc.utexas.edu/arctos/

>receive an email from TACC with the CSV for metadata

There's no magic and no communication - upload stuff, find it on the internet, that's it.

>bulkloading

There are any number of ways to do most everything in Arctos, I would bulkload everything but whatever works for you is probably OK.

>following notification

You've already created a media object for that binary so you can't create it again. You can use other bulkloaders to add to existing media objects.

**Comment by wellerjes** [comment]
Thanks for this information! I was able to attach one photo to multiple files using the relationships bulkloader. Just to clarify, I should only get an email with a link to the CSV if I do a small batch upload?

**Comment by dustymc** [comment]
>email with a link to the CSV if I do a small batch upload?

Yes, and see https://github.com/ArctosDB/arctos/issues/4274
