### ISSUE TITLE
Data Entry - make fields in Identification and Identification Extras identical

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#4351]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
The fields in the Identification section are not the same in the Identification Extra section.

<img width="804" alt="Screen Shot 2022-02-20 at 11 54 59 AM" src="https://user-images.githubusercontent.com/15368365/154859338-9a9ca7ff-be23-4aeb-a66e-eeb5c7c6953f.png">

<img width="1038" alt="Screen Shot 2022-02-20 at 12 01 00 PM" src="https://user-images.githubusercontent.com/15368365/154859544-366ff67f-4434-4dcc-a130-706e95c208d7.png">

**Describe what you're trying to accomplish** 
1.  We need to be able to "build" taxonomic names in the Identification Extra section.
2.  We need to be able to leave the date field blank as in the primary identification.

**Describe the solution you'd like**
Duplicate the Identification fields in the Identification Extras section.

**Describe alternatives you've considered**
We have to correct the record after it is uploaded which is a wonderful opportunity create errors and omissions.

**Additional context**
It would also be nice if the fields had the same names in each section and were in the same order.
Agent 1 vs. Identifying Agent
NatureofID vs. Nature of ID
ID Date vs. MadeDate
ID Confidence vs. Confidence
Remarks vs. ID Remarks

Volunteers who database for a few hours a week really need UI consistency.

**Priority**
We're running into problems daily, so it's high priority for us.

**Comment by Jegelewicz** [comment]
@dustymc this seems like a fairly simple ask - getting the labels for the fields to be consistent?

I recommend the following:

Regular Identification | Identification Extras
 -- | -- 
Identifying Agent | Identifying Agent 1 (and so on) 
Nature of ID | Nature of ID 
ID Date | ID Date (this should NOT be yellow in the extras form) 
ID Confidence | ID Confidence
ID Remarks | ID Remarks
