### ISSUE TITLE
Provide "try again" for WoRMS (via Arctos) refresh

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#4353]
**Is your feature request related to a problem? Please describe.**
I'm slowly refreshing the entire WoRMS (via Arctos) taxonomy for mollusca.  Most days, there are only a handful of names that fail to refresh so I manually refresh them.  Today there are 231 which is more than I want to refresh manually. 

<img width="981" alt="Screen Shot 2022-02-21 at 7 37 42 AM" src="https://user-images.githubusercontent.com/15368365/154976686-4cedfee4-5d7b-4796-9844-0aadaab7b102.png">

 They appear to be in multiple families.  If I choose to figure out which families and refresh them all, I'll add hundreds more names to the queue than necessary.  For example, one name is in Veneridae which would put 3,543 names into the queue again.

<img width="663" alt="Screen Shot 2022-02-21 at 7 38 38 AM" src="https://user-images.githubusercontent.com/15368365/154976715-28aed184-7c27-44b8-bcd4-7c928b95fc34.png">

**Describe what you're trying to accomplish** 

The ability to send these names back into the queue to be refreshed.

**Describe the solution you'd like**
A button on the page listing the names that failed to refresh that lets me add them back into the queue to be refreshed.

**Describe alternatives you've considered**
Figure out what families contain names that didn't refresh and add them back into the queue or manually refresh each name

**Priority**
Normal priority unless hundreds of names are added daily which will move the priority to critical.

**Comment by dustymc** [comment]
I recycled what was stuck.

**Comment by sharpphyl** [comment]
Thanks!  Should I request a recycle whenever it builds to a large quantity?

**Comment by dustymc** [comment]
yes please - and I'll try to figure out what's failing, if that ever happens when I've got time to look....

**Comment by sharpphyl** [comment]
Ok, I'll leave this issue open for now.

**Comment by sharpphyl** [comment]
It's been working pretty well until today. 

@dustymc can you refresh these 997 names?

<img width="261" alt="Screen Shot 2022-04-02 at 8 39 49 AM" src="https://user-images.githubusercontent.com/15368365/161389180-804f109b-c8e4-42e3-9869-b535b5b93525.png">

**Comment by Jegelewicz** [comment]
We need to consider what the refresh schedule should be going forward. Can we just pick up changes? Set up a schedule by family or something? Also need workflow for any incoming collections using WoRMS (via arctos) that needs new classifications.

**Comment by Jegelewicz** [comment]
@dustymc just want to clarify how WoRMS (via Arctos) is currently working: Classifications are ONLY refreshed from WoRMS on request?

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/4293

**Comment by Jegelewicz** [comment]
Well that didn't really clear it up for me, but I THINK that stuff is only refreshed upon request. Any way we could have a service that requests a refresh of some portion of WoRMS (via Arctos) monthly or something? Just thinking that the data will get stale and if Phyllis decides to move to Ireland we might not ever get a refresh?
