### ISSUE TITLE
Feature Request - Filter Bulkload Browse by status

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4354]
Regarding - https://arctos.database.museum/Bulkloader/browseBulk.cfm

**Is your feature request related to a problem? Please describe.**
I have to manually enter repetitive things.

**Describe what you're trying to accomplish** 
I have some records in the bulkload staging table entered by a single user. There are a couple that I want to hold for review and the rest I would like to load. Rather than adding autoload a million times, it would be nice to change the status on the few to "hold", then filter them out and use "Load all selected records" to load the rest.

This would also be consistent with the way the bulkload tools work.

![image](https://user-images.githubusercontent.com/5725767/154994865-329a9709-7183-494c-bf57-4c0255054183.png)

**Describe the solution you'd like**
Allow me to filter records in the bulkload staging table by status.

**Describe alternatives you've considered**
Manually changing the many records I want to load to "autoload"

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by campmlc** [comment]
Since this has been a year since initial request, please up priority.

**Comment by campmlc** [comment]
@sharpphyl @AdrienneRaniszewski @jldunnum

**Comment by campmlc** [comment]
This is especially needed as it appears the SQL tool is not working. When I try to access it, the page becomes non-responsive.

**Comment by dustymc** [comment]
review after 5331
