### ISSUE TITLE
Hide regular parts in the new data entry form

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4355]
I still cannot figure out how to do this. I am only using Part "extras" and I don't want to have to scroll past all of the parts.

How do you hide these?

<img width="960" alt="Screenshot 2022-02-21 12 12 39" src="https://user-images.githubusercontent.com/5725767/155014499-95c5f5bf-86d7-4818-8fdb-c7cd5a2f6644.png">

**Comment by sharpphyl** [comment]
Doesn't this do it?  Last column.  
<img width="220" alt="Screen Shot 2022-02-21 at 12 23 38 PM" src="https://user-images.githubusercontent.com/15368365/155015674-9e39c486-6151-4485-aa9f-d11a63374e14.png">

**Comment by Jegelewicz** [comment]
Where IS that?

**Comment by Jegelewicz** [comment]
OH wait! I found it! UGH to this being at the far right.....

**Comment by sharpphyl** [comment]
Yep.  Arctos UI is scroll happy.
