### ISSUE TITLE
Need Help with Arctos Error

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4356]
# Error Text
Save rejected: FAIL: Extras fail

# Where it happened
In the new data entry form - Save as new record

# Steps to get there
Enter some stuff, hit Save as new record

Here is what is in the part "extras"

part attribute type | value | date | determiner 
 -- | -- | -- | -- 
condition report | Some   browning of cotton which can be removed by cold water soaking overnight   without soap. A few dark brown spots which may come out in the cold water   soak; if not, could spot apply neutral soap paste for 1-3 minutes and rinse.   Do not think the spots are significant to retain for chemical testing. Box   with items .007 & .008. | 2022-02-21 | unknown 
location | MHB B2/R42/C06/S02 | 2022-02-21 | unknown 

# Problem
The base record actually saves, but the extras do not, yet all of the data remains in the form. Try a second time and it does the same thing. Eventually you wind up with 10 copies of the record in the bulkloader.

This seems specific to this record - many others have been entered without incident. Is there something in the text causing the problem?

In any case when I get a "FAIL" I would assume that nothing loaded, but the base record did.

# Solution
**Community response with directions for how to correct the problem**

**Comment by dustymc** [comment]
Cause of error patched.

Partial save bug fix in next release.
