### ISSUE TITLE
Bulkload parts

### ISSUE THREAD

**Issue by SerinaBrady** [ArctosDB/arctos#4357]
Hi, 

I bulkloaded parts this morning and they are still in the parts bulkloader. Normally they are loaded by now. Am I missing something?

Serina

**Comment by dustymc** [comment]
<img width="731" alt="Screen Shot 2022-02-21 at 1 10 59 PM" src="https://user-images.githubusercontent.com/5720791/155026738-495dc97e-1be2-44c6-8a02-96a0297e991e.png">


I've got a big load running, things will be slow for a day or two.

**Comment by Jegelewicz** [comment]
It seems to be taking a very long time....

**Comment by Jegelewicz** [comment]
OOPS - just saw the hidden thing at the bottom of your comment. I'll try to practice patience!
