### ISSUE TITLE
Acanthocephala disambiguation

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4358]
[Acanthocephala](https://arctos.database.museum/name/Acanthocephala) is both a [worm phylum](https://en.wikipedia.org/wiki/Acanthocephala) and an [insect genus](https://en.wikipedia.org/wiki/Acanthocephala_(bug)).

The classification in Arctos is for the phylum which leaves insects using the name as an identification with an incorrect classification.

I can see two paths forward:

1. If all Para collections will prefer WoRMS (via Arctos), they will get the phylum classification. Then I can change the Arctos classification to the insect and everyone will be happy.
2. I can create a new classification source "Arctos Entomology" and put the insect classification there, then all Ento collections will need to prefer Arctos Ento to get the correct classification.

What do we prefer?

Affected collections
<html><body>

Collection | UsesSource | #IDs
-- | -- | --
ASUMZ:Ento | Arctos | 1
DMNS:Para | Arctos | 11
HWML:Para | Arctos; TPT (via Arctos); WoRMS (via Arctos) | 247
MSB:Para | Arctos | 224
NMMNH:Ento | Arctos | 1
UNCG:Para | Arctos | 1

</body>
</html>

@bfluker @acdoll @gracz-UNL @campmlc @lin-fred @bryansmclean

**Comment by Jegelewicz** [comment]
> And I bet they are both in WORMS?

Nope - just the "worm" as far as I can tell

**Comment by dustymc** [comment]
>both in WORMS?

There's no problem if they are?

>new classification source "Arctos Entomology"

FWIW I don't like the huge garbage can Sources. "Arctos" is the ultimate case of that, where it's just arbitrary things that may or may not line up with other arbitrary things, but even smaller sets of arbitrary things doesn't seem great from here. I'd rather see "insects according to [ collection | source | view | whatever ]" with the classifications all sticking to that viewpoint, so potential users can have some idea of what to expect.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/4669
