### ISSUE TITLE
citation bulkloader is stuck

### ISSUE THREAD

**Issue by amgunderson** [ArctosDB/arctos#4359]
My citations are set to autoload and have been for a day to no avail. 
https://arctos.database.museum/tools/BulkloadCitations.cfm
I'm on a Mac using chrome. 
This is a priority level high, it's stopping my work.

**Comment by dustymc** [comment]
<img width="343" alt="Screen Shot 2022-02-21 at 1 09 52 PM" src="https://user-images.githubusercontent.com/5720791/155202683-d2873e31-6922-4379-b450-ba655b7eaad1.png">

I paused my stuff, it should process soonish.

**Comment by amgunderson** [comment]
working now, thanks.
