### ISSUE TITLE
Feature Request - component loader documention (or ??)

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4360]
**Is your feature request related to a problem? Please describe.**

The component loader is throttled in such a way that loading and post-load processing should not become disruptive, which means things can take some time - occasionally days - to process.

**Describe what you're trying to accomplish** 

Minimally, users should have clear expectations.

**Describe the solution you'd like**

1. New loader version with better documentation and a link to the status page in the header
2. ?? I'm very open to ideas

**Describe alternatives you've considered**

1. Hope users find the status page.
2. Hope someone pops in with a clever and realistic idea regarding how this process should work

**Comment by Jegelewicz** [comment]
Sometimes you need to load stuff ASAP (new parts for a loan you need ot get out in 30 minutes). Is there any way we could add priority for stuff like this?

**Comment by dustymc** [comment]
I'm bumping priority - I'm not sure what can be done but a lot of things have touched on this in the last several days, I'll figure something out.
