### ISSUE TITLE
Feature Request - data entry - profile expansion

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4361]
**Is your feature request related to a problem? Please describe.**

The data entry "seed" option is not accessible to low-rights users, gets inadvertently modified, and can be confused with "real" data.

**Describe what you're trying to accomplish** 

Split "seed" data off from normal data.

**Describe the solution you'd like**

Allow a profile to carry seed data in addition to the current layout capability. Drop the special "seed" handler.

**Describe alternatives you've considered**

Don't.

**Additional context**

Would be nice if data from the profile had special highlighting.

**Priority**

?

@ebraker please correct whatever I've mangled, and feel free to flip this to next task if I'm not too lost.

**Comment by ebraker** [comment]
Yes! All sounds correct to me and I think it will be a great improvement!

**Comment by ebraker** [comment]
@dustymc I'm planning on covering the new data entry screen in our next webinar (3/8) - do you think this will be live by then? If not, I can just mention the soon-to-be capability.

**Comment by dustymc** [comment]
That might be a little optimistic, but I'll see what I can do!

**Comment by ebraker** [comment]
No worries if not!

**Comment by dustymc** [comment]
@ebraker  (and @AdrienneRaniszewski and everybody else) - the basics of this are running in test, I'm still ironing some things out but it should be mostly functional and feedback would be appreciated.

**Comment by ewommack** [comment]
@ebraker I created a project to try and keep track of all of the tips and info for the new data entry screen that have been popping up across different issues: https://github.com/orgs/ArctosDB/projects/12?add_cards_query=is%3Aopen

**Comment by dustymc** [comment]
You should have email from Arctos.

**Comment by ebraker** [comment]
Got it, I'm in! Thanks.

**Comment by ebraker** [comment]
Said aloud: "YAY!". I love the highlighting of already-seeded info as a QC step, and I think this expanded profile approach works better than the the combo profiles and seed records. 

Minor suggestions:

- I envision a day in the near future when the list of profiles gets unwieldy (I for instance will probably create 5-8 just for UCM alone).  Can we add table sorting capabilities or filter by institution?
![image](https://user-images.githubusercontent.com/11336485/156406634-7218293f-84c3-4c65-af68-a97eb0a6026f.png)
- Is it possible to add "bring to front" ordering when actively working on a given table in the form? I realize I can move the table further down/to the side and just scroll, but some of my tables will perfectly fit within my large screen if they overlap slightly, and I could avoid scrolling if I the table I clicked automatically moved forward. (more of a wishlist item than necessity). E.g., the upper attributes table would move to front when clicked so I could access the "bill width" field without moving the lower table.

![image](https://user-images.githubusercontent.com/11336485/156408014-6e8cfb03-20c1-41d5-8cb8-fad39dffd07f.png)

**Comment by dustymc** [comment]
>works better than the the combo profiles and seed records

Yes, agreed. (Wish I'd have thought of it!) I think there will be a sort of awkward transition period (and there's a fair bit of complexity wrapped around that), but the only alternative I could come up with was just tossing everyone's existing profiles, which I presume would understandably involve torches and pitchforks and such....

>table sorting capabilities 

Sure, should be pretty trivial. Not sure I'll get it in this release, I'll start a wishlist if no.

The splash page...

<img width="452" alt="Screen Shot 2022-03-02 at 8 55 39 AM" src="https://user-images.githubusercontent.com/5720791/156409667-82f3f858-d122-4a41-b344-17d20dee957b.png">

... is going to hit the same wall.

>"bring to front" ordering

I'll see what I can come up with.

**Comment by dustymc** [comment]
> "bring to front" ordering

next release

**Comment by ebraker** [comment]
I'm cruising around and finding some super handy features! Thanks for the 'bring to front' ordering. 

Questions:
- Can you add hypertext to -> "Extras" Parts have to link to the part attribute code table?
- Do we still need to "autoload_extras" or will this be deprecated? If we do still use this, do we first have to autoload_core, then go back and auto_load extras (or does autoload_extras automatically signal core data to load)?

**Comment by dustymc** [comment]
>hypertext to -> "Extras" Parts have to link to the part attribute code table?

Going back to next task

>still need to "autoload_extras"


autoload_core is the same as the old loaded=null - it loads the catalog record (which disappears from the bulkloader as part of the process)
autoload_extras is autoload_core, plus when the catalog record loads it flags all the extras (via UUID) to follow.

Yes, it's permanent (until someone tells me we don't need that complexity...). You can

1. autoload_extras and be done (eg if you have some sort of procedure that makes you comfortable with that), or
2. autoload_core if you want to review the extras after the "core" loads for whatever reason

**Comment by sharpphyl** [comment]
When you say "Begin with previous records" it seems that only applies to records still in the bulkloader.  Can you add that comment so volunteers know they can't go back to records that have been uploaded?  

![Screen Shot 2022-03-05 at 11 15 08 AM](https://user-images.githubusercontent.com/15368365/156891468-744a65a3-0508-4be0-8f85-1117ab4c6ef7.png)

> table sorting capabilities
> Sure, should be pretty trivial. Not sure I'll get it in this release, I'll start a wishlist if no.

Yes, it would be helpful to limit most of us to just those profiles in our collection with our GUID:Prefix.

Can you confirm that only the user who created the profile can edit it.

**Comment by dustymc** [comment]
Extra parts linked up.

>applies only to records still in the bulkloader

Yep, hard to start with things that don't exist! I'd think clicking the links is all the documentation that any user would need, but I've added some maybe-confusing little subheader things, let me know what they should say.
<img width="1425" alt="Screen Shot 2022-03-09 at 8 55 55 AM" src="https://user-images.githubusercontent.com/5720791/157491243-2e092d8f-0dea-4602-b1a9-c8c5b899121a.png">


> profiles...with our GUID:Prefix

Yes that's probably correct, in next release.

>can edit 

Profiles should not be editable at all, but feel free to prove me wrong on that!

**Comment by ccicero** [comment]
I am trying out the new data entry form for the first time. Liking it! I chose 'bird' for the attribute helper, which is great. However, the values are carrying over from the previous entry when they shouldn't. The options for all are set to 'show' and not 'carry.'

**Comment by dustymc** [comment]
Going back next task for that. Should I carry units, or clear them as well?

**Comment by ccicero** [comment]
Carry units is OK I think. Thanks!

**Comment by ccicero** [comment]
Is there any way to make the boxes themselves dynamic in the 'dynamic view' so that you can resize the individual boxes? It will help to align things better.

**Comment by dustymc** [comment]
>make the boxes themselves dynamic

Probably "not trivial" but likely possible.

What are you trying to do? They're already as small as they can be without hiding anything, and you can leave any amount of space between them if you're looking for griddish. You can turn rows and/or columns off to make them magically smaller for most groups. You can now stack them and click any part to bring the whole thing to the front. 

Just trying to understand the use case - screenshots would probably help.
