### ISSUE TITLE
Arctos Down - 503 Service not available

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4363]
Please complete to the best of your ability.

## Unplanned Outage
 - Date and time outage discovered: 2022-02-22
 - Describe the outage (Arctos down or only some part not working?): All I get from any Arctos page is 503 Service not available

## Planned Outage
 - Date and time outage will begin:
 - Date and time outage is expected to end:
 - Reason for outage:
 - Expected behavior during and after the outage:

## Communication before/during outage
- [x] Pin this issue
- [x] Banner updated @jegelewicz 
- [ ] Email sent to AWG 
- [ ] Email sent to Arctos Google Group 
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [x] Unpin this issue
- [x] Banner updated @jegelewicz
- [ ] Email sent to AWG 
- [ ] Email sent to Arctos Google Group 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by dustymc** [comment]
bounced CF - seems to be up now
