### ISSUE TITLE
Jalitridae - the {string} part of an A {string} shouldn't show up in flat taxonomy gaps

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4364]
The name exists, but I cannot add a classification?

https://arctos.database.museum/name/Jalitridae

![image](https://user-images.githubusercontent.com/5725767/155235494-2ef51c93-2ea9-410c-ae19-dbae4443d812.png)

**Comment by dustymc** [comment]
>The name exists

How ya figure?

Also, why do you think that's a valid taxon?

**Comment by Jegelewicz** [comment]
> How ya figure?

![image](https://user-images.githubusercontent.com/5725767/155237317-d11a5cb8-268b-4ea5-9f82-5d7b4678ab8b.png)

> Also, why do you think that's a valid taxon?

Who says I do?

![image](https://user-images.githubusercontent.com/5725767/155237416-3aecec14-ae53-4ccb-9e69-5e005e448657.png)

SOOOO - maybe the {string} part of an A {string} shouldn't show up in flat taxonomy gaps?

**Comment by dustymc** [comment]
This doesn't make any sense.

**Comment by Jegelewicz** [comment]
What doesn't make sense?

Flat taxonomy should be looking at taxonomic names. Currently though it is looking at strings. For the example above, the identification is Amphipoda {Jalitridae} so the related classification will be to Amphipoda NOT Jalitridae. When the report tells me there is no classification for Jalitridae, that is true, but is also EXPECTED. I don't want to spend time hunting for classifications that aren't expected to be there. If there was no classification for Amphipoda, then I would want to know that, because there is an expectation that there should be one.

SO, for flat taxonomy gaps, don't evaluate the {string} part of an A {string} identification, just the A

**Comment by Jegelewicz** [comment]
See also #4637
