### ISSUE TITLE
Help with Creating New Taxa

### ISSUE THREAD

**Issue by zmsch** [ArctosDB/arctos#4365]
I haven't done this before but I'm trying to create two new taxon names (Coccotylus brodiei and Pelmatolapia mariae) following the instructions here: https://handbook.arctosdb.org/how_to/How-to-Create-Taxa.html

I don't have assigned taxonomic authority so I was going to use the "clone classification" option but this doesn't show as an option on the taxon page for me. I'll attach a screenshot, not sure if this a bug or authority issue. Any help is much appreciated, thanks!
![Screen Shot 2022-02-22 at 2 49 59 PM](https://user-images.githubusercontent.com/67019638/155236367-a0b23257-5afb-4306-b959-74b8da1f7413.png)

**Comment by dustymc** [comment]
Please read https://handbook.arctosdb.org/documentation/taxonomy.html, review https://handbook.arctosdb.org/documentation/sharing-data-and-resources.html, let us know if you have any questions, then log out and back in for new superpowers.

**Comment by Jegelewicz** [comment]
Post any questions here!

**Comment by zmsch** [comment]
Thanks, I think I successfully created those new taxa!
