### ISSUE TITLE
Code Table Request - One preservation attribute for "formalin-fixed, stored in 45% isopropanol"

### ISSUE THREAD

**Issue by zmsch** [ArctosDB/arctos#4366]
**Goal**
To have one preservation value that includes the fixation (formalin) and storage (45% isopropanol)

**Context**
Efficiency and less errors -- similar issue #4309 

**Table**
PART_PRESERVATION

**Proposed Value**
formalin-fixed, stored in 45% isopropanol

**Proposed Definition**
A process whereby a whole organism, body, carcass, etc. is sufficiently fixed in a formalin solution (typically 10% formalin, aka 3.7% formaldehyde), rinsed, and stored long-term in a 45% isopropanol solution.

**Collection type**
Fish, but could be used for other biological specimen collections

**Comment by dustymc** [comment]
>same problem that we have with part names

I'm assuming a user will expect these values, where they're less likely to expect their muscle sample to have been soaked in cold liver juice for a decade.

I'll open another issue.

**Comment by Jegelewicz** [comment]
@dustymc in a discussion this week with people from the TDWG MaterialSample Task Group, we talked about these "combo" preservations. Richard Pyle at the Bishop Museum (Hawaii) deals with this by providing the choice of "formalin fixed, 70% ethanol", but that selection actually creates two preservation attributes - formalin and ethanol 70%. It adds complexity behind the scenes, but makes data entry easier and would ultimately eliminate the combination preservations. in the data. Possible?

**Comment by campmlc** [comment]
I absolutely support this.

**Comment by Jegelewicz** [comment]
Code table say create it.

**Comment by Jegelewicz** [comment]
Done
