### ISSUE TITLE
Unable to Log in to Arctos

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4369]
Arctos opens and I get the login screen, but when I click sign in nothing happens.

**Comment by Jegelewicz** [comment]
Well on the 10th try it worked? Any idea what's going on?

**Comment by dustymc** [comment]
https://portal.tacc.utexas.edu/user-news/-/news/107361 and increased load due to global events.

**Comment by Jegelewicz** [comment]
Man - this has been a real drag today. I can't get anything done.

**Comment by Jegelewicz** [comment]
I don't see anything at TACC about issues there. I am unable to do anything in Arctos at all.

**Comment by Jegelewicz** [comment]
Maybe it is Firefox? Chrome logged me in right away.
