### ISSUE TITLE
Who can add new operators?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4370]
@barke042 had manage collection role but when logged in did not see the "Roles/Permissions" option under Manage Arctos.

Currently manage_collection Description says

> Manage Collection metadata; invite users to become operators; grant and revoke rights from users and Operators; DELETE cataloged items and identifications; mark records in bulkloader to load; create DOIs.

Is there some combination of roles required to invite new operators?

**Comment by dustymc** [comment]
<img width="328" alt="Screen Shot 2022-02-23 at 1 37 47 PM" src="https://user-images.githubusercontent.com/5720791/155413649-6d02e6b9-51df-4a53-b30f-719395acdc21.png">
<img width="852" alt="Screen Shot 2022-02-23 at 1 38 16 PM" src="https://user-images.githubusercontent.com/5720791/155413673-fa25974a-7966-4505-9aab-2c2f72373a14.png">

**Comment by Jegelewicz** [comment]
Cool - I think we need to add that somehow in the role description so that it is clear that two roles are necessary. Sound OK?

**Comment by Jegelewicz** [comment]
Updated manage_collection description as follows:

Manage Collection metadata; DELETE cataloged items and identifications; mark records in bulkloader to load; create DOIs. When combined with manage_agents invite users to become operators; grant and revoke rights from users and Operators.
