### ISSUE TITLE
Need Help with Arctos Error - saving changes to agent fails

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4371]
# Error Text
![image](https://user-images.githubusercontent.com/5725767/155412782-0e843449-1518-4fad-83e4-4cd342771b98.png)

Sorry - I can't highlight and copy this for some reason.

# Where it happened
https://arctos.database.museum/agents.cfm?agent_id=21247375

# Steps to get there
1. Added a Github address
2. Select Save all changes
3. get error

# Problem
**Community response to describe the problem that caused the error**

# Solution
**Community response with directions for how to correct the problem**

**Comment by Jegelewicz** [comment]
Same problem with https://arctos.database.museum/agents.cfm?agent_id=21334732

![image](https://user-images.githubusercontent.com/5725767/155413539-1ff808a5-0266-4b8a-97e6-578f6fcf0eec.png)

Something weird with that address?

**Comment by dustymc** [comment]
Looks like census.gov's webservice is having a rough day.

```
l,s$coordinates='\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r \r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r \r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r44.991676,-93.18942
```

**Comment by Jegelewicz** [comment]
Can we fix this? I need to add logins to agents to invite operators and I cannot edit any agents.

**Comment by Jegelewicz** [comment]
Any idea how long we can expect this to last?

**Comment by mkoo** [comment]
From AWG: Dusty will  prioritized in a week after container work. Meanwhile send him names to update
