### ISSUE TITLE
Need Help with Arctos Error-access to publications

### ISSUE THREAD

**Issue by byuherpetology** [ArctosDB/arctos#4372]
# Error Text
An error occurred while processing this page!
Message: not authorized
Detail: You are not authorized to access this form.
Check the [Arctos Handbook](http://handbook.arctosdb.org/documentation/understanding-errors.html) for more information on errors.
This message has been logged as 9EDF8DE6-795C-4162-80F4F86075A038CF Please [contact us](https://github.com/ArctosDB/arctos/issues/new?assignees=&labels=contact&template=contact-arctos.md&title=error%20feedback) with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue.

# Where it happened
Search, publication/projects, create a new publication

# Steps to get there
I need to create a publication in order to designate a type specimes

# Problem
I don't have access to create publications.  I am trying to designate types and to do so I need to identify the associated publication so I need to be able to enter that publication into Arctos

# Solution
Can I please get access to enter publications and projects

**Comment by Jegelewicz** [comment]
@byuherpetology please confirm that you have read and understand the following

[Arctos Publication Documentation](http://handbook.arctosdb.org/documentation/publications.html)
[Arctos Project Documentation](http://handbook.arctosdb.org/documentation/projects.html)

**Comment by byuherpetology** [comment]
Yes, I have read the documentation

**Comment by dustymc** [comment]
Granted - let is know if you have any problems.
