### ISSUE TITLE
Quarantine Taxon Name - Hetarina

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4374]
The name suggested for quarantine is: [Hetarina](https://arctos.database.museum/name/Hetarina#secclass)

The reason for quarantine is: This does not appear to be a valid name

The suggested treatment for all identifications currently using this name is: Change to Hataerina {Hetarina}

Collections currently using this name in identifications include: CHAS:Ento
@wellerjes 

Priority
Please assign a priority-label.

**Comment by wellerjes** [comment]
Thanks for letting me know! I updated the specimens with "Hetarina" to unaccepted and Formula A {string} to preserve the original documentation.
![image](https://user-images.githubusercontent.com/93737929/155606575-9cb841b5-ea4a-40fb-9b7a-40ec6754afcd.png)
Will this resolve the issue?

I am still seeing 2 results for "[Hetarina](https://arctos.database.museum/name/Hetarina#secclass)", but I know sometimes it takes some time for Arctos to process the changes.

**Comment by Jegelewicz** [comment]
> Will this resolve the issue?

Nope - those Hetarina identifications that are not A {string} need to be deleted.

**Comment by Jegelewicz** [comment]
I just quarantined the name. Yay!
