### ISSUE TITLE
Records stuck with "coordinate value error" in bulkloader

### ISSUE THREAD

**Issue by zmsch** [ArctosDB/arctos#4376]
**Describe the bug**
Records that I tried to bulkload with a bad locality ID show status "coordinate value error". I am able to edit the record to pick a new locality and save so it passes checks. But back on the bulkloader browse & edit page, the record still shows status "coordinate value error",  I am unable to load the record, and if I click back into the record it says it has failed checks.

Additional side note bug: I've been getting a pop-up when I click in to edit a record in the bulkloader that reads "arctos.database.museum says iframe url does not have permission to interact with me" (screenshot below). I can click ok and then everything seems to work as it did before.

**To Reproduce**
This specific group of records do not have collection location data so I am try to load with an existing "No specific locality recorded."/"no higher geography recorded" locality. I can't remember if the coordinate value error showed up the first time with the initial bad locality ID or after I chose a new unknown locality.

**Expected behavior**
I would expect to be able to pick a new unknown locality that passes checks and then re-load the record.

**Screenshots**
![Screen Shot 2022-02-24 at 9 01 28 AM](https://user-images.githubusercontent.com/67019638/155577800-d63577c3-9805-4c05-a70f-7d3737db1c87.png)
![Screen Shot 2022-02-24 at 9 02 06 AM](https://user-images.githubusercontent.com/67019638/155577807-347d611b-7110-4524-a0e1-528f02c35495.png)
![Screen Shot 2022-02-24 at 9 10 09 AM](https://user-images.githubusercontent.com/67019638/155577813-3ba53645-0a45-4ca6-a057-b92b978148b8.png)
![Screen Shot 2022-02-24 at 9 01 14 AM](https://user-images.githubusercontent.com/67019638/155577834-6a48482c-1777-4eef-80fb-78cf8ffd100a.png)

**Data**
[20220113_2.csv](https://github.com/ArctosDB/arctos/files/8134587/20220113_2.csv)

**Desktop (please complete the following information):**
 - OS: macOS Catalina Version 10.15.7
 - Browser: Chrome Version 98.0.4758.80

**Additional context**
Similar issue? #4197

**Comment by cjconroy** [comment]
I repeatedly have this problem if I use a locality that has no lat longs. It saves fine upon data entry, but when trying to load from bulkloader it somehow has added decimal degrees to the units, even when I picked a locality that has no lat longs. I then have to reset that field to nothign, save, and try to reload.

**Comment by dustymc** [comment]
That's probably coming from the original lat long units (should be NULL), and that might be caused by the old form. I don't think I have access to that collection so I can't see your data; I can look closer if you want to grant that.

The iframe thing seems to be Chrome (or maybe some extension) being weird with GeoLocate, but I don't think we've ever fully figured that out - @ccicero?

@ewommack where are we on https://github.com/ArctosDB/arctos/issues/4175?

**Comment by dustymc** [comment]
When I can switch to the new screen as the default.

**Comment by ewommack** [comment]
We should bring it to the AWG to get the final say.
Do you mean to the bulkloader edits as well? I've noticed that swings back to the old form instead of going to the new form?
We've published in the Newsletter and social media.

**Comment by zmsch** [comment]
Thanks, @dustymc how do I give you access to the collection?

I turned my Chrome extensions off and on again and that seemed to fix the iframe issue.

**Comment by dustymc** [comment]
<img width="362" alt="Screen Shot 2022-02-24 at 1 17 05 PM" src="https://user-images.githubusercontent.com/5720791/155609248-6c8ece62-47db-419c-a250-c27e5b3aa623.png">

https://arctos.database.museum/AdminUsers.cfm?action=edit&username=dlm

Or you can go through Agents - you can search by github username and there's a link to the operator form.

<img width="1127" alt="Screen Shot 2022-02-24 at 1 18 38 PM" src="https://user-images.githubusercontent.com/5720791/155609467-83d913b6-fae6-445e-829e-34c90cc3b8af.png">

**Comment by zmsch** [comment]
Thanks! done

**Comment by dustymc** [comment]
Yep, looks like that's the problem. You can clear them out in the browse-and-edit UI - just click in the cell to edit and tab out to save.

<img width="356" alt="Screen Shot 2022-02-24 at 1 50 02 PM" src="https://user-images.githubusercontent.com/5720791/155613637-3747efd2-7d83-4acb-ba1b-913efe1eca15.png">


I cleared and checked one to confirm.

**Comment by zmsch** [comment]
Okay great, that worked--sorry the suggestion to just clear it w/in the browse & edit table didn't click with me before!
