### ISSUE TITLE
https problem

### ISSUE THREAD

**Issue by evoecogen-git** [ArctosDB/arctos#4377]
** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **

** Outages should be reported to the contacts listed at https://arctosdb.org/arctos-down/ **

** Arctos Documentation is http://handbook.arctosdb.org/ **

** Learn more about Arctos at https://arctosdb.org/ **

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **

**Comment by evoecogen-git** [comment]
Website security

Hello, I am a new user (well, returning after 12 years). Something concerned me immediately: the website is not secure (not https). Highly unusual, is there a reason? My online security software complains. IMHO this could be a problem for two reasons:
1. the data of users can be easily stolen. Not much Personally Identifiable Information there, but people often use the same password for many websites...
2. If there is any restricted data on endangered species, say a herp that people poach from the wild for trade, it can be stolen.

**Comment by evoecogen-git** [comment]
OK, so a follow up. Apparently I get "insecure" warnings and some instances of http instead of https on the latest Firefox on Mac, and not all the time. I suppose this may be caused by my browser, not your page....

**Comment by dustymc** [comment]
Thanks, I've asked our infrastructure folks to address this.
