### ISSUE TITLE
cannot use DOI lookup tool for new citation

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#4378]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
trying to use DOI cross reference tool. It throws up an error. Not sure what the solution is. Journal is Mammalian Biology. 
<img width="1011" alt="citation problem" src="https://user-images.githubusercontent.com/5749672/155603566-2d84ce48-8b66-4b28-8a76-09c205902377.png">

**To Reproduce**
See image attached. If you google that DOI the publication pops right up. 

**Expected behavior**
Arctos would find the pub and populate fields. 

**Screenshots**
attached.

**Desktop (please complete the following information):**
 Mac, Chrome

**Additional context**
publication is relatively recent, but is real. 

**Priority**
medium

**Comment by dustymc** [comment]
It's just not in the crossref's system.

https://search.crossref.org/?from_ui=yes&q=10.1007/s42991-021-00176-5 should provide a human-readable summary, but I think they're pulling from the same API Arctos uses.

**Comment by dustymc** [comment]
DOI has been added to crossref
