### ISSUE TITLE
Feature Request - Higher Geography Component Loader

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4379]
**Describe what you're trying to accomplish** 
Easily confirm whether a list of higher geography is in Arctos and for those that aren't a way to bulkload them.

**Describe the solution you'd like**
Higher Geography component loader here - https://arctos.database.museum/tools/bulkGeography.cfm

**Describe alternatives you've considered**
Keep manually chacking everything or letting the bulkloader fail stuff

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/4755
