### ISSUE TITLE
GPS degrees disappearing after data entry

### ISSUE THREAD

**Issue by kmkocot** [ArctosDB/arctos#4383]
My student workers are experiencing an issue with entering GPS coordinates that are formatted as degrees and decimal minutes into Arctos where the degrees and direction (N, E, S, W) disappear after saving the record but the minutes are preserved. 

**To Reproduce**
1. Log into Arctos with data entry permissions.
2. Click on "Enter Data" then "Data Entry" then click the "Enter Data" button (in our case we are entering data into ALMNH:Inv).
3. Enter data as usual selecting "degrees dec. minutes" from the "Original lat/long Units" drop-down menu.
4. Finish entering data and save the record.
5. Move on to a new record or elsewhere on Arctos then return to that record.

Note - going to the "Browse and Edit" page shows an error message for these entries that says "coordinate value error" or "Error and units, datum, and georeference source and protocol must be accompanied by coordinates." but the coordinates entered are correct. They did check the coordinates in Google Maps and they looked fine there.

**Expected behavior**
I would expect that the values for "Lat Deg" and "Long Deg" would be saved.

**Screenshots**
![Screenshot 2022-02-25 210411](https://user-images.githubusercontent.com/10491081/155826486-f8efb78c-73f0-44e9-8594-bb312dd53a10.png)

**Desktop (please complete the following information):**
 - OS: MacOS (Big Sur 11.6)
 - Browser; Safari
 - Version: current

**Priority**
Medium? We are having to record GPS coordinates in a remarks field right now.

**Comment by dustymc** [comment]
The short answer is to not use that screen. The "new" screen does not have these problems. 

I'll move ahead with https://github.com/ArctosDB/arctos/issues/4175 for net release.

**Comment by Jegelewicz** [comment]
@kmkocot the new screen is loads better and customizable! If you want a brief overview, let me know.

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/4175 is done, closing this as well.

**Comment by kmkocot** [comment]
OK thank you both! @Jegelewicz, I think we should be able to figure out the new screen but I will follow up if we have questions.

Best,
Kevin
