### ISSUE TITLE
Arctos Down - 2022-03-02 8:38am Ak

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#4388]
Please complete to the best of your ability.

## Unplanned Outage
 - Date and time outage discovered:2022-03-02 8:38am Ak
 - Describe the outage (Arctos down or only some part not working?): 
<img width="422" alt="Screen Shot 2022-03-02 at 8 39 10 AM" src="https://user-images.githubusercontent.com/17605945/156417339-f0c8b757-64db-4818-84cc-046ad45607ff.png">

## Planned Outage
 - Date and time outage will begin:
 - Date and time outage is expected to end:
 - Reason for outage:
 - Expected behavior during and after the outage:

## Communication before/during outage
- [ ] Pin this issue
- [ ] Banner updated @jegelewicz 
- [ ] Email sent to AWG 
- [ ] Email sent to Arctos Google Group 
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @jegelewicz
- [ ] Email sent to AWG 
- [ ] Email sent to Arctos Google Group 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by dustymc** [comment]
bounced commandbox - it's up now.
