### ISSUE TITLE
Code Table Request - Add Dietrich's solution as a part preservation

### ISSUE THREAD

**Issue by zmsch** [ArctosDB/arctos#4389]
**Goal**
Add "Dietrich's solution" as an option for part preservation

**Context**
Dietrich's solution is a common fixative used in histology

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=CTPART_PRESERVATION

**Proposed Value**
Dietrich's solution

**Proposed Definition**
a compound fixative used in histology that is composed of ethanol, acetic acid, and formaldehyde in an aqueous solution

**Collection type**
Fish

**Attribute**
Tissueness: Denies

**Available for Public View**
Yes

**Comment by Jegelewicz** [comment]
@ArctosDB/arctos-code-table-administrators any problems with this?

**Comment by Jegelewicz** [comment]
Code Table Committee says add.

**Comment by Jegelewicz** [comment]
Added
