### ISSUE TITLE
Arctos Down - 3:27 pm 3-2-22

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4390]
Please complete to the best of your ability.

## Unplanned Outage
 - Date and time outage discovered:
 - Describe the outage (Arctos down or only some part not working?):

## Planned Outage
 - Date and time outage will begin:
 - Date and time outage is expected to end:
 - Reason for outage:
 - Expected behavior during and after the outage:

## Communication before/during outage
- [ ] Pin this issue
- [ ] Banner updated @jegelewicz 
- [ ] Email sent to AWG 
- [ ] Email sent to Arctos Google Group 
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @jegelewicz
- [ ] Email sent to AWG 
- [ ] Email sent to Arctos Google Group 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by campmlc** [comment]
Getting 503 Service Not Available

**Comment by dustymc** [comment]
bounced

**Comment by campmlc** [comment]
Flat status has 4 million records? Loan of 20 items not loading.
