### ISSUE TITLE
Feature Request - entity magic

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4392]
**Is your feature request related to a problem? Please describe.**

What data should be magicked into Entities?

**Comment by mkoo** [comment]
Definitely specimen collecting event-- ideally a single map showing all related catalog records; point data could be shown as minimum convex polygons or bounding boxes but just having access to all points would be key to acceptance
 
again looking at an Entity record and how to adjust to show it's more of a conceptual record as opposed to a physical record, it would be helpful to have a summary list of parts from the records too.

**Comment by Jegelewicz** [comment]
From the Issues Meeting

Cataloging multiple occurrences things got word -> so we made a link that could hook a specimen to a specimen event -> but now we have organisms/entities that will perform those parts in a more cohesive fashion.
The thing that we are trying to do is connect multiple different parts collected at different times to one individual.
So were using parts connected to specimen events
Entity update from Carla - on her Eagle work
Created entity records for the eagles through the bulkloader
The entity collection -> no physical parts in the entity
The entity creates the overarching organism ID that will connect with all of your cataloged museum objects
Bulkloaded series of new entities -> each are the same individual as a museum cataloged object
When you catalog a museum object part say that it is the same individual as the Organism ID from the entity collection
Example -> collect blood at one point in time and place, get own museum catalog number; add another blood cataloged part
Each of these cataloged blood parts are tied together by having the Same Individual as the Organism ID of the entity in the museum entity collection
The entities are put into the new entity collection
Organism ID in the Identifier field in the specimen record
If you do a search on the Organism ID it will bring up all the individual cataloged museum parts that are connected 
Collecting events - depended on how far the animal traveled -> put in an area across the full travel space and the range of time over which you have samples from
Collecting events for the entity in the entity collection is the above described practise
Presently the entities are not being shared with GBIF
There may be some magic that could tie together some of these entity connections in the future, but at the moment that you have to do it by hand
We’re ahead of GBIF with this entity creation
Problem happening is that new collections do not know about this new system that we are developing.
So how do we keep it from happening for new collections?
Get rid of the links that you can form between events and parts
Invite people to the entity meetings if they have this type of material
Question about being able to show the events - all the points in time that you sampled and collected from that individual together in one interface -> one page that shows us al these things together
So maybe rework the entity object page
Need a map or Berkeley mapper link that has all of the different cataloged parts that are tied that entity
So you could click on that and see where the entity has moved over time, or was encountered over time
Access the dates as well somehow
Maybe see the individual catalog info from each of the cataloged objects on the entity object page
Have the entity items -> the entity is comprised of these following object records from these collections
