### ISSUE TITLE
Arctos Down - 503 Service Not Available

### ISSUE THREAD

**Issue by skgolden7** [ArctosDB/arctos#4393]
Please complete to the best of your ability.

## Unplanned Outage
 - Date and time outage discovered: 3/3/22 1:20 pm
 - Describe the outage (Arctos down or only some part not working?): Every page is returning a 503 Service Not Available

## Communication before/during outage
- [x] Pin this issue
- [ ] Banner updated @jegelewicz 
- [ ] Email sent to AWG 
- [ ] Email sent to Arctos Google Group 
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @jegelewicz
- [ ] Email sent to AWG 
- [ ] Email sent to Arctos Google Group 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by lin-fred** [comment]
I am also getting a 503

**Comment by mkoo** [comment]
@lin-fred I've having trouble with twitter today (separate email to you next) but can you post a #ArctosStatus tweet:
Arctos is currently down. Sorry for any inconvenience

**Comment by mkoo** [comment]
@dustymc another reboot?

**Comment by dustymc** [comment]
done
