### ISSUE TITLE
Georeferencing Issue, possibly associated with Higher Geography error

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#4395]
Our intern noticed this issue while georeferencing and I'm wondering if it is connected to how a Higher Geography is spelled.

Higher Geography in question is "North America, United States, Illinois, La Salle County"

My understanding is that if a georeferenced locality matches with the Higher Geography, the box around the map will turn green. If it doesn't, then the box will turn red. But this locality has the georeferencing map in a yellow box (circled in red in the screenshot; not the larger verification/accepted box that encompasses the entire locality information).

![Screenshot 2022-03-04 093805](https://user-images.githubusercontent.com/93737929/156793660-69e049a4-7519-43e7-a91e-30f59d8d1fff.jpg)
Catalog Record Example: [1914.20.252](https://arctos.database.museum/guid/CHAS:Herb:1914.10.252)

My thought is that it could be related to the Higher Geography being listed as "La Salle" instead of "LaSalle"; the problem is, it looks like both are used interchangeably? The [Circuit Clerk's website](https://lasallecounty.com/) says "LaSalle," but the [.gov website](https://www.lasalle-il.gov/) says "La Salle" in the title, but also uses "LaSalle" within the website.

So my theory is that GeoLocate prefers "LaSalle" and that is why the yellow box is appearing. Would updating the higher geography name to "LaSalle" fix this? Or is the yellow box related to something else entirely?

Thanks!

**Comment by dustymc** [comment]
Oh - and sometimes @mkoo has spatial data for various geography hanging around, there's no UI for adding that at the moment but if someone can scrounge up the data from somewhere I can get it in (and maybe build a UI in the process).
