### ISSUE TITLE
Feature Request - "last edited by" on Agent profile page?

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#4399]
**Is your feature request related to a problem? Please describe.**
Since Agents is a shared table, it would be helpful to know who last edited an agent record, especially if you discover something that is incorrect in an agent related to your collection.

**Describe what you're trying to accomplish** 
Accountability for updates to agent profiles and the ability to retrace the history of edits in order to fix or clarify information.

**Describe the solution you'd like**
On catalog records we see a "last edited by" entry and a hyperlink to the full history of edits for a record. As agent records become more deeply documented and important sources of data, the ability to see the full history of edits is essential to maintaining data accuracy.

**Additional context**
We see who created the agent, but I want more! :-)
<img width="731" alt="Screen Shot 2022-03-05 at 8 39 39 AM" src="https://user-images.githubusercontent.com/17605945/156894508-38d9d530-8c09-43b8-9159-cdf50e1b0111.png">

I think we should be able to see this for the agent entry without having to go to a related catalog record.

<img width="367" alt="Screen Shot 2022-03-05 at 8 46 07 AM" src="https://user-images.githubusercontent.com/17605945/156894431-88bb0ff5-b299-446c-a1bf-dff724e5ca1f.png">

<img width="529" alt="Screen Shot 2022-03-05 at 8 46 30 AM" src="https://user-images.githubusercontent.com/17605945/156894448-09351229-bc53-472f-9af4-e0017dad4619.png">

**Priority**
Normal - but it would be really helpful and ensure better quality data.

**Comment by campmlc** [comment]
Agree, and we should make this a standard practice on all shared tables

**Comment by dustymc** [comment]
I need more information. What are you wanting to log (just username and date or data or ??), and what precisely would trigger a log event?

**Comment by AJLinn** [comment]
> What are you wanting to log

At minimum the user name and date. At maximum, what field was edited by that last user.

> what precisely would trigger a log event

Not sure what our options are?
Maybe:
-  If a new line/field is added (e.g., someone adds an aka, or relationship, address)
- If the preferred name is edited
- If a line/field is deleted

How do the logs work for the catalog record? Is that more/less than what we could have for agents? I don't understand the constraints nor what limitations you're working under so I'd appreciate knowing what is easier and what would create a problem.

**Comment by dustymc** [comment]
>How do the logs work for the catalog record?

Something triggers a change in  FLAT (aka the cache) - there's nothing similar for agents, but they're also (sorta, see below) simpler objects.

>Not sure what our options are?

Realistically, about what you laid out. Ideally (or the opposite!) - declaring some Agent to be/no longer be a {collector_role} of some object could be considered a change, it certainly affects the way people will see the agent going forward. Ditto for any other agent-related object, of which there are very many.

>create a problem

Grabbing username/date for changes to some few mostly-stable tables likely wouldn't be a problem, much beyond that might require more resources of some sort. (And FWIW I'd love to keep everything forever, but reality is even the essentials are often hard to come by.)

https://arctos.database.museum/tblbrowse.cfm?tbl=agent is a good place to see the tables (changes to which would trigger logging). Agents are everywhere, the "core" tables are (mostly-ish) https://arctos.database.museum/tblbrowse.cfm?tbl=agent,  https://arctos.database.museum/tblbrowse.cfm?tbl=address, https://arctos.database.museum/tblbrowse.cfm?tbl=agent_name, https://arctos.database.museum/tblbrowse.cfm?tbl=agent_relations

**Comment by Jegelewicz** [comment]
I would say that any edit to the things that appear on the edit agent page should trigger a "last edited by". Too broad?

**Comment by lin-fred** [comment]
Agent committee discussed:
We are agreeing that it should be anything that is edited, added or deleted needs to trigger a "last edited by"
BUT at this moment we think we can just start with one "last edited by" log

**Comment by dustymc** [comment]
>"last edited by" log

Is "log" meant to imply more than one "last"?

**Comment by lin-fred** [comment]
> > "last edited by" log
> 
> Is "log" meant to imply more than one "last"?

Nope, just one "last"
