### ISSUE TITLE
Arctos Down - 3/6/2022

### ISSUE THREAD

**Issue by keg34** [ArctosDB/arctos#4401]
Please complete to the best of your ability.

## Unplanned Outage
 - Date and time outage discovered: 12pm 3/6/2022
 - Describe the outage (Arctos down or only some part not working?):  Connection is timing out.  Arctos was up about an hour ago.  Now dead in the water.

## Planned Outage
 - Date and time outage will begin:
 - Date and time outage is expected to end:
 - Reason for outage:
 - Expected behavior during and after the outage:

## Communication before/during outage
- [ ] Pin this issue
- [ ] Banner updated @jegelewicz 
- [ ] Email sent to AWG 
- [ ] Email sent to Arctos Google Group 
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @jegelewicz
- [ ] Email sent to AWG 
- [ ] Email sent to Arctos Google Group 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by dustymc** [comment]
bounced
