### ISSUE TITLE
Quarantine Taxon Name - Turdus litsipsirupa

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4402]
The name suggested for quarantine is: [Turdus litsipsirupa](https://arctos.database.museum/name/Turdus%20litsipsirupa)

The reason for quarantine is: see https://github.com/ArctosDB/data-migration/issues/663

> Turdus litsitsirupa is in Arctos as Turdus litsipsirupa. I am pretty sure the spelling should have a "sits" instead of "sips" in the species name.

Also see Wikipedia - https://en.wikipedia.org/wiki/Groundscraper_thrush
GBIF Backbone - https://www.gbif.org/species/9071626

The suggested treatment for all identifications currently using this name is:

Change to Turdus litsitsirupa {Turdus litsipsirupa}

Collections currently using this name in identifications include:

MVZ:Egg - @ccicero 

Also probably need to quarantine:

Turdus litsipsirupa simensis --> Turdus litsitsirupa simensis {Turdus litsipsirupa simensis} MVZ:Bird @ccicero 
Turdus litsipsirupa stierlingi --> Turdus litsitsirupa  stierlingi {Turdus litsipsirupa stierlingi} MVZ:Bird @ccicero 

Priority
Please assign a priority-label.

**Comment by dustymc** [comment]
Let's bring this into the new quarantine system - I'll update IDs and quarantine the name about 2022-04-08 unless someone stops me, or sooner if everyone agrees.

Summary: identifications using the nominated name:

```

 guid_prefix | accepted_id_fg | numberids |                              link_to_records                              |     taxon_name      |                      link_to_taxon                      
-------------+----------------+-----------+---------------------------------------------------------------------------+---------------------+---------------------------------------------------------
 MVZ:Egg     |              0 |         1 | https://arctos.database.museum/SpecimenResults.cfm?taxon_name_id=10008902 | Turdus litsipsirupa | https://arctos.database.museum/name/Turdus litsipsirupa

```

Data Quality Users:


 @mkoo
 @ccicero
