### ISSUE TITLE
Georeferencing Issue

### ISSUE THREAD

**Issue by cefilipek** [ArctosDB/arctos#4406]
I uploaded some files via the bulkloader and I am attempting to georeference them prior to upload into the public facing database. However, the geolocate button is not working. I open the editing page by selecting the id. When I hover over the geolocate button it turns red, but when I click on it nothing happens. There is no suggestion of loading or anything, it is as if I clicked on empty space.

**Comment by dustymc** [comment]
URL or instructions on how to get there, please - I'm not sure what tool you're trying to use.

**Comment by cefilipek** [comment]
I clicked on the collections object ID from the Browse and Edit screen. It pulls up the data entry form and under coordinates I am unable to use the Geolocate button. This is the only way I know how to edit files pre-upload.

Here is the URL to one of my objects.
https://arctos.database.museum/editBulkloader.cfm?collection_object_id=97822364

**Comment by dustymc** [comment]
Thanks, that's what I needed. I'll go next task and high priority.

**Comment by jebrad** [comment]
Having the same problem.  I thought it was just me....
