### ISSUE TITLE
Quarantine Taxon Name - Ursus arctos middendorfi

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4407]
The name suggested for quarantine is: _[Ursus arctos middendorfi](https://arctos.database.museum/name/Ursus%20arctos%20middendorfi)_

The reason for quarantine is: Not a valid spelling. See https://github.com/ArctosDB/data-migration/issues/663#issuecomment-1061336683

The suggested treatment for all identifications currently using this name is: _[Ursus arctos middendorffi](https://arctos.database.museum/name/Ursus%20arctos%20middendorffi)_

Collections currently using this name in identifications include:

MSB:Host @campmlc @jldunnum 
UMNH:Mamm @kderieg322079 
UWYMV:Mamm @ewommack 

Priority
Please assign a priority-label.

**Comment by dustymc** [comment]
Let's bring this into the new quarantine system - I'll update IDs and quarantine the name about 2022-04-08 unless someone stops me, or sooner if everyone agrees.

Summary: identifications using the nominated name:


```
 guid_prefix | accepted_id_fg | numberids |                             link_to_records                              |        taxon_name        |                        link_to_taxon                         
-------------+----------------+-----------+--------------------------------------------------------------------------+--------------------------+--------------------------------------------------------------
 MSB:Host    |              1 |        11 | https://arctos.database.museum/SpecimenResults.cfm?taxon_name_id=3183848 | Ursus arctos middendorfi | https://arctos.database.museum/name/Ursus arctos middendorfi
 UMNH:Mamm   |              1 |         1 | https://arctos.database.museum/SpecimenResults.cfm?taxon_name_id=3183848 | Ursus arctos middendorfi | https://arctos.database.museum/name/Ursus arctos middendorfi
 UWYMV:Mamm  |              1 |         1 | https://arctos.database.museum/SpecimenResults.cfm?taxon_name_id=3183848 | Ursus arctos middendorfi | https://arctos.database.museum/name/Ursus arctos middendorfi

```
Data Quality Users:


 @msbparasites
 @ewommack
 @campmlc
 @kderieg322079

**Comment by ewommack** [comment]
Corrected the UWYMV specimen.

**Comment by Jegelewicz** [comment]
@dustymc automate away?

**Comment by campmlc** [comment]
You can swap all MSB:Host records with this ID for the valid Ursus arctos middendorffi, this was transcription error
