### ISSUE TITLE
Arctos Down - 503 Service not available

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4408]
Please complete to the best of your ability.

## Unplanned Outage
 - Date and time outage discovered: 2022-03-08 3:20 MST
 - Describe the outage (Arctos down or only some part not working?): 503 Service not available

## Planned Outage
 - Date and time outage will begin:
 - Date and time outage is expected to end:
 - Reason for outage:
 - Expected behavior during and after the outage:

## Communication before/during outage
- [x] Pin this issue
- [ ] Banner updated @jegelewicz 
- [ ] Email sent to AWG 
- [ ] Email sent to Arctos Google Group 
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @jegelewicz
- [ ] Email sent to AWG 
- [ ] Email sent to Arctos Google Group 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by lin-fred** [comment]
back up?
