### ISSUE TITLE
Code Table Request - entity ID

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4412]
**Goal**
Make use of Arctos entity records for things other than "organisms"

**Context**
UNM:MET has identifers for named meteorites and could use this functionality

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type

**Proposed Value**
entity ID

**Proposed Definition**
Identifier representing an entity or individual other than a DWC:Organism, generally one comprised of multiple catalog records. Preferably a globally unique identifier or url.

**Available for Public View**
Yes

**Priority**
[  Please choose a priority-label to the right.  ]

**Comment by campmlc** [comment]
I support this. The only concern I have is the potential confusion as to
whether biological collections should use this vs organism ID. I can see
both being used. Perhaps entity ID is the overarching term, and organism ID
is one type of entity? Or we add "entity type=organism" as ID metadata?

**Comment by Jegelewicz** [comment]
If I was doing this from scratch, I would get rid of organism ID and replace it with entity ID, then biological collections would map this to DwC:organismId and others could map it to whatever in their exchange standards.

Maybe this is what we should do?

**Comment by Jegelewicz** [comment]
**Goal**
Make use of "entity" identifier for meteorites

**Context**
UNM:MET has identifiers for named meteorites from MBDB and could use this functionality

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type

**Proposed Value**
MBDB: Meteoritical Bulletin Database

**Proposed Definition**
Identifier assigned by the Meteoritical Bulletin Database (MBDB)

**Other ID BaseURL**

"Base URL" with which to prepend entered values, - https://www.lpi.usra.edu/meteor/metbull.php?code=

and

A functional example URL, which should consist of the base URL provided in (1) plus a relevant value. https://www.lpi.usra.edu/meteor/metbull.php?code=23166

**Available for Public View**
Yes

**Priority**
[  Please choose a priority-label to the right.  ]
