### ISSUE TITLE
Barcode Series Request - need barcode for MVZ institution

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#4413]
'Museum of Vertebrate Zoology' exists as an institution but doesn't have its own barcode (legacy issue). We are creating new barcodes for rooms in MVZ, and need to move them into the institution. They are currently floating in the universe. Can you please add the barcode 'MVZ' to this institution container so that we can assign rooms properly? @mkoo and I need this for current archival work.

![image](https://user-images.githubusercontent.com/967275/157735940-81785181-d924-4745-a8cb-36bba61fe4a9.png)

**Comment by dustymc** [comment]
You need to claim the barcode (maybe as part of whatever series you're using for rooms) before it can be used - https://arctos.database.museum/info/barcodeseries.cfm?barcode=MVZ

**Comment by ccicero** [comment]
OK. Done, thanks!
