### ISSUE TITLE
container bulkloader - confirm access checks

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#4415]
# Error Text
oad fail::ERROR: triggercaught:::Changing barcode is not allowed Where: PL/pgSQL function trigger_fct_trg_container_content_control() line 214 at RAISE

# Where it happened
[create containers the non-evil way](https://arctos.database.museum/tools/create_container.cfm?action=table&username=mkoo&status=)

Might have to resort to "evil method" (one-by-one) since that method works!

The error implies I am trying to change barcodes -- they exist (we just made them today and they are the same in the CSV) so what do I have to change in the CSV to autoload?

PS. FYI, @Jegelewicz We are documenting (@ccicero @mkoo) this whole process since we need it!

**Comment by Jegelewicz** [comment]
Put yur data here too - it will help @dustymc

**Comment by dustymc** [comment]
Patched, I loaded 3101 VLSB to confirm.

You might want to have a look at https://handbook.arctosdb.org/documentation/container.html#guidelines-for-barcode-containing-labels regarding the gaps.

Need to beef up the pre-check until we can get some sort of better authentication; please leave this open until I can do that.
