### ISSUE TITLE
Feature Request - New Data Entry Form Identification panel(s) and Sensu Publication

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#4416]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

Just learning the new data entry form and was excited to see that with a little customization we can now enter more than one identification for a record. It is common that older specimens have taxon names that are no longer valid so in theory this will allow us to enter the older invalid name and the new valid name at the same time during data entry (rather than using the remarks for the older name, or finding the records after loading into arctos and adding new IDs to them then).

However, when exploring this new functionality I found some problems:

1) If I add the 'extras' for identification this allows the addition of SENSU PUBLICATION (and taxon concepts) - great! But the other default Identification panel _does not have these fields._ Thus, if I have a specimen with a single ID and I want to add Sensu Publication, I need to use the 2nd 'extras' panel... and leave the default panel blank. However, doing so causes an error upon save.  One cannot apparently leave the default Identification blank. If this is so, then please add the Sensu publication and taxon concept etc to the default identification panel. Or allow the default identification panel to be left blank and if the 'extras' panel is filled in, then it becomes the only identification for that record.

2) The sensu publication should behave as it does when adding these to already loaded records - a popup should appear after hitting tab providing a list of publication record matches to the search term put in the field (like linking an ID to a taxon name, or higher geography, or agent etc). Currently there is no popup and thus it seems the only way to use this field would be to know in advance the exact spelling of the citation / publication one wants to use. This is not ideal for obvious reasons. Presumably taxon concept suffers from the same problem but I did not explore that.

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.
high

**Comment by dustymc** [comment]
This requires adding columns to the core record loader table; drop and rebuild the table for better ordering, get https://github.com/ArctosDB/arctos/issues/4716#issuecomment-1138817127 (and whatever else might be jumbled) at the same time.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/5193
