### ISSUE TITLE
I need to change zero coordinate error to null

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4418]
**Is your feature request related to a problem? Please describe.**

Errors of 0.5 meters or less results in empty polygon geography; postgis seems to have a lower limit on ``geography`` data size for some reason. 

**Describe what you're trying to accomplish** 

Clean up and prevent nonsensical data.

**Describe the solution you'd like**

1. Update all localities with sub-half-meter error to NULL error.
2. Create a check to disallow such data going forward.

**Describe alternatives you've considered**

Let impossible/improbably data prevent access to spatial tools.

**Additional context**

Almost all of these are 0 meters error, which at some point was an acceptable way of saying 'we don't have that information.' NULL is now acceptable, and cannot be confused with "infinitely precise." The rest are -999M error used by MSB:Herp, which is almost certainly another way of saying "we don't know." @jtgiermakowski 

If we come to need to record legitimate <0.5M error, the check is easy to adjust. Hopefully postgis will be capable of smaller polygons by then; if not, we can find a way to fake it.

**Priority**

Unless there's some compelling reason not to update these to NULL, I'll do so when https://github.com/ArctosDB/arctos/issues/4259 goes to production, hopefully next week.

**Data**

[temp_veryprecise_locality.csv.zip](https://github.com/ArctosDB/arctos/files/8227734/temp_veryprecise_locality.csv.zip)

**Comment by sharpphyl** [comment]
> NULL is now acceptable, and cannot be confused with "infinitely precise."

Didn't know that and it's not in the Handbook.  Can we add it? 

https://handbook.arctosdb.org/how_to/How-to-Edit-Coordinates-and-Max-Error-of-a-Locality.html#using-geolocate

And will GBIF etc. show NULL as the error radius if we use it?  Or should we ask to add UNKNOWN as an option?

**Comment by tucotuco** [comment]
> And will GBIF etc. show NULL as the error radius if we use it? Or should we ask to add UNKNOWN as an option?

NULL is not a value, it is the absence of a value, it is empty. Empty values on GBIF will show up as empty to the human eye (nothing to be seen in the user interface for a value). UNKNOWN is not an option in Darwin Core because the term is coordinateUncertaintyInMeters and expects a number greater than 0.

**Comment by sharpphyl** [comment]
Thanks for the clarification.  We're probably better off putting in some kind of an error even if the size is a judgment call.

**Comment by tucotuco** [comment]
Yep. That radius is a scalar upon which to filter based on specificity. The issue really is that people don't tend to think deeper than points. No location is is "sizeless" and we want an easy way to say "this one may be useful because it is specific enough" or more often, "that one is not useful for me because it is really only know to the continental scale."

**Comment by dustymc** [comment]
>not in the Handbook. Can we add it?

Yes please.

> We're probably better off putting in some kind of an error even if the size is a judgment call.

Absolutely. I'm actually faking one-meter circles, but the technically correct approach would be to not do that, which would mean that no NULL-error points would be accessible to the spatial tools I'm building. In other words, the only really defensible way to interpret NULL error is to make no assumptions: somewhere on the planet, probably. If you have some indication that you are in fact dealing with something smaller than an entire planet, make a guess and support it in georeference method - you've just made your data more useful to to the people who are happy with continent-scale data, but not so much with planet-scale. (And if your guess falls out of some analysis, maybe they'll tell you about it.)
