### ISSUE TITLE
[CONTACT] Create Container Series Access Blocked

### ISSUE THREAD

**Issue by kokkoana27** [ArctosDB/arctos#4419]
Hi,

I logged in this week to find that I no longer have access to several different sections of Object Tracking, mainly "Create Container" and "Create Container Series." My other associate (Alison Whiting) says she has access to these tools and has informed me that I still have the same permissions/access as before. I'm not sure if there's a valid reason for this or if it's some kind of bug - I've tried to locate any issues similar to this problem but I couldn't find any that explained this, so apologies if this has already been addressed by someone else!

Let me know if you need any more specific information! Thanks

**Comment by campmlc** [comment]
Container permissions have changed, see #4084
