### ISSUE TITLE
Create Island Group Khuriya Muriya Islands

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#4420]
Code Table:  Island Group https://arctos.database.museum/info/ctDocumentation.cfm?table=ctisland_group

Goal: Expand Higher Geography

Documentation/Authority:  https://en.wikipedia.org/wiki/Khuriya_Muriya_Islands

**Proposed Value**
Khuriya Muriya Islands

**Proposed Definition**
(from Wikipedia)  A group of five islands in the [Arabian Sea](https://en.wikipedia.org/wiki/Arabian_Sea), 40 km (25 mi) off the southeastern coast of [Oman](https://en.wikipedia.org/wiki/Oman). The islands form part of the [province](https://en.wikipedia.org/wiki/Provinces_of_Oman) of [Shalim and the Hallaniyat Islands](https://en.wikipedia.org/wiki/Shalim_and_the_Hallaniyat_Islands) in the [governorate](https://en.wikipedia.org/wiki/Regions_and_governorates_of_Oman) of [Dhofar](https://en.wikipedia.org/wiki/Dhofar_Governorate).

**Available for Public View**
Yes

**Comment by dustymc** [comment]
I'm still not convinced that ~70 square kilometers constitutes "geography" (https://github.com/ArctosDB/arctos/issues/1278), but I have a functional alternative now. It would still be potentially useful to get some community consensus on what is and isn't geography, even if that's "whatever someone asks for."

**Comment by acdoll** [comment]
Fun fact: The smallest county in the US ([Kalawao County, Hawaii](https://en.wikipedia.org/wiki/Kalawao_County,_Hawaii)) is ~34 sq km. It was created as a leprosy colony and is managed by Maui County, but it's still a county.

**Comment by Jegelewicz** [comment]
As it is, the "island" stuff is a mess. If this will be helpful to DMNS right now I see no reason not to add it.

**Comment by dustymc** [comment]
>no reason not to add it

For clarity: Me either, I'd just like to find a real solution/plan, I keep hoping one of these conversations will spark that....

>managed by Maui County, but it's still a county.

Ain't geography GREAT!

**Comment by sharpphyl** [comment]
> but I have a functional alternative now.

Can you elaborate?

**Comment by dustymc** [comment]
>    functional alternative ... Can you elaborate?

<img width="1255" alt="Screen Shot 2022-03-12 at 8 32 12 AM" src="https://user-images.githubusercontent.com/5720791/158026568-e2f6a382-390d-4a74-b25f-e595f1a606ef.png">

Searching that considers the place-names that I pull in from coordinates; I can find the stuff that MAPS to North Dakota even if you've asserted it's Texas. https://github.com/ArctosDB/arctos/issues/4289 would be a great simplification; it simply wouldn't allow you to assert that something both maps to North Dakota and should be called "Texas," and I therefore wouldn't have to create my own convoluted path to finding things. (You can of course add multiple events if you need to say both, but any one assertion would not be able to contradict itself.)

**Comment by sharpphyl** [comment]
Ok.  I've added my 2 cents to [#4289](https://github.com/ArctosDB/arctos/issues/4289) already.

**Comment by sharpphyl** [comment]
> If this will be helpful to DMNS right now I see no reason not to add it.

Since this discussion (about how small an area should be included at the Higher Geography level) has been going on for years, can we decide whether or not to add Khuriya Muriya Islands as an Island Group this week so we can move the pending catalog record out of the bulkloader?  

Who needs to weigh in on this issue?

**Comment by mkoo** [comment]
Aside from size issues I can add to the Code table -- this isn't a request for new Higher Geography right?!
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctisland_group

But if it is for new HG: "When in doubt, use specific locality" has been my mantra. It's still discoverable (see Dusty's comment above) and in some ways when Higher Geog is really "high" it's easier to manage stuff.
