### ISSUE TITLE
Arctos Down - 503 Error 3/11/22 9:08 PT

### ISSUE THREAD

**Issue by zmsch** [ArctosDB/arctos#4423]
Please complete to the best of your ability.

## Unplanned Outage
 - Date and time outage discovered: 3/11/22 9:08 PT
 - Describe the outage (Arctos down or only some part not working?): 503 Service Not Available Error

## Planned Outage
 - Date and time outage will begin:
 - Date and time outage is expected to end:
 - Reason for outage:
 - Expected behavior during and after the outage:

## Communication before/during outage
- [x] Pin this issue
- [ ] Banner updated @jegelewicz 
- [ ] Email sent to AWG 
- [ ] Email sent to Arctos Google Group 
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @jegelewicz
- [ ] Email sent to AWG 
- [ ] Email sent to Arctos Google Group 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by dustymc** [comment]
bounced
