### ISSUE TITLE
No ascii variant agent notification, but there is a no ascii variant

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4424]
Received this today

[Maria Schönbächler](https://arctos.database.museum/agents.cfm?agent_id=21337105)
   CreatedBy: Teresa J. Mayfield-Meyer
   Problem: no_ascii_variant

But I definitely added an no ascii variant when I created the agent

![image](https://user-images.githubusercontent.com/5725767/157916657-d918ca40-85f5-4caf-9823-ea181bda7bd0.png)

**Comment by AJLinn** [comment]
Does Arctos not understand the modification of the ö to oe and ä to ae?
Did you try the exact same spelling without the diacritics?

**Comment by dustymc** [comment]
>not understand the modification of the ö to oe and ä to ae?

Not at all, see https://handbook.arctosdb.org/best_practices/Agents.html.

``Maria Schonbachler`` will stop the error (and maybe prevent duplicates from being created).

Adding better/alternative transliteration(s) may be useful for people (and help prevent duplicates from being created, so please!).

**Comment by Jegelewicz** [comment]
So I did that, but it feels wrong to make up some name that is meaningless.
