### ISSUE TITLE
lost attribute data in new data entry screen

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#4426]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
student entered data for a mammal using the standard measurement boxes. All looked fine, but the data are not in the bulkloader in the table view. Also, when you open the individual records, the standard mammal boxes are not present, nor are the data. 

On three of the records, it says "No UUID, nothing to check". Is this something we
<img width="667" alt="Screen Shot 2022-03-11 at 11 38 09 AM" src="https://user-images.githubusercontent.com/5749672/157947178-acc05e5e-b5cc-4c85-a59d-d519efebc4a2.png">
 need to worry about?

On one record, there is a bunch of text at the bottom of the screen. The student entered data under an attribute of reproductive data. Did we do something wrong?

This is accession MVZ Mammal 14928. We will wait to try entering the body measurements again until someone can take a look. 

Thanks,

Chris

**To Reproduce**

**Expected behavior**

**Screenshots**

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by dustymc** [comment]
Links would be most useful, but it looks like that was entered as "extras" - see https://handbook.arctosdb.org/documentation/bulkloader.html#processing for handling that.

**Comment by cjconroy** [comment]
No, they were entered in the standard boxes, not the extras at the bottom of the screen. The records are still in the bulkloader in case it helps.

**Comment by dustymc** [comment]
I may be lost, but I'm looking at https://arctos.database.museum/editBulkloader.cfm?collection_object_id=97820656


This:

<img width="515" alt="Screen Shot 2022-03-11 at 11 58 22 AM" src="https://user-images.githubusercontent.com/5720791/157950106-c34db224-2760-4366-ab3d-5a2f47a59e67.png">

was entered as a "standard" attribute, and this:

<img width="550" alt="Screen Shot 2022-03-11 at 11 59 14 AM" src="https://user-images.githubusercontent.com/5720791/157950236-82dc3185-5242-40c7-8e2f-a082e80442c6.png">

was entered as an extra, and is also accessible at https://arctos.database.museum/tools/BulkloadAttributes.cfm?action=table&UUID=EE006A16-6D09-40EC-8C755AA08173C3BF via the [OPEN](https://arctos.database.museum/tools/BulkloadAttributes.cfm?uuid=EE006A16-6D09-40EC-8C755AA08173C3BF) link.

**Comment by cjconroy** [comment]
OK, we see now that this repro data was entered as extra. Going to try adding in other box. However, what happened to total length, tail, hf, ear and weight, attributes 1-5? They were entered in the standard boxes

**Comment by dustymc** [comment]
I need a pre-save screenshot or something, I can't 100% rule out some sort of bug but one that saves only one attribute seems unlikely.

**Comment by cjconroy** [comment]
Our student just changed her options so that she can see all attributes. Previously they were had status 'hide', except attribute one, sex. Seems that in that mode the values from the standard mammal boxes did not make it to the large table because of this. Just tested with new data. We will re-enter them. That seems like a bug. If the standard mammal measures are up, then they should default to 'show'.

**Comment by dustymc** [comment]
Ah, thanks, got it. I'll add some documentation.
