### ISSUE TITLE
Feature Request - notifications

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4427]
**Is your feature request related to a problem? Please describe.**

Notifications are currently strictly email - they go out (or not), the intended user gets them (or not), sees them (or not), acts on them (or not), ....

**Describe what you're trying to accomplish** 

Make notifications more persistent, accessible, manageable, etc.

**Describe the solution you'd like**

Immediately: Write notifications to the database, email from that rather than directly.

Maybe/eventually: do something more - build a UI, show notifications at login, whatever.

**Describe alternatives you've considered**

Do nothing.

**Additional context**

https://github.com/ArctosDB/arctos/issues/4259 / https://github.com/ArctosDB/arctos/issues/3530 is going to add at least one more notification; significant growth seems inevitable.

The email server is often overworked; this would provide a mechanism for a "digest" format, which would greatly reduce the number of emails Arctos is required to send and the number users need to deal with.

**Priority**

High? Suggest we get in front of this before it turns into some sort of crisis. Tentatively going next task; feel free to recategorize if this is dumb.

**Comment by dustymc** [comment]
This is running in test and will be in the next release, testing greatly appreciated.

I'm leaving this issue open. Please use this for any notification-related requests/problems/questions.

There's a sorta-email-like UI with which notifications can be managed. It's accessible with a dedicated menu tab.

The [Locality/Geography report](https://arctos.database.museum/Reports/locality_georaphy.cfm) will initially be using this mechanism.

I'll let this run a few days in case there are problems, then begin rounding up everything that sends email and piping it through the notification mechanism.

My current intent is to send one email per day to active users with unread notifications, rather than the many and various emails Arctos currently sends (or tries to). There is lots of flexibility in that, so please let me know here ASAP if that's not the preferred approach.

One somewhat unanticipated feature is that this mechanism provides a means by which I can deliver notifications to users who wouldn't normally get them - those with locked accounts or no valid email address. Those users will continue to **not** receive email, but when they log in any notifications will be available to them.

**Comment by Jegelewicz** [comment]
> send one email per day

!!! How about one per week?

> Those users will continue to not receive email, but when they log in any notifications will be available to them.

Available, yes. Reviewed, unlikely. 

As much as I hate it, I think that at some point we may want anyone who has unread notifications to get the same red box that I get every time I log in, 

![image](https://user-images.githubusercontent.com/5725767/159783643-7bf6b43c-7d49-4e4c-afbd-0bc2c730d2cd.png)

but that says something like

> You have un-read notifications

But also, what the heck is this?

![image](https://user-images.githubusercontent.com/5725767/159783827-cce00f01-c1db-4671-9d96-ab14a269e6a9.png)

**Comment by cjconroy** [comment]
For MVZ mammals that I just looked at, it appears that the does not contain means that the center point is in the higher geography, but some part of the error radius lies outside the higher geography. MVZ Mammals has thousands of these.

**Comment by Jegelewicz** [comment]
OOF - that sounds like a huge pain.

**Comment by Jegelewicz** [comment]
> the center point is in the higher geography, but some part of the error radius lies outside the higher geography

I've said this before - this should not trigger a notification. It ends up making unnecessary work and means that a bunch of us just ignore notifications.

**Comment by dustymc** [comment]
>one per week?

No problem for me, not what I expect most/many users to want though. Maybe the schedules could be adjusted to accommodate - I don't want anyone to have a week less notice about expiring permits, but maybe a possible week more notice is all it takes to compensate.

A 'schedule your email' option isn't entirely out of scope, might even be relatively straightforward. Even a "schedule particular emails" is probably-mostly-plausible, although that's almost certainly in nontrivial territory.

>Reviewed, unlikely.

I'm trying to make very sure we horses actually know where the water is. Whether any of us actually drink isn't Arctos' problem.

>same red box

That's where this started - users only see that once per login and probably learn to ignore it. The tab is always there; I think it's the right combination of "most visible, least intrusive."

>what the heck is this?

Click that link, you'll get a report, it links to https://github.com/ArctosDB/arctos/issues/4289. @cjconroy got it - I don't think you can defensibly say something that explicitly claims to be maybe from Wyoming is in Utah, but i also don't think we have much chance of doing anything about that right now so there's just a "this might not be perfect, maybe fix" flag.

**Comment by cjconroy** [comment]
MVZ Mammals has 2225 does not intersect and 25463 does not contain. I will be getting notifications till longer after I am dead. But, send the notifications anyway!

**Comment by campmlc** [comment]
But please no permanent red boxes on login .  . . that just requires an
extra click on login and teaches people to ignore red boxes. And we will
all have permanent red boxes if they are triggered by unread locality
notifications.

**Comment by Jegelewicz** [comment]
Suggest stopping email for now - we have the opportunity to check this stuff from the menu now.

**Comment by dustymc** [comment]
Most Arctos events should now be going through notifications.

Long messages aren't great in the UI, need to change at least

* task status needs a UI and a shorter notification message
* collection report has a UI, notification message needs shortened

**Comment by dustymc** [comment]
Also - there are new options in global settings, add your username or let me know if you'd like taxonomy, agent, or general notifications.

**Comment by dustymc** [comment]
Need to show timestamp as date for better sorting

**Comment by dustymc** [comment]
TODO: round up the stuff that ends up in TSR, reroute it to notifications

**Comment by sharpphyl** [comment]
So if I DELETE a notification that goes to multiple users, what happens?  Does it take my name off the distribution or actually delete the notification for everyone.  Does it delete the notification for (the three) others who get them for the same collection DMNS:Inv so they know they've been taken care of?  Clicking "read" seems to only gray out the notification and keep it in the queue which implied that I need to delete it but can't find any instructions to confirm this.  I can't find any documentation on notification management in the handbook or tutorial bites.  

If we get notifications every day, what can't they be updated every day.  The locality/geography problem notification hasn't been updated since 2022-03-23/21:54 so it doesn't show if progress is being made.

Overall, this is a much better approach, but is there a menu item that links to the notification page?  I don't find one under Reports.

**Comment by dustymc** [comment]
Some of this is in https://github.com/ArctosDB/arctos/issues/4500, but...

> DELETE a notification that goes to multiple users, what happens?

You just delete the "you link" - you can't currently do anything for anyone else. (I'll clean up in some way at some point, but the "core" is never getting deleted at the moment.)

> Clicking "read" seems to only gray out t

Yep, status currently just looks different and provides a means to search.

>If we get notifications every day, what can't they be updated every day.

Not sure I understand, but there are two schedules in play.

1. You get periodic notifications about data problems/events/etc. detected when those run - daily for loans, monthly (or something) for locality problems, etc.
2. You get daily "notification notifications" if you have unread notifications, no matter when those might have been send.

> is there a menu item 

<img width="1358" alt="Screen Shot 2022-04-11 at 4 01 29 PM" src="https://user-images.githubusercontent.com/5720791/162846965-8416e902-cf2a-481d-a2b1-5543b1ce268b.png">

**Comment by sharpphyl** [comment]
That answers my questions.  

> is there a menu item'

<img width="200" alt="Screen Shot 2022-04-11 at 7 29 34 PM" src="https://user-images.githubusercontent.com/15368365/162860535-f0cfe1b3-8c61-440f-add6-1485a8e36f16.png">
Duh!  Thanks!

**Comment by dustymc** [comment]
closing, I think this has served its purpose
