### ISSUE TITLE
Feature Request - upper limit on locality precision

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4429]
**Is your feature request related to a problem? Please describe.**

Opposite https://github.com/ArctosDB/arctos/issues/4418, a few hundred localities have error greater than 2000000 meters.

**Describe what you're trying to accomplish** 

1. Confine things to the planet.
2. Maybe do even better - perhaps a smaller maximum error (1000 kilometers??) would be equally functional and "cleaner."

Note that "we have no idea, so NULL" and "we have no idea, so everything" are functionally identical. I don't think it's necessary to allow whole-planet errors.
 
**Describe the solution you'd like**

Add an upper limit to locality error. Next release will have a tentative 2000000 meter limit, but it would be good to do better, maybe write some documentation, etc.

**Describe alternatives you've considered**

Break spatial tools with funky data.

**Additional context**

https://github.com/ArctosDB/arctos/issues/4289 would prevent many of these. E.g. https://arctos.database.museum/place.cfm?action=detail&locality_id=11027739 claims to be from a sub-planet-sized county in a sub-planet-sized state in a sub-planet-sized country, but has error that wraps around the planet a few times.

**Additional additional context**

Data:

[temp_lotsa_err.csv.zip](https://github.com/ArctosDB/arctos/files/8236391/temp_lotsa_err.csv.zip)

Summary:

```

 guid_prefix |  c  
-------------+-----
 ASNHC:Bird  |   4
 BYU:Mamm    |   5
 CHAS:Bird   |  25
 CHAS:EH     |   5
 CHAS:Ento   |   1
 CHAS:Inv    |   3
 CHAS:Teach  |   6
 DMNS:Bird   |   3
 DMNS:Inv    |   3
 JSNM:Egg    |   1
 MSB:Herp    | 972
 MSB:Mamm    |  80
 MVZ:Bird    |  67
 MVZ:Egg     |   1
 MVZ:Herp    |  29
 MVZ:Mamm    | 113
 UAM:EH      | 101
 UAM:Mamm    |  53
 UCM:Bird    |   2
 UCM:Herp    |   5
 UMZM:Bird   |   1
 UTEP:Herp   |   2
 UWBM:Mamm   |  92
 UWYMV:Bird  |   1
 UWYMV:Herp  |   1
```

data quality contacts:

 @amgunderson
 @jldunnum
 @campmlc
 @jtgiermakowski
 @adhornsby
 @ccicero
 @mkoo
 @cjconroy
 @atrox10
 @jebrad
 @ewommack
 @mvzhuang
 @AJLinn
 @acdoll
 @crcarter00
 @sharpphyl
 @SerinaBrady
 @ebraker
 @droberts49
 @wellerjes
 @cefilipek

**Priority**

Normal, unless the limit in next release is problematic.

**Comment by dustymc** [comment]
See https://github.com/ArctosDB/arctos/issues/4259#issuecomment-1065888694, if we do choose a smaller upper limit it need to accommodate things like the Peru-Chile trench [https://en.wikipedia.org/wiki/Peru–Chile_Trench](https://en.wikipedia.org/wiki/Peru%E2%80%93Chile_Trench) which is 5,900 km long (or maybe that's "geography"??). A 10KKM radius would easily do so without allowing unrealistic data.

**Comment by sharpphyl** [comment]
How do we approach localities on this list that are in use by multiple collections?  See 11025592

<img width="391" alt="Screen Shot 2022-03-12 at 8 53 08 AM" src="https://user-images.githubusercontent.com/15368365/158025128-f526f18e-cc17-4637-a0a5-3dc549573c2c.png">


<img width="421" alt="Screen Shot 2022-03-12 at 8 55 31 AM" src="https://user-images.githubusercontent.com/15368365/158025146-ff8e1a97-3064-4d47-8aca-5283da828253.png">

Can you get AWG agreement to not geolocate continents?

**Comment by dustymc** [comment]
>How do we approach localities on this list that are in use by multiple collections? 

Make them better! A polygon could be used to exclude a lot of ocean from that assertion.

>AWG agreement to not geolocate continents?

Why not? I have no problem with continents (oceans, whatever) being georeferenced, I'm just trying to stop the nonsense. We do not need error that wraps around the planet multiple times. We **may** not need error that encompasses the entire planet; that part is what I'm hoping to get feedback on. 

That particular example is ~4KKM, well under my currently-proposed limit of 10KKM.

**Comment by sharpphyl** [comment]
> That particular example is ~4KKM, well under my currently-proposed limit of 10KKM.

But it was on [temp_lotsa_err.csv.zip](https://github.com/ArctosDB/arctos/files/8236391/temp_lotsa_err.csv.zip)

**Comment by dustymc** [comment]
>But it was on temp_lotsa_err.csv.zip

Ah, got it. I apparently picked an inappropriate filter - 2000000 meters seems to be well within what we need to allow. I can rerun the scripts if a better number solidifies.

**Comment by dustymc** [comment]
I now have a number; I'm elevating priority and moving this to AWG discussion in case it can't be resolved otherwise.

The comparison used by spatial query (draw a polygon on the google map) fails for localities with an error radius greater than 5924000 meters.

If we can limit error to that number then I should be able to simply make the comparison, everything's fast, and the results should be accurate.

If we cannot then I have to make a slow check before the comparison, and the results will exclude anything which fails that check.

I therefore propose to:

1. append the existing error to locality remarks as "Original error given as {error distance} {error units}"
2. Change these localities to have 5924000 meter error.


Here's revised data:

[temp_lotsa_err(1).csv.zip](https://github.com/ArctosDB/arctos/files/8247919/temp_lotsa_err.1.csv.zip)

A summary:

```

 guid_prefix | verificationstatus |  c  
-------------+--------------------+-----
 MSB:Herp    | unverified         | 791
 MVZ:Herp    | unaccepted         |   1
 UAM:Mamm    | unaccepted         |  37
 UTEP:Herp   | unverified         |   1
 UWBM:Mamm   | unverified         |  90


```

And involved contacts:


 @amgunderson
 @jtgiermakowski
 @mkoo
 @atrox10
 @jebrad
 @mvzhuang

For scale, here is what Error: 5924000 m looks like on a map:

<img width="697" alt="Screen Shot 2022-03-14 at 12 21 26 PM" src="https://user-images.githubusercontent.com/5720791/158245499-6f083d09-3c07-4aec-ac94-90b5a367786b.png">

Help!

**Comment by dustymc** [comment]
Plan B: I don't want our first impressions in spatial land to be bad, it will be if the checks are on, and I can un-do anything I'm about to do after it's discussed if there's a reason to. I'll pull full locality data, leave it here, and make the changes I suggested when this goes to production, maybe as early as tonight, if nobody stops me.

**Comment by dustymc** [comment]
[temp_veryimprecise_locality.csv.zip](https://github.com/ArctosDB/arctos/files/8249279/temp_veryimprecise_locality.csv.zip)
