### ISSUE TITLE
Request: Add the ability to bulk create positions at the same time as create or bulk edit container.

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4434]
Request: Add the ability to bulk create positions at the same time as create or bulk edit container.  
Problem: I am now using bulk edit container to turn container labels into freezer boxes with positions since my students no longer have access to do so. But once I create a bazillion freezer boxes in bulk, I still have to go to each one and create positions manually one at a time. And my students can't do this anymore one at a time as they use the boxes.
The tool should work so that the positions are automatically created, requiring no second step. Since it now requires admin_container role to bulk create containers, this should restrict access enough that I should hopefully know what I am doing.
@dustymc

_Originally posted by @campmlc in https://github.com/ArctosDB/arctos/issues/3632#issuecomment-1067323681_

**Comment by Jegelewicz** [comment]
This seems like a reasonable ask and she is correct that anyone doing this action should know what they are doing. It does seem like a way of bulk removing positions would be useful as well, so that a person could clean up their own messes?

**Comment by acdoll** [comment]
I support this!

**Comment by dustymc** [comment]
try with edit loader - might need dedicated loader to specify position dimensions

**Comment by campmlc** [comment]
Just checking back in on this? I have created the following freezer boxes, but now need to create the positions one at a time. I need to spend a day barcoding and creating freezer boxes on a large scale - and I don't want to create positions one at a time. Help?
DGR11643
DGR11644
DGR11645
DGR11646
DGR11647
DGR11648
DGR11649
DGR11650
DGR11651
DGR11652

**Comment by Jegelewicz** [comment]
What is your formula for positions? I can create them for you for now.

**Comment by campmlc** [comment]
That doesn't solve my problem when I want to create 100 or more boxes in
the near future. I used to be able to let the students create positions as
they pulled each box for use, but we have removed permissions for students
to create positions. Which means, now I have to click on each box one at a
time. There has got to be a way to do this in bulk.

**Comment by Jegelewicz** [comment]
There probs is, but @dustymc needs time to create and test it. I am happy to help you out with this batch if you want!

**Comment by campmlc** [comment]
I can do this rack of boxes. But I'm increasingly losing the ability to do
my job with the available tools - I run up against dead ends everywhere
I turn. If we can't implement this tool in a timely manner, then we need to
undo the restrictions on students creating positions.

**Comment by Jegelewicz** [comment]
This needs discussed in AWG on Thursday.

**Comment by campmlc** [comment]
While I'm requesting, since I have to do this one at a time, can I request changes to the layout of the page to create positions? I not only have to enter each box barcode into Find Container, click the box, click Positions, but then on the create positions page I have to scroll down through a lot of junk to get to the info on the position dimensions and the button to create positions. Can we move this latter to the top of the page? And saying that we have to scroll down through all that stuff no one reads is not going to happen.
his container is a freezer box

The positions you are about to create can hold cryovial

Do not proceed without careful review; the action of this form is difficult to un-do.

New Position Width
1.2
New Position Length
1.2
New Position Height
4.9

**Comment by campmlc** [comment]
I left the last one undone so you can see what I am having to go through. The position dimensions for cryovials in this case at least autofill.
DGR11652

**Comment by Jegelewicz** [comment]
I think the junk can be informative, but maybe we can "columnize" the page and put it to the right of the form. It's probably more useful that way anyhow.

**Comment by campmlc** [comment]
Anything to avoid yet another scroll down, please!

**Comment by dustymc** [comment]
> junk can be informative

Yes, it's critical, spending 10 seconds reading it can save many hours of less-than-fun work.

**Comment by Jegelewicz** [comment]
@dustymc can we arrange the page so it looks like this?
![image](https://user-images.githubusercontent.com/5725767/165403445-a21dc5e9-4609-406d-8f09-f671472c54b4.png)

**Comment by dustymc** [comment]
yes but new issue please

**Comment by dustymc** [comment]
If you mean shuffling the page, yes of course.

**Comment by Jegelewicz** [comment]
Just committed clunky column creation - will wait to see if it works.
