### ISSUE TITLE
Add label field to all bulkloaders that have a column for barcode

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4436]
Request: Add label field to any bulkload tool that asks for barcode, and allow this tool to update the label value.
Why: I would like to be able to add a label value when I bulkload parts or add a part to a container, so I don't have to go do a separate bulkload. This would cut my workflow time in half.
Tools that need label fields added:
https://arctos.database.museum/tools/BulkloadParts.cfm?action=ld
https://arctos.database.museum/tools/BulkloadPartContainer.cfm?action=ld

**Comment by campmlc** [comment]
This request is to make label and barcode fields consistent across all
tools. I think that would contribute to simplification, rather than
increasing complexity. This is would be adding a single column. I strongly
urge implementation.

**Comment by Jegelewicz** [comment]
Discussed in Object tracking - adding the label creation/edit here puts conflicting permissions on the form. We discussed the creation of automated-ish workflows to help ensure all steps get completed in a complex task. Perhaps a new Github Repo for creating workflow issues/projects? Some other method for doing this?
