### ISSUE TITLE
Error on data entry using Polygon for geolocate

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#4437]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
We attempted to save a new catalog record on which we had used a polygon as the spatial data type

![IMG-3959](https://user-images.githubusercontent.com/15368365/158418779-888b8d8e-8c78-4bda-86f4-b25258aa8715.jpg)

This is the error message

![IMG-3958](https://user-images.githubusercontent.com/15368365/158418851-b8e6a460-9067-449e-81aa-d414deb7d8bd.jpg)

**To Reproduce**

Select Polygon.  Create polygon. Save to record. Save locality.  Try to save as a new record

We didn't expect to see any error or coordinates as those are from the polygon per [4259](https://github.com/ArctosDB/arctos/issues/4259)

Is this a bug or do we need to do something differently during data entry?  We haven't had any problems switching from point-radius to polygon in existing records.  This is the first time we've tried it during data entry.

**Comment by dustymc** [comment]
Data entry cannot handle polygon data. You can pre-create localities and use the ID.

**Comment by sharpphyl** [comment]
Not as productive, but we'll try.  Thanks for the quick feedback.
