### ISSUE TITLE
Make summarize results more useful by turning off aspect excel cannot handle (links to records)

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#4439]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

Trying to get a summary of all Families in Orders from Alaska and excel cannot handle the csv links when they involve too many records.

A solution is to allow users to not include links to specimen records in summarize results

Trying to get this:

Diptera	Carnidae
Diptera	Cecidomyiidae
Diptera	Ceratopogonidae
Diptera	Chamaemyiidae
Diptera	Chaoboridae
Diptera    Chironomidae
Diptera	Chloropidae

and I get this

Diptera	Carnidae
Diptera	Cecidomyiidae
Diptera	Ceratopogonidae
Diptera	Chamaemyiidae
Diptera	Chaoboridae
	
28804082	22851538... which continues for hundreds or sometimes many thousands of numbers with the family name at the end
Diptera	Chloropidae

See attached download 

**Expected behavior**

Asking for a list of names, get a list of names, not including links.
Users should be able to work around this problem by unclicking the options for links to records in the summary results.

To be clear. Here is what the output looks like in csv (for a taxon with only 1 record so it is well behaved):

"https://arctos.database.museum/SpecimenResults.cfm?collection_object_id=24554106","1","Decapoda","Astacidae"

and here is what I would like it to look like:

"1","Decapoda","Astacidae"

**Priority**
High
[ArctosSpecimenSummary013075(1).csv.zip](https://github.com/ArctosDB/arctos/files/8258303/ArctosSpecimenSummary013075.1.csv.zip)

**Comment by dustymc** [comment]
Next release will have a new tool link:

<img width="603" alt="Screenshot 2022-12-14 at 9 11 05 AM" src="https://user-images.githubusercontent.com/5720791/207661816-bb83302f-217a-42e9-b34b-67d96474fc60.png">

to a new interactive summarize form in which you can turn whatever you want, however far it might be from the things I might anticipate, on or off as you wish.

<img width="291" alt="Screenshot 2022-12-14 at 9 12 47 AM" src="https://user-images.githubusercontent.com/5720791/207662175-7bc0988d-f527-46bb-a356-46897776f8d0.png">

You can also build links which probably-nothing, including Arctos, can handle, and probably melt your browser (although mine seems happy enough to do whatever I ask of ~100K records with ~a dozen columns).

<img width="291" alt="Screenshot 2022-12-14 at 9 13 37 AM" src="https://user-images.githubusercontent.com/5720791/207662469-ba572a3d-9b17-4085-9403-8bb5c88f4a97.png">
