### ISSUE TITLE
Problem with Parts Bulkloader?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4440]
Problem: Tried to bulkload the attached file using the part bulkload component loader, using NK as the identifier. I've done this for other records and it worked. But for these remaining, I get the message that the catalog record is not resolved.
However, if I do a catalog record search on the NK numbers, 5 of these show up in search results. 
Why can I find 5 records through search but the parts bulkloader can't resolve them? I don't see that there are duplicate identifiers.

[bulkloadPartsData (4).zip](https://github.com/ArctosDB/arctos/files/8263618/bulkloadPartsData.4.zip)

https://arctos.database.museum/saved/Solomon%20malaria%20slide%20part%20bulkload%20not%20resolved

**Comment by dustymc** [comment]
I'm not sure what I'm supposed to be looking for - your saved search comes back as one MVZ bird (via collector number), I checked a couple from the loader and they don't seem to exist as you've specified. One full example might work.

**Comment by campmlc** [comment]
Here's one of them: https://arctos.database.museum/guid/MSB:Bird:55593

**Comment by campmlc** [comment]
Odd - that search works for me? 
https://arctos.database.museum/saved/Solomon%20malaria%20slide%20part%20bulkload%20not%20resolved

**Comment by dustymc** [comment]
arctosprod@arctos>> select * from coll_obj_other_id_num where other_id_type='NK' and display_value='280236';
 collection_object_id | other_id_type | other_id_prefix | other_id_number | other_id_suffix | display_value | coll_obj_other_id_num_id | id_references | tempref 
----------------------+---------------+-----------------+-----------------+-----------------+---------------+--------------------------+---------------+---------
             28386356 | NK            |                 |          280236 |                 | 280236        |                 15362682 | self          | 
             28307062 | NK            |                 |          280236 |                 | 280236        |                 15305109 | self          | 

https://arctos.database.museum/guid/MSB:Bird:60175

**Comment by campmlc** [comment]
Gotcha - I'll go look at each one again. These are all handwritten numbers subsequently transcribed- yet another reason for barcodes.
