### ISSUE TITLE
Quarantine Taxon Name - Platyrrhinus brachycephallus

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4441]
Issue Documentation is at http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

Name Quarantine Documentation is at https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxon_name_type

Information requested | Response 
 -- | -- 
Name suggested for quarantine | **[Platyrrhinus brachycephallus](https://arctos.database.museum/name/Platyrrhinus%20brachycephallus)**
Reason for quarantine | **misspelling**
Suggested treatment for all identifications currently using this name | **[Platyrrhinus brachycephalus](https://arctos.database.museum/name/Platyrrhinus%20brachycephalus)**
Collections currently using this name in identifications | MSB:Mamm
Collection contacts for above | @jldunnum @campmlc 

This name will be quarantined and existing identifications changed to the suggested treatment following the next Arctos Working Group Issues meeting unless comments here suggest this should not happen or everyone affected agrees to the change before then.

Please add this issue to the Taxonomy Committee Project.

**Comment by Jegelewicz** [comment]
Relationship of potential alternate spelling has been added to [Platyrrhinus brachycephallus](https://arctos.database.museum/name/Platyrrhinus%20brachycephallus)

**Comment by Jegelewicz** [comment]
@dustymc can we "automate" this one?

**Comment by dustymc** [comment]
[temp_taxon_quarantine_reloader(10).csv.zip](https://github.com/ArctosDB/arctos/files/8789919/temp_taxon_quarantine_reloader.10.csv.zip)
