### ISSUE TITLE
Code Table Request - new taxonomy source = Arctos Rocks

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4446]
**Goal**
Keep rock classifications separate from biological classifications

**Context**
I was going to put all of the meteorite classifications into the Arctos source until I discovered this

![image](https://user-images.githubusercontent.com/5725767/158690215-68fec2f2-7be7-499b-86b3-c8ab3168c920.png)

The mineral taxonomy sources we have in place are very specific to minerals and do not include "rocks" and I don't want to mess with those because they come from very specific sources.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxonomy_source

**Proposed Value**
Arctos Rocks

**Proposed Definition**
Classifications assigned to naturally-occurring solid aggregates of one or more minerals, mineraloids or, in some cases, organic materials.

**Priority**
[  Please choose a priority-label to the right.  ]

**Comment by Jegelewicz** [comment]
@Nicole-Ridgwell-NMMNHS @beth3ha let me know if this makes sense. Meteorite classifications in Mindat fall under "Rock".

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I definitely agree a new source is needed. @beth3ha do you all use any particular classification scheme?

**Comment by Jegelewicz** [comment]
@Nicole-Ridgwell-NMMNHS I am using the classifications found in Mindat for the UNM meteorites that @beth3ha will manage.

**Comment by Jegelewicz** [comment]
Taxonomy Committee says this is OK

**Comment by Jegelewicz** [comment]
@dustymc any objections?

**Comment by dustymc** [comment]
>objections

To "Arctos Rocks"? Unpossible!

**Comment by Jegelewicz** [comment]
added
