### ISSUE TITLE
cannot get to report for a loan

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#4449]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I've created loan 9208 for MVZ Mammals. When I go to print reports I get the attached error. 

**To Reproduce**
go to loan 9208, try to go to Print Any Report. Error occurs after hitting the weird link to the reporter. 

**Expected behavior**
list of reports

**Screenshots**
attached.

**Priority**
High. Can't do job. 
<img width="901" alt="Screen Shot 2022-03-17 at 12 49 32 PM" src="https://user-images.githubusercontent.com/5749672/158884181-6079f05d-7f8b-435b-9671-46e70eb552bc.png">

**Comment by dustymc** [comment]
The report server is up and seems happy. This is usually caused by too many tabs open, authentication has to happen in a linear fashion.

**Comment by cjconroy** [comment]
too  many tabs on MY computer?  How many is too many?
