### ISSUE TITLE
Code Table Request - New other ID = NOAA: National Oceanic and Atmospheric Administration

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#4450]
**Context**
Numbers specific to NOAA - e.g., assigned to NOAA permitted specimens

**Table**
coll_other_id_type

**Proposed Value**
NOAA: National Oceanic and Atmospheric Administration

**Proposed Definition**
Identifier assigned by the National Oceanic and Atmospheric Administration

**Collection type**
Mamm, Bird, Fish, Amph, Herp, Mala, Rept, Zoo, Vert, Env

**Available for Public View**
yes

**Priority**
Normal

**Comment by Jegelewicz** [comment]
Code table committee says do this.

BUT are we sure that NOAA only issues one identifier? @acdoll

**Comment by acdoll** [comment]
No, not sure. Let me look into it a bit further...

**Comment by acdoll** [comment]
This was the text in a letter that authorized our possession of a recently acquired specimen:
![image](https://user-images.githubusercontent.com/12507297/158900888-9c3a63e3-097c-4674-a8b2-12af43b7e60d.png)

Maybe tweek the definition to say "Registration number assigned by the National Oceanic and Atmospheric Administration."

**Comment by Jegelewicz** [comment]
But will there also be "NOAA accession number" and "NOAA catalog number"? See U. S. National Park Service accession [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type#u__s__national_park_service_accession) and U. S. National Park Service catalog [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type#u__s__national_park_service_catalog)

Should the actual identifier be NOAA: National Oceanic and Atmospheric Administration registration number?

**Comment by dustymc** [comment]
``MMPA registration number`` ==>  Marine Mammal Protection Act registration number assigned by the National Oceanic and Atmospheric Administration (NOAA)

Er sumthin.

>will there also be "NOAA....

Yes.

**Comment by acdoll** [comment]
> But will there also be "NOAA accession number" and "NOAA catalog number"?
Not that I'm aware of. 

> MMPA registration number
 It is not a number associated with the Act, it is a number designated by NOAA. It has NOAA as a prefix. The zoo where we got it has this number (though they mis-entered the actual number) under the Identifier Type: NOAA ID
![image](https://user-images.githubusercontent.com/12507297/159061078-f583dfc3-4028-4a5d-b746-0a4ad208d246.png)
We'd really prefer 'NOAA: National Oceanic and Atmospheric Administration' so it is obvious to NOAA if they come looking.

**Comment by dustymc** [comment]
>Not that I'm aware of.

One example is that NOAA runs NMFS, NMFS runs (ran?) AMMTAP, http://test.arctos.database.museum/SpecimenResults.cfm?oidtype=AMMTAP%3A+Alaska+Marine+Mammal+Tissue+Archival+Project&scientific_name=&country=&state_prov=&county=&spec_locality= finds 195 records. Those are (sorta) "NOAA IDS."

I'm sure that about any huge organization issues dozens if not hundreds of identifiers. I suspect you'd have much better luck calling them regarding marine mammal registration number NOAA0002098 than you would with plain ol' NOAA0002098, and that likely extends to anything that might eventually come online. Or maybe not, maybe they really did start at NOAA1 and everything's in one system.....

I don't particularly care how the distinction is made or what the identifier is called, but I think it's a potentially important distinction to make. 

All that said, I won't object to the original request as long as everyone understands the implications.

**Comment by Jegelewicz** [comment]
Is this related to a permit? See https://fisheriespermits.noaa.gov/npspub/pub_track_activity/pub_cmn_search_request_inc.jsp

NOAA issues all kinds of permits....although none of them start with "NOAA". I cannot find anywhere that they issue "registration numbers" or anything else like that.

A Google search gives me this
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjui66oqdD2AhUFKn0KHTwUCY0QFnoECAMQAQ&url=https%3A%2F%2Ffoiaonline.gov%2Ffoiaonline%2Fapi%2Frequest%2FdownloadFile%2F2015-001372%2520Resp%2520Record%2520(MMIRS%2520all)%25201doc%252C%2520300pgs%2520(1).pdf%2F603b8562-947b-43e7-8366-769e32a89a6d&usg=AOvVaw1Ad-oXnMy_P23bX0sP4wJL

So I think the actual ID is NOA0002098

**Comment by Jegelewicz** [comment]
And I feel like that is some sort of permit number....

**Comment by Jegelewicz** [comment]
@ArctosDB/arctos-code-table-administrators please weigh in.

**Comment by acdoll** [comment]
I do not know the workings of NOAA administration; I just have a number that they provided and told us to label the specimen with it. 

> Is this related to a permit? See https://fisheriespermits.noaa.gov/npspub/pub_track_activity/pub_cmn_search_request_inc.jsp

I'm not sure what I'm supposed to see here.

> A Google search gives me this

If NIMM calls is a NOAA ID why don't we just go with that? However, it seems a convention of this code table to spell out external acronyms, so I feel that puts us back at NOAA: National Oceanic and Atmospheric Administration
If we come up with new types of NOAA numbers in the future, can't we change it then?

**Comment by campmlc** [comment]
See https://media.fisheries.noaa.gov/dam-migration/22686_revised_application.pdf:
"For captive-born animals:
o Provide documentation of the animal’s birth.
o Identify the parents of the animal and provide documentation of their origin (e.g.,
lineage), including the wild stock and geographic location the animals were
collected from. Use NOAA ID number if applicable. The purpose of this information
is to document that the animal did not originate from a depleted species or stock. "

**Comment by campmlc** [comment]
Likely related to the Marine Mammal Protection Act which requires both a NOAA and USFWS permit to house captive marine mammals. I assume they issue each animal an ID. I support using NOAA: National Oceanic and Atmospheric Administration and then making ammendments in the future if we get more info.

**Comment by Jegelewicz** [comment]
Suggest we add this.

**Comment by Jegelewicz** [comment]
Code Tables says go

**Comment by Jegelewicz** [comment]
added
