### ISSUE TITLE
Code Table Request - new other identifier relationship = reproduction of

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4451]
**Goal**
Indicate that a cataloged item is a reproduction of another cataloged item

**Context**
Doing some research for other identifier stuff and came across two methods for doing the same thing.

1. [ALMNH:Paleo:8993](https://arctos.database.museum/guid/ALMNH:Paleo:8993) is a reproduction of [NHM: Natural History Museum](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type#nhm__natural_history_museum): [734808](http://data.nhm.ac.uk/dataset/56e711e6-c847-4f99-915a-6894bb5c5dea/resource/05ff2255-c38a-40c9-b657-4ccb55ab2feb/record/734808) but the identifier is just added to the Arctos record with no relationship.
2. [OWU:ES:35](https://arctos.database.museum/guid/OWU:ES:35) is a reproduction of [NHM: Natural History Museum:2227981](http://data.nhm.ac.uk/dataset/56e711e6-c847-4f99-915a-6894bb5c5dea/resource/05ff2255-c38a-40c9-b657-4ccb55ab2feb/record/2227981) but the identifier is added with the relationship "same individual as"

Neither of these methods seems to sufficiently indicate the real relationship of the object cataloged in Arctos to the one cataloged at NHM.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctid_references

**Proposed Value**
reproduction of

**Proposed Definition**
The identifier indicates the original object (such as a fossil, letter, or painting) of which the cataloged object is an imitation, transcript, or copy.

**Priority**
[  Please choose a priority-label to the right.  ]

**Comment by dustymc** [comment]
Term seems reasonable, https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_event_type#creation will be relevant too.

I don't think I like your definition though, "of another cataloged item" is too specific. You could 3D print from an MRI and make the relationship to an ORCID, for example. "...of the referenced item" or something maybe.

**Comment by Jegelewicz** [comment]
>  "of another cataloged item" is too specific


The identifier indicates the original object (such as a fossil, letter, or painting) of which the cataloged object is an imitation, transcript, or copy.

It doesn't say "another cataloged item"?

**Comment by Jegelewicz** [comment]
Suggest we add this.

**Comment by Jegelewicz** [comment]
How is it different than depicted as and depiction from terms? It's not use them instead.

Add the depiction relationship for the above plus other casts from ALMNH

**Comment by Jegelewicz** [comment]
fixed relationships that started this issue to use depiction of and I think it's fine. We probably need to find the others? How? 
 @dustymc any ideas?

**Comment by Jegelewicz** [comment]
These will get fixed as they are found. Closing.
