### ISSUE TITLE
Code Table Request - new other identifier = lot number

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4452]
**Goal**
Accurately describe lot numbers assigned to lots in ASUMZ:Bivalve (but also other collections)

**Context**
Incoming records will already have an institutional catalog number, but each record is also assigned a lot number (many records may share a single lot number). I could ask for ASUMZ Bivalve Lot ID (as we did with MSB Fish) but I'm not sure that is necessary and it seems like the generic term would be used by more collections.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type#institutional_catalog_number

**Proposed Value**
lot number

**Proposed Definition**
an identification number assigned to a particular quantity or lot of material from a single event or manufacturer

**Priority**
[  Please choose a priority-label to the right.  ]

**Comment by campmlc** [comment]
This sounds like a reasonable idea.

**Comment by Jegelewicz** [comment]
@ArctosDB/arctos-code-table-administrators @dustymc I need this in order to migrate some data. Are there any objections?

**Comment by dustymc** [comment]
No objections, but maybe open another issue to see if we can merge the existing same-thing values.

**Comment by Jegelewicz** [comment]
OK, I'm going to add this so that the other issue makes sense.

**Comment by campmlc** [comment]
No objections here
