### ISSUE TITLE
replacing of offensive geographic names in specific locality

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#4453]
According to the [NYT (March2022)](https://www.nytimes.com/2022/03/10/us/squaw-new-name.html), 660 geographic features in the US will no longer use an offensive term for native women and be replaced with new names.  ([an interactive map](https://geonarrative.usgs.gov/names_taskforce/) for those who want to see which ones and where).

Arctos has 473 localities that include an eligible name across multiple US states.

I suggest we have an Arctos-wide plan to update these localities systematically once the replacement names are released -- several states have already started their own process of replacing these names. Discussion points may include:
- update name in Specific Locality; verbatim stays verbatim
- Include a common remark about this systematic update or not?
- how will this impact collections with physical labels or other collection related organization dependent on locality?
- notification to any impacted collections (ie., that has a changed spec locality)
- other needed actions?
FYI, USGS has had similar name change 'sweeps' to eliminate offensive/ racist geographic feature names in the past. Museums also stopped using them; I think we are all better for that!

**Comment by AJLinn** [comment]
Thanks for making an issue for this Michelle. There is a related issue that @KyndallH and I talked about with some common names of animals as well (this was the one I needed to deal with in our collection recently: https://en.m.wikipedia.org/wiki/Long-tailed_duck).

I think Kyndall found some resource online for dealing with this as well.

**Comment by wellerjes** [comment]
We've encountered some common names working in botany too. I made a chart of specimens that have problematic name associated with them so that we double-check labels and create new labels if needed. I'd be interested in hearing what other institutions are doing to address this too.

**Comment by ewommack** [comment]
> Include a common remark about this systematic update or not?

Yes please! Taking on historic collections with the outdated taxonomy and locality names is already a mystery to solve. If we could a record of the changes in the names that would be really helpful for determining if the written label from 100 years ago is referencing a specific locality or not. Maybe something like taxonomy (https://avibase.bsc-eoc.org/species.jsp?lang=EN&avibaseid=AF0C7BDEC7CEBAAC&sec=summary)

**Comment by dustymc** [comment]
> outdated taxonomy

And current.

https://arctos.database.museum/name/Iron%20Chink
https://www.nomenclature.info/parcourir-browse.app?lang=en&wo=N&ws=INT&id=4450

**Comment by Jegelewicz** [comment]
> Can we update our nomenclature to "iron butcher" as noted here:

What current term need to be changed?

**Comment by AJLinn** [comment]
Iron chink
https://arctos.database.museum/name/Iron%20Chink
 
I submitted a request to Nomenclature to change it to a "non-preferred term" and make Iron Butcher their preferred term.

**Comment by Jegelewicz** [comment]
Actually, nobody is using this - so if you guys agree, I will just quarantine it.

**Comment by AJLinn** [comment]
I like the idea of quarantining it, which seems like it's sort of the equivalent to the "non-preferred term" status that I'm asking Nomenclature folks to implement.
<img width="972" alt="Screen Shot 2022-05-06 at 8 40 59 AM" src="https://user-images.githubusercontent.com/17605945/167175712-7052ada0-b93f-4cca-80da-b3cf27f9eecd.png">

Agreed, it's important to document it in our records as a term used throughout the 20th century (and can be found all over the place now, for better or worse) but I wouldn't want anyone using it now.

**Comment by Jegelewicz** [comment]
It has been quarantined!

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/internal/issues/183
