### ISSUE TITLE
Bulkloading Accessions - issue with 'enteredby' agent role

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#4457]
We (@mkoo @ejbrock) are bulkloading accessions into the new MVZ:Arch collection. The documentation says that the entered by role is "Automatically populated with login information" but that didn't happen when she tried to bulk upload - so a bunch of accessions got uploaded to MVZ:Arch with enteredby = 'unknown.' Can you please change enteredby from 'unknown' to 'Erika J. Brock' (agent ID 21282690) for those MVZ:Arch accessions?

Second issue: the accession bulkloader file has fields for TRANS_AGENT_# and TRANS_AGENT_ROLE_#. In a second pass, Erika tried entering her name with a role of 'entered by' per this [code table](https://arctos.database.museum/info/ctDocumentation.cfm?table=cttrans_agent_role), but is getting an error "Only one agent in role entered by is allowed per transaction." She may be the second or third agent for a given accession, depending how many "received from" agents there are.

It makes sense to have the 'enteredby' agent be automatically populated from the agent login information, but that's not happening. Can we fix the ones that were already uploaded and then make that magic work the way it is supposed to?

**Comment by dustymc** [comment]
Loader will behave properly in next release.

Al MVZ:Arch enteredby=0 updated to 21282690.
