### ISSUE TITLE
Display specimen events in order by collecting event date

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4458]
Request: to order specimen events (which need renaming BTW) by date of the associated collecting event. Potentially also allow the option of display oldest to newest or newest to oldest - if we have to choose one, I would prefer the newest event showing up first, at the top, and displaying with the catalog record. Older events should display with the expand all option.
Why: Currently multiple events appear to display randomly on the Catalog Record page. This is confusing and misleading.  Also this is critical for the Entity catalog record display.
Priority: high - we want to be able to show off how Arctos can handle multiple events, and can't do under current random display.
@dustymc

**Comment by Jegelewicz** [comment]
> which need renaming BTW
