### ISSUE TITLE
Georeferencing Issues

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#4459]
The issue with the yellow box has returned, in a few different ways (see [Issue #4395](https://github.com/ArctosDB/arctos/issues/4395)), along with some other georeferencing questions.

1) [ChAS:Herb:1949.5225.46](https://arctos.database.museum/guid/CHAS:Herb:1949.5225.46): The box is yellow, but the locality is within the polygon. The only thing we can think is that the radius of uncertainty extends outside of the polygon, but this has not been an issue in the past.

2) Our intern georeferenced two localities to different borders of Chicago. She confirmed that the box turned green after she initially georeferenced it (her notes and date of georeferencing are saved in locality remarks), but noticed today that both now have yellow boxes and the coordinates are incorrect (one is georeferenced to the south border of Chicago ([ChAS:Herb:4151](https://arctos.database.museum/guid/CHAS:Herb:4151)), the other to the north ([ChAS:Herb:1119](https://arctos.database.museum/guid/CHAS:Herb:1119)), yet both have the same coordinates). The history does not indicate that anyone else has changed the locality. How did these get reset/changed?

3) Starting this week, an issue occurred when trying to georeference a locality with a manually created polygon. Our intern created a polygon for [Wady Petra, Illinois, which is a township](https://arctos.database.museum/place.cfm?action=detail&locality_id=11539293). She used the GeoLocate tools to draw in a polygon, then inserted a point and created a radius of uncertainty. However, when she hit save, it only saved the polygon coordinates, not the area encompassed by the radius of uncertainty. She's gotten around it by going back and deleting the polygon before saving, but this has not happened before.

4) Is there a way to search within georeferenced specimens to find what color the box is, in order to review and fix if necessary? Especially if coordinates are somehow changing after showing up green, I'd like another way to review. I am receiving emails/notifications regarding the Locality Change Log, but without opening each individual record, it's difficult to determine if something is off.

Thanks for your help!

**Comment by dustymc** [comment]
>only thing we can think

You don't have to guess, there's a key!

<img width="868" alt="Screen Shot 2022-03-18 at 9 55 21 AM" src="https://user-images.githubusercontent.com/5720791/159047937-8a1bb351-5362-4856-9fac-c6787e053fe4.png">

>has not been an issue in the past.

I haven't had the tools to detect that in the past.

>How did these get reset/changed?

See https://github.com/ArctosDB/arctos/issues/4259 - we're doing more with polygons, which those are.

>t only saved the polygon coordinates

See above, same issue.

>ind what color the box 

<img width="411" alt="Screen Shot 2022-03-18 at 9 58 52 AM" src="https://user-images.githubusercontent.com/5720791/159048565-9fa82493-09df-41cb-80ca-2bd820f1f16d.png">

See also https://github.com/ArctosDB/arctos/issues/4289 - that report contains "does not intersect" data, which is just wrong, and "does not contain" which should probably be seen as advisory at this point. (It's still "wrong" but I'm not sure we'll have to resources to do anything about it any time soon.)

**Comment by wellerjes** [comment]
Thanks for the updates!

Will we need to go back and correct the catalog records that were georeferenced, but have now shifted? Example: I [georeferenced this record in February](https://arctos.database.museum/guid/CHAS:Herb:1); at the time, the entire polygon was in the radius of uncertainty, but now it extends beyond the radius.

Will it correct itself when the updates are in place? Has the process for georeferencing changed?

**Comment by dustymc** [comment]
>Has the process for georeferencing changed?

Yes, that's the core of https://github.com/ArctosDB/arctos/issues/4259

* before, you had to provide coordinates to provide any spatial data, and there was no way to know which is "real" (especially if they're not obviously related, and nothing was forcing them to be)
* now, you provide one, that comes with a marker so I don't have to guess what's what, and I provide the other.

Essentially nothing (that you need to care about) has changed for point-radius data.

For polygon data, just draw the shape in geolocate (or file an issue for more tools, of course), click save, and I'll draw the circle around it - you don't need to, and can't, provide point-radius data. (You can add an event if you need both.)

I did assume that any existing polygon data was primary - I have a backup if that's a problem, we can roll whatever back to before the update (but there's no way around the part where Arctos generates whatever's not primary).

On https://arctos.database.museum/guid/CHAS:Herb:1,  the user is told....

<img width="171" alt="Screen Shot 2022-03-23 at 2 14 03 PM" src="https://user-images.githubusercontent.com/5720791/159796780-6cd18718-e7fd-48f7-b740-7cae9826f006.png">

... that the polygon is "correct" - I don't think there's anything wrong with the data, and there's nothing you can do about it (other than file an Issue) if there is. The circle is from my scripts, and in that case it's clearly not a perfect approximation of the polygon. Maybe we should somehow be more explicit that users should blame me/Arctos, not you, for that - I'm up for ideas. There's a bit more about how I generate the point-radius data in https://github.com/ArctosDB/arctos/issues/4259#issuecomment-1065971653 - I can rebuild that and regenerate any "derived" data at any time (but I'll probably need to find some help, what's running was the "most right more of the time" formula I could come up with).

**Comment by wellerjes** [comment]
With the new updates, a lot of our data has shifted from the original and is now incorrect. For example: [CHAS:Herb:1896.759.4172](https://arctos.database.museum/guid/CHAS:Herb:1896.759.4172) was georeferenced to the southern border of Chicago (see Locality Remarks). The center of the radius has now moved North, over 15 miles away from its original point. [CHAS:Herb:3727.1](https://arctos.database.museum/guid/CHAS:Herb:3727.1), also within Chicago, was georeferenced to a specific intersection, but now shows up at the same point (41.8260596924 / -87.7251996104) as CHAS:Herb:1896.759.4172.

Can you please restore our georeferencing data to what it was before the update? We have interns and volunteers who are matching records and historic maps to the data within GeoLocate to create more accurate measurements. The polygon itself is not always used as the final marker/radius. Thank you!

**Comment by dustymc** [comment]
TODO: Figure out where the polygon in GL is coming from - can we prefer one or the other? User settings??

Find chas records that use polygon, pull old PR, review, repatriate

**Comment by Jegelewicz** [comment]
@dustymc this has also happened for ASUNHC collections. Can we fix them too? Maybe there are others?

**Comment by dustymc** [comment]
> also happened for ASUNHC collections.

There are no pre-https://github.com/ArctosDB/arctos/issues/4259 localities with footprints used by any ASUNHC collection.

Here are the pre-update data with polygons, I've added in using collections. Let me know how to proceed.

[temp_locality20220314_fp.csv.zip](https://github.com/ArctosDB/arctos/files/8447357/temp_locality20220314_fp.csv.zip)

**Comment by dustymc** [comment]
I can't replicate the geolocate behavior that was described today. If I don't click ``Draw polygon`` then it saves point-radius data back to Arctos, if I do click ``Draw polygon`` then it saves footprint data back to Arctos. I can't make it do unpredictable things.

@wellerjes can you explain (maybe with screenshots or something) how you're getting polygons back?

@mkoo can you break it?

**Comment by wellerjes** [comment]
The polygons have always just appeared like that for me. This is a screenshot from January when I was first learning.
![image](https://user-images.githubusercontent.com/93737929/162454127-5dd0b4b6-abf6-40b5-8280-7126f889a113.png)
The option for error polygon is selected, I did not change anything for the screenshot (this is an example of how GeoLocate does not always correctly pull up the correct coordinates right away).

And an example from today:
![image](https://user-images.githubusercontent.com/93737929/162454446-d73a9684-5c6d-4240-b489-b5aeeedd511f.png)
This is what it looks like after I click on "Georeference with Geolocate" from the "Edit Locality" page.

We haven't really been been creating custom polygons; there are a few I did to teach myself and create examples for other staff working on the project (primarily related to bodies of water). The majority of the georeferencing is based off the polygon that GeoLocate provides upon opening the application. Our intern did say that the process changed (see the third point in my original post, above), which I think is when the new updates where implemented. The errors are appearing in the records that were georeferenced (correctly) prior to the updates and are now incorrect.

**Comment by ewommack** [comment]
So it looks like Geolocate couldn't find the specific locality in the Locality String and so backed out to the next level that it could (which may have been the entire town of Glen Ellyn)?

When Geolocate does that to me, I enter a new locality in the Locality String, or grab an approximate GPS coordinate set from Acme Mapper and enter that into the Locality String. I then hit the Georeference button again and it finds the more specific locality I want it to focus on. 
Does that sound similar to your general work flow when looking for more specific localities?

**Comment by wellerjes** [comment]
Yes, that is the general workflow we use when looking for more specific localities. Once we have broader location (such as the entire town of Glen Ellyn) then we will drag the marker to the proper location and adjust the error radius from there. For Glen Ellyn, the radius would encompass 2 miles south of the city's center to 2 miles south of the southern border.

**Comment by ewommack** [comment]
> Once we have broader location (such as the entire town of Glen Ellyn) then we will drag the marker to the proper location and adjust the error radius from there. For Glen Ellyn, the radius would encompass 2 miles south of the city's center to 2 miles south of the southern border.

So that's a little different than what I described. You're not actually entering a new location into Geolocate. I think dragging the marker should work, but you'd want to be careful if you then clicked the Georeference button again, instead of the Save to your Application button. The georeference button will send you right back to the previous locality.

> adjust the error radius from there

How are you adjusting the error? By drawing a polygon or editing the uncertainty radius? 

@dustymc are any of these steps the ones that might be resulting in movement of the locality? I'm not sure I'm actually narrowing down on what may be going wrong.

**Comment by dustymc** [comment]
>might be resulting in movement of the locality?

No, https://github.com/ArctosDB/arctos/issues/4259 removed any mystery. I'm still waiting to hear if I need to do something with https://github.com/ArctosDB/arctos/issues/4459#issuecomment-1092293196 - I think I made bad migration assumptions regarding the source of those polygons.

I still can't re-create what's being described in geolocate, but WHATEVER happens there just pushes data which can be saved to Arctos, and there should now be no mystery in what will happen with those data - ``Primary Spatial Data Type`` controls that.

**Comment by ewommack** [comment]
Thanks @dustymc, so the locality info will get fixed for @wellerjes?

**Comment by dustymc** [comment]
I don't know what "fixed" means - I can shuffle things around but I need guidance.

**Comment by ewommack** [comment]
I think this is what they are looking for:

>  I could do something with the pre-update point-radius data - replace the polygon (surely not what you want!) or add a second locality-stack, perhaps.

**Comment by wellerjes** [comment]
What would replace the polygon do? Would it bring the pre-update point-radius data back? Or would adding a second locality stack bring back the data? Do you have a screenshot or example so I can see what each option would do and how it would impact our records?

**Comment by dustymc** [comment]
Yes, those are the obvious choices. 

I don't have a great way to visualize without just doing something. Coordinates + error are in the file, but I know that's not the same as SEEING it. If you have some idea I'm happy to try it.

If I just replace the polygon with point-radius it will be "done" for better or worse. No cleanup, some potential to lose something you didn't want to lose. (I'd grab a backup first so not really "lose" but things could get more complicated.)

The other thing I can think of is to create new "locality stacks" (specimen_event, collecting_event, locality) for these. That would allow you to see them side-by-side and do whatever you want from there, but it would touch 2580 records so there's some potential for significant cleanup being needed somewhere.

Here are the GUIDs that would be affected, if that's useful.

[temp_chas_loc_guids.csv.zip](https://github.com/ArctosDB/arctos/files/8532346/temp_chas_loc_guids.csv.zip)

**Comment by wellerjes** [comment]
@dustymc I think we figured it out. Our process has been to intentionally plot the point radius. The "error polygon" option was checked during the process, but not impacting how our data showed up until the most recent update in March when the improvements were incorporated.

Would it be possible to remove the associated polygon error data? We just want the point radius data on the catalog records.
![image](https://user-images.githubusercontent.com/93737929/166967544-06ff5466-98dc-4e01-9439-651ad16fc5ad.png)

Going forward, we will make sure that the "error polygon" option is unchecked. Is there a way to save the form so that the error polygon option remains unchecked, or is that something we will need to do manually each time?

**Comment by Jegelewicz** [comment]
@mvzhuang mentioned some weirdness in her georferencing yesterday - may want to follow up there too. Pinging her here so she can find the issue.

**Comment by dustymc** [comment]
@wellerjes I think you're asking me to change the CHAS localities in the [CSV I posted](https://github.com/ArctosDB/arctos/issues/4459#issuecomment-1092293196) to the point-radius data in that file - please confirm.

**Comment by wellerjes** [comment]
@dustymc I have reviewed the CSV and am confirming. Thank you!
