### ISSUE TITLE
De-specimining of Arctos continued...From specimen events to record events

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4460]
> which need renaming BTW

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/arctos/issues/4458#issuecomment-1072592023_

"specimen event" does not work for cultural collections and needs to be changed as part of de-specimening Arctos. I suggest all references to "specimen event" in the UI be changed to "object event".

**Comment by mkoo** [comment]
I noticed this in particular when cataloging the first archive records!
how about "record" event since not everything is an object? So the spatial hierarchy (not a true hierarchy of course) would be something like:
-Higher geography
-locality (add coordinates if available, adds specific locality)
-collecting event (adds date)
-record event or circumstance (adds details for the cataloged record)

(see [this in handbook)](https://handbook.arctosdb.org/how_to/How-to-understand-the-Arctos-Locality-Model.html)
+1 on UI change

**Comment by Jegelewicz** [comment]
I like it except not all events are "collecting" I suggest this

-Higher geography
-locality (add coordinates if available, adds specific locality)
-event (adds date and what happened - collection, creation, etc)
-record event or circumstance (adds details for the cataloged record)

**Comment by AJLinn** [comment]
I like this - it’s quite confusing when we’re talking about a collecting event for a place/date of creation or use!

**Comment by campmlc** [comment]
Could we somehow merge what is currently collecting event and specimen
event into "event", and allow multiple "events" per record? There are just
a few extra fields. We'd have a "creation" "event" or an "encounter"
"event" or "collection" "event"? We don't have a way to search on
"specimen" events anyway - they seem not to actually "exists".

**Comment by dustymc** [comment]
>merge what is currently collecting event and specimen event into "event"

Not if you want hosts and parasites and such to share things.

>and allow multiple "events" per record? There are just
a few extra fields. We'd have a "creation" "event" or an "encounter"
"event" or "collection" "event"

We have that, https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_event_type

>We don't have a way to search on
"specimen" events anyway 

<img width="504" alt="Screen Shot 2022-03-18 at 11 23 53 AM" src="https://user-images.githubusercontent.com/5720791/159061526-b5752dfb-156f-4b66-800f-9bdb99927bcb.png">

https://arctos.database.museum/SpecimenResults.cfm?verificationstatus=accepted&collecting_method=net&collecting_source=wild&specimen_event_remark=a&specimen_event_type=collection&scientific_name=&country=&state_prov=&spec_locality=&related_record_summary=&verbatim_collector=

**Comment by campmlc** [comment]
Record/event remark? What is that? How do I know this is in any way related
to specimen events?

**Comment by campmlc** [comment]
I see that parasites and hosts sharing a collecting event might not share
the "collecting method" if we really get down into the details of what
"method" means.  And potentially a host could have event type "encounter"
while the parasite has event type "collection" - if you pull a flea off a
live animal and then release the host. But adding the complexity of a
separate event type just for those two details seems unnecessary. Is there
no other option for capturing these data? The specimen event model adds an
incredible level of confusion to any event editing process - I never know
if I'm using the right tool or am in the right place or am going to make a
giant mess, and if I'm having difficulties, I assume others more so. Plus
some tools don't work - e.g. Search Results ->Manage ->Collecting Events
And specimen event is not searchable - there is no way to find all specimen
events I entered yesterday and modify them in bulk, no events have an "ID"
or nickname etc.

**Comment by dustymc** [comment]
>confusion

https://handbook.arctosdb.org/how_to/How-to-Create-a-New-Collecting-Event-for-a-Locality.html#fork-edit-method provides a simplified UI which has little chance of making giant messes.

**Comment by campmlc** [comment]
Note that in this documentation, no where is specimen event defined, and
mentioned only in these terms which I still insist lead to confusion (and I
couldn't do any better):
"edit (“Edit the current specimen_event”) should be used when changes have
not affected the fundamental nature of the space-time data."

**Comment by Jegelewicz** [comment]
It IS confusing and I think it is because we are calling the very last thing "specimen event". Even "record event" is confusing. For me that piece is really ASSIGNMENT or DETERMINATION - WHO said this event belongs with this catalog record, WHEN did they assert that and WHY. I think if we were to make that more clear it would help. So

-Higher geography (WHERE in a very general, but normalized way)
-locality (WHERE - more specific, adds coordinates if available, add specific locality)
-event (WHEN, HOW - adds date and what happened - collection, creation, etc)
-assertion/determination (WHO, WHY - adds information about who added higher geography, locality and event to the catalog record)

**Comment by dustymc** [comment]
> -event (WHEN, HOW - adds date and what happened - collection, creation, etc)

Not if you want hosts and parasites and such to share things.

**Comment by Jegelewicz** [comment]
But FWIW - I think the host and parasite should share the HOW of one event. The parasite should have a second HOW when it is removed from the host and right now we aren't recording that event.

**Comment by campmlc** [comment]
Yes, agree that makes sense.

**Comment by dustymc** [comment]
I think this is done, please open specific requests if anything remains.
