### ISSUE TITLE
spatial announcement?

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4461]
Do we need some sort of announcement regarding the recent spatially oriented changes?

The core is in https://github.com/ArctosDB/arctos/issues/4259, but that changes:

1. All spatial data are constrained to "valid" - they can be used for any kind of spatial operation
2. The "spatial tools" widget on specimensearch got a lot of new functionality
    * users can draw polygons, not just squares
    * users can search spatially by geography, no matter what's been curatorially asserted
    * users can search by arbitrary spatial data (as KML)
    * all of that can match on intersecting or containining
3. There are a lot of new links on the place view (eg top of https://arctos.database.museum/place.cfm?action=detail&locality_id=11035378) and edit geography
4. https://github.com/ArctosDB/arctos/issues/3530 needs attention
5. There's a new report (reports/low-quality/locality/geography), notifications coming soon

**Comment by ewommack** [comment]
https://github.com/ArctosDB/newsletter/issues/146
and 
https://github.com/ArctosDB/newsletter/issues/147

Arctos Newsletter adding a new feature on Spatial Features. Would this be a good issue for the first article in April 2022?

**Comment by mkoo** [comment]
I am transferring my suggested draft text to the newsletter issues that Beth linked.
@dustymc I will keep this open until the next newsletter so anyone can keep adding any more ideas that we should mention
