### ISSUE TITLE
Problems with record creation

### ISSUE THREAD

**Issue by jandreslopez** [ArctosDB/arctos#4466]
The new interface for entering records is giving me a hard time.

When entering higher geography information, the form triggers the "An error occurred while processing this page!" window.  Likewise when entering part names.

I tried it a number of times with the same result.  Here is one error log id in case it helps:  4F269961-2C6F-4D3B-9174783807E094D5

**Comment by dustymc** [comment]
>error log id in case it helps

Yes, I'd have never figured this out without!

You're not logged in, which could mean you're just not logged in (timed out, maybe), or that your browser isn't accepting cookies or something of the sort.

<img width="282" alt="Screen Shot 2022-03-21 at 5 26 19 PM" src="https://user-images.githubusercontent.com/5720791/159384167-4cc84422-f3b6-419b-93de-a7a7adb30a74.png">
