### ISSUE TITLE
Merge specifc lot identifiers into generic "lot number" identifier

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4469]
No objections, but maybe open another issue to see if we can merge the existing same-thing values.

_Originally posted by @dustymc in https://github.com/ArctosDB/arctos/issues/4452#issuecomment-1075683567_

**Comment by Jegelewicz** [comment]
Let's merge the following identifier types into the generic identifier type "lot number".

[MSB Fish Lot ID](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type#msb_fish_lot_id)
[MSB Para Lot ID](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type#msb_para_lot_id)

@campmlc

**Comment by campmlc** [comment]
Agree

**Comment by dustymc** [comment]
[temp_cs_lot.csv.zip](https://github.com/ArctosDB/arctos/files/8328868/temp_cs_lot.csv.zip)

done
