### ISSUE TITLE
spatial tools search with polygon fails

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#4472]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

choose collection UAM:Ento

make a polygon with spatial tools on map to enclose the Aleutians

click search

get records limited to the latitude enclosed by the polygon but not the longitude (tons of records to the west and east of the polygon were returned).

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.
high

**Comment by dustymc** [comment]
Confirmed.

Something about st_contains isn't converting from geometry to geography correctly, I need to find another approach.

The "intersects" option seems to work correctly, although of course it's not returning the same records.

https://arctos.database.museum/SpecimenResults.cfm?guid_prefix=UAM%3AEnto&poly_coords=%5B%7B%22lat%22%3A56.710334113409985%2C%22lng%22%3A166.21646265431144%7D%2C%7B%22lat%22%3A55.43503805951048%2C%22lng%22%3A164.10708765431144%7D%2C%7B%22lat%22%3A52.166967856214235%2C%22lng%22%3A169.20474390431144%7D%2C%7B%22lat%22%3A49.5035704966242%2C%22lng%22%3A-173.65658422068856%7D%2C%7B%22lat%22%3A53.44204427110298%2C%22lng%22%3A-161.61556859568856%7D%2C%7B%22lat%22%3A56.662062468892486%2C%22lng%22%3A-154.40853734568856%7D%2C%7B%22lat%22%3A58.08349038460589%2C%22lng%22%3A-160.47299047068856%7D%2C%7B%22lat%22%3A53.6509317509246%2C%22lng%22%3A-171.19564672068856%7D%2C%7B%22lat%22%3A52.809180304282386%2C%22lng%22%3A-179.89681859568856%7D%2C%7B%22lat%22%3A53.96233288203579%2C%22lng%22%3A174.74185327931144%7D%2C%7B%22lat%22%3A56.273657066639025%2C%22lng%22%3A168.94107202931144%7D%5D&geog_srch_type=intersects&scientific_name=&country=&state_prov=&spec_locality=&formatted_scientific_name=

**Comment by ewommack** [comment]
Oh good it wasn't just me! I was trying to do a polygon search yesterday, and figured I just clicked on something wrong and was going to try again when I had more time today.

**Comment by dustymc** [comment]
slipped into production
