### ISSUE TITLE
agent cleanup request: United States Fish and Wildlife Service

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4474]
I clicked [United States Fish and Wildlife Service, Alaska Region](https://arctos.database.museum/agent/21337396) (there's no way that's not in Arctos, even if we don't call it that) and found

* United States Fish and Wildlife [Service]
* USFWS
* U. S. Fish and Wildlife Service

and probably didn't find more. Can we consolidate/organize those, maybe even add [appropriate relationships](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctagent_relationship#division_of)?

**Comment by Jegelewicz** [comment]
I just created the division of relationship between [United States Fish and Wildlife Service, Alaska Region](https://arctos.database.museum/agent/21337396) and [United States Fish and Wildlife Service](https://arctos.database.museum/agent/3679)

**Comment by Jegelewicz** [comment]
Changed preferred names for the following to the complete spelling and added these as aka's.

USFWS Bureau of Sport Fisheries and Wildlife (organization: 21277734) [[new window]](https://arctos.database.museum/agents.cfm?agent_id=21277734)
USFWS TX Fish and Wildlife Conservation Office, San Marcos TX (organization: 21325711) [[new window]](https://arctos.database.museum/agents.cfm?agent_id=21325711)

**Comment by Jegelewicz** [comment]
Changed preferred names for the following to the complete spelling and added these as aka's.

U. S. Fish and Wildlife Service, Key West National Wildlife Refuge (organization: 21247686) [[new window]](https://arctos.database.museum/agents.cfm?agent_id=21247686)
U. S. Fish and Wildlife Service Mexican Wolf Recovery Program (other agent: 1012059) [[new window]](https://arctos.database.museum/agents.cfm?agent_id=1012059)
U. S. Fish and Wildlife Service, Western Energy and Land Use Team (group: 21311786) [[new window]](https://arctos.database.museum/agents.cfm?agent_id=21311786)

**Comment by Jegelewicz** [comment]
Suggest that this one go away?

Personnel from Florida Fish and Wildlife Commission & U. S. Fish and Wildlife Service (group: 10014685) [[new window]](https://arctos.database.museum/agents.cfm?agent_id=10014685)

There are only 3 people in the group and the only activity I can see is that the group is associated with a permit. Suggest that they just get associated personally with the permit. I don't see any transactions associated with the permit, but that is probably my permissions....

**Comment by ewommack** [comment]
> Suggest that this one go away?

> Personnel from Florida Fish and Wildlife Commission & U. S. Fish and Wildlife Service (group: 10014685) [[new window]](https://arctos.database.museum/agents.cfm?agent_id=10014685)
> 
> There are only 3 people in the group and the only activity I can see is that the group is associated with a permit. Suggest that they just get associated personally with the permit. I don't see any transactions associated with the permit, but that is probably my permissions....

Might want to check with who is working with that permit. It might be one of those donations or gifts where you have a couple contacts at the agency, but the permit is held under the full agencies name. USFWS is making us do this now, where while one person is the contact for a permit, it is actually under an organization's name. Theoretically we might be able to switch contact people on a permit for an organization, though I haven't done that yet myself.
