### ISSUE TITLE
Arctos Down - keeps crashing and coming back online and then crashing again

### ISSUE THREAD

**Issue by atrox10** [ArctosDB/arctos#4475]
Please complete to the best of your ability.
Arctos keeps crashing and then coming back online and then crashing again, since 2:20 pm PST or so. I am in the middle of data editing and it keeps dying on me with a 503 error!

## Unplanned Outage
 - Date and time outage discovered:
 - Describe the outage (Arctos down or only some part not working?):

## Planned Outage
 - Date and time outage will begin:
 - Date and time outage is expected to end:
 - Reason for outage:
 - Expected behavior during and after the outage:

## Communication before/during outage
- [ ] Pin this issue
- [ ] Banner updated @jegelewicz 
- [ ] Email sent to AWG 
- [ ] Email sent to Arctos Google Group 
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @jegelewicz
- [ ] Email sent to AWG 
- [ ] Email sent to Arctos Google Group 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by wellerjes** [comment]
This is probably related: I'm trying to login after a 503 error, but I'm getting: "An error occurred while processing this page!"
This message has been logged as F3A396B5-719C-4D3D-81EF886BB3CBEBFE

**Comment by dustymc** [comment]
Arctos is back and hopefully stabilized.
