### ISSUE TITLE
Arctos Down - suggested change to template

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#4477]
@Jegelewicz - before I started changing templates I wanted to suggest a change here.
I just saw an Arctos down notice (https://github.com/ArctosDB/arctos/issues/4476) that said Arctos went down at 1:42pm, but was posted MT at 3:45pm. I assumed that was a time zone difference, but I wasn't sure. Maybe a good idea to suggest people add their time zone to the outage notice so we can tell when they are reporting the outage. I would assume that it is reported right away, but maybe not?

Please complete to the best of your ability.

## Unplanned Outage
 - Date and time **(suggest add time zone to the info collected on when an outage is found)** outage discovered:
 - Describe the outage (Arctos down or only some part not working?):

## Planned Outage
 - Date and time outage will begin:
 - Date and time outage is expected to end:
 - Reason for outage:
 - Expected behavior during and after the outage:

## Communication before/during outage
- [ ] Pin this issue
- [ ] Banner updated @jegelewicz 
- [ ] Email sent to AWG 
- [ ] Email sent to Arctos Google Group 
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @jegelewicz
- [ ] Email sent to AWG 
- [ ] Email sent to Arctos Google Group 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by Jegelewicz** [comment]
Good call - I added a request for time zone to the template.
