### ISSUE TITLE
spatial search results to berkeleymapper

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4479]
When I do a spatial search, it works fine to get me a table of specimens. But then if I try to map them in Berkeley Mapper, it fails consistently. 
An error occurred while processing this page!
Message: Syntax Error, Invalid Construct
Detail: at position 3 in [[{]
Check the [Arctos Handbook](http://handbook.arctosdb.org/documentation/understanding-errors.html) for more information on errors.
This message has been logged as FF400596-4B80-4A61-8DD571607CE0209F Please [contact us](https://github.com/ArctosDB/arctos/issues/new?assignees=&labels=contact&template=contact-arctos.md&title=error%20feedback) with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue.

_Originally posted by @cjconroy in https://github.com/ArctosDB/newsletter/issues/147#issuecomment-1079118660_

**Comment by mkoo** [comment]
BM expects a table. perhaps the results are not in the typical BM table format?
