### ISSUE TITLE
KML box search returns errors in Spatial tools

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#4480]
You know how I like trying out new functions without any instructions-- when testing out the new Spatial tools, I tried copy/pasting the raw KML in the KML box, AND in a different test,  a coordinate pair, to search by intersection. Both queries returned error messages!

Let me know what I am doing wrong so I can write up for the newsletter. Not sure if this is boring user error or a bug.
thanks

**Error message**
his message has been logged as DB30E0EB-5910-49F6-8D465FB79557842D Please [contact us](https://github.com/ArctosDB/arctos/issues/new?assignees=&labels=contact&template=contact-arctos.md&title=error%20feedback) with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue.

**Data**
KML file attached (zipped)
[HastingsReserve.kml.zip](https://github.com/ArctosDB/arctos/files/8352021/HastingsReserve.kml.zip)

**Comment by dustymc** [comment]
I was hoping you'd show up and tell me!

I'm using

```
ST_GeomFromKML('#kmlfile#')
```

and it's super-twitchy - I think I got it to work on a polygon or something, it definitely understands SOME KML, but it's not very robust.

**Comment by mkoo** [comment]
Ah ok, that helps to know-- it can only take an abbreviated KML without all the header attributes. In other words, the text has to be geometry only so should start with the tag ```<Polygon>```  and leave out any style or placemark tags that may precede the geometry. (it works now btw with the KML geometry)

Definitely not a user friendly option-- how about a way to upload the *.kml or *.kmz file then parse?

For now, can you place a "beta" note next to the search box? I can write up some helper text, but I want to test a little more.

**Comment by dustymc** [comment]
How's this?
<img width="450" alt="Screen Shot 2022-03-25 at 9 49 30 AM" src="https://user-images.githubusercontent.com/5720791/160165423-a9f5cc16-b6d2-42c6-9a21-f11de0ebd6cd.png">

**Comment by mkoo** [comment]
ok I'm digging around and definitely will need some GIS format translator help (ogr2ogr). I will have to keep looking

And that text looks good with possibly the addition in the box 
"Enter point or polygon in KML format, e.g. start with <polygon> tag"

It still requires the user to crack open the KML file in a text editor and do some reading....

**Comment by dustymc** [comment]
Added to documentation, I don't have better tools, closing.
