### ISSUE TITLE
Planned Arctos Outage - Friday April 8th at 10 am CT

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#4482]
## Planned Outage
 - Date and time outage: April 8 Friday at 10 am -12 pm Central Time 
 - Reason for outage: Important updates and a complete backup image of Arctos will be performed. Arctos will be offline and unavailable up to 2 hours during this operation.

## Communication before/during outage
- [x] Pin this issue
- [x] Banner updated @jegelewicz @mkoo 
- [x] Email sent to AWG 
- [x] Email sent to Arctos Google Group 
- [x] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [x] Unpin this issue
- [x] Banner updated @jegelewicz
- [x] Email sent to AWG 
- [x] Email sent to Arctos Google Group 
- [x] Tweet @lin-fred (@mkoo backup)
- [x] Close this issue when above are complete

**Comment by ewommack** [comment]
Text for email to google group:
Heads up Arctos!

**Arctos will be down on Friday the 8th of April from 10am - 12pm CT**

Arctos needs to go down on the 8th of April for important maintenance and the performance of a complete back-up image  of Arctos. Arctos will be offline and unavailable during this time for up to 2 hours during this operation.

Set to go out on Thursday 31st of March to AWG, Arctos group and Steering committee, and repeat message on Wednesday 6th of April.

**Comment by Jegelewicz** [comment]
> needs to go down 

Can we use some different wording?

Arctos will be offline and unavailable for up to 2 hours beginning at 10AM CT on the 8th of April for important maintenance and the creation of a complete back-up image of Arctos.

**Comment by lin-fred** [comment]
Edit:

Arctos will be offline and unavailable for up to 2 hours beginning at 10AM CT on the 8th of April for important maintenance. Please be sure to save your changes before then. Thank you for your patience!

**Comment by ewommack** [comment]
I updated the emails with @lin-fred's suggested text. Same schedule of emails as before.

**Comment by dustymc** [comment]
Arctos is back online.

**Comment by mkoo** [comment]
Please close once emails are sent! thanks all

**Comment by ewommack** [comment]
Emails sent and closing
