### ISSUE TITLE
Feature Request - Bulk add or remove identifiers from search results

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4486]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
It is frustrating to need to create an identifier bulkload when I am adding the same identifier to a bunch of (or just two....) records

**Describe what you're trying to accomplish** 
Add or remove an identifier from a group of records

**Describe the solution you'd like**
Use the manage function in search results to either add or remove a single identifier from the records listed in results.

**Describe alternatives you've considered**
Make a bulkload/bulk unload file

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by campmlc** [comment]
Yay! I enthusiastically support this.

**Comment by dustymc** [comment]
I'm torn on how to view this.

It's easy enough to do, I can see the usefulness, there are other tools like it, but it's not scalable - it would be born being fully capable of using up all the resources it can safely access and then throwing errors. (And if we had orders of magnitude more resources, that would still be true.) I think that was expected and understood then Arctos was much smaller, but recently the feedback on similar situations has been - let's just call it not-so-great PR. (And while I generally just hear from the user with the obvious error, other users would likely be affected - we've also long outgrown any single-user assumptions we might have ever been able to justify.)

A 'download for identifier loader' in search-->tools would have the same functionality, is scalable, but of course would require a few more clicks.

Any of the 'download for...' tools could have a 'massage data and write directly to component loaders' step added - the component loader ecosystem was designed with this in mind.

I think I very tentatively suggest this be rejected and that rejection be expanded to the other existing instant-mass-update options, but I still know how to do it and it should work on "a few" records most of the time.

**Comment by Jegelewicz** [comment]
> Any of the 'download for...' tools could have a 'massage data and write directly to component loaders' step added - the component loader ecosystem was designed with this in mind.

Can we demo that with this? Change my request to that?
