### ISSUE TITLE
503 Service Not Available

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4491]
Please complete to the best of your ability.

## Unplanned Outage
 - Date and time (**please add time zone from which you are reporting**) outage discovered: 4:10 PM MDT
 - Describe the outage (Arctos down or only some part not working?): 503 Service Not Available

## Planned Outage
 - Date and time outage will begin:
 - Date and time outage is expected to end:
 - Reason for outage:
 - Expected behavior during and after the outage:

## Communication before/during outage
- [x] Pin this issue
- [ ] Banner updated @jegelewicz 
- [ ] Email sent to AWG 
- [ ] Email sent to Arctos Google Group 
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @jegelewicz
- [ ] Email sent to AWG 
- [ ] Email sent to Arctos Google Group 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by lin-fred** [comment]
seems to be back up
