### ISSUE TITLE
geography - authority or not?

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4493]
At least two seemingly duplicate values (Primorsky, Adrar) were create yesterday.

I think we should be running geography through the issue process, like any other authority.

I would also like to see geography accompanied by spatial data, either as part of creation or as something that's part of some workflow, but I'm not sure how practical that is.

Are there other views of geography?

@Jegelewicz please review the recently-created values.

**Comment by Jegelewicz** [comment]
I don't know how Adrar is a dupliucate? It is a [Province of Algeria](https://en.wikipedia.org/wiki/Adrar_Province) and a [Region of Mauritania](https://en.wikipedia.org/wiki/Adrar_Region).

**Comment by Jegelewicz** [comment]
Deleted the dup of Primorsky.

Considering the number of HG I added this week, I think one problem isn't too bad. If we want to make this an issue process and have it reviewed, that is fine, but we need an active geography committee or data will never get migrated.

**Comment by dustymc** [comment]
> one problem

... that was detected! And that process is obviously far from perfect - I seem to be running about a 50% error rate (for whatever unknown percentage of these I actually see) at the moment, Adrar is fine.

A committee would be AWESOME, but just "I'll create this in 24H if nobody stops me" would add some level of betterment to the process.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/4755
