### ISSUE TITLE
Code Table Request - new part preservation = polished

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4497]
**Goal**
Accurately describe preservation of meteorites (and possibly rocks and minerals)

**Context**
The UNM Institute for Meteoritics uses this term in its data. Knowing what preservation is available can help researchers understand what they can do with a given sample. These are not fixed to a slide.

**Table**
[part preservation](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_preservation)

**Proposed Value**
polished

**Proposed Definition**
Shiny as a result of being rubbed

**Priority**
[  Please choose a priority-label to the right.  ]

**Comment by Jegelewicz** [comment]
@dustymc any objection?

**Comment by dustymc** [comment]
nope

**Comment by Jegelewicz** [comment]
added
