### ISSUE TITLE
Need to Undo Parts to Container Bulkload and Redo with Scary Red Box Bulkload

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4498]
Problem: I used the Parts to Container Bulkloader for 92 DGR containers for a loan. This was a mistake, because these were legacy containers converted from the DGR Locator, and they already had collection objects associated. Using the parts to container bulkload was the wrong tool - it moved the parts out of the legacy containers with no barcode (but with labels and a pathway) into totally new containers with barcodes but no label or pathway.
Request: I am requesting @dustymc  undo the bulkload as loaded in the attached file. Then, I need @dustymc to magic these barcodes into the previous legacy containers. 
I would  also like to request a tool to bulk add barcodes to legacy containers that already contain parts - a bulkload version of the scary red box. Currently, I have no way of adding barcodes to legacy containers except one at a time through the scary red box in Edit Container. For a loan of nearly 100 samples, this was not feasible. I still have several hundred thousand legacy samples without barcodes but with associated parts that will need barcodes added, and one at a time is not going to be feasible going forward. 
Priority: High. Loans are getting larger and larger - not possible to tackle this a few dozen records at a time.
[2022.020.Mamm parts to containers bulkload.zip](https://github.com/ArctosDB/arctos/files/8384124/2022.020.Mamm.parts.to.containers.bulkload.zip)

**Comment by Jegelewicz** [comment]
> a bulkload version of the scary red box.

That exists - https://arctos.database.museum/tools/scaryBarcodeSwapper_box.cfm

**Comment by dustymc** [comment]
>magic

Don't tell anyone, but the wizard thing isn't entirely true....

Particularly for things that haven't been moved in a while, I don't have a great history. Manually doing something 100 times is probably a couple orders of magnitude easier than some of the potential alternatives. Fortunately in this case I think I was able to pull what I needed from test - please review the attached and confirm that parts should be in the listed CONTAINER_ID, and if that's correct I can move them

[temp_msb_oc.csv.zip](https://github.com/ArctosDB/arctos/files/8391295/temp_msb_oc.csv.zip)
.

**Comment by campmlc** [comment]
Hmm, I'm not sure how to check the container ID? It's not something I can
access in any of the tools I see. If you found those in test, they should
be accurate, fingers crossed.

**Comment by dustymc** [comment]
CONTAINER_ID corresponds with CONTAINER_TYPE | LABEL | DESCRIPTION.

You can see them in the UI via eg https://arctos.database.museum/findContainer.cfm?container_id=18250037

**Comment by campmlc** [comment]
in that case, based on the url, the first one is correct.

**Comment by dustymc** [comment]
done

**Comment by campmlc** [comment]
Oh, you mean in the URL . . .
so in that case, the first one is correct.
