### ISSUE TITLE
Gold standard record nomination!

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#4499]
I was touring some records as I start to set up UCM:Para and found an awesome gold standard record from DMNS!

https://arctos.database.museum/guid/DMNS:Mamm:11098

This chipmunk has multiple parasites, multiple pubs, specimen (whole drawer) images, collecting event images, GenBank, Dryad and Globi links, and is linked to a project. What's not to love?

We should add to arctosdb.org. Putting this here so I don't forget and assigning a few of us who have website permissions.

**Comment by dustymc** [comment]
Definitely support this (and I've been using this record) - how does this proceed?

**Comment by cjconroy** [comment]
I know it is picky, but it looks like it was identified the day before it was collected.

**Comment by Jegelewicz** [comment]
That is actually a google doc - so adding has some weird group permissions.

https://docs.google.com/document/d/1JEOypOhTWaOW_t6M194tEr1ctkXM5gjzwkgtU-OaYsg/edit

**Comment by Jegelewicz** [comment]
@acdoll any chance we can fix the date issue mentioned [here](https://github.com/ArctosDB/arctos/issues/4499#issuecomment-1116255966)?

**Comment by acdoll** [comment]
John just updated that - and added a molecular-based confirmation! I might have to chase the skeleton down and get an image of the skull to add...

**Comment by Jegelewicz** [comment]
Added to the Gold Standard list - let me know if "Why we like it" needs any editing.

**Comment by acdoll** [comment]
@dustymc any thoughts on why this now has two GBIF links to different occurrences? (one with good data and one without)

**Comment by acdoll** [comment]
I see it now - looks like a GBIF issue. The European Nucleotide Archive must have uploaded data to GBIF and just had the catalog number. GBIF just created a new occurrence from that and then Arctos caught it as a match.

**Comment by dustymc** [comment]
Yea GBIF doesn't have a place for our real identifiers, so I have to use

```
http://api.gbif.org/v1/occurrence/search?catalogNumber=#guid#"
```
to try to dig something up.  [Yay science....](https://en.wikipedia.org/wiki/Replication_crisis)

**Comment by acdoll** [comment]
It looks like this new version of the EMBL database just repackaged GenBank data and submitted that into GBIF (probably with a lot of other stuff)

**Comment by dustymc** [comment]
EMBL (and DDBJ) used to exchange info with GB all the time, which is awesome for all kinds of reasons - or it was until now, I suppose....

**Comment by Jegelewicz** [comment]
From John W.

> EMBL are free to publish those records, are they not? And GBIF picks up the equivalence in their clustering algorithm (https://www.gbif.org/occurrence/3350405114/cluster). This is definitively not a GBIF problem. It is either a social one or not a problem at all.

From our perspective, could we use this kind of thing to create a relationship to the other identifier? Do we need to? Do we care if the extra link shows up on our page?

**Comment by acdoll** [comment]
Having the two links on our records doesn't really bother me - it's actually really cool that Arctos is catching these duplications when it can (I've found plenty others that won't be caught because the older GenBank submissions did not get the proper number format).

> could we use this kind of thing to create a relationship to the other identifier?

In this case, they both have the same identifier (DMNS:Mamm:11098), which is why Arctos caught it.  If Arctos could catch ones that do not have the proper identifier, now that would be something!
