### ISSUE TITLE
> a bulkload version of the scary red box.

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4503]
> a bulkload version of the scary red box.

That exists - https://arctos.database.museum/tools/scaryBarcodeSwapper_box.cfm

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/arctos/issues/4498#issuecomment-1083704768_

**Comment by campmlc** [comment]
This exists as a tool to give barcodes to all samples in a freezer box, but I am requesting a tool that will allow me to add barcodes to legacy containers that are scattered among different containers. Currently, I update legacy containers that are pulled for loan, and these may come from many different freezer boxes. I don't have the ability to update all samples in a given box, I just need to be able to add barcodes to existing containers from the loan list.

**Comment by dustymc** [comment]
I have no technical objections to this request, but it would be capable of making very impressive messes that we will not realistically have the resources to un-do. I think tools of this nature require more discussion.

Scripting stuff, particularly in a situation that we know is messy, is no problem but even then this must involve some checks. The most basic of those is "donor container is of a type which can't be involved in complex situations." (Donor containers are deleted and their barcodes are re-used by all of the "scary swapper" tools.) That means a container type involving "label," and all of these are cryovials - and they all seem to have locations.

One container_id is null as well - I think it didn't get included in the last update, hopefully that can be corrected through the check containers link from the record.

@campmlc I help clean up but I need explicit instructions - can I move all of these donors to 0 and change them to labels? Anything I need to be watching out for?

**Comment by campmlc** [comment]
You have as much info as I have now, so hopefully everything we need is in
the file.
But I do need this tool for DGR. I understand it will create messes. But I
can't add barcodes one at a time to 100 plus records - this is not a
feasible workflow option. My only other choice is not to barcode, which is
also not an option because I need barcodes to specifically link a
part/container to a loan item.

**Comment by dustymc** [comment]
donation complete

**Comment by campmlc** [comment]
OK, this is getting ridiculous. I just used the lovely parts to containers bulkload for yet another loan that had barcodes needing to be added to parent containers and subsamples. It all worked beautifully -  such a straightforward and simple process in the new component loader. My brain wants this to work, obviously. 
But no, dozens of the barcodes I loaded were for parts that had labels but no barcodes, and needed to be loaded one at a time through the scary red box. Please, please with sugar on top can I get a tool to bulkload legacy barcodes? I cannot add barcodes one at a time when I have 30, 40, 50, 100 samples in different freezer boxes that all need to have barcodes added in this way. The risk of my making a mess is no different that the risk of making a mess with the bulkloader that allows this process for barcodes within a single freezer box. 
And I am making terrible messes that waste my and everyone else's time without this tool
Priority: Urgent
@dustymc

**Comment by campmlc** [comment]
BTW  I was able to use part_id in the parts to containers bulkload tool to ensure that I matched the correct barcode to the correct parent part or subsample. I downloaded part ID from the loan item review csv. This works great - but only if I can bulkload the barcode to a part that has a legacy label and position but no barcode.

**Comment by campmlc** [comment]
Here is the file of the affected samples.  I need all of the parts in this file removed from the associated barcode and restored to their previous legacy label without a barcode locations. Then I need these barcodes added back to the legacy containers with positions so that I maintain the labels and positions with the new barcode associated.
[partFlatDownload -Malaney loan to fix.zip](https://github.com/ArctosDB/arctos/files/8526166/partFlatDownload.-Malaney.loan.to.fix.zip)

**Comment by campmlc** [comment]
I need help reversing this, please. High Priority. @dustymc @Jegelewicz

**Comment by Jegelewicz** [comment]
I would probably only make a bigger mess. @dustymc can you reverse that?

**Comment by campmlc** [comment]
And I do need the bulkloader tool for this, even if it is just specify to DGR. It is not possible for me to convert hundreds of records one at a time on a tight loan timeline.

**Comment by campmlc** [comment]
I have no way to check each of these, so you'll just have to apply it and I'll go look at container history to see if it worked correctly.
And yes, I agree with Teresa's solution. Any DGR container with a label and a position but no barcode should get some temporary series barcode that can be replaced as we actually pull and handle them. We could start this series with "DGRTEMPxxxxx" ?

**Comment by campmlc** [comment]
Although "moving stuff into a loan box" is really not possible- first, I don't want to have scan 100 samples into new positions to convert them keep track of their old positions, and then rescan them back to where they originally came from. There has got to be a better way. Again, if this problem is unique to DGR, give me the same tool as the converter for a single freezer box that I can use for any cryovial. Any mess I can possible make can't be any worse than this.

**Comment by dustymc** [comment]
>virtual barcodes 

That seems like more mess from here, but I can't wrap my head around what exactly is going on. Whatever it is, part_ids can provide an unambiguous internal handle and I'm not sure what a fake barcode can do that they can't. (The inverse isn't true, part_id uniquely has a 1:1 ratio with parts.)

>need the bulkloader tool for this, even if it is just limited to DGR

The framework can't handle that. I'm still happy to serve as your bulkloader - whatever you're doing, I'm positive I could have done it in way less time and with way less uncertainty than I've got in this, and I do keep backups so undoing anything I do should be possible - very unlike bulk tools.

**Comment by Jegelewicz** [comment]
> I'm not sure what a fake barcode can do that they can't

Right now, Mariel cannot MOVE anything that has a barcode-less label. Adding a barcode would at least allow her to move stuff.

IMO, the whole barcode-less label in object tracking is nothing but a way to make messes.

**Comment by campmlc** [comment]
What about giving everything the existing  part ID? Make an option of
making that permanent? That would give it a permanent ID I can use to
bulkload loan items. Then the barcode is something I can assign separately,
although I still need this tool. But right now I am completely handicapped
if I can't add barcodes in bulk to create the loan and document the
subsample parent ID.
FYI we have over 670,000 cryovials now - how many have actual barcodes?

**Comment by dustymc** [comment]
> giving everything the existing  part ID?

Every part in Arctos has an ID, you can file an issue to make it do stuff in any part-related application.

>option of making that permanent? 

https://github.com/ArctosDB/arctos/issues/3630


>barcodes...to create the loan 

Barcodes can do that, but if you're not finding things to loan by the barcodes it's probably just an extra unnecessary step.


>barcodes .. document the subsample parent ID.

Barcodes cannot do that, and I still don't understand the fundamental problem. 

This might be a good candidate for an AWG discussion.

>have over 670,000 cryovials now - how many have actual barcodes?

```
 institution_acronym |   c    | hasbarcode 
---------------------+--------+------------
 MSB                 | 282897 | yes
 MSB                 | 239352 | no
```

**Comment by Jegelewicz** [comment]
So 147K or so aren't even cataloged?

**Comment by campmlc** [comment]
This makes it very difficult to get an accurate count of what we have here - also the pending backlog material, e.g. zoo, other research material, and finally, the thousands of bird samples that may or may not be cataloged but if cataloged were loaded without barcodes. So I need to have time or staff support to bulkload barcodes to samples.
If we can get these legacy label with no barcode samples fully functional, meaning I can easily add barcodes to 100 samples scattered among 50+ different freezer boxes, then I can devote more time and attention to tackling these other problems.

**Comment by campmlc** [comment]
So, any chance of a resolution on the scary barcode bulkload problem soon? I have close to 500 samples requested for loan that I need to process in next 3 weeks.

**Comment by campmlc** [comment]
I just checked the first record in the temp file and it looks OK. Please go ahead and load these. I have to move on to other loans, and this one will get lost if not resolved asap.

**Comment by dustymc** [comment]
Done.

PLEASE let me know if I can help update (or anything else) **before** it becomes a recovery mission. Moving things around, adding stuff to loans, acting as your personal bulkloader, or WHATEVER is easy, recovering from a situation like this is the complete opposite.

**Comment by campmlc** [comment]
What I need is the bulkload tool. I cannot ask you to add barcodes to every
set of tissues for every loan that I am trying to get out the door before
Fedex closes at 7:30 pm.

**Comment by campmlc** [comment]
Several times per week.

**Comment by dustymc** [comment]
>Several times per week.

Still faster - and safer - than what I just did!

I have been asking for help in prioritizing issues for a very long time. I thought we were all agreed on otherIDs, and I now have that in a state where I can't really do anything else until it's done. I would be absolutely thrilled to have more guidance in whatever form that might take.

**Comment by campmlc** [comment]
Looks like you were able to successfully reverse my bulkload of the parts
to new barcodes and replace the parts in their original labels + positions
with no barcodes. But that now puts me back in the same situation of
needing the bulkload tools to move these labels into new barcodes without
losing the positions.

**Comment by campmlc** [comment]
Asking you to load barcodes for me is not a tenable workflow for me or a reasonable use of your time. Please, I need this tool.

Here is the file of the barcodes that need to be added to the barcode-less containers that have labels and positions.

[Malaney Baca Loan parent part to label only containers.zip](https://github.com/ArctosDB/arctos/files/8567299/Malaney.Baca.Loan.parent.part.to.label.only.containers.zip)

**Comment by dustymc** [comment]
>not a tenable workflow

I'm not asking for it to be, but I still can't do everything all at once. I can however usually drop everything to make some simple update until I can do something more permanent.

Done.

[temp_container_swapper.csv.zip](https://github.com/ArctosDB/arctos/files/8567332/temp_container_swapper.csv.zip)

**Comment by campmlc** [comment]
It looks like this worked, thank you. I'm hoping never to have to do this again, or to have to ask  you to do so.
But I am desperately needing a resolution going forward - for me, this is the highest priority request I currently have in Arctos as it impacts my ability to do my job on a daily basis. I'm trying to complete multiple loans before I lose my staff support at the end of the semester - and each loan requires this tool I am requesting. 
Priority - urgent.

**Comment by dustymc** [comment]
Needed: add container_id to part table download

**Comment by campmlc** [comment]
Not exactly sure what the process is going forward to implement this?

**Comment by Jegelewicz** [comment]
This tool - https://arctos.database.museum/tools/containerBarcodeReplacer.cfm?action=ld

Probably needs a simple test?
