### ISSUE TITLE
Feature Request - Agent prebulkloader enhancements

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4504]
**Is your feature request related to a problem? Please describe.**

**Describe what you're trying to accomplish** 
I am working with the Agent prebulkload tool and there are a few things that I think would make it easier to use.

**Describe the solution you'd like**
1. Can we somehow put all of the names that return a "fatal" exact duplicate exists together in a group? I used CTRL-F to dig them out of a long list and mark them "in Arctos", but that's a bit of a pain. It may not be perfect, but if I find a name exists, I use it. I don't spend hours looking at all of the other "possible" matches.
2. The output of a csv download from the tool provides the column headers for an agent bulkload, but only fills in the preferred name. We have the agent name splitter thing, could that get built into this tool so that the file I get out already includes first, middle and last name? I realize this will still need a review - but it would save a lot of time for me!
3. Can we change the result "CHECKED" to "Not in Arctos"? This makes it clear that this name needs to be added.

**Describe alternatives you've considered**
1. I can CTRL-F and find all of the exact matches and change their status to "in Arctos", but remember, the people using this generally can't load their own agents and the review process is hard enough!
2. I can text-to-columns that preferred name, but I know we have a tool for this, so let's just build it into the process!

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by Jegelewicz** [comment]
BTW - I have nearly 2,000 people to review for the CRCM bird collection and about 8,000 for the UWZM! This is A LOT of stuff to check and the more efficient I can be, the better.

**Comment by dustymc** [comment]
> agent name splitter thing

Good place for a workflow maybe - that (and whatever other cleanup tools are necessary) should be used before this, the final tools should be provided all of the data to work correctly, I'm sure that was in the documentation that the tool says you should follow but I can't find it....

>exact duplicate exists together in a group

That would be tricky, but finding (or excluding) isn't with the right tools - try

```
 select * from cf_temp_pre_bulk_agent where username='you' and status not like '%fatal%'
```

**Comment by Jegelewicz** [comment]
> that (and whatever other cleanup tools are necessary) should be used before this

So you are saying that if I put in first, middle and last name, I will get it back out? Because the tool only requires preferred name and I had first middle and last from my review before running names through the tool, but I just didn't add them to the file because they weren't required.

> That would be tricky, but finding (or excluding) isn't with the right tools - try
> 
>    ```select * from cf_temp_pre_bulk_agent where username='you' and status not like '%fatal%'```

Can we add a button for that or something? Again, this tool is one of the VERY FIRST things incoming collections staff will encounter in Arctos - having them write SQL seems like a drag....

**Comment by dustymc** [comment]
>first, middle and last name, I will get it back out

Yes, accompanied by better suggestions. Obviously need better docs/workflow/something.

>add a button 

"delete fatal"?

**Comment by Jegelewicz** [comment]
> "delete fatal"?

Maaaayyybeee? It feels weird to have them just go away, but maybe that's OK? I think I would need other opinions....

**Comment by Jegelewicz** [comment]
OK, I have been using this all day today and I managed to review almost 1,800 names in approximately 6 hours. Here are a few things that make it hard.

- [ ] The links out to similar agent names are great - but can we change them to open in a new tab? I have now trained myself to right-click and open in a new tab, but that's a time sink.
- [ ] Investigating any particular name means first clicking to the agent, then to the agent activity, then to the catalog records (in a private window). Almost anyone using this tool will likely have access to NO collections with data, so getting to the catalog records in a private window will be their goal. Can we eliminate all the clicking and get straight to that? 
- [ ] I spent a HUGE amount of time scrolling because the possible duplicates are smashed into the skinny left-hand column while the middle of the screen has a huge amount of white space.
![image](https://user-images.githubusercontent.com/5725767/161339908-e87f72bc-66f7-4447-872d-f705de29b7c0.png)
Sometimes it was difficult to find the tiny little check box for a given name because there were soooooooo many potential dupes. My initial reaction is that listing the potential duplicates UNDER the name (so two rows per name, one is the name, the other the dupes) might be better? Possible?
 - [ ] Returning to the "fatal" question above. Out of this list I found 258 "fatal"s which I selected and changed status to "In Arctos". Not sure how long it took, but it was a drag. If delete "fatal" is the only option, then let's offer it. I like ending up with the same list I put in so that I can be sure I have addressed everything, but....

I'll probably come up with more, but object tracking just ruined my flow......

**Comment by Jegelewicz** [comment]
@dustymc I just ran through the process of checking/loading agents for a small set and documented it here - https://github.com/ArctosDB/data-migration/issues/1327

One thing that might also be useful to have the output from the Agent Name Splitter put the first, middle and last names in columns like the Agent Prebulkloader accepts - it will mean less manipulation from one tool to the other.

I am struggling with how best to document/demonstrate this process. The steps are definitely a workflow and I can change the "Agents" issue template in data migration to reflect these steps, but it can be a real long and difficult process when there are a lot of names - as I am about to experience with the 5,000 names I just received from UWZM....

**Comment by dustymc** [comment]
Calling this next release - not everything will be addressed but it will all be different, reopen new issues post-next-release for further adjustment.
