### ISSUE TITLE
Agent Disambiguation - Henry J. Rust

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4505]
The agent [Henry J. Rust](https://arctos.database.museum/agents.cfm?agent_id=10010417) appears to cover two distinct people:

One who collected birds in Idaho in the early 1900's

One who collected fossils in Alabama in the 1990's

![image](https://user-images.githubusercontent.com/5725767/161316168-2fe05761-038e-4aed-b5e5-023c6e21836b.png)

@aklompma or @ccicero can either of you provide a full middle name for your collector? Is this in fact the same person who simply changed interests over time?

@aklompma it actually looks like more ALMNH:Paleo records are recorded under [Henry Rust](https://arctos.database.museum/agents.cfm?agent_id=21318106), so maybe I just need to move the ALMNH records to that agent? However, I am guessing that the confusion will simply continue and records for one agent may be cataloged using another since they are so similar.

@dustymc thoughts on how to reduce that possibility?

**Comment by dustymc** [comment]
>Is this in fact the same person who simply changed interests over time?

That's always the safest default position, and is absolutely the most discoverable situation. Lacking decent evidence of the contrary, fewer agents leads to more useful data.

>how to reduce that possibility

See above: I'll always vote for the opposite approach. Given one entity attributed to multiple Agents, nobody will ever find all of what they're interested in. Given multiple entities attributed to one Agent, everybody will find all of what they're interested in, and maybe some extra - which they might tell us about, at which point splitting becomes justified.

Henry has a "Tad" AKA and Henry J has a "T." in a name - I don't think the universe generally goes to that extent just to mess with us....

**Comment by Jegelewicz** [comment]
> I don't think the universe generally goes to that extent just to mess with us....

The universe, no. People, yes.

Once we hear from @aklompma and @ccicero we can decide if these two agents should be merged. or what needs to be done.

**Comment by aklompma** [comment]
It is Henry James Rust for the one collecting Alabama fossils and I _think_ he also went by Tad as a nickname.

**Comment by Jegelewicz** [comment]
HMMMMM - I think the Universe is messing with us!

**Comment by Jegelewicz** [comment]
So for now, I added the full middle name to Henry Rust and changed all collectors in ALMNH records to use that agent. Now the birds and fossils collected by the two Henry J. Rust agents are separate until we discover that they don't need to be....

**Comment by dustymc** [comment]
>separate until we discover that they don't need to be....

Both the specific data and the general trend of the type of data overwhelmingly suggest these are one person, so the conclusion is to keep them in the least-discoverable state?!

**Comment by campmlc** [comment]
Look at the dates. Collecting fossils near 100 years of age?

**Comment by dustymc** [comment]
>dates

Derp - 199**9**0s - thx @campmlc - disregard everything I said above, I agree that this is a rare (I think/hope....) case of the universe having a laugh. Add "live" status dates, 'not the same as' relationships, and comment on/prioritize https://github.com/ArctosDB/arctos/issues/903 - that should help with in-UI picks, and hopefully anyone who's using bulk tools knows what they're doing.

**Comment by bjwills** [comment]
Henry J. Rust from Idaho is Henry Judson Rust. He worked for the Forest Service from 1910-1945
