### ISSUE TITLE
Accession Weirdness?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4507]
From [this agent activity page](https://arctos.database.museum/info/agentActivity.cfm?agent_id=21296961) which says the agent participated in an MSB accession, 

![image](https://user-images.githubusercontent.com/5725767/161331640-d89cdf05-7920-4d07-87c9-da74b5d46523.png)

clicking the hyperlink takes me to an [Angelo State accession](https://arctos.database.museum/accn.cfm?action=edit&transaction_id=21115618)?

![image](https://user-images.githubusercontent.com/5725767/161331711-9692c820-7770-475e-b8d3-fe8bdd81476c.png)

**Comment by Jegelewicz** [comment]
OK - think I get it, my permissions have been removed from MSB:Herp - still this seems like a weird thing to end up at in this situation. It would be more appropriate to get the error "you don't have permission" instead of just an empty accession with the agent filled in.....

**Comment by dustymc** [comment]
Thanks and good diagnosis.

>"you don't have permission" 

I can't know that, but there will be better handling of this in next release.

**Comment by Jegelewicz** [comment]
Then let's say that. "noexist" tells me that this thing exists for NO ONE.

How about

This page is not available. This could be because:

1. You do not have appropriate permissions to view the page.
2. The page does not exist in Arctos.

If you believe that the page exists and you have appropriate permission to view it, please ensure that you are logged in. If that does not solve the problem, please <a href="https://github.com/ArctosDB/arctos/issues/new?assignees=&labels=contact&template=contact-arctos.md&title=%255BCONTACT%255D" class="external">file an issue in Github</a>.
