### ISSUE TITLE
rebuild startup stuff

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4509]
missing, onRequestStart, rolecheck don't always work together predictably; merge/simplify

errors that are handled by missing and then passed to 404 don't reliably get logged, make sure this fixes that

logthis uses threads which do not handle db fails gracefully - do something else, runasync maybe (but is it just abstracted threads??)

**Comment by dustymc** [comment]
This involves changes to the foundations of Arctos, some clicking around in test would be greatly appreciated.

**Comment by Jegelewicz** [comment]
I was able to log in on the first try (productions still makes me try about 10 times before it works). Suggestions on what kind of clicking around?

**Comment by dustymc** [comment]
Any and all - the things that literally everything runs on are new (and should be significantly lighter and faster).

Errors should be a lot better, logged in and out - break something.

All place-picks are new (and the antique code the old ones ran on, and the antique library that supported that, and the antiquier library that supported THAT is no more) but I don't really anticipate any problems there. (All the heavy lifting is through the API and those should serve as a model for other picks, but that's another thing.)

Otherwise it should be all behind-the-scenes stuff - break that thing I didn't check.....

**Comment by ewommack** [comment]
Is this something you want a call out to the AWG @dustymc? I'm swamped today, so it will definitely be tomorrow for me.

**Comment by campmlc** [comment]
My test account is locked. Can that happen with active operators who have
an active production account? Can someone unlock for me?

**Comment by dustymc** [comment]
you should have email
