### ISSUE TITLE
data entry mammal standard measurements ear uses ear from crown

### ISSUE THREAD

**Issue by amgunderson** [ArctosDB/arctos#4510]
**Describe the bug**
On the new data entry form in attributes, the line of standard mammal specimen measurements has a field for "Ear" but it populates the attribute "ear from crown" when it should populate attribute "ear from notch". This has consequences for specimen labels and attribute queries. Please make the standard mammal ear measurement "ear from notch". 

<img width="742" alt="Screen Shot 2022-04-01 at 3 35 31 PM" src="https://user-images.githubusercontent.com/8440698/161354561-c745df77-8fe2-4df8-94a5-d198e4966f22.png">

**Priority** a black hole of despair.

**Comment by cjconroy** [comment]
I agree. From notch is standard. I just corrected some recent records, thinking our student made some mistake, but now I realize what happened. Now I will go check all our recent records.

**Comment by cjconroy** [comment]
Related to this, it does not appear that you can change an attribute in the attribute table for a specimen. You have to add a new one and delete the old one, e.g. delete the ear from crown and add a row for ear from notch. Not just swap the attribute and keep the existing agent and date. 
On that table, it would help to have that Use Agent1/Date1 button on the new attribute row at the bottom. I suggested this some weeks ago, but I have not heard any discussion about it. Or I missed it. It would save time.

**Comment by dustymc** [comment]
Changed and relabeled to EFN.

**Comment by Jegelewicz** [comment]
Do we know how long this might have had an effect on data entered while this was a problem?

**Comment by dustymc** [comment]
I can help clean up if necessary, but this literally just helps insert data into the form and there's no behind-the-scenes magic involved.

**Comment by campmlc** [comment]
Yes, agree. I've already alerted MSB:Mamm, but there are likely other
collections.

**Comment by cjconroy** [comment]
I just searched all Arctos for any specimen entered between 1 Jan 2022 and now for any ear from crown greater than 1.  Only 1 specimen shows up, UAM:Mamm:144311.

**Comment by campmlc** [comment]
@amgunderson

**Comment by amgunderson** [comment]
Yep I had a student correct them all. Thanks!
