### ISSUE TITLE
Entity permissions?

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#4514]
Can I have permissions for the Entity collection? I'd like to create a few records that I will use to link UCM mammal and parasite specimens via an Entity. Essentially we have some slide-mounted ectoparasites that were collected from the bottom of jars containing fluid-preserved shrews and voles, so it is impossible to know the exact individuals from which the ectos were harvested. We can at least  create the jar contents/batched mammals as an Entity, so we have a narrowed down list of individuals that the parasites came from (and these jars each represent a trapline transect so the locality and event dates will be different...but similar).

**Comment by dustymc** [comment]
Certainly no objection from me.

The entity tools (none of which are necessary, they're just click-savers) are mostly "Organism ID"-oriented - that doesn't sound like what you need for this, let me know when that becomes a problem and we'll figure something more flexible out.

**Comment by Jegelewicz** [comment]
granted

**Comment by ebraker** [comment]
Thanks! I'll probably also link all the mammals and parasites to a container as a grouping mechanism, but the Entity catalog number will be helpful for creating host-parasite relationships.
