### ISSUE TITLE
Need Help with Arctos Error when Bulkloading

### ISSUE THREAD

**Issue by lin-fred** [ArctosDB/arctos#4515]
# Error Text
**Copy the text from the page and paste it here**
![image](https://user-images.githubusercontent.com/19802479/161836248-37aecd8c-d008-498e-bbec-8be50346944c.png)

# Where it happened
When I linked a csv for bulkloading records and clicked the "Upload this file" 
![image](https://user-images.githubusercontent.com/19802479/161836422-dccb7925-1e6d-4257-9106-1d049cb24cdb.png)

This is new, but is it just saying that there is something wrong with my CSV? or do I not have permission? @dustymc

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/4501

I'm very up for better ideas!

Something's wrong with your CSV

psql:/usr/local/webroot/temp/excopy_lindseyfrederick_20220405020403155_172.sql:19: ERROR: null value in column "collection_object_id" violates not-null constraint DETAIL: Failing row contains (null, null, ...


The best approach is generally to remove the collection_object_id column, assuming you don't need it for some reason.

**Comment by lin-fred** [comment]
Ah ok thank you for linking the other issue!

Thank you for the information about the CSV!
