### ISSUE TITLE
Double clicking Save as new record

### ISSUE THREAD

**Issue by lin-fred** [ArctosDB/arctos#4516]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I was entering an insect on the newer Data Entry Screen and I accidentally clicked the "save as new record" twice in quick succession. The current data entry settings are to erase everything once a new record is saved. When I checked the "Browse your Records" it shows TWO of the same record that I entered, check the time stamps. They both have the same information saved. @dustymc 
![image](https://user-images.githubusercontent.com/19802479/161841060-e7106d40-c9e9-4f4d-bd73-52a25d5776c4.png)

I think I have the fastest fingers in the west with that 0.4 seconds between data entry screens!

**Comment by dustymc** [comment]
>fastest fingers in the west

confirmed
