### ISSUE TITLE
Taxonomy Query - See hierarchy for all members of a given taxon

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4517]
I'm trying to track down the higher classification status of all species in the genus Neotoma in the Arctos taxonomy. 
Some Neotoma spp. are listed in Neotominae, per Mammal Species of the World, but others are in Sigmodontinae. I'd like to get a list or download of  the classifications for each species to see why there is this discrepancy. I'm not sure how to even see this in the current Taxonomy interface. Perhaps it's the hierarchical editor, which I am unfamiliar with?

I suppose this could be a SQL query, although being able to generate similar searches would be useful enough to have it be part of the main interface.

**Comment by dustymc** [comment]
<img width="709" alt="Screen Shot 2022-04-05 at 6 51 50 PM" src="https://user-images.githubusercontent.com/5720791/161879886-3f5ef06c-228a-406f-a546-bb964dc2659a.png">

>why there is this discrepancy

Because that source is a dumping ground.
