### ISSUE TITLE
Need Help with Arctos Error - weird error after bulkloading

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4519]
# Error Text
This message has been logged as 7ECE751D-BE4E-4322-A3C777FA32734993. Please [contact us](https://github.com/ArctosDB/arctos/issues/new?assignees=&labels=contact&template=contact-arctos.md&title=error%20feedback) with any information that might help us to resolve this problem. For best results, include the error and a detailed description of how it came to occur in the Issue.

# Where it happened
https://arctos.database.museum/Bulkloader/BulkloadSpecimens.cfm?action=checkStaged

# Steps to get there
1. Went to https://arctos.database.museum/Bulkloader/BulkloadSpecimens.cfm
2. Loaded a file and selected "check and load"
3. Got the error above

# Problem
No clue what is wrong? The records are sitting in the bulkloader with nothing in status. I usually get something more actionable (like there are non-printing characters or something) so that I know what to look for and fix. Stuff is still in there if that helps. File loaded is attached.
[University of Alabama_Gorgas House Collection_bulkload.csv](https://github.com/ArctosDB/arctos/files/8445028/University.of.Alabama_Gorgas.House.Collection_bulkload.csv)

# Solution
**Community response with directions for how to correct the problem**

**Comment by dustymc** [comment]
I don't have that error for some reason, but probably this:

{"Extended_Info":"","Message":"ERROR: new row for relation \"bulkloader\" violates check constraint \"ck_attribute_value_3_noprt\"","queryError":"insert into bulkloader ....
