### ISSUE TITLE
Code Table Request - Field ID for Utah Museum of Natural History

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4520]
[**Goal**
Add new identifier for Utah Museum of Natural History Field Number

**Context**
This number is used as the identifier for frozen tissues and to link all parts of a given specimen in the field, for example, vouchers, tissues, parasites. Other examples in Arctos = NK, AF, IF, etc.

**Table**
(https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type)

**Proposed Value**
UTF 

**Proposed Definition**
Utah Museum of Natural History Field Number

**Available for Public View**
 Yes 

**Priority**
High. Upcoming field work depends on this.

**Comment by Jegelewicz** [comment]
AWG says to add.

**Comment by Jegelewicz** [comment]
Make sure it only accepts integers.

**Comment by Jegelewicz** [comment]
@dustymc this is in the code table - please ensure that it only accepts integers. Thanks!
