### ISSUE TITLE
Bulkload Catalog Record Error: "Something is missing!"

### ISSUE THREAD

**Issue by Cloveis** [ArctosDB/arctos#4525]
![image](https://user-images.githubusercontent.com/90786192/162499222-29b291d5-e070-4938-8e6d-15838f85595e.png)

**Error message:** 
Something is missing!
May we suggest:
1. Logging in and try again. Log in link to the upper right.
2. On search pages, make sure you do not have values in fields that you do not mean to be there. Or try filling in fewer fields, the more likely to get a match.
3. You may not have sufficient privileges to perform that operation. Consult with your supervisor or Arctos mentor.
This message has been logged as 3C4A41DE-C54E-441A-8E7B2823C53D32AB. Please [contact us] with any information that might help us to resolve this problem. For best results, include the error and a detailed description of how it came to occur in the Issue.

# Where it happened
(https://arctos.database.museum/Bulkloader/BulkloadSpecimens.cfm)

# Steps to get there
       I went to arctos.database.museum and logged into my agent user name. I hovered over "enter data", then "Bulkloader", then selected "Bulkload catalog records". I then scrolled to choose my .csv file. When I clicked "Upload this file" that error message was returned. I was definitely logged in, I did not have anything in the search fields, and I have bulkloaded catalog records before. The last time I did was about a week ago and assured with my supervisor today that I was never removed from my agent permissions. This happened when I tried to load records this morning, and because arctos was down for maintenance I assumed it could have been that and I tried again this afternoon but was returned the same message.

# Problem
**Community response to describe the problem that caused the error**

# Solution
**Community response with directions for how to correct the problem**

**Comment by dustymc** [comment]
```
ERROR: column "collecting_event_id" specified more than once
```

Sorry for the inconvenience, we're working on more informative operator errors, see https://github.com/ArctosDB/arctos/issues/4501

**Comment by KyndallH** [comment]
<img width="1660" alt="Screen Shot 2022-04-11 at 2 18 35 PM" src="https://user-images.githubusercontent.com/16887896/162842663-ce58e4d0-e68c-424a-8ede-ee8c48c963cc.png">

What is my error?

**Comment by dustymc** [comment]
psql:/usr/local/webroot/temp/excopy_fskbh1_20220411050428816_245.sql:1: ERROR: syntax error at or near "," LINE 1: ...eth_2,attribute_determiner_2,collection_object_id,,) FROM st... ^
