### ISSUE TITLE
Error pre-creating locality using geography spatial data

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#4527]
**Describe the bug**
I noticed I now have the option to "use geography spatial data for locality" (yay!), so I thought, for our public version localities I could create a new locality and use the geography spatial data instead of cloning a georeferenced county-level locality, which seems more error-prone. When I tried to do this though, I got an error message.

**To Reproduce**
1. Go to Create Locality
2. Use pick geography to select the county-level geography.
3. Enter specific locality.
4. Click Save.
5. Enter locality nickname.
6. Click Save
7. Under Coordinates, select "polygon" and "use geography spatial data for locality"
8. Click Save
9. See error

**Expected behavior**
Locality should save and add the county polygon. Am I missing something? I also tried filling in Georeference Source/Datum/Georeference Protocol, but when I hit save, nothing happened at all.

**Screenshots**

![image](https://user-images.githubusercontent.com/47402809/162533626-323e3809-28d6-49db-a69a-b01683288db3.png)

![Locality Error 2](https://user-images.githubusercontent.com/47402809/162533674-5aae1931-0d44-431f-9413-b29b26bf7aec.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 100.0.4896.75

**Comment by dustymc** [comment]
You need to include datum, source, protocol - and the UI needs to reflect that.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> You need to include datum, source, protocol - and the UI needs to reflect that.

From my post:

> I also tried filling in Georeference Source/Datum/Georeference Protocol, but when I hit save, nothing happened at all.

**Comment by dustymc** [comment]
derp, elevating priority

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks!
