### ISSUE TITLE
Add New Github User to Arctos Team

### ISSUE THREAD

**Issue by kmkocot** [ArctosDB/arctos#4529]
New User Github username: Awkwardtree13

Please add to the following teams:
- [X] Arctos Users
- [ ] Arctos Code Table Administrators
- [X] Documentation
- [ ] Geo-group
- [ ] Media
- [ ] Paleontology
- [ ] Taxonomy

Thanks!

**Comment by mkoo** [comment]
Hi Kevin, I see your from Alabama-- welcome. You will have to accept the invitation on GH next
