### ISSUE TITLE
Code Table Request - other new identifier type = species code

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#4531]
**Goal**
To add species numbers as another option; we have been using "other identifier," which is vague does not indicate the source of the code.

**Context**
Examples include AOU numbers for birds, which appear on older specimens and checklists.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type

**Proposed Value**
species code

**Proposed Definition**
A standardized/agreed-upon number that serves as a short-hand method of identifying a species.

**Collection type**
All biological collections.

**Comment by dustymc** [comment]
>method of identifying a species.

Is that somehow not classification?

**Comment by ewommack** [comment]
> Examples include AOU numbers for birds, which appear on older specimens and checklists.

I haven't seen these used in years, but they are definitely on very old specimens. I think you would need a good resource to make sure you are referencing the right edition of the AOU checklist. 

>  taxon metadata or perhaps common names

I agree. It's not really an identifier, more a reference to a taxon ID that was made in the past.

**Comment by wellerjes** [comment]
How have these type of numbers (like AOU) been recorded in Arctos? Would it be possible to add a remarks field to "Identifiers" to add in a source (like the edition of AOU number)?

**Comment by campmlc** [comment]
See https://github.com/ArctosDB/arctos/issues/4101#issuecomment-1075229290

**Comment by Jegelewicz** [comment]
@wellerjes these identifiers belong with the taxon name, NOT any specific catalog record. Originally, I thought to put them inside the classification, but that is probably not correct. They are more like a taxon concept. I would like to help by setting up an example of how this would work. If you are willing to give me access to the collection and provide me with one catalog record where this is needed, I can set up an example for you.

**Comment by wellerjes** [comment]
That makes more sense, thank you! I will do some more research and let you know when I have an example ready. I'm trying to match a species code in the herbarium and need to do some digging in the archives to figure out the source.

**Comment by Jegelewicz** [comment]
I think this is exactly the same issue as the LSIDs discussed in #4776

**Comment by dustymc** [comment]
done?
