### ISSUE TITLE
Feature Request - Add Higher Geography

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#4532]
Could someone please add a new Higher Geography for the Copper River Census Area in Alaska? I need it for this object:
https://arctos.database.museum/guid/UAM:EH:UA69-036-0002AI

https://en.wikipedia.org/wiki/Copper_River_Census_Area,_Alaska

**Comment by dustymc** [comment]
I created https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10016162, but leaving this open - there are two related Issues.

1. I can't find spatial data, @mkoo help please!
1. The creation of this changed other stuff, would be very useful to sort out https://github.com/ArctosDB/arctos/issues/3018 while the "then" and "now" data are hopefully not TOO mixed up.

>On January 2, 2019, it was split from the [Valdez–Cordova Census Area](https://en.wikipedia.org/wiki/Valdez%E2%80%93Cordova_Census_Area), along with neighboring [Chugach Census Area](https://en.wikipedia.org/wiki/Chugach_Census_Area).

**Comment by mkoo** [comment]
I added geometry to this borough. But the geojson file did NOT work! WKT did.
I have the rest of AK and would like to try again with geojson but will have to experiment with how the json file is generated....

**Comment by dustymc** [comment]
>geojson file did NOT work!

Yea, PG is twitchy, of I don't quite understand something, or maybe both. I'm using postgis functions...


```

spatial_footprint=ST_GeographyFromText({input})::geography

spatial_footprint=ST_GeomFromKML({input})::geography


spatial_footprint=ST_GeomFromGeoJSON({input})::geography

```

if you want to play with that, send me (small!) files to play with, whatever.
