### ISSUE TITLE
Code Table Request - A whole lot of standard measurements for marine mammals

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4533]
**Goal**
Enter  "research grade" standard marine mammal measurements.

**Context**
See https://github.com/ArctosDB/data-migration/issues/1336

This is what are Cetacean and Pinniped data sheets look like.

![CetaceanSheet_back](https://user-images.githubusercontent.com/5402275/162534225-757b59ea-5cf1-4e13-8ad5-ded60bfc4a80.jpg)
![CetaceanSheet_front](https://user-images.githubusercontent.com/5402275/162534252-72775cac-feca-4bed-9d6b-3b6ea62dc980.jpg)
![PinnipedSheet](https://user-images.githubusercontent.com/5402275/162534237-2c55fe7a-2869-4431-9fe8-303defef942d.jpg)

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type

**Proposed Value**
Before we start proposing individual values, we will need to determine if any current values can be used, however, this would add a lot of new attributes, will this make all mammal collections nuts? Do we need to do something different than creating a new "length" type attribute for these specific measurements?

**Proposed Definition**
See above

**Collection type**
Mamm

**Attribute data type**
free-text, categorical, or number+units depending upon the attribute (TBA)

**Attribute value**
[ For categorical attributes, code table controlling value  ]

**Attribute units**
[  For number+units attributes, code table controlling units  ]

**Available for Public View**
Yes

**Priority**
[  Please choose a priority-label to the right.  ]
We are working to get Cal Poly Humboldt data in before July - would be nice if we can get this ball rolling.

**Comment by dustymc** [comment]
>"research grade"

Ever measure a walrus in the surf?

@amgunderson will have dealt with this kind of data, at least some of them exist as attributes (curvilinear length), one possibility is some kind of object stored as one attribute.

**Comment by dustymc** [comment]
See also: https://github.com/ArctosDB/arctos/discussions/6179

**Comment by dustymc** [comment]
Attributes need individual type requests.
