### ISSUE TITLE
Edit Container: Move all children of this container to barcode tool not working

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4537]
from #4536
Dealing with failed ultralow freezer, need to move all children racks from freezer rack positions in source freezer to identical rack positions in recipient freezer, without have to rescan all the racks. Move all children of this container tool should do this, but it is not working.

Go to: Edit Container: Move all children of this container to barcode
Trying to move freezer racks in positions in source freezer DGR12749 (which has failed) to recipient freezer DGR12547.
Both freezers have positions. I need the racks in freezer positions in DGR12749 to move out of the freezer rack positions in that freezer and into the complementary freezer rack positions in DGR12547.
Result: Get generic "you are not logged in" error.

I first tried to use this tool from a freezer with racks in rack positions to a freezer with empty freezer rack positions - didn't work.
Then I tried deleting the freezer rack positions in the recipient freezer - also didn'w work. I shouldn't have to do that anyway because having to delete freezer rack positions means extra steps, and it makes no sense - the source freezer positions are not moving, only the racks they hold.

**Comment by campmlc** [comment]
Priority: High- impeding work and putting samples and locations at risk of loss.

**Comment by dustymc** [comment]
Tools can't work with mismatched layout information.
```
arctosprod@arctos>> select * from container where barcode in ('DGR12749','DGR12547');
 container_id | parent_container_id | container_type | label  |                                             description                                             |    parent_install_date     |   container_remarks    | barcode  | print_fg | width | height | length | institution_acronym | number_rows | number_columns | orientation | positions_hold_container_type 
--------------+---------------------+----------------+--------+-----------------------------------------------------------------------------------------------------+----------------------------+------------------------+----------+----------+-------+--------+--------+---------------------+-------------+----------------+-------------+-------------------------------
     14840471 |            18189039 | freezer        | DGR-12 | Freezer 12; 1st freezer to use Arctos Object tracking, beginning with rack 8 (3B); circuit 514E05D4 | 2019-02-06 12:02:35        |                        | DGR12547 |          |    60 |     90 |    150 | MSB                 |           3 |             11 | vertical    | freezer rack
     14844245 |            18189039 | freezer        | DGR-6  | Freezer 6                                                                                           | 2020-11-03 16:48:54.787725 | room circuit: 741F05D4 | DGR12749 |          |    60 |     90 |    150 | MSB                 |             |                |             | 
(2 rows)
```
