### ISSUE TITLE
Code Table Request - New CTATTRIBUTE_TYPE: 'label transcribed'

### ISSUE THREAD

**Issue by camwebb** [ArctosDB/arctos#4538]
**Goal**

To add a new specimen attribute which confirms completion of transcription of a label

**Context**

Digitization of herbarium specimen labels.

**Table**

Specimen attributes: `CTATTRIBUTE_TYPE`

**Proposed Value**

`label transcribed`

**Proposed Definition**

"A person has looked at the label in the image and confirmed that all possible data has been transcribed into Arctos, and that the identifiers on the image match the specimen record."

Note that the second clause means that the definition includes the 'image confirmed' attribute.

**Collection type**

Herb

**Attribute data type**

yes/no (Boolean)

**Attribute value**

yes/no

**Attribute units**

N/A

**Available for Public View**

Yes

**Comment by dustymc** [comment]
Mostly in the interest of this being applicable to more situations across more collections...

> in the image

Is that necessary? Maybe "s looked at the label or representation of the label..." or something?

>all possible data h

"relevant" (or something of the sort) instead of "all possible" for the same reasons? 

There's not a true boolean datatype for attributes, but an attribute using http://test.arctos.database.museum/info/ctDocumentation.cfm?table=ctyes_no as the controlled value should be close enough (I hope).

**Comment by camwebb** [comment]
> Mostly in the interest of this being applicable to more situations across more collections... "in the image" 
> Is that necessary? Maybe "s looked at the label or representation of the label..." or something?

Agree. This should be an attribute with as wide a domain as possible. Also, there is often no single 'the image' but many images, so the term 'representation' is better.

> "all possible data"  -> "relevant" (or something of the sort) instead of "all possible" for the same reasons?

Agree. But something in the wording should imply clearly that the action of transcription has been comprehensive/complete.

> There's not a true boolean datatype for attributes, but an attribute using http://test.arctos.database.museum/info/ctDocumentation.cfm?table=ctyes_no as the controlled value should be close enough (I hope).

Yes, `yes`/`no` is good.

Is there an alternative way of flagging completion of label data entry? I know there is an 'accepted' field in many tables, but these are for data elements, not the whole package.

**Comment by dustymc** [comment]
>A person has looked at the label(s) or representation of the label(s) and confirmed that transcription of relevant data is complete and comprehensive.

???

>alternative way

Nothing comes to mind, this seems reasonable/useful to me.

**Comment by camwebb** [comment]
> A person has looked at the label(s) or representation of the label(s) and confirmed that transcription of relevant data is complete and comprehensive.

Excellent. I might just add "digital" before "representation". Or... add "(e.g. in images)" after the second "label(s)" so that the reader is immediately pointed towards what will probably be the main use case: transcription from image media. Thanks.

**Comment by Jegelewicz** [comment]
This feels off to me. What label was transcribed? When there are multiple labels (and there often are) how do we know which one was transcribed? Pairing this attribute with either an image or a "verbatim label" attribute seems like a better way to ensure you know what exactly was transcribed. Although I am not quite sure how the "pairing" would occur.

**Comment by Jegelewicz** [comment]
See also #4541

**Comment by camwebb** [comment]
@Jegelewicz 

> This feels off to me. What label was transcribed?

Maybe there is a better way to define this? But the use case is clear: we need a flag to check when all the available metadata (which for plants is the specimen label and annotations) has been entered - it's a specimen thing not an image thing. We are embarking on a big cleanup; this flag could be kept external to Arctos, but I think it is more useful and sustainable if it it in Arctos. The 'processing history' suggestion would work if there was a state that was 'all available metadata on physical specimen transcribed'.

**Comment by Jegelewicz** [comment]
> all available metadata on physical specimen transcribed'.

still seems vague to me

Data from a label/tag? Data from a written catalog? Data from field notes? Data from a publication?

There are a lot of places data can be transcribed from and I think being more specific would be better, especially if we want to be sure we have transcribed "it all".

**Comment by wellerjes** [comment]
> Maybe there is a better way to define this?

We have been indicating the source of the information in "Remarks"; for example, [this specimen](https://arctos.database.museum/guid/CHAS:Herb:1000) has information "From label." and "From label and records." This can be even more specific (pointing to a specific archival box instead of the entire manuscript collection), depending on the collection/institutional needs.

For herbarium collections, I'm looking for a way to confirm that the label on the herbarium sheet, that has been imaged and attached to the Arctos record, matches the data in Arctos. I've been coming across specimen records where locality has been imposed on an assumption (locality is listed as Chicago when it's actually in the suburbs) or dates that were mistranscribed years ago. I'm looking for a way (within Arctos) to confirm that I have double-checked that record matches; along the lines of event verification, but more broadly applicable.

**Comment by camwebb** [comment]
@wellerjes 

> along the lines of event verification, but more broadly applicable.

Yes, exactly

@Jegelewicz 

>>  all available metadata on physical specimen transcribed

> still seems vague to me. Data from a label/tag? Data from a written catalog? Data from field notes? Data from a publication?

Not sure why "metadata on physical specimen" is vague. "Written catalog", "field notes", "publication" are not attached to the physical specimen. But "Label/tag" is. Maybe thinking about herbarium sheets, where info is literally attached/glued and cannot be removed without damaging the specimen, is biasing the way I think about this issue?

**Comment by wellerjes** [comment]
>  info is literally attached/glued and cannot be removed without damaging the specimen

Agreed; we cannot provide access to the specimen without also presenting the label (either in person or digitally).

**Comment by Jegelewicz** [comment]
> Maybe thinking about herbarium sheets, where info is literally attached/glued and cannot be removed without damaging the specimen, is biasing the way I think about this issue?

Yes - we need to consider how other collections might view/use this attribute!

**Comment by wellerjes** [comment]
Could we make this attribute unique to herbaria? Or herbaria and art, with the possibility of expanding it to apply to archives in the future? Herbaria and Art collections have collector/creator notes that are much more likely to be attached directly to the specimen/artwork (by being written directly on the herbarium sheet or artwork), making it more difficult/impossible to separate from the specimen/object without damaging it. Proposed definition for the code table: "all inscriptions attached to this [specimen/artwork] have been transcribed"

Or we could rename the attribute to "transcription complete" and have a remarks field that we can use to indicate what exactly (in relation to the specimen/artwork) has been transcribed: the label attached to the herbarium sheet, the artist number in the bottom righthand corner, the field notebook associated with this specimen, etc.

**Comment by wellerjes** [comment]
The other thought I had was we could make this part of https://github.com/ArctosDB/arctos/issues/4541 instead of making a separate attribute?

**Comment by camwebb** [comment]
> Proposed definition for the code table: "all inscriptions attached to this [specimen/artwork] have been transcribed"

I like this. My vote is that this be an attribute, as original proposed here.

**Comment by Jegelewicz** [comment]
added - also added transcribed from ledger
