### ISSUE TITLE
Code Table Request - Edit definition of CTATTRIBUTE_TYPE: 'image confirmed'

### ISSUE THREAD

**Issue by camwebb** [ArctosDB/arctos#4539]
**Goal**

To expand the definition of `CTATTRIBUTE_TYPE`: 'image confirmed'. 

The current definition is: “A person has looked at the ALA Imaging Project image and confirmed that the identifiers on the image match the specimen record.” The specific project called 'ALA Imaging Project' has ended but the attribute is still useful. Expanding the definition should have no negative impact on the the meaning of this attribute for previous uses.

**Context**

Digitization of herbarium specimen labels.

**Table**

Specimen attributes: `CTATTRIBUTE_TYPE`

**Proposed Value**

`image confirmed` (NO CHANGE)

**Proposed Definition**

"A person has looked at the images and confirmed that the identifiers on the images match the specimen record."

**Collection type**

Herb

**Attribute data type**

yes/no (Boolean)

**Attribute value**

yes/no

**Attribute units**

N/A

**Available for Public View**

Yes

**Comment by dustymc** [comment]
```
select
    guid_prefix
from
    attributes
    inner join cataloged_item on attributes.collection_object_id=cataloged_item.collection_object_id
    inner join collection on cataloged_item.collection_id=collection.collection_id
where
    attribute_type = 'image confirmed'
group by guid_prefix;

 guid_prefix 
-------------
 UAMb:Herb
 UAM:Herb
 UTEP:Herb

```

@mvzhuang any objections to this?

**Comment by dustymc** [comment]
done
