### ISSUE TITLE
Code Table Request - New catalog record attribute "processing history"

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4541]
**Goal**
We have been entering this information under collection remarks, but if there is a lot of information in remarks, it tends to get lost / jumbled together.

**Context**
"processing history" will include information about: when the catalog record was inventoried (especially useful for legacy data), who transcribed the label, etc. It shows how other individuals have contributed to the catalog record's history in ways other than identification.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type

**Proposed Value**
processing history

**Proposed Definition**
[ Clear, complete, non-collection-type-specific definition of the new value. ]

**Collection type**
Arch, ES

**Attribute data type**
[ "Attributes" may apply to catalog records, parts, localities, and collecting events. You must specify a datatype (free-text, categorical, or number+units) if this request involves attributes. ]

**Attribute value**
[ For categorical attributes, code table controlling value  ]

**Attribute units**
[  For number+units attributes, code table controlling units  ]

**Available for Public View**
[  **Yes | No** to indicate whether the proposed value will be available for public view or available only for logged in operators.  ]

**Priority**
[  Please choose a priority-label to the right.  ]

**Comment by Jegelewicz** [comment]
@wellerjes can you provide a proposed definition? Thanks!

**Comment by Jegelewicz** [comment]
From @ewommack 

> processing history" will include information about: when the catalog record was inventoried (especially useful for legacy data), who transcribed the label, etc. It shows how other individuals have contributed to the catalog record's history in ways other than identification.

A lot of that sounds like attributes that might be available or good to touch base with Archive collections before creating. It sounds like something they might be recording already.

**Comment by Jegelewicz** [comment]
From @AJLinn 

> "processing history" will include information about: when the catalog record was inventoried (especially useful for legacy data), who transcribed the label, etc. It shows how other individuals have contributed to the catalog record's history in ways other than identification.

In Getty's [CDWA](https://www.getty.edu/research/publications/electronic_publications/intrometadata/crosswalks.html) (Categories for the Description of Works of Art, which is what FA is trying to use to guide many of their decisions) number 25 is "Cataloging History" where one records the cataloger name, cataloger action, cataloging date, and remarks, which sounds like it could easily be an attribute and have a controlled vocabulary list for the cataloger action, which might include things like inventory, update, transcribe, correction, etc.

I couldn't find anything at Dublin Core, which is one metadata schema used by archives (also listed on the amazing mapping table linked to above).

**Comment by Jegelewicz** [comment]
From @mkoo 

HI Jessica, we have only just started cataloging in the MVZ Archives and already I see some value to these. I have questions though:

2. **processing history** - I like this a lot. Originally we've been using accessions but cant continue that as the objects in an accession all have independent histories now. I also think this may have value beyond the cultural collections. We could potentially use it to flag specimens which are stored in 70% etoh but not fixed on formalin, for example. Anyone else think so?!

Also, we need to make a Archives team on github-- just havent done it yet!

**Comment by Jegelewicz** [comment]
**processing history**

Shouldn't this be an event? I hope that some of you can attend tomorrow's GBIF webinar, because I think we may find that we are under-utilizing events. An event type = "inventory" or "transcription" would allow for much more detailed information about who did the thing, when and what the results were.

EXCEPT

> >flag specimens which are stored in 70% etoh but not fixed on formalin,
> 
> That should definitely be "partward" - part remarks if it must be a remark, but why not just use the structured and defined [concept](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_preservation#ethanol__70_)?

With multiple parts per catalog record, we do not have a really good way to associate an event with a single part. Sure we have some duct tape, but I think we need to be taking a loser look at how we catalog in the digital world and either figure out a way for events to be associated with parts or start cataloging individual parts. Don't shoot the messenger....

**Comment by Jegelewicz** [comment]
From @mkoo 

>>processing history

>>Shouldn't this be an event? I hope that some of you can attend tomorrow's GBIF webinar, because I think we may find that we are under-utilizing events. An event type = "inventory" or "transcription" would allow for much more detailed information about who did the thing, when and what the results were.

Definitely not an event -- we have so much legacy stuff and makes little sense to find anything there for the archives

Hope this makes sense-- I could attend an upcoming meeting to discuss more

**Comment by AJLinn** [comment]
> Collection type
> Arch, ES

This is not restricted to just Archives and Earth Sciences... it should be made available to all collections, given the core goal of proper documentation of ongoing collection management processes!

**Comment by Jegelewicz** [comment]
> processing history is more related to what happens once it enters our care in the collections.

See new GBIF data package models. The things that happen after stuff is in our possession can be very important! However, an attribute in Arctos can almost be viewed as an event IF the date and determiner are complete. The only thing missing is the WHERE (which can possibly be inferred, but potentially not always....).

**Comment by campmlc** [comment]
I've been thinking for awhile that we need separate relational modules to display all the data related to a specimen, rather than trying to shove everything into the catalog record interface or flat search results. We could have a "collection management module" that tracks the history of the object and /or it's parts, and provides some management tools. Some components of the data could be viewed on the catalog record page, but they could be more easily viewed, tracked, and managed in a separate interface.

**Comment by Jegelewicz** [comment]
Add this attribute - but this could be useful at the accession level - with some magic to push it all to individual catalog records. Need to file an issues.

installed
verified presence
verified label

other categories

**Comment by Jegelewicz** [comment]
The term has been added to the code table. @dustymc now we need a table for the categories.

**Comment by dustymc** [comment]
I'll go next task, but I'm not going to get there today - how are you going to prevent someone from using it before there's a CT and making a giant mess?

**Comment by Jegelewicz** [comment]
The only collection type that can use it right now is Vert.....

**Comment by wellerjes** [comment]
@dustymc do you have an estimate of when this will be implemented? Just trying to plan ahead. Thanks!

**Comment by dustymc** [comment]
I'll try for this week

**Comment by dustymc** [comment]
Done

```
arctosprod@arctos>> \d core.ctprocessing_history
                      Table "core.ctprocessing_history"
       Column       |         Type          | Collation | Nullable | Default 
--------------------+-----------------------+-----------+----------+---------
 processing_history | character varying(60) |           | not null | 
 description        | character varying     |           | not null | 
Indexes:
    "ix_u_ctprocessing_history" UNIQUE, btree (processing_history)
Triggers:
    tr_log_ctprocessing_history AFTER INSERT OR DELETE OR UPDATE ON ctprocessing_history FOR EACH ROW EXECUTE FUNCTION trigger_fct_tr_log_ctprocessing_history()

```

@Jegelewicz want to wire it up and add some data?

**Comment by Jegelewicz** [comment]
The term is linked to the new code table - I added two terms from stuff above, any new things should come from new code table requests (and the terms I added may need better definitions). Closing
