### ISSUE TITLE
error feedback HELP!

### ISSUE THREAD

**Issue by SerinaBrady** [ArctosDB/arctos#4544]
Hi, 

I went to bulkload ASNHC Mammal records and I received this error. Please help!

Thanks!

![error](https://user-images.githubusercontent.com/86243942/162998102-3b3b818e-9c38-4ab7-8507-2b473a4204f3.JPG)

** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **

** Outages should be reported to the contacts listed at https://arctosdb.org/arctos-down/ **

** Arctos Documentation is http://handbook.arctosdb.org/ **

** Learn more about Arctos at https://arctosdb.org/ **

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **

**Comment by dustymc** [comment]
psql:/usr/local/webroot/temp/excopy_ssbrady_20220412100411188_726.sql:1: ERROR: column "attribute_remark_2" of relation "bulkloader_stage" does not exist

**Comment by SerinaBrady** [comment]
Thank you!
________________________________

**Comment by SerinaBrady** [comment]
Another issue! I get the same error when I go to create an agent. Not sure why; I haven't had this problem before.
Thanks!

**Comment by SerinaBrady** [comment]
That worked, thank you!
________________________________

**Comment by SerinaBrady** [comment]
Okay, hopefully last question. 
I received this error after I had marked the data to load: "<html>
<body>


duplicate key value violates unique constraint "ix_collector_coid_aid_role"
--


<br class="Apple-interchange-newline">
</body>
</html>"
No idea what that means. Any help is appreciated!
![image](https://user-images.githubusercontent.com/86243942/163018127-2c339bb5-eaf8-449a-9e07-c2a362d6ccea.png)

**Comment by campmlc** [comment]
Do you have the same collector and collector role twice in the same record?
e.g. name/collector and name/collector?

**Comment by SerinaBrady** [comment]
That I did (whoops!). Thank you!
________________________________
