### ISSUE TITLE
Agent disambiguation Frank Stephens

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4550]
[Frank Stephens](https://arctos.database.museum/info/agentActivity.cfm?agent_id=10011370) has a library of Congress number and from there I added his birth and death dates. Once I did that, it became clear that some records attributed to him are either incorrect or should be associated with a different Frank Stephens.

birth = 1849
death = 1937-10-05

ASUMZ records indicate that he collected things after his death. @bfluker any chance you can find a middle name or some other way for us to ID your Frank Stephens?
![image](https://user-images.githubusercontent.com/5725767/163235235-4b58fad5-5ad4-4fa9-af3c-664cbe9e1513.png)

In addition the UMNH:Bird begin and end dates for that collecting event should be updated to his birth and death dates if it is indeed the same Frank Stephens....

How should we handle these things when they are discovered?

**Comment by Jegelewicz** [comment]
The plot thickens?
After a bit of research, perhaps the inverts were really collected by [Kate Stephens](https://arctos.database.museum/info/agentActivity.cfm?agent_id=21339009) and the dates are wrong?

**Comment by dustymc** [comment]
>ASUMZ records indicate that he collected things after his death.

General rule: Do not preemptively rule out the possibility those data can't be trusted.

>How should we handle

Easy and probably-mostly-kinda-sufficient: ignore it unless you have some immediate and compelling reason not to, false positives (searches including some stuff from some other similarly-named agent) are less-evil then the easily-accessible alternatives.

Almost as easy but future users will hate you less: ignore the data, add a flag (there's some issue where I think I suggested expanding http://test.arctos.database.museum/info/ctDocumentation.cfm?table=ctagent_status for that purpose, I can't find it...)

Ideal (unless you're wrong - eg by trusting incorrect dates - in which case this is pure evil): make a new "not that Frank Stephens" and use https://github.com/ArctosDB/arctos/issues/4122 to move the suspect records.

Even Idealier (excepting same possibilities): above, plus file an issue to require some sort of 'dates within lifespan' control (which would probably involve more cleanup than we can bite off, but would be cool....)

Edit from your plot thickening: toldyaso....

**Comment by Jegelewicz** [comment]
BTW, an incoming collection has an agent name = F. Stephens. @ehalverson26 based upon whatever F. Stephens did in your collection would you say they were [Frank Stephens](https://arctos.database.museum/agent/10011370) or someone else?

**Comment by bfluker** [comment]
@Jegelewicz I have not been able to find any middle initials for the Frank Stephens that shows up in our collections. It looks like Frank and Marie were related to Bill Stephens (a student here at Arkansas State back in the late 1970s. Here is an image of Bill's field notebook and Frank only made a handful of collections
![_DSC0476](https://user-images.githubusercontent.com/67377346/163413979-974c368f-4b18-4b48-b283-aad40de3ea9f.JPG)
![_DSC0440](https://user-images.githubusercontent.com/67377346/163413991-61cc19c9-83c6-4c56-b8ba-d3c0a481c2c5.JPG)
.

**Comment by dustymc** [comment]
>this

Thx, next release.

**Comment by Jegelewicz** [comment]
Also just caught that identifications were by the wrong agent and updated them all.

**Comment by ehalverson26** [comment]
@Jegelewicz I looked into our F. Stephens and his collecting (three records) happened in California in 1903, so it seems legitimate that it could be the same Frank Stephens that is already and agent in Arctos. Should I go ahead and change our data to Frank Stephens?

**Comment by Jegelewicz** [comment]
> it seems legitimate that it could be the same Frank Stephens that is already and agent in Arctos. Should I go ahead and change our data to Frank Stephens?

Yep!

**Comment by dustymc** [comment]
Done?
