### ISSUE TITLE
Feature Request - Find low quality data when collection/identification dates are outside birth and death range of the agent

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4551]
From #4550 
> plus file an issue to require some sort of 'dates within lifespan' control (which would probably involve more cleanup than we can bite off, but would be cool....)

**Is your feature request related to a problem? Please describe.**
Our data looks less than "research grade" when we are attributing actions to people who have not been born or are dead at the time of the action.

**Describe what you're trying to accomplish** 
Increase data quality. Disambiguate agents.

**Describe the solution you'd like**
If any date associated with an agent action is before they were born or after their death, it should raise a red flag that either the date or the agent is incorrect.

**Describe alternatives you've considered**

**Additional context**
This could also be very helpful when trying to determine which agent is YOUR F. Stephens

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by ewommack** [comment]
Agents Committee discussed that this tool would be really useful for helping with a first pass of all Agent clean-up.

**Comment by dustymc** [comment]
collecting dates are in https://arctos.database.museum/Reports/cat_record_reports.cfm?report_name=dates:%20collecting%20vs.%20collector, need new report for identification dates

**Comment by Jegelewicz** [comment]
Here is an example of some stuff that could be cleaned up

Collector = [Joseph William Winthrop Spencer](https://arctos.database.museum/agent/21327113)
Dates Looks like some stuff was entered with placeholders:
![image](https://user-images.githubusercontent.com/5725767/184026708-b6d85fe2-2065-4e17-a041-214b5d15ebb8.png)

(Note - the identification dates and specimen event dates are also 1840-01-01!)

Affected records - https://arctos.database.museum/saved/1660169124103

To Do:
1. Change all collection event begin dates to agent born date
2. Change all collection event end dates to agent died date
3. Add collecting event remark - "begin and end dates from collector birth and death dates"
4. NULL all determination dates
5. Change specimen event assigned by and date to agent entered by and date

@dustymc this seems like a lot - but it would be great if we could "make it so"!

**Comment by dustymc** [comment]
New report: https://arctos.database.museum/Reports/cat_record_reports.cfm?report_name=dates:%20identification%20determiner
