### ISSUE TITLE
Create Locality Page gone???

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#4552]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Create Locality is no longer on the menu and the link to the create locality page doesn't work.

**To Reproduce**
1. On the menu go to Manage Data > Location >
2. Create Locality is gone.
3. Go to https://arctos.database.museum/Locality.cfm?action=newLocality
4. See nothing

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 100.0.4896.75

**Comment by cjconroy** [comment]
For me too. 
<img width="275" alt="Screen Shot 2022-04-13 at 12 20 37 PM" src="https://user-images.githubusercontent.com/5749672/163254519-80583da8-ce8a-4268-9b08-7a546e748f9f.png">

**Comment by dustymc** [comment]
Suggest using the clone functionality - I think it's less likely to result in near-duplicates - but I can bring the 'create from nothing' code back if necessary.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Cloning was what I had been doing to get county level georeferencing for our public localities. With the new "use the geography spatial data" function I was looking forward to being able to just create them. In fact spent today updating our protocols for this method and adding a workflow to the new repository. My reasoning for switching methods was that it was easier to make mistakes in cloning (oops! accidently edited the original locality! or oops! accidently left in some of the original data that was supposed to be changed).

Could we just add to the top of the form some big red text that says don't forget to check for duplicates and a link to locality search?

**Comment by mkoo** [comment]
please see this issue for the future
