### ISSUE TITLE
Arctos Down - 1:50 pm MDT

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4553]
Please complete to the best of your ability.

## Unplanned Outage -,appears to be the case.
 - 2022-04-13 1:50 pm MDT
 - endless spinning blue browser wheel of death

## Planned Outage
 - Date and time outage will begin:
 - Date and time outage is expected to end:
 - Reason for outage:
 - Expected behavior during and after the outage:

## Communication before/during outage
- [ ] Pin this issue
- [ ] Banner updated @jegelewicz 
- [ ] Email sent to AWG 
- [ ] Email sent to Arctos Google Group 
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @jegelewicz
- [ ] Email sent to AWG 
- [ ] Email sent to Arctos Google Group 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by Jegelewicz** [comment]
It's working for me.

**Comment by campmlc** [comment]
Well, it seems odd that multiple institutions are having trouble. I don't
even get an error message - just spinning. And it was working an hour ago.

**Comment by mkoo** [comment]
Mariel, try a different browser? or even a different device if possible?
Im online and editing without issues (in CA anyway)
MK

**Comment by mkoo** [comment]
Which other institution?
The message from NMU was a clientside error, not Arctos
Was there another alert I missed?

**Comment by lin-fred** [comment]
It's working for me as well

**Comment by dustymc** [comment]
>odd that multiple institutions 

I'm not aware of that, but it would not be surprising. The whole internet is a little crazy today (and has been for the last month or so) - TACC is a big target, but they're not the only one.

https://www.digitalattackmap.com can be amusing.

**Comment by campmlc** [comment]
Well, it appears to be just me. Somewhere in the past hour, my account shut
down and can no longer load in Chrome. I never use other browsers, have no
saved passwords elsewhere. Why would my account on Chrome shut down?
Russians?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
It was working for me an hour ago, but now is not loading.

**Comment by dustymc** [comment]
It's still up....

**Comment by campmlc** [comment]
I still can't log in via Chrome or Firefox. What could possibly have
happened? I am trying to work under a deadline on an annual report, so this
is not good. I really need access.

**Comment by Jegelewicz** [comment]
It seems slow - but working on my end.

**Comment by Jegelewicz** [comment]
Just got 500 Internal Server Error

**Comment by campmlc** [comment]
When I try to log in with Firefox, I enter my username and password and
nothing happens. When I try Chrome, the browser just spins.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I'm also now getting 500 Internal Server Error on Chrome and Firefox.

**Comment by lin-fred** [comment]
It's still working for me

**Comment by Jegelewicz** [comment]
I logged out and back in and it worked.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
And, it's back up now.

**Comment by dustymc** [comment]
There was a slowdown, I took the opportunity to bounce the application layer.

**Comment by campmlc** [comment]
I'm back in.

**Comment by campmlc** [comment]
Some setting change that is causing university firewalls to slam shut? I
can access via my phone.
