### ISSUE TITLE
Feature Request - Agents: down with groups?

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4555]
**Is your feature request related to a problem? Please describe.**

ref: https://github.com/ArctosDB/arctos/issues/4549#issuecomment-1098329575

We have [group agents](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctagent_type#group), they're not much used (805 agents, 417 having at least one member), probably not consistently used in the UI, and it just seems like unnecessary complication. 

**Describe what you're trying to accomplish** 

Simplify and unify.

**Describe the solution you'd like**

* convert agent_type=group agents to something else ('other' maybe)
* link any group members with some sort of relationship ([associate of](https://arctos.database.museum/info/ctDocumentation.cfm?table=CTAGENT_RELATIONSHIP#associate_of) maybe, but something else or something new would work too)
* get rid of the type, table ``group_member``, and any special handling

**Describe alternatives you've considered**

Kludge on.

**Additional context**

I don't think group agents do anything that "normal" agents and relationships aren't capable of; we now have a robust agent relationship table, let's just use it.

**Priority**

High-ish; we seem to have some momentum regarding agents, let's not lose it.

**Comment by Jegelewicz** [comment]
I agree with this. From the list in https://github.com/ArctosDB/arctos/issues/4549#issuecomment-1098329575 I added members to the groups that I could (but some of them are very low quality members), I converted a few to person agents - seems they were just created incorrectly as groups, and I marked a few as duplicates (one consequences of groups is that you end up with groups that are names differently, but include the same agents). I also marked a large number as organization and I think we should change those, but can you do that in bulk? That will leave some super low quality group agents and a bunch that should really just be verbatim (expeditions, etc.). or I suppose one might argue those are "other agents". Anyway, let me know how I can help from here.

[Group Agent Cleanup.csv](https://github.com/ArctosDB/arctos/files/8485820/Group.Agent.Cleanup.csv)

**Comment by campmlc** [comment]
Group agents are highly useful for giving credit for participants of expeditions, but they haven't been used correctly because for a long time they weren't working properly to add people. I would like to see this use expanded and imoroved rather than eliminated. @jldunnum

**Comment by dustymc** [comment]
> expanded and imoroved 

That's in no way incompatible with what I proposed, just use the mechanism that all other relationships - and groups can't be anything else - use. 

As above, I'm fine with new relationships if necessary, just come up with a name, definition, and potentially functionality.

**Comment by Jegelewicz** [comment]
@dustymc how about we just transition all current groups so that the members have an "associate of" relationship to the group, then we dump the current "group" functionality? This is just a simplification so that all agents function in the same manner.

**Comment by ewommack** [comment]
> Group agents are highly useful for giving credit for participants of expeditions

> I think that this should be done via accessions - everything from an expedition goes into a single accession (with related permit!) and all of the expedition participants are listed as "received from". Adding a list of 20 people as "collector" doesn't add directly to anyone's real body of work and in fact it probably over-credits people by giving them credit for collecting everything from the expedition rather than the two things they actually collected.

Or maybe something with projects? I'm doing something similar with Projects and our 3D skull work with the UWY Library, and tying in each worker who is producing data into the project. That way they have a permanent page they can refer back to in their CV if they need.

**Comment by campmlc** [comment]
Both of those are good ideas, but without a group agent, thousands of
specimen collections and determinations just get put on the PIs name, and
many times they aren't even on the trip.

**Comment by Jegelewicz** [comment]
>  but without a group agent, thousands of specimen collections and determinations just get put on the PIs name, and many times they aren't even on the trip.

But right now all 191 of these "group" agents have NO MEMBERS - so who is getting credit for any of it? Do we have lists of names to add to the groups? 

1977 All U Of A   Student Art Exhibit
1997 Angelo State University Mammalogy   Class
1998 Angelo State University Mammalogy   Class
1999 Angelo State University Mammalogy   Class
2015 Angelo State University Mammalogy   Class
2018 Angelo State University Volunteers
2019 Angelo State University Volunteers
A. K. and K. L.
A. K. and L. K.
Alaska Pipeline Route Survey
Albatross Expedition
Albatross North Pacific Expedition 1906
Anderson et al
APEX program
APSU Students
Arizona Expedition
ASU App Team
B. , T. & F.
B. B. B. and D. J. M.
B. G. and C. H.
B. G. and C. H. and J. C.
B. G. and J. C. and C. H.
B. G. and J. C. and R. M. and J. P. C.
BILG Expedition
Bio 116 students
BIO Photography Group, Biodiversity   Institute of Ontario
Biobus 2010
Biol FW Inverts class
Biology 366 class
Biology 432 Class
Birdsell & Gilmer
Blue Oak Ranch Reserve Staff
BOLD ID Engine
Bolivian Expedition 1987
Bolivian Expedition 1996
Bosque Ecosystem Monitoring Program
Boulder County Sheriffs Deputies
BYU AEC Ecology Project
BYU Herp Class
BYU Students
California Expedition
California Expedition of 1901
Camp Ockanickon Campers
Carnegie Museum and Indiana University   Expedition
Carnivore Initiative Project
Colorado Museum of Natural History South   American Expedition (1925-1926)
Colorado State University Wildlife   Management
CTNRC team
CU Expedition NW Colorado
CU Geology Party
CU Museum Expedition to Mexico
CWA
Dixie College Field Class
Ecology of Infectious Diseases Project
Evanston High School Biology Class
F and K
Field Mammalogy Class
Flora of North America Editorial   Committee
Florida Expedition
Florida Expedition, 1877
Geology Field Camp 1975, University of   Alaska Fairbanks
Geology field trip, fall of 1977
Gienger et al.
Gle/Buck,
Grinnel College Field Class
Herpetology class
HMC Collector
HMC Legacy Collector
J. R, CS
JHU Hanta Survey
Juniata Expedition, 1873
K. W. Philip, et al.
Kansas Mammal Atlas Project
Ladder Ranch Survey 1994
Ladder Ranch Survey 2000
Lone Star Cement Company personnel
Magna Site Expedition
Mammalogy Class
Mammalogy Class 1964
Mammalogy Class 1980
Mammalogy Class 1981
Mammalogy Class 1982
Mammalogy Class 1986
Mammalogy Class 1988
Mammalogy Class 1991
Mammalogy Class 1992
Mammalogy Class 1994
Mammalogy Class 1996
Mammalogy Class 1998
Mammalogy Class 2000
Mammalogy Class 2002
Mammalogy Class 2004
Mammalogy Class 2009
Mammalogy Class 2010
Mammalogy Class 2020 [JA Cook]
Maynard-Pratt Expedition
MSB - field trip
MSB Division of Mammals Staff (2020)
MSB DOM Volunteer
Museum Expedition
Museum Party
Native collector
Natural History Club
NCSU Herpetology class
North Arm Crew
Northern Michigan University Faculty
Northern Michigan University Guest
Northern Michigan University student
NPRA employees
Nuns at St Mary's Mission
Occidental College BIO 105 course
Occidental College BIO 260 course
Occidental College BIO 356 course
Occidental College BIO 369 course
Occidental College Oceanology course
Ornithology class
Pal. Expedition
Panama Hantavirus Project 2001
Panama Hantavirus Project 2002
Panama Hantavirus Project 2003
Panama Hantavirus Project 2004
Panama Hantavirus Project 2006
Panama Hantavirus Project 2007
Panama Hantavirus Project 2008
Panama Hantavirus Project 2010
Panama Hantavirus Project 2011
Panama SIGEO Climate Change Project
Parasitology 2014
Peter's family
Quillen Mr. & Mrs.
R. H. D. and K. T. J.
R. H. D. and S. J. M.
Red Des. Exepedition #1
Royal Ontario Museum Field Party
S. A. and S. L.
S. J. M. and A. S. H.
S. J. M. and J. B. F.
S. W. and M. K.
Scott Johnson's Nearshore Survey Team
Scripps Institution of Oceanography   VII-TOW Expedition
Sea of Cortez Expedition
senior class Innolo River High School
Sitka High School Field Science Class
sons of C. Olalla
sons of Teodomiro Mena
Spilogale Research Crew
Steere Expedition to the Phillipines
Stream Ecology Class UAF
students Northwest Florida State College
T. Park Ecology Class
Transfer from Ethnology
Treasure Island Scout Camp Staff
U Of A Art Exposition
U of A Seminar
U. S. Expedition
UAM & UCMP team
UAM ES Imaging Project
UC Berkeley Integrative Biology 174 class
UC Expedition
UCM 1969 Mexico Expedition
UCM Coahuila Expedition
UCM Excursion to Mexico
UCM Expedition
UCM Expedition for SE USA
UCM Expedition to Coahuila
UCM Expedition to SE USA
UCM Geological Party
UCM Magna Expedition
UCM Mexico Expedition
UCM SE Expedition
UCM Sonora Expedition
UCM Summer Expedition 1971
UCM Yucatan Expedition
UMC Expedition to Mexico
Unalakleet School students
University Acquisitions
University Expedition to NE Colorado
University of Arkansas Herp class 1974
University of Colorado Expedition to NW   Colorado
University of Wyoming Geology Class
UNM BIOL 487 Ichthyology
UNM Research Group
UNM Tropical Biology Class 2004
USDA Biological Expedition
USDA Forest Service Insect and Disease   Reports
Utah State Herp Class
Van Buren Expedition
Walker family
West Park Commissioners
WNMU Field Biology Class- 2005
WNMU Herpetology Class



</body>

</html>

**Comment by dustymc** [comment]
> just transition all current groups so that the members have an "associate of" relationship to the group, then we dump the current "group" functionality

Is that different than what I proposed?

>without a group agent,

Meh, keep it if you want, non-person agent type doesn't do anything anyway, I just want to get rid of the second type of relationship (=table group_member). I (probably) wouldn't even object to some sort of 'collected as part of group' relationship.

>collections and determinations just get put on the PIs name, and many times they aren't even on the trip.

No data structure can compensate for that.

**Comment by Jegelewicz** [comment]
> Is that different than what I proposed?

I don't think so - just trying to clarify.

**Comment by dustymc** [comment]
I think that's all functionally identical. It's either

* agent representing multiple entities-->normal relationship structure-->agent1,agent2

or 

* agent representing multiple entities-->special (group) relationship structure-->agent1,agent2

so same things on both ends (agents). Groups still look like arbitrary agents differentiated only by making us follow a separate path, which means we never focus on one path long enough to do cool(er) things.

**Comment by Jegelewicz** [comment]
@Nicole-Ridgwell-NMMNHS how's this? https://arctos.database.museum/agents.cfm?agent_id=21344806

**Comment by dustymc** [comment]
This is complicating other things, I'm going next task with

>@dustymc how about we just transition all current groups so that the members have an "associate of" relationship to the group, then we dump the current "group" functionality? This is just a simplification so that all agents function in the same manner.

which is identical functionality in a better-developed structure, unless someone comes up with a timely and compelling reason to do otherwise.

**Comment by Jegelewicz** [comment]
I think that's fair - it effectively does the same thing.

**Comment by campmlc** [comment]
Expedition agents are useful as group agents because they give credit to
the contributions of multiple members. We use them in MSB. The alternative
is to pick one member of an expedition and assign all the collecting and
preparing activities to them, which isn't fair and doesn't represent
reality. This happens too. I prefer to use the group agents. I have been
involved in many expeditions that I received no credit for as a collector
and preparator and determiner because only the name of the PI was used for
all attribution.

**Comment by Jegelewicz** [comment]
@dustymc there are still a few agents of type group because the term is till in the code table. Can we convert the few there and get rid of the term? Can we do this today?

**Comment by Jegelewicz** [comment]
I just did this - the agents marked as groups were all changed to organization and the term deleted from the code table.
