### ISSUE TITLE
Feature Request - agent relationship loader

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4558]
**Is your feature request related to a problem? Please describe.**
I am about to load over 500 agents for an incoming collection. I'd like to indicate clearly that these agents were generated by that institution even though they will be "created by me" in Arctos. 

**Describe what you're trying to accomplish** 
An clear and concise overview of the goals; why are you asking for this?

**Describe the solution you'd like**
The ability to add relationships while bulkloading agents OR an agent relationship bulkload tool so that I can add the relationships after the agents are loaded.

**Describe alternatives you've considered**
I can add a remark, but I think it would be more powerful to create the relationship "associated with" between these agents and the requesting institution's organization agent (or collection agent when possible).

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by dustymc** [comment]
I'd use remarks. We DO NOT want these to fall through the filters we're setting up in https://github.com/ArctosDB/arctos/issues/4554 - they (presumably and hopefully) **want** to know that their B. Dickerman looks like a duplicate of our Bob, the relationship will remove it from any tools which might suggest that. Strongly suggest we limit relationships to real relationships - I'm not sure precisely what that means, but it's something beyond "one of the hundreds of places Dickerman seems to have dropped off a bird or two" (which is precisely what you're proposing to create).

That aside, "add relationships while bulkloading agents" can't work - you'll end up trying to make relationships within the file, one of them must load before the other, confusing errors ensue.

A standalone bulkloader is no problem. (I thought there was an issue, but I can't find it??)

**Comment by Jegelewicz** [comment]
> "one of the hundreds of places Dickerman seems to have dropped off a bird or two" (which is precisely what you're proposing to create).

This happens eventually when catalog records use them as a collector, it just makes it easier to see up front where an agent has activity. I'm OK with not doing it, but we need better methods for evaluating incoming agents (I am about to file an issue).

> A standalone bulkloader is no problem. (I thought there was an issue, but I can't find it??)

Then let this be that issue!

**Comment by ewommack** [comment]
> I am about to load over 500 agents for an incoming collection. I'd like to indicate clearly that these agents were generated by that institution even though they will be "created by me" in Arctos.

I have used that info when double checking names. Agents added by people from my collection definitely throw up a flag to me that this is probably the name I want when adding someone to a record.

**Comment by Jegelewicz** [comment]
Closing because this isn't super necessary. Will reopen if needed.
