### ISSUE TITLE
Feature Request - agent status vocabulary

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4559]
**Is your feature request related to a problem? Please describe.**

I just declared a corporation "alive." Can we come up with better vocabulary?

**Describe what you're trying to accomplish** 

Terms that imply "still there" (and etc.) to all Agents.

**Describe the solution you'd like**

Better terms?

**Describe alternatives you've considered**

Current terms seem to be functional enough, just strange. We could just expand documentation.

**Additional context**

* https://arctos.database.museum/info/ctDocumentation.cfm?table=ctagent_status
* https://github.com/ArctosDB/arctos/issues/4554

**Comment by Jegelewicz** [comment]
extant = in existence

I don't know - I think we need different terms for orgs and people...it sucks, but saying a person is extant or operational doesn't feel very good. Is there a reason we have both "dead" and "died"? It seems like using died with no date is the equivalent of dead? Same goes for alive and born when there is no died?

people live and die, organizations are formed and dissolved

**Comment by dustymc** [comment]
>need different terms for orgs and people

I'll take awkward terms over that; I want to ask "[can this event realistically be associated with that Agent](https://github.com/ArctosDB/arctos/issues/4551)" and I may not know or care which pigeonhole the agent has been stuffed into.

>using died with no date

That's not structurally possible, and I think the "came into state/in state" distinction is useful.

>people .. are formed and dissolved

I giggled....

**Comment by Jegelewicz** [comment]
Well then, I say just use alive and dead for orgs because I'd rather offend an org than a person.....

**Comment by AJLinn** [comment]
I agree - I use the born/died all the time when I'm doing organizational agents for the date of incorporation or the date of dissolution. It is awkward but unambiguous.

**Comment by Jegelewicz** [comment]
Code Table Committee says just stick with alive and dead.
