### ISSUE TITLE
Need Help with Arctos Error

### ISSUE THREAD

**Issue by tgalfano** [ArctosDB/arctos#4561]
# Error Text
This page isn’t working
If the problem continues, contact the site owner.
HTTP ERROR 450

# Where it happened
When trying to move from homepage to search the arctos collections

# Steps to get there
Went to arctosdb.org
Clicked on:
Search Arctos
>Arctos collections
# Problem
Cannot get database to load so I can search it for specimen data. 
Tried a few days ago and had the same issue, used different browsers, restarted the computer etc 

# Solution
**Community response with directions for how to correct the problem**

**Comment by Jegelewicz** [comment]
@dustymc

**Comment by dustymc** [comment]
try again please
