### ISSUE TITLE
Agent Cleanup - C. C. C. Camp

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4562]
[C. C. C. Camp](https://arctos.database.museum/agents.cfm?agent_id=21294606)

I feel about 99% confident that this is really "[Civilian Conservation Corps Camp](https://en.wikipedia.org/wiki/Civilian_Conservation_Corps#Camps)".

Locations and dates of collection support this. The one "identified by" is probably just "use the collector as the identifier".

@wellerjes @byuherpetology

**Comment by byuherpetology** [comment]
Yes, I agree

**Comment by Jegelewicz** [comment]
BTW, I suggest we just change the name and change this agent into an organization.

**Comment by Jegelewicz** [comment]
Done
