### ISSUE TITLE
rebuild onRequestStart and checkRequest

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4564]
need rewritten in cfscript to avoid tags and whitespace

**Comment by dustymc** [comment]
This (of course!) turned into another rabbit warren, nothing visible should have changed but the background is running on modernized code, clicking around in test greatly appreciated.

**Comment by Jegelewicz** [comment]
How did that logo get there? Did I do that?

**Comment by Jegelewicz** [comment]
@dustymc I poked around a bit and didn't see anything weird (except for my own weird doings). Let me know if there is anything in particular I should poke.

**Comment by campmlc** [comment]
I poked randomly in the new data entry form, couldn't seem to figure out
how to customize, but them I haven't played with yet in production. Aren't
we supposed to be able to move the tables around or delete ones we don't
need?

**Comment by dustymc** [comment]
>customize

https://www.youtube.com/watch?v=QJeLNCn62dE

**Comment by ewommack** [comment]
Also check out the article in the last newsletter: https://us17.campaign-archive.com/?u=cfe3221343c60fe519031e616&id=a98156b9ab

**Comment by campmlc** [comment]
Yes, I watched that, but when I look at my data entry screen in test and
select "begin with a blank slate" - I can't move any of the tables around
like she does. Also my display is larger and more cluttered, but that could
be my laptop.
Another odd thing - when I logged in to test, I was immediately taken to
the edit page for an loan that I did not create and have never worked on.
