### ISSUE TITLE
Loan Shipment Mapping Tool not functioning properly?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4565]
Request: I need a map from Transaction Search Results, Map Loan Shipments for the MSB 2021 annual report, all MSB divisions, date range 2021-01-01 to 2021-12-31, in house agent =  Mariel Campbell. 
Problem: I can generate the map, but international shipments and potentially others are missing. For example, loan MSB:Mamm 2021.027.Mamm to France does not appear on the map. I'd like the map to show the global breadth of scientific interest in the DGR collections, but I need the map to show all shipments.
Priority: High, had hoped to complete this afternoon after losing time yesterday due to Arctos connectivity issues. Help?

**Comment by dustymc** [comment]
I don't have great tools, what you see is what they can do. https://github.com/ArctosDB/arctos/issues/2657 could be prioritized (or a better solution offered or whatever).

**Comment by campmlc** [comment]
So one of the missing loans is to the following agent, and I see his address on the loan summary. Why doesn't this map?
Shipped to Address: Pierre-Henri Fabre Molecular Biology Laboratory of the ISEM, Batiment 32 Equipe Phylogénie & Evolution Moléculaires (CC064 - RDC bat. 32) Institut des Sciences de l'Evolution de Montpellier (ISEM - UMR 5554 UM2-CNRS-IRD) Université de Montpellier - Place Eugène Bataillon 34 095 Montpellier Cedex 5 - France

**Comment by campmlc** [comment]
Here's another: Shipped to Address: [Johan Michaux Bât. B22 Labo de génétique de la conservation Quartier Vallée 1 chemin de la Vallée 4 Belgique](https://arctos.database.museum/agents.cfm?agent_id=21334922)
