### ISSUE TITLE
Curatorial Search Request - How many GenBank sequences associated with our collection?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4566]
I would like to request a report for all MSB collections - I need the total number of GenBank sequences (not catalog items) associated with MSB collections, ideally broken down by Division. 
Priority High - needed for grant proposal and annual report.

**Comment by dustymc** [comment]
added to cheatsheet

**Comment by campmlc** [comment]
Where is that?

**Comment by Jegelewicz** [comment]
https://docs.google.com/document/d/15e3b8WNErFPqg1SW-QNq0nI_RjiEEZjWQDznxIJNFHE/edit

**Comment by campmlc** [comment]
Wow, that's useful.

**Comment by Jegelewicz** [comment]
There is a link on the Write SQL page too.
![image](https://user-images.githubusercontent.com/5725767/163584580-b90646fe-aa9b-49c5-b461-f4181b271ebe.png)
