### ISSUE TITLE
Feature Request - data loans don't add project to catalog records?

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4570]
Confirm, fix if necessary - @campmlc what's the entity link?

**Comment by campmlc** [comment]
https://arctos.database.museum/guid/Arctos:Entity:1

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I have noticed this happening. Here is an example: https://arctos.database.museum/guid/NMMNH:Paleo:10086 is in https://arctos.database.museum/project/10003469 but that doesn't show up in the catalog record.
