### ISSUE TITLE
API question

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4572]
Took a crazy chance and got myself an API key. Using the documentation, tried this

https://arctos.database.museum/component/api/v1/catalog.cfc?method=getCatalogData?api_key=...&guid=MSB:Mamm:12345

And got this

```
XML Parsing Error: mismatched tag. Expected: </img>.
Location: https://arctos.database.museum/component/api/v1/catalog.cfc?method=getCatalogData?api_key=...&guid=MSB:Mamm:12345
Line Number 357, Column 9:
						</div>
--------------------------------------------------^
```

and yes, I used my key where the ... is in all this.

What am I doing wrong?

@camwebb advice?

**Comment by dustymc** [comment]
>c?method=getCatalogData?ap

should be

c?method=getCatalogData&ap

**Comment by Jegelewicz** [comment]
Woohoo! Thanks!

Documentation updated
