### ISSUE TITLE
Feature Request - Add disposition to parts table/download

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#4573]
**Is your feature request related to a problem? Please describe.**
I use parts table/download to pull up a list of part locations for visiting researchers. However, this download lacks the field part disposition. That makes it hard for me to determine what is not available for them.

**Describe what you're trying to accomplish** 
Add disposition to part table/download.

**Describe alternatives you've considered**
The alternative is to look at the records one by one, especially since #1669 hasn't been addressed. Perhaps adding disposition to parts table/download is an alternative solution to that issue? Or does this issue have the same computational infrastructure limitation?

**Comment by Jegelewicz** [comment]
Seems like a no-brainer? Get all "parts" info in a parts table download....

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks!
