### ISSUE TITLE
Code Table Request - HerpMapper Identifier

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#4574]
**Goal**
Link voucher records in Arctos to observation records hosted in HerpMapper.

**Context**
HerpMapper is a website similar to ebird or inaturalist where people can submit observation photos for herps, with place/time data. It aggregates observations from around the world, so HerpMapper identifiers in Arctos would likely be relevant for many Herp collections if they accept salvaged animals.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type

**Proposed Value**
HerpMapper ID

**Proposed Definition**
observation number assigned by HerpMapper.org

**Collection type**
Herp

**Other ID BaseURL**
https://www.herpmapper.org/record/
(e.g., https://www.herpmapper.org/record/321106 is now accessioned into the UCM:Herp collection)

**Priority**
Normal. We have a bulkloader of recently prepared specimens ready to go, all of which have a corresponding HerpMapper ID.

**Comment by Jegelewicz** [comment]
Sounds good to me - especially since you already have an example!
