### ISSUE TITLE
[CONTACT] uploading barcodes to containers

### ISSUE THREAD

**Issue by keg34** [ArctosDB/arctos#4575]
I need to upload a pile of (claimed) barcodes to Arctos to assign them to containers.  According to [this](https://handbook.arctosdb.org/how_to/How-to-Create-and-Edit-Containers.html) and past practice I need to go to Manage Data > Object Tracking > Create Container Series.  However, I don't see "Create Container Series" as an option under Object Tracking anymore.  Is this all handled through "Create Container (bulk)" now?  I see that there have been some changes to permissions, but I assume that admin_container should be sufficient to do what needs to be done here.  Is it possible that the aforementioned "How to" needs an update?  Apologies if I missed a discussion about this elsewhere.

**Comment by Jegelewicz** [comment]
@keg34 [Create Container (bulk)](https://arctos.database.museum/tools/create_container.cfm) is the tool you need. Let me know if it doesn't and we'll figure it out. Documentation definitely needs updating - we just can't find anyone with the time to do it!

**Comment by campmlc** [comment]
Yes, there has been a change. Use the Create Container (bulk) tool which is
now in the component loader system. It should be reasonably self
explanatory if you've used the other similar tools. Let me know if you have
questions!

**Comment by keg34** [comment]
Okay, great!  Thank you!  I figured that might be the case but figured I should ask before pushing buttons.  And yes, I fully understand the problem of "too many things to do and not enough minutes in the day to do them"!  Thanks to you all for being so responsive!
