### ISSUE TITLE
Berkeley mapper maps wrong coordinates

### ISSUE THREAD

**Issue by amgunderson** [ArctosDB/arctos#4576]
**Describe the bug**
The 3 ermine shown here are mapped to an unaccepted locality in Berkeley Mapper. The correct results show up in the specimen results table prior to mapping. The table of data shown on the mapper page (shown after clicking on the dot over Baker Island indicating 3 specimens were collected there) shows the old incorrect coordinates. So it seems Berkeley Mapper is grabbing the wrong coordinates.
<img width="970" alt="Screen Shot 2022-04-18 at 1 17 25 PM" src="https://user-images.githubusercontent.com/8440698/163879497-0b68c4cf-b2e8-4f06-acf3-1b0145245032.png">

**Priority** a black hole of despair.

**Comment by dustymc** [comment]
I can't reproduce - BM should be mapping all ``specimen_event.verificationstatus != 'unaccepted'`` events, and I can't get it to do otherwise.

**Comment by amgunderson** [comment]
If you search for Mustela erminea and Island=Prince of Wales you will find 26 specimens. The little map on the search result page shows no specimens on Baker Island, but when you map on berkeley mapper 3 specimens appear on Baker Island based on coordinates in an unaccepted specimen event. This worries me because I assume it does this for other specimens, mapping unaccepted coordinates.
I will delete the unaccepted events and see which coordinates it maps then.

**Comment by amgunderson** [comment]
Okay, so Berkeley mapper maps all events not just one dot per specimen? I see here 2 specimens are mapped twice to the same dot.
<img width="891" alt="Screen Shot 2022-04-20 at 9 34 01 AM" src="https://user-images.githubusercontent.com/8440698/164289733-4c955fb7-99eb-4dd3-94d3-e2bccd9fea20.png">

So I have to delete all unaccepted events to stop this? Why can't it only map accepted events? Why does it do this? It should be 1 dot per specimen as the default and have an option to map events if that is somehow useful for anyone.

**Comment by dustymc** [comment]
Got it, thanks. There was in fact a problem, I'd sort of accidentally fixed that in test a couple days ago. Calling this in next release.

>have to delete all unaccepted events to stop this? 

No!

>it only map accepted events? 

It could, would need discussion, it will (properly) be mapping "not unaccepted" in next release. (And most entry points, although probably not the most common, are doing that in production now.)

>It should be 1 dot per specimen

You can set that (sorta, I don't think there's an option to reduce to just dots).

<img width="1352" alt="Screen Shot 2022-04-20 at 10 52 52 AM" src="https://user-images.githubusercontent.com/5720791/164292505-e9094b51-4b28-4429-b46c-f421ee88c70a.png">

>as the default

I don't have that ability (or don't know how to invoke it if I do).

**Comment by campmlc** [comment]
my two cents - map accepted and unverified, but don't map unaccepted.
