### ISSUE TITLE
Add Higher Geography - Point of the Mountain 7.5 minute Quad

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#4577]
Point of the Mountain 7.5 minute quad (in Arizona) needed for a new locality. I'm not sure what the best option is for extracting spatial data. USGS Topo View has kml, GeoTIFF, and GeoPDF (https://ngmdb.usgs.gov/topoview/viewer/#12/34.5765/-109.9390). There is also https://www.arcgis.com/home/item.html?id=4bf2616d2f054fbe92eadcdc9582a765

**Comment by Jegelewicz** [comment]
@Nicole-Ridgwell-NMMNHS I know nothing about adding the spatial stuff, but if you need this geography, I say go ahead and add it.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I don't have the manage_geography role.

**Comment by Jegelewicz** [comment]
What county(ies) is this topo in? The site appears to be down for maintenance so I can't get the map link....

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Navajo County

**Comment by Jegelewicz** [comment]
@dustymc attempting to add this.

**Problem 1**
Quad filed still won't accept more than 30 characters?

![image](https://user-images.githubusercontent.com/5725767/164491749-27b1f2da-86cb-498c-9bca-694c615d1189.png)

<html><body>


ERROR_ID | 490DAAC8-B08A-4390-85630FA2C2C88409
-- | --
ERROR_TYPE | SQL
ERROR_MESSAGE | ERROR: value too long for type character varying(30)   Where: SQL statement "insert into log_geog_auth_rec( GEOG_AUTH_REC_ID, username, action_type, change_date, n_CONTINENT_OCEAN, n_COUNTRY, n_STATE_PROV, n_COUNTY, n_QUAD, n_FEATURE, n_drainage, n_ISLAND, n_ISLAND_GROUP, n_SEA, n_SOURCE_AUTHORITY, n_GEOG_REMARK ) values ( NEW.GEOG_AUTH_REC_ID, session_user, 'inserting', LOCALTIMESTAMP, NEW.CONTINENT_OCEAN, NEW.COUNTRY, NEW.STATE_PROV, NEW.COUNTY, NEW.QUAD, NEW.FEATURE, NEW.drainage, NEW.ISLAND, NEW.ISLAND_GROUP, NEW.SEA, NEW.SOURCE_AUTHORITY, NEW.GEOG_REMARK )" PL/pgSQL function trigger_fct_tr_log_geog_update() line 69 at SQL statement
ERROR_DETAIL |  
ERROR_SQL | INSERT INTO geog_auth_rec ( 				geog_auth_rec_id, 				continent_ocean, 				country, 				state_prov, 				county, 				quad, 				feature, 				drainage, 				island_group, 				island, 				sea, 				SOURCE_AUTHORITY, 				geog_remark 			) VALUES ( 				10016165, 				'North America', 				'United States', 				'Arizona', 				'Navajo County', 				'Point of the Mountain 7.5 minute', 				null, 				null, 				null, 				null, 				null, 				'https://en.wikipedia.org/wiki/Navajo_County,_Arizona', 				'https://ngmdb.usgs.gov/ht-bin/tv_browse.pl?id=5ff564b3ecae7e0713e8e938587ce936' 			)

</div>
</body>
</html>

So I shortened the quad name to Point of the Mountain 7.5 min (not ideal) then...

**Problem 2**
Not sure what this means?
![image](https://user-images.githubusercontent.com/5725767/164491392-f2536724-0d3b-4631-9be7-dc2c82c3f64e.png)

<html><body>


ERROR_ID | 7C3C0286-F0E9-4681-9266D8CB36E082D0
-- | --
ERROR_TYPE | expression
ERROR_MESSAGE | The key [GEOG_AUTH_REC_ID] does not exist.
ERROR_DETAIL |  

</div>
</body>
</html>

**Comment by dustymc** [comment]
(1) is the log, it's updated. If that doesn't fix the second, let me know how to get there.

**Comment by Jegelewicz** [comment]
OK 1 is fixed. Click save changes after creating geography and still get

<html><body>


ERROR_ID | 3D605186-050C-4EA0-ABBBDB992046790E
-- | --
ERROR_TYPE | expression
ERROR_MESSAGE | The key [GEOG_AUTH_REC_ID] does not exist.
ERROR_DETAIL |  

</div>
</body>
</html>

**Comment by dustymc** [comment]
I need more detail, I can't get there

**Comment by Jegelewicz** [comment]
I'm here
![image](https://user-images.githubusercontent.com/5725767/164519693-c1d7d1ef-352c-4315-bbf8-3c2bc9b9b033.png)

select Create, then I'm here
![image](https://user-images.githubusercontent.com/5725767/164519765-2c5746a7-1bed-4bde-bdf6-92d57b9b2e41.png)

force create, then error

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Looks like it did actually create the geography, when I search for it, there are now two duplicate entries.

**Comment by dustymc** [comment]
Thanks, that's what I needed, next release.

Yes there's a "min" and a "minute" - @Jegelewicz fix plz.

**Comment by Jegelewicz** [comment]
OK, but both times instead of seeing a successful term creation I received the above error - no way it seemed that anything was created?

**Comment by dustymc** [comment]
Yes, that's the bug that's squashed for next release.

**Comment by Jegelewicz** [comment]
OK so I picked the min one and deleted it, but after selecting delete just got a white screen with the Arctos header and it's still there....

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Since it is there, I am going to go ahead and use the "minute" version of the quad.

**Comment by dustymc** [comment]
also in next release - thanks!

**Comment by Jegelewicz** [comment]
Done - thanks!
