### ISSUE TITLE
Pick Collecting Event broken?

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#4578]
**Describe the bug**
I'm trying to add a new specimen event to a record, but when I try to pick a collecting event, the pick button next to the collecting event doesn't work.

Background: A curator corrected the locality for this specimen: https://arctos.database.museum/guid/NMMNH:Paleo:64940. I've marked the current events (public and private) as unaccepted and am trying to add new events.

**To Reproduce**
1. Go to specimen record.
2. Click edit on the top corner of the locality box.
3. Scroll down to Add Specimen/Event
4. Fill in event type, event assigned by agent, assigned date, and verification status
5. Click pick new event
6. Search for collecting event by locality name, in this case =NMMNH:Paleo:L-8621 (by the way this comes up with two identical collecting events, not sure why they haven't been merged)
7. Click the pick button next to the event
8. Nothing happens

**Expected behavior**
It 'picks' the locality and returns me to the add specimen event form.

**Screenshots**

screenshot, red circle around the button that doesn't work:
![image](https://user-images.githubusercontent.com/47402809/164063700-65e2362f-ce43-4d52-821a-93aae253b7d4.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 100.0.4896.127

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by dustymc** [comment]
> why they haven't been merged

Different verbatim coordinates.

The pick fix is in next release - it's hanging on singlequotes in the data, I encoded that so the picked values will be ugly but should also work for about anything.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> Different verbatim coordinates.

They looked identical, so must be some minor difference, I'll see if I can fix.

> The pick fix is in next release

Thank you!
