### ISSUE TITLE
Agents with low quality preferred names

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4579]
Today I came across many agents with low quality preferred names. One example is C. E. Brown whose agent record record included his full first and middle names in the Agent names section. These low quality preferred names mean I waste time researching whether C. E. Brown might be the same person as Charles E. Brown from an incoming collection (it most certainly is), which I could have seen directly had the agent preferred name actually been Charles Edward Brown as was indicated via first_name, middle_name and last_name in the agent record.

I propose that we create a list of agents with preferred names that include initials, but also include complete first and/or middle name in those agent name fields and we update preferred name to be the most complete name we have for any given agent. This could save incoming collections considerable time when attempting to normalize agents.

C. E. Brown - changed to [Charles Edward Brown](https://arctos.database.museum/agents.cfm?agent_id=10007905)
C. J. Maynard - changed to [Charles Johnson Maynard](https://arctos.database.museum/agents.cfm?agent_id=10007905)

Also note that I was able to associate both agents with a Wikidata item once I had their full name...

**Comment by dustymc** [comment]
I want to agree, and I want to not.

If https://github.com/ArctosDB/arctos/issues/4554 is in fact a step on a path to letting agents prefer whatever name they want, then 'CE' is (or will be) just fine and I'd rather not do this. (That would probably involve some generated and unique-keyed name type - displayed or not - in which we'd assemble 'Charles Edward Brown'.)

If we're not going in that direction, or maybe even if we're not going in that direction immediately, then this seems like something we should do.

Here's a starting point, Just In Case.

```
select agent.preferred_agent_name,
concat_ws(' ',fn.agent_name,mn.agent_name,ln.agent_name) as generated_name
from
agent
inner join agent_name fn on agent.agent_id=fn.agent_id and fn.agent_name_type='first name'
inner join agent_name mn on agent.agent_id=mn.agent_id and mn.agent_name_type='middle name'
inner join agent_name ln on agent.agent_id=ln.agent_id and ln.agent_name_type='last name'
where agent.preferred_agent_name != concat_ws(' ',fn.agent_name,mn.agent_name,ln.agent_name)
```

**Comment by Jegelewicz** [comment]
Sigh.

Couldn't figure out why D. Dalager was on the list twice...

![image](https://user-images.githubusercontent.com/5725767/164093112-2855be16-913b-41c6-adcb-d92edaf2c65f.png)

**Comment by Jegelewicz** [comment]
And apparently I did that!

**Comment by Jegelewicz** [comment]
There are 3,155 rows in the results. I see no reason to make a bunch of manual updates - I'd like to see us agree to just do it. Of course first we will need to clean up the agents that have more than one first_name, middle_name and/or last_name.

**Comment by ewommack** [comment]
> Sigh.

> Couldn't figure out why D. Dalager was on the list twice...

Ok walk me through what is wrong with the Delaine N. Dalager entry? Is it coming up twice because of the aka?

**Comment by Jegelewicz** [comment]
There is a first name = D. and a first name = Delaine

The script Dusty wrote made combinations of first, middle and last name so this person had two D. N. Delager and Delaine N. Dalager.

**Comment by ewommack** [comment]
> There is a first name = D. and a first name = Delaine

Ah, thank you. So if we can clarify something in an agent it is better to replace the original poor quality first name (D.) with the full name (Delaine), and then write an aka with the initials spelling of the name.
Do I have that right?

**Comment by dustymc** [comment]
Very very tentatively closing this. I think we have to get past the idea that "D." (or any other string) is somehow low quality (maybe that's just what they prefer, or what they were given by someone for some reason), and rely on context (dates, relationships, etc.) for "quality," even when picking.

If you don't know that stuff, then verbatim agents are functionally equivalent and what you should be using.

That said, I also don't want to ever encourage losing or withholding information. Delaine (probably) doesn't have to be in any particular place, but if they've used that at some point then it should be included somewhere.

https://github.com/ArctosDB/arctos/issues/4554
