### ISSUE TITLE
Help bulkloading higher geography

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4580]
@dustymc please see https://github.com/ArctosDB/data-migration/issues/1153

**Comment by Jegelewicz** [comment]
@dustymc poke

**Comment by dustymc** [comment]
Still only one me...

(And this has no priority so it's nowhere near the top of my list, and following priority lead to some stuff I really don't want to deal with yesterday, so if you have any clever ideas.....)

**Comment by Jegelewicz** [comment]
loaded manually
