### ISSUE TITLE
notification maintenance

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4581]
Notifications are currently consuming 19MB of disk. I'll start the cleanup by daily-deleting notifications which aren't attached to users (so not visible by anyone), but that only accounts for 160 of ~17K notifications.

How can we delete notifications? After some time period, of after some time when some criteria is met, or just about anything else would work for me. I don't think there are reasonable alternatives to periodic cleanup. Note that nothing in notifications is only in notifications -  everything there (except the new '[shared](https://github.com/ArctosDB/arctos/issues/4500)' text) is available elsewhere.

Adding to AWG Agenda for a hopefully-quick discussion.

**Comment by Jegelewicz** [comment]
How many of these are "repeat notifications"? If the exact same "this locality doesn't match the county" notification is coming at me daily and I never intend to fix it, if there was a way for me to say this explicitly, then the notification could stop.

**Comment by dustymc** [comment]
IDK, some certainly are. I'm definitely up for better ideas for sorting/prioritizing/filtering/etc., but "hide things that the last person in my job didn't care about" doesn't seem like something I could ever be comfortable with.

I would be thrilled to build rules so that notifications aren't necessary. https://github.com/ArctosDB/arctos/issues/4289 would stop the locality notifications by stopping the nonsensical data, for example.

**Comment by Jegelewicz** [comment]
How about just deleting things that are repeats so that there is only one - I don't need to see that notification thousands of times, just one is fine.

For instance, there are currently 21 reminders that loan ALMNH:EH 1992.5 is overdue. There only ever needs to be one unless someone comments on one or marks it somehow. They are all identical except for the date. When notifications are being generated, if there is an identical one that already exists, don't create another, or replace the existing one.

**Comment by dustymc** [comment]
> currently 21 reminders that loan ALMNH:EH 1992.5 is overdue

How is "someone ran off with something 27 years ago" not on the top of everyone's list? Those seem absolutely critical to me, and I'd like to think everyone else. I would want constant reminders about that, I refuse to believe I'm alone in that, and I double-extra refuse to believe some future curator won't feel the same way if nobody does now - which I still don't believe!

If it's a lost cause, leave a note and close the loan.

If it's not actually critical, change the due date (and leave a note) and deal with it later.

If nobody actually cares, don't add a due date at all.

**Comment by Jegelewicz** [comment]
Dude, I didn't say remove the notification - JUST LEAVE ONE. It doesn't take a million of them and when I finally find time to take one of those actions, I will probably only remark/delete the notification I happen to be looking at at the time. Just put one in there and let me decided if it needs attention. Adding another one every day isn't going to give me more time to get to it. :-)

**Comment by dustymc** [comment]
Next release will auto-delete notifications which are all of:

* 90 days old
* ``status`` is not 'important'
* ``shared`` is NULL
