### ISSUE TITLE
Bulkload Media Metadata/Relationships

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#4582]
@dustymc is there a relatively pain-free world where l can load these media without a lot of reformatting? I built my bulkloader vertically (1:1), but the media metadata loader wants more horizontal relationships (1:many) for each image (9 images, >200 relationships). If there's not a quick fix, I can work on reformatting tomorrow.
[Bird whole drawer images media metadata.csv](https://github.com/ArctosDB/arctos/files/8526060/Bird.whole.drawer.images.media.metadata.csv)
.

**Comment by dustymc** [comment]
Sorta, but it won't fit - so...

Start with this in the "core" loader

[temp_load_this_first.csv.zip](https://github.com/ArctosDB/arctos/files/8526217/temp_load_this_first.csv.zip)

then you can use the webservice 

<img width="640" alt="Screen Shot 2022-04-20 at 5 20 26 PM" src="https://user-images.githubusercontent.com/5720791/164345232-3b09cca4-8e3f-4bae-9e10-344f69b6e33d.png">

(or let me know and I can do it) to get IDs, swap them in to these, and then load them via the relationships and labels loaders.

[temp_ucmrels.csv.zip](https://github.com/ArctosDB/arctos/files/8526240/temp_ucmrels.csv.zip)
[temp_ucmlbl.csv.zip](https://github.com/ArctosDB/arctos/files/8526242/temp_ucmlbl.csv.zip)

Lemme know if any (all?!) of that doesn't make sense.

**Comment by ebraker** [comment]
@dustymc Wahoo, THANK YOU! I've got relationships loaded. The media_label loader is doing something funky with the status column - my media_IDs are populating there and all the other data are shifting over rather than aligning into the correct columns. I tried loading a csv with a [blank] STATUS column to see if it would rectify the issue, but no luck.

![image](https://user-images.githubusercontent.com/11336485/164515990-be27329d-9f0c-4561-96ef-b7f3651aeb58.png)

[temp_ucmlbl - temp_ucmlbl.csv](https://github.com/ArctosDB/arctos/files/8533240/temp_ucmlbl.-.temp_ucmlbl.csv)

**Comment by dustymc** [comment]
Blargh, yea that's busted, I'll try to get a replacement in next release (and will try to get that out tonight).

**Comment by ebraker** [comment]
@dustymc FYI no rush - I'm going to enter these by hand since there are relatively few and they are for a student presentation tomorrow. I'll definitely use this with my next batch of ledgers at some point this summer.
