### ISSUE TITLE
Cannot Access Arctos - help make it better

### ISSUE THREAD

**Issue by cefilipek** [ArctosDB/arctos#4585]
Hi! I have been trying to access Arctos to check on some information in my collection, but I have not been able to enter the site. On my computer it says my IP is blocked and I get an error message on my phone, both on and off wifi. I have contacted the IT department at my institution, but I wanted to see if this was perhaps something going on on the Arctos side that I missed since I am not able to access it from my phone even when it is not on the institution's network. I'm including screenshots of both messages below, obscuring the IP address in the message I got on my computer. If that information is needed, please let me know, but I didn't think that was something I should share publicly.

![IP Blocked (IP obscured)](https://user-images.githubusercontent.com/56844074/164477548-9cb3335c-4e3f-497f-bcfe-27d2375374a1.jpg)
![Arctos Error Message 4_21_22](https://user-images.githubusercontent.com/56844074/164477806-8b916908-71d7-4807-9e07-f11bd82fc55d.PNG)

**Comment by cefilipek** [comment]
Thank you! I was a little worried that it might be an attempt to introduce a virus by pretending to be a blocked message, so I wanted to be sure!

**Comment by AJLinn** [comment]
> There's a bug in the mobile site and I can't fix it until https://github.com/ArctosDB/internal/issues/178 is resolved.

Is the bug that you can't go to the desktop site when you're in the mobile view on your phone? Is there a way to see media in the mobile site?
![IMG_3D1210928604-1](https://user-images.githubusercontent.com/17605945/164585008-8ba5d4a7-7f80-4c17-b10c-ee8972ce75fa.jpeg)

**Comment by dustymc** [comment]
Logo and github link in next release.

No @AJLinn that's something else, but it might be a bit better in next release too. (The actual solution involves https://github.com/ArctosDB/arctos/issues/2745, and I still don't have what I need to go there.)

**Comment by mkoo** [comment]
> Aha! (maybe)
> 
> I'm hijacking your issue.
> 
> @ArctosDB/arctos-working-group-officers how can we make the 'prove you're not a bot' thing look more "authentic"?

I cant believe you didnt suggest putting a big red box around it (maybe create a div with a class=scarybox) !

or try a different captcha (eg https://captcheck.netsyms.com/)

**Comment by dustymc** [comment]
Closing, escaping mobile seems to work.

We don't seem to bots trying to get through captch, the super-simple thing is plenty for now.
