### ISSUE TITLE
Quarantine Taxon Name - tools

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4588]
I'm still not to "automation" (and increasingly unsure it's practical) but there will be tools in next release. The tool will be available to manage_taxonomy users, but only in a limited capacity. The issue template (included below) should be rebuilt to use the tool.

The tool is here (in test now, next release for production).

<img width="590" alt="Screen Shot 2022-04-21 at 9 39 11 AM" src="https://user-images.githubusercontent.com/5720791/164517470-8d2151dd-5ada-48df-9b6b-5f82785cd5c7.png">

Mini howto:

Find a problem name, create a relationship (or don't, whatever, but that's necessary before everything can complete), plug the name into the tool:

<img width="1047" alt="Screen Shot 2022-04-21 at 10 33 13 AM" src="https://user-images.githubusercontent.com/5720791/164518121-483195db-4e4f-4ade-87a8-d9c74078627e.png">

That leads to....

<img width="1586" alt="Screen Shot 2022-04-21 at 11 06 29 AM" src="https://user-images.githubusercontent.com/5720791/164524220-9796a756-20ff-4001-a243-b9b3b79b4e0e.png">

... summary data suitable for inclusion in github. Do what the form says, resulting in an issue or an actionable comment in an issue. Going past that point requires global_admin (because you're doing things no normal user should be able to do - changing identifications in collections to which you have no access). After the issue has cooked for the recommended amount of time and nobody's objected, rerun the tool, skip the second screen, click a few more buttons...

<img width="1057" alt="Screen Shot 2022-04-21 at 11 07 20 AM" src="https://user-images.githubusercontent.com/5720791/164524644-b47fd0c0-3f8b-4072-9c5b-ae829f1557a0.png">

<img width="546" alt="Screen Shot 2022-04-21 at 11 07 30 AM" src="https://user-images.githubusercontent.com/5720791/164524691-76eb965a-998c-4431-8928-3f898ef38c38.png">

<img width="459" alt="Screen Shot 2022-04-21 at 11 07 41 AM" src="https://user-images.githubusercontent.com/5720791/164524714-c5cce424-512e-4541-9703-c7af03d4a127.png">

<img width="418" alt="Screen Shot 2022-04-21 at 11 07 49 AM" src="https://user-images.githubusercontent.com/5720791/164524733-33a91d22-e6b6-4be0-a293-1dd42f4224a0.png">

... doing what the form suggests along the way, and you're done.

First, what's missing/broken/whatever from that process?

If nothing or once that's ironed out, can someone rebuild the issue template to use the tool? Or maybe that's a second step? I don't want to discourage users who don't have manage_taxonomy (or even users who aren't Arctos Operators) from nominating names for quarantine, but someone with at least that level of access needs to be involved somewhere, and including some minimal documentation in the issue seems useful. IDk, I'm very up for anything....

Current issue template:

------------------------------
Issue Documentation is at http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

Name Quarantine Documentation is at https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxon_name_type

Information requested | Response 
 -- | -- 
Name suggested for quarantine | **replace this with the name suggested for quarantine, and provide link to the Arctos taxon page**
Reason for quarantine | **replace this with the reason for quarantine, links to sources are useful**
Suggested treatment for all identifications currently using this name | **replace this with the suggested treatment for identifications using this name should the period for comment expire with no discussion, in general this will be A {string} = New name {Quarantined name}, provide a link to the New name taxon page in Arctos**
Collections currently using this name in identifications | @dustymc please provide
Collection contacts for above | @dustymc please provide

This name will be quarantined and existing identifications changed to the suggested treatment following the next Arctos Working Group Issues meeting unless comments here suggest this should not happen or everyone affected agrees to the change before then.

Please add this issue to the Taxonomy Committee Project.

**Comment by Jegelewicz** [comment]
@dustymc I made a few wording changes and added some links so that it is easier to create a new issue and relationship. BUT the link for the relationship only goes to the taxon page - can we make it go to the edit name page?

See my commit

**Comment by Jegelewicz** [comment]
This is a cool start on integrating stuff in Arctos with Github issues. we can definitely update the name quarantine template once we have this nailed down. I am wondering if we can automate the "baking time" using Github milestones with dates, but I don't think we can automate that?

**Comment by Jegelewicz** [comment]
@ArctosDB/taxonomy

**Comment by dustymc** [comment]
template updated, closing
