### ISSUE TITLE
Feature Request - Add another option for saving in Fork-edit

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#4589]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html
I love being able to use Fork-Edit when I'm adding new events for our UAM:EH objects (e.g. adding a creation or collection or use event after only one event was created in the data entry process).

However, once I fork, if I need to change some of the existing information (the whole point of using the fork-edit) I think I need another option for the save button.
<img width="563" alt="Screen Shot 2022-04-21 at 1 07 05 PM" src="https://user-images.githubusercontent.com/17605945/164552749-c29a7904-f242-4a7d-9af7-9cebb74d88de.png">

1. Unaccept old/Add new is not what I want, because I want to leave the one that was created in data entry, I just want to use it as a starting point from which I can add a new event.
2. Edit current is not what I want, because that keeps the existing event that was created and just overwrites with new info.
3. Add, change no existing data is what I am using, but I've found that it does what it says and it doesn't change some of the fields (like event determiner, determination date) and that is often what needs to get changed because someone else figured out that info at times.

Is it possible to add fourth save option, "Add, save updated data" or something like that?

**Priority**
Medium-High (it's not stopping me from editing, but it would save me from having to go back and edit the new event I just forked - I like saving steps).

**Comment by dustymc** [comment]
"I want to leave the one that was created in data entry, I just want to use it as a starting point from which I can add a new event." is what "Unaccept old/Add new" does - what am I not understanding?

**Comment by AJLinn** [comment]
I want them _both_ to be accepted because they're two different types of events. 
https://arctos.database.museum/guid/UAM:EH:UA2018-012-0225

<img width="554" alt="Screen Shot 2022-04-21 at 3 30 11 PM" src="https://user-images.githubusercontent.com/17605945/164567334-2a114790-fc51-4680-a95f-1c791878c5d2.png">

Both that and add, make no changes force me to go back and make another change after I've forked. One to fix the info that I need to change but didn't change and one to re-accept the event that go unaccepted.

**Comment by dustymc** [comment]
> both to be accepted

Use Add, change no existing data

Beyond that, I think this is magic (or I'm still not understanding something) - I think you're asking to fork BOTH the source and the new in one operation, but to somehow retain some of the original values rather than what's in the form for one of them?

**Comment by AJLinn** [comment]
I did a Zoom recording of me walking through the steps of fork-editing and what happens upon "add, change no existing data" and what I _wish_ would happen. Maybe it will clarify? If not, maybe we can add this to an agenda for the next office hours and someone can brainstorm with me!

Topic: Angela Linn's Zoom Meeting
Date: Apr 22, 2022 01:50 PM Alaska

Meeting Recording:
https://alaska.zoom.us/rec/share/BdJ3uji3QgUYrb0HF6cFWcQ_EX__YCsoiJpq5wIhNYOL5K437X9wL8jMum6UQxKk.2QTmvgw7BXMTd_m4

Access Passcode: FE55p&2v

**Comment by Jegelewicz** [comment]
I just did this yesterday and we used Add, change no existing data. This left the original event as it was and added the new one with the "acceptedness" we had chosen.

**Comment by dustymc** [comment]
Thanks @AJLinn that clears some things up.

* figure out why new agent/date isn't being preserved
* pass just-picked geography to geolocate
* see also https://github.com/ArctosDB/arctos/issues/4459 - geolocate is definitely defaulting to polygons in some situations, needs more control, better documentation, ????
