### ISSUE TITLE
Feature Request - use "transaction attributes" to populate collection object/part attribute bulkloaders

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4590]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
The things that happen to stuff prior to cataloging may be recorded in accessions/loans or borrows as a bunch of remarks. Some of this information is important to ultimate users and is somewhat detached from the cataloged items.

**Describe what you're trying to accomplish** 
Declutter transaction remarks and make use of data there to populate important information in catalog records.

**Describe the solution you'd like**
Record an attribute in a transaction that could later be used to populate an attribute loader for all items associated with the transaction. 

**Describe alternatives you've considered**
Leave the stuff in attribute remarks - maybe someone will translate it out of there someday.

**Additional context**
From https://github.com/ArctosDB/arctos/issues/4242#issuecomment-1105724209

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by mkoo** [comment]
Table this? I dont know if it would rise in priority but doesnt really belong in mystery milestone either.
The actual proposal of adding transaction attributes is an enticing one to me!

**Comment by Jegelewicz** [comment]
This is related to https://github.com/ArctosDB/arctos/issues/7384
