### ISSUE TITLE
Code Table Request - Add Cameron Formation

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#4591]
**Goal**
Add Cameron Formation to the lithostratigraphic formation locality attribute

**Context**
Cameron Formation exists ([Lucas 1993 chinle group.pdf](https://github.com/ArctosDB/arctos/files/8535342/Lucas.1993.chinle.group.pdf)) and I need to use it for one of our localities

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlithostratigraphic_formation

**Proposed Value**
Cameron Formation

**Proposed Definition**
Sandstone dominated unit dated to the Upper Triassic exposed in Utah, Arizona, and Nevada. [New Mexico Museum of Natural History and Science Bulletin](https://econtent.unm.edu/digital/collection/bulletins/id/889/rec/1)

If there are no objections I will add it to the code table

**Comment by Jegelewicz** [comment]
No opposition form me.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Added
