### ISSUE TITLE
Code Table Request - New cataloged item type = loanable object

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4593]
**Goal**
Create entities that represent composite objects (10 different fossils in a single block of matrix)

**Context**
Current collection object types do not provide an appropriate choice for this type of cataloged item.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcataloged_item_type

**Proposed Value**
loanable object

**Proposed Definition**
An object composed of two or more cataloged items that cannot be separated. A loan of one component object requires a loan of all component objects.

**Available for Public View**
Yes

**Priority**
[  Please choose a priority-label to the right.  ]

**Comment by Jegelewicz** [comment]
It is meant mostly to be used by entities.....

**Comment by dustymc** [comment]
Gotcha. "**An Entity representing** two or more cataloged items that cannot be separated. A loan of one component object requires a loan of all component objects." makes that clearer in my brain.

MAYBE I'd like that better as an attribute, where it could be constrained to entity collections and wouldn't pollute ctcataloged_item_type with the bajillion things that entities (and often only entities) do, but not at all sure of that.

**Comment by Jegelewicz** [comment]
> MAYBE I'd like that better as an attribute, where it could be constrained to entity collections and wouldn't pollute ctcataloged_item_type with the bajillion things that entities (and often only entities) do, but not at all sure of that.

But is weirdly a part? I mean this is a case where I might see an entity having a part and all of the component records' parts are really subsamples (or some other appropriate term) of the "loanable object"? UGH - I mean containers make sense, but not everyone uses them?

**Comment by dustymc** [comment]
I think the big-picture takeaway is that collections are going to do whatever they want, and Arctos is designed to accommodate that. Given 40 tons of pollen in a rock, someone (often the same someone over time) will catalog the whole thing as one part, catalog the whole thing with 500 parts (those that have been "loaned" - if we're lucky), catalog 500 "parts" (any of which might later get split and recataloged), etc., etc., bla bla.

FWIW I'd probably not use an Entity for any of that - just give the big rock a number and just use it, either as a relationship of some sort of an identifier, for the stuff that gets chipped off. This is more of a subtractive process, where we start with the whole then remove/study/identify bits (which may be related to the whole only by virtue of being caught up in floods that may have occurred thousands of years apart). A zoo animal is sort of the opposite - we start with a blood sample and slowly assemble those into some (incomplete, probably always) picture of the THING. I don't think an Entity is _wrong_ in such a situation, but it doesn't seem entirely necessary either.

If we're going to be stuffing Entities into pigeonholes, where would https://arctos.database.museum/guid/Arctos:Entity:38 go? It's sorta the situation - sorta.

**Comment by Jegelewicz** [comment]
Yes - I am thinking about this all wrong. This really should be an other identifier? All records that are "stuck together" share the identifier. It could be an entity or it could be something else. See https://github.com/ArctosDB/arctos/issues/4412

Closing this.
