### ISSUE TITLE
What is my error?

### ISSUE THREAD

**Issue by Cloveis** [ArctosDB/arctos#4594]
# Error Text
![image](https://user-images.githubusercontent.com/90786192/164758468-bed86c4d-3d52-42d9-8e41-1f85b6d5d8e1.png)

# Where it happened
![image](https://user-images.githubusercontent.com/90786192/164758409-754993a5-e525-4f85-94c9-f8840eaabcc2.png)
https://arctos.database.museum/accn.cfm?action=createForm

# Steps to get there
I logged into arctos and went to manage data>transactions>create accession. I filled out the fields (as seen above) and clicked save accession, to which I was returned this error message. I just created an accession a few days ago with the same method on the same page, so I am just confused at what I am doing wrong here.

**Comment by Jegelewicz** [comment]
Date must be in format YYYY-MM-DD

**Comment by dustymc** [comment]
https://handbook.arctosdb.org/documentation/dates.html

**Comment by Cloveis** [comment]
Ah yes, of course. Thank you!
