### ISSUE TITLE
Weird error on login, and error with looking at previous non-live records.

### ISSUE THREAD

**Issue by Awkwardtree13** [ArctosDB/arctos#4595]
When I log in to Arctos I'm getting an error message (see attached screenshots.) Exiting the error message window and reloading the Arctos page shows me as logged in, so I'd assume this error message is itself an error, but I don't know why it would show up. I've been able to replicate this about half a dozen times, and it happens every time. I have yet to confirm whether other people are having the same issue. 

<img width="796" alt="Screen Shot 2022-04-22 at 12 22 58 PM" src="https://user-images.githubusercontent.com/103291095/164764166-63a7e689-7d8c-45af-bdf5-f908ee86e19a.png">
<img width="411" alt="Screen Shot 2022-04-22 at 12 23 10 PM" src="https://user-images.githubusercontent.com/103291095/164764171-8f0cad2d-cb84-4b90-86cb-481cd31988d3.png">
<img width="970" alt="Screen Shot 2022-04-22 at 12 23 32 PM" src="https://user-images.githubusercontent.com/103291095/164764173-f842f8dc-4fce-46bc-8690-07d669a1658f.png">
<img width="970" alt="Screen Shot 2022-04-22 at 12 24 15 PM" src="https://user-images.githubusercontent.com/103291095/164764175-6cba67c3-7f9d-46df-8382-828787897a03.png">
<img width="970" alt="Screen Shot 2022-04-22 at 12 24 25 PM" src="https://user-images.githubusercontent.com/103291095/164764178-4f3f6e5c-9899-4454-8c5c-e23cbec60f32.png">
 
I am also having a second issue. When I hit the "Browse your Records" button on the new data entry screen, no records appear, regardless of the filters I use. However, when I hit the "download" button on the "Browse/Edit Bulkloaded Data" screen the downloaded table shows the expected records (see attached screenshots). 

<img width="1512" alt="Screen Shot 2022-04-22 at 12 32 12 PM" src="https://user-images.githubusercontent.com/103291095/164765258-c2d04600-7d0c-47b2-83e3-28431720d7b5.png">
<img width="1372" alt="Screen Shot 2022-04-22 at 12 32 25 PM" src="https://user-images.githubusercontent.com/103291095/164765261-0bdbab74-dd1d-4dd4-8090-f2d727592e79.png">

For additional data on my situation regarding both issues: I am using a MacBook Pro running macOS Monterey version 12.3.1 and using Safari version 15.4.

**Comment by dustymc** [comment]
I think this is more of https://github.com/ArctosDB/arctos/issues/868, which seems to have fallen entirely off the radar.

Error logs:
<img width="556" alt="Screen Shot 2022-04-22 at 11 08 55 AM" src="https://user-images.githubusercontent.com/5720791/164770703-3f44cfed-cd24-472c-a34f-0ecd2f449950.png">

Agent
<img width="694" alt="Screen Shot 2022-04-22 at 11 09 27 AM" src="https://user-images.githubusercontent.com/5720791/164770764-6d371d94-d8f5-4c51-a524-9415235aeaac.png">

I'll more-completely ignore case in login for next release, what happens after login still need discussed.
