### ISSUE TITLE
Quarantine Taxon Name -Doratopsylla currvata

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4596]
Issue Documentation is at http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

Name Quarantine Documentation is at https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxon_name_type

Information requested | Response 
 -- | -- 
[Name suggested for quarantine](https://arctos.database.museum/name/Doratopsylla%20currvata) | **replace this with the name suggested for quarantine, and provide link to the Arctos taxon page**
Reason for quarantine | **This flea name is a mispelling of an unaccepted name. The original name was Doratopsylla curvata Rothschild 1915, single r.  It has since been moved to a separate genus, Corrodopsylla curvata (Rothschild 1915). There is also a subspecies Corrodopsylla curvata curvata . In no circumstances should there be two "r's. This name has been used for two records at UCM. *
Suggested treatment for all identifications currently using this name | **replace this with the suggested treatment for identifications using this name should the period for comment expire with no discussion, in general this will be A {string} = New name {Quarantined name}, provide a link to the New name taxon page in Arctos**
Collections currently using this name in identifications | @dustymc please provide
Collection contacts for above | @dustymc please provide

This name will be quarantined and existing identifications changed to the suggested treatment following the next Arctos Working Group Issues meeting unless comments here suggest this should not happen or everyone affected agrees to the change before then.

Please add this issue to the Taxonomy Committee Project.

**Comment by campmlc** [comment]
We also need to create the relationship to the current accepted name, Corrodopsylla curvata  https://arctos.database.museum/name/Corrodopsylla%20curvata

**Comment by campmlc** [comment]
Priority - high. We have students working on this group and will be cataloging records.

**Comment by Jegelewicz** [comment]
I created the relationship.

**Comment by dustymc** [comment]
[temp_taxon_quarantine_reloader(9).csv.zip](https://github.com/ArctosDB/arctos/files/8789914/temp_taxon_quarantine_reloader.9.csv.zip)
