### ISSUE TITLE
Pull Function in new Data Entry Form not displaying info

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4597]
The Other ID "Pull" function in the new data entry form does not populate the locality and event tables with any information except locality ID.
The old form used to add in the event and locality IDs but also display the associated info.
This is needed as we have a lot of parasites to catalog from host records using this method to capture host data in the parasite record. But we need to be able to see the data to confirm it is correct before saving the record.
Priority: High

**Comment by dustymc** [comment]
https://www.youtube.com/watch?v=QJeLNCn62dE

Click pull (if you have it on, and have whatever you want to populate on).

**Comment by campmlc** [comment]
I do that, but it only populates with the locality I'd. All actual locality
fields are blank. In the old form, it would actually pull these data into
the data entry screen where they could be confirmed.
