### ISSUE TITLE
Please restore option of excluding related items from Other ID search

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4598]
This problem appears to have occurred recently, perhaps in last couple of days since most recent release.
I need to be able to search on Other IDs for an exact value or list and not have the results return every related item to that ID.
Previously, a search on "NK 12345" in Other ID would only return catalog items with that identifier.
However, a search on the same value in my preferred ID (as NK) would return not only the catalog record assigned that ID but all related offspring, embryos, siblings, parasites etc. 
I stopped using my preferred ID for this reason, and instead went to use Other ID search. This was frustrating, but manageable.
Now, a search in either field brings up all related items. Please restore to previous functionality, or give us the option to specify whether we want all related or limited search results (better option) for both fields.
Priority: Urgent. I cannot search on a loan item list without spending hours eliminating items that were not in the original request.

**Comment by dustymc** [comment]
Nothing has changed, use Identifier References

**Comment by campmlc** [comment]
Not true. I have never used identifier references in this search. I have merely copy pasted a csv list of identifier into the Other ID field, selecting identifier type. I need this functionality restored. Use search for NK 310600 as example.

**Comment by campmlc** [comment]
See #3379

**Comment by Jegelewicz** [comment]
@campmlc I search other identifier = NK and value = 12345 and I get exactly one record. Can you provide the search that is giving you trouble?

**Comment by Jegelewicz** [comment]
@campmlc it is because the offspring have the NK as "self" too.

https://arctos.database.museum/guid/MSB:Mamm:340571

![image](https://user-images.githubusercontent.com/5725767/164829357-648a60d5-4c28-41ad-9db0-44e0cd097132.png)

**Comment by campmlc** [comment]
This search should return only the references self results. Or, give me a
means to limit the results to self only.

**Comment by Jegelewicz** [comment]
Oh wait - my brain is fried from agents today! I see now those two numbers are different....

**Comment by dustymc** [comment]
>means to limit the results to self only

https://github.com/ArctosDB/arctos/issues/4598#issuecomment-1106801116

<img width="598" alt="Screen Shot 2022-04-22 at 5 19 39 PM" src="https://user-images.githubusercontent.com/5720791/164837717-d87ec995-1eff-4471-a8ba-9fb555c737c4.png">
<img width="227" alt="Screen Shot 2022-04-22 at 5 19 50 PM" src="https://user-images.githubusercontent.com/5720791/164837725-f083df39-bed2-47ed-a575-edfd79d67a80.png">

https://github.com/ArctosDB/arctos/issues/3437

**Comment by Jegelewicz** [comment]
AH HA

Do this!
![image](https://user-images.githubusercontent.com/5725767/164837840-9a4b5bfa-d7f6-4993-87e5-a10e5932944f.png)

**Comment by Jegelewicz** [comment]
Dang it!

**Comment by campmlc** [comment]
I've never had to use ID references for this search. Up until the last few days, this exact search had "self" as default. A bigger issue here is that search parameters and tools are changed with no notification to the community. This almost resulted in me adding double the number of items to a loan - a critical problem. 
I used to be able to do this same search with a paste of csv list on my preferred ID. Then that changed without warning to include related items. Then I had to switch to using Other ID, and then scrolling through the interminable Other ID table to choose my identifier, then clicking "in list". Now I have to click yet another field?  And with no warning???
Why not make the preferred identifer settings customizable so that I can decide whether I want that ID to be self only or return all related items. Then at least I can go back to one or two clicks per search, instead of now 4. I do this multiple times a day, and the results of this search - knowing the exact parameters that this search returns - is critical to my ability to function. 
Again, parameters should not change without warning.

**Comment by campmlc** [comment]
See below from #3379 - this is the situation which I've been operating under for over a year:
https://github.com/ArctosDB/arctos/issues/3379#issuecomment-767727921

**Comment by dustymc** [comment]
I don't know where to go with this other than pointing out that the code is available for review. Tentatively closing.

**Comment by campmlc** [comment]
They have separate NKs, not 310600.
