### ISSUE TITLE
Issue with data entry

### ISSUE THREAD

**Issue by Awkwardtree13** [ArctosDB/arctos#4599]
When attempting to save a record, I get the following error message.

<img width="450" alt="Screen Shot 2022-04-22 at 1 10 45 PM" src="https://user-images.githubusercontent.com/103291095/164795399-8e0bde96-becc-4f3c-ba63-cf89d9c032a9.png">

I checked with my boss, and all my permissions are in order, so we have no clue what's going on.

**Comment by dustymc** [comment]
Log out, log back in with your propercase username
