### ISSUE TITLE
Feature Request - make it easier to pick an other identifier in search (no more checkboxes in controlled vocab search fields)

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4600]
**Is your feature request related to a problem? Please describe.**
From the main search page when I want to search on an other identifier, I have to scroll around forever.
<img width="960" alt="Screenshot 2022-04-25 11 38 37" src="https://user-images.githubusercontent.com/5725767/165143565-f9e0e7f2-5b6b-49a1-a01f-df61d645e47e.png">

**Describe what you're trying to accomplish** 
Because the list of other identifier types is so long, it can be a big time sink if I want to search USGS...I'd like to make selection for this field easier.

**Describe the solution you'd like**
It would be nice to start typing and get a list of potential matches (beyond "starts with"). So I type U and get every identifier type that contains "U", and so on.

But at least we could make this consistent with other picks? I type U and am moved down to the terms in the list that start with U (the way Related Identifier Type: farther down the form works)
<img width="960" alt="Screenshot 2022-04-25 11 51 40" src="https://user-images.githubusercontent.com/5725767/165145675-6ec470bb-8cf4-4302-ba76-1b8d496f277c.png">

**Describe alternatives you've considered**
Just keep on scrolling

**Additional context**
There are few other search fields that work this way and should be updated:

Sources
Month (the separate thing - why do we have this?)

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

Making this high, because more and more outsiders are going to be looking for these things.

**Comment by Jegelewicz** [comment]
@dustymc I was thinking I could copy-pasta code from related identifier type but then realized why the identifier one is different - it lets you select multiple identifier types and the relationship section only lets you pick one. Can we get a type-ahead list and still pick more than one thing? (Sounds hard!)

**Comment by dustymc** [comment]
"Hard" isn't quite right, but something other than the [standard element](https://www.w3schools.com/tags/att_select_multiple.asp) is going to have some sort of complication. The least-insane way to deal with those, if you absolutely must, is generally a library, and we seem to be [stuck between those at the moment](https://github.com/ArctosDB/arctos/issues/2893).
