### ISSUE TITLE
Add New Github User to Arctos Team

### ISSUE THREAD

**Issue by zmsch** [ArctosDB/arctos#4601]
New User Github username: claypollock

Please add to the following teams:
- [x] Arctos Users
- [ ] Arctos Code Table Administrators
- [ ] Documentation
- [ ] Geo-group
- [ ] Media
- [ ] Paleontology
- [ ] Taxonomy

**Comment by mkoo** [comment]
Done! @zmsch Please add this user's affiliation at least to the Arctos profile
https://arctos.database.museum/agents.cfm?agent_id=21339710
(really helps for the rest of us!) Please close this ticket when @claypollack has accepted the Github invitation

**Comment by zmsch** [comment]
Thanks!

**Comment by Jegelewicz** [comment]
Added github username to Arctos agent.

**Comment by mkoo** [comment]
thanks all!
