### ISSUE TITLE
Bulkloader builder permission

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4602]
Hey @Jegelewicz! So, I'm trying to have my student tidy up the data for the bird collection a bit before I have you look it over and I bulkload, so I wanted a template but I'm getting a message that I don't have access to the Bulkloader Builder? Can you help with permissions? Thanks!

_Originally posted by @gradyjt in https://github.com/ArctosDB/data-migration/issues/681#issuecomment-1108921751_

**Comment by Jegelewicz** [comment]
@dustymc any idea why @gradyjt can't use the bulkloader builder?

**Comment by dustymc** [comment]
<img width="368" alt="Screen Shot 2022-04-25 at 11 59 07 AM" src="https://user-images.githubusercontent.com/5720791/165156289-79585c7b-2326-46ff-9a00-3e6bff2a2ac9.png">

will always tell you. That one's a little wonky, it had conflicting permissions for some reason - I dropped public, it should work in an hour or so when the cache clears.

**Comment by gradyjt** [comment]
Thank you!

**Comment by campmlc** [comment]
Hi @gradyjt I'm trying to get in touch with you
 Can you email me @campmlc ?
