### ISSUE TITLE
GUID-page identifier layout

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4605]
**Is your feature request related to a problem? Please describe.**

Identifiers are messy, https://github.com/ArctosDB/arctos/issues/4101 (especially if something interesting happens in https://github.com/ArctosDB/arctos/issues/4604) are going to make them messier.

**Describe what you're trying to accomplish** 

Display full data in a manageable format.

**Describe the solution you'd like**

Move identifiers to a full-width table above parts. (Maybe allow users to choose from a few versions, also like parts.)

**Describe alternatives you've considered**

Leave identifiers where they are, don't display full data.

**Additional context**

Yuck:

<img width="616" alt="Screen Shot 2022-04-25 at 4 03 50 PM" src="https://user-images.githubusercontent.com/5720791/165188547-5b255f7a-f49a-4548-84de-7a752032198b.png">

**Priority**

?

**Comment by Jegelewicz** [comment]
> Move identifiers to a full-width table above parts. 

Makes sense to me, but maybe that starts to point to a different catalog record page where things follow one after the other and we stop trying to have a two column page?

**Comment by ewommack** [comment]
> Makes sense to me, but maybe that starts to point to a different catalog record page where things follow one after the other and we stop trying to have a two column page?

I kind of like the two column page, or at least the windows and boxes in it. A student was checking out a collection's page from another collection management system and it was all just a long list of info one after another. It was hard for them to find what they were looking for. 

> Move identifiers to a full-width table above parts. (Maybe allow users to choose from a few versions, also like parts.)

What would be the column headings and how many columns? Identifier name; Identifier number; Identifier link?

**Comment by dustymc** [comment]
>how many columns?

Depends on the user and there are some details to sort out, but

* type
* value
* link (sometimes, may or may not include Entity-links, somehow)
* search Arctos
* check containers (just us)
* maybe relationships (or that's an almost-identical table with an extra column, or ??)
* who+when, merged or in separate columns
* https://github.com/ArctosDB/arctos/issues/4604, somewhere and somehow (probably "subrows")

The results/identifiers table contains the general idea for the core-stuff. 

The safe assumption is that some user will need all of that split out, but maybe some/most are good with clicky 'genbank' links. (Making it more like parts would allow offering however many views we need.)

Some layout that puts the links in a column (instead of jumbled all over the place) seems like a useful start.

**Comment by campmlc** [comment]
I like full width table idea, but maybe at top of page, above collecting
event and attributes?

**Comment by dustymc** [comment]
> above collecting event and attributes

I don't think a table disrupting the flow up there can work, but that did make me look closer at the scope of the problem: We have one record with 55 identifiers, plus a few hundred with more than 20, at the moment. The injected parts table can't play nice with the "expandopane," although maybe it could have something similar built in, and I'm not thrilled with the idea of needing to scroll past 50 rows of IDs to find parts, nor 200 (really) parts to get to identifiers. I'm not sure what to suggest - just focus on the "normal" 4 or 5 of each and see what happens in the real world?

**Comment by dustymc** [comment]
There's a changeable table at the bottom in test. I'll not mess with the current jumble at the top until this is resolved, and  I will plan to disable the table for next release unless this can be resolved. The table is set up so that adjusting something or adding views should be straightforward; nothing below has to be "final" (even ignoring https://github.com/ArctosDB/arctos/issues/4604). 

There are currently three views, plus some extras for "us".

Public:

<img width="1271" alt="Screen Shot 2022-04-26 at 11 18 08 AM" src="https://user-images.githubusercontent.com/5720791/165365992-29a7ad83-9949-43b5-8129-fac460f6ffe1.png">

Operator:


<img width="1511" alt="Screen Shot 2022-04-26 at 11 17 34 AM" src="https://user-images.githubusercontent.com/5720791/165366057-a81737be-bb47-4204-90a5-d00c52ba04eb.png">

or

<img width="1109" alt="Screen Shot 2022-04-26 at 11 40 14 AM" src="https://user-images.githubusercontent.com/5720791/165369582-137d99e0-da5a-4c25-a924-a019ad05230f.png">

or

<img width="510" alt="Screen Shot 2022-04-26 at 11 19 23 AM" src="https://user-images.githubusercontent.com/5720791/165366182-f3ccc914-0d15-41f1-bc58-c8bc22608f6a.png">

**Comment by dustymc** [comment]
split view is now default

office hours peeps like the table view approach

reprioritizing in hopes of getting this (current jumble at the top) out ASAP

**Comment by Jegelewicz** [comment]
Use a collection-wide priority to select some ids to put up top, then put the rest down below with a link to it from up top?

**Comment by Jegelewicz** [comment]
AWG says yes to these "identifier attributes"

**Comment by Jegelewicz** [comment]
Then we will really need the identifiers download table. I think there is already an issue?

**Comment by dustymc** [comment]
>need the identifiers download table

It's been in manage for a while.

**Comment by dustymc** [comment]
From https://github.com/ArctosDB/arctos/issues/4604#issuecomment-1112671720

>mock-up 

Scroll up for screenshots, or you can see the form that gets injected at

https://arctos.database.museum/includes/forms/SpecimenDetailIdentifiers.cfm?collection_object_id=21714980&format=full

https://arctos.database.museum/includes/forms/SpecimenDetailIdentifiers.cfm?collection_object_id=21714980&format=full_separated

https://arctos.database.museum/includes/forms/SpecimenDetailIdentifiers.cfm?collection_object_id=21714980&format=minimal

That said, it's set up so it's easy to change or add formats, it could look like most anything very quickly, the big question seems to be where we put it.

**Comment by campmlc** [comment]
Can we leave the minimal identifiers where they are now, and insert the
full table between Identification and collecting event and attributes when
it is expanded, but collapse down to the minimal table as default?
I prefer having these near top of page rather than down by parts.
Can we add a link to the identifier download tool from wherever it ends up?

**Comment by dustymc** [comment]
In next release, see https://github.com/ArctosDB/arctos/issues/4622 for prioritizing identifiers
