### ISSUE TITLE
Need help managing a collection

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4606]
@dustymc emilydyer has manage collection, but is not seeing it in the menu - what are we missing?

@Jegelewicz I'm still not seeing Metadata as an option
<img width="1440" alt="Screen Shot 2022-04-25 at 4 24 56 PM" src="https://user-images.githubusercontent.com/99691327/165190417-8243f72e-2929-4b08-8a10-b00cfee31a31.png">

_Originally posted by @edyer94 in https://github.com/ArctosDB/data-migration/issues/1334#issuecomment-1109135314_

**Comment by dustymc** [comment]
They need manage_specimens (and we need https://github.com/ArctosDB/arctos/issues/2893...)

**Comment by Jegelewicz** [comment]
Shouldn't that be listed here?
![image](https://user-images.githubusercontent.com/5725767/165194346-6b38b39d-a7f9-4262-bec8-0495053a4eef.png)

**Comment by dustymc** [comment]
It's just not that simple - I'm assuming anyone entrusted with a collection can touch the specimens (and lots of similar stuff) to save some CPU.
