### ISSUE TITLE
Feature Request - scrollto on guid page

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4609]
**Is your feature request related to a problem? Please describe.**

vaguely related to https://github.com/ArctosDB/arctos/issues/4605, can we have some sort of scrollto widget>

**Describe what you're trying to accomplish** 

make navigation easy

**Describe the solution you'd like**

https://github.com/ArctosDB/arctos/issues/2893, make it look like https://mczbase.mcz.harvard.edu/agents/Agent.cfm?agent_id=60265 (and check that out on mobile!)

**Describe alternatives you've considered**

* do something hacky
* do nothing

**Additional context**

@Jegelewicz 

**Priority**

**Comment by Jegelewicz** [comment]
Maybe these links should come from the "record summary"?
![image](https://user-images.githubusercontent.com/5725767/165970079-40f0a2d5-b9ce-4412-bd34-2f39c6020cdb.png)

Parts already does this.....
