### ISSUE TITLE
Object Tracking - Restore ability to see count and add all items in a container to a loan

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4614]
In the object tracking updates, we have gained an improved tool to allow us to see all collection objects in a container as well as the empty positions (Container Contents csv). But in the process we have lost the count of collection objects and the tool allowing us to add all items in a container to a loan.
Go to:  Find Container
Enter barcode in Container Barcode or In Container Barcode ( you can use DGR10432 as demo)
Click the box next to the barcode
Select from right panel: Container Contents
See: no count of collection objects at top - we used to have this. Perhaps a count of collection objects, and a count of barcodes, and a count of empty positions?
Also See: no ability to add all collection objects to loan here or below

Additionally - Flatten Part Container not working
Find Container
Enter Barcode or In Barcode
Click box next to barcode
Click Flatten Part Container at lower left
Expect: to see list of collection objects and their positions, with option to add all to a loan
See: Nada, even though this box contains collection objects with associated barcodes

Priority: Medium

**Comment by dustymc** [comment]
I'll turn the link back on.
