### ISSUE TITLE
Need Help with Arctos Error - User Permissions 

### ISSUE THREAD

**Issue by crcarter00** [ArctosDB/arctos#4616]
# Error Text
Fail: outcatch -- ERROR: enteredby (Tchaney_DMNS) is invalid Where:{PL/pgSQL functiontrigger _fct_ti_bulk_cid() line 29 at RAISE:

# Where it happened
Attempting to save a new record

# Steps to get there
Used two different existing profiles-
"Tom's Schaake form ID okay" and "Tom's Schaake updated ID form"
Verified user permissions.  Can see this user has two accounts (tchaney_dmns and ,tchaney_dmns) but unclear if this has any impact on the error.

![Screenshot 2022-04-27 105508](https://user-images.githubusercontent.com/84087467/165585453-1f4ba438-109a-402c-bf37-bcc06d5e744d.png)
![2022-04-27 11_00_01-edit user tchaney_dmns](https://user-images.githubusercontent.com/84087467/165586241-0384f78d-309b-4a01-92d4-7b5963eee94f.png)

**Comment by dustymc** [comment]
This is a variation of https://github.com/ArctosDB/arctos/issues/868. Unfortunately I don't know of any sure-fire way to save what's been entered, but you can have them try:

- open a new Arctos tab
- log out
- log in as ``tchaney_dmns`` (or in general, whatever matches the agent name of type 'login')
- try the save again, in the original tab

and going forward, log in with the username that exactly matches what's in the agent profile.

**Comment by crcarter00** [comment]
He logged out and back in three times, with the same error.  I am unclear how to change his user name in a new record, since the "Entered By" field is autopopulated.

**Comment by crcarter00** [comment]
Perhaps I delete him altogether and re-add him?

**Comment by dustymc** [comment]
Can you share those errors?

**Comment by acdoll** [comment]
I believe the trouble is that he is logging in as Tchaney_DMNS instead of tchaney_DMNS. If I'm understanding #868  correctly, the login system doesn't care which one he is using, it still lets him in. But the verification system in Data Entry is getting caught up by the difference in case. We'll have him try again and ensure he's using the lower case 't'.

**Comment by acdoll** [comment]
> verification system in Data Entry

and probably elsewhere - he mentioned issues while trying to edit existing records as well.

**Comment by crcarter00** [comment]
I'll be sure to make tchaney aware of case sensitivity on login.  As for the earlier errors, they were all the same as listed above. (Fail: outcatch -- ERROR: enteredby (Tchaney_DMNS) is invalid Where:{PL/pgSQL functiontrigger _fct_ti_bulk_cid() line 29 at RAISE:)

**Comment by crcarter00** [comment]
Looks like we need help to delete the duplicate user.  
,tchaney_dmns

Thanks.



</body>
</html>
