### ISSUE TITLE
Arctos Down - 3:40pm MDT

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4619]
Please complete to the best of your ability.

## Unplanned Outage
 - Date and time4-27-22 3:40pm  (**please add time zone from which you are reporting**) outage discovered:
 - Describe the outage (Arctos down or only some part not working?): endless spinning wheel of browser doom

## Planned Outage
 - Date and time outage will begin:
 - Date and time outage is expected to end:
 - Reason for outage:
 - Expected behavior during and after the outage:

## Communication before/during outage
- [ ] Pin this issue
- [ ] Banner updated @jegelewicz 
- [ ] Email sent to AWG 
- [ ] Email sent to Arctos Google Group 
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @jegelewicz
- [ ] Email sent to AWG 
- [ ] Email sent to Arctos Google Group 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by lin-fred** [comment]
It's up for me

**Comment by dustymc** [comment]
Arctos is not down.

**Comment by Jegelewicz** [comment]
Working for me.

**Comment by campmlc** [comment]
Appears to be a university wifi problem, blocking Arctos but not other websites?
