### ISSUE TITLE
Feature Request - allow collections to prefer identifier types

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4622]
**Is your feature request related to a problem? Please describe.**

Collections want some types of IDs near the top of the page

**Describe what you're trying to accomplish** 

@ccicero @mkoo @campmlc 

**Describe the solution you'd like**

List of IDs to prioritize under manage collection

**Describe alternatives you've considered**

don't

**Additional context**

https://github.com/ArctosDB/arctos/issues/4605

**Priority**

?

**Comment by campmlc** [comment]
I would say the priority of this goes along with the priority of #4605 -
because folks will want to see their favorite IDs that might be hidden
under the new model?

**Comment by dustymc** [comment]
> folks will want to see their favorite IDs

And almost assuredly others will see those few selected IDs, assume they've found everything (and maybe that Arctos is broken if they searched by something that's not among the chosen few), not scroll, and leave without what they came for. I don't think I'm ever much of a fan of putting arbitrary bits of a thing in one place and the rest in some other (https://github.com/ArctosDB/arctos/issues/3973 still gets me every single time), but if this is necessary to proceed with the tools that let me make full use of Entities then I'll not object.

**Comment by Jegelewicz** [comment]
I hear you, but we can also simply end the "favorite IDs" section with something like

**See all the identifiers associated with this catalog record**

that jumps you down to the richly annotated identifiers section.

I am starting to think we need a re-do of the top of the record summary - which is just another form of splitting the record up. How many people look at that an move on, not knowing there is a whole lotta goodness if they just keep scrolling?

**Comment by dustymc** [comment]
>re-do

Heck yea, but maybe https://github.com/ArctosDB/arctos/issues/2893 first?

>which is just another form of splitting the record up

Excellent point - I think my brain just completely tunes that stuff out. If we keep that "subheader" then maybe that's where the selected identifiers belong (with an anchor-link, like parts).

**Comment by dustymc** [comment]
Getting rid of the [identifier-jumble](https://github.com/ArctosDB/arctos/issues/4605) seems to be blocked by this, and I'm not going to rebuild those (for consistency with https://github.com/ArctosDB/arctos/issues/4650) and then immediately throw that out, so going active on this.

**Comment by dustymc** [comment]
In next release - use manage collection or let me know and I can set these for you with the release.


<img width="821" alt="Screen Shot 2022-05-25 at 10 50 20 AM" src="https://user-images.githubusercontent.com/5720791/170330111-4087bbb6-d5d5-47bd-9cbc-d1848fe171d7.png">

<img width="816" alt="Screen Shot 2022-05-25 at 10 51 33 AM" src="https://user-images.githubusercontent.com/5720791/170330348-c4f04209-9a8b-47f3-afd5-58f5aabf2993.png">


<img width="1092" alt="Screen Shot 2022-05-25 at 10 52 09 AM" src="https://user-images.githubusercontent.com/5720791/170330423-95f9a07c-300b-4eae-bfd1-d84924aefb26.png">

**Comment by ewommack** [comment]
I added it in the UWYMV collections and it turned out great, and was super easy to do. Thanks @dustymc 
![ID example](https://user-images.githubusercontent.com/18562884/170764215-ea7a79db-d270-4246-bce6-7a4dc04f459d.png)
!
