### ISSUE TITLE
Error on Loan Item Bulkload

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4624]
Getting unknown error trying to load loan items. 
load fail::ERROR: syntax error at or near "where" Position: 99

Here is the file - I don't see anything wrong with it, other than that I added a new condition for the first time using this tool
[bulkloadLoanItemData_errors.zip](https://github.com/ArctosDB/arctos/files/8587201/bulkloadLoanItemData_errors.zip)
.
Priority: High - need to complete this loan.

**Comment by dustymc** [comment]
I need to see the error

**Comment by campmlc** [comment]
It's what I posted above: "load fail::ERROR: syntax error at or near "where" Position: 99"

**Comment by dustymc** [comment]
Oh - derp, got it.

**Comment by dustymc** [comment]
patched

**Comment by campmlc** [comment]
Thanks!
