### ISSUE TITLE
New tool request - Clone records in bulk

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4627]
Request for help to clone 60 DGR:Mamm records as MSB:Mamm with all parts, identifiers, loan and publication history, identifications etc transferred entirely over to the new MSB:Mamm record.  I also need the original DGR:Mamm catnum to be added to the new MSB:Mamm record as an identifier referencing self, so the DGR records can be encumbered.
Why: DGR:Mamm no longer exists; I need to loan tissues from these specimens and therefore need an MSB:Mamm catnum to assign to the loan.
Alternatives: Cloning each one of the 60 by hand. Hopefully there is a better option?
The same accession can be used: 2003.913.DGRMamm = transaction_id=1000691
Priority: High, needed for loan request

List to clone:
DGR:Mamm:31520,DGR:Mamm:31522,DGR:Mamm:31530,DGR:Mamm:31532,DGR:Mamm:31543,DGR:Mamm:51101,DGR:Mamm:51110,DGR:Mamm:51112,DGR:Mamm:51116,DGR:Mamm:51124,DGR:Mamm:51126,DGR:Mamm:51132,DGR:Mamm:51134,DGR:Mamm:51136,DGR:Mamm:51138,DGR:Mamm:51140,DGR:Mamm:51147,DGR:Mamm:51149,DGR:Mamm:51152,DGR:Mamm:51155,DGR:Mamm:51157,DGR:Mamm:51160,DGR:Mamm:51162,DGR:Mamm:51164,DGR:Mamm:51167,DGR:Mamm:51168,DGR:Mamm:51170,DGR:Mamm:51176,DGR:Mamm:51178,DGR:Mamm:51181,DGR:Mamm:51183,DGR:Mamm:51185,DGR:Mamm:51187,DGR:Mamm:51190,DGR:Mamm:51204,DGR:Mamm:51205,DGR:Mamm:51207,DGR:Mamm:51214,DGR:Mamm:51216,DGR:Mamm:51218,DGR:Mamm:51220,DGR:Mamm:51222,DGR:Mamm:51226,DGR:Mamm:51235,DGR:Mamm:51237,DGR:Mamm:51239,DGR:Mamm:51241,DGR:Mamm:51243,DGR:Mamm:51253,DGR:Mamm:51255,DGR:Mamm:51257,DGR:Mamm:51266,DGR:Mamm:51267,DGR:Mamm:51269,DGR:Mamm:51271,DGR:Mamm:51274,DGR:Mamm:51276,DGR:Mamm:51277,DGR:Mamm:51279,DGR:Mamm:51281

**Comment by campmlc** [comment]
Looks like @jldunnum already loaded records to the bulkloader, and I marked to load. So yes, we can download/upload, but I don't think that captures everything about a record, including citations?
Looks like @jldunnum cloned each of the 60 one at a time using the tool below in Other IDs in order to clone the full record. I don't think there is a bulkload tool for this
![Screenshot 2022-04-29 08 17 18](https://user-images.githubusercontent.com/14808196/165962691-a8e6d21b-8ff8-4f5b-8faf-ad61ef474251.png)
?

**Comment by campmlc** [comment]
It was a request for immediate help, but then I found out that Jon had created records already in the bulkloader. So now, it is a request for either the ability to clone full records in groups or for help with converting the remaining full DGR records to MSB - whatever is easier , but this isn't urgent.
Priority is now Low.

**Comment by Jegelewicz** [comment]
> converting the remaining full DGR records to MSB - whatever is easier , but this isn't urgent.

Is this so that the DGR stuff can go away? Priority is low now, but tomorrow it will become critical for something else that needs loaning. How are you tracking what has already been cloned over and what is left to clone? Can I hel just get a task done so that it is one less thing to worry about?

**Comment by campmlc** [comment]
Note that the records entered above were not cloned in full, and don't have relationships to the original cloned record- these are going to have to be bulkloaded separately. So we still do need some means of making these conversions.

**Comment by campmlc** [comment]
Sure, happy to get it done. I think the majority of DGR records now are birds, as @jldunnum has been systematically working on the mammals. Whatever we do, we need to clone in full (citations etc) but we also need a relationship to the original identifier, which we can't get using the one click at a time clone in full from Other ID. The other issue, which does affect my ability to deal with tissues in loans, is that the DGR records have the part barcode and location, and this would need to transfer to the new record and disappear from the DGR records. Also, DGR records need to be removed from loans and replaced with MSB records so there are no dependencies and the DGR records can be encumbered. So this is a bit more effort than just cloning, but cloning is a good start.

**Comment by dustymc** [comment]
Everything that's left in DGR is probably a horrible mess of one form or another - we've been through it a couple times now, I think even the moderately-scary stuff has been dealt with.

>also need a relationship to the original identifier

"Relationship" implies keeping the old record around, where we can do this again in a few years. Strongly suggest a full cleanup if we're going to do anything. (And that probably involves at least new remarks at this point, see below.)

>DGR records need to be removed from loans and replaced with MSB records 

That's probably part of the aforementioned giant mess. Some of those loans are likely still open, have instructions regarding citations, etc., etc. I very strongly suspect that spending even a half-hour straightening an important record out now is likely to save ridiculous amounts of time in the future.

@lkvoong probably still has scripts, they may or may not be useful (they're probably a few versions out of date and written in oracleish) or I could potentially let the component loader run the clone function to bring this to the UI, but I am almost positive that pretending this is a technical issue and skipping the human component would be a huge mistake.

@jldunnum

**Comment by Jegelewicz** [comment]
I will help, but need clear instructions and access to all collections. I need to be certain that I am not interfering with anyone else's work or creating duplicates. I can see what needs to be done in general from the above, but on a record-by record basis, how would I know what has already been cloned? Barcode moved? ID added?

**Comment by campmlc** [comment]
We will also have to loop in MSB:Bird folks because they have been pre-assigning catalog numbers, so we need a series that has not been used. 
We need to clone everything associated with a record, including all identifications, citations, identifiers, relationships, events, attributes, parts, and part barcodes and locations - including barcode-less parts that have a label and location.
@dustymc can you generate a csv list of all current DGR records? I can try to screen for ones that are related to other MSB clones.

**Comment by campmlc** [comment]
I need to be able to clone the following series immediately to issue a loan in the next week. How should I proceed?
DGR:Mamm:31520,DGR:Mamm:31522,DGR:Mamm:31530,DGR:Mamm:31532,DGR:Mamm:31543,DGR:Mamm:51101,DGR:Mamm:51110,DGR:Mamm:51112,DGR:Mamm:51116,DGR:Mamm:51124,DGR:Mamm:51126,DGR:Mamm:51132,DGR:Mamm:51134,DGR:Mamm:51136,DGR:Mamm:51138,DGR:Mamm:51140,DGR:Mamm:51147,DGR:Mamm:51149,DGR:Mamm:51152,DGR:Mamm:51155,DGR:Mamm:51157,DGR:Mamm:51160,DGR:Mamm:51162,DGR:Mamm:51164,DGR:Mamm:51167,DGR:Mamm:51168,DGR:Mamm:51170,DGR:Mamm:51176,DGR:Mamm:51178,DGR:Mamm:51181,DGR:Mamm:51183,DGR:Mamm:51185,DGR:Mamm:51187,DGR:Mamm:51190,DGR:Mamm:51204,DGR:Mamm:51205,DGR:Mamm:51207,DGR:Mamm:51214,DGR:Mamm:51216,DGR:Mamm:51218,DGR:Mamm:51220,DGR:Mamm:51222,DGR:Mamm:51226,DGR:Mamm:51235,DGR:Mamm:51237,DGR:Mamm:51239,DGR:Mamm:51241,DGR:Mamm:51243,DGR:Mamm:51253,DGR:Mamm:51255,DGR:Mamm:51257,DGR:Mamm:51266,DGR:Mamm:51267,DGR:Mamm:51269,DGR:Mamm:51271,DGR:Mamm:51274,DGR:Mamm:51276,DGR:Mamm:51277,DGR:Mamm:51279,DGR:Mamm:51281

**Comment by dustymc** [comment]
See https://github.com/ArctosDB/arctos/issues/4634, I still don't have clone magic, the offer to move remains open. If the politics can't be worked out in time, the bulkloader is the most realistic path.

**Comment by campmlc** [comment]
Because of the failure of my attempt to get the DGR:Bird collection on board with doing a single conversion of DGR to MSB, I am going through the laborious process of cloning each of these 60 records one by one. 
Ideally, it would have been much easier if I could have done this using option 1, "clone full cataloged item" - instead of option 2, "create clone in bulkloader" - but I would need option 1 to allow cloning from one guid prefix into a different guid prefix. If this is possible, it would greatly help with future conversions of DGR records, and it could also be useful for collections that wish to move a cataloged item from a main collection into a teaching collection, for example.
In the current situation, however, because I created the clones one by one in the bulkloader, I have lost all identification history, citations, Other ID relationships, and all part locations. The latter is especially problematic, because these were all legacy objects converted from the DGR Locator - parts have locations but no barcodes. And I can't add to the loan without the barcodes attached to the parts first.
The workflow I have to do this requires I barcode all parts, use the scary barcode swapper to add the parts in the DGR records to the barcodes while preserving their locations, and then use the parts to containers tool to load all the MSB:Mamm parts to the same barcodes, all prior to deleting the DGR records. 
However, I've only barcoded the 60 parts that are in this loan I'm trying to process. I don't have the time or resources to track down and barcode all of the remaining non-loan parts. I still could do the above workflow, but it would leave all of the other parts not pulled for loan with no locations, and it would prevent me from deleting the DGR records. All of the part location info would be in the DGR records, and some of it would be duplicated in the MSB records, resulting in a giant mess that I would not remember how to sort once I stop focusing entirely on this after today.

So, I'm asking for some help here.  Attached is the file of part locations for the DGR parts, and the corresponding MSB records that share an NK. I need the part locations from the DGR records added to the MSB records, without requiring a barcode. Possible?
Priority: High. Blocking urgent loan processing.
[partFlatDownload - 2022-06-17T161242.701.zip](https://github.com/ArctosDB/arctos/files/8931724/partFlatDownload.-.2022-06-17T161242.701.zip)

**Comment by dustymc** [comment]
Let's set up a time to talk next week. @lkvoong might be able to move (not clone, move) selectively, at least by collection. From here, cloning looks like its just going to make messier messes, and I don't think there's any way I can safely script part locations in between what looks to me like two messes.

**Comment by campmlc** [comment]
Happy to talk next week, but I need a final list of loan items to give to the loan recipients, and I have to add the cloned MSB parts to the loan. That will create subsamples of the already cloned parts with no locations - which is going to be an even messier mess.

**Comment by campmlc** [comment]
I've gone ahead and manually created the clones I need for this loan, transferred all identifier and citation data, added barcodes to both the DGR (via scary barcode swapper) and MSB (via parts to containers) records, and bulkloaded the MSB parts to the loan using Part ID (since I can't use the barcodes which are now associated with two different guids). This means I can generate a loan form to send to the recipient with the correct MSB numbers to cite for the loan. But is also means I have MSB records where some of the cloned parts have no part locations, since these parts weren't barcoded for the loan, but were instead cloned via the bulkloader without their locations. The part locations for these can only be found in the corresponding DGR records. 
This means I cannot delete the DGR records. This is OK, really, although I'm not sure anyone but me would ever know where to look to find these data. But at least the data aren't lost.
My view from this point is still that what would have been best from the beginning would be to be able to clone the original record from DGR:Mamm to MSB:Mamm. Clone - not move. There are too many dependencies in the literature, too many of these kind of hacked attempts to deal with this same problem over the years. I do not want to risk losing data without being able to go through the DGR records individually, which will only happen as these records are included in loans. But I don't want to have to go this process for any future loans. I just need to be able to clone an entire record from one guid prefix into another guid prefix.  Can we do this?

**Comment by campmlc** [comment]
Here are the original DGR records:
https://arctos.database.museum/saved/DGR%20Mamm%20bats%20for%20Musevirome

and the cloned MSB records: https://arctos.database.museum/saved/DGR%20to%20MSB%20Conversion%20for%20Musevirome%20bats

**Comment by campmlc** [comment]
And here is the project this is for: https://arctos.database.museum/project/10003373
