### ISSUE TITLE
Code Table Request - New agent relationship: established by

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4628]
**Goal**
See https://github.com/ArctosDB/arctos/issues/4540#issuecomment-1112703631

**Context**
associate of is not specific enough for this purpose.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctagent_relationship

**Proposed Value**
creator of

**Proposed Definition**
Used for people who were involved in the creation or development of an organization or other agent.

**Priority**
[  Please choose a priority-label to the right.  ]

@ArctosDB/arctos-code-table-administrators

**Comment by dustymc** [comment]
This seems like a great way to step on toes - 3 people are listed for whatever reason, the 4th who isn't finds this and takes it personally.....

**Comment by Jegelewicz** [comment]
I'll let the people who want this chime in.

FWIW, people can be added. Nobody ever has all of the information, but that is no reason not to record what you do have.

**Comment by wellerjes** [comment]
Context: [Issue 4540](https://github.com/ArctosDB/arctos/issues/4540)
We are using Agents to connect collections within collections to a specific person (within the herbarium collection at ChAS, this specimen belonged to the collection of a specific person at one point in its existence. We have specimens that were exchanged and gifted to other collectors). I want to be able to connect the collection Agent to the person Agent. Right now, the closest I can get is "associate of"; I would like to have something more specific in the code table to link the agents together.
Example: https://arctos.database.museum/info/agentActivity.cfm?agent_id=21294657

**Comment by Jegelewicz** [comment]
@ArctosDB/agents-committee says this seems reasonable.

**Comment by Jegelewicz** [comment]
What about "founder of" or go the opposite and use "established by" on the collection agent with relationship to the person?

**Comment by wellerjes** [comment]
I like "established by"

**Comment by Jegelewicz** [comment]
Suggest add

**Goal**
See https://github.com/ArctosDB/arctos/issues/4540#issuecomment-1112703631

**Context**
associate of is not specific enough for this purpose.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctagent_relationship

**Proposed Value**
established by

**Proposed Definition**
Used for people who were involved in the creation or development of an agent of type organization or other agent.

**Priority**
[  Please choose a priority-label to the right.  ]

@ArctosDB/arctos-code-table-administrators

**Comment by Jegelewicz** [comment]
Code Tables says go

**Comment by Jegelewicz** [comment]
added
