### ISSUE TITLE
Code Table Request - New other identifier = MBDB: Meteoritical Bulletin Database

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4629]
**Goal**
Make use of "entity" identifier for meteorites

**Context**
UNM:MET has identifiers for named meteorites from MBDB and could use this functionality

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type

**Proposed Value**
MBDB: Meteoritical Bulletin Database

**Proposed Definition**
Identifier assigned by the Meteoritical Bulletin Database (MBDB)

**Other ID BaseURL**

"Base URL" with which to prepend entered values, - https://www.lpi.usra.edu/meteor/metbull.php?code=

and

A functional example URL, which should consist of the base URL provided in (1) plus a relevant value. https://www.lpi.usra.edu/meteor/metbull.php?code=23166

**Available for Public View**
Yes

**Priority**
[  Please choose a priority-label to the right.  ]

@ArctosDB/arctos-code-table-administrators

**Comment by Jegelewicz** [comment]
@dustymc any objection?

**Comment by dustymc** [comment]
nope

**Comment by Jegelewicz** [comment]
added
