### ISSUE TITLE
test nuttiness?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4630]
Just tried to access test and got this.

![image](https://user-images.githubusercontent.com/5725767/165995154-558998d0-1b6a-4651-9d02-7ca618cefbb9.png)

Bug or just work being done?

**Comment by dustymc** [comment]
work - http://arctos-test.tacc.utexas.edu may or may not be available from outside

**Comment by Jegelewicz** [comment]
That works, but my login there doesn't. No worries - I'll check back later...
