### ISSUE TITLE
Feature Request - make DGR go away

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4634]
What would be required to move all DGR records to their respective "real" collections?

@campmlc

**Comment by campmlc** [comment]
For DGR:Mamm: just clone in full, all citations, identifications attributes,, parts, and part labels /barcodes. I believe they can use the same accession?

For MSB:Birds, ditto, but I need to get a series of preassigned catnums from the curator. Let's go with Mammals first. 
@dusty do you need access?

**Comment by dustymc** [comment]
This is not an offer to clone. This is an offer to MOVE. That would result in the DGR collections being completely empty, and the problem that lead here no longer existing.

A list of new catnums would work.

Doing everything at once is very strongly preferred - it's no longer easy to find a time when Arctos isn't busy, doing this requires significant lockdown, we'd very much like to not do that multiple times.

**Comment by campmlc** [comment]
I understand. I'll need to know exactly how many records now exist in each
DGR collection.

**Comment by dustymc** [comment]
https://arctos.database.museum/SpecimenResults.cfm?guid_prefix=DGR:Ento
https://arctos.database.museum/SpecimenResults.cfm?guid_prefix=DGR:Mamm
https://arctos.database.museum/SpecimenResults.cfm?guid_prefix=DGR:Bird

**Comment by campmlc** [comment]
Not sure what was completed here? @dustymc

**Comment by mkoo** [comment]
only single MSB:DGR exists now

**Comment by dustymc** [comment]
>single

The messes still exist, efforts to change that have been rejected, closing this is the correct action at this time, thanks.


```
arctosprod@arctos>> select guid_prefix from collection where guid_prefix ilike '%dgr%';
 guid_prefix 
-------------
 DGR:Bird
 DGR:Ento
 DGR:Mamm
 MSB:DGR
(4 rows)
```

**Comment by campmlc** [comment]
For the record, MSB: DGR is a legitimate new collection that should not be eliminated. The others have numerous critical problems such as loan dependencies and object tracking issues that make a single solution impossible. They will likely need to be tackled one record at a time, which would be much easier if the clone feature would enable a full clone into a different collection.
