### ISSUE TITLE
[CONTACT: Blocked Network]

### ISSUE THREAD

**Issue by isavivas** [ArctosDB/arctos#4636]
restricted IP: 187.189.221.209

Good morning. I am having troubles accessing the Arctos database.  It says that my IP or organization has been blocked. I checked my PC for malicious software and did not find anything strange. I am PhD student from Universidad Nacional Autonoma de Mexico, Mexico City, and I am looking for data on specific specimens at institutions stored in the Arctos databases for research purposes. I would like to know how can I solve this issue. Thank you very much.

Isabela Vivas, MSc, PhD student
Museum of Zoology Alfonso Herrera
Faculty of Science
Universidad Nacional Autonoma de Mexico
Mexico

**Comment by dustymc** [comment]
released
