### ISSUE TITLE
convert datum

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ArctosDB/arctos#464]
```
Need to add columns to ctdatum:

1semimajoraxis_a
2 flattening_f
3 eccentricitysquared_e2
4 deltasemimajoraxis_da
5 deltaflattening_df
6 deltax_dx
7 deltay_dy
8 deltaz_dz

and wgs84_declat and wgs84_declong columns to lat_long, then apply triggers 
using the parameters stored in ctdatum to convert using code from 
http://home.hiwaay.net/~taylorc/bookshelf/math-science/geodesy/datum/transform/m
olodensky/


```

Original issue reported on code.google.com by `dust...@gmail.com` on 21 Oct 2010 at 5:33

**Comment by dustymc** [comment]
ref #115 - can these be combined?

**Comment by tucotuco** [comment]
The Molodensky transform is not always the best one to transform geographic coordinates to WGS84. It is not a simple issue. See http://www.epsg.org/Portals/0/373-07-2.pdf?ver=2019-03-08-165437-017.
