### ISSUE TITLE
Code Table Request - Other identifier = SEINet ID

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4643]
**Goal**
Provide capability to link to records in the SEINet Symbiota portal

**Context**
We can actually link up to multiple Symbiota portals with a single identifier, but each portal has it's own base url

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type

**Proposed Value**
SEINet ID

**Proposed Definition**
Integer ID assigned by Symbiota to the record.

**Collection type**
all

**Other ID BaseURL**
[  For OtherIDs, provide the following *or* explain why the unresolvable ID type is necessary:
1. https://swbiodiversity.org/seinet/collections/individual/index.php?occid=
2. https://swbiodiversity.org/seinet/collections/individual/index.php?occid=15853761
3. See it in action in test - http://arctos-test.tacc.utexas.edu/guid/UTEP:Herb:11983

**Priority**
[  Please choose a priority-label to the right.  ]

We could create similar other IDs for any Symbiota portal

SCAN: https://scan-bugs.org/portal/collections/individual/index.php?occid=
TORCH: https://portal.torcherbaria.org/portal/collections/individual/index.php?occid=

Caveat - what happens the next time UTEP updates with SEINet? Does the number change?

**Comment by Jegelewicz** [comment]
https://arctos.database.museum/guid/UTEP:Herb:11981 has some test identifiers

**Comment by dustymc** [comment]
I don't understand the use case - what's the benefit of linking to minimal repackaged data?

**Comment by Jegelewicz** [comment]
> what's the benefit of linking to minimal repackaged data?

Case in point - GBIF and iDigBio links?

But beyond that - I have just been made aware of the fact that SEINet includes annotations - I think we need to start looking at ways to bring those into Arctos. See https://swbiodiversity.org/seinet/collections/individual/index.php?occid=22946931 comments tab This was cited as being very important to UNM Herbarium last week.

Also, we may have things in Arctos that could be linked to things that are not "repackaged data" in SEINet. Check the duplicates tab for this record - https://swbiodiversity.org/seinet/collections/individual/index.php?occid=12500194&clid=0

**Comment by dustymc** [comment]
>GBIF and iDigBio links?

Those folks have APIs, there's no "add their identifiers" involved, it's all dynamic and uses our identifiers. Does seinet have an API?

>See https://swbiodiversity.org/seinet/collections/individual/index.php?occid=22946931 comments tab T

<img width="481" alt="Screen Shot 2022-05-21 at 12 45 39 PM" src="https://user-images.githubusercontent.com/5720791/169666915-e1d20309-7a93-47fd-ab5e-e4dc02aec57f.png">

??

If I had my way, a condition of repackaging our data would be using our API for annotations. 

>duplicates tab

OK, that's cool, but it should be handled by something other than a person adding a made-up identifier and then hoping someone clicks it and copy-pastes and doesn't mess that up and....

In any case I'm not exactly objecting to this sort of thing, but it would be good to get something back, and it would be very good to not need their identifiers to do it. They do seem to have something to offer, surely there's a less-kludgy way to get at it??

**Comment by Jegelewicz** [comment]
[An open API to help document Symbiota tools and terms](http://laura.rochaprado.com/symbiota-tooltips/)?

**Comment by campmlc** [comment]
We are the process of integrating Symbiota and Arctos records at MSB. The Arctos record will be the tissues, the SEINet and SCAN Symbiota records will be the vouchers. We need to be able to link these records - and a url pointing from Arctos would be ideal. Symbiota portals already can link back to Arctos - see above https://swbiodiversity.org/seinet/collections/individual/index.php?occid=15853761
These discussions started last week, and are pressing, as they involve endangered species genomic materials. The door is open - it would be good to do something, anything, even if we improve on it later.

**Comment by Jegelewicz** [comment]
@campmlc the question for me is do we need to add a bunch of identifiers (one for each Symbiota portal) or just one? I think we could go with just one if the thing we put in the value is the entire link.

If you look in my examples in https://arctos.database.museum/guid/UTEP:Herb:11981

![image](https://user-images.githubusercontent.com/5725767/217278763-c64d78b2-f347-4bf4-a270-8d2698e3f5b2.png)

the one thing you notice is that although this record appears in both the TORCH and SEINet portals, it always has the same identifier "22946931" which means (I think) appending that to any of the Symbiota portals should produce the related record.

It seems like we have created this "base url" thing but we don't want to use it here for some reason. Isn't this is exactly what it was meant for?

**Comment by Jegelewicz** [comment]
From @campmlc email

> what do we need to do to turn this into a live link?

Record in question is https://arctos.database.museum/guid/UTEP:Herb:100005

Identifier in question is 

![image](https://user-images.githubusercontent.com/5725767/217579630-15ed8224-6544-43dd-9e08-f03db871a106.png)

We either need to se this up as an identifier with a base url (see my original proposal above) or you could enter the identifier this way

`<a href="https://swbiodiversity.org/seinet/collections/individual/index.php?occid=19233620&clid=0" class="external">https://swbiodiversity.org/seinet/collections/individual/index.php?occid=19233620&clid=0</a>`

which is just unacceptable in my opinion

I think we also need to make sure this question gets answered

> what happens the next time UTEP updates with SEINet? Does the number change?

Maybe we need a meetup with Katie Pearson

**Comment by dustymc** [comment]
We really need to develop an identifiers policy.

See above regarding API, which is clearly the correct way to do this.

Any sort of linking can be done as Media.

**Comment by Jegelewicz** [comment]
I am closing this in favor of using other identifier and issued by Symbiota.

**Comment by campmlc** [comment]
Can we add an agent for SCAN and SEINet and other Symbiota portals,and use
those for the issued by? Because I believe the SEINet IDs are specific to
SEINet?

**Comment by Jegelewicz** [comment]
> I believe the SEINet IDs are specific to SEINet?

Nope - the identifier is the same across all Symbiota portals - see https://github.com/ArctosDB/arctos/issues/4643#issuecomment-1420920663. The only thing that changes between portals is the base url. I can create agents for each of the portals, but before I do - are we sure that is necessary? Also, I really think these should be treated just like the GBIF, iDigBio and GloBI links because those Symbiota instances are just diminished copies of Arctos data. Unfortunately, I don't think there is an available API that would let Dusty magic them in.

**Comment by dustymc** [comment]
>the identifier is the same 

It clearly is not, there is no joy in dealing with partial identifiers, the current model doesn't need any new values to do this.

>treated just like ... don't think there is an available API 

Then they can't be treated just like!

GBIF, iDigBio and GloBI work because they use OUR identifiers, along with having an API. Symbiota and clones is refusing to do that, but instead adding their own identifiers. There's no equivalency.

**Comment by Jegelewicz** [comment]
@dustymc they actually do have our urls - sorta. See https://swbiodiversity.org/seinet/collections/individual/index.php?occid=19233620

![image](https://user-images.githubusercontent.com/5725767/229943064-b700e4b3-1e33-4caf-ade9-75dfd800ba60.png)

We need to work with them to have the catalog record urls placed in Linked Resources! Then we might move one step closer....
