### ISSUE TITLE
entity magic updates

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4645]
* Make the "can't make entity list" be downloadable
* POST to avoid 431 errors when lots of problems
* display the chosen ID type rather than just the value
* consider new members of existing entities - not sure that can be part of the form, but try to avoid making messes

**Comment by Jegelewicz** [comment]
> consider new members of existing entities - not sure that can be part of the form, but try to avoid making messes

Yeah man, once we have a bunch if we just go magic-happy, we will end up with a bunch of duplicate entities. Instead of just tossing stuff that already has an organism ID, maybe a warning that an entity already exists and you should add new stuff to it?
