### ISSUE TITLE
don't show bare part names

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4649]
**Is your feature request related to a problem? Please describe.**

Bare part names never make sense - build ``part_name (unique attribute list)`` or something, show it anywhere part name can be seen by itself.

Need guidance on the format.

@mkoo : just preservation?

Display in:

* "header" of guid view
* attribute-free part views
* results

**Priority**

High?

**Comment by dustymc** [comment]
Normalizing remaining parts seems to hinge on this, prioritizing

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I think it might be helpful for collections to be able to choose which attributes show up. For example, with our paleo collection preservation isn't super important, but part modifier is.

**Comment by dustymc** [comment]
This is running at production - request a cache refresh, wait, reload to see it now, or it should catch up everywhere in a couple weeks.
