### ISSUE TITLE
Is it possible to encumber some or all info for a particular agent?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4652]
Is it possible to encumber some or all info for a particular agent? This relates to other discussions, e.g. students who have a restraining order on someone who could theoretically locate their info or where they are currently working online. It seems a shame to hide all information for all agents to protect sensitive information for a few.

_Originally posted by @campmlc in https://github.com/ArctosDB/arctos/issues/3000#issuecomment-669389483_

**Comment by ewommack** [comment]
Thanks for getting this in the issues @Jegelewicz

**Comment by dustymc** [comment]
>possible to encumber some or all info for a particular agent?

No, it is not.

We could potentially try, but given the scope of agents (they're everywhere) and the nature of Arctos (we try to make things public) and the size of our security team (ain't got one) and such, I'm not sure how realistic such a thing might be.

If some sort of time-traveling cyborg assassin was coming for me, I'd want to be removed from Arctos entirely. (And I'd hope there weren't any of those frighteningly common "DLM May 11 2022" remarks floating around anywhere...)

https://github.com/ArctosDB/arctos/issues/4653 and the deeply relational nature of Arctos provides a plausible, if not perfect, alternative for less-critical situations: name the agent "definitely not Sarah Connor" and use the restricted remarks for the private bits.

**Comment by lin-fred** [comment]
Agent committee discussed that we probably need a use case for us to be able to move forward with such a large project. https://github.com/ArctosDB/arctos/issues/4653 is a good way to help start this

closing for now
