### ISSUE TITLE
Agent Biography

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4653]
Currently any agent bios are placed in remarks. AWG today discussed creating a "biography" field for public biographical information and also requested a "hidden" field for "internal" information. Is there broader interest in this? How should we proceed?

@ArctosDB/agents-committee

**Comment by AJLinn** [comment]
Perhaps we could change the existing remarks field to be a "Biographical Profile / Agent Remarks" field and then we wouldn't have to selectively migrate a ton of info to a new field. Then we could move any non-biographical or private info into a non-public field that isn't relevant to general users.

**Comment by mkoo** [comment]
Basically the proposal boils down to this:

- add to the edit form a note that the reminds users that Remarks field is public
- on the public form page, Change "Remarks about" to "Biographical Profile / Remarks about" or maybe "Profile and Remarks about" (feedback on wording?)
- I would propose to change the Title "Agent Summary for" to just "Summary for"
- Add a new field for private remarks that are not public but viewable for any with edit permissions ("curatorial remarks" maybe?)
web page for reference:
![Firefox_Screenshot_2022-05-07T02-41-27 184Z](https://user-images.githubusercontent.com/2523089/167235071-3d6e1b58-9170-4757-a7fc-ce7083e6bfad.png)

**Comment by droberts49** [comment]
Teresa showed me how to do this in html. Thank you @Jegelewicz 

Can we add urls for biographic info online? I use the url in the contact info at the bottom and put the website/page name in the remarks field, but the remark (website name) doesn't show up on the public page.

**Comment by Jegelewicz** [comment]
Can we add urls for biographic info online?

Use this - https://arctos.database.museum/DataServices/linkerizer.cfm to get the html

**Comment by Jegelewicz** [comment]
@ArctosDB/agents-committee needs to create a mock-up so that Dusty knows what we want.

**Comment by dustymc** [comment]
>put the website/page name in the remarks field

You're of course welcome to replicate anything you want in remarks, but **please** also enter that sort of thing as an address.

>Dusty knows what we want

Well I hope I've got a handle on it, this will be in next release, maybe tonight....

**Comment by lin-fred** [comment]
If @dustymc is making the changes that @mkoo suggested, I think that is great for now.

I will still do a mockup meeting, which will mostly be for this issue https://github.com/ArctosDB/arctos/issues/3000
but biography information/changes will also fall under it anyway.

**Comment by krgomez** [comment]
I like the idea of changing the remarks field to something that is more specifically for a biography, since this is also how the UAM Art collection uses it. One thought is perhaps it would be good to have a related field for a citation to reference where the bio came from? I think the source is important to keep track of, but the only way to do that currently is to record it along with the bio text in that field. Maybe others are fine continuing to do that though.

**Comment by dustymc** [comment]
>citation

If it's a URI then it should be an address, if not then publications.
