### ISSUE TITLE
Display of special characters

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#4654]
@jrdemboski has some identification remarks that include the greater than (>) and less than (<) signs for identifying shrew species, eg, U3<U4. See: https://arctos.database.museum/guid/DMNS:Mamm:20924.
The info is entered into the field - you can see it when you go in to edit it. But these symbols and everything after them do not display on the record page. Can we get these to display properly? Thanks

**Comment by acdoll** [comment]
So, we just discovered that if there is a space in-between the symbol and the other text then the text will appear as it should. I'll leave this open for @dustymc to close, just so he's aware.

**Comment by acdoll** [comment]
FWIW: It looks like it is actually just the < symbol.

**Comment by dustymc** [comment]
> just the < symbol.

And then only if certain things follow - your browser is trying (not very successfully...) to be "helpful" and turn it into HTML. It's encoded for next release.

**Comment by acdoll** [comment]
Thanks!
