### ISSUE TITLE
What type of agent?

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#4655]
I have an agent, [Nunuk](https://arctos.database.museum/agents.cfm?agent_id=21320229), which is a pseudonym used by a Seattle-based carving establishment to make objects appear to be made by Alaska Native carvings. It does not represent a real person, but is a name applied to objects like it's a real person.

I have this noted in the Agent Remark, but I don't think the agent type should be person... I guess I could do "other agent" - but does this happen to anyone else? Does anyone have a better solution?

**Comment by dustymc** [comment]
Agree, definitely not a person.

Google suggest "Nuguruk" might be the name of the company, or maybe just another pseudonym - it should be included as some name.

And address=Seattle would be useful.

**Comment by AJLinn** [comment]
I just added Nuguruk and found a 1969 FTC listing the complaints against the Seattle-based marketers. Added as a media and gave relationships showing both agents. 
One thing I learned is that non-person agents can't have a first, middle, last name.
