### ISSUE TITLE
MVZ:Arch Request - initiate incremental loan-like transaction numbers

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#4657]
We would would like to request incrementing transaction numbers for MVZ:Arch (start with this year and 1). 
there's a strange number currently (see below) but maybe it will disappear if the numbers increment!

![Firefox_Screenshot_2022-05-09T03-31-58 775Z](https://user-images.githubusercontent.com/2523089/167336506-7ec5c709-89d1-4636-9e17-9539b4aabf91.png)

Looking at this more, I wonder if the increments are confused about which collection it is associated with now that we have cultural and bio collections in more than one institution? 
FYI, Currently not urgent but will be in a few months

**Comment by cjconroy** [comment]
The next MVZ loan is 9229, in case that helps.
