### ISSUE TITLE
Loan item bulkload not loading?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4659]
Trying to bulkload loan items - it has been 30 mins to load 25 items, nothing is happening.
Need to process this loan today - possible?
Priority: Medium high

**Comment by dustymc** [comment]
There is a status report.

**Comment by campmlc** [comment]
I looked at the status report - what does this mean?
<html>
<body>
<p style="color: rgb(0, 0, 0); font-family: Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">FILTERED_FLAT serves the same purpose to public users.</p>

Status | NumberRecords
-- | --
current | 4405794
error_in_processing | 106
filtered_flat_processing | 1
flat_processing | 2

<br class="Apple-interchange-newline">
</body>
</html>

**Comment by campmlc** [comment]
I have no way of interpreting that to know whether I should go get a cup of coffee or file an issue.

**Comment by campmlc** [comment]
Same problem. Trying to load 26 items for two loans., waiting for over an hour.  I need to be able to load the loan items, print the documents, and ship same afternoon. I can't wait 24 hrs for loan items to load. What's up?
![Screenshot 2022-05-16 16 50 51](https://user-images.githubusercontent.com/14808196/168695075-ea37bd60-0a43-48ba-a9c3-e40828e84bfe.png)
