### ISSUE TITLE
Feature Request - Migration to GNverifier API from GNresolver API

### ISSUE THREAD

**Issue by dimus** [ArctosDB/arctos#4662]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

I am planning to sunset http://resolver.globalnames.org in 2023.

**Describe what you're trying to accomplish** 

@dustymc, @Jegelewicz, I am releasing [GNverifier API](https://github.com/gnames/gnames) v1.0.0 in the end of May, start of June. 
[GNresolver code ](http://resolver.globalnames.org/) is now dated, 30 times slower than GNverifier is, and it experiences intermittent "Denial of Service" moments
when is pounded too much by users.

I am thinking to remove resolver.globalnames.org service sometime in 2023.

**Describe the solution you'd like**

It would be great if you could migrate your GlobalNames queries to new API sometime after GNverifier v1.0.0 is out (June 2022) and  before the mid 2023.  

**Additional context**

New API is currently located at https://apidoc.globalnames.org/gnames-beta and will migrate to https://apidoc.globalnames.org/gnames after v1.0.0

A simple example:  https://verifier.globalnames.org/api/v0/verifications/Monochamus%20galloprovincialis?data_sources=1%7C12%7C170&all_matches=true

**Priority**

Moderate/High

**Comment by dustymc** [comment]
Thanks, looks straightforward, give me a ping when the new service is up if you think of it, hopefully this won't get lost either way....

**Comment by dustymc** [comment]
v0 seems to have died, rebuilt next release for v1

**Comment by dimus** [comment]
Hi @dustymc, sorry for not letting your know, I did move gnverifier to v1.0.0, so yes, it is correct to move to /api/v1. It is pretty much the same as /api/v0 was, except that I consider API to "graduate" from development to stable version, and it should be backward compatible now, and will be kept running if/when v2 will appear. It was a hecktic summer for me, I am back to work now.

**Comment by dimus** [comment]
API with examples is described at https://apidoc.globalnames.org/gnames
