### ISSUE TITLE
Code Table Request - new other ID type "Assemblage ID"

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4665]
**Goal**
Get components of a cultural item to show up in an entity in a sensible manner

**Context**
I can get components to show using any generic identifier if I put the Entity url in the identifier value. I have done this using "other identifier" for this dress - https://arctos.database.museum/guid/Arctos:Entity:2

But when looking at any individual component, the "other identifier" doesn't convey what that url actually does. "assemblage ID" seems generic enough that it could be used for many purposes and still provide an indication of what that entity url does.

![image](https://user-images.githubusercontent.com/5725767/168099558-ec894b69-c4e3-441c-adcf-231ce2cc8d92.png)

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type

**Proposed Value**
Assemblage ID

**Proposed Definition**
Identifier applied to multiple parts of an assemblage in order to link them together. The addition of an Arctos:Entity url as the value will include the record as a component in that Entity.

**Comment by Jegelewicz** [comment]
> concept is similar but I imagine the cultural folks would prefer to use

Yeah - lots mean absolutely nothing in this context. These three pieces belong together, but may not have been made or collected at the same time. From a "fashion" sense, a "lot" might be all of the skirts made from a single bolt of cloth....

**Comment by dustymc** [comment]
>a "lot" might be all of the skirts made from a single bolt of cloth

Exactly - they're both "artificial assemblage identifiers" (I think?!) and having multiple ways of saying the same thing is evil.

The definition of lot count already contains 'or manufacturer', which I suspect means we've had this conversation, or parts of it, somewhere. "Same event" is uselessly vague (could mean "that cc^3@millisecond" or "planet before tomorrow" or just different punctuation in some remarks field). If these are the same, we should just find a mutually agreeable definition. If they're not the same, the definitions should make that clear. 

That said, there was also a conversation about making entity-things a sort of "super catalog number" - maybe we should add this new identifier and restrict its usage to Arctos:Entity IDs, do the same for OrganismID (is that practical???), and then do something special with those IDs (and whatever else comes to use Entities) in the UI.

**Comment by campmlc** [comment]
My understanding is that lot and assemblage are not multiple ways of saying the same thing - they say different things. A lot is a group of the same organisms, an assemblage is a group of potentially unrelated items used in the same context.
I do like the idea of the entity as a "super catalog number"

**Comment by ewommack** [comment]
> A lot is a group of the same organisms, an assemblage is a group of potentially unrelated items used in the same context.

That sounds like my understanding as well.

**Comment by Jegelewicz** [comment]
> do the same for OrganismID (is that practical???)

I'd like to yes, but I don't think it is. At some point there may be a perfectly good organism ID outside of Arctos that we might want to use instead of an Arctos Entity (say MVZ has the skeleton, AMNH has the skin AND AMNH already has minted an organism ID - don't laugh, it may happen someday...).

**Comment by dustymc** [comment]
>My understanding is

There's no ambiguity, we have a definition (and it doesn't say that).

>At some point there may be a perfectly good organism ID outside of Arctos

Like everything Arctos, if someone builds a system that sucks less than what we've built we should be positioned to just plug into it. This scenario seems extremely theoretical, but I'm also not sure it changes the idea - replace "Arctos:Entity" with something about "a resolvable identifier specifying a WHOLE in some larger context...." in the definition, and it still works. I'm not sure I'm completely sold on the idea yet, needs more thought/discussion, but I don't think this has to be a hard block either.

**Comment by Jegelewicz** [comment]
Closing until someone needs this.

**Comment by Jegelewicz** [comment]
Reopening for @campmlc

**Comment by Jegelewicz** [comment]
@dustymc what if we switch the Organism ID magic so that the magic is applied to any identifier that has an Arctos:Entity url in it? This means we could use "other identifier" and still get the same magic at the applicable entity. This would also be improved by #4604

**Comment by Jegelewicz** [comment]
Let's go with Material Entity ID and make it clear that you should use organism ID for organisms!

**Comment by Jegelewicz** [comment]
@ArctosDB/arctos-code-table-administrators please review and approve.

**Proposed Value**
Material Entity ID

**Proposed Definition**
An identifier used to link together multiple cataloged items that may be part of an natural or human created assemblage other than an organism. When an Arctos:Entity url is added as the value the record will be included as a component in that Entity. **Note** When linking together separately cataloged parts of an organism, use <a href="https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type#organism_id" class="external">Organism ID</a>.

**Comment by Jegelewicz** [comment]
Committee says Ok to add.

**Comment by Jegelewicz** [comment]
Whoa! Before I add this - does this change anything? https://github.com/gbif/model-material/issues/24#issuecomment-1387206083
