### ISSUE TITLE
Quarantine Taxon Name - 

### ISSUE THREAD

**Issue by atrox10** [ArctosDB/arctos#4668]
Issue Documentation is at http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

Name Quarantine Documentation is at https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxon_name_type

Information requested | Response 
 -- | -- 
Name suggested for quarantine | **replace this with the name suggested for quarantine, and provide link to the Arctos taxon page**
Reason for quarantine | **replace this with the reason for quarantine, links to sources are useful**
Suggested treatment for all identifications currently using this name | **replace this with the suggested treatment for identifications using this name should the period for comment expire with no discussion, in general this will be A {string} = New name {Quarantined name}, provide a link to the New name taxon page in Arctos**
Collections currently using this name in identifications | @dustymc please provide
Collection contacts for above | @dustymc please provide

This name will be quarantined and existing identifications changed to the suggested treatment following the next Arctos Working Group Issues meeting unless comments here suggest this should not happen or everyone affected agrees to the change before then.

Please add this issue to the Taxonomy Committee Project.

**Comment by atrox10** [comment]
[temp_taxon_quarantine_summary.csv](https://github.com/ArctosDB/arctos/files/8681427/temp_taxon_quarantine_summary.csv)
 This name is the unaccepted misspelling of Batrachuperus londongensis. See Amphibian Species of the World 
https://amphibiansoftheworld.amnh.org/Amphibia/Caudata/Hynobiidae/Hynobiinae/Batrachuperus/Batrachuperus-londongensis

or AmphibiaWeb
https://amphibiaweb.org/cgi/amphib_query?where-genus=Batrachuperus&where-species=londongensis
The only collections using this is MVZ, as an unaccepted ID.

**Comment by dustymc** [comment]
Summary:

|guid_prefix|accepted_id_fg|numberids|link_to_records|taxon_name|link_to_taxon|
|--|--|--|--|--|--|
|MVZ:Herp|0|18|https://arctos.database.museum/SpecimenResults.cfm?taxon_name_id=10000910|Batrachuperus longdongensis|https://arctos.database.museum/name/Batrachuperus+longdongensis|


Data Quality Users:


@mkoo
@atrox10

Data:

[temp_taxon_quarantine_reloader(8).csv.zip](https://github.com/ArctosDB/arctos/files/8689498/temp_taxon_quarantine_reloader.8.csv.zip)

User is requestor, proceeding....done
