### ISSUE TITLE
Code Table Request - new taxonomy source = Arctos Insects

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4669]
**Goal**
Ensure insects using identification of Acanthocephala get an appropriate classification

**Context**
See https://github.com/ArctosDB/arctos/issues/4358

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxonomy_source

**Proposed Value**
Arctos Insects

**Proposed Definition**
A source for classifications of taxa within the class Insecta

@ArctosDB/arctos-code-table-administrators

**Comment by dustymc** [comment]
[I still don't like the garbage can classifications.](https://github.com/ArctosDB/arctos/issues/4358#issuecomment-1048174319)

**Comment by Jegelewicz** [comment]
It's less-garbagy than Arctos and will let us have classifications appropriate for the stuff in ASNHC:Ento and NMMNH:Ento. If someone wants to curate an insect classification - that would be fabulous, but I don't see anyone stepping up.....

**Comment by Jegelewicz** [comment]
Baby steps...

**Comment by lin-fred** [comment]
I am ok with baby steps and setting up an insect classification. First, so it is ready if someone does want to do a bunch of updating to the insect taxonomy. Second, so that we are more ready for less garbage classifications (albeit small right now)

**Comment by Jegelewicz** [comment]
Closing until someone needs this.
