### ISSUE TITLE
Hangups in Firefox

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4671]
I wanted to register this in case anyone else is experiencing issues.  Beginning yesterday, I have had to use task manager to shut down Firefox several times as it hangs up doing something in Arctos. This has happened to me both in managing taxonomy and agents. I have also noticed some error messages that pop up and disappear faster than I can read them in both places. I will try to grab one if I can, but it really is a "blink of the eye" kinda speed. Not sure if this is something going on on my end, so checking here to see if anyone else has noticed this.

**Comment by Jegelewicz** [comment]
Also, just recently, about 90% of the time I log in after hitting the "log in" button nothing happens. Well, it looks like nothing happens, but if I close the log in pop up and refresh the tab in Arctos, I am logged in. I never see the "you have manage collection for....red box and it I hadn't played around, I would have just assumed I wasn't logged in.

**Comment by dustymc** [comment]
Yea that's TACC's network. They know about it, and they do seem to be changing stuff, but something's still dropping the ball from time to time.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I've been having issues with Chrome actually. When I go to arctos.database.museum it won't load, but if I go to any other link (for example https://arctos.database.museum/SpecimenSearch.cfm?guid_prefix=NMMNH%3APaleo) it will load. I'm not having this issue in Firefox. I also have the log in issue on both Chrome and Firefox.

**Comment by ewommack** [comment]
@Nicole-Ridgwell-NMMNHS I'll add to the weirdness. I'm working in Chrome and not having any issues.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/internal/issues/187
