### ISSUE TITLE
Getting error when trying to show all contents of barcode location in Object Tracking

### ISSUE THREAD

**Issue by atrox10** [ArctosDB/arctos#4674]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
When I go to Object tracking in Arctos (on MacBook - Chrome) and search on MVZ as barcode, and click on the [1143 VLSB] LN2 Tissue Facility, to see the entire contents of this freezer, it gives me an error. It's this error:
A query error occurred: ERROR: value ``20182020154391552415597`` is out of range for type integer.

Is there something we did wrong? Thank you!

**To Reproduce**
see above.

**Expected behavior**

**Screenshots**

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by atrox10** [comment]
here is a screenshot with the error

<img width="1231" alt="Screen Shot 2022-05-15 at 4 36 34 PM" src="https://user-images.githubusercontent.com/4494065/168499155-2e2f0bd4-c99e-48e2-87eb-00cb8227c78a.png">

**Comment by campmlc** [comment]
I'm getting the same thing when I try to double click to expand a position to the see the freezer box within.  But if I click the little edit box next to the position, I can get to the box and see the contents. This is happening with only some of the box positions within a freezer rack - others behave normally.

![Screenshot 2022-05-15 19 40 41](https://user-images.githubusercontent.com/14808196/168506011-0e213c8f-6456-4927-b923-ad45f1334035.png)
