### ISSUE TITLE
Report request - UAM:EH ledger report with media thumbnails 

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#4676]
I need to create my first report for a NAGPRA inventory, for the purpose of reporting to Alaska Native tribal councils. I have a loan created with an archived search of 496 catalog records. I'd like to develop a new report that mirrors what the search results spits out (including a thumbnail image of the object) but includes the following fields:

Media (first media file that pops up)
Catalog Number
Identification (Common Name)
Description
Specific Locality (place of origin)
Date of creation
Creator
Culture of origin
Collector
Remarks

Is this possible? If not I can just show the columns in the search results and print as a pdf, which is what I've been doing. Thanks for any suggestions. 

FWIW I did start the process of creating a report form - I've named it: UAM:EH_ObjectDetailReport

**Comment by dustymc** [comment]
I messed with your report a bit.

**Comment by mkoo** [comment]
HI @AJLinn what is the status of this report? I actually dont see this in the Reporter unless it was renamed.... let me know if it still needs attention

**Comment by mkoo** [comment]
OK I started a copy of your report with styling applied. I dont have a lot of cultural data cataloged but here's some paintings  to see the current version of the report
- do you want serif or sans serif font?
- Do you want some collection info at the top of the page?

Whatever you like, I will copy/paste that version into your regular report

**Comment by AJLinn** [comment]
Looking good so far! Here are some questions:

- Is there a way to do bounding boxes? I like bottom borders to show the bottom of each record just as a visual separator, or could be a full-grid pattern...
- Is it possible to change the way the records sort? Seems like it's not following the sort order from the search results page (do I have to edit the report for that? Sometimes I want is sorted by last part location, sometimes by GUID, sometimes by identified as, sometimes by creator, or specific locality...)
- Any way to get the column names to repeat by page? 

Thanks for working on this!

**Comment by dustymc** [comment]
@AJLinn is there any possibility that a fixed number of rows per page/fixed layout would work? I think I might be able to do that in cfml easier than it can be done in css, but maybe @mkoo has better magic now and it doesn't matter if you need dynamic sizing.

Yes, you'll need to modify the report to change the sort - from 

https://arctos.database.museum/Reports/reporter.cfm?action=edit&report_id=136



```
...
	    left outer join media_relations on flat.collection_object_id=media_relations.cataloged_item_id
	    left outer join media on media_relations.media_id=media.media_id
		Order by flat.guid
```

is ordering by guid, you can change that to anything in the select list, or comma-list those for multiple levels eg


```
...
	    left outer join media_relations on flat.collection_object_id=media_relations.cataloged_item_id
	    left outer join media on media_relations.media_id=media.media_id
		Order by flat.lastpartlocation,flat.scientific_name
```

would sort by part location then identification.

**Comment by mkoo** [comment]
@dustymc That was the first thing I tried to add ```Order by flat.guid``` but still not working?!
![Firefox_Screenshot_2023-12-11T19-21-28 194Z](https://github.com/ArctosDB/arctos/assets/2523089/6cd670b6-0d5c-4328-a70d-2d7a9369b4c3)

What am doing wrong? do I need group by? I'll try that....

Also, Angie will look at your formatting requests

**Comment by mkoo** [comment]
ok nevermind-- for future reference the ```order by guid``` needs to go after the uniques are listed out so after the extensive group by list, put 'order by guid' or whatever order is desired.

@AJLinn if I add back in the borders on the rows, shall I remove the alternating shading on the rows? Might be too busy wtih both. 

As for the repeating column headers, I am struggling with the paging library we are using since I need the code to "know" when there is a new page. For now, easiest way is what Dusty suggests which is limit each page to a specific number of rows. But that is not ideal since we want to accommodate lots of different amounts of description. Anyway we might need an interim solution of fixed rows per page for now. What would be a 'safe' row limit per page?

**Comment by AJLinn** [comment]
@mkoo got me a good, workable template that I can use for most purposes! Thank you!
