### ISSUE TITLE
Find Container Contents csv download error

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4681]
Still needing to be able to download the contents of a freezer. I tried two things from Find Container for barcode DGR12749:
1) See All Collection Contents - this worked! 28,000 objects displayed. But no csv download on this tool - can we add that, please?

2) Container Contents and csv only option:  Got the following error messages trying this route:
[container_contents csv error.pdf](https://github.com/ArctosDB/arctos/files/8708458/container_contents.csv.error.pdf)
[container_contents error.pdf](https://github.com/ArctosDB/arctos/files/8708459/container_contents.error.pdf)

**Comment by dustymc** [comment]
You're using up all available memory, and there's nothing I can do about it. TACC is working on something that might lead to a solution, but I'm not sure of that (It'll have some sort of limitation) and it's not imminent.

It would work if there was less stuff on the form, but we seem to be going in the opposite solution.

I can only suggest you download parts and pieces instead of all at once.

**Comment by campmlc** [comment]
Can I request a SQL query and an emailed csv then? This is critical functionality that we have lost with the migration from Oracle. There are 396 freezer boxes per freezer - downloading them one at a time and consolidating files is not an option.

**Comment by campmlc** [comment]
What about option 1? Can I get a csv download from the displayed results? The data were there in my browser - I just had no way to download them from that tool.

**Comment by dustymc** [comment]
>csv

[temp_DGR12749.csv.zip](https://github.com/ArctosDB/arctos/files/8717033/temp_DGR12749.csv.zip)

>What about option 1?

You know that's different data, right? And I don't think it is loading to your browser - I certainly can't make it work - but I can add a CSV option. You might also try something like https://addons.mozilla.org/en-US/firefox/addon/download-table-as-csv/.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/1747
