### ISSUE TITLE
 disposition cleanup: observation

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4684]
Ref: https://github.com/ArctosDB/arctos/issues/2667

Problem: I have no idea what we're trying to do here, and I don't think anyone else does either.

Proposed solution:
* update disposition="observation" to disposition="in collection"
* append "former disposition: observation" to part remarks

I will proceed with this if there are no objections by ~2022-06-17.

Users:

```
 guid_prefix  | count 
--------------+-------
 UAMObs:Mamm  |   193
 UAM:Herb     |   469
 UAM:Mamm     |     2
 UCM:Obs      |   150
 UAMObs:Ento  |     9
 UAM:Herp     |    24
 MVZObs:Herp  |     6
 MVZ:Herp     |     2
 MSBObs:Herp  |     2
 MSB:Para     |   610
 UCM:Egg      |     1
 MSBObs:Mamm  |     3
 DMNS:Bird    |     2
 DMNS:Mamm    |     1
 MSB:Host     |   442
 MLZObs:Fish  |  1394
 ASUMZ:Invert |     1
 UAM:Ento     |     1
 APSU:Herp    |   220
 UAMObs:Fish  |     3
```

Contacts:

 @ebraker
 @mkoo
 @campmlc
 @amgunderson
 @atrox10
 @dssikes
 @jtgiermakowski
 @gradyjt
 @acdoll
 @jldunnum
 @jrdemboski
 @msbparasites
 @mlbowser
 @bfluker
 @StefanieBond
 @jandreslopez
 @kyndallh

Data:

[temp_disp_cln_obs.csv.zip](https://github.com/ArctosDB/arctos/files/8711529/temp_disp_cln_obs.csv.zip)

**Comment by ebraker** [comment]
@dustymc I don't have a great solution, but since many observations are actually digitally or physically recorded and maintained, "in collection" could be appropriate for many of these records. I'd at least like to default all UCM to "in collection". Thanks!

**Comment by dustymc** [comment]
Proposal edited.

**Comment by mkoo** [comment]
Agree that disposition of 'in collection' makes more sense-- I just changed
MVZ:Herp and MVZObs records. They refer to media that are 'in collection'
(ie in our control even it's 'in cloud')
this reminds me to get URls for these!
