### ISSUE TITLE
disposition cleanup: recataloged

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4686]
Ref: https://github.com/ArctosDB/arctos/issues/2667

Problem: value makes no sense.

Proposed solution:

* update disposition="recataloged" to disposition="not applicable"
* append "former disposition: recataloged" to part remarks

I will proceed with this if there are no objections by ~2022-06-17.

Users:

```
 guid_prefix | count 
-------------+-------
 MVZ:Mamm    |     3
 DMNS:Bird   |     2
 DMNS:Mamm   |     5
 CHAS:Inv    |     4
 UMZM:Mamm   |     1
 DMNS:Inv    |     4
 UMZM:Bird   |     2
 MSB:Para    |   110

```

Contacts:

 @msbparasites
 @mkoo
 @campmlc
 @sharpphyl
 @cjconroy
 @wellerjes
 @adhornsby
 @droberts49
 @acdoll
 @crcarter00
 @jrdemboski

Data:

[temp_disp_cln_recat.csv.zip](https://github.com/ArctosDB/arctos/files/8711607/temp_disp_cln_recat.csv.zip)

**Comment by sharpphyl** [comment]
We can live without "recatalogued" but they are not "transfer of custody."  These are lots that were consolidated into a different catalog number.  We can manually adjust the disposition of the record if we go forward with the change.

**Comment by mkoo** [comment]
I'm ok with the original proposal from @dustymc

**Comment by dustymc** [comment]
Done. Fresh data:

[temp_disp_cln_recat(1).csv.zip](https://github.com/ArctosDB/arctos/files/9135413/temp_disp_cln_recat.1.csv.zip)
