### ISSUE TITLE
disposition cleanup: subsampled

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4688]
Ref: https://github.com/ArctosDB/arctos/issues/2667

Problem: Value makes no sense.

Proposed solution:

* update disposition="subsampled" to disposition="in collection"
* append "former disposition: subsampled" to part remarks

I will proceed with this if there are no objections by ~2022-06-17.

Users:

```

-------------+-------
 UCM:Mamm    |     8
 ASNHC:Mamm  |     8
 DMNS:Bird   |     3
 DMNS:Para   |     1
 UAM:Fish    |    35
 UAM:Herb    |     2
 UTEP:Bird   |     1
 DMNS:Mamm   |  1303
 MSB:Mamm    |     3
 UWBM:Mamm   |     3
 UAMObs:Ento |     2
 UNCG:Para   |     4
 MSB:Herp    |     2
 UAM:ES      |     1
 MSB:Host    |    18
 UCM:Bird    |     1
 BYU:Herp    |     5
 UMNH:Mamm   |    31
 MSB:Bird    |     3
 UAM:Ento    |     4
 UCM:Herp    |     4
 UTEP:ES     |     7
 MVZ:Bird    |    41
 MSB:Para    |    25
```
Contacts:

 @ebraker
 @bryansmclean
 @mkoo
 @campmlc
 @ccicero
 @dssikes
 @mvzhuang
 @jtgiermakowski
 @jebrad
 @AdrienneRaniszewski
 @acdoll
 @jldunnum
 @jrdemboski
 @byuherpetology
 @msbparasites
 @mlbowser
 @kderieg322079
 @StefanieBond
 @catherpes,@catherpes
 @SerinaBrady

Data:

[temp_disp_cln_ss.csv.zip](https://github.com/ArctosDB/arctos/files/8711644/temp_disp_cln_ss.csv.zip)

**Comment by dustymc** [comment]
>add a subsample part to all of these

Some/most of them are derivatives.
```
             part_name              | has_parent 
------------------------------------+------------
 skeleton                           | yes
 whole organism                     | no
 heart, kidney, liver, spleen       | yes
 tissue                             | no
 heart, liver                       | yes
 heart, liver, muscle               | yes
 skin clip                          | no
 liver                              | yes
 heart                              | no
 kidney                             | yes
 fin                                | yes
 tissue                             | yes
 skin, study                        | yes
 skeleton                           | no
 feces                              | yes
 whole organism                     | yes
 unknown                            | yes
 radius                             | no
 skin, study                        | no
 heart                              | yes
 stomach                            | no
 heart, kidney, muscle              | yes
 toe                                | yes
 tooth                              | yes
 heart, kidney                      | yes
 carcass                            | yes
 tibia                              | yes
 skin                               | yes
 radius                             | yes
 kidney, muscle                     | yes
 skull                              | yes
 spleen                             | no
 heart, spleen                      | yes
 heart, kidney, liver, lung, spleen | yes
 heart, kidney, liver               | yes
 dentary                            | yes
 heart, kidney, liver, muscle       | yes
 observation                        | no
 liver                              | no
 mandible                           | yes
 kidney, liver                      | yes
 skull                              | no
 lung                               | yes
 femur                              | no
 metacarpal                         | yes
 muscle                             | yes
```

**Comment by dustymc** [comment]
>"subsampled" status helps clarify what is going on

I don't think so - disposition should tell me where the thing is, that does not. WHAT the thing is - I think the intent - belongs - well, not there!

We can do WHATEVER with the UI, I'm always up for clever ideas. 

Unrelated(ish), we should strive to banish the word "subsample." That's only one use case, any part can have a parent, there are lots of reasons to track derived parts beyond taking a small piece from a (probably piece of) liver.

**Comment by dustymc** [comment]
>maybe that should be part location

Poor choice of words on my part - "can I get my hands on it?" or something might have been better - but yea, I've always thought that disposition would be a distraction and nothing else to anyone who REALLY uses machine-readable labels. If you know precisely where everything is and have good loan records and such you can probably derive the why (and whatever else disposition is supposed to do).

 If humans are reading labels or typing, disposition seems complementary; I'd never fully trust eg part attribute location.

> and, as an abstract generality, the status of cataloged items.

That's several years out of date; those data are still there, but they're all 'not applicable' and never exposed.

>people are planning to get different information from this field,

Yes, that's the issue! I don't think I actually much care what's in disposition, but it is influencing how we see other things and that leads to impenetrable data. _E.g._, disposition is apparently seen as a "backup alternative" to transactions, which just PAINS me. (But, if the transaction really just isn't possible - which seems to happen - then maybe disposition is as good as anything that's avaialble.) 

>"subsampled" definitely seems like a "status"....people are planning to get different information

Maybe, but that's a structural characteristic of the same thing disposition is hooked onto; something **designed** to perform that job is RIGHT THERE. Maybe we need 'subsampled' to differentiate some other kind of parent-child relationship or something, but disposition (or my view of it) can't make sense for that either - things that are subsampled can still be lost, loaned, in collection, etc., and every part has exactly one disposition.

ANYWAY - agreed, we need better documentation, it seems on what disposition is, what it isn't, and maybe what it can approximate in desperate situations.

**Comment by Jegelewicz** [comment]
Woke up this morning thinking that "subsampled" is a CONDITION.....

**Comment by dustymc** [comment]
I'll consider this discussion an objection; adding to AWG Agenda.

**Comment by campmlc** [comment]
In the whole organism case, I'd advise indicating in the subsample part
name what was actually taken - skin? a piece of liver? But for that, again,
we need a way to select a different part name than the parent in the loan
form.

**Comment by Jegelewicz** [comment]
This needs a focused discussion with pre-approval by some group of people - I don't think that laying this down in the AWG will get us any resolution?

**Comment by dustymc** [comment]
The funky data is almost certainly attracting more funky data, and we're coming up on two years of stalemate. I'm clearly unable to resolve this. If the AWG can't help, then who can? Is there just no resolution when someone or some group can't or won't find or accept a solution? That doesn't seem in any way sustainable.

I'm re-adding to the agenda in the hopes that the AWG can suggest SOMETHING, even if they can't or won't address the specifics.

**Comment by Jegelewicz** [comment]
ASNHC:Mamm records changed to transfer of custody and preparation method other with subsampled data in the method added.

**Comment by Jegelewicz** [comment]
UTEP:Bird - changed to in collection, added a child part with disposition transfer of custody and preparation method other and subsample remark in method.

**Comment by Jegelewicz** [comment]
UTEP:ES all were samples loaned out changed to used up (which was their condition) and changed condition to sample.

**Comment by Jegelewicz** [comment]
UWBM:Mamm - changed to transfer of custody with subsample in condition - all were subsamples taken for loans.

**Comment by Jegelewicz** [comment]
From my work above, this probably doesn't make sense

> update disposition="subsampled" to disposition="in collection"

My guess is that most of these either are a child part that should have a disposition of transfer of custody or used up OR they need a child part added. In the case of some of the above, I changed the child part type because it made sense to do that (UWBM child parts were hair not skin). 

I'd be happy to work on the other things if given permission by the collections.

**Comment by dustymc** [comment]
Thanks @Jegelewicz here's new data:

```
 guid_prefix | count 
-------------+-------
 MSB:Mamm    |     3
 MVZ:Bird    |    41
 MSB:Para    |    24
 UAM:ES      |     1
 UNCG:Para   |     4
 DMNS:Bird   |     1
 MSB:Host    |    17
 DMNS:Mamm   |  1375
 MLZ:Bird    |     3
 UAM:Ento    |     4
 DMNS:Para   |    14
 UCM:Bird    |     1
 BYU:Herp    |     5
 UMNH:Mamm   |    30
 MSB:Herp    |    10
 UAM:Fish    |    35
 MSB:Bird    |     3
 MVZ:Mamm    |    18
 UCM:Herp    |     6
 UAM:Herb    |     2
 MMNH:Bird   |     6
 UNCG:Mamm   |    20
 UAMObs:Ento |     2
 UCM:Mamm    |    13
```

 @ebraker
 @bryansmclean
 @mkoo
 @campmlc
 @ccicero
 @barke042
 @camwebb/
 @DerekSikes
 @cjconroy
 @jtgiermakowski
 @AdrienneRaniszewski
 @acdoll
 @jldunnum
 @jrdemboski
 @ccwlobo
 @byuherpetology
 @msbparasites
 @mlbowser
 @kderieg322079
 @StefanieBond
 @catherpes
 @adhornsby

[temp_disp_cln_ss.csv.zip](https://github.com/ArctosDB/arctos/files/14349318/temp_disp_cln_ss.csv.zip)

**Comment by ebraker** [comment]
I would approve that anything "subsampled" gets a disposition of "used up". I can deal with the rare cases where a researcher actually sends us back any unused sample.

**Comment by campmlc** [comment]
Subsample also implies, but does not state explicitly, that the parent sample was handled in some way, potentially defrosted.

**Comment by acdoll** [comment]
I agree that 'subsampled' doesn't seem like the best option for disposition.
I'll need to look through these more closely, but I believe most of these tissue samples (liver, heart, etc) should be 'transfer of custody' or 'used up'. The 'whole organism' ones probably should have a different part name for these subsamples and then set to 'used up'. Then there are some without parent parts; I'll have to check on each of those individually. We'll get this cleaned up soon.

**Comment by acdoll** [comment]
I think I got all of ours fixed. @dustymc can you run this query once more and see if I missed any?

**Comment by dustymc** [comment]
```
 guid_prefix | count 
-------------+-------
 MVZ:Mamm    |    18
 MMNH:Bird   |     6
 UCM:Mamm    |    13
 DMNS:Para   |    12
 UAM:Fish    |    35
 UAM:Herb    |     2
 DMNS:Mamm   |     7
 MSB:Mamm    |     3
 UAMObs:Ento |     2
 UNCG:Para   |     4
 MSB:Herp    |    10
 UNCG:Mamm   |    20
 UAM:ES      |     1
 MSB:Host    |    17
 MLZ:Bird    |     3
 UCM:Bird    |     1
 UMNH:Mamm   |    30
 MSB:Bird    |     3
 UAM:Ento    |     4
 UCM:Herp    |     6
 MVZ:Bird    |    41
 MSB:Para    |    24
(22 rows)
```
[temp_disp_cln_ss(1).csv](https://github.com/ArctosDB/arctos/files/14466404/temp_disp_cln_ss.1.csv)

**Comment by msbparasites** [comment]
MSB:Para were all easy, subsampled to used up

**Comment by msbparasites** [comment]
MSB:Host changed from subsampled to in collection

**Comment by Jegelewicz** [comment]
These get cleaned up, then used again almost immediately - perhaps this should be an issue to resolve at AWG Issues this week?

**Comment by acdoll** [comment]
DMNS done.

**Comment by dustymc** [comment]
>then used again almost immediately

That is a long-standing problem and seems to have happened here, we need a better approach.


```
 guid_prefix | count 
-------------+-------
 MMNH:Bird   |     6
 UCM:Mamm    |    13
 UAM:Fish    |    35
 UAM:Herb    |     2
 MSB:Mamm    |     3
 UAMObs:Ento |     2
 UNCG:Para   |     4
 MSB:Herp    |    10
 UNCG:Mamm   |    20
 UAM:ES      |     1
 MSB:Host    |     1
 MLZ:Bird    |     3
 UCM:Bird    |     1
 UMNH:Mamm   |    30
 MSB:Bird    |     3
 UAM:Ento    |     4
 UCM:Herp    |     6
 MVZ:Bird    |    41
 MSB:Para    |     1
```

**Comment by adhornsby** [comment]
Bell MMNH cleaned up.

**Comment by jldunnum** [comment]
MSB:Mamm cleaned up

______________________________________________________________
Jonathan L. Dunnum Ph.D. (he, him, his)
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
Research Assistant Professor (LAT)
Department of Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

Chair, Systematic Collections Committee, American Society of Mammalogists
Latin American Fellowship Committee, ASM

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by megulbranson** [comment]
UAM:Fish cleaned up

**Comment by dustymc** [comment]
```
 guid_prefix | count 
-------------+-------
 UAM:Herb    |     2
 UAMObs:Ento |     2
 UNCG:Para   |     4
 MSB:Herp    |    10
 UNCG:Mamm   |    20
 UAM:ES      |     1
 MSB:Host    |     1
 MLZ:Bird    |     3
 UMNH:Mamm   |     1
 MSB:Bird    |     3
 UAM:Ento    |     4
 MVZ:Bird    |    41
 MSB:Para    |     1
```

**Comment by campmlc** [comment]
remaining MSB should be cleaned up.
@bryansmclean let me know if you need help with UNCG

**Comment by msbparasites** [comment]
I see that MSB Para and Host each have one record, but when I do a search I cannot find what records those are. I went again through the cvs file that was sent earlier. Maybe I did the search wrong?

**Comment by campmlc** [comment]
> I see that MSB Para and Host each have one record, but when I do a search I cannot find what records those are. I went again through the cvs file that was sent earlier. Maybe I did the search wrong?

@msbparasites my bad, I fixed all the remaining MSB ones this morning. I can get you the info.

**Comment by campmlc** [comment]
Looks like we lost the ability to search on "last edited by" and date?
@msbparasites here is the MSB:Para I edited: https://arctos.database.museum/guid/MSB:Para:30066
The host was a snail subsampled from a lot for DNA analysis. Could be changed to on loan.

**Comment by dustymc** [comment]
```
 guid_prefix | count 
-------------+-------
 UAM:Herb    |     2
 UAMObs:Ento |     2
 UNCG:Para   |     4
 UNCG:Mamm   |    20
 UAM:ES      |     1
 MLZ:Bird    |     3
 UAM:Ento    |     4
 MVZ:Bird    |    41

```

**Comment by Jegelewicz** [comment]
Change all to unchecked and put subsampled in remark. Drop a csv here and remove. And email everyone affected, explain the options and give them a list.

**Comment by dustymc** [comment]
```
 guid_prefix | count 
-------------+-------
 UAM:Herb    |     2
 UAMObs:Ento |     2
 UNCG:Para   |     4
 UNCG:Mamm   |    20
 UAM:ES      |     1
 MLZ:Bird    |     3
 UAM:Ento    |     4
```

**Comment by ccicero** [comment]
Yay, progress :)

**Comment by mkoo** [comment]
Please let me know when csv available and then I'll write the collection contacts
Thanks, MK

**Comment by dustymc** [comment]
@mkoo here's fresh CSV

[temp_disp_cln_ss(2).csv](https://github.com/ArctosDB/arctos/files/14539130/temp_disp_cln_ss.2.csv)

summary

```
 guid_prefix | count 
-------------+-------
 UAM:Herb    |     2
 UAMObs:Ento |     2
 UNCG:Para   |     4
 UNCG:Mamm   |    20
 UAM:ES      |     1
 MLZ:Bird    |     3
 UAM:Ento    |     4
```

contacts

 @bryansmclean
 @camwebb/
 @DerekSikes
 @mlbowser
 @StefanieBond

**Comment by mkoo** [comment]
thanks, I'm going to send an email but this list of contacts seems off given the collections:
instead of Bryan, I think John McCormack of MLZ needs to be on here!

**Comment by dustymc** [comment]
>list of contacts seems off 

Probably, I'm just pulling from collection contacts.

**Comment by mkoo** [comment]
done

**Comment by bryansmclean** [comment]
UNCG:Mamm records above are now transitioned manually over to "on loan". I have some work to do with the UNCG:Para records later today. The proposed changes sound good to me. Thanks for the update everyone.

**Comment by Jegelewicz** [comment]
I will repeat - can we just finish this off?

> Change all to unchecked and put subsampled in remark. Drop a csv here and remove. And email everyone affected, explain the options and give them a list.

**Comment by dustymc** [comment]
If The Community is going to push https://github.com/ArctosDB/arctos/issues/7605 through then I suggest we close this - I clearly have/had strange ideas about what 'disposition' means, this value might fit under the new definition.

**Comment by Jegelewicz** [comment]
At AWG today we decided to 

> Change all to unchecked and put subsampled in remark. Drop a csv here and remove. And email everyone affected, explain the options and give them a list..

**Comment by dustymc** [comment]
>might fit under the new definition

It does, not sure if we still need to proceed or not??

**Comment by Jegelewicz** [comment]
I still don't think this fits - this is a CONDITION of the part. Something has been physically done to it.

**Comment by dustymc** [comment]
>don't think this fits

I don't either, but that's no longer a consideration: disposition has been defined to be [curatorial](https://handbook.arctosdb.org/documentation/parts.html#disposition).

**Comment by dustymc** [comment]
latest:

```
;
 guid_prefix |      guid       | part_id  |   part_name    | sampled_from_obj_id 
-------------+-----------------+----------+----------------+---------------------
 ALMNH:Inv   | ALMNH:Inv:22050 | 29860142 | whole organism |                    
 ALMNH:Inv   | ALMNH:Inv:22051 | 29860146 | whole organism |                    
 ALMNH:Inv   | ALMNH:Inv:22052 | 29860143 | whole organism |                    
 ALMNH:Inv   | ALMNH:Inv:22053 | 29860144 | whole organism |                    
 ALMNH:Inv   | ALMNH:Inv:22054 | 29860154 | whole organism |                    
 ALMNH:Inv   | ALMNH:Inv:22055 | 29860151 | whole organism |                    
 ALMNH:Inv   | ALMNH:Inv:22062 | 29860145 | whole organism |                    
 ALMNH:Inv   | ALMNH:Inv:22226 | 29860102 | whole organism |                    
 UTEP:Herb   | UTEP:Herb:77913 | 32421480 | whole organism |            26821417
 MSB:Mamm    | MSB:Mamm:55859  | 32551596 | skin           |             1909156
 MSB:Mamm    | MSB:Mamm:160462 | 32551544 | skin           |             2826615
 MSB:Mamm    | MSB:Mamm:49893  | 32551545 | skin           |             1893928
 MSB:Mamm    | MSB:Mamm:49896  | 32551546 | skin           |             1893935
 BYU:Herp    | BYU:Herp:53294  | 32577887 | tissue         |            32577883
 BYU:Herp    | BYU:Herp:53296  | 32577888 | tissue         |            32577886
 BYU:Herp    | BYU:Herp:53892  | 32577889 | tissue         |            32577885
 BYU:Herp    | BYU:Herp:53893  | 32577890 | tissue         |            32577884
 MSB:Mamm    | MSB:Mamm:56116  |  2150039 | liver          |                    
 ALMNH:Inv   | ALMNH:Inv:23598 | 30744666 | whole organism |                    
 ALMNH:Inv   | ALMNH:Inv:23599 | 30744671 | whole organism |                    
 ALMNH:Inv   | ALMNH:Inv:23636 | 30809778 | whole organism |                    
 UAM:Ento    | UAM:Ento:377328 | 28118504 | tissue         |                    
 ALMNH:Inv   | ALMNH:Inv:22049 | 29860141 | whole organism |                    
 ALMNH:Inv   | ALMNH:Inv:21378 | 29879253 | whole organism |                    
 ALMNH:Inv   | ALMNH:Inv:21377 | 29879794 | whole organism |                    
 ALMNH:Inv   | ALMNH:Inv:21376 | 29880913 | whole organism |                    
 ALMNH:Inv   | ALMNH:Inv:21383 | 29880920 | whole organism |                    
 UNCG:Para   | UNCG:Para:116   | 29843432 | whole organism |                    
 UAM:ES      | UAM:ES:52768    | 30086465 | radius         |                    
 ALMNH:Inv   | ALMNH:Inv:24334 | 31579157 | whole organism |                    
(30 rows)
```

**Comment by dustymc** [comment]
Tabling pending resolution of https://github.com/ArctosDB/arctos/issues/8021
