### ISSUE TITLE
disposition cleanup: teaching collection

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4689]
Ref: https://github.com/ArctosDB/arctos/issues/2667

Problem: Value does not make sense.

Proposed solution:

* update disposition="teaching collection" to disposition="in collection"
* append "former disposition: teaching collection" to part remarks

I will proceed with this if there are no objections by ~2022-06-17.

Users:

```
 guid_prefix | count 
-------------+-------
 MVZ:Mamm    |     4
 UCM:Mamm    |     1
 NMMNH:Mamm  |    21
 DMNS:Bird   |     1
 ALMNH:Paleo |     1
 UTEP:Mamm   |   185
 UTEP:Bird   |    18
 DMNS:Mamm   |     9
 UTEP:Fish   |     4
 MSB:Mamm    |   533
 DMNS:Egg    |     2
 MSB:Fish    |     1
 BYU:Edu     |     3
 MSB:Bird    |    24
 UWBM:Herp   |     1
 UAM:EH      |   159
 UTEP:Teach  |   185
 DMNS:Inv    |    82
 UTEP:ES     |     4
 UMNH:Teach  |   402
 MVZ:Bird    |     4
```

Contacts:

 @ebraker
 @mkoo
 @AJLinn
 @campmlc
 @ccicero
 @mvzhuang
 @cjconroy
 @AdrienneRaniszewski
 @aklompma
 @acdoll
 @jldunnum
 @jrdemboski
 @kderieg322079
 @sharpphyl
 @catherpes,@catherpes
 @lin-fred
 @crcarter00

Data:

[temp_disp_cln_tc.csv.zip](https://github.com/ArctosDB/arctos/files/8711661/temp_disp_cln_tc.csv.zip)

**Comment by sharpphyl** [comment]
Teaching Collections makes sense to us.  

They are specimens without scientific data that are retained for use with the public as "Teach and Touch" specimens.  They are housed in a separate section of the collection area.  I would not like to lose the ability to easily track these separately from the main research collection.   We are in the middle of a project to database several hundred records with the disposition "Teaching Collection."

@acdoll  and @crcarter00 Your thoughts?

**Comment by catherpes** [comment]
Agreeed.

**Comment by mkoo** [comment]
@sharpphyl isnt there better ways to track these records? Seems like containers is the way to go here. You could make a container called "Teaching Collection" or a series of specific rooms, cases, etc then the part clearly has  a status of "in collection" with the location trackable, findable and editable within your museum. We too have a teaching collection or objects for teaching or otherwise but it's still "in collection" if it's cataloged.

As a disposition status, it does make sense to keep at a higher perspective unless "teaching collection" also denotes a specific legal or other status too.

**Comment by Jegelewicz** [comment]
At UTEP, we created a [teaching collection](https://arctos.database.museum/SpecimenSearch.cfm?guid_prefix=UTEP%3ATeach) and moved the stuff there.

**Comment by acdoll** [comment]
I tend to agree with @mkoo on this; create Teaching Collection as a container - which makes sense as it is all stored in a particular cabinet. The standard disposition would be 'in collection', which we could then change to 'on loan' or 'on exhibit', should the occasion arise, without losing track of the fact that it is part of the Teaching Collection. 
I would be open to creating a separate collection for this, but we should probably discuss that more thoroughly.

**Comment by Jegelewicz** [comment]
Either way works! I liked having the teaching collection separate as it made it easy for instructors and students to search and request stuff. Containers aren't visible to the public.

**Comment by sharpphyl** [comment]
> I tend to agree with @mkoo on this; create Teaching Collection as a container

@acdoll   I don't think it's worth creating a separate collection, but creating a container (similar to the wet collection) would be fine.

**Comment by ebraker** [comment]
UCM is all fixed.

**Comment by mkoo** [comment]
MVZ records are all cleaned up!

**Comment by dustymc** [comment]
I'll consider this discussion an objection; adding to AWG Agenda. Please let me know if I'm reading that wrong and I can continue with the proposed update/cleanup.

**Comment by dustymc** [comment]
[temp_disp_cln_tc(1).csv.zip](https://github.com/ArctosDB/arctos/files/9135573/temp_disp_cln_tc.1.csv.zip)
