### ISSUE TITLE
disposition cleanup: unchecked and unknown

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4690]
Ref: https://github.com/ArctosDB/arctos/issues/2667

Problem: We have a two ways of saying "I don't know."

Proposed solution:

* move these to 'being processed' 
 
or

* pick and define one

No data/collections/users here yet, because pretty much everyone uses these (and lots of them!).

Do we need a "we don't know" value, or is 'being processed' a sufficient replacement?

If we do need a "we don't know" value, we also need a definition.

**Comment by mkoo** [comment]
I think we need a "I dont know" value. I wont get all metaphysical on the nuances between "unchecked" and "unknown" so these could be merged into a single value (pick one, kids). We need to differentiate from "being processed" (which is a known pathway)

Definition = the location and condition of the object cannot be determined at this time and may be misplaced, lost, or missing form the collection. No known formal transaction can account for its disposition.

COMMENT AWAY!!!

**Comment by dustymc** [comment]
I'll merge all 'unknown' into 'unchecked' if nobody objects by 2022-08-15

**Comment by campmlc** [comment]
No objection.

**Comment by dustymc** [comment]
Done

[temp_disp_cln_unknown.csv.zip](https://github.com/ArctosDB/arctos/files/9352160/temp_disp_cln_unknown.csv.zip)
