### ISSUE TITLE
Feature Request - option to use geography spatial data in locality bulkloading.

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#4693]
**Is your feature request related to a problem? Please describe.**
When I individually create our localities, I can use "geography spatial data" to create polygons for our public, county-level only localities (see [workflow](https://github.com/ArctosDB/Arctos-Workflows/blob/main/.github/ISSUE_TEMPLATE/NMMNH_Single_Locality_Entry.md)). When bulkloading, this is not an option and I have to look up the point-radius data (see [workflow in-progress](https://github.com/ArctosDB/Arctos-Workflows/blob/main/.github/ISSUE_TEMPLATE/NMMNH_Locality_Bulkload.md)).

**Describe what you're trying to accomplish** 
The ability to use geography spatial data to create polygons when bulkloading the public versions of our localities.

**Describe alternatives you've considered**
Continue to use point-radius data when bulkloading, and either leave it that way or fix it by hand later.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> These only need to be created once - then give them names and just put the name in the bulkload?

I currently have a batch of 150 localities to load. Creating those 150 public localities individually would take a lot of time, hence bulkloading.

**Comment by Jegelewicz** [comment]
Check!

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> For this particular use case - you're just reusing the geography-level spatial data, correct? If so would a "use geography polygon [ yes | no ]" "field" do what's needed?

Yes
