### ISSUE TITLE
Need Help with Arctos Error - locality bulkload

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#4697]
# Error Text
ERROR_ID	E22FAC85-F9F6-4BE5-9BCC1F612AA69F44
ERROR_TYPE	application
ERROR_MESSAGE	Error invoking external process
ERROR_DETAIL	psql:/usr/local/webroot/temp/excopy_nicoleridgwell_20220519110518144_118.sql:1: ERROR: column "utm_zone" of relation "cf_temp_locality" does not exist

# Where it happened
locality bulkload tool
https://arctos.database.museum/tools/bulkloadLocality.cfm?action=ld

# Steps to get there
bulkloading locality data

Here is the data (I've deleted values in specific locality, utm ew, and utm ns because this is sensitive data):
[L-12717-12827 to share.xlsx](https://github.com/ArctosDB/arctos/files/8732378/L-12717-12827.to.share.xlsx)

**Comment by dustymc** [comment]
I'll get this with next release, maybe tonight/probably tomorrow.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks!
