### ISSUE TITLE
Code Table Request - New attribute: exhibition history

### ISSUE THREAD

**Issue by krgomez** [ArctosDB/arctos#4698]
**Goal**
[ Describe what you're trying to accomplish. ]
I would like to propose the creation of a new attribute called “exhibition history.” While loans can track and document exhibitions after a work has been acquired, they can’t document exhibitions that a work was included in prior to acquisition. Exhibition history is important contextual information that should be made available to the public.

**Context**
[ Describe why this new value is necessary and existing values are not. ]
We can continue to use catalog record remarks, but because this is a catch-all field where we store various pieces of information that don’t fit elsewhere in the catalog record or which are considered internal curatorial notes, we do not make this field publicly visible.

**Table**
[ Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table you are requesting changes to here. ]
New catalog record attribute

**Proposed Value**
[ Proposed new value ]
Exhibition History

**Proposed Definition**
[ Clear, complete, non-collection-type-specific definition of the new value. ]
From CDWA: A historical record of the public display of a work, including its installation in a gallery, inclusion in a special or online exhibition, and any loan during which the work was on public view, even if not a part of a formal exhibition.

**Collection type**
[ If the code table includes a "Collection" column. Ex: Mamm, Herp, ES ]
Art

**Attribute data type**
[ "Attributes" may apply to catalog records, parts, localities, and collecting events. You must specify a datatype (free-text, categorical, or number+units) if this request involves attributes. ]
Free text

**Available for Public View**
[  **Yes | No** to indicate whether the proposed value will be available for public view or available only for logged in operators.  ]
Yes

**Priority**
[  Please choose a priority-label to the right.  ]
Normal

**Comment by Jegelewicz** [comment]
@ArctosDB/arctos-code-table-administrators any objections?

**Comment by AJLinn** [comment]
I love it - I usually track this by remarks or through loans (if I managed to remember to make one!) but it’s an imperfect way of doing it and would love a more standardized way to get at the info.

**Comment by krgomez** [comment]
Recording exhibitions as loans works great, especially if there is also a project associated, as this is offers a public viewing option. Is there a way to create a type of transaction that would be appropriate for an exhibition that occurred prior to acquisition (not a loan)? There are artworks in the collection by different artists that were part of the same exhibitions in Alaska prior to when they were acquired, and so connecting those works together through a transaction/project could be interesting. In some cases works were purchased by the museum from such exhibitions. I just wonder if transactions would be the appropriate way of handling exhibitions the museum was in no way involved with?

**Comment by mkoo** [comment]
@krgomez is this primarily for tracking history prior to accessioning in your collection? I was thinking of something similar to indicate provenance or other historic usage prior to our accessioning of the object. It could go into ```description``` for us which I would add as a second description to keep separate from a purely descriptive entry. Is there room for that in what you are proposing as a new attribute? Or maybe you have something much more specific in mind.

**Comment by krgomez** [comment]
My understanding is that provenance technically includes ownership, exhibitions, and publications history, in that all of this is part of the whereabouts history of an item, but each of these areas of information are usually recorded separately. Provenance descriptions specifically include transfers of ownership. I assumed that ownership history would be best recorded in collection and use events? I suppose all provenance could be recorded together in a free-text descriptive field (though I would not want to use the description attribute, which I consider to be the physical description of the item, but maybe other collections use this field more generically), but it makes sense to record exhibition history separately. The CDWA categorizes [ownership/collecting history](https://www.getty.edu/research/publications/electronic_publications/cdwa/15ownership.html) and [exhibition/loan history](https://www.getty.edu/research/publications/electronic_publications/cdwa/20exhibition.html) separately. Here is a random example from the Cleveland Museum of Art (I love their online collections interface) just to show how they record provenance and exhibition history separately in their online records: https://www.clevelandart.org/art/1947.209, and here is one from the National Gallery of Art: https://www.nga.gov/collection/art-object-page.105596.html

**Comment by dustymc** [comment]
>I just wonder if transactions would be the appropriate way of handling exhibitions the museum was in no way involved with.

I'd say yes - that would result in one kind of data, rather than some transactions and some attributes with which it would be difficult to paint a comprehensive picture.

**Comment by Jegelewicz** [comment]
Ithink @dustymc is correct - it would be better to use loans for consistency. I'm happy to help work out a process for this! Maybe we need a new loan type (although I think we could give [legacy](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctloan_type#legacy) a better definition and use it....).

**Comment by AJLinn** [comment]
I agree with the use of loans (side note: maybe this can term can be changed to ‘usage transactions’ so we get out of the mindset of a loan only being something that we send out and get back) for pre-accession exhibition history. The loan number would correlate with the year the exhibition took place. Media (photos of the item in the exhibit; scans of a page in an exhibit catalog) could be linked to the loan record. Exhibit catalogs would be entered as publications and citations linked to the catalog record.

I love using Project for exhibits - as you say, it’s a great public tool and can pull seemingly disparate things together in really nice ways.

Ownership history should be listed as collectors, in the proper sequence chronologically. This history could be narratively described in the remarks for additional clarification or in the accession record if there’s only one item in the accession.

**Comment by dustymc** [comment]
>usage transactions

Thanks! (I've been using "loan-like transactions" for lack of better ideas....)

**Comment by krgomez** [comment]
That sounds like a great plan to me, Angie! I think once the term "loan" isn't in the picture, "usage transactions" make sense for these pre-accession exhibitions, especially for consistency with post-accession exhibitions and other actual loans like Dusty and Teresa mention.

**Comment by Jegelewicz** [comment]
> Ownership history should be listed as collectors, in the proper sequence chronologically. This history could be narratively described in the remarks for additional clarification or in the accession record if there’s only one item in the accession.

I think this speaks to the need for more details around "collectors"? As with identifiers, these probably need metadata (dates of "ownership", "caretaking"? maybe we are not talking about "collectors", but "curators"?) and could be a better solution for #4540

**Comment by krgomez** [comment]
Should I use "legacy" as the transaction type, or should a new type be added for pre-accession exhibitions? "Pre-accession transaction"? I used legacy for a number of loans that were not well documented in our previous database, and I think it would be helpful to distinguish those from the pre-accession exhibitions if possible.

**Comment by Jegelewicz** [comment]
> Does it need a new issue?

Yep - a new code table request.

**Comment by Jegelewicz** [comment]
I think we have resolved that transactions are a better path? Tentatively closing and expect to add new transaction type today...

**Comment by krgomez** [comment]
Yes, transactions/projects will work great for pre-accession exhibition history. 

I have a related question. For long-term loans that contains many items (such as one of our "permanent" exhibitions at the UA Museum), I am not sure of the best way to handle maintaining the exhibition history of an item that is removed from exhibition. 

If I remove the item from the loan, the loan disappears from the parts table and the item is dissociated from the project generated from the loan. This means that the unless I have documented that the item was included in this exhibition elsewhere, this history will be lost (at least in the catalog record). The alternative is to leave the item included in the loan and simply change the disposition to in collection after it is returned to storage. I don't like this option though, as then the list of items included in the loan is not current. I would make a note in the loan remarks that the item was removed from exhibition so that the history is documented there, but this wouldn't be directly linked to the catalog record or show up there.

I hope this makes sense. Any thoughts on what others do with this sort of situation?

**Comment by dustymc** [comment]
Lots of various "traditional" use is complicated/impossible to adequately track because of arbitrary administrative things. Just take a slightly different not-so-arbitrary administrative path: make more smaller loans.

An item that's been on loan should never be removed for lots of reasons.

**Comment by krgomez** [comment]
Okay that makes sense, thanks! I'll figure out a way to handle this with multiple smaller loans.

**Comment by Jegelewicz** [comment]
> then the list of items included in the loan is not current. 

Yes it is! The list of items in the loan with the disposition "on exhibit" is the "current" exhibition?

**Comment by krgomez** [comment]
Changing the disposition is the way I have been handling it, as opposed to removing the item from the loan. But then the loan still shows as open next to the part, and the item is still included in the list of catalog records for the loan, neither of which seem like a big deal when we know why that's the case. How would you deal with a permanent exhibition loan that includes many items (one of these exhibits has 165 art items...), some of which may come off exhibit from time to time? Would you have one loan and simply change the disposition for items that come off exhibit, making note of the removal in the loan remarks? Or would you have individual loans for each item and link them together with a project for the permanent exhibition? Some other method?

**Comment by AJLinn** [comment]
I just change the disposition to "in collection" but keep it in the overall loan. Make notes in the Loan remarks field about wheen a particular item was removed.
Also when you update the part attribute location, you can make a note in the remarks to say "removed from exhibit, see Loan xxx".

**Comment by Jegelewicz** [comment]
A big huge NO to individual loans! What a pain!

**Comment by dustymc** [comment]
> What a pain!

The alternative is not properly documenting usage.
