### ISSUE TITLE
collection portal customization

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ArctosDB/arctos#470]
```
Anonymous users accessing Arctos through collection-specific portals 
(http://arctos.database.museum/msb_mamm) should get a customized form - add NK 
for MSB, AF for UAM, etc.
```

Original issue reported on code.google.com by `dust...@gmail.com` on 20 Dec 2010 at 7:22

**Comment by dustymc** [comment]
Do we want to build this sort of thing into Arctos proper (and can we afford the overhead if we do?) or should we provide a mechanism for users to build their own forms or ???
