### ISSUE TITLE
Feature Request - Show/Hide search terms for catalog record summary results

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#4700]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
I use catalog record summary searches a lot. Often times these searches require many search terms and for multiple searches I am usually only changing one term (eg the sciname). When I use the browser back navigation to the search form all my search terms are gone and need to be re-entered.

It would be very nice if the summary search had the same widget that the normal search has which allows one to show/hide search terms and re-query the same search or a slightly different search without having to start over at the search form page.

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.
medium

**Comment by Jegelewicz** [comment]
This seems like a really good idea and a very reasonable request!

**Comment by dustymc** [comment]
This should be a part of https://github.com/ArctosDB/arctos/issues/2745
