### ISSUE TITLE
Feature Request - Create new transaction : Deaccession

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#4701]
A new transaction is needed for documenting the processes and decision-making associated with the deaccessioning process. 

Form should have same fields and should function exactly like loans (e.g., adding parts, relating to projects, adding shipments, attaching media, etc.) as a starting point. Input from community about what additional fields would be useful.

For UAM:EH we use this form to justify our process to the acquisitions committee - might be useful to have some of the elements if they are usable for others. 
https://www.dropbox.com/s/4pcpvdcfl8hzjjg/DeaccessionForm_blank.pdf?dl=0

**Priority**
Medium

See #4189

**Comment by dustymc** [comment]
> should function exactly like loans

Unavoidable; it's the same structure.

Needs a definition which separates it fro everything else in https://arctos.database.museum/info/ctDocumentation.cfm?table=ctloan_type.

**Comment by Jegelewicz** [comment]
Weirdly though, I think it should hold essentially the same data as an accession?

deaccession - a transaction that documents the process by which accessioned materials are permanently removed from a collection

from https://dictionary.archivists.org/entry/deaccession.html
