### ISSUE TITLE
HG Authority Change for "no higher geography recorded"

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#4703]
**Goal**
For some of our Archives, we need a more generic Higher Geography option that may encompass more than one country, continent, or other high-level geography (like "somewhere on home planet")

**Context**
The current non-specific Higher Geography is "[no higher geography recorded](https://arctos.database.museum/editGeog.cfm?geog_auth_rec_id=69)" 
 It is used by over 112k records across almost all collections.

I propose two options:

1) Edit the current geog_auth_rec_id=69 to say ```no specific higher geography```, which will change the HG for +112k records which (at least for MVZ) are a lot of our legacy " no data" specimens and would be appropriate. I also see a lot of cultural collections so this may also work for them. But for the others? See next option...

2) Create a new geog_auth_rec of  ```no specific higher geography```. Not having the word "recorded" is key for the Archives since there is higher geography but at the record level I cannot narrow it down to just one. Against this option is having another HG entry that is potentially confusing to have two? Also it's not really a HG authority just a bit of a bin for those records you dont know what to do with, and now we would have two.

Either option would include adding remarks in the HG authority so we have a record of what we mean.

What do people favor? (I lean towards Option 1 but will not change it until I hear back from a ton of people/collections)

**Comment by dustymc** [comment]
>"somewhere on home planet"

https://arctos.database.museum/collection/UNM:MET exists, "Earth" seems like a suitable title for https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=69

I don't much like the word 'specific' in the context of ocean-sized things, but whatever.

I definitely don't like two ways of saying "IDK" but it's hard to see how this particular case of denormalization might come back to bite us.

**Comment by mkoo** [comment]
OK so maybe Option 1 should be edited to be "no administrative boundaries apply" 

(I tried variations of "planet Earth" and they all sounded cheesy in my head... I cannot channel my inner Captain Kirk this early in the day)

**Comment by dustymc** [comment]
>"no administrative boundaries apply"

They do sometimes "apply" eg https://arctos.database.museum/guid/UMZM:Mamm:6060 seems to be entirely within admin boundaries ("Asia" at worst), it's just not been applied/recorded for whatever reason. Maybe that's semantic minutia, just trying to somehow avoid making anything even less clear.

**Comment by mkoo** [comment]
>>>They do sometimes "apply" eg https://arctos.database.museum/guid/UMZM:Mamm:6060 

That's clean-up!  Many of the 112k records I took a look at have coordinates and thus we could apply a HG via reverse lookup services (in fact your tool does that already). So DQ can be enhanced. 

That's different from a record with no georeference, no specific locality, no known  origin, but likely not from outer space.

**Comment by mkoo** [comment]
OK, returning to this to refresh the proposed options (suggestions integrated):

**Option 1:**   Edit the current geog_auth_rec_id=69 ("[no higher geography recorded](https://arctos.database.museum/editGeog.cfm?geog_auth_rec_id=69)") to say ```no administrative boundaries apply```, which will change the HG for +112k records which (at least for MVZ) are a lot of our legacy " no data" specimens and would be appropriate. I also see a lot of cultural collections so this may also work for them. But for the others? See next option...

**Option 2:**   Create a new geog_auth_rec of ```no administrative boundaries apply```. Maybe it's easier to do this and leave the mess in Option 1 alone, HOWEVER I dont like adding a new authority unless absolutely warranted. (Also is this vague nonspecific HG open for abuse?!)

Either way, looking into what specimens are using no HG, we should do some Arctos wide clean-up as many specimens seem to have coordinates and the reverse-HG lookup could be added (future issue).

Meanwhile: please let me know what people prefer/think. This is timely for MVZ Archive to continue batchloading records.

**Comment by dustymc** [comment]
I still don't like multiple flavors of any form of "somewhere on the planet," but there is a remarks field which could (sorta, maybe) disambiguate.

I'm not very fond of "no administrative boundaries apply" - they (sometimes? always?) do, we just don't know about them (maybe we would if we found time to look more), or for whatever reason have chosen not to record them (I've done that - my GPS knows where I am, I don't, anything I do might be seen to conflict with the primary GPS data). "Not recorded" seems to better cover the possibilities. Maybe that's all just semantics.

All that said, if I had my way I suppose I'd make "curatorially-asserted geography" much less prominent in the UIs, let anyone add anything (eg stop treating it like an authority or even as useful for discovery, because it's not), and treat the service-derived as "primary." https://github.com/ArctosDB/arctos/issues/3272

FYI:

```
select
    count(distinct(specimen_event.collection_object_id)) as numRec,
    count(distinct(specimen_event.specimen_event_id)) as numSE,
    count(distinct(collecting_event.collecting_event_id)) as numEvents,
    count(distinct(locality.locality_id)) as numLocs
from
    specimen_event
    inner join collecting_event on specimen_event.collecting_event_id=collecting_event.collecting_event_id
    inner join locality on collecting_event.locality_id=locality.locality_id
where locality.geog_auth_rec_id=69


 numrec | numse  | numevents | numlocs 
--------+--------+-----------+---------
 104219 | 112142 |     10405 |    1772
```

**Comment by mkoo** [comment]
>>I still don't like multiple flavors of any form of "somewhere on the planet," but there is a remarks field which could (sorta, maybe) disambiguate.

I agree. That's why I propose to alter what we have

>>I'm not very fond of "no administrative boundaries apply" - they (sometimes? always?) do, we just don't know about them (maybe we would if we found time to look more), or for whatever reason have chosen not to record them (I've done that - my GPS knows where I am, I don't, anything I do might be seen to conflict with the primary GPS data). "Not recorded" seems to better cover the possibilities. Maybe that's all just semantics.

I think I did not explain my situation well enough. These are for records which have explicit locations, they are _recorded_ but they span MANY HG's and I simply cannot use more than one per record. Here's an example: handwritten journal that covers trips to: 5 different CA counties, 2 counties in AZ, (ok you're thinking just use United States...), a site in Peru (ok use Western hemisphere...), and several places in Taiwan, Japan and the Philippines. So I would rather use "no administrative boundaries apply" or "no specific higher geography" which is more accurate and does not preclude their use in the case where it was not recorded.

So in this case, it's got nothing to do with geocoordinates but allowing cataloging to proceed.

**Comment by AJLinn** [comment]
> So I would rather use "no administrative boundaries apply" or "no specific higher geography" which is more accurate and does not preclude their use in the case where it was not recorded.

We used to just say “various”… but you guys probably won’t like that solution… 🫣 I don’t mind “no specific higher geography” as long as we have a good definition. I think it is more intuitive.

**Comment by ewommack** [comment]
I'd really love to figure this out more. I try and constrain by country at least, but for some of our historic specimens they're more large geographic area based. I've got on egg that has a locality of Arabia, and I'm guessing any where on that peninsula is a possibility.

**Comment by mkoo** [comment]
thanks for these examples!
So maybe we do need two versions of "IDK" These are the terms/ definitions for 1 current and 1 new HG authority: 


"no higher geography recorded"  = No record of any higher geography, typically associated with records with "no specific locality recorded".

"no specific higher geography" = Higher geography is not restricted to a single administrative boundary or is not deducible from the verbatim locality description.

Edits?

**Comment by dustymc** [comment]
>"no specific locality recorded"

https://handbook.arctosdb.org/documentation/locality.html#specific-locality

No specific locality recorded.

**Comment by Jegelewicz** [comment]
"no higher geography recorded" = No record of any higher geography, typically associated with records with "No specific locality recorded.".

"no specific higher geography" = Higher geography is not restricted to a single administrative boundary or is not deducible from the verbatim locality description.

**Comment by ewommack** [comment]
I can definitely see using both of those, but how should we preserve the information that we have for the "no specific higher geography"? In verbatim locality only?
Can we georeference them and just have an error around multiple country boundaries?

**Comment by Jegelewicz** [comment]
>  but how should we preserve the information that we have for the "no specific higher geography"? In verbatim locality only?

I would say yes - this would go in verbatim locality

> Can we georeference them and just have an error around multiple country boundaries?

Yep

**Comment by mkoo** [comment]
exactly what Teresa said-- if we go with this new authority, the records with the previous one of "no higher geography recorded" need no changes although after this discussion it's clear we certainly have clean up tasks.

If there are objections for a new HG authority for a entry called "no specific higher geography" with those above definitions, please say something  before next **Wednesday 6/1/2022*

Without further comments or objections, I will update and add definitions after that date. Thanks for all the feedback!

**Comment by mkoo** [comment]
@dustymc I'd like to complete this task so I can continue cataloging by adding the above proposed definitions and adding the proposed new HG; HOWEVER can you please make an exception for the URL authority? If need be, can we  add this as an URI authority? https://handbook.arctosdb.org/documentation/higher-geography.html

I am also going to update that page to add in these two new options for people dealing with records with no specific or several higher geographies.

**Comment by dustymc** [comment]
I can't easily do that, and authority is a discussion worth having anyway. (My vote is for has polygon==spiffy, doesn't==garbage...). You should be able to use https://en.wikipedia.org/wiki/Not_Otherwise_Specified (or whatever) - it'll probably complain but should let it through anyway.

**Comment by mkoo** [comment]
ugh that wikilink isnt really spatially relevant though!
Might as well as use : https://en.wikipedia.org/wiki/Earth

authority discussion is fine but a new issue BTW

**Comment by mkoo** [comment]
https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10016350
