### ISSUE TITLE
Arctos Down - 5/22/2022 8:37pm MDT

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4705]
Please complete to the best of your ability.

## Unplanned Outage
 - 5/22/2022 8:37pm MDT
 - 503 Service not availalble
 - I broke it by asking for csv download of objects in my freezer room. There has to be a better way.

## Planned Outage
 - Date and time outage will begin:
 - Date and time outage is expected to end:
 - Reason for outage:
 - Expected behavior during and after the outage:

## Communication before/during outage
- [ ] Pin this issue
- [ ] Banner updated @jegelewicz 
- [ ] Email sent to AWG 
- [ ] Email sent to Arctos Google Group 
- [x] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @jegelewicz
- [ ] Email sent to AWG 
- [ ] Email sent to Arctos Google Group 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by lin-fred** [comment]
It is also down for me

**Comment by dustymc** [comment]
bounced
