### ISSUE TITLE
Feature Request - flatten collection objects

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4707]
EDIT: Here's a migration path spreadsheet summarizing the conversation below: https://docs.google.com/spreadsheets/d/1jfCdsMV4e4dDU-G1guYbyLBqTfuPSNZB_1zjDXol8NU

dependencies are 

https://github.com/ArctosDB/arctos/issues/6297
https://github.com/ArctosDB/arctos/issues/6691

Original below

--------------------------

**Is your feature request related to a problem? Please describe.**

From https://github.com/ArctosDB/arctos/issues/4706, the join to coll_object is surprisingly slow and hard to tune

**Describe what you're trying to accomplish** 

 Go fast.

**Describe the solution you'd like**

There are now only two types of collection objects in Arctos, and I can't envision having more. They're very different shapes, and I don't think there's any real reason to normalize the core. (Both need to join to table coll_object, but not everything in there is appropriate to both.) I don't think there's any obvious drawback to flattening, and doing so should simplify the model and make things a bit faster. Specifically,

1. Move to table specimen_part fields
    * coll_object.entered_person_id (or not?)
    * coll_object.coll_object_entered_date (or not?)
    * coll_object.last_edited_person_id (or not?)
    * coll_object.last_edit_date (or not?)
    * coll_object.coll_obj_disposition
    * coll_object.lot_count
    * coll_object.condition
    * coll_object.flags
    * coll_object_remark.disposition_remarks
    * coll_object_remark.coll_object_remarks
 2. Move to table cataloged_item fields:
    * coll_object.entered_person_id
    * coll_object.coll_object_entered_date
    * coll_object.last_edited_person_id  (or not? Flat edit history is about the same thing with more info)
    *coll_object. last_edit_date  (or not? Flat edit history is about the same thing with more info)
    * coll_object_remark.coll_object_remarks

and rebuild everything to use that simplified structure

**Describe alternatives you've considered**

Keep on keeping on.

**Additional context**

1. This would be a good opportunity to think about names - eg specimen_part.collection_object_id-->specimen_part.part_id, coll_object_remarks-->cataloged_item_remarks and part_remarks, etc.
2. This would leave coll_object_remarks.associated_species needing a new home, but we've known about that for a long time.

**Priority**

Lowish, probably; might be higher if the potential performance impact was better understood.

**Comment by ewommack** [comment]
> specimen_part.collection_object_id

I think it would be a good idea to take out specimen from the name if we could.

**Comment by Jegelewicz** [comment]
coll_object.condition and #4987

@dustymc said to add this here so...

Let's work with condition in a similar method that we do preservation.

There is no more "condition" field

Everything currently there gets migrated to the condition report attribute.

When entering data, the "condition" field still exists, but like preservation, it ends up as an attribute with the date stamp and determiner of the Arctos user who entered it. (Want more precision, then use the actual condition report attribute).

All of the "condition" attributes are grouped together to help us review the condition history of any given part using the "Metadata" (but I'll need instruction on how to do this properly!).

What did I forget?

**Comment by AJLinn** [comment]
> There is no more "condition" field

> Everything currently there gets migrated to the condition report attribute.

Wait, what? Is that what's actually going to happen? Currently UAM:EH uses that field for an overall statement of the condition (Excellent, good, fair, poor) and then we do the detailed condition report as a part attribute. Is the plan to totally get rid of the condition field?

**Comment by Jegelewicz** [comment]
This is just a proposal. Clearly we will need to discuss and decide how best to do this.

**Comment by AJLinn** [comment]
If it gets rid of some of the columns in the parts table I'd be okay in getting rid of it though. We can change as long as the info in there gets migrated into a condition report part attribute. It would save me from having to write "not recorded" in every single media condition field!

**Comment by campmlc** [comment]
I like this idea in general - I think it could work, especially if @AJLinn can get what she needs!
@jldunnum

**Comment by dustymc** [comment]
I also like the idea in general - it's a simplification, one [less way to specify](https://github.com/ArctosDB/arctos/issues/4987#issuecomment-1231852417) condition.

>save me from having to write

Yes, this would allow for any number of assertions, and zero is still a number.

**Comment by Jegelewicz** [comment]
I'm guessing this should go to the AWG now.

**Comment by Jegelewicz** [comment]
AWG asks that we be able to create new condition attribute(s) from the loan form.

**Comment by Jegelewicz** [comment]
AWG asks that we be able to create new condition attribute(s) from the loan form.

**Comment by dustymc** [comment]
I still have questions before this can go next task.

FOR PARTS:

```
    coll_object.entered_person_id (or not?)
    coll_object.coll_object_entered_date (or not?)
    coll_object.last_edited_person_id (or not?)
    coll_object.last_edit_date (or not?)
```

Do we need to record entered and edited for parts? (My vote: Nope, I don't think anyone's ever asked for that, I think that can be moved completely to cataloged items.)

```
coll_object.flags
```

Actually can we just get rid of this? Maybe move whatever's there to https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#processing_history? If anyone wants something similar for parts they can request a new part attribute.

```
coll_object.coll_obj_disposition
coll_object.lot_count
coll_object_remark.coll_object_remarks 
```

Is there any reason to do anything new and different with these? (I don't see one.)

```
coll_object_remark.disposition_remarks
```

I think this hasn't been exposed and holds nothing of value, suggesting finding a place (https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecpart_attribute_type#location perhaps) for whatever's in there if anything is and dropping the concept.

```
coll_object_remark.coll_object_remarks
```

rename to 'part_remark' (unless someone has better ideas)


----------------------

FOR CATALOGED ITEMS

```
    coll_object.entered_person_id
    coll_object.coll_object_entered_date
    coll_object.last_edited_person_id (or not? Flat edit history is about the same thing with more info)
    *coll_object. last_edit_date (or not? Flat edit history is about the same thing with more info)
```

Do we still need that, do we need something different, ????



```
coll_object_remark.coll_object_remarks
```

rename to  - uhhh - help! cataloged_item_remark?? record_remark? item_remark?? 


---------------------

TODO

Figure out what's in condition history, make a lot of attributes or concatenate it with current condition into the one new attribute or ??? Need to pull data, then discuss.

(ditto disposition_remarks, see above)

---------------------


CLARIFICATION

>AWG asks that we be able to create new condition attribute(s) from the loan form.

I think it'll just be any new part attribute(s) - https://github.com/ArctosDB/arctos/issues/4987 should use https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecpart_attribute_type#tissue_quality and/or https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecpart_attribute_type#storage_temperature instead of the generic descriptive option, for example.

**Comment by Jegelewicz** [comment]
> FOR PARTS:
> 
>     coll_object.entered_person_id (or not?)
>     coll_object.coll_object_entered_date (or not?)
>     coll_object.last_edited_person_id (or not?)
>     coll_object.last_edit_date (or not?)
> 
> Do we need to record entered and edited for parts? (My vote: Nope, I don't think anyone's ever asked for that, I think that can be moved completely to cataloged items.)

HMMMM - I say we keep it because eventually someone is going to ask "who the heck added 500 parts to my collection and why?".

**Comment by Jegelewicz** [comment]
> coll_object.flags
> 
> Actually can we just get rid of this? Maybe move whatever's there to https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#processing_history? If anyone wants something similar for parts they can request a new part attribute.

What's in there now?

**Comment by Jegelewicz** [comment]
> coll_object.coll_obj_disposition
> coll_object.lot_count
> coll_object_remark.coll_object_remarks 
> 
> Is there any reason to do anything new and different with these? (I don't see one.)

Agree - these are fine as they are.

**Comment by Jegelewicz** [comment]
> coll_object_remark.disposition_remarks
> 
> I think this hasn't been exposed and holds nothing of value, suggesting finding a place (https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecpart_attribute_type#location perhaps) for whatever's in there if anything is and dropping the concept.

What is in there and how did it get there?

**Comment by dustymc** [comment]
>keep it because eventually 

It's a fair bit of data for which we pay in performance and storage. Definitely a cost we can pay if we must, but I'd prefer not to get too theoretical here. The flat edit history mentioned in the initial comment is more than capable of getting at someone adding 500 parts.

[flags](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctflags)

**Comment by Jegelewicz** [comment]
> coll_object_remark.coll_object_remarks
> 
> rename to 'part_remark' (unless someone has better ideas)

Yes, please. Do we actually have two things called  coll_object_remark.coll_object_remarks?

**Comment by Jegelewicz** [comment]
> FOR CATALOGED ITEMS
> 
>     coll_object.entered_person_id
>     coll_object.coll_object_entered_date
>     coll_object.last_edited_person_id (or not? Flat edit history is about the same thing with more info)
>     *coll_object. last_edit_date (or not? Flat edit history is about the same thing with more info)
> 
> Do we still need that, do we need something different, ????

So this stuff is about the ENTIRE record, correct? I am in favor of only looking at last edited in one way, so as long as everyone can figure out who edited stuff and when with flat edit history, then let's simplify?

**Comment by dustymc** [comment]
>Do we actually have two things called coll_object_remark.coll_object_remarks?

No, but it's not flat. (So there's one, or there's at least one, or there's as many as you need, depending on your perspective.)

> Should all the part stuff be renamed

That's what @ewommack suggested. It would add work, maybe quite a bit, but there will probably never be a better time.

**Comment by Jegelewicz** [comment]
> coll_object_remark.coll_object_remarks
> 
> rename to - uhhh - help! cataloged_item_remark?? record_remark? item_remark??

cataloged_item_remark seems fine and the broadest brush?

**Comment by Jegelewicz** [comment]
[flags](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctflags)

These are useful for knowing what needs to be done - maybe these should be put into a catalog record attribute? Maybe the attribute is "data flags" and the values are what is in the list, then one could have date and determiner be the date entered and Arctos username of the person entering - also offers the opportunity to add a remark? Can we make this happen from data entry?

**Comment by Jegelewicz** [comment]
> It's a fair bit of data for which we pay in performance and storage. Definitely a cost we can pay if we must, but I'd prefer not to get too theoretical here. The flat edit history mentioned in the initial comment is more than capable of getting at someone adding 500 parts.

Fair - and if nobody has asked for it so far, perhaps it is unnecessary? Others can weigh in.

**Comment by Jegelewicz** [comment]
>     Should all the part stuff be renamed
> 
> That's what @ewommack suggested. It would add work, maybe quite a bit, but there will probably never be a better time.

I like the idea of doing this now. It makes the back end more friendly to those of us who never go there and also seems simpler (collection_object vs part). In the grand scheme of things, it may not matter, but if we can change it now, I'd vote to change. That's just me though!

**Comment by campmlc** [comment]
I support making things better and clearer now if that's an option. . .

**Comment by campmlc** [comment]
Good idea

**Comment by Jegelewicz** [comment]
> I still think https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#processing_history maybe makes the most sense, but we can come up with something new that uses the code table if that's better.

I could see that. So just add the [current list](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctflags) to [ctprocessing_history](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctprocessing_history). When they are created, could we insert the date and entered by in date and determiner and also put "data entry flag" in method if nothing is provided?

**Comment by Jegelewicz** [comment]
I tried adding some definitions to the terms in [ctflags](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctflags) I don't know what some of them mean, and the combo ones would instead get two attributes if we do this. Also, I think these all might need something like "flag" after the term so that people know how to use them? For me, this is another case where using text in the "units" field would be great

attribute - processing history
attribute value - data entry flag
units - pick from [ctflags](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctflags)
method - free text, what led you to use the flag?
date - date attribute is added
determiner - person adding the attribute
remark - anything else that might help resolve this later

**Comment by campmlc** [comment]
I like this?
As a related isssue, any way to somehow incorporate container checks as
attributes as well? This is the third means of recording "condition" or
condition checks - it would be super useful to allow these to propagate as
attributes.

**Comment by dustymc** [comment]
The obstacles are gone, proceeding with this, there's important stuff in the first comment.

**Comment by dustymc** [comment]
AWG - no overwhelming support for doing anything clever with condition, move it straight across

**Comment by dustymc** [comment]
AWG: last edit isn't useful, cache and drop (and maybe we need a focus group to find some actually-useful 'edited').

**Comment by dustymc** [comment]
I am splitting loan_item.collection_object_id into loan_item.part_id and loan_item.cataloged_item_id. Everything involving loan items should be checked.

**Comment by dustymc** [comment]
Unless someone has immediate and compelling reasons not to, I think I'll rename some of the coll_obj.... things - starting with https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_obj_disp - while I'm rebuilding kinda everything anyway.

**Comment by campmlc** [comment]
Is this related to the Parts View/Download issue, where the view version shows Part Remark but the download version calls same content Collection Object Remarks?
Any clarification on these sounds like a good idea.

**Comment by dustymc** [comment]
Essentially everything - anything that touches involving parts, catalog records, or loans - has been revised in test (https://arctos-test.tacc.utexas.edu) and should be tested.

**Comment by Jegelewicz** [comment]
Whats the deal with the little box after the part name in a loan?

![image](https://github.com/ArctosDB/arctos/assets/5725767/b3c02f80-8e52-4b43-bb5a-55de20c9a23b)

https://arctos-test.tacc.utexas.edu/loanItemReview.cfm?transaction_id=21112061

**Comment by dustymc** [comment]
<img width="579" alt="Screenshot 2023-09-26 at 07 46 14" src="https://github.com/ArctosDB/arctos/assets/5720791/59f62899-e3df-44c5-8a00-a556ccdaf854">

**Comment by Jegelewicz** [comment]
fair - possible to put some standard thing when there are no attributes so it doesn't look weird?

"no attributes"

OR just leave it off if there are none?

**Comment by dustymc** [comment]
Definitely not from here...

"Looks weird" is a feature - it should be obvious when there are no attributes vs. when they're not shown in this format.

**Comment by dustymc** [comment]
Per https://github.com/ArctosDB/arctos/issues/4707#issuecomment-1710641485 here's last edit data for cataloged items:

[temp_last_edit_catitem.zip](https://github.com/ArctosDB/arctos/files/12835443/temp_last_edit_catitem.zip)

**Comment by dustymc** [comment]
Per https://github.com/ArctosDB/arctos/issues/4707#issuecomment-1710641485 here's last edit data for parts:

Err, nope, it's too big and won't attach, it's on my drive and the test VM, ping me ASAP if anyone wants a copy. @mkoo maybe you have a place for a 30MB file?

**Comment by Jegelewicz** [comment]
> place for a 30MB file

Upload it to TACC? Sounds weird, but isn't that what we have storage there for?

**Comment by dustymc** [comment]
>Upload it to TACC? 

I think it's all garbage (that's why we're unloading it!) and don't really want to put that in archival storage....

**Comment by dustymc** [comment]
disposition_remarks cache:

[temp_part_dispn_remark.zip](https://github.com/ArctosDB/arctos/files/12835475/temp_part_dispn_remark.zip)
