### ISSUE TITLE
Duplicate Lithostratigraphic Member values

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#4708]
**Goal**
During data entry I found several duplicate values in this code table, these should be merged.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlithostratigraphic_member

**Duplicate Values**
Paguate Sandstone Member
Paguate Tongue Member

Based on https://ngmdb.usgs.gov/Geolex/results?ageRange=-624%2C0&minage=holocene&maxage=archean&Unit=paguate and https://macrostrat.org/sift/#/strat_name/72688 I propose these be merged as "Paguate Tongue" and the old value moved to attribute remarks. All localities that use these attribute values are NMMNH localities except one: https://arctos.database.museum/place.cfm?action=detail&locality_id=10975342 which has two collecting events but no specimens.

Merged name: Paguate Tongue
New Definition: Sandstone unit of the Dakota Sandstone which outcrops in the San Juan basin of Colorado and New Mexico. [Geolex](https://ngmdb.usgs.gov/Geolex/Units/Paguate_9742.html)

Two Wells Sandstone Member
Twowells Tongue Member

The definition for "Two Wells Sandstone Member" is a link to https://pubs.usgs.gov/bul/1372j/report.pdf which actually names the unit as "Twowells Sandstone Tongue" and [Geolex](https://ngmdb.usgs.gov/Geolex/Units/Twowells_10695.html) calls it the "Twowells Tongue". I propose these be merged as Twowells Tongue and the old value moved to attribute remarks. All localities that use these attribute values are NMMNH localities except one: https://arctos.database.museum/place.cfm?action=detail&locality_id=10897902 which has one collecting event but no specimens.

Merged name: Twowells Tongue
New Definition: Sandstone unit of the Dakota Sandstone which outcrops in Arizona, Colorado, and New Mexico. [Geolex](https://ngmdb.usgs.gov/Geolex/Units/Twowells_10695.html)

Whitemore Point Member
Whitmore Point Member

This one is more straightforward. "Whitemore" is a misspelling, the definition is a link to https://en.wikipedia.org/wiki/Moenave_Formation, which correctly spells the unit as Whitmore Point. Only one locality (an NMMNH locality) uses Whitemore point. I can fix this and delete Whitemore point.

Updated definition for Whitmore Point Member: Unit of the Moenave Formation consisting primarily of lake deposits that outcrops on the Colorado Plateau of Arizona, Nevada, and Utah. [Macrostrat](https://macrostrat.org/sift/#/strat_name/74423)

**Comment by Jegelewicz** [comment]
@Nicole-Ridgwell-NMMNHS I'll check the "bad" ones and move everything out of them that I need to so they can be deleted. I expect I can work on this on Wednesday...

**Comment by Jegelewicz** [comment]
> Two Wells Sandstone Member
> Twowells Tongue Member
> 
> The definition for "Two Wells Sandstone Member" is a link to https://pubs.usgs.gov/bul/1372j/report.pdf which actually names the unit as "Twowells Sandstone Tongue" and [Geolex](https://ngmdb.usgs.gov/Geolex/Units/Twowells_10695.html) calls it the "Twowells Tongue". I propose these be merged as Twowells Tongue and the old value moved to attribute remarks. All localities that use these attribute values are NMMNH localities except one: https://arctos.database.museum/place.cfm?action=detail&locality_id=10897902 which has one collecting event but no specimens.
> 
> Merged name: Twowells Tongue
> New Definition: Sandstone unit of the Dakota Sandstone which outcrops in Arizona, Colorado, and New Mexico. [Geolex](https://ngmdb.usgs.gov/Geolex/Units/Twowells_10695.html)

This record https://arctos.database.museum/guid/UNM:Paleo:9028 is using [Twowells Tongue Member](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlithostratigraphic_member#twowells_tongue_member)

I changed the definition of Twowells Tongue Member to the suggestion above BUT should we remove "Member" from the term? It is standard in all the "member" terms and I just want to make sure we don't want to maybe create a new set of terms or to include things that aren't members in the "member" table?

**Comment by Jegelewicz** [comment]
https://arctos.database.museum/guid/UNM:Paleo:15757 is using Paguate Tongue Member

**Comment by Jegelewicz** [comment]
Need to create two new terms - move everything to them then get rid of old dupes.

**Comment by Jegelewicz** [comment]
@dustymc can you update locality attributes for me?

Current attribute | Change to 
 -- | -- 
Paguate Sandstone Member | Paguate Tongue 

I think I got the rest manually.

**Comment by Jegelewicz** [comment]
Paguate Tongue Member is gone

**Comment by Jegelewicz** [comment]
Twowells Tongue Member is gone

**Comment by Jegelewicz** [comment]
Paguate Sandstone Member and Two Wells Sandstone Member are gone. I think we are done!

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Whitemore Point Member is removed.

**Comment by Jegelewicz** [comment]
Thanks - I missed that one!
