### ISSUE TITLE
Autoload Extras - where did they go?

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#4710]
@dustymc Looks like several records that were entered and uploaded a couple weeks ago do not have their "extras" (in this case, parts and attributes).

These were entered by ganderegg but I quality checked the records in the browse and edit screen and can confirm they included attribute extras, and part extras. I selected "autoload_extras" to load them, but only the cores made it.  Several measurements and tissues are not present in the records. Known affected records:

https://arctos.database.museum/guid/UCM:Bird:16347
https://arctos.database.museum/guid/UCM:Bird:16348
https://arctos.database.museum/guid/UCM:Bird:16349
https://arctos.database.museum/guid/UCM:Bird:16350
https://arctos.database.museum/guid/UCM:Bird:16351
https://arctos.database.museum/guid/UCM:Mamm:23165
https://arctos.database.museum/guid/UCM:Mamm:23166
https://arctos.database.museum/guid/UCM:Mamm:23167

Any idea if these components are findable and can be attached to the records?

**Comment by dustymc** [comment]
Yep - and let me know if something doesn't work, you need help, whatever.
