### ISSUE TITLE
Data Entry - edit form - pull function

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4711]
I'm looking over some records in Browse and Edit that were entered by a student (ssibrava) and there are some strange gaps, e.g. verbatim locality doesn't show up in some of the columns, even though the event ID was pulled with the host data. It would be helpful if the data would also be visible for review before I approve to load.
Also, when I click on the key to edit and individual record, there is no pull function visible to the right of the IDs. We need this function in order to be able to pull in collecting event etc from related items. Can we get that added back in, please?
![Screenshot 2022-05-24 13 26 28](https://user-images.githubusercontent.com/14808196/170117099-2673c8fb-04f3-40ad-b7eb-265cfb5c767f.png)

**Comment by campmlc** [comment]
Priority: high, needed for loan processing

**Comment by dustymc** [comment]
You can check by putting the ID in a url like

**Comment by dustymc** [comment]
What's needed is pull from identifiers, not event/locality (but that may be desired too??). This is useful when a student doesn't  enter the correct ID, or enters correct ID but forgets to pull collectors-n-such.

Edit form also need some sort of distinguishing look and feel, something (well) beyond the blurb at the top and the (lack of) background.
