### ISSUE TITLE
Arctos Down - 2:41pm MDT 5-24-2022

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4712]
Please complete to the best of your ability.

## Unplanned Outage
 - 2:41pm MDT 5-24-2022
 - Describe the outage (Arctos down or only some part not working?): 503 error, Chrome and Firefox

## Planned Outage
 - Date and time outage will begin:
 - Date and time outage is expected to end:
 - Reason for outage:
 - Expected behavior during and after the outage:

## Communication before/during outage
- [ ] Pin this issue
- [ ] Banner updated @jegelewicz 
- [ ] Email sent to AWG 
- [ ] Email sent to Arctos Google Group 
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @jegelewicz
- [ ] Email sent to AWG 
- [ ] Email sent to Arctos Google Group 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by lin-fred** [comment]
Down for me too

**Comment by AJLinn** [comment]
Blergh... me three!

**Comment by dustymc** [comment]
I can't get to whatever's broken, sent email to TACC.

**Comment by lin-fred** [comment]
ok Ill send a tweet

**Comment by dustymc** [comment]
prod is back up, corral seems to not be, tentatively closing but the network does not seem stable (yet, I hope)....
