### ISSUE TITLE
Need container IDs for list of part IDs

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4713]
I need to request the container IDs that correspond to the following list of part IDs so that I can bulkload barcodes using the scary barcode bulkloader. I have a file of approx 180 samples that need barcodes loaded using this tool, and I downloaded the data from parts table download before the container ID was added. Now I have a paper file showing exactly which part IDs correspond to the new barcodes, but I have no way to associate them with container ID.

PART_ID,2143982,2143984,2143985,2143988,2143990,2143992,2143994,2143996,2143998,2144000,2144023,2144024,2144026,2144029,2144031,2144033,2144034,2144037,2144039,2144040,2144043,2144045,2144047,2144049,2144313,2144315,2144318,2144671,2144674,2144676,2144678,2144681,2144684,2144686,2144687,2144690,2144692,2144694,2144696,2144697,2144699,2144702,2144704,2144707,2144735,2144736,2145067,2145068,2189826,2189827,2189834,2189850,2189852,2189860,2189861,2189864,2189865,2189868,2189870,2189876,2189877,2190137,2190138,2190141,2190147,2190148,2190152,2190154,2190156,2190158,2190160,2190162,2190170,2190174,2190176,2190179,2190189,2190190,27238799,2190194,27237458,27237459,2190199,27248351,27248804,27233740,2190218,27243882,27233850,2190480,2190483,2190484,2190496,2190498,2190500,2190502,2190504,2190514,2190516,2190518,2190520,2190522,2190524,2190526,2190528,2190530,2190533,2190535,2190547,2190549,2190551,2190554,2190555,2190827,2190829,2190837,2190839,2190841,2190843,2190845,2190847,21814075,22469217,22968391,23025025,22814262,22813048,2204214,2204216,2204219,2204220,2204222,2204224,2204238,2204239,2204262,2204116,2204118,2204129,2204132,2204134,2204137,21718476,21718480,21720215,21718484,27256792,2204149,2204151,27239139,27239896,27226751,2204285,2204286,2204288,2204291,2204293,2204294,2204296,2204299,2204300,2204302,2204305,2204307,2204309,2204310,2204312,2204164,2204166,2204169,2204266,2204269,2204271,2204274,2204276,2204279,2204282,2204283

Priority: high - needed to complete data for a loan before it gets swamped by the next onslaught.

**Comment by dustymc** [comment]
[temp_crtiplkup.csv.zip](https://github.com/ArctosDB/arctos/files/8772059/temp_crtiplkup.csv.zip)

**Comment by campmlc** [comment]
Fantastic, thank you!!
