### ISSUE TITLE
FLAT Status 

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4714]
Please let me know what the info below means, and whether there is a chance my barcode swapper upload will happen sometime soon?
I have 176 records stuck pending load at https://arctos.database.museum/tools/containerBarcodeReplacer.cfm

<html>
<body>
<p style="color: rgb(0, 0, 0); font-family: Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">FILTERED_FLAT serves the same purpose to public users.</p>

Status | NumberRecords
-- | --
current | 4412325
error_in_processing | 902

<br class="Apple-interchange-newline">
</body>
</html>

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/4659
