### ISSUE TITLE
Feature Request - special handler for Agent Zero

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4715]
**Is your feature request related to a problem? Please describe.**

Agent unknown is overused, which results in the agent page burning a bunch of CPU and then choking. There's nothing informative about the data.

**Describe what you're trying to accomplish** 

Don't use up a ton of CPU for no reason.

**Describe the solution you'd like**

``if agent_id=0 then abort early``

**Describe alternatives you've considered**

* Don't use 'unknown' when there's nothing to say, or 
* Figure out a way to support a public page for an agent with millions of actions

**Priority**

High-ish; might be cause of some instability in certain circumstances.

**Comment by Jegelewicz** [comment]
> Don't use 'unknown' when there's nothing to say

I've been thinking about this from other directions recently. For collectors and preparators and other "collector" agents, I think forcing the use of unknown doesn't make sense because you can use the "verbatim colelctor" attribute (but that seriousl needs to be changed to verbatim agent with metadata...). I have also been thinking that we need to more "verbatim" things for people and that perhaps using those to then decide who really needs an agent page might be a better path.

For example - [see this comment](https://github.com/ArctosDB/data-migration/issues/845#issuecomment-1133143800) from an incoming geology collection:

> I started an "agents" list but realized the names of collectors on the NHSM mineral labels are inconsistent (not a surprise), with initials sometimes and names other times, or groups instead of individuals, and so on. I would need to make all of these consistent so they matched the "official" agent name, which is a bunch of work and ignores what's really on the label. Meanwhile, for all that work, I'm not sure we get much - I don't think we're going to search the data much to determine who found what.

Perhaps the best thing for incoming collections would be to ignore "official" agents and just use the "verbatim" attribute, then we can create some tools to help them add "official" agents to their data where it makes sense. This would allow us to make some better rules for "official" agents so that we don't have fifty John Smiths, all known to be individual people but the majority of whom only contributed one object or observation.

BUT we need "verbatim" anywhere agents are used - identifications, determiners for all kinds of attributes, participants in transactions (although I might argue that those should always be "official"). I am thinking that we change "verbatim collector" to "verbatim agent" and add "agent role" so that one can describe collector, preparator, determiner, etc. Does this seem like too much?

**Comment by dustymc** [comment]
>verbatim agent with metadata...

https://github.com/ArctosDB/arctos/issues/1492 - it's a string approach to things in table collector, not other agent-things. (So far, keep reading....)

>perhaps using those to then decide who really needs an agent page

https://github.com/ArctosDB/arctos/issues/4554 - yes, I think Agents need a higher bar. (And maybe that will eventually mean we do need 'verbatim attribute determiner' or something, but I think that's a leap we might usefully consider only after we've dealt with the most common situation, which is collectors of various roles.)

>best thing for incoming collections would be to ignore "official" agents and just use the "verbatim" attribute

Absolutely. There are tools, and those kinds of decisions are best made in the context of other data, including that in other collections.

>add "agent role" 

That's method.

>Does this seem like too much?

Yes, for now, I think so, see above, babysteps. Definitely worth keeping on the radar, but I think we should see how far we can go with collector-agents before we consider bigger nets.

**Comment by AJLinn** [comment]
> Don't use 'unknown' when there's nothing to say

For cultural collections, agent unknown vs leaving it out altogether is an important distinction whereby we are alerting our users that we have attempted to assess who a creator is, we do not have that information, and we would appreciate it if someone _does_ know the creator they could suggest it to us.

Leaving the agent creator blank, and thereby not even listing that there is a creator agent for an item reaffirms a bias against the intellectual property of Indigenous peoples who have been systematically ignored or erased for at least 200 years of museum operations. At least for UAM:EH, our protocol will be to continue to use agent unknown to publicly acknowledge that this is information we do not have and are actively seeking from anyone who might have it. I would encourage other cultural collections to consider this protocol as well.

**Comment by dustymc** [comment]
@AJLinn there's obviously something to say in that situation, but I'm not sure you're effectively saying it. Seems a bit like https://github.com/ArctosDB/arctos/issues/4703 in that the information lies somewhere between "we have no idea" and "that particular well-defined and discrete entity."

**Comment by Jegelewicz** [comment]
I just love how some people actually care about the 'who" and others couldn't be bothered!

> Leaving the agent creator blank, and thereby not even listing that there is a creator agent for an item reaffirms a bias against the intellectual property of Indigenous peoples who have been systematically ignored or erased for at least 200 years of museum operations. At least for UAM:EH, our protocol will be to continue to use agent unknown to publicly acknowledge that this is information we do not have and are actively seeking from anyone who might have it. I would encourage other cultural collections to consider this protocol as well.

This makes sense, but maybe isn't clear from our description?

> This is a no-agent record.

**Comment by AJLinn** [comment]
> @AJLinn there's obviously something to say in that situation, but I'm not sure you're effectively saying it. Seems a bit like https://github.com/ArctosDB/arctos/issues/4703 in that the information lies somewhere between "we have no idea" and "that particular well-defined and discrete entity."

There was a suggestion a few years ago to use "artist not known" on labels. Maybe we could make an agent with that as the designation?
https://www.nytimes.com/2011/02/06/arts/design/06names.html

**Comment by dustymc** [comment]
>"artist not known"

I was thinking that if you're worried about stepping on the toes of some group of people then you must know (or suspect) that someone with some attachment to that group was involved - you know more than "unknown" (however we spell it) but less than a person (entity, whatever). But, I think that (as least as it applies to cultures) is actually handled pretty well by https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#culture_of_origin, so nevermind....

**Comment by ewommack** [comment]
> "artist not known" on labels

I kind of like that idea, because then it wouldn't be confounded by all us funny natural history collections who may be using it more loosely than the cultural collections: "this a no-agent record" -> no name on the tag, no catalog, urrggh fine, you're unknown.

**Comment by Jegelewicz** [comment]
>     add "agent role"
> 
> That's method.

No it isn't? Method is how I decided this string is the "verbatim collector". Things like "transcribed from label" belong in method.

Table "collector" includes copyright holder, creator, preparator, and subject. If we are doing things right, it seems like we need the following:

verbatim copyright holder
verbatim creator
verbatim preparator
verbatim subject

I definitely have records that have this information for both collector and preparator and putting them both in "verbatim collector" is misleading.

If we don't want all those attributes, we need a way to say what role this "verbatim" attribute applies to and I don't think that fits in "method".
