### ISSUE TITLE
Bulkloader will not accept degrees in degrees decimal minutes format

### ISSUE THREAD

**Issue by catherpes** [ArctosDB/arctos#4716]
Any records that I have in this file are not going in if they have degrees decimal minutes. This is the most updated version of the file in Excel from which I generate the csv file to upload.

I thought maybe the field name for degrees had changed so I went back to the bulkloader builder. I cleared all checks in the whole builder and then clicked on DM.m Coordinates. Scrolled down to see what fields are checked an apart from the default Coordinate Metadata, only dec_lat_min and dec_long_min are checked. There needs to be a degrees latitude and longitude field for these records. 

Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Any records that I have in this file are not going in if they have degrees decimal minutes. This is the most updated version of the file in Excel from which I generate the csv file to upload. 

I thought maybe the field name for degrees had changed so I went back to the bulkloader builder. I cleared all checks in the whole builder and then clicked on DM.m Coordinates. Scrolled down to see what fields are checked and apart from the default Coordinate Metadata, only dec_lat_min and dec_long_min are checked. There needs to be a degrees latitude and longitude field for these records. 
Opening one of these records in the data entry screen, degrees does not show up in the form for either latitude or longitude.

From this I conclude Arctos is broken

**To Reproduce**
Steps to reproduce the behavior: See above.

**Expected behavior**

**Screenshots**

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] current version of Windows
 - Browser [e.g. chrome, safari] current version of Firefox

**Additional context**

**Priority**
High. I was hoping to get this bulkload done yesterday

[drawer bulkload6.csv](https://github.com/ArctosDB/arctos/files/8780679/drawer.bulkload6.csv)

**Comment by catherpes** [comment]
whoops. I actually attached the csv file. not the xlsx file.

**Comment by dustymc** [comment]
``degrees dec.   minutes`` needs

dec_lat_deg
dec_lat_min
dec_lat_dir     
dec_long_deg   
dec_long_min 
dec_long_dir


and the documentation probably needs updated.

**Comment by catherpes** [comment]
Thanks
I see them now a 5 pages (at 12.5 inches/page) /200 rows below the other lat/lon fields in the builder. Could they at least be moved up where we might see them with the rest of the lat/lon fields? I could have figured this out myself then.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/5193
