### ISSUE TITLE
Feature Request - Better user log in experience

### ISSUE THREAD

**Issue by catherpes** [ArctosDB/arctos#4717]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

**Describe what you're trying to accomplish** 
ease of use

**Describe the solution you'd like**
How might we accomplish your goals?

**Describe alternatives you've considered**
Issues to streamline logging in, and logging back in after I've been timed out.

1) When I click the Log In button in the top right corner, the dialog box opens in the middle of the browser.

-The cursor should be blinking in the 'Username' box so I don't have to click again to get in it.

2) When I log out, a dialog box opens in the middle of the browser. It has a link to continue to Arctos Home.

-There should also be a username and password fields so I don't have to click around to log back in (because usually when I log out, it's because I've timed out and need to log back in).

3) When I'm timed out, there is a notification next to the log out button that I have been timed out.

-There should be a way to log back in if you're timed out without losing my spot in Arctos. I know I can open a new tab, etc. but why not just have a username and password box  and log in button when the timeout notification displays? 

**Additional context**

**Priority**
This would streamline user experience. Without criteria for how to rate these suggestions, I don't know what to put here. I'm annoyed by this every time I log in or get timed out and I would rate it as moderately high.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/2893
