### ISSUE TITLE
Need Help with Arctos Error

### ISSUE THREAD

**Issue by catherpes** [ArctosDB/arctos#4718]
# Error Text
insert or update on table "specimen_event" violates foreign key constraint "fk_specimenevent_ctcollsource"

# Where it happened
Bulkloader after approving records to load
# Steps to get there
**Describe the actions that led to the error**

# Problem
**Community response to describe the problem that caused the error**

# Solution
**Community response with directions for how to correct the problem**
[drawer bulkload6.csv](https://github.com/ArctosDB/arctos/files/8781008/drawer.bulkload6.csv)

**Comment by dustymc** [comment]
collecting_source is constrained to https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcollecting_source

**Comment by Jegelewicz** [comment]
the vocabulary for collecting source was changed from wild caught to just wild.

**Comment by catherpes** [comment]
Thank you both.
But this does beg the question- why isn't this caught in the pre-bukload stage, the same time agent mismatches and taxonomy are caught? it's really frustrating to have a 2 step process in which the second step is much more cumbersome than the first - 30 minute delays if records need to be deleted. I prefer to work these in discrete batches and when some go in and some don't, I lose track of which records have disappeared and which still need more work.
