### ISSUE TITLE
Feature Request - better agent merge report

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4719]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
I can know that an agent was marked for merge, but I'd like to see who made the suggestion

**Describe what you're trying to accomplish** 
Confidence to merge requests

**Describe the solution you'd like**
Add the Arctos Agent name of the person who added the "bad duplicate of" relationship

**Describe alternatives you've considered**
click around and look at the agent marked as bad duplicate of to see who last edited it (which may not be the person who added the relationship if anyone else made edits after the relationship was added...)

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by Jegelewicz** [comment]
Also - adding the remark (if any) next to the relationship would be useful.

**Comment by dustymc** [comment]
<img width="1035" alt="Screen Shot 2022-05-26 at 10 57 00 AM" src="https://user-images.githubusercontent.com/5720791/170547499-39947d8d-64c4-4298-8b19-a07fbd53d7c5.png">

??

**Comment by Jegelewicz** [comment]
Can we just put those two things in the notification? Less clicking and scrolling if I can see them there. If it's too much processing, then OK.
