### ISSUE TITLE
Code Table Request - Add "ready to catalog" in accession status options

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#4721]
We currently have two options in the dropdown for accession status: in progress and complete. It would be very helpful to add an option for 'ready to catalog'. 

We at MVZ (and other collections) get a lot of salvage material that needs to be prepared. As the specimens get prepared, we add the prep # and specimen type (skin, skeleton, etc.) to the accession remarks, but there's no easy way now to search for accessions where all specimens have been prepared and they are ready to catalog. Sure, it's 'in process' but that's very vague and could mean lots of things - in freezer, being prepared, etc.

Definition: All specimens in an accession are ready for collection catalog numbers.

**Comment by dustymc** [comment]
No objections on the term from me - that seems well within the intent of the field.

The definition might be a bit too focused, but I don't have better ideas either.

**Comment by ewommack** [comment]
We use "ready to catalog" as well at the UWYMV. It is really helpful with students and volunteers who are cataloging so they can find accessions that they can catalog themselves. Having it in the Accn field would be another good way to keep track of that.

**Comment by ebraker** [comment]
Agreed, sounds really useful!

**Comment by ccicero** [comment]
Great all! Given everyone's travel schedules, I don't know when the next CT meeting will be. Do we want to want and discuss this, or can I go ahead and add it?

**Comment by Jegelewicz** [comment]
sounds like you can add this....

**Comment by ccicero** [comment]
Will do, thanks!

**Comment by ccicero** [comment]
and done!
