### ISSUE TITLE
trouble inviting operator

### ISSUE THREAD

**Issue by keg34** [ArctosDB/arctos#4724]
Hi all,

I am trying to invite a student as an operator for data entry.  I've sent the invite and she received the invitation email, but the operator authentication dialog is not appearing for her in her profile to accept the invitation.  Her login is achesnut.  Any help will be appreciated!  Thanks!

Kurt

# Error Text
**Copy the text from the page and paste it here**

# Where it happened
**Provide a link to or a description of the page where the error occurred.**

# Steps to get there
**Describe the actions that led to the error**

# Problem
**Community response to describe the problem that caused the error**

# Solution
**Community response with directions for how to correct the problem**

**Comment by Jegelewicz** [comment]
@dustymc I don't see any issues?

**Comment by keg34** [comment]
Thanks, Dusty!  We'll report back if there are more issues.

**Comment by campmlc** [comment]
Try having her go in to reset her password once she's logged in. It may
show up there. We need to update this process.
