### ISSUE TITLE
Individual media uploader not working

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#4731]
I wonder if this is connected to the security certificate, but the individual media uploader is not working.
I'm getting a timeout and this wonky error red box:
<img width="977" alt="Screen Shot 2022-06-01 at 11 17 52 AM" src="https://user-images.githubusercontent.com/17605945/171484695-de8b4880-4fc1-4dcf-88fa-7e539782b6ff.png">

Anyone else experiencing trouble with media? Or can anyone confirm it's related to the "not secure" status right now?

**Priority**
HIgh / Critical

**Comment by dustymc** [comment]
It seems to just be timing out, but I wouldn't be surprised if something I can't see is refusing to deal with lopsided encryption too. If you have "large" files (a threshold largely determined by your network) you can file a [storage request](https://github.com/ArctosDB/internal/issues/new?assignees=&labels=Digital+Media+Storage+Request&template=arctos-digital-media-storage-request.md&title=Arctos+Digital+Media+Storage+Request) which should accommodate files of any size.

**Comment by AJLinn** [comment]
>  If you have "large" files 

This was just a 162kb pdf... I don't know why it's timing out.

**Comment by dustymc** [comment]
Happy?
