### ISSUE TITLE
Code Table Request - New transaction type: pre-accession or historical

### ISSUE THREAD

**Issue by krgomez** [ArctosDB/arctos#4732]
**Goal**
[ Describe what you're trying to accomplish. ]
The goal is to create a new transaction type appropriate for documenting exhibitions that an item was included in prior to its accessioning into a collection. See #4698.

**Context**
[ Describe why this new value is necessary and existing values are not. ]
We considered creating a new free-text attribute called "exhibition history," however we record post-accession exhibitions as loan transactions, and so it was decided in #4698 that recording the pre-accession exhibitions as transactions would make the most sense for consistency. We discussed possibly using the "legacy" transaction type, however the definition and current use of this transaction type does not accurately capture the information we are trying to record. For clarity, it appears that a new transaction type is needed to record pre-accession exhibition history.

**Table**
[ Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table you are requesting changes to here. ]
loan_type

**Proposed Value**
[ Proposed new value ]
pre-accession, historical, or something else? See https://github.com/ArctosDB/arctos/issues/4698#issuecomment-1143948303

**Proposed Definition**
[ Clear, complete, non-collection-type-specific definition of the new value. ]
Transaction that involved a collection item prior to its accession, such as an exhibition.

**Collection type**
[ If the code table includes a "Collection" column. Ex: Mamm, Herp, ES ]
Art, EH, others?

**Priority**
[  Please choose a priority-label to the right.  ]
Normal

**Comment by Jegelewicz** [comment]
pre-accession transaction

Transaction that involved a collection item prior to its accession into the current collection, such as an exhibition.

@krgomez does the above work for you?

**Comment by krgomez** [comment]
Looks good to me!
