### ISSUE TITLE
Erroneous records stuck in bulkloader

### ISSUE THREAD

**Issue by camwebb** [ArctosDB/arctos#4739]
Minor issue. 

By SQL editing the status of a set of bulkloaded records (which proceeded to be loaded fine), I somehow generated three erroneous records that are stuck in the [bulkloader](https://arctos-test.tacc.utexas.edu/Bulkloader/bulkloader_status.cfm).  For tidiness it would be good to purge these. They have been there a couple days now. Thanks!

```
Coll      | Accn | By | status   | n
UAM:Alg   |      |    | autoload | 1
UAMb:Herb |      |    | autoload | 1
UAM:Herb  |      |    | autoload | 1
```

**Comment by dustymc** [comment]
All loaders are being affected by https://github.com/ArctosDB/arctos/issues/4727#issuecomment-1145992025 so nothing will happen until that's resolved. 

If you mean you want them gone, you can change status to [DELETE](https://handbook.arctosdb.org/documentation/bulkloader.html#processing) (which still won't do anything until the DNS situation is resolved).

**Comment by camwebb** [comment]
> If you mean you want them gone, you can change status to DELETE

That's the problem. They don't belong to me, or anyone, so they can't be deleted. I guess you'll have to peer into the back-end. Not v important though. Thanks

**Comment by dustymc** [comment]
Gotcha, thanks. I think they're a relic of the old screen, and it will probably make more of them (now that it won't recognize them) until it's gone. Tentatively closing, this will be covered by https://github.com/ArctosDB/arctos/issues/4257
