### ISSUE TITLE
Feature Request - add create date to table collection

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4740]
**Is your feature request related to a problem? Please describe.**

Knowing when a collection was created would be handy for reporting.

**Describe what you're trying to accomplish** 

reports

**Describe the solution you'd like**

* new field create_date date default current_date
* anything else that would be handy for whatever reason?

**Describe alternatives you've considered**

struggle

**Additional context**

NOT NULL would be less likely to allow something to slip through - can we approximate the creation data for existing collections (or just use some obvious default or ??)?

**Priority**

sooner==better

**Comment by Jegelewicz** [comment]
Can we add in dates for those already created?

**Comment by ewommack** [comment]
Are we talking about creation in Arctos or creation in the universe as a whole?

**Comment by dustymc** [comment]
>default current_date

creation in Arctos

**Comment by dustymc** [comment]
no interest
