### ISSUE TITLE
Bulkload Identifiers Stuck in Autoload

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#4741]
I am trying to bulkload identifiers, but they have been stuck in autoload for over a day. I have experienced wait times in the past, but it usually starts processing within an hour. Arctos has not alerted me to any potential errors that would be preventing the bulkload from happening.
![image](https://user-images.githubusercontent.com/93737929/172021550-c47fb556-abc7-460d-950c-58c9faf81743.png)

I am accessing Arctos through this link: https://arctos-test.tacc.utexas.edu/tools/BulkloadOtherId.cfm and can edit individual records without an issue. I've tried restarting the processing, but it still gets stuck.

**Comment by Jegelewicz** [comment]
@wellerjes they will not load until the SSL certificate issue is corrected.

**Comment by wellerjes** [comment]
Thanks! They've loaded now.
