### ISSUE TITLE
Media uploaded last week are wonky

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#4742]
I uploaded a number of photos to records last week while we were running production off of test.
This week those records are showing media previews all wonky.
<img width="619" alt="Screen Shot 2022-06-06 at 9 15 08 AM" src="https://user-images.githubusercontent.com/17605945/172211694-590eab2c-02e3-43f4-9ba7-5e888190cffb.png">

Links to those records:
https://arctos.database.museum/guid/UAM:EH:UA74-039-0035
https://arctos.database.museum/guid/UAM:EH:UA70-054-0038
https://arctos.database.museum/guid/UAM:EH:UA2007-010-0111

Is there anything I need to do to fix these? Seems like it's just the thumbnails acting squirrely. When you click on them the full size image comes up fine.

Please help - critical to work currently happening for an exhibit.

**Comment by dustymc** [comment]
That's part of https://github.com/ArctosDB/arctos/issues/4727#issuecomment-1145992025, it should be catching up now.

FWIW the automagic preview generation will always (perhaps barring something like [IIIF](https://github.com/ArctosDB/arctos/discussions/4343) becoming available) be a bit limited, if you need a particular preview you can create and link it manually.

**Comment by AJLinn** [comment]
> if you need a particular preview you can create and link it manually.

99.9% of the time the automagic previews are perfect - good enough that I don't feel the extra work of manually creating a preview thumbnail and uploading/linking it is worth it!
