### ISSUE TITLE
Bulkload accessions

### ISSUE THREAD

**Issue by SerinaBrady** [ArctosDB/arctos#4744]
Hi!
About how long does the accessions bulkloader take? I am trying to bulkload some ASNHC Bird data and I'm waiting on the accessions to load.
Thanks!

**Comment by dustymc** [comment]
<img width="392" alt="Screen Shot 2022-06-06 at 1 59 58 PM" src="https://user-images.githubusercontent.com/5720791/172248479-87334276-5ae8-45df-9630-70ab38e0eebb.png">

**Comment by cjconroy** [comment]
Does this give an indication of when my file will load?  The 132 citations is mine. Its been a couple of hours. 498 minutes?

**Comment by dustymc** [comment]
>498 minutes?

Yes, unless someone changes the order or loads something "upstream" of that.

I can try to clarify if something's not already clear, just let me know.

**Comment by cjconroy** [comment]
How cool would it be if Arctos told you that when you set to autoload. Or sent you an email. I had no idea about that page. Or even a link on the bulkloader pages to get to that status page. 
BTW, the video for how to bulkload citations has out of date information.

**Comment by dustymc** [comment]
> link on the bulkloader pages 

Newer versions do, it should eventually get to everything as things get rebuilt.

<img width="1623" alt="Screen Shot 2022-06-06 at 2 35 00 PM" src="https://user-images.githubusercontent.com/5720791/172253197-96ca0542-b1d3-4898-b4ca-329734ddd131.png">

>out of date information

Yes, that eventually comes true for just about all documentation. I'm certainly up for clever ideas, but I suspect the only realistic option is to file an Issue when you notice something.
