### ISSUE TITLE
Georeferencing not saving correctly?

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#4746]
I'm in the process of updating the georeferencing handbook with the new features/processes from the last few months. I was working on an example when I noticed that the uncertainty radius isn't saving correctly.

Example: https://arctos.database.museum/guid/CHAS:Herb:1873.48.52

In GeoLocate, the borders of Duluth are in the orange transparent polygon. I adjusted the uncertainty to "resize uncertainty to polygon" and saved.
![image](https://user-images.githubusercontent.com/93737929/172411524-398d0d7b-6e06-4804-8cae-4fcff9bea5f9.png)

However, when I go back to the catalog record, the area uncertainty is now smaller and does not include the entire borders of Duluth.
![image](https://user-images.githubusercontent.com/93737929/172412853-928adc61-25fe-41b6-92de-36ef564130c6.png)

I tried the process with the "error polygon" box checked and unchecked (going forward, we will be georeferencing with this box unchecked), but the results are the same. Am I doing something wrong, or is this a GeoLocate bug?

Thanks!

**Comment by dustymc** [comment]
I don't think I understand what happened in GeoLocate, but https://arctos.database.museum/editLocality.cfm?locality_id=11595311 is saved as a polygon 


<img width="1312" alt="Screen Shot 2022-06-07 at 8 31 03 AM" src="https://user-images.githubusercontent.com/5720791/172420906-25cd29ad-1c5f-40a4-bc29-9aa4667cc934.png">

and the point-radius surrounding it is an approximation.

**Comment by wellerjes** [comment]
Okay, I think I understand. If I use the polygon to create the point-radius, then remove it, it looks like this:

[image](https://user-images.githubusercontent.com/93737929/172425448-38f21aeb-c1b4-4153-97b6-5ce65d6ed977.png)

![image](https://user-images.githubusercontent.com/93737929/172425639-a50e0860-e8e6-49a6-a127-18faa7335fd1.png)

The border around the map is still yellow (because the point radius overlaps with the county borders), but the radius appears exactly as I see it within GeoLocate because Primary Spatial Data Type is point-radius data.
