### ISSUE TITLE
Parts>>>Container Error

### ISSUE THREAD

**Issue by Cloveis** [ArctosDB/arctos#4747]
![image](https://user-images.githubusercontent.com/90786192/172457693-d2578670-ab03-41c9-9cd5-cd03e4e0a4d2.png)

# Error Text
load fail::ERROR: query returned no rows Where: PL/pgSQL function moveparttocontainer(bigint,text,bigint,text,text) line 13 at SQL statement

# Where it happened
(https://arctos.database.museum/tools/BulkloadPartContainer.cfm)

# Steps to get there
Logged into arctos and hovered over enter data, batch tools, parts, then selected. parts>>container I loaded my .csv using the column headers " guid, part_name, barcode, new_container_type". Some of these records loaded however 34 of them were returned with the status message above.

# Problem
I am unsure how to decipher this error to fix my spreadsheet and properly load this data.

**Comment by dustymc** [comment]
You're trying to use a barcode that doesn't exist.

<img width="1687" alt="Screen Shot 2022-06-07 at 11 41 04 AM" src="https://user-images.githubusercontent.com/5720791/172458165-280f7802-e4a0-47c7-82e4-466ef29f62bc.png">

https://handbook.arctosdb.org/documentation/container.html
