### ISSUE TITLE
Data entry - collecting source required?

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#4748]
My staff noticed yesterday while cataloging that collecting source is now a required field. The box is not yellow:
<img width="853" alt="Screen Shot 2022-06-07 at 12 49 44 PM" src="https://user-images.githubusercontent.com/17605945/172649523-84179c9f-2125-4178-a714-869f3431b06a.png">

But, when she tried to save with a NULL value she got this:
![IMG_2176-2](https://user-images.githubusercontent.com/17605945/172650317-cd454ee7-cf32-4685-8a6e-d36843ba6911.jpg)

This field does not make sense for cultural collections or paleo/geology collections.
Can we please un-require this field for data entry? The two options are not appropriate and using 'unknown' makes our data seem unreliable, especially if someone looks at the code table documentation:

<img width="933" alt="Screen Shot 2022-06-08 at 7 05 41 AM" src="https://user-images.githubusercontent.com/17605945/172651103-de3e3ed6-c4ae-4f29-a0fb-0ced7cfb13f1.png">

I know I weighed in on this issue already but I can't find the actual github issue.

**Comment by ewommack** [comment]
huh, how weird that it is required. I don't see a problem not having it required. It's great to have that data for natural history collections, but I agree with @AJLinn that it isn't going to be appropriate for other collection types.
