### ISSUE TITLE
http/https weirdness

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4749]
Today during the demo camp, I entered arctos.database.museum into the browser and Arctos opened. I then went to the portal page and searched the Arctos Entity portal for catalog number 19. I didn't pay attention to the url as everything was working, but then I wen to GBIF to search occurrences, copied the url from entity 19 into the dwc:organismID search field in GBIF occurrences and got no results! WHAAAAAAT? I did this last night from my computer and it worked perfectly, finding the four occurrences that are associated with this entity. I was stumped, but Erica Krimmel was on top of things and realized that the dwc:organismID in the GBIF records was https://arctos.database.museum/guid/Arctos:Entity:19 while the url I had copied from my search result was http://arctos.database.museum/guid/Arctos:Entity:19 What happened to the "s"? Shouldn't all http be redirected to https?

Just thought I would mention this as it seemed odd to me. Thanks to Erica's keen observational skills, the day was saved and the GBIF search worked using the https url.

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/discussions/4679

**Comment by Jegelewicz** [comment]
Check

**Comment by ewommack** [comment]
Ah, I bet this will help me with a request that came in while I was in the field. Thanks @Jegelewicz and @dustymc
