### ISSUE TITLE
Need Help with Arctos Error

### ISSUE THREAD

**Issue by esdearmon** [ArctosDB/arctos#4750]
Error ID: DBD642E0-B47C-49E7-B80B08AD33004A24
Error message: ERROR: Where: PL/pgSQL function trigger_fct_ti_bulk_cid() line 29 at RAISE

# Where it happened
[**Provide a link to or a description of the page where the error occurred.**
](https://arctos.database.museum/Bulkloader/BulkloadSpecimens.cfm)

# Steps to get there
Uploaded CSV file, records were in the staging table. Clicked just load these records, then this error occurred.

# Problem
**Community response to describe the problem that caused the error**

# Solution
**Community response with directions for how to correct the problem**

**Comment by dustymc** [comment]
>Clicked just load 

Something in your data is incompatible with the more controlled structure of table bulkloader. Check and load should find it.

**Comment by Jegelewicz** [comment]
@esdearmon I ALWAYS use check and load. My experience is that you never are able to load the first file you create, no matter how small the file or how clean you think it is. The check will give you better error messages that let you fix whatever data is problematic.

**Comment by esdearmon** [comment]
@Jegelewicz I am definitely noticing that. My confidence got a little too high this time!
