### ISSUE TITLE
Can't choose different datum?

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#4751]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I'm trying to correct a locality based off image transcription and can't change datum to NAD1927. It only lets me choose blank or World Geodetic System 1984

**To Reproduce**
1. Choose locality
2. Try to select drop down menu for datum
3. Only WGS1984 shows up

**Expected behavior**
All datum options to show up

**Screenshots**
![Screenshot 2022-06-09 081559](https://user-images.githubusercontent.com/38706617/172868823-3d9bd962-9fea-4587-b642-e711c44e58d3.png)

**Data**
Here's link to example: https://arctos.database.museum/editLocality.cfm?locality_id=10927332

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by dustymc** [comment]
When entered with a collecting event "as-entered" (including datum) is kept. 

Localities are only converted with human assistance, so there can't really be an "as-entered" that differs from the data.

If you're looking for "someone said" (not "as-entered") then I think there's currently no such thing. https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_event_attr_type and/or https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlocality_attribute_type are capable and seem appropriate, and that's been suggested a few times, but I guess nobody's ever actually fleshed that out?

**Comment by dustymc** [comment]
No, as-entered cannot be edited. (And should not be used for any purpose requiring that - they're "this was fed to the form and might be useful for things like tracing conversion bugs.")

**Comment by mvzhuang** [comment]
ok got it. thanks Dusty!
