### ISSUE TITLE
Timing out/runtime errors when attempting to create a new taxon

### ISSUE THREAD

**Issue by szaborac** [ArctosDB/arctos#4754]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I am attempting to create a new taxon - _Deschampsia cespitosa_ var. _pumila_. However, Arctos keeps timing out. 

**To Reproduce**
1. Go to https://arctos.database.museum/taxonomy.cfm and click "Create a New Name" button
2. Type in "Deschampsia cespitosa var. pumila" in the dialog box. Taxon Name Type = Linnean
3. click "Create New Name" button
4. Wait.

**Expected behavior**
According to the instructions (https://handbook.arctosdb.org/how_to/How-to-Create-Taxa.html##create-classification-by-cloning-local-source), I should be prompted to provide a webservice classification for the new name. If the system knows the new name is invalid, then I should be challenged to validate my attempt. 

**Screenshots**
See attached runtime errors.

Lucee [5.3.8.206] - Error (Expression)
--
Message | request  /editTaxonomy.cfm (/usr/local/webroot/editTaxonomy.cfm) has run into a  timeout (timeout: 60 seconds) and has been stopped. The thread started  60003ms ago.
Java Stacktrace | lucee.runtime.exp.RequestTimeoutException:  request /editTaxonomy.cfm (/usr/local/webroot/editTaxonomy.cfm) has run  into a timeout (timeout: 60 seconds) and has been stopped. The thread  started 60003ms ago.	at java.base@11.0.15/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)	at java.base@11.0.15/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929)	at java.base@11.0.15/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1519)	at java.base@11.0.15/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)	at java.base@11.0.15/java.net.InetAddress.getAllByName0(InetAddress.java:1509)	at java.base@11.0.15/java.net.InetAddress.getAllByName(InetAddress.java:1368)	at java.base@11.0.15/java.net.InetAddress.getAllByName(InetAddress.java:1302)	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)	at lucee.runtime.net.http.sni.DefaultHttpClientConnectionOperatorImpl.connect(DefaultHttpClientConnectionOperatorImpl.java:26)	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)	at lucee.runtime.tag.Executor4.execute(Http.java:1887)	at lucee.runtime.tag.Executor4.run(Http.java:1874)	at lucee.commons.lang.PageContextThread.run(PageContextThread.java:25) | lucee.runtime.exp.RequestTimeoutException:  request /editTaxonomy.cfm (/usr/local/webroot/editTaxonomy.cfm) has run  into a timeout (timeout: 60 seconds) and has been stopped. The thread  started 60003ms ago. | at java.base@11.0.15/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) | at java.base@11.0.15/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929) | at java.base@11.0.15/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1519) | at java.base@11.0.15/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848) | at java.base@11.0.15/java.net.InetAddress.getAllByName0(InetAddress.java:1509) | at java.base@11.0.15/java.net.InetAddress.getAllByName(InetAddress.java:1368) | at java.base@11.0.15/java.net.InetAddress.getAllByName(InetAddress.java:1302) | at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45) | at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112) | at lucee.runtime.net.http.sni.DefaultHttpClientConnectionOperatorImpl.connect(DefaultHttpClientConnectionOperatorImpl.java:26) | at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374) | at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) | at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) | at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) | at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) | at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) | at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) | at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) | at lucee.runtime.tag.Executor4.execute(Http.java:1887) | at lucee.runtime.tag.Executor4.run(Http.java:1874) | at lucee.commons.lang.PageContextThread.run(PageContextThread.java:25)
lucee.runtime.exp.RequestTimeoutException:  request /editTaxonomy.cfm (/usr/local/webroot/editTaxonomy.cfm) has run  into a timeout (timeout: 60 seconds) and has been stopped. The thread  started 60003ms ago.
at java.base@11.0.15/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
at java.base@11.0.15/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929)
at java.base@11.0.15/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1519)
at java.base@11.0.15/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)
at java.base@11.0.15/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
at java.base@11.0.15/java.net.InetAddress.getAllByName(InetAddress.java:1368)
at java.base@11.0.15/java.net.InetAddress.getAllByName(InetAddress.java:1302)
at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
at lucee.runtime.net.http.sni.DefaultHttpClientConnectionOperatorImpl.connect(DefaultHttpClientConnectionOperatorImpl.java:26)
at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
at lucee.runtime.tag.Executor4.execute(Http.java:1887)
at lucee.runtime.tag.Executor4.run(Http.java:1874)
at lucee.commons.lang.PageContextThread.run(PageContextThread.java:25)

**Desktop (please complete the following information):**
 - OS: Mac High Sierra 10.13.6
 - Browser: FireFox 101.0.1

**Additional context**
The instructions for creating a new taxon or cloning an existing taxon do not match the UI

**Priority**
I shouldn't be getting runtime errors. Priority 1 or 2.

**Comment by dustymc** [comment]
Looks like globalnames is having a bad day. I'll adjust timeouts for next release.
