### ISSUE TITLE
Feature Request - higher geography - require spatial authority?

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4755]
**Is your feature request related to a problem? Please describe.**

Our higher geography data could (relatively easily?) be a lot better. **Can we at least stop making it worse?**

**Describe what you're trying to accomplish** 

Less-horrid data.

**Describe the solution you'd like**

1. Immediately stop creating geography without spatial data
2. Find spatial data for existing geography that lacks it
3. (maybe) purge whatever geography can't be associated with spatial data. This can probably only be realistically discussed after (2), and would in any case probably be more complicated than ``not null`` - eg 'no higher geography recorded' will need to exist in some way (modify the structure, allow exceptions, whatever).

(1) is technically trivial, but we might need to provide tools to better import or create shapes (import exists but is fragile, an approximation made by a few clicks on geolocate's map would be worlds better than what we have now)

(2) is probably relatively technically trivial for "normal" things, but is very likely to be time consuming. Someone with access to and familiarity with real GIS would be a huge benefit, but I can probably (maybe?) deal with things like GADM.

**Describe alternatives you've considered**

1. Kludge on with increasingly cruddier data
2. Deprioritize "curatorially asserted geography" (https://github.com/ArctosDB/arctos/issues/3272), but 
    * I'm not aware of any existing service that can provide 'best contains' geography (so we're pulling lots of 'might be' data), and 
    * The Community seems fairly attached to local geography (I think?)

**Additional context**

Lots of issues related to this. 

https://github.com/ArctosDB/arctos/issues/2874 - if we had consistent higher geography data we could use it to magic higher geography strings from coordinates (and we can magic coordinates from locality strings, but I'm not sure how far that might extend in messy pre-Arctos data)

https://github.com/ArctosDB/arctos/issues/3018 - we could visualize what Valencia County looked like before and after Cibola County got hacked out, and from the discussion I could build my own "smallest containing authority" lookup

https://github.com/ArctosDB/arctos/issues/4703#issuecomment-1148958728, https://github.com/ArctosDB/arctos/issues/4493 - we could drop the goofy-but-functional wikipedia not-very-authoritative-authority (and potentially do spatial things on creation - "this is 95% overlap with that, are you really sure??")

https://github.com/ArctosDB/arctos/issues/2374, https://github.com/ArctosDB/arctos/issues/2401, etc.  - getting the names of arbitrary things "standardized" would be less important if we would spatially define "Dixie" or "San Francisco Bay" or whatever.

etc etc - would provide a lot of functionality, probably in unexpected ways

**Priority**

Seems high to me, might even be fundable, but probably needs Community buy-in to be properly prioritized.

@mkoo thoughts?

**Comment by dustymc** [comment]
Merging https://github.com/ArctosDB/arctos/issues/4493 into this: spatial or not, can/should we treat geography as an authority and push creations through the normal authority creation (eg github issue) process?

**Comment by dustymc** [comment]
I'm accepting the enthusiastically positive silence and moving ahead with the [Issue part of this](https://github.com/ArctosDB/arctos/issues/4755#issuecomment-1163558823) unless someone stops me NOW.

I'm finding lots of geography that doesn't meet the "BE SPECIFIC!" Authority guidelines, which forces me to re-do that to check if the thing is what it claims to be. (One example below.) Running this through the normal authority creation channels would prevent that, and probably lots of other problems.

TODO: create a geography creation request template



```

arctosprod@arctos>> select higher_geog from geog_auth_rec where source_authority ='https://en.wikipedia.org/wiki/Formosa_Province';
                       higher_geog                       
---------------------------------------------------------
 South America, Argentina, Formosa
 South America, Argentina, Formosa, Formosa Department
 South America, Argentina, Formosa, Laishi Department
 South America, Argentina, Formosa, Pilcomayo Department
 South America, Argentina, Formosa, Patino Department
(5 rows)
```

**Comment by Jegelewicz** [comment]
Please wait until the geography committee meets. I'm afraid this is going to stop data migrations....

**Comment by dustymc** [comment]
There's a template, I'm nuking anything above GID::10016358 without a good issue reference in remarks.

This will alert me to new geog, I can add spatial data before or after creation, I think that part is sufficiently addressed by the process itself.

I'm happy to do whatever I can to ensure this doesn't block anything (same as everything else). Whatever that involves, it will absolutely be less painful - and error prone - than cleaning up the messes.

**Comment by mkoo** [comment]
this is ok to do somewhat...
-- what's the word on wkt vs json for the spatial requirement?
-- what about my archival favorites: no higher geography recorded and no
specific higher geography?
they need to be exceptions OR I suppose we can add global extent (eg
180,-180,180,-180)

**Comment by dustymc** [comment]
> wkt vs json

Don't care. If I can make ``pgis::geog`` I'm happy. Or I've got GADM and a bunch of other junk cached, I can add that stuff for them. If the requestor is still around and willing to answer questions and I don't have to guess what their intentions were while not changing the meaning of the data on thousand of records most of which look to be lost in like 19 different ways then I'm happy, whatever else I have to do. Low bar at the moment, anyone should be able to sail right over.


>exceptions

Those are my....

```
arctosprod@arctos>> select count(*) from geog_auth_rec where spatial_footprint is null;
 count 
-------
 10439
```
10,438th and 10,439th problems at the moment. Maybe we'll learn something interesting before we get there.

**Comment by mkoo** [comment]
yep ok. more trials of footprint formats

also it's probably #1 and #10439 on your list.... But they can have spatial
footprints too!
