### ISSUE TITLE
Validation error when viewing Taxonomy page

### ISSUE THREAD

**Issue by szaborac** [ArctosDB/arctos#4756]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Getting a validation error when viewing taxonomy details

**To Reproduce**
1. Go to https://arctos.database.museum/taxonomy.cfm
2. Search for a taxon name (I most recently used Pedicularis arctica)
3. Wait about a minute

**Expected behavior**
I should be able to view page, then leave for a short period to review the data which is impacted by the information presented, then come back to the page without issue. 

**Screenshots**
Please see attached screenshot. 

**Desktop (please complete the following information):**
 - OS: Mac High Sierra
 - Browser FireFox
 - Version 101.0.1

**Priority**
Unsure where to set priority. 2? 1? 

![Screen Shot 2022-06-09 at 4 14 11 PM](https://user-images.githubusercontent.com/75702232/172965965-e36c29e5-3c9d-4150-9cc5-b03e2d56219e.png)

**Comment by szaborac** [comment]
Another way to find the error: 
Search for Pedicularis, then scroll down and select arctica.

**Comment by dustymc** [comment]
This is the same issue as https://github.com/ArctosDB/arctos/issues/4754, merging.

**Comment by szaborac** [comment]
Oh, okay. My apologies, and thank you!
