### ISSUE TITLE
Fixing old, serious locality error - procedure, permission?

### ISSUE THREAD

**Issue by camwebb** [ArctosDB/arctos#4757]
Locality id # 1171506 with spec_locality = "Bering Strait District: Vicinity of the Kukpuk River" (and with coordinates) is erroneously assigned to 27303 specimens, and 2893 collecting events (`select count(*) from collecting_event where locality_id = 1171506`) which were entered with verbatim_locality of "Alaska" or "unknown" (`select distinct verbatim_locality from collecting_event where locality_id = 1171506`). The vast majority of the collections were from accessions 2012.2.Cryp, 2014.03.Cryp, 2014.04.Cryp (`select accession, count(*) from flat where locality_id = 1171506 group by accession order by count(*) desc`), indicating that this is probably an old mistake, the mistake being (I guess) to 'fix' an unknown locality by adding spec_locality and long and lat.

Since these data are widely shared (GBIF), we should correct this error, by setting spec_locality to 'unknown' and removing long and lat from locality 1171506. This is an action that impacts collections across 10 collections (guid_prefix), and I don't want to just do it without checking first. What is the process for a fix of this kind? I looked in the handbook but didn't find an answer. Thanks.

**Comment by dustymc** [comment]
I don't see any coordinates, but you can figure the rest out it out by going to edit locality then, right under the big red box that tells you you're about to change ~27K records...

<img width="186" alt="Screen Shot 2022-06-10 at 8 37 35 AM" src="https://user-images.githubusercontent.com/5720791/173101190-c6bc03f8-1a56-4d2d-9700-57c4ae913aa0.png">

The user who changed things should be made aware of https://handbook.arctosdb.org/documentation/sharing-data-and-resources.html

The MSB records were all entered before the change and look like typical low-data records, I'm relatively sure they're fine with it just being changed back (which will leave history, so it's un-doable). The rest are UAM and probably in the same situation, but I can check whatever in the data if necessary or you can just ask them.

**Comment by dustymc** [comment]
done?

**Comment by camwebb** [comment]
Now [done](https://arctos.database.museum/info/localityArchive.cfm?locality_id=1171506).
