### ISSUE TITLE
Code Table Request - Add attributes to TEACH

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#4760]
**Goal**
Add specific attributes to the TEACH code table for birds in the teaching collection.

The following attributes are not accessible in TEACH:
sex: "unknown" not available
Link to code table: https://arctos.database.museum/info/ctDocumentation.cfm?table=ctsex_cde

age class: "immature" not available
Link to code table: https://arctos.database.museum/info/ctDocumentation.cfm?table=ctsex_cde

body condition: field not available
Link to code table: https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type

Thanks!

**Comment by Jegelewicz** [comment]
Added!
