### ISSUE TITLE
Need Help with Arctos Error - error after log in

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4761]
# Error Text
<html><body>

ERROR_ID | 6036582F-A953-4A26-93B49DF8960F551C
-- | --
ERROR_TYPE | expression
ERROR_MESSAGE | Component [Result] has no accessible Member with name [PARTVIEW]
ERROR_DETAIL | enable [trigger data member] in administrator to also invoke getters and setters

</div>
</body>
</html>

# Where it happened
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#individual_count

# Steps to get there
was on that page, and selected the log in button, entered my id and password in log in form, hit enter, get error

# Problem
**Community response to describe the problem that caused the error**

# Solution
**Community response with directions for how to correct the problem**

**Comment by Jegelewicz** [comment]
Apparently I am now logged in, but the search page now looks like this

![image](https://user-images.githubusercontent.com/5725767/173610290-f0635eb8-7df2-464f-af2d-8845625eff1a.png)

<html><body>


ERROR_ID | 1F874E96-62A0-44DD-B051959AB287015B
-- | --
ERROR_TYPE | expression
ERROR_MESSAGE | The key [SEARCHBY] does not exist, only the  following keys are available: [AUTH_KEY, cfid, cftoken,  COLLECTION_LINK_TEXT, COLLECTION_URL, DBUSER, EPW, FLATTABLENAME,  HEADER_COLOR, HEADER_CREDIT, HEADER_IMAGE, INSTITUTION_LINK_TEXT,  INSTITUTION_URL, IPADDRESS, LASTCHECKINTIME, lastvisit,  META_DESCRIPTION, META_KEYWORDS, MYAGENTID, portal_text,  REQUESTINGSUBNET, ROLES, sessionid, SESSIONKEY, STYLESHEET, timecreated,  urltoken, USERNAME].
ERROR_DETAIL |  

</div>
</body>
</html>

**Comment by dustymc** [comment]
I think something about the DB connection is caching. I patched an "even if" fix in. If that doesn't work for some reason, logging out and back in seems to fix it.

**Comment by wellerjes** [comment]
I just had this same issue in Chrome. I switched to Firefox and everything seems to be okay.

**Comment by Jegelewicz** [comment]
I was using Firefox when this happened.

**Comment by Jegelewicz** [comment]
So I logged out and back in and had the old problem of it looks like nothing happens even though I am logged in.

**Comment by Cloveis** [comment]
I'm still having this problem after trying Firefox. I've tried logging out and in, restarting the browser, and restarting my laptop. Any suggestions?

**Comment by dustymc** [comment]
@Cloveis are you seeing the same error? Error logs suggest you're not successfully logging in. If it is the same error, try clearing cookies - I'm not 100% sure that's the problem, but something persistent at the browser level seems to be involved and that's the usual mechanism.

**Comment by wellerjes** [comment]
I'm not sure if this is related (if so, I'll open another issue), but when I try to print labels (in FireFox), I get this error 
![image](https://user-images.githubusercontent.com/93737929/173651450-1bc6f117-dc9d-45eb-bc29-927aa4449e7e.png)
after clicking on http://reports.arctos.database.museum/reporter/report_printer.cfm?auth_key=79B48998-ED30-4DB6-B9ED5CFD4B83C80D&table_name=temp%5Fcache%2Ess%5Fjweller%5F20220614120607318%5F242&sort=guid

When I try in Chrome, I can't complete a search at all; I get this error:
![image](https://user-images.githubusercontent.com/93737929/173655274-329b024c-7cef-42f7-8e60-cb74909281c9.png)

**Comment by wellerjes** [comment]
Labels are working; thank you!
