### ISSUE TITLE
Invalid accession agent - but not?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4764]
Attempting to load accessions and getting this

![image](https://user-images.githubusercontent.com/5725767/173691474-e27f7928-d657-4f01-bd51-765c77baf843.png)

First, why the exact same error four times?
"invalid trans_agent_1"

Second, that isn't an invalid agent? https://arctos.database.museum/agents.cfm?agent_id=21336265

I checked for weird characters, but don't see anything. Help?

**Comment by dustymc** [comment]
I don't seem to have access to whatever you're loading, or you deleted it, or ??

**Comment by Jegelewicz** [comment]
Yeah, I deleted it because I had to spell collection correctly in the remarks...
Trying again so let's see what happens

**Comment by Jegelewicz** [comment]
OK - take a look now, it's weird how some of them post multiple errors for trans agent 1, but they all have the same agent in that column

**Comment by dustymc** [comment]
Thx, its not reporting errors correctly, will be in next release. At least University of Idaho Collection doesn't exist. (And hopefully neither does RMZ Project and etc.!)

**Comment by Jegelewicz** [comment]
Yep - that's right, some of those others don't exist and I expected errors on a few, but not all of them.

**Comment by dustymc** [comment]
I snuck a minirelease out, should be better errors
