### ISSUE TITLE
Can't login - Authentication failed/ Access restricted

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#4766]
I can't seem to login all of sudden. It worked earlier this morning. I tried resetting my password a few times and got the following message and can't get in. @dustymc Did I do something funky?????

# Error Text
Authentication failed. Additional Information: Access restricted.

# Where it happened
login page
# Steps to get there
*Login
Password

# Problem
**Community response to describe the problem that caused the error**

# Solution
**Community response with directions for how to correct the problem**

**Comment by dustymc** [comment]
Unlocked and emailed your latest pwd.

**Comment by Cloveis** [comment]
I'm having this same issue, I've been struggling to log in since yesterday morning. Could I get assistance?

**Comment by dustymc** [comment]
@Cloveis credentials in your email

**Comment by dustymc** [comment]
Happy?

**Comment by mvzhuang** [comment]
@dustymc I think it happened again...am I doing something that's triggering that???

**Comment by dustymc** [comment]
You have email - see https://github.com/ArctosDB/arctos/issues/4767, when whatever happens I don't have an ability to deliver mail.

**Comment by mvzhuang** [comment]
THanks!

**Comment by mvzhuang** [comment]
@dustymc I think it happened again. ....am I doing something that's triggering that????

On Jun 17, 2022 12:07 PM, dustymc ***@***.***> wrote:

Closed #4766<https://github.com/ArctosDB/arctos/issues/4766> as completed.

**Comment by dustymc** [comment]
I don't see anything unhappy about your account?

**Comment by mvzhuang** [comment]
uhhhh i don't know how this message sent, but i didn't send it O_O. Please ignore!
