### ISSUE TITLE
Duplicate accession, but not?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4768]
OK, errors are better described in accession loader, but now, I am being told that an accession already exists when it does not.

Example is CRCM:Bird 92

![image](https://user-images.githubusercontent.com/5725767/173906770-822f609c-8426-481b-a48e-02f9ab124595.png)

but a search for it 

![image](https://user-images.githubusercontent.com/5725767/173906912-c3069c7b-b127-4b55-b29b-997e1e9a90df.png)

gives me

![image](https://user-images.githubusercontent.com/5725767/173906841-c1943cc3-2f31-4d62-9c08-6095058e03b4.png)

**Comment by Jegelewicz** [comment]
Some other things I have noticed in the tedious process of bulkloading accessions, which really shouldn't be this tedious!

You MUST use an agent's preferred name, aka's will NOT load. Has this always been true?

When an agent's preferred name is also an aka on another agent, the error is "invalid_agent_x". This is a poor description for this case. Can we not say "there are two agents with this name, this accession MUST be entered manually"? Which sucks by the way, but without a method for choosing in the tool, I don't see another way this can work unless we can put the agent ID in there. (Can we?)

When an agent is not in the agents table and you add it, there is a significant lag before you can load the accession - Arctos takes a while to figure out that the agent has been added. Can we make this better? Leaving an accession in the loader just because Arctos doesn't know I've added an agent means that I have to keep coming back to a task that I should be able to finish NOW.

**Comment by dustymc** [comment]
> accession already exists when it does not.

I don't have access so IDK but the key probably isn't wrong - maybe dups in the load file?

> aka's will NOT load.

Howya figure?

> preferred name is also an aka on another agent

Ah - yea, I can fix that.

>takes a while...make this better

Its just resources. MAYBE not caching would be OK, I'd guess it would cause instability in other things in certain circumstances. FWIW I'd love to not cache anything, ever.

**Comment by Jegelewicz** [comment]
>>     aka's will NOT load.
> 
> Howya figure?

Actually, now that I think about it, the aka's were added just now, so are probably falling into 

> takes a while...make this better

**Comment by Jegelewicz** [comment]
Also - maybe the "duplicate" thing where I couldn't find the accession in search was cache related? Anyway, everything except the preferred name same as aka in another name is covered.
