### ISSUE TITLE
inviting an operator error

### ISSUE THREAD

**Issue by amgunderson** [ArctosDB/arctos#4769]
We are trying to invite Lisa Druckenmiller (Arctos username skirunplay) as an operator for UAM:Herb but get this error. As far as I can see all the needed bits are in place for her to be invited. Help please.

<img width="1322" alt="Screen Shot 2022-06-15 at 3 01 01 PM" src="https://user-images.githubusercontent.com/8440698/173956180-94f61b15-33b6-4c56-8ca0-355a963acfad.png">

**Comment by Jegelewicz** [comment]
Maybe it is because Arctos cannot send email right now? See #4767

**Comment by amgunderson** [comment]
The whole error as text is,

ERROR_ID | C5F54C35-F2F4-4084-ADDC943388BD4C2B
-- | --
ERROR_TYPE | SQL
ERROR_MESSAGE | ERROR: syntax error at or near "$2" Position: 173
ERROR_DETAIL |  
ERROR_SQL | insert into cf_temp_user_invite ( invited_username, invited_by_username, invited_by_email, status, status_date ) values ( 'skirunplay' 'aren', 'amgunderson@alaska.edu', 'invited', current_timestamp )
request dump:

request
node_name	
string	arctos-2021
rdurl	
string	/AdminUsers.cfm?makeNewDbUser&skirunplay
uui	
string	
uuid	
string	C5F54C35-F2F4-4084-ADDC943388BD4C2B
exception dump:

Catch
Entries: 15
additional	
Struct (ordered)
SQL	
string	insert into cf_temp_user_invite ( invited_username, invited_by_username, invited_by_email, status, status_date ) values ( 'skirunplay' 'aren', 'amgunderson@alaska.edu', 'invited', current_timestamp )
DatabaseName	
string	PostgreSQL
DatabaseVersion	
string	12.2
DriverName	
string	PostgreSQL JDBC Driver
DriverVersion	
string	42.2.20
Datasource	
string	user_login
DataSource	
string	user_login
Detail	
string	
ErrorCode	
string	0
Extended_Info	
string	
ExtendedInfo	
string	
Message	
string	ERROR: syntax error at or near "$2" Position: 173
NativeErrorCode	
number	0
queryError	
string	insert into cf_temp_user_invite ( invited_username, invited_by_username, invited_by_email, status, status_date ) values ( 'skirunplay' 'aren', 'amgunderson@alaska.edu', 'invited', current_timestamp )
Sql	
string	insert into cf_temp_user_invite ( invited_username, invited_by_username, invited_by_email, status, status_date ) values ( 'skirunplay' 'aren', 'amgunderson@alaska.edu', 'invited', current_timestamp )
SQLState	
string	42601
StackTrace	
string	lucee.runtime.exp.DatabaseException: ERROR: syntax error at or near "$2" Position: 173 at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553) at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285) at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323) at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481) at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401) at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164) at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:153) at lucee.runtime.type.util.QueryUtil.execute(QueryUtil.java:328) at lucee.runtime.type.QueryImpl.execute(QueryImpl.java:296) at lucee.runtime.type.QueryImpl.<init>(QueryImpl.java:235) at lucee.runtime.tag.Query.executeDatasoure(Query.java:1134) at lucee.runtime.tag.Query._doEndTag(Query.java:699) at lucee.runtime.tag.Query.doEndTag(Query.java:565) at adminusers_cfm$cf$ec.call(/AdminUsers.cfm:854) at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:1003) at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:926) at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:217) at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:44) at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2460) at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2450) at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2421) at lucee.runtime.engine.Request.exe(Request.java:45) at lucee.runtime.engine.CFMLEngineImpl._service(CFMLEngineImpl.java:1179) at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:1125) at lucee.loader.engine.CFMLEngineWrapper.serviceCFML(CFMLEngineWrapper.java:97) at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:51) at javax.servlet.http.HttpServlet.service(HttpServlet.java:590) at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74) at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129) at org.cfmlprojects.regexpathinfofilter.RegexPathInfoFilter.doFilter(RegexPathInfoFilter.java:47) at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68) at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68) at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117) at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at runwar.Server$1.handleRequest(Server.java:510) at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52) at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:280) at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79) at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134) at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131) at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:260) at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79) at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100) at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387) at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852) at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35) at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019) at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558) at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449) at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280) at java.lang.Thread.run(Thread.java:750)
TagContext	
Array
1	
Struct
codePrintHTML	
string	852: current_timestamp<br> 853: )<br> <b>854: &lt;/cfquery&gt;</b><br> 855: &lt;cfquery name=&quot;logit&quot; datasource=&quot;uam_god&quot;&gt;<br> 856: insert into user_access_log (<br>
codePrintPlain	
string	852: current_timestamp 853: ) 854: </cfquery> 855: <cfquery name="logit" datasource="uam_god"> 856: insert into user_access_log (
column	
number	0
id	
string	??
line	
number	854
Raw_Trace	
string	adminusers_cfm$cf$ec.call(/AdminUsers.cfm:854)
template	
string	/usr/local/webroot/AdminUsers.cfm
type	
string	cfml
type	
string	database
where	
string

**Comment by dustymc** [comment]
fixed, in production
