### ISSUE TITLE
Add alternate terms to controlled vocabularies for increased discoverability

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4773]
Different communities use specific vocabularies for things that are exactly or almost exactly the same thing. We have quite a few open code table clean-up issues related to this. For example:

https://github.com/ArctosDB/arctos/issues/3189
and a whole lot of stuff in here https://github.com/ArctosDB/arctos/issues/3708

Perhaps we should be thinking more like @jhpoelen and just accept that this will always be true and that while we can create normalized controlled vocabularies, people coming to search will likely use whatever term they are comfortable with. During Code Table Committee today, we took a look at life_stage and [how GBIF handles it](http://rs.gbif.org/vocabulary/gbif/life_stage.xml). Notice that they have a pretty slimmed down, but very well defined list of terms for life_stage, but also notice that for almost all of the terms there is one or more alternative terms. We discussed adding this functionality to the parts and life_stage code tables to help us close some our issues related to them.

With regard to parts, this would allow us to add "skeleton" as an alternate term for all of the individual bone parts and all of the individual bone parts as alternatives to skeleton, helping anyone looking for skeletal material find what they want. We discussed adding functionality so that searching could be exact, or make use of the alternative terms for a broader sweep.

I've essentially already created [a scenario for this with life_stage](https://github.com/ArctosDB/arctos/issues/2881#issuecomment-1158179904). If we can agree that this might be a good path to take, we could do similar work for parts and perhaps other code tables as well.

**Comment by dustymc** [comment]
For clarity: I think parts and life stage is a good place to start, but adding "search terms" or "alternative terms" or whatever it's called to all CTs seems like a worthy goal. https://arctos.database.museum/info/ctDocumentation.cfm?table=ctsex_cde#female --> hembra would likely help some users, for example.

And for completeness: We recognize that this isn't some Real Solution (like an ontology or other more structured approach might hope to be), but it would increase accessibility, perhaps ease discussions involving potential new values, and it is something that we could accomplish relatively quickly.

**Comment by Jegelewicz** [comment]
Working Group says let's do this as "alternate terms" (other languages, etc.).

**Comment by Jegelewicz** [comment]
@dustymc can we do this?

**Comment by dustymc** [comment]
I can't find a way to make this performant (at test), perhaps it needs something like https://github.com/ArctosDB/arctos/discussions/6524

**Comment by dustymc** [comment]
This performs fine with https://github.com/ArctosDB/arctos/issues/6823 (keyed parts code table carrying the search term), which will be available in next release. I'm not sure how or if that'll scale to attributes, which are one layer deeper.

**Comment by Jegelewicz** [comment]
headgear....hehehe also - how old are you?

I have been wanting this setup for YEARS!
