### ISSUE TITLE
Taxonomy Search Results do not show if WoRMS (via Arctos) metadata shows "accepted" or "not accepted"

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#4777]
**Describe the bug**
The metadata for WoRMS (via Arctos) has recently changed to show exactly (and completely) what is in the WoRMS entry.  This has eliminated the taxon status override of "valid" for "accepted" and "invalid" for "unaccepted."  The Search function no longer shows the status per WoRMS (via Arctos)

**To Reproduce**
Here is an example of a search for the genus Tomelasmus

<img width="780" alt="Screen Shot 2022-06-20 at 8 56 17 AM" src="https://user-images.githubusercontent.com/15368365/174630124-a3573b20-d246-4f19-bd25-410cdf23c377.png">

Expected behavior**
The Arctos and the WoRMS (via Arctos) should both show the taxon status - accepted, unaccepted, etc. for WoRMS (via Arctos) and valid, invalid, etc. for Arctos.  

**Screenshots**
See above screen shot

**Desktop (please complete the following information):**
iOS, Chrome

**Priority**
Please assign a priority-label. Not high priority but the current code hasn't caught up with the other changes in the taxonomy module.

**Comment by dustymc** [comment]
The 'show...' widget should just be removed - there's nothing predictable in the data, and I don't think we have the CPU to do what we've done with data entry in a public form (especially that one, it's most of our traffic).

**Comment by sharpphyl** [comment]
So you're going to switch taxonomy search results over to the same format as the display of scientific name in single-record data entry?  Or just remove "taxon status" from this search?

**Comment by dustymc** [comment]
>going to switch taxonomy search results over to the same format as the display of scientific name in single-record data entry?

I don't think there's a more-compact format that shows whatever some particular user might be interested in, but I don't think we have the resources to support such a thing either.

>Or just remove "taxon status" from this search?

Simplest and cheapest would be removing the ' [ Show Metadata ] ' thing altogether, but perhaps we can find something else that's more workable. Tell me what you need and I'll see if I can find a way to do that....

**Comment by Jegelewicz** [comment]
I'll put it up for discussion in Taxonomy Committee. I have thoughts, but they are not productive right now.
