### ISSUE TITLE
[CONTACT]duplicate project

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#4782]
@dustymc Can we get rid of this Open Wings [project](https://arctos.database.museum/project/10002980) which is a duplicate of https://arctos.database.museum/project/10003264. The duplicate only has Brant Faircloth and he's also listed on the other project. I added the award numbers from the first project to the second one, since they were missing there. Thanks.

**Comment by dustymc** [comment]
Yes please - @campmlc can move stuff and then the duplicate can be deleted.

**Comment by Jegelewicz** [comment]
I took care of the MSB stuff.

**Comment by dustymc** [comment]
Thanks, from there you can just remove any agents...
<img width="734" alt="Screen Shot 2022-06-21 at 4 49 18 PM" src="https://user-images.githubusercontent.com/5720791/174914814-237ce8a6-902a-4577-a151-ee747c47394c.png">
.. save, and click the new button

<img width="169" alt="Screen Shot 2022-06-21 at 4 49 28 PM" src="https://user-images.githubusercontent.com/5720791/174914836-84a3ba44-dcb0-4d9c-a0cd-4f993541aa4c.png">
