### ISSUE TITLE
Feature Request - install unaccent

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4783]
**Is your feature request related to a problem? Please describe.**

 It's occasionally useful to ignore accents and diacritics and such.

**Describe what you're trying to accomplish** 

https://github.com/ArctosDB/arctos/issues/2874, but this could be useful for lots of searches, perhaps could even allow relaxing some rules.

**Describe the solution you'd like**

Install https://www.postgresql.org/docs/current/unaccent.html, build stuff (probably mostly trigram indexes) to use it

**Describe alternatives you've considered**

-

**Additional context**

Needs coordinated with @lkvoong re backups/copies.

**Priority**

This would be new functionality, I don't have time to dive in at the moment, the really cool possibilities would take some time to develop, probably relatively low.

**Comment by Jegelewicz** [comment]
Using non-ASCII characters is nice BUT in every csv download, they come out crazy in Excel (which is how a lot of us will open them). I found this solution

1. On a Windows computer, open the CSV file using Notepad.
2. Click "File > Save As".
3. . In the dialog window that appears - select "ANSI" from the "Encoding" field and "All Files (*.*)" from the Save as type field. Then click "Save".
4. . That's all! Open this new CSV file using Excel - your non-English characters should be displayed properly.

And I am wondering if we can get downloads in ANSI format for Excel? In other words, could we have choices in the format of downloaded data?

**Comment by Jegelewicz** [comment]
You can just say no.

**Comment by dustymc** [comment]
Tabling; might be reconsidered in context of https://github.com/ArctosDB/arctos/discussions/6524
