### ISSUE TITLE
Feature Request - results summary - can we get suborder added?

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#4786]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

The parasitic lice have been subsumed into the free-living order of bark lice. Now, to find and work with parasitic lice data in Arctos we need to use suborder instead of order (and the parasitic lice belong to multiple suborders). Thus, I want to be able to search on the order name 'Psocodea' and get a list of all the free-living and parasitic lice (of Alaska) from which I can easily extract the parasitic ones if I can see their suborders.

**Describe the solution you'd like**
How might we accomplish your goals?

add 'suborder' to the list of choices in the catalog record summary group by tool.

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.
Medium

**Comment by dustymc** [comment]
I'll go next task, I know how to do this.

This will involve rebuilding the private and public caches and the things that feed them - would be good to merge any other such updates into this. 

I could (as always) use help prioritizing.

**Comment by Jegelewicz** [comment]
Also part of #5324
