### ISSUE TITLE
Code Table Request - add cultures to ctculture

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#4790]
I need to add the following cultures to ctculture

Tagish; Arc/EH; First Nations tribe of Yukon, Canada; see also https://en.wikipedia.org/wiki/Tagish
Tahltan; Arc/EH; First Nations tribe of northern British Columbia, Canada; see also https://en.wikipedia.org/wiki/Tahltan
Kaska; Arc/EH; First Nations tribe of northern British Columbia and southeastern Yukon, Canada; see also https://en.wikipedia.org/wiki/Kaska_Dena

Thank you!

**Comment by Jegelewicz** [comment]
Added - it'll probably take a few hours before you can use them!
