### ISSUE TITLE
Reporter Cache seems slow...

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#4795]
I'm trying to print a [loan ](https://arctos.database.museum/Loan.cfm?action=editLoan&transaction_id=21133729)and am waiting for the specimen conditions to update in my [loan invoice](http://reports.arctos.database.museum/reporter/reporter.cfm?action=edit&report_id=5601092&auth_key=7A8320A7-3124-4C33-9D3BE5938A6D97CE). Recently edited conditions have already updated/display correctly in the catalog record (from "unknown" to the specific condition recorded when I pulled each specimen this morning), but my loan invoice condition fields still display as "unchecked" even after an hour of constant refreshing.

Usually the condition updates more or less immediately on the invoice form. Trying to get this loan out today...
[Oddly, I edited sex attributes at the same time as I did conditions for these specimens, and these data have pulled through to the invoice just fine, so the invoice is live-updating, just not for part_condition]

![image](https://user-images.githubusercontent.com/11336485/176512024-bcf9114f-4d7c-48fa-9ddb-ae1baf1d4841.png)

![image](https://user-images.githubusercontent.com/11336485/176511897-a189cde9-e3da-4efa-a6e1-8c2dade267b1.png)

**Priority**
high

**Comment by ebraker** [comment]
just edited, sorry!

**Comment by dustymc** [comment]
Maybe you edited the wrong thing, or have something mapped wrong in the report, or maybe Arctos isn't mapping something right somewhere?? All of those seem to really have condition 'unchecked' but there's condition-like data in part remarks.

**Comment by ebraker** [comment]
Oh my, I see what I did. Ignore me...
