### ISSUE TITLE
Code Table Request - Add hallux length and middle toe length to Attribute Table

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#4798]
**How to Use This Form**
This is a template with examples and guidance on how to best communicate with the Arctos Working Group. Please delete this section along with anything in square brackets ```[ ] ``` below before submitting. 

[ **Instructions for reference:** ]
[ Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html ]

[ Code Table Documentation is https://handbook.arctosdb.org/how_to/How-to-Use-Code-Tables.html ]

[[Video Tutorial - Submit a Code Table Request](https://youtu.be/t2jHbsRA3lk)]

**Goal**
We have some hallux lengths and middle toe length data to add. 
**Context**
There are no digit length options

**Table**
Attribute_Type 

**Proposed Value**
hallux length
middle toe length

**Proposed Definition**
hallux length - measured from base of Digit I on hind limb to base of claw
middle toe length - measured from base of Digit III on hind limb to base of claw

**Collection type**
Bird and Teach

**Attribute data type**
number + units

**Attribute value**
NA

**Attribute units**
numeric units as for other measurements: mm, in, ft

**Available for Public View**
yes

**Other ID BaseURL**
[  For OtherIDs, provide the following *or* explain why the unresolvable ID type is necessary:
1. "Base URL" with which to prepend entered values, and
2. A functional example URL, which should consist of the base URL provided in (1) plus a relevant value.  ]

**ID_References**
[  If the request involves https://arctos.database.museum/info/ctDocumentation.cfm?table=ctid_references, the changes must be coordinated with the Database Admin team for notifications to function.  ]

**Priority**
[  Please choose a priority-label to the right.  ]

**Comment by mvzhuang** [comment]
any comments welcome on name and definition from bird collections people!!! @ewommack @ccicero

**Comment by Jegelewicz** [comment]
added
