### ISSUE TITLE
Delete Project?

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#4800]
@dustymc can you please delete project: https://arctos.database.museum/project/10003907?

We realized we already have a duplicate project https://arctos.database.museum/project/10003918 for several loans associated with UCM, UMNH, MVZ, MSB and want to consolidate. @cjconroy has moved his loan items out of 10003907 but can't delete it.

**Comment by dustymc** [comment]
Done - you can just remove everything and then delete it.

<img width="1121" alt="Screen Shot 2022-06-30 at 10 59 23 AM" src="https://user-images.githubusercontent.com/5720791/176746072-8f84cc16-49b2-4aad-9532-0fbb109cdb0c.png">
<img width="200" alt="Screen Shot 2022-06-30 at 10 59 34 AM" src="https://user-images.githubusercontent.com/5720791/176746103-78e941bc-c421-49ca-b522-4fdff6a7ad91.png">
<img width="240" alt="Screen Shot 2022-06-30 at 10 59 43 AM" src="https://user-images.githubusercontent.com/5720791/176746124-97879448-da6f-4a24-b041-a4c19e266044.png">
