### ISSUE TITLE
Need Help with Arctos Error: Cloning Record

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#4801]
# Error Text
cloning failed: fail: ERROR: column "collection_id" of relation "bulkloader_for_download" does not exist
Position: 61 

# Where it happened
I'm trying to [clone this record](https://arctos.database.museum/guid/CHAS:Herb:E2022B.31) using option two so it will appear in the bulkloader.

# Steps to get there
"Other IDs" - "[Clone this Record]"

# Problem
Error states that something does not exist. Am I doing something incorrectly or is this an internal issue?

# Solution
??

**Comment by Jegelewicz** [comment]
@wellerjes Dusty is on vacation until July 17. I imagine he will peek in - he seems to have trouble staying away, but if you cannot wait that long, maybe try another method?

**Comment by wellerjes** [comment]
I tried cloning the record again and am getting a new error:
cloning failed: fail: ERROR: column "collection_id" is of type integer but expression is of type character varying Hint: You will need to rewrite or cast the expression. Position: 33

**Comment by dustymc** [comment]
I'm still not entirely sure what's different but I hard-nuked everything and rebuilt from the ground up, this is working for me in production. Please confirm and close.

**Comment by wellerjes** [comment]
It's working. Thanks!

**Comment by wellerjes** [comment]
New (related) issue: once the record goes through the loader, the GUID changes.

I'm trying to move a botany specimen from the herbarium collection ([this specimen](https://arctos.database.museum/guid/CHAS:Herb:1968.26.1)) to the teaching collection by cloning the record and updating the catalog number and GUID in the bulkloader.

Here it is with the correct information in the bulkloader:
![image](https://user-images.githubusercontent.com/93737929/181360681-c76d0cab-0418-45b7-b350-087e4cd30fb8.png)

And here's the link to the catalog record that it created: https://arctos.database.museum/guid/CHAS:Herb:E2022B.31

**Comment by dustymc** [comment]
Thanks, I see what's going on, I need to rebuild some core code so this will have to be part of a full release. I'll get it as soon as I can.

**Comment by wellerjes** [comment]
Thank you!

**Comment by dustymc** [comment]
Patched for next release, tested with sting-number collection cross-collection clone, pushing the most coreward code off to https://github.com/ArctosDB/arctos/issues/4257

**Comment by wellerjes** [comment]
Thanks! What's the estimated timeline for the next release?

**Comment by dustymc** [comment]
If you're in a rush I think I can patch it in today without noticeable interruption, if its OK I'd prefer to wait until early next week when I'll be around to watch things the day after.

**Comment by wellerjes** [comment]
Early next week will work. Thanks!
