### ISSUE TITLE
[CONTACT: Blocked Network]

### ISSUE THREAD

**Issue by camwebb** [ArctosDB/arctos#4802]
restricted IP: 69.161.16.16

**Comment by camwebb** [comment]
Thanks @Jegelewicz, but no, still blocked. This is an IP for the major telco in Alaska - ACS (alaskacommunications.com). 

Related: I very frequently spend several minutes finding a way to reach Arctos - so many IPs I use are blocked. And then I need to find and delete the CFID cookie if I have previously tried from a blocked IP. Is the security risk really worth the significant inconvenience users experience trying to access Arctos?  Has the IP Blocking policy been revisited recently?

**Comment by Jegelewicz** [comment]
Well, I think I have exhausted my options - It looks like it is active to me, but I am kinda guessing at what to do. @mkoo is there anyone else who knows what to do?

**Comment by camwebb** [comment]
@mkoo Thanks! Works now. 

> You can usually unblock yourself too although there may a little delay.

I don't have the required Arctos permissions, I'm afraid. 

Is there any likelihood that the IP Blacklist policy might ever be reconsidered and liberalized? It certainly makes Arctos less friendly to use.
