### ISSUE TITLE
Mineral taxonomy - rock names should NOT be capitalized?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4804]
All of the rock and mineral names in Arctos are proper case, but I have now been advised by @mschmidtjr that they should be lowercase. See also

https://www.mindat.org/mesg-336825.html

Which essentially says that the IMA rules are no capitalization unless the first word of a sentence or part of a named place.

But Look at this? - https://www.minerals.net/mineralvarieties.aspx

And this - https://en.wikipedia.org/wiki/List_of_minerals

And this - published by the IMA! - http://cnmnc.main.jp/IMA_Master_List_%282022-07%29.pdf

Do we follow the stated rule or follow the actual actions of the IMA? It seems to me that an identification is just like the names in the approved mineral list - sort of the first word in a sentence, and therefore our terms should be capitalized, but I am open to making them all lowercase if that seems more appropriate. Looking for other opinions.

@Nicole-Ridgwell-NMMNHS @aklompma 

Should we add [The Commission on New Minerals, Nomenclature and Classification (CNMNC)](http://cnmnc.main.jp/) as a nomenclatural code? See http://cnmnc.main.jp/cnmmn98.pdf

**Comment by Jegelewicz** [comment]
Throwing this here for my reference:

> The existing names of mineral varieties such as amethyst, kunzite, etc., which are not regarded as species, do not come under the jurisdiction of the CNMMN, and are therefore unregulated. The introduction of new varietal names, however, is to be discouraged, as it tends to create confusion in the mineralogical literature.

Note: I have treated these as varieties and the names indicate what of, so Amethyst in Arctos is Quartz var. Amethyst. Is everyone OK with this formatting?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Yes, that formatting is good with me.

**Comment by dustymc** [comment]
Yikes. Is there something like a Code for any of this, and assuming so can we find someone familiar with it to help set the rules? This is really fundamental stuff, the current rules are REALLY loose, if there's any way we can establish "correct" then we should before we have an even bigger mess to extricate ourselves from.

>and are therefore unregulated.

Then not taxonomy and should be removed, no? Similar situations in Linnean land are definitely not "names" but as above guessing and hoping isn't a great way to tackle this....

**Comment by Jegelewicz** [comment]
> Is there something like a Code for any of this

And this - published by the IMA! - http://cnmnc.main.jp/IMA_Master_List_%282022-07%29.pdf

but apparently do not follow their own code?

**Comment by dustymc** [comment]
> apparently do not follow their own code?

We should not pretend that informal data is something else, ever, for any reason; doing so risks poisoning the whole well. If someone wants to DO STUFF that requires formal data then they can help us find a place for it, if nobody cares then we can [easily accommodate that](https://arctos.database.museum/name/unidentifiable).

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
From the IMA document: "Mineral names are common nouns, and thus have an
initial capital letter only at the beginning of a sentence, or when they occur in an index or in a table, as in the current list"

**Comment by Jegelewicz** [comment]
Soooo - we should capitalize them in Arctos? Taxonomy is just a list of names, but what about identifications?

**Comment by mschmidtjr** [comment]
Though I'm the one who first brought up that mineral and rock names aren't
capitalized, and still say that's true in a sentence, I'm seeing them
capitalized so often when they stand alone in indexes, tables, and lists,
that I'd say go ahead and capitalize them in Arctos identifications, as you
suggested earlier.  Here's an example where they're not using genus/species
names, so not capitalizing fish names in the 2nd paragraph, yet the same
names & all others are capitalized in the list farther down the page

https://www.chesapeake-bay.org/index.php/chesapeake-bay-information/fish-fishing/#:~:text=Sport%20Fish,%2C%20cobia%2C%20and%20Spanish%20mackerel
..
So stand-alone mineral & rock names can be capitalized as identifications.
They will remain lowercase in my verbatim comments/remarks, which are more
like sentences anyway.  At this point, I'll also support capitalization to
keep mineral and rock names as important as animal & plant names that are
capitalized - fair treatment!!   And always capitalize our important Earth
when you mean the planet, regardless of what English (english? - see?  it
changes the importance!) teachers say!

**Comment by Jegelewicz** [comment]
Thanks @mschmidtjr ! Closing
