### ISSUE TITLE
Attribute determined date inconsistency

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4812]
When adding attributes directly in a catalog record, determined date is NOT required. When adding attributes via the bulkloader, all attributes without a date get the following error and the record will not load:

ATTRIBUTE_DATE_1 is invalid

If the date is not required, this error should not occur. If is is required, then editing a catalog record should not be allowed without it.

**Comment by dustymc** [comment]
Agree, anything that's not structurally required should be allowed (until and unless we can find some way to implement https://github.com/ArctosDB/arctos/issues/4384). 

Going next task on the assumption that this universally is agreed.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/4184
