### ISSUE TITLE
Bulkload common names

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4815]
@dustymc when you're back - can you load these common names? Also, maybe just build a little component loader?

Thanks!

[Mineral no special char common names.csv](https://github.com/ArctosDB/arctos/files/9093947/Mineral.no.special.char.common.names.csv)

**Comment by dustymc** [comment]
Suggest this be killed - there are a bunch of issues which suggest the current common name model isn't satisfactory.

**Comment by Jegelewicz** [comment]
@dustymc until that gets worked out, can these be loaded and this issue closed?
