### ISSUE TITLE
Error when resetting password

### ISSUE THREAD

**Issue by awilkins007** [ArctosDB/arctos#4818]
I recently had to reset my password. However, whenever I try to login with the temporary password all I get is error messages saying authentication error. I've triple check both my username and temporary password. Is the error happening because I tried logging in to many times or some other issue?

** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **

** Outages should be reported to the contacts listed at https://arctosdb.org/arctos-down/ **

** Arctos Documentation is http://handbook.arctosdb.org/ **

** Learn more about Arctos at https://arctosdb.org/ **

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **

**Comment by Jegelewicz** [comment]
Looks like too many attempts with a bad password. I've reset that - maybe try again?

**Comment by awilkins007** [comment]
Still no working even when I either try to copy and paste the updated password or type it out.

**Comment by awilkins007** [comment]
Never mind I just reset my computer and now its working?
