### ISSUE TITLE
Feature Request - Agent Review Tool

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4820]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
See the many issues related to low quality agents. I regularly stumble upon two agents that are likely the same person, but reviewing their activity means a whole lotta clicking and back and forthing between the agent activity pages.

![image](https://user-images.githubusercontent.com/5725767/178851868-d5d21d79-4d0f-468a-801a-28566e82d5c5.png)

**Describe what you're trying to accomplish** 
Easily compare two agents

**Describe the solution you'd like**
I select two agents and see their agent activity pages side by side.

![image](https://user-images.githubusercontent.com/5725767/178852978-d87c30ab-d0ef-4a7b-9309-6d325d19af6e.png)

**Describe alternatives you've considered**
Little summaries as in the [low quality data tool](https://arctos.database.museum/info/dupAgent.cfm). But my conclusion is that I need to see all of the activity to make a proper assessment. Also, I can't just "get" the two agents I've stumbled upon in the tool.

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/4554 would offer what I think would be a solution, where this looks to me more like a way to view symptoms.

I regularly do this by opening more browser windows.

I'm definitely not opposed to a multi-column view if none of the above sufficiently addresses this.

**Comment by Jegelewicz** [comment]
Also a way to compare the activity of a verbatim agent to an agent to determine if they are the same person.

**Comment by Jegelewicz** [comment]
@dustymc says wait until after the Agent cleanup.

**Comment by dustymc** [comment]
Probably better to include verbatims rather than separate apps - users may not know/care.

elastisearch or similar might make this easy, esp. digging around in verbatim for similar names.

revisist after The Great Verbatim Purge

**Comment by Jegelewicz** [comment]
> The Great Verbatim Purge

Has happened some tools for comparing agents and verbatim agent activity would be super useful.
