### ISSUE TITLE
Larry can't login

### ISSUE THREAD

**Issue by KyndallH** [ArctosDB/arctos#4821]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

Larry: Tried to log onto arctos and the password that I recently changed was not working and it says "Authentication failed. Additional information. Authentication failure." I then went through the "Lost your password?" steps twice, but in the past two hours, I have not received any emails. So at this point I can not log on. I do have two accounts and we can not seem to remove the extra one. So we are not sure if that happens to be the cause or not. But as of yesterday there was no problem with me logging on. 

**To Reproduce**

**Expected behavior**
Login into Arcots. Recieve email with reset password.

**Screenshots**

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**
This is Larry's last day. Of course, it happens on the last day.

**Priority**
ASAP - URGENT. Got to get all the work we can out of him on his last day.

**Comment by KyndallH** [comment]
lpallozz

**Comment by msbparasites** [comment]
I am having the same problem, but when I asked for new password, I did get an email, but that password didn't work either, said "Authentication failed. Additional information. Authentication failure.". I tried this on different web browsers and same response.

**Comment by Jegelewicz** [comment]
@mkoo

**Comment by mkoo** [comment]
thanks for sending the username @Kyndall Hildebrandt ***@***.***>

the problem for larry may stem from having two accounts with the same
email.  1) lpallozz is the operator 2) lpallozzi (has i at end) is not.

Try changing the email for lpallozzi to something different (or send me a
different one to update for you) and then try logging into lpallozz (no i)

**Comment by KyndallH** [comment]
I can't change his email... most likely because he has two logins (or I think that is why I can't edit it).

<img width="1941" alt="Screen Shot 2022-07-14 at 12 24 41 PM" src="https://user-images.githubusercontent.com/16887896/179076840-c63ce543-3d04-405d-ba0a-2fb4101821cd.png">

**Comment by mkoo** [comment]
Kyndall, do you know an alternative email for him? I can just see if I can
edit it with one of ours....

**Comment by mkoo** [comment]
can you try to log into lpallozz (no i at end)?

**Comment by KyndallH** [comment]
It worked! Thanks!
