### ISSUE TITLE
Agent Split Request - Annie Johnson

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#4822]
Use this template if you believe an agent represents more than one person or organization.

**Agent that represents more than one person or organization**
https://arctos.database.museum/info/agentActivity.cfm?agent_id=21280898

**New Agent**
I have no information on Annie Johnson, but her name came up while the Agent Committee was reviewing agents. According to Annie Johnson's Agent Activity sheet she collected and created material from 1700 - 2000s. I believe that there may be two Annie Johnsons that lived in different centuries.

 - **Agent preferred name:** 
 As listed: Annie Johnson
 - **Agent details:**
 Only information in the Agent's page is the following remark: UAM ethnology

**Reason for split**
Annie Johnson created several objects in the 1700s that are stored in UAM:EH, and then she also collected and prepared 24 mammals in the UAM:Mamm collection in the 2000s. I believe that there may be two different Annie Johnson's that have lived in Alaska in different centuries. 
I will not do anything to the agent, but wanted to bring this to the attention of the affected collections.

**Affected Collections**
Please list the collections that will be affected and would use the new agent. If possible provide Github usernames for those who might have an interest in the split.
UAM:EH - @AJLinn 
UAM:Mamm - @amgunderson

**Comment by AJLinn** [comment]
Thanks for this. 
Our Annie Johnson is a Yup'ik woman from the SW Alaska village of Quinhagak. I'll create a new record for her and move the one object over to that record. She's actually a 20th century skin sewer, not from the 1700s. I think I found her on Ancestry.com.

When we moved our collections into Arctos we never used a begin/end date for our events - we had ca., or pre- dates or something definitive. We had to arbitrarily decide a begin date for all of our collections so we picked 1700 for a "modern Alaska Native culture" date range. Now we have to go thru and change those every time we come across one that is definitely wrong. Blergh.
