### ISSUE TITLE
Part Bulkload: part_attribute_determiner ignores entered field and enters person loading file

### ISSUE THREAD

**Issue by KyndallH** [ArctosDB/arctos#4824]
Bulkloader file:
<img width="1779" alt="Screen Shot 2022-07-14 at 12 22 17 PM" src="https://user-images.githubusercontent.com/16887896/179077050-6e564d8c-b597-48bd-86d3-dd15a432f9c0.png">

When loaded, it defaults to me instead of what was entered into the bulkloader file:
<img width="1534" alt="Screen Shot 2022-07-14 at 12 22 23 PM" src="https://user-images.githubusercontent.com/16887896/179077095-bbba851f-b348-4b70-be84-d70f1ac2b156.png">

**Comment by KyndallH** [comment]
Well, at least it keeps the date correct! :)

**Comment by Jegelewicz** [comment]
And you get all the credit!
