### ISSUE TITLE
Cannot login with current or new password

### ISSUE THREAD

**Issue by msbparasites** [ArctosDB/arctos#4826]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I tried to login with my password, it failed each time and said: Authentication failed. Additional Information: Access restricted. I requested a new password, this morning I got an email right away, that password didn't work. Now this afternoon I requested another password and that one does not work either. I thought it was related to Issue #4821, but that one was resolved, and was I did not create a new account.

**To Reproduce**

**Expected behavior**
I expected my password to work, and then I expected the temp password to work. Neither does.

**Screenshots**

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**
 -  iOS
 - Browser: tried chrome and safari]

**Additional context**

**Priority**
*ASAP* as I have waited all day to get something done and cannot progress without it, need to assign catalog numbers to a research for a publication.

**Comment by Jegelewicz** [comment]
What is your Arctos username?

**Comment by msbparasites** [comment]
sara

**Comment by Jegelewicz** [comment]
I just reset your password - let me know if you get an email and if that let's you change your password.

**Comment by msbparasites** [comment]
It has been about 30 minutes, but no email yet.....let me know if it could take a while.

**Comment by Jegelewicz** [comment]
Maybe just try to log in and see what happens?

**Comment by msbparasites** [comment]
Still the same response

**Comment by Jegelewicz** [comment]
I'm sorry, that's all I've got. Maybe @mkoo can help. I have access to the MSB:Para collection - if I can do something for you, I'm happy to help!

**Comment by msbparasites** [comment]
UUGGHHH!!! Ok thanks so much. No what I need to to enter a bunch of stuff, but I have to do it record by record and reconcile it with some other notes....

**Comment by Jegelewicz** [comment]
@msbparasites Want me to come over, log in and let you work?

**Comment by Jegelewicz** [comment]
Actually - look for an email from me with a password, once you have it, try logging in as arctostester

**Comment by Jegelewicz** [comment]
Well nevermind - that only works in test....

**Comment by msbparasites** [comment]
I will be in about 945 or so, let me know if we can meet.....THANK YOU

**Comment by Jegelewicz** [comment]
OK - here is what worked.

1. We turned off the auto username/password entry function in Firefox
2. Reset the user account (sent a temporary password and mail worked YAY!)
3. Used the temp password to login! YAY!!!
4. Changed the user's password.

So it seems like the autofill in the browser is somehow overriding whatever is typed in? I'm not sure why, but that seemed to be the problem...

**Comment by mkoo** [comment]
Hi all! sorry for the delay-- ok that makes sense and I was going to ask if
there was a password manager in play but maybe just browsers trying to be
"helpful" is the issue.
thanks for the note on what works!

**Comment by Jegelewicz** [comment]
One thing I didn't mention - I had to wait until the user reached the max number of attempts to log in (11) in order to reset their password. I don't know if they had requested a new password after turning off the autofill feature would work just as well (people could fix this themselves).

**Comment by msbparasites** [comment]
I just removed autofill on two other computers, both Firefox and Chrome, and was able to login!!
