### ISSUE TITLE
attribute sex case in-sensitive?

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#4830]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Didn't realize sex was case sensitive. Just loaded over 400 records and now all have error ATTRIBUTE_1 is not valid. 

**Expected behavior**
Would be great if it would accept Female, or female. Possible?

Any way, other than one-by-one to fix this?

**Priority**
Medium.

**Comment by Jegelewicz** [comment]
Are they sitting in the bulkloader?

**Comment by cjconroy** [comment]
Yes, but I am going through one by one and changing F to f, and M to m.

**Comment by Jegelewicz** [comment]
You can use the SQL button to change them all.

**Comment by Jegelewicz** [comment]
I can't see your stuff, or I'd make an example - but you'll need to filter Attribute_1 for Female, then update all to female, then do the same for Male. I think that should work if they are all in Attribute 1.

**Comment by Jegelewicz** [comment]
@dustymc maybe this is something that should get caught at first load?

**Comment by cjconroy** [comment]
Thanks. I am looking at the SQL page. I can't seem to use the drop down to get to Attribute 1. But, I am making fine progress doing it the hard way. Will be done soon enough. 
<img width="468" alt="Screen Shot 2022-07-15 at 3 35 29 PM" src="https://user-images.githubusercontent.com/5749672/179320600-c2fe7419-094f-43b2-8a5f-7bfe52473776.png">

**Comment by Jegelewicz** [comment]
You can always download - use Excel to change and re-upload - but if manual works for you, then awesome! Sometimes I do things that way too...

**Comment by dustymc** [comment]
>something that should get caught at first load?

It already is?

>can't seem to use the drop down 

https://github.com/ArctosDB/arctos/issues/4229#issuecomment-1187752228

Tentatively closing - let me know if I can update something (or whatever).

**Comment by Jegelewicz** [comment]
>     something that should get caught at first load?
> 
> It already is?

Apparently not, because @cjconroy was able to load "Female" and "Male"...
