### ISSUE TITLE
Code Table Request - UTM zones to add

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#4832]
**Goal**
I've finally got the bulk edit locality file ready so that we can load all our UTM data and have it convert to lat/long. The only thing holding me up is that a bunch of the UTM zones need to be added.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctutm_zone

**Proposed Value**
11T
12T
14R
14S
15S
16S
17S

**Comment by dustymc** [comment]
Go for it (I think you have access?) - but do be REALLY careful in sorting out the SRID, it is functional and if you get it wrong the conversion to DD.dd will also be wrong.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Ok, thanks, I will triple check the SRIDs before I add them.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
done
