### ISSUE TITLE
geography hit list

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4837]
Gave up trying to sort, everything here's a mess of some form. If you fix something please EDIT this comment and move the fixed item to the bottom (or just delete). All of this needs fixed, but more importantly it should also guide policy/structure/whatever - eg I think we're drastically over-using island, we should have some official stance on the "dirt, but saltwater" messes (unless we're going to adopt some existing geography schema), etc., etc. 

HELP!

* https://arctos.database.museum/editGeog.cfm?geog_auth_rec_id=1005141 is real but most do not consider it a country
* Newfoundland doesn't exist - https://github.com/ArctosDB/arctos/issues/3018 or die
* https://arctos.database.museum/editGeog.cfm?geog_auth_rec_id=10006648 is obsolete 
* https://arctos.database.museum/editGeog.cfm?geog_auth_rec_id=10003832 - the Arctos entry contains the island of Cuba, neither wiki nor gadm has appropriate data and Arctos records seem to be going to the country, not the island. Can we drop island?
    * I think actually everything in Cuba has Cuba as an island because filling in the blanks is fun, not because of any intention to be precise. Entire country should be reviewed.
    * There is more than one island in Cuba (https://en.wikipedia.org/wiki/Isla_de_la_Juventud), so the Cuba entry in the Island field should be removed.  And didn't we agree that West Indies isn't a continent?
* https://arctos.database.museum/editGeog.cfm?geog_auth_rec_id=10004495 and https://arctos.database.museum/editGeog.cfm?geog_auth_rec_id=10003836 are probably the same (but neither had a useful source, I could have misinterpreted something)  

- * Yes, both are for the Isle of Pines (until 1978), now Isla de la Juventud (English: Isle of Youth). Authority: https://en.wikipedia.org/wiki/Isla_de_la_Juventud.  Getty places it in North America, not West Indies.  

* https://arctos.database.museum/editGeog.cfm?geog_auth_rec_id=10004457 and friends - Cyprus is split, everything's a mess
    * most/all of the Czech Republic is duplicated and badly translated and a general mess, needs focused attention 
* Democratic Republic of the Congo- all mess, desperately needs #3018
* https://arctos.database.museum/editGeog.cfm?geog_auth_rec_id=10009667 includes an island but I suspect the intention is the province, which extends beyond the island
* https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10005140 (mostly Christmas Island, which is neither of the listed components)
* https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=120 ("US minus Hawaii" - see https://github.com/ArctosDB/arctos/issues/3114#issuecomment-1171790423)
* https://arctos.database.museum/place.cfm?sch=geog&higher_geog=salton - I don't think the Salton counts as a sea, no matter the name
* https://arctos.database.museum/editGeog.cfm?geog_auth_rec_id=10000047 - extinct
* https://arctos.database.museum/editGeog.cfm?geog_auth_rec_id=10000048 - extinct
* https://arctos.database.museum/editGeog.cfm?geog_auth_rec_id=10000735 - extinct and/or mangled
* https://arctos.database.museum/editGeog.cfm?geog_auth_rec_id=10000740 - extinct
    * all of finland needs review
* https://arctos.database.museum/editGeog.cfm?geog_auth_rec_id=4956 is a mess, "France" doesn't stop at Europe, we for some reason insist on mixing political and geography, it's a mess (like US, which still isn't confined to NA).
* all of France is a random mix of departments, regions, cultural regions, etc.
* https://arctos.database.museum/editGeog.cfm?geog_auth_rec_id=10000799 is extinct
* https://arctos.database.museum/editGeog.cfm?geog_auth_rec_id=1005085 - extinct
* greenland without spatial is either old or invented
* Italy is an inconsistent mess
* https://arctos.database.museum/editGeog.cfm?geog_auth_rec_id=10007081 "Use this entry only for the country of Madagascar excluding the island of Madagascar, and only when no more-specific data are known." omg....
* Oaxaca is a mess in gadm, needs reviewed, find better source of info if possible

------------------

**Comment by Jegelewicz** [comment]
The first one definitely isn't real and the locality belonged in Colorado - that one is fixed.

**Comment by Jegelewicz** [comment]
https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10005689 was not in use - deleted

Who created the great lakes as counties?

**Comment by Jegelewicz** [comment]
https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10005691 used by one locality which was changed to Saint Clair County and this one deleted.

**Comment by Jegelewicz** [comment]
https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10005704 not in use - deleted

**Comment by Jegelewicz** [comment]
https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10005692 used by one locality, changed to Washtenaw County then deleted this.

**Comment by dustymc** [comment]
>Who created the...

I think probably Cornell, lots of fish and seems typical of their (cleaned!) data. 

I'm not finding a lot of new-ish-created in-use garbage, which is sorta comforting.

I am finding a lot of not-very-discoverable data. Maybe half the provinces of AF weren't as expected - some less-common transliterations (I think), but some seem to be plain old typos. 

There are lots of things that I may never successfully "translate" - some large part are [intersections](https://github.com/ArctosDB/arctos/issues/4836), but some countries just have placenames that don't much line up with our data and/or GADM (and friends).

Lots of "dirt, but oh yea saltwater" that I think should probably be nuked. 

Africa isn't a country.....

I'm tempted to just implement https://github.com/ArctosDB/arctos/issues/4755. It would make creating a little painful, but that must be orders of magnitude less work than dealing with this, and it would provide a lower limit on data quality.

>used by one locality, changed to 

In case I haven't been clear about this: For most of the US, working on the world - anywhere I have spatial geography - I can magic best geography fit. (I obviously can't tell if the coordinates are correct or not, a human would be ideal, but I find smallest-containing-shapes.) Lemme know if you have some use for that....

Thanks!

**Comment by Jegelewicz** [comment]
I'll let @sharpphyl and @mkoo look at the three bottom ones.

**Comment by ccicero** [comment]
@mkoo @Jegelewicz I changed https://arctos.database.museum/guid/MVZ:Fish:347 to 'captive' and fixed the georeference.

**Comment by dustymc** [comment]
I got what I could, this needs more work but calling it blocked by https://github.com/ArctosDB/arctos/issues/3018 - I've been putting that in remarks which is essentially wasted effort, remainder is going to take research, worth waiting on a formal place for the result of that.

**Comment by sharpphyl** [comment]
I'm working through several of these and commented on two on Cuba.  I don't think I have (nor do you want me to have) higher geography authority to modify the entry.  

> I'll let @sharpphyl and @mkoo look at the three bottom ones.  

@Jegelewicz Did you mean Oaxaca, Madagascar and Italy?  The order of the entries may have changed.

**Comment by Jegelewicz** [comment]
> Did you mean Oaxaca, Madagascar and Italy?

No - I think this list has changed since I commented? Not sure what I was looking at...

> didn't we agree that West Indies isn't a continent?

Nope - https://github.com/ArctosDB/arctos/issues/3043 was never resolved.

**Comment by dustymc** [comment]
>West Indies isn't a continent?

Then CAN we agree that West Indies isn't a continent (ditto https://github.com/ArctosDB/arctos/issues/4857, https://github.com/ArctosDB/arctos/issues/4852), and that [this abonination](https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10007081) (see remarks) can't make sense, and in general to drop the things that seem to only add confusion while prohibiting wiring this stuff up to spatial data?

**Comment by Jegelewicz** [comment]
> CAN we agree that West Indies isn't a continent

I agree - this should absolutely go away. I also don't really give a darn about the other three - make them whatever the rest of the world understands. But that's just one "agreement". Putting this on today's issues agenda.

**Comment by dustymc** [comment]
> rest of the world understands

That's a useful perspective. Anyone who much cares about places probably has about the same spatial data I do, if we do something that lines up with GADM and such we'll be sharing the same book, if perhaps not the same page. Or we could put a whole bunch of work into finding data for [things](https://github.com/ArctosDB/arctos/issues/4836) that nobody else will have data for and probably doesn't care about....

**Comment by dustymc** [comment]
This is mostly more intersection problems, merge-->https://github.com/ArctosDB/arctos/issues/4836

(The rest is temporal problems, https://github.com/ArctosDB/arctos/issues/3018)
