### ISSUE TITLE
[CONTACT] part preservation migration issue

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#4840]
@dustymc @cjconroy Chris pointed out an issue with the migration of part preservation. See https://arctos.database.museum/guid/MVZ:Fish:347

Remark states "Added from original part whole organism (100% ethanol); 100% ethanol."

Yet part preservation attribute is just 'ethanol' and not 'ethanol, 100%'

Not sure how widespread of an issue that is, but if the original part indicated a particular ethanol concentration, the new part preservation attribute should have the same value. 

Preservation attributes should be checked against the remark and fixed if there is a mis-match like this.

**Comment by dustymc** [comment]
Vaguely remember discussing this somewhere, I believe the consensus was that pure ethanol can't exist outside a lab and doesn't make sense.

I can find things from remarks and make more updates, but I still don't believe the concentration....

**Comment by ccicero** [comment]
I don't recall any such discussion and am not sure what you mean by 'can't exist outside a lab' - ? @atrox10 and @mkoo may know more about the fish preservation at MVZ, but Chris Martin claims that it's 100% ethanol.

**Comment by cjconroy** [comment]
It may not be 100% after a fish is dropped into it, but the important history is that preservation technique. It was not dropped into formalin, or isopropynol, or 70% ethanol. We can check with the curator to see if they pour off the ethanol and refresh with 100% ethanol.

**Comment by mkoo** [comment]
well, I dont think anyone is going to quibble about absolute ETOH at 100% or not (usually 100% etoh is so hydrophilic once opened it's becomes 99% or less -- that's why they add stuff like benzene...). But Chris' point is that the specimen remained formalin-free. (ok, I realize we are quibbling...)

is 95% etOH an option? (if so why not 100%? what happens afterwards is not relevant past the initial preservation of that particular field.) And yes, you can have stable 100% in a lab-- just dont leave the stopper off! Usually the stuff we buy says 95% etOH anyway to reflect this reality.

compromise suggestion= 95%

**Comment by ccicero** [comment]
We do have 'ethanol, 95%' as an option but the initial preservation according to Chris M. is 'ethanol, 100%' so that's what it should state. I don't think compromise is a reasonable solution here. The etoh that Chris buys is different from what we buy for the other collections.

**Comment by cjconroy** [comment]
I emailed Chris to see if he would like to weigh on this, since these are his specimens. No response yet.

**Comment by campmlc** [comment]
I agree with keeping 100% ethanol as a preservation. We purchase it in
bottles that are specifically lab grade 100% ethanol. We can't assess how
much water is absorbed after opening - that is irrelevant. The important
thing is documenting the initial concentration - no additives, it was not
diluted with tap water or distilled water, etc.

**Comment by campmlc** [comment]
Here is a useful summary
https://bitesizebio.com/13518/which-type-of-ethanol-should-i-use/
Note that 100% may contain residual benzene - another reason to document
its use.

**Comment by ccicero** [comment]
I agree with Mariel about the initial concentration being what's important. Same for other concentrations - we preserve in 70% etoh but can't guarantee that's the actual concentration in a bottle without checking it.

Carol made the important point that the initial concentration is key because someone needs to know what concentration to add. If the preservation says 70% or 95% or 100%, then that's what should be added as needed.

Here is the bottle of ethanol that Chris Martin purchases for preserving his fish. He does not dilute it. Yes, the actual concentration is likely <100% but that's irrelevant as Mariel said.

![200proof_etoh](https://user-images.githubusercontent.com/967275/180027396-c4e29424-5acc-4437-a286-d764fca4b2c1.jpg)

**Comment by dustymc** [comment]
Sorry, I lost this - done, here's pre-update data.

[temp_eth_100.csv.zip](https://github.com/ArctosDB/arctos/files/10263242/temp_eth_100.csv.zip)
