### ISSUE TITLE
Error on find localities by lat/long

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#4842]
**Describe the bug**
I don't seem to be able to search localities by lat/long.

**To Reproduce**
1. Go to Search Localities
2. Enter coordinates in DecLat and DecLong and select search precision 2 (NN.nn)
3. Click Find Matches

**Expected behavior**
Get search results.

**Screenshots**
![image](https://user-images.githubusercontent.com/47402809/179859657-4ac6fa69-bad2-4da9-bb5f-3660bfa91704.png)
![image](https://user-images.githubusercontent.com/47402809/179859687-e23af4e1-55d5-40e8-909c-216878a98d46.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 103.0.5060.114

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I was able to successfully search with search precision set to NN.nn, but now I am also getting an error with search precision set to round to integer:

![image](https://user-images.githubusercontent.com/47402809/182186062-a886a37a-75c3-4206-8709-cea9783c662d.png)

![image](https://user-images.githubusercontent.com/47402809/182186132-057b9fa1-47b6-435e-a6c0-c1583b2004f7.png)

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks!

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Search precision 4 (NN.nnnn), seems to work, but then when you look at the coordinates, the results are wrong. I searched for 36.018538, -106.008645, with search precision 4(NN.nnnn) and got this locality back as a result: https://arctos.database.museum/place.cfm?action=detail&locality_id=11108765. The latitude is correct, but the  longitude is not (-107.3500242926).

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I'm also getting latitudes from -105.98 (fine) to -107.62 (not fine) on precision 2 (NN.nn).

**Comment by dustymc** [comment]
should be fixed, there was a misscoped variable

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks!
