### ISSUE TITLE
Help needed generating data from Other ID list

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4843]
Request for help with flat data download including the following columns for each of the following files of Other Identifiers. I cannot use the standard interface as the number of requested records exceeds the standard search UI. I need these data to estimate how many tissues from MSB and UAM in MSB research freezers need to be linked to their catalog records.
Other Catalog Numbers
Collectors
Collecting Event ID
Parts
Part Detail
Specimen Remarks
Related Record Summary

[Research Freezer list-NKs.zip](https://github.com/ArctosDB/arctos/files/9145164/Research.Freezer.list-NKs.zip)
[Research Freezer list-AFs.zip](https://github.com/ArctosDB/arctos/files/9145166/Research.Freezer.list-AFs.zip)
[Research Freezer list-IFs.zip](https://github.com/ArctosDB/arctos/files/9145167/Research.Freezer.list-IFs.zip)

Priority: High, needed for grant proposal

**Comment by dustymc** [comment]
@campmlc always easier (=less likely to be mangled) for me if you put things (that match the data, I think these do) in one file - hopefully I didn't muck up the merge.
[temp_msb_frpt_d.csv.zip](https://github.com/ArctosDB/arctos/files/9145801/temp_msb_frpt_d.csv.zip)

```

create table temp_msb_frpt_d as select
temp_msbfnrpt.collection,
temp_msbfnrpt.number,
flat.guid,
flat.othercatalognumbers,
flat.collectors,
flat.collecting_event_id,
flat.parts,
flat.partdetail,
flat.Remarks,
flat.related_record_cache
from
temp_msbfnrpt
left outer join coll_obj_other_id_num on temp_msbfnrpt.collection=coll_obj_other_id_num.other_id_type and temp_msbfnrpt.number=coll_obj_other_id_num.display_value
left outer join flat on coll_obj_other_id_num.collection_object_id=flat.collection_object_id;
```

**Comment by dustymc** [comment]
Happy?

**Comment by campmlc** [comment]
Yes, thanks!
