### ISSUE TITLE
Code Table Request - nature of ID definitions

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#4846]
MVZ is in the process of cataloging a large number of purely observational records, no associated media. We propose the following changes to the code table definitions for [nature_of_id](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctnature_of_id):

**Audio-visual:** 
CURRENT:Identification based on analog and digital media such as audio recordings, video recordings, and photographs.
PROPOSED: Identification based on analog and digital media such as audio recordings, video recordings, and photographs. Can be verified by examination of media.

**Features:**
CURRENT: Identification based on in-hand examination of diagnostic traits including morphology, coloration, structure, etc. This value encompasses "fine features" and "coarse features" and should not be used if more specific information is available.
PROPOSED: Identification based on diagnostic traits including morphology, coloration, structure, vocalizations, etc. Identification may or may not be verified independently (e.g., pure observations by sight or sound). This value encompasses "fine features" and "coarse features" and should not be used if more specific information is available.

**Comment by campmlc** [comment]
Should we clarify what situations there might be when this shouldn't be used, e.g. what other types of "specific information" that might be available?

**Comment by mkoo** [comment]
with changes from @DerekSikes @campmlc --
Seems like the proposed **Audio/Visual** definition is generally ok.
NEW PROPOSED: Identification based on analog and/or digital media such as audio recordings, video recordings, and photographs. Can be verified by examination of media.

**Features** 
NEW PROPOSED: Identification based on diagnostic traits including morphology, coloration, structure, vocalizations, etc. Identification may or may not be verifiable independently (e.g., observations by sight or sound). This value encompasses "fine features" and "coarse features" and should not be used if more specific identification evidence is available (see other nature of id options: function, geographic distribution, karyotype, molecular, etc).

Please weigh in with affirmative or negative so we can fix and update soon! thx

**Comment by Jegelewicz** [comment]
Fine by me.

**Comment by ccicero** [comment]
Changes made! If there are more comments, we can also tweak some more.
