### ISSUE TITLE
Bulkloader weirdness

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4847]
This is the second time this has happened to me, but I didn't report the first time because I thought it was a fluke.

I loaded stuff to the bulkloader - https://arctos.database.museum/Bulkloader/BulkloadSpecimens.cfm and received a response that 27,982 records were in there, so I marked them to "check and load" and it finished way quicker than it should and reported that x number out of 115 records wouldn't load. I go back to the main page and see someone else's data in there.

I don't know if the other person loaded data over mine or if we somehow interfered with each other at exactly the same moment, or if something else is going on. @dustymc any way to tell what happened?

**Comment by mvzhuang** [comment]
that's happened to me before, but i always assumed that we somehow uploaded near the same time, so it kicked out my data.

**Comment by Jegelewicz** [comment]
> I had a really clean dataset for some reason.

I do
