### ISSUE TITLE
Authentication form for operator not showing up in Profile page

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#4848]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I can't enable user management for a user geneseo2012 because the authentication form isn't showing up

**To Reproduce**
Invite operator
Operator logs in
No authentication form for operator invitation shows up.

**Expected behavior**
For form asking for new password to show up and allow operator to enable.

**Screenshots**
![processed-e91e92cb-6e49-4070-a7a5-89d71868cefe_oJCjE0FG](https://user-images.githubusercontent.com/38706617/180239750-dda5552f-e346-4e8f-b6af-463bc32d23df.jpeg)

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by dustymc** [comment]
They've somehow been invited 5 times, the forms all look for one.

I flushed all of that, you should be able to invite them again.

The table needs a unique index.
