### ISSUE TITLE
Delay in cache for new taxon name thwarts getting stuff done

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4851]
I decided to take a little break and help out some collections with Genbank identifiers but no citations. For one of these, a new taxon name was required, which I added, but I cannot use it for potentially up to an hour! Including to add a classification to the name. This means it is very likely that I will move on to something else and never finish up, leaving 1. the specimen still without a citation (and missing a new identification), 2. a publication created with no specimens cited, 3. a taxon name created with no classifications - all things that will end up creating MORE notifications all while trying to eliminate a single notification.....

Is there any way we can make this more seamless?

**Comment by dustymc** [comment]
>any way we can make this more seamless?

It's a resource limitation. https://github.com/ArctosDB/internal/issues/187 is one manifestation.

**Comment by Jegelewicz** [comment]
Taxon = Lithospermum macromeria
Record = https://arctos.database.museum/guid/UTEP:Herb:24064
Publication = 10.1016/j.ympev.2009.05.013

Dropping here in case I get distracted

**Comment by Jegelewicz** [comment]
FWIW - this delay is a reason you cannot give this project to a student and also a reason this never gets done. The thing is - it seems like this could be automated. From the Genbank accession, I can click through to the publication and get a DOI. But then I have to manually copy-paste the DOI into Arctos, manually add all the authors to the publication (and in this case also add them as agents, which I went back to and added OrcID where I could), then go and add a new identification with the citation to the catalog record. In the case of this one, the new identification requires adding a taxon name plus classification to Arctos. All in I have like 12 tabs open to get this done. There can be a LOT of balls in the air just to "add a citation to a record with a Genbank identifier" and the path for every single notification is different. It requires access to edit pubs, agents, catalog records, and taxonomy - I don't think there are a lot of students who have all that access?

End of rant.

**Comment by Jegelewicz** [comment]
Nothing to be done here.
