### ISSUE TITLE
geog data request: Ecuador 3rd-level

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4855]
I need spatial data for

South America, Ecuador, Orellana, Francisco de Orellana Canton

and I have (from GADM)

Ecuador|Orellana|Orellana|Dayuma| | 
Ecuador|Orellana|Orellana|El Dorado| | 

etc.

Ecuador isn't the only place with this situation, but it seems as good a place to start as any.

This could also be evidence that Arctos is doing something wrong, but in this case I don't think so - whatever GADM has seems to be state->province->canton->sub-county-level-thing that we would not consider geography.

@mkoo @tucotuco and anyone else - is there such a thing out there somewhere, or do I need to try to merge the 4th level stuff in PG (which I suspect would be problematic, GADM seems to have some gaps, but maybe that's better than nothing anyway), or ????

HELP!

**Comment by Jegelewicz** [comment]
Can you get something from this? https://commons.wikimedia.org/wiki/File:Ecuador_Orellana_province.svg

**Comment by dustymc** [comment]
I've looked but haven't been able to find the source of those images; that would be super-cool for a few cases. (I'm not sure how useful it would be here - I need a few hundred sub-state-like things from various places, Francisco de Orellana Canton is just a convenient example.)

**Comment by Jegelewicz** [comment]
Yeah - that is just some sort of image, no data involved....

**Comment by Jegelewicz** [comment]
I also see this, but again no way to get data...https://mapcarta.com/19646356

**Comment by Jegelewicz** [comment]
Clearly someone has it somewhere because - https://www.google.com/maps/place/Francisco+de+Orellana,+Ecuador/@-0.6035028,-77.2144195,9z/data=!3m1!4b1!4m5!3m4!1s0x91d7779296718627:0x1e3a071c15598ad1!8m2!3d-0.6592316!4d-76.7336521

**Comment by mkoo** [comment]
I can find it but I want to know why? Can we not use the gm api? I'm just
trying to understand why we're hosting adm4/ adm5 level data?

**Comment by mkoo** [comment]
oh I'm sorry canton is 2adm level. I just downloaded as shapefile-- what
format? can I post to the spatial layers gh repo @dusty?

**Comment by dustymc** [comment]
Because pulling https://gadm.org/download_world.html seemed like the simplest thing to do (and it worked well for lots of things, but has scary dark corners). Should I be looking at something else?

There's an API?!

 gpkg or shp should work if you have some big thing, if you just have that one then wtk is usually the least likely to fail/confuse postgis.

**Comment by mkoo** [comment]
On Fri, Jul 22, 2022 at 9:58 AM dustymc ***@***.***> wrote:

> Because pulling https://gadm.org/download_world.html seemed like the
> simplest thing to do (and it worked well for lots of things, but has scary
> dark corners). Should I be looking at something else?
>
Not sure! from my volunteer GIS work I often use data from the UN (HDX or
humanitarian data exchange).


> There's an API?!
>
yea I just dug into the API and I only see adm0 available as a
footprint.... so not really helpful here

> gpkg or shp should work if you have some big thing, if you just have that
> one then wtk is usually the least likely to fail/confuse postgis.
>
well the adm3 is kinda big file in any format (ca 33 mb). Is this the
canton you're looking for? in the db as "Puerto Francisco de Orellana (El
Coca)"
give me a sec to deal with something else and I will upload to arctos S3 as
media. (gh I think has a file size limit) but let me know if not on the
right track....
[image: canton_Puerto Francisco de Orellana (El Coca).png]

**Comment by mkoo** [comment]
one thing begets another...
if I upload to Arctos (via media) seems best if we have a new MIME type of
gpkg (application/geopackage+sqlite3)

from wikipedia:
*GeoPackage* (*GPKG*) is an open, non-proprietary, platform-independent and
standards-based data format for geographic information system
<https://en.wikipedia.org/wiki/GIS_file_formats> implemented as a SQLite
<https://en.wikipedia.org/wiki/SQLite> database container.

probably a little better than a shapefile in that there's just one file and
not a zipped folder of a bunch of shp stuff, eh?

Let me know if that works. otherwise I'll just email you a link to download
independent of db (the gpkg will have all the adm3 polygons with its
associated adm2-- see above)

**Comment by dustymc** [comment]
Email it or stash it somewhere I can wget or something - I'll just pull it into my cache, no reason to have a giant file in any kind of permanent/archival storage.

**Comment by mkoo** [comment]
done

**Comment by dustymc** [comment]
FYI I worked up a recipe for this, it's a little clicky and I have to do it by country but it is functional. Working on Ecuador, will get the rest of the ^^list^^, then this can close.
