### ISSUE TITLE
Russia Russia Russia

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4857]
Arctos contains [Asia, Russia](https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=4557), [Eurasia, Russia](https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10000002), and [Europe, Russia](https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10000905), with a probably-inconsistent application of the various continents to subdivisions. We have discussed this before, but not in a spatial context (and with no conclusion). The readily-available geography (spatial data) is just "Russia." I propose we unify on continent=NULL. (I suppose I'd also settle for Eurasia, but that leaves us perpetually debating whether some island is part of the continent and such, adds more inconsistency to other Eurasia-but-not places, etc.; seems like an unnecessary complication.)

https://github.com/ArctosDB/arctos/issues/4852 is related, but was all one value (so I can add it back if necessary).

@tucotuco @timrobertson100 would refusing to provide a continent do anything "interesting" in GBIF et al.?

**Comment by Jegelewicz** [comment]
> would refusing to provide a continent do anything "interesting" in GBIF et al.?

I doubt it - they would just supply whatever they are using. That's what happens when we put "Pacific Ocean" in continent.

**Comment by dustymc** [comment]
Removed continent from+added spatial to real Russia, left comments on half-Russias.

This is "Russian Asia" according to Arctos:

<img width="509" alt="Screen Shot 2022-08-19 at 7 25 53 AM" src="https://user-images.githubusercontent.com/5720791/185640235-8ccf6dc7-59e0-45a5-bfab-1f4bd94a3749.png">

And Europe:

<img width="315" alt="Screen Shot 2022-08-19 at 7 26 29 AM" src="https://user-images.githubusercontent.com/5720791/185640355-818b4fcc-b056-4fa5-adbc-e874946ad961.png">

If nobody has better ideas, I'll do something - merge, probably - the next time I stumble across this....

**Comment by dustymc** [comment]
This is just more intersection problems, merge-->https://github.com/ArctosDB/arctos/issues/4836
