### ISSUE TITLE
Need Help with Arctos Error: MVZ:Bird accession 15711 in bulkload table

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#4858]
@dustymc I tried to upload 781 blood sample records for MVZ:Bird accession 15711. They all failed with this error that I've never seen before:

**new row for relation "identification" violates check constraint "ck_identification_sciname_trim"** 

The records are sitting in the bulkload table, and I hit load 'autocore'

???

**Comment by dustymc** [comment]
They've got garbage in taxon name

```
arctosprod@arctos>> select ':'||taxon_name||':' from bulkloader where accn like '%15711';
      ?column?      
--------------------
 :Falco mexicanus :
 :Falco mexicanus :
 :Falco mexicanus :
 :Falco mexicanus :
 :Falco mexicanus :
 :Falco mexicanus :
 :Falco mexicanus :
....

update bulkloader set taxon_name=trim(taxon_name) where accn like '%15711';
```

try now

**Comment by ccicero** [comment]
Ahh, damn trailing space! Thanks. Trying again.

**Comment by ccicero** [comment]
Loaded, thanks again!
