### ISSUE TITLE
Feature Request - Locality Search - No option to search chronostratigraphy hierarchically

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#4861]
**Is your feature request related to a problem? Please describe.**
I have a large data request to pull all locality data with coordinates for seven different geological periods. I have no way to actually do this. For example, I can search for period = Cretaceous in locality search, but it won't come up with age = Campanian.

**Describe the solution you'd like**
I need this (which is in catalog record search): 
![image](https://user-images.githubusercontent.com/47402809/180867397-7e1a326c-c4b5-4f1d-9145-36e1f70f654f.png)
in locality search.

**Describe alternatives you've considered**
I can't get at this via catalog record search. I can search for all Cretaceous specimens, but I can't pull the locality data from there - by default catalog records only have our 'public' localities and I also cannot download locality attributes from catalog record search.

**Comment by Jegelewicz** [comment]
> For example, I can search for period = Cretaceous in locality search, but it won't come up with age = Campanian.

I thought this was what this was supposed to do?

![image](https://user-images.githubusercontent.com/5725767/180871456-36b8b853-6d89-47e8-8131-a60af55d81e9.png)

@dustymc

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
It does for that search field in catalog record search, but that isn't available for locality search.

**Comment by Jegelewicz** [comment]
Adding the bug label to get Dusty's attention

**Comment by dustymc** [comment]
Clearly not a bug....

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks Teresa!

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thank you!
