### ISSUE TITLE
provide more information on failed login attempts

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4862]
@Jegelewicz got it! I'll try that
@dustymc Thanks!!! 11 attempts should be enough, but not totally sure if it's resetting after successful logins.  I would've noticed if i was struggling with the password for that long. Any chance we can have a little notif that the account will lock at next unsuccessful attempt or would that cause security issue?

_Originally posted by @mvzhuang in https://github.com/ArctosDB/arctos/issues/4767#issuecomment-1194570661_

**Comment by mvzhuang** [comment]
ok for sure this time, i only typed it in wrong twice after a successful login yesterday and I've been locked out again. @dustymc I don't think the attempt number is resetting after a successful login. 

Can i get unlocked again?

**Comment by dustymc** [comment]
You should be open - I'll try to lock myself out in a bit...

**Comment by dustymc** [comment]
see https://github.com/ArctosDB/arctos/issues/5697 - make sure the counter is behaving properly

**Comment by dustymc** [comment]
There was a situation in which the counter wasn't being reset, fixed for next release.
