### ISSUE TITLE
Transarctos Unified Reporting Directive

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4863]
**Is your feature request related to a problem? Please describe.**

Arctos has lots of reports, but they're all report-centric; from a catalog record, it's not obvious what might be known to need further work. People only find problems when they go looking for them; things that might be easily fixed are not noticed and so are not incidentally fixed.

**Describe what you're trying to accomplish** 

Unify reports, make everything available from catalog records; show "flags" where they're most useful.

**Describe the solution you'd like**

Unified catalog record based reporting.

**Describe alternatives you've considered**

Crawl around lots of dissimilar reports; update complex+scattered code every time something changes; don't fix things when it might be convenient to do so.

**Additional context**

I think this would be entirely additive - "find records with X" (current functionality) would remain, this would just add a view/entry point and standardization. I am therefore going next task, but please do not hesitate to comment or change that if necessary.

**Priority**

**Comment by campmlc** [comment]
cool

**Comment by Jegelewicz** [comment]
Have you read this? https://discourse.gbif.org/t/the-vexed-question-of-missing-data-in-darwin-core/3374/3

**Comment by dustymc** [comment]
reopening for adjustments and report mergers

1. Make the form GET (copying URLs is useful)
2. Move "Uncited Loaned Records Notification" from eg https://arctos.database.museum/info/undocumentedCitations.cfm?action=citsnoloan&collectionid=4 to eg https://arctos.database.museum/Reports/cat_record_reports.cfm?report_name=usage:%20citation%20no%20loan&guid_prefix=UAM:Ento
3. See if we can get a count without melting the report (maybe add pagination??) - the "old" (current) form shows "Found 58788 matches." the new " 2500 matches The limit has been reached; this filter is not showing all records. "
