### ISSUE TITLE
Limit search on identification to a single type of taxonomy term

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4864]
From https://github.com/ArctosDB/data-migration/issues/842#issuecomment-1194202934
> (2) While I might want to search "any" field at times, it would seem like if I type in a search term in the line for Identification, that's the field I want to search, and I don't need to add another character to specify that. Another example: I tried "%garnet" (without the quotes), and still got many items I don't want because the word is somewhere else not related to minerals. I suppose we will have to learn more complex search methods, instead of just being able to search for something as in Excel; this may try the patience of non-professional curators & other users.

> word is somewhere else not related to minerals

There is no way to only find records identified with "mineral" names from the main search page. Could we add that functionality?

**Comment by dustymc** [comment]
>There is no way to only find records identified with "mineral" names

And there won't/can't be - name type is 'who got there first' not 'only for ...'

> if I type in a search term in the line for Identification, that's the field I want to search,

And that's what happens?

<img width="635" alt="Screen Shot 2022-07-26 at 12 51 26 PM" src="https://user-images.githubusercontent.com/5720791/181099784-7e01fc7c-0071-41e5-b69c-2a6cc64c0282.png">

will find 'name as used by...' - done?

**Comment by Jegelewicz** [comment]
This is a valid problem and we need a method for getting results as expected (Iron that is this - https://www.mindat.org/min-2047.html)

This is the homonym (#4794 ) issue writ large and I can think of absolutely no way for a person searching Arctos for "that" Iron to find it since the classification has nothing "searchable" that identifies it as such.

https://arctos.database.museum/name/Iron
![image](https://user-images.githubusercontent.com/5725767/181103359-b9e3f8d7-055d-4619-abd1-77882040fded.png)

**Comment by Jegelewicz** [comment]
Revision - I need to find stuff that has a classification X source.

**Comment by dustymc** [comment]
Allow "find stuff where names used in IDs have specified source(s)"

That solves https://github.com/ArctosDB/arctos/discussions/4891 (maybe?)

**Comment by Jegelewicz** [comment]
I think this is possible using term and source, so closing for now.
