### ISSUE TITLE
Geography data request: public lands

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4865]
@mkoo @mlbowser or anyone else, are you aware of any sources of public land data? North America, United States, Alaska, Kenai National Wildlife Refuge is the 5th most used spatial-free geography at the moment, and I can't find data for it.

I pulled parks from https://www.naturalearthdata.com/downloads/10m-cultural-vectors/ but it's very limited.

I can deal with geopackage or shapefile format "tables" or about anything for single shapes.

HELP!

**Comment by mkoo** [comment]
ok hang on -- my go-to source for public lands is USPAD. the data is
reported state-by-state so I dont know what AK looks like, but for CA it's
great

**Comment by mkoo** [comment]
ps. Natural Earth is excellent for cartography but would not use for spatial analysis

**Comment by mkoo** [comment]
also FWS has their own db with all wilderness and managed land boundaries.... do we need more than Kenai NWR?

**Comment by dustymc** [comment]
>s. Natural Earth is excellent for cartography but would not use for spatial analysis

It's better than nothing, but if you have something better I'm happy to swap it out. (I think I'll make my 'gadmizer' public and leave it around, so this can be done on a case-by-case basis by any manage_geography user as the need arises.)

I don't think I have tools to deal with 'raw GIS' but I assume/hope its easy for you to import / export as gpkg/shp?

Kenai is what I keep scrolling past, but there are lots of 'features' in Arctos that (perhaps after they've been separate from [overlaps](https://github.com/ArctosDB/arctos/issues/4836)) will need spatial data.

**Comment by mkoo** [comment]
does this work? see email since gh doesnt gpkg

**Comment by dustymc** [comment]
>I want to see serious search features with these! 

<img width="633" alt="Screen Shot 2022-07-26 at 10 54 46 AM" src="https://user-images.githubusercontent.com/5720791/181077322-c05eb5b4-f56b-49fe-9187-5462a2c58391.png">

Spatial data can be used in various types of searches, for pulling webservice data which is used in various searches and standardizations, and for things like suggesting appropriate geography.

<img width="882" alt="Screen Shot 2022-07-26 at 10 59 46 AM" src="https://user-images.githubusercontent.com/5720791/181078394-3fccdea8-2b7d-4a01-b296-0a4f0b820abf.png">

I'm also going to use it to build [48-point flashing red error messages](https://github.com/ArctosDB/arctos/issues/4863) (or something) if we can't use it to [prevent that in the first place](https://github.com/ArctosDB/arctos/issues/4289). More and clever-er use cases always appreciated!

>BTW are these gpkg or whatever downloadable from Arctos (ie., do they hang around as a file or just added to Arctos db table somewhere?

No, I'm using ogr2ogr and shp2pgsql to convert them to ``geometry`` and then I convert to ``geography`` for my cache, then I (sometimes) copy that to geog_auth_rec which also stores ``geography``. I could make both the cache and the authority available, somehow, but I think that would be somehow necessarily more complicated than 'click for current data.'

**Comment by mkoo** [comment]
> I'm also going to use it to build [48-point flashing red error messages](https://github.com/ArctosDB/arctos/issues/4863) (or something) if we can't use it to [prevent that in the first place](https://github.com/ArctosDB/arctos/issues/4289). More and clever-er use cases always appreciated!
> 
I like marching ants: https://codepen.io/stg/pen/YGRpZJ (kidding)
I think we should think more about user interfaces....

> > BTW are these gpkg or whatever downloadable from Arctos (ie., do they hang around as a file or just added to Arctos db table somewhere?
> 
> No, I'm using ogr2ogr and shp2pgsql to convert them to `geometry` and then I convert to `geography` for my cache, then I (sometimes) copy that to geog_auth_rec which also stores `geography`. I could make both the cache and the authority available, somehow, but I think that would be somehow necessarily more complicated than 'click for current data.'

that's fine. no need to have the file hanging around. might want some metadata about source however. but current storing as geometry is what I wanted to know

**Comment by dustymc** [comment]
>ants

As long as they're 48-point and red....

>think more about user interfaces.

I'm listening!

We also need to talk more about data, I think we're doing a bunch of things the way we are because that's how its always been done, not because that's the best way to do it with current tools. Seems like it should be one of those 'bigger than Arctos' conversations, but also maybe everyone else is still working with strings??

>metadata about source

I keep flipflopping. It'd add some complexity and require some extra knowledge, but also allow for easy 'find all low-quality because I've got better data and want to replace them' sorts of things. No real objection, Issue please.

**Comment by dustymc** [comment]
>serious search features 

I shuffled some things around and wrote some [unavoidably-linked documentation.](https://handbook.arctosdb.org/how_to/How-to-Search-for-Specimens.html#spatial)

**Comment by Jegelewicz** [comment]
Do any of the "map" options need a caveat that stuff without coordinates or appropriately selected geography might not show up (kinda like the "false positive" remark in the "any" search)?

**Comment by dustymc** [comment]
>stuff without coordinates 

I make 'em up for some of it, but the expectation should be that stuff without coordinates is entirely invisible to any serious user. (My longstanding offer to magic coordinates in to most everything stands; I'm not sure that would change much functionality, but it would make the invisible problems into obvious problems.)
