### ISSUE TITLE
Help with a geology term

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4867]
An incoming geology collection has an object identified as [ventifact](https://en.wikipedia.org/wiki/Ventifact). The Wikipedia article suggests that this is not a proper identification, but some sort of part name or attribute since a ventifact can be composed of many "identifiable" taxa ([Granite](https://arctos.database.museum/name/Granite), [Sandstone](https://arctos.database.museum/name/Sandstone), [Schist](https://arctos.database.museum/name/Schist), etc.)

The same is true for geode, stalagmite, stalactite, and probably other kinds of [geosample](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#geosample). So for my geology peeps @Nicole-Ridgwell-NMMNHS @aklompma  - what are your thoughts? Should these be part names, used instead of geosample, or should they be some kind of attribute - and if so, what? Or maybe using an A {string} formula Granite {ventifact} is the way to go?

All opinions welcome!

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
My initial thought was - these are very important descriptors, they should be in parts. BUT having part attributes visible in search results helps, and there would be an advantage in being able to add more than one of these types of geological structures to a single part. For example, a piece of limestone could be both a [Spelothem](https://en.wikipedia.org/wiki/Speleothem) and a [Stalactite](https://en.wikipedia.org/wiki/Stalactite). Add them to part modifiers? Part = Rock, Part Modifier = ventifact.

**Comment by Jegelewicz** [comment]
oh yeah -that seems like a good idea!
