### ISSUE TITLE
Code Table Request - New Identifier Relationship for Geology/Paleontology Collections

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#4868]
**Goal**
Create relationships between fossil/mineral specimens in the same matrix

**Context**
#4825 (mounted with) is doing something similar, associating specimens that are physically linked to each other, but this situation differs because it is an association created naturally by the rock the specimens are in.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctid_references

**Proposed Value**
in same matrix as

**Proposed Definition**
Specimens which are embedded in the same mass of rock and cannot be physically separated without additional preparation.

**Comment by Jegelewicz** [comment]
@wellerjes does this cover your vine wrapped around a branch? Is there some other way to do that?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
https://github.com/ArctosDB/arctos/issues/4825#issuecomment-1195983861

> but there are other things "naturally attached" can we come up with something less specific than same slab as? Maybe not, but I'd like to think about it.

More examples would definitely be helpful. Taking @wellerjes example of "a vine that wrapped around the stem of the plant", vs two fossils in a chunk of rock, one is an interaction, the other is not, and I don't know that they should be lumped together.

**Comment by dustymc** [comment]
>in same matrix as

This will lead to an infinite number of ways of saying 'together, naturally.' I can see no reason we'd have separate terms for phoretics and epiphytes and the million other things that get stuck together 'by nature,' and I don't see any way we can avoid that with such specific vocabulary.

**Comment by dustymc** [comment]
>interaction

Ah - maybe that is a reason to have fairly specific terminology.

**Comment by Jegelewicz** [comment]
> interaction

That seems like @DerekSikes "on" , because while these things are together, do we know why?

**Comment by wellerjes** [comment]
> cannot be physically separated without additional preparation.

I would also add, "or potential damage to the object"; with the vine around the branch example, it has been pressed for 100+ years and/or glued down to a herbarium sheet, so any attempt to separate the two could lead to irreparable damage, which is why it hasn't been attempted.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> when two minerals are attached, would this also work

I believe so.

**Comment by Jegelewicz** [comment]
added
