### ISSUE TITLE
get all agent "names" in one place on the catalog record

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4869]
>  I would like my VERBATIMCOLLECTORS and VERBATIMPREPARATORS to be visible in the Agents tab, instead of their current spot on the Attributes tab. Is this easy?

_Originally posted by @jbrad in https://github.com/ArctosDB/arctos/issues/4270

**Comment by Jegelewicz** [comment]
This just might make people more amenable to fewer. better documented agents?

**Comment by campmlc** [comment]
I definitely agree that whatever we do with agents, all agents and
agent-like-verbatim-things should be displayed in the same place. I

**Comment by dustymc** [comment]
>This just might make people more amenable to fewer. better documented agents?

If this lets me [periodically flush collector-only (table, not role) agents](https://github.com/ArctosDB/arctos/issues/4554) then I will elevate priority and drop everything else. If we can't make than sort of commitment - if we must keep creating and maintaining low-information agents (regardless of namestring format) - then the separation is probably just confusing.

**Comment by jebrad** [comment]
Ah... I missed this 4869.   Well - I hate to think of you dropping everything else to do something for me, but Yes if you can put my VERBATIMAGENTS someplace better I will be happy and I promise to make fewer low-quality agents.

**Comment by dustymc** [comment]
Other issue is moving and anticipating this, nobody's objecting, unless someone stops me now.....

**Comment by Jegelewicz** [comment]
I was thinking this morning how it would be cool to see verbatim, then agents - it shows what interpretations might have been made...BUT - it really would be nice if the verbatim term was "verbatim agent". Placing a verbatim collector next to a preparator agent looks odd....

**Comment by Jegelewicz** [comment]
Above would be "just UI"....

**Comment by dustymc** [comment]
>"just UI"..

Maybe-sorta, but saying A and seeing Z isn't _good_ UI.

>verbatim term was "verbatim agent"

But it's not, there's a giant Issue (or two?), this is not an arbitrary thing.

That said, here's a mini-proposal that I think won't break all of my scripts or lose anything, will make this work beyond collectors, gets away from arctos-techy-vocab, and (thanks to the component loader system) is something we can afford:

* Update all current without method to have something ('unspecified collector role' maybe)
* New trigger, verbatim.... requires method 
* Change verbatim collector to verbatim agent
* Make the [horrid documentation](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#verbatim_collector) better

**Comment by Jegelewicz** [comment]
This sounds reasonable to me!

**Comment by Jegelewicz** [comment]
I am reopening this to discuss the [horrid documentation](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#verbatim_collector)

First pass

Verbatim collector accepts any string value. This attribute should be used when there is little to no information about a collector or preparator instead of creating a low-quality agent. Indicate the agent role with regard to the catalog object in the attribute method.

**Comment by dustymc** [comment]
>reopening

You need to reset the milestone when you do that or I'll just close it again.

Suggest this is better in https://github.com/ArctosDB/arctos/issues/4871 - actually I'll just go ahead and move...
