### ISSUE TITLE
Code Table Request - verbatim agent

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4871]
**Goal**

Better handling of low-information agents.

**Context**

Multiple issues, nobody likes current table-based terminology :(

This proposal solves (I hope!) technical objections raised in other discussions by requiring method.

This also opens up the possibility of more than collectors as verbatim, but I don't think anyone's advocating for that usage.

https://github.com/ArctosDB/arctos/issues/4869 is recent and related.

https://github.com/ArctosDB/arctos/issues/4554 is the (my) ultimate goal. (tl;dr: less work=better data)

**Table**

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type

**Proposed Value**

verbatim agent

**Proposed Definition**

Verbatim agent string, unattached to Agents. Used by scripts in agent mergers. Should be used for all low-information agents (those lacking dates, relationships, addresses). Method is required, and should be used to specify (or approximate) in which role the agent is acting.

IMPORTANT: This attribute would be auto-created as necessary by the agent merger scripts, into which the definition would be hard-coded. Help getting this right greatly appreciated.

**Collection type**

All (this is automatically added as necessary by agent merger scripts).

**Attribute data type**

string, but trigger to require method

**Migration Path**

For existing verbatim collector attributes with NULL method, update method to 'unspecified collector role' before migrating

**Comment by Jegelewicz** [comment]
I am on board with this.

**Comment by Jegelewicz** [comment]
@ArctosDB/arctos-code-table-administrators @ArctosDB/agents-committee

**Comment by dustymc** [comment]
@Jegelewicz [says](https://github.com/ArctosDB/arctos/issues/4869#issuecomment-1202861800):

>Verbatim collector accepts any string value. This attribute should be used when there is little to no information about a collector or preparator instead of creating a low-quality agent. Indicate the agent role with regard to the catalog object in the attribute method.

I like 'low information' better than 'low-quality'- this may turn out to be some super important thing, you just don't have the information to know yet. And I'd like to elaborate on that: there's no date, relationship, or address information available.

**Comment by dustymc** [comment]
Nobody's objecting, going active
