### ISSUE TITLE
Feature Request - try to match agents to verbatim whateverwecallems

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4872]
**Is your feature request related to a problem? Please describe.**

I'd like to make more use of verbatim agents, but they should also be reconciled with actual Agents when possible. 

**Describe what you're trying to accomplish** 

Better data, less work.

**Describe the solution you'd like**

On edit agent, see if we can dynamically round up verbatim agents that might be representations of the active agent.

**Describe alternatives you've considered**

Bigger messes in Agents.

**Additional context**

https://github.com/ArctosDB/arctos/issues/4554#issuecomment-1198680601

**Priority**

Fairly high? Don't think this can be controversial so going next task, but please let me know if I'm not seeing something.

Blocked by https://github.com/ArctosDB/arctos/issues/4871 - no reason to write something then immediately have to change it.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
This seems like a good idea to me.

**Comment by lin-fred** [comment]
A J Smith (verbatim agent)
A. J. Smith (person: 10011077)

Do seem to be the same person, so could be used as an example

**Comment by Jegelewicz** [comment]
Once we make the great agent transition, this priority needs to get bumped up.

**Comment by dustymc** [comment]
I don't think this has a place post-https://github.com/ArctosDB/arctos/issues/6813, tabling.
