### ISSUE TITLE
Feature Request - expandable part attribute sub-table?

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#4873]
Is it possible in the catalog record detail page to make the internal sub-menu for the part attributes expandable?
We enter a lot of text in the part attributes and it's often hard to see the text or various part attributes even in the full view of the parts section. We'd love to be able to see an [expand] option inside that table if possible.

Maybe something like this?
<img width="1207" alt="Screen Shot 2022-07-28 at 2 34 25 PM" src="https://user-images.githubusercontent.com/17605945/181648776-18d0f603-7181-4254-af08-0f87aa8d5cc3.png">

**Comment by dustymc** [comment]
@AJLinn if you're just talking about the catalog record view, I can relatively easily build more templates that users can swap out (with that dropdown after 'Parts'). If that's it, don't let any existing things constrain your ideas, mock something up and we'll give it a go. 

If that's not the issue then I need more info.

Or I can try to adjust that view, but I think what you're asking for would make a mess out of the screen for other types of records (hence the switcher-thing).

And specific examples are always useful.

**Comment by AJLinn** [comment]
> @AJLinn if you're just talking about the catalog record view, I can relatively easily build more templates that users can swap out (with that dropdown after 'Parts'). If that's it, don't let any existing things constrain your ideas, mock something up and we'll give it a go.

Yes, just on the catalog record view (everything is easy to read in the part edit view)
I think it's mostly just being able to see that internal table easier. Instead of having to scroll thru the text all inside that small box, if it could expand like the main attributes to make the page longer and you scroll the whole page rather than just inside that small box, that would be great!

https://arctos.database.museum/guid/UAM:EH:UA64-007-0026
has a lot of text in those part attribute fields so rather than only seeing part of those condition report descriptions like this:

<img width="1711" alt="Screen Shot 2022-07-28 at 3 07 17 PM" src="https://user-images.githubusercontent.com/17605945/181652168-c9fb3ef0-2992-4781-9838-9463fe9543c5.png">

...you could expand that internal table to see the full text of all those part attributes. This is particularly important when you're working on a smaller screen and that internal table compresses so you can only see a few words in each line:
<img width="1253" alt="Screen Shot 2022-07-28 at 3 13 42 PM" src="https://user-images.githubusercontent.com/17605945/181652398-b8f36227-badb-4dd2-8748-520ec996fcd6.png">

**Comment by dustymc** [comment]
Make this like parts, with injectable (and so potentially user-selectable) full-width table at the bottom. Going active as part of https://github.com/ArctosDB/arctos/issues/4337
