### ISSUE TITLE
Remove attribute from all records

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#4875]
The UAM:EH collection used to use the attribute "historical" to determine whether an object related to the Ethnology or the History collection. We no longer want to use this attribute as we no longer split the collection into this binary designation. I've been deleting the attribute from each record as I randomly edit them.

Is is possible to remove that attribute from ALL of the UAM:EH records all at once?
Could someone help me do that?

**Comment by dustymc** [comment]
Search: https://arctos.database.museum/SpecimenResults.cfm?guid_prefix=UAM%3AEH&attribute_type_1=historical&attribute_units_1=&attoper_1=equals&attribute_value_1=&scientific_name=&country=&state_prov=&county=&spec_locality=

Download, shuffle


[uamehhistorical.csv.zip](https://github.com/ArctosDB/arctos/files/9233831/uamehhistorical.csv.zip)


review, feed to the [unloader](https://arctos.database.museum/tools/BulkUnLoadAttribute.cfm?action=ld)

**Comment by AJLinn** [comment]
I downloaded the csv file, uploaded to the unloader, and loaded so it said "success, records deleted" - but my records still have the historical attribute intact. 

Does it take a while for the unloader to be reflected in the records? Sorry for being thick on this... I rarely use bulkloading tools so I'm not very adept with the instructions. Can you help me figure out if I've missed a step?

**Comment by Jegelewicz** [comment]
> Does it take a while for the unloader to be reflected in the records?

Probably - especially if there were a lot of them? Only @dustymc can say for sure though

**Comment by AJLinn** [comment]
15000+

**Comment by dustymc** [comment]
> said "success, records deleted" 

I think maybe you deleted before anything happened, but I'm not sure - screenshots or something would be useful. It should just silently delete rows as it successfully processes them, or leave errors as it fails - same as all other component loaders.

>Only @dustymc can say 

<img width="358" alt="Screen Shot 2022-08-04 at 2 17 22 PM" src="https://user-images.githubusercontent.com/5720791/182954351-f194463e-eba9-496f-bd27-0ef897805d20.png">

will tell you what the loader's doing, right above that will tell you if whatever the loader's just done has been processed, and

<img width="216" alt="Screen Shot 2022-08-04 at 2 18 54 PM" src="https://user-images.githubusercontent.com/5720791/182954623-db4bd6a9-efc8-4d97-984f-9ec57ba1441d.png">

will tell you the status of a single record.

**Comment by Jegelewicz** [comment]
Oh yea - that message definitely doesn't sound right. After loading the file, did you have to review them?

**Comment by AJLinn** [comment]
Okay so I loaded
<img width="517" alt="Screen Shot 2022-08-04 at 2 04 09 PM" src="https://user-images.githubusercontent.com/17605945/182960810-88076d6c-cafc-4362-9c49-72a9a1b01eb8.png">

Reviewed and changed status to autoload
<img width="761" alt="Screen Shot 2022-08-04 at 2 05 10 PM" src="https://user-images.githubusercontent.com/17605945/182960861-84550cae-dd69-49b9-a81f-7d22b2acb256.png">

What's my next step?

**Comment by dustymc** [comment]
Click the orange button, but that's an older form lacking that bit of instruction and the ability to control page size so I did...


```
arctosprod@arctos>> update cf_temp_unload_attribute set status='autoload';
UPDATE 15602
```

now you can watch https://arctos.database.museum/tools/BulkUnLoadAttribute.cfm for errors and https://arctos.database.museum/info/component_loader_status.cfm for progress.

**Comment by AJLinn** [comment]
Huzzah! No more historical attribute!
Thanks for helping me push the right buttons.
