### ISSUE TITLE
Error on using Manage Parts to update Part Remarks

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4878]
Trying to use Modify Parts from Catalog Record Search Results page to update part remark field.
I get the attached error message.
Also, a related request - any way we can modify this tool to update multiple parts, or all parts, at once? Currently we have to choose each part type and do the same action for each one. Very tedious when there are 5 tissue types per record.

![image](https://user-images.githubusercontent.com/14808196/182050840-6f819902-e631-4e1a-9813-ec26c4c4524f.png)

![image](https://user-images.githubusercontent.com/14808196/182050864-2b78162a-1e56-4f2c-8d78-d3b520122f51.png)

![image](https://user-images.githubusercontent.com/14808196/182050914-ab120be7-adad-4c88-9216-b1e123c5d241.png)

[bulkPart.pdf](https://github.com/ArctosDB/arctos/files/9229968/bulkPart.pdf)

**Comment by dustymc** [comment]
Looks like a timeout/resource limitation.
