### ISSUE TITLE
Arctos Down - 4PM Pacific Thursday August 4th

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4879]
Please let me know ASAP if this schedule doesn't work for anyone.

## Planned Outage
 - Date and time outage will begin: 4PM Pacific Thursday August 4th
 - Date and time outage is expected to end: ~5PM Pacific Thursday August 4th
 - Reason for outage: finalize https://github.com/ArctosDB/arctos/issues/1747
 - Expected behavior during and after the outage: Arctos will be down/unavailable

## Communication before/during outage
- [x] Pin this issue
- [x] Banner updated @jegelewicz 
- [x] Email sent to AWG 
- [x] Email sent to Arctos Google Group 
- [x] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [x] Unpin this issue
- [x] Banner updated @jegelewicz
- [ ] Email sent to AWG 
- [ ] Email sent to Arctos Google Group 
- [x] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by ewommack** [comment]
So Arctos will be down for 1 hour on Thursday, if everything goes well. 

No objections.

**Comment by lin-fred** [comment]
No objections, I'll send out a tweet later today if no one says anything against

**Comment by ewommack** [comment]
Ok, I'm going to post an email with this since I haven't heard anything else in the thread.

**Comment by lin-fred** [comment]
The tweet has posted

**Comment by ewommack** [comment]
Email sent

**Comment by dustymc** [comment]
My update is still running, I will let it continue unless someone has an urgent need to bring Arctos back up.

**Comment by ewommack** [comment]
Nah, just me poking about. Keep going Dusty

**Comment by dustymc** [comment]
Arctos is back up but may be a little slow while things finish up.

**Comment by lin-fred** [comment]
Btw can we remove the Arctos Google Group from the checklist, as AWG and the Arctos Google Group are now the same

**Comment by mkoo** [comment]
edited template and banner.
close?
