### ISSUE TITLE
media enhancements

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ArctosDB/arctos#488]
```
List of random Media enhancements

* From Specimen, Click TAG-->highlighted-and-scrolled TAG

* Always (except when editing) open multipage documents (MPDs) in multipage 
view, e.g. from specimen TAG click

* Figure out standard way to include media, showing various size thumbnails and 
detail levels, eg one form that will, based on how it's called:

-- show 20 thumbnails + extensive details + full-blown scroll on a project page
-- show 10 thumbnails + some details + small scroll on taxon page
-- show 3 thumbnails + media type + tiny scroll on specimen page
-- etc., etc., bla bla bla
-- find media by relationship and ID, e.g., 
==={include-->locality_id=1234

* Cache/pre-make/something PDFs for MPDs

* Allow delete of Media (merge from Issue 482)

* Better handling by MIME-type (merge from Issue 476)
```

Original issue reported on code.google.com by `dust...@gmail.com` on 10 Jun 2011 at 6:51

**Comment by dustymc** [comment]
Summarized re-openable bits of this mess:

> Cache/pre-make/something PDFs for MPDs

The on-the-fly PDF-maker is slow and usually doesn't work except for very small documents, so has been disabled. It's probably possible to pre-build PDF, but would be a fairly complicated thing to maintain. File a separate Issue if this is worth further discussion.

>Consider tag-to-tag and/or tag-to-other-media tags. May have file cards related 
to ledger-rows, field-catalog entry related to itinerary, etc.

See #695; tag-to-tag isn't possible in the current model, but tag-to-media could be.

>Should "TAG" be capitalized?

Yes, it's an acronym.

>Let's have link from view-as-document to the big bare document, e.g., 
from http://arctos.database.museum/document/robert-l-rausch-necropsy-ledger/622
to http://web.corral.tacc.utexas.edu/MSB/20140211/011411.jpg

"Media Details" will get you there with one extra click. "Download Master" will get you the TIFF/DNG (when there is one). Open a new Issue if that needs adjustment.
