### ISSUE TITLE
Code Table Request - Smelser Pass Member

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#4889]
**Goal**
Add Smelser Pass Member to the lithostratigraphic member table.

**Context**
Needed for a new locality

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlithostratigraphic_member

**Proposed Value**
Smelser Pass Member

**Proposed Definition**
A Triassic Limestone unit that outcrops in Nevada. [Geolex](https://ngmdb.usgs.gov/Geolex/Units/SmelserPass_11951.html)

I will add in a day or two if there are no objections.

**Comment by Jegelewicz** [comment]
No objection here

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
added
