### ISSUE TITLE
Code Table Request - add Trachyceras silberlingi biostratigraphic zone

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#4890]
**Goal**
Add Trachyceras silberlingi biostratigraphic zone to the biostratigraphic zone code table.

**Context**
This value is needed for a new locality.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctbiostratigraphic_zone

**Proposed Value**
Trachyceras silberlingi

**Proposed Definition**
Range zone defined in [Balini et. al. (2012)](http://hdl.handle.net/2434/222979)

I will add in a day or two if there are no objections.

**Comment by Jegelewicz** [comment]
Looks OK to me!

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
added
