### ISSUE TITLE
Add Regions to Saudi Arabia

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#4894]
Attached is a csv with the Wikipedia Saudi Arabia regions.  

The current list includes Asia, Saudi Arabia, Taif which is a city in Mecca Province and should probably not be in higher geography, but at a minimum Taif should be at the "county" level instead of Province/State.

Province and Region appear to be used interchangeably.  See https://en.wikipedia.org/wiki/Provinces_of_Saudi_Arabia

[Saudi Arabia regions.csv](https://github.com/ArctosDB/arctos/files/9244644/Saudi.Arabia.regions.csv)

**Comment by dustymc** [comment]
Those seem to mostly match my states data (below), this looks like a good place for me to get that match set up.

Most spatial data don't use qualifiers at all, if there's not a reason to retain that I suggest we strip down to eg plain ol' ``Jazan``. (Whatever we do is just going to be a bad-to-someone transliteration, and the wiki link + spatial data removes any ambiguity - I think the intent at some point was to distinguish various things that might share a name, I don't see that as useful now.)


There is seldom spatial data for "dirt, but saltwater" - https://github.com/ArctosDB/arctos/issues/4836, the big picture is that is not resolved, if there's no compelling reason to create more of those then I strongly suggest we don't.

```

 naturalearthdata state   | Al Jawf, SA, Saudi Arabia
 naturalearthdata state   | Jizan, SA, Saudi Arabia
 naturalearthdata state   | Al Qasim, SA, Saudi Arabia
 naturalearthdata state   | Al Baha, SA, Saudi Arabia
 naturalearthdata state   | Ar Riyad, SA, Saudi Arabia
 naturalearthdata state   | Najran, SA, Saudi Arabia
 naturalearthdata state   | Hail, SA, Saudi Arabia
 naturalearthdata state   | Asir, SA, Saudi Arabia
 naturalearthdata state   | Al Madinah, SA, Saudi Arabia
 naturalearthdata state   | Makka, SA, Saudi Arabia
 naturalearthdata state   | Tabuk, SA, Saudi Arabia
 naturalearthdata state   | Al Hudud ash Shamaliyah, SA, Saudi Arabia




```

**Comment by dustymc** [comment]
I assume "governorate" ~ county and used "Mecca" for https://arctos.database.museum/editGeog.cfm?geog_auth_rec_id=10000485, should be synced with whatever we do for the rest

**Comment by sharpphyl** [comment]
Is naturalearthdata our new authority?  Just curious.

**Comment by dustymc** [comment]
>Is naturalearthdata our new authority? 

See https://github.com/ArctosDB/arctos/issues/4755

It's a useful source of spatial data, it's absolutely not authoritative, actually pretty dicey around the edges. My intention is to find (help you find, whatever) SOMETHING spatial for any new geography. If you have something I can probably use it, if you don't I'll try to make do with whatever I have (and hope its accurate enough), or try to talk you into reforming your geography to match whatever I have, or something. This (mostly) lines up with something I have handy so no problem.

The one record which includes sea still looks like the description of a place which can't exist to me, I'm not sure what to do in that situation.

**Comment by dustymc** [comment]
I've now got a super-hacky little tool (Admin/create_geography) that'll let me load small batches for which its easy to find spatial data. I can patch it into production and load these at any time, except

Asia    Saudi Arabia    Mecca Region    Red Sea https://en.wikipedia.org/wiki/Mecca_Province    Mecca Province

still seems like nonsense to me, its a sea or a continent, it can't be both, some sort of timely guidance from the @ArctosDB/geo-group would be fabulous

(Worst case:  I can make nonsense and [TURD-flag](https://github.com/ArctosDB/arctos/issues/4863) it, same as I'll do for the 8413 existing entries for which I can't find spatial data. That's is absolutely going to be a bunch of extra future work, I still can't see any way it can be viewed as anything but wrong, I think that jives with GBIF and the larger community in general - along with reality itself! - but maybe that's all somehow less-evil than blocking cataloging, IDK, HELP, PLEASE!!!)

Here's the spatial view of the above - this is a state-like-thing

<img width="517" alt="Screen Shot 2022-08-02 at 3 37 17 PM" src="https://user-images.githubusercontent.com/5720791/182485349-2a0924b5-93d1-4e94-bbd1-01ab90cddd1d.png">

this is (part of) the Red Sea

<img width="654" alt="Screen Shot 2022-08-02 at 3 39 53 PM" src="https://user-images.githubusercontent.com/5720791/182485608-4642db5c-9b2d-4aca-ae25-a89e15be1a68.png">

there's no overlap, pick one.

As I mentioned somewhere else I do have data for country+eez, but it's generally pretty huge and I'm not sure how it might be useful or fit into our model.

<img width="657" alt="Screen Shot 2022-08-02 at 3 41 42 PM" src="https://user-images.githubusercontent.com/5720791/182485877-c6ea5bc7-86e5-472a-b9be-db69e14871ff.png">

**Comment by sharpphyl** [comment]
> there's no overlap, pick one.

The Saudi Arabia EEZ might work but it goes into the Persian Gulf as well as the Red Sea.  I'm trying to associate specimens found within <1/4 mile of Saudi Arabia in the Red Sea.  If we had the field [Water Body #128](https://github.com/tdwg/dwc-qa/issues/128) and/or [#2876](https://github.com/ArctosDB/arctos/issues/2876) I could stick with Asia Saudi Arabia Mecca Region and put Red Sea in the Waterbody.

**Comment by dustymc** [comment]
>Water Body

We have Sea, the Red is definitely a Sea, whatever else happens we don't need to add any new "fields" for this. 

>Asia

I'm still pretty firmly in the "pick one" camp here - it's on a continent or its in saltwater, there's no spatial overlap. (I keep finding places where continent is inconvenient, and not finding places where having continent resolves something - left to my own devices I might do something radical there...)

>Saudi Arabia 

There's saltwater controlled by countries, no philosophical problems here (but that's not the only kind of problem, keep reading..).

>Mecca Region

I think maybe that's a soft "pick one" - I don't think states generally control saltwater so I don't think you'll find data that can be defended or that lines up with anyone else's data. You certainly won't find data which fits in a hierarchy, and that eliminates one possible model. I'm not sure I see *wrong* here, but I don't think I see *practical* either.

More generally:

If we make all of Arctos spatial then I can DO STUFF. 

If we're consistent about spatial data I can do predictable stuff - maybe forget about the external services and use our internal, predictable, and consistent data to - predictably! - guide georeferencing and such. (see also https://github.com/ArctosDB/arctos/issues/4837#issuecomment-1205436683 and https://github.com/ArctosDB/arctos/issues/4837#issuecomment-1205466522)

I'm not yet willing to concede to the idea that some of Arctos will always be an undefined mess unable to answer the same sorts of questions as the rest of Arctos, but that's where we are now and maybe we just aren't willing to change that.

> within <1/4 mile of Saudi Arabia

There's always the idea that there is no single useful "authoritative placenames" view of the planet, and if you have reliable georeferencing the most appropriate asserted geography is "[we ain't sayin'](https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10016350)."

**Comment by sharpphyl** [comment]
When opening this issue, I followed the "new issue" format to request the addition of higher geography and attached a csv. 

<img width="1175" alt="Screen Shot 2022-08-25 at 7 12 21 AM" src="https://user-images.githubusercontent.com/15368365/186674147-802108c3-33ed-4a13-ae39-610b5bde1d92.png">

Let's remove the last entry of my csv which raised the question of the Red Sea in Saudi Arabia.  I only need Mecca Province but figured including all of them might be helpful.  I omitted "Eastern Province" which is already in the Arctos table.

<img width="944" alt="Screen Shot 2022-08-25 at 7 21 52 AM" src="https://user-images.githubusercontent.com/15368365/186676239-e184d903-b9a7-4a36-b2fc-8548bc894797.png">


The remaining areas are still not in the higher geography.  Mecca is in (without a distinguishing Region or Province which may be best) but the entry includes the city of Taif.

<img width="1063" alt="Screen Shot 2022-08-25 at 7 11 13 AM" src="https://user-images.githubusercontent.com/15368365/186674380-8b0f6ae2-a8a5-4217-9e88-fd705bc0af8d.png">

It's fine to use the naturalearthdata for the regions/state and they can be regions or provinces or just the name.  Using that data would name the Mecca Province "Makka" so we should add an aka to link the two.  

I'm trying to database a collection that comes from Kournische on the coast of the Mecca Region/Province/State.  Can you please add the Mecca or Makka to the higher geography?  Is there a better way to request the addition of higher geography?

**Comment by dustymc** [comment]
Sorry, I got distracted (but I found some better data while I was out there), I made these consistent, dropped the sea, and added them.
