### ISSUE TITLE
Code Table Request - part modifiers for geology

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4897]
**Goal**
Provide more information about the standard geology part - geosample

**Context**
For some geosamples, we have additional identifying information, I had thought about creating new geology parts, but @Nicole-Ridgwell-NMMNHS pointed out that sometimes a single sample may represent more than one of these - see https://github.com/ArctosDB/arctos/issues/4867#issuecomment-1203015356

I am proposing values that I know are used in NHSM:Geol - there may be others

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_modifier

**Proposed Values**
ventifact
stalagmite
speleothem
stalactite
geode
cinder
volcanic bomb

**Proposed Definitions**
ventifact - a rock that has been abraded, pitted, etched, grooved, or polished by wind-driven sand or ice crystals. <a href=https://en.wikipedia.org/wiki/Ventifact" class="external">Wikipedia</a>

stalagmite - a type of rock formation that rises from the floor of a cave due to the accumulation of material deposited on the floor from ceiling drippings. <a href=https://en.wikipedia.org/wiki/Stalagmite" class="external">Wikipedia</a>

speleothem - a geological formation by mineral deposits that accumulate over time in natural caves. <a href=https://en.wikipedia.org/wiki/Speleothem" class="external">Wikipedia</a>

stalactite - a mineral formation that hangs from the ceiling of caves, hot springs, or man-made structures such as bridges and mines. <a href=https://en.wikipedia.org/wiki/Stalactite" class="external">Wikipedia</a>

geode - a geological secondary formation within sedimentary and volcanic rocks. Geodes are hollow, vaguely spherical rocks, in which masses of mineral matter (which may include crystals) are secluded. <a href=https://en.wikipedia.org/wiki/Geode" class="external">Wikipedia</a>

cinder - a pyroclastic, highly vesicular, volcanic rock that was ejected from a volcano as a molten blob and cooled in the air to form discrete grains or clasts. <a href=https://en.wikipedia.org/wiki/Cinder" class="external">Wikipedia</a>

volcanic bomb - a mass of molten rock (tephra) larger than 64 mm (2.5 inches) in diameter, formed when a volcano ejects viscous fragments of lava during an eruption. They cool into solid fragments before they reach the ground. <a href=https://en.wikipedia.org/wiki/Volcanic_bomb" class="external">Wikipedia</a>

**Available for Public View**
Yes

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Looks good to me.

**Comment by Jegelewicz** [comment]
just added volcanic bomb

**Comment by Jegelewicz** [comment]
Code Tables says go

**Comment by Jegelewicz** [comment]
added - I need to add these to appropriate objects in NHSM:Geo

**Comment by dustymc** [comment]
done?
