### ISSUE TITLE
Advice sought - mouse skulls from owl pellets

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4898]
ASUMZ:Mamm has quite a few mouse skulls that were recovered from collected owl pellets. These records do not identify the species of owl, just the species of mouse. I can see a bunch of ways to indicate what happened, but I would like some help choosing. Here are the methods I am thinking about.

1. Use an A {string} ID and add Strigiformes and the mouse identification to the string - "owl pellet". Use the part name [skull](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#skull)
2. Just identify the record with the mouse ID, but add the part [pellet](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#pellet) and a subsample from it with part name [skull](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#skull)
3. A combination of the above
4. What else?

**Comment by Jegelewicz** [comment]
@bfluker

**Comment by ewommack** [comment]
Oooh fun! 
Are the pellets cataloged with their own number? Then I would catalog the skull as a separate object and relationship them as eaten. 

I think cataloging the pellet as from Strigiformes makes sense to me.

I guess it would depend on if they want to track the other things in the pellet as well, if the pellet is in the ornithology collection, and if they want the other parts of the pellet to be opened up for future research and use. 

@ccicero @atrox10 - have both given me help with specimens pulled from the stomachs of other animals, or for ones collected by other animals.

**Comment by Jegelewicz** [comment]
> Are the pellets cataloged with their own number? Nope

**Comment by Jegelewicz** [comment]
> If they do not have the rest of the pellet, just the skull,

I believe this is the case - that the pellet has been discarded, but I am not 100% sure that is the case - await an answer from @bfluker

**Comment by Jegelewicz** [comment]
>  list the owl as the collector,

So verbatim collector = Strigiformes I kinda like that anyway, but also then there needs to be some collection event prior to the one in the data with unknown in most of the fields - right?

**Comment by dustymc** [comment]
>Are the pellets cataloged with their own number?

That's the only "correct" approach. If you can't do that then I'd recommend keeping it simple - nothing else is really capable of substituting for the intersection of two records, I don't see much reason to over-complicate the path to not-quite-where-you-need-to-be (which will just result in very confused users in a couple decades). Use remarks, or perhaps something like https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#verbatim_host_id ("typed remarks").

>pellet has been discarded

Doesn't matter, if you want deep interactions then you need two catalog records.

Do you know if multiple mousebits are from the same pellet?

**Comment by ewommack** [comment]
> Do you know if multiple mousebits are from the same pellet?

Good question! If you have multiple pieces from the same pellet, then that data should be saved in some way. It tells you info on the diet for that individual, as well as the species available in the specific place where that owl was hunting.

**Comment by Jegelewicz** [comment]
> Do you know if multiple mousebits are from the same pellet?

Nope - the data just has "owl pellet" in a remark field

**Comment by ewommack** [comment]
Are they all from the same locality and date, or a bunch of different localities and dates?

**Comment by Jegelewicz** [comment]
> Are they all from the same locality and date, or a bunch of different localities and dates?

There are a few "sets" from different localities/dates (someone clearly raided a barn and the football stadium for owl pellets!)

**Comment by Jegelewicz** [comment]
There are  3,813 of them!

**Comment by Jegelewicz** [comment]
How about this?

Create an entity with the identification = Strigiformes and make it the identifier with an "eaten by" relationship on the mouse records. Simple and can be expanded if new information arises?

**Comment by dustymc** [comment]
Seems reasonable. The Entity would represent a population of owls (one or more), seems well within scope, just make that clear (eg in remarks). 

And maybe one (population) for the barn and another for the stadium if you want to get all fancy - there might be science at that level.

**Comment by Jegelewicz** [comment]
> And maybe one (population) for the barn and another for the stadium if you want to get all fancy - there might be science at that level.

Yes to the fancy! I'll figure out how many I need if the locations are far enough apart...

**Comment by Jegelewicz** [comment]
OOOOO - look what I found!

https://scholarworks.uark.edu/cgi/viewcontent.cgi?article=2723&context=jaas

**Comment by ewommack** [comment]
That must definitely be some of them! Now you've got species of owl for a subset.

I like the entity idea. That way both are searchable, and it allows for better use of both sides of the biological story. Yes you did get rodent skulls, and those are valuable, but they were collected by an owl, so you also have information on that animal too.

If we can get this figured out, I bet it would be a great set of records to use as a demo. Owl pellets are used a lot still in biological classes and research projects. If we can show how they can be cataloged for museum data, Arctos collections might be able to get better sets and info from researchers.

**Comment by Jegelewicz** [comment]
Check it out! https://arctos.database.museum/project/10003933

Problem - apparently not all 93 skulls are cataloged (or at least not in the data I have) and there are two things identified as Oryzomys palustris but only 1 listed in the publication - possibly one was identified as something else in the paper and re-identified later? This definitely happened with the Microtus. But hey, it's still pretty cool!
