### ISSUE TITLE
Arctos Search page results with Agents and Verbatim Agents

### ISSUE THREAD

**Issue by lin-fred** [ArctosDB/arctos#4904]
The current consensus of #4554 is all of the agent search pages in Arctos need to result in showing both agents and verbatim agents

Currently it is known that the public agent search page does not pull up verbatim agents, @dustymc please add this ability

Also, when searching on the main search catalog page, If you search with collector you get only agents, if you search with nothing picked you get agents and verbatim agents. Is this ok? or do we want something else?

**Comment by Jegelewicz** [comment]
>  or do we want something else?

I would guess so - people often only want collectors or preparators - of course right now it is potentially difficult to know which a verbatim agent is...

**Comment by ewommack** [comment]
I think we would want to be able to search verbatim in both for now. Usually with the historic there isn't a lot of distinction, its just a name. Search all the verbatim till someone complains they get too much data from a search?

**Comment by dustymc** [comment]
Blocked by https://github.com/ArctosDB/arctos/issues/4871 - no reason to write something then immediately have to change it.
