### ISSUE TITLE
block creations of low quality agents

### ISSUE THREAD

**Issue by lin-fred** [ArctosDB/arctos#4905]
If I get to choose, what @Jegelewicz said sounds great, just outright ban low-information agents. No confusion, no surprise scripts, no complications, no running automation, nobody showing up on my lawn with pitchforks because they didn't read the docs and all their agents vaporized, pleaseplease lets do this...

(We can figure out the UI/details.)

If we can't get that organized, then a monthly-or-whatever purge of year-or-whatever-old low-information agents could work.

_Originally posted by @dustymc in https://github.com/ArctosDB/arctos/issues/4554#issuecomment-1205774589_

**Comment by lin-fred** [comment]
UI/details for bulk loading and single additions of agents

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/4913
