### ISSUE TITLE
Feature Request - agent death/birth date compared to collecting dates

### ISSUE THREAD

**Issue by lin-fred** [ArctosDB/arctos#4906]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
agents that need to be split

**Describe what you're trying to accomplish** 
If a death date is added to an agent, collecting dates that are after that death date should be a red flag that the agent may need to be split. Same for birth date but for collecting dates previous to that date.

**Describe the solution you'd like**
create a data quality report that can pull agents in which their birth/death dates don't coincide with a collection date

**Describe alternatives you've considered**
none

**Additional context**

**Priority**
low but useful to the agent clean up push

**Comment by Jegelewicz** [comment]
I would also add dates before a birth date if available.

**Comment by lin-fred** [comment]
> I would also add dates before a birth date if available.

true!

**Comment by dustymc** [comment]
No discussion required, the [TURD](https://github.com/ArctosDB/arctos/issues/4863) makes this trivial.

**Comment by lin-fred** [comment]
thats the best name

**Comment by dustymc** [comment]
In next release, filtered for event types 'collection','encounter','observation' - that may still need tuning, that's easy in this ecosystem.
