### ISSUE TITLE
Curatorial Search Request - UCM Media

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#4909]
@dustymc I need some usage statistics for an NSF report.

- number of images associated with project 10003438 (not CT media)
- Is there a way to know if people clicked/viewed media? If so, it would be great to get any analytics available for all media types associated with project 10003438 (how many views, different IP addresses, countries etc)

Thank you!

**Comment by dustymc** [comment]
<img width="417" alt="Screen Shot 2022-08-05 at 9 21 15 AM" src="https://user-images.githubusercontent.com/5720791/183119650-132a2725-20cb-4910-b7b5-49d5251d3cd3.png">

```
create table temp_p_10003438_mdia as select
media.media_id,
media.media_uri,
media.mime_type,
media.media_type,
exit_link.username,
exit_link.ipaddress,
exit_link.from_page,
exit_link.when_date,
exit_link.status
from media
inner join exit_link on media.media_id=exit_link.media_id
inner join media_relations on media.media_id=media_relations.media_id and project_id=10003438;


```



[temp_p_10003438_mdia.csv.zip](https://github.com/ArctosDB/arctos/files/9270287/temp_p_10003438_mdia.csv.zip)

**Comment by ebraker** [comment]
@dustymc Thanks! Can you send SQL for image count for project 10003438?

**Comment by dustymc** [comment]
```
select
media.media_id,
media.media_uri,
media.mime_type,
media.media_type
from media
inner join media_relations on media.media_id=media_relations.media_id and project_id=10003438
```
or maybe
```
select
media.mime_type,
media.media_type,
count(*) 
from media
inner join media_relations on media.media_id=media_relations.media_id and project_id=10003438
group by 
media.mime_type,
media.media_type
```

**Comment by ebraker** [comment]
Awesome, thank you!
