### ISSUE TITLE
[CONTACT: Blocked Network]

### ISSUE THREAD

**Issue by Andrew-N-Black** [ArctosDB/arctos#4910]
restricted IP: 50.109.234.25
I am a research from Purdue University, wishing to identify Lesser Prairie Chicken samples available for DNA extraction through your database. I am on a work computer, so I'm unsure why I was blocked. Can you please unblock me from accessing your site?
Thank you

**Comment by dustymc** [comment]
released - it will take about 10 minutes for everything to clear
