### ISSUE TITLE
Refresh/pull Global Names returns an error

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#4912]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
For several weeks now, whenever I click on Refresh/pull Global Names, I get this error.

<img width="1750" alt="Screen Shot 2022-08-05 at 8 15 32 PM" src="https://user-images.githubusercontent.com/15368365/183229692-4aa24444-b29d-4a26-a3e6-0eb266ed8c21.png">

**Desktop (please complete the following information):**
OS, Mac, Safari or Chrome

**Priority**
Medium.  I like to refresh and see the other sources, but it's not critical.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/4662
