### ISSUE TITLE
agent creation - require more information

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4913]
ref: https://github.com/ArctosDB/arctos/issues/4554#issuecomment-1205769789

Add

* relationship
* address
* status

to single-agent creation and bulkloader; require (or prepare to) at least one of them for creation.

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/3934 should come first

**Comment by lin-fred** [comment]
is this the same as #4905

**Comment by dustymc** [comment]
No, but the create form (and bulkloader and whatever) will have address as an option, and it needs to be in final form (dates instead of valid/not flag) before that can be implemented.
