### ISSUE TITLE
Feature Request - ignore prior loans when searching on items to add to a loan

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#4914]
I'm adding items to a loan and there is something confusing/unclear about the loan item picker: it includes items that were previously included in a loan, whether the item may either still be on loan or returned and in the collection. 

Example (loan item back in collection):
https://arctos.database.museum/guid/MVZ:Bird:149263

Here's a screenshot of the parts table:
![image](https://user-images.githubusercontent.com/967275/183524936-b82ff9f3-dab6-4d7a-bc45-c3d058ac6090.png)

Here's the loan item picker for that same specimen:
![image](https://user-images.githubusercontent.com/967275/183524996-523d0ae6-9ab1-411f-93c4-f2a8146cdb7d.png)

Note that 'skeleton' is listed twice in the loan item picker, and which item was included in the prior loan is very cryptic (presumably it's the one that doesn't have the institution in the path? To be sure you need to check the Part ID. That is certainly unclear.

If the item is still on loan, then it's more clear because you can look at the disposition. But can we just ignore those part IDs associated with a loan? If not, then highlight them somehow?

**Comment by campmlc** [comment]
Yes, maybe make the loan picker show the parent child relationship with the
indent more clearly? Also include loan column? This would be helpful as
sometimes I need to pick subsample of same part that has been previously
loaned and therefore is associated with Genbank accessions.

**Comment by ccicero** [comment]
I agree, it would be better to show those items but highlight them somehow, indent is fine just like in the parts table. I like the idea of including a loan column with associated loan number(s).

**Comment by dustymc** [comment]
Added loans and moved the part|parent column to the left for next release, hopefully without breaking anything else.

Also got https://github.com/ArctosDB/arctos/issues/3697

That form has grown beyond sustainable, likely isn't capable of surviving https://github.com/ArctosDB/arctos/issues/2745, and is just kludgy. We should start thinking about replacements - a dedicated UI, or a "click for all the complexity" button, or SOMETHING other than what's there.

https://github.com/ArctosDB/arctos/discussions/4917 is potentially a part of that discussion.
