### ISSUE TITLE
Need Help with Arctos Error - Bulkload Specimen Event

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#4920]
# Error Text

ERROR_ID | 0C204BC8-223D-4EA4-94BADB09BE8A79FD
ERROR_TYPE | application
ERROR_MESSAGE | Error invoking external process
ERROR_DETAIL | psql:/usr/local/webroot/temp/excopy_nicoleridgwell_20220809040804619_242.sql:136: ERROR: invalid input syntax for type numeric: "NMMNH:Paleo:L-7877" CONTEXT: COPY cf_temp_specevent, line 2, column locality_name: "NMMNH:Paleo:L-7877"

# Where it happened
https://arctos.database.museum/tools/BulkloadSpecimenEvent.cfm?action=ld

# Steps to get there
Choose file, click upload, receive error: 
[Barrick_81588-81664_ResearchEvents.csv](https://github.com/ArctosDB/arctos/files/9294865/Barrick_81588-81664_ResearchEvents.csv)

I've checked what the error seems to be pointing to, my locality name, and verified it exactly matches the locality name in Arctos.

**Comment by dustymc** [comment]
fixed

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks!
