### ISSUE TITLE
Citation without loan - a valid reason, can we stop the flag?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4921]
All 52 records in this accession were contributed by the [project](https://arctos.database.museum/project/10003933) reported in [this publication](https://arctos.database.museum/SpecimenUsage.cfm?action=search&publication_id=10011135). I don't think I should also have to create a loan for them to document their "use" in the related publication as the accession already does this. But as it is, there will always be this flag on the records:

![image](https://user-images.githubusercontent.com/5725767/183924781-c8e6574e-ab7b-49c5-a42f-d3a1b053f9d3.png)

Could we somehow document that no loan is necessary in this case and move on?

**Comment by ewommack** [comment]
I've got a couple publications like that related to graduate student work. They do not directly create or use specimens, but they document methods and other parts of the project that led to museum donations. It would be great to be able to keep them in Arctos in a project.

**Comment by dustymc** [comment]
>document that no loan is necessary

I am not convinced this is ever quite correct.

With a loan, there's a chain of custody - it adds some validity to the results, the citations lining up with the loan add some degree of certainty, the citations not lining up with the loan are almost certainly indicative of a problem, etc.

Without a loan - well, believe it it don't, you know what we know....

[These](https://github.com/ArctosDB/arctos/issues/4898) I believe are firmly in the latter camp - they're probably-maybe the right thing, but there's really no evidence beyond the authors said "owls!" and there are some suspiciously similar owls so.... 

I think the flag adds clarity; these citations don't have the documentation that one might wish, they're not quite the same thing as other citations that are backed up by that additional evidence.

What seems to be missing here is publication remarks - "nothing's actually cited, there's no loan, the donation happened after the publication and we have no idea what they actually did...." would clarify the situation.

**Comment by Jegelewicz** [comment]
This pub CREATED the specimens.

**Comment by Jegelewicz** [comment]
It is just a waste of time to create a second transaction here. It is the results of the study that were cataloged. And while it is true that no museum catalog numbers are "cited" in the publication, these ARE those things.  Let's face it, this is often how collections are obtained by university museums - student does something and we get the results. Why should I have to create an accession and a loan for the exact same material?

**Comment by Jegelewicz** [comment]
> chain of custody

Student collected owl pellets -> student dissected owl pellets, identified contents, and wrote publication -> contents accepted into museum collection (accession)

**Comment by Jegelewicz** [comment]
> What seems to be missing here is publication remarks - "nothing's actually cited, there's no loan, the donation happened after the publication and we have no idea what they actually did...." would clarify the situation.

What they did is documented in the publication? I don't see the problem.

**Comment by dustymc** [comment]
>Why should I have to

You do not and you should not. Information is missing, you can't do much about that, the flag helps inform users of the situation. Not all reports are resolvable, that does not make them less useful.

**Comment by campmlc** [comment]
I agree.

**Comment by acdoll** [comment]
We also agree; and are questioning whether these flags should be publicly visible (is this flag for our internal data cleaning/management?).
That said, I'm not sure these flags are working correctly. We've got records with this flag that do have a loan history:
e.g., https://arctos.database.museum/guid/DMNS:Mamm:13103
![image](https://user-images.githubusercontent.com/12507297/186258894-62a5102e-c755-4c9a-9e35-1e64eea5b947.png)

**Comment by dustymc** [comment]
> should be publicly visible

Yes! They are indications of fit for use and quality and such - eg, is there some reproducible line of Research Grade evidence, the kind of thing that Arctos is designed and built to support, or just some unsubstantiated assertion that might have been magically summoned out of the æther?

(That said, I've been sorta drifting towards the idea that we need ranks or categories something - "this isn't as good as it could be but it might truly be the best we can do, maybe proceed with caution" and "this just blatantly conflicts with itself, RUN!" and such.)

>not sure these flags are working correctly.

You're obviously right, thanks, rebuilt, perhaps even correctly....

**Comment by campmlc** [comment]
Here's another record with a report that there's no transaction history when there is one - I assume the updates haven't gone through yet?
https://arctos.database.museum/guid/MSB:Mamm:140413

**Comment by jrdemboski** [comment]
it looks like many records that had an associated transaction are now "no problems detected".....thanks.

I'm still unclear about legacy citations where I don't know what the transaction was 50-100 years ago, a loan? a visit to collection? correspondence? phone call? other?

Example: https://arctos.database.museum/guid/DMNS:Mamm:1159

Dave Armstrong most likely visited our collection, looked at the specimen, and the badger record ended up in his Distribution of Mammals in Colorado. This record now says "no loan" under the report.   so it's unsubstantiated? or we should retroactively assign some sort of transaction?  or just assign a binary call of no stated usage on the record?  seems like there are many categories of potential "assertions" around older records like this one.

**Comment by dustymc** [comment]
>retroactively assign some sort of transaction?

Ideally, yes I think so. (Realistically, we all have various kinds of resource limitations.)

Do nothing, potential users get a bit of an alert that the usage might not be documented up to current standards.

Using something like https://arctos.database.museum/info/ctDocumentation.cfm?table=ctloan_type#legacy would add a bit of credibility - maybe "this doesn't seem far-fetched, but we have limited records" would be a decent interpretation. (Or I suppose you could use this to just explicitly state "we have no additional evidence beyond the citation" - that might even save future-you some rehashing.)

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctloan_type#pre_accession_transaction (https://github.com/ArctosDB/arctos/issues/4732) would let you get at "we didn't have it then, but maybe the former custodian knows something." (And ideally there'd be something indicating who that might be, but that doesn't always happen even for modern stuff, esp. things like marine mmmals).

**Comment by jrdemboski** [comment]
what's the transaction when somebody downloads our specimen records from Arctos, GBIF, etc., publishes based on the download, and then I can identify specific museum records in their paper or supplemental files?  Many times I'm lucky that I run across those records.  But has there been any discussion about this kind of use of our records under a new transaction category vs. just tagging them as  "Record has a citation but does not have a transaction history."

**Comment by dustymc** [comment]
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctloan_type#data exists just for that sort of thing. You might not know if they looked at some particular record, but you can "loan" everything they might have accessed, which at least keeps stuff you haven't yet cataloged from looking like it might have been used. That adds some value to the publication, and makes it a bit easier to calculate collection usage - that's the idea, anyway.

You might also want to review https://arctos.database.museum/info/ctDocumentation.cfm?table=ctdata_license (what users must do, internally and externally) and https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcollection_terms (what users should do) in manage collection.

**Comment by Jegelewicz** [comment]
> what's the transaction when somebody downloads our specimen records from Arctos, GBIF, etc., publishes based on the download

that is a [data loan](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctloan_type#data)

**Comment by Jegelewicz** [comment]
Hehe great minds and all...

Hey @dustymc we talked around this yesterday in Code Table working hour. Wouldn't it be great to get a report that shows all the "downloaded for research" stuff so that we could create data loans?

**Comment by dustymc** [comment]
Always been there....

<img width="402" alt="Screen Shot 2022-09-09 at 10 15 16 AM" src="https://user-images.githubusercontent.com/5720791/189407878-134a7682-d773-4580-b629-792cbd1138cc.png">

**Comment by Jegelewicz** [comment]
Yes - but that only lets you find stuff by the username of the person who did the download.

![image](https://user-images.githubusercontent.com/5725767/189427840-598d0423-bf1c-4cd8-97eb-1dc989632a81.png)

We were thinking that a more useful search would be downloads that include a certain collection(s).

**Comment by jrdemboski** [comment]
hmm, data loan, I wouldn't really call it a loan.  And why wouldn't that be in the drop down for citations?

**Comment by dustymc** [comment]
Loan==usage, and it's usage. (Sorta - I think some see using data as expected/normal usage that doesn't require any further action.)

Data loans are the one type which involves catalog records instead of parts, so if some sort of usage-documentation is deemed appropriate then they're the tool.

Citations would be an additional step involving https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcitation_type_status (probably "voucher").

**Comment by ewommack** [comment]
> I think some see using data as expected/normal usage that doesn't require any further action

Indubitably, but we still want to know when and how! It's really nice to know which specimens and types of data are being used most. If we had a report that showed that people are downloading specific attribute data for a collection, I could see that report as good evidence to take to a board or director to advocate for making sure that the attribute data is added into a collection.

> Wouldn't it be great to get a report that shows all the "downloaded for research" stuff so that we could create data loans? 

Maybe something that we could sort by date and time too? We get some of those types of stats from our Sketchfab 3D models, but it only tells me how many people view or download a model. I wish there was a way to see at least when. Then I could figure out if maybe it was a class or result of an educational event if they were all clustered. Or if they were spread out over time then maybe that is just a really useful model for all sorts of people.

**Comment by dustymc** [comment]
>downloading specific attribute data for a collection,

https://github.com/ArctosDB/arctos/issues/5035
