### ISSUE TITLE
Need Help with Arctos Error - working in browse/edit unable to create or save changes

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#4923]
# Error Text
Save rejected: FAIL: outcatch -  - ERROR: new row for relation "bulkloader" violates check constraint "ck_accn_noprt": 

# Where it happened
I got this error two places. Browse/Edit Bulkload Data -> working on objects entered by jturcotte (ordered by cat#) -> tried to click on the first collection object ID link and it wouldn't let me. Tried to fix the errors straight in the table and got the above error and wouldn't let me go anywhere else on the page.
Second place -> clicked on UWYMV:Herp:726 Enter from Seed link -> corrected all the errors in the record -> clicked Save New As New Record and got the above error.

https://arctos.database.museum/Bulkloader/browseBulk.cfm

# Steps to get there
Not sure, but it says there was a problem with bulkloading UWYMV:Herp:726, except I do not remember setting that one to bulkload. I thought I stopped yesterday on UWYMV:Herp:725, but I could be wrong and did something funny.

# Solution
Any help would be greatly appreciated. I can't edit any of the entries in the browse and edit at all right now. When I click on any of the others it says the below error now as well:
![Arctos bulkload error](https://user-images.githubusercontent.com/18562884/184003886-d82fcaf0-3be5-47cc-80d7-ae2564c4d371.png)

**Comment by dustymc** [comment]
how about now?

**Comment by ewommack** [comment]
Working now, thanks @dustymc! I tried to fix the attribute problems, but it wouldn't' let me get through any of it.
