### ISSUE TITLE
NMMNH Paleo agent dates

### ISSUE THREAD

**Issue by lin-fred** [ArctosDB/arctos#4924]
Hey @Nicole-Ridgwell-NMMNHS 

When we were looking at some agent dates, we saw this agent https://arctos.database.museum/agents.cfm?agent_id=21270137

With Dusty's new TURD, we were able to catch that the collection dates don't match up with the death/birth date

Take a look over it but our agent committee has suggested setting the collection dates to much up with the birth and death date, so that at least you have a better idea of when they were collected!

Let me know if you are ok with that change. I will ping dusty because we want to make a tool that allows for editing the collecting date easier and we'd like to use this situation as an example and to test.

**Comment by lin-fred** [comment]
The TURD https://arctos.database.museum/Reports/cat_record_reports.cfm

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
This is probably a good example for your use case. This specimen: https://arctos.database.museum/guid/NMMNH:Paleo:49630 says it was collected eight years after Flower's death. It was definitely collected by Flower, but in this case someone misinterpreted Flower's catalog number as a year. The collecting date for this specimen is in fact unknown and should be constrained by Flower's birth and death dates.

Then there are also many records with collecting date unknown, entered with an artificial begin date (1/1/1900) that could also be constrained by his birth and death dates.

**Comment by lin-fred** [comment]
@Nicole-Ridgwell-NMMNHS thanks we will go forward with figuring this out then!

@dustymc we got the go ahead!

**Comment by Jegelewicz** [comment]
Is this already functioning? See also #5153

**Comment by dustymc** [comment]
done?
