### ISSUE TITLE
Bulkload Media Relationships - cache not refreshing?

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#4927]
@dustymc - I loaded a csv to bulkload media relationships yesterday and it doesn't look like anything has happened since I set everything to autoload. Is this loader actively pulling in data?

https://arctos.database.museum/tools/bulkloadMediaRelations.cfm?action=table&username=ebraker

**Comment by dustymc** [comment]
<img width="467" alt="Screen Shot 2022-08-11 at 8 04 11 AM" src="https://user-images.githubusercontent.com/5720791/184165641-d7cdbd0c-4458-46e8-965e-b7b237f46e13.png">

 will tell you what's going on and let you change things.
