### ISSUE TITLE
Unable to delete record in bulkloader

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#4929]
<html>
<body>

ERROR_ID | 59F6D819-D9FC-4A18-8AD911DCF869DDE8
-- | --
ERROR_TYPE | SQL
ERROR_MESSAGE | ERROR: new row for relation "bulkloader" violates check constraint "ck_coll_object_remarks_noprt"
ERROR_DETAIL |  
ERROR_SQL | update bulkloader set status='DELETE' where collection_object_id>1000 and enteredby in ('ssanders_dmns') and collection_object_id in (98022662)

<br class="Apple-interchange-newline">
</body>
</html>

Record in bulkloader contained two spaces in a comment and wouldn't load and I couldn't correct it in the bulkloader itself.  I recreated the record and uploaded it and tried to DELETE the erroneous record but consistently get this error message.  I understand the problem if I'm uploading a record but not if I'm trying to delete it.

If I change the status to DELETE I get this error

![error](https://user-images.githubusercontent.com/15368365/184195715-4a18e107-ecea-4d9a-851d-630f42ce5b71.PNG)

And when I try to make other corrections, I get errors that lock the bulkloader until I refresh - which erases my correction.

![next snip](https://user-images.githubusercontent.com/15368365/184196659-6e42c415-11c6-49c7-bc7a-f1e66a20b743.PNG)

**Comment by dustymc** [comment]
I cleaned up the messes that were blocking (and the messes that were blocking those messes and so on...) and marked that record to delete.
