### ISSUE TITLE
UCM identifiers - data update request

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4930]
Thanks @dustymc  Should I put in a separate issue for UCM for this?:

> Can I also request that for ALL UCM collections, when 'identified by' agent = "unknown" we insert the 'collected by' agent name in catalog records? This will update probably 70% of our records.

_Originally posted by @ebraker in https://github.com/ArctosDB/arctos/issues/4926#issuecomment-1212400011_

**Comment by ebraker** [comment]
@dustymc checking in on this...when does this update happen?

**Comment by dustymc** [comment]
I could use a change of scenery....

**Comment by ebraker** [comment]
The scenery is grand here at UCM ;)

**Comment by dustymc** [comment]
Attached is a view of agents who collected for UCM while ``unknown`` was making determinations.

I've made some merger suggestions from these data and some stuff I stumbled on while checking things in these data. Lots of strangely-spelled alleged persons collecting one thing alongside another alleged person who spells their name ALMOST the same way, one [bird in a trenchcoat](https://arctos.database.museum/agent/21285630), etc. Hopefully all completely noncontroversial. It was super interesting to see (part of) one collection not mixed in with the rest of Arctos, definitely a useful viewpoint for cleanup, maybe what I've done here could serve as the basis for https://github.com/ArctosDB/arctos/issues/4907

I think it would be useful to let the merger suggestions cook and then make another cleanup pass before proceeding, but maybe we can just develop https://github.com/ArctosDB/arctos/issues/4907 such that this can be done at any time. Very open to whatever. So very looking forward to the day when agents aren't just strings!

[temp_ucm_coll_where_id_is_unknown(1).csv.zip](https://github.com/ArctosDB/arctos/files/9522436/temp_ucm_coll_where_id_is_unknown.1.csv.zip)

**Comment by ebraker** [comment]
Thanks @dustymc - I've been ground truthing these agent mergers with ledger lookups - lots look great, but others not so much so I'm trying to make not-the-same-as relationships where I can. Let's simmer until at least October since I'm going to be out of office for a while starting tomorrow.

**Comment by ebraker** [comment]
@dustymc looks like all these mergers went through(?) so I guess we can go ahead and push collector agent to identifier when identifier = unknown.

**Comment by dustymc** [comment]
Here's another CSV dump -  I'll try to get this done this week.

[temp_ucm_coll_where_id_is_unknown(2).csv.zip](https://github.com/ArctosDB/arctos/files/9769058/temp_ucm_coll_where_id_is_unknown.2.csv.zip)

**Comment by dustymc** [comment]
These have some sort of complexity - multiple IDs (and maybe more), I don't think I can readily get them without more info.

[temp_ucm_multiid.csv.zip](https://github.com/ArctosDB/arctos/files/9790691/temp_ucm_multiid.csv.zip)

**Comment by dustymc** [comment]
done
