### ISSUE TITLE
[CONTACT] global data updates for MVZ media (licensing)

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#4931]
@lkvoong @dustymc 
Can you please help with some global updates to MVZ media data:

1) media where type = 'image' and label (type 'media identifier') contains 'MVZ' 
AND media where relationship 'shows cataloged item' like 'MVZ:Egg'

current label of type 'comment' : "Please contact the MVZ Archives (mvzarchives[at]berkeley.edu) for licensing and use of high resolution images. See http://mvz.berkeley.edu/PDFs/MVZ_terms_of_use.pdf"

updated label of type 'comment' : ""Please contact the MVZ Archives (mvzarchives[at]berkeley.edu) for licensing and use of high resolution images. See https://mvz.berkeley.edu/mvzdata_terms" - **NOTE THE UPDATED URL**

2) media where type = 'audio' and label (type 'audio cut number') contains 'MVZ' 

**REPLACE** current license 'MVZ Terms of Use' with CC license 'CC BY'

**INSERT** new comment 'See MVZ Terms of Use (https://mvz.berkeley.edu/mvzdata_terms)'

Let me and @mkoo know if you have any questions. Thanks!

**Comment by dustymc** [comment]
For (1) there are 32057 media labels with that value, you only want to update the 45 that meet your other criteria, correct?

```
select 
media.media_id,
cmt.media_label_id ,
cmt.label_value
from media_labels cmt
inner join media_labels midr on cmt.media_id=midr.media_id 
inner join media on media.media_id=cmt.media_id
inner join media_relations on media.media_id=media_relations.media_id
inner join cataloged_item on media_relations.cataloged_item_id=cataloged_item.collection_object_id
inner join collection on cataloged_item.collection_id=collection.collection_id
where
collection.guid_prefix='MVZ:Egg' and
cmt.media_label='comment' and
media.media_type='image' and
media_relations.media_relationship='shows cataloged_item'
and midr.media_label='media identifier'
and cmt.label_value='Please contact the MVZ Archives (mvzarchives[at]berkeley.edu) for licensing and use of high resolution images. See http://mvz.berkeley.edu/PDFs/MVZ_terms_of_use.pdf'
```

(2) this finds 6665 rows - sound right?
```
select media.media_id from media
inner join media_labels acn on media.media_id=acn.media_id and acn.media_label='audio cut number' and acn.label_value like '%MVZ%'
inner join ctmedia_license on media.media_license_id=ctmedia_license.media_license_id and display='MVZ Terms of Use'
```

Let us know what you need to confirm - you should be able to run that SQL or we can provide CSV or whatever's needed.

**Comment by ccicero** [comment]
@dustymc

(1) I'm not sure what you mean by the other criteria, but "See http://mvz.berkeley.edu/PDFs/MVZ_terms_of_use.pdf" in the comment should be updated globally to "See https://mvz.berkeley.edu/mvzdata_terms." The URL is old/wrong. Definitely more than 45 need updating.

(2) If all MVZ audio have a license, then yes, that number sounds about right. Change all MVZ audio to license CC BY and insert new label of type comment "See MVZ Terms of Use (See https://mvz.berkeley.edu/mvzdata_terms)." If there are MVZ audio without a license, then a CC BY license and comment should be added for those as well.

Make sense?

Thanks!

**Comment by dustymc** [comment]
Can I just replace then?

```

arctosprod@arctos>> select replace(label_value,'http://mvz.berkeley.edu/PDFs/MVZ_terms_of_use.pdf','https://mvz.berkeley.edu/mvzdata_terms'), count(*)  from media_labels where label_value like '%http://mvz.berkeley.edu/PDFs/MVZ_terms_of_use.pdf%' group by replace(label_value,'http://mvz.berkeley.edu/PDFs/MVZ_terms_of_use.pdf','https://mvz.berkeley.edu/mvzdata_terms');
                                                                                                                           replace                                                                                                                           | count 
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------
  Please contact the MVZ Archives (mvzarchives[at]berkeley.edu) for licensing and use of high resolution images. See https://mvz.berkeley.edu/mvzdata_terms                                                                                                  |     1
 Only web versions of MVZ images are licensed under a Creative Commons Attribution License (CC-BY).Please contact the MVZ Archives (mvzarchives[at]berkeley.edu) for licensing and use of high resolution images. See https://mvz.berkeley.edu/mvzdata_terms |     1
 t: Please contact the MVZ Archives (mvzarchives[at]berkeley.edu) for licensing and use of high resolution images. See https://mvz.berkeley.edu/mvzdata_terms                                                                                                |     1
 Please contact the MVZ Archives (mvzarchives[at]berkeley.edu) for licensing and use of high resolution images. See https://mvz.berkeley.edu/mvzdata_terms                                                                                                   | 32057
(4 rows)
```

**Comment by ccicero** [comment]
@dustymc yes, please go ahead and 

1) replace the old URL with the updated one.
2) insert comment for MVZ Audio ""See MVZ Terms of Use (See https://mvz.berkeley.edu/mvzdata_terms)."
3) change media_license for MVZ Audio to CC BY. 

Once that's done, can you check to see if there are any MVZ media files (label contains 'MVZ') without a CC BY license?

Thanks!

**Comment by dustymc** [comment]
Should be done, the only label = MVZ and using the old license is now https://arctos.database.museum/media/10311162

There are another 6867 using the MVZ license but without the label - you can find them with

```
select
distinct media.media_id from
media
where  media_license_id=61
```

**Comment by ccicero** [comment]
@dustymc Sorry it's taken be a while to get back to this. For those other 6867 (related WAV files), we also need to make the same changes:

1) change license to "CC BY"
2) add comment "See MVZ Terms of Use (See https://mvz.berkeley.edu/mvzdata_terms)"

Can you please make those changes, then we can close out this issue? Thanks!

**Comment by dustymc** [comment]
Done - can we zap https://arctos.database.museum/info/ctDocumentation.cfm?table=ctmedia_license#mvz_terms_of_use from the code table?

**Comment by ccicero** [comment]
@dustymc Thanks! Yes, I think we can zap that from the media license CT. 

Are there any MVZ media that have the 'license' "MVZ Archive and Media Policy" ? If so, can you send a list as those should also be CC BY. If not, I think we can zap that as well (we should have a reference to it in the media comments).

Any objections @mkoo ?

**Comment by dustymc** [comment]
>zap

zapped

>Are there any MVZ media that have the 'license' "MVZ Archive and Media Policy" 

```
select
distinct media.media_id from
media
where  media_license_id=21
...
(14680 rows)

**Comment by ccicero** [comment]
@dustymc @mkoo Those seem to be mostly egg data scans, but not all - some bird and herp pics from a quick perusal (e.g., https://arctos.database.museum/media/10242324; https://arctos.database.museum/media/10053375)

I think we can do the same thing:

1) update license to 'CC BY'
2) add comment 'See MVZ Terms of Use (See https://mvz.berkeley.edu/mvzdata_terms)'
3) zap from license code table

That way all are consistent.

**Comment by dustymc** [comment]
Done. Here's IDs Just In Case.

[Archive.zip](https://github.com/ArctosDB/arctos/files/9805390/Archive.zip)
