### ISSUE TITLE
Feature Request - More precise attribute unloader

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4932]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
I am about to unload almost all of the verbatim agent attributes in the UWBM:Mamm collection and then re-load them without numbers. The problem is that right now we have some records that have both a verbatim agent = collector and a verbatim agent = preparator and I really only want to unload the preparator.

**Describe what you're trying to accomplish** 
Leave the collector verbatim agent there and only unload the preparator verbatim agent

**Describe the solution you'd like**
Make the [unloader](https://arctos.database.museum/tools/BulkUnLoadAttribute.cfm) more precise, but don't require precision (I know, I want it all). If I add the attribute value to the unloader, only the attribute with that exact value will be unloaded. If I leave that field NULL, all attributes of that type will be unloaded.

**Describe alternatives you've considered**
Unload and reload attributes that require no change. A pain, but do-able.

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by dustymc** [comment]
Unless someone has some compelling objection I'm going to go ahead with this - I need to write the code, this lets me do that in a way that others can re-use, the simplest use case will still be the current functionality.

> report back the matches found

It can do most anything, but I'll need specifics (and we should justify any added complexity). Probably a new Issue, I think you're asking to change the environment.

**Comment by cjconroy** [comment]
I'd very much appreciate it. I am sure there are many who bulk load a file and moments later realize something went wrong and would like to retract exactly what was in that bulk upload file. Seems like it will be generally useful, even beyond attributes.

**Comment by dustymc** [comment]
In next release.

Also added a targeted download option, and tried out some new magic learned from https://github.com/ArctosDB/arctos/issues/7002 while I was in there.
