### ISSUE TITLE
Arctos Legal - any way to add in IUCN?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4935]
Our current search on Arctos Legal for CITES etc. fails to pull up taxa listed as endangered on the IUCN red list. 
In fact, it lists species in Species+ that are actually listed in that source as not threatened or endangered (see Lithobates catesbianus bullfrog in screenshot below)  but fails to document actual threatened and endangered species (Eleutherodactylus portoricensis on same page). 
I'm wondering whether there is a way for Arctos to include a search of taxa from the IUCN website? https://www.iucnredlist.org/
Wikipedia seems to be able to do this- see https://en.wikipedia.org/wiki/Eleutherodactylus_portoricensis
Right now I'm having to go the the IUCN site and search each taxon one at a time manually, although I could also be searching Wikipedia. Anyone know a better way? Maybe a report?

![Screenshot 2022-08-12 11 17 54](https://user-images.githubusercontent.com/14808196/184411702-3811c898-4e13-458a-831b-d9738982082f.png)
?

**Comment by mkoo** [comment]
Let me initiate a request for an api key so we can harvest their IUCN status. This wont get you CITES or any national protected status, just IUCN assessment results. didnt Taxonomy WG discuss how this would be incorporated?

**Comment by Jegelewicz** [comment]
> didnt Taxonomy WG discuss how this would be incorporated?

@dustymc and I discussed yesterday. I think he has a plan for doing this.

**Comment by dustymc** [comment]
Yep, you'll need to upload a classification. The stuff we get for Arctos Legal from the webservices is pretty spotty, it's neat but I'm not sure its functional.

Minimally the search will be 'ID uses taxa which has source' and the contents of the classification are entirely irrelevant for that - if ANYTHING exists then that's enough. If you need finer-scale filters (eg cites appendix or some taxon term/rank/whatever) then you'll want that included in the source some predictable way. 

See also https://github.com/ArctosDB/arctos/issues/4864

**Comment by mkoo** [comment]
Request submitted (I am also following with email to them). @dustymc I'll send an email with token (hopefully soon)
docs:
https://apiv3.iucnredlist.org/api/v3/docs
examples available there too!

**Comment by campmlc** [comment]
Apparently the CITES list is available via JSON - anyway we can use this to screen Arctos names? 
https://checklist.cites.org/#/en

**Comment by campmlc** [comment]
and thanks @mkoo !

**Comment by dustymc** [comment]
there's a csv link, should be easy enough to manipulate into arctos classification loader format, request a source, load it.
[Index_of_CITES_Species_2022-08-12 18 53.csv.zip](https://github.com/ArctosDB/arctos/files/9328959/Index_of_CITES_Species_2022-08-12.18.53.csv.zip)

**Comment by mkoo** [comment]
ooh that's great about CITES! it used to be a pain to get from their reports and pdfs!

**Comment by dustymc** [comment]
Done?

**Comment by mkoo** [comment]
remind me where IUCN status is in the taxonomy?

**Comment by dustymc** [comment]
Whatever we have is eg https://arctos.database.museum/name/Canis%20lupus#ArctosLegal

If you're loading classifications, you can put it wherever you want it.
