### ISSUE TITLE
Quarantine Taxon Name - Procyon cancrivorous

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4936]
Issue Documentation is at http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

Name Quarantine Documentation is at https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxon_name_type

### Name suggested for quarantine Procyon cancrivorous

[[ INITIALLY REQUIRED: Replace this with a link to the name suggested for quarantine. The link should be of the form https://arctos.database.museum/name/.... ]]
(https://arctos.database.museum/name/Procyon%20cancrivorous#secrel)

### Replacement Name

[ INITIALLY REQUIRED: Replace this with a link to the suggested replacement name. The link should be of the form https://arctos.database.museum/name/.... ]  https://arctos.database.museum/name/Procyon%20cancrivorus

### Reason for quarantine
Procyon cancrivorous is a mispelling of the correct name. There was a single MSB specimen with the mispelled identification, which I have corrected. I have added the publication providing the author date (Cuvier 1798) to the correct spelling.  This is the single record formerly using this ID: https://arctos.database.museum/guid/MSB:Mamm:211340

[ INITIALLY REQUIRED: Replace this with the reason for quarantine, links to sources are extremely useful ]

[ The following steps are not required for the initial request, and may be completed by community members with sufficient access. Please do not remove the text below. ]

### Relationship

[ INITIALLY OPTIONAL, requires manage_taxonomy access: Create a suitable taxon relationship between the nominated and replacement name. ]

### Taxonomy Committee Project

[ INITIALLY OPTIONAL: Please add this issue to the Taxonomy Committee Project. ]

### Collection Summary and Contacts

[ INITIALLY OPTIONAL, requires manage_taxonomy access: use the Manage Data / Metadata / Quarantine Taxon tool to provide a summary of the collections using the nominated name. Make sure the github contacts are outside any code block; they should turn into links. ]

### Data

[ INITIALLY OPTIONAL, requires manage_taxonomy access: use the Manage Data / Metadata / Quarantine Taxon tool to provide data sufficient to un-do this action ]

### Pause

Allow 30 days for all affected collections to respond. Proceed only after 30 days (and an issues committee meeting) has passed, or after all affected collections have approved the quarantine proposal.

### Update Identifications

[ AFTER PAUSE, requires manage_taxonomy and global_admin access: use the Manage Data / Metadata / Quarantine Taxon tool to update identifications. The tool will change all ID formulae to "A {string}" and move all references to the quarantined taxon to the replacement. ]

### Finalize Quarantine

[ AFTER PAUSE, requires manage_taxonomy and global_admin access: use the Manage Data / Metadata / Quarantine Taxon tool to quarantine the taxon name, making it unavailable for all use excepting relationships ]

### Close this issue

[ After all of the above have been completed, close this issue ]

**Comment by Jegelewicz** [comment]
Done.
