### ISSUE TITLE
drop address type ftp

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4940]
There are only two, they're probably not valid, lose nothing and clean up the code table

**Comment by Jegelewicz** [comment]
Aren't these used to distinguish for printing shipping labels on loans? I'm not sure what code table you are looking at because there are lots of address types - https://arctos.database.museum/info/ctDocumentation.cfm?table=ctaddress_type

**Comment by Jegelewicz** [comment]
Oh wait, I get it now....https://arctos.database.museum/info/ctDocumentation.cfm?table=ctaddress_type#ftp

**Comment by lin-fred** [comment]
agent committee approves

**Comment by dustymc** [comment]
Done

[temp_ftp_addr.csv.zip](https://github.com/ArctosDB/arctos/files/9922316/temp_ftp_addr.csv.zip)
