### ISSUE TITLE
error feedback

### ISSUE THREAD

**Issue by Neto97** [ArctosDB/arctos#4942]
318C8554-DEA9-4CD2-AE3FB2CC86CD4132

when trying to access the page, the error message was displayed

**Comment by dustymc** [comment]
I'm not sure what is going on, the error looks like you're simultaneously requesting `/` and rejecting the redirect to the root URL.

Are you perhaps using some misconfigured proxy, translation software, "virus blocker," on a "free" VPN, etc? 

More information - perhaps a screenshot - would be useful.
