### ISSUE TITLE
Code Table Request - add Spathian to informal chronostratigraphy

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#4943]
**Goal**
Add Spathian, a subdivision of the Lower Triassic Olenekian not on the International Chronostratigraphic Chart, to the informal chronostratigraphy code table.

**Context**
I have locality records with this value.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctchronostrat_informal

**Proposed Value**
Spathian

**Proposed Definition**
The Olenekian is sometimes divided into the Smithian and the Spathian subages or substages [Wikipedia](https://en.wikipedia.org/wiki/Olenekian)

If there are not objections, I will add this tomorrow.

**Comment by Jegelewicz** [comment]
None here. @aklompma

**Comment by aklompma** [comment]
Sounds good

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Added
