### ISSUE TITLE
Arctos Error / Is there another way to change GUID?

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#4944]
There are 55 catalog records that were mistakenly [entered into the wrong collection.](https://arctos.database.museum/saved/Change%20to%20CHAS%3ATeach) The specimens are in CHAS:Inv when they should be in CHAS:Teach. The catalog records are currently [encumbered](https://arctos.database.museum/SpecimenResults.cfm?encumbrance_id=10000606).

When I clone an individual record using Option Two, it does not copy the loan information or projects associated with the catalog record. Example: [CHAS:Inv:E2019G.1](https://arctos.database.museum/guid/CHAS:Inv:E2019G.1) and the clone, [CHAS:Teach:E2019G.1](https://arctos.database.museum/guid/CHAS:Teach:E2019G.1).

When I try Option One, I get the following error message (but I don't think this will solve my issue, because I won't have the opportunity to change the GUID to CHAS:Teach):
created [ERROR: ERROR: invalid input syntax for type numeric: "2019.10.110" Where: SQL statement "select max((cat_num)::numeric ) + 1 from cataloged_item where collection_id=oldCollectionID" PL/pgSQL function clone_cataloged_item(text) line 37 at SQL statement - Parameter types passed (2): CF_SQL_VARCHAR, CF_SQL_VARCHAR](https://arctos.database.museum/guid/ERROR:%20ERROR:%20invalid%20input%20syntax%20for%20type%20numeric:)

I also tried downloading all the catalog records from "Manage - Download for Specimen Bulkloader", but it does not appear that the loan / project information is downloaded in this bulkload. When I upload the csv to the bulkloader, it gives me this error (likely from a duplicate ID number? - although I did not have this issue when I cloned the individual record):
duplicate key value violates unique constraint "iu_catitem_catnum_collid"

Is there any way I can clone the records and not have to manually add them back into loans / projects?
Is there an easier way to change the collection/GUID that I am missing?

**Comment by dustymc** [comment]
There's inline documentation regarding your error

> This option will fail for collections which do not use integer catalog numbers. 

No, you can't change collection, that'd provide a path to bypass all security rules, but @lkvoong has a magic wand....

**Comment by lkvoong** [comment]
@wellerjes 
I can move the 55 records from CHAS:Inv to CHAS:Teach.  Can you confirm that the catnums should remain the same? E.g. CHAS:Inv:E2019G.1 CHAS:Teach:E2019G.1

**Comment by wellerjes** [comment]
Thank you! Yes, the catalog numbers should remain the same.

**Comment by wellerjes** [comment]
I deleted the incorrect version of CHAS:Teach:E2019G.1, so there will be 55 records total.

**Comment by lkvoong** [comment]
@wellerjes 
I moved the 55 CHAS:Inv records to CHAS:Teach.  Usually, when I migrate records to another collection, I add Other ID Num, and redirect records so that people looking for the record using the old GUID can be redirected to the new record.  Can you confirm that this is not needed?

**Comment by wellerjes** [comment]
These catalog numbers do not need a redirect. Thank you!
