### ISSUE TITLE
Cannot delete Agent Names 

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#4946]
**Describe the bug**
Trying to clean up an agent record and need to DELETE an AKA (see https://arctos.database.museum/agents.cfm?agent_id=10015024 and the aka= 0000-0002-9562-5585) One of the ```aka```  is his ORCID number. This has been moved to the address type and now I cannot delete the aka. No error message ensues.

**To Reproduce**
1. Go to ['edit agent'](https://arctos.database.museum/agents.cfm?agent_id=10015024)
2. Change the ```aka``` which lists "0000-0002-9562-5585" to DELETE
3. Save changes
4. No changes happen, no errors

TESTED in FF, Opera, Chrome

Low priority

**Comment by dustymc** [comment]
This is from https://github.com/ArctosDB/arctos/issues/3761, I'd be OH SO VERY happy to drop that, I'm not convinced acting like Clippy is ever a good idea (and here we are, again...) but I already lost that argument once....
