### ISSUE TITLE
Curatorial Search Request - SQL to find container type of large series of containers

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4947]
**Describe what you are trying to accomplish** 
Some way of finding out which of a series of barcodes have been used and converted from labels to containers, and which are still labels. I'd like to be able to input a list of barcodes, or even better - a start and end barcode, and specify if the series is base 10 or base 36. 

**List the fields that you would like to see in your results table**
barcode
label
container type
institution

Priority: reasonably high; just found out MSB divisions are doing weird workarounds "scanning" part labels on data sheets into non-existent containers to convert labels to cryovials in order to catalog records before cryovials have been scanned in DGR and autoconverted to cryovials. Need to sort out the mess.

**Comment by dustymc** [comment]
check data services

**Comment by campmlc** [comment]
Thanks!
