### ISSUE TITLE
Code Table Request - new keyword for art collections

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4948]
**Goal**
See https://github.com/ArctosDB/arctos/issues/2362#issuecomment-1218316801

**Context**
properly describe artwork subjects

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctsubject_term

**Proposed Value**
tourism

**Proposed Definition**
The industry providing facilities and services to people traveling for recreation. [AAT ID: 300132466](http://vocab.getty.edu/page/aat/300132466)

**Priority**
[  Please choose a priority-label to the right.  ]

@krgomez please make sure I have translated this correctly!

**Comment by krgomez** [comment]
Looks good to me - thanks Teresa.

**Comment by Jegelewicz** [comment]
Suggest we add

**Comment by Jegelewicz** [comment]
Code Table says go

**Comment by Jegelewicz** [comment]
added
