### ISSUE TITLE
Bulk Edit Container Reset Record Limit not functioning

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4951]
In Bulk Edit Container, Review for this user/status - there is an option to "reset record limit" from 250 to 2500 record default up to 5000  and 10000. I need to mark 40-80K records to autoload - probably should have used status in the csv. But since I didn't, it is a lot of clicks to get them to autoload 2500 at a time. 
Can we get the 5000 and 10000 record options to work, or is this browser limited?
![Screenshot 2022-08-17 17 46 37](https://user-images.githubusercontent.com/14808196/185263133-b8110da0-999a-4917-86b8-627655d220f6.png)

Priority: normal

**Comment by campmlc** [comment]
Firefox and Chrome both

**Comment by Jegelewicz** [comment]
I noticed the same thing in the Other ID number load batch tool last week - just did a lot of clicks. It doesn't happen often, but I do sometimes have large files in the component loaders so it would be nice to review more at one time - although using the status in the original file is an option, I often forget that...

**Comment by dustymc** [comment]
>Can we get the 5000 and 10000 record options to work, or is this browser limited?

Yes and yes. I could set that to whatever, but it will with some data in some forms assuredly eat your browser. I think about 99% of the time that causes more complaints than the rare instance of having to click a button a few times, but that's not a technical limitation.
