### ISSUE TITLE
Code Table Request - add Langston Formation and Spence Shale Member

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#4952]
**Goal**
Add Langston Formation and Spence Shale Member to the lithostratigraphic formation and lithostratigraphic member tables respectively.

**Context**
Values are needed for new localities.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlithostratigraphic_formation
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlithostratigraphic_member

**Proposed Value**
Langston Formation
Spence Shale Member

**Proposed Definition**
Langston Formation - A Cambrian unit that outcrops in Idaho and Utah, composed primarily of dolomite and limestone. [Geolex](https://ngmdb.usgs.gov/Geolex/Units/Langston_9262.html)
Spence Shale Member - A Cambrian unit that outcrops in Idaho and Utah [Geolex](https://ngmdb.usgs.gov/Geolex/Units/Spence_10517.html)

If there are no objections, I will add this tomorrow.

**Comment by Jegelewicz** [comment]
Code Tables says go!

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Added
