### ISSUE TITLE
Code Table Request - New Other ID num type - TAMUIC 

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#4953]
**Goal**
Create other ID type for the Texas A&M University Insect Collection

**Context**
MVZ was just informed that the TAMUIC have ectoparasites in their collection from mammal and bird vouchers at MVZ. It would be great to cross list these values in Arctos. 

**Proposed Value**
TAMUIC: Texas A&M University Insect Collection

**Proposed Definition**
[ Clear, complete, non-collection-type-specific definition of the new value. ]

**Collection type**
[ If the code table includes a "Collection" column. Ex: Mamm, Herp, ES ]

**Other ID BaseURL**
As far as I know there is no URL link to the records at Texas A&M University Insect Collection

**Priority**
[ Low. This effects only 6 mammals and potentially 5 birds. If this is too few, I can put the values into a remark field ]

**Comment by Jegelewicz** [comment]
I'm not opposed to this. Pretty sure there will be more as time goes on. @ArctosDB/arctos-code-table-administrators any thoughts?

**Comment by cjconroy** [comment]
Any progress on this? It would be nice to get this done. Thanks.

**Comment by campmlc** [comment]
I'd like to clarify that this number is their barcode.

**Comment by campmlc** [comment]
And we also need this at MSB.

**Comment by Jegelewicz** [comment]
So for

**Proposed Definition**
Texas A&M University Insect Collection barcode

should the term be
TAMUIC: Texas A&M University Insect Collection Barcode

In other words, may there be other kinds of TAMUIC: Texas A&M University Insect Collection numbers?

**Comment by cjconroy** [comment]
I will ask them. I don't have any plans to add anything. They just informed me of the existing material.

**Comment by campmlc** [comment]
I asked them  - they haven't really thought about it.  They use their barcodes as catnums. They also feed to SCAN which will provide a Guid- we should check scan to see if anything already published. But I think it is worth explicitly stating this is a barcode value, especially since it is non numeric. I'd suggest TAMUIC: Texas A&M University Insect Collection Barcode.

**Comment by campmlc** [comment]
OK if I add this? We need to move forward with uploading these data.

**Comment by Jegelewicz** [comment]
If [this](https://github.com/ArctosDB/arctos/issues/4953#issuecomment-1232243428) - then I say OK. @ArctosDB/arctos-code-table-administrators

**Comment by campmlc** [comment]
Yep. TAMUIC: Texas A&M University Insect Collection Barcode

**Comment by campmlc** [comment]
Completed.

**Comment by dustymc** [comment]
This was not done in accordance with the [guidelines](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html#specific-values-considerations) - please fix.

>In addition - add the link to the Github Issue in which the code table request was approved. For example:
