### ISSUE TITLE
Data Entry_Age in bird format does not write to the age attribute anymore

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#4955]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
When using the bird format for the data entry form it has the age attribute up top, which then rewrites to the attribute table below. That still works great, but because we changed the age code table to not be free text any more the rewrite no longer works. It doesn't actually choose an attribute when it send the info to the attribute table at all.
![Arctos error_dataentry](https://user-images.githubusercontent.com/18562884/185665592-c325128d-2389-4d60-b350-1130be4fd88d.png)

**To Reproduce**
Go to Data Entry -> click the customize button above the attribute table -> under the Helper select bird -> Save settings -> go back to data entry and enter in free text in the Age field at the top of the table.

**Expected behavior**
We should probably change the Age field in the bird helper to be a selection of the terms now allowed for Age Class attributes. Age doesn't exist anymore as a free text field.

**Desktop (please complete the following information):**
Mac OS desktop, chrome

@ccicero - might be important since I think you use the data entry page as well.

**Comment by ccicero** [comment]
What?!! We no longer have a free text 'age' field anymore? That doesn't work for birds. 

We need an age class but also a way of entering free text data because bird age data doesn't always fit nicely into age classes (e.g., 3rd winter [plumage]; adult skull, first year wings and tail; etc.). MVZ first migrated to Arctos, we tried putting our age data into 'age class' and gave up, so we've been entering all age data in the free text field.

@dustymc Please explain how we're supposed to handle these data.

**Comment by ccicero** [comment]
I also changed the priority to 'high' as this is needed for work.

**Comment by dustymc** [comment]
"What?!!" indeed.....

I don't have enough information to know what's going on, but it's not ^^ that.

<img width="192" alt="Screen Shot 2022-08-19 at 10 04 09 AM" src="https://user-images.githubusercontent.com/5720791/185670858-f292715d-91d6-48aa-9a89-2d552bb40a4f.png">

**Comment by ccicero** [comment]
Phew! @ewommack I just tried and it filled it in for me too.

**Comment by ewommack** [comment]
Ah I know what went funny. I was entering a herp record but had my bird attributes turned on. So maybe a lesson in that you can select any data entry customization for any collection, but they will not always work for each collection?

**Comment by ccicero** [comment]
Good to know. Seems like the customization should depend on the collection type for things like attributes that are collection specific.

**Comment by ewommack** [comment]
I think the plan is eventually any collection can choose any attribute in the future. It's not a huge issue now, and the error pick up got it right away. I just need to remember to switch my customization between groups.
