### ISSUE TITLE
Can't Reset Password? [CONTACT]

### ISSUE THREAD

**Issue by dallinkohler** [ArctosDB/arctos#4956]
Hi, 

Arctos won't let me log in; when I put in my username and password it says "Authentication failed. Additional Information: Authentication failure."

I attempted to reset my password multiple times using my email address but I never got an email (and I checked my spam). 

My username is Dallinkohler and the email associated with the account is dallinkohler@gmail.com

Is there anything I can do? I had the same problem yesterday and I figured Arctos was just having some sort of issue but it didn't work today either so I figured I'd ask.

Thanks

**Comment by dustymc** [comment]
I reset and emailed you your most recent password - let me know if that doesn't work and can I hard reset.

https://github.com/ArctosDB/arctos/issues/4767
