### ISSUE TITLE
Feature Request - hyperlink to Borrows from Project

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#4958]
In Projects I would like to be able to directly connect to the Borrows that contribute to it. Currently I can only see the Borrows if I make them public and then they show up on the Project Detail page without a hyperlink:

https://arctos.database.museum/project/10003942
<img width="1081" alt="Screen Shot 2022-08-19 at 10 21 12 AM" src="https://user-images.githubusercontent.com/17605945/185682786-0e552e9a-15ff-438f-a4cf-f5c330377cfc.png">

**Describe what you're trying to accomplish** 
In Edit Project you can directly connect to several types of things, including Accessions, Loans, Publications, and Taxonomy. I would also like to be able to directly connect to a Borrow with a live hyperlink.

**Describe the solution you'd like**
Insert a **"Project Borrows"** section on the Edit Project page.

<img width="1028" alt="Screen Shot 2022-08-19 at 10 15 25 AM" src="https://user-images.githubusercontent.com/17605945/185682473-42160aea-e2f6-4dfe-85de-77de9da5e4b9.png">

**Priority**
Please assign a priority-label. 
Medium - It would be a very nice improvement by allowing Borrows to stay not-public, but save many clicks to get to the info I want.

**Comment by dustymc** [comment]
I think this is a request to show borrows from the edit project page??

**Comment by AJLinn** [comment]
Yes please.
