### ISSUE TITLE
Cryovial count request

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4959]
I need to know how many cryovials have been scanned into position in DGR (for the first time - e.g. not just moved within DGR )since  2022-01-01.
I'd like to have this be a regular report I can run for whatever period of dates required.
I can't figure out any way to use the current Find Container interface to come up with this info- and apologies,
I know I've asked this question before, but I haven't been able to find the search or the answer.
Priority: high; grant report

**Comment by campmlc** [comment]
So I found this SQL - which looks like it might work, but it makes no sense for 2022 results. We did not bring in >200,000 cryovials this year. Any help in interpreting why we might be getting such unrealistic numbers?

select to_char(PARENT_INSTALL_DATE,'YYYY'),count(*) from container where container_type='cryovial' and institution_acronym in ('MSB','DGR') group by to_char(PARENT_INSTALL_DATE,'YYYY') order by to_char(PARENT_INSTALL_DATE,'YYYY');

![Screenshot 2022-08-19 16 08 35](https://user-images.githubusercontent.com/14808196/185713571-d4bb59e6-0921-4a40-9c57-dcaafd917ef9.png)

**Comment by campmlc** [comment]
I'm guessing this includes things that were moved from ultralow freezers into cryotanks. So I will need the SQL after all - a means of restricting the search to just first scan only in DGR containers. I need an estimate for the number of tissues accessioned into DGR, as all our accessions are by cataloged items in other divisions, not by cryovials.

**Comment by campmlc** [comment]
Found more SQL - this may work? Please let me know if so, and I'll leave it posted here for future reference:

with recursive subordinates as (
    select
        container.container_id,
        container.container_type,
        container.parent_install_date,
        container.institution_acronym,
        0 lvl
    from
        container
    where
        container.barcode='DGR'
    union
    select
        e.container_id,
        e.container_type,
        e.parent_install_date,
        e.institution_acronym,
        s.lvl + 1 lvl
    from
        container e
        inner join subordinates s ON s.container_id = e.parent_container_id
    -- this prevents infinite recursion
    where lvl<20
) select 
   to_char(parent_install_date,'YYYY'),
   count(*) c
from 
    subordinates 
where 
    container_type='cryovial' and 
    institution_acronym in ('MSB','DGR') 
group by 
    to_char(parent_install_date,'YYYY') 
order by 
    to_char(parent_install_date,'YYYY')
;

**Comment by campmlc** [comment]
Better formatting: 
with recursive subordinates as ( select container.container_id, container.container_type, container.parent_install_date, container.institution_acronym, 0 lvl from container where container.barcode='DGR' union select e.container_id, e.container_type, e.parent_install_date, e.institution_acronym, s.lvl + 1 lvl from container e inner join subordinates s ON s.container_id = e.parent_container_id -- this prevents infinite recursion where lvl<20 ) select to_char(parent_install_date,'YYYY'), count(*) c from subordinates where container_type='cryovial' and institution_acronym in ('MSB','DGR') group by to_char(parent_install_date,'YYYY') order by to_char(parent_install_date,'YYYY') ;

![Screenshot 2022-08-19 16 19 34](https://user-images.githubusercontent.com/14808196/185714404-2bfb2de7-1700-4c4c-89cc-ed36f6188a6f.png)

**Comment by dustymc** [comment]
Yep, that's it.

You need to take the comment out (lest something random happen) if you're going to oneline it.

```
with recursive subordinates as ( select container.container_id, container.container_type, container.parent_install_date, container.institution_acronym, 0 lvl from container where container.barcode='DGR' union select e.container_id, e.container_type, e.parent_install_date, e.institution_acronym, s.lvl + 1 lvl from container e inner join subordinates s ON s.container_id = e.parent_container_id where lvl<20 ) select to_char(parent_install_date,'YYYY'), count(*) c from subordinates where container_type='cryovial' and institution_acronym in ('MSB','DGR') group by to_char(parent_install_date,'YYYY') order by to_char(parent_install_date,'YYYY')
```

**Comment by campmlc** [comment]
Fantastic - thanks!

**Comment by Jegelewicz** [comment]
Added to [SQL cheat sheet](https://docs.google.com/document/d/15e3b8WNErFPqg1SW-QNq0nI_RjiEEZjWQDznxIJNFHE/edit#heading=h.hh5gczfbgec1)
