### ISSUE TITLE
[CONTACT] Locked out of account

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#4962]
I typed in the wrong password twice(?) and seem to have gotten locked out of my account. When I try to login I get the message "Authentication failed. Additional Information: Access restricted." I tried resetting my password, but still get the same message.

**Comment by dustymc** [comment]
reset

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thank you!
