### ISSUE TITLE
Curatorial Search Request - # citations

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#4963]
@dustymc For the Arctos presentation in Sept:

- I'm hoping to give a summary of total # citations across all of Arctos (not necessarily number of cataloged records since something could be cited in 3 different publications). 

- I'd also like to include # of publications with citations (I see in System Statistics ~10K pubs, but I assume some may not be linked with records...just need a total for "actively linked" pubs).

Thanks!

**Comment by dustymc** [comment]
```
arctosprod@arctos>> select count(*) from citation;
 count  
--------
 378526
(1 row)

Time: 48.593 ms
arctosprod@arctos>> select count(distinct(publication_id)) from citation;
 count 
-------
  3842
(1 row)
```

**Comment by ebraker** [comment]
Thank you! So speedy!
