### ISSUE TITLE
agent status date accepted (blank)

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4976]
I have fixed that bug, here are the status values which slipped through. I don't think there's anything worth recovering here ("was apparently alive at some point"??) but here are the data if someone wants them.

[temp_agentstatusnull.csv.zip](https://github.com/ArctosDB/arctos/files/9419651/temp_agentstatusnull.csv.zip)

/remind me to close this in a week

**Comment by ewommack** [comment]
@Jegelewicz - the reminder bot is back!
