### ISSUE TITLE
Preservation part attribute not pulling up field for value entry

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4979]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
The preservation part attribute, when selected, does not pull up the field to allow the value for the preservation to be entered.

**To Reproduce**
1. Go to Catallog Record view
2. Click on Edit Part
3. Scroll down to Manage Attributes
4. Select Preservation
5. See that no field opens up to enter value or units.

**Expected behavior**
To be able to add a preservation attribute value and units.

**Screenshots**
![Screenshot 2022-08-24 19 22 14](https://user-images.githubusercontent.com/14808196/186553271-1a7ee503-b686-4f78-9c88-443c445547e7.png)

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Firefox

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by dustymc** [comment]
patched (js compressor was having a bad hair day)
