### ISSUE TITLE
Cannot find a specific article by string "Thomas"

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#4981]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
This article is in Arctos. 
Thomas, W. K., S. Pääbo, F. X. Villablanca, and A. C. Wilson. 1990. Spatial and temporal continuity of kangaroo rat populations shown by sequencing mitochondrial DNA from museum specimens. Journal of Molecular Evolution 31:101–112. Springer Science and Business Media LLC.

I cannot find the article by searching Title or Full Citation, or Participant with word "Thomas". 35 papers come up, but not this one. If you search Title or Full Citation by just "Villablanca" it does come up. Also, if you search Participant by "W. Kelley Thomas" it comes up, as that agent is linked to it. 

Furthermore, if you search participant by "Thomas" you cannot find it, but you can find it by "Villablanca".

So, why can I find it by Villablanca, but not by Thomas? I have also downloaded all the results from a search on Thomas, but it is not in there.  Is this an Arctos glitch, or my browser?

One last thing. If you search Title or Full Citation by "Thomas,", it does come up. 

**To Reproduce**
Search as written above

**Expected behavior**
This article should come back from a search with the text "Thomas" in either search field.

**Desktop (please complete the following information):**
 MacOS 10.14.6, Chrome 104.0.5112.101

**Priority**
Medium. General Arctos weirdness.

**Comment by dustymc** [comment]
patched
