### ISSUE TITLE
bulkloader and verification status

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#4982]
Why does the bulkloader limit verification status to unverified? I realize there is a way to change it afterward, but what is the point of the extra step? I've tried looking in documentation and through github issues and can't find the reason for this. The only thing I found was in How to Bulkload Catalog Records and it just says "Anything else will lock this section and cannot be changed." What does that even mean?

**Comment by dustymc** [comment]
The general idea is that you can't verify something before its in Arctos, where you still have an opportunity to mistranscribe it or view it under some wonky projection or etc. IDK if that still makes sense (yes but no, probably?), definitely needs better docs either way.

**Comment by Jegelewicz** [comment]
This is very annoying when a curator or collection manager has done the work to verify data, then has to do it again.

**Comment by dustymc** [comment]
No amount of work can result in "verified" as long as they data can still be manipulated (eg mangled by Excel) outside of Arctos - or so goes the theory.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
You still have the opportunity to review the data for mangling in the bulkloader though. Maybe at least allow "accepted" and "unaccepted" but not "verified and locked"?

**Comment by dustymc** [comment]
Merging https://github.com/ArctosDB/arctos/issues/5392 into here, it seems useful to include it in the conversation. If we keep the current idea, I think it would result in clones of 'verified and locked' becoming 'accepted.' 

>at least allow "accepted" and "unaccepted"

Seems reasonable to me. Tentatively going next task....

**Comment by Jegelewicz** [comment]
> Currently event verification status is forced to be unverified for a bulkload. If we are keeping this constraint, there is no reason to have this column in the bulkloader, since nothing else will load.
I personally suggest we abandon this constraint, as I doubt there is a single collection with the time and collector and staff resources to incorporate updating all these values after load into their workflows. If we know that an event is accepted during data entry, we should be able to enter that. Otherwise we end up with entire collections full of "unverified" values merely because of the bulkloader constraint, not because other information is unavailable. This defeats the purpose of recording these data.

from https://github.com/ArctosDB/arctos/issues/5193#issuecomment-1509936715

**Comment by mkoo** [comment]
Needs to be discussed further. See next Arctos Happy Hour
2023-04-27 5PM MDT (Arctos calendar has links)

**Comment by dustymc** [comment]
I'm so lost, I think we spent an hour or so trying to get back to where we were a [few months ago](https://github.com/ArctosDB/arctos/issues/4982#issuecomment-1359683134) yesterday?? Can someone please spell out what we're trying to accomplish?

**Comment by campmlc** [comment]
My understanding is that we agreed yesterday to allow accepted as an option
in the verification status field, which means we also add in verified by
and verified date?

**Comment by campmlc** [comment]
But if that will cause huge problems, the alternative is to delete the
column entirely as the default is forced to unverified.

**Comment by dustymc** [comment]
I am now loster. Is that the same as or different than where we were a [few months ago](https://github.com/ArctosDB/arctos/issues/4982#issuecomment-1359683134), and in the current bulkloader proposal?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> My understanding is that we agreed yesterday to allow accepted as an option in the verification status field

This was my impression as well.

**Comment by campmlc** [comment]
@Jegelewicz

**Comment by dustymc** [comment]
>currently

Yes, it takes time to do things, and https://github.com/ArctosDB/arctos/issues/5331 (along with everyhting else bulkloader-related) is being blocked by https://github.com/ArctosDB/arctos/issues/6171.

**Comment by campmlc** [comment]
In that case, this is a non- issue?

**Comment by ewommack** [comment]
Here's what I recorded during the AWG meeting:

Verification Status -> at the moment “verificationstatus” will only allow unverified as the only thing can be entered into it

- Proposed changes is that you change to verification status - verified or unverified into the Bulkloader.
- Discussion unsure on if this is a step that should be allowed in bulkloader ability.

**Comment by Jegelewicz** [comment]
Final update

Once the bulkloader is rebuilt verfication status can be entered as unverfied, accepted, unaccepted. Using verified and locked will still require manual review.

**Comment by Jegelewicz** [comment]
@dustymc I think we can remove the blocked label?
