### ISSUE TITLE
[ geography request ] Okanagan-Similkameen Regional District

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4985]
Download and populate the following CSV template to request geography.

(Not seeing a link? Click "preview.")

[geog_template.csv](https://github.com/ArctosDB/arctos/files/9246027/geog_template.csv)

Carefully read the documentation at https://handbook.arctosdb.org/documentation/higher-geography.html before submitting a request.

``spatial_footprint`` may be anything that can be made into ``geography`` data - WKT usually converts easiest. (Or ask for help - we have or can get spatial data for most geography-like places.)

``search_terms`` is a pipe-delimited list of search terms; these are optional but recommended.

``the_issue`` is the URL of the Issue in which the geography is requested (and discussed as necessary). This is required.

**Comment by dustymc** [comment]
[geog_template(2).csv](https://github.com/ArctosDB/arctos/files/9447432/geog_template.2.csv)

[done](https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10016385)

@mkoo @ccicero

**Comment by mkoo** [comment]
ah ok so now I can upload a footprint?

**Comment by dustymc** [comment]
> upload a footprint?

You can
<img width="615" alt="Screen Shot 2022-08-29 at 1 00 10 PM" src="https://user-images.githubusercontent.com/5720791/187287674-d0ae31fc-8eb8-4bb0-ada7-45dae33ad96c.png">

but its already got one

<img width="763" alt="Screen Shot 2022-08-29 at 12 59 56 PM" src="https://user-images.githubusercontent.com/5720791/187287717-3bfb764e-4cab-418d-a51b-15034af83829.png">

I'm still struggling to figure out what we as a community would like to be doing with geography, but assuming that involves any sort of consistency or overlap with whatever anyone else might be doing, its almost certainly better to use some standard polygon (and geography which appears in the standard sources). I have back-end tools to load those, but I've already pulled GADM for a few dozen countries along with some other stuff - just ask if you need more.

You can get to those via....

<img width="717" alt="Screen Shot 2022-08-29 at 1 05 09 PM" src="https://user-images.githubusercontent.com/5720791/187288449-d0bdcc1b-f967-4f01-a57f-63a4a1bc9043.png">

but the UI is super twitchy, in part because https://github.com/ArctosDB/arctos/issues/4783

When and if I get island data I'll load it to the same place.
