### ISSUE TITLE
Reports not working

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4986]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
From an Edit loan form, click Print Any Report, Select Print Any Report at 
http://reports.arctos.database.museum/reporter/report_printer.cfm?auth_key=6F3E0DAA-137E-48E1-A6D6919D501BB795&transaction_id=21134073
Get "nope" as result

**To Reproduce**
Steps to reproduce the behavior: see above

**Expected behavior**

**Screenshots**

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome (happened once in Firefox, then worked in Firefox)

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by dustymc** [comment]
This is almost always from a nonlinear approach, usually something about getting lost in a sea of tabs. The reporter is functioning.

**Comment by ccicero** [comment]
@dustymc Jim Patton is trying to print mammal labels and the link to the old reporter with our labels is not working. It just spins and then times out. Since we don't yet have labels in the new format, we need to be able to access the old labels.

**Comment by ccicero** [comment]
I'm also trying to print from the old reporter and it's not working (both Chrome and FF).

**Comment by dustymc** [comment]
Doesn't seem to be anything I can control, I'll see if Chris can revive it.

**Comment by sharpphyl** [comment]
I can't print either.  

![snip2](https://user-images.githubusercontent.com/15368365/187976570-b76c53da-e0bc-4ad3-86f8-ae25517f6d1c.PNG)

![snip 1](https://user-images.githubusercontent.com/15368365/187976559-a93bdf46-72e3-47c8-9b83-e66b733de8ee.PNG)

**Comment by dustymc** [comment]
TACC is aware of this and working on a solution.

**Comment by ebraker** [comment]
Can we get a timeline from Chris? I've got three loans packed and ready to ship...I'm just waiting on printing out the invoices.

**Comment by ccicero** [comment]
@dustymc Yes, this is critical. Any update?

**Comment by dustymc** [comment]
The person who can fix this is out today, probably tomorrow.

**Comment by dustymc** [comment]
If anyone wants to use this as an opportunity to upgrade to the new reporter, just send us whatever information you have (example, old report name, etc. - more is better) and we'll get that started.

**Comment by campmlc** [comment]
I can't get the old report name without access to the old reporter, unfortunately . . . but I need MSB mammal, bird, herp loan invoices with the 2021 suffix.

**Comment by campmlc** [comment]
MSB loan invoices and loan headers with 2021 suffix.

**Comment by dustymc** [comment]
We can use the report name to get SQL, which isn't that useful for loans. We need an example to develop anything.

**Comment by campmlc** [comment]
I'll email some examples of ones we've used?

**Comment by campmlc** [comment]
Email sent.

**Comment by campmlc** [comment]
And we do use the SQL in the loan forms.

**Comment by dustymc** [comment]
Got them, questions:

What does "I'd like to be able to tweak these" mean? If you've got some redesign or whatever in mind it would be very useful to know about it before we write a bunch of code you don't want to use.

What does "we do use the SQL in the loan forms" mean?

**Comment by campmlc** [comment]
Apologies - by tweaking, I mean that for some collections, we need the option of the invoice displaying either NK or collector number or prep number or field number etc. . . . - sometimes it depends on the loan items. I don't know how much flexibility there is in html. Can we do "if this, then this, if not, then that, etc etc for a list"?) 
Also would be good to have loan item remarks display across the board, as on the Herp invoice. 
Remove subsample on mammal forms or replace with y/n - it certainly isn't working. Null doesn't mean anything - these are all subsamples. 
I guess I thought that we are using SQL to query the database for agent names and roles, addresses, and catalog record data for the invoices? I don't type this all in. . . .

**Comment by ebraker** [comment]
We also need some dedicated time to figure out formatting....loans printed with the old coldfusion reporter have a better look over the new, e.g., 
old: [V-233_McCain_MammalogyClass_Fall2021.pdf](https://github.com/ArctosDB/arctos/files/9500594/V-233_McCain_MammalogyClass_Fall2021.pdf) vs.
new: [reporter.pdf](https://github.com/ArctosDB/arctos/files/9500621/reporter.pdf) and https://arctos.database.museum/Reports/reporter.cfm?action=view&report_id=3&&transaction_id=21127839 (the UCM-loan_invoice doesn't generate the pdf for some reason)

**Comment by campmlc** [comment]
Yes, some ability to preview so we can make sure of the spacing would be helpful. Spacing has been really hard to deal with in ColdFusion, and our current reports are not ideal. Not enough room for the loan description and too much white space in other areas, for example.

**Comment by dustymc** [comment]
>dedicated time to figure out formatting.

Yes, and the more of that we can do now the better everything that follows will work out. Patching some good idea back to 500 reports doesn't sound like all that much fun....

>doesn't generate the pdf for some reason

Yes, the option is still there because maybe someone will figure something magical out, but in my experience so far your browser's print to PDF function is about a bajillion times better than CF's built-in thingee (which seems to understand some very limited and probably antique subset of CSS, and maybe HTML).

>some ability to preview

splat-p, pick PDF, open it with whatever you open PDFs with.

>Not enough room for the loan description and too much white space in other areas

If anything, the HTML option should handle that better than "real" reporters - HTML contains the (default) option of just letting things take whatever space they need, most any "reporter" has as default (and sometimes as the only realistic option) a pre-defined area.

**Comment by dustymc** [comment]
The reports server should again be functional.

**Comment by ebraker** [comment]
Indeed! Thank you!

**Comment by ccicero** [comment]
Yes, thanks! We need to schedule a working session (or multiple sessions) where we can focus on building new reports. This seems like really high priority.

**Comment by dustymc** [comment]
Yep. We remain hopeful that we can work with someone to get some report completely happy, then build on that. (There are about a million things we could do, none of them seem all wrong, none of them seem entirely perfect, what we know needs more real-world exposure.) @ebraker via https://github.com/ArctosDB/arctos/issues/5023 is our current intended victim, we're happy to set that up HOWEVER, but would very much like to not build lots of reports that aren't quite right and will need immediate revision, however that happens.

Hopefully that will result in some close-to-usable template that eg @mkoo 's student can fine-tune.

I've been trying to organize that through mostly-dedicated issues that start with REPORTS: - feel free to open one or more!
