### ISSUE TITLE
Code Table Request - New Media label = tombstone

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4988]
@Jegelewicz I just went back through this whole issue again. I had created #2846 proposing a new media label _thumbnail description_ but the issue was closed and "merged" with this one. Above, you and Dusty both said to just take this one over instead of creating a new one, so I have no idea why I made a new issue. This is what I proposed there:

Goal
Describe what you're trying to accomplish.
We need a designated media field that will display below thumbnails on catalog records. See #2813, #1652, #2529.

Context
Describe why this new value is necessary and existing values are not.
Currently, media labels (description, comment, and maybe others) unpredictably display below thumbnails. We need the ability to predictably display critical media data to users on catalog records. By calling this media label “thumbnail description”, it allows flexibility for collections to prioritize what type of data they consider to be most important to display.

Table
Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm
media_label

Value
Proposed new value
~thumbnail description~ tombstone

Definition
Clear, complete, non-collection-type-specific definition of the new value.

Description that will display below thumbnails on catalog records. If this label is not present, the description label value will display. Best practice is to add only one of these and keep it concise.

> IF ~thumbnail description~tombstone THEN
>    use that
> ELSE
>   use description
> 
> and the documentation should reflect that.
> There will also be length and cardinality limitations - 500000 characters isn't going to fit in any current (or probably future) UI, nor will 5000 "thumbnail description" labels no matter the contents. I don't have anything hard and fast to offer, but "add only one of these" and "keep it concise" might be useful things to include in the definition as well.

_Originally posted by @krgomez in https://github.com/ArctosDB/arctos/issues/2813#issuecomment-862533357_

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/2813 - not sure why this needs further fragmented?
