### ISSUE TITLE
Code Table Request - Some part modifiers for turtles

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#4992]
**Goal**
I'd like to migrate our bony turtle 'scutes' from part scute to part carapace . See https://github.com/ArctosDB/arctos/issues/2423#issuecomment-1233157321. At that point I can add the specific skeletal components as part modifiers.

**Context**
Some of the values I need are already in the code table, some are not. These can all be used to refer to specific skeletal components of the turtle carapace, but can also be used as anatomical directions, so I include a more general definition.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_modifier

**Proposed Value**
neural
nuchal
peripheral
pleural

**Proposed Definition**
neural - Situated in the region of or on the same side of the body as the brain and spinal cord. In turtles, the bones of the carapace situated between the pleurals.
nuchal - Of, relating to, or lying in the region of the back of the neck. In turtles, a single bone at the anterior of the carapace.
peripheral - Situated away from the center, as opposed to centrally located. In turtles, the bones situated around the edge of the carapace.
pleural - Of or relating to the pleura or the sides of the thorax. In turtles, the bones of the carapace lying between the neural and the peripheral bones.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Double check to make sure these don't duplicate part names

**Comment by Jegelewicz** [comment]
Add, but we need a turtle person (or @Jegelewicz and @Nicole-Ridgwell-NMMNHS make sure these aren't duplicated in parts.

add modifiers to parts with this stuff in remarks

**Comment by ewommack** [comment]
@atrox10 @mkoo - herpetologists go!

> Add, but we need a turtle person

**Comment by campmlc** [comment]
@jtgiermakowski

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
None of these are currently in the parts table.

**Comment by jtgiermakowski** [comment]
Fantastic! That will help us out too! please add to part modifier table!

**Comment by Jegelewicz** [comment]
modifiers have been added - now we need to do some cleanup? Pretty sure there are lots of "scutes" with these terms in remarks so can we find all of those and add the appropriate modifier? Also need to look for marginal and costal.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I'm working on cleaning up turtle scute data in NMMNH Paleo.

**Comment by dustymc** [comment]
Is this done, and how can I help if not?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
NMMNH turtle scutes are cleaned up. I think it is just up to individual collections to do clean up now? I think this can be closed?
