### ISSUE TITLE
Unlock my account please

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#4993]
I think I incorrectly entered my password too many times... can you please unlock my account?
Is this the preferred path for fixing such situations? It's my first time...

<img width="413" alt="Screen Shot 2022-08-31 at 10 50 56 AM" src="https://user-images.githubusercontent.com/17605945/187759150-ebb22fc6-0144-41c2-b78c-801a2bca068e.png">

**Comment by dustymc** [comment]
reset

**Comment by AJLinn** [comment]
Hooray, I"m in!
