### ISSUE TITLE
Searching Part Attributes

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#4996]
Is there a way to search for a specific value within a part attributes?

I can find where a specimen is by searching "Part Attribute" - "Location" under catalog record. I'm looking for a way to pull information from the location attribute, specifically method and date, in order to track progress on a project (section underlined in green).

![image](https://user-images.githubusercontent.com/93737929/187941301-6d2510ac-fc79-4126-bc0e-a1fb0b8d3ebf.png)

"Part Search" and "Park Remark" are only pulling from parts (underlined in blue), not the attributes as well, correct? Is there a way to expand the search to the rest of the attribute, or add location to this section (circled in yellow) as well?

![image](https://user-images.githubusercontent.com/93737929/187943154-92a9ec1f-0c3b-48e9-a101-870004946baf.png)

Thanks!

**Comment by dustymc** [comment]
<img width="586" alt="Screen Shot 2022-09-01 at 7 49 53 AM" src="https://user-images.githubusercontent.com/5720791/187944631-8376375a-0667-47f3-8cbe-b052ac1f3332.png">

**Comment by wellerjes** [comment]
I'm looking specifically to pull date / determiner / remark / method from within the location:
![image](https://user-images.githubusercontent.com/93737929/187945457-ed4610da-fd21-48db-afbe-4ea41ee71f87.png)

**Comment by wellerjes** [comment]
By a csv if possible?

**Comment by Jegelewicz** [comment]
You can get ALL parts and attributes using the download part tool, but then you'd have to filter the download. Not exactly what you are looking for, but could get you there?

<img width="960" alt="Screenshot 2022-09-01 08 57 36" src="https://user-images.githubusercontent.com/5725767/187946326-29492c10-8f99-440c-9c40-ba1907aa7901.png">

**Comment by Jegelewicz** [comment]
You have to get some search results (all records in some collection with the part location attribute?) to use this.

**Comment by dustymc** [comment]
>specifically to pull date / determiner / remark / method 

Does that mean you need to search by them? I can add them if so, just rather not complicated the form unless there's a reason to do so, and I don't think I'm clear on what you're asking yet.

**Comment by wellerjes** [comment]
Sorry for the confusion!

We've been leaving a note within location attributes (method) that the specimen was part of the backlog and integrated into the collection as part of our processing. "Specimen was integrated into the larger collection" indicates that the specimen is completely done being processed. I want to track how many specimens have been integrated so we can report the grant progress to our staff, the board, etc. but the notes are all attached to the location attribute. Basically, it was our way of documenting [processing history](![image](https://user-images.githubusercontent.com/93737929/187951293-5863966c-b64f-49eb-9ebf-6f8bcfd35f16.png)) before that attribute existed. We can start documenting it under processing history to make it easier to search in the future, but I'm not sure how to find the existing data in remarks without checking each individual catalog record.

**Comment by wellerjes** [comment]
@Jegelewicz The parts table/download does not contain all the information I'm looking for, but is useful on another data cleaning project I'm working on. Thank you for pointing that out!

**Comment by dustymc** [comment]
Thx, going next task for searching gritty details.

There could also be another part-attribute-centric flattened table/download if that's useful.

**Comment by wellerjes** [comment]
Update: I was able to pull the data I needed from the code in "Part Detail" and add it as an attribute under processing history. I still think that being able to search within part attributes is useful, but not as high as priority.

**Comment by campmlc** [comment]
I also agree that searching within part attributes is necessary. One other
much less intuitive means of accessing data from part attributes in a
usable format is to pull up a search of catalog records, then go to Manage,
scroll down to Parts/Table Download, and download that csv. The part
attributes will be accessible in a column, not in JSON.
