### ISSUE TITLE
Reporter down

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#4997]
I tried accessing the "print any report" function last night (https://arctos.database.museum/Reports/report_printer.cfm?transaction_id=21134099) to generate loan paperwork and kept getting timeout errors. I'm on a different computer/internet network today and still receiving the same error:

![image](https://user-images.githubusercontent.com/11336485/187977487-80b4f251-4f4c-4a01-b73a-8783306bda39.png)

Help please! Trying to get this loan out.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/4986
