### ISSUE TITLE
Code Table Request - salivary gland

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#4999]
I'm working on bulkloading Canada Jays that I collected, and we saved salivary glands from them. I searched the Arctos parts code table for 'gland' which appears only in the definition for the following parts:

adrenal
gonad
mammary tissue
testis

I suggest the following changes/additions to the code table for [specimen_part_name](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name):
gland, adrenal
gland, salivary

Proposed definition for salivary gland: "A type of exocrine gland that produces saliva through a system of ducts."

If approved, we would add a value to the code table (gland, salivary) and change an existing value (adrenal --> gland, adrenal).

**Comment by dustymc** [comment]
Would be nice to avoid digging the scary comma-hole deeper. 

Suggest either 

* 'salivary gland' or
* 'gland' plus salivary, adrenal, etc in https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_modifier

**Comment by Jegelewicz** [comment]
I kinda like the idea of gland plus modifier, but either way, I agree with @dustymc and if we change adrenal, it should be adrenal gland

**Comment by ccicero** [comment]
I was going to suggest 'salivary gland' but thought you wouldn't like that. 'Gland' with modifier is fine with me, but how does 'modifier' get added? When I click on a part to edit, I don't see an option for adding modifier. I also don't see it in the data entry screen, and how would it get bulkloaded?

**Comment by Jegelewicz** [comment]
> I don't see an option for adding modifier.

It is a part attribute - manage attributes

**Comment by Jegelewicz** [comment]
> how would it get bulkloaded?

Separately. Either with the part (separate from the rest of the record) using the [part loader](https://arctos.database.museum/tools/BulkloadParts.cfm) or added to the part after it is loaded using the [Part Attribute loader](https://arctos.database.museum/tools/BulkloadSpecimenPartAttribute.cfm).

**Comment by ccicero** [comment]
OK, thanks. I don't really care if it's a modifier (though more of a pain to add data) or its own part name. More searchable if it's a distinct part?

**Comment by dustymc** [comment]
>More searchable if it's a distinct part?

I think maybe the opposite - people who just want glands can find them all, people who want THAT gland can limit - but I'm not at all sure if it works that way, or if anyone might ever be interested in random glands....

>more of a pain

We seem to be moving more and more towards this structure (whatever happens here), so let me know if there's something we might do to smooth things out.

**Comment by campmlc** [comment]
anyone might ever be interested in random glands....
Yes to above. We are issuing a loans of adrenal glands and shrew venom glands, and I'm sure that's going to increase.

**Comment by ewommack** [comment]
We've got salivary glands from jays here at the UWYMV too. I think I put them in with the tongues though. Glands sound good to me. No matter what ours going to have have modifiers to figure out where they are.

**Comment by Jegelewicz** [comment]
I think I am hearing a new proposal.

New part = gland 
Definition = In animals, a gland is a group of cells in an animal's body that synthesizes substances (such as hormones) for release into the bloodstream or into cavities inside the body or its outer surface. <a href="https://en.wikipedia.org/wiki/Gland" class="external">Wikipedia</a>. In [plants](https://en.wikipedia.org/wiki/Plant), a gland is defined functionally as a plant structure which secretes one or more products. This may be located on or near the plant surface and secrete externally, or be internal to the plant and secrete into a canal or reservoir. <a href="https://en.wikipedia.org/wiki/Gland_(botany)" class="external">Wikipedia</a>

New part modifiers = 

adrenal - Relating to the adrenal glands (also known as suprarenal glands) are endocrine glands that produce a variety of hormones including adrenaline and the steroids aldosterone and cortisol. <a href="https://en.wikipedia.org/wiki/Adrenal_gland" class="external">Wikipedia</a>

salivary - Relating to or secreting saliva (commonly referred to as spit) which is an extracellular fluid produced and secreted by glands in the mouth. <a href="https://en.wikipedia.org/wiki/Saliva" class="external">Wikipedia</a>

venom - a type of toxin produced by an animal that is actively delivered through a wound by means of a bite, sting, or similar action. The toxin is delivered through a specially evolved venom apparatus, such as fangs or a stinger. <a href="https://en.wikipedia.org/wiki/Venom" class="external">Wikipedia</a>

Trying to keep the definitions such that these modifiers could be used with other parts - is that necessary?

**Comment by ccicero** [comment]
I like this general concept but would change the modifier definitions slightly:

adrenal - Relating to the endocrine glands (also known as suprarenal glands) that produce a variety of hormones including adrenaline and the steroids aldosterone and cortisol. [Wikipedia](https://en.wikipedia.org/wiki/Adrenal_gland)

salivary - Relating to the glands that produce saliva (commonly referred to as spit), an extracellular fluid secreted in the mouth. [Wikipedia](https://en.wikipedia.org/wiki/Saliva)

venom - Relating to the glands that secrete a type of toxin produced by an animal. The toxin is delivered through a specially evolved venom apparatus, such as fangs or a stinger, by means of a bite, sting, or similar action. [Wikipedia](https://en.wikipedia.org/wiki/Venom)

**Comment by ccicero** [comment]
Slight additional modification for venom:

venom - Relating to the glands that produce a type of toxin produced by an animal. The toxin is delivered through a specially evolved venom apparatus, such as fangs or a stinger, by means of a bite, sting, or similar action. [Wikipedia](https://en.wikipedia.org/wiki/Venom)

**Comment by ccicero** [comment]
@Jegelewicz @dustymc Can we go ahead and add the part of 'gland' with those modifiers and associated definitions (as I've revised them)? I need to upload my Canada Jays this week for a paper revision we're close to submitting, and will be out of town Thursday-Friday so will miss the code table meeting.

**Comment by Jegelewicz** [comment]
I am OK with this - but then we need to fix the things that are currently "adrenal".

**Comment by dustymc** [comment]
Can we relax the definitions? If we're going to have gland+salivary then maybe we'll want (secretion??? Something like that) + salivary as well, and  the defs seem a bit too "gland-centric" for that. 

I don't think that needs to stop anything, but if the idea isnt' crazy and if things can be tuned in that direction then it seems useful.

**Comment by ccicero** [comment]
How about this:

adrenal - Relating to the system that produces hormones including adrenaline and the steroids aldosterone and cortisol. [Wikipedia](https://en.wikipedia.org/wiki/Adrenal_gland)

salivary - Relating to the system that produces saliva (commonly referred to as spit), an extracellular fluid secreted in the mouth. [Wikipedia](https://en.wikipedia.org/wiki/Saliva)

venom - Relating to the system that produces a type of toxin produced by an animal. The toxin is delivered through a specially evolved venom apparatus, such as fangs or a stinger, by means of a bite, sting, or similar action. [Wikipedia](https://en.wikipedia.org/wiki/Venom)

???

**Comment by ccicero** [comment]
@dustymc are you ok with these definitions? 

Can I go ahead and add these, then you can fix up the 'adrenal' data currently in Arctos?

**Comment by dustymc** [comment]
Go!

**Comment by ccicero** [comment]
Done! Does it take a while to show in the code table view?

**Comment by dustymc** [comment]
yep

**Comment by ccicero** [comment]
ok, they're showing now. @dustymc you can close this once you've dealt with the other 'adrenal' values. Thanks!
