### ISSUE TITLE
Code Table Request - UBCBBM

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#5000]
I'm working on bulkloading Canada Jays that I collected, and some parts are deposited in the UBC Beaty Biodiversity Museum. That institution doesn't exist in the code table for[ other_ID_type](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type). 

Request is to add the following to the code table:
UBCBBM: University of British Columbia Beaty Biodiversity Museum

Definition:
Identifier for the Beaty Biodiversity Museum at the University of British Columbia, Vancouver, BC, Canada.

They do have an online database, if we want to add a base URL (everything before the 'B' number), e.g., 
https://databases.beatymuseum.ubc.ca/details.php?Database=avian&AccessionNo=B018032

(note, they call the catalog number an accession number)

**Comment by dustymc** [comment]
Your identifier needs to include something about birds - other departments have different URLs (eg https://databases.beatymuseum.ubc.ca/details.php?Database=mammal&AccessionNo=M000183)

And they need Arctos!

**Comment by ccicero** [comment]
@dustymc @Jegelewicz How about this? I really need to get these uploaded this week (for a paper revision we're almost ready to submit), and I will be out of town Thursday-Friday so will miss the code table meeting on Thursday.

Request is to add the following to the code table:
UBCBBM-B: University of British Columbia Beaty Biodiversity Museum Bird Collection

Definition:
Identifier for the bird collection at the Beaty Biodiversity Museum, University of British Columbia, Vancouver, BC, Canada.

Base URL:
https://databases.beatymuseum.ubc.ca/details.php?Database=avian&AccessionNo=

to translate to
https://databases.beatymuseum.ubc.ca/details.php?Database=avian&AccessionNo=B018032

**Comment by Jegelewicz** [comment]
I say add it!

**Comment by ccicero** [comment]
Done! I had to shorten it because of this error: value too long for type character varying(75)

![image](https://user-images.githubusercontent.com/967275/189716299-713e1565-3ef9-4991-8499-dcaa815c9249.png)

Thanks!
