### ISSUE TITLE
[ geography request ] add Comoros Islands (individual islands) to higher geography

### ISSUE THREAD

**Issue by jtgiermakowski** [ArctosDB/arctos#5001]
Please add the three islands that make up the Union of the Comoros and Mayotte (the overseas dept of France), all part of the Comoro Islands

Maharaba mendij!

**Comment by Jegelewicz** [comment]
@dustymc I have no idea if this is what you need - but tagging you so that you see it.

**Comment by jtgiermakowski** [comment]
> Please add the three islands that make up the Union of the Comoros and Mayotte (the overseas dept of France), all part of the Comoro Islands
> 
> Maharaba mendij!

[Comoros.csv](https://github.com/ArctosDB/arctos/files/9473625/Comoros.csv)

**Comment by jtgiermakowski** [comment]
Also, note that MVZ had already added Grand Comore as higher geography but the spelling is not consistent with Wikipedia and should be deprecated.

**Comment by dustymc** [comment]
FYI I'm not ignoring this, @mkoo is working on getting island spatial data into a form that Arctos can use, I'll check back once I have that.

**Comment by jtgiermakowski** [comment]
Any updates? only because we want to "showcase" the specimens in Arctos as part of the report... what's the timeframe? Thanks!

**Comment by dustymc** [comment]
I just got the data, here are two options, both in the spirit of https://github.com/ArctosDB/arctos/issues/5076

GADM: [temp_geog_comoros.csv.zip](https://github.com/ArctosDB/arctos/files/9660335/temp_geog_comoros.csv.zip)

Or USGS Islands - these are organized by "plate" (continent_ocean is probably the best Arctos match) and I can't find any other than Somalia:Grande Comore in there, so I've scooped up the whole plate - hopefully someone with some familiarity can pick them out, if this is the preferred approach.

[temp_geog_comoros_islands.csv.zip](https://github.com/ArctosDB/arctos/files/9660606/temp_geog_comoros_islands.csv.zip)

**Comment by jtgiermakowski** [comment]
I'd go with GADM, although neither appears to really follow the admin of the Comoros:

The island of Mayotte is an overseas department of France

The rest of the islands (three major plus many others) is the Union of the Comoros (the only Arab world country entirely in the southern hemisphere!). The three major islands are commonly known by their French names: northwesternmost [Grande Comore](https://en.wikipedia.org/wiki/Grande_Comore) (Ngazidja), [Mohéli](https://en.wikipedia.org/wiki/Moh%C3%A9li) (Mwali), and [Anjouan](https://en.wikipedia.org/wiki/Anjouan) (Ndzwani). These names are both in the GADM file and the USGS one...

I'd make sure that both French and Comoro names are associated with the islands...

Thanks!!!

**Comment by dustymc** [comment]
>go with GADM

Done, and the existing cleaned up.

>neither appears to really....

Your input would be most welcome in https://github.com/ArctosDB/arctos/issues/5076. I think we're all agreed that geography should be more than strings (spatial data can DO STUFF), and that following some bigger-than-Arctos Source is a logical path if we want to really communicate with the world, but how exactly we accomplish that is still a bit fuzzy. It seems that the case is often that GADM (or whatever) isn't quite RIGHT, but it also seems that it's seldom entirely wrong, and as above at least that leaves us in the same position as most everyone else (who've probably scooped up GADM as a sort of de-facto starting position, if not outright Standard).

Please close or let me know what needs more attention.
