### ISSUE TITLE
Feature Request - locality flag

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5002]
**Is your feature request related to a problem? Please describe.**

Flag "point out of asserted geography" separately from error/polygon intersections (for primary point-radius only or also derived/primary polygon??)

**Describe what you're trying to accomplish** 

Flag "probably wildly wrong" things separately from more refined/technical/pedantic/whatever it is.

**Describe the solution you'd like**

 Transarctos Unified Reporting Directive 

**Describe alternatives you've considered**

things that reality keeps rejecting

**Additional context**

@Nicole-Ridgwell-NMMNHS did I get this right?

**Priority**

**Comment by dustymc** [comment]
The generated point-radius isn't used for anything, but I just tried this and you are correct, there's some sort of imprecision involved, I think in the query.

I'm running into CPU limitations and I'm not sure how practical this might be, but maybe we could define some sort of "close enough" parameter. The thing I just built using the UI to test works out to have....

```

@arctos>> select st_area(spatial_footprint)/ST_Area(ST_INTERSECTION(locality_footprint,spatial_footprint ))
arctos-> from geog_auth_rec inner join locality on geog_auth_rec.geog_auth_rec_id=locality.geog_auth_rec_id
arctos-> where locality_id=10482969;
      ?column?      
--------------------
 0.9999999999999788
```
.. a whole buncha 9s percentage overlap, which probably makes any human happy enough but it's not 1 so the machines don't like it.

I'm not sure what the magic number might look like, but calling "more than (50, 70, 90, ???)% overlap" `spatially appropriate` doesn't seem TOO awful, considering the circumstances. (We're not a GIS shop, we don't have "real GIS" tools, wouldn't have the time to use them if we did, just trying to do cool things with museum stuff).

Assuming I can make something that work with what I've got, does that do what you want or would the 'center in' check still be necessary?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> percentage overlap

This would be great! That magic number is definitely arbitrary, but I think maybe 70%??? seems about right? 

> Assuming I can make something that work with what I've got, does that do what you want or would the 'center in' check still be necessary?

A center outside the geography still seems like it would need a flag, although I image a locality with center outside the geography that still has greater than 70% overlap with the geography would be rare?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Although, thinking about something that is right on a border, maybe 50%???

**Comment by dustymc** [comment]
50% feels really low to me, but I still can't tell "we are in county within x-distance of point" (in which case 50% is fine and some sort of 'hack off at the borders' tool would be neat) from "we are within x-distance of point and there's a blank for county on the datasheet and I really like filling in blanks so here's a guess" (in which case 50% is cause for concern). In any case it should be pretty easy to adjust, I'll pick something, see if I can support it, check what falls out....

The current check isn't structured to do this very well, I need to rebuild, I think I want to remove all dependencies and just do several independent checks (which will be slightly more expensive but also make growth/change even easier). Here's what I'm thinking - does this sound reasonable?

 1. Report if the geography is not current (has start or end dates)
2. Report if geography does not have a footprint
3. If there is no georeference, report if a suggestion is available (eg could this easily be [automated](https://github.com/ArctosDB/arctos/issues/4916))
4. If there is a georeference and the geography has a footprint, report if less than {threshhold %} of the locality polygon (asserted or derived) overlaps the geography footprint
5. If there is a georeference and the geography has a footprint, report (including separation distance) if there is no spatial intersection
6. If there is a georeference and the geography has a footprint, find the smallest geography (falling back to the cache if necessary) that entirely contains the locality, report if that is not the asserted geography

That essentially separates "does it fit?" and "could it be better?" (which are more or less combined now), which lets me get at things like 'yea, there's great overlap, but there's a continent-level assertion and a county-level georeference.' (There are many thousands of those in Arctos, they're not WRONG by any means, but I think they confuse some users who see "huge thing" and just assume the data need that much wiggle room, which isn't always the case).

**Comment by Jegelewicz** [comment]
> If there is a georeference and the geography has a footprint, report if less than {threshhold %} of the locality polygon (asserted or derived) overlaps the geography footprint

What about reporting the % outside the polygon? Not necessarily as a flag, but as information for users to consider?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> What about reporting the % outside the polygon?

I like this. It lets the user decide what is the important threshold for however they are using the data.

**Comment by dustymc** [comment]
>% outside the polygon

Yes, clearly much better, handles 'hanging off the edge' and 'huge circle around a tiny shape' about equally well, thanks.

It does get weird via with sufficiently large error and small geography, but hopefully that sort of thing is relatively rare.

<img width="864" alt="Screen Shot 2022-09-08 at 12 31 29 PM" src="https://user-images.githubusercontent.com/5720791/189210076-9c507c5b-1f16-4574-bd70-2a0643a84740.png">

Actual values in case anyone is willing to check my math/approach:

```
arctosprod@arctos>> select
arctos-> st_area(locality_footprint),
arctos-> st_area(spatial_footprint),
arctos-> (st_area(locality_footprint)-ST_Area(ST_INTERSECTION(locality_footprint,spatial_footprint)))/st_area(locality_footprint) as percentout
arctos-> from 
arctos-> flat
arctos-> inner join specimen_event on flat.collection_object_id=specimen_event.collection_object_id and specimen_event.verificationstatus!='unaccepted'
arctos-> inner join collecting_event on specimen_event.collecting_event_id=collecting_event.collecting_event_id
arctos-> inner join locality on collecting_event.locality_id=locality.locality_id
arctos-> inner join geog_auth_rec on locality.geog_auth_rec_id=geog_auth_rec.geog_auth_rec_id
arctos-> where
arctos-> round((st_area(locality_footprint)-ST_Area(ST_INTERSECTION(locality_footprint,spatial_footprint)))/st_area(locality_footprint)*100) > 5 and
arctos-> locality.locality_id=11027719;
      st_area      |      st_area       |    percentout     
-------------------+--------------------+-------------------
 679208297963.3164 | 3020024125.2584496 | 0.995553611261499


```


I've gone back and forth a few times, ``locality: georeference does not intersect geography`` is almost department of redundancy department with ``100 percent of locality ... falls outside the specified geography.`` BUT the former includes how far (``The specified geography and the georeference are separated by 12,568 meters; the data cannot be correct.``) and sorting on that allows separation of "just missed, maybe the geography shape isn't perfect" and "halfway around the planet, reject from any and all analyses" - maybe even something finer-scaled - so it's back in there for now.
