### ISSUE TITLE
GEOGRAPHY CLEANUP: quad and county

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5003]
ref: https://github.com/ArctosDB/arctos/issues/4836

Something easy to start our spatial journey, I hope! There are 2897 geography entries with quad and county, but only 573 are used. Those are attached, along with the collection(s) using them.

I think https://github.com/ArctosDB/arctos/issues/4836#issuecomment-1189160370 is a tentative agreement to set up a locality attribute for quad. If that's still acceptable to @Nicole-Ridgwell-NMMNHS  and nobody else has objections or better ideas, I'll create that, figure out a migration path, move these, and delete ~3K intersection-geography records.

(I think there might be some good examples of ignoring the inconvenient when choosing geography in here too - eg @sharpphyl were you wanting to assert 'Port Aransas 7.5 minute Quad' for one record, or just aiming for the island?)

Summary:

```

         users          | count 
------------------------+-------
 DMNS:Inv|NMMNH:Paleo   |     1
 MSB:Para               |     1
 UAM:ES                 |     1
 NMMNH:Paleo            |   547
 UAM:Herb               |     8
 NMMNH:Geol             |    10
 UTEP:Herb              |     1
 NMMNH:Geol|NMMNH:Paleo |     1
 MSB:Herp|NMMNH:Paleo   |     1
 UTEP:Ento              |     2
```

CSV:

[temp_quad_and_county.csv.zip](https://github.com/ArctosDB/arctos/files/9474000/temp_quad_and_county.csv.zip)

Github collection contacts:

 @msbparasites
 @campmlc
 @StefanieBond
 @jtgiermakowski
 @mvzhuang
 @acdoll
 @sharpphyl
 @Jegelewicz
 @Nicole-Ridgwell-NMMNHS
 @genevieve-anderegg

**Comment by sharpphyl** [comment]
> (I think there might be some good examples of ignoring the inconvenient when choosing geography in here too - eg @sharpphyl were you wanting to assert 'Port Aransas 7.5 minute Quad' for one record, or just aiming for the island?)

Definitely chose the wrong locality.  Will relocate that.  Thanks.

**Comment by Jegelewicz** [comment]
I am on board. The only thing it will really change is where to look for quad.

**Comment by dustymc** [comment]
There is a new code table: https://arctos.database.museum/info/ctDocumentation.cfm?table=ctquad

There is a new locality attribute: https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlocality_attribute_type#quad

There is a link: https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlocality_att_att#quad

Here's a migration path:

[temp_quad_m.csv.zip](https://github.com/ArctosDB/arctos/files/9481420/temp_quad_m.csv.zip)


First step, for each row in the table (=each affected locality):

```
update locality set geog_auth_rec_id=NEW_GEOID where locality_id=LOCALITY_ID
```

From the UI end, that'll swap NEW_HIGHERGEO for HIGHER_GEOG. The former should be the latter without the quad.

second step, new locality attribute for each row/locality

attribute_type: quad
attribute_value: NEW_LOCATTQV
attribute_remark: Migrated from geography.

@Nicole-Ridgwell-NMMNHS or anyone else, please have a look at the data, make sure I haven't borked anything, let me know if you want anything different. There is some inconsistency in the data so I had to map a few things manually, I cleaned up a few manually instead of trying to map, etc. - I don't think I mangled anything, but I had the opportunity so more eyes are greatly appreciated.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Looks good, the only thing I noticed was two quads (Five Lakes Canyon and Sheep Mountain Table) have misspellings ("minut" instead of "minute") and it would be good to fix this before migration.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
And I will update our locality upload protocols so I will not be creating any new localities with quad geography.

**Comment by dustymc** [comment]
>"minut" instead of "minute"

Fixed and remapped.

**Comment by dustymc** [comment]
Done, county+quad geography removed.

**Comment by dustymc** [comment]
I'm using this same approach for all remaining quads, which do not fit into The Plan.

I've created FFFs for those with spatial data.

All quads are now also locality attributes and will be disappearing from higher geography over the next few days.
