### ISSUE TITLE
Arctos Down - now!

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#5004]
Please complete to the best of your ability.

## Unplanned Outage: now 930 AM PT
 - Describe the outage: unresponsive, probably needs a kick in the pants @dustymc 

## Communication before/during outage
- [x] Pin this issue
- [ ] Email sent to AWG  
- [ ] Tweet @lin-fred (@mkoo backup) - only if not resolved quickly

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by mkoo** [comment]
returned 503

**Comment by Jegelewicz** [comment]
It took a while, but it's working for me now.

**Comment by Jegelewicz** [comment]
OOPS - spoke too soon!Also 503 for me.

**Comment by Jegelewicz** [comment]
OK, now is working - am I being punked?

**Comment by lin-fred** [comment]
hm working for me

**Comment by dustymc** [comment]
Its busy but I'm not seeing anything that might look like an outage - might be the proxy, I'll check with Chris.

**Comment by jldunnum** [comment]
Has been off and on for me for the past couple hours

______________________________________________________________

Jonathan L. Dunnum Ph.D.
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

Chair, Systematic Collections Committee, American Society of Mammalogists
Latin American Fellowship Committee, ASM

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by mkoo** [comment]
stable enough to close now? @dustymc any update?

**Comment by dustymc** [comment]
I think so - it was some sort of (far) upstream network issue, TACC is blaming some ambiguous combination of fiber-hungry squirrels and drunken engineers.

**Comment by mkoo** [comment]
>  some ambiguous combination of fiber-hungry squirrels and drunken engineers.

So the usual... thanks

**Comment by mkoo** [comment]
ok connected now... 503 errors are so vague anyway.... thanks will close
