### ISSUE TITLE
'body' vs 'body (taxidermy)' on results page

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#5006]
We're looking at our taxidermy specimens and there is an oddity in how they display on the results page. For some records the part is listed as just 'body' and for others it is listed as 'body (taxidermy)'. 
![image](https://user-images.githubusercontent.com/12507297/188234057-74fbaddf-cab6-4d34-95a8-59839eb31be6.png)
Any ideas on why this might be? I don't see anything obviously different in the specimen records. 

(records from the screenshot: https://arctos.database.museum/guid/DMNS:Mamm:1, https://arctos.database.museum/guid/DMNS:Mamm:1002, https://arctos.database.museum/guid/DMNS:Mamm:1027, https://arctos.database.museum/guid/DMNS:Mamm:1028)

BTW: We do like the parenthetical taxidermy, it would be great if they were all like that.

**Comment by dustymc** [comment]
That's from https://github.com/ArctosDB/arctos/issues/4649, I guess the cache still hasn't completely caught up. I can force it (and nothing else will process for ~a week), or I can force bits of it, or you can use the request button. I clicked the button on https://arctos.database.museum/guid/DMNS:Mamm:1, prerefresh .. 
<img width="171" alt="Screen Shot 2022-09-02 at 2 18 10 PM" src="https://user-images.githubusercontent.com/5720791/188236697-aa21c48e-995d-4ac2-ad47-6e3307d5c6ae.png"> and post 
<img width="156" alt="Screen Shot 2022-09-02 at 2 18 16 PM" src="https://user-images.githubusercontent.com/5720791/188236719-ead0899f-99f7-49c9-a0a1-f76118a160f0.png">

**Comment by acdoll** [comment]
No need to force it. Just wanted to you know in case there was something else weird going on. Thanks!
