### ISSUE TITLE
[CONTACT]

### ISSUE THREAD

**Issue by Awkwardtree13** [ArctosDB/arctos#5007]
After coming back from summer break the system isn't letting me log in, and it seems to have forgotten my email, so I can't reset my password. 

I spent about three months not using Arctos due to being on summer break, bringing me past six months since my last password change. Upon trying to log in now I am being told that my account is "inactive or misconfigured." I expected this result, so I tried to reset my password. However, upon entering my account name (Awkwardtree13) and my email that I had used for the account (swhenning@crimson.ua.edu) , it told me "Sorry, that email wasn't found with your username." I've checked numerous times that I entered the username and the email correctly, and I did. Additionally, my sister was in the same situation of having been inactive due to summer break, but has not experienced the same issue of the system forgetting her email. 

How can I get my email associated properly with my account again, so that I can reset my password and get back to work?

**Comment by campmlc** [comment]
@dustymc will need to reset for you, system isn't currently sending emails.

**Comment by dustymc** [comment]
I can't unlock without collection approval @kmkocot @Jegelewicz

**Comment by Jegelewicz** [comment]
I think this is OK, but really @kmkocot should approve. I'll send email.

**Comment by kmkocot** [comment]
I approve. Thank you!

**Comment by Jegelewicz** [comment]
Account unlocked and reset password email sent. Also backup email from me just in case.
