### ISSUE TITLE
error feedback- getting error on trying to download bulkload file with errors

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#5010]
** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **

** Outages should be reported to the contacts listed at https://arctosdb.org/arctos-down/ **

** Arctos Documentation is http://handbook.arctosdb.org/ **

** Learn more about Arctos at https://arctosdb.org/ **

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **
In Bulkloader, loaded csv with 46 records. Got message that 46 records will not successfully load. 
Clicked Download Data with Errors, and got the Something Is Missing! error
![Screenshot 2022-09-05 21 19 31](https://user-images.githubusercontent.com/14808196/188540402-eea99f6d-944d-44fe-836b-deaae0b3c5c6.png)

![Screenshot 2022-09-05 21 19 44](https://user-images.githubusercontent.com/14808196/188540409-24e6fc02-bf06-46a2-abbb-b0b1bacbd4dd.png)

**Comment by campmlc** [comment]
Nevermind - seems Arctos logged me out in the middle of a bulkload? Once I logged back in, I could download the csv. But I shouldn't have been logged out in the middle of a process? I certainly was not inactive.

**Comment by dustymc** [comment]
Assuming I correctly got the ID from the image, that error happened at 2022-09-05 21:19:56. Your browser requested a signout out at 2022-09-05 21:19:18

<img width="1597" alt="Screen Shot 2022-09-06 at 2 28 42 PM" src="https://user-images.githubusercontent.com/5720791/188743631-f99a6092-ccab-410b-be94-6049866b1a81.png">
