### ISSUE TITLE
Solomon Islands - Treasury Islands - Mono Island [ geography request ]

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#5011]
Download and populate the following CSV template to request geography.

(Not seeing a link? Click "preview.")

[geog_template.csv](https://github.com/ArctosDB/arctos/files/9246027/geog_template.csv)

Carefully read the documentation at https://handbook.arctosdb.org/documentation/higher-geography.html before submitting a request.

``spatial_footprint`` may be anything that can be made into ``geography`` data - WKT usually converts easiest. (Or ask for help - we have or can get spatial data for most geography-like places.)

``search_terms`` is a pipe-delimited list of search terms; these are optional but recommended.

``the_issue`` is the URL of the Issue in which the geography is requested (and discussed as necessary). This is required.

**Comment by campmlc** [comment]
[geog_template Mono Island.zip](https://github.com/ArctosDB/arctos/files/9493121/geog_template.Mono.Island.zip)

Requesting help with the spatial footprint? 
Also, as we have a curator who specializes in birds of the Solomon Islands, it would be good to go ahead and add all of the islands while we are at it
<html><body>


Islands of Solomon Islands by province
--
Aeaun Gavutu Mbanika Nggela Islands Pavuvu Russell Islands Savo Tanambogo Tulagi
Choiseul Cyprian Bridge Island Nuatambu Rob Roy Taro Wagina
Guadalcanal Korasahalu Marau Sound Marapa Nughu Tavanipupu Vulelua
Arnarvon Furona Island Kerehikapa Mahige Maleivona Ramos San Jorge Santa Isabel Sikopo
Ali'ite Makira Malaulalo Malaupaina Pio Olu Malau Santa Ana Santa Catalina Ugi Ulawa
Adagege Alite Anuta Paina Faore Funaafou Langa Langa Lagoon Lau Lagoon Laulasi Maana'omba Malaita Maramasike Matuavi Mbasakana Ndai Ontong Java Roncador Reef Sikaiana Sulufou Tehaolei
Bellona Indispensable Reefs Rennell
Anuta Banie Bass Islands Duff Islands Fatutaka Fenualoa Lomlom Makalom Malo Matema Nendö Ngalo Ngandeli Ngatendo Ngawa Nibanga Nendi Nibanga Temau Nifiloli Nukapu Nupani Patteson Shoal Pigeon Pileni Reef Islands Santa Cruz Islands Tahua Taumako Teanu Temotu Noi Tikopia Tinakula Utupua Vanikoro
Akara Arundel Balalae Faisi Fauro Ghizo Ghoi Kennedy Kiambe Kingguru Kolombangara Liapari Logha Lola Lumbari Magusaiai Masamasa Marovo Matikuri Mbava Mborokua Mbulo Mondomondo Mono Nakaza Naru New Georgia New Georgia Islands Nggatokae Nusatupe Olasana Ovau Island Pirumeri Ranongga Rendova Shortland Shortland Islands Simbo Stirling Telina Tetepare Treasury Islands Vella Lavella Uepi Vangunu Vonavona


</body>
</html>Solomon [Islands](https://en.wikipedia.org/wiki/List_of_islands_of_Solomon_Islands) Islands of [Solomon Islands](https://en.wikipedia.org/wiki/Solomon_Islands) by province
[Central](https://en.wikipedia.org/wiki/Central_Province_(Solomon_Islands))	

    [Aeaun](https://en.wikipedia.org/wiki/Aeaun) [Gavutu](https://en.wikipedia.org/wiki/Gavutu) [Mbanika](https://en.wikipedia.org/wiki/Mbanika) [Nggela Islands](https://en.wikipedia.org/wiki/Nggela_Islands) [Pavuvu](https://en.wikipedia.org/wiki/Pavuvu) [Russell Islands](https://en.wikipedia.org/wiki/Russell_Islands) [Savo](https://en.wikipedia.org/wiki/Savo_Island) [Tanambogo](https://en.wikipedia.org/wiki/Tanambogo) [Tulagi](https://en.wikipedia.org/wiki/Tulagi)

[Choiseul](https://en.wikipedia.org/wiki/Choiseul_Province)	

    [Choiseul](https://en.wikipedia.org/wiki/Choiseul_Island) [Cyprian Bridge Island](https://en.wikipedia.org/wiki/Cyprian_Bridge_Island) [Nuatambu](https://en.wikipedia.org/wiki/Nuatambu) [Rob Roy](https://en.wikipedia.org/wiki/Rob_Roy_Island) [Taro](https://en.wikipedia.org/wiki/Taro_Island) [Wagina](https://en.wikipedia.org/wiki/Wagina_Island)

[Guadalcanal](https://en.wikipedia.org/wiki/Guadalcanal_Province)	

    [Guadalcanal](https://en.wikipedia.org/wiki/Guadalcanal) [Korasahalu](https://en.wikipedia.org/wiki/Korasahalu) [Marau Sound](https://en.wikipedia.org/wiki/Marau_Sound) [Marapa](https://en.wikipedia.org/wiki/Marapa) [Nughu](https://en.wikipedia.org/wiki/Nughu) [Tavanipupu](https://en.wikipedia.org/wiki/Tavanipupu) [Vulelua](https://en.wikipedia.org/wiki/Vulelua)

[Isabel](https://en.wikipedia.org/wiki/Isabel_Province)	

    [Arnarvon](https://en.wikipedia.org/wiki/Arnarvon) [Furona Island](https://en.wikipedia.org/wiki/Furona_Island) [Kerehikapa](https://en.wikipedia.org/wiki/Kerehikapa) [Mahige](https://en.wikipedia.org/wiki/Mahige) [Maleivona](https://en.wikipedia.org/wiki/Maleivona) [Ramos](https://en.wikipedia.org/wiki/Ramos_Island) [San Jorge](https://en.wikipedia.org/wiki/San_Jorge_Island) [Santa Isabel](https://en.wikipedia.org/wiki/Santa_Isabel_Island) [Sikopo](https://en.wikipedia.org/wiki/Sikopo)

[Makira-Ulawa](https://en.wikipedia.org/wiki/Makira-Ulawa_Province)	

    [Ali'ite](https://en.wikipedia.org/wiki/Ali%27ite) [Makira](https://en.wikipedia.org/wiki/Makira) [Malaulalo](https://en.wikipedia.org/wiki/Malaulalo) [Malaupaina](https://en.wikipedia.org/wiki/Malaupaina) [Pio](https://en.wikipedia.org/wiki/Pio_Island) [Olu Malau](https://en.wikipedia.org/wiki/Olu_Malau) [Santa Ana](https://en.wikipedia.org/wiki/Owaraha) [Santa Catalina](https://en.wikipedia.org/wiki/Owariki) [Ugi](https://en.wikipedia.org/wiki/Ugi_Island) [Ulawa](https://en.wikipedia.org/wiki/Ulawa_Island)

[Malaita](https://en.wikipedia.org/wiki/Malaita_Province)	

    [Adagege](https://en.wikipedia.org/wiki/Adagege) [Alite](https://en.wikipedia.org/wiki/Alite_Island) [Anuta Paina](https://en.wikipedia.org/wiki/Anuta_Paina) [Faore](https://en.wikipedia.org/wiki/Faore) [Funaafou](https://en.wikipedia.org/wiki/Funaafou) [Langa Langa Lagoon](https://en.wikipedia.org/wiki/Langa_Langa_Lagoon) [Lau Lagoon](https://en.wikipedia.org/wiki/Lau_Lagoon) [Laulasi](https://en.wikipedia.org/wiki/Laulasi_Island) [Maana'omba](https://en.wikipedia.org/wiki/Maana%27omba) [Malaita](https://en.wikipedia.org/wiki/Malaita) [Maramasike](https://en.wikipedia.org/wiki/South_Malaita_Island) [Matuavi](https://en.wikipedia.org/wiki/Matuavi) [Mbasakana](https://en.wikipedia.org/wiki/Mbasakana) [Ndai](https://en.wikipedia.org/wiki/Ndai) [Ontong Java](https://en.wikipedia.org/wiki/Ontong_Java_Atoll) [Roncador Reef](https://en.wikipedia.org/wiki/Roncador_Reef) [Sikaiana](https://en.wikipedia.org/wiki/Sikaiana) [Sulufou](https://en.wikipedia.org/wiki/Sulufou) [Tehaolei](https://en.wikipedia.org/wiki/Tehaolei)

[Rennell and Bellona](https://en.wikipedia.org/wiki/Rennell_and_Bellona_Province)	

    [Bellona](https://en.wikipedia.org/wiki/Bellona_Island) [Indispensable Reefs](https://en.wikipedia.org/wiki/Indispensable_Reefs) [Rennell](https://en.wikipedia.org/wiki/Rennell_Island)

[Temotu](https://en.wikipedia.org/wiki/Temotu_Province)	

    [Anuta](https://en.wikipedia.org/wiki/Anuta) [Banie](https://en.wikipedia.org/wiki/Banie_(island)) [Bass Islands](https://en.wikipedia.org/wiki/Bass_Islands_(Duff_Islands)) [Duff Islands](https://en.wikipedia.org/wiki/Duff_Islands) [Fatutaka](https://en.wikipedia.org/wiki/Fatutaka) [Fenualoa](https://en.wikipedia.org/wiki/Fenualoa) [Lomlom](https://en.wikipedia.org/wiki/Lomlom) [Makalom](https://en.wikipedia.org/wiki/Makalom) [Malo](https://en.wikipedia.org/wiki/Malo_(Solomon_Islands)) [Matema](https://en.wikipedia.org/wiki/Matema_Island) [Nendö](https://en.wikipedia.org/wiki/Nend%C3%B6) [Ngalo](https://en.wikipedia.org/wiki/Ngalo) [Ngandeli](https://en.wikipedia.org/wiki/Ngandeli) [Ngatendo](https://en.wikipedia.org/wiki/Ngatendo) [Ngawa](https://en.wikipedia.org/wiki/Ngawa_Island) [Nibanga Nendi](https://en.wikipedia.org/wiki/Nibanga_Nendi) [Nibanga Temau](https://en.wikipedia.org/wiki/Nibanga_Temau) [Nifiloli](https://en.wikipedia.org/wiki/Nifiloli) [Nukapu](https://en.wikipedia.org/wiki/Nukapu) [Nupani](https://en.wikipedia.org/wiki/Nalongo_and_Nupani) [Patteson Shoal](https://en.wikipedia.org/wiki/Patteson_Shoal) [Pigeon](https://en.wikipedia.org/wiki/Pigeon_Island_(Solomon_Islands)) [Pileni](https://en.wikipedia.org/wiki/Pileni) [Reef Islands](https://en.wikipedia.org/wiki/Reef_Islands) [Santa Cruz Islands](https://en.wikipedia.org/wiki/Santa_Cruz_Islands) [Tahua](https://en.wikipedia.org/wiki/Tahua) [Taumako](https://en.wikipedia.org/wiki/Taumako) [Teanu](https://en.wikipedia.org/wiki/Teanu_(island)) [Temotu Noi](https://en.wikipedia.org/wiki/Temotu_Noi) [Tikopia](https://en.wikipedia.org/wiki/Tikopia) [Tinakula](https://en.wikipedia.org/wiki/Tinakula) [Utupua](https://en.wikipedia.org/wiki/Utupua) [Vanikoro](https://en.wikipedia.org/wiki/Vanikoro)

[Western](https://en.wikipedia.org/wiki/Western_Province_(Solomon_Islands))	

    [Akara](https://en.wikipedia.org/wiki/Akara_Island) [Arundel](https://en.wikipedia.org/wiki/Arundel_Island) [Balalae](https://en.wikipedia.org/wiki/Balalae_Island) [Faisi](https://en.wikipedia.org/wiki/Faisi) [Fauro](https://en.wikipedia.org/wiki/Fauro_Island) [Ghizo](https://en.wikipedia.org/wiki/Ghizo_Island) [Ghoi](https://en.wikipedia.org/wiki/Ghoi) [Kennedy](https://en.wikipedia.org/wiki/Kennedy_Island) [Kiambe](https://en.wikipedia.org/wiki/Kiambe) [Kingguru](https://en.wikipedia.org/wiki/Kingguru) [Kolombangara](https://en.wikipedia.org/wiki/Kolombangara) [Liapari](https://en.wikipedia.org/wiki/Liapari) [Logha](https://en.wikipedia.org/wiki/Logha) [Lola](https://en.wikipedia.org/wiki/Lola_Island) [Lumbari](https://en.wikipedia.org/wiki/Lumbari_Island) [Magusaiai](https://en.wikipedia.org/wiki/Magusaiai) [Masamasa](https://en.wikipedia.org/wiki/Masamasa) [Marovo](https://en.wikipedia.org/wiki/Marovo_Island) [Matikuri](https://en.wikipedia.org/wiki/Matikuri) [Mbava](https://en.wikipedia.org/wiki/Mbava) [Mborokua](https://en.wikipedia.org/wiki/Mborokua) [Mbulo](https://en.wikipedia.org/wiki/Mbulo_Island) [Mondomondo](https://en.wikipedia.org/wiki/Mondomondo) Mono [Nakaza](https://en.wikipedia.org/wiki/Nakaza_Island) [Naru](https://en.wikipedia.org/wiki/Naru_Island_(Solomon_Islands)) [New Georgia](https://en.wikipedia.org/wiki/New_Georgia) [New Georgia Islands](https://en.wikipedia.org/wiki/New_Georgia_Islands) [Nggatokae](https://en.wikipedia.org/wiki/Nggatokae_Island) [Nusatupe](https://en.wikipedia.org/wiki/Nusatupe) [Olasana](https://en.wikipedia.org/wiki/Olasana_Island_(Solomon_Islands)) [Ovau Island](https://en.wikipedia.org/wiki/Ovau_Island) [Pirumeri](https://en.wikipedia.org/wiki/Pirumeri) [Ranongga](https://en.wikipedia.org/wiki/Ranongga) [Rendova](https://en.wikipedia.org/wiki/Rendova_Island) [Shortland](https://en.wikipedia.org/wiki/Shortland_Island) [Shortland Islands](https://en.wikipedia.org/wiki/Shortland_Islands) [Simbo](https://en.wikipedia.org/wiki/Simbo) [Stirling](https://en.wikipedia.org/wiki/Stirling_Island) [Telina](https://en.wikipedia.org/wiki/Telina) [Tetepare](https://en.wikipedia.org/wiki/Tetepare_Island) [Treasury Islands](https://en.wikipedia.org/wiki/Treasury_Islands) [Vella Lavella](https://en.wikipedia.org/wiki/Vella_Lavella) [Uepi](https://en.wikipedia.org/wiki/Uepi) [Vangunu](https://en.wikipedia.org/wiki/Vangunu) [Vonavona](https://en.wikipedia.org/wiki/Vonavona)

**Comment by dustymc** [comment]
The CSV contains only one row, I don't think that's all of the request??

This can't be fully discussed without island spatial data (@mkoo  is working on it), but there are some preliminary things that can be ironed out, and maybe they'll mean we don't need island data for this.

The CSV contains continent=Pacific and then dirt-stuff. Those spatially conflict. Suggest dropping continent, including for existing things. (And I'll eventually make that suggestion for most everything, as we discussed at the [AWG](https://docs.google.com/document/d/1y7rLKJCJrVTxijsVzf730tYcwI53JtwSUjsXa9MsxYs/edit#heading=h.q3pk226foene) meeting - certainly not particular to these data.)

The CSV contains a mix of political and physical. I don't think I'll be able to deal with that, and https://github.com/ArctosDB/arctos/issues/4836 suggests its a path best entirely avoided, but if you really need to mix those then we can discuss. (If necessary, that should be an AWG-level discussion, and you'd almost certainly have to come up with the spatial data.)

Tentatively I suggest not creating geography for the islands at all (and removing those that exist from Arctos) - following GADM is going to be much cleaner and more "portable," and there is a county-equivalent for the Solomons. We can certainly discuss (after I get island data) if there are strong opinions about this, I think at least some islands (Saint Lawrence for example - it's a major feature and not part of any spatial+political thing that I can find) probably need to exist as geography, but I don't at all have that line (if it exists) precisely identified.

I pulled GADM for the political entities of the Solomons and updated what existing data I could. I can easily add state and ward (data below) if the island thing isn't an issue.


```
arctosprod@arctos>> select geog_string from external_gis_data where geog_string like 'Solomon%' and source='gadm2' order by geog_string;
                    geog_string                     
----------------------------------------------------
 Solomon Islands|Central|East Gela
 Solomon Islands|Central|Lovukol
 Solomon Islands|Central|Mbanika
 Solomon Islands|Central|North East Gela
 Solomon Islands|Central|North Savo
 Solomon Islands|Central|North West Gela
 Solomon Islands|Central|Pavuvu
 Solomon Islands|Central|Sandfly-Buenavista
 Solomon Islands|Central|South East Gela
 Solomon Islands|Central|South Savo
 Solomon Islands|Central|South West Gela
 Solomon Islands|Central|Tulagi
 Solomon Islands|Central|West Gela
 Solomon Islands|Choiseul|Babatana
 Solomon Islands|Choiseul|Bangara
 Solomon Islands|Choiseul|Batava
 Solomon Islands|Choiseul|Katupika
 Solomon Islands|Choiseul|Kerepangara
 Solomon Islands|Choiseul|Kirugela
 Solomon Islands|Choiseul|Polo
 Solomon Islands|Choiseul|Senga
 Solomon Islands|Choiseul|Susuka
 Solomon Islands|Choiseul|Tavula
 Solomon Islands|Choiseul|Tepakaza
 Solomon Islands|Choiseul|Vasiduki
 Solomon Islands|Choiseul|Viviru
 Solomon Islands|Choiseul|Waghina
 Solomon Islands|Guadalcanal|Aola
 Solomon Islands|Guadalcanal|Avuavu
 Solomon Islands|Guadalcanal|Birao
 Solomon Islands|Guadalcanal|Duidui
 Solomon Islands|Guadalcanal|East Ghaobata
 Solomon Islands|Guadalcanal|East Tasimboko
 Solomon Islands|Guadalcanal|Kolokarako
 Solomon Islands|Guadalcanal|Longgu
 Solomon Islands|Guadalcanal|Malango
 Solomon Islands|Guadalcanal|Moli
 Solomon Islands|Guadalcanal|Paripao
 Solomon Islands|Guadalcanal|Saghalu
 Solomon Islands|Guadalcanal|Savulei
 Solomon Islands|Guadalcanal|Talise
 Solomon Islands|Guadalcanal|Tandai
 Solomon Islands|Guadalcanal|Tangarare
 Solomon Islands|Guadalcanal|Tetekanji
 Solomon Islands|Guadalcanal|Valasi
 Solomon Islands|Guadalcanal|Vatukulau
 Solomon Islands|Guadalcanal|Vulolo
 Solomon Islands|Guadalcanal|Wanderer Bay
 Solomon Islands|Guadalcanal|West Ghaobata
 Solomon Islands|Honiara|Cruz
 Solomon Islands|Honiara|Kola'a
 Solomon Islands|Honiara|Kukum
 Solomon Islands|Honiara|Mataniko
 Solomon Islands|Honiara|Mbumburu
 Solomon Islands|Honiara|Naha
 Solomon Islands|Honiara|Nggosi
 Solomon Islands|Honiara|Panatina
 Solomon Islands|Honiara|Rove - Lengakiki
 Solomon Islands|Honiara|Vavaea
 Solomon Islands|Honiara|Vuhokesa
 Solomon Islands|Honiara|Vura
 Solomon Islands|Isabel|Buala
 Solomon Islands|Isabel|Havulei
 Solomon Islands|Isabel|Hovukoilo
 Solomon Islands|Isabel|Japuana
 Solomon Islands|Isabel|Kaloka
 Solomon Islands|Isabel|Kia
 Solomon Islands|Isabel|Kmaga
 Solomon Islands|Isabel|Kokota
 Solomon Islands|Isabel|Kolomola
 Solomon Islands|Isabel|Kolotubi
 Solomon Islands|Isabel|Koviloko
 Solomon Islands|Isabel|Samasodu
 Solomon Islands|Isabel|Sigana
 Solomon Islands|Isabel|Susubona
 Solomon Islands|Isabel|Tatamba
 Solomon Islands|Isabel|Tirotonga
 Solomon Islands|Makira Ulawa|Arosi East
 Solomon Islands|Makira Ulawa|Arosi North
 Solomon Islands|Makira Ulawa|Arosi South
 Solomon Islands|Makira Ulawa|Arosi West
 Solomon Islands|Makira Ulawa|Bauro Central
 Solomon Islands|Makira Ulawa|Bauro East
 Solomon Islands|Makira Ulawa|Bauro West
 Solomon Islands|Makira Ulawa|Haununu
 Solomon Islands|Makira Ulawa|North Ulawa
 Solomon Islands|Makira Ulawa|Rawo
 Solomon Islands|Makira Ulawa|Santa Ana
 Solomon Islands|Makira Ulawa|Santa Catalina
 Solomon Islands|Makira Ulawa|South Ulawa
 Solomon Islands|Makira Ulawa|Star Harbour North
 Solomon Islands|Makira Ulawa|Star Harbour South
 Solomon Islands|Makira Ulawa|Ugi and Pio
 Solomon Islands|Makira Ulawa|Wainoni East
 Solomon Islands|Makira Ulawa|Wainoni West
 Solomon Islands|Makira Ulawa|Weather Coast
 Solomon Islands|Makira Ulawa|West Ulawa
 Solomon Islands|Malaita|Aba - Asimeuru
 Solomon Islands|Malaita|Aiaisi
 Solomon Islands|Malaita|Aimela
 Solomon Islands|Malaita|Areare
 Solomon Islands|Malaita|Asimae
 Solomon Islands|Malaita|Auki
 Solomon Islands|Malaita|Buma
 Solomon Islands|Malaita|East Baegu
 Solomon Islands|Malaita|Fauabu
 Solomon Islands|Malaita|Faumamanu - Kwai
 Solomon Islands|Malaita|Foondo - Gwaiau
 Solomon Islands|Malaita|Fouenda
 Solomon Islands|Malaita|Gulalafou
 Solomon Islands|Malaita|Kwaimela - Radefasu
 Solomon Islands|Malaita|Kwarekwareo
 Solomon Islands|Malaita|Langalanga
 Solomon Islands|Malaita|Luaniua
 Solomon Islands|Malaita|Malu'u
 Solomon Islands|Malaita|Mandalua - Folotana
 Solomon Islands|Malaita|Mareho
 Solomon Islands|Malaita|Matakwalao
 Solomon Islands|Malaita|Nafinua
 Solomon Islands|Malaita|Pelau
 Solomon Islands|Malaita|Raroisuu
 Solomon Islands|Malaita|Siesie
 Solomon Islands|Malaita|Sikaiana
 Solomon Islands|Malaita|Sububenu-Burianias
 Solomon Islands|Malaita|Sulufou-Kwarande
 Solomon Islands|Malaita|Tai
 Solomon Islands|Malaita|Takwa
 Solomon Islands|Malaita|Waneagu-Taelanasin
 Solomon Islands|Malaita|Weagu Silana Sina
 Solomon Islands|Malaita|West Baegut-Fatale
 Solomon Islands|Rennell and Bellona|East Ghongau
 Solomon Islands|Rennell and Bellona|East Te Nggano
 Solomon Islands|Rennell and Bellona|Kangava
 Solomon Islands|Rennell and Bellona|Lughu
 Solomon Islands|Rennell and Bellona|Matangi
 Solomon Islands|Rennell and Bellona|Mugihenua
 Solomon Islands|Rennell and Bellona|Sa'Aiho
 Solomon Islands|Rennell and Bellona|Tetau Nangoto
 Solomon Islands|Rennell and Bellona|West Ghongau
 Solomon Islands|Rennell and Bellona|West Te Nggano
 Solomon Islands|Temotu|Duff Islands
 Solomon Islands|Temotu|Fenualoa
 Solomon Islands|Temotu|Graciosa Bay
 Solomon Islands|Temotu|Lipe-Temua
 Solomon Islands|Temotu|Luva Station
 Solomon Islands|Temotu|Manuopo
 Solomon Islands|Temotu|Nanggu-Lord Howe
 Solomon Islands|Temotu|Nea-Noole
 Solomon Islands|Temotu|Nenumpo
 Solomon Islands|Temotu|Neo
 Solomon Islands|Temotu|Nevenema
 Solomon Islands|Temotu|Nipua-Nopoli
 Solomon Islands|Temotu|North East Santa Cruz
 Solomon Islands|Temotu|Polynesian Outer Islands
 Solomon Islands|Temotu|Tikopia
 Solomon Islands|Temotu|Utupua
 Solomon Islands|Temotu|Vanikoro
 Solomon Islands|Western|Bilua
 Solomon Islands|Western|Buini Tusu
 Solomon Islands|Western|Central Ranongga
 Solomon Islands|Western|Dovele
 Solomon Islands|Western|Gizo
 Solomon Islands|Western|Inner Shortlands
 Solomon Islands|Western|Iringgila
 Solomon Islands|Western|Kolombaghea
 Solomon Islands|Western|Kusaghe
 Solomon Islands|Western|Munda
 Solomon Islands|Western|Nggatokae
 Solomon Islands|Western|Nono
 Solomon Islands|Western|Noro
 Solomon Islands|Western|North Kolombangara
 Solomon Islands|Western|North Ranongga
 Solomon Islands|Western|North Rendova
 Solomon Islands|Western|North Vangunu
 Solomon Islands|Western|Nusa Roviana
 Solomon Islands|Western|Outer Shortlands
 Solomon Islands|Western|Roviana Lagoon
 Solomon Islands|Western|Simbo
 Solomon Islands|Western|South Kolombangara
 Solomon Islands|Western|South Ranongga
 Solomon Islands|Western|South Rendova
 Solomon Islands|Western|Vonavona
 Solomon Islands|Western|Vonunu
(183 rows)
```

**Comment by campmlc** [comment]
I'm not seeing Mono Island, the one I need, in your list? It's in Western Province.  Is that the "Nono" island?

I don't have any horses in this race, but there are people who might. 
Here is Wikipedia list:
![Screenshot 2022-09-06 14 38 31](https://user-images.githubusercontent.com/14808196/188734227-2b3b26f8-bf61-4f02-89a0-4182e06c5480.png)

**Comment by campmlc** [comment]
I just need something I can use for a pending bulkload file to process a loan in the near future.

**Comment by dustymc** [comment]
> Is that the "Nono" island

This is GADM, islands are not (generally) political so are not (generally) in GADM. Those are wards. 


>something I can use for a pending bulkload

I recommend [the province](https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10009048) as geography and island in spec locality.
