### ISSUE TITLE
Taxon Name Validator timing out

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#5014]
# Error Text
Lucee [5.3.8.206] - Error (Expression)
request /DataServices/taxonNameValidator.cfm (/usr/local/webroot/DataServices/taxonNameValidator.cfm) has run into a timeout (timeout: 60 seconds) and has been stopped. The thread started 60005ms ago.

# Where it happened
https://arctos.database.museum/DataServices/taxonNameValidator.cfm

# Steps to get there
I uploaded a csv with "taxon_name" 319 values. It processes about 8 before timing out. I was able to run the [Taxon Name Check Tool](https://arctos.database.museum/DataServices/SciNameCheck.cfm) without issue.

# Problem
Taxon name validator is timing out.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/3101
