### ISSUE TITLE
GEOGRAPHY CLEANUP: drainage

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5015]
ref: https://github.com/ArctosDB/arctos/issues/4836

I do not have spatial data for the intersection of drainage and other stuff.

If drainage spatial data is available and if that can be made usable for Arctos then I could create geography appropriate for it and update localities to use it.

Alternatively drainage could be moved to a locality attribute and the localities could be moved to the geography without drainage. This would not lose any current information or functionality, so I'll plan on going this route if there are no objections or better ideas by ~2022-09-12.

Here's CSV of used drainage-having geography:

[temp_drainage.csv.zip](https://github.com/ArctosDB/arctos/files/9500215/temp_drainage.csv.zip)

Collections using drainage-having geography:

```
 guid_prefix | count  
-------------+--------
 ALMNH:Inv   |      1
 BYU:Herp    |     18
 CHAS:EH     |      3
 CHAS:Fish   |      4
 DMNS:Inv    |      4
 MLZ:Fish    |      2
 MSB:Fish    | 110026
 MSB:Mamm    |      2
 MVZ:Mamm    |     18
 UAM:EH      |     16
 UAM:Herb    |     19
 UCM:Fish    |      1
 UCM:Obs     |      1
 UNM:Paleo   |      1
 UTEP:Ento   |      5
 UTEP:Herp   |      1
 UTEP:Mamm   |      1
(17 rows)
```

Contacts:

 @ebraker
 @mkoo
 @AJLinn
 @campmlc
 @mvzhuang
 @cjconroy
 @wellerjes
 @AdrienneRaniszewski
 @acdoll
 @jldunnum
 @byuherpetology
 @genevieve-anderegg
 @StefanieBond
 @sharpphyl
 @claypollock
 @Jegelewicz
 @kmkocot
 @droberts49
 @zmsch

I suspect this also contains more "ignore the inconvenient" - eg MSB:Mamm has one record which uses North America, United States, New Mexico, Valencia County, Rio Grande and ~1568 which use North America, United States, New Mexico, Valencia County. Maybe eg https://github.com/ArctosDB/arctos/issues/4785 would have prevented this, assuming its not intentional?

**Comment by Jegelewicz** [comment]
> drainage could be moved to a locality attribute and the localities could be moved to the geography without drainage. This would not lose any current information or functionality, so I'll plan on going this route if there are no objections or better ideas by ~2022-09-12.

This seems reasonable to me.

**Comment by dustymc** [comment]
Here's a very flat version of the data which should be useful for any future adjustments:

[temp_drainage(1).csv.zip](https://github.com/ArctosDB/arctos/files/9602580/temp_drainage.1.csv.zip)

I'll create a new locality attribute 'drainage' and a new linked code table 'ctdrainage' from the 'drainage' column of these data, add the attribute to each listed locality, update each locality to use geography new_geoid/new_highergeo, then clean up all other drainage-things.

**Comment by barke042** [comment]
I'm working with the Bell Museum fish data and we have ~323 drainages listed (t[here](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctdrainage) are a few duplicates because of spelling, this wasn't a controlled vocabulary). Is the listing of drainages here based on what's in the data or is there a reference? Our data are seemingly much more granular (e.g. we have the St. Croix River, which is within the Mississippi drainage). If the listing is fixed, I guess I will have to add drainage information to the locality or verbatim locality. If not fixed, should I request addition of terms?

**Comment by Jegelewicz** [comment]
@barke042 that list is based on requests from the community. Expanding the list seems like something we should expect.
