### ISSUE TITLE
for some reason, unable to find UCM:Para in vertnet rss feed 

### ISSUE THREAD

**Issue by jhpoelen** [ArctosDB/arctos#5018]
@ebraker similarly, I found records linking UCM:Para to UCM:Mamm (see example http://arctos.database.museum/guid/UCM:Mamm:20797 hasParasite http://arctos.database.museum/guid/UCM:Para:10 below). Please do note however, that the UCM:Para collection is somehow not included on the vertnet rss feed, so GloBI was unable to associated the detailed taxonomic information about the parasite. Did you publish the UCM:Para collection publicly? 

https://en.wiktionary.org/wiki/support	http://arctos.database.museum/guid/UCM:Mamm:20797?seid=2623787	UCM:Mamm:20797	Mamm	95	UCM		Sorex cinereus			Animalia | Chordata | Mammalia | Soricomorpha | Soricidae | Sorex | Sorex cinereus	kingdom | phylum | class | order | family | genus | species			unknown	http://purl.obolibrary.org/obo/RO_0002445	hasParasite	http://arctos.database.museum/guid/UCM:Para:10						http://arctos.database.museum/guid/UCM:Para:10				PreservedSpecimen	2012-09-10T00:00:00Z	37.84595333	-108.0318		San Juan Mountains, Lizardhead Wilderness, along north side of West Dolores River, just east of Navajo Lake ('Navajo Lake Site')		http://arctos.database.museum/guid/UCM:Mamm:20797	http://arctos.database.museum/guid/UCM:Mamm:20797	globalbioticinteractions/vertnet	UCM Mammal Collection (Arctos) - Version 17.70	http://ipt.vertnet.org:8080/ipt/archive.do?r=ucm_mammals	2022-09-03T15:37:41.720Z	f324019ad23212691cdb91d958bf8cf266bb93dd97210f1a153bc070a996c0a0	0.12.4

_Originally posted by @jhpoelen in https://github.com/ArctosDB/arctos/issues/4998#issuecomment-1238868099_

**Comment by jhpoelen** [comment]
Here are the collections mentioning UCM that I can see publicly in the vertnet rss feed - 

```
curl http://ipt.vertnet.org:8080/ipt/rss.do |  grep UCM
```

produced:

```
 <title>UCM Amphibian and Reptile Collection (Arctos) - Version 17.68</title>
        <title>UCM Vertebrate Observations Collection (Arctos) - Version 16.68</title>
        <title>UCM Mammal Collection (Arctos) - Version 17.70</title>
        <title>UCM Bird Eggs/Nests Collection (Arctos) - Version 16.68</title>
        <description>[Vertebrate Zoology in the CU Museum of Natural History is a biodiversity repository of more than 120,000 specimens from five taxa: Fishes, Amphibians and Reptiles (Herpetology), Birds, and Mammals. With the exception of birds, our collections are the largest collections of their kind in Colorado. Specimens from Colorado and the surrounding plains, plateaus, and basins are the strength of our collection. The UCM Egg &amp; Nest Collection contains over 2,250 egg sets and nests. Nearly three-quarters of this collection was assembled by distinguished naturalists Denis Gale and G. Morrison in the mid-to-late nineteenth century. These historic specimens represent much of the avifauna found in Colorado and several Midwestern states, and are accompanied by detailed field notes. An additional 600 egg sets collected in the US and Peru in the late 1970s-1990s are preserved as broken fragments, historically used to examine variation in eggshell gas exchange in montane and lowland habitats.]</description>
        <title>UCM Bird Collection (Arctos) - Version 16.68</title>
        <title>UCM Fish Collection (Arctos) - Version 18.68</title>
        <title>UCM Invertebrate Paleontology - Version 26.41</title>
        <title>UCM Entomology Collection - Version 6.4</title>
```

**Comment by jhpoelen** [comment]
I am assuming that all Arctos collections have ```(Arctos)``` in their titles. For some reason ```UCM Entomology Collection``` does not. Any reason why?

**Comment by Jegelewicz** [comment]
> For some reason UCM Entomology Collection and UCM Invertebrate Paleontology do not. Any reason why?

They are not maintained in Arctos

**Comment by Jegelewicz** [comment]
Also, I am guessing that the UCM:Para collection has not yet been published. @ebraker can confirm.

**Comment by jhpoelen** [comment]
@Jegelewicz thanks for your prompt reply, and for confirming that UCM Entomology Collection and UCM Invertebrate Paleontology  are not managed in Arctos. 

Curious to hear what @ebraker has to say about the UCM:Para .

**Comment by Jegelewicz** [comment]
UCM:Para is a relatively new collection and every new collection requires some coordination with VertNet before it gets published... I'm guessing this just hasn't been done yet.

**Comment by jhpoelen** [comment]
@Jegelewicz very exciting to see how others follow in the footsteps of MSB:Para . Am working hard behind the scenes to make sure that these (again) get indexed in some useful way, inspired by the discussion yesterday.

**Comment by Jegelewicz** [comment]
@ebraker there is a step in the data migration workflow specifically for this - [Publish to Aggregators](https://github.com/ArctosDB/data-migration/issues/new?assignees=&labels=&template=12--publication-to-aggregators.md&title=Acronym+Collection+-+12.+Publish+to+Aggregators). Feel free to open an issue there to track your progress and work with Dave.

**Comment by ebraker** [comment]
Thanks all! Yup, UCM:Para is a new collection that I still need to publish, and will follow the  workflow and reach out to Dave. On my to do list!

**Comment by jhpoelen** [comment]
@dustymc thanks for responding to the issue of the UCM:Para records not getting published via vertnet. 

According to my records, the UCM:Para collection was not yet included in the vertnet feed on 3 September 2023 (see attached screenshot). Is this consistent with your observations? Or, did the UCM:Para collection get added after 3 Sept 2023 ? 

https://www.globalbioticinteractions.org/?accordingTo=http%3A%2F%2Farctos.database.museum%2Fguid%2FUCM%3AMamm%3A20797&interactionType=interactsWith

![Screenshot from 2023-09-13 09-26-07](https://github.com/ArctosDB/arctos/assets/1084872/03cc360b-0c17-4c1c-89a6-48b4ea37dbbb)

**Comment by Jegelewicz** [comment]
@jhpoelen it still has not been published by UCM

**Comment by jhpoelen** [comment]
@Jegelewicz thanks for sharing. So, now I wonder why the issue was closed. Curious to hear more about this.

**Comment by Jegelewicz** [comment]
See https://github.com/ArctosDB/data-migration/issues/1808

**Comment by jhpoelen** [comment]
For some reason the issue url didn't resolve for me.

![image](https://github.com/ArctosDB/arctos/assets/1084872/49209567-4d54-423a-bc59-29b6506582f1)

**Comment by Jegelewicz** [comment]
It is an internal repo for data migration....sorry!

**Comment by Jegelewicz** [comment]
@jhpoelen I sent an email...

**Comment by jhpoelen** [comment]
ps, via https://depot.globalbioticinteractions.org/reviews/globalbioticinteractions/vertnet/, I was able to retrieve a list of UCM:Para references using - 

```bash
curl https://depot.globalbioticinteractions.org/reviews/globalbioticinteractions/vertnet/review.tsv\
 | grep "UCM:Para"\
  > ucm-para.tsv
```

| reviewId | reviewDate | reviewer | namespace | reviewCommentType | reviewComment | archiveURI | referenceUrl | institutionCode | collectionCode | collectionId | catalogNumber | occurrenceId | sourceCitation | dataContext |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| a6bc53a6-f2a1-4d67-bfb7-939a43da1ed9 | 2023-09-11T13:07:15Z | GloBI automated reviewer (elton-0.12.7) | globalbioticinteractions/vertnet | note | found unresolved reference [http://arctos.database.museum/guid/UCM:Para:1] |  |  |  |  |  |  |  |  |  |
| a6bc53a6-f2a1-4d67-bfb7-939a43da1ed9 | 2023-09-11T13:07:15Z | GloBI automated reviewer (elton-0.12.7) | globalbioticinteractions/vertnet | note | found unresolved reference [http://arctos.database.museum/guid/UCM:Para:10] |  |  |  |  |  |  |  |  |  |
| a6bc53a6-f2a1-4d67-bfb7-939a43da1ed9 | 2023-09-11T13:07:15Z | GloBI automated reviewer (elton-0.12.7) | globalbioticinteractions/vertnet | note | found unresolved reference [http://arctos.database.museum/guid/UCM:Para:11] |  |  |  |  |  |  |  |  |  |
| a6bc53a6-f2a1-4d67-bfb7-939a43da1ed9 | 2023-09-11T13:07:15Z | GloBI automated reviewer (elton-0.12.7) | globalbioticinteractions/vertnet | note | found unresolved reference [http://arctos.database.museum/guid/UCM:Para:12] |  |  |  |  |  |  |  |  |  |
| a6bc53a6-f2a1-4d67-bfb7-939a43da1ed9 | 2023-09-11T13:07:15Z | GloBI automated reviewer (elton-0.12.7) | globalbioticinteractions/vertnet | note | found unresolved reference [http://arctos.database.museum/guid/UCM:Para:13] |  |  |  |  |  |  |  |  |  |
| a6bc53a6-f2a1-4d67-bfb7-939a43da1ed9 | 2023-09-11T13:07:15Z | GloBI automated reviewer (elton-0.12.7) | globalbioticinteractions/vertnet | note | found unresolved reference [http://arctos.database.museum/guid/UCM:Para:15] |  |  |  |  |  |  |  |  |  |
| a6bc53a6-f2a1-4d67-bfb7-939a43da1ed9 | 2023-09-11T13:07:15Z | GloBI automated reviewer (elton-0.12.7) | globalbioticinteractions/vertnet | note | found unresolved reference [http://arctos.database.museum/guid/UCM:Para:16] |  |  |  |  |  |  |  |  |  |
| a6bc53a6-f2a1-4d67-bfb7-939a43da1ed9 | 2023-09-11T13:07:15Z | GloBI automated reviewer (elton-0.12.7) | globalbioticinteractions/vertnet | note | found unresolved reference [http://arctos.database.museum/guid/UCM:Para:17] |  |  |  |  |  |  |  |  |  |
| a6bc53a6-f2a1-4d67-bfb7-939a43da1ed9 | 2023-09-11T13:07:15Z | GloBI automated reviewer (elton-0.12.7) | globalbioticinteractions/vertnet | note | found unresolved reference [http://arctos.database.museum/guid/UCM:Para:19] |  |  |  |  |  |  |  |  |  |
| a6bc53a6-f2a1-4d67-bfb7-939a43da1ed9 | 2023-09-11T13:07:15Z | GloBI automated reviewer (elton-0.12.7) | globalbioticinteractions/vertnet | note | found unresolved reference [http://arctos.database.museum/guid/UCM:Para:2] |  |  |  |  |  |  |  |  |  |
| a6bc53a6-f2a1-4d67-bfb7-939a43da1ed9 | 2023-09-11T13:07:15Z | GloBI automated reviewer (elton-0.12.7) | globalbioticinteractions/vertnet | note | found unresolved reference [http://arctos.database.museum/guid/UCM:Para:20] |  |  |  |  |  |  |  |  |  |
| a6bc53a6-f2a1-4d67-bfb7-939a43da1ed9 | 2023-09-11T13:07:15Z | GloBI automated reviewer (elton-0.12.7) | globalbioticinteractions/vertnet | note | found unresolved reference [http://arctos.database.museum/guid/UCM:Para:21] |  |  |  |  |  |  |  |  |  |
| a6bc53a6-f2a1-4d67-bfb7-939a43da1ed9 | 2023-09-11T13:07:15Z | GloBI automated reviewer (elton-0.12.7) | globalbioticinteractions/vertnet | note | found unresolved reference [http://arctos.database.museum/guid/UCM:Para:22] |  |  |  |  |  |  |  |  |  |
| a6bc53a6-f2a1-4d67-bfb7-939a43da1ed9 | 2023-09-11T13:07:15Z | GloBI automated reviewer (elton-0.12.7) | globalbioticinteractions/vertnet | note | found unresolved reference [http://arctos.database.museum/guid/UCM:Para:23] |  |  |  |  |  |  |  |  |  |
| a6bc53a6-f2a1-4d67-bfb7-939a43da1ed9 | 2023-09-11T13:07:15Z | GloBI automated reviewer (elton-0.12.7) | globalbioticinteractions/vertnet | note | found unresolved reference [http://arctos.database.museum/guid/UCM:Para:24] |  |  |  |  |  |  |  |  |  |
| a6bc53a6-f2a1-4d67-bfb7-939a43da1ed9 | 2023-09-11T13:07:15Z | GloBI automated reviewer (elton-0.12.7) | globalbioticinteractions/vertnet | note | found unresolved reference [http://arctos.database.museum/guid/UCM:Para:25] |  |  |  |  |  |  |  |  |  |
| a6bc53a6-f2a1-4d67-bfb7-939a43da1ed9 | 2023-09-11T13:07:15Z | GloBI automated reviewer (elton-0.12.7) | globalbioticinteractions/vertnet | note | found unresolved reference [http://arctos.database.museum/guid/UCM:Para:26] |  |  |  |  |  |  |  |  |  |
| a6bc53a6-f2a1-4d67-bfb7-939a43da1ed9 | 2023-09-11T13:07:15Z | GloBI automated reviewer (elton-0.12.7) | globalbioticinteractions/vertnet | note | found unresolved reference [http://arctos.database.museum/guid/UCM:Para:27] |  |  |  |  |  |  |  |  |  |
| a6bc53a6-f2a1-4d67-bfb7-939a43da1ed9 | 2023-09-11T13:07:15Z | GloBI automated reviewer (elton-0.12.7) | globalbioticinteractions/vertnet | note | found unresolved reference [http://arctos.database.museum/guid/UCM:Para:28] |  |  |  |  |  |  |  |  |  |
| a6bc53a6-f2a1-4d67-bfb7-939a43da1ed9 | 2023-09-11T13:07:15Z | GloBI automated reviewer (elton-0.12.7) | globalbioticinteractions/vertnet | note | found unresolved reference [http://arctos.database.museum/guid/UCM:Para:3] |  |  |  |  |  |  |  |  |  |
| a6bc53a6-f2a1-4d67-bfb7-939a43da1ed9 | 2023-09-11T13:07:15Z | GloBI automated reviewer (elton-0.12.7) | globalbioticinteractions/vertnet | note | found unresolved reference [http://arctos.database.museum/guid/UCM:Para:30] |  |  |  |  |  |  |  |  |  |
| a6bc53a6-f2a1-4d67-bfb7-939a43da1ed9 | 2023-09-11T13:07:15Z | GloBI automated reviewer (elton-0.12.7) | globalbioticinteractions/vertnet | note | found unresolved reference [http://arctos.database.museum/guid/UCM:Para:35] |  |  |  |  |  |  |  |  |  |
| a6bc53a6-f2a1-4d67-bfb7-939a43da1ed9 | 2023-09-11T13:07:15Z | GloBI automated reviewer (elton-0.12.7) | globalbioticinteractions/vertnet | note | found unresolved reference [http://arctos.database.museum/guid/UCM:Para:36] |  |  |  |  |  |  |  |  |  |
| a6bc53a6-f2a1-4d67-bfb7-939a43da1ed9 | 2023-09-11T13:07:15Z | GloBI automated reviewer (elton-0.12.7) | globalbioticinteractions/vertnet | note | found unresolved reference [http://arctos.database.museum/guid/UCM:Para:37] |  |  |  |  |  |  |  |  |  |
| a6bc53a6-f2a1-4d67-bfb7-939a43da1ed9 | 2023-09-11T13:07:15Z | GloBI automated reviewer (elton-0.12.7) | globalbioticinteractions/vertnet | note | found unresolved reference [http://arctos.database.museum/guid/UCM:Para:38] |  |  |  |  |  |  |  |  |  |
| a6bc53a6-f2a1-4d67-bfb7-939a43da1ed9 | 2023-09-11T13:07:15Z | GloBI automated reviewer (elton-0.12.7) | globalbioticinteractions/vertnet | note | found unresolved reference [http://arctos.database.museum/guid/UCM:Para:39] |  |  |  |  |  |  |  |  |  |
| a6bc53a6-f2a1-4d67-bfb7-939a43da1ed9 | 2023-09-11T13:07:15Z | GloBI automated reviewer (elton-0.12.7) | globalbioticinteractions/vertnet | note | found unresolved reference [http://arctos.database.museum/guid/UCM:Para:5] |  |  |  |  |  |  |  |  |  |
| a6bc53a6-f2a1-4d67-bfb7-939a43da1ed9 | 2023-09-11T13:07:15Z | GloBI automated reviewer (elton-0.12.7) | globalbioticinteractions/vertnet | note | found unresolved reference [http://arctos.database.museum/guid/UCM:Para:6] |  |  |  |  |  |  |  |  |  |
| a6bc53a6-f2a1-4d67-bfb7-939a43da1ed9 | 2023-09-11T13:07:15Z | GloBI automated reviewer (elton-0.12.7) | globalbioticinteractions/vertnet | note | found unresolved reference [http://arctos.database.museum/guid/UCM:Para:7] |  |  |  |  |  |  |  |  |  |
| a6bc53a6-f2a1-4d67-bfb7-939a43da1ed9 | 2023-09-11T13:07:15Z | GloBI automated reviewer (elton-0.12.7) | globalbioticinteractions/vertnet | note | found unresolved reference [http://arctos.database.museum/guid/UCM:Para:9] |  |  |  |  |  |  |  |  |  |

**Comment by jhpoelen** [comment]
Just in case you are interested in other Arctos references that GloBI could not resolve for some reason:




Here's a frequency table of the institution code / collection code and their frequency of appearance, as generated using

```bash
curl https://depot.globalbioticinteractions.org/reviews/globalbioticinteractions/vertnet/review.tsv\
 | grep -oE "http://arctos.database.museum/guid/[^\t]+"\
 | grep -oE "[A-Z]+:[A-Z][a-z]+"\
 | sort\
| uniq -c\
 | sort -nr 
```

```
   5792 NMMNH:Mamm
   1006 MSB:Mamm
    982 NMU:Para
    324 UNCG:Para
    202 KNWR:En
    196 UAM:Mamm
    167 UAM:Bird
    150 HWML:Para
    133 UAM:En
    113 NMMNH:Bird
     94 USNPC:Para
     93 DGR:Mamm
     59 MSB:Hos
     41 MSB:Para
     39 CUMV:Mamm
     37 CHAS:Teach
     31 TCDGM:Paleo
     30 UCM:Para
     18 MSB:Herp
     17 MMNH:Bird
     14 UMZM:Para
     14 MVZ:Mamm
     13 MVZ:Img
     10 CHAS:Mamm
     10 BYU:Mamm
      9 CHAS:Herb
      8 UAM:Herb
      8 MSB:Inv
      7 MLZ:Egg
      6 NMU:Mamm
      6 NMMNH:Paleo
      5 UWYMV:Bird
      5 UWBM:Herp
      5 OWU:Fish
      5 MSB:Fish
      5 DMNS:Mamm
      4 UTEP:En
      3 UWZM:Bird
      3 KNWR:Herb
      2 UTEP:Herp
      2 CHAS:Bird
      2 CDSC:Herb
      1 UWBM:Mamm
      1 UTEP:Teach
      1 UTEP:Herb
      1 MVZ:Egg
      1 MVZ:Bird
      1 MSB:Bird
      1 DMNS:Bird
      1 CHAS:Herp
      1 CHAS:En
```

For a full list of unresolved arctos records, please see attached globi-arctos-ref-unresolved-2023-09-13.txt . 
[globi-arctos-ref-unresolved-2023-09-13.txt](https://github.com/ArctosDB/arctos/files/12599086/globi-arctos-ref-unresolved-2023-09-13.txt)

**Comment by jhpoelen** [comment]
note that I am not expecting any action on this, just want to share in case GloBI's resolving techniques need a little TLC.
