### ISSUE TITLE
Code Table Request - New agent relationship: relative of

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5019]
**Goal**
I have two agents that are related as "grand niece" and "grand aunt" and there isn't a way to create that specific relationship.
[Mary W. Frame](https://arctos.database.museum/agents.cfm?agent_id=21339694)
[Stacey Litchfield](https://arctos.database.museum/agents.cfm?agent_id=21331833)

**Context**
I have used "associate of" to relate them, but this seems less than good? However, I don't see the need to add every kind of familial relationship we might possibly encounter.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctagent_relationship

**Proposed Value**
relative of

**Proposed Definition**
Agent is related to another in a familial relationship other than spouse of, sibling of, parent/child or grandparent/grandchild. Please state actual relationship in relationship remark.

**Available for Public View**
Yes

**Priority**
[  Please choose a priority-label to the right.  ]

**Comment by AJLinn** [comment]
I like this idea - documenting relationships between creators in the UAM:EH collections is very important and I've often wished for this more generic relationship term. I support adding this.

**Comment by wellerjes** [comment]
I agree, this would be a useful feature for us.

**Comment by Jegelewicz** [comment]
This will probably work well after #5172

**Comment by ebraker** [comment]
Approved 2023-06-15 code table meeting, added to code table.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Added.
