### ISSUE TITLE
Problems with Media loading

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#5021]
Something is wrong with the media server today. Anyone else having trouble accessing media? 

It doesn't seem to be _all_ media but there are definitely issues with media that was created today:
(e.g., https://arctos.database.museum/guid/UAM:EH:0693-0036, https://arctos.database.museum/guid/UAM:EH:0693-0044, https://arctos.database.museum/guid/UAM:EH:0693-0045) that show the bear "media available" as the thumbnail and then you get a "Status: 500" error when you click on it to view at full size:
<img width="954" alt="Screen Shot 2022-09-07 at 12 51 55 PM" src="https://user-images.githubusercontent.com/17605945/188977041-66f4c5f6-70f7-4eb8-9015-5aa0bcf4a251.png">

Seems like the already-loaded thumbnails show up but the full sized media views are not available.
<img width="473" alt="Screen Shot 2022-09-07 at 1 00 50 PM" src="https://user-images.githubusercontent.com/17605945/188978459-10ad0eec-7829-42e4-a135-cea009235a39.png">

I also had a problem loading PDFs from Projects:
https://arctos.database.museum/project/10003147

<img width="954" alt="Screen Shot 2022-09-07 at 12 59 08 PM" src="https://user-images.githubusercontent.com/17605945/188977985-5b8db8a6-e8f0-40e0-9477-7db2f3f11cee.png">

**Comment by dustymc** [comment]
TACC wiggled the wires, I think this is resolved.
