### ISSUE TITLE
Add Kuwait Governates

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#5022]
Currently there are no subdivisions in the Kuwait higher geography.  These are from Wikipedia.

[Kuwait Governates to add to higher geography 09 Sep 2022.csv]

(https://github.com/ArctosDB/arctos/files/9521871/Kuwait.Governates.to.add.to.higher.geography.09.Sep.2022.csv)

**Comment by dustymc** [comment]
Assuming "[just use GADM](https://github.com/ArctosDB/arctos/issues/5017#issuecomment-1239617721)" isn't actually off the table, let's turn this around and try that. Even this small set isn't entirely unambiguous (I spent some time trying to reconcile Al-Asimah in your terminology, Capital_Governorate in your source, and Al Kuwayt in my data), it still contains the ranks, and the issue isn't valid.

So, the first step of that process would be essentially "tell us what you want" - first-level divisions of Kuwait is clear.

From that, I'll pull whatever data I can scrounge up and build a partially-populated CSV. You will need to grab that and

1. Confirm it's actually what you want
1. Delete anything you don't care about
1. Add the wiki link for anything you do want

and I'll adjust my loader to handle that.

Reasonable/workable/etc?

If so, this should load - just please confirm I didn't mangle anything.


[temp_geog_kuwait.csv](https://github.com/ArctosDB/arctos/files/9528048/temp_geog_kuwait.csv)

**Comment by sharpphyl** [comment]
I should probably have noticed that the above csv doesn't include CONTINENT (Asia).  I've added that to your csv.  Is that correct?
[temp_geog_kuwait (1).csv](https://github.com/ArctosDB/arctos/files/9560989/temp_geog_kuwait.1.csv)

**Comment by dustymc** [comment]
> csv doesn't include CONTINENT

Yes, because as above continent is not in GADM, and filling in the blanks for no good reason leads to https://github.com/ArctosDB/arctos/issues/4836

Note that https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=1005245 exists, so a search for....

<img width="555" alt="Screen Shot 2022-09-13 at 2 58 30 PM" src="https://user-images.githubusercontent.com/5720791/190016825-59ab87c0-8e0b-4080-bf89-1b479596fd9c.png">


will still find things from Kuwait (or anywhere else in Asia).

**Comment by sharpphyl** [comment]
Ok, but this may drive our volunteers a bit nuts not knowing whether to search with or without the continent.  

If you search for Asia, Kuwait in geography - as they have always done - you get no geography records.  Remove "Asia" and they appear.  But a search for Saudi Arabia can be done without or without the continent Asia.

Is this the direction all higher geography is headed?

**Comment by dustymc** [comment]
>Is this the direction all higher geography is headed?

That is the question, and its one for which I've been seeking an answer for a very long time. In 
https://github.com/ArctosDB/arctos/issues/5017#issuecomment-1239617721 @Jegelewicz suggests that doing what others have done, or following the de-facto standards, was at least not outright rejected by ya'll. Doing that would certainly solve my most annoying problems, and would make our data TREMENDOUSLY more predictable, which I suspect would make your volunteers (along with just about everybody else) very happy.

**Comment by Jegelewicz** [comment]
I know this should probably go somewhere else, but I'm putting it here because I just came across it doing other stuff and thought it might be helpful?

https://github.com/gbif/portal-feedback/issues/4232

**Comment by Jegelewicz** [comment]
Also this

[Georeferencing for Research Use (GRU): An integrated geospatial training paradigm for biocollections researchers and data providers](https://riojournal.com/article/32449/)

which I haven't had time to read...

**Comment by dustymc** [comment]
I don't understand what either of those have to do with geography, can you elaborate?

Here's how I see our position.

1. None of this matters for things that aren't georeferenced - they just can't participate in the spatial aspects of any system.
2. There are no point-only data in Arctos. (https://github.com/ArctosDB/arctos/issues/2660, https://github.com/ArctosDB/arctos/issues/4418#issuecomment-1065906730)
3. There's nothing special about any point within any shape in Arctos. (Think of all our shapes as flat probability surfaces.)
4. We've agreed to move towards spatial data, which means geography is (becoming) spatially defined; we know precisely what is and what is not Sandoval County, New Mexico, for example. (That doesn't imply our spatial definition is correct, just that we have - or intend to have - one.)

I think that only leaves 2 open (and entirely independent) questions:

1. What is geography? Is there some set of things that we should create as geography and some that we should not, or some individual determination to be made for every request, or is ANY/EVERYTHING geography, or ?????
2. What do we call stuff? There are some practical considerations in https://github.com/ArctosDB/arctos/issues/4836, but I suppose there are plenty of viable approaches which involve filling in all the blanks. (But I'm not sure any of them are compatible with our resources.)

"Just do whatever GADM-n-friends have done" provides an answer to both of those questions, so has my support.

**Comment by Jegelewicz** [comment]
> There are no point-only data in Arctos.

How is [this](https://arctos.database.museum/guid/ACUNHC:Mamm:10) not point-only? The polygon associated doesn't get sent to GBIF, does it?

![image](https://user-images.githubusercontent.com/5725767/190192739-dfb0c046-e9ba-4f29-9eaf-aa12b471efa0.png)

![image](https://user-images.githubusercontent.com/5725767/190192949-d0777d14-185d-4bc6-9bbf-2859aaebb2f8.png)

**Comment by Jegelewicz** [comment]
[Georeferencing for Research Use (GRU): An integrated geospatial training paradigm for biocollections researchers and data providers](https://riojournal.com/article/32449/) is part of a larger discussion ongoing at the global level about fitness for use. If someone cares very specifically about the Pepperdine campus, a point there with an error the size of the county polygon makes the data there look less usable. IS it really from the campus or was the point just haphazardly dropped there?

**Comment by dustymc** [comment]
I can't explain it better than the linked does - NULL error gets padded out to 1 meter. https://arctos.database.museum/place.cfm?action=detail&locality_id=11528401 and zoom leads to 
<img width="306" alt="Screen Shot 2022-09-14 at 3 36 52 PM" src="https://user-images.githubusercontent.com/5720791/190275097-6bf08730-8d86-40c8-817d-59c14b714460.png">


Yes GBIF gets the polygons.

>IS it really from the campus or was the point just haphazardly dropped there?

I don't think there's anything in the data, structure, or anything that might be considered documentation going back at least to MaNIS that would justify treating any point (say, the centroid) differently than any other (some random choice from the points furthest from the centroid, maybe).

**Comment by Jegelewicz** [comment]
>  NULL error gets padded out to 1 meter.

That statement should go along with the data.
