### ISSUE TITLE
REPORTS: MSB

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5024]
Apologies - by tweaking, I mean that for some collections, we need the option of the invoice displaying either NK or collector number or prep number or field number etc. . . . - sometimes it depends on the loan items. I don't know how much flexibility there is in html. Can we do "if this, then this, if not, then that, etc etc for a list"?) 
Also would be good to have loan item remarks display across the board, as on the Herp invoice. 
Remove subsample on mammal forms or replace with y/n - it certainly isn't working. Null doesn't mean anything - these are all subsamples. 
I guess I thought that we are using SQL to query the database for agent names and roles, addresses, and catalog record data for the invoices? I don't type this all in. . . .

_Originally posted by @campmlc in https://github.com/ArctosDB/arctos/issues/4986#issuecomment-1238623744_

**Comment by campmlc** [comment]
Just checking back in on this - I am going to be needing to print loan forms very soon. Any progress?

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/5245
