### ISSUE TITLE
error feedback

### ISSUE THREAD

**Issue by keg34** [ArctosDB/arctos#5026]
I've got a batch of data in Browse and Edit (bulkloader) that can neither be deleted nor loaded.  Any attempt to do anything with them throws an error that I can't make heads or tails of:

ERROR_ID | 7284F2E7-5A72-48C8-B8715332E8D8A9D2
-- | --
ERROR_TYPE | SQL
ERROR_MESSAGE | ERROR: new row for relation "bulkloader" violates check constraint "ck_dec_lat_noprt"
ERROR_DETAIL |  
ERROR_SQL | update bulkloader set status='DELETE' where collection_object_id>1000

At this point we would like to just delete these and bulkload a fresh file.  Any assistance with a) deleting these and b) figuring out if the problem could have stemmed from the original data upload in the first place will be much appreciated.  Thanks!

**Comment by dustymc** [comment]
See https://handbook.arctosdb.org/documentation/understanding-errors.html for error explanations.

This is leftover from https://github.com/ArctosDB/arctos/issues/2678

I fixed what was throwing that and one similar, let me know how to find them if you want me to nuke something or the new error if you have more problems.

**Comment by keg34** [comment]
Ah - thanks, Dusty.  I see where I went astray.  I didn't realize that errors in the data can prevent deletion of the data too (as well as loading).
