### ISSUE TITLE
Bulkloading Error

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#5027]
# Error Text
<html><body>

ERROR_ID | 3B9C0090-E728-4CF1-9101C06A947FDA49
-- | --
ERROR_TYPE | SQL
ERROR_MESSAGE | ERROR: new row for relation "bulkloader" violates check constraint "ck_coll_event_remarks_noprt"
ERROR_DETAIL |  
ERROR_SQL | insert into bulkloader select * from bulkloader_stage

</div>
</body>
</html>

# Where it happened
Bulkloading catalog records

# Steps to get there
Error is occurring due to a non-printing character in remarks, but I cannot find it. I've used trim and clean in excel, replaced / and &, searched for double spaces. I cannot figure out what it wants.

**Comment by dustymc** [comment]
Data please

**Comment by wellerjes** [comment]
[BulkloaderTemplate_TeachMalacology_Batch2.csv](https://github.com/ArctosDB/arctos/files/9530646/BulkloaderTemplate_TeachMalacology_Batch2.csv)

**Comment by dustymc** [comment]
```
arctosprod@arctos>> select coll_object_remarks from  temp_cache.temp_dlm_uptbl  where checkfreetext(coll_object_remarks) is false;
                       coll_object_remarks                       
-----------------------------------------------------------------
 Handwritten on sticky note on outside of box: "(F) Cerithidae" 
```

That's excess spaces, SQL can find it via

```
arctosprod@arctos>> select coll_object_remarks from  temp_cache.temp_dlm_uptbl  where trim(coll_object_remarks) != coll_object_remarks;
                       coll_object_remarks                       
-----------------------------------------------------------------
 Handwritten on sticky note on outside of box: "(F) Cerithidae" 
(1 row)
```
I'm not sure how to translate to Excelish.

**Comment by wellerjes** [comment]
Where can I run it through SQL to check? Do I need specific software?

**Comment by Jegelewicz** [comment]
@wellerjes you can check in Excel - see https://handbook.arctosdb.org/documentation/understanding-errors.html (But also you can use TRIM instead of CLEAN in the formula to find spaces).

**Comment by wellerjes** [comment]
@Jegelewicz This formula? =IF(LEN(A1)=LEN(CLEAN(A1),”OK”,”CLEAN”)
When I try entering it, it says I've entered too many arguments. Is there a parentheses I'm missing?

**Comment by Jegelewicz** [comment]
=IF(LEN(A1)=LEN(CLEAN(A1)),”OK”,”CLEAN”)

**Comment by dustymc** [comment]
>Where can I run it through SQL
<img width="336" alt="Screen Shot 2022-09-08 at 3 49 57 PM" src="https://user-images.githubusercontent.com/5720791/189239344-2a11d3fe-4b3b-4618-8322-3b2da9182772.png">
<img width="190" alt="Screen Shot 2022-09-08 at 3 50 04 PM" src="https://user-images.githubusercontent.com/5720791/189239355-a771142c-f0a7-40c8-9e30-eb7fd0a3cfd5.png">

**Comment by wellerjes** [comment]
@dustymc it says I'm not authorized to access the CSV to Table form. I was able to find the error without it this time; what do I need to do to get permission if I need it again?

<html><body>


ERROR_ID | 0DDF0753-E116-4908-BC98CFC021BF619A
-- | --
ERROR_TYPE | unauthorized
ERROR_MESSAGE | not authorized
ERROR_DETAIL | You are not authorized to access this form.


</body>
</html>

**Comment by wellerjes** [comment]
Also, I have remarks and attributes that have been in autoload for hours. I can bulkload catalog records okay, but nothing has budged on the other bulkloaders. Is this just me, or is it a system-wide issue?

**Comment by Jegelewicz** [comment]
@wellerjes I just bumped up their priority - I have a ton of stuff and when it gets to the top it really slows stuff down. You can do this too [here](https://arctos.database.museum/info/component_loader_status.cfm).

**Comment by wellerjes** [comment]
Thank you!

**Comment by dustymc** [comment]
Oh, that's right, we opened up access to the download but not upload. We can talk about changing that but there would be some security concerns to somehow address, or whoever does that sort of thing for you can grant more access if they want. Manage/Permissions/FormPermissions will tell them what's necessary (global_admin IIRC).

Component loader docs are https://handbook.arctosdb.org/documentation/componentloader.html

I believe the pre-bulkloader checks nonprinting, and the architecture would allow that if it doesn't.

I'm certainly up for clever ideas, and I'm happy to find problems in data until I can point at a tool.
