### ISSUE TITLE
Expand Media search to include relationships defined by TAGs

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ArctosDB/arctos#503]
```
do it
```

Original issue reported on code.google.com by `dust...@gmail.com` on 16 Nov 2011 at 2:33

**Comment by dustymc** [comment]
#695 does this - merging with wontfix

**Comment by campmlc** [comment]
Can we reopen this and see what is possible? We need to be able to use specimen search and media search to find tagged specimens.
@dustymc @Jegelewicz

**Comment by dustymc** [comment]
The linked duplicate issue is a better place to discuss. https://github.com/ArctosDB/arctos/issues/1608 is a hard blocker.

**Comment by dustymc** [comment]
done via linked issue
