### ISSUE TITLE
Code table cleanup - encumbrance action = mask specimen remarks

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5031]
As part of de-specimening and to be consistent with the UI, can we change [mask specimen remark](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctencumbrance_action#mask_specimen_remarks) to "mask collection object remark"?

**Comment by Jegelewicz** [comment]
Code Tables says do this.

**Comment by Jegelewicz** [comment]
I created the new term, but see https://github.com/ArctosDB/arctos/issues/5032#issuecomment-1412674450

So the "new" term is gone. Not sure how to proceed at this point.

**Comment by Jegelewicz** [comment]
@dustymc can we make this happen? It has been approved and it would be a simple (I think) step to de-specimening. Thanks.

**Comment by dustymc** [comment]
We definitely need to work out the prioritization part of https://github.com/ArctosDB/internal/issues/258. I would put this as lowest possible priority, and we have very many issues which are actively screaming for attention (while frustrating users and mangling data) at the moment.
