### ISSUE TITLE
Can't make loan transaction

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#5034]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

Tried to make a loan, and it fails to create. 10+ minutes of waiting (and clicking & reloading etc) and end up with internal server error.

Tried fresh and got:

Something is missing!
May we suggest:

    Logging in and try again. You may log in from the home page.
    On search pages, make sure you do not have values in fields that you do not mean to be there. Or try filling in fewer fields, the more likely to get a match.
    You may not have sufficient privileges to perform that operation. Consult with your supervisor or Arctos mentor.

This message has been logged as EA701A5F-1D41-40F0-A31EFEDE3AE009E0. Please contact us with any information that might help us to resolve this problem. For best results, include the error as text and a detailed description of how it came to occur in the Issue. 

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.
high! Need to make a loan now!!

**Comment by DerekSikes** [comment]
ah I was kicked out of Arctos oddly... logging in & trying again

**Comment by DerekSikes** [comment]
working now but that was a frustrating experience

**Comment by dustymc** [comment]
Yes, there was a significant slowdown and a brief interruption, it should be cleared up now.
