### ISSUE TITLE
Download Statistics Requests

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#5035]
At the Code Table meeting yesterday, we discussed:

1. Adding more query fields to the Download Statistics page (https://arctos.database.museum/Admin/download.cfm). Currently one can search by individual user and date range. Can we add a field to query Purpose (Educational, Research, Personal)?
![image](https://user-images.githubusercontent.com/11336485/189448289-3b6015ca-5ff4-4d71-adda-1dd40c83d1a9.png)
2. It would be great if we could add an "intended use" free-text field for downloads so that people can add more specifics (doesn't have to be required). MorphoSource has this field (and it is required on their platform), but it is really helpful and impactful to see what people are doing with the data, and can be included in annual reports, grant proposals, etc. Here's some recent examples from my MorphoSource request dashboard:

- ![image](https://user-images.githubusercontent.com/11336485/189449517-ccb31f0d-e6bf-474d-902d-84c06ca85fb9.png)
- ![image](https://user-images.githubusercontent.com/11336485/189449853-4ff0c867-301c-43e7-ad6a-ab5c67d048ee.png)
- ![image](https://user-images.githubusercontent.com/11336485/189449573-b48e3c7a-5251-4835-8fa3-f712127fb8cd.png)
- ![image](https://user-images.githubusercontent.com/11336485/189449592-5ecdbd87-0a65-4d9b-80a4-c68604c417ac.png)
- ![image](https://user-images.githubusercontent.com/11336485/189450029-1acd5007-0611-4e11-9d44-277516e1e25e.png)

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/internal/issues/237
