### ISSUE TITLE
Code Table Request - Egg Case in TEACH

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#5037]
**Goal**
Add "egg case" as a valid part in CHAS:Teach

**Context**
The current valid values are "egg" and "egg shell"; "egg case" is only available for Fish and Inv.

**Table**
[specimen_part_name](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name)

**Collection type**
TEACH

Thanks!

**Comment by Jegelewicz** [comment]
added

**Comment by wellerjes** [comment]
Thank you!

**Comment by sharpphyl** [comment]
We need to modify the Egg case description.  Currently it reads: An egg case or egg capsule, often colloquially called a mermaid's purse, is the casing that surrounds the eggs of oviparous sharks, skates and chimaeras.

None of our "egg case" specimens fit this description.  All of them are some type of molluscan egg case.  It's necessary to look at several Wikipedia entries to get all types of egg cases.

for egg cases created by cephalopods:  https://en.wikipedia.org/wiki/Cephalopod#Reproduction_and_life_cycle or https://en.wikipedia.org/wiki/Argonaut_(animal)#Eggcase

for egg cases created by gastropods such as whelks and conchs the best Wikipedia page I can find: https://en.wikipedia.org/wiki/Knobbed_whelk

Just FYI, here's a description of an egg case in our collection: https://www.shellmuseum.org/post/2018/06/01/the-lighning-whelk-part-2

Recommended revision:  An egg case or egg capsule is the protective casing that surrounds the eggs of oviparous sharks, skates, chimaeras, and some gastropods and cephalopods.

**Comment by Jegelewicz** [comment]
Update complete
