### ISSUE TITLE
Need Help with Arctos Error

### ISSUE THREAD

**Issue by erikajprice** [ArctosDB/arctos#5038]
First error type is "OTHER_ID_NUM_TYPE_3 [ 10 ] is invalid," which pops up for 45 out of 1,016 records - I don't have the column "OTHER_ID_NUM_TYPE_3" in the CSV file I'm trying to bulkload, and it doesn't show up as a column header when I download the data with errors.
[Final error report 11 Sep 2022.xlsx](https://github.com/ArctosDB/arctos/files/9543495/Final.error.report.11.Sep.2022.xlsx)

Second error type is "query string argument of EXECUTE is null," which pops up for 9 records.

**Comment by dustymc** [comment]
I need the CSV that causes the errors.

**Comment by Jegelewicz** [comment]
Looks like it is your trap numbers causing a problem.

**Comment by dustymc** [comment]
Did you recreate the error with that CSV? I'm not seeing anything like that in the logs.

**Comment by Jegelewicz** [comment]
> Did you recreate the error with that CSV?

Nope - just looked at the excel file above and that's what I see in it.

**Comment by erikajprice** [comment]
Ah, thank you so much! I'll change the column headers for the trap numbers.

**Comment by erikajprice** [comment]
And I'll try bulkloading the CSV again today, if possible, and see what errors pop up.

**Comment by erikajprice** [comment]
That did it! Thank you!

**Comment by erikajprice** [comment]
@jebrad
