### ISSUE TITLE
fa_cett

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5039]
https://arctos.database.museum/agents.cfm?agent_id=21247823 (Robert Faucett)
https://arctos.database.museum/agents.cfm?agent_id=21345912 (Robert Fawcett)
https://arctos.database.museum/agents.cfm?agent_id=21278710 (Susan Faucett)
https://arctos.database.museum/agents.cfm?agent_id=21278624 (Susan Fawcett)

Half of those have been around a while, half of them were just created, duplicates?

@jebrad

**Comment by jebrad** [comment]
Whoops, Robert Fawcett is a bad duplicate of Robert Faucett.  Looks like Erika created that one this past Sunday, she must have run into the wrong spelling in a catalog.
Both Susans were created long ago, not familiar to me at all.
