### ISSUE TITLE
Can't download data from bulkloader

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5040]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Cannot download from Bulk Browse and Edit

**To Reproduce**
1. Go to https://arctos.database.museum/Bulkloader/browseBulk.cfm
2. Filter for Collection = UWBM:Mamm and catalog number = 81967,80786,80787,80789,80788,42010,39431,48980,39793,41991
3. Select Download

<html><body>

ERROR_ID | 58B8653B-EBF7-456A-A3597C99EEFC071C
-- | --
ERROR_TYPE | application
ERROR_MESSAGE | Parent directory for [/usr/local/webroot/download/BulkPendingData_6KJ1b29/bd.csv] doesn't exist
ERROR_DETAIL |  

</div>
</body>
</html>

**Expected behavior**

**Screenshots**

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by bryansmclean** [comment]
We are getting this same error while attempting to review bulkloader records. Any updates on causes?

**Comment by dustymc** [comment]
The cause is related to a change in encryption. You can log out and back in and you'll **probably** get a key that works, or just let me know what you need and I'll get it to you.

**Comment by bryansmclean** [comment]
I logged out and back in, and all good. Thanks @dustymc
