### ISSUE TITLE
Record not loading

### ISSUE THREAD

**Issue by krgomez** [ArctosDB/arctos#5041]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I have one record that will not load: https://arctos.database.museum/guid/UAM:Art:UA2018-001-026 All other records seem to be loading correctly, but for some reason this one will not open and I get the 500 Internal Server Error.

**To Reproduce**
1. I searched for the UAM:Art accession UA2018-001
2. I tried to open the catalog record for UA2018-001-026
3. I get this error: 500 Internal Server Error

**Desktop (please complete the following information):**
 - OS: Mac Big Sur 11.6
 - Browser: Firefox
 - Version: 95.0.2

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.
Normal

**Comment by dustymc** [comment]
This seems to be spatial stuff timing out, I've got a request for help in to TACC, I will figure something out ASAP.

**Comment by dustymc** [comment]
Fix confirmed.

<img width="736" alt="Screen Shot 2022-09-13 at 5 29 05 PM" src="https://user-images.githubusercontent.com/5720791/190032546-43cea0bb-4177-4c11-ad71-6cfb94cc7b7c.png">
