### ISSUE TITLE
Code Table Request - Montezuma Valley Member

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#5043]
**Goal**
Add Montezuma Valley Member to the lithostratigraphic member code table.

**Context**
I need this value for a locality.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlithostratigraphic_member

**Proposed Value**
Montezuma Valley Member

**Proposed Definition**
A predominantly shale unit of the Cretaceous Mancos Shale. Outcrops in New Mexico and Colorado. [New Mexico Geological Society](https://doi.org/10.56577/FFC-48.163)

I will add this tomorrow if there are no objections.

**Comment by Jegelewicz** [comment]
none here

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Added
