### ISSUE TITLE
Code Table Request - part modifier mammary

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5047]
**Goal**

Part cleanup - normalize glands

**Context**

Bring existing parts into alignment with https://github.com/ArctosDB/arctos/issues/4999

**Table**

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_modifier

**Proposed Value**

mammary

**Proposed Definition**

Relating to the milk-secreting organs of mammals.

**Collection type**

Mamm

**Comment by Jegelewicz** [comment]
Sounds good to me

**Comment by Jegelewicz** [comment]
change parts from mammary tissue to tissue with mammary modifier

**Comment by Jegelewicz** [comment]
term added to code table

**Comment by Jegelewicz** [comment]
@dustymc can you convert all [mammary tissue](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#mammary_tissue) parts to [tissue](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#tissue) with attribute mammary?

**Comment by dustymc** [comment]
That's https://github.com/ArctosDB/arctos/issues/5048
