### ISSUE TITLE
Part Cleanup: Glands

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5048]
Parts ``adrenal`` and ``mammary tissue`` need brought into alignment with https://github.com/ArctosDB/arctos/issues/4999. I'll move to https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#gland with modifiers https://github.com/ArctosDB/arctos/issues/5047 and https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_modifier#adrenal if there are no objections before ~2022-09-27

Data:

[temp_part_gland.csv.zip](https://github.com/ArctosDB/arctos/files/9558651/temp_part_gland.csv.zip)

Summary: 

```

 guid_prefix | nrecs 
-------------+-------
 MSB:Mamm    |     9
 NMU:Mamm    |    49
 UAM:Mamm    |     9

```

Contacts:

 @campmlc
 @amgunderson
 @keg34
 @AdrienneRaniszewski
 @jldunnum

/remind me to complete this in two weeks

**Comment by Jegelewicz** [comment]
> mammary tissue

IS that gland or is it something else? The definition doesn't help. Probably the collections using it need to weigh in.
