### ISSUE TITLE
Part Cleanup: Tendon

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5050]
'tendon, ossified' seems to have avoided previous cleanup. Neither the part nor the modifier? preservation? other??? exist, I'm hoping someone will show up and help with a path, but I'll do something if that doesn't happen before  ~2022-09-27

Data:

[temp_part_tendon.csv.zip](https://github.com/ArctosDB/arctos/files/9558838/temp_part_tendon.csv.zip)

Summary:

```

 guid_prefix | nrecs 
-------------+-------
 NMMNH:Paleo |    11
 UAM:ES      |   369

```

Contacts:

 @Nicole-Ridgwell-NMMNHS

/remind me to complete this in two weeks

**Comment by Jegelewicz** [comment]
@Nicole-Ridgwell-NMMNHS @aklompma thoughts on the best way to handle this?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I think we could change this to part = tendon, part modifier = ossified

**Comment by dustymc** [comment]
Bla there is no part modifier = ossified! 

@Nicole-Ridgwell-NMMNHS could I talk you into making that happen?

**Comment by Jegelewicz** [comment]
I just added it.
