### ISSUE TITLE
Potential Part Cleanup: Urine

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5051]
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#urinary_bladder and https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#urine exist. I tentatively suggest they should be handled more like https://github.com/ArctosDB/arctos/issues/5048 but ??? (And maybe whatever happens here can influence the many blood-involved things??)

Users:

```

 guid_prefix |    part_name    | nrecs 
-------------+-----------------+-------
 ASNHC:Mamm  | urine           |     1
 MSB:Mamm    | urinary bladder |    26
 MSB:Mamm    | urine           |   101

```

Contacts:

 @campmlc
 @AdrienneRaniszewski
 @jldunnum
 @SerinaBrady

Help!

**Comment by Jegelewicz** [comment]
I don't see the problem with urine as a part - we have feces

urinary bladder - we could go with part name = bladder and modifier = urine? but that feels weird? other than air bladders, what else would bladder get used for?

**Comment by Jegelewicz** [comment]
Code Table Committee says we don't need to do anything here.
