### ISSUE TITLE
Code Table Request - new part electric organ

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5052]
**Goal**
Catalog CSULB fish data

**Context**
they have an electric organ

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name

**Proposed Value**
electric organ

**Proposed Definition**
The electric organ is an organ that an electric fish uses to create an electric field. Electric organs are derived from modified muscle or in some cases nerve tissue, and have evolved at least six times among the elasmobranchs and teleosts. <a href="https://en.wikipedia.org/wiki/Electric_organ_(fish)" class="external">Wikipedia</a>

**Collection type**
Fish, Teach

**Priority**
[  Please choose a priority-label to the right.  ]

**Comment by Jegelewicz** [comment]
Code table committee says add.

**Comment by Jegelewicz** [comment]
done

**Comment by AJLinn** [comment]
LOL, as the manager of an ethnology & history collection I thought this new part was for one of these! https://en.m.wikipedia.org/wiki/Electric_organ

**Comment by Jegelewicz** [comment]
@AJLinn in your world, that would be identification!
