### ISSUE TITLE
Agent Merge Request - Allen Ross --> E. Ross Allen

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5053]
Use this template when you discover two agents that you believe represent the same person or organization.

**Agent that should remain after the merge**
[E. Ross Allen](https://arctos.database.museum/agents.cfm?agent_id=10000279)

**Agent that will no longer remain after the merge**
[Allen Ross](https://arctos.database.museum/agents.cfm?agent_id=21298094)

**Reason for merge**
@wellerjes They have the same address and both collected herps. E. Allen Ross had a Reptile Institute in Ocala FL. I believe that they are the same person and that CHAS just has the names transposed.

Please add this issue to the Agents Project

@ArctosDB/agents-committee

**Comment by droberts49** [comment]
Agreed and merged
