### ISSUE TITLE
agents - make create better

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5057]
check agent remarks for http, born, died, student...

complain when found

**Comment by dustymc** [comment]
on agent create form

add dedicated fields for orcid, wikidata, url, correspondence address, etc

on edit - change placeholder to 'data {type?} goes here' (somehow suggest "orcid goes here", current is confusing)

**Comment by Jegelewicz** [comment]
dead, alive, died, born, https, ORCID, associate, student, employee, work

Also, maybe change the form for the "address" area to something like "addresses, phone numbers, urls, and other identifiers".

**Comment by Jegelewicz** [comment]
remark blurb - put this next to the remark field

You can enter anything you want here, but if there is information that fits into status, relationship, contact info, or identifier fields, please enter it there also!

**Comment by Jegelewicz** [comment]
@dustymc I can work on the text stuff in this issue. Already changed the agent edit "address" section legend to "Contact Information and Identifiers". Suggest the same for the create Agent form.

**Comment by dustymc** [comment]
https://arctos-test.tacc.utexas.edu/includes/forms/createagent.cfm?agent_type=undefined&caller=&agentIdFld=&agentNameFld=&agentNameVal=

**Comment by Jegelewicz** [comment]
Got the create form too. Text changes complete. Still open

- [ ] Check agent remarks for  
> dead, alive, died, born, http, ORCID, associate, student, employee, work

- [ ] on agent create form add dedicated fields for orcid, wikidata, url, correspondence address, etc

**Comment by Jegelewicz** [comment]
@dustymc  says close
