### ISSUE TITLE
code table cleanup - tissue quality

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5058]
CSULB Fish has a numeric condition assigned to most of their fish records.

5 - All body parts present, fins not broken, skin and scales on fish intact
4 - One body part broken, some fin breakage, small skin spots discolored or fallen off
3 - Substantial cuts or breaks on body, much of skin fallen off, or fins frayed to near nonexistence
2 - Large portion of body broken or missing, all of skin fallen off, but still identifiable; or dessicated
1 - Damage to specimen prevents identification, severely degraded over entire body

Obviously the "identifiable" part here is vague, as it depends on the taxon.

_Originally posted by @SuellenJacob in https://github.com/ArctosDB/data-migration/issues/1394#issuecomment-1247240469_

I can just put the numbers in condition, but I think it might be better to handle this in the same way we handle [tissue quality](https://arctos.database.museum/info/ctDocumentation.cfm?table=cttissue_quality). Thoughts? Ideas? Help!

**Comment by Jegelewicz** [comment]
@SuellenJacob could we make these a bit more generic so that they could be applied to any biological specimen?

5 - All body parts present, nothing broken, integument intact
4 - One body part broken, some appendicular breakage, small discolored spots on integument, missing small patches of integument
3 - Substantial cuts or breaks on body, much of integument disassociated, appendages frayed to near nonexistence or missing
2 - Large portion of body broken or missing, all integument disassociated, but still identifiable; if in fluid storage, dessicated
1 - Damage to specimen prevents identification, severely degraded over entire body

**Comment by SuellenJacob** [comment]
Yes, we could make it generally applicable to vertebrates at least, maybe like this?

5 - All body parts present, nothing broken, integument intact
4 - One body part broken, some appendicular breakage, integument with minor discoloration or damage
3 - Substantial cuts or breaks on body, appendages severely frayed or missing, much of integument damaged
2 - Large portions of body broken or missing, most integument damaged, but still identifiable; if in fluid storage, desiccated
1 - Severely degraded over entire body, damage to specimen prevents identification

**Comment by Jegelewicz** [comment]
Ideas:

1. Merge with tissue condition

2. Put number in condition report and the definition in remark

@SuellenJacob how do you guys USE this?

**Comment by SuellenJacob** [comment]
There was no fish catalog when I took this job at CSULB, and someone complained that many specimens were of poor quality. So when we cataloged the collection we took note of each lot's condition. I think it ended up in a report I generated upon completion of the project. I think it's nice to have in there, but I admit we haven't actively used it since then.

**Comment by dustymc** [comment]
We have ~7ish ways of specifying "condition," if there's no compelling use case I suggest spelling it out (eg, "3 - Substantial cuts or breaks on body, appendages severely frayed or missing, much of integument damaged") in [condition report](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecpart_attribute_type#condition_report); whatever slight theoretical utility might be lost is more than made up for by fewer (apparently arbitrary) ways of saying (about?) the same thing.

Suggest the same fate for [tissue quality](https://arctos.database.museum/info/ctDocumentation.cfm?table=cttissue_quality), which has been used less than 500 times (and it looks like mostly via migration, not a collection choosing a specific approach).

```
select
    collection.guid_prefix,
    count(*)
from
    specimen_part_attribute
    inner join specimen_part on specimen_part_attribute.collection_object_id=specimen_part.collection_object_id
    inner join cataloged_item on specimen_part.derived_from_cat_item=cataloged_item.collection_object_id
    inner join collection on cataloged_item.collection_id=collection.collection_id
where
    attribute_type = 'tissue quality'
    group by collection.guid_prefix;

-------------+-------
 DMNS:Mamm   |     6
 MSB:Mamm    |     1
 CRCM:Bird   |   431
(3 rows)

```

**Comment by Jegelewicz** [comment]
@SuellenJacob I think for your fish we can put the number plus the definitions you originally gave me in condition which will end up in the condition report attribute when we finish up https://github.com/ArctosDB/arctos/issues/4707#issuecomment-1232229535 

The tissue rating convo can continue in this issue.
![image](https://user-images.githubusercontent.com/5725767/190519716-ab1428d0-f0d9-4f91-ba85-89a64bf71aed.png)

**Comment by SuellenJacob** [comment]
Having the entire number + condition description written out in a generic condition field is acceptable to me.

**Comment by dustymc** [comment]
I will move existing 'tissue quality' values to condition report if nobody objects by ~2022-09-26.

Data:

[temp_tissue_quality.csv.zip](https://github.com/ArctosDB/arctos/files/9602290/temp_tissue_quality.csv.zip)


Summary:

```
 guid_prefix | count 
-------------+-------
 CRCM:Bird   |   431
 DMNS:Mamm   |     6
 MSB:Mamm    |     1
```

Contact:


 @campmlc
 @AdrienneRaniszewski
 @acdoll
 @jldunnum
 @jrdemboski
 @jessicatir

/remind me to check back in a week

**Comment by dustymc** [comment]
Loaded this to attribute loader:

[temp_tissue_quality_to_cr(2).csv.zip](https://github.com/ArctosDB/arctos/files/9669354/temp_tissue_quality_to_cr.2.csv.zip)

but I don't have enough access - @Jegelewicz can you give me some rights or load the crcm stuff plz? This can be closed when that's done.

and 

```
delete from specimen_part_attribute where attribute_type = 'tissue quality';
```

Former table:

[cttissue_quality.csv.zip](https://github.com/ArctosDB/arctos/files/9669360/cttissue_quality.csv.zip)

**Comment by Jegelewicz** [comment]
CRCM:Bird access granted
