### ISSUE TITLE
Character limit on verbatim locality

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#5060]
I'm trying to add some events using the specimen event bulkloader, but getting an error on verbatim locality because this field is apparently limited to 255 characters. I've already edited out things out like higher geography and it is still too long. This field is supposed to be "whatever the collector wrote, warts and all", and I can't do that if I have to edit it down to meet a character limit.

**Comment by dustymc** [comment]
That's just an artifact in the loader - should be happy now, and I left myself a note to rebuild everything else whenever that loader goes under the knife again.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks!
