### ISSUE TITLE
Move agent identifiers from addresses to their own thing

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5061]
> on agent create form
> 
> add dedicated fields for orcid, wikidata, url, correspondence address, etc
> 
> on edit - change placeholder to 'data {type?} goes here' (somehow suggest "orcid goes here", current is confusing)

_Originally posted by @dustymc in https://github.com/ArctosDB/arctos/issues/5057#issuecomment-1247268571_

In the Agent meeting where this was discussed, I think everyone agreed that these are different things than addresses, even if the link they create is an address.

I know I have suggested this before, but maybe the time is better now, but these should function in the same way other identifiers for collection objects do. The four currently in use all have base urls:

Agent Identifier | base url | sample identifier | link
 -- | -- | -- | -- 
GitHub username | https://github.com/ | Jegelewicz | https://github.com/Jegelewicz 
Wikidata | https://www.wikidata.org/wiki/ | Q63834511 | https://www.wikidata.org/wiki/Q63834511  
ORCiD | https://orcid.org/ | 0000-0002-1970-7044 | https://orcid.org/0000-0002-1970-7044 
Library of Congress | https://lccn.loc.gov/ | no2018099044 | https://lccn.loc.gov/no2018099044 

Also note that all of these (other than Wikidata) are used in exactly this way by Wikidata

![image](https://user-images.githubusercontent.com/5725767/190475922-7881d28b-5976-4213-b676-cb3e64b9b9c7.png)

It has become clear that putting this in the same category as address is not clear to those creating agents, and I think they would be much clearer and potentially more useful if they were "agent identifiers".

**Comment by ewommack** [comment]
Dusty has changed the name of the section to Contact Information and Identifiers for Arctos Working Group.

Still using the whole URL address, though. Closing for now.
