### ISSUE TITLE
Need Help with Arctos Error

### ISSUE THREAD

**Issue by droberts49** [ArctosDB/arctos#5064]
# Error Text
<html>
<body>

ERROR_ID | 4A6E11CE-AF41-4CA5-A10569637F23344D
ERROR_TYPE | template
ERROR_MESSAGE | missing terminating [#] for expression
ERROR_DETAIL

<br class="Apple-interchange-newline">
</body>
</html>

# Where it happened
agents search page

# Steps to get there
Trying to get into any of the agents to edit and update, they all are giving this error
![image](https://user-images.githubusercontent.com/16580148/190679130-28ef0477-b590-489a-bc0c-9785f829b5be.png)

**Comment by dustymc** [comment]
@Jegelewicz I think this must be https://github.com/ArctosDB/arctos/issues/5057, I haven't been there?

**Comment by dustymc** [comment]
Patched, hopefully....

**Comment by droberts49** [comment]
Yay! It works! Thank you @dustymc

**Comment by Jegelewicz** [comment]
Sorry if this was me - I did not work on Friday...
