### ISSUE TITLE
Make pop-ups in data entry function the same way

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#5065]
During single record data entry, selecting a scientific name identification is often done from a pop-up showing all options.  The pop-up is outside of the screen and can be manipulated for size and location.  

<img width="1503" alt="Screen Shot 2022-09-16 at 8 11 34 AM" src="https://user-images.githubusercontent.com/15368365/190660696-d1782439-6c62-45d0-afe7-5289850fd478.png">

Selecting a higher geography or specific locality, however, results in a pop-up that is constrained by the size of the Arctos screen.

<img width="1983" alt="Screen Shot 2022-09-16 at 8 16 17 AM" src="https://user-images.githubusercontent.com/15368365/190661715-b7ea8e1d-a8d6-4a89-b388-9d71a16a0d76.png">

<img width="1913" alt="Screen Shot 2022-09-16 at 8 16 23 AM" src="https://user-images.githubusercontent.com/15368365/190661731-04b66b04-5dcf-4581-801e-d3eaff499bb5.png">

Often, there's need for significant manipulation to find, then select the appropriate locality.  Without a  magic mouse there's lots of scrolling around and having the pop-up be constrained within the screen makes it frustrating - especially as the pop-up size often changes without warning.  The scroll bar at the bottom is often hidden depending on the outer scroll bar position.  

Is there a reason for the pop-ups not all functioning the same way?  Can the geography pop-ups be like the Identification pop-up?  

The request to [provide the option to hide the empty columns](https://github.com/ArctosDB/arctos/issues/4349) (and put the most important columns first) still stands.

**Comment by dustymc** [comment]
The first is an "old style" popup window.

The second is a "modern" modal.

Popups get blocked by some browsers and lost by users and such, but there are still lots of them in Arctos and I'm not sure there's any current compelling technical argument to banish them. I assume that will be a bit of a sustainability issue, that browsers will just block or not handle them correctly at some point, but who knows what the future holds.

Guidance, @ArctosDB/arctos-working-group-officers ??

**Comment by campmlc** [comment]
If there is an alternative to popups, I say we use that. Pop ups get lost
behind my windows and I frequently don't even know they are there, even
when they aren't blocked by my browser. Pop up blockers are so common as to
make this an issue.

**Comment by Jegelewicz** [comment]
> Popups get blocked by some browsers and lost by users and such, but there are still lots of them in Arctos and I'm not sure there's any current compelling technical argument to banish them. I assume that will be a bit of a sustainability issue, that browsers will just block or not handle them correctly at some point, but who knows what the future holds.

Can we do the same thing in a separate tab? The ability to make use of all the functionality of a geography or taxonomy search when adding data seems like it would be useful. I just don't know if it is possible?

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/5553
