### ISSUE TITLE
Error Creating Agent or Person

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#5066]
On https://arctos.database.museum/agents.cfm, clicking on Create Agent or Create Person, you get the same error below (missing a template). 
Try it for fun! I dont think it's related to my local environment (FF on Mac)

<div style="border:2px solid green; padding: 1em; margin: 1em; text-align: center;"></div>

ERROR_ID | FA69F7A6-0EBD-4EE4-97648E8AE9A0F743
-- | --
ERROR_TYPE | template
ERROR_MESSAGE | missing terminating [#] for expression
ERROR_DETAIL |  

</div>

<p>request dump:</p>

        

<div id="xs63" class="-lucee-dump">

request
--
node_name | stringarctos-2021 | string | arctos-2021
string | arctos-2021
rdurl | string/includes/forms/createagent.cfm?person&&&& | string | /includes/forms/createagent.cfm?person&&&&
string | /includes/forms/createagent.cfm?person&&&&
uui | string | string |  
string |  
uuid | stringFA69F7A6-0EBD-4EE4-97648E8AE9A0F743 | string | FA69F7A6-0EBD-4EE4-97648E8AE9A0F743
string | FA69F7A6-0EBD-4EE4-97648E8AE9A0F743

</div>

**Comment by dustymc** [comment]
Blargh, this is the same as https://github.com/ArctosDB/arctos/issues/5064 and I've got a bunch of stuff torn apart at the moment - I'll figure something out as soon as I can....

**Comment by dustymc** [comment]
patched
