### ISSUE TITLE
Taxonomy: Family Update for Sphecius speciosus

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#5067]
We have 7 Sphecius speciosus (cicada killers) between two collections (CHAS:Ento and CHAS:Teach). While trying to integrate specimens today, we noticed that the Family name has changed.

Taxonomy page: https://arctos.database.museum/name/Sphecius%20speciosus

Under data from Arctos, the Family is listed as Sphecidae, the source being ITIS as of February 2007.
![image](https://user-images.githubusercontent.com/93737929/190726448-b179a16e-34c2-4ef9-98c6-53c8b3df6371.png)

However, ITIS currently classifies Sphecius speciosus as Family Crabronidae.
![image](https://user-images.githubusercontent.com/93737929/190726565-b2c26308-df17-4159-971c-b8bfea0bd7ee.png)

There are also instances of Sphecidae being listed under a data source, but not associated with Family level, just kind of floating around at the top.
![image](https://user-images.githubusercontent.com/93737929/190726744-587e1334-f02b-4d1d-affa-f214e2cd3b76.png)

Questions
1. Am I allowed to update the taxonomy in Arctos as a source from Sphecidae to Crabronidae, given that its original source was ITIS and ITIS has since changed? Or is that something the taxonomy committee needs to discuss, since this change potentially impacts specimens from ACUNHC:Ento as well?
2. Since Arctos as a data source is using ITIS as a source authority, is it possible that Arctos could update taxonomy, based on that field, when "Refresh/pull Global Names" is clicked? Or does it have to be done manually when we discover it?

Thanks!

**Comment by dustymc** [comment]
See https://github.com/ArctosDB/arctos/issues/3607, I still would not under any circumstances invest anything in the Arctos classification.

I interpret https://github.com/ArctosDB/arctos/issues/3121 as The Community accepting updates from whatever, and nothing in https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxonomy_source#arctos changes my outlook - if you really feel the need, goferit....

> it possible that Arctos could update taxonomy

I don't see any way that could be workable, but if you like ITIS then https://github.com/ArctosDB/arctos/discussions/4965 would let you just use it.

**Comment by Jegelewicz** [comment]
@wellerjes ITIS is a terrible source for taxonomy IMO. Because GBIF is now integrating WoRMS and other managed sources into it's taxonomic backbone, I tend to use the GBIF taxanomic data as my default in the Arctos source.

Actually, it would be great if we could just use GBIF. I believe they make periodic updates to the backbone. If we can figure out their schedule, we could update when they do. Given the opportunity, I would use the GBIF backbone in preference to the Arctos source.

**Comment by dustymc** [comment]
>ITIS is a terrible source

EVERYTHING seems to be a terrible source for someone; that's why we have many options.

> if we could just use GBIF

Still https://github.com/ArctosDB/arctos/discussions/4965.

**Comment by Jegelewicz** [comment]
> Still https://github.com/ArctosDB/arctos/discussions/4965.

And still problematic? I assume that directly using GBIF (not GlobalNames GBIF) will pose many of the same issues we currently experience with WoRMS (via Arctos). Any update from GBIF is likely to eat up a lot of CPU? I feel like WoRMS (via Arctos) IS our test case and it is not quite functioning as we had hoped.

**Comment by dustymc** [comment]
What do you think might be problematic?

>not GlobalNames GBIF

CPU is a relatively small part of problem. Doing what GN has done should be expected to take something like the same amount of resources they needed to do it, which AFAIK is significantly more than we have available. Why not just use GN?

**Comment by campmlc** [comment]
Isn't this what we do when we make changes to Arctos taxonomy? Since GN
harvests from that? I'm still using Arctos fwiw for lack of an alternative.

**Comment by dustymc** [comment]
Not sure what that means, but all Arctos taxonomy is available for download.

"Using" the Arctos (or Arctos Plants) source as a catchall seems reasonable to me, at least as long as https://github.com/ArctosDB/arctos/discussions/4965 is limiting the options. Updating/curating any of the huge legacy messes is what I think isn't a great investment.

**Comment by Jegelewicz** [comment]
@wellerjes let's return to the original request.

> Am I allowed to update the taxonomy in Arctos as a source from Sphecidae to Crabronidae, given that its original source was ITIS and ITIS has since changed? Or is that something the taxonomy committee needs to discuss, since this change potentially impacts specimens from ACUNHC:Ento as well?

ACUNHC:Ento has no subject matter expert. I suggest you make the changes as you see fit.

> Since Arctos as a data source is using ITIS as a source authority, is it possible that Arctos could update taxonomy, based on that field, when "Refresh/pull Global Names" is clicked? Or does it have to be done manually when we discover it?

As far as I know, this is a manual process. @dustymc might be able to update a whole resource from GN (like ITIS) upon request though.

> There are also instances of Sphecidae being listed under a data source, but not associated with Family level, just kind of floating around at the top.

We have no control over what the external resources do and these cannot be edited, so there is nothing to be done about that one.

**Comment by wellerjes** [comment]
I updated the Family classification in Arctos as a source, okay to close. I'll revisit this in a new issue if updating from a whole resource would be beneficial; I haven't run into it since this original issue.
