### ISSUE TITLE
print stuff not working

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#5068]
I have a batch of labels to print; from the search results, I went to the manage dropdown, selected "Print any Report"; Arctos opens a new page and I clicked on the link to continue to the Arctos reporter. The page tries to load for a bit, then I got the following message:

The connection was reset
The connection to the server was reset while the page was loading.
    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.

I tried to run the report in Chrome and got a similar message. I tried running troubleshoot on my computer and it came back with no issues on my end (at least with my computer).

**Comment by dustymc** [comment]
restarted

**Comment by wellerjes** [comment]
Reopened - same process to get to reports, but now it is telling me "nope" after I click on the link to access the reporter.

**Comment by dustymc** [comment]
The reporter is happy, that's usually (always??) from some nonlinear entry path - search, click straight through.

**Comment by wellerjes** [comment]
It appears to only be my computer, and only in Firefox. It works okay in Chrome. Do I need to clear a cache or something?

**Comment by dustymc** [comment]
That is unexpected! Maybe some extension or setting?? It's usually the ad company's browser which caches overly aggressively and causes this sort of problem. If you don't have any addons which might cause this then yes, I suspect something is somehow sideways and clearing cookies/cache is a good place to start.
