### ISSUE TITLE
Problems setting up customized data entry profile

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#5069]
Trying to set up a customized data entry profile for MSB:Birds.
Go to:  Data Entry > Begin with a Blank Slate > MSB:Bird
Form populates with messy tables all over the place in table view.
Switch to dynamic view
Edit table positions - none of which fit nicely together on the screen - like Tetris but with irregular tables that are puzzle pieces that do not fit, lots of jagged edges and blank spaces that cannot be made compatible - can we fix this?
Then try to go back to Table view to save profile- but this table to allow switch to dynamic view has disappeared? 

Rather than do this dysfunctional Tetris over and over for each collection, can we make it possible to just clone a functional profile already in use and modify for a different collection? And please make Save and Edit tools more visible. 

Priority: moderately high - would be nice to get this working for new students to do data entry.

Screenshot showing missing table/dynamic view tool - I looked behind every visible table.

![Screenshot 2022-09-17 15 26 10](https://user-images.githubusercontent.com/14808196/190877100-2d1ba3ba-3d68-43c0-ba4e-35830fdc75d5.png)

**Comment by campmlc** [comment]
So there is some more weirdness - the table view showed up later after I left the form and came back to it. But when I click dynamic view again, it shows up very briefly and then disappears before I can click it. Same when I go to new collections I haven't set up yet - the table/dynamic option flashes briefly, then disappears.

**Comment by campmlc** [comment]
Firefox

**Comment by dustymc** [comment]
> Form populates with messy tables all over the place in table view.

You've customized on some other wildly-different device?

> showed up later after I left

That almost has to be a local problem. Suggest restarting everything.

The finder should stay near the top of the stack unless you've placed it elsewhere.

The initial load is from your last view, so yes - opening a new collection will look just like wherever you set off, you can save a new profile from there.

I like the gridless system - there can be nothing more compact or customizable - and it's not some mistake nor dysfunctional. You can of course file an Issue for some other option, but I think you have environmental problems which need solved first.

**Comment by campmlc** [comment]
Windows/Firefox on a laptop?

**Comment by campmlc** [comment]
And I did not move the finder/save tool. It flashed and disappeared.
