### ISSUE TITLE
Quarantine Taxon Name - Arphia tenerosa

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#5073]
Issue Documentation is at http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

Name Quarantine Documentation is at https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxon_name_type

### Name suggested for quarantine
Arphia tenerosa
https://arctos.database.museum/name/Arphia%20tenerosa

### Replacement Name
Arphia tenebrosa

### Reason for quarantine 
Misspelled; the correct version is also invalid; valid taxon: Arphia pseudonietana
https://bugguide.net/node/view/81841
https://www.gbif.org/species/1710269

[ The following steps are not required for the initial request, and may be completed by community members with sufficient access. Please do not remove the text below. ]

### Relationship

[ INITIALLY OPTIONAL, requires manage_taxonomy access: Create a suitable taxon relationship between the nominated and replacement name. ]

### Taxonomy Committee Project

[ INITIALLY OPTIONAL: Please add this issue to the Taxonomy Committee Project. ]

### Collection Summary and Contacts

[ INITIALLY OPTIONAL, requires manage_taxonomy access: use the Manage Data / Metadata / Quarantine Taxon tool to provide a summary of the collections using the nominated name. Make sure the github contacts are outside any code block; they should turn into links. ]

### Data

[ INITIALLY OPTIONAL, requires manage_taxonomy access: use the Manage Data / Metadata / Quarantine Taxon tool to provide data sufficient to un-do this action ]

### Pause

Allow 30 days for all affected collections to respond. Proceed only after 30 days (and an issues committee meeting) has passed, or after all affected collections have approved the quarantine proposal.

### Update Identifications

[ AFTER PAUSE, requires manage_taxonomy and global_admin access: use the Manage Data / Metadata / Quarantine Taxon tool to update identifications. The tool will change all ID formulae to "A {string}" and move all references to the quarantined taxon to the replacement. ]

### Finalize Quarantine

[ AFTER PAUSE, requires manage_taxonomy and global_admin access: use the Manage Data / Metadata / Quarantine Taxon tool to quarantine the taxon name, making it unavailable for all use excepting relationships ]

### Close this issue

[ After all of the above have been completed, close this issue ]

**Comment by dustymc** [comment]
Can't proceed without initially required information

>[ INITIALLY REQUIRED: Replace this with a link to the suggested replacement name. The link should be of the form https://arctos.database.museum/name/.... ]

**Comment by wellerjes** [comment]
https://arctos.database.museum/name/Arphia%20tenebrosa

**Comment by dustymc** [comment]
[temp_taxon_quarantine_summary(5).csv.zip](https://github.com/ArctosDB/arctos/files/9801387/temp_taxon_quarantine_summary.5.csv.zip)

**Comment by Jegelewicz** [comment]
Appropriate time has elapsed, but no notifications were made. However, CHAS is the only institution using the name.

GUID_PREFIX | ACCEPTED_ID_FG | NUMBERIDS | LINK_TO_RECORDS | TAXON_NAME | LINK_TO_TAXON
-- | -- | -- | -- | -- | --
CHAS:Ento | 0 | 1 | https://arctos.database.museum/SpecimenResults.cfm?taxon_name_id=10965024 | Arphia tenerosa | https://arctos.database.museum/name/Arphia tenerosa

**Comment by Jegelewicz** [comment]
Also - somebody already quarantined the name. Closing
