### ISSUE TITLE
Quarantine Taxon Name - Mermirini

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#5074]
Issue Documentation is at http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

Name Quarantine Documentation is at https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxon_name_type

### Name suggested for quarantine
Mermirini
https://arctos.database.museum/name/Mermirini

### Replacement Name
Mermiriini (there are two i's between r and n)
https://arctos.database.museum/name/Mermiriini

### Reason for quarantine 
Misspelled
https://www.catalogueoflife.org/data/taxon/8PT9X

[ The following steps are not required for the initial request, and may be completed by community members with sufficient access. Please do not remove the text below. ]

### Relationship

[ INITIALLY OPTIONAL, requires manage_taxonomy access: Create a suitable taxon relationship between the nominated and replacement name. ]

### Taxonomy Committee Project

[ INITIALLY OPTIONAL: Please add this issue to the Taxonomy Committee Project. ]

### Collection Summary and Contacts

[ INITIALLY OPTIONAL, requires manage_taxonomy access: use the Manage Data / Metadata / Quarantine Taxon tool to provide a summary of the collections using the nominated name. Make sure the github contacts are outside any code block; they should turn into links. ]

### Data

[ INITIALLY OPTIONAL, requires manage_taxonomy access: use the Manage Data / Metadata / Quarantine Taxon tool to provide data sufficient to un-do this action ]

### Pause

Allow 30 days for all affected collections to respond. Proceed only after 30 days (and an issues committee meeting) has passed, or after all affected collections have approved the quarantine proposal.

### Update Identifications

[ AFTER PAUSE, requires manage_taxonomy and global_admin access: use the Manage Data / Metadata / Quarantine Taxon tool to update identifications. The tool will change all ID formulae to "A {string}" and move all references to the quarantined taxon to the replacement. ]

### Finalize Quarantine

[ AFTER PAUSE, requires manage_taxonomy and global_admin access: use the Manage Data / Metadata / Quarantine Taxon tool to quarantine the taxon name, making it unavailable for all use excepting relationships ]

### Close this issue

[ After all of the above have been completed, close this issue ]

**Comment by dustymc** [comment]
Summary:

|guid_prefix|accepted_id_fg|numberids|link_to_records|taxon_name|link_to_taxon|
|--|--|--|--|--|--|
|CHAS:Ento|0|1|https://arctos.database.museum/SpecimenResults.cfm?taxon_name_id=10965040|Mermirini|https://arctos.database.museum/name/Mermirini|


Data Quality Users:


@wellerjes
@droberts49


used only by requesting collection, no waiting period is necessary.


[temp_taxon_quarantine_reloader(12).csv.zip](https://github.com/ArctosDB/arctos/files/9637408/temp_taxon_quarantine_reloader.12.csv.zip)
