### ISSUE TITLE
Bulk Edit Parts without Barcodes

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#5075]
We do not currently have barcodes set up for our entomology collection. We have a cabinet that needs to have the Cornell drawers shifted in order to make room for newly cataloged specimens. Is there a way to either:
- bulk unload part attributes, or
- overwrite current part attributes?

I see there is a form for to "[Bulk Edit Parts](https://arctos.database.museum/loaders/bulk_edit_parts.cfm?action=ld)" - will this overwrite the current part attributes? I want to make sure I have a correct understanding of the form before I try to process any data.

Thanks!

**Comment by dustymc** [comment]
<img width="484" alt="Screen Shot 2022-09-20 at 10 34 50 AM" src="https://user-images.githubusercontent.com/5720791/191326165-8b7df7de-45da-454d-82dd-57b47f7961a8.png">

will get partIDs that work in the part loaders.

I don't think overwrite can be safely implemented.

An attribute unloader could be developed. I'm not entirely convinced there's ever a reason to remove an attribute which might solve some future problem, but maybe the history of administrative stuff causes more problems than it solves.

Bulk edit parts does nothing for attributes.

**Comment by Jegelewicz** [comment]
@wellerjes consider just adding a new part location attribute with the date of the move. This give you a location history but still lets you find stuff (in the most recent location).
