### ISSUE TITLE
error feedback

### ISSUE THREAD

**Issue by BAcordCNDDB** [ArctosDB/arctos#5077]
I'm trying to query and download specimen records, specifically Charina records from the central Sierra Nevada. If I am not logged in, I can query the records just fine; I get results. However, to download the records I need to be logged in. So, I log in and run the same query or alternative queries but keep getting an error page, attached. 

![CaptureMVZ_2022-09](https://user-images.githubusercontent.com/29760364/191365000-fc62d89b-2a7d-4cd9-b343-d51656a385a8.JPG)

** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **

** Outages should be reported to the contacts listed at https://arctosdb.org/arctos-down/ **

** Arctos Documentation is http://handbook.arctosdb.org/ **

** Learn more about Arctos at https://arctosdb.org/ **

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **

**Comment by Jegelewicz** [comment]
@BAcordCNDDB you must have some privileges in Arctos (data entry, etc.) If this is true, when you are logged in, you ONLY have access to collections that you are allowed to edit. I suggest you create a second Arctos user account so that you can download information from collections other than those to which you have edit access.

If this doesn't fix your problem, please post here!

**Comment by BAcordCNDDB** [comment]
Thanks Teresa, I've never had this issue before and have been using this same and only account for about the past 10 years. Wouldn't it be odd for a generic accounts properties to change in the past few days?
Sincerely,
Brian
--
Brian Acord // CNDDB zoology
CDFW<https://www.wildlife.ca.gov/>//Biogeographic Data Branch<https://www.wildlife.ca.gov/Explore/Organization>
https://www.wildlife.ca.gov/Data/CNDDB

New mailing address:
California Department of Fish & Wildlife (CDFW)
California Natural Diversity Database (CNDDB)
PO Box 944209
Sacramento, CA 94244

New physical address:
1700 9th Street, 4th floor, Sacramento

**Comment by dustymc** [comment]
Thanks @BAcordCNDDB  the problem should be corrected, you'll need to log out and back in.

**Comment by BAcordCNDDB** [comment]
I think its working. Thanks!  :)

--
Brian Acord // CNDDB zoology
https://www.wildlife.ca.gov/Data/CNDDB
