### ISSUE TITLE
column "drainage" does not exist

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5078]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
trying to search some fish records

**To Reproduce**
1. Go to Search > Catalog Records
2. Select Collection = CSULB:Fish
3. See error

**Expected behavior**
See some results

**Screenshots**

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**
<html><body>

ERROR_ID | 5ECA75CB-4C28-473E-8C984BECEEB5CFD8
-- | --
ERROR_TYPE | SQL
ERROR_MESSAGE | ERROR: column "drainage" does not exist   Where: PL/pgSQL function getgeographyterm(bigint,text) line 14 at FOR over EXECUTE statement
ERROR_DETAIL |  
ERROR_SQL | create table  temp_cache.ss_jegelewicz_2022092004094328_765 AS  SELECT distinct  flat.collection_object_id 			,concatSingleOtherId(flat.collection_object_id,$other identifier$)  AS CustomID, 			$other identifier$ as myCustomIdType, 			ConcatSingleOtherIdInt(flat.collection_object_id,$other  identifier$) AS CustomIDInt,flat.guid as guid,flat.catalognumberint as  catalognumberint,flat.othercatalognumbers as  othercatalognumbers,flat.ACCESSION as  accn_number,getJsonMediaUriBySpecimen(flat.collection_object_id) as  media,flat.scientific_name as scientific_name,flat.identifiedby as  identified_by,flat.id_sensu as id_sensu,flat.made_date as  id_date,flat.formatted_scientific_name as  sci_name_with_auth,flat.previousIdentifications as  id_history,flat.identification_remarks as  identification_remarks,flat.nature_of_id as nature_of_id,flat.made_date  as made_date,flat.kingdom as kingdom,flat.phylum as  phylum,flat.phylclass as phylclass,flat.phylorder as  phylorder,flat.superfamily as superfamily,flat.family as  family,flat.subfamily as subfamily,flat.tribe as tribe,flat.subtribe as  subtribe,flat.genus as genus,flat.species as species,flat.subspecies as  subspecies,flat.typestatus as citations,flat.relatedcatalogeditems as  relatedcatalogeditems,flat.collectors as collectors,flat.preparators as  preparators,concatCollectorAgent(flat.collection_object_id,'creator') as  creator,flat.SPECIMEN_EVENT_TYPE as  specimen_event_type,flat.EVENT_ASSIGNED_BY_AGENT as  event_assigned_by_agent,to_char(flat.EVENT_ASSIGNED_DATE,'yyyy-mm-dd')  as event_assigned_date,flat.collecting_source as  collecting_source,flat.SPECIMEN_EVENT_REMARK as  specimen_event_remark,flat.continent_ocean as continent_ocean,flat.sea  as sea,flat.country as country,flat.state_prov as state_prov,flat.quad  as quad,flat.feature as  feature,getGeographyTerm(flat.collection_object_id,'drainage') as  drainage,flat.county as county,flat.island_group as  island_group,flat.island as island,flat.min_elev_in_m as  min_elev_in_m,flat.max_elev_in_m as max_elev_in_m,flat.minimum_elevation  as minimum_elevation,flat.maximum_elevation as  maximum_elevation,flat.orig_elev_units as orig_elev_units,case when  flat.MIN_ELEV_IN_M is null then null else flat.MIN_ELEV_IN_M\|\|'-'\|\|  flat.MAX_ELEV_IN_M end as elev_in_m,case when flat.MIN_DEPTH_IN_M is  null then null else flat.MIN_DEPTH_IN_M\|\|'-'\|\| flat.MAX_DEPTH_IN_M end  as depth_in_m,flat.spec_locality as spec_locality,flat.locality_remarks  as locality_remarks,flat.verbatim_locality as  verbatim_locality,flat.habitat as habitat,flat.LOCALITY_NAME as  locality_name,flat.collecting_method as  collecting_method,flat.verbatim_date as verbatim_date,flat.began_date as  began_date,flat.ended_date as  ended_date,getDayCollected(flat.began_date,flat.ended_date) as  day_collected,getMonthCollected(flat.began_date,flat.ended_date) as  month_collected,flat.year as year_collected,flat.parts as  parts,flat.partdetail as partdetail,case strpos(flat.parts,'skull') when  0 then 'false' else 'true' end as skull_yn,flat.remarks as  remark,flat.collecting_event_id as  collecting_event_id,flat.VERBATIM_COORDINATES as  verbatim_coordinates,flat.orig_lat_long_units as  orig_lat_long_units,flat.dec_lat as dec_lat,flat.dec_long as  dec_long,flat.coordinateuncertaintyinmeters as  coordinateuncertaintyinmeters,flat.verificationstatus as  verificationstatus,flat.datum as datum,flat.GEOREFERENCE_PROTOCOL as  georeference_protocol,flat.GEOREFERENCE_SOURCE as  georeference_source,flat.individualcount as  individualcount,flat.formatted_scientific_name as  formatted_scientific_name,flat.COLL_EVENT_REMARKS as  coll_event_remarks,flat.associated_species as  associated_species,getSpecimenEventDeterminer(flat.collection_object_id)  as  specimeneventdeterminer,CONCATTYPESTATUS_FULLPUB(flat.collection_object_id)  as long_citation,flat.json_locality as  json_locality,flat.full_taxon_name as full_taxon_name,flat.enteredby as  entered_by,flat.related_record_cache as  related_record_summary,flat.attributedetail::varchar as  attributedetail,flat.LastPartLocation as  lastpartlocation,concatAttributeValue(flat.collection_object_id,'abundance')  as abundance,concatAttributeValue(flat.collection_object_id,'age') as  age,concatAttributeValue(flat.collection_object_id,'age class') as  age_class,concatAttributeValue(flat.collection_object_id,'air  temperature') as  air_temperature,concatAttributeValue(flat.collection_object_id,'archaeological  feature') as  archaeological_feature,concatAttributeValue(flat.collection_object_id,'axillary  girth') as  axillary_girth,concatAttributeValue(flat.collection_object_id,'bill  depth') as  bill_depth,concatAttributeValue(flat.collection_object_id,'bill length')  as bill_length,concatAttributeValue(flat.collection_object_id,'bill  width') as  bill_width,concatAttributeValue(flat.collection_object_id,'body  condition') as  body_condition,concatAttributeValue(flat.collection_object_id,'body  temperature') as  body_temperature,concatAttributeValue(flat.collection_object_id,'body  width') as  body_width,concatAttributeValue(flat.collection_object_id,'breadth') as  breadth,concatAttributeValue(flat.collection_object_id,'brood patch') as  brood_patch,concatAttributeValue(flat.collection_object_id,'bursa') as  bursa,concatAttributeValue(flat.collection_object_id,'bursa length') as  bursa_length,concatAttributeValue(flat.collection_object_id,'bursa  width') as  bursa_width,concatAttributeValue(flat.collection_object_id,'calcar  length') as  calcar_length,concatAttributeValue(flat.collection_object_id,'carapace  length') as  carapace_length,concatAttributeValue(flat.collection_object_id,'caste')  as caste,concatAttributeValue(flat.collection_object_id,'clutch size')  as clutch_size,concatAttributeValue(flat.collection_object_id,'clutch  size of nest parasite') as  clutch_size_of_nest_parasite,concatAttributeValue(flat.collection_object_id,'colors')  as colors,concatAttributeValue(flat.collection_object_id,'copyright  status') as  copyright_status,concatAttributeValue(flat.collection_object_id,'credit  line') as  credit_line,concatAttributeValue(flat.collection_object_id,'crop  contents') as  crop_contents,concatAttributeValue(flat.collection_object_id,'crown-rump  length') as  crown_rump_length,concatAttributeValue(flat.collection_object_id,'culmen  length') as  culmen_length,concatAttributeValue(flat.collection_object_id,'culture of  origin') as  culture_of_origin,concatAttributeValue(flat.collection_object_id,'culture  of use') as  culture_of_use,concatAttributeValue(flat.collection_object_id,'curvilinear  length') as  curvilinear_length,concatAttributeValue(flat.collection_object_id,'description')  as  description,concatAttributeValue(flat.collection_object_id,'dimensions')  as dimensions,concatAttributeValue(flat.collection_object_id,'diploid  number') as  diploid_number,concatAttributeValue(flat.collection_object_id,'ear from  crown') as  ear_from_crown,concatAttributeValue(flat.collection_object_id,'ear from  notch') as  ear_from_notch,concatAttributeValue(flat.collection_object_id,'ectoparasite  examination') as  ectoparasite_examination,concatAttributeValue(flat.collection_object_id,'ectoparasites  detected') as  ectoparasites_detected,concatAttributeValue(flat.collection_object_id,'egg  content weight') as  egg_content_weight,concatAttributeValue(flat.collection_object_id,'eggshell  thickness') as  eggshell_thickness,concatAttributeValue(flat.collection_object_id,'electrical  conductivity') as  electrical_conductivity,concatAttributeValue(flat.collection_object_id,'endoparasite  examination') as  endoparasite_examination,concatAttributeValue(flat.collection_object_id,'endoparasites  detected') as  endoparasites_detected,concatAttributeValue(flat.collection_object_id,'examined  for parasites') as  examined_for_parasites,concatAttributeValue(flat.collection_object_id,'exhibit  caption') as  exhibit_caption,concatAttributeValue(flat.collection_object_id,'experimental')  as  experimental,concatAttributeValue(flat.collection_object_id,'extension')  as extension,concatAttributeValue(flat.collection_object_id,'fat  deposition') as  fat_deposition,concatAttributeValue(flat.collection_object_id,'forearm  length') as  forearm_length,concatAttributeValue(flat.collection_object_id,'framed')  as framed,concatAttributeValue(flat.collection_object_id,'gonad') as  gonad,concatAttributeValue(flat.collection_object_id,'head length') as  head_length,concatAttributeValue(flat.collection_object_id,'head width')  as head_width,concatAttributeValue(flat.collection_object_id,'height')  as height,concatAttributeValue(flat.collection_object_id,'hind foot with  claw') as  hind_foot_with_claw,concatAttributeValue(flat.collection_object_id,'hind  foot without claw') as  hind_foot_without_claw,concatAttributeValue(flat.collection_object_id,'hind  limb length') as  hind_limb_length,concatAttributeValue(flat.collection_object_id,'historical')  as historical,concatAttributeValue(flat.collection_object_id,'image  confirmed') as  image_confirmed,concatAttributeValue(flat.collection_object_id,'incubation  stage') as  incubation_stage,concatAttributeValue(flat.collection_object_id,'inscriptions  and marks') as  inscriptions_and_marks,concatAttributeValue(flat.collection_object_id,'isotope  value') as  isotope_value,concatAttributeValue(flat.collection_object_id,'keywords')  as keywords,concatAttributeValue(flat.collection_object_id,'left gonad  length') as  left_gonad_length,concatAttributeValue(flat.collection_object_id,'left  gonad width') as  left_gonad_width,concatAttributeValue(flat.collection_object_id,'location  in host') as  location_in_host,concatAttributeValue(flat.collection_object_id,'materials')  as materials,concatAttributeValue(flat.collection_object_id,'maximum  standard length') as  maximum_standard_length,concatAttributeValue(flat.collection_object_id,'maximum  total length') as  maximum_total_length,concatAttributeValue(flat.collection_object_id,'middle  toe length') as  middle_toe_length,concatAttributeValue(flat.collection_object_id,'minimum  standard length') as  minimum_standard_length,concatAttributeValue(flat.collection_object_id,'minimum  total length') as  minimum_total_length,concatAttributeValue(flat.collection_object_id,'molt  condition') as  molt_condition,concatAttributeValue(flat.collection_object_id,'NAGPRA  category') as  nagpra_category,concatAttributeValue(flat.collection_object_id,'neck  width') as  neck_width,concatAttributeValue(flat.collection_object_id,'nest  description') as  nest_description,concatAttributeValue(flat.collection_object_id,'nest  phenology') as  nest_phenology,concatAttributeValue(flat.collection_object_id,'number of  labels') as  number_of_labels,concatAttributeValue(flat.collection_object_id,'numeric  age') as  numeric_age,concatAttributeValue(flat.collection_object_id,'object  title') as  object_title,concatAttributeValue(flat.collection_object_id,'ovum') as  ovum,concatAttributeValue(flat.collection_object_id,'parasites found')  as parasites_found,concatAttributeValue(flat.collection_object_id,'parts  examined') as  parts_examined,concatAttributeValue(flat.collection_object_id,'pit  depth') as  pit_depth,concatAttributeValue(flat.collection_object_id,'plastron  length') as  plastron_length,concatAttributeValue(flat.collection_object_id,'provenience')  as  provenience,concatAttributeValue(flat.collection_object_id,'provenience  east') as  provenience_east,concatAttributeValue(flat.collection_object_id,'provenience  north') as  provenience_north,concatAttributeValue(flat.collection_object_id,'quadrant')  as quadrant,concatAttributeValue(flat.collection_object_id,'radiometric  date') as  radiometric_date,concatAttributeValue(flat.collection_object_id,'reproductive  data') as  reproductive_data,concatAttributeValue(flat.collection_object_id,'right  gonad length') as  right_gonad_length,concatAttributeValue(flat.collection_object_id,'right  gonad width') as right_gonad_width,flat.sex as  sex,concatAttributeValue(flat.collection_object_id,'skull ossification')  as  skull_ossification,concatAttributeValue(flat.collection_object_id,'snout-vent  length') as  snout_vent_length,concatAttributeValue(flat.collection_object_id,'SNV  results') as  snv_results,concatAttributeValue(flat.collection_object_id,'soft parts')  as soft_parts,concatAttributeValue(flat.collection_object_id,'square')  as square,concatAttributeValue(flat.collection_object_id,'standard  length') as  standard_length,concatAttributeValue(flat.collection_object_id,'stomach  contents') as  stomach_contents,concatAttributeValue(flat.collection_object_id,'stratigraphic  position') as  stratigraphic_position,concatAttributeValue(flat.collection_object_id,'tail  base width') as  tail_base_width,concatAttributeValue(flat.collection_object_id,'tail  condition') as  tail_condition,concatAttributeValue(flat.collection_object_id,'tail  length') as  tail_length,concatAttributeValue(flat.collection_object_id,'tarsus  length') as  tarsus_length,concatAttributeValue(flat.collection_object_id,'tested for  presence') as  tested_for_presence,concatAttributeValue(flat.collection_object_id,'thumb  length with claw') as  thumb_length_with_claw,concatAttributeValue(flat.collection_object_id,'tooth  length') as  tooth_length,concatAttributeValue(flat.collection_object_id,'tooth  width') as  tooth_width,concatAttributeValue(flat.collection_object_id,'total  length') as  total_length,concatAttributeValue(flat.collection_object_id,'tragus  length') as  tragus_length,concatAttributeValue(flat.collection_object_id,'trap  type') as  trap_type,concatAttributeValue(flat.collection_object_id,'unformatted  measurements') as  unformatted_measurements,concatAttributeValue(flat.collection_object_id,'value')  as value,concatAttributeValue(flat.collection_object_id,'verbatim host  age') as  verbatim_host_age,concatAttributeValue(flat.collection_object_id,'verbatim  host ID') as  verbatim_host_id,concatAttributeValue(flat.collection_object_id,'verbatim  host sex') as  verbatim_host_sex,concatAttributeValue(flat.collection_object_id,'verbatim  preservation date') as  verbatim_preservation_date,concatAttributeValue(flat.collection_object_id,'water  temperature') as  water_temperature,concatAttributeValue(flat.collection_object_id,'weight')  as weight,concatAttributeValue(flat.collection_object_id,'width') as  width,concatAttributeValue(flat.collection_object_id,'wing chord') as  wing_chord,concatAttributeValue(flat.collection_object_id,'wing span')  as wing_span,concatAttributeValue(flat.collection_object_id,'year  class') as year_class from flat INNER JOIN cataloged_item ON  (flat.collection_object_id = cataloged_item.collection_object_id)  WHERE  flat.collection_object_id IS NOT NULL  			 and  			 				flat.guid_prefix 				in 				 					( 					'CSULB:Fish' 					) 				 				 			 			 			limit 500000

</body>
</html>

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by dustymc** [comment]
Same as https://github.com/ArctosDB/arctos/issues/5077, log out and back in, I fixed it (or hope so) for everyone.

**Comment by Jegelewicz** [comment]
Thanks!
