### ISSUE TITLE
Code Table Request - Collection Object: Other Identifier Types: WK

### ISSUE THREAD

**Issue by ehalverson26** [ArctosDB/arctos#5082]
**Goal**
Add an additional object identifier to the code table to accommodate additional but specific object identifiers for the UWZM frozen tissue collection.

**Context**
Same concept as New Mexico (NK), Alaska (AF), Angelo State (ASK). To be used as an identifier for frozen tissue collections with the UWZM.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type

**Proposed Value**
WK for field, numerical sequence to be entered. Ex: WK 100

**Proposed Definition**
University of Wisconsin Karyotype Number. A frozen tissue collection number for University of Wisconsin Zoological Museum.

**Collection type**
All

**Attribute data type**
Number

**Attribute value**
[ For categorical attributes, code table controlling value  ]

**Attribute units**
[  For number+units attributes, code table controlling units  ]

**Available for Public View**
Yes

**Other ID BaseURL**
[  For OtherIDs, provide the following *or* explain why the unresolvable ID type is necessary:
1. "Base URL" with which to prepend entered values, and
2. A functional example URL, which should consist of the base URL provided in (1) plus a relevant value.  ]

**ID_References**
[  If the request involves https://arctos.database.museum/info/ctDocumentation.cfm?table=ctid_references, the changes must be coordinated with the Database Admin team for notifications to function.  ]

**Priority**
[  Please choose a priority-label to the right.  ]

**Comment by Jegelewicz** [comment]
> numerical sequence to be entered. Ex: WK 100

All the other identifiers like this would do the following:

attribute | attribute value 
 -- | -- 
WK | 100 

This will appear on the record as WK100

**Comment by ehalverson26** [comment]
I believe that looks good and should work!

**Comment by Jegelewicz** [comment]
Code Table Committee says OK, but the definition is misleading

**Proposed Definition**
University of Wisconsin frozen tissue number. A frozen tissue collection number for University of Wisconsin Zoological Museum. May also be referred to as a karyotype number.

**Comment by Jegelewicz** [comment]
Added

**Comment by Jegelewicz** [comment]
@ehalverson26 you can now use the WK identifier.

**Comment by ehalverson26** [comment]
Great! For the original purposed definition, I did use Alaska's AF, New Mexico's, NK and Angelo State's ASK as a model definition and was trying to keep it somewhat standardized. If the committee felt that definition was misleading, it may be necessary to review AF, NK and ASK. Thanks!

**Comment by dustymc** [comment]
I think it can be re-added - it's one of the few "local types" with no possible ambiguity in meaning and I think we're stuck with those. (Err, sorta. I'll never be able to really know what "WK" on a tag means - probably Wacław Kopisto, are we really sure we have the appropriate permits?! - but they'll know and I guess that's close enough.... This should be formalized so we don't have to guess at what's an appropriate type!)

**Comment by dustymc** [comment]
Agreed - we don't need the type at all (except maybe in what seems a bit like 'include me in the screenshot, bro' use cases) but picking battles and low-information identifiers and etc.....
