### ISSUE TITLE
Code Table Request - Collection Object: Other Identifier Types: Prep Number

### ISSUE THREAD

**Issue by ehalverson26** [ArctosDB/arctos#5083]
**Goal**
Add an additional object identifier to the code table to accommodate additional but specific object identifiers for the UWZM collection.

**Context**
The term Prep Number is used in our museum in conjunction with accession and catalog numbers. It is specific to one specimen and a place holder when the specimens initially get accessioned and until they are prepared and determined what collection they will be cataloged and housed in. It is used for the vast majority of our specimens and a unique and specific field. It is NOT the same as preparator number.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type

**Proposed Value**
processing number
~~free text; For our collections format should be begin with P, year, numeric value counting up. Ex: P2022-001, P2022-002.~~

**Proposed Definition**
**I**dentifier used to track a**n object** before it is cataloged.

~~Specimen identifier that refers to the year and sequence of intake for a single specimen. Used to track a specimen through the preparation process and before it is cataloged. (Make less specific if other collections were to use this field)~~

**Collection type**
All

**Attribute data type**
**Free text**

**Available for Public View**
Yes

**Priority**
High

**Comment by Jegelewicz** [comment]
> processing number

I like that one.

**Comment by Jegelewicz** [comment]
See updated request above.

**Comment by ehalverson26** [comment]
The term "Prep Number" is still described in the "Context" section but as long as that is okay, it looks good to me!
Thank you!

**Comment by Jegelewicz** [comment]
@ehalverson26 "context" doesn't make it into the end result, so it's OK.

**Comment by Jegelewicz** [comment]
added
