### ISSUE TITLE
Add missing provinces to Vietnam

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#5084]
### First Step: Explain what geography needs created.

Currently, there are 26 provinces in Vietnam Higher Geography in Arctos. 

[Wikipedia](https://en.wikipedia.org/wiki/Provinces_of_Vietnam) shows 58 plus 5 municipalities. 

[ GADM](https://gadm.org/maps/VNM_1.html) shows 65 first level divisions.

Can we add the additional provinces/municipalities from GADM to complete the data for Vietnam?  

Specifically, we need the Province Quang Ngai - https://en.wikipedia.org/wiki/Qu%E1%BA%A3ng_Ng%C3%A3i_province if you don't want to add all the subdivisions at this time.

****************************************************

We will respond with a CSV template, or request more information.

**Comment by dustymc** [comment]
@sharpphyl  please fill in some blanks at https://docs.google.com/spreadsheets/d/1PxdPJJEnT35WpbdUygll3GRMKC4tR87uxsfdk8fzrYY/edit?usp=sharing

Or I'll get there eventually...

I added a column and mapped existing to Arctos (I hope...), those DO NOT need anything (unless there's some problem), I'll not make new but will copy the vietnamese to search terms (so our not-so-great transliterations aren't a barrier).

For the rest, two things are necessary:

* SOURCE_AUTHORITY needs to be a wikipedia link, and
* barring https://github.com/ArctosDB/arctos/issues/5076 taking us in some radical direction, STATE_PROV and COUNTY need transliterated to ASCII128

I can try to transliterate, but it'll just be a primitive replace and I'm not sure whatever I muck up will be justified by whatever time it might save, but let me know if you want me to try (or I'll try to work on this more later, maybe I'll figure it out then).

https://github.com/ArctosDB/arctos/issues/4783 might radically change the landscape - it could mean we don't need to transliterate, or I can do it - or not, I don't yet have access, I'm guessing and hoping....

I'm leaning towards creating entire countries by default  - it's not that much more work, it's certainly much, much less work than eg revisiting vietnam maybe-dozens of times, and it means the next person who shows up with data has geography waiting for them. Please let me know if you have other thoughts about that, or anything else in here.

**Comment by sharpphyl** [comment]
> please fill in some blanks at

The scope of this has mushroomed from adding around 30-40 provinces to over 770 subdivisions.  I added the Wikipedia link for the Provinces that are not currently in Arctos and a few others before I looked at the overall scope.   Are those the blanks you wanted me to fill in?

If we're confident with the accuracy of GADM, do we still need to add Wikipedia as the authority?  Wikipedia is good data and looks like there are links for all the counties based on the sample I completed, but it's time-consuming for you, me or anyoe else to add it to every record. 

> creating entire countries by default

Makes sense to me and then all the data is there for everyone to use without having to constantly ask you to add one more province or county.  Is there any downside to do this?

**Comment by dustymc** [comment]
>770

Yikes! (I never look at data until I have to...)

>accuracy of GADM, do we still need to add Wikipedia 

I've gone back and forth a bit, but I keep finding situations where I can't make sense of one without the other. I (reluctantly) think they're both necessary.

>time-consuming

Maybe it just has to be, and I think you can just call this my problem if you want. I'd definitely like to at least have ya'll say "yep, you didn't completely muck that up in any apparent way" before I start smashing buttons, but I don't expect the cost of getting one entry to involve looking up 769 more either. If you're not in some huge hurry - maybe can amuse yourself with Morocco, which I think I almost have wrapped up - I can see what I can script. Let me know if you are and - well, I'll do something....

> any downside

It's a decent amount of storage, but that's relatively cheap these days so I'm not sure that's a cost worth worrying about.

If Vietnam up and renames all their provinces or moves the borders tomorrow then MAYBE it will be a mess to clean up, but I'd probably start that by nuking everything that's not used so that's sorta theoretical on theoretical.

I think that's a "not really"??

**Comment by dustymc** [comment]
@sharpphyl check out the edit_this_one tab https://docs.google.com/spreadsheets/d/1PxdPJJEnT35WpbdUygll3GRMKC4tR87uxsfdk8fzrYY/edit#gid=1739631357

I converted state and county to ASCII - I may have horribly mangled something, please keep an eye on them.

I magicked source_authority URLs from wikipedia. I absolutely mangled a few of these - eg Vietnam | Hoa Binh | Mai Chau got linked to https://en.wikipedia.org/wiki/Mai_Ch%C3%A2u, that is clearly wrong, it should be https://en.wikipedia.org/wiki/Mai_Ch%C3%A2u_district/

That will probably be a pattern, more people are interested in towns than admin divisions, I don't think I can do much better with the scripts, at least not in any reasonable amount of time. 

Hopefully I did enough to make this sort of thing a bit more digestible, I'm of course open to other opinions. I'll get back to this tomorrow, way too much blood in my alcohol system to keep going tonight...

**Comment by dustymc** [comment]
See https://github.com/ArctosDB/arctos/issues/5076#issuecomment-1255333983, I'm going to load/clean/homogenize GADM1 only at this time unless I'm directed elsewhere

**Comment by dustymc** [comment]
[temp_vn_prov.csv.zip](https://github.com/ArctosDB/arctos/files/9629280/temp_vn_prov.csv.zip)

These are loaded, cleaned, and homogenized.

I removed one GADM2-level record (used by https://arctos.database.museum/guid/UTEP:Herb:64533) in anticipation of the above-linked comment.

@sharpphyl please close if this addresses your need, or let me know if it needs more discussion.

**Comment by sharpphyl** [comment]
Everything we need is now in higher geography so I'll close this.  Thanks!
