### ISSUE TITLE
catalog record bulkloader error handling

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#5085]
# Error Text
<html>
<body>

ERROR_ID | FB995AF7-ECFB-4E37-A48D214A99AF1636
-- | --
ERROR_TYPE | SQL
ERROR_MESSAGE | ERROR: new row for relation "bulkloader" violates check constraint "ck_other_id_num_2_noprt"
ERROR_DETAIL |  
ERROR_SQL | insert into bulkloader select * from bulkloader_stage

</body>
</html>

# Where it happened
Bulkloader

# Steps to get there
Loaded the file, clicked check and load, got error. I had previously loaded this file, successfully checked it, got some errors and fixed them. The column I fixed was other_id_num_type_2 NOT other_id_num_2, so I don't know why the check won't even run now.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Here is the file

[Moore_81801-82068.csv](https://github.com/ArctosDB/arctos/files/9619626/Moore_81801-82068.csv)

**Comment by Jegelewicz** [comment]
81971 - other id 2 is "JM170624002 " - it has a trailing space

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks! Is there a reason this isn't just flagged in the checker rather than the checker just failing?

**Comment by Jegelewicz** [comment]
Thats a question for @dustymc

**Comment by dustymc** [comment]
I'll agree that SOMETHING needs to happen.

I think the cleanup tools - should be an option after load - will strip junk.

I think the pre-bulkloader handles this, and certainly could if it doesn't.

I don't think I can check without causing more timeouts at this level, but maybe that's a tradeoff we're willing to make??

Some big-picture guidance would be useful - is the single-user approach (which allows the cleanup tools) still viable, do we need the pre-bulkloader, can we push everything through the pre-bulkloader, etc. etc???

**Comment by campmlc** [comment]
It would be great if we could have the records load, and then the ones with an error could be flagged in the loader. Having an entire bulkload file fail to load due to these cryptic messages is extraordinarily frustrating and difficult to resolve. 
Making the cleanup tools as a default option to strip junk after load sounds ideal. Have a message - "Arctos has detected non-printing characters or terminal spaces in your file. Allow cleanup operation on file to enable load? Yes/No"  and proceed.

**Comment by campmlc** [comment]
Personally, I find the pre-bulkloader interface very difficult to use and confusing. And I'm an experienced user. Perhaps we can combine the useful tools from the pre-bulkloader with the single user interface into a  step by step bulkload process with informative messaging that would allow users to pass checkpoints and resolve issues in a guided process.

**Comment by sharpphyl** [comment]
This is also a problem with single-record data entry when we have "extras" identifications that end up in a bulkloader.  If the trailing spaces and other junk could be automatically stripped out, that would be very helpful.

**Comment by dustymc** [comment]
>automatically stripped

I don't think that can be viable.

* You type ``cañón`` and don't bother with [encoding](https://handbook.arctosdb.org/documentation/encoding.html)
* Whatever editor you're using converts that to ``ca��n``
* The proposed automagicker converts that to ``can``

And so you happily and unknowingly create a whole bunch of completely indecipherable and unrecoverable nonsense (there are surely lots of failures which don't start with ``cañón`` but still lead to ``can``) and (rightly) proclaim Arctos to be broken.

Lots of things might be done, but I don't think any form of 'just strip it' can be one of them.

There can certainly be 'just strip it' tools (there are a couple now, could be more), but they **must** be seen as tools which require careful operators reviewing the results, not magic.

>"extras" identifications

Excellent and increasingly relevant point: the catalog record bulkloader is but one of many-and-growing ways to introduce streadsheets-n-such to Arctos. Whatever is done should be done on a global scale.

**Comment by dustymc** [comment]
from @Jegelewicz 

>Every single one of these (there were also some in other_identifier and collecting_method) were either two spaces next to each other OR a trailing space. I spent about 30 minutes this morning figuring them all out and correcting them. If I just put TRIM in front of every lookup I do to get stuff into the bulkloader format, none of it would have happened. Lesson learned, but I still probably won't remember to do it and on a really large file, it takes up computing power. Cleaning up data is NOT for the fainthearted.

Cleaning whitespace requires two clicks:

<img width="132" alt="Screen Shot 2022-10-05 at 9 57 42 AM" src="https://user-images.githubusercontent.com/5720791/194118469-89c976bf-fe4f-4bae-9376-ecc709497311.png">
<img width="102" alt="Screen Shot 2022-10-05 at 9 57 49 AM" src="https://user-images.githubusercontent.com/5720791/194118487-a58771f4-ffc9-405c-b9cc-06a4c0a86ced.png">

but the cautions above apply - you still need to confirm that didn't make any '[cans](https://github.com/ArctosDB/arctos/issues/5085#issuecomment-1259641226).'

**Comment by campmlc** [comment]
I still think we could provide a message such as 
> "Arctos has detected non-printing characters or terminal spaces in your file. Allow cleanup operation on file to enable load? Yes/No"
which would then direct users to the option of the Cleanup Tools,
With a warning that they should carefully check the file. However, we need to offer users better directions and tools for checking their data. When someone like @Jegelewicz might hae to spend 30 min going out of her way to track down cryptic hidden double spaces, the rest of us would spend hours, and we'd still likely miss the cans
 ['https://github.com/ArctosDB/arctos/issues/5085#issuecomment-1259641226.'](url)
How can we provide users with better messaging to direct them to the problems in their data, so they can find and fix the issues?

**Comment by campmlc** [comment]
Is there no tool out there that would provide a csv list of the problem records in a datafile with the option of fixing them? Something we could add to Arctos tools available for bulkload?

**Comment by campmlc** [comment]
But how would we know we didn't create any "cans"? I don't have screening
tools at that level. When we are processing legacy migration data, we
aren't familiar with the data at that level to catch those things, and
honestly, neither are the various operators at the various incoming
collections since most of this is legacy data. Ideally, we'd have a tool
that would give us an easily readable list of the the various errors about
to be trimmed/corrected, for approval prior to load.

**Comment by dustymc** [comment]
>But how would we know we didn't create any "cans"?

Don't do the things I refuse to do without checking the results (I refuse because I can't check) and you'll be fine.

This has obviously swung way too far in the wrong direction, I have a recipe to check for nonprinting, I'll push it out tonight. It is crazy expensive and bigger files are going to fail, but at this point that seems the lesser evil. The pre-bulkloader is underutilized and built to deal with any amount of data, so a pathway for loads of any size remains available.
