### ISSUE TITLE
Code Table Request - pathology attributes

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5087]
**Goal**
UWZM has some people interested in pathologies, but I also happen to know that there is some of this in UTEP:ES. They have pathology data that they would like to preserve and be able to search.

[Pathology: Non-normal skeletal conditions that include lytic, proliferative and deformative lesions, as well as accessory bones, non- fusion anomalies and antemortem trauma.](https://github.com/ArctosDB/data-migration/issues/667#issuecomment-1244068562)

**Context**
This data is structured a lot like the current parasite attributes:

AttributeType | Description
-- | -- 
ectoparasite examination  | Was a systematic effort made to detect ectoparasites on this organism? (Not applicable to incidental detections.) 
ectoparasites detected | Apply this attribute to animals examined specifically for  ectoparasites. Do not use this attribute if ectoparasites were collected  only incidentally. "Yes" for positive findings, "no" for negative  findings. 
endoparasite examination | Was a systematic effort made to detect endoparasites on this organism? (Not applicable to incidental detections.) 
endoparasites detected | Apply this attribute to animals examined specifically for  endoparasites. Do not use this attribute if endoparasites were collected  only incidentally. "Yes" for positive findings, "no" for negative  findings.
examined for parasites | Do not use, deprecated term. Be more specific: Use  "ectoparasite examination" and "ectoparasite(s) detected," or  "endoparasite examination" and "endoparasite(s) detected."

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecpart_attribute_type

**Proposed Value**
What if, instead of creating a bunch of "examined for" and "detected" attributes, we only have one version of these then use a code table to select the thing that was detected? Also - these should be associated with the appropriate part, so I have moved them to the part attribute table.

examined and detected
examined and not detected
detected
not examined

**Proposed Definition**

**examined and detected** - The attribute value was detected during a systematic examination. Do not use this attribute for incidental detection.

**examined and not detected** - The attribute value was not detected during a systematic examination.

**detected** - The attribute value was detected incidentally. Do not use this attribute for detection made during a systematic examination.

**not examined** - No examination was made for the attribute value.

**Collection type**
Bird, ES, Herp, Host, Mamm, Teach

**Attribute data type**
categorical

**Attribute value**

**ectoparasite** - parasites that live on the external surface of hosts, for example fleas and lice of various terrestrial vertebrates, and Monogenea and Copepoda of freshwater and marine fishes.

**endoparasite** - parasites that live in the tissues and organs of their hosts, such as tapeworms, flukes, and protozoans of vertebrates.

**pathology** - Non-normal skeletal conditions that include lytic, proliferative and deformative lesions, as well as accessory bones, non- fusion anomalies and antemortem trauma.

**Available for Public View**
Yes

So, instead of this

<html><body>

Attribute | Value | Determiner | Date | Method | Remark
-- | -- | -- | -- | -- | --
ectoparasite examination | no | Troy Harrell | 1990-07-30 |   |  
endoparasite examination | yes | Troy Harrell | 1990-07-30 |   | none found
endoparasites detected | no | Troy Harrell | 1990-07-30 |   |  

you would have

Attribute | Value | Determiner | Date | Method | Remark
-- | -- | -- | -- | -- | --
not examined | ectoparasite | Troy Harrell | 1990-07-30 |   |  
examined and not detected | endoparasite | Troy Harrell | 1990-07-30 |   |

**Comment by dustymc** [comment]
I'm not sure I'm madly in love with this particular path, but these have needed better handling for a long time and I don't have better ideas so I support this.


While we're cleaning:

parasites found [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#parasites_found)

```
 guid_prefix | count 
-------------+-------
 MSB:Host    | 18734
```

Tentatively suggest converting to ``endoparasite examination`` with verbose remarks; some will be wrong, the remarks should easily clarify.




parts examined [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#parts_examined)


```
 guid_prefix | count 
-------------+-------
 MSB:Bird    |     1
 MSB:Host    |   780

```

append to method of an ``endoparasite examination`` attribute, or add such attribute if necessary


tested for presence [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#tested_for_presence)


```
 guid_prefix | count 
-------------+-------
 UAM:Env     |   334
```

should be brought closer into alignment, and this suggests 'examination' may not quite be the right word - I think these functionally differ only by vaguely-implied method (human digging around in guts vs. chemical magic). That said, I can't think of a word that encompasses 'tested' and 'examined' so ???

@campmlc @KyndallH

**Comment by dustymc** [comment]
From @jldunnum in https://github.com/ArctosDB/arctos/issues/5147#issuecomment-1275190379

>OK if we went this route, what would be the next steps? Lots more potential layers in the pathogen metadata than there are in the simple physical examination of a bone for pathology or presence of a parasite. Not sure how broad metagenomic screening would fit into this model.  Also terminology-wise we "screen" for pathogens as opposed to "examine".

> Lots more potential layers

Elaborate?

The attribute is that you looked or didn't and found something or didn't, the value is what you found (or didn't or whatever), and that could be anything from 'pathogen' to - well, whatever. (But if that "whatever" is complicated - eg has taxonomy, and not necessarily just Linnean - then it probably needs a catalog record to hold that complication, and there's no reason to complicate the 'source' record by trying to overload it with data it can't carry - just 'found some {category}' is enough.

'metagenomic screening' is method.

examine/screen sounds close enough to the same to me so I don't think I have any preferences other than consistency.

**Comment by jldunnum** [comment]
Lots more potential layers

Elaborate?


Might need to re-query some virologists and bioinformaticians once we have a general framework. In our discussions folks have been interested in titers, viral loads, etc., basically various quantification values derived during pathogen screening. Then there are the data associated with the genomic screening methods (sequencing method, platform, depth of coverage), and the bioinformatics analyses afterward.

______________________________________________________________

Jonathan L. Dunnum Ph.D. (he, him, his)
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

Chair, Systematic Collections Committee, American Society of Mammalogists
Latin American Fellowship Committee, ASM

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by dustymc** [comment]
Yes, some actual data and some annotation or input from the potential users would be exceedingly useful. I suspect we'll end up with one general 'looked for {category}' attribute and one or more grungy details structures of some sort - attributes, related records, external resources, linked Media, not really a lot of barriers here.....

**Comment by Jegelewicz** [comment]
>  titers, viral loads, etc., basically various quantification values derived during pathogen screening. Then there are the data associated with the genomic screening methods (sequencing method, platform, depth of coverage), and the bioinformatics analyses afterward.

Isn't this a lot like the [DNA stuff](https://github.com/ArctosDB/arctos/issues/3624) we recently added? Just a bunch more attributes of some kind?

**Comment by Jegelewicz** [comment]
I need to set upa couple of use cases - then let's look at it.

**Comment by Jegelewicz** [comment]
UTEP Pathologies - https://arctos.database.museum/SpecimenResults.cfm?&guid_prefix=UTEP:ES&part_condition=%25patholo%25

**Comment by Jegelewicz** [comment]
Examples in test where I jury-rigged this up.

https://arctos-test.tacc.utexas.edu/guid/MSB:Mamm:158399
https://arctos-test.tacc.utexas.edu/guid/MSB:Mamm:127129
https://arctos-test.tacc.utexas.edu/guid/UTEP:ES:120-1045

This still doesn't cover WHAT ectoparasites, endoparasites, or pathologies were detected. For the parasites, I can figure it out because the things detected are either parts or associated catalog records (although there may be cases where this isn't true?). For the pathologies, I suppose the pathology details could be recorded in the attribute remark, but at some point I feel like there will be a need to find all the "xyz pathologies". I guess we can deal with that when it becomes an issue, but I think that may happen soon given the UWZM stuff.

> there's no reason to complicate the 'source' record by trying to overload it with data it can't carry - just 'found some {category}' is enough.

That makes sense for things that could or should get cataloged elsewhere or have appropriate parts available - pathology doesn't, which is why I suggested the [new attribute](https://github.com/ArctosDB/arctos/issues/5101). Also, FWIW, just because there are ectos and endos associated with a record doesn't mean they were all discovered in whatever exam happens to be documented in these attributes, so I feel like we are still cobbling together something that should be an event with all of it's own details.

At TDWG last week there was a presentation on the [Humboldt Core](https://www.tdwg.org/community/osr/humboldt-core/#goals%20outputs%20and%20outcomes) extension to Darwin Core with use cases for biological inventories. While watching it, I began to feel that "examined for" is an event that we are forcing into an attribute. This is maybe OK, but at some point in the future maybe not ideal. One of the issues Humboldt Core is looking to address is the ability to share presence/absence data and this is what an examination for something specific is going to generate - right?

I examine a bunch of dead mice for fleas and on some I find them and some I don't but I want to make sure that I report the examination and the findings in a way that lets others reproduce my "inventory". Adding a single "examination" event to all the mouse records indicates the scope of my inventory (all the mice appear in that event) but then I also need to indicate the results for each mouse. This seems appropriate as an attribute, but an attribute of the event (we currently don't have any "specimen event" attributes, which is where I think this belongs?). Any actual things found would ideally be reported as an associated catalog record (for parasites) or a catalog record attribute (pathology)

Of course, many of these exams are just made as part of preparation - not some specific "inventory", so maybe nobody cares? It definitely feels like we could have more than one option for doing this and we have gravitated toward attributes, but while we are considering a change, I think we should consider other possibilities as well...

Anyone is welcome to help clarify or shoot down any of this!

**Comment by dustymc** [comment]
An example of "pathology details" would still be very useful - this still looks like unnecessary (and potentially irreversible) scattering from here.

I'm also not convinced there's such a clear distinction between 'parasites' and pathologies, but see above.

>attribute of the event

Everything's an attribute of an event in certain models, but someone would need to write the proposal to make that reality. From there, I suppose it's not too unrealistic to look at any simpler (or more complicated, depending on your perspective) structure as a hack which could be better handled by a true event-based model.

**Comment by dustymc** [comment]
From https://github.com/ArctosDB/internal/issues/51

> scattered across about five different fields

Once this (or something like it) is solidified, I could set up a bot to create a 'detected' attribute, which should result in one way (minus whatever the other 4 fields are!) to find things with parasites (and maybe some other stuff). I'm not going to be able to tell ectos from endos so that would need a 'parasites' (what I can get from relationships) value. And on that note I don't think people can tell ectos from endos either (flip a coin for botflies?!), suggest merging those two into one and using method where more is currently asserted.

**Comment by campmlc** [comment]
Sorry, bots are ectos to any parasitologist. :)
I need to review this thread as I somehow missed it, but this also relates to our repeated request for a new pathology model most recently articulated by @jldunnum . I strongly support the two attribute model we came up with ten years ago, to separate the " examined for x y/n" and the "x found y/n" data fields. This is essential to get at prevalence. This is similar to the " tested for presence" attribute used by UAM for testing for eDNA,which could be used either for a taxonomic entity or for environmental contaminants. What is missing is some controlled vocabulary for what is examined or tested for. Ideally, we could use the same attribute to put in a taxonomic name or a virus name or a chemical contaminant. Failing that, we need separate attributes for different scenarios. Unfortunately, " parasites", either ecto or Endo, are not a taxonomic group, hence the used of these broader terms up to now.

**Comment by dustymc** [comment]
I think the data demonstrate conclusively that the 54 (2, whatever) attribute thing does not work (because it's not used as designed, not because the structure isn't capable of doing what it was built to do). IDK if what's proposed here does either, but it's a lot harder to avoid providing useful data in this model.

>This is essential to get at prevalence

Are you suggesting that what's been proposed somehow fails that?

>What is missing is some controlled vocabulary for what is examined or tested for.

That is in the proposal.

>taxonomic name

There's a node which can get at that and a method for involving it. That's above and beyond (and beside: both are necessary to answer all questions) this attribute.

**Comment by Jegelewicz** [comment]
OK - but make these **part attributes** edited [original proposal](https://github.com/ArctosDB/arctos/issues/5087#issue-1381447884).

**Comment by Jegelewicz** [comment]
> here are some pathology attribute examples to play with.
> 
> MSB is now archiving all the material from the island (Channel, San Nicolas, Catalina, etc.) foxes (Urocyon littoralis) managed by the Navy, and Nature Conservancy. So far we are just receiving blot clots and sera but that will soon change to full animals and tissues.
> 
> There will be vaccinations (i.e. rabies, canine distemper) and potentially medications that we would want to track dates and titers for. For animals that die we will have full necropsy data associated with them. They will look something like this.
> 
> San Nicolas Island fox (SNI-19-03 30119):
> 
> 1. Colitis, multifocal (70%) necrocystic, neutrophilic, transmural with intramural Spirocerca.
> 
> 2. Peritonitis, neutrophilic, fibrinous, hemorrhagic with mesenteric vascular proliferation.
> 
> 3. Aural (pinna) abscess, hemorrhagic, suppurative, fibrinous and multifocal abraisions; E. coli, Pasteurella canis, Staphylococcus pseudintermedius isolated.
> 
> 4. Otitis externa with mites (Otodectes) detected.
> 
> 5. Emaciation. (serious atrophy of fat).
> 
> 6. Interstitial nephritis, moderate, multifocal, nonsuppurative.
> 
> 7. Pulmonary bronchial/bronchiolar nematodes.
> 
> 8. Enteric cestodiasis and trematodiasis.
> 
>  
> 
> San Nicolas Island fox (SNI-19-04):
> 
> 1. Tubulointerstitial nephritis, severe, diffuse, chronic, nonsuppurative with tubular atrophy and interstitial fibrous connective tissue (chronic renal failure) and amyloid.
> 
> 2. Interstitial pneumonia, moderate, multifocal, histiocytic with intracytoplasmic refractile crystals (pneumoconiosis) and pleocellular interstitial pneumonia, multifocal.
> 
> 3. Pulmonary vascular hypertrophy/hyperplasia with bronchiolar intraluminal nematode.
> 
> 4. Myocardial degeneration, multifocal, chronic
> 
> 5. Thyroid interstitial amyloidosis
> 
> 6. Hepatic centrilobular degeneration, mild, attenuation.
> 
> 7. Colonic Spirocerca (10% of colon affected).
> 
> 8. Otitis externa with Otodectes detected.
> 
> 9. Mesentery / serosa small intestine: multifocal vasculitis with fibrinoid necrosis.
> 
>  
> 
> San Nicolas Island fox (SNI-19-10):
> 
> 1. Tubulointerstitial nephritis/nephrosis, chronic with cellular and red granular casts and tubular epithelial megalocytosis and karyosis and syncytial cells.
> 
> 2. Brain, diffuse white matter vacuolation (spongiosis) and presumptive astrocytosis.
> 
> 3. Pleuritis and bronchopneumonia, regionally extensive, neutrophilic with intralesional bacteria; Streptococcus canis and Staphylococcus pseudointermedius isolated.
> 
> 4. Cystitis, acute, neutrophilic
> 
> 5. Scant fat (perirenal, pericardial, mesenteric).
> 
> 6. Otitis externa with Otodectes dectected.
> 
> 7. Scant stomach contents.
> 
> 8. Mesenteric panniculitis, multifocal, necrotizing, histiocytic, neutrophilic, hemorrhagic .and colitis with intralesional bacteria and Spirocerca.
> 
>  
> 
> San Nicolas Island fox (SNI-21-11)
> 
> Cause of death: likely renal failure, emaciation with:
> 
> a. Colitis (100% affected with Spirocerca lesions), necrocystic and necrohistiocytic and mesenteritis, chronic, necrohistiocytic.
> 
> b. Emaciation
> 
> c. Interstitial nephritis, multifocal, nonsuppurative and severe interstitial fibrosis (renal failure).
> 
> Misc.
> 
> a. Otitis externa; mites detected in exudate.
> 
> b. Interstitial pneumonia, multifocal, nonsuppurative and multiple intrabronchial/ bronchiolar nematodes.
> 
> c. Enteric cestodiasis (Mesocestoides sp.).
> 
>  
> 
> San Nicolas Island fox (SNI-20-12)
> 
> 1. Cause of death: trauma with:
> 
> a. Crushed skull with maceration of the brain.
> 
> b. Fractured mandible and maxilla.
> 
> Misc.
> 
> a. Otitis externa with mites detected (Otodectes sp.).
> 
> b. Interstitial pneumonia (regionally extensive; one lobe), chronic, pleocellular with intralesional embryonated eggs and vasculitis, neutrophilic and hypertrophic/hyperplastic with smooth muscle hyperplasia and expansion of the intima; likely associated with Angiostrongylus vasorum.
> 
> c. Colitis (10% affected), necrocystic, histiocytic and pleocellular with intralesional Spirocerca.
> 
> d. Mesenteritis, moderate, diffuse, nonsuppurative and rarely granulomatous with intralesional nematodes and multifocal, fibrosing, histiocytic (Spirocerca) with intracytoplasmic grey/brown pigment.

Jonathan L. Dunnum Ph.D. (he, him, his)

**Comment by Jegelewicz** [comment]
Closing this in favor of a new proposal as discussed at today's pathology parasite meeting.
