### ISSUE TITLE
Integer field in other ID has decimal display?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#5089]
OTHER ID Edit in Catalog record integer field is displaying integers with a decimal - this implies we are allowing decimals in this field? I've already been asked this by divisions who we've told in the past that decimals are not allowed. Please clarify.

![Screenshot 2022-09-22 09 45 24](https://user-images.githubusercontent.com/14808196/191793472-0bc91b1b-c302-4efa-bffc-84a9053c899f.png)

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/2225

https://arctos.database.museum/tblbrowse.cfm?tbl=coll_obj_other_id_num is authoritative.
