### ISSUE TITLE
Query Stats not restricting to Begin and Ended Dates

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#5090]
**The bug**
Love the query stats (https://arctos.database.museum/info/queryStats.cfm) @dustymc 
however getting 500 errors because it is spitting out all years and not limiting to the Begin and Ended Dates as the form allows. 

A huge pain to compile this now. 

** High Priority**
Let me know whether it can be fixed today!

**Comment by dustymc** [comment]
I think its filtering properly, it's just a lot of data. Do you want it all, some subset, ??

**Comment by mkoo** [comment]
The implication  when you have a start and end date options is that the results will be only monthly stats for those inclusive dates-- instead I'm getting all available months (no filtering) so browser dies, arctos 500's, everyone's cranky... 
so can the filters based on those start and end dates be implemented? or just remove (my false hopes)?

**Comment by dustymc** [comment]
patched
