### ISSUE TITLE
Printing Stuff with mail merge in MS Word

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5091]
Create templates using .csv downloads form Arctos using mail merge in MS Word.

@dustymc I could use 2 csv files - one for a loan header and one for a loan invoice - just pick a loan for MSB:Mamm. Let me know if that's not enough info.

**Comment by campmlc** [comment]
use one of the 2021 loan templates for MSB - they have more updated data.

**Comment by dustymc** [comment]
Find a loan, print any report, then...

<img width="1002" alt="Screen Shot 2022-09-22 at 12 38 31 PM" src="https://user-images.githubusercontent.com/5720791/191836125-cbffe8d1-e827-4557-956b-7ab26fa35702.png">

view HTML to get standard loan header stuff as CSV

I grabbed the SQL from (old reporter) MSB_Mamm_loan_invoice, and (new report) loan_item_download will provide CSV for loan items. Use the same path to get there.

**Comment by dustymc** [comment]
See also https://www.avery.com/software/partners/google-drive and https://workspace.google.com/marketplace/app/avery_label_merge/687713670524 - I know nothing of them, just stumbled on them at some point. Sheets/docs seems nice because its easy to share and collaborate, but we can link to word templates in a github repo or whatever if necessary (might be an item for https://github.com/ArctosDB/arctos/issues/5092)

**Comment by Jegelewicz** [comment]
UTEP Loan Invoice SQL

select 
    flat.collection, 
    flat.collection_cde, 
    flat.scientific_name, 
    flat.cat_num, 
    flat.sex, 
    flat.collection_object_id, 
    specimen_part.part_name as part, 
    coll_object.condition part_condition, 
   CASE WHEN length(coll_object.condition) > 15 or flat.ENCUMBRANCES is not null THEN 'X' end AS has_appendix, 
     higher_geog || '. ' || spec_locality || '' || case when orig_lat_long_units is not null then '. ' ||  verbatim_coordinates  || ', ' || flat.datum else 'Not georeferenced.' end as locality,
    item_instructions, 
    loan_item_remarks, 
    coll_object.coll_obj_disposition, 
    flat.ENCUMBRANCES, 
    loan.loan_number,
    trans.trans_date,
    flat.datum,
    flat.verbatim_coordinates
from 
    loan_item, 
    loan,
    trans,
    specimen_part, 
    coll_object,
    flat
WHERE 
    loan.transaction_id = loan_item.transaction_id and
    loan.transaction_id = trans.transaction_id and
    loan_item.collection_object_id = specimen_part.collection_object_id AND
    specimen_part.collection_object_id = coll_object.collection_object_id and
    specimen_part.derived_from_cat_item = flat.collection_object_id and
    loan_item.transaction_id = #transaction_id# 
ORDER BY 
    flat.scientific_name,
    flat.cat_num::numeric

**Comment by Jegelewicz** [comment]
Ran the above and get

> The code you submitted contains illegal characters.

**Comment by dustymc** [comment]
I suspect you mean in writesql - it's paranoid (has to be), is probably concerned about your ||. I don't think the reporter cares.

**Comment by Jegelewicz** [comment]
I am trying to get the data in csv so that I can create a Word mail merge example for a loan. Please help with sql.

**Comment by Jegelewicz** [comment]
took out the || and get the same error

I am happy to work on the word mail merge option, but I need some data (and a way to get it)

**Comment by dustymc** [comment]
See report: utep_loan_invoice_csv

**Comment by Jegelewicz** [comment]
I have several examples in reports now - closing
