### ISSUE TITLE
GUI Request - Project page dates need better separation

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#5098]
currently dates in ISO format just runs together in an indecipherable fashion
Would be much better to have the middle hyphen be the work "to" with spaces on either side. (if the end date is missing I think no one will misunderstand that the project is ongoing)
![Project Detail_ oVert_ Open Exploration of Vertebrate Diversity in 3D (1)](https://user-images.githubusercontent.com/2523089/192375105-283be30c-ddaf-4f9c-a7ac-c6da5f4ea801.png)

**Comment by Jegelewicz** [comment]
Hopefully this was as easy as it looked....

**Comment by dustymc** [comment]
>Hopefully

Please confirm, don't hope.

**Comment by Jegelewicz** [comment]
> Please confirm, don't hope.

I apparently can't access test - where the heck is it nowadays?

**Comment by Jegelewicz** [comment]
OK it works, but this now probably looks weird?

2020-09-01 to ongoing 

![image](https://user-images.githubusercontent.com/5725767/192598221-78433b26-5df3-4b74-8e7a-bfa5d0a9cc4c.png)

Suggestions for making that better?

**Comment by mkoo** [comment]
weird but better (in my view)
a conditional display would be ideal (e.g. if ended date null, then omit "to") 
however, I dont have a better solution (thought of changing "ongoing" to "active" or "present" but still weird; maybe change "to" to "through")...

**Comment by Jegelewicz** [comment]
Added an if for the above.

**Comment by Jegelewicz** [comment]
Needs updating here too

![image](https://user-images.githubusercontent.com/5725767/192644449-4c45de6f-4c07-404a-8550-a01aec99c1a9.png)

**Comment by Jegelewicz** [comment]
Waiting on Dusty to pull so I can verify it works.

**Comment by dustymc** [comment]
test is current

**Comment by Jegelewicz** [comment]
Welp - that didn't work!

**Comment by Jegelewicz** [comment]
Ok - think I figured it out...

**Comment by Jegelewicz** [comment]
Nope - it's still broken. @dustymc I think I finally got it, can you check?
