### ISSUE TITLE
Need changes to container edit roles

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#5099]
Currently we have four roles for managing containers in object tracking. These are still poorly defined and need to be tweaked and updated to make them more functional for actual workflows and use.
Current roles are:
1) view container - allows users to view but not edit containers and barcodes
2) manage specimens - allows good student operators to edit specimens at the record level, and also to associate barcodes with specimens.
3) manage container - higher level access for collection managers only - allows create, delete, and edit containers
4) admin container -scary level control, create and manage barcode series

What we are missing: something as an alternative to manage specimens, so that novice users can just scan barcodes into positions in object tracking without editing catalog records. I have this need all the time when I am training new students - the first thing I want them to do in Arctos is scan cryovials into freezer box positions. I do not want to give them manage specimens access at this point. I just want to see if they can use a scanner properly. These students are only using object tracking - they are not in the regular Arctos catalog record database. 

The quickest and easiest thing that comes to mind is to add the ability to scan a barcode into position as part of the "data entry" role permissions, given that is the first role any student is given. 

Alternately, we rename all these object tracking roles as follows, to be consistent and more easily found and distinguished in the growing list of operator roles:
container_view
container_entry - this would be the new role, limited to scanning a barcode into a position and using batch scan tools only. 
container_manage
container_admin

**Comment by dustymc** [comment]
>still poorly defined

<img width="310" alt="Screen Shot 2022-09-26 at 2 36 42 PM" src="https://user-images.githubusercontent.com/5720791/192385229-f2d8cf8a-2e49-4ede-9cce-b6e292f0b8f6.png">
<img width="618" alt="Screen Shot 2022-09-26 at 2 36 50 PM" src="https://user-images.githubusercontent.com/5720791/192385234-2312fd84-a010-409c-9a85-71dc0403692d.png">
<img width="446" alt="Screen Shot 2022-09-26 at 2 37 01 PM" src="https://user-images.githubusercontent.com/5720791/192385243-421807d6-7657-42ac-aac1-7b39beaeb814.png">

?? I do not believe there can be, much less are, poorly-defined roles in Arctos.

> limited to scanning a barcode into a position and using batch scan tools 

I don't think I can write that code. MAYBE we could talk about it and come up with something that could be implemented at the business rule level (something like the screenshot above), but this really sounds like a great place to set them up with an Excel-or-whatever template, let them do stuff, carefully review it, use the tools to load it, and maybe think about giving them more access when they start providing good data. That should all exist, gives you a clear pathway to catching huge problems BEFORE they come to exist, provides a nice little view to evaluate whether they understand things (and perhaps thereby whether your procedures are understandable), etc., etc.

**Comment by campmlc** [comment]
This is the workflow I have used for the past 7 years, it works, and I'm not going to change it. If I have to keep giving them manage specimens to do so, I will. But that seems an absurb overkill given that they are just picking up a scanner for the first time.
I don't see the problem here.

**Comment by campmlc** [comment]
I have procedures in place to check and catch if they scan something incorrectly. But I shouldn't have to give them access to edit specimens for them to scan a barcode.

**Comment by campmlc** [comment]
And yes, they are also creating an Excel file at the same time - one of the double check procedures I just mentioned.

**Comment by campmlc** [comment]
@Jegelewicz

**Comment by dustymc** [comment]
>give them access to edit specimens 

I have no idea how this is related to container roles, or what it might mean for whatever you're trying to do when things aren't yet cataloged.

**Comment by campmlc** [comment]
In order for a student to be able to scan a cryovial barcode into a freezer box position, they must have the role view_container and also edit_specimens. I can't give them manage_container. There is no other role. The other role is what I'm asking for.
DGR operates entirely in object tracking, prior to things being cataloged.

**Comment by Jegelewicz** [comment]
@campmlc if they don't have access to any collections, this shouldn't matter? Can you give someone manage_specimens without access to a single collection? If so, could they still get the work done that you need?

**Comment by campmlc** [comment]
I need them to scan barcodes which may or may not be linked to parts in
multiple collections, so I have to give them access to all those
collections. I don't want them to have to give them manage specimen in all
those collections, but that's my only option right now. I'd prefer to just
give them only data entry access, or, better, since they never do data
entry, this new container_entry role.

**Comment by Jegelewicz** [comment]
I need to think on this for a bit - not sure how this could be accomplished....

**Comment by dustymc** [comment]
>how this could be accomplished.

It can't.

We can make a new role, but it will be "{[crud](https://en.wikipedia.org/wiki/Create,_read,_update_and_delete)} on {table}"

There's no way I'll successfully limit it to certain forms, and even if I could that's not sustainable going forward (eg into a future where everything runs through APIs and I have no idea what forms exist or how they work).

I am positive that we are missing information as well. The solution described above (granting manage_specimen) cannot address the described problem (scan barcodes which may or may not be linked to parts). Finding solutions starts with understanding problems - we need more information @campmlc

**Comment by dustymc** [comment]
From office hours - new role with update on container and nothing else - is that correct @campmlc ? It would be useful if you could review the existing role definitions to make sure that is the full and proper scope of this.

update_container is probably the most consistent name, assuming the above doesn't reveal anything interesting. container_whatever would sort better, I'm not opposed to that, but it's Major Surgery where just adding a role is trivial - maybe that's worth a hopefully-quick AWG-ish discussion??

>It isn't possible to give roles without access to collections

That is not true, please see https://handbook.arctosdb.org/documentation/users.html and let me know if anything isn't clear. I think the idea is about right when dealing with containers, but the more we're all on the same page the better this is going to work; it's useful to be precise here.

**Comment by campmlc** [comment]
I'd love to have all the container roles be consistent and sort together in the roles table - I think it would help people choose and assign the correct level of permission. I think we have enough roles now that navigating the table is already challenging. That is why I suggested changing the prefix to "container_". So changing the other role names is major surgery? If not, my preference is still "container_entry".

If it is too difficult, then I'd prefer the role name "enter_container", again because it sounds like data entry, which is equivalent to this entry level in the "other" catalog record database.  I don't want to imply there is any updating or editing going on here. The role should merely allow a student with a scanner to scan a barcode associated with their institution into a form (except for the scary barcode swapper).

As for giving roles without access to collections, while it may be possible to do so outside of object tracking, in object tracking, and therefore for my purposes, access to at least one collection in the institution is required in order for a student to have the ability to scan barcodes for that institution.  I agree with this, unless access can be given at the institution level for barcodes only. I particularly don't want to have to give the student access to manage specimen for all collections in the institution in order for them just to scan barcodes. Hence the request.

I don't know where to find that lovely table you referenced above at https://github.com/ArctosDB/arctos/issues/5099#issuecomment-1258668042? Do you need me to suggest which tables would be affected?

**Comment by dustymc** [comment]
Definitely surgery, not sure how major, we've never tried it. 

Not sure I understand "entry" when the only proposed operation is an update, but I suppose the name doesn't necessarily need to be intuitive, we're all reading the critically-important readme anyway, right?

>don't want to imply there is any updating

That is precisely what "student with a scanner to scan a barcode" does - 
```
update (container associated with one barcode) set parent = (container associated with the other barcode)
```
> where to find that lovely table

There are screenshots of the path in https://github.com/ArctosDB/arctos/issues/5099#issuecomment-1258668042, that's the aforementioned readme. Yes there are a bunch of container-tables, the various container-related roles are probably the most intuitive place to see them.

**Comment by campmlc** [comment]
Update to me implies some sort of conscious and deliberate change. Believe me, these students aren't doing anything consciously except for pointing a scanner at a barcode to get the code to "enter" into a cell. Hence "enter". 
Semantics aside, I still don't see where that table comes from. 
The following screenshots are what I see when I go to Arctos user and roles documentation. What is the "def" link? If I click the "link" next to the role, the row turns yellow, that's it. The rest is just links to the handbook.

![Screenshot 2022-09-27 19 51 09](https://user-images.githubusercontent.com/14808196/192669631-94251296-e748-408b-9f1d-e8edf049afe0.png)


![Screenshot 2022-09-27 19 50 31](https://user-images.githubusercontent.com/14808196/192669765-1522e4a0-644f-40a0-89cc-7e74e1e5fdeb.png)



![Screenshot 2022-09-27 19 49 36](https://user-images.githubusercontent.com/14808196/192669658-dfd5f703-11f6-4504-a80d-63756a2766fe.png)

**Comment by Jegelewicz** [comment]
"edit" vs. "update"

What about "move_container"?

**Comment by campmlc** [comment]
That works.

**Comment by campmlc** [comment]
That works.
In the meantime, I have a student who cannot scan barcodes into positions, which is holding up work. I have given her the following access: cold fusion user, data entry, manage specimens, view container, and access to MSB:Mamm.  She can pull up the freezer box positions form, but it looks strange as below, and she can't enter anything. What needs to happen here so she can have access to "move_container"?

![image](https://user-images.githubusercontent.com/14808196/193664515-8701d6a2-f473-41e0-8bb9-eb13b91609fa.png)

**Comment by dustymc** [comment]
I'm still not very happy with that role name, it implies things that are not true - if you can 'move' you can also eg change remarks and layout.

That may be related to me still not knowing exactly what you're asking for - it is only ``update`` on table ``container`` or something else?

Barcode has secondary control (requires admin_container to change), otherwise that will allow changing anything you can see in https://arctos.database.museum/tblbrowse.cfm?tbl=container

Is that the full and correct scope of this role?

**Comment by dustymc** [comment]
That's the table, the role map I suggested above it still probably better for overall understanding. I'll just do something unless you stop me now-ish....

**Comment by dustymc** [comment]
This is running in test, very very highly recommend extensive testing before usage. It's sort of hanging awkwardly in between other roles, I'd be half surprised if it doesn't do something unexpected somewhere.

For the record, I still have no idea how manage_specimens relates to any of this, and of course there is no safe level of access at all when "these students aren't doing anything consciously."

Please test and proceed very cautiously, if at all.

**Comment by campmlc** [comment]
Hoping I can delete the manage specimen role and this will still wallow
students to scan. Will test. Thanks!

**Comment by campmlc** [comment]
I don't know what the tables are - I still can't find that table you posted
earlier, per my earlier post - so that hampers my ability to respond. From
my view, I see tools and forms, not tables.
I need students to be able to access Find Container-> Container Details >
Positions for a freezer box, and scan a barcode into an empty cell.
More advanced students may use Batch Scan tools.
Both of these forms/tools effectively "enter" a barcode into a position in
the object tracking hiercharchy. They also work to be able to "move" an
existing barcode from one place in the hierarchy to another.
Currently, these students would also potentially see the other Container
Details fields, such as Edit Container. I do occasionally have advanced
students who need to be able to use those tools, e.g. to add remarks or to
see or download all collection objects. In that case, I'd need permissions
to allow those students access to those tools without having to give them
manage container.
Most of the time, however, they just scan, and they don't even see any
editing tools or pages.
