### ISSUE TITLE
[CONTACT] viewing pdf attached to accession

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#5100]
@dustymc I just uploaded a PDF to an accession, but I can't actually view the content of the file either on the accession page or the media detail page. I can edit the media record but can't view the actual media. Am I missing something? 

https://arctos.database.museum/media/10723078

**Comment by mkoo** [comment]
Did you click on the media icon? I can view it in my browser (maybe you have popups blocked??) or try a different browser to test

**Comment by ccicero** [comment]
No media icon was showing, but now it is - took a while. It shows in the accession page but not in the media detail page (not sure if it's supposed to or not).

**Comment by mkoo** [comment]
You mean this page? Shows up for me... and yes it's suppose to (ok to close?)
![Firefox_Screenshot_2022-09-27T16-46-28 672Z](https://user-images.githubusercontent.com/2523089/192586879-455eef2d-f020-4166-8a06-770f77f5d076.png)

**Comment by dustymc** [comment]
Yep, closing, with a reference to https://github.com/ArctosDB/arctos/issues/3331 which should make sure that some default image and alt text are available to browsers immediately after creation. (IDK what actually happened, this has always worked for me, looks like some combination of Arctos caching + browser caching + fairly particular create/edit procedure.)
