### ISSUE TITLE
Code Table Request - new catalog record attribute: pathology

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5101]
**Goal**
record details about pathology detected

**Context**
https://github.com/ArctosDB/data-migration/issues/667#issuecomment-1255312947

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type

**Proposed Value**
pathology

**Proposed Definition**
Non-normal skeletal conditions that include lytic, proliferative and deformative lesions, as well as accessory bones, non- fusion anomalies and antemortem trauma.

**Collection type**
Bird, Mamm, Fish, Herp, Amph, Rept, Vert, Teach

**Attribute data type**
free-text

**Available for Public View**
Yes

**Priority**
[  Please choose a priority-label to the right.  ]

**Comment by Jegelewicz** [comment]
> Non-normal skeletal conditions that include lytic, proliferative and deformative lesions, as well as accessory bones, non- fusion anomalies and antemortem trauma.

Could this be applied to things other than bones? Should we generalize the definition if so? @ehalverson26

**Comment by dustymc** [comment]
Why is this separate from https://github.com/ArctosDB/arctos/issues/5087?

**Comment by Jegelewicz** [comment]
Because it is kinda independent of it - we will ask for this either way that goes and I don't want to hold this up for that (which needs some considering...)

**Comment by dustymc** [comment]
>independent

I don't see it - the other thing has a 'just stumbled on it' option (if that's the concern), I can't see any reason anyone would ever need more, this just looks like simple denormalization (==hiding data from users by having many arbitrary places for it) from here at the moment.

**Comment by Jegelewicz** [comment]
See https://github.com/ArctosDB/data-migration/issues/667#issuecomment-1255312947

**Comment by dustymc** [comment]
Not sure what I'm looking for there, still two ways of saying the same thing.

Definitely agree that this belongs at the record level, unless we're prepared to have records for parts which no longer exist (eg something like/beyond https://github.com/ArctosDB/arctos/issues/3630)

**Comment by dustymc** [comment]
>pathology in tissues 

<img width="721" alt="Screen Shot 2022-09-29 at 9 09 32 AM" src="https://user-images.githubusercontent.com/5720791/193083031-d812dc6b-bcda-40fe-b7fe-0d56d9ab9adc.png">

"enlarged spleen" and similar are very common notations (at least when there's a parasitologist in the camp), I think that would end up in a better place if such a place were available.

**Comment by ewommack** [comment]
When you work with whole animals from vet labs, zoos, or rehab clinics you might get the pathology information from them.

**Comment by campmlc** [comment]
Following up with this as we are getting a lot of these data in a format that cannot easily be parsed by tissue type/part attributes. 
And to the previous point, this includes a lot of information on pathology in tissues but which needs to be recorded at the catalog record level. 
There is a ton of this info in the Rausch records at MSB that all got shoved into remarks.  I strongly support making this record level attribute available.

**Comment by campmlc** [comment]
Alternately, we could use the Examined for/Detected/Not Detected proposed attributes, and have pathology as a value in the code table.

**Comment by jldunnum** [comment]
We just received serology data for >8000 records of Panamanian rodents. Where can I put it?

______________________________________________________________
Jonathan L. Dunnum Ph.D. (he, him, his)
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

Chair, Systematic Collections Committee, American Society of Mammalogists
Latin American Fellowship Committee, ASM

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131

**Comment by dustymc** [comment]
Example data would be most useful in figuring that out. "All of it" is my preferred sample size.

I think the biggest hangup at the moment is probably https://github.com/ArctosDB/arctos/issues/5688 - there was a long discussion then everything reset as the meeting was ending and I have no idea what to do about that.

**Comment by Jegelewicz** [comment]
We have a meeting set for 2023-03-21 at 10AM MDT, perhaps we can figure it out now that we have a use case? But, yes, data in advance would be helpful.

**Comment by dustymc** [comment]
pruning offshoots
