### ISSUE TITLE
Code Table Request - add Collection "Herp" to Part_Name "scale" in table specimen_part_name

### ISSUE THREAD

**Issue by jtgiermakowski** [ArctosDB/arctos#5102]
**Goal**
I need "scale" to be part of Herp collections as a Part_Name, already exists for ES and Fish

**Context**
We received a series of scales from different squamates preserved separately in ISOH

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name

**Proposed Value**
scale - already exists but need to be part of Collection "Herp"

**Priority**
[  Please choose a priority-label to the right.  ]

**Comment by ebraker** [comment]
@jtgiermakowski added scale to Herp collections!
