### ISSUE TITLE
collector bulk-unloader

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#5104]
We have a large number of records with "unknown" as the collecting agent and a name in the "verbatim agent" field.  The number of these records is increasing as we move low-data agents from collector to verbatim agent/collector.

**Is your feature request related to a problem? Please describe.**
Currently, there is no way to bulk remove the "unknown" collector.  Manage/Agents only enables a new or replacement agent.  Bulkload agents also only adds agents.

**Describe what you're trying to accomplish** 
Unload "unknown" as the collector where we now have a "verbatim agent/collector."

**Describe the solution you'd like**
Add "delete/unload to the options under Manage/Agents or "unload agents" to bulkload agents.

**Describe alternatives you've considered**
Do it one by one.

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by Jegelewicz** [comment]
**Describe the solution you'd like**
A collector unloader (opposite of https://arctos.database.museum/tools/BulkloadCollector.cfm)

**Comment by sharpphyl** [comment]
Actually, what would be equally helpful is to add the option to DELETE to the Manage/Agents screen.  Today you can only replace one agent with another.

For example, here I can add A. Stark easily as a new attribute but I have to remove A. Stark as the collector by preparing a csv or manually for each record.  Even if I replace A. Stark with "unknown," I have to go back and delete it as the collector is known and listed directly below.  Can you add the option to DELETE an agent?

<img width="1489" alt="Screen Shot 2022-10-17 at 8 54 19 AM" src="https://user-images.githubusercontent.com/15368365/196210706-e0565ff5-b0f4-4cf2-ac3e-05c59f414d19.png">

**Comment by ewommack** [comment]
> Can you add the option to DELETE an agent?

That makes me super nervous. What if the agent you delete is used by a bunch of other collections too? How would we stop that from happening?

**Comment by ewommack** [comment]
> it wouldn't delete the agent, just the use of it in catalog records

Gotcha. Thanks for the clarification.

**Comment by dustymc** [comment]
>Can you add the option to DELETE an agent?

Yep.

>What if the agent you delete is used by a bunch of other collections 

It's definitely a potentially dangerous tool, but so is every other bulk tool. Don't give anyone you don't trust to read the fine print access to your collection, or to any bulk tools. You can check that here:

<img width="436" alt="Screen Shot 2022-10-17 at 1 28 00 PM" src="https://user-images.githubusercontent.com/5720791/196276728-67691d2a-b8cf-4f9f-8bc0-47c05980f0a8.png">

**Comment by Jegelewicz** [comment]
Could we also have an Agent unloader? It is a safer option IMO that some people might like to use instead.

**Comment by dustymc** [comment]
>Could we also have an Agent unloader?

Kinda no - I can't see enough need for a third identifier of unaccepted identifications unloader, but the replace tool handles that just fine (although not with that precision). We can have a collector unloader, I think that's probably most of the use case. I changed the title, let me know if I'm wrong and that's not useful or we do need more-targeted unloaders or whatever.

**Comment by Jegelewicz** [comment]
> We can have a collector unloader

That's what I am talking about.

**Comment by dustymc** [comment]
agent nullifier running at test and could use testing

todo: collector bulk unloader

**Comment by sharpphyl** [comment]
NULLIFY works great.  Thanks.

**Comment by Jegelewicz** [comment]
@camwebb I haven't used the NULLIFIER - but maybe that will help you out?

@dustymc is this still just in test or has it made it's way to production?

This will need documentation and perhaps a brief demo at the beginning of an AWG meeting?

**Comment by camwebb** [comment]
@Jegelewicz Not sure what the NULLIFIER is... the ability to delete an agent from a catalog record? Yes, that's good to have, but it's a one-by-one tool. We need a batch tool.

**Comment by dustymc** [comment]
>it's a one-by-one tool

Nope. 

<img width="463" alt="Screenshot 2023-06-15 at 8 27 08 AM" src="https://github.com/ArctosDB/arctos/assets/5720791/fa8934f9-365e-47bc-9f2e-c9c34739047b">

Find the agent, check the row, click NULL or select a replacement, click, and all records in the results get an update.

<img width="1692" alt="Screenshot 2023-06-15 at 8 29 40 AM" src="https://github.com/ArctosDB/arctos/assets/5720791/9bb6ebd3-46cc-45c6-ad63-33aacb20452c">

**Comment by camwebb** [comment]
Wow! This does the job we need! Had no idea this existed, and yes, I should have checked the [Docs](https://handbook.arctosdb.org/how_to/How-to-Batch-Update-Agents.html)... Thanks.

**Comment by camwebb** [comment]
Curious though, why is `replace_agents.cfm` not in [this](https://github.com/ArctosDB/arctos/tree/master/tools) directory, or anywhere in ArctosDB repo (that I can search, at least)? I did look for it based on the old title to this issue.

**Comment by dustymc** [comment]
https://github.com/ArctosDB/PG

**Comment by camwebb** [comment]
Ah - thanks. (It's hidden from me, but no worries)

**Comment by dustymc** [comment]
tabling this pending a tangible need not better served by other forms
