### ISSUE TITLE
geography for marine areas and edges

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5105]
@sharpphyl here's what I have at the moment that might be useful for you. Let me know if you want screenshots of the maps or whatever.

```
create table temp_maybe_wet as select source,search_terms from external_gis_data where source in ('eez_land_union','iho_world_seas','seavox_areas');
```

[temp_maybe_wet.csv.zip](https://github.com/ArctosDB/arctos/files/9659550/temp_maybe_wet.csv.zip)

**Comment by sharpphyl** [comment]
The list has a number of marine geographic areas that we are currently using.  To help us better understand which sources best fit our specimens, could you show screenshots for the Sulu Seas (iho_world-seas) and SOUTH CHINA AND EASTERN ARCHIPELAGIC SEAS|SULU SEA (seavos.areas).  Thanks.

**Comment by dustymc** [comment]
>Sulu Seas (iho_world-seas)

<img width="1236" alt="Screen Shot 2022-10-04 at 1 35 28 PM" src="https://user-images.githubusercontent.com/5720791/193921856-a7d7b3e8-6429-4b9b-9370-f7d35fca59c7.png">

> SOUTH CHINA AND EASTERN ARCHIPELAGIC SEAS|SULU SEA (seavos.areas)

<img width="951" alt="Screen Shot 2022-10-04 at 1 36 36 PM" src="https://user-images.githubusercontent.com/5720791/193922062-9b6635dd-24d1-4869-853d-ec25b3303b5c.png">

I think https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=4986 is using seavox_areas

**Comment by sharpphyl** [comment]
So, they appear to be identical.  And are seavox_areas (and the others on your list) already in higher geography and we just have to select them?   You can tell, we don't really understand how to use this data effectively.

**Comment by dustymc** [comment]
You'd request geography creation in the normal manner, I'd use these sources to build the initial CSV. Some of them are used, but not in accordance with https://github.com/ArctosDB/arctos/issues/5076 (which I'm going to assume has enthusiastic support unless told otherwise) - I think that just means we'll (eventually) drop "North Pacific Ocean" from https://arctos.database.museum/editGeog.cfm?geog_auth_rec_id=4986. That still seems entirely correct to me, it just adds confusion, there's not some other Sulu Sea in some other ocean (and we have the geography if I'm wrong about there, there's nothing ambiguous about the place).

**Comment by sharpphyl** [comment]
Can we make requests from this list within this GitHub issue rather than opening a new one each time?  There is no footprint for Geography [10001035](https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10001035).  Can you add this eez to that geography?

eez_land_union	Republic of Mauritius|Republic of Mauritius|Republic of Mauritius|Union EEZ and country

**Comment by Jegelewicz** [comment]
Alaska

But that doesn't really solve @sharpphyl problem? She wants to say this thing was found in the water, but that EEZ includes land?

**Comment by dustymc** [comment]
> She wants to say this thing was found in the water

If that's the case then the EEZ-combos perhaps aren't best - something like https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=1148 might be more appropriate.

I'll always prefer "might be more appropriate" over "just wrong," and things in the water close to AK and attributed to the EEZ won't be "just wrong" even if they do include a few hundred thousand square miles of extraneous dirt.

(Things on/near the beach - maybe water, maybe dirt, who knows - will also land inside the shape, and I think these are most of the actual problem.)

FWIW I had the suggester-thing running against the cache for a while (failed experiment), and a huge number of the 'no appropriate geography' localities land in one of the EEZ-union shapes. I can't say I'm entirely thrilled with the whole sorta-weird situation, but it does seem to very nicely solve a big chunk of a huge problem. It's probably not what I'd suggest if we had unlimited resources, but until then I don't see a better approach.

**Comment by sharpphyl** [comment]
> but that EEZ includes land?

The spatial visual does include land, but the EEZ definition would only be the area offshore.  I'm ok with that if others are - for Alaska, Guam, Mauritius, etc.  

> a huge number of the 'no appropriate geography' localities land in one of the EEZ-union shapes.

Ultimately, I think that's the heart of this discussion.  How can we create spatial geography that is helpful - confirms that our coordinates are within the designated boundaries - rather than creating a ton of problem records.  As long as what we do works for the aggregators, it's a plus for our collection.

**Comment by sharpphyl** [comment]
BTW, we've learned that Geolocate is working on a system for donuts around mountain tops (for elevation) and around islands.  That may help with EEZ's and other island-related spatial geography.  Is anyone in touch with them or know more about this?

**Comment by dustymc** [comment]
>spatial visual does include land, but the EEZ definition would only be the area offshore.

I think maybe there's still some major miscommunication. The EEZ+country data provides a single shape which is the country plus the EEZ. The spatial visual is just a visualization of the shape, which is definitive. The summit of Denali is in "Alaska Exclusive Economic Zone."

If geolocate is doing something cool that can be imported into postgis and they're willing to share then it could be discussed as another spatial source.

**Comment by dustymc** [comment]
Merge-->https://github.com/ArctosDB/arctos/issues/5138
