### ISSUE TITLE
Antigua and Barbuda

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5108]
### First Step: Explain what geography needs created.

Administrative divisions for [Antigua and Barbuda](https://en.wikipedia.org/wiki/Antigua_and_Barbuda) in order to upload CSULB Bird records.

There are two types of [administrative units](https://en.wikipedia.org/wiki/Antigua_and_Barbuda#Administrative_divisions), but they can all be treated as State level units I think. One is already in Arctos: [Saint George Parish](https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10003803)

Needed:
Parishes
        [Saint John](https://en.wikipedia.org/wiki/Saint_John_Parish,_Antigua_and_Barbuda)
        [Saint Mary](https://en.wikipedia.org/wiki/Saint_Mary_Parish,_Antigua_and_Barbuda)
        [Saint Paul](https://en.wikipedia.org/wiki/Saint_Paul_Parish,_Antigua_and_Barbuda)
        [Saint Peter](https://en.wikipedia.org/wiki/Saint_Peter_Parish,_Antigua_and_Barbuda)
        [Saint Philip](https://en.wikipedia.org/wiki/Saint_Philip_Parish,_Antigua_and_Barbuda)
    Dependencies
        [Barbuda](https://en.wikipedia.org/wiki/Barbuda)
        [Redonda](https://en.wikipedia.org/wiki/Redonda)

We will respond with a CSV template, or request more information.

**Comment by dustymc** [comment]
Here's CSV - it just needs source filled in.

[temp_geog_aab.csv](https://github.com/ArctosDB/arctos/files/9668295/temp_geog_aab.csv)

I'll just create all of those, then merge the existing into them - that'll be easier than trying to save anything.

**Comment by Jegelewicz** [comment]
Added sources
[temp_geog_aab.csv](https://github.com/ArctosDB/arctos/files/9668520/temp_geog_aab.csv)

**Comment by dustymc** [comment]
done
