### ISSUE TITLE
Get link to Detail page for different collections?

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#5110]
@dustymc 
I'd like to imbed the link to the UWYMV details pages for our different collections, but I can't seem to grab it from the portal page. 
Is there a way to get a stable link to these pages for each collection?
![Untitled_1](https://user-images.githubusercontent.com/18562884/192872699-35b7fbaa-e7b8-4d7c-a92e-97a5afc3bc28.png)

I've tried to copy the link here:
![Untitled_2](https://user-images.githubusercontent.com/18562884/192872751-e872bd41-adfa-4262-abbe-8694a92cea23.png)

but it won't let me copy the link, and when I copy the address at the top of the Details page it just takes me straight back to the general Arctos portals page.

I'm probably just missing something basic here, but I'd really like to use our detail pages rather then the ones on GBIF for this introduction to the collections. We have so much more data!

**Comment by dustymc** [comment]
<img width="480" alt="Screen Shot 2022-09-28 at 12 39 14 PM" src="https://user-images.githubusercontent.com/5720791/192873512-0f4a4855-82fc-46fb-88ae-115735eea0e5.png">

**Comment by ewommack** [comment]
Thanks Dusty! I thought that led to our search page. I got confused on the name: Collection ID.

**Comment by dustymc** [comment]
It's meant to be just that, and using it as such would make things like https://github.com/ArctosDB/internal/issues/201 a whole lot less mystical, but there was some problem that I don't understand so we're sending gbif some sort of useless thing instead....

It's not a link in the hopes that it'll be more recognizable as text, but maybe that's not working. It is an identifier, like all Arctos identifiers it's also resolvable, ideas for somehow communicating that more effectively greatly appreciated.

**Comment by ewommack** [comment]
When I see ID and think Identification. Bird ID: Robin - _Turdus migratorius_
Does ID mean something else for web-based info?

Maybe it would clearer as 
Link to Collection Detail Page:.....
or 
Collection Detail Address:....
or 
Collection ID Address:....

?

@ebraker @lin-fred, what do you think - I may just be confusing things more.

**Comment by dustymc** [comment]
Yea, English is dumb...

"ID"="identifier" - https://arctos.database.museum/collection/UWYMV:Bird is an instance of a [URI](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier).

I don't mind spelling Identifier out there, but I'm not sure if overall that would lead to more or less confusion.

**Comment by Jegelewicz** [comment]
It's kinda the collection's descriptive metadata that is found at that URI. Maybe the label for this should be

Collection Metadata

or

Arctos Homepage

**Comment by dustymc** [comment]
The URL is completely secondary, the purpose was to create an identifier and I don't want to water that down in any way, even if whatever mess exists is keeping us from using it at the moment.

**Comment by Jegelewicz** [comment]
> so we're sending gbif some sort of useless thing instead

What are we sending that's useless? We should figure out where we want this identifier to go so that it is working for us. As far as I can tell, the place this would go at GBIF is in the other identifiers section, but right now that just has our VertNet IPT endpoint.

![image](https://user-images.githubusercontent.com/5725767/192911418-56918849-a47f-494b-a482-8cebbf94ee43.png)

And most of our collections' metadata at GBIF is currently completely different from GrSciColl, otherwise, I would say we should add the Arctos URIs there.

![image](https://user-images.githubusercontent.com/5725767/192911673-775ede22-35f9-4548-9ef5-0ea19c0ef119.png)

**Comment by ewommack** [comment]
> the purpose was to create an identifier

I think I understand @dustymc - this is to act like a permanent way to identify each collection. So you can use that address and always get to the full information for that specific collection in Arctos. Do I have that right? Overlapping with our long-running discussion on identifiers and permanent identifiers in museums?

**Comment by dustymc** [comment]
>o you can use that address and always get to the full information for that specific collection in Arctos

Yes but no.
 
First and foremost it's an identifier - it's a string which is very unlikely to exist for some other purpose (unlike say "12") and which is associated with your collection. It doesn't necessarily need to DO anything at all to serve this purpose; I pass it on to GBIF, they keep it attached to your stuff, I can use it to find your stuff. (And that - shared unique identifiers - would be a HUGE improvement at the moment.) UUIDs for example are at least as good as ``https://arctos.database.museum/collection/UWYMV:Bird`` at this level.

DOING STUFF is a nice bonus - this identifier (very much unlike a UUID) will send all kinds of devices to somewhere they can get more information about your collection. Neat, useful for all kinds of things, but secondary to being an identifier.

Persistence is yet another step; ideally that identifier will outlive the collection it represents but that gets complicated (and might even not be terribly important for this).

**Comment by ewommack** [comment]
So permanent collection information address?

**Comment by ewommack** [comment]
I got my problem solved, but do we need another issue for the clarification of the use of "ID" for the collection portal weblink?
