### ISSUE TITLE
Counties of Kenya

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5111]
### First Step: Explain what geography needs created.

It looks like Kenya has undergone some revision. Some may be in Arctos, some not. 

[Counties of Kenya](https://en.wikipedia.org/wiki/Counties_of_Kenya) needed for CSULB data migration include [Machakos](https://en.wikipedia.org/wiki/Machakos_County), [Makueni](https://en.wikipedia.org/wiki/Makueni_County) and [Nyeri](https://en.wikipedia.org/wiki/Nyeri_County)

We will respond with a CSV template, or request more information.

**Comment by dustymc** [comment]
[temp_geog_kenya.csv.zip](https://github.com/ArctosDB/arctos/files/9668884/temp_geog_kenya.csv.zip)

**Comment by dustymc** [comment]
Many of these exist, just misplaced and malformed - I'll provide fresh CSV after I clean up.

**Comment by dustymc** [comment]
[temp_geog_kenya(1).csv](https://github.com/ArctosDB/arctos/files/9669329/temp_geog_kenya.1.csv)

**Comment by Jegelewicz** [comment]
I added those sources, but also sources for ALL counties, so you either need to remove the ones I added or find them in GADM?
[Uploading temp_geog_kenya.1.csv…]()

**Comment by dustymc** [comment]
You're too quick on the draw, the file didn't upload.

**Comment by Jegelewicz** [comment]
[temp_geog_kenya.1.csv](https://github.com/ArctosDB/arctos/files/9678675/temp_geog_kenya.1.csv)

**Comment by dustymc** [comment]
> find them in GADM

That's never going to happen - I pull straight from GADM (or whatever I'm using), then attempt to remove what we already have. (I seem to have missed two in this case.)

>ALL counties

Yes, the idea has been to clean up countries when possible, even if [reality](https://github.com/ArctosDB/arctos/issues/5084) sometimes gets in the way.

Another instance of [stopping at state ](https://github.com/ArctosDB/arctos/issues/5109)(what these are, whatever they're called) being practical....
