### ISSUE TITLE
error feedback

### ISSUE THREAD

**Issue by jebrad** [ArctosDB/arctos#5112]
@Jegelewicz Maybe you can help me delete these, or perhaps it's a Dusty resolution needed.

Using bulkloader > Browse and Edit to try to delete everything (367 records) in accession 2019-101, so I can upload those same records that have been corrected in Excel. 

First step after selecting DELETE all selected records seems to go well, it takes me here:
![image](https://user-images.githubusercontent.com/62565118/192892055-06e41bbe-4c75-4eb2-bf81-802261124129.png)

But after I "click here" it returns a long page of errors, starting with this:

ERROR_ID | 9F15D9DA-1943-4D17-95F158BF1A188E33
-- | --
ERROR_TYPE | SQL
ERROR_MESSAGE | ERROR: new row for relation "bulkloader" violates check constraint "ck_part_remark_1_noprt"
ERROR_DETAIL |  
ERROR_SQL | update bulkloader set status='DELETE' where collection_object_id>1000 		 		 			and accn in ('[UWBM:Mamm]2019-101')

[Trying to attached a PDF, and also a zipped copy of that PDF, showing the entire error page.... but dragging and dropping isn't working and I am not sure you need to see it anyway].

**Comment by dustymc** [comment]
I cleaned up the data that was blocking and ran your SQL

UPDATE 367

**Comment by jebrad** [comment]
Ok thanks - I see their status is all set to DELETE right now, so I assume they will disappear by tomorrow morning. If so, I will close this.   If not, I will click "Delete all selected records" again, and then either close this or comment again depending on what happens.

**Comment by jebrad** [comment]
Thanks Dusty I see they are all gone.
