### ISSUE TITLE
error feedback - please delete all bulkloaded records for MSB:Herp that were loaded by IRtorre5

### ISSUE THREAD

**Issue by jtgiermakowski** [ArctosDB/arctos#5114]
There's some issue with characters in the loaded data, please delete all bulkloaded records that were loaded by irtorre5, there are over 12,000 of them

Thanks!

<html><body>

ERROR_ID | FB8D552F-5A71-400C-B23B453F483E9CA1
-- | --
ERROR_TYPE | SQL
ERROR_MESSAGE | ERROR: new row for relation "bulkloader" violates check constraint "ck_collector_agent_2_noprt"
ERROR_DETAIL |  
ERROR_SQL | update bulkloader set status='DELETE' where collection_object_id>1000 		 			and enteredby in ('IRtorre5')

</body>
</html>

**Comment by dustymc** [comment]
Updated - they should delete within about an hour.

**Comment by jtgiermakowski** [comment]
Awesome, thanks!
