### ISSUE TITLE
[CONTACT: Blocked Network]

### ISSUE THREAD

**Issue by btlotfi77** [ArctosDB/arctos#5115]
restricted IP: 41.97.100.183

hi sir
I received this message today

could youexplain to me what's the problem
thank you

Your IP (41.97.100.183) or organization has been blocked. You may wish to check your computer for malicious software and alert your IP or organization. Further intrusion attempts may result in more restrictive blocks. Access from this network has been restricted. You may open an[ Issue on our GitHub ](https://github.com/ArctosDB/arctos/issues/new?labels=contact&template=contact-arctos.md&title=%5BCONTACT:+Blocked+Network%5D&body=restricted+IP:+41.97.100.183)to request access.

We cannot consider requests which do not include your IP address, "41.97.100.183"

**Comment by dustymc** [comment]
released
