### ISSUE TITLE
error viewing projects

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#5117]
@dustymc Projects should be viewable by the public without being logged in - correct? I just tried and got this:

![image](https://user-images.githubusercontent.com/967275/193083610-2d0d284f-6bab-4be7-a7fa-e072d6375b81.png)

**Comment by ccicero** [comment]
Actually, it's also giving an error when logged in.

![image](https://user-images.githubusercontent.com/967275/193084203-5d355c9f-51a4-4a02-96d2-0065a20bb454.png)

**Comment by dustymc** [comment]
I pulled to test, tried a search, it works, so I packaged up a release. I don't have time to review code right now.

>I have a fix in, but I do not have the ability to pull anything.

You've got to find a way to test what you change.

**Comment by Jegelewicz** [comment]
> You've got to find a way to test what you change.

Agree - how do you do this?

**Comment by dustymc** [comment]
SSH in to the test box - I thought you got an account for this purpose a couple years back?

That would also let you restart services and other scary stuff, which might be handy if I don't make it back from lunch.
