### ISSUE TITLE
Feature Request - simplify print menu

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5119]
**Is your feature request related to a problem? Please describe.**

There are lots of print options in various places, most of them don't work, none will as we transition to HTML reports.

Example from catalog record search results:

<img width="327" alt="Screen Shot 2022-09-30 at 12 51 32 PM" src="https://user-images.githubusercontent.com/5720791/193346184-c1efb893-5ff2-46a5-b195-bd0e41298576.png">

**Describe what you're trying to accomplish** 

clean

**Describe the solution you'd like**

remove all but 'print any'

**Describe alternatives you've considered**

clutter

**Additional context**

-

**Priority**

Low - this can be discussed if necessary, otherwise I'll proceed around 2022-10-14.

**Comment by mkoo** [comment]
thank goodness for this cleanup!
