### ISSUE TITLE
Code Table Request - New locality attribute georeference source

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5120]
**Goal**
We want more information about who georeferenced and when.

**Context**
https://github.com/ArctosDB/arctos/issues/4866#issuecomment-1265817500

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlocality_attribute_type

**Proposed Value**
georeference source

**Proposed Definition**
A description that is specific enough to allow anyone in the future to use the same resources to validate the coordinates, or to georeference the same locality. <a href="https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlocality_attribute_type" class="external">Documentation</a> Determiner should be the Arctos Agent who completed the georeference and determined date should be the date the georeference was completed.

**Attribute data type**
free-text

**Available for Public View**
Yes

**Priority**
[  Please choose a priority-label to the right.  ]

**Comment by dustymc** [comment]
This will be created for https://github.com/ArctosDB/arctos/issues/4916, but will still need reconciled with the locality column of the same name. I think this is another place where we want to let the catalog record bulkloader pretend that the attribute is a simple 'field'?

All locality-related loaders will likely need updated in some way.

**Comment by dustymc** [comment]
Going back to needs discussion - this can be resolved in https://github.com/ArctosDB/arctos/issues/5193

**Comment by dustymc** [comment]
Unless there are timely and defensible suggestions, I'm going active (will happen as part of https://github.com/ArctosDB/arctos/issues/5193) opposite of what I suggested above: I don't think (most of) these data add any clarity to "normal" localities, and there are only two useful views:

1. Do nothing; 'Google Earth 18 Sept 2007' adds no value whatsoever, it's just a denormalizer (ensures that locality will never be merged with 'Google Earth 199 June 2007'), leaving it out adds value and loses nothing in most situations, or
2. Add a full locality attribute, the structure of which (determiner, mostly, perhaps) is necessary to take the above to a useful place from which one might better understand a locality.

The bulkloader/data entry screen already includes locality attributes.

Therefore I will

* move existing locality.georeference_source to https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlocality_attribute_type#georeference_source
* remove the column from any table or form in which it may exist, including the bulkloader/data entry UI

Here's current data in case anyone wants to use it to refute any of the above.

[temp_u_loc_grs.csv.zip](https://github.com/ArctosDB/arctos/files/9923275/temp_u_loc_grs.csv.zip)

**Comment by Jegelewicz** [comment]
Crap - now I have to redo the 12K records I am trying to bulkload today? (Also @ehalverson26 has another 10K).....

**Comment by dustymc** [comment]
>today

I'm not that fast! I'm gonna try to cram https://github.com/ArctosDB/arctos/issues/5193 through (so I can implement some ID stuff that's looking obvious at the moment without rewriting the same forms 19 times), but I imagine that's weeks away at best. Going forward, using the attribute plus the value 'see accompanying locality attribute' (which I WILL NOT migrate - I made it, I can un-make it...) should avoid any potential crossover-gotchas.

**Comment by Jegelewicz** [comment]
OK - but maybe we should start thinking about warnings when a change will affect those working on data migration/entry? We have a lot of people working on those things and one day something works, then the next it doesn't which can be mind-blowing. Could we give people a one week notice so that everyone can either try to finish up what they have or reformat for the new process?

**Comment by dustymc** [comment]
I don't think this level of change ever happens without lots of warning, I don't think see how this one is/will be any different, but maybe that isn't adequately communicated?? (I'm never surprised...) As above this seems like it's at least days from me starting actual development, and then probably at least a couple weeks of actual development. This might be a good candidate to try whatever communication you think might be more effective.

**Comment by Jegelewicz** [comment]
> maybe that isn't adequately communicated??

I don't think it is. Those who are on GitHub a lot may be aware, but it is very easy to miss these things, especially when your head is down cleaning data to bring into Arctos.

> This might be a good candidate to try whatever communication you think might be more effective.

OK - let me get something together

**Comment by Jegelewicz** [comment]
It seems like these things should go here - https://arctosdb.org/category/alerts/ but for the life of me I cannot figure out where that is in Wordpress. @mkoo
