### ISSUE TITLE
Arctos Down - 

### ISSUE THREAD

**Issue by cpurcell2** [ArctosDB/arctos#5123]
Please complete to the best of your ability.

## Unplanned Outage
 - 10/04/22, 11:00am MST outage discovered:
 - Describe the outage: unresponsive

## Planned Outage
 - Date and time outage will begin:
 - Date and time outage is expected to end:
 - Reason for outage:
 - Expected behavior during and after the outage:

## Communication before/during outage
- [ ] Pin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG  
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by dustymc** [comment]
Looks fine from here....

**Comment by mkoo** [comment]
I'm logged in without issue....

Can you explain exactly your system setup and if there are error messages?
Can you refresh the browser? Clear cache and log in?

**Comment by cpurcell2** [comment]
It's up again, don't know what happened! Thanks!
