### ISSUE TITLE
Code Table Request - New Biostratigraphic Zone

### ISSUE THREAD

**Issue by cpurcell2** [ArctosDB/arctos#5124]
**How to Use This Form**
This is a template with examples and guidance on how to best communicate with the Arctos Working Group. Please delete this section along with anything in square brackets ```[ ] ``` below before submitting. 

[ **Instructions for reference:** ]
[ Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html ]

[ Code Table Documentation is https://handbook.arctosdb.org/how_to/How-to-Use-Code-Tables.html ]

[[Video Tutorial - Submit a Code Table Request](https://youtu.be/t2jHbsRA3lk)]

**Goal**
Catalog fossils

**Context**
We have fossils from the Discoscaphites iris zone of the Late Maastrichtian and need it in Arctos.

**Table**
Biostratigraphic zone

**Proposed Value**
Discoscaphites iris zone

**Proposed Definition**
(http://treatment.plazi.org/id/B01187C67851FB09FCA9F9CC2939D917)

**Collection type**
[ If the code table includes a "Collection" column. Ex: Mamm, Herp, ES ]

**Attribute data type**
[ "Attributes" may apply to catalog records, parts, localities, and collecting events. You must specify a datatype (free-text, categorical, or number+units) if this request involves attributes. ]

**Attribute value**
[ For categorical attributes, code table controlling value  ]

**Attribute units**
[  For number+units attributes, code table controlling units  ]

**Available for Public View**
[  **Yes | No** to indicate whether the proposed value will be available for public view or available only for logged in operators.  ]

**Other ID BaseURL**
[  For OtherIDs, provide the following *or* explain why the unresolvable ID type is necessary:
1. "Base URL" with which to prepend entered values, and
2. A functional example URL, which should consist of the base URL provided in (1) plus a relevant value.  ]

**ID_References**
[  If the request involves https://arctos.database.museum/info/ctDocumentation.cfm?table=ctid_references, the changes must be coordinated with the Database Admin team for notifications to function.  ]

**Priority**
[  Please choose a priority-label to the right.  ]

**Comment by Jegelewicz** [comment]
@Nicole-Ridgwell-NMMNHS sound OK?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> sound OK?

Yep

**Comment by Jegelewicz** [comment]
added
