### ISSUE TITLE
Cannot edit accession

### ISSUE THREAD

**Issue by cpurcell2** [ArctosDB/arctos#5125]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Added a project to the accession and it wont save.

**To Reproduce**
1. Go to Accession: https://arctos.database.museum/accn.cfm?action=edit&transaction_id=21134366
2. Click on Add Project
3. Save

**Expected behavior**
I expect the project to get added.

**Screenshots**

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**
<html>
<body>
<div style="border: 2px solid green; padding: 1em; margin: 1em; text-align: center;">Please<span> </span><a target="_blank" class="external" href="https://github.com/ArctosDB/arctos/issues/new?assignees=&amp;labels=contact&amp;template=contact-arctos.md&amp;title=error%20feedback" style="text-decoration: underline solid blue; color: blue;">contact us</a><span> </span>if you need assistance in resolving this error. Include the ERROR_ID (below)<span> </span><strong>as text</strong><span> </span>and enough information for us to re-create the problem.</div>

ERROR_ID | 5B350449-CFE8-4341-BAE6F0E5E11B4BA4
-- | --
ERROR_TYPE | SQL
ERROR_MESSAGE | ERROR: permission denied for table project_trans
ERROR_DETAIL |  
ERROR_SQL | INSERT INTO project_trans ( project_id, transaction_id ) VALUES ( 10003978, 21134366 )

</td></tr><tr><td class="luceeH0" style="border: 1px solid rgb(51, 51, 153); vertical-align: top; padding: 2px; empty-cells: show; color: rgb(51, 51, 153); background-color: rgb(153, 153, 255);">where</td><td class="luceeN0" style="border: 1px solid rgb(51, 51, 153); vertical-align: top; padding: 2px; empty-cells: show; color: rgb(51, 51, 153); background-color: rgb(204, 204, 255);"><table style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif; font-size: 11px; empty-cells: show; color: rgb(0, 0, 0); border-collapse: collapse;"><tbody><tr><td class="luceeH1" style="border: 1px solid rgb(153, 0, 0); vertical-align: top; padding: 2px; empty-cells: show; color: rgb(153, 0, 0); background-color: rgb(255, 102, 0); font-family: Verdana, Geneva, Arial, Helvetica, sans-serif; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">string</td>
</body>
</html>

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.
Please [contact us](https://github.com/ArctosDB/arctos/issues/new?assignees=&labels=contact&template=contact-arctos.md&title=error%20feedback) if you need assistance in resolving this error. Include the ERROR_ID (below) as text and enough information for us to re-create the problem.
ERROR_ID	5B350449-CFE8-4341-BAE6F0E5E11B4BA4
ERROR_TYPE	SQL
ERROR_MESSAGE	ERROR: permission denied for table project_trans
ERROR_DETAIL	
ERROR_SQL	INSERT INTO project_trans ( project_id, transaction_id ) VALUES ( 10003978, 21134366 )
request dump:

request
node_name	
string	arctos-2021
rdurl	
string	/accn.cfm
uui	
string	
uuid	
string	5B350449-CFE8-4341-BAE6F0E5E11B4BA4
exception dump:

Catch
Entries: 15
additional	
Struct (ordered)
SQL	
string	INSERT INTO project_trans ( project_id, transaction_id ) VALUES ( 10003978, 21134366 )
DatabaseName	
string	PostgreSQL
DatabaseVersion	
string	12.2
DriverName	
string	PostgreSQL JDBC Driver
DriverVersion	
string	42.2.20
Datasource	
string	user_login
DataSource	
string	user_login
Detail	
string	
ErrorCode	
string	0
Extended_Info	
string	
ExtendedInfo	
string	
Message	
string	ERROR: permission denied for table project_trans
NativeErrorCode	
number	0
queryError	
string	INSERT INTO project_trans ( project_id, transaction_id ) VALUES ( 10003978, 21134366 )
Sql	
string	INSERT INTO project_trans ( project_id, transaction_id ) VALUES ( 10003978, 21134366 )
SQLState	
string	42501
StackTrace	
string	lucee.runtime.exp.DatabaseException: ERROR: permission denied for table project_trans at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553) at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285) at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323) at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481) at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401) at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164) at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:153) at lucee.runtime.type.util.QueryUtil.execute(QueryUtil.java:328) at lucee.runtime.type.QueryImpl.execute(QueryImpl.java:296) at lucee.runtime.type.QueryImpl.<init>(QueryImpl.java:235) at lucee.runtime.tag.Query.executeDatasoure(Query.java:1134) at lucee.runtime.tag.Query._doEndTag(Query.java:699) at lucee.runtime.tag.Query.doEndTag(Query.java:565) at accn_cfm$cf$hl.call(/accn.cfm:801) at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:1015) at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:938) at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:219) at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:44) at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2482) at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2468) at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2439) at lucee.runtime.engine.Request.exe(Request.java:45) at lucee.runtime.engine.CFMLEngineImpl._service(CFMLEngineImpl.java:1198) at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:1144) at lucee.loader.engine.CFMLEngineWrapper.serviceCFML(CFMLEngineWrapper.java:97) at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:51) at javax.servlet.http.HttpServlet.service(HttpServlet.java:590) at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74) at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129) at org.cfmlprojects.regexpathinfofilter.RegexPathInfoFilter.doFilter(RegexPathInfoFilter.java:47) at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68) at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68) at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117) at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at runwar.Server$1.handleRequest(Server.java:510) at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52) at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:280) at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79) at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134) at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131) at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:260) at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79) at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100) at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387) at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852) at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35) at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019) at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558) at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449) at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280) at java.lang.Thread.run(Thread.java:750)
TagContext	
Array
1	
Struct
codePrintHTML	
string	799: &lt;cfqueryparam value=&quot;#transaction_id#&quot; CFSQLType=&quot;cf_sql_int&quot;&gt;<br> 800: )<br> <b>801: &lt;/cfquery&gt;</b><br> 802: &lt;/cfif&gt;<br> 803: &lt;cfquery name=&quot;updateAccn&quot; datasource=&quot;user_login&quot; username=&quot;#session.dbuser#&quot; password=&quot;#decrypt(session.epw,session.sessionKey,'AES/CBC/PKCS5Padding','hex')#&quot;&gt;<br>
codePrintPlain	
string	799: <cfqueryparam value="#transaction_id#" CFSQLType="cf_sql_int"> 800: ) 801: </cfquery> 802: </cfif> 803: <cfquery name="updateAccn" datasource="user_login" username="#session.dbuser#" password="#decrypt(session.epw,session.sessionKey,'AES/CBC/PKCS5Padding','hex')#">
column	
number	0
id	
string	??
line	
number	801
Raw_Trace	
string	accn_cfm$cf$hl.call(/accn.cfm:801)
template	
string	/usr/local/webroot/accn.cfm
type	
string	cfml
type	
string	database
where	
string

**Comment by Jegelewicz** [comment]
@dustymc Ceara created this accession - why can't she edit it?

**Comment by dustymc** [comment]
The error is not about accessions, it's a lack of project/publication access.

> ERROR_SQL INSERT INTO project_trans ( project_id, transaction_id ) VALUES ( 10003978, 21134366 )

**Comment by Jegelewicz** [comment]
But she also created the project!

**Comment by Jegelewicz** [comment]
https://arctos.database.museum/project/10003978
