### ISSUE TITLE
geography: island - policy needed

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5126]
First and foremost, I'd like some sort of policy regarding island in geography. If we can just shuffle them off to specific locality by policy then there's not much technical problem and I can move on. If we need to keep them, or some of them, then I think that has to be spelled out before we can move.

FWIW I *sort of* think that at least big isolated islands have a place in geography - https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10003566 (Pitcairn) is way out in the middle of nowhere, no other geography includes it at any useful scale. It's currently entered as Pacific Ocean (it's not, islands are the part which **is not** ocean!), United Kingdom (perhaps correct, but not in any way spatially useful) - I don't think what we've done is useful, quite the opposite, but I can't quite get rid of the idea that some islands are "geography worthy" - nor can I quantify that in any way which might lead to consistent or usable data, I'm completely open to the idea that I'm just wrong and islands are not geography.

The three georeferenced records which uses Pitcairn all map to Ducie (a member of the Pitcairns, but not Pitcairn itself), about 350KM away. Maybe that's just overwhelming evidence that something like a strict "if it ain't GADM it ain't geography" approach is the only usable view of the world. (Or maybe that's evidence that humans just can't be trusted and some flavor of https://github.com/ArctosDB/arctos/issues/4785 is the only path to defensible data, I am completely open to radical ideas.)

I hoped there'd be some direction in the data, but I don't think I've found it. There are 1996 geography records with island in Arctos, pulled out to https://docs.google.com/spreadsheets/d/1hNcVASLYGWrTTMwQrOOB2ZmFt2OjWrLgFkctfnDiuMY/edit?usp=sharing

538 of them are associated with a county, they look like low-hanging fruit, suggest they be merged with the county record (ala https://github.com/ArctosDB/arctos/issues/5076). 

Of those without county, 137 have one match with the island data I have. That doesn't necessarily means it's a good match - Europe, Netherlands, Noord-Holland Province, Texel Island==South America:Texel is clearly(ish, probably) wrong, for example - but hopefully most of those would be somewhat straightforward to deal with, if we had some policy under which to do so.

140 have no match at all - I probably-maybe just don't have spatial data for them, they'd not qualify as geography under even very liberal approaches to https://github.com/ArctosDB/arctos/issues/5076 (none of my sources seem to include them).

461 have less than 10 matches - I might have an appropriate match, and I might be able to find it without too much struggle - although I suspect this would involve mapping most everything, and even then some would not match.

76 have more than 10 matches, those would almost certainly require lots of digging.

I don't think I have any real idea regarding how to proceed with this, and it's affecting things like [new collection migration](https://docs.google.com/spreadsheets/d/1hNcVASLYGWrTTMwQrOOB2ZmFt2OjWrLgFkctfnDiuMY/edit?usp=sharing) so I'm calling it critical. (If forced, I suppose I'd go with the 'GADM or bust' thing at the moment, not because I think it's "correct" but because it's the _only_ clear path I see to anywhere consistent and somewhat defensible.) 

Geography Committee, help?!

**Comment by Jegelewicz** [comment]
Would it be useful to just move island to a locality attribute? (I know this has been discussed, but why is it not an option?) We have a code table and we can add any island anyone wants to keep track of to it. It keeps islands a bit more standardized but out of geography.

**Comment by dustymc** [comment]
Define "useful."

That would simplify some things, but make Pitcairn (above) and https://github.com/ArctosDB/arctos/issues/5106 and such a bit less formal. I don't know if ya'll see that as a good trade or not; I can't get anyone to tell me much of anything about geography....

**Comment by Jegelewicz** [comment]
> make Pitcairn (above) and https://github.com/ArctosDB/arctos/issues/5106 and such a bit less formal. I don't know if ya'll see that as a good trade or not

I'm OK with it - what does @sharpphyl think? Who else has a bunch of stuff on islands?

**Comment by Jegelewicz** [comment]
I guess I'm wondering what the difference is - if people care about Pitcairn, they can find it if it's in a locality attribute. If it's tucked away in spec loc, it's harder and easier for it to be in there as:

Pitcarn
Pitcirn
pitcairn

etc.

As far as I can tell, the ONLY advantage of including it in geography right now is that it is spelled exactly ONE way.

**Comment by dustymc** [comment]
The single most-used island is https://github.com/ArctosDB/arctos/issues/5106, those users are listed there. I can dig deeper if necessary but I think it's safe to say that's a good representation.

>ONLY advantage of including it in geography

...  is access to "formal spatial" data. If spelling is the concern then a locality attribute (with a CT, which is not a problem) should be functionally equivalent.

**Comment by sharpphyl** [comment]
I'd better jump in since a many of our records are from islands.  Are you just concerned about small, distant islands?  I don't see any problem with countries such as Iceland or subdivisions such as Kauai, Maui, Puerto Rico etc.  

I'm not sure exactly what you're proposing or which islands on your spreadsheet you want to modify or eliminate or make features. Can you highlight your concerns or tell us who's using the islands so we can focus on them.

Pitcairn is a good example of the mishmash of administrative designations (United Kingdom) and physical areas (Pacific Ocean), so I see the problem but I don't see why making it a feature does anything for us. 

If we want to just do administrative areas (from https://www.government.pn.) the Pitcairn Islands group is a British Overseas Territory. It comprises the islands of Pitcairn, Henderson, Ducie and Oeno.  

GADM doesn't list British Overseas Territory (or Pitcairn), but we could create it.  https://en.wikipedia.org/wiki/British_Overseas_Territories

Can we have a committee meeting to discuss this?

**Comment by dustymc** [comment]
Merge-->https://github.com/ArctosDB/arctos/issues/5138
