### ISSUE TITLE
project creation permissions

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5128]
But she also created the project!

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/arctos/issues/5125#issuecomment-1267627630_

**Comment by Jegelewicz** [comment]
This is another place where projects and publications maybe should not be linked?

**Comment by dustymc** [comment]
Somehow manage_transactions has insert on project and some other crazy stuff (https://arctos.database.museum/Admin/user_roles.cfm?action=defineRole&role_name=manage_transactions) 

I think its safe to just remove non-transaction roles but maybe whoever asked for this - someone must have! - will show up and refresh my memory....

**Comment by Jegelewicz** [comment]
Part of the issue may be that there appear to be no "project" permissions, just publications and transactions. What are project permissions supposed be tied to?
