### ISSUE TITLE
Sign in not working

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#5129]
Our intern is trying to sign in on Arctos but it keeps telling him his password is incorrect. He's tried Chrome, Firefox, and Explorer. Last week, he was able to sign in to Chrome, but not Firefox (he's working on georeferencing). Today, he's unable to log in to any browser.

I looked under "Manage Users" and it did not say his account was locked for too many sign-in attempts. We're attempting to reset his password now to see if that helps, but the reset link is not going through.

username: tricco

**Comment by dustymc** [comment]
See also https://github.com/ArctosDB/arctos/issues/4767

I sent you email with the latest notification.

I think this is usually caused by some browser plugin password manager.

**Comment by wellerjes** [comment]
He was able to login. Thanks!

**Comment by babogan** [comment]
I am having this problem as well (BABOGAN). It has been occurring on multiple devices since two weeks ago.

**Comment by Jegelewicz** [comment]
Sent email with password reset.

**Comment by Jegelewicz** [comment]
This is the error message I receive:

Authentication failed. Additional Information: Access restricted.

**Comment by Jegelewicz** [comment]
I just unlocked the account and reset the password.
