### ISSUE TITLE
Need Help with Arctos Error ERROR: new row for relation "bulkloader" violates check constraint "ck_coll_event_remarks_noprt"

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5130]
# Error Text
ERROR: new row for relation "bulkloader" violates check constraint "ck_coll_event_remarks_noprt"

# Where it happened
After check and load in bulkloader

# Steps to get there
Go to https://arctos.database.museum/Bulkloader/BulkloadSpecimens.cfm?action=checkStaged

# Problem
I have NOTHING in coll_event_remarks, but also checked specimen_event_remark and found no offensive characters

[Database_Ornithology_20220406.csv](https://github.com/ArctosDB/arctos/files/9716945/Database_Ornithology_20220406.csv)

# Solution
**Community response with directions for how to correct the problem**

**Comment by dustymc** [comment]
I don't think you're getting that from what you attached - if you can get the error again, leave the data wherever it happened and let me know how to get there - that should eliminate a bunch of variables (and save me a bunch of clicking...)

**Comment by Jegelewicz** [comment]
OK just reloaded and got the same error - left stuff in the loader.

**Comment by Jegelewicz** [comment]
Oh wait - now error is ck_verbatim_locality_noprt - I can check those too.

**Comment by Jegelewicz** [comment]
There were excess spaces in verbatim locality - no idea why that wasn't the error the first time....

**Comment by dustymc** [comment]
you can also..


arctosprod@arctos>> select replaceFreeText(verbatim_locality,'X') from bulkloader_stage where checkfreetext(verbatim_locality) is false;
                                                            replacefreetext                                                            
---------------------------------------------------------------------------------------------------------------------------------------
 United States, California, Orange County; Mouth of Santa Ana River
 United States, California, San Bernardino County; El Cajon Pass, 3 miles north east of Summit
 United States, California, Orange County; Lemon Hts, northXTustin
 United States, California, Los Angeles County; 1 mile northXColby Camp
 United States, Nevada, Washoe County; Washoe Valley
 United States, Montana, Lake County; Biological Station
 United States, Arizona, Pima County; San Xavier Reservation, near Tucson
 Mexico, Baja California; End of northXRoad, elevation 7,000 feet
 Mexico, Baja California; End of northXRoad, elevation 7,000 feet
 Mexico, Baja California; End of northXRoad, elevation 7,000 feet
 Mexico, Sonora; 2 miles Sse Alamos
 Mexico, Sonora; 2 miles Sse Alamos
 Mexico, Baja California; Norte, Sa. Juarez, El Progresso
 United States, California, Riverside County; Joshua Tree National Monument, 1 mile N.W. Old Dale JunctionX
 United States, California, San Bernardino County; Joshua Tree National Monument, Lower Covington Flats, 3.1 miles Inside Park Bounary
 United States, California, Riverside County; Joshua Tree National Monument, Lower Covington Flats, south of Campgrounds
 United States, California, Orange County; Bolsa Chica Slough (Near Gun Club)
 United States, Kansas, Geary County; 3 miles N.W. of Alta Vista
 United States, California, Marin County; 3 miles east Point Reyes Station, St. Hwy 116
 Marianas Islands Road To Cubras Islands
 United States, California, Kern County; Route 14 1 mile northX of Route 38
 United States, California, San Francisco County; San Francisco
 United States, Nevada, Churchill County; Intersection of U.SrouteX50 and State Route 376
(23 rows)



to find instream problems - trim problems won't be so obvious, but they're still easy to find if you know that

>why that wasn't the error the first time....

It'll die on the firs encountered error

**Comment by campmlc** [comment]
Should "trim excess white space" just be a default for the bulkloader so we
can bypass these issues? It is such a drain of time and energy to track
these down.

**Comment by dustymc** [comment]
>Should "trim ... just be a default

[No.](https://github.com/ArctosDB/arctos/issues/5085#issuecomment-1259641226)
