### ISSUE TITLE
Feature Request - search for specific combinations of parts AND/OR exclude parts from search

### ISSUE THREAD

**Issue by kderieg322079** [ArctosDB/arctos#5131]
**Is your feature request related to a problem? Please describe.**
I am working on assessing the value of the collection for risk management purposes and need to put together a detailed summary of what is in the collection. This includes listing how many fluid specimens, skins +skull only, skins +skull/skel, and skin only. I cannot figure out a way to search for specimens that are ONLY a study skin with no skull, post-cranial skeleton, or tissue. Similarly, I am struggling to search for specimens that are ONLY a skull with no skin. If I search just for "skin" it will return all results that have a skin and any other part; same with skull.

**Describe what you're trying to accomplish** 
I would like to be able to run a search for (1) all specimens containing a specific combination of parts and/or (2) excluding other parts. 
Examples:
1. Search for skin,skull and results are ONLY specimens that have a skin and skull with no other parts.
2. Search for all specimens that have any parts EXCEPT for skin

**Describe the solution you'd like**
I could envision this either being a query builder were you select the parts from the code table and maybe check a box that says "exclude other parts not listed". Or there could be a drop down box similar to the **Identifiers** search:
![image](https://user-images.githubusercontent.com/82051765/194134732-062b40c8-d307-4246-8249-d1df9047b3a0.png)
And this drop down could include "is not" as an option so you could search "Part Name: is not **skin**"

**Describe alternatives you've considered**
The alternative is downloading the whole collection as a CSV and just filtering in Excel. I can easily do this, but I feel like better part filtering within Arctos would be ideal.

**Additional context**
I recognize that this is more important for collection management than it is for researchers searching for parts since a researcher wanting to use skulls probably wouldn't care to specifically exclude skins from their search, for example. I'm not sure if this is a feature others would care about, but it certainly makes inventorying a collection much easier. 

Maybe this fits in with #2745?

**Comment by Jegelewicz** [comment]
In a way - you don't care about catalog numbers? Just the "kind" of parts in a given collection, right? Sounds like some SQL might be good.

Are you comfortable trying to modify existing SQL? there is something [here](https://docs.google.com/document/d/15e3b8WNErFPqg1SW-QNq0nI_RjiEEZjWQDznxIJNFHE/edit#heading=h.aorsh71cfnom) that might be a good start. But also @dustymc could probably whip something up and then we can add it to the cheat sheet....

**Comment by kderieg322079** [comment]
Oh yes, that google doc is super helpful!! If this isn't a feature folks would use, then no point in wasting the time making it I can easily accomplish my goal with a SQL query. I am comfy enough with SQL for basic queries; I've mostly used it in a GIS context. I guess I just don't know how to interact with Arctos that way... So forgive my ignorance, but *where* do I run such a query?

**Comment by dustymc** [comment]
>isn't a feature folks would use

The spreadsheet is good at answering that too - things that get a lot of use find their way to the UI.


<img width="226" alt="Screen Shot 2022-10-05 at 1 42 17 PM" src="https://user-images.githubusercontent.com/5720791/194159464-3ff72c74-c05e-49c8-867a-5117675feada.png">

**Comment by Jegelewicz** [comment]
I feel like this could be s standard report that many collections might use.

**Comment by kderieg322079** [comment]
I agree. Most collections have to go through this process, which is frustrating enough since you can't _really_ put a price on any of these things, but being able to generate a report that summarizes a collection would indeed be helpful

Thanks for pointing me in the right direction - I usually am hesitant to submit an issue for this very reason because frequently Arctos already does the thing I need to do, I just don't know how to do it. I promise I combed through the documentation first. Might be worth updating the [documentation for conducting a search](https://handbook.arctosdb.org/how_to/How-to-Search-for-Specimens.html#specimen-search-refine-widget) to show that you can write SQL queries. I figured there must be a way, but obviously couldn't find it on my own.

**Comment by dustymc** [comment]
>I just don't know how to do it

100% issue-worthy (and maybe newsletter-worthy - you can't be the only one). There's often/usually _*something*_ that makes Arctos better in those.

**Comment by dustymc** [comment]
Here's some starter SQL - this finds UMNH:Bird records which do have a skin and do not have a skull or skeleton.

Just let me know if you need more.

```
select guid from flat
inner join specimen_part haspart on flat.collection_object_id=haspart.derived_from_cat_item
left outer join specimen_part nopart on flat.collection_object_id=nopart.derived_from_cat_item and nopart.part_name in ('skull','skeleton')
where
flat.guid_prefix='UMNH:Bird' and
haspart.part_name ='skin'  and
nopart.collection_object_id is null
```

**Comment by dustymc** [comment]
resolved via sql
