### ISSUE TITLE
Allow coordinate converter to leave a trail

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5133]
Original data entered into the coordinate converter disappear after you click "use these coordinates" They need to not disappear. It would be nice if the original data automatically get added/appended to georeference source.

_Originally posted by @Nicole-Ridgwell-NMMNHS in https://github.com/ArctosDB/arctos/issues/4866#issuecomment-1249606417_

**Comment by Jegelewicz** [comment]
Like verbatim geography, it would be nice to have verbatim coordinates....

**Comment by dustymc** [comment]
They're not like verbatim geography - I'm not changing anything.

They're not like as-entered coordinates -  see the source issue.

**Comment by dustymc** [comment]
I'm very unclear on how this could become functional, please:

1. transfer to documentation (if it can become guidance), or 
2. transfer to discussions (if it's just an idea), or
3. provide some actionable path, or
4. close

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Here is a screenshot of the coordinate converter:

![image](https://github.com/ArctosDB/arctos/assets/47402809/c90d050b-703c-4cec-a7a3-e5090cc73956)

Currently, if I want to record the coordinates as-entered into the converter, I have to type them into notepad or whatever, copy them into the converter, and then copy them into georeference source.

It would be very helpful if, when you select use these coordinates, it not only entered the converted coordinates, but also generated a georeference source attribute that says something like "coordinates entered into coordinate converter utm_ew 12345, utm_ns 123456, UTM Zone NAD27/UTM zone 13N, Datum North American Datum 1927" 

I do this manually right now, but it is very easy to make mistakes, especially forgetting to select the original datum in the converter, but entering the original datum correctly in georeference souce.

**Comment by dustymc** [comment]
Thanks, I was having trouble making sense of @Jegelewicz 's reference from https://github.com/ArctosDB/arctos/issues/6638.

I think you'd like the coordinate converter, when invoked from the edit locality UI, to write stringified input data (format TBD) to a https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlocality_attribute_type#georeference_source attribute - correct?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> correct?

Yes.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Awesome, thank you!

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
This works great, very helpful!
