### ISSUE TITLE
Feature Request - privilege creators

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#5136]
As a way of showing respect for the creative power of artists, especially those of Indigenous heritage who have been systemically erased in many Western museums, the cultural collections request moving the "Creator" agent line to the top of the list in the Catalog record display:

<img width="778" alt="Screen Shot 2022-10-06 at 11 41 25 AM" src="https://user-images.githubusercontent.com/17605945/194404493-bee52a98-ad6d-441e-bb59-1a4e32c0c76a.png">

This would show that when a creator's name is known and displayed, it is that information that is privileged.

**Comment by campmlc** [comment]
I support this.

**Comment by ewommack** [comment]
Sounds like a good idea to me.

Ok if I add to the development of the diversity and inclusion committee? https://github.com/ArctosDB/internal/issues/183

**Comment by Jegelewicz** [comment]
I agree with this.
