### ISSUE TITLE
geography - we have a plan!

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5138]
Geography discussed by Issues Group - https://docs.google.com/document/d/1lo14CsD-5jgCrxnuQg52Feb-O0Lix2B0LFNDrouLPSc/edit#

I think we have unanimous agreement on a very workable and shareable/portable approach.

# The Plan

The old "acceptable" flag will be revitalized and used - only certain geographies will be assertable. (That is, there will exist spatial "features" which cannot be chosen when eg entering catalog record data.)

# Geography

To begin, acceptable "assertable" geography will be limited to:

* GADM  - https://gadm.org/maps.html
    * levels 0 (country) and 1 (state) will be created globally
    * level 2 (county) will be created by Community approval only when there is a special need and a significant history of stability. Currently United States is the only candidate for this treatment.
* ~~SeaVox - https://www.marineregions.org/gazetteer.php?p=details&id=23616~~ EDIT: seavox is THE SHOUTY ONE, I meant IHO
* IHO World Seas -https://iho.int/
* "we don't know" - https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=69
* "we refuse to say" - https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10016350

# Fun and Flexible Features!

Anything will be eligible to be "unassertable" geography, including but in no way limited to
* continents - https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=4962
* parks - https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10004785
* islands - https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=1005324

Search will be rewritten to use intersections of geography and locality in addition to asserted geography. That is, a record which maps to Yosemite will be findable by:

* Park
* County/counties
* State
* Country
* Continent

Making the record also discoverable by region ("The West") or ecoregion (Sierras) or WHATEVER will involve only creating a spatially-aware feature.

Note that no search functionality hinges on what's asserted. Asserting Mariposa County and "we refuse to say" are functionally equivalent when the locality maps to the bits of Mariposa County that are within Yosemite.

(That's probably not entirely true, it's still possible to claim something that maps to Yosemite is from Antarctica, but I think it's true when the data do not conflict with themselves.)

# Cleanup

I will update current geography to reflect the structure and vocabulary of GADM, move finer-scaled geography to specific locality, and ask questions when anything ambiguous arises.

(Ditto SeaVox, but I've got to look closer at that before I can say anything useful.)

# Model Changes

There will be none. There will be *policy* changes about how the model is used, and a never-used field will be resurfaced, but this does not require any structural changes, everything is in place now.

# User Interface Changes

Also none; no UI changes are anticipated.

# Usability Changes

Users can expect fewer, less-ambiguous choices when selecting geography. Everything else stays the same.

# Arbitrary Assertions

Most anything can be asserted via Locality Attributes, which can optionally use controlled vocabulary. This provides a mechanism by which a collection can assert whatever they wish, geography-like or otherwise, and control the vocabulary as needed.

# Automagically Fixes

* https://github.com/ArctosDB/arctos/issues/5109 - Are non-US County-level political subdivisions geography?
   * No, see above, gadm2-equivilant places will not be created as assertable geography except by special approval
* https://github.com/ArctosDB/arctos/issues/5126   - Are islands geography?
    * No, Islands will not be assertable geography, but island data will be converted to features, and will work precisely like the Yosemite example above.
* https://github.com/ArctosDB/arctos/issues/5118 - will arbitrary things in collection data be created as geography?
    * No, these will need mapped to one of the four categories of assertable geography outlined above.
* https://github.com/ArctosDB/arctos/issues/5116 - Is US Berkeley Campus geography?
    * Nope, but it could easily be created as a Feature
* https://github.com/ArctosDB/arctos/issues/5105 - is country-or-weird-thing-plus-EEZ geography?
    * The Community would need to decide if they're assertable geography or not, some compelling need seems necessary
    * They could be created as Features, no debate or approval necessary
 * https://github.com/ArctosDB/arctos/issues/5036 - is some public area geography?
     * Nope, but it's a great Feature if spatial data can be produced.
* https://github.com/ArctosDB/arctos/issues/5017 - HELP, I don't know what to do with Feature!
    * Now I do:
        * Those without spatial data will be moved to specific locality
        * Those with spatial data will be cleaned up and kept as Features
* https://github.com/ArctosDB/arctos/issues/4836 - what to do with intersections?
    * Not geography, can be build - at any level of complexity and using various operations - dynamically
* https://github.com/ArctosDB/arctos/issues/4785 - higher geography lookup
    * Still could be implemented by request, but just asserting 'we refuse to say' will be functionally equivalent to letting Arctos figure out the assertion   
* https://github.com/ArctosDB/arctos/issues/4806 - Arctos comes up with crazy placenames!
    * Not any more. Arctos is now consulting only Arctos regarding place names, this agreement will ensure those data are consistent and predictable (but it'll take a while to get everything cleaned up and then processed)
    * 

# Does Not Fix

* https://github.com/ArctosDB/arctos/issues/4289 - users can assert Mongolia for a Yosemite-mapping locality 
    * There's no solution to this problem in what's been discussed and accepted, but it will make it a much easier thing to avoid (by choosing from much cleaner geography, or not picking anything and letting Arctos figure it out)

@mkoo @ewommack @AJLinn @genevieve-anderegg @Nicole-Ridgwell-NMMNHS @Jegelewicz @campmlc @wellerjes @ebraker @lin-fred @gracz-UNL @atrox10 please let me know if I've mucked anything up

@ewommack this needs communicated, but I don't know how to distill it down to anything between the above near-manifesto and "simple good, data better" - help?

**Comment by Jegelewicz** [comment]
Historical geogrpahy suggestiong from TDWG - https://openhistoricalmap.org/#map=5/51.481/-0.088&layers=O&date=1922-01-01&daterange=1922-01-01,2022-12-31

**Comment by dustymc** [comment]
Neat! I was wondering if I should un-do the recently added geography dates, but whatever data that service is using could be pulled in as FFF and the dates would be useful for that.

**Comment by Jegelewicz** [comment]
Was this already discussed? Discovered at TDWG - Along with IHO, Marine Regions has announced a new dataset to for marine areas: https://marineregions.org/files/newsletter_ecs.htm

**Comment by dustymc** [comment]
This Issue is announcing the results of a discussion, so yes.

There is room for more "standards," as long as they don't (much, maybe) conflict. Whatever this new thing is, it's probably eligible if some user wants to champion it through.

**Comment by Jegelewicz** [comment]
Question about how this works. I find [this feature](https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10016796)

![image](https://user-images.githubusercontent.com/5725767/198733914-1da9efb2-28d0-4d69-9a0b-887a1a1275c3.png)

and NONE of the options here give me anything - they either time out or say "no records found"

BUT a search in any geog from the main search page for Yosemite National Park gets me this
![image](https://user-images.githubusercontent.com/5725767/198734230-4a2d806b-083a-4fcf-b7dc-b87c23ad97cf.png)

PLUS a crazy map
![image](https://user-images.githubusercontent.com/5725767/198734309-c292989e-7738-4740-a240-d7f62eaf183d.png)

So what is going on and how should we expect these to work?

That crazy looking outlier in New Mexico is a group of 9 records

![image](https://user-images.githubusercontent.com/5725767/198734576-fcf54cec-0eea-489a-b4e6-fd99910d6f4c.png)

And they show up in the search results because of a HUGE coordinate error.

How could I get the stuff that only falls WITHIN the park boundaries from the main search page?

**Comment by dustymc** [comment]
>"no records found"

https://github.com/ArctosDB/arctos/issues/5211 - some of those options won't be in next release (because they can't do anything).

> time out

https://github.com/ArctosDB/arctos/issues/5213 - that's a request for more resources, if I don't get that I'll put like some huge amount of effort into some sort of crazy cache or something.

>crazy map

Yes, I've been struggling with that for a while, I don't know what to suggest, at some point ``huge error`` and ``null`` are (almost) functionally equivalent, I'm almost-sorta thinking we should be much more restrictive on max-max-error but that's nowhere near solidified either.

>How could I get the stuff that only falls WITHIN the park boundaries from the main search page?

<img width="575" alt="Screen Shot 2022-10-28 at 2 28 42 PM" src="https://user-images.githubusercontent.com/5720791/198735935-085b1fda-baa4-4558-8d69-3d49c8c261dc.png">

(which times out because #5213, but add California and it's probably close-ish...)


<img width="495" alt="Screen Shot 2022-10-28 at 2 31 30 PM" src="https://user-images.githubusercontent.com/5720791/198736249-2532f292-0606-4559-84aa-799451877ae8.png">

(The extras out by Lard should be additional events on records with contained events)

**Comment by dustymc** [comment]
I'm calling this done, with a few notes and exceptions

* Nepal:  https://github.com/ArctosDB/arctos/issues/5201
* Madagascar: https://github.com/ArctosDB/arctos/issues/5185
* Finland: https://github.com/ArctosDB/arctos/issues/5180

are best addressed with the next release of GADM, but I'll do what I can if someone needs them before, or if having a few outliers causes confusion.

Bits of the UK, along with another ~20 seemingly-random places, are in GADM maps but are not (or not in a way I can unravel) in GADM data, so are incomplete in some way. These are all documented in geography remarks.

I disabled the Wikipedia requirement long enough to update US counties so those are somewhat incomplete, but getting through the automation is strong evidence that they're correct and could be easily documented if someone has the time.
