### ISSUE TITLE
Arctos will automatically georeference localities without coordinates

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5141]
ref https://github.com/ArctosDB/arctos/issues/4916

Any locality which 
* DOES NOT have coordinates, and 
* DOES NOT have a ``georeference source`` locality attribute 

will be automatically georeferenced.

(The bot is currently in timeout for bad behavior, I plan to let it out early next week. The bot should **not** ever overwrite any existing data, only replace nothing with something. The bot - and it's creator - will be very sure it follows this rule before resuming operations.)

**Comment by acdoll** [comment]
These bot coordinates are not great! Especially the international and marine ones. It puts a locality for [Cuba](https://arctos.database.museum/guid/DMNS:Inv:11104) on Haiti. [Bali](https://arctos.database.museum/guid/DMNS:Inv:1287) is a 300 meter circle on the wrong island of Indonesia.  [Marshall Islands](https://arctos.database.museum/guid/DMNS:Inv:5348) is a small circle in the general vicinity. [Curacao Island](https://arctos.database.museum/guid/DMNS:Inv:23092) is placed on Martinique Island. [Ohio, Butler Count, Licking River](https://arctos.database.museum/guid/DMNS:Inv:23162) is placed on the Ohio River (not in even in Butler Co.)
I could keep going, but here's all the [DMNS:Inv specimens with bot generated coords](https://arctos.database.museum/SpecimenResults.cfm?locality_attribute_1=georeference+source&locality_attribute_value_1=Automatically+&locality_attribute_unit_1=&locality_attribute_determiner_1=&locality_attribute_method_1=&locality_attribute_remark_1=&scientific_name=&country=&state_prov=&spec_locality=&guid_prefix=DMNS%3AInv) if you'd like to click through them

One thought for improvement: If there is a spatial polygon, the error needs to include all of that. 
Can the bot cite it's source so we can back-track some of these issues? Maybe they all come from the same place. 

It's frustrating that we may have evaluated a record and determined that it was inappropriate to put coordinates in for whatever reason, and then the bot just comes along and does a crappy job of it anyway. (I'm not saying that is always the case, but I know that, in the past, I've intentionally excluded coordinates after careful deliberation)

> the spatial data adds value even if it is wildly wrong for some reason.

I couldn't disagree more. Unless you're considering 'value' as containing both positive and negative numeric values. A point on a map in the wrong spot is at best mis-leading, at worst it leads to incorrect inferences in spatial analyses. This doesn't seem research-grade to me.

All this said, I'm not against this concept in general - it seems to work reasonably well for terrestrial and north American stuff. But now it seems like we need to click through each one of these to see where it might be off. That's no different then needing to click through all of our un-georeference records, except now there's bad data sprinkled throughout.

**Comment by acdoll** [comment]
> sciencey reason

two actual locations with the same name that we cannot differentiate based on the info avialable

> add a `georeference source` locality attribute.

yes, that works going forward, but this ignores previous effort already put into it (I know, there's nothing we can do about that)

> nobody can find the thing has no (or negative) current value

That's assuming people are only searching on geography. Maybe these things aren't appropriate for questions where geography is important (maybe that's why we didn't put in questionable coordinates in the first place).

**Comment by dustymc** [comment]
>two actual locations with the same name that we cannot differentiate

So loop 'em both in. (I'm sure there are limitations on that, but surely there aren't TOO many 'Omaha-or-Kerguelens' situations.)

>ignores previous effort

Yes, that is unfortunately how our evolutionary development approach works sometimes. Let me know if I can help dig something out, and hopefully we've got everything right this time around....

>people are only searching on geography

I'm sure some don't, but I think most questions - at least in NH collections - involve some degree of place-ness. And I can't imagine a situation where someone rejects things because they have some place-data, so even if I'm wrong I'm not sure there's a cost to it.

**Comment by amgunderson** [comment]
We intentionally do not georeference captive specimens. We have zoo animals, pets, and tree shrews from medical experiment labs. We should not be plotting trees shrews to Duke University or tigers to anchorage or pet wolves (dogs) to urban centers.

**Comment by Jegelewicz** [comment]
After TDWG this year, I have to disagree with the statement above. Captive things interact with their environments and often with things that are "wild" like parasites, bacteria and viruses. Someone at TDWG was complaining that the work they do is not as easy because we view "captive" and "cultivated" things as less valuable, but they are still part of an ecosystem that some people may be interested in researching. Weird coordinates can also help people weed out those things if they aren't interested in them.

**Comment by mkoo** [comment]
@amgunderson I know this is an common practise, but see this too:
https://academic.oup.com/bioscience/article/72/5/449/6570825

We have ways to make sure that captive species translocated far from their natural range will not be mistaken for species documented in the wild but the documented location is still important (may just not be valid for a particular analysis). happy to talk more on this topic

**Comment by amgunderson** [comment]
I'll look at that paper. I am most concerned about data aggregators and niche models sucking up our data with bots making all the decisions, and we will have gerbils, hamsters, and garter snakes considered native fauna. I have never had an inquiry about captive specimens that was concerned with the geography of those specimens. Their geography is still very much documented in higher geography and specific locality fields and not hidden at all. Coordinates are always an important part of research into wild populations, which are 99% of the research use of our collections.

**Comment by cjconroy** [comment]
I agree with Aren. If users want to find our lab colony, aviary, zoo, pet store specimens, they can find them by searching for Captive under Collecting Source. I don't think all users are wise enough to parse out the captive ones when dowloading hundreds of thousands of records for range maps, niche models, etc.

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/5302 provides a compelling reason to *not* do that - the (correct) georeference revealed an incorrect geography assertion. 

>all the most incorrect 

https://arctos.database.museum/place.cfm?action=detail&locality_id=10669031 is the example I was able to find. Plattevelle seems to be what's confusing geolocate, so it ignores that and uses EAST which for some reason lands out there. Google suggests that there's no Plattevelle in Colorado, but there is a Platteville and if the locality is changed to that the results are very different.

Assuming my guess is what was originally intended then revealing the erroneous data seems more useful than not to me...

**Comment by bryansmclean** [comment]
Hi everyone, posting this after an unwanted interaction with the georef bot. Wondering if there are solutions to limit what gets automatically georeferenced....

We (UNCG:Mamm) have long-term sampling sites that exist as localities in Arctos (example: https://arctos.database.museum/place.cfm?action=detail&locality_id=11551843). These do NOT have associated geocoordinates because we sample mammals from individual traps within that locality, and give each a unique lat/lon. So we basically use those localities to ensure they are consistent among seasons and years. 

Unfortunately, when entering records the unique (trap-level) geocoordinates we assign are being replaced with the locality -level (automated) geocoordinates. In the prior data entry form we could "Depick locality" and this might help us again - is that particular functionality gone now?

**Comment by dustymc** [comment]
>geocoordinates we assign are being replaced

I don't think this is possible, the bot should never replace coordinates, but if you have a recipe for doing so please let me know ASAP and I'll fix.

I will add "locality is named" to the list of ways to avoid the bot - I don't think that will conflict with anyone's workflows, and it would have prevented the bot in this case.

**Comment by Jegelewicz** [comment]
> when entering records

I don't think the bot does anything upon data entry? It sounds like upon data entry, a named locality is selected, then different coordinates are entered, but because a named locality was picked, those coordinates get ignored. Am I understanding that correctly?

**Comment by bryansmclean** [comment]
100% @Jegelewicz. 
"Depick locality" helped us previously (and would help in this case too).

**Comment by Jegelewicz** [comment]
@dustymc see above. I think this is a data entry issue. Can we reinstate the "depick locality" functionality?

**Comment by dustymc** [comment]
Ah thanks @Jegelewicz 

"clear locality" should be the functionality you're looking for, but picking a locality and supplying coordinates are mutually exclusive so I think maybe this is deeper than the button having a better name?

**Comment by bryansmclean** [comment]
Confirmed that the Clear Locality button works as the "Depick locality" button once did.
