### ISSUE TITLE
[ geography request ]

### ISSUE THREAD

**Issue by jldunnum** [ArctosDB/arctos#5143]
# Carefully read the documentation at https://handbook.arctosdb.org/documentation/higher-geography.html before submitting a request.

### First Step: Explain what geography needs created.

Explain in sufficient detail for us to locate standardized spatial data. "County-level divisions of Some State, Some Country" or "whatever might be available for Some Country" is usually sufficient to start the process.

We will respond with a CSV template, or request more information.

Please add the following higher geography for Mongolia:

https://en.wikipedia.org/wiki/Rashaant,_Bulgan

Asia, Mongolia, Bulgan, Rashaant Sum

https://en.wikipedia.org/wiki/Delgertsogt,_Dundgovi

Asia, Mongolia, Dundgovi, Delgertsogt Sum

https://en.wikipedia.org/wiki/Saikhan-Ovoo,_Dundgovi

Asia, Mongolia, Dundgovi, Saikhan-Ovoo Sum

https://en.wikipedia.org/wiki/%C3%96mn%C3%B6delger,_Khentii

Asia, Mongolia, Khentii, Omnodelger Sum

https://en.wikipedia.org/wiki/Altanbulag,_T%C3%B6v

Asia, Mongolia, Tov, Altanbulag Sum

https://en.wikipedia.org/wiki/Bayan-%C3%96nj%C3%BC%C3%BCl

Asia, Mongolia, Tov, Bayan-Onjuul Sum
 

https://en.wikipedia.org/wiki/Sergelen,_T%C3%B6v

Asia, Mongolia, Tov, Sergelen Sum

https://en.wikipedia.org/wiki/Khanbogd,_%C3%96mn%C3%B6govi

Asia, Mongolia, Omnogovi, Khanbogd Sum

https://en.wikipedia.org/wiki/Khan_khongor,_%C3%96mn%C3%B6govi

Asia, Mongolia, Omnogovi, Khan khongor Sum

https://en.wikipedia.org/wiki/Bat-%C3%96lzii,_%C3%96v%C3%B6rkhangai

Asia, Mongolia, Ovorkhangai, Bat-Olzii Sum

 

The Sum needs to be capitalized on these which are already in Arctos.

Altanbulag sum
Nomgon sum

**Comment by dustymc** [comment]
Please see https://github.com/ArctosDB/arctos/issues/5138

I believe all of the GADM1-level areas exist as geography.

**Comment by jldunnum** [comment]
I think the Aimags exist but not the Sums.

______________________________________________________________

Jonathan L. Dunnum Ph.D. (he, him, his)
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

Chair, Systematic Collections Committee, American Society of Mammalogists
Latin American Fellowship Committee, ASM

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by dustymc** [comment]
Yes.

>level 2 (county) will be created by Community approval only when there is a special need and a significant history of stability. Currently United States is the only candidate for this treatment.

**Comment by jldunnum** [comment]
Ahh OK, we already had some Sums in there...

______________________________________________________________

Jonathan L. Dunnum Ph.D. (he, him, his)
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

Chair, Systematic Collections Committee, American Society of Mammalogists
Latin American Fellowship Committee, ASM

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________
