### ISSUE TITLE
Code Table Request - verbatim geography

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5144]
**Goal**

https://github.com/ArctosDB/arctos/issues/5138 will require changing a lot of geography. Some preservation of the current values would make understanding the migration path harder to avoid. A new locality attribute is one possible way of doing this.

**Context**

I don't think we have an appropriate place for this data. Verbatim locality is not appropriate. 

**Table**

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlocality_attribute_type

**Proposed Value**

* verbatim geography

The word 'verbatim' in the proposed attribute may imply something that isn't true, but I can't think of a better term. Help with terminology would be greatly appreciated.

**Proposed Definition**

* Previously-asserted geography string.

This serves my purpose, but the concept may be useful for other things. Better/broader/more inclusive definitions are most welcome.

**Attribute data type**

free-text

**Attribute value**

For my purposes, this will be the higher_geography concatenation. Other collections might wish to eg, preserve values from another database.

**Priority**

High - I will create this as I begin to change things, unless someone has a better idea for maintaining this history.

**Comment by campmlc** [comment]
"geography as migrated"?
"as-entered geography"- doesn't imply verbatim?
"legacy geography"?

**Comment by Jegelewicz** [comment]
HMMMM - this will potentially separate localities that are otherwise exactly the same, no? Shouldn't this really be a collecting event attribute? OR will some locality potentially have multiple "verbatim geography" attributes?

**Comment by dustymc** [comment]
> this will potentially separate localities that are otherwise exactly the same, no? 

Correct.

>o? Shouldn't this really be a collecting event attribute? 

That would be a huge denormalization, but it would also lead to more locality normalization so perhaps that's a price worth paying.

>OR will some locality potentially have multiple "verbatim geography" attributes?

Not from me. 

I'm going to change 'thing we've now agreed isn't geography' into 'thing we've now agreed is geography.' I'm going to try to faithfully move whatever is in the former and not in the latter into specific locality, which would almost assuredly be enough if everyone followed documentation. They don't, so I'd like a second fully-verbatim place for the original data because I'm not 100% sure I won't do something cryptic (when combined with other data) during the cleanup process.

I don't much care how precisely that's done, but I'm not going to let the minor details much get in the way of a major revision so if someone wants something other than what I've proposed now is the time. I can work with WHATEVER - some new thing as proposed, a datadump archived somewhere, media attached to records, WHATEVER, I don't care, I just don't want to get yelled at when Island ends up somewhere unexpected.

**Comment by Jegelewicz** [comment]
> faithfully move whatever is in the former and not in the latter into specific locality, which would almost assuredly be enough if everyone followed documentation. They don't, so I'd like a second fully-verbatim place for the original data because I'm not 100% sure I won't do something cryptic (when combined with other data) during the cleanup process.

Yeah - I guess it's no different than the township stuff, just thinking out loud and want to make sure I don't regret not saying anything later....

**Comment by dustymc** [comment]
I tried a few things and went with 'previous geography' in test - I think I like it....

Here's an example of what I'm planning, timely suggestions greatly appreciated:

<img width="795" alt="Screen Shot 2022-10-13 at 8 29 55 AM" src="https://user-images.githubusercontent.com/5720791/195640483-aff9f62e-62f2-4c29-a530-3388b5d305c9.png">
