### ISSUE TITLE
[CONTACT]

### ISSUE THREAD

**Issue by Mastough** [ArctosDB/arctos#5146]
** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **

** Outages should be reported to the contacts listed at https://arctosdb.org/arctos-down/ **

** Arctos Documentation is http://handbook.arctosdb.org/ **

** Learn more about Arctos at https://arctosdb.org/ **

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **

** I could not remember my password. I try to press forget password, but when I put the temporary password in from the email, it does not work and shows what is in the screenshot: **
<img width="784" alt="Screen Shot 2022-10-09 at 10 58 13 PM" src="https://user-images.githubusercontent.com/115438045/194797487-13cada5d-bf52-4932-9c56-515589b25dd6.png">

**Comment by mkoo** [comment]
HI Mary, please try again to reset your password. I reset your account as
it was likely over its password attempt limit.
