### ISSUE TITLE
Feature Request - Accomodate pathogen screening documentation

### ISSUE THREAD

**Issue by jldunnum** [ArctosDB/arctos#5147]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
Arctos ' ability to accomodate pathogen screening data is very limited

**Describe what you're trying to accomplish** 
As many collections are now actively tied into research on pathogen discovery and pathobiology Arctos has a great need to enhance functionality in regard to linkage of hosts/pathogens but also capture associated screening metadata. 
The goal is to capture whatever would be useful for us as collection managers but also to others in the various pathogen focused communities in regard to querying host/pathogen relationships and also simply mitigating loss of testing lab data that often doesn't make it into collection databases.  
So in addition to the already available ability to link to other databases containing pathogen sequences and other associated data we would like to add a series of attributes. Those included below are meant as a first pass and hopefully the Arctos community can help to refine these.

**Describe the solution you'd like**
ATTRIBUTE FIELDS              [drop down query options]
**"Screened for pathogen"** - [yes, no]

**"Pathogen screening"** – [targeted, non-targeted] 
(e.g. targeted - Orthohantavirus, plague, malaria, rabies, SARS CoV2, West Nile, Lyme disease, histoplasma, Coccidioides, ......, and Non-targeted (e.g. metagenomic screening) 

**"Screening method"** - [metagenomics, eDNA – (need sequencing method, platform, and depth of coverage), Western blot (WB), enzyme-linked immunosorbent assay (ELISA), PCR,.......] 

**"Tissue type screened"** - [blood, heart, kidney, lung, liver, large intestine, small intestine, cecum, feces, saliva,......] _should be linked to individual part in Arctos_

**"Screening results"** - [positive, negative]
_(This field probably only makes sense when the screening method is targeted. Metagenomic methods will likely be the more common method going forward and will identify many different pathogens in a single host so need to accommodate multiples)_

**"Pathogen detected"** - [i.e. Sin nombre orthohantavirus, Hantaan orthohantavirus, Plasmodium falciparum,  ......]
_(This would need to be a multiple selection field. Needs to be backed by pathogen taxonomy and accommodate coarser classifications (ie. if a pathogen was only classified to family-level). ) Will also need pathogen taxonomic fields in Arctos so that we can query host pathogen combinations._
**“Pathogen titer”** 

**Describe alternatives you've considered**
No other alternatives are out there as far as I know

**Additional context**

**Priority**
High

**Comment by campmlc** [comment]
This may be better as a part attribute - to record the actual tissue part that was screened. But then we currently don't have all the fields required in part attributes.
@dustymc any way to automatically link attributes and part attributes? We may need both, but we would need to populate the fields from a single interface for users to enter the data. Maybe a Parasite/Pathogen module?

**Comment by campmlc** [comment]
Related to linking GenBank identifiers and genetic sequence data directly to parts vs to the catalog record.
See also https://github.com/ArctosDB/internal/issues/175

**Comment by dustymc** [comment]
I'm tentatively merging this with https://github.com/ArctosDB/arctos/issues/5087 - I think it's the same data, WHATEVER is done should be coordinated with other similar data. 

>better as a part attribute

Fine with me, but that means you'll need to maintain eg a liver part after you've destroyed the part (by making lots of tissues and using them up, perhaps).

>currently don't have all the fields required in part attributes.

Sure we do??

>automatically

I have no idea what this means. Unified search isn't much problem, knowing you were looking at a liver when you enter the data for the catalog record requires more sorcery than I possess - clarify?

>Related to linking GenBank identifiers 

I think maybe you're referring to https://github.com/ArctosDB/arctos/issues/3630 so I'll say it again:

That capability has existed for a very long time, it's a social problem between loaning collections and borrowers. More formalized structure would add stability, not change functionality. If you want to do this then do it; the data will guide more development.

**Comment by Jegelewicz** [comment]
Thanks @dustymc I agree this is the same Type of data.

**Comment by jldunnum** [comment]
OK if we went this route, what would be the next steps? Lots more potential layers in the pathogen metadata than there are in the simple physical examination of a bone for pathology or presence of a parasite. Not sure how broad metagenomic screening would fit into this model.  Also terminology-wise we "screen" for pathogens as opposed to "examine".


______________________________________________________________

Jonathan L. Dunnum Ph.D. (he, him, his)
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

Chair, Systematic Collections Committee, American Society of Mammalogists
Latin American Fellowship Committee, ASM

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by campmlc** [comment]
Reopening per 1-10-23 pathogen discussion.  We need to reconsider these fields as part attributes, and map some use cases.
@jldunnum
