### ISSUE TITLE
Agent Split Request Oscar W. Johnson / Oscar Johnson

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#5148]
Use this template if you believe an agent represents more than one person or organization.

**Agent that represents more than one person or organization**
Navigate to the agent page, copy the url and paste it below:
https://arctos.database.museum/agents.cfm?agent_id=1015880

**New Agent**
Provide details that should be associated with a new agent to be split from the agent above.

all UTEP ID's, permits, collections, attributes, event determinations
most of UCSC's ID's, collections, and preparations, but they may need to be sorted out.
all MSB's ID's 

 - **Agent preferred name:** 
 - **Agent details:**
 Oscar Johnson
Ornithology Postdoc specializing in neotropical birds in Michael G. Harvey Lab at UTEP 2022-
Nicknamed OJ
i can add the rest after.

**Reason for split**
Please provide the reason you believe that this agent represents more than one person or organization.
Postdoc Oscar Johnson isn't the same as Oscar W. Johnson who was at CRCM in 1960s. UC Santa Cruz may have both Oscars collections and collections from 1900-1990 are Oscar W.?? Postdoc Oscar was only at UCSC from 2008-2011

**Affected Collections**
Please list the collections that will be affected and would use the new agent. If possible provide Github usernames for those who might have an interest in the split.

UCSC:Bird
UCSC:Herp
MSB:Bird
UTEP:Bird (I can move all related items over if necessary).

@catherpes (is this working? drop down menu didn't show up user).

Please add this issue to the Agents Project.
@
@ArctosDB/agents-committee

**Comment by lin-fred** [comment]
The Arctos committee approves of this but it seems you might have a difficult time getting a hold of the other collections, as I think catherpes left the institution as their profile is no longer under the Arctos Github.

**Comment by Jegelewicz** [comment]
@mvzhuang create the new agent, then use the Change Stuff Agents tool to change your agents to the correct name. See https://handbook.arctosdb.org/how_to/How-to-Batch-Update-Agents.html

**Comment by jldunnum** [comment]
Catherpes is Andy Johnson, he is still at MSB Birds and says he will weigh in when he gets a chance

______________________________________________________________

Jonathan L. Dunnum Ph.D. (he, him, his)
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

Chair, Systematic Collections Committee, American Society of Mammalogists
Latin American Fellowship Committee, ASM

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by catherpes** [comment]
I don't see which specimens are associated with an Oscar Johnson at MSB Birds. I would suggest emailing Oscar at UTEP and asking him which specimens are his. ojohnson@utep.edu

**Comment by mvzhuang** [comment]
I think he id'd some birds. Look under identifications on his agent page. And one pub has a msb associated specimen

On Oct 13, 2022 4:06 PM, catherpes ***@***.***> wrote:

I don't see which specimens are associated with an Oscar Johnson at MSB Birds. I would suggest emailing Oscar at UTEP and asking him which specimens are his. ***@***.******@***.***>

**Comment by dustymc** [comment]
https://arctos.database.museum/SpecimenResults.cfm?identified_agent_id=1015880&collection_id=20

**Comment by catherpes** [comment]
So that one Dusty sent is UTEP Oscar Johnson

**Comment by catherpes** [comment]
Is there some documentation as to how Johnson and Brumfield became the identifiers on this specimen? Oscar does not have a login or user name, so was this somehow automated??

**Comment by mvzhuang** [comment]
Whoever entered in the associated publication and the specimen citation I'm guessing. Who enters your pubs? You don't need login (just for modifying or entering data) for identification - just need to be an agent.

Will work on splitting our stuff!


On Oct 13, 2022 5:00 PM, catherpes ***@***.***> wrote:

Is there some documentation as to how Johnson and Brumfield became the identifiers on this specimen? Oscar does not have a login or user name, so was this somehow automated??

**Comment by dustymc** [comment]
The "More" link will tell you what I know, which isn't much.

<img width="655" alt="Screen Shot 2022-10-13 at 4 06 27 PM" src="https://user-images.githubusercontent.com/5720791/195726582-7b859e4d-63d9-4e6a-89b3-1458b0d94cad.png">

About the only thing close to automation that's possible there would be an agent merge, and I don't see any indication of that on the agent record. Looks like a user picking the wrong (??) thing to me, but I can't prove it....

**Comment by dustymc** [comment]
>Whoever entered in the associated publication 

Oh duh, yes, that's surely it.

**Comment by catherpes** [comment]
Okay Thanks. Good to know this isn't automation making a mess.

**Comment by Jegelewicz** [comment]
Are we done here? I'm not clear on what needs to happen.

**Comment by mvzhuang** [comment]
uhhh i need to get a hold of ucsc i think

**Comment by Jegelewicz** [comment]
OK - @dustymc does this need the next task milestone? Seems like it should be requires user action?

**Comment by mvzhuang** [comment]
i moved all of my stuff
@catherpes MSB ID still needs to be changed to Oscar Johnson
Already contacted UCSC - Alex Krohn responded but not sure if he's still there? and no action from other data manager.
What do?

**Comment by Jegelewicz** [comment]
@mvzhuang Matthew Brady entered two records on December 23, 2022 and picked Oscar W. Johnson instead of Oscar Johnson. I changed them, but you may want to make sure any new records get the correct agent.

https://arctos.database.museum/guid/UTEP:Bird:3108
https://arctos.database.museum/guid/UTEP:Bird:3111

**Comment by Jegelewicz** [comment]
Closing this to keep things clean - will create a new issue for the new problem.
