### ISSUE TITLE
modifications to Nature of ID and Basis of Citation

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ArctosDB/arctos#515]
```
Distilled from a long email thread 18 Jan 2012:


rename "Basis of Citation" to "Citation/Type Status" on Specimen Search page.

Remove "type specimen" as a value from Nature of ID.

Modify Nature of ID so values represent something about HOW a specimen was 
ID'd, e.g., morphology, molecules, plumage, song, etc. Figure out what to do 
with existing values that don't fit into  new categories.
```

Original issue reported on code.google.com by `carla...@gmail.com` on 19 Jan 2012 at 1:16

**Comment by DerekSikes** [comment]
Whatever we do with this list - can we please, immediately remove 'ID of Kin' as the default? The default should be NULL like every other yellow field in data entry! Too many techs accidentally let records go with 'ID of Kin' when they shouldn't. And fixing them is a one-at-a-time PITA.

**Comment by AJLinn** [comment]
> can we please, immediately remove 'ID of Kin' as the default? The default should be NULL like every other yellow field in data entry!

YES, a thousand times yes! This is a weird thing for cultural items and we get way too many of them.

**Comment by campmlc** [comment]
Yes, absolutely, please. Ditto for any dropdown anywhere - all default
values should be null.
Could we get a list by collection of all "ID of Kin" records so we can go
through and identify which need to be corrected?
