### ISSUE TITLE
error feedback

### ISSUE THREAD

**Issue by drtplp** [ArctosDB/arctos#5150]
** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **

** Outages should be reported to the contacts listed at https://arctosdb.org/arctos-down/ **

** Arctos Documentation is http://handbook.arctosdb.org/ **

** Learn more about Arctos at https://arctosdb.org/ **

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **

Hello!

ERROR_ID | 9DB4A422-E164-491C-8F3B28EA34FDDB7E
-- | --
ERROR_TYPE | application
ERROR_MESSAGE | Error invoking external process
ERROR_DETAIL | psql:/usr/local/webroot/temp/excopy_pereiratpl_20221010051030411_081.sql:122: ERROR:  syntax error at or near "[" LINE 2: [uamobs:ento]uam-2012.06-un-ento,2004-06-29,2004-06-29,2004-...         ^

I know for a fact that : [uamobs:ento]uam- needs to be uppercase BUT when I open the csv. doc on my apps (Pluma and LibreOficce) they are in uppercase. The same with the date, I know for a fact that it needs to be YYYY-MM-DD, but again when I open the csv. doc on my apps (Pluma and LibreOficce) they are correct. Which open-source app could I use to fix it?

Thanks

[Phorid LACM_data to bulkload into Arctos_4.csv](https://github.com/ArctosDB/arctos/files/9749756/Phorid.LACM_data.to.bulkload.into.Arctos_4.csv)

**Comment by drtplp** [comment]
I just opened the doc on google spreadsheets, save as csv. and worked!

**Comment by dustymc** [comment]
I believe whatever you're using is using linebreaks instead of carriage returns - newlines aren't being recognized, whatever the cause. Should be some setting somewhere...
