### ISSUE TITLE
distinguish between collector and preparator for "potential problem" reports

### ISSUE THREAD

**Issue by droberts49** [ArctosDB/arctos#5153]
I'd like to request that there is distinction between the collector and preparator for the error reports that show up at the bottom of a catalogue record to reduce the number of issues that are generated.

Example: CHAS:Herb:1878.17.1103 (https://arctos.database.museum/guid/CHAS:Herb:1878.17.1103) has a collector of Elizabeth Emerson Atwater, collected sometime between 1870-12-31 to 1878-04-11. It was unmounted for many years and prepared by Anna Pedersen Kummer in the 1940s. At the bottom of this record is the report indicating a potential problem in the dates (collecting vs collector). In this situation, it is picking up the preparator, rather than the collector (or maybe it's finding both but the preparator gives the error).

Could the process through which this report reviews collection date and agent data be changed to only look at the collector (or maker) but not the preparator?

**Comment by Jegelewicz** [comment]
But the original report is still there - wait for some sort of cleanup or are we just stuck with those?
