### ISSUE TITLE
Feature Request - agent search - verbatim agents

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5157]
**Is your feature request related to a problem? Please describe.**

<img width="559" alt="Screen Shot 2022-10-12 at 12 40 46 PM" src="https://user-images.githubusercontent.com/5720791/195433365-ad94b38e-f571-46bb-b888-6a0cf058f048.png">

Should that be default yes?

Maybe remember by user?

**Describe what you're trying to accomplish** 

happy search

**Priority**

?

@jtgiermakowski

**Comment by jtgiermakowski** [comment]
I'd say by default we should assume that "Any part of any name" jives well with searching through verbatim agents as well by default. If that's something that can be set per user logged in (or personalized), even better...

Searching for obscure names can help to put more data in those entries...
medium priority

**Comment by lin-fred** [comment]
>Maybe remember by user?

I vote for this as I would rather the default be no as most of my agents that are in verbatim are in there for a reason and I don't need to seem them in my usual searches.

But I could see a lot of collections who still need to see their verbatim agents often wanting the search to default to 'yes'
