### ISSUE TITLE
Code Table Request - potential duplicate of

### ISSUE THREAD

**Issue by lin-fred** [ArctosDB/arctos#5158]
**Goal**
Sometimes there's a hint that agents might be duplicated but more investigation is needed.

**Context**
See issue #5056 from dusty

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctagent_relationship

**Proposed Value**
potential duplicate of

**Proposed Definition**
This agent appears to be a duplicate of the related agent. If the [not the same as](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctagent_relationship#not_the_same_as) relationship is not added within 90 days the relationship will be changed to [bad duplicate of](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctagent_relationship#bad_duplicate_of), marking the agents for merger.

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/5711 needs to happen, there'll never be a better time to catch this. 2CT admins have reacted positively and I'm volunteering to build the necessary handlers while I'm rebuilding the things that aren't working properly. I'm moving on with a slightly altered definition:

```
This agent appears to be a duplicate of the related agent. If sufficient disambiguating information is not added and this relationship removed within 90 days the relationship will be changed to bad duplicate of, beginning the usual agent merger process. https://github.com/ArctosDB/arctos/issues/5158
```
