### ISSUE TITLE
Data entry 

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#5159]
Blank slate data entry page: 
Attribute date is required (often not provided) - not yellow, should be optional
Elevation fields - if depth default is set to show, elevation should be too (or was that just my settings?).

and just to be nit-picky, these buttons should be standardized:
![image](https://user-images.githubusercontent.com/12507297/195463801-0b227048-050e-4ed9-bff3-459e5497e3a4.png)
![image](https://user-images.githubusercontent.com/12507297/195464294-4c342718-e9b3-4b7d-b443-62799487021c.png)

**Comment by dustymc** [comment]
>Attribute date is required 

https://github.com/ArctosDB/arctos/issues/4184

>Elevation fields



```
 minimum_elevation                              | character varying   |           |          | 'show'::character varying
 maximum_elevation                              | character varying   |           |          | 'show'::character varying
 orig_elev_units                                | character varying   |           |          | 'show'::character varying
 min_depth                                      | character varying   |           |          | 'show'::character varying
 max_depth                                      | character varying   |           |          | 'show'::character varying
 depth_units                                    | character varying   |           |          | 'show'::character varying
```
>should be standardized

Define the standard! (And a CSS class would be nice - search ``/* BEGIN purpose-coded buttons */`` in https://github.com/ArctosDB/PG/blob/master/includes/style.css for existing.)

**Comment by dustymc** [comment]
>copy to next, copy to multiple?

Good point, and yes I think so. Maybe --> (copy one) and ==> (copy many)? (The former looks a lot like ending an HTML remark and the latter has some meaning in PG functions - not sure how distinctive these need to be??)

> looking for in that CSS 

It's the stuff that makes delete buttons red and links blue and such. We can do nothing, reuse some existing (this is not QUITE an insert, maybe, ish...), or build a new 'cpyBtn' (just need colors).

**Comment by acdoll** [comment]
I don't think we need to change colors, but the different symbols were a little confusing and I know many (most?) people are weary of just clicking buttons to see what they do. (I'm not, clicking buttons is the best!)
I like symbols so would go with --> for copy to next field and -->> for copy to the following fields

If people thought text is better for clarity's sake, maybe to match Copy2All:
Copy2Next - completes the next related field
CopyAcross - completes the following fields in that row
