### ISSUE TITLE
[CONTACT]

### ISSUE THREAD

**Issue by jsalazarbravo** [ArctosDB/arctos#5160]
** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **

** Outages should be reported to the contacts listed at https://arctosdb.org/arctos-down/ **

** Arctos Documentation is http://handbook.arctosdb.org/ **

** Learn more about Arctos at https://arctosdb.org/ **

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **

I am currently located in Bolivia. When i try to use Arctos database, I get the following message: "Your IP (177.222.113.185) or organization has been blocked."

I need to use Arctos, I worked at Univ of New Mexico for many years and deposited several hundred specimens at MSB.

Please help me get access.

Jorge

**Comment by dustymc** [comment]
Released - it will take about 10 minutes for everything to catch up.
