### ISSUE TITLE
Cannot login with existing password and cannot create new password

### ISSUE THREAD

**Issue by msbparasites** [ArctosDB/arctos#5162]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I tried to login with my password, it failed each time and said: "Authentication failed. Additional Information: Access restricted". 
I requested new passwords,  those passwords didn't work. I had this same problem, #4826, and we resolved it by the following:

"1. We turned off the auto username/password entry function in Firefox
2. Reset the user account (sent a temporary password and mail worked YAY!)
3. Used the temp password to login! YAY!!!
4. Changed the user's password.
So it seems like the autofill in the browser is somehow overriding whatever is typed in? I'm not sure why, but that seemed to be the problem..."

I did the above in both Chrome and Firefox, turned off autofill (which I had done in #4826, so do browser updates reset autofills?). Attempted to get new temp password in each browser, and those attempts failed.	

Another question is why does this happen? It happened at UNM today on Chrome, and I did not have time to fix it. Now I am home on two different computers from UNM, and the same error. Maybe they all update at the same time? I don't know the version of the browsers of the UNM ones until tomorrow.

**To Reproduce**
Attempt to login

**Expected behavior**
enter into my Arctos account

**Desktop (please complete the following information):**
 - OS 12.6 Monteray
 - Chrome (106.0.5249.119) and Firefox (105.0.3 (64-bit))

**Priority**
ASAP - just like last time, I got a pile of stuff in that needs to be catalogued I hope by tomorrow at this point.....

**Comment by campmlc** [comment]
Just got this, apologies, I can try to help first thing tomorrow? I don't know why this is happening, but maybe can help with a workaround.

**Comment by msbparasites** [comment]
No worries, most certainly tomorrow is good!

**Comment by dustymc** [comment]
I reset the login attempt block and emailed you the latest password recovery from the logs.

**Comment by msbparasites** [comment]
woohoo!!! It works.... Is there something I can do to prevent this, or fix it without bothering everyone...?

**Comment by dustymc** [comment]
I don't know. One thing these seem from here to have in common is password managers, but those are really common and that could be incidental (and FF **probably** didn't turn it back on in an update, but stranger things have happened).

If I had to guess, I'd probably blame UNM - either something they install on computers or something in their network, we've see strange things from both before, but I don't see any recent evidence of that either.

There's always a possibility that this is someone trying to brute-force their way into your account (what the attempt restriction is designed to prevent), I can never quite rule that out but I don't see any evidence of it either.

Do please let me know if you get any hints or notice any patterns or whatever - I know this is frustrating and I'd definitely like to address it.

**Comment by msbparasites** [comment]
Will do. You all have always been so responsive, I was hoping the funny business could be easily sorted! But no problem, thanks again so much for everything.

**Comment by campmlc** [comment]
If this happens again, maybe try to open a new private window in your browser to log in? Possibly won't try to autofill?

**Comment by msbparasites** [comment]
I have no idea why this is happening again, but I logged in this morning, worked in Arctos, and now I cannot login and I cannot get the requested new password to work. I cannot login to Arctos. I tried to login with my password, it failed each time and said: "Authentication failed. Additional Information: Access restricted". I do not understand how or why this happens?

**Comment by dustymc** [comment]
Reset the lock

**Comment by msbparasites** [comment]
I just tried that and nothing changed, same error.

**Comment by dustymc** [comment]
Is your computer caching like crazy perhaps? (Probably some 'make it go fast' extension or plugin or virus checker or similar.)

<img width="1329" alt="Screen Shot 2022-10-25 at 12 04 27 PM" src="https://user-images.githubusercontent.com/5720791/197860103-3d99d604-9243-4222-b6eb-d871a5419dcb.png">

**Comment by msbparasites** [comment]
If it is doing that, it is doing it on its own. I have not changed any of the settings. On the Mac, I don't have a virus checker, extensions and plug ins should all be what was there before (or maybe I am computer illiterate?).

**Comment by msbparasites** [comment]
UGH!! Ok, I will put in a ticket and see if anyone comes to look...... if they know Macs... Yes I logged in at home, but I am not in yet and wanted to make sure I can login at work too. If so, I will close this. I anticipate it should work, as before. THANK YOU!!!!

**Comment by msbparasites** [comment]
At work, I could log in to Arctos  with new password minus telling me I am a failure. Good to know. For now. I feel like the browsers are now like the Titan slugs in Heinlein's The Puppet Masters......Thank you, again!

**Comment by msbparasites** [comment]
Hello again, I am back with the same password problem. I tried to login with a password I had just used Friday, still good. Says "Authentication failed. Additional Information: Access restricted".

I asked for new password, typed that in, and still "Authentication failed. Additional Information: Access restricted".

I had opened an issue with UNM, no response, I was also out of the country for a bit so just now requested UNM get back to my request. 

I wonder if there is a "number of times logged in to Arctos, then get kicked out"? I looked at the dates I posted complaints, but that is not helpful, I don't know how much I used Arctos between when the problem started. 

This last stretch, I used 3 different computers. Maybe one of them is buggy? (I don't know how to ask it if it is buggy...).
Ugh. Thanks for looking at this.

**Comment by dustymc** [comment]
I'm sorry that I still don't have much diagnostic help to offer, but I've reset your login attempts and your last password should work.

**Comment by msbparasites** [comment]
Ok thanks so much. I could this time request a new password, old one did not work. But at least I got it changed and am logged in.

**Comment by msbparasites** [comment]
Hello again, I am back with the same password problem. I tried to login with a password, says "Authentication failed. Additional Information: Access restricted".

I have had IT over and checked the computers I use, showed him the Github and email exchanges of possible problems, and he could find nothing wrong on UNM side. At least this password lasted longer than the other ones....

If you could please reset, or let me know a new plan..... Thanks.

**Comment by dustymc** [comment]
reset

**Comment by msbparasites** [comment]
Thanks. I finally got my temp password and it still won't let me login

**Comment by dustymc** [comment]
I'm not sure what that could be. You still had some attempts left, but I reset anyway so you have 10 open tries. I believe Arctos is reliably sending email. Your last password (starts with ``i;i``) is a doozy, maybe your email client is mangling it; you can request another if that might be it.

**Comment by msbparasites** [comment]
ok, will try again later. Arctos refuses to load right now, and bird guts are calling....

**Comment by msbparasites** [comment]
Got it, thank you!

**Comment by msbparasites** [comment]
I am back. I could not login with my NEW password from 5 days ago, which I wrote down and stuck it to the computer, and requesting a new password also does not work. The usual merry go round. Help please.

**Comment by campmlc** [comment]
This is pretty crazy. How many times has this happened to you?

**Comment by msbparasites** [comment]
Several, not sure if at double digits yet. Can't find pattern. Had Matt come out too and look.....

**Comment by campmlc** [comment]
Does it only happen on one computer, or on different computers and browsers?

**Comment by msbparasites** [comment]
ok great. Finally got a password and I can login. Thanks.
