### ISSUE TITLE
Add more than one Id_Made_By_Agent to bulkloader

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#5164]
Does anyone have a solution for when you are bulkloading catalog records and you have IDs made by more than one agent? How do you handle that short of going back through each record and adding the additional identifiers or creating a 'group' agent? I've looked at both change stuff > identification and change stuff > agents and neither seems like they will work for this?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
That is just in the bulkload identifications tool? The catalog record bulkloader appears to just have one id_made_by_agent field?

**Comment by Jegelewicz** [comment]
This is definitely a problematic thing. In the past, I've only had a few and I have gone back and manually edited them. If you have a lot though, I suggest adding the ids in the bulkloader with a single agent, then using the batch tool to add the actual ID. I think you could then use the manage option to remove the original.

FWIW, this is my argument for being able to add a record WITHOUT an identification.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I have 268 records that need to be updated with a second id made by agent. And that will eventually become several thousand records.

> If you have a lot though, I suggest adding the ids in the bulkloader with a single agent, then using the batch tool to add the actual ID.

I considered this, but it doesn't look the the manage option can remove the original version. I wouldn't want to leave the original version, because it would be inaccurate. I suppose I could load the data with ID unidentifiable, agent unknown, but that would just be garbage data.

**Comment by Jegelewicz** [comment]
If you use something really generic (Animalia by unknown) @dustymc could probably remove it pretty easily? Not a good long-term solution, but that may get us to one....

**Comment by Jegelewicz** [comment]
> usual approach to this is to add identifier_n columns, where n is something that does 90ish% of what's necessary without adding a million extra columns 

This seems like a really good solution. Nowadays you get a lot of multiple identifying agents (the ID is from a pub) and being able to add them at the first bulkload would be nice.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
@dustymc here is a file of guids and agents. It's pretty simple. All IDs for these guids with agent Brooklyn D. Armijo should be updated to add agent Jason Richard Moore. Thank you!

[Moore_81801-82068_updateID.xlsx](https://github.com/ArctosDB/arctos/files/9788085/Moore_81801-82068_updateID.xlsx)

> add identifier_n columns

This would be very helpful!

**Comment by dustymc** [comment]
Need more info - 165 of these have multiple IDs, I think maybe not intentionally?? https://arctos.database.museum/guid/NMMNH:Paleo:81905 for example - something mixed up or I'm just lost?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Yes, intentionally. Curator/student gave IDs of unidentifiable. I ID'd as vertebrate based simply on the fact that they are bones/teeth. If I'd had more foresight, I'd have substituted those in the initial bulkload, and cleanup would have been easier, but I didn't start this thread until after I'd bulkloaded and realized there was no easy way to add the second agent.

**Comment by dustymc** [comment]
Got it, thx.

This failed - already there I think

       guid        | identification_id 
-------------------+-------------------
 NMMNH:Paleo:81832 |          15418939


rest should be updated

>more foresight

The spice must flow....

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks!

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/5193
