### ISSUE TITLE
Arctos media links broken?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#5166]
Anyone else having trouble with Arctos being slow and not connecting? I've tried three different browsers to open the following link, and it just spins:
https://arctos.database.museum/media/10430897?open

**Comment by ebraker** [comment]
Yeah, I can't load Arctos - no error, just spinning.

**Comment by cjconroy** [comment]
Spinning for me too in Berkeley

**Comment by ebraker** [comment]
It's back!

**Comment by ebraker** [comment]
It worked for a bit but now I'm getting a 500 error
