### ISSUE TITLE
[ geography request ] Geographic Feature: Goblin Valley State Park

### ISSUE THREAD

**Issue by kderieg322079** [ArctosDB/arctos#5168]
We are conducting a small mammal survey in Goblin Valley State Park and need the following higher geography:

North America, United States, Utah, Emery County, Goblin Valley State Park

The park very recently [expanded its boundaries](https://stateparks.utah.gov/parks/goblin-valley/map/), so most polygons out there are no longer accurate, but it looks like most Geographic Features that are parks don't have spatial geography in Arctos. The park is still within just one county. For our first collecting trip in July, I assigned "Goblin Valley State Park" as the specific locality, but it would actually be most appropriate to be more specific since there were multiple traplines in different parts of the park, so the park name should be part of higher geography.

**Comment by dustymc** [comment]
Please see https://github.com/ArctosDB/arctos/issues/5138

https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=1004204 exists and should be used for cataloging.

If you can get the park's current spatial boundaries, send it to me and I'll make it into a Feature. That won't change what's appropriate for cataloging.
