### ISSUE TITLE
Geography request for BELL Museum, part 2

### ISSUE THREAD

**Issue by barke042** [ArctosDB/arctos#5169]
Hi, I just pre-bulkloaded a bunch of data and it spit back some higher geography terms that need fixing or that I found a bit confusing. I've attached a CSV with my notes on these. Three entries were just missing from higher geography where they shouldn't be; I have noted this in the CSV under NOTE, and request they be added. The others need clarification for me or correction in the database:

1) Kenya does not appear to have a continent? I input "Africa, Kenya" but that does not seem to exist at the moment, although I was grooming my data with a list previously provided by @dustymc.
2) Our data has an entry for "North America, United States, Virginia, Washington County", but Arctos recognizes "North America, United States, Virginia, Virginia, Washington County". Any idea what's going on there?
3) Vanuatu appears to be missing an ocean, requiring use of "Vanuatu" rather than "Pacific Ocean, Vanuatu". Is this correct?

BTW, will I have to restart the entire bulk upload if the missing geography terms are added? Or can I just fill in the added term in 'SHOULDBE' and it will be okay?

Thanks!

[geography_additions_queries_10_13_2022.csv](https://github.com/ArctosDB/arctos/files/9781470/geography_additions_queries_10_13_2022.csv)

**Comment by dustymc** [comment]
>Kenya does not appear to have a continent? 

Correct, see https://github.com/ArctosDB/arctos/issues/5138 - everything else will become GADMish too, but it'll take a while.

>Virginia, Virginia

Wut the wut?! I wiggled the wires and it seems to have fixed itself. Shoulda saved it for the spooky newsletter I suppose....

>Vanuatu

That one is very half-baked, 'Vanuatu' is correct, the rest will catch up. (And eventually all of the "rocky saltwater" weirdness/tradition will go away.)

>SHOULDBE

You should be able to iterate as many times as you want - upload new data, repatriate, rinse and repeat if necessary.

I'm scared to look at the UK in GADM, but if something's in GADM1 it can be created.

Note that GADM2 (excepting US) will be going away - just move that to specloc.

https://arctos.database.museum/editGeog.cfm?geog_auth_rec_id=10016606
[temp_geog_mn.csv](https://github.com/ArctosDB/arctos/files/9781542/temp_geog_mn.csv)

Lemme know what I missed, brain's a little mushy right now...
