### ISSUE TITLE
Code Table Request - new Other_ID = DOI

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#5173]
**Goal**
Add a new code table value: DOI

**Context**
I need this to add MorphoSource DOIs, e.g., [https://doi.org/10.17602/M2/M168689](https://doi.org/10.17602/M2/M168689)   (researchers can request MorphoSource to mint a DOI for media they've included in their published datasets). Since the MorphoSource DOI base path is https://doi.org/, we probably want this identifier to be generic ('DOI") instead of specific ('MorphoSource DOI')

**Table**
Other IDs

**Proposed Value**
DOI (base path https://doi.org/)

**Definition** Digital Object Identifier. A persistent identifier or handle used to uniquely identify various objects, standardized by the International Organization for Standardization. [wikipedia](https://en.wikipedia.org/wiki/Digital_object_identifier#:~:text=A%20digital%20object%20identifier%20(DOI,system%20(Uniform%20Resource%20Identifier).)

NOTE: An existing other_ID value, 'Dryad DOI', has the same base path (https://doi.org/) so we should either combine all DOIs into a single other_ID, or separate them all out for clarity, in which case I would advocate for a new value, MorphoSource DOI

**Comment by dustymc** [comment]
Wut? Just a synonym for the ARK for some reason?? No objections, I suppose, but this is the same link as the Media, no? I'm not sure what they're trying to do, which seems to be a common thing lately...

>Dryad DOI

https://github.com/ArctosDB/arctos/issues/2281 / https://github.com/ArctosDB/arctos/discussions/4969, that should have never been created, certainly not while ignoring the guidelines. Those should definitely be merged, whatever else happens. (About 99% of the point of DOIs is that they don't need to do what we've done...)

>same base path

Meh, a DOI resolver is (sorta/usually...) a DOI resolver, https://doi.pangaea.de/10.17602/M2/M168689

**Comment by Jegelewicz** [comment]
But also - #4604 to go with it!

**Comment by Jegelewicz** [comment]
@dustymc I have created DOI - can we migrate all Dryad DOI to it and then get rid of Dryad DOI?

**Comment by dustymc** [comment]
Merged.

@ebraker UCM:Herp:47446 has a bad DOI value and should be fixed.
