### ISSUE TITLE
tested for presence

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5174]
tested for presence is misconfigured and needs fixed

-------------

        I have put updating the ctattributes table on my to do later list for the moment.

As for:

> In https://arctos.database.museum/info/ctDocumentation.cfm?table=CTATTRIBUTE_TYPE + not in https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_code_tables ==> free text

this is true except for attribute "tested for presence", which actually gave me pause about formatting because I thought it would be as you say above until I saw that entry. So I will add that to the update list as well.

_Originally posted by @barke042 in https://github.com/ArctosDB/data-migration/issues/1141#issuecomment-1279848724_

**Comment by dustymc** [comment]
cleaned, I don't think this was intended to be free-text but that's how it was set up and that hasn't changed, but its manageable now. Control and values can be dealt with in https://github.com/ArctosDB/arctos/issues/5087

**Comment by jldunnum** [comment]
Yes, not sure why that went in the way it did originally. This could be looped into the current pathogen model. As it currently exists, SNV results (yes/no) is actually misleading. Anything with a value associated with it ("yes" or "no") has results (been tested). "yes" means positive and "no" means negative for SNV.

______________________________________________________________

Jonathan L. Dunnum Ph.D. (he, him, his)
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

Chair, Systematic Collections Committee, American Society of Mammalogists
Latin American Fellowship Committee, ASM

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by jldunnum** [comment]
OK, thought it was referring to the SNV data...

______________________________________________________________

Jonathan L. Dunnum Ph.D. (he, him, his)
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

Chair, Systematic Collections Committee, American Society of Mammalogists
Latin American Fellowship Committee, ASM

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by campmlc** [comment]
That's another relevant one. That's SNV positive or negative.
