### ISSUE TITLE
Geography Request - Chobe District

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5175]
# ~~Carefully read the documentation at https://handbook.arctosdb.org/documentation/higher-geography.html before submitting a request.~~ (Don't read that, it's out of date.)

# Carefully read The Plan at https://github.com/ArctosDB/arctos/issues/5138 before submitting a request.

### First Step: Explain what geography needs created.

Africa, Botswana, Chobe District - https://gadm.org/maps/BWA/chobe.html

Can we just create all districts of Botswana? https://gadm.org/maps/BWA_1.html

Explain in sufficient detail for us to locate standardized spatial data. A country is usually sufficient.

We will respond with a CSV template, or request more information.

**Comment by Jegelewicz** [comment]
Needed for UWZM:Bird Data Migration

**Comment by Jegelewicz** [comment]
Why does Botswana include continent (Africa), but Kenya doesn't?

![image](https://user-images.githubusercontent.com/5725767/196248081-78b95861-b045-4d74-a0be-a6413a7c4880.png)

![image](https://user-images.githubusercontent.com/5725767/196248185-0148cb7d-f87a-4c5d-bc26-39be7a5cc005.png)

**Comment by dustymc** [comment]
[temp_geog_botswana.csv.zip](https://github.com/ArctosDB/arctos/files/9803338/temp_geog_botswana.csv.zip)

Fill in  source_authority please.

>Why does Botswana include continent (Africa), but Kenya doesn't?

Because https://github.com/ArctosDB/arctos/issues/5138 is not an instantaneous process - I'll clean up the country when I add these.

**Comment by Jegelewicz** [comment]
UGH - this is going to forever plague incoming data that has already been matched to higher geography! People trying to load data today that was prepped last week now have  to re-do HG. Do we have an estimate of when the process may finish?

**Comment by Jegelewicz** [comment]
[temp_geog_botswana.csv](https://github.com/ArctosDB/arctos/files/9803417/temp_geog_botswana.csv)
