### ISSUE TITLE
Geography request - North America, Canada, Ontario, Elgin County

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5176]
# Carefully read The Plan at https://github.com/ArctosDB/arctos/issues/5138 before submitting a request.

### First Step: Explain what geography needs created.

Explain in sufficient detail for us to locate standardized spatial data. A country is usually sufficient.

North America, Canada, Ontario, Elgin County - https://gadm.org/maps/CAN/ontario/elgin.html
North America, Canada, Ontario, Perth County - https://gadm.org/maps/CAN/ontario/perth.html

Maybe just create all Ontario Counties? - https://gadm.org/maps/CAN/ontario_2.html

We will respond with a CSV template, or request more information.

**Comment by Jegelewicz** [comment]
Needed for UWZM:Bird data migration

**Comment by dustymc** [comment]
Please see https://github.com/ArctosDB/arctos/issues/5138

>level 2 (county) will be created by Community approval only when there is a special need and a significant history of stability. Currently United States is the only candidate for this treatment.

**Comment by Jegelewicz** [comment]
Canada is in GADM, seems stable and I think we should add them all since some of them are already there.

@mkoo @campmlc @ebraker @ehalverson26 

![image](https://user-images.githubusercontent.com/5725767/196251409-2ad63199-cbdb-489a-8b0b-8e07c9687892.png)

**Comment by dustymc** [comment]
I don't think Canada is particularly stable, and the current data is in serious need of cleanup (in no small part because Canada isn't particularly stable!). I don't think it's a good candidate for this. 

No objections to loading current gadm2 as FFFs, of course.

**Comment by Jegelewicz** [comment]
I don't really care either way - but let's get some consistency so that I can get this done.

**Comment by dustymc** [comment]
>I don't really care

Considering this a withdrawal of the request.
