### ISSUE TITLE
[CONTACT] How to mass update began dates and ID Date

### ISSUE THREAD

**Issue by lin-fred** [ArctosDB/arctos#5177]
I am looking to update the ID date and the event start date from 1800-01-01 to 1924-10-14 for these records: 
[ArctosDataWUA5sysXVk.csv](https://github.com/ArctosDB/arctos/files/9803505/ArctosDataWUA5sysXVk.csv)

How do I do that?

**Comment by lin-fred** [comment]
@dustymc when I try to search for the specimens, then do Manage - collecting events, I get this message: 
his form is temporarily disabled, please see https://github.com/ArctosDB/arctos/issues/4033

And when I go to the issue it doesn't really lead to what the solution is, do you know what I am supposed to use instead?

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/4033 is the hope that someone will find a use for an old form. This is a good example of what it can't do - some of the events may be used by records that aren't in your list, and some of the records in your list may have multiple events.

If you can get this down to a list of collecting_event_ids I can probably make the update pretty quickly, if not I'll get to it when I've got the brainpower to deal with the aforementioned available.

**Comment by Jegelewicz** [comment]
>  what to do with the ID date if it is unknown?

Remove it (ID date can be NULL - although deleting it might not work - I haven't tried it

**Comment by lin-fred** [comment]
I have been able to just edit the ID and remove the date and save, but I can't seem to batch remove them. But thank you! I will start leaving it blank if the date is unknown
