### ISSUE TITLE
geography cleanup: United Kingdom

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5178]
Ref https://github.com/ArctosDB/arctos/issues/5138 esp, "level 2 (county) will be created by Community approval only when there is a special need and a significant history of stability. Currently United States is the only candidate for this treatment."

I'm not sure what to do for UK.

Current Arctos data are https://arctos.database.museum/place.cfm?sch=geog&any_geog=united%20kingdom - we have lots of gadm2 stuff (sort by county).

GADM splits the UK into 4 levels, eg https://gadm.org/maps/GBR/england_2.html - England (gadm1) has 112 gadm2-things.

It's a small whatever-it-is, I'm tempted to follow the general rules and merge everything into the four "states," Scotland/Northern Ireland/England/Wales.

Those things are also a bit "country-like" for various reasons and there's probably some precedent to treating the gadm2-things like states (gadm1).

I suppose I'll go with the simpler approach and stop at gadm1 if nobody chimes in in the next week or so.

HELP!

@ArctosDB/geo-group 

users:

 @ebraker
 @Nicole-Ridgwell-NMMNHS
 @mkoo
 @AJLinn
 @campmlc
 @ccicero
 @amgunderson
 @atrox10
 @mvzhuang
 @cjconroy
 @jtgiermakowski
 @wellerjes
 @jebrad
 @jrpletch
 @AdrienneRaniszewski
 @aklompma
 @acdoll
 @jldunnum
 @jrdemboski
 @byuherpetology
 @msbparasites
 @genevieve-anderegg
 @jessicatir
 @kderieg322079
 @StefanieBond
 @sharpphyl
 @catherpes,@catherpes
 @marecaguthrie
 @gracz-UNL
 @lin-fred
 @adhornsby
 @jcabbott72
 @Jegelewicz
 @kmkocot
 @jandreslopez
 @droberts49
 @SerinaBrady

**Comment by sharpphyl** [comment]
I vote to extend "level 2" entities to the United Kingdom.  We'd give up a ton of data without counties, parishes, etc.  They're probably as stable as the US counties, if that's the major concern.

**Comment by dustymc** [comment]
> extend "level 2" entities

I think I generally agree, but...

>We'd give up a ton of data

Definitely not, WHATEVER we do will be a move, not a loss.

> if that's the major concern

Stability is part of it. I'm not sure where the line is, I looked up a couple and found

*created 1974, renamed 1997 - https://en.wikipedia.org/wiki/Blackburn_with_Darwen
* created 1965: https://en.wikipedia.org/wiki/London_Borough_of_Sutton

so yea, probably about like the US - far from stable, still about as good as it gets.

**Comment by ewommack** [comment]
> They're probably as stable as the US counties, if that's the major concern.

It might be nice to have the "level 2" present as well in case of the "level 1" groups separate out and become their own country.

**Comment by ewommack** [comment]
Haha, no not quite. I just studied politics in Scotland right after the formation of the Scottish Parliament and devolution of Scotland, Wales, and NIreland. They're pushing for another vote on whether Scotland should become an independent country right now, and you never know.
