### ISSUE TITLE
Code Table Request - merge tooth set into part modifier

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#5179]
**Goal**
Simplify part attributes by merging tooth set into part modifier.

**Context**
I _think_ that tooth set is currently being used to record only one or two values - "deciduous" and maybe "permanent" or "adult"- although it is an open text field, so I'm not sure what else may have gotten in there. Merging these values into part modifier would not only simplify things, but it would turn these values into code table controlled values.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecpart_attribute_type
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_modifier

**Proposed Value**
Add to part modifiers the value "deciduous" and possibly something for permanent/secondary/adult teeth that would not be ambiguous.

**Proposed Definition**
The first set of teeth in the growth and development of diphyodont mammals. [Wikipedia](https://en.wikipedia.org/wiki/Deciduous_teeth)

**Comment by dustymc** [comment]
Agree, this should be merged. The data are all yours, so just propose/implement values/definitions and let me know or use the bulkloaders to migrate.

I will need to remove the old table, please don't let me wander off before that's done.

```
 select guid_prefix,
arctos-> count(*) from temp_toothset group by guid_prefix;
 guid_prefix | count 
-------------+-------
 NMMNH:Paleo |   664
(1 row)

Time: 1.419 ms
arctosprod@arctos>> select attribute_value from temp_toothset group by attribute_value;
 attribute_value 
-----------------
 decidouous
 Deciduous
 deciduous
 senile
(4 rows)

```

**Comment by Jegelewicz** [comment]
This sounds good - it seems like deciduous and permanent are the usual terms. Adult seems problematic due to confusion with age classes.

[permanent teeth](https://en.wikipedia.org/wiki/Permanent_teeth)

**Comment by Jegelewicz** [comment]
@Nicole-Ridgwell-NMMNHS can we come up with definitions for deciduous and senile (and hopefully those are the only two terms in use?

deciduous - The first set of teeth in the growth and development of diphyodont mammals. [Wikipedia](https://en.wikipedia.org/wiki/Deciduous_teeth)

permanent - the second set of [teeth](https://en.wikipedia.org/wiki/Tooth) formed in diphyodont mammals. [Wikipedia](https://en.wikipedia.org/wiki/Permanent_teeth).

good?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Sorry I haven't had the bandwidth to get back to this. I don't think senile needs its own value. I will change the one record that uses it. We're not using permanent at this point, I'd say lets just migrate the deciduous value and call it good. I am fine with your definition for deciduous.

**Comment by Jegelewicz** [comment]
@dustymc do you want me to file a new code table issue or can we just roll with this one (is NMMNH:Paloe still the only collection involved?)

**Comment by dustymc** [comment]
>still the only collection

Yes, and can we move on this while that's still the case?

```

 guid_prefix | count 
-------------+-------
 NMMNH:Paleo |   669


 attribute_value 
-----------------
 decidouous
 Deciduous
 deciduous
(3 rows)


```

**Comment by dustymc** [comment]
Fixed some spelling variations, updated, cleaned up.

[temp_toothset.csv.zip](https://github.com/ArctosDB/arctos/files/13709148/temp_toothset.csv.zip)

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thank you!
