### ISSUE TITLE
Ampersand in preferred agent breaks data entry form 

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#5182]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
In the new data entry form, if you select an agent whose preferred name has an ampersand (&),  you are unable to save the record. You also can't edit the entry using the new edit page (you can fix it, apparently, in the old edit page). As of right now, our operators must enter "unknown" as the agent, load it, and then go in and edit the agent to add the preferred agent with ampersand.

**Expected behavior**
According to the handbook [best practice - Creating Meaningful Agents](https://handbook.arctosdb.org/best_practices/Agents.html):
"Do include symbols and their alternatives where users might search by either. For preferred name “Smith & Wesson,” also include name “Smith and Wesson.” (It doesn’t matter which goes where, as long as both are included with the agent.)"

Based on that last sentence, I would expect to have the preferred name with the ampersand save properly into the data entry form.

**Screenshots**

![image](https://user-images.githubusercontent.com/17605945/196567735-5e9694d4-32be-4c58-8d19-044f40806fd4.png)

![image](https://user-images.githubusercontent.com/17605945/196567715-4cdb7a0d-0830-49b7-9ff2-ce5391e5c631.png)

**Priority**
High priority
Thank you!

**Comment by dustymc** [comment]
Patched. For whatever reason at least FF is doing things differently if it thinks there's a human involved vs. when automation. The auto-use-one thing now only works if there is not an ampersand in the preferred name; passing those off to humans for button-clicking seems to get everything back to functional.
