### ISSUE TITLE
Agent Merge Request - Henry Messing

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#5183]
Use this template when you discover two agents that you believe represent the same person or organization.

**Agent that should remain after the merge**
This agent should represent the same person or organization as the agent below, but be of higher quality (more complete name, or includes additional information such as dates, relationships, addresses). Navigate to the agent page, copy the url and paste it below:
Henry J. Messing

**Agent that will no longer remain after the merge**
This agent should be of lower quality than the agent into which it will be merged. Navigate to the agent page, copy the url and paste it below:

Henry Messing

**Reason for merge**
Please provide the reason you believe that these two agents represent the same person or organization.
Pretty sure these are the same Messings. Messing became reclamation biologist in Arizona. Same birth year and full name in El Paso and Arizona.

Please add this issue to the Agents Project

@ArctosDB/agents-committee

**Comment by lin-fred** [comment]
@jldunnum looks like Henry Messing is used in your collection

**Comment by jldunnum** [comment]
Thanks Lindsey, yes should be OK to merge

______________________________________________________________

Jonathan L. Dunnum Ph.D. (he, him, his)
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

Chair, Systematic Collections Committee, American Society of Mammalogists
Latin American Fellowship Committee, ASM

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by mvzhuang** [comment]
Done. Thanks all!
