### ISSUE TITLE
Recently updated private locality data showing on search results when logged out

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#5187]
**Describe the bug**
I discovered during some data cleaning today that localities with access = nmmnh_paleo are showing data in public search results. This appears to ONLY be happening for localities that have been recently edited.

**To Reproduce**
1. I've been updating/cleaning localities today that fall under the criteria (locality name: NMMNH:Paleo, landholder: US Bureau of Reclamation)
2. I happened to be looking at some of the records associated with these localities which led me to run a search for part remark: opalized.
3. The search results showed some specimens with the usual encumbered locality message, but two of them, the ones who's localities had been updated, showed the actual specific locality and coordinates. I thought that was weird.
4. So I logged out and ran the same search and the specific locality and exact coordinates are still showing.
5. I've double checked that the locality access didn't get deleted.
6. Logged out, the data is not visible in the record view, just the search results.

**Expected behavior**
This data should be visible only to NMMNH:Paleo collection users and definitely should not be visible to the public.

**Screenshots**
Not included because of the sensitive data. I can email if they are necessary.

**Comment by dustymc** [comment]
Send me a GUID. I suspect the cache has a lag because I'm updating geography plus the normal load, but I can look if I have something to check.

**Comment by campmlc** [comment]
@Nicole-Ridgwell-NMMNHS you may want to encumber these records asap until resolved.

**Comment by dustymc** [comment]
Thx, please see if you can find anything you shouldn't for that record, then I'll set the rest to refresh. I missed a function with the private/collection attribute update, I think I've got it, would like to confirm before locking everything up for a few hours.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I've checked that record, adding any data fields that might have sensitive locality information. All the fields are now showing the public locality information, both logged out and logged in with a non-operator account.

**Comment by dustymc** [comment]
OK, thanks, full update running - you can check progress in the usual spot (reports/stats).

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks!

**Comment by dustymc** [comment]
Cache seems to be caught up
