### ISSUE TITLE
nonfatal error when deleting unused localities

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#5188]
**Describe the bug**
Deleting an unused locality gets you error obnoxiousness. Error pasted below

**To Reproduce**
1. Go here: https://arctos.database.museum/editLocality.cfm?locality_id=10097864
2. Click on DELETE
3. Enjoy

**Expected behavior**
A reward for sweeping away unused locality detritus, which is not forthcoming

Instead there's this:
<div style="border:2px solid green; padding: 1em; margin: 1em; text-align: center;"></div>
        

ERROR_ID | E300E04B-68ED-4A0E-B1BCD11F916C1C30
-- | --
ERROR_TYPE | SQL
ERROR_MESSAGE | ERROR: Geography is not assertable.   Where: PL/pgSQL function trigger_fct_tr_locality_bud() line 42 at RAISE
ERROR_DETAIL |  
ERROR_SQL | delete from locality where locality_id=10097864

</div>

<p>request dump:</p>

        

<div id="x3w34" class="-lucee-dump">

request
--
node_name | stringarctos-2021 | string | arctos-2021
string | arctos-2021
rdurl | string/editLocality.cfm?deleteLocality&10097864 | string | /editLocality.cfm?deleteLocality&10097864
string | /editLocality.cfm?deleteLocality&10097864
uui | string | string |  
string |  
uuid | stringE300E04B-68ED-4A0E-B1BCD11F916C1C30 | string | E300E04B-68ED-4A0E-B1BCD11F916C1C30
string | E300E04B-68ED-4A0E-B1BCD11F916C1C30

</div>

**Comment by dustymc** [comment]
de-derped, thx
