### ISSUE TITLE
Curatorial Search Request/ container update

### ISSUE THREAD

**Issue by mabreslin** [ArctosDB/arctos#5190]
I am trying to find all UAM:Herb 'specimen labels' so that they can be changed to 'herbarium sheet'. I was able to find aprox. 4000 and have changed them already, however barcode H1095419 and many others still exist as 'specimen label' 

If you could please include in results:
GUID, barcode, and container type

**Comment by dustymc** [comment]
>GUID

There can be none, https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcontainer_type

>UAM:Herb

Containers are partitioned by institution.

>container type

That's the query.

Try this in writesql, and let me know if it's not what you need.
```
select barcode from container where institution_acronym='UAM' and container_type='specimen label' and barcode like 'H%'
```

**Comment by mabreslin** [comment]
Thank you, that did the trick!
