### ISSUE TITLE
Code Table Request - Places of birth, death, and activity for agent profile

### ISSUE THREAD

**Issue by krgomez** [ArctosDB/arctos#5191]
**Goal**
[ Describe what you're trying to accomplish. ]
Have a specific field in the agent profile to record the places of birth, death, and activity.

**Context**
[ Describe why this new value is necessary and existing values are not. ]
I have been using the remarks field for agent status to record the places of birth and death for an agent. However, I am now also using the remarks field to record the source of publication for the birth year of living agents (Wikipedia, artist's website, etc). It makes sense to have a designated field to record place information, so that the remarks field can be used for supplementary notes. For art and cultural collections, the places of birth and death of an artist are important biographical details. Furthermore, it would also be helpful to be able to record when and where an agent was active.

**Table**
[ Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table you are requesting changes to here. ]
Agent status

**Proposed Value**
[ Proposed new value ]
My suggestion is to add another field called "place" for agent status, in addition to the date and remarks fields.

For agent activity, we would optionally need the ability to record a date range, so I'm not sure "active" could simply be added to the agent status code table. Maybe there is a way to have begin and end date boxes when a particular agent status value is selected?

**Available for Public View**
[  **Yes | No** to indicate whether the proposed value will be available for public view or available only for logged in operators.  ]
No

**Comment by dustymc** [comment]
merge --> https://github.com/ArctosDB/arctos/issues/5172
