### ISSUE TITLE
Feature Request - picks should include definitions

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5192]
**Is your feature request related to a problem? Please describe.**

Don't show values without supporting definitions.

**Describe what you're trying to accomplish** 

Don't let people guess what values mean.

**Describe the solution you'd like**

Rebuild picks to include definitions

**Describe alternatives you've considered**

-

**Additional context**

part picks, but important everywhere

**Priority**

?

**Comment by Jegelewicz** [comment]
High priority for @ArctosDB/arctos-code-table-administrators who want to ensure those entering data can pick appropriate terms - see #5186
