### ISSUE TITLE
How to create verbatim Agent

### ISSUE THREAD

**Issue by catherpes** [ArctosDB/arctos#5194]
In creating agents, there is no obvious way to create a verbatim agent, although the database clearly is encouraging it. How about a link to documentation on 'how to create a verbatim agent' where it now only links to what a verbatim agent is? 

Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

**Describe what you're trying to accomplish** 
An clear and concise overview of the goals; why are you asking for this?

**Describe the solution you'd like**
How might we accomplish your goals?

**Describe alternatives you've considered**

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by dustymc** [comment]
<img width="871" alt="Screen Shot 2022-10-20 at 3 26 28 PM" src="https://user-images.githubusercontent.com/5720791/197070778-8a5ca8ea-59ef-4880-a21b-ac74ecfa664d.png">

That's it - supply attribute type and value.

**Comment by ewommack** [comment]
@lin-fred just tagging this for the agents committee for documentation, reminder, newsletter, tutorial, etc use later.

**Comment by catherpes** [comment]
What does that look like in a bulkloading situation when Some Name collected a specimen?

**Comment by dustymc** [comment]
<img width="759" alt="Screen Shot 2022-10-20 at 6 07 01 PM" src="https://user-images.githubusercontent.com/5720791/197087756-6e083144-2696-4f69-8565-9a6d4ee5dbdf.png">

**Comment by catherpes** [comment]
thanks

**Comment by lin-fred** [comment]
https://handbook.arctosdb.org/documentation/agent.html#verbatim-agent-attribute there is documentation here as well, so I will close this for now.
