### ISSUE TITLE
clarify bulkloader requirements

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5196]
* check documentation
* make sure the pre-bulkloader is clear about what's required
* revisit defaults

        > Often from bad/no documentation - please feel free to leave an Issue in https://github.com/ArctosDB/documentation-wiki/issues if you think that might be the case.

I had a vague recollection so I looked back at the documentation and indeed [this page](https://handbook.arctosdb.org/documentation/bulkloader.html#fields) claims that "At least one part is required.". It also claims that "At least one collector_agent is required.". Similarly, the bulkloader builder includes both collector_agent_1 and part_name_1 in the list of "required" fields. Seeing all of that, and also that the pre-bulkloader was set to replace NULL values for part and collector with "unknown", I left those in place even though the header for step 13 of the pre-bulkloader indicates that these can be erased as necessary. 

If it is the case that parts are unnecessary on initial upload, is the same true for agents? If so, then I have a lot of unnecessary 'unknown' agents that will need to be wiped out. Maybe we could do that after I've assigned agents for those that I'm going to?

_Originally posted by @barke042 in https://github.com/ArctosDB/data-migration/issues/1141#issuecomment-1286213358_

**Comment by Jegelewicz** [comment]
@dustymc I also added that here https://github.com/ArctosDB/documentation-wiki/issues/277 for the documentation stuff

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/5193
