### ISSUE TITLE
Account locked

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#5199]
My account locked after just a couple of failed login attempts. Can NICOLERIDGWELL please be unlocked?

**Comment by dustymc** [comment]
reset

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks!

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I fiddled with some browser settings, maybe that will make a difference.
