### ISSUE TITLE
Stuck in bulkloader

### ISSUE THREAD

**Issue by jebrad** [ArctosDB/arctos#5203]
@Jegelewicz - finally getting back to this.  

This file made it through the pre-bulkloader, but then at "load all" it returned this error.
[BulkPendingData_JEB.csv](https://github.com/ArctosDB/arctos/files/9847187/BulkPendingData_JEB.csv)

ERROR_ID | 5CD51B70-FB7D-45E8-BEB563345433BBAF
-- | --
ERROR_TYPE | SQL
ERROR_MESSAGE | ERROR: new row for relation "bulkloader" violates check constraint "ck_part_remark_1_noprt"
ERROR_DETAIL |  
ERROR_SQL | insert into bulkloader select * from bulkloader_stage

Thanks for any advice -
Jeff

**Comment by dustymc** [comment]
Both the pre-bulkloader and the normal upload/check process should handle this. If you clicked the 'yea yea load anyway' option then you've explicitly bypassed the check that will find this problem. If you got here in any other way, please elaborate.

**Comment by jebrad** [comment]
OK all my dates are invalid.
[bulkloader_datawitherrors.csv](https://github.com/ArctosDB/arctos/files/9852937/bulkloader_datawitherrors.csv)

So my settings are wrong in how I am saving the csv?   I will try to find that in our earlier thread.

**Comment by acdoll** [comment]
If you open your .csv file in Excel and re-save, it usually reformats your dates. If I need to make minor edits to the data prior to upload (often to fix issues found by Arctos during first upload attempt), I usually use a text editor to avoid this issue.

**Comment by jebrad** [comment]
Thanks - I had to do major edits, so used Excel.
But I just found this advice from @Jegelewicz 
"When you get ready to save the csv - make sure that you save as CSV UTF-8" 
I just re-tried to bulkload after making sure I saved it that way- and got the same date errors. Unless it was important that I re-saved it that way each time.  I'll go look for the original file from Teresa now.

**Comment by campmlc** [comment]
I save as plain csv but I also make changes first to my xlsx file and
re-export as csv.

**Comment by dustymc** [comment]
https://handbook.arctosdb.org/documentation/dates.html#excel-hates-me-help

**Comment by acdoll** [comment]
I noticed some year-only dates in some of the fields in your file. Be careful with these, Excel will interpret these as 'days since 1900-01-01'. So the year 2005 will become 1905-06-27. We usually default to the latest possible value for these (e.g., 2005-12-31).

**Comment by dustymc** [comment]
@acdoll you should add that to the docs somewhere - I certainly had no idea (but I refuse to use Excel because 'Excel will interpret' so whatever...)

**Comment by jebrad** [comment]
OK excellent, excel-hates-me-help gave enough advice for me to fix the dates.

Now my main problem is "collecting_source (wild caught) is invalid" so I will work on that.

**Comment by jebrad** [comment]
OK got them all into the Bulkloader.  Will go delete from the staging table.  Thanks for all the help.
