### ISSUE TITLE
Feature Request - add media (thumbnail) to reports table to preview

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#5205]
Let's make reports and labels more user friendly

**Describe what you're trying to accomplish** 
Most of the time you set it and forget it-- but when trying to see which report or label you need or need to customize for your collection it's difficult to figure that out without a picture from the Report table (https://arctos.database.museum/Reports/reporter.cfm)

Solution: Create a bunch of generic templates for people to copy and use. Add in the new feature of a media link so we can add in a thumbnail. Workaround: edit the description box wiht html (e.g., "src={image link}")

**Comment by dustymc** [comment]
Are you asking for media.media_id or 'preview_image TEXT'? (I think the latter might be more approachable for users??)

**Comment by mkoo** [comment]
I'm not sure -- the preview probably would be easier on user-- but what about the dude who has to implement?

**Comment by dustymc** [comment]
semi-controlled text (url) is OK
