### ISSUE TITLE
Minimum permission needed to print reports?

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#5206]
This is not clear from database roles (https://arctos.database.museum/Admin/user_roles.cfm)
thanks

**Comment by dustymc** [comment]
Roles will determine what's required to access data (and may vary from report to report, and can mostly/probably be ignored).

Accessing them reports themselves requires only coldfusion user; you can check that via....

<img width="372" alt="Screen Shot 2022-10-24 at 4 29 02 PM" src="https://user-images.githubusercontent.com/5720791/197649139-e824d4e6-01e5-4a16-9a1b-df278e0e87eb.png">

**Comment by mkoo** [comment]
well printing from the manage dropdown is slightly different that accessing
that .CFM
So wasnt sure about that.
I guess we'll find out with the student but does make sense
thanks
