### ISSUE TITLE
locality attribute: feature

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5207]
Someone will want them, so I'm creating a new locality attribute 'feature' using https://arctos.database.museum/info/ctDocumentation.cfm?table=ctfeature, and will use it for ~~North America~~ geography [cleanup](https://github.com/ArctosDB/arctos/issues/5138).

Timely naming suggestions appreciated, and that can be adjusted at any time.

Strongly suggest that whatever's important be created as a FFF and accessed spatially; I'll keep what I can as such, but many of these are only vague descriptors.

I can help remove these for anyone who doesn't want them.

**Comment by Jegelewicz** [comment]
@camwebb using the locality attribute makes it easier to find all the stuff from a park, however getting a spatial footprint and creating a geography FFF will make it even easier.

**Comment by dustymc** [comment]
The locality attribute is the most formal way to make an assertion.

Specloc (which will accept DNP instead of requiring "Denali National Park") is probably sufficient if you don't need to be quite so formal.

You can use spatial queries to find things that map to the park, no matter what's been asserted.

https://handbook.arctosdb.org/how_to/How-to-understand-the-Arctos-Locality-Model.html#geography-model

**Comment by dustymc** [comment]
>So users will have to request new FFFs?

For now - yes. Going forward I'm very up for ideas, but we do need to have a conversation about resources before we get TOO crazy.

I did save everything I could eg 

https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10016786

https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10016787

but that's a bit spotty (and might not be great quality, I think those were passed around as WKTs).
