### ISSUE TITLE
reporter: templates

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5208]
Somehow break uneditable (unless you are @lkvoong) templates out into their own section

**Comment by dustymc** [comment]
better idea: new type 'template' with 'unless lam then nope' check to disallow editing

**Comment by mkoo** [comment]
I would make sure more than one (@lkvoong plus friends) can create and edit template-- a few super users basically

**Comment by mkoo** [comment]
what does Protected_template= true/false indicate in the updated reporter?

**Comment by dustymc** [comment]
>what does Protected_template= true/false indicate 

True: 

1. Adds a style in the tables
2. Sorts first by default,
3. Prefixes report type with 'template'
4. Disallows changes except by global_admin users
5. Doesn't make cloning more complex than I can deal with, unlike the original idea
6. Allows protected templates to be used like any other report


<img width="1318" alt="Screen Shot 2022-10-28 at 4 45 29 AM" src="https://user-images.githubusercontent.com/5720791/198579768-7678013d-3914-409b-bf8b-7b27b934f07c.png">
