### ISSUE TITLE
relabel reporter

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5209]
legacy - move it to bottom

HTML/CFML/CSS report printer --> Reporter

@mkoo @campmlc @Jegelewicz

**Comment by dustymc** [comment]
hide this stuff, esp, if there are no variables available

```
 NOTE: The open+debug option simply sets variable 'debug' to 'true.' Reports may access this variable for eg printing debug code. If there's no "if debug..." code in the report, this will work exactly like 'open.'

Filtering for reports with accepts_variable ()
No suitable reports found 
```

**Comment by Jegelewicz** [comment]
# Arctos Report Builder
Copy templates and modify to create custom reports in Arctos. If there isn't a template that meets your needs and you don't want to attempt to build a report from scratch, file an issue.

# Legacy Report Builder
 
The Legacy Arctos Report Builder lives on a different server. You must get there directly from here, or you will not be properly authenticated.

IMPORTANT: Arctos is transitioning away from CFR reports, which have been deprecated. All new reports should be developed using the Arctos Report Builder, and all existing reports must be transitioned. Jump right in below, or contact @lkvoong on GitHub for help and support.

Click this to continue to the legacy reporter: http://reports.arctos.database.museum/reporter/report_printer.cfm?auth_key=4B3C6739-88AA-458A-8FDD8884B3ADD895

**Comment by dustymc** [comment]
>Builder

It's also printer, downloader, and potentially lots more things.

**Comment by mkoo** [comment]
Arctos Report Builder

how about:

Access all reports and labels here. Generate or Copy templates and modify them to create custom reports in Arctos. If there isn't a template that meets your needs and you don't want to attempt to build a report from scratch, [file an issue](https://github.com/ArctosDB/arctos/issues/new?assignees=lkvoong&labels=function-Reports&template=report-template-request.md&title=New+Arctos+Report+Template+Request).

**Comment by campmlc** [comment]
Looks great. Add links to handbook and help docs.

**Comment by mkoo** [comment]
cool!
