### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by genevieve-anderegg** [ArctosDB/arctos#5212]
Unable to log in to Arctos, username: ganderegg
Regular password not working, tried resetting password, temporary password sent to email not working.
OS: both Mac and Windows
Browser: Chrome

Error message: "Authentication Failed. Additional Information: Access Restricted"

**Comment by mkoo** [comment]
I just reset your attempts-- somehow you were up to 11 failed logins.
Try #12 Genna!

**Comment by genevieve-anderegg** [comment]
YAY thank you so much Michelle! Mission success
