### ISSUE TITLE
Can't log in to test

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5215]
Log in attempt results in

![image](https://user-images.githubusercontent.com/5725767/198072083-3f506d06-b1ce-4198-b2f5-1c2a5cba8f5e.png)

from https://arctos-test.tacc.utexas.edu/

**Comment by Jegelewicz** [comment]
Logged in with reset - went to profile and changed password, seemed like it worked, but now only getting 404 and this

![image](https://user-images.githubusercontent.com/5725767/198078636-1b8d101f-a782-46f0-b4ea-56bda2cb021b.png)

**Comment by Jegelewicz** [comment]
guess some link is pointing the wrong way.

**Comment by dustymc** [comment]
https://arctos-test.tacc.utexas.edu

(Making the nice URL functional is between ya'll and TACC.)

**Comment by mkoo** [comment]
what happened to the other test site which was under the subdomain 'test'?
Did it never get used after all the TACC server moves over the summer? In teresa's screenshot, it looks like the url is still active....

**Comment by dustymc** [comment]
>what happened

Not sure, last I heard bringing it back was imminent.
