### ISSUE TITLE
Old Reporter Error

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#5216]
I'm trying to print the DZTB report for the following records: https://arctos.database.museum/saved/1666799254700.
The old reporter doesn't seem to like my data; is this an issue with the quotes in my Specimen Remarks?:
![image](https://user-images.githubusercontent.com/12507297/198072891-9cc77d68-1ecd-477e-8926-238142519095.png)
![image](https://user-images.githubusercontent.com/12507297/198074280-04447448-c53c-4cde-b789-30787d799b2a.png)

**Comment by dustymc** [comment]
<img width="299" alt="Screen Shot 2022-10-26 at 8 52 43 AM" src="https://user-images.githubusercontent.com/5720791/198074877-d22e6e2e-8f6f-4320-834b-a18b6b8ca970.png">

It's expecting ``collection_object_id`` and not getting it. You might change it to use ``#table_name#`` - I can help, but will need more detail.

**Comment by acdoll** [comment]
Isn't that the first thing pulled in the sql:
SELECT
flat.collection_object_id, 
flat.cat_num, 
flat.scientific_name,
flat.ACCESSION accn_number, 
flat.higher_geog, 
flat.spec_locality, 
flat.VERBATIM_LOCALITY,
flat.COLLECTING_METHOD,
flat.COLLECTING_SOURCE,
    flat.VERBATIM_DATE, 
    flat.BEGAN_DATE,
    flat.ENDED_DATE,
flat.collectors,
flat.remarks,
flat.minimum_elevation,
flat.orig_elev_units,
round(dec_lat::numeric,5) DEC_LAT,
round(dec_long::numeric,5) DEC_LONG,
concatsingleotherid(flat.collection_object_id,'preparator number') as preparator_number,
concatsingleotherid(flat.collection_object_id,'original identifier') as original_identifier,
concatsingleotherid(flat.collection_object_id,'secondary identifier') as secondary_identifier,
concatsingleotherid(flat.collection_object_id,'DZTB: Denver Zoology Tissue Bird') as DZTB,
concatsingleotherid(flat.collection_object_id,'field number') as field_number,
concatsingleotherid(flat.collection_object_id,'collector number') as collector_number,
concatsingleotherid(flat.collection_object_id,'GWRC: Greenwood Wildlife Rehabilitation Center') as GWRC,
concatsingleotherid(flat.collection_object_id,'RMRP: Rocky Mountain Raptor Program') as RMRP,
flat.habitat
FROM
flat
WHERE
flat.collection_object_id IN (#collection_object_id#)
ORDER BY
cat_num

**Comment by dustymc** [comment]
Yes, the variable isn't being set. (I have vague memories of the long list breaking something at TACC a while back.)

**Comment by acdoll** [comment]
Why does the #collection_object_id# disappear from the sql on the error page. When I changed that to #table_name# it remains there in the error:
![image](https://user-images.githubusercontent.com/12507297/198080880-97e85ab6-7837-4efa-9435-fbf3fa4374e5.png)
(I know that's not exactly what you meant, but I thought I'd see what happened)

**Comment by dustymc** [comment]
It's evaluated.

?collection_object_id=123-->123

**Comment by acdoll** [comment]
so, is there something else I should put in instead of #collection_object_id#? we use that in all of our reports.

**Comment by dustymc** [comment]
https://handbook.arctosdb.org/documentation/reports.html#accepts-variable

```
....
flat.habitat
FROM
flat
inner join #table_name# on flat.collection_object_id=#table_name#.collection_object_id
ORDER BY
flat.cat_num

```

**Comment by acdoll** [comment]
Still not quite there
![image](https://user-images.githubusercontent.com/12507297/198100147-6c99366b-4918-49be-8c24-4c263b868c7b.png)

**Comment by dustymc** [comment]
Your saved search and my guess at the report got me something.

<img width="1028" alt="Screen Shot 2022-10-26 at 10 56 35 AM" src="https://user-images.githubusercontent.com/5720791/198101027-8e37f6c5-e2e7-439d-a31e-8cda733ded89.png">

**Comment by acdoll** [comment]
That's the one, but I can't get it to work. I tried multiple browsers just to be sure, same result.
![image](https://user-images.githubusercontent.com/12507297/198108158-84b399dc-25c1-408a-98cb-cbbf17ec50d7.png)

**Comment by acdoll** [comment]
Now I can't get to that server:
![image](https://user-images.githubusercontent.com/12507297/198108373-1553077b-97d3-459d-9f7e-9ea3ab452ed6.png)

**Comment by dustymc** [comment]
>That's the one, 

I'm not so sure about that... - drop the comma after flat

The other thing is usually from too many tabs - you have to follow your last authentication token.

**Comment by acdoll** [comment]
> usually from too many tabs

might have been from being logged in on different browsers, too (?). Logging out of everything then back in (just once) seemed to work.

> drop the comma after flat

I had added that after trying it without. I've removed it but still am getting the earlier error.
![image](https://user-images.githubusercontent.com/12507297/198112140-420b549b-6906-471a-9021-d158802324cc.png)

**Comment by dustymc** [comment]
I think you're going to have to share the name of the report if I'm to figure this out.

**Comment by acdoll** [comment]
DZTB or DMNS_DZTB.cfr

**Comment by acdoll** [comment]
Ah, you may have used DMNS_DZTB_prepped.cfr - that one does work for me. I don't seem much difference in the handlers. I'm sure I just copied the DMNS_DZTB.cfr handler and added a few things to make DMNS_DZTB_prepped.cfr

**Comment by acdoll** [comment]
I just pasted in the end of the 'prepped' handler in to the original DZTB and now it works. I see no difference other than the indents:

original, non-functional handler for DMNS_DZTB.cfr:
FROM
flat
WHERE
flat.collection_object_id IN (#collection_object_id#)
ORDER BY
cat_num

new, functioning handler for DMNS_DZTB_prepped.cfr:
FROM 
    flat 
WHERE  
    flat.collection_object_id IN (#collection_object_id#)
ORDER BY 
    cat_num

**Comment by acdoll** [comment]
Did you change anything else? Before all of our reports were giving a similar error. Now they seem to be working (no changes to their handlers).

**Comment by dustymc** [comment]
Nope....

**Comment by acdoll** [comment]
shurg... Thanks for your assistance!

**Comment by dustymc** [comment]
Sure, let me know if you need me to do nothing while something magically fixes itself again....
