### ISSUE TITLE
Catalog records not updating properly

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#5218]
Example: https://arctos.database.museum/guid/CHAS:Teach:E2022B.81

Yesterday, I updated the identification for this catalog record. I went to print an updated label and noticed it wasn't pulling the new identification. In the search results, it still shows up at the previous identification, as well as under the catalog number on the record page. But the updated identification is showing.

At first I thought it might be Arctos is being slow on refreshing, but I went to print the label again today and the issue is still there. This is not the only catalog record I've noticed this on. So far, I've only noticed it with taxonomy.

**Comment by dustymc** [comment]
duplicate-->https://github.com/ArctosDB/documentation-wiki/issues/279
