### ISSUE TITLE
Code Table Request - Add new lithostratigraphy and informal chronostratigraphic units

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#5219]
**Goal**
Add lithostratigraphy necessary for new localities

**Context**
I am adding a group of new localities, many of which have geology that is not in the code tables.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctchronostrat_informal
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlithostratigraphic_formation
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlithostratigraphic_member

**Proposed Values and Definitions**
**Informal Chronostratigraphy**
**Osagean (Series/Epoch)**: A North American subdivision of the Mississippian. [Wikipedia](https://en.wikipedia.org/wiki/Mississippian_(geology))

**Formations**
**Genesee Formation**: A Devonian unit that outcrops in the Appalachian basin. [Geolex](https://ngmdb.usgs.gov/Geolex/Units/Genesee_1776.html)
**Edwardsville Formation**: A Mississippian unit, predominantly siltstone, sandy shale, and sandstone, that outcrops in Indiana. [Geolex](https://ngmdb.usgs.gov/Geolex/Units/Edwardsville_1505.html)
**Great Blue Limestone Formation**: A Mississippian unit that outcrops in Utah and Idaho. [Geolex](https://ngmdb.usgs.gov/Geolex/Units/GreatBlue_8474.html)
**Warsaw Formation**: A Mississippian unit, predominantly limestone, shale, and siltstone that outcrops primarily in the Illinois basin. [Geolex](https://ngmdb.usgs.gov/Geolex/Units/Warsaw_4300.html)
**Harrodsburg Limestone**: A Mississippian unit that outcrops in Indiana and Kentucky. [Geolex](https://ngmdb.usgs.gov/Geolex/Units/Harrodsburg_1992.html)
**Ludlowville Formation**: A Devonian unit, predominantly shale and siltstone, that outcrops in the Appalachian Basin. [Geolex](https://ngmdb.usgs.gov/Geolex/Units/Ludlowville_2564.html)

**Members**
**Ithaca Member**: A Devonian unit, predominantly shale, that outcrops in New York. [Geolex](https://ngmdb.usgs.gov/Geolex/Units/Ithaca_13265.html)
**Fraileys Shale Member**: A Mississippian unit that outcrops in Illinois, Kentucky, and Missouri. [Geolex](https://ngmdb.usgs.gov/Geolex/Units/Fraileys_1722.html)
**Wayland Shale Member**: A Pennsylvanian unit that outcrops in Texas. [Geolex](https://ngmdb.usgs.gov/Geolex/Units/Wayland_11080.html)
**Cameron Creek Member**: A Pennsylvanian unit comprised of sandstones, mudstones, and limestones that outcrops in North Dakota and Montana. [Geolex](https://ngmdb.usgs.gov/Geolex/Units/CameronCreek_6921.html)

If there are no objections, I will add these.

**Comment by Jegelewicz** [comment]
I trust you to maintain these!

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Values added.
