### ISSUE TITLE
Shipping method code table needs a clean up and we need to separate the who from the how

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#5224]
I'm working on a loan right now that will be shipped to Norway via World Courier. That is not an option now in the Shipped Method. We could either add it as a method or add a generic 'other' and put the method in the shipment remarks, since this probably won't be a common method used (it's the first time in my 30+ years that we've used it, but that's what the Norwegians want).

@Jegelewicz @dustymc Thoughts?

**Comment by dustymc** [comment]
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctshipped_carrier_method, not https://arctos.database.museum/info/ctDocumentation.cfm?table=ctshipment_type, correct?

Agree with something generic, I'm actually not sure all the existing companies in there make sense nowadays - if you've got a tracking number you can figure out who you shipped with from it, and if you don't have that then this isn't doing you much good anyway!

**Comment by Jegelewicz** [comment]
I mean, Alaska Air Cargo is in there....

but a generic shipper might be good - the code table needs some definitions.

**Comment by Jegelewicz** [comment]
But also - shouldn't these just be agents?

**Comment by ccicero** [comment]
That makes sense to have them as agents, but there are also other options such as 'electronic' (for media) or 'hand carried'

correct @dustymc 
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctshipped_carrier_method

So what to do now as I need to get this loan sent?

**Comment by Jegelewicz** [comment]
So this table is a mix of who and how. Seems like it should just be how. Who should come from agents (who was the hand carrier?).

To get the loan out, maybe just add something generic, but this needs more thought and I think we can do better.

**Comment by Jegelewicz** [comment]
+1 for adding World Courier" we can convert to an agent later if we go that way.

**Comment by ccicero** [comment]
OK, great! I agree that it would be better to separate the who from the how:
who ---> agents
how ---> maybe something simple like:

cargo/mail
electronic
hand carried

each of those could have an agent attached so you know who hand carried, sent, or shipped it

I'll go ahead and add World Courier for now. Thanks!

**Comment by Jegelewicz** [comment]
I'll hijack this issue so we can get the bigger picture on the to do list.

**Comment by ccicero** [comment]
While I'm at it, I took a first stab at definitions in https://arctos.database.museum/info/ctDocumentation.cfm?table=ctshipped_carrier_method.  Most were just 'pending' previously.

**Comment by Jegelewicz** [comment]
I don't know why this was closed. We still need to clean up this code table.

**Comment by mkoo** [comment]
I see serviceable definitions in the entire code table. Closing for now and open a new one if there's something new to be done
