### ISSUE TITLE
What is the part remark "Possible duplicate with specimen_part.collection_object_id" [CONTACT]

### ISSUE THREAD

**Issue by amgunderson** [ArctosDB/arctos#5226]
Why are remarks being added to specimens saying "Possible duplicate with specimen_part.collection_object_id 21341397", as in https://arctos.database.museum/guid/UAM:Mamm:21922 and 717 other UAM:Mamm specimens? I do not want remarks added without any curatorial input and Arctos should not be assuming things are duplicates much less telling everyone that. We often save multiples vials of muscle or blubber because those tissues are used in isotopes or contaminants research that often requires more than a dna subsample. Arctos should not be thinking for itself!

<img width="678" alt="Screen Shot 2022-10-31 at 1 05 20 PM" src="https://user-images.githubusercontent.com/8440698/199110466-6b6bc28f-d12a-4201-96e5-d76a755f0649.png">

**Comment by dustymc** [comment]
That was part of a bugfix - maybe 15 years back....

**Comment by dustymc** [comment]
>get them off

Sure - just mammals or any/all of the rest?

Here's data with a proposed update ("new_remark") - have a quick look and let me know if it looks OK or needs more adjustment.

[temp_dupprtrms.csv.zip](https://github.com/ArctosDB/arctos/files/9913053/temp_dupprtrms.csv.zip)


```
 guid_prefix | count 
-------------+-------
 UAM:Herp    |     2
 MSB:Mamm    |  1101
 MVZ:Herp    |    20
 MVZ:Bird    |     2
 MVZ:Mamm    |    53
 MSB:Para    |    20
 UAM:ES      |     4
 UAM:Herb    |   142
 UAM:Bird    |     4
 UAM:Mamm    |  1385
 UAM:Ento    |     4
```


 @mkoo
 @campmlc
 @ccicero
 @amgunderson
 @DerekSikes
 @atrox10
 @cjconroy
 @AdrienneRaniszewski
 @jldunnum
 @msbparasites
 @StefanieBond
 @jandreslopez
 @kyndallh

**Comment by dustymc** [comment]
[temp_dupprtrms(1).csv.zip](https://github.com/ArctosDB/arctos/files/10272572/temp_dupprtrms.1.csv.zip)

done
