### ISSUE TITLE
specimen labels lost and broken

### ISSUE THREAD

**Issue by amgunderson** [ArctosDB/arctos#5227]
**Describe the bug**
the link, http://reports.arctos.database.museum/reporter/report_printer.cfm?auth_key=1337D4BF-3893-42B6-A78C4330FE6E8810, on the reports printer page, https://arctos.database.museum/Reports/report_printer.cfm, does not work.

My uam vial labels got totally messed up and uam box labels no longer exist. Editing CFM and CSS code is not what any collection manager should have to learn. How do I get me labels back?

**Priority**
 a black hole of despair.

**Comment by amgunderson** [comment]
the how to print labels on the tutorial site is no longer relevant and shold be deleted. https://arctosdb.org/learn/tutorial-blitz/#reports

**Comment by amgunderson** [comment]
This how-to is also obsolete, https://handbook.arctosdb.org/how_to/How-To-Print-Labels.html

**Comment by amgunderson** [comment]
This how-to is also obsolete, https://handbook.arctosdb.org/how_to/How-to-Create-Labels.html

**Comment by Jegelewicz** [comment]
I've added a [documentation update issue](https://github.com/ArctosDB/documentation-wiki/issues/280) in the documentation repo and for now added the under construction bear and some instructions for [filing an issue](https://github.com/ArctosDB/arctos/issues/new?assignees=lkvoong&labels=function-Reports&template=report-template-request.md&title=New+Arctos+Report+Template+Request) to get help with an updated report.

**Comment by dustymc** [comment]
Old report printer resurrected, again.

**Comment by campmlc** [comment]
@amgunderson please be aware that the old reporter will eventually die permanently, and we are working on replacements. There is an issue template where you can post the downloads of the reports you currently use, ideally along with an image of the report and dimensions, so we can work on providing a replacement. @lkvoong is helping create the new files so we don't have to deal with html etc; @Jegelewicz and @mkoo are looking into word and Google report options as well. We are meeting during weekly Arctos office hours to tackle this as a priority - please come!

**Comment by amgunderson** [comment]
Where is the "issue template"? I have created a template in Word using the mailings function. It uses a csv of specimen data downloaded from arctos to make this, 
[UAM vial labels.pdf](https://github.com/ArctosDB/arctos/files/9931353/UAM.vial.labels.pdf)
I'll do a larger box label next. I don't like this, but it will work.

**Comment by dustymc** [comment]
>Where is the "issue template"?

<img width="208" alt="Screen Shot 2022-11-03 at 9 55 29 AM" src="https://user-images.githubusercontent.com/5720791/199785220-953a5273-a205-4b99-9865-9bbdc2bb8fed.png">

<img width="1287" alt="Screen Shot 2022-11-03 at 9 55 44 AM" src="https://user-images.githubusercontent.com/5720791/199785255-cc30dd4c-5f7f-4f53-b419-a15713d606d4.png">

https://github.com/ArctosDB/arctos/issues/new?assignees=lkvoong&labels=function-Reports&template=report-template-request.md&title=New+Arctos+Report+Template+Request

>Word using the mailings function

Please share.

>csv of specimen data downloaded from arctos

If that needs any manipulation/customization for whatever reason, the reporter can also produce CSV.

**Comment by campmlc** [comment]
Looking at this now for our MSB reports - I can download the report as cfr file, and I can see and copy the SQL. Is this what you want posted to the issue template if we request help with creating the html version?
@dustymc @lkvoong

**Comment by campmlc** [comment]
And yes, @amgunderson, please share you mail merge protocol. I've done this with other labels, but I never set it up from scratch.

**Comment by dustymc** [comment]
>standard measurements

I can help with that, but I need to know what "columns" you want - maybe just send me a CSV and I'll see how far I get with that, but I'll try to work with however you want to communicate that.

@campmlc yes the initial SQL is useful, but please don't hesitate to ask us to review it (as long as you're willing to answer questions) - I know there's a lot of variation in that (eg MSB has ~dozens of ways of translating sex) but I don't/can't know if that's intentional or not. That said, it'll probably do whatever it did in the old system in the new, so if you're happy with that you can probably just use whatever you've got.

**Comment by dustymc** [comment]
report  uam_mamm_label_csv created
