### ISSUE TITLE
move some record attributes to collecting event?

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5228]
* air temperature :  https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#air_temperature
* water temperature : https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#water_temperature

And whatever I'm not seeing.

Can/should we move these to https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_event_attr_type?

```
 guid_prefix |  attribute_type   | count 
-------------+-------------------+-------
 UAM:Env     | air temperature   |   183
 UAM:Env     | water temperature |   183
```

@KyndallH looks like this is all you, just let me know if you want me to move, or maybe make the docs better if there's some reason NOT to move.

**Comment by campmlc** [comment]
Working on getting more fields from MSB.There are a lot.

**Comment by campmlc** [comment]
Here are the data fields in use by MSB Fish collection, for which ideally we'd have locality attributes:

<html>
<body>
<div style="font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);"><br class="Apple-interchange-newline">

Field | Description | Units
-- | -- | --
Salinity of water, min and max | Salt dissolved in a body of water, measured by parts per thousand | ppt
Water Temperature, min and max | Temperature of a body of water | °C
Air Temperature, min and max | Temperature of the air at collecting site | °C
Dissolved Oxygen, min and max | oxygen present in a body of water | mg/l
Conductivity | conductivity of a body of water | µS
Specific conductivity | conductivity of a body of water, at 25°C | µS
pH min and max | Acidity or basicity of a body of water, potential hydrogen in a body of water | N/A
Flow, start and end | Volume of water that passes within a unit of time | cms (cubic meters per second)
Secchi depth/Transparency | Transparency of water at collection site, measured by secchi disk | cm
River Width, min and max | Width of river from one side of bank to the other bank | m

<br></div><span class="im" style="color: rgb(80, 0, 80);"><span style="color: rgb(80, 0, 80); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"></span><div style="color: rgb(80, 0, 80); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br class="Apple-interchange-newline">
</body>
</html>

**Comment by campmlc** [comment]
Excuse me, I mean collecting event attributes, as they reflect temporal as well as spatial data.

**Comment by dustymc** [comment]
@campmlc those need their own CT request, this is just cleanup, but some brief comments:

* Some of them exist and can just be used
* Without more information, I'll object to all of the min-and-max stuff - just enter what you have, multiple determinations are fine, there's no reason to tell the user that the smaller one is smaller.


https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#electrical_conductivity should be added to the initial request.

**Comment by dustymc** [comment]
Interpreting the silence as enthusiastic support and going next task.
