### ISSUE TITLE
[CONTACT]

### ISSUE THREAD

**Issue by jldunnum** [ArctosDB/arctos#5230]
** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **

** Outages should be reported to the contacts listed at https://arctosdb.org/arctos-down/ **

** Arctos Documentation is http://handbook.arctosdb.org/ **

** Learn more about Arctos at https://arctosdb.org/ **

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **
Under identifications can we add the ability to select multiple "Nature of IDs"?
For example, often we identify a species based on a combination of "features" and "geographic location".

<img width="580" alt="Screen Shot 2022-11-01 at 3 52 42 PM" src="https://user-images.githubusercontent.com/17278851/199349578-b43d30a2-4997-4a6b-bc80-11fc062af094.png">

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/4829
