### ISSUE TITLE
Arctos Down - no response

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5236]
Please complete to the best of your ability.

## Unplanned Outage
 - 2022-11-02 1:30PM MDT
 - Browser just spinning. Tried both Firefox and Chrome - I have a demo in 20 minutes...

## Planned Outage
 - Date and time outage will begin:
 - Date and time outage is expected to end:
 - Reason for outage:
 - Expected behavior during and after the outage:

## Communication before/during outage
- [x] Pin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG  
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by dustymc** [comment]
resurrected

**Comment by Jegelewicz** [comment]
Thanks!
