### ISSUE TITLE
How to fix this in the bulkloader?

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#5238]
# Error Text
Trying to load records created in the data entry form and I got this screen:
<img width="1283" alt="Screen Shot 2022-11-02 at 1 49 35 PM" src="https://user-images.githubusercontent.com/17605945/199609360-4cb7c703-7cf0-4f17-9547-66ea4a57563e.png">

# Where it happened
https://arctos.database.museum/Bulkloader/browseBulk.cfm

# Steps to get there
Clicked:
1. Load All selected Records
2. Autoload_core

# Problem
All of the higher geographies were selected from the higher geography picker so there should be nothing wrong with them.

# Solution
**Community response with directions for how to correct the problem**

**Comment by Jegelewicz** [comment]
Remove all the continents from Higher Geography is probably the answer, but also in your case the quads? @dustymc may need to help.

**Comment by Jegelewicz** [comment]
But also @dustymc can we do some fixes for things hanging out in the bulkloader in general that have been affected by the new geography plan?

**Comment by dustymc** [comment]
I did this:


update bulkloader set higher_geog=replace(higher_geog,'North America, ','') where guid_prefix='UAM:EH';

>All of the higher geographies were selected

https://github.com/ArctosDB/arctos/issues/5138

**Comment by dustymc** [comment]
happy?

**Comment by AJLinn** [comment]
you beat me to it - thanks!
