### ISSUE TITLE
[ geography request ] Alexander Archipelago 

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5239]
### Explain what geography needs created.

A user requested a search of Alexander Archipelago. We don't have that, we should.

If someone has this, could you please pass it on?

If nobody has this, perhaps we should just click around on the map and create it from that? I don't think FFF need to be particularly high-resolution, they are primarily search aids, and anyone who wants to complain can do so by supplying spatial data. Thoughts?

@mkoo @ArctosDB/geo-group

**Comment by Jegelewicz** [comment]
@dustymc they may need more than just that. I see that as one example of many searches they could be doing as part of that lesson. I have a TDWG meeting this morning, so I can't look for this right now. Sorry!

**Comment by dustymc** [comment]
Tabling for lack of resources; FFFs of neato random things would still be cool.
