### ISSUE TITLE
Code Table Request - redefine 'hyoid'

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#5247]
currently:
|coll | part | defn|
|---|---|---|
|ES, Bird, Mamm | hyoid | A horseshoe-shaped bone situated in the anterior midline of the neck between the chin and the thyroid cartilage. [Wikipedia](https://en.wikipedia.org/wiki/Hyoid_bone)|

The definition excludes Herps but even then, the hyoid described is really just for the human bone (the link to Wikipedia is the clue!) So can we have a more  generic vertebrate definition? Definitely doesnt describe birds or even many mammals the way it is now.

Suggestion:
|coll | part | defn|
|---|---|---|
|ES, Bird, Mamm, Herp | hyoid | The bone(s) located in the anterior midline of the neck which supports the musculature of the tongue and throat cavity. It is typically unarticulated in the vertebrate skeleton. It may be arch-shaped or has paired processes that lie on either side of the midline, and may be fully or partially ossified. [Wikipedia definition for the human hyoid](https://en.wikipedia.org/wiki/Hyoid_bone) |

**Comment by ewommack** [comment]
I don't think bone is accurate. In birds it is made up of several bones, and I think in a number of mammals it actually is multiple bones. I would be more comfortable with "the bone(s)..."

Here's what I have from Vertebrate Dissection for mammals:
The hyoid..."consists of a tranverse bar of bone, the body of the hyoid, composed of a single bone (basihyal) from which two pairs of processes (horns) extended cranially and caudally. The caudal or greater horns of the hyoid are the larger horns, and each consists of but one bone, which is called the thyrohyal, for it extends caudally to attach to the thyroid cartilage of the larynx...Each of the cranial or lesser horns of the hyoid consists of a small ceratohyal..." (and it goes on with more smaller named ossicles too).
"In some mammals (human beings, for example) the hyoid apparatus consists of a single bone, the hyoid, having a body, a lesser horn, and a greater horn."
"A hyoid apparatus is present in mammals but is not so large as in nonmammalian tetrapods."

**Comment by dustymc** [comment]
>hyoid described is really just for the human bone

Yes, but that came long after the material was cataloged - and we keep going back to the idea that those wikipedia copypasta definitions make things worse, not better....

>The bone 

I think that's wrong/incomplete.

Here's data

[temp_part_hyoid.csv.zip](https://github.com/ArctosDB/arctos/files/9932949/temp_part_hyoid.csv.zip)

users
```

 guid_prefix | count 
-------------+-------
 MVZ:Mamm    |    17
 UCM:Mamm    |     2
 NMMNH:Paleo |     2
 DMNS:Mamm   |    15
 UAM:Mamm    |   875
 MSB:Mamm    |     5
 UWBM:Mamm   |    53
 UAM:ES      |     3
 UMZM:Mamm   |    16
 UTEP:ES     |     3
 UMZM:Bird   |     2
 MVZ:Bird    |     1
```

contacts


 @ebraker
 @Nicole-Ridgwell-NMMNHS
 @mkoo
 @campmlc
 @ccicero
 @amgunderson
 @mvzhuang
 @cjconroy
 @adhornsby
 @jebrad
 @AdrienneRaniszewski
 @acdoll
 @jldunnum
 @jrdemboski

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Another option from Analysis of Vertebrate Structure, (5th ed., 2001, Hildebrand and Goslow):
Hyoid Apparatus: The complex of bones that moves the tongue and suspends the larynx from the base of the skull.

**Comment by Jegelewicz** [comment]
OOF - see how hyoid and hyoid apparatus get confused.....

**Comment by ewommack** [comment]
We're getting to the bones of the matter :D

**Comment by Jegelewicz** [comment]
But these aren't necessarily bones....

**Comment by Jegelewicz** [comment]
@mkoo do you still care about this?

**Comment by jebrad** [comment]
I care - but only to the extent that we would like to continue to do this: We have been using hyoid as if it is "hyoid apparatus", we use it even if we only have some but not all of the hyoid bones for that specimen. We would only use it for bones even if "these aren't necessarily bones".  
We could change all to partial skeleton with hyoids in the remarks, but that seems like it would be part of a bigger project targeting more than just hyoids.
@Jegelewicz if you think we should clean this up, let me know and we can have Erika fix the ones we have already. I know we have more of these coming in, when we clean skulls for hunters we typically keep a tissue plus bones that may include mandibles, hyoids, and a couple verts.

**Comment by Jegelewicz** [comment]
@jebrad this is just a request to change a definition, so the term wouldn't go anywhere. I think you are using it in an appropriate way...

**Comment by ebraker** [comment]
I am ok with changing the definition to be more inclusive. And hyoid to hyoid apparatus if need be.

**Comment by dustymc** [comment]
See also https://github.com/ArctosDB/arctos/issues/5186 / https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#hyobranchial_apparatus.

**Comment by dustymc** [comment]
status?
