### ISSUE TITLE
New Arctos Report Template Request specimen data labels for skeleton vials and boxes

### ISSUE THREAD

**Issue by amgunderson** [ArctosDB/arctos#5251]
**Description of the report**
A specimen data label for small mammal skeleton vials.
I have created a template in Word to produce shell vial labels of 1 x 1 5/8 inches.
It is here, 
[UAM vial labels template.docx](https://github.com/ArctosDB/arctos/files/9933666/UAM.vial.labels.template.docx)
The labels it produces look like this, 
[UAM vial labels example.pdf](https://github.com/ArctosDB/arctos/files/9933670/UAM.vial.labels.example.pdf)

To use this template do this (on an Apple Imac, maybe the same in windows):
Download a specimen search result of those specimens you want labels for.
Fields included in the UAM vial label template are: guid, species, country, state_prov, spec_locality, dec_lat, dec_long, verbatim _date, collectors, sex, total_length, tail_length, hind_foot_with_claw, ear_from_notch, weight, othercatalognumbers.
In excel, do a find/replace to remove the “ mm” from the measurement columns.
Save the csv.

Open the label template file in Word
Click on the mailings menu
Click “select recipients”, “use an existing list”
Choose your csv file of arctos data.
A window about encoding pops up, click okay.
To see your data in the labels, click “preview results” in the Mailings menu.
Print.

The template has 2 pages and will print 64 labels. If you need more labels, copy and paste more rows until you have enough to print all the labels you need.

**Comment by amgunderson** [comment]
Description of the report
A specimen data label for mammal skeleton boxes.
I have created a template in Word to produce box labels of 2 x 3 inches.
It is here, 
[UAM box labels template.docx](https://github.com/ArctosDB/arctos/files/9933726/UAM.box.labels.template.docx)

The labels it produces look like this,
[UAM box labels example.pdf](https://github.com/ArctosDB/arctos/files/9933753/UAM.box.labels.example.pdf)

To use this template do this (on an Apple Imac, maybe the same in windows):
Download a specimen search result of those specimens you want labels for.
Fields included in the UAM box label template are: guid, species, country, state_prov, spec_locality, dec_lat, dec_long, verbatim _date, collectors, sex, total_length, tail_length, hind_foot_with_claw, ear_from_notch, weight, othercatalognumbers, accn_number, parts.
In excel, do a find/replace to remove the “ mm” from the measurement columns.
Save the csv.

Open the label template file in Word.
Click on the mailings menu.
In the first label, change "University of Alaska Museum Mammal Collection" to your collection.
Click on the "update labels" button, looks like this,
<img width="34" alt="Screen Shot 2022-11-03 at 3 55 37 PM" src="https://user-images.githubusercontent.com/8440698/199856738-5b47b4e2-7053-4b0a-82f6-1dafd967e7b3.png">
That sends your change in the first label to all other labels.

Click “select recipients”, “use an existing list”
Choose your csv file of arctos data.
A window about encoding pops up, click okay.
To see your data in the labels, click “preview results” in the Mailings menu.
Print.

The template has 10 pages and will print 100 labels. If you need more labels, copy and paste more rows until you have enough to print all the labels you need.

**Comment by Jegelewicz** [comment]
@amgunderson this is awesome!!!!! Thank you!!!!!!

**Comment by campmlc** [comment]
Yes, fantastic, thanks!

**Comment by Jegelewicz** [comment]
I added a link to this issue in How To Print Labels.

**Comment by dustymc** [comment]
@amgunderson I built the start of a CSV download. It just strips 'mm' from measurements (and makes sure you get the columns you need). I'm not sure if you actually meant 'species' (what its built with) or scientific name, I can convert measurements if necessary, I can stick measurements together as a string, WHATEVER, there's a lot of flexibility in this environment. Let me know if you want to change something, or let me know if you don't want to use that and I'll just delete it.

It's called  uam_mamm_label_csv , search/manage --> Arctos reporter, click Open.

<img width="740" alt="Screen Shot 2022-11-04 at 9 10 23 AM" src="https://user-images.githubusercontent.com/5720791/200023396-79e089ca-04a0-4e6d-ba68-ddeb325c3fa8.png">

**Comment by amgunderson** [comment]
Excellent. If you can make the standard measurements appear in a single column as total_length-tail_length-hind_foot_with_claw-ear_from_notch=weight, with the hyphens and equals sign in there, units for weight still there, that would be cleaner for specimens that lack measurements. 
That is the only hassle with preparing the csv file for the word template so if that is made to work I wouldn't even have to open the csv file after downloading it.

**Comment by amgunderson** [comment]
I don't know what the difference is between species and scientific name. Whichever provides the accepted identification is fine.

**Comment by dustymc** [comment]
>standard measurements

Give uam_mamm_label_csv a try, it should be fairly robust but probably not bulletproof. I'm converting to mm and g, using X as a placeholder, aggregating multiple unique values - let me know how if you break it and I'll do something different.

>difference is between species and scientific name

Scientific name will always exist is probably the most obvious for this. They'll (usually) be the same when there's one taxon that has a species involved. I switched to scientific_name, I can easily rename columns or use something else if you need anything different.

>only hassle

Some other user won't have one of the required columns turned on, this should avoid that as well.

> wouldn't even have to open the csv 

That's the idea. I have really great CSV-making tools, I should be able to manipulate data in just about any way, I just need fully-fledged specifications or some back and forth or to figure out what you need.

**Comment by dustymc** [comment]
Report created, please reopen if adjustments are necessary.
