### ISSUE TITLE
Help needed to resolve geography and locality errors

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#5252]
I understand we have just made changes to the geography model. But I don't understand what is wrong with the records below or how to fix. As an aside, it would be great to have a csv download tool available for this search.

https://arctos.database.museum/Reports/cat_record_reports.cfm?guid_prefix=MSB:Host&report_name=locality:%20georeference%20does%20not%20intersect%20geography

This includes extremely valuable records such as [these two](https://arctos.database.museum/saved/Antarctica%20MSB%20Para%20Host%20records) from Antarctica. I can google this locality, and I can map it in Arctos in Berkeley mapper. What is wrong with it so that we get this error, and what is the recommended fix? I don't get that from the error or the UI.

**Comment by dustymc** [comment]
Those are all slightly out of date errors, you can just delete them and see what happens next time around. (https://github.com/ArctosDB/arctos/issues/5213 - I could use more CPU-er-something.)

The Antarctica things actually map fine, but I think that's probably an error - the geography (which they fit) says they're from saltwater while the specloc claims they're from a rock.

<img width="756" alt="Screen Shot 2022-11-03 at 5 00 07 PM" src="https://user-images.githubusercontent.com/5720791/199857161-93ebda66-3824-419e-898d-f624da1878ef.png">

I clicked some other random thing (https://arctos.database.museum/guid/MSB:Host:24425) from your list and it's more as expected: you claim there's some county involved but the georeference isn't anywhere near the county. The cacher will pick up the spatially-correct county and make this discoverable, but users still have to decide which piece of conflicting information to believe. (FWIW given self-conflicting data I'd always choose "none of it" and just reject the record.)

<img width="773" alt="Screen Shot 2022-11-03 at 5 01 12 PM" src="https://user-images.githubusercontent.com/5720791/199857331-b7355904-602f-4bb0-babc-e9e609d7d940.png">

**Comment by campmlc** [comment]
Cool. Possible to get csv download of the errors?
