### ISSUE TITLE
Help needed to update some geography that was in the bulkloader

### ISSUE THREAD

**Issue by jebrad** [ArctosDB/arctos#5253]
Hello @dustymc , I need some help updating my Higher_geog, please.

Here is the file of data with errors.  
[bulkloader_stage(JEB 2021-15).csv](https://github.com/ArctosDB/arctos/files/9934035/bulkloader_stage.JEB.2021-15.csv)

These records were entered months ago, I recently downloaded all 264 records from that accession, cleaned up some columns, and then when I tried to re-upload via "Bulkload Catalog Records" most failed to load due to "HIGHER_GEOG matches 0 records"
Please let me know if/what I can do myself.  I will go through and work on the other errors.

Thanks much,
Jeff

**Comment by dustymc** [comment]
Column newgeo should be the correct/current geography, but you may need to update specloc to reflect anything that was removed - especially islands.

[temp_uw_g.csv.zip](https://github.com/ArctosDB/arctos/files/9934325/temp_uw_g.csv.zip)

This change is from https://github.com/ArctosDB/arctos/issues/5138.

**Comment by jebrad** [comment]
This is great, thanks.

Question:  how picky is SPEC_LOCALITY?  I plan to just copy/paste island names out of HIGHER_GEOG right into the start of the cell for SPEC_LOCALITY unless you say that's a Bad Idea.

**Comment by Jegelewicz** [comment]
> how picky is SPEC_LOCALITY? 

It isn't!

**Comment by jebrad** [comment]
OK great and thanks.  Got them all into bulkloader, now loading.  Will start a new issue if I have another.
