### ISSUE TITLE
Arctos Down - Nov 4 6:43AM MT

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#5254]
Please complete to the best of your ability.

## Unplanned Outage
 Website times out (Nov 4 6:43am)

## Communication before/during outage
- [x] Pin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG  
- [x] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [x] Unpin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by lin-fred** [comment]
this is also happening for me

**Comment by lin-fred** [comment]
tweeted

**Comment by ebraker** [comment]
Restored!

**Comment by lin-fred** [comment]
it is back up for me too
