### ISSUE TITLE
New Arctos Report Template Request - CHAS:Herb

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#5255]
**Description of the report**
Specimen label for herbarium sheets

**Collection for which the report is needed**
CHAS:Herb

**Priority**
Normal - we have been working from a mail merge, so we have a workaround for now, but it requires a lot of manual edits (see below)

Here's a copy of the mail merge template: [Backlog Botany Labels_Mail Merge_2022-11-04.docx](https://github.com/ArctosDB/arctos/files/9940902/Backlog.Botany.Labels_Mail.Merge_2022-11-04.docx)
And the fields downloaded from Arctos: [Atwater_Label Example.csv](https://github.com/ArctosDB/arctos/files/9940907/Atwater_Label.Example.csv)

A few things that we've had to fix manually while using mail merge (see screenshot below); can these be automated for the reporter?
![image](https://user-images.githubusercontent.com/93737929/200042040-caaecfca-4747-43c1-9eef-561b36c9e5c6.png)

- Adjusting for something that isn't recorded. For example, if there isn't a recorded locality, date, habitat, or collector number, there's a floating comma or empty parentheses
- Only pulling the collector number, not any of the "other identifier"; also, removing "collector number=" from the text
- The old form pulled the ID remarks up to the period. We record the common name in ID remarks, so we've had to manually remove the period and any information after it when using the mail merge.
- Can it auto-fill the continent?

Please let me know if you need any clarifications. Thanks!

**Comment by dustymc** [comment]
>Adjusting for something that isn't recorded. For example, if there isn't a recorded locality, date, habitat, or collector number, there's a floating comma or empty parentheses

I think that's going to have to be dealt with in your doc - the data is coming across correctly, yes?

>We record the common name in ID remarks

I'm going to need more explanation, but WHATEVER you are doing sounds like it's _designed_ to prohibit access (and so it's doing precisely what I'd expect, breaking things!). Are you asking to manipulate the data in the CSV (which I can probably help with) or is this something in Word? 

> auto-fill the continent?

See https://github.com/ArctosDB/arctos/issues/5138, I can get continents as FFFs but that needs a dedicated issue.

**Comment by wellerjes** [comment]
Backing up a little: Is there a way to take this mail merge document and make it into a [report embedded within Arctos](https://arctos.database.museum/Reports/reporter.cfm)? That is ultimately my goal. I looked at https://codepen.io/, but I'm not sure how to get what I have into HTML or CSS, since it's a word document, or how to get it to align with the categories in Arctos (enclose within #?). 

The data is coming across correctly, yes. In the old reporter, it would only add the commas if there was data to follow.

**Comment by dustymc** [comment]
>mail merge document and make it into a [report embedded within Arctos](https://arctos.database.museum/Reports/reporter.cfm)

No, Arctos speaks HTML and CSS (and such), not Word.

>. In the old reporter,

If there's existing SQL reusing it will save me a lot of time and guessing. @Jegelewicz something about old reports should be added to the template.

**Comment by campmlc** [comment]
I think the problem with codepen is it only works if we already have an html template and want to tweak it. This means we are still reliant on Lam making one for us?

**Comment by Jegelewicz** [comment]
> something about old reports should be added to the template.

I added a request for the SQL. Anything else?

**Comment by mkoo** [comment]
> I think the problem with codepen is it only works if we already have an html template and want to tweak it. This means we are still reliant on Lam making one for us?

Actually the new system means anyone can make one and tweak-- codepen is just a tool to help with the process but by no means the only one.

I am setting up a bunch of templates and a help page today so more on this later. I will go through the issues here and link to the template that seems to match the best.

We have all the previous SQL and prefunctions so if its not too crazy (ie. not a lot of updated tables and such) we should be able to reuse in the new system. more soon

**Comment by dustymc** [comment]
Does this need action?

**Comment by wellerjes** [comment]
Closing; I'm going to try to use the new label reporter format based on last week's reporter tutorial.
