### ISSUE TITLE
Geography Lookup not processing records

### ISSUE THREAD

**Issue by barke042** [ArctosDB/arctos#5258]
Hi, I uploaded ~1000 records to the new geography lookup service yesterday and they have not processed as of this morning. I'm not sure if this is related to the outage yesterday, or whether the delay is because of other component loaders running or whatever, but I thought I'd point it out.

Please close out if this is normal/expected and nothing is wrong.

**Comment by dustymc** [comment]
<img width="449" alt="Screenshot 2022-11-05 at 3 35 26 PM" src="https://user-images.githubusercontent.com/5720791/200143872-17d3c906-2815-4f0a-907a-7d46923e2f18.png">

will tell you when things are scheduled to run. I tuned the media relationship loader up, it should complete in an hour or so (up from ~3 days).

**Comment by barke042** [comment]
Thanks!
