### ISSUE TITLE
Feature Request - Locality page - please return Berkeleymapper link (and move 'no data button')

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#5261]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

A HUGE part of my data-quality checking workflow was to
1) find all records without 'accepted' localities (eg unverified)
2) find all localities of those records
3) check over each locality record for errors, missing data, wrong lat/long etc.
4) click the berkeleymapper link to ensure the lat/longs were mapping properly (often using the 'topo' view to ensure place names missing from most google maps etc were as they should be etc)

Now the berkelymapper link (thumbnail) is missing from the locality page so to get to that map I have to do a bunch more clicking between different pages/tabs in browser.

Can that thumbnail or at least a text link to that tool be returned? (or if it is there, make it more obvious! I can't find it)

ITEM 2: The button "No specific locality recorded" is way too close to the entry point for the specific locality field - I've accidentally clicked it just when trying to enter the field to edit. Please move it - maybe far to the right or something so it's not so close. It's for a rare situation and it's a bad idea for it to be so close to that field's start point.

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.
High

**Comment by DerekSikes** [comment]
Wondering if this could be attended to soon? A simple link to berkeleymapper from the locality record page would be great (like it had been!).

**Comment by dustymc** [comment]
Should be in next release, but I can't get BM to talk to test so that needs checked.

I can't find a better place for the button (the usage of which is very much not rare!), and there's a revert path so I'm ignoring that for now - could be addressed in another issue but needs more attention than I can give it incidentally.
