### ISSUE TITLE
Need Help with Arctos Error - Is the old reporter dead?

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#5262]
# Error Text
Tried to print report from the old reporter; it's telling me "This site can't be reached. The connection was reset."

# Where it happened
When I tried to print from the old reporter. Is it officially gone?

# Steps to get there
From search results - Print Stuff - Arctos Reporter - Click this to continue to the legacy reporter:

# Problem
We don't have a new report set up to print labels yet.

# Solution
**Community response with directions for how to correct the problem**

**Comment by dustymc** [comment]
>Is it officially gone?

Maybe! I can't get in either, requested help from TACC.

**Comment by mkoo** [comment]
I'm working on documentation and training a student with web dev skills to help with the migration process.... what was the label you needed? some are much simpler to create in the new system than others! Let me know

**Comment by dustymc** [comment]
It seems to happen more and more often and take a few more people to resolve every time, but the old report server has once again been pulled out of the grave and propped up into a lifelike pose.

**Comment by wellerjes** [comment]
@mkoo It was a malacology label. Thanks!

**Comment by mkoo** [comment]
yea we're in 'weekend with Bernie' 's territory...
