### ISSUE TITLE
New Request - DOI's for Projects

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#5263]
With journals requiring more publicly available data, we would like to be able to cite Arctos datasets used in original research. Arctos Projects are already set up to associate data loans and other transactions and we can link to journal  etc. So being able to then share a DOI for the Project URL would be a huge boon. Currently the project does have a stable URI but it is not recognized as a digital object. (GBIF is not a good option for a variety of reasons...) This would be available across all collection types and has a lot of potential 

Can we add a new function button in the edit Project-- generate DOI? This would need to be displayed in the public view when available. This would not be required.

**Comment by dustymc** [comment]
No objection (thought we already had this?!) going next task, BUT, bigger picture...

>cite Arctos datasets used in original research

Arctos (and Arctos alone, I sometimes think) is hugely dynamic, WHATEVER you cite is probably going to be wildly different by the time I see it. Arctos is also hugely flexible, I might not have turned on whatever you were looking at for your analysis (or vice-versa). Etc. etc. ad nauseum. Enter Dryad, which exists just for you to be able to stash whatever you used for your analysis. I don't think we make enough use of that, and I don't think we encourage/require borrowers to do so. We should. (And maybe we need some additional Project/Dryad connection, but that's probably some kind of Major Surgery - just a link works for now and might be functionally equivalent anyway.)

**Comment by mkoo** [comment]
Yes my thoughts too but let's take this easy baby step towards those deeper functional links. Right now, we could have some documentation about best practices and suggest that DOI minting of projects is for loan transactions (specifically for us, data loans) which gets us to citing large lists of specimens. The lists are static although allows for dynamic updating.
