### ISSUE TITLE
Code Table Additions - Reproductive Data

### ISSUE THREAD

**Issue by jldunnum** [ArctosDB/arctos#5264]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
Current structure doesn't allow for full parsing of the varied reproductive data we collect. There is a large initiative to capture and serve trait data. This would improve that capability.

**Describe what you're trying to accomplish** 
Would like more fields for reproductive trait data. Basically all of our data are currently in the "Reproductive data" or "Specimen remarks" fields.

**Describe the solution you'd like**
Currently Arctos has the following fields: "Reproductive data", "crown rump length", "left gonad length", "left gonad width", "right gonad length", "right gonad width", "gonad", "gonad weight", and "ovum". 

We would like some iteration of the following: Testes - scrotal/abdominal, testis length, testis width (we have not discriminated between left and right historically), vagina - open/closed, nipples - small/enlarged, lactating/not lactating, pregnant - yes/no, embryos - yes/no, placental scars - yes/no, number of embryos/scars left horn, number of embryos/scars right horn

**Describe alternatives you've considered**
The alternative is to leave all repro data in a single free text field. Not ideal.

**Additional context**
Current efforts will soon be underway in many Arctos hosted collections to capture trait data so now is a good time to standardize this and get these data out of the free text fields if possible

**Priority**
High

**Comment by campmlc** [comment]
We should be removing the constraint on the number of attributes that can
be loaded through the bulkloader, so this is good timing!
Any chance you can provide the exact terms and their definitions, plus
maybe a link to some documentation on how these are obtained, so we can add
to the code table?

**Comment by dustymc** [comment]
> constraint on the number of attributes that can be loaded through the bulkloader,

Absolutely impossible, see https://github.com/ArctosDB/arctos/issues/5193 - which might be going active in the next week or so and then will be locked for some number of years.

**Comment by jldunnum** [comment]
Here are some definitions for the requested attributes.

Reproductive attributes Feature Request - (Issue #5264)
testes: scrotal/abdominal             [scrotal - testes descended into scrotum; abdominal – testes undescended, still in abdomen] 
testis length: [number] mm         [length of longest aspect of testis]
testis width: [number] mm     [length of shortest aspect of testis]
vagina: open/closed                  [open - vagina perforated; closed – vagina sealed]
nipples: small/enlarged                         
lactating: yes/no                        [milk expressible from nipples]
pregnant: yes/no                       
placental scars: yes/no                  [Placental scars are pigmented areas found at former sites of implantation in the uterine wall]
embryos in left uterine horn: [number]
embryos in right uterine horn: [number]
placental scars in left uterine horn: [number]
placental scars in right uterine horn: [number]

**Comment by Jegelewicz** [comment]
This also is like #4533

We need to make sure they are useful and defined well by the user community.

**Comment by Jegelewicz** [comment]
These terms have been added to the list of existing terms for the RANGES team to consider. I am going to close this issue. If any of these terms needs to be requested, please request each separately using the [code table request template](https://github.com/ArctosDB/arctos/issues/new?assignees=&labels=Function-CodeTables&template=authority-request.md&title=Code+Table+Request+-+).

**Comment by bryansmclean** [comment]
Hi @Jegelewicz, I would like to re-open this issue in advance of our RANGES (#5532) start date of 1 May 2023. There is an urgent need for the Arctos community to weigh in on trait terms and it would be great to standardize at the outset of the digitization process. When could we convene?

**Comment by Jegelewicz** [comment]
> Arctos RANGES Team,
> 
> [Bryan has asked that we meet](https://github.com/ArctosDB/arctos/issues/5264#issuecomment-1507452495) - please provide your availability in [this When2Meet](https://www.when2meet.com/?19715290-eBblP) By tomorrow afternoon so that I can select a time when most of you can attend.
> 
> Adios,

Teresa J. Mayfield-Meyer

**Comment by Jegelewicz** [comment]
I think this is now addressed via individual code table issues - closing.
