### ISSUE TITLE
Flat taxonomy refresh

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5267]
Requesting a refresh of flat for a list of catalog numbers or everything in CSULB:Fish with Sebastes as genus in WoRMS (via Arctos)

These records - https://arctos.database.museum/saved/CSULB%20Sebastes

**Comment by sharpphyl** [comment]
We just refresh the genus Sebastes and it flows to all the catalog numbers using that taxon.  Are you doing something different here?

**Comment by Jegelewicz** [comment]
I think so - the current taxonomy associated with these records does not reflect what is in the preferred source becuase the preferred source was changed recently. Sebastes was already correct, but the collection just selected WoRMS (via Arctos). But maybe your method would still work?

**Comment by dustymc** [comment]
Is this still needed?

**Comment by Jegelewicz** [comment]
Looks like it has refreshed. Thanks!
