### ISSUE TITLE
Agent Merge Request - https://arctos.database.museum/agents.cfm?agent_id=4860 with https://arctos.database.museum/agents.cfm?agent_id=21313785

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#5268]
Use this template when you discover two agents that you believe represent the same person or organization.

**Agent that should remain after the merge**
Lemuel Floyd Clarke (https://arctos.database.museum/agents.cfm?agent_id=21313785)

**Agent that will no longer remain after the merge**
This agent should be of lower quality than the agent into which it will be merged. Navigate to the agent page, copy the url and paste it below: Clarke (https://arctos.database.museum/agents.cfm?agent_id=4860)

**Reason for merge**
Person has specimens in UWYMV and Denver collections from around the correct time period, and was associated with the UWY at this time. So Clarke is probably Lemuel Floyd Clarke.
I'm not sure on the DMNS specimen though - @acdoll ?

Please add this issue to the Agents Project

@ArctosDB/agents-committee

**Comment by ewommack** [comment]
Alternatively I can add the UWYMV specimens to the https://arctos.database.museum/agents.cfm?agent_id=21313785, but the DMNS agent will still need info.

**Comment by acdoll** [comment]
> I'm not sure on the DMNS specimen though - @acdoll ?

Our ledger just says Clarke; the specimen tag says Mr. Clarke. Our specimen is from 1922 which probably predates Lemuel's start undergrad based on the snac page. There also was a settlement on the southeast side of Denver called Clark(e) Colony  (named after Rufus Clark) in the early 1900's that might be related (see https://arctos.database.museum/guid/DMNS:Bird:9653).
I don't think there's enough evidence to convince me that our Mr. Clarke is the same person as Lemuel.

**Comment by acdoll** [comment]
Did I mention that Rufus was the Potato King of Colorado?
https://www.greenwoodvillage.com/DocumentCenter/View/373/Historical---Clark-County--The-Potato-King?bidId=

**Comment by ewommack** [comment]
Ok I've moved the UWYMV specimens out and stopped the merge. Clarke is set to become a verbatim agent since I couldn't find any additional data for it. How strongly do you think Clarke might be the Potato King, versus the other Clarkes in Arctos?
