### ISSUE TITLE
Help needed to modify a label

### ISSUE THREAD

**Issue by jebrad** [ArctosDB/arctos#5272]
Hello, I need to slightly modify our box labels.  The file is currently in the legacy reports: uwbm_mammal_box.cfr, I will add a PDF showing how it printed 9 records, at the bottom of this.

Modifications desired: 
1) We want to move the coords and date into the Event Box, making that box 1 line taller (aka extend the dimension of the box to include coords anchored to lower Left, and date anchored lower R).  
2) have start of text in event box be Higher Geography, which will also print county (currently it is printing Country and State before the specific locality).
3) print static "Parts:" before the list of parts
4) change static "Acc. No." to "Accession #: "
5) print Repro data after the sex, with comma, if we have any Repro data.

I have someone here who built that label using the UAM box label as a template, so I could ask her to help modify this cfr.

But @Jegelewicz said there had been a lot of label work done recently, so I would be better asking @dustymc /filing an issue here, in case someone is doing this type of work already.
[uwbm_mammal_box(1).pdf](https://github.com/ArctosDB/arctos/files/9975996/uwbm_mammal_box.1.pdf)

**Comment by dustymc** [comment]
Going active on this, all labels need brought into the new system in some way.

I think the first question is one of format, do you prefer html+css or word-or-whatever (eg csv-only report)?

**Comment by jebrad** [comment]
Excellent. We have made some progress since my first post: I asked Elly (Burke IT) to modify ours in this way, she originally built ours based on the UAM one. I believe the modifications were close to being finished when the Burke had that IT cluster and all work on my labels stopped.  My next plan action was to ask Elly to watch last week's webinar and then re-do our labels in the best format, but I am waiting for the smoke to clear before asking our IT for anything.
I am happy to take this label modification project out of Elly's hands and into yours, if that works for you. I could ask for Elly's most recent version, I am not sure how close she got to making all my changes, or if it would even help you at all.  
And as for your first question "one of format": I have no idea. Ideally I would prefer our labels to be easy for me (Elly) to modify things, and eventually I will need to do double-sided skin tags.  Not sure if html+css is the best format to get those qualities, or to do word or something else - my hope was that Elly would advise me on that after watching last week's webinar and getting an idea of what is working for other people.

**Comment by dustymc** [comment]
>double-sided skin tags

As a founding member of the Coalition to Abolish Paper I'm far from a labelologist, but those are possibly better done in mailmerge, and if you've got to manage one thing there maybe it makes sense to do everything there. (Or not...)

@lkvoong @mkoo @acdoll  have all been more involved in the layout/print side of this than I and might have better advice.

**Comment by Jegelewicz** [comment]
@jebrad Also resolved with the new box labels? If so, please close, If not, let me know what you need!

**Comment by jebrad** [comment]
Yes this is done.  My main problem was not asking @Jegelewicz for help sooner.  I'll try to avoid that one in the future!
