### ISSUE TITLE
Arctos Down - from https://github.com/ArctosDB/arctos/issues/5275#issuecomment-1310951554

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#5276]
Please complete to the best of your ability.

## Unplanned Outage
 - Date and time (**please add time zone from which you are reporting**) outage discovered: from https://github.com/ArctosDB/arctos/issues/5275#issuecomment-1310951554
 - Describe the outage (Arctos down or only some part not working?): @dustymc says he has contacted TACC

## Communication before/during outage
- [x] Pin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [x] Email sent to AWG  
- [x] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [x] Email sent to AWG 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by lin-fred** [comment]
down for me too, tweeted

**Comment by acdoll** [comment]
Seems to be working now (though a little slow)

**Comment by cjconroy** [comment]
It was working for me. I created a loan, added parts, but now I cannot even get to the search page. I get the attached error. 
<img width="1106" alt="Screen Shot 2022-11-10 at 3 45 19 PM" src="https://user-images.githubusercontent.com/5749672/201229391-751e6ef1-8900-4496-bc58-6f8852102ffe.png">

**Comment by acdoll** [comment]
I spoke too soon. It was up and working; now I can get to pages, but am getting errors on all pages:
![image](https://user-images.githubusercontent.com/12507297/201229632-3b5ba7b9-1c19-4e41-841e-f67028f87022.png)

**Comment by ewommack** [comment]
I just tried to get to the home page and got the Arctos error message with additional info:
This message has been logged as 21623BD6-8C0A-4FCF-995FFA5A9E741319. Please [contact us](https://github.com/ArctosDB/arctos/issues/new?assignees=&labels=contact&template=contact-arctos.md&title=error%20feedback) with any information that might help us to resolve this problem. For best results, include the error as text and a detailed description of how it came to occur in the Issue.

**Comment by ewommack** [comment]
@dustymc says we may be getting somewhere soon : https://github.com/ArctosDB/arctos/issues/5275#issuecomment-1311063236

**Comment by ewommack** [comment]
Looks like we're back up

**Comment by ewommack** [comment]
I've logged in and done data entry, I think we're all back

**Comment by lin-fred** [comment]
it is back for me too...
