### ISSUE TITLE
Arctos Down - 

### ISSUE THREAD

**Issue by barke042** [ArctosDB/arctos#5277]
##Unplanned Outage
 - Date and time (**please add time zone from which you are reporting**) outage discovered: 7:49 CDT, 11 November 2022
 - Describe the outage (Arctos down or only some part not working?):
Arctos timing out multiple times on multipel browsers: "An error occurred during a connection to arctos.database.museum. PR_IO_TIMEOUT_ERROR"

## Communication before/during outage
- [x] Pin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [x] Email sent to AWG  
- [x] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [x] Unpin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [x] Email sent to AWG 
- [x] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by lin-fred** [comment]
it is down for me too

**Comment by ewommack** [comment]
I can't reach the page either

**Comment by barke042** [comment]
I am getting through now.

**Comment by barke042** [comment]
Point of information: if I started this issue and it now appears resolved, do I close it or do I wait for something more official?

**Comment by ewommack** [comment]
Hi @barke042,

This issue type has a couple things officers have to do for communication, but if you see we've taken care of it (sent out the "Arctos Down" and "Arctos back-up" communication, please feel free to close.
