### ISSUE TITLE
Arctos not correctly converting from NAD 27

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#5279]
**Describe the bug**
I was using the coordinate converter today to help georeference a specimen with coordinates in multiple formats, and was playing around with some other converters and realized that Arctos is not correctly converting NAD 27.  I initially noticed this in the coordinate converter, but also tested this with a locality with original NAD 27 utm coordinates that had been converted using the bulk edit locality tool and found the error there too.

Which leads me to the conclusion that I now have thousands of incorrectly converted localities, which is an incredibly huge mess to clean up.

**To Reproduce**
1. Go to edit locality
2. Click on coordinate converter
3. Enter NAD 27 coordinates
4. See that the coordinates are exactly the same in NAD 27 and NAD 83

**Expected behavior**
The coordinates should be correctly converted.

**Screenshots**
![NAD27](https://user-images.githubusercontent.com/47402809/201733296-3a33d38b-8163-443f-af4e-871bd3cfc037.PNG)
![NAD83](https://user-images.githubusercontent.com/47402809/201733321-05712bd7-68e9-4a85-82b8-884f0acd667f.PNG)
![difference](https://user-images.githubusercontent.com/47402809/201733385-c4640847-e907-4b8e-a7dc-17915aa1f99a.PNG)

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Comment by dustymc** [comment]
See https://arctos.database.museum/info/ctDocumentation.cfm?table=ctdatum NAD27 is using https://epsg.io/4267, you need https://epsg.io/26710 (or something like it). (And maybe some code needs adjusted, I think maybe we did something crazy for UTMs, that needs tested - and I need data to do that with - once there's a new CT value.)

I think you can probably just propose a 'datum' (string) with whatever SRID you need and we can go ahead with this, but maybe we should convert existing strings to something a little less fluffy and a little more functional (``https://epsg.io/4267`` is nice...) to avoid this sort of thing in the future.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
https://github.com/ArctosDB/arctos/issues/4255
https://github.com/ArctosDB/arctos/issues/4271

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
TBH I'm panicking right now, because I used edit locality to mass converted ~7000 utm localities that were in NAD 27. It took me months to create that conversion file. Some stuff has been georeferenced since then, so I can't just rerun that csv through edit locality once this is fixed.

**Comment by dustymc** [comment]
@mkoo can you take a look at https://github.com/ArctosDB/PG_DDL/blob/master/function/convertRawCoords.sql please - line 160 is UTM handling, https://arctos.database.museum/info/ctDocumentation.cfm?table=ctdatum and https://arctos.database.museum/info/ctDocumentation.cfm?table=ctutm_zone are the CT's with SRIDs.

I think my comment above is incorrect, I am converting from UTM (using ctutm_zone) into whatever datum is given, and then (using ctdatum) into WGS84. If that's the problem, advice on how to handle this would be very appreciated. If it's not, then I'm not sure what's going on here.

And I'm certain this got a lot of testing, its concerning that an apparent problem is only showing up now.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Here is an example of a locality where edit locality bulk load converted incorrectly: https://arctos.database.museum/editLocality.cfm?locality_id=11104355

This load, according to the edit history, was completed 2022-07-19.

**Comment by dustymc** [comment]
Looks like that came in with an event (https://arctos.database.museum/editEvent.cfm?collecting_event_id=11435530) which has as-entered data.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Nope, Teresa created those events before Arctos could convert from UTM, but when it still accepted verbatim UTM.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
What is the status of fixing this?

Also, I think to fix this:

> I used edit locality to mass converted ~7000 utm localities that were in NAD 27. It took me months to create that conversion file. Some stuff has been georeferenced since then, so I can't just rerun that csv through edit locality once this is fixed.

I will need to search the (non-attribute) georeference source for the exact phrase I used in my bulk edit so that I can rerun the bulk edit sans localities that have been georeferenced since the bulk edit.

**Comment by dustymc** [comment]
>status

I don't think I understand what's going on, hoping someone with postgis+utm know-how will step in - @mkoo ??

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Between this and https://github.com/ArctosDB/arctos/issues/4169#issuecomment-1374132539 it seems like datum in Arctos is a mess, and perhaps not just for UTMs??? I know between November and December holidays and big Arctos updates, things have been busy, but Arctos is actively creating bad data. Every locality request I've had to do since this error I've had to spend hours manually correcting data. I've got a locality request I've been trying to do today that should have taken 30 minutes, but will probably end up taking at least five or six hours because I have to correct the data on about 50 localities. Plus it has put a roadblock on trying to get our federal partners to use the database.

**Comment by dustymc** [comment]
I'm still not sure where to go with this - @mkoo ??

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
@mkoo can you assist on this? This has become a huge roadblock for us.

**Comment by lin-fred** [comment]
> Between this and [#4169 (comment)](https://github.com/ArctosDB/arctos/issues/4169#issuecomment-1374132539) it seems like datum in Arctos is a mess, and perhaps not just for UTMs??? I know between November and December holidays and big Arctos updates, things have been busy, but Arctos is actively creating bad data. Every locality request I've had to do since this error I've had to spend hours manually correcting data. I've got a locality request I've been trying to do today that should have taken 30 minutes, but will probably end up taking at least five or six hours because I have to correct the data on about 50 localities. Plus it has put a roadblock on trying to get our federal partners to use the database.

@mkoo This is high priority and needs to be focused on, what's going on?

**Comment by mkoo** [comment]
@dustymc I look into this and saw nothing that suggested itself to me, maybe a zoom call would be more efficient 
do you have to time today 2-3? text me pls!

**Comment by dustymc** [comment]
Yes, I can do 2, see you in zoom then.

**Comment by mkoo** [comment]
ok this is the last piece of the puzzle -- the other NAD27/UTm's 

@dustymc please import 
[ctutm_zone_load.csv](https://github.com/ArctosDB/arctos/files/11057338/ctutm_zone_load.csv)

I did the first one but these are the rest of them
(does not deal with the other subunit zones like S,R, T, etc)

Each of these entries look like the inital one I loaded: NAD27 / UTM zone 1N etc
So hopefully will be easy to distinguish from the WGS84 zones

Will address #5525

**Comment by mkoo** [comment]
Looks like these have been loaded so closing 
I'll file another one for the MGRS zones -- that may take longer to find since it may require opening a book (!)
