### ISSUE TITLE
SQL help

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5281]
@dustymc can you write me some SQl to get all of the collection codes and their descriptions?

![image](https://user-images.githubusercontent.com/5725767/201794322-bf30a9c1-5114-4823-9006-46055060b07d.png)

I need this for all collections, not just those with more than 1 object cataloged or I'd get it from the portals page and stats doesn't include the description.

**Comment by dustymc** [comment]
>SQl

select * from collection

**Comment by Jegelewicz** [comment]
HAHAHAHA! Sheesh.

Thanks

**Comment by Jegelewicz** [comment]
But wait -that doesn't give me all collections? I only got 178, but there are 294. So I can only get the collections I have edit access to?

**Comment by dustymc** [comment]
There is nothing I can do to change this.
