### ISSUE TITLE
Can we name a "we don't know" locality

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5282]
The geography already exists = no higher geography recorded

and so does the locality = No specific locality recorded.

Can we give this one big unknown place a name to make it easy to use?

I was going to do this, but there appear to be a lot of them (644!!!). This is maybe OK because they include things like elevation, depth and locality attributes, but I'd like to see if we can name a "we don't know" that is really we don't know anything about the place this came from. Can someone help me pick which of the 644 to do this with?

**Comment by Jegelewicz** [comment]
I'm thinking this would be a good one? https://arctos.database.museum/place.cfm?action=detail&locality_id=80907

**Comment by ewommack** [comment]
I like the text, but what are the list of geographic features in the table Service-Derived Place Names (all localities), and why does the Geography Map show localities in the Bay Area of California?

**Comment by dustymc** [comment]
>what are the list of geographic features in the table Service-Derived Place Names (all localities), and why does the Geography Map show localities in the Bay Area of California?

Both are from someone knowing but refusing to assert geography. Those should be moved to https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10016350.

(And the service derived place names are all coming from Arctos now that we have sane and consistent geography so those will be a lot more familiar as the cache refreshes, but that's CPU limited so might take a while.)

**Comment by Jegelewicz** [comment]
So does it seem appropriate to name https://arctos.database.museum/place.cfm?action=detail&locality_id=80907?

And should the name be locality_unknown? Or something else?

**Comment by dustymc** [comment]
There are now 863 named localities using "we don't know" for some reason, 
```

 NULL Locality Data
 temp_11169564
 temp_11193770
 temp_11265585
 VRG unknowns
```

seem the best candidates for this, but ??????????

I would NOT recommend [80907](https://arctos.database.museum/place.cfm?action=detail&locality_id=80907) as long as it has the verbose remark instead of NULL.

I'm not sure what might be actionable here so closing.
