### ISSUE TITLE
Cannot Select Higher Geography

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#5284]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
In data entry, I cannot select higher geography from the pop-up window.

**To Reproduce**
1. Go to the data entry form.
2. Type a locality into higher geography field; in this case I wrote: "United States, Illinois, LaSalle County"
3. The "Pick Geography" window will pop up, but there is no way to select the geography I want. Didn't there used to be a button that said "Pick"? Instead there is red text that says "higher geography is required for this operation"
![image](https://user-images.githubusercontent.com/93737929/201985294-394813da-5f01-4849-8348-3822ff142888.png)

**Expected behavior**
A way to select the correct geography and have it autofill into the data entry form. Since I typed the higher geography exactly as it appears under "Pick Geography", I was able to save the new record, but the text field won't change from red, even if the entered text is correct.
![image](https://user-images.githubusercontent.com/93737929/201986485-c9833be8-1e02-4013-98ed-bbd5f3f0eb43.png)

**Desktop (please complete the following information):**
Firefox

**Comment by wellerjes** [comment]
The "pick" button is back; thank you!

**Comment by Jegelewicz** [comment]
OK we have the same problem in create locality.

**Comment by dustymc** [comment]
You're using Chrome, or you've customized and removed higher_geog from your results. (Or maybe the bug I fixed customized for you, but I can't see how.)

**Comment by Jegelewicz** [comment]
It wasn't me - someone was screen sharing and I was watching - we got around it by cloning a locality.
