### ISSUE TITLE
Feature Request - loan item picks

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5285]
**Is your feature request related to a problem? Please describe.**

I am going to [rebuild and modernize specimen search and results](https://github.com/ArctosDB/arctos/issues/2745). The injected loan pick thing is antique and crusty and not very compatible with modern architecture.

**Describe what you're trying to accomplish** 
* Not try to do crazy things to the results table, all in the name of sanity and sustainability
* Make the loan pick thing better

**Describe the solution you'd like**

I think this is best done via a 'manage' option that redirects to a loan part picker table. This would be a static/pre-defined table, but we can add WHATEVER to it, and it would be born with the correct part-centric structure. It would also be completely internal so there's lots more flexibility than there can be in anything which must also support public users.

Another possibility is a 'pick loan' button which pops open an overlay (perhaps similar to the current embedded thing). I'm not crazy about this idea - it's a potentially expensive check in a very expensive form - but I can explore how possible this is if absolutely necessary.

**Describe alternatives you've considered**

I'm up for anything.

**Additional context**

n/a

**Priority**

Relatively high - I'd rather not surprise anyone with this, and I'd very much like some guidance from the users who do this sort of thing. I'll eventually be forced to interpret silence as enthusiastic approval for whatever I'm thinking at the time, so input please!

**Comment by campmlc** [comment]
Any chance we can design this for public use? I'd love for researchers to
be able to do a search or even multiple searches, and add items from each
search to a little an request form. Maybe this could be a modified version
of Saved Search? So they could add to a saved search to get a final list
that could be submitted as a url to request these samples?

**Comment by campmlc** [comment]
Add items to a *loan* request form, which is a saved search.

**Comment by dustymc** [comment]
>design this for public use

I think for the sake of this discussion just "no" - maybe that'll change if https://github.com/ArctosDB/arctos/discussions/4917 ever does something, but we're not there yet.
