### ISSUE TITLE
Unable to create an agent

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5288]
I attempted to create a person agent with a name and an email address and nothing happens. I get the familiar message

![image](https://user-images.githubusercontent.com/5725767/202046993-e8b4d0cd-7166-4861-82c4-6bb1e43f5220.png)

With absolutely no indication of what the "problems" may be. So I click on "click here to force creation" and nothing happens.

**Comment by Jegelewicz** [comment]
Screenshots for context

![image](https://user-images.githubusercontent.com/5725767/202047334-d55b4ef0-44a6-4a1f-8868-e3170f7857fa.png)

![image](https://user-images.githubusercontent.com/5725767/202047366-9839bebe-9262-43ad-94d8-39614ebe25db.png)

**Comment by ebraker** [comment]
@Jegelewicz not sure what the issue is, but I was able to create two agents this morning. @dustymc thanks for moving the "force creation box" down the page!

**Comment by Jegelewicz** [comment]
It worked for me an hour later.
