### ISSUE TITLE
coordinate value error

### ISSUE THREAD

**Issue by kmkocot** [ArctosDB/arctos#5290]
# Error Text
coordinate value error

# Where it happened
I was trying to bulkload the attached file. 
[Euphrosinid_bulkloader.csv](https://github.com/ArctosDB/arctos/files/10020708/Euphrosinid_bulkloader.csv)

# Steps to get there
I thought I had all the columns related to the GPS coordinates entered in correctly but I'm getting this error consistently. When I switched them to decimal degrees I didn't have this issue. I'm just trying to understand how to do this correctly in the future.

# Problem
**Community response to describe the problem that caused the error**

# Solution
**Community response with directions for how to correct the problem**

Thanks!
Kevin

**Comment by dustymc** [comment]
Same problem as https://github.com/ArctosDB/arctos/issues/4716 (you're using the wrong columns, probably because the builder has them scattered), https://github.com/ArctosDB/arctos/issues/5193 will provide a fix.

**Comment by kmkocot** [comment]
Thank you! That wasn't clear to me from this page: https://handbook.arctosdb.org/documentation/bulkloader.html
