### ISSUE TITLE
Other Identfiers for Collections

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5291]
I can currently assign at least 3 identifiers to many of the Arctos collections. Take the MVZ bird collection for an example:

Arctos Identifier: https://arctos.database.museum/collection/MVZ:Bird

NCBI Identifier: https://www.ncbi.nlm.nih.gov/biocollections/107170
GBIF Publisher: https://www.gbif.org/dataset/e3b959d6-fcbe-4a28-a166-e4a807c340a0
GRSciColl Identifier: https://www.gbif.org/grscicoll/collection/910442b2-e0aa-46a9-b3dc-5a4efb1ed3a3

I would think that collections would want to keep track of these and make sure that their data is correct in the various places it might be appearing. Also to allow others to match up an Arctos collection using any of the potential identifiers it might be found under. we currently allow for two "other identifers" in manage collection, but these are not really meant for the situation above. I propose that we need other identifiers for collections in the same way we have them for catalog records, with types controlled by a code table. Initial values for the collection identifier code table would be those listed above.

Also, proper NCBI identifiers might make finding GenBank stuff better?

**Comment by campmlc** [comment]
If we make each collection an agent as standard procedure, these
identifiers could be associated agent names or IDs?

**Comment by dustymc** [comment]
https://arctos.database.museum/agent/21334678

Maybe there's some UI-mergey-stuff to be done, maybe https://github.com/ArctosDB/arctos/issues/6746 will change something, but I think there's a place for these data (thanks in part to GUM) - closing.
