### ISSUE TITLE
Depth units not autofilling in record entry after picking locality/event

### ISSUE THREAD

**Issue by genevieve-anderegg** [ArctosDB/arctos#5292]
**Describe the bug**
When picking a locality or collecting event when entering a catalog record, if the event/locality has a depth associated with it (e. g., 25 meters), the units of the depth will not autofill after pulling and syncing the event/locality

**To Reproduce**
Go to enter a catalog record, select an event or locality with a depth, pull and sync the even or locality. Depth units are not synced.

**Expected behavior**
It would be nice to have the depth units autofill with the min and max depth values, just to decrease confusion when entering the record, and eliminate the possibility that a databaser might then enter the incorrect depth unit when they see the field isn't filled (e. g., entering "fathoms" instead of "meters"

**Screenshots**
Here is a locality with a depth (locality 10962761)
![Capture](https://user-images.githubusercontent.com/83782023/202243140-15076a2f-333f-4299-a702-efa70861aa34.PNG)

After syncing the locality, depth units is not synced; or if it is, it's not viewable to the databaser.
![Capture2](https://user-images.githubusercontent.com/83782023/202243478-47f58efc-19bb-4b17-a8ee-a50446238831.PNG)

**Desktop (please complete the following information):**
Windows, Chrome

**Comment by sharpphyl** [comment]
@dustymc 

> [dustymc](https://github.com/dustymc) added this to the [Next Task](https://github.com/ArctosDB/arctos/milestone/2) milestone [on Dec 20, 2022](https://github.com/ArctosDB/arctos/issues/5292#event-8081746754)

The depth units are still not always filling in as expected.  Is a correction in the queue anywhere?  While it's not urgent, it's confusing for data entry volunteers.

**Comment by Jegelewicz** [comment]
This does seem like Arctos isn't performing as expected. There are [19 open "bug" issues](https://github.com/ArctosDB/arctos/issues?q=is%3Aopen+is%3Aissue+label%3ABug) and it seems like these should get addressed as quickly as possible after "Arctos is going to die" issues. Of the 19, [8 include the "Next Task" milestone](https://github.com/ArctosDB/arctos/issues?q=is%3Aopen+is%3Aissue+label%3ABug+milestone%3A%22Next+Task%22). What do we have in process that is higher priority? @dustymc how are you setting priority now? Any idea how long these 8 would take to tackle?

**Comment by genevieve-anderegg** [comment]
It would be great to get this addressed, as it creates confusion with volunteers during data entry. It's not the most dire, but should be fixed at some point. Is it a complex thing to deal with?
