### ISSUE TITLE
Fix "Loan-like" transactions and loan bulkloader menu terms

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#5293]
Can we fix what we are calling Transactions to something comprehensible?
I would argue strongly that this is not what we want our users to have to navigate:
![image](https://user-images.githubusercontent.com/14808196/202264056-d7ef9641-cda4-4b28-8852-ead4e301e85d.png)

I have to use the loans and bulkloader tabs multiple times weekly, and after months of looking at this I still find my eyes get crossed just attempting to figure out this dropdown and what these terms really mean. 
"Loan-like transactions" needs a better term. Let's use Loans - and then clarify the different types.
"Part-linked" vs "record-linked" - what does that actually mean? How is this different from a part vs a data loan? We need clear terms that are just one or two words - not word salad.

We owe it to users to make our terms and our user interface comprehensible. The current situation is not. 

Priority: High. We are bringing in many new collections. We want them to be able to use our tools.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/4189
