### ISSUE TITLE
Nomenclature spelling update: Ax to Axe

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#5294]
Can someone (@Jegelewicz ?) please update the spelling for all the references to axes in the Nomenclature taxonomy to be spelled "axe" instead of "ax"? The preferred spelling of that object type includes the e at the end.
Hopefully there's a bulkload update find & replace option?

<img width="1142" alt="Screenshot 2022-11-16 at 11 55 09 AM" src="https://user-images.githubusercontent.com/17605945/202292586-7d3b2923-d086-4fa1-bbcb-92d5230cc478.png">

<img width="896" alt="Screenshot 2022-11-16 at 12 00 23 PM" src="https://user-images.githubusercontent.com/17605945/202293182-506902bd-1a79-46db-a16b-c867a22a863d.png">

<img width="1159" alt="Screenshot 2022-11-16 at 12 01 08 PM" src="https://user-images.githubusercontent.com/17605945/202293319-e7df3f6a-c490-45e7-aa68-8f106303ad11.png">

**Comment by Jegelewicz** [comment]
@AJLinn the way to do this is to add the new terms, then re-identify everything using the old terms with the new terms, then synonomize (and probably quarantine) the old terms. I can put this on my to do list, but I probably will not be able to make all of the re-identifications and it may be a while before I get to it.

**Comment by AJLinn** [comment]
Wow... that seems overly complicated to fix a spelling issue... I would have thought it worked like agents? Correct the spelling in one place and it fixes it everywhere it's used? 🤔

I doubt there are many/any existing uses other than the ones I just made but I can try to do that... I think?

**Comment by Jegelewicz** [comment]
We cannot change any taxon name that is being used - they aren't like agents in that way. This is because I could easily change the entire concept of an identification and not know I did it.

**Comment by Jegelewicz** [comment]
If any of the Ax names aren't being used, then they can just be changed, but it might make sense to have the alternate spellings in the list for discoverability.

**Comment by Jegelewicz** [comment]
Axe created and Ax related as potential alternate spelling of Axe
Axe Hammer created and Ax Hammer related as potential alternate spelling of Axe Hammer
Axe Sheath created and Ax Sheath related as potential alternate spelling of Axe Sheath
Axe Weapon created and Ax Weapon relates as potential alternate spelling of Axe Weapon

**Comment by Jegelewicz** [comment]
All names above added.

**Comment by Jegelewicz** [comment]
Realationship of potential alternate spelling from "Ax" to "Axe" terms loaded.

**Comment by Jegelewicz** [comment]
Classifications added to Arctos Culture for all of the above with all "Axe" terms updated.

**Comment by Jegelewicz** [comment]
@AJLinn all of the "Axe" terms are now available to you so that you can change your identifications as needed. Closing.

**Comment by AJLinn** [comment]
You are the best! I'll assign those ASAP!
Thank you-
