### ISSUE TITLE
Unable to log in with temporary password

### ISSUE THREAD

**Issue by szaborac** [ArctosDB/arctos#5300]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I am unable to log in using the temporary password I obtained 

**To Reproduce**
1. Go to "https://arctos.database.museum"
2. Click on the Log in button
3. Use the following login credentials "Susitna" and "7(N)-_729wE" (the temporary password I obtained because I couldn't remember my password)

**Actual Behavior**
I am getting the following message:
"Authentication failed. Additional Information: Access restricted. "

**Expected behavior**
I should be able to log in and be forced to change my password.

**Desktop (please complete the following information):**
 - OS: Mac High Sierra
This is independent of browser type (i.e., I tried it on all of them. Same result)

I got the requested Lost Password email impressively quickly. I just can't log on with the temporary passwords provided. I am blocked from work.

**Priority**
Priority 1, Severity 1 (blocking me from work)

**Comment by Jegelewicz** [comment]
I just reset your account - please try again.

**Comment by szaborac** [comment]
Thank you.

Just an FYI: It's not asking me to reset my password. Should I have
expected that?

**Comment by Jegelewicz** [comment]
No, I just reset, I didn't request a temporary password. I think you are OK.

**Comment by szaborac** [comment]
Even better - I'm able to log in!

Thank you!!!!
