### ISSUE TITLE
Arctos down? Get this error trying to access

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#5301]
** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **

** Outages should be reported to the contacts listed at https://arctosdb.org/arctos-down/ **

** Arctos Documentation is http://handbook.arctosdb.org/ **

** Learn more about Arctos at https://arctosdb.org/ **

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **

**Comment by dustymc** [comment]
Arctos is not down.

**Comment by campmlc** [comment]
It is back up. But two of us at MSB on different floors and different
computers got the same error message. Maybe UNM weirdness.
