### ISSUE TITLE
Code Table Request - Add reproductive tract to Inv collections

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#5307]
**How to Use This Form**
This is a template with examples and guidance on how to best communicate with the Arctos Working Group. Please delete this section along with anything in square brackets ```[ ] ``` below before submitting. 

[ **Instructions for reference:** ]
[ Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html ]

[ Code Table Documentation is https://handbook.arctosdb.org/how_to/How-to-Use-Code-Tables.html ]

[[Video Tutorial - Submit a Code Table Request](https://youtu.be/t2jHbsRA3lk)]

**Goal**
be able to add reproductive tract parts to Inv collections.

**Context**
I have dried up genitalia of a snail I need to associate with my record.

**Table**
part name

**Proposed Value**
reproductive tract (existing value)

**Proposed Definition**
see existing code table

**Collection type**
Inv

**Available for Public View**
yes

**Other ID BaseURL**
[  For OtherIDs, provide the following *or* explain why the unresolvable ID type is necessary:
1. "Base URL" with which to prepend entered values, and
2. A functional example URL, which should consist of the base URL provided in (1) plus a relevant value.  ]

**ID_References**
[  If the request involves https://arctos.database.museum/info/ctDocumentation.cfm?table=ctid_references, the changes must be coordinated with the Database Admin team for notifications to function.  ]

**Priority**
[  Please choose a priority-label to the right.  ]

**Comment by Jegelewicz** [comment]
Would you prefer [genitalia](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#genitalia)?

**Comment by mvzhuang** [comment]
I was thinking about that, but my part includes the whole tract?  genitalia is "external sex organs". Anyone know what snail people use? @lin-fred @Nicole-Ridgwell-NMMNHS . One of these description papers uses "reproductive anatomy", so i'm leaning towards rep tract.

**Comment by Jegelewicz** [comment]
Added both.
