### ISSUE TITLE
Database error prevents working in Arctos

### ISSUE THREAD

**Issue by szaborac** [ArctosDB/arctos#5308]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I am getting database errors when trying to do *anything* in Arctos

**To Reproduce**
1. Go to 'arctos.database.museum' and log on
2. Click on 'Search' menu
3. See error, below
ERROR_ID | 84A4C171-9854-4160-850042050C6F9D1E
-- | --
ERROR_TYPE | SQL
ERROR_MESSAGE | ERROR: current transaction is aborted, commands ignored until end of transaction block
ERROR_DETAIL |  
ERROR_SQL | select SEARCH_NAME,URL 	from cf_canned_search,cf_users 	where cf_users.user_id=cf_canned_search.user_id 	and username='Susitna' 	and URL like '%SpecimenResults.cfm%' 	order by search_name

<p>request dump:</p>
request
--
node_name | stringarctos-2021 | string | arctos-2021
string | arctos-2021
rdurl | string/SpecimenSearch.cfm | string | /SpecimenSearch.cfm
string | /SpecimenSearch.cfm
uui | string | string |  
string |  
uuid | stringEBF2E1F2-E5FC-4751-9EE1376E827EF20B | string | EBF2E1F2-E5FC-4751-9EE1376E827EF20B
string | EBF2E1F2-E5FC-4751-9EE1376E827EF20B

exception dump
lucee.runtime.exp.DatabaseException: ERROR: current transaction is aborted, commands ignored until end of transaction block at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553) at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285) at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323) at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481) at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401) at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:322) at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:308) at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:284) at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:279) at lucee.runtime.type.util.QueryUtil.execute(QueryUtil.java:320) at lucee.runtime.type.QueryImpl.execute(QueryImpl.java:287) at lucee.runtime.type.QueryImpl.<init>(QueryImpl.java:235) at lucee.runtime.tag.Query.executeDatasoure(Query.java:1134) at lucee.runtime.tag.Query._doEndTag(Query.java:699) at lucee.runtime.tag.Query.doEndTag(Query.java:565) at specimensearch_cfm$cf.call(/SpecimenSearch.cfm:32) at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:1015) at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:938) at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:219) at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:44) at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2482) at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2468) at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2439) at lucee.runtime.engine.Request.exe(Request.java:45) at lucee.runtime.engine.CFMLEngineImpl._service(CFMLEngineImpl.java:1198) at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:1144) at lucee.loader.engine.CFMLEngineWrapper.serviceCFML(CFMLEngineWrapper.java:97) at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:51) at javax.servlet.http.HttpServlet.service(HttpServlet.java:590) at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74) at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129) at org.cfmlprojects.regexpathinfofilter.RegexPathInfoFilter.doFilter(RegexPathInfoFilter.java:47) at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68) at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68) at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117) at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at runwar.Server$1.handleRequest(Server.java:510) at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52) at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:280) at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79) at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134) at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131) at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:260) at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79) at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100) at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387) at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852) at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35) at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019) at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558) at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449) at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280) at java.lang.Thread.run(Thread.java:750) 

Different pages give variations on this same error: current transaction is aborted, commands ignored etc.

**Expected behavior**
Not this.

**Desktop (please complete the following information):**
 - OS: Mac High Sierra
 - Browser doesn't matter

**Priority**
I am entirely blocked from work.  ERROR_ID | B4576D40-F45D-44BA-BE3A66AF52242D9A

**Comment by szaborac** [comment]
Trying to add update a locality; I was adding an error range for a record I
had just bulkuploaded (ALAAC = L22911).

**Comment by Jegelewicz** [comment]
So I just looked at the record and there isn't an error for the coordinates, so that update seems to be where things went wrong, but I don't see anything in the log to tell me what happened. This is a task for @dustymc

**Comment by Jegelewicz** [comment]
It could be this but I don't know how to fix it.

ERROR: deadlock detected Detail: Process 80622 waits for ShareLock on transaction 1233947223; blocked by process 81943. Process 81943 waits for ShareLock on transaction 1233947085; blocked by process 80622. Hint: See server log for query details. Where: while inserting index tuple (6182,5) in relation "iu_oidnum_id_typ_disp_refs"

INSERT INTO coll_obj_other_id_num (collection_object_id, other_id_type, other_id_prefix, other_id_number, other_id_suffix, id_references ) VALUES ( 30920828, 'U. S. National Park Service accession', 'BELA-', null, null, 'self' )

**Comment by szaborac** [comment]
Ah. Yes, I was doing that just before I tried updating the locality. But I
thought it worked...
Obviously not
