### ISSUE TITLE
Code Table Request - CDPHE id type

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#5309]
**Goal**
Add 'CDPHE: Colorado Department of Public Health and Environment' to the ID type code table (https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type)

**Context**
We've got hundreds of bats from this organization and have been inconsistent in how their numbers are recorded.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type

**Proposed Value**
CDPHE: Colorado Department of Public Health and Environment

**Proposed Definition**
Colorado Department of Public Health and Environment specimen number

**Collection type**
Mamm

**Priority**
normal

**Comment by dustymc** [comment]
See https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html#ctcoll_other_id_type - is there data on the other end of this identifier?

**Comment by acdoll** [comment]
Not available online; could possibly get data from direct requests: https://cdphe.colorado.gov/public-information/public-records

Is that enough to warrant its own ID type?

**Comment by dustymc** [comment]
>could possibly get data from direct requests

I think that's a bit of a gray area, but this seems (at least potentially) like a stable identifier issued by a stable entity, if you have some reason to believe correspondence might lead to data then it seems tentatively reasonable to me.

**Comment by Jegelewicz** [comment]
There was already an agent for these guys - https://arctos.database.museum/agents.cfm?agent_id=21253010 but it was going away under the new agent model. I added the url above to keep them active.

Once again this points to connecting identifiers with agents... https://github.com/ArctosDB/arctos/issues/4604

I am in favor of adding this other identifier. Any objections @ArctosDB/arctos-code-table-administrators ?

**Comment by Jegelewicz** [comment]
Added.

**Comment by acdoll** [comment]
THANK YOU!!

**Comment by acdoll** [comment]
Not a problem at all - its funny because I just trained someone on data entry with some of these specimens, so you were probably adding it as we were discussing it.
