### ISSUE TITLE
Need Help with Arctos Error - adding items to loan with new search page

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#5312]
# Error Text

<img width="1147" alt="Screenshot 2022-11-29 at 6 21 11 PM" src="https://user-images.githubusercontent.com/17605945/204700070-2af817be-8f28-45a2-9e80-ad77eb4d1e2e.png">

# Where it happened

(https://arctos.database.museum/cat_records.cfm?add_to_trans_id=21134691)

# Steps to get there
Trying to add items to a loan using the new add items form and I can't get anywhere... I put the catalog number into the box and hit Submit Query... and then the error box pops up.

Is it connected to issues people are having with the new search form in general?

# Problem
**Community response to describe the problem that caused the error**

# Solution
**Community response with directions for how to correct the problem**

**Comment by dustymc** [comment]
I might have patched that, but I can't recreate so I'm sort of guessing. More details would be most useful, especially if you can do this again.

> issues people are having 

If you know something I don't, I'd like to....

**Comment by AJLinn** [comment]
Works now... but follow up question: how do I add this to my loan when this is the results view while adding to my loan:

<img width="1448" alt="Screenshot 2022-11-29 at 7 19 58 PM" src="https://user-images.githubusercontent.com/17605945/204706802-8c507a29-e52b-4eb7-820c-342aa4a99843.png">

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/5285
<img width="247" alt="Screenshot 2022-11-29 at 8 30 22 PM" src="https://user-images.githubusercontent.com/5720791/204707923-24babab0-62b3-4668-9b5d-532415392782.png">

**Comment by AJLinn** [comment]
Thanks - figuring it out slowly... so many different steps! But sidebar... I do like the customizable search results and dragging things into the order I want them to appear! very nice.
