### ISSUE TITLE
Arctos Down - 11/30/2022

### ISSUE THREAD

**Issue by lin-fred** [ArctosDB/arctos#5314]
Please complete to the best of your ability.

## Unplanned Outage

From Dusty on AWG email:

Prod is coming and going, I suspect the proxy is running very short on connections?

Not much is getting through, but 54.246 (AWS) is definitely banging around in there if you need something to block.

I think it's completely stuck now so I suppose I'll bounce commandbox.....

## Communication before/during outage
- [x] Pin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [x] Email sent to AWG  
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by Jegelewicz** [comment]
It seems to be back.
