### ISSUE TITLE
[CONTACT] cat_records feedback

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5317]
It would be nice if the leave feedback link were on the new search page so I don't have to back up to leave input. Maybe that should be at the top of EVERY page to allow us to get more information about problems people might be experiencing with the site as opposed to the data? 

![image](https://user-images.githubusercontent.com/5725767/205108441-67b4c7a9-7e84-4e29-8195-3ad69a218125.png)

We have a very long list of choices and once you scroll past the first 15 or so, you don't know what you are looking at because the column headers are no longer visible.

![image](https://user-images.githubusercontent.com/5725767/205108089-5e22400a-6e9f-4e54-b1f4-48f0880cf5c6.png)
![image](https://user-images.githubusercontent.com/5725767/205108197-23a2ea3d-0233-4699-8833-a77d21d39af9.png)

UGH ALL of these need proper definitions. This needs a focused group to get it done.

**Comment by Jegelewicz** [comment]
Also, maybe I'm the weird one, but instead of unchecking stuff I don't want, I'd like to pick the stuff I do. How about an option to uncheck EVERYTHING instead of needing to go category by category?

![image](https://user-images.githubusercontent.com/5725767/205110149-0f101d29-adae-440e-89a2-95d00d71cf3e.png)

**Comment by Jegelewicz** [comment]
The part stuff is scattered all over the place.

![image](https://user-images.githubusercontent.com/5725767/205111611-1d763547-4edd-4a39-8cc6-75ce6de19e5d.png)

![image](https://user-images.githubusercontent.com/5725767/205111776-e33225be-03de-47b6-9711-5098953f1728.png)

**Comment by dustymc** [comment]
>EVERY

It is, in the footer, where it (probably) should be except when a special and temporary situation exists, https://github.com/ArctosDB/internal/issues/211

>column headers are no longer visible

Surely it can't be THAT confusing?! I'll see what I can come up with, but I'm not sure there's much without adding more complexity than I think is justified.

>uncheck EVERYTHING

I can do that, but it'll also let people turn GUID off. I've been trying to just assume that our audience is all smart people and won't have any problems recovering from that, but IDK how justified that is (and look up one comment....).

>part stuff is scattered

That's from the old form (default, parts, curatorial) and compounded by me jumping back and forth on organization a bunch of times. I think my current take would be to put it all together (eg organize the form according to default_order in the spreadsheet/table), but that's something the needed committee should decide. In any case it's hard-coded so I'll need some sort of ordering list.

**Comment by Jegelewicz** [comment]
> > EVERY
> 
> It is, in the footer, where it (probably) should be except when a special and temporary situation exists, https://github.com/ArctosDB/internal/issues/211

Then it would be nice if the footer was visible at all times. Depending on the page you could be for days and nobody new to the system KNOWS it is there (apparently people who use it every day don't...)

**Comment by Jegelewicz** [comment]
> >     uncheck EVERYTHING
> 
> I can do that, but it'll also let people turn GUID off. I've been trying to just assume that our audience is all smart people and won't have any problems recovering from that, but IDK how justified that is (and look up one comment....).

So uncheck EVERYTHING except the ONE THING that is REQUIRED?

**Comment by dustymc** [comment]
It's not required, there may be valid reasons to ditch it, I can't possibly know how people will use this.

**Comment by Jegelewicz** [comment]
Then why not offer the option to uncheck all?
