### ISSUE TITLE
[CONTACT] cat_records feedback

### ISSUE THREAD

**Issue by atrox10** [ArctosDB/arctos#5320]
** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **

** Outages should be reported to the contacts listed at https://arctosdb.org/arctos-down/ **

** Arctos Documentation is http://handbook.arctosdb.org/ **

** Learn more about Arctos at https://arctosdb.org/ **

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **

**Comment by atrox10** [comment]
For the new search, is it possible to keep a version of the old search page (current page) that people can still use, for those of us that like that? I realize that the public might prefer the new version with fewer boxes. Also can we bring back the "Use your last search terms"? Why did that go away? I used it all the time. Thanks for this.

**Comment by campmlc** [comment]
Yes, that's the plan.
