### ISSUE TITLE
Problem trying to add project to a loan

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#5321]
In the loan edit form, for an old loan, DGR:Bird 2012.006.Bird
Trying to add it to the project Phylogeography and ecological niche modeling of the Steller's Jay (Cyanocitta stelleri), Carla Cicero - https://arctos.database.museum/project/10000114
I select the project, but it does not autofill the project field and does not save.
![Screenshot 2022-12-01 15 08 16](https://user-images.githubusercontent.com/14808196/205169436-da643f31-58ce-41fc-b758-6bae488a6943.png)

**Comment by ccicero** [comment]
I don't have access to that loan to add to the project. @dusty ???

**Comment by ccicero** [comment]
Also, not sure if this is related: I'm trying to help @atrox10 add a description to a [project](project_id=10000347) (for some reason it didn't have a description, not sure how it got saved) and it's giving an error: 

ERROR: new row for relation "project" violates check constraint "ck_project_name_noprint" Detail: Failing row contains (10000347, Patterns of evolutionary diversification in South Pacific scinci..., Within the large skink genus Emoia there are several specialized..., null, 2009-06-25, null, null).

We tried with a just one line of the description and still getting the error. I don't see any [NO PRINT] breaks.

Here's the description:
Within the large skink genus Emoia there are several specialized species groups which represent what appears to be adaptive radiations, represented by various eco-morphs, across their ranges.  One group, the Emoia atrocostata group, was recently studied by Richmond et al. (2020) to look at the repeated evolution of the reef eco-morph versus the forest ground eco-morph across its range.  This study focusses on the Emoia cyanogaster group where there appears to be repeated evolution of the twig eco-morph and possibly the trunk eco-morph.  We hope to use genome wide SNPs to evaluate if there is repeated evolution in either of these eco-morphs.  The MVZ samples of Emoia longicauda from the far west of its range will help fill in a missing sampling gap and identify if there is much genetic structure across this species that seems to maintain a conservative morphology.

**Comment by dustymc** [comment]
Apostrophe handler fixed in next release.

@ccicero your link doesn't work so I can't update but if the checker isn't finding anything inline its usually leading or trailing spaces, or multiple whitespace characters together.

**Comment by ccicero** [comment]
@atrox10 Try again but see @dustymc comment about things to check for.

**Comment by campmlc** [comment]
I am still unable to add the above project to a loan.
