### ISSUE TITLE
Feature Request - cat record attribute search

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5322]
**Is your feature request related to a problem? Please describe.**

Attribute search is a bit overwhelming.

**Describe what you're trying to accomplish** 

 Less whelm.

**Describe the solution you'd like**

Lots of possibilities

* https://github.com/ArctosDB/arctos/issues/5316#issuecomment-1334121796 - some sort of helper/builder/better integration of the documentation/ ????

**Describe alternatives you've considered**

One alternative is to provide select individual attributes their own "search field." 

**Additional context**
 
Whatever's done for record attributes should probably be done for all attributes

**Priority**

Wishlist?

**Comment by campmlc** [comment]
Can we choose to alphabetize, or better - categorize and alphabetize within
category?

**Comment by Jegelewicz** [comment]
Maybe we can make use of this?

![image](https://user-images.githubusercontent.com/5725767/205682900-48cc573f-bdf9-4a11-8403-5c9dc2373aa7.png)
