### ISSUE TITLE
[CONTACT] cat_records feedback - can't add items to loan using new form

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#5323]
Trying to add an item to a loan using the new form and inputing the guid - nothing happened. Switched back to the old form and it worked.

**Comment by dustymc** [comment]
What I think you're saying isn't possible (it is literally only one thing, it can't be different) so you're probably not saying what I thought you were saying but that doesn't leave me with any idea of what you're actually saying. I need a screenshot, URL, better description, SOMETHING.

**Comment by campmlc** [comment]
Just tried with a different loan - same thing. Using the Add items (not old form), I input the guid and click search and nothing happens.
![Screenshot 2022-12-01 16 05 50](https://user-images.githubusercontent.com/14808196/205177944-d2a0b888-fe49-49c7-810e-c8042ee8c71e.png)

**Comment by dustymc** [comment]
https://arctos-test.tacc.utexas.edu/cat_records.cfm?add_to_trans_id=1005277

<img width="334" alt="Screenshot 2022-12-01 at 3 05 32 PM" src="https://user-images.githubusercontent.com/5720791/205177741-ca3f5e86-16f9-48e0-981c-d7803bf6cc42.png">

<img width="376" alt="Screenshot 2022-12-01 at 3 06 05 PM" src="https://user-images.githubusercontent.com/5720791/205177808-7217f069-6ec8-4834-9607-1063a45ef343.png">

>nothing happens.

Scroll down to where things happen?

**Comment by campmlc** [comment]
That tools menu does not show up in the menu in my screenshot - only Submit Query. I already had clicked on Add Items to Loan from within the Edit Loan page in order to get to this view. I shouldn't have to know there is some hidden button somewhere in a non-visible dropdown once I get there. We need tools that don't require prior knowledge or reading pages of documentation to know where the button is to click - let's make this clear for users.

**Comment by dustymc** [comment]
>tools menu does not show up in the menu in my screenshot

Then your computer is not functioning correctly; the tools menu should always be present. I need details and if possible the contents of your javascript console.

The method was discussed in https://github.com/ArctosDB/arctos/issues/5285

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I agree with Mariel, this is confusing, I had to track down the Github issue to figure out what was going on.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Also, with the new form you cannot add cataloged records to a data loan, just parts.

**Comment by dustymc** [comment]
>confusing

I think only because the old form existed. I'm not convinced that scattered all over the place is more usable than everything organized in one place, but I'm up for about anything (as long as it's sustainable and supported by the tech).

>data loan

Yea, on my list, but lets formalize that with a new issue.

**Comment by campmlc** [comment]
Attaching the screenshot again of what I see when I click on Add Items to Loan from the Loan Edit page. Note that in order to see the tool that would allow me to add items, I would have to know in advance to scroll down past what I can see on this page to the bottom, then know in advance that I need to look for a dropdown menu that says Tools, and then know that I will need to click on that menu to then open up a dropdown, and then scroll down in that dropdown **beyond what I can see** to near the end of 20+ items to find the hidden "Add Items to Transaction" selection. To do this, I must have a priori knowledge of all these hidden things  and where to find them. This is not a viable expectation for users.
This is what I see when I select "Add Items" fromt the Loan page:
![Screenshot 2022-12-02 21 37 25](https://user-images.githubusercontent.com/14808196/205423960-6176b139-1c65-4012-bb18-ca004019efcf.png)

**Comment by campmlc** [comment]
This is what I see with the current "old" form. Note that I get a message that I am searching for items to add to a loan, and I can also see all the necessary fields to search on a collection object. Even if I need to scroll down the page, everything is clearly organized and findable by category, and visually easy to locate.
![Screenshot 2022-12-02 21 48 34](https://user-images.githubusercontent.com/14808196/205424163-22005937-7c62-4d8a-9edb-b524aa665f4c.png)

**Comment by dustymc** [comment]
Added secondary notification.

**Comment by KyndallH** [comment]
Okay, I'll expand on this. I was trying to load some voles to a loan and also couldn't use the new form. Once I hit query, it just gave me the specimen list BUT no way to add them to a loan. I clicked on the specimen, and it was just its record.

<img width="971" alt="Screen Shot 2022-12-16 at 4 58 27 PM" src="https://user-images.githubusercontent.com/16887896/208218129-153e1751-d92c-4a61-ab86-24030e1150fc.png">

<img width="2138" alt="Screen Shot 2022-12-16 at 4 58 35 PM" src="https://user-images.githubusercontent.com/16887896/208218148-35360a47-56ee-40e4-b360-0e85c88be4f5.png">
