### ISSUE TITLE
Change term used in place of encumbered data to "redacted"

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5325]
### Discussed in https://github.com/ArctosDB/arctos/discussions/5232

<div type='discussions-op-text'>

<sup>Originally posted by **Jegelewicz** September  8, 2022</sup>
Many of the encumbrance actions return 'anonymous' instead of the data being encumbered. @ArctosDB/arctos-code-table-administrators think it would be better to use the term 'redacted' so that we indicate that information is known, but hidden from public view as well as using a more appropriate term for both person and non-person data. Affected encumbrance actions include:

[mask collector](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctencumbrance_action#mask_collector)
[mask coordinates](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctencumbrance_action#mask_coordinates)
[mask original field number](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctencumbrance_action#mask_original_field_number)
[mask preparator](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctencumbrance_action#mask_preparator)
[mask year collected](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctencumbrance_action#mask_year_collected)
</div>

**Comment by Jegelewicz** [comment]
This was approved at the AWG meeting on 2022-12-01.

**Comment by mkoo** [comment]
This issue is expired (over 2 years old) and still needs a actual user request. The Encumbrance committee can file one once they have decided what they actually want to see online

**Comment by mkoo** [comment]
This issue is expired (over 2 years old) and still needs a actual user request. The Encumbrance committee can file one once they have decided what they actually want to see online
