### ISSUE TITLE
Expand and refine definitions for code tables

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5326]
In addition to definitions for code table terms, we need good definitions for the things the terms are applied to.

What is a part?
What is a part attribute?
What is a catalog record attribute?
What is an other identifier?
What is an identification?
What is a "collector agent"?

In addition to what they are, what are our expectations of these things?

What needs to be added to the list?

**Comment by dustymc** [comment]
Who's the audience? The table browser and code tables, all of which are public, fully define these things.

**Comment by Jegelewicz** [comment]
# Parts
Parts are physical entities, in contrast to [Cataloged Items](https://handbook.arctosdb.org/documentation/catalog) (an abstract entity) or binary objects (such as Images). One or many parts may comprise a Cataloged Item, and parts may be defined as the minimal units for which [storage location](https://handbook.arctosdb.org/documentation/container), usage, and condition are tracked. (“Parts are things to which you can stick barcodes.”) Parts are generally the equivalent of [dwc:MaterialSample](https://dwc.tdwg.org/terms/#materialsample)

**Comment by Jegelewicz** [comment]
@ebraker says that "parts" are whatever we are managing, so digital stuff belongs there too. And I say that even digital media is in a physical storage location (which you can barcode), so we think that media belongs in parts.

Parts needs a more appropriate definition and we need to ensure documentation all matches up.

**Comment by Jegelewicz** [comment]
Change part section to "catalog record components"

**Comment by ewommack** [comment]
> One or many parts may comprise a Cataloged Item, and parts may be defined as the minimal units for which [storage location](https://handbook.arctosdb.org/documentation/container), usage, and condition are tracked.

I like this section of the definition in particular. There are many parts or there may be one part, they are found somewhere, they get used, and we want them tracked please.

**Comment by dustymc** [comment]
>Parts are ... or binary objects

Nope.

**Comment by dustymc** [comment]
Bringing this back up in light of https://github.com/ArctosDB/arctos/issues/7605#issuecomment-2091521078. Disposition, by decree, is no longer what the structure or term would suggest. This issue of documenting such things should be somehow resolved (eg we just decide to document everything!), and definitions should be reviewed - many or most of them are me or Gordon postulating, certainly none are similar to disposition in having been endorsed or defined by The Community. (Are we agreed that The Handbook is our official repository of authoritative definitions?) Partially defining terms and concepts outside the boundaries suggested by the structure and common usage is a recipe for inconsistent data; we have started down that path, getting distracted before completion could have significant consequences.

As a sort of acceptance of the apparent necessity of allowing data which doesn't meet structural expectations, I suggest that code table values should have the ability to carry something like a 'research-grade' flag. This is essentially an expansion of https://github.com/ArctosDB/arctos/discussions/5378 (also see above).

**Comment by Jegelewicz** [comment]
> Are we agreed that The Handbook is our official repository of authoritative definitions?) 

I think should be added to the next AWG and agreement by the community recorded.

**Comment by dustymc** [comment]
AWG discussion: Everyone likes this idea, details are fuzzy.

Something with a history (github repo or wiki) seems necessary, Arctos is not static, thing change over time.

A glossary page (something my browser's find function can work on, please) would be nice/critical.

Possible format: Short (definition, no discussion) block of text and links to background/issues/discussions/etc.

**Comment by Jegelewicz** [comment]
We can use the TDWG format for DarwinCore - no need to develop new stuff.

https://github.com/tdwg/dwc

**Comment by mkoo** [comment]
This will be on the next CT agenda. let's just do it! definitions can evolve and be adapted over time
@dustymc can you please send /post a csv of table and current definition so I can start a doc for draft edits?
https://arctos.database.museum/info/ctDocumentation.cfm

**Comment by mkoo** [comment]
in progress...
