### ISSUE TITLE
Feature Request - Batch loader for `identifiedby`

### ISSUE THREAD

**Issue by camwebb** [ArctosDB/arctos#5330]
We are working with NPS to reconcile data in their databases with what is in Arctos, and find that many ALA specimens in Arctos are lacking determiner (`identifiedby` in `flat`) information for taxonomic identifications. Many of these values exist in the NPS databases, some will need to be generated from reading specimen labels. Either way, having a batch loader for these elements would save a great deal of time.  

The CSV input fields could include:

 * GUID
 * Identiciation ID (`identification_id` in `flat`) , which should of course match one of the IDs for the GUID, but not necessarily the most recent one 
 * Agent_1 name
 * Agent_2 ... n name
 * Date of identification (optional)

The optimum behavior would be to _overwrite_ any existing data for that determination (i.e., overwriting the default "unknown" agent).

Priority: fairly high. This feature would save many hours of work, starting now.

**Comment by dustymc** [comment]
I'm not sure many could use that as a public tool, and I generally try to avoid update tools (which inevitably lead to big messes and frustrated users), but we can figure something out if this is a more widespread need than I suspect.

If there's not a general need (or if there is and while we're waiting to resolve the details) that should be a pretty simple sql update, especially if I can replace without worrying about old data. The format you suggest should work. I would be somewhat cautious about using identification_id from flat, particularly if this involves non-accepted IDs, although it's PROBABLY all current and correct, and I can help you write the SQL to get IDs directly fro table identification if necessary.

**Comment by camwebb** [comment]
Thanks Dusty. I'll craft some SQL. Code questions: 

 * Will a WHERE on the text string in agent name always return the correct agent ID? I.e., the agent name sting is UNIQUE. (Of course we will have to have done the prior checking to make sure we have the right text string for the person we intend.)  
 * Do you prefer a separate transaction for each UPDATE case, or, can I create a TEMPORARY TABLE and run the updates as a single transaction? 

Once we have the code right, we can store these up and maybe ask you to run them once a month. 👍

**Comment by dustymc** [comment]
I can write the update code if you can just get me the CSV. (Or I don't have any problem with you having SQL access, but I suppose we'd need to run that by the admin folks and you'd need a TACC account to get behind the firewall.)

I usually run that sort of thing as a transaction (all or none works), but occasionally (almost always for want of more CPU) I'll run record by record. Doesn't really matter, as long as there's a workable path for failure (and as long as it doesn't choke the DB to death...).

I'm not sure what exactly you mean by the agent question, but in general agent.preferred_agent_name is unique and corresponds to agent.agent_id. There are a pair of functions to go back and forth, or you can just join on eg identification_agent.agent_id (https://arctos.database.museum/tblbrowse.cfm?tbl=identification_agent).

Here are the functions. One takes ID and returns preferred name, the other takes a name and tries to make an ID out of it.

```
arctosprod@arctos>> \df getPreferredAgentName
                                List of functions
 Schema |         Name          | Result data type  | Argument data types | Type 
--------+-----------------------+-------------------+---------------------+------
 public | getpreferredagentname | character varying | aid integer         | func
(1 row)

arctosprod@arctos>> \df getAgentID
                          List of functions
 Schema |    Name    | Result data type | Argument data types | Type 
--------+------------+------------------+---------------------+------
 public | getagentid | integer          | name text           | func
(1 row)
```

Lemme know if I've misunderstood, and happy to zoom if that works better for you.

**Comment by camwebb** [comment]
Thanks - you answered my questions fully. 

> I can write the update code if you can just get me the CSV

I might try my hand at some SQL for this - will help me learn, and might save you some time. But I'll ask you to check the code first, and run it.

> I don't have any problem with you having SQL access, but...

Thanks. But I'm not sure I want the responsibility of back-end DB write permission!  It would however be great to get back-end read permission. I work with Arctos mainly through the SQL GUI window - it's good, but having CLI access would be much easier.  Perhaps you could bring this up with the admin folks? I have a TACC account.

> `tblbrowse.cfm?tbl=...`

Wow! I didn't know about this. Very handy!

**Comment by camwebb** [comment]
@dustymc Here is some SQL that might be (close to) right. I double-checked the association between GUID and identification_id. Thanks.

[update_determiners_ALA_2022-12-07.sql.gz](https://github.com/ArctosDB/arctos/files/10181067/update_determiners_ALA_2022-12-07.sql.gz)

**Comment by camwebb** [comment]
(Ping to @mabreslin, who generated the data)

**Comment by dustymc** [comment]
Hu. Not how I'd have done it (about like everything else in every language, I suppose) but looks like it ought to run to me. Shall I?

**Comment by dustymc** [comment]
Actually nevermind, I tried it at test, there's at least one error - and here's why I'd not do things thisaway, it works or don't, there's no useful way to look at the data. The pre-error data DOES STUFF, but if there's one error.....

```
....
arctosprod@arctos>> UPDATE identification SET made_date = '2006-02-29'
arctos-*>   WHERE identification_id = 11530855 ;
ERROR:  new row for relation "identification" violates check constraint "ck_identification_madedate"
DETAIL:  Failing row contains (11530855, 22737971, unknown, 1, Former nature_of_id: legacy., A, Pertusaria geminipara, null, 2006-02-29, null, null).
Time: 3.563 ms
arctosprod@arctos>> 
garctosprod@arctos>> DELETE FROM identification_agent WHERE identification_id = 11530960 ;
ERROR:  current transaction is aborted, commands ignored until end of transaction block
```

**Comment by camwebb** [comment]
@mabreslin Please check these dates (Feb 29 in a non-leap-year) and correct them if possible.

**Comment by camwebb** [comment]
@dustymc I will supply updated SQL shortly. I can rewrite using a TEMPORARY TABLE if you prefer.

**Comment by mabreslin** [comment]
@camwebb dates have been corrected

**Comment by dustymc** [comment]
>prefer

I suppose I should be asking for something that'll let me make sure those are actually your records and such, but I'm not that paranoid for this. Maybe next time something with data isolated as data will be better, for now I think whatever's fine.

**Comment by camwebb** [comment]
Updated SQL [here](https://github.com/ArctosDB/arctos/files/10189270/update_determiners_ALA_2022-12-08.a.sql.gz). I also wrote it [using a procedure](https://github.com/ArctosDB/arctos/files/10189271/update_determiners_ALA_2022-12-08.b.sql.gz) with an extra dummy variable of GUID - you could parse these into a table and check the GUID <-> identification relationship for a few. If the latter is better, pls let me know for next time. (PS - I don't have a postgres instance handy so couldn't check the procedure syntax - but I think I have it right.)

**Comment by dustymc** [comment]
I'm not sure that's really any different, and me trying to parse is a really nice entry point for some bug. I basically do everything with CSV - it's hugely robust (until someone opens it in Excel, anyway) and postgres is great at importing and exporting. (And there are GUI tools in Arctos.) Once the CSV is in a table there are any number of paths to an update. 

ANYWAY - that ran successfully at test so it should at production too. You can check a few at https://arctos-test.tacc.utexas.edu/ or just say GO and I'll kick it off in production.

**Comment by dustymc** [comment]
>So "GO" please.

Done.
