### ISSUE TITLE
Major Arctos release packaging

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5331]
## Status

* there is now an API to create and edit identifications
* my homegrown overlay now supports multiple active instances, and is used for a (new) taxa picker which can work in the complexity of the edit IDs form
* ID attributes are implemented (in the model)
* ID ranks have replaced accepted (in the model)
* The guid-page identifications tab form is rebuilt to support the new model (and will continue to be refined)
* there is now a relatively performant function to pull taxa-according-to-collection data
* ^^ that thing is being used to pull taxa into identifications on guid pages
* guid-page identifications now display attributes
* results/tools/identifications should be fully functional
* identification bulkloader is rebuilt
* citation bulkloader is rebuilt
* browse-and-edit is functional, although background tasks are still being refined
* edit record (click the key from browse and edit) is functional
* The bulk-checker function is functional (and producing status for edit)
* Data Entry UI is functional
* Load function is functional
* Clone into bulkloader is functional (and ridiculously complex and in need of testing)
---------------------------

Discussed with [AWG](https://docs.google.com/document/d/1zPuqUgNdsxU7xbTxU8bP0tez8BDtpxSDCNsEGMlY5TA/edit#heading=h.q3pk226foene) there are significant efficiencies in packaging a bunch of requests that will change the bulkloader up with the bulkloader change issue itself. This issue will serve as a way to link them, hopefully keeping me from getting lost and ultimately keeping me from rewriting code and then needing to immediately rewrite it again. No information should exist solely in this Issue, it is just a link. Anything that can be resolved and will change the structure of the bulkloader should be linked here. Anything that will change the structure of the bulkloader and cannot be resolved in a reasonable time will (barring significant developments, dedicated funding, fundamental changes in how we see the world, etc.) be delayed for ~5 years.

I'm going active to keep this on my radar, but some things (eg specific shape of the future bulkloader) still need discussed. At this time I don't believe there is any hard/timebomb (eg 'something will die unless...') timeline for proceeding; this can take as long as is needed, but lots of users are waiting on these things so there is a sense of urgency.

Bundled Issues:

* Shiny New Keystone: all new columns: https://github.com/ArctosDB/arctos/issues/6171
* https://github.com/ArctosDB/arctos/issues/4829 -  Feature Request - Make Nature of ID an attribute of identifications
* https://github.com/ArctosDB/arctos/issues/3540 -  Allow variably ranked acceptedness of identifications (was: order identifications on catalog record) 
* https://github.com/ArctosDB/arctos/issues/5120 -  Code Table Request - New locality attribute georeference source 
* https://github.com/ArctosDB/arctos/issues/4982 - rebuild the checker to accept more verificationstatus
* https://github.com/ArctosDB/arctos/issues/5424 - drop collector 'requirements'
* https://github.com/ArctosDB/arctos/issues/6183 - builder must go out with new loader format
* https://github.com/ArctosDB/arctos/issues/6003 - full identifiers metadata in bulkloader and entry screen
* https://github.com/ArctosDB/arctos/issues/6244
* https://github.com/ArctosDB/arctos/issues/6245
* https://github.com/ArctosDB/arctos/issues/6243

REMOVED

* Keystone issue: ~~https://github.com/ArctosDB/arctos/issues/5193 -  Feature Request - more data entry/bulkloader columns~~<!--- that's dead
* ~~https://github.com/ArctosDB/arctos/issues/4707 -  Feature Request - flatten collection objects~~ - I'm removing this, I don't think it's sufficiently ironed out, particularly in light of recent observation/part/media discussions
* ~~UNRESOLVED: https://github.com/ArctosDB/arctos/issues/6170 - refactor locality?~~

**Comment by ewommack** [comment]
@dustymc - would projects help to keep track of all of these things, or is this issue enough for you and your organization? Just trying to think about ways to help everyone navigate and track the development of changes in Arctos.

**Comment by dustymc** [comment]
I like Issues and don't quite understand what projects DO so I'm happy with this, but it's (eventually) going to be a big chunk of different all dumped out at the same time so WHATEVER might help people cope with that is most welcome.

Also spreading the word about https://github.com/ArctosDB/arctos/issues/5193 (still ~700 columns available before we even need to start negotiating!) would be very useful; any sort of real or perceived limitations regarding bulkloading (columns, naming conventions, order, WHATEVER) can probably be addressed there.

**Comment by ewommack** [comment]
@lin-fred has been doing a great job with issues for the Agent's Committee. I will admit to not understanding it as much as I would like, but it does help you keep track of different issues together, and sort them into your own designated columns. Some sorting I have seen involve, Need to Do, Discussion, Under Progress, Completed, etc. 

You can also share the Project and people can access all of the issues at once. @lin-fred - do you think projects might help with the organization of this?

**Comment by Jegelewicz** [comment]
@dustymc look at [this project](https://github.com/orgs/ArctosDB/projects/24). I created it yesterday to try to understand what was on the Next Task list. Maybe you would find this a helpful way to organize stuff by priority, "size", and whatever else.

**Comment by Jegelewicz** [comment]
Discussed at Arctos Lunch today. Based upon notes in the AWG meeting last week, we feel it is time for @dustymc to write up his plan for implementation for review and communication prior to any development.

**Comment by dustymc** [comment]
> plan for implementation

Here's a draft, I'll copy it over to arctos-dev when we get a little closer to the June 1 whatever-that-was-supposed-to-be that was specified at the last [Issues Meeting](https://docs.google.com/document/d/16eDBrhzqJ7YWhYbJnYzTFlp6w1xgRnIep4uOCThXhMI/edit#heading=h.q3pk226foene).

re: https://github.com/ArctosDB/internal/issues/258 - I'm assuming all of our meetings somehow add up to sufficient agreement to consider eventually posting this in arctos-dev, I'm still not at all clear what happens after that. Advise on any aspect of that, for this and/or in general, would be greatly appreciated.

---------------------------------


* https://github.com/ArctosDB/arctos/issues/6171: bulkloader will be completely rebuilt with all new column names. I will provide old-form CSV and migrate anything that's left in the bulkloader using some formula that I'll specify once some things have solidified.
* https://github.com/ArctosDB/arctos/issues/4829: Nature of ID will become an attribute of identifications
    * https://github.com/ArctosDB/arctos/issues/6244
* https://github.com/ArctosDB/arctos/issues/6245: identification confidence will become an attribute of identifications
    * https://github.com/ArctosDB/arctos/issues/6243  
* https://github.com/ArctosDB/arctos/issues/3540: Variably ranked acceptedness of identifications will be allowed
* https://github.com/ArctosDB/arctos/issues/5120: georeferecene source will be removed from everything as a column, and migrating to locality attributes.
* https://github.com/ArctosDB/arctos/issues/4982: more verificationstatus values will be acceptable for initial entry
* https://github.com/ArctosDB/arctos/issues/5424 - data entry and bulkloader collector-agent requirements will be removed
* https://github.com/ArctosDB/arctos/issues/6183 - the bulkloader builder will be rebuilt
* https://github.com/ArctosDB/arctos/issues/6003 - identifiers metadata will be added to bulkloader and entry screen

**Comment by campmlc** [comment]
This is my understanding of our discussions, and I support moving forward.

**Comment by ebraker** [comment]
Agreed
