### ISSUE TITLE
"used only by" in collecting events/locality search does not limit records

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#5335]
A search for collecting events using country: Japan, specific locality: Kii without any limit under Collection, returns 77 results.  

<img width="395" alt="Screenshot 2022-12-03 at 8 18 02 AM" src="https://user-images.githubusercontent.com/15368365/205448267-9c0a3ca0-1709-43d4-ae95-ffbafcb6f4ea.png">

If I limit it to "used by" DMNS:Inv, I get 65 results.

<img width="395" alt="Screenshot 2022-12-03 at 8 04 08 AM" src="https://user-images.githubusercontent.com/15368365/205448133-8f05fdd2-545d-404e-bf1d-244177cfa5ca.png">

The results include ones we aren't using.

<img width="907" alt="Screenshot 2022-12-03 at 8 04 57 AM" src="https://user-images.githubusercontent.com/15368365/205447683-d6a6365a-b2a0-4797-8aaa-e43dd3c1b2ce.png">

If I limit it to events only used by DMNS:Inv, I get the same 65 results.

<img width="584" alt="Screenshot 2022-12-03 at 8 12 50 AM" src="https://user-images.githubusercontent.com/15368365/205448168-cbd5740e-1ca4-4c7c-accd-df3b6e59d366.png">

The results still include events not used in our collection.

<img width="713" alt="Screenshot 2022-12-03 at 8 20 32 AM" src="https://user-images.githubusercontent.com/15368365/205448352-df932389-c5f7-4a1f-9255-87cf1bd1755e.png">

**Expected behavior**
Only the collecting events or localities that our collection is using should appear in the results if it's limited the those "only used by" a specific collection

**Desktop (please complete the following information):**
 - OS: Mac, Chrome but it's the same on PCs and Firefox

**Additional context**
It's been this way for ages.

**Priority**
Not high priority, but now that we have months of clean-up to do on localities with the new bot, it would be nice to be able to focus on just the localities and events used in our collection.

**Comment by dustymc** [comment]
I'm calling this next release, but 'only' performance is not great at test and I'm not sure how sustainable this option will prove to be.
