### ISSUE TITLE
[CONTACT]

### ISSUE THREAD

**Issue by frenz7** [ArctosDB/arctos#5336]
** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **
Likely in error, several Texas entries for CHAS are attributed to Frank M. Woodruff as collected in Brazos County circa 1891.  
I previously commented on CHAS:Egg:342 collected by Woodruff 11 Jun 1891 and your database shows the correction (changed Lesser Nighthawk to Common Nighthawk).
Collected the same day was CHAS:Egg:395 Plegadis chihi (White-faced Ibis).  Although not common, the ibis did nest in the Brazos County area at that time.  However, in light of other specimens collected by Woodruff, perhaps the location is coastal such as Galveston County, not inland Brazos County.
CHAS:Egg:272 is undated though attributed to Woodruff.  Laughing Gull Larus atricilla is now Leucophaeus atricilla.  Laughing Gull is rare in Brazos County and not known to nest.  At that time, it was only known in the area from vagrants blown in by hurricanes or tropical storms.  The photographed eggs do look like color-faded Laughing Gull eggs.  Was there a location label with the eggs?  Could these have been taken in coastal Brazoria County rather than inland Brazos County?
CHAS:Egg:279 3 Jul 1890 Rynchops niger (Black Skimmer) has the location as Bolivar, Denton County, Texas.  Black Skimmer would be accidental in Denton County.  However, it would be expected on the Bolivar Peninsula, Galveston County.
CHAS:Egg:405 is undated and assigned to Boat-tailed Grackle (Quiscalus major) which does not and did not occur in Brazos County.  The eggs are similar to Great-tailed Grackle Quiscalus mexicanus which first arrived in the area in the late 19th century and was known to nest in the adjoining county, Washington.  At that time, local observers considered Boat-tailed and Great-tailed the same species.  In 1886, AOU split Boat-tailed and Great-tailed.  If, in fact, these eggs were collected in Brazos County, then they should be assigned to Great-tailed Grackle Quiscalus mexicanus.  The date of collection could be narrowed to circa 1884-1894 to align with known dates of other eggs and specimens collected by Woodruff.  Alternatively, the eggs are in fact from Boat-tailed Grackle and the location is coastal.  These could be from Bolivar Peninsula, Galveston, collected 3 Jul 1890 as was CHAS:Egg:279.
Bert Frenz bert2@bafrenz.com

**Comment by dustymc** [comment]
@droberts49 @wellerjes

**Comment by Jegelewicz** [comment]
@droberts49 @wellerjes if you have addressed this, please close or let me know if you need any help.

**Comment by dustymc** [comment]
@droberts49 @wellerjes done?

**Comment by Jegelewicz** [comment]
> Jessica and Dawn,
> 
> I don't think you have seen this and Dusty closed it - https://github.com/ArctosDB/arctos/issues/5336
> 
> Adios,

Teresa J. Mayfield-Meyer
