### ISSUE TITLE
[CONTACT] cat_records feedback - entities notice and page help

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5338]
Old form includes info about entities being included
![image](https://user-images.githubusercontent.com/5725767/205696494-c6abe34b-c53a-41c1-80fe-5922b0debd76.png)

Should new form too?

Also, the "About this widget" in the old form is needed in the new form (but probably also needs updating) or should that link just be page help (if so, updating will also be necessary to accommodate all the things this form does)?

Also are we using this - https://handbook.arctosdb.org/how_to/How-to-Search-for-Specimens.html#specimen-search-refine-widget 

or this - https://handbook.arctosdb.org/documentation/specimen-results.html

**Comment by dustymc** [comment]
>Should new form too?

I think not, but I don't think I've ever understood why it was there in the first place. (Unjustified assumptions regarding users' intelligence??)

Maybe https://arctos-test.tacc.utexas.edu/info/ctDocumentation.cfm?table=ctcataloged_item_type should be moved to 'core' (and it'll be more prominent in https://github.com/ArctosDB/arctos/issues/5333).

>Also are we using this 

No, that's much of the point of the new UI - it's natively interactive, doesn't need duct tape (and ridiculous amount of CPU+network) to poorly fake it.

**Comment by Jegelewicz** [comment]
> I think not, but I don't think I've ever understood why it was there in the first place. (Unjustified assumptions regarding users' intelligence??)
> 
> Maybe https://arctos-test.tacc.utexas.edu/info/ctDocumentation.cfm?table=ctcataloged_item_type should be moved to 'core' (and it'll be more prominent in https://github.com/ArctosDB/arctos/issues/5333).

Maybe, but I think this is where the pre-built searches could come in handy. Only want records that will get you "things" use this form.

> No, that's much of the point of the new UI - it's natively interactive, doesn't need duct tape (and ridiculous amount of CPU+network) to poorly fake it.

So there won't be anymore page help link? It's there now. My question was about WHICH documentation we should link to for this page.

![image](https://user-images.githubusercontent.com/5725767/205701296-ea7d82a9-850a-4a9c-b5eb-2b372f114369.png)
