### ISSUE TITLE
[CONTACT] cat_records feedback - let's clean up "specimen"

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5340]
Can we change this category to de-specimen this? Suggest "Catalog Record"

![image](https://user-images.githubusercontent.com/5725767/205707493-7512b562-1231-4fd2-95ed-5f33c92028b7.png)

**Comment by dustymc** [comment]
>change

Sure, just change the CSV I provided.

>Catalog Record

I'm less sure of that - ``[a-z_]`` is all that's known to work so if you can stick to that then this is easy, if not then maybe we need some sort of complexity (which will be at least slightly less sustainable).

Merge-->https://github.com/ArctosDB/arctos/issues/2745#issuecomment-1333998804
