### ISSUE TITLE
Feature Request - search part attribute remarks in "Part Search"

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#5343]
I just tried searching 'palatal rugae' in the "Part Search" field. That value is in remarks for the part attribute='representation' with value '35 mm negative'. The part name is 'palate'

Nothing comes up in the search. If I just search 'palate' it also retrieves records with 'palate' in part remarks, but the part attribute remarks don't seem to be searchable. 

Please fix so that the attribute remarks are searchable too.

Example:
https://arctos.database.museum/guid/MVZ:Mamm:172358

**Comment by dustymc** [comment]
I was able to tune the indexes to support this, so it's in next release. 

Note that you can also search directly via...

<img width="422" alt="Screenshot 2022-12-06 at 7 10 47 AM" src="https://user-images.githubusercontent.com/5720791/205949491-23c9ddc0-4d66-489a-8dba-9f0da480d476.png">

<img width="1077" alt="Screenshot 2022-12-06 at 7 10 30 AM" src="https://user-images.githubusercontent.com/5720791/205949520-54bc3543-e5e4-4f8c-b962-bdb6b6ba6202.png">
