### ISSUE TITLE
Need Help with Arctos Error - "You do not have access to this collection" in Bulkload Container Tool

### ISSUE THREAD

**Issue by jtgiermakowski** [ArctosDB/arctos#5344]
# Error Text
You do not have access to this collection

# Where it happened
Bulkload Container Tool

# Steps to get there
Trying to create shelves as container in our collection

# Problem
can't use Bulkload container tool

# Solution
¿permission problem?
![Screenshot 2022-12-05 at 16-28-36 Bulkload Containers](https://user-images.githubusercontent.com/2381228/205767062-2581e089-0cd3-422d-a38b-98840b105fd0.png)

**Comment by dustymc** [comment]
You can get institution_acronym from manage collection - you're probably looking for ``MSB``.

**Comment by jtgiermakowski** [comment]
Thanks! There's a proverb that i think says "the darkest place is underneath a lamp". I was really thrown off by the "you don't have access to the collection". I wrongly assumed that the container tools is based on collection and not institution. it worked!
