### ISSUE TITLE
[CONTACT] cat_records feedback - slowdowns and login weirdness

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5347]
Ever since the new search form went live in production I have noticed that when I log in I get logged in but the login form never goes away and I don't see the 20 collections that currently do not have an active user with manage collection. I can just close the login form then refresh Arctos and move on, but that doesn't feel right.

Also, I randomly get very long waits for pages to open. I've mostly noticed this with the search records page, but it has also happened while working with agents and elsewhere. I don't know if this is the result of two search pages running simultaneously or what, but it is a bit inconvenient.

**Comment by dustymc** [comment]
Definitely unrelated, relatively sure you're just seeing more of https://github.com/ArctosDB/internal/issues/187
