### ISSUE TITLE
Planned Outage - 8 January 2023, TACC maintenance

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#5350]
Please complete to the best of your ability.

## Planned Outage
 - Date and time outage will begin: 8 January 1000 CST
 - Date and time outage is expected to end: 8 January 1600 CST
 - Reason for outage: TACC Network Maintenance Sunday January 8th 2023
From: Mark Brueschke
Network maintenance will be carried out between 10:00 AM and 4:00 PM (CST) on Sunday, January 8th. Access to all TACC systems will be unavailable during this time. Jobs will continue to run, but users will have no access to TACC services and systems until the upgrade is complete.
 
Please submit any questions you may have via the TACC User Portal.
 
https://portal.tacc.utexas.edu/tacc-consulting
To manage your TACC Announcements subscriptions, please visit https://www.tacc.utexas.edu/news/subscribe
 - Expected behavior during and after the outage: We should all have to take a break on the 8th, and then come back nice and refreshed.

## Communication before/during outage
- [x] Pin this issue
- [x] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG  
- [x] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by lin-fred** [comment]
oh woops, I just saw this briefly on my phone and totally missed the details. I apologize!

**Comment by mkoo** [comment]
I can add a banner reminder on Jan 2 
thanks!

**Comment by mkoo** [comment]
I will update the banner this Wednesday since we have the agents reminder as the banner reminder right now

**Comment by mkoo** [comment]
banner reminder up for Sunday outage
