### ISSUE TITLE
Display of part preservation in results

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#5351]
The display of part_preservation attributes is not consistent in parts results; e.g. ([Results](https://arctos.database.museum/SpecimenResults.cfm?catnum=19025-19028&guid_prefix=DMNS%3AMamm&accn_number=&scientific_name=&phylum=&phylclass=&phylorder=&family=&subfamily=&tribe=&subtribe=&genus=&species=&subspecies=&continent_ocean=&sea=&country=&state_prov=&county=&island_group=&island=&spec_locality=&habitat=&collecting_method=&remark=&age_class=&calcar_length=&ear_from_notch=&ectoparasite_examination=&ectoparasites_detected=&endoparasite_examination=&endoparasites_detected=&hind_foot_with_claw=&sex=&tail_length=&tarsus_length=&thumb_length_with_claw=&total_length=&tragus_length=&unformatted_measurements=&verbatim_preservation_date=&weight=))
![image](https://user-images.githubusercontent.com/12507297/206283468-90ae40e7-1fe4-404c-9a8c-a653d2858b49.png)
As far as I can tell, these all appear to be entered in the same manor. Any idea why they display differently?

**Comment by dustymc** [comment]
<img width="137" alt="Screenshot 2022-12-07 at 12 40 48 PM" src="https://user-images.githubusercontent.com/5720791/206291052-4fcaa7ba-c879-423f-b84c-e455c80d81f8.png">

will make it easier to see things.

What specifically isn't consistent?

**Comment by acdoll** [comment]
Sorry, in the 'parts' column it will sometimes put the preservation in parentheses like "whole organism (ethanol)", but other times it doesn't and you only get "whole organism".

**Comment by acdoll** [comment]
Thanks! Yes, it's not worth mucking other things up, but it seemed like something odd was going on.

**Comment by dustymc** [comment]
OK, DMNS:Mamm should refresh in the next hour or so, let me know if you want me to trigger any more collections (or if that doesn't do what I think it will...).

**Comment by acdoll** [comment]
That seems to have done it. Could you trigger the DMNS:Bird collection also? I appreciate it!

**Comment by dustymc** [comment]
>Bird

running
