### ISSUE TITLE
flatten stuff for default results and dedicated search fields

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5354]
**Is your feature request related to a problem? Please describe.**

Cache commonly-used stuff for performance reasons

**Describe what you're trying to accomplish** 

Not kill Arctos, make users happy

**Describe the solution you'd like**

Add to flat and filtered flat (from https://github.com/ArctosDB/arctos/issues/5341 and https://github.com/ArctosDB/arctos/issues/4786)

* suborder
* media
* creator
* subject
* materials
* copyright holder
*  culture of origin
*  culture of use
* formation
* member
* event_count
* locality_count
*  age 
* confirm: age_class

**Describe alternatives you've considered**

Limited search or timeouts/crashes

**Additional context**

I'll also make some of these into dedicated search options, in addition to the attributes search table. Please let me know of anything else that should be considered for similar treatment. 

It is a giant pain to change FLAT (especially when taxonomy-stuff is involved), please let me know **before 2022-12-14** if anything else should be added to the list above so it can be used as default search and/or results items. 

**Priority**

gonna happen

**Comment by campmlc** [comment]
Related catalog items, related ID,

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> search and/or results items

I'd like to be able to see formation in specimen search results if that's the type of thing you are talking about here.

**Comment by dustymc** [comment]
> if that's the type of thing you are talking about here.

Sorry for not being clear. I think formation is a good candidate, but you tell me. The cache has to be something that (usually) makes sense squished into a column as a value. So ~50% of 'sex' values are 'female' and ~50% are 'male' and those convey the idea sufficiently while making the queries very cheap (which is necessary if we're going to put them out there as defaults). A few (still lots these days) are things like 'male; female; male; female' which should be interpreted as "it's complicated, scroll down to the Attributes section."

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Based on what you said, yes, I think formation is a good candidate. This will definitely make sense squished into a column, and most of the data will be a single formation.

Adding member would be helpful too. 

I wish we could do chronostrat as well, but with it split up between multiple locality attributes and not all levels filled out for each locality, that one seems extra compliated.

Even just having formation will be a huge improvement for paleo/geo specimens.

**Comment by mkoo** [comment]
In today's webinar, the field 'age' was requested and confirmed to not be in the current flat.
Can ```age``` be added?

**Comment by dustymc** [comment]
> Can age be added?

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#age - correct?

``age_class`` exists, wondering if we need something new or if I mucked up the UI?

**Comment by dustymc** [comment]
Adding event_count and locality_count for https://github.com/ArctosDB/arctos/issues/1853

**Comment by mkoo** [comment]
```age```  is different than ```age_class``` and specifically requested by bird collections
@ccicero and others can chime in to expound but you can see the values are different.

**Comment by dustymc** [comment]
thx @mkoo I know its different but wasn't clear on what was being requested - I'll add age and make sure age_class is being handled properly.

**Comment by ccicero** [comment]
@dustymc 'age' used to be part of flat but I guess it isn't anymore? We need to make sure that both age and age_class are in flat.

**Comment by dustymc** [comment]
Done, will take a couple days for the cache to fully catch up.
