### ISSUE TITLE
Loan picker showing two object parts while catalog record shows one

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#5357]
**Describe the bug**

I'm adding items (part=object) to a loan in the new add to loan form (loving it).
When I searched for this item ([Sled runner](https://arctos.database.museum/guid/UAM:EH:UA2006-009-0084)) the new loan adder form shows two object parts but the catalog record only shows one.

<img width="1660" alt="Screenshot 2022-12-09 at 2 11 59 PM" src="https://user-images.githubusercontent.com/17605945/206810872-65b35536-4ce3-42c2-a858-95ef8a46bd72.png">

<img width="1795" alt="Screenshot 2022-12-09 at 2 12 34 PM" src="https://user-images.githubusercontent.com/17605945/206810891-8e533507-2e1a-4d2f-9360-5afc2e61ebde.png">

**Additional context**
Old add to loan form only shows one object part.
<img width="1795" alt="Screenshot 2022-12-09 at 2 21 52 PM" src="https://user-images.githubusercontent.com/17605945/206811083-4b109981-88bb-4f51-a0d9-feb475203102.png">

**Priority**
High - this is making my brain hurt! Which object part should I pick? Does it matter?

**Comment by AJLinn** [comment]
AND, when I tried to just add one of them randomly, I got an error:

<img width="1805" alt="Screenshot 2022-12-09 at 2 32 58 PM" src="https://user-images.githubusercontent.com/17605945/206811965-89d129da-9ccf-4562-ad33-603eb49d1d82.png">

**Comment by dustymc** [comment]
patched
