### ISSUE TITLE
Planned Outage - Friday 2022-12-16

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5358]
Please complete to the best of your ability.

## Planned Outage
 - Date and time outage will begin: 2PM Central
 - Date and time outage is expected to end: %PM
 - Reason for outage: backup
 - Expected behavior during and after the outage: Arctos will be down

The times might need to adjust a bit, but we'd like to take Arctos down for a static snapshot before Christmas. Please let me know ASAP if we need to reschedule.

## Communication before/during outage
- [x] Pin this issue
- [x] Banner updated @jegelewicz @mkoo
- [x] Email sent to AWG  
- [x] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [x] Unpin this issue
- [x] Banner updated @jegelewicz @mkoo
- [x] Email sent to AWG 
- [x] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by ewommack** [comment]
I think you're saying stop work early on a Friday. I suppose I can do that.

**Comment by ewommack** [comment]
I've set the email to go out on Thursday the 15th at 0800 MT

**Comment by lin-fred** [comment]
tweeted and sent out a reminder for Thursday

**Comment by dustymc** [comment]
Arctos is back up

**Comment by mkoo** [comment]
just noticed!
yay!

**Comment by mkoo** [comment]
also new home page
double-yay!

**Comment by ewommack** [comment]
> also new home page

The new search page or the new arctos.db page?

**Comment by cjconroy** [comment]
quick question on the new search page. Aside from other fields being used, how do I search by sex? I have a few criteria, but only want to bring up males. 
Thanks

**Comment by dustymc** [comment]
Customize:

<img width="460" alt="Screenshot 2022-12-16 at 3 22 45 PM" src="https://user-images.githubusercontent.com/5720791/208204708-a3e04594-fe2c-4636-a252-34bfb9faaeaa.png">

Check, save:

<img width="469" alt="Screenshot 2022-12-16 at 3 23 53 PM" src="https://user-images.githubusercontent.com/5720791/208204714-224a6d3a-4721-4106-979b-e93a4037b7f8.png">

Search:

<img width="394" alt="Screenshot 2022-12-16 at 3 24 11 PM" src="https://user-images.githubusercontent.com/5720791/208204722-e5fb58d7-5b6f-4c1e-9496-a2ee4af846d3.png">

**Comment by cjconroy** [comment]
Thanks. I think most people will find this challenging.

**Comment by dustymc** [comment]
>challenging

Commonly-used attributes (and perhaps other stuff) can be added as stand-alone options - just open an Issue. (Doing so takes several days of CPU and should have been done as part of https://github.com/ArctosDB/arctos/issues/5354, but I think sex is already handled.)

We can also create 'profiles' (see https://github.com/ArctosDB/arctos/issues/5341) if some user group who might benefit from such can be identified.
