### ISSUE TITLE
Feature Request - Restore Manage Agent functionality

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#5360]
I just tried to add an agent to several records using the Manage menu and see that the form is updated, but some functionality/ease is lost.

I used to be able to bulk add or delete agents from records, and re-order ranking. Now it looks like my only option is to replace agents, when ultimately what I want to do is add an individual agent to 267 records, and it appears I have to do this by hand. 

Is there a way to restore mass adds, deletes, and re-ordering of display names?

![image](https://user-images.githubusercontent.com/11336485/207079153-bd4ca4e6-516c-427a-a5df-14d47f04cec0.png)
https://arctos.database.museum/tools/replace_agents.cfm?table_name=temp_cache.ss_ebraker_20221212081233974_572&sort=guid

**Comment by dustymc** [comment]
<img width="250" alt="Screenshot 2022-12-12 at 7 34 52 AM" src="https://user-images.githubusercontent.com/5720791/207086509-365dba7f-abc9-4bdc-a9b1-e34615abfd10.png">
