### ISSUE TITLE
adjust data for observation records

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5361]
@dustymc @Jegelewicz 

What were the criteria for the records that were changed? Was it where specimen_event_type = 'collection' and/or disposition = 'in collection' I don't see MVZObs:Bird in the temp file so I'm not sure what the criteria was for records that were changed, as we have a lot of observational data.

I'm checking some records and the event type is 'collection' e.g., https://arctos.database.museum/guid/MVZObs:Bird:1000. All MVZObs: records should have an event type of 'observation'

If we're adding a part name of 'media' to observational records, then can you also add part of 'media' to MVZ:Obs records where there is a linked media (image, audio)? Or what is the part 'protocol' for those types of records? Records without a linked media should not have a part of 'media' or any other part.

_Originally posted by @ccicero in https://github.com/ArctosDB/arctos/issues/1302#issuecomment-1346965900_

**Comment by dustymc** [comment]
>what is the part 'protocol'

That's part of what https://github.com/ArctosDB/arctos/discussions/5250 is intended to sort out, but I don't think I'll ever be convinced that doing anything other than recording what you have will make any sense.

> we have a lot of observational data.

Again I'm hesitant to do much until the discussion is resolved, but cataloged_item_type seems like the keystone to me:

```

select 
  guid_prefix,cataloged_item_type,count(*) c 
  from cataloged_item 
  inner join collection on cataloged_item.collection_id=collection.collection_id where 
  guid_prefix like 'MVZ%'
  group by guid_prefix,cataloged_item_type
  order by guid_prefix,cataloged_item_type;


 guid_prefix | cataloged_item_type |   c    
-------------+---------------------+--------
 MVZ:Arch    | item                |    148
 MVZ:Bird    | preserved specimen  |     19
 MVZ:Bird    | specimen            | 194161
 MVZ:Egg     | preserved specimen  |      2
 MVZ:Egg     | specimen            |  15004
 MVZ:Fish    | specimen            |    784
 MVZ:Herp    | preserved specimen  |      6
 MVZ:Herp    | specimen            | 294991
 MVZ:Hild    | specimen            |    659
 MVZ:Mamm    | preserved specimen  |    120
 MVZ:Mamm    | specimen            | 242090
 MVZObs:Bird | human observation   |  20847
 MVZObs:Bird | observation         |   4663
 MVZObs:Bird | specimen            |    211
 MVZObs:Herp | observation         |     33
 MVZObs:Herp | specimen            |      1
 MVZObs:Mamm | observation         |    101

```

>adding a part name of 'media' to observational records

There are two possibilities here.

1. You need to get something physical (thumb drive, print, slide, anything not actually a part of the whole - bloody-bits for vert collections) into your object tracking system ====> you need a part 'media,' this is why it exists
2. You don't have anything physical =====> you don't need parts and the introduction thereof is just going to confuse everything. (BUT, that's a defensible part name and I can't control how you use it and I won't much try to stop you from making giant messes. But please don't.)


> change to event type

I feel this needs somehow more synced up with cataloged_item_type, but maybe I'm wrong and they're truly independent. Again, hopefully the discussion will lead somewhere useful. Here's your data.

```
select 
  guid_prefix,specimen_event_type,count(*) c 
  from cataloged_item 
  inner join collection on cataloged_item.collection_id=collection.collection_id 
  inner join specimen_event on cataloged_item.collection_object_id=specimen_event.collection_object_id
  where 
  guid_prefix like 'MVZ%'
  group by guid_prefix,specimen_event_type
  order by guid_prefix,specimen_event_type;


 guid_prefix | specimen_event_type |   c    
-------------+---------------------+--------
 MVZ:Arch    | creation            |    148
 MVZ:Bird    | collection          | 212568
 MVZ:Bird    | creation            |      1
 MVZ:Bird    | encounter           |    308
 MVZ:Egg     | collection          |  15744
 MVZ:Fish    | collection          |    783
 MVZ:Herp    | collection          | 304283
 MVZ:Hild    | collection          |    662
 MVZ:Mamm    | collection          | 261242
 MVZObs:Bird | collection          |   4678
 MVZObs:Bird | observation         |  21237
 MVZObs:Herp | collection          |     25
 MVZObs:Herp | observation         |      9
 MVZObs:Mamm | collection          |    101
(14 rows)

```

**Comment by ccicero** [comment]
@dustymc Thanks. The MVZ:Bird with event type of 'creation' is ok - it is a buzz toy. The 308 records with type 'encounter' should be changed to 'collection' as those are blood samples, can you please update those?

I think that event type for all MVZObs should be 'observation' and not 'collection.' Can you also update those please?

We clearly need to be more consistent with cataloged_item_type. I don't know what just 'specimen' is intended for, but it seems to me that we need to make these changes for compliance with DwC:

guid_prefix | cataloged_item_type |   c    
-------------+---------------------+--------
 MVZ:Arch    | item                |    148
 MVZ:Bird    | specimen            | 194161 ---> preserved specimen
 MVZ:Egg     | specimen            |  15004 ---> preserved specimen
 MVZ:Fish    | specimen            |    784 ---> preserved specimen
 MVZ:Herp    | specimen            | 294991 ---> preserved specimen
 MVZ:Hild    | specimen            |    659 ---> preserved specimen
 MVZ:Mamm    | specimen            | 242090 ---> preserved specimen

OBSERVATIONS REQUIRE DISCUSSION. According to DwC, 'Human Observation' is "A record of an Occurrence without physical evidence nor evidence captured with a machine." So how to deal with records that have media, radio tracking data, etc. I guess those are 'Machine Observation' per DwC ("A photograph. A video. An audio recording. A remote sensing image. A Occurrence record based on telemetry."), although the machine didn't observe and identify it so ??? This requires discussion by the observation group. 'Specimen' is clearly wrong, however.

 MVZObs:Bird | human observation   |  20847
 MVZObs:Bird | observation         |   4663
 MVZObs:Bird | specimen            |    211
 MVZObs:Herp | observation         |     33
 MVZObs:Herp | specimen            |      1
 MVZObs:Mamm | observation         |    101

**Comment by dustymc** [comment]
>'collection' as those are blood samples

Did the animal survive? If so 'encounter' is correct, https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_event_type

>know what just 'specimen' is intended for

I don't either, but see also https://github.com/ArctosDB/arctos/issues/2432#issuecomment-1218320073 - some values will drop your entire dataset from DWC.

>specimen | 194161 ---> preserved specimen

You may want to revisit the defaults in manage collection.

Bigger picture, can we just drop "specimen" and make a global update? (I can do smaller sets too, but it will take a lot more CPU and it seems like maybe we have an unresolved issue here.)

**Comment by ccicero** [comment]
Ah yes, the animal survived so good that those are correct :) I think we have other blood only samples that probably say 'collection' vs 'encounter'. Can you query MVZ:Bird records where part_name = 'blood' (and no other parts) and event type = 'collection', then send me a CSV? Thanks.

I just updated the default to 'preserved specimen' for MVZ:Bird and MVZ:Egg, thanks for the suggestion!

I like the idea of simplifying and dropping just 'specimen' but sounds like it requires more discussion?

**Comment by dustymc** [comment]
```

select
    guid_prefix,
    concat_ws(':',guid_prefix,cat_num) as guid,
    specimen_part.collection_object_id partID,
    specimen_part.part_name,
    coll_obj_disposition,
    string_agg(specimen_event_type,'|') as specimen_event_type
from
    specimen_part
    inner join coll_object on specimen_part.collection_object_id=coll_object.collection_object_id
    inner join cataloged_item on specimen_part.derived_from_cat_item=cataloged_item.collection_object_id
    left outer join specimen_event on cataloged_item.collection_object_id=specimen_event.collection_object_id
    inner join collection on cataloged_item.collection_id=collection.collection_id
    left outer join specimen_part notblood on cataloged_item.collection_object_id=notblood.derived_from_cat_item and notblood.part_name!='blood'
where
    specimen_part.part_name = 'blood' and
    specimen_event_type='collection' and
    guid_prefix='MVZ:Bird'
group by
    guid_prefix,
    cat_num,
    specimen_part.collection_object_id,
   specimen_part.part_name,
    coll_obj_disposition

```
[temp_part_mvz_blood.csv.zip](https://github.com/ArctosDB/arctos/files/10212387/temp_part_mvz_blood.csv.zip)


>dropping just 'specimen' but sounds like it requires more discussion?

Blargh, yea 195 collections are using it as default! @Jegelewicz care to take the lead on this, or tell me where I got lost, or ??

**Comment by Jegelewicz** [comment]
"Specimen" is potentially useful to geological collections. But biological collections should not be using it. I can change a lot of those 195, but probably not all of them.

**Comment by Jegelewicz** [comment]
FWIW - I think we defaulted to "specimen" when we added that to manage collection.

**Comment by dustymc** [comment]
> I can change

I can do that faster, I'm more hoping you'll help us understand what we should be doing. Now that I know the [implications of not using DWC terms,](https://github.com/ArctosDB/arctos/issues/2432#issuecomment-1218320073) I suggest we revisit the terminology. Ideally I'll just report what's there to DWC, but if I absolutely must translate https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcataloged_item_type needs updated (and who know if that'll survive the GUM and etc etc so can we please just use native terms??).

**Comment by Jegelewicz** [comment]
> understand what we should be doing

https://github.com/ArctosDB/arctos/issues/2432#issuecomment-572181596

**Comment by ccicero** [comment]
@dustymc Thanks for the file. Some of those records have parts other than blood, e.g., 
https://arctos.database.museum/guid/MVZ:Bird:187066

Can you redo it where it only returns MVZ:Bird records with ONLY blood as a part?

**Comment by dustymc** [comment]
The big discussion doesn't look like it might be going anywhere so I'll just update MVZ - that's running now, will take a while, and then maybe a few days to clear the cache. 

If we eventually decide to do better it'll just be another update, maybe that can be a bigger-picture thing.

I don't think I much buy into DWC's observation definitions (seems like its mostly gray area to me), happy to do whatever you want with those.

**Comment by ccicero** [comment]
Thanks @dustymc I'm not crazy about their observation definitions either.

Re: encounter updates, those should only be for records that don't have any part other than a blood sample. Tissue (or any other part) + blood is still a 'collection'
