### ISSUE TITLE
part pick behavior

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#5362]
I'm working on part representations for Jim Patton, and some of them involve the parietal. I'm trying to add a part 'parietal' which is in the parts code table, but it's filling the field with 'interparietal' and won't let me pick 'parietal' as a part. 

@dustymc Help?

**Comment by dustymc** [comment]
Link and screenshot please? I'm lost.

**Comment by ccicero** [comment]
MVZ:Mamm:157951

Entered 'parietal' in the part name field and if I hit tab or go to the next field, it auto fills interparietal:

![image](https://user-images.githubusercontent.com/967275/207199282-74bc0cd8-3816-4128-8a27-dd1ac1aec31a.png)

It worked once where it didn't do that but when I tried to create the part I got an error which I can't replicate now.

**Comment by dustymc** [comment]
Ah, thanks. 

<img width="278" alt="Screenshot 2022-12-12 at 4 55 13 PM" src="https://user-images.githubusercontent.com/5720791/207199828-4577ad7b-1738-4bf2-aeb4-57f041ee7e11.png">

You need to add Mamm - or wait a while for the cache to clear if you already did.

**Comment by ccicero** [comment]
Ah, thanks! 

Rather than filling in a different part, could it have a pop up window that says something like "Part name not available for this collection type. Update code table."

???

**Comment by dustymc** [comment]
See also https://github.com/ArctosDB/arctos/issues/5270.

I suspect we've just outgrown the idea of Arctos being able to guess what's meant from a partial match and need to re-do all picks accordingly, but ??? Some Community input would be most appreciated.

**Comment by ccicero** [comment]
I made a suggestion about what to with where parts exist but not for the collection trying to use that part. Is such a pop up message feasible?

**Comment by dustymc** [comment]
>feasible

I'm not sure. If this happens a few times per day, sure. If it happens millions (probably doesn't) then  I probably don't have the infrastructure. (Every fail would require at least one more connection and query.) 

Maybe https://github.com/ArctosDB/arctos/issues/3452 will have some influence, and I can kinda see that going either way. 

100% chance someone has figured out how to type 2 letters to pick something and will yell at us (me!) when/if that changes, and from the above I'd guess there's a very-near-100% chance that someone has used an unintended part a few times (and a non-zero chance that "few" is really tens of thousands...). ANYTHING I do, including nothing, is likely to make things worse for someone. That all still kinda looks like a significant social problem and then, depending on how that goes, hopefully a relatively straightforward technical bit.
