### ISSUE TITLE
New Search Page Question - Allowing Public Search on Permit Number and Info?

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#5364]
Playing around in the new search page and I love all of the options I can find. 

One that I found in the public search that I wasn't sure on is being able to search on Permit number and info. 

Without logging in I can pull up all of the specimens that are tied to a specific permit number or permit info. 
Is this something we want the public to be able to search on or have access to? I know Permits are controlled by curatorial access currently, but this might form a bit of a back door, especially if a collection has their accessions restricted, so permit info is generally not discoverable publicly.

**Comment by ewommack** [comment]
Screen shot of the permit search field:
![Permit Search_Arctos](https://user-images.githubusercontent.com/18562884/207431677-cc7786b6-4692-4f33-b8c3-81f3e9949761.png)

**Comment by campmlc** [comment]
For GGBN, all they need to know is if permit info is available from the
collection. I don't think we should make permits publicly searchable?

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/1569
https://github.com/ArctosDB/arctos/issues/1372
https://github.com/ArctosDB/arctos/discussions/4967
https://github.com/ArctosDB/arctos/issues/1563

**Comment by ewommack** [comment]
Thanks @dustymc I understand a bit more of how the permit info become searchable. It looks like they came along with all of the curatorial attributes with #1563, but we never really finished the discussions on the rest of the issues (through lack of participation). Should I open up that discussion again? I'm really not sure that info should be searchable by the general public.
