### ISSUE TITLE
Need occurence file

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5365]
Attempting to get needed information for publishing a new collection to GBIF using SQL provided and I am getting an error that I don't have permission to the occurrences table.

![image](https://user-images.githubusercontent.com/5725767/207445015-8a4241a4-b013-4cda-9aa0-0986851bb81d.png)

SQL is
```select catalognumber,occurrenceid from ipt_cache.occurrence where collectionid=(select collection_id from collection where guid_prefix ='CSULB:Mamm')```

**Comment by dustymc** [comment]
>don't have permission to the occurrences table.

Correct, there's special access and special rules for those tables.

**Comment by Jegelewicz** [comment]
But I have run this SQL before so that I can create resource relationships for collections publishing to GBIF from Arctos for the first time - we HAVE to do this, so either I need you to run it for me or I need permission.

**Comment by dustymc** [comment]
[temp_csulb.csv.zip](https://github.com/ArctosDB/arctos/files/10261150/temp_csulb.csv.zip)

**Comment by Jegelewicz** [comment]
I also need this for CSULB:Fish and CSULB:Bird

**Comment by dustymc** [comment]
```
arctosprod@arctos>> drop table temp_csulb;
DROP TABLE
Time: 75.674 ms
arctosprod@arctos>> create table temp_csulb as  select catalognumber,occurrenceid from ipt_cache.occurrence where collectionid in  (select collection_id from collection where guid_prefix like 'CSULB%');
```

[temp_csulb(1).csv.zip](https://github.com/ArctosDB/arctos/files/10261287/temp_csulb.1.csv.zip)

**Comment by Jegelewicz** [comment]
@dustymc can you get me this same info for all the UNR collections please?

**Comment by Jegelewicz** [comment]
@dustymc any chance I could get the UNR collections now?

**Comment by dustymc** [comment]
drop table temp_unr;
create table temp_unr as  select catalognumber,occurrenceid from ipt_cache.occurrence where collectionid in  (select collection_id from collection where guid_prefix like 'UNR%');
[temp_unr.csv.zip](https://github.com/ArctosDB/arctos/files/10523926/temp_unr.csv.zip)

Out of morbid curiosity, is this an attempt to introduce continuity using ephemeral identifiers?

**Comment by Jegelewicz** [comment]
> morbid curiosity

Yes - because occurrence ids are SUPPOSED to be permanent, but we have not paid attention.

https://www.gbif.org/data-quality-requirements-occurrences#dcOccurrenceID

**Comment by dustymc** [comment]
"We" have absolutely paid attention, starting from well before DWC was developed. That is not and has never been the problem. The GUM is largely an acknowledgement of reality, but we're there yet. In the meantime, I don't think pretending OccurrenceIDs are anything other than what they are is in anybody's best interest.

**Comment by Jegelewicz** [comment]
It;s kinda a requirement when people move from whatever to Arctos. So let's just play along until GUM....
