### ISSUE TITLE
[CONTACT] cat_records feedback

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5367]
When I add event type to search results, how does Arctos pick what to display when there is more than one event? For example:

https://arctos.database.museum/guid/UNM:MET:100 has two events, both unverified. Search results only show the creation event

![image](https://user-images.githubusercontent.com/5725767/207467381-e98151fa-4515-475c-b5d8-44f75662e384.png)

How did Arctos choose which event to list? Should it choose or do we need to let users know that there is more than one?

**Comment by Jegelewicz** [comment]
Note - search was for https://arctos.database.museum/search.cfm?cat_num=100

**Comment by Jegelewicz** [comment]
Results with column headers if that helps
![image](https://user-images.githubusercontent.com/5725767/207467948-41e3218c-c33a-4cf0-847d-d8ab00739089.png)

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/862
