### ISSUE TITLE
[CONTACT] locked out of my account

### ISSUE THREAD

**Issue by babogan** [ArctosDB/arctos#5368]
For whatever reason I end up getting locked out of my account when I try to login on the collections room computer.
I assume I'm just mis-typing my password. However now my account "BABOGAN" is locked and I can't get back in. Please assist. I did the reset password link but even entering the new password yields nothing

**Comment by dustymc** [comment]
I've reset your account, your most recent password should work.

Your user name is ``babogan`` and Arctos is case-sensitive.

**Comment by babogan** [comment]
Thank you!
