### ISSUE TITLE
Unable to invite Arctos user to become an Operator

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#5369]
Since we joined Arctos, our User IDs have included an underscore.  Example: bjohnson_dmns. Today, we entered a new user and got this error message beginning with "bad username."  Is the underscore no longer acceptable as an ASCI character? If not acceptable, can the user and agent information for Bryan Baer be deleted so we can start fresh?  

<html>
<body>
<p style="color: rgb(0, 0, 0); font-family: Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">bad username</p><div style="color: rgb(0, 0, 0); font-family: Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: table;"><div style="display: table-row;"><div style="display: table-cell; vertical-align: middle; padding: 1em;"><img src="https://arctos.database.museum/images/arctos_error_bear.png" style="display: table-row; font-size: small; color: gray;"><div><a href="https://arctos.database.museum/" style="text-decoration: none; color: blue;">Return to Arctos home page</a></div></div><div style="display: table-cell; vertical-align: top; padding: 1em;"><h2 style="font-size: 1.6em; font-weight: 700;">An error has occurred!</h2>May we suggest:<ol><li>On search pages, make sure you do not have values in fields that you do not mean to be there. Or try filling in fewer fields, the more likely to get a match.</li><li>You may not have sufficient privileges to perform that operation.<span> </span><em>Consult with your supervisor or Arctos mentor.</em></li></ol></div></div></div><div style="color: rgb(0, 0, 0); font-family: Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; border: 2px solid green; padding: 1em; margin: 1em; text-align: center;">Please<span> </span><a target="_blank" class="external" href="https://github.com/ArctosDB/arctos/issues/new?assignees=&amp;labels=contact&amp;template=contact-arctos.md&amp;title=error%20feedback" style="text-decoration: underline solid blue; color: blue;">contact us</a><span> </span>if you need assistance in resolving this error. Include the ERROR_ID (below)<span> </span><strong>as text</strong><span> </span>and enough information for us to re-create the problem.</div>

ERROR_ID | EFED058A-E379-4BCD-94C69E719E87D2D5
-- | --
ERROR_TYPE | application
ERROR_MESSAGE | invalid user invitation
ERROR_DETAIL | A user that does not meet requirements was invited to become an operator.

</div>
</body>
</html>bad username

[Return to Arctos home page](https://arctos.database.museum/)
An error has occurred!
May we suggest:
On search pages, make sure you do not have values in fields that you do not mean to be there. Or try filling in fewer fields, the more likely to get a match.
You may not have sufficient privileges to perform that operation. Consult with your supervisor or Arctos mentor.
Please [contact us](https://github.com/ArctosDB/arctos/issues/new?assignees=&labels=contact&template=contact-arctos.md&title=error%20feedback) if you need assistance in resolving this error. Include the ERROR_ID (below) as text and enough information for us to re-create the problem.
ERROR_ID	EFED058A-E379-4BCD-94C69E719E87D2D5
ERROR_TYPE	application
ERROR_MESSAGE	invalid user invitation
ERROR_DETAIL	A user that does not meet requirements was invited to become an operator.
request dump:

request
node_name	
string	arctos-2021
rdurl	
string	/AdminUsers.cfm?makeNewDbUser&bbaer_dmns
uuid	
string	EFED058A-E379-4BCD-94C69E719E87D2D5
exception dump:

Catch
additional	
Struct (ordered)
code	
string	
Detail	
string	A user that does not meet requirements was invited to become an operator.
ErrorCode	
string	
Extended_Info	
string	
ExtendedInfo	
string	
Message	
string	invalid user invitation
StackTrace	
string	lucee.runtime.exp.CustomTypeException: invalid user invitation at lucee.runtime.tag.Throw._doStartTag(Throw.java:212) at lucee.runtime.tag.Throw.doStartTag(Throw.java:201) at adminusers_cfm$cf$11q.call(/AdminUsers.cfm:796) at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:1015) at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:938) at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:219) at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:44) at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2482) at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2468) at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2439) at lucee.runtime.engine.Request.exe(Request.java:45) at lucee.runtime.engine.CFMLEngineImpl._service(CFMLEngineImpl.java:1198) at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:1144) at lucee.loader.engine.CFMLEngineWrapper.serviceCFML(CFMLEngineWrapper.java:97) at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:51) at javax.servlet.http.HttpServlet.service(HttpServlet.java:590) at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74) at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129) at org.cfmlprojects.regexpathinfofilter.RegexPathInfoFilter.doFilter(RegexPathInfoFilter.java:47) at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68) at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68) at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117) at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at runwar.Server$1.handleRequest(Server.java:510) at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52) at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:280) at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79) at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134) at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131) at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:260) at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79) at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100) at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387) at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852) at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35) at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019) at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558) at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449) at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280) at java.lang.Thread.run(Thread.java:750)
TagContext	
Array
1	
Struct
codePrintHTML	
string	794: &lt;cfif REFIND(&quot;[^A-Za-z0-9]&quot;,getTheirEmail.username) or REFIND(&quot;[^A-Za-z]&quot;,left(getTheirEmail.username,1))&gt;<br> 795: &lt;p&gt;bad username&lt;/p&gt;<br> <b>796: &lt;cfthrow message=&quot;invalid user invitation&quot; detail=&quot;A user that does not meet requirements was invited to become an operator.&quot;&gt;</b><br> 797: &lt;cfabort&gt;<br> 798: &lt;/cfif&gt;<br>
codePrintPlain	
string	794: <cfif REFIND("[^A-Za-z0-9]",getTheirEmail.username) or REFIND("[^A-Za-z]",left(getTheirEmail.username,1))> 795: <p>bad username</p> 796: <cfthrow message="invalid user invitation" detail="A user that does not meet requirements was invited to become an operator."> 797: <cfabort> 798: </cfif>
column	
number	0
id	
string	??
line	
number	796
Raw_Trace	
string	adminusers_cfm$cf$11q.call(/AdminUsers.cfm:796)
template	
string	/usr/local/webroot/AdminUsers.cfm
type	
string	cfml
type	
string	application

**Comment by dustymc** [comment]
>underscore

Unrelated. The error would have shown the problem, but that's not logged. I'll change that.

I'm guessing without that, but they've got a different email in their profile and agent page, start there and let me know the entire error if that doesn't fix the problem.

**Comment by sharpphyl** [comment]
That was it!  Inconsistent emails.  Thanks!

**Comment by sharpphyl** [comment]
No.  Even though we fixed the email error, we're getting the same error message

**Comment by sharpphyl** [comment]
<html>
<body>
<p style="color: rgb(0, 0, 0); font-family: Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">bad username</p><div style="color: rgb(0, 0, 0); font-family: Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: table;"><div style="display: table-row;"><div style="display: table-cell; vertical-align: middle; padding: 1em;"><img src="https://arctos.database.museum/images/arctos_error_bear.png" style="display: table-row; font-size: small; color: gray;"><div><a href="https://arctos.database.museum/" style="text-decoration: none; color: blue;">Return to Arctos home page</a></div></div><div style="display: table-cell; vertical-align: top; padding: 1em;"><h2 style="font-size: 1.6em; font-weight: 700;">An error has occurred!</h2>May we suggest:<ol><li>On search pages, make sure you do not have values in fields that you do not mean to be there. Or try filling in fewer fields, the more likely to get a match.</li><li>You may not have sufficient privileges to perform that operation.<span> </span><em>Consult with your supervisor or Arctos mentor.</em></li></ol></div></div></div><div style="color: rgb(0, 0, 0); font-family: Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; border: 2px solid green; padding: 1em; margin: 1em; text-align: center;">Please<span> </span><a target="_blank" class="external" href="https://github.com/ArctosDB/arctos/issues/new?assignees=&amp;labels=contact&amp;template=contact-arctos.md&amp;title=error%20feedback" style="text-decoration: underline solid blue; color: blue;">contact us</a><span> </span>if you need assistance in resolving this error. Include the ERROR_ID (below)<span> </span><strong>as text</strong><span> </span>and enough information for us to re-create the problem.</div>

ERROR_ID | 6C74C2E5-5C34-4502-A6AED205EB6A9BAC
-- | --
ERROR_TYPE | application
ERROR_MESSAGE | invalid user invitation
ERROR_DETAIL | A user that does not meet requirements was invited to become an operator.

</div>
</body>
</html>bad username


[Return to Arctos home page](https://arctos.database.museum/)
An error has occurred!
May we suggest:
On search pages, make sure you do not have values in fields that you do not mean to be there. Or try filling in fewer fields, the more likely to get a match.
You may not have sufficient privileges to perform that operation. Consult with your supervisor or Arctos mentor.
Please [contact us](https://github.com/ArctosDB/arctos/issues/new?assignees=&labels=contact&template=contact-arctos.md&title=error%20feedback) if you need assistance in resolving this error. Include the ERROR_ID (below) as text and enough information for us to re-create the problem.
ERROR_ID	6C74C2E5-5C34-4502-A6AED205EB6A9BAC
ERROR_TYPE	application
ERROR_MESSAGE	invalid user invitation
ERROR_DETAIL	A user that does not meet requirements was invited to become an operator.
request dump:

request
node_name	
string	arctos-2021
rdurl	
string	/AdminUsers.cfm?makeNewDbUser&bbaer_dmns
uuid	
string	6C74C2E5-5C34-4502-A6AED205EB6A9BAC
exception dump:

Catch
additional	
Struct (ordered)
code	
string	
Detail	
string	A user that does not meet requirements was invited to become an operator.
ErrorCode	
string	
Extended_Info	
string	
ExtendedInfo	
string	
Message	
string	invalid user invitation
StackTrace	
string	lucee.runtime.exp.CustomTypeException: invalid user invitation at lucee.runtime.tag.Throw._doStartTag(Throw.java:212) at lucee.runtime.tag.Throw.doStartTag(Throw.java:201) at adminusers_cfm$cf$11q.call(/AdminUsers.cfm:796) at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:1015) at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:938) at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:219) at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:44) at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2482) at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2468) at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2439) at lucee.runtime.engine.Request.exe(Request.java:45) at lucee.runtime.engine.CFMLEngineImpl._service(CFMLEngineImpl.java:1198) at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:1144) at lucee.loader.engine.CFMLEngineWrapper.serviceCFML(CFMLEngineWrapper.java:97) at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:51) at javax.servlet.http.HttpServlet.service(HttpServlet.java:590) at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74) at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129) at org.cfmlprojects.regexpathinfofilter.RegexPathInfoFilter.doFilter(RegexPathInfoFilter.java:47) at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68) at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68) at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117) at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at runwar.Server$1.handleRequest(Server.java:510) at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52) at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:280) at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79) at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134) at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131) at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:260) at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79) at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100) at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387) at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852) at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35) at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019) at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558) at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449) at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280) at java.lang.Thread.run(Thread.java:750)
TagContext	
Array
1	
Struct
codePrintHTML	
string	794: &lt;cfif REFIND(&quot;[^A-Za-z0-9]&quot;,getTheirEmail.username) or REFIND(&quot;[^A-Za-z]&quot;,left(getTheirEmail.username,1))&gt;<br> 795: &lt;p&gt;bad username&lt;/p&gt;<br> <b>796: &lt;cfthrow message=&quot;invalid user invitation&quot; detail=&quot;A user that does not meet requirements was invited to become an operator.&quot;&gt;</b><br> 797: &lt;cfabort&gt;<br> 798: &lt;/cfif&gt;<br>
codePrintPlain	
string	794: <cfif REFIND("[^A-Za-z0-9]",getTheirEmail.username) or REFIND("[^A-Za-z]",left(getTheirEmail.username,1))> 795: <p>bad username</p> 796: <cfthrow message="invalid user invitation" detail="A user that does not meet requirements was invited to become an operator."> 797: <cfabort> 798: </cfif>
column	
number	0
id	
string	??
line	
number	796
Raw_Trace	
string	adminusers_cfm$cf$11q.call(/AdminUsers.cfm:796)
template	
string	/usr/local/webroot/AdminUsers.cfm
type	
string	cfml
type	
string	application

**Comment by dustymc** [comment]
Thanks, I think I see it but it will take a release - that should happen tonight, I hope, or Friday if not.

**Comment by sharpphyl** [comment]
Ok, thanks!
