### ISSUE TITLE
[ geography request ]

### ISSUE THREAD

**Issue by barke042** [ArctosDB/arctos#5372]
Arctos seems to be missing the Missouri county Sainte Genevieve. I downloaded the current GADM Level 2 shapefile and found it (GID_2: USA.26.96_1; see also https://en.wikipedia.org/wiki/Ste._Genevieve_County,_Missouri), but can't find it using any geography search. We have specimens from here, so...

**Comment by dustymc** [comment]
https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10020295

**Comment by barke042** [comment]
Thanks!
