### ISSUE TITLE
[ geography request ]

### ISSUE THREAD

**Issue by barke042** [ArctosDB/arctos#5376]
I should have held off on requesting Sainte Genevieve MO, it turns out our fish data have a number of GADM level 2 (and even 1) entities requiring addition to Arctos. See below:

Geography | GADM Level | GADM ID | Wikipedia | Note 
-- | -- | -- | -- | -- 
Missouri, Sainte Genevieve County | 2 | USA.26.96_1 | https://en.wikipedia.org/wiki/Ste._Genevieve_County,_Missouri | 
Thailand, Trat Province | 1 | THA.71_1 | https://en.wikipedia.org/wiki/Trat_province | 
China, Heilongjiang Province, Mudanjiang | 2 | CHN.11.8_1 | https://en.wikipedia.org/wiki/Mudanjiang | 
China, Hunan Province, Yueyang County | 2 | CHN.14.12_1 | https://en.wikipedia.org/wiki/Yueyang_County | 
Thailand, Phatthalung Province, Pak Phayun District | 2 | THA.40.9_1 | https://en.wikipedia.org/wiki/Pak_Phayun_district | 
Italy, Grosseto Province | 2 | ITA.16.3_1 | https://en.wikipedia.org/wiki/Province_of_Grosseto | 
Asia, Nepal, Central Region, Narayani Zone | 2 | NPL.1.3_1 | https://en.wikipedia.org/wiki/Narayani_Zone | Superceded by provinces but this is not reflected in GADM 
Taiwan, Chiayi | 2 | TWN.7.3_1 | https://en.wikipedia.org/wiki/Chiayi_County | 
Taiwan, Hualien | 2 | TWN.7.6_1 | https://en.wikipedia.org/wiki/Hualien_County | 
Taiwan, Miaoli | 2 | TWN.7.8_1 | https://en.wikipedia.org/wiki/Miaoli_County | 
Taiwan, Penghu | 2 | TWN.7.10_1 | https://en.wikipedia.org/wiki/Penghu | 
Taiwan, Pingtung | 2 | TWN.7.11_1 | https://en.wikipedia.org/wiki/Pingtung_County | 
Taiwan, Taitung | 2 | TWN.7.12_1 | https://en.wikipedia.org/wiki/Taitung_County | 
Taiwan, Yilan | 2 | TWN.7.14_1 | https://en.wikipedia.org/wiki/Yilan_County,_Taiwan |

**Comment by barke042** [comment]
Thanks for editing @Jegelewicz. Any tips on how to paste in a tab-delimited table with formatting? Pasting direct from a spreadsheet added a bunch of Microsoft dreck.

**Comment by Jegelewicz** [comment]
I have no advice - sometime it just works and sometimes it doesn't. It was easy - mostly did it to make it more readable for me....

**Comment by dustymc** [comment]
>paste in a tab-delimited table

Converting to CSV and attaching would make things nice for me, but I'll probably not muck up TOO much if I have to copypasta from some table either....

**Comment by barke042** [comment]
Please note that Sainte Genevieve is the first entry in there, which you've already done. Dunno if we care that much, but I noticed that it's in Arctos as "Sainte Genevieve", not "Sainte Genevieve County".

**Comment by barke042** [comment]
Well, somehow I missed adding a Census Area in Alaska ("Alaska, Skagway-Yakutat-Angoon Census Area"). Please refer to this updated geography addition request table.
[geography_to_add_MMNH.12_16_2022.csv](https://github.com/ArctosDB/arctos/files/10247292/geography_to_add_MMNH.12_16_2022.csv)

**Comment by dustymc** [comment]
I'm not sure what to do about the 'still in GADM but no longer valid' items (some of which are noted in https://github.com/ArctosDB/arctos/issues?q=is%3Aissue+is%3Aopen+geography+cleanup)

I suppose just adding them is most consistent with the documentation, but then with the next (I hope) release of GADM everything will get shuffled again, which isn't great.

We can NOT add them, but then we end up with state- or county-level data in an attribute or something, which isn't great.

@mkoo thoughts on this?

Do you perhaps have a channel to GADM through which we could request updates? Seems like they want to keep on top of this sort of thing, perhaps we can help them prioritize or ?????

**Comment by dustymc** [comment]
I added the one record that seems to meet current standards:

[geography_to_add_MMNH.12_16_2022(1).csv](https://github.com/ArctosDB/arctos/files/10271263/geography_to_add_MMNH.12_16_2022.1.csv)

Many of the rest are GADM2 which is out of scope.

I'm still hoping to hear from @mkoo on the remainder (comment above this one).

**Comment by barke042** [comment]
@dustymc darn I didn't RTFM closely enough. I didn't realize that GADM level 2 were only recognized for the US/UK. That kind of stinks because then I will have to push all of those identifiers down to the locality level--since we have that information it doesn't make sense to just drop it (although I guess it will also be retained in the verbatim locality).

**Comment by dustymc** [comment]
> retained in the verbatim locality

Specific locality as well, I hope!
