### ISSUE TITLE
Login and password reset not working

### ISSUE THREAD

**Issue by adhornsby** [ArctosDB/arctos#5377]
I was able to log in (user adhornsby1) this morning, but this afternoon Arctos isn't recognizing my password across Mac/PC and Chrome/Safari/Firefox.  My student is able to log in to her profile just fine.  I've tried to reset my password twice, but I'm not receiving any reset emails to inbox or spam folder.

**Comment by dustymc** [comment]
Unlocked, and I forwarded your latest password reset info via email.

**Comment by adhornsby** [comment]
That worked, thanks!
