### ISSUE TITLE
Why is this still a "Funky Agent"?

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#5379]
I continue to get daily alerts for this "funky agent"
<img width="1434" alt="Screenshot 2022-12-15 at 12 35 52 PM" src="https://user-images.githubusercontent.com/17605945/207972550-9c71a5ba-2a29-46c6-94a5-2914e9fe78d6.png">

The agent in question does have "ascii variant" entries as multiple AKAs.
<img width="731" alt="Screenshot 2022-12-15 at 12 38 05 PM" src="https://user-images.githubusercontent.com/17605945/207973788-3363c263-557f-412b-a159-6b3d05a8b44b.png">

Our "[Best Practices - Creating Meaningful Agents](https://handbook.arctosdb.org/best_practices/Agents.html)" documentation says this:

> Do include symbols and their alternatives where users might search by either. For preferred name “Smith & Wesson,” also include name “Smith and Wesson.” (It doesn’t matter which goes where, as long as both are included with the agent.)

In particular for organizations (often corporate manufacturers) our practice is to make the format of the Preferred Name  as it appears on the labels or emblazoned on an object.

Shealyn has created three AKAs that provide full-text descriptions for the abbreviations in the preferred name, which is how the name appears on the jar of vaseline.

What can we do to make this agent entry comply with our departmental best practices, Arctos recommendations, and the agent rules so I stop getting daily notifications for this (and future) funky agents?

**Comment by dustymc** [comment]
Neat, you broke my scripts! I'll update ASAP.
