### ISSUE TITLE
Feature Request - add "Require Tissues" & "Cataloged Item Type" & Media to new specimen search interface

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#5380]
@dustymc 

The new search interface no longer has a check box for 'Require Tissues' which is intended to make it easier for users to find tissue samples. It's used regularly. Please add it.

There has been lots of discussion recently about cataloged_item_type. See updated definitions: 
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcataloged_item_type

The new search interface doesn't have a way of searching cataloged_item_type so it should be added and made more obvious than in the current search page.

**Comment by ccicero** [comment]
Also, I don't see have a way to search media by type on the new interface - ?

**Comment by ccicero** [comment]
Never mind regarding Media, I see Media that in test.

**Comment by ccicero** [comment]
@dustymc when is the next release that will include this?

**Comment by dustymc** [comment]
>@dustymc when is the next release that will include this?

>3 days ago

**Comment by campmlc** [comment]
I'm not seeing anything but media type?

**Comment by campmlc** [comment]
I think we were expecting these to be placed on the main search page. To
find Is Tissue, users have to know to customize the  search, and select
parts as subcategory. Public users will have no idea.

**Comment by ccicero** [comment]
I agree, better to have that as a main search term on the page rather than as a customizable term - it's currently hidden unless you know to look there.

**Comment by dustymc** [comment]
>main search term

I don't think any term which is used by only (or even primarily) a small group of users should be forced on everyone.

Portals can be used to dynamically create forms for just about any user group. I think broader groups are probably more useful, but there's really no limits on those. I just need a URL, list of search fields and defaults, and ordered list of results fields to create those.

I'd suggest @ArctosDB/search-ui-task-group address this, but I don't think there's adequate representation there either.

(And please try to reset the milestone when you reopen an Issue - I try to catch that but don't always, and 'in next release' issues get magicked closed.)

**Comment by ccicero** [comment]
adding @atrox10 to this thread because she also views this as important for MVZ. So with 'portals' is it possible to create collection-specific search interfaces, and if so, how and where?

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/5341 has some examples, just let me know the stuff in https://github.com/ArctosDB/arctos/issues/5380#issuecomment-1372775826.
