### ISSUE TITLE
genbank report isn't completing

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5381]
The notifications seem to have failed partway through. The table https://arctos.database.museum/info/mia_in_genbank.cfm seems OK, and I've attached collection-match data and contacts.

[temp_gb_collection.csv](https://github.com/ArctosDB/arctos/files/10246436/temp_gb_collection.csv)

 @msbparasites
 @mkoo
 @ewommack
 @campmlc
 @ccicero
 @kderieg322079
 @StefanieBond
 @catherpes,@catherpes
 @amgunderson
 @atrox10
 @DerekSikes
 @gracz-UNL
 @mvzhuang
 @cjconroy
 @jtgiermakowski
 @lin-fred
 @adhornsby
 @jebrad
 @jandreslopez
 @AdrienneRaniszewski
 @acdoll
 @SerinaBrady
 @jldunnum
 @jrdemboski
 @kyndallh

**Comment by acdoll** [comment]
Are you looking for any type of action on our part?

**Comment by dustymc** [comment]
>any type of action 

Nope, the issue is (mostly) for me. 

If you're pinged here you're a collection contact for a collection which has unlinked collection match data in GenBank and might have missed the expected notification - I'm just trying to make up for that as much as I can.

**Comment by acdoll** [comment]
Thanks

**Comment by dustymc** [comment]
Suspect this was related to https://github.com/ArctosDB/internal/issues/187, I'm not seeing recent problems.
