### ISSUE TITLE
Taxonomy Checker

### ISSUE THREAD

**Issue by barke042** [ArctosDB/arctos#5382]
Hi, I just tried to upload our fish taxa to start cleaning these up and got an error:

ERROR_ID | DD6594D4-AEA1-4592-88F04139373B4275
-- | --
ERROR_TYPE | application
ERROR_MESSAGE | Error invoking external process
ERROR_DETAIL | psql:/usr/local/webroot/temp/excopy_barke042_20221216101240455_903.sql:2189: ERROR:  syntax error at or near "acipenser" LINE 2: acipenser fulvescens         ^

Here's the file:
[fish.taxonomy.query.csv](https://github.com/ArctosDB/data-migration/files/10247404/fish.taxonomy.query.csv)

Any idea what might be happening @Jegelewicz @dustymc? I tried deleting the first blank line but that doesn't seem to help. Thanks!

_Originally posted by @barke042 in https://github.com/ArctosDB/data-migration/issues/1118#issuecomment-1355176703_

**Comment by dustymc** [comment]
<img width="250" alt="Screenshot 2022-12-16 at 8 53 14 AM" src="https://user-images.githubusercontent.com/5720791/208148921-307304c0-0edb-46e1-8f7f-ffefe0a2f725.png">

Kill the blank line and try it.

**Comment by barke042** [comment]
I did. Still fails:



ERROR_ID | B02D7C4A-00C2-42C2-BD1CEF2A991335CB
-- | --
ERROR_TYPE | application
ERROR_MESSAGE | Error invoking external process
ERROR_DETAIL | psql:/usr/local/webroot/temp/excopy_barke042_2022121610120995_557.sql:2190: ERROR:  syntax error at or near "acipenser" LINE 2: acipenser fulvescens         ^

**Comment by dustymc** [comment]
Something (linefeeds maybe) about your CSV isn't very CSVish. i opened in and saved from Excel which probably broke like 12000 other things, but the resulting file did SOMETHING....
 
[sciname_lookup(1).csv.zip](https://github.com/ArctosDB/arctos/files/10247630/sciname_lookup.1.csv.zip)

**Comment by barke042** [comment]
Thanks! I checked, the file has Unix linefeeds. Are they not handled?
