### ISSUE TITLE
Can we drop "County" from US geography?

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5383]
Please note that Sainte Genevieve is the first entry in there, which you've already done. Dunno if we care that much, but I noticed that it's in Arctos as "Sainte Genevieve", not "Sainte Genevieve County".

_Originally posted by @barke042 in https://github.com/ArctosDB/arctos/issues/5376#issuecomment-1353698567_

**Comment by barke042** [comment]
This would avoid the whole County/Parish issue.

**Comment by dustymc** [comment]
Yea, we should care for the sake of consistency. I fixed that one.

I DID NOT remove the 'rank' from these when I GADMified everything, and now they're inconsistent with the rest of the world and I keep making messes. Can we just trim County/Parish/Census from US 'county' names?

**Comment by ewommack** [comment]
> Can we just trim County/Parish/Census from US 'county' names?

Just throwing possible problems around for discussion - if we drop 'county' will it confuse anyone when a county is the same name as a town or city in the same state? 
Example: If I had a locality of Laramie in Wyoming that could either be Laramie in Albany County WY, or could be Laramie County in WY. Or Sheridan in Wyoming could be either the town of Sheridan in Sheridan County, WY or Sheridan County in WY. 

I know when curatorial is picking higher geography that for the first locality we will have to pick Albany County, WY to go along with the specific locality, but will visitors spot the difference when they look at the locality information they download?

**Comment by dustymc** [comment]
I'm sure users can find infinite ways to confuse themselves, but they can also just turn the 'county' column on in downloads.

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/5395 and https://github.com/ArctosDB/arctos/issues/5376 illustrate the kinds of problems being inconsistent against GADM cause. Going active on this; I don't think the data provide any real choice on what to do here.

**Comment by Jegelewicz** [comment]
I guess I don't feel strongly, but most users are used to providing "county" in the bulkloader and I would think this might be a headache for a while until everyone gets on board - could we send out a warning email/tweet/banner before this gets done?

Also, let's be sure to adjust everything hanging out in the bulkloader whenever this happens.

**Comment by ewommack** [comment]
Ah we're changing again? I thought we had already updated.

> could we send out a warning email/tweet/banner before this gets done? @ewommack @lin-fred

Yes we can help. When are things getting switched?

**Comment by Jegelewicz** [comment]
We haven't switched - the US geography still contains "county" - https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=1046

**Comment by Jegelewicz** [comment]
>  When are things getting switched?

That's a question for @dustymc

**Comment by dustymc** [comment]
Before the next time someone shows up with some gap involving the US would be nice!

I'm not in a huge hurry and can do this about any time, but I'd rather not let it hang out forever either. It'll take a ton of CPU so I might do it by state to spread the load, which might mean it'll take a week or so. I can fix stuff in the bulkloader while I'm updating other stuff. Anyone want to suggest a schedule?

**Comment by ewommack** [comment]
I like county, I'm going to set your the longest schedule. So someone else should probably chime in.

**Comment by campmlc** [comment]
Absolutely agree we need county.

**Comment by Jegelewicz** [comment]
UGH - Can we get GADM to add county?

**Comment by ewommack** [comment]
Do they have Github? We could badger them

**Comment by dustymc** [comment]
I'm going to remove ranks, not places - see opening comment - that's clear, right??

**Comment by AJLinn** [comment]
I agree, I like and prefer to keep county (even tho we have boroughs in Alaska).

**Comment by Jegelewicz** [comment]
Ok this is what I thought was going on

Right now we have - [United States, New Mexico, Bernalillo County](https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=1046)

But after we would have - [United States, New Mexico, Bernalillo](https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=1046)

Right?

**Comment by dustymc** [comment]
>fter we would have 

Yes - because [that's what GADM has](https://gadm.org/maps/USA/newmexico/bernalillo.html) and after a whole bunch of meetings and talks and trying stuff and gnashing of teeth and crying in the corner we all agreed to do what GADM does, which does not involve qualifiers.

I tried to leave the US alone (because tradition) but it's just not tenable - I have to strip or add any time I need to match something, and then there's Bouroughs and census areas and parishes and bah! - it's just not workable, and that's been demonstrated a few times since this was opened - an opening involved a new collection getting drug into a mess because we don't do what our documentation says we do.

**Comment by ewommack** [comment]
So we are keeping the name of counties in higher geography, we are just getting rid of the word "County"?

That's less terrifying, and will allow us to maintain accuracy.

And we can also keep writing "county" in verbatim locality text correct?

**Comment by dustymc** [comment]
AWG Issues Meeting: Go, but with https://github.com/ArctosDB/arctos/issues/5594

**Comment by dustymc** [comment]
Scheduling to begin 2022-02-20.

**Comment by dustymc** [comment]
nvrmind https://github.com/ArctosDB/arctos/issues/5654#issuecomment-1472683826
