### ISSUE TITLE
Need Help with Arctos Error - MVZ:Mamm:242211 could not be resolved.

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#5384]
# Error Text
MVZ:Mamm:242211 could not be resolved.
--

# Where it happened, # Steps to get there
I entered a record yesterday morning and it appeared to load. It is gone from the bulkloader. However, I still cannot find a fully formed record. If I look up records attached to the accession, through the accession interface, there is a row for the specimen, but it lacks most data. It only holds collector number and a few measurements. No catalog number. I cannot find the specimen via the normal search. The error that comes back is 

MVZ:Mamm:242211 could not be resolved.

Carla Cicero says that she sees this too, but usually resolves in a few hours. Should I continue to wait for this?

# Problem
I may have done something wrong in data entry, but there doesn't seem to be a way to fix this from my end, or see what I might have done wrong. 

# Solution
Any advice?
<img width="748" alt="Screenshot 2022-12-16 at 9 00 28 AM" src="https://user-images.githubusercontent.com/5749672/208151489-a831ae2e-029d-4708-9b08-6d668de9dc92.png">
<img width="1238" alt="Screenshot 2022-12-16 at 8 59 55 AM" src="https://user-images.githubusercontent.com/5749672/208151496-e3deff06-c267-4e8e-aa15-270a5aa4bdc7.png">
<img width="986" alt="Screenshot 2022-12-16 at 8 59 47 AM" src="https://user-images.githubusercontent.com/5749672/208151497-cb6823dd-2814-4503-b041-ded16c9439f4.png">

**Comment by dustymc** [comment]
<img width="546" alt="Screenshot 2022-12-16 at 9 24 30 AM" src="https://user-images.githubusercontent.com/5720791/208154141-8d4e9b0d-5328-40a4-b6a6-1c35dcc1bca5.png">

It's almost caught up.

**Comment by dustymc** [comment]
Confirmed this now works for rights-having users. Public cache looks like it may not catch up before the outage but should before end of day.
