### ISSUE TITLE
[CONTACT] Question on searching part remarks

### ISSUE THREAD

**Issue by krgomez** [ArctosDB/arctos#5385]
Is there a way to search part remarks for an exact term? It's not working to use "=" in front of what I want to find. Instead I get results for items with part remarks that include the term and more. Specifically, I want to find all records that have the media part remark "photograph" and nothing else.

**Comment by dustymc** [comment]
>search part remarks for an exact term? 

No, but there will be when Arctos comes back up this afternoon.

>part remark "photograph"

That's not a very good place for that, @ccicero is working on a better solution, I'm sure your input would be appreciated. I'm not sure if that's rolled up in the [observation discussions](https://github.com/orgs/ArctosDB/teams/observation-interest-group) or will take a life of its own. https://github.com/ArctosDB/arctos/discussions/5378 is also potentially relevant, although the latest discussion looks like we're not going to do anything to distinguish 'part of the object' parts from media (however correctly, or not, it might be used....).
