### ISSUE TITLE
low-data agent cleanup question and request

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#5386]
Two items related to #4903 process.

UAM:EH has 918 offending low-data agents on the [cleanup list ](https://docs.google.com/spreadsheets/d/11Hy5kG7kcrSIBB-VLY9jedRp5jDWGCZlJKnY-jKv0X0/edit?usp=sharing) that we are working diligently to upgrade. We have successfully updated around 120, most of which we found upgradable data and only a few were noted as truly low-data requiring verbatimization.

HOWEVER I don't anticipate we'll be able to get all 900+ records upgraded before they are schedule to be verbatimized at the end of January since there are only three of us working on it about once per week as we find time. I'm concerned about 1) the additional time it's going to take to re-agentify them once they've been verbatimized while also 2) losing access to  activity information for that non-agent verbatim agent. As I've discussed offline with @KyndallH it's valuable for us as managers of collections to be able to look up someones agent activity to determine if they should be loaned to, or to determine if they are/are not the same as someone whose activity is represented in another person's collection.

Is it possible to request an exemption from the verbatimization process for UAM:EH or others who are working on upgrading the data but are finding it a huge time consuming task for three people? I have seen some collections added a relationship "associate of" museum departmental agent as a way of adding one additional piece of information to circumvent the verbatimization process. I don't really want to do that... but if it's the only option can someone help me with a bulkload process to make that happen?

Thanks for considering. I tried to attend the Agent committee meeting on the 14th but I had to pick up my kid from school.

**Comment by ewommack** [comment]
Just checking on a couple things in case this might save some time and worry:
1. The agents will become verbatim agents if they only are used as [collector roles](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcollector_role) in Arctos. If they appear elsewhere they will not be switched over to verbatim agents.

2. You can actually look up verbatim agents and see their objects results
![Agents_search](https://user-images.githubusercontent.com/18562884/208192166-1e336740-b2c2-42b2-8027-d91d5d10d159.png)
![Verbatimagent_objectrecord](https://user-images.githubusercontent.com/18562884/208192198-f4d49160-f0b8-4981-8a5c-11544610626e.png)
![Verbatim Agents](https://user-images.githubusercontent.com/18562884/208192238-1a6fb090-c7d1-4df5-94d7-a90e0d355076.png)
So the agents are not disappearing, nor will any data they are associated with. 

Did I get that right @lin-fred ?

**Comment by dustymc** [comment]
Making some sort of collection-or-whatever based exception would be difficult, and a great place to introduce bugs. Let's don't do that, but that doesn't mean we have to get all nukey either. We could

* delay a bit, although there does need to be some endpoint in sight, or
* I could help you make the flaky relationships, and then un-make them whenever you're done.

And please see https://github.com/ArctosDB/arctos/issues/4554#issuecomment-1287455870 regarding the aforementioned flaky relationships. IDK how, but if this is going to turn in to something awesome (like, say, dropping the unique constraint on preferred name) it's going to have to involve something more than people playing lowest-possible-effort limbo with whatever bar we set up. Maybe we can find a way to get rid of all flaky/pointless relationships when we get rid of your temporary ones, if that's the way this goes.

>So the agents are not disappearing, nor will any data they are associated with.

Exactly right. Anyone who's involved in any sort of transaction activity already has more information than a verbatim agent can carry, so can't be involved in this process. I suspect this isn't understood and people erroneously see the flaky relationships and "(presumably) not dead on the day they ran over this squirrel" statuses and such as a way to preserve data???
