### ISSUE TITLE
Feature Request - add "Permit  not applicable" to dropdown for accessions

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#5388]
When you create an accession, there is a dropdown when editing the accession that says "I do not wish to enter permit information at this time" - if you haven't added a permit, you can't edit the accession without selecting that option.

Permits are not always applicable (e.g., observational records and some other cases).

Please add to the dropdown "Permit not applicable". If selected, then you shouldn't have to select that each time you want to edit the accession.

![image](https://user-images.githubusercontent.com/967275/208530060-60d7b987-ac9c-4d47-98f0-36265eee8da7.png)

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/1139 was a long time ago and I can't find any AWG notes, but I think we discussed this scenario. In any case, there's about a 100% chance that'd be misused, it would require some sort of new structure, there'd be no place for metadata (who says you don't need a permit?), etc etc. Suggest you just issue yourself a 'nope' permit (or a bunch of them or whatever), include whatever data you think might be useful, and use it/them however you want. I think it's the same functionality but there's already UI, places for metadata, etc.

**Comment by ccicero** [comment]
OK, that makes sense. Thanks!
