### ISSUE TITLE
Record load in test

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5389]
@dustymc I am working on some stuff in test for a prospect and I entered a record a couple of hours ago and it's still sitting there. Can you jiggle the wires or something?

**Comment by dustymc** [comment]
jiggled

**Comment by Jegelewicz** [comment]
I still isn't showing up in search results.

**Comment by Jegelewicz** [comment]
Demo:Inv:22818

**Comment by dustymc** [comment]
That wasn't as fun as the whisperings might have been.

**Comment by Jegelewicz** [comment]
Maybe you'll enjoy whispering to the part bulkloader?

**Comment by dustymc** [comment]
You can whisper to component loaders: https://arctos-test.tacc.utexas.edu/ScheduledTasks/component_loader.cfm?debug=true
