### ISSUE TITLE
[CONTACT] lot count for collection objects versus part attributes

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#5390]
I'm working on uploading Jim Patton karyotype data which has different preservations and/or representations. The karyotypes may be on a slide, mounted, or represented by a photo print or 35 mm negative (not digital). There may be multiple slides, mounts, or representations for a given specimen.

For example:
MVZ:Mamm:239722 has 23 different variations on preservation/representation for the karyotype:
![image](https://user-images.githubusercontent.com/967275/208555178-27285242-d6a7-4f75-abbf-ce320f35a4b8.png)

There is no option currently for lot count in part attributes, yet lot count is required for the part. I want to first upload the part to create 'karyotype' for the records and then do a separate upload for the attributes. What should I enter for lot count? I can put the counts after the unique attributes (e.g., representation= '35 mm negative' and attribute remark = 'BamH1 digested Giemsa stained mitotic metaphase (4)') but I still need an overall lot count for the karyotype part.

There is no easy way to add up all the counts for each cataloged item and make that sum the lot count. There are 3-4K parts.

Thoughts?

**Comment by dustymc** [comment]
>Thoughts

Wild guesses and remarks. Nobody's going to care that you have 23 images, probably anyone who wants that stuff will want it all, and it's not like a liver sample where usage results in less material and lot count might influence what you're willing to loan. I just can't get my head around how lot count could be very important here, at least not before someone wants to get their hands on the slides - and then they can count them for you, or that usage will result in the lot being split into many citable parts, or ....

> lot count as a part attribute.

So file an issue and have fun. I don't think you'll convince the world that counting to almost-always-one requires that much overhead/metadata, but there's no reason "factual" information can't be repeated as attributes where it has access to that structure.

**Comment by campmlc** [comment]
I filed an issue, #5393, so we can at least add the part lot count attribute.

**Comment by ccicero** [comment]
@dustymc I do think it's important to know how many (e.g.) negatives we have of a representation, so if someone does want them all we know how many 'all' is. Patton thought it was important, so we don't want to lose those data.

Going to the other issue...

**Comment by dustymc** [comment]
>important to know how many

At some level, I think all "important" parts have a lot count of 1 - you can just DO MORE with 27 individually-identifiable THINGS than you can with one vague cluster of allegedly-27 nameless members. 

The purpose (at least, the pparts I'm not supposed to ignore lacking https://github.com/ArctosDB/arctos/discussions/5378) of part=media is to introduce physical material to the object tracking system, or to loan media items. You can't effectively do that with lots. 

Maybe it would be better all around to enter these differently?

**Comment by Jegelewicz** [comment]
> Maybe it would be better all around to enter these differently?

Agree - At the least, I would enter 23 karyotype parts, each with the appropriate attributes. Easy enough using the part bulkload tool.

**Comment by ccicero** [comment]
So the suggestion is to enter karyotype 23 times, each with it's lot count, vs one karyotype part with 23 different representations? I guess I could do that. It doesn't really matter as long as it's findable. Thanks (leaving this open until I actually get it done in case I run into issues).

**Comment by campmlc** [comment]
Also, who wants to count the 23 parts? It is useful to know the actual starting count of a lot, at least for biological collections. And the lot is the parent, and split lots are the children of these types of collections which typically share a container and barcode. If I have 23 objects that share a barcode, I can no longer use batch tools to add parts to loan. There are many other management implications here that are not being considered. Theoretical implications aside, we need to provide people the tools they need for effective management or they will come up with add hoc work around that inevitably cause messes and result in lost data.

**Comment by campmlc** [comment]
@DerekSikes

**Comment by ccicero** [comment]
So based on the comment from @campmlc, I've gone back to thinking we need to sort this all out (including related issue [5393](https://github.com/ArctosDB/arctos/issues/5393) before I move forward with uploading Jim's data. I would prefer not to wait until the next CT meeting which is January 19th, so can we prioritize these issues for discussing during the first 'issues' meeting on January 5th? It would be good to have others weigh in on this.

**Comment by Jegelewicz** [comment]
> can we prioritize these issues for discussing during the first 'issues' meeting on January 5th? 

I am not in favor of bringing complex issues without a proposed resolution that at least the code table committee has agreed to into the general issues meeting. Whenever we do this, a single issue takes up a quarter or more of the Issues meeting and things that should get done, don't get done. 

> It would be good to have others weigh in on this.

They almost NEVER do that in a general issues meeting because they haven't even seen the issue and they don't have time to read through it, they just hear us arguing about things they didn't even think were a problem.

My objection to this is that we will now have counts in two places. Also, right now, I am actually not sure what is being proposed. Are we adding a part attribute = lot count OR are we adding lot count to ALL part attributes? The second seems like a HUGE deal as it would add another field EVERY part attribute (and the bulkloader).

**Comment by dustymc** [comment]
> not sure what is being proposed

I'm not either. I thought we were talking about two distinct things, now they seem be bleeding together. The other one is lacking fundamental information so it really can't be discussed. Here, https://github.com/ArctosDB/arctos/issues/5390#issuecomment-1359783539 seems to me to contain everything that's needed: my assumptions were wrong, these data are in fact important, and there's only one defensible way to treat important components of a catalog record.

>OR are we adding lot count to ALL part attributes

Not that, anyway!

**Comment by campmlc** [comment]
I'm on the road with family and can't keep up with this discussion, but the request was to add parts lot count as a part attribute as we have done with preservation, NOT add lot count to all part attributes. That way we can add metadata as needed. This helps track changes in lot count as lots are split over time. Having to make a separate part for all parts in a lot is not a viable solution for collections that manage lots.

**Comment by ccicero** [comment]
I'm also getting a little lost in this discussion, but if we add lot count as a new part attribute AND keep lot count for each part, then 
1) we will have counts in two places (which @Jegelewicz doesn't like, I understand why)
2) I'm still unsure what to put in the part lot count which is now required. 

It seems that both @dustymc and @Jegelewicz favoring creating a separate part for each one (23 parts in the example I gave). I'm not crazy about that either because it just makes the detail page very messy.

Rather than discuss at the issues meeting or wait until the next CT meeting in late January, how about a separate smaller meeting in early January with @Jegelewicz @dustymc @campmlc to hash this out and come up with a proposal to bring to the CT/issues meeting? I find it's easier to discuss these complex issues in person rather than just through github comments.

**Comment by Jegelewicz** [comment]
@ccicero can we close this in favor of #5393 and keep this to one issue?

**Comment by dustymc** [comment]
Closing as inactionable; please refile as a discussion if necessary.
