### ISSUE TITLE
Please have clones made into bulkloader appear with verification status = unverified

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#5392]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

THis was not previously a problem but now it is - any clones made into the bulkloader set to load now fail to load because:

VERIFICATIONSTATUS must be unverified for initial load

So could the clone into bulkloader tool please be improved to make these clones with verificationstatus changed to unverified.

It is a pain to have to change these after they are made in order to load them.

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.
medium

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/4982
