### ISSUE TITLE
Add Inv to Table ctspecimen_part_name: Media

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#5394]
See 2022-12-15/03:03 | Authority Change Notification

For some reason Invertebrates were omitted from collections with access to media as a part name

<img width="1442" alt="Screenshot 2022-12-20 at 8 35 20 AM" src="https://user-images.githubusercontent.com/15368365/208705284-67b0744c-2fe3-4cd2-8024-e5021bd863f8.png">

Please add.  Thanks.

**Table**
ctspecimen_part_name

**Proposed Value**
media

**Collection type**
Inv

**Comment by dustymc** [comment]
done
