### ISSUE TITLE
[CONTACT] - GUID pages that include a special header are not performing correctly

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5396]
Working on some agent stuff and went to an ASNHC record, which now looks like this:

![image](https://user-images.githubusercontent.com/5725767/208715682-a5ab71c0-9c33-4202-90d0-d03f3cf534b8.png)
![image](https://user-images.githubusercontent.com/5725767/208715762-80f16cf9-58cf-4fd2-8c52-25ed65c3dd93.png)
![image](https://user-images.githubusercontent.com/5725767/208715855-0e1786e1-255c-4885-bb1f-1c0f8aa29950.png)
![image](https://user-images.githubusercontent.com/5725767/208715941-4a7c3aa4-8bd7-4209-be7e-0a285766d9f3.png)

I am assuming it is the css header causing the problem - many collections are using custom headers for their catalog records, so this needs fixing, even if it involves removing them for now.

https://arctos.database.museum/guid/ASNHC:Mamm:20257

**Comment by Jegelewicz** [comment]
Also, this leaves me no options to edit the record. (At least I can't find them).

**Comment by dustymc** [comment]
patched
