### ISSUE TITLE
Geography notification adjustment

### ISSUE THREAD

**Issue by szaborac** [ArctosDB/arctos#5400]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

Arctos can't find a feature (in this case, a national park) in Find Geography, even when it recommends use of that exact feature

**To Reproduce**
1. After logging into Arctos, pull up GUID "UAMb:Herb:58680" (https://arctos.database.museum/guid/UAMb:Herb:58680)
2. Click on Locality tab
3. Click on Edit Locality
4. Note the message "This locality is not using a spatially appropriate geography. Suggest: [North America, United States, Alaska, Kobuk Valley National Park](https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10006854)"
5. Click on "Change for this Locality"
6. Under "Feature", select Kobuk Valley National Park 

**Expected behavior**
I SHOULD be able to find Kobuk Valley National Park, especially since the system recommends it. Instead, system returns "No data available in table"

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.
Priority 2. Functionality is broken, but I don't have to make this correction in order to get the record into Arctos.

**Comment by dustymc** [comment]
See https://github.com/ArctosDB/internal/issues/222 - you are seeing a lag in the system, that recommendation is very old. You can delete it, but I think perhaps Arctos can do better as well so I'm hijacking your issue.

>I SHOULD be able to find Kobuk Valley National Park

Find, yes, and you can - these may be found by https://arctos.database.museum/search.cfm?higher_geog=&geog_shape=Kobuk+Valley+National+Park&geog_srch_type=contains, for example. (There are several other ways which use the same data to find them.)

ASSERT - absolutely not, see https://handbook.arctosdb.org/documentation/higher-geography.html. 


>Functionality is broken

Again, please note that not being able to assert such geography DOES NOT mean the record isn't findable by the Feature. This results in better, more consistent functionality, not worse/less (but it is different than the old system). 

In general, I **suggest we get rid of all "smaller is better and there's something available" notifications;** Arctos is still making those discoverable by the intersecting shapes and shape-names, I don't think there's anything wrong with more general/less-specific geography assertions in the current system (so yay current system!).

Going next task for that, please let me know ASAP if there's any reason to retain this notification.

**Comment by szaborac** [comment]
I interpret this to mean that I need to wait the system out a little - the
"lag" that you refer to - as well as reset my expectations for
functionality. I'm suffering from "This is how the old system worked". If
the new system offers a better experience (and it looks like it will), I'm
all for it! I can deal with a bit of retraining. :)

Thank you!!

**Comment by dustymc** [comment]
Yes, I think that's about right.

I have magic tools but they're slow; I'm hoping to get some help changing that.

The old system was a big jumble of all sorts of things, the new follows bigger-than-Arctos standards so is very predictable.

The spatially-aware bits of the jumble survive (and can be added to) for use in discovery.

This particular notification doesn't make a lot of sense under the more-organized system; I can get the same discoverability without needing the collections to change stuff.

**Comment by szaborac** [comment]
Arctos is very powerful, which comes at a cost: it can sometimes be
challenging to use. Therefore, "predictable" = wonderful.
I'll take it.
