### ISSUE TITLE
'Pick new collecting event' is buggy

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#5406]
I'm went to pick a new collecting event for MVZ:Bird:186150. I was able to select the event but when I tried to save, nothing happened (tried both Chrome and FF). Refreshed a few times and still nothing. Then suddenly a window popped up with a 504 (?) error quickly, then reverted back to the specimen detail page and the new event was saved. Not sure how reproducible this is, but it's worth seeing if others are encountering similar issues.

**Comment by dustymc** [comment]
Error logs are showing a bunch of timeouts, which might be because of whatever you're searching but mostly looks like network flakiness. merge-->https://github.com/ArctosDB/internal/issues/187
