### ISSUE TITLE
Code Table Request - Agent Type definition updates

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5410]
**Goal**
Create better definitions for agent types since removal of the "group" agent type and make definitions more professional

**Context**
Current definitions for these terms are:

Agent Type | Definition 
 -- | -- 
bot | Agent that represents a computer program that performs automatic repetitive tasks and writes a specific kind of data to relevant bulkloaders. See functions/create_bot_agent for details.
organization | A named organization, such as US National Park Service
other agent | Mishmash of garbage largely synonymous with "unknown." Examples: "native", "crab boat", "student", "WIT 48", "Post."
person | Person agents have additional atributes, such as first, middle, and last names and birth and death dates

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctagent_type#organization 

**Proposed Value**
No changes in values are proposed

**Proposed Definition**

Agent Type | Definition 
 -- | -- 
bot | Agent that represents a computer program that performs automatic repetitive tasks and writes a specific kind of data to relevant bulkloaders. See functions/create_bot_agent for details.
organization | An organized body of person agents with a particular purpose, especially a business, society, association, etc. It is recommended this be used for formal organization ssuch as "United States National Park Service".
other agent | An informal organization or group such as "Paul May and Spencer Lucas". **CAUTION** use of these types of groups will not provide appropriate attribution of effort to the individual associates. Consider using individual people or organizations as active agents in determinations and other activities.
person | A human being regarded as an individual.

**Priority**
[  Please choose a priority-label to the right.  ]

**Comment by Jegelewicz** [comment]
@ArctosDB/arctos-code-table-administrators please review.

**Comment by dustymc** [comment]
3 are great.

You're being way too nice considering the reasons 'other agent' exists, BUT [none of those should see February](https://github.com/ArctosDB/arctos/issues/4554), and (I think because of group cleanup) other agent now contains things like https://arctos.database.museum/agents.cfm?agent_id=9. Suggest:

1. Wait for the big cleanup event
2. Manually+carefully review remaining 'other agents'
3. Convert whatever survives those processes to 'organization' and drop the 'other agent' not-quite-distinction.

That would probably mix some "you and me" junk in with NPS and company, but I think maybe that's less-evil than keeping the extra overlapping+arbitrary category.

**Comment by Jegelewicz** [comment]
> That would probably mix some "you and me" junk in with NPS and company, but I think maybe that's less-evil than keeping the extra overlapping+arbitrary category.

Yes, I considered making the definition of organization reflect the removal of other and perhaps we should do that now?

organization - an organized body of person agents with a particular purpose, especially a business, society, association, etc.

**Comment by dustymc** [comment]
>perhaps we should do that now?

I sort of like having some of them segregated (makes review easy, and whatever survives the big cleanup needs review), the existence of the term probably encourages garbage creation, not sure how to balance that...

>organization - an organized body of person agents with a particular purpose, especially a business, society, association, etc.

Nice.

**Comment by Jegelewicz** [comment]
@ArctosDB/agents-committee approves of new definitions.

**Comment by Jegelewicz** [comment]
Code table definitions changed.
