### ISSUE TITLE
Code Table Request - Agent Name Type definition updates

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5411]
**Goal**
Create better definitions for agent name types and make definitions more professional

**Context**
Current definitions for these terms are:

AGENT_NAME_TYPE | Documentation 
-- | -- 
Kew abbr. | A string as published in Brummitt, R.K. & Powell, C.E.  (1992), Authors of Plant Names, Kew: Royal Botanic Gardens, ISBN  978-1-84246-085-6 
aka | Any alternate name 
birth name | Name given at birth. Old "maiden" name. 
first name | given name; old person.first_name 
job title | current job title (rescued from old addr table) 
labels | Used by the reporter function as a way of abbreviating agent  names so that they fit on labels. Example: "CJ Conroy" instead of  "Christopher J. Conroy." This is useful for small labels/boxes.  Developed for MVZ reports but can be used by anyone. 
last name | family name; old person.last_name 
login | Exact case-sensitive name used to log into Arctos 
middle name | middle name; old person.middle_name 
preferred | The one name by which an agent is typically known.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctagent_name_type

**Proposed Value**
no changes in values are proposed

**Proposed Definition**

AGENT_NAME_TYPE | Documentation 
-- | -- 
Kew abbr. | A string as published in Brummitt, R.K. & Powell, C.E.  (1992), Authors of Plant Names, Kew: Royal Botanic Gardens, ISBN  978-1-84246-085-6 
aka | Any alternate name string used by the agent. 
birth name | Full name given at birth. 
first name | A personal name, unusually used before the last name.
job title | The agent's current job title.
labels | Used by the reporter function as a way of abbreviating agent  names so that they fit on labels. Example: "CJ Conroy" instead of  "Christopher J. Conroy." This is useful for small labels/boxes. 
last name | A surname or family name. The portion of a person's name that indicates one's family, tribe or community. Practices vary by culture.
login | Exact case-sensitive text string used to log into Arctos. 
middle name | A portion of a name that is written between the person's first name and last name. 
preferred | Name used to uniquely identify the agent in Arctos. Ideally this is the most complete version of a person's or organization's name and/or the name used professionally. This is the name that will be displayed throughout Arctos.

**Priority**
[  Please choose a priority-label to the right.  ]

**Comment by Jegelewicz** [comment]
@ArctosDB/agents-committee and @ArctosDB/arctos-code-table-administrators please review.

**Comment by Jegelewicz** [comment]
Committee says make updates.

**Comment by Jegelewicz** [comment]
@lin-fred do you want to have the Agent committee review at the next meeting?

**Comment by Jegelewicz** [comment]
Updates made.

**Comment by lin-fred** [comment]
No I think it is great.
