### ISSUE TITLE
Feature Request - agent addresses criteria/documentation

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5413]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

I noticed an agent with a google search results address. That's not useful, not stable, and I posit should not be allowed.

**Describe what you're trying to accomplish** 

Require something meaningful as address.

**Describe the solution you'd like**

Cleanup, but mostly better documentation.

**Describe alternatives you've considered**

??

**Additional context**

This probably isn't limited to google search results, that's just what I noticed, the real need is to develop good documentation. (And I'm not sure what that should say - maybe something about 'specific'??)

**Priority**

High-ish? The 4 cruddy addresses aren't hurting much, but the docs should be made better ASAP.

**Data**

```select 
preferred_agent_name,
getPreferredAgentName(created_by_agent_id) as creator,
address
from agent
inner join address on agent.agent_id=address.agent_id
where address ilike '%google.com/url%'
order by address;


               preferred_agent_name               |    creator    |                                                                                                                                    address                                                                                                                                    
--------------------------------------------------+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Washington State Department of Natural Resources | Jessica Tir   | https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiN0-u4jIT8AhXDKEQIHWhxAqcQFnoECAkQAQ&url=https%3A%2F%2Fwww.dnr.wa.gov%2F&usg=AOvVaw3zYfKRFPzkwGYPPKylgG0v
 Jamie Jaegel                                     | unknown       | https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiXocbLusn5AhWjOH0KHUJxCJ8QFnoECA8QAQ&url=https%3A%2F%2Fwww.seattletimes.com%2Fseattle-news%2Fwoman-collects-roadkill-for-beetles-at-burke-museum%2F&usg=AOvVaw3ubmkpkdsMf5o246z578Vv
 Fairbanks Pioneer Home                           | Karinna Gomez | https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwj83bz6ssL7AhUwADQIHYGNCOoQ_Bd6BAhBEAM&url=https%3A%2F%2Fdhss.alaska.gov%2Fdaph%2FPages%2Ffairbanks%2Fdefault.aspx&usg=AOvVaw0rjJXMr_gXN_7MjpCugnAY
 University of South Carolina                     | Jessica Tir   | https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjBw-73oIT8AhVCMEQIHXTlBJ0QFnoECB4QAQ&url=https%3A%2F%2Fsc.edu%2F&usg=AOvVaw2di16gZCJF7GW469RlBb0r
(4 rows)

```

**Comment by Jegelewicz** [comment]
Can we disallow urls containing "https://www.google.com/url?"? I think these are probably just mistakes in copying urls.

**Comment by Jegelewicz** [comment]
Above four are corrected.

**Comment by Jegelewicz** [comment]
I don't think documentation will fix this because I am pretty sure it is just peopl in a hurry copying the search url instead of the one they really wanted.

**Comment by Jegelewicz** [comment]
Thanks @AJLinn for getting the Fairbanks Pioneer Home!

**Comment by dustymc** [comment]
>isallow urls containing "https://www.google.com/url?"? I t

Yes, but there are a LOT of not-very-useful URLs. I can't stop them all, expectations need made clear. This should be recognized as the social problem it is. (And it's [much bigger than addresses](https://github.com/ArctosDB/arctos/issues/4554#issuecomment-1287455870)).

>don't think documentation will fix 

Are you seriously arguing that the [current documentation](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctaddress_type) is adequately defining the kind of data we want?!

``A Uniform Resource Locator (URL), colloquially termed a web address,[1] is a reference to a web resource that specifies its location on a computer network and a mechanism for retrieving it. [Wikipedia](https://en.wikipedia.org/wiki/URL) For example, personal website. Available in public view.``

>people in a hurry

Verbatim agent exists for that. Of course mistakes will be made, expectations should still be clear.

**Comment by Jegelewicz** [comment]
Above are fixed and code table change has been requested. Suggest we close.
