### ISSUE TITLE
New search page - how to select items for removal?

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#5414]
On the old search page we had a column to the left with boxes we could click and then use Tools/Remove Checked Rows to eliminate items we didn't want.

<img width="1318" alt="Screenshot 2022-12-21 at 9 50 22 AM" src="https://user-images.githubusercontent.com/17605945/208981424-7368c413-1bc4-4910-8dfe-530a32be1bab.png">

How do we do the same thing in the new search page with the new results output? 
<img width="2060" alt="Screenshot 2022-12-21 at 9 54 48 AM" src="https://user-images.githubusercontent.com/17605945/208982091-945f3e03-40ae-4810-8fe9-792e6d0b21a4.png">

Same thing on regular search as well as the add to loan search - sometimes I need to cast a wide net and it's easier to eliminate from the search results than to scroll thru the whole group of them in the much harder-to-see Add to Transaction layout.
<img width="2060" alt="Screenshot 2022-12-21 at 9 54 28 AM" src="https://user-images.githubusercontent.com/17605945/208982282-c81e580f-781d-4780-94fc-dc7e99ec3f5d.png">

Did I miss a customized column to add?

**Comment by dustymc** [comment]
>Remove Checked Rows 

It's not there, I was hoping it wasn't necessary, I can try to figure out how to re-add it. Going next task for that.

>harder-to-see Add to Transaction

That's (obviously, I hope) the opposite of the intention (which is to make it much more part-centric with the ability to fully integrate attributes) - how can it be better?

**Comment by AJLinn** [comment]
> That's (obviously, I hope) the opposite of the intention (which is to make it much more part-centric with the ability to fully integrate attributes) - how can it be better?

In general I think it's quite easy to add the parts needed to the loan. If we had the check boxes out front in the add to loan search results, we can refine the item list to what we actually want to add and then once we're in the Add to Transaction view, we can click the boxes to add to the loan. That part is fine.

**Comment by dustymc** [comment]
Next release will have this option. It's called remove_rows, and in both search and results customization the docs will be

>Remove rows; will not work properly unless both remove_row in results and remove_row in search are on. USAGE: Search, click the button to select rows for removal, requery to exclude selected rows.

In action, that looks like this.

Usage:
<img width="171" alt="Screenshot 2023-01-30 at 2 18 49 PM" src="https://user-images.githubusercontent.com/5720791/215608694-6ad299b8-e6bd-4fcd-b1df-41ded8659cd6.png">

<img width="237" alt="Screenshot 2023-01-30 at 2 19 28 PM" src="https://user-images.githubusercontent.com/5720791/215608718-271a9a9a-7f54-453b-89fe-bb1de8553681.png">

<img width="151" alt="Screenshot 2023-01-30 at 2 19 59 PM" src="https://user-images.githubusercontent.com/5720791/215608833-1ba6e2f2-0281-47ef-8a09-3f7413577d14.png">
<img width="527" alt="Screenshot 2023-01-30 at 2 20 13 PM" src="https://user-images.githubusercontent.com/5720791/215608842-73faf28a-6af7-4c80-bd27-df7e17081448.png">

search, get results with remove_row.

<img width="1621" alt="Screenshot 2023-01-30 at 2 23 34 PM" src="https://user-images.githubusercontent.com/5720791/215609716-282d235f-e740-499d-a275-0c2607eb5bc9.png">

Click the button for any number of rows. The value will change

<img width="1633" alt="Screenshot 2023-01-30 at 2 24 14 PM" src="https://user-images.githubusercontent.com/5720791/215609796-94b7d363-6269-447e-8482-f2f53f895ce9.png">

and the ID will be added to remove_rows on the form


<img width="256" alt="Screenshot 2023-01-30 at 2 25 41 PM" src="https://user-images.githubusercontent.com/5720791/215609913-eafe8aae-881a-47aa-bb7d-aa2f2046aea5.png">

requery
<img width="133" alt="Screenshot 2023-01-30 at 2 26 05 PM" src="https://user-images.githubusercontent.com/5720791/215609984-36c341f6-579f-4909-b725-f2e606b8ca06.png">

selected rows will be gone

<img width="1617" alt="Screenshot 2023-01-30 at 2 26 35 PM" src="https://user-images.githubusercontent.com/5720791/215610097-16acbbf2-a905-4e81-b7c7-96fa7eb20e9e.png">

**Comment by AJLinn** [comment]
YAY!

**Comment by dustymc** [comment]
why doesn't this work for @mkoo ?

checkboxes?

**Comment by dustymc** [comment]
when both are on, add a shortcut to tools

**Comment by dustymc** [comment]
Doesn't work in prod because I tried to reuse too much, cleaned and fixed for next release.

See screenshots above, the button does change when clicked (when it works...).

Checkboxes aren't practical because they're not persistent - find something, remove rows, requery works as expected, but further adjusting that query re-adds the removed rows (which are no longer checked for exclusion because they don't exist in that results set). If there's some way around this that doesn't break the flow of the form, I can't find it.

Next release will automagic the necessary search box when results contains remove_row, and documentation will update accordingly.
