### ISSUE TITLE
Code Table Request - Better description of Agent Address url

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5415]
**Goal**
Properly direct users as to what information should go in the Agent address type "url"

**Context**
https://github.com/ArctosDB/arctos/issues/5413#issuecomment-1361699706

Current definition is

Address Type | Definition 
-- | --
[url](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctaddress_type#url) | A Uniform Resource Locator (URL), colloquially termed a web  address,[1] is a reference to a web resource that specifies its location  on a computer network and a mechanism for retrieving it. Wikipedia For example, personal website. Available in public view.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctaddress_type

**Proposed Value**
no new value is proposed

**Proposed Definition**

Address Type | Definition 
-- | --
[url](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctaddress_type#url) | A Uniform Resource Locator (URL), colloquially termed a web address ([Wikipedia](https://en.wikipedia.org/wiki/URL)) that provides information about the Agent. For example a personal website, employer staff page, or a social media profile page. **NOTE** there are special address types for [GitHub](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctaddress_type#github), [Library of Congress](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctaddress_type#library_of_congress), [ORCiD](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctaddress_type#orcid), and [Wikidata](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctaddress_type#wikidata) urls. Please use the appropriate address type. Websites are not guaranteed to persist, please capture specific data (e.g. birth date) in other available fields. Add the most stable or persistent link possible. Available in public view.

**Priority**
[  Please choose a priority-label to the right.  ]

**Comment by dustymc** [comment]
Not sure how but can we say something more about purpose? Maybe 'provides information about the Agent' does??

**Comment by Jegelewicz** [comment]
> Guys,
> 
> Thanks for being in the meeting today - whenever Carla enters the Berkeley Zoom, she becomes the master - so when she left, the meeting ended. Can we agree on [this definition](https://github.com/ArctosDB/arctos/issues/5415) so I can close the issue? Indicate your response there please!
> 
> Adios,

Teresa J. Mayfield-Meyer

**Comment by Jegelewicz** [comment]
Edit complete.

**Comment by ccicero** [comment]
Sorry about that, I didn't realize. Just one very minor tweak:

Because websites are not guaranteed to persist, please capture specific data (e.g. birth date) in other available fields. 

Thanks!
