### ISSUE TITLE
Code Table Request - Datum documentation

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5418]
**Goal**
Add documentation to Datum values

**Context**
Code Table clean up

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctdatum

**Proposed Value**
no new values are proposed

**Proposed Definition**

Help! Are these still useful? When I look around, it seems like [World Geodetic System 1984](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctdatum#world_geodetic_system_1984) is the only useful value. In any case, each of these has a link to "SRID". Do we need more than that to define these? If so, what should be added?

**Priority**
[  Please choose a priority-label to the right.  ]

**Comment by dustymc** [comment]
>Are these still useful? 

Yep, they provide conversion formulae.

>[World Geodetic System 1984](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctdatum#world_geodetic_system_1984) is the only useful value

Not at all, but it's the standard/result of the conversion.

>Do we need more than that to define these? 

Nope, anything else would just be engrishification of math....

>If so, what should be added?

My vote is still mostly for nothing, but that's heavily "we-centric" and if there's something that'll get some user from whatever they're looking at to some Arctos value then that might be spiffy.

**Comment by Jegelewicz** [comment]
How about adding something for this that explains what's going on?

[World Geodetic System 1984](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctdatum#world_geodetic_system_1984) is the standard for Arctos coordinates, all of the other datum terms are used in conversion formulae to this datum when they are provided as the verbatim datum.

and this one

unknown will be converted as if it were [World Geodetic System 1984](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctdatum#world_geodetic_system_1984)

Hack away at what I've written if I don't understand what's really going on!

**Comment by Jegelewicz** [comment]
Also, perhaps we could provide an explanation of what's going on in each of these (in case anybody clicks on one. Maybe something like

This datum reflects the information provided in the linked SRID which is used for conversion to [World Geodetic System 1984](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctdatum#world_geodetic_system_1984) for spatial data in Arctos.

**Comment by Jegelewicz** [comment]
Code Table committee says add above for explanation.

**Comment by Jegelewicz** [comment]
Done.
