### ISSUE TITLE
[CONTACT] Blocked IP

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#5422]
Received from an associate who is accessing Arctos through a US Government network:

"Hi Nicole, Arctos is blocking my IP address again, this time the IP is 172.84.155.85"

**Comment by Jegelewicz** [comment]
I think I've released that IP.

**Comment by Jegelewicz** [comment]
Note that the entire subnet 172.84 is blocked and has been since 2020 - I don't know why though

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks! I'll let him know it should be released.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
This is still blocked.

**Comment by dustymc** [comment]
>still blocked.

Not now, but it'll take about 10mins to clear up.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks!
