### ISSUE TITLE
Agent should no longer be a required field for the single data entry form

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#5424]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

We are now encouraging people to use verbatim agents in attributes instead of agents when they are low-quality, but the data entry form still requires an agent to be entered as collector or preparator etc in order to save.

I recently made a new record this way and in order to save it I had to enter 'unknown' for agent and chose 'preparator' to get around this problem.

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.
medium

**Comment by Jegelewicz** [comment]
I am setting this as next task, because I don't see any reason we shouldn't do it, especially now that we cannot create an agent without some additional information.

**Comment by lin-fred** [comment]
approved by AWG issues

**Comment by Jegelewicz** [comment]
Yes and also everything else that isn't required for reals.

**Comment by dustymc** [comment]
AWG says go, and get other "required" that's not core required while in there.

https://github.com/ArctosDB/arctos/issues/4184

others?

Wishlist for collection-specific "required" is https://github.com/ArctosDB/arctos/issues/4384

**Comment by sharpphyl** [comment]
> AWG says go, and get other "required" that's not core required while in there.

Is there a time frame for removing this requirement?
