### ISSUE TITLE
Code Table Cleanup - use better links in license code tables

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5425]
**Goal**
Use the most authoritative links in the Creative Commons license table

**Context**
The links currently provided in the table take users to the "summary" of the license, which is NOT the legal authority. The current links are http and the proposed links are https. Also, CC licenses can be passed to GBIF, but only the authoritative license title and link are allowed.

For example, collections using the CCO license should record the following in the collection metadata:

```<ulink url="http://creativecommons.org/publicdomain/zero/1.0/legalcode"><citetitle>Public Domain (CC0 1.0)</citetitle></ulink>```

But we currently report

```<ulink url="http://creativecommons.org/publicdomain/zero/1.0/"><citetitle>CC0</citetitle></ulink>```

Note the url and title differences.

I have changed the description for these licenses in the code table to reflect the appropriate titles, but I cannot change the urls as many of these are already being used.

Note that I was able to change these in the [media license](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctmedia_license) table and that the change will make the license information more authoritative.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctdata_license

**Proposed Values**

License | Description | URI
-- | -- | --
CC0 | Public Domain (CC0 1.0) | ~~http://creativecommons.org/publicdomain/zero/1.0/~~ https://creativecommons.org/publicdomain/zero/1.0/legalcode 
CC BY | Attribution 3.0 Unported | ~~http://creativecommons.org/licenses/by/3.0/~~ https://creativecommons.org/licenses/by/3.0/legalcode 
CC BY-SA | Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0) | ~~http://creativecommons.org/licenses/by-sa/3.0/~~ https://creativecommons.org/licenses/by-sa/3.0/legalcode 
CC BY-ND | Attribution-NoDerivs 3.0 Unported (CC BY-ND 3.0) | ~~http://creativecommons.org/licenses/by-nd/3.0~~ https://creativecommons.org/licenses/by-nd/3.0/legalcode 
CC BY-NC | Attribution-NonCommercial 3.0 Unported (CC BY-NC 3.0) | ~~http://creativecommons.org/licenses/by-nc/3.0~~ https://creativecommons.org/licenses/by-nc/3.0/legalcode 
CC BY-NC-SA | Attribution-NonCommercial-ShareAlike 3.0 Unported (CC BY-NC-SA 3.0) | ~~http://creativecommons.org/licenses/by-nc-sa/3.0~~ https://creativecommons.org/licenses/by-nc-sa/3.0/legalcode 
CC BY-NC-ND | Attribution-NonCommercial-NoDerivs 3.0 Unported (CC BY-NC-ND 3.0) | ~~http://creativecommons.org/licenses/by-nc-nd/3.0~~ https://creativecommons.org/licenses/by-nc-nd/3.0/legalcode 

**Proposed Definition**

Definitions have been changed to reflect the actual license titles.

**Priority**
This change will create better metadata files for the IPT - see https://github.com/ArctosDB/arctos/issues/3919 and also link to the most authoritative license information.

**Comment by Jegelewicz** [comment]
Once complete - the EML generator will need to be modified to use the code table description instead of the value in <citetitle></citetitle>

**Comment by dustymc** [comment]
The CC summary exists for humans, and it's mostly humans using it. I cannot support the suggested changes, and strongly recommend the undiscussed changes in other tables be rolled back.

The URL to the legalese is (by design, for just this purpose) predictable; giving GBIF what they want does not necessitate sending humans anywhere complicated and unfamiliar.

**Comment by ewommack** [comment]
Could we include both some how? I know having the easy definition can help when summarizing, but diving deeper into the legal information would make me better informed to speak with the University's legal department when I need to ask for their advice.

**Comment by ewommack** [comment]
Might also be something to think about - would legal definitions be required to be shown if there is a legal question about data, or would a link to the summary information be enough?

**Comment by Jegelewicz** [comment]
> link to the summary information be enough?
I don't think so

The summary information cincludes a disclaimer:

![image](https://user-images.githubusercontent.com/5725767/211633742-33513ee6-d81a-4ee6-b7aa-0eb7f2c46c44.png)

>  Disclaimer
> 
> The Commons Deed is not a legal instrument. It is simply a handy reference for understanding the CC0 Legal Code, a human-readable expression of some of its key terms. Think of it as the user-friendly interface to the CC0 Legal Code beneath. This Deed itself has no legal value, and its contents do not appear in CC0.
> 
> Creative Commons is not a law firm and does not provide legal services. Distributing, displaying, or linking to this Commons Deed does not create an attorney-client relationship.
> 
> Creative Commons has not verified the copyright status of any work to which CC0 has been applied. CC makes no warranties about any work or its copyright status in any jurisdiction, and disclaims all liability for all uses of any work.
>

**Comment by ewommack** [comment]
So it would be better to link to both then I would think. Human readable and legal clarity. 

I wish I understood the law more. @AJLinn - is there recommendation on what to link to when citing copyright controls for cultural collections? I feel you guys have a better handle on the importance of this issue.

**Comment by dustymc** [comment]
@ArctosDB/arctos-code-table-administrators please help - some things were changed, I don't really understand why, now everything's inconsistent. Can I revert and close, do we need more structure, does something need to change, ??????

**Comment by mkoo** [comment]
These links should point to the CC canonical URLs-- please revert as necessary so we arent all over the place!
