### ISSUE TITLE
[CONTACT] URGENT Encumbered locality data on iDigBio

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#5427]
Our encumbered locality data is being shared with iDigBio.

Example:
https://arctos.database.museum/guid/NMMNH:Paleo:70405

Our records now have two iDigBio links. One of the links is to the occurrence with the public data, the other is to a second occurrence with the encumbered locality data.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I've logged into the vertnet IPT and our number of occurrences doubled on the 2022-10-28, that that is probably when this started. Perhaps as a result of changes made in https://github.com/ArctosDB/arctos/issues/5054?

I've verified that GBIF still only has the public data occurances, though I'm not sure how.

@Jegelewicz @dbloom 

Is there something I can do ASAP to get this data pulled down from idigbio until this can be fixed?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Email has been sent to iDigBio to remove our dataset.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Fixed on Arctos end. Waiting for iDigBio to update.

**Comment by dbloom** [comment]
iDigBio was notified that they can re-harvest the dataset with corrections. @Nicole-Ridgwell-NMMNHS @Jegelewicz This process can take days or weeks. If you have not seen a change in your data at iDigBio by Feb 1, let me know and I will follow up.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
The data is now completely down from iDigBio. Thanks Everyone!
