### ISSUE TITLE
Feature Request - can we please get rid of the dotted lines?

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#5428]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

The locality search form is giving my eyes spasms - it's a user interface nightmare

https://arctos.database.museum/place.cfm?sch=locality

can we please remove the dotted lines (make them solid)? They make it far harder to find what one is looking for.

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.
medium

**Comment by DerekSikes** [comment]
These dotted lines continue to freak me out. I can't believe I'm unusual in this respect. How hard is it to remove them? / replace with non-dotted lines? And if these are on the collection event search form they should be replaced/removed there too.

**Comment by dustymc** [comment]
FYI my intention is to restyle that to look like https://arctos.database.museum/search.cfm whenever those conversations stabilize (which was all supposed to be worked out in https://github.com/ArctosDB/arctos/issues/2916 and friends but here we are...).

**Comment by dustymc** [comment]
and move the type-changer-thing buttons somewhere else, or something
