### ISSUE TITLE
Contact - Island not available

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5429]
> Good morning,
> 
> I am an educator that uses Arctos as a source for our online laboratory activities. The activity requires students to download data for 'weight' and 'island'. When attempting to download this data again using the new form, I cannot seem to get the 'island' tag to return any results regardless where I define my search. I attempted to download data with the legacy form and this data is still not included properly as it had been before. Previously, this tag would return either no data for a given specimen or the name of the island it was collected from. 
> 
> How can I get these data to return these results appropriately?

-Wil Falkner

**Comment by sharpphyl** [comment]
From  [#5138](https://github.com/ArctosDB/arctos/issues/5138)
> No, Islands will not be assertable geography, but island data will be converted to features, and will work precisely like the Yosemite example above.

I don't find our islands in Features, but I do find most of them by search in the  Specific Locality field.

**Comment by ewommack** [comment]
So @sharpphyl - you would recommend the searching for the full island name in "Specific Locality" will find some of the info?
Is that because you did not switch over the islands to features yet? Just trying to understand how the new search fields might work.

**Comment by sharpphyl** [comment]
I just checked several of our records that used to be in Islands (or Island Groups) and found the data in Specific Locality.  I'm not aware that I'm able to switch the islands to features and don't know why that would be of any value.  So, yes, I would search for the island name (the same as what you entered in Island field in the past) in Specific Locality.

**Comment by dustymc** [comment]
Yes, @sharpphyl is correct, islands - like all other not-geography - should be asserted via specific locality.

Islands (those for which we could locate spatial data) were retained as FFFs, you can list them here: https://arctos.database.museum/place.cfm?sch=geog&island=_&valid_catalog_term_fg=0

They - like all geography, assertable or otherwise - can be used for record discovery via "Geography Shape Name" or Place Terms. Place Terms is probably most appropriate and is certainly the simplest.

Both are resource limited (https://github.com/ArctosDB/internal/issues/222), and both could be added to results (via dedicated Issue - they're not simple/flat data, discussion would be required).

**Comment by sharpphyl** [comment]
Now I'm confused.  What is an FFF?  

I looked at the list of islands and we have lots of specimens from many of them.  On the details of several it says that they cannot be used for cataloguing, e.g. https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10019848.  Is that true of the entire list?

Is there something we're supposed to do with catalog records from islands on this list, or are they only used to find catalog records or assign spatial data to our records.   Since the island isn't in Geography, is the spatial data based on Specific Locality?   Anything else about how islands and island groups now function that we should understand for data entry, geolocation and search?

**Comment by Jegelewicz** [comment]
> Anything else about how islands and island groups now function that we should understand for data entry, geolocation and search?

We need to update documentation and I don't think I can do that as I am not 100% certain how these things work right now.

**Comment by Jegelewicz** [comment]
@dustymc @sharpphyl can we work together to clean up this? - https://handbook.arctosdb.org/documentation/higher-geography.html

1. Are we using IHO World Seas? If so, how?
2. Can I proceed with deleting everything below "Suggest removing everything below (although some might beuseful for eventual locality attributes?"?
3. Can we rename "Unassertable Higher Geography" to "Flexible and Fun Features" AND can we provide information on requesting new ones and how these WORK in search?

**Comment by dustymc** [comment]
>Are we using IHO World Seas? 

It's listed on https://handbook.arctosdb.org/documentation/higher-geography.html so yes. We're using it exactly like all assertable geography, not sure what you're asking?


>deleting everything below 

No, some of it needs updated - primarily the guidelines, which can't be addressed until https://github.com/ArctosDB/arctos/issues/5417 is.

>rename "Unassertable Higher Geography"

Not from here.

>provide information on requesting new ones

Not until https://github.com/ArctosDB/internal/issues/222 is addressed. (As a measure of my current level of desperation, I'm tempted to nuke what's there to see if it helps.)

>how these WORK

Maybe a good subject for a locality meeting? I can't quite understand what's confusing, I guess I need more background or something.

**Comment by Jegelewicz** [comment]
> not sure what you're asking

Everything in IHO World Seas can be used as assertable geography in Arctos? If so, has it all been added already? I think letting users know the status or how they could ask for new things (if needed) would be helpful.

**Comment by Jegelewicz** [comment]
So, "Unassertable Higher Geography" is NOT Fun, Flexible, Features? What they hell are they then! I am just not getting something about FFF.

Also, when someone has something that has no information but "North America", what do they do? Put that in spec_loc and use no higher geography recorded?

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/5155

https://github.com/ArctosDB/arctos/issues/new?assignees=&labels=&template=geography-request.md&title=%5B+geography+request+%5D

As far as I know everything has been announced and discussed and is in the expected place.

**Comment by Jegelewicz** [comment]
> Not until https://github.com/ArctosDB/internal/issues/222 is addressed.

Does this need a "Potential Wildfire" label? Nobody is going to pay attention right now because there are no labels or committees assigned.

**Comment by dustymc** [comment]
I think this needs to go to a meeting or something, anything that develops here is also going to be lost from here.

If I put it in /internal it generally already looks like a wildfire or worse to me.

**Comment by Jegelewicz** [comment]
The [example in the documentation for island](https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=1005324) gets me this

![image](https://user-images.githubusercontent.com/5725767/212745820-bb750c2c-39ff-43ff-a234-77c81d235ec9.png)

**Comment by Jegelewicz** [comment]
Same for parks - https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10004785

Can we get new examples and be sure they will work?

**Comment by sharpphyl** [comment]
> Also, when someone has something that has no information but "North America", what do they do? Put that in spec_loc and use no higher geography recorded?

We have the same issue with specimens from the Atlantic and Pacific Oceans as well as continents such as Africa that show "no specific higher geography" as the geography.  I understand "the plan" sets up this construct, but it seems our GADM and IHO only rules are devaluing some significant geography.

**Comment by sharpphyl** [comment]
Back to the original question.  If we no longer use Island and Island Group, shouldn't those fields be eliminated from "customize results" the same way they have been eliminated from "customize search."  

<img width="626" alt="Screenshot 2023-01-18 at 8 07 10 AM" src="https://user-images.githubusercontent.com/15368365/213207916-4922af96-abb2-4527-80cd-e161e5661dd0.png">

The only islands that I've found are in Madagascar which may just be a holdover until we update that country per GADM.

**Comment by dustymc** [comment]
>fields be eliminated from "customize results"

https://github.com/ArctosDB/arctos/issues/5429#issuecomment-1372324497, IDK, hoping I'll get some direction!

>Madagascar

https://github.com/ArctosDB/arctos/issues/5185

**Comment by dustymc** [comment]
I'm recategorizing this, I don't think it's a documentation issue (and don't know what else it is or what might be done about that)

Option One: Point everyone at Any Geographic Element, it'll find data wherever it exists. Maybe relabel everything else as 'curatorial' or something.
Option Two: Do something clever with https://github.com/ArctosDB/arctos/discussions/7666

**Comment by mkoo** [comment]
Closing: Stale issue and original issue has been addressed. Obsolete with introduction of locality attributes and current discussion about islands and geography shapes
