### ISSUE TITLE
Older Loans and Accessions Results Not in Order

### ISSUE THREAD

**Issue by KyndallH** [ArctosDB/arctos#5430]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
For some reason, older loans and accession results are not sorted in order. Newer transactions are not having the same problem.

<img width="411" alt="Screen Shot 2023-01-03 at 11 45 18 AM" src="https://user-images.githubusercontent.com/16887896/210439452-e55d1b48-f17f-490b-aba1-ce0fef843507.png">

<img width="522" alt="Screen Shot 2023-01-03 at 11 48 32 AM" src="https://user-images.githubusercontent.com/16887896/210439459-b2b4d305-d806-4565-a549-1fcb0ba08daa.png">

<img width="406" alt="Screen Shot 2023-01-03 at 11 48 57 AM" src="https://user-images.githubusercontent.com/16887896/210439464-91f404e0-001b-4cb6-ac01-0084cf979174.png">

<img width="274" alt="Screen Shot 2023-01-03 at 11 49 29 AM" src="https://user-images.githubusercontent.com/16887896/210439470-aed1d661-2288-4674-99c2-4b6febefd984.png">

**To Reproduce**
1. Manage Data --> Transactions --> Find Transactions
2. Enter Search Criteria: for example: loan, UAM:Mamm, 2003
3. Hit "Search"
4. Scroll down to see that results are not in order:

<img width="348" alt="Screen Shot 2023-01-03 at 11 55 05 AM" src="https://user-images.githubusercontent.com/16887896/210439966-cc0b9865-e6f5-483b-8445-0eefd8b0c29a.png">

**Expected behavior**
UAM:Mamm 2003.029 should go AFTER UAM:Mamm 2003.009.Mamm

**Screenshots**
See above.

**Data**
N/A

**Desktop (please complete the following information):**
 - OS: macOS version 12.5.1 iMac
 - Browser Chrome 
 - Version 108.0.5359.124 (Official Build) (x86_64) [is up-to-date]

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.
Slightly above black hole of despair. In Green hole of despair.

**Comment by KyndallH** [comment]
Angie and I talked. I guess you can set it on the search transaction page how you want your results and it appears that it sorts by enter date as default.
Angie and I agreed on two points (and I think others would agree):
1. Default sort should be the Loan number.
2. On the results page, you should have the option to change how the results page is sorted - that is where I looked to change how my results were sorted, not on the search page.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I agree, the sorting is confusing.

**Comment by dustymc** [comment]
>Default sort should be the Loan number.

I removed the 'whatever/NULL' options and set the defaults to 'numbers.'

>results page, you should have the option 

That's not very compatible with that tech stack - fine-tuning (in any way) would require a full rebuild of some sort.
