### ISSUE TITLE
Arctos Down - Unplanned 3 Jan 2023

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#5432]
Please complete to the best of your ability.

## Unplanned Outage
 - Arctos has been working fine all day but now it's not responding. It went down around 3:30pm Pacific on 3 Jan 2023.
 - None of Arctos is responding. I also checked with Carol and she's having the same issue.

## Communication before/during outage
- [ ] Pin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG  
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by ccicero** [comment]
It is back up now. So maybe all is ok? Will keep this open until I'm done with what I'm doing, then will close if no more issues.

**Comment by ewommack** [comment]
Works for me.

**Comment by Jegelewicz** [comment]
It is working for me

**Comment by mkoo** [comment]
Are both you and Carol at work? maybe a network issue?
works fine from the island ....

**Comment by AJLinn** [comment]
I'm having intermittent problems as well... hard time logging in; media files not loading from the catalog record page. Maybe connected, maybe not?

**Comment by AJLinn** [comment]
> media files not loading from the catalog record page

Of course as soon as I add that comment, the files upload just fine! 😵‍💫
