### ISSUE TITLE
New user password reset, and account clarification

### ISSUE THREAD

**Issue by genevieve-anderegg** [ArctosDB/arctos#5433]
We have a new volunteer in DMNS Marine Invertebrate Collection, "bbaer_dmns". He cannot log in and cannot remember his password; could I have it reset and sent to his email?
Interestingly, there are (somehow) two accounts with the same username, both linked to his email address (picture below). Could we get the password reset for the account that also has a Role and is associated with "DMNS Marine Invertebrates" instead of just "DMNS" (bottom account in the picture), and get the account deleted that is not associated with Marine Inverts and has no roles (top in the picture). 
![image](https://user-images.githubusercontent.com/83782023/210477099-884fe05e-4227-4dd4-815b-757e437c1ef8.png)

Thank you so much!

**Comment by sharpphyl** [comment]
Bryan has requested a new password and when he logs in with the password (copy/paste) it rejects the password and says that he has "insufficient privileges."  We can't find any errors in his login or password, so something is hung up in the system.

**Comment by sharpphyl** [comment]
OK, we were able to finally get him in and assign roles.  Thanks for doing whatever needed to be done!

**Comment by Jegelewicz** [comment]
I don't think anybody did anything! But if he still has two user accounts with exactly the same user name, that needs fixing - I just don't know how to fix it.

**Comment by dustymc** [comment]
I deleted ``space-or-tab-or-whatever-it-was-bbaer_dmns``
