### ISSUE TITLE
Add British Indian Ocean Territory and Christmas Island to geography

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#5434]
Attached is csv with required data.  We have catalog records that would use these geographies.

[BIOT and Christmas Island.csv](https://github.com/ArctosDB/arctos/files/10344597/BIOT.and.Christmas.Island.csv)

**Comment by dustymc** [comment]
Done:

[BIOT.and.Christmas.Island.csv.zip](https://github.com/ArctosDB/arctos/files/10353448/BIOT.and.Christmas.Island.csv.zip)

In the future, please use the [request template](https://github.com/ArctosDB/arctos/issues/new?assignees=&labels=&template=geography-request.md&title=%5B+geography+request+%5D).
