### ISSUE TITLE
Odd behavior since new search form implemented

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5436]
Ever since the new search form was implemented, I keep experiencing the same odd behavior from other pages of Arctos. When I try to do anything else directly from the menu, Arctos does not respond unless I am at the new search page. So, if I am editing Agents and then use the menu to go do anything else besides search, Arctos just spins (sometimes even when I select search). I can go to the search page first, then select whatever I want and it works just fine. Occasionally, I have to just close whatever Arctos tabs I have open and then enter https://arctos.database.museum in my browser to get everything working again.

Also, whenever I log in, I no longer get the "you have manage collection" list. Instead, it seems like nothing has happened, but if I refresh, I can see that I am now logged in.

Is anyone else experiencing these things?

Firefox Version 108.0.1 (64-bit)

**Comment by Jegelewicz** [comment]
Also, when working on agents, if I am away from the form for an extended period of time and come back to search a new name, Arctos will spin and never return anything. When I select Search from the menu, I get this.
<img width="960" alt="Screenshot 2023-01-04 15 30 48" src="https://user-images.githubusercontent.com/5725767/210662613-ce9a8c6e-e2e0-40c7-b4f8-39c44092f993.png">

**Comment by dustymc** [comment]
not related, https://github.com/ArctosDB/internal/issues/187
