### ISSUE TITLE
Unable to log in or get password reset

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#5437]
No problems with login this morning but this afternoon my password is rejected and when I request one be sent to my mailbox, nothing comes through.

Can you reset the account and password?

login:  sharpphyl
email: sharpphyl@gmail.com

![Capture](https://user-images.githubusercontent.com/15368365/210664017-1eaf24dd-2c0e-4288-9c8f-41c3c9fd7e4f.PNG)

Chrome/PC

**Comment by Jegelewicz** [comment]
@sharpphyl I just sent you an email

**Comment by Jegelewicz** [comment]
Do we need to reopen https://github.com/ArctosDB/arctos/issues/4767 ?

This is the second one of these I've had to do today.

**Comment by sharpphyl** [comment]
I still can't login even with the password I got in your email.  And, yes, I was not getting the emails with the passwords all day.

**Comment by Jegelewicz** [comment]
OK - l've just reset the account. When you log in it will probably fail, but request a password change, then let me know and I'll email you whatever Arctos produces.

**Comment by sharpphyl** [comment]
That's what I needed.  I'm in.  Thanks!!
