### ISSUE TITLE
Don't display "entered by" as an agent role option in transactions

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5439]
> I guess the thing that confused me is that that role is available on the list of roles as one that can be entered in an upload but it is not in fact something you can enter, at least for accessions. Maybe somewhere else? If not, then could it be masked in the code table or labeled as something that is only machine entered?

_Originally posted by @barke042 in https://github.com/ArctosDB/data-migration/issues/1144#issuecomment-1372384650_

Because this role is automatically assigned, it cannot be entered either through any of the transaction bulkload tools or manually. Can we mask this option in those places or highlight it in the code table as not assignable by people?

**Comment by barke042** [comment]
Here is the current text in trans_agent_role:
entered by [ link ] | Automatically populated with login information.

Could we just add: "Do not assign this value in bulk uploads."?

**Comment by Jegelewicz** [comment]
@ArctosDB/arctos-code-table-administrators any objections?

**Comment by Jegelewicz** [comment]
Just add it. Also make it clear that this is the agent who entered or loaded the accession into Arctos.
