### ISSUE TITLE
New taxonomy source

### ISSUE THREAD

**Issue by byuherpetology** [ArctosDB/arctos#5440]
**Goal**
I would like to create a new taxonomy source. 

**Context**
I would like to use my own taxonomy for amphibians for our collections. Current Arctos amphibian classification is out of date and making a new source seems to be the most efficient way to update. I have taxonomy in the hierarchical editor now. If I can do this myself, just point me in the right direction, I couldn't find a way to do it.

**Table**
(https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxonomy_source)

**Proposed Value**
Source: Current Amphibian classification
Documentation: Extant amphibian taxonomy, intended to reflect current literature. Managed in the Arctos Hierarchical Taxonomy Editor by [Alison Whiting](https://arctos.database.museum/agent/21320583) (@byuherpetology on GitHub); please preemptively coordinate any changes or additions. Changes made by other editors are subject to replacement without notice.

**Priority**
normal

**Comment by dustymc** [comment]
I'm proceeding under the assumption that classification sources do not require discussion, but I'll clean up whatever mess I just made if @ArctosDB/arctos-code-table-administrators think differently.

I did change case - "Current Amphibian Classification" - to match https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxonomy_source#current_reptile_classification
