### ISSUE TITLE
Code Table Request - Add Glorieta Sandstone Formation

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#5441]
**Goal**
Add Glorieta Sandstone Formation to the lithostratigraphic formation code table.

**Context**
I need this value for a locality.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlithostratigraphic_formation

**Proposed Value**
Glorieta Sandstone Formation

**Proposed Definition**
A Permian unit that outcrops in central New Mexico. [Geolex](https://ngmdb.usgs.gov/Geolex/Units/Glorieta_8383.html)

I will add this tomorrow if there are no objections.

**Comment by Jegelewicz** [comment]
No objection from me.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Added
