### ISSUE TITLE
Feature Request - Finding Endangered/Threatened Species

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#5444]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
1. Create a better way to find specimens associated with Arctos Legal.
2. Determine if there is a better resource than Species+ to pull information about endangered/threatened

**Describe what you're trying to accomplish** 
Each year, we need to pull information about endangered/threatened species in our collections to report for state/federal levels for permits. The current method is clunky and pulls data from an unstable website.

**Describe the solution you'd like**
1. A report, a code table, an attribute, a downloadable csv -- something that makes it easier to find this data within Arctos.
- Under "Tools", there is an option called "Check Arctos Legal (taxonomy)"; would it be possible to only pull the taxonomy/catalog numbers for catalog records that have this information, as opposed to a bunch of blanks? And have a download option?

2. A way to see all species that have "Arctos Legal" associated with their name (from the issues meeting--I think it would appear under source here?).
![image](https://user-images.githubusercontent.com/93737929/210885796-82b85ad3-dfa6-45b8-9597-f9ca0166bafe.png)

**Describe alternatives you've considered**
Searching individual taxon names based on a list from CITES, US Fish and Wildlife, each state.

**Additional context**
Related discussions and issues:
- https://github.com/ArctosDB/arctos/discussions/4891
- https://github.com/ArctosDB/arctos/issues/4935
- https://github.com/ArctosDB/arctos/issues/4763

Discussed during Issues Meeting on January 5 (see agenda notes); determined that we need to put together a task force to discuss. Taxonomy will discuss at their next meeting on January 12.

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by wellerjes** [comment]
US Fish and Wildlife Services has an option to do a csv download of the species considered threatened/endangered. Could we us the information from these csv downloads to help jump-start the process? Here's the search page: https://ecos.fws.gov/ecp0/reports/ad-hoc-species-report-input

I'm envisioning a way to add this to the taxonomy records / code table like this:
![image](https://user-images.githubusercontent.com/93737929/210891206-131e7c17-25f5-4828-9744-3efcd8dd8dac.png)
- Add term type: "conservation status" with terms endangered and threatened
- Add term type: "where listed" with the terms: US State or US Federal (to start with)
- Add term types: "conservation_source_authority" and "conservation_remark", which would function like the taxonomy source and remark to document what source as used (USFWS, IUCN Redlist, etc.)
Adding these terms would allow users to know when the status was last check and what source was used -- US Fish and Wildlife Services isn't going to address foreign species, so any species collected outside of the US is going to require double-checking.

This information would then populate on the taxonomy page under info:
![image](https://user-images.githubusercontent.com/93737929/210892538-a3182294-0a49-4b6e-887f-1c98a86b0ca7.png)

Thoughts?

**Comment by dustymc** [comment]
>-I think it would appear under source here?).

I'm just going to do something, add a 'managed' column to the code table or something. (Which might be a roundabout way of implementing https://github.com/ArctosDB/arctos/discussions/4965...) Going next task for that, I'm not sure it's tied to the rest anyway.

>something

I can't work from that, nor from "this sucks." I need to know what you're trying to do in at least enough detail to get it started, and more is always better. https://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

I'm not sure I completely understand where you're coming from or where you're going, but lacking better ideas (hopefully not for long) I'll recommend this be done as a report - I think it's well within the capabilities of the current reporter, easy to change or clone/adapt or etc., and takes minimal development to get started.

>Could we us the information from these csv downloads

Yes, that's the core idea behind the model.

https://handbook.arctosdb.org/documentation/taxonomy.html

You can start that by requesting a new [source](https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxonomy_source), the classification loader should be more than capable of handling whatever's behind that URL.

**Comment by wellerjes** [comment]
Another thought I just had--instead of tying it taxonomy, we could create a new attribute/code table. That way each collection could tie it to the record based on the source they use, since it varies state by state and internationally.

Example: https://arctos.database.museum/guid/CHAS:Herb:2021.6.1956
[IUCN](https://www.iucnredlist.org/species/135952711/135956142) lists _Halesia carolina_ as least concern, but I want it to be flagged as endangered because we have to report it to IDNR--it's considered [endangered plant in Illinois](https://www2.illinois.gov/dnr/ESPB/Documents/ET%20List%20Review%20and%20Revision/IllinoisEndangeredandThreatenedSpecies.pdf). Rather than having all the different sources in the taxonomy that differ based on your location/collecting localities, an attribute is tied directly to the catalog page with the source connected (IUCN, state, federal, etc.).

For the Code Table:
- Attribute: Conservation Status
- Values: use the [IUCN Red List for values and definitions](https://en.wikipedia.org/wiki/Conservation_status#IUCN_Red_List_of_Threatened_Species); also add "threatened", which encompasses critically endangered, endangered, and vulnerable. Having each of these in the code table allows us to add an attribute if the species is taken off an endangered/threatened species list.
- Method: The source that we are using to base the conservation status on (are we able to make the method field required for an attribute?)

As long as we can download attributes from the search page, I would be happy with this solution.

**Comment by Jegelewicz** [comment]
@wellerjes send me the list of IDNR endangered stuff. I'll set something up in test and we can decide if it works for you.

**Comment by wellerjes** [comment]
Thank you @Jegelewicz!!

Here's a csv for the IDNR endangered and threatened species list.
[IDNR Endangered-Threatened List 2020.csv](https://github.com/ArctosDB/arctos/files/10418517/IDNR.Endangered-Threatened.List.2020.csv)

Here's the original as a PDF
[IDNR_IL-stateTEspecies-2020.pdf](https://github.com/ArctosDB/arctos/files/10418518/IDNR_IL-stateTEspecies-2020.pdf)

**Comment by dustymc** [comment]
I don't really object to the attribute, but it's a very roundabout way of getting where I think you want to be (which inevitably results in inconsistent output) and I would like that added to the documentation if the attribute is created.

If you want to just add that CSV as a source I can help you query against it. (But maybe drop 'type', or at least the implicit assertion that only birds lay identifiable eggs...)

**Comment by Jegelewicz** [comment]
> just add that CSV as a source

This is what I plan to do.

**Comment by Jegelewicz** [comment]
Setting this up in test and noticed a few things

1. Arctostaphylos uva-ursi exists in Arctos but doesn't match with Arctostaphylos uva-ursi in the file. I'm guessing the dash is causing problems?
2. I am forced to add terms to the [code table](https://arctos-test.tacc.utexas.edu/info/ctDocumentation.cfm?table=cttaxon_term) for no-class stuff. I thought this was not necessary since we now just import whatever from wherever and we can't use those terms in searches?
3. the no-class terms MUST be lowercase, which makes for weird terms (idnr status and idnr common name as opposed to IDNR status and IDNR common name).

**Comment by Jegelewicz** [comment]
This search yields results when I am logged in to test - https://arctos-test.tacc.utexas.edu/search.cfm?tax_trm_1=endangered&tax_rnk_1=idnr%20status&tax_src_1=IDNR%20List

![image](https://user-images.githubusercontent.com/5725767/219206708-63713fa6-b6df-4836-a283-3994bd2c37e2.png)

even more when not logged in as expected

![image](https://user-images.githubusercontent.com/5725767/219206978-fcd45885-8030-4996-a955-9de144da3b86.png)

@wellerjes try using that url when you are logged in to test and let me know if this is what you need. You can also see how this would work for common names

https://arctos-test.tacc.utexas.edu/search.cfm?tax_trm_1=%25&tax_rnk_1=idnr%20common%20name&tax_src_1=IDNR%20List

We would just need to set up a source for the ones that you specifically want to use. This will work for search and reports, but those specific common names won't show up on your catalog records.

**Comment by Jegelewicz** [comment]
Other notes to self:

If we add this to production, we need a source for all the classifications (with timestamp) so it can be updated as needed.

**Comment by Jegelewicz** [comment]
@wellerjes have you tried checking this out in test? The data may be overwritten soon and this will disappear into the ether requiring me to do it all again if you are still interested.

**Comment by Jegelewicz** [comment]
Your account in test should be the same as your account in production. I just unlocked and reset it, so look for an email from test and try again.

**Comment by wellerjes** [comment]
Thanks! I like how this works in the search. What would be involved in keeping this updated?

**Comment by dustymc** [comment]
Classification-stuff (just CHAS classification-stuff?? Probably not...) needs a unified Issue, there are a bunch of little bits and pieces of similar (the same?? I don't know...) issues floating around, and how things  should be managed will 100% depend on WHY they need managed in the first place. Probably without worrying about how the Arctos model does or does not work (that seems to mostly be a distraction?), can someone put together some sort of cohesive picture of how this and https://github.com/ArctosDB/arctos/issues/6731 and https://github.com/ArctosDB/arctos/issues/6644 and whatever I'm missing might ideally function?

**Comment by Jegelewicz** [comment]
> What would be involved in keeping this updated?

Downloading, formatting for Arctos taxonomy and uploading to the source.

I don't know the schedule of updated that IDNR makes - so updating Arctos may or may not depend on that - totally up to you. You could set a reminder and just update it once a year, or you could do an update any time you really need to know current information. It is pretty easy to do and I could write up some instructions if you want to maintain the source.

> needs a unified Issue

I don't think this does - this source is just a way to mark IDNR status (an extension of Arctos Legal in a way), the common name thing is just something extra that doesn't matter now that #6644 has been closed and this has absolutely nothing to do with #6731

**Comment by wellerjes** [comment]
Thanks! The IDNR list isn't updated every year (we're currently working with the version from 2020), so upkeep shouldn't be difficult.

**Comment by Jegelewicz** [comment]
OK - I am going to assign myself to upload it to production and I will add both of us as "managed by".

**Comment by Jegelewicz** [comment]
Closing this in favor of the code table request.
