### ISSUE TITLE
See all collection objects in this container: return results 1000 but wanted bumped up to 1450

### ISSUE THREAD

**Issue by KyndallH** [ArctosDB/arctos#5446]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
When viewing samples in a freezer rack, I can only do 1000, but my max tissue in a rack is 1400. Since it doesn't return all 1000, I have to go down to the next lower unit, which is 100. Ugh. I want to modify parts in larger batches ==> faster Kyndall.

**Describe what you're trying to accomplish** 
Return results boosted from 1000 to 1450 (while the max of my racks are 1400 tissues, sometimes there is a @#$@#, and I end up with phantom tissues in a box that I need to address.)

**Describe the solution you'd like**
see above

**Describe alternatives you've considered**
Doing box by box (100 tissues) instead of at the rack (1400 tissues) level. That = a lot more work.

**Additional context**
<img width="459" alt="Screen Shot 2023-01-05 at 1 40 59 PM" src="https://user-images.githubusercontent.com/16887896/210894669-c11be15f-0c1e-4351-aafe-40db4ce91b13.png">

<img width="604" alt="Screen Shot 2023-01-05 at 1 41 10 PM" src="https://user-images.githubusercontent.com/16887896/210894692-40c8f0bd-12ef-47cd-8d67-b2ba1493e9ec.png">

<img width="400" alt="Screen Shot 2023-01-05 at 1 41 14 PM" src="https://user-images.githubusercontent.com/16887896/210894704-fd9b07db-10e3-47ed-b331-43f193ecbfaf.png">

Pretty please!

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by KyndallH** [comment]
I do need this for work, but not sure if I'd consider it priority-high for anyone but me.

**Comment by campmlc** [comment]
More is better for me too, given I have containers with 72K objects, and
that's a lot of downloads 1000 at a time.

**Comment by campmlc** [comment]
Any way to customize?

**Comment by KyndallH** [comment]
I thought there was a limit due to the spinning wheel of death or something. I figured going up 450 wouldn't kill it, and that is all I really need (or so I think). Granted, being able to view ALL collection objects in a cryovat would be nice.

I like the idea of customizing based on what you are trying to download, but I don't know how challenging that would be.

**Comment by dustymc** [comment]
>customize

This is resource limited, and one (the??) failure mode is running the VM out of memory and bringing Arctos down. I'm sure I've mentioned that before and I might push the issue, but the second limitation is your network-or-something (remember this - or some similar form - magically working during some meeting when you weren't in your usual environment?) so I don't think you could make use of much more anyway.

I don't think bumping to 1500-ish is going to be fatal to Arctos so there is (I hope) an easy solution to the described problem, but much beyond that needs some sort of nontrivial something-or-another.

**Comment by campmlc** [comment]
Can you describe what resources are needed? I'd like to flag all issues
that are resource limited so we can start to think about our long term
needs.
