### ISSUE TITLE
Subject the collector role and subject the attribute are causing issues

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5448]
>add subject to the search results, nothing shows up.

Neato! Let's call this a failure of the code table committee. This...

<img width="1403" alt="Screenshot 2023-01-05 at 3 53 54 PM" src="https://user-images.githubusercontent.com/5720791/210902075-c44ef8ad-ff47-41cd-b4c5-6a7cb8c11849.png">

.... is mapped to https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcollector_role#subject (as suggested by the documentation), not https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#subject. That's (obviously) not a technical problem, but it was sufficient to confuse at least one of us....

Actually, this...

<img width="193" alt="Screenshot 2023-01-05 at 3 52 04 PM" src="https://user-images.githubusercontent.com/5720791/210901889-e6f0dcc9-d3d1-4bb8-94aa-18330f1edf4d.png">

is mapped to the attribute so maybe I just confused myself twice and everybody else is immune. Still, can we somehow make this a bit less confusing?

_Originally posted by @dustymc in https://github.com/ArctosDB/arctos/issues/2362#issuecomment-1372943909_

**Comment by Jegelewicz** [comment]
OOOOH I see how it is confusing, but I am not sure what needs to be done? I mean, they are the same word, but Subject is the collector agent role and subject is the attribute. Can we use both and rely on the definitions (although clearly I didn't read it when I made my selection!). Because right now "subject" the attribute does not appear in the customization list, but all the other attributes do.....

**Comment by Jegelewicz** [comment]
>> Can we use both
> 
> Not in the same context - we can have at most one search term and one results column with any given name. I think the only real path out involves renaming at least one of these things, and 'subject' is a super-common word that means all kinds of things in various languages and dialects so I vote for renaming both.
> 
> "subject" is a dedicated search term and flat column by request, so there should be some priority in sorting this out, and I think at least one of those things will need rebuilt.

**Comment by Jegelewicz** [comment]
@AJLinn @sjshirar @krgomez thoughts?

[subject collector role](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcollector_role#subject)
[subject attribute](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#subject)

**Comment by krgomez** [comment]
Well, we need to keep both, but I'm not sure what to rename either one if that's what's needed. Subject is the right term for both things. We need to be able to search subject terms (attribute) but I do not want it to appear in the default search results. It's not something we need to see there. We also wouldn't need to see the subject agent role in the results, but we should be able to search it like the other agent roles.

**Comment by dustymc** [comment]
>subject terms

Works for me....

>something we need to see there

I apparently confused myself somewhere on https://github.com/ArctosDB/arctos/issues/5341, can you be precise (here or there) on what you want where?

**Comment by Jegelewicz** [comment]
To be clear - I was customizing my search results and wanted to add the subject attribute to help me fix the duplicate children's art stuff. I was not able to do it because that attribute is not available (although all the others are as far as I can tell) in the customize form.

**Comment by krgomez** [comment]
> I apparently confused myself somewhere on https://github.com/ArctosDB/arctos/issues/5341, can you be precise (here or there) on what you want where?

In the search results, the ideal columns to see for an art collection are: GUID, media, identification (title), creator, verbatim date (creation event), specific locality (though not totally necessary), and taxon (object/work type). For taxon it would be nice if it was just the specific work type (for example, watercolor) as opposed to the full taxon name, and it's also something that we could go without.

We could possibly change _subject_ to _subject matter_ for the attribute. See https://www.getty.edu/research/publications/electronic_publications/cdwa/18subject.html

**Comment by krgomez** [comment]
Also, I think you had said that the subject attribute would appear in the custom search options, but it's still not there. The way the search fields are right now is great, except that subject is missing.

**Comment by Jegelewicz** [comment]
> We could possibly change subject to subject matter for the attribute. See https://www.getty.edu/research/publications/electronic_publications/cdwa/18subject.html

@krgomez my plan is to do this so that we can have both subject (the role) and subject matter (the attribute) in search results. The fact that they are currently the same term means we can only have one or the other. I hope to get this done today!

**Comment by Jegelewicz** [comment]
subject matter attribute has been added and subject attributes are being unloaded.
[attributeDataDownload(2).csv](https://github.com/ArctosDB/arctos/files/10394463/attributeDataDownload.2.csv)

**Comment by Jegelewicz** [comment]
subject matter attributes loading.
[attributeDataDownload(2).csv](https://github.com/ArctosDB/arctos/files/10397262/attributeDataDownload.2.csv)

**Comment by Jegelewicz** [comment]
subject matter attributes loaded.
[Uploading attributeDataDownload(2).csv…]()

**Comment by krgomez** [comment]
We may as well remove the keywords attribute too, unless this has value for other collections. UAM:Art doesn't use the keywords attribute, as it was originally intended as a place for subject terms, which of course we are now using the subject matter attribute for.

**Comment by Jegelewicz** [comment]
@krgomez please discontinue the use of subject - a record was entered with it today and I can't get rid of the term from the code table until it is no longer used. @dustymc help!

**Comment by krgomez** [comment]
Oh shoot. I'm sorry - I added two subject terms to an existing record using the old attribute. It looks like you fixed it. I promise to not use subject anymore!

**Comment by dustymc** [comment]
@krgomez here's what I have for your results columns:

``<cfset catrec_rslt_cols="guid,media,scientific_name,spec_locality,creator,collector,subject">``

That's collector role subject - I can remove if necessary.

>taxon

That would need cached, and I think there's nothing appropriate at the moment. Flattening something beyond "core Linnean" taxonomy was https://github.com/ArctosDB/arctos/issues/3498, probably best to revive that if you can specify what could be added.

Search is currently:

``
<cfset catrec_srch_cols="guid_prefix,cat_num,accn_number,scientific_name,any_geog,spec_locality,collector,culture_of_origin,
		description,taxon_name,identification,common_name,materials,specimen_event_type,verbatim_date">
``
 Which I think is not involved in the ambiguity and so probably OK.

**Comment by krgomez** [comment]
@dustymc I do not want subject or collector included in the results columns - can we remove those? That's okay if we can't add taxon to the results. Though, I don't suppose there is a way to easily include only the specific object type (drawing, painting, silver gelatin print, etc.) and not the full taxon? Another search result that would be nice to see is _verbatim date_ (for the creation event).

The search fields are good except that _subject matter_ is missing. We need to be able to search by subject. Is it possible to also add the _portfolio or series_ attribute?

**Comment by Jegelewicz** [comment]
@dustymc I tried this again today - I don't see that the "subject" attribute is in use, but I am unable to remove collections from it or delete it.

**Comment by dustymc** [comment]
ctattribute_code_tables has to come first - i zapped everything

**Comment by Jegelewicz** [comment]
DOH!

**Comment by krgomez** [comment]
I just want to make sure this request hasn't been lost/forgotten: https://github.com/ArctosDB/arctos/issues/5448#issuecomment-1382232330

**Comment by Jegelewicz** [comment]
@dustymc now I think this needs changed to "subject matter" 

![image](https://user-images.githubusercontent.com/5725767/215884637-7fc8cc61-ac10-46b8-bab9-002d58e48299.png)

**Comment by dustymc** [comment]
>not want subject or collector included in the results columns 

Next release

Taxonomy still needs something like https://github.com/ArctosDB/arctos/issues/3498, I don't have a place for those data (or don't know how to use it, or something).

>verbatim date (for the creation event)


https://github.com/ArctosDB/PG_DDL/blob/master/function/getpriorityspecimenevent.sql controls "flattened type" but that seems to be heavily biased towards creation, so added for next release.

I'll handle the change in https://github.com/ArctosDB/arctos/issues/5460

Any further additions (portfolio or series) should be added to that as well.
