### ISSUE TITLE
Check out event loader and update collecting event remarks for JFBM:Fish

### ISSUE THREAD

**Issue by barke042** [ArctosDB/arctos#5451]
**Background:**
I recently uploaded collecting events for JFBM:Fish. The component uploader worked fine but appears to have bypassed addition of event remarks. This happened twice because I had two separate event files both of which had records with event remarks, and no event remarks (placed in a field headed 'coll_event_remarks' as in the template provided) ended up in the database. Consequently, the component loader for events may be broken (or it just hates me or my data--however, it is unprecedented in my brief Arctos experience for a loader to take some but not all template fields from what I loaded).

**Requests:**
1) Please check on the event loader to see what's up with it or with my upload. Here is one of the original upload files:
[fish.events.upload.12_27_2022.csv](https://github.com/ArctosDB/arctos/files/10363211/fish.events.upload.12_27_2022.csv)

2) Please update JFBM:Fish collecting events to include the remarks attached here:
[fish.event.remarks.01_06_2023.csv](https://github.com/ArctosDB/arctos/files/10363175/fish.event.remarks.01_06_2023.csv)
This file includes event names (which are UUIDs from our old database), and the corresponding remarks.

**Comment by dustymc** [comment]
Loader patched for next release.

One event had a remark, I just dropped it/did nothing.

```

arctosprod@arctos>> select coll_event_remarks,collecting_event_name from collecting_event where coll_event_remarks is not null and collecting_event_id in (select cid from temp_update_evt_rmk);
                                                 coll_event_remarks                                                 |        collecting_event_name         
--------------------------------------------------------------------------------------------------------------------+--------------------------------------
 Accession 1001<br>Collected using 6'x10'x1/8" seine as well.<br>Froze: Etheostoma lynceum (7), Noturus miurus (6). | 9640bc92-6413-11e3-81f0-12313d0829ba
(1 row)

arctosprod@arctos>> delete from temp_update_evt_rmk where collecting_event_name='9640bc92-6413-11e3-81f0-12313d0829ba';
DELETE 1



```

Blargh, then I made a mess. I didn't pre-check these and 45 records have problematic characters (I think it's a UTF conversion failure).

Please fix these, or let me know how to do so, and I'll load them too.

The rest are done.

[temp_update_evt_fail.csv.zip](https://github.com/ArctosDB/arctos/files/10489979/temp_update_evt_fail.csv.zip)

**Comment by barke042** [comment]
Thanks, @dustymc! Yes, there was an issue with the my ° symbols. Here is the (hopefully fully) corrected file.
[temp_update_evt_fail_fixed.csv](https://github.com/ArctosDB/arctos/files/10501177/temp_update_evt_fail_fixed.csv)

**Comment by dustymc** [comment]
done
