### ISSUE TITLE
Update JFBM:Fish report to include TRS data from locality_attributes

### ISSUE THREAD

**Issue by barke042** [ArctosDB/arctos#5453]
**Background:**
Our legacy Fish collection labels look like this:
![Screen Shot 2023-01-06 at 3 36 53 PM](https://user-images.githubusercontent.com/11162169/211104381-30d03f6a-c9a1-4f83-99ac-0f59dcc22449.jpg)

With some help from Dusty and templates of others, I have gotten to this point with Arctos reports:
![Screen Shot 2023-01-06 at 3 34 08 PM](https://user-images.githubusercontent.com/11162169/211104528-cfcea3f7-3ec0-4634-9c36-c4cc41ad0068.jpg)
Ignore the fact that it's a different specimen.

In this mockup I have put placeholders (e.g., ^tn^) for TRS data. In our original Specify database, TRS were multiple fields in a locality detail table, whereas in Arctos these are locality attributes with a one to many relationship. So, we need to tabulate TRS to make them available for formatting in html, and I would like help doing so!

**Request:**
Modify the SQL for our fish report (https://arctos.database.museum/Reports/reporter.cfm?action=edit&report_id=48) to allow printing of TRS data on fish jar labels.

**Comment by dustymc** [comment]
Example record with these data?

**Comment by barke042** [comment]
I should point out that I've only hand-entered TRS data for one locality, "Mud Creek, ca. 2 miles NW of Murdock" (name=ec94dc9c-55fa-4db7-b2a8-c08b04bd79b0).

**Comment by dustymc** [comment]
```
arctosprod@arctos>> select concatLocalityAttributeValue(locality_id,'TRS range') from locality where locality_name ='ec94dc9c-55fa-4db7-b2a8-c08b04bd79b0';
 concatlocalityattributevalue 
------------------------------
 R38W
(1 row)
```

**Comment by barke042** [comment]
Success!
![Screen Shot 2023-01-06 at 4 28 47 PM](https://user-images.githubusercontent.com/11162169/211110661-192bb531-02db-4ccd-8ce7-4e3d2b0bd1ef.jpg)

**Comment by barke042** [comment]
Although with the structure imposed in Arctos, I can drop the leads. Anyway, I'll let you know if I run into other problems. Thanks!

**Comment by dustymc** [comment]
It's beautiful (for not being a 2d barcode...)!
