### ISSUE TITLE
Need Help with Arctos Error - Bulkload Status PART_BARCODE_1 is a label

### ISSUE THREAD

**Issue by kderieg322079** [ArctosDB/arctos#5455]
# Error Text
**PART_BARCODE_1 [ UMNH020168 ] is a label**

# Where it happened
**Bulkloader status**

# Steps to get there
**I scanned a barcode that is associated with a part on the data entry form**

# Additional Details
We have the series UMNH000001-UNMH100000 claimed. Barcodes in the series UMNH020001 and beyond have not yet been assigned to containers in Arctos. The barcode is on the datasheet and was therefore scanned into the data entry form. The matching barcode is on a cryovial, but it has not been scanned into position yet.

**QUESTION:** Can the record not be loaded unless the barcode is already assigned to a container?

**Comment by dustymc** [comment]
Short version: yes, https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcontainer_type#container_label

Longer version: https://handbook.arctosdb.org/documentation/container.html#object-tracking-in-general

I'm hoping someone with a more practical outlook will pop in...

**Comment by campmlc** [comment]
You need to convert your barcodes to container types in bulk using bulk
update container, or you can use Find Container, Edit to change the
container type of a single barcode, or you need to scan the barcode into a
freezer box, which automatically converts it to a cryovial.

**Comment by kderieg322079** [comment]
Thanks Dusty & Mariel! I am in the process of reworking our object tracking workflow and still have much to learn.
