### ISSUE TITLE
Catalog Item Type reporting

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5458]
> @dustymc how about a report for collections of records without a GBIF-approved catalog item type? I'm guessing someone made an error when entering that record.

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/arctos/issues/2432#issuecomment-1218335285_
      
Maybe this is just something for collection stats? Basically a list of the catalog item types used in any given collection that links to search results. This would make it clear when a paleo collection has no "fossil specimens" and allow collections using catalog item types that do not match approved GBIF BasisOfRecord values to clean up their act.

**Comment by dustymc** [comment]
This is irrelevant in light of https://github.com/ArctosDB/arctos/issues/2432#issuecomment-1648238071
