### ISSUE TITLE
Code Table Request - add values to citation type status table

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#5462]
**Goal*
Update citation type status to include terms in current usage for molecular vouchers and other vouchers types outside of traditional taxonomy. 

**Context**
Existing values are not current; people are putting these terms in remarks in Arctos records which is suboptimal.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcitation_type_status

**Proposed Value**
See paper:  https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3890671/

**Proposed Definition**
See paper. 

**Priority**
Normal - requires discussion.

**Comment by Jegelewicz** [comment]
@campmlc It would be very helpful if you could provide a list of terms and definitions - there is a lot going on in this paper and I am not sure what terms you are talking about.

**Comment by campmlc** [comment]
Sure, will do once I can get to my computer. I just wanted to post the
issue so I don't lose the mental thread.

**Comment by ebraker** [comment]
Pinging @campmlc - will you add values and definitions?

**Comment by campmlc** [comment]
In field with limited service until next week - keep pinging me!

**Comment by Jegelewicz** [comment]
See also #6434
