### ISSUE TITLE
Feature Request - Arctos Resource for Disaster Preparation for collections

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#5463]
From the January AWG Issues meeting - is there a way to put together either training or resources center for Arctos collections to use in case of a disaster at one of our collections.

Starting off with a few helpful links and ideas.
[HENTF ](https://culturalrescue.si.edu/hentf/) looks to be a good source to start for collections in the US.
International sources?

An idea was also put forward that maybe we could organize Arctos training or workshops for collections.

**Comment by ewommack** [comment]
The [Cultural Rescue Initiative](https://culturalrescue.si.edu/) also works internationally.

**Comment by AJLinn** [comment]
Here are a few also that I've worked with or received training from.

- https://www.culturalheritage.org/resources/emergencies/national-heritage-responders
- https://lam.alaska.gov/c.php?g=901538&p=6487353
- https://www.getty.edu/conservation/publications_resources/pdf_publications/emergency.html
- https://www.culturalemergency.org/who-we-are
- https://www.iccrom.org/what-we-do/programmes/first-aid-and-resilience-cultural-heritage-times-crisis-far/emergency
- https://www.americansforthearts.org/by-program/networks-and-councils/local-arts-network/national-coalition-for-arts-preparedness-and-emergency-response
