### ISSUE TITLE
Feature Request - expedition

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5466]
**Is your feature request related to a problem? Please describe.**

Pathology meeting suggests we're missing a "node" in Arctos.

**Describe what you're trying to accomplish** 

Record something accession-like, project-like, event-like, but not exactly any of those. Might include a place for "trapline data" (Standardized? Attached? Both?) and individual records in there (if standardized) might be linked to catalog records. 

**Describe the solution you'd like**

Discussion; do we need this, where does it go, what does it look like, why should anyone care?

**Describe alternatives you've considered**

* Whatever we're doing now.
* Catalog 'set a trap and nothing happened'

**Additional context**

* Provides a place for effort - 500 traps were set, resulted in 18 captures, those are linked to catalog records so eg evidence for taxa can be examined.
* Provides a place for an "effort summary" - "we were looking for fleas and would have ignored everything else."

**Priority**

Low?

**Comment by acdoll** [comment]
I could see this being useful to some collectors/datasets. Sounds kind of like LIMS data from fieldwork. FWIMS?

**Comment by Jegelewicz** [comment]
This seems project-like to me and it seems like anyone could do this now using accessions, projects and media?
