### ISSUE TITLE
Code Table Request - New other ID type

### ISSUE THREAD

**Issue by krgomez** [ArctosDB/arctos#5467]
**Goal**
[ Describe what you're trying to accomplish. ]
UAM:Art has botanical drawings that were created from observing specimens from the Harriman Alaska expedition at the United States National Herbarium. I added other IDs using the USNM: National Museum of Natural History type and the catalog numbers. Can we add a type for the NMNH botany collections with a URL so that the specimens can be linked to the catalog records?

**Table**
[ Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table you are requesting changes to here. ]
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type

**Proposed Value**
[ Proposed new value ]
I think it would be NMNH:Botany, but you all would know better than me. Or maybe USNH - United States National Herbarium?

**Proposed Definition**
[ Clear, complete, non-collection-type-specific definition of the new value. ]
National Museum of Natural History Botany Collections?

**Other ID BaseURL**
https://collections.nmnh.si.edu/search/botany/?ark=

**Comment by dustymc** [comment]
Suggest this NOT be implemented.

After https://github.com/ArctosDB/arctos/issues/6005, just use type "identifier" and the full identifier, no base needed.

**Comment by ebraker** [comment]
@krgomez please close the issue if this works for you or add additional comments

**Comment by Jegelewicz** [comment]
@DellaCHall let me know if you still need this and I'll help you figure it out.

**Comment by dustymc** [comment]
Actually - the URL suggests that this is an ARK, in which case the ARK itself - not the current target - should be used as the identifier (of type 'identifier').

**Comment by dustymc** [comment]
nothing to do here
