### ISSUE TITLE
support needed

### ISSUE THREAD

**Issue by Michaelaaaaa3** [ArctosDB/arctos#5471]
When I attempt to access the David H. Snyder Museum of Zoology via submitting a query, I get a signal that it is loading but it never fully loads. I can't access what is in the database.
![Screenshot (18)](https://user-images.githubusercontent.com/122562435/212153439-131af4fa-7a5a-4305-a4bc-7f05fdd1ca93.png)

**Comment by Jegelewicz** [comment]
@Michaelaaaaa3 try simply accessing arctos.database.museum then search for that particular collection.

**Comment by Jegelewicz** [comment]
![image](https://user-images.githubusercontent.com/5725767/212162690-ab721ce6-6eed-4c8c-97b1-42ca482f7cc0.png)

**Comment by Michaelaaaaa3** [comment]
I added APSU:herp, then added bog turtle as my identifications common name. I am still only getting a loading signal after submitting query. Suggestions?

**Comment by Michaelaaaaa3** [comment]
maybe it would be helpful if someone could screenshot for me a step by step on how they're accessing the collection

**Comment by Jegelewicz** [comment]
https://arctos.database.museum/search.cfm

![image](https://user-images.githubusercontent.com/5725767/212165057-fb0d505a-65b6-4acd-a1ab-36898fd256b3.png)

Enter collection to search

![image](https://user-images.githubusercontent.com/5725767/212162690-ab721ce6-6eed-4c8c-97b1-42ca482f7cc0.png)

enter bog turtle in any identification

![image](https://user-images.githubusercontent.com/5725767/212165534-3e579b92-8b5f-41b8-aac0-84a83bb2cbcc.png)

Select Submit Query

Results
https://arctos.database.museum/search.cfm?guid_prefix=APSU%3AHerp&taxon_name=bog%20turtle

**Comment by Michaelaaaaa3** [comment]
It must be a problem with my computer, I could follow those steps and see the results on my phone just fine. thankyou!

**Comment by Jegelewicz** [comment]
It seems like you are stuck in the APSU:Herp portal - maybe clear cookies and cache and see if that works.
