### ISSUE TITLE
form cleanup

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5472]
I'll remove these forms in a few days if nobody has reason to keep them.

I think all of these reports are probably older than the old (cfr) reporter, but please let me know if any of them are being used in some mysterious way.

* MSBMammLabels.cfm
* /CustomTags/makeBarcode.cfm is used by MSBMammLabels
* [/Reports/UAMLoanInvoice.cfm](https://arctos.database.museum/Reports/UAMLoanInvoice.cfm)
* [/Reports/kenai.cfm](https://arctos.database.museum/Reports/kenai.cfm)
* [/Reports/label_report.cfm](https://arctos.database.museum/Reports/label_report.cfm)
* [/Reports/ledger.cfm](https://arctos.database.museum/Reports/ledger.cfm)
* [/Reports/LoanInstructions.cfm](https://arctos.database.museum/Reports/LoanInstructions.cfm)
* [/Reports/loanShipLabel.cfm](https://arctos.database.museum/Reports/loanShipLabel.cfm)
* [/Reports/mammalLabels.cfm](https://arctos.database.museum/Reports/mammalLabels.cfm)
* [/Reports/msbLabelDataDown.cfm](https://arctos.database.museum/Reports/msbLabelDataDown.cfm)
* [/Reports/MSBMammLoanInvoice.cfm](https://arctos.database.museum/Reports/MSBMammLoanInvoice.cfm)
* [/Reports/print_nk.cfm](https://arctos.database.museum/Reports/print_nk.cfm)
* Reports/SpecUsageReport.cfm (linked as "Create Report Data" from project search results)
* [/MSBMammLabels.cfm](https://arctos.database.museum/MSBMammLabels.cfm)
* [/narrowLabels.cfm](https://arctos.database.museum/narrowLabels.cfm)

*  [/uam_eh/search.cfm](https://arctos.database.museum/uam_eh/search.cfm) @AJLinn are you still using this? It can stay as long as the legacy search form if necessary

**Comment by AJLinn** [comment]
> [/uam_eh/search.cfm](https://arctos.database.museum/uam_eh/search.cfm) @AJLinn are you still using this? It can stay as long as the legacy search form if necessary

If you can send me the stable URL for the new custom EH search, I'll implement it and then you can get rid of this.

**Comment by dustymc** [comment]
> stable URL

https://github.com/ArctosDB/arctos/issues/5341#issuecomment-1347635717

https://arctos.database.museum/search.cfm?sp=uam_eh&guid_prefix=UAM:EH

**Comment by AJLinn** [comment]
> https://github.com/ArctosDB/arctos/issues/5341#issuecomment-1347635717

https://arctos.database.museum/search.cfm?sp=uam_eh&guid_prefix=UAM:EH

New links have been integrated into my various locations and my website instructions are updated to the new default search screen and UAM:EH profile page. I'm ready to cut loose the old link when you're ready to get rid of the legacy search form.

**Comment by dustymc** [comment]
Done.

Removed files can be recovered from v1.9 if necessary.
