### ISSUE TITLE
New UI Development - distraction

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5477]
Can we eliminate the pop-up when automated options from the customize dropdowns are selected? They are pretty distracting.

https://user-images.githubusercontent.com/5725767/212353214-b36c7e1c-ba79-4da2-9598-0c42eb427a48.mp4

**Comment by dustymc** [comment]
>eliminate the pop-up

Not while reusing current code. (And this was discussed in a UI meeting.)
