### ISSUE TITLE
Arctos New Search Page Help Request - Arctos Alert download/export search results

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#5478]
Received through Arctos Communications email:
Dear Arctos,

I am trying to download a dataset of specimens from arctos. Hoping to put the data into excel to help me organize/select specimens for a genetic study.

How do I export the search result? 

In addition, I would like to be able to display which specimens have associated frozen tissues.

Regards,

Mark

>,-,~

Mark Statham Ph.D.| Professional Researcher | Mammalian Ecology and Conservation Unit

University of California, Davis
Veterinary Genetics Laboratory

[Email:Statham@ucdavis.edu](mailto:Email%3AStatham@ucdavis.edu) | Phone office/lab: 530 754 7932
[Personal website](https://markstatham.com/)
[UC Davis website](http://mecu.ucdavis.edu/)
[ResearchGate](https://www.researchgate.net/profile/Mark-Statham-3)

**Comment by ewommack** [comment]
Sent at at 1233 on 13th February 2023 from Arctos Communications email:

Hi Mark,

Thank you for using the Arctos Database. 
We are working on putting together a new search page for Arctos, and we appreciate you trying it out.

Our general system of technical help is done through Github. I will try and help you here, but I am also going to put together a Github issue for your question as well, in case anyone else in the community can provide additional help. The issue on Github is here: https://github.com/ArctosDB/arctos/issues/5478

The tools for download data from the Arctos database become available when you log in, and you can find the download option under the drop down menu title Tools at the top of the search results. 

You can modify your search using all of the different options on the search page, and for tissue type you will want to look under Parts. You can enter a part name in, or you can click the option to customize and see all of the different options in the code table. 
![Untitled_arctos question help](https://user-images.githubusercontent.com/18562884/212403613-a0aa85f0-1d3a-4435-b6d5-6864d2759076.png)
I hope that helps.

thank you,
Beth Wommack

**Comment by m-statham** [comment]
Hi Beth.

Thanks for the info.
I have now created an account, logged in, and I can access the download function.

I am still having some issues with the 'part'. I would like to have a column that lists what type of specimen is available. Here I am mainly interested in skin, v skull, v frozen tissue.

**Comment by dustymc** [comment]
>column that lists what type of specimen is available.

<img width="124" alt="Screenshot 2023-01-13 at 5 31 04 PM" src="https://user-images.githubusercontent.com/5720791/212444501-67d8cac5-6ae9-4c1a-a286-e2c42e357cb8.png"> 

<img width="480" alt="Screenshot 2023-01-13 at 5 31 29 PM" src="https://user-images.githubusercontent.com/5720791/212444508-5fd1ff46-10bf-4d0c-974c-118af5d8cd83.png">

**Comment by ewommack** [comment]
Hi @m-statham this might also be what you are looking for. I did a search for a taxon only in one collection, and then to download all of the parts for those objects I went to the Tools Menu under search and selected Download Parts:
![Arctos_download parts](https://user-images.githubusercontent.com/18562884/212984900-dc01b64c-ba18-4af6-9779-f6325dd349d2.jpg)

That got me a file that I could play with and download that had all of the parts for all of those objects on it.

**Comment by ewommack** [comment]
On 13 Jan 2023 - @ccicero sent email answer:
Hi Mark - When you get the result set click on 'Tools' and you'll see an option for Download (second from the top in the dropdown menu).
image.png
Regarding frozen tissues, the parts will be downloaded if you customize the result set to include them (Customize results ---> scroll down to 'parts' and check the box, then hit save.

You can also customize the search screen to include a checkbox for just searching on records with tissues. Customize Search ---> scroll to category 'Parts' and select 'Is Tissue' - that will give an option in the parts block for selecting 'yes' to only get records with tissue.

image.png

I hope this helps, and let us know if you have more questions.

Thanks,
Carla

**Comment by ewommack** [comment]
On 17 Jan 2023:
Hi Beth,

I am having some issues with 'parts detail'.

I had the option the day when I was not logged in. I it would display in the results output. But now that I am logged in i dont see that option.

Would you have a few minutes to zoom chat, so that you can see what I have on my screen.

Mark

**Comment by ewommack** [comment]
Hi Mark,

Sorry, I'm a bit swamped today with the start of the semester. I think I have some time around 3pm MT, or 5pm MT for a zoom call. 

Where are you looking for the "parts detail", perhaps I can figure out where it went?

Thank you,
Beth

**Comment by m-statham** [comment]
Hi Beth,

No worries. I am open to either of those times. Just shoot me an email if/when you are available.

I am looking under parts, customize, customize (choose individual options). 

I am happy to leave this sit until we talk.

**Comment by ewommack** [comment]
@m-statham - so somewhere in here?
![Arctos_parts detail?](https://user-images.githubusercontent.com/18562884/212990364-c0ba7ad3-ea51-4494-b424-3476daa9f709.png)

@dustymc - did we rearrange some of the search options? I can't find "Parts Detail" in Customize search options, only detail for identifier and events (in the description)

**Comment by dustymc** [comment]
Parts Detail is a results, not search, option.

**Comment by ewommack** [comment]
@dustymc - I'm really sorry, but confused I am.

Where do I find it?

**Comment by m-statham** [comment]
In my search output, I previously had a column header "Parts Detail". Subsequently I have been unable to get this information to display.

**Comment by ewommack** [comment]
@m-statham - I think that is what you get now when you select Tools -> download parts.
This is a bird example, but it took me to a file that I could create where I could download all of the part types for all of the specimens from my search:
![Parts details_arctos](https://user-images.githubusercontent.com/18562884/213057471-0cbde525-110e-4220-9d39-13881cc5212f.png)

**Comment by dustymc** [comment]
@ewommack that's an Operator form.

https://github.com/ArctosDB/arctos/issues/5478#issuecomment-1382625797 is the path to adding columns.

**Comment by ewommack** [comment]
@m-statham - ok lets try it while logged in as a researcher.
I first got my search results -> clicked Customize Results -> I clicked parts and partdetail -> clicked save
And I got a column with parts and the partsdetails:
![Parts4](https://user-images.githubusercontent.com/18562884/213061276-d98ae4b5-ee2e-41db-8f6e-d85cacedcefa.png)

Then under Tools -> download will let you download that info in the results.
Or you can select Tools -> Reload with sharable URL, and you can save your search URL and come back to it with the same selected results columns. 
Or try Tools -> Summarize, and you can select parts, and see how many have different parts you may be interested in.

@dustymc -> are we still allowing saved searches?

**Comment by dustymc** [comment]
>still allowing saved searches?

Everything's always in the one place.

<img width="294" alt="Screenshot 2023-01-17 at 5 57 49 PM" src="https://user-images.githubusercontent.com/5720791/213062518-2742b990-2e75-4a37-8e20-215e781d91bc.png">

**Comment by ewommack** [comment]
> Everything's always in the one place.

When I was logged in as just a regular user I did not see Save Search as an option. 
![Parts5](https://user-images.githubusercontent.com/18562884/213064504-c9831389-9fa6-4806-bfd9-29a034235da6.png)

**Comment by dustymc** [comment]
>logged in as just a regular user

Ah, thx, next release.

**Comment by ewommack** [comment]
Archive Search may also be an option that regular users may find useful. If I'm looking for parts, it would be really helpful to be able to come back and open up the same search parameters and results again.

**Comment by Jegelewicz** [comment]
One thing that came out of the meetup we had is that people are trying to customize their results with the customize thingees in the search form - maybe we need to emphasize that these are two different things?

**Comment by m-statham** [comment]
I agree.
________________________________

**Comment by AJLinn** [comment]
> maybe we need to emphasize that these are two different things

Make those two buttons different colors?

**Comment by campmlc** [comment]
Maybe a single drop-down with two options?

**Comment by dustymc** [comment]
>different colors?

I don't think so, the basic function is the same: customize stuff.

**Comment by ewommack** [comment]
> different colors?

> I don't think so, the basic function is the same: customize stuff.

Maybe make the text larger for Results?

**Comment by Jegelewicz** [comment]
But in this case these things were being confused!

![image](https://user-images.githubusercontent.com/5725767/213504779-6845996f-6aaa-4f21-abd4-a90baba7a1d8.png)

So he was trying to customize results using the customize thingees in the search form....

**Comment by Jegelewicz** [comment]
Maybe something that draws a line between the search form and the results stuff?

**Comment by ewommack** [comment]
A line between the results and search field might work. I was also thinking that if you made Customize Results and the Tools menu larger it would create a header effect for the search results section.

**Comment by dustymc** [comment]
> text larger 

Same argument, the object is of a class and so should look like others of its kind (or we should drop the classes).

>using the customize thingees in the search form

OH! Thx, that makes more sense that what I though was happening. Those are "Customize Search" with some extra parameters, FWIW.
