### ISSUE TITLE
Add missing provinces to Philippines

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#5483]
Explain what geography needs created.

Arctos is missing twenty provinces from the Philippines.  

Abra
Agusan del Norte
Agusan del Sur
Aklan
Apayao
Camarines Norte
Camiguin
Capiz
*Davao de Oro
Dinagat Islands
Ifugao
Kalinga
Lanao del Sur
Misamis Occidental
Misamis Oriental
Nueva Vizcaya
Quirino
South Cotabato
Sultan Kudarat
Tawi-Tawi

*GADM still shows Compostela Valley as a Province.  Per Wikipedia the Name of Compostela Valley changed to Davao de Oro through the Republic Act 11297 approved on April 17, 2019.  Can we add Davao de Oro with GADM's spatial data for Compostela Valley? (See  https://en.wikipedia.org/wiki/Davao_de_Oro) 

We have many, many specimens from the Philippines so having all the provinces in Arctos is very helpful.

Is this request getting closer to what you need?

**Comment by dustymc** [comment]
>Per Wikipedia

I still don't think we can realistically manage dealing with diverging from GADM. I'm definitely willing to try whatever, but it needs some sort of conversation/flag/SOMETHING.

I added Davao de Oro as a search term of Compostela Valley. Here's what I think it missing from Arctos. Please fill in source_authority or let me know what I've mangled.

[temp_geog_create(9).csv.zip](https://github.com/ArctosDB/arctos/files/10421521/temp_geog_create.9.csv.zip)

**Comment by sharpphyl** [comment]
Here are the data for source_authority.  For Compostela Valley, I had to use https://en.wikipedia.org/wiki/Davao_de_Oro because I can't find a Wikipedia entry for Compostela Valley (although the history is outlined in the Davao de Oro entry).  

Looks good.  Thanks!

[temp_geog_create(9).csv](https://github.com/ArctosDB/arctos/files/10421655/temp_geog_create.9.csv)

**Comment by dustymc** [comment]
done
