### ISSUE TITLE
Add missing provinces to Poland

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#5487]
GADM lists 12 additional provinces to what is in Arctos geography. 

Greater Poland
Lesser Poland
Łódź (Lodz)
Lublin
Lubusz
Opole
Podlachian
Pomeranian
Silesian
Subcarpathian
Świętokrzyskie
West Pomeranian

The Arctos listing of Kujawsko-Pomorskie includes Kuyavian-Pomeranian as a search term.  GADM shows that the province name is [Kuyavian-Pomeranian](https://gadm.org/maps/POL/kuyavian-pomeranian.html) if we want to match GADM.

We have two catalog records that are missing the province.  We don't need the ASCII characters for our searches.

**Comment by dustymc** [comment]
Ouch. I have no idea where to go with this one. Kujawsko-Pomorskie is the only match I can make between Arctos and GADM. Can we put this off until a prioritized https://github.com/ArctosDB/arctos/issues/5417 is discussed? If not I suppose I'll just replace characters and hope that's a defensible transliteration??

**Comment by sharpphyl** [comment]
> Ouch. I have no idea where to go with this one. Kujawsko-Pomorskie is the only match I can make between Arctos and GADM. 

It's ok if you prefer to leave Kujawsko-Pomorskie as it is since Kuyavian-Pomeranian is in its "search" list.  We'll make a comment in our catalog record linking the two.  I leave further direction to the Geography team.

**Comment by dustymc** [comment]
Sorry, I wasn't clear. I run my scripts to round up GADM data from a country then...

```

arctosprod@arctos>> select state_prov from temp_geog_create;
     state_prov      
---------------------
 Dolnośląskie
 Kujawsko-Pomorskie
 Łódzkie
 Lubelskie
 Lubuskie
 Małopolskie
 Mazowieckie
 Opolskie
 Podkarpackie
 Podlaskie
 Pomorskie
 Śląskie
 Świętokrzyskie
 Warmińsko-Mazurskie
 Wielkopolskie
 Zachodniopomorskie
(16 rows)

Time: 0.899 ms

arctosprod@arctos>> select country,state_prov from  temp_geog_create where (country,state_prov) in (select country,state_prov from geog_auth_rec where country='Poland');
 country |     state_prov     
---------+--------------------
 Poland  | Kujawsko-Pomorskie
```

I can only match the last line, which I'd normally use to remove that (it already exists and needs no more work) before sending the CSV on to you. 

>GADM shows that the province name is [Kuyavian-Pomeranian](https://gadm.org/maps/POL/kuyavian-pomeranian.html)

That doesn't seem to be the case in the [data I have](https://geodata.ucdavis.edu/gadm/gadm4.1/shp/gadm41_POL_shp.zip). This isn't the first time I've found a mismatch between GADM's data and their UI; perhaps that needs clarified for documentation.

**Comment by sharpphyl** [comment]
I think this is the second time we've found a mismatch between your GADM download and GADM's UI.  Here's a clip from their website which is lagging behind your download in addition to being significantly different (in Polish?), e.g. Dolnośląskie is Lower Silesian Voivodeship per Wikipedia.

<img width="189" alt="Screenshot 2023-01-16 at 2 59 21 PM" src="https://user-images.githubusercontent.com/15368365/212771689-dd800992-4f97-413e-9d52-91f4ce637268.png">

**Comment by dustymc** [comment]
>continue to send you the names as they appear in the GADM UI?


I pull data for the country, delete whatever's already in Arctos, and then start digging to see what I might have missed and why, and use this opportunity to correct (to align with GADM) whatever I missed in the Arctos data on the first pass. That can be super-simple (drop "Prefecture" and it all works), or brain-melting (are there really 19 things that all vary by what looks like typos?!). A list of what you think I'll find in there is pretty handy when things get complicated. If including the list is easy, it's worth it to me. If it's not easy, I'm not sure it's critical (but I might make a huge mess and then decide it's critical...).

Also, I dug an old script up - it promptly died on these data, but it could be coerced into asciiifing these, which might not be anyone's idea of 'valid' but it is repeatable and I suppose I'll take that, if I must. I'd still prefer to come to some sort of consensus first, but if you don't want to wait I think I have a mostly-defensible-ish way to just do this.

**Comment by sharpphyl** [comment]
We can wait.  I've adjusted our two catalog records that triggered this request so there is no rush for making decisions on ascii etc.

**Comment by dustymc** [comment]
Here's CSV:

[temp_geog_create(15).csv](https://github.com/ArctosDB/arctos/files/10744355/temp_geog_create.15.csv)

Please VERY carefully review the state names, and compare to the data in Arctos (which I've hopefully GADMized without error). My asciialyzer had to learn a lot for this, I could have mucked it up.

Assuming I somehow didn't turn all the ą's into Ž's, please add appropriate wikipedia links to source_authority and post the CSV back here.

**Comment by sharpphyl** [comment]
This may take more than one review but I think you've got it.  Again, the GADM that I see online isn't the same as what you get in your download.  Maybe GADM uses English in the URL and Polish in the download.  Anyway, I added the GADM URL in the last column just as a doublecheck.  Just delete that column if you don't see anything weird.  I did check in  Wikipedia to make sure they also list the GADM verbiage.  

Do you want to add additional search terms or will that happen automatically?  For example, Wielkopolskie is also Greater Poland which does appear within the URLs for GADM and Wikipedia. Not sure which might be the more common search term.


[temp_geog_create.15 (1).csv](https://github.com/ArctosDB/arctos/files/10756906/temp_geog_create.15.1.csv)

**Comment by dustymc** [comment]
>more than one review but I think you've got it. 

Thanks! Yes doesn't have to be perfect (but it should be!) but would definitely like to avoid any 'eyes glazed over 5 minutes ago' mistakes, which seem somewhat likely with all these characters.

>GADM that I see online isn't the same as what you get in your download. 

I think maybe I figured that out. https://gadm.org/maps.html says "(GADM version 2.8) " When I download I get things like ``gadm41_CXR_shp.zip`` which for various reasons I'm relatively sure is version 4.1. So maybe their maps are just much older data (or maybe those versions refer to completely different things, IDK).

>I added the GADM URL

I'm not sure what to do about that. We've been looking for an identifier, but it seems the version is important and that doesn't seem to be something I can directly tie to what I download.

> add additional search terms 

Sure!

>which might be the more common

Doesn't matter, except in the sense that some super-obscure thing might be what makes some old data make sense. (That's the use case I created the idea in support of.) WHATEVER you want to add as search terms is welcome, and if you want to do that after the fact I'll find a way to make that happen. 

Let me know if you want me to just load this, it looks fine to me unless you want to dig out more search terms.

**Comment by sharpphyl** [comment]
I think it's fine to load (just delete my GADM URL column) but I think we should add search terms that may be more common to US users.  Do I send them to you in a csv or other document or just a list?

**Comment by dustymc** [comment]
>fine to load 

done

>search terms

CSV would be great - one column higher_geography and one column search_term would be ideal, but I can work with anything that lets me get there. Just repeat higher_geography as many times as necessary eg

higher_geography--search_term
someplace--A
someplace--B
someplace--C

**Comment by mkoo** [comment]
In the past we had a policy that we had HG for all admn_0, admin 1. Admn_2
was only for USA, CAN, and a few other select countries. Other countries
with Admn_2 in the verbatim locality would add as part of specific locality.

Maybe we need to return to that policy or find out if GADM has a quality
flag we can use for countries with confirmed admn_2 designations?

FYI, I asked Robert about the best way to coordinate and share updates and
issues with him (still waiting for response). We really need a change log
from GADM too

**Comment by dustymc** [comment]
The geography policy is https://handbook.arctosdb.org/documentation/higher-geography.html (and I don't think there are any problems or conflicts with it here??)

**Comment by sharpphyl** [comment]
Let me know if I've misinterpreted your instructions.  I think these are more than enough other search terms to find what we're looking for.  Thanks!

[Search Terms for Poland.csv](https://github.com/ArctosDB/arctos/files/10768120/Search.Terms.for.Poland.csv)

**Comment by dustymc** [comment]
Done. Ask me for a template if you want to do this again - I could make it a little easier for both of us. (Or request a component loader if you want to do this a lot.)
