### ISSUE TITLE
Add missing provinces to Thailand

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#5488]
GADM lists 77 provinces for Thailand.  Arctos is missing 39 of them.  I don't see any strange characters in this list, but GADM and Wikipedia often don't agree on how to to structure the names, e.g. GADM uses Buri Ram and Wikipedia uses Buriram.

Amnat  Charoen
Ang Thong
Bangkok Metropolis
Bueng Kan
Buri Ram
Chachoengsao
Chai Nat
Chumphon
Kalasin
Kamphaeng Phet
Lampang
Lamphun
Lop Buri
Maha Sarakham
Nakhon Phanom
Nakhon Sawan
Narathiwat
Nong Bua Lam Phu
Nong Khai
Nonthaburi
Phayao
Phichit
Phitsanulok
Phra Nakhon Si Ayutthaya
Ratchaburi
Rayong
Roi Et
Sa Kaeo
Sakon Nakhon
Samut Prakan
Samut Sakhon
Samut Songkhram
Si Sa Ket
Sing Buri
Sukhothai
Udon Thani
Uttaradit
Yala
Yasothon

We need several of the missing provinces for data entry.  This is the last request for additions, at least until we run into more missing geography.

**Comment by dustymc** [comment]
> don't agree on how to to structure the names

GADM wins or this whole system falls apart. I changed a couple in Arctos and I think I've got the duplicates out of this list, but please check carefully and drop/change/let me know anything that I missed.

Here's CSV, needs the usual wiki links in source_authority.

[temp_geog_create(14).csv.zip](https://github.com/ArctosDB/arctos/files/10430694/temp_geog_create.14.csv.zip)

**Comment by sharpphyl** [comment]
Attached csv with Wiki links.  

I show that we already have Phangnga in Arctos but it's listed as Phang Nga.


[temp_geog_create(14).csv](https://github.com/ArctosDB/arctos/files/10437601/temp_geog_create.14.csv)

**Comment by dustymc** [comment]
>in Arctos but it's listed as 

Thanks, fixed, and please REMOVE those from the CSV in the future.

Done with this:

[temp_geog_create.14.csv.zip](https://github.com/ArctosDB/arctos/files/10457698/temp_geog_create.14.csv.zip)
