### ISSUE TITLE
Review loan items not loading

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#5489]
**Describe the bug**
Review loan items is not loading.

**To Reproduce**
I am trying to remove [CHAS:Inv:18013](https://arctos.database.museum/guid/CHAS:Inv:18013) from Loan L2016.13. The specimen was recataloged into CHAS:EH. I have already added CHAS:EH:18013 into the loan. I'm now trying to remove the old record (now duplicate) so I can encumber and delete it.

1. Outdated catalog record: https://arctos.database.museum/guid/CHAS:Inv:18013
2. Click for loan list
3. Edit data
4. Review attached items
5. Nothing loads

Arctos recognizes that there are items in the loan (20,743 cataloged items), but in the table below, where I can update disposition, etc., it says "No data available!"
![image](https://user-images.githubusercontent.com/93737929/212961784-484eba45-418d-4857-9671-d1a90079ca7a.png)

**Expected behavior**
The part attribute summary should load with disposition information.

**Desktop (please complete the following information):**
Firefox

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by dustymc** [comment]
Documentation could use some work - that's a data loan, I don't think there's even been a single-record removal UI. There is a bulk unloader.

**Comment by wellerjes** [comment]
I'm trying the bulk unload options and encountered this, but the loan does exist:
![image](https://user-images.githubusercontent.com/93737929/222258334-94288a02-194d-46a1-b7a1-6b58ba945b9e.png)

For these two catalog records: one is a duplicate, the other was recataloged into a different collection. I can't get rid of the duplicate records until I disconnect them from the original loan records.

**Comment by wellerjes** [comment]
When I try to review loan items for L2013.15, I get an error saying "An error occurred while communicating to the server"
![image](https://github.com/ArctosDB/arctos/assets/93737929/13f7378a-3ff4-4e96-84d8-483ab336a7ec)

There are over 3,000 parts attached to the load. Sometimes I can get a page to load, but this catalog record does not appear within the first page of search results. When I try going to the next page or changing the number of search results per page, then I get the communication error again.

I also tried the bulk unload option again just now, with the same result. Loan L2013.15 does exist, the transaction id is 21129807. The template doesn't ask for this, just guid, loan_guid_prefix, and loan_number.

**Comment by dustymc** [comment]
I think that's just a glitch in the matrix/https://github.com/ArctosDB/internal/issues/187, it works for me, but see also https://github.com/ArctosDB/arctos/issues/6288 - that does need rebuilt (and change requests are welcome).

**Comment by dustymc** [comment]
> bulk unload option

Can you be more specific, I'm not sure what that means.

**Comment by dustymc** [comment]
Thanks, that is only for data loans, CHAS:Mamm L2013.15 is not a data loan.

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctloan_type#data

The documentation has all been fragmented for some reason and I can't find any decent explanation. https://handbook.arctosdb.org/best_practices/Loan_Type.html glosses over the important things. https://github.com/ArctosDB/documentation-wiki/blob/92987701f1e9b86ed60ecfefe523a6128589d872/_documentation/loans.markdown maybe, if you can access that.

@Jegelewicz the doc edits are from you, help??

Anyway: Data loans are the only type of loan which related to cataloged items rather than parts, and the tools which work on one generally won't work on the other.

**Comment by Jegelewicz** [comment]
> doc edits are from you, help??

I was the editor, but that stuff came from a bunch of work by @ccicero and others.

https://docs.google.com/drawings/d/1Zs4IoCzJJ2ymbSrm3NIC6ZzWdmw421mIMTO4HlSpxHY/edit

Give me an idea what needs to be changed. @wellerjes did you read through this? What led you astray?

**Comment by wellerjes** [comment]
I did not, but this is super useful. I misunderstood above; I was thinking data within a loan (along the lines of data entry, what we're entering into the form) vs. a loan of specific information.

**Comment by dustymc** [comment]
done?
