### ISSUE TITLE
Feature Request - Annotation Type

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5492]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
Reviewing annotations is overwhelming. I can filter annotations by origin (record, taxonomy, project, publication, media), but I would like to be able to filter them by labels. 

**Describe what you're trying to accomplish** 
@ArctosDB/diversity-and-inclusion would like to be able to find all annotations related to harmful content so that in the future, we can address issues important to the committee.

**Describe the solution you'd like**
An addition to annotations that requires the person submitting the annotation to select a basic reason for the annotation. We would need a code table to create the list of "annotation labels".

First items in the "annotation label" vocabulary (please add others that are distinct and useful!)

harmful content - this annotation concerns derogatory, racist, or other sensitive terms
agents - this annotation concerns information about people or organizations
other - none of the defined annotation labels apply

**Describe alternatives you've considered**
I don't know that we have one right now!

**Additional context**

Add a field to this form: annotation label, types will come from a controlled vocabulary.

![image](https://user-images.githubusercontent.com/5725767/213028642-36f87938-678f-485a-a4f9-6c4515a6c25f.png)

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by dustymc** [comment]
Annotations started out in categories, and it just resulted in barriers - users do not pick what you wish they'd have picked, if they ignore it then you have to as well, it just adds clutter.

Annotations are also public and permanent, which might not inspire discussion of harmful content.

Tentatively suggest the Committee provide some sort of platform (maybe already has?), and we add some sort of alternate "click to discuss harmful content" link to it in the annotations form.

**Comment by Jegelewicz** [comment]
@ArctosDB/diversity-and-inclusion see above.

**Comment by AJLinn** [comment]
> Annotations are also public and permanent, which might not inspire discussion of harmful content.

Thanks for reminding us about that point Dusty. On one hand I agree that folks should feel free to discuss their issues in a less-public forum. However, the whole point we're making is that this information is already public and we want to make it better for others and so the public accountability of having it documented regarding how we dealt with it is sort of appealing.

That said, I think that all the other museums that I've found examples send folks to a dedicated email address where concerns can be expressed so maybe that's the solution that's already in process - we include that new email address in the statement and get a dedicated link everywhere that sends an email to that address and the committee can review and bring issues to our monthly committee meetings to address.

**Comment by ewommack** [comment]
Email set-up: https://github.com/ArctosDB/internal/issues/230

**Comment by ewommack** [comment]
DUI committee met today and decided that we would like to use @dustymc suggestion of a popup that appears in the Annotation window.

So @dustymc could we please add to the top of the window that opens when you click the make an annotation for this record button, text that says "to contact the Arctos DUI Committee to discuss harmful content please send an email to dei_contact@ instead of adding an annotation here"

**Comment by Jegelewicz** [comment]
@ewommack what does DUI stand for? (Seriously, I don't know!).

I think I would prefer this text.

To report harmful content please send an email to dei_contact@ instead of adding an annotation here.

**Comment by dustymc** [comment]
>dei_contact@

??

And I'm with @Jegelewicz , I was just (unsuccessfully, unless this is an attempt at [blatant trademark infringement](https://trademarks.justia.com/907/28/dui-diversity-unity-90728466.html)!) trying to figure out what the heck DUI means in this context....

Ping me when there's solid verbiage, I guess....

**Comment by Jegelewicz** [comment]
Maybe this is better?

![image](https://github.com/ArctosDB/arctos/assets/5725767/ee6911ba-1f57-433b-bc62-b607c6d8f44d)

So just add at the top:

> If you are uncomfortable reporting harmful content in public annotations please send an email to the [dei_contact@arctosdb.org](mailto:dei_contact@arctosdb.org) instead of adding an annotation here.

Because commenting publicly on this stuff might not feel comfortable.

**Comment by dustymc** [comment]
Changed "email to the" to "email to".

**Comment by ewommack** [comment]
Huzzah! Thank you @dustymc.
