### ISSUE TITLE
arctos logo constraints

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5493]
* only deal with local (via github) images. Round up anything that's at a URL and check it into github
* check size, limit to something reasonable
* check dimensions? Will be constrained in "collection header" - figure out what that is, add docs somewhere.

**Comment by mkoo** [comment]
These are all reasonable and necessary!

> * only deal with local (via github) images. Round up anything that's at a URL and check it into github
--> should also clean up old unused images here; happy to help here but the CSV from manage collection you sent will be the guide
> * check size, limit to something reasonable
 (right off the bat anything over 1 mb should be disallowed)
> * check dimensions? Will be constrained in "collection header" - figure out what that is, add docs somewhere.

**Comment by dustymc** [comment]
>1 mb 

!!!! I was horrified that one was 40-some K!

**Comment by mkoo** [comment]
that's what I mean -- a limit can be set now!

**Comment by dustymc** [comment]
I'll do this in a several steps. 

First, I'm pulling everything into a dedicated directory.

Second, I'll allow only files in that directory (and update the code and UI accordingly).

Soon, we'll recommend dimensions. (https://github.com/ArctosDB/arctos/issues/5333)

Eventually, I'll impose restrictions on filesize, current is below. (10KB seems sorta reasonable, should be plenty for an image this size and doesn't excessively punish those who pay for data.)

Even more eventually, I'll write scripts to purge unused images. (This is the reason for the dedicated directory.)

## Please let me know ASAP if you are using your header image anywhere other than the header!

I'm going to *move* images over the next couple days, any use outside the header will be broken soon-ish.

For next release, I've created a new folder /images/header in which I'll push/pull all existing images.

To use or update a header image going forward, you'll need to check it into GitHub - just open an Issue. 

Here's a directory listing with filesize.

-rw-r--r--  1 dlm  staff    65K Jan 19 07:07 54710047-7d933180-4b0c-11e9-9816-d013c681830d.jpg
-rw-r--r--@ 1 dlm  staff    44K Jan 19 07:29 ASNHC_Sq_4c_01_small.jpg
-rw-r--r--@ 1 dlm  staff    37K Jan 19 07:30 Lingnan_collection_Logo.JPG
-rw-r--r--@ 1 dlm  staff    36K Jan 19 07:27 CUMNH_logo_resized.jpg
-rw-r--r--  1 dlm  staff    31K Jan 19 07:12 chas.jpeg
-rw-r--r--@ 1 dlm  staff    22K Jan 19 07:29 AmasonUA2004_019_001_Arctos_banner_image_small.jpg
-rw-r--r--  1 dlm  staff    19K Jan 19 07:14 DMNS_3_Line_RGB.jpg
-rw-r--r--@ 1 dlm  staff    17K Jan 19 07:26 320px-University_of_Montana_logo.png
-rw-r--r--  1 dlm  staff    11K Jan 19 07:19 uamb_100px.jpg
-rw-r--r--  1 dlm  staff   8.6K Jan 19 07:16 KNWR_Ento_logo.gif
-rw-r--r--  1 dlm  staff   7.4K Jan 19 07:17 KNWR_Herb_logo_201106071602.gif
-rw-r--r--  1 dlm  staff   6.9K Jan 19 07:19 pika.gif
-rw-r--r--  1 dlm  staff   6.7K Jan 19 07:18 MVZ_fancy_logo.jpg
-rw-r--r--@ 1 dlm  staff   6.5K Jan 19 07:27 JSNM_Logo2.jpg
-rw-r--r--  1 dlm  staff   5.1K Jan 19 07:15 ethno4.jpg
-rw-r--r--@ 1 dlm  staff   4.6K Jan 19 07:28 nmmnhs_color_100_px.jpg
-rw-r--r--  1 dlm  staff   4.3K Jan 19 07:17 KWPHeaderIcon.gif
-rw-r--r--  1 dlm  staff   3.9K Jan 19 07:21 wasp.gif
-rw-r--r--  1 dlm  staff   3.8K Jan 19 07:16 flower2.gif
-rw-r--r--@ 1 dlm  staff   3.5K Jan 19 07:28 ACBC_logo_small.jpg
-rw-r--r--@ 1 dlm  staff   3.5K Jan 19 07:30 tn_10765704.jpg
-rw-r--r--  1 dlm  staff   3.1K Jan 19 07:21 UTEP-Logo-60px.jpg
-rw-r--r--  1 dlm  staff   3.1K Jan 19 07:20 UAMlogo.gif
-rw-r--r--  1 dlm  staff   2.0K Jan 19 07:18 MSB_trans2.gif
-rw-r--r--@ 1 dlm  staff   2.0K Jan 19 07:24 msb-dar-logo-small.jpg
-rw-r--r--  1 dlm  staff   1.9K Jan 19 07:11 Arctos-generic-header.png
-rw-r--r--  1 dlm  staff   1.8K Jan 19 07:20 USGSHeader.gif
-rw-r--r--  1 dlm  staff   1.7K Jan 19 07:22 wnmu.jpg
-rw-r--r--  1 dlm  staff   1.5K Jan 19 07:24 TTg6AyPQ.jpeg



TO REMOVE

images/54710047-7d933180-4b0c-11e9-9816-d013c681830d.jpg
images/Arctos-generic-header.png
images/chas.jpeg
/images/DMNS_3_Line_RGB.jpg
images/ethno4.jpg
images/flower2.gif
images/KNWR_Ento_logo.gif
images/KNWR_Herb_logo_201106071602.gif
images/KWPHeaderIcon.gif
images/MSB_trans2.gif
images/MVZ_fancy_logo.jpg
images/pika.gif
images/uamb_100px.jpg
images/UAMlogo.gif
images/USGSHeader.gif
images/UTEP-Logo-60px.jpg
images/wasp.gif
images/wnmu.jpg
/images/TTg6AyPQ.jpeg


From the web:

http://msb.unm.edu/divisions/amphibians-reptiles/_img/msb-dar-logo-small.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/University_of_Montana_logo.png/320px-University_of_Montana_logo.png
https://web.corral.tacc.utexas.edu/arctos-s3/cfilipek/2022-03-08/JSNM_Logo2.jpg
https://web.corral.tacc.utexas.edu/arctos-s3/ebraker/2020-06-18/CUMNH_logo_resized.jpg
https://web.corral.tacc.utexas.edu/arctos-s3/jegelewicz/2020-01-16/nmmnhs_color_100_px.jpg
https://web.corral.tacc.utexas.edu/arctos-s3/jegelewicz/2022-02-22/ACBC_logo_small.jpg
https://web.corral.tacc.utexas.edu/arctos-s3/jegelewicz/2022-04-21/ASNHC_Sq_4c_01_small.jpg
https://web.corral.tacc.utexas.edu/arctos-s3/krgomez/2022-10-27/AmasonUA2004_019_001_Arctos_banner_image_small.jpg
https://web.corral.tacc.utexas.edu/arctos-s3/lingnancollection/2020-08-21/Lingnan_collection_Logo.JPG
https://web.corral.tacc.utexas.edu/arctos-s3/thumbs/2023-01-17/tn_10765704.jpg

**Comment by Jegelewicz** [comment]
> TO REMOVE
and 
> From the web:

Will those just get moved to the new directory? Sorry if that is what you mean by "I will be moving files" but that just doesn't seem clear. And will we need to go into manage collection and change our images locations?

**Comment by dustymc** [comment]
Sorry for not being clear, this is all for me so far.

I've gathered everything up, I'll remove the then-unused from /images/ when I've made some code changes.

I will also update collections, no user action is required at this point (unless you're using something in /images/ outside the header), and this won't result in any visible changes. Same image, different (manageable) place.

I will ask for replacement images, but not until I have dimension recommendations.

**Comment by dustymc** [comment]
See https://github.com/ArctosDB/arctos/issues/5333#issuecomment-1397483696

Current inclination is to force all logos to 150PX height, but more feedback would be very appreciated.

**Comment by AJLinn** [comment]
I'd like to submit a new file for the same image (it's just the full image instead of the slightly cropped one). To clarify, 150px square at 72 dpi? And should I attach here or submit somewhere else?

**Comment by dustymc** [comment]
150PX high (or close enough that forcing it there won't get weird), width not so important but it will get cropped at 300px or something for mobile. Resolution and filesize are going to have to fight it out somewhere, but I don't know enough to say anything about that yet - try for "not huge" and we'll make it work for now. Just attach it here (or email me or whatever).

And I can swap out your current logo (should go out tonight, if I can get out of the hole I'm in at the moment) or add it alongside for testing or whatever - just let me know, and try to remind me to clean up when you're done if you need options for a while.

**Comment by AJLinn** [comment]
I tried to get this image file to fit your parameters but it keeps totally pixeling out. I'm attaching here what our museum designer reduced to a <1MB file. Maybe you can see what it does to the header/download speed for my records. I love that it's going to be bigger but by going bigger we compromise the quality of the custom image. I guess I could always drop the image and just go graphical but I love this and it's become our collection's Arctos identity. I don't know if @Emily or @mkoo have any suggestions as to the balance of quality vs quantity for custom headers?

![UA66-006-0002 2_150dpi](https://user-images.githubusercontent.com/17605945/213591756-23585d06-f63f-4b78-b33e-d289f7769791.jpg)

When I look at test, the old image is a blur, especially compared to the thumbnail of the actual photo below!
<img width="634" alt="Screenshot 2023-01-19 at 3 31 14 PM" src="https://user-images.githubusercontent.com/17605945/213592269-f2991154-6015-4047-9c88-0ee2cbb5ee26.png">

**Comment by dustymc** [comment]
@mkoo help?

>header/download speed 

I'm more concerned about load speed and data costs, and maybe I'm just being paranoid, or too paranoid. (I'm generally on vacation when I have to think about either of those things so don't really count, but I think we should at least attempt to build something that works in places where that's the norm.)

**Comment by mkoo** [comment]
![UAM_header_150h](https://user-images.githubusercontent.com/2523089/213614706-52b8e65f-f0c5-4500-bd3d-b4ca6f8ce2ac.jpg)

how does this look? Can I upload it somewhere for you to grab for Arctos or does this work?

@AJLinn if it does work, should the background color be dropped out?

**Comment by dustymc** [comment]
@Jegelewicz @mkoo  help!

Can we finalize the "will force to 150PX height" thing? (Still looks good to me, is in production and linked for Operators for easy checking.)

Width is device-dependent, but under 450PX is fine on desktop and around 250PX is OK on most mobile devices. Not sure how to form a recommendation out of that, but it also doesn't seem as critical.

The big problem is that we seem to have giant images, or blurry (at 150PX high) images, for most every collection. (Surely somewhere there's a giant yet blurry!) I think we should reach out to everyone, but I'd also like to help with the resize itself and I don't have the tools to do so. 

See also above, we need some kind of limitation on filesize but I'm not sure what's reasonable.  https://github.com/ArctosDB/arctos/issues/5493#issuecomment-1397895711 is 56K which seem crazyhuge, but my efforts resulted in 89K so....???? (I was thinking 10K would be about twice what's necessary so a nice easy bar to cross!)

I suspect many will want to change link color as well. That's shiny and new (in manage collection) and I'm not sure anyone knows about it.

**Comment by mkoo** [comment]
first, how does the UAM image look? does 150px h at 56kb work? can you live with that? I can try to go smaller kb but then there's the tradeoff with res etc...
We will have to redo a lot of header images-- they're just old and tired (lossy jpgs) so not a big deal. And I'm happy to do that (and I have help next week when my Arctos students are back)

I'm happy with a max height of 150px and then width can vary but with a max width so it doesnt run into the other links. Of course we should mention very wide images will interfere with mobile responsiveness so tread carefully. Max file size should really be that so say 60kb but recommend 40 or less. 

I need to be able to see this in action... what's the best way to pass some test images and see them on test (give me the URL please) @dustymc ?

**Comment by dustymc** [comment]
>can you live with that?

I can, but I'm not on a limited SIM card at the moment....

I say we run with it here, but it feels like it should be a bigger conversation, maybe for the SC?? 

>interfere with mobile responsiveness 

To be clear: It'll just chop off whatever won't fit (so sorta the other way around).

>see this in action.

I wired that one in "properly" but it'll still take a URL and isn't caching so you can edit a collection at test (https://arctos-test.tacc.utexas.edu/Admin/Collection.cfm) while reloading in another tab.

https://arctos-test.tacc.utexas.edu/guid/UAM:EH:UA2005-008-0003AB

<img width="1586" alt="Screenshot 2023-01-20 at 9 22 13 AM" src="https://user-images.githubusercontent.com/5720791/213763637-bfe1776b-d0aa-4b41-ab33-7244a4fcdf7a.png">

@AJLinn

**Comment by dustymc** [comment]
iphone

<img width="414" alt="Screenshot 2023-01-20 at 9 25 01 AM" src="https://user-images.githubusercontent.com/5720791/213764169-42b6e201-40fd-4297-a618-77e3b161a123.png">

**Comment by AJLinn** [comment]
> how does this look? Can I upload it somewhere for you to grab for Arctos or does this work?
> 
> @AJLinn if it does work, should the background color be dropped out?

LOVE it! Looks like there's enough detail at the larger size on the new page. 
Can you see what it looks like with the background color dropped out? Might be tough with the tassels...Go for it if you can make it look nice!

**Comment by mkoo** [comment]
tried a few different methods to allow for transparency, size etc (note to self: degrading to 8 bit is too much of a color drain but saves a ton of kb (3x) UNLESS you apply 128 color dither then it's best of both worlds-- look for PS presets or custom save)

result is 130h transparent background at 23 kb-- does this work?

![UAM_header_xbg2](https://user-images.githubusercontent.com/2523089/213881732-9ad637a9-3c32-4cac-a81a-5a838fe07194.png)

**Comment by AJLinn** [comment]
> result is 130h transparent background at 23 kb-- does this work?

Looks pretty good to me here and much better than anything we came up with to achieve a smaller file size.

**Comment by dustymc** [comment]
Very nice on all counts, screenshot in https://github.com/ArctosDB/arctos/issues/5333 or https://arctos-test.tacc.utexas.edu/SpecimenDetailResponsive.cfm?collection_object_id=23821087

**Comment by mkoo** [comment]
> Very nice on all counts, screenshot in #5333 or https://arctos-test.tacc.utexas.edu/SpecimenDetailResponsive.cfm?collection_object_id=23821087

woo! Looks good
> 
> See also notes on size over there - moving the collection and institution links means I need stretch the logo only to 100POX height, which works lots better with existing logos.

I think we will have to rework many if not all logos actually-- as I mentioned in some other issue, many of the logos are pretty old and lossy so wouldnt hurt to redo them

100-130px seems good to me

Can you please remove underline on links ? It might have to be done on all the behavours (not sure really) but something like (or maybe only have it appear on hovering -- so ignore the a:hover line):

```
a:link {text-decoration: none;}

a:visited {text-decoration: none;}

a:hover {text-decoration: underline;}

a:active {text-decoration: underline;}

```

Thanks!

**Comment by dustymc** [comment]
>rework many 

Sure, but the look isn't so drastic with less resizing.

>underline

Done, I think - let me know if I missed anything obvious and I'll open an Issue....

**Comment by dustymc** [comment]
@AJLinn your transparent logo is in production, you can manage collection and change HEADER_IMAGE to  ``/images/header/uamehlogotransparent.png`` (or let me know and I'll do it).

I ~~desecrated~~ added HEADER_CREDIT to ALMNH:Inv if anyone wants to see how that looks - https://arctos-test.tacc.utexas.edu/SpecimenDetailResponsive.cfm?collection_object_id=29511292

**Comment by mkoo** [comment]
while I think the padding/margin issues are addressed, and credit is better with the small font, your spelling has deteriorated.
Also what about hyperlinking the image?!

**Comment by AJLinn** [comment]
Now THAT is what I call a Banner notification! Wow...
And my new header image is bee-you-tiful! Thanks.

**Comment by ewommack** [comment]
@dustymc we could have banner quote day! That might be fun.

**Comment by mkoo** [comment]
hah! I added the Melville opening lines to see really how much text we were allowed-- a lot!

Also, UAM:EH does look good now!

@dustymc in test the banner field is back in the giant global admin page-- I like it in the standalone manage_banner edit page. Which will it be in new prod?

**Comment by mkoo** [comment]
> hah! I added the Melville opening lines to see really how much text we were allowed-- a lot!
> 
> Also, UAM:EH does look good now!
> 
> @dustymc in test the banner field is back in the giant global admin page-- I like it in the standalone manage_banner edit page. Which will it be in new prod?

oh wait I think I add that myself in Manage Directory...

**Comment by dustymc** [comment]
>pelling has deteriorated.

NEVER!

>what about hyperlinking the image?!

OMG still takes me more than zero minutes to do stuff! But not that much more, it's running in test now.

QUESTION: what should the target be? It's currently default, I'm tempted to make it open in a new tab.

>banner quote day! 

No, would not be fun - I just copypasta nonsense, @mkoo used like words and stuff.

>standalone manage_banner

global_settings.cfm?action=manageBanner is safe-ish.

global_settings.cfm is as far from safe as any tool can get.

>add that myself

Yep!

**Comment by dustymc** [comment]
@mkoo and future me: I shuffled the manage collection page around a bit and left instructions about images and directories, but it's still free-text. Should I go ahead with changing everything and making that into a pick list now, or would waiting a bit make things easier for you?

**Comment by mkoo** [comment]
Logging into test-- I like the new explanations and fields. You could make the input fields highlighted like you have on the other parts of manage_collection eventually (I will be more patient).

And if it could stay free-text while we get used to it a while longer at least on test, it would be helpful I think. 

I'll have more specific questions likely soon

**Comment by dustymc** [comment]
>highlighted

That indicates required - I don't think any of these are, but you can probably make weird stuff by nor reading the explanations.

>stay free-text while

No problem, let's just try to not close this until that's all wrapped up.

**Comment by Jegelewicz** [comment]
> Explanations

Can we at least make these appear consistent with the "explanations" in the left-hand column?

![image](https://user-images.githubusercontent.com/5725767/214654129-af7db524-5d59-4962-8b6e-b7d18f758997.png)

**Comment by Jegelewicz** [comment]
@dustymc before this happens, can we notify people who are going to lose a logo? (Is anyone losing a logo?)

Let me know if I can help preserve any of these or pester people to bring better files.

**Comment by dustymc** [comment]
Nobody's losing anything, the rules are very relaxed at the moment, @mkoo  is on a logomaking crusade, there's never been a better time to update! Checking things into /images/header/ would be nice but I'll pull from wikipedia or WHATEVER too, not a big deal. Pester away!

**Comment by Jegelewicz** [comment]
I don't really have time to look around and pester people, so perhaps I'll just wait until people complain.

**Comment by jldunnum** [comment]
Here is one for MSB. Could you resize to whatever you need and try it out in test to see if it works? Thanks!

______________________________________________________________

Jonathan L. Dunnum Ph.D. (he, him, his)
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

Chair, Systematic Collections Committee, American Society of Mammalogists
Latin American Fellowship Committee, ASM

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by mkoo** [comment]
Hey @jldunnum please email me directly at my berkeley address-- attachment did not go through the GH issue. Happy to help!

**Comment by mkoo** [comment]
> I don't really have time to look around and pester people, so perhaps I'll just wait until people complain.

no worries Teresa. I have a list of collections that I am going through-- send complaints my way or they can wait. It's also become a test of the contact list....

**Comment by Jegelewicz** [comment]
I already emailed @mvzhuang beacuse the current UTEP logo is too small (pixelated).

**Comment by mvzhuang** [comment]
@Jegelewicz i think...i lost that email because i saw it..but can't find it.
@dustymc when i resized it to 150px in ht, it was 30 kb. Does that sound ok? Attaching the one i got from the thumbnail maker at 8kb but it looks a bit pixely to me still.


![UTEP_logos_full_color_tn](https://user-images.githubusercontent.com/38706617/215892360-8c197958-14be-466d-95fa-f8fe06567540.jpg)
![UTEPLogo30](https://user-images.githubusercontent.com/38706617/215892421-31cd5096-5cd9-4e4e-a9e8-03159aaf7884.png)

**Comment by dustymc** [comment]
@mvzhuang I'm not sure what's reasonable. I'd say goferit - we can always swap a smaller one in later??

I checked that one in as  images/header/utep_logo.png, it should go to production later tonight.

@mkoo ?

**Comment by mkoo** [comment]
I've been shooting for something in the 20s kb so 30 is ok.
Which do you prefer? logo with black or transparent background? Depends on what the banner color will be.
If you want to work with the pixelly one, you can email me the largest version you have and I can reduce with PS magic to something more appropriate.. Just wrapped up Burke and UNM  so on a roll!

**Comment by mvzhuang** [comment]
I think the transparent background works. I might fiddle with the banner colors later, but at least this is functional
![image](https://user-images.githubusercontent.com/38706617/216142206-2b422b23-e1ec-4e74-9b86-6b8bc9dad46a.png)

**Comment by dustymc** [comment]
@mkoo can I move these to github and create the rules now?

```
select guid_prefix,header_image from cf_collection 
inner join collection on cf_collection.collection_id=collection.collection_id
where coalesce(header_image,'') != ''  and header_image not like '/%'
order by guid_prefix,header_image;



    guid_prefix    |                                                        header_image                                                         
-------------------+-----------------------------------------------------------------------------------------------------------------------------
 ALMNH:Anc         | http://arctos.database.museum/images/TTg6AyPQ.jpeg
 ALMNH:Arc         | http://arctos.database.museum/images/TTg6AyPQ.jpeg
 ALMNH:Bird        | http://arctos.database.museum/images/TTg6AyPQ.jpeg
 ALMNH:EH          | http://arctos.database.museum/images/TTg6AyPQ.jpeg
 ALMNH:Ento        | http://arctos.database.museum/images/TTg6AyPQ.jpeg
 ALMNH:ES          | http://arctos.database.museum/images/TTg6AyPQ.jpeg
 ALMNH:Geo         | http://arctos.database.museum/images/TTg6AyPQ.jpeg
 ALMNH:Herp        | http://arctos.database.museum/images/TTg6AyPQ.jpeg
 ALMNH:Inv         | http://arctos.database.museum/images/TTg6AyPQ.jpeg
 ALMNH:Mamm        | http://arctos.database.museum/images/TTg6AyPQ.jpeg
 ALMNH:Paleo       | http://arctos.database.museum/images/TTg6AyPQ.jpeg
 ASNHC:Bird        | https://web.corral.tacc.utexas.edu/arctos-s3/jegelewicz/2022-04-21/ASNHC_Sq_4c_01_small.jpg
 ASNHC:Herb        | https://web.corral.tacc.utexas.edu/arctos-s3/jegelewicz/2022-04-21/ASNHC_Sq_4c_01_small.jpg
 ASNHC:Herp        | https://web.corral.tacc.utexas.edu/arctos-s3/jegelewicz/2022-04-21/ASNHC_Sq_4c_01_small.jpg
 ASNHC:Mamm        | https://web.corral.tacc.utexas.edu/arctos-s3/jegelewicz/2022-04-21/ASNHC_Sq_4c_01_small.jpg
 ASNHC:Para        | https://web.corral.tacc.utexas.edu/arctos-s3/jegelewicz/2022-04-21/ASNHC_Sq_4c_01_small.jpg
 DGR:Mamm          | https://raw.githubusercontent.com/ArctosDB/arctos/master/images/MSB%20logo_xbg_v2_150.png
 DMNS:Bird         | https://web.corral.tacc.utexas.edu/arctos-s3/acdoll/2023-02-01/DMNS_3_Line_RGB_border_small.jpg
 DMNS:Egg          | https://web.corral.tacc.utexas.edu/arctos-s3/acdoll/2023-02-01/DMNS_3_Line_RGB_border_small.jpg
 DMNS:Herp         | https://web.corral.tacc.utexas.edu/arctos-s3/acdoll/2023-02-01/DMNS_3_Line_RGB_border_small.jpg
 DMNS:Inv          | https://web.corral.tacc.utexas.edu/arctos-s3/acdoll/2023-02-01/DMNS_3_Line_RGB_border_small.jpg
 DMNS:Mamm         | https://web.corral.tacc.utexas.edu/arctos-s3/acdoll/2023-02-01/DMNS_3_Line_RGB_border_small.jpg
 DMNS:Para         | https://web.corral.tacc.utexas.edu/arctos-s3/acdoll/2023-02-01/DMNS_3_Line_RGB_border_small.jpg
 JSNM:Egg          | https://web.corral.tacc.utexas.edu/arctos-s3/cfilipek/2022-03-08/JSNM_Logo2.jpg
 JSNM:Herb         | https://web.corral.tacc.utexas.edu/arctos-s3/cfilipek/2022-03-08/JSNM_Logo2.jpg
 JSNM:Paleo        | https://web.corral.tacc.utexas.edu/arctos-s3/cfilipek/2022-03-08/JSNM_Logo2.jpg
 LINGU:Herp        | https://web.corral.tacc.utexas.edu/arctos-s3/lingnancollection/2020-08-21/Lingnan_collection_Logo.JPG 
 MSB:Bird          | https://raw.githubusercontent.com/ArctosDB/arctos/master/images/MSB%20logo_xbg_v2_150.png
 MSB:Fish          | https://raw.githubusercontent.com/ArctosDB/arctos/master/images/MSB%20logo_xbg_v2_150.png
 MSB:Herp          | https://raw.githubusercontent.com/ArctosDB/arctos/master/images/MSB%20logo_xbg_v2_150.png
 MSB:Host          | https://raw.githubusercontent.com/ArctosDB/arctos/master/images/MSB%20logo_xbg_v2_150.png
 MSB:Mamm          | https://raw.githubusercontent.com/ArctosDB/arctos/master/images/MSB%20logo_xbg_v2_150.png
 MSBObs:Herp       | http://msb.unm.edu/divisions/amphibians-reptiles/_img/msb-dar-logo-small.jpg
 MSBObs:Mamm       | https://raw.githubusercontent.com/ArctosDB/arctos/master/images/MSB%20logo_xbg_v2_150.png
 MSB:Para          | https://raw.githubusercontent.com/ArctosDB/arctos/master/images/MSB%20logo_xbg_v2_150.png
 MVZ:Arch          | https://raw.githubusercontent.com/ArctosDB/arctos/0e4f66dc38cea5cac22902067ebb2d4d477bc68a/images/MVZ_logo_color.png
 MVZ:Bird          | https://raw.githubusercontent.com/ArctosDB/arctos/0e4f66dc38cea5cac22902067ebb2d4d477bc68a/images/MVZ_logo_color.png
 MVZ:Egg           | https://raw.githubusercontent.com/ArctosDB/arctos/0e4f66dc38cea5cac22902067ebb2d4d477bc68a/images/MVZ_logo_color.png
 MVZ:Fish          | https://raw.githubusercontent.com/ArctosDB/arctos/0e4f66dc38cea5cac22902067ebb2d4d477bc68a/images/MVZ_logo_color.png
 MVZ:Herp          | https://raw.githubusercontent.com/ArctosDB/arctos/0e4f66dc38cea5cac22902067ebb2d4d477bc68a/images/MVZ_logo_color.png
 MVZ:Hild          | https://raw.githubusercontent.com/ArctosDB/arctos/0e4f66dc38cea5cac22902067ebb2d4d477bc68a/images/MVZ_logo_color.png
 MVZ:Img           | https://raw.githubusercontent.com/ArctosDB/arctos/0e4f66dc38cea5cac22902067ebb2d4d477bc68a/images/MVZ_logo_color.png
 MVZ:Mamm          | https://raw.githubusercontent.com/ArctosDB/arctos/0e4f66dc38cea5cac22902067ebb2d4d477bc68a/images/MVZ_logo_color.png
 MVZObs:Bird       | https://raw.githubusercontent.com/ArctosDB/arctos/0e4f66dc38cea5cac22902067ebb2d4d477bc68a/images/MVZ_logo_color.png
 MVZObs:Fish       | https://raw.githubusercontent.com/ArctosDB/arctos/0e4f66dc38cea5cac22902067ebb2d4d477bc68a/images/MVZ_logo_color.png
 MVZObs:Herp       | https://raw.githubusercontent.com/ArctosDB/arctos/0e4f66dc38cea5cac22902067ebb2d4d477bc68a/images/MVZ_logo_color.png
 MVZObs:Mamm       | https://raw.githubusercontent.com/ArctosDB/arctos/0e4f66dc38cea5cac22902067ebb2d4d477bc68a/images/MVZ_logo_color.png
 NHSM:Geol         | https://web.corral.tacc.utexas.edu/arctos-s3/thumbs/2023-01-17/tn_10765704.jpg
 NMMNH:Bird        | https://web.corral.tacc.utexas.edu/arctos-s3/jegelewicz/2020-01-16/nmmnhs_color_100_px.jpg
 NMMNH:Ento        | https://web.corral.tacc.utexas.edu/arctos-s3/jegelewicz/2020-01-16/nmmnhs_color_100_px.jpg
 NMMNH:Fish        | https://web.corral.tacc.utexas.edu/arctos-s3/jegelewicz/2020-01-16/nmmnhs_color_100_px.jpg
 NMMNH:Geol        | https://web.corral.tacc.utexas.edu/arctos-s3/jegelewicz/2020-01-16/nmmnhs_color_100_px.jpg
 NMMNH:Herb        | https://web.corral.tacc.utexas.edu/arctos-s3/jegelewicz/2020-01-16/nmmnhs_color_100_px.jpg
 NMMNH:Herp        | https://web.corral.tacc.utexas.edu/arctos-s3/jegelewicz/2020-01-16/nmmnhs_color_100_px.jpg
 NMMNH:Inv         | https://web.corral.tacc.utexas.edu/arctos-s3/jegelewicz/2020-01-16/nmmnhs_color_100_px.jpg
 NMMNH:Mamm        | https://web.corral.tacc.utexas.edu/arctos-s3/jegelewicz/2020-01-16/nmmnhs_color_100_px.jpg
 NMMNH:Paleo       | https://web.corral.tacc.utexas.edu/arctos-s3/jegelewicz/2020-01-16/nmmnhs_color_100_px.jpg
 UAM:Art           | https://web.corral.tacc.utexas.edu/arctos-s3/krgomez/2023-01-20/AmasonUA2004_019_001_Arctos_banner_image.jpg
 UCM:Bird          | https://web.corral.tacc.utexas.edu/arctos-s3/ebraker/2020-06-18/CUMNH_logo_resized.jpg
 UCM:Egg           | https://web.corral.tacc.utexas.edu/arctos-s3/ebraker/2020-06-18/CUMNH_logo_resized.jpg
 UCM:Fish          | https://web.corral.tacc.utexas.edu/arctos-s3/ebraker/2020-06-18/CUMNH_logo_resized.jpg
 UCM:Herp          | https://web.corral.tacc.utexas.edu/arctos-s3/ebraker/2020-06-18/CUMNH_logo_resized.jpg
 UCM:Mamm          | https://web.corral.tacc.utexas.edu/arctos-s3/ebraker/2020-06-18/CUMNH_logo_resized.jpg
 UCM:Obs           | https://web.corral.tacc.utexas.edu/arctos-s3/ebraker/2020-06-18/CUMNH_logo_resized.jpg
 UWBM:Herp         | https://raw.githubusercontent.com/ArctosDB/arctos/0e10205837dc500b90e4b52c039fac99fa649a43/images/burke-logo-social_120.png
 UWBM:IP           | https://raw.githubusercontent.com/ArctosDB/arctos/0e10205837dc500b90e4b52c039fac99fa649a43/images/burke-logo-social_120.png
 UWBM:Mamm         | https://raw.githubusercontent.com/ArctosDB/arctos/0e10205837dc500b90e4b52c039fac99fa649a43/images/burke-logo-social_120.png
 UWBM:MET          | https://raw.githubusercontent.com/ArctosDB/arctos/0e10205837dc500b90e4b52c039fac99fa649a43/images/burke-logo-social_120.png
 UWBM:MINERAL      | https://raw.githubusercontent.com/ArctosDB/arctos/0e10205837dc500b90e4b52c039fac99fa649a43/images/burke-logo-social_120.png
 UWBM:PaleoArchive | https://raw.githubusercontent.com/ArctosDB/arctos/0e10205837dc500b90e4b52c039fac99fa649a43/images/burke-logo-social_120.png
 UWBM:PB           | https://raw.githubusercontent.com/ArctosDB/arctos/0e10205837dc500b90e4b52c039fac99fa649a43/images/burke-logo-social_120.png
 UWBM:VP           | https://raw.githubusercontent.com/ArctosDB/arctos/0e10205837dc500b90e4b52c039fac99fa649a43/images/burke-logo-social_120.png
(72 rows)
```

**Comment by mkoo** [comment]
Ok to do now as long as you dont mind doing it again in a few months. I am working with and reaching out to several collections which are featuring a blank banner. Thanks!
