### ISSUE TITLE
bulkloader data @barke042

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#5494]
Catalog bulkloader data attached (these were left in the catalog bulkloader, thus preventing others from using).
[bulkloader_stage(2).csv.zip](https://github.com/ArctosDB/arctos/files/10441396/bulkloader_stage.2.csv.zip)

**Comment by Jegelewicz** [comment]
@DerekSikes please proceed and thanks for leaving the .csv

@barke042 if you are looking for what was left in the bulkloader, it is attached above!

**Comment by barke042** [comment]
Nope I was done with it, thanks.
