### ISSUE TITLE
Arctos is in error mode

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#5495]
It must've been the screenshots I was in the midst of taking.. seriously I was just browsing pages and not editing but now have this: 
![Firefox_Screenshot_2023-01-18T06-56-33 705Z](https://user-images.githubusercontent.com/2523089/213104670-dd36e7c0-8e71-42f0-a404-bcd753f40e0b.png)
here's the error in the above screenshot:
 3B08C461-E117-4964-A5F6FEC8B1D860ED

Reboot please!

**Comment by dustymc** [comment]
Its the usual, a tremendous amount of garbage traffic compounded by Arctos working hard to refresh flat. It was plugged up enough that your request wasn't logged, along with who knows what else.

I had to take the front end down briefly to flush out the toobs, I think it's all happy now.

https://github.com/ArctosDB/internal/issues/229
