### ISSUE TITLE
Feature Request - Add link for acknowledgment of harmful content to manage collection

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5496]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
As part of the new interface development, a link to the new Arctos Acknowledgment of Harmful Content (under review) will be added to the site-wide footer for arctos.database.museum. In addition a link will be made available in the site-wide main menu under the Help options.

**Describe what you're trying to accomplish** 
Some collections may want the acknowledgement to be more prominent OR to provide one of their own.

**Describe the solution you'd like**
Add link and link text fields for content warning. The link text will appear in all of the collection's record headers along with license, terms, etc.

**Describe alternatives you've considered**
Creating pop-ups

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by dustymc** [comment]
I don't think this is controversial, except...

>OR to provide one of their own.

That's a bit like https://github.com/ArctosDB/arctos/issues/5493 in that Arctos is growing and we should possibly have some control over this sort of thing. The content of your policy isn't the concern of Arctos, but the possibility that the domain on which it is hosted might be taken over by something that'll greatly expand everyone's idea of 'harmful content' might be. I don't know how to deal with that (limit hosting to arctosdb.org?), and maybe it's just not a valid concern. @mkoo ?

**Comment by Jegelewicz** [comment]
But this is how we do loan policies - so....

**Comment by Jegelewicz** [comment]
I really don't see the huge issue and this goes for the logos too.

Could it be misused? sure - anything can! And if we actually get [Universal Global access for all collections](https://docs.google.com/document/d/1fD0MTvzlRR5ru0wClKIIGL9LazgEvI05RjuB-LT5KyE/edit#heading=h.w6edd3e9o174) in Arctos set up, then we can manage it too.

**Comment by dustymc** [comment]
>how we do loan policies

Yes, and using our dicey data to justify more dicey data is not a viable approach. We identified a potential problem in a meeting yesterday, we should not let that pile up until it becomes an emergency.

>Universal Global access for all collections

There are a few of us with this, I still don't understand the problem nor what it has to do with this.

**Comment by ewommack** [comment]
Since we're talking about placement for the Acknowledgement statement, I'm going to share the hard work @AJLinn did to compile examples from other types of institutions on placement:

> See standalone document for a number of examples of leading  ethnographic/anthropological museums and their statements [https://docs.google.com/document/d/1vjrJ-flqIjJccqUbOQ4l5pFD77d8Z1CX58T0xl4JgDM/edit?usp=sharing](https://www.google.com/url?q=https://docs.google.com/document/d/1vjrJ-flqIjJccqUbOQ4l5pFD77d8Z1CX58T0xl4JgDM/edit?usp%3Dsharing&sa=D&source=docs&ust=1674076618900362&usg=AOvVaw1rUFnTTqwNDOq1EEHUWGep) 
> Lots of libraries & archives, as well as museums

**Comment by dustymc** [comment]
Techy-bits aside: Would anyone who runs a collection use this, or is the Arctos-wide statement sufficient? @AJLinn @krgomez ??

**Comment by AJLinn** [comment]
> Would anyone who runs a collection use this, or is the Arctos-wide statement sufficient

Are you asking if we might add our own institutional policy on harmful content and add that to our collection-specific header? If so, I'd likely use the Arctos one as the basis for proposing one at UAMN but I would keep the Arctos one on my header.

**Comment by dustymc** [comment]
@AJLinn there's not really any structural 'institution' in Arctos, so this would be by collection. Several collections can of course act as a group if they'd like....

Arctos doesn't particularly want any say in what you'd use this link and content for; mirroring the Arctos policy on your GUID pages would be a perfectly acceptable use.

The origins of this (at least in my brain) is that the idea of "we will do..." has come up a few times in various discussions. That just can't happen (at least not without a new round of MOUs and a very different way of seeing the world or something) - Arctos doesn't own any data, all "we" can really DO is an acknowledgement. (That's not the limit of what usually happens because we're all pretty good at working together, but Arctos still can't tell you to go duct-tape over that one part of that one thing that we find offensive...)

That's of course not necessarily true within a collection - you might respond in all sorts of different ways (or spell out why you can't, Arctos still doesn't care about content), this would give you a place to - well, whatever.

The "timeline" (complicating factor, anyway) is https://github.com/ArctosDB/arctos/issues/5493 - if we're going to add a link-line, it would be VERY good to know about it before we rebuild a bunch of logos because it might change what we want to do with them. If there's no interest in this, that would be good to know about as well.

**Comment by ewommack** [comment]
> The "timeline" (complicating factor, anyway) is https://github.com/ArctosDB/arctos/issues/5493 - if we're going to add a link-line, it would be VERY good to know about it before we rebuild a bunch of logos because it might change what we want to do with them. If there's no interest in this, that would be good to know about as well.

@dustymc and @AJLinn - would it be possible for collections to put in the link to the Arctos Acknowledgement for the spot in the collection record header? Something similar to how a lot of collections do for the "Terms" selection?

So we would put a place in the header for it to be, if collections have their own acknowledgement to link to they could, or they could choose to link to the Arctos one if they do not have their own yet?

**Comment by dustymc** [comment]
> would it be possible for collections to put in the link to the Arctos Acknowledgement for the spot in the collection record header? 

That's one usage of what's being proposed.

>e, if collections have their own acknowledgement 

Adding a second link seems overkill (and overload!) - just copy and paste from the source policy if your policy serves as an extension. I can't quite see how a second would be necessary, but now's the time to address that if I've confused myself somewhere along the line.

**Comment by ewommack** [comment]
> Adding a second link seems overkill (and overload!) - just copy and paste from the source policy if your policy serves as an extension. I can't quite see how a second would be necessary, but now's the time to address that if I've confused myself somewhere along the line.

Not a second link -> collections can link to their own terms of usage in their collection metadata, or they can select the Arctos Terms and Usage policy. So a link where you can select your own Acknowledgement or if you do not have one you can link to the Arctos Acknowledgement. If at a future date your collection comes up with their own, you can go into your collection metadata and change the link to go to your collection's own policy.

**Comment by dustymc** [comment]
>or

Thx, yep, I think we're on the same page. 

> select your own Acknowledgement or if you do not have one you can link to the Arctos Acknowledgement

Or you could select nothing - this isn't something that will be forced on anyone, just (potentially) there if a collection wants to use it.

So would anyone use this?

**Comment by mkoo** [comment]
@dustymc PLease update the submenu link on new arctos header so the
``` "[Acknowledgment of Harmful Content](https://arctosdb.org/acknowledgment-of-harmful-content)"```

Current link has the "mispelled" acknowledg**e**ment

**Comment by dustymc** [comment]
>Current link has the "mispelled" acknowledgement

fixed

**Comment by mkoo** [comment]
ready for new footer launch
