### ISSUE TITLE
Change wording - Bulkload Specimen Event to Bulkload Catalog Record Event

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#5497]
This page still uses "specimen":
https://arctos.database.museum/tools/BulkloadSpecimenEvent.cfm

Can we change to Catalog Record?

**Comment by Jegelewicz** [comment]
See also #4460

**Comment by dustymc** [comment]
I'm hesitant to break the implicit link between internal "advanced user" UI and eg the table browser. The table is clearly poorly named and I'm not defending anything, I'd just like to confuse people as little as possible and I think renaming/retitling this would confuse some users.

We really need a policy on this. Renaming database structures is a huge pain, but this particular table just keeps popping up and taking a week to rename and rebuild it and everything it touches might have actually saved some time. That's not the only possibility, but it might be the most radical and it's not seeming very radical at the moment. (Of course finding a spare week is a whole nuther matter.)

See also https://github.com/ArctosDB/arctos/issues/4707 - good opportunity to rename some stuff (hopefully not to something that'll need renamed in a bit!) in there.

**Comment by Jegelewicz** [comment]
> Renaming database structures is a huge pain

So we need to be careful when we create new ones? This seems to have been a somewhat ad-hoc adventure, but maybe we need to carefully consider what we name tables/fields going forward? See also #5326

**Comment by dustymc** [comment]
>careful when we create new ones?

Yes, that's the sort of thing the admin arm of Arctos should be dealing with (in a timely manner) so I don't have to. Or I could just name everything whatever generateUUID() spits out....

**Comment by Jegelewicz** [comment]
So - process matters here. We need a little time to consider these things and we have to get community input. Perhaps we need a request form just like we have for code tables. What do you need from us when a new field or table is added?

**Comment by Jegelewicz** [comment]
How about this?

/SpecimenDetailResponsive.cfm

instead could we have 

/RecordDetail.cfm

?

**Comment by dustymc** [comment]
>need a little time 

Yes, but there has to be some sort of linear progression to a finish. We get distracted, move on to the next thing, rope tangentially-related stuff in, etc., etc. That's probably all got to be considered, but it can't be a distraction either. IDK how to do that....

>What do you need 

Start with the policy. I sound like a broken record on that of late, but it's what matters. 

>How about this?

That's a temporary URL - it'll just be /guid/... (which is why I panicked a bit when it was suggested we keep the old stuff for a while yesterday - that and I can't clean up some things that desperately need cleaning while I have to keep the old stuff functional).

**Comment by ewommack** [comment]
@dustymc - the Diversity and Inclusion Committee would like to help develop and move forward the process of making the language and shared areas of the Arctos database more inclusive. 
We are not proposing changes or renaming things, but first want to understand where things are with the use of the word "specimen" across the website.

Could we start with a list of all of the places in Arctos (tables, column names, page names, fields, etc.) that use "specimen" in some way please? I know we've been changing a number of them for a bit (https://github.com/ArctosDB/arctos/issues/3780), but could we get material that is also behind the scenes that only you can see?

Once we have the list, the committee feels we'll have a better understanding of where we are using the word presently. Understanding would be a good place to start to figure out the best way to move forward. And hopefully not result in you having to change things piece-meal.

**Comment by ewommack** [comment]
Hi @dustymc - just checking if this might a possible ask? The committee would be happy to work on that list if we could get it.

**Comment by dustymc** [comment]
>material that is also behind the scenes that only you can see

I was under the very firm impression that behind-the-scenes stuff is not to be involved in this process.  @mkoo

**Comment by ewommack** [comment]
I probably used the wrong terms. Would it be possible to get a current list of all of the places in Arctos that use the term "specimen"?

No behind the scenes things, but not sure if this is possible in your magic @dustymc powers.

**Comment by Jegelewicz** [comment]
The first comment has been resolved and is now

https://arctos.database.museum/loaders/BulkloadSpecimenEvent.cfm

but looks like this

![image](https://github.com/ArctosDB/arctos/assets/5725767/2ffadb30-61c8-4e8e-b77f-e0bc4f259a37)
