### ISSUE TITLE
Agent Creation Question - same name as another person

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#5502]
I am creating an agent for a new project and eventual accession coming in and one of the researchers is named Michael Yates. There is already a Michael Yates in Arctos (https://arctos.database.museum/agents.cfm?agent_id=1012139), but I have double checked and they are not the same person. 
I'll make sure to add contact information, employment and associations to the newly created Michael Yates, as well as check for a middle initial or name that might be used for my agent. I'll also make sure to mark them as "not the same as"

However I wanted to check if there was anything else I'm missing for creating an Agent with the same name, but confirmed as not the same person?

**Comment by Jegelewicz** [comment]
@ewommack As far as I know you CANNOT create two agents with the same preferred name. @dustymc can confirm or deny. I feel that we should be able to do this now that we have given up all of our low-quality agents, but I don't think Dusty has made that possible at this point?

If not, what does Beth do now?

**Comment by dustymc** [comment]
>CANNOT create two agents with the same preferred name

Correct.

>what does Beth do now?

What the docs recommend, but perhaps that could be adjusted in light of current agent data. The existing agent made one ID, minimally I'd suggesting making the lowest-data agent the parenthetical. In this case, and maybe most cases, I'd then continue on to flagging them as a duplicate of unknown - there's no information in the agent record, or nearly so. Maybe a topic for the Committee.

>"not the same as"

FYI I intend to kill those, it's a super-cruddy replacement for the data we're now requiring.

**Comment by dustymc** [comment]
@jldunnum just that relationship is a great start, thanks.

**Comment by ewommack** [comment]
I've gotten a middle initial, so what I'm going to do is create Michael A. Yates, employee of Earthspan, associate of two other agents, with email and address. Will that be enough to allow creation of a separate agent?

**Comment by jldunnum** [comment]
Just looked and that relationship is already in there.

______________________________________________________________
Jonathan L. Dunnum Ph.D. (he, him, his)
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

Chair, Systematic Collections Committee, American Society of Mammalogists
Latin American Fellowship Committee, ASM

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131

**Comment by ewommack** [comment]
> Just looked and that relationship is already in there.

I'm not sure what you mean?

**Comment by jldunnum** [comment]
“Child of” Terry L. Yates

______________________________________________________________
Jonathan L. Dunnum Ph.D. (he, him, his)
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

Chair, Systematic Collections Committee, American Society of Mammalogists
Latin American Fellowship Committee, ASM

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131

**Comment by dustymc** [comment]
>relationship is already in there.

I added it.

>enough to allow creation

Yep, any one of those things plus a distinct preferred name will get you past the technical bits. The rest is interesting in that both have a fair bit of data now, but none of it's directly comparable. How sure are we that Terry's son didn't go on to work at Earthspan? (And maybe not being sure is OK, some future investigator is still going to have a lot more than strings to start with.)

**Comment by ewommack** [comment]
> How sure are we that Terry's son didn't go on to work at Earthspan? (And maybe not being sure is OK, some future investigator is still going to have a lot more than strings to start with.)

I asked my Michael Yates, and he says nope that is not me. You need a button that I can click that says "I spoke with this agent and he says he is not this other person".

**Comment by Jegelewicz** [comment]
@ewommack I would add that in the internal remarks....

**Comment by dustymc** [comment]
>he says nope that is not me.

OH! Woohoo/crud, doesn't get any better than that, but there goes my plans to just outright kill "not the same as" relationship - it's exactly the right tool for this job. I wonder if we can somehow do better with the 'according to whom' bits (eg in https://github.com/ArctosDB/arctos/issues/5172) - relationships asserted by agents participating in the relationship get elevated, or certain kinds of relationships require some level of authoritativeness, or something of the sort?

**Comment by Jegelewicz** [comment]
See also #4534 and #5158

**Comment by ewommack** [comment]
>  relationships asserted by agents participating in the relationship get elevated, or certain kinds of relationships require some level of authoritativeness, or something of the sort?

You need a verified sticker like in locality.
I've flagged it "not the same as" as put it in remarks that I checked with Michael A. Yates that was not the same person, and then also added it in curatorial remarks. Thanks everyone for your help!
