### ISSUE TITLE
Nothing happens after log in

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5503]
When Arctos goes down, the first time I log in, I get expected behavior. I see the list of collections without an active collection contact, then when I continue I get the search page. Every time I log in after that I see this

![image](https://user-images.githubusercontent.com/5725767/213543613-9acc0a1a-c433-4333-ad40-64dc79a4f981.png)

I can close the log in pop-up, and select search catalog records and then everything works as expected.

Any idea why this "freeze" is happening?

**Comment by AJLinn** [comment]
This happens to me 99% of the time when I log in.

**Comment by dustymc** [comment]
Just more of https://github.com/ArctosDB/internal/issues/187, what we're trying to fix with all the active changes.

**Comment by Jegelewicz** [comment]
This is still happening.

**Comment by dustymc** [comment]
[yea](https://github.com/ArctosDB/internal/issues/187)
