### ISSUE TITLE
Arctos Down - 2022-01-19 11:44 am AST

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#5504]
Please complete to the best of your ability.

## Unplanned Outage
2022-01-19 11:44 am AST
getting a 500 error in Safari when I try to connect. Just spinning when trying to edit existing records that are open.

## Planned Outage
 - Date and time outage will begin:
 - Date and time outage is expected to end:
 - Reason for outage:
 - Expected behavior during and after the outage:

## Communication before/during outage
- [ ] Pin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG  
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by AJLinn** [comment]
<img width="1325" alt="Screenshot 2023-01-19 at 11 47 59 AM" src="https://user-images.githubusercontent.com/17605945/213556358-79be1835-28be-4638-ada5-67bf2a55c3ce.png">

**Comment by dustymc** [comment]
wiggled the wires
