### ISSUE TITLE
Part attribute editing funkiness

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#5505]
something is amiss in the part attribute editing process.

**Describe the bug**
When I create a new part attribute, sometimes it takes a while for it to save. It does nothing for ~10 seconds so I hit save again... then I end up with two new part attributes exactly the same.

<img width="1335" alt="Screenshot 2023-01-19 at 11 58 06 AM" src="https://user-images.githubusercontent.com/17605945/213558205-4490245d-dc55-4a6a-9e0f-3f445651ecd2.png">

Then I go to delete the one part attribute by clicking the delete button and nothing happens... for several minutes. I'll exit and then suddenly/magically it's deleted.
<img width="1335" alt="Screenshot 2023-01-19 at 12 00 21 PM" src="https://user-images.githubusercontent.com/17605945/213558510-6b696418-22d5-46a2-93d4-1a17427ac030.png">

This happened to me several times yesterday as I've been adding part attribute "condition report" on items returning from a loan. It's quite vexxing...  is it possibly connected to something else that's happening behind the curtain and I should just be more patient (ALA 1998 dial-up speed patient?)

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by dustymc** [comment]
>patient

I think so, but some other stuff that was slow isn't at the moment so maybe someone finally threw the right thing into the volcano...

Going next task; once the old header is no more I can rebuild those apps to something that'll handle network issues (or whatever) a little better.
