### ISSUE TITLE
Locked out of Test

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5506]
https://arctos-test.tacc.utexas.edu/  Test says it doesn't recognize my password. I reset, but no email is forthcoming. Please send temp password.

**Comment by dustymc** [comment]
Your Arctos username/password is jegelewicz / LwRdJ?%l77?1ERP You will be required to change your password after logging in. http://arctos-test.tacc.utexas.edu/login.cfm If you did not request this change, please immediately contact the DBA team.

**Comment by Jegelewicz** [comment]
Logged in and was immediately given this

![image](https://user-images.githubusercontent.com/5725767/213586981-8b4d5db6-784d-497b-9b13-8450d26d02a5.png)

ErrorID: 2DDDEF57-EE5C-404F-9A19E5086BC96D34
Mesasge: ERROR: permission denied for table api_pubusrallall_20230119110140615_830
Details:

**Comment by dustymc** [comment]
Yes, the user you became can't see the user you were's data.

**Comment by Jegelewicz** [comment]
Was I abducted by aliens and transformed?
