### ISSUE TITLE
give the part 2 container bulkloader more power

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5512]
**Is your feature request related to a problem? Please describe.**

The loader won't recontainerize parts because it's always been hard to identify parts. We now have partID everywhere, there's no ambiguity, we should drop the constraints.

**Describe what you're trying to accomplish** 

Specifically fix a problem for @DerekSikes but in general make things better.

**Describe the solution you'd like**

Drop the 'part is already in a container' check

**Describe alternatives you've considered**

delete and readd parts (thx @KyndallH )

**Additional context**

This does provide a path to make huge messes, collections should check training and access.

**Priority**

?

**Comment by campmlc** [comment]
I support this
