### ISSUE TITLE
Feature Request - manage agents for found catalog set - can we ADD ?

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#5513]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
I've got 27 cat records that need a collector agent added to them. The manage agents form appears to allow replacement of agents, but not addition of agents?

Can we get this form modified to allow one to add agents?

for my follow up - these are specimens in unit tray C49968 and the agent R. I. Sailer needs to be added a collector for each

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.
medium

**Comment by dustymc** [comment]
<img width="346" alt="Screenshot 2023-01-22 at 8 14 09 AM" src="https://user-images.githubusercontent.com/5720791/213926495-b2bb9986-a0a3-47db-bb8e-11780ac94a04.png">

**Comment by DerekSikes** [comment]
perfect! thanks
