### ISSUE TITLE
add the form Create Transaction to Tool Directory

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#5515]
I dont see **Create Accession** https://arctos.database.museum/accn.cfm?action=createForm available on the Tool Directory 

Also I would like to rename the category "Transactions" to "Accessions and Loans" for clarity on the Tools Directory. (added bonus, the tool box would no longer be at the bottom of everything)

Objections anyone?

**Comment by mkoo** [comment]
oh apologies -- it is there but doesnt have a title I think (so not visible). Let me see if I can edit that.
But the category name change is still a question!

**Comment by mkoo** [comment]
Fixed visibility by adding a link name: Create Accessions

**Comment by mkoo** [comment]
To be clear about my second part: this tool "box" would be renamed to "Accessions and Loans"
![Firefox_Screenshot_2023-01-21T22-18-07 281Z](https://user-images.githubusercontent.com/2523089/213889158-04385fe5-ee16-46cd-97b4-dfd51c553f57.png)

Let me know what you think

**Comment by campmlc** [comment]
Accessions, Loans, Permits.
I prefer the specific terms to the generic Transactions.

**Comment by campmlc** [comment]
And can we please, please get rid of " Bulkload Loan- like transactions"? It makes my eyes hurt trying to read the this and the submenus with all this extra verbiage. If it looks like a loan, call it a loan. Clear language that is easily sorted visually so you know where to click.
Put the terms in order by type: Accession Tools, Loan Tools, Permit Tools

**Comment by mkoo** [comment]
>Accessions, Loans, Permits.

I like this!

> And can we please, please get rid of " Bulkload Loan- like transactions"? It makes my eyes hurt trying to read the this and the submenus with all this extra verbiage. If it looks like a loan, call it a loan. Clear language that is easily sorted visually so you know where to click. 

"Bulkload Loans and other transactions" ? I never really understood why it said "Loan-like" but I assumed someone used if for something not technically a Loan...

>Put the terms in order by type: Accession Tools, Loan Tools, Permit Tools


Right now it's simple alphabetical order-- manual reordering is an extra management function that would have to be coded in. Can the ordering function be added to the management table @dustymc without a lot of fuss or issue? Otherwise we can file for a future iteration

**Comment by campmlc** [comment]
Can we change as follows, so they will sort into categories:
Accessions
Loans
Permits

And then under each Category, either in this drop-down or in the sub drop-down, have:

Accessions
     Bulkload Accessions
     Create Accessions
Loans
     Bulkload Data Loans
     Bulkload Data Loan Items
     Bulkload Loans
     Bulkload Loan Items
     Create Loan
     Loan Statistics 
Permits
     Create Permit
     Manage Permits

**Comment by dustymc** [comment]
I don't like lists - everyone's forgotten borrows, and even then this is contrary to https://github.com/ArctosDB/arctos/issues/4189 (which was agreed to but now nobody likes??).

>ordering

It would not be difficult to add, but I suspect it would be impossible to manage. Eg every time I create a new form (or a link to an existing "subform" or etc.) I'd have to figure out ordering, and I'd muck it up, or just use ++, or do SOMETHING that would ultimately result in more entropy than a straight sort. Don't think this is practical unless someone's willing to commit to helping me push every release out.

**Comment by dustymc** [comment]
Not also that the link is going to a part of the form without a handler. I made a new one via...

<img width="73" alt="Screenshot 2023-01-22 at 8 04 00 AM" src="https://user-images.githubusercontent.com/5720791/213926240-81b0fa51-95ef-46ba-ac40-35a5f76ebf92.png">

<img width="1524" alt="Screenshot 2023-01-22 at 8 05 36 AM" src="https://user-images.githubusercontent.com/5720791/213926249-b7c84f17-89d6-43c5-83eb-1a6ca1ca2786.png">

**Comment by campmlc** [comment]
So 
Accessions
Borrows
Loans
Permits

That's in alphabetical order

**Comment by campmlc** [comment]
Then we choose which one and get options. I don't like huge long lists of irrelevant options either. Bring allowed to choose which transaction type you want, and then go to a drop-down with relevant options, is what users need. Not a long, incomprehensible list.

**Comment by campmlc** [comment]
And deaccession can be an option under Accession. There's no problem here. What we need is an interface that users can understand, that does not confuse and impede.
