### ISSUE TITLE
[CONTACT: Blocked Network]

### ISSUE THREAD

**Issue by Iezik** [ArctosDB/arctos#5516]
Thank you for contacting Arctos with your issue. You may delete this note before typing your message. To best address your message, please include enough information to re-create the problem if your message involves a bug report on the database. Webpage links, steps you took, error messages, and screenshots are helpful. We promise to respond. If you prefer an email, contact us at arctoscontact@googlegroups.com

Hello, 
My ip was blocked for an unknown reason. From the error message from your site, it may be malware on my phone.
The main reason for this message is to enquire about ways to prevent this from happening in the future.
Ip address: 197.210.227.94

**Comment by dustymc** [comment]
released

**Comment by Iezik** [comment]
Thank you for your response
