### ISSUE TITLE
Code Table Request - estimated lot count

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#5521]
**Goal**
Distinguish between whether lot counts are estimated or actual counts. 

**Context**
Currently there is no way to say whether the part lot count is estimated or actual. This is important for ento collections per @DerekSikes. Adding a part attribute of 'estimated lot count' with a 'yes/no' value would solve this. Users can also add metadata such as who estimated the count and when, or who actually counted the number in the lot and when.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecpart_attribute_type

**Proposed Value**
estimated lot count - yes/no values

**Proposed Definition**
A part attribute that specifies whether the lot count is an estimated or actual count. Use 'yes' for estimated and 'no' for actual'.

**Attribute data type**
yes/no

**Attribute value**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctyes_no

**Available for Public View**
Yes

**Comment by campmlc** [comment]
Can we also then have actuallotcount as another part attribute? Because we
have thousands upon thousands of existing "lot counts =1" which are wrong,
and I need a way to record that a lot has been counted and by whom on what
date.

**Comment by dustymc** [comment]
>Can we also 

New Issue, please.

**Comment by ccicero** [comment]
I think that's confusing to have 'lot count' and separately 'actual lot count' - can we call it something that doesn't use the term 'lot'  - how about 'verified count' ?

**Comment by Jegelewicz** [comment]
This is so old it isn't using the correct request template. @ccicero do you still want this?
