### ISSUE TITLE
Arctos Down - 2023-01-23 3:30 MT

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#5522]
Please complete to the best of your ability.

## Unplanned Outage
 - 2023-01-23 3:30 MT
 - Arctos isn't loading. TACC seems to be down as well since my TACC media URL is also timing out.

## Communication before/during outage
- [x] Pin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG  
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [x] Unpin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by ebraker** [comment]
Back up @ 3:52pm MT

**Comment by dustymc** [comment]
It didn't go down for me and I don't see any major gaps in the logs, but the RStudio scripts are bashing around in there again (and there are more messages from @mlbowser regarding blocked networks) - if it wasn't your DNS or similar it could have been that.
