### ISSUE TITLE
Need Help with Arctos Error -> solution extra free spaces in free text field trips up error

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#5524]
@msaqib2
# Error Text
FAIL: outcatch - - ERROR: new row for relation "bulkloader" violates check constraint "ck_attribute_value_4_noprt":

# Where it happened
Attempting data entry from the data entry page, but not sure why it is catching. We got rid of attribute 4 and it still wouldn't let us enter the data.

# Steps to get there
bird record, for UWYMV:Bird:4279

# Problem
attempt save file and hit error record

# Solution
what am I doing wrong?

**Comment by dustymc** [comment]
Screenshot would be useful, but that should be unacceptable characters in attribute_value_4.

**Comment by ewommack** [comment]
Sorry @dustymc I'll try and grab one. We changed the text out and now got this error: 
Save rejected: FAIL: outcatch -  - ERROR: new row for relation "bulkloader" violates check constraint "ck_coll_object_remarks_noprt":

**Comment by ewommack** [comment]
<img width="2560" alt="Screen Shot 2023-01-23 at 4 32 48 PM" src="https://user-images.githubusercontent.com/18562884/214175873-68b7a137-0336-4442-acf6-ad0e1e4c3503.png">

**Comment by ewommack** [comment]
Ok we took out all text in the Object Remark field, but I can't figure out why it was catching an error in it. We just entered the same text in the field in the bulkload editor and it took it fine. Very confused.

**Comment by dustymc** [comment]
>ck_coll_object_remarks_noprt

That's specimen/record/whatever we call it remarks.

>figure out why 

https://handbook.arctosdb.org/documentation/understanding-errors.html

Extraneous spaces are also considered and can cause that kind of confusion.

**Comment by ewommack** [comment]
Ok. Maybe it was the extra spaces. We took the text out, saved it and then added it back in by typing it directly and it took. We'll say it was the extra spaces, and try again to make sure we do better. Thanks @dustymc

**Comment by ewommack** [comment]
And just checking, because I'm still trying to figure out what I did wrong:

An extraneous space is something like _ that? One extra space inbetween words?
Or would it be something like 
this where I got a return in on the end of a line?

**Comment by dustymc** [comment]
https://github.com/ArctosDB/PG_DDL/blob/master/function/checkFreeText.sql is authoritative. Leading, trailing, or double (or more) allowable whitespace characters, or any disallowed characters, which includes return, will trip the error.

**Comment by ewommack** [comment]
Ok, so I had it right. Extra spaces and extra following spaces will trip up PG_DDL in free text. So I must have added an extra space somewhere in the line of free text, and the best solution is to rewrite your text, or find the extra space.

I'll change the name of this Error with the solution so I can find again if I need to, and I'm closing this.

Thanks for the help and explanation @dustymc
