### ISSUE TITLE
Code Table Request - MGRS UTM zones need to be added to CT

### ISSUE THREAD

**Issue by barke042** [ArctosDB/arctos#5525]
**Add missing value to ctutm_zone**
Looking forward to adding our invertebrate data, the majority of records have UTM data, the majority of which are zones 14N and 15N. Currently only MGRS zones 14R, 14S, 15S, 15T, and 15U are listed in ctutm_zone.

**Context**
Our data are in actual UTM rather than MGRS and we have no convenient way to translate from one into the other.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctutm_zone

**Proposed Value**
14N, 15N

**Proposed Definition**
Definition is clear within the UTM system, see e.g. https://epsg.io/32615

**Available for Public View**
**Yes**

**Note**: I would guess that this addition would involve some code change involved in translating UTM to decimal degree coordinates. However, given the documentation [here](https://handbook.arctosdb.org/documentation/locality.html) versus [here](https://arctos.database.museum/tools/bulkloadLocality.cfm?action=ld), I'm not sure the status of that process.

**Comment by dustymc** [comment]
My only hesitation with this is https://github.com/ArctosDB/arctos/issues/5279 - apparently Arctos doesn't convert correctly,  I can't figure out why, and I haven't been able to successfully summon help. I'd like to not make a bigger mess of that, and I don't know if adding this would do that or not. @mkoo ??

**Comment by mkoo** [comment]
UTM conversions can be tricky (CRS and projection transformation); GIS is
most reliable way to do it of course... @dustymc does postgis have a GDAL
extension? (maybe it's installed together nowadays?).

OK I missed the earlier transformation issue so let me take a closer look.
But a quick read of the earlier issue is that those coordinates just need a
datum transformation (NAD27 to WGS84).

UTM is a CRS transformation and sometimes includes a datum change too.

Meanwhile Keith, if you need to batch convert a bunch of UTM's (WGS84) as
soon as possible, I have easy desktop tools to use, so please email me.

**Comment by mkoo** [comment]
btw just for fun can you run ST_Transform with from UTM 15N to long/lat (assuming WGS84)
https://epsg.io/transform#s_srs=32615&t_srs=4326&x=NaN&y=NaN

**Comment by dustymc** [comment]
I added these two, but please test them carefully, and hopefully we'll figure out what seems to be a bigger problem out in the other issue.

**Comment by barke042** [comment]
OK, thanks @dustymc . @mkoo would you suggest that I upload the data as is and then cross check the Arctos results with an independent transformation? I can do the conversion within QGIS using Lat Lon Tools. Or would you suggest I do the conversion locally and then just upload the decimal latitude and longitude? I guess the only downside to trying it out is that if things are off I would have to ask for an update query using the locally generated coordinates.

**Comment by dustymc** [comment]
>update query using the locally generated coordinates.

If there's any chance of that, please use named localities (or they're likely to be so mixed up by the time I get there that I'll just make a mess).

It's probably worth some sort of babysteps and broad review before the next tiny step process - let me know if I can help in some way.

**Comment by barke042** [comment]
Maybe it would be best to just upload a smallish subset of named localities with UTM data, cross-check with locally-generated latilongs, and then purge them if necessary prior to committing to a bulk upload?

**Comment by mkoo** [comment]
HI Keith, all the UTM zones are loaded now by datum-- so you need to select the zone and the datum (ie WGS84/ 10N or NAD27/10N)

I dont have all the MGRS zones yet and looking for a nice open reference/auth for that still. Let me know if you have any leads or can search the EPSG site more effectively. 

I'm updating the name of this issue to reflect what's left of the issue but the initial request is fulfilled!

**Comment by Jegelewicz** [comment]
@mkoo are we done here?
