### ISSUE TITLE
Print report issues

### ISSUE THREAD

**Issue by Cloveis** [ArctosDB/arctos#5531]
I am attempting to print specimen container labels, formerly found in the search "tools > print stuff > print any report".

 I haven't done this in a while and since the last time, the process must've changed as these fields aren't available anymore. Where can these print templates be found?

**Comment by mkoo** [comment]
To print labels, in the results section of the new interface, go to the dropdown Tools.
Tools--> Arctos Reporter will get you to the new reporter where you can select the legacy forms (still working of course; but let us know if it's not responding) or use one of the new ones if available for your collection.

**Comment by dustymc** [comment]
done?
