### ISSUE TITLE
new search FAQ

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5534]
Stuff from my inbox

# Type status

To search:
<img width="179" alt="Screenshot 2023-01-25 at 10 03 17 AM" src="https://user-images.githubusercontent.com/5720791/214645952-a3a8799e-8884-462d-aecd-a2ff5e8b1688.png">

then

<img width="1079" alt="Screenshot 2023-01-25 at 10 03 41 AM" src="https://user-images.githubusercontent.com/5720791/214645992-00865ff9-e435-44b3-a62d-8008ee796110.png">

and click any save button.

In Results:
<img width="186" alt="Screenshot 2023-01-25 at 10 05 10 AM" src="https://user-images.githubusercontent.com/5720791/214646118-f2d5d1ff-d708-4fd6-83f3-8e0afa0202d4.png">

then

<img width="1088" alt="Screenshot 2023-01-25 at 10 05 55 AM" src="https://user-images.githubusercontent.com/5720791/214646284-94fe7da7-a2d8-428f-8688-9831ab3ccac0.png">

(and optionally drag the row up or down to position the column within results)

**Comment by jldunnum** [comment]
Thanks!

**Comment by dustymc** [comment]
# Summarize Results

Perform a search that returns results, then

<img width="381" alt="Screenshot 2023-01-25 at 10 08 09 AM" src="https://user-images.githubusercontent.com/5720791/214646746-2a80d61d-c95c-4ae7-979f-769a4669b97d.png">

On the resulting page, select columns and click summarize:

<img width="494" alt="Screenshot 2023-01-25 at 10 08 47 AM" src="https://user-images.githubusercontent.com/5720791/214646966-a25c6727-35ac-4626-8308-7396f760a9f2.png">

**Comment by dustymc** [comment]
# Ordering Columns

Results columns may be ordered by clicking Customize Results and using the 'drag' column to move selected rows up or down. For example, starting here:

<img width="656" alt="Screenshot 2023-01-25 at 12 10 55 PM" src="https://user-images.githubusercontent.com/5720791/214679114-f5464228-740a-4576-91b9-5837c9cfd48e.png">

Then doing this:


<img width="399" alt="Screenshot 2023-01-25 at 12 11 26 PM" src="https://user-images.githubusercontent.com/5720791/214679158-526e8e3b-20eb-457b-b47a-30fae9875782.png">

Results in this order:

<img width="882" alt="Screenshot 2023-01-25 at 12 11 39 PM" src="https://user-images.githubusercontent.com/5720791/214679182-6aa49c0d-5b2f-4f3b-aef2-5042fcc60308.png">

This ordering is maintained in Summarize.


<img width="385" alt="Screenshot 2023-01-25 at 12 13 40 PM" src="https://user-images.githubusercontent.com/5720791/214679500-dd62dad3-d5aa-4b67-a4a6-b9ca8e9e817f.png">

# Ordering Data

After finding records, click headers to sort.

Default ordered by GUID (note the dark arrow-half)

<img width="582" alt="Screenshot 2023-01-25 at 12 14 47 PM" src="https://user-images.githubusercontent.com/5720791/214679814-7d24b099-98b5-4fff-801d-1d2c8664c6a9.png">

One click to sort by a column (Identified As):


<img width="593" alt="Screenshot 2023-01-25 at 12 14 57 PM" src="https://user-images.githubusercontent.com/5720791/214679865-2aa1fbea-9e98-41a9-882a-b379d209367e.png">

Two clicks to reverse the sort:

<img width="567" alt="Screenshot 2023-01-25 at 12 15 06 PM" src="https://user-images.githubusercontent.com/5720791/214679944-94910a77-f20b-418f-bf5b-082855376512.png">

**Comment by dustymc** [comment]
# Remove Rows

https://github.com/ArctosDB/arctos/issues/5414#issuecomment-1409470702
