### ISSUE TITLE
Manage Collection - Make it more pleasant

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5535]
> Explanations

![image](https://user-images.githubusercontent.com/5725767/214652216-45447834-85cb-4d94-9230-9a020708f230.png)

Completing collection metadata is one of the FIRST tasks a new collection gets assigned and I would like it to be more pleasant. This whole page is confusing and a mash-up without offering a reason for what is being completed. Could we organize this in sections and just have them cross the page (no more 2 column set-up)?

Hopefully that would eliminate this

![image](https://user-images.githubusercontent.com/5725767/214649457-668ac330-d98f-49a0-b784-1bfcb99a5086.png)

And provide more room for explanations/instructions

Right now, I see these specific groups of information

## Arctos Community Data 
(cannot be changed without DBA assistance or should only be changed if you understand the implications)

![image](https://user-images.githubusercontent.com/5725767/214649873-8cc590df-3ce7-4011-8f7c-3ea56712371c.png)
![image](https://user-images.githubusercontent.com/5725767/214650641-f1ddf68d-cc8f-41fd-ba3d-03c6bae6aef7.png)

## Collection Contacts
![image](https://user-images.githubusercontent.com/5725767/214650024-9a3d8ea3-6eaa-47bc-972a-dcc5df672582.png)

## Collection Header
![image](https://user-images.githubusercontent.com/5725767/214650115-e3d033c2-9514-462b-bc58-7d5487854e36.png)

## Licenses and Terms
![image](https://user-images.githubusercontent.com/5725767/214650345-6b5df976-11b9-4c2f-9875-371b3798eef5.png)
Can we move Loan Policy to this block?

## Collection Defaults
Can we move Default Cataloged Item Type here?
Taxonomy source(s)
Preferred identifiers

## Summary Information
(Important for portal pages and biodiversity data aggregators)

![image](https://user-images.githubusercontent.com/5725767/214651913-7b85b5fc-9b62-44fa-8c60-9936d1979f7c.png)
![image](https://user-images.githubusercontent.com/5725767/214651620-acabc6c5-b8ce-4a4d-b22d-e0a83987125f.png)
![image](https://user-images.githubusercontent.com/5725767/214651721-b6d06eb9-135c-4bae-8b35-daee552d2dcd.png)
![image](https://user-images.githubusercontent.com/5725767/214651808-7bf31436-a919-45ec-a457-f1d78361b6b1.png)

_developed from comments by @mkoo in https://github.com/ArctosDB/arctos/issues/5493#issuecomment-1403977939_

**Comment by dustymc** [comment]
Revise docs to accommodate https://github.com/ArctosDB/arctos/issues/5552

**Comment by Jegelewicz** [comment]
Nice! Any chance these can just stretch across? I mean, I know I can adjust them, but why are they so small in the first place?

![image](https://user-images.githubusercontent.com/5725767/215920462-5da7fac7-d010-45c8-a0d6-ae7c01828349.png)

**Comment by dustymc** [comment]
>just stretch across? 

Choose or define a css class (splatF textarea in https://github.com/ArctosDB/PG/blob/master/includes/style.css)

**Comment by Jegelewicz** [comment]
OK - trying a test, but also added some links to GBIF documentation for IPT stuff. I will check later in test to see if my choice for a class is OK.

**Comment by Jegelewicz** [comment]
Do we still need the stylsheets?

```
<cfdirectory action="list" directory="#Application.webDirectory#/includes/css" name="sheets" filter="*.css">
					<div class="lblGrp">
						<label for="institution_url">
							stylesheet: CSS to supplement or replace CSS directives on /guid/ pages
						</label>
						<select name="STYLESHEET" size="1">
							<option value=" ">none</option>
							<cfloop query="sheets">
								<option <cfif #name# is #app.STYLESHEET#> selected="selected" </cfif>value="#name#">#name#</option>
							</cfloop>
						</select>
					</div>
```

Do they do anything anymore?

**Comment by Jegelewicz** [comment]
> You've really got to get ssh figured out

If you would give up an hour of your time to show me what to do, I could proceed. As I recall the last time we had this conversation, I still don't have appropriate permissions at TACC and I can't get anyone to help me figure that out. I would love to be able to see what I do so this doesn't happen!

@mkoo maybe we need to have a meet up about this?

**Comment by Jegelewicz** [comment]
I can't get test to open.

**Comment by dustymc** [comment]
I fixed this. Lots of unescaped ``#`` - and I'm not thrilled with documentation links in code, we have a mechanism for that, but I don't have the time to deal with that now.

I'm happy to answer whatever questions I can but I'm basically not involved in your TACC access other than approval.

And speaking of, that should probably be treated like an API request @mkoo ? It will provide access to scary stuff, intentionally or otherwise, seems useful to have a record of that?
