### ISSUE TITLE
Code Table Request - Add container types Cavity Mount and Cradle

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#5537]
**Goal**
Barcoding storage mounts for our oversize collection.

**Context**
Existing values do not cover these types of storage. We are rehousing our oversize collection and need these values so that we can enter our barcoded mounts in Arctos.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=CTCONTAINER_TYPE

**Proposed Values and Definitions**
Cradle: A form-fitted storage mount typically made of Hydrocal and fiberglass with a foam or felt liner.
Cavity Mount: A form-fitted storage mount made of of foam set into a tray and lined with Tyvek.

**Comment by Jegelewicz** [comment]
Suggest

cradle and cavity mount (no caps) to be consistent with other containers.

My only reservation has to do with the construction materials - are there cradles made from other substances? Do we really need to provide material composition in the definition? Could we go with:

cradle: A form-fitted storage mount.
cavity mount: A form-fitted storage mount.

HMMMM - is there really a difference that needs to be part of the code table term, or could we use one general term?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
They definitely should not be merged into one term - it makes a difference in what type of handling/lifting/moving the specimen needs.

I can't entirely remove the materials if we want to actually define what these are, and the materials are part of why they have different handling requirements.

Here is a stab at more generalized definitions:
cradle: A form-fitted storage mount created by molding a sturdy setting material to the surface of a specimen. Also known as a clamshell.
cavity mount: A custom storage mount with a foam cavity that a specimen or object sits within.

**Comment by dustymc** [comment]
>cradle: A form-fitted storage mount created by molding a sturdy setting material to the surface of a specimen. Also known as a clamshell.
cavity mount: A custom storage mount with a foam cavity that a specimen or object sits within.

No DBA problems

**Comment by Jegelewicz** [comment]
object tracking says go for it.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Trying to add these, getting an error message after clicking edit:
<html>
<body>


ERROR_ID | A5FB0667-0D2D-4DD3-BFA3A18D80044ECA
-- | --
ERROR_TYPE | SQL
ERROR_MESSAGE | ERROR: syntax error at or near "as" Position: 9
ERROR_DETAIL |  
ERROR_SQL | select as data from CTCONTAINER_TYPE ORDER BY


</body>
</html>

**Comment by dustymc** [comment]
I added both after trying fairly hard, and failing, to break test. Are we really sure the state hasn't hired a new IT guy or deployed some creepy (and buggy) software, or ?? Something about Roswell and/or VLA? ??

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks. It wouldn't surprise me.

**Comment by campmlc** [comment]
Chinese balloons over Los Alamos . . .

**Comment by Jegelewicz** [comment]
It is totally that ^^
