### ISSUE TITLE
Encumbrance visibility

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5541]
I believe that only those who can edit encumbrances can see them? I think the encumbrance itself (not the encumbered data) needs to be visible at least to operators so that they can see what is encumbered, why, and for how long. This is part of #4557 as there will probably be those who can create and edit loans but cannot create and edit encumbrances.

**Comment by dustymc** [comment]
see also https://github.com/ArctosDB/arctos/issues/1727
