### ISSUE TITLE
Error updating correspondence address

### ISSUE THREAD

**Issue by barke042** [ArctosDB/arctos#5542]
**The Bug (?)**
Updating the correspondence address for an agent involved in a loan. Searched for agent, selected 'Edit', deleted current contents of correspondence and pasted new contents. Received the following error:
![Screen Shot 2023-01-26 at 9 46 20 AM](https://user-images.githubusercontent.com/11162169/214883548-e0d5b153-5417-4a24-8ba5-f4227c4f1d36.jpg)

**To Reproduce**
See description above.

**Expected behavior**
The address should update, I would think.

**Screenshots**
See above.

**Desktop (please complete the following information):**
 - OS: Mac 10.14.6
 - Browser: Firefox
 - Version: 109

**Comment by Jegelewicz** [comment]
@barke042 the screen shot didn't finish loading before you commented.

BUT - don't delete old addresses, just mark them as inactive by adding and end date and add the new address with today as a begin date.

**Comment by Jegelewicz** [comment]
- that address may have been used in some other transaction that still exists, so deleting or editing is not a good thing to do.

Maybe we need to say that right here in the edit agent form?

**Comment by barke042** [comment]
I put an end date of today on the first address, and then added a new correspondence address that starts today. Hopefully that makes things clear enough. Thanks for the clarification!
