### ISSUE TITLE
Edit existing "A" type ID instead of Adding Determination?

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#5544]
We use A{string} IDs for naming cultural objects. The taxon pulls from Nomenclature (usually) and then we enter a free-text term into the {string} part, that might or might not be the same word as the controlled vocabulary in taxon.

If they are the same, Arctos automatically converts this to an "A" type ID rather than retaining the A{string} presumably because it would be silly to have two lines with the same term.

My student cataloged a collection, not realizing he should put the Indigenous term in the {string} part following a / mark and now I'm going back to add those to the ID line. But because they got converted to A I now have to create a whole new determination.

My question is: is it possible to make it possible to edit a "Formula:A" scientific name rather than creating a new determination? This collection has 44 items and I hadn't budgeted time this morning to make 44 new individual IDs this morning.

**Comment by Jegelewicz** [comment]
@AJLinn how about [bulkloading identifications](https://arctos.database.museum/tools/BulkloadIdentification.cfm) - that would at least get the accepted ID as the one you want.

Are they all the same identification? If so, then using the Manage tool in search results to add an identification would be the quickest way to add them.

<img width="960" alt="Screenshot 2023-01-26 11 08 17" src="https://user-images.githubusercontent.com/5725767/214915392-2bb887b3-bd28-4237-8d33-0c86038bd06d.png">

**Comment by AJLinn** [comment]
> Are they all the same identification? 

:-) of course not... that would be too easy!
https://arctos.database.museum/saved/JohnJBurnsCollection
<img width="1347" alt="Screenshot 2023-01-26 at 9 29 46 AM" src="https://user-images.githubusercontent.com/17605945/214919697-af2fff42-64a6-4861-a21d-a95b019ccdf9.png">

All different...

**Comment by Jegelewicz** [comment]
So the identification bulkloader is probably the easiest thing. Let me know if you need any help.

**Comment by dustymc** [comment]
It is possible to edit A {string} names in the /guid/ UI.

The bulkloader exists, but it's an additive tool.

Bulk edit tools never work out, but IDs have IDs and there could be a remove (and remove+add=edit) BUT - everything in Arctos assumes there's some kind of identification, so that would be dangerous in interesting ways beyond the normal 'make data go poof.'

Are we missing something, and if so what might it look like?

**Comment by Jegelewicz** [comment]
I think an add + remove would be useful. I understand that we could end up with a record with no identification, but we could also add a trigger to the unloader that won't let you unload the ONLY identification?

So we could use the bulk add tool to get the corrected ids, then use the bulk un-load tool to remove the incorrect ones.

See like an OK deal? We would need a way to get the identifiers for the incorrect ids (which we could do before we load the correct ones).

**Comment by dustymc** [comment]
I believe this is easily handled by current bulk tools.
