### ISSUE TITLE
Documentation update request: relationship "same individual as"

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#5547]
Cultural objects sometimes get broken apart either through post-depositional taphonomic processes (e.g. a point gets broken in an archaeological site as a result of cryoturbation) or through intentional processes of cutting things to make them fit a certain circumstance (e.g., bus 142 having parts of the floor and roof cut apart to remove it from the Stampede Trail). These items might get cataloged separately until a collections staff person realizes they fit back together. 

I would like to expand the use of "same individual as" (in the code table [id_references](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctid_references)) to cultural objects to include these "refit" processes that sometimes occur with cultural objects. 
<img width="1343" alt="Screenshot 2023-01-26 at 8 53 06 AM" src="https://user-images.githubusercontent.com/17605945/214911623-a7acf75f-9e95-4651-8086-a38dd3bbc558.png">

I propose the following new definition (but am open to suggestions):

_Refers to a cataloged item that is the same biological individual specimen or individual cultural object as described in the current record. For example, when parts and tissues are cataloged by separate institutions or when two individually cataloged items are refit following conservation treatment. Reciprocal relationship is "same individual as."_

**Comment by Jegelewicz** [comment]
I like it.

**Comment by dustymc** [comment]
With an eye towards https://github.com/ArctosDB/internal/issues/251

* 2 CT admins reacted to this
* It doesn't break stuff
* It doesn't change the meaning of existing data

Done.
