### ISSUE TITLE
Managing encumbrances

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5550]
You can look in https://arctos.database.museum/info/encumbrances and see all active encumbrances but it may be difficult to filter them for your collections. Also, that is a hidden page of sorts? It isn't available on any menu when you are not logged in, I am not even sure it is when you are?

When logged in, those who have permission to manage encumbrances can go to https://arctos.database.museum/Encumbrances.cfm and search for specific encumbrances

It's crazy though, because I guess encumbrances can cross collections? So there is no real way to filter for all encumbrances that include records from a given collection - that seems like something we would want?

Except there is? https://arctos.database.museum/Reports/encumbranceByCollection.cfm

I feel like I have just opened Pandora's box.....

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/newsletter/issues/221#issuecomment-1405677725_

**Comment by Jegelewicz** [comment]
@campmlc said

> I don't understand why encumbrances are associated with a specific agent if we can use other people's and institutions encumbrances. I would like to know that if I delete all items in an encumbrance, I'm only dealing with records I have control over.

**Comment by Jegelewicz** [comment]
Hoever, I am not sure the filter on https://arctos.database.museum/Reports/encumbranceByCollection.cfm actually works and it seems like there are a lot of unused encumbrances too?

**Comment by Jegelewicz** [comment]
FWIW https://arctos.database.museum/info/encumbrances seems like a really helpful start, but it needs de-specimen-ing and instead of some truncated list of catalog records, a link to search results would be more useful. Also, a column indicating collections involved for sorting.

**Comment by dustymc** [comment]
I do not see any actionable requests in this, closing.
