### ISSUE TITLE
jqueryui

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5553]
We're still using jqueryui for dialog, that should be rebuild in html5 (or something).

Find and remove any other uses.

Purge the code.

**Comment by dustymc** [comment]
new homegrown modal running for login at test

**Comment by dustymc** [comment]
We're also using jqueryui for suggest (edited title), and it's not being very helpful at the moment - see search-->geog name, which isn't visible and sometimes just does nothing?? Need a replacement or workaround for suggest-with-type.

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/5592:

I want to expand the customize catalog record search results window but every time I click to the 'drag window bigger' portion of the window (lower right corner) the window vanishes. It's a massive list of fields and hard to navigate. I'd also like to use my browser's 'find' tool to find the field I want rather than my eyeballs, but this also fails - the window vanishes when I click command-f to initiate a within-browser window search.

**Comment by dustymc** [comment]
I'm tabling this.

We're using jqueryUI for suggest-with-type and I can't find a workable replacement.

My homegrown overlay doesn't seem to have any problems coexisting with the jquery modal.

I can change specific instances of the jquery popup to my overlay, just open an Issue.

**Comment by mkoo** [comment]
tabled-- can I also either move this issue to arctos-dev or close? (especially since you're just talking to yourself...)
