### ISSUE TITLE
Button extended

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5556]
NBD, but the submit query button at the top of search is kinda weird.

![image](https://user-images.githubusercontent.com/5725767/215116201-918e4c38-b8d4-42c2-b47d-f0737a3f96ef.png)

**Comment by dustymc** [comment]
Ever wonder what your browser'd do with an object of type ``fsubmit``? Now you know...

**Comment by Jegelewicz** [comment]
Why isn't the bottom one like that?

![image](https://user-images.githubusercontent.com/5725767/215119541-031dd7e1-6c0d-491e-a776-7d63863e6f67.png)
