### ISSUE TITLE
Create an Accession?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5559]
@dustymc it appears we have no way to manually create an accession? At least I can't figure out how to get there (probably just me being nuts...) Help!

**Comment by Jegelewicz** [comment]
Thanks - I'll fix up the directory too.

**Comment by Jegelewicz** [comment]
Same issue for loans?

**Comment by AJLinn** [comment]
Yeah, there's only loan bulkload stuff, and there's no Create Permit either.

**Comment by AJLinn** [comment]
NVM, I see create permit is at the top of the Find Permit page.

**Comment by cjconroy** [comment]
I can create an MVZ mammal accession, but it does not offer a link to the next available number like it used to. But, the next number can still be entered manually. 
<img width="373" alt="Screenshot 2023-01-27 at 2 30 16 PM" src="https://user-images.githubusercontent.com/5749672/215218718-8e41bc71-650a-4a45-91cb-80f53c15b1bc.png">

**Comment by dustymc** [comment]
Glitch in the matrix?

<img width="1630" alt="Screenshot 2023-01-27 at 2 34 00 PM" src="https://user-images.githubusercontent.com/5720791/215218973-3c2dbdde-6e97-46ae-9505-2181c6032d69.png">

**Comment by cjconroy** [comment]
still doing it
<img width="1450" alt="Screenshot 2023-01-27 at 2 45 15 PM" src="https://user-images.githubusercontent.com/5749672/215220330-469efae8-67ae-4067-9043-55945e7c8e4c.png">
