### ISSUE TITLE
Cannot search by collection object remarks

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#5561]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Searching for information in the collection object remarks is not giving any results.

**To Reproduce**
1. New search page - Catalog Record - [customize] - select "coll_object_remarks" - save
2. Make sure Specimen Remarks is visible in the results.
3. Type a known word from collection object remarks into "Remarks"
4. No search results. I tried again with % around the search term and still no results.

**Expected behavior**
There are notes in collection object remarks that I have been able to locate in the past by searching remarks.

**Screenshots**
This is where I am attempting to search the remarks in the new search form:
![image](https://user-images.githubusercontent.com/93737929/215188319-f37d939c-87d8-48ca-a5f0-82d091cb5f5c.png)

This is where the data is at in the catalog record:
![image](https://user-images.githubusercontent.com/93737929/215188832-dddbd359-a508-4094-a01d-5629b6dcf73a.png)

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**
Firefox

**Additional context**
Still getting used to the new format.

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by dustymc** [comment]
This just went out, you'll probably have to recustomize, the field is now just 'remark'
