### ISSUE TITLE
Get Something Random Right in Middle of Screen

### ISSUE THREAD

**Issue by KyndallH** [ArctosDB/arctos#5568]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
<img width="2443" alt="Screen Shot 2023-01-30 at 8 56 59 AM" src="https://user-images.githubusercontent.com/16887896/215556763-6d1f7671-2310-4cef-8ec9-4dc1045ec1c1.png">

Something random right in middle of box. Doesn't move when I change the width of my screen. Just seems odd.

**To Reproduce**
Go to [Arctos](https://arctos.database.museum/)
No something random once I login.

**Expected behavior**
Perhaps be dynamic and move. 

**Screenshots**
See above.

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**
Chrome. Mac.

**Additional context**

**Priority**
Low.

**Comment by mkoo** [comment]
obsolete issue with new UI
