### ISSUE TITLE
Manage Collection Automation

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5569]
> I don't usually use this, but I had need for it today! I was trying to get a summary of catalog records for an entire collection by Class and I don't think it is possible? Or maybe I just don't see how to do it in the new system.

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/arctos/issues/5536#issuecomment-1409517506_

Here is something that is seems like we should be able to do. In Manage Collection, we ask people to provide a kind of taxonomy summary:

![image](https://user-images.githubusercontent.com/5725767/215619356-dcab11b7-d55f-4a33-a6a3-585a8bb23cf7.png)

It seems like we should be able to enter a rank in the first field, then let Arctos summarize and provide the answer in the second?

I resorted to a download of all data for the collection including "phylclass" in the results, opening in Excel and removing dupes in that field. This works, but for some larger collections might not work well (timeout limits to search results?).

**Comment by dustymc** [comment]
I'm relatively sure taxonomic data aren't that predictable, and I'd guess that the existence of this concept is an acknowledgement of that.

**Comment by Jegelewicz** [comment]
Why do issues just get closed with absolutely no community discussion? Maybe nobody cares, but 2 weeks isn't long enough to find out.

**Comment by Jegelewicz** [comment]
Clearly nobody but me cares - closing
