### ISSUE TITLE
Code Table Request - part attribute weight

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#5572]
**Goal**
Tracking part weight for the purposes of shelving load capacity.

**Context**
There is a record attribute weight, but that does not work for specimens that have multiple parts on different shelves.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecpart_attribute_type

**Proposed Value**
weight

**Proposed Definition**
The weight of the part.

**Attribute data type**
number+units

**Attribute units**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctweight_units

**Available for Public View**
Yes

See #5573 for the wider goal.

**Comment by Jegelewicz** [comment]
I could also use this for a potential incoming collection. In reality - a lot of the weights recorded as attributes are for a "whole organism" part that was never cataloged. I'm starting to think we need to change that practice if we want to have research-grade data.

**Comment by Jegelewicz** [comment]
Yes, you want the capacity - but also want to know if you are exceeding it!

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I like Dusty's idea, I'm going to close this for now so the discussion is not split over two separate threads.
