### ISSUE TITLE
New Tools Menu - where is make comma separated list from anything tool?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#5574]
I'm working on creating my first loan since the update. I need to be able to generate a comma-separated list from a list of NKs copied from an Excel file, and we used to have a super handy tool to do this in reports. I can't find it in the current interface? Can we get it back  please?
Alternately, can we just enter a non-comma separated list of values into GUID and other ID searches, so I don't have to either request this tool or go do multiple data manipulations to convert my column list of values to a row list of values and resave file as csv? This gets very tedious when I have to do it multiple times per day.

**Comment by dustymc** [comment]
https://arctos.database.museum/DataServices/listerizer.cfm, directory updated (but cached).
