### ISSUE TITLE
collection selector standardization

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5578]
This is what I see when I visit [System Stats](https://arctos.database.museum/info/sysstats.cfm)

![image](https://user-images.githubusercontent.com/5725767/215885703-016bd52b-fa9b-49a5-aefd-a8352b88113a.png)

Can we make the filter options more like those in Search?

![image](https://user-images.githubusercontent.com/5725767/215885893-1b1ac652-ace7-4c26-a7fa-4dd7b3261108.png)

**Comment by dustymc** [comment]
I'm going to back up and ask for guidance from above. See eg https://github.com/ArctosDB/arctos/issues/1555, https://github.com/ArctosDB/arctos/issues/3352, probably more - there've been a lot of non-standard UIs for picking collections (including the current thing at https://arctos.database.museum/search.cfm), I think all of them are probably less-accessible than a standard-issue select multiple. Certainly having everything different isn't accessible! Can we pick one thing (or a few for specific purposes or whatever), add it/them to https://handbook.arctosdb.org/how_to/developer-guide.html, and strive to make the dozens of these things consistent?

**Comment by Jegelewicz** [comment]
> a standard-issue select multiple

Sounds like a good idea. I assume that is CTRL click?
