### ISSUE TITLE
Error feedback

### ISSUE THREAD

**Issue by barke042** [ArctosDB/arctos#5579]
*Error*: ED484E71-6101-487D-8E4AEDD0C4B8E35D

*Circumstances*: Attempted to grant access for data entry to a new agent/username. Immediately received error with text "ERROR: role "mill8849" does not exist Where: SQL statement "grant coldfusion_user to mill8849" PL/pgSQL function manage_user(text,text,text,text,text,text) line 126 at EXECUTE".

Any insights?

**Comment by ewommack** [comment]
Sometimes I get that error when I have not made an agent into an operator yet: https://handbook.arctosdb.org/how_to/How-to-Create-your-Arctos-Team-Users-and-Operators.html

**Comment by barke042** [comment]
Oh shoot, you're right, I forgot that step!
