### ISSUE TITLE
Arctos seems to be down

### ISSUE THREAD

**Issue by jebrad** [ArctosDB/arctos#5580]
Upon landing, this is happening on multiple computers and browsers:

An error has occurred!
May we suggest:

    Logging in and try again. [You may log in from the home page.](https://arctos.database.museum/)
    On search pages, make sure you do not have values in fields that you do not mean to be there. Or try filling in fewer fields, the more likely to get a match.
    You may not have sufficient privileges to perform that operation. Consult with your supervisor or Arctos mentor.

This message has been logged as 52297089-8C93-4A40-830C109E1B53A01B. Please [contact us](https://github.com/ArctosDB/arctos/issues/new?assignees=&labels=contact&template=contact-arctos.md&title=error%20feedback) with any information that might help us to resolve this problem. For best results, include the error as text and a detailed description of how it came to occur in the Issue.

**Comment by genevieve-anderegg** [comment]
Same for me

**Comment by wellerjes** [comment]
I'm getting this error message:
<html><body>


ERROR_ID | B7435B07-1B82-4360-A484E432B1B03D55
-- | --
ERROR_TYPE | expression
ERROR_MESSAGE | variable [ISVALID] doesn't exist
ERROR_DETAIL |  


</body>
</html>

I also got this error message around 4pm, but it (seemed to) resolve after a few minutes. But I'm including it in case these are related:
<html><body>


ERROR_ID | 3A7E514F-FE8B-4CD4-89F5E9AD1793277D
-- | --
ERROR_TYPE | SQL
ERROR_MESSAGE | ERROR: current transaction is aborted, commands ignored until end of transaction block
ERROR_DETAIL |  
ERROR_SQL | select GMAP_API_KEY_EXTERNAL from cf_global_settings


</body>
</html>

**Comment by ewommack** [comment]
https://github.com/ArctosDB/arctos/issues/5581

**Comment by dustymc** [comment]
It wasn't entirely down, but I can't get ahead of the nonsense so I took the UI down until I can. Back up shortly, I hope.

**Comment by dustymc** [comment]
Arctos should be back up.
