### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by genevieve-anderegg** [ArctosDB/arctos#5581]
Attempting to log in to Arctos (Windows PC, Google Chrome), repeatedly met with this message. Selecting the "You may log in from the home page" link leads to this same message. Attempted on other browsers as well as Incognito, same issue.
Last error message text: D99B44BF-E401-4E31-A58179050FD0090D

![image](https://user-images.githubusercontent.com/83782023/215896649-82f22def-08cf-43da-814e-b53a3cc9ee5c.png)

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/5580
