### ISSUE TITLE
"Download parts" needs a better name

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#5582]
EDIT: current conversation starts here: https://github.com/ArctosDB/arctos/issues/5582#issuecomment-1411243223

----------------

Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Not sure if this is a bug, so please reclassify. There used to be a drop down tool to allow you to make a nice spreadsheet of the hierarchy of part locations. Super helpful for finding tissues for loans. Where is it now?

**To Reproduce**
Get a list of specimens
Find tool in drop down

**Expected behavior**
A way to easily find part location hierarchy. Old way was to flatten part locations, open in Excel, text to column, etc., etc.

**Screenshots**

**Priority**
medium

**Comment by Jegelewicz** [comment]
Is it this?

<img width="960" alt="Screenshot 2023-01-31 16 44 29" src="https://user-images.githubusercontent.com/5725767/215909267-d64f9a0a-3ff7-4ea4-9b04-3fdbf6809f34.png">

**Comment by Jegelewicz** [comment]
Then this?

<img width="960" alt="Screenshot 2023-01-31 16 46 04" src="https://user-images.githubusercontent.com/5725767/215909446-fac5cc18-f70a-40df-85ab-3b7f8bee74fb.png">

**Comment by Jegelewicz** [comment]
And finally, this?

<img width="960" alt="Screenshot 2023-01-31 16 47 20" src="https://user-images.githubusercontent.com/5725767/215909608-11f9a8a4-529a-4e3e-b2f4-7a13d1b80d48.png">

**Comment by cjconroy** [comment]
No. There was another tool, that I think Mariel succeeded in getting. It automatically parsed out the parts to tank, rack, box, etc. in a table format that could be downloaded. Extremely helpful.

**Comment by cjconroy** [comment]
The download file was called partFlatDownload. See attached screenshot. 
<img width="1165" alt="Screenshot 2023-01-31 at 3 50 13 PM" src="https://user-images.githubusercontent.com/5749672/215910034-544ce651-72e7-4896-8f0a-fed722a8adc3.png">

**Comment by dustymc** [comment]
<img width="341" alt="Screenshot 2023-01-31 at 3 51 35 PM" src="https://user-images.githubusercontent.com/5720791/215910139-61d8b145-0989-484b-b8d6-f0fbfba8378c.png">

**Comment by cjconroy** [comment]
Thanks!  When I see download, I think it is going to just download something. Download parts and Identifiers SHOWS the table, but download attributes just immediately downloads. What do people say about SHOW part matrix? Or something more clear?

**Comment by Jegelewicz** [comment]
I actually think we need some sort of "Tour of Search Results Tools"...

**Comment by dustymc** [comment]
Edited title - better names are very welcome, just be more consistent than I apparently have been....

**Comment by campmlc** [comment]
I had the same confusion first time I looked for that table.  I like having
Part as the first search term, rather than a verb. Maybe Parts Detail?
Parts View? Parts Table Download?

**Comment by atrox10** [comment]
Parts Table Download makes more sense to me.

**Comment by KyndallH** [comment]
I also vote for Parts Table Download!

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/6061
