### ISSUE TITLE
Log out unclear

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5584]
After I log out, the screen greys out, but nothing happens...apparently.

<img width="960" alt="Screenshot 2023-01-31 17 21 41" src="https://user-images.githubusercontent.com/5725767/215914630-22f876d3-f124-4aab-bb57-adce1c6b4335.png">

However, if I scroll waaaaaaaaayyyyyy down, I finally see what I am used to seeing.

<img width="960" alt="Screenshot 2023-01-31 17 22 02" src="https://user-images.githubusercontent.com/5725767/215914725-cdd50959-ac7c-4245-833a-0d7acf78401e.png">

Can this somehow be anchored to the header so that it shows up right where I click sign out?

**Comment by dustymc** [comment]
symptom of https://github.com/ArctosDB/arctos/issues/5553 - but that exactly application has about 30 minutes to live, you might want to try out the replacement in test like NOW....
