### ISSUE TITLE
Error message when creating agent

### ISSUE THREAD

**Issue by ufarrell** [ArctosDB/arctos#5585]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Added two agents and got this message, so here is a bug report!: 

Agent created successfully. If you're seeing this something is broken so file a bug report!

The agents were indeed added successfully:
Charles Hepworth Holland (person: 21347173),
George Sevastopulo (person: 21347174)

**To Reproduce**
1. Go to 'Manage'
2. Click on 'Create Agent'
3. Create Agent

**Comment by Jegelewicz** [comment]
@ufarrell what was the error message you received?

**Comment by ufarrell** [comment]
Its exactly that - here's a screenshot: 
![image](https://user-images.githubusercontent.com/11726107/216098635-dbf5e9c6-e39d-4adc-96f9-abce1ddb9252.png)

I just tried to add two others - one via the "manage agents" window - that didn't get an error. And then another through the "create agent" link - that got the same error again.

**Comment by Jegelewicz** [comment]
@dustymc it looks to me like that statement is just hanging out there as part of making a new agent and will show up any time the form is used. Any reason I can't get rid of it?

```
		</cfif>
		If you're seeing this something is broken so file a bug report!
	</cfoutput>
</cfif>
```

**Comment by dustymc** [comment]
>Any reason I can't get rid of it?

!!

@ufarrell your browser is blocking javascript (or some of it, you apparently got this far?!) which should have redirected you to the edit application. (Or you read really fast!)

**Comment by Jegelewicz** [comment]
@dustymc what does that message mean - is some information missing? incorrect? 

The agent was created, what pop-up was supposed to show up?

**Comment by ufarrell** [comment]
@dustymc - could an ad blocker cause a problem? Or maybe not - I just tried again with it turned off and got the same message. 

I'm using Chrome - let me know if there's anything I can look out for, maybe using "inspect"? I can see the script there - but don't really know how to troubleshoot any further. I'll try a different browser tomorrow!

**Comment by dustymc** [comment]
@Jegelewicz it should close the overlay.

@ufarrell please let me know if you figure it out - I just made an agent in test and it's still doing what it should for me. I'd guess something's blocking the javascript but ??

**Comment by Jegelewicz** [comment]
I made two agents today and never saw this. @ufarrell I am using Firefox

**Comment by Jegelewicz** [comment]
> it should close the overlay.

AHHH, I get it now, but it seems strange that both messages were present? It would be interesting to know if anyone else has seen this and just ignored it. Old-timers tend to do that....

**Comment by ufarrell** [comment]
@dustymc @Jegelewicz - no luck I'm afraid - I tried Firefox, and the same thing happens - it works perfectly from Manage>Manage Agents>Create Agent. But if I go Manage>Create Agent then I get the error. 

I've run out of agents to test for the moment and going through "Manage Agents" seems to work just fine (unless I am adding bad data somehow). But if you want me to do anything else to test it out just let me know - can't figure out what might be helpful in 'inspect', but happy to screenshot anything and everything if you want it!

**Comment by dustymc** [comment]
AHA! Your initial message somehow didn't penetrate my skull. That shouldn't have been linked like that, Manage Agents then create should be the only pathway. I've updated the directory, it'll clear in an hour or so. THANKS!

TODO: the overlay should not allow itself to be opened without a parent (ideally even the proper parent). Possible?

**Comment by Jegelewicz** [comment]
@ufarrell this was GREAT! Thanks!!! And Welcome to Arctos development!

**Comment by ufarrell** [comment]
@dustymc @Jegelewicz  - great! glad it worked out, having fun already:)

**Comment by dustymc** [comment]
There's a fix for this form in next release, perhaps eventually it can be generalized and picks (forms which aren't intended to stand alone but aren't called as iframes) somehow included, but seems very low-priority so will let this close.
