### ISSUE TITLE
Arctos Down - not working 2/1/2023 12:15 pm

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#5588]
Please complete to the best of your ability.

## Unplanned Outage
 - I was working with Arctos and now it seems down (2/1/2023 at 12:15pm)
 - Arctos is not responding at all

## Communication before/during outage
- [x] Pin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG  
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by Jegelewicz** [comment]
Down in ABQ too.

**Comment by dustymc** [comment]
revived
