### ISSUE TITLE
Manage_collection page down

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#5589]
Seems like a simple fix. Cannot access manage_collection 

This page: https://arctos.database.museum/Admin/Collection.cfm
is throwing this error:
<div style="border:2px solid green; padding: 1em; margin: 1em; text-align: center;"></div>
        

ERROR_ID | 202F40DE-37A4-4432-B566729468549F17
-- | --
ERROR_TYPE | template
ERROR_MESSAGE | missing terminating [#] for expression
ERROR_DETAIL |  

</div>

**Comment by Jegelewicz** [comment]
Yep -see #5535

**Comment by dustymc** [comment]
patched
