### ISSUE TITLE
customize search results window problem

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#5592]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

I want to expand the customize catalog record search results window but every time I click to the 'drag window bigger' portion of the window (lower right corner) the window vanishes. It's a massive list of fields and hard to navigate. I'd also like to use my browser's 'find' tool to find the field I want rather than my eyeballs, but this also fails - the window vanishes when I click command-f to initiate a within-browser window search.

Using Firefox on mac

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.
medium

**Comment by DerekSikes** [comment]
The field I want to add is collector. I've just eyeballed the entire list of fields and did not see it. How do I add collector??

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/5553

<img width="954" alt="Screenshot 2023-02-02 at 1 12 42 PM" src="https://user-images.githubusercontent.com/5720791/216450619-7a1e5aa5-636d-48e4-bc3f-8aef2f090fe1.png">
