### ISSUE TITLE
"curatorial geography"

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5594]
In conjunction with https://github.com/ArctosDB/arctos/issues/5383, create a new locality attribute 'curatorial geography.' 

It can be used for qualifiers ("Alameda County") but also for eg historic names which might not agree with current spatial geography, or just WHATEVER a collection might want to use it for.

@dustymc will revise labels as necessary/on request to use this. (There's a function, should be simple.)

@ccicero plz fix whatever I messed up!

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/5383 is now scheduled to begin the 20th; I'll need instructions if I'm to do anything with this in conjunction.

**Comment by Jegelewicz** [comment]
This doesn't seem that different from [previous geography](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlocality_attribute_type#previous_geography). Is this needed just for label creation or can we envision other reasons it might be used? If we are making something specifically for label generation, maybe we should say that? Sorry - just thinking that we might need more than one thing, but maybe not - I don't know the whole story.

**Comment by dustymc** [comment]
@ccicero is that compatible with whatever you're trying to do?

**Comment by Jegelewicz** [comment]
Adding this to code tables for tomorrow as priority.

**Comment by dustymc** [comment]
>priority

Not sure how an arbitrary change in terminology is priority?

>verbatim

No? I think @ccicero is wanting a formatted string to print labels, not necessarily verbatim anything. (And that might be incompatible with multiple 'determinations'?) I used the existing attribute for stuff that's also not verbatim (except as constructed pre-GADMification). Whatever I use for the next phase (if I use anything @ccicero  help!) won't be verbatim either.

Maybe geog search terms can be leveraged for this (but it'll have cardinality issues too - some sort of findable+replaceable flag? "MVZLabels: bla bla..."==>replace(...)=="bla bla..") Example: https://arctos-test.tacc.utexas.edu/place.cfm?action=detail&geog_auth_rec_id=1001626

If this solidifies (maybe before?) it should be recast to https://github.com/ArctosDB/arctos/issues/new?assignees=&labels=Function-CodeTables&template=code-table-request--proposed-.md&title=Code+Table+Request+-+ - this issue is missing a well-defined goal, I don't think we're going to get anywhere useful without a target in sight.

**Comment by Jegelewicz** [comment]
> priority

> > https://github.com/ArctosDB/arctos/issues/5383 is now scheduled to begin the 20th; I'll need instructions if I'm to do anything with this in conjunction.

**Comment by Jegelewicz** [comment]
Will be a non-issue after concatenation of GADM fields.
