### ISSUE TITLE
How to capture all of a taxon from a continent?

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#5595]
Here is my curatorial issue. An expert has told me that all wildcaught Mus musculus from North and South America should be Mus musculus domesticus, until proven otherwise. So, in trying to grab just those records, I tried querying by continent. As you can guess, some South American records come back with South America as a search term, whereas others don't. 
I will be able to figure this out by a bounding box, or some other tool. But, what would others do in this case?  Doesn't it seem reasonable that someone might want to search for all records of some taxon from a continent?  South America is not in any of the higher geography under Brazil, so not clear how I am getting the ones I am. Verbatim?
<img width="508" alt="Mus musculus - South America" src="https://user-images.githubusercontent.com/5749672/216453986-38abb2ce-d7be-413e-9f43-1916117c296e.png">
<img width="494" alt="Mus musculus - all wild caught" src="https://user-images.githubusercontent.com/5749672/216453994-b5a330dd-0147-47ff-8a6d-a9066c575ed4.png">
<img width="538" alt="Screenshot 2023-02-02 at 1 27 11 PM" src="https://user-images.githubusercontent.com/5749672/216454001-417d7dfc-594c-41f9-b889-9646bef5943a.png">

**Comment by dustymc** [comment]
https://arctos.database.museum/search.cfm?guid_prefix=MVZ%3AMamm&CustomOidOper=BETWEEN&scientific_name=Mus%20musculus&geog_shape=South%20America

https://handbook.arctosdb.org/how_to/How-to-Search-for-Specimens.html#spatial

**Comment by campmlc** [comment]
I did this for MSB on a genus that only occurs in SA, and got 168 values if
I put in South America, but over 800 if I left that off.

**Comment by cjconroy** [comment]
OK, I see that I need to use Geography Shape Name. I get 463. If I put South America in Any Geographic Element, I get 231. If I put it in Place Term: Continent, I get zero. If I put it in Place Term: continent_ocean, I get 119.  This is way too complicated. If the correct answer is 463, then the other options should probably be removed, or at least throw up some flag to say it is not going to give me what I want.

**Comment by dustymc** [comment]
@cjconroy that's https://github.com/ArctosDB/internal/issues/222, which https://github.com/ArctosDB/arctos/issues/5597 might make irrelevant. 

Otherwise - yea, maybe removal is preferable to unpredictable?

@mkoo help!

**Comment by mkoo** [comment]
The new functionality in berkeleymapper could address this-- Spatial Intersections uses GIS layers to assign your points to a polygon. I am going to request to add continents as a new polygon layer
