### ISSUE TITLE
[external CONTACT] Manage records

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#5596]
@dustymc @atrox10 I revoked my own permission for 'manage_records' and am able to access the Reporter from both the search results tools and transactions.

HOWEVER, now I can't add back that permission. The pick has nothing in the dropdown so that seems odd. @dustymc can you please reinstate that role for me??? Thanks.

![image](https://user-images.githubusercontent.com/967275/216456151-a84cacb8-aee7-4d6c-af32-395a1de30b4b.png)

**Comment by dustymc** [comment]
heh - I might have done that a time or two! You'll probably have to log out/in to see it.

And confirmed, only coldfusion_user is necessary to access the reporter.

**Comment by ccicero** [comment]
@dustymc ok will do once I'm finished uploading a whole bunch of bird observations. Thanks!

**Comment by ccicero** [comment]
Yep, all good now. Thanks!
