### ISSUE TITLE
Manage Attributes - needs manage_collection permission but is a tool my lab techs need to use a lot

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#5598]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

When our Ento specimens come back from loan they often come back with sex identifications (male/female) that were previously unknown. Thus, when we update their identifications (which are typically also imprecisely known when going out on loan) we also want to bulk-update their attributes - eg add sex = male or = female for lots of specimens at a time.

We also periodically find we haven't added ageclass attribute to large series of specimens so my lab techs will search & add this attribute.

Currently, the manage attribute tool requires the manage_collection permission. I'd rather not give that permission to all my lab techs so can we get this permission changed to the same ones needed for manage identification (which has a similar bulk-change feature that we use all the time).

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.
high

**Comment by campmlc** [comment]
I have the same issue with Download Parts - which apparently requires
Manage Records, an assistant collection manager role. It would be good if
this could be added to Manage Specimens instead. I need my grad student to
be able to download part locations.

**Comment by dustymc** [comment]
There's nothing technical about this, if we are comfortable with some lesser role having access to potentially dangerous tools then someone with global admin can change it in the directory (or let me know and I'll do it).

FWIW manage_records for this seems reasonable to me (but I don't own any data that someone with too many rights might do horrible things to!).

**Comment by campmlc** [comment]
But Manage Records allows the immediate cloning of records and access to the component loaders. A student who just needs to download attributes or part locations doesn't need that amount of access. 
But a student who has Manage Specimens access already has the ability to see and edit records, including attributes. Isn't that more appropriate?

**Comment by Jegelewicz** [comment]
It would be nice if the component loaders worked the same way the bulkloader does - students with data entry could load stuff, but Derek could approve and mark to autoload. I think this would solve the issue? (Although not for the downloading thing).

**Comment by dustymc** [comment]
Resolution in https://github.com/ArctosDB/arctos/issues/5598#issuecomment-1414616191
