### ISSUE TITLE
Code Table Request - Definition of "verbatim preservation date"

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#5600]
**Goal**
Update the definition for "verbatim preservation date"; typically, the date when the specimen is collected is the same date as when it ceases to grow and change.

**Context**
When the specimen is collected, it is not necessarily preserved right away. Specimens are put into pressing papers, freezers, etc. until staff have time to prepare them for collections use (pinning, taxidermy, creating study skins, etc.). This can occur the same day as the specimen's collection, or months or years afterwards. There is a difference between when the specimen is no longer growing/changing to when it is ready for collections use/research.

Current definition: "The date the specimen ceased to grow and change, as opposed to the date when it was collected. Often the date of death. Avoid this in favor of additional specimen_event determinations."

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type

**Proposed Value**
Keep "verbatim preservation date" and update the definition (see below)

**Proposed Definition**
New definition: "The date when the preparator finishes preparing the specimen for collections use, i.e., it is mounted, stuffed, taxidermied, etc. and ready to be used for cataloging, research, programming, etc."
(please feel free to edit/add suggestions)

**Collection type**
All collections that "verbatim preservation date" currently applies to.

**Attribute data type**
Free-text

**Attribute value**
date as written on preparator label

**Attribute units**
date

**Available for Public View**
yes

**Other ID BaseURL**
n/a

**ID_References**
n/a

**Media Relationships**
n/a

**Taxon Terms**
n/a

**Priority**
normal

**Comment by dustymc** [comment]
This cannot proceed; it would incorrectly change the nature of many records.

The use case is that an animal is collected when it's removed from nature (from way back in the dark ages when only one untyped event was possible), verbatim preservation date was introduced as the date of death (which might be hours later for a karyotype or years later for a captive program).

I think you're asking for some new thing (and it should probably be a part attribute, because parts are what preparators concern themselves with).

**Comment by wellerjes** [comment]
Can we use the definition I provided with a new term? We have been using "verbatim preservation date" as the date when the preparator readies the specimen for collections use; it wasn't until I was working with our intern the other day that I realized the definition was not as I understood it.

**Comment by dustymc** [comment]
Yes, but maybe a new issue without any unnecessary entanglements.

(Sorry, I was trying to do the least confusing thing and might have done the opposite - I'll close, but feel free to do whatever if that's not adding clarity!)

**Comment by ewommack** [comment]
@wellerjes - we put the date of preservation as the date the attributes are created for an object. 

For an example, I collected a bird on 1 July 2020 and then my student prepared it on the 15 Jan 2021. I would put down the verbatim date and the event date as the 1 July 2020, and the date for all of the attributes determination (weight, skull ossification, molt, sex, reproductive data, stomach contents) would be the 15 Jan 2021. I would also list myself as the collector, and my student as the preparator. I'd tie my student as the determiner of the attributes not me.

**Comment by ewommack** [comment]
> "verbatim preservation date" does not match the related definition which really indicates "date euthanized" but we are afraid to say that.

If we're lucky it represents the date of death. Most of the time it is the date I found this thing out in the wide world and I have brought it in to be part of a collection.
@Nicole-Ridgwell-NMMNHS - does verbatim date represent the estimated date of death for your collection? That would be really cool.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> does verbatim date represent the estimated date of death for your collection? That would be really cool.

We don't use this attribute, "estimated date of death" for us is either the geologic age of the rock strata the specimen was found in or a radiometric date, both of which have their own fields.

**Comment by Jegelewicz** [comment]
@ewommack we aren't talking about verbatim date but the attribute [verbatim preservation date](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#verbatim_preservation_date).

**Comment by ewommack** [comment]
> the attribute [verbatim preservation date](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#verbatim_preservation_date).

Sorry! 
Ignore my comments on salvage then.

**Comment by wellerjes** [comment]
Thanks for this info! I think I can go back and correct the verbatim preservation date attributes we have added to our collections records through an attribute bulkload/unload.

Would it be possible to change the terminology of "verbatim preservation date" and replace "preservation" with something else? I realize that euthanize is not ideal, but it's confusing to use "preservation" in a different context, given how we use "[part preservation](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_preservation)" to mean how it is prepared (study skin, ethanol, etc.).

**Comment by dustymc** [comment]
>IMO "verbatim preservation date" does not ...

This is *_precisely_* why we have definitions (and why I'm always complaining about the wikipedia copypasta). What any one person thinks a term should mean, or why we've chosen that particular term to mean that particular thing, is completely irrelevant. We have a definition, the term means what the definition says it means (which is often not very informative, but it can and should be).

I think 'preservation' decently describes the situation, we don't say or mean 'preparation' (nor do we say or mean 'euthanasia' which would be a difficult concept to apply to some taxa, and I suppose even things like crystal, stalagmites, eDNA samples, etc. which might undergo similar processes). This is the same idea as part preservation, but applies to "whatever someone felt like cataloging" rather than a specific physical part of said whatever.

That said, there's no technical reason to keep most terminology and it could be changed.

**Comment by dustymc** [comment]
done?

**Comment by Jegelewicz** [comment]
I think Code Table Committee should review.

**Comment by Jegelewicz** [comment]
@dustymc can we get a list of collections using this attribute?

**Comment by Jegelewicz** [comment]
@ArctosDB/arctos-code-table-administrators say that we need to either change the definition or add a new term - it seems that most people are using this in the way described by @wellerjes and the term itself indicates that. Then we need to figure out who should continue with the attribute and document how "kept alive in captivity some time after collection from the wild" should be recorded.

Suggesting is to add an event of type [captive](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcollecting_source#captive), with start date = ended date of [wild](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcollecting_source#wild) collection event and ended date of date of "dispatch".

**Comment by campmlc** [comment]
I like the idea of a captive event type, now that we have the ability to have multiple events. The Rausch collection has used the attribute verbatim preservation date to record date of death of a captive animal, but there aren't a huge number of these: https://arctos.database.museum/saved/Rausch%20Verbatim%20Preservation%20Date%20as%20Date%20of%20Death
It would be better to create two events, one for removal from wild, one for death, although it is not always clear where the animal was held or died. 
But I need to make sure we don't lose these data in a big data conversion - as for these records, verbatim preservation means date of death.

**Comment by ewommack** [comment]
It might be helpful with collections that receive animals from rehab hospitals. Sometimes those animals are kept in captive settings for a while.

**Comment by Jegelewicz** [comment]
AWG - says need a new code table term for preservation date

We need a count by colelction to figure out who is using it how and migrate as appropriate.
