### ISSUE TITLE
Data Entry Pull/Sync functions

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#5601]
Some requests for fixes/updates to the new Data Entry form:

1) The locality table now has a very nice Pull/Sync Locality etc box which is clearly visible. However, there is no such box for Collecting  Event ID. Can we add one please?

2) If we use the pull function in OtherID to pull collecting event information from another record, the Collecting Event ID autopopulates but no data autopopulates the event fields, leading to confusion as to whether the verbatim date and locality info need to be entered. However, when this same tool is used to Pull/Sync Locality, the locality fields autopopulate. Can we get this functionality in CE Event, please?

3) The Other ID pull tool is almost invisible, as the light blue font is very tiny and the color does not contrast with the green data entry background. Can we change that tool so it looks exactly like the Pull/Sync Locality box, except that it says Pull/Sync from Other ID?

4) Finally, this is a general request: any way we can get rid of avocado green and puke pink as the background colors for data entry enter and error screens, and possible use some of our Arctos template colors here?

Priority: Normal to High. These tools are necessary for parasite collection management, and although there aren't very many of us, our numbers are increasing.

**Comment by AJLinn** [comment]
> any way we can get rid of avocado green and puke pink as the background colors for data entry enter and error screens, and possible use some of our Arctos template colors here?

I ran this idea past my staff person who has visual triggers to migraines and her thought was that a nice light blue background for the data entry page would be a calm color for those with sensitivities (similar to the search page colors). And then a good contrasting color to blue (she thought perhaps a light yellow or goldenrod) for the error color would work? We're using that shade for the public access button alert - that might be a good consistent use?

Incidentally, that colored background for the data entry page is only visible if you only create one record. Once you save it, the background goes to white... should I submit an issue?

**Comment by campmlc** [comment]
I like the idea of using the same color templates as our new search page.
And a yellow for error works too - maybe with the error message showing up
at both top and bottom of page?

**Comment by campmlc** [comment]
Upping priority - I now have a student using the Pull function for data entry to link parasites and hosts for a grant funded project. I would like to see these tools updated as requested to improve user functionality and reduce error.

**Comment by campmlc** [comment]
Please - I need this fixed. I have a student hired who is at a standstill because this tool is not working. 
Summary of the problem:
1) The student needs to use the Pull function to get the host information for parasite record data entry, so that host and parasite share collecting event and locality and collectors.

2) Currently, the Pull function pulls the correct Collecting Event ID  and Locality ID. But the yellow data fields for higher geography, date, and locality are completely blank, so there is no way to check the accuracy of these data.

3) Even more concerning, at point the student working on this used "start from existing" to start data data entry. So in this case, even though she used the PULL function for Collecting Event, the fields are still populated with the previous records data. So she sees data saying the specimen was collected in Mongolia when in fact it was collected in Alaska - but the CE ID is correct for Alaska. She's trying to fix things, but making it worse. A giant mess. This could be fixed if the correct data pulled into the Collecting Event fields in Data Entry. 

2)	Once a record is saved, if you go back in to Edit the record, the Pull function is gone. We need this back in the Edit view  - otherwise the student is having to go into enter from seed where she can still access the Pull function, and copy information. Again, a giant mess.

**Comment by campmlc** [comment]
Correction - the collecting event and locality data are not showing in the Browse and Edit Table AT ALL, even though the pull function was successfully used to pull in the CE ID and Locality ID into the saved record in Data Entry.
So something is seriously broken.

**Comment by dustymc** [comment]
I need more information - there's some unrealistic expectation that I don't quite understand here, or ????

The documentation is accurate: "A value here will over-ride anything entered into higher_geog, spec_locality, coordinates, etc." Expecting me to keep random things (including that Excel on your hard drive?!) synced up with ever-changing data - well, I can't. Whatever the expectation, that's just not technically plausible.

I could also use some elaboration on "the pull function" - there are a bunch of ways to specify various pre-existing data, a couple ways to sync the entry screen with current remote data, some things you say don't exist clearly do, I need more information.

<img width="580" alt="Screenshot 2023-03-29 at 12 34 08 PM" src="https://user-images.githubusercontent.com/5720791/228648294-8140474b-51e9-4e8c-9575-89d971f839b8.png">

See also https://github.com/ArctosDB/arctos/issues/5292.

I will rebuild the form for https://github.com/ArctosDB/arctos/issues/5193, which I think is now scheduled for discussion and perhaps finalization at the 2023-04-06 Issues meeting.  It would be good to get the expectations clearly expressed before then.

Colors should probably be discussed in https://github.com/ArctosDB/internal/issues/220, but implementing them might require something beyond palette.

**Comment by campmlc** [comment]
We used to use this same function, and the data would pull along with the
Locality and CE ID. I'm not asking for anything new. Have we lost this
functionality?
The Pull button visible on edit is critical. Holding up work.

**Comment by DerekSikes** [comment]
Yes, this was already functional in the old data entry form. You enter a CE ID or 'name' and hit tab and all the fields for collection event and locality would fill in (but be grey to show the data were pulled). Now, you hit tab and nothing happens so users get no feedback its worked. Worse, and related to my problems with habitat & collection methods fields being in specimen rather than collection events, when I enter these data into the remarks field of collection events, hoping my students can see those entries and then re-enter them into the actual specimen event fields... they can't see them! The data are not pulled in.

**Comment by dustymc** [comment]
>used to

Yes, we still do, and we used to too.

>tab

I don't think that's compatible with the current form, and I don't think the buttons present an insurmountable obstacle.

>nter these data into the remarks field

You lost me somewhere in there, I really need specifics if I'm going to successfully address whatever's going on here.

**Comment by campmlc** [comment]
I'm not sure I understand what is causing the problem.. It is quite clear
that the Pull function is not pulling these data into Data Entry. It is
also definite that they used to do so. So if it is possible for this to
happen, can we get that functionality back, please? If this is not
possible, then that is a whole other level of problem.

From what I understand, Derek is putting info into a named collecting event
remarks field that used to populate into and be visible from data entry
when the named event was picked. He needs students to be able to see those
data in Data Entry in the Collecting Event fields and copy them into
Specimen Events - because his request to have those fields transferred to
Collecting Event was denied.

**Comment by dustymc** [comment]
>Pull function is not pulling these data into Data Entry. 

Screenshots or something?? I cannot replicate this, it works for me and (excepting depth units) everyone else, as far as I know.

>see those data in Data Entry

Click the button, there they are??? I am clearly not understanding something, please, someone, anyone, fill in the blanks??

<img width="289" alt="Screenshot 2023-03-29 at 2 04 35 PM" src="https://user-images.githubusercontent.com/5720791/228667123-cd95ca6a-0f0c-411c-9191-72e39b335b1d.png">

>request to have those fields transferred to Collecting Event was denied.

Which has no affect whatsoever on what can be done, and I have no idea how that would involve remarks?

Maybe this is another place a task force could help, I don't know, one or more of us clearly does not understand something.

**Comment by campmlc** [comment]
I will try to document our workflow with a series of screenshots.

1) Entering a new record from seed (same happens when starting from scratch). I can use the "Pull" tool with other identifiers so I can pull the UAM host data (based on the IF number) into the parasite record, with relationship "parasite of". But the Pull tool font is so light it is barely visible -**please make the same font and size and the "Pick" functions next to Collecting Event and Locality IDs.**

![Screenshot 2023-03-29 19 51 15](https://user-images.githubusercontent.com/14808196/228708719-8fae757f-727f-48a3-8ca7-5c35fc6f08ea.png)

2) Once Pull is selected, I can choose to pull collecting event, locality, collectors, attributes, and identifications. Since this is a parasite record, I choose only the first three from the host data.
![Screenshot 2023-03-29 19 52 06](https://user-images.githubusercontent.com/14808196/228709085-53aa6064-0a99-4bc0-b22c-49b731ac35df.png)

3) Note that when the pull function is used, the Collecting Event ID and the Locality ID populate the respective tables. But:  The data associated with these IDs does not populate the relevant fields. **This is what we are asking for.** This is what used to happen  when we either picked events or pulled event data from other IDs - and now no longer does.

![Screenshot 2023-03-29 19 51 15](https://user-images.githubusercontent.com/14808196/228709646-a5232760-3930-46bc-a698-0be4584864c1.png)

4) I save the record and go to Browse and Edit, filter on my user name. Note that the collecting event ID and locality ID are visible, but no other relevant information in higher geography or locality that we can use to verify that we indeed selected the right data, and to avoid students thinking they have to enter it (I've had this happen too).

![Screenshot 2023-03-29 19 53 25](https://user-images.githubusercontent.com/14808196/228709331-1e014573-8638-452d-a430-fbdff968c876.png)

![Screenshot 2023-03-29 19 54 02](https://user-images.githubusercontent.com/14808196/228709951-61a9de82-b823-4533-aec1-97954d08a19f.png)


5) If we then need to check the record from Browse and Edit to make additional edits, by clicking on the key field to the left of [old edit] - this is what we see. NOTE that the Pull function that should be next to other identifiers is no longer there. If the student wants to check to make sure that the record is pulling the data correctly, or wants to go back and add the verbatim host ID, they can no longer access the data from the related record. **This Pull function next to other identifiers is what I am requesting should be added back in to the Edit screen in Browse and Edit - with the requested larger font and darker font color.**

![Screenshot 2023-03-29 19 54 30](https://user-images.githubusercontent.com/14808196/228710814-1ebd3ded-6802-45ce-84bc-11ce99d17f6f.png)

**Comment by Jegelewicz** [comment]
This may be totally crazy, but are those fields set to carry in the form? Could that be the problem?

**Comment by dustymc** [comment]
Thank you!

>Pull tool

it's a button in next release.

>This is what we are asking for. 

Choose (or specify names/ID in whatever way), then click this: 

<img width="102" alt="Screenshot 2023-03-30 at 7 30 00 AM" src="https://user-images.githubusercontent.com/5720791/228869438-e5045045-bbbf-440b-8843-74518f5b0bd2.png">

(Or the locality version.)

Edit is https://github.com/ArctosDB/arctos/issues/4711, but maybe that makes a bit more sense in light of some above comments. Would something like a "show this" button which opens a locality/event *current* data overlay do this? That would be more approachable from a sustainability and diversity perspective. (There's a LOT of breadth to Arctos these days, just about 100% chance that a button which cryptically _replaces_ data is going to be absolutely DEVASTATING to a few users, a view is completely safe.)

>fields set to carry

That probably won't do it, but the necessary button can be turned off with customization.

**Comment by campmlc** [comment]
RE: "Edit is https://github.com/ArctosDB/arctos/issues/4711, but maybe that makes a bit more sense in light of some above comments. Would something like a "show this" button which opens a locality/event current data overlay do this?"
I guess I don't understand why we can have the pull button in initial data entry but not in Edit? Can't it work the same way? Which is a pop up screen, like what you are describing?

**Comment by dustymc** [comment]
> just toggling back and forth 

No, also for sustainability reasons. The old form had limited customization and was still almost impossible to make sure you see everything in "edit mode." The new has those separated, "edit mode" always shows everything, so the entry form can be much more complicated. (There's a long Issue somewhere....)

>It looks like exactly the same form

If you've got everything on in table most that should be SORTA correct, otherwise I'm not sure you're looking at the right form???

>Can't it work the same way? 

It could, but that introduces the aforementioned problem. If there's some other way that avoids things that some users will rightly see as horrid then I'd like to explore it.

>so students don't get confused.

I think it's as simple as it safely can be.

>Which is a pop up screen, 

IDK, doesn't exist yet, something that would "translate" a name or ID into current data (probably as a table but ??) - click some button, see current data. (Maybe even the view page in an overlay?)

**Comment by campmlc** [comment]
Maybe we can do a quick zoom so I can show you what the interface looks
like from the student perspective? Nothing you are saying makes sense from
what we see. But whatever needs to happen to the back end, hopefully we can
see something similar to what we see now from the front end.

**Comment by dustymc** [comment]
sure, say when

**Comment by campmlc** [comment]
I can do 4 or 4:30 pm MDT?

**Comment by campmlc** [comment]
I could do tomorrow am after 10 am your time?

**Comment by dustymc** [comment]
Sounds good.

**Comment by campmlc** [comment]
OK - calendar invite sent - see edited version.

**Comment by dustymc** [comment]
Calling this next release, I think all is understood now.
