### ISSUE TITLE
Need password reset help

### ISSUE THREAD

**Issue by gradyjt** [ArctosDB/arctos#5607]
Hello, I haven't logged in to Arctos for a while so I'm guessing my profile is locked or something. I tried requesting a password reset a couple of times, but got nothing. My username is gradyjt and my e-mail is Rodkey10@gmail.com Thanks for your help.

**Comment by campmlc** [comment]
Looks like someone got to it already? It says open and active. Let me know
if something is still not working . . .

**Comment by dustymc** [comment]
reset and forwarded password request via email

@mkoo https://github.com/ArctosDB/internal/issues/177#issuecomment-1382189020
