### ISSUE TITLE
Low Quality Agent - William Apsu Perry

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5611]
How did this agent survive the purge?

[William Apsu Perry](https://arctos.database.museum/agents.cfm?agent_id=21325772)

Suggest changing to verbatim in the two records where the name is used as a collector.

**Comment by dustymc** [comment]
<img width="359" alt="Screenshot 2023-02-07 at 8 55 34 AM" src="https://user-images.githubusercontent.com/5720791/217311408-ea939312-5b71-4718-9645-dd8b9e5a00d4.png">

The Purge involved only the most low-hanging fruit. There are still many thousands of no-information (or apparently just wrong information, in the case of this one) agents involved in various activities. We definitely need another cleanup-or-something if we're to get to somewhere magical, but I'm not sure what that should involve. @lin-fred 

And a very quick scan suggests the two suggested duplicates of that agent (they're probably not) are duplicates of each other @AJLinn @krgomez

**Comment by Jegelewicz** [comment]
> most low-hanging fruit. 

Maybe the agent is doing something else that I can't see? This agent has absolutely no data other than names and is only involved in the collector role - I thought all of those were converted to verbatim. If that is not what happened, can you tell us exactly what did so we can prioritize the next set of clean-up?

**Comment by lin-fred** [comment]
> How did this agent survive the purge?
> 
> [William Apsu Perry](https://arctos.database.museum/agents.cfm?agent_id=21325772)
> 
> Suggest changing to verbatim in the two records where the name is used as a collector.

This is because of the identification that dusty screenshotted that kept it from verbatimizing.

Although there are still plenty more no or low information agents, I think we should beef up the documentation and get some of the tools/how-to's for cleaning agents done first, before discussing more agent changes.

**Comment by Jegelewicz** [comment]
Got it - for this case I would support changing the determiner to unknown and adding a verbatim agent with method "identification determiner". Maybe this should be the next level of hanging fruit.

**Comment by dustymc** [comment]
>beef up the documentation

Agreed - I think people are still creating "probably alive when they were collecting, and try not to think about where that [date might have come from](https://github.com/ArctosDB/arctos/issues/5612#issuecomment-1421169175)" stuff which suggests there's still some confusion regarding where we're trying to go with this. (LESS work for BETTER data, not MORE work for WORSE data!)

> changing the determiner to unknown and adding a verbatim agent with method "identification determiner"

Also seems reasonable - it's not quite what I had in mind way back when, but continuing forward with small steps (whatever the details, and hopefully reinforced by better and better documentation) seems right at this point.

**Comment by Jegelewicz** [comment]
> Edit for example: https://arctos.database.museum/agent/21292419

I just don't know how to stop this. Some people are really attached to the idea of an agent page, no matter that it contains absolutely no information. I also don't know how to make the documentation any better or how to make long-time users read updated documentation. we either have to disallow stuff or understand that people are going to create meaningless agents. Making it a little harder helps, but clearly doesn't deter a determined person. Maybe the alive and dead things shouldn't count against "thou shalt provide some information that tells me who this is"?

**Comment by krgomez** [comment]
Why is an agent that we know was alive at a particular time less valid than an agent we know a birth year for? It feels arbitrary and I think that curatorial discretion should be allowed for managing agents associated with a particular collection. Particularly given that verbatim agents are excluded from showing as creators in search results, I don't think they are serving as an adequate replacement for full on agents. If this could get fixed, then it would be fine to make K.R.S. a verbatim agent if the information we know about this person is too low for the current agent standards, but I wouldn't want to do that at this point.

**Comment by lin-fred** [comment]
> Why is an agent that we know was alive at a particular time less valid than an agent we know a birth year for? It feels arbitrary and I think that curatorial discretion should be allowed for managing agents associated with a particular collection. Particularly given that verbatim agents are excluded from showing as creators in search results, I don't think they are serving as an adequate replacement for full on agents. If this could get fixed, then it would be fine to make K.R.S. a verbatim agent if the information we know about this person is too low for the current agent standards, but I wouldn't want to do that at this point.

@krgomez If the alive date is the same as the collection/creation date - so in the case of K. R. S. 1898, that alive date is not new information. The creation date is inherently a piece of information, so adding it as an alive date is just duplicating that information and not adding anything new.

A birth date adds information that is not inherent to the creation date. If the person was born in 1850, but the creation of the piece was 1898, then you would have 2 pieces of information about the person.

Also, you can find verbatim collectors/creators using both the main search page and the Agents search page? Could you give me an example of the issue you are having? I just tried it on both pages and I was able to find a record with 0.8. Smith, which is a verbatim agent. On the Agent search page you may need to toggle the "Include verbatim agent?" option

**Comment by krgomez** [comment]
That makes sense, thanks for explaining the thinking around this. I love that we are being asked to make agent profiles more robust, and there are certainly some artists that we really just don't know much about who may be totally fine as verbatim agents. I have been doing all that I can to add more information to our agent profiles to make them better. 

Here is an example of the issue I am seeing in the search results:
![Screen Shot 2023-02-07 at 2 35 36 PM](https://user-images.githubusercontent.com/40579515/217391279-5a4f1210-450c-4153-9ce4-eba7c05d8461.png)

Only agents with profiles are showing in the creator column. I guess I can see how this may seem minor, but artists are integral to their works and it's really basic information that should be visible (in a clear way) when searching a collection. I know I can add verbatim agents as a column so that I can see them in my results, but as I mentioned in #5576, the meaning of this will not make sense to average users. Outside of this, searching them and the way they appear in the catalog records is fine.

**Comment by lin-fred** [comment]
Thank you for linking the issue and explaining it, looks like Teresa added it to the agents committee meeting, which is actually this afternoon so it will be discussed. You're information will be great as this is something I am not familiar with.
