### ISSUE TITLE
search fields extending beyond search "box"

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5613]
Something weird is going on here

![image](https://user-images.githubusercontent.com/5725767/212103854-290b0966-0892-42b1-bc68-af041ac2722c.png)

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/arctos/issues/2745#issuecomment-1380536147_

**Comment by dustymc** [comment]
I know this has been filed a few times (maybe even by you??), would be handy to find that....

**Comment by Jegelewicz** [comment]
I t was in the long list of stuff in #2745 (where I copied this from). I don't think it was anywhere else.

**Comment by dustymc** [comment]
Ah thanks.

The main point from over there still stands: I don't have the tools (or skill, but I'm getting better!) to design CSS except on my device (macbook) and the stuff I can simulate (smaller than macbook). I can make the gray wider, but it'll break whatever I made it explicitly narrower for.

BUT, things have changed even on my device, so maybe I can make improvements without going into the 'box.'

First, I'm controlling the size of the text boxes, and could drop those a bit, but I need input on what might work. You can play with that in your browser:

<img width="995" alt="Screenshot 2023-02-08 at 7 14 05 AM" src="https://user-images.githubusercontent.com/5720791/217570375-3420ba8a-0948-4884-b754-55f11be83582.png">

and it'll quickly reveal the biggest change, that the labels and controls embedded in the labels have changed and are now mostly controlling the width of tables.

<img width="948" alt="Screenshot 2023-02-08 at 7 16 15 AM" src="https://user-images.githubusercontent.com/5720791/217571221-cb43cc45-b57a-4c36-b37f-236b1167a906.png">

So two pieces of information I could make use of:
1. Can we make table elements any smaller, and
2. Can we somehow shorten the labels?

**Comment by Jegelewicz** [comment]
> Can we somehow shorten the labels?

My first inclination would be to remove "Attribute" from all except the first one. It seems redundant to keep saying "Attribute" in a table that I can see on  one screen?

Also for the date columns use "Earliest Date" and Latest Date" and lose the parentheses.

Maybe that would be enough?

**Comment by dustymc** [comment]
Not present in current UI
