### ISSUE TITLE
Can't log into Arctos

### ISSUE THREAD

**Issue by szaborac** [ArctosDB/arctos#5616]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I am getting an authentication error when trying to log into Arctos this afternoon. I had no trouble this morning.

**To Reproduce**
1. Go to arctos.database.museum
2. Click on 'Log In or Create Account"
3. At log in, attempt to log in with username Susitna and pwd Qiviut%5 

**Expected behavior**
I have not attempted to change my password since this morning's successful login attempt, so I should be able to log in this time.

Actual Result:
The following error message in red: "Authentication failed. Additional Information: Access restricted. "

**Desktop (please complete the following information):**
 - OS: Mac High Sierra
 - Browser: FireFox, Safari

**Priority**
Sev-1 Pri-1. I am utterly blocked out of doing data entry and modification, uploading metadata, etc.

**Comment by dustymc** [comment]
access limit reset, your most-recent password should work

**Comment by szaborac** [comment]
Awesome. Thank you, Dusty!
