### ISSUE TITLE
Constantly in Loading Process

### ISSUE THREAD

**Issue by coloradosnakes** [ArctosDB/arctos#5618]
Every time I update this updated "Catalog Record Search" window it shows as if it is already processing a search with the blue dots that circulate through at the bottom of the page. It will let me enter things into the search bars but it will not let me submit any queries. Any help is appreciated so I don't have to find the old Catalog Record Search outlet.

**Comment by ewommack** [comment]
hi @coloradosnakes - what is the address you are using to get to the search page?
We've found some people have been having problems with getting results if they are using an old http: address.

Here is the current search page address: https://arctos.database.museum/search.cfm

**Comment by coloradosnakes** [comment]
@ewommack thank you for that link. It appears any time I search it on Google or pull the page up with anything other than clicking on that exact link I still encounter the same issue. I think I may just have to bookmark the page and hope it continues to work. Appreciate your help.

**Comment by ewommack** [comment]
> It appears any time I search it on Google or pull the page up with anything other than clicking on that exact link 

@dustymc - could this just be Google's outside cache, or do we possibly have bad links somewhere that the search pages are catching up on? If they might be on collections own homepages we could send out a reminder to everyone to make sure they have updated their collection search links.

**Comment by dustymc** [comment]
No, if it's what we suspect it's some (possibly old) browser (safari?) somehow avoiding "requests" to move to the secure channel. There is now hopefully an error message rather than a cryptic lack of functionality, but I don't seem to own any devices that will get that far without switching. It would be useful if anyone can confirm that insecure connections are now explicitly denied.

**Comment by coloradosnakes** [comment]
@dustymc I don't know if this helps but I tried opening it on both Google Chrome and Microsoft Edge before I received this link and had the problem described above. I am not sure about the explicit denial aspect you're referring to however.

**Comment by ewommack** [comment]
Thanks for the info @coloradosnakes.

I've also put together an issue to try and track if we anyone gets the error message: https://github.com/ArctosDB/arctos/issues/5640

**Comment by dustymc** [comment]
Thanks @coloradosnakes any info is appreciated, that is very helpful.
