### ISSUE TITLE
Code Table Request - add curation to reasons for download

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5620]
**Goal**
Better track data usage

**Context**
I'd like to know when downloads are for collections work

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctdownload_purpose

**Proposed Value**
curatorial

**Proposed Definition**
Data will be used for purposes of curation.

**Priority**
[  Please choose a priority-label to the right.  ]

**Comment by dustymc** [comment]
No objection from me.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Logged in I never get asked for reason for download. If reason for download is not recorded for operators (?), I would think # of downloads for collections work would end up massively undercounted?

**Comment by dustymc** [comment]
<img width="143" alt="Screenshot 2023-05-23 at 10 42 13 AM" src="https://github.com/ArctosDB/arctos/assets/5720791/9c1051c3-0bf6-4a7b-9b95-f4a252733739">


skips that - there's a (long) discussion somewhere, maybe in google groups.

**Comment by campmlc** [comment]
I support this.

**Comment by ebraker** [comment]
Approved 2023-06-15 code table meeting, added to code table.
