### ISSUE TITLE
Feature Request - agent activity links

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5621]
**Is your feature request related to a problem? Please describe.**

Need better links to data

**Describe what you're trying to accomplish** 

"Assigned 154 events" should link to something.

**Describe the solution you'd like**

link

**Describe alternatives you've considered**
-

**Additional context**

Anything else missing links?

**Priority**

?

**Comment by Jegelewicz** [comment]
![image](https://user-images.githubusercontent.com/5725767/217686490-e52150e5-0aa5-4bb6-bee4-b89b01d9a41d.png)

**Comment by Jegelewicz** [comment]
Also determined part attributes - which isn't on the agent page at all?

**Comment by wellerjes** [comment]
I would like to request that this applies to taxonomy created as well:
![image](https://user-images.githubusercontent.com/93737929/217862142-e02614ad-330c-4b34-b197-afe00637ad72.png)
