### ISSUE TITLE
Agent Split Request - Oscar W. Johnson part 2

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5622]
Use this template if you believe an agent represents more than one person or organization.

**Agent that represents more than one person or organization**
https://arctos.database.museum/agents.cfm?agent_id=1015880

**New Agent**
Provide details that should be associated with a new agent to be split from the agent above.

Unsure 

 - **Agent preferred name:** 
 - **Agent details:**

**Reason for split**
- this is clearly two people based upon the collecting dates.

**Affected Collections**
<html><body>

Collection | Earliest Date | Latest Date | NumberSpecimens | contact
-- | -- | -- | -- | -- 
UCSC:Bird | 1900-01-01 | 2011-02-07 | 47 | 
CRCM:Bird | 1958-06-25 | 1959-06-03 | 5 | @jessicatir 
UCSC:Herp | 2009-11-22 | 2009-11-22 | 1

**Agent change tool**
For any collection that needs to change to the agent created as part of this split, follw the instructions at [How to Batch Update Agents](https://handbook.arctosdb.org/how_to/How-to-Batch-Update-Agents.html)

Please add this issue to the Agents Project.

@ArctosDB/agents-committee

**Comment by Jegelewicz** [comment]
I think this is the UCSC Oscar Johnson? https://www.linkedin.com/in/henicorhina

Also the same person as https://arctos.database.museum/agents.cfm?agent_id=21346298 ?

@mvzhuang can you confirm that?

**Comment by mvzhuang** [comment]
yes. data entry error is something i just missed, but entry should be fixed from now on- updated agent page with more contact info
I'm having trouble getting UCSC to respond further. They need to move all of their 2008-2011 Oscar W. Johnson specimens over to our Oscar Johnson. Oscar's c.v. indicates he was at UCSC during that time period.

I only got partial agreement ->
"Hey Vicky,

This was before my time at UCSC, so I think Chris will be the expert in this matter. Overall your approach sounds solid to me. 

-Alex
"

**Comment by Jegelewicz** [comment]
@dustymc can we make this happen? I don't have access to their collections, but I am confident that all the UCSC Oscar W. Johnso should instead be Oscar Johnson.

**Comment by Jegelewicz** [comment]
@ArctosDB/agents-committee agrees that the UCSC usage should be switched to Oscar Johnson and requests @dustymc to make the switch for us.

**Comment by dustymc** [comment]
I don't believe I have access, and I'm nervous about the general idea of changing data for some collection to which I have no connection. Maybe this is something that should be addressed in MOUs or ?????  @mkoo advise please
