### ISSUE TITLE
Agents & Users

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5626]
I did this, so I should have done it differently in the beginning and maybe it is just the Albuquerque Breaking Bad that is getting to me, but "Agents & Users" gives me drug dealer vibes. Would anyone care if I changed it to "Agents & Operators"?

**Comment by campmlc** [comment]
That's much better.

**Comment by ewommack** [comment]
Makes sense to me. Any thoughts @lin-fred?

**Comment by lin-fred** [comment]
Whether "users" has some other connotation does feel biased but Agents & Operators is more keyword descriptive of what is in that section so that works for me

**Comment by dustymc** [comment]
The tools apply to users who are neither agents nor operators.
