### ISSUE TITLE
Code Table Request - Add Mount Airy 7.5 minute to quad table

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#5627]
**Goal**
I need to add this quad to a locality, and it is not in the code table already

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctquad

**Proposed Value**
Mount Airy 7.5 minute

**Proposed Definition**
This code table does not have definitions

**Proposed Documentation**
Link to this issue

I can add this value if there are no objections.

**Comment by Jegelewicz** [comment]
I have none

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Added
