### ISSUE TITLE
Request to reserve new GUID prefixes

### ISSUE THREAD

**Issue by barke042** [ArctosDB/arctos#5629]
**Issue**: We are creating two new Bell Museum collections and would like to reserve two new GUID prefixes.

**Request**: As requested in the documentation, we are asking for Arctos DBA approval for the following prefixes:

MMNH:Egg (egg and nest collections)
MMNH:Edu (consolidated teaching collections)

**Comment by Jegelewicz** [comment]
Those are fine by me.

**Comment by dustymc** [comment]
No technical problems, just promise you'll love them forever!

``...:Teach`` is more common than ``...:Edu`` but there's no problem with either.

**Comment by barke042** [comment]
Thanks! We went with Edu since we are also going to put in some mounted material that is used more for outreach than coursework so it felt like a better fit. We found another example that was already in Arctos and went with that.
