### ISSUE TITLE
Arctos Report: MVZ wide box labels

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#5632]
**Description of the report** for dry box labels 

**Collection for which the report is needed** - MVZ:Mamm and MVZ:Bird
(I think we need two separate ones after all)

Work in progress and notes are on edited print out at the workstation.

**Comment by mkoo** [comment]
We had a problem with labels getting cut off at the bottom of pages. @JhK830 figured out how to address this in the CSS

in the cell class, she added: ```flex-direction: column;```
with the specific dimensions of the label. The labels are designed to be cut out and placed on top of dry boxes.

Full CSS example below:

```
/* set size is 64 mm wide by 42 mm height */
.cell {
  width: 64mm;
  height: 42mm;
  max-width: 64mm;
  padding: 2px;
  border: 1px black dashed;
  page-break-inside: avoid;
  font-family: Helvetica, sans-serif;
  display: flex;
  flex-direction: column;
  overflow: hidden;
}
```

**Comment by dustymc** [comment]
Interesting! I think https://github.com/ArctosDB/arctos/issues/5767 is browser-print not understanding grid, but it apparently knows flex?! Maybe a point for a how-to or something??

**Comment by mkoo** [comment]
woop-- missed that issue -- print from screen!
yea-- it's a combo of browser/print/ css flex/angels and demons that seem to control your end product here. I will discuss that issue with students too

**Comment by mkoo** [comment]
This is a stale issue that has since moved to the MVZ internal task list
