### ISSUE TITLE
New agent operator set up weirdness

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#5634]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

Trying to get a lab tech added as an operator.

1) had her make a public account
2) I then created an agent for her
3) I tried to add name type login = her user name (Lucyhw)
4) got error "Arctos user does not exist"

had her log out and in. Same error.

I refreshed the page, same error. I waited. Same error.

5) went to another computer, I logged in & searched for her Agent record (Lucy White) but it was not found!!

I know an agent record had been made in step 2 above - I got to the form to edit her agent.

So I then made another Agent record for them. This worked!! (but was very frustrating)

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.
medium

**Comment by dustymc** [comment]
There are no skipped (eg created and deleted) sequence keys leading up to this agent, it wasn't created at about the same time as another, I'm not sure what could have happened. Calling it a glitch in the matrix....

```
arctosprod@arctos>> select agent_id,created_date,getPreferredAgentName(created_by_agent_id), preferred_agent_name from agent where agent_id between 21347267 and 21347277;
 agent_id |        created_date        | getpreferredagentname  | preferred_agent_name  
----------+----------------------------+------------------------+-----------------------
 21347267 | 2023-02-09 07:43:14.493543 | Frederick Keith Barker | Matt Edling
 21347268 | 2023-02-09 11:35:10.371428 | Karinna Gomez          | Helen K. Olifie
 21347269 | 2023-02-09 11:40:55.966121 | Karinna Gomez          | Susie Malgokak
 21347270 | 2023-02-09 11:54:47.208613 | Karinna Gomez          | Harry M. Walker
 21347271 | 2023-02-09 12:16:16.32366  | Karinna Gomez          | Helen MacDonald
 21347272 | 2023-02-09 12:20:41.071493 | Karinna Gomez          | Henry Varnum Poor
 21347273 | 2023-02-09 12:50:31.401077 | Karinna Gomez          | Howard D. Ringley Jr.
 21347274 | 2023-02-09 12:57:25.046456 | Karinna Gomez          | Huntington Witherill
 21347275 | 2023-02-09 13:02:24.354421 | Karinna Gomez          | J. Shadrach
 21347276 | 2023-02-09 15:18:50.588419 | Angela Linn            | William Howard Taft
 21347277 | 2023-02-09 16:37:43.101282 | Derek S. Sikes         | Lucy White
(11 rows)

```
