### ISSUE TITLE
Can't get the Bulkload Parts to Container Tool to work anymore

### ISSUE THREAD

**Issue by atrox10** [ArctosDB/arctos#5635]
I formerly used the Bulkload Parts to Container Tool to put parts (whole organism) into barcoded jars for me. You can see that here:
https://arctos.database.museum/tools/BulkloadPartContainer.cfm
We are labeling our jars with barcodes, make an inventory of what's in the jar, and then I upload a CSV to this site to get the whole organisms into the jars. There are multiple part (whole organisms) in one jar. This use to work fine but lately I have been having issues/errors where it's saying the "parts are already in a container" and won't put them into the barcoded jar. 
For example, one record that it says is already in a container: https://arctos.database.museum/guid/MVZ:Herp:225661
I am trying to put the whole organism into this jar barcode: MVZ3169-JAR0030
Right now its in our default location: [ ] Museum of Vertebrate Zoology (institution)
It used to replace the "[ ] Museum of Vertebrate Zoology (institution)" with the jar barcode but it isn't anymore.
**Am I doing something wrong, or is there a different tool that will move my whole organism parts into a barcoded jar?**

**Comment by atrox10** [comment]
Hi Dusty
Anyway you can help with this soon!!?? Otherwise I have to upload these barcodes by hand, which is a giant pain (for over 300 animals). I already uploaded this set by hand (see attach
[bulkloadPartContainerData.csv](https://github.com/ArctosDB/arctos/files/10725135/bulkloadPartContainerData.csv)
ed CSV), for some reason ALL of thse went into "can't find one part" error so I think this whole tool is broken. I uploaded them by hand and deleted the errors but something really funky is happening.

**Comment by dustymc** [comment]
@atrox10 I think this is just a symptom of https://github.com/ArctosDB/arctos/issues/5512 so I'm merging and reprioritizing.

I'll try to get to that this week, ping me Thursday if that's still open and I'll figure something out, or reopen this if that doesn't work for you.

**Comment by atrox10** [comment]
Okay here is the CSV I uploaded that got stuck in the "can't locate part" error (the other one was the problems I downloade) - 
[Sceloporus MexicoPhrynobatrachus francisci - Sheet2.csv](https://github.com/ArctosDB/arctos/files/10725266/Sceloporus.MexicoPhrynobatrachus.francisci.-.Sheet2.csv)

**Comment by dustymc** [comment]
Thanks - I'll check the loader when I can and update the docs as necessary, but I think GUID might be case-sensitive ("MVZ:Herp:1111").

**Comment by atrox10** [comment]
ok so they should be MVZ:HERP:1111 or MVZ:Herp:1111?

**Comment by dustymc** [comment]
https://arctos.database.museum/home.cfm will tell you - it should be MVZ:Herp (and next release will ACTUALLY say that....)

**Comment by atrox10** [comment]
Thank you!!! :)
