### ISSUE TITLE
Feature Request - Accession Remarks be made private when Accession is public

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#5637]
This may be more relevant for cultural collections, but having some Accession information publicly available is helpful for discovery; however, we would only do so if we can keep **Remarks** private only to those with editing permissions. Thus like many other forms (eg agents) we are requesting a curatorial remarks section. Nature of Material would become the main public content for public accessions.

For those with public accessions, how would that impact your public/private accns? @AJLinn

**Comment by AJLinn** [comment]
Yes, I agree this is a great idea and keeping the accession remarks private / used for curatorial remarks is exactly how we are using the field. 100% support this process.

**Comment by dustymc** [comment]
> requesting a curatorial remarks section. Nature of Material would become the main public content f

Can this be satisfied by withholding remarks for 'public' transactions and updating the documentation regarding NoM, or is another remarks necessary?

**Comment by mkoo** [comment]
> Can this be satisfied by withholding remarks for 'public' transactions and updating the documentation regarding NoM, or is another remarks necessary?

that's exactly what I'm asking for (and I think Angie is saying the same). NoM is part of public transactions but the remarks is not. No new remarks field needed. We need to have the web form indicate that remarks is 'internal' or 'not viewable by public' 

We requested the same for Agents where we have some comments are public and some are 'curatorial' and internal viewing only. Example:

![Firefox_Screenshot_2023-02-16T05-06-34 265Z](https://user-images.githubusercontent.com/2523089/219273694-75812b0b-6c7d-4c28-bb90-5b27affec1b7.png)

**Comment by dustymc** [comment]
>NoM is part of public transactions but the remarks is not

I know how to do that, going next task.
