### ISSUE TITLE
Looking for info on insecure connection access

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#5640]
**Call out to all Arctos users:**

If you find an old insecure Arctos link (http rather than https) it should send you to an error message. Can anyone confirm that they are getting the error message please?

**Comment by dustymc** [comment]
> it should send you to an error message.

Arctos should seamlessly redirect http links to the secure site. If your device somehow evades that process you should get an error, and I would be very interested in knowing sufficient detail to re-create.

**Comment by mkoo** [comment]
Redirects function seems pretty solid. Closing for now
