### ISSUE TITLE
Code Table Request - add collection type ES to attribute width

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#5642]
**Goal**
I'm databasing specimens with width data, I need to be able to load it.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type

**Collection type**
ES

If there are no objections, I will add ES to the width attribute.

**Comment by Jegelewicz** [comment]
I say add it.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Added.
