### ISSUE TITLE
Attempting to add items to loan using new form: Need Help with Arctos Error

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#5648]
# Error Text
<div style="color: rgb(0, 0, 0); font-family: Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; border: 2px solid green; padding: 1em; margin: 1em; text-align: center;">Please<span> </span><a target="_blank" class="external" href="https://github.com/ArctosDB/arctos/issues/new?assignees=&amp;labels=contact&amp;template=contact-arctos.md&amp;title=error%20feedback" style="text-decoration: none; color: var(--arctoslinkcolor);">contact us</a><span> </span>if you need assistance in resolving this error. Include the ERROR_ID (below)<span> </span><strong>as text</strong><span> </span>and enough information for us to re-create the problem.</div>

ERROR_ID | 7F8D827B-A655-4F88-BDD44B54BF2E2806
-- | --
ERROR_TYPE | SQL
ERROR_MESSAGE | ERROR: Data Loans may contain only cataloged items Where: PL/pgSQL function trigger_fct_trg_loan_item_biu() line 9 at RAISE
ERROR_DETAIL |  
ERROR_SQL | INSERT INTO loan_item ( TRANSACTION_ID, COLLECTION_OBJECT_ID, RECONCILED_BY_PERSON_ID, RECONCILED_DATE, ITEM_DESCR, ITEM_INSTRUCTIONS, LOAN_ITEM_REMARKS ) VALUES ( 21136051, 22487023, 21247374, current_date, 'UWYMV:Mamm:2048 skull', null, null )

</div>Please [contact us](https://github.com/ArctosDB/arctos/issues/new?assignees=&labels=contact&template=contact-arctos.md&title=error%20feedback) if you need assistance in resolving this error. Include the ERROR_ID (below) as text and enough information for us to re-create the problem.
ERROR_ID	7F8D827B-A655-4F88-BDD44B54BF2E2806
ERROR_TYPE	SQL
ERROR_MESSAGE	ERROR: Data Loans may contain only cataloged items Where: PL/pgSQL function trigger_fct_trg_loan_item_biu() line 9 at RAISE
ERROR_DETAIL	
ERROR_SQL	INSERT INTO loan_item ( TRANSACTION_ID, COLLECTION_OBJECT_ID, RECONCILED_BY_PERSON_ID, RECONCILED_DATE, ITEM_DESCR, ITEM_INSTRUCTIONS, LOAN_ITEM_REMARKS ) VALUES ( 21136051, 22487023, 21247374, current_date, 'UWYMV:Mamm:2048 skull', null, null )
request dump:

request
node_name	
string	arctos-2021
rdurl	
string	/info/loan_item_pick.cfm
uuid	
string	7F8D827B-A655-4F88-BDD44B54BF2E2806
exception dump:

Catch
Entries: 15
additional	
Struct (ordered)
SQL	
string	INSERT INTO loan_item ( TRANSACTION_ID, COLLECTION_OBJECT_ID, RECONCILED_BY_PERSON_ID, RECONCILED_DATE, ITEM_DESCR, ITEM_INSTRUCTIONS, LOAN_ITEM_REMARKS ) VALUES ( 21136051, 22487023, 21247374, current_date, 'UWYMV:Mamm:2048 skull', null, null )
DatabaseName	
string	PostgreSQL
DatabaseVersion	
string	12.2
DriverName	
string	PostgreSQL JDBC Driver
DriverVersion	
string	42.2.20
Datasource	
string	user_login
DataSource	
string	user_login
Detail	
string	
ErrorCode	
string	0
Extended_Info	
string	
ExtendedInfo	
string	
Message	
string	ERROR: Data Loans may contain only cataloged items Where: PL/pgSQL function trigger_fct_trg_loan_item_biu() line 9 at RAISE
NativeErrorCode	
number	0
queryError	
string	INSERT INTO loan_item ( TRANSACTION_ID, COLLECTION_OBJECT_ID, RECONCILED_BY_PERSON_ID, RECONCILED_DATE, ITEM_DESCR, ITEM_INSTRUCTIONS, LOAN_ITEM_REMARKS ) VALUES ( 21136051, 22487023, 21247374, current_date, 'UWYMV:Mamm:2048 skull', null, null )
Sql	
string	INSERT INTO loan_item ( TRANSACTION_ID, COLLECTION_OBJECT_ID, RECONCILED_BY_PERSON_ID, RECONCILED_DATE, ITEM_DESCR, ITEM_INSTRUCTIONS, LOAN_ITEM_REMARKS ) VALUES ( 21136051, 22487023, 21247374, current_date, 'UWYMV:Mamm:2048 skull', null, null )
SQLState	
string	45371
StackTrace	
string	lucee.runtime.exp.DatabaseException: ERROR: Data Loans may contain only cataloged items Where: PL/pgSQL function trigger_fct_trg_loan_item_biu() line 9 at RAISE at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553) at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285) at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323) at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481) at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401) at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164) at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:153) at lucee.runtime.type.util.QueryUtil.execute(QueryUtil.java:328) at lucee.runtime.type.QueryImpl.execute(QueryImpl.java:296) at lucee.runtime.type.QueryImpl.<init>(QueryImpl.java:235) at lucee.runtime.tag.Query.executeDatasoure(Query.java:1134) at lucee.runtime.tag.Query._doEndTag(Query.java:699) at lucee.runtime.tag.Query.doEndTag(Query.java:565) at info.loan_item_pick_cfm$cf$2ab.call(/info/loan_item_pick.cfm:847) at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:1015) at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:938) at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:219) at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:44) at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2482) at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2468) at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2439) at lucee.runtime.engine.Request.exe(Request.java:45) at lucee.runtime.engine.CFMLEngineImpl._service(CFMLEngineImpl.java:1198) at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:1144) at lucee.loader.engine.CFMLEngineWrapper.serviceCFML(CFMLEngineWrapper.java:97) at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:51) at javax.servlet.http.HttpServlet.service(HttpServlet.java:590) at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74) at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129) at org.cfmlprojects.regexpathinfofilter.RegexPathInfoFilter.doFilter(RegexPathInfoFilter.java:47) at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68) at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68) at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117) at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at runwar.Server$1.handleRequest(Server.java:510) at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52) at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:280) at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79) at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134) at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131) at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:260) at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79) at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100) at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387) at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852) at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35) at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019) at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558) at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449) at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280) at java.lang.Thread.run(Thread.java:750)
TagContext	
Array
1	
Struct
codePrintHTML	
string	845: &lt;cfqueryparam value=&quot;#thisIR#&quot; CFSQLType=&quot;cf_sql_varchar&quot; null=&quot;#Not Len(Trim(thisIR))#&quot;&gt;<br> 846: )<br> <b>847: &lt;/cfquery&gt;</b><br> 848: &lt;cfquery name=&quot;setDisp&quot; datasource=&quot;user_login&quot; username=&quot;#session.dbuser#&quot; password=&quot;#decrypt(session.epw,session.sessionKey,'AES/CBC/PKCS5Padding','hex')#&quot;&gt;<br> 849: UPDATE coll_object SET coll_obj_disposition = &lt;cfqueryparam value=&quot;#thisDisp#&quot; CFSQLType=&quot;cf_sql_varchar&quot;&gt;<br>
codePrintPlain	
string	845: <cfqueryparam value="#thisIR#" CFSQLType="cf_sql_varchar" null="#Not Len(Trim(thisIR))#"> 846: ) 847: </cfquery> 848: <cfquery name="setDisp" datasource="user_login" username="#session.dbuser#" password="#decrypt(session.epw,session.sessionKey,'AES/CBC/PKCS5Padding','hex')#"> 849: UPDATE coll_object SET coll_obj_disposition = <cfqueryparam value="#thisDisp#" CFSQLType="cf_sql_varchar">
column	
number	0
id	
string	??
line	
number	847
Raw_Trace	
string	info.loan_item_pick_cfm$cf$2ab.call(/info/loan_item_pick.cfm:847)
template	
string	/usr/local/webroot/info/loan_item_pick.cfm
type	
string	cfml
# Where it happened
On the new add items to loan page

# Steps to get there
Created a loan, then went to add objects to it. The objects came up ok. I selected only the skulls for the different objects, and then clicked the "Add all checked parts to transaction" and got the above error message.

# Problem
I can try the old add records loan form, but I'd like to use the new form if possible.

**Comment by dustymc** [comment]
explicit error for data loans in next release

**Comment by ewommack** [comment]
> explicit error for data loans in next release

So I can't create a data loan at the moment?

**Comment by dustymc** [comment]
I'm not sure what that means, I don't think anything regarding data loans has changed. Most of the download options will provide 'guid' and that (plus the loan number) is all that's required to bulkload items.

**Comment by ewommack** [comment]
So why am I getting an error and can't add anything to the loan?

**Comment by dustymc** [comment]
Because you're trying to add parts to a loan that explicitly will not deal with parts.

**Comment by ewommack** [comment]
Bugger, thanks.
