### ISSUE TITLE
Code Table Request - new media relationship = shows part

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5649]
**Goal**
Describe media contents using the parts code table. We hope that this could lead to searches for parts that not only return records that include those parts, but also media that includes those parts.

**Context**
An image of a bird would include shows_part = whole organism. An image of a karyotype would include shows_part = karyotype. A photo from a camera trap that only shows the tail and leg of an animal would include shows_part = tail and shows_part = leg

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctmedia_relationship

**Proposed Value**
shows part

**Proposed Definition**
Media depicting a part of an object or organism as defined in the Arctos part name code table.

**Media Relationships**
If terms are added to or deleted from the [Media: Relationship Types code table](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctmedia_relationship), please alert the DBA as changes may be required to the Media Metadata Bulkload Tool.

**Priority**
[  Please choose a priority-label to the right.  ]

**Comment by dustymc** [comment]
"please alert the DBA" is an understatement, if that's from the docs they should be updated - full coordination is required (at least when there's a new 'node' involved, as here).

I will need a LOT of UI guidance - I'm struggling to picture what this might look like. (And I think all of the part forms could probably use a revamp, so nice timing?)

>An image of a bird would include shows_part = whole organism

Mostly unrelated, but I think at least those of live birds would more accurately show the cataloged item.

>part = karyotype

I'm getting dizzy...

**Comment by Jegelewicz** [comment]
> more accurately show the cataloged item.

perhaps, but that whole organism in the photo is probably just a skin and skeleton now? No reason that both relationships couldn't be present.

> I'm getting dizzy...

join the club and see https://github.com/ArctosDB/arctos/issues/2596

> what this might look like.

A link to the part name in the part name code table, this helps us explicitly state parts that are in an image AND hopefully allow for easier searching for part-like things across actual parts and representations of those parts in media.

**Comment by dustymc** [comment]
>A link to the part name in the part name code table

???????????????????????????????????????

Are you asking for a label or a relationship??
