### ISSUE TITLE
Can't view collection details

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5651]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

**To Reproduce**
1. Go to Brows collections - https://arctos.database.museum/home.cfm
2. Click on 'Details' for any collection
3. See error

**Expected behavior**
See the collection details

**Screenshots**
![image](https://user-images.githubusercontent.com/5725767/218596866-f4e75422-fb9c-4fb0-90d1-ad7a2af4ab71.png)

<html><body>

ERROR_ID | B64B121C-CC41-441C-81908A3E88DCA6C6
-- | --
ERROR_TYPE | expression
ERROR_MESSAGE | variable [CHECK_FORM_PERMISSIONS] doesn't exist
ERROR_DETAIL |  

</div>
</body>
</html>

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by dustymc** [comment]
can't replicate
