### ISSUE TITLE
Bulk move container giving error

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#5652]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

Click link to 'Bulk Move Container' from the 'Barcodes & Containers ' group of tools and get error below:

ERROR_ID 	35A5A317-94B3-4BCA-A4F641D97E142B83
ERROR_TYPE 	expression
ERROR_MESSAGE 	variable [CHECK_FORM_PERMISSIONS] doesn't exist
ERROR_DETAIL 	

request dump:
request
node_name	
string	arctos-2021
rdurl	
string	/batchScan.cfm
uuid	
string	35A5A317-94B3-4BCA-A4F641D97E142B83

exception dump:
Catch
additional	
Struct (ordered)
Detail	
string	
ErrNumber	
number	0
ErrorCode	
string	0
Extended_Info	
string	
ExtendedInfo	
string	
Message	
string	variable [CHECK_FORM_PERMISSIONS] doesn't exist
StackTrace	
string	lucee.runtime.exp.ExpressionException: variable [CHECK_FORM_PERMISSIONS] doesn't exist at lucee.runtime.type.scope.UndefinedImpl.getCollection(UndefinedImpl.java:434) at includes._headerchecks_cfm$cf.call(/includes/_headerChecks.cfm:231) at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:1015) at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:938) at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:919) at includes._header_cfm$cf$1i3.call(/includes/_header.cfm:184) at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:1015) at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:938) at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:919) at batchscan_cfm$cf$275.call(/batchScan.cfm:2) at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:1015) at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:938) at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:219) at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:44) at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2482) at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2468) at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2439) at lucee.runtime.engine.Request.exe(Request.java:45) at lucee.runtime.engine.CFMLEngineImpl._service(CFMLEngineImpl.java:1198) at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:1144) at lucee.loader.engine.CFMLEngineWrapper.serviceCFML(CFMLEngineWrapper.java:97) at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:51) at javax.servlet.http.HttpServlet.service(HttpServlet.java:590) at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74) at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129) at org.cfmlprojects.regexpathinfofilter.RegexPathInfoFilter.doFilter(RegexPathInfoFilter.java:47) at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68) at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68) at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117) at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at runwar.Server$1.handleRequest(Server.java:510) at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52) at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:280) at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79) at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134) at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131) at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:260) at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79) at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100) at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387) at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852) at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35) at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019) at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558) at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449) at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280) at java.lang.Thread.run(Thread.java:750)
TagContext	
Array
1	
Struct
codePrintHTML	
string	229: where form_path = &lt;cfqueryparam value='#replace(cgi.script_name,&quot;//&quot;,&quot;/&quot;,&quot;all&quot;)#' CFSQLType=&quot;cf_sql_varchar&quot;&gt;<br> 230: &lt;/cfquery&gt;<br> <b>231: &lt;cfif check_form_permissions.recordcount is 0&gt;</b><br> 232: &lt;cfthrow message=&quot;uncontrolled form&quot; detail=&quot;This is an uncontrolled/locked form.&quot; errorCode=&quot;403&quot;&gt;<br> 233: &lt;cfelseif valuelist(check_form_permissions.role_name) is not &quot;public&quot;&gt;<br>
codePrintPlain	
string	229: where form_path = <cfqueryparam value='#replace(cgi.script_name,"//","/","all")#' CFSQLType="cf_sql_varchar"> 230: </cfquery> 231: <cfif check_form_permissions.recordcount is 0> 232: <cfthrow message="uncontrolled form" detail="This is an uncontrolled/locked form." errorCode="403"> 233: <cfelseif valuelist(check_form_permissions.role_name) is not "public">
column	
number	0
id	
string	??
line	
number	231
Raw_Trace	
string	includes._headerchecks_cfm$cf.call(/includes/_headerChecks.cfm:231)
template	
string	/usr/local/webroot/includes/_headerChecks.cfm
type	
string	cfml
2	
Struct
codePrintHTML	
string	182: &lt;/cfif&gt;<br> 183: &lt;/div&gt;&lt;!---- the_whole_header ----&gt;<br> <b>184: &lt;cfinclude template=&quot;/includes/_headerChecks.cfm&quot;&gt;</b><br>
codePrintPlain	
string	182: </cfif> 183: </div> 184: <cfinclude template="/includes/_headerChecks.cfm">
column	
number	0
id	
string	??
line	
number	184
Raw_Trace	
string	includes._header_cfm$cf$1i3.call(/includes/_header.cfm:184)
template	
string	/usr/local/webroot/includes/_header.cfm
type	
string	cfml
3	
Struct
codePrintHTML	
string	1: &lt;cfset title=&quot;Move Containers&quot;&gt;<br> <b>2: &lt;cfinclude template=&quot;/includes/_header.cfm&quot;&gt;</b><br> 3: &lt;script&gt;<br> 4: jQuery(document).ready(function() {<br>
codePrintPlain	
string	1: <cfset title="Move Containers"> 2: <cfinclude template="/includes/_header.cfm"> 3: <script> 4: jQuery(document).ready(function() {
column	
number	0
id	
string	??
line	
number	2
Raw_Trace	
string	batchscan_cfm$cf$275.call(/batchScan.cfm:2)
template	
string	/usr/local/webroot/batchScan.cfm
type	
string	cfml
type	
string	expression

**To Reproduce**

**Expected behavior**
It should bring us to the tool we use all the time.

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.
very high, we use this tool all the time to manage the UAM:Ento collection

**Comment by dustymc** [comment]
glitch in the matrix?
