### ISSUE TITLE
[ geography request ]: Add the Quba-Khachmaz Region in Azerbaijan

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#5655]
# Carefully read the documentation at https://handbook.arctosdb.org/documentation/higher-geography.html before submitting a request.

### Explain what geography needs created.

Request to add the Quba District of Azerbaijan

Location information: https://en.wikipedia.org/wiki/Quba_District_(Azerbaijan)
https://gadm.org/maps/AZE/quba-khachmaz/quba.html
or it may make more sense to create the Quba-Khachmaz Region in Azerbaijan, since Quba is a District within that region
https://gadm.org/maps/AZE/quba-khachmaz.html

Either would be very helpful. I have a record that comes from Quba, Quba, Azerbaijan that I am trying to bulkload.

**Comment by dustymc** [comment]
Please fill source_authority with an appropriate wikipedia link and re-attach the CSV to this Issue.

[temp_geog_create(16).csv.zip](https://github.com/ArctosDB/arctos/files/10744528/temp_geog_create.16.csv.zip)

**Comment by ewommack** [comment]
Here you go. I think I found all of the ones in the file.
[temp_geog_create(16)_15Feb2023.csv](https://github.com/ArctosDB/arctos/files/10746211/temp_geog_create.16._15Feb2023.csv)

**Comment by dustymc** [comment]
done
