### ISSUE TITLE
ChAS: replace logo image for header

### ISSUE THREAD

**Issue by droberts49** [ArctosDB/arctos#5656]
Hi Dusty, I'd like to replace our logo for the header on all the CHAS collections. From other discussions, it looked like PNG files were ok?
![PNNM_logo_FullColor_Horiz_7461C](https://user-images.githubusercontent.com/16580148/218861638-a9c49a83-6f78-4cbb-8005-5ee5614b6c82.png)

Thank you, Dawn

**Comment by mkoo** [comment]
PNG's are fine! 
I will upload to post right now and see how it looks on test! (this looks ready to go)

**Comment by mkoo** [comment]
check out test:
https://arctos-test.tacc.utexas.edu/guid/CHAS:Bird:22

if you like that then change the header link color to White (under manage _collection) and and you can use this image URL:
https://raw.githubusercontent.com/ArctosDB/arctos/master/images/ChAS_logo.png

NIce logo!

**Comment by mkoo** [comment]
ugh, test is being testy. here's a snapshot:

![Firefox_Screenshot_2023-02-15T00-31-13 249Z](https://user-images.githubusercontent.com/2523089/218894491-b70f811b-6c5f-4a56-b762-b90022e332c0.png)

**Comment by mkoo** [comment]
@droberts49 Hi Dawn, making sure you saw the new logo on the TEST site--  let me know if you want guidance on making this live on the production site

>check out test:
https://arctos-test.tacc.utexas.edu/guid/CHAS:Bird:22

>if you like that then change the header link color to White (under manage _collection) and and you can use this image URL in the URL field:
https://raw.githubusercontent.com/ArctosDB/arctos/master/images/ChAS_logo.png

**Comment by mkoo** [comment]
Sorry for letting this slip!
two options:
blue font on white background
https://web.corral.tacc.utexas.edu:9013/guid/CHAS:Mamm:22
![Firefox_Screenshot_2024-12-10T18-10-12 154Z](https://github.com/user-attachments/assets/51bdf374-7f70-4230-9da3-4ab45c1504da)

or

white font on blue background
https://web.corral.tacc.utexas.edu:9013/guid/CHAS:Bird:22
![Firefox_Screenshot_2024-12-10T18-10-38 693Z](https://github.com/user-attachments/assets/4c64b7b0-01fb-418a-b8bc-8ba102ede626)

Let me know which @droberts49 

@dustymc when you can please post the resized logo to prod!
https://www.dropbox.com/scl/fi/39plegjdassdacn6dlqjm/CHAS_logo-header130.png?rlkey=bk8dao3k5atcxcjzzzqe2iyjf&raw=1

**Comment by dustymc** [comment]
Next release:

 create mode 100644 images/header/CHAS_logoheader130.png

**Comment by wellerjes** [comment]
This is no longer needed--we have a new logo and it has been updated on all the relevant pages.

**Comment by wellerjes** [comment]
Please remove from next update and then okay to close.
