### ISSUE TITLE
[ geography request ] Add the Bingöl Province of Turkey

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#5657]
# Carefully read the documentation at https://handbook.arctosdb.org/documentation/higher-geography.html before submitting a request.

### Explain what geography needs created.

Request to add the Bingöl Province of Turkey.

Locality information: https://en.wikipedia.org/wiki/Bing%C3%B6l_Province
https://gadm.org/maps/TUR/bingol.html

I am bulkloading a record with the following locality: Yedisu, Bingöl Province, Turkey.
I could use Turkey, but it would help to have the province to help with discoverability.

**Comment by dustymc** [comment]
Here's CSV:

[temp_geog_create(17).csv.zip](https://github.com/ArctosDB/arctos/files/10744700/temp_geog_create.17.csv.zip)

I could definitely use help in making sure I've transliterated consistently and that there are no duplicates with existing Arctos records and for general mess avoidance.

I will see if I can revise my wikimagicinator to fill some links in - there's apparently going to be a [lot of that](https://github.com/ArctosDB/arctos/issues/5654) in my future, doing it all manually doesn't sound like much fun. I'll be back, hopefully with better data....

**Comment by dustymc** [comment]
Better CSV - [temp_pre_geog.csv.zip](https://github.com/ArctosDB/arctos/files/10746093/temp_pre_geog.csv.zip)

Please confirm nothing's obviously crazy, it should be ready to load

**Comment by ewommack** [comment]
> Please confirm nothing's obviously crazy, it should be ready to load

The province I need is on there, and the data look good. Did you want all of the provinces though? It looks like there are 81 in Turkey (https://en.wikipedia.org/wiki/Provinces_of_Turkey). Your csv has only 60.
