### ISSUE TITLE
Feature Request - check all button for adding to loan

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#5659]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

The previous add items to loan via a cat record search had a way to add all the found items to the loan in one click. Now this seems missing. We have to check a box for each part to add??

Can that feature be added back?

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.
medium until I have another large loan request. I don't want to have to click 200+ check boxes.

**Comment by campmlc** [comment]
Will this have the ability to select in bulk to "subsample yes/no, subsample as (part name), and subsample part disposition ( select from drop-down)" for all items in the search? That would solve our previous problems with the loan item select UI.
