### ISSUE TITLE
Feature Request - Navigating Search Results

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#5660]
**Is your feature request related to a problem? Please describe.**
The new interface does not have the arrows to navigate between catalog records within search results:
![image](https://user-images.githubusercontent.com/93737929/219085583-a845335d-1d3f-4929-838c-ae31762269a6.png)

**Describe what you're trying to accomplish** 
Would it be possible to add the arrows back into the new interface?

**Describe the solution you'd like**
Adding back the arrows; underneath "Get a DOI"?
![image](https://user-images.githubusercontent.com/93737929/219086577-85241c2a-2863-4da6-b209-1f8e24eb5a48.png)

**Describe alternatives you've considered**
Closing the record page and going back to the search results.

**Additional context**
n/a

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by AJLinn** [comment]
I've been missing those arrows also! They're super helpful in progressing through a number of records without having to go back out to the search results.

**Comment by dustymc** [comment]
I don't know how I'd do this, and I think that actually wasn't doing what anyone - or anyone who's into certain flavors of multitasking - would have expected for the last couple years or so. That control was a legacy of a design that made sense before browser tabs were a thing.

This isn't technically implausible, it just doesn't work very well with the flow of the UI, so I'm leaving this up for discussion.

> progressing through a number of records without having to go back out to the search results.

Embrace the tabs!

**Comment by AJLinn** [comment]
> Embrace the tabs!

It's about reducing the clicks! ;-)

**Comment by wellerjes** [comment]
I'd also like to add, the arrows were especially helpful in searches where you've already clicked on all the links and they've turned purple. It's useful for when data is in the search results looks very similar (catalog numbers are one off, same collector/locality, etc.). I really do think the arrows add to ease of use.
![image](https://user-images.githubusercontent.com/93737929/219413794-3bc07c4d-0a71-4c43-b92e-5e88826ed184.png)

**Comment by dustymc** [comment]
Tabling, I still do not have a mechanism for this in the current UI.
