### ISSUE TITLE
Password Reset Help

### ISSUE THREAD

**Issue by bryansmclean** [ArctosDB/arctos#5662]
My password expired and now the Reset Password functionality is not working for me (have tried requesting reset email several times to no avail). Seems like this has happened to others prior. Help please!

**Comment by Jegelewicz** [comment]
@bryansmclean I just sent you an email (to gmail) - let me know if that doesn't work.

**Comment by bryansmclean** [comment]
Got the email, but the combo is not working for me...

"Authentication failed. Additional Information: Access restricted."

**Comment by bryansmclean** [comment]
Worked this time, thanks @Jegelewicz
