### ISSUE TITLE
search form UI

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#5667]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

Part attribute fields spilling over the blue box - see screenshot

Looks weird
![Screen Shot 2023-02-15 at 5 18 24 PM Feb 15, 23](https://user-images.githubusercontent.com/9099827/219251569-4295b175-527c-4210-b917-41a4f748b36e.jpg)

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.
medium

**Comment by Jegelewicz** [comment]
This is already discussed in #5613
