### ISSUE TITLE
[CONTACT: Blocked Network]

### ISSUE THREAD

**Issue by lito-89** [ArctosDB/arctos#5668]
restricted IP: 146.70.33.61

Good morning,
My name is Manuel Amadori and I am a researcher at the University of Vienna and need to check the online catalogue of the Natural History Museum in Alabama via Arctos.
A few days ago everything was working. Unfortunately, I am no longer allowed access and I don't know why.
The following message appears on the Arctos platform:
_<<Your IP (146.70.33.61) or organization has been blocked. You may wish to check your computer for malicious software and alert your IP or organization. Further intrusion attempts may result in more restrictive blocks. Access from this network has been restricted. You may open an Issue on our GitHub to request access. We cannot consider requests which do not include your IP address, "146.70.33.61">>_
I would be grateful if you could help me.

Best regards,

Manuel

**Comment by dustymc** [comment]
released
