### ISSUE TITLE
David Easterla

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5672]
https://arctos.database.museum/agent/21347315 was just force-created and looks to be a duplicate of https://arctos.database.museum/agent/21306668

@gradyjt

**Comment by gradyjt** [comment]
Hey Dusty, I'm working on cleaning up agents and I wanted to correct this name and separate it from the non-apsu institutions, but I failed to clean up the bad duplicate. I'll do that now.

**Comment by gradyjt** [comment]
Should be marked appropriately now.

**Comment by dustymc** [comment]
Thanks!
