### ISSUE TITLE
Code Table Request - Add Colors to Observation Collection Attributes

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#5680]
(https://arctos.database.museum/Admin/CodeTableEditor.cfm?action=editctattribute_type&tbl=ctattribute_type)

I have photo observations showing various albino, melanistic and leucistic taxa. Currently the "Colors" attribute is not available in the drop-down menu for Obs collection types. Can we add it please? It is available for multiple other Collection types.

**Comment by Jegelewicz** [comment]
I say go for it.

**Comment by ebraker** [comment]
@Jegelewicz Collection type = Obs isn't on the drop-down. I added Host to see if Obs uses the same template (some of the code table values are shared) but it didn't add Colors as an option so I removed it. Any ideas?

![image](https://user-images.githubusercontent.com/11336485/220472086-e46c907f-6645-428c-95e8-e30d2742cdbe.png)

**Comment by Jegelewicz** [comment]
There is no such collection type - https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcollection_cde What code is that collection using?

**Comment by ebraker** [comment]
UCM:Obs

**Comment by Jegelewicz** [comment]
I'm guessing that is a Teach collection - you can see in manage Collection.

![image](https://user-images.githubusercontent.com/5725767/220473766-9962a9ef-8d05-4d5c-b42b-209be1190f41.png)

**Comment by ebraker** [comment]
Yes but Teach already has Colors added.

That's why I thought it may be Host since it has a lot of the standard bird/mamm options -  I looked at things like "culmen length" and "ear from notch" and Host shares those but had NOT been added to Colors. But no dice.

**Comment by dustymc** [comment]
https://arctos.database.museum/collection/UCM:Obs

Host

**Comment by ebraker** [comment]
Ok, I tried that but maybe there was a delay and I wasn't patient enough...

**Comment by Jegelewicz** [comment]
@ebraker once you add it - it may take a while before you can actually use it..

**Comment by Jegelewicz** [comment]
Sometimes 15 minutes, sometimes a few hours - not sure what the difference is!

**Comment by ebraker** [comment]
Gotcha. Ok that's probably it since I tried refreshing and logging out. Thanks!

**Comment by ebraker** [comment]
Worked!
