### ISSUE TITLE
Identifiers and Relationships: Check Container --> Remove space

### ISSUE THREAD

**Issue by KyndallH** [ArctosDB/arctos#5683]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Space between end of # and % needs to be removed in the check container feature.

**To Reproduce**
1. Click "Check Container" under Identifiers and Relationships in a record
2. Returns No results
3. Delete space between # and %. Returns results (if there are any)

**Expected behavior**
Delete space so I don't have to every time.

**Screenshots**
<img width="968" alt="Screen Shot 2023-02-20 at 2 18 12 PM" src="https://user-images.githubusercontent.com/16887896/220212912-1fa144a8-aee0-4b23-b2b4-fd149d7a9550.png">

<img width="924" alt="Screen Shot 2023-02-20 at 2 17 48 PM" src="https://user-images.githubusercontent.com/16887896/220212906-bcc64ecc-a723-4d86-9954-c272faaba461.png">

<img width="837" alt="Screen Shot 2023-02-20 at 2 17 59 PM" src="https://user-images.githubusercontent.com/16887896/220212909-66259811-b1d7-428b-b919-ed4dc9bd1893.png">

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by campmlc** [comment]
Yes please!

**Comment by dustymc** [comment]
That was purposefully added as a filter on MSB data but if @campmlc doesn't need it anymore it's easy enough to change.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/4163#issuecomment-985939745
