### ISSUE TITLE
Need Help with Arctos Error: Specimen Event Bulkloader tool not bulkloading spatial data

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#5684]
# Error Text
load fail::ERROR: Error and units, datum, and georeference source and protocol must be accompanied by spatial data. Where: PL/pgSQL function trigger_fct_trg_locality_biu() line 119 at RAISE 

# Where it happened
Specimen event bulkload 
[CleanElPasoBirds_Accepted.csv](https://github.com/ArctosDB/arctos/files/10791216/CleanElPasoBirds_Accepted.csv)
tool

# Steps to get there
Upload file, set status to review, receive error

# Problem
Specimen event not loading data despite all accompanying spatial data is available
[CleanElPasoBirds_Accepted.csv](https://github.com/ArctosDB/arctos/files/10791199/CleanElPasoBirds_Accepted.csv)

I'm sort of at a loss. All the dec lats and dec longs are attached and all the georeference sources, datum, error max distance, error untis, protocols, higher geog etc. are available too. Is there something I'm missing?? 

Data is attached. 

# Solution
[CleanElPasoBirds_Accepted.zip](https://github.com/ArctosDB/arctos/files/10791219/CleanElPasoBirds_Accepted.zip)

**Community response with directions for how to correct the problem**

**Comment by dustymc** [comment]
Loader apparently hasn't been revised for primary_spatial_data - neds rebuilt and modernized, going next task, please help prioritize.

**Comment by Jegelewicz** [comment]
@dustymc I think would need immediate attention as a tool that a lot of people might be using?

**Comment by mvzhuang** [comment]
i figured out a workaround by pre-creating localities, but it is kind of annoying, not intending to do so.
