### ISSUE TITLE
Help adding UWYMV logo to record detail pages

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#5687]
@mkoo - the UWYMV is ready to try again to add our logo to our record detail pages.

I tried this a bit ago, couldn't get it to look like what we needed following the directions, and had to move on to other things. I've spoken to our faculty curator, and he said that if there is help we can try again if we can keep it simple and does not take up too much time.

We'd like to keep the banner color white and the text color the default, but could I get your help to add our logo please? I've attached copies of the version we would like to add as a jpg and as a png file.

[UWYMV_colorlogo.zip](https://github.com/ArctosDB/arctos/files/10796682/UWYMV_colorlogo.zip)

**Comment by dustymc** [comment]
done??

**Comment by mkoo** [comment]
not done-- I will look into this after 10 today @ewommack!

**Comment by mkoo** [comment]
@ewommack  Which style do you like?
https://arctos-test.tacc.utexas.edu/guid/UWYMV:Herp:1001
 - logo no letters, 
 - collection is "Herpetology" (not "Herps" or Herp Collection)
 
https://arctos-test.tacc.utexas.edu/guid/UWYMV:Bird:1001
- logo you sent me with letters
- collection is Bird Collection not Ornithology
- is there a webpage just for birds? I couldnt find it... so we can remove the link to the general museum page.

All in test so you can log in and see for yourself! Lettering is black for both but we could also match the brown in the logo if that sounds good

**Comment by ewommack** [comment]
@mkoo - thank you!
I'll add the options to our staff meeting agenda for next week, and get back to you right after.
At the moment I am guessing logo with letters, black and white is fine.

No we don't have individual collections pages for each collection. They're all managed by one faculty and staff, so we love them all equally. You could try our collections page: https://uwymv.wyomingbiodiversity.org/index.php/collections. It has links to our use policy and our loan policy.

**Comment by ewommack** [comment]
@mkoo @dustymc - I learned a valuable lesson this week that when I want to show something to my curator to send screenpics and not links.

The test links show a broken image file. Help?

**Comment by ewommack** [comment]
Thanks @mkoo! I've snagged the screencaps to share with our faculty curator.

> [https://arctos-test.tacc.utexas.edu/guid/UWYMV🐦1001](https://arctos-test.tacc.utexas.edu/guid/UWYMV:bird:1001)

Am I right in that there is an emoji of a bird in this address?

**Comment by mkoo** [comment]
hah-- that's because of ```bird:``` somehow GH interprets as an emoji!

we could do something with a color banner or color lettering too but let me know what you think of this for now

**Comment by dustymc** [comment]
>there is an emoji of a bird in this 

New Arctos policy: All bird collections shall have at least one bird emoji in their GUID...

>bird: somehow GH interprets as an emoji!

Everything Microsoft [touches](https://www.nature.com/articles/d41586-021-02211-4)....

**Comment by mkoo** [comment]
let GUM now deal with emojis in our occurrenceID's (Arctos leads the way!)

**Comment by ewommack** [comment]
Hi @mkoo - we went over the logo options you gave. A big thank you for the help.

Consensus is the log without letters please:

> logo without letters:
[https://arctos-test.tacc.utexas.edu/guid/UWYMV🐦1001](https://arctos-test.tacc.utexas.edu/guid/UWYMV:bird:1001)

and just regular black and white lettering. We're going pretty simple for now.

**Comment by ewommack** [comment]
@mkoo - just checking on this issue?

**Comment by ewommack** [comment]
@mkoo - just checking on the issue?

**Comment by ewommack** [comment]
Teresa helped me finish it during Arctos Happy Hour!
