### ISSUE TITLE
Feature Request - Loan Instructions templates

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#5691]
It would be a great efficiency if operators could save  loan instruction text somewhere and be able to select it when creating loans.

I have standard text that I copy and paste into each loan (varies by wet vs dry specimen types,  CT media, destructive sampling, etc). Currently, every time I create a loan I do a concurrent Loan Search to copy and paste instructions from previous loans. If we could save text somewhere and create nick names, e.g.," "UCM destructive" "UCM ethanol" etc. and use a pick list (or something similar), it would save a lot of time.

Separate but another efficiency: it would be great if we could use a default operator's address for 'Shipped From Address' rather than looking up our agent name each and every loan (still could be editable as needed).

**Comment by Jegelewicz** [comment]
See also https://github.com/ArctosDB/arctos/issues/5094

**Comment by Jegelewicz** [comment]
>  loan instruction text

I see this sitting in Manage Collection - other ideas?

**Comment by dustymc** [comment]
>sitting in Manage Collection

So - collection attributes? (But maybe simplified - type and value seem all that could be necessary here??)

That would also cover https://github.com/ArctosDB/arctos/issues/4740 (random thing that someone apparently wanted for some reason at some point) and would allow us to remove eg Geographic Description (random thing that some external collaborator - GBIF in this case - wants for some reason, not something many/most collections should be forced to scroll past).


```

arctosprod@arctos>> \d collection
                                                                       Table "core.collection"
            Column            |          Type           | Collation | Nullable |                                       Default                                        
------------------------------+-------------------------+-----------+----------+--------------------------------------------------------------------------------------
 collection_cde               | character varying(5)    |           | not null | 
 institution_acronym          | character varying(20)   |           |          | 
 descr                        | character varying(4000) |           |          | 
 collection                   | character varying(50)   |           | not null | 
 collection_id                | integer                 |           | not null | 
 web_link                     | character varying(4000) |           |          | 
 web_link_text                | character varying(50)   |           |          | 
 genbank_prid                 | integer                 |           |          | 
 genbank_username             | character varying(20)   |           |          | 
 genbank_pwd                  | character varying(20)   |           |          | 
 loan_policy_url              | character varying(255)  |           | not null | 
 institution                  | character varying(255)  |           |          | 
 guid_prefix                  | character varying(20)   |           | not null | 
 use_license_id               | integer                 |           |          | 
 citation                     | character varying(255)  |           |          | 
 catalog_number_format        | character varying(21)   |           | not null | 
 geographic_description       | character varying(4000) |           |          | 
 west_bounding_coordinate     | integer                 |           |          | 
 east_bounding_coordinate     | integer                 |           |          | 
 north_bounding_coordinate    | integer                 |           |          | 
 south_bounding_coordinate    | integer                 |           |          | 
 general_taxonomic_coverage   | character varying(4000) |           |          | 
 taxon_name_rank              | character varying(4000) |           |          | 
 taxon_name_value             | character varying(4000) |           |          | 
 purpose_of_collection        | character varying(4000) |           |          | 
 alternate_identifier_1       | character varying(4000) |           |          | 
 alternate_identifier_2       | character varying(4000) |           |          | 
 specimen_preservation_method | character varying(4000) |           |          | 
 time_coverage                | character varying(4000) |           |          | 
 genbank_collection           | character varying       |           |          | 
 internal_license_id          | integer                 |           |          | 
 external_license_id          | integer                 |           |          | 
 collection_terms_id          | integer                 |           | not null | 
 default_cat_item_type        | character varying       |           | not null | 
 preferred_identifiers        | character varying[]     |           |          | 
 collection_role              | character varying       |           |          | generated always as (lower(replace(guid_prefix::text, ':'::text, '_'::text))) stored
```

**Comment by Jegelewicz** [comment]
> collection attributes?

This could offer a solution for https://github.com/ArctosDB/arctos/issues/5291 (attribute type = identifier) and https://github.com/ArctosDB/arctos/issues/4740 (determined date...) but I also think that we might as well make these things like every other attribute in Arctos and include date, determiner, method and remark. It may seem like they will never get used, but I could see this:

coll_att_type | coll_att_value | coll_att_units | coll_att_determiner | coll_att_det_date | coll_att_method | coll_att_remark
 -- | -- | -- | -- | -- | -- | --  
identifier | https://arctos.database.museum/collection/MVZ:Bird | | [Arctos Consortium](https://arctos.database.museum/agent/21334341) | 2010-01-01 |  | collection created in Arctos 
identifier | https://www.ncbi.nlm.nih.gov/biocollections/107170 | | [NCBI](https://arctos.database.museum/agent/21347867) | | |

**Comment by dustymc** [comment]
>5291

Yea, but I'm sorta digging the GUM approach (collections are agents, and agents can already carry those things). In any case, however I feel about it, this would indeed provide ~~a place to hide~~ an alternate place for those data.


>might as well

Maybe, but I can't imagine a situation where an ambiguous identifier ("3") would do anything for anyone, even if it was assigned for some reason, and neither Arctos Consortium nor NCBI has or will ever have access to edit a collection.
