### ISSUE TITLE
FYI: Page Help

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5694]
For pages with pagehelp, there's a menu item.

<img width="1013" alt="Screenshot 2023-02-22 at 7 24 25 AM" src="https://user-images.githubusercontent.com/5720791/220668827-0aa9b44e-dfd2-4574-9394-4363f39f3b09.png">

Those with sufficient access can control this from Manage Arctos Directory. (There is a cache, it will take ~an hour for changes to become visible to everyone.) 

Those without access can file an Issue - just include links to the Arctos page and the appropriate help file.

I moved everything I could from the old stopgap system, here are those data (which I'll now delete).

```
create table temp_old_ph as select * from redirect where old_path ilike '%handbook%';
```

[temp_old_ph.csv.zip](https://github.com/ArctosDB/arctos/files/10805529/temp_old_ph.csv.zip)

This can be closed in ~a month.

**Comment by Jegelewicz** [comment]
@dustymc Thanks! @ebraker we can see what pages have nothing (maybe there is something, but it just hasn't been added) and this could help guide handbook/tutorial needs.

**Comment by mkoo** [comment]
I really like this. Might be a way to reorganize Handbook pages focused on specific tool and edit pages.

Has anyone run through this to see which help pages are missing? Maybe a task for any Switzer activities?!

**Comment by Jegelewicz** [comment]
I started working on this here - https://docs.google.com/spreadsheets/d/1Ia5cdkHy_v0bozrU9dwBExOYsFpkp8pPwykKZZxNpRg/edit#gid=1070095246

But it's a chore and stuff is REALLY scattered right now.
