### ISSUE TITLE
Code Table Request - Subject Matter terms updates

### ISSUE THREAD

**Issue by krgomez** [ArctosDB/arctos#5695]
**Goal**
I would like to update one term in the subject matter code table, as well as add one new term.

**Table**
[ctsubject_term](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctsubject_term)

**Proposed Value**
Term to update: indigenous decolonization --> Indigenous decolonization (should be capitalized)
Term to add: drums

**Proposed Definition**
Definition: Membranophones with a resonating cavity covered at one or both ends by a membrane, which is sounded by striking, rubbing, or plucking.
Getty AAT URL: http://vocab.getty.edu/page/aat/300041729

**Comment by Jegelewicz** [comment]
@ArctosDB/arctos-code-table-administrators this seems like an easy yes on the drums, the capitalization probably needs a nod form @dustymc

**Comment by ebraker** [comment]
Approved 2023-06-15 code table meeting, added to code table: Indigenous Decolonization (@dustymc to resolve lowercase version) and 'drums.'

**Comment by dustymc** [comment]
cleaned
