### ISSUE TITLE
Arctos access restricted

### ISSUE THREAD

**Issue by adhornsby** [ArctosDB/arctos#5697]
I'm trying to log into Arctos but am getting the error:

Authentification failed. Additional information: Access restricted.

I'm guessing my account got locked somehow?  Same error coming from login attempts on Mac-Chrome, Mac-Safari, and PC-Chrome.  Thanks in advance!

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I've had the same issue a few times (#5199). I've noticed that if I look up my operator details, this:
![image](https://user-images.githubusercontent.com/47402809/220755930-de6b9b5e-b6af-411f-b2ab-bf352ab29be7.png)
increases each time I mess up my password and doesn't reset after a successful login. @dustymc is that how its supposed to be and could it be related to the lock out issue?

**Comment by dustymc** [comment]
reset

Yes that's the item of interest but it should reset with success.

**Comment by adhornsby** [comment]
Thanks @dustymc !
