### ISSUE TITLE
[external CONTACT] duplicate MVZ:Egg number?

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#5700]
@dustymc I'm trying to catalog a new MVZ:Egg record using the catnum =15007 which is the next available number per my record. When I try to save the record, it says that 15007 is a duplicate number (accession is MVZ:Egg 15739). However, when I search for MVZ:Egg:15007 it doesn't find any records ("No data available in table").

????

**Comment by dustymc** [comment]
>try to save the record

From where? I need a screenshot or URL or something.

**Comment by ccicero** [comment]
From the data entry screen:

![image](https://user-images.githubusercontent.com/967275/220799553-387a60d0-7f0a-410b-a3a5-9649b7b52d83.png)

**Comment by dustymc** [comment]
<img width="228" alt="Screenshot 2023-02-22 at 5 09 58 PM" src="https://user-images.githubusercontent.com/5720791/220799928-402fbd3a-1260-48cc-bff1-dac839fb0983.png">

https://arctos.database.museum/guid/MVZ:Bird:15007

**Comment by ccicero** [comment]
Ah, I know. I'm using the form I set up for birds, I guess that automatically fills in the MVZ:Bird GUID so I need to set up a new template for MVZ:Egg. Duh. thanks.
