### ISSUE TITLE
cannot add agent - 400 Bad Request

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#5705]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Trying to add a new agent, Erin Voss. She is a new collector and preparator, and will also be the source for an accession.

**To Reproduce**
I filled in preferred name, first and last. Added email. Added student of Michael Nachman. No luck. 400 bad request. 

**Expected behavior**
Create a new agent.

**Additional context**
When getting that error, would be great if it said what the issue was and allowed one to go back and rectify. I have to close the whole box and start over. 

**Priority**
High. Cannot do my job if I cannot create agents.

**Comment by mkoo** [comment]
looks like you were successful!
https://arctos.database.museum/agents.cfm?agent_id=21347409

 I will close so just file a new one if there's something else (400 errors are typically client side )

**Comment by cjconroy** [comment]
I don't know what I did differently, but then it worked.
