### ISSUE TITLE
Feature Request - loan transactions: placement of "update all [dispositions] to..."

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#5706]
The new loan interface is great, but the option to batch update all dispositions when adding items to a loan transaction is somewhat buried amidst a bunch of text. 

![image](https://user-images.githubusercontent.com/967275/221010808-7f647711-d66f-4400-9607-695c93b8acf1.png)

It would be much more obvious if we could move that to right above the grid where you select the parts, to the right of "Add all checked parts to transaction"

My suggestions is to add to the right of that: "Update disposition for all to..." [dropdown]

@dustymc is that feasible?

**Comment by ebraker** [comment]
something like this?
![image](https://user-images.githubusercontent.com/11336485/221012338-8174188a-1108-4ff2-af19-1b78a9d0adc6.png)

**Comment by campmlc** [comment]
Yes, that would be great. That is similar what we had with the previous interface. Even better, "Update all loan parts of type (dropdown)"  to "select disposition".
