### ISSUE TITLE
Unable to access gn_merge file

### ISSUE THREAD

**Issue by dimus** [ArctosDB/arctos#5709]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

Hi @dustymc, it is time to update Arctos at verifier.globalnames.org, and I am having trouble to get to the file you generated.

This issue is related to: 

https://github.com/ArctosDB/arctos/issues/4298

I am trying to harvest arctos data and looks like I am not able to get to `http://arctos.database.museum/cache/gn_merge.tgz.zip` file anymore. HTTP generates 426 error, and probably wants me to get to HTTPS, and when I try to go to HTTPS I am getting "Access denied".

**Comment by dustymc** [comment]
Bah @dimus I need to spend some more time on this but for now ``https://arctos.database.museum/cache/gn_merge.tgz`` should work - let me know if you have any problems with that, and I'll try to actually get this put back together before you need it again....

future-me: zip isn't installed in the VM? Do we still need it??

**Comment by dustymc** [comment]
This should be happy in next release.

I confused myself in https://github.com/ArctosDB/arctos/issues/4298 (thanks for the link), zip was a one-time thing to deal with a webserver setup that's since been corrected. Arctos is now happy to serve up .tgz (and that's what's actually being created).

I also added the path to the API page for next release.

**Comment by dimus** [comment]
thank you @dustymc, the URL you provided did work well, making import from it as we speak

**Comment by dimus** [comment]
Hi @dustymc, I am having trouble again to download the file for gn, this was the last URL that did work for me before:

https://arctos.database.museum/cache/gn_merge.tgz

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/7346 - should be back shortly

**Comment by dimus** [comment]
@dustymc, @Jegelewicz, thanks, all worked perfectly
