### ISSUE TITLE
rebuild agent merge scripts

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5711]
**Is your feature request related to a problem? Please describe.**

They've been consistently failing to complete, which means things don't get processed.

**Describe what you're trying to accomplish** 

Make scripts more robust.

**Describe the solution you'd like**

More smaller bites.

**Describe alternatives you've considered**

Wait, but the backlog may be growing faster than its being resolved.

**Additional context**

 Seems related to https://github.com/ArctosDB/internal/issues/187

**Priority**

High-ish; not critical at the moment but see above, may be moving in that direction

**Comment by Jegelewicz** [comment]
I would like to request that while you are doing this, we include redirects for the merged agent (stablize agent IDs?). When an agent is merged into another, we don't ever re-use that identifier (https://arctos.database.museum/agents.cfm?agent_id=21300608) but instead point it at the new agent. Possible? Already happens?

**Comment by dustymc** [comment]
>stablize agent IDs

Issue - that's not something I can tack on to a bugfix!

>don't ever re-use that identifier

We don't.

> point it at the new agent.

It's (much) more complicated than that.

**Comment by Jegelewicz** [comment]
>     stablize agent IDs
> 
> Issue - that's not something I can tack on to a bugfix!

Can you explain what is a "stable" identifier? I am clearly not understanding that!

**Comment by Jegelewicz** [comment]
>     point it at the new agent.
> 
> It's (much) more complicated than that.

Can you explain this too? I think we need to understand exactly what does happen.
