### ISSUE TITLE
can't add to loan

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#5712]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

scanned the barcode of UAM100064253

tried to add to this loan https://arctos.database.museum/Loan.cfm?action=editLoan&transaction_id=21136060

got this error

An error has occurred!
May we suggest:

    On search pages, make sure you do not have values in fields that you do not mean to be there. Or try filling in fewer fields, the more likely to get a match.
    You may not have sufficient privileges to perform that operation. Consult with your supervisor or Arctos mentor.

Please contact us if you need assistance in resolving this error. Include the ERROR_ID (below) as text and enough information for us to re-create the problem.
ERROR_ID 	415F41B7-69D4-4464-91D203E1B52FB79A
ERROR_TYPE 	SQL
ERROR_MESSAGE 	ERROR: insert or update on table "coll_object" violates foreign key constraint "fk_collobject_ctcollobjdisp" Detail: Key (coll_obj_disposition)=() is not present in table "ctcoll_obj_disp".
ERROR_DETAIL 	
ERROR_SQL 	UPDATE coll_object SET coll_obj_disposition = '' where collection_object_id =26923866

request dump:
request
node_name	
string	arctos-2021
rdurl	
string	/info/loan_item_pick.cfm
uuid	
string	415F41B7-69D4-4464-91D203E1B52FB79A

exception dump:
Catch
Entries: 15
additional	
Struct (ordered)
SQL	
string	UPDATE coll_object SET coll_obj_disposition = '' where collection_object_id =26923866
DatabaseName	
string	PostgreSQL
DatabaseVersion	
string	12.2
DriverName	
string	PostgreSQL JDBC Driver
DriverVersion	
string	42.2.20
Datasource	
string	user_login
DataSource	
string	user_login
Detail	
string	
ErrorCode	
string	0
Extended_Info	
string	
ExtendedInfo	
string	
Message	
string	ERROR: insert or update on table "coll_object" violates foreign key constraint "fk_collobject_ctcollobjdisp" Detail: Key (coll_obj_disposition)=() is not present in table "ctcoll_obj_disp".
NativeErrorCode	
number	0
queryError	
string	UPDATE coll_object SET coll_obj_disposition = '' where collection_object_id =26923866
Sql	
string	UPDATE coll_object SET coll_obj_disposition = '' where collection_object_id =26923866
SQLState	
string	23503
StackTrace	
string	lucee.runtime.exp.DatabaseException: ERROR: insert or update on table "coll_object" violates foreign key constraint "fk_collobject_ctcollobjdisp" Detail: Key (coll_obj_disposition)=() is not present in table "ctcoll_obj_disp". at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553) at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285) at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323) at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481) at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401) at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164) at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:153) at lucee.runtime.type.util.QueryUtil.execute(QueryUtil.java:328) at lucee.runtime.type.QueryImpl.execute(QueryImpl.java:296) at lucee.runtime.type.QueryImpl.<init>(QueryImpl.java:235) at lucee.runtime.tag.Query.executeDatasoure(Query.java:1134) at lucee.runtime.tag.Query._doEndTag(Query.java:699) at lucee.runtime.tag.Query.doEndTag(Query.java:565) at info.loan_item_pick_cfm$cf.call(/info/loan_item_pick.cfm:826) at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:1015) at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:938) at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:219) at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:44) at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2482) at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2468) at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2439) at lucee.runtime.engine.Request.exe(Request.java:45) at lucee.runtime.engine.CFMLEngineImpl._service(CFMLEngineImpl.java:1198) at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:1144) at lucee.loader.engine.CFMLEngineWrapper.serviceCFML(CFMLEngineWrapper.java:97) at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:51) at javax.servlet.http.HttpServlet.service(HttpServlet.java:590) at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74) at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129) at org.cfmlprojects.regexpathinfofilter.RegexPathInfoFilter.doFilter(RegexPathInfoFilter.java:47) at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68) at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68) at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117) at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at runwar.Server$1.handleRequest(Server.java:510) at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52) at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:280) at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79) at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134) at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131) at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:260) at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79) at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100) at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387) at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852) at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35) at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019) at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558) at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449) at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280) at java.base/java.lang.Thread.run(Thread.java:829)
TagContext	
Array
1	
Struct
codePrintHTML	
string	824: UPDATE coll_object SET coll_obj_disposition = &lt;cfqueryparam value=&quot;#thisDisp#&quot; CFSQLType=&quot;cf_sql_varchar&quot;&gt;<br> 825: where collection_object_id =&lt;cfqueryparam value=&quot;#thePartID#&quot; CFSQLType=&quot;cf_sql_int&quot;&gt;<br> <b>826: &lt;/cfquery&gt;</b><br> 827: &lt;/cfloop&gt;<br> 828: &lt;/cftransaction&gt;<br>
codePrintPlain	
string	824: UPDATE coll_object SET coll_obj_disposition = <cfqueryparam value="#thisDisp#" CFSQLType="cf_sql_varchar"> 825: where collection_object_id =<cfqueryparam value="#thePartID#" CFSQLType="cf_sql_int"> 826: </cfquery> 827: </cfloop> 828: </cftransaction>
column	
number	0
id	
string	??
line	
number	826
Raw_Trace	
string	info.loan_item_pick_cfm$cf.call(/info/loan_item_pick.cfm:826)
template	
string	/usr/local/webroot/info/loan_item_pick.cfm
type	
string	cfml
type	
string	database
where	
string	

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.
High - need to send out loan!!

**Comment by DerekSikes** [comment]
I noticed that this vial was still marked as disposition = on loan from a former loan it had been in. So changed it to 'in collection' then tried again & got the same error

**Comment by DerekSikes** [comment]
btw this was using '[ add items ]' to add to loan.

I tried using [ add items by part container barcode ] which I had never used before, and that worked.

**Comment by dustymc** [comment]
<img width="185" alt="Screenshot 2023-02-24 at 11 51 32 AM" src="https://user-images.githubusercontent.com/5720791/221277425-466ab1f4-4c14-4c6b-8fb2-6ac9513be602.png">

Going next task to see if I can generate a better pre-submit error.
