### ISSUE TITLE
Request: links to catalog records should go to guid page (not collection_object)

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#5713]
Here's the situation but I think this may not be limited to media details:

On a media details page ( ex. https://arctos.database.museum/media/10213280)
![Firefox_Screenshot_2023-02-24T20-28-29 965Z](https://user-images.githubusercontent.com/2523089/221285103-40254ba8-e947-4101-a481-e1c76449ca9f.png)
The hyperlink of  **shows cataloged_item** is: 
```https://arctos.database.museum/search.cfm?collection_object_id=10602126```
Which takes the user to the search page and NOT the cataloged_item
Please change these links to ```https://arctos.database.museum/guid/MVZ:Egg:1222```
Which, to me, is the intuitive and expected behaviour.

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/3331 blocks this; it will provide a mechanism to do this when the relationship is more complicated than 1:1. It could use prioritized.

Going next task - I know how to do this.

**Comment by mkoo** [comment]
yea I figured it was something to do with somethin! cool to have it done-thx
