### ISSUE TITLE
other ID cleanup

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5715]
I don't know how possible this is without https://github.com/ArctosDB/arctos/discussions/5707, but some of the requests in https://github.com/ArctosDB/arctos/issues/5460 don't make much sense to me, it would be very, very good to make sure we're all on the same page before I dedicate a week of CPU to elevating an identifier that primarily serves to confuse people.

[preparator number](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type#preparator_number) is I'm sorta-sure completely interchangeable with collector number, at least in some collections. Are we doing anything unambiguous here (if so the definitions need clarified) or could those be merged?

[institutional catalog number](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type#institutional_catalog_number) looks to me like a full duplicate of [other identifier](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type#other_identifier) - "only if you don't know what institution or collection might have assigned the number" is just "various values that are not known to be of a more defined identifier type" with more words...

@campmlc claims to need [field number](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type#field_number), which might actually be a defensible value but isn't something that can make any sense in the context of mammals or tissues. I checked (data below), it's used - almost certainly contrary to the definition - by 56 collections. I doubt a whole bunch of users are refusing to follow documentation for only one type of identifier, which makes me suspect that we really need to do something way beyond simple cleanup. I'm relatively sure that we are simultaneously maintaining hundreds of distinct types, and then using them arbitrarily; we are putting a lot of work into creating low-quality and misleading data. ????????????????

These are the ALMNH IDs I noticed from the Discussion

```

arctosprod@arctos>> select other_id_type, description,base_url from ctcoll_other_id_type where other_id_type ilike '%ALMNH%' order by other_id_type;
            other_id_type            |                                      description                                       |                    base_url                     
-------------------------------------+----------------------------------------------------------------------------------------+-------------------------------------------------
 ALMNH:Anc                           | Alabama Museum of Natural History Teaching specimens catalog number                    | http://arctos.database.museum/guid/ALMNH:Anc:
 ALMNH:Arc                           | ALMNH Archaeology catalog number                                                       | http://arctos.database.museum/guid/ALMNH:Arc:
 ALMNH:Bird                          | ALMNH Bird specimens catalog number                                                    | http://arctos.database.museum/guid/ALMNH:Bird:
 ALMNH:EH                            | ALMNH History and Ethnology catalog number                                             | http://arctos.database.museum/guid/ALMNH:EH:
 ALMNH:Ento                          | ALMNH Insect specimens catalog number                                                  | http://arctos.database.museum/guid/ALMNH:Ento:
 ALMNH:ES                            | ALMNH Paleontology catalog number                                                      | http://arctos.database.museum/guid/ALMNH:ES:
 ALMNH Ethnology Collection          | Alabama Museum of Natural History Ethnology Collection                                 | 
 ALMNH:Geo                           | Alabama Museum of Natural History Geology specimens catalog number                     | http://arctos.database.museum/guid/ALMNH:Geo:
 ALMNH Geology Collection            | Alabama Museum of Natural History Geology Collection                                   | 
 ALMNH:Herp                          | ALMNH Amphibian and reptile specimens catalog number                                   | http://arctos.database.museum/guid/ALMNH:Herp:
 ALMNH History Collection            | Alabama Museum of Natural History Historical Object Collection                         | 
 ALMNH:Inv                           | ALMNH Invertebrate Zoology catalog number                                              | http://arctos.database.museum/guid/ALMNH:Inv:
 ALMNH:Mamm                          | ALMNH Mammal specimens catalog number                                                  | http://arctos.database.museum/guid/ALMNH:Mamm:
 ALMNH: Museum Expedition            | Identifier associated with an Alabama Museum of Natural History collecting expedition. | 
 ALMNH: Museum Staff Trip            | Identifier associated with an Alabama Museum of Natural History staff trip.            | 
 ALMNH:Paleo                         | Alabama Museum of Natural History Paleontology specimens catalog number                | http://arctos.database.museum/guid/ALMNH:Paleo:
 ALMNH PaleoBotany Collection        | Alabama Museum of Natural History PaleoBotany Collection                               | 
 ALMNH PaleoInvertebrate Collection  | Alabama Museum of Natural History PaleoInvertebrate Collection                         | 
 ALMNH PaleoVertebrate Collection    | Alabama Museum of Natural History PaleoVertebrate Collection                           | 
 ALMNH Vertebrate Zoology Collection | Alabama Museum of Natural History Vertebrate Zoology Collection                        | 
(20 rows)
```

 @aklompma
 @Jegelewicz
 @brandon-s-thompson
 @kmkocot

help?! I think that's two very lost projects and a bunch of duplicates? Let me know if I can merge some or help shuffle data or whatever.

 'field number' usage:

```
 guid_prefix  | count 
--------------+-------
 ALMNH:Inv    |     3
 ALMNH:Paleo  |   181
 APSU:Herp    | 11338
 ASNHC:Mamm   |     1
 ASUMZ:Invert | 29017
 BYU:Herp     |  6136
 BYU:Mamm     |   726
 BYUObs:Herp  |    23
 CHAS:Herb    |     2
 CHAS:Mamm    |     1
 CHAS:Teach   |     1
 CRCM:Fish    |     6
 CSULB:Bird   |  2948
 CSULB:Mamm   | 11639
 DMNS:Bird    |    11
 DMNS:Mamm    |  1490
 DMNS:Para    |   342
 HWML:Para    | 35416
 JFBM:Fish    | 25885
 JSNM:Egg     |     1
 KNWR:Ento    |    67
 KNWR:Herb    |    82
 KNWR:Inv     |    70
 KNWRObs:Fish |     1
 MLZ:Bird     |     1
 MLZ:Mamm     |     1
 MMNH:Bird    |     1
 MMNH:Mamm    | 14145
 MSB:Bird     |    46
 MSB:Fish     |  7661
 MSB:Herp     |  4507
 MSB:Host     |    13
 MSB:Mamm     |   478
 MSB:Para     |   321
 NCWRC:Fish   |     2
 NCWRC:Mamm   |     1
 NMMNH:Paleo  |     2
 NMU:Mamm     |   332
 UAM:Arc      | 22141
 UAMb:Herb    |   485
 UAM:Bird     |     3
 UAM:EH       |    42
 UAM:Ento     | 18462
 UAM:ES       |   102
 UAM:Herb     |     4
 UAM:Inv      |     2
 UAM:Mamm     |    23
 UAMObs:Ento  |   500
 UCM:Bird     |     1
 UMNH:Mamm    |     2
 UMZM:Mamm    |    22
 UNCG:Para    |    11
 UTEP:Ento    |    34
 UWBM:Mamm    |     5
 UWYMV:Mamm   |     1
 UWZM:Bird    |  1375
```

I was going to suggest https://github.com/ArctosDB/arctos/issues/5460 be added to Thursday's AWG meeting, but I'm not sure it should proceed before this, and I don't think this is a great candidate for an Issues meeting. This feels stuck, I'm not sure what to do, HELP!

I am adding wildfire potential - I don't think things are being used properly, and using the wrong type is an assertion that's going to confuse all future users; this is probably actively degrading data.

**Comment by Jegelewicz** [comment]
other_id_type | description  |  base_url  
 -- | -- | -- 
ALMNH Ethnology Collection          | Alabama Museum of Natural History Ethnology Collection                                 | 
ALMNH History Collection            | Alabama Museum of Natural History Historical Object Collection | 

As above, the History and Ethnology Collections are expected to be combined in a single EH colelction when they have previously been maintained as two. However, as far as I know, only History (Gorgas House) has been migrated and I do not know the status of the Ethnology material.

**Comment by Jegelewicz** [comment]
other_id_type | description  |  base_url  
 -- | -- | -- 
ALMNH Geology Collection            | Alabama Museum of Natural History Geology Collection | 

If my memory is correct, geology was previously cataloged with non-integer catalog numbers, this identifier is meant to hold those numbers as catalog numbers are to be converted to integer upon migration.

**Comment by Jegelewicz** [comment]
other_id_type | description  |  base_url  
 -- | -- | -- 
ALMNH: Museum Expedition            | Identifier associated with an Alabama Museum of Natural History collecting expedition. | 
ALMNH: Museum Staff Trip            | Identifier associated with an Alabama Museum of Natural History staff trip. |

I could see these being converted to projects but

https://github.com/ArctosDB/arctos/issues/3539

**Comment by campmlc** [comment]
I suggest we have a UI meeting to address this, or use the office hours
tomorrow. The solution to me seems a complete rework of how we view
identifiers, but that means adding the needed metadata, which is for
whatever reason still on hold. In person discussion seems to be needed.

**Comment by dustymc** [comment]
This clearly isn't UI and I strongly suggest we keep the ad-hoc groups focused, and disband them when that becomes difficult. (I think that's why they're effective!)

I think we should probably get rid of the office hours thing too (It's always at most one person, they could have scheduled a meetup at some time that's more convenient for them by filing an Issue - does everyone know that's possible??), but it's a decent time for an ad-hoc group. 

Shall we schedule the first meeting of Task Force Identifiers Awesomification for noon Pacific tomorrow?

**Comment by acdoll** [comment]
RE: preparator vs. collector number - these are two separate values we would certainly like to keep. 
Example: John collected chipmunks in the field and assigns each one of his serial collector numbers (JRD-XXXX). It ends up in our freezer and sometime later gets prepped in our lab by our preparator, Andie, who assigns it one of her serial preparator number (AMC-XXXX). 
We get lots of stuff through our salvage program which has no field/collector numbers, but they will often get a preparator number, depending on who is prepping it.

**Comment by dustymc** [comment]
One goal of https://github.com/ArctosDB/internal/issues/251 should be to make sure that whatever we know about authorities should be recorded with them, not stuck in someone's head. Suggestions for accomplishing that greatly appreciated.

@acdoll could we talk you into writing documentation that clearly distinguishes from [collector number](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type#collector_number)?

I suspect that involves beefing up the collector number documentation as well. And maybe @ccicero could be talked into joining, I think she's where I got the idea (wrong though it may be!) that this isn't a functional distinction (eg they all end up in the same book).

**Comment by acdoll** [comment]
> clearly distinguishes from [collector number](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type#collector_number)?

They are not a collector; I'd be happy to write some documentation, but I don't see what is wrong with the current definitions. Collection numbers refer to the act of collection. Preparation numbers refer to the act of preparing/preserving a specimen.

> Are they in two separate books

Yes. They are two distinct types of numbers designating two distinct processes.

**Comment by dustymc** [comment]
> refer to the act of 

I think that's my point of confusion. I don't think the activity makes any difference, I just want to know where I might find more data (which is more or less why IDs exist). If the answer is "all in the same place" (I think maybe that's true for some collections/users/????) then this seems straightforward. If the type is necessary to get me to the data then it's at least worth more discussion. If I'm just confused them maybe we need more documentation. 

I'll save anything that looks like it might be sticky for last-ish in the cleanup queue, so perhaps we'll all have a bit more of an idea how the new data is going to shape the system by the time we really need to finish this conversation, and if you can shine up the docs then maybe that'll make that smoother/unnecessary.

**Comment by acdoll** [comment]
> If the type is necessary to get me to the data

Yes, knowing if we're looking at a collector number vs. a preparator number would point us to different sources of original data. I'll consider some different language that would help clarify these types.
