### ISSUE TITLE
Berkeley Mapper Issue [CONTACT]

### ISSUE THREAD

**Issue by jldunnum** [ArctosDB/arctos#5717]
The record results are not appearing at the bottom of the Berkeley mapper page. Dynamic relationships between map place markers and records are not working.
![image](https://user-images.githubusercontent.com/17278851/221646765-1e941e68-66dc-46b6-b9f6-fcb3ac6f273f.png)

**Comment by Jegelewicz** [comment]
@jldunnum Is this still not working?

**Comment by jldunnum** [comment]
This is functional again so this issue could be closed. Thanks!
