### ISSUE TITLE
volume code table is poorly named and contains a nonsensical value

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5718]
(The template is from https://github.com/ArctosDB/internal/issues/251 and change suggestions are most welcome.)

## Initial Request

**Goal**: Describe what you're trying to accomplish. This is the only necessary step to start this process. The Committee is available to assist with all other steps. Please clearly indicate any uncertainty or desired guidance if you proceed beyond this step.

Limit volume units to things which can be used to measure volume.

**Proposed Value**: Proposed new value. This should be clear and compatible with similar values in the relevant table and across Arctos. 

This proposal is to REMOVE "percent" from https://arctos.database.museum/info/ctDocumentation.cfm?table=CTTISSUE_VOLUME_UNITS

**Proposed Definition**: Clear, complete, non-collection-type-specific **functional** definition of the value. Avoid discipline-specific terminology if possible, include parenthetically if unavoidable.

Tissue volume units should be limited to volume units, and the table should be generalized to 'ctvolume_units'

**Context**: Describe why this new value is necessary and existing values are not.

The current data do not make sense to me - "10 percent of some unknown something" is, I believe, the only viable interpretation of this.

This will require finding a new home for existing data, but only 4 records are involved.

Alternatively some better definition might be developed, but I believe that any useful definition would also provide an easy path to conversion, and as absolute volumes these data might be useful for many unanticipated uses. I can still see not way to justify retaining this value.

**Table**: Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table or value. This may involve multiple tables and will control datatype for Attributes. OtherID requests require BaseURL (and example) or explanation. Please ask for assistance if unsure.

See above

**Collection type**: Some code tables contain collection-type-specific values. ``collection_cde`` may be found from https://arctos.database.museum/home.cfm

All collections should have a volume CT available.

Only MSB:Mamm would be involved in any cleanup.

**Priority**: Please describe the urgency and/or choose a priority-label to the right. You should expect a response within two working days, and may utilize [Arctos Contacts](https://arctosdb.org/contacts/) if you feel response is lacking.

I believe all code table cleanup Issues should be highest priority; these values become used and cleanup of the specific issue becomes more difficult, and nonsensical data are near-inevitably used as justification for more indefensible data. 

**Available for Public View**: Most data are by default publicly available. Describe any necessary access restrictions. 

none

**Discussion**: Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

@campmlc @jldunnum @AdrienneRaniszewski - can I assume these refer to a 1.8mL tube and convert appropriately?

```

 part_id  |      guid       | guid_prefix | part_name |  attribute_type  | attribute_value | attribute_units | determined_date |     determiner     |           remark            | attribute_method 
----------+-----------------+-------------+-----------+------------------+-----------------+-----------------+-----------------+--------------------+-----------------------------+------------------
  2136493 | MSB:Mamm:40797  | MSB:Mamm    | liver     | remaining volume | 10              | percent         | 2021-06-04      | Mariel L. Campbell | not enough for future loans | 
  2138106 | MSB:Mamm:43526  | MSB:Mamm    | kidney    | remaining volume | 10              | percent         | 2021-06-04      | Mariel L. Campbell | not enough for future loans | 
  2138140 | MSB:Mamm:43531  | MSB:Mamm    | kidney    | remaining volume | 10              | percent         | 2021-06-04      | Mariel L. Campbell | not enough for future loans | 
 27858154 | MSB:Mamm:311832 | MSB:Mamm    | liver     | remaining volume | 5               | percent         | 2021-06-04      | Mariel L. Campbell | not enough for future loans | 
(4 rows)
```

## Approval

All of the following must be checked before this may proceed.

The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality).

- [ ] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [ ] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection

If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc. 

1. Can a suitable solution be found here? If not, proceed to (2)
2. Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)
3. Take the discussion to a monthly Arctos Working Group meeting for final resolution.

## Implementation

Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made.

Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel. 

Make changes as described above. Ensure the URL of this Issue is included in the definition. 

Close this Issue.

**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result.

## Special Exemptions

In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases.

1. Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step.
2. The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology.

**Comment by Jegelewicz** [comment]
See also https://github.com/ArctosDB/arctos/issues/3626

**Comment by Jegelewicz** [comment]
Also - I think we need to remove "tissue" - these volume units should be used wherever we have a need for them.

**Comment by dustymc** [comment]
>See also

Yes, our "easy" problems sure have a way of piling up if they're not immediately contained. (And maybe that's strong evidence that we need to be a lot more aggressive about this sort of thing??)

>Also - I think we need to remove "tissue" 

>Tissue volume units should be limited to volume units, and the table should be generalized to 'ctvolume_units'

??

**Comment by mkoo** [comment]
only makes sense if we have a method of "eyeballing"

**Comment by dustymc** [comment]
> method of "eyeballing"

That's fine/expected, but the assertion is still for "half of something."

How can this proceed? It should have been discussed today, but I didn't put it on [The List](https://github.com/ArctosDB/arctos/milestone/16) and the issues meeting somehow completely avoided the issues list anyway.....

**Comment by campmlc** [comment]
I fixed all the MSB:Mamm tissues - they were misentered as % instead of mg.
No one else needs a "percent" remaining volume going forward - so the alternate path of creating a new part attribute is not necessary?

**Comment by dustymc** [comment]
>misentered

Confirmed

```

arctosprod@arctos>> select 
arctos->     specimen_part.collection_object_id as part_id,
arctos->     flat.guid,
arctos->     flat.guid_prefix,
arctos->     part_name,
arctos->     specimen_part_attribute.attribute_type,
arctos->     specimen_part_attribute.attribute_value, 
arctos->     specimen_part_attribute.attribute_units,
arctos->     specimen_part_attribute.determined_date,
arctos->     getPreferredAgentName(specimen_part_attribute.determined_by_agent_id) as determiner,
arctos->     specimen_part_attribute.attribute_remark as remark,
arctos->     specimen_part_attribute.determination_method as attribute_method
arctos-> from 
arctos->     specimen_part_attribute
arctos->     inner join specimen_part on specimen_part_attribute.collection_object_id=specimen_part.collection_object_id
arctos->     inner join flat on specimen_part.derived_from_cat_item=flat.collection_object_id
arctos-> where 
arctos-> --specimen_part_attribute.attribute_type='remaining volume' and
arctos-> specimen_part_attribute.attribute_units='percent'
arctos-> ;
 part_id | guid | guid_prefix | part_name | attribute_type | attribute_value | attribute_units | determined_date | determiner | remark | attribute_method 
---------+------+-------------+-----------+----------------+-----------------+-----------------+-----------------+------------+--------+------------------
(0 rows)
```

and removed. Thanks!

I'll open another non-urgent issue for the bigger generalization.
