### ISSUE TITLE
Code Table Request - Add Ovid 7.5 minute to quad table

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#5719]
**Goal**
I need to add this quad to a locality, and it is not in the code table already.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctquad

**Proposed Value**
Ovid 7.5 minute

**Proposed Definition**
This code table does not have definitions

**Proposed Documentation**
Link to this issue

I can add this value if there are no objections.

**Comment by dustymc** [comment]
> This code table does not have definitions

It does, they're just all cruddy. Can we change that? This one's a good example of why - Google suggests it might be NY or ID.

Actually now I'm even more confused - is there some problem with one "Ovid 7.5 minute" quad that gets used in a bunch of states? Did USGS really do that??

ANYWAY - if these aren't unique then we need more sorting-out, if they are then a definition ("Southern New Mexico" or similar seems sufficient) seems necessary.

No objections to adding this either way, but if we can stop digging the hole we're standing in deeper then we should.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> used in a bunch of states

I don't know how widespread this problem is. It wasn't an issue when this was under geography, but obviously that had its own issues. If we can grab a copy of the quads as geography data, perhaps the states could be autopopulated into the definitions.

Initially when we added these, we added what we thought were stable links to the individual usgs quad maps. Then USGS updated how it handled the maps (https://ngmdb.usgs.gov/topoview/), and they frustratingly don't have individual links, much less a DOI or some sort of permalink.

**Comment by dustymc** [comment]
Yes no problem (other than https://github.com/ArctosDB/internal/issues/222) to have quads as FFF's - https://arctos.database.museum/place.cfm?sch=geog&quad=_ is what's there now.

States could be derived from spatial assertions, but quad would take us back to the problem we solved by the change: they cross state lines and hang off into the ocean and etc. etc. etc. (So maybe we can't get nice 1:1 ratios everywhere but we can still answer lots of questions.)

ANYWAY - I'd still like to see a state or something - more than nothing! - as documentation, and we can deal with the "yeabut!"s when/if we're forced to.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> quads as FFF's

That would be really nice sometime in the future.

> States could be derived from spatial assertions

I was just thinking for now, since these were recently migrated, that we could use one of the files in #5003 to magic geography data into the documentation. It shouldn't be too hard to concatenate multiple counties/states. I can work on a file if you think that will work.

In the meantime, proposed documentation for Ovid Quad: Bear Lake County, Idaho, link to this issue.

**Comment by dustymc** [comment]
> magic geography data into the documentation

OH! Yea, that sounds great, happy to load it if you want to put something together.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Here it is: 
[QuadsGeography.csv](https://github.com/ArctosDB/arctos/files/10855671/QuadsGeography.csv)

I included the Github issue link, so you can just entirely replace the documentation. I've only added one quad since the conversion to attribute, I included that in the file, if anyone else has added anything, those are not included.

**Comment by dustymc** [comment]
Thanks, docs updated

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Are all the values that weren't updated just not used? I think the file I pulled from #5003 only had used values.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Ovid Quad added.
