### ISSUE TITLE
Barcode Series Request - reserved barcodes not found

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#5720]
Issue Documentation is at http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html 
Barcode Series Documentation is at http://handbook.arctosdb.org/documentation/container.html#barcode-series

A bit ago with help from Dusty I edited the UAM barcode series here

https://arctos.database.museum/info/barcodeseries.cfm

so that we have reserved UAM100000001 - UAM299999999

but when I search containers for UAM299999999

nothing is found but shouldn't I be able to find that code and edit it etc?

**Priority**
Please assign a priority-label.
high - we need to start using this UAM2 series soon!

**Comment by Jegelewicz** [comment]
@DerekSikes they are reserved, but they haven't been created - see https://handbook.arctosdb.org/how_to/How-to-Start-Object-Tracking.html#create-containers

**Comment by DerekSikes** [comment]
Thanks! There is no 'Create Container Series' link in the [Barcodes & Containers](https://arctos.database.museum/directory.cfm) (and the handbook guide needs updating now? plus 'This step enters enters your ' needs editing to remove the extra 'enters'

Is this now called Bulk Edit Container or Bulkload Containers ?

**Comment by DerekSikes** [comment]
that tool requires  collection.institution_acronym but this is not found when I search the handbook. I assume for my collection, UAM:Ento this would be just UAM? But I don't want to get this wrong. It's not explained eg with an example...

**Comment by DerekSikes** [comment]
But this will require making a file with 199,099,998 rows of data to upload. That seems difficult. Advice???

**Comment by dustymc** [comment]
>Advice

https://handbook.arctosdb.org/documentation/container.html#object-tracking-in-general

Create the containers when you have labels in hand; otherwise you'll never know what you have ("somewhere...." I believe is the common state), and what you have reserved but have not printed/ordered.

If you have some alternative proven procedure, please add it to the how-to.

**Comment by DerekSikes** [comment]
Thanks!
