### ISSUE TITLE
Feature Request - Berkeleymapper no longer has topo maps??

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#5721]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

Why do things get worse instead of better?

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

high - I need topo maps to verify locality data quality

**Comment by mkoo** [comment]
Apologies @DerekSikes ! 
the in-progress updated version got launched to production instaed of sticking to the test server. We are not planning on having fewer basemaps! They will be back and a lot more functions too. so sorry for the inconvenience. 

As for checking georeferences you could use Geolocate instead for now (I know it's extra steps to get there...)

Go to Edit locality and near the bottom of the page, click on the button Modify spatial with Geolocate (or something along those lines) which will place your georef on the map (then you have more than one ESRI topo quads and county lines to choose from (right hand side plus sign)

**Comment by DerekSikes** [comment]
Ah, good to hear!!
thnx!
