### ISSUE TITLE
Attribute bulkloader issue

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#5722]
I've mucked something up with the Attribute bulkloader. It's taking forever and I'm getting warnings like these for every forth record or so:

load fail::ERROR: deadlock detected Detail: Process 13270 waits for ExclusiveLock on tuple (1344498,1) of relation 18624812 of database 18624026; blocked by process 143681. Process 143681 waits for ShareLock on transaction 1496435541; blocked by process 13527. Process 13527 waits for ExclusiveLock on tuple (1342397,2) of relation 18624812 of database 18624026; blocked by process 13271. Process 13271 waits for ShareLock on transaction 1496434615; blocked by process 13270. Hint: See server log for query details. Where: SQL statement "UPDATE flat SET stale_flag = 1, lastuser=usr, lastdate=LOCALTIMESTAMP, last_edited_table=tbl WHERE collection_object_id = cid and -- no reason to do anything if already marked stale_flag != 1" PL/pgSQL function mark_flat_stale(name,name,bigint) line 3 at SQL statement SQL statement "SELECT mark_flat_stale(session_user,TG_TABLE_NAME,id)" PL/pgSQL function trigger_fct_tr_attributes_aiud_flat() line 16 at PERFORM

**Comment by dustymc** [comment]
Yep, that's stuck...

I'm going to shut down most automation while I sort things out.

**Comment by dustymc** [comment]
I think everything is unkinked and working as it should now.
