### ISSUE TITLE
Legacy reporter down?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#5723]
I get "nope" when I try to access. Can it be kickstarted, or fully dead?

**Comment by mkoo** [comment]
It's up for me
note that it is on plain ol' http so your browser may need an exception to
access since it's not a secure https URL

**Comment by campmlc** [comment]
But the fact that it diverts to "nope" makes me think that some sort of @dustymc speak is involved?

**Comment by mkoo** [comment]
Nope-- a TACC issue. Not sure if it's worth their effort to install SSL
certificate but we can ask.

Meanwhile it's up and available, you just need to let your browser access
it. The 'Nope' is coming from Chrome or FF or whatever. (you probably
already allow pop-up windows in these clients so similar preference setting)

**Comment by campmlc** [comment]
Any chance anyone knows how to fix this in chrome? I go to Privacy and
Security, then Site settings, and see no way to add anything.

**Comment by campmlc** [comment]
I went from a loan, as I needed to print loan forms.

**Comment by campmlc** [comment]
Loans is where I've always accessed the legacy reporter from.

**Comment by campmlc** [comment]
I was able to access from an incognito window, so must be browser/ TACC issue?
