### ISSUE TITLE
search fails with non-breaking spaces between GUIDs

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#5724]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
It is really nice that we can search GUID without having to first remove all spaces and add commas as was necessary before. I just did a search by grabbing a column of GUID's from a spreadsheet and was confused when I was missing two records. After some staring very hard, I realized there were TWO spaces between some GUID's, rather than one. It just failed to return the records with two spaces after them. However, it does not seem exactly like spaces. I tried doing a search of GUIDs, but adding extra spaces. They worked fine. I pasted the offending records into Word. The little circle by 225110 looks like a space in the GUID search box, but causes that record to fail. I think it is a non-breaking space.
Is there a way to make the search box more robust to these sorts of things? 
<img width="228" alt="Screenshot 2023-02-27 at 4 04 25 PM" src="https://user-images.githubusercontent.com/5749672/221718930-aebcf803-3932-48b2-9e78-2909b24232b9.png">
<img width="263" alt="Screenshot 2023-02-27 at 3 41 55 PM" src="https://user-images.githubusercontent.com/5749672/221718934-ff59294d-247e-4041-857d-c2a585bb35d4.png">

**Comment by Jegelewicz** [comment]
I generally use the [Listerizer tool ](https://arctos.database.museum/DataServices/listerizer.cfm) to get lists for these kinds of searches - I don't know if it fixes these kinds of things, but it would be interesting to see what happens to your list in that tool.

**Comment by cjconroy** [comment]
Listerizer does not remove it. Pasted what listerizer did and the record preceding it is not returned. 
I used your link for the listerizer. I can't find it in the new interface. How do you get to it now?

<img width="1351" alt="Screenshot 2023-02-28 at 12 24 42 PM" src="https://user-images.githubusercontent.com/5749672/221970489-6185b6d5-3c3c-421c-a12d-33df05463fbe.png">

**Comment by dustymc** [comment]
>Listerizer does not remove it

It can - can you attach a text file with that data, or enclose the data in three tick marks in a comment?

**Comment by cjconroy** [comment]
Here is an excel file and a csv of the same thing. The offending character is after 225110.
[SpaceTest.csv](https://github.com/ArctosDB/arctos/files/10855467/SpaceTest.csv)
[SpaceTest.xlsx](https://github.com/ArctosDB/arctos/files/10855468/SpaceTest.xlsx)

**Comment by Jegelewicz** [comment]
![image](https://user-images.githubusercontent.com/5725767/222009650-4e906ee7-1a4e-4e32-aa45-25981d0d0179.png)

 is where you find that tool now.

**Comment by campmlc** [comment]
Maybe we could rename as "Generate CSV List"

**Comment by cjconroy** [comment]
I was looking in the table view. Not sure it is there. Cannot find by searching that page for "list"

**Comment by dustymc** [comment]
>Generate CSV List"

That's not accurate.

>e table view. Not sure it is there.

Woops, typo, patched.

@cjconroy here's your CSV:

<img width="250" alt="Screenshot 2023-03-01 at 7 18 18 AM" src="https://user-images.githubusercontent.com/5720791/222182526-7a55aaed-0e7b-4b9e-bc3a-4683f4fa5e72.png">

Something (Excel seems to have been involved, I have guesses) has added a nonbreaking space, in addition to a normal space. The tool should handle that now.

```MVZ:Mamm:224568,MVZ:Mamm:224969,MVZ:Mamm:225110,MVZ:Mamm:226083,MVZ:Mamm:227369,MVZ:Mamm:228329```

**Comment by campmlc** [comment]
How about List Generator? Listerizer is cute, but most people won't know
what that is.

**Comment by campmlc** [comment]
Maybe we should copyright the name and code :)
I'm.ok with it, as I now know what it is and where to find it. Hopefully
others feel the same.
