### ISSUE TITLE
Working with Agents is painful

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5727]
I have been working quite a bit with Agents today and Arctos tends to hang up on Agent search about every third search or even every third link to another agent. I have to close the tab, open a new Arctos tab and go back to Manage Agents to get any work done.

Sometime I have to make two or three tries to finally get back to work.

Maybe this is more than agents, but that is where I am working right now, so it seems like an agents problem to me.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Arctos has been slow/not loading on and off for me today.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Just came back up for me.
