### ISSUE TITLE
query string argument of EXECUTE is null

### ISSUE THREAD

**Issue by catherpes** [ArctosDB/arctos#5729]
This is the error I get when I try to save a new record in the online data entry screen. 
My afternoon will be full of meetings so won't be able to provide more information so hopefully this is sufficient. It doesn't seem like it is and I'm sorry for that. 

Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

**To Reproduce**

**Expected behavior**
Acceptance of record, or an intelligible error I can fix.
**Screenshots**

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**
Windows OS
firefox browser.
**Additional context**

**Priority**
High. Would like to have this record in today so I can be done with it.

**Comment by dustymc** [comment]
I unfortunately don't see anything like this in the logs, nor can I find anything that might have caused it in the code. You should be able to log in from another tab and try the save again if the page is still open.

**Comment by campmlc** [comment]
If this happens again, can you take a screenshot?

**Comment by catherpes** [comment]
![image](https://user-images.githubusercontent.com/38987000/222008905-b5e497cc-bd6c-452c-8df8-01b87b895867.png)

**Comment by catherpes** [comment]
![image](https://user-images.githubusercontent.com/38987000/222009052-aded0e04-83c0-4757-80a8-486e60cc666e.png)

**Comment by catherpes** [comment]
i put a negative sign in front of longitude so it doesn't map to China and it still does the same thing. Not that the program should have cared about that negative sign.

**Comment by campmlc** [comment]
What about your agents? Some are not yellow highlighted - did Arctos accept
them? Try taking off the last letter and hitting tab?
Regardless, you shouldn't get such an uninformative error - but maybe we
can figure out the source to fix it.

**Comment by catherpes** [comment]
I just fixed the accession, which was in a pick popup I didnt' see. That was not the problem, although it would have been eventually. 
I'll try your suggestion.

**Comment by campmlc** [comment]
I've had problems before with weird errors if the accession isn't recognized. But still, it would be helpful to have an error that says "accession required".

**Comment by catherpes** [comment]
nothing with agents has helped.

**Comment by catherpes** [comment]
![image](https://user-images.githubusercontent.com/38987000/222010558-1695f237-acaa-4f2b-9b35-be8127740f86.png)

**Comment by catherpes** [comment]
![image](https://user-images.githubusercontent.com/38987000/222010611-031a4c89-abaf-452f-ba9f-a74b4a48a5c9.png)
This is where I'm leaving it tonight. Time to run off to my next appt.

**Comment by campmlc** [comment]
I can take a look again tomorrow - the only thing that seems weird is that Wildlife Rescue of NM isn't highlighted; also Jenna's name.

**Comment by dustymc** [comment]
I still can't see any errors (TACC is ~~flinging poo at an amazing rate~~ conducting a security audit, so it's hard to see anything) so I tried to make one, and failed.

## I made a MSB:Bird record in production

Please don't load it.

Data errors should produce data errors, and they do for me:

<img width="1600" alt="Screenshot 2023-02-28 at 4 16 18 PM" src="https://user-images.githubusercontent.com/5720791/222013226-50ab4b5e-737b-4927-b914-9e211d0c703a.png">

I clicked the button a bunch of times as the list got smaller and smaller, eventually ended up here...

<img width="1631" alt="Screenshot 2023-02-28 at 4 19 38 PM" src="https://user-images.githubusercontent.com/5720791/222013253-2fc654ba-a842-47b6-9dea-fb6e069d34ad.png">


... and then https://arctos.database.museum/Bulkloader/browseBulk.cfm?collection_object_id=99083766 happened.

@catherpes please delete or let me know if it's no longer useful and I will.

The best place to look is in your javascript console, you can google that plus your browser (it should output lots of stuff when you try to save, hopefully some of it has whatever I need), or better yet can you find some local IT help to do that?

**Comment by campmlc** [comment]
Maybe he should just delete the record. log out, log in, and reenter it? A
pain, but if something is his browser is doing something, or if something
timed out, that should catch it?

**Comment by dustymc** [comment]
>delete the record.

There's obviously something going on here, I'd like to know what it is so I can fix it - but I'll also totally understand if you're tired of being a test mule.

One easy experiment might be to 'enter from seed' from my record and see if you can save it - that might provide some evidence suggesting something in some data field vs a haunted computer. (And let me know if you need help cleaning up these experiments - I try to make them ridiculous enough they'll be easy to spot even if they make it all the way through....)

**Comment by catherpes** [comment]
I rebooted the following day and was able to successfully load a re-entered version of the record. My OS wanted to update at the same time, so I allowed that.

**Comment by campmlc** [comment]
That's good news. I added the tissue barcodes to the record as well
yesterday pm.
