### ISSUE TITLE
Code Table clean up - UCM Other Identifiers

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5731]
@ebraker can you confirm that these should be changed to Colorado?

Other identifier | description 
-- | -- 
UCM Synoptic Teaching Collection [ link ] | University of **California** Museum Synoptic Teaching Collection identifier
UCM Public Education and Exhibition Collection [ link ] | University of **California** Museum Public Education and Exhibition Collection identifier

**Comment by ebraker** [comment]
@Jegelewicz oh wow, YES please!

**Comment by Jegelewicz** [comment]
Confirmed only in use by UCM collections and changed.

**Comment by dustymc** [comment]
>Confirmed...and changed.

No user has sufficient access to confirm this sort of thing, and therefore I strongly oppose *any* changes which aren't documented by a request (https://github.com/ArctosDB/internal/issues/251)

These are in fact used only by UCM, but that should never be determined after a change has been made.

There's no issue in the documentation.

@mkoo pretty please can we prioritize adopting some sort of procedure?

```
select guid_prefix,other_id_type,count(*) from
coll_obj_other_id_num
    inner join cataloged_item on coll_obj_other_id_num.collection_object_id=cataloged_item.collection_object_id
    inner join collection on cataloged_item.collection_id=collection.collection_id
where
    other_id_type in ('UCM Public Education and Exhibition Collection','UCM Synoptic Teaching Collection')
    group by guid_prefix,other_id_type order by guid_prefix,other_id_type
;


 guid_prefix |                 other_id_type                  | count 
-------------+------------------------------------------------+-------
 UCM:Bird    | UCM Public Education and Exhibition Collection |    27
 UCM:Bird    | UCM Synoptic Teaching Collection               |   214
 UCM:Fish    | UCM Synoptic Teaching Collection               |   375
 UCM:Herp    | UCM Public Education and Exhibition Collection |     5
 UCM:Herp    | UCM Synoptic Teaching Collection               |    83
 UCM:Mamm    | UCM Public Education and Exhibition Collection |    82
 UCM:Mamm    | UCM Synoptic Teaching Collection               |    32
(7 rows)
```
