### ISSUE TITLE
Finding Entities by Search of component Identifiers

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#5734]
Request to find Entity records by searching on an identifier of a component record.
Problem:
I just searched on the following list of Albuquerque Biopark Local IDs, all of which are components of Entities, but the search results only returned one Entity record.
M10032,M02025,10113,M02033,M02027,M02032,8120,M02029,M18007,M98020,M92067,M07003
I also tried the search by explicitly selecting the Entity collection, with the same result.

The Entity that was returned in the search, Arctos:Entity:1, was created manually. All the others were created with the automated entity creation tool. Can we modify this tool so that Other IDs associated with components get added to the entity, so that if I search on a Biopark ID, I get the Entity record returned as well as the components? Or somehow modify the search tool so that these records show up in search?

Priority: High, needed for work.

**Comment by campmlc** [comment]
I'm not sure what discussion is needed. If the entity model is going to work, we should be able to find entities when we search on component IDs, at the very least the component ID which was used to create the Entity. Right now, if I search on the following list of Albuquerque Zoo Local IDs needed for a loan, I get over 3000 records, yet these represent only 17 entities.
M03031,10113,M92067,M98020,M13018,M18007,M06015,m02052,m02031,m15026,m15013,m19008,m13006,m16010,m08034,M18013,M18013 
Wading through these to find the correct samples for a given date is virtually impossible unless I go one by one, and even then I'm dealing with multiple pages as I can only view 100 records at time logged in. 
If I could search the Entity records directly, based on these identifiers - which were used to create the Entities - I would have 17 records to examine. This is possible.

Priority: High. Actively impeding work.

**Comment by Jegelewicz** [comment]
This should have been handled by #6807 for all MSB entities. Tested on M03031 and it worked. Closing.

**Comment by campmlc** [comment]
The identifier added to MSB Entities for the Albuquerque Biopark specimens is incorrect. MSB uses the identifier type "Albuquerque Biopark Zoo Local ID" to track all specimens from this source. We do not use and object to the use of identifier type = "identifier" "issued by" "Albuquerque Biopark Zoo Local Identifier". This needs to be fixed.
@AdrienneRaniszewski @jldunnum @Jegelewicz

**Comment by campmlc** [comment]
Ditto for GAN, which we use and search on as an identifier type, not "identifier" issued by an agent that is itself an ID type.

**Comment by campmlc** [comment]
Also, https://arctos.database.museum/guid/Arctos:Entity:4 is incorrectly associated with M02024.

**Comment by mkoo** [comment]
The original issue of finding Arctos Entity with a component of the identifier appears resolved:
Searching on the identifier value of M02024, results  in https://arctos.database.museum/guid/Arctos:Entity:320
![Firefox_Screenshot_2024-05-07T23-33-04 985Z](https://github.com/ArctosDB/arctos/assets/2523089/df546e1b-6d00-41db-afa0-0b4dd2b4d2d0)
