### ISSUE TITLE
Feature Request - lock down components

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5735]
**Is your feature request related to a problem? Please describe.**

A bot has been trying to access webservices.

**Describe what you're trying to accomplish** 

More secure

**Describe the solution you'd like**

Require some sort of authentication, probably involving auth_key

**Describe alternatives you've considered**

There are none

**Additional context**

Don't think anything's actually vulnerable, but this makes me nervous and implementation should be straightforward

**Priority**

high because this seems a good place to be paranoid

**Comment by ewommack** [comment]
So stepping up from the click button to access stuff system we've been using?

**Comment by dustymc** [comment]
@ewommack no, this is nothing a human should notice, the current level of authentication still seems satisfactory.

This turned into a major refactor, so I've just done the things that looked most critical and ran a quick check to look for any huge gaps (which I didn't find). We are using components as both functions and APIs, which is one of the really great things about coldfusion, but also probably not a great idea with current threat levels.

I moved some things into the versioned API system, but these are all "local" and probably should be moved up a step for simplicity.

Minimally and immediately, stop digging the hole deeper: Do not create remote-access functions.

Eventually, eg when changing something or when there's a small timeslot to fill:

1. Anything which is only remote access can simply be moved to APIs/behind API security
2. Anything which serves as both a function and an API should be mirrored as an API call+invocation

I'm not ready to drop the wildfire tag, but I think this is a low-smouldering situation which can be addressed over time.

**Comment by ewommack** [comment]
> Minimally and immediately, stop digging the hole deeper: Do not create remote-access functions.

What are the remote-access functions that we have now? Is that people who have access to individual API keys or something in the database permissions?
