### ISSUE TITLE
Remove all NMMNHS: New Mexico Museum of Natural History and Science identifiers

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5736]
All [NMMNHS: New Mexico Museum of Natural History and Science](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type#nmmnhs__new_mexico_museum_of_natural_history_and_science) identifiers have been entered as NMMNH:Mamm relationships. The identifiers need to be removed and that value dropped from the code table.

**Comment by Jegelewicz** [comment]
Here it is - I have confirmed that all of these have an identical same individual as NMMNH:Mamm identifier.

[MSB_NMMNH_Mamm_identifiers.csv](https://github.com/ArctosDB/arctos/files/10865047/MSB_NMMNH_Mamm_identifiers.csv)

**Comment by Jegelewicz** [comment]
As expected, there are a few outliers.

guid | scientific_name | [nmmnhs](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type#nmmnhs__new_mexico_museum_of_natural_history_and_science)
-- | -- | --
MSB:Mamm:271014 | Geomys bursarius | X
MSB:Mamm:271015 |  Geomys bursarius | X
MSB:Mamm:271016 | Geomys bursarius | X
MSB:Mamm:271017 | Thomomys bottae | X
MSB:Mamm:271018 | Thomomys bottae | X
MSB:Mamm:271019 | Thomomys bottae | X
MSB:Mamm:271020 | Cratogeomys castanops | X
MSB:Mamm:273564 | Thomomys bottae | X
MSB:Mamm:273565 | Dipodomys merriami | X
MSB:Mamm:273619 | Tadarida brasiliensis | X 

All of these do not have a number, but instead just an "X". I assume this was because the number was not known. I will see if I can work them out based upon missing NMMNH numbers in the MSB records and matching localities.

**Comment by Jegelewicz** [comment]
All of the above also include institutional catalog number = NMMNH, so I think we can just remove those as well.  Here is the final.
[MSB_NMMNH_Mamm_identifiers.csv](https://github.com/ArctosDB/arctos/files/10865157/MSB_NMMNH_Mamm_identifiers.csv)

Please indicate that I can unload these.

**Comment by Jegelewicz** [comment]
Also -to see what I did to match things here is the whole workbook.
[MSB_NMMNH_Mamm_identifiers.xlsx](https://github.com/ArctosDB/arctos/files/10865181/MSB_NMMNH_Mamm_identifiers.xlsx)

**Comment by mkoo** [comment]
@lin-fred @Jegelewicz ok to proceed? this seems pretty straightforward for a handful! 
Let us know if there's something else blocking fixing this

**Comment by lin-fred** [comment]
I'm fine with it but you're not altering my data, you'll be altering MSB's records

**Comment by jldunnum** [comment]
We are OK with this proceeding, thanks

**Comment by Jegelewicz** [comment]
These are done - @dustymc you can remove this from the code table.
