### ISSUE TITLE
Other Identifier Locality ID should be moved to locality attribute

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5739]
There are over 250K records using the [Locality ID](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type#locality_id) attribute. These should be added to the appropriate localities as a [site identifier](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlocality_attribute_type#site_identifier) locality attribute. Although the definition suggests they belong with collecting event?

This one is going to take a lot of work - I would bet that there are multiple localities per identifier and possibly requires review by individual collections

**Comment by dustymc** [comment]
At least those of these owned by @sjshirar are where they need to be. 

The definition is correct and explains why these are where they are.

Those from other collections might be mistyped, but that has come to be expected.

```
 guid_prefix | count  
-------------+--------
 ALMNH:Paleo |   6894
 DMNS:Inv    |   1061
 MSB:Mamm    |      1
 NMMNH:Paleo |   1682
 UAM:Arc     | 507539
 UAM:Ento    |   2301
 UAM:ES      |  35772
 UCM:Herp    |      1
 UTEP:Ento   |     82
 UTEP:ES     |     38
 UTEP:Inv    |   1337
```
I suggest this be closed as inactionable.

related:

* https://github.com/ArctosDB/arctos/issues/4604#issuecomment-1448966173
* https://github.com/ArctosDB/arctos/discussions/5707
* https://github.com/ArctosDB/arctos/issues/5715

**Comment by Jegelewicz** [comment]
I don't understand why this isn't part of code table cleanup

**Comment by sharpphyl** [comment]
>  DMNS:Inv    |   1061

How do I find them?

**Comment by Jegelewicz** [comment]
> How do I find them?

![image](https://user-images.githubusercontent.com/5725767/222457334-a94f746d-fbac-47ad-9a19-1b9652a1ea46.png)

![image](https://user-images.githubusercontent.com/5725767/222457513-fbbe0c15-bf94-4aa9-b114-8b069df03615.png)

Saved Search - https://arctos.database.museum/search.cfm?guid_prefix=DMNS%3AInv&oidtype=Locality%20ID&oidnum=%25

**Comment by dustymc** [comment]
> why this isn't part of code table cleanup

I don't think the code table needs anything. This value has been carefully considered, it DOES NOT correspond with Arctos' idea of locality or event, so we put it where it is and said that in the documentation. There's nothing (that I can see) to do with code tables here, and that label is one I pay attention to - it exists to prevent what has become the most disruptive sort of messes.

There is potentially some misplaced data that the collections might wish to deal with, and I'm of course happy to help with that (I'd just need clear instructions). So I guess this is 'actionable' just not (yet) for me - I'm still not quite sure how to best file that.

**Comment by Jegelewicz** [comment]
OK - added data quality tag so that we can ask collections to make sure they are using the term as intended.

@mvzhuang
@ebraker 
@Nicole-Ridgwell-NMMNHS 
@babogan @aklompma 
@jldunnum

**Comment by ebraker** [comment]
Fixed UCM record

**Comment by dustymc** [comment]
>all records...same data

Never! Denormalization ...uhhhhh.....finds a way....

It does! No matter how small the user group, how careful the users, how much sense it makes on paper, *_consistently_* doing kinda anything the same way multiple places just doesn't seem very compatible with being human. 

```

select 
display_value,
locality.locality_name,
count(*) c
from
flat
left outer join coll_obj_other_id_num on flat.collection_object_id=coll_obj_other_id_num.collection_object_id and other_id_type='Locality ID'
left outer join locality on flat.locality_id=locality.locality_id and locality.locality_name is not null
where
flat.guid_prefix='DMNS:Inv'
group by 
display_value,
locality.locality_name;

             display_value              |              locality_name               |   c   
----------------------------------------+------------------------------------------+-------
 DMNS:Inv:Bugge Beach Ketchikan 1       | DMNS:Inv:Bugge Beach Ketchikan 1         |    12
 DMNS:Inv:Bunche Beach 2018             | Bunche Beach                             |    52
 DMNS:Inv:Fort DeSoto 1                 |                                          |    31
 DMNS:Inv:Kaelia Beach 2016             | Kaelia Beach, Kauai                      |    18
 DMNS:Inv:Kaelia Beach 2016             | Kaelia Beach, Kauai                      |   158
 DMNS:Inv: Kualoa Beach 2016            |                                          |    19
 DMNS:Inv: Old Kona Airport Beach 2016  | Old Kona Airport Beach, Kailua-Kona      |   120
 DMNS:Inv:Old Kona Airport Beach 2016   | Old Kona Airport Beach, Kailua-Kona      |     1
 DMNS:Inv: Poipu Beach Park 2016        |                                          |    83
 DMNS:Inv: Portlock Rd., Koko Head 2016 |                                          |    24
 DMNS:Inv: Salt Pond Park 2016          |                                          |    38
 DMNS:Inv:Second Chance sandbar 2016    |                                          |    12
 DMNS:Inv:Shell Key 1                   |                                          |    94
 DMNS:Inv: Sunset Beach 2016            |                                          |    60
 DMNS:Inv:Turtle (Laniakea) Beach 2016  |                                          |   216
 Fiesta Island 2018                     |                                          |    22
 Fort DeSoto North Beach 2018           |                                          |    52
 Sand Key Park 2016                     |                                          |    11
 Sand Key Park 2018                     |                                          |    39
                                        | Bahia                                    |     1
                                        | Bunche Beach                             |    60
                                        | California                               |     1
                                        | DMNS:Inv Amiga Island                    |   108
                                        | DMNS:Inv Australia                       |     1
                                        | DMNS:Inv Balicasag 150 meters/80 fathoms |    75
                                        | Dry Tortugas 110 feet depth              |     1
                                        | Dry Tortugas 280 feet depth              |    42
                                        | Kice Death Beach                         |   112
                                        | Machalilla                               |     1
                                        | marine Nha Trang with no depth           |    34
                                        | terrestrial Nha Trang                    |     5
                                        |                                          | 32147
(32 rows)

```

**Comment by sharpphyl** [comment]
> anything the same way multiple places 

When I created these Locality IDs, I was not aware that there was any other way to bring together specimens from one locality that could easily be found by anyone.  (In fact, I thought it was really cool that I could it.)

So, what do you want me to do?  Is [#5757](https://github.com/ArctosDB/arctos/issues/5757) the answer?

**Comment by sharpphyl** [comment]
I think https://github.com/ArctosDB/arctos/issues/5757 has answered this question.  

So I need to create a Locality name to replace all the Locality IDs and delete the Locality IDs.  Is there anyway to do that in bulk?

**Comment by sharpphyl** [comment]
@Jegelewicz  I'll play with it and probably come back to you for advice and options.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Based on looking at a sampling of ours, this data will probably be better suited to collecting event. I'll add this to my to do list.

**Comment by dustymc** [comment]
done/abandoned?
