### ISSUE TITLE
Code Table Clean up - Other identifier = BMNH: Bell Museum of Natural History

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5743]
As the BELL has now migrated to Arctos (Woo Hoo!), this particular identifier can go away. I have already removed all of the MSB:Bird usage of it and replaced that with same individual as relationships between the MSB:Bird and MMNH:Bird records. All that is left are two DMNH:Mamm records:

DMNH:Mamm | BMNH: Bell Museum of Natural History 
 -- | -- 
https://arctos.database.museum/guid/DMNS:Mamm:8194 | 1969 #31 
https://arctos.database.museum/guid/DMNS:Mamm:8195 | 1969 #32 

That I cannot figure out.

@acdoll @barke042 can you guys match these up?

**Comment by Jegelewicz** [comment]
For MSB records file used is attached.
[BELL Bird identifiers.xlsx](https://github.com/ArctosDB/arctos/files/10873997/BELL.Bird.identifiers.xlsx)

**Comment by acdoll** [comment]
Those are just numbers on the tags (see photos in specimen records). Without any knowledge of the Bell's numbering schema in the late 60's, I can't say for sure what they are. If I had to guess, they are more akin to collector numbers but for the institution - some temporary number for tracking material between the field and its eventual inclusion in the museums records; but I really have no idea. 
Looks like John suggested a possible link between DMNS:Mamm:8195 and a record at the Bell:
Might be Bell Museum Nat. Hist. #7893 (collected March 15, 1968)?

**Comment by dustymc** [comment]
Using issuedby for this avoids the need to guess (and the subsequent mess bad guesses lead to).

```
 guid_prefix | numrecs 
-------------+---------
 DMNS:Mamm   |       2

```

@acdoll can I just add issuedby=https://arctos.database.museum/agent/21253628 and change these to other identifier?

**Comment by acdoll** [comment]
That sounds reasonable to me.

**Comment by dustymc** [comment]
https://arctos.database.museum/search.cfm?id_issuedby=Bell%20Museum%20of%20Natural%20History

**Comment by acdoll** [comment]
That looks good - it captures the fact that this number came from the Bell and not us. Thanks
