### ISSUE TITLE
Code Table Request - 'type status' for adding observational records to publications

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#5744]
**Goal**
Add observational records as citations to publications.

**Context**
When adding citations to a publication, type status is required. The current values are all geared toward specimens, and there is no appropriate value for non-specimen observations. "Type status" is not the appropriate term for observations, but there is no other option.

**Table**
[citation_type_status](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcitation_type_status)

**Proposed Value**
'observation' or 'non-specimen observation' are obvious choices, but I'm open to other suggestions.

**Proposed Definition**
An organism that was observed but not collected. Use this for adding citations to publications based on observational data.

**Collection type**
N/A

**Available for Public View**
Yes

**Priority**
I assigned this High Priority because I'm trying to add >20K citations to a publication.
publication_id=10011816
records are from https://arctos.database.museum/project/10003947

**Comment by ccicero** [comment]
@Jegelewicz FYI, I obviously want to be part of the discussion but will be out of the country for the March code table meeting (gone 3/15-3/26).

**Comment by Jegelewicz** [comment]
@ccicero can you provide an example?

**Comment by dustymc** [comment]
@ccicero how are these different from voucher/referral?

I think you're trying to create a pigeonhole that doesn't and can't exist - there's nothing about 'observational' in these data, that should be evident from the methods section of the publication, nothing more is warranted. If I'm wrong then that distinction, whatever it might be, should be abundantly clear from the documentation.

**Comment by ccicero** [comment]
@Jegelewicz I put the publication and project ids into the issue. There are 20+K records for this project that are referenced in the publication (they provide the project link as the archive in the publication). 

@dustymc it's a question of how we're defining voucher. Voucher to me means that there is a physical specimen (or maybe with media) that can vouch for the ID. These are strictly bird observations from point counts (i.e., no voucher). 'referral' is for citing specimens in non-peer reviewed literature per the definition. This paper is peer-reviewed. None of the values in the code table really fit.

**Comment by ccicero** [comment]
Also, maybe we need to refine the definition of voucher in the code table to distinguish specimen/object vouchers. The current code table definition doesn't mention specimen but that is typically what a voucher is.

Current 'voucher' definition: "Cited in a peer-reviewed analysis with no specific type designation."
Proposed 'voucher' definition: "Preserved specimen cited in a peer-reviewed analysis that has no specific type designation." OR to make it broader for cultural collections: "Specimen or object housed in a collection that is cited in a peer-reviewed analysis and has no specific type designation." tagging @AJLinn for input.

From https://www.animalethics.org.au/policies-and-guidelines/wildlife-research/voucher-specimens:

Voucher specimen - a preserved specimen that serves as a verifiable and permanent record of wildlife as it preserves as much of the physical remains of an organism as possible. A voucher specimen should be in an accessible collection; however, even if it is not, it remains a voucher. Voucher specimens typically refer to taxidermied study skins, cleaned skeletal material including skulls, or spirit specimens, but may also include frozen samples such as tissue or blood. Spirit specimens include whole or partial animals fixed in a preservative (e.g. formalin or ethanol). Voucher specimens are extremely important as they preserve the characters by which species can be distinguished and serve as a basis of future study.

**Comment by dustymc** [comment]
>Voucher to me means

Arctos Authorities are not subjective, we have a real definition: [Cited in a peer-reviewed analysis with no specific type designation.](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcitation_type_status#voucher) We can change that, but that would be a (huge) matter of tracking down whatever needs split off into wherever we're splitting it - that would need to be a dedicated issue, it's not something that can happen incidentally to this request. (And this request probably can't happen without it - that would result in denormalization; a bunch of ways of saying the same thing.)

**Comment by ccicero** [comment]
There is a scientific definition of voucher that is more specific than in the definition. I don't think it would require a lot of tracking/moving of data as I think 'voucher' typically has been used to refer to specimens in that sense. Are there any 'Obs' records that are cited in publications as 'voucher'? If not, then I think we just need to tweak the definition for 'voucher' and add one for non-vouchered observations. Using 'voucher' for observations implies that there's something you can return to in order to check the ID, and that is not the case for pure point-count data.

**Comment by dustymc** [comment]
>any 'Obs' records that are cited in publications as 'voucher'?

Not sure what you mean, here are a couple guesses.

```
select 
	guid_prefix,count(*) from 
	collection
	inner join cataloged_item on collection.collection_id=cataloged_item.collection_id
	inner join citation on cataloged_item.collection_object_id=citation.collection_object_id
where
type_status='voucher' and cataloged_item_type ilike '%obs%'
group by guid_prefix;

 guid_prefix  | count 
--------------+-------
 KNWRObs:Bird |   515
 KNWRObs:Herb |   849
 KNWRObs:Mamm |     3
 MVZObs:Herp  |     2
 UAMObs:Ento  | 18881
 UAMObs:Mamm  |    22
 UCM:Obs      |    93
 UTEPObs:Herp |   111
(8 rows)

select 
	guid_prefix,count(*) from 
	collection
	inner join cataloged_item on collection.collection_id=cataloged_item.collection_id
	inner join citation on cataloged_item.collection_object_id=citation.collection_object_id
where
type_status='voucher' and guid_prefix ilike '%obs%'
group by guid_prefix;

 guid_prefix  | count 
--------------+-------
 KNWRObs:Bird |   515
 KNWRObs:Herb |   849
 KNWRObs:Mamm |     3
 MVZObs:Herp  |     2
 UAMObs:Ento  | 20007
 UAMObs:Mamm  |    22
 UCM:Obs      |    93
 UTEPObs:Herp |   111
```

(They almost line up! Yay us!!)

I'd expect a similar pattern on other ideas of 'Obs' - that's just not involved in type status (and clearly means lots of things to lots of people, so shouldn't/can't be).

Download stuff from GBIF, run some analysis. It makes no difference at all if there's a voucher, or was at the time of the publication. (Maybe it was lost but the collection hadn't noticed yet - how would I know?? I can't, so it doesn't matter!) Whatever might have been there wasn't used, it's just an analysis involving some data (which are hopefully stashed on dryad), everything should be clear from the publication. If we did try to pigeonhole that as some type I suspect it would result in various users doing various things - we'd just end up back at denormalization. I just can't wrap my head around any situation where this would result in some sort of consistent usage.

>voucher...implies 

We have to get past that idea; it's been causing a lot of problems lately. Voucher (and everything else in any authority table) means what we say it means, nothing else, and I'll always assume that users read the definitions before choosing to use it so constricting a meaning will always involve a migration. (Relaxing doesn't, but we never want to do that...) I just don't think any other viewpoint can possibly allow the collections to adequately assert what they have.

**Comment by campmlc** [comment]
I agree with @ccicero . In the broader museum and publication community, "voucher...implies" a physcial specimen that can be returned to for further study and extension. This concept is being broadly disseminated in many national and international discussions of the extended specimen, e.g. here: https://academic.oup.com/bioscience/article/72/10/978/6648186
We should ensure that whatever definition we use internally, it does not conflict with this concept.

**Comment by dustymc** [comment]
>whatever definition we use internally

We publish code tables so nothing's really "internal." That aside, https://github.com/ArctosDB/arctos/issues/5744#issuecomment-1452572968

**Comment by ccicero** [comment]
@dustymc I understand what you're saying about authority tables and definitions, but in this case 'voucher' does have a very specific meaning and has gained further importance in the concept of extended specimen. So I think it's confusing to use that term in other ways. The specimen detail page will show citation as 'voucher' and that means something specific to the user.

**Comment by ccicero** [comment]
That said, 'observation' has different meanings apparently to different Arctos users. @DerekSikes and @campmlc have been using it differently from what I think of as an 'observation' so that does seem to deserve more discussion.

**Comment by dustymc** [comment]
I see no technical problems with changing the term. "Non-taxonomic/nomenclatural mention in a peer-reviewed publication" is a bit of a mouthful, but that's the idea.

**Comment by mkoo** [comment]
just had a chat with Carla about this term 'voucher' -- Yes there's general usage and technical usage among museums but I think in this specific context of associating a record to a pub, 'voucher' is appropriate (as species and records can be 'vouchered' with media or primary source material, i.e. field notes or orgiinal data sheets). Most importantly it's available and ready for use to do its job of linking the observations with the publication. Just think of voucher in its broadest application and that field notes are the primary media. So go with longwinded definition (no harm in that) and get those published records linked!
my two cents

**Comment by campmlc** [comment]
I support that.
