### ISSUE TITLE
Code Table Clean up - Other identifier = California State University Long Beach

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5745]
As CSULB has now migrated to Arctos (Woo Hoo!), the [California State University Long Beach](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type#california_state_university_long_beach) identifier type can go away. Only MVZ:Mamm is involved. I have already added the appropriate same individual as identifiers to the CSULB records, but someone from MVZ needs to add them to the MVZ:Mamm records and unload the California State University Long Beach identifiers so that we can remove this term from the code table.

I have attached an Excel file that has both the unload and load in separate tabs.

[California Long Beach IDs.xlsx](https://github.com/ArctosDB/arctos/files/10874261/California.Long.Beach.IDs.xlsx)

@cjconroy @mkoo

**Comment by cjconroy** [comment]
Does this mean just going to each record and changing the CSULB other id num line from Self to Same Individual As?  I'm happy to do it, just need to know what to do.
If we remove the other ID part from the MVZ record, how do we have a reciprocal relationship?

**Comment by mkoo** [comment]
yes easy edit in Identifiers
I did the first one-- changed in the dropdown to CSULB:Mamm, removed the prefix, hit save and now we have the lovely link to their record in Arctos!
![Firefox_Screenshot_2023-03-02T18-21-02 068Z](https://user-images.githubusercontent.com/2523089/222518107-a6ac9267-a2f9-4cce-8fba-879897bf5f42.png)

Will you do the rest? if not, let me know -- thx!

**Comment by mkoo** [comment]
Also, thanks @Jegelewicz for sending the list!

**Comment by cjconroy** [comment]
Thanks for the example. I can do the rest.

**Comment by cjconroy** [comment]
OK, I've done with the rest what Michelle did with the first. Is there no need to use "same individual as", or is "self" still appropriate?

**Comment by Jegelewicz** [comment]
I made files for the load/unload in the attached Excel workbook - I would have just done it, but I don't have access.

**Comment by Jegelewicz** [comment]
You should use same individual as!

**Comment by cjconroy** [comment]
OK, I changed all to Same Individual As for the CSULB identifiers.

**Comment by Jegelewicz** [comment]
@dustymc can you confirm that the other identifier [California State University Long Beach](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type#california_state_university_long_beach) is no longer in use and remove it form the code table?

**Comment by dustymc** [comment]
arctosprod@arctos>> select guid_prefix,other_id_type,count(*) from
arctos-> coll_obj_other_id_num
arctos->     inner join cataloged_item on coll_obj_other_id_num.collection_object_id=cataloged_item.collection_object_id
arctos->     inner join collection on cataloged_item.collection_id=collection.collection_id
arctos-> where
arctos->     other_id_type in ('California State University Long Beach')
arctos->     group by guid_prefix,other_id_type order by guid_prefix,other_id_type
arctos-> ;
 guid_prefix | other_id_type | count 
-------------+---------------+-------
(0 rows)
