### ISSUE TITLE
planned outage - 2PM Central Friday 2022-03-03

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5746]
## Planned Outage
 - Date and time outage will begin: 2PM Central Friday 2022-03-03
 - Date and time outage is expected to end: 5PM Central Friday 2022-03-03
 - Reason for outage: update and backup
 - Expected behavior during and after the outage: Arctos will be unavailable 

## Communication before/during outage
- [x] Pin this issue
- [x] Banner updated @jegelewicz @mkoo
- [x] Email sent to AWG  
- [x] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [x] Unpin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [x] Email sent to AWG 
- [x] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by lin-fred** [comment]
I will make a tweet today and a reminder tomorrow

**Comment by ewommack** [comment]
I also sent a notice to the Slack channel.

**Comment by dustymc** [comment]
Arctos is back.

**Comment by ewommack** [comment]
Sorry I was in the fish.
