### ISSUE TITLE
Manage vs. Tools Directory

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5747]
From AWG today:

On main menu change Manage to Directory? Or something completely different?

**Comment by mkoo** [comment]
I vote **Directory**

**Comment by mkoo** [comment]
Can I elevate this to In Progress?!
Any other opinions?

**Comment by dustymc** [comment]
I also vote Directory.

**Comment by Jegelewicz** [comment]
Sigh - I hate to be this person, but Directory implies a telephone book. We call the thing Tools Directory and I know it is a violation of the "one word in the menu" rule, but we should either give the thing a one-word name "Tools" or use "Tools Directory" in the menu.

![image](https://user-images.githubusercontent.com/5725767/228038699-91e6f2d7-56ce-4451-bc2e-cc861df6b942.png)

**Comment by dustymc** [comment]
And "Tools" implies something beyond what many of these things do.

Map?

Registry?

Index?

**Comment by mkoo** [comment]
More

**Comment by mkoo** [comment]
ok not being facetious... The page is called "Tools Directory" so we could just call it that and not get all tied up in knots over whether we have 1 or 2 words in our menu links, yes? (can we get the OCD fairy to just grant a little allowance?)

**Comment by campmlc** [comment]
I agree with @Jegelewicz about Directory by itself. I don't see the difference between Tools and Tools Directory - they mean the same thing, so if that's the only choice I'd prefer Tools, or "More Tools".

**Comment by ewommack** [comment]
Directory sounds like where I would go to find the members of Arctos...but that I may be a western NAmerica use bias for word defintions.

I vote "tools directory" 

or "gizmo directory" :D

**Comment by dustymc** [comment]
```

				<div class="nav_menu_item">
					<a href="/directory.cfm">Tools Directory</a>
				</div>
```
