### ISSUE TITLE
manage directory needs a warning before deleting

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#5754]
Trying to edit an accession and received this error (same error from any Edit Accession link):

![Firefox_Screenshot_2023-03-03T19-38-23 585Z](https://user-images.githubusercontent.com/2523089/222811500-09e7b80a-5e9d-4d88-a448-b0da934a5ea1.png)
Not sure how to interpret this one....

**Comment by dustymc** [comment]
Someone has done something bad in the directory manager (the primary purpose of which remains to control how Arctos works).

You can...

<img width="130" alt="Screenshot 2023-03-03 at 11 44 32 AM" src="https://user-images.githubusercontent.com/5720791/222812320-b9c6d9ee-6317-47c1-99a1-1b1f067de826.png">

then fill in some blanks and...

<img width="1556" alt="Screenshot 2023-03-03 at 11 45 18 AM" src="https://user-images.githubusercontent.com/5720791/222812488-abdf5994-fbb8-4727-b397-f188d0ae7398.png">

There's a (necessary) cache, it should be back in about an hour.

Do we need a log or something, or is everyone comfortable calling that a glitch in the matrix?

**Comment by mkoo** [comment]
glitch it is.... I was editing yesterday in both the directory and in accessions but didnt notice anything amiss.... maybe in the manage directory, the save and delete buttons are dangerously close? Does the delete button have a warning attached to it (eg. are you sure you want to delete?) You usually have something like that...  thanks for restoring

**Comment by dustymc** [comment]
>dangerously close?

I can work with that.

Yea, the cache works both ways - you can oopsie stuff and not notice for an hour.
