### ISSUE TITLE
Add my box labels .cfr back to list of legacy reports?

### ISSUE THREAD

**Issue by jebrad** [ArctosDB/arctos#5755]
Hello - can someone please replace my box label report back into this list?
I did a search for some records, then selected Arctos Reporter, and at the bottom I followed this, as usual, because my labels are not in the new Reporter yet: 
"Click this to continue to the legacy reporter: http://reports.arctos.database.museum/reporter/report_printer.cfm?auth_key=9F7BD11A-2935-40C0-A1F04E5CC3EF1ADE&table_name=api%5Fjebrad%5F20230303010313906%5F199 "

Then I tried to print via the legacy Report Builder, but my report wasn't on the list. It was there the last time I tried but that was a few weeks ago.
So because I found no report, I followed "Manage Reports", and in the table my report was listed but it shows Last Access as "-(- days)" so it looks like it was somehow deleted?

I tried to create a new one today by Create Handler but I have no idea what to do, but it may look like I deleted it today.  I didn't!

Can someone put this .cfr file back in that list?
[uwbm_mammal_box.cfr.zip](https://github.com/ArctosDB/arctos/files/10885671/uwbm_mammal_box.cfr.zip)
I realize it's down for maintenance until tonight but this is not urgent for today.
Thanks.

**Comment by mkoo** [comment]
Yes, will do once back from maintenance mode

FYI, we grabbed a snapshot of all legacy reporter files here:
https://github.com/ArctosDB/arctos-assets/tree/master/templates2020-09-11

UWBM mamm is not on the list which makes me think it's been missing awhile but I will add to this archive as well for future reference and access.

**Comment by jebrad** [comment]
Thanks. We made that label and added it UWBM_mammal_box in September 2021, which was after that snapshot and might explain why it disappeared.
I started to ask about modifying this label and also finding a double-sided skin tag to copy, and I didn't take it anywhere after Dusty said that the label making was probably moving to something like mailmerge ("all labels need to be brought into the new system in some way").  https://github.com/ArctosDB/arctos/issues/5272#issue-1442966743 
I decided to stop working on our .cfr file labels and give someone else a chance to make something in the new system that I can copy.
My current need to get this .cfr back on the list of reports is to to print some draft labels so people can number some skeletons - so thanks for enabling that.  - Jeff

**Comment by mkoo** [comment]
Hi Jeff, I added it back to the list. I think you did as well, however they were missing the handler so I added one in that was enabled for the UW herp labels. I'm not sure if that will work for your mammal labels as I didnt try it.

So let us know if it's functional for you. We should get your label converted to the new system. So let us know when you're ready for that with a new issue

**Comment by jebrad** [comment]
I see my .cfr back on the list once I follow "Manage Reports" - and I can download the report (and edit or clone handler), but I cannot find a way to print it.  I used to print via the pull-down on Arctos Report Printer, and it's not in that pull-down.

**Comment by Jegelewicz** [comment]
@jebrad is this resolved now that you have the mail merge box label? If so, please close this. If not, let me know what else you need.

**Comment by jebrad** [comment]
Yep pleasure to close this.  Thank you!
