### ISSUE TITLE
UI review: Agents & Users tile

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#5756]
Agents & Users tile:

Currently has:
[Agent Deconcatenator](https://arctos.database.museum/DataServices/agent_splitter.cfm)
[Agent Name Splitter](https://arctos.database.museum/DataServices/agentNameSplitter.cfm)
[Bulkload Agents](https://arctos.database.museum/loaders/bulkload_agents.cfm)
[Find Duplicate Agents](https://arctos.database.museum/info/dupAgent.cfm)
[Manage Agents](https://arctos.database.museum/agents.cfm)
[Manage Operators](https://arctos.database.museum/AdminUsers.cfm)
[Pre-Bulkload Agents](https://arctos.database.museum/loaders/pre_bulkload_agents.cfm)

notes from Issues meetings included: redundant use of "Agent", mixing verbs and nouns
I've hijacked Kyndall's spreadsheet so now we have sheet for[ suggestions here](https://docs.google.com/spreadsheets/d/1jGSP4K4NQUcxeUTdKv-li8CqBhURhEoawJMbDTs8XEg/edit#gid=1335023224)

Option 1:

Agent Bulkloader  (keeping agent in name so it groups with pre-bulkloader)
Agent Pre-Bulkloader
Find Duplicates 
Manage Agents
Manage Operator
Name Deconcatenator
Name Splitter

--- 
ok, you guys, have at it. Feel free to add a new column of suggestion in the spreadsheet

**Comment by Jegelewicz** [comment]
Added my 2 cents - if we are going to make use of ":" and put the noun first - we should do this consistently across tiles?

Also, did we decide to stick with "search" or "find"?

**Comment by Jegelewicz** [comment]
Changes are out - let me know if anything is crazy.

**Comment by dustymc** [comment]
it's beautiful!
