### ISSUE TITLE
Enhancement - Allow search by Locality Name from the main search page

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5757]
> The Other ID Locality ID makes available with one click all records from that locality.  I know the same data is available if someone knows to click on the Specific Locality "i" link, then go down to Locality and click on Catalog Record Search, but I doubt many people would find that path easily.  
> 
If the Locality Name could be made to have the same "search" properties as the Locality ID, I'd have no problem eliminating the Locality ID from our 1,061 records as that is the reason we assigned them a Locality ID and were planning to do that to more records.
> 
> <img width="1534" alt="Locality ID" src="https://user-images.githubusercontent.com/15368365/223146793-b95d7415-e0ad-41d1-8653-e2b008b1c9a9.png">
> 
_Originally posted by @sharpphyl in https://github.com/ArctosDB/arctos/issues/5739#issuecomment-1456293637_

Is there any reason this field is left out of the search options?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I would greatly appreciate this.

**Comment by Jegelewicz** [comment]
![image](https://user-images.githubusercontent.com/5725767/223460943-df2e9646-0989-46a8-98a1-e88206d9b024.png)

Woo Hoo!

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Awesome, thanks!
