### ISSUE TITLE
Feature Request - search for attribute doesn't exist

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5759]
**Is your feature request related to a problem? Please describe.**

ref https://github.com/ArctosDB/arctos/issues/5688 - find records that don't have an 'examined' attribute, but probably useful for lots of other things

**Describe what you're trying to accomplish** 

Normalize!

**Describe the solution you'd like**

Ability to search for 'doesn't have any {attribute} data"

**Describe alternatives you've considered**

Negative attributes - ugh!!

**Additional context**

**Priority**

high-ish?

**Comment by dustymc** [comment]
@cjconroy (and others?) have various uses for this, it would be purely additive, no changes, going direct implementation

**Comment by cjconroy** [comment]
Thanks!  What would the format be?  Would you type "Null" into the box?

**Comment by ewommack** [comment]
I can see a number of us using this to search out blank spots in our attributes like @cjconroy is doing. Thanks for working on it both of you!

**Comment by cjconroy** [comment]
Has this been implemented yet? It would be super helpful. Thanks.

**Comment by dustymc** [comment]
value=NULL will work in next release.

I am ignoring encumbrances for that functionality on the theory that "isn't there" can't be encumbered.

The query is a bit convoluted, would be nice to find a way to rewrite the "guts builder" to support not exists joins in general.

**Comment by cjconroy** [comment]
Thanks!
