### ISSUE TITLE
Add a field for GitHub Issue to all code tables

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5760]
@dustymc has requested that we include the link to the appropriate GitHub issue for every new code table term or changes to a code table term. This is often overlooked and is not added in a consistent method. If this is to be a REQUIRED object for code table terms, then we should have a dedicated space for it that is REQUIRED to be completed. It would also be helpful if the link added would be clickable in the UI and take one directly to the GitHub issue without the need for adding html.

This would make it easy for everyone to follow the "policy" and also easy to find the GitHub issue where a given term was discussed. Suggesting that we tack it on to the description/definition is clearly not working.

**Comment by Jegelewicz** [comment]
https://github.com/ArctosDB/arctos/issues/5731#issuecomment-1458706841

**Comment by dustymc** [comment]
I don't think this can possibly do what I'm asking for. A term comes from one issue, is renamed but not redefined in another, is redefined (and perhaps split) in another, etc., etc., etc. All are about equally important in understanding why some value is (or isn't) used in some context. A single field can't do that. I don't think anything beyond https://github.com/ArctosDB/internal/issues/251 is necessary or useful.

**Comment by Jegelewicz** [comment]
This seems like an easy ask?

![image](https://github.com/ArctosDB/arctos/assets/5725767/7af2792c-6772-413b-b572-e53ca2b1d446)

Just add a column like we have here

![image](https://github.com/ArctosDB/arctos/assets/5725767/ed047655-46f0-4021-8db9-5c585dc5e6c7)

All code table requests are supposed to be accompanied by an issue and instead of jamming them into the term description, let them live in their own column in the code table.
