### ISSUE TITLE
mask coordinates encumbrance is masking whole records

### ISSUE THREAD

**Issue by amgunderson** [ArctosDB/arctos#5761]
The mask coordinates encumbrance action is masking whole records. I cannot find specimen records that should have only their coordinates masked. They do not show up in a record search but their url does produce a record page.
Try to find UAM:Mamm:142739 when not logged in. This is happening to UAM:ES records also.

**Comment by dustymc** [comment]
Both locality and event attribute evaluation were being too eager; should be fixed in next release.
