### ISSUE TITLE
error feedback

### ISSUE THREAD

**Issue by msbparasites** [ArctosDB/arctos#5762]
Thank you for contacting Arctos with your issue. You may delete this note before typing your message. To best address your message, please include enough information to re-create the problem if your message involves a bug report on the database. Webpage links, steps you took, error messages, and screenshots are helpful. We promise to respond. If you prefer an email, contact us at arctoscontact@googlegroups.com

I was entering and modifying parts in MSB HOST. But when I put anything in the parts remarks, and save I get the error below. If I delete what I typed for the new part I added, it then complains about a part remark entered a while ago, it was already there. So if I delete all part remarks, then it will save the additions/modifications.

If I add the part remarks I want to the Attribute subsection remarks, then it works. 

If that is where you want remarks, that is find, but then the part remarks box needs to be gone or renamed or a bug fixed?
Thank you, Sara

<html><body>
<div style="border:2px solid green; padding: 1em; margin: 1em; text-align: center;">
            Please <a target="_blank" class="external" href="https://github.com/ArctosDB/arctos/issues/new?assignees=&amp;labels=contact&amp;template=contact-arctos.md&amp;title=error feedback">contact us</a> if you need assistance in resolving this error. Include the ERROR_ID (below) <strong>as text</strong> and enough information for us to re-create the problem.
        </div>
        

ERROR_ID | DEBB7775-5291-42CC-82E6256F3ED5F71A
ERROR_TYPE | SQL
ERROR_MESSAGE | ERROR: new row for relation "coll_object_remark" violates check constraint "ck_coll_object_remarks_noprint"   Detail: Failing row contains (26890561, null, uninfected snails , null).
ERROR_DETAIL |  
ERROR_SQL | UPDATE coll_object_remark SET 	coll_object_remarks = 'uninfected snail  WHERE collection_object_id = 26890561

</div>
</body>
</html>Please [contact us](https://github.com/ArctosDB/arctos/issues/new?assignees=&labels=contact&template=contact-arctos.md&title=error%20feedback) if you need assistance in resolving this error. Include the ERROR_ID (below) as text and enough information for us to re-create the problem.
ERROR_ID 	DEBB7775-5291-42CC-82E6256F3ED5F71A
ERROR_TYPE 	SQL
ERROR_MESSAGE 	ERROR: new row for relation "coll_object_remark" violates check constraint "ck_coll_object_remarks_noprint" Detail: Failing row contains (26890561, null, uninfected snails , null).
ERROR_DETAIL 	
ERROR_SQL 	UPDATE coll_object_remark SET coll_object_remarks = 'uninfected snails ' WHERE collection_object_id = 26890561

request dump:
request
node_name	
string	arctos-2021
rdurl	
string	/editParts.cfm
uuid	
string	DEBB7775-5291-42CC-82E6256F3ED5F71A

exception dump:
Catch
Entries: 15
additional	
Struct (ordered)
SQL	
string	UPDATE coll_object_remark SET coll_object_remarks = 'uninfected snails ' WHERE collection_object_id = 26890561
DatabaseName	
string	PostgreSQL
DatabaseVersion	
string	12.2
DriverName	
string	PostgreSQL JDBC Driver
DriverVersion	
string	42.2.20
Datasource	
string	user_login
DataSource	
string	user_login
Detail	
string	
ErrorCode	
string	0
Extended_Info	
string	
ExtendedInfo	
string	
Message	
string	ERROR: new row for relation "coll_object_remark" violates check constraint "ck_coll_object_remarks_noprint" Detail: Failing row contains (26890561, null, uninfected snails , null).
NativeErrorCode	
number	0
queryError	
string	UPDATE coll_object_remark SET coll_object_remarks = 'uninfected snails ' WHERE collection_object_id = 26890561
Sql	
string	UPDATE coll_object_remark SET coll_object_remarks = 'uninfected snails ' WHERE collection_object_id = 26890561
SQLState	
string	23514
StackTrace	
string	lucee.runtime.exp.DatabaseException: ERROR: new row for relation "coll_object_remark" violates check constraint "ck_coll_object_remarks_noprint" Detail: Failing row contains (26890561, null, uninfected snails , null). at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553) at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285) at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323) at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481) at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401) at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164) at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:153) at lucee.runtime.type.util.QueryUtil.execute(QueryUtil.java:328) at lucee.runtime.type.QueryImpl.execute(QueryImpl.java:296) at lucee.runtime.type.QueryImpl.<init>(QueryImpl.java:235) at lucee.runtime.tag.Query.executeDatasoure(Query.java:1134) at lucee.runtime.tag.Query._doEndTag(Query.java:699) at lucee.runtime.tag.Query.doEndTag(Query.java:565) at editparts_cfm$cf$118.call(/editParts.cfm:519) at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:1015) at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:938) at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:219) at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:44) at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2482) at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2468) at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2439) at lucee.runtime.engine.Request.exe(Request.java:45) at lucee.runtime.engine.CFMLEngineImpl._service(CFMLEngineImpl.java:1198) at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:1144) at lucee.loader.engine.CFMLEngineWrapper.serviceCFML(CFMLEngineWrapper.java:97) at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:51) at javax.servlet.http.HttpServlet.service(HttpServlet.java:590) at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74) at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129) at org.cfmlprojects.regexpathinfofilter.RegexPathInfoFilter.doFilter(RegexPathInfoFilter.java:47) at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68) at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68) at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117) at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at runwar.Server$1.handleRequest(Server.java:510) at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52) at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:280) at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79) at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134) at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131) at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:260) at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79) at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100) at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387) at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852) at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35) at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019) at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558) at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449) at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280) at java.base/java.lang.Thread.run(Thread.java:829)
TagContext	
Array
1	
Struct
codePrintHTML	
string	517: coll_object_remarks = &lt;cfqueryparam value=&quot;#thiscoll_object_remarks#&quot; CFSQLType=&quot;CF_SQL_VARCHAR&quot;&gt;<br> 518: WHERE collection_object_id = &lt;cfqueryparam value=&quot;#thisPartId#&quot; CFSQLType=&quot;cf_sql_int&quot;&gt;<br> <b>519: &lt;/cfquery&gt;</b><br> 520: &lt;/cfif&gt;<br> 521: &lt;cfelse&gt;<br>
codePrintPlain	
string	517: coll_object_remarks = <cfqueryparam value="#thiscoll_object_remarks#" CFSQLType="CF_SQL_VARCHAR"> 518: WHERE collection_object_id = <cfqueryparam value="#thisPartId#" CFSQLType="cf_sql_int"> 519: </cfquery> 520: </cfif> 521: <cfelse>
column	
number	0
id	
string	??
line	
number	519
Raw_Trace	
string	editparts_cfm$cf$118.call(/editParts.cfm:519)
template	
string	/usr/local/webroot/editParts.cfm
type	
string	cfml
type	
string	database
where	
string

**Comment by Jegelewicz** [comment]
@msbparasites the key in the error is

ck_coll_object_remarks_noprint

there is a non-printing character or trailing space and later it says

`Failing row contains (26890561, null, uninfected snails , null).`

Note the space at the end of uninfected snails? Somehow when you copied and pasted it elsewhere, you didn't grab that space.

**Comment by msbparasites** [comment]
oh wow. I thought I had checked for that.... Ok, that worked GREAT! I tested it and put back in the remarks I wanted and it worked. Seems like it is picking up new and old errors.... Thank you for your time!
