### ISSUE TITLE
De-specimen add citation form

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5764]
https://arctos.database.museum/Citation.cfm needs de-specimening

@dustymc I am fairly certain I can make the changes to catalog record/cataloged item if you want me to just do this.

![image](https://user-images.githubusercontent.com/5725767/223765937-08814a57-504a-43c8-9646-00d0df298654.png)

![image](https://user-images.githubusercontent.com/5725767/223766198-6fe7f29c-0b98-4bcd-9f44-032716200bb0.png)

![image](https://user-images.githubusercontent.com/5725767/223767067-bcc5557c-f258-42bc-b340-44134b49f56d.png)

High priority because I would like to change this to match documentation.

**Comment by dustymc** [comment]
IIRC that page is mostly an old dialect of JS - you're welcome to make updates, but you really need access to the VMs, and you absolutely must debug anything you touch. I've got a sick kid and those can be rough on schedules, but I'm hoping to (1) be working on the CF side of things today, and (2) get a release out tonight.

**Comment by dustymc** [comment]
I have to rebuild a bunch of this page in support of the new identification structure, and I'm wondering how (or if) anyone uses this - I suspect it can just be deprecated, everyone adds citations along with identifications??

I'll do something or another soonish if I don't get any feedback, but I'd rather not invest in something that's not useful.

HELP!

**Comment by Jegelewicz** [comment]
I'm gonna ping people who might be using it.

@DerekSikes 
@ccicero 

Anyone else?

**Comment by AJLinn** [comment]
I use it! I only know how to add citations from here... no clue on how to do it with identifications!

**Comment by DerekSikes** [comment]
I never add identifications and citations together. I always add citations using this form for small numbers or bulkload citations for larger numbers

**Comment by Jegelewicz** [comment]
Well who knew! Glad I pinged people...
