### ISSUE TITLE
search numeric portion of identifiers (and prefix and suffix?)

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#5765]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
How do you search for a range of collector numbers when some collector numbers have something non-numeric?  I am trying to find erroneously high collector number for Louise Kellogg. Her catalog goes to 3413, but I know there are numbers in the 9000's in Arctos. But, no matter what range I search for I get this error. The problem seems to be a collector number that has some non-numeric stuff going on. Since I can only query for up to 5000 records, I can't get all her records to find the issues. 
I tried searching my own records and have the same issue with a collector number "2749A". 
What's the solution?
<img width="832" alt="Screenshot 2023-03-08 at 10 44 55 AM" src="https://user-images.githubusercontent.com/5749672/223824580-82ed2903-0a02-489c-bda8-d94e103b48c5.png">

**Comment by dustymc** [comment]
> What's the solution?

Lists. 

"Range" and "crazy mix of numbers and letters and maybe clown emojis" aren't generally compatible, but in a specific case you can probably get Excel-or-something to give you what you need, or given enough details I should be able to put something together.

> only query for up to 5000 records,

That's cost-based - turn some stuff off and/or request a cache expansion in https://github.com/ArctosDB/arctos/issues/5460.

**Comment by cjconroy** [comment]
I bet a lot of people have some suffixed collector numbers. I have a few as embryos. The trailing letter is in the suffix field, but gets combined with the number on the main detail page. So, I will NEVER be able to search for a range of my collector numbers? That doesn't sound great.

**Comment by cjconroy** [comment]
I really don't know the logistics here. I think a lot of work went into moving non-numeric stuff into prefixes and suffixes. Wasn't that done so that the middle numeric number would be more useful?
Its also weird that the search fails even when the suffixed number is outside the range of the query. Could that be part of the solution?

**Comment by dustymc** [comment]
>logistics

Do you need to search the prefix and suffix as components of the 'display', or is the numeric portion (which can deal with ranges) a sufficient (when combined with all other options, of course) addition?

>Wasn't that done so that the middle numeric number would be more useful?

Yes, I'm just exposing those data (in a sustainable and obvious manner - there was some super wonky and overly specialized thing that hopefully died with the old UI), ideally with some more guidance

>fails even when the suffixed number is outside the range of the query

Any nonnumeric in the type will kill range searches - the criteria are all combined by the optimizer which can't know that your other criteria might avoid whatever can't be cast to sequential-capable types.

**Comment by cjconroy** [comment]
My current scenario is trying to track down erroneously large collector numbers. That does not generally involve any prefixes or suffixes. So I can do a search like 3413-10000.
If this is not possible, I will just find another way. Like downloading the entire list from that collector, or by year span, etc.

**Comment by cjconroy** [comment]
Thanks!
