### ISSUE TITLE
Arctos Down - Can't save changes to agents

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5768]
Please complete to the best of your ability.

## Unplanned Outage
 - Date and time (**please add time zone from which you are reporting**) outage discovered: 2023-03-08 2:40 PM MST
 - Describe the outage (Arctos down or only some part not working?): unable to save changes to agents

## Planned Outage
 - Date and time outage will begin:
 - Date and time outage is expected to end:
 - Reason for outage:
 - Expected behavior during and after the outage:

## Communication before/during outage
- [x] Pin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG  
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [x] Unpin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by mkoo** [comment]
I think it's down completely so not just agents need saving!
 @dustymc poke please

**Comment by mkoo** [comment]
back online now!
