### ISSUE TITLE
Bulkload parts to containers tool?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#5769]
I thought we had this tool, which used container IDs from download parts. But I can't find it? Does it still exist? All I see is the old Parts to Containers tool which only allows one record to be edited at a time.

**Comment by campmlc** [comment]
I found it - but it is confusingly located under Records, instead of with the Parts to Containers tool under Barcodes and Containers. Can we get the link in both places?

**Comment by dustymc** [comment]
>both places?

Please, in the name of all that's holy (and/or good design, and/or general usability), do not replicate. That ultimately never makes things easier to find, always makes everything else (and itself) harder to find. Clutter is bad.

I don't really care how things get categorized, but I will suggest that we do something systematic. Having found one bulkloader, a user should be able to see enough pattern to find the rest.

**Comment by campmlc** [comment]
OK, then I would like to request that the Parts to Containers (Bulk) tool
get moved to the Barcodes and Containers Table in Manage, so it sits with
its partner single record at a time Parts to Container tool.

**Comment by Jegelewicz** [comment]
I added this request to the[ issue about this tile](https://github.com/ArctosDB/arctos/issues/5749) - so I am closing it
