### ISSUE TITLE
New Other Identifer Functionality and Code Table Cleanup

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5771]
Due to new functionality in Arctos, the Code Table Admins are embarking upon a clean up of the [Other Identifiers code table](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type). Other identifiers that indicate they are issued by a specific person or organization that do not have an associated base url will be converted to the identifier type [other identifier](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type#other_identifier) and the issuing agent will be added in the newly available issued by field. Each of the affected identifiers will be evaluated in a GitHub Issue where the collections making use of the identifier can weigh in on whether other identifier is the appropriate generic identifier type and if the issuing agent is appropriate. Your GitHub username will be tagged in issues affecting your collection(s). Identifier issues that receive no feedback will be acted upon as proposed if there is no opposition two weeks after being opened.

Note that this new functionality can be applied to collector and preparator numbers!

![image](https://user-images.githubusercontent.com/5725767/224099194-2d1ad447-e3e2-4ba6-beb6-bb93b9de6e56.png)

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/arctos/issues/5770#issuecomment-1462415620_

**Comment by Jegelewicz** [comment]
Announcement added to banner.

**Comment by catherpes** [comment]
What does Base URL mean? ABQ zoo has a URL, and I assume other zoos do as well. Not understanding this. 

A single institution/person can issue more than one type of number (I can issue preparator and collector numbers If I understand this logic correctly).

**Comment by dustymc** [comment]
BaseURL is what has traditionally been prepended to partial identifiers to make them whole/unique/functional.

``http://www.ncbi.nlm.nih.gov/nuccore/`` (from https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type#genbank) + ``ON148013`` ==> https://www.ncbi.nlm.nih.gov/nuccore/ON148013, an actual identifier. 

ABQ zoo's URL probably can't make sense of an identifier, so it's not useful as a base. (But in this model it's a good agent address and the IDs issued by them link to their agent, from which you can click the url, look around for contacts, and maybe find someone who'll tell you why 12345 is associated with some meerkat - even flaky associations are handled better.)

>I can issue preparator and collector numbers If I understand this logic correctly

Yep, and if they're in different places then perhaps you should (see ~ https://github.com/ArctosDB/arctos/issues/5715#issuecomment-1462697526).

If you're not that into pigeonholes and just maintain one notebook-or-whatever, then perhaps the type isn't so important, and what really matters is you (which under this model is an unambiguous link, I don't have to go digging around looking for strings that might handwave in your general direction or etc.) - see also ~ https://github.com/ArctosDB/arctos/issues/4604#issuecomment-1461270984

**Comment by ewommack** [comment]
Will this affect the UWYMV Tissue and the UWYMV Historia Catalog Vertebrate Identifiers? 
Those are specific Identifiers that the museum uses that are different than catalog number and prep numbers (that need to be searched and discoverable, or is a shared catalog with multiple rotating users where the abbreviation of the name (HCV) does not correspond to one user. I am a preperator in the HCV catalog, but I also have my own catalog. I would not say and HCV # is my catalog or prep #. We also really need to be able to search by the Tissue Numbers specifically, and display them in the catalog records.

They're both internal to the museum so you could say they have the UWYMV base URL, but the museum is already in Arctos. Does that meet the requirements you are looking for?

**Comment by wellerjes** [comment]
When will the new fields for identifiers appear in the data entry form? It currently only allows for ID References, ID Type, and ID Value.

Thanks!

**Comment by dustymc** [comment]
>UWYMV Tissue and the UWYMV Historia Catalog Vertebrate

Somewhat up to you/The Community, but I think there should be some sort of compelling functional use case.

>both set-up for display

That's maybe compelling-enough for the first pass. I think the agent is capable of serving in that role as well, but that would be some (minor, I think) development (and maybe more agents, more below).

>searched and discoverable

I'm increasingly certain that the agent attachment completely changes what that means, all for the better.

>display them in the catalog records.

I'm certainly this is also better (=less ambiguous).

>base URL

I'm hoping that is less-used before this is all done, but we shall see....

>museum is already in Arctos

And 'divisions of' could be easily created. That's one of the things that the agent-issuer approach just does much better - it can easily and explicitly handle complex relationships (eg between institutions, departments, "subdepartments," whatever).

>data entry form?

Someone tell me, please! (And soon!)

https://github.com/ArctosDB/arctos/issues/4604#issuecomment-1461116416

https://github.com/ArctosDB/arctos/issues/5193

**Comment by ewommack** [comment]
> Someone tell me, please! (And soon!)

Please do not get rid of UWYMV Frozen Tissue Collection or UWYMV Historia Catalog Vertebrate for now.

I'm not sure this new system will work for what they were set-up for as Identifiers, and we need to use them both regularly.

**Comment by dustymc** [comment]
There will be issues for each identifier type.

I meant, I need more information about data entry - https://github.com/ArctosDB/arctos/issues/5193 / https://github.com/ArctosDB/arctos/issues/5331 needs to happen (possibly as early as next week), we've agreed to NOT change anything for some years after that is implemented, and I don't know what to do about identifiers.

**Comment by dustymc** [comment]
From @Jegelewicz in https://github.com/ArctosDB/arctos/issues/5880#issuecomment-1466914356:

 The line underlined in green will be added and line underlined in red will go away.

![image](https://user-images.githubusercontent.com/5725767/224825336-26292218-a012-4cbe-be95-5cb6c854e1ad.png)

**Comment by ewommack** [comment]
That really does not help. I know you guys think it does, but I think we really needed to have a broader conversation at a AWG and AWG Issues meeting about this.

**Comment by amgunderson** [comment]
I am oppose to this in principle. This removes the option of using and creating identifiers from the collection managers and curators. Arctos users should be able to use identifiers as they see fit to manage their collection data, as has always been the case. If you do not like an identifier for your collection, do not use it.

**Comment by Jegelewicz** [comment]
A brief note about why we are doing this.

The current other identifier code table includes over 540 unique values. This makes customizing search results almost impossible if they are all listed as options for columns. In addition, it makes selecting an identifier difficult during search or data entry as one may need to peruse this long list to find what one needs. As Arctos grows, the only thing that can happen is that this code table will grow as well and at some point it is going to be unmanageable with hidden duplicates everywhere. A smaller selection of generic types, accompanied by the most specific issuing agent possible will reduce growth in this code table and create richer data about the identifiers.

See https://github.com/ArctosDB/arctos/discussions/5707#discussioncomment-5306608 for an example of how this process has made the related data move one step closer to Arctos and provided a more succinct identifier rather than a generic one (a specific collection vs. an entire museum)

Please remember that agents can be [organizations](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctagent_type#organization) and that is very loosely defined. Collections are organizations and may be divisions of museums, institutions or even other collections! GBIF and GRSciColl recognize collections and we should too. Creating an appropriately specific agent should not be a problem.

This is a new way of thinking about identifiers. It requires documentation and use to find flaws, however, any changes made are just moving information from the identifier to the agent. A specific agent was created for each identifier being proposed for change, so for now, nothing is happening except that once an issuing agent is assigned, you have the ability to embellish that agent. Add links to websites or GRSciColl or GBIF collection or to people who work in them. Create a rich web of information about your identifiers by telling the world who created them.

**Comment by DerekSikes** [comment]
Aren - are you opposed because you have operators that you don't give permissions to create agents? Because anyone who can create agents can create new identifier types (as I understand it).

**Comment by amgunderson** [comment]
No, I am opposed because using or creating identifiers should be done at the discretion of collection managers and curators. That ability should not be overruled or removed by Arctos.

**Comment by DerekSikes** [comment]
Aren - I'm sure that collection managers and curators will still have the ability to create identifiers as they see fit (Dusty/Teresa- correct me if I'm wrong). The advantage is that one can annotate (if desired) the issuing agent of the identifier.

I suspect that making new identifier types will become even faster & easier - didn't one have to ask for a code table update if one wanted to add a new identifier type in the past? Now (Dusty/Teresa- correct me if I'm wrong) one should be able to make a new type by simply creating the agent record for that type.

Also, when searching for identifiers now, one has to drop down a list of 500+ types and eyeball search that list to find the one you want. The new search functionality should (hopefully) allow one to type a partial string like "national park" and hit tab and you'll get a list of the 2 or 3 types that match that string, click the one you want, and bob's your uncle.

**Comment by amgunderson** [comment]
Can you limit the Identifier Type list to only those that apply to collections each user has access to? That is how the GUID list is filtered.

**Comment by campmlc** [comment]
@derek is correct - this tool will allow us to create identifiers using agents without having to change the code table. If I understand correctly, this is really just creating a new way of viewing identifiers with the same functionality, and ability to add akas and urls - that we have with agents. They will just be using the same table.
I am fully on board with adding the "issued by"ID metadata to link the identifier with the associated agent. That can happen regardless of what ID type is used.
 I am less enthusiastic about the idea of turning ALL identifiers into agents. We need some identifier types to be hard coded as ID types - see and comment on the current list at https://github.com/ArctosDB/arctos/discussions/5707#discussioncomment-5326636.  
Perhaps we can compromise by adding the new identifiers/agents but keeping the old as well for now so everyone can see what this new functionality does and does not do.

**Comment by amgunderson** [comment]
How will this change data entry? We assign ID type at the entry stage. Looks like we will need to assign ID type "other identifier" and then choose an "Issued By" agent from the agents code table - super confusing, likely to be confused with "assigned by" and will result in NPS numbers being listed as issued by collectors and other similar problems.

**Comment by amgunderson** [comment]
Creating an Issued By agent is not the same as creating an Identifier Type. All these numbers will become other identifiers and will only be filtered through a search of Issued By agents. It may be easier to create Issued By agents than it is to create an Identifier Type but that doesn't make any sense in the real world to force types of ID numbers to become Issued By agent numbers. When we need a new type of identification number we don't want a new agent, we need a number TYPE because we deal with types of numbers. You want us to start thinking that catalog numbers aren't catalog numbers, they are identifiers issued by a code table agent entity. You are in the matrix.

Say you have an accession of NPS specimens (they have an NPS accession number that is the same for all specimens and each specimen has a unique NPS catalog number) you need to enter into Arctos and you have to train someone how to do that...Instead of telling me an NPS accession number is an NPS accession number, you are telling me an NPS accession number is an other identifier issued by an agent called "United States National Park Service Accession" and the NPS catalog number is an other identifier issued by an agent called "United States National Park Service Catalog". Again, this only makes sense if you think of Arctos code as reality rather than specimen/object data as real.

**Comment by campmlc** [comment]
I agree and support keeping identifier type "catalog" or " catalog number"
and adding "accession" as an ID type. The alternative proposal as I now
understand it was to make " National Park Service Catalog" the agent name -
or really, save it in the agent table so it can have all the associated
metadata and linkages. I think despite the functionality of that approach
it's going to be a hard sell to convince everyone that their ID types can
be managed along with agents. Accepting that an ID type is issued by an
agent is much easier to grasp. But we then need to decide on the set of ID
types that will remain in the code table.

**Comment by amgunderson** [comment]
What you have done already to identifiers is now ruining specimen labels. Please pause this change. I propose it be abandoned completely.

**Comment by catherpes** [comment]
all that stuff between the brackets in the identifiers column is printing on the label??
