### ISSUE TITLE
Media tags not aligning to photos

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#5791]
The boxes to outline various tagged items in media images are no longer lining up correctly:
![image](https://user-images.githubusercontent.com/12507297/224145924-68a6fc75-a6c1-4194-922a-aaf61147981a.png)
Also: note how the footer doesn't appear at the bottom of the page, but rather at the top and behind the photo.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/5685
