### ISSUE TITLE
FORMATTED_SCIENTIFIC_NAME in flat

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5794]
How is FORMATTED_SCIENTIFIC_NAME in flat constructed?

We are still grappling with #3609 and looking for a solution so that collections making use of WoRMS (via Arctos) can get properly formed names. As more collections use this taxonomy source, we need to make it fully functional. Has implications for [potential new collections](https://github.com/ArctosDB/new-collections/issues/565) as well.

**Comment by dustymc** [comment]
>How is FORMATTED_SCIENTIFIC_NAME in flat constructed?

https://github.com/ArctosDB/PG_DDL/blob/master/function/flat_components/getFlatTaxonomy.sql, but the important point is that it is constructed, and the take-home from the issues that you just killed for some reason is that I'm not very good at guessing how various Arctos users might want things constructed. I still see two ways forward for both of these issues:

* users of classifications select or provide something(s), somehow, or
* I use a ridiculous amount of CPU doing random things that maybe-sorta-work for some limited subset of everybody.

And even that's probably incompatible with https://github.com/ArctosDB/arctos/discussions/4965 and does nothing for https://github.com/ArctosDB/arctos/issues/3498.

Maybe this is just one of those things that can't usefully be scrunched into strings, and we should be considering what we do about that.

What precisely do you think the AWG can bring to this conversation? This looks to me like a horrible candidate for that, and a really great candidate for some focus group.

**Comment by Jegelewicz** [comment]
> really great candidate for some focus group.

Taxonomy Committee has discussed for over a year - I think they have given all they have to give.

@lin-fred @sharpphyl @genevieve-anderegg

**Comment by Jegelewicz** [comment]
I am closing this as a duplicate of a bunch of other issues and covered by the classification visible in the identification dropdown on the record pages.
