### ISSUE TITLE
Feature Request - Add Attribute to Specimen Add Part

### ISSUE THREAD

**Issue by KyndallH** [ArctosDB/arctos#5811]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
Add Specimen Parts --> need to be able to add attributes (in particular, preservation).

**From Specimen Page:**

<img width="201" alt="Screen Shot 2023-03-09 at 3 12 23 PM" src="https://user-images.githubusercontent.com/16887896/224189933-fea8fb07-6966-4b39-b8f9-559fd35f0336.png">

<img width="381" alt="Screen Shot 2023-03-09 at 3 12 28 PM" src="https://user-images.githubusercontent.com/16887896/224189941-6b4303aa-e12b-43cd-9f84-b30caa1eb3d1.png">

**From Add Parts to Container Page:**

<img width="343" alt="Screen Shot 2023-03-09 at 3 12 59 PM" src="https://user-images.githubusercontent.com/16887896/224190031-e8612c28-9122-4265-9561-6778de88c4d2.png">

<img width="1265" alt="Screen Shot 2023-03-09 at 3 13 21 PM" src="https://user-images.githubusercontent.com/16887896/224190039-4d4a69c3-708c-4b58-b86e-32569a136921.png">

<img width="645" alt="Screen Shot 2023-03-09 at 3 13 25 PM" src="https://user-images.githubusercontent.com/16887896/224190050-ffc3a29b-20ad-4982-a538-0e3edd82c6d4.png">

**Describe what you're trying to accomplish** 
When I create a part via the two methods above, I want to add attributes right then and there.

**Describe the solution you'd like**
Add attribute to the create part field. 

**Describe alternatives you've considered**
1. Not adding attributes like preservation type.

2. Clicking a lot of buttons and wasting my time adding attributes manually to each part I create. (Mostly, I do 1 of not adding attribute).

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by campmlc** [comment]
This would be super helpful.

**Comment by Jegelewicz** [comment]
Agree

**Comment by campmlc** [comment]
This needs to extend to the Clone function in Edit catalog record parts. Right now, Clone does not include the attributes, which results in multiple extra steps and effort, and risk of error. 
Can we tackle some of these issues, please?

**Comment by dustymc** [comment]
I'll go next task - I know how to do this - but

1. please help prioritize, and
2. please help link any related issues if there are any
3. I think this probably involves clean-slate rebuilding the edit parts form, and input/requests/whatever on that greatly appreciated.

cloning should be its own issue (with details, please) - https://github.com/ArctosDB/arctos/issues/5193 is going to completely reshape that landscape (the parts of it that involve the bulkloader)

**Comment by Jegelewicz** [comment]
> clean-slate rebuilding the edit parts form,

I will look to see if there is an issue, but I remember someone saying they don't like the need to select "manage attributes" - can they just be there to be managed whenever you edit parts?

**Comment by dustymc** [comment]
That's why it needs a full rebuild.

**Comment by Jegelewicz** [comment]
Yeah - and I could not find an issue for that, but I feel like it was requested in some meeting....

**Comment by campmlc** [comment]
It would be great to be able to enter, view, and manage part attributes
from the same screen as we enter and edit parts. The current method of
adding part attributes is very cumbersome as you have to click multiple
times, starting with just selecting the manage attributes tab.And then when
you are done you can't see whether the attributes were correctly added to
parts unless you exit the part attributes tab and go back to parts, and
then back again if something has to be changed.

**Comment by KyndallH** [comment]
I'm commenting to keep this fresh and hopefully moving forward....

**Comment by campmlc** [comment]
This is high priority for object tracking. We need to keep the older tools in sync with the newer tools and usages.

**Comment by KyndallH** [comment]
High-priority for me too. And I don't put high priority on most of my stuff if that is any indication of how I feel about this.

**Comment by dustymc** [comment]
I've added some attributes to guid-page parts for next release, I think that's about all I can do without a major rebuild, and I can't do that before https://github.com/ArctosDB/arctos/issues/4707.

If https://arctos-test.tacc.utexas.edu/part2container.cfm is to survive this needs a complete rebuild - it is using some old stuff that's not a great foundation. But, I don't quite understand why it still exists, or what it does that's not better done from edit parts. Can it just go away, or can edit parts be rebuilt to do whatever's lacking, or  ???
