### ISSUE TITLE
Feature Request - ban barcodes with commas & have Arctos ignore commas at the end of barcodes in certain fields

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#5812]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

There are at least two object-tracking parent container fields on forms that will fail if a comma is in the field.

These are: catalog record search->manage identifications->Move parts to container barcode field

If I scan a parent barcode into that field, and my scanner is set to deliver a comma at the end of the scan, I have to delete that comma from that field for it to work.

Also: bulk move container csv paste mode (aka https://arctos.database.museum/batchScan.cfm?mode=csv ) 

parent barcode field also fails if a comma is present.

For those who use their scanners set on 'terminate with commas' (which is how mine is set because I am always scanning long strings of barcodes into the catalog record search form barcode field to find & edit records) it would be great if these two 'parent barcode' fields could ignore commas if they are present so users don't have to delete them.

BUT in order for that to be safe, we have to ensure that no one has any barcodes that have commas in them. Apparently no one does now, so we should prevent anyone from using barcodes that have commas in them - this would be good for not only this issue, but such barcodes would never be useful for any of the csv barcode list fields and are a bad idea in general so they should be banned.

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.
medium

**Comment by campmlc** [comment]
I certainly agree there should not be commas allowed within a barcode.

**Comment by dustymc** [comment]
I went the other way. Next release, barcodes will be allowed to contain only ``'[^a-zA-Z0-9\ \-\.\_]'``

* upper and lowercase letters
* numbers
* dash ``-``
* underbar ``_`` 
* spaces (because legacy, but they break everything and this is a horrible idea)
* dot ``.`` (because  K.1049 and similar exist, this also seems like a terrible idea)

The attempt to pretend commas are tabs will be https://github.com/ArctosDB/arctos/issues/1689 (and I'm still not sure that's a good idea....)

**Comment by DerekSikes** [comment]
Related to this issue is the trailing space problem. Arctos seems to be the only thing online that can't tell these are the same thing: Arctos. and Arctos . Can we fix that?

**Comment by dustymc** [comment]
>Related

Nope, but you can reopen https://github.com/ArctosDB/arctos/issues/2678

>Can we fix that?

We did....

**Comment by Jegelewicz** [comment]
> spaces (because legacy, but they break everything and this is a horrible idea)
> dot . (because K.1049 and similar exist, this also seems like a terrible idea)

How many of these are in use and can we get them changed? If someone has printed barcodes, I guess not....

**Comment by Jegelewicz** [comment]
Can we at least disallow them in the barcode series reserve tool? Then maybe we can get rid of them by attrition?
