### ISSUE TITLE
dropdown values should match column names

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ArctosDB/arctos#582]
```
In SpecimenResults.cfm, the values for "Order by" and "then order by," should 
(as far as possible) match the names of the columns in the form. The 
"scientific_name" versus "Identification" is the example that confused one user.

```

Original issue reported on code.google.com by `gordon.jarrell` on 3 Sep 2012 at 6:53

**Comment by dustymc** [comment]
This is largely implemented via Field-Level Documentation, which I'm slowly sprinkling to forms which can use it. File a new Issue for specific requests or to prioritize the sprinkling.
