### ISSUE TITLE
other ID search and results

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5830]
I am fine with this, but I do have a question about  the interface. I customized the search interface to show 'any identifier' but I don't see it on the UI. And how would that show in results? I have collector and preparator selected, is it under something else? What are the fields we need to show these records in both the search and results UI?

Here's what my screen looks like:

![image](https://user-images.githubusercontent.com/967275/224387157-7f9231d6-760d-40d6-ad17-e8bc32b44b5a.png)

_Originally posted by @ccicero in https://github.com/ArctosDB/arctos/issues/5825#issuecomment-1464156283_

**Comment by dustymc** [comment]
@ccicero bringing this out here.

For search: Turn on "Identifier Search Details"

<img width="941" alt="Screenshot 2023-03-10 at 10 15 48 AM" src="https://user-images.githubusercontent.com/5720791/224392758-29954016-6396-4f9e-9377-4ad319b1a1a2.png">

For results: I don't know yet (other than https://github.com/ArctosDB/arctos/issues/4604#issuecomment-1461240190 - the messy string we have now doesn't look sufficient). I am up for whatever, but I think this is probably a job for JSON.

There are a few types in FLAT (and we can add more see https://github.com/ArctosDB/arctos/issues/5460) but that probable needs discussed as well - I think the issuer should probably be part of the value??

For record details: Depending on the view, you should see something like:

<img width="905" alt="Screenshot 2023-03-10 at 10 20 39 AM" src="https://user-images.githubusercontent.com/5720791/224393544-3c655ac9-2a94-4352-a36b-20f05007200c.png">

**Comment by ccicero** [comment]
Thanks @dustymc re: search details!

Detail page looks good, but we do need to be able to show (through customize) these in results.

**Comment by dustymc** [comment]
The coarsest option will be othercatalognumbers (=all record identifiers other than guid) in some format (still probably JSON but up for ideas) and that will happen no matter where we end up with the individual identifiers.

Some (possibly all if cleanup is sufficiently supported) of these will certainly end up as results columns, how that works needs sorted out. I think we probably need issuer in that as well - eg ``Carla Cicero CC123``  (and maybe even a href on the agent-bit??) but - well, you tell me. 

And I can SQL eg you into your collector numbers if you'll tell me how to find them - having some big chunk of real data would make this easier to understand.
