### ISSUE TITLE
[external CONTACT] container evironment parameter

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#5846]
@dustymc There is a code table for [container environment parameter](https://arctos.database.museum/info/ctDocumentation.cfm?table=CTCONTAINER_ENV_PARAMETER) but it's not clear to me or @mkoo where you can add those values to a container. Can you provide screenshots on where you would e.g., add 'ethanol concentration' or examples of records that have something about container environment parameters? Thanks.

**Comment by dustymc** [comment]
edit container

<img width="851" alt="Screenshot 2023-03-10 at 2 20 14 PM" src="https://user-images.githubusercontent.com/5720791/224438923-8c4bbadc-13c6-4c43-8ef2-a2ae33fb30ff.png">

or Bulkload Container Environment

**Comment by ccicero** [comment]
Where do you go to get to Container Environment? That's what's not clear to me. I see how you bulkload container environment, but where do you go to create container environment on a specific record?

**Comment by dustymc** [comment]
https://arctos.database.museum/directory.cfm

Find Containers - https://arctos.database.museum/findContainer.cfm

Find something

<img width="153" alt="Screenshot 2023-03-10 at 2 42 20 PM" src="https://user-images.githubusercontent.com/5720791/224441846-160bbd3b-b2c8-406d-945d-8a7787add945.png">

Select one
<img width="182" alt="Screenshot 2023-03-10 at 2 42 35 PM" src="https://user-images.githubusercontent.com/5720791/224441887-b8c5d9d9-b3a6-4b9f-9ad0-74aec96383fb.png">

edit
<img width="169" alt="Screenshot 2023-03-10 at 2 42 42 PM" src="https://user-images.githubusercontent.com/5720791/224441895-360b4f1c-6368-4412-bcae-5b2cc3e42569.png">

**Comment by ccicero** [comment]
cool, thanks!
