### ISSUE TITLE
Feature Request - edit taxonomy classifications

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#5857]
I need to change all our taxonomy records that have family = Silphidae to family = Staphylinidae and change all the Silphid subfamilies to tribes

I would think  I could this:

1) search taxonomy for all such records, eg taxon term = Silphidae

this finds 238 taxon names

2) but how do I download the Arctos classification for all these as csv? There is a statement at the top that says 

A taxonomy download is available - Get Details. 

but those details bring one to this: https://github.com/ArctosDB/arctos/issues/3205#issuecomment-758809795

I want a csv that I can open, edit, and upload to fix all these problems. 

This page: https://handbook.arctosdb.org/how_to/How-to-manage-taxonomic-classifications.html

has a section on Common Problems

but there is no mention of this very common problem in entomology in which large numbers of taxa need a higher taxon changed (eg let's say a family of 1000 species is changed, how do we do that)

I've poked around with https://arctos.database.museum/tools/hierarchyEditor.cfm

which never approached anything near an intuitive enough tool for me to figure out. I tried to create a source 'Silphidae' hoping I could then download csv like I want above, but 'download CSV' give me an empty file with just headers. I tried export for classification loader and got this:

Export initiated. You'll find data in the classification bulkloader with status like 'hierarchy_export_{name}_{date}' 

But when I go to the classification bulkloader review and load there is nothing there.

As stated above - an intuitive solution is:
1) search taxonomy for records you want to edit
2) download link to get csv of those records that you can edit offline
3) bulkloader to upload the fixed classification (presumably this exists already)

Help!

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.
high

**Comment by dustymc** [comment]
<img width="950" alt="Screenshot 2023-03-10 at 3 35 30 PM" src="https://user-images.githubusercontent.com/5720791/224448187-644b323d-f5de-4cac-9d13-d890599d22f3.png">


>hierarchyEditor

Yea, I don't really recommend that - but, it works and some collections manage with it, but it's easy to manage smaller batches in Excel-or-whatever, the classification loader is really good, and the structure of Arctos supports that in several ways. I suspect that's the easiest/most effective approach (excepting https://github.com/ArctosDB/arctos/discussions/4965, if GN happens to have something you like) for most situations.

I'd absolutely not put any work into any of the big legacy classifications, which are full of all sorts of crazy things that lots of people edit (in occasionally-crazy ways), but I think lots of folks do so maybe I'm just being paranoid.

I'd not assume Arctos will keep "my" data safe (taxonomy is fully shared), but rather I'd stash my excel-or-whatever (Sheets is nice, and collaborative to boot) once I got it cleaned up, and just make changes in that and occasionally push to Arctos.

You can load small batches to one big Source, or to a few smaller ones that you stitch together in manage collection. The second should have a lot more potential for collaboration, but AFAIK that's all theoretical so ?? You can of course request new sources via Issues.

I think this is all in https://handbook.arctosdb.org/documentation/taxonomy.html

**Comment by DerekSikes** [comment]
Deja vu - I've learned and forgotten this before! Thanks!

However, maybe that's not a good place for that... since I can't seem to remember or puzzle it out from logic etc. Not sure what would be better... but I think this stems from there being Names & Classifications as 2 things... and we search taxonomy for names and if we want to edit classifications of many names it makes sense that one would search for all those names first. This design asks users to go about finding all the names one wants by first finding only a single name...  need to think more on this.

**Comment by dustymc** [comment]
>not a good place for that.

With apologies to Churchill: It's the worst place, except all the rest...

I hope that's mitigated by it also being used only rarely (once per group per usergroup seems right), but I'm not sure I know what anyone actually does in taxonomy-land anymore. Do something amazing and make a webinar of it!

**Comment by dustymc** [comment]
documentation request: https://github.com/ArctosDB/documentation-wiki/issues/305
