### ISSUE TITLE
Agent Merge Request

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#5861]
Use this template when you discover two agents that you believe represent the same person or organization.

**Agent that should remain after the merge**
I was fixing some corrupted MVZ mammal collector numbers and was querying by affected agent. I found that J. K. Doutt has also been entered as J. K. Douth. However, J. K. Douth is no longer an agent, merged with Unknown. There are 130 mammals that have J. K. Douth that should be corrected. Since I can't say J. K. Douth is a bad synonym of J. K. Doutt what are the options? It looks like under Manage Agents I might be able to bulk change Unknown to J. K. Doutt. Is that the proper way to fix these records?
<img width="1296" alt="Screenshot 2023-03-10 at 4 54 28 PM" src="https://user-images.githubusercontent.com/5749672/224455372-5974e117-572f-419e-b01d-f81661816465.png">

**Comment by dustymc** [comment]
> longer an agent, merged with Unknown

Not recently?

https://arctos.database.museum/agents.cfm?agent_id=0

<img width="205" alt="Screenshot 2023-03-13 at 7 48 45 AM" src="https://user-images.githubusercontent.com/5720791/224737822-20e145ed-b1bb-4355-a3c0-4483850e5b23.png">

<img width="848" alt="Screenshot 2023-03-13 at 7 49 42 AM" src="https://user-images.githubusercontent.com/5720791/224737844-50e62bc0-d074-4b79-8964-0f0a98797759.png">

> Manage Agents I might be able to bulk change Unknown to J. K. Doutt.

That will selectively change agent-in-role for your found records (and so I can't tell if that particular screenshot will do what you want or not without knowing how you got there - this thing:

 
<img width="444" alt="Screenshot 2023-03-13 at 7 55 08 AM" src="https://user-images.githubusercontent.com/5720791/224739382-6a950aa4-7ecb-4f3a-93c5-3d9cbcb153c7.png">

is useful for sharing that).

ANYWAY - if that recordset contains 134 attributes and/or 16 event assigners which were attributed to https://arctos.database.museum/agents.cfm?agent_id=0 but which should have been attributed to https://arctos.database.museum/agents.cfm?agent_id=21252720 (or whomever), then that tool can make it so. (And that should all be clear from the inline docs at the top - please let me know if something isn't and I'll try to make it better.)

**Comment by dustymc** [comment]
done?
