### ISSUE TITLE
[external CONTACT]

### ISSUE THREAD

**Issue by hippyherpdude** [ArctosDB/arctos#5862]
Never mind, I found it, after asking several people to stare at the form and see if they could find Waldo. There it was, hidden in plain sight:
<img width="501" alt="Screen Shot 2023-03-12 at 14 32 22" src="https://user-images.githubusercontent.com/65426642/224574982-6cdfa9ae-edc9-44cf-90a4-c058ab68efee.png">
How about making this button a BIG PART OF THE BIG RED SQUARE AT THE TOP OF THE PAGE WHICH APPARENTLY IS IMPORTANT ENOUGH TO ANNOUNCE BUT NOT IMPORTANT ENOUGH TO TELL ME WHERE THE DAMN THING IS. WHEN ONE CLICKS ON "ADD ITEMS" ITS THE ONLY THING I WANT TO DO! THANKS FOR ANOTHER 3 HOURS WASTED ARCTOS.

**Comment by campmlc** [comment]
It's been moved down to the Tools menu- Add Items To Transaction should be the first menu option when you land there from the loan page.

**Comment by campmlc** [comment]
So from the Loan Edit page - go to Add Items, enter your search parameters, and then go down to the tools menu.
