### ISSUE TITLE
Code Table Request - MSB: Museum of Southwestern Biology

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5870]
## Instructions

This is a template to facilitate communication with the Arctos Code Table Committee. Submit a separate request for each relevant value. This form is appropriate for exploring how data may best be stored, for adding vocabulary, or for updating existing definitions.

Reviewing documentation before proceeding will result in a more enjoyable experience.

* [Issue Documentation](http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html)
* [Code Table Documentation](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html)
* [Video Tutorial - Submit a Code Table Request](https://youtu.be/t2jHbsRA3lk)

------------------------------

## Initial Request

**Goal**: Describe what you're trying to accomplish. This is the only necessary step to start this process. The Committee is available to assist with all other steps. Please clearly indicate any uncertainty or desired guidance if you proceed beyond this step.

All [MSB: Museum of Southwestern Biology](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type#msb__museum_of_southwestern_biology) should be replaced with other ID type = other identifier and issued by agent [Museum of Southwestern Biology, University of New Mexico](https://arctos.database.museum/agent/21274282)

**Proposed Value**: Proposed new value. This should be clear and compatible with similar values in the relevant table and across Arctos. 

**Proposed Definition**: Clear, complete, non-collection-type-specific **functional** definition of the value. Avoid discipline-specific terminology if possible, include parenthetically if unavoidable.

**Context**: Describe why this new value is necessary and existing values are not.

**Table**: Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table or value. This may involve multiple tables and will control datatype for Attributes. OtherID requests require BaseURL (and example) or explanation. Please ask for assistance if unsure.

**Collection type**: Some code tables contain collection-type-specific values. ``collection_cde`` may be found from https://arctos.database.museum/home.cfm

**Priority**: Please describe the urgency and/or choose a priority-label to the right. You should expect a response within two working days, and may utilize [Arctos Contacts](https://arctosdb.org/contacts/) if you feel response is lacking.

**Available for Public View**: Most data are by default publicly available. Describe any necessary access restrictions. 

**Project**: Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

**Discussion**: Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

## Approval

All of the following must be checked before this may proceed.

The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality).

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection

If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc. 

1. Can a suitable solution be found here? If not, proceed to (2)
2. Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)
3. Take the discussion to a monthly Arctos Working Group meeting for final resolution.

## Implementation

Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made.

Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel. 

Make changes as described above. Ensure the URL of this Issue is included in the definition. 

Close this Issue.

**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result.

## Special Exemptions

In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases.

1. Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step.
2. The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology.

**Comment by dustymc** [comment]
I will plan on proceeding with this about 2023-03-27 if there are no objections.

I will proceed immediately upon approval of each of the involved collections.


Data:
[temp_msb_museum_of_southwestern_biology.csv](https://github.com/ArctosDB/arctos/files/10959493/temp_msb_museum_of_southwestern_biology.csv)


Summary:

```
 guid_prefix | numrecs 
-------------+---------
 MSB:Mamm    |       4
 MSBObs:Mamm |       3
 MSB:Para    |       1
 MVZ:Mamm    |      16
 UTEP:Bird   |       1
(5 rows)


```

Users:
 @msbparasites
 @mkoo
 @campmlc
 @mvzhuang
 @cjconroy
 @AdrienneRaniszewski
 @jldunnum



See also https://github.com/ArctosDB/arctos/issues/5771

**Comment by msbparasites** [comment]
Good for parasites

**Comment by Jegelewicz** [comment]
@campmlc @mvzhuang the [UTEP:Bird record](https://arctos.database.museum/guid/UTEP:Bird:1465) MSB: number doesn't match the [MSB:Bird:2999](https://arctos.database.museum/guid/MSB:Bird:2999) record I expect it to. Rather than just keep a mess - maybe we should research this one?

**Comment by cjconroy** [comment]
I logged out and searched for one of the MVZ mammals supposedly linked to MSB mammals. Searched catalog number 34945. There is an MSB bird with that number, but no mammal. Is it possibly just encumbered?

**Comment by cjconroy** [comment]
Never mind, it was on the second page. But, to fix, I don't see any reference to MVZ on that record.

**Comment by mvzhuang** [comment]
Typo in our paper catalogs. Should be 5319 – fixed and checking through the other associated ones.

@campmlc I’m guessing y’all gave us the skeleton, because it can’t have skeletons in two places

**Comment by mvzhuang** [comment]
@campmlc Following may need updated dispositions since they're with us now: MSB:Bird: 1765, 1362, 1844, 8807, 4662, 1701, 575, 8501, 4837, 4226, 3949, 5550, 5319, 5277, 2999

**Comment by campmlc** [comment]
@catherpes

**Comment by Jegelewicz** [comment]
Love to see this cleanup and new relationships!

**Comment by campmlc** [comment]
@mvzhuang can you confirm you have all the parts listed for these MSB records? If so, I can change disposition. Let us know if there are specific parts that may be still at MSB.
https://arctos.database.museum/saved/MSB%20Bird%20at%20UTEP

**Comment by campmlc** [comment]
> 34945

@cjconroy here is the MSB:Mamm with that number: https://arctos.database.museum/guid/MSB:Mamm:34945.

Looks like these just need to be changed over to the actual Arctos guids for MSB:Mamm with the integer catalog number, and "same individual as" relationship?

**Comment by campmlc** [comment]
> 5319

@mvzhuang not sure I understand what we need to do with this one? What is the correct MSB:Bird number, and what UTEP number does it link to? And who has what?  :)

**Comment by campmlc** [comment]
> > 34945
> 
> @cjconroy here is the MSB:Mamm with that number: https://arctos.database.museum/guid/MSB:Mamm:34945.
> 
> Looks like these just need to be changed over to the actual Arctos guids for MSB:Mamm with the integer catalog number, and "same individual as" relationship

@cjconroy Looks like we have vouchers and you have tissues. I've loaded the correct same individual as relationships from our end - you should get a notification to accept the reciprocal, or look in Manage: Data Quality: Unreciprocated Relationships to find and accept.

**Comment by campmlc** [comment]
Also @mvzhuang, for this list, we should create "same individual as" relationships to the UTEP specimens. Can you send me the list of your catalog numbers that correspond to each, and confirm which parts you have?
MSB:Bird: 1765, 1362, 1844, 8807, 4662, 1701, 575, 8501, 4837, 4226, 3949, 5550, 5319, 5277, 2999

**Comment by Jegelewicz** [comment]
The one with MSB: Museum of Southwestern Biology | 5319

is https://arctos.database.museum/guid/UTEP:Bird:1465

MSB:Bird

GUID | MSB:Bird | Identified As
-- | -- | --
UTEP:Bird:1463 | 2999 | Geococcyx californianus
UTEP:Bird:1464 | 5277 | Columba livia
UTEP:Bird:1467 | 5550 | Gymnorhinus cyanocephalus
UTEP:Bird:1468 | 3949 | Myadestes townsendi
UTEP:Bird:1469 | 4226 | Callipepla gambelii
UTEP:Bird:1470 | 4837 | Amphispiza bilineata
UTEP:Bird:1471 | 8501 | Gavia immer
UTEP:Bird:1472 | 575 | Callipepla squamata
UTEP:Bird:1474 | 1701 | Melanerpes erythrocephalus
UTEP:Bird:1476 | 4662 | Aphelocoma ultramarina
UTEP:Bird:1477 | 1765 | Aphelocoma coerulescens
UTEP:Bird:1481 | 1362 | Bombycilla garrulus
UTEP:Bird:1482 | 8807 | Geothlypis tolmiei
UTEP:Bird:1484 | 1844 | Carpodacus purpureus
UTEP:Bird:2003 | 1760 | Parus rufescens
UTEP:Bird:2005 | 1673 | Calidris ptilocnemis
UTEP:Bird:2006 | 1698 | Melanerpes carolinus

**Comment by campmlc** [comment]
Great, thanks! and can I assume that there are no parts left at MSB? Everything is at UTEP? It would be helpful to confirm this.
@mvzhuang

**Comment by cjconroy** [comment]
I'm not sure what the steps are. When I go to unreciprocated specimens there is a tool to download them. I see no tool to "accept". Can someone send me a screen shot? Attached are images of what I see. I've downloaded the list of MSB specimens in this case. 
<img width="928" alt="Screenshot 2023-03-24 at 10 56 14 AM" src="https://user-images.githubusercontent.com/5749672/227628051-ca85e433-9eb8-4fe4-8415-6cfbc2df34de.png">
<img width="538" alt="Screenshot 2023-03-24 at 10 54 59 AM" src="https://user-images.githubusercontent.com/5749672/227628065-0e8d89ae-7cb7-4f6d-979b-8a0b9d770b24.png">

In the larger picture, it seems that it is preferred that for any other ID where it involves parts in two different institutions, we need to update relationship from **self** to **same individual as**. MVZ mammals must have thousands of these!  What are the tools to find these, and are there are tools in development to do this automatically?  I was getting along just fine before this development. . . . .

**Comment by Jegelewicz** [comment]
> it is preferred that for any other ID where it involves parts in two different institutions, we need to update relationship from self to same individual as. MVZ mammals must have thousands of these! What are the tools to find these, and are there are tools in development to do this automatically?

This sounds like something that @dustymc might be able to help with. I was going to suggest getting all of the other identifiers for your collection in an Identifier Download Table and reviewing them for needed changes, but that may not be the best path.

<img width="960" alt="Screenshot 2023-03-27 09 25 54" src="https://user-images.githubusercontent.com/5725767/227987825-a019cf06-4755-47cf-94c7-9368127f237f.png">

@dustymc why isn't the "self" relationship available to search?

**Comment by Jegelewicz** [comment]
@dustymc are there any of these left?

**Comment by dustymc** [comment]
```

 guid_prefix | numrecs 
-------------+---------
 MSBObs:Mamm |       3
 MVZ:Mamm    |      16
 UTEP:Bird   |       1
(3 rows)

```

**Comment by Jegelewicz** [comment]
I fixed the UTEP one.

**Comment by Jegelewicz** [comment]
@campmlc @mkoo can we proceed?

**Comment by campmlc** [comment]
Are the MVZ records fixed? The three MSB:MammObs are wolves that also have MSB:Mammal records, I believe - I can check when I'm back at my computer. @jldunnum

**Comment by jldunnum** [comment]
We were testing out the observation catalog with these three. They are in MSB:Mamm as well so can go away

______________________________________________________________

Jonathan L. Dunnum Ph.D. (he, him, his)
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

Chair, Systematic Collections Committee, American Society of Mammalogists
Latin American Fellowship Committee, ASM

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by Jegelewicz** [comment]
> They are in MSB:Mamm as well so can go away

What does that mean? The observation records can be deleted? They should be changed to MSB:Mamm?

**Comment by Jegelewicz** [comment]
No - the MVZ records are not fixed and I do not have the power to fix them. @cjconroy can I help?

**Comment by campmlc** [comment]
Change to MSB:Mamm with jldunnum approval

**Comment by Jegelewicz** [comment]
@campmlc I do not have access to MSBObs:Mamm, so I cannot change these. Sorry!

**Comment by mkoo** [comment]
@dustymc can you fix these 16 records so they properly resolve to MSB records? 

A question of procedure-- these should in relationships since "same individual as"? right? or keep in other identifiers

**Comment by campmlc** [comment]
@jldunnum @dustymc I don't have access to MSB:MammObs either - but it in this case the identifier should just be converted to MSB:Mamm with relationship same individual as.

@mkoo when two institutions share records of the same catalog record, either through sharing parts (tissues one place, voucher other place) or the same record (MSB:Host and MVZ:Bird records, for example), then the relationship should be same individual as. 
But in this case the identifier is in the incorrect format of MSB-34945, so these records need to have the links added to the guids e.g. to MSB:Mamm:34945 with relationship same individual as. The existing identifiers  MSB-34945 could then be converted to other identifier issued by MSB or they could be deleted.

**Comment by campmlc** [comment]
I should add that for external collections not in Arctos but with duplicate data,  the same individual as relationship will be a broken link, until we can find a way to link indirectly via GBIF or GloBI. 
This will also happen when the linkage is correct, but the formatting is wrong, e.g. using "MSB-34945" instead of "MSB:Mamm:34945" as the identifier.

**Comment by dustymc** [comment]
>fix these 16 records 

It'd be a lot easier if we would get out of this horrid inbetweens and address https://github.com/ArctosDB/arctos/issues/6163, but sure.

You can also do it by feeding whatever this gives you:

<img width="345" alt="Screenshot 2023-05-24 at 3 57 58 PM" src="https://github.com/ArctosDB/arctos/assets/5720791/7a03c4ee-8662-49f4-9b7b-623b0ae942a2">


To this:


<img width="236" alt="Screenshot 2023-05-24 at 4 01 49 PM" src="https://github.com/ArctosDB/arctos/assets/5720791/00e90a53-3193-47cb-b533-aab7ffead145">

and this

<img width="213" alt="Screenshot 2023-05-24 at 4 02 01 PM" src="https://github.com/ArctosDB/arctos/assets/5720791/352a8e2f-8201-4e0c-ac6e-ef39741b091e">

I am also confident that at least 16 records could be entered consistently under #6163!

```

 display_value 
---------------
 MSB-34923
 MSB-34924
 MSB-34927
 MSB-34929
 MSB-34938
 MSB-34947
 MSB-34939
 MSB-34945
 MSB-34940
 MSB-34941
 MSB-34931
 MSB-34930
 MSB-34928
 MSB-34946
 MSB-34921
 MSB34922
(16 rows)
```

```
arctosprod@arctos>> update coll_obj_other_id_num set display_value=replace(replace(display_value,'-',''),'MSB',''),other_id_type='MSB:Mamm'
arctos-> where coll_obj_other_id_num_id in (select coll_obj_other_id_num_id from coll_obj_other_id_num
arctos(> inner join flat on coll_obj_other_id_num.collection_object_id=flat.collection_object_id
arctos(> where flat.guid_prefix='MVZ:Mamm' and other_id_type='MSB: Museum of Southwestern Biology');
UPDATE 16
```

Now these are left

```

 guid_prefix | numrecs 
-------------+---------
 MSBObs:Mamm |       3
```

> for external collections not in Arctos but with duplicate data, the same individual as relationship will be a broken link

This is incorrect.

**Comment by campmlc** [comment]
External links with same individual as relationship to anything that does not have a url and cannot create the reciprocal will be a broken link. This is virtually all museums outside of Arctos.

**Comment by campmlc** [comment]
As requested previously by me and @jldunnum, please just convert the MSBObs:Mamm to a same individual as relationship with the MSB:Mamm counterpart.

**Comment by dustymc** [comment]
>External links ... that does not have a url 

🤷

> please just convert the MSBObs:Mamm to a same individual as relationship with the MSB:Mamm counterpart.

```
arctosprod@arctos>> update coll_obj_other_id_num set other_id_type='MSB:Mamm' where other_id_type='MSB: Museum of Southwestern Biology';
UPDATE 3
```

**Comment by cjconroy** [comment]
Let me know what I need to do. I have re-downloaded the list of 16 MVZ mammals. There are only 16, so I don't think I need to bulk load anything. Attached is what I see in other ID for one of them. 

![OtherIDMSB](https://github.com/ArctosDB/arctos/assets/5749672/29646b1c-94d3-413a-ab13-3f7e6e78737c)

**Comment by campmlc** [comment]
@cjconroy  this might already by done by @dustymc ?
If not, then the MSB:Mamm ID type stays the same, there should be nothing in the prefix, the value should be the same numeric value, and the relationship should be "same individual as".  The issued by agent should also be Museum of Southwestern Biology Divison of Mammals.

**Comment by cjconroy** [comment]
LIke this?
<img width="1568" alt="Screenshot 2023-05-24 at 4 44 45 PM" src="https://github.com/ArctosDB/arctos/assets/5749672/5068d39c-b4a0-4945-96c0-0c46b754c01b">

**Comment by campmlc** [comment]
Yep!

**Comment by Jegelewicz** [comment]
Pro tip - you can just change the existing MSB:Mamm identifier - remove the MSB- prefix change the relationship and add the issued by, then save changes

**Comment by campmlc** [comment]
Going forward, you should be getting notifications about any unreciprocated relationships that MSB creates to MVZ collections, with a csv that you can load through the other id component loader. I realize these now get lost in the many notifications we receive, but if you keep an eye out and filter notifications just for those, you can catch them periodically and create the reciprocals.

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/5870#issuecomment-1562038066 should have caught up by now.

>notifications about any unreciprocated relationships 

You can also just turn the bot on.

**Comment by campmlc** [comment]
where do we turn on the bot?

**Comment by dustymc** [comment]
https://handbook.arctosdb.org/documentation/bot.html

**Comment by cjconroy** [comment]
Done. I think.

**Comment by campmlc** [comment]
I'm not seeing how to turn on the bot?

**Comment by cjconroy** [comment]
Just checking my work. I see that if I go to the TURD and look for unreciprocated relationships, my 16 records linked to MSB show up. However, if I use the other tool o the main tools page to look for unreciprocated relationships, there aren't any. I understand these things take time to resolve, but why longer for one than the other?  Is that a sign of an issue?

<img width="310" alt="Screenshot 2023-05-26 at 9 33 32 AM" src="https://github.com/ArctosDB/arctos/assets/5749672/f91ec72e-c68d-4971-904d-6d3edfc60bcd">
<img width="1305" alt="Screenshot 2023-05-26 at 9 33 17 AM" src="https://github.com/ArctosDB/arctos/assets/5749672/a35a62d8-c0e7-4257-8fd8-02c9c03b4839">

**Comment by dustymc** [comment]
Those two things both cache (because I have limited resources), and the caches can get out of sync (potentially for up to about a month). Other than adding resources, I'm not sure how I can get around that, but I could add warning messages or something??

**Comment by mkoo** [comment]
I like warning message and for top-shelf usefulness adding timestamp of last cache

**Comment by campmlc** [comment]
I really really would like to resolve all the issues related to "limited resources" - what can we do to fix? Can we set up a time to discuss and brainstorm? Surely there is a solution.
