### ISSUE TITLE
Planned outage: Sun March 26

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#5872]
## Planned Outage
 - Date and time outage will begin: Sunday March 26 2023
 - Date and time outage is expected to end:  8:00 AM to 2:00 PM (CDT) 
 - Reason for outage: TACC Network Maintenance 
 - Expected behavior during and after the outage: Arctos will be offline

## Communication before/during outage
- [x] Pin this issue
- [x] Banner updated @jegelewicz @mkoo --> post banner next week 3/20
- [x] Email sent to AWG  
- [x] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [x] Unpin this issue
- [x] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by Jegelewicz** [comment]
/remind me to add banner on 2023-03-20

**Comment by ewommack** [comment]
Email scheduled to go out on Thursday 23rd at 1300 MT and Friday 24th March at 1000 MT.

**Comment by Jegelewicz** [comment]
Banner added through 2023-03-26

> Notice: Planned outage. <b>Sunday 26 Mar 2023 between 8:00 AM and 2:00 PM (CST)</b> for TACC Network Maintenance during which time Arctos will not be available. Please plan accordingly and sorry for any inconvenience.

**Comment by lin-fred** [comment]
tweeted and set a tweet to also go out Sunday morning

**Comment by ewommack** [comment]
UPDATE:
Network maintenance is complete. 
-----------------------
Original Announcement:
TACC Network Maintenance Sunday March 26 2023
From: Mark Brueschke
TACC network infrastructure will not be available from 8:00 AM to 2:00 PM (CDT) on Sunday, 26 March 2023. Network maintenance will be performed during this time.

Please submit any questions you may have via the TACC User Portal.
 
https://portal.tacc.utexas.edu/tacc-consulting
