### ISSUE TITLE
Map on search form for polygon search not available?

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#5873]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

I turn on the 'map' and 'spatial search type' customization in the search form and get this:

![Screen Shot 2023-03-13 at 10 17 31 AM Mar 13, 23](https://user-images.githubusercontent.com/9099827/224793404-1dd18be0-fb2a-438c-bea8-299ac188889c.jpg)

no map!

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.
high

**Comment by lin-fred** [comment]
@dustymc can you @ me when it's done so I can message that person on twitter? Thank you!

**Comment by dustymc** [comment]
@lin-fred you have impeccable timing, it should be patched
