### ISSUE TITLE
[external CONTACT] HELP - UNCG:Mamm erroneous locality edit

### ISSUE THREAD

**Issue by bryansmclean** [ArctosDB/arctos#5874]
Hi everyone,

We (UNCG:Mamm) just made a mistake (a really bad one) wherein we edited a locality in error. This caused the coordinates on all specimens using that locality to be changed.

HELP!
Is there anyway we can go back to a prior snapshot for our whole collection???

Bryan

**Comment by campmlc** [comment]
You can see the locality edit history from the Locality Edit View Edit History page - and it should show you previous values, current values, and specimens affected. Can you use that to correct the edits?

**Comment by bryansmclean** [comment]
Thanks @campmlc! Im there but I dont see a way to revert all affected specimens to a prior set of coordinate values.

In digging deeper, this appears to have affected a smaller set of specimens than feared (~10). I think we will revert by hand as I am already planning to move through this record set with some data tasks anyway.

**Comment by campmlc** [comment]
You can't revert with a click  - but you can see what edits were made, and
edit the locality to correct them. This will affect all 10 of the specimens
- so no need to do it one specimen at a time.
