### ISSUE TITLE
Code Table Request - CAS: California Academy of Sciences

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5893]
## Instructions

This is a template to facilitate communication with the Arctos Code Table Committee. Submit a separate request for each relevant value. This form is appropriate for exploring how data may best be stored, for adding vocabulary, or for updating existing definitions.

Reviewing documentation before proceeding will result in a more enjoyable experience.

* [Issue Documentation](http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html)
* [Code Table Documentation](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html)
* [Video Tutorial - Submit a Code Table Request](https://youtu.be/t2jHbsRA3lk)

------------------------------

## Initial Request

**Goal**: Describe what you're trying to accomplish. This is the only necessary step to start this process. The Committee is available to assist with all other steps. Please clearly indicate any uncertainty or desired guidance if you proceed beyond this step.

All [CAS: California Academy of Sciences](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type#cas__california_academy_of_sciences) should be replaced with other ID type = other identifier and issued by agent [California Academy of Sciences](https://arctos.database.museum/agent/10014598)

**Proposed Value**: Proposed new value. This should be clear and compatible with similar values in the relevant table and across Arctos. 

**Proposed Definition**: Clear, complete, non-collection-type-specific **functional** definition of the value. Avoid discipline-specific terminology if possible, include parenthetically if unavoidable.

**Context**: Describe why this new value is necessary and existing values are not.

**Table**: Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table or value. This may involve multiple tables and will control datatype for Attributes. OtherID requests require BaseURL (and example) or explanation. Please ask for assistance if unsure.

**Collection type**: Some code tables contain collection-type-specific values. ``collection_cde`` may be found from https://arctos.database.museum/home.cfm

**Priority**: Please describe the urgency and/or choose a priority-label to the right. You should expect a response within two working days, and may utilize [Arctos Contacts](https://arctosdb.org/contacts/) if you feel response is lacking.

**Available for Public View**: Most data are by default publicly available. Describe any necessary access restrictions. 

**Project**: Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

**Discussion**: Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

## Approval

All of the following must be checked before this may proceed.

The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality).

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection

If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc. 

1. Can a suitable solution be found here? If not, proceed to (2)
2. Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)
3. Take the discussion to a monthly Arctos Working Group meeting for final resolution.

## Implementation

Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made.

Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel. 

Make changes as described above. Ensure the URL of this Issue is included in the definition. 

Close this Issue.

**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result.

## Special Exemptions

In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases.

1. Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step.
2. The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology.

**Comment by dustymc** [comment]
I will plan on proceeding with this about 2023-03-27 if there are no objections.

I will proceed immediately upon approval of each of the involved collections.

Data:
[temp_cas_california_academy_of_sciences.csv.zip](https://github.com/ArctosDB/arctos/files/10961613/temp_cas_california_academy_of_sciences.csv.zip)


Summary:
|guid_prefix|numrecs|
|-----------|--------|
|CHAS:Bird|2|
|DMNS:Inv|1|
|MVZ:Bird|14|
|MVZ:Herp|185|
|MVZ:Mamm|15|
|UAM:Fish|3|
|UAM:Mamm|9|
|UCM:Herp|24|
|UTEP:Ento|1|


Users:
@ebraker
@genevieve-anderegg
@mkoo
@ccicero
@sharpphyl
@amgunderson
@atrox10
@cjconroy
@wellerjes
@Jegelewicz
@droberts49
@acdoll


See also https://github.com/ArctosDB/arctos/issues/5771

**Comment by Jegelewicz** [comment]
UTEP record changed

**Comment by wellerjes** [comment]
Reviewed; okay to proceed for CHAS

**Comment by cjconroy** [comment]
The spelling seems fine to me. Are we supposed to do anything with our specimens, like change relationships?
Also, I found it quite handy to find all MVZ mammals that were also cross listed as something else by finding them in the drop down. I can't seem to even find that drop down. What will be the process where I will try to find all MVZ mammals that are cross listed at CAS? Clearly not a drop down menu, but will I need to know the exact spelling of this agent?
Lastly, I know we put in other identifiers even when there was no number. For example, where we knew vouchers went to south American collections, but would take many years to get cataloged. Are those records going to be problematic?

**Comment by dustymc** [comment]
>do anything with our specimens

Nope.

>find all MVZ mammals that were also cross listed

Speaking only to the data, not to current UI: There are ~a dozen "MVZ Numbers" (and they're probably not used very predictably). I think you're probably seeing some hopefully-not-quite-arbitrary subset of what you want when you look for things bearing some particular MVZ identifier. There's not really anything else that could be supported by typed identifiers - they're just authorities, that's the end of their reach. Agents changes all of that. Given MVZ (and maybe UCB and UC - this goes in all directions) and some subdepartments (https://arctos.database.museum/agent/21334682 and https://arctos.database.museum/agent/21334677) - a bunch of related agents, whatever the details - it's just a matter of UI to *actually* find everything related to MVZ, even extending to things collected by you while you were an employee. There's no UI for that, I'm not sure there will be until/unless there's some specific use case, but it's easily supported by the agent-linked data (and not at all available from the strongly-typed identifiers, even if by some miracle they've been used precisely).

> identifiers even when there was no number.

Whatever you did to fool the constraints will keep working, and maybe this'll make them a bit easier to resolve.

**Comment by cjconroy** [comment]
Thanks. Back to how I find all MVZ mammals that also have CAS identity. What buttons do I press, cells I fill in, now that I won't be able to find through the drop down. 
Chris

**Comment by dustymc** [comment]
>find all MVZ mammals that also have CAS identity

IssuedBy

<img width="989" alt="Screenshot 2023-03-14 at 10 39 37 AM" src="https://user-images.githubusercontent.com/5720791/225091520-b2b83a36-e019-475f-ab07-5b47b9e026bb.png">

>CAS

https://arctos.database.museum/agent/10014598 should have an AKA.

**Comment by Jegelewicz** [comment]
> should have an AKA.

added - I tried to do this as I went - but sometimes I either wasn't sure what was a good acronym or I just missed them...

**Comment by Jegelewicz** [comment]
MSB Birds asks for institutional catalog number instead of other identifier, but they aren't using it.

**Comment by ebraker** [comment]
Ok for UCM
