### ISSUE TITLE
random stuff from MSB pow-wow

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ArctosDB/arctos#590]
```
parasites, data entry, and randomness:


https://docs.google.com/document/d/17geDOzPRZrfGOc9jupuSXqI4Nl3nmF_oG_j_Zg7XkYI/
edit
```

Original issue reported on code.google.com by `dust...@gmail.com` on 7 Nov 2012 at 3:57

**Comment by dustymc** [comment]
tentatively closing - I think everything in the doc has been discussed

**Comment by mkoo** [comment]
I agree and if there isnt, someone will file an issue with a better title!
thx
