### ISSUE TITLE
Code Table Request - Coyotean biochron

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#5916]
**Goal**
Add biochron necessary for a new locality.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctbiochronology

**Proposed Value**
Coyotean

**Proposed Definition**
The oldest interval of Permian time based on tetrapods. Coyotean time begins with the first appearance datum of the pelycosaur Sphenacodon and encompasses the Pennsylvanian-Permian boundary. [Lucas 2006
](https://doi.org/10.1144/GSL.SP.2006.265.01.04)

If there are no objections, I will add this.

**Comment by Jegelewicz** [comment]
no objection
