### ISSUE TITLE
other IDs - limit options

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ArctosDB/arctos#593]
```
for known "types" of otherID (genbank=text, af=numeric, etc.) limit/hide the 
irrelevant options when creating/editing/dataentering other ID
```

Original issue reported on code.google.com by `dust...@gmail.com` on 30 Nov 2012 at 8:19

**Comment by dustymc** [comment]
Low priority - does not seem to cause data problems, just errors for some users.

**Comment by dustymc** [comment]
Changes to SpecimenDetail/OtherIDs:
- new ID type GenBank will only accept prefix
- new ID types NK and AF will only accept integer
