### ISSUE TITLE
Code Table Request - U. S. National Park Service accession

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5968]
## Instructions

This is a template to facilitate communication with the Arctos Code Table Committee. Submit a separate request for each relevant value. This form is appropriate for exploring how data may best be stored, for adding vocabulary, or for updating existing definitions.

Reviewing documentation before proceeding will result in a more enjoyable experience.

* [Issue Documentation](http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html)
* [Code Table Documentation](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html)
* [Video Tutorial - Submit a Code Table Request](https://youtu.be/t2jHbsRA3lk)

------------------------------

## Initial Request

**Goal**: Describe what you're trying to accomplish. This is the only necessary step to start this process. The Committee is available to assist with all other steps. Please clearly indicate any uncertainty or desired guidance if you proceed beyond this step.

All [U. S. National Park Service accession](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type#u__s__national_park_service_accession) should be replaced with other ID type = other identifier and issued by agent [United States National Park Service](https://arctos.database.museum/agent/40)

**Proposed Value**: Proposed new value. This should be clear and compatible with similar values in the relevant table and across Arctos. 

**Proposed Definition**: Clear, complete, non-collection-type-specific **functional** definition of the value. Avoid discipline-specific terminology if possible, include parenthetically if unavoidable.

**Context**: Describe why this new value is necessary and existing values are not.

**Table**: Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table or value. This may involve multiple tables and will control datatype for Attributes. OtherID requests require BaseURL (and example) or explanation. Please ask for assistance if unsure.

**Collection type**: Some code tables contain collection-type-specific values. ``collection_cde`` may be found from https://arctos.database.museum/home.cfm

**Priority**: Please describe the urgency and/or choose a priority-label to the right. You should expect a response within two working days, and may utilize [Arctos Contacts](https://arctosdb.org/contacts/) if you feel response is lacking.

**Available for Public View**: Most data are by default publicly available. Describe any necessary access restrictions. 

**Project**: Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

**Discussion**: Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

## Approval

All of the following must be checked before this may proceed.

The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality).

- [ ] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [ ] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection

If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc. 

1. Can a suitable solution be found here? If not, proceed to (2)
2. Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)
3. Take the discussion to a monthly Arctos Working Group meeting for final resolution.

## Implementation

Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made.

Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel. 

Make changes as described above. Ensure the URL of this Issue is included in the definition. 

Close this Issue.

**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result.

## Special Exemptions

In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases.

1. Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step.
2. The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology.

**Comment by dustymc** [comment]
~~I will plan on proceeding with this about 2023-03-28 if there are no objections.~~

I will proceed immediately upon approval of each of the involved collections.

Data:
[temp_u_s_national_park_service_accession.csv.zip](https://github.com/ArctosDB/arctos/files/10971902/temp_u_s_national_park_service_accession.csv.zip)


Summary:
|guid_prefix|numrecs|
|-----------|--------|
|DMNS:Mamm|30|
|KWP:Ento|39|
|MSB:Mamm|534|
|MSB:Para|1|
|MVZ:Mamm|1|
|UAM:Alg|1|
|UAMb:Herb|15050|
|UAM:Ento|55937|
|UAM:ES|1182|
|UAM:Herb|19090|
|UAM:Inv|1|
|UAM:Mamm|5740|
|UAMObs:Ento|3|
|UCM:Bird|37|
|UCM:Egg|2|
|UCM:Fish|4|
|UCM:Herp|60|
|UCM:Mamm|197|
|UMNH:Mamm|9|
|UTEP:ES|1|


Users:
@ebraker
@mkoo
@campmlc
@amgunderson
@DerekSikes
@mvzhuang
@cjconroy
@AdrienneRaniszewski
@acdoll
@jldunnum
@jrdemboski
@msbparasites
@mlbowser
@kderieg322079
@StefanieBond
@jandreslopez


See also https://github.com/ArctosDB/arctos/issues/5771

**Comment by campmlc** [comment]
Hold pending resolution of other ID type. Given this is one of at least two identifiers issued by NPS, changing to other identifier is inappropriate. Propose using "accession number" as ID type.
See https://github.com/ArctosDB/arctos/issues/5968

**Comment by dustymc** [comment]
I'd like to request a revision: The agent should be more specific. (NPS Accession System or ?????????) This is an addition request, not change - the new agent should be a child/division/whatever of NPS (and should have a 'catalog' sister).

@ebraker here's some loader-tables, but you probably should adjust the agent, see above.

[temp_ucm_npsa_loader.csv](https://github.com/ArctosDB/arctos/files/10994592/temp_ucm_npsa_loader.csv)
[temp_ucm_npsa_unloader.csv](https://github.com/ArctosDB/arctos/files/10994593/temp_ucm_npsa_unloader.csv)

**Comment by Jegelewicz** [comment]
> The agent should be more specific. (NPS Accession System or ?????????) 


[United States National Park Service Register](https://arctos.database.museum/agent/21347817)

**Comment by ebraker** [comment]
Each reposited specimen receives an NPS catalog number and an NPS accession number. So we need to make that distinction somewhere.

**Comment by Jegelewicz** [comment]
> we need to make that distinction somewhere.

There are two issuing agents

[United States National Park Service Register](https://arctos.database.museum/agent/21347817) for accessions
[United States National Park Service Catalog](https://arctos.database.museum/agent/21347816) for catalog numbers

**Comment by Jegelewicz** [comment]
Feel free to suggest better names.

**Comment by campmlc** [comment]
Here is relevant info on how the National Park Service uses catalog and
accession numbers:https://www.nps.gov/museum/publications/mhii/mh2ch3.pdf

Sec 3.2:  Note: The catalog number identifies the object or group of
objects. The accession number identifies the transaction that established
NPS ownership of the object or group of objects.

**Comment by mabreslin** [comment]
Having both USNPS catalog and accession numbers as an option for the type of identifier is incredibly helpful for tracking park specimens, especially when they are entered under so many slightly different formats. Having the type of identifier indicate clearly which number is the accession verses the catalog allows the users to group specimens based on park accession rather than arctos accession.  Also, if a mistake has been made on the locality of a record the other identifier field is a good back up to indicate that a specimen belongs to the National Park Service.

**Comment by campmlc** [comment]
I agree with @mabreslin. I also support keeping catalog number (or institutional catalog number) and adding accession number as a new value in the identifier code table, so that we can use the single agent National Park Service (or the agent name of a specific park, if available) which can be associated with either or both the ID types. This also allows searching on all identifiers of both types from the agent activity page, so if one is mis-assigned it can still be found. 
Having both identifier types in the code table would mean we could use either or both for any park and have them share issued by agents.

**Comment by dustymc** [comment]
>I agree

The best way to express that would be by opening an [Issue](https://github.com/ArctosDB/arctos/issues/new?assignees=&labels=Function-CodeTables&template=code-table-request--proposed-.md&title=Code+Table+Request+-+) requesting and documenting a new type.

**Comment by campmlc** [comment]
See https://github.com/ArctosDB/code-table-work/issues/41

**Comment by campmlc** [comment]
Also posted in #41 above:
See the problem with using NPS Register as an agent: https://www.nps.gov/subjects/nationalregister/index.htm
A search on this yields the wrong database. Collections accessions in the NPS are not assigned by the Register of Historic Places.

From https://www.nps.gov/museum/publications/MHII/mh2ch2firstfile.pdf
In the National Park Service (NPS), an accession is the process of acquiring museum objects or specimens from a single source at one time. The NPS keeps accession records in several ways, including: 
Accession book: Contains information about the accession 
Accession file: Contains all relevant documentation about the accession 
Automated National Catalog System (ANCS+) accession database: Contains accession records 
The NPS also uses accession numbers to link materials submitted with a study. For example, when collecting specimens in Acadia National Park, the research permit will include an accession number. 
The NPS is authorized to accession and deaccession by two laws: 
Museums: Formerly known as the Museum Properties Management Act, this law is codified at 54 U.S.C §§ 102501- 102504 
Native American Graves Protection and Repatriation Act (NAGPRA): This law is codified at 25 U.S.C. §§ 3001-3013 
The NPS Museum Handbook, Part II, Chapters 3 and 4, Appendix H, and the ANCS+ User Manual provide standard cataloging procedures.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/code-table-work/issues/41
