### ISSUE TITLE
Code Table Request - UAM: University of Alaska Museum

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5971]
## Initial Request

All [UAM: University of Alaska Museum](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type#uam__university_of_alaska_museum) should be replaced with other ID type = identifier and issued by agent [University of Alaska Museum of the North](https://arctos.database.museum/agent/3691)

**Comment by dustymc** [comment]
I will plan on proceeding with this about 2023-03-28 if there are no objections.

I will proceed immediately upon approval of each of the involved collections.

Data:
[temp_uam_university_of_alaska_museum.csv.zip](https://github.com/ArctosDB/arctos/files/10972141/temp_uam_university_of_alaska_museum.csv.zip)


Summary:
|guid_prefix|numrecs|
|-----------|--------|
|MSB:Bird|173|
|MSB:Mamm|1|
|UAM:Arc|5|
|UAM:ES|5|
|UAM:Inv|2|
|UAM:Mamm|1|


Users:
@campmlc
@catherpes
@amgunderson
@sjshirar
@jandreslopez
@AdrienneRaniszewski
@jldunnum


See also https://github.com/ArctosDB/arctos/issues/5771

**Comment by amgunderson** [comment]
I am opposed. As with all these other ID changes you are proposing - if someone doesn't like an ID type they can choose not to use it. You are deleting original data with these changes.

**Comment by Jegelewicz** [comment]
I changed the MSB:Mamm to a relationship with the UAM:Mamm record.

**Comment by Jegelewicz** [comment]
On the MSB:Bird records, it appears this is someone picking the wrong type during data entry? in any case, all MSB;Bird have been changed to UAM:Bird with same individual as relationships. File attached.

I can do nothing about the UAM stuff which is potentially more of the same and as long as this identifier type is available for use people doing data entry will miss creating relationships because they pick the wrong type.
[UAM_Bird_identifiers.xlsx](https://github.com/ArctosDB/arctos/files/11576872/UAM_Bird_identifiers.xlsx)

**Comment by dustymc** [comment]
>someone picking the wrong type during data entry? i

Yes, a very common pattern (or what certainly looks like it from here!) - and just what https://github.com/ArctosDB/arctos/issues/6163 is designed to address.

**Comment by dustymc** [comment]
@AJLinn this is taking up a significant portion of your screen in https://github.com/ArctosDB/arctos/issues/8115, apparently you've chosen it as "your" type.

There are a ~dozen records involved

```
 guid_prefix | numrecs 
-------------+---------
 UAM:Arc     |       5
 UAM:Ento    |       1
 UAM:ES      |       5
 UAM:Inv     |       2
 UAM:Mamm    |       1
```

and the data have (predictably) become denormalized and undiscoverable, see eg https://arctos.database.museum/guid/UWBM:VP:119941

I am hesitant to bring this up at all, but I would very much like to find a path out of this less-than-functional state, and this seems like a very easy and non-intrusive upgrade of some very low-quality data. Help?


 @amgunderson
 @DerekSikes
 @sjshirar
 @jandreslopez

**Comment by mkoo** [comment]
This is a stale issue with no new discussion and is currently blocking several current issues. We are resolving and closing.
