### ISSUE TITLE
Search involving agents does not use agent pick

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5978]
When I search other identifiers and want to make use of the "issued by" I expect to enter something, hit tab and get the usual agent pick form - this is not happening. I think this may contribute to reluctance to use this feature....

**Comment by Jegelewicz** [comment]
FWIW - this should also work in "assigned by" but does not.

**Comment by dustymc** [comment]
No agent search does this, so I'm generalizing the issue.

FWIW I think this would be a significant step backwards. It's not necessary to spell https://arctos.database.museum/agent/2570 as "Robert L. Rausch" - any of the 15 aliases ("Rausch, Bob") or even parts thereof ("Lloyd Rausch") will find the records. The worst case scenario involves false positives (there might be an unrelated Lloyd Rausch and you don't care about those items), which is always easy to narrow down. I think what you're proposing would lead to false negatives, which can be near impossible to recover from. (The average user response seems to be deciding there's nothing of interest and moving on.)

**Comment by campmlc** [comment]
I don't see how we can use other identifier as ID type and not allow a controlled vocab search of issued by agent? What am I missing?

**Comment by campmlc** [comment]
Is the functionality to search other identifier and put issued by as "Rausch"? And then it would pull up anything with remotely that name?
So if I understand correctly, if we are searching IDs issued by a USFWS, and USFWS is an aka of United States Fish and Wildlife Service, this would work?

**Comment by Jegelewicz** [comment]
This is a must have if we are going to differentiate between

Florida Museum (organization: 1015781) [[new window]](https://arctos.database.museum/agents.cfm?agent_id=1015781)
Florida Museum Herpetology Collection (organization: 21347655) [[new window]](https://arctos.database.museum/agents.cfm?agent_id=21347655)
Florida Museum Ichthyology Collection (organization: 21347652) [[new window]](https://arctos.database.museum/agents.cfm?agent_id=21347652)
Florida Museum Invertebrate Zoology Collection (organization: 21347650) [[new window]](https://arctos.database.museum/agents.cfm?agent_id=21347650)
Florida Museum of Natural History (other agent: 21259400) [[new window]](https://arctos.database.museum/agents.cfm?agent_id=21259400)
Florida Museum Ornithology Collection (organization: 21347651) [[new window]](https://arctos.database.museum/agents.cfm?agent_id=21347651)

And we expect to be able to do that.

**Comment by dustymc** [comment]
>issued by as "Rausch"? And then it would pull up anything with remotely that name?

String-match-ish so not too remote (yet, probably...), but yes - which is the same way all agent search fields have worked in every form since Arctos was Sybil.

>USFWS is an aka of United States Fish and Wildlife Service, this would work?

Yes.

>Florida

Yes. Just about 100% chance 1015781 holds a few things that should properly be attributed to 21347651 (or something of the sort) - "Florida Museum" finds them all. (And maybe someday the explicit relationships through those will drill even deeper - that's "just UI.") The few(?? I very occasionally wish I had creepy facebook-like stats...) people who know what they're asking for and really want only 21347651 can just click the link from whatever record they find first.

**Comment by dustymc** [comment]
> I've heard "Just UI" a lot of times 

It's all true! And it's a critical distinction, even if we don't have the resources (or need, or whatever) to do anything about it. The structure of the data controls what questions those data can answer, absolutely and always. [GIGO](https://en.wikipedia.org/wiki/GIGO)! Any identifier that's paired with an issuer just became capable of answering a whole bunch of new questions, even if nobody's probably ever going to want to search by sum of the digits in the issuer's nephew's phone number. Still, that sort of thing is not possible without the involvement of Agents - which can carry addresses and relationships - and is truly "just UI" when they are involved.

>see something made to actually work.

Search any agent-thing in any interface? (Or tell me what precisely you'd like to see.)

>should be able to link to the correct collection

That is in no way related to this so I'm not sure what you are suggesting. An appropriate agent (that almost always means 'as specific as possible') should be asserted, always, for everything.

**Comment by campmlc** [comment]
I agree with this: An appropriate agent (that almost always means 'as specific as possible') should be asserted, always, for everything.
But are you saying that even though we link records to specific agents, we shouldn't provide that level of specificity in the search so people will enter something randomly and hopefully something relevant will pop up? That is what is sounds like from a user's perspective? If that is the proposal, I guess it would be helpful to see this work?

**Comment by campmlc** [comment]
Maybe we need "general search" and "specific search" options - and the latter brings up the code table?

**Comment by dustymc** [comment]
>we shouldn't provide

No, I'm saying we shouldn't FORCE.

>guess it would be helpful to see this work?

Select an agent in data entry.

**Comment by campmlc** [comment]
https://github.com/ArctosDB/arctos/issues/6004

**Comment by campmlc** [comment]
#6002

**Comment by Jegelewicz** [comment]
I guess I see the point - and because nobody has ever noticed the issue when searching for agents in other places, perhaps it is OK? It can be misleading if people aren't paying close attention though - I'll need to think about it!

**Comment by Jegelewicz** [comment]
Not a pick, but a suggestion...
