### ISSUE TITLE
Question re: agent merging notifications

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#5989]
Just curious about how this seemingly endless group of agents of initials-only managed to not get verbatimized and wondering how much longer this process might take so I can stop having 30 new notifications every day resulting from their merging to unknown?

(Sorry, just feeling cranky today as I attempt to keep my Arctos notifications at net-zero, since I will never again see that in my email inbox!).
<img width="761" alt="Screenshot 2023-03-14 at 10 45 51 AM" src="https://user-images.githubusercontent.com/17605945/225107222-31c4b06a-bc16-4df2-a963-6e54b8dcdddb.png">

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/5711 - there was a huge backlog, now it's almost caught up.

**Comment by cjconroy** [comment]
I have nothing to add to 99% of these things. Should I be changing my status to Read or Delete in order for them to go away?  It would help if there was a helper pop up window next to these boxes, or at the top.

**Comment by Jegelewicz** [comment]
> Notifications are deleted after 90 days, unless marked important or having 'shared.''

 You don't have to make them go away, but if they bother you, filter for them, check all, and delete. (This doesn't delete them for everyone, just for you.)

![image](https://user-images.githubusercontent.com/5725767/225449701-fe7c3938-3ef3-4dd3-b864-41d64ebbc657.png)
