### ISSUE TITLE
Code Table Request - UFC: University of Florida Collections

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6001]
## Instructions

This is a template to facilitate communication with the Arctos Code Table Committee. Submit a separate request for each relevant value. This form is appropriate for exploring how data may best be stored, for adding vocabulary, or for updating existing definitions.

Reviewing documentation before proceeding will result in a more enjoyable experience.

* [Issue Documentation](http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html)
* [Code Table Documentation](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html)
* [Video Tutorial - Submit a Code Table Request](https://youtu.be/t2jHbsRA3lk)

------------------------------

## Initial Request

**Goal**: Describe what you're trying to accomplish. This is the only necessary step to start this process. The Committee is available to assist with all other steps. Please clearly indicate any uncertainty or desired guidance if you proceed beyond this step.

All [UFC: University of Florida Collections](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type#ufc__university_of_florida_collections) should be replaced with other ID type = ~~other identifier and issued by agent [Florida Museum](https://arctos.database.museum/agent/1015781)~~ institutional catalog number and agents as outlined [here](https://github.com/ArctosDB/arctos/issues/6001#issuecomment-1468770317).

**Proposed Value**: Proposed new value. This should be clear and compatible with similar values in the relevant table and across Arctos. 

**Proposed Definition**: Clear, complete, non-collection-type-specific **functional** definition of the value. Avoid discipline-specific terminology if possible, include parenthetically if unavoidable.

**Context**: Describe why this new value is necessary and existing values are not.

**Table**: Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table or value. This may involve multiple tables and will control datatype for Attributes. OtherID requests require BaseURL (and example) or explanation. Please ask for assistance if unsure.

**Collection type**: Some code tables contain collection-type-specific values. ``collection_cde`` may be found from https://arctos.database.museum/home.cfm

**Priority**: Please describe the urgency and/or choose a priority-label to the right. You should expect a response within two working days, and may utilize [Arctos Contacts](https://arctosdb.org/contacts/) if you feel response is lacking.

**Available for Public View**: Most data are by default publicly available. Describe any necessary access restrictions. 

**Project**: Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

**Discussion**: Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

## Approval

All of the following must be checked before this may proceed.

The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality).

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [ ] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection

If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc. 

1. Can a suitable solution be found here? If not, proceed to (2)
2. Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)
3. Take the discussion to a monthly Arctos Working Group meeting for final resolution.

## Implementation

Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made.

Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel. 

Make changes as described above. Ensure the URL of this Issue is included in the definition. 

Close this Issue.

**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result.

## Special Exemptions

In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases.

1. Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step.
2. The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology.

**Comment by dustymc** [comment]
I will plan on proceeding with this about 2023-03-28 if there are no objections.

I will proceed immediately upon approval of each of the involved collections.

Data:
[temp_ufc_university_of_florida_collections.csv.zip](https://github.com/ArctosDB/arctos/files/10973392/temp_ufc_university_of_florida_collections.csv.zip)


Summary:
|guid_prefix|numrecs|
|-----------|--------|
|ALMNH:Inv|70|
|MSB:Bird|1|
|MSB:Fish|1|


Users:
@campmlc
@catherpes
@kmkocot


See also https://github.com/ArctosDB/arctos/issues/5771

**Comment by campmlc** [comment]
The University of Florida Collections are the same as the Florida Museum, the Florida Museum of Natural History, the Florida State Museum. They should share the same agent issued by, and the agents should share a relationship.

**Comment by campmlc** [comment]
Do we need to add acronyms such as FLMNH, UF etc to the agent page as akas? Should we be doing this for all collections? Will someone want to search "issued by" = FLMNH?

**Comment by dustymc** [comment]
For The List: Issuedby makes merging duplicate messes easy.

The agents should be dealt with in the same way any agent should be dealt with - there should be one agent per "entity" and duplicates should be flagged for merger. 

But, please comment with the replacement agent if that happens before any data updates - I'll just be looking at the ID and expecting what was initially proposed to work, knowing that's not good enough BEFORE the crash would be very appreciated.

**Comment by campmlc** [comment]
The University of Florida Collections are the same as the Florida Museum, the Florida Museum of Natural History, the Florida State Museum. They should share the same agent issued by, and the agents should share a relationship.

**Comment by Jegelewicz** [comment]
The mergers have already been made.

Here are all the agents that include the word "Florida". I think we are good?

Conservancy of Southwest Florida (organization: 1014866) [[new window]](https://arctos.database.museum/agents.cfm?agent_id=1014866)
Florida Department of Agriculture and Consumer Services (organization: 21345738) [[new window]](https://arctos.database.museum/agents.cfm?agent_id=21345738)
Florida Department of Health in Miami-Dade County (organization: 1009367) [[new window]](https://arctos.database.museum/agents.cfm?agent_id=1009367)
Florida Expedition (other agent: 21293752) [[new window]](https://arctos.database.museum/agents.cfm?agent_id=21293752)
Florida Expedition, 1877 (other agent: 21293540) [[new window]](https://arctos.database.museum/agents.cfm?agent_id=21293540)
Florida Fish and Wildlife Conservation Commission (organization: 21277478) [[new window]](https://arctos.database.museum/agents.cfm?agent_id=21277478)
Florida Keys Wild Bird Rehabilitation Center (organization: 21316445) [[new window]](https://arctos.database.museum/agents.cfm?agent_id=21316445)
Florida Museum (organization: 1015781) [[new window]](https://arctos.database.museum/agents.cfm?agent_id=1015781)
Florida Museum Herpetology Collection (organization: 21347655) [[new window]](https://arctos.database.museum/agents.cfm?agent_id=21347655)
Florida Museum Ichthyology Collection (organization: 21347652) [[new window]](https://arctos.database.museum/agents.cfm?agent_id=21347652)
Florida Museum Invertebrate Zoology Collection (organization: 21347650) [[new window]](https://arctos.database.museum/agents.cfm?agent_id=21347650)
Florida Museum of Natural History (other agent: 21259400) [[new window]](https://arctos.database.museum/agents.cfm?agent_id=21259400)
Florida Museum Ornithology Collection (organization: 21347651) [[new window]](https://arctos.database.museum/agents.cfm?agent_id=21347651)
Florida State University (organization: 21344916) [[new window]](https://arctos.database.museum/agents.cfm?agent_id=21344916)
Florida Wildlife Care (organization: 21252058) [[new window]](https://arctos.database.museum/agents.cfm?agent_id=21252058)
Florida Wildlife Hospital (organization: 21347749) [[new window]](https://arctos.database.museum/agents.cfm?agent_id=21347749)
Northwest Florida State College (organization: 21346533) [[new window]](https://arctos.database.museum/agents.cfm?agent_id=21346533)
South Florida Wildlife Hospital (organization: 21316577) [[new window]](https://arctos.database.museum/agents.cfm?agent_id=21316577)
University of Florida (organization: 1014631) [[new window]](https://arctos.database.museum/agents.cfm?agent_id=1014631)
University of Florida, Department of Biology (organization: 21293398) [[new window]](https://arctos.database.museum/agents.cfm?agent_id=21293398)

**Comment by campmlc** [comment]
We still need University of Florida Mammalogy Collection = Florida Museum Mammalogy Collection although perhaps it is not currently used by Arctos Collections. But likely will be, if we can add it.

**Comment by Jegelewicz** [comment]
> if we can add it.

Pretty sure that a bunch of you guys have manage agent capability? There isn't any secret formula! Or are you asking me to add it now?

**Comment by campmlc** [comment]
I can do so, but didn't want to interrupt a specific process and risk a duplicate. I'll add now.

**Comment by campmlc** [comment]
MSB is OK with this if the issued by agent can be changed to Florida Museum Ornithology Collection and Florida Museum Ichthyology collection agents. And ID type = catalog number.

**Comment by Jegelewicz** [comment]
@dustymc I'd say this one is ready to go.
