### ISSUE TITLE
entities and identifiers and issuers

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6002]
If this is used for entities, that usage should be resolved before
proceeding.

_Originally posted by @campmlc in https://github.com/ArctosDB/arctos/issues/5992#issuecomment-1468750885_

**Comment by dustymc** [comment]
Do entity tools (or??) need some UI change to work with more agent-typed identifiers?

**Comment by dustymc** [comment]
Added and tested assigned by, but I don't think it's necessary unless there are super-waffly identifiers involved, and those should never be used for this sort of thing anyway.

The only sorta-maybe-weird thing I changed is that session user now who issues OrganismIDs - I think that's correct but not 100% sure.

**Comment by campmlc** [comment]
Magic Entities tool now allows selection of issued by agent. But this is free text entry. This is another area where we should discuss having a dropdown.
