### ISSUE TITLE
Feature Request - Add New Identifier Attributes to Data Entry Form/Bulkload

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#6003]
**Is your feature request related to a problem? Please describe.**
Related to New Identifier Functions

**Describe what you're trying to accomplish** 
With the new Identifier Functions, there is a need to update corresponding forms.

**Describe the solution you'd like**
Incorporate the new fields (Issued by, Remarks) into standard workflow in data entry, bulkloader form.
![image](https://user-images.githubusercontent.com/93737929/225138522-62ec7dd0-89fe-4b89-ace4-f2c108fdfb36.png)

**Describe alternatives you've considered**
Edit individual catalog records as I come across them.

**Additional context**
Pulling this from [Issue  5771](https://github.com/ArctosDB/arctos/issues/5771#issuecomment-1464336002) so it doesn't get buried.
Also applicable to [Issue 4604](https://github.com/ArctosDB/arctos/issues/4604)

**Priority**
Normal to High - I'd like to be able to include this in workflows sooner rather than later.

**Comment by campmlc** [comment]
Agree, especially to enable the pull function for these new fields. While we are at it, can we change the font on pull to larger and more visible?

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/5193 is also particularly relevant (and ultimately controls what's available from the data entry UI)
