### ISSUE TITLE
New Identifier Model Effect on Relationships and Entities

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6004]
The new identifier model of assigning issued by agent information and converting IDs to other IDs needs to be evaluated for effects on the following:
-creating relationships across collections and institutions
-creating entities across collections and institutions
-searching relationships across collections and institutions
-searching entitites
-data entry forms: see #6003 
-pull functions
-reports
-export to aggregators - including GGBN and NEON.

**Comment by dustymc** [comment]
TODO



- data entry forms: see https://github.com/ArctosDB/arctos/issues/6003
    - will be addressed in https://github.com/ArctosDB/arctos/issues/5331 (and off-topic, but I assume the silence is enthusiastic approval of where we are in https://github.com/ArctosDB/arctos/issues/5193 and there will be no complaints when the bulkloader is locked after implementation as discussed and agreed, starting about now??)
    - added to extras; not blocking entry
--------------------

NOT HERE


- creating entities across collections and institutions
    - should be discussed in https://github.com/ArctosDB/arctos/issues/6002
- searching entitites
    - possibly a topic for https://github.com/ArctosDB/arctos/issues/6002, but this also makes me suspect that something isn't understood??
- reports
    - Can be handled individually, I can't know what you want without being told and that's probably different for everyone

------------------

DONE


- searching relationships across collections and institutions
    - added to UI
- creating relationships across collections and institutions
    - none (and this point makes me suspect that identifiers in general are not understood??)
- pull functions
    - done
-export to aggregators - including GGBN and NEON.
    - no effect
----------------------
