### ISSUE TITLE
geog request: Sri Lanka

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6008]
@dustymc can you reload **Myanmar** from service? I dont know why Kayah State is missing for Phyllis because it's there in the shapefile (and the other missing states) 

Same with reloading **Sri Lanka**-- if we stick with adm_1 then we should have 25 districts (all included in GADM v4.1)

_Originally posted by @mkoo in https://github.com/ArctosDB/arctos/issues/5654#issuecomment-1469272445_

**Comment by dustymc** [comment]
[temp_pre_geog(2).csv](https://github.com/ArctosDB/arctos/files/10981423/temp_pre_geog.2.csv)

Please review and check carefully against what's in Arctos (which is now GADMified).

**Comment by sharpphyl** [comment]
> Please review and check carefully against what's in Arctos (which is now GADMified).

Not sure if you're asking me or @mkoo to review.  It looks good to me and should add the missing 15 districts.

**Comment by dustymc** [comment]
>me or @mkoo

eyeballs is eyeballs....

done!

**Comment by mkoo** [comment]
my eyeballs are more blood shot!
