### ISSUE TITLE
Save Profile error message problem

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#6009]
Saving a data entry profile returns this error

![snip](https://user-images.githubusercontent.com/15368365/225416166-f90acdbe-5edd-4947-b9f0-321394ed4f9d.JPG)

The only change was a date.  It's happened to other volunteers even with no changes to the profile

PC on Chrome

**Comment by dustymc** [comment]
Well that was fun - should be patched into production.
