### ISSUE TITLE
identifiers display

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6011]
![Screenshot 2023-03-15 at 1 45 05 PM](https://user-images.githubusercontent.com/9099827/225451077-792e62d8-9542-4d0b-9584-603766a57500.jpg)
This is a problem. Will it be fixed? I'd like the identifiers display to be compact like it was before.

_Originally posted by @DerekSikes in https://github.com/ArctosDB/arctos/issues/6005#issuecomment-1470888482_

**Comment by campmlc** [comment]
Any way to toggle or choose between compact or expanded options, or have
the default be simple/compact view, and add an IDdetail like partsdetail?

**Comment by dustymc** [comment]
This is ongoing in a couple different ways, but I do have some answers.

We really need something that can carry full identifier-data, I reused 'othercatalognumbers' and relabeled it 'Identifiers.' I HAVE NOT rebuilt everything (hoping to get much more worked out before I invest a week of CPU, but I could kick that off at any time, or update bits and pieces, or whatever) but for those I have you can click the button....

<img width="120" alt="Screenshot 2023-03-15 at 2 58 36 PM" src="https://user-images.githubusercontent.com/5720791/225454135-ef729df9-cfee-46e1-9e86-cbc455e95ced.png">


to make them more readable.

<img width="493" alt="Screenshot 2023-03-15 at 2 59 03 PM" src="https://user-images.githubusercontent.com/5720791/225453337-a03ad75c-05ec-43c7-81e3-67bbde2f6061.png">

I'm not at all opposed to some "lighter" field (one which can't carry all the data we have in identifiers), I just need a name, recipe (what's included, how it's formatted and delimited, etc.), and some sort of light documentation (for the results customizer) describing what it is. Ideally that would happen with the above - it will also need a ~week of CPU (and running parallel with similar updates won't add much).

I'm hoping this process will eventually result in ~20 or fewer types that will be easy to treat as columns, but that seems to be stuck in a place that I'm having a lot of difficulty understanding (I think/hope it's just all one big understanding that we'll find a productive path through) and I'm not sure where we'll end up. In any case I don't think the data supports anything there now, but at some point I hopefully will be asking how to formulate that as well. (This also would ideally be included in the update, but that's probably just not realistic.)

**Comment by dustymc** [comment]
@campmlc not really toggle (although the json formatter sorta does that) but a second "compact" (simple? partial? summary??) column is I think about functionally equivalent.

**Comment by campmlc** [comment]
And the other option we discussed is a Download Identifiers tool under
Tools, like the Download Parts, -which both should be named Parts Table
View and Identifiers Table View or something that doesn't imply it only
functions to download. That way each ID and its metadata can be viewed and
downloaded as columns associated with the guid.

**Comment by dustymc** [comment]
I don't think that's an option, that's just something different. Open an issue - I need to know columns (should be obvious), label (for the dropdown tool) - what else? Tell me there....

**Comment by Jegelewicz** [comment]
If this worked like parts wouldn't you just be showing the values, then offer an "Identifiers detail" column that has all that mess?

And yes, I think we will need an "Identifiers download" option from the tools menu - I can create the issue (it is on my list)

Something else that just occurred to me is how we can select preferred identifiers - which may need an update to be able to account for using the issuer to "prefer" one?

**Comment by dustymc** [comment]
>just be showing the values

Technically plausible and this isn't an objection, but I think you're asking for things like "1; 1; 1; 1"??

>select preferred identifiers

That is (somehow...) tied in with my (vague...) ideas of what makes a "keepable" type: NK is above the bar because @campmlc needs it front-and-center, any of the recent hundreds are not because some vague handwavey thing towards some ambiguous ID isn't something that any curatorial-type sees as primary (or primary enough). (And "ambiguous" also isn't the key there, because truly unambiguous identifiers are self-typing.) Issuer offers a ready replacement for NK, but maybe not so much for eg collector number.

**Comment by Jegelewicz** [comment]
We can shorten the agent names using the label name type - I don't know if that is too much processing?

Instead of aka, put the acronyms in labels?

![image](https://user-images.githubusercontent.com/5725767/225457858-767ec2df-b24c-43a5-b8b4-f680c4c5360b.png)

**Comment by dustymc** [comment]
>too much processing?

I don't think that's a viable short-term solution, but it's not (entirely, I think, maybe) unrealistic longer-term.

That said, maybe we've got the names bass-ackwards and AMNH is a better preferred name anyway??

**Comment by Jegelewicz** [comment]
> AMNH is a better preferred name anyway?

Again, I don't think it matters except that we have set up preferred name to be something special and I don't think people will like it.

**Comment by campmlc** [comment]
Maybe for any identifier that already is in the code table with a prefix, eg most institutional IDs, we use the prefix as the label and preferred name? How many lack one?

**Comment by Jegelewicz** [comment]
@dustymc I'm not sure this is working as expected?

![image](https://user-images.githubusercontent.com/5725767/227226550-d1a10aea-134f-4c24-9ab8-2b9cf5eace94.png)

I was expecting something in Identifiers...

**Comment by Jegelewicz** [comment]
Also - "simple identifiers' doesn't really describe what's in there? That seems like "expanded identifiers" or something.

Sorry I didn't comment yesterday - I didn't think this would happen overnight.

**Comment by Jegelewicz** [comment]
Why is mine different?

**Comment by Jegelewicz** [comment]
Well Ok, now it seems good - that was weird?

![image](https://user-images.githubusercontent.com/5725767/227232807-b99a411b-dcd8-40a2-9156-ecd63a82d799.png)

**Comment by Jegelewicz** [comment]
> Elswhere we have "Parts" and "PartsDetail". Can we change this to "Identifiers" (simple) and "IdentifierDetail"? I'm sure everyone would prefer to have simple identifiers = Identifiers be the default.

I agree with all of that.

**Comment by dustymc** [comment]
>expanded display

I haven't refreshed that because we seem to be stuck in a weird place, but you can request refresh for specific records or I can SQL update or whatever.

>change this 

https://github.com/ArctosDB/arctos/issues/6017
