### ISSUE TITLE
Code Table Request - institutional catalog number 

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6012]
## Instructions

This is a template to facilitate communication with the Arctos Code Table Committee. Submit a separate request for each relevant value. This form is appropriate for exploring how data may best be stored, for adding vocabulary, or for updating existing definitions.

Reviewing documentation before proceeding will result in a more enjoyable experience.

* [Issue Documentation](http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html)
* [Code Table Documentation](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html)
* [Video Tutorial - Submit a Code Table Request](https://youtu.be/t2jHbsRA3lk)

------------------------------

## Initial Request

**Goal**: Describe what you're trying to accomplish. This is the only necessary step to start this process. The Committee is available to assist with all other steps. Please clearly indicate any uncertainty or desired guidance if you proceed beyond this step.

~~institutional catalog number should go away~~
institutional catalog number needs a better definition but perhaps we can simplify and just use the word "catalog"?

**Proposed Value**: Proposed new value. This should be clear and compatible with similar values in the relevant table and across Arctos. 

~~[identifier](https://github.com/ArctosDB/arctos/issues/6005)~~

catalog
(This is an identifier type - so we shouldn't need to add terms like "number" or "identifier". By inclusion in this code table, these things are already considered identifiers.)

**Proposed Definition**: Clear, complete, non-collection-type-specific **functional** definition of the value. Avoid discipline-specific terminology if possible, include parenthetically if unavoidable.

The unique identifier for a particular item or group of items within the collection catalog of the issuing agent. 

**Context**: Describe why this new value is necessary and existing values are not.

~~Check any of the very many recent identifier-involved issues; type is almost never used consistently. "Typing" anything to which this could apply adds confusion, not clarity.~~

We can stick with institutional catalog number if everyone prefers it - I'm just making a suggestion that would take up less space and I think still gets the point across.

**Table**: Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table or value. This may involve multiple tables and will control datatype for Attributes. OtherID requests require BaseURL (and example) or explanation. Please ask for assistance if unsure.

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type

**Collection type**: Some code tables contain collection-type-specific values. ``collection_cde`` may be found from https://arctos.database.museum/home.cfm

**Priority**: Please describe the urgency and/or choose a priority-label to the right. You should expect a response within two working days, and may utilize [Arctos Contacts](https://arctosdb.org/contacts/) if you feel response is lacking.

**Available for Public View**: Most data are by default publicly available. Describe any necessary access restrictions. 

**Project**: Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

**Discussion**: Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

## Approval

All of the following must be checked before this may proceed.

The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality).

- [ ] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [ ] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection

If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc. 

1. Can a suitable solution be found here? If not, proceed to (2)
2. Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)
3. Take the discussion to a monthly Arctos Working Group meeting for final resolution.

## Implementation

Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made.

Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel. 

Make changes as described above. Ensure the URL of this Issue is included in the definition. 

Close this Issue.

**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result.

## Special Exemptions

In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases.

1. Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step.
2. The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology.

**Comment by Jegelewicz** [comment]
Are you trying to start a war?

**Comment by Jegelewicz** [comment]
I mean - I agree, but we gotta take the baby steps!

**Comment by campmlc** [comment]
MSB personnel disagree with eliminating this identifier. @AdrienneRaniszewski @catherpes @jldunnum @msbparasites @jtgiermakowski. It functions to distinguish between valid institutional identifiers and random values. There may be issues with random values being associated with this ID, but those can be found and fixed. 
Propose using this ID for catalog numbers, however they may be locally defined, in the sense of the record ID that would be cited in a publication for the institution. It should encompass both institution and collection code information when possible.

**Comment by dustymc** [comment]
No wars!! 

I'm trying to find a definition, at least to start. To me, it looks like we have a bunch of arbitrary things. I'm pretty sure that's not the view for others. Can we get on the same page? This is an attempt to do so.

>random values being associated with this ID, but those can be found and fixed.

Thanks, that's a good place to start. I contend that they cannot (and I think a bunch of the cleanup concerns in recent issues support that). There is meaning behind types; they should exist when they add value. If I find something in the THING-A "slot" I will always assume it's there because someone purposefully put it there. If there's some tendency for users to misfile, then we've got too many THINGS, or unclear definitions, or ???? - some problem, which I hope to find and fix here.

**Comment by Jegelewicz** [comment]
Based upon community needs, I suggest we keep this, but the definition should be:

An alphanumeric catalog number applied to an object by an institution.

**Comment by dustymc** [comment]
>by an institution.

So are we promoting [Ken](https://github.com/ArctosDB/arctos/issues/5927) or ???????????

>community needs,

Can that somehow be clarified/qualified/? I clearly do not understand the need, and minimally would like to have something by which to judge the next identifier type request.

**Comment by dustymc** [comment]
>issuing agent's collection catalog.

How's that not a collector number??

**Comment by campmlc** [comment]
We should include that this is the  identifier used for citations. There has to be a publication somewhere that documents this.

**Comment by dustymc** [comment]
>, the "collection" means an action

Maybe, but I don't care - the functionality of the type (if I'm understanding @acdoll ) is that it tells me to find data in the agent's collector book (or catalog, or ledger, or whatever that individual wants to call it). If they do stuff that's not "collecting" (whatever that means...) and record it in that same thingee then it should still get the type of identifiers that leads me to that particular kind of book-thing (or THEIR book with the agent component). 

So I guess following that, if they have an "institutionalizor ledger/catalog/book/whatever" then we need this identifier for that? The point isn't that there's an entity (the institution) involved, but that they have a "book"??? (So we're looking for some level of organization?????)

>"a group of stuff that I keep together for a reason".

So if I have a reason I'm involuntarily promoted to institution? I'm so confused....

Since it keeps being handy, what about KWP - it's no longer kept together so ???

This still seems like we're all struggling - unsuccessfully - to find some line in the sand that just doesn't exist.

>the identifier used for citations

ALL identifiers can be (and unfortunately are from time to time) used for citations - I don't think this is a distinguishing characteristic.

**Comment by catherpes** [comment]
And we're not doing this for plumbers and lacrosse players and interior decorators. we're doing this for Museum Professionals who should have a clue what an institutional catalog number is supposed to represent. Context is important.

**Comment by dustymc** [comment]
>The catalog number

If you mean the identifier assigned by Arctos collections, that is a different structure/thing.  (And that - ideally in resolvable and globally unique form - is what SHOULD be used for citations.)

> the one number that a given entity

Yep, that's not this, that's "our" sacred identifier. This issue refers to various things that couldn't be more-appropriately sorted.

['Use this only if you don't know what institution or collection might have assigned the number.'](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type#institutional_catalog_number) (I'm relatively sure that's from the Arctos ABQ - not Sevillita - pow-wow - so this idea is at least ~15 years old.)

Here's the data

[temp_institutional_catalog_number.csv.zip](https://github.com/ArctosDB/arctos/files/11032453/temp_institutional_catalog_number.csv.zip)


and summary

```

  guid_prefix  | numrecs 
---------------+---------
 ACUNHC:Bird   |     158
 ACUNHC:Ento   |    1268
 ACUNHC:Fish   |      82
 ACUNHC:Herp   |     227
 ACUNHC:Inv    |    1353
 ACUNHC:Paleo  |      40
 ALMNH:Mamm    |    2374
 ALMNH:Paleo   |       4
 APSU:Herp     |   11338
 ASNHC:Bird    |       7
 ASUMZ:Bivalve |    9042
 ASUMZ:Mamm    |      42
 BYU:Herp      |      60
 BYU:Teach     |       2
 CHAS:Bird     |       9
 CHAS:Herb     |      51
 CHAS:Mamm     |      51
 CRCM:Bird     |   16721
 CRCM:Fish     |    2480
 CRCM:Herp     |    5691
 CRCM:Mamm     |   36739
 CRCM:Paleo    |     115
 DGR:Bird      |    2141
 DGR:Ento      |      35
 DGR:Mamm      |     695
 DMNS:Bird     |       6
 DMNS:Inv      |       1
 DMNS:Mamm     |      10
 KNWR:Ento     |      15
 KNWR:Herb     |       3
 MLZ:Bird      |       1
 MMNH:Bird     |       1
 MSB:Bird      |      27
 MSB:Fish      |    2022
 MSB:Herp      |     410
 MSB:Host      |     268
 MSB:Mamm      |   24848
 MSB:Para      |     204
 MVZ:Herp      |      38
 MVZ:Mamm      |       4
 NCWRC:Fish    |       1
 NCWRC:Mamm    |       2
 NMMNH:Mamm    |    5984
 OWU:Bird      |       1
 OWU:ES        |       2
 UAM:Bird      |      11
 UAM:Ento      |       3
 UAM:ES        |     120
 UAM:Fish      |       2
 UAM:Herb      |     119
 UAM:Inv       |       4
 UAM:Mamm      |       1
 UAMObs:Ento   |    1043
 UCM:Bird      |      75
 UCM:Fish      |      28
 UCM:Herp      |      29
 UCM:Mamm      |     523
 UMNH:Mamm     |       4
 UNM:MET       |   10258
 UNR:Fish      |     119
 UNR:Mamm      |     153
 UTEP:Bird     |       4
 UTEP:Ento     |       1
 UTEP:Herb     |       6
 UTEP:Herp     |       5
 UTEP:Inv      |      34
 UTEP:Mamm     |       1
 UWBM:Herp     |      22
 UWBM:Mamm     |     398
```

**Comment by campmlc** [comment]
Agree with @catherpes. This number should be used in the same way we use guid in Arctos collections - as the number assigned by a museum collection as the official number to be cited in publications. The only difference is that the institution is not in Arctos.

**Comment by catherpes** [comment]
27/48,600 (soon to be 49,600 when I get the next bulkload done) is well below my threshold for MSB:Birds

**Comment by Jegelewicz** [comment]
> it's no longer kept together 

Whether it is still in the collection or not isn't the point, the point is that the collection assigned it an identifier and recorded that number in it's catalog.

**Comment by dustymc** [comment]
>This number should be used in the same way we use guid in Arctos collections

Anything that approximates that **will not** be involved in this.

That aside, **if we knew even the institution then this type would not have been used**. These are (assuming documentation is being followed, which is the best-case scenario!) things like "3" - that is it.

(Actually many of them aren't that informative - there's a big block of things like...

```

 MSB:Mamm:207807        | MSB:Mamm      | institutional catalog number | SSUC M -                                           | self
 MSB:Mamm:206555        | MSB:Mamm      | institutional catalog number | SSUC M -                                           | self
 MSB:Mamm:207810        | MSB:Mamm      | institutional catalog number | SSUC M -                                           | self
```
).

>by a museum collection

Again, in an attempt to understand this, that then excludes KPW (and I suppose anyone else who does the same things that a museum might do while not calling themselves a museum).

>assigned it an identifier and recorded that number in it's catalog.

https://github.com/ArctosDB/arctos/issues/6012#issuecomment-1478066413

**Comment by campmlc** [comment]
There is some fundamental misunderstanding going on here. 
I believe most Arctos operators would consider "AMNH:American Museum of Natural History" as some sort of catalog number assigned by the collection for the purposes of citation - we just don't know the collection. If we know the collection, we have: "AMNH:Mamm" - which specifically designates an institutional guid prefix as a catalog number. 
Under the new model - what exactly do you propose using for the ID type for this latter situation, if not institutional catalog number? To be honest, "catalog number" is preferable, but apparently using that breaks something in Arctos.

"Identifier" is not acceptable. We need some value that we can use to explicitly designate the catalog number of an institution. If we have citable catalog numbers in non-museum collections, then let's broaden the definition. If there are weird things like SSUC-M being used - I'm assuming that references a museum catalog number, and we need to find out what that institution is. If it turns out that it isn't a catalog number as we define it, we can change the ID types for those values. But I honestly don't understand why keeping "institutional catalog number" or something equivalent to designate formal institutional identifiers for collections outside of Arctos is even remotely a controversial subject.

**Comment by campmlc** [comment]
SSUC - M: 
Colección de Flora y Fauna Profesor Patricio Sánchez Reyes (SSUC),Departamento de Ecología, Pontificia Universidad Católica de Chile, Santiago, Chile

**Comment by campmlc** [comment]
> So I guess following that, if they have an "institutionalizor ledger/catalog/book/whatever" then we need this identifier for that? The point isn't that there's an entity (the institution) involved, but that they have a "book"??? (So we're looking for some level of organization?????)

Yes! There is a formal collection being maintained according to collection management best practices - there is a formal "book" , or there used to be (we have ours in a safe, as do most collections), there definitely is some level of organization - these are, in the vast majority of cases, institutionally assigned identifiers that are MEANT TO BE unique identifiers for the collection/institution, frequently assigned by institutional registrars to prevent duplicates and track permits and legal issues. They differ from "collector numbers" in that they are issued by an institution or collection as part of a formal process, usually after some sort of institutional accesssion process whereby the institution takes formal ownership.  
https://cool.culturalheritage.org/byorg/spnhc/spnhc1.html : 
https://www.natsca.org/sites/default/files/publications/books/Vertebrates.pdf
https://collectionstrust.org.uk/wp-content/uploads/2016/11/Standards-in-the-museum-care-of-biological-collections.pdf
6.3 Each accession and (where appropriate) each individual specimen must be marked or
labelled with an unique accession or inventory number. Such marking must not
damage the specimen or obscure features of taxonomic importance. Any previous
marking must be preserved or recorded, and all old labels must be preserved. The
documentation system must ensure that the links between individual specimens and
all associated data are maintained.
6.4 A catalogue must normally be maintained, bringing together all the primary
information about each item or group in the collection.

> Can that definition (or something like it) be quantified in such a way that we know what gets these kinds of identifiers, and what needs something else? I keep bringing up KWP because it seems to cross whatever lines get drawn: Is it or is it not this, and why?

It appears that we have collections in Arctos that are given guids but are not formal institutions? Is that what this refers to? Is KWP a collection, and were the numbers assigned as a permanent identifier to be in used citations? Was it a research collection that was adopted as a special collection by a formal institution? Would it work if we amend the definition  to reference a formal, unique number assigned by a collection (as a **noun**, not as a verb?)

**Comment by campmlc** [comment]
@DerekSikes

**Comment by dustymc** [comment]
I don't think I can write the definitions, but I do think I can (or nearly can) see the distinction. (It's not functional in any way I can see, but maybe that's just me being too idealistic.)

>formal collection

KWP was just some crazy guy with a garage full of butterflies when it came into Arctos,  I'd not call that formal and I'd definitely be willing to go less-formal under the right circumstances.

I think the biggest deciding factor was Ken's relationship with the museum community: it was always assumed that the material was and would remain available for research, and it has. "Researchey"....

"Collection" is the right idea (and maybe that's enough, given the audience).

>by a formal institution?

Nope.

>best practices

Drop that, a fair bit of the stuff in Arctos is in Arctos because of absolutely terrible practices that fortunately lead to things bearing this type of identifier being adopted by other collections.


>unique identifiers

Nope, not even at very small scales, this should not collide with reality.

> formal, ~~unique~~ ~~number~~ identifier assigned by a collection

maybe with some sort of a working elaboration of "collection" - I think??? (Or my brain is GUMmy mush, not sure at this point...)

**Comment by Jegelewicz** [comment]
Suggest we change this and develop some sort of consistent naming convention for types (XYZ number)

catalog number - A unique alphanumeric identifier (ideally) that a given agent (be it an institution or personal collection) has assigned to a cataloged entity and is the number most traditionally requested to be used by museums/collections for citations.

**Comment by Jegelewicz** [comment]
> but no matter how organized they are, research collections may be abandoned on the death or end of career of the individual;

I am pretty sure this has happened with museum collections. Do we want the type to carry the baggage or can we let the agent you pick do that?

**Comment by campmlc** [comment]
If we don't draw the line between an official institution, extant or not,
and an individual - then we have no reason to distinguish any number from
any other. Collector numbers are equivalent to catalog numbers. And I
disagree strongly with that.

**Comment by Jegelewicz** [comment]
Don't shoot the messenger - I just combined what we had with @catherpes https://github.com/ArctosDB/arctos/issues/6012#issuecomment-1478402723 and @ewommack suggestions https://github.com/ArctosDB/arctos/issues/6012#issuecomment-1478391188

if we plan to keep "institutional", then we probably also need "personal", which seems to belled into "collector" if we don't have good definitions. Feel free to write up something, because I am having a difficult time.

**Comment by Jegelewicz** [comment]
@ArctosDB/arctos-code-table-administrators @campmlc @catherpes @ewommack 

Please read the [initial post](https://github.com/ArctosDB/arctos/issues/6012#issue-1626360302) again - it has been edited based upon discussion in the AWG issues meeting today. Post your thoughts here. Thanks!

**Comment by ewommack** [comment]
Ok so the proposal now if to have the term be:
catalog

and the definition to be: 
The unique identifier for a particular item or group of items within the collection catalog of the issuing agent.

Do I have that right?

If you have multiple catalog numbers assigned by different agents, then is that ok with Arctos? This would pull the identifier to the same level as a person's catalog, so you could have for some museums one catalog number assigned by a specific person, and then have another catalog number that was assigned by an institution for the same object.

**Comment by campmlc** [comment]
My understanding is that we cannot use "catalog number" because it is already in use in Arctos @dustymc ?
And that is why we have institutional catalog number.
But the proposal as I understand it is to limit this specifically to museum collections outside of Arctos - and ideally, it would be associated with the most specific institutional agent possible - e.g. American Museum of Natural History Mammalogy. 
Collector number and preparator numbers would be separate values, as would National Park Service Catalog and National Park Service Accession.

**Comment by dustymc** [comment]
>multiple catalog numbers assigned by different agents, then is that ok with Arctos?

Absolutely - institutionA gave it a number then sent to to institutionB who gave it a number and then sent it to ....

>This would pull the identifier to the same level as a person's catalog,

Yes, exactly, people keep coming to that apparently-inevitable conclusion and then wishing they hadn't and deciding the world needs more arbitrariness, or something.....

> so you could have for some museums one catalog number assigned by a specific person, and then have another catalog number that was assigned by an institution for the same object.

Yes, but that's obviously not the limit either - it might also bear the same agent's preparator number, and an identifier from That Same Institution, That Division, Some Weird Subdivision, and a previous identifier from a now-merged collection in the same division, and - WHATEVER, there's no limit here, and agents can clearly carry more complexity than types so it's easier to understand such complex paths (eg by following Agent Relationships).

>cannot use "catalog number" because

That's mostly a social problem, but yea, we've demonstrated many times that shared names find ways to be nuisances, at best.


>And that is why we have institutional catalog number.

To be clear: This still looks artificial to me. We have no functional definition, I can see no reason (other than 'causing chaos') for such things to exist. I'm happy to use this anyway if it lets us get through the giant mess (and that is what the AWG agreed to, and I intend to get started today).

>as would National Park Service Catalog and National Park Service Accession.

That has gone back and forth so many times, I'm getting dizzy....

**Comment by ewommack** [comment]
So let's stick to institutional catalog number. 

That's clearer than "catalog". There will be other types of catalogs we may need to distinguish, but if this is for use by data entry to distinguish the number assigned is the catalog number assigned by a specific institution, it definitely makes sense. 

A institution may assign other types of numbers as well, but the collections catalog number will be something we definitely want to be able to distinguish.

**Comment by dustymc** [comment]
Nope, that should be something different (THE catalog number, not an "other identifier" of any type, I think) - give me specifics (url, description,??) and I can give you a better answer.

**Comment by Jegelewicz** [comment]
catalog number was never in [this code table](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type) or if it ever was it was a loooooong time ago.

**Comment by ccicero** [comment]
I thought I had used it recently for a loan item bulkloader but the recent files I have use the GUID.

**Comment by campmlc** [comment]
We used to have it in some form, maybe the bulkloader, but it's been a long time.

**Comment by dustymc** [comment]
[Not for (too) long!](https://github.com/ArctosDB/arctos/issues/4171)

**Comment by campmlc** [comment]
I just found data entry records in various divisions at my institution using institutional catalog number for the new guid format for the arctos guid url. This would make sense to most people, as it obviously did to these collections, and it makes sense to me too, in the current absence of a way to distinguish that the arctos guid urls are specifically a catalog number in Arctos. Using "identifier" is confusing.  "Catalog numbers" in Arctos ARE explicit - there is no guessing as to whether the number from another instition is or is not one. We need some way to flag the Arctos catalog numbers if we are going to enforce loan requirements to "cite in this format" and make our guid urls explicitly what we want cited and searched. Some random url "identifier" is not going to do this, even for people who might understand what an Arctos guid actually is.

**Comment by mkoo** [comment]
This proposal is old. I think the comments show the direction of the conversation, and I'd prefer not to complicate our work by a new term especially I since I dont see a strong justification for it.

In the original post, Dusty wrote:
"We can stick with institutional catalog number if everyone prefers it"

I think we're sticking with ``` institutional catalog number```

Definition suggestions welcome but I suggest one without confusing references to issuers, agents etc (complements DwC):

>An identifier, preferably unique, for a record within the catalog, ledger, or other collection of an institution or other collection.

If I get a bunch of thumbs up can we proceed with a modified definition?!

**Comment by dustymc** [comment]
This still looks like a simple denormalizer to me; there's no functional differentiation between https://arctos.database.museum/info/ctDocumentation.cfm?table=CTCOLL_OTHER_ID_TYPE#institutional_catalog_number and https://arctos.database.museum/info/ctDocumentation.cfm?table=CTCOLL_OTHER_ID_TYPE#identifier, they're used interchangeably, and the inevitably-arbitrary usage can only serve to hide data.

Something like...

|type|value|issuedby|
|----|----|----|
|institutional catalog number|1|[Museum of Southwestern Biology, Division of Mammals](https://arctos.database.museum/agent/1014691)|
|identifier|https://arctos.database.museum/guid/MSB:Mamm:1|NULL|

... might make sense (for reasons that I can't quite grasp at the moment), but that's not what's been proposed nor how these are being used.

**Comment by mkoo** [comment]
Points noted! I think this has been played out for now. Without a strong rationalization to implement anything for the moment, I am closing this issue. We can revisit in the future if needed.
