### ISSUE TITLE
Add issued by and remark to Identifer download table

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6013]
https://arctos.database.museum/tools/identifier_download.cfm?table_name=api_jegelewicz_20230315050331121_137

![image](https://user-images.githubusercontent.com/5725767/225458556-5c66e521-fae1-4882-81b7-98e678079045.png)

**Comment by Jegelewicz** [comment]
Adding wildfire because - well people will want this and we need it to facilitate buy-in for new identifier model.

**Comment by dustymc** [comment]
Hey, that's neat, who wrote it?! (@campmlc nevermind apparently this already exists...)

**Comment by Jegelewicz** [comment]
Yeah - I went to get parts table download as an example and there it was....

**Comment by campmlc** [comment]
Any way we can change the names to Identifier Table View and Parts Table View?  Download has already been documented to cause confusion, and there are previous requests for this.

**Comment by dustymc** [comment]
> change the names 

Uhh - sure. In production in 10....9.......

>previous requests

Here's a whine, in case you haven't heard enough of that from me today: we're not good at focusing requests, things get addressed in the strangest places, someone will complain about what I just did and I'll never find this to point them at, and now there's probably some abandoned issue (or 17...) requesting this out there somewhere. (Find a close them prettyplease if you want...) Help??

**Comment by campmlc** [comment]
Will try to find, thanks!
