### ISSUE TITLE
search results customization data

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6017]
get CSV for @mkoo

**Comment by dustymc** [comment]
remove (most) distinct identifiers

**Comment by mkoo** [comment]
Related to the same flyout window's usablity so I'm piggybacking here: 
See the current window:
![Firefox_Screenshot_2023-03-16T23-31-17 471Z](https://user-images.githubusercontent.com/2523089/225777383-418878f9-f819-480d-85c5-61bea50f89fc.png)

1) Suggested replacement text for the top of window:
Use this form to select fields to be included in your results. Use the "drag" field to reorder the displayed fields (drag with mouse). Are you trying to increase the number of returned results (record limit)? Then select fewer fields or fields with lower costs. 
 
2) reduce font size of last three fields

**Comment by campmlc** [comment]
Suggest making a link to the definition to reduce all the clutter. Get rid
of default order column.

**Comment by Jegelewicz** [comment]
> Would "grip dot" icon help? I dont remember if we are using font-awesome here but something like <i class="fa-solid fa-grip"></i> (https://fontawesome.com/icons/grip?s=solid&f=classic) along with the word 'drag'?

I think the three line thing is used for "drag" fairly often, however, in edit classification we use  [ drag handle ]

![image](https://user-images.githubusercontent.com/5725767/226383283-8fe396d7-3ea3-4b11-9e82-2f634cae14ae.png)

Let's be consistent no matter what we choose.

**Comment by dustymc** [comment]
Closing; data has changed dramatically for https://github.com/ArctosDB/arctos/issues/6097, I can provide current data in a new Issue upon request.

Suggest the UI comments be addressed to https://github.com/ArctosDB/arctos/issues/6096
