### ISSUE TITLE
Send Search Results as email attachment

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#6018]
this needs more investigation but posting to track. Addresses the need to access large query result sets with many fields (say more than 500 records). Instead of hitting the limit of returned records with many result fields, users would have the option of having the results emailed as zipped csv with their choice of fields. 
 
things to figure out:
- appropriate email service that can handle attachments
- hard cap of # records that can be emailed  (e.g., 1M?)
- PG job scheduling to balance request load
- other resource needs

**Comment by dustymc** [comment]
Is an email with a download link better than an attachment?

Are there any security concerns with this? (I think yes lots??)

**Comment by campmlc** [comment]
Would the link cause problems with flagging for spam/phishing?

**Comment by mkoo** [comment]
>Is an email with a download link better than an attachment?

maybe-- either way might cause flags so we can make sure people check spam. If its the same known Arctos email address hopefully they have cleared it for their mail box

**Comment by dustymc** [comment]
<img width="398" alt="Screenshot 2023-04-11 at 1 56 13 PM" src="https://user-images.githubusercontent.com/5720791/231286191-c6d48848-9c59-4273-a133-27c0510ee6dd.png">

I'm calling this in next release (probably tonight), but there's still a lot of room for improvement.

This is limited to "us" (users with coldfusion_user) at the moment - going beyond that would open a big can of security worms that I have no way of addressing at the moment.

This can probably be used to melt Arctos, although I haven't been able to do so.

There are probably some query terms which will break something, but I haven't been able to do that either.

This can still time out (hopefully right before melting Arctos) - there are still limitations, even though they're orders of magnitude more liberal than the 'live' form can allow.

The post-processing download (and almost certainly a few of them requested simultaneously) can probably be used to melt Arctos.

There's no record cap on this, and that's not a great metric - 4.5M guids is way cheaper than 20K 'check alls'. (Both can still melt Arctos, but in different ways!)

I think I've done what I can until some experience comes to exist; please reopen this or file a new Issue if something could be improved.
