### ISSUE TITLE
Collection-type specific Customizations for everyone

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#6021]
Arctos has a lot of subpopulations of users so let's make the search and result customizations easier for everyone (also, speaking for myself, I switch between cultural and bio collections a lot so one click swapping is ideal!)

So I think we're proposing to add some new buttons at the top of both Customize Forms (Search and Results) where we can have basic EH, ART, Mamm, Bird etc profiles (Maybe even in a dropdown menu where selecting one profile automatically selects the corresponding fields, which then could be further customized)
![Firefox_Screenshot_2023-03-17T16-53-39 826Z](https://user-images.githubusercontent.com/2523089/225969912-9a327e18-7f49-4521-93f7-d7fca73eb38d.png)

We have the EH and Art already created so if we can start those perhaps we can then work on the others.

I suggest we mull this over and discuss in a UI meeting since there are two components here-- the Search Customization and Results Customization. Do we want them tied together or not? (ie selecting one profile then selects the fields in the other one?) Do we need a Vert version or do we need separate for each collection-type? 

This will potentially address many many user issues about the new search UI

**Comment by campmlc** [comment]
This is a great idea. I like the idea of a profile with Search and Results Customization tied together, and also the idea of dropdown menu where selecting one profile automatically selects the corresponding fields, which then could be further customized.

**Comment by dustymc** [comment]
>EH and Art already

Note that those are single collections, not general "discipline portals."

>Search Customization and Results Customization. Do we want them tied together or not? 

That was discussed at some length in the issue that lead to the current form. They are linked.

>Do we need a Vert version 

I don't care, but some idea of the scope would be useful. These are hard-coded in right now, if we're going much past ~a dozen (and certainly if this turns out to be a way to encompass https://github.com/ArctosDB/arctos/issues/5661) I'll want to do something more sophisticated.

I'll go next task for adding the selector.

**Comment by mkoo** [comment]
related #5624

**Comment by ebraker** [comment]
This would be great, especially given that operators must be logged out to search other collections (losing query and results customizations) and therefore I find myself having to rebuild the forms way more often than I want. I'm guessing a basic collections-based default would likely cover most of my needs vs. starting from scratch every time.

**Comment by mkoo** [comment]
```Profiles``` new functions in search page are in production
