### ISSUE TITLE
Part Attribute bugs working on iPad

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#6022]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
When editing a Part or Part Attribute free-text field on an iPad, you can't change the field size (there's no re-sizing corner to grab). This makes it impossible to enter, edit, or read a condition report or any piece of information that takes up more space than ~22 characters in many of the fields in the part / part attribute window.

**Screenshots**

![IMG_0C31690D5FDD-1](https://user-images.githubusercontent.com/17605945/226020023-952fc9ce-1f73-4ec3-874f-c9a1640ca9b5.jpeg)

![IMG_6D4A14769E7E-1](https://user-images.githubusercontent.com/17605945/226020098-05aa8e91-82bd-4b86-94d4-77cb9c0ab8c5.jpeg)

Also needs to be de-specimened (not sure if #5340 is the right one but tagging it anyway).

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] iOS 16.3.1 iPad Pro
 - Browser [e.g. chrome, safari] Safari

**Priority**
High priority - sometimes only an iPad is available to do work in the collections range - causing an interruption in work flow to have to make changes back at my desktop.

**Comment by Jegelewicz** [comment]
@AJLinn can you install Firefox on the iPad?

**Comment by AJLinn** [comment]
I can try that.
I was using Brave and it did the perpetual-load at the search window.

**Comment by AJLinn** [comment]
![IMG_54E13ECB9B42-1](https://user-images.githubusercontent.com/17605945/226432435-2aa93b91-a954-4f1c-8491-6363f65e6d93.jpeg)
Just the same as Safari. No expando-corners.

**Comment by dustymc** [comment]
I can't make this work, it seems that ios/safari is just outright ignoring the standard.

**Comment by AJLinn** [comment]
I will let my staff & students know the iPad should be used for limited purposes then, and all editing of records should be done on a standard Mac OS not iOS. Totally fine in my view given our limited ability to support any standard besides Firefox. I agree we should be sure to note that on our system page.

**Comment by AJLinn** [comment]
I'll close with the assumption that Apple is not going to play properly with Arctos and that's just the way it is.
