### ISSUE TITLE
Curatorial Search Request - Arctos-wide statistics

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#6029]
I need a few additional stats not listed on the system statistics page to include in some figures. These will all be system-wide:

1. Barcoded items (sum total across collections and container types)
2. Loans in arctos (sum total across collections and loan types)
3. Cited records (Arctos wide)

**Comment by campmlc** [comment]
Cool!

**Comment by ebraker** [comment]
SQL I can handle! ;)

**Comment by ebraker** [comment]
@dustymc can you run these again please? I'm updating these stats for the Arctos paper 

arctosprod@arctos>> select count(*) from container where barcode is not null;
  count  
---------
 3503825
(1 row)

Time: 717.202 ms
arctosprod@arctos>> select count(*) from loan;
 count 
-------
 12759
(1 row)

Time: 14.559 ms
arctosprod@arctos>> select count(*) from loan_item;
 count  
--------
 858504
(1 row)

Time: 100.065 ms
arctosprod@arctos>> select count(*) from citation;
 count  
--------
 430658
(1 row)

Time: 37.298 ms
arctosprod@arctos>>

**Comment by dustymc** [comment]
```
select count(*) from container where barcode is not null;
select count(*) from loan;
select count(*) from loan_item;
select count(*) from citation;
```
arctosprod@arctos>> select count(*) from container where barcode is not null;
  count  
---------
 3747810
(1 row)

Time: 531.646 ms
arctosprod@arctos>> select count(*) from loan;
 count 
-------
 13506
(1 row)

Time: 5.080 ms
arctosprod@arctos>> select count(*) from loan_item;
 count  
--------
 898037
(1 row)

Time: 76.547 ms
arctosprod@arctos>> select count(*) from citation;
 count  
--------
 438881
(1 row)

**Comment by ebraker** [comment]
@dustymc Thank you!
