### ISSUE TITLE
I broke portals

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6034]
@AJLinn @krgomez I'm sorry but I (partially) broke your search portals last night - I ended up dropping the 'data' bit of portals so that I could generalize and share them.

I set up some redirects, which should be easy to maintain no matter what crazy thing we do to the UI going forward. Can you please update any links to use

https://arctos.database.museum/uamart and https://arctos.database.museum/uameh ? (And let me know if you want something else, most anything that's not an actual link to an Arctos page should work.)

The old links still work, but will have stopped filling in collection.

Sorry for the continued interruptions, hopefully this gets things stable. (And I haven't forgotten about the requested changes to UAM:Art!)

**Comment by AJLinn** [comment]
Fine for me! I'm updating my links now.
