### ISSUE TITLE
Dealing with offensive terms in common names

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6040]
Today @ArctosDB/diversity-and-inclusion discussed ways for handling offensive terms in common names. A resource found by @ewommack suggests placing the offensive term in quotes and appending [offensive historical name]. See https://github.com/ArctosDB/internal/issues/246#issuecomment-1478676063

Our goals for offensive common names include:

1. Searches using them should find what is expected.
2. The offensive names should not display on catalog records.
3. The offensive names should appear on the taxon page, but should be designated as offensive historical common names.

We tested some options on https://arctos.database.museum/name/Clangula

Let it be known that quotes break the common name. The term will save, but when you return to edit it, the field is blank.

In any case, anything that precedes the name adds the requirement of preceding a search for it with % if one expects to find anything. And not using some sort of preceding comment or character means the offensive names will not sort together.

Given this, we see two possible options:

1. A second “type” of common name: offensive historical common name - A common name previously applied to the taxon that is offensive and other common names should be preferred. 
2. A flag on common name that
 - prevents the name from appearing in catalog records
 - groups the offensive names on the taxon page and separates them from the acceptable names

Other ideas are appreciated! We feel that once we have a solution, we can begin to make taxonomy more inclusive!

**Comment by ewommack** [comment]
Ooops created the same issue: https://github.com/ArctosDB/arctos/issues/6041

**Comment by dustymc** [comment]
Common names are clearly overloaded. Moving them to classifications would support this, fix https://github.com/ArctosDB/arctos/issues/5025, make https://github.com/ArctosDB/arctos/issues/4815 irrelevant, etc.

**Comment by ewommack** [comment]
Questions to help understand what you are suggesting:
How would classifications appear in taxonomy? 

How would classifications appear on the cataloged record page?

**Comment by ewommack** [comment]
> I guess we could create a new source = Arctos Common Names that includes no classification term stuff, just metadata that are a long list of taxon term type (non-classification) = common name?

There may be some resources which might be able to help with these, at least for some geographic areas. Some of the societies do publish accepted common name lists for different taxonomy, and there are committees that are tackling offensive and racial language. That might take time though waiting on outside committees, but it could also provide us with sources to use and reference.

**Comment by dustymc** [comment]
> clones in a classification to the Arctos source from GBIF 

I can't wrap my head around why you'd ever do that, so maybe??

>updates [Lota lota](https://arctos.database.museum/name/Lota%20lota) using the classification bulkloader I

You cannot. You can update a source at that name. Nobody should be destructively managing classifications that they don't solely control, whatever the contents of them.

>create a new source = Arctos Common Names 

That seems like a decent "lets get this started" bandaid (one which would maintain current functionality while removing some complexity - and limitations).

> this would remove all those common names from the catalog records

There's an Issue, this problem isn't that specialized.

>Taxon Term = common name is

Habitual pigeonholes are used to not finding stuff! If you KNOW what you're looking for, that'll find it. If you just want burbot, then just search burbot and don't worry about how it's been typed.

> really messy proposition

Absolutely not, it's the opposite! You can't use table common_name to assert 'spikey weird mammal-thingee' for https://arctos.database.museum/name/Echidna without also including viruses and eels. As classifications, that's not all confounded.

**Comment by Jegelewicz** [comment]
I am not seeing something and I will need a demonstration of your proposed solution before I can understand what you are suggesting we do.

**Comment by dustymc** [comment]
>not seeing something

It's just a nonhierarchical (probably...) classification term. It would act like all the other nonhierarchical classification terms, like remarks. If you want to see something different (eg treat it more like family than remarks) then there'd be an issue spelling out what exactly you want to see and where, and if that's technically plausible we'd make it so. Here I gave two terms two labels, so it would be possible to treat one of them differently than the other.

>demonstration

https://arctos-test.tacc.utexas.edu/guid/UAM:Fish:8627
https://arctos-test.tacc.utexas.edu/name/Carcharodon%20carcharias#Arctos

**Comment by dustymc** [comment]
merge -->https://github.com/ArctosDB/arctos/issues/7832
