### ISSUE TITLE
Help needed: picking Higher geography

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#6043]
What am I doing wrong? Please help.

In a catalog record, I am using Fork-Edit to create a new event, which I'm creating in the background of this pop-up.
I used to be able to enter my basic info and then click on the Higher Geography "pick" button, enter a higher geography (like a quad, census area, or county) and then a number of choices would come up in the bottom and I'd pick the one that had a mappable capability (if possible).

Now I go to Pick Geography, enter "St. Lawrence" into the Higher Geography and I get nuttin'

What's the dealio? Can someone please educate me on what the new right way to do this is?
<img width="2021" alt="Screenshot 2023-03-21 at 4 13 03 PM" src="https://user-images.githubusercontent.com/17605945/226769671-1c8b6ed9-2b21-409b-adc8-cb8a49c460e1.png">

Thanks in advance for the help.
Signed, Frustrated in Fairbanks 🥺

**Comment by dustymc** [comment]
See https://github.com/ArctosDB/arctos/issues/5138 for background, https://arctos.database.museum/place.cfm?sch=geog&state_prov=Alaska&valid_catalog_term_fg=1 for "assertable" AK geography.

**Comment by dustymc** [comment]
done?
