### ISSUE TITLE
Feature Request - user fired script to fill in missing taxonomic names

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#6047]
Looking over this list of Alaskan arthropods

https://arctos.database.museum/record_summary.cfm?guid_prefix=KNWR:Ento,KNWR:Inv,KWP:Ento,UAA:Ento,UAM:Ento,UAMObs:Ento&phylum=Arthropoda&state_prov=Alaska&result_columns=phylum,phylclass,phylorder,suborder,superfamily,family,subfamily,tribe,subtribe,genus,species

It is obvious that the higher taxonomic ranks have many inconsistencies - a perpetual problem. The CNC and their 17 million specimens will likely be aghast at this situation.

We have 3 ways I know of to solve this, none of which work well:

1) by hand, one at a time. Too slow & costly of human time.

2) by the classification bulkloader. Large taxa cause timeouts when trying to download the current taxonomy which prevent this from being functional. Even if a download is successful, the format of the data is horrendous to edit because 'missing taxa' are not missing - that is, CLASS_TERM_n CLASS_TERM_TYPE_n provide a string of first, 2nd, 3rd, etc ranks with no fixed ranks that can be 'missing'. This allows flexibility in the preparation of classifications for different groups some of which genuinely lack certain ranks, but is a major pain to edit such a file offline for upload to the classification bulkloader.

3) the hierarchical classification editor - no idea how this works and too-large taxa cause the same timeouts.

So... I propose a simple user fired script:

When fired this would crawl through all the taxonomy records and if a classification record is found in a specified source, that has, for example:

family = Staphylinidae

then it would check to see if certain user specified criteria are met, such as

superfamily = Staphylinoidea

and if this was missing, add it. Once all records were checked, the script would end. This would help users fill in missing ranks for the classifications they use.

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.
medium

**Comment by DerekSikes** [comment]
I would need to prepare a request for you involving something like 30-50 different situations (each involving different files to manage).

I would also like the column headers to not be CLASS_TERM_n CLASS_TERM_TYPE_n  but be actual ranks (eg superfamily etc) so the missing taxa can be easily seen & filled in. Then the classification bulkloader would need (or you'd need to do some magic) to handle that file for uploading.

Is that possible? It all seems like band-aids on top of band-aids to me.

**Comment by dustymc** [comment]
>30-50 different situations 

If it leads to a situation where taxonomy is actually managed and/or manageable then that doesn't seem too crazy from here??

>column headers to not be CLASS_TERM_n CLASS_TERM_TYPE_n but be actual ranks

That's not scalable and as such I don't think it can sustainably be "part of Arctos" but we can probably find a way to help anyway. (Maybe @Jegelewicz has some excel magic, of there could potentially be a conversion tool, or ????)

>band-aids on top of band-aids

If that's true then let's don't do this. From here, it looks to me like you're trying to manage some unmanageable thing. We can get to where thing(s) are manageable, or you could accept the limitations of what you're using for taxonomy, or WHATEVER, but let's don't just shuffle around and ultimately end up back about where we came from but frustrated from the journey.

That Task Force still doesn't seem like a bad idea....

**Comment by DerekSikes** [comment]
There is a taxonomy task force.

Getting back to the original script idea of this post - your major criticism is that it could mangle other people's data. What if the script was constrained to only edit classifications of taxa in that user's collection?

Yes, this could still mangle other people's data because yes some collections share taxa, but the idea here is just to automate something that a human could do one-at-a-time. I know you hate the single-record editor because it allows users to create inconsistency, but of course, it is needed & I can think of various ways it could be improved to prevent or reduce inconsistencies but that's a different issue.

Getting back to my point - if I had the time (or a clone of myself I could direct to do this work) I would just make all these edits one-at-a-time anyway. The only thing stopping me is time. Thus, you can't criticize a plan that allows the same edits one can make now, but removes the time problem.

By limiting the script to just classifications used in one's collections this would prevent most of the upset jellyfish people problems.

**Comment by campmlc** [comment]
If there is a temporary band aid that lets us show Canadian National
Collections that our taxonomy is not completely unusable, or at least not
an embarrassment, for a particular taxonomic group, then that may be worth
putting some effort into in the short term. If the Task Force is set up, it
should be with the idea of achieving something quickly.

**Comment by Jegelewicz** [comment]
Next Taxonomy WG Meeting is set for May 11, 10AM PDT

We have only been meeting every other month as there haven't been any big issues to tackle. I am happy to try to set up a meeting in the next couple of weeks if it will help. Managing taxonomy in Arctos is a huge pain no matter which way you look at it and our system for management is like no other in the world as far as I know. It is flexible, but that makes it complicated. Perhaps we can figure out some ways to make things work better for everyone.

Note that we do have some apparently intractable problems that have been open forever for which we have not been able to develop an acceptable solution - see [our project](https://github.com/orgs/ArctosDB/projects/27).

**Comment by DerekSikes** [comment]
The system is elegant, scalable, flexible, and not in need of band-aids.

An elegant system would be a relational one with parent-child taxa that fits the original vision of taxonomy. We've been over this ground before. I know you'll say Arctos is elegant because it accommodates reality in which a taxon does not have only one parent taxon. However, homonyms aside, within a well curated subset of taxonomy (eg the family of ground beetles, Carabidae) every taxon should have only 1 parent and thus if an edit is needed (say to change that parent) only 1 record needs editing, not 30,000 records (the number of carabid species). The flexibility of the current system also makes it unweildly and more likely to generate inconsistencies.

What about a truly relational parent-child taxonomy system for editing that generates a flat file for searching? Perhaps this is what the hierarchical editor was trying to accomplish but I'm thinking of something that isn't a tool but an entire database of relational taxa that can be edited as described above and from which the flat file (which would not need direct editing) is produced in the background.

**Comment by Jegelewicz** [comment]
@DerekSikes I have been dreaming about such a thing - that doesn't require a bunch of downloading/uploading. I think we need to get together some funding though.

**Comment by DerekSikes** [comment]
Button to download all the names & preferred classification from the collections one manages and it appears in a format that is easy to edit (taxon ranks as column headers). Thus, an improvement on the current classification bulkloader.

Button to upload the fixed data.

If I or Teresa et al comes up with some offline scripting to make the current classification csv easy to edit this will likely leave many users wishing they also had such scripting so why not build it into Arctos so the downloads are easy to edit?

Time outs when trying to get the data are still a problem forcing us to ask Dusty.

**Comment by dustymc** [comment]
>download all the names & preferred classification from the collections one manages

OK, we're not quite on the same page yet. That should be a one-time thing, the generalized structure is no better for storage than it is as an editor.

>why not build it into Arctos 

That's a question for The Community.  Some considerations:

* taxon ranks as column headers means this would only be suitable for a relatively small set of users, and 
* I suspect you're wanting fairly specific ranks, so this isn't going to be useful for the mineral folks (or whoever might use different ranked taxa) - but it might be easy enough to turn into something that is
* I'd need something like functional requirements to go very far, but I think you're asking for a relatively straightforward spreadsheet-kind-of-thing with eg vocabulary controls baked into the structure (as column headers) 
    * you're probably really not, you're going to want it to also feed the taxon name bulkloader and check for errors and ???????? but maybe that still involves relatively flat structures and tasks that familiar libraries can tackle
* Several people have at various times mentioned something like this and I don't think any have taken the plunge (which means they're increasingly frustrated, or they've found something even easier, or they're doing this but it hasn't caused any problems so I don't know about it, or ????????????)
* NSF still seems to be throwing taxonomy $$ around

I don't think I can add all that up and balance it against everything else, and it's not my place to do so anyway, but it all seems technically plausible and perhaps not entirely out of scope so ??

**Comment by dustymc** [comment]
> Downloading stuff shouldn't be one of those places.

I don't know if we're all on the same page or not! There are two aspects of this:

1. I think it's fair to ask me for assistance in downloading legacy data. It's coming out of what's probably been a lossy container, it won't be consistent, things can very quickly get complicated, etc.
2. That should be a one-time operation for all of the reasons above. Whatever I manage to extract will need help (beyond whatever obvious thing lead to the request). The user should be cleaning and maintaining those data in some suitable-for-that environment and uploading a COPY to Arctos when something needs fixed.

**Comment by Jegelewicz** [comment]
As the original ask in this issue has been labeled as technically problematic, I suggest we close it. If any new solutions are proposed, new issues should be opened.
