### ISSUE TITLE
Identifiers field now shows nonsense in a search result and on labels

### ISSUE THREAD

**Issue by amgunderson** [ArctosDB/arctos#6049]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
In a search result the Identifiers field now shows all this nonsense, 
<img width="275" alt="Screenshot 2023-03-22 at 9 58 51 AM" src="https://user-images.githubusercontent.com/8440698/226996757-a4a9c0da-3cfb-4371-b621-4a26a6d24d02.png">
This is printing on specimen labels too. 

**Priority**
a black hole of despair.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/6011
