### ISSUE TITLE
Feature Request - Look up list of locality names

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#6050]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
I often need to look up lists of locality names. For example, I get a request - give me all the locality and specimen data you have for a particular area. I go to locality search, enter parameters, get a list of things around that area. I download and refine the list in excel to cut out anything not actually in the search area. But now I need a catalog record list and I've no way to input my refined list of localities back in to run a catalog record search.

**Describe what you're trying to accomplish** 
Look up localities from a list of locality names.

**Describe the solution you'd like**
The current search interface does allow me to do this if I have locality_id. So really I just need a way to translate my list of locality names into locality ids. Perhaps this tool https://arctos.database.museum/DataServices/getLocalityUsers.cfm could be modified to do that?

**Describe alternatives you've considered**
I'm guessing it would be difficult to just allow search by concatenated locality names, since they're allowed to have commas and other characters that would be used as delimiters in a concatenated search.

**Additional context**
I realize locality ids are ephemeral, but I'd be using them to search immediately after looking them up.

**Priority**
I've managed without for a while, but I've got a request on my desk that would take a whole day without this, and 15 minutes with this.

**Comment by dustymc** [comment]
I can set the delimiter if you want to recommend some unlikely (or bannable if we want to get fancy) character.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I like pipes as a delimeter.

**Comment by dustymc** [comment]
<img width="454" alt="Screenshot 2023-03-22 at 5 24 56 PM" src="https://user-images.githubusercontent.com/5720791/227068020-73022de8-83bc-436b-903a-18d5e652d521.png">

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks!
