### ISSUE TITLE
Link Arctos Collections with institutional agents

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6052]
From https://github.com/gbif/model-material/issues/110

> institution - there's no such thing in Arctos so we do something random, it'd be nice if this was all NULLable or something but whatever

> > institution - there's no such thing in Arctos

> yes and no? Every collection has an "Institution"

![image](https://user-images.githubusercontent.com/5725767/227279958-595fb1a2-27f0-465d-aecd-d5580476b151.png)

> True - there's a string (couple of them maybe), there's not a data object or even any attempted control of the string.

> > there's not a data object or even any attempted control of the string.

> Perhaps we need an institution metadata page? Or is the agent good enough? https://arctos.database.museum/agent/21334566

> It's been handy to let the agent carry some of the stuff that the collection can't, so maybe. Parent-child relationships would do ^^ that stuff, and maybe whatever weird thing CHAS (at least) is doing by involving dates in the relationships (the collections have changed parents, maybe).

I am not sure what @dustymc envisions, but I can see this two ways:

1. We add a field in collection metadata where we add the Agent for the institution
2. We add some new relationship and ensure that the collection agents are all "owned by" and institution agent instead of just the generic "division of" as they are now.

Any other suggestions?

**Comment by dustymc** [comment]
>envisions

A decent description of the goal would be handy, but I think it would be...

1. require all collections to have corresponding agents with something like ``collection.agent_id int not null references agent(agent_id)``
2. use agent relationships to get at institution (and whatever) - and it would not necessarily be simple, KWP's "parent" would be Ken and then UAM and then AMNH over time, for a convenient and familiar example. (And that's the cool thing: Agents are powerful, we don't have to predict every weird thing that might happen up front, we just use a data object which can already deal with all that.)

**Comment by dustymc** [comment]
long done
