### ISSUE TITLE
Code Table Request - toe clip number

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6057]
## Instructions

_This is a template to facilitate communication with the Arctos Code Table Committee. Submit a separate request for each relevant value. This form is appropriate for exploring how data may best be stored, for adding vocabulary, or for updating existing definitions._

_Reviewing documentation before proceeding will result in a more enjoyable experience._

* [Issue Documentation](http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html)
* [Code Table Documentation](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html)
* [Video Tutorial - Submit a Code Table Request](https://youtu.be/t2jHbsRA3lk)

------------------------------

## Initial Request

_**Goal**: Describe what you're trying to accomplish. This is the only necessary step to start this process. The Committee is available to assist with all other steps. Please clearly indicate any uncertainty or desired guidance if you proceed beyond this step._

Generic other identifier clean-up #6032 

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type#toe_clip_number seems more appropriate as an attribute? It describes something I would expect to find when I look at the specimen.

I propose we move it there. 

_**Proposed Value**: Proposed new value. This should be clear and compatible with similar values in the relevant table and across Arctos._

toe clip number

_**Proposed Definition**: Clear, complete, non-collection-type-specific **functional** definition of the value. Avoid discipline-specific terminology if possible, include parenthetically if unavoidable._

no change

`Refers to a combination of toe clips unique to a given specimen in a mark-recapture study using this numbering procedure. This number is generally 4 digits ranging from 0-5 representing the 5 toes of each foot (0=none). Order is given as front right, front left, rear right, rear left feet. Numbering of toes is 1-5 from inside to outside of foot. If more than one toe on a given foot is clipped, two numbers in parentheses are noted e.g. 2(23)14 is interpreted as: front right second toe, front left second and third toe, rear right first toe, and rear left fourth toe.`

_**Context**: Describe why this new value is necessary and existing values are not._

_**Table**: Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table or value. This may involve multiple tables and will control datatype for Attributes. OtherID requests require BaseURL (and example) or explanation. Please ask for assistance if unsure._

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type

_**Collection type**: Some code tables contain collection-type-specific values. ``collection_cde`` may be found from https://arctos.database.museum/home.cfm_

Mamm, Herp, Teach (others?)

_**Priority**: Please describe the urgency and/or choose a priority-label to the right. You should expect a response within two working days, and may utilize [Arctos Contacts](https://arctosdb.org/contacts/) if you feel response is lacking._

_**Available for Public View**: Most data are by default publicly available. Describe any necessary access restrictions._

yes

_**Project**: Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184)._

_**Discussion**: Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary._

## Approval

_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality)._

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection

_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation

_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

_Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel._

_Make changes as described above. Ensure the URL of this Issue is included in the definition._

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by dustymc** [comment]
Agreed, although I wonder if even attributes are necessary - remarks might be completely sufficient to contain the utility of these data??

(And I think this suggests something about identifiers: scope is involved, something grander than a mark-recapture study.)

Data
[temp_toe_clip_number.csv.zip](https://github.com/ArctosDB/arctos/files/11056910/temp_toe_clip_number.csv.zip)

Summary

```

 guid_prefix | numrecs 
-------------+---------
 MSB:Mamm    |       3

```


 @campmlc
 @AdrienneRaniszewski
 @jldunnum

**Comment by Jegelewicz** [comment]
@campmlc, based on your description, this number needs to be given in conjunction with some project or it is very likely to be duplicated with no way to know which individual is part of which survey. This means that for this particular identifier type, the issued by would be CRUCIAL and there would need to be a unique agent for each project if the identifier itself were to be of any use. Do we have enough detail to create those agents?

> As such, they function as an organism identifier, when added to the "issued by" project agent.
> the primary identifier of the organism (the toe clip) 
> this is serving as an organism ID

Maybe Organism ID is the type it SHOULD be with toe clip in remark?

> Probably there are more toe clips out there that were entered in some other format - eg other identifier with "toe clip" as part of the ID value?

@dustymc can you check that out? I only find twenty other identifiers that include "toe" in the value, but I cant see everything and most of the ones I do find aren't toe clips except:

https://arctos.database.museum/guid/MSB:Mamm:138956
https://arctos.database.museum/guid/MSB:Host:17567

If this is really only being used 5 times - I suggest we find a better way to record it than with an identifier type. It opens the door to every kind of clip anyone might use in any survey as an identifier type and I'm not sure that is where we want to be?

**Comment by dustymc** [comment]
> can you check that out?

I can only access what's actually in the data, and I believe that to be true for everyone else as well. (That's in the [attached CSV](https://github.com/ArctosDB/arctos/issues/6057#issuecomment-1482002034))

>Organism ID is the type

That's what's being suggested (and then refused for some reason I think???) but mixing this in would just serve to pollute the pool. (Unless "2" carries a lot more weight than I can see.) Still, if that's what's required to move on this then I'm all for it.

>opens the door to every kind 

Yes, that's also how I'm understanding the feedback.

>not sure that is where we want to be

We do seem to be stuck in just about the most uncomfortable position imaginable, and hopefully that's not just a lack of imagination!

**Comment by Jegelewicz** [comment]
Given the limited use of this type, I suggest we do the following:

1. Add an issued by if we can
2. Change the type to other identifier
3. Put "toe clip number" in identifier remark
4. Remove toe clip number form the code table

If we end up with some critical mass (we should define that) of "toe clip" in other identifier remarks, then we can consider adding a new type and all of the appropriate identifiers that need changing could easily be found. 

I really think we need to think about our resources and where they are best spent. Maintaining a term in a code table may seem like no big deal, but it all adds up. Nothing will be lost, but there will be one less item on the "[endless dropdown of death](https://github.com/ArctosDB/arctos/issues/6067#issuecomment-1487522088)."

**Comment by campmlc** [comment]
Our institution doesn't need this right now, so let's do what is proposed and see if that can work.

**Comment by Jegelewicz** [comment]
@dustymc I have change the three records - we can remove this from the code table.
