### ISSUE TITLE
GADM oddities

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6059]
ref: https://github.com/ArctosDB/arctos/issues/5654

I'm filing this as a sort of final test of what was decided in https://github.com/ArctosDB/arctos/issues/5654, namely that we want "ranks" for GADM2 (county-equivalent) geography.

Arctos contains [United States, Colorado, Broomfield County](https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10004747)

GADM would have us make that ``Broomfield City and County``

Being able to script things requires consistency, so most anything not involving "except...." is fine with me. https://en.wikipedia.org/wiki/Broomfield,_Colorado suggests that GADM is more correct. I don't see any problem with this, but it will mean that the data for Colorado (and whatever other states do this sort of thing) will be slightly less homogenous so, out of an abundance of caution, here I am.

Is there any reason I should not proceed with this update?

Ping @mkoo

**Comment by dustymc** [comment]
See also https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10002467 - I'm most of the way through the US and it looks like this is rare, probably going to rock on and leave this in case we need to revisit.

**Comment by mkoo** [comment]
Go with GADM -- if there's stuff to change we coordinate with GADM and alter at the source/authority. But technically it's correct. If this is an issue at some practical level then we can address with a report's SQL or other means.

**Comment by mkoo** [comment]
Also, _sigh_ Carson City! I bet the residents dont even know its formal name... (includes lots are our MVZ specimens: Carson City is part of the spec_loc so doesnt really have a huge impact until we print out labels where we can adjust accordingly)

**Comment by dustymc** [comment]
[District of Columbia District](https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=1005332)

**Comment by dustymc** [comment]
I'm not sure if this is a typo or intentional: https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10020510

**Comment by dustymc** [comment]
I think this one's for GADM, but it could very well be my import tools - it looks like something, somewhere, is truncating.

https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10006838 is currently state='Greece, Peloponnese, Western Greece and the Ionian Islands', GADM gives (or my tool takes, or??) that as 'Peloponnese, Western Greece and'

My scripts are trying to create duplicates while filling in the missing-from-Arctos states, leaving the correctly-incorrect version still seems least-evil but ???????? Not sure where this'll end up, but now it's noted....

**Comment by dustymc** [comment]
https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10006768 - I'm not sure if "Naoasaki" is a defensible transliteration or not

**Comment by dustymc** [comment]
[Pakistan, Federally Administered Tribal Ar](https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10021504)

**Comment by dustymc** [comment]
Saint Helena, Ascension and Tristan da Cunha == Saint Helena, Ascension and Tris - ignoring

**Comment by dustymc** [comment]
South Georgia and the South Sandwich Islands wants to be South Georgia and the South Sand - ignoring

**Comment by dustymc** [comment]
https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10007520, suspect surrounding shapes are affected

**Comment by dustymc** [comment]
https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10005145 and children wants to be ``United States Minor Outlying Isl`` - ignoring
