### ISSUE TITLE
search.cfm --> tools

### ISSUE THREAD

**Issue by KyndallH** [ArctosDB/arctos#6061]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
This is a mess:

<img width="315" alt="Screen Shot 2023-03-24 at 10 33 06 AM" src="https://user-images.githubusercontent.com/16887896/227611332-c2d55057-adea-4ae7-a193-8d8cafa65a3d.png">

**Describe what you're trying to accomplish** 
Can we either do verb or noun first? How about in alphabetical order?

**Describe the solution you'd like**
Figure out if folks like verbs first (which it sounds like most do) and rewrite them with verb first, then put this in alphabetical order.

**Describe alternatives you've considered**
Being frustrated. Ignoring.

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by dustymc** [comment]
Here's the whole widget, I can work with however you can communicate what needs to happen.

Also its been mentioned that maybe this needs a new kind of tool (popup like login maybe?), I can do that too just let me know what might work.

```
<select form="cat_rec_sch_frm" name="tools_ctl" id="tools_ctl" size="1">
		<option value="">[ Tools ]</option>
		<cfif listfindnocase(session.roles,'manage_transactions') and len(add_to_trans_id) gt 0>
			<option value="/info/loan_item_pick.cfm?add_to_trans_id=#add_to_trans_id#">Add items to Transaction</option>
		</cfif>
		<cfif listfindnocase(results_flds,'remove_row|remove_row')>
			<option value="remove_row_submit">Remove selected rows</option>
		</cfif>

		<option value="/bnhmMaps/bnhmMapData.cfm">BerkeleyMapper</option>
		<cfif len(session.username) gt 0>
			<option value="/SpecimenResultsDownload.cfm">Download</option>
			<option value="reloadAtURL">Reload with shareable URL</option>
			<option value="/info/cat_record_group.cfm">Summarize</option>
			<option value="annotateall">Comment or report Bad Data</option>
			<option value="savsearch">Save Search</option>
			<option value="archiveRecords">Archive Search</option>
		<cfelse>
			<option value="login">Log in or create account for more options.</option>
		</cfif>
		<cfif listfindnocase(session.roles,'coldfusion_user')>
			<option value="/Reports/report_printer.cfm">Arctos Reporter</option>
			<cfif listfindnocase(session.roles,'manage_records')>
				<option value="/multiAttribute.cfm">Manage Attributes</option>
				<option value="/place.cfm??sch=collecting_event">Manage Collecting Event</option>
				<option value="/Encumbrances.cfm">Manage Encumbrances</option>
				<option value="/multiIdentification.cfm">Manage Identifications</option>
				<option value="/multiAgent.cfm">Manage Collectors</option>
				<option value="/tools/replace_agents.cfm">Manage Agents</option>
				<option value="/findContainer.cfm">Part Locations</option>
				<option value="/place.cfm?sch=locality">Manage Locality</option>
				<option value="/SpecimenUsage.cfm?action=search">Manage Publications</option>
				<option value="/bulkSpecimenEvent.cfm">Manage Specimen Events</option>
				<option value="/addAccn.cfm">Manage Accession</option>
				<option value="/tools/bulkPart.cfm">Modify Parts</option>
				<option value="/tools/magicEntity.cfm">Magic Entities</option>
				<option value="/Reports/specrescollevent.cfm">Download Collecting Event CSV</option>
				<option value="/info/part_data_download.cfm">Part Table View</option>
				<option value="/tools/identifier_download.cfm">Identifier Table View</option>
				<option value="/Reports/attribute_data_download.cfm">Download Attributes</option>
				<option value="/SpecimenResultsDownload.cfm?action=bulkloaderFormat">Download for Record Bulkloader</option>
				<option value="/SpecimenResultsDownload.cfm?action=citationFormat">Download for Citation Bulkloader</option>
			</cfif>
			<option value="/info/checkLegalTaxonomy.cfm">Check Arctos Legal (taxonomy)</option>
			<option value="/SpecimenUsage.cfm?tbl_use=sensu&action=search">View Sensu Publications</option>
		</cfif>
	</select>
```

**Comment by dustymc** [comment]
As an easy update, suggest outgroups be added. For example, Customize and Presets are outgroups of the profiles selector:

<img width="341" alt="Screenshot 2023-05-02 at 3 48 19 PM" src="https://user-images.githubusercontent.com/5720791/235801792-c1aa461c-c407-49e4-89b5-9dec9d76571d.png">

I started a spreadsheet but didn't get very far, HELP!

https://docs.google.com/spreadsheets/d/1IYag_BXETMROilH119SBZFZny5Uji1s70p9Rp1qbdxA/edit?usp=sharing

**Comment by ewommack** [comment]
> I started a spreadsheet but didn't get very far, HELP!

You spreadsheet needs? Help with grouping the things that were in the tools menu that stared the issue?

**Comment by dustymc** [comment]
1. Whatever else happens, the tool names/labels need help. So help!
2. They could probably also benefit from some sort of organization, something better than a giant formless list. Making them look like the screenshot above (outgroups) is a simple way to add a bit of organization. If that seems useful then I'd like some help on that too, and hopefully the spreadsheet is a useful way of doing that. (If that doesn't seem useful then I'm open to about anything.)

If that's still clear as mud (and maybe even if it isn't), this might be a good task for @ArctosDB/search-ui-task-group

**Comment by Jegelewicz** [comment]
I added my ideas to the sheet and have requested a couple of enhancements....

**Comment by dustymc** [comment]
Request Data should be worked in somewhere.

**Comment by Jegelewicz** [comment]
I added it to Special - could also go in Download, but it is a little different?

**Comment by Jegelewicz** [comment]
@ArctosDB/arctos-working-group-officers please review https://docs.google.com/spreadsheets/d/1IYag_BXETMROilH119SBZFZny5Uji1s70p9Rp1qbdxA/edit?usp=sharing

**Comment by dustymc** [comment]
I've made an adjustment for https://github.com/ArctosDB/arctos/issues/5628, "manage publications" is now plain old 'publications' and available to any "us" user.

If that's acceptable then please adjust the spreadsheet, if not then the other issue will need revisited.

```

		<cfif listfindnocase(session.roles,'coldfusion_user')>
			<option value="/Reports/report_printer.cfm">Arctos Reporter</option>
			<option value="/SpecimenUsage.cfm?action=search">Publications</option>
```

**Comment by Jegelewicz** [comment]
I'm messing with the sheet to sort the categories, then items.

**Comment by Jegelewicz** [comment]
I have a meeting at 10 AM PDT, but we can meet up after that to talk about this if you want...

**Comment by dustymc** [comment]
I did some of that (check test) and...

* I don't think I like uncategorized items (but I'll roll with it if ya'll do)
* The transaction thing should probably be at the top, that's been a topic a few times (and if it's there it's likely what's wanted)
* there's some efficiency in grouping things by access to whatever extent that's possible. It's *probably* not entirely fatal here (this page only processes once on init load), but it still takes some CPU. Right now you've got the first three items each requiring their own check (which later gets repeated a bunch of times):
   * operator
   * everyone
   * has username

**Comment by Jegelewicz** [comment]
> The transaction thing should probably be at the top, that's been a topic a few times (and if it's there it's likely what's wanted)

OK by me - I changed in the sheet

## everyone
![image](https://github.com/ArctosDB/arctos/assets/5725767/a3d515cf-a034-4040-9f17-c762ae1d67cd)


Trying to do the same when logged in as jegelewicz and get this

An error has occurred. Please include the ErrorID as text in any communications. 
ErrorID: 6FCC812F-092D-41B6-AFEC460393BD45F2
Mesasge: ERROR: permission denied for table api_pubusrallall_20230711060737185_480
Details:

**Comment by Jegelewicz** [comment]
## operator
![image](https://github.com/ArctosDB/arctos/assets/5725767/c93c8657-b33e-453b-9d92-cfc6efb519ce)
![image](https://github.com/ArctosDB/arctos/assets/5725767/50d77f4e-d67c-433d-adde-757c75f78c30)

**Comment by Jegelewicz** [comment]
## has username
![image](https://github.com/ArctosDB/arctos/assets/5725767/0a602e79-26e7-45f0-8a57-317454593d7d)

**Comment by Jegelewicz** [comment]
The Special category should go away?

Why can't has username access these things?

Reload with sharable url
Request data

**Comment by dustymc** [comment]
>Reload with sharable url

The only "technical" (usability, really) reason is that it's possible/easy to melt the form. That would also introduce a fair bit of complexity in the menu as things are currently arranged, but that can be dealt with.

> Request data

We don't really have the resources to safely run that for "us" - there's some discussion in the source Issue.
