### ISSUE TITLE
Consistent naming of Arctos Component Loaders

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6066]
The various "component loader" tools are referenced in the Arctos Tools Directory, but when you reach the tool, the page title differs from the tool name in the directory.

For example, Catalog Record Event: Bulkload in the Directory

![image](https://user-images.githubusercontent.com/5725767/228049703-885a089a-1cb9-45d7-824a-43b3a715ab6f.png)

Takes you to Bulkload Specimen Event Tool

![image](https://user-images.githubusercontent.com/5725767/228049804-8c41c136-2a02-4057-9981-1ebcb8052af7.png)

It would be nice if the title for the component loaders could be derived directly from the Title assigned in Manage Directory. This would create a "single source of truth" for the tools and provide consistency between the directory and the tools themselves.

**Comment by dustymc** [comment]
I though this was resolved, we agreed to NOT do it - @mkoo ? 

The consistency would be nice, but someone misnaming a link (lots of users can manage that, a fair number of them are currently inaccurate - https://github.com/ArctosDB/arctos/issues/5742#issuecomment-1452749503 for example) also resulting in a mislabeled and misleading form doesn't sound so great.

**Comment by Jegelewicz** [comment]
If we cannot make the page titles read from the Manage Directory Title, then can we at least change them to match what we have now? They are just static text, no?

**Comment by Jegelewicz** [comment]
OK - but does it have to be that way? Why does the UI have to show us what you decided to call the tool rather than what our directory calls it?
