### ISSUE TITLE
Add NCBI issued by agent to GenBank identifier

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6067]
Request to globally add the NCBI issued by agent to all records with a GenBank identifier.
Currently the only two NCBI identifiers in Arctos are GenBank and BioSample identifiers. Both of these should automatically get NCBI issued by agents - can this be done retroactively @dustymc ? And going forward?

We should discuss at some point what to do about the many other NCBI identifiers for their constantly increasing number of databases - however, NCBI has created the BioSample ID as a means of linking to all the connected identifiers, a dashboard where all related IDs/urls are linked. So if Arctos records link to that ID, then they can link to SRA and other databases indirectly. https://www.ncbi.nlm.nih.gov/books/NBK169436/

Also, we need to address the issue of automatic reciprocal relationships with other databases outside of GenBank at NCBI. Is this happening now, or do we need to raise this issue with them? And do we need a way to flag which records in Arctos have whole genomes or transcriptomes, by adding these identifiers to the code table, or some other way, eg via catalog record attributes? I realize these will need new issues, but just starting the discussion.

See #5771

**Comment by dustymc** [comment]
What's the goal? I figure someone will ask for a bulk-tool for this sort of thing at some point, but with resolvable identifiers it won't DO (much of) anything (they can only be issued by whomever owns nih.gov, and I don't think that's much of a mystery!), so it doesn't seem any kind of priority from here.

See also https://github.com/ArctosDB/arctos/issues/6064; this is clearly more complicated than it has to be, and there's an easy solution just begging to be adopted.

**Comment by campmlc** [comment]
The goal is to be able to find all records with NCBI identifiers, including
whole genomes, which do not have GenBank numbers. NCBI is another
organizational agent that has multiple types of identifiers. In order to
find everything with genomic data, we need to link the different
identifiers together under the single NCBI issued by agent for
discoverability.
Right now there are only two NCBI identifiers in the code table: GenBank
and BioSample.  If we link each of these to NCBI, we may be be able to keep
this relatively simple. Both types of identifiers and their records could
be found through agent activity search.
Also, I thought the goal was to add issued by agents to all resolvable IDs,
for the same reason.

**Comment by dustymc** [comment]
>thought the goal was to add issued by agents to all resolvable IDs

It is, they're just not as important (and this has turned into an impressive time sink so I'm trying to prioritize). "MC1" could have been "issued" by maybe-millions, while there's a whole system controlling where ``http://www.ncbi.nlm.nih.gov/nuccore/ON148026`` could have come from.

>find all records with NCBI 

Fair enough, done.

>Right now there are only two NCBI identifiers 

That's why I linked the other issue. That is not true, there are not. There are four - and one of them is "NCBI Biosample" which was added by you two years after I added "BioSample." They are of course used interchangeably

```
           other_id_type           | count 
-----------------------------------+-------
 BioSample                         |   235
 GenBank                           | 37473
 NCBI Biosample                    |   806
 NCBI Sequence Read Archive Run ID |   168

```

SEVEN YEARS we've been living with a duplicate that we don't seem to have seen. SEVEN YEARS people are finding only some proportion of what we have. I cannot understand the great resistance to simplifying.

**Comment by campmlc** [comment]
This is a great opportunity to merge these. If they were all under the same issued by agent, we'd immediately be able to see the problem and get it fixed, instead of scrolling through an endless dropdown of death.  
Happy to merge NCBI Biosample into BioSample with NCBI issued by - I'm sure the absence of issued by NCBI was part of the reason for the duplicate identifier. For the Sequence Read Archive (SRA) IDs - if we can determine that their information is captured by the BioSample IDs, those could also be dealt with. The SRA value is another database at NCBI.

**Comment by campmlc** [comment]
So given that, these could all have an "isssued by NCBI" agent - and then they can all be found through the agent name as we deal with solving their individual issues.

**Comment by Jegelewicz** [comment]
Let's take this one step at a time?

First - I suggest we merge [BioSample](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type#biosample) into [NCBI BioSample](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type#ncbi_biosample)

And end the duplication. After that is done, we can move on to other stuff. I will file a separate issue, just so it is clear to everyone.

**Comment by Jegelewicz** [comment]
<img width="960" alt="Screenshot 2023-03-28 16 08 27" src="https://user-images.githubusercontent.com/5725767/228377686-5b78e6d6-01ba-41d9-9bab-b11dc8f3e578.png">

**Comment by dustymc** [comment]
>suggest we merge

That's well within my powers as DBA and doesn't need further discussion, but we are struggling with things that seem crystal clear for reasons I can't understand, and I am hoping that perhaps this situation can in some way shed some light on the big picture. If not then whatever, this can be closed, but surely SOMETHING can be used to leverage us out of what's increasingly feeling like an impossible quagmire??

**Comment by campmlc** [comment]
This is cleaning up the quagmire - we are making things better!
