### ISSUE TITLE
Question [external CONTACT]

### ISSUE THREAD

**Issue by lin-fred** [ArctosDB/arctos#6069]
From twitter: 
![image](https://user-images.githubusercontent.com/19802479/228279664-d6af8a72-a007-4635-9659-cbf0f0b904e6.png)

>[@arctosdb](https://twitter.com/arctosdb)
 There seems to be an issue with the Map portion of the Record Search; I no longer see a map with which I can draw a polygonal area?

Does anyone have a reply for this? @mkoo @dustymc

**Comment by dustymc** [comment]
Duplicate of https://github.com/ArctosDB/arctos/issues/5873 - I'll see what I can do.....
