### ISSUE TITLE
Make it easy to add issued by to existing other identifiers in bulk

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6072]
@dustymc asking for a test of https://github.com/ArctosDB/arctos/issues/6033#issuecomment-1478067397

The attached list of GUIDs have only one collector and one collector number - can you add Arthur H. Harris to the "issued by" for the collector numbers?

[Art Harris Identifiers.csv](https://github.com/ArctosDB/arctos/files/11090609/Art.Harris.Identifiers.csv)

I know Art and most of these data, so I thought this would be a place to start. These get complicated though when there are more than one collector or when I can see that the collector number clearly belongs to someone else, which is an opportunity for cleaning stuff up, but means time and effort that probably aren't available around the community (sigh).

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/arctos/issues/6033#issuecomment-1487007961_

**Comment by campmlc** [comment]
Support this 100%. Collections need this ability to determine collectors and other issued by agents and add them on a case by case basis.
See also #6067

**Comment by Jegelewicz** [comment]
These came from this search https://arctos.database.museum/search.cfm?oidtype=collector%20number&coll_role=collector&collector=Arthur%20H.%20Harris

I went through the downloaded results (I only got GUID, collector number and collector), and found those that had a single collector (Arthur H. Harris) and a collector number that was clearly his or was nothing more than a number.

Below is that part of the download.
[Art Harris Identifiers safe.csv](https://github.com/ArctosDB/arctos/files/11093694/Art.Harris.Identifiers.safe.csv)

It would be nice if there was an easy way for me to just Arthur H. Harris to issued by for all of these. Perhaps some sort of Manage Identifiers tool? I can use this to upload a new identifier with the issuer, but I have to remove the old ones first or else the Identifier Unloader will just unload all of them. See also https://github.com/ArctosDB/arctos/issues/5891

**Comment by dustymc** [comment]
I think this is a specialized loader, even though it could be done through unloading and loading. Lots of folks are probably going to want to sort through their IDs, making that as easy as possible seems to me to justify a dedicated tool.

I think it would be difficult to filter this through manage, and adding this incorrectly is probably irreversible: someone sees Art linked to some strange "1" and they're just going to accept it as one of life's little mysteries and never figure out that a too-coarse filter was fed to a mostly-blind update tool. I think CSV will mitigate that, and if this ends up being "us" acting on behalf of some user then the CSV will perhaps be doubly important (so we can eventually fix whatever we might muck up).

I think the tool would accept:

* guid
* IDtype
* IDvalue
* issued_by

and

1. Add issued_by if the data describes one ID with NULL issuer, or
2. Fail

Workable/reasonable/etc? (Go next task if so.)

**Comment by campmlc** [comment]
Could the tool accept all ID metadata fields, including relationship, link
urls and remarks? I've already had to do a second load of duplicate
identifiers because I couldn't change the relationship.

**Comment by dustymc** [comment]
>change the relationship.

That's a job for the unloader and loader.

**Comment by dustymc** [comment]
@Jegelewicz break it

**Comment by Jegelewicz** [comment]
In test or prod?

I loaded one in prod and it failed

https://arctos.database.museum/guid/UTEP:Herb:11888

![image](https://user-images.githubusercontent.com/5725767/228582916-c5d3fe7e-18c8-4326-80f2-0ad6da155222.png)

![image](https://user-images.githubusercontent.com/5725767/228583048-e798b531-6c06-4ac0-9a21-9c4027a23292.png)

**Comment by dustymc** [comment]
>In test or prod?

yes

> loaded one 

?? wrong tool? Don't think what I built can do that, but lemme know if so!

[Bulkload Identifier IssuedBy](https://arctos.database.museum/loaders/bulk_identifier_assignedby.cfm)

Ugh - and I've mixed up assigned and issued - it does what it should but I messed up the labeling, I'll try to patch that in in a bit.

**Comment by Jegelewicz** [comment]
Got it - let me know when to try again.

**Comment by Jegelewicz** [comment]
Also - I changed the title to be consistent with the rest of the tile: Other Identifier: Bulkload IssuedBy.

**Comment by dustymc** [comment]
https://arctos.database.museum/loaders/bulk_identifier_issuedby.cfm

I think it's all de-my-dumb-brain-ed but the directory listing may be cached.

I think test won't be auto-running but you can https://arctos-test.tacc.utexas.edu/ScheduledTasks/component_loader.cfm?debug=true and see what happens, there should be a few hundred set to autoload.

**Comment by Jegelewicz** [comment]
It looks like that works. At least it added the issued by to https://arctos-test.tacc.utexas.edu/guid/UTEP:Herb:15477

**Comment by dustymc** [comment]
> At least it added

I'm sure you know, but click the name, scroll down, and

<img width="252" alt="Screenshot 2023-03-29 at 11 20 22 AM" src="https://user-images.githubusercontent.com/5720791/228631874-8f6e9446-a67b-450c-9acd-4bcdd1acceab.png">

https://arctos-test.tacc.utexas.edu/search.cfm?id_issuedby=Arthur%20H.%20Harris

**Comment by Jegelewicz** [comment]
Check. Just let me know when it's in production and I'll load this stuff (and some other stuff...).

**Comment by dustymc** [comment]
>when

2 hours ago.

**Comment by Jegelewicz** [comment]
I can't get there.

![image](https://user-images.githubusercontent.com/5725767/228635682-29bb2a68-f920-45dc-9ab0-c36a00feb213.png)

**Comment by Jegelewicz** [comment]
Nevermind - got it now.

**Comment by Jegelewicz** [comment]
I haven't used this yet - wondering if we should also allow an insert of remarks? Same tool or some other tool?

**Comment by Jegelewicz** [comment]
Once the stuff I have in there loads, I'll test it by trying to enter a duplicate.

**Comment by cjconroy** [comment]
Not sure if there is another thread for this. But, how do you add "issuedby" during data entry? In my example below, this is a San Diego Natural History Museum catalog number. 
<img width="735" alt="Screenshot 2023-04-28 at 1 45 47 PM" src="https://user-images.githubusercontent.com/5749672/235251216-70212095-44ac-4ec4-b79c-a30aefcea0ab.png">

**Comment by dustymc** [comment]
You can use extras, a rebuild to add that to the core fields is blocked by https://github.com/ArctosDB/arctos/issues/6171 (and I'm not sure that's progressing at a reasonable pace @Jegelewicz @mkoo )

https://github.com/ArctosDB/arctos/issues/6003

**Comment by campmlc** [comment]
We have a meeting on Tuesday to hopefully resolve issues related to #6171 - see Banner.
