### ISSUE TITLE
Code Table Request - "whole organism, slide" - remove from part name list

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#6075]
Can we get 'whole organism, slide' out of the part name code table and 'slide' used as the preservation type for any records that currently have 'whole organism, slide' as their part?

This change may have already happened (I can't restrict search to exact match of part type = whole organism, slide) so all that is left to do may be to remove 'whole organism, slide' from the part name code table

and the list of definitions: https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name

slide is already a preservation type.

**Comment by Jegelewicz** [comment]
[whole organism, slide](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#whole_organism__slide)

**Comment by dustymc** [comment]
done

**Comment by campmlc** [comment]
Whoa, I thought we had a process for code table changes. Not that I don't agree with this - but 2 minutes? Seriously? 
This affects our collections and I would like to at least notify and get feedback from our affected collection managers.
