### ISSUE TITLE
Request Collection Creation, MMNH:Edu

### ISSUE THREAD

**Issue by barke042** [ArctosDB/arctos#6080]
I am requesting creation of MMNH:Edu, a database for Bell Museum teaching and outreach specimens. The CSV from the prospective collections form is attached.
[collection_request_template.csv](https://github.com/ArctosDB/arctos/files/11112256/collection_request_template.csv)

**Comment by Jegelewicz** [comment]
@barke042 I moved this over to new collections - https://github.com/ArctosDB/new-collections/issues/647
