### ISSUE TITLE
Agent Merge Request - the two Ulyses Pardinas

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#6081]
Use this template when you discover two agents that you believe represent the same person or organization.

**Agent that should remain after the merge**
Ulyses F. J. Pardinas (person: 1016443)
https://arctos.database.museum/agents.cfm?agent_id=1016443)

**Agent that will no longer remain after the merge**
Ulyses Pardiñas (person: 10014749) 
https://arctos.database.museum/agents.cfm?agent_id=10014749

**Reason for merge**
Same person. The better one has more stuff attached. The secondary one only has MSB mammal attachments, and Jon Dunnum OK's it. 

Am I also supposed to do the Bad Duplicate Of relationship?

Please add this issue to the Agents Project

@ArctosDB/agents-committee

**Comment by Jegelewicz** [comment]
> Am I also supposed to do the Bad Duplicate Of relationship?

Yep - that will mark them to merge and it seems like this one is easy.

**Comment by cjconroy** [comment]
So what does posting in github do?

**Comment by lin-fred** [comment]
For the cases when it's not easy?

Can also be useful when needing to contact several collections or if you aren't sure who to contact.
