### ISSUE TITLE
Increase Max Search Record Results to 5000 from 100

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6082]
Request: To increase the dropdown values in the Catalog Record Search results from the current 100 records max to what we previously had before the new UI change: 5000 records.

Justification: 100 records is an unmanageably small number of records to view when the search results may be 1000 or more records. We previously had this functionality and have lost it. I am requesting return to previous functionality which is necessary to use the interface for most curatorial, if not also public, searches, as these types of searches routinely yield thousands of records.

Priority: High. Impeding work.

**Comment by cjconroy** [comment]
I thought the number of rows had something to do with the number of columns in your results. I find the number of rows I get is dynamic.

**Comment by mkoo** [comment]
This is essentially tied to #6020 

And yes, you're right too Chris-- currently dependent on customized search results (not search parameters)

**Comment by dustymc** [comment]
The filter is dynamic, I need more information to even consider considering any changes.

Specific column - as explained on the form which turns them on - controls the allowable count.

Search criteria do not influence results, but were involved in calculating the cost factor.

Also related: https://github.com/ArctosDB/arctos/issues/5460

**Comment by campmlc** [comment]
Even as a public user in an incognito window, with standard fields selected, and a single result returned, I still only have the option of 100 records at a time in the dropdown.
![Screenshot 2023-03-31 10 22 23](https://user-images.githubusercontent.com/14808196/229176364-6c8d5799-d09d-471c-bb8a-87f6b8bcb68f.png)

And nothing changes if I do a public search, same criteria, that yields over 2000 records:

![Screenshot 2023-03-31 10 25 05](https://user-images.githubusercontent.com/14808196/229176899-d34c3958-05b9-4fbc-9d4e-a241d3a0b283.png)

**Comment by dustymc** [comment]
Is this two requests or was the initial just misunderstood by everyone?

Yes, page size options are different for public users and "us" for reasons involving both back-end and user experience. Most users seem to have no difficulty with the pagination.
