### ISSUE TITLE
data entry screen: post-successful-save background color

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6085]
Incidentally, that colored background for the data entry page is only visible if you only create one record. Once you save it, the background goes to white... should I submit an issue?

_Originally posted by @AJLinn in https://github.com/ArctosDB/arctos/issues/5601#issuecomment-1416833385_

**Comment by ewommack** [comment]
If we can get the nice blue for each new entry that would be great! Yes please.

**Comment by AJLinn** [comment]
Checking in to see where we are on this? My curatorial assistant who is susceptible to migraines is having to go out and start over every time she saves a new record so she gets the green background instead of the white.

**Comment by dustymc** [comment]
@AJLinn this is blocked by https://github.com/ArctosDB/arctos/issues/5331, which has been blocked for way too long but finally scheduled to start next week. I'll add this and get it at the same time.

https://github.com/ArctosDB/internal/issues/258 is in part an attempt to make sure we never end up indefinitely stuck in the betweens again, your input would be appreciated.
