### ISSUE TITLE
UI request: scroll to top button

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#6087]
I love my long list of options in Customize Results/Search etc and in Search Results, so it would make it even more wonderful if there was a scroll to top button where the save button is (hitting return is not as obvious)

A little js would do the trick

https://www.w3schools.com/howto/howto_js_scroll_to_top.asp

I would put this in some top level page spot so it automatically appears on any page when a user scrolls more than say, 100px.

**Comment by campmlc** [comment]
Along with fixed column headers when we scroll?

**Comment by dustymc** [comment]
We can do whatever, but if we're going to sticky a button maybe we should just sticky whatever you want to see - I don't think there's much at the top  (and I don't quite understand why you want to go to the top, quick discussion might be useful).

>fixed column headers

That's not happening from some unrelated comment, it would have significant sustainability impacts, needs a dedicated Issue.

**Comment by dustymc** [comment]
tentatively merging this into https://github.com/ArctosDB/arctos/issues/6096
