### ISSUE TITLE
Feature Request - Add link to Create Accession from Accession Search results page

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#6089]
Would others find it useful to have a direct link from the Accession Search results page to the Create Accession page? I know I would LOVE it!

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I search for UAM:EH accessions to see if anyone has already created the accession I need to add. I do a search, end up with no results, then have to click back to Tools Directory and then click again on Accession: Create.

**Describe what you're trying to accomplish** 
We don't always add accessions in sequential order so the "Most recently used" suggestion is not always accurate/relevant. I'd like to go directly from my search results page to the Create Accession form without adding two more clicks in the meantime.

**Describe the solution you'd like**
Add a hyperlink or button linked to the Create Accession form.
<img width="1019" alt="Screenshot 2023-04-03 at 3 02 14 PM" src="https://user-images.githubusercontent.com/17605945/229648167-44b44b93-613a-473b-8148-0d228dcb75fd.png">

(Sorry my colors don't match, but you get the idea!)

**Priority**
Medium (it would make me super happy, but nothing is broken without)

BTW, this would be nice for links to the Create new loan in the same way!

**Comment by dustymc** [comment]
Going next task, I know how to do this.

**Comment by campmlc** [comment]
Yes, I would love this too. We look to see if an accession has already been
created, and the search is negative - so we need to create one. It would be
much easier to do so from the results page .

**Comment by dustymc** [comment]
See also https://github.com/ArctosDB/arctos/issues/6144, add all create relevant stuff buttons

**Comment by Jegelewicz** [comment]
How about a way to create an accession directly from the tool menu? Why should I have to (or how would I know to) search fpr an accession before I create one?

**Comment by Jegelewicz** [comment]
How DO you create an Accession right now? I cannot see a path!

**Comment by campmlc** [comment]
There was an Accession: Create at one point .. . seems to be gone?
We should have
Accession: Create
Accession: Search
and replace the Accession and Loan Search with Transaction Search

**Comment by campmlc** [comment]
Can still get there from editing one: 
https://arctos.database.museum/accn.cfm?action=createForm

**Comment by acdoll** [comment]
> @dustymc How DO you create an Accession right now? I cannot see a path!
> 
> This goes to a blank page - https://arctos.database.museum/accn.cfm

My registrar is looking for this too. I see you've put this in next release now - thanks.

**Comment by dustymc** [comment]
In case this isn't all clear, next release is...

<img width="293" alt="Screenshot 2023-04-17 at 11 46 06 AM" src="https://user-images.githubusercontent.com/5720791/232581947-f78dabeb-e504-4750-a1ab-24b6f3145581.png">

... new buttons in results.

IDK what (if anything) happened to the directory, I think that's still being discussed, anyone with global_admin can update that at any time.

**Comment by Jegelewicz** [comment]
The above is nice and all, but this should be a menu item in the Accession, Loan and Permit Tile. You shouldn't have to search accessions before creating one.

So I'll ask as best I know how. Can we create a menu item

Accession: Create that goes directly to Can still get there from editing one:
https://arctos.database.museum/accn.cfm?action=createForm

?

**Comment by campmlc** [comment]
Absolutely support this. It should never have disappeared in the first
place.

**Comment by dustymc** [comment]
>Can we create a menu item

Accession: Create that goes directly to Can still get there from editing one:
https://arctos.database.museum/accn.cfm?action=createForm

Yes, there are inline docs, or see eg Search Collecting Event at test for a demo.
