### ISSUE TITLE
Add Arctos record urls in linked resources in Symbiota portals

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6093]
`@dustymc they actually do have our urls - sorta. See https://swbiodiversity.org/seinet/collections/individual/index.php?occid=19233620`

![image](https://user-images.githubusercontent.com/5725767/229943064-b700e4b3-1e33-4caf-ade9-75dfd800ba60.png)

`We need to work with them to have the catalog record urls placed in Linked Resources! Then we might move one step closer....`

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/arctos/issues/4643#issuecomment-1496714799_

**Comment by Jegelewicz** [comment]
I'll put this on the list of things to talk to Symbiota about.

**Comment by Jegelewicz** [comment]
> Hi Teresa,
> 
> Oo, this is a cool experiment!
> 
> Because the provided occurrenceID is a URL, there is automatically a link to Arctos on the public page of any record: https://lichenportal.org/portal/collections/individual/index.php?occid=1671100. Adding them to linked resources would do essentially the same thing, but would allow us to specify the relationship, as you've done in Arctos. So, if the purpose is providing a link, that's already done, but if the purpose is providing a semantic link, perhaps adding the links via linked resources would be a good extra step.
> 
> I'm trying to find a fitting term from the [Relationship Ontology](https://www.ebi.ac.uk/ols/ontologies/ro) that we could use to link these records (we currently don't have an equivalent of "same individual as" in our controlled vocabulary, and the rest of our terms from from the RO,apparently). Source? Reciprocal of? None of them seem quite right. We don't need to follow the RO, but it would be nice.
> 
> In any case, we could add a stored procedure to our imports from Arctos that automatically creates the crosslink from the Symbiota portal to Arctos upon update in Symbiota, which would be really cool.
> 
> As for cross-linking back to Arctos, I think this would be relatively straightforward: you can create the URL to any specimen by adding the base url (e.g., https://portal.torcherbaria.org/portal/collections/individual/index.php?) plus the occid value, also known as the "id" value in a DwC export of the records. I'll bet you could extract the ids from our API, once it's up and running. In the meantime, you could batch load them.
> 
> Best,

~Katie

**Comment by Jegelewicz** [comment]
> Katie,
> 
> Yeah - I was definitely thinking about providing information about the link. Same individual as probably does it, although in this case, they are the same object as, which is a bit different (duplicate herbarium sheets from the same collecting event = "same individual as", vs. data about the the same sheet = another identifier for the object or in Arctos we use "self").
> 
> Check out this one! https://arctos.database.museum/guid/UTEP:Herb:26769 
> 
> > we could add a stored procedure to our imports from Arctos that automatically creates the crosslink from the Symbiota portal to Arctos upon update in Symbiota, which would be really cool.
> 
> Love it! 
> 
> >  : you can create the URL to any specimen by adding the base url (e.g., https://portal.torcherbaria.org/portal/collections/individual/index.php?) plus the occid value, also known as the "id" value in a DwC export of the records. I'll bet you could extract the ids from our API, once it's up and running. In the meantime, you could batch load them.
> 
> The API will be fantastic! This is how we add the GBIF, iDigBio, and GloBI identifiers to the Arctos catalog records now. Waiting impatiently for that API!!! In the meantime, I'll see if I can find time to do a download/upload.
> 
> Next up will be how to add the relationships including hosts, parasites, etc. You can see our entire code table of relationships [here](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctid_references). Which is why I asked about definitions for the relationship terms you guys are using. we will need to map the two if we want to make them work between Arctos and Symbiota.
> 
> Good times!

Teresa J. Mayfield-Meyer

**Comment by Jegelewicz** [comment]
> Hi Teresa,
> 
> I didn't find a "same individual as" in the relationship ontology (https://www.ebi.ac.uk/ols/ontologies/ro). Did you find an equivalent? This could be used in cases of the exact same object, but it gets more tricky with botanical duplicates, as you know...botanical duplicates are the same population, but they might not be the same individual as another member of the duplicate cluster. It's almost like we need to start tracking whether duplicate specimens are part of the same individual or just additional individuals...perhaps a 15 year goal, haha!
> 
> Yes, the API is almost there! I'll bring this up at the next Symbiota core team meeting. The part of the API that would facilitate this might already be ready.
> 

Best,
~Katie

**Comment by Jegelewicz** [comment]
> Katie,
> 
> I don't find the OBO to be very useful - it is cryptic and lacks good (or any sometimes) definitions as far as I can tell.  But perhaps I am missing something.
> 
> [same individual as](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctid_references#same_individual_as) seems fairly equivalent to [organism or virus or viroid](https://www.ebi.ac.uk/ols/ontologies/ro/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCARO_0001010)
> 
> As for the duplicates that aren't from the same plant (ugh botanists...) they might be [same assemblage as](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctid_references#same_assemblage_as) in Arctos (although I would pretty much guarantee they have been related as "same individual as") or in OBO, [member of](https://www.ebi.ac.uk/ols/ontologies/ro/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002350)?
> 
> This is just another of those dark corners of biology where people "know what they know" and there are no good methods for describing relationships across disciplines. OBO may be a start, but I find it to be haphazard and not very informative. When "organism or virus or viroid" has an actual definition that makes the term understandable, this might be something to actually use. Just my opinion - not that of anyone I may appear to represent!
> 
> Keep us posted on the API!
> 
> Adios,


Teresa J. Mayfield-Meyer

**Comment by Jegelewicz** [comment]
> Hi Teresa,
> 
> I agree about OBO. I wonder who (if anyone) is managing the Relationship Ontology, specifically. I know nothing about its background. It does seem to be missing some key relationships/terms.
> 
> Hm, for botanical duplicates, I wonder if [same lot as](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctid_references#same_lot_as) would actually be more appropriate, because we're talking about specimens of the same taxon collected in the same collecting event.
> 
> As for linking across specimens that are the exact same (i.e., they come from Arctos and we just have a copy in the Symbiota portal), should we just use [self](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctid_references#self)? They are the exact same entity, just displayed in different locations.
> 
> Thanks!

~Katie

**Comment by Jegelewicz** [comment]
> Katie,
> 
> According to the website -  "OLS is developed and maintained by the [Samples, Phenotypes and Ontologies Team](http://www.ebi.ac.uk/about/spot-team) at EMBL-EBI."  More volunteer labor now that their funding has expired?
> 
> "OLS is supported in part by CORBEL funded by the EU’s Horizon 2020 research and innovation programme (2014–2020) under grant agreement number 654248 and previously by [DIACHRON](http://www.diachron-fp7.eu/), EU FP7 Capacities Specific Programme,/grant/agreement/number/284209."  
> 
> I don't think that reliance upon volunteers is the path forward for biological data, but it seems like it is where we are. :-(
> 
> for botanical duplicates, I wonder if [same lot as](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctid_references#same_lot_as) would actually be more appropriate, because we're talking about specimens of the same taxon collected in the same collecting event.
> 
> That would probably be a decent choice. In Arctos, these things may or may not have an explicit relationship because they "should" share a collecting event. So, depending upon a given collection (or even person doing data entry) the relationship might just be inferred due to the shared collection event. Sigh!
> 
> As for linking across specimens that are the exact same (i.e., they come from Arctos and we just have a copy in the Symbiota portal), should we just use self? They are the exact same entity, just displayed in different locations.
> 
> Yes - I think self would be appropriate.
> 
> Adios,

Teresa J. Mayfield-Meyer

**Comment by Jegelewicz** [comment]
> Hi Teresa,
> 
> Happy Easter to you too, haha!
> 
> I chatted with Ed, and it looks like the API is already running for the TORCH portal. Here's the base url you can use:
> 
> [https://portal.torcherbaria.org/portal/api/v2/occurrence/](https://portal.torcherbaria.org/portal/api/v2/occurrence/12500194)
> 
> Normally, you would be able to put an occurrenceID value at the end, and it would result in all the data associated with that specimen, but because the Arctos occurrenceIDs are links, it's not resolving those at the moment. You can alternatively use catalog numbers or any other provided identifier, until that's fixed.
> 
> An alternative way that we could set up a linkage back to the Arctos record can be seen on this record: https://portal.torcherbaria.org/portal/collections/individual/index.php?occid=12500194. Note the "Arctos record:" listing on the bottom of the page.
> 
> Since the data from this collection aren't being pushed to any aggregators from Symbiota, it's not imperative that there's a semantic link between the two records online using Linked Resources, but it's not wrong to do either.
> 
> Best,

~Katie

@dustymc what do you need to be able to use their API?

**Comment by dustymc** [comment]
>@dustymc what do you need to be able to use their API?

An example of a result using some Arctos identifier would do it - something that responds to https://arctos.database.museum/guid/UTEP:Herb:26769 would be ideal, but UTEP:Herb:26769 would also work (with the understanding that it might do something crazy from time to time because that's not necessarily a unique identifier)

**Comment by Jegelewicz** [comment]
Katie says you can use catalog number:

![image](https://user-images.githubusercontent.com/5725767/231842155-b74fc666-365a-4a0a-ad3e-9f4e5ae25002.png)

Can we try it out?

**Comment by Jegelewicz** [comment]
>  provide a functioning example.

https://portal.torcherbaria.org/portal/collections/individual/index.php?occid=12500194

https://arctos.database.museum/guid/UTEP:Herb:26769

Can we use the Symbiota API to add the identifiers as we do GBIF and iDigBio?

Found in https://github.com/ropensci/SymbiotaR2

> Determine the URL of the Symbiota2 portal you wish to access data from; its "API endpoint" is probably its web address with "api" appended to it (see below). Remember that your particular portal may not have enabled data download.

If this can't be done and all the identifiers have to be added manually, then I say we close this.

**Comment by Jegelewicz** [comment]
Nobody really cares about this - closing
