### ISSUE TITLE
subject matter attribute search

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6095]
Wonderful, thanks Dusty! I notice that if I start typing a term, a list of terms containing those letters does not appear like it does when we search culture of origin, for example. Also, when I click subject matter, the documentation box says "No documentation is available for subject_matter."

_Originally posted by @krgomez in https://github.com/ArctosDB/arctos/issues/5460#issuecomment-1497767501_

**Comment by krgomez** [comment]
I have just one more request --

For culture of origin, the documentation box has a link to the controlled vocabulary: 
![Screen Shot 2023-04-06 at 10 11 40 AM](https://user-images.githubusercontent.com/40579515/230460992-33bc4c4a-a882-4eed-ac31-cc1420d1ff99.png)

but subject matter does not: 
![Screen Shot 2023-04-06 at 10 12 41 AM](https://user-images.githubusercontent.com/40579515/230461092-0d29b817-54c4-4396-bb5e-34fbd4208836.png)

Could this be added? It's such a long list of terms that it would be helpful for users to know precisely what they can search.

**Comment by dustymc** [comment]
done
