### ISSUE TITLE
search UI customization proposal - do more with profiles

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6096]
# Shortform Proposal:

Keep only Profile button, remove all other customization options.

-----------

**Is your feature request related to a problem? Please describe.**

See much of https://github.com/orgs/ArctosDB/projects/26/views/1 - search customization has become complicated, cluttered, etc.

**Describe what you're trying to accomplish** 

Simplify.

**Describe the solution you'd like**

1. Get rid of the red-circled stuff (various 'customize' options) on the screenshot below.
2. Keep the green-circled stuff ('profiles' button) on the screenshot below.

This does not involve any functionality change, it is just a simplification in the UI.

Profiles can be shared, so there would be a functional change on that front: Most users can probably find something they like instead of chasing checkboxes.

**Describe alternatives you've considered**

Don't, but it's fairly clear that some (most? all??) users are getting overwhelmed by the UI.

**Additional context**

It might be nice to create some 'Arctos'-created profiles for "normal" - uhh, whatever. "Tissue-centric vertebrate users" or ????. (I don't think profiles are going anywhere, so that can be done even if everything here is rejected.)

**Priority**

No technical rush, but I think a cleaner UI would benefit everyone and this would be an easy change (remove some code and retire some forms). This would also make a bunch of 'overwhelmed by the customize forms' issues irrelevant.

Here's what I'd like to get rid of (red), and the proposed replacement (green):

<img width="717" alt="Screenshot 2023-04-05 at 10 29 22 AM" src="https://user-images.githubusercontent.com/5720791/230160313-ad9b56dc-59ac-43b4-a79a-bd8ff24ef80d.png">

And the profiles screen in test ATM - note that only the circled bit would be relevant for most users most of the time.

<img width="1540" alt="Screenshot 2023-04-05 at 10 40 34 AM" src="https://user-images.githubusercontent.com/5720791/230160907-ea4b5214-0ffd-42da-a0a5-8f856775759b.png">

**Comment by Jegelewicz** [comment]
I need to try this out - I'll see if I can get to it this afternoon between meetings.

**Comment by ewommack** [comment]
Question: what happens if we want to add an option to our search?
Example: I may want to look at just species and geography most of the time, but for one specific search I need to turn on sex and if it has media too.

How do we get to add or take away more search features?

**Comment by Jegelewicz** [comment]
Ditto above for results. Sometimes, once I have my results, I just want to add one more thing in the view.

Maybe we still need the big customize buttons? Start with a profile, then if you really just need one more thing use one of these?

![image](https://user-images.githubusercontent.com/5725767/230212587-cf5f9599-6b51-4c54-abd1-cff8da47da59.png)

Kinda sucks, but I feel like the eventual result will be Profiles plus all of the customize thingees everywhere....

**Comment by campmlc** [comment]
I like profiles. I also very much like the interface for creating one. Can
we make that the default interface for customize search and results? It
could be the current abridged format.  Then the separate expanded customize
search and results form we are using now could be "advanced customize" ?

**Comment by dustymc** [comment]
>separate expanded customize search and results form we are using now could be "advanced customize"

I'm still up for anything, but I'm also not sure I'm being clear on this yet. **There's nothing "advanced" about the extra buttons and widgets and stuff**, everything those can do profiles can also do (other than confuse people and add clutter!). I'm 100% positive that there's no technical reason the profiles interface can't be the **only**, not just default, customization UI, and I'm still hoping that everyone's going to see the (obvious??) usability (and maintenance and etc) benefits of getting rid of 2 interfaces, 3 buttons, a column (and fair bit of the page) full of widget-thingees, and whatever I haven't yet found!

**Comment by Jegelewicz** [comment]
> I'm still hoping that everyone's going to see the (obvious??) usability (and maintenance and etc) benefits of getting rid of 2 interfaces, 3 buttons, a column (and fair bit of the page) full of widget-thingees, and whatever I haven't yet found!

Hope - but if this was what we actually experienced in test, then you would know.

**Comment by dustymc** [comment]
>actually experienced

If that's necessary, then I think so is some ability for me to spin up new instances. Could this somehow be clarified without becoming unsolvable? While I'd love to have some Amazon-level test environment, I think that's probably just a hard block in reality.

Imaging the buttons not being there doesn't seem difficult to me, imaging life without the [ customize ] widgets is perhaps more of a stretch, but minimally it would just be a slightly narrower "column" on the left. (IDK if that could be turned into another 'column' in the main search page or not.)

I'm pretty sure there are no technical problems with this and mostly-sorta-kinda sure that nobody's madly in love with the current UI, maybe I should just do it???

**Comment by Jegelewicz** [comment]
> maybe I should just do it?

Don't make it hard on yourself! Let's bring it up at AWG Issues and see how imaginative people are.

**Comment by dustymc** [comment]
>make it hard on yourself

Believe it or not, I'm always aiming for the opposite!

>AWG Issues

Sure, but it seems that's getting more and more behind - I wonder if that needs to move to weekly, or a much tighter schedule, or both, or ????????????

**Comment by Jegelewicz** [comment]
> more and more behind 

Just an announcement - I'll try not to have anyone spend time on it in the meeting - just get them to review this after.

**Comment by Jegelewicz** [comment]
Pretty sure nobody has reviewed. It's only been a week, but we didn't provide a deadline, so I guess you are g2g?

**Comment by AJLinn** [comment]
My only issue with this is the name of the button for casual users. 
"Customize" is pretty self-explanatory but a first-time public user won't know what "Profiles" means to them. Maybe you can make it "Customize / Profiles"?

**Comment by dustymc** [comment]
If the other stuff didn't exist, I think "Customize" would be sufficient.

**Comment by campmlc** [comment]
Is there a way to leave the option to "expand" the search results for each table? I use this alot when there is one thing I need to add, and I don't know exactly what it is called in the list. I agree with replacing customize with profiles. I'm just suggesting we keep the option to expand each table, and call it expand/basic instead of customize.

**Comment by dustymc** [comment]
>leave the option to "expand" the search results for each table

I do not know what this means, please clarify.

**Comment by campmlc** [comment]
And I also agree we should really figure out a way to run these through test first - rather than ironing out all the wrinkles in public or leaving problem issues hanging to result in annoyed users. 
Sounds like we need to address the following with TACC: feasibility of
1) more "resources" so our "cache" can refresh in real time, or at avoid the recent hangups?
2) a test box?

**Comment by campmlc** [comment]
> > leave the option to "expand" the search results for each table
> 
> I do not know what this means, please clarify.
The vertical oval encircling the "customize" options in each search tile: keep those, but rename as "expand".

![image](https://user-images.githubusercontent.com/14808196/231556789-5310c2d6-b3a4-4cb7-a023-efcbf6ebe516.png)

**Comment by dustymc** [comment]
>keep those, but rename as "expand".

That's not compatible with what I've proposed; it uses a form that I'm trying to get rid of. 

>figure out a way to run these through test first

There's no other path to production, I almost never get feedback on anything while its in test.

>so our "cache" can refresh in real time,

I do not understand how that's related to this.

**Comment by campmlc** [comment]
I'm asking if we can keep "Show all options" and "Reset to Basic" while getting rid of customize on the side bars of the search pane. I don't need elaborate customization here -just all or none, expand or reset.

**Comment by wellerjes** [comment]
> I'm asking if we can keep "Show all options" and "Reset to Basic" while getting rid of customize on the side bars of the search pane. I don't need elaborate customization here -just all or none, expand or reset.

Yes, I just came here to request this as well. I made my own "Reset to Basic" profile (to reset after I've been in another profile), but if everyone does this, there's going to be a million profiles in the dropdown.

**Comment by dustymc** [comment]
>request this as well.

That's still not compatible with what's been proposed.

>if everyone does this, there's going to be a million profiles in the dropdown.

We deal with millions of lots of things, it's not a big deal. Not a job for a select/dropdown, but there are lots of alternatives.

**Comment by Jegelewicz** [comment]
Let's make a "generic" profile that is "basic search" - everyone can use it - no need to create your own.?

**Comment by dustymc** [comment]
>a "generic" profile that is "basic search"

I think maybe a few of them - I'm not convinced there's one globally-useful view, but 3 or 4 or ?? might get most people pretty close.

Note that the owner is just a suggestion, so you can make that 'bird people' or 'ABC Institution" or whatever. (And then you can't delete, but ping me if you need that.) And as above that's still sorting itself out, so if we want to "pin" a few 'Arctos' profiles or whatever then that's possible (at least if we find some way to proceed with this).

**Comment by dustymc** [comment]
UI committee: do it, rename to "customize search and results", some sort of shortcut to a few preselected profiles ("everything", "default", ??)

**Comment by Jegelewicz** [comment]
customize search and results - goes to where "profiles" does now
simple search - basic search (whatever that is now)
advanced search - expand all

**Comment by dustymc** [comment]
@Jegelewicz please let me know when I can do this, or if it needs to go through arctos-dev.....or if we're going somewhere else??

**Comment by Jegelewicz** [comment]
Dropdowns for Basic and Advanced Search with these

- Cultural Collections Preset
- Art Collections Preset
- Archives Preset
- Paleo Collections Preset

Plus a button for "Customize Search & Results"

**Comment by acdoll** [comment]
Something like this:
![image](https://user-images.githubusercontent.com/12507297/235006246-0d667560-34bb-46ec-9216-de7871df99b2.png)

**Comment by mkoo** [comment]
@AJLinn Please note that we are moving some "profiles" to a more prominent place on the main search page. EH, Art profiles will now be in a dropdown soon to be called  "Search Presets" (no longer buried)

We will use what you have already supplied in profiles-- is that a good plan? If you need to revisit it, let Dusty know since it will be hardcoded in the dropdown. However, that doesnt mean a user cannot still customize. Users can still pick that and then click on Customize Search and Results for detailed changes.

The UI group met today and wanted to be able to have the cultural collections also weigh in on these changes and tweaks. Let us know if there's others who have the bandwidth to weigh in and I'll contact too

(BTW for now, the Advanced button, in Andy's mockup above, will simply give all the search fields -- for the brave)

**Comment by dustymc** [comment]
UI Committee even later: do something, try to get it close to what we talked about.

@ewommack will send message monday, this can go to prod ~wednesday

**Comment by dustymc** [comment]
I need preset profiles. Lacking other direction, I will clone

* a 'default' profile, but 
    * that's semi-arbitrary things from an old system and now might be a good time to update, and
    * the name still bugs me, especially if its going to include any discipline-specific stuff
* 'art' (from uam_art)
* 'ethnology' (from uam_eh)

Please let me know the profile name of anything else which should be hard-coded into the shortcut selector. You may need to create profiles to get a name - you can delete them after I've made my protected clones if you wish.

And I still think 'everything' is more than a little silly, but if someone wants that option please just make a profile.

**Comment by AJLinn** [comment]
>  @AJLinn Please note that we are moving some "profiles" to a more prominent place on the main search page. EH, Art profiles will now be in a dropdown soon to be called "Search Presets" (no longer buried)
> 
> We will use what you have already supplied in profiles-- is that a good plan?

Thanks for the heads-up and sorry I was unable to attend the UI meeting yesterday. In the new model will our dedicated URL no longer take folks to a pre-designed custom profile? 
https://arctos.database.museum/uameh

We have this link embedded in several locations so I'll just need to know if I need to update it.

**Comment by dustymc** [comment]
@AJLinn nope, you don't need to do anything, that will keep doing what it does.

Unless I hear something else I'll clone your profile (your shortcut link minus the ``&guid_prefix=UAM:EH`` bit) into an 'Ethnology & History Preset' option. The presets will just make the most basic options available  as a sort of one-click shortcut. Users can still set up their own (optionally starting with the presets) if they want, and of course anyone can combine profiles (presets or otherwise) with search criteria to build things like your ``https://arctos.database.museum/uameh`` link.

**Comment by ewommack** [comment]
> @ewommack will send message monday, this can go to prod ~wednesday

@dustymc 
I've added a newsletter article to go out tomorrow. Check out: https://github.com/ArctosDB/newsletter/issues/235

**Comment by dustymc** [comment]
I've got this running with a single (but replicated at top and bottom) dropdown in an effort to reduce clutter. I think that's probably the least-confusing thing (and the multiple buttons have obviously been leading to confusion), but It's easy enough to add buttons if I'm giving weight to the wrong thing.

(I think it didn't get an Issue, but I somehow managed to remember someone asking for used search term highlights, that will be in next release too.)

<img width="947" alt="Screenshot 2023-05-02 at 8 09 15 AM" src="https://user-images.githubusercontent.com/5720791/235707891-0346c43b-834e-4f69-bf67-c636f5e813bc.png">


<img width="360" alt="Screenshot 2023-05-02 at 8 07 08 AM" src="https://user-images.githubusercontent.com/5720791/235707333-1f8db879-c233-448b-b045-d9c353026389.png">

Its easy to add more 'presets' but those are hard-coded, I need a profile to copy and some warning (so like NOW for anything that's going to be in first release!).

The profile UI at the moment:

<img width="1589" alt="Screenshot 2023-05-02 at 8 10 38 AM" src="https://user-images.githubusercontent.com/5720791/235708221-473228d2-22cc-4b24-a565-01facff2ad34.png">

I have a bunch of 'compacting code' on the control panel, which lets me give some more space to the selectors. 

The control panel should be happy enough with very long names/descriptions, which are toggle-truncated.


<img width="916" alt="Screenshot 2023-05-02 at 8 12 21 AM" src="https://user-images.githubusercontent.com/5720791/235708840-8bb71e67-b005-451e-92a4-ef5153c81c49.png">

<img width="504" alt="Screenshot 2023-05-02 at 8 12 32 AM" src="https://user-images.githubusercontent.com/5720791/235708887-6d28eeca-c9cc-403e-af7c-7b85c048e71b.png">


<img width="493" alt="Screenshot 2023-05-02 at 8 12 42 AM" src="https://user-images.githubusercontent.com/5720791/235708916-22948cd1-0a4e-4f82-9686-b14045553f69.png">


Definitions are now behind fontawesome see/stop icons


<img width="296" alt="Screenshot 2023-05-02 at 8 14 18 AM" src="https://user-images.githubusercontent.com/5720791/235709192-4369325a-d847-4db8-b4a0-4fc11ccf5863.png">

<img width="365" alt="Screenshot 2023-05-02 at 8 14 28 AM" src="https://user-images.githubusercontent.com/5720791/235709263-430d98a7-b1c6-40ef-a625-ab694214b4cd.png">

which I think is a pretty nice balance between clean and compact and "there when you need it."

I considered merging options (1) and (2), but (1) provides better "linkability" - eg if I 

* adopt a profile
* search
* reload with shareable URL

I get something like 

https://arctos-test.tacc.utexas.edu/search.cfm?cat_num=12&sp=%F0%9F%A4%A1%20%F0%9F%A5%9C

which takes a user to specific data in a specific layout, which I think is pretty cool.

I'm still working on a million details, but I think the general shape won't change too radically except by intent. Please let me know ASAP if any of that seems too far out of line.

**Comment by Jegelewicz** [comment]
I took a quick peek

Why are somethings highlighted from the beginning? This is the "basic" preset - why the random red box?

![image](https://user-images.githubusercontent.com/5725767/235732301-4d3a48ea-4d39-46a5-8ce0-982a218a8b66.png)

Honestly, I feel like the other identifier ends up in all of my "save as shareable url"s...

**Comment by dustymc** [comment]
>why the random red box?

Because you've selected something! (And your profile has remembered it, I think.)

>other identifier 

Custom identifier - yea, the weird thing is weird.

**Comment by Jegelewicz** [comment]
What is this physics? I don't think we should expect "spooky red boxes when Arctos feels like it"!

**Comment by dustymc** [comment]
It's there because you put it there, I don't know how to explain that better.

**Comment by Jegelewicz** [comment]
I put it there by selecting the BASIC PRESET I am saying that I don't think it should be included in the BASIC PRESET!

**Comment by dustymc** [comment]
>by selecting 

Ah - no, by https://arctos.database.museum/myArctos.cfm

<img width="451" alt="Screenshot 2023-05-02 at 10 41 02 AM" src="https://user-images.githubusercontent.com/5720791/235743124-faeb3df2-faa8-470c-8073-d8f1f81e22d7.png">

**Comment by dustymc** [comment]
done

**Comment by acdoll** [comment]
@dustymc This looks great! Seems like you caught most everything from the other day. I like the Customize dropdowns - seems efficient; and the viewable definitions work really well. The highlighted search terms is going to be a life-saver for me! Nice work!
