### ISSUE TITLE
Feature Request - flattened single identifier format

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6098]
**Is your feature request related to a problem? Please describe.**

Some identifiers exist in FLAT, https://github.com/ArctosDB/arctos/issues/6097 will add more. The function which flattens identifiers does not currently consider anything beyond display_value. It should.

**Describe what you're trying to accomplish** 

Make identifiers more useful/understandable as columns in tabular views.

**Describe the solution you'd like**

An example collector number from the current function:

```
  select concatsingleotherid(collection_object_id,'collector number') from coll_obj_other_id_num where other_id_type ='collector number' and issued_by_agent_id is null limit 1;

 concatsingleotherid 
---------------------
 3533
```

What I propose to do:

```
-- no issuer==no change

select concatsingleotherid_maybenew(collection_object_id,'collector number') from coll_obj_other_id_num where other_id_type ='collector number' and issued_by_agent_id is  null limit 1;


 concatsingleotherid_maybenew 
------------------------------
 3533


-- with issuer, include that as a sort of prefix

  select concatsingleotherid_maybenew(collection_object_id,'collector number') from coll_obj_other_id_num where other_id_type ='collector number' and issued_by_agent_id is not null limit 1;

 concatsingleotherid_maybenew 
------------------------------
 Arthur H. Harris 4885

```

**Describe alternatives you've considered**

Most anything's possible...

**Additional context**

Note that this DOES NOT in any way affect data, this is simply how some data are formatted for specialized display.

This does not need to compete with the JSON view, nor with the view from Arctos GUID pages - eg the agents don't need linked and etc., this should just be enough information to better understand the identifier when it's acting as a column in a table.

**Priority**

Wildfire - I need to get some things cleaned up ASAP - but (at the cost of perhaps several days of processing) this could be adjusted at any time; it's not completely critical that the first pass be perfect.

**Comment by Jegelewicz** [comment]
```
concatsingleotherid_maybenew 
------------------------------
 Arthur H. Harris 4885
```

I like this.

**Comment by campmlc** [comment]
Me too. Looks good.

**Comment by Jegelewicz** [comment]
@dustymc I was working on some LACM stuff this morning and I wonder if using the label name type for this would make sense?

For Art, if his label name type is "AHH", then it would simplify this even more. You would have:

```
concatsingleotherid_maybenew 
------------------------------
 AHH 4885
```

or maybe we should introduce a new name type = identifier acronym to make this very clear? Although, this would mess with @ebraker who put that acronym in front of all of her identifiers already plus a lot of collector numbers already have an associated acronym. OK, just leaving this here for consideration.

**Comment by dustymc** [comment]
> label name type for this would make sense?

It can't - it doesn't exist for most things, might exist in 5000 variants for others, etc. I can help build labels that use that or whatever, but I can't use it globally. 

And, I think this will matter most when it's detached from the agent. In Arctos you'll click a link and it'll tell you that AHH is https://arctos-test.tacc.utexas.edu/agent/1008959. In GBIF etc., there are orders of magnitude more AHH than Arthur H. Harris, the most-clear form will do the best job of - well, being clear!

Even Arctos can't turn those initials into a name:

<img width="193" alt="Screenshot 2023-04-06 at 7 39 45 AM" src="https://user-images.githubusercontent.com/5720791/230413766-4af8fcb7-faa7-4638-827f-d31c9c8d9066.png">

**Comment by dustymc** [comment]
done
