### ISSUE TITLE
Code Table Request - Formation needed for paleo/geo

### ISSUE THREAD

**Issue by babogan** [ArctosDB/arctos#6099]
## Initial Request

_**Goal**: I would like to add a new formation to ARCTOS. The formation is legitimate and is needed for my bulkload: https://macrostrat.org/sift/#/strat_name_concept/1767
--
_**Proposed Value**: "Gasper Limestone Formation"
--
_**Proposed Definition**:
Meramecian - Chesterian
--
336 - 331 Ma
2,889 km2
≤ 275 m thick
--
_**Context**: It is a formation that needs to be added as it is not there and there is no synonymy
--
_**Table**:  https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlithostratigraphic_formation
--
_**Collection type**: Paleontology and Geology
--
_**Priority**: Not urgent
--
_**Available for Public View**: This should be available for pubic view
--
_**Project**: Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184)._
--
_**Discussion**: Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary._

## Approval

_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality)._

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection

_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation

_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

_Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel._

_Make changes as described above. Ensure the URL of this Issue is included in the definition._

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by Jegelewicz** [comment]
@Nicole-Ridgwell-NMMNHS please advise!

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I would just suggest adding a bit to the definition. Perhaps: 

A Mississippian (Meramecian - Chesterian) unit that outcrops in the southeastern United States.

**Comment by Jegelewicz** [comment]
And also - https://macrostrat.org/sift/#/strat_name_concept/1767

**Comment by dustymc** [comment]
I checked my boxes, but maybe the exemptions section needs to be more clear on that: I'm still relying on @Nicole-Ridgwell-NMMNHS et al, my input on new terms in existing rocks-n-such attributes isn't necessary or useful.

**Comment by Jegelewicz** [comment]
What @dustymc said.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> exemptions section needs to be more clear

So, someone with an exemption for particular tables (in this case me for taxonomy-like geology) can make an issue and add the code table value without approval, or they can add someone else's value without approval.

@babogan if your ok with the suggested definition I will add this.

**Comment by dustymc** [comment]
>without approval

More like you are the approval, but yea. Same goal as always: As little friction as possible while avoiding messes and retaining the ability to fix any messes that do get through (because they will, you can still blame me when that happens, but even then I'll probably be asking for some help in understanding things). Please let me know if I'm making any unfounded presumptions, otherwise thanks!

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
That makes sense!

**Comment by babogan** [comment]
Sounds good!

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Added. It will probably take at least a few hours to show up.
