### ISSUE TITLE
Feature Request - "filed under" checkbox on identifications

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#6102]
MCZbase has a nifty checkbox in identifications that operators can toggle on to indicate which identification a specimen/object is stored under (very helpful when physical collections don't reflect taxonomic updates and do not use container tracking). I think they call it "filed under" or "stored under" and it is only visible in curatorial view. Mock up below.

![image](https://user-images.githubusercontent.com/11336485/230439871-a68ee2df-e775-4ef4-8542-9ce586ac3dec.png)

I think we should incorporate something similar.

**Comment by dustymc** [comment]
They're claiming to store the conceptual.

The closest Arctos equivalent would be part attribute [location](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecpart_attribute_type#location), which is a sort of low-quality object tracking approach (but still involving things which can be stored!). It would be easy enough to write to that through some shortcut-or-whatever, and "some taxon" is a perfectly valid value, but I have no idea how that would be used from the thing which is not physical without adding a great deal of confusion.

**Comment by ebraker** [comment]
> They're claiming to store the conceptual.

Perhaps but it is a very tangible reality for a lot (most?) collections. The goal here is facilitating physical collections management while still allowing identifications to march onwards, sideways, whatever.

Identifications table:
My suggestion would be a simple yes/no field defaulted to no. There'd be no impact on ID sort order, just perhaps a dependency (can't delete ID when "stored under" = yes). 

vs.

Part attribute table:
It could make sense storing filed under info here, but ideally users would be able to use a pick list of existing identifications on the record rather than enter free text. In my scenario it would be redundant to apply this value to different parts of the same specimen, but maybe that's not the case for others.

**Comment by Jegelewicz** [comment]
Almost every incoming collection asks about this - they have their stuff arranged taxonomically and this would make it easy for them to find things while they are preparing to migrate to Arctos object tracking....

**Comment by dustymc** [comment]
>every

That doesn't make it any less wrong, but https://github.com/ArctosDB/arctos/issues/4829 would allow such things without desecrating the model so....

**Comment by dustymc** [comment]
Tabling this; it could be re-cast as an identification attribute (and maybe UI-magic??) request.
