### ISSUE TITLE
Feature Request - bulkloader column names

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6103]
**Is your feature request related to a problem? Please describe.**

https://github.com/ArctosDB/arctos/issues/5193 - we're rebuilding the bulkloader, that provides an opportunity to rename some stuff.

**Describe what you're trying to accomplish** 

More intuitive names.

**Describe the solution you'd like**

(These contain codejunk from my build scripts and github is going to mangle some stuff, but " id_made_by_agent_#i#_#a#" is "second agent for first identification" and etc.)

* taxon_name_#i# - it's not, rename to scientific_name?? plain ol' "identification"??
* id_made_by_agent_#i#_#a# - identification_#i#_agent_#a# ??
* made_date_#i# - identification_date_#i#
* sensu_publication_#i# - identification_publication_#i#

**Describe alternatives you've considered**

Don't - nobody should ever try to guess these anyway, this should always be generated by Arctos, the names aren't important as long as they're documented.

**Additional context**

I'm sure the current names are used in documentation and such, this may be asking for a mess, IDK, HELP!!

**Priority**

This will be resolved in some way by 2023-04-14. If there's easy agreement then we can change stuff, if not then whatever.

**Comment by Jegelewicz** [comment]
> taxon_name_#i# - it's not, rename to scientific_name?? plain ol' "identification"??

UM - I think the taxonomy committee has decided that it IS taxon name - see https://github.com/ArctosDB/arctos/issues/3258

scientific name is too biology oriented and identification just has so many possibilities for confusion with identifiers....

**Comment by Jegelewicz** [comment]
> id_made_by_agent_#i##a# - identification#i#agent#a# ??

id_determiner

**Comment by Jegelewicz** [comment]
> made_date_#i# - identification_date_#i#

id_date

**Comment by Jegelewicz** [comment]
> sensu_publication_#i# - identification_publication_#i#

sensu

unless this can mean things other than 

`as understood or defined by. used especially in technical taxonomic references.`

**Comment by dustymc** [comment]
>sensu

my only "objection" there involves consistency - 'identification_....' or 'id_...' (but the latter might be confused with identifiers - are they consistent??) seems useful from here.

>IS taxon name

We can call it whatever we want, but all sorts of manglings that result in something that is no longer a taxon name - which of course isn't called a taxon name in table taxon_name.... - happen here! 

identification_name to be consistent?????? Not sure I like that...

And in case I'm not being clear: I don't care, except on behalf of the folks who actually use this. if there's anything that's even sorta-contentious here then perhaps the whole issue should be dropped. If there's some way to easily make something more understandable then I can make it happen while I'm changing everything anyway, if not then we've got more important things to worry about.

**Comment by campmlc** [comment]
Classification_name??? 
I think I like " identification" . That seems distinct from identifiers to me. 
What works for a mouse and also the McCandless bus? @AJLinn

**Comment by Jegelewicz** [comment]
If we want to keep things brief - see my Column header prefix column in [Arctos Bulkloader Columns](https://docs.google.com/spreadsheets/d/1ssNP_jAiOok7TYIPq8b-OKcLCw9NngtCElPwbS6ajFo/edit#gid=0)

**Comment by dustymc** [comment]
>want to keep things brief 

I generally prefer clear, I'm not sure what's gained by brevity here (but I still have little opinion on this, I can roll with whatever makes ya'll happy!).

**Comment by Jegelewicz** [comment]
> what's gained by brevity here

Maybe nothing - but I find that sometimes it is hard to read these things when they are the length of a sentence. I don't really care - but I do think using some sort of recognizable prefix for each of these "sections" when we can have more than one makes sense.

**Comment by Jegelewicz** [comment]
Putting this here for now. [Bulkloader Rebuild](https://docs.google.com/spreadsheets/d/1qstLM0xpW8gkkEnRxUpZWOZGtJkv2NTu8zIgKxv-nYc/edit?usp=sharing)
