### ISSUE TITLE
Feature Request - please return Container: Bulk move CSV paste mode form

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#6104]
My scanner is set on csv so I always use the csv bulk move container form. We had recently discussed improvements to this form but now I see the form is gone! (replaced by a bulk upload link).

Please return the form! I do not want to have to fiddle with files offline to upload things every time I want to move a bunch of unit trays into a drawer (which is a LOT). 

The tab form remains so the csv form should remain (and the current name for that page on

https://arctos.database.museum/batchScan.cfm

is "CSV Paste mode"

not "CSV upload" so please return the form as it was (so I can 'paste' barcodes)

Thanks!

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.
high

**Comment by dustymc** [comment]
I need a link or annotated screenshot or something, I'm sorta-sure all proposed changes to that whole suite of forms got blocked and nothing has changed.

https://github.com/ArctosDB/arctos/issues/4290

https://github.com/ArctosDB/arctos/issues/1689

?????????

**Comment by DerekSikes** [comment]
Ah, I mis-clicked the ;'upload CSV file' which is like WAY TOO CLOSE to the other link - can those be separated by some space- a blank line or something? thanks!

**Comment by DerekSikes** [comment]
on this page: https://arctos.database.museum/batchScan.cfm

**Comment by dustymc** [comment]
Whew!

My hope is still to kill that form entirely, please see the above-linked (and blocked) issues.
