### ISSUE TITLE
Need Help with Arctos Error - 404 for https://arctos.database.museum/guid/UAM:Ento:482889

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#6106]
# Error Text
**Copy the text from the page and paste it here**

ERROR_ID 	908A0106-82D6-41E5-B9A93BE88E382848
ERROR_TYPE 	application
ERROR_MESSAGE 	404: GUID not found
ERROR_DETAIL 	UAM:Ento:482889 could not be resolved.

# Where it happened
**Provide a link to or a description of the page where the error occurred.**

cloned https://arctos.database.museum/guid/UAM:Ento:407674 and 

this is the clone: https://arctos.database.museum/guid/UAM:Ento:482889 but here I am 20?? minutes later and it's not appeared. I've had this happen before and I wonder if this could be given higher priority? When one expects a record to appear in a couple minutes and it sometimes takes dozens or more this is a problem.

Also, while I'm on this issue, previously when I cloned full catalog item I would get a link to the new record. Now I get a popup with the GUID that I have to copy & then paste it into a browser bar that has another record (replacing one GUID for the new one) then click refresh to see if the record has appeared.

Could we get the old functionality back of having a link to the new record?

I wonder if this is related to the wonkiness Carla was reporting on the cloning of localities?

AND... of course by the time I had waited 20+ minutes and then started  typing this issue, the record has appeared! But the problem persists - this cloning needs higher priority so background stuff doesn't delay it (and that link request).

Priority
medium

**Comment by dustymc** [comment]
https://arctos.database.museum/info/flat_status.cfm

If I had more CPU, I'd use it....

**Comment by DerekSikes** [comment]
We've asked many times for some added text to that flat_status page that explains what the numbers mean.

You look at it and know what it means, but I look at it and it means nothing. Please add something like "If this number is bigger than X then you'll probably see slow downs in Arctos" or something.

**Comment by dustymc** [comment]
If I knew how to be more clear, I'd have done so a long time ago. 

And I suppose if you knew what you need to know you'd have told me that too.

This might be a good topic for some sort of meeting - maybe whatever office hours has become?? @Jegelewicz help?

**Comment by campmlc** [comment]
We discussed this at the last AWG meeting - this is a recurrent, priority
request.

**Comment by Jegelewicz** [comment]
@dustymc any way to change priority - the way we can with component loaders? Otherwise, I do not have technical answers to why this take a while or what the numbers in flat status mean time-wise.

I'm in the Arctos Lunch space right now if anyone wants to jump in.

**Comment by dustymc** [comment]
>change priority

No, there's one one thing involved, it already gets all the priority.

> why this take a while 

Finite resources.

> what the numbers in flat status mean time-wise

Absolutely nothing (except zeroes, which would mean that everything's current) - there's a lot of complexity, updates are common, there's no predicting.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/5511
