### ISSUE TITLE
Broken link in Handbook search: How to Create a Citation

### ISSUE THREAD

**Issue by szaborac** [ArctosDB/arctos#6107]
I was searching for how to designation a holotype in an Arctos record, so from the Handbook page https://handbook.arctosdb.org/, I did a search on "holotype". Most search results are clickable and will send the user to the correct page, but "How to Create a Citation" doesn't. 

This does not block work, as I can get to the requisite page manually.

**Comment by mkoo** [comment]
HI Stephanie, do you mean this page?
https://handbook.arctosdb.org/how_to/How-to-Create-Citations.html

It is working for me (FF on Mac). Let me know how you are accessing and if it still is blocked or if you get an error message

**Comment by szaborac** [comment]
That is the page I am trying to get to, and it works fine - but it's not the bug. The link to that page, brought up from the results of the Search section of https://handbook.arctosdb.org/, is what's not working. 

I did try other searches on https://handbook.arctosdb.org/, and those links ARE working, so I'm pretty sure it's just a one-off bug.

**Comment by dustymc** [comment]
Do worse at searching. That UI is super twitchy, you have to have 3(??) results or they (maybe only some of them??) are not clickable.

**Comment by szaborac** [comment]
Woof. That's... kinda atypical behavior for search results. 
So, known issue?
