### ISSUE TITLE
Code Table Request - new examined_detected value = pathology

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6120]
## Instructions

_This is a template to facilitate communication with the Arctos Code Table Committee. Submit a separate request for each relevant value. This form is appropriate for exploring how data may best be stored, for adding vocabulary, or for updating existing definitions._

_Reviewing documentation before proceeding will result in a more enjoyable experience._

* [Issue Documentation](http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html)
* [Code Table Documentation](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html)
* [Video Tutorial - Submit a Code Table Request](https://youtu.be/t2jHbsRA3lk)

------------------------------

## Initial Request

_**Goal**: Describe what you're trying to accomplish. This is the only necessary step to start this process. The Committee is available to assist with all other steps. Please clearly indicate any uncertainty or desired guidance if you proceed beyond this step._

> See original comment https://github.com/ArctosDB/data-migration/issues/667#issuecomment-1244068562 and additional request in https://github.com/ArctosDB/arctos/issues/5087
> UWZM has some people interested in pathologies, but I also happen to know that there is some of this in UTEP:ES. They have pathology data that they would like to preserve and be able to search.

_**Proposed Value**: Proposed new value. This should be clear and compatible with similar values in the relevant table and across Arctos._

> pathology

_**Proposed Definition**: Clear, complete, non-collection-type-specific **functional** definition of the value. Avoid discipline-specific terminology if possible, include parenthetically if unavoidable._

> Use a more specific value if known. Abnormalities that may be markers of disease or injury.~~General non-normal conditions that include lesions, anomalies and antemortem trauma.~~

_**Context**: Describe why this new value is necessary and existing values are not._

> No pathology values exist in the code table

_**Table**: Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table or value. This may involve multiple tables and will control datatype for Attributes. OtherID requests require BaseURL (and example) or explanation. Please ask for assistance if unsure._

> https://arctos.database.museum/info/ctDocumentation.cfm?table=ctexamined_detected

_**Collection type**: Some code tables contain collection-type-specific values. ``collection_cde`` may be found from https://arctos.database.museum/home.cfm_

> Bird
> Mamm
> Herp
> Amph
> Rept
> Teach
> Fish https://github.com/ArctosDB/arctos/issues/6120#issuecomment-1503963499

_**Priority**: Please describe the urgency and/or choose a priority-label to the right. You should expect a response within two working days, and may utilize [Arctos Contacts](https://arctosdb.org/contacts/) if you feel response is lacking._

_**Available for Public View**: Most data are by default publicly available. Describe any necessary access restrictions._

_**Project**: Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184)._

_**Discussion**: Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary._

@ArctosDB/arctos-code-table-administrators @ehalverson26 

## Approval

_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality)._

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval (https://github.com/ArctosDB/arctos/issues/6120#issuecomment-1503963499)
- [x] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection

_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation

_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

_Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel._

_Make changes as described above. Ensure the URL of this Issue is included in the definition._

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by campmlc** [comment]
I support this. Please also add to Fish.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Does the definition need to note that this is for soft tissue pathologies since pathology: skeletal is also being added?

**Comment by dustymc** [comment]
My interpretation was that this was for unknown or general, and 'pathology: soft tissue' might be another value beside https://github.com/ArctosDB/arctos/issues/6119 - this would only be appropriate when a more-specific value isn't known. 

The intent and appropriate usage should be clarified in the definition before this proceeds, whatever that actually is.

**Comment by Jegelewicz** [comment]
General non-normal conditions that include lesions, anomalies and antemortem trauma. Please use or request a more specific pathology attribute when possible.

Better?

**Comment by campmlc** [comment]
"general pathology including lesions" - better than non-normal conditions

**Comment by Jegelewicz** [comment]
> "general pathology including lesions" - better than non-normal conditions

Using the term being defined in the definition is never a good way to go.....

**Comment by dustymc** [comment]
>General non-normal conditions

Is there data/an identified user for this? Do we really need this, or is bones+gooeystuff sufficient? Alternatively, do we need subdivisions of this?

(Assuming those questions have good answers, this is still fine by me with the clarifying definition.)

**Comment by campmlc** [comment]
General disease state, per https://en.m.wikipedia.org/wiki/Pathology

**Comment by ehalverson26** [comment]
I do like the subdivisions as we are going to using the "pathology: skeletal" frequently.  The "pathology: soft tissue" is interesting and could replace the general term. I find that most of the other pathologies we will be using will fall under pathogens (rabies) or parasites so I will be interested to know if others will find a general pathology and/or pathology: soft tissue useful.

**Comment by Jegelewicz** [comment]
OK - I just added this because it seemed weird to have the specific pathology without some general bucket to use - maybe we don't need this now, maybe ever? How about I close this and if someone ends up needing it, we can re-open?

**Comment by campmlc** [comment]
I support having a general pathology attribute. This is needed for Rausch
records as well as impending kit fox data.

**Comment by dustymc** [comment]
>close this and if someone ends up needing it, we can re-open?

Can we generalize that as part of the request procedure/template? I wasn't aware that this was theoretical, I would not have been so eager to consent if I would have been. That's clearly not a valid assumption, I doubt I'm the only one to have made it, suggest we alter the template to require data.

**Comment by campmlc** [comment]
It's not theoretical. We have these data. Besides, we need to use this value for both "examined for" and also detected. In all these attributes, we need a general option to be able to examine for general condition and detect a specific condition.

**Comment by campmlc** [comment]
#5087

**Comment by campmlc** [comment]
Can we go ahead and add this? MSB has existing (Rausch) and pending (endangered species recovery program) data to populate this. We also have general terms for every other category planned.

**Comment by Jegelewicz** [comment]
I don't think we yet have a working definition? How about this?

abnormalities that may be markers of disease or injury

from https://en.wikipedia.org/wiki/Pathology

**Comment by campmlc** [comment]
I like that.

**Comment by Jegelewicz** [comment]
Still needs boxes checked

@ArctosDB/arctos-code-table-administrators @dustymc

**Comment by campmlc** [comment]
I checked

**Comment by Jegelewicz** [comment]
added
