### ISSUE TITLE
Problems with MSB:Bird data entry

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6121]
**Describe the bug**
I entered three MSB:Bird records yesterday: MSB:Bird:51118,MSB:Bird:51518,MSB:Bird:51519.

The first one, MSB:Bird:51118, did not load, with an error: CAT_NUM (51118) is invalid (dup)
But when I search for this number using the search interface, nothing shows up. This number has been assigned to a record by @catherpes - so I can't change the number. I'd like to know what it is duplicate with?

The other two do not show up in the browse and edit tool under any search parameters I can find. Neither do they show up in an Arctos search.  I waited 24 hrs since data entry - but nada.
The search screen is acting weird - when I enter these numbers - nothing happens. But then, that is what happens with there are no results? 
Help please - I have to ship these items on loan this afternoon!
Priority: urgent

**To Reproduce**

**Expected behavior**

**Screenshots**

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by dustymc** [comment]
https://arctos.database.museum/info/flat_status.cfm

**Comment by campmlc** [comment]
What can we do to fix this? What resources do we need? We shouldn't have to wait over 24 hrs for 3 records to load???

**Comment by campmlc** [comment]
@mkoo

**Comment by catherpes** [comment]
This is frustrating. Would you please elaborate on what this means?

**Comment by dustymc** [comment]
There is a cache (because we have finite resources). Updating it takes some time. https://arctos.database.museum/info/flat_status.cfm attempts to explain that.

I'm merging this into https://github.com/ArctosDB/arctos/issues/5511 - this obviously needs make better in some way, but I don't know what that might be, maybe discussing in one please will lead somewhere useful.
