### ISSUE TITLE
Identifier search

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#6123]
Maybe I'm doing it wrong, but it seems like we are no longer able to do a search on multiple, non-consecutive identifiers. Eg.:
![image](https://user-images.githubusercontent.com/12507297/231508191-e14dbfc1-1bae-4bc1-886a-0af729b20713.png)
I can get a consecutive series by putting a range (eg.:14471-14475) in the Numeric field, but using comma separated values in either of these fields returns no results. Am I missing something here?

**Comment by dustymc** [comment]
That is a mistake, fixed for next release.

The logic is:

* if starts with = then exact (which provides a path to finding '14471,14475')
* else if contains comma then assume exact list item values (14471,14475 finds 14471 and 14475 and nothing else)
* else substring (14475 finds 14475  and 144759999999 and ....)

Anything that's potentially cryptic should have a mouseover display (but this one is lying at the moment...)

<img width="431" alt="Screenshot 2023-04-12 at 9 05 57 AM" src="https://user-images.githubusercontent.com/5720791/231517017-66299538-0707-4ee9-9076-d4dc4f420fd8.png">

**Comment by acdoll** [comment]
Thanks! RE mouseover: I don't see anything appear for these fields (chrome, firefox and edge). I've checked most of the fields and the only working mouseovers I see 'Any taxon, ID, common name' and 'Any Geographic Element'.

**Comment by amgunderson** [comment]
I am hoping to search for a comma list of other identifiers soon, when is the next release?

**Comment by dustymc** [comment]
I will get this out today.
