### ISSUE TITLE
Error on my part

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6124]
@dustymc I made the mistake of adding units to [storage temperature ](storage temperature [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecpart_attribute_type#storage_temperature))- and it isn't being used that way - can you fix that for me? A million apologies!

**Comment by dustymc** [comment]
I will need to lock the database and drop some constraints. I think I can do that without downtime, but it will probably be disruptive (hopefully for seconds, but ??). I'm not sure if we need to schedule that, or  ???

**Comment by dustymc** [comment]
See https://github.com/ArctosDB/arctos/issues/4242, nothing needs fixed.
