### ISSUE TITLE
Two Agents, Same Name: The Scott Jones Story

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6143]
We had an existing [Scott Jones](https://arctos.database.museum/agent/21258988) in Arctos. I just added a much better known Scott Jones, but I had to add a parenthetical remark to the high quality agent [Scott Jones (SI)](https://arctos.database.museum/agent/21348017) in order to add a person with the same name. I would bet that at some point in the future we will have two or even more different Scott Jones in Arctos. Can we do something better than parenthetical remarks in preferred name to allow them to exist side-by-side in Arctos and to ensure that people doing data entry realize they need to investigate and choose the correct agent?

I am guessing that students doing data entry will ignore the agent with the weird parenthetical and we will end up with people choosing the wrong thing.

**Comment by ewommack** [comment]
I ran into this here: https://github.com/ArctosDB/arctos/issues/5502

Where I could actually reach the agent that I created who was the same name. I suggested a verified different person flag.

**Comment by Jegelewicz** [comment]
This will continue to happen more frequently as we make better agents and I think we need to consider better ways of handling it than adding potential garbage to preferred name.

**Comment by dustymc** [comment]
>allow them to exist side-by-side in Arctos and to ensure that people doing data entry realize they need to investigate

That's the whole point of all the cleanup we've done, but we're stuck in the middle again. All agents should carry identifying information, ideally such that it can be compared to other data (so Arctos itself can check if things fit). 

Those look like duplicates to me - first glance fails to suggest that the new agent isn't just the old one with more information. Why's there no 'not the same as' relationship? How'd YOU know the old isn't the new, and why'd you not leave that somewhere on the old? How sure are we that the old is one entity? (I'd guess it's four people in a trench-coat, certainly two!) What do we DO about that; can that invoke some sort of special Community attention, or ???????

We need some sort of procedure or something, I think, and maybe some sort of explicit 'this looks like junk, use at your own peril' flag to mark things until we can figure out what to do and/or do it.

**Comment by Jegelewicz** [comment]
I doubt they are duplicates due to the types of collections - the one currently in Arctos may even be two or three different people.

![image](https://user-images.githubusercontent.com/5725767/231803390-eb05a345-d15f-4efd-be95-2a89d739085c.png)

and so, I decided to create an agent for the person I know to keep this mess out of it. FWIW Scott Jones (SI) is working in the marine environment and I doubt he was even alive in 1957. If he was, he was too young to be collecting and measuring lizards - https://arctos.database.museum/guid/UWBM:Herp:2661. I didn't do this lightheartedly and I am not making snap judgements.

![image](https://user-images.githubusercontent.com/5725767/231805937-4eaa89a7-8362-4d78-bbe0-17d4d144e7a9.png)

It feels awful to add some tacky parenthetical remark to this well-documented person and have the undocumented one get to appear as if it is perfectly fine. When will we feel that this is worthy of changing our view on preferred names?

I just created [Dan Richards (NPS)](https://arctos.database.museum/agent/21348023) is this the same person as [Dan Richards](https://arctos.database.museum/agent/21313221)? It is possible, but the one I created is a Marine Biologist and the one in use collected a single raptor in Colorado. Again, this is a fairly common name and I don't want to mix potential garbage into an agent if I don't have too.

**Comment by dustymc** [comment]
(And why am I not seeing that picture on https://arctos.database.museum/agent/21348023, assuming that's who that is?!)

**Comment by Jegelewicz** [comment]
No seeing the picture - go here https://naturalhistory.si.edu/staff/scott-jones which is also part of his agent page.
