### ISSUE TITLE
My handlers disappeared from Reports

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#6145]
Where did handlers go?

![image](https://user-images.githubusercontent.com/11336485/231827125-166adb9d-8ffb-404a-921c-e6ba0798ad1f.png)

They were also missing from another report but I was able to clone a similar one back in. I see that other collections might be in this same boat(?)

**Comment by dustymc** [comment]
I don't have any logs on that machine, so I'm probably not going to figure out what happened.

Going forward, please use the backup link

<img width="203" alt="Screenshot 2023-04-13 at 10 09 45 AM" src="https://user-images.githubusercontent.com/5720791/231834516-29da21e7-960f-494f-9cf1-3407b19330af.png">

often. I just grabbed one and left it in the recommended place, https://github.com/ArctosDB/arctos-assets

And please don't lose sight of the fact that the legacy reports *is* going to irrecoverably fail at some point. (And hopefully that confident statement will inspire it to outlive us all....)

Here's the data table from test, which should be a few months old.

[cf_report_sql(2).csv.zip](https://github.com/ArctosDB/arctos/files/11224721/cf_report_sql.2.csv.zip)

I would also HIGHLY recommend using the Download as CSV option on the new reporter. The arctos-assets repo is available for that as well. Or you can use the CSV tool to grab the whole table, cf_reporter - I stashed that there too.

**Comment by ebraker** [comment]
Thank you! That worked.

I also realize I had them pasted in the New Report Template Request issue #5266 

So they should be in the design queue...
