### ISSUE TITLE
Parts load from yesterday not visible

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6146]
OK, I know the answer is https://arctos.database.museum/info/flat_status.cfm

but I don't know what these issues are:

![image](https://user-images.githubusercontent.com/5725767/231865903-cd2cfffc-0eff-4000-9016-f8c86fe410f9.png)

I loaded 176 parts to the part bulkload tool yesterday and they aren't there anymore, but they also are not on the catalog records.

@dustymc First question - did I not load them - because I could have deleted them instead of loading them - if so, I'll just re-load. But my notes say I marked them to load and I don't want to load them twice. If I did load them - it sure is taking a long time to see them...

**Comment by dustymc** [comment]
That's not the main source of truth here, https://arctos.database.museum/info/component_loader_status.cfm is. Flat status will tell you if FLAT things have been processed, which probably isn't very interesting unless you are checking results/partdetail or something.

I'll need your CSV, or you can just check a record.

(And figuring out what those problems are is somewhere on my overwhelmingly huge list..)

**Comment by campmlc** [comment]
I loaded 3 records Monday and they didn't show up until Wednesday. In the meantime, they weren't in Browse and Edit. They didn't show up on a search. But in the search results, I got a message "showing 2 of 2 records" - but nothing populated the search results table. They were in limbo . . . existing and yet not existing. Before I realized that - I loaded one of the records a second time, thinking I must have accidentally deleted or not saved. But then I got the error that it was a dup catalog number . .  . yet, not visible.

**Comment by Jegelewicz** [comment]
I'm sorta hoping I accidentally deleted them instead of loading them....

[AJSA.csv](https://github.com/ArctosDB/arctos/files/11226323/AJSA.csv)

**Comment by dustymc** [comment]
```
UWBM:Mamm:75776,tissue,unchecked,in collection,2,hl,,,,part identifier,AJS 001,,,Burke Museum Genetic Resources Collection,,,preservation,frozen,,,,minus 80°C,,storage temperature,-80,celsius,,,minus 80°C,,,,,,,,,,,,,,,,,,,,,,
```
https://arctos.database.museum/guid/UWBM:Mamm:75776


<img width="1242" alt="Screenshot 2023-04-13 at 1 45 35 PM" src="https://user-images.githubusercontent.com/5720791/231878928-35b3e545-9b79-4f7f-80ec-0ea6166c2ba1.png">

??

**Comment by Jegelewicz** [comment]
Yes, ONE of them is visible - the rest are not?

![image](https://user-images.githubusercontent.com/5725767/231887484-d25ad9e1-996e-4943-94f8-23859c0c0d27.png)

https://arctos.database.museum/search.cfm?guid_prefix=UWBM%3AMamm&customoidoper=LIST&oidnum=AJS%25&partname=%3Dtissue

**Comment by Jegelewicz** [comment]
OK - I just figured it out - my csv was mangled and they all loaded to a single record. UGH!

Will unload and redo this.

**Comment by dustymc** [comment]
>ONE of them is visible

Oh

<img width="306" alt="Screenshot 2023-04-13 at 2 35 41 PM" src="https://user-images.githubusercontent.com/5720791/231888298-0e4cc862-e8ab-4dea-b210-8369b7be44b5.png">


DAMMIT STOP DOING THINGS ONE SECOND BEFORE I DO THEM - ha!
