### ISSUE TITLE
Feature Request - how to search on catalog records that have 'any' citation

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#6147]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

I see we can add 'citation title' as a search field to the search form and if I could search that as 'notnull' or with a wildcard, this would work. How do I search for catalog records that have at least one citation?

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.
high - needed for work

**Comment by dustymc** [comment]
https://arctos.database.museum/search.cfm?type_status=any

**Comment by DerekSikes** [comment]
is this Media type? that's not obvious if so

**Comment by ebraker** [comment]
@DerekSikes it's under Catalog Record:
![image](https://user-images.githubusercontent.com/11336485/231922530-c7b038fb-6f37-45d4-a049-babb1f5b050b.png)

**Comment by DerekSikes** [comment]
thanks!
