### ISSUE TITLE
Agent Merge Request

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6148]
Use this template when you discover two agents that you believe represent the same person or organization.

**Agent that should remain after the merge**

@jegelewicz just force-created agent [Katie Miller (CMB)](https://arctos.database.museum/agents.cfm?agent_id=21348029).

and there are now three marine-involved K Millers!  (All auto-linked from the new, plus something about birds which might be distinct.)

**Agent that will no longer remain after the merge**

disambiguated uniques

**Reason for merge**

I think we're making bigger messes, or this needs to be a higher bar, or ?????

See also https://github.com/ArctosDB/arctos/issues/6143

Please add this issue to the Agents Project

@ArctosDB/agents-committee

**Comment by Jegelewicz** [comment]
Agent Name | Link | what is known 
 -- | -- | -- 
Katherine Miller | https://arctos.database.museum/agents.cfm?agent_id=21282355 | Possible Auke Bay, AK Collector Agent (NOAA); UAM:Fish 2006
Katie Miller | https://arctos.database.museum/agents.cfm?agent_id=21332223 | DMNS:Bird 2012
Katie Miller (CMB) | https://arctos.database.museum/agents.cfm?agent_id=21348029 | Student at Coastal Marine Biolabs in 2013 

What are the chances that the student I created collected a fish in Auke Bay in 2006 as part of NOAA? Possibly, but when did she change from Katherine to Katie? Did this same Katherine/Katie collect 4 birds in Colorado in 2012, apparently as part of some activity of [Bird Conservancy of the Rockies](https://arctos.database.museum/agent/21252000)? 

Maybe two of these K. Millers are the same person, but the thing is, I know that all of the things related to Katie Miller (CMB) (when they get entered) were THAT Katie Miller. If we merge these - Katie Miller will suddenly be a single person who did all of these things and has all of this information associated with her. Does it matter? I don't know. But if someday one of these Katie Millers is the world famous taxonomist for some group, it would be nice to know that she is not being attributed with a lot of other Katie Millers' actions.

To some degree, I am just following the advice given [here](https://github.com/ArctosDB/arctos/issues/6114#issuecomment-1503685858). When possible, I am making an effort to use and enhance existing agents, but sometimes, it just doesn't feel right to take over a "generic" low-quality agent and assign what might be important information about what can be trusted to existing data using those agents.

Again, the fact that this very difficult task is being placed on incoming collections seems unfair and I am doing the best I can to make it less painful.

**Comment by dustymc** [comment]
>student I created collected a fish in Auke Bay in 2006 as part of NOAA?

Non-zero, probably.

>change from Katherine to Katie

Unless it's coming from them, I think that carries exactly no weight - "correcting" names with unsupported assumptions is a favorite hobby of a great many people, ask my kid....

>doing the best I can

I'm absolutely not claiming I'd have done anything different, I'm just trying to sort out some procedure-or-whatever that we won't regret in any foreseeable way. 

>very difficult task is being placed on incoming collections seems unfair 

I think it's fair that we ask them to not make the problem worse, but I don't know what that really means (for them or "us").

>following the advice given 

I was just asking questions!! (And my 'not the same as' relationship looks plain WRONG from this angle, you know nothing so you said nothing - perfect.)

>it would be nice to know that she is not being attributed with a lot of other Katie Millers' actions.

And that she's getting credit for her actions without having to somehow find all 48 slices of herself and somehow piece them together. And there's the big question I keep finding myself asking again: which of those scenarios is less-evil?

**Comment by Jegelewicz** [comment]
> without having to somehow find all 48 slices of herself 

But if she were here to review this - she could tell us. She could also find all of the possibles if we had the "potentially the same as" relationship, which I would happily add for these three and would allow for better review process by people who "know" these agents.

**Comment by dustymc** [comment]
>she could tell us.

If it was that clear we'd not be here and none of this would matter. And all 48 of the slices will end up representing like 12 agents too....

>"potentially the same as" relationship

Meh, these are already magicked by Arctos. MAYBE that'd be useful if 30 of the variants were spelled weird, but that's getting pretty stretchy.

**Comment by Jegelewicz** [comment]
Also, any of those could be

https://www.linkedin.com/in/km2019/

or

https://www.linkedin.com/in/katie-miller-a0776a222/

This is such a common name that making assumptions that any Katie Miller is any other Katie Miller seems impossible. That doesn't even get into the potential "Katherine" or "Kathy" or 

 Kathryn, Catherine, Kate, Katy, Kaytee, Kayteigh, Katerina, Caitlyn, Kathleen, Katayoun, Catie, Cathy, Cady, Ceitidh

**Comment by dustymc** [comment]
>assumptions that any Katie Miller is any other Katie Miller seems impossible.

Exactly!! That's the whole premise of all of the verbatimization and cleanup and such!

So whadawedoaboutit?

What do we do with the existing agents that don't have any information at all?

Are we creating agents with sufficient information, or do we need to somehow raise the bar? 

What can we DO with that information? (We should be pulling data from ORCID and then using that to check Arctos activity - which sounds pretty fun, and like something I may never get to.)

Etc. Minimally, how can we avoid making a bigger mess?

>Kathryn, Catherine, Kate, Katy, Kaytee, Kayteigh, Katerina, Caitlyn, Kathleen, Katayoun, Catie, Cathy, Cady, Ceitidh

You checked that those are all in https://arctos.database.museum/DataServices/agent_name_synonym_manager.cfm, right?

**Comment by Jegelewicz** [comment]
Here's one that demonstrates how hard this can be!

In Arctos we had [Marguerite Butler](https://arctos.database.museum/agent/10015030)

An incoming collection also has Marguerite Butler and you might just assume these are the same person. But they are not. I just added [Marguerite Butler (BAKX)](https://arctos.database.museum/agent/21348032).

Without review, the incoming collection would probably just have used the existing Marguerite Butler and whatever activity she did in that collection would be mis-attributed (and maybe relied upon more than it should be since one of these people is still working in "our" field).

**Comment by Jegelewicz** [comment]
> You checked that those are all in https://arctos.database.museum/DataServices/agent_name_synonym_manager.cfm, right?

Didn't know that was a thing I could do. Shouldn't that be here? Who can manage this?

![image](https://user-images.githubusercontent.com/5725767/232111710-de74e764-a368-44ba-9090-256ef58d8400.png)

**Comment by dustymc** [comment]
>Shouldn't that be here?

The thing that lets you move it will also tell you who can access it.

**Comment by Jegelewicz** [comment]
> The thing that lets you move it will also tell you who can access it.

Fair - but I am not moving or doing anything to that anymore because I don't want to screw something up - https://github.com/ArctosDB/arctos/issues/6144

**Comment by dustymc** [comment]
In that case see https://arctos.database.museum/directory.cfm?dv=table&access=all&directaccess=all

**Comment by Jegelewicz** [comment]
@ArctosDB/agents-committee should probably read this issue.

**Comment by ewommack** [comment]
@acdoll - can you help? Any data on Katie Miller who donated these birds? https://arctos.database.museum/agents.cfm?agent_id=21332223

**Comment by acdoll** [comment]
Nope. She was not our direct contact with RMBO (now BCR). The internet suggests that she did, in fact, work for them when these birds were collected: [https://www.birdconservancy.org/wp-content/uploads/2014/06/8-12-PrimSource-No42-smallest.pdf](https://www.birdconservancy.org/wp-content/uploads/2014/06/8-12-PrimSource-No42-smallest.pdf)
But whether she is the same person (or not) as these other K Millers, I cannot say.

**Comment by ewommack** [comment]
Yeah still more info!

**Comment by Jegelewicz** [comment]
Added email and phone to her agent from the newsletter.

**Comment by lin-fred** [comment]
Agents committee has decided to close this issue for now, there is at least information and data in these agent pages so we are going to leave as is.
