### ISSUE TITLE
Feature Request - ability to enter condition by date, agent

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#6149]
**Is your feature request related to a problem? Please describe.**
Add individual fields within condition.

**Describe what you're trying to accomplish** 
The text is currently an open field; I would like to be able to see more clearly when the condition of the specimen was accessed, by whom, how it has changed over time, when a repair was made, who made the assessment, etc. The taxidermy mounts on display at the museum get cleaned every year. Not all specimens are in cases; because they are on display and more exposed, these are more likely to sustain damage / have a lot of information within condition. If it were in an attribute, it would be easier to see a summary of how the condition changes over time. Ideally, I'd like an entry for each year there is an update / document how recently it was cleaned. By using attributes with required fields, we would have more consistent data for when and who the condition report was made.

**Describe the solution you'd like**
Along the lines of an attribute for location, preservation within remarks
attribute = condition
value = excellent, good, poor, fair
date = YYYY-MM-DD
determiner = person who did the condition report or assessment (linked to agent record)
remark = free text, allowing room for a description
method = free text, allowing room for how the specimen was cleaned or repaired

Example of a specimen that has a lot of information in condition: https://arctos.database.museum/guid/CHAS:Mamm:1600

**Describe alternatives you've considered**
Keep the free text and reiterate that name and date needs to be included with each update.

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by dustymc** [comment]
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecpart_attribute_type#condition_report

**Comment by wellerjes** [comment]
Aha! Thank you!
