### ISSUE TITLE
Missing Find Geography from Tools UI

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6152]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
We seem to be missing Geography: Find from the Places and Events tile. If there is somewhere else to find it, it's not obvious. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by Jegelewicz** [comment]
Search Places and Events
