### ISSUE TITLE
Need Help with Arctos Error 

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6153]
# Error Text
<html>
<body>

ERROR_ID | 3F7C3005-2DAE-4BAC-80074BBE1C28C730
-- | --
ERROR_TYPE | application
ERROR_MESSAGE | Error invoking external process
ERROR_DETAIL | psql:/usr/local/webroot/temp/excopy_campmlc_20230414050414607_285.sql:944: ERROR: null value in column "collection_object_id" violates not-null constraint DETAIL: Failing row contains (null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 2023-04-14 16:47:34.183547, null, null, null, null, null, null, null, null, null, null, null). CONTEXT: COPY bulkloader_stage, line 939: ",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,..."

</body>
</html>
**Copy the text from the page and paste it here**

# Where it happened
bulkloader

# Steps to get there
Attempt to load attached file. I've replaced all values in the collection object ID field - still same result.
[Bulkload File April 2023 all non-Holloman_for_bulkload_1.zip](https://github.com/ArctosDB/arctos/files/11237581/Bulkload.File.April.2023.all.non-Holloman_for_bulkload_1.zip)

# Problem
**Community response to describe the problem that caused the error**

# Solution
**Community response with directions for how to correct the problem**

**Comment by campmlc** [comment]
Excel shows no duplicates in the collection object ID field using conditional formatting - are these duplicates blank rows?

**Comment by Jegelewicz** [comment]
@campmlc remove the collection object id column and try again.
