### ISSUE TITLE
Attribute download error

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6154]
Attempting to use the attribute download tool on this set of serach results - https://arctos.database.museum/search.cfm?guid_prefix=UWBM%3AMamm&customoidoper=LIST&oidtype=preparator%20number&oidnum=%25

Getting this error

<html><body>

ERROR_ID | 1434FC7F-B541-4656-9A1C6CBEA17961DD
-- | --
ERROR_TYPE | application
ERROR_MESSAGE | unhandled file request
ERROR_DETAIL | Missing.cfm could not resolve a request.

</div>
</body>
</html>

**Comment by dustymc** [comment]
You're asking for more resources than I have. 

I can try to tune the query or explore the possibility of a CSV-only option if the bottleneck is in building the table.

**Comment by Jegelewicz** [comment]
I am also unable to get an identifiers download for this collection. The Identifiers table never finishes loading and my browser freezes. Can you get that for me?

**Comment by dustymc** [comment]
See "List of Attributes of a given type for a given collection by GUID" in the cheatsheet, and I just added "All Identifiers for a collection"

**Comment by dustymc** [comment]
done?
