### ISSUE TITLE
New Tools Directory menu Item - Accession: Create

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6155]
See https://github.com/ArctosDB/arctos/issues/6089#issuecomment-1512113969

Also I just received this

![image](https://user-images.githubusercontent.com/5725767/232625261-531437ee-ce90-42b7-b055-95ad1fba874a.png)

New collections cannot follow instructions to manually create their first accession.

Because there have been so many accusations about people changing the Tools Directory, I am unwilling to do so without express permission of the community.

Do I have permission to add this to the Accessions, Loans, Permits Tile?

Accession: Create that goes directly to https://arctos.database.museum/accn.cfm?action=createForm

AND

Do we need policies about who can change those things and what community consensus is involved? See also https://github.com/ArctosDB/arctos/issues/6152 and https://github.com/ArctosDB/arctos/issues/6105

**Comment by AJLinn** [comment]
> Do I have permission to add this to the Accessions, Loans, Permits Tile?

> Accession: Create that goes directly to https://arctos.database.museum/accn.cfm?action=createForm

I'd say yes from my small corner of the community.

> Do we need policies about who can change those things and what community consensus is involved? See also https://github.com/ArctosDB/arctos/issues/6152 and https://github.com/ArctosDB/arctos/issues/6105

Seems like this must be yes given the kafuffle the last week or so of missing tile links!

**Comment by campmlc** [comment]
I agree for both- and it is disturbing that there are changes that no one can account for. Is the interface so prone to accidental error?

**Comment by ewommack** [comment]
Go for it!

I'm so confused right now. I used to add Accessions one by one...but I can't remember where the tool was. Was the create Accession button in the Search Loan and Accession area? I'm not accusing or complaining, I'm just confused....

This is like that display case I swear we had in storage under the stairs, and now it is not there. Either display cases wander away (possible) or I am slowly going mad (also possible).

**Comment by Jegelewicz** [comment]
I followed the instructions and did this

![image](https://user-images.githubusercontent.com/5725767/232797865-7506462c-40d8-4f03-945c-c522c640dd7b.png)

and was rewarded with this

<html><body>


ERROR_ID | BD7DB6FB-0CB7-435C-B8C52EC013B1AF32
-- | --
ERROR_TYPE | SQL
ERROR_MESSAGE | ERROR: new row for relation  "cf_form_permissions" violates check constraint "check_relpath"   Detail: Failing row contains (514076966,  https://arctos.database.museum/accn.cfm?action=createForm,  manage_transactions, Accession: Create, Direct path to manually create a  single accession., Direct path to manually create a single accession.,  Accessions, Loans, Permits, null).
ERROR_DETAIL |  
ERROR_SQL | insert into cf_form_permissions ( 			form_path, 			role_name, 			header_title, 			description, 			internal_remark, 			category, 			pagehelp 		) values ( 			'https://arctos.database.museum/accn.cfm?action=createForm', 			'manage_transactions', 			'Accession: Create', 			'Direct path to manually create a single accession.', 			'Direct path to manually create a single accession.', 			'Accessions, Loans, Permits', 			null 		)


</body>
</html>

I don't know what is incorrect. @dustymc

**Comment by dustymc** [comment]
Absolute path

Not URI.

``/accn.cfm?action=createForm``


https://github.com/ArctosDB/arctos/issues/6105#issuecomment-1501907046

**Comment by Jegelewicz** [comment]
@dustymc DOH and Thanks.

OK - I think I added it. Waiting for it to show up in the Tile.
