### ISSUE TITLE
Feature Request - Places and Events search

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#6156]
This issue is an extension of https://github.com/ArctosDB/arctos/issues/6105

Currently, the "Places and Events" search is under the Search tile in the Tools Directory. The idea was to make the Directory and Search dropdown match. However, for operators looking for tools to manage data, the more intuitive place to find places and events is under the "Places and Events" tile. This has been a topic of discussion and it's moved back and forth. I think we need to revisit.

Users searching for records by place/event can do that in the basic UI search without using that option in the dropdown. I think it's more critical to make it easier for data managers to use the UI for searching Places and Events in order to clone, edit, etc. 

So it seems like the two options are:
1) remove from Search dropdown and Search tile, move to Places and Events tile
2) keep in Search dropdown, move to Places and Events - so those won't mirror each other
3) have them in both places but call them something different since you can't have the same thing in two tiles - this is confusing

As an aside, it also makes sense in the main search UI page to move Place above Event (switch the order) so at least the order would mirror.

**Comment by Jegelewicz** [comment]
I thought about this overnight - I think we should ditch the search tile and move all of those things to their "more intuitive" tiles:

Search tile | move to tile | New title
 -- | -- | -- 
[Agents](https://arctos.database.museum/agent.cfm) | Agents & Users | [Agent: Search](https://arctos.database.museum/agent.cfm) 
[Catalog Records](https://arctos.database.museum/search.cfm) | Records | {Catalog Records: Search](https://arctos.database.museum/search.cfm) 
[Code Tables](https://arctos.database.museum/info/ctDocumentation.cfm) | Data Quality | [Code Tables](https://arctos.database.museum/info/ctDocumentation.cfm) 
[Media & Documents](https://arctos.database.museum/MediaSearch.cfm) | Media & Documents | [Media: Search](https://arctos.database.museum/MediaSearch.cfm) 
[Places & Events](https://arctos.database.museum/place.cfm) | Places & Events | [Places & Events: Search](https://arctos.database.museum/place.cfm) 
X | Places & Events | [Event:Search ](https://arctos.database.museum/place.cfm?sch=collecting_event) 
X | Places & Events | [Geography: Search](https://arctos.database.museum/place.cfm?sch=geog) 
X | Places & Events | [Locality](https://arctos.database.museum/place.cfm?sch=locality)
[Portals](https://arctos.database.museum/home.cfm) | Community | [Collections: Search ](https://arctos.database.museum/home.cfm)
[Publications & Projects](https://arctos.database.museum/SpecimenUsage.cfm) |Publications & Projects | [Publications & Projects: Search](https://arctos.database.museum/SpecimenUsage.cfm) 
[Surprise Me!](https://arctos.database.museum/random.cfm) | Community | [Surprise Me!](https://arctos.database.museum/random.cfm) 
[Taxonomy](https://arctos.database.museum/taxonomy.cfm) | Taxonomy | [Taxonomy](https://arctos.database.museum/taxonomy.cfm)

**Comment by Jegelewicz** [comment]
If people want to search - they can find everything here too:

<img width="960" alt="Screenshot 2023-04-17 15 18 59" src="https://user-images.githubusercontent.com/5725767/232613136-1393e328-35b3-4366-bba6-035f0410c8f9.png">

**Comment by Jegelewicz** [comment]
See also https://github.com/ArctosDB/arctos/issues/5742

**Comment by campmlc** [comment]
I support that approach.

**Comment by dustymc** [comment]
done?
