### ISSUE TITLE
[CONTACT: Blocked Network]

### ISSUE THREAD

**Issue by Peterbillman** [ArctosDB/arctos#6157]
restricted IP: 172.226.93.152

Hi there, I'm unsure why my IP address has been blocked. I have used Arctos in the past to examine species' past distributions from museum records but never used any data for research purposes, data analysis, or the such. Is there anything I can do to regain access to the database? Thank you for your time!
-Peter

**Comment by dustymc** [comment]
The restriction has been removed.
