### ISSUE TITLE
Bulkloader Edit Tools needed

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6161]
@dustymc we discussed changes to the Browse and Edit tools so that it could be possible to edit an existing record prior to marking for load.
The existing editing functions associated with a key do not include the Pull function, or the ability to add extras. 
This means that if a student is using the single record data entry screen, and they forget to pull something from the host record, they cannot make these edits. Ditto if they forget to add a second preservation, eg frozen, if the first preservation is ethanol.
It is asking a lot of students to make it a requirement that they capture all necessary data exactly right in a first pass, without allowing subsequent editing on review. I'm not sure that is possible for humans, actually.

I would hope we could come up with an interface tool that would allow what the old deprecated form did - to access the same tools in edit view as we have in data entry view. Even if these are different tools under the hood - the functionality from the user interface should be the same.

Priority: Very high. We are hiring 4 new students to use this tool to capture parasite data from host records, for work that needs to be completed in the next 3 months.

**Comment by dustymc** [comment]
>Pull function

I'm pretty sure there's an issue for that, and duplicates prevent me from effectively dealing with problems. (Putting together a coherent package is part of what I'm hoping to accomplish with https://github.com/ArctosDB/internal/issues/258, but duplicates will still find a way to hide from whatever "finalize" process that might become.)

>ability to add extras.

That seems like more of a stretch than can be made, but https://github.com/ArctosDB/arctos/issues/4583 might provide something close (and https://github.com/ArctosDB/arctos/issues/6171 should make it largely irrelevant anyway).
