### ISSUE TITLE
Part Attribute Values and Units Don't Carry

### ISSUE THREAD

**Issue by AdrienneRaniszewski** [ArctosDB/arctos#6164]
**Describe the bug**
in the single record data entry screen, the extra part attribute values and units don't carry over even when set to carry over. They don't save to a new data entry profile either.

**Expected behavior**
I expect them to be filled out when I start a new record

**Desktop (please complete the following information):**
 - OS: MacOS 13.2.1
 - Browser: Chrome
 - Version: 112.0.5615.121

**Priority**
medium - need it fixed, but can manually re-enter them each time until then

**Comment by AdrienneRaniszewski** [comment]
After working with this a little more, I need to change this to high-priority. It really does slow down our workflow. And we have thousands of records to enter in the next few months.

**Comment by campmlc** [comment]
This is part of the grant funding from MSB to Arctos - so it is actually a funded mandate, for once!
Please help us get this moving, as we have students ready to start entering data.

**Comment by dustymc** [comment]
I'm not quite sure where to go with this. It's blocked by https://github.com/ArctosDB/arctos/issues/6171, which should also make it irrelevant. It's not *impossible* that we might add more capacity to extras, but I think it's probably complex enough that something like a new dedicated screen would be more sustainable. (And i occasionally wonder if a few simpler screens wouldn't be more sustainable than one hugely complex one anyway.)

**Comment by AdrienneRaniszewski** [comment]
I thought it was just a glitch. Everything else carries over as expected. It's just the part attribute values and units that I have to re-fill out every single time. even though they are set to carry over.

<img width="559" alt="Screenshot 2023-04-21 at 8 38 48 AM" src="https://user-images.githubusercontent.com/23192428/233664934-932515c6-0beb-4fc1-ba91-ad89359cbbb2.png">
<img width="646" alt="Screenshot 2023-04-21 at 8 38 23 AM" src="https://user-images.githubusercontent.com/23192428/233664954-4ea65242-34d4-4d0d-9f51-3fdb4e12f9a0.png">

**Comment by Jegelewicz** [comment]
>  if a few simpler screens wouldn't be more sustainable than one hugely complex one anyway.

I believe this is exactly what @campmlc and others have asked for previously (Enter all the general stuff -> hit continue, enter all the identification stuff -> hit Continue and so on).

But when done, a person would still need to be given an opportunity to review what they entered before committing it all to the bulkloader AND their supervisor wants to review it BEFORE it gets loaded too - maybe in the same section-by-section way or maybe all on one page. Can we have both or do we have to choose one way or the other?

**Comment by dustymc** [comment]
Oh  - sorry, I got lost and was looking at attributes, thanks for the screenshot.

<img width="378" alt="Screenshot 2023-04-21 at 7 45 46 AM" src="https://user-images.githubusercontent.com/5720791/233666031-ab8a5944-0eb2-4af1-bbcc-3c47dc312255.png">

<img width="883" alt="Screenshot 2023-04-21 at 7 45 18 AM" src="https://user-images.githubusercontent.com/5720791/233666417-3cc3a776-7498-4ce3-9b78-94c574c54e2b.png">

<img width="1111" alt="Screenshot 2023-04-21 at 7 45 39 AM" src="https://user-images.githubusercontent.com/5720791/233666439-4e7ab64e-61b3-4d29-a983-8eafe56ff669.png">

Works for me??

**Comment by campmlc** [comment]
I can confirm that yesterday on @AdrienneRaniszewski screen, not only did the part attributes not carry, but if she made any edits elsewhere on the screen, the part attributes she has entered disappeared. . .

**Comment by dustymc** [comment]
>Enter all the general stuff -> hit continue, 

That's not what I'm talking about (and Sybil had that and it was awful, nope...). 

By "simpler" I meant that this screen has some near-infinite number of states, and there's a lot of really complex code that makes it all work ("tolerably well for most users" or thereabouts, we hope). If there was real stability in the structure (and I think we're all agreed on that), then having a 'mammal screen' (or YOUR mammal screen, or even your bat screen - IDK what the limit might be) that has a field called 'sex' (hard-coded in, super-simple) rather than the wildly complex (and not cheap) thing that's currently used to create dynamic attributes for however many it is now collection types might be more approachable (or not, I don't know, we've never tried it - but it can't possibly be less-sustainable than continually increasing complexity without increasing resources!).

>disappeared

Check the settings - the thing that is acting mysteriously isn't in the provided screenshot, are you sure it's right?

If that doesn't do it, try ditching Chrome - it's PROBABLY not that, but I don't test in Chrome either.

This is network-intensive (see above) and UNM has a bit of a history of mysterious behavior on that front - can you try it at Starbucks or something?

**Comment by dustymc** [comment]
Tell me every click to get to wherever you are in as much detail as possible, maybe it's something about data or ???

**Comment by Jegelewicz** [comment]
Zoom up you guys - share a screen and demonstrate - it will make everything go faster...

**Comment by AdrienneRaniszewski** [comment]
I started with Mariel’s “ MSB:Para standard data entry” profile

Moved things around, customized sections to hide things I didn’t need

Ended up with what’s in the first screen shot

Saved as new profile “TPT"

Then when I was ready to enter data, I chose to use “TPT” from the profile list

The second screen shot is what I see. All is well, except the value and units in the extras parts section are not there

<img width="886" alt="Screenshot 2023-04-21 at 4 27 10 PM" src="https://user-images.githubusercontent.com/23192428/233744081-86233f2f-917e-423b-bb68-f0a02f26949c.png">

<img width="762" alt="Screenshot 2023-04-21 at 4 30 20 PM" src="https://user-images.githubusercontent.com/23192428/233744110-418de887-7b1c-4b41-ad13-d2acfc8f375e.png">

**Comment by dustymc** [comment]
Ah, thanks. Yea, the profile is bypassing the magic. I changed each of those (to whatever), then back to what you had, and I think it's working - pre and post save:

<img width="1135" alt="Screenshot 2023-04-21 at 3 38 24 PM" src="https://user-images.githubusercontent.com/5720791/233744753-2db06dd2-86b4-4e76-a4d4-9a01b8f3bcc5.png">

<img width="826" alt="Screenshot 2023-04-21 at 3 39 21 PM" src="https://user-images.githubusercontent.com/5720791/233744762-92f60a0c-a7e4-4158-aaf3-3e24839eeedb.png">

Not ideal, but maybe that's a sufficient workaround until we can find some way to move on https://github.com/ArctosDB/arctos/issues/6171?

# I saved at least one record in production

someone please nuke it at some point, it should be pretty easy to find.

**Comment by Jegelewicz** [comment]
I deleted it.

**Comment by AdrienneRaniszewski** [comment]
It's still not working for me. BUT when I start a new record via the TPT profile, if I don't blink, I can see the values in there for a split second, then they disappear.
