### ISSUE TITLE
Media not uploading

### ISSUE THREAD

**Issue by jldunnum** [ArctosDB/arctos#6165]
Media associated with this transaction Attach/Upload Media

Files don't upload when dropped into loading area

![image](https://user-images.githubusercontent.com/17278851/233179617-d0aa4c60-c554-4f4d-b07b-6d89744d82e8.png)

**Comment by AJLinn** [comment]
I'm getting the same issue. The image uploads, I get a checkmark, but then the Upload Media box just sits there with a solid grey line and no change.  We don't have a TACC allocation and this is our primary way of loading all images to individual records. 

> there's not much I can do about that thing timing out.

Are you saying you don't have anything to do with this part of the media upload process and there's no recourse for it not working? What's my next option? Get a TACC allocation?

**Comment by AJLinn** [comment]
Here's the file and the record it should be uploaded to. I hope you're able to diagnose! Thank you!

https://arctos.database.museum/guid/UAM:EH:UA2002-007-0018AB
![UA2002-007-0018AB](https://user-images.githubusercontent.com/17605945/234643530-e39504c9-050d-4392-84a6-a49834f7ae65.jpg)

**Comment by dustymc** [comment]
Thanks, there's something about that file (or ??) - I can re-create, I will get to this as soon as possible.

@jldunnum can you send me (attach here, whatever works) the file that failed for you?

**Comment by AJLinn** [comment]
>  there's something about that file

I'll take a new photo! Thanks!

**Comment by dustymc** [comment]
@AJLinn this is some perfect storm of crazy.

* The weird thing about that photo is that it's already used as media.
* However that happened, it also broke the cache, which means you can't see it in the UI. (One out of 978823 ain't TOO bad, eh?!)
* That handler for that particular error had a bug (relating all the way back to Adobe not really understanding JSON).

I've squished the bugs and given the cache-thing some suspenders to wear over its belt, some stuff should be fixing itself now and the rest will be next release (tonight).

@jldunnum I'd guess you found at least one of those, but it's definitely not quite the same situation. Try again ~tomorrow.

**Comment by AJLinn** [comment]
> this is some perfect storm of crazy.

My purpose in life is to find the crazy so we can fix it! 🤪

>  I've squished the bugs and given the cache-thing some suspenders to wear over its belt, some stuff should be fixing itself now and the rest will be next release (tonight).

Thanks for your excellent sleuthing/bug-wrangling.
