### ISSUE TITLE
parts or Identifiers not visible

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6166]
This has also happened to @campmlc 

Sometimes, when I open an Arctos catalog record it appears to have no parts:

![image](https://user-images.githubusercontent.com/5725767/233198788-304234d6-a1b8-4684-bf0f-143cc4e1e22a.png)

BUT if I then refresh the page or switch between the "views", the parts suddenly appear:

![image](https://user-images.githubusercontent.com/5725767/233198926-e042eb0e-051c-4c1e-bb0e-d6fb73ad2493.png)

Maybe not a big deal for me, when I am willing to poke around, but a novice user or any non_Arctosian would probably just go on believeing this record had no parts. I'm calling this broken because I think most people would not go to the extra effort to search for parts that are there, but not visible.

**Comment by ewommack** [comment]
I just had this happen to me!
I was opening up different mammals form Accession 373, and one out of about eight showed up with the parts hidden. I made sure they were there by clicking the edit button, but otherwise didn't have time to poke about. It was a little startling though, since we were inventorying parts using Arctos.

**Comment by dustymc** [comment]
Symptom of https://github.com/ArctosDB/internal/issues/187

**Comment by campmlc** [comment]
Perhaps we can get rid of the view option dropdown so that at least the
default is that we can see the identifiers and parts - will losing the
customize options help?

**Comment by ewommack** [comment]
I think @dustymc just hinted that this is a symptom of things beyond our control at TACC?

**Comment by campmlc** [comment]
Yes, but the other tables don't disappear?

**Comment by campmlc** [comment]
Checking back in on this. If having random parts of our user interface disappear from view on an unpredictable basis is a symptom of things beyond our control, we need to have a discussion with TACC.  @mkoo

**Comment by ewommack** [comment]
Has something disappeared for you this week @campmlc? I haven't seen anything.

**Comment by campmlc** [comment]
It is a sporadic occurrence, unfortunately.

**Comment by campmlc** [comment]
Yes, frequently when I open a catalog record the parts and identifiers tables are not expanded, and so not visible. If you click the dropdown next to the table name, you can select a view option that brings them back. I don't understand why we have that view option at the record level - or at least, the option to totally hide everything should go away, and we should have a basic view and expanded view option, but not hide everything.

**Comment by dustymc** [comment]
Added a loading graphic.
