### ISSUE TITLE
Need Help with Arctos Error - Arctos Reporter

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#6168]
I'm trying to create a csv export report. The new report is NMMNH:PALEO label data and I copied the CFM from NMMNH_paleo_species_standard_tag (which needs some tedious minor format fiddling that I don't know how to do). I get an error trying to use either of these two reports.

# Error Text
<html>
<body>

ERROR_ID | 8C272171-4478-4BC9-98F98E538A773606
ERROR_TYPE | SQL
ERROR_MESSAGE | FATAL: password authentication failed for user "nicoleridgwell"
ERROR_DETAIL |  
ERROR_SQL

<br class="Apple-interchange-newline">
</body>
</html>

# Where it happened
Arctos Reporter

# Steps to get there
Log in. Run search, (in this case collection: NMMNH:Paleo, Catalog Number 81588-81664). From tools, select Arctos Reporter. Click open next to NMMNH:PALEO label data (or NMMNH_paleo_species_standard_tag). Get error.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Note: this doesn't happen if I try to use someone else's report, so I assume it is a problem with these particular reports.

**Comment by dustymc** [comment]
You are using an old authentication method. Replace

```
<cfquery name="d" datasource="user_login" username="#session.dbuser#" password="#decrypt(session.epw,session.sessionKey)#">
```

with

```
<cfquery name="d" datasource="user_login" username="#session.dbuser#" password="#decrypt(session.epw,session.sessionKey,'AES/CBC/PKCS5Padding','hex')#">
```

I grabbed that from...

<img width="591" alt="Screenshot 2023-04-19 at 3 06 45 PM" src="https://user-images.githubusercontent.com/5720791/233210363-9baa37d8-0fc8-4189-817f-35756415465c.png">

... one of the protected templates, which should have various good stuff available.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Fixed that error, now I get:

<html>
<body>




ERROR_ID | 7D360322-4F29-4F15-97F8250EAD028430
ERROR_TYPE | expression
ERROR_MESSAGE | The key [DATADUMP] does not exist.
ERROR_DETAIL

<br class="Apple-interchange-newline">
</body>
</html>

I can see where the CFM says datadump, and I tried to compare to the csv export template, but I don't really know what I'm looking at.

**Comment by dustymc** [comment]
I snipped

```
<cfif datadump is true>
	<cfdump var=#d#>
</cfif>
```

for you, you can replace it with ``debug`` (see right column) if necessary.

(And please let me know if you just want me to make the thing work - I think it does now - I'm never quite sure if folks want to know how to make the thing work or just want to get some data.)

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
NMMNH_paleo_species_standard_tag now works, thank you. I copied your fix over to NMMNH:PALEO label data, and it will at least run now, but it won't give me CSV. I tried to substitute a bit of code from the end of the csv export template, but that didn't work, so I set it back the way it was and at this point I think I just want it to work rather than know how it works.

**Comment by dustymc** [comment]
"As I found it" CSV: [NMMNH PALEO label data .csv.zip](https://github.com/ArctosDB/arctos/files/11288254/NMMNH.PALEO.label.data.csv.zip)

It should be silently spitting out CSV now - let me know if I've misunderstood something, or if I can help in any way.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I don't know what happened, it wasn't working and now it is :shrug:
