### ISSUE TITLE
Error managing parts

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6169]
Attempting to manage parts in bulk from these search results - https://arctos.database.museum/search.cfm?guid_prefix=UWBM%3AMamm&customoidoper=LIST&partname=%3Dliver

1. Select Modify parts

2. Convert all liver parts to tissue and insert part remark = "l"

> ![image](https://user-images.githubusercontent.com/5725767/233428015-55b1f5e1-d9be-4ece-b620-830264d9c038.png)

3. Get the list of changes

> ![image](https://user-images.githubusercontent.com/5725767/233427743-94a2225a-4d62-446e-b215-4a0b5e05943d.png)

5. Say they are good, get error

<html><body>

ERROR_ID | 3F90D122-0537-4CAE-A583242C116821FB
-- | --
ERROR_TYPE | SQL
ERROR_MESSAGE | ERROR: current transaction is aborted, commands ignored until end of transaction block
ERROR_DETAIL |  
ERROR_SQL | update coll_object_remark set                                  coll_object_remarks='l' where                                  collection_object_id=27548518

</body>
</html>

**Comment by Jegelewicz** [comment]
just did the same exact thing for https://arctos.database.museum/search.cfm?guid_prefix=UWBM%3AMamm&customoidoper=LIST&partname=%3Dmuscle and it worked fine.

**Comment by dustymc** [comment]
That should be a temporary state.

**Comment by Jegelewicz** [comment]
How long is temporary? Just tried again:

<html><body>


ERROR_ID | 87BA58D6-E74B-4D3E-93BD97D22D761FE4
-- | --
ERROR_TYPE | SQL
ERROR_MESSAGE | ERROR: current transaction is aborted, commands ignored until end of transaction block
ERROR_DETAIL |  
ERROR_SQL | update coll_object_remark set                                  coll_object_remarks='l' where                                  collection_object_id=27548518


</body>
</html>

**Comment by dustymc** [comment]
>How long is temporary?

60 seconds, but I think I wasn't being clear. This is just a flavor of timeout, if the stars align just right it might work, if they don't it might time out the next million tries. (And more generally, I think we've simply outgrown all of the "live" mass-update tools under the current allocation of resources.)

**Comment by dustymc** [comment]
>sharable url is not correct -

issue please. The customid bits aren't the problem, but seeing 60K instead of 32 sounds like one.

>something is weird

Maybe, 30 records should USUALLY work, I'd think. I'll try to break test.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I've just run into the same issue, but different error message:

This search: https://arctos.database.museum/saved/Aetosaur%20scutes

With this part update:

![image](https://github.com/ArctosDB/arctos/assets/47402809/9a1d4fc3-b3a2-4ad9-8c21-0b8f14369c51)

After approving the list of changes I get this error message:

<html>
<body>


ERROR_ID | D6FA3161-BA74-4834-A98BA7AE286ED328
-- | --
ERROR_TYPE | SQL
ERROR_MESSAGE | ERROR: new row for relation "coll_object_remark" violates check constraint "ck_coll_object_remarks_noprint" Detail: Failing row contains (29113930, null, original part name , null).
ERROR_DETAIL |  
ERROR_SQL | insert into coll_object_remark ( collection_object_id, coll_object_remarks ) values ( 29113930, 'original part name ')


</body>
</html>

My new remark does not have any non printing characers.

**Comment by dustymc** [comment]
No, the existing data are just a mess. I grabbed a copy Just In Case and updated, should work now.

```
create table temp_cache.coll_object_remark20230608 as select * from coll_object_remark;

alter table coll_object_remark drop constraint ck_coll_object_remarks_noprint;
alter table coll_object_remark drop constraint ck_disposition_remarks_noprint;
alter table coll_object_remark drop constraint ck_associated_species_noprint;

arctosprod@arctos>> update coll_object_remark set coll_object_remarks=replaceFreeText(coll_object_remarks) where checkfreetext(coll_object_remarks) is false;
UPDATE 91021
Time: 449217.722 ms (07:29.218)
arctosprod@arctos>> update coll_object_remark set disposition_remarks=replaceFreeText(disposition_remarks) where checkfreetext(disposition_remarks) is false;
UPDATE 68
Time: 2371.084 ms (00:02.371)
arctosprod@arctos>> update coll_object_remark set associated_species=replaceFreeText(associated_species) where checkfreetext(associated_species) is false;
UPDATE 20438


alter table coll_object_remark add constraint ck_coll_object_remarks_noprint check ( checkfreetext(coll_object_remarks) );
alter table coll_object_remark add constraint ck_disposition_remarks_noprint check ( checkfreetext(disposition_remarks) );
alter table coll_object_remark add constraint ck_associated_species_noprint check ( checkfreetext(associated_species) );
```

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Still wouldn't run with the quotes. Teresa's suggestion of removing the quotes worked, but why would it be reading a quotation mark as non-printing?


Nicole Volden

Geoscience Collections Manager

New Mexico Museum of Natural History and Science

1801 Mountain Road NW

Albuquerque, NM 87104-1375

505-841-2843

***@***.******@***.***>

www.nmnaturalhistory.org

________________________________
From: dustymc ***@***.***>
Sent: Thursday, June 8, 2023 8:21 AM
To: ArctosDB/arctos ***@***.***>
Cc: Volden, Nicole, DCA ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ArctosDB/arctos] Error managing parts (Issue #6169)

CAUTION: This email originated outside of our organization. Exercise caution prior to clicking on links or opening attachments.

No, the existing data are just a mess. I grabbed a copy Just In Case and updated, should work now.

create table temp_cache.coll_object_remark20230608 as select * from coll_object_remark;

alter table coll_object_remark drop constraint ck_coll_object_remarks_noprint;
alter table coll_object_remark drop constraint ck_disposition_remarks_noprint;
alter table coll_object_remark drop constraint ck_associated_species_noprint;

***@***.***>> update coll_object_remark set coll_object_remarks=replaceFreeText(coll_object_remarks) where checkfreetext(coll_object_remarks) is false;
UPDATE 91021
Time: 449217.722 ms (07:29.218)
***@***.***>> update coll_object_remark set disposition_remarks=replaceFreeText(disposition_remarks) where checkfreetext(disposition_remarks) is false;
UPDATE 68
Time: 2371.084 ms (00:02.371)
***@***.***>> update coll_object_remark set associated_species=replaceFreeText(associated_species) where checkfreetext(associated_species) is false;
UPDATE 20438


alter table coll_object_remark add constraint ck_coll_object_remarks_noprint check ( checkfreetext(coll_object_remarks) );
alter table coll_object_remark add constraint ck_disposition_remarks_noprint check ( checkfreetext(disposition_remarks) );
alter table coll_object_remark add constraint ck_associated_species_noprint check ( checkfreetext(associated_species) );

**Comment by dustymc** [comment]
>why would it be reading a quotation mark as non-printing?

It's not - if you're seeing that error, there's an extra whitespace or something you can't see (hence "nonprinting") in there somewhere.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I checked multiple times on the whitespace - (beginning, middle, end, typing it in instead of copy/paste), there wasn't any. When I finally got it to work, I had copy/pasted what I entered before and the only change I made was to delete the quotes.

**Comment by dustymc** [comment]
Data?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I had no problem replicating this:

Copied exactly from what I entered.
`original part name "scute"`

![image](https://github.com/ArctosDB/arctos/assets/47402809/fed60eb7-1600-4483-8759-4aab752b41e7)

<html>
<body>


ERROR_ID | 543D354F-646D-49E9-BC2C063F78BA3DFC
-- | --
ERROR_TYPE | SQL
ERROR_MESSAGE | ERROR: new row for relation "coll_object_remark" violates check constraint "ck_coll_object_remarks_noprint" Detail: Failing row contains (29113926, null, original part name , null).
ERROR_DETAIL |  
ERROR_SQL | insert into coll_object_remark ( collection_object_id, coll_object_remarks ) values ( 29113926, 'original part name ')


</body>
</html>

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Here is the search result link for the specimen I tested this out on if you want to try to replicate: https://arctos.database.museum/search.cfm?guid_prefix=NMMNH%3APaleo&cat_num=11001

**Comment by dustymc** [comment]
Oh derp. You're getting the error because of whitespace - which broken handling of the quotes is inserting...
