### ISSUE TITLE
Shared UAM /MSB locality edits

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6180]
@amgunderson @DerekSikes 
We are working at MSB with parasites of UAM hosts, including shared UAM:Ento records - these all share the same localities/collecting events.
As we come across some cleanup issues, I'd like to post them in this issue so we can collaboratively address. 
The following posts will be for shared specific localities that need looking at/cleanup. Please comment.

**Comment by campmlc** [comment]
Locality ID: 15512
Specific Locality:
[Kandik[X]Cabin, Charley River Quad, Yukon-Charley Rivers National Preserve](https://arctos.database.museum/place.cfm?action=detail&locality_id=15512)

Verbatim Locality:
[Kandik Cabin](https://arctos.database.museum/place.cfm?action=detail&collecting_event_id=28754)

Can I fix the [X]?

**Comment by DerekSikes** [comment]
Please do all the locality editing you feel appropriate. These localities were made by UAM:Mammals. However, in Entomology it is customary to order locality place names from largest to smallest region, so I prefer:

Yukon-Charley Rivers National Preserve, Charley River Quad, Kandik Cabin

Also, at UAM:Ento we don't use topo quads in our speclocs. So I'd really prefer:

Yukon-Charley Rivers National Preserve, Kandik Cabin

but feel free to do as you would normally. The stipulations above matter most for specimens we need to print labels for (so the data are as ready for labels as possible, and these specimens are not in our queue for label printing (yet)).

**Comment by dustymc** [comment]
[Specific Locality should start with the most specific part of the locality and end with the most general.](https://handbook.arctosdb.org/documentation/locality.html)

**Comment by DerekSikes** [comment]
[Specific Locality should start with the most specific part of the locality and end with the most general.](https://handbook.arctosdb.org/documentation/locality.html)

I and all entomologists disagree - for the reason stated. That's how people address mail! It's not how we label specimens. The labels should be like:

USA: Alaska: Fairbanks: 930 Fitz Ct

And there are VERY good reasons for this which you would know if you had to search thousands of tiny labels by eyeball in a collection looking for certain (larger) localities.

**Comment by campmlc** [comment]
I'm happy to edit however - or happy for you all to do so. But we should make sure that if we have html for printing labels in Arctos, that we aren't duplicating the higher geography in the specific locality, causing it to show up twice in the label?

My guess is none of the ones I edit will be used by UAM:Ento for labels, as they are all physically present and cataloged here at MSB:Para. We do need to make sure all appropriate reciprocal relationships are captured to document this. Our records should have the "parasite of: UAM:Mamm:xxxxx " relationship - which I assume @amgunderson needs to approve for the reciprocal? I'm not sure how that works anymore with the change to PostGreSQL. Does he get a reciprocal relationship notification to approve? Are they all sitting in his component loaders?
Also, we will need to create "same individual as" relationships to UAM:Ento once we have our complete list ready. Ditto on how to make those reciprocal links.

**Comment by campmlc** [comment]
I think if the higher geog is not duplicated, it makes sense to go from general to specific. 
E.g. "Sevilleta National Wildlife Refuge, Five Points Grassland, Web 2"
This is how we record these mark/recapture localities, which differ only by the web number.

**Comment by dustymc** [comment]
>entomologists disagree

On the format of the standardized field that was developed to support things like georeferencing projects?! I'm not trying to convert you, they're your data and you can do with them what you will, but I suspect there's a bit of a misunderstanding somewhere in that.

``USA: Alaska: Fairbanks: 930 Fitz Ct`` would make a great verbatim locality.


> not sure how that works 

There's a monthly notification, or search for agent type bot if you don't want to review.

**Comment by Jegelewicz** [comment]
> [Specific Locality should start with the most specific part of the locality and end with the most general.](https://handbook.arctosdb.org/documentation/locality.html)

Does not make sense. I don't know how it became a thing and I agree with @DerekSikes and I organized most of my specific localities that way when I was doing data entry. That is the way most people write things down and is consistent with the order of higher geography.

**Comment by mkoo** [comment]
Seems like UAM and MSB have connected on locality editing! Stale issue alert so I'm closing; feel free to file a new issue if needed!
