### ISSUE TITLE
iframe url does not have permission to interact with me

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#6181]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
On Mac Chrome in Locality page I am getting a popup window. See attached. At first it takes like 5 hits to make it go away. Then subsequently it only goes away for 3 seconds. It is impossible to work on that window if I have only 3 seconds! 
Carla says she's been living with this for months. 

**To Reproduce**
Mac Chrome. Going to any locality edit page. Popup is coming up. 

**Expected behavior**
A clear and concise description of what you expected to happen. - NO POPUP!

**Screenshots**
Attached.

**Desktop (please complete the following information):**
 -Mac
 - Chrome

**Additional context**
It just started for me yesterday, but I recall seeing it in the past. What changed? Do I need to do something to fix it?

**Priority**
High. I have to use a different browser. Inconvenient. 
<img width="630" alt="Screenshot 2023-04-21 at 12 27 25 PM" src="https://user-images.githubusercontent.com/5749672/233744790-65c30cb2-cb47-45b8-8a15-d471162968f2.png">

**Comment by cjconroy** [comment]
It is also doing this on the data entry form.

**Comment by mkoo** [comment]
I just started typing out this issue myself based on our emails!

Anyway here's more details: this can be fix somewhat with a browser extension but also see this:
https://davidwalsh.name/iframe-permission-denied
basically tweaking the header setting to  "``` x-frame-options``` to ```SAMEORIGIN```"

Users can also address (what I did a while ago) with a CORS extension on FF or Chrome (eg https://addons.mozilla.org/en-US/firefox/addon/access-control-allow-origin/ or https://addons.mozilla.org/en-US/firefox/addon/cors-everywhere/) 

And yes it'll show up on all the rich editing pages

**Comment by cjconroy** [comment]
why did it just start up for me? Did my chrome update?  This kind of stuff really impacts work productivity.

**Comment by dustymc** [comment]
That is some browser extension (or virus, or network, or something) trying to do horrid things to geolocate. @ccicero had this a while back, I think hers was some extension - which might not be the same for you, but that's the place to start looking. 

@mkoo I think this is happening BEFORE any iframe is requested, if not I'll probably need whatever's in the console.

**Comment by ccicero** [comment]
I was also having the issue again but will need to see if it's still happening in my browser.

**Comment by mkoo** [comment]
is this still happening? We've had a lot improvements to framework of UI and I personally have not seen this error since. I am going to close for now. It can be reopened or reissued but this is has not been reproducible since it's likely a highly localized set of conditions.
