### ISSUE TITLE
Feature Request - bulkloader builder

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6183]
**Is your feature request related to a problem? Please describe.**

There was a request for the bulkloader builder to be revised and released with whatever https://github.com/ArctosDB/arctos/issues/6171 or https://github.com/ArctosDB/arctos/issues/5331 might become during last CT meeting.

**Describe what you're trying to accomplish** 

Provide a place to get a partial/customized bulkloader template

**Describe the solution you'd like**

I need to know what's necessary in order to build tools (and that may be unknowable until the structure is settled??)

@ccicero 

**Describe alternatives you've considered**

?

**Additional context**

See above

**Priority**

?

**Comment by Jegelewicz** [comment]
When we were looking at the column headers we grouped them as follows:

General
Identifier
Identification
> Identification Attribute
Agent
Locality
> Locality Attribute
coordinate
Event
> Event Attribute
Record Event
Attribute
Part
> Part Attribute

I think that to start providing this list and allowing one to choose the number of each makes sense. Some will automatically be "1" as some information from the section is required to bulkload. That being said - it would also be interesting to have an option for "minimum data required".

**Comment by dustymc** [comment]
>minimum data required

That would vary by collection settings, but 

*accn
*guid_prefix
*enteredby 

should be close if the structure ends up anything like the latest proposal. I think all the proposals add up to very few data constraints, which I'm assuming is clearly understood by the folks who have approval powers.....
