### ISSUE TITLE
Code Table Request - Duplicate values for Pierre Shale in code table

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#6185]
## Initial Request

_**Goal**: I noticed today that there are duplicate values for the Pierre Shale. This issue is to remove duplicate values.

_**Proposed Value**: Keep Pierre Shale Formation, remove Pierre Shale

_**Proposed Definition**: A Late Cretaceous marine unit that outcrops in the western United States and was deposited by the Western Interior Seaway. [Geolex](https://ngmdb.usgs.gov/Geolex/Units/Pierre_9624.html)

_**Context**: All attributes using "Pierre Shale" will need to be migrated to "Pierre Shale Formation"

_**Table**: https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlithostratigraphic_formation

_**Discussion**: There are probably a number of paleo/geo collections using this value, it is a very commonly collected unit.

@ArctosDB/arctos-code-table-administrators 

## Approval

_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality)._

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [ ] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection

_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation

_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

_Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel._

_Make changes as described above. Ensure the URL of this Issue is included in the definition._

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I'm using special access to go ahead and update the definition.

**Comment by dustymc** [comment]
I'm invoking my superpowers of righting wrongs for this. Done.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks!
