### ISSUE TITLE
agent address update-by-duplicating trigger is broken

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6186]
**Describe the bug**

```
ERROR: column "valid_addr_fg" of relation "address" does not exist Where: PL/pgSQL function trigger_fct_tr_address_bu() line 66 at SQL statement
```

**To Reproduce**

Attempt to update a used address. There's a trigger which at one point would insert rather than updating. It's not working.

**Expected behavior**

See above, but I'm not sure that's what we *should* expect - I think Arctos has outgrown such blackbox magic, and we should just clearly prevent changing used addresses.

**Additional context**

**Priority**

Relatively high - this is in the error logs associated with a new collection, not a great welcome.

**Comment by Jegelewicz** [comment]
> clearly prevent changing used addresses.

Or require extra clicks to change a used address? let's face it, mistakes happen and providing people with a warning that they are changing a used address may be enough here?

**Comment by dustymc** [comment]
A loan has gone missing. Someone has made the extra clicks because reasons and now not only won't it be found, but neither will the cause. That still seems a bit suboptimal from here.

(And "extra clicks" is at best a temporary and localized thing.)
