### ISSUE TITLE
two summarize by methods give different results

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#6190]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

When I use this newer summarize by tool: https://arctos.database.museum/record_summary.cfm?guid_prefix=KNWR:Ento,KNWR:Inv,KWP:Ento,UAA:Ento,UAM:Ento,UAMObs:Ento&phylum=Arthropoda&species=_&taxa_formula==A&state_prov=Alaska&result_columns=phylum,phylclass,phylorder,suborder,superfamily,family,subfamily,tribe,subtribe,genus,species

I get a list of **9146 species** of Arthropods for Alaska

when I use the cat record search form to replicate this search 
https://arctos.database.museum/search.cfm?guid_prefix=KNWR%3AEnto%2CKNWR%3AInv%2CKWP%3AEnto%2CUAA%3AEnto%2CUAM%3AEnto%2CUAMObs%3AEnto&taxa_formula=A&phylum=Arthropoda&species=NOTNULL&state_prov=alaska

and use the older summarize results tool (by 'identified as')

I get a list of **9474 species** of Arthropods for Alaska. These counts should be same.

I checked the list of 9474 for any duplicate names and found none. What is going on (or what am I doing wrong)?

Context - I am trying to build a discovery curve of species for Alaska so need to limit searches by dates (so I can get total counts for each year) - this led me to use the cat record form because I saw no way to limit the former URL (newer summarize tool) by date entered.

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.
medium

**Comment by DerekSikes** [comment]
I just compared the two results and seems the catalog record search is failing to respect taxon ID formula = A

so that seems broken.

**Comment by dustymc** [comment]
There are three things going on here.

1. "by 'identified as'" - you're not counting the same things.
2. The summary tool is limited to flat, which is limited to one accepted ID at the moment. You're not including that in search and should add ID Score to do so
3. There is no way to limit search to flat and the summary tool is still confined, so 'alaska' doesn't mean the same thing.

In this case (3) doesn't seem to be a factor, and https://arctos.database.museum/search.cfm?guid_prefix=KNWR%3AEnto%2CKNWR%3AInv%2CKWP%3AEnto%2CUAA%3AEnto%2CUAM%3AEnto%2CUAMObs%3AEnto&customoidoper=BETWEEN&identification_score=1&taxa_formula=A&phylum=Arthropoda&species=NOTNULL&state_prov=alaska leads to....

<img width="418" alt="Screenshot 2023-04-25 at 2 08 31 PM" src="https://user-images.githubusercontent.com/5720791/234404366-30064c00-48e6-4d35-9db3-2cf53a3e8cbc.png">

... your expected count.

**Comment by DerekSikes** [comment]
Thanks! I've never had this issue of 'identified as' behaving differently than 'species' when limiting to ID formula=A
but I got this working and now have a nice updated discovery curve for AK arthropods!

**Comment by dustymc** [comment]
>never had this issue 

You probably did, you just didn't have a second view of the data from which to notice.

> 'identified as' behaving differently than 'species' 

subspecies (or potentially a mislabeled family or something, but I don't think so)

>discovery curve 

Sweet!

**Comment by dustymc** [comment]
done?
