### ISSUE TITLE
Need Help with Arctos Error: query string argument of EXECUTE is null

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6193]
# Error Text
query string argument of EXECUTE is null

# Where it happened
Status error message in bulkloader

# Steps to get there
Got for two records out of 475 records marked to load - I need to understand what to fix. I don't see anything obviously wrong or different about these two records.

# Problem
**Community response to describe the problem that caused the error**

# Solution
**Community response with directions for how to correct the problem**

**Comment by campmlc** [comment]
Records enteredby SomiyaDunnum

**Comment by Jegelewicz** [comment]
@campmlc I think it is because you have a preservation_2, but no part to pair it with?

**Comment by Jegelewicz** [comment]
Only a single preservation can be entered for a part in data entry. If you want to enter more than one, you have to use part extras and add the two attributes.

**Comment by dustymc** [comment]
I think it's probably the malformed attribute

<img width="364" alt="Screenshot 2023-04-26 at 10 32 25 AM" src="https://user-images.githubusercontent.com/5720791/234656608-9fe97917-ba44-4747-8414-3fce9770bcee.png">

but I'd started working on https://github.com/ArctosDB/arctos/issues/6103 under the original schedule and test is not in sync with prod so it's hard to be definitive.

**Comment by dustymc** [comment]
Confirmed it's the missing units, will get a fix out tonight.
