### ISSUE TITLE
Feature Request - georeference bot is in stasis

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6195]
**Is your feature request related to a problem? Please describe.**

The georeference bot is being restructured. I've set up a dedicated task, but for now the task just notifies me when a collection grants the bot access. 

The details need sorted out and implemented when there's an identified need.

**Describe what you're trying to accomplish** 

Make georeference bot available to collections, don't write code until there's a need.

**Describe the solution you'd like**

This is a placeholder pending a request.

**Describe alternatives you've considered**

There are none.

**Additional context**

This also needs - documentation?? IDK, something clearly isn't understood.

**Priority**

None pending a request.

**Comment by ewommack** [comment]
Maybe a link to how collections can grant access?

**Comment by dustymc** [comment]
https://handbook.arctosdb.org/documentation/bot.html

**Comment by ewommack** [comment]
Yeah! Thank you.
