### ISSUE TITLE
UI scheduled meeting

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6196]
Request to restart recurring meetings for UI issues and development.
Proposed time: Thursdays 2:30-3:30 MDT
https://www.when2meet.com/?19878138-HMOD3

**Comment by mkoo** [comment]
Lets get the proposed time Th at 130 PT/ 230 MT on the calendar-- I'll do this now and hope to see folks there tomorrow (it will be a packed Arctos day!)

**Comment by dustymc** [comment]
There should be at least one issue (regarding login) filed from this (and the notes are not in my recent docs??).

**Comment by ewommack** [comment]
> and the notes are not in my recent docs??

Do you mean the meeting notes?

**Comment by dustymc** [comment]
yes

**Comment by ewommack** [comment]
Here you go: https://docs.google.com/document/d/1lXFhBd4LH4802pOEGkj892ZUcJt19kh8Os1ky-qG570/edit?usp=sharing

In the shared drive now, under the UI Committee
