### ISSUE TITLE
Add Show All button to search page

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6201]
I wanted to create a really simple profile (#6199) and it took a lot of clicking just to get rid of the stuff I didn't want. I figured out the categories remove all, but I would have preferred a "remove all" so that I could have started from scratch creating my profile. Possible?

![image](https://user-images.githubusercontent.com/5725767/235169237-b1f9e27d-691a-44ba-aa0b-b147f6590f0c.png)

**Comment by dustymc** [comment]
I remain completely unconvinced that having eg kingdom and culture of origin on the same screen makes any sense for any user. There are a lot of things which are just never going to intersect in any user's area of interest, overwhelming them with a bunch of stuff that they're not going to bother understanding is not doing anyone any favors. (And there are a several recent of "I turned all this stuff on and now all this stuff that I've turned on is making a mess" Issues supporting this hypothesis.)

If you must, you can shift-click.

You can save everything as a profile.

I don't think you can save nothing as a profile, but one of each is possible and maybe pretty close.

**Comment by campmlc** [comment]
So we can't uncheck all? I agree with @Jegelewicz that this is necessary when you don't know what you've checked and need to start over.

**Comment by Jegelewicz** [comment]
Now I need direction because if we put everything in one issue you mark things as off topic and things get lost. I am trying very hard to create issues that address a single thing.

> shift-click.

Please provide me some direction on how this is supposed to work. When I do this on the splash page, it just highlights everything.

![image](https://user-images.githubusercontent.com/5725767/235269867-3f91afe2-281a-4e36-9ea1-9dd6c59e84be.png)

If it works, then I am fine with that - and honestly, maybe nobody else ever wants to "clear" the form. It seems like a reasonable request for any form, but I now have a profile with just two things selected, so I can use it to "clear" the form.

As part of our new development process, perhaps allowing a bit of discussion among users so you can see if more than one person cares or if another user has a solution would be useful?

**Comment by dustymc** [comment]
>thought you rejected her suggestion.

I try really hard to never do that unless there's some technically-compelling reason. I'm hearing conflicting things and trying to balance them - "there's too much clutter," "it doesn't fit on my screen," and "let's add stuff" - and in this case the extra stuff would go to a state that I think is not useful for any user. (But, that state can be a shortcut to lots of things that are useful - this still isn't a rejection, just an attempt to understand.)

>direction

Me too. I guess I need both, the big picture and the components. The components sometimes carry enough (necessary) detail to make the big picture completely overwhelming, and the components by themselves often (usually, perhaps) add up to be incompatible with the big picture and need some adjustment, which of course feeds off it itself and can lead to other pieces needing similar adjustments. I don't think I've ever claimed to have perfected that process, I'm very open to better ideas on how to guide development.

>direction

Check (or uncheck) a box

<img width="315" alt="Screenshot 2023-05-01 at 8 58 53 AM" src="https://user-images.githubusercontent.com/5720791/235483162-9ae34607-3283-4717-8e5e-572b53dbe467.png">

Scroll a bit, hold shift while checking (or unchecking) another box, everything in between the two will be checked (or unchcecked).

<img width="388" alt="Screenshot 2023-05-01 at 8 59 08 AM" src="https://user-images.githubusercontent.com/5720791/235483253-f0a68b5a-c999-4092-ad99-1ee940aed839.png">

> allowing a bit of discussion

I've never intended to discourage that, tell me what you want me to do and I'll try it.

**Comment by Jegelewicz** [comment]
After discussion with several people including @ebraker I think that everyone would really like a button on the search page that will just "show all".

**Comment by ebraker** [comment]
`I think that everyone would really like a button on the search page that will just "show all"`

Emphatically agree. I felt I was changing my customizations daily because I can't anticipate every type of search I need so I resorted to a 'show all' profile. I don't mind that it has chronostratigraphic attributes that I will never use - it is far more simple than having to tweak and untweak every other search.

Most importantly, a show all option is so much more welcoming and accessible for non-operators using Arctos. People understand that they can ignore fields they don't need. People will first encounter the simplified default form and also understand that they are opting in to seeing all the fields when they choose 'show all,' so I think that visual clutter is a nonissue. This is much more approachable than an outside user trying to explore and navigate the intimidating customize table at their first Arctos rodeo.

We'd need to figure out how this works with results given the costs. Would it be possible to somehow set results to 'default + any field that contains search terms' so that people would get a meaningful query return and avoid brushing up against record limits?

**Comment by dustymc** [comment]
>how this works with results given the costs

That's one reason I'm still suggesting that someone make an (or a few, or whatever - I've got lots of room to play with at the moment!) "everything" profile (which probably won't quite be everything for lots of reasons). 

The other is that there's a mechanism to do WHATEVER it is that needs done NOW, and I'd rather not add more complexity (front and back end) unless we **_really_** have to (and we haven't explored this path at all, so I don't think we're there yet).

I'm hoping to have a release this evening, if someone wants to send me a profile name to set as a preset in the next hour or so.

>+ any field that contains search terms

Not at the moment.

1. That would be some sort of new development, and
2. We'd have to remove a bunch of things to maintain a 1:1 ratio. (Which I think probably isn't realistic, Arctos is not a big spreadsheet, there are lots of things that make sense on one side or the other but not both.)

**Comment by ebraker** [comment]
@dustymc I'd like to highlight this issue again. I find myself wishing for this multiple times a week if not every day. I cannot search other institution's records when I am logged in, and thus I am unable to get at the search fields I need (I can only customize when logged in, but once logged in, the VPD kicks in and I am unable to search non-UCM collections). 

I have a profile titled "show all" that has every field toggled that I am able to access. Can we start with that to create some sort of "search all fields" preset?

**Comment by dustymc** [comment]
>profile

Perfect - this it?

https://arctos.database.museum/search.cfm?sp=show%20all

First problem, name - that's not really "all" (no ID attributes, at least), suggestions??

Second problems, that's going to throttle everything to 3 records (5 for "us" - maybe pending some sort of feedback on https://github.com/ArctosDB/arctos/issues/6922) - I don't think most users will find that very useful (even if someone really wants meteorite and parasite attributes at the same time....), and I'm not sure what the impacts of making something that expensive a suggested default might be (crashy-time?!).

>start with that

I haven't considered the possibility of making changes once something's in the list - I suppose it wouldn't be TOO disruptive, but I'd prefer to solidify as much as possible before moving anything to the production/public shortcut list.

**Comment by ebraker** [comment]
> throttle everything to 3 records 

hmmm, yes I see that now that I am trying a search. Does reducing the number of query-able Record Attributes, Event Attributes, Locality Attributes to two (from four) get us anywhere? I can attempt to trim further to a bio-geo diversity "search all" and leave room for a cultural "search all" preset.

**Comment by dustymc** [comment]
>query-able

Nope, query-stuff has no (measured) cost, only results with a cost > 1 really matter. (Err, I mean, sorting through thousands of fields is a "cost" but not one that limits results in Arctos....)

> bio-geo ... cultural 

I would advocate building for some tangible audience.

**Comment by ebraker** [comment]
Ok, I made a profile "advanced search (bio-geo)". It only knocks off a few fields. If we went even more targeted to extant biodiversity collections, we'd only loose Age and Chronostratigraphy so I think it makes sense to keep them co-mingled for now at least.

**Comment by Jegelewicz** [comment]
There's a difference between show all search fields and show all results. I only want the first one.

**Comment by dustymc** [comment]
>Age and Chronostratigraphy

Sure, those seem relevant.

I question the usefulness of eg phylum (all taxon rank things) those WILL NOT mean what a lot of users are expecting, the 'Taxonomy' table-thingee contains all the functionality without the whole 'guessing how some collection sees some taxon' problem.

Same thing to a lesser extent for geography.

there's still some admin stuff (enteredby) - intentional?

https://arctos.database.museum/search.cfm?sp=advanced%20search%20(bio-geo) - still crazy expensive though.

<img width="569" alt="Screenshot 2024-01-24 at 13 44 43" src="https://github.com/ArctosDB/arctos/assets/5720791/b2d06273-a665-494e-90f5-1a89df22f328">

> difference between show all search fields and show all results

A profile is the only realistic tool for this job, and those are inseparable components of a profile.

**Comment by ebraker** [comment]
> there's still some admin stuff (enteredby) - intentional?

Ok, I further trimmed "advanced search (bio-geo)".since we don't need curatorial fields (containers, entered by, etc) since one won't be able to view this info anyway for other collections/logged out:

Does that help?

**Comment by ebraker** [comment]
@dustymc I'm hoping we can have something in place before I demo Arctos to my institution in a couple of weeks. I'd like to easily navigate to non-vertebrate records so folks can see examples from their own discipline, but my search options are limited while not logged in.

**Comment by dustymc** [comment]
I don't know how to proceed. I can't make a default profile that will melt Arctos, and won't make one that'll result in angry users. This still does both. I think there's some confusion about https://github.com/ArctosDB/arctos/issues/6201#issuecomment-1908970666 but I don't know what - the way I interpret, that's just wrong (see my next comment) but could be I'm lost. See my screenshot in the same comment - all of those >1 cost results columns need turned off before I make anything permanent and default.

I'm still of the opinion that making "all the boxes" permanent and default isn't doing anyone any favors, but that's like, just my opinion, man.

>but my search options are limited while not logged in.

And that makes me think I've been lost for a while! NOTHING about default profiles has ANY relationship to operator status. Do this:


<img width="859" alt="Screenshot 2024-01-29 at 08 13 11" src="https://github.com/ArctosDB/arctos/assets/5720791/1f868fc1-0604-41a3-a206-b7ee04c73057"> 

then this



<img width="165" alt="Screenshot 2024-01-29 at 08 13 20" src="https://github.com/ArctosDB/arctos/assets/5720791/4ff351e4-3db2-4630-ae80-e292a83a4f6d">


 then search and (if you're lucky and/or careful!) you'll end up with...



<img width="603" alt="Screenshot 2024-01-29 at 08 13 48" src="https://github.com/ArctosDB/arctos/assets/5720791/b08a3efa-5834-4c99-9cd6-1f6f7994675e">

Try the same thing as an Operator and you'll end up...

<img width="587" alt="Screenshot 2024-01-29 at 08 15 07" src="https://github.com/ArctosDB/arctos/assets/5720791/62748df7-f95d-43fb-b95d-ac942600fa6e">

with a couple more records, that's it.

From https://arctos.database.museum/search.cfm?sp=advanced%20search%20(bio-geo) anyone with an account, operator or not, can...

<img width="348" alt="Screenshot 2024-01-29 at 08 15 51" src="https://github.com/ArctosDB/arctos/assets/5720791/07067cdc-6bb1-483f-ad13-5915aba4c722">

then...

<img width="399" alt="Screenshot 2024-01-29 at 08 16 05" src="https://github.com/ArctosDB/arctos/assets/5720791/d3d8d76a-69a2-470b-8a48-8f1b89feb07d">

and now

https://arctos.database.museum/search.cfm?cat_num=12&sp=copy%20of%20other%20thing

will do EXACTLY what your proposed default does, for anyone.

Does that clarify anything? If not, let's talk.

(And we should probably talk about characters in default profiles, lots of things will mangle those encoded spaces.)

@mkoo can you clarify anything?

**Comment by ebraker** [comment]
Ok, try the Advanced Search (bio-geo) profile again - I just customized results. I understand that one can customize while not logged in, but that is easily 30-50 clicks to get what is essentially an advanced search.

Also, can we add "map" to the default search? And rename "default_eh" (is that ethnography?). It is not super clear.

**Comment by dustymc** [comment]
The old search is gone, I think you probably mean https://arctos.database.museum/search.cfm?sp=Advanced%20Search%20(bio-geo) ?? (And I'll need a HTML-friendly name before moving this to the default list.)

The expense is fine, it won't melt Arctos.

Year collected is MAYBE a little flaky as a default, whatever.

Catnumint is a bit more flaky, it won't exist for lots of collections. Still kinda meh/whatever from my perspective.

Not sure where we go from here, @Jegelewicz @mkoo HELP!!!

----------

Renaming or refactoring existing defaults definitely needs at least an issue - I suspect you're asking to break about a million external things, and some relatively complex internal that we've set up for @AJLinn as well. My first instinct is that defaults should be entirely immutable. Maybe that's overly conservative for the contents, I think it's probably unavoidable for the names.

**Comment by ebraker** [comment]
OK great!!! I removed the flaky values: 
https://arctos.database.museum/search.cfm?sp=advanced_bio-geo
 
How about 'advanced_bio-geo' for a name?

I wan't suggesting to break anything, just that something like 'default_ethno' might be more clear than 'default_eh' to outside users, but I have no skin in the game (@ajlinn can ignore).

**Comment by dustymc** [comment]
Settle for advanced_bio_geo? (Don't think the - is actually problematic but I like consistency if possible.)

Nobody's screaming, I'll push this through the dev channel for a bit more exposure and get it in next release (unless the screaming starts!).

**Comment by ebraker** [comment]
Yup,  I'm fine with advanced_bio_geo

> Nobody's screaming, I'll push this through the dev channel for a bit more exposure and get it in next release 

I'm screaming with joy for this update! Thank you.

**Comment by ebraker** [comment]
@dustymc 

I can view and click on the advanced_bio_geo preset but only the default fields display (note that the URL is correct - https://arctos.database.museum/search.cfm?sp=advanced_bio_geo):

![image](https://github.com/ArctosDB/arctos/assets/11336485/a2dfacf2-fd11-4dc5-87b4-8a69da2a78ca)

**Comment by dustymc** [comment]
>default fields display

Uh - neato!

I'm using an ilike to make the selection less-twitchy, and apparently _ and - are synonymized with that:

```
arctosprod@arctos>> select profile_name,cf_username from cf_cat_rec_srch_profile where profile_name ilike 'advanced_bio_geo';
   profile_name   | cf_username 
------------------+-------------
 advanced_bio-geo | ebraker
 advanced_bio_geo | arctos
```

So the immediate 'solution' is to delete your profile. Finding a real solution probably needs an Issue.

**Comment by ebraker** [comment]
Ok I deleted my profile.

**Comment by ebraker** [comment]
It works now, thanks!
