### ISSUE TITLE
Reduce horizontal scrolling in the search and results sections of the profile customizer

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6202]
Could we organize everything in the left column of the customize search and results window horizontally and move it above the search and results sections so that I don't have to try to scroll horizontally in the search and results sections while creating a profile?

From

![image](https://user-images.githubusercontent.com/5725767/235172737-0a8f2e27-d9ce-4879-aeb9-7158b464fd59.png)

To

![image](https://user-images.githubusercontent.com/5725767/235173074-eba9e48a-9240-4b26-832d-cec40d3d127c.png)

If I scroll down to get to the horizontal scroll, I can't see the column headers (again). Can we make this so that I don't have to scroll BOTH vertically AND horizontally?

![image](https://user-images.githubusercontent.com/5725767/235171794-a3dabb7f-f06f-4dcf-b464-41e9c4e9418c.png)

Or perhaps allow me to stretch the size of this splash page so that I could eliminate scrolling the splash page AND the various columns vertically?

I guess what I am saying is we aren't providing enough space to make this an easy process. A div at the top with all of the stuff that is currently in the left column would allow the other two columns to be wider and would at least eliminate the need for horizontal scrolling within them?

**Comment by dustymc** [comment]
See https://github.com/ArctosDB/arctos/issues/6200 - it fits on my screen, which I think is somewhere nearish average. Don't think this is actionable without a CSS wizard or radical idea or ??

**Comment by Jegelewicz** [comment]
I went away for half a day and now the splash page looks like this?

![image](https://user-images.githubusercontent.com/5725767/235270130-220ea45d-0eb9-4c2f-91f1-1c642d9d505f.png)

I can't even see a single column of the search or results customization forms!

**Comment by dustymc** [comment]
That's part of the development process - I always try to do all the crazy things that users will eventually get around to doing.

Default-cached things also change rapidly and I make no effort to do anything about that - you'll probably need to shift-reload.

There's some of your recent comments incorporated into the current version, it should be a lot more compact even with very verbose data.

<img width="1679" alt="Screenshot 2023-05-01 at 8 46 03 AM" src="https://user-images.githubusercontent.com/5720791/235480969-0721ef9f-ad61-4120-a0d3-773ee98af872.png">

**Comment by Jegelewicz** [comment]
Still unusable for me.

![image](https://user-images.githubusercontent.com/5725767/235537482-b803cd60-a9e5-4077-ac2c-607e565e04eb.png)

**Comment by dustymc** [comment]
Shift-reload, don't think you're seeing current CSS. If you are then I need details of your environment.

**Comment by Jegelewicz** [comment]
Shift-reload changes nothing

Firefox 112.0.2 (64 bit) on Windows Version 10.0.19044 Build 19044

but it looks the same in Chrome

![image](https://user-images.githubusercontent.com/5725767/235546826-dfeebb74-eb87-4ae6-94fc-8f4b9d7c8021.png)

**Comment by dustymc** [comment]
OMG I just noticed the URL, you're in production! (And I think we've got a script kiddie playing around, maybe I need to be less-liberal with the connection to username.)

Go check test, it should deal with that exact situation.

**Comment by Jegelewicz** [comment]
Search catalog records in test gets me this

![image](https://user-images.githubusercontent.com/5725767/235552240-acbadd59-7b2e-4ab6-a799-768a63ed1790.png)

So I can't go to profiles

**Comment by Jegelewicz** [comment]
> less-liberal with the connection to username.

You don;t have to have a username to create a profile - I think that is a problem.

**Comment by dustymc** [comment]
Log in - there was a pretty significant attack on test, it's locked down at least through next week.

**Comment by dustymc** [comment]
Yea, it's all happy, thanks. The downtime next week should get everything back to where it needs to be.

**Comment by dustymc** [comment]
@Jegelewicz happy?

**Comment by Jegelewicz** [comment]
Much better - I still have to scroll horizontally, but as everything is contained in the splashpage, I don't have two vertical scrolls (the ones in the search and results sections AND the whole slashpage) to deal with as well.
