### ISSUE TITLE
Rename `made_date` and `date_made_date` fields in `flat`

### ISSUE THREAD

**Issue by camwebb** [ArctosDB/arctos#6208]
It would be very helpful to rename the `made_date` and `date_made_date` fields in `flat` to something more informative (e.g., `identification_date` and `first_ident_date`), or at least to document them somewhere (e.g., [here](https://arctos.database.museum/tblbrowse.cfm?tbl=flat)).  I had erroneously been using `date_made_date` for the identification date in several projects. 

I know renaming might be hard for reasons of backward compatibility, but some documentation would be valuable. I added a note to the SQL [cheat sheet](https://docs.google.com/document/d/15e3b8WNErFPqg1SW-QNq0nI_RjiEEZjWQDznxIJNFHE/edit).

Thanks.

**Comment by dustymc** [comment]
See also https://github.com/ArctosDB/arctos/issues/6171 (can/should we be consistent?) and https://github.com/ArctosDB/arctos/issues/3540 (what is it that we flatten when there's not longer a single "The Important Identification"?).

>first_ident_date

If you mean chronologically, the 'more accepted' (what's being flattened at the moment) can be centuries after the first.

If you mean by preference, we are heading towards a model in which the 'best' IDs can span centuries.

**Comment by camwebb** [comment]
> `first_ident_date` ... If you mean chronologically, ... If you mean by preference...

I don't actually know what `date_made_date` is, other than _a_ date associated either with the current or with a prior identification. Searching on `date_made_date` in this repo or the handbook draws a blank. Is there the SQL code for making `flat` anywhere?

**Comment by dustymc** [comment]
Turns out I don't either! Looks to be some  unmaintained migration leftover.

>code

https://github.com/ArctosDB/PG_DDL/blob/master/function/flat_components/update_flat_row.sql

**Comment by camwebb** [comment]
Thanks - closing; attention now on new issue.
