### ISSUE TITLE
Legacy reporter down?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6209]
I can't access the legacy reporter. Possible to revive it, or is it completely dead?

**Comment by Jegelewicz** [comment]
> Good morning Teresa,
> 
> Quick question…I was trying to print labels for bird boxes/vials, and the link I usually use at the bottom of the Arctos Reporter is coming up invalid, saying Arctos refused to connect and load the page.  This is the only way I can access the appropriate label templates for our collections, so I was wondering if there was an ongoing issue and it is just temporarily down, or if it was a permanent issue and there was another way I could access those templates.
> 
> Thank you,

Makayla Easley
@makaylaeasley

**Comment by Jegelewicz** [comment]
> Makayla,
> 
> It appears that the legacy reporter is down - I have added you to the Github issue - https://github.com/ArctosDB/arctos/issues/6209
> 
> Please note that these reports will eventually be gone for good and you should request help with preparing reports under the new system - see https://github.com/ArctosDB/arctos/issues/new?assignees=lkvoong&labels=function-Reports&template=report-template-request.md&title=Arctos+Report+Template+Request
> 
> Adios,

Teresa J. Mayfield-Meyer

**Comment by campmlc** [comment]
#3006 Need help please.

**Comment by dustymc** [comment]
I managed to bring it back up. It was not happy about being resuscitated. Please prioritize migrating labels!

**Comment by Jegelewicz** [comment]
> Please prioritize migrating labels!

People have been doing this, but who is responsible? Clearly @campmlc has had an issue open for quite some time and there seems to be nobody who can help?

**Comment by cjconroy** [comment]
Can the legacy reporter get revived?  Link just says Nope

**Comment by dustymc** [comment]
> Link just says Nope

Then it's not dead, you're just not authenticating properly. Try closing all your tabs - I think that's at least part of what leads here.
