### ISSUE TITLE
search and results terms and definitions

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6210]
**Is your feature request related to a problem? Please describe.**

Some search and results terms are missing definitions, possibly could be made more clear, etc.

**Describe what you're trying to accomplish** 

Make Profiles slightly more awesome

**Describe the solution you'd like**

Help updating data, which is currently https://docs.google.com/spreadsheets/d/1-ejtSV0euJMUy5T5z2vr-71_tnQPhWNuQrcn8XvOttc/edit#gid=535800415

**Describe alternatives you've considered**

I'll do it

**Additional context**

I'll push this back to production ~ tomorrow. Help appreciated, or I'll make it work - let me know if you'd like edit access to the spreadsheet.

**Priority**

High - a UI I'm working on is weird when NULLs are involved and doing something is easy.

**Comment by Jegelewicz** [comment]
I'll help but I need access to the sheet and I won't be able to look at it until tomorrow morning.

**Comment by dustymc** [comment]
Thanks, you should have access.

**Comment by Jegelewicz** [comment]
I added a column in the search tab with suggestions and one with notes/questions. I'd like to leave "search" or "filter" out of these descriptions and make them more about the term as much as possible since this is about adding or removing fields from a customized search - those things should be self-evident. I may be completely off on any number of these - I don't use a lot of this stuff in daily searching and it might make sense for those that do to make the descriptions better?

**Comment by Jegelewicz** [comment]
Do all the individual attributes in results really only have a cost of 1?

**Comment by Jegelewicz** [comment]
I feel like the descriptions in search and results should be the same if the element is in both places. Again, I'd also like to leave the search/filter/results stuff out of the description as that is implied in the form already.

All of the attributes in results should just be using the description in the code table - probably without the Github (or other) links as they don't seem to translate?

**Comment by Jegelewicz** [comment]
> All of the attributes in results should just be using the description in the code table

Can that be automated so that changes in the code table get reflected here automatically?

**Comment by dustymc** [comment]
>added a column

I don't see much need for the complexity, just update (or do whatever works for you - add your column and remove the original is fine).

>this is about adding or removing fields from a customized search 

And knowing how the API works.

The "special" stuff is special because someone asked for it to be. (And that adds some complexity and maintenance, but not too much - seems reasonable, within limits, to me, at least until everyone figures out how to build their own UIs.)

I could figure out how to force GUID on everyone if I had to, but I'm sure someone would find that annoying and checking would add a cost - I don't see much need to force anything on anyone.

There are very many paths to projects, a few of them have search fields.

chronological_extent is days

anybarcode is - uhhh, any barcode??

https://github.com/ArctosDB/PG/blob/master/includes/specimenSearchQueryCode__param.cfm#L4640 will tell you what identifiers are covered, infinite things that someone might consider an identifier are excluded.

Anything cached has a cost of 1.

Things that share names in search and results aren't necessarily the same, but yea, docs should be shared when they are.

Yes ideally some of this would come from the code tables, but it's also transformed and merged and such here so IDK if a straight copy is enough. It's a few selected things for now, I'm not sure we need the complexity but ???

Yes embedding html in html gets wonky, not to mention the poor folks who use the API. I'd still like a policy of just bare links, still not a hill I'm willing to die on....

Lemme know what I missed!

**Comment by dustymc** [comment]
See also https://github.com/ArctosDB/arctos/issues/6111 before spending too much time on attributes.

**Comment by Jegelewicz** [comment]
RE attributes

> It's a few selected things for now

not in results - it's TONS of things!

**Comment by dustymc** [comment]
>display names agree with what is on the search page

There's no magic link. I've played with that a few times, it's not ENTIRELY magic, but it's definitely on the other side of a serious conversation about one massive "everything for everyone" UI. I'll just have to manually update the UI for now.

>not in results - it's TONS of things!

Ah - yes, https://github.com/ArctosDB/arctos/issues/6111 (and no small part of why I run screaming at any mention of 'everything'....)

**Comment by Jegelewicz** [comment]
I have to step away for a bit, but I think we should get more eyes on this if we possibly can....

**Comment by dustymc** [comment]
I'm going to push SOMETHING with definitions (even if they're 'pending...') to production ~tonight, but that doesn't have to stop this process. There is some time component (I'll have to change something and then won't want to deal with trying to reconcile that with some other thing and etc.), but I can re-pull/re-load this whenever. More eyes would be fabulous, happy to do whatever's necessary to make that happen.

**Comment by dustymc** [comment]
Thanks, pushed back to test - I'll grab a new copy of the spreadsheets for prod ~tonight.

**Comment by dustymc** [comment]
done
