### ISSUE TITLE
I can't log out?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6211]
Where do I log out?

<img width="960" alt="Screenshot 2023-05-01 18 07 25" src="https://user-images.githubusercontent.com/5725767/235552704-a361c7b5-b9c7-4e5f-b702-a2dd0ed5f980.png">

**Comment by dustymc** [comment]
I think I might know what happened (your session almost expired in another tab??). That came from https://github.com/ArctosDB/arctos/issues/5852 (its been out for a while now), and it's why I'm pretty paranoid about "minor" changes to complex systems - they often turn out not to be when mixed in with everything else.

I don't have a great solution. I can back out the attempt at saving a click, I can add a bunch more complexity (and expense) to try to compensate for what I think happened (but I'm guessing at what actually happened), ????

**Comment by Jegelewicz** [comment]
I'm guessing this was some sort of fluke - closing until it happens again...
