### ISSUE TITLE
Verbatim Date disappearing 

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#6213]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I'm adding information to the locality remarks field, but when I go into "Edit Event" to add something, the verbatim date disappears.

**To Reproduce**
1. Go to a catalog record (note that the verbatim date is recorded): https://arctos.database.museum/guid/CHAS:Ento:2018.6.226
![image](https://user-images.githubusercontent.com/93737929/235713157-d46f1760-dd89-4ab6-8412-37db869641c0.png)

2. Click on "Edit" next to "Place and Time"
3. Click on "Edit Event"
4. When the edit page opens, the verbatim date is gone:
![image](https://user-images.githubusercontent.com/93737929/235713420-9f11082a-8bdf-4f97-a7e4-2e977321960e.png)
5. When I add verbatim locality back to the field and save, it disappears again upon saving. It also allows me to save without any data in the field. With yellow fields, typically Arctos does not let you save if a yellow field is blank. I'm concerned about losing/having to lookup and reenter verbatim data.

**Expected behavior**
Verbatim date should not disappear.

**Desktop (please complete the following information):**
Firefox

**Additional context**
Is it because the field is highlighted in yellow? The verbatim locality, date, began date/time, end date/time are all required, but verbatim date is the only one that is highlighted.

**Priority**
Priority high for the potential to lose data.

**Comment by dustymc** [comment]
That's a bug - the "quotes" in the value aren't being escaped properly. 

(Does that indicate a particularly verbatimey verbatim?!)


```
arctosprod@arctos>> select verbatim_date from collecting_event where collecting_event_id=12544339;
 verbatim_date 
---------------
 "Aug 29, 199"
```

**Comment by wellerjes** [comment]
Ahhhh. We (staff, volunteers) put the quotes in Excel when transcribing data for the bulkloader. It prevents Excel from reformatting data after the spreadsheet is closed.
