### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6214]
I just logged in to production and was greeted with this

![image](https://user-images.githubusercontent.com/5725767/235739197-d6f87e91-b383-4c13-8152-7e44d647dcbc.png)

```
An error has occurred. Please include the ErrorID as text in any communications. 
ErrorID: ADDC8288-4F0D-483E-835770F09D0BD332
Mesasge: ERROR: permission denied for table api_pubusrallall_2023050210055252_960
Details: 
``

**Comment by Jegelewicz** [comment]
And it seems like I can't do any searching - a page refresh just brings up the same error.

**Comment by Jegelewicz** [comment]
Went away to the tools directory, returned to search and now it seems OK...

**Comment by Jegelewicz** [comment]
This seems problematic. I do some stuff as a public user, then I log in and I get errors? Shouldn't logging in clear the form automatically? Or at least I should get a more understandable error (please clear the form and try again) or something like that? I can't believe this has never happened to be before today! I do this all of the time....

**Comment by dustymc** [comment]
And maybe my recent push for simplicity in the name of sustainability now makes sense!

>Shouldn't logging in clear the form automatically? 

Sure, except when it shouldn't....

If The Community wants to lay out some sort of "when this then that..." thing then I would be thrilled to write code to it. I don't know how to write code to do whatever you might be asking at the moment, at least not without breaking a bunch of other stuff.

**Comment by mkoo** [comment]
This is likely a stale issue that is largely due to aggressive browser caching which I dont know if Arctos has an easy fix for.  No one else has filed an issue because this error stopped them from working. So closing for now. Reopen or file a new issue especially if reproducible
