### ISSUE TITLE
Login Issue- when signing in to Arctos

### ISSUE THREAD

**Issue by Msaqib2** [ArctosDB/arctos#6216]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html
@ewommack 
**Describe the bug**
When I click on to login on Arctos, it would sometimes be delayed to log me in and refresh the page. Other times it would keep trying to log me in (like my Reload Current Page button would show an X to suggest that the page is loading), however this goes on to happen for what seems like forever. I have to manually click on the X and try to Reload Current Page. Other times, I just close everything and reopen browser and login in like normal, upon which it works. I believe when my browser shows that it is reloading the current page after adding in credentials, Arctos isn't able to succesfully reload it for some reason.
You can also check this link out to see what is happening, in the video I am repeatedly clicking login to log me in the site, but it doesn't log me in, then I just refresh the page and it shows I am logged in but then the whole page seems funky https://drive.google.com/file/d/1Na_NqOxKXXqpet720p_6CYZqok1mmy8D/view?usp=sharing
I am a Graduate Student with University of Wyoming Museum of Vertebrates.

**To Reproduce**
1. Go to 'https://arctos.database.museum'
2. Click on 'Login or Create Account'
3. Scroll down to 'Login'

**Expected behavior**
I expected the page to refresh on its own after clicking sign in and then take me to search a catalog page, like it occasionally does for me

**Screenshots**
Please also check the link for a video recording of what it is doing.
<img width="1410" alt="Screenshot 2023-05-02 at 5 07 04 PM" src="https://user-images.githubusercontent.com/123424602/235804048-619d5d50-75fa-4daa-82b6-7f6ecaeba499.png">

**Data**
The Data is my Login: msaqib1

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Browser [Firefox]
 - Version [111.0.1]

**Additional context**
Sometimes it would log me in like normal, while other times it won't. First I thought the problem happened due to me not loging out after every session and letting it expire on its own, however I found that it happens regardless of whether I log out or not

**Priority**
Priority High (Needed for work)

**Comment by ewommack** [comment]
@dustymc - Moe is one of our UWYMV Graduate CAs. Something is going funny when he tries to log in to Arctos, where it either will not let him log in or it seems to break part of the page display when he gets logged in.

Any help much appreciate!

**Comment by dustymc** [comment]
I think this must be two things:

1. https://github.com/ArctosDB/internal/issues/187 - SOMETHING (that feels, but may not be, network-ish) is sometimes weird. TACC knows about it, hopefully the upcoming downtime will help.
2. The crazy blurry thing almost has to be in your browser - some plugin, it's just running out of resources, ????? Try clearing cookies and cache and disabling extensions, shutting other stuff down, rebooting, etc.

Please let me know if any of that changes anything, every little clue is useful.

@mkoo FYI

**Comment by mkoo** [comment]
having trouble replicating the specific issue but other times when  folks
here had a slow to respond login window, then simply clearing cache worked.
try that in your favorite browser before anything else. hopefully some of
the other UI changes will mitigate login problems too

otherwise more info always welcome-- let us know what happens for you

**Comment by Msaqib2** [comment]
Hi @dustymc @mkoo ,
I deleted the cache (1GB worth?!) and I am able to login as normal. I will keep you all updated if the issue occurs again,and what I was doing at the time etc.

Thank you for the help.
