### ISSUE TITLE
Feature Request - Attribute Download Enhancement

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6223]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

I was working on making the tools dropdown in search results more readable and I noticed that the attribute download could benefit from being more like the parts and identifiers view tables functionality. I also think this will be useful to the RANGES folks as they work on adding attributes.

**Describe what you're trying to accomplish** 
An clear and concise overview of the goals; why are you asking for this?

I have been making a lot of use of the identifier and part table view/download tools and they work great! I'd like to be able to do the same with catalog record attributes.

**Describe the solution you'd like**
How might we accomplish your goals?

Instead of "download Attributes, have a tool that works just like the part and identifier view tables that let's me filter the attributes and then download the ones I need.

**Describe alternatives you've considered**

Use the current download tool and filter them myself. This works, but is inconsistent with the other tools.

**Additional context**

Adding this functionality would make all of the View/download tolls work consistently which makes for a better user experience.

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by dustymc** [comment]
Definitely agree the tools should be made consistent, but I believe HOW could use some discussion

* Some table-thing can potentially melt Arctos, can definitely melt your browser, but there's a nifty table-thing
* A straight CSV download can deal with a LOT more data, is much less likely to melt anything, carries a lower maintenance cost, but there's no nifty table-thing

**Comment by Jegelewicz** [comment]
I can go either way - but people don't always want to download - they may just want to view so the table-thing can be very useful as it means I don't have to take the data elsewhere just to look at it. 

> melt your browser

Can we offer the direct download when this happens? In other words, a timeout offers the advice that you download directly and miss out on the nifty viewer, but at least you get what you need? I suppose then we will need two "tools" view/download and just download.

**Comment by campmlc** [comment]
Is there some reason an attribute table view would be any different from parts table view and identifier table view in context of browser melting? 
I agree these things are equivalent in terms of use and should be standardized in format.  People need to be able to view the attribute table in the same way they view the parts table, with an option to download csv.

**Comment by dustymc** [comment]
>attribute table view would be any different 

 https://github.com/ArctosDB/arctos/issues/6223#issuecomment-1533252348

**Comment by campmlc** [comment]
What is the option then? I'm don't understand the comment.  If browser melting is a risk, we should have a popup that provides a warning (not a red box) with an option to download csv, but we should still provide the table view. A warning box is not very user friendly. Has this ever actually happened?

**Comment by Jegelewicz** [comment]
> Has this ever actually happened?

Not to me, and I have been using the identifier and parts view table tools a bunch over the past few weeks.

My vote is we make the attribute table viewer work just like the other two and if browser-melting becomes a problem we decide if we can offer both options (we are sorta doing that now because we have attributes as direct download and parts and identifiers with a table view) or if we have to abandon the viewer and go straight to downloading.

**Comment by campmlc** [comment]
Strongly agree. And I also use parts table view multiple times weekly.
