### ISSUE TITLE
Check Arctos Legal Tool Error

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6226]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

Maybe it isn't a bug, but the error makes that unclear?

**To Reproduce**
1. Go to https://arctos.database.museum/
2. Click on 'get some search results - https://arctos.database.museum/search.cfm?guid_prefix=MSB%3AMamm&cat_num=10000-10005&customoidoper=LIST
3. Select Tools > Check Arctos Legal (taxonomy)

<html><body>

CurrentID | ArctosLegal | GUIDs from Search Results
-- | -- | --
Lasiurus cinereus |  

</body>
</html>
<html><body>

ERROR_ID | 7FC39F3D-A886-40DF-B1695FCF161AA523
-- | --
ERROR_TYPE | SQL
ERROR_MESSAGE | ERROR: column "scientific_name" does not exist   Position: 61
ERROR_DETAIL |  
ERROR_SQL | select guid from api_jegelewicz_20230503090546657_170 where scientific_name='Lasiurus cinereus' order by guid

</body>
</html>

**Expected behavior**

Receive a report with taxa that are in Arctos Legal and require special handling.

**Screenshots**

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by dustymc** [comment]
I propose we

* shut down the service which maintains Arctos Legal classification, and
* deprecate that tool

The service is pretty spotty, I'm not sure anyone's ever done anything with this thing, and the current search capability provides better-than-equivalent functionality (and can be extended to many other sources).

**Comment by dustymc** [comment]
No objections, https://github.com/ArctosDB/arctos/issues/6894 has some entanglement with this, proceeding.

**Comment by Jegelewicz** [comment]
Pretty sure some people are relying on this for finding "sensitive" species when putting loans together? @ccicero @campmlc

**Comment by campmlc** [comment]
Yes, we do or could use it, when it works. . . . 
If it worked, it would be super helpful. But the tool and the interface are not user friendly. I've posted previously about suggested improvements that would make it actually useful, need to try to track those down.

**Comment by Jegelewicz** [comment]
@dustymc just checking - you aren't removing the Arctos Legal source are you?

**Comment by dustymc** [comment]
We should probably chat.

I'm not proposing to remove the source at the moment, but

1. The way the source is handled is weird/complicated/expensive, and
2. The data are spotty because the API has always been very fragile, and
3. The tools clearly didn't work as imagined, and 
4. There's now a much more robust path to any sort of "whatever according to some source" query, and
5. Managing the data for such things is now trivial

Unless someone has some actual compelling use case of their own, I'm proceeding with removing the API stuff which is making an actual issue more difficult than it needs to be.

IDK if there are any of the old tools still hanging around, but they should be cleaned up if so (barring some timely and unforeseen response to the above).

Given all the above, I think the source just adds confusion and should be removed, or upgraded and adopted, or WHATEVER, but not abandoned.

**Comment by Jegelewicz** [comment]
> We should probably chat.

It seems like this is a fire you are trying to put out? I don't really have any skin in the game - I cannot say that Arctos Legal has helped me out recently and honestly, I don't even remember what I was doing back in May that led me to post this issue!

I guess I really don't understand what is causing the problem?

> The way the source is handled is weird/complicated/expensive, and

How is the source handled?

> The data are spotty because the API has always been very fragile

Our API or an API elsewhere?

> The tools clearly didn't work as imagine

What was imagined?

> Managing the data for such things is now trivial

Like https://github.com/ArctosDB/arctos/issues/6768? I wouldn't call it trivial, there is definitely manual labor involved in transforming data into Arctos taxonomy...but it is possible if someone is willing to make the updates.

**Comment by dustymc** [comment]
>skin in the game

This hasn't worked for a long time and nobody's complained or requested anything even since we noticed and announced.

>definitely manual labor involved

File an Issue or talk to the source about GlobalNames - there's a mechanism by which taxonomic information can be very easily exchanged, or I'll push the buttons.

**Comment by campmlc** [comment]
@cicero and I requested this tool, which is apparently not able to function in Arctos. Closing for lack of bandwidth.

**Comment by dustymc** [comment]
@campmlc I use Issues to track what I'm doing, please do not close until the work has been done.

Anyone, please open a new Issue if there are further questions or concerns.

**Comment by campmlc** [comment]
Absolutely agree. I have expressed the same concern.  Will do from now on.
