### ISSUE TITLE
Feature Request - Replace Define througout with the "eye"

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6229]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

**Describe what you're trying to accomplish** 
An clear and concise overview of the goals; why are you asking for this?

Create a consistent interface. The little "eye" tool to see a definition in the search and results customization splashpage is GREAT! 

![image](https://user-images.githubusercontent.com/5725767/235961046-be17b5b8-d326-4e48-94e9-6e9f15943177.png)

**Describe the solution you'd like**
How might we accomplish your goals?

Can we use it on the search page in place of "Define"?

![image](https://user-images.githubusercontent.com/5725767/235961178-c27f7366-4630-4646-b96b-d030307752a0.png)

**Describe alternatives you've considered**

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by dustymc** [comment]
The functionality of the two things is not identical.
