### ISSUE TITLE
Arctos Report Template Request - Migrating old CFR files

### ISSUE THREAD

**Issue by makaylaeasley** [ArctosDB/arctos#6230]
> I am having problems migrating the old cfr files. I tried to download the ColdFusion app, but somethings not fully working so the app is not installing. I don't know of another way to install the ColdFusion app, or of another app to be able to download and view the old cpr files to start migrating. 

**Description of the report** - [Write a brief description of the report you need. Include link or name of previous report if migrating from a Cold Fusion report.]

https://github.com/ArctosDB/arctos/issues/6230#issuecomment-1533259702

**Collection for which the report is needed** - [Enter the GUID prefix of the requesting collection]

ASNHC:Bird, ASNHC:Herp, ASNHC:Mamm

If this is a request to upgrade from an existing ColdFusion report in Arctos complete the following:

**SQL used in ColdFusion report** - copy the SQl from your old report and paste it here - begin and end it with ``` or it will be invisible. Let us know if there is a prefunction to migrate.

ASNHC:Bird - https://github.com/ArctosDB/arctos/issues/6230#issuecomment-1533263256
ASNHC:Herp - https://github.com/ArctosDB/arctos/issues/6230#issuecomment-1533267316
ASNHC:Mamm - https://github.com/ArctosDB/arctos/issues/6230#issuecomment-1533265552

**Priority** - [Please assign a priority so that the DBA knows whether there is any urgency associated with the new template}

**Comment by Jegelewicz** [comment]
@makaylaeasley list the names of the reports in this issue and I'll see if I can get them for you.

**Comment by Jegelewicz** [comment]
If they are all the reports that start with ASNHC, I think I can get them, but I am not sure that this is what is needed. WThe SQL can be found in Edit Handler

![image](https://user-images.githubusercontent.com/5725767/235964764-9d955bfb-bc94-47b4-8e4e-ba94db841883.png)

Once there, copy this

![image](https://user-images.githubusercontent.com/5725767/235964933-92856ab8-3ed3-4446-8caf-09d0ee71c1db.png)

```
select
    scientific_name,
     case 
      when trim(flat.sex)='male' then 'M'
      when trim(flat.sex)='male ?' then 'M'
      when trim(flat.sex)='female' then 'F'
      when trim(flat.sex)='female ?' then 'M'
      when trim(flat.sex)='unknown' then 'U'
      when trim(flat.sex)='not recorded' then 'U'
      when trim(flat.sex)='recorded as unknown' then 'U'
    end sex,
    flat.parts,
    cat_num,
    country, 
    state_prov,
    county,
    island,
    island_group,
    feature,
    quad, 
    spec_locality,
    flat.verbatim_coordinates,
    MAXIMUM_ELEVATION,
    MINIMUM_ELEVATION,
    ORIG_ELEV_UNITS,
    collecting_source,
    flat.collectors,
    flat.preparators,
    concatotherid(flat.collection_object_id) as other_ids,
    concatsingleotherid(flat.collection_object_id,'collector number') collector_number,
    concatsingleotherid(flat.collection_object_id,'preparator number') preparator_number,
    concatsingleotherid(flat.collection_object_id,'ASK') ASK,
    concatsingleotherid(flat.collection_object_id,'original identifier') original_identifier,
    
    verbatim_date,
    began_date,
    ended_date,
    flat.habitat
FROM
    flat
WHERE
    flat.collection_object_id IN (#collection_object_id#)
ORDER BY
    country, 
    state_prov,
    county,
    cat_num::int
```

And then, if there is anything in Pre-function, add it to the issue too

![image](https://user-images.githubusercontent.com/5725767/235965283-8b4b0e43-5a54-4c1e-822a-2d35cbd3bb4a.png)

**Comment by makaylaeasley** [comment]
The only ones we use are:

ASNHC_Bird_skel_small_2(ASNHC_Bird_skel_small_2.cfr)
ASNHC_mamm_label_vial(ASNHC_mamm_small_label_vial.cfr)
ASNHC_Herp_skel_Medium(ASNHC_Herp_skel_Medium.cfr)

Thank you,
Makayla

***@***.***
Makayla Easley
Collections Manager
Angelo State Univeristy
ASU Station #10890
San Angelo, TX 76909
***@***.***

**Comment by Jegelewicz** [comment]
ASNHC_Bird_skel_small_2(ASNHC_Bird_skel_small_2.cfr)

# SQL
```
select
    scientific_name,
     case 
      when trim(flat.sex)='male' then 'M'
      when trim(flat.sex)='male ?' then 'M'
      when trim(flat.sex)='female' then 'F'
      when trim(flat.sex)='female ?' then 'M'
      when trim(flat.sex)='unknown' then 'U'
      when trim(flat.sex)='not recorded' then 'U'
      when trim(flat.sex)='recorded as unknown' then 'U'
    end sex,
    flat.parts,
    cat_num,
    country, 
    state_prov,
    county,
    island,
    island_group,
    feature,
    quad, 
    spec_locality,
    flat.verbatim_coordinates,
    MAXIMUM_ELEVATION,
    MINIMUM_ELEVATION,
    ORIG_ELEV_UNITS,
    collecting_source,
    flat.collectors,
    flat.preparators,
    concatotherid(flat.collection_object_id) as other_ids,
    concatsingleotherid(flat.collection_object_id,'collector number') collector_number,
    concatsingleotherid(flat.collection_object_id,'preparator number') preparator_number,
    concatsingleotherid(flat.collection_object_id,'ASK') ASK,
    concatsingleotherid(flat.collection_object_id,'original identifier') original_identifier,
    
    verbatim_date,
    began_date,
    ended_date,
    flat.habitat
FROM
    flat
WHERE
    flat.collection_object_id IN (#collection_object_id#)
ORDER BY
    country, 
    state_prov,
    county,
    cat_num::int
```

# pre-function
format_msb

**Comment by Jegelewicz** [comment]
ASNHC_Herp_skel_Medium(ASNHC_Herp_skel_Medium.cfr)

# SQL
```
select
    scientific_name,
     case 
      when trim(flat.sex)='male' then 'M'
      when trim(flat.sex)='male ?' then 'M'
      when trim(flat.sex)='female' then 'F'
      when trim(flat.sex)='female ?' then 'M'
      when trim(flat.sex)='unknown' then 'U'
      when trim(flat.sex)='not recorded' then 'U'
      when trim(flat.sex)='recorded as unknown' then 'U'
    end sex,
    flat.parts,
    cat_num,
    country, 
    state_prov,
    county,
    island,
    island_group,
    feature,
    quad, 
    spec_locality,
    flat.verbatim_coordinates,
    MAXIMUM_ELEVATION,
    MINIMUM_ELEVATION,
    ORIG_ELEV_UNITS,
    collecting_source,
    flat.collectors,
    flat.preparators,
    concatotherid(flat.collection_object_id) as other_ids,
    concatsingleotherid(flat.collection_object_id,'collector number') collector_number,
    concatsingleotherid(flat.collection_object_id,'preparator number') preparator_number,
    concatsingleotherid(flat.collection_object_id,'ASK') ASK,
    concatsingleotherid(flat.collection_object_id,'original identifier') original_identifier,
    
    verbatim_date,
    began_date,
    ended_date,
    flat.habitat
FROM
    flat
WHERE
    flat.collection_object_id IN (#collection_object_id#)
ORDER BY
    country, 
    state_prov,
    county,
    cat_num::int
```

# pre-function
format_msb

**Comment by Jegelewicz** [comment]
@makaylaeasley can you scan the labels that the old reporter output for you and attach the scans to this issue? PDF will work. or take a photo and place the images here. Thanks!

**Comment by makaylaeasley** [comment]
[ASNHC_Bird_skel_small_2.pdf](https://github.com/ArctosDB/arctos/files/11443742/ASNHC_Bird_skel_small_2.pdf)
[ASNHC_mamm_small_label_vial.pdf](https://github.com/ArctosDB/arctos/files/11443743/ASNHC_mamm_small_label_vial.pdf)
[ASNHC_Herp_skel_Medium.pdf](https://github.com/ArctosDB/arctos/files/11443745/ASNHC_Herp_skel_Medium.pdf)

**Comment by dustymc** [comment]
I've started one of these as ASNHC_Bird_skel_small. I think the others may use the same SQL, but we can further adjust if necessary.

MSB at one point had several different ways of manipulating sex. The SQL I've written contains one of them (I think involving values which are no longer in the code table, but extra computational expense here isn't too much of a problem), if that's some sort of "standard" then perhaps we should write a function to handle it. (That would be a way to guarantee that 'male' in always results in M out, and if we decide we really want ♂ out then we'd change one thing and all 9876 reports would magically follow.)

The rest of the format_msb pre-function is the same idea - turn ``United States`` into ``USA`` and such. That was all written for a fairly primitive query language, we can do better now (if necessary - I think a bunch of that stuff was never used on labels at all).

1. If this is for a label or three, let me know what's needed and I'll do it in the query
2. If this is some "standard" thing, let me know and I'll write a function that we can all use and add it to the query
3. If this is some super-weird one-off thing that's beyond all of that, I'll do something like I've done for uam_mamm_label_csv

**Comment by dustymc** [comment]
done?
