### ISSUE TITLE
Feature Request - taxonomy classification source suggest

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6231]
**Is your feature request related to a problem? Please describe.**

Ref: https://github.com/ArctosDB/arctos/issues/5444#issuecomment-1372903429 - it's occasionally useful for various reasons to query by taxonomy which isn't managed in Arctos. I'm going to re-do the source selector to be a suggest-with-type to better facilitate this. I'm going to do this using https://arctos-test.tacc.utexas.edu/info/ctDocumentation.cfm?table=cttaxonomy_source as the source, which means users will have to know and type other values.

Selecting source from the data takes well over a minute. If we want to suggest more than managed sources, we'll need a cache or something. (And if we're going to mix local data with whatever else is in there, we may want a prefix-or-something.)

Do we need to build some sort of cache, or is limiting suggest to the local data sufficient?

**Describe what you're trying to accomplish** 

Query using any taxonomy.

**Describe the solution you'd like**

Understand what's useful.

**Describe alternatives you've considered**

??

**Additional context**

In case anyone's curious, here are current source of taxonomy:

 3i - Typhlocybinae Database
 AlgaeBase
 American Ornithological Society
 AntWiki (via Arctos)
 Arctos
 Arctos Culture
 Arctos Ichnology
 Arctos Legal
 Arctos Plants
 Arctos Relationships
 Arctos Rocks
 ASM Mammal Diversity Database
 ASM Mammal Diversity DB
 Belgian Species List
 BirdLife International
 Catalogue of Life
 Catalogue of Life Checklist
 Catalogue of Life - June 2021
 CATE Sphingidae
 Checklist da Flora de Portugal (Continent...
 Checklist da Flora de Portugal (Continental, Açores e Madeira)
 Checklist of Beetles (Coleoptera) of Canada and Alaska. Second Edition.
 Clements' Birds of the World
 Current Amphibian Classification
 Current Reptile Classification
 Dana 8 (via Arctos)
 Database of Vascular Plants of Canada (VASCAN)
 Discover Life Bees
 Discover Life Bee Species Guide
 EUNIS
 FishBase Cache
 Freebase
 Freshwater Animal Diversity Assessment - Normalized export
 Fungal Names
 GBIF Backbone Taxonomy
 Getty AAT (via Arctos)
 GRIN Taxonomy for Plants
 Gymno
 Heys CIM (via Arctos)
 /home/dimus/files/dwca/zoological names.zip
 Howard and Moore Complete Checklist of the Birds of the World
 Howard & Moore Birds of the World
 iNaturalist
 Index Fungorum
 Index Fungorum (Species Fungorum)
 Integrated Taxonomic Information SystemITIS
 Interim Register of Marine and Nonmarine Genera
 IOC World Bird List
 IPNI
 IRMNG
 IRMNG (old)
 ITIS
 Leipzig Cat. Vasc. Plants
 Mammal Species of the World
 MCZbase
 Myriatrix
 National Center for Biotechnology Information
 NCBI
 Nickel-Strunz 10 (via Arctos)
 Nomenclature 4.0 (via Arctos)
 Open Tree of Life
 Open Tree of Life Reference Taxonomy
 PaleoBioDB
 Sendoya S., Fernández F. AAT de hormigas (Hymenoptera: Formicidae) del Neotrópico 1.0 2004 (Spreadsheet)
 Terrestrial Parasite Tracker
 The eBird/Clements Checklist of Birds of the World
 The Interim Register of Marine and Nonmarine Genera
 The International Plant Names Index
 The Leipzig Catalogue of Vascular Plants
 The Mammal Species of The World
 The Paleobiology Database
 The Reptile Database
 The Reptile DataBase
 The Terrestrial Parasite Tracker
 TPT (via Arctos)
 UAM Art
 Union 4
 VASCAN
 Wikispecies
 World Checklist of Vascular Plants
 World Flora Online
 World Flora Online consortium
 World Register of Marine Species
 WoRMS
 WoRMS (via Arctos)
 Zoological names

**Priority**

Low; this would just be a helper, not change any functionality.

**Comment by dustymc** [comment]
See also https://github.com/ArctosDB/arctos/issues/6281#issuecomment-1544410250 - this may be equally overwhelming / not worth doing ??

**Comment by Jegelewicz** [comment]
> this may be equally overwhelming / not worth doing 

I'm not sure I actually understand the proposal!

**Comment by dustymc** [comment]
>understand the proposal!

<img width="551" alt="Screenshot 2023-05-11 at 11 26 02 AM" src="https://github.com/ArctosDB/arctos/assets/5720791/af07ebe4-33bf-435c-b35c-5e0bc54dd70e">


 on


<img width="249" alt="Screenshot 2023-05-11 at 11 26 29 AM" src="https://github.com/ArctosDB/arctos/assets/5720791/5dea2d7a-d670-4e12-ada2-136b18434e82">


using.^^.

**Comment by Jegelewicz** [comment]
I see - that doesn't seem too awful if instead of listing everything that includes a letter, listing things that start with it - possible? And if I type Wo, I get a list of things that start with Wo?

A cache seems fine - provide for a periodic update (don't know how often that should be, but maybe you have an idea?)

**Comment by dustymc** [comment]
I think we need something much more compelling than "doesn't seem too awful" to add significant CPU demand, complexity, storage, and maintenance! Probably some sort of sustainability evaluation should be part of https://github.com/ArctosDB/internal/issues/258, but IDK what that might look like. @mkoo

**Comment by Jegelewicz** [comment]
> is limiting suggest to the local data sufficient?

I think it would be. Can we do that then close this? Nobody seems to be using this (or complaining about it) right now, so it doesn't seem like a huge priority....
