### ISSUE TITLE
Agent Merge Request

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6234]
Use this template when you discover two agents that you believe represent the same person or organization.

**Agent that should remain after the merge**
 unknown

**Agent that will no longer remain after the merge**

[C. N. Morgan](https://arctos.database.museum/agents.cfm?agent_id=21348285).

That's probably a bad idea.

**Reason for merge**

Can we revisit minimum quality guidelines? This doesn't seem capable of awesomification.

Please add this issue to the Agents Project

@ArctosDB/agents-committee

**Comment by ewommack** [comment]
Ok what is going on? I took a look at it appears that the agent could be listed as a student of Angelo State University, but they were not, so people are forcing agents without adding info to them?

**Comment by Jegelewicz** [comment]
I have emailed the creator - let's see if we can get this fixed up before we do drastic things.

**Comment by Jegelewicz** [comment]
If anything, this is the same person as [Clint N. Morgan](https://arctos.database.museum/agent/21317038)

**Comment by Jegelewicz** [comment]
Marked as bad duplicate of [Clint N. Morgan](https://arctos.database.museum/agent/21317038).
