### ISSUE TITLE
Help correcting longitudes loaded yesterday

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6236]
@dustymc yesterday @acoconis loaded some data and inadvertently left off the negatives from her longitudes. How can we make these corrections easily in bulk? Any advice to make this less manual is appreciated!

**Comment by dustymc** [comment]
I'm not sure that there's a tool. I can possibly update them if they're somehow easy to find. Encumber/delete/reload is probably easiest if they're very recent.

**Comment by dustymc** [comment]
Depends on the data, I can check.

**Comment by Jegelewicz** [comment]
@acoconis could you build that file? If not, send be your bulkload file and I'll do it!

**Comment by acoconis** [comment]
Hi there. Thank you for the help. So in reality, there is only 34 records that I need to correct. I can probably do this manually, or as Dusty said encumber, and delete. However, I am having another issue. I have manually changed 4 records. The map has been corrected as well, but it still has an orange box around it. The error says "There is no spatially appropriate geography for this locality." What is the fix for this? Thanks!

**Comment by acoconis** [comment]
> @acoconis can you send me a link to one of the records?

https://arctos.database.museum/guid/UNR:Mamm:4117

Thanks!

**Comment by Jegelewicz** [comment]
@acoconis I do not have edit access to the collection, so I can only see this as a public user would and this is what I see

![image](https://user-images.githubusercontent.com/5725767/236944767-37806c0c-a601-4c70-beb4-b2f69f08b2dc.png)

so from a public perspective this looks OK until I click on the map border key

![image](https://user-images.githubusercontent.com/5725767/236945591-26e8c93b-d339-473f-9bef-f0c6147c53d5.png)


@dustymc please correct me, but I believe this is happening because you haven't added an error to the point coordinates.

**Comment by Jegelewicz** [comment]
@dustymc see above - can you provide me the details for what `Spatial data are not available` means?

**Comment by dustymc** [comment]
https://github.com/ArctosDB/internal/issues/222 - I'm very resource-limited, refreshing is slow. 

The error will clear whenever it refreshes - but the suggested locality seems to match the description better than the asserted.

**Comment by acoconis** [comment]
So just to clarify, the orange means that the suggested locality is a better match to the description, but that "error" is only temporary, and that will eventually disappear without manually telling it that I want to keep my original lat/lon?

**Comment by dustymc** [comment]
Definitely not an error, just a flag - it can mean there's some problem, or just that enough of something doesn't fall within some admin area. This particular example should clear up entirely.

>details for what Spatial data are not available

The assertion doesn't fall entirely (ish, I think it's some %) within one authority-shape. Could be a gap in coverage, or just spans some country or land/sea border.

And in case "suggested locality seems to match the description better than the asserted" isn't clear:

<img width="1413" alt="Screenshot 2023-05-11 at 1 29 08 PM" src="https://github.com/ArctosDB/arctos/assets/5720791/7bf2a9b9-ea04-467e-899e-4254ae9deb84">

**Comment by Jegelewicz** [comment]
@acoconis do you need anything else here or can we close?
