### ISSUE TITLE
UI modify results (remove/select row)

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#6237]
From Issues Meeting:
Can we modify the 'Remove Row' option in the search results to make it selectable with an inverse option?
![image](https://user-images.githubusercontent.com/12507297/236301087-902cc5db-b428-4250-88d6-28b8bd1338de.png)

**Comment by dustymc** [comment]
"no, but..."

The remove button just writes (internal) identifiers to a field, then a requery filters using them.

<img width="229" alt="Screenshot 2023-05-04 at 2 51 29 PM" src="https://user-images.githubusercontent.com/5720791/236337791-0c4812af-b090-4492-bb45-7f04a3faf1c2.png">

We could add another button to write to 


<img width="216" alt="Screenshot 2023-05-04 at 2 52 16 PM" src="https://user-images.githubusercontent.com/5720791/236337905-c65270b8-4abd-42fc-b7ad-e9bea50d3b65.png">


or maybe even 

<img width="299" alt="Screenshot 2023-05-04 at 2 52 42 PM" src="https://user-images.githubusercontent.com/5720791/236337960-57935266-8b2d-4888-b899-e6a67232b15b.png">

if we want to be a little less opaque.

I think that could be done as a new option, or perhaps it would be better to change the existing to 'add/remove' or something of the sort.

**Comment by acdoll** [comment]
So, is the checkbox type option we used to have just not an option with the current table library (or whatever you call it)? 
What I would like it to accomplish is to be able to do a general search that returns lots of records, then requery for just a small subset of selected records. Then I can use the short list for download or printing labels or whatever.
Anything over 10-15 click-to-remove-rows begins to test my patience.

**Comment by dustymc** [comment]
>checkbox type option we used to have just not an option with the current table library

Correct. 

>small subset

Any widget would require the same number of checks, or I'm not understanding something.

* Find 40K birds
* Check three "keep" boxes
* requery

or


* Find 40K birds
* click three "keep" buttons
* requery

**Comment by Jegelewicz** [comment]
But we don't have a "keep" checkbox? Just a remove....

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/6237#issuecomment-1535459503

Are some of my comments not visible?

**Comment by Jegelewicz** [comment]
> Are some of my comments not visible?

Totally not visible! Especially when I'm looking at it after 5PM...

Sorry!

**Comment by acdoll** [comment]
> or I'm not understanding something

No, you've got it. This will work for what I'd need.

**Comment by dustymc** [comment]
Proposed dev issue:

-----------------


## Source

https://github.com/ArctosDB/arctos/issues/6237

## Summary

Change search results option "remove rows" to "keep/remove," rewrite so that selecting this will add a "keep"  button beside the current 'remove' button.

## User Interface Changes

See above

## Data Structure Changes

None

**Comment by dustymc** [comment]
In dev queue at https://github.com/ArctosDB/arctos-dev/issues/19
