### ISSUE TITLE
Feature Request - post-login splash page

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6238]
**Is your feature request related to a problem? Please describe.**

Possible to change 'continue' to a button and focus on it?

**Comment by campmlc** [comment]
Any way we can see the mockup of the current proposal in test? That way we can all be on the same page.
If we have to have this post login splash page, which I personally don't support but whatever, then we need to make it easy to acknowledge from the keyboard, without having to mouse over to yet another click box.
