### ISSUE TITLE
Media thumbnails inconsistently showing at search results

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#6246]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
When jpegs are uploaded to catalog records, some end up not not consistently being visible in our search results. We've noticed that some thumbnails are perfect, some are using the generic "media available" Arctos bear, some are showing a strange icon implying there is an image that exists but doesn't want to be seen, and still others don't show up at all!

**To Reproduce**
Show all results for UAM:EH UA2020-008 accession (Bus 142 collection). Go to items UA2020-008-0101+ and you'll see inconsistent thumbnail representation.

**Expected behavior**
All thumbnails should show for the collection in the search results.

**Screenshots**
A range of weird icons visible in this group:
<img width="789" alt="Screenshot 2023-05-04 at 3 22 07 PM" src="https://user-images.githubusercontent.com/17605945/236350848-722e5d9b-5872-40ad-ad5f-dcdc65a7854f.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac OS 13.2.1
 - Browser [e.g. chrome, safari] Same results in Firefox and Brave
 - Version [e.g. 22] Firefox 109.0.1 ; Brave [Version 1.51.110 Chromium: 113.0.5672.77 (Official Build) (arm64)](https://brave.com/latest/)

**Additional context**
I noticed on some of the image files (almost all of which are jpegs under 1MB when uploaded) they were loaded with a relationship of "documents catalog_item" instead of "shows cataloged_item" [can I make a new issue to change the default to be "shows" instead of "documents"?]. However, not ALL of the missing images have this relationship and not all media files with this relationship don't show up... however, all of the ones with "documents' that we changed to "shows" did show up in results after a refresh.

**Priority**
Medium-high
The media thumbnail files are visible when you go into the catalog record, so nothing is technically missing. Not being able to see them in the search results makes it harder to do quicker research.

**Comment by dustymc** [comment]
Looks like the cache got out of whack. I set the accession to refresh.

FYI you can request a refresh for single records:

<img width="275" alt="Screenshot 2023-05-04 at 4 46 25 PM" src="https://user-images.githubusercontent.com/5720791/236352875-227ea423-bd2f-498a-bd2b-d77563beb473.png">

**Comment by dustymc** [comment]
https://arctos.database.museum/search.cfm?accn_number=%3DUA2020-008&sp=preset_eh

**Comment by AJLinn** [comment]
Spectacular!

> FYI you can request a refresh for single records:

Thanks for the tip.

**Comment by AJLinn** [comment]
> FYI you can request a refresh for single records:

@dustymc Can I /should I do this any time I see a media thumbnail not loading either in the search results view or within a catalog record? I have a bunch that are showing the same icons as indicated above.
