### ISSUE TITLE
Code Table Request - REMOVE identification confidence unknown

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6247]
## Instructions

_This is a template to facilitate communication with the Arctos Code Table Committee. Submit a separate request for each relevant value. This form is appropriate for exploring how data may best be stored, for adding vocabulary, or for updating existing definitions._

_Reviewing documentation before proceeding will result in a more enjoyable experience._

* [Issue Documentation](http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html)
* [Code Table Documentation](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html)
* [Video Tutorial - Submit a Code Table Request](https://youtu.be/t2jHbsRA3lk)

------------------------------

## Initial Request

_**Goal**: Describe what you're trying to accomplish. This is the only necessary step to start this process. The Committee is available to assist with all other steps. Please clearly indicate any uncertainty or desired guidance if you proceed beyond this step._

Remove extraneous data from Arctos. Is there a reason to add unknown here?

_**Proposed Value**: Proposed new value. This should be clear and compatible with similar values in the relevant table and across Arctos._

REMOVE unknown [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctidentification_confidence#unknown)

_**Proposed Definition**: Clear, complete, non-collection-type-specific **functional** definition of the value. Avoid discipline-specific terminology if possible, include parenthetically if unavoidable._

_**Attribute data type** If the request is for an attribute, what values will be allowed?
free-text, categorical, or number+units depending upon the attribute (TBA)

_**Attribute controlled values** If the values are categorical (to be controlled by a code table), add a link to the appropriate code table. If a new table or set of values is needed, please elaborate.

_**Attribute units** If numberical values should be accompanied by units, provide a link to the appropriate units table.

_**Context**: Describe why this new value is necessary and existing values are not._

_**Table**: Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table or value. This may involve multiple tables and will control datatype for Attributes. OtherID requests require BaseURL (and example) or explanation. Please ask for assistance if unsure._

_**Collection type**: Some code tables contain collection-type-specific values. ``collection_cde`` may be found from https://arctos.database.museum/home.cfm_

_**Priority**: Please describe the urgency and/or choose a priority-label to the right. You should expect a response within two working days, and may utilize [Arctos Contacts](https://arctosdb.org/contacts/) if you feel response is lacking._

_**Available for Public View**: Most data are by default publicly available. Describe any necessary access restrictions._

_**Project**: Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184)._

_**Discussion**: Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary._

@ArctosDB/arctos-code-table-administrators 

## Approval

_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality)._

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval - https://github.com/ArctosDB/arctos/issues/6247#issuecomment-1536331618
- [x] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection

_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation

_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

_Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel._

_Make changes as described above. Ensure the URL of this Issue is included in the definition._

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by dustymc** [comment]
```
select guid_prefix,count(*) 
from 
identification
inner join cataloged_item on identification.collection_object_id=cataloged_item.collection_object_id
inner join collection on cataloged_item.collection_id=collection.collection_id
where identification_confidence='unknown'
group by guid_prefix order by guid_prefix;

 guid_prefix | count 
-------------+-------
 ALMNH:EH    |     5
 ALMNH:Geo   |     3
 ALMNH:Inv   |     1
 ALMNH:Paleo |   153
 APSU:Herp   | 11341
 ASNHC:Bird  |     3
 ASNHC:Mamm  |     2
 CHAS:Bird   |    45
 CHAS:Ento   |    10
 CHAS:Herb   |  6676
 CHAS:Inv    |     1
 CHAS:Teach  |    50
 CRCM:Bird   |     2
 DMNS:Bird   |     3
 DMNS:Egg    |     2
 DMNS:Inv    |  2841
 DMNS:Mamm   |   292
 HMCM:Herb   |     1
 MSB:Bird    |     2
 MSB:Herp    |   330
 MSB:Host    |    10
 MSB:Mamm    |    26
 MSB:Para    |    10
 MVZ:Bird    |     4
 MVZ:Herp    |     4
 NMMNH:Paleo |   189
 UAM:Ento    |  1377
 UAM:Fish    |    20
 UAM:Herb    |     2
 UAM:Inv     |     4
 UAMObs:Ento |    39
 UMNH:Bird   |     1
 UMNH:Herp   |     4
 UMZM:Bird   |     7
 UMZM:Mamm   |     5
 UNR:Mamm    |     1
 UTEP:Ento   |   401
 UTEP:ES     |     1
 UTEP:Herb   |     1
 UWBM:Mamm   |    17

```

**Comment by Jegelewicz** [comment]
A lot of these are probably somebody doing data entry believeing they had to complete this field, and not knowing an answer, selecting "unknown".

![image](https://user-images.githubusercontent.com/5725767/236865609-fa6d80be-2b64-4cac-a727-fa5bdf881a41.png)

@gradyjt if we removed all of the "unknown" id confidence from the APSU:Herp collection, would it make any difference?

**Comment by gradyjt** [comment]
Nah, go ahead 👍sorry about that

**Comment by genevieve-anderegg** [comment]
I'll discuss with Phyllis and Andy

**Comment by Jegelewicz** [comment]
UTEP:ES and UTEP:Herb fixed

**Comment by Jegelewicz** [comment]
@jebrad 
@wellerjes 
@babogan 

See above.

**Comment by wellerjes** [comment]
Okay on our end.

**Comment by Jegelewicz** [comment]
@Nicole-Ridgwell-NMMNHS @DerekSikes see https://github.com/ArctosDB/arctos/issues/6247#issuecomment-1536354642

**Comment by Jegelewicz** [comment]
ASNHC records remoed and added to ID remark.

**Comment by Jegelewicz** [comment]
CRCM records removed and added to ID remark.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Yes, you can remove confidence unknown from NMMNH Paleo IDs.

**Comment by genevieve-anderegg** [comment]
Spoke with @acdoll and @sharpphyl , good to go for DMNS:Inv

**Comment by Jegelewicz** [comment]
This is dragging on - suggest we bring it before the AWG and either do it or drop it.

**Comment by dustymc** [comment]
This seems like something for which we should have some abbreviated administrative process. I can't see any possible functional distinction between "Determiner(s), or collection personnel on behalf of determiners(s), have expressed that they do not know how confident the identification is." and nothing (AKA no attribute). It's nice to get some acknowledgement that we're not missing some obvious gotcha, which the ~15 positive responses overwhelmingly indicate. If we do somehow still completely mangle it, I always drop pre-update CSV (which can be used to reverse anything that happens) on these issues - this just can't POSSIBLY be lossy! Can we get the AWG to address that slightly bigger picture?

**Comment by Jegelewicz** [comment]
> This seems like something for which we should have some abbreviated administrative process. 

We DO - all this needs is one more box checked by @ArctosDB/arctos-code-table-administrators and it could proceed. However, we are already cheating since I flied the issue and approved it. I don't know how we can get more Code Table Admin participation, but that is really all we need to get some stuff done.
