### ISSUE TITLE
Reciprocal Relationships question

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6248]
I would like clarification on how reciprocal relationships between records within the same institution and across institutions are approved and created now that we have shifted to using the component loader system.

When we first developed reciprocal relationships as Other IDs a decade ago, a collection would create an other ID with some relationship other than self to another record. Then an email notification would be sent out to the appropriate collection managers of the reciprocal collection, informing them of the asserted relationship, and requiring action on their part to approve the reciprocal. This email notification contained a summary table with each guid as a live link to the affected records in their collection, with the proposed relationship visible, and an option to approve. The actual relationships were in some version of what is now the component loader system.

Now, we are no longer receiving email notifications.  The reciprocal relationship notification is mixed in with the long list of other random notifications we are supposed to review at login - that no one has time to review. But regardless, if you filter the list for the term reciprocal, you can find the notification, if you know it might be there. Most people with several thousand notifications (which accumulate rapidly to this level) are not going to do this - and I'm afraid the notification will get deleted and lost.

Once the notification is found, then the related collection manager clicks the link embeded in the notification, and they get a prepared csv of the identifier bulkload file which allows them to load that through the component loader. But unlike our previous system, there is no easy way for a collection manager in another collection or institution to quickly spot check the asserted relationships, because there is no preview table with live links to the guids, as we used to have. So we are loading these relationships blind, with no idea who created them, an no ability to spot check for accuracy of the link. Even when I am the one creating these relationships, and I have reasonable understanding in what was done and reasonable confidence that most of the assertions should be correct - I hesitate to load these. I can't imagine another collection manager doing so.

Is there any chance we can restore the format of the reciprocal notification so that we get a link to a preview table of asserted guids and relationships, with live links in the guids? Without this, I don't see this system working. I can create host relationships to parasite records, but no host collection will ever create the reciprocal without some means of verifying the assertions first.

**Comment by dustymc** [comment]
I've been trying to achieve this for a very long time.

https://github.com/ArctosDB/arctos/discussions/5310

https://github.com/ArctosDB/arctos/issues/6163

**Comment by campmlc** [comment]
Given I now have over 5000 pending reciprocal relationships to load, and I'm hesitant to do this without some means of checking and verifying, I'd like to see if we can move this forward?
See #6511 for more detail.

**Comment by campmlc** [comment]
Also need Id issued by and date metadata added to Other ID component loader.

**Comment by Jegelewicz** [comment]
@campmlc if we convert the Arctos identifiers to the urls, the links will "just be there" in the file.

As for the other stuff you want - that's some code on the file for download.
