### ISSUE TITLE
Code Table Request - add studbook number

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6252]
## Initial Request

_**Goal**: 
Add studbook number to the identifiers code table, so that eventually this can be used to find endangered species identifiers in combination with issued by agent, and help reduce the other identifiers table. This value is necessary as the issuing agents in question have multiple identifier types, and we need the ability to explicitly search on studbook values issues by this agent.

_**Proposed Value**: 
studbook~~number~~ https://github.com/ArctosDB/arctos/issues/6252#issuecomment-1538794758

_**Proposed Definition**: 
~~The studbook number is used by endangered species recovery programs, zoos, and other breeding facilities to document the pedigree and entire demographic history of each animal within a managed population.~~ 

A breed registry, herdbook, or register; an official list of animals within a specific breed whose parents are known. May be used by endangered species recovery programs, zoos, and other breeding facilities to document the pedigree and entire demographic history of each animal within a managed population.

_**Context**: Describe why this new value is necessary and existing values are not._
We currently have "Mexican wolf studbook number" in the other identifiers code table. Adding this value will allow use for other breeding programs, and will allow conversion of the former ID to "studbook number" issued by "Mexican Wolf Recovery Program". Use of "other identifier" for value in this context is unacceptable because these agencies typically issue multiple identifier types, and the identifier needs to explicitly reference the studbook number. These are collaborative projects that need to use clear and mutually understood terms acros agents and agencies, for external as well as internal users. Arctos needs to reflect the needs of the broader user community in this context.

_**Table**:  https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type

_**Priority**: Normal to High. We need to clarify how we are setting up search profiles for these external agencies, so that they can find records of deposited specimens in Arctos collections. 

_**Available for Public View**: Most data are by default publicly available. Describe any necessary access restrictions._

_**Project**: Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184)._

_**Discussion**: Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary._

@ArctosDB/arctos-code-table-administrators 

## Approval

_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality)._

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval - https://github.com/ArctosDB/arctos/issues/6252#issuecomment-1542312167
- [x] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection

_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation

_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

_Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel._

_Make changes as described above. Ensure the URL of this Issue is included in the definition._

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by dustymc** [comment]
I will support this as a step in the right direction if implementation can include finalizing https://github.com/ArctosDB/arctos/issues/5936, but 

1. The definition seems very overly focused, suggest something more like modified wiki copypasta: "A breed registry, herdbook, studbook or register; a list of animals whose parents are known."
2. ``because these agencies typically issue multiple identifier types`` - there is still some great misunderstanding involved in this, if you could provide some sort of an example, explanation, ANYTHING that might help me understand why you think this matters, it would be greatly appreciated.

**Comment by campmlc** [comment]
That definition includes the term being defined. . .and it's more general than the context we are using it for, but it still could work. 
I believe we are having a meeting to go over entities, so I can explain my concerns there with visuals. But if we can add this and related identifiers, and I can see if it works, that might help resolve the larger issue.

**Comment by campmlc** [comment]
If this is approved, I will also need this added to the customize results options in Search, so I can create a profile.

**Comment by dustymc** [comment]
>more general

I think that's good - certainly a researcher might want to know the pedigree of anything from a racehorse to a fruitfly, and I can't see how that falls outside of this, assuming we must have this pigeonhole. (So someone please illuminate if it does!)

>see if it works

That's the problem with babysteps - at best, they tend to wander around a lot before getting anywhere from which the intended system is truly visible.

>customize results options in Search, so I can create a profile.

That does not seem to be understood either. As a hopefully-clarifying but somewhat ridiculous example, https://arctos.database.museum/search.cfm?sp=uam_art&id_issuedby=United%20States%20Fish%20and%20Wildlife%20Service%20Mexican%20Wolf%20Recovery%20Program is an art profile and some search criteria.

>meeting

Surprise!? Can you add that to the Arctos calendar, or tell me how to find it please?

**Comment by campmlc** [comment]
Well, if you want to get rid of "Mexican Wolf Studbook Number" and replace
it with something general, this is the only route MSB will accept. If it
isn't workable, then we keep the former, and we need that specific
identifier added to customized search and results as soon as possible.

I'll see if I can find Beth's notes from yesterday, but we all agreed to
meet and discuss entities. It may not yet be scheduled. I'm on my phone,
but will look later on computer.

**Comment by Jegelewicz** [comment]
can we just use studbook? I'd like to get away from adding "number" in the identifier types.

**Comment by campmlc** [comment]
Sure. studbook is fine.

**Comment by Jegelewicz** [comment]
> ``because these agencies typically issue multiple identifier types`` - there is still some great misunderstanding involved in this, if you could provide some sort of an example, explanation, ANYTHING that might help me understand why you think this matters, it would be greatly appreciated. 

Let's change this up to think about how anyone who is unfamiliar with Arctos might come at this. I could see how people looking at identifier type would want to find studbook things, no matter who issued the identifier, so perhaps the combination of the specific issuer with the generic "studbook" provides a path for people coming at it from either direction (I only care about AZA studbook stuff OR I only care about Mexican Wolf Recovery Program stuff OR I want them all...)

**Comment by campmlc** [comment]
That is what I thought we were aiming for? 
Studbook as an ID value, and then any variety of agents that might issue one. Issued by as an agent, and any possible set of identifier types for that agent. Enter both to specifically target only studbook number issued by Mexican Wolf recovery program. 
And that latter combination is what I need to create entities.

**Comment by Jegelewicz** [comment]
> That is what I thought we were aiming for?

Just trying to explain that as I am not sure that particular argument has been laid out here. I have added my OK for this with the changes I proposed in the original comment.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> Studbook as an ID value, and then any variety of agents that might issue one

Sounds good to me.

**Comment by Jegelewicz** [comment]
added
