### ISSUE TITLE
Unable to access test server

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6253]
# Error Text
![Screenshot 2023-05-07 14 18 12](https://user-images.githubusercontent.com/14808196/236700863-e3d411b5-5970-4603-abe1-4c25f0c4f4f5.png)

# Where it happened
Trying to access url from Chrome

# Steps to get there
**Describe the actions that led to the error**

# Problem
**Community response to describe the problem that caused the error**

# Solution
**Community response with directions for how to correct the problem**

**Comment by mkoo** [comment]
Try logging in at: https://arctos-test.tacc.utexas.edu/
(that's the old URL so bookmark the above)
MK

**Comment by campmlc** [comment]
Thanks!
