### ISSUE TITLE
Add Issued By = Arctos to UUIDs

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6255]
> These are generated by Arctos. 

_Originally posted by @campmlc in https://github.com/ArctosDB/arctos/issues/6251#issuecomment-1536563170_

Let's make that clear by adding Issued By = [Arctos Consortium](https://arctos.database.museum/agents.cfm) when they are generated.

**Comment by dustymc** [comment]
This still isn't UI.

IDK how this would work, but I think it would have to have some sort of significant impact on https://github.com/ArctosDB/arctos/issues/6171 (and maybe all related component loaders???).

Usage of UUIDs of the form mentioned in the source issue should also mostly be eliminated by that change so ???

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/6171 updated
