### ISSUE TITLE
Extremely limited record download with attributes

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#6256]
I am trying to download records with attributes and can only see/download 500 at a time. I am trying to get all the measurement data for all the Peromyscus maniculatus at MVZ. I am only searching on SIX fields, only TWO of those are attributes. And still only 500 records. How can I get more?  As RANGES populates more fields and more specimens, how are we going to get the data out? I hope I am just missing something here. 
Somehow, earlier today I searched for all MVZ mammals from Joseph Grinnell and found 4693 records with more fields. I just tried again with the 6 fields and now only getting 500 records. 
It would be swell if there were some bell or whistle that would tell a user why they were only getting 500 records and how to improve their results. 
<img width="513" alt="Screenshot 2023-05-08 at 3 51 06 PM" src="https://user-images.githubusercontent.com/5749672/236954662-e92b09ea-0d67-4cea-83f4-812cb2d507b1.png">

**Comment by Jegelewicz** [comment]
@cjconroy Limit your results to a few fields, this will allow you to get all of the records you need. When I am working with attributes, I only ask for GUID and identification or maybe other identifiers in results, then I use the tool Dusty pointed out above to get the attributes that I need.

**Comment by dustymc** [comment]
>few fields

They'll add up, but individually (almost?) everything except Attributes should have little impact at this point.

**Comment by cjconroy** [comment]
OK, I am down to just THREE fields in results. My only search criteria are Peromyscus maniculatus, asserted state is California, and tail length greater than 1. My only results columns are Tail Length, Total Length, and Specific Locality. Still only 500 records. 

<img width="555" alt="Screenshot 2023-05-09 at 8 47 25 AM" src="https://github.com/ArctosDB/arctos/assets/5749672/2efb1195-2ae0-4763-a443-d50f7217cdeb">
<img width="1120" alt="Screenshot 2023-05-09 at 8 49 21 AM" src="https://github.com/ArctosDB/arctos/assets/5749672/0dd0fd61-5a1f-46b2-baa2-09411af04d12">

**Comment by Jegelewicz** [comment]
Using the attributes in results severely limits the output. Remove them and see what you get - as a reminder, you DO NOT need to include ANY attributes in results to get them all from the tool that Dusty pointed out.

**Comment by cjconroy** [comment]
Thanks, that works. However, the spreadsheet has one column for all attributes. Can Arctos put each attribute in a different column?  Or do you know an easy way to convert a spreadsheet like this to something useful? Pivot table?  
<img width="1042" alt="Screenshot 2023-05-09 at 10 20 44 AM" src="https://github.com/ArctosDB/arctos/assets/5749672/fbbc09b5-c415-4a1e-bcbc-ac096ee08631">

**Comment by Jegelewicz** [comment]
My solution is to use a lookup - get the unique values of all the attributes in the download and the unique GUIDs - put the unique GUIDS in the first column of another sheet and the unique attributes in the column headers (it takes a little bit of building for the column headers if you want to get all the attribute information, but once you have done this once, you can re-use them). Then use a bunch of lookup formulas to get everything out of the download.

A pivot table might work too! I haven't tried that for this. If you want to send me the download (attach it here) I'll work up the lookups. If you get a pivot table to work - send details! I think a lot of people might want this. I have also thought that an R or Python script could be useful, but I don't know how many people use those tools...

**Comment by cjconroy** [comment]
Thanks. Here is the basic situation. I just want to plot total length vs. tail length for all of our California deermice. Hopefully someone on this list will see a super easy way to rearrange this csv to make that possible. Back when we could see and download all the attributes, they were in their own columns. So, this is a step backwards. 
[attributeDataDownload (1).csv](https://github.com/ArctosDB/arctos/files/11434339/attributeDataDownload.1.csv)

**Comment by Jegelewicz** [comment]
Let me know if this works.
[attributeDataDownload.1.xlsx](https://github.com/ArctosDB/arctos/files/11434642/attributeDataDownload.1.xlsx)

**Comment by cjconroy** [comment]
That's great. What were your steps? Thanks.

**Comment by dustymc** [comment]
>backwards

I don't think so, it's just a recognition of the reality that data aren't always simple and Arctos doesn't always squish into a spreadsheet. Ideas for dealing with that in some way that's convenient to you would be very appreciated in 6111.

These are surprisingly clean, but there are still some units in inches and multiple determinations which I think would somehow mess with the column-in-a-spreasheet view, plus a few methods and remarks that might be worth considering. Ignoring all that....

```
create table temp_ttlcp as select
flat.guid,
round(to_meters(t.attribute_value::numeric,t.attribute_units)* 1000) as tail_length,
round(to_meters(tl.attribute_value::numeric,tl.attribute_units)* 1000) as total_length
from flat 
inner join attributes t on flat.collection_object_id=t.collection_object_id and t.attribute_type='tail length'
inner join attributes tl on flat.collection_object_id=tl.collection_object_id and tl.attribute_type='total length'
where 
flat.species='Peromyscus maniculatus' and 
flat.state_prov='California' 
```
[temp_ttlcp.csv](https://github.com/ArctosDB/arctos/files/11436633/temp_ttlcp.csv)



```


arctosprod@arctos>> select guid from temp_ttlcp group by guid having count(*) > 1 ;
      guid       
-----------------
 MSB:Mamm:318403
 MSB:Mamm:318459
 MSB:Mamm:318471
 MSB:Mamm:318573
 MSB:Mamm:318484
 MSB:Mamm:318437
(6 rows)

arctosprod@arctos>> select max(tail_length), max(total_length) from temp_ttlcp;
 max | max 
-----+-----
 147 | 211
(1 row)

arctosprod@arctos>> select * from temp_ttlcp where tail_length>total_length;
      guid       | tail_length | total_length 
-----------------+-------------+--------------
 MVZ:Mamm:219547 |          69 |           16
 UCM:Mamm:16499  |          79 |            7
 MVZ:Mamm:240897 |          93 |           89
(3 rows)

```

**Comment by Jegelewicz** [comment]
Thanks @dustymc This is a perfect example of how my "quick and dirty" is just that! I made no attempt to include units or to see if there were two (or more) total or tail lengths for anything. Maybe fine for a quick review, but any real research needs more attention to the details.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/6111
