### ISSUE TITLE
Code Table Request - ectoparasite values to add to the Examined_Detected code table

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6260]
## Initial Request

_**Goal**: Add the ectoparasite examination and detected values to the Examined_Detected code table:

_**Proposed Values**: 
ectoparasite: diptera
ectoparasite: flea
ectoparasite: lice
ectoparasite: Acari
ectoparasite: mite
ectoparasite: tick

_**Proposed Definitions**: 

ectoparasite: diptera:  "Ectoparasitic Diptera, includes bat flies, bot flies and other hippoboscidae. Avoid using for dipteran larvae that are found on dead organisms, unless these were known to be feeding on the organism while it was alive (myiasis)."

ectoparasite: flea:   " The common name for the insect order Siphonaptera, small flightless insects that live as external parasites of mammals and birds.  https://en.wikipedia.org/wiki/Flea"

ectoparasite: louse  "Louse (pl: lice) is the common name for any member of the clade Phthiraptera, which contains nearly 5,000 species of wingless parasitic insects, including chewing and sucking lice.  https://en.wikipedia.org/wiki/Louse"

ectoparasite: Acari :   "Legacy subclass of mites and ticks, unspecified.  Use a more specific value (mite or tick) if known."

ectoparasite: mite:  "Small arachnids (eight-legged arthropods), many of which are ectoparasitic. Includes the orders Acariformes and the Parasitiformes, which were historically grouped together in the subclass Acari. https://en.wikipedia.org/wiki/Mite"

ectoparasite: tick: "Ticks (order Ixodida) are parasitic arachnids, formerly in the Acari, that are part of the mite superorder Parasitiformes.; https://en.wikipedia.org/wiki/Tick"

_**Context**: These values are being added the Examined_Detected code table to capture existing data in Arctos and to accommodate ongoing research which will be populating these attributes going forward. The current attributes "ectoparasite examination" and "ectoparasite detected" will be migrated to these new attributes.

_**Table**: https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_code_tables

_**Priority**: Normal to High. Needed for grant funded research within the next few months if possible.

_**Available for Public View**: Yes

_**Project**: Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184)._

_**Discussion**: 
@jldunnum @campmlc @acdoll @bryansmclean 

@ArctosDB/arctos-code-table-administrators 

## Approval

_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality)._

- [ ] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [ ] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection

_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation

_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

_Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel._

_Make changes as described above. Ensure the URL of this Issue is included in the definition._

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by dustymc** [comment]
I don't think group requests can receive sufficient review, and believe this should be resubmitted as multiple requests.

**Comment by Jegelewicz** [comment]
Closing this as the individual requests have been placed and handled
