### ISSUE TITLE
Code Table Request - Add Parasites to the Examined_Detected Code Table

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6262]
## Initial Request
Add the term "parasite" to the Examined_Detected code table to aid in the migration of legacy data.

_**Proposed Value**:  
parasite

_**Proposed Definition**: 
A parasite is an organism that benefits at the expense of another organism of a different species (the host). Use this term only when more specific information on the type of parasite is not available.

_**Context**: We are migrating "examined for parasites" "yes/no" and "parasites found yes/no" attributes to the new examined/detected/not detected system. This value is necessary to capture these legacy data.

_**Table**: 
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctexamined_detected

_**Priority**: High

_**Available for Public View**: Yes

_**Project**: Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184)._

_**Discussion**: Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary._

@jldunnum @msbparasites @acdoll @bryansmclean 
@ArctosDB/arctos-code-table-administrators 

## Approval

_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality)._

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection

_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation

_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

_Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel._

_Make changes as described above. Ensure the URL of this Issue is included in the definition._

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by dustymc** [comment]
Please make the requested value singular to follow the pattern of other values.

Please provide a FUNCTIONAL definition, as requested.

**Comment by Jegelewicz** [comment]
OK - so how will anyone wanting to find all "parasite" exams find them? They will need to know to search for all attributes beginning with `parasite`, `endoparasite`, and `ectoparasite`. Is everyone OK with that? OR should we have organized them as follows:

parasite
parasite: endo
parasite: endo: helminth
parasite: ecto:
parasite: ecto: Siphonaptera

?

**Comment by campmlc** [comment]
"parasite" is embedded in all the terms "ectoparasite" "endoparasite" and
"parasite". I don't agree with adding more complexity. We only need this
for legacy data, eg 20,000+ Rausch records.

**Comment by Jegelewicz** [comment]
Great - just making sure bases are covered!

**Comment by campmlc** [comment]
Approved and created 5-18-2023
