### ISSUE TITLE
Arctos Down - Old reporter down again

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#6264]
@dustymc Can you please reboot the server with the old reporter, it's not loading again.

Thanks!

**Comment by dustymc** [comment]
Reanimated.

**Comment by ccicero** [comment]
@atrox10 says it's down again, please restart @dustymc

**Comment by dustymc** [comment]
propped up with small sticks and bubblegum....

**Comment by Jegelewicz** [comment]
Get some duct tape and chicken wire!
