### ISSUE TITLE
Code Table Request - Add fungi: Coccidioides to the Examined_Detected Code Table

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6267]
Initial Request
Add the term "fungi: Coccidioides" to the Examined_Detected code table to aid in the migration of legacy data.

_Proposed Value:
fungi: Coccidioides

_Proposed Definition:
Coccidioides is a genus of dimorphic ascomycete fungi in the family Onygenaceae. Member species are the cause of coccidioidomycosis, also known as San Joaquin Valley fever, an infectious fungal disease largely confined to the Western Hemisphere and endemic in the Southwestern United States. https://en.wikipedia.org/wiki/Coccidioides

_Context: This is a new attribute value to capture current research results and pathogen studies using museum specimens. Data are available in publications referencing voucher specimens.

_Table:
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctexamined_detected

_Priority: High

_Available for Public View: Yes

Project: Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

Discussion: Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

@jldunnum 

https://github.com/orgs/ArctosDB/teams/arctos-code-table-administrators

## Approval

_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality)._

- [ ] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection

_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation

_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

_Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel._

_Make changes as described above. Ensure the URL of this Issue is included in the definition._

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by Jegelewicz** [comment]
The definition does not apply to the requested term. Do we actually need `fungi: Coccidioidess` or should the definition be revised?

Some data would be really useful to determine the appropriateness of the terms.

**Comment by campmlc** [comment]
From conversation with researcher in March:

<html>
<body>
<div class="gE iv gt" style="font-size: 0.875rem; padding: 20px 0px 0px; cursor: pointer; color: rgb(34, 34, 34); font-family: &quot;Google Sans&quot;, Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Paris Salazar - Hamm | Mar 31, 2023, 10:24 AM |   |  
-- | -- | -- | -- | --
Paris Salazar - Hamm <
to me, Jonathan, Teresa, Dusty | to me, Jonathan,, Teresa, Dusty

</div><div id=":5n7" style="color: rgb(34, 34, 34); font-family: &quot;Google Sans&quot;, Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="qQVYZb"></div><div class="utdU2e"></div><div class="lQs8Hd" jsaction="SN3rtf:rcuQ6b" jscontroller="i3Ohde"></div><div class="btm"></div></div><div class="" style="color: rgb(34, 34, 34); font-family: &quot;Google Sans&quot;, Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="aHl" style="margin-left: -38px;"></div><div id=":5mu" tabindex="-1"></div><div id=":5n5" class="ii gt adO" jslog="20277; u014N:xr6bB; 1:WyIjdGhyZWFkLWY6MTc2MTg1NzY5MzkwNDQ0NDM3OSIsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsW11d; 4:WyIjbXNnLWY6MTc2MTkwMTE1NDMzNjIxODkyNiIsbnVsbCxbXV0." style="direction: ltr; margin: 8px 0px 0px; padding: 0px; position: relative; font-size: 0.875rem;"><div id=":5n6" class="a3s aiL msg6322346133551169900" style="font: small / 1.5 Arial, Helvetica, sans-serif; overflow: hidden;"><div class="adM"></div><div dir="ltr"><div class="adM"></div><div style="font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);">Thank you all for the help! Mariel, I am providing some thoughts below, but I'd be happy to do a zoom chat if you need more information or explanation. </div><div style="font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);"><br></div><div style="font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);">I would defer to using attributed that say detection by organism rather than disease. For example, we have detections of Coccidioides, but we don't think the animal was diseased based on the mycobiome results that the reads were in low abundance and didn't disrupt the mycobiome. The fungal biology is different for each of these species and so it's hard in some cases to conclude disease state. I would also be careful with your above example. Bsal and Bd should be categorized as chytridiomycosis as they are chytrid fungi  (two different species), but snake fungal disease is an ascomycete and so it is not chytridiomycosis even though it's in a reptile host. </div><div style="font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);"><br></div><div style="font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);">I would say my samples would need both the indicators "fungi: Coccidioides" and "fungi: mycobiome" because of amplicon sequencing performed which was broader than a targeted PCR screening. All of my samples would be <span style="text-decoration: none; background-color: rgb(255, 255, 255); display: inline !important;">"fungi: mycobiome"<span> = TRUE and then there would be TRUE/FALSE for <span style="text-decoration: none; background-color: rgb(255, 255, 255); display: inline !important;">"fungi: Coccidioides".<span> Can these attributes also be connected with the tissue that was tested? I know of other groups who have variable testing results by tissue type.</span></span></span></span></div><div style="font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);"><br></div><div style="font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);">Methods: Tissues underwent a CTAB DNA extraction followed by PCR amplification of the ribosomal internal transcribed spacer (ITS) region. The ITS2 region was targeted for sequencing using 5.8SFUN and ITS4-FUN primers. DNA libraries were prepared with the Illumina MiSeq DNA library protocol for paired-end reads followed by sequencing on the MiSeq PE300. All raw reads were deposited in the NCBI Short Read Archive (SRA) under BioProject ID PRJNA769405.</div><div style="font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);"><br></div><div style="font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);">Please use this paper as the citation (doi: 10.3389/ffunb.2022.996574) as the one in your last email is the review. The link for github in the paper does take you to the correct repository even though I have edited the name to encompass more data. </div></div></div></div></div>
</body>
</html>

**Comment by Jegelewicz** [comment]
> Can these attributes also be connected with the tissue that was tested? I know of other groups who have variable testing results by tissue type.

UGH - this really makes me think these should be part attributes, but I guess we have crossed that bridge...

As for my [comment above](https://github.com/ArctosDB/arctos/issues/6267#issuecomment-1542291455) - I think there was just a misspelling in the request that you have fixed?

**Comment by campmlc** [comment]
Yes and yes. They should always have been part attributes, but some
collections didn't have the loans tracked to the part to be able to say
which part was tested, so this was a compromise. At MSB, we do have data at
the part and container level, so part attributes would have been ideal.

**Comment by Jegelewicz** [comment]
> some collections didn't have the loans tracked to the part to be able to say which part was tested,

That could be a great use for a part = [unknown](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#unknown)?

**Comment by campmlc** [comment]
I don't think changing directions to switch to part attributes from record attributes at this late stage in the game is a viable model. We've had multiple meetings, and this is what the community agreed upon. It was not my choice, but more importantly, it will work until we can build something better. I need these data fields populated to present to the parasitology meetings in July. @jldunnum needed these data 6 months ago for a time-constrained project. 

I support continuing to have pathology meetings. There was one yesterday, and no one showed, so that is why I have moved forward with these issues. We need them resolved as soon as possible.

**Comment by dustymc** [comment]
>no one showed

That is not true.

https://docs.google.com/document/d/1_67RpIhKLIR5BkaHW7eHngMghOMmmeZmexKGbxmwVBM/edit#heading=h.31drnsreahrc

**Comment by campmlc** [comment]
I joined the zoom meeting in the calendar invite and stayed on for 15
minutes with no one there. Was there a different zoom?

**Comment by campmlc** [comment]
Regardless, there is no record of the discussion in the chat and no
comments on the github issues other than mine or some "blocked" by another
issue, so I assume none of these were resolved during the meeting.

**Comment by Jegelewicz** [comment]
The only thing in chat were links to the agenda and the github project, so I didn't copy it. And yes, nothing was really resolved in the meeting.

> Attendees will review. We gave them a half hour to do so!

We discussed the not examined for request but as there were so few people in attendance, I just asked everyone to review the open issues (a lot were opened after the meeting!).

> I joined the zoom meeting in the calendar invite and stayed on for 15 minutes with no one there. Was there a different zoom?

I don't know what happened to the link, but the one in the calendar is correct and it is the same link I use for all of the zoom meetings. I'm sorry that something happened with the link and if you can figure out what it was, I am happy to fix whatever the problem is!

**Comment by campmlc** [comment]
Re-uping original request in priority. I have data from a researcher that needs to be added, and this needs to be used in a presentation.

**Comment by campmlc** [comment]
Nevermind - appears to have been added to table? Closing
