### ISSUE TITLE
Add Values to Customize Search and Results

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6270]
Please add the following values to the Customize Search and Results editing table:
Identifier:
IF: Idaho Frozen Tissue Collection 

Attributes:
Examined For
Detected
Not Detected 

Needed to create customized searches for MSB
Priority: High, needed to create profiles for grant funded project

**Comment by campmlc** [comment]
Please make this happen.

**Comment by mkoo** [comment]
I dont understand this request? Is this to create a preset search/ results? if so, please let us know what your saved search is called in your profile. @campmlc 
We can take it from there

**Comment by dustymc** [comment]
I believe this was a duplicate, please reopen with specifics if something's still needed.
