### ISSUE TITLE
Need Help with Arctos Error - Editing Agents

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#6286]
# Error Text
Upgrade required: error: [object Object]
![image](https://github.com/ArctosDB/arctos/assets/93737929/9bac1861-dcb7-46c0-8152-903b73dad3be)

# Where it happened
Arctos user vbecerril cannot edit agent records; he has the appropriate operator access and has been able to edit / create in the past. 

# Steps to get there
Trying to add information to an agent record and saving. He also was not able to create an agent record earlier today; the loading wheel kept spinning and nothing happened. I was able to create the agent record and add to it on my end.

# Problem
**Community response to describe the problem that caused the error**

# Solution
**Community response with directions for how to correct the problem**

**Comment by wellerjes** [comment]
Thank you!

**Comment by dustymc** [comment]
This should be patched, but please let me know if an insecure connection can still be established.

**Comment by wellerjes** [comment]
I tried removing https from mine and it automatically redirected to the correct url
