### ISSUE TITLE
Full clone fails to copy ID confidence

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#6287]
I just used the other ID -> clone this record -> clone full cataloged record and the clone lacks ID confidence (the original had ID confidence = high).

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.
high

**Comment by dustymc** [comment]
blocked by https://github.com/ArctosDB/arctos/issues/5331

**Comment by dustymc** [comment]
This is addressed by https://github.com/ArctosDB/arctos/issues/4829
