### ISSUE TITLE
Rebuild loanItemReview

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6289]
from #6288 

https://arctos.database.museum/loanItemReview.cfm needs to be rebuilt and Dusty has asked if anyone has changes to recommend.

The form Looks like this

![image](https://github.com/ArctosDB/arctos/assets/5725767/514db828-3d0f-4a49-8ce5-c7c51509a53f)
![image](https://github.com/ArctosDB/arctos/assets/5725767/02986ad4-82f1-41ba-816a-a171ee35a112)

**Comment by Jegelewicz** [comment]
Is anything [here](https://docs.google.com/document/d/1XCedmJwlKoGL1hnQRCDdoA_dnv-agJyXddNf-FBT7S8/edit#heading=h.fatws3xvnvbn) relevant?

**Comment by campmlc** [comment]
Rebuilt in what way?

**Comment by acdoll** [comment]
I'm pretty happy with what's included in the current setup. One question - what goes in those brackets next to the part name? Is it always 'part modifier' or do any of the other part attributes go in there?

**Comment by campmlc** [comment]
Agree with @acdoll . However, one change that would be super helpful is for Encumbrances: can we see the text of the encumbrance, and not just yes/ no? I need to see why an encumbrance exists, and not have to go look up each record to see what each is individually. Plus if the the encumbrance is " cute this NSF funding" the loan recipients need that in the loan agreement, so I need to flag those records with that info.

**Comment by dustymc** [comment]
> Part attribute summary is included with part name, enclosed in square brackets. 

Same as "string view" on guid pages.

**Comment by wellerjes** [comment]
Would it be possible to search for one guid within the loan, especially if it contains a lot of catalog records?

**Comment by campmlc** [comment]
Can there be a link to the encumbrance for each record? So for example the type is "restrict usage" and we see that in the encumbrance column. But that text is a hyperlink to the encumbrance for that record?
