### ISSUE TITLE
New Feature - Hoonah-Angoon_Census_Area

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6291]
> There area higher geography options for a bunch of other Alaska census area, we have a bunch of martins from Hoonah-Angoon, it'd be nice to have it as a higher geog option too. I made a shapefile for it from a file that had all of the census areas, is there anything else you need to request that it be added as a feature?
> 
> [Hoonah-Angoon_Census_Area.zip](https://github.com/ArctosDB/data-migration/files/11467770/Hoonah-Angoon_Census_Area.zip)

_Originally posted by @asemerdj in https://github.com/ArctosDB/data-migration/issues/1302#issuecomment-1546311061_

@dustymc @mkoo I need your guidance!

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/6058

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/6058
