### ISSUE TITLE
Tube barcode -> postions

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#6293]
@dustymc Could you please load this file of cryovial-barcodes into their freezer-box-positions? As you did in #3181, #3598 and #4134. 
I should have all the boxes loaded and positions created (if/when you get errors, know that I tried). This should be the last time I ask for this (I think). 
[MF2_cryovials-freezer_box_positions.csv](https://github.com/ArctosDB/arctos/files/11468291/MF2_cryovials-freezer_box_positions.csv)

**Comment by acdoll** [comment]
8 of 15806 = 0.05%; not _too_ bad. Those are fixed now:
[edit_MF2_cryovials-freezer_box_positions.csv](https://github.com/ArctosDB/arctos/files/11481153/edit_MF2_cryovials-freezer_box_positions.csv)

**Comment by dustymc** [comment]
> not too bad

Not at all!

Should be done.

**Comment by acdoll** [comment]
AWESOME! I am amazed they went through with only one error. I appreciate your help!
