### ISSUE TITLE
How to load data to 'Associated Species' field for 2856 existing catalog records?

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#6295]
I've got the attached data - a list of GUIDs and plant names. I'd like to load these plant names into the 'Associated Species' field for these 2856 catalog records. I assume I can't do this with a pre-existing tool? If I can, please tell me how. If not, can Dusty make this happen?

Thanks!
Derek
[plantdatawguids.csv](https://github.com/ArctosDB/arctos/files/11481090/plantdatawguids.csv)

**Comment by dustymc** [comment]
I'll get it.

**Comment by dustymc** [comment]
done

**Comment by DerekSikes** [comment]
Thanks! Sorry, I missed 114 records - attached. Could you load these as well (plant names into the "Associated Species" field for these catalog records-GUIDs?
[plantdatawguids2.csv](https://github.com/ArctosDB/arctos/files/11482869/plantdatawguids2.csv)

**Comment by DerekSikes** [comment]
Oops - my collaborator had sent me 2 data sheets (one with old plant names and one with new improved names - seems I loaded the old ones!)

The attached have the correct names - what is the best way to fix?
- undo the recent load & load this instead (my preference)
- just load the attached without deleting the prior (but this would result in many cases of the same plant name appearing twice in this field, which is undesirable - can these be loaded only if they differ from what is in that field now?)
[plantdatawguids3.csv](https://github.com/ArctosDB/arctos/files/11483234/plantdatawguids3.csv)

**Comment by dustymc** [comment]
Let's try this. In the attached CSV,

* ASP is your data from https://github.com/ArctosDB/arctos/issues/6295#issuecomment-1548849452
* EASP is current associated_species, however it got there

Do whatever you want with this file, then I'll REPLACE associated species with whatever you tell me to.

I'm up for anything else, but I think that's probably what's least likely to confuse someone at this point.


[temp_asp.csv.zip](https://github.com/ArctosDB/arctos/files/11488603/temp_asp.csv.zip)

**Comment by DerekSikes** [comment]
Excellent. Please replace associated species for those catalog records with the ASP data. I've confirmed ASP is good & EASP is bad. Thanks!

**Comment by dustymc** [comment]
Done

**Comment by DerekSikes** [comment]
Thanks!
