### ISSUE TITLE
USGS Anchorage Can't Access Arctos.database.museum from Arctos.db.org

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6296]
<html>
<body>

Pierson, Barbara J' via Arctos Working Group Officers <arctos-working-group-officers@googlegroups.com> | Mon, May 15, 2023 at 1:58 PM
-- | --
Reply-To: "Pierson, Barbara J" <bpierson@usgs.gov>To: "mkoo@berkeley.edu" <mkoo@berkeley.edu>Cc: "arctos-working-group-officers@googlegroups.com" <arctos-working-group-officers@googlegroups.com>
Hi Michelle,I'm getting an error while trying to search collections from the ARCTOS website this morning.I'm getting this error:when I click on "ARCTOS collections" from this window:Also, when I click on the report problems as soon as possible, it's trying to make me log in via Google and my federal e-email address is rejected preventing me from contacting via the web.  (Or requires me to log in via Git Hub)Others in our building are getting the same error, so I don't think it's our USGS firewalls for once!  Thanks,BobbiB. PiersonGeneticistU.S. Geological SurveyAlaska Science Center4210 University DriveAnchorage, AK 99508United Statese-mail:  bpierson@usgs.govOffice Phone: (907) 786-7107Mobile :  (907) 782-8189Fax: (907) 786-7020--You received this message because you are subscribed to the Google Groups "Arctos Working Group Officers" group.To unsubscribe from this group and stop receiving emails from it, send an email to arctos-working-group-officers+unsubscribe@googlegroups.com.To view this discussion on the web visit https://groups.google.com/d/msgid/arctos-working-group-officers/SJ0PR09MB8933A70A1BE0CA8076F60D59A6789%40SJ0PR09MB8933.namprd09.prod.outlook.com. | Hi Michelle,I'm getting an error while trying to search collections from the ARCTOS website this morning.I'm getting this error:when I click on "ARCTOS collections" from this window:Also, when I click on the report problems as soon as possible, it's trying to make me log in via Google and my federal e-email address is rejected preventing me from contacting via the web.  (Or requires me to log in via Git Hub)Others in our building are getting the same error, so I don't think it's our USGS firewalls for once!  Thanks,BobbiB. PiersonGeneticistU.S. Geological SurveyAlaska Science Center4210 University DriveAnchorage, AK 99508United Statese-mail:  bpierson@usgs.govOffice Phone: (907) 786-7107Mobile :  (907) 782-8189Fax: (907) 786-7020--You received this message because you are subscribed to the Google Groups "Arctos Working Group Officers" group.To unsubscribe from this group and stop receiving emails from it, send an email to arctos-working-group-officers+unsubscribe@googlegroups.com.To view this discussion on the web visit https://groups.google.com/d/msgid/arctos-working-group-officers/SJ0PR09MB8933A70A1BE0CA8076F60D59A6789%40SJ0PR09MB8933.namprd09.prod.outlook.com.
Hi Michelle,I'm getting an error while trying to search collections from the ARCTOS website this morning.I'm getting this error:when I click on "ARCTOS collections" from this window:Also, when I click on the report problems as soon as possible, it's trying to make me log in via Google and my federal e-email address is rejected preventing me from contacting via the web.  (Or requires me to log in via Git Hub)Others in our building are getting the same error, so I don't think it's our USGS firewalls for once!  Thanks,BobbiB. PiersonGeneticistU.S. Geological SurveyAlaska Science Center4210 University DriveAnchorage, AK 99508United Statese-mail:  bpierson@usgs.govOffice Phone: (907) 786-7107Mobile :  (907) 782-8189Fax: (907) 786-7020--You received this message because you are subscribed to the Google Groups "Arctos Working Group Officers" group.To unsubscribe from this group and stop receiving emails from it, send an email to arctos-working-group-officers+unsubscribe@googlegroups.com.To view this discussion on the web visit https://groups.google.com/d/msgid/arctos-working-group-officers/SJ0PR09MB8933A70A1BE0CA8076F60D59A6789%40SJ0PR09MB8933.namprd09.prod.outlook.com.

</body>
</html>
Pierson, Barbara J' via Arctos Working Group Officers <arctos-working-group-officers@googlegroups.com>	Mon, May 15, 2023 at 1:58 PM
Reply-To: "Pierson, Barbara J" <bpierson@usgs.gov>
To: "mkoo@berkeley.edu" <mkoo@berkeley.edu>
Cc: "arctos-working-group-officers@googlegroups.com" <arctos-working-group-officers@googlegroups.com>
Hi Michelle,

I'm getting an error while trying to search collections from the ARCTOS website this morning.

I'm getting this error:

when I click on "ARCTOS collections" from this window:

Also, when I click on the report problems as soon as possible, it's trying to make me log in via Google and my federal e-email address is rejected preventing me from contacting via the web.  (Or requires me to log in via Git Hub)

Others in our building are getting the same error, so I don't think it's our USGS firewalls for once!  

Thanks,
Bobbi

B. Pierson
Geneticist
U.S. Geological Survey
Alaska Science Center
[4210 University Drive](https://www.google.com/maps/search/4210+University+Drive+%0D%0A+%0D%0A+%0D%0A+Anchorage+,+AK+99508+%0D%0A+United+States?entry=gmail&source=g)
[Anchorage](https://www.google.com/maps/search/4210+University+Drive+%0D%0A+%0D%0A+%0D%0A+Anchorage+,+AK+99508+%0D%0A+United+States?entry=gmail&source=g), [AK](https://www.google.com/maps/search/4210+University+Drive+%0D%0A+%0D%0A+%0D%0A+Anchorage+,+AK+99508+%0D%0A+United+States?entry=gmail&source=g) [99508](https://www.google.com/maps/search/4210+University+Drive+%0D%0A+%0D%0A+%0D%0A+Anchorage+,+AK+99508+%0D%0A+United+States?entry=gmail&source=g)
[United States](https://www.google.com/maps/search/4210+University+Drive+%0D%0A+%0D%0A+%0D%0A+Anchorage+,+AK+99508+%0D%0A+United+States?entry=gmail&source=g)

e-mail:  [bpierson@usgs.gov](mailto:bpierson@usgs.gov)

--
You received this message because you are subscribed to the Google Groups "Arctos Working Group Officers" group.
To unsubscribe from this group and stop receiving emails from it, send an email to [arctos-working-group-officers+unsubscribe@googlegroups.com](mailto:arctos-working-group-officers+unsubscribe@googlegroups.com).
To view this discussion on the web visit [https://groups.google.com/d/msgid/arctos-working-group-officers/SJ0PR09MB8933A70A1BE0CA8076F60D59A6789%40SJ0PR09MB8933.namprd09.prod.outlook.com](https://groups.google.com/d/msgid/arctos-working-group-officers/SJ0PR09MB8933A70A1BE0CA8076F60D59A6789%40SJ0PR09MB8933.namprd09.prod.outlook.com?utm_medium=email&utm_source=footer).
Mariel Campbell 	Mon, May 15, 2023 at 2:50 PM
To: "Pierson, Barbara J" <bpierson@usgs.gov>
Cc: "arctos-working-group-officers@googlegroups.com" <arctos-working-group-officers@googlegroups.com>
Hi Barbara,
Michelle is out of town, but I can try to help with this. I am not seeing a problem from my end - I'm able to access the [arctos.database.museum](http://arctos.database.museum/) site as well as the link from [arctosdb.org](http://arctosdb.org/). I'll file an issue in Github to let our programmer know. Can you provide a few more details on whether this is happening on more than one computer, what browser you are using, and if anything is different from when you previously accessed the database?
Thanks, and sorry you are having difficulty. 
Mariel Campbell
Arctos Working Group
Museum of Southwestern Biology

**Comment by campmlc** [comment]
More info - see below:

Hi Mariel,

I'm using an Edge browser window, have had multiple co-workers in the same building and another building on different USGS servers try and all get the error on the search (.museum) page.  I just tried with Chrome and got the same error.  By my personal, mobile phone just now, it let me onto the search screen.  But, my USGS desktop and laptop still gave the error even when on secure connect VPN app.

I work for USGS (federal/DOI), so numerous system updates have probably occurred since I last queried ARCTOS about a month ago.

I'll tap one of our IT folks here, but this error is a new one to me where it seems to be indicating I'm being blocked from your side when it says "It looks like [arctos.database.museum](http://arctos.database.museum/) closed the connection"

Let me know if you have any ideas.  I'll work it from my side with our IT as well.

Thanks,
Bobbi

**Comment by ewommack** [comment]
![image](https://github.com/ArctosDB/arctos/assets/18562884/07c21fa0-20f3-4ca3-b1f7-919a85b8ce08)

I've asked them for their IP.

**Comment by ewommack** [comment]
@dustymc 

Ok here is what we've gotten from USGS. Any help on figuring out why they can't get into Arctos from their official computers on the network?


Here is our complete ranges. It is looking like maybe your network does not like our man-in-the-middle device used for traffic visibility.

[130.118.176.0/21](http://130.118.176.0/21)
[130.118.184.0/23](http://130.118.184.0/23)
[159.189.224.0/22](http://159.189.224.0/22)
[159.189.228.0/23](http://159.189.228.0/23)
[10.208.100.0/22](http://10.208.100.0/22)

V/R

 
Will Newnham  


Network Administrator

USGS - Alaska Science Center
ASC IT Office
Email: [wnewnham@usgs.gov](mailto:wnewnham@usgs.gov)

Phone: (907) 786-7121
Cell: (907) 917-0170

**Comment by dustymc** [comment]
I can confirm that none of those are blocked in any way by Arctos.

I will ping TACC to be sure, but I don't think they'd be blocked from there.

**Comment by ewommack** [comment]
And response from USGS:

Like I said, I think it's failing at the handshake. 

V/R

Will Newnham
Network Administrator

USGS - Alaska Science Center
ASC IT Office
Email: wnewnham@usgs.gov

Phone: (907) 786-7121
Cell:(907) 917-0170

**Comment by ewommack** [comment]
Possibly related to: https://github.com/ArctosDB/arctos/issues/6305. Or same problem.

**Comment by ewommack** [comment]
Info from @dustymc from #6305 is:

> Doesn't seem like anything Arctos or TACC might have done, and none of us can replicate. Chris guesses it could possibly be related to the recent DNS changes (so try restarting everything).

**Comment by ewommack** [comment]
Latest response from USGS:

> The dns looks good, it's resolving properly. I'm adding someone who may be able to look at the A10 device and see if it's passing the traffic. 
> 
> Jerry, can you assist with this, or, if I'm in the wrong lane, point me in the right direction?
> 
> V/R
> 
> Will Newnham
> Network Administrator
> 
> USGS - Alaska Science Center
> ASC IT Office
> Email: wnewnham@usgs.gov
> 
> Phone: (907) 786-7121
> Cell:(907) 917-0170

**Comment by mlbowser** [comment]
I am also unable to access Arctos from DOI/USFWS in Soldotna.

**Comment by dustymc** [comment]
@mlbowser can you get to https://www.tacc.utexas.edu/? 

Or test, https://arctos-test.tacc.utexas.edu?

I don't think there's any way our guesses could still be in play, but I don't know what else this could be - something about your network, perhaps??

If possible you might put your IT folks in touch with Chris - https://www.tacc.utexas.edu/research/tacc-research/ or ``ctjordan @ tacc . utexas . edu``

**Comment by mlbowser** [comment]
Both of those URIs work for me, <but not https://arctos.database.museum/>.

**Comment by wrstAlaskan** [comment]
The test website works for me as well (I submitted issue #6305, DOI/NPS). I forwarded the issue to our IT department and they sent it to our regional office (https://arctos.database.museum/ still does not open on work computer) but no update yet. Thanks for setting up the test website, very helpful!

**Comment by ewommack** [comment]
@wrstAlaskan - the test website is where we test and try out new ideas. It definitely has Arctos data, but it may not have the most up to date data. You may also see new functions and tools as we try them out before implementation. Something to keep in mind as you use it.

It is seems odd that you can access parts of Arctos but not our main page. @dustymc said he cannot replicate the problem, so any help your IT department can provide would be greatly appreciated.
