### ISSUE TITLE
move Associated Species

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6297]
**Is your feature request related to a problem? Please describe.**

Associated Species is in table coll_object_remark for some reason

**Describe what you're trying to accomplish** 

Move a legacy field to somewhere more appropriate

**Describe the solution you'd like**

1. Find a better home for these data
2. Move existing data there
3. Do whatever's necessary in the UI

If these data are meant to be event-things (seems like they should??) then a new event attribute might be most appropriate. If the current functionality (all associated species across the life of the item??) is desired then a record attribute might be most appropriate. I'm up for anything other than the current arrangement!

**Describe alternatives you've considered**

There are none - the data are clearly misplaced, the table itself should not survive https://github.com/ArctosDB/arctos/issues/4707

**Additional context**

**Priority**

Not high at the moment, but I'm calling it wildfire as I think this has been overlooked at least once. At some point the table will go away, I'd REALLY like to have a plan before then.

**Comment by Jegelewicz** [comment]
These seem like they should be an event attribute?

**Comment by dustymc** [comment]
Reprioritizing this for https://github.com/ArctosDB/arctos/issues/4707

HELP!

Data:

[temp_asssp.csv.zip](https://github.com/ArctosDB/arctos/files/12477138/temp_asssp.csv.zip)


Summary:

```


 guid_prefix  | count 
--------------+-------
 ALMNH:Ento   |     1
 ALMNH:Inv    |    20
 ALMNH:Paleo  |     2
 APSU:Fish    |    24
 APSU:Herp    |    29
 BYU:Teach    |     1
 CHAS:Bird    |     2
 CHAS:Herb    |    14
 CHAS:Inv     |    10
 CHAS:Teach   |    21
 CRCM:Bird    |     2
 CSULB:Bird   |    10
 DGR:Bird     |     1
 DMNS:Bird    |     7
 DMNS:Mamm    |    54
 KNWR:Ento    |    23
 KNWR:Herb    |     2
 MSB:Bird     |   402
 MSB:Herp     |     3
 MSB:Mamm     |   588
 MSB:Para     |    14
 MVZ:Bird     |     1
 MVZ:Herp     |     2
 MVZ:Mamm     |     3
 MVZObs:Bird  |     2
 NMMNH:Ento   |     1
 NMMNH:Geol   |   508
 NMMNH:Paleo  |     4
 OWU:Bird     |     1
 OWU:Inv      |     2
 OWU:Para     |     1
 UAMb:Herb    |    46
 UAM:Ento     |  3832
 UAM:ES       |     1
 UAM:Fish     |     4
 UAM:Herb     |  4570
 UAM:Mamm     |     3
 UAMObs:Ento  |    11
 UAMObs:Fish  |     1
 UCM:Egg      |     1
 UCM:Mamm     |     2
 UCM:Obs      |     1
 UMZM:Bird    |     1
 UNCG:Para    |   197
 UNM:Geol     |  1056
 UNM:Paleo    |    46
 UNR:Herp     |    14
 UTEP:Ento    |   733
 UTEP:Herb    |  2446
 UTEP:Herp    |   101
 UTEP:HerpOS  |     1
 UTEP:Inv     |   417
 UTEPObs:Ento |     2
 UTEPObs:Herp |    19
 UWZM:Bird    |    12
 UWZM:Mamm    |    31

```

Users:


 @ebraker
 @bryansmclean
 @ehalverson26
 @Nicole-Ridgwell-NMMNHS
 @mkoo
 @campmlc
 @ccicero
 @camwebb/
 @amgunderson
 @atrox10
 @DerekSikes
 @mvzhuang
 @cjconroy
 @jtgiermakowski
 @wellerjes
 @gradyjt
 @AdrienneRaniszewski
 @aklompma
 @acdoll
 @jldunnum
 @jrdemboski
 @msbparasites
 @jessicatir
 @StefanieBond
 @catherpes
 @lin-fred
 @adhornsby
 @Jegelewicz
 @kmkocot
 @droberts49

**Comment by dustymc** [comment]
>What do we need to do?

Find a place for the data, make sure at least the heavy users are aware and onboard.

**Comment by Jegelewicz** [comment]
I suggested event attribute, which might require a bit of work if any of the records have more than one event...

**Comment by DerekSikes** [comment]
Of course, associated species could benefit from linking to actual species names in the taxonomy table... currently it's unstructured text that likely contains myriad typos and names spelled many ways (and a mix of common and scientific names).

**Comment by dustymc** [comment]
> linking to actual species

Yes, and if this lands somewhere with a definition that should be made clear. In general:

* some free-text thing is super-easy (and infinitely flexible) but low confidence and will get more and more cryptic as time goes on. (We have actual experience here, a bunch of common names in Rausch's  data from the ~60s were near-impossible to disambiguate.)
* a relationship to an observation is much more stable, but still no way to know how reliable
* a relationship to something with material is all sciencey

**Comment by dustymc** [comment]
AWG likes record attribute.

**Comment by campmlc** [comment]
I support making this an event attribute.  At least that way there would be associated metadata. Making related observation records is not feasible in many situations, e.g. a bird collection could only catalog associated bird taxa as observational records, not insects or plants, even if they could incorporate multiple related bulkloads as part of their workflow.

**Comment by Jegelewicz** [comment]
@campmlc at the AWG meeting last week we came to agreement to

> For now move to catalog record attribute to be consistent with current treatment as “part of the catalog record” vs. “part of the event”

**Comment by campmlc** [comment]
Ok, that works too! Just as long as it has a place to go with metadata and this issue can be resolved.

**Comment by Jegelewicz** [comment]
@dustymc I think this is good to go BUT maybe we need to warn everyone because this will change data entry?

**Comment by dustymc** [comment]
Warn away, please! I intend to do this with https://github.com/ArctosDB/arctos/issues/4707, that could start as early as next week. (And might take a week, but 2 is probably more realistic.)

**Comment by DerekSikes** [comment]
So... does this mean we won't have this field as a column in the catalog results list to download the data as we do now? That would be unfortunate.

**Comment by dustymc** [comment]
> won't have this field as a column in the catalog results list to download 

Na, ``associated_species`` is already a FLAT column, I can just map the attribute to that - https://github.com/ArctosDB/arctos/issues/6111

**Comment by DerekSikes** [comment]
cool

**Comment by dustymc** [comment]
Here are the bulkloader records with this data:


[temp_bulkloader_with_associated_species.zip](https://github.com/ArctosDB/arctos/files/12835667/temp_bulkloader_with_associated_species.zip)


They should all be happily transferred to attribute 30, please confirm.
