### ISSUE TITLE
Feature Request - match incoming localities to existing Arctos localities with coordinates (gazetteer)

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6300]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

See https://github.com/ArctosDB/data-migration/issues/1303

**Describe what you're trying to accomplish** 
An clear and concise overview of the goals; why are you asking for this?

We are looking to make use of exiting georeferenced localities when possible, rather than creating effective duplicates that are just missing coordinates. See https://github.com/ArctosDB/data-migration/issues/1303#issuecomment-1546262123 for a csv of the localities in question.

**Describe the solution you'd like**
How might we accomplish your goals?

A matching tool? Lookup the localities we have and match them to any exiting in Arctos. Maybe we start with exact matches, then look for near matches?

**Describe alternatives you've considered**

Just load localities as they are and georeference them later.

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by dustymc** [comment]
Try https://github.com/VertNet/bels

There's a service, it (more or less, via DWC) uses Arctos data, I think it'll take spreadsheet-ish input, it might make this easy-peasy.

**Comment by Jegelewicz** [comment]
It is this - https://localityservice.uc.r.appspot.com/

@asemerdj can you add higher geography to your file? I think it will provide the service more information to get better matches.

**Comment by dustymc** [comment]
done?
