### ISSUE TITLE
Feature Request - display_name (taxonomy / classifications)

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6302]
**Is your feature request related to a problem? Please describe.**

Arctos has generated display_name for some time, and it's used in some arbitrary places. I think we have now grown to the point where that makes little sense for bio collections, and none at all for others.

**Describe what you're trying to accomplish** 

Stop making unpredictable data.

**Describe the solution you'd like**

Turn off display_name generator

**Describe alternatives you've considered**

1. Leave the generator on, somehow filter or ???? 
2. Make sure zero-length results are somehow handled

That all sounds a little magical at the moment, if there's some compelling reason to keep this thing around I will need very specific (and technically plausible) instructions regarding how that might be accomplished.

**Additional context**

https://github.com/ArctosDB/arctos/issues/6299

**Priority**

I'm going to disable the automation now, it's just making messes. If this does need resurrection we can discuss priority then.

**Comment by dustymc** [comment]
Related: https://github.com/ArctosDB/arctos/issues/5794 - generated display_name is used (cryptically, and often in a horribly mangled fashion for all the reasons above) as flat component "FORMATTED_SCIENTIFIC_NAME." 

The same scripts also generate nonhierarchical classification term 'scientific name,' which I believe exists to support search. Propose that also be dropped, and search expanded to consider taxon_name.scientific_name as necessary.

**Comment by dustymc** [comment]
https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxon_term#scientific_name and https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxon_term#display_name will likely need adjusted in some way before this is completed.

**Comment by Jegelewicz** [comment]
See also - https://github.com/ArctosDB/arctos/issues/3609

Author text is important and the full name (which includes the author text) is expected in a lot of cases. It is unfortunate that WoRMS (via Arctos) does not include a full name like the one that appears on a taxon page in WoRMS

![image](https://github.com/ArctosDB/arctos/assets/5725767/1dc64a6a-4ab5-4347-9bf7-6ed56ac5512d)

the difference between WoRMS use of "authority" and Arctos use of "author_text" and who knows what others are using, makes building a Linnean "display_name" a chore.

We could consciously add "display_name" in non-classification terms and use that on the catalog record pages, but it will take work, and it will not work for anyone using WoRMS (via Arctos). I don't really have answers, but I think just ignoring the author/authority isn't very "research grade"?

@sharpphyl @DerekSikes

**Comment by dustymc** [comment]
>building a Linnean "display_name" a chore.

For Worms, as it's used by Arctos, where I can pretend that I somehow know everything is ICZN-ish: Yea, that sounds about right, a chore. I could do it, it would take some effort and my results probably wouldn't be very defensible, but if anything that's probably better than I've been doing in the big legacy classifications since we stopped requiring nomenclatural_code, and nobody seems to much notice whatever messes I make in there.


For anything a little further from our core origins or for anything that comes through a less-specialized webservice (which probably isn't very sustainable anyway, we really need to figure out how to use globalnames), it's probably closer to 'magic.' Some marine algae collection also wanting to use WoRMs would violate all of my assumptions regarding Codes (and therefore proper formatting, which is the ONLY purpose this term serves), for an easy and realistic example.

>ignoring

By whom? "Using what I'm given" or "pretending that I know more than our sources of taxonomy" look like the options from here. This looks like a curatorial job - and one which an be entirely ignored, or embraced to whatever extent seems most useful. Arctos can facilitate managing taxonomy, Arctos can facilitate letting some external source or service manage taxonomy, asking Arctos itself to manage taxonomy does not seem realistic to me (and I don't see how else this could be viewed).

>expected

One possibility that comes up from time to time might be to (somehow) help build author-bearing identifications, rather than trying to magic it out of the aether (what display_name tries to do) later. If this is expected and important and disambiguating and all the other stuff that comes up from time to time, then it's surely also something that Curators want/need to assert, not some secondary thing for the scripts to deal with! (And if my scripts can deal with it then so can anyone elses, so again I'm seeing conflicting information here.)

**Comment by DerekSikes** [comment]
I am strongly opposed to the loss of display name (unless it's replaced by something better that includes taxon name+author).

**Comment by dustymc** [comment]
@DerekSikes I'm not quite sure how to respond to that. I can defensibly keep doing what I'm doing for classifications which contain single understandable assertions of nomenclatural_code and author_text. I'm certain that all local classifications which have those data also have a display_name generated. There will be no loss in current data. 

I also can't keep ignoring the necessities and generating nonsense for minerals. 

I'm up for anything which can be supported by some data to which I have access.

**Comment by Jegelewicz** [comment]
I'm not a taxonomist, but what I see in the world is that the thing we call `Clangula hyemalis`, a decent size chunk of the world calls `Clangula hyemalis (Linnaeus, 1758)`

https://www.gbif.org/species/2498273
https://www.catalogueoflife.org/data/taxon/5YVVD
https://www.marinespecies.org/aphia.php?p=taxdetails&id=137071

I have tried and failed to figure out why there are two ways of writing this name. I only know that for some names the part we leave off is important - see https://github.com/ArctosDB/arctos/issues/4794#issue-1288870606.

This topic has come up over and over since I have been using Arctos and we have never reached a satisfactory conclusion - otherwise it wouldn't come up! Our answer is generally "fire up a new classification source", but nobody has the time or energy it seems. Now, we do not have a standard way to say "this is the author of this taxon name" and even when we did, it was not used consistently. When we have an external source that is clearly making use of the author name, like WoRMS, we can't use it in the same way because we would have to build the name + authority using different terms for every different external source. 

What is the rest of the world doing? We cannot be the only data managers dealing with this issue.

**Comment by Jegelewicz** [comment]
I just did this in test

https://arctos-test.tacc.utexas.edu/name/Clangula%20hyemalis#Arctos

![image](https://github.com/ArctosDB/arctos/assets/5725767/b8224be9-df4c-48bd-ab67-b9a262d2668b)

results on the catalog record

![image](https://github.com/ArctosDB/arctos/assets/5725767/3dd02a3d-5042-4be6-aa3d-f576e4be4a30)

Call it display name or whatever you want, put it after the final rank in the classification

It works, but is it workable?

**Comment by dustymc** [comment]
>What is the rest of the world doing?

Conflating identifications and taxonomy and classifications while not managing busses and holotypes in the same system.

>did this in test

That's all I'm suggesting. Either supply whatever you want to see or tell me how I can magick it, because we've clearly outgrown what I've been doing. (And if you'd have called that 'display_name' and left it out of the hierarchy then it'd get some special handling.)

**Comment by Jegelewicz** [comment]
But this CANNOT be used for WoRMS (via Arctos) and that is a drag.

**Comment by dustymc** [comment]
Well yea, if you want to let someone else manage your taxonomy then you're stuck with whatever they're doing.

**Comment by campmlc** [comment]
I like this. Can it be shared with GBIF?

**Comment by sharpphyl** [comment]
> But this CANNOT be used for WoRMS (via Arctos) and that is a drag.

But WoRMS has the concatenated taxon name and authority.  Is there a way to use it or create it?  We miss not having the author on taxonomic display in the catalog record.

**Comment by dustymc** [comment]
>on taxonomic display in the catalog record

EVERYTHING is now in the record, it's just folded up so it doesn't take up the whole page. 

<img width="617" alt="Screenshot 2023-11-09 at 07 09 40" src="https://github.com/ArctosDB/arctos/assets/5720791/6f4fbac7-4561-4f0d-bcc6-51c50ab6dd86">

I suppose I don't entirely care if it takes up the whole page, but do remember that there are records with dozens of identifications (and potentially dozens of equally-valid identifications: I don't think there's any justified hiding behind particular examples of current data). 

https://github.com/ArctosDB/arctos/issues/6685 is another request to do something in these data (and some other stuff, maybe). This conversation seems to have become something other than what it started as. This topic really needs some sort of focus group. I've already got the data cached (there's an Issue somewhere...), come up with some technically viable and scalable recipe and I can probably make it happen in the UI.

And it would still be useful to somehow address the lack of display_name generation.

**Comment by sharpphyl** [comment]
Thanks for your reply.  You're right that the data is just there - one click away.  We just got used to seeing the authority along with the species.  We're fine with the way it's working now.  Just a touch of nostalgia.

**Comment by Jegelewicz** [comment]
Closing - I think we have solutions.

**Comment by dustymc** [comment]
This isn't closable, I still need to clean up (or ??) - I'll assume the consensus is that I can clean up the (broken) generators?

**Comment by Jegelewicz** [comment]
Yes, I think that is the consensus.

**Comment by DerekSikes** [comment]
I was just showing how to prepare taxon labels and found a bunch of records that didn't have names despite the arctos taxonomy being complete - is this issue going to solve that? These were records I changed their IDs in October and had made new records in the taxonomy file for those names. They appear in the record in Arctos but when I download the data to make labels they don't.

**Comment by dustymc** [comment]
Example/details/??

**Comment by DerekSikes** [comment]
https://arctos.database.museum/guid/KWP:Ento:12289
https://arctos.database.museum/name/Boloria%20myrina#Arctos

but arctos reporter UAM_Ento_CSV

SCI_NAME_WITH_AUTH is empty

[uam_ento(11).csv](https://github.com/ArctosDB/arctos/files/13313188/uam_ento.11.csv)

see attached

**Comment by dustymc** [comment]
Thanks. I'm mapping ``display_name`` to ``formatted_scientific_name`` which you're aliasing as ``SCI_NAME_WITH_AUTH`` in https://arctos.database.museum/Reports/reporter.cfm?action=edit&report_id=50. There's no ``display_name`` in https://arctos.database.museum/name/Boloria%20myrina#Arctos, so the behavior is as expected.

I'm up for something different, just let me know what might work for you and I'll let you know if it seems workable from here.

**Comment by DerekSikes** [comment]
why is there no display name in https://arctos.database.museum/name/Boloria%20myrina#Arctos

that is the problem. Users can't make display name anymore (or edit them) so Arctos needs to make them for all names automatically and has failed to do so. Can that be fixed?

**Comment by dustymc** [comment]
>Users can't make display name anymore (or edit them) 

That's easily solvable, I will investigate.

>Arctos needs to make them 

PLEASE see above.

**Comment by DerekSikes** [comment]
Ah, yes. So you'll return the ability of users to make and edit display name?

**Comment by dustymc** [comment]
> return the ability of users to make and edit display name?

Yep, I can do that (and I can confirm that there are some filters), I can map something else, probably lots of things I can't think of, I just can't reliably make predictable data from completely uncontrolled source data.

**Comment by DerekSikes** [comment]
So.. what's the process now to make display names?

**Comment by dustymc** [comment]
They're just terms, manage them with everything else. The expectation is something like https://arctos.database.museum/editTaxonomy.cfm?action=editClassification&TAXON_NAME_ID=10098389&classification_id=10098389

**Comment by DerekSikes** [comment]
So... just to be clear. When making a new taxon name we have to remember to fill this field out and add the html to it? Nothing is done automatically to complete this field?

**Comment by DerekSikes** [comment]
Can you find taxonomy records that I made after you disabled the auto-generated display name so I can manually add them? Thanks.

**Comment by DerekSikes** [comment]
@dustymc  - couple final items to this issue above

**Comment by dustymc** [comment]
Yes, no automation, if you want to use the data then you need to provide them.

I was going to give you everything but it's too big - about 60MB if you've got a way to catch that, otherwise here are records you created.

[temp_dn_dss.csv.zip](https://github.com/ArctosDB/arctos/files/13369752/temp_dn_dss.csv.zip)

**Comment by DerekSikes** [comment]
thanks!
