### ISSUE TITLE
Borrows Form MIA?

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#6303]
The borrow form seems to be missing and it doesn't seem to be an issue with my permissions:

![image](https://github.com/ArctosDB/arctos/assets/11336485/8c767ee6-50bf-48be-922d-717eadb7e65a)

I did a search on previous GitHub issues but may have missed it so sorry if you've addressed this problem already....

**Comment by dustymc** [comment]
Borrows are included in "Accession & Loan: Search"

https://github.com/ArctosDB/arctos/issues/5515#issuecomment-1399529004

https://github.com/ArctosDB/arctos/issues/5742

and I think a few more....

**Comment by ebraker** [comment]
Found it! https://arctos.database.museum/borrow.cfm?action=new

Can we add this to the directory?

Suggested title update: Accessions, Borrows, Loans, Permits
Suggested new value: Borrow: Create
Suggested new value: Borrow: Search OR Accession, Borrow, Loan: Search

![image](https://github.com/ArctosDB/arctos/assets/11336485/53eaa006-9827-4fc3-a8da-17859e707c1e)
