### ISSUE TITLE
Code Table Request - hind foot length

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6308]
## Initial Request

_**Goal**: Describe what you're trying to accomplish. This is the only necessary step to start this process. The Committee is available to assist with all other steps. Please clearly indicate any uncertainty or desired guidance if you proceed beyond this step._

On behalf of @jldunnum @campmlc and the RANGES team, and in preparation for https://github.com/ArctosDB/arctos/issues/6111:

* hind foot without claw [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#hind_foot_without_claw)
* hind foot with claw [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#hind_foot_with_claw)

into one new 'hind foot ' attribute

_**Proposed Value**: Proposed new value. This should be clear and compatible with similar values in the relevant table and across Arctos._

hind foot length

_**Proposed Definition**: Clear, complete, non-collection-type-specific **functional** definition of the value. Avoid discipline-specific terminology if possible, include parenthetically if unavoidable._

Length of the hind foot.

_**Attribute data type** If the request is for an attribute, what values will be allowed?
free-text, categorical, or number+units depending upon the attribute (TBA)_

number+units

_**Attribute units** If numberical values should be accompanied by units, provide a link to the appropriate units table._

ctlength_units

_**Context**: Describe why this new value is necessary and existing values are not._

We have method embedded in a term (and much of it may be guesses).

_**Table**: Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table or value. This may involve multiple tables and will control datatype for Attributes. OtherID requests require BaseURL (and example) or explanation. Please ask for assistance if unsure._

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type

_**Collection type**: Some code tables contain collection-type-specific values. ``collection_cde`` may be found from https://arctos.database.museum/home.cfm_

carry over from existing

_**Priority**: Please describe the urgency and/or choose a priority-label to the right. You should expect a response within two working days, and may utilize [Arctos Contacts](https://arctosdb.org/contacts/) if you feel response is lacking._

? high ?

_**Example Data**: Requests with clarifying sample data are generally much easier to understand and prioritize. Please attach or link to any representative data, in any form or format, which might help clarify the request._

I can work with collections to determine an appropriate migration pathway if this is approved in principle.

_**Discussion**: Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary._

@ArctosDB/arctos-code-table-administrators 

## Approval

_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [ ] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection

_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation

_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

_Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel._

_Make changes as described above. Ensure the URL of this Issue is included in the definition._

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by Jegelewicz** [comment]
hind foot length?

**Comment by Jegelewicz** [comment]
also should be ctlength_units

**Comment by mkoo** [comment]
Responding to elevate this-- I think this is straightforward
**Proposed New Value:
hind foot length**

(see definition above)

**Proposed actions:** Merge hind foot without claw [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#hind_foot_without_claw)
    hind foot with claw [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#hind_foot_with_claw)

merged values would have the old values in method to distinguish between them
I know @jldunnum @bryansmclean are in the field but tagging them so they see this notice!

**Comment by dustymc** [comment]
Data:

[temp_foot.csv.zip](https://github.com/ArctosDB/arctos/files/11748821/temp_foot.csv.zip)

```

     attribute_type     | guid_prefix | count  
------------------------+-------------+--------
 hind foot with claw    | ACUNHC:Mamm |    824
 hind foot with claw    | ALMNH:Mamm  |    960
 hind foot with claw    | ASNHC:Mamm  |   4723
 hind foot with claw    | CHAS:Mamm   |   2964
 hind foot with claw    | CHAS:Teach  |     26
 hind foot with claw    | DGR:Mamm    |      2
 hind foot with claw    | DMNS:Mamm   |  14352
 hind foot without claw | DMNS:Mamm   |     99
 hind foot with claw    | HMCM:Mamm   |     41
 hind foot with claw    | HSUVM:Mamm  |     43
 hind foot with claw    | MLZ:Mamm    |     17
 hind foot with claw    | MMNH:Mamm   |    420
 hind foot with claw    | MSB:Host    |   3760
 hind foot with claw    | MSB:Mamm    | 112761
 hind foot without claw | MSB:Mamm    |    413
 hind foot with claw    | MVZ:Mamm    |  25260
 hind foot with claw    | MVZObs:Mamm |     35
 hind foot with claw    | NMMNH:Mamm  |    295
 hind foot with claw    | NMU:Mamm    |   2475
 hind foot with claw    | OWU:Mamm    |      1
 hind foot with claw    | UAM:Mamm    |  58776
 hind foot without claw | UAM:Mamm    |     10
 hind foot with claw    | UCM:Mamm    |  13901
 hind foot with claw    | UCSC:Mamm   |    297
 hind foot with claw    | UMNH:Mamm   |  15767
 hind foot with claw    | UMZM:Mamm   |   8021
 hind foot with claw    | UNCG:Mamm   |    648
 hind foot with claw    | UNR:Mamm    |   1974
 hind foot with claw    | UTEP:Mamm   |    298
 hind foot without claw | UTEP:Mamm   |      1
 hind foot with claw    | UTEP:Teach  |      8
 hind foot with claw    | UWBM:Mamm   |  51205
 hind foot without claw | UWBM:Mamm   |      3
 hind foot with claw    | UWYMV:Mamm  |    116
 hind foot with claw    | WNMU:Mamm   |     16

```


 @ebraker
 @bryansmclean
 @mkoo
 @campmlc
 @sharonjansa
 @barke042
 @amgunderson
 @mvzhuang
 @cjconroy
 @makaylaeasley
 @wellerjes
 @asemerdj
 @keg34
 @jebrad
 @babogan
 @AdrienneRaniszewski
 @acdoll
 @jldunnum
 @jrdemboski
 @msbparasites
 @ewommack
 @kderieg322079
 @lin-fred
 @adhornsby
 @droberts49

**Comment by cjconroy** [comment]
I am guessing that if method is going to be "with claw" or "without claw" and is not controlled in some way, it will be spelled 50 different ways and will require cleanup at a later date. Is that a bad assumption?

**Comment by bryansmclean** [comment]
This seems good to me (speaking on behalf of RANGES).

**Comment by ebraker** [comment]
Suggest a hindfoot_length_methods code table with values for "with claw" and "without claw" for reasons stated in my comment in #6307 (could also include 'other' if people think it is an immediate need):

> I'm a bit worried about losing precision so I would advocate for an ear_length_methods code table that includes "from notch" and "from crown" as I'm certain a goodly amount of our volunteers and students will forget to record "from notch" as free text when entering records. There's still Remarks to accommodate pubs and other methods, plus the potential to expand the code table should we start measuring ears in novel ways, or need to add "other" and punt specifics to the Remarks field.

**Comment by dustymc** [comment]
See also https://github.com/ArctosDB/arctos/issues/6413

**Comment by Jegelewicz** [comment]
RANGES group feels like these are different things and should stay as they are.

**Comment by bryansmclean** [comment]
Requesting a slight change in the definitions of the attributes created here. Tweaks to how the base and tip of claws are described.

**hind foot with claw**
current def: Length of the hind foot from the back of the ankle to the end of the longest claw. A numeric value plus units.
new def: Length of the hind foot from the back of the ankle to the tip of the longest claw. A numeric value plus units.

**hind foot without claw**
current def: Length of the hind foot from the back of the ankle to the start of the longest claw. A numeric value plus units.
new def: Length of the hind foot from the back of the ankle to the base of the longest claw. A numeric value plus units.

**Comment by bryansmclean** [comment]
Is this change implemented and just takes a while to refresh? Just not sure how long code table changes usually take.
