### ISSUE TITLE
FYI: AOU checklist

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6311]
Since I've been suggesting this sort of thing forever, I thought I'd demonstrate that it really is possible.

I pulled the checklist from https://checklist.americanornithology.org/

I spent some time trying to clear up malformed linebreaks in data.....

<img width="343" alt="Screenshot 2023-05-19 at 6 37 29 AM" src="https://github.com/ArctosDB/arctos/assets/5720791/9c3af032-0acd-476b-980c-190ec6f5a1b0">
<img width="835" alt="Screenshot 2023-05-19 at 6 37 20 AM" src="https://github.com/ArctosDB/arctos/assets/5720791/3a77e629-2d99-4da8-978a-1001497130d1">
<img width="800" alt="Screenshot 2023-05-19 at 6 35 53 AM" src="https://github.com/ArctosDB/arctos/assets/5720791/100a3ebb-ce2a-41f9-ad2d-bed525b442ae">
<img width="781" alt="Screenshot 2023-05-19 at 6 35 40 AM" src="https://github.com/ArctosDB/arctos/assets/5720791/f41ee901-b47d-4695-8c1a-3127f3721ead">
<img width="1114" alt="Screenshot 2023-05-19 at 6 35 19 AM" src="https://github.com/ArctosDB/arctos/assets/5720791/9c8f4d60-661c-45c3-9d26-314bb707a984">
<img width="1029" alt="Screenshot 2023-05-19 at 6 32 24 AM" src="https://github.com/ArctosDB/arctos/assets/5720791/8cbf8410-9643-419e-9692-bf7971f8480f">

.... and finally gave up, loaded it to Sheets, then downloaded as CSV, which loaded to Arctos without further problem.

This seems like something they might want to correct - @ccicero ??

then I did this:

```
create table temp_aou as select * from  temp_cache.temp_dlm_uptbl ;

alter table temp_aou add scientific_name varchar;
update temp_aou set scientific_name=species;

-- keep I guess, why not
alter table temp_aou add noclass_term_type_1 varchar;
update temp_aou set noclass_term_type_1='AOU ID';
alter table temp_aou rename column id to noclass_term_1;

-- don't think this does anything??
alter table temp_aou drop column rank;


alter table temp_aou add noclass_term_type_2 varchar;
update temp_aou set noclass_term_type_2='common_name';
alter table temp_aou rename column common_name to noclass_term_2;


alter table temp_aou add noclass_term_type_3 varchar;
update temp_aou set noclass_term_type_3='french_name';
alter table temp_aou rename column french_name to noclass_term_3;


alter table temp_aou add noclass_term_type_4 varchar;
update temp_aou set noclass_term_type_4='annotation';
alter table temp_aou rename column annotation to noclass_term_4;


alter table temp_aou add noclass_term_type_5 varchar;
update temp_aou set noclass_term_type_5='status_accidental';
alter table temp_aou rename column status_accidental to noclass_term_5;


alter table temp_aou add noclass_term_type_6 varchar;
update temp_aou set noclass_term_type_6='status_hawaiian';
alter table temp_aou rename column status_hawaiian to noclass_term_6;


alter table temp_aou add noclass_term_type_7 varchar;
update temp_aou set noclass_term_type_7='status_introduced';
alter table temp_aou rename column status_introduced to noclass_term_7;


alter table temp_aou add noclass_term_type_8 varchar;
update temp_aou set noclass_term_type_8='status_nonbreeding';
alter table temp_aou rename column status_nonbreeding to noclass_term_8;



alter table temp_aou add noclass_term_type_9 varchar;
update temp_aou set noclass_term_type_9='status_extinct';
alter table temp_aou rename column status_extinct to noclass_term_9;


alter table temp_aou add noclass_term_type_10 varchar;
update temp_aou set noclass_term_type_10='status_misplaced';
alter table temp_aou rename column status_misplaced to noclass_term_10;


-- this is not really justified, but also expected by GBIF and such, DO WHAT YOU WANT DON'T FOLLOW ME!!


alter table temp_aou add class_term_type_1 varchar;
update temp_aou set class_term_type_1='kingdom';
alter table temp_aou add class_term_1 varchar;
update temp_aou set class_term_1='Animalia';


alter table temp_aou add class_term_type_2 varchar;
update temp_aou set class_term_type_2='class';
alter table temp_aou add class_term_2 varchar;
update temp_aou set class_term_2='Aves';

-- now back to your regularly scheduled conversion


alter table temp_aou add class_term_type_3 varchar;
update temp_aou set class_term_type_3='order';
-- I chanegd this in the csv to be a valid column header
alter table temp_aou rename column porder to class_term_3;


alter table temp_aou add class_term_type_4 varchar;
update temp_aou set class_term_type_4='family';
alter table temp_aou rename column family to class_term_4;


alter table temp_aou add class_term_type_5 varchar;
update temp_aou set class_term_type_5='subfamily';
alter table temp_aou rename column subfamily to class_term_5;


alter table temp_aou add class_term_type_6 varchar;
update temp_aou set class_term_type_6='genus';
alter table temp_aou rename column genus to class_term_6;



alter table temp_aou add class_term_type_7 varchar;
update temp_aou set class_term_type_7='species';
alter table temp_aou rename column species to class_term_7;

-- my one cheat; this would need an Issue

insert into  cttaxonomy_source (source,description) values ('AOU checklist','AOU checklist');


alter table temp_aou add source varchar;
update temp_aou set source='AOU checklist';

-- OK, one more cheat: these data still contain garbage
update temp_aou set noclass_term_4=replaceFreeText(noclass_term_4);

-- this IS NOT the way to do this, but test is test so...
delete from temp_aou where scientific_name not in (select scientific_name from taxon_name);

```

downloaded the table as CSV, loaded it to the classification loader, and you can check it out in test: https://arctos-test.tacc.utexas.edu/taxonomy.cfm?source=%3DAOU+Checklist

I skipped the Issue process, a new Source would require that, but I think that would be very quick and easy.

All of the format manipulation should be completely trivial in something like Excel.

I just deleted anything that wasn't already a name, that would add some work if anyone actually wanted to do this. There are Arctos tools, it should be trivial.

Getting rid of nonprinting characters in data was my biggest challenge, and I suspect it would be for anyone using other tools as well. IDK how well the UI tools would handle that, but I could certainly help now that I know what to expect.

**Comment by ccicero** [comment]
@dustymc This is awesome! I'll definitely check it out. 

I need to get in touch with the checklist db folks anyway, so I'll ask them about the nonprinting character/line break issues.

**Comment by ewommack** [comment]
@wellerjes - pulling you in

@dustymc would it be possible to do this with the common names associated with the AOS list?

**Comment by dustymc** [comment]
@ewommack I did (or, more likely, don't know what you mean and require explanation...)


https://arctos-test.tacc.utexas.edu/name/Syndactyla%20subalaris#AOUchecklist


<img width="518" alt="Screenshot 2023-05-19 at 4 26 55 PM" src="https://github.com/ArctosDB/arctos/assets/5720791/3ceb9023-ffe1-44f9-82ae-efd1b48a4adc">

**Comment by ewommack** [comment]
I guess I'm more brainstorming to see if this new taxonomy might help in some way with: https://github.com/ArctosDB/internal/issues/246
and 
https://github.com/ArctosDB/arctos/issues/5025

The AOS actually reviews and works through their common names, so it might be a good source for agreed upon modern names.
