### ISSUE TITLE
taxonomy mess - botanical hybrids

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6312]
From the error logs:

```
UPDATE taxon_name SET scientific_name='Helianthus X luxurians', name_type='Linnean' where taxon_name_id=12098223
```

That caused an error, but it makes me wonder what hasn't. Are we missing some documentation or ????

https://arctos.database.museum/name/Helianthus%20%C3%97luxurians exists - I think that's probably the intention??

https://arctos.database.museum/name/Helianthus%20xluxurians also exists - I think that probably needs a quarantine, or possibly just deletion, request???

@wellerjes help?

**Comment by wellerjes** [comment]
I discovered this yesterday and need to take a better look at it (I'll go pull the specimens and look at the verbatim taxonomy). I think the ID is a hybrid and should be quarantined/deleted.

Do we have documentation on how hybrid specimens should be entered? I'm assuming as a string?

**Comment by wellerjes** [comment]
I found this re: hybrid: https://github.com/ArctosDB/arctos/issues/4218

https://arctos.database.museum/name/Helianthus%20xluxurians should be quarantined / deleted. I updated the records that had that ID to https://arctos.database.museum/name/Helianthus%20%C3%97luxurians

**Comment by wellerjes** [comment]
I'm trying to correct https://arctos.database.museum/name/Morus%20alba%20xrubra to follow the format and got this error:

<html><body>


ERROR_ID | 7F446588-BB06-46A9-801165FF1D1C1BA8
-- | --
ERROR_TYPE | SQL
ERROR_MESSAGE | ERROR: Save rejected: × can only occur as first character   Where: PL/pgSQL function trigger_fct_trg_taxon_name_biu() line 9 at RAISE
ERROR_DETAIL |  
ERROR_SQL | UPDATE taxon_name SET 		scientific_name='Morus alba ×rubra', 		name_type='Linnean' 		where taxon_name_id=12117099


</body>
</html>

I tried formatting it as × Morus alba rubra and received the same error:
<html><body>


ERROR_ID | BCD97BED-A578-46CB-B7A65060003C8F74
-- | --
ERROR_TYPE | SQL
ERROR_MESSAGE | ERROR: Save rejected: × can only occur as first character   Where: PL/pgSQL function trigger_fct_trg_taxon_name_biu() line 9 at RAISE
ERROR_DETAIL |  
ERROR_SQL | UPDATE taxon_name SET 		scientific_name='× Morus alba rubra', 		name_type='Linnean' 		where taxon_name_id=12117099


</body>
</html>

**Comment by Jegelewicz** [comment]
@wellerjes I believe that you can't change a name that is in use and you are using the name.

Same goes for https://arctos.database.museum/name/Helianthus%20xluxurians which appears to be used by your collection, so it cannot be changed OR quarantined.

![image](https://github.com/ArctosDB/arctos/assets/5725767/ff50257f-3d97-4e02-b4a4-574424b756cc)

**Comment by dustymc** [comment]
> how hybrid specimens should be entered?

Named hybrids require names, which can be created as outlined in https://github.com/ArctosDB/arctos/issues/4218.

This really needs a botanist+taxonomist, but a couple minutes of google suggest

* Helianthus ×luxurians is likely real, if maybe not current.
* Helianthus xluxurians is probably just wrong and does not need quarantined. Records had been moved so I deleted it.
* I'm not sure what ``× Morus alba rubra`` is, but I think it can't be a valid botanical name for a few reasons. 
* If that's at all correct, https://arctos.database.museum/name/Morus%20alba%20xrubra needs deleted.

Maybe the intention is a hybrid of https://arctos.database.museum/name/Morus%20alba and https://arctos.database.museum/name/Morus%20rubra, in which case https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxa_formula#a_x_b is probably relevant

These probably need a hard look as well:

```
arctosprod@arctos>> select scientific_name from taxon_name where created_by_agent_id =(select agent_id from agent where preferred_agent_name='Dawn R. Roberts') and scientific_name like '% x%';
   scientific_name    
----------------------
 Equisetum xmackaii
 Lecanora xanthophana
 Verbena xblanchardii
 Verbena xmoechina
 Verbena xrydbergii
 Morus alba xrubra
(6 rows)
```

```

arctosprod@arctos>> select scientific_name from taxon_name where scientific_name like '% x-%' order by scientific_name;
    scientific_name     
------------------------
 Acicnemis x-nigrum
 Anacroneuria x-nigrum
 Balaninus x-pallidum
 Baridius x-littera
 Baris x-album
 Baris x-littera
 Baris x-signum
 Bethelium x-scriptum
 Brevoxathres x-littera
 Centrinaspis x-album
 Cercidocerus x-rubrum
 Ctenoplon x-littera
 Curculio x-album
 Curculio x-pallidum
 Demonax x-signatus
 Desmiphora x-signata
 Diadelia x-brunnea
 Diadelia x-fasciata
 Diadelia x-fascioides
 Diadelia x-flava
 Diadelia x-fusca
 Diadelia x-fuscoides
 Encyclops x-signata
 Erimystax x-punctatus
 Exocentrus x-ornatus
 Geraeus x-album
 Geraeus x-notatum
 Glenea x-nigrum
 Hadena x-scriptum
 Heterachthes x-notatus
 Heurippa x-album
 Homoeostethus x-alba
 Hybopsis x-punctata
 Leptostylus x-griseus
 Luperina x-notata
 Malacosoma x-strigata
 Monochamus x-fulvum
 Nericonia x-litterata
 Omotemnus x-rufum
 Oncocnemis x-scripta
 Oncocnemis x-signata
 Orchestes x-album
 Paramecyna x-signata
 Perissus x-littera
 Perrhaebius x-album
 Phelypera x-maculata
 Phragmatobia x-album
 Rhinochenus x-rubrum
 Rhinoscapha x-album
 Rhynchaenus x-album
 Rosama x-magnum
 Sanogasta x-signata
 Scinax x-signata
 Scinax x-signatus
 Sybrinus x-ornatus
 Sympaector x-album
 Tabatinga x-littera
 Zygiella x-notata
(58 rows)

```

**Comment by wellerjes** [comment]
This can be deleted: https://arctos.database.museum/name/Morus%20alba%20xrubra

I will work on re-entering the other ones as strings and will let you know when they can be deleted.

**Comment by wellerjes** [comment]
Record changed, okay to delete taxonomy page for [Helianthus ×luxurians](https://arctos.database.museum/name/Helianthus%20%C3%97luxurians)

Reviewed:
- Equisetum xmackaii - updated records, okay to delete
- Lecanora xanthophana - NOT a hybrid, but is a synonym (updated record)
- Verbena xblanchardii - updated records, okay to delete
- Verbena xmoechina - updated records, okay to delete
- Verbena xrydbergii - updated records, okay to delete

I started on the second batch and realized there were non-plants; I ran them through https://verifier.globalnames.org/
out of the 58, 54 are Phylum Arthropoda; the rest are Phylum Chordata

**Comment by dustymc** [comment]
>rest are Phylum Chordata

Oh - yikes/thanks, done.

Delete requests done.

Issue done?

**Comment by Jegelewicz** [comment]
> Issue done?

Are there still some that are weird that we need to review?

**Comment by dustymc** [comment]
Not that I could find.

**Comment by Jegelewicz** [comment]
Cool - so I'm closing.
