### ISSUE TITLE
MVZ mammal attribute dates are largely migration dates, not prep or collecting dates

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#6317]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
There are 6135 MVZ mammals that have attribute tail length greater than 1 with a date of determination of 2005-11-01. This is a data migration date, not a date related to either collection or preparation of the specimens. This appears to be the date for most of the attributes for the same animal, e.g. total, ear, foot, weight, sec. If we are going to put value on this field, then it would be great to clean this up. I don't know if it is possible, but where there is only one date for a specimen, like the end date for collecting, that should be the date there. However, there are likely many cases where there are specimens that were frozen and prepared, and measured later. Could these be divvied up?

In perusing the list of specimens with this made up date, 3,670 MVZ mammals have a reproductive comment attributes with a date of 2006-05-23. This is probably another data migration date and not real. Could these also be updated somehow?  

I would guess this is a broader issue than MVZ mammals. I was going to query arctos for these attribute dates while logged out, but totally unclear on how to query specimen attributes when logged out. 
--

**Comment by dustymc** [comment]
>totally unclear on how to query specimen attributes when logged out

Bah, there's a bug, I'll get it for next release. (And we keep talking about more 'default' profiles but nobody's proposed anything actionable....)

>broader issue than MVZ mammals. 

Probably, but it'll be different values and some collections may want the 'before or on' date or whatever. Let's deal with small chunks, at least for now.

>where there is only one date for a specimen, like the end date for collecting, that should be the date there. 

I'd recommend just saying what's known without making assumptions for users, but they're your data and you can do with them what you will (and this is of course common practice). I think there are publications on eg mammal length measurements changing between live and various stages of postmortem, introducing unsubstantiated data in here would make that sort of thing difficult to avoid.

Here's some data. Let me know if you want me to update something based on this, further refine something, or whatever.

```


drop table temp_mvzmamm20051101;
create table temp_mvzmamm20051101 as
select
    flat.guid_prefix,
    flat.guid,
    attributes.attribute_id,
    attributes.collection_object_id,
    attribute_type,
    attribute_value,
    attribute_units,
    getPreferredAgentName(determined_by_agent_id) determiner,
    attribute_remark,
    determination_method,
    determined_date,
   flat.ended_date as flat_ended_date
from
    attributes
    inner join flat on attributes.collection_object_id=flat.collection_object_id
where
    guid_prefix='MVZ:Mamm' and
    determined_date='2005-11-01'
;

-- these can't be right

arctosprod@arctos>> select count(*) from temp_mvzmamm20051101 where flat_ended_date>determined_date;
 count 
-------
   323
(1 row)


```
[temp_mvzmamm20051101.csv.zip](https://github.com/ArctosDB/arctos/files/11537062/temp_mvzmamm20051101.csv.zip)

**Comment by cjconroy** [comment]
I'm not clear on how you got only 323 when I get far more records with that date. 
I think it would not take me very long to parse the longer list into specimens prepped in the field vs. those that were frozen and prepped later. However, I don't think we had a way to record prepped on date back then, so those dates will have to stay erroneous.
Sort of related, the agent who determined the attribute is listed as [Museum of Vertebrate Zoology, University of California, Berkeley](https://arctos.database.museum/agent/10014238). For the wild caught and prepared specimens we know who prepared it, so could we also update those attributes to the collector?

Chris

**Comment by mkoo** [comment]
@cjconroy see the above -- Dusty's recommendation work?

**Comment by cjconroy** [comment]
If we can have null, it seems good to replace 2005-11-01 with null for attribute date since it is a fake date. Go for it. I know now when we enter data attributes get the date of prep, so those are all good. This 2005-11-01 date was just a migration date and is meaningless.

**Comment by dustymc** [comment]
Done, will take a while for the cache to catch up.
