### ISSUE TITLE
Code Table Request - REMOVE wing span OR extension

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6319]
## Initial Request

_**Goal**: Describe what you're trying to accomplish. This is the only necessary step to start this process. The Committee is available to assist with all other steps. Please clearly indicate any uncertainty or desired guidance if you proceed beyond this step._

We have wing span and extension. Documentation suggests they're duplicates. If not, they should be clarified. If so, one should be removed.

_**Discussion**: Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary._

[temp_wse.csv.zip](https://github.com/ArctosDB/arctos/files/11537896/temp_wse.csv.zip)

```

 guid_prefix | count 
-------------+-------
 ASNHC:Mamm  |     3
 CHAS:Bird   |   135
 CRCM:Bird   |  3986
 CSULB:Bird  |     5
 DMNS:Bird   |    75
 MLZ:Bird    |     1
 OWU:Mamm    |     1
 UAM:Mamm    |     2
 UCM:Bird    |   740
 UCM:Mamm    |   140
 UMZM:Bird   |     3
 UNR:Bird    |     1
 UTEP:Bird   |    41
 UWBM:Mamm   |    21
 UWZM:Bird   |    58

```

 @ebraker
 @amgunderson
 @mvzhuang
 @makaylaeasley
 @wellerjes
 @jebrad
 @acdoll
 @jessicatir
 @adhornsby
 @droberts49

@ArctosDB/arctos-code-table-administrators 

## Approval

_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [ ] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection

_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation

_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

_Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel._

_Make changes as described above. Ensure the URL of this Issue is included in the definition._

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by acdoll** [comment]
I was taught that wingspan was the colloquial way of saying extension.

**Comment by dustymc** [comment]
If they are the same, my preference would be for the colloquial. I suspect that's how we got here - bats or bugs or something didn't recognize or understand the fancy word. (Or I didn't on someone's behalf...)

**Comment by dustymc** [comment]
I've added this to the next AWG agenda as an announcement.

Unless some other directive surfaces before, on **2024-09-27** I will

*  change all 'extension' to 'wing span'
* add ``formerly "extension"`` to remark for the changed attributes
* remove extension from the code table

Fresh data:

[temp_wse.csv.zip](https://github.com/user-attachments/files/17078486/temp_wse.csv.zip)

Summary:

```

 guid_prefix | count 
-------------+-------
 ASNHC:Mamm  |     3
 CHAS:Bird   |   135
 CHAS:Ento   |     1
 CRCM:Bird   |  3989
 CSULB:Bird  |     5
 DMNS:Bird   |    74
 DMNS:Mamm   |    61
 HSUVM:Mamm  |     1
 MLZ:Bird    |     3
 MMNH:Bird   |    52
 MMNH:Mamm   |    11
 OWU:Mamm    |     1
 UAM:Mamm    |     2
 UCM:Bird    |   747
 UCM:Mamm    |   140
 UMZM:Bird   |    13
 UMZM:Mamm   |    11
 UNR:Bird    |     1
 UTEP:Bird   |    41
 UWBM:Mamm   |    21
 UWZM:Bird   |    58
 UWZM:Mamm   |    60
```

Contacts:


 @ebraker
 @ehalverson26
 @amgunderson
 @mvzhuang
 @rwilhoyt
 @wellerjes
 @asemerdj
 @jebrad
 @jrpletch
 @acdoll
 @jrdemboski
 @jessicatir
 @adhornsby
 @droberts49

**Comment by adhornsby** [comment]
Does anyone know what "extension" would mean in mammal collections?  My gut reaction is to change these to wingspan for birds but shift into a verbatim attribute for mammals.

**Comment by dustymc** [comment]
> what "extension" would mean in mammal collections

That's why (lacking other input) I'll go the other way; see https://github.com/ArctosDB/arctos/issues/6319#issuecomment-1558481151, https://github.com/ArctosDB/arctos/issues/6319#issuecomment-1559553286, https://github.com/ArctosDB/arctos/issues/6319#issuecomment-2364181225

And only one winged raccoon in Arctos!

```
          scientific_name           | count 
------------------------------------+-------
 Aeorestes cinereus                 |     1
 Artibeus jamaicensis yucatanicus   |     1
 Artibeus lituratus palmarum        |     1
 Carollia perspicillata             |     4
 Carollia perspicillata azteca      |     4
 Corynorhinus rafinesquii           |     1
 Corynorhinus townsendii            |     2
 Corynorhinus townsendii pallescens |    53
 Corynorhinus townsendii townsendii |     4
 Desmodus rotundus rotundus         |     2
 Eptesicus fuscus                   |    24
 Eptesicus fuscus fuscus            |     3
 Eptesicus fuscus pallidus          |    20
 Euderma maculatum                  |     1
 Hipposideros armiger               |     2
 Lasionycteris noctivagans          |    11
 Lasiurus borealis                  |     7
 Lasiurus cinereus                  |     5
 Lasiurus cinereus cinereus         |     6
 Lasiurus ega xanthinus             |     1
 Leptonycteris nivalis longala      |     1
 Megaderma lyra                     |     1
 Myotis                             |     9
 Myotis californicus                |     3
 Myotis californicus stephensi      |    23
 Myotis ciliolabrum                 |     2
 Myotis ciliolabrum ciliolabrum     |     1
 Myotis ciliolabrum melanorhinus    |     2
 Myotis evotis                      |     2
 Myotis evotis evotis               |     1
 Myotis keenii septentrionalis      |     1
 Myotis lucifugus                   |    19
 Myotis lucifugus carissima         |     5
 Myotis lucifugus lucifugus         |     5
 Myotis septentrionalis             |    11
 Myotis sodalis                     |     3
 Myotis thysanodes thysanodes       |     1
 Myotis velifer                     |     4
 Myotis volans                      |     3
 Myotis volans ?                    |     1
 Myotis volans interior             |    10
 Myotis yumanensis                  |     2
 Myotis yumanensis saturatus        |     1
 Nyctinomops femorosaccus           |     1
 Parastrellus hesperus hesperus     |    14
 Parastrellus hesperus maximus      |     2
 Perimyotis subflavus               |     8
 Procyon lotor hirtus               |     1
 Pteropus                           |     1
 Tadarida brasiliensis              |     2
 Tadarida brasiliensis cynocephala  |     1
 Tadarida brasiliensis mexicana     |    17
(52 rows)
```

**Comment by adhornsby** [comment]
> And only one winged raccoon in Arctos!

Ah, that makes more sense!  I thought we were dealing with a bunch of squirrel wingspans or something...

**Comment by campmlc** [comment]
Everything but the raccoon (?) is a bat. My understanding is that mammals would prefer to use wingspan, but cc'ing mammalogists @jldunnum @bryansmclean @amgunderson 
I've honestly never heard of bat "extension" - but Google has:  "The .bat extension is used for batch files in Microsoft's Windows operating system.

**Comment by dustymc** [comment]
@campmlc PLEASE read https://github.com/ArctosDB/arctos/issues/6319#issuecomment-2364181225 - and I'm going to hide some off-topic comments, including this one.

**Comment by dustymc** [comment]
AWG discussed, go.

**Comment by dustymc** [comment]
[temp_extension.csv.zip](https://github.com/user-attachments/files/17171381/temp_extension.csv.zip)
