### ISSUE TITLE
Arctos not displaying catalog records

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#6320]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I went to look at the records associated with Accn UWYMV:Mamm:407, clicked on the button at got a search results page with blank results:

![problem with catalog](https://github.com/ArctosDB/arctos/assets/18562884/9f93011e-c74a-4b11-ad3e-1f9e254098ee)

I thought ok, maybe the records didn't load right and so searched for UWYMV:Mamm:6672 (which I had loaded from Accn 373 before), and got the record just fine.
So maybe something went wrong with uploading the records for Accession UWYMV:Mamm:407? (UWYMV:Mamm:6673 through 6680). I looked in the bulkloader, and the accession is no longer accessible so they should have loaded. I submitted them several hours ago.

Using MacOS Chrome

**Comment by dustymc** [comment]
https://arctos.database.museum/info/flat_status.cfm

https://github.com/ArctosDB/arctos/issues?q=is%3Aissue+https%3A%2F%2Farctos.database.museum%2Finfo%2Fflat_status.cfm

**Comment by ewommack** [comment]
So just wait it out?
