### ISSUE TITLE
MOVE: attribute trap type

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6323]
## Initial Request

_**Goal**: Describe what you're trying to accomplish. This is the only necessary step to start this process. The Committee is available to assist with all other steps. Please clearly indicate any uncertainty or desired guidance if you proceed beyond this step._

I don't understand why trap type [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#trap_type) exists - that should be collecting method, no??

_**Discussion**: Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary._

[temp_traptype.csv.zip](https://github.com/ArctosDB/arctos/files/11545548/temp_traptype.csv.zip)

```
 guid_prefix | count 
-------------+-------
 MSB:Mamm    |     5
 MVZ:Mamm    |    30
 MVZObs:Mamm |    89
 UAM:Mamm    |     5
 UTEP:Ento   |   328
```

 @mkoo
 @Jegelewicz
 @campmlc
 @AdrienneRaniszewski
 @amgunderson
 @jldunnum
 @cjconroy

@ArctosDB/arctos-code-table-administrators 

## Approval

_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [ ] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [ ] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection

_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation

_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

_Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel._

_Make changes as described above. Ensure the URL of this Issue is included in the definition._

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by dustymc** [comment]
>converted

Probably won't be a 1:1 relationship, so that would require a migration.

>once we are ready 

What's the current obstacle?

**Comment by jldunnum** [comment]
Main thing here for us is being able to get at trap success via the different trap types (sherman, museum special, rat trap, pitfall, etc.) as well as tracking what works for what taxa.

______________________________________________________________

Jonathan L. Dunnum Ph.D. (he, him, his)
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

Chair, Systematic Collections Committee, American Society of Mammalogists
Latin American Fellowship Committee, ASM

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by dustymc** [comment]
@jldunnum understood, but scattering those data around just ensures that nobody will be able to make sense of them, no matter how good the data themselves are.

This structure also absolutely precludes your stated goals, unless you're cataloging all the things you don't catch in traps. (You are not, that would be impossible - even if we are attempting it elsewhere.) In collecting method (where n-5 of your data are), that's accessible - just check method vs. captured species-or-sex-or-whatever normalized across ranges or habitats or whatever. (More or less, there are some denormalizers - collecting event would be much better, but some bigger-picture things need sorted out before we can really embrace that, at least for legacy data.)

**Comment by jldunnum** [comment]
Yeah I don't care where it is as long as its retrievable and we can record actual trap type. We do track trap success for our traplines and have started archiving track data from our GPS units which we eventually hope to integrate into Arctos to show effort (# of traps per a given distance), and at some level the negative data as well as the capture locations.

______________________________________________________________

Jonathan L. Dunnum Ph.D. (he, him, his)
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

Chair, Systematic Collections Committee, American Society of Mammalogists
Latin American Fellowship Committee, ASM

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by dustymc** [comment]
>don't care where it is as long as its retrievable

Going active for transfer to collecting method.

**Comment by campmlc** [comment]
What was the solution? It would be good to get a summary of how this was resolved. It is being moved to where?

**Comment by dustymc** [comment]
Pre- and post-update data: [temp_traptype.csv.zip](https://github.com/user-attachments/files/16695772/temp_traptype.csv.zip)
