### ISSUE TITLE
Code Table Request - CLARIFY: colors, soft parts

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6324]
## Initial Request

_**Goal**: Describe what you're trying to accomplish. This is the only necessary step to start this process. The Committee is available to assist with all other steps. Please clearly indicate any uncertainty or desired guidance if you proceed beyond this step._

colors [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#colors)

>General description of colors.

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#soft_parts

>Areas of skin and other organs that may change or be modified throughout an animal's lifetime. Examples include the eye, legs, and areas around the beak and mouth. [Publication](https://static1.squarespace.com/static/5a9484cf5b409b74dffe7b7b/t/5c4cd68d42bfc1202788a30f/1548539534548/SoftPartColoration.pdf)

Are these different? Can we shore up the documentation or merge them?

_**Discussion**: Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary._

[temp_csp.csv.zip](https://github.com/ArctosDB/arctos/files/11545662/temp_csp.csv.zip)

agreed | guid_prefix | count 
 --- | --- | --- 
 - [ ] | ALMNH:EH    |   710
 - [ ] | ALMNH:Mamm  |     1
 - [ ] | APSU:Herp   |    57
 - [ ] | ASNHC:Bird  |     1
 - [ ] | BYU:Herp    |     3
 - [ ] | CHAS:Bird   |   338
 - [ ] | CHAS:EH     |     1
 - [ ] | CHAS:Herb   |   142
 - [ ] | CHAS:Herp   |    29
 - [ ] | CHAS:Mamm   |     2
 - [ ] | CSULB:Bird  |    64
 - [ ] | DMNS:Bird   |   107
 - [ ] | DMNS:Mamm   |    39
 - [ ] | MLZ:Bird    |   312
 - [ ] | MLZ:Fish    |    85
 - [ ] | MSB:Bird    | 14995
 - [ ] | MSB:Herp    |     1
 - [ ] | MVZ:Bird    | 22297
 - [ ] | MVZ:Herp    |   876
 - [ ] | NHSM:Geol   |  1089
 - [ ] | NMMNH:Bird  |     1
 - [ ] | NMMNH:Geol  |   756
 - [ ] | UCM:Bird    |    79
 - [ ] | UCM:Herp    |   505
 - [ ] | UCM:Mamm    |     2
 - [ ] | UCM:Obs     |     1
 - [ ] | UMNH:Herp   |     1
 - [ ] | UMZM:Bird   |     1
 - [ ] | UNR:Bird    |     5
 - [ ] | UTEP:Bird   |    54
 - [ ] | UTEP:Herb   |  2586
 - [ ] | UTEP:Herp   |    38
 - [ ] | UTEP:HerpOS |     1
 - [ ] | UWBM:Herp   |     1
 - [ ] | UWYMV:Bird  |   404
 - [ ] | UWYMV:Mamm  |     3
 - [ ] | UWZM:Bird   |    92

 @ebraker
 @Nicole-Ridgwell-NMMNHS
 @mkoo
 @ccicero
 @atrox10
 @mvzhuang
 @makaylaeasley
 @jtgiermakowski
 @wellerjes
 @brandon-s-thompson
 @babogan
 @gradyjt
 @acdoll
 @jrdemboski
 @byuherpetology
 @ewommack
 @kderieg322079
 @catherpes
 `@mschmidtjr`
 @lin-fred
 @claypollock
 @adhornsby
 @Jegelewicz
 @droberts49

@ArctosDB/arctos-code-table-administrators 

## Approval

_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection

_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation

_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

_Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel._

_Make changes as described above. Ensure the URL of this Issue is included in the definition._

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by Jegelewicz** [comment]
[colors](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#colors) vs. [soft parts](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#soft_parts)

**Comment by ewommack** [comment]
> I feel like 'soft parts' should be subsumed into 'colors'.

But not as a methods I think. I'd still look for entries that have soft part colors recorded, since those will be taken at a specific time in the animals life, and can't be taken after death.

**Comment by catherpes** [comment]
Soft parts or probably better termed 'bare parts' is something we and a 
lot of other bird collections use in freshly collected bird specimens to 
describe the visible unfeathered areas of the specimen. We don't do 
apteria unless they are the vocal sacs on grouse, and maybe another 
example I'm forgetting.

eye combs, facial wattles, vocal sacs, iris, feet including tarsi, toes, 
toe pads/soles,webs, lobes; bill including maxilla, mandible, tomia, 
culmen, gonys; cere, head and neck skin of vultures, guinea fowl, etc.  
I'm surely forgetting some. These have to be done on live or freshly 
dead specimens because they can change extremely rapidly.

Subsuming this into a catch-all 'colors' that seems to be used in other 
taxa for any part of the specimen does not seem appropriate.

**Comment by dustymc** [comment]
<img width="380" alt="Screenshot 2023-05-23 at 11 36 27 AM" src="https://github.com/ArctosDB/arctos/assets/5720791/95952b63-731e-47b4-8097-17b7837f6fc9">



Not a collection-thing either:



<img width="337" alt="Screenshot 2023-05-23 at 11 44 08 AM" src="https://github.com/ArctosDB/arctos/assets/5720791/3e9ca3b8-2a2d-48d0-9858-6b776692ff2b">



I think these are used interchangeably. I certainly have no problem keeping both if they're different things, but if that's so we clearly need better definitions and a migration path.



>live or freshly dead



Hopefully that's recorded in method! (And maybe something about the device - "human of unknown visual acuity" or spectroscope or ?? - and lighting and .....)

>any part of the specimen

I think there's necessarily an expectation of the part being named in such a free-text approach (but that doesn't always happen):

<img width="323" alt="Screenshot 2023-05-23 at 11 44 53 AM" src="https://github.com/ArctosDB/arctos/assets/5720791/54d7f240-ab82-4c55-a693-d6309d96772d">



>used in other taxa

I don't think I see a problem here. (I definitely struggle with similar situations, but I think mostly when a term itself means slightly different things in different contexts.) Maybe there's something interesting in being able to query brown gemstones and motorcycles and birds. Is there some potential harm in that?

**Comment by catherpes** [comment]
In the current table, soft parts is only used in birds. whereas colors 
is in bird collections and others.

The inconsistencies within a collection -even perhaps MSB Birds- of 
using colors vs soft parts is likely a function of people entering data 
and not knowing the distinction, or a collection that doesn't care to 
make the distinction. It is my prefernce for this collection that soft 
parts is used exclusively to describe unfeathered parts of the specimen.

Yes, there is an expectation that parts are named in the text string. If 
a part is not included, It's not very helpful of course, but mistakes do 
happen.

I do  not imagine that there is an efficient way to come up with a 
series of drop down menus with constrained vocabulary to guarantee that 
a color without an associated part is not entered, and I'm okay with 
that. We're dealing with qualitative data here, and it's going to be 
messy. Message ID: ***@***.***>

**Comment by ewommack** [comment]
You also might use soft part color for a very specific point in an animals life cycle for live behavioral data. 

Some birds definitely change color at different times of year in their skin tones for eye rings, feet, and ceres. Eye color is also a known trait that can change with age and sex. As we bring in more behavioral data I could see us adding multiple soft part colors across an animals life time.

**Comment by dustymc** [comment]
>it's going to be messy

There are two variants of "messy."

1. Normalization - clear, delineated, non-overlapping homes for specific types of data. That's the entire purpose of free-text attributes: a way to categorize descriptive data. We can't make anyone use them, much less use them correctly, but Arctos can - and must! - provide the container when there's a need.
2. Data quality - the contents. Unless we're willing and able to specify color in K, it's going to be messy. Oh well, it is what it is. Hopefully we can develop guidance and such, but free text is free text.


I'm only asking to address (1) here, a task at which the data themselves strongly suggest we have failed. I just need to know if these two THINGS are the same or not in sufficient detail to recommend a next step.

**Comment by ewommack** [comment]
> if these two THINGS are the same or not

Not the same for birds. Two different things.

**Comment by dustymc** [comment]
>Two different things.

Then please provide definitions and we can start looking for a migration path.

**Comment by Jegelewicz** [comment]
@ccicero thoughts?

**Comment by Jegelewicz** [comment]
@ArctosDB/arctos-code-table-administrators think these should be merged with soft parts in method for those attributes.

**Comment by ewommack** [comment]
I'm still not sold on the idea of merging them, but we'll handle it. We will probably need a part for color morph or intugumunt color at some point. Soft parts will not be where we should be putting info on colors of things like fur/feathers. 

Is the agreement from the committee to merge soft parts into colors, or colors into soft parts?

**Comment by Jegelewicz** [comment]
soft parts into colors

to be as generic as possible

**Comment by mschmidtjr** [comment]
Does this conversation need a reminder that minerals and rocks also have colors to describe, and are not soft parts?  I'm not sure why I have been in this thread, so you can decide whether this is relevant to the question you are working on.
Also, for Teresa: I need one or more classes with you to figure out how to enter new data records (and maybe another smaller batch) and correct existing data.  July could be a time to do this.

**Comment by Jegelewicz** [comment]
@mschmidtjr Thanks! I think that using [colors](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#colors) for mineral collections makes perfect sense and this conversation should not affect that at all! Basically, we are planning to take all [soft parts](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#soft_parts) attributes and change them to colors with "soft parts" in the method. This won't affect your use of colors at all!

> I need one or more classes with you to figure out how to enter new data records (and maybe another smaller batch) and correct existing data. July could be a time to do this.

Please let me know your availability in [this When2Meet](https://www.when2meet.com/?20558428-yOOcF) and I will schedule a call for us!

**Comment by Jegelewicz** [comment]
@mschmidtjr great! I sent you a calendar invite for Monday. See you then!

**Comment by dustymc** [comment]
```

 guid_prefix | attribute_type | count 
-------------+----------------+-------
 ALMNH:EH    | colors         |   710
 ALMNH:Mamm  | colors         |     1
 APSU:Herp   | colors         |    57
 ASNHC:Bird  | soft parts     |     1
 BYU:Herp    | colors         |     3
 CHAS:Bird   | colors         |     7
 CHAS:Bird   | soft parts     |   331
 CHAS:EH     | colors         |     1
 CHAS:Herb   | colors         |   173
 CHAS:Herp   | colors         |    29
 CHAS:Mamm   | colors         |     2
 CSULB:Bird  | colors         |    64
 DMNS:Bird   | colors         |    17
 DMNS:Bird   | soft parts     |    90
 DMNS:Inv    | colors         |     1
 DMNS:Mamm   | colors         |    42
 MLZ:Bird    | colors         |    71
 MLZ:Bird    | soft parts     |   268
 MLZ:Fish    | colors         |    85
 MMNH:Bird   | soft parts     |     1
 MSB:Bird    | colors         |   290
 MSB:Bird    | soft parts     | 14793
 MSB:Herp    | colors         |     1
 MVZ:Bird    | colors         |  2210
 MVZ:Bird    | soft parts     | 20108
 MVZ:Herp    | colors         |   876
 NHSM:Geol   | colors         |  1171
 NMMNH:Bird  | colors         |     1
 NMMNH:Geol  | colors         |   756
 NMMNH:Herb  | colors         |     1
 UAM:EH      | colors         |     1
 UCM:Bird    | colors         |    31
 UCM:Bird    | soft parts     |    47
 UCM:Herp    | colors         |   505
 UCM:Mamm    | colors         |     3
 UCM:Obs     | colors         |     1
 UMNH:Bird   | colors         |     3
 UMNH:Herp   | colors         |     1
 UMZM:Bird   | colors         |    18
 UNR:Bird    | colors         |     5
 UTEP:Bird   | colors         |     6
 UTEP:Bird   | soft parts     |    48
 UTEP:Herb   | colors         |  2587
 UTEP:Herp   | colors         |    38
 UTEP:HerpOS | colors         |     1
 UWBM:Herp   | colors         |     1
 UWBM:Mamm   | colors         |    64
 UWYMV:Bird  | colors         |   223
 UWYMV:Bird  | soft parts     |   181
 UWYMV:Mamm  | colors         |     3
 UWZM:Bird   | colors         |    92
 UWZM:Herp   | colors         |    86
 UWZM:Mamm   | colors         |   101
```

**Comment by ewommack** [comment]
So the goal is to move soft parts to colors, and colors is staying as is?

**Comment by Jegelewicz** [comment]
> move soft parts to colors, and colors is staying as is?

Yep!

**Comment by mschmidtjr** [comment]
Teresa -

I never have known why I'm a CC on this thread, so maybe I can get
dropped.  My only reminder is to think beyond the biology box and remember
minerals and rocks have colors but usually don't have soft parts, in case
that matters.  And one day we'll get around to my making changes or entries
in our Arctos data, but busy now.

- Martin

**Comment by Jegelewicz** [comment]
@mschmidtjr unfortunately, I cannot remove you from this thread, and we had a side conversation, so you are being notified because you participated. There is nothing for you to do here, so you can just ignore any future notifications from this thread.

**Comment by catherpes** [comment]
Call them all colors. I think it's only slightly more useful than soft parts, which should really be bare parts in birds. External colors? As long as vocabulary is not constrained because of another collection, I don't suppose it really matters to me.

**Comment by dustymc** [comment]
From email:

>see if there are any records that have both 'colors' and 'soft parts'

```

 UTEP:Bird:3096
 UTEP:Bird:3096
 UTEP:Bird:3096
 MVZ:Bird:59115
 UWYMV:Bird:4254
```

>Dusty would auto-insert “soft parts” into Method for all existing soft parts values.

Sure, I can do that.

>saved if possible is the determiner and the date

Unless someone tells me to do something else I'll just change the type (and update the method as above) - all metadata will be preserved.

**Comment by ewommack** [comment]
Ah yep - the UWYMV bird is one where I had both soft part color and also plumage aberrations I needed to record. All one determiner though, since I got the bird quickly after death. 
I could combine those into one color attribute for our record - would that be easier @dustymc? Or I could go in and fix it later after the migration.

**Comment by Jegelewicz** [comment]
@dustymc @ccicero @ArctosDB/arctos-code-table-administrators do the people using colors need to agree to this or are we only concerned with those using soft parts? Before I make a long list of collections that need to respond, do we only need responses from those using soft parts?

**Comment by ebraker** [comment]
I would think we only need feedback from those collections using soft parts

**Comment by ccicero** [comment]
Summary of responses to the issue of merging soft parts into colors:

1) UCM: @ebraker +1. Comment for @dustymc to auto-insert “soft parts” into Method for all existing soft parts values
2) UWYMV: @ewommack +1. The one thing I'd like saved if possible is the determiner and the date for the "soft parts"
3) CHAS: @droberts49 +1. 
4) ASNHC: Rose Wilhoyt +1
5) MSB: @catherpes +1
6) MVZ: @ccicero +1

I think that covers all affected collections using 'soft parts' so ok to move this to Active Development. Will let @dustymc do that.

**Comment by dustymc** [comment]
Fresh data:

[temp_sprt.csv.zip](https://github.com/ArctosDB/arctos/files/14812005/temp_sprt.csv.zip)

done
