### ISSUE TITLE
Code Table Request - Add Blood Plasma to birds

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#6333]
@msaqib2 - including our Grad CA in the issue so he can track

## Initial Request
Can we please add Blood Plasma (https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name&coln=#blood_plasma) to the bird part code table?

_**Proposed Value**: 
blood plasma](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name&coln=#blood_plasma)

_**Proposed Definition**: 
Same as already present in code table: Blood plasma, unknown preservation.

_**Attribute data type** Object part

_**Context**: The UWYMV will have birds that have both blood and blood plasma parts coming in from banded individuals very soon.

_**Table**: Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. 
The UWYMV will have birds that have both blood and blood plasma parts coming in from banded individuals very soon.

_**Collection type**: Birds

_**Available for Public View**: yes

_**Project**: Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184)._

_**Discussion**: Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary._

@ArctosDB/arctos-code-table-administrators 

## Approval

_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [ ] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection

_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation

_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

_Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel._

_Make changes as described above. Ensure the URL of this Issue is included in the definition._

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by campmlc** [comment]
I support this. Checked code table box.

**Comment by Jegelewicz** [comment]
Added.

**Comment by ewommack** [comment]
Thank you!
