### ISSUE TITLE
Arctos Report Template Request: AKA agent to formulate new identifiers in a report

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#6334]
**Description of the report**  This a request so I dont forget for a generic SQL to show other identifiers in a typical formatted way. For example:
if **Issued by** is "MCZ: Museum of Comparative Zoology" (and AKA = MCZ:Herp) and **IDValue** is "A-1234" then I want in my report: **"MCZ:Herp:A-1234"**

I dont have a specific report yet but anticipate this need on reports or labels or CSV output under "Identifiers" (or call it something else)

**Comment by dustymc** [comment]
In general: sure, give me a specific example and I should be able to make that happen.

Specifically: This loops back to https://github.com/ArctosDB/arctos/issues/6163, there's no need for cryptic references when there's a good one available (and it matters little who issued good identifiers, they just can't be very cryptic). If you mean https://mczbase.mcz.harvard.edu/guid/MCZ:Herp:A-1234, you should just say https://mczbase.mcz.harvard.edu/guid/MCZ:Herp:A-1234 - anything else is going to be more work for worse data.

**Comment by dustymc** [comment]
Addressed via https://github.com/ArctosDB/arctos/issues/7722 and https://github.com/ArctosDB/arctos/issues/7722
