### ISSUE TITLE
Need Help with Arctos Error - trying to add 31 UAM:Ento records to a KWP:Ento data loan

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#6335]
# Error Text
**Copy the text from the page and paste it here**

ERROR_ID 	A60EBFC7-9C81-4EC6-B060B4AA6CF654CB
ERROR_TYPE 	SQL
ERROR_MESSAGE 	ERROR: Data Loans may contain only cataloged items Where: PL/pgSQL function trigger_fct_trg_loan_item_biu() line 9 at RAISE
ERROR_DETAIL 	
ERROR_SQL 	INSERT INTO loan_item ( TRANSACTION_ID, COLLECTION_OBJECT_ID, RECONCILED_BY_PERSON_ID, RECONCILED_DATE, ITEM_DESCR, ITEM_INSTRUCTIONS, LOAN_ITEM_REMARKS ) VALUES ( 21112965, 541217, 1014877, current_date, 'UAM:Ento:409965 whole organism', null, null )

request dump:
request
node_name	
string	arctos-2021
rdurl	
string	/info/loan_item_pick.cfm

# Where it happened
**Provide a link to or a description of the page where the error occurred.**

Trying to add 31 records to a data loan 

# Steps to get there
**Describe the actions that led to the error**

this is the loan
https://arctos.database.museum/transactionSearch.cfm?action=srch&loaned_part_id=31490198

I also tried the data loan bulkloader (which BTW is an antique - it doesn't take GUIDs, one has to split the GUID into catalog number in one column, specify 'id= catalog number' and put the guid prefix in another column...)

and got the below (I suspect it's confused about the specimens GUID prefix being UAM:Ento and the loan prefix being KWP:Ento)

Query
Template: /tools/DataLoanBulkload.cfm:193
Execution Time: 0.687 ms
Record Count: 31
Cached: No
Lazy: No
SQL:
select * from cf_temp_data_loan_item
	key	guid_prefix	other_id_type	other_id_number	loan_number	collection_object_id	transaction_id	item_description	status
1	536329525	UAM:Ento	catalog number	409965	KWP.2017.001.Ento				loan not found
2	536329526	UAM:Ento	catalog number	411121	KWP.2017.001.Ento				loan not found
3	536329527	UAM:Ento	catalog number	415818	KWP.2017.001.Ento				loan not found
4	536329528	UAM:Ento	catalog number	422660	KWP.2017.001.Ento				loan not found
5	536329529	UAM:Ento	catalog number	422661	KWP.2017.001.Ento				loan not found
6	536329530	UAM:Ento	catalog number	444905	KWP.2017.001.Ento				loan not found
7	536329531	UAM:Ento	catalog number	444940	KWP.2017.001.Ento				loan not found
8	536329532	UAM:Ento	catalog number	445023	KWP.2017.001.Ento				loan not found
9	536329533	UAM:Ento	catalog number	461579	KWP.2017.001.Ento				loan not found
10	536329534	UAM:Ento	catalog number	461583	KWP.2017.001.Ento				loan not found
11	536329535	UAM:Ento	catalog number	461645	KWP.2017.001.Ento				loan not found
12	536329536	UAM:Ento	catalog number	461782	KWP.2017.001.Ento				loan not found
13	536329537	UAM:Ento	catalog number	461948	KWP.2017.001.Ento				loan not found
14	536329538	UAM:Ento	catalog number	461953	KWP.2017.001.Ento				loan not found
15	536329539	UAM:Ento	catalog number	461954	KWP.2017.001.Ento				loan not found
16	536329540	UAM:Ento	catalog number	461955	KWP.2017.001.Ento				loan not found
17	536329541	UAM:Ento	catalog number	462324	KWP.2017.001.Ento				loan not found
18	536329542	UAM:Ento	catalog number	462353	KWP.2017.001.Ento				loan not found
19	536329543	UAM:Ento	catalog number	462616	KWP.2017.001.Ento				loan not found
20	536329544	UAM:Ento	catalog number	463119	KWP.2017.001.Ento				loan not found
21	536329545	UAM:Ento	catalog number	463136	KWP.2017.001.Ento				loan not found
22	536329546	UAM:Ento	catalog number	463779	KWP.2017.001.Ento				loan not found
23	536329547	UAM:Ento	catalog number	463797	KWP.2017.001.Ento				loan not found
24	536329548	UAM:Ento	catalog number	463825	KWP.2017.001.Ento				loan not found
25	536329549	UAM:Ento	catalog number	465854	KWP.2017.001.Ento				loan not found
26	536329550	UAM:Ento	catalog number	466054	KWP.2017.001.Ento				loan not found
27	536329551	UAM:Ento	catalog number	466055	KWP.2017.001.Ento				loan not found
28	536329552	UAM:Ento	catalog number	466056	KWP.2017.001.Ento				loan not found
29	536329553	UAM:Ento	catalog number	466057	KWP.2017.001.Ento				loan not found
30	536329554	UAM:Ento	catalog number	466058	KWP.2017.001.Ento				loan not found
31	536329555	UAM:Ento	catalog number	466059	KWP.2017.001.Ento				loan not found
---------31------------- Something isn't happy. Check the status column in the above table, fix your data, and try again. 

High priority fix - need to get these into this loan so they are in this project:

https://arctos.database.museum/project/10002314

which I need to cite in a publication about to be submitted.

# Problem
**Community response to describe the problem that caused the error**

# Solution
**Community response with directions for how to correct the problem**

**Comment by DerekSikes** [comment]
I'm using GUIDs... what do you mean "trying to put parts into a loan which is typed to only carry catalog records." The data loan has 2000+ catalog records and I want to get 31 more in. HELP.

**Comment by DerekSikes** [comment]
That parts-into-data-loan error came from use of the 'add items to this loan' link on the data loan itself. If that link should not be used for data loans then it should not be on a data loan.

One solution might be to rebuild this project-data loan entirely in UAM:Ento? I'd prefer that be the case anyhow... but I'd still be waiting an unknown number of days for Lam to move the 5 KWP:Ento specimens into UAM:Ento, because 'security'

**Comment by DerekSikes** [comment]
Ok I'm going to try to rebuild this project in UAM:Ento but need some information.

Currently there are 2470 catalog records linked to this project:

https://arctos.database.museum/project/10002314

which is based on their being in a data loan in KWP:Ento

https://arctos.database.museum/Loan.cfm?action=editLoan&transaction_id=21112965

Here's my plan:

1) batch-unload all the records from the KWP loan
2) I made a data loan in UAM:Ento https://arctos.database.museum/Loan.cfm?Action=editLoan&transaction_id=21136815
and will then try to batch-load these to that.
3) I've already linked the UAM:Ento loan to the project
4) I'll then delete the empty KWP:Ento loan

??? will that work?

I'm really not clear on how dataloans and projects relate to one another (I see no way to unlink a data loan from a project, for example).

thanks

**Comment by Jegelewicz** [comment]
That sounds like a reasonable plan - maybe do the steps in this order:

1. batch-load these to data loan in UAM:Ento https://arctos.database.museum/Loan.cfm?Action=editLoan&transaction_id=21136815
2. batch-unload all the records from the KWP loan
3. then delete the empty KWP:Ento loan

This lets you confirm that the stuff in the new load is associated with the project before you remove the old loan.

**Comment by DerekSikes** [comment]
thanks!

can catalog records be in more than one data loan at the same time?

**Comment by Jegelewicz** [comment]
> can catalog records be in more than one data loan at the same time?

YES! Otherwise they wouldn't be super-useful. There is nothing to return, so a record can be included in an infinity of loans.

**Comment by dustymc** [comment]
done?
