### ISSUE TITLE
taxonomy flat gaps

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6336]
From @DerekSikes 

>The lack of a phylum for 1720 UAM:Ento records is a problem I'd like fixed because it'll cause failures of many key searches... how do we find & fix these?

This is from DWC-related conversation, and DWC taxonomy comes from FLAT.

Navigate to the Arctos directory and choose Taxonomy: Find Gaps

<img width="644" alt="Screenshot 2023-05-24 at 11 01 37 AM" src="https://github.com/ArctosDB/arctos/assets/5720791/74591154-47f1-4d41-86d9-c8cc993b6143">

Provide some data:

<img width="197" alt="Screenshot 2023-05-24 at 11 02 18 AM" src="https://github.com/ArctosDB/arctos/assets/5720791/8fba3a4a-a2a0-49ef-89de-6939313171d3">

Click the button and get answers.

<img width="875" alt="Screenshot 2023-05-24 at 11 02 50 AM" src="https://github.com/ArctosDB/arctos/assets/5720791/fd9dda00-f119-4b73-af89-197d7bbfbb99">

These are all straightforward, so the links to taxa work.

https://arctos.database.museum/name/Eucerotinae looks like...

<img width="519" alt="Screenshot 2023-05-24 at 11 03 10 AM" src="https://github.com/ArctosDB/arctos/assets/5720791/b78f00fb-453e-4fd0-91af-774ccb8b6132">

and https://arctos.database.museum/collection/UAM:Ento reveals that none of those Sources are preferred by the collection.

<img width="253" alt="Screenshot 2023-05-24 at 11 06 43 AM" src="https://github.com/ArctosDB/arctos/assets/5720791/f1701dcb-35f2-44e8-bf7e-62249b6984f0">

The solution to filling this gap - assuming the classification would have a term at the specified rank - would be to add a classification under a preferred Source, or to choose a Source which includes the desired data under manage collection.

**Comment by DerekSikes** [comment]
thanks!
