### ISSUE TITLE
Arctos Report Template Request: Shipping label 

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#6339]
this is a simple one-page PDF for shipping label

[MVZ_Shipping_Label.pdf](https://github.com/museum-of-vertebrate-zoology/MVZ-Data/files/11559278/MVZ_Shipping_Label.pdf)

Basically need a new SQL for loan transaction id, from address (inhouse contact name and address) and to address (shipped to name and address)

I cant find the previous prefunction but variables needed might look like these old ones (probably wrong!):
```
#getLoan.loan_number#
#replace(getLoan.shipped_to_address,chr(10),"
","all")#
#dateformat(now(),"dd mmmm yyyy")#```
and the inhouse contact name and address?

**Comment by dustymc** [comment]
See report loan_data_dump.

Edit any loan, click this


<img width="209" alt="Screenshot 2023-05-25 at 7 26 28 AM" src="https://github.com/ArctosDB/arctos/assets/5720791/3c8bef6d-ce0b-47a4-af4d-e609d79a16c3">

open that:

<img width="869" alt="Screenshot 2023-05-25 at 7 25 48 AM" src="https://github.com/ArctosDB/arctos/assets/5720791/f98f8238-a0bd-4247-8d40-1646a5dcb19a">
