### ISSUE TITLE
UI improvement: rename "Transarctos Unified Reporting Directive" tool

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#6342]
In case you didnt know, you can search on your records by the Arctos data quality report results -- handy!
"https://arctos.database.museum/Reports/cat_record_reports.cfm"

However the current name under Stats requires/invokes a little too much imagination and not enough specifics (also could be just me; seems to channel some Star trek vibes)

alternative name suggestions?
**Data Quality Reports by Collection**
others?

**Comment by dustymc** [comment]
I am emotionally attached to acronym.

<img width="351" alt="Screenshot 2023-05-25 at 10 10 30 AM" src="https://github.com/ArctosDB/arctos/assets/5720791/5b03bcb5-97b1-4e43-9a9d-961a62a88131">

**Comment by campmlc** [comment]
I like Data Quality Reports by Collection.

**Comment by mkoo** [comment]
> I am emotionally attached to acronym.

aha I had not noticed and now will be spending time thinking about that!
