### ISSUE TITLE
Feature Request - add issued by to simple identifiers in results

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6344]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

As we transition to issued by, this will be an important part of the identifiers.

**Describe what you're trying to accomplish** 
An clear and concise overview of the goals; why are you asking for this?

Here is how they look now

![image](https://github.com/ArctosDB/arctos/assets/5725767/645466d2-a898-463d-9ed5-97a9cb5a2a6d)

but the first one has an issuer

![image](https://github.com/ArctosDB/arctos/assets/5725767/14e170cc-4207-45a4-afe4-6849922b9462)

**Describe the solution you'd like**
How might we accomplish your goals?

simple identifier in results should be id_type issued_by value

**Describe alternatives you've considered**

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by dustymc** [comment]
That's coming from...


```

CREATE OR REPLACE FUNCTION concatotherid (p_key_val int ) RETURNS varchar LANGUAGE sql stable PARALLEL SAFE AS
$body$
 select 
 	string_agg(concat(other_id_type,'=',display_value),', ' order by other_id_type,display_value) 
 from 
 	coll_obj_other_id_num
 where 
 	coll_obj_other_id_num.ID_REFERENCES = 'self' and 
    collection_object_id = p_key_val;
$body$
;
 
```

No problem to change the function/concatenation, but it will take ~days of CPU to refresh so if possible to bundle with other flat stuff (#6111 possibly) that would be nice.

Suggestions regarding what the format should be?

assignedby-space-type-space-value  - "Carla Cicero collector number 12" ????

**Comment by Jegelewicz** [comment]
> Suggestions regarding what the format should be

type-space-value-"issued by"-space-**issued**by - "collector number 12 issued by Carla Cicero"

I like having the issued by close to the identifier - it gives the number more meaning than the type, especially for those identifiers that are simply "other identifier".

But honestly, I don't care as long as the issuer is included.

**Comment by dustymc** [comment]
>"issued by"

That seems overly verbose for this but I don't much care either.

Strong agree that the agent is more important than the type.

**Comment by Jegelewicz** [comment]
yep - see https://github.com/ArctosDB/data-migration/issues/1616#issuecomment-1563481354 for a good laugh!

**Comment by ewommack** [comment]
> eg "Carla Cicero collector number 12"

Would these be all in separate columns in a downloadable csv or the same column? I'm thinking about searching and working with the data. 

Also, how might this look if we want to see all of the collector numbers in a search results window? Not the data record page, but in the search list?

**Comment by Jegelewicz** [comment]
> Would these be all in separate columns in a downloadable csv or the same column? 

one column, concatenated if there is more than one identifier FROM SEARCH RESULTS (see below for getting them parsed out).

current view:

![image](https://github.com/ArctosDB/arctos/assets/5725767/704a44ce-a1f7-4a67-b076-2a5990c12361)

> how might this look if we want to see all of the collector numbers in a search results window? Not the data record page, but in the search list?

It doesn't - use the Identifier Table View on the search results tools.

<img width="960" alt="Screenshot 2023-06-05 13 16 25" src="https://github.com/ArctosDB/arctos/assets/5725767/f04080f6-ff5a-4b66-855c-2d4253234d15">

![image](https://github.com/ArctosDB/arctos/assets/5725767/d700180a-9085-4d72-ac5e-620a193b5690)
