### ISSUE TITLE
Agent Names that don't fit in our "rules"

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6346]
I'm getting an error that preferred agent names cannot have a space after a capital letter. However, I have an agent I'd like to add whose first name is "Thien-Y" so her preferred name is "Thien-Y Le". Is there a way to get around this, or a recommended way for handling this kind of name (e.g., enter her preferred name as "Thien-y Le" but then an aka as "Thien-Y Le"?

_Originally posted by @WaigePilson in https://github.com/ArctosDB/data-migration/issues/1545#issuecomment-1548274700_

**Comment by dustymc** [comment]
This rule exists to combat the constant stream of attempts to create

* S R Guy
* SR Guy

etc., and standardize on

* S. R. Guy

I think that there's no choice but to drop that constraint to accommodate a person's name, but it would be very good if we could somehow mitigate the possible problems by upping the bar on creation, cleaning up the old legacy messes, etc.

@ArctosDB/agents-committee

**Comment by Jegelewicz** [comment]
> cleaning up the old legacy messes, etc.

https://github.com/ArctosDB/arctos/issues/6340

**Comment by WaigePilson** [comment]
FYI I was able to add this agent (Thien-Y Le) manually no problem! So it's only an issue for bulkloading. And I agree with the sentiment that not allowing bulk loading of agents with no period after a capital letter makes sense so someone doesn't bulkload 500 agents e.g., S R Guy as you say!

**Comment by Jegelewicz** [comment]
@WaigePilson great! I'm going to close this issue.
