### ISSUE TITLE
Reciprocal Relationship Bot for within Institutions only

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#6348]
From the AWG meeting today, and referencing the following issue where creating reciprocal relationships may prove difficult when between multiple collections (https://github.com/ArctosDB/arctos/issues/6248).

AWG asked if it would be possible to create an Arctos bot that helped create reciprocal relationships, but only worked the collections present in one institution.

**Comment by dustymc** [comment]
I don't think this would be too technically challenging (although there's not really anything that might be called 'institution' in Arctos so it could be fragile around that), but I'm also not sure how much ROI might be available - periodically downloading the reciprocal file, removing what's not wanted, and feeding whatever's left to the loader doesn't seem like an overly burdensome task??

**Comment by ewommack** [comment]
What does ROI stand for?

**Comment by Jegelewicz** [comment]
Return on investment

**Comment by mkoo** [comment]
If ROI includes saving curatorial staff a mindless step then it's high!
otherwise we may have lots of unreciprocated relationships (and unrequited relations should stay in our romance books not arctos)-- technically this may need to work at the collection level which is functionally institutional since users should have some permission level access (yes?)

**Comment by dustymc** [comment]
>mindless

If that's involved, just turn the normal bot on?

>collection level 

That's more technically approachable, but it doesn't overlap with the initial ask.

I think this needs a use case to proceed - I'm really struggling to understand the space some new bot might occupy.

**Comment by ewommack** [comment]
@Nicole-Ridgwell-NMMNHS - use case?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I only just learned about the reciprocal relationship bot at the last meeting, and I followed the instruction for how to turn it on for our collection. What is the difference between this and that?

**Comment by Jegelewicz** [comment]
I would really like to encourage our community to allow this bit of automated collective curation as it currently exists! It saves time and energy and it is clear that the identifier/relationship is created by an automated bot.

![image](https://github.com/ArctosDB/arctos/assets/5725767/b03d5476-2e58-48f5-aafc-df12126d9a14)

There is no need to limit this to other collections at your institution - why do you trust that more than any other Arctos institution that might also be editing localities or taxonomy? The information is additive and you can always review and refute things by adding your own relationship - assigned by YOU. Log in, go to the BOT agent page - https://arctos.database.museum/agent/21344957 and see what identifiers it has assigned for you.

**Comment by dustymc** [comment]
There's no use case for this, tabling
