### ISSUE TITLE
Why am I seeing other collections' loan reminders in notifications?

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#6351]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
When I logged in today I can see loan reminders in my notifications. I should not be able to see them (nor do I want to! I have enough of my own to work thru!)

<img width="927" alt="Screenshot 2023-05-25 at 7 17 51 PM" src="https://github.com/ArctosDB/arctos/assets/17605945/20c085c6-9801-455c-a9d9-3d6163ca33e2">

I am not listed on the CC column either, so this seems to not make any sense. Is it a glitch in the Matrix?

**Comment by dustymc** [comment]
You are The Chosen One??

I'm pretty sure nobody has done anything crazy with some weird intersection of your username and their name. You're not a contact for the collection, you're not a loan contact, you haven't signed up to get a copy of everything.

I can't find any bugs in the code. I don't bother trying to sanitize the usernames for various reasons, which is the most likely place for something like this to slip through, but I'm sure that's not it.

My best guess is that someone accidentally did one of those things for some reason (eg, chose the wrong agent somewhere), then noticed and un-did it about the time notifications were running, but that's really not all that convincing either.

If it's not that then until/unless some other clue exposes itself - glitch in the matrix it is....
