### ISSUE TITLE
Feature Request - identifiers and "checkfreetext"

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6352]
**Is your feature request related to a problem? Please describe.**

In https://github.com/ArctosDB/arctos/issues/6350, I noticed some Unicode "I have no idea what you mean" characters. We have not applied any text control to the table because those can be legitimate - GAN may truly have issued ``MIG12-23431334�`` and  encoded it into PIT tags and giraffe collars and etc., and if they have then blocking that from Arctos would be plain wrong. The world doesn't always work the way we wished it did, sillier things have happened.

**Describe what you're trying to accomplish** 

For now, find data that's potentially in need of help.

Eventually, possibly some sort of report, control, whatever's appropriate.

**Describe the solution you'd like**

First and foremost, https://github.com/ArctosDB/arctos/issues/6163 - there are mangled links under every flipped rock, including this one. I don't see how moving away from that system is in any way controversial, but it seems to be.

Otherwise - whatever the data allow??

**Describe alternatives you've considered**

There are none, there are demonstrably broken data in here.

**Additional context**

https://github.com/ArctosDB/arctos/issues/5771

In the CSV below, column "REPLACEDWITHBRACKETX" should have prohibited-elsewhere characters replaced by ``[X]``. Some rows do not have that, in which case the problem is almost certainly leading or trailing spaces (which absolutely must be accommodated in order to have a numeric/sortable component with identifier "ABC 123 XYZ" - but if here all of those pieces aren't there, and it's probably more like 'ABC{space}').

Please let me know if I can provide some other form, clean something up, or help in any other way.

**Priority**

I'd be panicking if they were my data....

-----------------

Data:

[temp_id_funkychars.csv.zip](https://github.com/ArctosDB/arctos/files/11576537/temp_id_funkychars.csv.zip)

Summary:

```

  guid_prefix  | numrecs 
---------------+---------
 ACUNHC:Bird   |       1
 ACUNHC:Fish   |       3
 ACUNHC:Herp   |       2
 ACUNHC:Inv    |       8
 ALMNH:Inv     |     216
 ALMNH:Mamm    |       3
 ALMNH:Paleo   |       1
 APSU:Herp     |    8213
 ASNHC:Herp    |       1
 ASNHC:Mamm    |       4
 ASUMZ:Bivalve |      10
 BYU:Herp      |      69
 BYU:Mamm      |    6808
 CHAS:Egg      |       2
 CHAS:Herb     |       1
 CHAS:Herp     |       1
 CRCM:Bird     |       2
 DMNS:Bird     |       4
 DMNS:Egg      |      14
 DMNS:Inv      |      17
 DMNS:Mamm     |      42
 DMNS:Para     |       8
 HWML:Para     |     117
 JSNM:Egg      |       2
 KNWR:Ento     |       4
 MSB:Bird      |      23
 MSB:Herp      |      33
 MSB:Host      |      65
 MSB:Mamm      |    1208
 MSB:Para      |      40
 MVZ:Bird      |      23
 MVZ:Herp      |      15
 MVZ:Mamm      |      61
 NMMNH:Bird    |       1
 NMMNH:Paleo   |       1
 NMU:Mamm      |       1
 OWU:Bird      |       2
 UAM:Arc       |    4542
 UAM:Art       |      40
 UAMb:Herb     |    1670
 UAM:Bird      |       1
 UAM:EH        |      28
 UAM:Ento      |      27
 UAM:ES        |      69
 UAM:Fish      |       6
 UAM:Herb      |    1908
 UAM:Inv       |      58
 UAM:Mamm      |     130
 UAMObs:Ento   |      44
 UCM:Egg       |       4
 UCM:Herp      |     668
 UCM:Mamm      |       6
 UMNH:Bird     |       1
 UMNH:Mamm     |      42
 UNM:MET       |       2
 UNR:Bird      |       2
 USNPC:Para    |      22
 UTEP:Ento     |      26
 UTEP:Herb     |      13
 UTEP:Herp     |      55
 UTEP:HerpOS   |       2
 UTEP:Inv      |       8
 UWBM:Herp     |       2
 UWBM:Mamm     |      53
 UWYMV:Bird    |       2
 UWYMV:Mamm    |      10
 WNMU:Mamm     |       1
```

Likely broken links:

```

arctosprod@arctos>> select guid_prefix,other_id_type,count(*) from  temp_id_funkychars where link_value is not null  group by guid_prefix,other_id_type  order by guid_prefix,other_id_type;
 guid_prefix |  other_id_type  | count 
-------------+-----------------+-------
 DMNS:Bird   | DMNS:Para       |     2
 DMNS:Mamm   | BoLD Process ID |     2
 DMNS:Mamm   | DMNS:Mamm       |     1
 DMNS:Mamm   | GenBank         |     1
 DMNS:Mamm   | MSB:Mamm        |     1
 DMNS:Para   | GenBank         |     1
 KNWR:Ento   | UAM:Ento        |     4
 MSB:Host    | GenBank         |     2
 MSB:Host    | MSB:Host        |     4
 MSB:Mamm    | DMNS:Mamm       |     6
 MSB:Mamm    | GenBank         |   290
 MSB:Mamm    | MSB:Host        |     2
 MSB:Mamm    | MSB:Para        |     1
 MSB:Para    | BoLD Process ID |     2
 MSB:Para    | GenBank         |     5
 MSB:Para    | MSB:Mamm        |     2
 MSB:Para    | UAM:Mamm        |     1
 MVZ:Herp    | GenBank         |     3
 MVZ:Mamm    | GenBank         |     3
 UAM:Art     | UAM:Art         |    13
 UAM:Art     | UAM:EH          |    26
 UAM:EH      | UAM:Art         |    20
 UAM:Ento    | UAMObs:Ento     |     1
 UAM:Mamm    | GenBank         |    81
 UAM:Mamm    | NCBI Biosample  |    21
 UCM:Mamm    | GenBank         |     2
 UCM:Mamm    | UCM:Mamm        |     2
 UTEP:Herb   | GenBank         |     1
 UTEP:Herp   | GenBank         |     1
 UWBM:Mamm   | GenBank         |     1
(30 rows)
```

Users:

 @ebraker
 @Nicole-Ridgwell-NMMNHS
 @mkoo
 @AJLinn
 @campmlc
 @ccicero
 @amgunderson
 @DerekSikes
 @atrox10
 @mvzhuang
 @cjconroy
 @makaylaeasley
 @jtgiermakowski
 @wellerjes
 @keg34
 @jebrad
 @babogan
 @gradyjt
 @jrpletch
 @AdrienneRaniszewski
 @aklompma
 @acdoll
 @jldunnum
 @jrdemboski
 @genevieve-anderegg
 @msbparasites
 @byuherpetology
 @mlbowser
 @jessicatir
 @ewommack
 @kderieg322079
 @sharpphyl
 @StefanieBond
 @catherpes
 @marecaguthrie
 @gracz-UNL
 @sjshirar
 @lin-fred
 @Jegelewicz
 @kmkocot
 @jandreslopez
 @droberts49

**Comment by Jegelewicz** [comment]
@dustymc do we need to clean these up? If so, How can I find them?

**Comment by dustymc** [comment]
>do we need to clean these up?

I can't know, hence this issue.

>How can I find them?

```
select
    guid_prefix,
    guid,
    other_id_type,
    display_value,
    other_id_prefix,
    other_id_number,
    other_id_suffix,
    link_value,
    id_references,
    getPreferredAgentName(assigned_agent_id) assignedby,
    getPreferredAgentName(issued_by_agent_id) issuedby,
    coll_obj_other_id_num.remarks,
    replacefreetext(display_value,'[X]') as replacedwithbracketx
from
    coll_obj_other_id_num
    inner join flat on coll_obj_other_id_num.collection_object_id=flat.collection_object_id
where
    checkfreetext(display_value) is false
```

**Comment by Jegelewicz** [comment]
I am reopening and assigning to me to investigate the stuff that I can.

**Comment by ebraker** [comment]
@dustymc - fine to proceed with UCM records

**Comment by acdoll** [comment]
We should be able to clean up the DMNS ones pretty quickly

**Comment by Jegelewicz** [comment]
ALMNH:Inv can you just remove all of the trailing spaces for me?

**Comment by Jegelewicz** [comment]
ACUNHC all cleaned up

**Comment by Jegelewicz** [comment]
ALMNH:Mamm and ALMNH:Paleo cleaned up

**Comment by Jegelewicz** [comment]
APSU:Herp - can you remove the leading spaces for me?

**Comment by campmlc** [comment]
For MSB collections, please remove any leading or trailing spaces @Jegelewicz @dustymc and can you let me know what's left after that? GAN numbers definitely should not have anything weird embedded, but I'd need to look at them to see what happened.

**Comment by Jegelewicz** [comment]
ASUMZ:Bivalve cleaned up

**Comment by Jegelewicz** [comment]
BYU - please remove all leading and trailing spaces

**Comment by Jegelewicz** [comment]
CRCM all cleaned up

**Comment by Jegelewicz** [comment]
JSNM all cleaned up

**Comment by Jegelewicz** [comment]
NMU:Mamm cleaned up

**Comment by babogan** [comment]
@kmkocot - seems something went wrong with one of your bulkloads maybe? 
Teresa, thanks for cleaning up the other two collections!

**Comment by Jegelewicz** [comment]
OWU:Bird cleaned up

**Comment by Jegelewicz** [comment]
@dustymc would it be possible to remove ALL leading and trailing spaces? That would clean up most of this, then we can deal with the rest.

**Comment by dustymc** [comment]
>remove ALL leading and trailing spaces? 

Do you mean technically possible, or somehow knowing that doing so isn't mangling identifiers?

I can do the former, and the point of this issue is asking if that's problematic when it intersects with reality (eg is the latter how identifiers work or just messy data?). If we can establish rules then I can clean data to comply with those rules. (And if we can't the cleanup probably isn't going to last.) So - rules? Can we just apply checkfreetext to the assembled value, perhaps? ???

**Comment by cjconroy** [comment]
I'm confused on what to do here. I opened the file and looked up the MVZ mammal records. The spreadsheet shows we had an issued by Museu de Zoologia Da Universidade de Sao Paulo. There is no value. This is what we did when we knew specimens were accessioned there, but no idea what number they were given. 
In Arctos, there is nothing under otherID. This seems to have been wiped out. Some others too like Kunming Institute of Zoology. How can we fix? And please don't delete our data!

**Comment by Jegelewicz** [comment]
Rules for identifiers should include

1. no leading spaces
2. no trailing spaces
3. no sequential spaces

**Comment by jldunnum** [comment]
Probably lots of legacy identifiers with collector or preparator then a space then the number

______________________________________________________________
Jonathan L. Dunnum Ph.D. (he, him, his)
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

Chair, Systematic Collections Committee, American Society of Mammalogists
Latin American Fellowship Committee, ASM

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131

**Comment by jldunnum** [comment]
OK good

______________________________________________________________
Jonathan L. Dunnum Ph.D. (he, him, his)
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

Chair, Systematic Collections Committee, American Society of Mammalogists
Latin American Fellowship Committee, ASM

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131

**Comment by Jegelewicz** [comment]
ALMNH:Inv have been fixed

**Comment by Cpittman53** [comment]
Hi, I was working on cleaning up the DMNS identifier issues by using the Bulk Unload and Bulkloader. When using the Identifier Bulkloader, I was not able to upload the Prefix/Suffix values due to the required and conditional fields. Is this something that could be considered and should I file a separate issue for this feature?

**Comment by Jegelewicz** [comment]
SOOOO - the results of the WriteSQL put "unknown" in issued by, but actually issued by is blank for the ALMNH:Inv problem children. No bueno. Now I have to re-do everything....

**Comment by kmkocot** [comment]
Sorry for the mess. I've tried to follow this thread and the one linked to in the first post but I'm not understanding. When time permits if someone could briefly explain what I did wrong (leave trailing spaces in one or more fields on the specimen or parts bulkloader?), that would be really helpful. Thanks and sorry!

**Comment by babogan** [comment]
@kmkocot to my understanding it's either nonprinting characters (usually the collections with one or two) or trailing/leading spaces (prob what happened with yours)
I believe Teresa is fixing them for us! I also went through the excel file and am confused but before I had a chance to ask it was already fixed.
You rock Teresa!

**Comment by kmkocot** [comment]
#

>You rock Teresa!

Agreed! Thank you @Jegelewicz!

**Comment by Jegelewicz** [comment]
@kmkocot @babogan these are all issues in other identifiers where there is either a leading or trailing space. When you are bulkloading stuff you often can't see these in Excel and they load into Arctos fine (so maybe we need triggers that catch them before they get loaded, which is what I am suggesting in https://github.com/ArctosDB/arctos/issues/6352#issuecomment-1691970376). One way to eliminate this is to use the TRIM function on everything in Excel when preparing a bulkload file. Admittedly, I know this, but often fail to do it because it just requires more processing power in Excel when building a bulkload. If Arctos could tell me when I try to load that it is a problem, I can fix them before they become a problem....

Anyhoo - I am working to get all of these fixed - it might take me to the end of the day because I have lots of meeting today. Woohoo!

**Comment by babogan** [comment]
Teresa,
Ah! I have been using the Excel magic trick since ARCTOS was so angry with me and not allowing my bulkloads to come in because of trailing spaces!

**Comment by campmlc** [comment]
Absolutely support triggers to catch these prior to load - ideally that automatically do the TRIM as I can't see any use case where the leading, trailing, or double+ spaces are anything other than an entry error.[https://github.com/ArctosDB/arctos/issues/6352#issuecomment-1691970376](url)

**Comment by babogan** [comment]
For me it seemed to call them "nonprinting characters" and error me out when I attempted bulkloads. I assume the spaces were the issue because the TRIM was all it took to get my entries up...

**Comment by Jegelewicz** [comment]
Yep - leading, trailing and multiple consecutive spaces are all "nonprinting characters"!

**Comment by mkoo** [comment]
I'm working on MVZ's -- it highlighted another issue so let me see if I can bulkload or I'll ask for Dusty's touch

**Comment by Jegelewicz** [comment]
UWBM:Mamm all cleaned up

**Comment by Jegelewicz** [comment]
UTEP:Ento cleaned up

**Comment by Jegelewicz** [comment]
UTEP:Herb cleaned up

**Comment by Jegelewicz** [comment]
UTEP:Inv cleaned up

**Comment by Jegelewicz** [comment]
UTEP:Herp cleaned up

**Comment by Jegelewicz** [comment]
USNPC:Para all cleaned - all were trailing spaces on collector number.

**Comment by Jegelewicz** [comment]
UNM:MET cleaned up

**Comment by Jegelewicz** [comment]
UMNH all cleaned up

**Comment by mkoo** [comment]
@Jegelewicz have you used the bulkloader for these?
how long does it take to appear? I loaded 1 via the bulkloader as a test and it still hasnt appeared (I set to autoload before my 4 pm meeting!)
Also I assume these are append operations since many of these records already have identifiers... just wondering your MO

**Comment by dustymc** [comment]
>how long

https://arctos.database.museum/info/component_loader_status.cfm

**Comment by mkoo** [comment]
well sure but I'm not going to bump someone else's job! (thx; helpful link)

**Comment by AJLinn** [comment]
UAM:EH are cleaned up.

**Comment by wellerjes** [comment]
CHAS records are cleaned up.

**Comment by Cpittman53** [comment]
DMNS records are cleaned up.

**Comment by dustymc** [comment]
>leading, trailing, or consecutive spaces in an indentifier which was used to autocreate a url,

I cleaned those up - there were a bunch of duplicates (I think some 3-way even - space and encoded space and intended value). Possibly worth noting that those would have been silently broken in the old fragment system.

Then there were a bunch with leading and trailing spaces, and in them a bunch of duplicates (so possibly 4-way duplicates in the previous batch - or more if there were multiple spaces involved). 

That leaves about 2100 URIs with spaces. I think all of these are just mis-typed (anyone mention anything about not being very fond of the partial identifier system yet?) - I'm happy to help clean them up, but I'll need some guidance.

[temp_uri_space.csv.zip](https://github.com/ArctosDB/arctos/files/12441071/temp_uri_space.csv.zip)

**Comment by Jegelewicz** [comment]
These all seem new? why weren't they in the original list?

**Comment by dustymc** [comment]
> why weren't they in the original list?

Either they don't violate checkfreetext or they've been added since it was run.

**Comment by Jegelewicz** [comment]
All of the UTEP:ES ones are not urls and it seems like the "http://arctos.database.museum/guid/UTEP:ES:" was somehow appended there? 

Last Edited By: DBA on 2023-08-03?

**Comment by dustymc** [comment]
Yes, same situation we dealt with for nearly everything - people don't read documentation and pick inappropriate types. The only thing that's changed is the problems are obvious now, while before they were only noticeable in UIs where the full type had been assembled.

**Comment by Jegelewicz** [comment]
I cleaned up the UWBM and MSB except for this one because I am not sure what is going on - https://arctos.database.museum/guid/MSB:Fish:98720

**Comment by dustymc** [comment]
I replaced a bunch of doublespaces and leading prefix spaces and trailing suffix spaces, here's what's left:

[temp_id_funkychars(1).csv](https://github.com/ArctosDB/arctos/files/12441828/temp_id_funkychars.1.csv)

**Comment by Jegelewicz** [comment]
I think I have cleaned everything I can. But I am wondering about the duplicates. Can we also clean those up? Some of them happened because I was bulklo-unloading and loading when you cleaned everything for spaces. I cleaned up ALMNH:Inv and APSU:Herp duplicates - are there any others?

**Comment by Jegelewicz** [comment]
@dustymc FWIW the identifier loader will totally load exact duplicates - that really shouldn't be allowed?

**Comment by dustymc** [comment]
>cannot do anything about the rest of them.

I guess I will then? We're right next to what looks like a solution to a significant problem, I don't think there's any way to justify stopping here.

> exact duplicates 

Show me....

```

arctosprod@arctos>> \d coll_obj_other_id_num
                                             Table "core.coll_obj_other_id_num"
          Column          |          Type          | Collation | Nullable |                     Default                      
--------------------------+------------------------+-----------+----------+--------------------------------------------------
 collection_object_id     | integer                |           | not null | 
 other_id_type            | character varying(59)  |           | not null | 
 other_id_prefix          | character varying(255) |           |          | 
 other_id_number          | numeric                |           |          | 
 other_id_suffix          | character varying(60)  |           |          | 
 display_value            | character varying(255) |           | not null | 
 coll_obj_other_id_num_id | integer                |           | not null | nextval('sq_coll_obj_other_id_num_id'::regclass)
 id_references            | character varying(60)  |           | not null | 'self'::character varying
 tempref                  | character varying(255) |           |          | 
 assigned_agent_id        | integer                |           |          | getagentidfromlogin(SESSION_USER::text)
 assigned_date            | date                   |           |          | CURRENT_DATE
 link_value               | character varying      |           |          | 
 issued_by_agent_id       | integer                |           |          | 
 remarks                  | character varying      |           |          | 
Indexes:
    "coll_obj_other_id_num_pkey" PRIMARY KEY, btree (coll_obj_other_id_num_id)
    "iu_oidnum_id_typ_disp_refs" UNIQUE, btree (collection_object_id, other_id_type, display_value, id_references, issued_by_agent_id)
    "ix_coll_obj_other_id_num_assigned_agent_id" btree (assigned_agent_id)
    "ix_coll_obj_other_id_num_issued_by_agent_id" btree (issued_by_agent_id)
    "ix_coll_obj_other_id_num_other_id_number" btree (other_id_number)
    "ix_collobjoidn_coid" btree (collection_object_id)
    "ix_collobjoidn_display" btree (display_value)
    "ix_collobjoidn_type" btree (other_id_type)
    "ix_tg_flat_coll_obj_other_id_num_displayvalue" gin (display_value gin_trgm_ops)
    "ix_tg_flat_coll_obj_other_id_num_other_id_type" gin (other_id_type gin_trgm_ops)
    "ix_upper_display_value" btree (upper(display_value::text))
Check constraints:
    "coll_obj_other_id_num_remarks_check" CHECK (checkfreetext(remarks))
Foreign-key constraints:
    "coll_obj_other_id_num_assigned_agent_id_fkey" FOREIGN KEY (assigned_agent_id) REFERENCES agent(agent_id)
    "coll_obj_other_id_num_issued_by_agent_id_fkey" FOREIGN KEY (issued_by_agent_id) REFERENCES agent(agent_id)
    "fk_collobjconthist_ctcoidtype" FOREIGN KEY (other_id_type) REFERENCES ctcoll_other_id_type(other_id_type)
    "fk_collobjconthist_ctidref" FOREIGN KEY (id_references) REFERENCES ctid_references(id_references)
Triggers:
    coll_obj_data_check BEFORE INSERT OR UPDATE ON coll_obj_other_id_num FOR EACH ROW EXECUTE FUNCTION trigger_fct_coll_obj_data_check()
    coll_obj_disp_val BEFORE INSERT OR UPDATE ON coll_obj_other_id_num FOR EACH ROW EXECUTE FUNCTION trigger_fct_coll_obj_disp_val()
    tr_collobjoidnum_aiud_flat AFTER INSERT OR DELETE OR UPDATE ON coll_obj_other_id_num FOR EACH ROW EXECUTE FUNCTION trigger_fct_tr_collobjoidnum_aiud_flat()

```

**Comment by dustymc** [comment]
>these duplicates?

Oh - neat, thanks, and that explains @Jegelewicz 's observation.

The bad news is, there are probably lots of these and it would be difficult to prevent them at the moment because postgres has weird handling of NULL (compared to Oracle, anyway), which the unique index spans.

The good news is, PG15 introduces NULLS NOT DISTINCT and so this should be trivial next week. The 45 linked above still need human intervention (and I'll still do something if nobody else does), the rest I'll revisit when I have more superpowers. I should be able to losslessly magick them and then prevent reoccurrence, I'll post here if that turns out not to be true.

**Comment by dustymc** [comment]
done
