### ISSUE TITLE
Feature Request - Go to Component Loader Status from Component Loader pages

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6354]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

When it is taking a while for stuff in a component loader to load, people get frustrated. We have a tool to check the status of the component loaders, but few people realize it and it takes quite a few clicks to get over there from the Tools Directory.

**Describe what you're trying to accomplish** 
An clear and concise overview of the goals; why are you asking for this?

Make it easier for people to check the status of and manage a component loader.

**Describe the solution you'd like**
How might we accomplish your goals?

A button on every component loader that says "View and manage component loader status" that takes you directly to https://arctos.database.museum/info/component_loader_status.cfm

**Describe alternatives you've considered**

Keep answering issues about component loaders taking too long and keep clicking three times to get to the status tool.

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by dustymc** [comment]
Been there for at least a couple versions, file an Issue (or check/prioritize arctos-dev) if you need something specific modernized.

<img width="1544" alt="Screenshot 2023-05-26 at 9 05 36 AM" src="https://github.com/ArctosDB/arctos/assets/5720791/2557b816-e89a-46ff-b4bf-a24479464f7b">
