### ISSUE TITLE
UI request: Link to "advanced Agent Search" in Tools Directory

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#6360]
Any reason why we cannot make the Agent Search link in the Tools Directory/Agents&Users panel go to this page?
https://arctos.database.museum/agents.cfm?agent_id=#

This is where we have all the fun fields! We can call this "Agent Advanced Search"

Seems easy to do so I am suspicious that I am missing a problem here... let me know @dustymc @Jegelewicz

**Comment by Jegelewicz** [comment]
This was moved to a discussion - https://github.com/ArctosDB/arctos/discussions/5373

**Comment by mkoo** [comment]
Saw the discussion-- not sure the issue is the same as the discussion (I assumed it was for the public search page?) We have a pretty good agent search page (linked above) for managers; now we just need to add to the Tools Directory.

**Comment by Jegelewicz** [comment]
> now we just need to add to the Tools Directory

That is the link at [Agents: Manage](https://arctos.database.museum/agents.cfm)?

**Comment by mkoo** [comment]
Oh there's my issue all solved! thx!
