### ISSUE TITLE
Feature Request - add parent/child relationships to part component loader

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6363]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

**Describe what you're trying to accomplish** 
An clear and concise overview of the goals; why are you asking for this?

I am entering new data that includes tissues and extracted DNA and would like to indicate which tissue the DNA was extracted from during data entry.

**Describe the solution you'd like**
How might we accomplish your goals?

Ability to create the parent/child relationship between parts during data entry.

**Describe alternatives you've considered**

Making the relationships after the parts are loaded either manually or with a bulkloader.

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by dustymc** [comment]
I'm not sure this should be in normal entry, it feels like a "1%" thing. 

It could be relatively easily accommodated in the part loader, however - maybe by a 'temporary_id' and 'temporary_parent_id' column. Is that satisfactory?

**Comment by Jegelewicz** [comment]
> It could be relatively easily accommodated in the part loader, however - maybe by a 'temporary_id' and 'temporary_parent_id' column. Is that satisfactory?

Yes, that would work for what I am doing!

**Comment by dustymc** [comment]
I'm struggling to make this work.

Counting on things ending up in any particular order is, at best, fragile - I don't think that's viable.

We could perhaps add a relative_load_order (so the user can specify that the parent loads, then the child, then the child's child) but that's getting complicated. (And I suppose would prioritize data using this, but that's probably OK.)

Loading things without a parent and then looping back around for those with would mean this is only one-layer capable, which doesn't seem workable (even for OGL).

I always have to deal with the possibility that a row loads, then the loader spends a week elsewhere, then the next row loads, so I can't use anything even semi-volatile.

The best solution I can come up with is to use nontemporary part identifier [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecpart_attribute_type#part_identifier) (and maybe add an unloader), but those aren't necessarily unique so even that's a bit more fragile than I'd like. And it might take several tries - with a week between them at the moment - to get things in the right order, which probably isn't great UX for importing a collection.

How can this be made to work?

**Comment by Jegelewicz** [comment]
If I can load all of the parents, then get a download of something that has:

GUID | part_ID | partname

And have the ability to add "parent part ID" when I load the children, that would probably accomplish what I need.

I will probably (hopefully) have barcodes on the parent parts, so maybe you don't need to do anything. When I get to that point, if it is still a problem, I'll come back to this.

**Comment by Jegelewicz** [comment]
Using parent barcodes worked for me. Closing.
