### ISSUE TITLE
UMZM Collections header image for /images/header/

### ISSUE THREAD

**Issue by adhornsby** [ArctosDB/arctos#6367]
It's a png with clear background so I assume it will show correctly against the UMZM maroon headers...  Thanks!

![UMZM_mini_clear_130pxtall](https://github.com/ArctosDB/arctos/assets/40217539/ba3cd26b-c7f1-4c39-aece-8c2137fc1577)

**Comment by dustymc** [comment]
I moved this to images/header/umzm_header_image.png (available from test now, production in next release) and edited a collection to use it: https://arctos-test.tacc.utexas.edu/collection/UMZM:Mamm

**Comment by mkoo** [comment]
thanks! I like your logo BTW @adhornsby 
I think the background needs to be this #70002E (got this from your homepage). Should the lettering be white?
I can give this a try tomorrow after i get into test server....

**Comment by mkoo** [comment]
gentle reminder to add logo to prod and their collection management @dustymc gracias!

**Comment by dustymc** [comment]
The logo did go out with last release.

I don't have access to all of the collections, but I updated the two I do can.

**Comment by mkoo** [comment]
Thanks! I think it looks gorgeous on prod @adhornsby @dustymc 

![Firefox_Screenshot_2023-06-03T18-12-42 779Z](https://github.com/ArctosDB/arctos/assets/2523089/87f444dc-ae35-4b01-a2da-901f0cc03a87)

Those values in Manage Collection can be copied over to the rest of the collections in your care
