### ISSUE TITLE
Weird zoomed output view on "View attached items" from loan transaction

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#6369]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
When I move from the standard loan form view:
<img width="1446" alt="Screenshot 2023-05-30 at 1 28 02 PM" src="https://github.com/ArctosDB/arctos/assets/17605945/b3831fa0-6907-4056-97dd-4c06d7baf67a">

to the "View attached items" page:
<img width="1446" alt="Screenshot 2023-05-30 at 1 28 13 PM" src="https://github.com/ArctosDB/arctos/assets/17605945/f665e11f-0735-4365-ad9f-f2fc1be0c724">

the output is strangely zoomed MUCH larger. This seems to be a bug as it occurs across various browsers and machines.

**Expected behavior**
I expect the relative scale of all the pages I'm working in to be relatively similar so I'm not having to expand my browser window and reduce the zoom (in this case to 70% normal or more to see the full width of output columns on my 24" desktop screen).

**Data**
Not sure if these links will work for you but these are the two pages I captured above:
https://arctos.database.museum/Loan.cfm?action=editLoan&transaction_id=21136255
https://arctos.database.museum/loanItemReview.cfm?transaction_id=21136255

**Priority**
Medium priority - an inconvenience considering I don't do hundreds of loans each year. But for those 27 I've made so far this year, it's annoying!

**Comment by dustymc** [comment]
very tentatively merging with https://github.com/ArctosDB/arctos/issues/6289 / https://github.com/ArctosDB/arctos/issues/6288 - that's an obsolete library with a very limited future.
