### ISSUE TITLE
Higher Geography reassignment to "United States, Alaska"

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#6370]
I maintain a checklist of the nonmarine arthropods of Alaska. I was thus surprised to see that this specimen:

https://arctos.database.museum/guid/UAMObs:Ento:228570#

which was collected on St. Matthew Island, in Alaska, has had its higher geography changed from:

North America, Bering Sea, United States, Alaska, Saint Matthew Island 
to
North Pacific Ocean, Bering Sea

Thus, it is no longer in our list of Alaskan species!!!!!! Unacceptable.

This makes me not just mildly furious but also curious how many other records have had their state lost from their higher geography???

Please reverse for this and any other records that have lost their state. (I could clone the locality, fix it, and reassign all my records to it but why should I spend my time fixing this problem? And how many other of my records are involved in this?)

There are a bunch of MVZ vertebrates in that locality too.

**Comment by DerekSikes** [comment]
btw, I'm reviewing species occurrence records for the USFWS for their National Wildlife Refuges in Alaska so this data corruption is interfering with work.

Priority = high

**Comment by Jegelewicz** [comment]
@DerekSikes This was planned as part of our conversion to the spatial higher geography in GADM. It would help if you could let us know what geography should be used for the island so that we can gather the appropriate localities and reassign them. I am sorry that I can't point to the GADM issue, but I am currently in sessions at SPNHC.

**Comment by DerekSikes** [comment]
the original higher geo before the change would be appropriate: North America, Bering Sea, United States, Alaska, Saint Matthew Island

But more importantly, as stated, if any localities that had included the state name Alaska in them were changed to no longer include the state name Alaska.. those should be found and reversed to include their state name.

In general, no locality should have its political place names removed! This island belongs to the United States and to Alaska. To remove those names from the higher geo is unacceptable & I worry about how many other records have been affected?

**Comment by ewommack** [comment]
I think this is the GADM issue: https://github.com/ArctosDB/arctos/issues/5138

**Comment by mkoo** [comment]
weighing in late here-- yes the easy thing is to assign your locality to "United States: Alaska" which is authority-based and fine. I think this farflung island just didnt get assigned properly. As a matter of future saerches and discovery, Bering Sea can be added as a locality attribute. Both can be done programmatically. If that's a workable solution then I can file as issue to review all islands actually.

**Comment by DerekSikes** [comment]
My real concern is how many other locality records that had had a state/province now longer have one? Is there a way to search to see?

I'll clone & fix this issue for this one but it really seems like a 'how could this have happened & if it happened to one, how many more?' kind of emergency to fix.

**Comment by DerekSikes** [comment]
Actually, it would be easier to just edit the locality itself - but there are about 40 MVZ records linked to it. I will edit to add state & country & if MVZ doesn't want that they can make a clone to have a locality without a state/country

**Comment by DerekSikes** [comment]
Seems there is no higher geography that has:

North America, Bering Sea, United States, Alaska,

so I just dropped it down to United States, Alaska

https://arctos.database.museum/editLocality.cfm?locality_id=10026588

**Comment by mkoo** [comment]
That works! (and what I suggest too)
Yes, higher geography is created from an authority now so the combo "North America, Bering Sea, United States, Alaska" is no longer but  "United States, Alaska" is because it also has a spatial representation and comes from GADM.org. 

I'll let you close this issue  (or tell me it's ok) and I will file another one about checking islands and their administration. The original data is still all there as an attribute.

Another question I have is how you would like to search? If via by a spatial search, St Matthew site would appear. If as a term search in the state field we could probably do better than simply by h.g.

**Comment by DerekSikes** [comment]
The most important search I do, and how this issue arose, is https://arctos.database.museum/record_summary.cfm?guid_prefix=KNWR:Ento,KNWR:Inv,KWP:Ento,UAA:Ento,UAM:Ento,UAMObs:Ento&phylum=Arthropoda&state_prov=Alaska&result_columns=phylum,phylclass,phylorder,suborder,superfamily,family,subfamily,tribe,subtribe,genus,species

which as you can see includes state = Alaska and produces a taxon summary list for the state. Thus, my consternation that suddenly all these 100+ St. Matthew records were not being found because the island had no state designation.

**Comment by DerekSikes** [comment]
Before I close I'd like to know how many other localities (I really only care about AK ones but I expect others would care about other states) have had their state vanish? Re: Alaska this is super important for me to know. Was this locality the only one to lose its state & country, or are there others?

**Comment by cjconroy** [comment]
I would like to continue to see our Alaska specimens in a query for Alaska. 
See attached maps. One is for a bounding box around most of Alaska. The other is with the word Alaska in the search. Arrows indicate the differences. 

![Alaska](https://github.com/ArctosDB/arctos/assets/5749672/8b288281-3f6c-4873-8358-81f664aad2f0)
![Alaska bounding box](https://github.com/ArctosDB/arctos/assets/5749672/c9a78c61-807a-45b7-9c3e-6bb2416af2ae)

**Comment by cjconroy** [comment]
So, to correct this, each collection needs to do the comparisons and go in and fix them by swapping the higher geography over to a term that includes Alaska?

**Comment by DerekSikes** [comment]
Looks like the following Alaska localities have also lost their state:
16890
10201946
10201947
10201948
10201949
10201950
10202355
10202356
10202357
10202358
10326481
10326502
10456601
10456602
10456603
10458787
10458788
10458790
10458791
10458792
10458793
10458794
10458795
10458796
10458797
10458800
10470233
10475870
10475871
10475872
10475873
10475875
10475876
10475877
10475961
10475963
10475964

I'd rather not have to fix these all myself manually. Dusty???

**Comment by mkoo** [comment]
This is now a job for @dustymc !
He can do this directly and I just had a chat with him about this. Thanks for sharing the list of loc_IDs @DerekSikes

**Comment by DerekSikes** [comment]
Note that I got that list by doing a polygon-map search in the Bering Sea to find catalog records in the collections I manage. This is a far from complete list given such a search. To get all localities that need fixing would require finding all localities that have a place name = to a state or province in the most recent history that is missing from the current higher geo.

**Comment by dustymc** [comment]
I'm unclear on the scope of this.

Here's a summary from the IDs above, which could be updated to https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=121

[temp_ds_ak.csv.zip](https://github.com/ArctosDB/arctos/files/11643201/temp_ds_ak.csv.zip)

>inding all localities that have a place name = to a state or province in the most recent history that is missing from the current higher geo

I think this expansion would result in a lot of very large messes, especially if expanded to collections with marine records, but please clarify if the scope does need expanded to something other than the above attachment and I'll pull data.

**Comment by mkoo** [comment]
I agree about expanding from this list-- so I think you just reiterated the scope right there with that list which is pretty much the same as Derek's (38 locs)

Please start with those Bering Sea locs in the list and I think that will cover 99% 
We can hunt down the others now that I know what I'm looking for. Thanks!

**Comment by dustymc** [comment]
>start with those Bering Sea locs in the list 

done
