### ISSUE TITLE
Data Loan Unloader not working?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6374]
Trying to unload records from a data loan at https://arctos.database.museum/tools/bulkUnLoadDataLoanItem.cfm but I get a blank screen with this message:

Try https://arctos.database.museum

**Comment by mkoo** [comment]
The proper URL is https://arctos.database.museum/loaders/bulkUnLoadDataLoanItem.cfm
(right @campmlc ?)

If so, please confirm so we can add a redirect to that badly formed link.
