### ISSUE TITLE
Add Data Loan Number to Catalog Record Page

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6375]
Maybe I'm missing something, but I can't find any indication on the catalog record page that a record is used in a data loan, and what that loan number is. Could we have a separate box near the parts table for this? Or perhaps in the Curatorial box with accession and project information? 
It would also be very useful if we could add/remove records from a data loan from the loan page, using the same type of tools to add remove parts from a loan, rather than exclusively having to use the component loaders to Add or Remove.
Priority: medium to high - needed for grant funded work.

**Comment by dustymc** [comment]
Going next task for a link - not sure where I'll put it, I don't like the idea of separating types of usage, will figure something out.
