### ISSUE TITLE
Label Request-- SQL for Mamm 

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#6379]
Two more changes are needed for MVZ Mamm labels (https://arctos.database.museum/Reports/reporter.cfm?action=edit&report_id=39)-- then we may be done with this one!?!!!!

- [x] SQL conditions for parts
For the #parts# variable we need to work in some if-then logic into the SQL.
Here are the conditions
1. if skin + skull = leave blank
2. if skin + skull with either skeleton, phallus, baculum, carcass then = "+skeleton". "+phallus", "+baculum", or "+ carcass" (basically plus sign and partname)
3. if skull only = "skull only"
4. if skeleton only = "complete skeleton" 

- [x] change in Arctos function. Buried somewhere in a function, when you select ```flat.othercatalognumbers other_ids,``` you get "collector number=" appended to the value. We just need the value!

- [ ] This is my to-do: add to the Tips sheet on labels and reports

**Comment by dustymc** [comment]
report modified, let me know what needs adjusted

**Comment by mkoo** [comment]
@cjconroy I'm working on this and your details are noted (I have lots of notes from Patton) I am putting your comment in the MVZ repo to keep this issue focused on the SQL

**Comment by mkoo** [comment]
@dustymc a few adjustments to the Arctos functions please!

- [ ] getMvzMammParts.sql please exclude the value 'tissues' In other words, if parts include 'tissues' do not print the value 'tissues'

- [ ] Other IDs-- this is going to need a new SQL. Currently
```concatsingleotherid(flat.collection_object_id,'collector number') collectornumber,```
is fine  now that you excluded "collector number=" in the output but it needs to show alternative values if no collector number is available. So the hierarchical and preferred order of displaying otherID is: 
1. collector number
2. preparator number
3. where IssuedBy = Museum of Vertebrate Zoology Prep Lab Catalog (https://arctos.database.museum/agents.cfm?agent_id=21347703)

in theory a record could have all three values but we would only print the collector number. If it is missing the collector number then print the next value in the list. Let me know if you have questions!

**Comment by dustymc** [comment]
done

**Comment by cjconroy** [comment]
here are some more differences between the legacy label and the new one.
Chris

![label comp](https://github.com/ArctosDB/arctos/assets/5749672/e005d498-c7d7-4515-89e0-83a9032ea040)

**Comment by mkoo** [comment]
@cjconroy please post this to the mvz repo since that's where this belongs... I can do it for you or come talk to me
Thanks!

**Comment by mkoo** [comment]
reminder to update docs

**Comment by dustymc** [comment]
Done?
