### ISSUE TITLE
Request: Display reciprocal relationship GUID+Identification on reciprocated record detail page

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#6380]
After discussing with @dustymc this is largely a UI request.

Currently reciprocal relationships look like this:
![Firefox_Screenshot_2023-06-05T15-29-45 952Z](https://github.com/ArctosDB/arctos/assets/2523089/cdd42986-8f2c-4613-b0ef-3680138bc938)

Instead, please include the reciprocal relationship's identification and better format the GUID into a hyperlink (no URL string) so it reads like this (in this case)

```<a href=https://arctos.database.museum/guid/MSB:Para:19677>MSB:Para:19677  Hoplopleura arboricola</a> ```
even including the "Identified by" (agent name and date) would be better! 

Please include the reciprocal relationship record info as small font and viewable in Full and Minimal views.

I dont recall discussing any barriers to this-- please note the Priority tag as this should be part of July demo of TPT grant update. let me know if there are questions! Thanks

**Comment by dustymc** [comment]
The significant barrier is https://github.com/ArctosDB/arctos/issues/6163, of which there are two factors

1. We have many ways of referring to records, there's nothing with which I can just join to another record, therefore there's nothing with which I can index, I have to manipulate strings and join on dynamic variables which is fragile and (very) expensive.
2. For all the same reasons, there are a LOT of malformed identifiers in Arctos - this will incur quite a bit of expense in checking, or look like Arctos is broken, or ???

I don't understand the objections to what from here looks like a huge simplification. Is there any way to complete 6163 before addressing this?

>July demo 

As (extensively!) discussed, I have begun work on https://github.com/ArctosDB/arctos/issues/5331, I have made significant changes to the model and UI, and changing tracks at this point would be extremely difficult. This is a UI request, but it's still one which needs to go through the development environment, which is completely occupied. This timeline does not seem approachable, and I'm not sure how I might accommodate this except by developing in production, which I believe is simply unacceptable.

**Comment by mkoo** [comment]
FYI, just saw in Jorrit's ppt at Idigbio where he had a screenshot of the pre-framework change.
this is what is seen from the reciprocal related record:
- family
- Identification
- locality string (concatenated HG+locality)

**Comment by jrpletch** [comment]
This is something that would be useful for us if it can be accomplished at some point.  It would definitely make seeing what parasite species were collected much easier at a glance.

https://arctos.database.museum/guid/NMU:Mamm:2832
<img width="931" alt="arctos Parasite ids" src="https://github.com/ArctosDB/arctos/assets/45340977/6f30a9f7-a840-409d-ae26-7f1e2890fd8a">

**Comment by dustymc** [comment]
>at some point.

How's[ Aug 21, 2023](https://github.com/ArctosDB/arctos/issues/6380#event-10151857999)?

<img width="662" alt="Screenshot 2024-03-15 at 16 20 37" src="https://github.com/ArctosDB/arctos/assets/5720791/fb5d0d0d-f202-4629-aa74-40efc8ddf340">

**Comment by mkoo** [comment]
to clarify, it's a hover action to see the reciprocal information

**Comment by jrpletch** [comment]
Got it, I was thinking along the lines of replacing the url with that info, but that is helpful too!
