### ISSUE TITLE
[ geography request ]the any geographic element field produces bad results

### ISSUE THREAD

**Issue by amgunderson** [ArctosDB/arctos#6382]
### Explain what geography needs created.

When I search in the any geographic element field for "Denali" I get results with this distribution,
<img width="1018" alt="Screenshot 2023-06-05 at 11 30 03 AM" src="https://github.com/ArctosDB/arctos/assets/8440698/8af600f1-acb3-4b68-bb34-10681338f436">

most have nothing to do with Denali. I thought the associated names were the problem (that field should be deleted as we have zero control over its association with our specimens and lists completely unassociated names like Denali linked to Kodiak Island as in this specimen https://arctos.database.museum/guid/UAM:Mamm:14133), but I do not find Denali in some of the associated names linked to specimens.
I am asked for clarification many times a year by users why they get bad results when using any geographic element to search Arctos. I tell them that field is useless and should be ignored. 
Can we make any geographic element work or eliminate it please?

**Comment by mkoo** [comment]
Hi @amgunderson yes I agree that search function doesnt work for a term with lots of synonyms, associations, etc but it is useful for some of the obscure stuff I work on. I recommend just ignoring it and creating a customized search interface which excludes it.
Here's the one I use regularly:
https://arctos.database.museum/search.cfm?sp=simple_search

You can do this in Customize Search and Results at the top of the page. Maybe this should be one of the universal presets?

anyway, if you create a profile, you can share with the URL!

**Comment by mkoo** [comment]
Adding for a future AWG demo of profiles
