### ISSUE TITLE
managing multiple Family identifications (specifically for Arctos Plants)

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#6385]
I'm looking for some guidance on how Arctos Plants (and any Arctos-based Classification Source) works regarding identifications that are not agreed upon by the scientific community.

For example: [Sambucus canadensis](https://arctos.database.museum/name/Sambucus%20canadensis)

I have found references attributing it to Family level: Adoxaceae, Caprifoliaceae, Viburnaceae
Arctos Plants currently attributes the Family to Caprifoliaceae; this was imported from ITIS in 2007 (and now ITIS says that Sambucus canadensis is not accepted, but the other sources do--that's a different rabbit hole).

In our herbarium, we organize specimens taxonomically by Family, then Genus. We currently use Adoxaceae for Sambucus canadensis, but they are not showing in Family searches as Adoxaceae, but Caprifoliaceae instead (screenshot of search results, pulled by location, not Family)
![image](https://github.com/ArctosDB/arctos/assets/93737929/ea9de76d-b6ed-4471-a09c-1a99703e851b)

I am working on adding folder-level location to catalog records, but this only helps us with Family ID internally, since location in the collection is restricted by permission.
![image](https://github.com/ArctosDB/arctos/assets/93737929/f0a4b1cc-21a5-4429-a9de-7702cdcec7a0)

If there are any botanists or collections managers out there who have some insight on which Family is considered "most" valid/accepted, please let me know! I've been comparing against KEW, GBIF, ITIS, Catalog of Life, and general internet searches for university/botanic organizations.

For Arctos Plants specifically, if the taxonomy genuinely isn't agreed upon (as opposed to just needs an update), how can we ensure that all of our specimens show up in the same Family search? Because Sambucus canadensis is used by multiple collections, I do not want to change the current Arctos Plants record. Do I clone the identification and create another Arctos Plants ID? If so, how do I ensure that the one we want shows up in search results?

**Comment by Jegelewicz** [comment]
> Do I clone the identification and create another Arctos Plants ID? 

No - there should be only one classification per name in each source.

> If so, how do I ensure that the one we want shows up in search results?

You should request a new source, add the classification you want there and prefer it over Arctos Plants. But it might be good to recognize that organizing by taxonomy is only going to give you endless headaches! Embrace object tracking! This won't fix your taxonomy problems but it will give you absolute control over finding things in your collection.

**Comment by wellerjes** [comment]
Please disregard the storage issue here, as it is secondary to the taxonomy issue. I'll address this in https://github.com/ArctosDB/arctos/issues/6386

Our main concern here is making sure that our data is clear and up-to-date when it is being pushed out to multiple data aggregators. If someone is searching for Adoxaceae is our collection, there are 28 catalog records that would be applicable to their search, but are not showing up because the Arctos Plants classification is tied to Caprifoliaceae. When taxonomy is disagreed upon by multiple reputable resources, how do we address it within Arctos to ensure consistent / correct data is being found by searches in the aggregators?

In Arctos overall, how do we make a distinction when there is disparity in taxonomy? We have looked through the sources we usually use (ITIS, GBIF, Catalogue of Life, Kew, IPNI, etc.) and they all say something different. Is this something we bring to the Taxonomic group? Should we implement a template similar to taxonomy quarantine and shared agents, where we request collections that have specimens with the disputed taxonomy to weigh in? Or should the Taxonomy committee review each request and decide internally? I am not a taxonomist and do not understand all the nuances. I'm just trying to make sure that the data we are putting out is findable.

**Comment by dustymc** [comment]
>how do we address it within Arctos to ensure consistent / correct data is being found by searches in the aggregators?

We don't - Arctos isn't a taxonomist and doesn't have an opinion on the matter. It is up to the collections to assert whatever they want to assert. (Ideally - in my view anyway - this might be through some coalition of Arctos collections collectively managing some shared Source, or better yet by collections just using some external source, but the fallback is always to create your own classification and do with it whatever you will.)

>omething we bring to the Taxonomic group

I'd say no, they should be focusing on Arctos-wide problems. (Deciding on the family of some genus probably isn't in scope, but helping a collection figure out how to express such things certainly is.)

>I am not a taxonomist and do not understand all the nuances. I'm just trying to make sure that the data we are putting out is findable.

In that case I'd encourage you to revive https://github.com/ArctosDB/arctos/discussions/4965, after which you could just use what eg, GBIF is using. (And @adhornsby might join you.)

(OK, that's a horrible choice, for your example above they have 6 conflicting opinions - https://arctos.database.museum/name/Sambucus%20canadensis#GBIFBackboneTaxonomy - but the idea of just following some trusted source through the magic of globalnames is still sound!)

**Comment by Jegelewicz** [comment]
@wellerjes This is a question for taxonomists who clearly are hashing through something or you would find a consensus. In Arctos, as long as classifications using all the possible families exist in any of the taxonomy sources people should still find your stuff. Outside of Arctos is out of our control and no matter what you choose it appears that someone will disagree. This is a much larger community issue! You can rely on one of the biggest players though. GBIF has a taxonomic backbone and any raw data sent to them gets converted to that backbone in order to standardize information. If the backbone agrees with Arctos Plants, then maybe you can worry less? If not and you think that the GBIF backbone is a good way to choose a classification, the path is either to prefer GBIF taxonomy for all of your plants (I think @dustymc would love to work with someone to do that!) or set up a new source and put what you need in it and prefer it over Arctos Plants.

We should talk about this in taxonomy and include the limitations that arise when non-taxonomists are required to make taxonomic assessments.
