### ISSUE TITLE
Feature Request - view or download part attributes

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#6386]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
I would like to easily view details part attributes.

**Describe what you're trying to accomplish** 
I am adding folder level Family identifications into the remarks of part attributes. I want to be able to download "Last Part Location" with all associated information, i.e., date, determiner, remark, method.
![image](https://github.com/ArctosDB/arctos/assets/93737929/dabe0011-ed11-4862-a998-a026d887fc25)

Currently, only the attribute label and value show up in part/loan summary:
![image](https://github.com/ArctosDB/arctos/assets/93737929/267e088e-f383-44be-8194-562812d3f0fe)

**Describe the solution you'd like**
Modify part/loan summary to include this information; make a "Manage Part Attributes" tool similar to "Manage Attributes"

**Describe alternatives you've considered**
n/a

**Additional context**
I'm adding Family level identification into remarks so we can better keep track of specimen organization and help indicate that Family-level identification has changed.

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by Jegelewicz** [comment]
@wellerjes can we talk about object tracking and converting your part location attributes to that system?

**Comment by Jegelewicz** [comment]
@dustymc I definitely see how a part attribute table that stretches those part attributes out into sets of columns (a reverse of the part bulkloader) could be very useful....complicated maybe, but useful.

**Comment by wellerjes** [comment]
@Jegelewicz - thank you for your offer. From my understanding of object tracking through the handbook, it requires barcoding--is this correct? If so, we do not have the capacity to implement a barcoding system at the moment.

I think downloading the information with JSON Parts will work. More to additional context: I want to see if someone left notes in remarks or method, as well as who updated the location for the specimen and when (some specimens are not in the recorded location and I'm trying to find a pattern--if they were put away by a specific person on a certain day and they just got the shelf off by one). If I can pull that from the JSON data and do text to columns in Excel, I should have the data I need.

**Comment by dustymc** [comment]
>reverse of the part bulkloader

That would carry limitations and isn't something I'd want to use, but expanding the "Attr" columns is actionable.

>object tracking in the Arctos Handbook, it requires a barcoding system--is this correct? 

"Require" isn't quite accurate, but yea - no way I'd want to use it without machine-readable labels.

Let me know if you have any problems with the JSON - we can find someone to help with that, or it might be a good use for reports, or I can help with SQL, or ....

**Comment by Jegelewicz** [comment]
@wellerjes You don't have to use the barcodes - they are the handles, but you can rely on labels. This is what @ebraker does (and I believe also @Nicole-Ridgwell-NMMNHS unless she has purchased some barcode readers) and I'd be happy to meet up to show you how it works. At the level of cabinets, drawers and shelves, I think the reader-less system works fine.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
We do use the barcodes, but not heavily. I agree with @Jegelewicz that this would work best in the object tracking, and you can do that without even printing the barcodes/having a reader. If you do want to set up some very basic barcoding capability, all you really need is some Avery label sheets, a cheap $30 barcode reader, and a student to stick them on stuff.

**Comment by dustymc** [comment]
https://handbook.arctosdb.org/documentation/container.html#object-tracking-without-barcodes should be clarified. I still won't suggest anyone try to type UUIDs off of nuncs or anything, but "object tracking" a (relatively) few big mostly-stationary things seems completely reasonable (and a big step in the right direction!).

**Comment by dustymc** [comment]
merge --> https://github.com/ArctosDB/arctos/issues/6806
