### ISSUE TITLE
Code Table Request - new locality attribute for labels

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#6387]
_**Goal**: Entomologists have such tiny labels (actually useful for anyone using size-limited labels)! So we need to have a standardized, customizable, shortened forms of spec_locality for label printing. 

_**Proposed Value**:
 ~~Proposed addition to: https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlocality_att_att~~

~~**label_locality**~~
(or suggest something better)

locality label from https://github.com/ArctosDB/arctos/issues/6387#issuecomment-1603503903

This will allow users to create alternative shortened locality descriptions that will fit on small labels. It will be free-text; all other attribute rules apply.

Once completed, we will need a SQL for label/report. 

_**Proposed Definition**:  Alternative shortened locality description that will fit on small printed labels or other reports. 

_**Attribute data type**: free-text

_**Table**:

 ~~https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlocality_att_att~~

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlocality_attribute_type from https://github.com/ArctosDB/arctos/issues/6387#issuecomment-1589949170

_**Priority**: Priority-High

_**Project**: Added to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184)._

_**Discussion**: @DerekSikes I'll rely on you for testing!

@ArctosDB/arctos-code-table-administrators 

## Approval

_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection

_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation

_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

_Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel._

_Make changes as described above. Ensure the URL of this Issue is included in the definition._

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by Jegelewicz** [comment]
@mkoo I suggest that we propose this using the code table request issue template - or are we abandoning that?

**Comment by Jegelewicz** [comment]
> label_locality
> (or suggest something better)

The under bar seems weird - most of our code table terms are just standard text. I suggest 

label locality

> Proposed addition to: https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlocality_att_att

I think you meant https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlocality_attribute_type

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I think this would be useful! I am unsure about "label locality", but don't have any serious objections and can't think of a good alternative.

**Comment by mkoo** [comment]
same here- fine with ``` label locality``` which seems to clear enough

**Comment by DerekSikes** [comment]
how about 'locality label'? This is a term well established in entomology to refer to the label on an insect pin that is not the identification label (most specimens have just these 2 labels and many have only locality labels).

**Comment by Jegelewicz** [comment]
I thought about that - but also thought it could be confused with locality name. However, we added this to [site identifier](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlocality_attribute_type#site_identifier):

`not to be confused with locality_name`

so maybe we could do the same for this and it would be OK?

**Comment by dustymc** [comment]
I have near-zero opinion on the label, but if there's something bigger than Arctos that's probably what we should use.

**Comment by mkoo** [comment]
OK to proceed with ```locality label``` ?
Let's make this happen!

**Comment by DerekSikes** [comment]
Thumbs up!

**Comment by Jegelewicz** [comment]
Added to the code table.

I'd like to add something to this workflow - an announcement. I think at least a section in the newsletter that highlights all new code table items would be good? Thoughts on how we let people know that new and useful things are available?

**Comment by dustymc** [comment]
>announcement

Maybe that's the compelling reason to do this in another repo for @mkoo 

1. This repo has some generic 'tell us what you're trying to do' template
2. discussion until solidification
3. "we" make a new ct-template issue in some repo that exists for only that reason, and 
    * someone shows up to tell us we haven't actually understood the problem and we start over, or
    * it gets approved by the Committee and implemented

Making the issue probably isn't really any more work than reading the existing template.

That would completely avoid wrong-template issues (and not make users who might do this a time or two per year wade through our mess).

It would be an easy repo to watch - near-everything that appears results in a data change - which would remove the need for a notice, or maybe just make it super-easy.

Or maybe that's trying to herd cats who just aren't going to march that orderly, I don't know....

**Comment by Jegelewicz** [comment]
That's probably a good way to go - but someone will have to manage the other repo.....

I can do that, but the number of repos I am currently managing is a bit much and people can't keep up!

**Comment by dustymc** [comment]
>someone

I figured I was volunteering myself, but maybe it could/should be a task of the CT Committee. 

>people can't keep up!

That's my big question - what's easier to deal with?
* one inevitably-messy everything-repo, or 
* one messy (but only for planning) plus two hopefully-no-so-messy "stuff happens" repos? 
 
I think maybe the latter but ??????

**Comment by Jegelewicz** [comment]
Added to newsletter issue https://github.com/ArctosDB/newsletter/issues/241
