### ISSUE TITLE
FYI Clean-up of otherID Type: removing MVZ:Page

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#6392]
MVZ'ers decided to remove MVZ:Page from the otherID types which has no records attached and is unused!

I can do this but wanted the other Code Table Admins to know.  I will close when complete

**Comment by dustymc** [comment]
Please don't, scripts depend on those (some will break, some will add it back...), see https://github.com/ArctosDB/arctos/issues/6357

This is also fixed by https://github.com/ArctosDB/arctos/issues/6163

**Comment by mkoo** [comment]
oh right -- I couldnt find an issue for this (and forgot to look in closed) so let's close this one and have it deleted with the others-- I just wanted this off the list of possibilities so it is not 'accidentally' used in btween. I will instead update the description to be clear
