### ISSUE TITLE
Label Request: SQL for Higher Geography

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#6394]
I noticed we need a better way to handle Higher Geography (HG) strings in reports.

So maybe some SQL logic to help accomplish this? Many labels have some kind of higher geography listed out along with the locality. Either in ascending or descending order and with commas or colons as separators:
ex ```Alameda County, California, USA``` or ```Brazil: Mato Grosso```

So could have a way to concatenate the fields of country, state_prov, county and only have county display if country = 'USA' as well as determine the ascending or descending order and the separator? I would like to have the SQL shared here so users can have it visible in the reporter.cfm boxes so it's editable by collections and not have it buried as a function in master.

Makes sense? @dustymc 

- [ ] Add to the Report handbook page (@mkoo task)

**Comment by dustymc** [comment]
Variety platter:

```
select
case 
    when geog_auth_rec.country = 'United States' then concat_ws(', ',geog_auth_rec.county,geog_auth_rec.state_prov,'USA')
    when geog_auth_rec.country = 'Brazil' then concat_ws(': ',geog_auth_rec.country,geog_auth_rec.state_prov)
    else geog_auth_rec.higher_geog 
end as geog
from
flat
inner join geog_auth_rec on flat.geog_auth_rec_id=geog_auth_rec.geog_auth_rec_id
where flat.guid in (
    (select guid from flat where country='United States' limit 10)
    union 
    (select guid from flat where country='Brazil' limit 10)
    union 
    (select guid from flat where country='Vietnam' limit 10)
);

               geog               
----------------------------------
 Brazil
 Alaska, USA
 Vietnam
 Vietnam
 Alaska, USA
 Vietnam
 Brazil: Mato Grosso do Sul
 Vietnam
 Catron County, New Mexico, USA
 Alaska, USA
 Alaska, USA
 Vietnam
 Brazil
 Dolores County, Colorado, USA
 Vietnam
 Mariposa County, California, USA
 Vietnam
 Vietnam, Gia Lai
 Brazil: Mato Grosso
 Vietnam
 Baltimore County, Maryland, USA
 Vietnam, Vinh Phuc
 Brazil: Espirito Santo
 Alaska, USA
 Brazil
 Alaska, USA
 Brazil: Espirito Santo
 Brazil: Sao Paulo
 Brazil
 Brazil: Sao Paulo
```

Let me know if that's not clear or something needs refined or whatever.

>not have it buried as a function

FYI I do that when I want another language. Functions provide access to a higher-level language, and in-report manipulation is yet another level. PG-SQL is a lot more powerful than old Oracle (for which many of the functions were developed), but there are still lots of things that are just BETTER (even possible) in other languages. That said, I do agree that doing things in SQL when practical should be preferred, let me know if you think a function can be recast and I'll give it a go.

**Comment by mkoo** [comment]
Yes I can work with that. Thanks! closing.....

**Comment by mkoo** [comment]
ps it was still open since I needed to add the reports doc but I'll do now-- you were finished a long time ago!
