### ISSUE TITLE
Customization warning on in Browse and Edit - update

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6403]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

Show All Columns in Browse and Edit does not remove customization warning (apparently I can never get rid of it now that I customized?) 

**To Reproduce**
1. Go to Browse and Edit
2. Click on Customize the view in some way
3. Scroll down to select "Show ALL Columns"
4. Still seeing this - how do I get rid of it?
![image](https://github.com/ArctosDB/arctos/assets/5725767/a25a2ad0-64d0-4f5a-becb-5ca9a1217ac6)

**Expected behavior**

There should be some way to clear this notification, otherwise I'll never know if I am seeing everything. I am guessing that this is still there because I haven't re-ordered the columns to whatever the default is - but nobody is going to know that! Selecting Show ALL Columns should be enough to clear the warning.

**Screenshots**

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by dustymc** [comment]
Not a bug, the behavior is intentional. The test is "has the user done something?", which is cheap and foolproof.

I could do something else, but it would take more resources (probably from the server, but potentially in the browser), be more prone to oopsies, and not provide clues as to why two users might not be seeing the same thing.

**Comment by Jegelewicz** [comment]
How difficult is it to reset that customization warning whenever I select Show All Columns?

**Comment by dustymc** [comment]
>whenever I select Show All Columns?

Those things are completely unrelated - I can't know where you came from or how you got some settings (because there are lots of ways to set setting, things change, etc., etc.), I can only know what you show up with (which as above is currently analyzed only as "something" or "nothing").

**Comment by dustymc** [comment]
@sharpphyl I think you're in production?

Below is the simplest possible check (beyond the aforementioned 'exists') - it's far from foolproof, but suggests that you aren't seeing everything.

I don't think I put up unjustified warnings.

The choices here - in order of risk - still look like:

1. disallow customization (which may be reasonable with https://github.com/ArctosDB/arctos/issues/6171)
2. a warning when anything has been customized (current situation), or 
3. actual checks, which we may or may not be able to afford, and which absolutely won't list all the possible problems customization might introduce. 

```

arctosprod@arctos>> select array_length(usr_fields,1) from cf_de_approve_settings where username ='sharpphyl';
 array_length 
--------------
          293
(1 row)

Time: 1.059 ms
arctosprod@arctos>> select count(*) from information_schema.columns where table_name='bulkloader';
 count 
-------
   301
(1 row)
```

**Comment by mkoo** [comment]
If we cannot click away the box, then Let's make it orange or some color that does not signify something is broken or wrong, just that the possibility exists! I agree that it's warranted to keep the message though so the user knows that something from the default has been implemented. compromise?

**Comment by Jegelewicz** [comment]
This is saying that once I have customized the table, I can NEVER be certain that I can see everything! That seems like a bad thing?

**Comment by Jegelewicz** [comment]
Once I have asked to show everything again, there should be no more scary box of any color, because I CAN see all the fields (ostensibly...)

**Comment by dustymc** [comment]
>once I have customized the table, I can NEVER be certain that I can see everything! 

That is precisely the situation.

>Once I have asked to show everything again, there should be no more scary box of any color

That is what happens.

**Comment by dustymc** [comment]
>Angry box!

Current options are

https://github.com/ArctosDB/PG/blob/master/includes/style.css#L49

https://github.com/ArctosDB/PG/blob/master/includes/style.css#L56

easy enough to add something else, just need CSS (easy) and some guidance (for https://handbook.arctosdb.org/how_to/developer-guide.html) on how these things should be used. I don't see a problem with as many styles as are necessary, as long as they're not used arbitrarily (and they probably already are, so guidance please!).

**Comment by mkoo** [comment]
clearly you need a third!
```
/* general-purpose alert */	
	.alertNotification {
		margin:1em;
		display:inline-block;
		padding:1em;
		border:10px solid orange;
	}
```
See how easy?!

**Comment by mkoo** [comment]
and I will stop calling it the Angry box from now on too!

**Comment by dustymc** [comment]
>See how easy?!

Yes - now guidance please, when should I use this instead of one of the others?

**Comment by mkoo** [comment]
well, here for starters but similarly when it's more of a gentle warning then imminent hellfire will start cascading

**Comment by dustymc** [comment]
>imminent hellfire

That's exactly what this looks like to me! I can't wrap my head around how anyone sees anything else, hence all the questions!

https://github.com/ArctosDB/PG/blob/master/includes/style.css#L63
