### ISSUE TITLE
taxon force create confirmation request

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6410]
[Castanea castaneifolia (Linnean)](https://arctos.database.museum/name/Castanea%20castaneifolia) was force-created

<img width="303" alt="Screenshot 2023-06-14 at 1 35 26 PM" src="https://github.com/ArctosDB/arctos/assets/5720791/b95036fb-f89a-48cc-a98c-028af787ebd1">

Is this real, and if so could the evidence be added to the name please?

@WaigePilson

**Comment by Jegelewicz** [comment]
@dustymc it's real - we added this today as part of a walk-through. source authority will get added.

This is part of the request I made to you last week for classifications from a group of genera. The output wasn't complete - I don't know why. For example, Salix definitely has a classification in Arctos Plants, but was mostly blank in the download.

Please be patient as we work through the list of names to add and then bulkload the classifications after they are added. We plan to repatriate to Arctos Plants - a decision about creating a new source will wait until a future date.

**Comment by dustymc** [comment]
>The output wasn't complete - I don't know why.

All the stuff in the email!

This is why I'm constantly saying that I'd never put any work directly into the big legacy classifications - re-extraction is lossy, the work you put into this thing today will just about inevitably be lost, and so will anything else that gets dumped in there. (And it'll probably mess up some other user's data, but hopefully that's a known risk of using these things...)

**Comment by dustymc** [comment]
Still don't see why this was created but at least its quarantined now?!
