### ISSUE TITLE
bulkloader and data entry: requirements

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6416]
ref: https://github.com/ArctosDB/arctos/issues/6171

What should be required in the bulkloader? At the moment I think it's accn (there's a NOT NULL key) and one identification (scientific name and ID order, because I explicitly check).

There are some weird dependencies that I don't quite know how to address without requiring a record-event - eg I think right now a record with lots of locality and event data but no record event type would load with no locality-stack, dumping the locality and event data in the process. I suppose I'll make place required to avoid that unless I hear otherwise, but place information isn't critical to a record so maybe that's weird/wrong?? 

I think everything else being optional is correct, but now's the time to add any constraints that should exist. Help!

**Comment by Jegelewicz** [comment]
My very hot take.

All you need to create a record in Arctos is a GUID prefix, an accession number, and a catalog number (including a catalog number assigned by Arctos, which means you may only need a GUID prefix and an accession number). Everything can be added as you like with component loader tools.

**Comment by dustymc** [comment]
>GUID prefix

You can't get to where I start worrying about this without, but yea, that's required, ditto enteredby and date.

I'm not listing/considering things that Arctos can magic for you - cat_num and record_type, at least - just things that are going to error if not provided.

**Comment by dustymc** [comment]
Related: I've got the current scripts set up as....

```
    IF rec.attribute_30_type is not null and rec.attribute_30_value is not null THEN
```

So any attribute with everything except value, or everything except type, or neither, will just be ignored. Only things with both type and value will be checked and entered. Without both, anything else that's there will be tossed.

I can change that - we've been all over the place in the past - but I think this is probably the most-usable balance. Please let me know ASAP if this approach is a terrible idea for some reason.

**Comment by dustymc** [comment]
Same note: if agent is given then I check role, otherwise I ignore the "object" - acceptable?

**Comment by dustymc** [comment]
I'm tentatively changing identifiers to match attributes: if type and value are given then process, else ignore. Feedback appreciated!

**Comment by dustymc** [comment]
I've removed this code:

```
<cfquery na...
		select count(*) as cnt from bulkloader_stage where orig_lat_long_units is null and (
			DEC_LAT is not null or
			DEC_LONG is not null or
			LATDEG is not null or
			DEC_LAT_MIN is not null or
			LATMIN is not null or
			LATSEC is not null or
			LATDIR is not null or
			LONGDEG is not null or
			DEC_LONG_MIN is not null or
			LONGMIN is not null or
			LONGSEC is not null or
			LONGDIR is not null or
			DATUM is not null or
			MAX_ERROR_DISTANCE is not null or
			MAX_ERROR_UNITS is not null or
			GEOREFERENCE_PROTOCOL is not null or
			UTM_ZONE is not null or
			UTM_EW is not null or
			UTM_NS is not null
		)
	</cfquery>
	<cfif pmiac.cnt gt 0>
		<p>
			<strong>CAUTION!</strong> There are coordinate data or metadata without orig_lat_long_units in your file.
			All coordinates are <strong>IGNORED</strong> when orig_lat_long_units is not given.
		</p>
	</cfif>
```

It's currently possible to ignore the whole place-time stack, so I don't think a check at this level can make any sense.
