### ISSUE TITLE
Agent Merge Request

### ISSUE THREAD

**Issue by jebrad** [ArctosDB/arctos#6418]
**Agent that should remain after the merge**
Erin F. McCarty

**Agent that will no longer remain after the merge**
Erin F. McCartney

**Reason for merge**
I believe UWBM created McCartney accidentally during our recent agents blitz, due to typo or perhaps a Beatles song playing someplace.  McCartney has zero records.

Please add this issue to the Agents Project

@ArctosDB/agents-committee

**Comment by dustymc** [comment]
It's only used by you, I don't think there's need for more discussion, marked.

Also, the blanket waffly data....

<img width="1078" alt="Screenshot 2023-06-14 at 5 51 27 PM" src="https://github.com/ArctosDB/arctos/assets/5720791/6ef4e4c2-c75a-4aed-be8c-ad254809fb0c">


just confuses the issue, @ArctosDB/agents-committee can we pretty please raise that bar?
