### ISSUE TITLE
ERROR: insert or update on table "cf_temp_media" violates foreign key constraint

### ISSUE THREAD

**Issue by kmkocot** [ArctosDB/arctos#6419]
Hi all, 

I'm having an issue bulkloading media metadata where I'm getting an error about (mime_type)=(PORTRAIT). I have tried to check for obvious things like typos and extra spaces/non-printing characters but I'm not seeing anything and the header was identical to one that worked before.

# Error Text
I'm getting an error when bulkloading media metadata:
"ERROR: insert or
update on table "cf_temp_media" violates foreign key constraint "cf_temp_media_mime_type_fkey"
DETAIL: Key (mime_type)=(PORTRAIT) is not present in table "ctmime_type"."

Here's a print-out of the whole error page:
[BulkloadMedia.pdf](https://github.com/ArctosDB/arctos/files/11753249/BulkloadMedia.pdf)

# Where it happened
https://arctos.database.museum/tools/BulkloadMedia.cfm?action=ld

# Steps to get there
I uploaded the media metadata file below and got this error. 
[NBP23-03_media_metadata.csv](https://github.com/ArctosDB/arctos/files/11753270/NBP23-03_media_metadata.csv)

Any advice would be greatly appreciated.

Best,
Kevin

**Comment by dustymc** [comment]
<img width="1239" alt="Screenshot 2023-06-15 at 6 24 38 AM" src="https://github.com/ArctosDB/arctos/assets/5720791/7fe91a21-dc99-47d0-82db-8f4afa573893">

**Comment by kmkocot** [comment]
Thank you @dustymc. I was afraid it was something dumb I was going. I scrolled through the file a couple times and somehow missed PORTRAIT in all caps (and somehow didn't consider to do a ctrl+F for it). Media metadata loading just fine now :)
