### ISSUE TITLE
Report pre-function lag?

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#6420]
@dustymc I have a few labels I've been trying to print and the pre-function does not appear to be integrating specimens recently added to a container into the correct ordering sequence.

For example, the two specimens below were added to this container two days ago and are still displaying on a separate line even though they belong to the same locality (10616827) as the other catalog numbers listed.

https://arctos.database.museum/EditContainer.cfm?container_id=21513716
![image](https://github.com/ArctosDB/arctos/assets/11336485/a290aa90-f642-4e3d-8743-293ba3a852be)

Usually if I make some sort of container or record update, there may be a 15-60 minute lag to display changes on the report, but this one is not resolving for several labels I've tried to generate.

**Comment by dustymc** [comment]
There should not be a lag, other than perhaps FLAT status (which you can check on guid pages).

I clicked print and  UCM_Jar_consolidated_country_Large and the group includes part name. I think you're probably using the old reporter, but the new code was modeled after it and is probably doing the same thing.

**Comment by ebraker** [comment]
Thanks! It looks like I didn't have one of the newer preservation part_attribute values recorded in the reporter code that was hanging it up.

I've continued to use the old template because the current version available gives me this:

![image](https://github.com/ArctosDB/arctos/assets/11336485/ec7d84a1-a724-4eb3-8ef6-902c3a79052d)

instead of this:

![image](https://github.com/ArctosDB/arctos/assets/11336485/6f012c73-b47c-4636-8cb3-005bda82f38f)

**Comment by dustymc** [comment]
done?
