### ISSUE TITLE
permissions for "manage collecting event"

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#6421]
Prior to the UI changes, our collections technicians and interns had access to editing and cloning collection events (seen here)
![image](https://github.com/ArctosDB/arctos/assets/93737929/67829c66-6611-4e24-9d87-95bf1e66c7c8)

I haven't changed permissions for their accounts since the UI updates, but now they are unable to access it in the new tool dropdown menu:
![image](https://github.com/ArctosDB/arctos/assets/93737929/1e61a48c-a0b0-4683-bed5-2a9798d9938c)

If this not a bug, my questions are:
1) which role is this permission tied to?
2) can it be tied to "manage_locality"?

Thank you!

**Comment by mkoo** [comment]
I dont think anything has changed.... I still see Manage Collecting Event in the second screenshot too-- at the bottom of that page is the list of the collecting events-- I think that the UI for that link needs work (there's any issue somewhere for the UI tasks) but the functionality is the same

If your students see that in their dropdown they should have access. Let me know if it's different than what's shown
