### ISSUE TITLE
Create new accession does not properly populate with suggested next number for MVZ Mamm

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#6422]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Where there should be a new accession number to click and populate the box for accession number, there is just the text error catch, [object Object]. 

**To Reproduce**
Try to make a new accession
Select MVZ mammals
That's it. 

**Expected behavior**
The next expected MVZ accession number should pop up.

**Screenshots**
Attached. 

**Desktop (please complete the following information):**
 Mac, Chrome

**Priority**
Low. Can still do job. 

<img width="1567" alt="New accn no next number help" src="https://github.com/ArctosDB/arctos/assets/5749672/a86f9e1c-eb0d-4461-b128-f43636d13cbb">

**Comment by dustymc** [comment]
Merge-->https://github.com/ArctosDB/arctos/issues/6509 + ping @mkoo
