### ISSUE TITLE
SQL fix please! is_tissue not current term

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#6423]
I have two SQLs to run but it's using apparently an outdated term? ```is_tissue ``` See below for the two queries (both from cheatsheet so I'll update with fixes):

1) **Count of specimens that have tissue flag and are whole organisms for a collection
Replace highlighted text with GUID Prefix of collection of interest**

SELECT
 	count(distinct(CAT_NUM))
FROM
 	flat,
 	specimen_part,
 	ctspecimen_part_name
WHERE
 	flat.collection_object_id = specimen_part.derived_from_cat_item and
 	specimen_part.part_name=ctspecimen_part_name.part_name and
 	upper(PARTS) LIKE '%WHOLE ORGANISM%' AND
 	ctspecimen_part_name.is_tissue = 1
 	AND guid_prefix LIKE 'MVZ:Herp%'

**ERROR: column ctspecimen_part_name.is_tissue does not exist Position: 280**

2) **List and count of cataloged specimens with tissues by family, genus, and species:
Replace highlighted text with GUID prefix of collection of interest**

select
	count(distinct(flat.collection_object_id)) specimencount,
	flat.family,
	flat.genus,
	flat.species
from
	flat,
	specimen_part,
	ctspecimen_part_name
where
	flat.collection_object_id=specimen_part.derived_from_cat_item and
	specimen_part.part_name=ctspecimen_part_name.part_name and
	ctspecimen_part_name.is_tissue=1 and
	flat.guid like 'MVZ:Bird:%'
group by
	flat.family,
	flat.genus,
	flat.species

**ERROR: column ctspecimen_part_name.is_tissue does not exist Position: 304**

Thanks! Needed for annual report and a grant proposal

**Comment by dustymc** [comment]
```
SELECT
count(*) numrecs
FROM
flat
WHERE
parts ilike '%whole organism%' AND
has_tissues > 0 and
guid_prefix = 'MVZ:Herp'
;


select
count(distinct(flat.collection_object_id)) specimencount,
flat.family,
flat.genus,
flat.species
from
flat
where
has_tissues > 0 and
flat.guid_prefix = 'MVZ:Bird'
group by
flat.family,
flat.genus,
flat.species
;

```

**Comment by mkoo** [comment]
Thanks-- working!
