### ISSUE TITLE
bulk change resulted in specific locality errors: "non-Native Columbia"

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#6424]
Back when UAM:EH first came into Arctos, we updated our cultures of origin/use which previously included some nationalities instead of straight cultures. "British" was one such nationality that we had @dustymc bulk change to "non-Native".

I've been pulling together records for a repatriation research request to locate all items from British Columbia and I'm finding an alarming number of records that say things like: "Canada, non-Native Columbia, Massett" for the specific & verbatim locality.

I have a feeling that whatever bulk change sucked in those specific/verbatim localities and swapped "British" for "non-Native".

Is there a way to find and replace all of those localities that are erroneously noted as "non-Native Columbia" instead of "British Columbia"? I can go thru and do them manually, but I sort of think there must be a simpler way.

I'm not great at bulkloading changes, so if that's the suggested route, I'd appreciate some hand-holding.

See for example: 
https://arctos.database.museum/guid/UAM:EH:UA2001-018-0020
https://arctos.database.museum/guid/UAM:EH:UA76-023-0001AC

**Comment by dustymc** [comment]
I did this:

```
select
    geog_auth_rec.higher_geog,
    locality.locality_id,
    collecting_event.collecting_event_id, 
    locality.spec_locality,
    collecting_event.verbatim_locality,
    replace(locality.spec_locality,'non-Native Columbia','British Columbia') as proposed_new_spec_locality,
    replace(collecting_event.verbatim_locality,'non-Native Columbia','British Columbia') as proposed_new_verbatim_locality
from locality
inner join geog_auth_rec on locality.geog_auth_rec_id=geog_auth_rec.geog_auth_rec_id
inner join collecting_event on locality.locality_id=collecting_event.locality_id
where (
    locality.spec_locality ilike '%non-Native Columbia%' or
    collecting_event.verbatim_locality ilike '%non-Native Columbia%'
);
```

and made this:

[temp_not_wut_bc.csv.zip](https://github.com/ArctosDB/arctos/files/11803303/temp_not_wut_bc.csv.zip)

Please confirm that these are the data of concern and that the 'proposed..' columns are what they should be and I can make the updates.

**Comment by AJLinn** [comment]
Aside from being embarrassed about the inconsistency of my locality data, that looks GREAT! Please make it so.

I'm glad there weren't more than this...
