### ISSUE TITLE
What happened to MSB loan reports in new reporter?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6425]
MSB Herp had some draft loan header forms in the new reporter, but I can't find them. Any idea where they went?

**Comment by Jegelewicz** [comment]
https://arctos.database.museum/Reports/reporter.cfm?action=edit&report_id=67

?

**Comment by mkoo** [comment]
@campmlc did Teresa identify the one you were looking for? please close if so!

**Comment by campmlc** [comment]
They showed back up as misteriously as they disappeared . . . random quantum fluxuations in the time space continuum?
I'm still needing reports for MSB, but I believe Teresa has started another issue for that.
Closing.
