### ISSUE TITLE
Request: Save searches in findContainer search page

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#6430]
I'd like to find all the containers in UAM:Ento that have container type = tag

but when I do this search nothing is found, yet hundreds of containers should have been found.

![Screenshot 2023-06-21 at 12 54 01 PM](https://github.com/ArctosDB/arctos/assets/9099827/35d205f6-5368-4148-b24a-889086f703a1)

Ideally I want to find those of container type = tag that have preservation type = pinned so I can change type 'tag' to type 'pin'

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.
high

**Comment by dustymc** [comment]
That search should not find anything - use Contained By Container Type

**Comment by mkoo** [comment]
I sense there's actually a feature request here, which I am going to edit this issue to rework as a request to save searches in findContainer.cfm

Thus Derek can do regular searches of collection = UAM:Ento and Contained By Container Type  = vial 

Not sure whether a technical challenge but a useful feature
