### ISSUE TITLE
Notification for something that isn't there?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6433]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

I am reviewing notifications and I see this:

![image](https://github.com/ArctosDB/arctos/assets/5725767/2c90a6ed-19b6-4b5f-956b-011ed5d6b8b8)

but when I click that link - there is nothing in that component loader. https://arctos.database.museum//loaders/BulkloadCollector.cfm

**To Reproduce**

**Expected behavior**

I expect to find 13 rows in there under the user krgomez

**Screenshots**

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by dustymc** [comment]
> there is nothing in that component loader.

... for you.

For various reasons (most obvious: your former student, who no longer has access to your collection, left stuff in some loader) that goes to everyone. I think there's an issue somewhere. Nothing is broken, everything is functioning as it should.

**Comment by Jegelewicz** [comment]
But the manager of that collection (@DellaCHall ) also sees nothing....

**Comment by Jegelewicz** [comment]
FWIW - I also have access....

**Comment by dustymc** [comment]
Aha! That's precisely why this exists! Theory meets reality, the heavens open, angels sing, bla bla....

There are data entered by krgomez, and @dchall has removed all collection association from that account. 

That's part of the reason the documentation is the way it is, but I think that's been stuck in limbo for a couple years (there's an issue...) and I used the logs to see what happened so the old way isn't necessarily the only way now, but this does need accounted for, somewhere/somehow.

>FWIW - I also have access....

You clearly don't - nobody does, see above.

This is the point where someone should summon a DBA, who can pull the data:

[cf_temp_collector.csv.zip](https://github.com/ArctosDB/arctos/files/11837454/cf_temp_collector.csv.zip)

**Comment by Jegelewicz** [comment]
@DellaCHall @AJLinn OK - this makes sense. You guys removed all of Karinna's access to the collection, therefore anything she left behind is in limbo...

See also [Managing Operator Roles and Permissions for Exiting Team Members](https://handbook.arctosdb.org/how_to/How-to-Create-your-Arctos-Team-Users-and-Operators.html#2-managing-operator-roles-and-permissions-for-exiting-team-members)

@dustymc if they add her back to the collection will the stuff become visible again?

**Comment by dustymc** [comment]
Yes that would make it visible, but the load will still fail unless full access is restored. I don't think there's any reason to complicate this, there are two tasks here:

1. Do something about user management documentation
2. Do something with the data I provided above - eg remove the username and load them.

**Comment by AJLinn** [comment]
> You guys removed all of Karinna's access to the collection, therefore anything she left behind is in limbo...

We removed all of that access because we didn't want someone else unlocking her account, thereby giving her access to all the same levels she had before (which was a lot). If/when she was reassigned access to the collection, Della should be the one to give her access at the level she determines is appropriate. In this way, I don't really agree with the documentation we have in the handbook.

If she reinstates access to UAM:Art, but keeps her account in LOCKED status, what minimal roles would clear this up? coldfusion_user? Or just give her access to the UAM:Art collection but no roles?

**Comment by dustymc** [comment]
>I don't really agree with the documentation

@AJLinn agree, this is fine, it's (most of) why there's a log now, the documentation just needs solidified and updated (and that conversation keeps finding strange ways to stop itself...).

There's no reinstatement needed, just grab the CSV above and do whatever needs done with it.

**Comment by AJLinn** [comment]
So I just looked at the catalog records in question and that agent is listed as the creator for all those items. I assume this was some bulk change from verbatim agent to creator. How does @DellaCHall  clear this out of the component loader?

**Comment by dustymc** [comment]
> I assume this was some bulk change from verbatim agent to creator.

No, these were entered by krgomez, I don't/can't know why.

> How does @DellaCHall clear this out of the component loader?

No need to do anything, I've taken care of it, the cleared data are in the CSV above.

**Comment by DellaCHall** [comment]
Thank you all!
