### ISSUE TITLE
Feature Request - See container weight and load capacity in find container

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#6446]
From the Working Group/Issues meeting 6/22/2023:

> Suggestion - add a field that allows you to see all of the weight total for an area/container

**Describe what you're trying to accomplish** 
It would be easier to use/see this data if it was visible in find container.

**Describe the solution you'd like**
Show this data in container details.

**Comment by dustymc** [comment]
Marked-up screenshot please?

**Comment by dustymc** [comment]
tabling; needs more information
