### ISSUE TITLE
[external CONTACT] error moving a container

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#6451]
@dustymc I created barcodes for MVZ bird cases and the barcode works when I tested it. But now I'm trying to create the hierarchy as follows:

MVZ
--- 3103 VLSB
------MVZBIRD-CASE-1

I used the 'move container' form and got this error when trying to move 3103 VLSB into MVZ, and MVZBIRD-CASE-1 into 3103 VLSB:

[2023-06-22T21:45:57.627Z]: ERROR: query returned no rows Where: PL/pgSQL function movecontainerbybarcode(character varying,character varying,character varying,character varying) line 69 at SQL statement: Parameter types passed (4): CF_SQL_VARCHAR, CF_SQL_VARCHAR, CF_SQL_VARCHAR, CF_SQL_VARCHAR

Is this a bug or am I doing something wrong?

Thanks,
Carla

**Comment by dustymc** [comment]
Something doesn't exist - actually maybe none of it does, did you create the containers? First create them, then move.

**Comment by ccicero** [comment]
hmmm, maybe not, duh!

but where is Container: Create???

![image](https://github.com/ArctosDB/arctos/assets/967275/7698085f-79fe-4823-9ee0-e30fed476344)

**Comment by dustymc** [comment]
[Container: Bulkload](https://arctos.database.museum/loaders/bulkCreateContainer.cfm)

**Comment by ccicero** [comment]
So only a bulkloader option? OK, I'll try that. Thanks.

**Comment by ccicero** [comment]
Got it working, thanks!
