### ISSUE TITLE
Code Table Request - add Barcode of Life BIN as identifier type

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6454]
## Initial Request

_**Goal**: Barcode of Life is another agent with multiple identifier types, including BIN numbers and Process IDs. Arctos currently has BOLD Process ID, which links via url to the BOLD specimen record. Propose we also add BoLD BIN (Barcode Index Number) to the code table, so we can distinguish these two types of identifiers issued by the same agent.

_**Proposed Value**: BoLD BIN ID

_**Proposed Definition**: Barcode of Life Barcode Index Numbers (BIN): Clustered barcode sequences that create OTUs (operational taxonomic units) closely reflective of species groupings

_**Context**: We already have BOLD Process ID in the code table. The BIN number is a second number issued by BOLD that provides the closest taxonomic match to the genetic sample in question. The only alternative to adding the BIN is to either put BIN in remarks, which is not acceptable, or creating BIN as an agent, which as we have discussed multiple times, is controversial among members of the community. 

_**Table**: https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type

_**Priority**:  Moderate - because we are eliminating "published identifier" in the code table, this information has temporarily been put in remarks, which need to be fixed.

https://arctos.database.museum/guid/MSB:Mamm:299313
http://boldsystems.org/index.php/Public_RecordView?processid=MUP185-14

_**Project**: Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184)._

_**Discussion**: Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary._

@ArctosDB/arctos-code-table-administrators 
@DerekSikes @jldunnum @AdrienneRaniszewski 

## Approval

_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [ ] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [ ] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection

_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation

_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

_Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel._

_Make changes as described above. Ensure the URL of this Issue is included in the definition._

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by DerekSikes** [comment]
I support this idea!

**Comment by campmlc** [comment]
From @dustymc 
There is already a robust solution in place: simply use the full identifier (https://v3.boldsystems.org/index.php/Public_BarcodeCluster?clusteruri=BOLD:AAA3869) as the value of type 'identifier' and everything will function as it should.

**Comment by campmlc** [comment]
> From @dustymc There is already a robust solution in place: simply use the full identifier (https://v3.boldsystems.org/index.php/Public_BarcodeCluster?clusteruri=BOLD:AAA3869) as the value of type 'identifier' and everything will function as it should.

@dustymc I'm still confused as to how your solution allows for searching? If I want to find all records with BIN numbers, how would I do that if they are all ID type = identifier, with just the url to distinguish the multiple ID types issued by the BOLD agent? What am I missing?

**Comment by campmlc** [comment]
Reviewing what you said, the problem is getting the url to autopopulate when all we have for data entry is "BOLD:AAA3869". Expecting students or even staff to enter the full ul is not going to work without some automation.

**Comment by Jegelewicz** [comment]
These BINs have DOIs

![image](https://github.com/ArctosDB/arctos/assets/5725767/55af58de-fc0a-4d1d-b9be-a73aeb51c10a)

https://dx.doi.org/10.5883/BOLD:AAA3869

Which I would think would the better identifier since https://v3.boldsystems.org/index.php/Public_BarcodeCluster?clusteruri=BOLD:AAA3869 could change. I don't know why, but that DOI takes FOREVER to resolve! Still it does work.

**Comment by Jegelewicz** [comment]
UGH see also https://arctos.database.museum/guid/DMNS:Mamm:10191

which includes the determiner as [BOLD Engine ID](https://arctos.database.museum/agent/21259274), but the BOLD record says the identification is Chordata, not [Perognathus flavus](https://arctos.database.museum/name/Perognathus%20flavus)

http://boldsystems.org/index.php/Public_RecordView?processid=NEONU1696-13

**Comment by campmlc** [comment]
Yes, these NEON records are a mess, because they still don't link to the
voucher specimens, and NEON probably gave them no info with the submission.
The Engine ID is used for identification assignments, as it is an automated
identification system, I believe?

**Comment by Jegelewicz** [comment]
This has been solved by adding the issued by BoLD to these identifiers.
