### ISSUE TITLE
why no display name for this species

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#6455]
https://arctos.database.museum/editTaxonomy.cfm?action=editClassification&taxon_name_id=10040163&name=Leptothorax%20canadensis&classification_id=10040163

Has no display name but should have one, what's up?

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.
high

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/6302
