### ISSUE TITLE
Code Table Request - add part name 'object' to Inv collection type

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#6457]
Can you add the existing specimen_part_name 'object' to be used for Inv collections? We have some manufactured objects made out of shells and other material that would fit best under this part name. Thanks
## Approval

_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [ ] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [ ] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

**Comment by dustymc** [comment]
This can proceed under the exemption:


1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._

but this is about what the warning was written for:

>Placeholder generic part name for cultural objects; likely to change when and if we can disentangle parts and taxonomy.


Added to Inv - please close or propose a better definition.

**Comment by acdoll** [comment]
These are essentially ~modern day cultural items; the current definition will suffice and we will keep an eye on future changes.
