### ISSUE TITLE
Code Table Request - add part name 'pearl' 

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#6458]
Please add 'pearl' to [ctspecimen_part_name](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name) to be used (at least) by Inv collection types.

```

A hard, glistening object produced within the soft tissue (specifically the mantle) of a living shelled mollusk or another animal, such as fossil conulariids. https://en.wikipedia.org/wiki/Pearl https://github.com/ArctosDB/arctos/issues/6458

```
## Approval

_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

**Comment by Jegelewicz** [comment]
Might conflict with identification at some point, but we are also doing this with amber, so I am giving it the green light.

https://www.mindat.org/min-42674.html
https://www.getty.edu/vow/AATFullDisplay?find=pearl&logic=AND&note=&english=N&prev_page=1&subjectid=300011827

**Comment by dustymc** [comment]
>conflict with identification

It's also awfully close to 'evidence of life' eg trace+modifiers, but if @Jegelewicz is happy with a part then I'm happy with a part!

**Comment by Jegelewicz** [comment]
added
