### ISSUE TITLE
Help with report - need a bit of SQL

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6463]
I need some help adding stuff to a report that gets the csv for a Word mail merge - UWBM_mammal_box_large_csv

1. Adding in verbatim collector when you have that instead of collector
2. Right now the download includes all other catalog numbers - I need to narrow this down to prep number only.

I can probably fool around and figure this out, but I assume @dustymc can do it in a minute or two.

Thanks!

**Comment by dustymc** [comment]
>1. Adding in verbatim collector when you have that instead of collector

Elaborate please, there are a lot of ways to interpret that, different collections are likely to want different dialects (reflecting how - or if - they manage verbatim agents).

https://github.com/ArctosDB/arctos/issues/5449 is one take, let me know what you want if there's not an answer in there.

>Right now the download includes all other catalog numbers - I need to narrow this down to prep number only.

```
concatsingleotherid(flat.collection_object_id,'preparator number') as whateveryouwannacallit
```

>do it in a minute or two.

Once I understand the request: yea, usually, please don't hesitate to ask for SQL/data help!

**Comment by Jegelewicz** [comment]
OK - got the other id working

but the verbatim preparator is always NULL even when there is a verbatim preparator

I used this

`vac.vacls as verbatim_preparators`

```
left outer join (select collection_object_id,string_agg(attribute_value,'; ') as vacls from attributes 
			where attribute_type ='verbatim agent' and attribute_remark= 'preparators' 
			group by collection_object_id) vac
			on coll_object.collection_object_id=vac.collection_object_id
```

What am I missing?

**Comment by dustymc** [comment]
>What am I missing?

Data/example?

**Comment by Jegelewicz** [comment]
Run the report - UWBM_mammal_box_large_csv

from this search - https://arctos.database.museum/search.cfm?guid_prefix=UWBM%3AMamm&customoidoper=LIST&oidnum=EFM%20%25

**Comment by dustymc** [comment]
Your query

``` attribute_remark= 'preparators' ```

https://arctos.database.museum/guid/UWBM:Mamm:82495

<img width="861" alt="Screenshot 2023-06-27 at 1 28 02 PM" src="https://github.com/ArctosDB/arctos/assets/5720791/3a868959-400d-4527-b944-36037969f47d">


So maybe something like ``determination_method ilike  '%preparator%' - case-insensitive substring.

Snuck a peek at the data, these are relatively consistent, determination_method =  'preparators' might work (and will be cheaper - although not a big deal here - and less likely to return false positives)

```

          attribute_remark           | determination_method 
-------------------------------------+----------------------
 translated fromASC                  | collectors
 translated fromBrooks Kohli, WDFW   | collectors
 translated fromDennis Schott        | collectors
 translated fromE. F. McCarty 004    | preparators
 translated fromE. F. McCarty 005    | preparators
 translated fromE. F. McCarty 009    | preparators
 translated fromE. F. McCarty 013    | preparators
 translated fromE. F. McCarty 014    | preparators
 translated fromE. F. McCarty 015    | preparators
 translated fromE. F. McCarty 019    | preparators
 translated fromE. F. McCarty 037    | preparators
 translated fromE. F. McCarty 050    | preparators
 translated fromE. F. McCarty 051    | preparators
 translated fromE. F. McCarty 052    | preparators
 translated fromJayne von Doenhoff   | collectors
 translated fromJon Gallie           | collectors
 translated fromK.S. Tan             | collectors
 translated fromToby Bradshaw w/hawk | collectors
 translated fromWPZ # 200495         | collectors
 translated fromWPZ#204496           | collectors
 translated fromWPZ# 920149          | collectors
```

I messed with your report, lemme know if it's crazy.

**Comment by dustymc** [comment]
<img width="343" alt="Screenshot 2023-06-27 at 2 01 37 PM" src="https://github.com/ArctosDB/arctos/assets/5720791/005e74bd-866d-4402-bb38-65a3c055308c">

**Comment by Jegelewicz** [comment]
OH wait - it is only doing it for some things?

For example https://arctos.database.museum/guid/UWBM:Mamm:82616

has a verbatim preparator, but nothing in the file.

**Comment by Jegelewicz** [comment]
DOH! Nevermind - I am dyslexic.

Thanks for this!
