### ISSUE TITLE
Agent Creation and Operator settings not in sync?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6465]
**Describe the bug**
I am trying to create an agent to assign operator permissions, and when I create the agent and then go to Manage Operators, the display says agent not found, even though the agent exists.

**To Reproduce**
1. Go to Create Agent - assign agent's login, add agent email, save, then go to  Manage Operator
2. Find agent login
3. Go to agent https://arctos.database.museum/AdminUsers.cfm?action=edit&username=avinod04
4. Try to invite as operator, get error that agent does not exist.

**Expected behavior**
For this to be manageable in real time. We need to be able to assign operator permissions when we have students sitting down for training.

**Screenshots**
![Screenshot 2023-06-27 11 41 12](https://github.com/ArctosDB/arctos/assets/14808196/8b98d9c1-a951-4cf8-ac01-123f52f7e4ed)

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by dustymc** [comment]
https://handbook.arctosdb.org/documentation/users.html

>New operators must be agents. Under the Agents tab, locate them if they are an existing agent or, after carefully checking, create them as a new agent. Make sure they have a name-type of “login,” and that their login name exactly matches their Arctos username. These are case sensitive.

**Comment by campmlc** [comment]
All of the above has been done. Agent is Amal Vinod, he has a login and an email associated with his agent profile and his account?

**Comment by Jegelewicz** [comment]
His agent does not have a name type = login with his username.

**Comment by mkoo** [comment]
More specifically if avinod04 is his login it needs to be added as a login not aka (or in addition to aka)

![Firefox_Screenshot_2023-06-27T21-10-48 611Z](https://github.com/ArctosDB/arctos/assets/2523089/c4229b21-6a8e-42ef-bc51-2d459007b3e8)

**Comment by campmlc** [comment]
Ah, that must be it. I meant to select login, but I was talking so probably grabbed the wrong one.
