### ISSUE TITLE
CHAS Mamm Links to USNM

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6467]
@wellerjes The attached file can be loaded to the [identifiers bulkload tool](https://arctos.database.museum/loaders/BulkloadOtherId.cfm?action=ld) to add links from your mammal records to the associated Smithsonian records. Let me know if you have any questions!
[CHAS_Mamm_Smithsonian_ARKs.csv](https://github.com/ArctosDB/arctos/files/11896605/CHAS_Mamm_Smithsonian_ARKs.csv)

I tried to do the same for the birds - but none of the records seemed to match. For example

https://arctos.database.museum/guid/CHAS:Bird:62

has an identifier USNM-53376 and is identified as [Charadrius wilsonia](https://arctos.database.museum/name/Charadrius%20wilsonia)

![image](https://github.com/ArctosDB/arctos/assets/5725767/42dcfc16-9971-404a-8d89-541ab6138264)

but when I search the Smithsonian bird data at https://collections.nmnh.si.edu/search/birds/ for catalog number = 53376, it seems to be [a completely different thing](http://n2t.net/ark:/65665/3aed412c1-df4f-40af-91bb-5db6ebbe4504):

![image](https://github.com/ArctosDB/arctos/assets/5725767/d085a513-8b9f-48fc-96e8-1e102f84b68f)

I tried about 5 and none of them matched or the catalog number was not found. I'm wondering if these are really USNM numbers or if they are some kind of USNM expedition number...

**Comment by dustymc** [comment]
done?

**Comment by Jegelewicz** [comment]
The mammal links have never been added. I will email them to see if we can get this done.

**Comment by Jegelewicz** [comment]
> Jessica and Dawn,
> 
> Happy New Year! Do you want to add the links mentioned in this issue? https://github.com/ArctosDB/arctos/issues/6467 
> 
> Let me know if you need any help. Please close the issue when you are done or if you don't want to add the links.
> 
> Thanks!

Teresa J. Mayfield-Meyer

**Comment by droberts49** [comment]
This is done for the mammal records.
