### ISSUE TITLE
[external CONTACT] change identifier type for issued by 'Museum of Vertebrate Zoology Prep Lab Catalog'

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#6469]
@dustymc @mkoo 

The identifier type for issued by 'Museum of Vertebrate Zoology Prep Lab Catalog' is currently 'identifer' but it is really should be 'preparator number' to better reflect what that number represents?

Can we update the values that currently contain 'identifier' for issued by 'Museum of Vertebrate Zoology Prep Lab Catalog' to 'prepator number' ?

**Comment by Jegelewicz** [comment]
@mkoo

**Comment by dustymc** [comment]
Probably need to revise the definition to do this.

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type#preparator_number

>A value that refers to a record in the catalog of the person listed as the first preparator of a specimen.

And FWIW I'm happy to shuffle things however you want (or there are tools, you can too), but I don't think any clarity can be wrung out of type either.

**Comment by mkoo** [comment]
Well, I see both sides of the issue here. Issued By is the prep lab catalog (its in the title!) so I dont know if it needs to be also an IDtype since the fewer the better as we move into a brave(r) new world. Simply using ```preparator number``` seems to only embrace the transitional phase harder. So I would favor keeping it "identifier" if pushed

>>I don't think any clarity can be wrung out of type either.

you know what they say about blood from a stone

**Comment by ccicero** [comment]
I can't read the whole thread right now but for the PLC I think the identifier type should be preparator number as that is what the number represents.

**Comment by mkoo** [comment]
Exactly! the issued_by makes it clear: "Museum of Vertebrate Zoology Prep Lab Catalog"

**Comment by cjconroy** [comment]
How do you assign an issued_by in data entry? I don't see a box for it.

<img width="984" alt="Screenshot 2023-07-05 at 8 12 18 PM" src="https://github.com/ArctosDB/arctos/assets/5749672/587c5a0e-1e27-414f-9f0d-bb4f9f516ed9">

**Comment by dustymc** [comment]
>issued_by in data entry?

https://github.com/ArctosDB/arctos/issues/6003

**Comment by Jegelewicz** [comment]
> Why not add issued by and remark to the primary identifier box in data entry?

@cjconroy that will happen as soon as the bulkloader rebuild is complete!

**Comment by cjconroy** [comment]
glad to hear it

**Comment by cjconroy** [comment]
I'm glad that you can search for Prep lab catalog in the issued by just by entering PLC. Is this nonsense text a bug that can be fixed?

<img width="972" alt="Screenshot 2023-08-15 at 8 38 23 AM" src="https://github.com/ArctosDB/arctos/assets/5749672/c35a778a-b953-4162-af8f-2674dd322d01">

**Comment by mkoo** [comment]
that's a trailing space... that should be automatically deleted out, yes? @dustymc

**Comment by dustymc** [comment]
It's a trailing space on the prefix, but it's HTML-encoded (https://handbook.arctosdb.org/documentation/encoding.html).

If there's no compelling reason for the space (there would be if it were an actionable identifier, but probably not in something that's just for people) then I'd recommend removing it - its just going to break search.

Bigger-picture, I'd recommend removing the prefix altogether - that's clearly people trying (for a couple hundred years) to do PRECISELY what we've done (attach an agent to identifiers) but without the structure to do it effectively. You don't have to guess what PLC might mean (programmable logic controller, obviously!), you can just hook into a data object with a good identifier (https://arctos.database.museum/agent/21347703) and remove all ambiguity.

**Comment by ccicero** [comment]
I like retaining 'PLC' to make it clearer that this is not a collector number. However, I'm not totally opposed to removing it but it would be clearer in this instance (where a record has both a collector and PLC number) if we went back to the full/split view vs the minimal view.

![image](https://github.com/ArctosDB/arctos/assets/967275/da18efa3-5fe7-4f19-9a03-e70033bea699)

versus 

![image](https://github.com/ArctosDB/arctos/assets/967275/dcd5a992-fcd5-4b09-a327-0543d3bb4453)

**Comment by ccicero** [comment]
Also, shouldn't there also be an 'issued  by' for the collector number? In this case there are two collectors, how does one know which number that goes to?

**Comment by cjconroy** [comment]
What about preparator number? Does it also get issued by the preparator?  The assigned by is whoever is doing data entry?

**Comment by dustymc** [comment]
>shouldn't there also be an 'issued by' for the collector number?

File a focused Issue - I'll need some guidance.

>What about preparator number?

Ditto, happy to help however I can but I will need some direction.

>The assigned by is whoever is doing data entry?

Yep (maybe-sorta-useful for things like tracking mistakes, but the real magic is that it allows things like machine-created reciprocal relationships without any chance of confounding human-asserted and derived data).
