### ISSUE TITLE
Feature Request - add 'year' as an option for catalog record summary

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#6471]
@dustymc 

I love the catalog record summary tool! We used to have an option to summarize by collecting year - can we please add that back in as an option in the list?

![image](https://github.com/ArctosDB/arctos/assets/967275/21c10c42-293e-471a-bd79-ce21e55e8e21)

**Comment by mkoo** [comment]
Which year? Probably Begin_date for the collecting event, right?

**Comment by dustymc** [comment]
>Which year?

Just wondering that myself...

The data in FLAT come from

    getYearCollected(collecting_event.began_date,collecting_event.ended_date),

Choosing the event to flatten comes from https://github.com/ArctosDB/PG_DDL/blob/master/function/getpriorityspecimenevent.sql

year-puller is https://github.com/ArctosDB/PG_DDL/blob/master/function/getYearCollected.sql


All pretty cryptic, could use some sort of documentation.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Where is this tool? I would like to use it.

**Comment by dustymc** [comment]
Oh - I think this one is search/find something/


<img width="318" alt="Screenshot 2023-06-30 at 2 15 39 PM" src="https://github.com/ArctosDB/arctos/assets/5720791/2fae1303-d9a4-4898-9dc5-b59011d3fdf5">


and if so just customize and...

<img width="226" alt="Screenshot 2023-06-30 at 2 16 45 PM" src="https://github.com/ArctosDB/arctos/assets/5720791/bbc016dc-036d-40b1-ade6-7d6cada257e3">

and then you can..


<img width="284" alt="Screenshot 2023-06-30 at 2 17 50 PM" src="https://github.com/ArctosDB/arctos/assets/5720791/bae74e8a-7ac5-4054-833c-7e760bcd6d5a">

There's also [Record Summary](https://arctos.database.museum/record_summary.cfm), which does some things the above can't and doesn't do some things the above can.

... and it has year too...


<img width="777" alt="Screenshot 2023-06-30 at 2 20 18 PM" src="https://github.com/ArctosDB/arctos/assets/5720791/73f4c926-b9c0-4919-8559-5ab2e507d994">


@ccicero clarify please!

**Comment by dustymc** [comment]
done?
