### ISSUE TITLE
Help adding in Issued by Agents

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#6474]
@dustymc would it be possible to add some "issued by" identifier agents for me (too many to do manually)? If so:

- For all UCM records where identifier value contains 'ERW' (n=3326), add issued by agent: **Edward Royal Warren Collection** (organization: 21346679). 
-- These are inconsistently assigned 'collector number' and 'identifier' ID types - these could all get updated to 'collector number' if possible (...it's also ok if they stay as is)
- For all UCM records where identifier value contains 'CCM' (n=5547), add issued by agent: **Colorado College Museum** (organization: 21293373)
-- Many of these records currently have identifier= Colorado College Museum: CCM #### - would it be possible to delete the "Colorado College Museum: " text (leave in CCM) from the value? (again, not an issue if they stay as is)
- For all UCM records where identifier value contains 'original AOU number' (n=1433), add issued by agent: **American Ornithologists' Union** (organization: 21307928)

**Comment by dustymc** [comment]
I set these up so that they can be updated by row if you want to massage anything. Let me know what I mucked up, say "go," send me cleaned data and instructions, or feed these to the bulkloaders.
```

create table temp_ucm_erw as
select
    coll_obj_other_id_num_id,
    guid,
    guid_prefix,
    other_id_type,
    display_value,
    other_id_type as new_other_id_type,
    display_value as new_other_id_number,
    issued_by_agent_id,
    issued_by_agent_id as new_issued_by_agent_id
from
    coll_obj_other_id_num
    inner join flat on coll_obj_other_id_num.collection_object_id=flat.collection_object_id
where
    display_value ilike '%erw%' and
    guid_prefix like 'UCM%'
;


update temp_ucm_erw set new_other_id_type='collector number',new_issued_by_agent_id=21346679;

```

[temp_ucm_erw.csv.zip](https://github.com/ArctosDB/arctos/files/11908045/temp_ucm_erw.csv.zip)


```

create table temp_ucm_ccm as
select
    coll_obj_other_id_num_id,
    guid,
    guid_prefix,
    other_id_type,
    display_value,
    other_id_type as new_other_id_type,
    display_value as new_other_id_number,
    issued_by_agent_id,
    issued_by_agent_id as new_issued_by_agent_id
from
    coll_obj_other_id_num
    inner join flat on coll_obj_other_id_num.collection_object_id=flat.collection_object_id
where
    display_value ilike '%ccm%' and
    guid_prefix like 'UCM%'
;
update temp_ucm_ccm set new_other_id_number=trim(replace(new_other_id_number,'Colorado College Museum: ','')),new_issued_by_agent_id=21293373;


```

[temp_ucm_ccm.csv.zip](https://github.com/ArctosDB/arctos/files/11908067/temp_ucm_ccm.csv.zip)

```

create table temp_ucm_aou as
select
    coll_obj_other_id_num_id,
    guid,
    guid_prefix,
    other_id_type,
    display_value,
    other_id_type as new_other_id_type,
    display_value as new_other_id_number,
    issued_by_agent_id,
    issued_by_agent_id as new_issued_by_agent_id
from
    coll_obj_other_id_num
    inner join flat on coll_obj_other_id_num.collection_object_id=flat.collection_object_id
where
    display_value ilike '%original AOU number%' and
    guid_prefix like 'UCM%'
;
update temp_ucm_aou set new_issued_by_agent_id=21307928;

```
[temp_ucm_aou.csv.zip](https://github.com/ArctosDB/arctos/files/11908078/temp_ucm_aou.csv.zip)

**Comment by ebraker** [comment]
Awesome!

Looks like there is one outlier for CCM:
![image](https://github.com/ArctosDB/arctos/assets/11336485/7b1980e0-3084-48d3-a53e-42090c923241)
...but it is the only UCM:Fish record, so you can exclude that one or use this file: [temp_ucm_ccm_CLEANED.zip](https://github.com/ArctosDB/arctos/files/11908184/temp_ucm_ccm_CLEANED.zip)


Otherwise, all looks great! It's a go! Thank you!

**Comment by dustymc** [comment]
Took the lazy route:

```
arctosprod@arctos>> delete from temp_ucm_ccm where guid_prefix='UCM:Fish';
DELETE 1
```

done
