### ISSUE TITLE
Remove Barcode: Swap by Bulk from Tool Directory

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#6475]
Barcode: swap by Bulk (https://arctos.database.museum/tools/scaryBarcodeSwapper_box.cfm) leads to nowhere:
![image](https://github.com/ArctosDB/arctos/assets/11336485/75fb510b-6780-4a8e-a543-c07da890dea6)

Users should instead use Barcode: Swap (currently on menu)
![image](https://github.com/ArctosDB/arctos/assets/11336485/76d521db-28ca-441b-97ba-8721e02d69a3)

Please delete "Barcode: swap by Bulk" value from this tile

**Comment by dustymc** [comment]
added to next release scripts
