### ISSUE TITLE
force agent data request - J. S. Torres

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6476]
sharpphyl just force-created agent [J. S. Torres](https://arctos.database.museum/agents.cfm?agent_id=21348959).

@sharpphyl is this necessary? "Possibly..." in the remarks and the no-data URL make me think this is a (very) good candidate for a verbatim agent.

@ArctosDB/agents-committee can we clarify the requirements please?

**Comment by Jegelewicz** [comment]
@sharpphyl a Google of the publication confirms Juan Sebastian. I upgraded the name and added a link to the paper in the remark, but if this isn't exactly who you want, I suggest using a verbatim agent attribute.

**Comment by sharpphyl** [comment]
The URL does not have a locality, but it does reference work in Malaga which is the locality of the specimen we are databasing.   We cannot confirm beyond question that it's the same J. S. Torres, but it's highly likely.  

Yes, can you clarify what level of detail is required to create an agent beyond an URL and a publication?

**Comment by Jegelewicz** [comment]
A meaningful URL that tells me something about the person such that I can tell them apart from any other J. S. Torres would be better.  Here's the thing - I am going to get 5,000 names from some incoming collection and if they have James Torres, I am going to have to investigate whether or not they are J. S. Torres. The information in that agent is helpful (if my James Torres studies mice, then I can be pretty sure they aren't the same) but it is not solid enough to tell me anything if James Torres studies some marine invertebrate thing.

Anyway, the publication is the better resource and if taken a step further (I Googled the publication and there found the author listed as Juan Sebastián Torres Alba) it confirms that the J. S. Torres you found on that website is actually Juan Sebastián Torres Alba. What it doesn't necessarily confirm is that YOUR J. S. Torres is the author of the paper (unless you know that for certain).

So, as it stands right now, you are asserting that Juan Sebastián Torres Alba is your agent doing whatever role they are doing in your collection - I just want to make sure that you are comfortable with that.

**Comment by sharpphyl** [comment]
> I just want to make sure that you are comfortable with that.

No.  I think it's highly likely, but I'm never going to be 100% certain unless (for example) I get another specimen from the same collecting event with his full name.  I'll move it to verbatim collector.
