### ISSUE TITLE
Barcode bulkloader - which one(s)?

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#6477]
I have about 250 parts that are currently incorrectly placed in ~120 different jar containers due to transcription errors during a collections inventory project. 

I need to (1) remove the parts from their current containers (ideally not including these barcodes as container history since the specimens were never physically in these jars) and (2) place the parts into different containers.

Is there a way I can do this? What bulkloader(s) should I use? @dustymc @campmlc @Jegelewicz

**Comment by dustymc** [comment]
[Part: Bulkload to Containers](https://arctos.database.museum/loaders/BulkloadPartContainer.cfm)

**Comment by ebraker** [comment]
Thank you!
