### ISSUE TITLE
Feature Request - add all parts to loan

### ISSUE THREAD

**Issue by amgunderson** [ArctosDB/arctos#6478]
We used to be able to add all parts of partname=whatever to a loan through an add items to loan search. Now we have to check every box next to the part to be added to a loan. And when subsampling those parts we must click the "use part" button for every single specimen. Can we please get those functions back. Creating a loan of 100+ subsampled bones now requires at least 200 clicks when it used to require 2. 

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I agree, this is needed!

**Comment by dustymc** [comment]
Here's a proposal.

--------------

## Source

https://github.com/ArctosDB/arctos/issues/6478

## Summary

Save clicks when adding samples of multiple like parts to a loan.

## User Interface Changes

* add part name filter option
* add a 'set subsample to part name' button

## Data Structure Changes

none
