### ISSUE TITLE
add attributes to entomology

### ISSUE THREAD

**Issue by droberts49** [ArctosDB/arctos#6479]
Would you please add a couple attributes to entomology: "color" and "description". They are in some of the other collection categories but not in ento.

**Comment by ebraker** [comment]
Seems fine to me. I can add barring no objections. @Jegelewicz ?

**Comment by Jegelewicz** [comment]
None from me!

**Comment by dustymc** [comment]
The [code table template](https://github.com/ArctosDB/arctos/issues/new?assignees=&labels=Function-CodeTables&projects=&template=code-table-request.md&title=Code+Table+Request+-+) has an exemption (and a warning) for this:

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._

If @droberts49 is happy with [those](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#colors) [definitions](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#description) (and these seem like what might be expected to me) then nothing else is needed, this can proceed.

**Comment by Jegelewicz** [comment]
Added both
