### ISSUE TITLE
Code Table Request - New part preservation = resin embedded

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6480]
_**Goal**: Add a preservation to described embedded specimens

_**Proposed Value**: resin-embedded

_**Proposed Definition**: 

https://github.com/ArctosDB/arctos/issues/6480#issuecomment-1613880389

~~a specimen or object embedded in resin (a substance that converts into rigid polymers by the process of curing) typically for the purposes of thin-sectioning. [Github Issue](https://github.com/ArctosDB/arctos/issues/5689)~~

Fixed firmly in resin (a substance that converts into rigid polymers by the process of curing). Typically used as a medium for the purposes of thin-sectioning.

_**Context**: Paraffin embedded exists already, but is a different material. I don't think the two should be merged under "embedded" because I think the different properties of the two substances probably warrant different treatment.

_**Table**: https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_preservation

@ArctosDB/arctos-code-table-administrators 

## Approval

_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection

_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation

_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

_Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel._

_Make changes as described above. Ensure the URL of this Issue is included in the definition._

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

_Originally posted by @Nicole-Ridgwell-NMMNHS in https://github.com/ArctosDB/arctos/issues/5689#issuecomment-1613857750_

**Comment by dustymc** [comment]
This should match paraffin-embedded, I don't care how.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I am ok with the definition change.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Definition was updated again, but I don't think in sounds quite right. How about this:

Fixed firmly in resin (a substance that converts into rigid polymers by the process of curing). Typically used as a medium for the purposes of thin-sectioning.

**Comment by Jegelewicz** [comment]
I checked the box for @Nicole-Ridgwell-NMMNHS based upon the comment above and added the new definition.

**Comment by Jegelewicz** [comment]
added
