### ISSUE TITLE
Count units = individuals change to "count"

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6481]
### Goal
_Describe what you're trying to accomplish. This is the only necessary step to start this process. The Committee is available to assist with all other steps. Please clearly indicate any uncertainty or desired guidance if you proceed beyond this step._

Have a palatable term for numeric values that represent a count of something

### Proposed Value
_Proposed new value. This should be clear and compatible with similar values in the relevant table and across Arctos._

We currently use [individuals](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcount_units#individuals) but it does feel awkward! It was suggested that we change this to

count

### Proposed Definition
_Clear, complete, non-collection-type-specific **functional** definition of the value. Avoid discipline-specific terminology if possible, include parenthetically if unavoidable._

A number or mathematical object used to count, measure, and label. The original examples are the natural numbers 1, 2, 3, 4, and so forth. Expected values are numerals; for example, "5" is a numeral that represents the number five.

### Attribute data type
_If the request is for an attribute, what values will be allowed? free-text, categorical, or number+units depending upon the attribute (TBA)_

N/A

### Attribute controlled values
_If the values are categorical (to be controlled by a code table), add a link to the appropriate code table. If a new table or set of values is needed, please elaborate._

N/A

### Attribute units
_If numerical values should be accompanied by units, provide a link to the appropriate units table._

### Context
_Describe why this new value is necessary and existing values are not._

              That units code table is very odd - "individuals, ng/ml, percent" ? 
The units for this proposed attribute would be none of the above, so perhaps "count" would be the value?
Or am I not seeing something?

_Originally posted by @campmlc in https://github.com/ArctosDB/arctos/issues/6173#issuecomment-1518193339_

### Table
_Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table or value. This may involve multiple tables and will control datatype for Attributes. OtherID requests require BaseURL (and example) or explanation. Please ask for assistance if unsure._

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcount_units#individuals

### Collection type
_Some code tables contain collection-type-specific values. ``collection_cde`` may be found from https://arctos.database.museum/home.cfm_

N/A

_**Priority**: Please describe the urgency and/or choose a priority-label to the right. You should expect a response within two working days, and may utilize [Arctos Contacts](https://arctosdb.org/contacts/) if you feel response is lacking._

_**Example Data**: Requests with clarifying sample data are generally much easier to understand and prioritize. Please attach or link to any representative data, in any form or format, which might help clarify the request._

_**Available for Public View**: Most data are by default publicly available. Describe any necessary access restrictions._

_**Project**: Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184)._

_**Discussion**: Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary._

@ArctosDB/arctos-code-table-administrators 

## Approval

_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [ ] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [ ] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection

_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation

_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

_Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel._

_Make changes as described above. Ensure the URL of this Issue is included in the definition._

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by campmlc** [comment]
We are using this a bunch to track the number of individual organisms bulk cataloged in a roughly sorted lot (e.g. 50 fleas of various unsorted species) for grant reporting, and the format currently is "individual count = "50" individuals", with the units as "individuals". 
Perhaps this could be made into a "count" attribute with units = "individuals"? 
Or maybe "individual count" attribute with a numeric value and no units?
But we are heavily using this at the moment, so please give a long lead time for any changes. 

I think the ng/mL and the percent values exist because this code table is used by other attributes???? Very confusing.

**Comment by Jegelewicz** [comment]
@ campmlc this is made at your request and would change 

"individual count = "50 individuals"

to

"individual count = "50 count"

**Comment by campmlc** [comment]
I was just remarking that the code table made no sense for that attribute, so we could leave as is, change the attribute name, or change the code table units. 
I'm happy with selecting individuals as units, or leaving units off completely since the attribute is explicit. In fact, most of our students doing data entry forget the units half the time, and I have to try to use the semi-functional SQL tool in the bukloader to try to fix. But I thought perhaps there might be a better solution that addresses other issues. 
Regardless, this is working currently for MSB, and if no one else is using it, then we can leave for now.

**Comment by Jegelewicz** [comment]
> leaving units off completely 

Is not possible for numeric values - there has to be units....

Closing and leaving individuals as units for antler points.
