### ISSUE TITLE
Enhancement - Landholders should be Agents

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6485]
Half of this code table is Agents - https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlandholder

Perhaps this needs splitting?

Landholder:general (the code table)
LANDHOLDER GENERAL | Documentation | Metadata 
-- | -- | --
city [ link ] | A geographic unit defined as a permanent and densely settled  place with administratively defined boundaries whose members work  primarily on non-agricultural tasks. |  
county [ link ] | A geographical region of a country used for administrative or other purposes. |  
land grant [ link ] | A gift of real estate – land or its use privileges – made by a  government or other authority as an incentive, means of enabling works,  or as a reward for services to an individual, especially in return for  military service |  
private [ link ] | Property owned by non-governmental legal entities. |  
public [ link ] | A portion of land held by central or local government. |  
state [ link ] | Land held and administered by state government. |  
tribal [ link ] | Land held and administered by a federally recognized Native American tribal nation under the U.S. Bureau of Indian Affairs. |  
unknown [ link | Unknown landholder status 

Landholder:specific (VALUE IS an agent) the below get removed from the code table and added as agents

LANDHOLDER GENERAL | Documentation | Metadata 
-- | -- | --
Bankhead-Jones Land Use Lands [ link ] | Lands acquired by the United States under the Bankhead–Jones  Farm Tenant Act of 1937 and managed by the U.S. Forest Service and the  Bureau of Land Management management. |  
US Army Corps of Engineers [ link ] | An engineer formation of the United States Army |  
US Bureau of Land Management [ link ] | An agency within the United States Department of the Interior responsible for administering federal lands. |  
US Bureau of Reclamation [ link ] | A federal agency under the U.S. Department of the Interior, which oversees water resource management. |  
US Department of Defense [ link ] | An executive branch department of the federal government  charged with coordinating and supervising all agencies and functions of  the government directly related to national security and the United  States Armed Forces. |  
US Department of Energy [ link ] | A cabinet-level department of the United States Government  concerned with the United States' policies regarding energy and safety  in handling nuclear material. |  
US Fish and Wildlife Service [ link ] | An agency of the United States Government within the United  States Department of the Interior dedicated to the management of fish,  wildlife, and natural habitats. |  
US Forest Service [ link ] | An agency of the U.S. Department of Agriculture that administers the nation's national forests and grasslands. |  
US National Park Service [ link ] | An agency of the federal government of the United States that  manages all national parks, many national monuments, and other  conservation and historical properties with various title designations. |  
US National Wildlife Refuge System [ link ] | A designation for certain protected land areas of the United States managed by the United States Fish and Wildlife Service.

OR (crazy idea!) could we add something to the agents - landholder type (the code table) and create generic agents for the generic landholders?

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/arctos/issues/6470#issuecomment-1613461779_

**Comment by Jegelewicz** [comment]
Agents already exist for most of these. I added the link to the agent in the code table and a link to the code table in the agents

**Comment by mkoo** [comment]
I like this in general (makes sense!) but not to introduce complications, some of the land holders are actually types of land rights like the Bankhead-Jones or Wildlife Refuge System which are administered through one fed agency or another. (also owner and administrator of lands are not always the same).

**Comment by Jegelewicz** [comment]
> , some of the land holders are actually types of land rights like the Bankhead-Jones or Wildlife Refuge System

OR (crazy idea!) could we add something to the agents - landholder type (the code table) and create generic agents for the generic landholders?

**Comment by dustymc** [comment]
> create generic agents for the generic landholders

Pretty hard "no" from me - "the public" (or "depends who you ask" or ...) are indefensible stretches of the 'identifiable human-based entity' datatype.

**Comment by mkoo** [comment]
yea I agree with Dusty on this -- what is a generic agent anyway?! if it has a profile, not generic by definition. We can have a verbatim agent for that.
