### ISSUE TITLE
Record/Event determiner doesn't show up in search results

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#6487]
**Describe the bug**
Record/Event determiner is blank in search results.

**To Reproduce**
Record/Event determiner should be Gary S. Morgan:
![image](https://github.com/ArctosDB/arctos/assets/47402809/ec6283a0-db8c-4980-86eb-5b5e589e623b)

1. Search for specimen (example here is NMMNH:Paleo:67120)
2. Customize Search results to add Record/Event Determiner
3. Search results show a blank in the Record/Event Determiner column
4. Download data - Event Determiner is also blank in the download

![image](https://github.com/ArctosDB/arctos/assets/47402809/7e7de1f7-a1a7-43dc-93c2-bc3f1b225820)

**Expected behavior**
I should see the event determiner

**Comment by dustymc** [comment]
rebuilt the function

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks!
