### ISSUE TITLE
[external CONTACT] fix citation mistake

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#6492]
@dustymc I recently uploaded a large number of citations for publication_id=10011907 and mistakenly put the page number (95) in the remarks column. Can you please move the page number in remarks to the page number field?

![image](https://github.com/ArctosDB/arctos/assets/967275/17b919e1-ab82-4bca-b5c8-5078571dc704)

Thanks!

**Comment by dustymc** [comment]
done

**Comment by ccicero** [comment]
Thanks!
