### ISSUE TITLE
[CONTACT: Blocked Network]

### ISSUE THREAD

**Issue by JimY128** [ArctosDB/arctos#6493]
restricted IP: 15.181.147.170

**Comment by mkoo** [comment]
Hello @JimY128 
You appear to be running an VPN that will constantly trigger Arctos. Is there any way you can access Arctos without it? Please let us know what you are trying to do so we can help out. best, MK

**Comment by JimY128** [comment]
I turned off the VPN and get the same error with a different IP 96.244.70.22

**Comment by dustymc** [comment]
96.244.70.22 is released and should be cleared up within 10 minutes.

**Comment by JimY128** [comment]
thank you!
