### ISSUE TITLE
error feedback

### ISSUE THREAD

**Issue by av096** [ArctosDB/arctos#6494]
Trying to log in as new operator - get the following error:
9C5A84ED-502B-4ED9-8800B8093EFDDB94

**Comment by mkoo** [comment]
HI @av096 I think you jumped the gun as you are now an operator administered by @campmlc 
New operators cannot do anything until permissions and cold_fusion access is applied.

Please file another issue or talk to your supervisor if you have further access issues!

**Comment by campmlc** [comment]
Just FYI - he got this error when we were working together to set him up as
an operator, after I had assigned permissions, and after he had logged out
and logged back in. But we waited five minutes and it worked. There seems
to be some lag time in processing operator access that results in that
error - we should have some kind of documentation for what to expect when
that happens.
