### ISSUE TITLE
Code Table Request - A long list of Quads to add

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6495]
## Initial Request

We have compiled a list of new quads to add to the code table in Arctos. The attached spreadsheet has the quad name and documentation for each. We have included a link to the USGS map wherever possible as documentation, or a listing of the country, state when not possible.

Note: We (@KatherineLAnderson and myself) have many instances in our data where the map quad is listed without reference to the scale (15 Minute vs 7.5 Minute vs other). Since we cannot determine which specific map quad we are referencing in these cases, we therefore are requesting adding the quad name with just the country, state for documentation rather than a URL link to the USGS map. There are also some instances where some of our localities list the map with scale but other localities do not (e.g., some list "Jordan 7.5 Minute" but some just list "Jordan"). Therefore, you will also see that we have requested to add both e.g., "Jordan" and "Jordan 7.5 Minute" as new quad names in the Arctos code table. If you have any questions or concerns, or think there is a better way to handle this, let us know!

### Goal
_Describe what you're trying to accomplish. This is the only necessary step to start this process. The Committee is available to assist with all other steps. Please clearly indicate any uncertainty or desired guidance if you proceed beyond this step._

Appropriately label paleo localities within a Quad

### Context
_Describe why this new value is necessary and existing values are not._

##Table
_Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table or value. This may involve multiple tables and will control datatype for Attributes. OtherID requests require BaseURL (and example) or explanation. Please ask for assistance if unsure._

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctquad

### Proposed Value
_Proposed new value. This should be clear and compatible with similar values in the relevant table and across Arctos._

[UWBM_Quad_Import.xlsx](https://github.com/ArctosDB/data-migration/files/11962258/UWBM_Quad_Import.xlsx)

### Proposed Definition
_Clear, complete, non-collection-type-specific **functional** definition of the value. Avoid discipline-specific terminology if possible, include parenthetically if unavoidable._

See spreadsheet above

### Collection type
_Some code tables contain collection-type-specific values. ``collection_cde`` may be found from https://arctos.database.museum/home.cfm_

N/A

#### Attribute data type
_If the request is for an attribute, what values will be allowed?
free-text, categorical, or number+units depending upon the attribute (TBA)_

N/A

#### Attribute controlled values
_If the values are categorical (to be controlled by a code table), add a link to the appropriate code table. If a new table or set of values is needed, please elaborate._

N/A

#### Attribute units
_if numerical values should be accompanied by units, provide a link to the appropriate units table._

N/A

### Priority
_Please describe the urgency and/or choose a priority-label to the right. You should expect a response within two working days, and may utilize [Arctos Contacts](https://arctosdb.org/contacts/) if you feel response is lacking._

### Example Data
_Requests with clarifying sample data are generally much easier to understand and prioritize. Please attach or link to any representative data, in any form or format, which might help clarify the request._

### Available for Public View
_Most data are by default publicly available. Describe any necessary access restrictions._

### Helpful Actions

- [x] Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

- [x] Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

@ArctosDB/arctos-code-table-administrators 

## Approval

_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection

_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation

_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

- [ ] Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

- [ ] Add or revise the code table term/definition as described above. Ensure the URL of this Issue is included in the definition.

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by Jegelewicz** [comment]
@Nicole-Ridgwell-NMMNHS I'd greatly appreciate your help on this one!

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
There are a few duplicate values with the current table that I've highlighted in the excel sheet. There might be others with slight formatting differences.
[UWBM_Quad_Import.xlsx](https://github.com/ArctosDB/arctos/files/11983114/UWBM_Quad_Import.xlsx)

I'd rather find another way to handle the scale-less maps and clean up the quad table a bit (most of the maps on there currently without scale are the original Alaska 1:250,000 quads) I'm concerned that if we start adding the maps without scales that will just lead to more of a mess.

**Comment by Jegelewicz** [comment]
@Nicole-Ridgwell-NMMNHS thanks for the help - I will also review for duplicates.

> I'd rather find another way to handle the scale-less maps and clean up the quad table a bit (most of the maps on there currently without scale are the original Alaska 1:250,000 quads) I'm concerned that if we start adding the maps without scales that will just lead to more of a mess.

Agree - perhaps a new attribute = verbatim quad? Free text, Use this when you are uncertain which map scale applies to the named quad.
?

**Comment by dustymc** [comment]
>verbatim quad?

This is already a low-information (maybe just assertable) variant of [https://arctos.database.museum/place.cfm?sch=geog&quad=_](https://arctos.database.museum/place.cfm?sch=geog&quad=_), not sure we need a lower!

**Comment by Jegelewicz** [comment]
But we can't add quads to HG anymore (and why are these even there?) I am really confused about how higher geography is supposedly working right now....

**Comment by Jegelewicz** [comment]
Here are the exact matches that I found


Quad
--
Big   Delta
Bloomfield   15 minute
Carson   Trading Post 7.5 minute
Des   Moines 7.5 minute
Horseshoe   Bend 7.5 minute
Kimbeto   7.5 minute
Sheep   Mountain Table 7.5 minute
Sorrel   Horse Mesa 7.5 minute
Tanana
Twin   Buttes 7.5 minute
Umiat
Upper   Valley 7.5 minute

**Comment by Jegelewicz** [comment]
Removed those from the file and here is what is left.

[UWBM_Quad_Import.csv](https://github.com/ArctosDB/arctos/files/11986485/UWBM_Quad_Import.csv)

Can we add these? What else do we need to do for this?

**Comment by dustymc** [comment]
I think I need final CSV before I check any boxes, but I also don't think there's any possibility that I'll have any objections to whatever ya'll work out - ping me when everything else is happy.

**Comment by Jegelewicz** [comment]
As far as I am concerned, the last file I attached is the final. Although I submitted this issue, it was on behalf og @KatherineLAnderson so I went ahead and checked a Code Table Admin box. @Nicole-Ridgwell-NMMNHS if you are OK with this, please check the box, if not, let me know what else I can do to get this ball rolling as this is needed for data migration. Thanks!

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> This is already a low-information (maybe just assertable) variant of https://arctos.database.museum/place.cfm?sch=geog&quad=_, not sure we need a lower!

I'll concede to that. Can you lower-case minute to be consistent with the rest of the table? Otherwise I'm ok with this. box checked.

**Comment by Jegelewicz** [comment]
> Can you lower-case minute to be consistent with the rest of the table? 

Done

[UWBM_Quad_Import(2).csv](https://github.com/ArctosDB/arctos/files/12003708/UWBM_Quad_Import.2.csv)

**Comment by dustymc** [comment]
There's only one box checked but 2 said they'd check it, I think that's good enough. 

A few of these had whitespace issues, I cleaned them up.

Done.
