### ISSUE TITLE
Code Table Request - specimen part name: genitalia: mamm

### ISSUE THREAD

**Issue by ehalverson26** [ArctosDB/arctos#6497]
Goal: Add the part “genitalia” to mammal collections. 
Context: Our mammal collection has a legacy collection that focuses heavily on reproductive parts including specifically genitalia.
Table: specimen_part_name
Proposed Value: genitalia
Proposed Definition: Can remain the same as the current definition: The external sex organs.
Collection type: Mamm
Priority: High, waiting to bulkload
Available for Public View: Yes

**Comment by dustymc** [comment]
done
