### ISSUE TITLE
Code Table Request - specimen_part_name_: trachea: mamm

### ISSUE THREAD

**Issue by ehalverson26** [ArctosDB/arctos#6498]
Goal: Add the existing part “trachea” to mammal collections.
Context: Part is something from a legacy collection and needed for bulkloading.
Table: specimen_part_name
Proposed Value: trachea
Proposed Definition: Can remain the same as the current definition: Also known as the windpipe, a cartilaginous tube that connects the larynx to the bronchi of the lungs, allowing the passage of air, and so is present in almost all air-breathing animals with lungs.
Collection type: Mamm
Priority: High, waiting to bulkload
Available for Public View: Yes

**Comment by dustymc** [comment]
done
