### ISSUE TITLE
Code Table Request - Add ectoparasite: flea to Examined_Detected Code Table

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6503]
# Initial Request

## Goal: 

Add ectoparasite: flea to the Examined_Detected code table:

## Proposed Values:

ectoparasite: flea

## Proposed Definitions:

~~The common name for the insect order Siphonaptera, small flightless insects that live as external parasites of mammals and birds. https://en.wikipedia.org/wiki/Flea~~
Fleas are ectoparasitic insects in the order Siphonaptera. Specify specific type and life stage if known in methods/remarks.

## Context: 

These values are being added the Examined_Detected code table to capture existing data in Arctos, to accommodate ongoing research which will be populating these attributes going forward, and for TPT digitization and host linkage. The current attributes "ectoparasite examination" and "ectoparasite detected" will be migrated to these new attributes. Splitting from https://github.com/ArctosDB/arctos/issues/6260 .

## Table: 

~~https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_code_tables~~
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctexamined_detected

## Priority: 

High. Needed for TPT Arctos and MSB funding, and for upcoming presentation at American Society of Parasitology meetings July 13-15, 2023.

## Available for Public View: 

Yes

## Project: 

Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

## Discussion:

@jldunnum @campmlc @acdoll @bryansmclean

https://github.com/orgs/ArctosDB/teams/arctos-code-table-administrators

# Approval

All of the following must be checked before this may proceed.

The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality).

 - [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
 - [x] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
 - [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
 - [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)
Rejection
If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc.

Can a suitable solution be found here? If not, proceed to (2)
Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)
Take the discussion to a monthly Arctos Working Group meeting for final resolution.
Implementation
Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made.

Review everything one last time. Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

Make changes as described above. Ensure the URL of this Issue is included in the definition.

Close this Issue.

DO NOT modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result.

Special Exemptions
In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases.

Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step.
The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology.

**Comment by Jegelewicz** [comment]
Code table changed to https://arctos.database.museum/info/ctDocumentation.cfm?table=ctexamined_detected

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Looks fine. Checked.

**Comment by Jegelewicz** [comment]
@dustymc @campmlc @Nicole-Ridgwell-NMMNHS before I add this, I'd like to simplify the definition. OK?

Ectoparasitic insects in the order Siphonaptera.

**Comment by dustymc** [comment]
New def is fine with me - and please don't forget to include the issue when you add!

**Comment by campmlc** [comment]
Please change def slightly:
"Fleas are ectoparasitic insects in the order Siphonaptera".

**Comment by Jegelewicz** [comment]
added
