### ISSUE TITLE
Code Table Request - Add ectoparasite: mite to Examined_Detected code table

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6506]
# Initial Request
## Goal: 

Add ectoparasite: mite to the Examined_Detected code table:

## Proposed Values:

ectoparasite: mite

## Proposed Definitions:

~~Small arachnids (eight-legged arthropods), many of which are ectoparasitic. Includes the orders Acariformes and the Parasitiformes, which were historically grouped together in the subclass Acari. https://en.wikipedia.org/wiki/Mite~~
Ectoparasitic mites are arachnids in the orders Acariformes and Parasitiformes (exclusive of ticks, use ectoparasite: tick for known ticks). Specify specific type and life stage if known in methods/remarks.
## Context: 

These values are being added the Examined_Detected code table to capture existing data in Arctos, to accommodate ongoing research which will be populating these attributes going forward, and for TPT digitization and host linkage. The current attributes "ectoparasite examination" and "ectoparasite detected" will be migrated to these new attributes. Splitting from https://github.com/ArctosDB/arctos/issues/6260 .

## Table: 

~~https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_code_tables~~
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctexamined_detected

## Priority:

High. Needed for TPT Arctos and MSB funding, and for upcoming presentation at American Society of Parasitology meetings July 13-15, 2023.

## Available for Public View: 

Yes

## Project: 

Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

## Discussion:

@jldunnum @campmlc @acdoll @bryansmclean

https://github.com/orgs/ArctosDB/teams/arctos-code-table-administrators

## Approval

All of the following must be checked before this may proceed.

The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality).

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)
Rejection
If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc.

Can a suitable solution be found here? If not, proceed to (2)
Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)
Take the discussion to a monthly Arctos Working Group meeting for final resolution.
Implementation
Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made.

Review everything one last time. Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

Make changes as described above. Ensure the URL of this Issue is included in the definition.

Close this Issue.

DO NOT modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result.

Special Exemptions
In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases.

Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step.
The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology.

**Comment by Jegelewicz** [comment]
Changed the code table to https://arctos.database.museum/info/ctDocumentation.cfm?table=ctexamined_detected

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Looks fine. Checked.

**Comment by Jegelewicz** [comment]
@dustymc @campmlc @Nicole-Ridgwell-NMMNHS Let's be consistent and simplify this definition

Mites are arachnids in the orders Acariformes and Parasitiformes. Specify specific type and life stage if known in methods/remarks.

**Comment by campmlc** [comment]
This works, although at the moment, ticks are also in the Parasitiformes. The problem is that mites are paraphyletic. What we really mean is "any non-tick Acari". But that could all change if anyone ever figures out mite taxonomy.

**Comment by dustymc** [comment]
>What we really mean is "any non-tick Acari"

You're still referencing a complex and dynamic concept - what's a "tick" and what precisely do you mean by 'Acari'?

>that could all change

Exactly. So what does this mean? Do I need to understand two taxon concepts (neither of which exist or are referenced....) to understand this, or can it be simplified to some *functional* and practical definition? (If not then I'd suggest that ectoparasite [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctexamined_detected#ectoparasite) is the actual resolution and this has no place.)

**Comment by campmlc** [comment]
That is true for fleas, ticks, and even birds . . . 
We've already accepted that this tool is not going to solve all problems and is a flag to bridge when we have dedicated funding. 
Where exactly do I put "Acari" or "ticks/mites" if I don't have this value? We know these mites/ticks are a specific group of arachnids confirmed to be in the Acari. They aren't spiders, they aren't bat flies or fleas, and we can't say for certain more specific than that. I can say for certain if we have detected mites, and I can say for certain if we have detected ticks, but I need a term for the unsorted group that includes both.

**Comment by campmlc** [comment]
This isn't a semantic discussion - we need these to be discoverable. Researchers who want ticks to test for pathogens will want to find records that detected "ticks" and  "mites/ticks = Acari".

**Comment by campmlc** [comment]
For the purposes of this request, "mite" is a perfectly legitimate term. If "tick" is an allowable term, the "mite" should also be allowable. 
Approving this attribute will allow @ccicero  to use this for  her requested "feather mites" and for MSB Mammals to use it for "ear mites".

**Comment by dustymc** [comment]
> "mite" is a perfectly legitimate term.

Agreed, but that's not what's been proposed. (And neither is "tick" - AFAIK all ticks are ectos and so what's actually been proposed there can be justified, where with mites it's often beyond the means of the person recording these data to know if they're parasitic or just passing through. I still don't understand how that is addressed.)

>This isn't a semantic discussion

It absolutely is, and we spent a fair bit of today's CT Meeting talking about why it has to be. "Mite" (or any other code table value) means some defined thing, and without that it becomes impossible to understand how the term fits in with other terms, and a [10-minute issue](https://github.com/ArctosDB/arctos/issues/6111) finds a way to drag out for 4 months (and counting).

Can you (someone, anyone!) define "mite" (for the purposes of this and this alone, not cataloging or identifying!) without referring to 'Acariformes and Parasitiformes'? I think I know one when I see it, but I can't put words around that and Google isn't being very helpful.

**Comment by Jegelewicz** [comment]
How about this

`Ectoparasitic mites are arachnids in the orders Acariformes and Parasitiformes (exclusive of ticks, use ectoparasite: tick for known ticks). Specify specific type and life stage if known in methods/remarks.`

I don't see a problem naming taxa (we are doing this in every other group.

**Comment by dustymc** [comment]
>don't see a problem naming taxa (we are doing this in every other group.

Yea, probably. I like the parenthetical you've proposed.

My remaining question involves the 'ectoparasite:' prefix. I've definitely grabbed mites off of carcasses and later found out they were predatory wanderers - should we remove the 'ecto' bits from this so one could use it in "it's a mite, I don't know why it was there" situations, or should this be reserved for situations in which more information is known?

**Comment by Jegelewicz** [comment]
> should we remove the 'ecto' bits from this so one could use it in "it's a mite, I don't know why it was there" situations, or should this be reserved for situations in which more information is known?

I think this one is pretty specifically "ectoparasitic mites" if we need plain ole "mite", then let's add that too?

**Comment by campmlc** [comment]
I agree - we need this searchable on the "ectoparasite" tag, which is why we decided to use the prefixes. Again, this is just a means of finding hosts that were examined for something and had something detected,  so people can find the records of interest and pursue further. Ideally, we'd have all the resources we need to identify everything down to species level and have everything, all hosts and parasites, ready to catalog in all respective collections and institutions all at once - but that isn't happening. So we need a way to capture these data with the host record at the time of cataloging, and ideally, a means to update the host record over time as more specific information becomes available. Researchers wanting more than "mite" info need to contact the institution and track down the actual mites to confirm IDs, and with this attribute, they can find the records of interest and do so if needed. And as the "mites" get sorted, ID'd, cataloged, and linked via relationships to the host records, they will be able to do so using Arctos tools, although it may be a few decades before this happens.

**Comment by Jegelewicz** [comment]
Added
