### ISSUE TITLE
Using "no higher geography" for captive animals

### ISSUE THREAD

**Issue by adhornsby** [ArctosDB/arctos#6508]
I have a bunch of captive / lab animals that I want to strip of locality data, since it's misleading.  

However, I can't figure out how to apply "no higher geography" (https://arctos.database.museum/editLocality.cfm?locality_id=12058429) when I'm editing the locality for a specimen through "Change [Higher Geography] for this Locality" -> "Pick Geography."

Example specimen: https://arctos.database.museum/guid/UMZM:Mamm:16773

If using "no higher geography" is still an option, how can I find it on the "Pick Geography" search?  Every combination I've tried has failed.  

If it's not an option anymore, what is the best practice for higher geography of captive animals?

**Comment by Jegelewicz** [comment]
> I  have a bunch of captive / lab animals that I want to strip of locality data, since it's misleading.

Why? You will mark them all as captive under collecting source - the location where they were held or dispatched can be very important for people doing certain work. I am begging you not to do this!

**Comment by dustymc** [comment]
>what is the best practice

This:

<img width="477" alt="Screenshot 2023-07-06 at 12 28 34" src="https://github.com/ArctosDB/arctos/assets/5720791/e3ac404d-57ac-4794-a817-120909b85a32">

There are all sorts of questions which can be answered with spatial data and cannot without. I don't think I'll ever see the logic behind denying those data to some researcher who might make good use of them, and Arctos has a robust mechanism to inform users for which purposes a locality might be useful.

**Comment by adhornsby** [comment]
Yes, we have a mechanism to mark as captive.  But on either Arctos or the aggregators, is it easy to filter out captive animals -- or even obvious that that would need to happen?  I'm usually on the other end arguing that researchers are responsible for understanding the data they're using, but this seems like a case where casual and/or big data users could be easily confused unless they're combing through all the specific localities.  Especially hazardous when it's a species found locally, so it wouldn't stand out as extralimital.

I would not (!) totally remove the captivity info from these records.  My thought was to keep the lab/colony info in specific locality, but remove the higher geog.  That this animal came from this facility is relevant, but nothing (?) about the higher geography is relevant except for in being able to verify where that facility is (and I can just add address to specific locality).

If these pros and cons have already been discussed, I'd be happy to read those threads!  I'm still unsatisfied by the fact that captive animals will show up as being from e.g. Missoula County...

**Comment by Jegelewicz** [comment]
>  I'm still unsatisfied by the fact that captive animals will show up as being from e.g. Missoula County...

But they ARE from  Missoula County and saying they aren't is even more misleading IMO. 

>  keep the lab/colony info in specific locality, but remove the higher geog

That is just hiding information and I dislike it! The specloc should be a clue as to the captive nature of a thing along with the captive collecting source.

>  But on either Arctos or the aggregators, is it easy to filter out captive animals -- 

Arctos:
<img width="960" alt="Screenshot 2023-07-06 15 24 41" src="https://github.com/ArctosDB/arctos/assets/5725767/1c6c0b95-08b7-40f2-92a7-7f7cfb05de87">

GBIF:
https://dwc.tdwg.org/terms/#dwc:establishmentMeans exists and can be used to filter out captive and introduced things from a GBIF download.

> or even obvious that that would need to happen? 

Perhaps not, and if we need to make that obvious, then perhaps we need a large red box warning people that museums may also have objects from captive situations. I would prefer to talk about some sort of flag for captive things in downloads or a big button that says "only show me wild stuff" than removing data from it's appropriate location.

**Comment by dustymc** [comment]
>captive animals will show up as being from e.g. Missoula County...

They are, and that might help explain some disease or similar - unless the data are preemptively lobotomized!

>large red box

Arctos also contains casts and prints and replicas and experimental infections and domestics and motorcycles and ... - maybe it should all be red!
