### ISSUE TITLE
Tweak configuration for next accession value (previously: new accession doesn't increment)

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#6509]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
On select new accession in MVZ, it used to know what the last accession was and suggest the next number. It doesn't anymore. Now it says Error Catch [object Object]. Can it be fixed?

<img width="410" alt="Screenshot 2023-07-06 at 10 03 15 AM" src="https://github.com/ArctosDB/arctos/assets/5749672/14e76a43-4389-4f0c-aa6e-b526211cff9e">
<img width="650" alt="Screenshot 2023-07-06 at 10 03 06 AM" src="https://github.com/ArctosDB/arctos/assets/5749672/d7d2938d-752a-44bb-9eca-55a1d3333101">

**Comment by dustymc** [comment]
The "next" logic involves integer accession numbers, it's choking on 2021.001 - and actually there are a BUNCH of non-integer MVZ accessions. I'll need clear instructions (somehow compatible with existing data) specifying what you expect as "next."

**Comment by cjconroy** [comment]
I don't know how to help. The 2021.001 etc. are for MVZ archives, not the specimen accessions. Once you select the collection, doesn't that help figure out the counting?

**Comment by dustymc** [comment]
I was told that all MVZ collections share an accessioning system, and the code was written with that in mind.

I can do something else, I just need to know what should be considered to calculate "next."

**Comment by cjconroy** [comment]
That would be Michelle's department.

**Comment by mkoo** [comment]
Revisiting this issue:
This is the current situation where the error occurs where we expect the next available accession:
![Firefox_Screenshot_2023-11-16T19-35-40 224Z](https://github.com/ArctosDB/arctos/assets/2523089/3c8e89f2-5121-409f-a5fd-f40b551781b8)

We need the new counter to exclude the collection ```MVZ:Arch``` since that uses a different accession series (and type)
