### ISSUE TITLE
Allow general search on Attribute fields to include methods, remarks etc. in Search UI

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6510]
In code table committee meeting today, regarding soft parts vs color, the suggestion was made to allow a means of searching for any term used in attribute types, values, methods, or remarks in the main Search UI.

This would mean that someone searching for "soft parts" would still be able to find values if these words were entered in methods for a "color" attribute. It would mean that someone searching for Mycobacterium leprae would find the records in which this specific bacterium was detected even if the attribute value is "detected = bacterium: Mycobacterium" and "Mycobacterium leprae" is entered in methods or remarks.

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/discussions/6524 might provide a robust solution to this.

**Comment by mkoo** [comment]
Functionally implemented in customized search option
