### ISSUE TITLE
Code Table Request - New terms of use - Ocean Genome Legacy

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6512]
### Goal
_Describe what you're trying to accomplish. This is the only necessary step to start this process. The Committee is available to assist with all other steps. Please clearly indicate any uncertainty or desired guidance if you proceed beyond this step._

Get an incoming institution's collection created.

### Context
_Describe why this new value is necessary and existing values are not._

OGL has their own terms of use.

### Table
_Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table or value. This may involve multiple tables and will control datatype for Attributes. OtherID requests require BaseURL (and example) or explanation. Please ask for assistance if unsure._

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcollection_terms

### Proposed Value
_Proposed new value. This should be clear and compatible with similar values in the relevant table and across Arctos._

OGL Terms of Use

### Proposed URI

https://ogl.northeastern.edu/wp-content/uploads/2023/07/OGL-Terms-of-Use.pdf

### Proposed Definition
_Clear, complete, non-collection-type-specific **functional** definition of the value. Avoid discipline-specific terminology if possible, include parenthetically if unavoidable._

```Ocean Genome Legacy Terms of Use. https://github.com/ArctosDB/arctos/issues/6512``` 

### Priority
_Please describe the urgency and/or choose a priority-label to the right. You should expect a response within two working days, and may utilize [Arctos Contacts](https://arctosdb.org/contacts/) if you feel response is lacking._

High - needed to create collection

@ArctosDB/arctos-code-table-administrators 

## Approval

_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection

_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation

_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

- [ ] Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

- [ ] Add or revise the code table term/definition as described above. Ensure the URL of this Issue is included in the definition.

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by dustymc** [comment]
I edited the definition.

**Comment by Jegelewicz** [comment]
> I edited the definition.

But the URI is needed for the code table...

https://ogl.northeastern.edu/wp-content/uploads/2023/07/OGL-Terms-of-Use.pdf

**Comment by dustymc** [comment]
The URI has its own place - it's the data, everything else is metadata for this.

```
arctosprod@arctos>> \d ctcollection_terms
                                                    Table "core.ctcollection_terms"
       Column        |          Type          | Collation | Nullable |                             Default                             
---------------------+------------------------+-----------+----------+-----------------------------------------------------------------
 collection_terms_id | integer                |           | not null | nextval('ctcollection_terms_collection_terms_id_seq'::regclass)
 display             | character varying(30)  |           | not null | 
 description         | character varying(255) |           | not null | 
 uri                 | character varying(255) |           | not null | 
Indexes:
```

**Comment by Jegelewicz** [comment]
OK - but you removed it from the issue and whoever adds it will need to know what it is!

**Comment by dustymc** [comment]
oh derp how's that?

**Comment by Jegelewicz** [comment]
You replaced the link with the Github issue link! Anyhoo - I added it back.

**Comment by Jegelewicz** [comment]
Fair - I didn't see your new section.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Looks good to me.

**Comment by Jegelewicz** [comment]
I made this request on behalf of OGL (it wasn't MY request) - so I am also checking the second box.

**Comment by Jegelewicz** [comment]
@dustymc I just tried to add this and I get:

<html><body>


ERROR_ID | B55A2A86-D9CF-4A0A-AF20AD8DB79EF2AA
-- | --
ERROR_TYPE | SQL
ERROR_MESSAGE | ERROR: permission denied for sequence ctcollection_terms_collection_terms_id_seq
ERROR_DETAIL |  
ERROR_SQL | insert into ctcollection_terms ( 			display, 			description, 			uri 		) values ( 			'OGL Terms of Use', 			'Ocean Genome Legacy Terms of Use. https://github.com/ArctosDB/arctos/issues/6512', 			'https://ogl.northeastern.edu/wp-content/uploads/2023/07/OGL-Terms-of-Use.pdf' 		)


</body>
</html>

**Comment by Jegelewicz** [comment]
![image](https://github.com/ArctosDB/arctos/assets/5725767/581c4f57-c2bd-4f24-a46a-4ddc384edaa2)

**Comment by dustymc** [comment]
try again

**Comment by Jegelewicz** [comment]
added
