### ISSUE TITLE
Join collection data to loan data in reports

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6513]
@dustymc I am trying to create a generic MSB loan report that would let me fill in the institution and collection descriptions from the information in https://arctos.database.museum/tblbrowse.cfm?tbl=collection

How do I join that table up with `<cf_getLoanFormInfo>` currently in the report?

**Comment by dustymc** [comment]
You can't. Happy to write SQL (or modify the function), but I need specifics. https://github.com/ArctosDB/arctos/issues/5245#issuecomment-1553189252

**Comment by Jegelewicz** [comment]
> Happy to write SQL

I think that's what I need.

**Comment by dustymc** [comment]
Here's a conversation starter:

```
   SELECT
    trans_date,
    concattransagent(trans.transaction_id, 'authorized by') authAgentName,
    concattransagent(trans.transaction_id, 'received by')   recAgentName,
    concattransagent(trans.transaction_id, 'outside contact')   outside_contact_name,
    concattransagent(trans.transaction_id, 'inside contact')   inside_contact_name,
    getAgentNameType(outside_contact.agent_id,'job title') outside_contact_title,
    getAgentNameType(inside_contact.agent_id,'job title') inside_contact_title,
    get_address(inside_contact.agent_id,'correspondence',0) inside_address,
    get_address(outside_contact.agent_id,'correspondence',0) outside_address,
    get_address(inside_contact.agent_id,'email',0) inside_email_address,
    get_address(outside_contact.agent_id,'email',0) outside_email_address,
    loan.return_due_date,
    trans.nature_of_material,
    trans.trans_remarks,
    loan.loan_instructions,
    loan.loan_description,
    loan.loan_type,
    loan.loan_number,
    loan.loan_status,
    shipment.shipped_date,
    case when  concattransagent(trans.transaction_id, 'received by') !=  concattransagent(trans.transaction_id, 'outside contact')  then
        concat('Attn: ',concattransagent(trans.transaction_id, 'outside contact') , '<br>', ship_to_addr.address)
    else
        ship_to_addr.address
    end  shipped_to_address,
    ship_from_addr.address  shipped_from_address,
    getPreferredAgentName(shipment.PACKED_BY_AGENT_ID) processed_by_name,
    getPreferredAgentName(project_sponsor.PROJECT_AGENT_ID) project_sponsor_name,
    PROJECT_AGENT_REMARKS acknowledgement,
    collection.guid_prefix
FROM
    loan
    inner join trans on loan.transaction_id = trans.transaction_id
    inner join collection on trans.collection_id=collection.collection_id
    left outer join shipment on loan.transaction_id = shipment.transaction_id
    left outer join address ship_to_addr on shipment.SHIPPED_TO_ADDR_ID = ship_to_addr.address_id
    left outer join address ship_from_addr on shipment.SHIPPED_FROM_ADDR_ID = ship_from_addr.address_id
    left outer join trans_agent inside_contact on trans.transaction_id = inside_contact.transaction_id and inside_contact.trans_agent_role='in-house contact'
    left outer join trans_agent outside_contact on trans.transaction_id = outside_contact.transaction_id and outside_contact.trans_agent_role='outside contact'
    left outer join project_trans on trans.transaction_id = project_trans.transaction_id
    left outer join project_agent project_sponsor on project_trans.project_id = project_sponsor.project_id and project_sponsor.project_agent_role='Sponsor'
WHERE
    loan.transaction_id=21063292
group by
    trans_date,
    authAgentName,
    recAgentName,
    outside_contact_name,
    inside_contact_name,
    outside_contact_title,
    inside_contact_title,
    inside_address,
    outside_address,
    inside_email_address,
    outside_email_address,
    loan.return_due_date,
    trans.nature_of_material,
    trans.trans_remarks,
    loan.loan_instructions,
    loan.loan_description,
    loan.loan_type,
    loan.loan_number,
    loan.loan_status,
    shipment.shipped_date,
    shipped_to_address,
    shipped_from_address,
    processed_by_name,
    project_sponsor_name,
    acknowledgement,
    collection.guid_prefix
```

**Comment by Jegelewicz** [comment]
Well - that didn't help. I am just trying to be able to add institution and collection from https://arctos.database.museum/tblbrowse.cfm?tbl=collection to use in the header of these reports

MSB Loan Invoice Detail html
MSB Loan Header html 

adding your join line

`inner join collection on trans.collection_id=collection.collection_id`

in MSB Loan Invoice Detail html throws an error. I tried all kinds of stuff and could never get it to work. The other report is using `<cf_getLoanFormInfo>` so adding a join in the reporter doesn't make sense - can it get added in '<cf_getLoanFormInfo>' and at least get me what I want for the header report?

**Comment by dustymc** [comment]
I need links and specifics.

https://arctos.database.museum/Reports/reporter.cfm?action=edit&report_id=91 has been rewritten by Lucee's security engine, whatever you're trying to do ain't gonna work.

```
<invalidTag src="https://unpkg.com/pagedjs/dist/paged.polyfill.js"></script>
```

and the rest of it is some other dialect of SQL, so IDK where you'd add my "join line"

If I can ever understand where you're going with this collection thing I might be able to add it to the cf_ but we're not there, and if we get there that will require a code release.

**Comment by Jegelewicz** [comment]
> has been rewritten by Lucee's security engine, 

That was a copy pasta from MVZ Loan Invoice
https://arctos.database.museum/Reports/reporter.cfm?action=edit&report_id=36 

which is where most of the SQL also came from! I am trying to use things that already work and modify them for MSB needs. I have a working report, but it has things "hard coded" in the header like MUSEUM OF SOUTHWESTERN BIOLOGY  and DIVISION OF MAMMALS that I was hoping I could replace with the information in collection.insitution and collection.collection, which would mean that other collections could just use the report without the need to create a clone and only change those two things.

**Comment by dustymc** [comment]
>copy pasta from MVZ Loan Invoice

I was (and am) very lost then, but here's SQL from there with a join to collection added

```
select 
    flat.collection, 
    flat.collection_cde, 
    flat.cat_num, 
    flat.scientific_name, 
    flat.sex, 
    flat.collectors, 
    flat.verbatim_date verbatim_date, 
    flat.collection_object_id, 
    specimen_part.part_name as part, 
    case 
        when part_name='whole organism (formalin-fixed, 70% ethanol)' then '70% ETOH' 
        else part_name 
    END part_name, 
    coll_object.condition part_condition, 
    CASE WHEN length(coll_object.condition) > 15 or flat.ENCUMBRANCES is not null THEN 'X' end AS has_appendix, 
    concat_ws('. ', higher_geog, spec_locality, verbatim_coordinates, flat.datum) as locality, 
    item_instructions, 
    loan_item_remarks,
    coll_object.coll_obj_disposition, 
    flat.ENCUMBRANCES, 
    loan.loan_number, 
    trans.trans_date, 
    flat.datum, 
    flat.verbatim_coordinates,
    collection.guid_prefix
from 
    loan_item
    inner join loan on loan.transaction_id = loan_item.transaction_id
    inner join trans on loan.transaction_id = trans.transaction_id 
    inner join collection on trans.collection_id=collection.collection_id
    inner join specimen_part on loan_item.collection_object_id = specimen_part.collection_object_id
    inner join coll_object on specimen_part.collection_object_id = coll_object.collection_object_id
    inner join flat on specimen_part.derived_from_cat_item = flat.collection_object_id
WHERE 
    loan_item.transaction_id=1005278

```

>MUSEUM OF SOUTHWESTERN BIOLOGY and DIVISION OF MAMMALS t

Yea, that's where I got lost and unsuccessfully asked for help a [while back](https://github.com/ArctosDB/arctos/issues/5245#issuecomment-1553189252) - those things aren't in [the data](https://arctos.database.museum/collection/MSB:Mamm) and if what's being asked for isn't there.....

**Comment by Jegelewicz** [comment]
OK - here is what happens. When I try to use '#guid_prefix#' I get this error - The key [GUID_PREFIX] does not exist. What step am I missing?

**Comment by dustymc** [comment]
link please

**Comment by Jegelewicz** [comment]
https://arctos.database.museum/Reports/reporter.cfm?action=edit&report_id=91

**Comment by dustymc** [comment]
https://arctos.database.museum/Reports/reporter.cfm?action=view&report_id=91&&transaction_id=1005278

<img width="1163" alt="Screenshot 2023-07-07 at 15 34 06" src="https://github.com/ArctosDB/arctos/assets/5720791/781a1a0b-cea8-47b6-9988-b701daec61a9">


????????

**Comment by Jegelewicz** [comment]
It works because I took out '#guid_prefix#'

Go try it now

**Comment by dustymc** [comment]
Scope!

I did a 'living dangerously' patch - it should be rewritten if there's any chance collection-stuff isn't unique (but IDK how any of this would work then so again I'd need some sort of direction).

Reload.

**Comment by Jegelewicz** [comment]
DOH! OK - it works, but now I know the users won't be happy with what they have in institution and collection! But this gives everyone an idea....

THANKS!!!
