### ISSUE TITLE
Feature Request - allow Bulk Loan Items for those with manage_transactions

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#6516]
Is there a reason why the permission/role for bulkloading loan items ([Loan: Item Bulkload](https://arctos.database.museum/tools/BulkloadLoanItem.cfm)) is tied to Manage_collection and not manage_transactions?

If there is not a reason (aside from legacy) than I would like to request that be shifted to manage_transactions since it seems to be a pretty solid Loan activity and not a collection management one! But let me know as I could easily have forgotten/overlooked why it's set up like this. Thanks

**Comment by dustymc** [comment]
The form itself needs (manage_records,manage_transactions) - it will tell you that, and that can be changed (but I think it's probably correct here, https://arctos.database.museum/Admin/user_roles.cfm) . Permissions can't quite deal with that, but I set it to manage transactions which is the more "core" of the two.

**Comment by mkoo** [comment]
ah good! so I can "relieve" the user of manage_collection then?!
Thanks
