### ISSUE TITLE
why does download collecting event (from search) exist?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6517]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

I was working on making the tools dropdown in search results more readable and I noticed that the collecting event download could benefit from being more like the parts and identifiers view tables functionality. 

**Describe what you're trying to accomplish** 
An clear and concise overview of the goals; why are you asking for this?

I have been making a lot of use of the identifier and part table view/download tools and they work great! I'd like to be able to do the same with collecting events.

**Describe the solution you'd like**
How might we accomplish your goals?

Instead of "download Collecting Events, have a tool that works just like the part and identifier view tables that let's me filter the Events and then download the ones I need.

**Describe alternatives you've considered**

Use the current download tool and filter them myself. This works, but is inconsistent with the other tools.

**Additional context**

Adding this functionality would make all of the View/download tolls work consistently which makes for a better user experience.

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by dustymc** [comment]
Events are their own thing with their own UI, not children of records - this already exists as manage/events.

**Comment by Jegelewicz** [comment]
Hmmm - OK, makes sense and I guess we will just have the one weird "download some stuff without looking at it" thing.

**Comment by dustymc** [comment]
>one weird "download some stuff without looking at it" thing

Uhh - yea, why's that there?  Manage/events has a download. I'll assume it's a pre-current-event-UI leftover and nuke it unless someone tells me otherwise
