### ISSUE TITLE
Arctos Down - Planned Outage for updates

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6518]
Please complete to the best of your ability.

## Planned Outage
 - Date and time outage will begin: July 21, 2023 8 AM PDT
 - Date and time outage is expected to end: July 22, 2023 8 AM PDT
 - Reason for outage: Updates to data entry, bulkloader, idetifications
 - Expected behavior during and after the outage: No access. If the update takes less time an announcement will be made that Arctos is available via email.

## Communication before/during outage
- [x] Pin this issue
- [x] Banner updated @jegelewicz @mkoo
- [x] Email sent to AWG  
- [x] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [x] Unpin this issue
- [x] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by Jegelewicz** [comment]
# Banner

Arctos will be offline on Friday, July 21st as we implement the new data entry and bulkloader formats. Data in the bulkloader at the time will be migrated to the new bulkloader format. If you have data in process in Excel or some other file format, please note that the bulkloader after July 21st will require a new set of column headers. Mapping from the old to the new column headers can be found [here](https://docs.google.com/spreadsheets/d/1qstLM0xpW8gkkEnRxUpZWOZGtJkv2NTu8zIgKxv-nYc/edit?usp=sharing). If you need help transitioning to the new headers, please let us know by [filing an issue](https://github.com/ArctosDB/arctos/issues/new).

**Comment by lin-fred** [comment]
Sent out tweet with all information. 
Also scheduled a reminder tweet about Arctos being down for that Thursday before

**Comment by ewommack** [comment]
Email sent out to AWG and another scheduled for Friday morning right before the outage so people know why we are down.

**Comment by DerekSikes** [comment]
In looking over the new BL column names, they all make sense and I like how their sort order will make fields of interest easier to find in a list (eg if filtering by them in the SQL editor); however - what's up with 
georeference_source	-> locality_attribute_6_value ?

All the other georeference fields are getting rennamed with 'coordinate', eg 

georeference_protocol	-> coordinate_georeference_protocol

I would think 

georeference_source	would become coordinate_georeference_source ????

**Comment by dustymc** [comment]
>georeference_source

https://github.com/ArctosDB/arctos/issues/5331 / https://github.com/ArctosDB/arctos/issues/5120

**Comment by Jegelewicz** [comment]
@DerekSikes georeference_source will be moved to a locality attribute. This was the best way I could think to demonstrate that in the mapping.

**Comment by dustymc** [comment]
Arctos is now tentatively available, but many services have been disabled to prioritize cache rebuild, which should take around 48 hours. I can turn access restrictions back on if this is problematic. Please let me know if you encounter any problems.
