### ISSUE TITLE
Bulkload locality stuck

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#6521]
I was bulkloading some localities yesterday afternoon. Half of them loaded just fine right away, the remaining 18 have not (they are still set to autoload, not throwing errors or anything). I moved bulkload localities up to the top of the component loader status, but this didn't help. This was about the time Arctos went down, so I decided to let them sit overnight, but they're still there this morning.

**Comment by dustymc** [comment]
That loader was involved in some instability yesterday, I'll get it turned on as soon as I can.

**Comment by dustymc** [comment]
@Nicole-Ridgwell-NMMNHS I think it's going to be a while - the localities which use California geog are doing nasty things to the DB. (So this probably is a bug, just not one which I have any control over - not sure how to categorize that.) I don't know if that's generally true, or big-shape true, or just CA true. If you want to create the localities without spatial data (or with point-radius, I think) I can help update them later. I'm working on getting a consultation with TACC's PG folks which will hopefully lead to a solution, I'll ping you here when I know more.

We probably do need to remove those from the loader so other things can run, I'll do that and get you the data if they're still hanging out in a bit.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Data removed from bulkload. Can I run it without the California localities?

**Comment by dustymc** [comment]
Please don't try today - Chris is busy all day and I don't have access to kill what this wedges.

**Comment by mkoo** [comment]
What is the status of this? I am confused as the source of the error-- bulkloader, gadm authority, or what?

**Comment by dustymc** [comment]
>What is the status of this?

Nothing has changed, as far as I know.

>source of the error-

It came from the bulkloader, but any operation that re-uses geography shapes (Maybe just big ones? The scope isn't clear) for localities seems capable of breaking things that I can't fix.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Can I try this again, taking out the California localities and doing those manually?

**Comment by dustymc** [comment]
Maybe try at test (or send me some data) - the stuff that kills prod seems to pretty reliably kill test too. And maybe don't try in the evening (Austin time), I still can't un-wedge what this wedges. (And I still haven't heard from TACC....)

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Here is the set I was trying to load before it stuck:

[L-13002-13019_wontload.csv](https://github.com/ArctosDB/arctos/files/12743379/L-13002-13019_wontload.csv)

and that set without California:

[L-13002-13019_wontload_noCA.csv](https://github.com/ArctosDB/arctos/files/12743388/L-13002-13019_wontload_noCA.csv)

**Comment by dustymc** [comment]
Seems happy at test (after I zapped an old column) and Chris was around this AM - goferit....

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks! I was able to load the non-CA ones. Should I leave this open since it still wouldn't load with big geography and USE_GEOGRAPHY_POLYGON?

**Comment by dustymc** [comment]
Yes definitely leave this open, there's still a problem.

>still wouldn't load 

That probably means we're about to have some unscheduled downtime....

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I took it out of the loader as soon as I saw it wasn't going and there wasn't anything else queued up in the component loader and it seems like we're still up.

**Comment by Jegelewicz** [comment]
@dustymc let me make sure that I understand - the real issue is that using use_geography_polygon = TRUE gums up the works?

I have over 5000 rows in the locality bulkloader and a bunch of them include use_geography_polygon = TRUE

Before I just set everything to load - let me know if I need to change all of those to FALSE....

**Comment by dustymc** [comment]
>use_geography_polygon = TRUE gums up the works?

Yes, and the one person who can un-gum is away until Friday.

**Comment by Jegelewicz** [comment]
OK - I will just leave them in the loader for now - I won't be immediately using them anyway.

**Comment by dustymc** [comment]
@mkoo can you help with this please, I really don't like being one "OO, that looks neat!" from a potentially-catastrophic crash. SOMETHING (that I can't see, much less control) must be wrong at TACC, and I've still not heard from their postgis folks.

**Comment by Jegelewicz** [comment]
@dustymc @mkoo this is now preventing the use of Arctos to convert from degrees minutes seconds or degrees decimal minutes to decimal degrees within Arctos?

![image](https://github.com/ArctosDB/arctos/assets/5725767/ccbec8a5-a592-4a30-b088-d3ea4a866c4c)

What can we do to fix that? The loss of something seemingly simple is making my life difficult and when trying to help collections migrate legacy data, saying we cant convert coordinates is making me sad. If I am missing something here, please set me straight.

**Comment by dustymc** [comment]
> preventing the use of Arctos to convert from degrees minutes seconds or degrees decimal minutes to decimal degrees within Arctos?

I think you need <img width="173" alt="Screenshot 2023-11-02 at 08 39 41" src="https://github.com/ArctosDB/arctos/assets/5720791/a314b664-e814-4917-8fd3-0ac90bbeab71"> not <img width="143" alt="Screenshot 2023-11-02 at 08 39 37" src="https://github.com/ArctosDB/arctos/assets/5720791/b71c802b-1465-421a-83b0-e08493d7a04c"> ??

**Comment by Jegelewicz** [comment]
Sorry - overwhelmed...

**Comment by Jegelewicz** [comment]
Are we done here?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I don't think use_geography_polygon has ever been fixed?

**Comment by mkoo** [comment]
done
