### ISSUE TITLE
show subgenus on specimen pages e.g. Genus (Subgenus) species

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#6523]
Not sure where to file this. 
We have a number of taxonomic revisions we are working on that include adding subgenus to the taxonomic hierarchy. While they can be easily added to the taxonomic hierarchy, and will show in the fine print in the identification box, they do not show up on the specimen page in large font with the Genus and species under the catalog number. 
How hard would it be to have a specimen page show something like:

Lasiurus (Dasypterus) xanthinus

**Comment by dustymc** [comment]
See also https://github.com/ArctosDB/arctos/issues/6302 (and I think there's another involving 'formatted names' as identifications, but I can't find it).

>with the Genus and species under the catalog number.

As a point of clarification, that is ``identification.scientific_name``

You can use the ``A {string}`` formula to make identifications of near any form.

That (or any) format could be a term in your preferred classification, and there could potentially be some sort of tool that makes using some classification term as the ID easier. None of that seems very technically challenging, but I would need a lot of guidance on how it might be put together, and it would probably need to involve managing classifications (I doubt I can reliably extract ANYTHING out of the legacy nightmares).

**Comment by sharpphyl** [comment]
We discussed in 2019 in [#2098 ](https://github.com/ArctosDB/arctos/issues/2098) that Arctos does not allow subgenera in the taxon names.  See Dusty's comment at https://github.com/ArctosDB/arctos/issues/2098#issuecomment-498868685

For mollusks, we need subgenera mostly for legacy names, not for the accepted identification as subgenera are not the preferred name in WoRMS.  It's a bigger issue for echinoderms, corals, etc.

For WoRMS (via Arctos) we use the WoRMS classification with the subgenus and link it to the taxon name without the subgenus.  So, there is a mismatch between the Arctos taxon name and the WoRMS species.  We use a lot of strings too.

I fully understand the potential for taxonomic messes if parentheses are added to taxonomic names, but when there is an external, vetted source such as WoRMS controlling the taxon name and classification, it would be an helpful to allow subgenera in the taxon name which would then appear in the catalog record.

**Comment by Jegelewicz** [comment]
At today's taxonomy committee meeting, @sharpphyl expressed that they are able to work with subgenera using a combination of the A {string} and classification. @cjconroy an we close this issue?

**Comment by Jegelewicz** [comment]
Closing as there is a workable solution
