### ISSUE TITLE
Code Table Request - Add part=spine for Invertebrate Collections

### ISSUE THREAD

**Issue by genevieve-anderegg** [ArctosDB/arctos#6525]
### Request
Add ctspecimen_part_name=spine for Invertebrate type collections. Per the current spine definition: "In a zoological context, spines are hard, needle-like anatomical structures found in both vertebrate and **invertebrate** species. The spines of most spiny mammals are modified hairs, with a spongy center covered in a thick, hard layer of keratin and a sharp, sometimes barbed tip. Wikipedia. For fish see Wikipedia". 

### Goal.
We have a sea urchin spine we would like to database.

### Context
Spines are not the same things as "tests" in sea urchins, which is the hard shell. Spines are attached to the hard shell via soft tissue "tubercles", and are used for locomotion and defense. It would also be incorrect to call spines a portion of an exoskeleton, because the test of an urchin is actually an endoskeleton. [Wikipedia](https://en.wikipedia.org/wiki/Sea_urchin)

### Table
[Specimen_part_name](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name)

### Collection type
Collection Code = Inv

**Comment by Jegelewicz** [comment]
The part name exists

[spine]{https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#spine}

if you are OK with the definition, I can just add it for Inv collections.

**Comment by Jegelewicz** [comment]
Oh wait - I see now that is all you are asking...done

**Comment by genevieve-anderegg** [comment]
Thank you!!
