### ISSUE TITLE
Feature Request - Locality Name Lookup Tool

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6526]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

**Describe what you're trying to accomplish** 
An clear and concise overview of the goals; why are you asking for this?

I have a list of named sites that I would like to compare to named localities in Arctos to see if I can use localities that are already entered.

**Describe the solution you'd like**
How might we accomplish your goals?

A Lookup tool like the taxon name checker that compares my list of names to Arctos Locality names.

**Describe alternatives you've considered**

Searching them one by one (there are 457 of them)

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

This will help me get the UNM Geology data migrated.

**Comment by dustymc** [comment]
Your taxon reference makes my brain hurt...

Maybe the most practical approach would be to allow place search to accept lists, which would require choosing some delimiter and somehow doing something when it's inevitably used as data, but I'm not sure I'm understanding this request either. (Surely you need something beyond "some random thing is named this random thing"?!)

**Comment by Jegelewicz** [comment]
> some random thing is named this random thing

That's probably true for a bunch of things, BUT when I entered the NMMNH Geol data, I made a lot of the mines named places. Now I have data from UNM Geol and they have some mine names. I'd prefer to use the already-named mine localities whenever possible. Anyhoo - I did a locality name search for stuff with "mine" and I'm using that. Still, I could see some utility for this kind of lookup - but maybe it would be more like the Agent prebulkloader - just helping me find exact matches (including higher geography) and then all the other potential matches if any.

**Comment by dustymc** [comment]
Some SQL, which seems like a sufficient tool for future instances of this:

```
select locality_name from locality where locality_name ilike '% mine'


       locality_name        
----------------------------
 Abenab Mine
 Adventure Mine
 Aguas Claras Mine
...
 White Raven Mine
 Yaogangxian Mine
(111 rows)


select locality_name from locality where locality_name in ('Abenab Mine','Adventure Mine','ADVENTURE Mine','not this one')


 locality_name  
----------------
 Abenab Mine
 Adventure Mine
(2 rows)


```
