### ISSUE TITLE
remove flat column "ATTRIBUTES"

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6528]
**Is your feature request related to a problem? Please describe.**

We are currently caching a concatenation of record attribute ``type=value`` as "attributes" and I don't think it's useful nor being used. (It's being queried in at least one DMNS report, but the value is not used there.)

**Describe what you're trying to accomplish** 

Conserve resources when possible.

**Describe the solution you'd like**

Remove this from the cache

**Describe alternatives you've considered**

There are none.

**Additional context**

This would save several hours of CPU if it can be done by Friday!

**Priority**

See above, otherwise nocritical.

**Comment by dustymc** [comment]
I'll assume enthusiastic support for this if I don't hear otherwise by ~1 Feb.

**Comment by AJLinn** [comment]
Will this significantly delay searches in attributes as a result? These are often key search criteria in cultural collections. 

Sorry if I don't quite understand what you're proposing to eliminate... is this the attribute "value" (as in the field we use to record the appraised value of our collections?)

**Comment by dustymc** [comment]
>delay searches

Nope.

>is this the attribute "value"

Nope.


>proposing to eliminate

A column that I think isn't used (but is fairly expensive to compile and maintain). The data in it are

```
    string_agg(concat_ws(' ',concat_ws('=',attribute_type,attribute_value),attribute_units),';')
```
