### ISSUE TITLE
Feature Request - Locality Bulkloader should include locality attributes

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6535]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

I can create localities with attributes using the main bulkloader - I should be able to do the same with the locality bulkload tool

**Describe what you're trying to accomplish** 
An clear and concise overview of the goals; why are you asking for this?

Make bulkloading tools consistent

**Describe the solution you'd like**
How might we accomplish your goals?

Add locality attributes to the locality bulkload tool - https://arctos.database.museum/tools/bulkloadLocality.cfm

**Describe alternatives you've considered**

Manually create any locality that includes attributes.

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by dustymc** [comment]
The alternative (which, unlike what's being proposed, carries no limitations) is to create the locality, then load the attributes. Suggest this not proceed unless some compelling and tangible fatal flaw with the normalized approach can be identified.
