### ISSUE TITLE
Duplicate "Collecting" Events - MCZBase Experiment

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6538]
I had a discussion with Charles Farnum from Harvard at Digital Data. He presented a poster about a Python script he has written to find duplicate events. He's been using this on data from MCZBase but is looking for other data to experiment with. Based upon his criteria (attached), I figured that Arctos Data would be perfect for testing his script so I searched for all of the NMMNH bio collections (34,039 records) and used the Manage Collecting Event tool which returned 16,982 events. I downloaded that and will send the file to Charles for testing his script.

[Event Duplication detection data requirements.pdf](https://github.com/ArctosDB/arctos/files/12110314/Event.Duplication.detection.data.requirements.pdf)

**Comment by dustymc** [comment]
done?
