### ISSUE TITLE
Creating Field Museum Links

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6540]
We can create links to Field Museum records with some research. See the process below. As an example, Adding  https://db.fieldmuseum.org/9478d7bc-b47c-4347-a966-e2405f29c387 as an identifier issued by Field Museum to  https://arctos.database.museum/guid/MVZ:Bird:178148 will let you hop right over to the Field's record.

I don't have edit access to any of the records that could use these links, but I have found them and set up an identifier bulkload for those with matches (attached). @ccicero @cjconroy @ebraker you all have links to add in the file. Emily - note that the three you have sharing three identifiers can be disambiguated because the Field has used your catalog numbers as Field # in their records.

There are two records that don't seem to match with the Field Museum record:

GUID | OTHERCATALOGNUMBERS | Link to Field Museum Record
-- | -- | --
CHAS:Bird:18054 | institutional catalog number=FMNH-1525 | https://db.fieldmuseum.org/363a585c-59fd-4448-8264-4a438efad25d
MVZ:Bird:178150 | institutional catalog number=FMNH-313427 | https://db.fieldmuseum.org/5fcf26ff-7910-4b85-ad32-025cb9f1c115

The UNR identifiers issued by the Field Museum, do not appear to be catalog numbers, but dates and need to be reviewed and moved to a more appropriate identifier or field. @acoconis 

GUID | OTHERCATALOGNUMBERS
-- | --
UNR:Mamm:2028 | institutional catalog number=67-8-3
UNR:Mamm:2044 | institutional catalog number=69-8-7
UNR:Mamm:2047 | institutional catalog number=69-8-2
UNR:Mamm:2048 | institutional catalog number=69-8-8
UNR:Mamm:2050 | institutional catalog number=69-8-16
UNR:Mamm:2418 | institutional catalog number=TU-70-6-5
UNR:Mamm:2420 | institutional catalog number=TU-70-6-6
UNR:Mamm:2520 | institutional catalog number=69-8-24
UNR:Mamm:2536 | institutional catalog number=70-4-9
UNR:Mamm:2537 | institutional catalog number=1970-04-06
UNR:Mamm:2538 | institutional catalog number=1970-04-05
UNR:Mamm:2539 | institutional catalog number=70-4-10
UNR:Mamm:2542 | institutional catalog number=69-8-23
UNR:Mamm:2543 | institutional catalog number=69-8-19
UNR:Mamm:2544 | institutional catalog number=70-4-11
UNR:Mamm:2596 | institutional catalog number=70-7-3
UNR:Mamm:2616 | institutional catalog number=69-8-18

Arctos - digitally extending specimens whenever we can (even if everyone else makes it hard...)

[Field Museum Links.csv](https://github.com/ArctosDB/arctos/files/12112185/Field.Museum.Links.csv)

**Comment by Jegelewicz** [comment]
Here's how this works:

https://arctos.database.museum/guid/MVZ:Bird:178148 claims to also use the catalog number FMNH-313428. Sure enough, that seems correct. If I search the bird collection at FMNH, I get a match with this urn: https://collections-zoology.fieldmuseum.org/catalogue/1566655. 

But to get the long identifier, I first need to know it exists, then I need to scroll down the detail page to find 9478d7bc-b47c-4347-a966-e2405f29c387 (which is kinda greyed out and hard to see), then concatenate that with [https://db.fieldmuseum.org/](https://db.fieldmuseum.org/d48d9623-4c00-4966-98e9-39d2536b5793) to get https://db.fieldmuseum.org/9478d7bc-b47c-4347-a966-e2405f29c387 which works to link me up to the Field's record. I'll ask The people at MVZ to add this to their record.

Suggestions for making this easier are appreciated. Right now, I can see 35 identifiers in Arctos that are supposedly issued by the Field - unfortunately, I do not have edit access to any of the collections that are using them, so I have to ask people to take time to test this out. 35 isn't a ton and I could spend the time to look them all up - I probably will at some point when I need to calm my brain for an hour or two...

**Comment by ebraker** [comment]
UCM Field identifiers are entered, thanks!

**Comment by ccicero** [comment]
FMNH identifiers for MVZ birds, mammals, herps also entered, thanks!

**Comment by Jegelewicz** [comment]
> Teresa,
> 
> So it seems that these specimens were labeled at the Field Museum (perhaps in the field) with these numbers before being transferred the UNR Museum. Attached are two pictures of both sides of the skin specimen label of the first specimen on the list (UNR:Mamm:2028). These Field Museum numbers seem to closely align the to date of collection, but not exactly.
> 

Ally

**Comment by Jegelewicz** [comment]
Sent to the Field:

<html>
<body>
<span style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Janeen,</span><div style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br></div><div style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">I don't know if you can help with this, but if not, perhaps you can pass it on to the appropriate person.</div><div style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br></div><div style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">The University of Nevada, Reno has some mammal specimens that include a Field Museum number that is not one of your catalog numbers. Here is a list of them:</div><div style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br></div><div style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Arctos GUID | FMNH Number
-- | --
https://arctos.database.museum/guid/UNR:Mamm:2028 | 67-8-3
https://arctos.database.museum/guid/UNR:Mamm:2044 | 69-8-7
https://arctos.database.museum/guid/UNR:Mamm:2047 | 69-8-2
https://arctos.database.museum/guid/UNR:Mamm:2048 | 69-8-8
https://arctos.database.museum/guid/UNR:Mamm:2050 | 69-8-16
https://arctos.database.museum/guid/UNR:Mamm:2418 | TU-70-6-5
https://arctos.database.museum/guid/UNR:Mamm:2420 | TU-70-6-6
https://arctos.database.museum/guid/UNR:Mamm:2520 | 69-8-24
https://arctos.database.museum/guid/UNR:Mamm:2536 | 70-4-9
https://arctos.database.museum/guid/UNR:Mamm:2537 | 1970-04-06
https://arctos.database.museum/guid/UNR:Mamm:2538 | 1970-04-05
https://arctos.database.museum/guid/UNR:Mamm:2539 | 70-4-10
https://arctos.database.museum/guid/UNR:Mamm:2542 | 69-8-23
https://arctos.database.museum/guid/UNR:Mamm:2543 | 69-8-19
https://arctos.database.museum/guid/UNR:Mamm:2544 | 70-4-11
https://arctos.database.museum/guid/UNR:Mamm:2596 | 70-7-3
https://arctos.database.museum/guid/UNR:Mamm:2616 | 69-8-18

</div><div style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br></div><div style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">I thought that these must be dates, so I asked UNR about them. They sent me an image of one of the labels which is attached. The label indicates it is some sort of Field Museum number.</div><div style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br></div><div style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">I've tried searching for these numbers in many formats, but haven't found any matches in y'all's data. Can you figure them out? I'd love to link these up with your records if possible!</div><div style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br></div><div style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Thanks!</div><span class="im" style="color: rgb(80, 0, 80); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div><br></div><div><div><div dir="ltr" class="gmail_signature" data-smartmail="gmail_signature"><div dir="ltr"><div dir="ltr"><span style="font-family: arial, helvetica, sans-serif;"><font size="4">Teresa J. Mayfield-Meyer</font></span></div></div></div></div></div></span>
</body>
</html>

**Comment by Jegelewicz** [comment]
> Hello Janeen and Teresa,
> 
> What an interesting mystery, especially considering these FMNH tags appear to have been pre-printed for an expedition to Turkey! 
> 
> Sadly, I used various information from the Arctos links to search for these specimens and nothing came back.
> 
> I searched by locality, year, taxon, and collector in various combinations and we do not have any specimens recorded in the database that meet the criteria for either the Mustela erminea or the Peromyscus maniculatus records I took the search terms from. 
> 
> For example, we have zero specimens collected by RW Rust in our collection and there is no Mustela erminea from that specific locality nor Nevada County. The only Mustela we have from California are all from different counties/locations. 
> 
> I presume there's no useful information on the other side of the tag? 
> 
> Finally, I also searched for any loans related to UN Reno and came up with nothing. There are no specimens or transactions linked to that institution, which there should be. 
> 
> Janeen, interestingly we have a record for R.W. Rust (IRN 101399) but it is only linked to a single Accession record (IRN 15738) for specimens from the Street Expedition to Iran collected in 1968. Our party records for University of Nevada Reno (IRN 103943) and BRRC at UNR (IRN 223940) also do not appear to be linked to any existing records in EMu, with the exception of BRRC at UNR which is linked to a party record (161124). 
> 
> The mystery continues...

Adam
--
Adam W. Ferguson, Ph.D. (he/him/his)
Negaunee Collection Manager of Mammals
Field Museum

> Adam,
> 
> Thank you so much for doing this research! Perhaps this is a case of re-using tags?
> 
> As for your question about the back of the tag, here you go - I don't know if any of it will help!
> 
> Adios,

Teresa J. Mayfield-Meyer

> Hi all,
> 
> Given all of this information, it does seem to be the best guess is that these tags were printed for a different purpose and not used, then re-purposed for an entirely different project and entirely different country.
> 
> I have seen things like this a few times before; it is easy to reach for a stack of specimen tags and use what is available.  This does not solve the mystery, but it does suggest that it may not be possible to learn more.
> 
> Best regards to all,

Larry

--
Lawrence R. Heaney
Negaunee Curator of Mammals
Field Museum of Natural History

**Comment by Jegelewicz** [comment]
> Ally,
> 
> The Field looked into these and you can see my correspondence with them [here](https://github.com/ArctosDB/arctos/issues/6540#issuecomment-1656199341). I don't think these are actually Field Museum numbers even though they are on Field Museum tags. I'd like to change these in Arctos to look like this:
> 
> Identifier | IssuedBy | Type | AssignedBy | Remarks
> -- | -- | -- | -- | --
> 67-8-3 |   | identifier | jegelewicz | This specimen has a Field Museum   tag with this number, however, the Field Museum does not have any numbers   that match and it is assumed that this pre-printed tag was used outside of   its initial purpose. See https://github.com/ArctosDB/arctos/issues/6540
> 
> If you agree, I will ask Dusty to make the changes. If you would prefer something different, just let me know!
> 
> Thanks!

Teresa J. Mayfield-Meyer

**Comment by Jegelewicz** [comment]
> That sounds great, Teresa. I did see your correspondence with them, and this path forward seems best.
> 
> Best,
> 

Ally Coconis

**Comment by Jegelewicz** [comment]
@dustymc can you make [this](https://github.com/ArctosDB/arctos/issues/6540#issuecomment-1656212496) happen for [these](https://github.com/ArctosDB/arctos/issues/6540#issuecomment-1652296652) or do I need to make some load/unload files for Ally? (I don't have edit access to their collection).

**Comment by dustymc** [comment]
I can update but I need some sort of CSV or something please, Just In Case.

**Comment by Jegelewicz** [comment]
Will this do?
[Field Museum Links.csv](https://github.com/ArctosDB/arctos/files/12198698/Field.Museum.Links.csv)

**Comment by dustymc** [comment]
Not with those headers! Danged Excel users....

Done.

**Comment by Jegelewicz** [comment]
Looks like I left @wellerjes off the notification list above. You can create links to your Field Museum collections. Use the data in the file [here](https://github.com/ArctosDB/arctos/issues/6540#issue-1814438421). More information about this is [here](https://github.com/ArctosDB/arctos/issues/6540#issuecomment-1644278310).

**Comment by Jegelewicz** [comment]
How can we make this obvious for the next collection coming in with Field Museum catalog numbers?

**Comment by dustymc** [comment]
>obvious

You could add something to the Identifier Helper, but I'm not sure how much we can DO when there are two completely disjointed identifiers involved.

**Comment by Jegelewicz** [comment]
> You could add something to the Identifier Helper

But I can't? How do you add things? I can edit existing stuff, but there is no add button.

**Comment by dustymc** [comment]
I guess that's still in test.

**Comment by Jegelewicz** [comment]
Helper added with link to the instructions above.
