### ISSUE TITLE
[external CONTACT] NCBI linkouts

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#6543]
@dustymc Did we lose the linkouts for NCBI identifiers (GenBank, SRA, BioSample) when we migrated to the 'Assigned by' model? The identifiers are there but they're not linking out.

https://arctos.database.museum/guid/MVZ:Bird:193978
https://arctos.database.museum/guid/UAM:Mamm:21440

???

**Comment by dustymc** [comment]
Ugh, we're still stuck in the denormalizedland.

Once we actually migrate it'll look like https://arctos-test.tacc.utexas.edu/guid/MVZ:Bird:165389 / https://arctos-test.tacc.utexas.edu/guid/MVZ:Bird:192114

We really need to finish the migration, but if that's not possible I could update by collection - @mkoo, chat early next week?

**Comment by ccicero** [comment]
@dustymc ok, thanks.

**Comment by mkoo** [comment]
Fixed
