### ISSUE TITLE
UTM what's going on?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6544]
We provide columns for UTM, but no good direction for using them that I can find and once loaded, they seem to just disappear. What are we doing with these? If nothing, then why do we have places to put them? I just loaded six records in the bulkloader with data in

coordinate_utm_zone
coordinate_utm_ew
coordinate_utm_ns

And the data from those columns is MIA

**Comment by dustymc** [comment]
I need some sort of a clue - data, how do I find the records, something more than nothing please....

**Comment by dustymc** [comment]
Thanks!

Those did not have a coordinate_lat_long_units, which will result in the coordinates being ignored. (They also don't have valid zones, but that'll just result in an error.)

**Comment by Jegelewicz** [comment]
> did not have a coordinate_lat_long_units
I had UTM in there and they would NOT load - kept giving me `coordinate value error`

Which I guess is because:

> They also don't have valid zones, but that'll just result in an error

BUT they were all 12S [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctutm_zone#12s) which is in the code table?

**Comment by Jegelewicz** [comment]
In any case - can they be added after the fact?

**Comment by Jegelewicz** [comment]
and yes, I tried loading them with World Geodetic System 1984 as the datum....

**Comment by Jegelewicz** [comment]
@dustymc there is one of these left in Browse and Edit - https://arctos.database.museum/Bulkloader/editBulkloader.cfm?key=key_17987

The current error is `Coordinate conversion failed: incompatible datum`

coordinate_datum = [World Geodetic System 1984](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctdatum#world_geodetic_system_1984) 
utm_zone =  [12S](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctutm_zone#12s) which suggests "WGS 84 / UTM zone 12S"

What am I doing wrong here?

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/6428

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctutm_zone#12s bad.

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctutm_zone#wgs84___utm_zone_12s good.

**Comment by Jegelewicz** [comment]
Sigh - why do we keep stuff that doesn't work in the code table - leading me to believe it is something useful? OK, done ranting.

**Comment by Jegelewicz** [comment]
Can we highlight the ones that won't work in data entry? Give me a list and I will add something to the description to let people know they aren't available for use.

**Comment by dustymc** [comment]
>why do we keep stuff that doesn't work in the code table

https://github.com/ArctosDB/arctos/issues/4169#issuecomment-1573927120 - there's apparently something that needs to happen before we can clean up, I don't understand it, I've been asking for help. HELP!

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
#4169 is not a UTM issue, so I wouldn't think this would depend on that.

I'd be very happy to meet about both issues.

**Comment by mkoo** [comment]
HI @Nicole-Ridgwell-NMMNHS let's meet to talk-- if it's a matter of converting UTM's I am happy to just do it so you can move forward. We are cleaning up the CT very soon as we've just wrapped up what needs to be done (remove dependencies on very old data)

So for now I am closing this issue and please email me when convenient! (mkoo@berkeley.... etc)
