### ISSUE TITLE
collecting event editing error?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6545]
Please complete to the best of your ability.

## Unplanned Outage
 - Date and time (**please add time zone from which you are reporting**) outage discovered: 2023-07-24 10:15 PDT
 - Describe the outage (Arctos down or only some part not working?): No matter what I try to do I get some version of this error:

An error has occurred. Please include the ErrorID as text in any communications. 
ErrorID: E1A003DC-E56E-4740-BE8265C068C96D17
Mesasge: ERROR: current transaction is aborted, commands ignored until end of transaction block

## Planned Outage
 - Date and time outage will begin:
 - Date and time outage is expected to end:
 - Reason for outage:
 - Expected behavior during and after the outage:

## Communication before/during outage
- [x] Pin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG  
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by dustymc** [comment]
That's just postgres being not-Oracle.

**Comment by mkoo** [comment]
Dusty-translation: you have SQL commands that need to be updated to PG

I see those in the logs now.... what's the commands you're trying to run?

**Comment by Jegelewicz** [comment]
> what's the commands you're trying to run?

Edit collecting event, search some records, log in

**Comment by Jegelewicz** [comment]
I am not running any SQL commands except those that are part of using Arctos menus.

**Comment by mkoo** [comment]
So maybe I dont see what you're doing-- link and coll_event id? Dusty?

**Comment by dustymc** [comment]
PG is tripping over its own feet (often but not always from trying to do conflicting things at the same time), some transaction has failed and now it's stuck in some weird state (which is why eg airlines buy Oracle). That usually clears itself up, I can attempt to kill the session if not, if that works it'll mean you'll need to log out and back in.

**Comment by Jegelewicz** [comment]
I already tried logging out and back in. When I log in I get 

<html><body>


ERROR_ID | D2DEACFE-9B91-495C-B19D32791434DBE5
-- | --
ERROR_TYPE | SQL
ERROR_MESSAGE | ERROR: current transaction is aborted, commands ignored until end of transaction block
ERROR_DETAIL |  
ERROR_SQL | select count(*) c from  user_notification where status is null and username ='jegelewicz'


</body>
</html>
