### ISSUE TITLE
Error on Save with New Data Entry 

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6546]
Please see error below. Trying to enter first record using new data entry form. 
![image](https://github.com/ArctosDB/arctos/assets/14808196/05f2ec0a-cb51-4969-8fa6-906b9cbfd16d)

**Comment by dustymc** [comment]
Reload and try again - the error should be handled better now. 

(And see https://github.com/ArctosDB/arctos/issues/6416 - if you're trying to create a record with place-data then you'll need something in record-event-type.)

**Comment by campmlc** [comment]
Tried that, fixed event type; she got a new error:
![image](https://github.com/ArctosDB/arctos/assets/14808196/ab2dfccb-fbaa-4068-9f31-2872e92c9b28)

**Comment by dustymc** [comment]
Thanks, fixed.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I just got this error:

2023-7-25T16:30:4: FAIL: exception catch, check console: [object Object]: {"message":"exception catch, check console","status":"fail","dump":{"Extended_Info":"","Message":"ERROR: insert or update on table \"bulkloader\" violates foreign key constraint \"bulkloader_enteredby_fkey\"\n Detail: Key is not present in table \"cf_users\".","queryError":"INSERT INTO bulkloader

**Comment by dustymc** [comment]
Is that production? Has your session expired? What's the upper-right corner of your screen....

<img width="180" alt="Screenshot 2023-07-25 at 15 47 55" src="https://github.com/ArctosDB/arctos/assets/5720791/06deeea6-fee1-40ca-a291-fcd4c6f77674">

look like?

**Comment by campmlc** [comment]
Yes production, not expired, but I'll get student to try again tomorrow and
share screen..

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Yes, production, not expired.

![image](https://github.com/ArctosDB/arctos/assets/47402809/b34ab896-1550-4deb-b48f-036ee757ec3b)

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
2023-7-26T8:40:1: FAIL: exception catch, check console: [object Object]: {"message":"exception catch, check console","status":"fail","dump":{"Extended_Info":"","Message":"ERROR: insert or update on table \"bulkloader\" violates foreign key constraint \"bulkloader_enteredby_fkey\"\n Detail: Key is not present in table \"cf_users\".","queryError":"INSERT INTO bulkloader

![image](https://github.com/ArctosDB/arctos/assets/47402809/95356a4c-0332-432e-97c8-a9eff09e9fc4)
![image](https://github.com/ArctosDB/arctos/assets/47402809/a9220305-e1ba-4ac5-ace2-dd59b8510992)

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
You have my permission to use my account to test.

**Comment by dustymc** [comment]
Browser, network, friendly local developer, whatever....

Thanks! Found, fixed, patched, you can ask Arctos for a new password.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks!

**Comment by campmlc** [comment]
Also working for my student, thanks!
