### ISSUE TITLE
cloning into bulkloader fails

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#6548]
**Describe the bug**

Tried to clone this record into the bulkloader:
https://arctos.database.museum/guid/UAMObs:Ento:247075

got this error:
cloning failed: fail: ERROR: null value in column "entered_to_bulk_date" violates not-null constraint 

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.
high - need this!

**Comment by dustymc** [comment]
patched

**Comment by DerekSikes** [comment]
thanks!

I'm seeing this error but it doesn't seem real: locality_id and locality_name cannot both be given

because records that have one have the other when the data are pulled and they load fine

**Comment by DerekSikes** [comment]
Correction - they don't load. Will make an issue
