### ISSUE TITLE
locality_id and locality_name cannot both be given in BL

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#6549]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

Not exactly sure how to replicate this but I think when a locality name is used in the data entry form & the data are pulled/synched the locality ID comes with it... but then we get this error when trying to save/load the record:

locality_id and locality_name cannot both be given

which it seems prevents the record from loading..

I had a similar problem when cloning a record that had a locality name into the bulkloader.

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.
high

**Comment by dustymc** [comment]
Yes, that's the problem.

IIRC checking both when they're given caused some sort of confusion (involving humans, not machines), but - as long as we're forced to have the ephemeral IDs here - I think that's the only realistic solution. I'll just plan to make that update if nobody has an immediate and compelling reason not to.

**Comment by cjconroy** [comment]
I have a bunch of records in the bulk loader with this remark now after trying to load. "locality_id and locality_name cannot both be given"
When should I try to reload? 
Most of my localities are like this. I create them to be used later in data entry, and to keep them from disappearing I have to create locality names.

**Comment by dustymc** [comment]
update made

**Comment by cjconroy** [comment]
I tried to load the records, and now they come back with the error "locality_id+locality_name could not be resolved"

You can see in the bulkloader, MVZ Mammal accession 14938. 

The locID is 11983995 with name 2CAD9F36-17E5-450D-B69B3BAC3E28E062

Fortunately, this is one lab colony for a whole accession, but I regularly make locailties with names.

**Comment by dustymc** [comment]
Thanks, bug found, squashed, and confirmed - but I'll let you close after you've double-confirmed, please.

**Comment by cjconroy** [comment]
Thanks, they loaded.
