### ISSUE TITLE
manage identification with ID formula A {string} fails

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#6552]
Just searched for a bunch of records using their barcodes:

UAM100369433,UAM100451406,UAM100031923,UAM100008302,UAM100003674,UAM100008796,UAM100009001,UAM100007976,

found them, used tools -> Manage - Identifications

tried to apply taxon formula A {string} and although the form allowed me to enter an A {string} ID this did not save - only the A ID saved, not the {string} part.

I then tried to see if this would happen again and tried to do another set of bulk IDs and got this error:

The following do not have one ID of order>0; this form cannot be used.
Query
Template: /multiIdentification.cfm:99
Execution Time: 0.066 ms
Record Count: 1
Cached: No
Lazy: No
SQL:
select idf,guid from raw where idf like '%=%'
	idf	guid
1	1=1	UAM:Ento:26237

So that tool, which I use A LOT, is broken...

And a final problem, which I bet I'll be told is a feature and not a bug, but to me is a definite bug.... when I look at one of these specimens in list view (see screenshot) the higher taxa are duplicated:

two 'Animalia' for Kingdom, two 'Arthropoda' for phylum, etc. This is terrible. If a catrec has 5 identifications will Animalia be duplicated 5 times? Horrible UI. Return to prior interface please.
![Screenshot 2023-07-25 at 10 11 39 AM](https://github.com/ArctosDB/arctos/assets/9099827/e9718f64-71ed-4640-ab97-5ad9ff2ea7db)

Perhaps this has to do with the record having multiple IDs with ID order = 1?

Also, It is not obvious how to order IDs - is #1 the first ID chronologically? Is it the last? _How do we specify which one is equal to what we called 'accepted' before_ - please add all this info to the popup definition of 'ID order' (all it says now is the useless 'rank of identifications') which doesn't answer any of my questions.

Although this feature of multiple accepted IDs may be valuable to some, the default behavior should be nearly identical to how it worked before _so those who need new stuff this can jump through some hoops to enable it when they need it._ The default should not be to force everyone to jump through hoops to figure out how to do what they need to do (and knew how to do already - which no longer works!).

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.
very very high

**Comment by DerekSikes** [comment]
So I just experimented with this record with 3 IDs:
https://arctos.database.museum/guid/UAM:Ento:26237
all had id order = 1 so I changed one to 2, and one to 3 and clicked 'save' - this saved only the one with the save button next to it (the one I set to 3), so instead of saving them all I ended up with two with order =1 and one with =3.

And it appears that #1 is the one most like 'accepted' - which is backwards. If a specimens has say 20 identifications and you want to add a 21st ID to make it the accepted you have to manually change it to #1, then change the former #1 to #2, then change the former #2 to #3,clicking 'save' after every change? Insane UI.

The most recently added ID should get an auto increment # of the most recent (eg #21) and the highest # should be the 'accepted' ID.

**Comment by dustymc** [comment]
>nly the A ID saved, not the {string} part.

Patched.

>The following do not have one ID of order>0; this form cannot be used.

That is intended to prevent messes and can be removed, but I think it needs focused discussion first.

>Perhaps this has to do with the record having multiple IDs with ID order = 1?

Yes.

> first ID chronologically?

No, those are completely separate, 100% unlinked, concepts.

>doesn't answer any of my questions.

https://handbook.arctosdb.org/documentation/identification.html#identification-order

>How do we specify which one is equal to what we called 'accepted' before

That idea has been removed (as a result of a very lengthy discussion: https://github.com/ArctosDB/arctos/issues/3540).

You can convey the same information by limiting yourself to EXACTLY one ID of order > 0 (which is why the above limitation was added).

> Insane UI.

It's not, but that's not the model. THERE IS NO ONE ACCEPTED!! You can have 21 equally-accepted (which includes "we love it" or "these are all wrong") IDs eg because 21 techniques lead to the same taxon concept, or because you have cataloged 21 identifiable things together for some reason, or because 21 people agree, or WHATEVER.

>e most recently added ID

... has nothing to do with curatorial preference. (Maybe the most-recent is some obviously wrong but published nonsense - most would want to capture that usage, I don't think anyone would want that to be forced into the foreground!)

>https://github.com/ArctosDB/arctos/issues/1 is the one most like 'accepted' - which is backwards

I think you're suggesting all the 1s (previous "accepted") should be 10 (currently "last on the list")? I don't think I much care, although that's clearly not what was proposed, but if we're going to change something it should be done NOW before a bunch of 4s are added (if they haven't already been).

**Comment by dustymc** [comment]
> all the IDs had order of 1 

"one" is the important word, maybe "exactly one" would be more clear?

>becomes accepted,

I don't understand why adding a maybe-terrible ID would force-do anything to any previous IDs! Maybe a good place for another ad hoc Committee?

**Comment by DerekSikes** [comment]
99.9999% of the ids we add are improvements. If we want to add a wrong ID for history sake we could always do that and then change the accepted flag after it was made so it (the bad one) was no longer accepted. Problem solved.

I still don't see how this works - if I change a bunch of ants (ID = Formicidae) to improve their ID to genus = Formica how do I specify that the genus ID becomes the one the record will be called (the big ID name in the upper left)?? I hear you loudly that we're not calling it a single 'accepted' ID so I'll just call it "the big taxon-name ID in the upper left of the catalog record' because that's so much more convenient? 

If I set the new ID to order =1 and there's already an ID of order =1 then there are two and which one is the 'the big taxon-name ID in the upper left of the catalog record' ID? How do I get it to behave like it did before? Like I said, if someone wants this new feature they should have to do extra work to get it to happen instead of the rest of us.

**Comment by DerekSikes** [comment]
Until I know how to make bulk-ID changes that work as expected (automatically make the new ID = 1, the others = increment downwards) OR change the rank orders so the highest number is always the last # and the 'accepted' ID.. I can't proceed with my work. I need to update the IDs of tons of specimens all the time so this needs addressing please. Thanks!

**Comment by dustymc** [comment]
>(automatically make the new ID = 1, the others = increment downwards) 

AHA! (I hope...) That won't quite work, but a "add this and flip all existing IDs to 0" option is actionable, and I think would do what you want (replicate the old system where there's ~always **exactly** one clear "best" - yes?).

Does that sound right?

**Comment by DerekSikes** [comment]
yes! that sounds good thanks! - however, when viewing these older IDs they should sort chronologically too. Can that be done? When I go into a record to edit ID there's a list and that list should have a logical sort order and I can't think of any better sort than by the date of the ID.

**Comment by dustymc** [comment]
>yes!

Going direct for that - this is new, that is additive, I don't think it needs to go through the dev process, someone please stop me if that's not right.


>sort


```

		ORDER BY sort_order,made_date DESC
```

Are you seeing something else?

**Comment by DerekSikes** [comment]
I'll trust you and assume my memory is bad, but I thought I've seen non-chronological sorts.. I'll keep an eye out in the future & make note if so. thanks.

**Comment by DerekSikes** [comment]
New problem - the Manage ID tool form vanishes after completing the ID update and if I click to go back to the form I get the error:
The following do not have one ID of order>0; this form cannot be used. 

I understand that this form will be fixed to allow all prior IDs to be set to order=0 but even after that happens, I'd prefer the form behave as it used to because I want to be able to do as always do:
1) update the IDs
2) update the container for the specimens
all without leaving the form.

Now, even if the bug is fixed to allow me to use this form properly it still will take more clicking - leaving the form, click to get back to the form, then do the container updates.

That back-and-forth is likely to lead to me or lab techs etc forgetting to do the container updates. Please return the prior functionality of the form not vanishing when the update ID button is clicked. Thanks,.

**Comment by Jegelewicz** [comment]
> a "add this and flip all existing IDs to 0" option is actionable

That is a nice option, but I can also see situations where "add this and flip all existing to existing plus one" would be needed (you want to keep "acceptedness" but still have only one "uber accepted" identification. Possible?

**Comment by DerekSikes** [comment]
Could someone point me to a description of what these rank order #s mean?  I'm sorta understanding that 0 = not accepted, and 1 = accepted (uber accepted?) but what do all the rest mean? And when can I expect this to be functional so I can get back to work?

**Comment by dustymc** [comment]
>Now, even if the bug is fixed to allow me to use this form properly it still will take more clicking - leaving the form, click to get back to the form, then do the container updates.

>That back-and-forth is likely to lead to me or lab techs etc forgetting to do the container updates. Please return the prior functionality of the form not vanishing when the update ID button is clicked. Thanks,.

Currently the form does this after save:

<img width="654" alt="Screenshot 2023-07-26 at 08 43 42" src="https://github.com/ArctosDB/arctos/assets/5720791/de284c76-6d1e-429e-9083-20916b2aeedb">

It's ONE click, and it carries a super-important message: it might look like nothing has happened for a bit, don't assume that's the case and create 57 more identifications (because you now can, and then you'll have a giant mess to clean up, and you NEED a warning before that happens).

I don't think that's unreasonable!

-----------


The form will now work with messy IDs, it just has a warning:


<img width="1696" alt="Screenshot 2023-07-26 at 10 31 52" src="https://github.com/ArctosDB/arctos/assets/5720791/56d5fae6-fde1-4008-b266-2ac793aee40c">



---------


and there's a new option which is both capable of creating the above, and (more or less) hiding the above.


<img width="760" alt="Screenshot 2023-07-26 at 09 19 10" src="https://github.com/ArctosDB/arctos/assets/5720791/75a304ee-b415-4495-b44c-b6fcbdfb20e6">


-


<img width="1606" alt="Screenshot 2023-07-26 at 09 19 37" src="https://github.com/ArctosDB/arctos/assets/5720791/13c93584-f5a9-4633-aab8-9de7adb327fc">


-----------


I hopefully-clarified some of the formerly-accepted 'reuse the....' options, but I think that's just always going to be confusing here. Is there some tangible use case or can this be removed?

<img width="1291" alt="Screenshot 2023-07-26 at 12 48 47" src="https://github.com/ArctosDB/arctos/assets/5720791/15c98c6e-e13b-489e-9577-e7e356c1c9c9">

**Comment by DerekSikes** [comment]
Thanks for fixing this. I'll test it out. But I want to push back on the disappearing form. The prior form would give the clear indication that things had changed because all the data entered in the ID fields vanished. This has worked for me and my lab for many years and now you're telling me we need to change, why? 

Also, it may seem like just one more click but really, with the movement of nature of ID and ID confidence to attributes, combined with the extra clicking for ID order, all adds up to something like 8+ clicks and typing for the attributes, which all used to be much simpler and faster. The form has already slowed down my workflow considerably and so I'd like to pushback on this unneeded (in my view) change of having the form vanish while I'm still using it, and then have to click to get it back. If it's not broke, don't fix it. My lab probably uses that form an order of magnitude more than any other and has anyone ever complained that they wished the form would vanish and give them a warning??

Plus, we have enough problems with keeping our object tracking current and this vanishing form will likely make it even harder as lab techs forget to go back and update the object tracking.

**Comment by dustymc** [comment]
>disappearing form.

I think you're seeing something I'm not?? Detailed annotated screenshots might help.

**Comment by DerekSikes** [comment]
Arctos is not responding now... but my reply was because you wrote this:
It's ONE click, and it carries a super-important message: it might look like nothing has happened for a bit, don't assume that's the case and create 57 more identifications (because you now can, and then you'll have a giant mess to clean up, and you NEED a warning before that happens).

I don't think that's unreasonable!

which made me assume that you were defending the form vanishing after clicking to apply the bulk ID update and then having to click to get the form back. Is that no longer the case?

**Comment by dustymc** [comment]
>responding

It is for me - and no, my screenshot above is what you should see after a save, nothing should lead to - uhh - nothing??

**Comment by DerekSikes** [comment]
Ok, I just tried it and after clicking to apply the new IDs the form vanished as I've been complaining about. I have to click 'return to this form' to get back to the form. Please see my statements above to return this form to its original non-disappearing nature after applying an ID

**Comment by DerekSikes** [comment]
Also, contrary to my request, the default value of the form for 'existing identification order' is not 'set all existing IDs to order=0' which it should be. This will mimic the behavior before this new ranked order IDs was introduced. People should need to OPT IN to using the new ranked features. The rest of us should be able to ignore it by using the default settings. Instead, you're asking the majority to OPT OUT of the new features by making us click a 'do what I was doing before without clicking anything' button every time I want to do something... Please make the default = 'set all exisiting IDs to order =0' for that form. THanks.

**Comment by DerekSikes** [comment]
I'll add that having the form disappear and then having to click 'return to this form' adds not just extra time to manage the click but sometimes my browser spins its wheels a few seconds before the form returns. If I had a blood pressure monitor attached there would be a very strong relationship between those seconds and my blood pressure! How about we return it to the way it was and wait for community discussion to decide if we should implement this new vanishing form warning page interruption of entomology workflow - and if the community agrees then so be it but in the meantime, return it to the way it was, more streamlined, simpler, faster, and help my blood pressure return to normal!
thanks

**Comment by Jegelewicz** [comment]
Who else is using this? I don't use it so I cannot really provide any feedback. If @DerekSikes is the primary user, then we should be looking at meeting his blood pressure needs! If others are using this, how can we find out and contact them for feedback?

**Comment by AJLinn** [comment]
I didn't even know about this form but could imagine using it to try and standardize a bunch of my A{string} names. I agree with Teresa that the lack of discussion by others must mean this is a bit of a non-issue to others so by all means, get the entomology workflow back up and running and the rest of us will adapt.

**Comment by dustymc** [comment]
Changes in next release. 

Can I assume the silence on https://github.com/ArctosDB/arctos/issues/6552#issuecomment-1652403407 (removing the scary 'do things based on some arbitrary ID' links) is an expression of enthusiastic support?

**Comment by DerekSikes** [comment]
THANKS!!
