### ISSUE TITLE
United States, New Mexico, Dona Ana County; No specific locality recorded.

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6555]
There are 57 localities using the higher geography `United States, New Mexico, Dona Ana County` that also include `No specific locality recorded.` in the specific locality. It makes sense that there may be more than one, but some of them seem nonsensical.

For example https://arctos.database.museum/place.cfm?action=detail&locality_id=11467864

Which clearly does have some specific locality? 

`No specific locality recorded., Dona Ana County, White Sands National Monument`

The question here is what do you do when the specific locality is covered by a feature? The current specific locality makes no sense and I imagine there are others like this from migrating to GADM. This seems like a job for the geography committee. @mkoo

**Comment by mkoo** [comment]
This is specific to UTEP (https://arctos.database.museum/search.cfm?locality_id=11467864)
My recommendation is to have the spec_loc simply be "White Sands National Monument" so you can suggest that to UTEP:Herb but likely the way their catalog originally has it listed. Not a geo community work but collection-level work.

Will you reach out and close?

**Comment by Jegelewicz** [comment]
@mkoo this happened as a result of the migration to GADM, which is why I posted this.

https://arctos.database.museum/info/localityArchive.cfm?locality_id=11467864

Everything after "No specific locality recorded" in specific locality was added by scripts when White Sands National Monument was removed from higher geography. My point is that this is probably true in a lot of other localities. I can fix this one - but I don't think that "White Sands National Monument" should be the specific locality as it is included as a Feature? I'd like some guidance there as well.

**Comment by mkoo** [comment]
Can you clean for UTEP (is Vicky involved here?) The best spec_loc for this is simply "White Sands National Monument" (the other parts are useless!) I can do this is Vicky @mvzhuang agrees!

**Comment by Jegelewicz** [comment]
@mkoo I have fixed this one, but my point with this issue is that there will be others?

Can we find and fix them in some programmatic way? Remove the No specific locality which is now nonsensical?

**Comment by mkoo** [comment]
> @mkoo I have fixed this one, but my point with this issue is that there will be others?
> 
> Can we find and fix them in some programmatic way? Remove the No specific locality which is now nonsensical?

Thanks, and yes, this can be part of our larger clean-up work this summer with HG and other locality work. Let's close this and we can start a new one.
