### ISSUE TITLE
add geolocate capability to bulkloader edit

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6556]
Still doesn't work in Chrome (even after updating), but works in Firefox. In Chrome it still displays the "replace existing coordinates" pop up, and clicking "okay" does nothing. 

Additionally I just noticed that when you go to Browse and Edit, "edit_key" to edit the record on the data entry form, there is no longer a Geolocate button. I was able to geolocate records this way before the update, which I did occasionally when I wanted to correct coordinates that a volunteer geolocated. Was removing the geolocate button from this editing page intended? I know the catalog record edit page from Browse and Edit has limitations; just curious.

_Originally posted by @genevieve-anderegg in https://github.com/ArctosDB/arctos/issues/6547#issuecomment-1650274224_

**Comment by mkoo** [comment]
This was not working for us this week either (same issue as above)
