### ISSUE TITLE
Feature Request - After download proceed directly to delete from bulkloader

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6557]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

I have stuff that won't load, so I download with errors, then I have to go back to the Tool Directory to remove my messy data from the bulkloader

**Describe what you're trying to accomplish** 
An clear and concise overview of the goals; why are you asking for this?

After I download data with errors, delete it from the bulkloader (freeing it for others to use!)

**Describe the solution you'd like**
How might we accomplish your goals?

A button here 

![image](https://github.com/ArctosDB/arctos/assets/5725767/179f6be3-1dae-4941-afc7-dee14988ecef)

that let's me delete stuff or takes me directly to here - https://arctos.database.museum/Bulkloader/BulkloadSpecimens.cfm so I can use the delete button. OR even better have a **download AND delete button that let's me take care of everything at once**!

**Describe alternatives you've considered**

Leave my garbage in the tool and make other people delete it or hunt me down to ask me if they can delete it OR Tool Directory -> Bulkload Catalog Records -> Delete (I almost always forget to do this....

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by dustymc** [comment]
I can't quite figure out how to do a download-and-delete without doing some sort of super-complicated thing that your browser will probably fight, so I added requested links (and converted everything to buttons) for next release.

<img width="831" alt="Screenshot 2024-01-22 at 11 22 35" src="https://github.com/ArctosDB/arctos/assets/5720791/218fdcf4-d31a-45d1-8314-a17a9102a7a1">
