### ISSUE TITLE
geography request - Kosovo

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6558]
### Explain what geography needs created.

Explain in sufficient detail for us to locate standardized spatial data. For GADM-based data, a country is usually sufficient and appropriate. Please request distinct countries in distinct issues. We will respond with a CSV template and instructions for proceeding, or a request more information if necessary.

GADM includes this country and I have records in the bulkloader waiting to use it.

https://gadm.org/maps/XKO.html

If the above does not seem correct, usable, or ideal, please open a request for information Issue (you may use this template). We are happy to discuss specifics or alternates; please bring any potential concerns or problems to our attention *before* assembling data or requesting that we do so.

**Comment by dustymc** [comment]
I can't do this right now (same reason as https://github.com/ArctosDB/arctos/issues/6521, I think), I've asked TACC for additional help, here's the data.

[temp_pre_geog(6).csv](https://github.com/ArctosDB/arctos/files/12177959/temp_pre_geog.6.csv)

**Comment by Jegelewicz** [comment]
@dustymc @mkoo I have records sitting in the bulkloader awaiting this request. What is the status?

**Comment by dustymc** [comment]
done
