### ISSUE TITLE
Arctos Down - 503 Server Error 12:36 pm MDT

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6559]
Please complete to the best of your ability.

## Unplanned Outage
 - Date and time (**please add time zone from which you are reporting**) outage discovered:
 - Describe the outage (Arctos down or only some part not working?):

## Planned Outage
 - Date and time outage will begin:
 - Date and time outage is expected to end:
 - Reason for outage:
 - Expected behavior during and after the outage:

## Communication before/during outage
- [ ] Pin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG  
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by Jegelewicz** [comment]
Its working for me

**Comment by campmlc** [comment]
It's working for me now too. Temporary glitch in the matrix?
