### ISSUE TITLE
Can't delete records if they have ID attributes?

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#6560]
Tried to delete 2 records 
https://arctos.database.museum/guid/UAM:Ento:288395
https://arctos.database.museum/guid/UAM:Ento:288404

and got this error:

ERROR_ID 	A06F5975-2CF4-4B5D-B69C22459A16F100
ERROR_TYPE 	SQL
ERROR_MESSAGE 	ERROR: update or delete on table "identification" violates foreign key constraint "identification_attributes_identification_id_fkey" on table "identification_attributes" Detail: Key (identification_id)=(11997923) is still referenced from table "identification_attributes".
ERROR_DETAIL 	
ERROR_SQL 	delete from identification where collection_object_id IN ( select collection_object_id FROM coll_object_encumbrance WHERE encumbrance_id = 10000058 )

A workaround might be to delete the ID attributes before trying to delete the records but I see no way to do this & that would not be a functional workaround if there are lots of records to delete. 

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.
very high

**Comment by DerekSikes** [comment]
Same problem trying to delete a stand-alone locality (with no collection events linked to it):
ERROR_ID 	713AFF87-F971-41AC-A470B1EDD5D3C4BA
ERROR_TYPE 	SQL
ERROR_MESSAGE 	ERROR: update or delete on table "locality" violates foreign key constraint "locality_attributes_locality_id_fkey" on table "locality_attributes" Detail: Key (locality_id)=(12094546) is still referenced from table "locality_attributes".
ERROR_DETAIL 	
ERROR_SQL 	delete from locality where locality_id=12094546

**Comment by dustymc** [comment]
>identification

patched

>locality

I don't think that's wrong or should be changed, locality attributes should protect localities. Issue if you think otherwise, there's no technical reason to go either way, just needs discussed and resolved.

**Comment by DerekSikes** [comment]
Can we delete attributes from localities? I made a locality by mistake (via cloning) and wanted to delete it but couldn't so I let it be... will the autodelete script find it and delete it?

Also, minor UI issue: Collection event records have a single 'save' button that saves the data entered in all the fields, including any attributes added... Locality records have 2 save buttons, one for locality data and another for attributes. This leads to people like myself entering all the data, hitting save and then seeing my attribute data vanish and having to enter it again and click the separate 'save attribute' button. Please make consistent UI & the Collection Event model is the superior option for the reasons stated.
