### ISSUE TITLE
Genbank links are no longer functional

### ISSUE THREAD

**Issue by jldunnum** [ArctosDB/arctos#6561]
I can see the Genbank accession numbers in the other identifiers but the hot links to NCBI no longer function

![image](https://github.com/ArctosDB/arctos/assets/17278851/f988000b-e726-4838-87dd-85c9ce71875f)

**Comment by mkoo** [comment]
HI Jon, we're working on updating identifiers right now-- the functionality will return with better formatted and LINKED values so hang on for the next update!

**Comment by jldunnum** [comment]
Oh good, I was distressed to say the least.

______________________________________________________________

Jonathan L. Dunnum Ph.D. (he, him, his)
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

Chair, Systematic Collections Committee, American Society of Mammalogists
Latin American Fellowship Committee, ASM

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by mkoo** [comment]
Fixed
