### ISSUE TITLE
Save locality attributes with save locality

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6562]
Collection event records have a single 'save' button that saves the data entered in all the fields, including any attributes added... Locality records have 2 save buttons, one for locality data and another for attributes. This leads to people like myself entering all the data, hitting save and then seeing my attribute data vanish and having to enter it again and click the separate 'save attribute' button. Please make consistent UI & the Collection Event model is the superior option for the reasons stated.

_Originally posted by @DerekSikes in https://github.com/ArctosDB/arctos/issues/6560#issuecomment-1652447024_

**Comment by Jegelewicz** [comment]
This happened to me yesterday when using geolocate. We should be able to save the georeference source attribute at the same time we are saving the coordinates entered via Geolocate. Also, could the georeference source attribute get auto-populated when using Geolocate?

As it is, I can add coordinates to a locality and never add a georeference source....

**Comment by dustymc** [comment]
> could the georeference source attribute get auto-populated when using Geolocate?

Why? There's no information in that.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Yes please! I've had to reenter things so many times!

**Comment by ewommack** [comment]
I'll second that yes please! For those of us using Data Entry, auto-population from Geolocate would be really helpful.
