### ISSUE TITLE
Bug/ Feature Request- 

### ISSUE THREAD

**Issue by Msaqib2** [ArctosDB/arctos#6564]
**Is your feature request related to a problem? Please describe.**
When I bulkload the data in the new format, and there are errors it just gives a big error which was difficult to interpret. The lack of download data with errors, makes things a bit more complicated to determine where exactly in my document I was having an issue. This might just be a bug I have attached a screenshot with this issue. 

**Describe what you're trying to accomplish** 
I want to be able to download the data with error from the staging manager, or if possible from the same screen it gave me an error message to see where exactly in the document I was having errors.

**Describe the solution you'd like**
To be able to download the data with errors.

**Describe alternatives you've considered**
Figuring out the error, and reading into the error message to determine where in my document I had an error.

**Priority**
Normal

[httpsarctos.database.museumBulkloaderBulkloadSpecimens.cfm.pdf](https://github.com/ArctosDB/arctos/files/12177685/httpsarctos.database.museumBulkloaderBulkloadSpecimens.cfm.pdf)

**Comment by dustymc** [comment]
Please please please 
<img width="581" alt="Screenshot 2023-07-26 at 15 17 14" src="https://github.com/ArctosDB/arctos/assets/5720791/11817238-7508-466d-947e-3fb1337285e5">

There is no identification_1_agent_type_1 column in anything and I'm not sure what the intent is.  Please use the [Bulkloader Builder](https://arctos.database.museum/Bulkloader/bulkloaderBuilder.cfm) to get column names.

[CSV Checker](https://arctos.database.museum/Reports/csvChecker.cfm) might be useful in this situation.

Please provide data if that doesn't solve the problem.

**Comment by Msaqib2** [comment]
Hi,
I was able to figure out the error. What I was trying to say was that, Arctos wasn't giving an option to download the data with errors. Unless that doesn't happen if the column names are wrong?

**Comment by dustymc** [comment]
Ah - thanks, yes, that error is Arctos not being able to understand the data, there's not much opportunity for a better error in that particular place. If the CSV checker can't figure it out then an Issue is probably the best (or only) remaining option.

Also - please add your github info to your Arctos Agent! ( And @Jegelewicz can you add that to https://doi.org/10.7299/X75B02M5 please ? )

**Comment by ewommack** [comment]
> Also - please add your github info to your Arctos Agent! 

That was my fault! Msaqib2 is the UWYMV grad CA.

**Comment by Jegelewicz** [comment]
> And @Jegelewicz can you add that to https://doi.org/10.7299/X75B02M5 please ? )

It has always been there....

![image](https://github.com/ArctosDB/arctos/assets/5725767/00c53b83-11bc-46ac-bd18-5e79ceb6a981)

**Comment by dustymc** [comment]
>always been there

I'm asking for the opposite, I check Arctos (because problems involve user environment some crazy percentage of the time)

<img width="603" alt="Screenshot 2023-07-26 at 16 17 39" src="https://github.com/ArctosDB/arctos/assets/5720791/0dc873c3-ed5c-449e-945c-0f567d500463">

.. which wasn't nearly so happy a while ago!

**Comment by Jegelewicz** [comment]
Oh I see - this is for the person who adds the operator...

That is probably better in [here](https://handbook.arctosdb.org/how_to/How-to-Create-your-Arctos-Team-Users-and-Operators.html). Will do.

**Comment by mkoo** [comment]
@Msaqib2 Did the CSV header checker help?
I am just following up to see if we can close this issue! let us know if you need more help
thanks, MK

**Comment by ewommack** [comment]
I think the issue wasn't actually about the CSV Checker or the error message. It was about:

> What I was trying to say was that, Arctos wasn't giving an option to download the data with errors. Unless that doesn't happen if the column names are wrong?
> https://github.com/ArctosDB/arctos/issues/6557 I was hoping to get the screen, "download data with errors"

**Comment by Jegelewicz** [comment]
@ewommack you cannot download data with errors at this point in the process because no data has been loaded. The load failed because there was a problem with one or more of the column headers.

**Comment by Msaqib2** [comment]
Hi,
I was able to get the data uploaded. Thank you all!
