### ISSUE TITLE
ID determiner (agent) not showing up in list view

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#6565]
note the name of the ID determiner is not showing in list view:

![Screenshot 2023-07-26 at 4 23 16 PM](https://github.com/ArctosDB/arctos/assets/9099827/4183f94a-524c-406f-9102-c54eb77f43a0)

but when I click on the first record the name shows in the ID (Sayde Ridling)

![Screenshot 2023-07-26 at 4 23 20 PM](https://github.com/ArctosDB/arctos/assets/9099827/8055ce0e-68f4-4a1d-9618-ea84b558017b)
can we get the agent name of the determiner to show in list view again? 
**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.
medium

**Comment by dustymc** [comment]
Thanks, bug should be fixed, everything should catch up in a few days, I can prioritize stuff if necessary.
