### ISSUE TITLE
Arctos Down - 5PM Pacific TONIGHT

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6566]
I need to upgrade some dependencies on the server. The outage should last seconds, but users will likely be forced to log back in, and things don't always go as planned. I can be flexible with the timing, please let me know ASAP if this presents a problem and we'll reschedule.

Please complete to the best of your ability.

## Planned Outage
 - Date and time outage will begin: **5PM Pacific 2023-07-27**
 - Date and time outage is expected to end: **510PM Pacific 2023-07-27**
 - Reason for outage: **server upgrade**
 - Expected behavior during and after the outage: **probable forced logout of all users, possible noticeable outage**

## Communication before/during outage
- [x] Pin this issue
- [x] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG  
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [x] Unpin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by Jegelewicz** [comment]
Suggested banner text

Arctos will be offline on Friday, July 27th at 5PM Pacific to upgrade some dependencies on the server. The outage should last seconds, but users will likely be forced to log back in and it is possible that an unplanned issue could result in a longer outage. If this presents a problem for your workflow, please comment in <a href="https://github.com/ArctosDB/arctos/issues/6566" target="_blank">this issue</a>.

**Comment by Jegelewicz** [comment]
@dustymc @mkoo is above OK?

**Comment by dustymc** [comment]
done

**Comment by mkoo** [comment]
yay! seems fine now that I relogged on!
closing
