### ISSUE TITLE
Request - CSV Header Checker guidance on results page

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#6570]
Love the CSV Header Checker (https://arctos.database.museum/Reports/csvChecker.cfm)
From AWG today:
The results page needs some guidance tweaks (giving a long and shorter options):

- [ ] Change the results table columns from ```Upload``` to ```Uploaded CSV``` or ```CSV```
- [ ] Change the results table columns from ```Table``` to ```Validation Table```
- [ ] Add some Guidance text at the top or to the right (lots of white space since the table is very long). Make suggestions below but here's my first draft (and Dusty may be able to better recreate the check marks with your font-awesome codes (eg ```class="fas fa-check```) :

---------
This forms checks the header row of an uploaded CSV with the acceptable field names in the bulkloader. It is provided as a tool for you to check your CSV prior to bulkloading so typos, missing fields, and other header row issues can be addressed by the user.  It does not check any values beyond the first row. Green checks = field name is valid. Red X's = field name is not valid. Examples:

![Firefox_Screenshot_2023-07-27T23-12-36 608Z](https://github.com/ArctosDB/arctos/assets/2523089/5dbba34d-6667-4b07-8b18-0d4e8d8bc9b3)
If your CSV and Table values are both green checks, then the field name is valid and can be uploaded.

![Firefox_Screenshot_2023-07-27T23-13-54 299Z](https://github.com/ArctosDB/arctos/assets/2523089/337409e3-5abc-4186-9506-fdcdd50b07ca)
If you have a green check and red x, then the field name in your CSV is not valid and you must correct it first.

![Firefox_Screenshot_2023-07-27T23-15-17 963Z](https://github.com/ArctosDB/arctos/assets/2523089/50f80c6a-208a-4b54-abd3-88976be27405)
If you have a red x and a green check, then the CSV is missing a field that is in the bulkloading table. This is not necessarily a fatal condition and may be valid if you are not bulkloading a record with 20 attributes. However, if it is a field that should be included in your record (eg. the collector name as in this example), then be sure to add those fields with the proper field name and desired values.

**Comment by dustymc** [comment]
I don't much like "bulkloader" - this can work for things that aren't - but maybe it's not very confusing anyway. "Table" is correct but may also be confusing. "Target"? "Tool"? The user-selected table name (currently only 'bulkloader' - maybe that's what's being suggested?!)?? ?????

In the name of future expansion, a suggestion:

>This is not necessarily a fatal condition as many tools have optional columns (such as many attributes in the record bulkloader). However, if it is a field that should be included in your record (eg. the collector name as in this example), then be sure to add those fields with the proper field name and desired values.

Yep im using fontawesome, its pretty awesome....

Seems the purpose also needs clarity - this tool is intended to find the **structural** problems that will prevent a user from getting to the point where **data** problems may be identified. Verbiage to that effect greatly appreciated.

**Comment by mkoo** [comment]
ok edited the original proposal above-- also how about "Validation Table"?

**Comment by Jegelewicz** [comment]
Suggested changes

## CSV Header Checker
This form checks the header row of an uploaded CSV against the acceptable field names in the selected bulkload tool. It does not check any values beyond the header row as it is provided to find structural problems that will prevent a bulkload file from getting to the point where data problems may be identified, (typos in column headers, missing column headers, and other header row issues). 

## Interpreting the Results
### Uploaded CSV
 - Green checks indicate that the column is present
 - Red X's indicate the column is not present, but is available in the upload tool
### Validation Table
 - Green checks indicate that the column header is valid
 - Rex X's indicate that the column header is not valid

![Firefox_Screenshot_2023-07-27T23-12-36 608Z](https://github.com/ArctosDB/arctos/assets/2523089/5dbba34d-6667-4b07-8b18-0d4e8d8bc9b3)
If your CSV and Table values are both green checks, then the field name is valid and can be uploaded.


![Firefox_Screenshot_2023-07-27T23-13-54 299Z](https://github.com/ArctosDB/arctos/assets/2523089/337409e3-5abc-4186-9506-fdcdd50b07ca)
If you have a green check and red x, then the field name in your CSV is not valid and you must correct it first.


![Firefox_Screenshot_2023-07-27T23-15-17 963Z](https://github.com/ArctosDB/arctos/assets/2523089/50f80c6a-208a-4b54-abd3-88976be27405)
If you have a red x and a green check, then the CSV is missing a field that is in the bulkloading table. This is not necessarily a fatal condition and may be valid if you are not bulkloading a record with 20 attributes. However, if it is a field that should be included in your record (eg. the collector name as in this example), then be sure to add those fields with the proper field name and desired values.

**Comment by ewommack** [comment]
Edited a typo from Rex to Red.
