### ISSUE TITLE
[CONTACT]

### ISSUE THREAD

**Issue by gshugart** [ArctosDB/arctos#6571]
Directories of collections don't match, for the Burke and maybe others
https://arctos.database.museum/home.cfm

Burke Museum of Natural History and Culture (UWBM) | Amphibian and reptile specimens | UWBM:Herp | 10453 | Search | Details
Burke Museum of Natural History and Culture (UWBM) | Mammal specimens | UWBM:Mamm | 58258 | Search | Details

https://arctos.database.museum/

UWBM:Herp | UWBM | Herp | Burke Museum of Natural History and Culture (UWBM) | Amphibian and reptile specimens
  | UWBM:IP | UWBM | Inv | Burke Museum of Natural History and Culture (UWBM) | Invertebrate Paleontology specimens
  | UWBM:Mamm | UWBM | Mamm | Burke Museum of Natural History and Culture (UWBM) | Mammal specimens
  | UWBM:MET | UWBM | ES | Burke Museum of Natural History and Culture (UWBM) | Meteoritics
  | UWBM:MINERAL | UWBM | ES | Burke Museum of Natural History and Culture (UWBM) | Geology specimens
  | UWBM:PaleoArchive | UWBM | EH | Burke Museum of Natural History and Culture (UWBM) | Paleontology Library
  | UWBM:PB | UWBM | Herb | Burke Museum of Natural History and Culture (UWBM) | Paleobotany specimens
  | UWBM:PR | UWBM | Herb | Burke Museum of Natural History and Culture (UWBM) | Paleobotany Reference specimens
  | UWBM:VP | UWBM | ES | Burke Museum of Natural History and Culture (UWBM) | Vertebrate Paleontology specimens

**Comment by Jegelewicz** [comment]
@gshugart the bottom set of collections do not have any data in Arctos yet. @dustymc can confirm, but I think that is why there is currently a "mismatch".

**Comment by mkoo** [comment]
Yes, by default: if a collection does not have any records then it does not show up on the public page. If you're logged in user then you can see all the collections in System Stats. (There's a long history of discussion about this-- some collections are in progress of migration, some collections are strictly for curatorial workflows so will always have 0 records, etc). Thanks for your inquiry!
