### ISSUE TITLE
Record Entry Issue

### ISSUE THREAD

**Issue by Cpittman53** [ArctosDB/arctos#6573]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

Attempted to enter record for a herp specimen, but was unsuccessful in loading the entry into the uploader. An error message appeared. Was successful in a previous attempt to upload
[Error Message Record Entry Arctos.docx](https://github.com/ArctosDB/arctos/files/12196263/Error.Message.Record.Entry.Arctos.docx)
 a similar specimen. 

**To Reproduce**

**Expected behavior**

To load the record entry into the data uploader. 

**Screenshots**

Error Message attached in document file

[Error Message Record Entry Arctos.docx](https://github.com/ArctosDB/arctos/files/12196263/Error.Message.Record.Entry.Arctos.docx)

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

Windows 10 Pro
Browser: Chrome 

**Additional context**

**Priority**
Please assign a priority. Unprioritized issues get sent into a black hole of despair.
_Priority-High_

[Error Message Record Entry Arctos.docx]
(https://github.com/ArctosDB/arctos/files/12196248/Error.Message.Record.Entry.Arctos.docx

**Comment by dustymc** [comment]
This is a bug that only appears in some mysterious set of circumstances which I'd hoped the patch last night would fix. It apparently did not. I will try to get another attempt out this evening or early next week. You might try another browser or machine, but I don't know what causes this so I'm not sure what might help. Please let me know if you see any pattern.

**Comment by dustymc** [comment]
I just pushed to production, please try again and let me know what happens.

**Comment by Cpittman53** [comment]
Seems to be working now! I was able to enter the record without error. Thank you

**Comment by Cpittman53** [comment]
May have spoke too soon. Was able to upload one Herp record, but was unsuccessful on the next one. Tried to input a Mammal record but received the same error message.

**Comment by dustymc** [comment]
I need the error, even if it's the same as the last one.

**Comment by Cpittman53** [comment]
Here is the error message from my most recent attempt. I tested a few other records, where I either put in only a couple of the attributes, or no parts, and those all worked fine. It was when I entered in about 13 attributes and the two associated parts, that I received the error message.
[Error Message Record Entry Arctos 7_31_2023.docx](https://github.com/ArctosDB/arctos/files/12217536/Error.Message.Record.Entry.Arctos.7_31_2023.docx)

**Comment by dustymc** [comment]
Thanks. Can you try using FireFox please?

**Comment by Cpittman53** [comment]
Same message on Firefox after attempting to submit a full record.

[Error Message Record Entry Arctos 7_31_2023 Mammal entry.docx](https://github.com/ArctosDB/arctos/files/12217809/Error.Message.Record.Entry.Arctos.7_31_2023.Mammal.entry.docx)

**Comment by dustymc** [comment]
Thanks.

**Comment by dustymc** [comment]
I think I might have figured this out (in a black-box "just avoid the buggy thing" sort of way, no real understanding). I've rewritten the API to avoid QofQ and should get another patch out tonight. Things are becoming functional in test, last-minute attempts to break it greatly appreciated.

FYI https://github.com/ArctosDB/arctos/issues/6578 lead here - so thanks @ebraker !

**Comment by Cpittman53** [comment]
Entered a full record with no issues. I will be entering in more records soon, so hoping it will all go smoothly. Thank you for your help with this.
