### ISSUE TITLE
Edit existing determination in Catalog Record not saving Identifier (Agent)

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#6576]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I added a new record yesterday via the new data entry form.
https://arctos.database.museum/guid/UAM:EH:UA2023-006-0001

Today I reviewed the record to see if I caught everything in the new layout and realized I needed to add an agent to the A{string} identification (we had zero for the Identifiers). When I went into the catalog record and edited the ID by adding my name, it wouldn't save.

1. Record without an agent or date for the determination.
<img width="956" alt="Screenshot 2023-07-29 at 6 20 49 PM" src="https://github.com/ArctosDB/arctos/assets/17605945/1e0d15b6-9e0a-42ba-8d9b-5baa78808ef8">
2. Added agent then date:
<img width="956" alt="Screenshot 2023-07-29 at 6 21 03 PM" src="https://github.com/ArctosDB/arctos/assets/17605945/9844ccf7-1fba-4255-9f59-0c7bfa90cc17">
3. Save Changes, but agent did not save. Date did.
<img width="956" alt="Screenshot 2023-07-29 at 6 27 01 PM" src="https://github.com/ArctosDB/arctos/assets/17605945/c92cb544-270e-449c-b87f-1c1a55eb981d">

**Priority**
HIgh, as data is not being added.

**Comment by dustymc** [comment]
patched
