### ISSUE TITLE
Agent Pick doesn't show an exact match

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6577]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I wanted to add a relationship for a person to [University of Washington](https://arctos.database.museum/agents.cfm?agent_id=21264106). So I added "student of" then typed University of Washington in the related agent box. I am presented with the following choices:

![image](https://github.com/ArctosDB/arctos/assets/5725767/66170b67-6f4a-43f2-881b-f4dda8fbcc23)
![image](https://github.com/ArctosDB/arctos/assets/5725767/3185e03a-cfa1-4188-b533-232f3e542ff0)

Which do not include University of Washington - the EXACT match for the name I typed in.

**To Reproduce**
See above

**Expected behavior**
I would expect University of Washington to be in the pick list

**Screenshots**
See above

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 115.0.3 (64 bit)

**Additional context**
This means I cannot create the needed relationship to make this agent higher quality.

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by dustymc** [comment]
Neato...

That's me trying to juggle resources from the edge of a razor blade. Agent search was there (I can't say 'caused' but I didn't see anything else using more resources....) the last time Arctos crashed, so I throttled things - clearly too aggressively when an agent with a lot of *stuff* is involved. I'll up the throttle, but I don't think I can safely remove it. The problem involves our remaining thousands of low-information Agents (mixed in with a relatively few happily information-dense Agents) - perhaps you can poke the Agent Committee with a stick and see if there's a twitch?

I added an AKA - use UofW for now.
