### ISSUE TITLE
Coordinate rounding/truncation?

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#6578]
I just had a researcher point out an issue on one of his records that seems to be commonplace now that I am looking through several examples.

The original coordinates are being rounded/truncated and plotting to the wrong place.

For example, his provided coordinates 39.576699, -105.037745 are displayed as "40/-105":
![image](https://github.com/ArctosDB/arctos/assets/11336485/d0649096-b0c3-490e-b1ca-22c35d81ff73)

When I enter these coordinates in Google Maps, they plot correctly:
![image](https://github.com/ArctosDB/arctos/assets/11336485/a371fc39-b7ed-470f-8e92-fc922cf4bcb8)

Most of the records in question are documented range extensions and are currently getting written up as county record publications, so it is essential that these display correctly. The coordinates also display as "as is".  What is happening?

**Comment by dustymc** [comment]
Seems to be some crazy bug (involving column names) in the recently-updated JDBC drivers. Does seem to be display only.

**Comment by dustymc** [comment]
GUID page avoids the bug for next release, I opened a dev issue for a full solution.
