### ISSUE TITLE
specsearch part filtering

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ArctosDB/arctos#658]
```
Specsearch does not return "missing" (and ??) parts - need some sort of 
curatorial override.
```

Original issue reported on code.google.com by `dust...@gmail.com` on 11 Oct 2013 at 1:51

**Comment by dustymc** [comment]
I don't believe we have the resources to selectively filter parts by disposition. I'm not sure what the point of hiding missing (etc.) parts was. This seems to be useful information - eg, if I have a cranial morphology publication citing a specimen for which you report there is no skull, I might question the validity of the citation; if I can see that the skull is (missing/destroyed/whatever) I might wish to revise my research goals, etc.

**Comment by dustymc** [comment]
See also #480

**Comment by dustymc** [comment]
From @jldunnum https://github.com/ArctosDB/arctos/issues/1131#issuecomment-316140513

>I'd like to also ask that when a part is listed as missing it still show up under parts.  Currently when you do a search it doesn't appear at all if listed as missing.  I'd like to see what is supposed to be there and then when you go into the individual record you can see that it currently is listed as missing.

Agreed, setting this next task. I'll proceed with

- search finds all parts by default
- all parts are displayed for all users

unless there is other direction from ya'll.

**Comment by Jegelewicz** [comment]
I agree on seeing all parts cataloged regardless of disposition

**Comment by dustymc** [comment]
The function is rebuilt to ignore disposition - it will take some time for everything to make it to the cache. In light of "partdetail" (which includes disposition) now existing maybe we should just get rid of this?
