### ISSUE TITLE
Customizing profile within data entry erases data in other fields

### ISSUE THREAD

**Issue by genevieve-anderegg** [ArctosDB/arctos#6580]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
After entering data into a few fields in data entry, I want to make a change to my profile to show a few more fields (go from 1 identification attribute to 3). I click customize and change the value from 1 to 3. Click Save and Use. The form is completely reverted to the base profile, with the changes applied, but losing all the data I previously entered.

**To Reproduce**

Some data entered:
![image](https://github.com/ArctosDB/arctos/assets/83782023/9bb4929c-fa6f-449d-9ce6-b0d6ea1f0f64)

Requesting change, changing number of identification attributes from 1 to 3. Then clicked Save and Use:
![image](https://github.com/ArctosDB/arctos/assets/83782023/37219a07-2a95-4f33-8ce4-81c0ef7d02ac)

After clicking "Save and Use"
![image](https://github.com/ArctosDB/arctos/assets/83782023/540336e0-8861-4f5e-ae30-c2e5f7da4010)

All previously entered data is lost. 

**Expected behavior**
Would be great if we could make changes to the profiles in data entry while entering data, and not lose all previously entered data, especially if the profile update was in a different section of catalog record data entry (here, I lost changes to the catalog number and record remarks and a few other places, when I only changed the number of ID attributes).
Being able to edit the data entry form while within data entry keeps the record entry process nimble, and lessens the need for our volunteers to manage several different data entry profiles. 
Or is this by design?

**Desktop (please complete the following information):**
 Windows, Chrome, Firefox. This had been observed across several different Arctos accounts, computers, computer accounts, browsers, and days.

**Comment by dustymc** [comment]
Profiles carry data, so this is not very compatible with the current environment and I don't see a readily-available workaround.

**Comment by genevieve-anderegg** [comment]
Gotcha. We'll just have to make sure to communicate this with volunteers then!
