### ISSUE TITLE
Can't change identification

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#6581]
Trying to change identification of specimens. I cannot tell what I am doing wrong. I have selected the values from Arctos, not just typing them in. 

<img width="849" alt="Screenshot 2023-07-31 at 12 16 14 PM" src="https://github.com/ArctosDB/arctos/assets/5749672/2db74e8d-160a-4637-a1cb-cd63d3133b5d">
<img width="1410" alt="Screenshot 2023-07-31 at 12 15 13 PM" src="https://github.com/ArctosDB/arctos/assets/5749672/dcb75b5a-8382-4318-a8c7-b06109483263">

**Comment by Jegelewicz** [comment]
@cjconroy after selecting the name, did you hit the TAB key? that should then turn the Taxon A field green.

**Comment by dustymc** [comment]
Your browser is "helpfully" filling in the field. Backspace a character off the taxon and hit tab.

**Comment by cjconroy** [comment]
Wow. I am pretty sure I picked the species by first searching on Genus. But since I forgot to set identification order I had to do over. Which seems like it means you have to re-pick these items. Is that possible?

**Comment by dustymc** [comment]
>do over

Yes that sounds as expected - your browser probably re-filled the visible stuff and not the hidden stuff (that gets populated when a pick is successful). Tentatively closing, please reopen if this needs more discussion.
