### ISSUE TITLE
MSB Identifiers and Relationships have no way to link to the "parasite of" or "host of" records

### ISSUE THREAD

**Issue by msbparasites** [ArctosDB/arctos#6582]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
1) The relationship links are not working in Parasites and Hosts- need to restore the link
2) restore the link to the locality of the related record - it used to pull the host identification and locality into the parasite record and vice versa

**To Reproduce**
1. Go to https://arctos.database.museum/guid/MSB:Para:19503
2. Click on in Identifiers and Relationships either "parasite of" or "search" neither send you to the host record which is this: https://arctos.database.museum/guid/MSB:Host:15491. The reverse is true to if you want to see a parasite record directly linked out from host (or bird, or mammal, or fish etc...) record

**Expected behavior**
I expected to click the MSB catalog number of the host listed as "parasite of" and then be taken directly to that record and visa versa. The only places the links take you are to the code table definition or to catalog search, neither of which I want. 

When making host and parasite records, to save typing, I like to pull the data from either the host or parasite records to move on quickly since they are exactly the same.

**Screenshots**
![Screen Shot 2023-07-31 at 13 20 41](https://github.com/ArctosDB/arctos/assets/16925986/8e2cdb06-e6b4-4b74-95f0-415273d08592)

**Desktop (please complete the following information):**
 -iOS
 - Browser chrome
 - Version 115.0.5790.114

**Additional context**
It is fine to have flexibility to look up definitions and get a new catalog search window, but one of the whole points of an active catalogued number was that it too you directly to the record, and you didn't have to copy and paste the catalog number and search, and whole step that is unnecessary. Same for the pull feature for these related records. I use these feature a lot and would like them back. Thank you.

**Priority**
ASAP because we are starting a project where we need easy access to parasite and host (or bird, fish etc..) records with a single link and well as create new related records efficiently. Thank you

**Comment by Jegelewicz** [comment]
@msbparasites this is part of https://github.com/ArctosDB/arctos/issues/6163

**Comment by msbparasites** [comment]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

Describe the bug

The relationship links are not working in Parasites and Hosts- need to restore the link
restore the link to the locality of the related record - it used to pull the host identification and locality into the parasite record and vice versa
To Reproduce
Steps to reproduce the behavior:

Go to https://arctos.database.museum/guid/MSB:Para:19503
Click on in Identifiers and Relationships either "parasite of" or "search" neither send you to the host record which is this: https://arctos.database.museum/guid/MSB:Host:15491. The reverse is true to if you want to see a parasite record directly linked out from host (or bird, or mammal, or fish etc...) record
Expected behavior
I expected to click the MSB catalog number of the host listed as "parasite of" and then be taken directly to that record and visa versa. The only places the links take you are to the code table definition or to catalog search, neither of which I want.

When making host and parasite records, to save typing, I like to pull the data from either the host or parasite records to move on quickly since they are exactly the same.

Screenshots
Screen Shot 2023-07-31 at 13 20 41

Desktop (please complete the following information):
-iOS

Browser chrome
Version 115.0.5790.114
Additional context
It is fine to have flexibility to look up definitions and get a new catalog search window, but one of the whole points of an active catalogued number was that it too you directly to the record, and you didn't have to copy and paste the catalog number and search, and whole step that is unnecessary. Same for the pull feature for these related records. I use these feature a lot and would like them back. Thank you.

Priority
ASAP because we are starting a project where we need easy access to parasite and host (or bird, fish etc..) records with a single link and well as create new related records efficiently. Thank you

**Comment by campmlc** [comment]
pending resolution, Issues meeting 8-3-2023
