### ISSUE TITLE
Data entry converts © to something weird

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#6583]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
When creating a new record using the new data entry form, I entered the symbol for copyright using the Mac keyboard shortcut option+G. 

When the record loaded it appeared like this:
<img width="541" alt="Screenshot 2023-07-31 at 11 31 20 AM" src="https://github.com/ArctosDB/arctos/assets/17605945/2ee90388-cb99-4cbb-8ba7-bf4b8d67f504">

See record: https://arctos.database.museum/guid/UAM:EH:UA2023-006-0002AB

If there is a preferred/recommended way to easily enter the copyright symbol that won't cause this error, I'm happy to implement it. Prefer to not have to copy/paste from somewhere else, but if that's what I have to do, I'll make it a protocol for our Mac-based lab.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS 13.5
 - Browser [e.g. chrome, safari] Brave [Version 1.56.14 Chromium: 115.0.5790.114 (Official Build) (arm64)](https://brave.com/latest/)

**Priority**
Normal - annoying but isn't stopping me from doing my work.

**Comment by Jegelewicz** [comment]
The UTF-8 code is C2 A9 but my experience in data entry is those don't work. What does it look like in edit?

**Comment by dustymc** [comment]
I think this is probably your browser, but it's potentially related to https://github.com/ArctosDB/arctos/issues/6573 - for which I hope to have a fix out tonight, so I'm calling this next release.

>my experience in data entry is those don't wor

?!? hu? I just confirmed that non-ASCII works fine in entry, edit, and the resulting record.

<img width="477" alt="Screenshot 2023-07-31 at 13 40 19" src="https://github.com/ArctosDB/arctos/assets/5720791/4522bfde-59b7-467f-a0c4-811c1145b087">

<img width="482" alt="Screenshot 2023-07-31 at 13 40 25" src="https://github.com/ArctosDB/arctos/assets/5720791/58cd63e8-5350-488a-b12b-09a8b0a750c5">

<img width="309" alt="Screenshot 2023-07-31 at 13 40 32" src="https://github.com/ArctosDB/arctos/assets/5720791/7ca558e4-c18d-405f-8c10-f3331f98d74f">

```

arctosprod@arctos>> select identification_remarks from flat where guid='ALMNH:Herp:1';
    identification_remarks     
-------------------------------
 n'"$#n'"$#n'"$# " " \1 \' © 🤡
(1 row)
```

https://arctos-test.tacc.utexas.edu/guid/ALMNH:Herp:1

Characters are characters IF you're inputting Unicode - if not - https://handbook.arctosdb.org/documentation/encoding.html might have something useful, but it's probably just going to be a mess, find a way to deal with unicode!

I can confirm that this was jumbled by the time it was deleted from the bulkloader.

```
ingle sheet of blue-painted drywall with a drawing of a brown bear standing on its back legs, holding a book in it's right hand entitled "Track Book" while looking down at the bottom of its left back foot. The piece of drywall is cut down the center, proper left side (A) and proper right side (B). Artist's signature next to the bear's right foot: "Â© 1968 WDB". A measures 50" H x 15" W x 1/2" D. B measures 50" H x 18" W x 1/2" D. |                   | Angela Linn            | 2023-07-31       |                    |                    | dimensions       | A measures 50" H x 15" W x 1/2" D. B measures 50" H x 18" W x 1/2" D. |                   | Angela Linn            | 2023-07-31       |                    |                    | materials        | Drywall; Paint; Ink |                   | Angela Linn            | 2023-07-31       |                    |                    | value            | 100    
```

**Comment by AJLinn** [comment]
> I think this is probably your browser

I've got some more data entry to do this afternoon so I'll try out Firefox and see what happens with the same mac keyboard shortcut. Thanks!
