### ISSUE TITLE
Feature Request - Put Batch Scan Move Container link back on Move Container page

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#6584]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

The Move Container page used to have a direct link to the Batch Scan page. It was super helpful if you were moving individual things in the single scan page but then came to a drawer and you decided to scan a bunch at once. 

Maybe add a new button like this?
<img width="626" alt="Screenshot 2023-07-31 at 11 56 42 AM" src="https://github.com/ArctosDB/arctos/assets/17605945/b2dc45aa-4976-4d9a-af69-f68b2b4f5e59">

Then it would be sort of like moving to the single Move Container page from the batch scan page:
<img width="626" alt="Screenshot 2023-07-31 at 11 57 11 AM" src="https://github.com/ArctosDB/arctos/assets/17605945/9b8dc8e7-2b67-41ec-b315-9f0f21a9cdff">

Priority: Normal - we used to have it and I got used to it... but I can continue to click back to Tools Directory and click on Container: Move. I always like to save clicks if possible.

**Comment by dustymc** [comment]
Batch scan was supposed to be long gone, that development was stopped when requirements began changing mid-update: https://github.com/ArctosDB/arctos/issues/1689, https://github.com/ArctosDB/arctos/issues/4290

**Comment by AJLinn** [comment]
I don't understand... how are people scanning a whole drawer of items into the same place now?

**Comment by dustymc** [comment]
https://arctos.database.museum/moveContainer.cfm

**Comment by DerekSikes** [comment]
this link https://arctos.database.museum/moveContainer.cfm does not look to allow batch scanning. I use batch scanning all the time and have wanted improvements, all minor & mostly UI improvements.  I hope we're not going to lose batch scanning?

**Comment by dustymc** [comment]
>does not look to allow batch scanning

That's what it does?? It just tells you of problems as they happen instead of letting you do 100 things that aren't going to work and then complaining.

**Comment by DerekSikes** [comment]
Oh, So I can scan lots of comma-separated barcodes in to the child field?

**Comment by DerekSikes** [comment]
that's not obvious on the page. If it lets one scan lots of csv barcodes into the child field then it should say something about allowing that

**Comment by AJLinn** [comment]
Sorry, no one ever showed me the "new" tool of clicking the box at the top to scan multiples. I just had a UAM staffer show me. Another victim to progress while looking the other way...

**Comment by DerekSikes** [comment]
does that allow csv? I don't set my scanner to send tabs...

**Comment by DerekSikes** [comment]
could I get a reply re: csv barcode batch scanning before this is closed, thanks.

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/1689 is linked a few comments above.
