### ISSUE TITLE
Arctos Down - Planned TACC Maintenance 20 Aug 2023

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#6585]
Please complete to the best of your ability.

## Planned Outage
TACC Network Maintenance Sunday August 20 2023
From: Mark Brueschke
TACC network infrastructure will not be available from 8 AM to 2:00 PM (CDT) on Sunday, 20 August 2023. Network maintenance will be performed during this time.

Please submit any questions you may have via the TACC User Portal.
 
https://portal.tacc.utexas.edu/tacc-consulting
To manage your TACC Announcements subscriptions, please visit https://accounts.tacc.utexas.edu/subscriptions

## Communication before/during outage
- [x] Pin this issue
- [x] Banner updated @jegelewicz @mkoo
- [x] Email sent to AWG  
- [x] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [x] Unpin this issue
- [x] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by ewommack** [comment]
Emails will be going out on Wednesday the 16th of August and Friday the 18th of August.

**Comment by Jegelewicz** [comment]
Before I add a banner - just want to be sure this will affect Arctos. Banner suggestion:

Arctos will be offline from 8 AM to 2:00 PM (CDT) on Sunday, 20 August 2023 due to TACC network maintenance.
