### ISSUE TITLE
collecting source should be mapped to dwc:degreeOfEstablishment

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6586]
For my embarrassing question and the answer that proves this see https://github.com/gbif/portal-feedback/issues/4885

We need to change the mapping of collecting source to dwc:degreeOfEstablishment.

**Comment by ewommack** [comment]
Yep I agree and the explanation was pretty clear.

One a side note - I learned a bit about more power in different terms. Establishment Means seems like a field to pay attention to as we work with more breeders/zoo groups. 

We should be using dwc:degreeOfEstablishment for collecting source, definitely.

**Comment by mkoo** [comment]
Makes sense and thanks for highlighting the original discussion.
What's the status of this change in IPT mapping?

**Comment by dustymc** [comment]
Added to map, merge https://github.com/ArctosDB/arctos/issues/7348
