### ISSUE TITLE
new data entry form 'date copy across'

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#6589]
I thought we had asked for the return of the button to copy the date from verbatim to began & end date, or at the least to copy began date to end date so I clicked 'copy across' expecting that would do what I had hoped and instead it replaced all the dates in the data entry form with the collection date & now I have to delete and replace all those dates with the correct dates.

1) can we get the prior functionality returned
2) can this 'copy across' button go away or include a warning ' do you really want to replace all the dates of this record with this date y/n'

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.
normal

**Comment by DerekSikes** [comment]
Sorry - I see that there's a button near the verbatim date to copy to the began/ended... but I thought we had a little arrow button that allowed one to click & copy the began to ended?

And the warning on the copy across still seems like a good idea. Not a bug but I don't know how to change the label to 'feature request'

**Comment by AJLinn** [comment]
> And the warning on the copy across still seems like a good idea. Not a bug but I don't know how to change the label to 'feature request'

I think that would be useful also. I had that happen when I copied across the agents and it overwrote all the names. 

Is there a way to do "from here forward" when you copy across or is it a all-or-nothing kind of button?

**Comment by dustymc** [comment]
> little arrow 

https://github.com/ArctosDB/arctos/issues/5159

>began to ended

I could add a "Copy2Next" (but the form's getting crowded, there are real usability implications in that, and I'm not sure where that'd ever be better than the one from event_verbatim_date so needs discussion).

>warning

I'm guessing that would be near-universally hated but no technical barriers.

>forward

There is no forward - the form is now CSS-sorted so no two things can necessarily agree on direction.
