### ISSUE TITLE
Can't update ID of formula B records?

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#6591]
Trying to batch update the ID on these:

UAM100495479,UAM100495478,UAM100392372,UAM100495325,UAM100495257,UAM100495253,UAM100495245,UAM100495244,UAM100495238,UAM100498750,UAM100497128,UAM100495487,UAM100497114,UAM100495482,UAM100495484,UAM100495483,UAM100495481,UAM100495480,UAM100495485,UAM100360950,UAM100360952,UAM100360956,UAM100363559,UAM100363503,UAM100363497,UAM100363510,UAM100363496,UAM100363506,UAM100363522,UAM100363498,UAM100360947,UAM100360976,UAM100360975,UAM100363509,UAM100360977,UAM100360953,UAM100360948,UAM100360951,UAM100360970,UAM100360980,UAM100371255,UAM100363512,UAM100497117,UAM100497156,UAM100497116,UAM100439248,UAM100444515,UAM100349602,UAM100354920,UAM100354919,UAM100355563,UAM100354918,UAM100355561,UAM100354724,UAM100390608,UAM100381065,UAM100497110,UAM100497118,UAM100497121,UAM100497113,UAM100353408,UAM100353404,UAM100353405,

some of which have ID formula B IDs (that I want to make ID order=0 and add a new formula A id to all).

Getting this error:
string	INSERT INTO identification_taxonomy ( identification_id, taxon_name_id, variable ) VALUES ( 15968637, [CF_SQL_INTEGER], 'B' )
DatabaseName	
string	PostgreSQL
DatabaseVersion	
string	12.2
DriverName	
string	PostgreSQL JDBC Driver
DriverVersion	
string	42.6.0
Datasource	
string	user_login
DataSource	
string	user_login
Detail	
string	
ErrorCode	
string	0
Extended_Info	
string	
ExtendedInfo	
string	
Message	
string	ERROR: null value in column "taxon_name_id" violates not-null constraint Detail: Failing row contains (15968637, null, B).
NativeErrorCode	
number	0
queryError	
string	INSERT INTO identification_taxonomy ( identification_id, taxon_name_id, variable ) VALUES ( 15968637, [CF_SQL_INTEGER], 'B' )
Sql	
string	INSERT INTO identification_taxonomy ( identification_id, taxon_name_id, variable ) VALUES ( 15968637, [CF_SQL_INTEGER], 'B' )

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.
high - impeding work

**Comment by dustymc** [comment]
This must be related to https://github.com/ArctosDB/arctos/issues/6552#issuecomment-1654659864, I'm just going to remove those 'existing...' options unless some compelling and functional reason shows up now-ish - I (clearly!) can't see how they can work in the current system.

**Comment by DerekSikes** [comment]
I don't understand what you're going to do and what consequences it will have. Can you elaborate?

**Comment by dustymc** [comment]
The handlers behind these things...

<img width="657" alt="Screenshot 2023-08-02 at 09 19 13" src="https://github.com/ArctosDB/arctos/assets/5720791/e9ebdfe1-bbd4-4ad8-8539-4c17eb1b9358">

don't make sense (the kind that I can write code to) in a model where there's not necessarily one 'good' identification. I'd like to remove them.

**Comment by DerekSikes** [comment]
As long as this fix can happen asap because I've got a mess of ants that need to have their IDs updated today

**Comment by DerekSikes** [comment]
Just checking in on this. The error seems to be due to some specimens having **ID formula A or B.** I'm not using any of those handlers-tools you mention above and want to remove. At this point I could have spent the time to one-at-a-time change the IDs of those with formula A or B to formula A so I can then proceed but that would be very inefficient use of my time.

**Comment by DerekSikes** [comment]
So I went and changed all the ID formula A or B records to order = 0 and set a different ID to order = 1 and the bulk ID update still failed with this error: Catch
Entries: 15
additional	
Struct (ordered)
SQL	
string	INSERT INTO identification_taxonomy ( identification_id, taxon_name_id, variable ) VALUES ( 15969057, [CF_SQL_INTEGER], 'B' )
DatabaseName	
string	PostgreSQL
DatabaseVersion	
string	12.2
DriverName	
string	PostgreSQL JDBC Driver
DriverVersion	
string	42.6.0
Datasource	
string	user_login
DataSource	
string	user_login
Detail	
string	
ErrorCode	
string	0
Extended_Info	
string	
ExtendedInfo	
string	
Message	
string	ERROR: null value in column "taxon_name_id" violates not-null constraint Detail: Failing row contains (15969057, null, B).
NativeErrorCode	
number	0
queryError	
string	INSERT INTO identification_taxonomy ( identification_id, taxon_name_id, variable ) VALUES ( 15969057, [CF_SQL_INTEGER], 'B' )
Sql	
string	INSERT INTO identification_taxonomy ( identification_id, taxon_name_id, variable ) VALUES ( 15969057, [CF_SQL_INTEGER], 'B' )

**Comment by DerekSikes** [comment]
Ok, so I went and deleted the Formula A or B ids from the 22 records that had them. Then I used the batch ID tool and another weird bug appeared! All the records that never had the Formula A or B IDs were updated with my new ID but none of the 22 records that had previously had Formula A or B Ids were updated - and no errors were reported. Note that all these 22 records now have an ID formula of A ? so perhaps that's what prevented them from being updated? Do I now have to go delete these formula A? IDs as well?

In any case, this tool that I need all the time is is dire need of fixing so it works again.

**Comment by DerekSikes** [comment]
these are the 22 records that need to have their IDs updated: https://arctos.database.museum/search.cfm?identified_agent=sayde&taxa_formula=A%20%3F&barcode=UAM100495479%2CUAM100495478%2CUAM100392372%2CUAM100495325%2CUAM100495257%2CUAM100495253%2CUAM100495245%2CUAM100495244%2CUAM100495238%2CUAM100498750%2CUAM100497128%2CUAM100495487%2CUAM100497114%2CUAM100495482%2CUAM100495484%2CUAM100495483%2CUAM100495481%2CUAM100495480%2CUAM100495485%2CUAM100360950%2CUAM100360952%2CUAM100360956%2CUAM100363559%2CUAM100363503%2CUAM100363497%2CUAM100363510%2CUAM100363496%2CUAM100363506%2CUAM100363522%2CUAM100363498%2CUAM100360947%2CUAM100360976%2CUAM100360975%2CUAM100363509%2CUAM100360977%2CUAM100360953%2CUAM100360948%2CUAM100360951%2CUAM100360970%2CUAM100360980%2CUAM100371255%2CUAM100363512%2CUAM100497117%2CUAM100497156%2CUAM100497116%2CUAM100439248%2CUAM100444515%2CUAM100349602%2CUAM100354920%2CUAM100354919%2CUAM100355563%2CUAM100354918%2CUAM100355561%2CUAM100354724%2CUAM100390608%2CUAM100381065%2CUAM100497110%2CUAM100497118%2CUAM100497121%2CUAM100497113%2CUAM100353408%2CUAM100353404%2CUAM100353405%2C

**Comment by DerekSikes** [comment]
I was able to update these 22 records IDs.
