### ISSUE TITLE
Code Table Request - can we get 'AI image match' added to 'nature of ID'

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#6596]
Increasingly I'm getting IDs that originate from artificial intelligence image matching technology. One today was based on the app 'Leps' developed by the NSF funded LepNet project that trained the AI on images of museum specimen Lepidoptera. A local in town sent me a photo of a moth & since I don't know moths well, I used the app. The match seems good to me so I'm making an observation record and figure 'audio-visual' is a little vague as a nature of ID choice in this case.

Of course, I checked out the species to ensure I agreed with the ID. Just for the record - the iNaturalist AI got it in the wrong family but the Leps app (appears to have) nailed it.
![Orange moth](https://github.com/ArctosDB/arctos/assets/9099827/e38727ff-2756-451c-bca7-60c05f8dfe84)

the Leps app ID'd it as Enargia paleacea https://www.gbif.org/species/1770150

**Comment by DerekSikes** [comment]
PS, I'm following up with some moth experts so the ID might get improved but I'd still like to record this AI based ID

**Comment by Jegelewicz** [comment]
@DerekSikes does it seem appropriate to create an agent for the AI, then just use that as the determiner?

**Comment by dustymc** [comment]
I definitely support somehow conveying the concept of 'machines did it.'

People have been calling things that aren't AI AI for a while now, so I'm not sure I'm crazy about the proposed term. 

"Leps app" should definitely be an Agent (and, assuming it's getting better as it gets used, identification dates will be extra-important).

"Some app-agent using audio-visual" probably adequately conveys the information, but maybe an additional term ("machine-based automation"??) in https://arctos.database.museum/info/ctDocumentation.cfm?table=ctnature_of_id would make that easier to find and understand?

**Comment by wellerjes** [comment]
Can we require two identifiers when using an AI component? Because someone is reviewing the AI identification before it goes into Arctos confirming that they agree with the AI assessment.

**Comment by Jegelewicz** [comment]
If we are to proceed with this code table request, we need a code table template.

**Comment by DerekSikes** [comment]
I like the solution of making an agent for the AI app

**Comment by Jegelewicz** [comment]
@DerekSikes did you do that already?

I need to add to documentation.

**Comment by Jegelewicz** [comment]
Also, @dustymc do AI need a new agent type, or can we just go with "other"?

**Comment by dustymc** [comment]
I think [organization](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctagent_type#organization) - there's no such thing as AI (or perhaps they're just very sneaky!), this isn't a human-equivalent entity, its a thing built by a definable group of people.

**Comment by Jegelewicz** [comment]
Fair and relationships could make that clear...

**Comment by DerekSikes** [comment]
I made this organization agent: https://arctos.database.museum/agents.cfm?agent_id=21349097

I saw no place to put the URL other than remarks so put it there.

**Comment by dustymc** [comment]
>place to put the URL

updated

**Comment by dustymc** [comment]
done?
