### ISSUE TITLE
issue uploading multiple identifications

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#6597]
This appears when uploading catalog records with multiple identifications; if the "identification_#_order" is 0, it will not load.
Text: null value in column "identification_order" violates not-null constraint

Before, multiple identifications would appear in "extras" - is that being phased out?

**Comment by dustymc** [comment]
I need data, a record, some sort of more information.

**Comment by wellerjes** [comment]
[CHAS_bulkload-error_2023-08.csv](https://github.com/ArctosDB/arctos/files/12251982/CHAS_bulkload-error_2023-08.csv)

here's a csv with some of the stuck records. I was able to load a few others by changing the "identification_1_order" to 1, then manually fixed it by going to the catalog record after it uploaded and changing it back to 0.

**Comment by dustymc** [comment]
Thanks!

Those are NULL, not 0.

<img width="345" alt="Screenshot 2023-08-03 at 07 52 44" src="https://github.com/ArctosDB/arctos/assets/5720791/c7d50b39-c884-4a4b-b745-5cb7e2fe6431">

**Comment by wellerjes** [comment]
Reopening because I have new info from one of our collections technicians. The "0" value is not always carrying over from the data entry from, which is why those values were "null". He's had to go into "Browse and Edit" to add back the "0" manually.

**Comment by vbec97** [comment]
Following up to confirm that this is still the case as of today. Upon entering two identifications at once when creating a new record, one ranked 1 and the other ranked 0, the "0" disappears from the identification_order field once it's pushed to the bulkloader, while the "1" remains in the other. In order for the records to be successfully autoloaded, I have to manually re-enter the 0 from "Browse/Edit Bulkloaded Data".

**Comment by dustymc** [comment]
>disappears from the identification_order field

That's the default behavior, which can be changed in Customize.

**Comment by vbec97** [comment]
Sorry, to clarify, I mean the identification order "0" disappears from the bulkloader although I originally entered the record with it. That is why I have to _manually re-enter_ it again via the bulkloader. This issue only seems to be affecting identification order "0" and not "1".

**Comment by Jegelewicz** [comment]
@dustymc I think this is a bug? when someone enters "0" it gets converted to NULL

**Comment by AJLinn** [comment]
This happened to me when my student created records in the data entry form and left the IDs as a zero value. The load failed and I had to manually enter 1 in each field.

**Comment by Jegelewicz** [comment]
@AJLinn there is a difference between blank and "0". Were they blank?

**Comment by AJLinn** [comment]
Oh well, maybe they were actually NULL... now that I look at the form. I was thinking they were "0" by default. Sorry! Ignore me!

**Comment by Jegelewicz** [comment]
Thanks for the confirmation!

**Comment by dustymc** [comment]
AHA! Thanks, indeed a bug, found and will be mashed in next release, which I'll try to get out tonight.
