### ISSUE TITLE
Show, Carry, Hide not all working correctly in custom profiles

### ISSUE THREAD

**Issue by AdrienneRaniszewski** [ArctosDB/arctos#6601]
**Describe the bug**
record attribute values are carrying over despite being set to "show"

**To Reproduce**
1. enter data in a profile. I'm currently using MSB:Mamm ectos
2. save
3. the refreshed entry screen has data from the last record that it shouldn't

**Expected behavior**
According to the customize screen setting the field to "show" should result in an empty value after save. It doesn't for all fields. The ones I'm noticing are the record attribute values. and identification remark. there could be others.

I do notice if I just refresh my browser all the old data clears out. but still... seems like a glitch

**Screenshots**
<img width="536" alt="Screenshot 2023-08-03 at 11 50 11 AM" src="https://github.com/ArctosDB/arctos/assets/23192428/355fe3b1-406e-4425-9414-2edfa4ee5779">
<img width="545" alt="Screenshot 2023-08-03 at 11 44 18 AM" src="https://github.com/ArctosDB/arctos/assets/23192428/4c248b62-9c74-4d75-80ab-111e59b11f79">

Thanks!

**Comment by wellerjes** [comment]
Yes, our staff encountered this as well. Specifically with the fields identification remarks and verbatim locality -- they are set to show but have been carrying info to the next record.
