### ISSUE TITLE
Map event method to Darwin Core sampling Protocol

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6605]
From https://github.com/ArctosDB/arctos/issues/6218#issuecomment-1536820947

> If I start using this event-method attribute will it be mapped to the Darwin core collection method so GBIF et al. get the data?

@dustymc where are we mapping collection method now?

The only place that seems remotely appropriate is [dwc:samplingProtocol](https://dwc.tdwg.org/terms/#dwc:samplingProtocol) and looking at that Darwin Core term, this is something that belongs with the [dwc:Event](https://dwc.tdwg.org/terms/#event) (An action that occurs at some location during some time.) It would make sense to map [event method](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_event_attr_type#event_method) to this Darwin Core field.

See also [GBIF Occurrence Core](https://rs.gbif.org/core/dwc_occurrence_2022-02-02.xml) 

If we are already mapping collecting method to dwc:samplingProtocol, the I suggest a concatenation of the two replace the current data.

**Comment by dustymc** [comment]
Previously done, merge --> https://github.com/ArctosDB/arctos/issues/7348
