### ISSUE TITLE
data not updating in search results

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#6606]
**Describe the bug**
The locality information was incorrect in the catalog record. Victor updated it, but the search results still reflect the "unaccepted" data. It has been a few days and the info hasn't corrected for this specific catalog number. He updated another record and the correct (set as unverified in the record, but not incorrect) data appeared in the search results shortly after.

**To Reproduce**
1. Search CHAS:Herb:1878.17.1228
2. How the locality data shows up in the search results: 
![image](https://github.com/ArctosDB/arctos/assets/93737929/91d914e4-aac7-433d-8520-25b0db389ce4)
3. How the data shows up in the catalog record: 
![image](https://github.com/ArctosDB/arctos/assets/93737929/e9e94397-4246-44bf-b9be-00f5fb804982)

**Expected behavior**
The search results should reflect the current Place and Time data. Why is this impacting just the one record? (that we know of)

**Screenshots**
See above.

**Data**
n/a

**Desktop (please complete the following information):**
 - Browser: Firefox

**Priority**
high

**Comment by dustymc** [comment]
Glitch in the matrix. Try the request cache refresh button from the record.

**Comment by wellerjes** [comment]
It's saying the information is current and does not appear to register when I push the button:
![image](https://github.com/ArctosDB/arctos/assets/93737929/abd8b7d0-88d4-4d5d-b9cc-0f4e8f052cfb)

**Comment by dustymc** [comment]
Thanks, I rebuilt getpriorityspecimenevent to subtract more weight for 'unaccepted' - the presence of coordinates was (incorrectly, I think) balancing that out.

**Comment by wellerjes** [comment]
Thank you!
