### ISSUE TITLE
bulkloading identifications with new ranking system

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#6607]
**Is your feature request related to a problem? Please describe.**
I just bulkloaded some identifications. I was able to set them to "1" so they would be the valid/accepted identification in the catalog record and I uploaded without any issue. However, upon review of the catalog record, both the new identification and the previous/unaccepted identification are set to "1".

![image](https://github.com/ArctosDB/arctos/assets/93737929/8fa37b2a-f9f9-4c36-b0b4-60b771f931aa)

Is there a way to unaccept the current identification when a new identification is uploaded? I remember being able to set accepted vs. unaccepted in the past; the column title was: "accepted_fg"

**Comment by dustymc** [comment]
This seems like a place where an ad hoc Committee would be valuable; there are several requests (some of which probably conflict with others) regarding the new identification model, The Community putting together a comprehensive picture of how things do and should work would be valuable to me, and I think everyone else.

>unaccept the current identification 

Some variant of this seems to show up fairly often. I think perhaps a fundamental aspect of the model isn't well understood: There is no **the** - well, anything. These states are all possible:

* one accepted identification
* no accepted identifications
* more than one accepted identifications

paired with

* zero unaccepted (defined as identification_order==0) identifications, or 
* more than zero unaccepted identifications

In other words, it's possible to

* do what you did in the old model, limit yourself to one 'preferred' and any number of 'unaccepted', or
* say things like "we don't think any of these are correct", or
* say things like "we think all of these are correct, we like them all equally", or
* say things like "we think all of these are correct, but we like some of them more than we like others of them", or
* do lots of other things which nobody has yet thought of, probably.

https://github.com/ArctosDB/arctos/issues/6552 set some defaults on one UI (essentially what's being requested here, and a 'change_all_existing_identification_order_to' addition to the loader does look plausible), and then I think that confused a bunch of people (in the linked issues). Can we meet and figure out what needs to happen in both documentation and the UI?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I'm doing my first citation upload since the update and it looks like the new upload format is going to add a lot of work manually adjusting rank. I don't see rank in template? This form defaults to 1?

I need to fields for:
-Set rank of the new citation ID. We're uploading lots of old records, many of these ids are no longer the accepted ID.
-Set the rank of the existing IDs. This could be a simple, set all other ids to this rank, if blank do nothing with the existing IDs.

I'll go forward with my current load, but I can't do any other citation uploads until this is fixed.

**Comment by dustymc** [comment]
I think the actionable parts of this have been addressed elsewhere, a Committee does not seem to be appearing, closing.
