### ISSUE TITLE
portals & stats

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#6608]
Can we get a link to the portals on the tools directory? I've found the link after many many clinks through various arctos webpages...

also, why are the record counts for UAM:Ento different between the stats page:
https://arctos.database.museum/info/sysstats.cfm

396,192 records

and the portals page:
https://arctos.database.museum/home.cfm

398043 records

**Comment by Jegelewicz** [comment]
> Can we get a link to the portals on the tools directory?

Is this what you are looking for?

![image](https://github.com/ArctosDB/arctos/assets/5725767/0908f200-ca0d-4c17-a63d-2284d8ee3fed)

It is on the details page for each collection, but you can always just replace the GUID of any collection with the GUID of interest.

If that isn't what you want - let me know!

**Comment by DerekSikes** [comment]
I want this link: https://arctos.database.museum/home.cfm

which I would think we'd want to make much more easily found if we want to show all the different collections using arctos.

**Comment by Jegelewicz** [comment]
That is Search Collections from the main menu. Where else should it be?

**Comment by DerekSikes** [comment]
I went to the tools directory page: https://arctos.database.museum/directory.cfm

and searched for 'Search Collections' with my browser and it was not found. I see it in the 'search' drop down menu under 'collections' which is basically hiding it & the removal of the 'portals' from the name that we've grown used to referring to these as has made _it extra hard to find._

Also, every search link in the drop down menus should be in the tools directory listing, shouldn't it? Some but not all is not good UI.

And while I'm on this subject, the drop down search menu could use 'accessions and loans' which is I bet far more often needed by operators than 'search collections' = (search portals).

**Comment by Jegelewicz** [comment]
> the drop down search menu could use 'accessions and loans' which is I bet far more often needed by operators than 'search collections' = (search portals).

All of the "management" tools are found in the Tools Directory. The things in the Search menu are available to anyone, while accessions and permits are only available to operators with the appropriate permissions.

> every search link in the drop down menus should be in the tools directory listing, shouldn't it? 

I think they all are, but we certainly could have missed one!

Search collections is there in the Community tile, maybe we can talk about changing it to Search Collections, but for some reason we ordered it as Collections: Search.

![image](https://github.com/ArctosDB/arctos/assets/5725767/2e377ac7-a6ce-4895-a7aa-7eee429095b4)

**Comment by Jegelewicz** [comment]
Also, FWIW

> the removal of the 'portals' from the name that we've grown used to referring to these as has made it extra hard to find.

Was removed very purposefully because "we" were the only ones who knew what it meant.

**Comment by Jegelewicz** [comment]
@dustymc from above:

> why are the record counts for UAM:Ento different between the stats page:
https://arctos.database.museum/info/sysstats.cfm
> 
> 396,192 records
> 
> and the portals page:
> https://arctos.database.museum/home.cfm
> 
> 398043 records
>

**Comment by dustymc** [comment]
cache and/or encumbrances

**Comment by mkoo** [comment]
asked, answered!
