### ISSUE TITLE
Bulkloader identifiers problem: null value in column "assigned_by_agent_id" violates not-null constraint

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#6610]
A lab tech (mgwyatt) entered 300+ records into the bulkloader but when I go to load them they fail with this error:

null value in column "assigned_by_agent_id" violates not-null constraint

two issues:

1) the lab tech should not have been allowed to save the records into the bulkloader if this would prevent them from loading - can we get this error check earlier in the process so the tech can fix the error immediately?

2) I used the SQL tool to add my agent name to the the assigned_by_agent_id field but the records are still not loading and are reporting the same error.

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.
High - wanted these loaded today so I could generate labels to put on them tomorrow.

**Comment by Jegelewicz** [comment]
> I used the SQL tool to add my agent name to the the assigned_by_agent_id field but the records are still not loading and are reporting the same error.

Try using the agent identifier instead. That can be found after the last "/" in the agent url

**Comment by DerekSikes** [comment]
using the agent identifier instead did not work. same error.

**Comment by DerekSikes** [comment]
strange, even though I used the SQL tool to insert the agent identifier # when I just opened one of the records it did not have the agent identifier # - it had my name. I will try the SQL tool again.

**Comment by DerekSikes** [comment]
This time the SQL tool worked. I opened a record and it had my # instead of name. However, at the bottom of the page it says "identifier_1_issued_by is not valid"

**Comment by Jegelewicz** [comment]
Do you have anything in the issued_by column?

**Comment by DerekSikes** [comment]
Yes, the issued_by has my agent identifier number.. but now when I try to load these records I get this error:

identifier_1_issued_by is not valid

**Comment by Jegelewicz** [comment]
> identifier_1_issued_by is not valid

That column requires a preferred name or user name and is different than assigned by agent - the assigned by agent should be populated when the record is entered - I don't know why that didn't happen correctly. That appears to be the "bug". Issued by is added intentionally by whoever enters the data and should be the name of the agent who issued the related identifier. If that is your collector number, then you should be the issued by agent, but it should be `Derek S. Sikes`.

**Comment by DerekSikes** [comment]
Ok I changed the identifier_1_issued_by back to Derek S. Sikes

But how do I change the assigned_by_agent_id ?

It does not seem possible.

**Comment by Jegelewicz** [comment]
> It does not seem possible.

Yeah - that makes sense because it is assigned by Arctos, thus the bug. I guess I don't have a fix - I was hoping you could see that column in Browse and Edit. @mkoo is there someone who could fix this now?

**Comment by dustymc** [comment]
I don't have the bandwidth to dig very deep now, but I think maybe the problem is with record_event_determiner (which would be converted to an identifier in specimen_event.assigned_by_agent_id for the load).

There should be a better error, I'll get that when I can, but dependencies are (hopefully!) spelled out in the [spreadsheet](https://docs.google.com/spreadsheets/d/1VbNC3k17WAHMum_qD5UYoXxUUWwXXh5gZSM5vfGvRzU).

**Comment by DerekSikes** [comment]
I don't understand. Did you provide a solution that I can use to load these records?

**Comment by dustymc** [comment]
There's an unsatisfied dependency for 386 records entered by that user.

[104 | record_event_determiner | Required if record_event_type is given. | agent](https://docs.google.com/spreadsheets/d/1VbNC3k17WAHMum_qD5UYoXxUUWwXXh5gZSM5vfGvRzU/edit#gid=529334279)

```

arctosprod@arctos>> select record_event_determiner, record_event_type, count(*) from bulkloader where enteredby='mgwyatt' group by record_event_determiner,record_event_type;
 record_event_determiner | record_event_type | count 
-------------------------+-------------------+-------
 M. G. Wyatt             | collection        |     4
 Stephen F. MacLean Jr.  | collection        |     1
                         | collection        |   386
(3 rows)


```

**Comment by DerekSikes** [comment]
ok, how to fix this?

**Comment by Jegelewicz** [comment]
You need to add an agent to `record_event_determiner` (the person who is saying this collecting event belongs with this catalog record).

**Comment by DerekSikes** [comment]
That worked! & Yes, would be good if the data entry form did not allow saving with this as NULL.
