### ISSUE TITLE
Locality not saving

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#6612]
I just uploaded a [record](https://arctos.database.museum/guid/UCM:Obs:AC-350) and none of my locality info is present that I successfully entered, saved and loaded from the Data Entry screen.

![image](https://github.com/ArctosDB/arctos/assets/11336485/e7fe619b-920d-40f1-b6aa-105c4bbe0154)

When I go to the Locality form to re-enter this info, I am unable to do anything but create a new specimen event. When I try to do so, I get an error:

![image](https://github.com/ArctosDB/arctos/assets/11336485/8a94b7fb-86d1-4d02-8c56-3566be430157)
![image](https://github.com/ArctosDB/arctos/assets/11336485/2b6bd6a9-0fa6-4349-95ee-04a0fc4e9082)

Help?

**Comment by dustymc** [comment]
Check the [spreadsheet](https://docs.google.com/spreadsheets/d/1VbNC3k17WAHMum_qD5UYoXxUUWwXXh5gZSM5vfGvRzU) for dependencies - wild guess, record_event_type wasn't provided?

Click the 'pick new event' button to fix that error - the specimen_event you're trying to create needs a collecting_event.

**Comment by ebraker** [comment]
> wild guess, record_event_type wasn't provided?

Maybe? 

`click the 'pick new event' button to fix that error `

but that would require an existing event?

I'm just going to delete this record.
