### ISSUE TITLE
Adding catalog records to data loan through add records app?

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#6617]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Can't add records through the tool when doing a data loan
**To Reproduce**
Create data loan
Try to add records through "Add records" tool

**Expected behavior**
To not have to batch load data loan items if it's just a fewrecords

**Screenshots**
![image](https://github.com/ArctosDB/arctos/assets/38706617/866d06e4-f0b4-4941-93b1-a9d3612b90b0)
**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**
Chrome
**Additional context**
Is there a reason we have to batch load data items now? No tool for small data loans?

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by ebraker** [comment]
I was just about to add this issue. I'm running into this problem as well.

**Comment by ebraker** [comment]
Seems like the data loan item bulkloader doesn't work either:
![image](https://github.com/ArctosDB/arctos/assets/11336485/14bd6b5d-54b8-4c20-ad54-ae907b482b58)
[pinnacles.csv](https://github.com/ArctosDB/arctos/files/12306301/pinnacles.csv)

**Comment by dustymc** [comment]
A data loan item UI could exist, just needs prioritized.

The loader seems to have a bug - I'll split that off and get a fix out ASAP, but I think it's firing because that loan doesn't exist (or maybe is the wrong type).

**Comment by ebraker** [comment]
Worked for me! Leaving open until @mvzhuang confirms all is good on her end.

**Comment by dustymc** [comment]
I believe this is done.
