### ISSUE TITLE
Object Tracking tree sort order still not making sense

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6619]
I know this issue has been raised multiple times, but the sort order of multiple containers searched in object tracking Find Container is still random for positions. 

Expectation: If the hierarchy goes from  freezer label/barcode-> rack position -> rack label/barcode-> box position -> box label/barcode-> box position, then the positions should sort numerically within each category.

Right now, I can choose to sort by label or barcode, numeric or not - but I can't edit how Arctos sorts the positions within those.
And the positions sort appears to be random from the point of view of a human observer.
Can we get this fixed, so that positions of any kind sort by their numeric values, pretty please?

![Screenshot 2023-08-09 14 34 55](https://github.com/ArctosDB/arctos/assets/14808196/e73af547-b54c-41bd-9412-d5089858613c)

**Comment by campmlc** [comment]
checking back in on this one? Possible?

**Comment by dustymc** [comment]
I can't re-create this. The sort is applied server-side, when a request is made, and won't affect anything that was already on the page - I suspect the screenshot was made via multiple requests, possibly with different sort criteria. Closing as inactionable; please re-open with a path to replicate if the sort can be demonstrated to not be working properly.
