### ISSUE TITLE
Search Catalog Records by date range?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6621]
Am I missing something? I can't find how to search on records with collecting event dates between two values, e.g. Jan 1 and Dec 31 of a given year.
We used to have this functionality - and the current interface does not make it easy to find.
Help?
Priority: high, needed for work and important for discovery.

**Comment by mkoo** [comment]
In the Customize Search, add the fields Began Date and End Date (verbatim date is default). Then use ISO dates to search, so everything in 2022 would be:
Began Date =2022-01-01 and End Date = 2022-12-31

I usually also tack on specimen event date in Results so I can sort results
