### ISSUE TITLE
Feature Request - data entry magic

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6623]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

Once upon a time we entered a single part = whole organism, formalin-fixed, 70% ethanol, now we enter

part name = whole organism
preservation = formalin
preservation = ethanol, 70%

And from the database perspective, this makes great sense! But from a data entry perspective it requires a ton of effort!

**Describe what you're trying to accomplish** 
_A clear and concise overview of the goals; why are you asking for this?_

Simplify data entry

**Describe the solution you'd like**
_How might we accomplish your goals?_

I'd like to pick from a list that includes whole organism, formalin-fixed, 70% ethanol but what happens after that is the appropriate fields in data entry get populated:

part name = whole organism
preservation = formalin
preservation = ethanol, 70%

then I could add dates, determiners and remarks to the preservation attributes if I choose.

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

Just keep on picking and picking and picking or having students forget to pick....

**Additional context**
_Add any other context or screenshots about the feature request here._

This will require building the "magic" for any "compound part plus part attribute" thing.

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._

Normal - it isn't necessary, but if you think about the potential time saved across all collections entering data - it could be HUGE?

**Comment by DerekSikes** [comment]
similar magic I'd love to see is an option operators can select in their profile to make it so that any attributes on any attribute-editable forms get auto-populated with the name and date of the operator (and any attributes that are not 'used' (eg the key values like 'preservation' are left null) will be ignored & not saved & not throw errors).

**Comment by dustymc** [comment]
I don't think that would be particularly magical to implement, but there was a great deal of confusion around the single-field preservation so I'm not sure how *understandable* such a thing would be. I think this would minimally need some sort of very open discussion and *very* clear documentation.

>auto-populated with the name 

<img width="1010" alt="Screenshot 2023-08-11 at 07 25 18" src="https://github.com/ArctosDB/arctos/assets/5720791/c32d108c-0f8d-40c6-876d-06e2b4cca99b">

>today-date

That would be some sort of magic and I think would need the same level of openness as above.

> ignored & not saved & not throw errors

https://github.com/ArctosDB/arctos/issues/6615 might be the place to discuss - [documentation](https://docs.google.com/spreadsheets/d/1VbNC3k17WAHMum_qD5UYoXxUUWwXXh5gZSM5vfGvRzU) will always tell you how things work and interact.
