### ISSUE TITLE
Explain options on data entry customization

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6624]
I am trying to write documentation

What does the Pulled column do?

What does the Use button do?

**Comment by dustymc** [comment]
<img width="375" alt="Screenshot 2023-08-14 at 06 24 38" src="https://github.com/ArctosDB/arctos/assets/5720791/19b17e49-629a-4956-8ae9-ff2d0ebf73aa">


<img width="391" alt="Screenshot 2023-08-14 at 06 25 34" src="https://github.com/ArctosDB/arctos/assets/5720791/d4296430-75b7-4716-ade8-720e9a223f16">


<img width="609" alt="Screenshot 2023-08-14 at 06 26 03" src="https://github.com/ArctosDB/arctos/assets/5720791/8df4841c-6aee-472c-b2e2-b80d36bdde59">



<img width="120" alt="Screenshot 2023-08-14 at 06 26 07" src="https://github.com/ArctosDB/arctos/assets/5720791/ac733416-b140-4556-8d2d-3b55c0008601">

<img width="486" alt="Screenshot 2023-08-14 at 06 26 12" src="https://github.com/ArctosDB/arctos/assets/5720791/639a1f14-6ce7-4c00-b71c-ca6ee48474ea">

or 

<img width="287" alt="Screenshot 2023-08-14 at 06 27 11" src="https://github.com/ArctosDB/arctos/assets/5720791/db5265fb-32df-412e-9aa7-288761059ba7">

to skip the 'use' click.
