### ISSUE TITLE
Smokey Hill Chalk Member change to Smoky Hill Chalk Member

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6626]
> "Smoky Hill Chalk Member" is the correct spelling. The macrostrat link provided for "Smokey Hill Chalk Member" spells it Smoky.

@dustymc can you just make this change in the code table?

**Comment by dustymc** [comment]
see https://github.com/ArctosDB/arctos/issues/6627#issuecomment-1678193549
