### ISSUE TITLE
Sonsela Sandstone Member change to Sonsela Member

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6627]
> Sonsela Member is now the accepted terminology, per the literature (and NPS preference). Sonsela Sandstone Bed was previously used to refer to the same packet of rocks when it was considered part of the Petrified Forest Member.

@dustymc can you make this change?

**Comment by dustymc** [comment]
Wouldn't be much of a constraint if I could get around them! Will need a CT request, then I can help update or there's an appropriate downloader/uploader.
