### ISSUE TITLE
cannot add operator; doesn't recognize email

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#6628]
# Error Text
<html><body>

ERROR_ID | BD0F4065-0541-4E56-9E8D5CB72CB5569A
-- | --
ERROR_TYPE | application
ERROR_MESSAGE | invalid user invitation - noemail
ERROR_DETAIL | A user that does not meet requirements was invited to become an operator.

</body>
</html>

# Where it happened
Trying to invite a user as an operator.
![image](https://github.com/ArctosDB/arctos/assets/93737929/2ab20699-41f7-4382-bf57-578eafcd644a)
I have our general collections email attached to her agent record so I can set up her account, but it's not registering. When I click on edit, then "invite as operator", I get the above error.

I have her login attached to her agent record. Is there anything else I'm missing?
![image](https://github.com/ArctosDB/arctos/assets/93737929/8ebc6844-4c81-41e8-91e1-3678975715f5)

**Comment by Jegelewicz** [comment]
She needs an email in her profile.

**Comment by wellerjes** [comment]
Whoops, thanks! I had added it to her agent record.
