### ISSUE TITLE
[external CONTACT] System stats has Genbank links = 0

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#6630]
@dustymc The system stats page for Arctos is currently showing 0 GenBank links:
https://arctos.database.museum/info/sysstats.cfm

Presumably this is because of changing how we deal with identifiers. We should be sure to update how the stats are generated to show the actual # GenBank links.

**Comment by dustymc** [comment]
The scripts were rebuilt, that just doesn't refresh itself very often. I kicked it off manually, should catch up in a couple hours.
