### ISSUE TITLE
Feature Request - Make the download page more useful

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6631]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

I feel confident that people searching and downloading data from search results are not getting everything they might be interested in (nor do they even know they are missing some things).

**Describe what you're trying to accomplish** 
_A clear and concise overview of the goals; why are you asking for this?_

Make it clear to anyone downloading from search results that they are only getting a form of "summary data" and that more details can be had with the use of other download tools.

**Describe the solution you'd like**
_How might we accomplish your goals?_

More explanation on the download terms page which currently looks like this

![image](https://github.com/ArctosDB/arctos/assets/5725767/980d492a-8a71-493b-bd98-cc50f89d18fe)

Text is

>These data are licensed by collection. Data are intended for use in education and research, and their use must follow the individual license and terms set by each collection as specified in the download file. If required, those wishing to include these data in analyses or reports must acknowledge the provenance of the original data and notify the appropriate curator prior to publication. These are secondary data, and their accuracy is not guaranteed. Please contact the individual collections with any data-related questions or to examine primary source material. Arctos collections and their staff are not responsible for loss or damages due to use of these data.

Perhaps add

> Data from search results is summarized and may be missing important metadata or ancillary information. For a more complete set of data, consider adding any of the detail download options for attributes, identifiers, or parts to get a more complete set of the data available.

We need to make the detail downloads available to the public if we do this...

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

Just let people remain blissfully unaware.

**Additional context**
_Add any other context or screenshots about the feature request here._

We also need a little cleanup here:
 - the color contrast of red an green is a poor choice for the text due to color blindness.
 - what the heck is "down_pg"after the download button?
 - I can almost guarantee that people are selecting "curatorial" even when that is NOT the purpose. This should make people pick, not give them a pre-filled selection (that is potentially wrong).

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._

**Comment by Jegelewicz** [comment]
Does anyone in the Ranges project care about this or should I close it?

@dbloom @bryansmclean @jebrad @cjconroy @jldunnum 

Sorry I am not remembering everyone here!

**Comment by cjconroy** [comment]
I haven't tried lately, but the bigger problem was that anything costly beyond a certain number of records were not returned, you had to download separately, and in a bizarre format. Has all that been resolved? Like, if we implement some of the things discussed today, will embryo count be a 50, or a 1?

**Comment by dustymc** [comment]
50 at the moment, but that's not sustainable. 

https://github.com/ArctosDB/arctos/issues/6922

It also loops back around to the whole 'value isn't the whole picture, metadata is super critical, why are we pretending that these are simple?" thing.

>bizarre format

I don't think including metadata is bizarre!

**Comment by dustymc** [comment]
Tabling for lack of input; please reopen if there are specific requests.
