### ISSUE TITLE
agent address cleanup help request

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6635]
**Is your feature request related to a problem? Please describe.**

Data in https://github.com/ArctosDB/arctos/issues/6634 contain

<img width="296" alt="Screenshot 2023-08-15 at 08 08 44" src="https://github.com/ArctosDB/arctos/assets/5720791/74924039-7df6-47be-905b-1de8044467c3">

**Describe what you're trying to accomplish** 

Prevent garbage

**Describe the solution you'd like**

Magic? I'm not sure how much of this is possible, it might be an exercise in futility.

**Describe alternatives you've considered**

Deal with some garbage (which can be used to justify agents that otherwise wouldn't need to exist - see https://github.com/ArctosDB/internal/issues/280 - so this could be critical-ish.)

**Additional context**

**Priority**

**Comment by Jegelewicz** [comment]
I can remove the NA's from the file, but I don't see how we can control phone numbers because of international numbers and the fact preferences for formatting will come and go.

I realize that this appears as "garbage" to you, but it is what an incoming collection has in their data and I simply CANNOT review every last thing (an neither can they). These agents all have A LOT of information, so one little bit of "garbage" is way beyond what I am worried about right now.

**Comment by dustymc** [comment]
The agent checker is now considering addresses, and nonsense on both ends causes, at best, very verbose checks. Not-so-best, these data in part exist to prevent duplicates and can't do that if they're not what they claim to be. I've added some rudimentary checks to the existing rules, and done so in a more modular manner which could be used for more than on-save validation.

Here are some data which could use help.

[temp_bad_address.csv.zip](https://github.com/ArctosDB/arctos/files/12353760/temp_bad_address.csv.zip)

**Comment by dustymc** [comment]
>is not an invalid address.

It's not a valid **wikidata** address.

**Comment by Jegelewicz** [comment]
Perhaps that is a more useful error for this then?

**Comment by Jegelewicz** [comment]
Also - one bit of quick cleanup that could be done in bulk is to change and type = Wikidata that isn't a Wikidata url to type = url.

**Comment by AJLinn** [comment]
>  type = Wikidata that isn't a Wikidata url to type = url.

Yeah, I apologize since i see a number of those erroneously listed Wikidatas were done by my former staff. I can take a stab at doing some of this cleanup today. Agent work is one of my favorite things to do!

**Comment by dustymc** [comment]
>more useful error 

I've now got this structured in a way that can support that, just let me know what you'd like to see.

>quick cleanup

Yep, I can update things that can be mass-updated.

**Comment by Jegelewicz** [comment]
When I se something to delete, it shouldn't have to match the type parameters.

**Comment by Jegelewicz** [comment]
I don't understand why the Library of Congress IDs are invalid.

**Comment by Jegelewicz** [comment]
It looks like the "extraneous characters have been mostly removed? I think that I have done all that I can if the Wikipedia stuff gets converted to url as requested.

**Comment by Jegelewicz** [comment]
>>  When I set something to delete, it shouldn't have to match the type parameters.

> Hu?

There were a few cases where the problematic address just needed to be deleted (it was a dupe). changing the type to delete will NOT delete the offending address until I change it to meet whatever format the original type was. DELETE shouldn't have any checks.

**Comment by Jegelewicz** [comment]
I also do not understand why Sandra L. Talbot is on this list.

**Comment by dustymc** [comment]
> DELETE shouldn't have any checks.

It doesn't (but an update from that form is doing a lot so ??) - a recipe would be most useful.

>John E. Cadle


The ``<>`` thing is used in a shipment, I'll have to use the scary password after hours.

>Sandra L. Talbot 

Someone fixed it?

**Comment by jldunnum** [comment]
Which list are you referring to? We work with her.

______________________________________________________________

Jonathan L. Dunnum Ph.D. (he, him, his)
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

Chair, Systematic Collections Committee, American Society of Mammalogists
Latin American Fellowship Committee, ASM

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by Jegelewicz** [comment]
@jldunnum the file that Dusty attached above with funky addresses. Apparently hers is fixed now, so nothing to do here.

**Comment by jldunnum** [comment]
OK thanks

______________________________________________________________

Jonathan L. Dunnum Ph.D. (he, him, his)
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

Chair, Systematic Collections Committee, American Society of Mammalogists
Latin American Fellowship Committee, ASM

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by dustymc** [comment]
I had to do something else so I fixed Cadle and trimmed what could be trimmed while I was in there. That leaves only these:

```
 agent_id | address_id | preferred_agent_name |    creator    |    editor     | address_type |             address             |               isvalidaddress               
----------+------------+----------------------+---------------+---------------+--------------+---------------------------------+--------------------------------------------
 21323829 |   10063359 | Edmond Buniet        | Phyllis Sharp | Phyllis Sharp | fax          | 96-43-30                        | Invalid address; please see documentation.
 21323829 |   10063358 | Edmond Buniet        | Phyllis Sharp | Phyllis Sharp | phone        | 96-42-89                        | Invalid address; please see documentation.
 21247311 |   10003644 | Susan Heckly         | unknown       |               | email        | susanheckly@wildlife_museum.org | Invalid email; please see documentation.
```

That email can't be real and should probably just be deleted - @ccicero help?

The other two MIGHT be real (in which case I need to update my validation) but I can't get anyone to answer so I suspect they aren't real either - @sharpphyl help?

**Comment by dustymc** [comment]
Moved nonsense data to internal remarks.
