### ISSUE TITLE
Feature Request - directory - tile view - eyeballs

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6637]
**Is your feature request related to a problem? Please describe.**

On the directory tile view, add a way to access documentation (eg, fontawesome eyeball toggle)

**Describe what you're trying to accomplish** 

Access to more information without the complexity of the table view

**Describe the solution you'd like**

^^

**Describe alternatives you've considered**
nope

**Additional context**
nope

**Priority**

**Comment by mkoo** [comment]
"book" for documentation works too
```https://fontawesome.com/icons/book?f=classic&s=solid```
