### ISSUE TITLE
reproject to WGS84 datum is not working

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#6643]
Currently:
Arctos reprojects coordinates from identified non-WGS84 datum to WGS84 in order to standardized coordinates and ensure stability when mapping in Arctos. If curatorial user does not know datum of coordintes, they can either assume it to be WGS84 (eg. from a GPS unit where the default is WGS84) or note it as verbatim coordinates as locality attributes but know that it will not be mapped in displays (they can always georeference later with Geolocate tool)

Problem: standalone coordinate converter is not correctly converting between datums
Not sure why but first noted here (https://github.com/ArctosDB/arctos/issues/4169). Probably the same for scripts running in background according to that issue

@dustymc when you've got time, lets run some tests-- hopefully easy PG fix?

**Comment by dustymc** [comment]
>run some tests

Sure - send me coordinates and datum (csv is always nice) and I'll run the converter in debug mode.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
The issue that I was noting in #4169 is when Arctos standardized to WGS84, coordinates were supposed to be converted, but per examples I posted in that issue, they were not actually converted.

**Comment by dustymc** [comment]
>examples

Ah thanks @Nicole-Ridgwell-NMMNHS, here's that one running in debug mode.

```


select convertRawCoords('{
    "debug":"true",
    "orig_lat_long_units":"decimal degrees",
    "dec_lat":"36.12536",
    "dec_long":"-107.2204214",
    "datum":"North American Datum 1927"
}'::json)::text ;


NOTICE:  DEBUG is on: t
NOTICE:  raw input: {
    "debug":"true",
    "orig_lat_long_units":"decimal degrees",
    "dec_lat":"36.12536",
    "dec_long":"-107.2204214",
    "datum":"North American Datum 1927"
}
NOTICE:  orig_lat_long_units: decimal degrees
NOTICE:  ---------------------------------------------------------------------------------
NOTICE:  At this point we should have coordinates transformed to DD.ddd format, and a datum
NOTICE:  noconvlat is not null and noconvlong is not null - we can proceed
NOTICE:  noconvlat: 36.12536
NOTICE:  noconvlong: -107.2204214
NOTICE:  v_datum: North American Datum 1927
NOTICE:  datum_srid: 4267
NOTICE:  wgs84: 4326
NOTICE:  Operation: 
            SELECT 
                ST_Transform(
                    ST_SetSrid(
                        ST_MakePoint(
                            noconvlong,
                            noconvlat
                        ),
                        datum_srid
                    ), 
                    wgs84
                )
NOTICE:  Evaluated: 
                SELECT 
                    ST_X(geom), 
                    ST_Y(geom) 
                from (
                    select
                        ST_Transform(
                            ST_SetSrid(
                                ST_MakePoint(
                                    -107.2204214,
                                    36.12536
                                ),
                                4267
                            ), 
                            4326
                        ) as geom
                ) g
                         convertrawcoords                          
-------------------------------------------------------------------
 {"lat":36.12538827808947,"lng":-107.22102918614863,"status":"OK"}
(1 row)


```

and the function is https://github.com/ArctosDB/PG_DDL/blob/master/function/convertRawCoords.sql, in case I've somehow mangled the debug-bits.

**Comment by mkoo** [comment]
Thanks, all. I tried out a few XY's and that function matches the GIS output on my workstation. So in @Nicole-Ridgwell-NMMNHS example (above values and here https://arctos.database.museum/info/localityArchive.cfm?locality_id=11108210) it does look like the coordinates did not convert to WGS 84 -- they are the same as the original dd. So can you @dustymc rerun this locality with the function to see if it will convert? Maybe it's not the SQL but something else in the implementation

**Comment by mkoo** [comment]
addressed
