### ISSUE TITLE
Code Table Request - New Identification Attribute for Common Names

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#6644]
### Goal
1) To document common name outside of ID Remarks and without tying common names to taxonomy
If the common name is embedded in the metadata ([like in AOU](https://github.com/ArctosDB/arctos/issues/6311)), then it runs the risk of being overwritten if the taxonomy changes.

2) Increase accessibility of collections for non-scientific users
To make it easier for museum volunteers and staff to find specimens, particularly in the teaching collections.

### Context
Identification attributes are a new feature and this will get some information out of ID remarks.

### Table
**https://arctos.database.museum/info/ctDocumentation.cfm?table=ctidentification_attribute_code_tables**

### Proposed Value
main attribute: "common name"

### Proposed Definition
a non-scientific (or non-taxonomic) name used to refer to a specimen or object; note that these names vary geographically and culturally

### Collection type
All

#### Attribute data type
free-text
Discussed during the @ArctosDB/diversity-and-inclusion meeting. While this opens up the possibility of alternate/misspellings/capitalizations, managing a code table of all the common names is going to be overwhelming and unwieldy; we'd like to start with free text and evaluate how it is used.

#### Attribute controlled values
- "preferred" (by the collection; this takes into account regional differences);
- "historic" (provides the opportunity to capture outdated/problematic common names);
- verbatim (captures what's on a tag; sometimes the common name is the only name provided on old labels and ledgers and we, as collections managers, are assigning taxonomic names based on the available common name)

#### Attribute units
n/a

### Priority
Normal; will help resolve or advance some other issues, especially within @ArctosDB/diversity-and-inclusion 

### Example Data
n/a

### Available for Public View
yes

@ArctosDB/arctos-code-table-administrators 

## Approval
_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [ ] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [ ] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection
_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation
_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

- [ ] Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

- [ ] Add or revise the code table term/definition as described above. Ensure the URL of this Issue is included in the definition.

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by Jegelewicz** [comment]
@wellerjes you cannot have any controlled values in a free-text attribute.

If you want to distinguish between

> "preferred" (by the collection; this takes into account regional differences);
> "historic" (provides the opportunity to capture outdated/problematic common names);
>  verbatim (captures what's on a tag; sometimes the common name is the only name provided on old labels and ledgers and we, as collections managers, are assigning taxonomic names based on the available common name)

Then I think you will need three different identification attributes.

**Comment by dustymc** [comment]
I don't think any of this makes sense to me.

>runs the risk of being overwritten if the taxonomy changes

Why in the world would you use ANY classification for which that's a concern? Sure, it could happen in the big legacy messes, but I don't think anyone using them can much care about curating taxonomy.

>Increase accessibility of collections 

I think this is just simple denormalization - some TaxonA are findable (but not in the expected way) by someCommonName and some are not - in which case the opposite result is near inevitable (and everyone encountering that situation will assume it's because Arctos is poorly designed).

>easier for museum volunteers and staff to find specimens

I would think that "common names" (broadest possible interpretation) exist mostly for discovery, yes - but this proposal is to put them somewhere outside of that path!

>names vary geographically and culturally

Yep, some call it Albacore, some Cá bò vang, it's the same population/circumscription/taxon, https://arctos.database.museum/name/Thunnus%20albacares. (But "Iron" in your collection might only refer to https://arctos.database.museum/name/Iron#NomenclatureviaArctos, not all of https://arctos.database.museum/name/Iron, which suggests a clear path for this information.)

>managing a code table of all the common names 

?!

**Comment by ewommack** [comment]
> runs the risk of being overwritten if the taxonomy changes

This comes from the fact that we want to be able to keep that data somewhere accessible. So the name changes over time, but we have a record of the original name it was given somewhere. When the AOS updates their common names, they rewrite the old ones in the taxonomy.

> managing a code table of all the common names

We thought this would just create a horrendous mess. I have an entire book with past common names of NAmerican birds, and it is already out of date. 
We know a free text field will lead to misspellings and potential problems, but given the alternative we wanted to trial it free text first to see if it would be better than the potential expanding beast of a code table of common names.

**Comment by dustymc** [comment]
>So the name changes over time, but we have a record of the original name it was given somewhere. 

Identifications (the link of names to records) change only if they're changed - there's no automation or anything like that, changes are entirely at the discretion of the Curator. (And FWIW I would near-never change anything - even if it's just a big pile of mistakes, historical data has a way of being useful and Arctos has a mechanism for keeping it around without letting it get in the way.)

>When the AOS updates their common names,

If tracking some particular bit of metadata regarding a name (common names, family, WHATEVER) is important to the collection, then using a Source over which they don't have control would be a horrible idea. (And that is just about 100% of why https://github.com/ArctosDB/arctos/discussions/4965 is still being discussed - someone using a remote classification needs to really understand this, and I've never been sure if that's the case or if we're flirting with disaster.)

>    code table of all the common names  ... would just create a horrendous mess. 

That is definitely true, but I'm not sure why it was brought up. (That is, I think someone isn't understanding something, I'm trying to figure out who and/or what that might involve.)

>given the alternative 

I think you mean something other than managing these data as what they clearly are, metadata of a "taxon concept," alongside all similar data??

**Comment by Jegelewicz** [comment]
Identifications may never change, but CLASSIFICATIONS change all the time. Storing a common name name there means it can be lost when a classification is edited.

EVERYONE is using a source over which they have no control because NO ONE has the ability to maintain one on their own!

> metadata of a "taxon concept," alongside all similar data??

NO - CHAS has very specific common names that their staff and volunteers use to locate things in the collection. CHAS does NOT want to maintain an entire taxonomic backbone just so they can facilitate that.

**Comment by dustymc** [comment]
>CLASSIFICATIONS change all the time

I think that's always been "only if you want them to" but that's now formalized with https://github.com/ArctosDB/arctos/issues/6671

>use to locate things in the collection

That information could only be appropriate in https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecpart_attribute_type#location ?!

>CHAS does NOT want to maintain an entire taxonomic backbone just so they can facilitate that.

OK?

This request will clearly fit in the model and if there's some use case I'm not understanding or whatever I'll check the boxes, but this still looks like a nightmare in the making from here: a lot of unnecessary work leading to inconsistent data still looks like the only possible outcome.

Can we try Zoom to get on the same page?

**Comment by wellerjes** [comment]
> a lot of unnecessary work leading to inconsistent data still looks like the only possible outcome

My common name request primarily came about as a way to clean up identification remarks (see https://github.com/ArctosDB/arctos/issues/4922#issuecomment-1240839750). If we can continue to record our preferred common names in identification remarks, then I will let go preferred common name attribute.

> information could only be appropriate in [attribute location]

We use the common name on the labels for a variety of reasons; in addition to helping locate a specimen when we don't know its scientific name off the top of our heads, it's beneficial to have it visible during public engagement events and collections tours, and in other situations when we don't have Arctos readily available to reference.

I propose moving forward with an [attribute in this table](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctidentification_attribute_code_tables) called "verbatim identification", defined as "scientific or common name as it appears on the original record." This would allow us to capture what is on the tag/ledger/etc. and document in remarks if it is a historic/problematic name. We also get a lot of salvage specimens brought to the museum that are only identified by their common name and it would provide a place to record that information as well.

**Comment by dustymc** [comment]
> continue to record our preferred common names in identification remarks

I'm still baffled and would like to talk about this!

>verbatim identification

That's exactly ``A {string}`` [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxa_formula#a__string_) (but without the functionality) no?

**Comment by campmlc** [comment]
So just to clarify my own understanding of this:
1) Currently if I want to search on "grizzly bear" using Any Taxon, ID, or Common Name - I can do so, because "grizzly bear" is a common name associated with the taxon name "Ursus arctos", correct? 
2) If I search on "duck" I get both birds and fish, since this common name is used in different contexts. This should be expected.
3) So in order for common names to be used in searches, they need to be associated with taxon names. And anyone searching on these names will likely get way more than they expect because common names are shared widely.
4) But, @dustymc is saying this functionality is going away from our current search interface? Please explain?

Regardless, an alternative to allow records to be searchable by common name would be to add a second identification using A {string}, correct? 
So ID 1 would be "Ursus arctos" and ID 2 would be "Grizzly Bear"? How would a search for grizzly bear work in this case? and how would these display in the Search results?

**Comment by dustymc** [comment]
(1) yes
(2) probably
(3) that's one way
(4) There's limited utility with the current setup - there's no possible way to associate "a bug" with https://arctos.database.museum/name/Iron#Arctos (a bug) and not with https://arctos.database.museum/name/Iron#OpenTreeofLifeReferenceTaxonomy (a plant) - "common_name" is keyed to https://arctos.database.museum/name/Iron. Associating an item in a collection with a specific common name, or searching for things like...

<img width="739" alt="Screenshot 2023-09-07 at 16 23 21" src="https://github.com/ArctosDB/arctos/assets/5720791/7eac7642-2c6c-447a-9e78-9232c653ac38">

 ... requires something like https://arctos-test.tacc.utexas.edu/name/Iron#HeysCIMviaArctos. I don't have any plans to preemptively kill anything, but it seems that there are use cases which can't be met by the current structure (which was meant to be temporary from the beginning).

> records to be searchable by common name would be to add a second identification using A {string}

Uhh - sorta?? If Rausch wrote "P. J." and you want someone to find records to which that identification has been applied by that identification, then yes. (And https://github.com/ArctosDB/arctos/issues/4827 cannot be an alternative to that - which everyone fully understands, right?!)

>and ID 2 would be "Grizzly Bear"?

If you mean a specific record identified in that way, sure, same as above. If you mean as a way to find eg https://arctos.database.museum/name/Ursus%20arctos then it's just denormalization - there's 0% chance you'll do this consistently (but you can put a tremendous amount of effort into the attempt!), it will be anti-useful (it will actively discourage discovery), and people will (perhaps rightly) see it as evidence that Arctos is broken.

>How would a search for grizzly bear work in this case?

There are a great number of possibilities, I think the documentation is pretty good, and if you have something specific I can set it up in test.

**Comment by wellerjes** [comment]
closing; since this is a CHAS-specific issue, we are going to address this internally
