### ISSUE TITLE
[external CONTACT] issued_by 'collector'

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#6646]
@dustymc This is an extension of issue # [6469](https://github.com/ArctosDB/arctos/issues/6469) for MVZ records:

If agent role = 'collector' AND 
if there is only one such agent for a record AND
if identifier type = 'collector number'

THEN

insert collector agent name into 'issued by' for the collector number.

This applies to legacy data. New records should be done as such in data entry or bulkloader.

Copying MVZ staff curators @mkoo @atrox10 @cjconroy @libbybeckman

**Comment by dustymc** [comment]
Please review this and let me know if it's what you asked for.

[temp_mvz_all_collector.csv.zip](https://github.com/ArctosDB/arctos/files/12354077/temp_mvz_all_collector.csv.zip)

**Comment by ccicero** [comment]
@dustymc I did some spot checking and this CSV looks good to me.  Thanks!

**Comment by dustymc** [comment]
The direct update was getting unstable without completing so I pushed these to the [component loader](https://arctos.database.museum/loaders/bulk_identifier_issuedby.cfm). They're running now, should complete in a few days.

**Comment by dustymc** [comment]
This has completed, just open a new issue if we need another pass.
