### ISSUE TITLE
[external CONTACT] issued_by preparator

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#6647]
@dustymc This is an extension of issue # [6469](https://github.com/ArctosDB/arctos/issues/6469) for MVZ records:

If agent role = 'preparator' AND 
if there is only one such agent for a record AND
if identifier type = 'preparator number'

THEN

insert preparator agent name into 'issued by' for the preparator number.

This applies to legacy data. New records should be done as such in data entry or bulkloader.

Copying MVZ staff curators @mkoo @atrox10 @cjconroy @libbybeckman

**Comment by dustymc** [comment]
Let me know if this is them.

[temp_mvz_all_preparator.csv.zip](https://github.com/ArctosDB/arctos/files/12354102/temp_mvz_all_preparator.csv.zip)

**Comment by ccicero** [comment]
@dustymc I checked a few of these and it looks good to me.

**Comment by dustymc** [comment]
Also pushed to the [component loader](https://arctos.database.museum/loaders/bulk_identifier_issuedby.cfm).

**Comment by dustymc** [comment]
This has completed, just open a new issue if we need another pass.
