### ISSUE TITLE
DMNS Marine Invert: Arctos Report Help Request

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#6653]
I'm working on the 'DMNS Marine Invert_test' report for our labels and could use some SQL help. 
We would like to display the Family on the label. For specimens with multiple identifications, Family in FLAT is a concatenation of family from each of the identifications so just using flat.family results in things like: "Camaenidae; Camaenidae". How can we pull the Family name (or any higher level rank) from just the preferred identification (ID order=1)? see [DMNS:Inv:30008](https://arctos.database.museum/guid/DMNS:Inv:30008) as example.
Any help would be appreciated.

**Comment by acdoll** [comment]
That seems simple enough and would work for most of our cases; however, the concatenated values in these fields appear to ordered alphabetically and thus, for the cases where the families differ, this only works when the preferred term (ID order=1) also comes first alphabetically.  Here's a case where that will fail to get the correct value:
<html>
<body>


select cat_num as catlog, family as originalfamily, split_part(family,';',1) as family from flat where guid='DMNS:Inv:39310'
--
  | catlog | originalfamily | family
1 | 39310 | Lottiidae; Acmaeidae | Lottiidae


</body>
</html>

**Comment by acdoll** [comment]
That seems simple enough and would work for most of our cases; however, I can't tell how the concatenated values in these fields are ordered (I though it was alphabetically but after further review that is not the case). So, for the cases where the families differ, this only works when the preferred term (ID order=1) also comes first in that field. Here's a couple of cases where that will fail to get the correct value:
<html>
<body>


SQL:select cat_num as catlog, family as originalfamily, split_part(family,';',1) as family from flat where guid='DMNS:Inv:36936' OR guid='DMNS:Inv:36742'
--
  | catlog | originalfamily | family
1 | 36742 | Trochidae; Tegulidae | Trochidae
2 | 36936 | Ovulidae; Pediculariidae | Ovulidae


</body>
</html>

**Comment by dustymc** [comment]
I will try to order those for next release, but I'm not sure it'll carry all the way through and don't have a convenient (and affordable) way to make that explicit.

I'll grab a copy of the report, deserialize identifications, and probably ping you for help when I get lost in whatever that is you're doing with family in the sql....

**Comment by acdoll** [comment]
Thanks. I simplified what was in our sql for the family - the old version was just appending an indicator of subfamily (due to perceived space limitation) for when the family is Muricidae. Now it just displays the entire subfamily when appropriate.

**Comment by acdoll** [comment]
This is great! It looks more like what I had in mind (it also fixes the same issue for the identifier and ID remarks which I was ignoring). Thank you so much! I don't think we should have an issue with multiple ID order=1 except for cases of data entry error. I copied this into our reporter and it seem to be working!

Now my only issue is getting a page break every four rows for printing purposes. I believe @mkoo suggested she or @lkvoong has found a solution for that.

**Comment by mkoo** [comment]
Yes, it's a CSS thing.
When you initiate your cell environment, add ```page-break-inside: avoid```

so the whole thing may look like:
```.cell {
  padding: 1px;
  width: 41mm;
  max-width: 41mm;
  border: 1px black dashed;
  page-break-inside: avoid;
  font-family: "Times New Roman", serif;
  font-size: 11px;
  display: flex;
  flex-direction: column;
  overflow: hidden;
}
```
this should be the label's div class
I forgot to add to the cheatsheet so will do so today!

**Comment by acdoll** [comment]
Either this is not quite what I'm looking for or I'm not doing it right. I have a div class 'page' that is supposed to be a 4 x 4 grid of labels for each printed page, but it seems to just keep adding rows; is there something in the CFM that I'm missing? Do I need some kind of loop to create a new page after 16 labels (4 rows), but continues through the query loop? Does that make any sense?

**Comment by mkoo** [comment]
let me take a look... happy to zoom later too so expect an email from me

**Comment by acdoll** [comment]
That would be great. Thanks

**Comment by mkoo** [comment]
check your email!

**Comment by acdoll** [comment]
Thank you both - it's working like a charm now. Well, at least for me (and Genna). Phyllis was getting this error, but we could not recreate it:
**ERROR: column reference "individualcount" is ambiguous Position: 58**
![image](https://github.com/ArctosDB/arctos/assets/12507297/77a38b8d-84fa-4473-837f-860522804523)
Any thoughts on that @dustymc

**Comment by dustymc** [comment]
>reference "individualcount" is ambiguous

I'm not sue which label you're working on so I didn't change anything, but she'll have it turned on in ``#table_name#`` - just change ``individualcount as count,`` to ``flat.individualcount as count,`` and it should worrk.

**Comment by acdoll** [comment]
That fixed the problem - thank @dustymc. I was hoping to close this, but we discovered today that some of the Family names are coming up blank for no apparent reason (that I can see). E.g. https://arctos.database.museum/search.cfm?guid_prefix=DMNS%3AInv&cat_num=35524-35525
![image](https://github.com/ArctosDB/arctos/assets/12507297/6861fdd3-de4a-449c-875b-1054b287b8a2)
Both of these should display FAM: Caecidae
Any thoughts?

**Comment by dustymc** [comment]
What report?

**Comment by acdoll** [comment]
DMNS Marine Invert

**Comment by dustymc** [comment]
Derp...

I added the stuff under comment 					
```
<!--- check to see if these exist before trying to access them ---->
```
<img width="373" alt="Screenshot 2023-08-24 at 07 25 29" src="https://github.com/ArctosDB/arctos/assets/5720791/3a89bccb-e75d-4e4b-be14-a722fac9b8d1">

**Comment by acdoll** [comment]
Thanks @dustymc!
