### ISSUE TITLE
Need Help with Arctos Error

### ISSUE THREAD

**Issue by AdrienneRaniszewski** [ArctosDB/arctos#6655]
# Error Text
2023-8-17T9:6:33: FAIL: query string argument of EXECUTE is null22004: {"message":"query string argument of EXECUTE is null22004","status":"fail"}

# Where it happened
in create record screen https://arctos.database.museum/Bulkloader/enter.cfm?guid_prefix=MSB:Mamm

# Steps to get there
created new profile (MSB:Mamm 2023.053 Panama)
entered data
clicked "create record"
got the red screen and the above error message

I checked for mistakes in the data and made adjustments to the profile. over and over and over again. keep getting the same error. no idea what it means or how to fix it

**Comment by dustymc** [comment]
Nope, I made that record from your profile, even had a failure which produced an expected error.

<img width="1611" alt="Screenshot 2023-08-17 at 08 44 48" src="https://github.com/ArctosDB/arctos/assets/5720791/b68fac4a-dae7-4186-bef8-51546b4296e8">

I'm not sure it's possible to set up a profile that can't save, and you should get a helpful error if you do. It's certainly possible to set up a profile that'll mangle data, but I can't see any way that might lead here.

**Comment by dustymc** [comment]
Yes it was in the data - part attributes that need units and have incomplete data, when there's a comma in the part name, was somehow bypassing error handling. (Test was doing something slightly different, something about database versions I think.) Not QUITE mystical, still closer than I like to get. Please don't break anything ever again! (Err, uhh, uncover the stuff I broke....)

**Comment by AdrienneRaniszewski** [comment]
it worked!! hooray! thanks, so much, Dusty
