### ISSUE TITLE
Imploding object hierarchy

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#6656]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
The containers are trying to contain themselves infinitely and imploding???

**To Reproduce**
...no idea
Everything in UTEPE6058 seems to be doing that where the herbarium folder is trying to contain the herbarium sheet UTEPE6049, but is contained in the subsequent child sheets simultaneosuly

**Expected behavior**
For it to not be possible for that to happen - throw error if it tries to get to this coniditon.

**Screenshots**
![image](https://github.com/ArctosDB/arctos/assets/38706617/b1eb88cd-00d5-445b-9f41-28aebbc99e3d)
**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**
Chrome 

**Additional context**
I don't know what i did, but something scanned wrong a couple of years ago. Any possibility in preventing this from happening again? My plan is to delete these containers and recreate them. Arctos just freezes if i try to access the container. Hopefully, it hasn't happened elsewhere...

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by dustymc** [comment]
I moved one:

```
arctosprod@arctos>> select barcode,container_type,container_id,parent_container_id from container where barcode in ('UTEPE6058','UTEPE6049');
  barcode  |  container_type  | container_id | parent_container_id 
-----------+------------------+--------------+---------------------
 UTEPE6049 | folder           |     21100646 |            21100655
 UTEPE6058 | herbarium folder |     21100655 |            21100646
(2 rows)

Time: 1.110 ms
arctosprod@arctos>> update container set parent_container_id=0 where container_id=21100655;
```

This is one of the places where postgres is just primitive compared to Oracle, and I haven't figured out how to prevent this without melting something even more interesting. I do limit recursion so it shouldn't suck up all the electrons in the universe or anything, but it's still possible to make things pretty weird. Maybe next version will have better magic....

**Comment by mvzhuang** [comment]
Thanks Dusty. Can you see  how it happened from your end ? Like did i mistakenly edit something outside of the container move app? or try put the folder into the specimens instead of the other way around?

**Comment by dustymc** [comment]
You can check history (blue button in the tree detail panel and top of edit container) - looks like an 'oops' to me, I think those are inevitable if you scan enough, meh, whatever, that's why we have history. This has also happened when there are misprinted barcodes (eg multiple things that scan the same) involved, and that's definitely reason to panic - might be worth doublechecking if convenient, but I think those usually make themselves more obvious than this is.
