### ISSUE TITLE
MVZ Agent Cleanup Request

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6657]
From eg https://github.com/ArctosDB/arctos/issues/6646 I noticed eg https://arctos.database.museum/agent/10001024 - a low-information agent. I'm guessing most anyone who has field notes at MVZ has probably done other stuff, and MVZ probably knows something about them. At some point we will (I hope) verbatimize agents without any independent data, this might be a good opportunity to add some of that to some important agents (who probably aren't getting proper attribution without).

I made https://docs.google.com/spreadsheets/d/1REIjxB9ay4rU6yOpT8iRo2LsFuiPlfyFc9cF0JDpfmQ/edit?usp=sharing, which is agents who's issued identifiers to MVZ records (including those still cooking in the component loader). Let me know if you need different data, edit access, or anything else I might be able to help with.

It contains unknown and genbank and such, those can just be ignored or deleted - I didn't clean anything up because I suspect there are duplicates in here. (Because there are duplicates everywhere low-information data appears, not because I saw any....)

Anything with nothing in has_data needs help - 1329 of 2242 agents involved in this have no non-string information.

Help?

@ccicero @cjconroy @atrox10 @mkoo

**Comment by mkoo** [comment]
Thanks, I have a student who has been working with these agents all
summer-- we've been adding bios, obit info, birth/ death dates, etc. (it
was a lot longer list a few weeks ago!) She's on a bit of a sabbatical this
week as semester is starting up. We can cross reference that file with
ours, but we have been prioritizing those with a lot of material in our
archives first. Likely your list has some that we missed too!

**Comment by mkoo** [comment]
also fixed up JE Simpson since it was right THERE! and bugged me so much I
couldnt close the tab...

**Comment by mkoo** [comment]
This is a stale issue that has been mostly resolved
