### ISSUE TITLE
bulkload citations help

### ISSUE THREAD

**Issue by amgunderson** [ArctosDB/arctos#6659]
Bulkloading citations requires a GUID, DOI, and type status, but I get a not enough information error when attempting to load the csv. I suspect it needs a "use identification ID". There used to be a field for using the existing identification which could be filled with "TRUE" to use the current accepted ID. I have no way of generating a list of "identification IDs". Do I have to copy an paste 52 (in this instance) individual identification ID urls to fill in the bulkload citations form? That would require me to open every specimen record and copy the link to each specimen ID. please help

**Comment by dustymc** [comment]
You can find the records then...

<img width="430" alt="Screenshot 2023-08-17 at 10 53 45" src="https://github.com/ArctosDB/arctos/assets/5720791/9771e15f-1a9c-427c-8002-04d903c28ea7">

... which will give you a CSV with USE_IDENTIFICATION_ID.

If that doesn't work let me know what might.

**Comment by amgunderson** [comment]
Sweet, that should do it, thanks
