### ISSUE TITLE
Agent Merge Request - Loye Holmes Miller

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6660]
ref: https://github.com/ArctosDB/arctos/issues/6657

**Agent that should remain after the merge**
This agent should represent the same person or organization as the agent below, but be of higher quality (more complete name, or includes additional information such as dates, relationships, addresses). Navigate to the agent page, copy the url and paste it below:

https://arctos.database.museum/agents.cfm?agent_id=10008319

**Agent that will no longer remain after the merge**
This agent should be of lower quality than the agent into which it will be merged. Navigate to the agent page, copy the url and paste it below:

https://arctos.database.museum/agents.cfm?agent_id=10002026

**Reason for merge**
Please provide the reason you believe that these two agents represent the same person or organization.

Relatively sure these are the same person, a bunch of info has been added to the not-great-name version, would be useful if someone could verify it and move whatever's correct over before merging.

Please add this issue to the Agents Project

@ArctosDB/agents-committee

**Comment by mkoo** [comment]
Seems the two agents should be reversed since the entry https://arctos.database.museum/agents.cfm?agent_id=10002026 has more info than the other one. Maybe just a copy/paste error here?!

thanks for merging.
