### ISSUE TITLE
Feature Request - Part order on ~~record~~ edit page

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#6661]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
When I'm looking at a record with a lot of parts, they're listed in the order they were added which can be confusing.

**Describe what you're trying to accomplish** 
Manually order parts on the catalog record.

**Describe the solution you'd like**
Drag to order (and if you drag a part with a child, the child should go with it)

**Describe alternatives you've considered**
Continue to use as is. Sort alphabetically by part name.

**Additional context**
See https://arctos.database.museum/guid/NMMNH:Paleo:21094 as an example of a record that could be improved by ordering the parts.

**Comment by Jegelewicz** [comment]
Parentage should definitely get used!

After that, I think sorting alphabetically by part name (so sort the "parent" parts by name) would at least make the order more relatable?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> sorting alphabetically by part name (so sort the "parent" parts by name) would at least make the order more relatable?

This would be a great improvement over the current sort. As you can see from the example I linked, using parentage can only get so far.

**Comment by dustymc** [comment]
PG14 introduced some new magic (still ain't Oracle...) so sorting by part name may be possible now - needs lots more experimentation but I'll go direct for that much.

**Comment by dustymc** [comment]
Test should be sorting, testing greatly appreciated.

@Nicole-Ridgwell-NMMNHS assuming the sort is working, please close if this does what you need or go back to 'needs discussion' if you still want more control.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
The sorting on the record page looks good! Is it possible to also have that alphabetical sorting on the edit parts page?

**Comment by dustymc** [comment]
>sorting on the edit parts page

Sure, assuming the detail view is working as it should. I'll go back direct for that.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks!
