### ISSUE TITLE
Arctos Down - Friday, September 1 for database upgrade

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6666]
## Planned Outage
 - Date and time outage will begin: Friday, September 1, 9AM Central
 - Date and time outage is expected to end: Friday, September 1, 5PM Central
 - Reason for outage: Database upgrade
 - Expected behavior during and after the outage: https://arctos.database.museum/ will be unavailable

## Communication before/during outage
- [x] Pin this issue
- [x] Banner updated @jegelewicz @mkoo
- [x] Email sent to AWG  
- [x] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [x] Unpin this issue
- [x] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by Jegelewicz** [comment]
Proposed banner (after the current one expires this weekend):

Arctos will not be available on Friday, September 1, 2023 from 9AM until 5PM Central Daylight Savings time as we complete a database upgrade.

**Comment by mkoo** [comment]
I would add after that sentence:
"Please save your work and sorry for any inconvenience!"
thanks!

**Comment by ewommack** [comment]
Have emails sending out on Friday 25th (week before) and Thursday the 31st of August.

**Comment by dustymc** [comment]
Arctos is up and seems to be stable. Please let me know if you discover any problems.
