### ISSUE TITLE
Cannot download search results

### ISSUE THREAD

**Issue by jebrad** [ArctosDB/arctos#6668]
Hello,
After I get search results, the Download in the [Tools] pull-down menu is grayed out and cannot be selected. See attached.  

This happens while logged in with Safari and Chrome.  Seems glitchy, but I cannot rule out user error.  Please advise!

Thanks, Jeff

<img width="601" alt="Screen Shot 2023-08-18 at 11 54 41 PM" src="https://github.com/ArctosDB/arctos/assets/62565118/df3ee745-96e6-473b-b965-bf75b20f1241">

**Comment by dustymc** [comment]
done?
