### ISSUE TITLE
Missing Family on one record - why?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6670]
I am trying to ensure that classifications are in Arctos for a dataset. I don't understand why this one record doesn't include a Family (even though it clearly has one per the record page).

![image](https://github.com/ArctosDB/arctos/assets/5725767/1b891bc6-2848-448c-abaa-e679b6710220)

![image](https://github.com/ArctosDB/arctos/assets/5725767/73fb7dd3-351e-4e4e-9ead-5452fae45c60)

**Comment by Jegelewicz** [comment]
Note that this means that the results of a search for Family=Sciuridae in ASUMZ:Mamm excludes this record, which is a shame.

**Comment by dustymc** [comment]
Bug fixed, everything should catch up in a week or so, or you can request specific things be prioritized.

>esults of a search for Family=Sciuridae in ASUMZ:Mamm 

.... relies on the intersection of a bunch of completely opaque administrative stuff and a probably-inconsistent classification. That's probably OK for "us" - we'll notice problems and end up here - but really no 'researcher' should be using that stuff, and I'd remove it from the UI if I could.

**Comment by jldunnum** [comment]
Not that this is the problem but just glancing through whats in the list above I see a number misspelled taxa. 
Cavia tschudii
Zapus hudsonius
Tupaia glis

**Comment by DerekSikes** [comment]
UAM:Ento is still missing classification higher taxonomy for >90% of the records (95% missing in the attached query for 510 records from spec_loc 'Kodiak'  - this is interfering with work in many ways (not to mention the damage to public perception if their queries fail). At this rate, 5% restored in 4 days, it will take 80 days to restore our higher taxonomy which is unacceptable. Can this be  vastly accelerated? 
[catalog_record_summary(45).csv](https://github.com/ArctosDB/arctos/files/12440930/catalog_record_summary.45.csv)

**Comment by dustymc** [comment]
UAM:Ento refresh has been prioritized

**Comment by Jegelewicz** [comment]
This has been completed? Closing
