### ISSUE TITLE
Download Flat Attributes (locality search) gone!?

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#6673]
This function has disappeared. I use it all the time for pulling locality reports for curators, mitigation companies, and land managers. Unless someone knows some excel magic for recreating it from download attributes, I need it back or a viable alternative by the end of the week.

**Comment by Jegelewicz** [comment]
@Nicole-Ridgwell-NMMNHS where was it found before?

**Comment by Jegelewicz** [comment]
Is this not it?

![image](https://github.com/ArctosDB/arctos/assets/5725767/581d7227-9db6-4e49-a89c-5bce04e5c4ed)

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Ok, so I figured out that it disappeared because I removed locality attributes from search results.
