### ISSUE TITLE
Agent Merge Request - J. T. Noyakuk

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6675]
Use this template when you discover two agents that you believe represent the same person or organization.

**Agent that should remain after the merge**
This agent should represent the same person or organization as the agent below, but be of higher quality (more complete name, or includes additional information such as dates, relationships, addresses). Navigate to the agent page, copy the url and paste it below:

unknown

**Agent that will no longer remain after the merge**
This agent should be of lower quality than the agent into which it will be merged. Navigate to the agent page, copy the url and paste it below:

https://arctos.database.museum/agent/21349915

**Reason for merge**
Please provide the reason you believe that these two agents represent the same person or organization.

low-data agents should not exist

Please add this issue to the Agents Project

@ArctosDB/agents-committee

@AJLinn

**Comment by AJLinn** [comment]
Confirmed no additional biographical information able to be located for this agent. Moved to verbatim agent in record.
