### ISSUE TITLE
Agent Merge Request - Velero

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6679]
Use this template when you discover two agents that you believe represent the same person or organization.

**Agent that should remain after the merge**
This agent should represent the same person or organization as the agent below, but be of higher quality (more complete name, or includes additional information such as dates, relationships, addresses). Navigate to the agent page, copy the url and paste it below:

unknown

**Agent that will no longer remain after the merge**
This agent should be of lower quality than the agent into which it will be merged. Navigate to the agent page, copy the url and paste it below:

ridabrams just force-created agent [Velero](https://arctos.database.museum/agents.cfm?agent_id=21349936).

That's probably a bad idea.

**Reason for merge**
Please provide the reason you believe that these two agents represent the same person or organization.

no-data agents should not exist

Please add this issue to the Agents Project

@ArctosDB/agents-committee
@mkoo

**Comment by mkoo** [comment]
well she did add an associate of relationship and both agents have issued identifiers now so I would say a little better than no-data. They are legacy so if we figure out their names in time we will update!

**Comment by dustymc** [comment]
> associate of 

I would like to remove that relationship. This is doing nothing a verbatim agent can't do, except preventing us from being able to accurately reflect the names our collaborators would like us to use.

@ArctosDB/agents-committee

**Comment by mkoo** [comment]
Well that's a separate issue... which I'm not opposed to since it's pretty vague but more importantly very sporadically applied to be quite useless honestly!
