### ISSUE TITLE
SpecimenResults: large/long fields

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ArctosDB/arctos#668]
```
from ABJ: verbose remarks=ugly

Solutions: 

1) Put all data in styled div - funky, likely performance problems
2) Explore jquery grid, etc. as a replacement for the table
```

Original issue reported on code.google.com by `dust...@gmail.com` on 19 Nov 2013 at 5:58

**Comment by dustymc** [comment]
Now using jquery.jtables, but does not solve this - this would require adding code which would 1) increase overhead, and 2) decrease portability. DLM recommends against, please re-open if necessary.
