### ISSUE TITLE
Entity Tools need to allow addition of new records to existing Entities

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6683]
Entities are designed to join records sharing a common identifier, and the Entity url is designated as an organism ID.
One significant use case for Entities is to link repeated samples taken from the same organism as part of mark/recapture or captive breeding programs. 

Problem: we need to be able to add new records to already existing Entities, as new samples are taken from the same individuals over time. That functionality doesn't appear to exist with current tools.

Example:
Trying to use the Entity tools for three records from the same chimpanzee - two of which already were joined by an entity url, and the third needed to be included. When I searched on all records with the same GAN identifier, and then used the Search Tools Menu to Manage Entities, and choose GAN as the ID type to create the Entity, I get the following error message: 

![Screenshot 2023-08-24 10 19 10](https://github.com/ArctosDB/arctos/assets/14808196/96f45369-8aa9-44d9-a6e1-ee3f7b7c6811)

**Comment by Jegelewicz** [comment]
I believe the way to do this is to add the Entity url to the new record as OrganismID. The tool is meant to create new entities, not add new records to existing entities.

**Comment by mkoo** [comment]
@campmlc would this new tool/function be able to look up stuff with the same GAN? 
What other info do you have now to help track down any existing Entities? And then presuming you find it, you want to tool to offer something like ``` Add to existing Arctos:Entity:214```
Right?

**Comment by mkoo** [comment]
Essentially the current tool is not designed for what you want to do.

Another suggestion: a bot that you can manually run that looks through the  Arctos:Entity collection for the same GAN and same taxon and then can add the appropriate organismID to the record.

**Comment by dustymc** [comment]
I added a bullet point.

> This tool will not add to an existing Entity. Use any identifier tool for that.

**Comment by campmlc** [comment]
> Essentially the current tool is not designed for what you want to do.
> 
> Another suggestion: a bot that you can manually run that looks through the Arctos:Entity collection for the same GAN and same taxon and then can add the appropriate organismID to the record.

Can I get the bot to run through designated collections looking for the same identifier and adding the appropriate organism ID? If I understand correctly, this would be similar to the relationships bot that we currently have? 

Having to periodically bulkload identifiers is not a viable alternative here. There are already hundreds of relevant entities with thousands of component records - and this is only going to increase. If the entity tool can only be used a a single point in time, we need something that will function to add new records over time as they occur.

**Comment by mkoo** [comment]
Actually what Teresa said is the most direct way-- after searching for the arctos:entity, just add as another identifier (choose type=organismID and enter the URL (eg https://arctos.database.museum/guid/Arctos:Entity:xxx) in the prefix string -- done) but I think you're asking for a button to do both the search and then something like select from the results to make that organismID for you. Right?! Let us know if we have characterised your need

**Comment by mkoo** [comment]
> > Essentially the current tool is not designed for what you want to do.
> > Another suggestion: a bot that you can manually run that looks through the Arctos:Entity collection for the same GAN and same taxon and then can add the appropriate organismID to the record.
> 
> Can I get the bot to run through designated collections looking for the same identifier and adding the appropriate organism ID? If I understand correctly, this would be similar to the relationships bot that we currently have?
> 
> Having to periodically bulkload identifiers is not a viable alternative here. There are already hundreds of relevant entities with thousands of component records - and this is only going to increase. If the entity tool can only be used a a single point in time, we need something that will function to add new records over time as they occur.

@campmlc I think it may be more productive we have chat about this over the phone. what's a good time for a phone call?

**Comment by campmlc** [comment]
Absolutelty willing to do a call and a demo. The use cases for handling zoo and captive breeding program samples are  far more complex that what is being described above, and that is what I had understood the current tool to accomplish, but it won't work if new components cannot be added to multiple entities at a time as it currently does for new entities. It is not a matter of loading organism IDs for a single animal. 
This week is pretty rough, but Thursday morning is possible?

**Comment by mkoo** [comment]
Maybe next week then? or whenever the new identifier tool is pushed to
prod--  email me with separately with times bc maybe the new functions may
help too. We can figure out a way to make it easier

**Comment by campmlc** [comment]
This Thursday works before 3pm MDT and not 12-1 MDT.  I have to process a zoo loan, so need to get this sorted to make sure the new samples can be cataloged correctly.

**Comment by campmlc** [comment]
I don't see the meeting invite on my calendar - maybe got deleted? I'm ok
with next Thursday before AWG meeting if that works better than today?

**Comment by dustymc** [comment]
Needed functionality requests are being moved to other issues, closing this.
