### ISSUE TITLE
Feature Request - Prefix/Suffix ID Values

### ISSUE THREAD

**Issue by Cpittman53** [ArctosDB/arctos#6687]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

I was working on cleaning up the DMNS identifier issues by using the Bulk Unload and Bulkloader. When using the Identifier Bulkloader, I was not able to upload the Prefix/Suffix values due to the required and conditional fields.

**Describe what you're trying to accomplish** 

For future bulk loading of Identifiers, we hope to include Prefix and Suffix identifiers.

**Describe the solution you'd like**

The addition of Prefix and Suffix id to the Identifier Bulk Loader as a conditional field. 

**Describe alternatives you've considered**

It looks like the prefix/suffix id's are only able to be put in manually. 

**Additional context**

![image](https://github.com/ArctosDB/arctos/assets/106274900/24eb4951-9719-4a69-ac95-5590556dae86)

**Priority**

Low priority but may come up again soon.

**Comment by Jegelewicz** [comment]
@Cpittman53 as I have been working on these I wonder why we have the prefix-integer-suffix. It looks like things loaded a long time ago got separated this way, but things loaded more recently seem to end up in prefix if they have any characters other than numbers and nothing is split to the integer section. It seems like we either need the three sections everywhere identifiers might be entered or we shouldn't have the three sections at all?

**Comment by dustymc** [comment]
> wonder why we have the prefix-integer-suffix.

So one can sort by the integer, or so goes the theory.

Reality is that is adds a LOT of complexity and I'm not sure anyone uses it. The "core-most" use case may completely overlap with an agent-free identifiers model - eg, this is handy for 'DLM123' (so the 123 sorts numerically), but that format is just a very old and very ineffective attempt to link 123 to an Agent, which we've done explicitly.

I'd certainly be happy to see it go away if that's possible.

>need the three sections everywhere identifiers might be entered

Maybe, but that's also completely incompatible with what we've decided regarding changing data entry.

> not able 

I need to know specifically what's not acting as the [documentation](https://handbook.arctosdb.org/documentation/other-identifying-numbers.html#bulk-loading-rules) says it should.

**Comment by Jegelewicz** [comment]
> not able

There aren't column headers in the loader for prefix, integer, suffix and as far as I can tell, when you load something that might want to use that format, it sometimes ends up in the three places and sometimes it is just all in prefix or suffix.

![image](https://github.com/ArctosDB/arctos/assets/5725767/4e037179-6de2-4140-9814-d34c3033852c)

It feels random and the only way to make sure it isn't random is to enter it manually in the form on the catalog record because you do not have that fine control anywhere else.

**Comment by dustymc** [comment]
>only way to make sure it isn't random

Please see my previous comment.

**Comment by Jegelewicz** [comment]
And that is my point - do we need this anymore or is it just unnecessary complexity? Can we figure out if anyone uses it and if not let's reduce the complexity?

**Comment by mkoo** [comment]
Seems like everyone agrees that  prefix and suffix adds confusion and resource burden. I have been adding new_other_ids that are strings, integers or alphanumerics so seems functionally we dont need it? Can all the instances where suffix is not null be just added to the "value" field? There's a lot of legacy stuff with initials being part of collector/field number series so I dont see a problem just making the whole thing strings. If sorting is an issue then it can be cleaned up with separate clean-up issues.

I am going to change the issue title to reflect removing the prefix and suffix and have simply one field for the value-- ok?
Can that be added to the documentation of the bulkloader so it's clear one can use more than one thing here?

**Comment by dustymc** [comment]
Adding to AWG agenda as an effort to find any actual use of the components. I suspect a simplification would go totally unnoticed (by users - I would notice, this is expensive and complex to maintain!), and if there is any use I can easily extract relevant bits out of the value.

**Comment by campmlc** [comment]
I agree with the simplification. I don't know of anyone using it, and the variability in results and lack of good documentation are problematic.

**Comment by dustymc** [comment]
AWG meeting: nobody is dealing with identifiers that can't be dynamically parsed, GO! (But stash split data here just in case.)

**Comment by dustymc** [comment]
Pre-migrate data are in ``old_other_ids.zip`` on arctos-ha. It's about 100MB, if anyone wants a copy let me know ASAP.
