### ISSUE TITLE
Curatorial Search Request - Project Media views

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#6690]
NSF report time! @dustymc - Can you please give me SQL or csv for how many people viewed/clicked media from Project 10003438?

This is the SQL from last time but I get an error about it containing illegal characters:

create table temp_p_10003438_mdia as select
media.media_id,
media.media_uri,
media.mime_type,
media.media_type,
exit_link.username,
exit_link.ipaddress,
exit_link.from_page,
exit_link.when_date,
exit_link.status
from media
inner join exit_link on media.media_id=exit_link.media_id
inner join media_relations on media.media_id=media_relations.media_id and project_id=10003438;

**Comment by dustymc** [comment]
```
select
media.media_id,
media.media_uri,
media.mime_type,
media.media_type,
exit_link.username,
exit_link.ipaddress,
exit_link.from_page,
exit_link.when_date,
exit_link.status
from media
inner join exit_link on media.media_id=exit_link.media_id
inner join media_relations on media.media_id=media_relations.media_id and project_id=10003438
```
[temp_cache.user_sql_tbl_dlm(7).csv.zip](https://github.com/ArctosDB/arctos/files/12458820/temp_cache.user_sql_tbl_dlm.7.csv.zip)
