### ISSUE TITLE
Record won't load because of locality 1 attribute date being invalid (but it's fine)

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#6693]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

This record of mine in the bulkloader keeps failing to load because of a supposed error
https://arctos.database.museum/Bulkloader/editBulkloader.cfm?key=key_182261

the error is
locality_attribute_1_date is invalid

but the locality_attribute_1_date  is correctly formatted (﻿﻿2023-08-25) and has no trailing spaces etc. There is only 1 locality attribute so what's going on & how do I fix & load this record? And more importantly how do we prevent this error from happening to other records? (oddly this was one of dozens of records entered together and the others all loaded fine)

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.
high

**Comment by dustymc** [comment]
That starts with 4 ASCII(6527) characters, which whatever you're using (and certainly my terminal!) isn't showing.

I can update (or you can re-enter and save in the editor), but you might want to figure out where that came from.

**Comment by DerekSikes** [comment]
Strange! No idea how those got there... I deleted the contents of the field & re-entered and it worked. Invisible ASCII mumbo jumo ghost in the machine! Thanks

**Comment by dustymc** [comment]
Been thinkin' we need an Official Arctos Exorcist for a while now....
