### ISSUE TITLE
Feature Request - why does a pop-up window appear asking me to click agent name when there is only 1 match?

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#6694]
Previously if an agent name had only 1 match it would auto-fill when one hit tab. Now a window pops up and I have to click a button. Can we please return the prior faster more streamlined functionality?

This is happening when I select my own name Derek S. Sikes. It will create a massive number of new clicks I didn't have to deal with! (Esp with all these new attributes!)

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._
high

**Comment by dustymc** [comment]
>why

https://github.com/ArctosDB/arctos/issues/5270

**Comment by AdrienneRaniszewski** [comment]
I am also finding this pretty annoying. I copy and paste a lot of names and having to move my cursor and make another click every single time really slows me down.

**Comment by Jegelewicz** [comment]
@dustymc it does seem like we have at least one set of unique identifiers for at least some names - https://github.com/ArctosDB/arctos/issues/5270#issuecomment-1700024693

Is there any other way we can make this less "clicky"?

The issue I had is a problem only because there was no EXACT match and Arctos picked something I did not intend. I understand that we hope someday to allow for two John Smiths, but right now we cannot do that. An exact match to any preferred name should be able to safely insert that agent without the need to pick from a list of one.

**Comment by dustymc** [comment]
>e have at least one set of unique identifiers for at least some names 

All agents have a unique name (for now, I hope, but I'm not sure that's moving).

>Is there any other way we can make this less "clicky"?

You type "John Doe." John Doe is preferred name == unique == exact match so I think you're saying that it should auto-accept. Maybe it's who you intend, maybe that John Doe has a death date of 1840 and you have a butterfly collected in 2023, there's no possible way I can know! And maybe you are looking for John Doeherty, but if we try to do something with uniques you're still going to be forcefed John Doe. 

The way it was, "John Doeherty" would auto-select (assuming there's no "John Doehertyy" in Arctos) - there was nothing about "unique" involved, "one match" was the filter - and the world could still have known multiple people named John Doeherty and the one in Arctos could still not be the one you want!

I'm having a hard time understanding how autoselecting ANYTHING isn't going to lead to messes, but maybe we're truly not there yet. It's easy enough to change the techy-bits, but this does seem to be something that needs specific guidance. I I'll change the milestone.

**Comment by dustymc** [comment]
>We aren't 

Then why does https://github.com/ArctosDB/arctos/issues/new?assignees=&labels=Function-Agents&projects=&template=agent-split-request.md&title=Agent+Split+Request exist?! I think at some point we're going to have to let the data speak for themselves....

Anyway - this was your request, I apparently misunderstood it (and definitely did not see any way it was going to be controversial!), I'll just roll back for next release, we can start over if there's some need.

**Comment by DerekSikes** [comment]
Thanks!
