### ISSUE TITLE
Code Table Request - New event attribute type: event documentation

### ISSUE THREAD

**Issue by KatherineLAnderson** [ArctosDB/arctos#6695]
### Goal
_Describe what you're trying to accomplish. This is the only necessary step to start this process. The Committee is available to assist with all other steps. Please clearly indicate any uncertainty or desired guidance if you proceed beyond this step._

Request to add locality attribute type "field documentation" (or alternatively "additional documentation") as a place to enter references to field notebook and/or maps for localities. 

### Context
_Describe why this new value is necessary and existing values are not._

The ultimate goal will be to link the locality records to archival records. There is currently no other place other than locality remarks or less specific locality attributes (e.g., site identifier) to enter these references. Entering this data into their own specific field will make pulling the relevant data for this linkage easier.

### Table
_Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table or value. This may involve multiple tables and will control datatype for Attributes. OtherID requests require BaseURL (and example) or explanation. Please ask for assistance if unsure._

~~https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlocality_attribute_type~~

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_event_attr_type (https://github.com/ArctosDB/arctos/issues/6695#issuecomment-1701536464)

### Proposed Value
_Proposed new value. This should be clear and compatible with similar values in the relevant table and across Arctos._

~~Field documentation~~ ~~field~~ event documentation

### Proposed Definition
_Clear, complete, non-collection-type-specific **functional** definition of the value. Avoid discipline-specific terminology if possible, include parenthetically if unavoidable._

Reference to field notebooks, maps, and/or other materials that document the event. Tip: Publications can also be used to reference event documentation and provide another path for associating documentation with events.

### Collection type
_Some code tables contain collection-type-specific values. ``collection_cde`` may be found from https://arctos.database.museum/home.cfm_

ES (perhaps others?)

#### Attribute data type
_If the request is for an attribute, what values will be allowed?
free-text, categorical, or number+units depending upon the attribute (TBA)_

free-text

#### Attribute controlled values
_If the values are categorical (to be controlled by a code table), add a link to the appropriate code table. If a new table or set of values is needed, please elaborate._

n/a

#### Attribute units
_if numerical values should be accompanied by units, provide a link to the appropriate units table._

n/a

### Priority
_Please describe the urgency and/or choose a priority-label to the right. You should expect a response within two working days, and may utilize [Arctos Contacts](https://arctosdb.org/contacts/) if you feel response is lacking._

Priority-high for ongoing migration projects

### Example Data
_Requests with clarifying sample data are generally much easier to understand and prioritize. Please attach or link to any representative data, in any form or format, which might help clarify the request._

### Available for Public View
_Most data are by default publicly available. Describe any necessary access restrictions._

yes

### Helpful Actions

- [x] Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

- [x] Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

@ArctosDB/arctos-code-table-administrators 

## Approval
_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection
_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation
_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

- [ ] Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

- [ ] Add or revise the code table term/definition as described above. Ensure the URL of this Issue is included in the definition.

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

Request per discussion with @Jegelewicz @WaigePilson @dustymc

**Comment by WaigePilson** [comment]
I think that "field documentation" is the best use here, to maintain a distinction between the documentation that happens in the field (e.g., maps, notes on the weather) and the administrative record being asked for in #6695.

Also, maybe I'm understanding all of this incorrectly but wouldn't it be most appropriate to have "field documentation" be an attribute of a collecting event? The field documentation is not only place but also time specific.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> attribute of a collecting event

I agree, that might be the right place for this information.

Maybe this could even be split into two different things?
"verbatim field documentation" for a transcription of field notes.
"archive reference" for link/location of the archive record

**Comment by KatherineLAnderson** [comment]
> > attribute of a collecting event
> 
> I agree, that might be the right place for this information.
> 
> Maybe this could even be split into two different things? "verbatim field documentation" for a transcription of field notes. "archive reference" for link/location of the archive record

I think Paige is right as well. "field documentation" or "field documentation reference" (if we want to be specific that this is a place for a reference rather than a description/transcription) should likely be an event attribute type because the field notes are verbatim. Good call! 

As for field note transcriptions, I'm not sure but perhaps this deserves more discussion in its own thread. Most of it already ends up in other fields, like verbatim locality, yes?

**Comment by mkoo** [comment]
I have also struggled with this and now MVZ has historic localities with references to field notebook pages mainly in the locality remarks so they can be visible on public pages.

I do like "field documentation" as an attribute but where it's most appropriate confounds me right now
@WaigePilson point is a solid one as field doc would be place and time specific so collecting event table is appropriate and would appear on the record detail page as well (just tried it). Other thoughts?

let's talk about field transcription in a new thread as we are going to launch a crowd funding project soon!

**Comment by Jegelewicz** [comment]
People seem to like this, but nobody has checked any boxes. @mkoo @Nicole-Ridgwell-NMMNHS @dustymc

**Comment by dustymc** [comment]
I'm still not terribly comfortable with the term (I read 'grassy place' or 'database mapping') or definition (maybe implies I need something other than the free text this will accept), and I could use some more disambiguation from https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_event_attr_type#data_management_history, but the *concept* seems sound enough and hopefully my reservations are all minor details - checking boxes.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I think both the term and the definition are fairly vague, but perhaps that is ok, individual collections can use the term in whatever way works best for them to record notebooks, maps, etc. Added a check.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Maybe add to definition something like "TIP: Publications can also be used to reference event documentation"

**Comment by Jegelewicz** [comment]
Changes on March 7 were made during the code table meeting - https://docs.google.com/document/d/1eZ_S8VTp-m5Wrbb6cAK96ODPZpt2-Hvnvt6yfU9qVwg/edit#heading=h.95vtqbnbctbb

added
