### ISSUE TITLE
Code Table Request - New locality attribute type: Administrative history

### ISSUE THREAD

**Issue by KatherineLAnderson** [ArctosDB/arctos#6696]
### Goal
_Describe what you're trying to accomplish. This is the only necessary step to start this process. The Committee is available to assist with all other steps. Please clearly indicate any uncertainty or desired guidance if you proceed beyond this step._

Request for "Administrative history" locality attribute type to record history of locality data management/administration.

### Context
_Describe why this new value is necessary and existing values are not._

This attribute type will be used to record history of locality data management/administration, akin to processing history for catalog records. E.g., date of entry and who entered it into the legacy database.

### Table
_Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table or value. This may involve multiple tables and will control datatype for Attributes. OtherID requests require BaseURL (and example) or explanation. Please ask for assistance if unsure._

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlocality_attribute_type

### Proposed Value
_Proposed new value. This should be clear and compatible with similar values in the relevant table and across Arctos._

~~Administrative history~~ data management history

### Proposed Definition
_Clear, complete, non-collection-type-specific **functional** definition of the value. Avoid discipline-specific terminology if possible, include parenthetically if unavoidable._

Description of administrative actions capturing or otherwise affecting locality data (e.g., date and determiner of data entry into legacy databases)

### Collection type
_Some code tables contain collection-type-specific values. ``collection_cde`` may be found from https://arctos.database.museum/home.cfm_

ES (perhaps others?)

#### Attribute data type
_If the request is for an attribute, what values will be allowed?
free-text

#### Attribute controlled values
_If the values are categorical (to be controlled by a code table), add a link to the appropriate code table. If a new table or set of values is needed, please elaborate._

n/a

#### Attribute units
_if numerical values should be accompanied by units, provide a link to the appropriate units table._

n/a

### Priority
_Please describe the urgency and/or choose a priority-label to the right. You should expect a response within two working days, and may utilize [Arctos Contacts](https://arctosdb.org/contacts/) if you feel response is lacking._

Priority-high for ongoing migration projects

### Example Data
_Requests with clarifying sample data are generally much easier to understand and prioritize. Please attach or link to any representative data, in any form or format, which might help clarify the request._

Date and Agent who entered locality record into Filemaker Pro database

### Available for Public View
_Most data are by default publicly available. Describe any necessary access restrictions._

yes

### Helpful Actions

- [x] Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

- [ ] Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

@ArctosDB/arctos-code-table-administrators 

## Approval
_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval (https://github.com/ArctosDB/arctos/issues/6696#issuecomment-1707286492)
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection
_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation
_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

- [ ] Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

- [ ] Add or revise the code table term/definition as described above. Ensure the URL of this Issue is included in the definition.

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

Request per discussion with @Jegelewicz @WaigePilson @dustymc
ker Pro). Retains ability to search/track how many records were entered each year and by who. There is currently not a similar attribute for localities.

### Table
_Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table or value. This may involve multiple tables and will control datatype for Attributes. OtherID requests require BaseURL (and example) or explanation. Please ask for assistance if unsure._

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlocality_attribute_type

### Proposed Value
_Proposed new value. This should be clear and compatible with similar values in the relevant table and across Arctos._

Administrative history

### Proposed Definition
_Clear, complete, non-collection-type-specific **functional** definition of the value. Avoid discipline-specific terminology if possible, include parenthetically if unavoidable._

Description of administrative actions capturing or otherwise affecting locality data (e.g., date and determiner of data entry into legacy databases)

### Collection type
_Some code tables contain collection-type-specific values. ``collection_cde`` may be found from https://arctos.database.museum/home.cfm_

ES (perhaps others?)

#### Attribute data type
_If the request is for an attribute, what values will be allowed?
free-text

#### Attribute controlled values
_If the values are categorical (to be controlled by a code table), add a link to the appropriate code table. If a new table or set of values is needed, please elaborate._

n/a

#### Attribute units
_if numerical values should be accompanied by units, provide a link to the appropriate units table._

n/a

### Priority
_Please describe the urgency and/or choose a priority-label to the right. You should expect a response within two working days, and may utilize [Arctos Contacts](https://arctosdb.org/contacts/) if you feel response is lacking._

Priority-high for ongoing migration projects

### Example Data
_Requests with clarifying sample data are generally much easier to understand and prioritize. Please attach or link to any representative data, in any form or format, which might help clarify the request._

Date and Agent who entered locality record into Filemaker Pro database

### Available for Public View
_Most data are by default publicly available. Describe any necessary access restrictions._

yes

### Helpful Actions

- [x] Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

- [ ] Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

@ArctosDB/arctos-code-table-administrators 

## Approval
_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [ ] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [ ] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection
_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation
_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

- [ ] Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

- [ ] Add or revise the code table term/definition as described above. Ensure the URL of this Issue is included in the definition.

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

Request per discussion with @Jegelewicz @WaigePilson @dustymc

**Comment by Jegelewicz** [comment]
Thinking about what "administrative history" might sound like (without reading the description - because lots of people don't...) and this feels like it would describe administration of the physical locality (aka landowner, etc.).

How about

data version history - Description of administrative actions capturing or otherwise affecting locality data. This value should describe the activity (e.g., data entry into legacy database). The date and determiner should reflect the date the action occurred and the agent who performed the action. If possible, provide a link to a stored copy of the data or add it as text to the attribute remark.

Thoughts?

@happiah-madson @falco-rk @Nicole-Ridgwell-NMMNHS would any of you have use for this? I think ti would be a really useful addition for these localities.

@ArctosDB/arctos-code-table-administrators 

Finally, I think this could also be used instead of #6695 to record the link to physical data about the location as well? If the first "version" is the collector's notebook, then just add it to this attribute?

**Comment by dustymc** [comment]
>describe ... the physical locality

Yea, I keep ending up there too, having trouble with clear terminology. And (I imagine..) this could include "bought by ..." in addition to "entered by..." - it might have to do with the place itself in addition to data-wrangling so maybe I do like 'administrative' better than 'data.' ??

I don't quite see the separation from https://github.com/ArctosDB/arctos/issues/6695 either - it all just - uhh - documentation?

* someone wrote something in some document
* sold to new owners
* paved for new walmart
* someone scribbled on a map
* someone entered something into some computer

All same thing, no?

**Comment by WaigePilson** [comment]
I am in favor of adding something either "Data version history" or "Administrative history"!

One key distinction which I would push for: the history being documented is regarding the data (e.g., who entered the database record, which database system was the record entered into) NOT the physical place/object (e.g., who found the locality, sold to new owners). I am willing to be convinced otherwise, but it feels like DATA versus PHYSICAL PLACE should be maintained as two distinct concepts in terms of "processing" or "administration" in the conceptualization of this new attribute.

>I don't quite see the separation from https://github.com/ArctosDB/arctos/issues/6695 either - it all just - uhh - documentation?
This is definitely distinct to me! #6695 is requesting a very specific field which will contain data about the fieldnotes or other written documentation about the locality; ideally in the future will be linked to a specific archive record of that documentation. This is documentation about the fieldwork, not the data entry. Again, I would like to maintain a distinction between the DATA and the PHYSICAL (fieldwork) here.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I would definitely use a field where I could put date entered into our locality ledger.

> NOT the physical place/object

Agreed.

I don't particularly like either data version history (could get confused with georeference source) or Administrative history (this sounds like landownership to me). What about "Documentation History" and something like "Archive Reference" for #6695?

**Comment by wellerjes** [comment]
CHAS would have a use for this as well; currently a lot of this is in the catalog records remarks, along the lines of "last updated in Excel prior to Arctos migration" or "last updated in FileMaker in the 1990s". It definitely goes under processing history, but doesn't really fit in with verified presence or verified to source.

**Comment by KatherineLAnderson** [comment]
In terms of the name of the field, yes "administrative history" could be misleading. I think I'd prefer something with "data" in the title, reflecting the field is for data about the capturing/management of the locality data--perhaps "data administration history",  "data curation history", "data management history"...?

**Comment by wellerjes** [comment]
I like "data management history"!

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I agree, data management history works well!

**Comment by Jegelewicz** [comment]
@ArctosDB/arctos-code-table-administrators we need one more code table manager to check a box.

**Comment by KatherineLAnderson** [comment]
Still waiting on the box check?

**Comment by Jegelewicz** [comment]
added
