### ISSUE TITLE
Curatorial Search Request - Media Counts

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#6697]
@dustymc I need some media counts for a report:

- count of all media_URIs that contain "ark.colorado.edu"
- count of all documents_cataloged item relationships tied to media_URIs that contain "ark.colorado.edu" (possible?)

Thanks!

**Comment by dustymc** [comment]
```
select count(*) from media where media_uri ilike '%ark.colorado.edu%'

 count 
-------
  6074

```

I changed this one up a bit because the number surprised me.

```
select 
count(media_relations.media_relations_id) numReltionships,
count(distinct(media.media_id)) numMedia
from media 
inner join media_relations on media.media_id=media_relations.media_id
where 
media_uri ilike '%ark.colorado.edu%' and
media_relationship='documents cataloged_item'

 numreltionships | nummedia 
-----------------+----------
          112503 |     6041
```

**Comment by ebraker** [comment]
Amazing, thank you! The second number is high since we should be linking to nearly every record (and there are many cases where we have an old ledger that has been re-transcribed, so some records may have two separate ledger links).
