### ISSUE TITLE
Feature Request - search agent curatorial remark

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6699]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

We added curatorial remark to agents, but there is no way to search it.

**Describe what you're trying to accomplish** 
_A clear and concise overview of the goals; why are you asking for this?_

Find an agent based upon information placed in curatorial remark

**Describe the solution you'd like**
_How might we accomplish your goals?_

add the field to the search form

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

not finding stuff, asking for SQL

**Additional context**
_Add any other context or screenshots about the feature request here._

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._

Agent data has been added for an incoming collection that will want to find things using this information. Inability to do this makes data migration more difficult.

**Comment by AJLinn** [comment]
Yes please.

**Comment by Jegelewicz** [comment]
@dustymc I really need this to help me work through some agents for an incoming collection. How hard is it to add this search field?

**Comment by dustymc** [comment]
Not difficult (has that ever been the limitation?!) but still needs to go through the process (https://github.com/ArctosDB/internal/issues/258), gappy though it may be. (And if you can somehow ram that through now-ish, I'm at a point where I could start working on this...)

Ideally I think this would be combined with https://github.com/ArctosDB/arctos/issues/6645 - the searching would likely be much more productive if seeing the results wasn't a couple clicks away.

(And that might reuse the pick format, which also doesn't contain curatorial remarks...)

**Comment by Jegelewicz** [comment]
Honestly - I don't think #6645 is needed, but I'll let others weigh in.

@ArctosDB/arctos-working-group-officers thoughts on getting this to implementation?

**Comment by campmlc** [comment]
I support implementing this. I'm not sure #6645 is needed either - especially since it would return far fewer results at a time without scrolling down. Maybe if the interface were cleaned up a bit. But that shouldn't stop #6699.

**Comment by AJLinn** [comment]
I'm not an officer, and agreed that this would be useful above, so I'll just reiterate my support that the curatorial remarks field would be useful for searching.

**Comment by Jegelewicz** [comment]
> except for the different letters. :)

yeah - that's a pretty small difference!
