### ISSUE TITLE
Data loaded but disappeared

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#6700]
**Describe the bug**
I entered 4 records in data entry, checked them, and loaded them and they disappeared but the records aren't there. Based on weird behavior in search results, I don't think that I just accidently hit delete instead of load (although maybe those buttons should not be right next to each other.)

**To Reproduce**
1. Go to Enter records
2. Enter the records (in this case I did something I usually don't which is use collection event ID instead of locality name)
3. Successfully enter the records
4. Go to browse and edit, check things, fix a few errors
5. Load records
6. records disappear from browse and edit
7. Search for the records and get this:

![image](https://github.com/ArctosDB/arctos/assets/47402809/1a452357-2c1f-4f5c-8be3-dd8f2f7e72d8)

I would think if I had accidently hit delete that it would just show no results. I waiting a bit thinking the results just hadn't cached, but nothing. I also tried going to the GUID directly, but it says GUID not found:

![image](https://github.com/ArctosDB/arctos/assets/47402809/06ab5ce9-f6c0-4e3e-beca-3f176ee5905f)

**Expected behavior**
My data to load.

**Data**
I don't have this. These were four individually entered records and I didn't download the data before loading.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 116.0.5845.140

**Comment by dustymc** [comment]
https://arctos.database.museum/info/flat_status.cfm

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I see my records now thankfully! What does error in processing on cache status mean?

![image](https://github.com/ArctosDB/arctos/assets/47402809/aa2acd05-db6b-41a9-93e1-943f8dd99c0e)

**Comment by dustymc** [comment]
>What does error in processing on cache status mean?

Usually a glitch in the matrix, but this time it was someone following Worst Practices (recording no dates) and confusing a now-slightly-smarter function. Thanks!

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> recording no dates

Because the event date is just a year?

Haha, I could give a whole rant about folks here not recording dates.

**Comment by dustymc** [comment]
>just a year?

Someone in a few decades will think that's really great precision!

You can *always* eliminate tomorrow from dates. (I want a ride to Hawking's party if that's not true!) Even absolutely nothing holds more precision NOW than it can in a day, a year, or a century. Recording nothing is discarding information.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> You can always eliminate tomorrow from dates.

Well, yes that is always try to do when I enter this stuff. These records (NMMNH:Paleo:83543-83546) were no exception?

I want to verify that part of this was just cache catching up? It is doing it again for NMMNH:Paleo:83630-83655.

**Comment by dustymc** [comment]
Aha, sorry - I don't think your records were in any way involved in the hiccup, and that particular hiccup has been eliminated so it shouldn't matter (for this, still Best Practices demand certain things!) if they were.

Whatever's going on now should be explained by https://arctos.database.museum/info/flat_status.cfm -there are ~6K records to process at the moment.
