### ISSUE TITLE
Make Parts Table Download consistent with Parts Table View

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6709]
Parts Table View from Search Results Tools shows a part remarks column and a loans column at the end of the display after CID1.  But when you download these results from the View page, the column order and headers are not the same. Loans and remarks get moved to the left, near disposition. Furthermore, Part Remarks get renamed Collection Object Remarks, which they are not.  Can we get the view and download columns to match, please, and have part remarks names correctly and placed after CID1 next to part attributes, where they should be?
1) Go to Search Results: Tools: View/Download:  Parts
2) See displayed values
3) Click download button
4) See displayed values
5) See discrepancy

**Comment by dustymc** [comment]
merge --> https://github.com/ArctosDB/arctos/issues/6806
