### ISSUE TITLE
Feature Request - bulkloader_stage needs more control

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6710]
**Is your feature request related to a problem? Please describe.**

Somehow the bulkloader ended up with 2million+ mostly-blank records which took Arctos down a couple times.

**Describe what you're trying to accomplish** 

Keep Arctos alive

**Describe the solution you'd like**

Infinite resources.

**Describe alternatives you've considered**

Add more requirements - nothing can get out of the table without a recognizable/keyed enteredby and guid_prefix, and requiring them here should have prevented this (perhaps at the cost of more-cryptic errors, but anyone with errors at this level probably needs focused help anyway).

I'm very up for better ideas, complicating anything at this stage will find a way to cause someone some stress, but I think what we have now isn't sustainable so I'll do something very soon unless I hear otherwise.

**Additional context**

**Priority**

fatal but rare == critical

**Comment by Jegelewicz** [comment]
HMMMM - as I recall, the bulkloader would throw an error if I had a blank row, but maybe we asked that Arctos ignore blank rows, and maybe that isn't happening?

In any case, I agree that any row that is missing a GUID prefix or entered by should throw an error and hopefully would stop what happened.
