### ISSUE TITLE
uplink single media error - help!

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6711]
**Describe the bug**

I'm seeing 

```
Can't cast String [] to a value of type [Array]
```

in the error logs.

**To Reproduce**

I can't reproduce - help! Might not even be visible in the UI.

@ufarrell you should have seen (or not....) some of these - help?

**Priority**

No idea, is this disruptive or just logging some weird state or ??

**Comment by ufarrell** [comment]
I'm no help, sorry - happily uploading images, not seeing any error! I'll keep an eye out, I'll be adding more soon

**Comment by dustymc** [comment]
Calling this a glitch in the matrix....
