### ISSUE TITLE
Better dates for events

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6713]
@dustymc All of the events in CRCM:Mamm have bogus begin and ended dates. This file has two columns at the end that include the better begin and ended dates. Can you update them for us?

[CRCM_event_dates2.csv](https://github.com/ArctosDB/arctos/files/12541332/CRCM_event_dates2.csv)

**Comment by Jegelewicz** [comment]
From Bob Mesibov

Hi, Teresa.

By way of explaining my question, have a look at (for example)
https://arctos.database.museum/guid/CRCM:Mamm:7009

This gives the verbatim date as 20-Aug-18, and the start/end as 1800/2023-01-27. In your CRCM_event_dates2.csv, this record (collecting event ID 12420516) is said to have VERBATIM_DATE "20-Aug-18" and you give the start/end date 2018-08-20.

VertNet has interpreted "20-Aug-18" as 20 August 1918
http://portal.vertnet.org/o/crcm/mammals?id=urn-catalog-crcm-mammals-662

and this is the date that's found its way to GBIF.

How did VertNet interpret "18" as 1918, and you as 2018?

**Comment by dustymc** [comment]
I don't really have a safe way to do this, and it's not a terribly uncommon ask. (But still - this doesn't seem like something that should have happened, how'd we get here?!)

One option might be to change https://github.com/ArctosDB/arctos/issues/4033 into 'bulk fork-edit specimen event' and somehow run through that process, if that's compatible with what's there (and here - that would probably have to fail if there are named anythings involved in any way).

These data are wonky enough that they're PROBABLY not very shared and I might be able to just update, and that's got us here....

I could ask for downtime and safely update, but that doesn't seem entirely reasonable.

I'm not sure how to approach this, help?

(And I think the comments mean you need to revise the data??)

**Comment by Jegelewicz** [comment]
> this doesn't seem like something that should have happened, how'd we get here?

I really do not have a good answer for that, but here we are.

> need to revise the data?

Yes - I will now make a comparison of data in Arctos to data in GBIF to see what's up.

**Comment by Jegelewicz** [comment]
This is going to be a long slog because the data in GBIF uses the old catalog numbers which are hyphenated and do weird things in Excel, so I am probably gonna have to use R to work through this and it isn't going to be simple. I'm going to close this and return to the data migration project.
