### ISSUE TITLE
identification unloader needed

### ISSUE THREAD

**Issue by AdrienneRaniszewski** [ArctosDB/arctos#6714]
DLM edit:

* need an identification download (with - SOMETHING - we can add to it when there's a defined need)
* it needs an identification unloader to feed

Going next task, I know how to do this (but won't until/unless there's support from the collections).

----------------------

original:

A researcher ran across over 100 of our records that were loaded with incorrect species identification. He needs them fixed ASAP. They are incorrect because of some sort of excel sorting error, so we'd like to completely delete these identifications. and then bulkload the correct ones. What's the best way to delete? I see where I can go into each record and delete the bad identification one at a time, but I can't find the bulk delete option.

**Comment by Jegelewicz** [comment]
> best way to delete

I'd suggest using the manage identification tool from search results to unaccept whatever is there now (I think that can be done?), then use the identification bulkload tool to load the new identifications.

**Comment by dustymc** [comment]
There's no bulk-deleter but there could be. It would need to work with the identificationID (eg https://arctos.database.museum/guid/ACUNHC:Herp:12/IID15096696) - you can get that in the 'download for citation' option now (but maybe not in a terribly useful format).

Any clever ideas about what a useful identification download might look like would be greatly appreciated - and I can SQL for you, if you want to let me know something about what you're looking for.

Once there's no ambiguity) I can zap things for you, and hopefully the shape of a loader will become apparent somewhere along the way.

I definitely wouldn't recommend adding more IDs!

See also https://github.com/ArctosDB/arctos/issues/6607 - the big picture could use some shaping, help!

**Comment by AdrienneRaniszewski** [comment]
so, just so I can get this researcher his data quickly, can I give a list of the identifications I want deleted? I have a bulkload file with the correct identifications ready to go.

**Comment by dustymc** [comment]
yes

**Comment by AdrienneRaniszewski** [comment]
[nofchissey-id-bulkload.csv](https://github.com/ArctosDB/arctos/files/12542827/nofchissey-id-bulkload.csv)
great! here's the bulkoad file. I need all the existing identifications for these records deleted. and then the correct identifications in the file added. I can do that part though if you want. Thank you!!

**Comment by dustymc** [comment]
>all

Well that makes it easy, but please confirm anyway. At least one of these does have multiple IDs (or I messed something up, so check for that too please!).

[temp_msb_id_to_unload.csv.zip](https://github.com/ArctosDB/arctos/files/12542890/temp_msb_id_to_unload.csv.zip)

**Comment by AdrienneRaniszewski** [comment]
Will do! I’m away from my computer now, but will take a look a bit.
________________________________

**Comment by AdrienneRaniszewski** [comment]
Looks perfect! That one with two identifications - totally fine to delete both. It’ll just get reloaded when I add all the correct ones. So go for it!


~ Adrienne


Collections Associate/Staff Coordinator
MSB Division of Mammals
505-277-5369


From: Adrienne Raniszewski ***@***.***>
Date: Wednesday, September 6, 2023 at 4:23 PM
To: ArctosDB/arctos ***@***.***>, ArctosDB/arctos ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [ArctosDB/arctos] Help deleting identification (Issue #6714)
Will do! I’m away from my computer now, but will take a look a bit.
________________________________

**Comment by dustymc** [comment]
Done, I'll hijack your issue now, this seems like it might be a common need (but hopefully for other reasons!).

**Comment by AdrienneRaniszewski** [comment]
Got everything fixed. Thanks so much for your help! And yeah, always nice to have a way to do stuff ourselves so we don't have to bug you excessively.

**Comment by dustymc** [comment]
tabling - please reopen and reclassify when/if there's an articulable need for this
