### ISSUE TITLE
Help with SQL to get institutional identifiers for report

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6715]
See https://github.com/ArctosDB/data-migration/issues/1680#issuecomment-1709032738

I have the report here - https://arctos.database.museum/Reports/reporter.cfm?action=edit&report_id=107

I added othercatalognumbers, but that is just everything and all I need are institutional catalog number. I tried reusing the statement to join with attributes to join with other identifiers, but it is failing.

```
 left outer join (select collection_object_id,string_agg(display_value,'; ') as instid from coll_obj_other_id_num 
			where other_id_type ='institutional catalog number' 
			group by collection_object_id) inst
			on flat.collection_object_id=inst.collection_object_id
```

Any help is appreciated!

**Comment by dustymc** [comment]
added missing comma

**Comment by dustymc** [comment]
done?

**Comment by Jegelewicz** [comment]
Done for you, but not for me! Thanks for reminding me though....
