### ISSUE TITLE
geography request - Cornwall map

### ISSUE THREAD

**Issue by ufarrell** [ArctosDB/arctos#6719]
I'd like to use Cornwall, which is there, but missing from the map: "In GADM4.1 maps, missing from data". Could be related to this can of worms: [#6062](https://github.com/ArctosDB/arctos/issues/6062)

Cornwall: https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10015872
GADM (but I guess this might not reflect what the shapefile says??): https://gadm.org/maps/GBR/england/cornwall.html 

I suspect this might be the first of a few, I can see that there are 31 of them - let me know if I can be more helpful with how I file the issues, or if there's more I can do to help clean up

**Comment by dustymc** [comment]
I don't have any great advice, and GADM hasn't updated data as far as I can tell.

For now - you can use that, but yes, you'll be guessing what the shape might eventually-we-hope be, and potentially setting your self up for needing some sort  of migration.

Maybe a chat when @mkoo gets back - there's some chance I'm missing something in the data, she has better toys, maybe you can help interpret things, ???

**Comment by ufarrell** [comment]
Ok thanks! I will use it and see how it goes. Happy to talk about it more if it helps in any way.

**Comment by dustymc** [comment]
I am tabling this; it should be re-opened when something happens with https://github.com/ArctosDB/internal/issues/335.
