### ISSUE TITLE
Issue with password reset

### ISSUE THREAD

**Issue by Awkwardtree13** [ArctosDB/arctos#6720]
I haven't used Arctos in a few months thanks to summer break, and am now back at work since the semester has started. As expected, my old password expired during this period of inactivity. I attempted to reset my password so I could resume my work. However, when I entered my username and email the system told me "Sorry, that email wasn't found with your username." I am certain this must be an error, as I repeatedly checked to make sure the spelling and capitalization of my username was correct, and that I was using the correct email. How can I get this error resolved?

**Comment by Jegelewicz** [comment]
@babogan can you please unlock the account?

**Comment by mkoo** [comment]
@babogan HI Brooke, is your student all set? Can we close this issue?
thanks-- let us know if you have questions

**Comment by babogan** [comment]
Hi! Missed this one - I'll unlock the account!

**Comment by babogan** [comment]
@Awkwardtree13 
I have unlocked and "reset" the account! You should have received an email asking you to set a new password! Let me know if it arrived... it sent me the email as well for some reason

**Comment by Awkwardtree13** [comment]
I have received the email, so things should be good now.On Sep 13, 2023, at 1:47 PM, Brooke Bogan ***@***.***> wrote:﻿
@Awkwardtree13
I have unlocked and "reset" the account! You should have received an email asking you to set a new password! Let me know if it arrived... it sent me the email as well for some reason
