### ISSUE TITLE
Feature Request - search for "doesn't have ID"

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6726]
**Is your feature request related to a problem? Please describe.**

Various reasons, starting with entities: search for records have one ID and do not have some other ID (eg, has GAN1234 DOES NOT HAVE Arctos:Entity:1234).

@mkoo 

**Describe what you're trying to accomplish** 

**Describe the solution you'd like**

new search section - 'not ID'

**Describe alternatives you've considered**

?

**Additional context**

?

**Priority**

?

**Comment by campmlc** [comment]
Was this functionality added, or the issue just closed? Github doesn't clarify.
I needed this yesterday to be able to see if any of our DMNS identifiers are associated with records that do not have DMNS:Mamm Arctos guids.

**Comment by dustymc** [comment]
It was closed because the person who implements has no idea what's going on here, and the person who opened the issue was unable to clarify. Please re-open and clarify if you have a specific request, but please DO NOT re-open if that involves only a legacy mess (I'm always happy to help with SQL for that sort of thing).

I'll go back to confusing myself now....

**Comment by campmlc** [comment]
My understanding is that this is a request to add Boolean capability into identifier search? So we could search on two ID types at once? "Has ID type = X but NOT ID type = Y"?
