### ISSUE TITLE
Need Help with Arctos Error - ñ in Agent's last name can't resolve Agent in Arctos (even though there's an "ASCI" variant available)

### ISSUE THREAD

**Issue by jtgiermakowski** [ArctosDB/arctos#6728]
# Error Text
**Copy the text from the page and paste it here**
Can't figure out what the problem is with Agent "Adalberto Ubiñas"

# Where it happened
**Provide a link to or a description of the page where the error occurred.**
individual record edit from the bulkloader, see attached screenshots

# Steps to get there
**Describe the actions that led to the error**
tried inputting agent as "Adalberto Ubinas" "aubinas" "Adalberto L. Ubiñas", none work for the bulkloader

also, there's no way to Edit Agent for nonpreferred name, as per instructions: 

> 
![Screenshot 2023-09-11 at 15-56-31 Edit Bulkloader Records](https://github.com/ArctosDB/arctos/assets/2381228/db0c16e5-5c80-488d-94fe-645e630337bc)
![Screenshot 2023-09-11 at 15-56-00 Edit Bulkloader Records](https://github.com/ArctosDB/arctos/assets/2381228/176e2196-7857-4ec5-bfc9-901a64a3e974)
![Screenshot 2023-09-11 at 15-55-43 Adalberto L  Ubiñas Romero - Agent Activity](https://github.com/ArctosDB/arctos/assets/2381228/572e3294-1d78-43bd-a445-25d11c27723e)
![Screenshot 2023-09-11 at 16-02-34 Manage Agents](https://github.com/ArctosDB/arctos/assets/2381228/01a1c019-29b5-4958-9365-748f41a96a37)

# Problem
**Community response to describe the problem that caused the error**

# Solution
**Community response with directions for how to correct the problem**

**Comment by Jegelewicz** [comment]
I don't see an error - probably a timing thing?

![image](https://github.com/ArctosDB/arctos/assets/5725767/cc21da30-47bb-4276-b63f-e0c164daafe4)

**Comment by Jegelewicz** [comment]
As for data entry - you should get results with either Adalberto L. Ubiñas Romero or Adalberto L. Ubinas Romero but whatever is getting entered is something weird? A selection from Arctos agents shouldn't do that so maybe this is a bug?

**Comment by dustymc** [comment]
Try with "Adal" - if you provide enough to autoselect it'll double-encode for reasons I can't adequately investigate at the moment, so just do worse at searches. (Or ignore the selector and just provide a name in data entry - it's string-based and ignores the behind-the-scenes stuff anyway.) 

Next release (tonight) will not autoselect anything with an enye in it.

See also https://github.com/ArctosDB/arctos/issues/6694 and https://github.com/ArctosDB/arctos/issues/5270 - we really shouldn't be autoselecting anything.....

**Comment by jtgiermakowski** [comment]
Awesome, that "Adal*" trick seems to have worked. Thank you @dustymc  and @Jegelewicz  for looking at it quickly.

**Comment by jtgiermakowski** [comment]
cheers
