### ISSUE TITLE
Catalog Record Type - update to GBIF-compliant terms

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6730]
From the long issue referenced below, here's a proposal to update catalog record type to values which won't cause rejection by external sources.

current value | updateto | description 
 -- | -- | -- 
fossil specimen | FossilSpecimen | A preserved biological specimen that is a fossil. Fossil specimens are physical vouchers and are expected to include one or more non-media parts. https://dwc.tdwg.org/terms/#fossilspecimen. https://github.com/ArctosDB/arctos/issues/2432
human observation  | HumanObservation | An output of a human observation process. Human observations are unvouchered and are expected to have NO parts. https://dwc.tdwg.org/terms/#humanobservation https://github.com/ArctosDB/arctos/issues/2432
item | MaterialEntity | An entity that can be identified, exists for some period of time, and consists in whole or in part of physical matter while it exists. Equivalent to Getty "item". http://vocab.getty.edu/page/aat/300404024 | https://dwc.tdwg.org/terms/#materialsample https://github.com/ArctosDB/arctos/issues/2432
living specimen | LivingSpecimen | A biological specimen that is alive. Living specimens are physical vouchers and are expected to include one or more non-media parts. https://dwc.tdwg.org/terms/#livingspecimen https://github.com/ArctosDB/arctos/issues/2432
machine observation |MachineObservation | An output of a machine observation process. Machine observations are media vouchers and are expected to have one or more media parts. https://dwc.tdwg.org/terms/#machineobservation | https://github.com/ArctosDB/arctos/issues/2432
preserved specimen | PresevedSpecimen | A biological specimen that has been preserved. Preserved specimens are physical vouchers and are expected to include one or more non-media parts. https://dwc.tdwg.org/terms/#preservedspecimen https://github.com/ArctosDB/arctos/issues/2432
specimen | PresevedSpecimen |  [[defined above]]

_Originally posted by @dustymc in https://github.com/ArctosDB/arctos/issues/2432#issuecomment-1648238071_

-------

## EDIT

Keeping track of specifics in this comment, below this line.

---------- 

## Step One

Approve values and documentation in the table above, should probably be issues for each if someone wants to start them, or pretend I've checked my boxes and go with this....

-----
## Step Two

Specific update requests:

* https://github.com/ArctosDB/arctos/issues/6730#issuecomment-1716031286 - MSB - 'specimen'  --> 'PresevedSpecimen'
* https://github.com/ArctosDB/arctos/issues/6730#issuecomment-1716417092 -  UAM - 'specimen'  --> 'PresevedSpecimen'
* https://github.com/ArctosDB/arctos/issues/6730#issuecomment-1716484244 - DMNS - 'specimen'  --> 'PresevedSpecimen'

------

## Step Three

* Migrate whatever's left per the table above. 
    * update ``cataloged_item.cataloged_item_type``
    * update ``collection.default_cat_item_type``
    * update ``bulkloader.record_type``
    * delete old values from https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcataloged_item_type

**Comment by Jegelewicz** [comment]
I am fine with this.

**Comment by DerekSikes** [comment]
Yes! But given the possible confusion that might have happened between 'specimen' and 'preservedspecimen' - I'd like to make sure all my specimens are correctly tagged as 'preservedspecimen' and not become 'materialentity' - how do we ensure this?

**Comment by campmlc** [comment]
I vote we have a default value for a collection that is controlled via manage collection permissions, unless for some reason there are collections that use both? Leaving it up to students or even staff to understand the difference between "preservedspecimen" and "specimen" is a recipe for disaster.
@AdrienneRaniszewski @jldunnum

**Comment by dustymc** [comment]
>my specimens are correctly tagged

@DerekSikes just give me a recipe.

>default value for a collection

@campmlc we did that several years ago, https://handbook.arctosdb.org/how_to/How-to-Manage-a-Collection-in-Arctos.html and the source Issue should clear up any ambiguity, please read them.

>student accidentally choosing the wrong thing 

That's why data entry works as it does. It is up to the collections to provide access, instruction, and review.

**Comment by campmlc** [comment]
> > default value for a collection
> 
> @campmlc we did that several years ago, https://handbook.arctosdb.org/how_to/How-to-Manage-a-Collection-in-Arctos.html and the source Issue should clear up any ambiguity, please read them.

I don't see anything in the handbook link for Manage a Collection that deals with basis of record? I searched on "specimen" in the text?
> 
> > student accidentally choosing the wrong thing
> 
> That's why data entry works as it does. It is up to the collections to provide access, instruction, and review.

I found "specimen" in the bulkloader entered by students who are not under direct supervision. At last count we have over twenty students across all MSB divisions under different supervisors, entering tens of thousands of records annually. If the option to make a catastrophic error by choosing the wrong entry in a dropdown exists, it will eventually happen and slip by overworked collection staff. I happened on these records by accident. Just saying - we shouldn't make it possible for student error/staff oversight to cause catastrophic error such as loss of GBIF publication.

**Comment by campmlc** [comment]
Regardless, I support the code table update.

**Comment by campmlc** [comment]
Looks like virtually all MSB collections have records entered as "specimen" that will need to be migrated to "preserved specimen" and not "MaterialEntity".

**Comment by cjconroy** [comment]
MVZ mammals has 242569 as preserved specimen and 31 as specimen. Can I manually fix these 31?

**Comment by Jegelewicz** [comment]
> I vote we have a default value for a collection that is controlled via manage collection permissions

We do have that now? Does anyone ever actually manage their collections though?

**Comment by Jegelewicz** [comment]
> I don't see anything in the handbook link for Manage a Collection that deals with basis of record? I searched on "specimen" in the text?

https://handbook.arctosdb.org/how_to/How-to-Manage-a-Collection-in-Arctos.html#collection-defaults

We don't call it BasisOfRecord, we call it catalog_item_type

**Comment by campmlc** [comment]
So I see cataloged_item_type in the handbook, but we need to add a warning there about choosing something that will ensure publication to GBIF?
Also, currently even if we choose preservedspecimen as a collection default, a student could still override that in data entry?

**Comment by campmlc** [comment]
Maybe what we need in Manage Collection is a box to check if you wish your records to be published to GBIF. If yes, you can only select from compatible catalog item types, and those will override anything else selected during data entry?

**Comment by dustymc** [comment]
@cjconroy you can do them record by record or I can get them - see edit in initial comment.

**Comment by Jegelewicz** [comment]
> add a warning there about choosing something that will ensure publication to GBIF?

That is in the code table - https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcataloged_item_type

Scary red boxes and all!

But sure - I can add something in the How To.

**Comment by DerekSikes** [comment]
recipe = any record in any of the collections I manage with a value of 'MaterialEntity' should have that changed to 'PreservedSpecimen'

**Comment by cjconroy** [comment]
I would do the MVZ mammals, but I don't know how. Clicking all over a record and I don't see the option. But, even if I did, the table suggests that specimen changes to MaterialEntity. I am not sure we want to use that. And MaterialEntity isn't an option in data entry. Still confused. 
@mkoo

**Comment by dustymc** [comment]
>don't know how

Attributes tab
<img width="488" alt="Screenshot 2023-09-12 at 10 11 26" src="https://github.com/ArctosDB/arctos/assets/5720791/b9b87c62-99a5-49ba-893b-c4c40df08a36">

>sn't an option in data entry

See Step One [here](https://github.com/ArctosDB/arctos/issues/6730#issue-1892606074)

**Comment by dustymc** [comment]
>alue of 'MaterialEntity' should have that changed to 'PreservedSpecimen'

That's easy - there's no such thing in https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcataloged_item_type, you can't have that in your data.

>add something in the How To

The whole point of this is to make what's being requested impossible. If that proceeds, the edit just adds confusion. If that's not what we want to do here, someone please close this Issue.

**Comment by cjconroy** [comment]
MVZ mammals fixed.

**Comment by Jegelewicz** [comment]
I can re-do the How To once this is done.

**Comment by campmlc** [comment]
Can we get a list of all MSB records that have "specimen" as a value - and have them all converted to "preserved specimen" in bulk? My understanding is that the MaterialEntity conversion hasn't happened yet.

**Comment by DerekSikes** [comment]
I was being proscriptive... so AFTER these changes are made, please 

recipe = any record in any of the collections I manage with a value of 'MaterialEntity' should have that changed to 'PreservedSpecimen'

or BEFORE:

recipe = any record in any of the collections I manage with a value of 'specimen' should have that changed to 'PreservedSpecimen'

**Comment by acdoll** [comment]
> recipe = any record in any of the collections I manage with a value of 'specimen' should have that changed to 'PreservedSpecimen'

Could you do the same for the ~120K DMNS specimens as well? Thanks!

**Comment by campmlc** [comment]
And the same for all MSB "specimens" too, please!

**Comment by campmlc** [comment]
I imagine there are other collections that may be affected here - any way to get a global list so we can notify them?

**Comment by wellerjes** [comment]
Requesting a list of CHAS records that have the "specimen" value to review before they are converted.

CHAS does not have paleo or earth science migrated to Arctos yet, but we do have specimens in the Teaching collection that fall under those categories. Fossils are addressed; what is the equivalent for rocks and minerals?

**Comment by dustymc** [comment]
> CHAS records that have the "specimen" value

https://arctos.database.museum/search.cfm?guid_prefix=CHAS%3AArt%2CCHAS%3ABird%2CCHAS%3AEgg%2CCHAS%3AEH%2CCHAS%3AEnto%2CCHAS%3AES%2CCHAS%3AFish%2CCHAS%3AHerb%2CCHAS%3AHerp%2CCHAS%3AInv%2CCHAS%3AMamm%2CCHAS%3ATeach&cataloged_item_type=specimen

>equivalent for rocks and minerals

I'm not sure what's happening (or will happen) at GBIF and how (or if) that might (eventually) change the view from Arctos, but "MaterialEntity" == 'not observation' seems reasonable to me....

**Comment by mkoo** [comment]
thanks all for weighing in and cleaning stuff up-- wont regret this! (aggregators aside but from the external view too)

**Comment by Jegelewicz** [comment]
> equivalent for rocks and minerals
> > "MaterialEntity" == 'not observation' seems reasonable to me....

Yes

**Comment by dustymc** [comment]
I am going active on this, please let me know ASAP if there are any additional concerns.

**Comment by campmlc** [comment]
Did my request to update all MSB from specimen to preserved specimen go through?

**Comment by sharpphyl** [comment]
@dustymc 

Spelling error on Enter Record screen

<img width="271" alt="Screenshot 2023-10-21 at 7 27 21 AM" src="https://github.com/ArctosDB/arctos/assets/15368365/9082063f-04bc-4dba-a3a0-ea737879ffde">

**Comment by dustymc** [comment]
OMG - thanks! De-derped....

**Comment by DerekSikes** [comment]
That typo is in the table at the top of this issue too.
