### ISSUE TITLE
Code Table Request - New identification attribute: verbatim identification

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6731]
### Goal
_Describe what you're trying to accomplish. This is the only necessary step to start this process. The Committee is available to assist with all other steps. Please clearly indicate any uncertainty or desired guidance if you proceed beyond this step._

Record the identification as written that resulted in the taxon name being associated with a catalog record in a manner that makes it easy to understand.

### Context
_Describe why this new value is necessary and existing values are not._

https://github.com/ArctosDB/arctos/issues/4827#issuecomment-1710709904

It is clear from that discussion that this would be useful to a few collections (MSB, CHAS, OGL) and possibly others if they were aware of the conversation.

I understand the concept of simply using a second identification, however, our current method of ranking identifications does not allow a method for marking an identification as "verbatim" and I do not believe it is clear to anyone outside of (and perhaps even within) the Arctos community that an A {string} identification = verbatim. In addition, using an A {string} identification still requires a remark to flag the identification as "verbatim" adding to the [overburden of identification remark](https://github.com/ArctosDB/arctos/issues/4922).

The alternate that I could see to this is replacing our current identification numerical ranks with values such as accepted, unaccepted, verbatim. The numbers 2-10 have no meaning and in some ways are useless except to whoever assigned the order and knows why they assigned it unless it is laid out in the identification remark adding to the [overburden of identification remark](https://github.com/ArctosDB/arctos/issues/4922). I could argue that 0 and 1 are also meaningless to anyone but "us".

### Table
_Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table or value. This may involve multiple tables and will control datatype for Attributes. OtherID requests require BaseURL (and example) or explanation. Please ask for assistance if unsure._

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctidentification_attribute_type

### Proposed Value
_Proposed new value. This should be clear and compatible with similar values in the relevant table and across Arctos._

verbatim identification

### Proposed Definition
_Clear, complete, non-collection-type-specific **functional** definition of the value. Avoid discipline-specific terminology if possible, include parenthetically if unavoidable._

A string representing the taxonomic identification as it appeared in the original record.

 - from Darwin Core [verbatimIdentification](https://dwc.tdwg.org/terms/#dwc:verbatimIdentification)

### Collection type
_Some code tables contain collection-type-specific values. ``collection_cde`` may be found from https://arctos.database.museum/home.cfm_

N/A

#### Attribute data type
_If the request is for an attribute, what values will be allowed?
free-text, categorical, or number+units depending upon the attribute (TBA)_

free-text

#### Attribute controlled values
_If the values are categorical (to be controlled by a code table), add a link to the appropriate code table. If a new table or set of values is needed, please elaborate._

N/A

#### Attribute units
_if numerical values should be accompanied by units, provide a link to the appropriate units table._

N/A

### Priority
_Please describe the urgency and/or choose a priority-label to the right. You should expect a response within two working days, and may utilize [Arctos Contacts](https://arctosdb.org/contacts/) if you feel response is lacking._

High - we need a resolution for the incoming OGL data.

### Example Data
_Requests with clarifying sample data are generally much easier to understand and prioritize. Please attach or link to any representative data, in any form or format, which might help clarify the request._

We always list verbatim name, even if it is identical to the 'official' scientific name, and having that as 2 official identifications seems confusing not clarifying. - https://github.com/ArctosDB/arctos/issues/4827#issuecomment-1715736330

### Available for Public View
_Most data are by default publicly available. Describe any necessary access restrictions._

yes

### Helpful Actions

- [x] Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

- [x] Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

Tagging all participants in the other issue: @happiah-madson @falco-rk @campmlc @wellerjes @DerekSikes 

Others who may have an interest: @sharpphyl @genevieve-anderegg (this would be applicable to your identification order = 2 identifications)

@ArctosDB/arctos-code-table-administrators 

## Approval
_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection
_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation
_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

- [x] Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

- [x] Add or revise the code table term/definition as described above. Ensure the URL of this Issue is included in the definition.

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by happiah-madson** [comment]
> The alternate that I could see to this is replacing our current identification numerical ranks with values such as accepted, unaccepted, verbatim. 

I think this would be fine with me, too. But I'm not sure it would be okay with other users like @campmlc

> I'm not sure I yet 100% understand the use case, but approval is for eg https://github.com/ArctosDB/arctos/issues/4827#issuecomment-1715736330 - 'what the collector wrote' as more of a procedure/policy, something less than an identification.

I don't understand how that's unique to verbatim identifications. We have verbatim coordinates, and those are also 'what the collector wrote' but aren't treated as 'less than.'

> This issue will now be part of the documentation, it would be useful to elaborate on how exactly this should be used here.

We use this field like this: https://dwc.tdwg.org/terms/#dwc:verbatimIdentification

**Comment by dustymc** [comment]
>We have verbatim coordinates, and those are also 'what the collector wrote' but aren't treated as 'less than.'

Of course they are!

locality is (sorta) analogous to taxonomy - useful for discovery, often not quite what the collector said, etc. (But taxa are dynamic hypotheses and spatial data are persistent facts, so don't try to follow the analogy too far.)

collecting_event carries 'verbatim' which are less-UI-centric (and some other stuff) and is more like identifications.

If "this thing came from that place at that time" was all there was to it, there'd be no reason to have collecting events in the model.

If "that thing is a member of _Some taxon_" was all there was to it, there'd be no reason to have identifications in the model.

>We use this field like this:

That's just identification. (A bunch of DWC seems to exist to accommodate "spreadsheet databases" that can't support things like any number of complex identification, that looks like such a thing to me.)

**Comment by campmlc** [comment]
I don't think we are going to resolve this issue on philosophical arguments. What we need is something now that will allow a feasible approach to moving forward for all the collections that are involved and who have a reason and a need for this. And so far, the overwhelming consensus among actual users is for the verbatim ID attribute. I vote we add the attribute, with all the metadata, and if for some reason that needs to be turned into a separate ID down the line, all the info will be there to do so.
I checked a box.

**Comment by campmlc** [comment]
@Nicole-Ridgwell-NMMNHS does this work for you?

**Comment by Jegelewicz** [comment]
A timely post - https://discourse.gbif.org/t/using-gnparser-to-check-scientificname-entries/4145

**Comment by dustymc** [comment]
>The [scientificName](https://dwc.tdwg.org/terms/#dwc:scientificName) field, on the other hand, is strictly for proper scientific names.

That suggests Arctos should be mapping ``identification.scientific_name`` to [verbatimIdentification](https://dwc.tdwg.org/terms/#dwc:verbatimIdentification) and ``identification_taxonomy --> taxon_name.scientific_name`` to [scientificName](https://dwc.tdwg.org/terms/#dwc:scientificName) - except we can have zero or 456 (or any other number) of the latter, neither of which would then map....

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I agree that adding an attribute is the best solution. A {string} isn't great for this purpose. You still have to include something in remarks to say {string} is verbatim, and then if you don't want the misspelled or whatever id being the accepted ID and showing up in search results (and if you are not actually identifying the specimen yourself, just interpreting) you have to add a second ID in A format with a remark that you didn't actually ID the specimen, you just interpreted the original ID. That is very clunky.

**Comment by mkoo** [comment]
This issue has a resolution and CT admin approval. @dustymc please place in the appropriate milestone (Next Task, yes?)

**Comment by dustymc** [comment]
>appropriate milestone 

?? does this mean that I need to handle code table requests as part of my work?

**Comment by Jegelewicz** [comment]
Nope - this one is on me.

**Comment by mkoo** [comment]
> > appropriate milestone
> 
> ?? does this mean that I need to handle code table requests as part of my work?

no! rather I just didnt know if you're doing other stuff with this pending reboot today-- so if not Next Task, maybe somewhere in your task queue.... needs a last review

**Comment by mkoo** [comment]
sorry hit wrong button!

**Comment by Jegelewicz** [comment]
FWIW - although Dusty has checked boxes - he doesn't seem committed and I wanted to make sure his checks were meant to be there....

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/6731#issuecomment-1715868597

There was a use case that seemed defensible (if not entirely clear, but that's my problem) at the time, but there are also a lot of comments not really related to that suggesting a misunderstanding of the model. I suspect there's some planned usage that will turn out to not do what was hoped for, and I'm also hoping that my comments in this Issue (which will be a part of the documentation) will prevent that, or at least help whoever's cleaning it up understand what happened.

**Comment by Jegelewicz** [comment]
added
