### ISSUE TITLE
[external CONTACT] new locality not saving?

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#6732]
@dustymc I'm trying to create a new locality by cloning an existing one. When I hit save at first, nothing seemed to happen. I closed the form and tried again. This time it seems like it saved but I can't find the locality if I search by the ID (12111228) or spec loc.

???

**Comment by dustymc** [comment]
https://arctos.database.museum/place.cfm?action=detail&locality_id=12111228

https://arctos.database.museum/editLocality.cfm?locality_id=12111228

Chrome?

**Comment by ccicero** [comment]
@dustymc Yes-Chrome. Hmmm, so is it just a lag in showing up?

**Comment by dustymc** [comment]
There's no lag on the Arctos end, sounds like the ad company's browser caching stuff way too aggressively....

**Comment by ccicero** [comment]
Hmmm.. What ad company? In any case, seems to be saved so thanks!

**Comment by dustymc** [comment]
>What ad company

Google!
