### ISSUE TITLE
Feature Request - drop object_condition

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6733]
**Is your feature request related to a problem? Please describe.**

Object condition history is tracked. It requires significant resources in complexity and storage. The associated agent is the person pushing buttons, not the person who did something, which has caused confusion a few times. The data seem to be mostly people correcting their spelling mistakes. https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecpart_attribute_type#condition_report provides a much more robust method of tracking part condition history.  All in all, I don't think the data are useful enough to justify the expense, and I'd like to get rid of table ``object_condition`` as part of https://github.com/ArctosDB/arctos/issues/4707

The "history" link from edit parts (and probably some other places) will reveal the data. 

**Describe what you're trying to accomplish** 

Simpler system and more predictable (==better) data.

**Describe the solution you'd like**

* stash existing data here
* remove the table
* maybe help create condition report attributes or such if there's a request

**Describe alternatives you've considered**

Transfer history to the new structure if there's some compelling reason to.

**Additional context**

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._

High - imminent development.

**Comment by Jegelewicz** [comment]
## Summary

1. All current part condition text will be converted to a [condition report](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecpart_attribute_type#condition_report) part attribute
2. Part condition will no longer be a data entry or search field - going forward all of that information will be added/searched via the [condition report](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecpart_attribute_type#condition_report) part attribute
3. Part condition history may be converted to additional [condition report](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecpart_attribute_type#condition_report) part attributes if desired. This would happen on an as requested basis, or one could use whatever data download happens to create a [part attribute bulkload](https://arctos.database.museum/tools/BulkloadSpecimenPartAttribute.cfm).

Correct?

**Comment by dustymc** [comment]
## I am proposing ONLY to get rid of the automated history of part condition.



I am **_not_** proposing to get rid of condition. (See mapping in https://docs.google.com/spreadsheets/d/1jfCdsMV4e4dDU-G1guYbyLBqTfuPSNZB_1zjDXol8NU/edit#gid=0) That has been discussed a few times, most recently at the last AWG meeting (https://docs.google.com/document/d/1fKM_nC-pHv4FUnBPZCKF4FJVW2wC2CuQDrBYjdvv-3E/edit#heading=h.q3pk226foene), there is no consensus to change anything. (Even the users of the attribute like the 'attached summary.')




I can help create part attributes from the historical data, but only with guidance - everything I've checked is just "Unchecked-->unchecked" and maybe some cryptic initials and such - it does not seem useful in general, although I'm sure there's some good stuff buried in there somewhere.

If I do anything at all I will stash the data here; anything that is useful can be added as an attribute at any time.

**Comment by Jegelewicz** [comment]
glad I asked!

**Comment by dustymc** [comment]
cache:

crud, also failed, it's about 114MB compressed, suppose I'll load this (nokey_object_condition.zip) and https://github.com/ArctosDB/arctos/issues/4707#issuecomment-1751399054 (temp_last_edit_part.zip) to TACC if I have to....
