### ISSUE TITLE
Bulk editing DIA localities.

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#6734]
Is it possible to bulk edit localities that don't have locality names? We have 282 localities with a spec_locality = "Denver, Denver International Airport". One of these is our general DIA locality that covers the entire airport and we will want to keep that as is (localityID=10583650; now named "General DIA"). The rest all have specific coordinates within the airport that we received from the USDA. To prevent these from being merged at some point, I thought I could edit the spec_locality field to include the provided coordinate (e.g., "Denver, Denver International Airport (39.872508, -104.687119)"). However, it appears that you can only use the Bulk Edit Locality tool on localities with a locality_name. Is there a was to do this with just locality_ID?
To complicate this further, there are another 303 localities at DIA that have more specific spec_localities (e.g., Denver, Denver International Airport, 17L/35R; indicating a runway), but multiple sets of coordinates. These coordinates were determined based on marked locations from maps, so each of these separate localities is unique. Again, I am considering adding the coordinates to the spec_locality to prevent merging (e.g., Denver, Denver International Airport, 17L/35R (39.837801, -104.642391)). 
Let me know if there's a better way to handle this or, if not, how we can get these edited with locality_ID. Thanks

**Comment by dustymc** [comment]
Short answer is no, ids are too ephemeral to be safely used for this sort of thing.

It's really easy to add and remove temporary names, Arctos will even send you notifications. Find the localities in whatever way, click 'manage locality names.' (And remember how you got there so you can un-name them when you get the notification!)

See also https://github.com/ArctosDB/arctos/issues/2134

>so each of these separate localities is unique

Then they won't auto-merge. If you want to preserve something, a name is the proper tool - doing something other than the documentation suggests to specific locality will just make the data less accessible, and maybe encourage someone to mangle it more in a few years. (And it should be pretty trivial to draw a polygon around that runway in geolocate if you really want to get fancy with the naming...)

**Comment by acdoll** [comment]
> a name is the proper tool

I figured you might say that - I just didn't know what to call these things. I'd never clicked on the Manage Locality Names button before, so I hadn't realized how that worked. These temp_# names are a great start - some of these localities do correspond to numbers which have been added to specimen records as other_ids, so we'll work on getting those swapped in for the temporary names. Then I'll devise a sensible system for dealing with the remainders. Thanks @dustymc!

**Comment by Jegelewicz** [comment]
@acdoll I'm not sure why you are naming these? The different coordinates automatically make them unique and ineligible for merge.

**Comment by acdoll** [comment]
@Jegelewicz I'm not trying to prevent the auto-merge, I'm trying to prevent people in our collections from merging them (well, TBH, mostly me). Without close inspection, this could appear like people unintentionally just picked a different spot each time they made a new entry for the airport.
