### ISSUE TITLE
Container Bulk Move error, but seems to have worked?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6736]
I just used the upload csv function at https://arctos.database.museum/batchScan.cfm?action=saveCSV to move a bunch of containers. It seems to have worked, but when it finished I was greeted with an error:

<html><body>

ERROR_ID | C64C3BC8-DC21-4193-903162918451E08C
-- | --
ERROR_TYPE | SQL
ERROR_MESSAGE | ERROR: query returned no rows   Where: PL/pgSQL function movecontainerbybarcode(character  varying,character varying,character varying,character varying) line 69  at SQL statement
ERROR_DETAIL | Parameter types passed (4): CF_SQL_VARCHAR, CF_SQL_VARCHAR, CF_SQL_VARCHAR, CF_SQL_VARCHAR
ERROR_SQL | { call moveContainerByBarcode(?,?,?,?) }

</div>
</body>
</html>

This makes me uneasy and if the tool worked properly I shouldn't get anything but maybe "move complete"?

here is the file I used.

[temp_cache.user_sql_tbl_jegelewicz(19).csv](https://github.com/ArctosDB/arctos/files/12602182/temp_cache.user_sql_tbl_jegelewicz.19.csv)

**Comment by Jegelewicz** [comment]
I seriously don't know what priority to apply - this could be nothing, or it could be some sort of bug?

**Comment by dustymc** [comment]
Sorta-sure that's this:

<img width="234" alt="Screenshot 2023-09-13 at 15 09 00" src="https://github.com/ArctosDB/arctos/assets/5720791/3f70d703-6635-42b9-9134-c9b69bbe9dac">


https://github.com/ArctosDB/arctos/issues/4290 needs pushed through, it would have given you better errors. I'm tempted to just go direct in the name of sustainability, there's no functional change, maybe you can help guide that?

I think that's related to https://github.com/ArctosDB/arctos/issues/1689 - that form causes problems, it's clearly doing too much, a solution was approved then blocked and I don't know how to proceed, help appreciated there as well.
