### ISSUE TITLE
Feature Request - Add shipments to Accessions

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6737]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

OGL sends out kits to researchers who send back material. At the time the kits are sent, an accession is created to track them. Currently there are no shipments associated with accessions.

**Describe what you're trying to accomplish** 
_A clear and concise overview of the goals; why are you asking for this?_

Allow for tracking both outgoing and incoming shipments related to accessions.

**Describe the solution you'd like**
_How might we accomplish your goals?_

It would be nice for them to be able to track both outgoing and incoming shipments of accession material using the same shipment forms used in loan transactions.

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

Placing the shipment information in accession remarks.

**Additional context**
_Add any other context or screenshots about the feature request here._

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._

**Comment by dustymc** [comment]
MAYBE this is all on the wrong side of some super-pedantic line, still seems reasonable to me.

Here's the table - I don't see anything that doesn't work for accessions, if that's true then this should just be a matter of UI.

```

arctosprod@arctos>> \d shipment
                                                Table "core.shipment"
          Column           |            Type             | Collation | Nullable |               Default               
---------------------------+-----------------------------+-----------+----------+-------------------------------------
 container_id              | integer                     |           |          | 
 transaction_id            | integer                     |           | not null | 
 packed_by_agent_id        | integer                     |           | not null | 
 shipped_carrier_method    | character varying(25)       |           | not null | 
 carriers_tracking_number  | character varying(25)       |           |          | 
 shipped_date              | timestamp without time zone |           |          | 
 package_weight            | character varying(10)       |           |          | 
 hazmat_fg                 | smallint                    |           | not null | 
 insured_for_insured_value | numeric                     |           |          | 
 shipment_remarks          | character varying(255)      |           |          | 
 contents                  | character varying(255)      |           |          | 
 foreign_shipment_fg       | smallint                    |           | not null | 
 shipped_to_addr_id        | integer                     |           | not null | 
 shipped_from_addr_id      | integer                     |           | not null | 
 shipment_id               | integer                     |           | not null | nextval('sq_shipment_id'::regclass)
 shipment_type             | character varying(60)       |           | not null | 
Indexes:
    "shipment_pkey" PRIMARY KEY, btree (shipment_id)
    "iu_shipment_contid" UNIQUE, btree (container_id)
    "ix_shipment_transid" btree (transaction_id)
Foreign-key constraints:
    "fk_ctshipment_type" FOREIGN KEY (shipment_type) REFERENCES ctshipment_type(shipment_type)
    "fk_ctshipped_carrier_method" FOREIGN KEY (shipped_carrier_method) REFERENCES ctshipped_carrier_method(shipped_carrier_method)
    "fk_shipment_addr_shippedfrom" FOREIGN KEY (shipped_from_addr_id) REFERENCES address(address_id)
    "fk_shipment_addr_shippedto" FOREIGN KEY (shipped_to_addr_id) REFERENCES address(address_id)
    "fk_shipment_agent" FOREIGN KEY (packed_by_agent_id) REFERENCES agent(agent_id)
    "fk_shipment_container" FOREIGN KEY (container_id) REFERENCES container(container_id)
    "fk_shipment_trans" FOREIGN KEY (transaction_id) REFERENCES trans(transaction_id)
    "fk_shipment_type" FOREIGN KEY (shipment_type) REFERENCES ctshipment_type(shipment_type)
Triggers:
    trg_shipment_biu BEFORE INSERT OR UPDATE ON shipment FOR EACH ROW EXECUTE FUNCTION trigger_fct_trg_shipment_ud()

```

**Comment by Jegelewicz** [comment]
Why does it "require justification"? Isn't the use case presented enough?

**Comment by mkoo** [comment]
It's not clear to me what the proposed change is -- aside from the goal of tracking shipments in accessions -- justification is clear enough.
But...
Did you want to add shipments to an accession (presumably may be more than one), right? How would you create a shipment without creating a loan? Or am I missing something?

**Comment by Jegelewicz** [comment]
> How would you create a shipment without creating a loan? Or am I missing something?

They ship out kits for collection of tissues that are then accessioned into the collection. Effectively "loaning" a kit that becomes the accession. The kits will include barcoded cryovials! Doing it right!

**Comment by mkoo** [comment]
No, I get that part-- I understand the reason there are shipments associated with the accn-- it was clear. I just dont think you can create a shipment _in Arctos_ outside of a loan. Is that what is being asked here?  Or will loans AND shipments be created and the accession actually needs to track the loan #. (the latter would be the feature request)

**Comment by mkoo** [comment]
associating different transactions to each other (loans and accessions) doesnt seem that scary to me. But I am going to put this on the next AWG or Issues  meeting agenda since realtime discussion is needed

**Comment by dustymc** [comment]
AWG: go

**Comment by dustymc** [comment]
This is running in test, everything-ish is new, feedback is greatly appreciated. If nothing melts I will try to sprinkle this to other transactions+clean up tomorrow and get a release out tomorrow evening.

* shipments are now responsive
* the address pick form is better
* the address pick method is better (and different)
* the code is reusable

My test mule is https://arctos-test.tacc.utexas.edu/accn.cfm?action=edit&transaction_id=1001225 if that's handy.

**Comment by Jegelewicz** [comment]
Cool!

Why not

make weight a number with units from https://arctos.database.museum/info/ctDocumentation.cfm?table=ctweight_units

make value a number with units from https://arctos.database.museum/info/ctDocumentation.cfm?table=ctmonetary_units
