### ISSUE TITLE
new identifier type: Arctos record identifier for all Arctos records

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6738]
The recent conversion of all Arctos guids as identifiers to the full url is bringing up an important issue in how we designate Arctos catalog numbers within and outside of Arctos. It is important for collections to be able to designate catalog numbers as opposed to other identifier types, since this is what we require to be cited in loan agreements and publications.

Previously, any Arctos record which referenced another Arctos guid referenced the guid int the format "MSB:Mamm:12345" with the full url in adjacent column in the catalog record page. This was usually in the context of a record with relationships such as "same individual as" or "host of" or "parasite of".
Now those relationships reference the full url, e.g. "parasite of"   "https://arctos.database.museum/guid/MSB:Mamm:158132".
However, the url ID type is listed as an "identifier" issued by a given collection.

My colleagues and I at MSB support explicitly designating which identifier associated with a record is actually a formal catalog number in Arctos.  We could use "institutonal catalog number" for this. But it seems awkward to apply that the the full url, and besides, that option is not allowed by the url generator in data entry.

The other option is to enter the ID twice, once as the traditional guid format with "institutional catalog number" as the ID type, and a separate row as the url "identifier". This requires twice the data entry effort, and also we'd need to enter "parasite of" related to both types of host identifiers. 

Thoughts from the community on how to address this?

**Comment by campmlc** [comment]
Revisiting this and upping priority. We need to standardize what we mean by "GUID" for Arctos collections so that there is a standard ID type and format that can be used to link Arctos guids between records. Currently this is causing increasing chaos and problems in parasite/host and other related collections as there is no consistent standard or format or ID type.

**Comment by mkoo** [comment]
From the AWG discussion:
A new identifier would be created called ```Arctos record identifier``` which would expressly be the full URL of the Arctos record. 

The data entry form needs to reflect that users would be able to add the catalog record or DwC triple and the domain etc (```https://arctos.database.museum/guid/```) be appended. Although the builder could do that already.

Other suggested UI tweaks-- the Edit form on the record page:

![Firefox_Screenshot_2024-05-23T19-49-20 310Z](https://github.com/ArctosDB/arctos/assets/2523089/5936bcfb-07d5-47e6-b29c-77fbb640bbef)
- Change text in red circle to "Prefix or String (see Type definitions)"
- increase Integer box (I can never see the full value! at least let us see more than 4 digits)

There is also agreement that we would remove the type= "institutional catalog number" and replace with simply "identifier" and the appropriate Issued by for consistent and discoverable other ids.
