### ISSUE TITLE
Find Container weirdness

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6739]
I am using find container to look for Barcode = OGL11 and it just says "working" forever. I know it exists, because I tried creating it an get the duplicate barcode error.

Have I done something dumb to OGL11? Why can't Arctos find it?

Other searches produce results pretty quick

OGL13
Z0001

**Comment by dustymc** [comment]
Doublequotes (and probably lost of other stuff) in label seem to break the JS. I think I've mentioned a few times that the tree library is very old...

I'll try to add some duct tape if we can't find a better solution.


```

arctosprod@arctos>> select barcode from container where label like '%"%';
 barcode  
----------
 PM52
 P135X
 A7QU4
 A7QU6
 A7QU7
 A7QU5
 A6VYC
 A6VYA
 A6VY9
 A6VYB
 DGR15271
 P12QD
 P12QG
 P12QI
 P12QZ
 P29L3
 P29N4
 A7QU8
 BOWIE 10
 P29T4
 PKM3
 PKMJ
 PKMY
 PKOL
 PKOQ
 P4976
 P29N2
 OGL11
(28 rows)
```

**Comment by Jegelewicz** [comment]
Can we just disallow them from label text? I didn't even realize I had added them to OGL11 - you can remove them if that helps.

**Comment by campmlc** [comment]
Yes, I agree - and any MSB barcodes can have those removed. Do I need to do this manually?

**Comment by campmlc** [comment]
duh, I guess I can't do it manually because I can't find them. @dustymc can I use bulk edit container for this if you provide a csv?

**Comment by Jegelewicz** [comment]
OOOO - I didn't think about bulk edit! I can fix mine.

**Comment by dustymc** [comment]
WriteSQL 

```
select * from container where label like '%"%'
```

**Comment by dustymc** [comment]
* " updated to `
* " trigger-prevented
