### ISSUE TITLE
Request: additions to Loan Statistics report tool

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6740]
Request to modify the Loan Statistics report at https://arctos.database.museum/info/loanStats.cfm
 to provide the following:
1) Add column for Loan Description. Currently only Loan remarks shows up. I would like to see both, if possible, but if only one is allowed, then please replace remarks with description.
2) Allow for selection of a range of dates, or by year. Currently the report provides all loans for a given collection since the beginning of time.
3) Allow for selection of more than one collection at a time, if possible, perhaps through using control select?
4) Add back in the ability to select loan agents/roles -e.g.  I'd like all loans from 2022 for which I am in-house contact.

We used to have a tool that provided most of these functions, but that seems to have disappeared with the UI changeover?
Priority - high, needed for annual reporting and funding justification.

@dusty

**Comment by mkoo** [comment]
Agree that these are desirable/ needed filters

**Comment by Jegelewicz** [comment]
Can we set a milestone?

**Comment by dustymc** [comment]
PLEASE see the linked issue, this cannot survive what's already been done at test, I think this is just a symptom of having an unnecessary legacy form hanging around.

**Comment by mkoo** [comment]
> Can we set a milestone?
hmm, maybe new one (because I am struggling to review these properly)-- "It's complicated" or "Needs Magic/ Funding"
or what?

Also I think the functional needs remain and loan stats are not in the TURD as far as I can see....
So if you remove it (#6743) what's the plan for a replacement?

**Comment by mkoo** [comment]
ok second cup of coffee kicking in.... not TURD but our search/ manage for all transactions (https://arctos.database.museum/transactionSearch.cfm) 

Agreed that's a powerful interface. Might need a new request for some summary stats based on those search results but I see what's up now! (sorry for jumping the gun)

@campmlc the transaction search/ manage gets you what you want-- let's open a new issue if the results could be more useful
