### ISSUE TITLE
Feature Request - remove /info/loanStats.cfm

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6743]
**Is your feature request related to a problem? Please describe.**

/info/loanStats.cfm is is a subset of the data and capability available from the transaction management UI, excepting citation stats which are only incidentally related anyway.

**Describe what you're trying to accomplish** 

Simplify; remove unnecessary clutter.

**Describe the solution you'd like**

Remove /info/loanStats.cfm, which was developed before we had a unified transaction UI.

**Describe alternatives you've considered**

I don't think there are any, nor are any needed.

**Additional context**

https://github.com/ArctosDB/arctos/issues/6740

**Priority**

Perhaps critical from a UX perspective. Very tentatively going direct implementation, but please comment ASAP if I'm reading any of this wrong or anything needs discussion.

**Comment by dustymc** [comment]
Going forward with this as part of https://github.com/ArctosDB/arctos/issues/4707#issuecomment-1729983402

**Comment by mkoo** [comment]
Just for clarification: this is the robust search/manage interface to replace this tool's fxn:
https://arctos.database.museum/transactionSearch.cfm
