### ISSUE TITLE
Unable to limit identifier search to "self" relationships

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6744]
In the new search interface, we seem to have lost the ability to do a search on only those identifiers that are explicitly assigned to an individual record, and instead, an identifier search automatically pulls not only all records with a specified identifier but also all records related to records with those identifiers.
This is not clear in the interface.
Can we add back in the ability to search on "self" explicitly? Currently "self" is not an option in the search identifier relationships option. But, because that's an extra click, and many people will not know to it is necessary to do this, can we also change the default value in search to be the self relationship, and anyone who wants a broader "show me all related items" search can use relationships dropdown to do so?
Priority: High, impeding work. This is causing lots of confusion both curatorially and with researchers and loan requests.

**Comment by campmlc** [comment]
<html>
<body>
<div class="pglayout" style="margin: 0px auto; display: grid; gap: 0.2rem; border: 0.1px dotted white; grid-template-columns: repeat(4, 1fr);"><div class="schitem" id="si_custom_identifier" style="padding: 0.1rem; margin: 0.1rem;"><div class="dontwrap" style="white-space: nowrap;"><select name="customoidoper" id="customoidoper" size="1" onchange="setSessionCustomID(this.value);" class="constrained_select highlightst" style="outline: tomato solid 3px; z-index: 300; margin: 3px; max-width: 5em;"><span> </span>										<option value=""></option><span> </span>										<option value="IS">is</option><span> </span>										<option value="">contains</option><span> </span>										<option value="LIST" selected="selected">in list</option><span> </span>										<option value="BETWEEN">in range</option><span> </span>									</select><span> </span><input type="text" class="short_input" name="customidentifiervalue" id="customidentifiervalue" value="" placeholder="Custom ID"></div></div></div><table id="si_otheridsrchtbl" class="wideCollapseTable" style="border: 1px solid black; border-collapse: collapse; margin: 0px; padding: 0px;"><thead><tr><th scope="col" style="display: table-cell; font-size: 0.85em;">Identifier IssuedBy<span> </span><span title="Prefix with = for exact match" class="likeLink" onclick="var e=document.getElementById('id_issuedby');e.value='='+e.value;" style="cursor: pointer; color: var(--arctoslinkcolor);">[=]</span></th><th scope="col" style="display: table-cell; font-size: 0.85em;">Identifier Type<span> </span><span class="likeLink" onclick="getCtDoc('ctcoll_other_id_type',cat_rec_sch_frm.oidtype.value);" style="cursor: pointer; color: var(--arctoslinkcolor);">Define</span></th><th scope="col" style="display: table-cell; font-size: 0.85em;"><span title="=value for exact, value for partial, value1,value2 for comma-list">Value<span> </span></span><span title="Prefix with = for exact match" class="likeLink" onclick="var e=document.getElementById('oidnum');e.value='='+e.value;" style="cursor: pointer; color: var(--arctoslinkcolor);">[=]</span></th><th scope="col" style="display: table-cell; font-size: 0.85em;"><div title="Search numeric component of IDs (when available). 1-3 (one through three), <2 (less than 2), >2 (more than 2), or 2 (two) are accepted.">Numeric</div></th><th scope="col" style="display: table-cell; font-size: 0.85em;">References<span> </span><span class="likeLink" onclick="getCtDoc('ctid_references',cat_rec_sch_frm.id_references.value);" style="cursor: pointer; color: var(--arctoslinkcolor);">Define</span></th><th scope="col" style="display: table-cell; font-size: 0.85em;">AssignedBy<span> </span><span title="Prefix with = for exact match" class="likeLink" onclick="var e=document.getElementById('id_assignedby');e.value='='+e.value;" style="cursor: pointer; color: var(--arctoslinkcolor);">[=]</span></th></tr></thead><tbody><tr><td data-label="IssuedBy" style="color: rgb(0, 0, 0); font-family: Arial, Helvetica, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(218, 227, 243); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="text" name="id_issuedby" id="id_issuedby" value="" placeholder="Issued By" autocomplete="off" class="ac_input"></td><td data-label="Identifier Type" style="color: rgb(0, 0, 0); font-family: Arial, Helvetica, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(218, 227, 243); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><select name="oidtype" id="oidtype" style="max-width: 10em;"><span> </span>										<option value=""></option><span> </span>										 											<option value="barcode">barcode 											</option><span> </span>										 											<option value="collector number">collector number 											</option><span> </span>										 											<option value="identifier">identifier 											</option><span> </span>										 											<option value="creator number">creator number 											</option><span> </span>										 											<option value="ear tag">ear tag 											</option><span> </span>										 											<option value="field number">field number 											</option><span> </span>										 											<option value="institutional catalog number">institutional catalog number 											</option><span> </span>										 											<option value="lot number">lot number 											</option><span> </span>										 											<option value="Organism ID">Organism ID 											</option><span> </span>										 											<option value="pit tag">pit tag 											</option><span> </span>										 											<option value="preparator number">preparator number 											</option><span> </span>										 											<option value="processing number">processing number 											</option><span> </span>										 											<option value="studbook">studbook 											</option><span> </span>										 											<option value="trapline identifier">trapline identifier 											</option><span> </span>										 											<option value="trap number">trap number 											</option><span> </span>										 											<option value="vessel identifier">vessel identifier 											</option><span> </span>										 											<option value="volume ID">volume ID 											</option><span> </span>										 											<option value="AF">AF 											</option><span> </span>										 											<option value="ALAAC">ALAAC 											</option><span> </span>										 											<option value="NK">NK 											</option><span> </span>										 											<option value="ADFG: Alaska Department of Fish and Game">ADFG: Alaska Department of Fish and Game 											</option><span> </span>										 											<option value="AHRS (Alaska Heritage Resources Survey)">AHRS (Alaska Heritage Resources Survey) 											</option><span> </span>										 											<option value="Albertson College Museum of Natural History">Albertson College Museum of Natural History 											</option><span> </span>										 											<option value="Albuquerque Biopark Zoo Local ID">Albuquerque Biopark Zoo Local ID 											</option><span> </span>										 											<option value="ALMNH: Museum Expedition">ALMNH: Museum Expedition 											</option><span> </span>										 											<option value="ALMNH: Museum Staff Trip">ALMNH: Museum Staff Trip 											</option><span> </span>										 											<option value="AMMTAP: Alaska Marine Mammal Tissue Archival Project">AMMTAP: Alaska Marine Mammal Tissue Archival Project 											</option><span> </span>										 											<option value="AMNH: American Museum of Natural History">AMNH: American Museum of Natural History 											</option><span> </span>										 											<option value="ASK">ASK 											</option><span> </span>										 											<option value="BSI: Biotic Survey and Inventory">BSI: Biotic Survey and Inventory 											</option><span> </span>										 											<option value="DGR: Division of Genomic Resources (MSB)">DGR: Division of Genomic Resources (MSB) 											</option><span> </span>										 											<option value="DMNS: Denver Museum of Nature and Science">DMNS: Denver Museum of Nature and Science 											</option><span> </span>										 											<option value="DZTB: Denver Zoology Tissue Bird">DZTB: Denver Zoology Tissue Bird 											</option><span> </span>										 											<option value="DZTH: Denver Zoology Tissue Herp">DZTH: Denver Zoology Tissue Herp 											</option><span> </span>										 											<option value="DZTM: Denver Zoology Tissue Mammal">DZTM: Denver Zoology Tissue Mammal 											</option><span> </span>										 											<option value="Fort Worth Zoo">Fort Worth Zoo 											</option><span> </span>										 											<option value="GAN">GAN 											</option><span> </span>										 											<option value="IF">IF 											</option><span> </span>										 											<option value="KNRC: Koyukuk Nowitna Refuge Complex">KNRC: Koyukuk Nowitna Refuge Complex 											</option><span> </span>										 											<option value="KWP: Kenelm W. Philip Lepidoptera Collection">KWP: Kenelm W. Philip Lepidoptera Collection 											</option><span> </span>										 											<option value="Locality ID">Locality ID 											</option><span> </span>										 											<option value="MLZ: Moore Laboratory of Zoology">MLZ: Moore Laboratory of Zoology 											</option><span> </span>										 											<option value="NEON: National Ecological Observatory Network">NEON: National Ecological Observatory Network 											</option><span> </span>										 											<option value="NEON sample ID">NEON sample ID 											</option><span> </span>										 											<option value="OWMZ: Ohio Wesleyan Museum of Zoology">OWMZ: Ohio Wesleyan Museum of Zoology 											</option><span> </span>										 											<option value="UAM:Arc Locality ID">UAM:Arc Locality ID 											</option><span> </span>										 											<option value="UAM: University of Alaska Museum">UAM: University of Alaska Museum 											</option><span> </span>										 											<option value="UCM Public Education and Exhibition Collection">UCM Public Education and Exhibition Collection 											</option><span> </span>										 											<option value="UCM Synoptic Teaching Collection">UCM Synoptic Teaching Collection 											</option><span> </span>										 											<option value="USFWS: U.S. Fish and Wildlife Service">USFWS: U.S. Fish and Wildlife Service 											</option><span> </span>										 											<option value="USGS Bird Banding Laboratory (BBL)">USGS Bird Banding Laboratory (BBL) 											</option><span> </span>										 											<option value="USGS: HUC 8-digit">USGS: HUC 8-digit 											</option><span> </span>										 											<option value="U. S. National Park Service accession">U. S. National Park Service accession 											</option><span> </span>										 											<option value="U. S. National Park Service catalog">U. S. National Park Service catalog 											</option><span> </span>										 											<option value="USNM: National Museum of Natural History">USNM: National Museum of Natural History 											</option><span> </span>										 											<option value="USNPC: United States National Parasite Collection">USNPC: United States National Parasite Collection 											</option><span> </span>										 											<option value="UTF">UTF 											</option><span> </span>										 											<option value="UUID">UUID 											</option><span> </span>										 											<option value="UWYMV Frozen Tissue Collection">UWYMV Frozen Tissue Collection 											</option><span> </span>										 											<option value="UWYMV Historia Catalog Vertebrate">UWYMV Historia Catalog Vertebrate 											</option><span> </span>										 											<option value="WK">WK 											</option><span> </span>										 									</select></td><td data-label="value" style="color: rgb(0, 0, 0); font-family: Arial, Helvetica, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(218, 227, 243); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="text" name="oidnum" id="oidnum" value="" placeholder="oidnum"></td><td data-label="numeric" style="color: rgb(0, 0, 0); font-family: Arial, Helvetica, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(218, 227, 243); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="text" name="id_numeric" id="id_numeric" value="" placeholder="n-n, <n, >n, n"></td><td data-label="References" style="color: rgb(0, 0, 0); font-family: Arial, Helvetica, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(218, 227, 243); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><select name="id_references" id="id_references" size="1"><span> </span>										<option value=""></option><span> </span>										 											<option value="ate">ate</option><span> </span>										 											<option value="collected with">collected with</option><span> </span>										 											<option value="depicted as">depicted as</option><span> </span>										 											<option value="depiction of">depiction of</option><span> </span>										 											<option value="eaten by">eaten by</option><span> </span>										 											<option value="host of">host of</option><span> </span>										 											<option value="in amplexus with">in amplexus with</option><span> </span>										 											<option value="in same matrix as">in same matrix as</option><span> </span>										 											<option value="littermate or nestmate of">littermate or nestmate of</option><span> </span>										 											<option value="mate of">mate of</option><span> </span>										 											<option value="mounted with">mounted with</option><span> </span>										 											<option value="offspring of">offspring of</option><span> </span>										 											<option value="parasite of">parasite of</option><span> </span>										 											<option value="parent of">parent of</option><span> </span>										 											<option value="physically associated with">physically associated with</option><span> </span>										 											<option value="same assemblage as">same assemblage as</option><span> </span>										 											<option value="same collection as">same collection as</option><span> </span>										 											<option value="same edition as">same edition as</option><span> </span>										 											<option value="same individual as">same individual as</option><span> </span>										 											<option value="same lot as">same lot as</option><span> </span>										 											<option value="same series as">same series as</option><span> </span>										 											<option value="same set as">same set as</option><span> </span>										 											<option value="sibling of">sibling of</option><span> </span>										 									</select></td><br class="Apple-interchange-newline">
</body>
</html>

**Comment by Jegelewicz** [comment]
Agree that "self" needs to be added to the possible search terms.
