### ISSUE TITLE
Code Table Request - New Code Table: collection attributes

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6746]
# Final Disposition

Unless someone shows up with a better idea very soon, here's what I'm doing.

## Stay

These will remain where they are.

| Column | Justification |
|--------------|------------------|
|collection_cde|Used for selecting some collecting-specific things (a shortcut, not a necessity) and would be mildly inconvenient to move.|
|institution_acronym| Used for container ownership.|
|collection_id|Primary Key (internal)|
|web_link|Used, might be consolidated with cf_collection in a future update, leaving for now.|
|web_link_text|Used, might be consolidated with cf_collection in a future update, leaving for now.|
|loan_policy_url|Correctly placed.|
|guid_prefix|Correctly placed.|
|catalog_number_format|Correctly placed.|
|institution|Doesn't do anything, I'm not sure it's exposed anywhere, but probably the correct cardinality, people seem to like it, leaving for now.|
|citation|IDK what this does but seems like it should be used and the cardinality is correct here.|
|genbank_collection|Correctly placed.|
|internal_license_id|Correctly placed.|
|external_license_id|Correctly placed.|
|collection_terms_id|Correctly placed.|
|default_cat_item_type|Correctly placed.|
|preferred_identifiers|Correctly placed.|
|collection_role|Correctly placed.|
|preferred_identifier_issuers|Correctly placed.|
|collection_agent_id|New; Correctly placed.|
|cache_public_record_count|The same performance limitations that require this require it in this structure.|
|collection|nevermind, keeping this, I need something for the /collection/ UI, collections should be encouraged to update this to something less nonsensical see also https://github.com/ArctosDB/arctos/issues/6746#issuecomment-2220728109|

# Go

These will be moved to ``collection_attributes``

| Column | Attribute | Definition |HELP!!|
|--------------|------|------------|----|
|descr    |description|Former column "descr" - a description of the collection.|-|
|use_license_id|Not used.|
|geographic_description|geographic description|DWC thing.|-|
|west_bounding_coordinate|west bounding coordinate|DWC thing.|-|
|east_bounding_coordinate|east bounding coordinate|DWC thing.|-|
|north_bounding_coordinate|north bounding coordinate|DWC thing.|-|
|south_bounding_coordinate|south bounding coordinate|DWC thing.|-|
|general_taxonomic_coverage|general taxonomic coverage|DWC thing.|-|
|taxon_name_rank|taxon name rank|DWC thing.|-|
|taxon_name_value|taxon name value|DWC thing.|-|
|alternate_identifier_1|alternate identifier|DWC thing.|https://github.com/ArctosDB/arctos/issues/6746#issuecomment-2220834935|
|alternate_identifier_2|alternate identifier|DWC thing.|https://github.com/ArctosDB/arctos/issues/6746#issuecomment-2220834935|
|specimen_preservation_method|specimen preservation method|DWC thing.|-|
|time_coverage|time coverage|DWC thing.|-|
|purpose_of_collection|purpose of collection|DWC thing.|-|

--------------

### Mapping Spreadsheet

https://docs.google.com/spreadsheets/d/1wieT6LtKk6ZSjP3gABMto25y_PWftiJecVnIqcL3QIc/edit?gid=0#gid=0

 -----------

### Goal

Provide flexibility for adding information to collection metadata (manage collection)

> It would be a great efficiency if operators could save loan instruction text somewhere and be able to select it when creating loans.
> 
> I have standard text that I copy and paste into each loan (varies by wet vs dry specimen types, CT media, destructive sampling, etc). Currently, every time I create a loan I do a concurrent Loan Search to copy and paste instructions from previous loans. If we could save text somewhere and create nick names, e.g.," "UCM destructive" "UCM ethanol" etc. and use a pick list (or something similar), it would save a lot of time.

### Context

https://github.com/ArctosDB/arctos/issues/5691#issuecomment-1553405829

### Example Data

https://github.com/ArctosDB/arctos/issues/5691

@ArctosDB/arctos-code-table-administrators 

## Approval

https://github.com/ArctosDB/arctos/issues/6746#issuecomment-2190038087 - there are defined needs, there's been no action from The Community, I am proceeding.

**Comment by dustymc** [comment]
Thanks @Jegelewicz 

I think this would have to be public (and if that's not possible then let's figure the mechanism out up front, maybe it'll feed https://github.com/ArctosDB/arctos/discussions/6742).

I think this could be always/only free-text - I just can't imagine an actual use case where all collections would have trouble staying in sync, or how this might usefully involve units. (That would also be a huge simplification in implementation, usage, and expectations.) I propose we go that way until and unless some compelling use case shows up.

I'm not sure I get the need for method and determiner (mentioned in some other issue), but I also think there's not much "cost" in those so let's include them.

If all of that seems right then we'll need a migration path - here's the current table.

```

arctosprod@arctos>> \d collection
                                                                       Table "core.collection"
            Column            |          Type           | Collation | Nullable |                                       Default                                        
------------------------------+-------------------------+-----------+----------+--------------------------------------------------------------------------------------
 collection_cde               | character varying(5)    |           | not null | 
 institution_acronym          | character varying(20)   |           |          | 
 descr                        | character varying(4000) |           |          | 
 collection                   | character varying(50)   |           | not null | 
 collection_id                | integer                 |           | not null | 
 web_link                     | character varying(4000) |           |          | 
 web_link_text                | character varying(50)   |           |          | 
 genbank_prid                 | integer                 |           |          | 
 genbank_username             | character varying(20)   |           |          | 
 genbank_pwd                  | character varying(20)   |           |          | 
 loan_policy_url              | character varying(255)  |           | not null | 
 institution                  | character varying(255)  |           |          | 
 guid_prefix                  | character varying(20)   |           | not null | 
 use_license_id               | integer                 |           |          | 
 citation                     | character varying(255)  |           |          | 
 catalog_number_format        | character varying(21)   |           | not null | 
 geographic_description       | character varying(4000) |           |          | 
 west_bounding_coordinate     | integer                 |           |          | 
 east_bounding_coordinate     | integer                 |           |          | 
 north_bounding_coordinate    | integer                 |           |          | 
 south_bounding_coordinate    | integer                 |           |          | 
 general_taxonomic_coverage   | character varying(4000) |           |          | 
 taxon_name_rank              | character varying(4000) |           |          | 
 taxon_name_value             | character varying(4000) |           |          | 
 purpose_of_collection        | character varying(4000) |           |          | 
 alternate_identifier_1       | character varying(4000) |           |          | 
 alternate_identifier_2       | character varying(4000) |           |          | 
 specimen_preservation_method | character varying(4000) |           |          | 
 time_coverage                | character varying(4000) |           |          | 
 genbank_collection           | character varying       |           |          | 
 internal_license_id          | integer                 |           |          | 
 external_license_id          | integer                 |           |          | 
 collection_terms_id          | integer                 |           | not null | 
 default_cat_item_type        | character varying       |           | not null | 
 preferred_identifiers        | character varying[]     |           |          | 
 collection_role              | character varying       |           |          | generated always as (lower(replace(guid_prefix::text, ':'::text, '_'::text))) stored
 cache_public_record_count    | integer                 |           |          | 
```

**Comment by Jegelewicz** [comment]
In an effort to get the conversation moving, I am taking @dustymc comment and rolling with it. We could actually move other things currently in manage collection to attributes if this makes sense.

BUT

> **collections are agents, and agents can already carry those things**
> In any case, however I feel about it, this would indeed provide ~~a place to hide~~ an alternate place for those data. - https://github.com/ArctosDB/arctos/issues/5691#issuecomment-1553848495

What belongs in Agent and what in manage collection? I have been putting identifiers in the agents as things are published to GBIF and included in GRSciColl

Agent = [ASNHC:Mamm](https://arctos.database.museum/agent/21334572)
Collection = [ASNHC:Mamm](https://arctos.database.museum/collection/ACUNHC:Mamm)

Note the differences (some of which are NOT visible in the two public views (so maybe look at one of your own collections in edit mode).

If the agent and manage collection were more connected, perhaps we can only manage really internal stuff in manage collection? What would that "stuff" be?

**Comment by dustymc** [comment]
>What belongs in Agent and what in manage collection?

This will be a mess if that in any way involves anything arbitrary.

I want to say 'all belongs in collection' (because why in the world wouldn't it?!), but '{this} was part of {that} from {date} to {date} according to {agent}, then moved to {there} and spawned {subcollection} managed by {person}....' is native to the agent model and just not ([yet?](https://github.com/ArctosDB/arctos/discussions/6742)) possible in Attributes.

(So maybe this idea is dumb and GUM got it exactly right: collections should be core internal collection stuff - enough to allow guid_prefix to act as a pkey - and a required pointer to Agents, which might need the expansion??)

**Comment by Jegelewicz** [comment]
> and a required pointer to Agents

I think that is the key and we should decide what is included manage collection NOW that actually belongs in the agent.

BUT agents can be edited by a lot of people which can have positive and negative consequences. It has allowed me to add GBIF, GRSciColl, and NCBI identifiers to EVERY collection, even when I don't have edit access to them, but it also means that someone could remove them or change them unwittingly. I don't see this happening often and hopefully anybody with access to edit agents would know better, but it is a consideration.

**Comment by Jegelewicz** [comment]
FWIW part of collection creation on my side is making an agent for every Arctos institution and collection.

**Comment by dustymc** [comment]
>every

Pretty close...

```
select guid_prefix from collection
left outer join address on 'https://arctos.database.museum/collection/'||collection.guid_prefix=address.address
left outer join agent on address.agent_id=agent.agent_id
where agent.agent_id is null;


 guid_prefix 
-------------
 ALMNH:ES
 DGR:Bird
 DGR:Ento
 DGR:Mamm
 PSU:Mamm
 UAMObs:Art
 UNM:Geol
 ZSFQ:Herp
```

**Comment by Jegelewicz** [comment]
Thanks - Do I really need to add DGR?

 ALMNH:ES - added to the new split collections
 DGR:Bird - aren't these going away?
 DGR:Ento - aren't these going away?
 DGR:Mamm - aren't these going away?
 PSU:Mamm - this should go away https://github.com/ArctosDB/internal/issues/209
 UAMObs:Art - what is this? It doesn't have any records
 UNM:Geol - added to the agent
 ZSFQ:Herp - corrected format

**Comment by dustymc** [comment]
>Do I really need to add DGR?

That should be clear from the MOU.... (I failed in [getting rid of those collections](https://github.com/ArctosDB/arctos/issues/4634), and now apparently I've failed in failing the failing....)

>PSU:Mamm - this should go away

Is that a question or a request? Not clear from the other issue. (And something about MOUs...)

>UAMObs:Art - what is this?

Also evident from the MOU?? (Should I be able to find those? Might be a handy [collection attribute](https://github.com/ArctosDB/arctos/issues/6746)...)

@mkoo MOU....

**Comment by campmlc** [comment]
DGR needs to exist for now for legacy records and accessions, but currently does not catalog new records or issue loans. There is a possibility that may change in the future, at least for administrative functions such as tissue only accessions. 
I'm not able to follow this discussion right now due to other commitments, but can try to answer any questions later this afternoon.

**Comment by dustymc** [comment]
This would simplify https://github.com/ArctosDB/arctos/issues/7808, maybe help with https://github.com/ArctosDB/arctos/issues/7888, address https://github.com/ArctosDB/arctos/issues/7837 (but I'm not sure anyone cares, or maybe does care but not in the way I'd go, or ??)

@jldunnum has asked for something that needs this https://github.com/ArctosDB/arctos/issues/7896 and https://github.com/ArctosDB/arctos/issues/7384

I'm not getting any guidance, guess I'll go next task and do something??

**Comment by Jegelewicz** [comment]
> I'll go next task and do something??

Seems fairly straightforward? Provide the infrastructure to add attributes to manage collection with a new code table for collection attributes. Then the first request for a value in that code table would be something to meet the needs of #7384?

As for the other stuff, I think it makes sense and is maybe a bit behind the scenes?

We might also start to look at things that are currently in manage collection and transition them to attributes?

**Comment by dustymc** [comment]
>Seems fairly straightforward? 

Always does - until someone with an unexpected viewpoint shows up, I'd like to get them here BEFORE I write code if possible. 

>start to look at things that are currently in manage collection and transition them to attributes?

https://github.com/ArctosDB/arctos/issues/6746#issuecomment-1725789622 - I'd like to write that code once, or as close to it as I can get.

**Comment by dustymc** [comment]
>heck are these

unused

>only have one value

... because of the _{int} suffix in at least one case....

Anyway, those are super weird - I understood they were necessary to generate eml, now I understand that doesn't work, IDK, not terribly interested in making ANYONE - much less the collections who don't want to talk to GenBank - scroll past them at this point. If someone does mangle them they can sort out the effects (of which I believe there are none) with GenBank. I don't think they belong as "fields" if there's an alternative.

>which is the current value

Except who can limit your collection is extremely limited, and I'm not sure the history matters. I'm looking at this as simplification and flexibility, not quite the same use case as shared or public/"data" things.

>people who had roles in managing

that's in the operator log

>created

Thanks! Added some comments, could definitely use more feedback. HELP!

**Comment by Jegelewicz** [comment]
> I understood they were necessary to generate eml, now I understand that doesn't work,

It DOES work! But right now it only works ONCE. We need to figure out how to make it work any time there is an update and that needs time/money for Dave.

> that's in the operator log

No it isn't. The roles here sometimes indicate people who aren't even operators (Admins who just sign MOUs and pay invoices)

> could definitely use more feedback. HELP!

Agree

**Comment by dustymc** [comment]
>ONCE

Oh, that's relieving! So good docs and maybe a check or something.

>No it isn't.

Uhhh - yes it is??

OH - nevermind, gotcha, contacts. I'm not touching them now, but yea, next pass (and maybe the changes will lead somewhere interesting).

**Comment by Jegelewicz** [comment]
Although - it would be much easier to just add a role?

**Comment by dustymc** [comment]
These collections don't have a findable corresponding agent.

```

 guid_prefix 
-------------
 DGR:Ento
 PSU:Mamm
 UAMObs:Art

```

**Comment by dustymc** [comment]
See first comment for mapping, I'm not sure how to handle ``collection.collection``, grouped data below, advice most welcome.

```
arctosprod@arctos>> select collection,count(*) from collection group by collection order by collection;
                  collection                   | count 
-----------------------------------------------+-------
 Algae specimens                               |     2
 Algae specimens (ALA)                         |     1
 Amphibian and reptile observations            |     4
 Amphibian and reptile osteology specimens     |     1
 Amphibian and reptile specimens               |    31
 Amphibian and Reptile specimens               |     2
 Amphibian and Reptile Specimens               |     1
 Amphibian specimens                           |     2
 Anatomical preparations                       |     1
 Anthropology, History, and Ephemera artifacts |     1
 Aquatic macroinvertebrate specimens           |     1
 Archaeology                                   |     2
 Archeology                                    |     2
 Archive                                       |     1
 Archives                                      |     2
 Art                                           |     2
 Arthropod tissues                             |     1
 Bird                                          |     1
 Bird Egg/Nest Specimens                       |     1
 Bird eggs                                     |     2
 Bird eggs/nests                               |     5
 Bird observations                             |     3
 Bird Observations                             |     1
 Bird specimens                                |    37
 Bird tissues                                  |     1
 Bivalve specimens                             |     2
 Crustacean specimens                          |     1
 Cryptogam specimens (ALA)                     |     1
 Earth Science                                 |     5
 Egg and nest specimens                        |     2
 Egg specimens                                 |     1
 Entity Records                                |     1
 Entomology specimens                          |     1
 Environmental samples                         |     2
 Ethnology                                     |     1
 Ethnology and History artifacts               |     1
 Ethnology and History objects                 |     1
 Fish observations                             |     4
 Fish specimens                                |    25
 Fossil specimens                              |     4
 Gastropod specimens                           |     1
 Genomic samples                               |     2
 Geology specimens                             |    10
 Herbarium                                     |     1
 Herbarium specimens                           |     7
 History and Ethnology                         |     1
 Host observations                             |     1
 Host (of parasite) specimens                  |     2
 Image                                         |     1
 Insect observations                           |     2
 Insect specimens                              |    16
 Invertebrate Paleontology specimens           |     1
 Invertebrate specimens                        |    14
 Invertebrate Zoology                          |     2
 Lepidopteran specimens                        |     1
 Mammal Collection                             |     1
 Mammal observations                           |     6
 Mammal specimens                              |    37
 Mammal Specimens                              |     1
 Mammal tissues                                |     1
 Marine invertebrate specimens                 |     2
 Meteoritics                                   |     2
 Mineral specimens                             |     1
 Mollusc specimens                             |     2
 Observations                                  |     1
 Paleobotany Reference specimens               |     1
 Paleobotany specimens                         |     1
 Paleontology Library                          |     1
 Paleontology specimens                        |     7
 Parasite Collection                           |     1
 Parasite specimens                            |    11
 Plant observations                            |     1
 Plant Observations                            |     1
 Plant specimens                               |     8
 Plant specimens (ALA)                         |     1
 PSU Mamm                                      |     1
 Reptile specimens                             |     3
 Teaching and Education specimens              |     4
 Teaching specimens                            |     9
 UAM:Art observations and proposed donations   |     1
 UAM:EH observations and proposed donations    |     1
 Vertebrate observations                       |     1
 Vertebrate Paleontology specimens             |     1
 Vertebrate specimens                          |     1
 Zooarchaeological comparative specimens       |     1
 Zooplankton specimens                         |     1
```

**Comment by dustymc** [comment]
These should probably be moved to the collection-agent, and that can be done any time post-migration.

```

arctosprod@arctos>> select guid_prefix,alternate_identifier_1 from collection where alternate_identifier_1 is not null;
 guid_prefix |                                                       alternate_identifier_1                                                       
-------------+------------------------------------------------------------------------------------------------------------------------------------
 ALMNH:ES    | AMNH; UAM; PV; PI; PB; G
 UWYMV:Egg   | http://ipt.vertnet.org:8080/ipt/resource?r=uwymv_egg
 ACUNHC:Mamm | https://csvcoll.org/portal/collections/misc/collprofiles.php?collid=1029
 UNR:Bird    | UN
 UNR:Mamm    | UN
 OWU:Inv     | OWMZ
 CRCM:Paleo  | CRCM-##-#####
 ALMNH:Paleo | AMNH; UAM; PV; PI; PB
 UNR:Herp    | UN
 NMMNH:Paleo | NMMNH P-
 UTEP:Inv    | MALB
 ALMNH:Mamm  | ZV; M-
 CRCM:Mamm   | CRCM-##-#####
 NMMNH:Herb  | NMMNH
 OWU:ES      | OWUM
 OWU:Rept    | OWMZ
 UWYMV:Fish  | Historically known with the following acronyms and names: UW; University of Wyoming Vertebrate Museum
 OWU:Mamm    | OWMZ
 OGL:Genomic | OGL:OGR
 UTEP:Herb   | http://arctos.database.museum/utep_herb
 CRCM:Bird   | CRCM-##-#####
 CRCM:Fish   | CRCM-##-#####
 UNR:Egg     | UN
 OWU:Bird    | OWMZ
 MSB:Fish    | Catalog Number
 UWYMV:Bird  | Historically known with the following acronyms and names: UW; University of Wyoming Vertebrate Museum
 UWYMV:Herp  | Historically known with the following acronyms and names: UW; University of Wyoming Vertebrate Museum
 UNM:MET     | <a href="https://www.lpi.usra.edu/meteor/MetBullCollectionInfo.php?coll=UNM" target="_blank">Meteoritical Bulletin Information</a>
 CRCM:Herp   | CRCM-##-#####
 UNR:Fish    | UN
 OWU:Para    | OWMZ
 OWU:Fish    | OWMZ
 OWU:Ento    | OWMZ
 MMNH:Mamm   | MIN
 UWYMV:Mamm  | Historically known with the following acronyms and names: UW; University of Wyoming Vertebrate Museum
 OWU:Amph    | OWMZ
(36 rows)

Time: 2.111 ms
arctosprod@arctos>> select guid_prefix,alternate_identifier_2 from collection where alternate_identifier_2 is not null;
 guid_prefix |                                        alternate_identifier_2                                         
-------------+-------------------------------------------------------------------------------------------------------
 UWYMV:Egg   | Historically known with the following acronyms and names: UW; University of Wyoming Vertebrate Museum
 UNR:Bird    | RENO
 UNR:Mamm    | RENO
 ALMNH:Paleo | ALMNH:ES
 UNR:Herp    | RENO
 NMMNH:Herb  | NMMNH&S
 UTEP:Herb   | http://ipt.vertnet.org:8080/ipt/resource?r=utep_herb 
 UNR:Egg     | RENO
 UNR:Fish    | RENO
(9 rows)
```

**Comment by dustymc** [comment]
For posterity: The Plan didn't survive implementation, templates don't actually mix with collection attributes very well, I'm putting them in a dedicate place ``collection_templates``

**Comment by Jegelewicz** [comment]
I literally do not know what is happening here and why this has become actionable? Who said go? @mkoo we can't even test anything, so I say this needs to get held for now.
