### ISSUE TITLE
Code Table Request - new informal lithostratigraphy: Blacks Fork A

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6747]
### Goal
_Describe what you're trying to accomplish. This is the only necessary step to start this process. The Committee is available to assist with all other steps. Please clearly indicate any uncertainty or desired guidance if you proceed beyond this step._

Create terms for use in informal lithostratigraphy as per incoming collection request. See https://github.com/ArctosDB/arctos/issues/6707

### Context
_Describe why this new value is necessary and existing values are not._

https://github.com/ArctosDB/arctos/issues/6707

### Table
_Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table or value. This may involve multiple tables and will control datatype for Attributes. OtherID requests require BaseURL (and example) or explanation. Please ask for assistance if unsure._

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlithostratigraphic_informal

### Proposed Value
_Proposed new value. This should be clear and compatible with similar values in the relevant table and across Arctos._

~~Blacks Fork A~~

~~A unit of Blacks Fork Member~~

Blacks Fork Member unit A - https://github.com/ArctosDB/arctos/issues/6747#issuecomment-1751438103

### Proposed Definition
_Clear, complete, non-collection-type-specific **functional** definition of the value. Avoid discipline-specific terminology if possible, include parenthetically if unavoidable._

~~https://en.wikipedia.org/wiki/Bridger_Formation~~

Blacks Fork A of Blacks Fork Member of Bridger Formation as described in Murphey and Evanoff 2011. https://arctos.database.museum/publication/10011992. See also https://github.com/ArctosDB/arctos/issues/6747#issuecomment-1730224788 | https://github.com/ArctosDB/arctos/issues/6747

### Collection type
_Some code tables contain collection-type-specific values. ``collection_cde`` may be found from https://arctos.database.museum/home.cfm_

N/A

#### Attribute data type
_If the request is for an attribute, what values will be allowed?
free-text, categorical, or number+units depending upon the attribute (TBA)_

N/A

#### Attribute controlled values
_If the values are categorical (to be controlled by a code table), add a link to the appropriate code table. If a new table or set of values is needed, please elaborate._

N/A

#### Attribute units
_if numerical values should be accompanied by units, provide a link to the appropriate units table._

N/A

### Priority
_Please describe the urgency and/or choose a priority-label to the right. You should expect a response within two working days, and may utilize [Arctos Contacts](https://arctosdb.org/contacts/) if you feel response is lacking._

### Example Data
_Requests with clarifying sample data are generally much easier to understand and prioritize. Please attach or link to any representative data, in any form or format, which might help clarify the request._

### Available for Public View
_Most data are by default publicly available. Describe any necessary access restrictions._

### Helpful Actions

- [x] Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

- [x] Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

@ArctosDB/arctos-code-table-administrators 

## Approval
_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval https://github.com/ArctosDB/arctos/issues/6747#issuecomment-1751438103
- [ ] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection
_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation
_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

- [ ] Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

- [ ] Add or revise the code table term/definition as described above. Ensure the URL of this Issue is included in the definition. URLs should be included *_as text_*, separated by spaced pipes. Do not include HTML in definitions.

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by Jegelewicz** [comment]
FWIW holding off on these until we get a resolution here

Blacks Fork B
Blacks Fork B2
Blacks Fork B3
Blacks Fork B4
Blacks Fork B5
Blacks Fork C

**Comment by dustymc** [comment]
>I think we need to show where this is "consistently used in the literature".

I was just heading over here with that exact request! Hard agree, all of these should have some sort of a reference to a "type publication" (maybe ideally an Arctos URL - local and not very prone to linkrot is nice).

**Comment by Jegelewicz** [comment]
@KatherineLAnderson @Nicole-Ridgwell-NMMNHS @WaigePilson

**Comment by KatherineLAnderson** [comment]
Here is a good reference about the Bridger formation, and attaching a screenshot of Figure 2 which shows "Blacks Forks A" and all the other subunits in a nifty little visual.

https://www.researchgate.net/publication/297943742_Paleontology_and_stratigraphy_of_the_middle_Eocene_Bridger_Formation_southern_Green_River_Basin_Wyoming

![History-of-Bridger-Formation-stratigraphic-nomenclature-Bridger-from-1869-until-present_W640](https://github.com/ArctosDB/arctos/assets/27514212/1e441c43-9be6-4324-93e3-c339d4000da0)

**Comment by dustymc** [comment]
@KatherineLAnderson that's awesome.

So would the *term* be

* Blacks Fork A
* Blacks Fork A of Blacks Fork Member
* Blacks Fork A of Blacks Fork Member of Bridger Formation


???? (Not sure I have much opinion, but I read definitions!)

And a definition (with an eye towards https://github.com/ArctosDB/internal/issues/284) of something like 

>Blacks Fork A of Blacks Fork Member of Bridger Formation as described in Murphey and Evanoff 2007.  {maybe something about states or whatever???} https://en.wikipedia.org/wiki/Bridger_Formation | https://www.researchgate.net/publication/297943742_Paleontology_and_stratigraphy_of_the_middle_Eocene_Bridger_Formation_southern_Green_River_Basin_Wyoming

(And I'm not sure that wiki link is necessary, doesn't seem terribly informative.)

Yay?

**Comment by dustymc** [comment]
Oh - and you might think about requesting better keys before you get too serious about part-JSON-stuff. https://github.com/ArctosDB/arctos/issues/2131#issuecomment-1595202679

**Comment by KatherineLAnderson** [comment]
That gets a yay from me!

**Comment by KatherineLAnderson** [comment]
> @KatherineLAnderson that's awesome.
> 
> So would the _term_ be
> 
>     * Blacks Fork A
> 
>     * Blacks Fork A of Blacks Fork Member
> 
>     * Blacks Fork A of Blacks Fork Member of Bridger Formation
> 
> 
> ???? (Not sure I have much opinion, but I read definitions!)
> 
> And a definition (with an eye towards [ArctosDB/internal#284](https://github.com/ArctosDB/internal/issues/284)) of something like
> 
> > Blacks Fork A of Blacks Fork Member of Bridger Formation as described in Murphey and Evanoff 2007.  {maybe something about states or whatever???} https://en.wikipedia.org/wiki/Bridger_Formation | https://www.researchgate.net/publication/297943742_Paleontology_and_stratigraphy_of_the_middle_Eocene_Bridger_Formation_southern_Green_River_Basin_Wyoming
> 
> (And I'm not sure that wiki link is necessary, doesn't seem terribly informative.)
> 
> Yay?



> 
> So would the _term_ be
> 
>     * Blacks Fork A
> 
>     * Blacks Fork A of Blacks Fork Member
> 
>     * Blacks Fork A of Blacks Fork Member of Bridger Formation
> 

All of these are correct.

**Comment by Jegelewicz** [comment]
> All of these are correct

Agree - but which would be best as the term in the table?

**Comment by KatherineLAnderson** [comment]
> > All of these are correct
> 
> Agree - but which would be best as the term in the table?

Blacks Fork A of Blacks Fork Member of Bridger Formation 

it's the most specific, so probably the best (albeit a little long).

**Comment by dustymc** [comment]
For future reference: https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html#specific-values-considerations

**Comment by KatherineLAnderson** [comment]
Can this be applied for all the issues for Blacks Fork and Twin Butte subunits?

This one is open: https://github.com/ArctosDB/arctos/issues/6752

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Do we need "Blacks Fork A of Blacks Fork Member of Bridger Formation if that information is reflected in the definition? Presumably these localities will already have attributes Blacks Fork Member and Bridger Formation.

I like the definition Dusty proposed, but for the publication, since this one does not have a DOI, we should add it as a publication to Arctos (put the research gate link in the publication remark) and the link we use in the definition should be to the Arctos publication record. That way we're linking to the full citation information and not relying on a research gate link that could go defunct at any time.

**Comment by dustymc** [comment]
>Do we need "Blacks Fork A of Blacks Fork Member of Bridger Formation if that information is reflected in the definition? 

No strong opinions from me. I do keep hearing that people can't be bothered with definitions, but hopefully that was just a bad joke that I took too seriously...


>add it as a publication to Arctos

Definitely my preference, but I suppose I understand if that's just not practical. (Or: These are Authorities, there's nothing more important, I will make time to do that if nobody else can. IDK!)

**Comment by Jegelewicz** [comment]
Publication added - https://arctos.database.museum/publication/10011992

**Comment by Jegelewicz** [comment]
Also cleaned up Paul C. Murphey agents - woo hoo!

**Comment by Jegelewicz** [comment]
@KatherineLAnderson @Nicole-Ridgwell-NMMNHS @WaigePilson @dustymc are we ok with the revised request (first comment)?

**Comment by dustymc** [comment]
I still like - and can/should we [standardize](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html#specific-values-considerations) that "formal bits" go at least to formation? (Or maybe that's unnecessary and ' of Bridger Formation' could be removed??)

**Comment by KatherineLAnderson** [comment]
Sounds good to me! I think as long as it has the next highest formal unit (e.g., of Blacks Fork member) which would be nested into higher order terms, we probably don't need to list those higher order terms (e.g., of Bridger formation in this case).

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> as long as it has the next highest formal unit

agreed.

**Comment by dustymc** [comment]
>next highest formal unit

Thx, documentation updated.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Checking box for Blacks Fork A of Blacks Fork Member

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Sorry, I missed where this was changed to "A unit of Blacks Fork Member" unchecked because I'm not sure if this works. Looking at this out of context I would read "A" as an article not as the designator for the unit.

**Comment by Jegelewicz** [comment]
Yeah - just trying to stick to informal = lowercase and it isn't working out very well.

unit A of Blacks Fork member?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> unit A of Blacks Fork member

Yes, that is better.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
It also lines up with the format used in https://github.com/ArctosDB/arctos/issues/6750

**Comment by Jegelewicz** [comment]
OK - before I add this. @KatherineLAnderson @WaigePilson are you OK with 

unit A of Blacks Fork Member - Blacks Fork A of Blacks Fork Member of Bridger Formation as described in Murphey and Evanoff 2011. https://arctos.database.museum/publication/10011992 | https://github.com/ArctosDB/arctos/issues/6747

**Comment by Jegelewicz** [comment]
Added as consistent with other units.
