### ISSUE TITLE
Code Table Request - new informal lithostratigraphy: lower unit of Fremouw Formation

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6748]
### Goal
_Describe what you're trying to accomplish. This is the only necessary step to start this process. The Committee is available to assist with all other steps. Please clearly indicate any uncertainty or desired guidance if you proceed beyond this step._

Create terms for use in informal lithostratigraphy as per incoming collection request. See https://github.com/ArctosDB/arctos/issues/6707

### Context
_Describe why this new value is necessary and existing values are not._

#6707 

### Table
_Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table or value. This may involve multiple tables and will control datatype for Attributes. OtherID requests require BaseURL (and example) or explanation. Please ask for assistance if unsure._

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlithostratigraphic_informal

### Proposed Value
_Proposed new value. This should be clear and compatible with similar values in the relevant table and across Arctos._

~~lower member of Fremouw Formation~~

lower unit of Fremouw Formation - https://github.com/ArctosDB/arctos/issues/6753#issuecomment-1755951617

### Proposed Definition
_Clear, complete, non-collection-type-specific **functional** definition of the value. Avoid discipline-specific terminology if possible, include parenthetically if unavoidable._

~~https://en.wikipedia.org/wiki/Fremouw_Formation~~

The Fremouw Formation can be subdivided into three informal members. The lower member consists of coarse to medium-grained, trough cross-bedded, channel-form sandstone units alternating with equally thick fine-grained units of fine to very fine-grained sandstone, silstone and mudstone . - Institute of Polar Studies Report 87 | https://kb.osu.edu/bitstream/handle/1811/48692/IPS_Report_87_Part1.pdf?sequence=2) | https://github.com/ArctosDB/arctos/issues/6748

### Collection type
_Some code tables contain collection-type-specific values. ``collection_cde`` may be found from https://arctos.database.museum/home.cfm_

N/A

#### Attribute data type
_If the request is for an attribute, what values will be allowed?
free-text, categorical, or number+units depending upon the attribute (TBA)_

N/A

#### Attribute controlled values
_If the values are categorical (to be controlled by a code table), add a link to the appropriate code table. If a new table or set of values is needed, please elaborate._

N/A

#### Attribute units
_if numerical values should be accompanied by units, provide a link to the appropriate units table._

N/A

### Priority
_Please describe the urgency and/or choose a priority-label to the right. You should expect a response within two working days, and may utilize [Arctos Contacts](https://arctosdb.org/contacts/) if you feel response is lacking._

### Example Data
_Requests with clarifying sample data are generally much easier to understand and prioritize. Please attach or link to any representative data, in any form or format, which might help clarify the request._

### Available for Public View
_Most data are by default publicly available. Describe any necessary access restrictions._

### Helpful Actions

- [x] Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

- [x] Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

@ArctosDB/arctos-code-table-administrators 

## Approval
_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection
_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation
_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

- [ ] Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

- [ ] Add or revise the code table term/definition as described above. Ensure the URL of this Issue is included in the definition. URLs should be included *_as text_*, separated by spaced pipes. Do not include HTML in definitions.

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by dustymc** [comment]
Why isn't this just https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlithostratigraphic_formation? (And I'm guessing the answer will be useful in https://github.com/ArctosDB/arctos/issues/6747, which at the moment feels more slippery than I'd anticipated....)

**Comment by Jegelewicz** [comment]
It is possible that a better term would be

Fremouw Formation Lower Member

**Comment by Jegelewicz** [comment]
@KatherineLAnderson @Nicole-Ridgwell-NMMNHS @WaigePilson

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Cool! Antarctic geology!

I'm iffy about this one as well. I'm guessing this unit hasn't been well studied enough to describe formal members. My normal course of action would be a remark in the Formation attribute.

**Comment by dustymc** [comment]
Is "lower unit of Fremouw Formation" accurate? It's more in line with the emerging pattern, won't trick me into asking questions like the above (by avoiding Formal Sounding Things), and follows the terminology used in the linked wiki article. Copy-paste that to the definition, maybe throw in something about Antarctica, and this looks OK to me, unless I'm now even loster that I used to be....

**Comment by Jegelewicz** [comment]
@dustymc @KatherineLAnderson @Nicole-Ridgwell-NMMNHS @WaigePilson can we go with what is currently in the first comment?

**Comment by dustymc** [comment]
>first comment?

My being confused?

FWIW I still like the "informal bit of some formal thing" pattern, assuming it survives exposure to reality.

**Comment by Jegelewicz** [comment]
> "informal bit of some formal thing"

That is what is there?

Lower Member of Fremouw Formation

**Comment by dustymc** [comment]
Oh THAT first - **maybe** the Proper Case is too proper, otherwise I like.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I _think_ it should be "lower member of Fremouw Formation", but I'll let @KatherineLAnderson and @WaigePilson decide that.

**Comment by KatherineLAnderson** [comment]
^Agree with Nicole.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
box checked

**Comment by dustymc** [comment]
"lower unit of Fremouw Formation" because https://github.com/ArctosDB/arctos/issues/6753#issuecomment-1756008075 ??

**Comment by Jegelewicz** [comment]
added under special consideration BUT

Looking at what is in the code table now: 

![image](https://github.com/ArctosDB/arctos/assets/5725767/09f22d9c-357b-487e-9428-c1b09094884d)

- I wonder if this might be better?

Fremouw Formation lower unit
Fremouw Formation middle unit
Fremouw Formation upper unit
Lashly Formation C unit

Before these get used - please let me know your thoughts! @KatherineLAnderson @WaigePilson @Nicole-Ridgwell-NMMNHS @dustymc

**Comment by dustymc** [comment]
The sort might be nice, but no real opinion from me.

**Comment by Jegelewicz** [comment]
OK - rules for terms:

Start with the "formal" litho then follow with the "informal" in lowercase (except for letter designations like "unit C"

Good?

**Comment by dustymc** [comment]
I like. Update https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html#informal-lithostratigraphy please.

**Comment by Jegelewicz** [comment]
Done
