### ISSUE TITLE
Code Table Request - new informal lithostratigraphy: Member A of Lashley Formation

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6749]
### Goal
_Describe what you're trying to accomplish. This is the only necessary step to start this process. The Committee is available to assist with all other steps. Please clearly indicate any uncertainty or desired guidance if you proceed beyond this step._

Create terms for use in informal lithostratigraphy as per incoming collection request. See https://github.com/ArctosDB/arctos/issues/6707

### Context
_Describe why this new value is necessary and existing values are not._

#6707 

### Table
_Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table or value. This may involve multiple tables and will control datatype for Attributes. OtherID requests require BaseURL (and example) or explanation. Please ask for assistance if unsure._

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlithostratigraphic_informal

### Proposed Value

~~member A of the Lashly Formation~~

Lashley Formation unit A

### Proposed Definition

```
The Lashly Formation was subdivided into informal members (A, B, C and D) in Barrett, P.J. and Kohn, B.P. (1975) Changing sediment transport directions from Devonian t o Triassic in the Beacon Supergroup of south Victoria Land, Antarctica In: Campbell, K.S.W. (Ed.), Gondwanan geology. Canberra, Australian National Univ. Press, pp. 329-332.  | https://github.com/ArctosDB/arctos/issues/6749
```

### Collection type
_Some code tables contain collection-type-specific values. ``collection_cde`` may be found from https://arctos.database.museum/home.cfm_

N/A

#### Attribute data type
_If the request is for an attribute, what values will be allowed?
free-text, categorical, or number+units depending upon the attribute (TBA)_

N/A

#### Attribute controlled values
_If the values are categorical (to be controlled by a code table), add a link to the appropriate code table. If a new table or set of values is needed, please elaborate._

N/A

#### Attribute units
_if numerical values should be accompanied by units, provide a link to the appropriate units table._

N/A

### Priority
_Please describe the urgency and/or choose a priority-label to the right. You should expect a response within two working days, and may utilize [Arctos Contacts](https://arctosdb.org/contacts/) if you feel response is lacking._

### Example Data
_Requests with clarifying sample data are generally much easier to understand and prioritize. Please attach or link to any representative data, in any form or format, which might help clarify the request._

### Available for Public View
_Most data are by default publicly available. Describe any necessary access restrictions._

### Helpful Actions

- [x] Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

- [x] Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

@ArctosDB/arctos-code-table-administrators 

## Approval
_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [ ] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection
_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation
_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

- [ ] Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

- [ ] Add or revise the code table term/definition as described above. Ensure the URL of this Issue is included in the definition. URLs should be included *_as text_*, separated by spaced pipes. Do not include HTML in definitions.

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by Jegelewicz** [comment]
I think this should be more specific and the term should be:

**Lashly Formation Member A**

The referenced article does not mention "Lashly Formation member A" as far as I can tell (paywall and all), although it does mention "Previously established informal members B, C, and D of the Lashly Formation". Can we actually find where member A is published in the literature?

**Comment by dustymc** [comment]
I don't like your definition (especially the part where it's behind a paywall - and there you are a minute ahead of me...) - I think these need to contain some verbiage/summary/description/something (and that could maybe be formalized as guidance at some point).

**Comment by Jegelewicz** [comment]
@KatherineLAnderson @Nicole-Ridgwell-NMMNHS @WaigePilson

**Comment by WaigePilson** [comment]
> especially the part where it's behind a paywall

OK, I think we need to take a step back and really evaluate this code table in this case! So so so much of scientific literature is behind a paywall--that's a huge argument for another forum. But we cannot simultaneously say "wikipedia is not sufficient" and "articles cannot be behind a paywall" because then we will have no sources for any of the stratigraphic units we are trying to define.

Separately/relatedly I would argue that wikipedia is a fine source in these cases. A) because if the unit were formally defined enough to have a type section and publication describing it, then it would likely be in geolex and B) because we accept wikipedia for many other code tables in Arctos (can't think of specific examples off the top of my head, but I'm sure we have used them in our recent work adding Burke values).

**Comment by dustymc** [comment]
@WaigePilson I don't think *any* URL is by itself sufficient, I'm just asking for a bit of a summary to go along with the URL. (And maybe that could be my problem if the URL is a webservice or something, but I don't think that's the case here.)

If I have to pick between a paywall and Wiki I suppose I'll take wiki - assuming the article is about the term in question, but a bunch of these don't quite seem to be.

In any case the definition of these is "consistently used in the literature" so I'd think there'd be something like a 'type publication' (that thing that the literature *_consistently_* refers to, whatever form it might take).

**Comment by WaigePilson** [comment]
> In any case the definition of these is "consistently used in the literature" so I'd think there'd be something like a 'type publication' (that thing that the literature __consistently__ refers to, whatever form it might take).

A type section would certainly make whatever stratigraphic unit we are describing "official" enough to be in the non-informal tables in Arctos, so the examples we are giving to add to this informal table will not have published type sections (unless I'm seriously misunderstanding here).

@KatherineLAnderson @Nicole-Ridgwell-NMMNHS--Katie and I were just talking about this. It feels like there is still a lot of resistance to the idea of an informal stratigraphy table, and I am leaning back to the idea of putting these terms into remarks. The number of questions and threads on this topic is getting a little out of hand for what I can handle, and it seems like the documentation needed for each term is beyond what we will be able to find (if we are looking for published literature defining these units). What do you two think?

**Comment by dustymc** [comment]
>published type sections

I don't think it needs to be that formal. "Bla part of something else as understood/hinted at/defined/whatever in somepublication" is about what I was thinking we'd end up with.

>lot of resistance

I hope you're not seeing that from me, and I apologize if so! I do think the idea should be (however loosely) definable - it should not be some *_entirely_* arbitrary list - but I thought we'd established what that means in https://github.com/ArctosDB/arctos/issues/6707. Here I'm just looking for something more informative than a link I can't access!

**Comment by KatherineLAnderson** [comment]
See this reference: https://www.jstor.org/stable/24102383

Which includes a stratigraphic column that includes Member A of the Lashly Formation:

![Screen Shot 2023-09-22 at 12 57 41 PM](https://github.com/ArctosDB/arctos/assets/27514212/8e394a3f-cb30-4002-b44c-404255022c2f)

Also mentioned in Issue https://github.com/ArctosDB/arctos/issues/6750

(I don't even want to get into the paywall issue.)

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I think https://arctos.database.museum/info/ctDocumentation.cfm?table=ctbiostratigraphic_zone might be a good model for what we should try to do here in terms of documentation. A bit of text for anyone that might not want or be able to access the linked article, and a linked article (DOI or arctos pub link) that describes the unit. Trying to find a 'type' publication is overkill. Paywall stinks but it is a reality. The link is a pointer - here is where there is more information. The user can figure out how to access that information if it is important to them. Its not useful if it is a dead link or it points to a wikipedia article that doesn't have more information. For data migration time's sake, if the documentation needs to cleaned up afterward, I think that is fine.

In terms of approving this term, that article works. It does mention member A (https://www.researchgate.net/profile/David-Elliot-3/publication/259408666_Triassic_and_Jurassic_strata_at_Coombs_Hills_south_Victoria_Land_Stratigraphy_petrology_and_cross-cutting_breccia_pipes/links/56b8cb8208ae0a89c12f8a61/Triassic-and-Jurassic-strata-at-Coombs-Hills-south-Victoria-Land-Stratigraphy-petrology-and-cross-cutting-breccia-pipes.pdf)

**Comment by dustymc** [comment]
> A bit of text for anyone that might not want or be able to access the linked article, and a linked article (DOI or arctos pub link) that describes the unit.

Yes.

> Trying to find a 'type' publication is overkill.

I think that's just me being unclear. I'm asking for what you're asking for, I think. The type was created for "consistently used in literature" so it seem to me that we ought to be able to find some article that "defines" or describes the thing in some however-flaky way.

The paywall seems tolerable (never desirable) if there's some description. I was complaining about the ONLY information being "A" and "give us thirty bucks to find out more."

"Member A of the Lashly Formation" is infinitely more descriptive. I think we've settled on that (rather than plain ol' 'A') for the terms, and from my perspective it's enough of a 'definition' too - I can know we're not talking about Member A of the Somethingelse Thingee without shelling out $30, that seems like a reasonable minimum to me.

Yes https://arctos.database.museum/info/ctDocumentation.cfm?table=ctbiostratigraphic_zone is nice (short description, pointer to more) - EXCEPT - https://github.com/ArctosDB/internal/issues/284, 

``
A middle Anisian ammonite range zone in North America. <a href="https://doi.org/10.3133/pp1207" class="external">Silberling and Nichols 1982</a>. <a href="https://github.com/ArctosDB/arctos/issues/6322" class="external">Github</a>.
``

keeps finding INTERESTING ways to terrify me, unless there's some absolutely compelling reason to do that (in which case I'm going to propose more restricted access) let's go with


``
A middle Anisian ammonite range zone in North America. https://doi.org/10.3133/pp1207 | https://github.com/ArctosDB/arctos/issues/6322
``

(Or something that doesn't introduce the possibility of malformed HTML eating the notification system.)

I've updated the original comment, hopefully we're all on the same page now....

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> absolutely compelling reason

No. I've been using the links builder tool which I thought was what I was supposed to do.

**Comment by KatherineLAnderson** [comment]
> "Member A of the Lashly Formation" is infinitely more descriptive. I think we've settled on that (rather than plain ol' 'A') for the terms, and from my perspective it's enough of a 'definition' too - I can know we're not talking about Member A of the Somethingelse Thingee without shelling out $30, that seems like a reasonable minimum to me.
> 

I'm good with that. 

Sorry for the misunderstanding, I never intended to just put "Member A" in this table without a higher term--I didn't know how the higher terms would be incorporated when I start the initial discussion of this code table and the values that would go into it.

**Comment by KatherineLAnderson** [comment]
Looks like Member C of Lashly Formation made it into the code table, but not Member A. What additional information is needed?

**Comment by Jegelewicz** [comment]
added - I think that we have agreement even without boxes being checked.

**Comment by Jegelewicz** [comment]
> Could we update to remove the E in this one?

Whew! It hadn't been used, so I updated it. Thanks!
