### ISSUE TITLE
Code Table Request - informal lithostratigraphy: Member C

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6750]
### Goal
_Describe what you're trying to accomplish. This is the only necessary step to start this process. The Committee is available to assist with all other steps. Please clearly indicate any uncertainty or desired guidance if you proceed beyond this step._

Create terms for use in informal lithostratigraphy as per incoming collection request. See https://github.com/ArctosDB/arctos/issues/6707

### Context
_Describe why this new value is necessary and existing values are not._

#6707 

### Table
_Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table or value. This may involve multiple tables and will control datatype for Attributes. OtherID requests require BaseURL (and example) or explanation. Please ask for assistance if unsure._

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlithostratigraphic_informal

### Proposed Value
_Proposed new value. This should be clear and compatible with similar values in the relevant table and across Arctos._

~~Member C~~

member C of the Lashly Formation

### Proposed Definition
_Clear, complete, non-collection-type-specific **functional** definition of the value. Avoid discipline-specific terminology if possible, include parenthetically if unavoidable._

https://en.wikipedia.org/wiki/Lashly_Formation

### Collection type
_Some code tables contain collection-type-specific values. ``collection_cde`` may be found from https://arctos.database.museum/home.cfm_

N/A

#### Attribute data type
_If the request is for an attribute, what values will be allowed?
free-text, categorical, or number+units depending upon the attribute (TBA)_

N/A

#### Attribute controlled values
_If the values are categorical (to be controlled by a code table), add a link to the appropriate code table. If a new table or set of values is needed, please elaborate._

N/A

#### Attribute units
_if numerical values should be accompanied by units, provide a link to the appropriate units table._

N/A

### Priority
_Please describe the urgency and/or choose a priority-label to the right. You should expect a response within two working days, and may utilize [Arctos Contacts](https://arctosdb.org/contacts/) if you feel response is lacking._

### Example Data
_Requests with clarifying sample data are generally much easier to understand and prioritize. Please attach or link to any representative data, in any form or format, which might help clarify the request._

### Available for Public View
_Most data are by default publicly available. Describe any necessary access restrictions._

### Helpful Actions

- [x] Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

- [x] Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

@ArctosDB/arctos-code-table-administrators 

## Approval
_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [ ] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [ ] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection
_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation
_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

- [ ] Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

- [ ] Add or revise the code table term/definition as described above. Ensure the URL of this Issue is included in the definition. URLs should be included *_as text_*, separated by spaced pipes. Do not include HTML in definitions.

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by Jegelewicz** [comment]
@KatherineLAnderson @Nicole-Ridgwell-NMMNHS @WaigePilson

**Comment by KatherineLAnderson** [comment]
Wikipedia page states--
"Lashly member C consists of fining-upward cycles of medium- to fine-grained sandstone grading upward into carbonaceous siltstone and mudstone, and thin [coal](https://en.wikipedia.org/wiki/Coal) beds. [Quartz](https://en.wikipedia.org/wiki/Quartz) pebbles and cobbles and mudstone clasts occur near the base of major sandstone units. Irregular lenses of coal occur along bedding planes and over large scours. [Dicroidium](https://en.wikipedia.org/wiki/Dicroidium) fronds and other plant fragments are common in carbonaceous beds.[[2]](https://en.wikipedia.org/wiki/Lashly_Formation#cite_note-FWLashly-2)"

Here's another reference, which shows Member C of the Lashly formation in the stratigraphic column in Figure 2:
https://www.jstor.org/stable/pdf/24102383.pdf?casa_token=7o7jOKvAO0cAAAAA:8grpeNaGSnr9__UYq4LUTE-wYWVqlPHTxP0EDq-NxhgsYQOp0gL9hCHGkHk3zr0WxxSjSY057BiWcTCvrzCc9EZMK0GYlozeI69T-jVLQPaOXEnUQHaB0Q
![Screen Shot 2023-09-22 at 12 57 41 PM](https://github.com/ArctosDB/arctos/assets/27514212/961efa1b-5f73-42fc-9382-46487cc51e52)

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
member C of the Lashly Formation

**Comment by Jegelewicz** [comment]
added based on approval by @Nicole-Ridgwell-NMMNHS and special access provision.
