### ISSUE TITLE
Code Table Request - new informal lithostratigraphy: Twin Buttes C

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6752]
### Goal
_Describe what you're trying to accomplish. This is the only necessary step to start this process. The Committee is available to assist with all other steps. Please clearly indicate any uncertainty or desired guidance if you proceed beyond this step._

Create terms for use in informal lithostratigraphy as per incoming collection request. See https://github.com/ArctosDB/arctos/issues/6707

### Context
_Describe why this new value is necessary and existing values are not._

https://github.com/ArctosDB/arctos/issues/6707

### Table
_Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table or value. This may involve multiple tables and will control datatype for Attributes. OtherID requests require BaseURL (and example) or explanation. Please ask for assistance if unsure._

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlithostratigraphic_informal

### Proposed Value
_Proposed new value. This should be clear and compatible with similar values in the relevant table and across Arctos._

~~Twin Buttes C~~

Twin Buttes Member unit C

### Proposed Definition
_Clear, complete, non-collection-type-specific **functional** definition of the value. Avoid discipline-specific terminology if possible, include parenthetically if unavoidable._

Tuffs very similar to the preceding. Defined inferiorly by a heavy and persistent calcareous stratum, the Sage Creek White Layer, shown at Sage Creek Spring. Another persistent stratum of flinty lime, the Burnt Fork White Layer, lies about the middle of the horizon. Fossils abundant and varied. Definition of Bridger Horizon C in Matthew, 1909; The Carnivora and Insectivora of the Bridger Basin, middle Eocene. Memoirs of the AMNH ; v. 9, pt. 6 | https://www.biodiversitylibrary.org/bibliography/88116

![image](https://github.com/ArctosDB/arctos/assets/5725767/5a991dc1-9093-4f18-86cd-66479a4921e2)

~~https://en.wikipedia.org/wiki/Bridger_Formation~~

### Collection type
_Some code tables contain collection-type-specific values. ``collection_cde`` may be found from https://arctos.database.museum/home.cfm_

N/A

#### Attribute data type
_If the request is for an attribute, what values will be allowed?
free-text, categorical, or number+units depending upon the attribute (TBA)_

N/A

#### Attribute controlled values
_If the values are categorical (to be controlled by a code table), add a link to the appropriate code table. If a new table or set of values is needed, please elaborate._

N/A

#### Attribute units
_if numerical values should be accompanied by units, provide a link to the appropriate units table._

N/A

### Priority
_Please describe the urgency and/or choose a priority-label to the right. You should expect a response within two working days, and may utilize [Arctos Contacts](https://arctosdb.org/contacts/) if you feel response is lacking._

### Example Data
_Requests with clarifying sample data are generally much easier to understand and prioritize. Please attach or link to any representative data, in any form or format, which might help clarify the request._

### Available for Public View
_Most data are by default publicly available. Describe any necessary access restrictions._

### Helpful Actions

- [x] Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

- [x] Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

@ArctosDB/arctos-code-table-administrators 

## Approval
_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection
_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation
_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

- [x] Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

- [x] Add or revise the code table term/definition as described above. Ensure the URL of this Issue is included in the definition. URLs should be included *_as text_*, separated by spaced pipes. Do not include HTML in definitions.

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by Jegelewicz** [comment]
I cannot find anything about Blacks Fork A in the referenced Wikipedia article - I think we need to show where this is "consistently used in the literature".

**Comment by Jegelewicz** [comment]
FWIW holding off on these until we get a resolution here

Twin Buttes C1
Twin Buttes C3

**Comment by Jegelewicz** [comment]
@KatherineLAnderson @Nicole-Ridgwell-NMMNHS @WaigePilson

**Comment by KatherineLAnderson** [comment]
Whatever we're doing with Blacks Fork A #6747 we should do here, too.

**Comment by mkoo** [comment]
I finally downloaded the Matthew paper (The Carnivora and Insectivora of the Bridger Basin, middle Eocene. Memoirs of the AMNH ; v. 9, pt. 6) to see where the definition came from. I agree that all the strata that need to be added from this paper should be handled together. And the definitions should not be simply a copy/paste from the paper but give a little context to larger formation group as well as cite the paper (so thanks for the BHL links!)

How about this tweak:

Twin Buttes Horizon C

Part of the Bridger Formation, Horizon C "tuffs very similar to the preceding (horizon D). Defined inferiorly by a heavy and persistent calcareous stratum, the Sage Creek White Layer, shown at Sage Creek Spring. Another persistent stratum of flinty lime, the Burnt Fork White Layer, lies about the middle of the horizon. Fossils abundant and varied." Definition of Bridger Horizon C in Matthew, 1909; The Carnivora and Insectivora of the Bridger Basin, middle Eocene. Memoirs of the AMNH ; v. 9, pt. 6 | https://www.biodiversitylibrary.org/bibliography/88116

BTW should this be Horizon C or Twin Buttes Horizon C ? I see that Horizon C appears in a few other geologic features according to Plate 42... just wondering if we also need to add
 'Henry's Fork Table Hor. C' etc

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I think we should use the format we already settled on.

**Comment by Jegelewicz** [comment]
Added under special exemption and as consistent with previous terms.

**Comment by KatherineLAnderson** [comment]
@Jegelewicz Twin Buttes Member unit C3 didn't make it into the code table--does it need more documentation?
