### ISSUE TITLE
Code Table Request - new informal lithostratigraphy: upper unit of Fremouw Formation

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6753]
### Goal
_Describe what you're trying to accomplish. This is the only necessary step to start this process. The Committee is available to assist with all other steps. Please clearly indicate any uncertainty or desired guidance if you proceed beyond this step._

Create terms for use in informal lithostratigraphy as per incoming collection request. See https://github.com/ArctosDB/arctos/issues/6707

### Context
_Describe why this new value is necessary and existing values are not._

#6707 

### Table
_Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table or value. This may involve multiple tables and will control datatype for Attributes. OtherID requests require BaseURL (and example) or explanation. Please ask for assistance if unsure._

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlithostratigraphic_informal

### Proposed Value
_Proposed new value. This should be clear and compatible with similar values in the relevant table and across Arctos._

~~upper member of Fremouw Formation~~

upper unit of Fremouw Formation - https://github.com/ArctosDB/arctos/issues/6753#issuecomment-1755951617

### Proposed Definition
_Clear, complete, non-collection-type-specific **functional** definition of the value. Avoid discipline-specific terminology if possible, include parenthetically if unavoidable._

~~https://en.wikipedia.org/wiki/Fremouw_Formation~~

The Fremouw Formation can be subdivided into three informal members. The upper member consists of coarse to medium-grained slope-forming, channel-forming sandstone alternating with fining-upward sequences of very fine-grained sandstone, siltstone and mudstone. - Institute of Polar Studies Report 87 | https://kb.osu.edu/bitstream/handle/1811/48692/IPS_Report_87_Part1.pdf?sequence=2) | https://github.com/ArctosDB/arctos/issues/6753

### Collection type
_Some code tables contain collection-type-specific values. ``collection_cde`` may be found from https://arctos.database.museum/home.cfm_

N/A

#### Attribute data type
_If the request is for an attribute, what values will be allowed?
free-text, categorical, or number+units depending upon the attribute (TBA)_

N/A

#### Attribute controlled values
_If the values are categorical (to be controlled by a code table), add a link to the appropriate code table. If a new table or set of values is needed, please elaborate._

N/A

#### Attribute units
_if numerical values should be accompanied by units, provide a link to the appropriate units table._

N/A

### Priority
_Please describe the urgency and/or choose a priority-label to the right. You should expect a response within two working days, and may utilize [Arctos Contacts](https://arctosdb.org/contacts/) if you feel response is lacking._

### Example Data
_Requests with clarifying sample data are generally much easier to understand and prioritize. Please attach or link to any representative data, in any form or format, which might help clarify the request._

### Available for Public View
_Most data are by default publicly available. Describe any necessary access restrictions._

### Helpful Actions

- [x] Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

- [x] Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

@ArctosDB/arctos-code-table-administrators 

## Approval
_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection
_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation
_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

- [ ] Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

- [ ] Add or revise the code table term/definition as described above. Ensure the URL of this Issue is included in the definition. URLs should be included *_as text_*, separated by spaced pipes. Do not include HTML in definitions.

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by Jegelewicz** [comment]
Make sure whatever happens that this is consistent with https://github.com/ArctosDB/arctos/issues/6748

Also, I would prefer the source be a publication instead of Wikipedia.

**Comment by Jegelewicz** [comment]
@KatherineLAnderson @Nicole-Ridgwell-NMMNHS @WaigePilson

**Comment by WaigePilson** [comment]
> Also, I would prefer the source be a publication instead of Wikipedia.
I feel like Wikipedia citation is the perfect use case for this "informal" designation. If it were formally published in a peer reviewed journal, it would likely be listed in Geolex and belong in the formal stratigraphy tables? What do others think?

**Comment by Jegelewicz** [comment]
I'd like to clarify my wishes (and I am not the final say, I am just here hoping to avoid future problems).

When all we provide as a description is a link to a Wikipedia article, we are trusting that whatever is there when the term is created will always be there. Wikipedia is edited on the daily and the linked article may look nothing like it did today when I visit it tomorrow, much less 5 years from now. If we are presenting a Wikipedia link, perhaps a brief summary of whatever the definition is along with the date it was obtained would be useful?

In the linked article I can see 

![image](https://github.com/ArctosDB/arctos/assets/5725767/cde4767b-6c06-47a3-8e67-6c9567dc52c0)

and

![image](https://github.com/ArctosDB/arctos/assets/5725767/b3d65674-2cf0-4306-a906-d2a7000a139c)

what I do not see is any kind of definition for those. Is there one on this page? Maybe we don't care about where the line between upper, middle and lower is, we just want to attach the fact that someone put that tag on something? Should I also infer from Wikipedia that there is a Lowe Fremouw Member?

![image](https://github.com/ArctosDB/arctos/assets/5725767/3a875cd7-f5c7-4cc8-bc97-b28bbd0a37e5)

(OK - now I am just being obnoxious)

This isn't meant to be difficult, but it is meant to make sure that the next user (or searcher) who comes along can make choices about what values to apply to their records or their searches. 

"Lower Fremouw was described in XXXX as YYYY."

would be so much more helpful! If we can't provide that, do we even know what Lower Fremouw is?

It took a little digging, but maybe this is helpful?

from https://a-dinosaur-a-day.com/post/139468073695/lower-fremouw-formation

> Time: About 252 to 247 million years ago, from the Induan to Olenekian ages of the Early Triassic Period, Mesozoic Era, Phanerozoic Eon
> 
> Location: Transantarctic Mountains, Antarctica
> 
> Environment: The early member of the Fremouw Formation is one of the earliest environments post the Permian extinction, which is the largest known extinction in Earth’s history.

But wait, a little deeper into the Google results and I find this:

[Institute of Polar Studies Report 87](https://kb.osu.edu/bitstream/handle/1811/48692/IPS_Report_87_Part1.pdf?sequence=2)

![image](https://github.com/ArctosDB/arctos/assets/5725767/25b003e8-1a4c-4750-b678-5a11e38f903e)

![image](https://github.com/ArctosDB/arctos/assets/5725767/a5b20159-5584-48db-abba-b0e0c5511b76)

Which isn't the first description, but definitely points to it.

I know that making good definitions for things is not easy, but we should at least make an effort to make them the best we possibly can. When we don't (and we very rarely do), we end up with code table requests stuck in forever limbo because we cannot distinguish them from some term in use with a terrible or non-existent definition. I know that 30 minutes of Googling and reading papers is not in anyone's job description, but it can make a huge difference in the quality of the data associated with these terms and that pays off over time.

**Comment by KatherineLAnderson** [comment]
I think we can understand the need for a "definition" (however we want to define that, but let's run with reference to mentioned in Wikipedia article XXX on date YYY) for data integrity, but we are struggling with the various demands on our time outside of this data migration project--so 30 minutes of googling for each term is a big deal on our end. 

Is a definition of "Defined as the uppermost sub-unit of the Fremouw formation at wikipedia link XXX on 22 September 2023" sufficient (for now anyway)?

**Comment by dustymc** [comment]
>"Defined as the uppermost sub-unit of the Fremouw formation at wikipedia link XXX on 22 September 2023" sufficient (

Suits me, and feel free to skip the date-bits (there's a log and the entry will reference the issue, both of which have that).

* there's some at-least-hint of the literature in which the term is consistently used
* there's some disambiguation and context (which is perhaps less critical with "Blacks Fork A of Blacks Fork Member of Bridger Formation" than "A" but nice to be clear).

I don't think these have to be super-detailed, but they should also be unambiguous.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Sounds good to me.

**Comment by Jegelewicz** [comment]
I cannot add this because everything is a bit cloudy for me.

1. Are we going with "Upper Fremouw Formation" or "upper unit of Fremouw Formation" (see https://github.com/ArctosDB/arctos/issues/6754#issuecomment-1734680350) or "upper member of Fremouw Formation" See below)?
2. What is the definition for this term? While the Wikipedia thingee is "sufficient" I did the research and we could say
> The Fremouw Formation can be subdivided into three informal members. The upper member consists of coarse to medium-grained slope-forming, channel-forming sandstone alternating with fining-upward sequences of very fine-grained sandstone, siltstone and mudstone. - Institute of Polar Studies Report 87 | https://kb.osu.edu/bitstream/handle/1811/48692/IPS_Report_87_Part1.pdf?sequence=2) | https://github.com/ArctosDB/arctos/issues/6753

**Comment by dustymc** [comment]
>everything is a bit cloudy

Me too, and sorry if I'm stirring up the muck. 

I very tentatively like the '{informal division} of {some unambiguous and formal thing}' structure, but IDK if my attempts to parse into that have been accurate, and of course I'm up for anything else (as long as it's as clear and consistent as it can be).

**Comment by Jegelewicz** [comment]
@KatherineLAnderson @WaigePilson @Nicole-Ridgwell-NMMNHS @dustymc can we go with the current term/description in the first comment?

**Comment by dustymc** [comment]
Does ``Upper Member`` need to be proper case?

**Comment by KatherineLAnderson** [comment]
@Jegelewicz That works for me!
@dustymc I don't think that it needs to be proper case.

**Comment by KatherineLAnderson** [comment]
@dustymc because as you mention "member" has formal connotations, going with "upper unit of Fremouw Formation" is likely the least misleading option here.

**Comment by KatherineLAnderson** [comment]
> @dustymc because as you mention "member" has formal connotations, going with "upper unit of Fremouw Formation" is likely the least misleading option here.

Except in the other thread for "Lower Fremouw Formation" #6748 we went with member, so it should be consistent....

**Comment by Jegelewicz** [comment]
added
