### ISSUE TITLE
Help needed with Loan Item Bulkload error

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6756]
I've been trying to bulkload loan items since yesterday, and keep getting cryptic errors. Yesterday's error message said the loan that I had just created did not exist.  I looked but couldn't find any non-printing characters. So I bypassed the bulkloader and loaded records one at a time using Add Items to the clearly existing loan, and that worked fine.
Today, trying to bulkload more items to same loan, and I get the following error, which appears to state that the collection object disposition "on loan" doesn't exist? Again, I checked for non-printing characters but didn't see anything. 
Here is the error: 
load fail::ERROR: insert or update on table "coll_object" violates foreign key constraint "fk_collobject_ctcollobjdisp" Detail: Key (coll_obj_disposition)=(on loan) is not present in table "ctcoll_obj_disp".

and here is the file: 
[bulkloadLoanItemData.zip](https://github.com/ArctosDB/arctos/files/12679450/bulkloadLoanItemData.zip)

**Comment by dustymc** [comment]
>I checked for non-printing characters

<img width="550" alt="Screenshot 2023-09-21 at 06 47 32" src="https://github.com/ArctosDB/arctos/assets/5720791/8cfdc2af-88c1-4e59-83ad-f4cfbee104a2">

**Comment by campmlc** [comment]
Oh cool, where is that tool?

**Comment by Jegelewicz** [comment]
![image](https://github.com/ArctosDB/arctos/assets/5725767/208ee2f9-e85a-4d0b-9481-1a1f2f28d853)

**Comment by Jegelewicz** [comment]
https://arctos.database.museum/DataServices/findNonprintingCharacters.cfm

**Comment by campmlc** [comment]
Wonderful, thanks! Item for newsletter?

**Comment by mkoo** [comment]
putting on agenda for future AWG demo
