### ISSUE TITLE
Agent "fatal flaw" that is really unnecessary

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6757]
See https://github.com/ArctosDB/data-migration/issues/1512#issuecomment-1729845884

We are discouraging incoming collections with these "fatal flaw" flags on agents. Of course, these all include "Northeastern University" because they are part of it! If we really want people to embrace creating an agent as issuer for identifiers, these "fatal flaw" errors are not helping. A less scary comment such as "this agent includes the same text string as these other agents - does that seem correct?" would be far more useful.

![image](https://github.com/ArctosDB/arctos/assets/5725767/57a219e5-dde9-4883-8cfa-9f7f7f551d0e)

**Comment by ewommack** [comment]
> A less scary comment such as "this agent includes the same text string as these other agents - does that seem correct?" would be far more useful.

That seems a better suggestion to me too.

**Comment by dustymc** [comment]
>better suggestion

For clarity and posterity: It's not, this is just a bug, that's never been part of any check. (People tend to share some names, after all....)
