### ISSUE TITLE
Feature Request - Additional filter for parts table view to filter by part attribute

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6763]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

See https://github.com/ArctosDB/arctos/issues/6760

**Describe what you're trying to accomplish** 
_A clear and concise overview of the goals; why are you asking for this?_

Download the parts with a single attribute to eliminate the attributes appearing across multiple columns when I am only interested in a single part attribute.

**Describe the solution you'd like**
_How might we accomplish your goals?_

Add a filter to the parts table view that allows me to filter by part attribute type.

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

See https://github.com/ArctosDB/arctos/issues/6760

**Additional context**
_Add any other context or screenshots about the feature request here._

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._

**Comment by dustymc** [comment]
>probably easy

Gonna be onem days, innit....

The part viewer-thing is using https://github.com/ArctosDB/PG_DDL/blob/master/function/getOrderedPartAttr.sql, which doesn't produce much opportunity for filtering (it's pulling the nth key-ordered attribute), and is returning only type/value/units.

Also not sure someone working with part attributes really needs to scroll past 21 columns of container-stuff to get where they need to be.

Is that form doing what everyone needs? (I'm hoping some sort of more-useful rebuild will result in something that's also more filter-able.)

**Comment by dustymc** [comment]
>separate thing

Seems like it to me, but I don't use this stuff.

>How

Evolution probably. 

I think maybe a blank-slate issue encompassing

* this
* https://github.com/ArctosDB/arctos/issues/6386
* https://github.com/ArctosDB/arctos/issues/6709
* https://github.com/ArctosDB/arctos/issues/6363 (needs ID)
* whatever I missed

makes more sense than trying to do anything with what seems to be a bit of a mix-n-match prototype??

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/6806
