### ISSUE TITLE
[CONTACT] Account mbowser deactivated?

### ISSUE THREAD

**Issue by mlbowser** [ArctosDB/arctos#6766]
Dear Arctos Team,

It appears that my account mbowser may have been deactivated. Can this be fixed?

Thank you for your help.

Sincerely,

Matt

**Comment by dustymc** [comment]
You should have email from Arctos.

**Comment by mkoo** [comment]
@mlbowser your account it open and active so I am closing this issue. open a new one if there are other issues!
