### ISSUE TITLE
Feature Request - allow container positions to accept decimal dimensions

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6767]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

When creating positions in a container, I enter the following:

position length = 2.79
position width = 2.79
position height = 7.5

and what saves is 

position length = 2
position width = 2
position height = 7

NOT useful when the containers in these positions have the following dimensions

length = 2.69
width = 2.69
height = 7

**Describe what you're trying to accomplish** 
_A clear and concise overview of the goals; why are you asking for this?_

Faithfully record dimensions of stuff

**Describe the solution you'd like**
_How might we accomplish your goals?_

Allow decimals at least to two places in position dimensions. Especially since the numbers I have are conversions from inches - trying to fudge everything so that the containers will fit into positions and the box will fit into the cabinet is a huge drain on my time/energy. If I could just record the actual measurements, life would be so much simpler....

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

Make up stuff so that things will work.

**Additional context**
_Add any other context or screenshots about the feature request here._

See also #6452 

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._

**Comment by dustymc** [comment]
How do I re-create?

**Comment by Jegelewicz** [comment]
Set up a container with positions then try to assign position width 2.79.

**Comment by Jegelewicz** [comment]
![image](https://github.com/ArctosDB/arctos/assets/5725767/20b82735-2029-44a5-b391-a70a8a6ff713)

![image](https://github.com/ArctosDB/arctos/assets/5725767/d242764b-bde4-461d-b500-85ebfb532cea)


![image](https://github.com/ArctosDB/arctos/assets/5725767/acb8b0b4-7623-414a-bb49-bac36229aa90)

![image](https://github.com/ArctosDB/arctos/assets/5725767/73952297-caf7-4f28-8738-c6b82d0a7d94)

**Comment by dustymc** [comment]
Thanks. That's a bug (I think from recent postgres upgrades) and it involves both back and front end - there's no way I can patch it in the middle of a development cycle, I'll get it in next release, perhaps that should be expedited....

**Comment by Jegelewicz** [comment]
I can fudge things to keep moving - but it really isn't ideal. I will let you know if it becomes a real roadblock.

**Comment by Jegelewicz** [comment]
> maybe I should just shut the form off

That is a hard NO - I bet MSB is using this on the daily and I need it for setting up OGL NOW (and for their freezer boxes it doesn't matter as positions in them are standard as 1,1,4). I'll hold off on the weird boxes where I noticed this for now.
