### ISSUE TITLE
Feature Request - allow longer permit numbers

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6769]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

I cannot add permits for an incoming collection because their numbers extend to more than 25 characters

**Describe what you're trying to accomplish** 
_A clear and concise overview of the goals; why are you asking for this?_

Enter permits

**Describe the solution you'd like**
_How might we accomplish your goals?_

Make permit number VARCHAR (60) (or longer? That should cover me for now)

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

truncate the permit number to make do

**Additional context**
_Add any other context or screenshots about the feature request here._

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._

**Comment by dustymc** [comment]
done
