### ISSUE TITLE
Feature Request - validate user emails

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6770]
**Is your feature request related to a problem? Please describe.**

A user with an invalid email somehow managed to get created, after lots of probably-frustrating errors.

**Describe what you're trying to accomplish** 

Make sure emails are emails.

**Describe the solution you'd like**

Cleanup and control ``cf_users.email``.

**Describe alternatives you've considered**

There are none.

**Additional context**

I will just remove invalid email addresses, but I can share data internally if necessary. (A quick glance suggests only one of these is "us.")

**Priority**

Rare but critical = still critical.

**Comment by ewommack** [comment]
Sounds reasonable to me. Would there be any costs to setting it up?
