### ISSUE TITLE
Planned Arctos Downtime- Friday 10/6, 12PM Pacific/2PM Central

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#6774]
## Planned Outage
 - Friday October 6th 
 - Starting 12 pm Pacific/ 2 pm Central lasting about 5 hours
 - Reason for outage: updates to database and deep backup
 - Arctos will be unavailable during this time for planned maintenance; please plan accordingly

## Communication before/during outage
- [x] Pin this issue
- [x] Banner updated @jegelewicz @mkoo
- [x] Email sent to AWG  
- [x] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [x] Unpin this issue
- [x] Banner updated @jegelewicz @mkoo
- [x] Email sent to AWG 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by ewommack** [comment]
Emails schedule to go out on this Friday at 8am and next Thursday (5th of Oct) at 8am. So one week notice, and then reminder the day before.

**Comment by dustymc** [comment]
I've brought the Arctos UI back up, I don't see smoke pouring out of anything important-looking yet but will keep monitoring and may need to take things down suddenly if something comes up. Please let me know ASAP if you find any problems.

**Comment by ewommack** [comment]
Poking about and nothing is broken yet. Let me know when you want to call it @dustymc and I can send out another email.

**Comment by dustymc** [comment]
I still don't see smoke, goferit - and thanks!

**Comment by ewommack** [comment]
And sent!
