### ISSUE TITLE
Calculate media thumbnail when media/preview URI is not from TACC?

### ISSUE THREAD

**Issue by kderieg322079** [ArctosDB/arctos#6775]
**Describe the bug**
Not necessarily a bug? But something not working how I want... We archive media in a DAMS hosted by the University of Utah digital library system. I'm using links from the digital library to add media to records. The thumbnail won't automatically generate for images sourced from the digital library. 

**To Reproduce**
Go to [UMNH:Mamm:1000](https://arctos.database.museum/guid/UMNH:Mamm:1000) and you will see there is no thumbnail for the media.
Example record: https://arctos.database.museum/guid/UMNH:Mamm:1000
Media URI: Media record on digital library: https://collections.lib.utah.edu/ark:/87278/s68vat63
Preview URI: Direct download of image from digital library: https://collections.lib.utah.edu/file?id=2311581

**Expected behavior**
I hoped a thumbnail would automatically generate, like it does with media that I load directly into Arctos (i.e. media URI is from TACC).
Example of records with media with automatically generated thumbnails: [UMNH:Mamm:3274](https://arctos.database.museum/guid/UMNH:Mamm:3274)

**Screenshots**
![image](https://github.com/ArctosDB/arctos/assets/82051765/3a660a2d-bae8-4d0f-966b-38a7817093df)
![image](https://github.com/ArctosDB/arctos/assets/82051765/8f8efa28-5adc-43bd-a952-07078871e046)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version [e.g. 22] ???

**Additional context**
I have tried using the media record URL (aka reference URL) and the direct download URL for both Media URI and Preview URI. No combination of those links produces a thumbnail. I would rather not have to upload every thumbnail manually because we are trying to link up about 16,000 images from the digital library. 

**Priority**
Normal/Low. I hesitate to put low because I would really like thumbnails but it isn't the absolute end of the world if this doesn't work out.

**Comment by dustymc** [comment]
The metadata for that media record are incorrect. https://collections.lib.utah.edu/ark:/87278/s68vat63 is NOT an image, it's HTML. The thumbnailer should work for any accessible image, so (assuming it's not blocking Arctos) you could change the Media to do that (if you can find the image URL - I can't), but then you'd lose whatever magic the not-just-image webpage is adding.

**Comment by kderieg322079** [comment]
Oh that makes sense that it is HTML since it is a whole webpage... So why does the direct download URL not allow for thumbnail calculation? E.g. if I am on the library webpage, right click on "Download File" and click "Copy Link Address" I get this URL: https://collections.lib.utah.edu/file?id=2311581. I thought that might work but it doesn't. Not really sure how else to go about getting the image URL. I'll see if anyone at the library has suggestions. Thanks!

**Comment by dustymc** [comment]
The auto-thumbnailer is always going to have limitations. Loading the media with a thumbnail-appropriate image file will be a lot more robust, if that's a possibility.

(And FWIW you might consider using a maybe-more-stable ARK resolver eg  https://n2t.net/ark:/87278/s68vat63)

**Comment by kderieg322079** [comment]
Okay, thanks for the insight!
