### ISSUE TITLE
Preset paleo search profile

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#6776]
The default search profile, particularly results, doesn't work very well for paleo. Editing search profile is difficult for anyone who doesn't usually use Arctos. I'd like to add a preset (preset_paleo) with the following:

Search:
Collection
Catalog Number
Any taxon, ID, common name
Identification
Agent (collector)
Type Status
Media Type
Part Search
Part Name
Part Attribute Search
Age (Mya)
Chronostratigraphy
Asserted Country
Asserted State/Province
Asserted County
Locality Attributes
Specific Locality
Locality Name

Results:
GUID
Identified As
Media
Part Names
Locality Name
formation
member

@WaigePilson @KatherineLAnderson this will probably be useful for you as well.

**Comment by dustymc** [comment]
@Nicole-Ridgwell-NMMNHS I can't easily work with your list, but that's a simplification: Just set up a profile, let me know the name of it, I'll steal it and get it in next release.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Ok, profile is nicole_paleo_final

**Comment by dustymc** [comment]
Thanks, I'll plan to use https://arctos.database.museum/search.cfm?sp=nicole_paleo_final as 'preset_paleo' (always up for better ideas!) with next release.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks!

**Comment by mkoo** [comment]
Tested! I like it
Also learned that I can share my presets with a URL- love it
