### ISSUE TITLE
Request - update help text on collection.cfm to indicate changes need to be made manually on IPT

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#6778]
From AWG meeting: When changing collection contacts, the updates are not reflected in the IPT automatically and must be manually edited on the Vertnet IPT site. Please add a note to the top of the form-- possibly a 3rd bullet point -- 

"Changes to the collection contacts are only changed here; update the IPT metadata directly on the IPT site. Contact Arctos or the VertNet contact if you need information."

![Firefox_Screenshot_2023-09-28T20-39-59 294Z](https://github.com/ArctosDB/arctos/assets/2523089/cfaf7599-0983-4025-af93-c0618422a274)

**Comment by dustymc** [comment]
[Make EML](https://arctos.database.museum/info/ipt.cfm) - I can see no technical reason that this isn't automated.

**Comment by Jegelewicz** [comment]
> I can see no technical reason that this isn't automated.

It is for the very first publication, but we do not hold all of the information required and @dbloom has to make some changes after ingesting the EML. A manual update every time someone changes something is not feasible. We have had previous discussions about better automation and what is needed to make the pipeline between Arctos and the VertNet IPT automated, but we never quite get to the finish line - maybe we can now?

https://github.com/ArctosDB/internal/issues/150
