### ISSUE TITLE
Locality help - No higher geography, No specific locality recorded.

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6780]
@dustymc is there a locality that uses no higher geography and No specific locality recorded. that has nothing else in any of the locality fields? Can we name this locality something so that I can use it whenever I need it?

**Comment by dustymc** [comment]
```
create table temp_maybe_ona_tehse as select locality.* from locality
 left outer join locality_attributes on locality.locality_id=locality_attributes.locality_id
 where geog_auth_rec_id =69 and 
 spec_locality='No specific locality recorded.' and dec_lat is null
 and locality_attributes.attribute_type is null;
```


[temp_maybe_ona_tehse.csv](https://github.com/ArctosDB/arctos/files/12772266/temp_maybe_ona_tehse.csv)

**Comment by Jegelewicz** [comment]
Ah Ha - Locality Name = NULL Locality Data

**Comment by Jegelewicz** [comment]
Added a tip to documentation for no locality data entry. Thanks!
