### ISSUE TITLE
Agent Merge Request: J Woodburn

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6782]
Use this template when you discover two agents that you believe represent the same person or organization.

**Agent that should remain after the merge**

unknown

**Agent that will no longer remain after the merge**

https://arctos.database.museum/agent/21350288

**Reason for merge**

Agent seems to be low-information person structured as 'other agent.'

Please add this issue to the Agents Project

@ArctosDB/agents-committee

@mgskinner @andrew-hope @Jegelewicz

**Comment by Jegelewicz** [comment]
Done
