### ISSUE TITLE
question on data entry - carry option and mammal specifics?

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#6784]
Hi, I think I may be missing something regarding customizing the data entry screen, but we used to have a useful tool to set various fields to carry or not carry. We used to have a very handy tool for mammals where the fields sex, total, tail, hind foot, ear and weight were all next to each other and linked to the same date and agent. Am I missing something, or is this gone forever? 
On a related note, is it possible in data entry to make required fields block you from getting to save? For example, identification_1_order is required, but apparently you can save a record without a selection, but it will fail in the subsequent load step. It would be helpful if required fields were colored or coded in some way. 

The data entry videos here are totally out of date. 
https://arctosdb.org/learn/tutorial-blitz/#dataentry

**Comment by mkoo** [comment]
not gone-- go to the very bottom of the data entry screen to the bright blue Customize button to access show/hide/ carry options for every field. We showed this off at the last AWG meeting or attend one of the many weekly office hours for a demo of the new features gained from the updated bulkloading tools.

Are you offering to do some new tutorial videos?!

**Comment by Jegelewicz** [comment]
@mkoo this reminds me that we need to record those demos at the AWG meetings - I added a reminder in the agenda....

**Comment by mkoo** [comment]
@cjconroy when you're back and have had a chance to check this out, let me know if you have other data entry issues. Meanwhile closing this initial inquiry

**Comment by cjconroy** [comment]
I've just done data entry with an MSB template and tweaking things as I went. I have questions and will ask in office hours. But, if you can help with this, I'd appreciate it. Any idea what this error is? Accn 15420 in bulkloader. 

<img width="1045" alt="Screenshot 2023-10-06 at 11 09 49 AM" src="https://github.com/ArctosDB/arctos/assets/5749672/1c20d7f7-7c6c-48d3-b575-f4ee5c1ace34">

**Comment by dustymc** [comment]
ix_collector_coid_aid_role is duplicate collectors

**Comment by mkoo** [comment]
maybe because you have the same name as preparator1,2,3,4 etc?

compare row 1 (no error) and row 2 etc 
or email me for a zoom

**Comment by cjconroy** [comment]
Yes, I had extra agents. Their form has 8 agents. Another reason I have to create another form for MVZ mammals.

**Comment by dustymc** [comment]
File an Issue. IDK how realistic 'MVZ Mammals' is (as "part of Arctos" - there's of course an API that'll support near anything), but 'mammals' might make a nice specialized form. (I think ~a dozen extra forms might be sustainable, I'm pretty sure 400 is not, but ?? - it seems an idea worth exploring if someone wants to.)

**Comment by cjconroy** [comment]
I have not yet made my own data entry template. I think I need to do that before weighing in. The issue I envision is that there are so many varieties. Lab animals with one species and one locality, field excursions with one or more localities and multiple species, accessions with one collection, others with many collectors. I think the best thing is to have a good starting place, but a way to tailor it on the fly. I would hate to clutter up arctos with a new template for every variant.
I also need to figure out setting up the carry function, but need arctos to be back online to try to customize. This changes a lot as noted above. one collector or many, one species or many, one locality or many, etc.
