### ISSUE TITLE
Add DeKalb County, Missouri in higher geography

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#6785]
This does not seem to exist. I have some mice I need to catalog from that county. 
Thanks.

**Comment by cjconroy** [comment]
https://en.wikipedia.org/wiki/DeKalb_County,_Missouri

**Comment by dustymc** [comment]
https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10020515

**Comment by cjconroy** [comment]
Found it, but on the world wide web, there is no space in De Kalb as there is in Arctos.

**Comment by dustymc** [comment]
https://gadm.org/maps/USA/missouri_2.html is the standard we follow.

**Comment by cjconroy** [comment]
OK
