### ISSUE TITLE
Feature Request -new role to allow autoloading/inserting records in bulkloader

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#6786]
Another request for finer permissions to avoid giving unnecessary access to certain permissions: I would like to enhance manage_records role to include permission to autoload records and remove from manage_collection (where accidental changes can really mess with a collection)

users with Manage_collection can already clone records (ie. create new GUIDs) so this is not that much more and still requires the same level of care and attention to detail.

@dustymc says not a technical challenge

**Comment by Jegelewicz** [comment]
Let me make sure that I understand because

> users with Manage_collection can already clone records (ie. create new GUIDs) so this is not that much more

is confusing me.

The request is to add the ability to load records from the bulkloader to production to the manage_records role and changing no permissions for the manage_collection role?

**Comment by dustymc** [comment]
>changing no permissions for the manage_collection role?

I think that's actually possible in PG, but let's don't go there - roles don't overlap, and for the sake of simplicity let's keep it that way. This request would require and allow ``manage_records`` to update ``bulkloader.status`` to (``autoload_core``,``autoload_extras``) (and INSERT on cataloged_item, but as mentioned that's an expansion).

These users DO have manage_collection and DO NOT have manage_records; they would lose functionality with this change.

```

 ah972
 alorenz
 amye04
 bbetting
 bjp830
 creyespuig
 dandistel
 eflint03
 ehoque
 huffcuta
 ianba
 jacobjan
 jdc288
 jlp21
 jrr228
 kbranch6
 lammerma
 leache
 lexia02
 lingnancollection
 mccadyc
 mrdg2
 pb5674
 pdrucken
 sbirks
 semunm
 srd66
 tasials
 vbecerril
(29 rows)
```

These users DO have manage_records and DO NOT have manage_collection; they would gain functionality with this change.

```

 amgiddings
 avinod04
 bbarton8
 cotterstrom
 cpurcell2
 cscarr
 cxmcdaniels
 ekauffman
 evanwheeler
 hlwitherington
 jblake
 jerryjohnson
 jihyunk830
 jjcornelius
 jmix12
 jslowik
 kcwebster11
 kkay
 lexibaca
 libby
 litsawooten
 llawson14
 lroberts22
 mbonnot
 mdevireddy
 mgskinner
 mgwyatt
 mhampton
 mschmidt
 ngznatalie
 nikki800
 oschapman
 pmarquez
 ridabrams
 rpianka
 skgolden7
 skipskidmore
 ssibrava
 zellis
```

I can get collections and contacts if necessary, but it's basically everyone - those users touch 316 collections.

**Comment by Jegelewicz** [comment]
I think it is fairly easy to just ensure those who currently have manage_collection get assigned manage_records if they don't already have that.

The second bunch seems more difficult because we don't want to up any users capability without express consent of the collections to which they have edit access.

Would it just be better to add a role? insert_records? Then add it to everyone who has manage collection and everyone can adjust manage_collection as necessary and assign the new role if needed?

This is kinda making me nuts - I might have just said "WLTEIYHedlkg,vnW[OA49."...

**Comment by dustymc** [comment]
>nsure those who currently have manage_collection get assigned manage_records if they don't already have that.

Agree, I can't see the trap in me doing that if this proceeds. (Which is how traps work, I suppose...)

>second bunch seems more difficult

Yes, I would NOT be comfortable giving anyone access to manage any collection, that's the domain of the CMs.

>better to add a role

There's been a bit of an ongoing debate about that, I don't think I have much opinion. I like it in theory: Minting GUIDs and eg loading attributes are VERY different commitments, those are now entangled, separating them seems "correct," but I'm not sure how much of that carries over to reality, I think the people in those roles just work together and the confounding isn't much of a problem.

Big-picture, I think the options are:

* lots of options == lots of explicit complexity in which people can get lost
* fewer options == lots of implicit complexity in which people can get lost

**Comment by campmlc** [comment]
This is very timely, as I was just facing the same problem. We have CMs assigning manage collection for the sole purpose of allowing graduate students to mark to load. This definitely needs to be removed from manage collection in any way. I support moving to manage_records. Can we manage_collection automatically include manage_records role? What we need is a hierarchy, because I know that just within our institition, people are confused by the role descriptions in terms of which to assisgn in what order.

**Comment by campmlc** [comment]
I think this is what we have now:
> * fewer options == lots of implicit complexity in which people can get lost
Given the choice, I'd prefer:
> * lots of options == lots of explicit complexity in which people can get lost

**Comment by mkoo** [comment]
> I think this is what we have now:
> 
> > * fewer options == lots of implicit complexity in which people can get lost
> 
> But given the choice, I'd prefer:
> 
> > * lots of options == lots of explicit complexity in which people can get lost

I agree with that principle.
So really the request is a new role called insert_records or add_records (or whatever the Arctos wizard wants) which would circumvent the most obvious issues here. Let me edit the request!
thx

**Comment by campmlc** [comment]
bulkload_records?

**Comment by dustymc** [comment]
>automatically include 

No.

>hierarchy

That is incompatible with how this functions.

>bulkload_records

That seems very misleading; it's one of ~three paths to minting a GUID.

Question: Would the new role also inherit DELETE on ``collection``?

**Comment by mkoo** [comment]
> Question: Would the new role also inherit DELETE on `collection`?

I would say not-- that should remain with manage_collection (it's one of the scary powers we want to differentiate)
That needs someone who understands, creates, and uses encumbrances so let's keep separate.

**Comment by mkoo** [comment]
With respect to the 29 with current manage_collections, they would inherit the new role so no loss of permissions.

Copied below for clarity:

 ah972
 alorenz
 amye04
 bbetting
 bjp830
 creyespuig
 dandistel
 eflint03
 ehoque
 huffcuta
 ianba
 jacobjan
 jdc288
 jlp21
 jrr228
 kbranch6
 lammerma
 leache
 lexia02
 lingnancollection
 mccadyc
 mrdg2
 pb5674
 pdrucken
 sbirks
 semunm
 srd66
 tasials
 vbecerril
(29 rows)

**Comment by dustymc** [comment]
Is this correct?

* new role ``create_records`` (I think that's sorta-consistent with some random stuff...)
* revoke insert on cataloged_item from {everyone}
* grant insert on cataloged_item to create_records
* grant create_records to {everyone with an active and open manage_collection account}
    * note "everyone" NOT just the missed-intersection 29 above
* update [documentation](https://arctos.database.museum/Admin/user_roles.cfm)

**Comment by mkoo** [comment]
I think that sums up the solution nicely!

**Comment by dustymc** [comment]
Then this should be additive and I can't see any problems with direct implementation.

**Comment by mkoo** [comment]
Hey @dustymc what is the status of this?
thx

**Comment by dustymc** [comment]
I'll try to get it out this week.

**Comment by dustymc** [comment]
done

**Comment by mkoo** [comment]
One last comment @dustymc Can you complete the user description please? I am waiting to see who the "very user" is!

![Firefox_Screenshot_2023-10-13T15-34-19 948Z](https://github.com/ArctosDB/arctos/assets/2523089/5793b5f2-2569-425f-a695-fb753131d548)

**Comment by dustymc** [comment]
Thx, you should be able to do that but you can't, updated and will be functional in next release.
