### ISSUE TITLE
Feature Request - full-row index on all attributes

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6787]
**Is your feature request related to a problem? Please describe.**

 See https://github.com/ArctosDB/arctos/issues/6760 - it's easy to create duplicate attributes

**Describe what you're trying to accomplish** 

Never again have to clean up duplicate attributes!

**Describe the solution you'd like**

Full-row unique index on all attribute tables. PG15 introduces ``NULLS NOT DISTINCT`` which should allow this capability. The full-row scope would mean that the same type+value determined by different agents, or a second apart by a datalogger agent, etc., could still exist, while rows which share all information cannot. I can't see any problems with this restriction, please comment below if I'm missing something.

**Describe alternatives you've considered**

Delete more duplicates.

**Additional context**

**Priority**

Calling it high, duplicates are no fun for anyone, we now have the capacity to do something about it.

**Comment by dustymc** [comment]
## Part Attributes

Duplicates which will be purged:

[temp_dup_part_attrs.csv.zip](https://github.com/ArctosDB/arctos/files/12820306/temp_dup_part_attrs.csv.zip)


Summary:

```

 guid_prefix | count 
-------------+-------
 ALMNH:Paleo |    20
 CHAS:Bird   |     1
 CHAS:Inv    |     1
 DMNS:Bird   |     1
 DMNS:Mamm   |     1
 MLZ:Fish    |     1
 MSB:Bird    |     1
 MSB:Herp    |    65
 MSB:Mamm    |     5
 MSB:Para    |     3
 MVZ:Bird    |     1
 NMMNH:Paleo |     5
 UAM:Arc     |    12
 UAM:EH      |     1
 UAM:Ento    |     7
 UAM:Mamm    |     1
 UCM:Bird    |     1
 UWBM:Mamm   |     5
(18 rows)
```

ping:


 @ebraker
 @Nicole-Ridgwell-NMMNHS
 @mkoo
 @AJLinn
 @campmlc
 @ccicero
 @amgunderson
 @DerekSikes
 @jtgiermakowski
 @wellerjes
 @jebrad
 @AdrienneRaniszewski
 @acdoll
 @aklompma
 @jldunnum
 @jrdemboski
 @msbparasites
 @catherpes
 @sjshirar
 @claypollock
 @droberts49

**Comment by AJLinn** [comment]
ah ha... that makes sense now!
Then yes, I agree with the overall premise, if all elements are exactly the same, it was likely a mistake. This happened to me a lot a year or so ago when there was a lag in saving new part attributes. I'd hit the save button, nothing would happen, so I'd hit it again thinking I mis-clicked the first time, only to find two identical part attributes. I tried to clean them up immediately, but likely this is one that got overlooked. Thanks then and sorry to not see the "direct implementation" milestone and what that meant.

**Comment by dustymc** [comment]
## Record Attributes

Duplicates which will be purged:

[temp_dup_rec_attrs.csv.zip](https://github.com/ArctosDB/arctos/files/12820994/temp_dup_rec_attrs.csv.zip)


Summary:

```

 guid_prefix | count 
-------------+-------
 ALMNH:EH    |     1
 APSU:Bird   |     2
 ASNHC:Bird  |     1
 ASNHC:Mamm  |    19
 CHAS:Bird   |    11
 CHAS:Ento   |     2
 CHAS:Herb   |     2
 CHAS:Mamm   |     3
 CHAS:Teach  |     1
 CSULB:Bird  |     1
 CSULB:Mamm  |     6
 DMNS:Bird   |    60
 DMNS:Inv    |     1
 DMNS:Mamm   |   623
 KNWR:Ento   |     4
 KWP:Ento    |     1
 MLZ:Bird    |     1
 MSB:Bird    |     5
 MSB:Herp    |     1
 MSB:Host    |     2
 MSB:Mamm    |  1247
 MSB:Para    |    88
 MVZ:Bird    |     9
 MVZ:Herp    |     3
 MVZ:Mamm    |     4
 MVZObs:Bird |     4
 NMMNH:Geol  |     1
 UAM:Arc     |    35
 UAM:Art     |    78
 UAM:Ento    |    30
 UAM:Fish    |     1
 UAM:Herb    |     2
 UAM:Inv     |     1
 UAM:Mamm    |    26
 UCM:Bird    |    26
 UCM:Egg     |     1
 UCM:Herp    |     1
 UCM:Mamm    |    17
 UCSC:Bird   |     2
 UMNH:Bird   |     1
 UMNH:Herp   |    11
 UMNH:Mamm   |  2192
 UMZM:Bird   |    18
 UMZM:Mamm   |   216
 UNCG:Mamm   |     3
 UNR:Bird    |     1
 UNR:Herp    |     2
 UTEP:Bird   |     1
 UTEP:Ento   |     4
 UTEP:ES     |     1
 UTEP:Herp   |     6
 UWYMV:Bird  |     1
 UWZM:Bird   |    15
 UWZM:Mamm   |    17
```

ping:



 @ebraker
 @bryansmclean
 @ehalverson26
 @Nicole-Ridgwell-NMMNHS
 @mkoo
 @campmlc
 @ccicero
 @camwebb/
 @amgunderson
 @atrox10
 @DerekSikes
 @mvzhuang
 @cjconroy
 @makaylaeasley
 @jtgiermakowski
 @wellerjes
 @brandon-s-thompson
 @gradyjt
 @AdrienneRaniszewski
 @acdoll
 @jldunnum
 @jrdemboski
 @msbparasites
 @genevieve-anderegg
 @DellaCHall
 @ewommack
 @kderieg322079
 @StefanieBond
 @sharpphyl
 @catherpes
 @sjshirar
 @adhornsby
 @Jegelewicz
 @jandreslopez
 @droberts49

**Comment by dustymc** [comment]
## Event Attributes

Duplicates which will be purged:

[temp_dup_evt_attrs.csv.zip](https://github.com/ArctosDB/arctos/files/12821244/temp_dup_evt_attrs.csv.zip)

Summary:

```

 guid_prefix | count 
-------------+-------
 UAM:Env     |     2

```

Ping: 

 ghaddr 
--------
(0 rows)

**Comment by dustymc** [comment]
## Locality Attributes

Duplicates which will be purged:

[temp_dup_loc_attrs.csv.zip](https://github.com/ArctosDB/arctos/files/12822654/temp_dup_loc_attrs.csv.zip)



Summary:
```

 guid_prefix | count 
-------------+-------
 ALMNH:Inv   |     1
 DMNS:Inv    |     3
 JFBM:Fish   |  5129
 MSB:Mamm    |     1
 MVZ:Bird    |     4
 MVZ:Egg     |     2
 MVZ:Herp    |   183
 NMMNH:Geol  |     1
 NMMNH:Paleo |   164
 UAM:ES      |   256
 UCM:Herp    |     3
 UTEP:ES     |     8
```

Ping:


 @ebraker
 @Nicole-Ridgwell-NMMNHS
 @mkoo
 @campmlc
 @ccicero
 @barke042
 @atrox10
 @mvzhuang
 @AdrienneRaniszewski
 @acdoll
 @jldunnum
 @genevieve-anderegg
 @sharpphyl
 @kmkocot

**Comment by dustymc** [comment]
## Identification Attributes

Index built without issue.
