### ISSUE TITLE
Feature Request - unique constraint on containers

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6789]
**Is your feature request related to a problem? Please describe.**

See https://github.com/ArctosDB/data-migration/issues/1812#issuecomment-1747385377

**Describe what you're trying to accomplish** 

Figure out the scope in which barcodes must be unique, and how barcodes may be claimed.

**Describe the solution you'd like**

I believe there are three possibilities:

1. What we have now is by far the simplest system
    * Barcodes are globally unique. 
    * Claims use "native" SQL. 
2. We could expand claim capability, but doing so would introduce some potential fragility (are we SURE everyone counts the same way in base36?) and confusion (are you SURE this Xxxxx barcode is yours?).
    * Barcodes are globally unique. 
    * Claims require some extension (at least to base36 counting to accommodate current data)
3. We could extend the key to (container.barcode, container.institution_acronym). This is by far the most robust system (I have no idea how we don't have a bunch of previously-barcoded institutions fighting over "1" already!), but would SOMEHOW involve needing to contextualize nonunique barcodes, and I don't know how that might work
    * Barcodes are unique within institutions. 
    * Claims use "native" SQL. 

**Describe alternatives you've considered**

I don't think there are any, even if the current situation can be resolved we'll probably encounter this again.

**Additional context**

I can't offer much help in the referenced Issue until this social problem is sorted out by The Community.

**Priority**

@andrew-hope can set this

**Comment by campmlc** [comment]
For option 3, what would be changed if we went this route? Would the barcode series change, or just the permissions key to include the institution acronym or guid prefix?

**Comment by Jegelewicz** [comment]
> needing to contextualize nonunique barcodes

We don't have to share the container environment. I don't know how many of UAM things are scanned into MSB containers and the other way around, but is anyone else doing that?

Maybe an institution's container environment should just belong to them to do whatever?

**Comment by dustymc** [comment]
>For option 3, what would be changed if we went this route?

That is my question. I'm telling you what I see as options and asking what affects implementing them (or not) might have.

>don't have to share the container environment

But we don't prevent it.

* UserA who only has access to Institution1 collections scans ``1`` - no problem
* UserB who only has access to Institution2 collections scans ``1`` - no problem
* UserC who has access to Institution1 and Institution2 scans ``1`` - this has to result in an error, lacking some something that I can't see from here.

So that will prevent me from scanning ``1`` - which is fine, if I need to update I'll do it by keys.

>don't know how many

```
select
    p.institution_acronym as parent,
    c.institution_acronym as child,
    count(*) c
from
    container c
    inner join container p on c.parent_container_id=p.container_id
where 
    p.institution_acronym != c.institution_acronym
group by 
    p.institution_acronym,
    c.institution_acronym 
order by
    p.institution_acronym,
    c.institution_acronym
;

 parent | child  |   c   
--------+--------+-------
 KNWR   | UAM    |   839
 MSB    | DGR    |   337
 MSB    | DMNS   |     2
 MSB    | NMMNHS |   165
 MSB    | NMU    |     2
 MSB    | UAM    |  2439
 MVZ    | UAM    |   733
 MVZ    | UCSC   |    23
 UAM    | ACBC   |     1
 UAM    | KNWR   |  1060
 UAM    | KWP    | 57465
 UAM    | MSB    |     6
 UAM    | MVZ    |   187
```
Some of those are messes (some of which might have been prevented by Option 3), but others are collaborations - KWP is purposefully in UAM containers, for example. So those two collections both having a barcode=``1`` would cause errors.

Small price to pay for the much more scalable solution??

>institution's container 

That's part of the - maybe not problem, but weird. An institution is a text string hanging awkwardly off collection, which gets joined to the institution hanging awkwardly off container for things like checking access. Not sure I have better ideas, but it's awkward and probably hard to understand and makes collaborating maybe more fragile than it has to be.

**Comment by campmlc** [comment]
I haven't been able to check the previous table yet, but I just found some more recent issues from June and July where students in MSB entered parasite records via data entry and apparently put the MSB:Mamm host catalog number in the part barcode field instead of the parasite vial base36 MSB barcode. The number series overlaps with the numeric UAM barcodes, so when these records were marked to load, the parasite parts loaded to UAM cryovials with that value. I thought at least that the current restrictions prevented this? We probably need to set up a call or task force to discuss.


![Screenshot 2023-10-08 19 08 13](https://github.com/ArctosDB/arctos/assets/14808196/b960a893-b835-4d4e-828b-0f6b71d7c356)
![Screenshot 2023-10-08 19 07 39](https://github.com/ArctosDB/arctos/assets/14808196/44d02c09-73b4-47b1-b622-4310e0840a15)
![Screenshot 2023-10-08 19 10 34](https://github.com/ArctosDB/arctos/assets/14808196/2af39d8a-65bb-4605-a78c-6e18911fbf52)
![Screenshot 2023-10-08 19 10 18](https://github.com/ArctosDB/arctos/assets/14808196/317a34cc-9588-4776-bb27-173b2f689fe0)

**Comment by campmlc** [comment]
@megulbranson @AdrienneRaniszewski @jldunnum

**Comment by dustymc** [comment]
>restrictions prevented this?

No, but that's why changing container type with entry isn't possible. That clearly isn't enough.

> put the MSB:Mamm host catalog number in the part barcode field

I suggest we go ahead with (3) above, including at entry using ``enteredby``. That will make some collaboration perhaps slightly more finicky, but I don't think these data allow for anything else.

```
select
    p.institution_acronym as parent,
    c.institution_acronym as child,
    count(*) c
from
    container c
    inner join container p on c.parent_container_id=p.container_id
where 
    p.institution_acronym != c.institution_acronym and
    c.container_type='collection object'
group by 
    p.institution_acronym,
    c.institution_acronym 
order by
    p.institution_acronym,
    c.institution_acronym
;


 parent | child  |   c   
--------+--------+-------
 KNWR   | UAM    |   328
 MSB    | DGR    |   337
 MSB    | DMNS   |     2
 MSB    | NMMNHS |   165
 MSB    | NMU    |     2
 MSB    | UAM    |   112
 MVZ    | UAM    |     1
 MVZ    | UCSC   |    23
 UAM    | ACBC   |     1
 UAM    | KNWR   |   744
 UAM    | KWP    | 57465
 UAM    | MSB    |     2
```

**Comment by campmlc** [comment]
Some of these are legitimate, as you have described - for example, MSB/DGR  and some MSB/UAM, MSB/NMMNHS - these involve joint relationships, not necessarily something broken. We'll need to address these individually.  One of the biggest is UAM tissues in MSB freezers - these do exist, three freezers worth, and this is going to involve a dedicated project to recatalog them as MSB records linked to UAM vouchers. But in the meantime, can we try out your option to limit students from accidentally scanning or entering the wrong barcode value? I'm not sure I understand exactly what is being proposed or how that will affect workflows - can you explain a bit more? @dusty @AdrienneRaniszewski

**Comment by campmlc** [comment]
And any chance I can get a csv of all the MSB + other institution records in your SQL above?

**Comment by andrew-hope** [comment]
All, Just to circle back to the original issue with the order I placed within the base-36 A**** series, Electronic Imaging apparently will replace the double diot barcodes that were partially duplicated with MSB, but not the ones that were not duplicated. They are pressing me for confirmation of how to move forward with the order. At this point, can I assume that I can ask them to print a new series for the ones that included duplicates, but using base-36 beginning with G****? If they will not reprint the other series, I guess I will need to know whether or not I can use them. I can hold off for a little while longer, but curation here is pretty much stalled until I can use barcodes. There are two issues ongoing that I feel are related, so not sure if this comment is best here or on the other issue.

**Comment by dustymc** [comment]
@andrew-hope sorry I don't think I can be much help. I've laid out what I see as the possibilities, I'm not sure what I can do from there without more directed feedback from the collections. We keep finding things that suggest (3) will eventually become hard to dodge, but we don't have to go there now, I'm not sure how that might affect workflows, and I think those points are mostly *not* from the folks who wander around collections with scanners (eg maybe we're wrong on all of it).

Very big picture, anything you can do to reduce confusion is probably worth doing - if it's possible to get barcodes which can't possibly conflict with or be confused (by humans or machines) with anything else then that's probably the thing to do, if you can't then - well, you tell me, it can certainly be my technical problem (eg, (3) above) but I also think that's likely to have social ripples, or ya'll can avoid those restrictions in some way, or ????

@Jegelewicz thoughts?

**Comment by Jegelewicz** [comment]
The 5 character starting with G base 36 for the remaining four barcodes are reserved for KSB and safe to order. The conflicting A barcodes are something that KSB and MSB need to resolve. The options I see include:

1. Figure out the A series at KSB and remove it from the reserved series that MSB has then reserve them for KSB
2. Send the A series at KSB to MSB, then let MSB order the same quantity of G barcodes for KSB.

Anything I am missing?

**Comment by andrew-hope** [comment]
Ok, thanks both. This all sounds good. I certainly will strive to minimize any issues going forward, and for now, I will proceed with ordering the G-series, and then I will discuss which of the two options Teresa mentioned will be best for MSB. 

Appreciated. More soon once I can figure out the latter point.

**Comment by campmlc** [comment]
I agree with you ordering the 2 part circles reprinted at EIM with the Gseries.  The other three part labels are more problematic for us to use only because of the potential confusion with the Kansas State University label. These are used in so many different ways across our multiple divisions that I don't think we can use them.  But if we could figure out how to remove that series from MSB and assign them to KU, that would work - but I don't know how to do this and would need @dustymc to help.
I  assume would have to change our MSB series going forward to different values.  And that still doesn't solve the problem of MSB barcodes KU has already used that we don't yet have a record of.
I don't think we have responded regarding option 3 above because I don't understand what that entails. Would it allow the same barcodes to be used at different institutions? What do you mean by setting the key to include institution? Perhaps we need a call to go over this.

**Comment by andrew-hope** [comment]
Ok, I'll go ahead with the re-order of the double dots. I also agree that ideally, we would not swap rolls of barcodes, as I think that introduces much more uncertainty for the future like we discussed on the previous zoom call. If there were a way to box off only that series for KSB, remove it from ever being used by MSB, and subsequently, we both stick to our own series (A-series for MSB and G-series for KSB) then perhaps we can keep this an isolated incident??

**Comment by campmlc** [comment]
I'm not understanding (2) and how that affects what is proposed. That solution is the only one that would allow KU to keep the several thousand dollars worth of stickers they ordered in a series that MSB has claimed but not purchased/used. Can we schedule a call?

**Comment by Jegelewicz** [comment]
> Can we schedule a call?

I probably cannot do Thursday. Friday between 11AM and 5PM MDT I might be able to work in.

The issue with #2 is that the base 36 codes aren't really a "series" that can be easily split - but depending on the actual barcodes that are held at KSB, we might be able to work something out or it might be extra complicated. The key to potentially using that solution is knowing what those barcodes are. I wouldn't think that would be super difficult to find out and report?

**Comment by campmlc** [comment]
I have a full list of the new barcodes that KSB ordered that could easily be transferred, including the first and last values. They are at the end of the series that we have ordered, but I don't know how those values translate into the SQL used to reserve a series in Arctos in order to adjust the values MSB has reserved. 
This does not include the 1000 or so that @andrew-hope says they've barcoded with leftover MSB stickers. I have no idea what those are or how to deal with those at this point, other than having them rebarcode them. They need to provide an inventory. But solving the problem of the 25,000 new labels so that KSB can use them would be a huge step in the right direction.

**Comment by campmlc** [comment]
I can do Friday. Let's say 11am MDT?

**Comment by andrew-hope** [comment]
Hi, sorry for the silence, this month is pretty much full tilt for me. I could feasibly meet Friday, but I will be up in Omaha for a local mammal meetings. I can probably find a place with internet and hotspot. 

Again, I'm very sad that this is all happening. If I had lots of money, I could potentially just call it an expensive mistake and move on, but this was one of the last supplies items I bought and I can't afford more until I get more funding. In theory I could arrange my team here to focus on re-stickering all tubes, pages, skull tags etc. etc. to replace all the MSB barcodes, and I will if I have to. But, it will be a heavy undertaking, and likely will not happen fast. Specimen parts are in all stages of the curatorial process. Plus, I'm not sure if it will solve all the problems. I have many parts here which are associated with MSB specimens that will remain here. This may further confuse things. I expect these will become a long-term or permanent loan. 

Would it be possible to figure out the surplus series of stickers I used up, which are MSB barcodes on KSB specimens, and generate an accession for this lot and somehow make it a permanent loan from MSB? That would mean that they have a KSB catalog number, but MSB barcode. Probably not a good option. 

Anyway, I can do 11MDT tomorrow if that is a go for others.

**Comment by campmlc** [comment]
Added to calendar, see you soon. @andrew-hope @mgskinner

**Comment by mgskinner** [comment]
@Jegelewicz @campmlc  we are still on the road. We are hoping to be in secure spot in about 20 minutes. At most we will be a couple minutes late.

**Comment by mgskinner** [comment]
@campmlc @Jegelewicz Andrew is driving can I have the zoom meeting link sent to me. I did not receive that email?

**Comment by dustymc** [comment]
Option (3) - moving the unique constraint to (institution+barcode) - seems the most robust and future-proof solution.

The 'claim' (probably?) allows nonunique claims now, need to confirm. (That is, 10 institutions can - or should be able to - all own a barcode ``1``.)

Claim sheet/documentation should still encourage unique barcodes (eg because they facilitate collaboration).

MSB and KSB will work together, actual barcodes should not be duplicated so there is not an immediate need to move anything in the model (assuming the claim process does in fact allow nonunique). We as a community have some time to try to identify and mitigate for any pitfalls before moving the constraint (but let's don't lose sight of this either).

@campmlc @andrew-hope @mgskinner please fix whatever I got wrong.

**Comment by mkoo** [comment]
Were things resolved then between the two museums? It appears this is not requiring anything software wise but simply all parties working together. Keep this open and rename or close? thx

**Comment by Jegelewicz** [comment]
Sorry I missed all of this - I am just now able to check email today. I hope it is all worked out and if I need to do anything, please let me know.

**Comment by campmlc** [comment]
Great talking with everyone. To summarize according to my understanding:
1) MSB and KSB agree to resolve the current issue through mutual agreement. MSB will discontinue its currently reserved base36 barcode series starting at AE0MR and ending at AEJX6 (base36 conversion of base10 values), which correspond to a series of 25,000 CapNWrap EIM labels ordered by KSB. KSB is free to use these three part labels that they have already purchased and printed with their institutional name.

3) The second set of 25000 values ordered by KSB in the attached file that overlap existing MSB barcodes already in use (ACY1V -ADHCA) will be reprinted by EIM label company with a new set of G-series values specifically reserved for KSB, so these new labels should not pose a problem in Arctos.

4) Both MSB and KSB will stop any future orders of A series base36 values. MSB will request and reserve a new series in Arctos.

5) @dustymc has proposed adding institutional keys going forward to prevent this from happening again, although the recommendation will always be that each institution maintains an unique series within Arctos. How this works out when instititutions are legitimately sharing collection objects across reserved container series will need to be resolved and worked out going forward. This includes MSB/UAM, MSB/NMMNHS, and MSB/KSB collaborations where collection objects such as tissues may be archived in different institutions from the primary object record, e.g. a voucher specimen, in contrast to errors made by accidentally scanning or entering a barcode belonging to a different institution. 


[KU Barcode Label series MSB overlap.pdf](https://github.com/ArctosDB/arctos/files/12896863/KU.Barcode.Label.series.MSB.overlap.pdf)

**Comment by campmlc** [comment]
Here is the file of base36 barcode values that should be transferred to KSB ownership. 
[MSB Barcodes to transfer to KSB ownership.zip](https://github.com/ArctosDB/arctos/files/12900214/MSB.Barcodes.to.transfer.to.KSB.ownership.zip)

**Comment by campmlc** [comment]
MSB will not be discontinuing our existing A series. See edits above. We will just skip the values in use by KSB, which will subsequently for all future orders use their own institutional series to avoid overlap. @andrew-hope

**Comment by dustymc** [comment]
I keep coming around to the idea that VPD-partitioning the container table would be the most robust/only strictly correct solution to this, but I'd also like some illumination on @campmlc 's statement:

>legitimately sharing collection objects across reserved container series will need to be resolved and worked out going forward. This includes MSB/UAM, MSB/NMMNHS, and MSB/KSB collaborations where collection objects such as tissues may be archived in different institutions from the primary object record, e.g. a voucher specimen, in contrast to errors made by accidentally scanning or entering a barcode belonging to a different institution.

Are you scanning eg UAM parts into MSB tubes (or eg installing UAM tubes into MSB boxes??)? Then loaning them under MSB terms, or ?????

See also https://github.com/ArctosDB/arctos/issues/6789#issuecomment-1753156333 - I think most of that *should* be prevented, but would like to hear more before we do anything that would prevent collaboration.

@mkoo @Jegelewicz could/should this be some widely-published meeting (or question, or ???) - I would like to act on this before it goes somewhere crazy and would like to ensure that everyone has ample opportunity to guide that if at all possible.

**Comment by campmlc** [comment]
Some illumination:
1) MSB/UAM:  Because of collaborative research efforts and the transfer of those efforts from MSB to UAM, there are three ULT freezers worth of tissues that are linked to UAM voucher specimens that were transferred to MSB around 2006.  Some of these MSB tissue samples have been recataloged at MSB and barcoded with MSB barcodes, and we have just received funding that can be applied to continue and complete this effort. During discussions over the past decade with @KyndallH at UAM, she was onboard with the transfer and barcoding of these samples in MSB, but she expressed interest in being able to see but not edit the part locations of UAM-linked samples in MSB freezers.  Of course we can also link these tissues to their voucher specimens through reciprocal "same individual as" relationships in Arctos. We haven't started this project yet, so there is flexibility in how this is carried out, but I want to make sure that whatever restrictions are placed for security reasons to prevent mistakes don't restrict legitimate needs for cross-institutional sample viewing and management needed for collaboration between institutions. Note this same situation applies for UAM Ento ectoparasites now cataloged in MSB Para. @DerekSikes 

2) MSB/NMMNHS:  Genetic samples and some vouchers from NMMNHS collections were transferred to MSB over the last decade, prior to NMMNHS moving into Arctos. Tissues are linked to both MSB and NMMNHS vouchers, including samples transferred from another legacy institution, UNLV.  All tissues are cataloged and will remain at MSB, but some legacy tissue parts are also cataloged with NMMNHS in Arctos. These are duplicate records with MSB. So there needs to be some thought as to how this should be managed given potential constraints, especially given these institutions are in multiple collaborative ongoing projects as well. 

3) MSB/KSU(KSB): Similar situation as the above, in that KSU is coming into Arctos but the curator and PI is a former MSB associate, and samples are currently located at KSU that need to be tracked as MSB long term loans. This requires shared inventory management at least initially as they get their object tracking system set up in Arctos. This is complicated by their ordering barcodes in the MSB reserved series. But if we can share permissions with them, we can work together to get this sorted out. 

So yes, in answer to the above, we have UAM parts in MSB boxes, and we are rebarcoding them with MSB barcodes and eventually recataloging them as MSB records linked to UAM vouchers. These are loaned under MSB terms. UAM would like to be able to see where these are, because currently they have the tissue parts at UAM in their "parentless void" location.  Once we have completed the recataloging, rebarcoding, and linking to UAM, this may no longer be an issue. This same situation applies to the other institutions. It is the transitional period I'm concerned about, to make sure restrictions do not prohibit project management. 
@jldunnum @megulbranson  @andrew-hope @amgunderson @lin-fred @DerekSikes

**Comment by Jegelewicz** [comment]
> VPD-partitioning the container table would be the most robust/only strictly correct solution 

I agree. But in order for people to see collaboratively managed containers, we would need to make viewing the storage hierarchy public? That way I could browse UAM's storage even if I couldn't edit anything. I don't think opening object tracking to just anyone makes very good sense, so how could we manage that?

**Comment by dustymc** [comment]
>browse UAM's storage 

If you mean by default, this still seems like a huge security bug. Whether you can see where I keep my gold up or not should be *my* decision, not yours.

>storage hierarchy

Maybe there's some misunderstanding? Containers are containers, VPDs are VPDs, there's no way to sorta-sometimes either. Whatever works for part-containers will also work for campus-containers, and whatever mechanism allows (or prohibits) C also allows (or prohibits) RUD.

>how could we manage that?

More granularity in roles is still my suggestion, and that would still need more focus to become actionable. Whatever the final resolution and/or details, I don't think it can allow blocking what is clearly a huge security-related bug.

**Comment by campmlc** [comment]
Agree with more granularity in roles. And if we had that, viewing permissions could be granted to operators across collections - they could view only in one collection, manage in another. We dont have that capability now.

**Comment by dustymc** [comment]
These barcodes are not within the owning institution's claims.

[temp_noclaim_bc_inst.csv.zip](https://github.com/ArctosDB/arctos/files/13079797/temp_noclaim_bc_inst.csv.zip)

I'll update containers and/or claims very soon if I don't get instructions. HELP!

 @campmlc @DerekSikes @megulbranson @ccicero @mkoo @mlbowser

**Comment by dustymc** [comment]
These labels violate the nonprinting character check. I'll update them to ``gonna_update_label_to`` unless I hear otherwise soon.

[temp_funky_label.csv.zip](https://github.com/ArctosDB/arctos/files/13079891/temp_funky_label.csv.zip)

**Comment by dustymc** [comment]
I will remove all dimensions from these unless I get a better recipe very soon.

[temp_partial_dimensions.csv.zip](https://github.com/ArctosDB/arctos/files/13081430/temp_partial_dimensions.csv.zip)

**Comment by campmlc** [comment]
Dealing with family health care issues but will try to look over these

**Comment by Jegelewicz** [comment]
For the DGR followed by 5 numbers - I think they were expected to fall within "DGR10001- DGR20001"

SQL = barcode~'^DGR[0-9]*$') and substr(barcode,4)::INT between 10001 and 20001

Whatever is needed in the SQL statement to agree with the description should fix those. (change the 4 to 5?)

**Comment by Jegelewicz** [comment]
> These labels violate the nonprinting character check.

I fixed all of the ALMNH labels - they included trailing spaces. Maybe try first removing all trailing spaces and see what is left?

**Comment by dustymc** [comment]
``barcode~'^DGR[A-Z0-9_-]{0,8}$'`` covers them. They're in the list because that's a DGR claim with an MSB container. That's never made any difference before, but it will soon. I suspect the easy thing is to flip all DGR claims and containers to MSB but ???? I don't care how it happens, but allowing nonunique barcodes isn't very compatible with unconstrained claims.

**Comment by Jegelewicz** [comment]
> flip all DGR claims and containers to MSB

That seems reasonable, but @campmlc will have to agree.

**Comment by Jegelewicz** [comment]
> remove all dimensions from these unless I get a better recipe very soon.

I fixed DGR13141

but I don't know what to do with the remaining MSB stuff (weird vials - a lot of parasites)

**Comment by dustymc** [comment]
I believe this is fully functional at test, please test.

The error logs have been suggesting this needs to get to production ASAP.

BUT, I also suspect some MSB folks really need access to DGR containers, would like to hear from @campmlc  on converting if at all possible.

I think everything else can be dealt with at any time.

**Comment by dustymc** [comment]
I changed ownership of these containers:

[temp_noclaim_bc_inst.csv.zip](https://github.com/ArctosDB/arctos/files/13210680/temp_noclaim_bc_inst.csv.zip)


I manipulated these labels:
[temp_funky_label.csv.zip](https://github.com/ArctosDB/arctos/files/13210681/temp_funky_label.csv.zip)

I remove dimensions from these containers:

[temp_partial_dimensions.csv.zip](https://github.com/ArctosDB/arctos/files/13210684/temp_partial_dimensions.csv.zip)

**Comment by ccicero** [comment]
@dustymc Looking at barcode series and see your entry:

![image](https://github.com/ArctosDB/arctos/assets/967275/5a7eeb69-e899-4c13-8399-a27ec0e7f45d)

I tried deleting but don't have permissions - ? I'm not sure about this one but we have a working barcode series for our LN2 chest freezer:

![image](https://github.com/ArctosDB/arctos/assets/967275/57195a2e-ebc9-4e05-a9aa-339e930e866e)

Can you please delete the messy one? Thanks!

**Comment by dustymc** [comment]
@ccicero please confirm that you mean https://arctos.database.museum/info/barcodeseries.cfm?action=edit&key=666455329 should be DELETED.

**Comment by dustymc** [comment]
@ccicero these are the containers using the claim I think you want deleted, please advise.

```

arctosprod@arctos>> select barcode from container where institution_acronym='MVZ' and barcode~'^LN2CF-[A-C]{1}-[0-9]{1,2}$'
arctos-> ;
  barcode   
------------
 LN2CF-A-1
 LN2CF-A-2
 LN2CF-A-3
 LN2CF-A-4
 LN2CF-A-5
 LN2CF-A-6
 LN2CF-A-7
 LN2CF-A-8
 LN2CF-A-9
 LN2CF-A-10
 LN2CF-B-1
 LN2CF-B-2
 LN2CF-B-3
 LN2CF-B-4
 LN2CF-B-5
 LN2CF-B-6
 LN2CF-B-7
 LN2CF-B-8
 LN2CF-B-9
 LN2CF-B-10
 LN2CF-C-1
 LN2CF-C-2
 LN2CF-C-3
 LN2CF-C-4
 LN2CF-C-5
 LN2CF-C-6
 LN2CF-C-7
 LN2CF-C-8
 LN2CF-C-9
 LN2CF-C-10
(30 rows)
```

**Comment by campmlc** [comment]
@dustymc can you send a list of what containers are under DGR as institution? Yes, MSB folks need access, but I'll need to look over first to decide in conversion

**Comment by dustymc** [comment]
Please open issues for any remaining questions.

**Comment by campmlc** [comment]
@dustymc Can you please re-run this script from above and provide a csv? It times out when I try it.

> select
>     p.institution_acronym as parent,
>     c.institution_acronym as child,
>     count(*) c
> from
>     container c
>     inner join container p on c.parent_container_id=p.container_id
> where 
>     p.institution_acronym != c.institution_acronym
> group by 
>     p.institution_acronym,
>     c.institution_acronym 
> order by
>     p.institution_acronym,
>     c.institution_acronym
> ;
> 
>  parent | child  |   c   
> --------+--------+-------
>  KNWR   | UAM    |   839
>  MSB    | DGR    |   337
>  MSB    | DMNS   |     2
>  MSB    | NMMNHS |   165
>  MSB    | NMU    |     2
>  MSB    | UAM    |  2439
>  MVZ    | UAM    |   733
>  MVZ    | UCSC   |    23
>  UAM    | ACBC   |     1
>  UAM    | KNWR   |  1060
>  UAM    | KWP    | 57465
>  UAM    | MSB    |     6
>  UAM    | MVZ    |   187
> ```
>

**Comment by campmlc** [comment]
@dusty can you please provide a csv of the records that result from this query? I need a list of the barcode values, which I can't get from the SQL tool.

select
    p.institution_acronym as parent,
    c.institution_acronym as child,
    count(*) c
from
    container c
    inner join container p on c.parent_container_id=p.container_id
where 
    p.institution_acronym != c.institution_acronym
group by 
    p.institution_acronym,
    c.institution_acronym 
order by
    p.institution_acronym,
    c.institution_acronym
;

**Comment by campmlc** [comment]
@dustymc apologize for missing this - yes, MSB folks need access to DGR containers. I see 337 shared - is that all of them? Can you provide the list requested above?
> 
> BUT, I also suspect some MSB folks really need access to DGR containers, would like to hear from @campmlc on converting if at all possible.
> 
.
The challenge here is that there are items cataloged in DGR that other collections do not want to manage due to reasons. Any way to recatalog all of them in the new collection "MSB:DGR"?

**Comment by dustymc** [comment]
@campmlc please open a new issue with your functional needs, this has long been resolved and contains lots of complexity that can no longer be relevant.

**Comment by campmlc** [comment]
@dusty Please explain and provide documentation as to the the resolution. Under the new constraints, can anyone with MSB access to containers see DGR containers?
