### ISSUE TITLE
Catalog numbers in MorhpoSource

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#6790]
MorphoSource is displaying our catalog numbers incorrectly (e.g., https://www.morphosource.org/concern/biological_specimens/000551560)
Institution code and collection code are repeated in the identifier data that MorphoSource displays (e.g., DMNS:Mamm:DMNS:Mamm:6456 Gorilla gorilla). 
This is because we send the Institution code (DMNS), collection code (Mamm), and catalog number (as DMNS:Mamm:6456) to iDigBio; MorphoSource pulls this data in and concatenates it together. 
MorphoSource considers this an Arctos problem: 
_Unfortunately we have little power here. DMNS as the author of the metadata we pull in needs to change their recordset format if you want things displayed differently. In other words this is something for you to discuss with whomever handles your arctos database. Does that make sense?_

Should we be sending out our catalog numbers without the guid_prefix or do we need to push back on MorphoSource to be more creative? This is an issue for all Arctos records where MorphoSource is pulling data from iDigBio (I saw MVZ, UTEP, MSB, etc.). @mkoo @mvzhuang @campmlc @dustymc

**Comment by mkoo** [comment]
This seems to be a MS issue if they are displaying IPT data incorrectly. @atrox10 can we set up a call with Morphosource principals to fix?

**Comment by dustymc** [comment]
Done?
