### ISSUE TITLE
Feature Request - notnull for barcode search

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#6803]
The search page allows us to find records with barcode = NULL but I'd like to be able to search for records that have barcode = NOTNULL.

If someone could provide the SQL for a search of UAM:Ento and KWP:Ento with family = Pieridae and barcode = NOTNULL

that would also work (but the permanent fix to the search page would benefit more people I think).

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._
medium

**Comment by Jegelewicz** [comment]
@dustymc possible to add the "%" option in this field?

**Comment by DerekSikes** [comment]
Can this get added to the next release?

**Comment by dustymc** [comment]
Sorry, I missed this - @mkoo  can we PLEASE either close or make actionable some Issues, I am constantly lost in clutter that I don't think can be addressed lately. https://github.com/ArctosDB/arctos/issues?q=is%3Aopen+is%3Aissue+milestone%3Amystery certainly isn't all of that, but it might be a convenient place to start.

ANYWAY - this has the potential to melt things, but so does the existing NULL option so - sure?
