### ISSUE TITLE
Request reset of password link for undergrad CA

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#6804]
@dustymc - sorry to bother, could we get a reset password email sent to user: jturcotte
please?

My undergrad CA entered his password incorrectly into Arctos and now he needs to get a new one.

**Comment by ewommack** [comment]
Oooh wait, can I do that? Do I just click the little "Reset" button in the Arctos operator profile?

**Comment by dustymc** [comment]
yep

**Comment by ewommack** [comment]
Ah fantastic, thank you!

Is this something we might want to update the documentation for? I took a peak through the handbook and didn't find it in the manage operator section.

**Comment by mkoo** [comment]
Answered!
![Firefox_Screenshot_2023-10-05T19-56-45 441Z](https://github.com/ArctosDB/arctos/assets/2523089/08f450f6-e765-4873-90f0-73ec3149ff02)

**Comment by ewommack** [comment]
@mkoo I was actually meaning the "reset" link you find under the operator profile when you are managing it under their password. I didn't know I could reset their password lock myself.

**Comment by Jegelewicz** [comment]
@ewommack I trust that you can update documentation as necessary!

**Comment by ewommack** [comment]
Yep just asking to make sure we wanted that out there.
