### ISSUE TITLE
rebuild citation bulkloader

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6805]
I'm doing my first citation upload since the update and it looks like the new upload format is going to add a lot of work manually adjusting rank. I don't see rank in template? This form defaults to 1?

I need to fields for:
-Set rank of the new citation ID. We're uploading lots of old records, many of these ids are no longer the accepted ID.
-Set the rank of the existing IDs. This could be a simple, set all other ids to this rank, if blank do nothing with the existing IDs.

I'll go forward with my current load, but I can't do any other citation uploads until this is fixed.

_Originally posted by @Nicole-Ridgwell-NMMNHS in https://github.com/ArctosDB/arctos/issues/6607#issuecomment-1749396319_

**Comment by dustymc** [comment]
> Set rank of the new citation ID.

``identification_order`` is in the template, looks like it was just missed in the map.

>Set the rank of the existing IDs.

Works for me.

Are there any other requests, or should this be prioritized?

I'll tentatively go direct, I think this is a mix of bugfix and minor addition.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> is in the template

Ah thanks!

> Are there any other requests

I don't have any others.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thank you!
