### ISSUE TITLE
Add identifiers from components to entity records

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6807]
@dustymc I am planning to work up an Entity demo fro the next AWG meeting. I'd like to make sure that all existing entities have the appropriate identifiers associated with them. Can you get me a file that includes the identifiers for all of the component records associated with them. I need

Entity GUID | Component GUID | Component Identifier Type | Component Identifier Value | Component Identifier Issued By | Component Identifier Remark 
 -- | -- | -- | -- | -- | -- 

there would be a row for each component identifier.

Make sense?

I'll go through them and build an identifier load for the Entity records.

I thought about searching for all records with %Arctos:entity% in identifier values, but a lot of them are in collections to which I don't have access so I can't use the identifier view/download :-(

**Comment by dustymc** [comment]
If you can't download you certainly can't upload?!

**Comment by Jegelewicz** [comment]
> certainly can't upload?!

True - but I can build the file and ask someone to do it (less work than asking them to build the file too...)

**Comment by Jegelewicz** [comment]
I have uploaded identifiers for the following issuers to the Entities:

ABQ BioPark Zoo Local Identifier
East Bay Regional Park District
GAN - Global Zoological Accession Number
USGS Bird Banding Laboratory

as well as the identifier "names" for the zoo animals

In the process, I found that the following are listed as identifiers on some catalog records, but the links are malformed and the numbers they reference appear to be incorrect. leftovers from when we were first experimenting with entities. I'll review and see if I can get them sorted out.

https://arctos.database.museum/entity/1
https://arctos.database.museum/entity/2
https://arctos.database.museum/entity/3
https://arctos.database.museum/entity/4
https://arctos.database.museum/entity/5

data
[ArctosDataoJstAkuyzS.csv](https://github.com/ArctosDB/arctos/files/13191609/ArctosDataoJstAkuyzS.csv)

**Comment by Jegelewicz** [comment]
https://arctos.database.museum/entity/3 was on a single UTEP:Ento record - and I assume it was going to be a demo for a "lot" entity that was never completed, so I just deleted the identifier.

**Comment by Jegelewicz** [comment]
https://arctos.database.museum/entity/1
https://arctos.database.museum/entity/4
https://arctos.database.museum/entity/5

are all zoo animals that apparently never had an entity created. I created the three entities, unloaded the malformed entity identifiers and loaded new ones.

malformed organism ID | new organism ID
 -- | -- 
https://arctos.database.museum/entity/1 | 
https://arctos.database.museum/entity/4 | 
https://arctos.database.museum/entity/5 | 

I also renamed the available accessions so that it is easier to pick an appropriate accession during data entry.

@ccicero the records with

https://arctos.database.museum/entity/2

are MVZ birds - so I am unable to fix them. they either should be connected to an actual entity url or one should be created for them. Let me know if you have any questions.

Data
[ArctosDataoJstAkuyzS.xlsx](https://github.com/ArctosDB/arctos/files/13192148/ArctosDataoJstAkuyzS.xlsx)

**Comment by ccicero** [comment]
@Jegelewicz https://arctos.database.museum/entity/2 is the 1840's 3-piece Day Dress - ???

**Comment by campmlc** [comment]
I'm very confused - https://arctos.database.museum/guid/Arctos:Entity:1 is a chimpanzee that we have cited in projects and publications. And yet the link above has been deprecated?

**Comment by Jegelewicz** [comment]
https://arctos.database.museum/entity/1 was deprecated not https://arctos.database.museum/guid/Arctos:Entity:1

**Comment by Jegelewicz** [comment]
@ccicero I am not talking about 

Please see https://arctos.database.museum/guid/MVZ:Bird:193195 and https://arctos.database.museum/guid/MVZObs:Bird:4777

which have this identifier `https://arctos.database.museum/entity/2`

![image](https://github.com/ArctosDB/arctos/assets/5725767/45041c4b-4cc7-4079-948d-5654f7c61a52)

That is NOT a properly formed Arctos entity url. I don't know what entity this is supposed to be, but clearly it is NOT the dress, which is actually https://arctos.database.museum/guid/Arctos:Entity:2 Please note the difference:

https://arctos.database.museum/entity/2
vs
https://arctos.database.museum/guid/Arctos:Entity:2

and just try to click that first link - it isn't a thing!

**Comment by Jegelewicz** [comment]
@campmlc @ccicero also see the data in [this comment](https://github.com/ArctosDB/arctos/issues/6807#issuecomment-1783356987). The records that had https://arctos.database.museum/entity/1 (malformed link)

are all a Mexican Wolf for which an entity did not exist, so I created one and added the properly formatted entity url to the wolf records. This had NO impact at all on https://arctos.database.museum/guid/Arctos:Entity:1

GUID | SCIENTIFIC_NAME | OTHERCATALOGNUMBERS
-- | -- | --
MSB:Mamm:233254 | Canis lupus baileyi | NK 108353 \| NK 226810 \| NK 296562 \| NK 296707 \| Organism ID   https://arctos.database.museum/entity/1 \| United States Fish and Wildlife   Service Mexican Wolf Recovery Program studbook 1216
MSB:Mamm:233261 | Canis lupus baileyi | NK 108340 \| Organism ID https://arctos.database.museum/entity/1 \| United   States Fish and Wildlife Service Mexican Wolf Recovery Program studbook 1216
MSB:Mamm:233262 | Canis lupus baileyi | NK 108358 \| Organism ID https://arctos.database.museum/entity/1 \| United   States Fish and Wildlife Service Mexican Wolf Recovery Program studbook 1216
MSB:Mamm:233267 | Canis lupus baileyi | NK 108363 \| Organism ID https://arctos.database.museum/entity/1 \| United   States Fish and Wildlife Service Mexican Wolf Recovery Program studbook 1216
MSB:Mamm:268079 | Canis lupus baileyi | NK 226653 \| Organism ID https://arctos.database.museum/entity/1 \| United   States Fish and Wildlife Service Mexican Wolf Recovery Program studbook 1216
MSB:Mamm:270001 | Canis lupus baileyi | NK 226700 \| Organism ID https://arctos.database.museum/entity/1 \| United   States Fish and Wildlife Service Mexican Wolf Recovery Program studbook 1216

I think these malformed urls were left behind from when we were first developing the Entity model.

**Comment by dustymc** [comment]
Don't think there's anything to do here
