### ISSUE TITLE
Historical specimens from Borneo not enterable

### ISSUE THREAD

**Issue by Awkwardtree13** [ArctosDB/arctos#6812]
Our collection has several specimens from about a century ago with "Borneo" as the only location given. The isle of Borneo is in modern times split between multiple countries, and thus we can't just choose one or the other. Would it be possible for Borneo to be added as a valid Higher Geography, so these specimens could be entered into the database?

**Comment by dustymc** [comment]
See https://handbook.arctosdb.org/documentation/higher-geography.html

https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10016350 is appropriate geography.

**Comment by Jegelewicz** [comment]
@Awkwardtree13 I would suggest using no specific higher geography, then put Borneo in specific locality.

**Comment by Awkwardtree13** [comment]
This is more or less what I was planning, now that I’ve been reminded that “no specific higher geography” is an option the system accepts.
