### ISSUE TITLE
Unable to Delete Parts

### ISSUE THREAD

**Issue by Cpittman53** [ArctosDB/arctos#6816]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Attempted to delete a part but was unable to and received an error message.

**To Reproduce**
1. Go to any specimen record (In this case DMNS:Bird:44408)
2. Click on 'Edit Parts'
3. Click on 'Delete Cascade' for "Whole Organism"

Error ID: 377943F0-39BF-448B-A47C57F28DEAFC8E

</body>
</html>

**Expected behavior**
The "Whole Organism" Part would be deleted.

**Screenshots**
[ERROR_Oct_09_2023.docx](https://github.com/ArctosDB/arctos/files/12848655/ERROR_Oct_09_2023.docx)

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**
 - OS: Widndows
 - Browser Chrome
 - Version 117.0.5938.149

**Priority**
High priority

**Comment by dustymc** [comment]
patched
