### ISSUE TITLE
Arctos Report Template Request: MSB:Mamm loan invoice template repairs and modification for Zoo samples

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6818]
**Description of the report** - I need a loan invoice report for MSB:Mamm that allows the option of printing other types of identifiers instead of the "NK".  I tried cloning the existing MSB:Mamm loan invoice template and changing the "NK" field to "Albuquerque Biopark Zoo Local ID" identifier, but I apparently didn't do it correctly. Now neither that template nor the original MSB:Mamm loan invoice template are working. 
The immediate need is to get the MSB:Mamm Loan Invoice Detail html working as soon as possible, and then fix whatever necessary to allow the Biopark Zoo ID for the new template, MSB:Mamm Loan Invoice Zoo html.

**Collection for which the report is needed** - MSB:Mamm

**Priority** - High. Impeding work.

**Comment by Jegelewicz** [comment]
If no changes were made to the original - it should still work?

**Comment by campmlc** [comment]
I didn't consciously make any changes, just used the copy button, but now it doesn't work?

Mariel Campbell   (she/her)
Collection Manager, Division of Genomic Resources
Museum of Southwestern  Biology

Shipping Address:
Museum of Southwestern Biology
Division of Genomic Resources
1 University of New Mexico
MSC03 2020
Albuquerque, NM 87131

(505) 277-7808 office
email: ***@***.***


________________________________

**Comment by Jegelewicz** [comment]
@dustymc I found something

`ERROR: column loan_item.collection_object_id does not exist Position: 1472`

Seems like this is part of recent updates? What new header is needed?

**Comment by dustymc** [comment]
I fixed https://arctos.database.museum/Reports/reporter.cfm?action=edit&report_id=91

>What new header 

https://arctos.database.museum/tblbrowse.cfm?tbl=specimen_part

**Comment by Jegelewicz** [comment]
means that other MSB loan detail reports will need fixing too - leave open until done

**Comment by dustymc** [comment]
went through reports, fixed the obvious

**Comment by Jegelewicz** [comment]
Thanks man!

**Comment by campmlc** [comment]
Thanks to you both!
