### ISSUE TITLE
Update portal page

### ISSUE THREAD

**Issue by jldunnum** [ArctosDB/arctos#6819]
The portal page does not reflect the list/number of collections and institutions listed in the system stats page

**Comment by Jegelewicz** [comment]
Because some collections have encumbered data or have not yet entered any records.

**Comment by mkoo** [comment]
@jldunnum did you have a specific collection that you were wondering about? if this was a general question that Teresa was able to answer, let's close the issue!

**Comment by jldunnum** [comment]
No I just noticed the numbers didn’t match so brought it up.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mkoo** [comment]
thx!
