### ISSUE TITLE
Need Help with Arctos Error - "Create New Specimen/Event" not responding!

### ISSUE THREAD

**Issue by jtgiermakowski** [ArctosDB/arctos#6821]
# Error Text
**Copy the text from the page and paste it here**

No text, just unresponsive to creating a New Event, i tried two different browsers.

https://arctos.database.museum/specLocality.cfm?collection_object_id=31951852#specimen_event_new

# Where it happened
**Provide a link to or a description of the page where the error occurred.**

https://arctos.database.museum/specLocality.cfm?collection_object_id=31951852#specimen_event_new

![Screenshot 2023-10-09 at 15-58-01 MSBObs Herp 7 Pseudacris regilla](https://github.com/ArctosDB/arctos/assets/2381228/626e4622-96a6-4959-847d-81a529bbbbbf)

# Steps to get there
**Describe the actions that led to the error**

uploaded new records through bulkloader but needed to create a locality for this record after getting additional information from collector

# Problem
**Community response to describe the problem that caused the error**

# Solution
**Community response with directions for how to correct the problem**

**Comment by dustymc** [comment]
Not sure how you got there, but that's an iframe URL. 

https://arctos.database.museum/guid/MSBObs:Herp:7 then Locality tab then

<img width="795" alt="Screenshot 2023-10-09 at 15 05 10" src="https://github.com/ArctosDB/arctos/assets/5720791/4a533658-45fe-4018-9ebd-85f486e7e2c3">

works for me (and please delete that or let me know when you're done with it so I can)


<img width="1620" alt="Screenshot 2023-10-09 at 15 06 41" src="https://github.com/ArctosDB/arctos/assets/5720791/3e63bf33-ef00-4b5c-990b-d2b7c2aedda8">

**Comment by jtgiermakowski** [comment]
Hmmm... yes, weird URL and thanks for a quick response. I was able to get it to work. Started with a fresh login.

cheers, Tom
