### ISSUE TITLE
Need Help with Arctos Error

### ISSUE THREAD

**Issue by AdrienneRaniszewski** [ArctosDB/arctos#6825]
# Error Text
duplicate key value violates unique constraint "specimen_part_pkey"

# Where it happened
when loading records in the bulkloader. every single record entered by user litsawooten. Prior to this she's entered many records in the same way that did not get this error.

# Steps to get there
litsawooten enters data into the bulkloader via the "2022.011 Hope" data entry profile, as usual. I set to autoload_extras. wait. get error on every single record

# Problem
they won't load and I don't understand the error message

# Solution
??

**Comment by dustymc** [comment]
Thanks, should be patched, please check https://arctos.database.museum/guid/MSB:Mamm:347701 carefully though - WHOEVER made that one mistake might have made others....

**Comment by AdrienneRaniszewski** [comment]
what was the mistake?

**Comment by dustymc** [comment]
I - err, someone... -  missed something in the last update - I used to have to make a bunch of precursors (which mint IDs) before making parts, now I can just make parts, SOMEONE was trying to use an unminted ID. (That same _someone_ is very confused about how that got through our near two weeks of testing, but here we are....)

**Comment by AdrienneRaniszewski** [comment]
ah! So not SOMEONE on our end! haha. thanks, Dusty!

**Comment by dustymc** [comment]
Ah sorry, no, your end looks fine, that record loaded smoothly once I uncrossed my wires.
