### ISSUE TITLE
Data download requests

### ISSUE THREAD

**Issue by jldunnum** [ArctosDB/arctos#6826]
Where do we see the queue for these requests and how long do they take? Is it automated or does someone have to push a button? Thanks

**Comment by dustymc** [comment]
> Requests may be tracked though Async Requests (username tab). 

>how long do they take?

However long it takes, but usually less than an hour.

>automated

Of course!

**Comment by dustymc** [comment]
That's straight from the creation form

<img width="1513" alt="Screenshot 2023-10-11 at 10 08 45" src="https://github.com/ArctosDB/arctos/assets/5720791/2e4124a6-d381-4da6-9fa3-9a28485251dd">

I can change it, but I'll need specifics.


<img width="282" alt="Screenshot 2023-10-11 at 10 09 45" src="https://github.com/ArctosDB/arctos/assets/5720791/62a0a94e-8081-429f-8137-31b6e1b0eaf1">

**Comment by jldunnum** [comment]
Hmm, I don't believe thats what I saw when I did it...

**Comment by jldunnum** [comment]
Got it, that shows up on the request page before you submit, not after.
