### ISSUE TITLE
Remove restriction on container labels for data entry

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6827]
Request:  Allow data entry and bulkloading of records even if the part barcode is a label of some kind.  Any restrictions on labels as containers should be at the level of object tracking, not at the level of data entry. 

Justification:  Our institutional workflows frequently do not allow for prior knowledge of what type of sample will be assigned to a particular barcode. Barcodes are assigned in the field and prep lab to both cryovials and to parasite vials, and sometimes to whirlpack bags, at the time a specimen is being prepped. If these are scanned into position in a freezer box, they will autoconvert to cryovials. But those that aren't - for example, in cases where a sample is still in processing before cataloging occurs, or when a sample is set aside to be issued on loan pending cataloging, or when a label is applied to a vial or bag instead of a cryovial - this currently blocks cataloging. And the error in the bulkloader does not specifiy which part is in the offending barcode - a particularly difficult problem to resolve when we have 5 or more barcoded parts per record, of which only one might be causing the error, in a bulkloaded accession of hundreds of records.  Note that some years ago, this restriction did not exist, so we are requesting that it be removed.

One of the reasons that students are being given inappropriately advanced permissions in object tracking has been that collections are running up againsts restrictions like these that affect their immediate workflows and ability to function, and so CMs are coming up with creative ways to bypass the restrictions that end up taking enormous time and effort and make even bigger messes. 

From @AdrienneRaniszewski 

"Sometime in the last three days or so Arctos stopped allowing new records that students are entering to even be saved to the bulkoader if the barcode is still classified as a label. In this particular case they appear to be primarily the vials from the Sev that are on loan..

Seems to me the simplest solution would be to convert ALL of our barcodes that are still “cryovial labels” to “cryovials.” This would make life easier in many other ways too! Is that something you can do?

The only other options that I can think of are:

1)When a record won’t save, edit the container types one by one. go back and try saving the record again. Time consuming
2) When a record won’t save, add the problem-causing barcodes to a bulk edit file. I load the file once they’ve gone through all the records. Then they go back and re-enter all the records that wouldn’t save the first time. Even more time consuming.

So not really options, in my opinion. Thoughts?"

**Comment by AdrienneRaniszewski** [comment]
the inability to even save is new. And means we can't do much work at all. I am hoping Mariel (or Dusty) would be able convert all remaining "cryovial labels" to "cryovials" so we could get working again while the larger permissions and restrictions issues are sorted out. Thanks!

**Comment by AdrienneRaniszewski** [comment]
Mariel says she can convert them. but the larger issue still need to be resolved. And I'm in agreement with Mariel!

**Comment by dustymc** [comment]
Yes, there are bulk conversion tools and I'm happy to make updates or provide data for the tools or whatever.

The check is from https://github.com/ArctosDB/arctos/issues/6820, which was implemented as an emergency because I don't think it can realistically be viewed as anything else. That could potentially be refactored to work in some other way, but I'd need explicit and actionable instructions. (If I had any better ideas I'd have used them!)

I cannot support preemptively removing everyone's guardrails, but somehow strictly isolating containers (https://github.com/ArctosDB/arctos/issues/6789) might change that conversation. I think it would always need the full understanding and support of The Community.

https://handbook.arctosdb.org/documentation/container.html originates from about this situation.

**Comment by campmlc** [comment]
Please see #6820. "Some updates to this issue: currently the mammal division is working around the problem by having students enter the record and parts without barcodes, which allows the record to save to the bulkloader. Then they have to go Browse and Edit and click edit the record, and then enter the barcodes separately. That apparently works, but takes much more time and risks a barcode getting added to the wrong sample since it can't be done simultaneously with data entry. Plus, it makes no sense to prohibit save but allow editing for the same data by the same agent in data entry. "
At the very least, whatever is preventing students from being able to save to the bulkloader needs to be removed. Then collection managers can at least address the records that get errors regarding parts in container labels. @dustymc

**Comment by dustymc** [comment]
Is my offer [above](https://github.com/ArctosDB/arctos/issues/6827#issuecomment-1758199263) not satisfactory for some reason? It seems that MSB isn't using the protections offered by label-type containers so I'm not sure that changing them to something else would have any costs to ya'll, while removing the other guardrails clearly does have significant costs to other collections.

**Comment by campmlc** [comment]
I think we are having trouble understanding each other. What we are asking for is fix whatever happened three days ago that no longer allows records to save to data entry if one of the containers is a label. This is not asking for these records to load from the bulkloader. This records will still produce an error saying that a label cannot be a parent. But it will allow collection staff to find and fix these problems. Until just the other day -  this was possible. 
Based on this information, I will convert all unused labels in MSB collections to cryovials, but I want the ability to review these to see how they are being used, so I do not want to request a global DBA conversion. But right now, I can't even find out which labels are causing the problem because the records will not save to allow for browse and edit review by someone with manage or admin container access. 
And the current restriction is NOT WORKING - because students re-enter all the data ove again, this time without the barcodes, go into browse and edit, and edit in the bulkloader to successfully add the forbidden labels anyway. In the process, they likely make mistakes and certainly waste an enormous amount of time. 
@AdrienneRaniszewski

**Comment by dustymc** [comment]
You are asking for the ability to enter the wrong thing in the wrong field, and thereby take over other collection's containers. https://github.com/ArctosDB/arctos/issues/6789#issuecomment-1752233387 I still cannot see any way that can be viewed as anything other than a critical security bug, which is how it was addressed.

>still produce an error saying that a label cannot be a parent

That's an entry-only form, it *_must_* either succeed or fail, getting stuck in the middle isn't an option.

**Comment by campmlc** [comment]
I don't understand what changed in the last few days, then? Because until then, the data could be saved to the table, where they could received appropriate errors on being marked to load and be reviewed and corrected by a CM. For example, see below for records entered 2023-10-05 with just such an error. Under the current constraint, this record would have failed on save in data entry, disallowing review and correction.

![Screenshot 2023-10-11 17 49 00](https://github.com/ArctosDB/arctos/assets/14808196/8897ef0e-e15e-4196-9f65-e5c1172acb59)

**Comment by campmlc** [comment]
> Yes, there are bulk conversion tools and I'm happy to make updates or provide data for the tools or whatever.
> 
> The check is from #6820, which was implemented as an emergency because I don't think it can realistically be viewed as anything else. That could potentially be refactored to work in some other way, but I'd need explicit and actionable instructions. (If I had any better ideas I'd have used them!)

FWIW There are existing records in Arctos that are associated with container labels from before this restriction - for example, see A5Z2V. There are also records in the Browse and Edit from a week or so ago from prior to this restriction - these have errors related to putting a part into a label but at least they are saved and can be dealt with. But now with this new restriction all data entry using barcodes is being entered separately at high risk of error, eg parts being manually added to the wrong barcodes. To put a stop to this, I need urgent help.

I tried to use the tools at my disposal - Tools: Container from Barcode and GUID from Barcode to find and convert all barcodes as labels not associated with parts from an order of 125000 barcodes in 2017, but the tools time out through the browser. 

So I am going to have to ask @dustymc to help with bulk conversion tools. For all MSB barcodes, we need:
1)  A list of all MSB cryovial labels including associated guids and containers/parts
Once we have the above please convert all cryovial labels in MSB to cryovials. Hopefully this won't break anything.

**Comment by dustymc** [comment]
> list of all MSB cryovial labels including associated guids and containers/parts

Here you go, but this is all label-type containers, should be easy to filter if a subset is truly what's needed.

[temp_msb_lbl.csv.zip](https://github.com/ArctosDB/arctos/files/12961623/temp_msb_lbl.csv.zip)

**Comment by mkoo** [comment]
@campmlc this appears to have a solution that will fix the problem without significant programming.... ok to close?

**Comment by campmlc** [comment]
Not yet, please. I'd like to actually implement the fix and see if it works.

**Comment by dustymc** [comment]
Emergencies have long since been resolved, this does not seem to be a problem, closing.
