### ISSUE TITLE
Unable to delete records listed in Records for Deletion encumberance

### ISSUE THREAD

**Issue by genevieve-anderegg** [ArctosDB/arctos#6829]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
We have three records that we would like to delete, because they were entered with the wrong catalog numbers (we have entered the records correctly, so no data will be lost upon the deletion of these incorrect records). We have moved them to our "Records for deletion" encumbrance (10000684), but when we go to Delete all Records in this Encumbrance -> Delete these Records, we get an error.

**To Reproduce**
1. Go to encumberance ID=10000684 "Record for deletion", user=ganderegg
2. Try to delete the records as usual

**Expected behavior**
Records are deleted.

**Screenshots**
![image](https://github.com/ArctosDB/arctos/assets/83782023/004d5b9e-6690-416d-bdc2-cd022bf40ce3)

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**
 Windows, Chrome

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by dustymc** [comment]
Thanks, indeed a bug, I'll get it for next release (early next week).

**Comment by genevieve-anderegg** [comment]
Thank you Dusty! Glad it wasn't user error!
