### ISSUE TITLE
Long 'Higher Geography' name is truncated

### ISSUE THREAD

**Issue by genevieve-anderegg** [ArctosDB/arctos#6830]
FYI Today one of my volunteers noticed that a higher geography name was truncated: "Chile, Libertador General Bernardo O'Hi " (id=1006071), which should be "Libertador General Bernardo O'Higgins Region", a first level administrative district of Chile. The truncated nature of this name made the higher geography hard to find during data entry. 
Are higher geography names/values limited to a certain number of characters? Is this a byproduct of downloading from GADM (even though the whole name appears correctly in GADM)? Could there be other instances of truncation, or is this just an oops? I'm always happy to help with a large cleanup effort, let me know if this uncovers something that needs cleaning!
![image](https://github.com/ArctosDB/arctos/assets/83782023/56b554e5-4eeb-4996-9e2f-92a5980f209a)

![image](https://github.com/ArctosDB/arctos/assets/83782023/62441861-15e2-431d-8252-cce9ee31482e)

**Comment by dustymc** [comment]
Yea, either GADM or the (sorta primitive) tools I use to pull GAMD into Arctos seem to be a bit choppy - the matching remark definitely wouldn't have been truncated on my end.

I changed https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=1006071 to match https://gadm.org/maps/CHL/libertadorgeneralbernardoohiggins.html

https://github.com/ArctosDB/arctos/issues/5597 sure would be cool @mkoo ....
