### ISSUE TITLE
Accidentally overwrote report

### ISSUE THREAD

**Issue by adhornsby** [ArctosDB/arctos#6831]
With the hugest of apologies to @ebraker , it appears that I accidentally overwrote the report CFM portion of UCM Loan Header report in the midst of trying to update the Bell Museum invoice.  Wreaking havoc from Minnesota already.

https://arctos.database.museum/Reports/reporter.cfm?action=edit&report_id=41

@dusty @Jegelewicz @lkvoong I'm desperately hoping there's some way to retrieve an archived version of Emily's report?

Edit history is: Created by Lam Voong on 2022-10-28 for collection UCM:Mamm. Last modified by Angela D. Hornsby on 2023-10-12. Last accessed on 2022-10-28.

**Comment by dustymc** [comment]
I dump an archive in https://github.com/ArctosDB/arctos-assets whenever I think about it (just added one!), but I'm not sure what version might be most current.

**Comment by adhornsby** [comment]
Thanks @dusty, there's a version from four months ago, so I restored to that.  And apologies again @ebraker , the four month old version looks the same, so my fingers are crossed that this doesn't make any headaches for you, major or minor.
