### ISSUE TITLE
Barcode Series Request - MSB C series

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6833]
Issue Documentation is at http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html 
Barcode Series Documentation is at http://handbook.arctosdb.org/documentation/container.html#barcode-series

Please supply the following so that we can evaluate your barcode series request. If the series is available, it will be claimed and created for you. If it is not, a response will be posted to this issue and we will work to get you a suitable barcode series.

First barcode in series: _C0000_____

Last barcode in series: __CZZZZ________

Rules for creating random letters or digits:
I would like all barcodes to have 5 places, start with a C, and the remaining 4 places can be any combination of capital letters A-Z or numbers 0-9. This C series corresponds to a total of 1,679,616 reserved values converted from base10 to base36.
Based on the SQL in Arctos for the current MSB A series, I believe that the SQL should be "barcode~'^C[A-Z0-9]{4}$' but please confirm.

Additional context Add any other context or screenshots about the feature request here:
This series will replace the MSBs current reserved A series to avoid overlap with a Kansas State University order. The C series corresponds to new barcodes that will primarily be used for cryovials in the Division of Genomic Resources (DGR) at MSB, but that may be shared between all MSB divisions. I have tested this against the barcode reserve tool in Arctos, but again, please confirm.

**Priority**
High. Needed for work and issue resolution #6789.

**Comment by Jegelewicz** [comment]
@campmlc this will overlap with some "DMRC followed by any series of letters or numbers" barcodes that are already reserved.

**Comment by dustymc** [comment]
>"DMRC followed by any

Good catch - also conflicts with barcode~'^DGR[A-Z0-9_-]{0,8}$' (but not the description) and who knows what else - that is a mess (at least three integer series run all over each other), should probably be cleaned up (but that might make it worse?!) and made nonoverlapping (possible?!), and now https://github.com/ArctosDB/arctos/issues/6789 is making me nervous for some reason.....

Really feel like we need a big-picture review of this, but no idea how we could get there.

Related:

```
barcode~'^K.[0-9]{0,4}$'
```

allows - well, some crazy stuff.

"K followed by 4 numbers" is 

```
barcode~'^K[0-9]{4}$'
```

but I think that's not what was ordered either??

"K followed by 4-long base36" (is that is???) would be

```
barcode~'^K[0-9A-Z]{4}$'
```

**Comment by Jegelewicz** [comment]
> K followed by four numbers

was my poor interpretation of an existing claim that had no description? That was back when I was trying to help ensure that all "existing" barcodes were claimed.

It probably should say "K followed by **up to** four numbers? I'd have to go find the issue where we were claiming stuff to see...

**Comment by Jegelewicz** [comment]
See https://github.com/ArctosDB/arctos/issues/1747#issuecomment-1050300443

**Comment by dustymc** [comment]
OH! My brain somehow merged that with KSB "G numbers" - ANYWAY - would be very useful to know what the sheet is supposed to accomplish (because whatever people might imagine, I don't think it does that). Might even be that the claim isn't useful at all in a world where barcodes are not globally unique. (It still probably-kinda prevents scanning your Doritos into a nunc tube, but the descriptions and SQL clearly do not align very well.)

**Comment by campmlc** [comment]
Happy to switch the request to "C" series for cryovial, cryogenic etc. This is exactly the same series protocol as the A series I was previiously using . And please, the claim series is necessary at least on at institutional level, and it helps me to see what other collections are using, especially those we are collaborating with.

**Comment by dustymc** [comment]
>"C" series

Some overlap with ``C1-C96500`` in there.

>claim series is necessary

OK, but WHY -  actually I'll just open another issue.....

**Comment by campmlc** [comment]
Why is because I've been using this same format and number tracking for nearly a decade, and I am willing to make some changes to the values to accommodate KSB but I'm not willing to entirely change everything we do at MSB. to accommodate this. I need a base36 value with 5 alphanumeric digits starting with a consistent single letter so that these can fit on our standard cryovial labels. I need consistent values that I can track to make sure we know what series has already been ordered and what to order next. Since we are using base36, this is not trivial. So far MSB has ordered 550,000 of these labels since 2014. Someone needs to be able to track this so that duplicates don't occur at least within our institution. I have counted on Arctos to be able to prevent this up to know, but I also need an Arctos tool to let me check our series before I place a $5000 order.

**Comment by campmlc** [comment]
I am retracting this request and will continue to manage and use barcodes in the MSB reserved A series. I still have over 1 million values left in that series. I will omit the 25000 values that KSB mistakenly ordered, and go onward from there.  Making any changes at this point is a waste of everyone's time.
