### ISSUE TITLE
barcode claims

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6834]
The barcode claim sheet is "necessary" but I think it's probably not doing what some - maybe all! - users expect. There are lots of claims that don't match the description, there are what look to me like single claims scattered across multiples, etc., etc., etc. WHATEVER the need, I don't think it's being met.

What SHOULD that form *do*, and how might that change with a unique constraint on (institution, barcode) rather than just (barcode)? https://github.com/ArctosDB/arctos/issues/6789

---------

              Happy to switch the request to "C" series for cryovial, cryogenic etc. This is exactly the same series protocol as the A series I was previiously using . And please, the claim series is necessary at least on at institutional level, and it helps me to see what other collections are using, especially those we are collaborating with.

_Originally posted by @campmlc in https://github.com/ArctosDB/arctos/issues/6833#issuecomment-1764929182_

**Comment by campmlc** [comment]
I need a base36 value with 5 alphanumeric digits starting with a consistent single letter so that these can fit on our standard cryovial labels. I need consistent values that I can track to make sure we know what series has already been ordered and what to order next. Since we are using base36, this is not trivial. So far MSB has ordered 550,000 of these labels since 2014. Someone needs to be able to track this so that duplicates don't occur at least within our institution. I have counted on Arctos to be able to prevent this up to know, but I also need an Arctos tool to let me check our series before I place a $5000 order.

**Comment by campmlc** [comment]
So what we need to prevent overlaps is a way to check an entire series of 25,000 or 50,000 barcodes against other series in Arctos, not just beginning and ending values. And even with institutional constrainst, I should be able to do this for my institution.

**Comment by campmlc** [comment]
I checked my D and C series requests using the existing tool by putting in start and end values. The tool did not flag any problems.  So if there is a problem with either of my requests, the tool is failing, and there is a problem.

**Comment by dustymc** [comment]
>Someone needs to be able to track this so that duplicates don't occur at least within our institution.

If that means "handy reference for a person" then the SQL might be unnecessary? It's currently evaluated when a barcode is created in whatever way, but I suspect that doesn't quite do what's expected - see 'don't match' in initial comment.

> counted on Arctos to be able to prevent this

Controlling the world's printers is, unfortunately, still beyond my reach. ((8) at https://handbook.arctosdb.org/documentation/container.html#guidelines-for-barcode-containing-labels is intended to make that clear.)

>The tool did not flag any problems.

I'm not sure what this means. "Is distinct" is not considered - the test barcode turns one or more lines green (by evaluating the SQL), that's it. Is that a request for something??

**Comment by campmlc** [comment]
I expect that I can use the form to test whether a barcode series has been reserved by my institution and doe not overlap with series of other institutions, so it is safe for me to to order and use without risk of duplicates.

**Comment by dustymc** [comment]
>I entered D0000 and DZZZZ and C0000 and CZZZZ - these did not match any reserved series

>I expect that I can use the form to test whether a barcode series has been reserved by my institution and does not overlap with series of other institutions,

The former (a few selected representatives of a set??) clearly doesn't satisfy the latter (check the series). ``C1234`` for example is within ``barcode~'^C[0-9]*$' and substr(barcode,2)::INT between 1 and 96500`` and ``barcode~'^C[0-9A-Z]{4}$'``. 

> by my institution 

Institution is currently a nonfunctional string.

I suspect "test whether a barcode series has been reserved by my institution and does not overlap with series of other institutions" requires moving 'claims' to DBA-domain, but would be very good to fully flesh out all expectations before proposing any action.

**Comment by campmlc** [comment]
So that means that "check barcode" really is a non-functional tool, if we can't use it to see if a barcode belongs to a series reserved by another institution. I thought, obviously mistakenly, that that was the point of the tool, especially given the text at top of the page: 
Claim barcodes and barcode series.

Review container documentation, especially container purchase guidelines , before doing anything here.
[Contact Us](https://github.com/ArctosDB/arctos/issues/new?assignees=&labels=contact&template=contact-arctos.md&title=%5BCONTACT%5D) if you need help with any part of the barcoding process or anything in Arctos, including this form.
If you claim XYZ1 through XYZ5, don't be surprised if someone else claims XYZ6. Claim what you might need, not only what you currently have.
Don't be "that person"; contact the XYZ-folks before claiming what might be part of an intended series.
Don't be redundant. If you already own XYZ1 through XYZ5 and you buy XYZ6 through XYZ10, edit the original entry rather than adding a new entry. This thing is already hard enough to read!

**Comment by campmlc** [comment]
![Screenshot 2023-10-16 13 07 07](https://github.com/ArctosDB/arctos/assets/14808196/43dee5e9-3af1-40d6-882f-66fc6233ec81)

**Comment by dustymc** [comment]
>So that means that "check barcode" really is a non-functional tool, 

No!

>an't use it to see if a barcode belongs to a series reserved by another institution.

You can absolutely do that.

**Comment by campmlc** [comment]
So obviously this form does not allow us to test barcode series, only single values. What we need is a way to test if a series overlaps another series already claimed. The barcodes I tested were the first and last values of a series that would encompass other series, but there is no way for me to know currently unless I can read the SQL.

**Comment by dustymc** [comment]
@ccicero @mkoo can I merge your single-container claims into one IN list? (And see https://handbook.arctosdb.org/documentation/container.html#guidelines-for-barcode-containing-labels - those spaces and dashes and etc. are limiting.)

```

arctosprod@arctos>>  select barcodeseriessql from cf_barcodeseries where  institution='MVZ' order by  barcodeseriessql;
                                         barcodeseriessql                                         
--------------------------------------------------------------------------------------------------
 barcode='1'
 barcode='1143 VLSB'
 barcode='1168 VLSB'
 barcode='3101 VLSB'
 barcode='3103 VLSB'
 barcode='3140 VLSB'
 barcode='3144 VLSB'
 barcode='3170 VLSB'
 barcode='3174 VLSB'
 barcode='3182 VLSB'
 barcode='3184 VLSB'
 barcode='3189 VLSB'
 barcode='3193 VLSB'
 barcode~'^AR[0-9]{1}-[A-E]{1}-[1-5]{1}$'
 barcode~'^AR9-[A-E]{1}-b[1-8]{1}$'
 barcode~'^AR9-[A-E]{1}-d[1-4]{1}$'
 barcode~'^BIRD [0-9]{1,3}$' and substr(barcode,6)::INT between 1 and 500
 barcode~'^BOWIE [0-9]{1,3}$' and substr(barcode,7)::INT between 1 and 500
 barcode~'^FRZ [0-9]$'
 barcode~'^HERP [0-9]{1,3}$' and substr(barcode,6)::INT between 1 and 500
 barcode  in ('VLSB 1143','CAS','MTEC','SEMC','USDA-ARS','USNM','OSAC','PMJ-Phyletisches-Museum')
 barcode~'^LN2CF-[A-Z]{1}-[0-9]{1,2}-[0-9]{1,2}$'
 barcode='MVZ'
 barcode~'^MVZ[0-9]*$' and substr(barcode,4)::INT between 1000 and 500000
 barcode~'^MVZ3135-JAR[0-9]*$' and substr(barcode,12)::INT between 1 and 9999
 barcode~'^MVZ3137-JAR[0-9]*$' and substr(barcode,12)::INT between 1 and 9999
 barcode~'^MVZ3139-JAR[0-9]*$' and substr(barcode,12)::INT between 1 and 9999
 barcode~'^MVZ3165-JAR[0-9]*$' and substr(barcode,12)::INT between 1 and 9999
 barcode~'^MVZ3167-JAR[0-9]*$' and substr(barcode,12)::INT between 1 and 9999
 barcode~'^MVZ3169-JAR[0-9]*$' and substr(barcode,12)::INT between 1 and 9999
 barcode~'^MVZBIRD-CASE-[0-9]{1,4}$'
 barcode='MVZ HerpRoom 3135'
 barcode='MVZ HerpRoom 3137'
 barcode='MVZ HerpRoom 3139'
 barcode='MVZ HerpRoom 3165'
 barcode='MVZ HerpRoom 3167'
 barcode='MVZ HerpRoom 3169'
```

**Comment by Jegelewicz** [comment]
Instead of "check barcode" we need "check barcode series" - something that would take a csv list of barcodes and check them all.

**Comment by dustymc** [comment]
>take a csv list of barcodes and check them all

I can do that, it would almost certainly have to be asynchronous, but I think we need the above completely resolved before investing in such expensive tools.

I'm not sure what's wanted for claims, there are all sorts of conflicting requests leading up to this point. I need something I can write as code, it doesn't have to have anything to do with how anything currently works.

There was some mention of adding something to this, including a way of tracking 'last printed' and such (maybe using remarks is enough??), let's resolve that if we're doing anything significant.

Access (eg to update those remarks-or-addition) is super-wonky and meant to support a fully-shared system. The system is no longer shared (InstitutionA doesn't need to care that InstitutionB already has a '1' barcode), and https://github.com/ArctosDB/arctos/issues/7127 is at the moment suggesting this will be very limited access - maybe that form can just be completely open (possibly depending on the functionality needed).

The claim system could possibly even be dropped - I don't think I have to care if some institution wants to print random barcodes, although I can't imagine why they'd not want me to.

This probably can't be fully resolved until #7127 is.

**Comment by mkoo** [comment]
> @ccicero @mkoo can I merge your single-container claims into one IN list? (And see https://handbook.arctosdb.org/documentation/container.html#guidelines-for-barcode-containing-labels - those spaces and dashes and etc. are limiting.)
> 
> ```
> 
> arctosprod@arctos>>  select barcodeseriessql from cf_barcodeseries where  institution='MVZ' order by  barcodeseriessql;
>                                          barcodeseriessql                                         
> --------------------------------------------------------------------------------------------------
>  barcode='1'
>  barcode='1143 VLSB'
>  barcode='1168 VLSB'
>  barcode='3101 VLSB'
>  barcode='3103 VLSB'
>  barcode='3140 VLSB'
>  barcode='3144 VLSB'
>  barcode='3170 VLSB'
>  barcode='3174 VLSB'
>  barcode='3182 VLSB'
>  barcode='3184 VLSB'
>  barcode='3189 VLSB'
>  barcode='3193 VLSB'
>  barcode~'^AR[0-9]{1}-[A-E]{1}-[1-5]{1}$'
>  barcode~'^AR9-[A-E]{1}-b[1-8]{1}$'
>  barcode~'^AR9-[A-E]{1}-d[1-4]{1}$'
>  barcode~'^BIRD [0-9]{1,3}$' and substr(barcode,6)::INT between 1 and 500
>  barcode~'^BOWIE [0-9]{1,3}$' and substr(barcode,7)::INT between 1 and 500
>  barcode~'^FRZ [0-9]$'
>  barcode~'^HERP [0-9]{1,3}$' and substr(barcode,6)::INT between 1 and 500
>  barcode  in ('VLSB 1143','CAS','MTEC','SEMC','USDA-ARS','USNM','OSAC','PMJ-Phyletisches-Museum')
>  barcode~'^LN2CF-[A-Z]{1}-[0-9]{1,2}-[0-9]{1,2}$'
>  barcode='MVZ'
>  barcode~'^MVZ[0-9]*$' and substr(barcode,4)::INT between 1000 and 500000
>  barcode~'^MVZ3135-JAR[0-9]*$' and substr(barcode,12)::INT between 1 and 9999
>  barcode~'^MVZ3137-JAR[0-9]*$' and substr(barcode,12)::INT between 1 and 9999
>  barcode~'^MVZ3139-JAR[0-9]*$' and substr(barcode,12)::INT between 1 and 9999
>  barcode~'^MVZ3165-JAR[0-9]*$' and substr(barcode,12)::INT between 1 and 9999
>  barcode~'^MVZ3167-JAR[0-9]*$' and substr(barcode,12)::INT between 1 and 9999
>  barcode~'^MVZ3169-JAR[0-9]*$' and substr(barcode,12)::INT between 1 and 9999
>  barcode~'^MVZBIRD-CASE-[0-9]{1,4}$'
>  barcode='MVZ HerpRoom 3135'
>  barcode='MVZ HerpRoom 3137'
>  barcode='MVZ HerpRoom 3139'
>  barcode='MVZ HerpRoom 3165'
>  barcode='MVZ HerpRoom 3167'
>  barcode='MVZ HerpRoom 3169'
> ```

A lot of those (all?) single barcodes were done with a certain air of 'trial and error' at the time of creation. So yes smush together. Do you want me to set up something for the rooms? For the 'MVZ HerpRoom *' series there will be no more but the others (eg, **** VLSB) have been created one at time (my bad!). The rooms numbers are potentially 1100 - 3101-5199 which would take care of the entire building (if we should be so lucky to expand). Thx

**Comment by dustymc** [comment]
>trial and error

Yea welcome to earlyadopterville....

Thanks @mkoo I made some compressions and have some more questions.

```
 barcode~'^AR[0-9]{1}-[A-E]{1}-[1-5]{1}$'
 barcode~'^AR9-[A-E]{1}-b[1-8]{1}$'
 barcode~'^AR9-[A-E]{1}-d[1-4]{1}$'
```

Can those all be covered by

```
 barcode~'^AR[0-9]{1}-[A-E]{1}-[b,d]{0,1}[1-8]{1}$'
```

or is there some reason to keep them separate?

```
 barcode~'^LN2CF-[A-C]{1}-[0-9]{1,2}$'
 barcode~'^LN2CF-[A-Z]{1}-[0-9]{1,2}-[0-9]{1,2}$'
```

Those could be compressed to  

```
barcode ~'^LN2CF-[A-Z]{1}-[0-9]{1,2}[-]?[0-9]{0,2}$'
```



```
 barcode~'^MVZ3135-JAR[0-9]*$' and substr(barcode,12)::INT between 1 and 9999
 barcode~'^MVZ3137-JAR[0-9]*$' and substr(barcode,12)::INT between 1 and 9999
 barcode~'^MVZ3139-JAR[0-9]*$' and substr(barcode,12)::INT between 1 and 9999
 barcode~'^MVZ3165-JAR[0-9]*$' and substr(barcode,12)::INT between 1 and 9999
 barcode~'^MVZ3167-JAR[0-9]*$' and substr(barcode,12)::INT between 1 and 9999
 barcode~'^MVZ3169-JAR[0-9]*$' and substr(barcode,12)::INT between 1 and 9999
```


could be

```
barcode~'^MVZ[0-9]{4}-JAR[0-9]*$' and (substr(barcode,4,4)::INT between 3135 and 3169) and (substr(barcode,12)::INT between 1 and 9999)
```

OK to make any or all of those changes?

**Comment by mkoo** [comment]
Hey I am a permanent resident of earlyadopterville!

Yes, that's ok to do as far as I see. I think it's clear we werent sure about some of the series that we were 'making' up or how we were going to use them! Also, I assume the Labels will be untouched; we're going to rely on those more for the human-readable locations. Thx!

**Comment by mkoo** [comment]
a question:
``` barcode~'^AR[0-9]{1}-[A-E]{1}-[b,d]{0,1}[1-8]{1}$'```
This one does not require the presence of the "b" or "d" in the series, right?
Most of our shelf locations should not have a little b or d (eg AR1-A-4 but we have special spots for AR9-E-b1....)

That's the only accommodation for that proposed series

**Comment by dustymc** [comment]
> Labels will be untouched;

Yes, this is just a more-organized way to let the containers exist, it doesn't touch the containers themselves in any way.

> not require the presence of the "b" or "d"

Correct, one of those is optional.

Done.

**Comment by dustymc** [comment]
I'm going to fold up the 'done' cleanup requests so we can focus on what might be useful functionality. Happy to merge or simplify things for anyone, just post here or open a new Issue.

**Comment by dustymc** [comment]
tabling for lack of interest
