### ISSUE TITLE
Need Help with Arctos Error

### ISSUE THREAD

**Issue by libbybeckman** [ArctosDB/arctos#6835]
# Error Text

ERROR_ID | A85AA323-3622-414D-83B637058D381409
ERROR_TYPE | SQL
ERROR_MESSAGE | ERROR: syntax error at or near "."   Position: 133
ERROR_DETAIL |  
ERROR_SQL | INSERT INTO specimen_part ( COLLECTION_OBJECT_ID, PART_NAME, SAMPLED_FROM_OBJ_ID, DERIVED_FROM_CAT_ITEM,. created_agent_id, created_date, disposition, part_count, condition ) VALUES ( 31959323, 'skin, study', 13206391, 10206391, 21249215, current_date, 'in collection', 1, 'unchecked' )

# Where it happened
I get an error every time I try to add items to a loan. See the steps below that lead to the error.

https://arctos.database.museum/info/loan_item_pick.cfm

# Steps to get there
I created an MVZ loan, 2023.9421.Bird. This loan requires 9 items to be added.
I selected "Add items to loan"
I searched the specimen numbers and found the nine items to add and selected from "Tools" > Add items to transaction.
For each individual, I selected one part to subsample, indicated I will subsample it, and for the subsample selected "Transfer of custody" for the disposition
When I then press, "Add all checked items to transaction", I get the error above.

# Problem
I cannot add any items to this loan. Initially, I tried to add nine items to the loan, but I have also tried one item at a time for multiple specimens. I also worked with a colleague who should have the same permissions (or more) than me, and he was unable to add items to the transaction and got the same error message.

I have added items to loans before in the MVZ:Bird collection, so I'm not sure what has changed that is now preventing me from adding items to this transaction.

Any help would be much appreciated.

# Solution
**Community response with directions for how to correct the problem**

**Comment by dustymc** [comment]
try now

**Comment by libbybeckman** [comment]
Works! Thanks so much!
- Libby
