### ISSUE TITLE
multi identification error handling

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#6836]
I don't know if this is a bug, or some mistake on my part. I used these parameters to add an id for another similar specimen. Same agent, same pub, etc. But, trying to change 8 specimens to a new ID I get these errors. I tried both options for "ignore past ID" and "set past ID to 0".
Also, sort of frustrating that when you have a mistake, and browse back, you can't edit the attributes. You have to flip the attributes for confidence and nature of ID and repopulate them. 

Chris

<img width="1070" alt="Screenshot 2023-10-17 at 2 55 34 PM" src="https://github.com/ArctosDB/arctos/assets/5749672/96291a55-3569-43ee-84ee-2f6b6f71bc36">
<img width="807" alt="Screenshot 2023-10-17 at 2 51 20 PM" src="https://github.com/ArctosDB/arctos/assets/5749672/89c556e2-519f-48fa-8479-60e1140bae58">

**Comment by dustymc** [comment]
>can't edit the attributes

That's related and I'm able to replicate - save, get error, back, *then hold shift and reload*, then fill in stuff and it should save.

I'm not sure if I can do anything about that, but I'll go next task for trying.

**Comment by cjconroy** [comment]
I don't understand. Did I make a mistake? I would like to make some new identifications.

**Comment by dustymc** [comment]
>mistake

Apparently, and the form isn't good at recovering from that. You can

1. Just start over, don't try to reload, close the window, or
2. Use your back button to get back to the initial form (which will be wedged in your browser), then hold shift and click reload (which should un-wedge stuff).

**Comment by cjconroy** [comment]
It worked, but I still don't know what I did wrong.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/6841
