### ISSUE TITLE
attributes not valid and I don't know why

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6837]
Attempting to load ZSFQ records and the following attributes are marked as invalid in the process:

processing history
verbatim agent

both are available to Herp collections:

![image](https://github.com/ArctosDB/arctos/assets/5725767/30c7ebda-9b90-4436-8c40-7981e244b040)
![image](https://github.com/ArctosDB/arctos/assets/5725767/f0c255a0-272e-4bf5-a6de-63d66cc4da13)

What am I doing wrong?

**Comment by Jegelewicz** [comment]
[1_1500.ZSFQ_v2.csv](https://github.com/ArctosDB/arctos/files/13057596/1_1500.ZSFQ_v2.csv)

**Comment by dustymc** [comment]
digitador nombre   completo: Tammy Paulina Pastor Villasis

is not in https://arctos.database.museum/info/ctDocumentation.cfm?table=ctprocessing_history

snout-vent length needs units

not seeing anything about verbatim agents

**Comment by Jegelewicz** [comment]
DOH! Thanks!
