### ISSUE TITLE
Feature Request - last scan date on review loan items

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#6838]
The last scan date is no longer present on the review loan items page. Can that be returned? We had that whole discussion (lost track of which github item) about the problem and how to solve it...

As stated then, I rely heavily on that to ensure a loan has been returned and no specimens have been skipped in object tracking etc. 

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._
high

**Comment by Jegelewicz** [comment]
https://github.com/ArctosDB/arctos/issues/5644

or

https://github.com/ArctosDB/arctos/issues/5815

or

https://github.com/ArctosDB/arctos/issues/4213

**Comment by dustymc** [comment]
merge --> https://github.com/ArctosDB/arctos/issues/6028
