### ISSUE TITLE
Feature Request - can we get default 'identification_order' value of 1 for the Manage Identifications tool?  

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#6841]
With the addition of multiple accepted identifications came all sorts of problems but as I've said before, those who don't want to use this new ability shouldn't have to do anything different. It should be an opt-in, not an opt-out, situation.

The manage identification tool (which I use all the time) has 2 fields related to this new ability:

Existing Identification order: - this has a default value of zero, which is good, so the prior ability is preserved. Yay!

and

identification_order

but this last field has no default value so we have to remember to set it to 1 to preserve the prior functionality. boo!

If one forgets this is a pain that leads to confusion and problems, and teaching new people that they need to set this to 1 to get it behave properly is a pain. "Yes, they added a new feature that we don't use so we have to remember to set this to 1 to avoid using it."

Can that be set to 1 as a default on that form? This way if someone wants to use this new feature and choose something other than 1, they will have to click & choose (or suffer the consequences), instead of having the rest of us suffer.

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._
medium

**Comment by dustymc** [comment]
Nobody's asking to block this and it accomplishes much of https://github.com/ArctosDB/arctos/issues/6836 so - sure?
