### ISSUE TITLE
How do I fix an old numbering error in Arctos

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#6846]
Situation: We have three numbers that were decades ago cataloged thus:

15018 - mammoth tooth
15019 - mammoth tooth
15020 - amphibian skeleton

The second mammoth tooth entry was a duplicate, the specimens were correctly labeled and cited multiple times as:

15018 - mammoth tooth
15019 - amphibian skeleton

15020 - doesn't appear to exist

However, the original cataloging error was never noticed, it was propagated to the database and uploaded that way to Arctos.

I've just noticed the error, I'm annotating the catalog with the correct numeration, but need advise on how best to do this in Arctos.

I think I need to migrate the data in the 15020 record to 15019 with remarks explaining what happened and make 15020 some kind of placeholder record with a relationship back to 15019. Any suggestions would be helpful.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Here are the records:
https://arctos.database.museum/guid/NMMNH:Paleo:15018
https://arctos.database.museum/guid/NMMNH:Paleo:15019
https://arctos.database.museum/guid/NMMNH:Paleo:15020

**Comment by dustymc** [comment]
https://handbook.arctosdb.org/documentation/redirect.html

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks! Ok, so my steps will be:

Update 15019 so that it matches the data in 15020.
Encumber and delete 15020.
Create a redirect from 15020 to 15019.

Am I understanding that correctly?

**Comment by dustymc** [comment]
That'd do it. Or don't delete, just mask record encumber, if you (with permissions) need the record for some reason, whichever future-you will think is less confusing.....

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
done, thank you!
