### ISSUE TITLE
Feature Request - add field for accessions: 'actual count'

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#6853]
Currently you can enter 'estimated count' for the # records in an accession. It would also be very useful to have a separate field for 'actual count' to show how many specimens in actuality have been received for that accession. This would be especially useful for accessions of salvaged material where the specimens are received whole and prepared in the museum incrementally. By having a field for actual count vs estimated count, it will make it easier to update the accession as prepared specimens are received to know whether all specimens have been prepared or not. One could also use this to prioritize accessions to finish for specimen preparation (e.g., if all but just a few are done).

At MVZ we've been adding the specimens we receive to the accession remarks after they are frozen for pest management. For larger accessions this becomes clunky because there's no running total (unless you add that in remarks) so you have to count each specimen that was recorded in remarks. The running total is better as a numeric field so that you could download a CSV of open accessions and subtract actual from estimated specimens to get the # remaining that are still unaccounted for.

![image](https://github.com/ArctosDB/arctos/assets/967275/45f0038f-1af9-497f-bd82-562adfe5b9c5)

**Comment by dustymc** [comment]
>actual count
<img width="1307" alt="Screenshot 2023-10-19 at 12 53 23" src="https://github.com/ArctosDB/arctos/assets/5720791/28cc2872-fd16-4c99-b41d-3b7aacf6c321">

??????????????

**Comment by ccicero** [comment]
Sorry, should clarify. This would be for tracking accessions BEFORE they're cataloged.

**Comment by ccicero** [comment]
Issue discussed at code table meeting 19 Oct 2023. Feature to be part of new [transaction attributes](https://github.com/ArctosDB/arctos/issues/6854).

**Comment by ccicero** [comment]
Per Arctos workshop Feb 2026, suggested term = 'verified count' but requires discussion.

**Comment by dustymc** [comment]
blocked by https://github.com/ArctosDB/dev/issues/40
