### ISSUE TITLE
Code Table Request - new life stage: gamete

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6856]
### Goal
_Describe what you're trying to accomplish. This is the only necessary step to start this process. The Committee is available to assist with all other steps. Please clearly indicate any uncertainty or desired guidance if you proceed beyond this step._

Record life stage (currently age class in Arctos) using GBIF terms for an incoming collection to keep their published data consistent.

### Context
_Describe why this new value is necessary and existing values are not._

No existing term properly describes this life stage which is a term in the GBIF vocabulary.

### Table
_Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table or value. This may involve multiple tables and will control datatype for Attributes. OtherID requests require BaseURL (and example) or explanation. Please ask for assistance if unsure._

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctage_class

### Proposed Value
_Proposed new value. This should be clear and compatible with similar values in the relevant table and across Arctos._

gamete

### Proposed Definition
_Clear, complete, non-collection-type-specific **functional** definition of the value. Avoid discipline-specific terminology if possible, include parenthetically if unavoidable._

A gamete is a cell that fuses with another gamete during fertilization in organisms that reproduce sexually. In species that produce two morphologically distinct types of gametes, and in which each individual produces only one type, a female is any individual that produces the larger type of gamete — called an ovum (or egg) — and a male produces the smaller tadpole-like type — called a sperm. This is an example of anisogamy or heterogamy, the condition wherein females and males produce gametes of different sizes. In contrast, isogamy is the state of gametes from both sexes being the same size and shape, and given arbitrary designators for mating type. Gametes carry half the genetic information of an individual, one chromosome of each type. |  http://rs.gbif.org/vocabulary/gbif/life_stage/gamete

### Collection type
_Some code tables contain collection-type-specific values. ``collection_cde`` may be found from https://arctos.database.museum/home.cfm_

Amph, Bird, Ento, Mamm, Herp, Host, Fish, Inv, Herb, Para, Rept, Teach, Vert, Zoo

#### Attribute data type
_If the request is for an attribute, what values will be allowed?
free-text, categorical, or number+units depending upon the attribute (TBA)_

N/A

#### Attribute controlled values
_If the values are categorical (to be controlled by a code table), add a link to the appropriate code table. If a new table or set of values is needed, please elaborate._

N/A

#### Attribute units
_if numerical values should be accompanied by units, provide a link to the appropriate units table._

N/A

#### Part preservation attribute affect on "tissueness"
_if a new part preservation is requested, please add the affect it would have on "tissueness": No Influence, Allows, or Denies_

N/A

### Priority
_Please describe the urgency and/or choose a priority-label to the right. You should expect a response within two working days, and may utilize [Arctos Contacts](https://arctosdb.org/contacts/) if you feel response is lacking._

Part of OGL data migration

### Example Data
_Requests with clarifying sample data are generally much easier to understand and prioritize. Please attach or link to any representative data, in any form or format, which might help clarify the request._

### Available for Public View
_Most data are by default publicly available. Describe any necessary access restrictions._

yes

### Helpful Actions

- [x] Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

- [x] Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

@ArctosDB/arctos-code-table-administrators @happiah-madson @falco-rk 

## Approval
_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection
_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation
_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

- [ ] Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

- [ ] Add or revise the code table term/definition as described above. Ensure the URL of this Issue is included in the definition. URLs should be included *_as text_*, separated by spaced pipes. Do not include HTML in definitions.

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by mkoo** [comment]
Should we reference our definitions with some external links (eg GBIF 'adult'?)

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
How much is this value used in their data?

**Comment by dustymc** [comment]
I might want to uncheck - coming from https://github.com/ArctosDB/arctos/issues/6855, how does this intersect with https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name? (And so what: Do we want to say **this** when/if it can unavoidably be inferred from **that**?)

**Comment by dustymc** [comment]
>Some terms are in both places, some are not.

I'm asking about these data - are they not-part and needing to be here-or-close, or are they being derived from parts? These discussions are already difficult to track, considering the infinite theoretical does not seem necessary if we can just address the immediate reality.

>follow [GBIF](https://rs.gbif.org/vocabulary/gbif/life_stage.xml)

Unless they're also managing parts and normalizing that doesn't seem completely prescriptive to out little ecosystem.

**Comment by Jegelewicz** [comment]
In OGL's current data they are "not-part" and instead are included in "lifeStage"

The related parts in the OGL data are whole organism

**Comment by happiah-madson** [comment]
The part name/tissue type for these materials is "spawn bundles." I think we'd be okay with this information being in part name instead of life stage (even though gamete is def a life stage) but neither gamete nor spawn bundle exists as a part name.

**Comment by Jegelewicz** [comment]
> (even though gamete is def a life stage) but neither gamete nor spawn bundle exists as a part name.

I agree that gamete is a life stage and I don't think making it a part makes sense. But maybe you would want "spawn bundle"? However, for only 3 records that seems unnecessary. This is where I can see the need for a part name = "other" with the description "A detailed description should be provided in part remark".

**Comment by happiah-madson** [comment]
Coolio, I'm fine with that. This is data that you're wrangling, tho, so...are you cool with that?

**Comment by Jegelewicz** [comment]
OK - I am returning here because there are 11 catalog record attributes in the attribute bulkload tool that would use this and I'd rather not have them there a year from now.

I am advocating for this to be added as a life stage because:

1. that is how it is used in the broader community (GBIF vocabulary) so I expect that people will search for it in life stage NOT part.
2. ovum and sperm are already parts (and those records should carry the life stage "gamete"?), adding gamete means that nobody will probably ever find all of the gametes (they already won't unless the life stage gets added to all the appropriate records)?

This doesn't seem controversial to me. Can we get it done? @ArctosDB/arctos-code-table-administrators

**Comment by campmlc** [comment]
So to clarify, you are proposing this as a record attribute, rather than a part attribute? The reason for parts = eggs/sperm or gamete would be if there are other parts associated witht the same record that are not gametes. We could have a frog collected in the process of producing unfertilized eggs, and the eggs could be a part along with the frog whole organism. Or an animal in a captive breeding program with frozen sperm and blood. How many records do we have that only have "gametes"? What would be the part name? Whole organism doesn't work. ??

**Comment by Jegelewicz** [comment]
> How many records do we have that only have "gametes"? What would be the part name? Whole organism doesn't work. ??

OGL has them and is using tissue, but I could also see using cell (which isn't an option but maybe should be).

**Comment by campmlc** [comment]
Cell still doesn't distinguish gametes, which are very distinct types of cells with half the chromosome count. Could we add "gametes" as a part name and record "ovum" and "sperm" as a part attribute? That could help disambiguate "egg" which is currently used as the fertilized zygote  and it's shell and shell contents, vs "ovum" = female gamete. "Gamete" is also a better term for protoza, fungi, non-vertebrates etc. The parts code table currently has "sperm" but not "ovum", and in fact is conspicuouly missing many non-vertebrate reproductive parts.

"Gamete, [sex](https://www.britannica.com/science/sex), or reproductive, [cell](https://www.britannica.com/science/cell-biology) containing only one set of dissimilar [chromosomes](https://www.britannica.com/science/chromosome), or half the genetic material necessary to form a complete organism (i.e., haploid). Gametes are formed through [meiosis](https://www.britannica.com/science/meiosis-cytology) (reduction division), in which a germ cell undergoes two fissions, resulting in the production of four gametes. During [fertilization](https://www.britannica.com/science/fertilization-reproduction), male and female gametes fuse, producing a diploid (i.e., containing paired chromosomes) [zygote](https://www.britannica.com/science/zygote).
Gametes may be identical in form ([isogamy](https://www.britannica.com/science/isogamy)), as in certain species of [algae](https://www.britannica.com/science/algae), [fungi](https://www.britannica.com/science/fungus), and [protozoans](https://www.britannica.com/science/protozoan), or there may be more than one morphological type ([heterogamy](https://www.britannica.com/science/heterogamy), or anisogamy), as with many [green algae](https://www.britannica.com/science/green-algae) of the [genus](https://www.britannica.com/dictionary/genus) [Chlamydomonas](https://www.britannica.com/science/Chlamydomonas). Gametes of [animals](https://www.britannica.com/animal/animal), some algae and fungi, and all higher [plants](https://www.britannica.com/plant/plant) exhibit an advanced form of [heterogamy](https://www.britannica.com/science/heterogamy) called [oogamy](https://www.britannica.com/science/oogamy). In oogamy one of the gametes is small and motile (the [sperm](https://www.britannica.com/science/sperm)), and the other is large and nonmotile (the [egg](https://www.britannica.com/science/egg-biology))."

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
box checked

**Comment by dustymc** [comment]
added (with abbreviated definition)
