### ISSUE TITLE
data entry -> clone records by barcode (add container?)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ArctosDB/arctos#686]
```
...lotsa specimens....'clone records by barcode'....2-3hrs of scanning

Then when it is time to make labels for those specimens we have to find them in 
Arctos.

.....when we do the initial clone records by barcode, we also can scan in the 
container these specimens are in so that each single barcode scan kills two 
birds with one stone (creates a specimen record with a barcode, and puts that 
specimen in a container).....
```

Original issue reported on code.google.com by `dust...@gmail.com` on 2 Jun 2014 at 4:11

**Comment by dustymc** [comment]
How should this work? Suggestion as a starting point:

DataEntry/CloneByBarcode.

Scan some codes, push the new button....

<img width="261" alt="screen shot 2015-09-01 at 3 45 47 pm" src="https://cloud.githubusercontent.com/assets/5720791/9619052/bc2d8fa2-50c0-11e5-9433-d60cfcf84715.png">

... to dump what you've just scanned into a batch scan (CSV mode)....

<img width="302" alt="screen shot 2015-09-01 at 3 48 20 pm" src="https://cloud.githubusercontent.com/assets/5720791/9619082/f4d1bce8-50c0-11e5-8798-10dc3f2ca3e2.png">

where you can change container type and move the soon-to-be-part container to a parent. Save, close the window, back to data entry, save, approve, load specimens, they'll magically find their way to the correct container.

Does any of that conflict with your workflow, sound unreasonable, whatever? 

(emailed DSS 20150901)
