### ISSUE TITLE
Need to add Issued By: Museum of Vertebrate Zoology Prep Lab Catalog (PLC)

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#6860]
Hi @dustymc The MVZ has a number of what we call PLC numbers as identifiers where the IssuedBy is still null (leftover task from the Identifiers clean-up round). So to finish up this task, we have the following request:

For all Identifiers which have "PLC" and IssuedBy is null, please add the new IssuedBy as "Museum of Vertebrate Zoology Prep Lab Catalog" (https://arctos.database.museum/agent/21347703)

EXAMPLES (fixed manually): https://arctos.database.museum/guid/MVZ:Bird:183633
Waiting for you! https://arctos.database.museum/guid/MVZ:Bird:193159

(ps. I dont want to sully this request with the whole identifier type debate at this time-- I know we have two types. There will come a time when the debate is meaningless....)
THANKS

**Comment by dustymc** [comment]
@mkoo I did

```
   guid_prefix like 'MVZ%' and
    display_value like 'PLC %' and
    issued_by_agent_id is null
```

and got this:

[temp_mvz_plc.csv](https://github.com/ArctosDB/arctos/files/13056561/temp_mvz_plc.csv)

Does that look right?

**Comment by mkoo** [comment]
only 210? wow thought we had more!
Wait, try without the space
```display_value like 'PLC%' ``` 
(yea dont get me started)
then let's go for it (at least before we have any collectors with the same initials)

**Comment by dustymc** [comment]
>ilike 'plc%'

SELECT 210


Looks like probably really 210.

[temp_mvz_plcnospacenocase.csv](https://github.com/ArctosDB/arctos/files/13057608/temp_mvz_plcnospacenocase.csv)

> go for it 

UPDATE 210
