### ISSUE TITLE
Arctos Down - 11:11 (now 11:20) no response from Arctos, all other webpages loading immediately

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#6861]
Please complete to the best of your ability.

## Unplanned Outage
 - Date and time (**please add time zone from which you are reporting**) outage discovered: Alaska
 - Describe the outage (Arctos down or only some part not working?): totally down

**Comment by dustymc** [comment]
It's back up but perhaps not stable, there are some user-induced problems that I'm having trouble staying ahead of.

**Comment by DerekSikes** [comment]
update - got a 500 internal service error after the Arctos pages failed to load after waiting about 10 minutes.

Then re-connected to Arctos, it loaded, but I was logged out. So I logged in & went back to repeat what I was doing - a bulk ID change.

I searched for these via their barcodes: UAM100375294,UAM100374808,UAM100374817,UAM100372204,UAM100373263,UAM100372197,UAM100372207,UAM100372209,UAM100372208,UAM100372193,UAM100372192,UAM100317575,UAM100316901,UAM100317674,UAM100317655,UAM100317967,UAM100317142,UAM100317146,UAM100043416,UAM100045462,UAM100317819,UAM100317787,UAM100317852,UAM100317807,UAM100317816,UAM100316930,UAM100317835,UAM100317857,

then I did manage identification:

identification_order = 1
ID formula =A
Taxon A = Formica subaenescens
ID date = 2023-10-20
remarks = max eye diameter <0.50 mm, ratio of scape to head length <1.056 (measured into data file)
existing ID order = set all to zero
ID condfidence = medium
nature of ID = fine features

and when I clicked 'add ids to all listed records' Arctos did nothing & started the same error-like waiting game.

Maybe this ID change is what's killing it?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I'm getting 503 Service Not Available.

**Comment by mkoo** [comment]
ok to close?

**Comment by DerekSikes** [comment]
yes

**Comment by wellerjes** [comment]
I think it was the catalog records that I was adding to a loan. Thanks!
