### ISSUE TITLE
[external CONTACT] change identifier type for 'Museum of Vertebrate Zoology Prep Lab Catalog'

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#6862]
When data were migrated to the new structure for identifiers, the generic type 'identifier' was used for the MVZ Prep Lab Catalog. My opinion is that the identifier type should be 'preparator number' because that's really what the number represents. That's what I've been doing for new records. Copying @mkoo @atrox10 @cjconroy @libbybeckman for discussion with other MVZ Staff Curators. We should be consistent in what identifier type we use. 

If agreed, change identifier type to 'preparator number' where 'identifier_issued_by' = 'Museum of Vertebrate Zoology Prep Lab Catalog' and 'identifier_type' = 'identifier'

**Comment by mkoo** [comment]
this is a repeat of https://github.com/ArctosDB/arctos/issues/6469

FYI We can discuss at the next staff meeting. Generally my view is that type= preparator makes sense for individuals to distinguish from collector number (although that is arguable too) and since "MVZ Prep Lab Catalog" is more of an institutional apparatus, type=identifier is actually more appropriate and wont break the 'preparator number' as currently defined.

but pls add to next staff meeting agenda so we can spare github from our internal reposts!

**Comment by mkoo** [comment]
Discussed and decided at MVZ staff meeting: use type=identifier for the Issuer 'Museum of Vertebrate Zoology Prep Lab Catalog'

@dustymc Right now we have 232 records with Issued_by 'Museum of Vertebrate Zoology Prep Lab Catalog'
and type='preparator number', please change those to identifier_type='identifier'

Or let me know (point me to right spot) if I can bulkload a _replace_ to type; the current tools seem to be _insert_ actions.
Thanks!

**Comment by dustymc** [comment]
Done.

Pre-update data:

[temp_mvz_plc2.csv.zip](https://github.com/ArctosDB/arctos/files/13384656/temp_mvz_plc2.csv.zip)


>replace

[Identifier Unloader](https://arctos.database.museum/loaders/bulkUnLoadIdentifier.cfm) plus [Identifier: Bulkload](https://arctos.database.museum/loaders/BulkloadOtherId.cfm) do that without any potential ambiguity. 

The "prefix" is inconsistent, and doesn't really have a purpose - our current structure is clearly what that's trying to get at! - if you're looking for a place to try out the replace loaders....

**Comment by dustymc** [comment]
I wasn't involved in this decision, but the general trend is that unless types DO STUFF (and here they clearly don't, the Agent does one thing) then they're just complications that sorta-inevitably end up as denormalizers (eg, things that prevent people from finding data).

**Comment by cjconroy** [comment]
How do you add the MVZ Prep Lab Catalog as the issuer ?  I don't seem to have that issue in data entry. 
<img width="1260" alt="Screenshot 2023-11-16 at 3 13 51 PM" src="https://github.com/ArctosDB/arctos/assets/5749672/9cca9d51-debe-4ea7-af0b-cd6d9c067943">

**Comment by dustymc** [comment]
You've turned it off - customize in the bottom bar and turn ... issued_by on.

**Comment by cjconroy** [comment]
I was using someone else's template. I've created a new MVZ mammal template. But, wow, now to customize hundreds of fields.

**Comment by mkoo** [comment]
@adhornsby Dusty provided one semantic argument but also in this case, we sometimes have preparators also assign another number in their own personal catalog of specimens so we reserve ```preparator number``` for individuals (back to Dusty's distinction of agent of action). TBF Carla disagrees with this decision and we talked about its role sometimes as a distinction without a difference but I also felt in the case the 'preparator' role was embedded in the name of the institutional catalog itself-- 'Prep Lab Catalog' so in this case it felt redundant. So mainly for the individual vs institution argument. The main importance was for us to be consistent one way or the other!

**Comment by Jegelewicz** [comment]
> I was using someone else's template. I've created a new MVZ mammal template. But, wow, now to customize hundreds of fields.

@cjconroy you could just modify the one you were using, add the one field and save it with a new name....

**Comment by cjconroy** [comment]
It was about time I created a template for myself, which means some time spent looking at what came across from the  cloned template. Lots of fields to delete, or unhide, pre-populate or unpopulate, etc., etc. But, now I have a reasonable template for myself.
