### ISSUE TITLE
Code Table Request - new part preparation method: Qiagen BioSprint96 DNA Blood Kit

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6864]
### Goal
_Describe what you're trying to accomplish. This is the only necessary step to start this process. The Committee is available to assist with all other steps. Please clearly indicate any uncertainty or desired guidance if you proceed beyond this step._

Apply methods for DNA extraction consistently

### Context
_Describe why this new value is necessary and existing values are not._

populate the new code table created in https://github.com/ArctosDB/arctos/issues/6802

### Table
_Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table or value. This may involve multiple tables and will control datatype for Attributes. OtherID requests require BaseURL (and example) or explanation. Please ask for assistance if unsure._

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpreparation_method

### Proposed Value
_Proposed new value. This should be clear and compatible with similar values in the relevant table and across Arctos._

~~Qiagen BioSprint96~~

Qiagen BioSprint96 DNA Blood Kit

### Proposed Definition
_Clear, complete, non-collection-type-specific **functional** definition of the value. Avoid discipline-specific terminology if possible, include parenthetically if unavoidable._

DNA was extracted using a Qiagen BioSprint96 DNA Blood Kit https://www.qiagen.com/us/products/discovery-and-translational-research/dna-rna-purification/dna-purification/genomic-dna/biosprint-dna-blood-kits

### Collection type
_Some code tables contain collection-type-specific values. ``collection_cde`` may be found from https://arctos.database.museum/home.cfm_

N/A

#### Attribute data type
_If the request is for an attribute, what values will be allowed?
free-text, categorical, or number+units depending upon the attribute (TBA)_

N/A

#### Attribute controlled values
_If the values are categorical (to be controlled by a code table), add a link to the appropriate code table. If a new table or set of values is needed, please elaborate._

N/A

#### Attribute units
_if numerical values should be accompanied by units, provide a link to the appropriate units table._

N/A

#### Part preservation attribute affect on "tissueness"
_if a new part preservation is requested, please add the affect it would have on "tissueness": No Influence, Allows, or Denies_

allows

### Priority
_Please describe the urgency and/or choose a priority-label to the right. You should expect a response within two working days, and may utilize [Arctos Contacts](https://arctosdb.org/contacts/) if you feel response is lacking._

### Example Data
_Requests with clarifying sample data are generally much easier to understand and prioritize. Please attach or link to any representative data, in any form or format, which might help clarify the request._

https://github.com/ArctosDB/data-migration/issues/1517#issuecomment-1747380980

### Available for Public View
_Most data are by default publicly available. Describe any necessary access restrictions._

yes

### Helpful Actions

- [x] Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

- [x] Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

@ArctosDB/arctos-code-table-administrators @happiah-madson @falco-rk @campmlc @megulbranson 

## Approval
_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection
_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation
_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

- [x] Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

- [x] Add or revise the code table term/definition as described above. Ensure the URL of this Issue is included in the definition. URLs should be included *_as text_*, separated by spaced pipes. Do not include HTML in definitions.

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by Jegelewicz** [comment]
@happiah-madson @falco-rk is this really a thing or is it some combination of things?

https://www.qiagen.com/us/search/products?query=Biosprint%2096

**Comment by falco-rk** [comment]
Biosprint96 is a machine to automate extractions that could be used with a couple different extraction kits. We used it with the[ biosprint DNA blood kit ](https://www.qiagen.com/us/products/discovery-and-translational-research/dna-rna-purification/dna-purification/genomic-dna/biosprint-dna-blood-kits). So we should maybe make the definition more specific or add an additional part preparation method that is the biosprint DNA blood kit and we would have 2 attributes on our samples extracted using biosprint.

**Comment by falco-rk** [comment]
Or we could just put the biosprint DNA blood kit as the part preparation method attribute and write "Biosprint96" in the methods place. That has the downside of being terrible and requiring us to remember, but its mostly legacy data, so I'm not too worried about it.

**Comment by Jegelewicz** [comment]
> Or we could just put the biosprint DNA blood kit as the part preparation method attribute and write "Biosprint96" in the methods place.

I think this makes more sense?

**Comment by happiah-madson** [comment]
If we do that, then we need to add Biosprint DNA Blood Kit as a new preparation method.

**Comment by Jegelewicz** [comment]
> Biosprint DNA Blood Kit as a new preparation method.

file an issue!

**Comment by Jegelewicz** [comment]
@dustymc OK?

**Comment by dustymc** [comment]
Is 96 just the size??

https://www.qiagen.com/us/products/discovery-and-translational-research/dna-rna-purification/dna-purification/genomic-dna/biosprint-dna-blood-kits

**Comment by mkoo** [comment]
I adjusted the term and added the link to the definition-- this is proprietary so keep the company name associated with it. (and yes, @dustymc it's the size/number of wells). Otherwise I checked a box

**Comment by dustymc** [comment]
So value should be "Qiagen BioSprint" - right??

**Comment by mkoo** [comment]
Yes I suppose you are right in some sense but 96 is the standard size most would get and it is a separate product line so I am inclined to be as specific as possible and include the 96

However rereading this maybe the term should be ```Qiagen BioSprint96 DNA Blood Kit``` to be specific and complete
Anyway, I would be ok with or without 96 so @happiah-madson maybe weigh in if you guys ever buy the smaller kits

**Comment by falco-rk** [comment]
We are happy with Qiagen BioSprint96 DNA Blood Kit. 

BioSprint 96 is a specific instrument. There is also a BioSprint 15.

**Comment by Jegelewicz** [comment]
edits made - @dustymc are we happy?

**Comment by dustymc** [comment]
I'm still lost, sorry!

I *think* this is something like  ``Qiagen BioSprint DNA Blood Kit`` and one could purchase 96, 15, or maybe other amounts **_of the same thing_** packaged for usage in various machines. If that's correct then including the number of wells-er-whatever here just makes it impossible to find everything with a single query - we'll end up with a bunch of the same things but in different sizes. If that's not correct then please set me straight!

The same thing will need addressed on the machine, but in that case it seems more likely that eg the 15-well models have a reputation for whatevering and there might be some reason to keep them separate (or not, whatever, I'm asking - and I suppose that could be true here too).

?????

**Comment by happiah-madson** [comment]
So my understanding is our BioSprint can exclusively handle 96-well plates and we would never be able to use a 15 kit because of reasons. I totally get what you mean about searchability, though. If it helps, we *only* have BioSprint96.

I don't think we're interested on dying on this hill, though, so...

**Comment by dustymc** [comment]
> dying on this hill,

Yea, that hill's definitely not getting fertilized today...

The concerns are laid out here, this is part of the definition, if someone shows up with a 23½-well kit and wants to argue it's the same then we can merge. Concerns addressed, @Jegelewicz you're up.

**Comment by happiah-madson** [comment]
> Yea, that hill's definitely not getting fertilized today...

💀💀💀💀💀💀💀💀

**Comment by Jegelewicz** [comment]
added
