### ISSUE TITLE
leftover bulkloader data 2023-10-23 rpianka

### ISSUE THREAD

**Issue by jtgiermakowski** [ArctosDB/arctos#6868]
@rpianka this file has been in the bulkloader for a few hours. not sure if you forgot it...

[2023-10-23T10-23_rpianka_bulkloader_stage.csv](https://github.com/ArctosDB/arctos/files/13078741/2023-10-23T10-23_rpianka_bulkloader_stage.csv)

**Comment by Jegelewicz** [comment]
@happiah-madson @falco-rk

**Comment by rpianka** [comment]
@jtgiermakowski I believe I just cleared it! Thanks for the heads up.

**Comment by jtgiermakowski** [comment]
cheers! @rpianka
