### ISSUE TITLE
Code Table Request - paradichlorobenzene

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#6874]
### Goal
_Describe what you're trying to accomplish. This is the only necessary step to start this process. The Committee is available to assist with all other steps. Please clearly indicate any uncertainty or desired guidance if you proceed beyond this step._
document botany specimens treated with paradichlorobenzene

### Context
_Describe why this new value is necessary and existing values are not._
nothing in the code table currently represents this type of preservation

### Table
_Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table or value. This may involve multiple tables and will control datatype for Attributes. OtherID requests require BaseURL (and example) or explanation. Please ask for assistance if unsure._
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_preservation

### Proposed Value
_Proposed new value. This should be clear and compatible with similar values in the relevant table and across Arctos._
paradichlorobenzene

### Proposed Definition
_Clear, complete, non-collection-type-specific **functional** definition of the value. Avoid discipline-specific terminology if possible, include parenthetically if unavoidable._
A fumigant insecticide that targets molds, mildews, and insects. http://npic.orst.edu/factsheets/PDBgen.html#products

### Collection type
_Some code tables contain collection-type-specific values. ``collection_cde`` may be found from https://arctos.database.museum/home.cfm_
needed for CHAS:Herb, CHAS:Teach

#### Attribute data type
_If the request is for an attribute, what values will be allowed?
free-text, categorical, or number+units depending upon the attribute (TBA)_

#### Attribute controlled values
_If the values are categorical (to be controlled by a code table), add a link to the appropriate code table. If a new table or set of values is needed, please elaborate._

#### Attribute units
_if numerical values should be accompanied by units, provide a link to the appropriate units table._

#### Part preservation attribute affect on "tissueness"
_if a new part preservation is requested, please add the affect it would have on "tissueness": No Influence, Allows, or Denies_

### Priority
_Please describe the urgency and/or choose a priority-label to the right. You should expect a response within two working days, and may utilize [Arctos Contacts](https://arctosdb.org/contacts/) if you feel response is lacking._

### Example Data
_Requests with clarifying sample data are generally much easier to understand and prioritize. Please attach or link to any representative data, in any form or format, which might help clarify the request._

### Available for Public View
_Most data are by default publicly available. Describe any necessary access restrictions._

### Helpful Actions

- [x] Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

- [x] Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

@ArctosDB/arctos-code-table-administrators 

## Approval
_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection
_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation
_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

- [x] Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

- [x] Add or revise the code table term/definition as described above. Ensure the URL of this Issue is included in the definition. URLs should be included *_as text_*, separated by spaced pipes. Do not include HTML in definitions.

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by Jegelewicz** [comment]
@wellerjes would this treatment affect the ability to get DNA from the specimens? Also, approximately how many records would this affect?

**Comment by mkoo** [comment]
> would this treatment affect the ability to get DNA from the specimens?

According to this article, this particular fumigant would not
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2819063/

but it is toxic so I could see the value of marking that treatment. Sorta same category as ```thymol``` since we've added it here let's do the same with paradichlorobenzene

**Comment by AJLinn** [comment]
Can we add this to all collections, not just botany?

Owners of historical clothing regularly use moth flakes or balls that include PDB and other carcinogenic and respiratory-irritating substances. Likewise, museum professionals regularly used it on textiles and other items made from natural materials to deter pests. It's super important for cultural collections to be able to document past usage of toxic fumigants like PDB, arsenic, etc. as insecticides because if we repatriate sacred objects, people might be wearing these items while they engage in ceremonial activities.

**Comment by Jegelewicz** [comment]
@dustymc check boxes?

**Comment by dustymc** [comment]
>check boxes?

Was hoping for more information re

> approximately how many records would this affect?

@AJLinn no collection_cde on the [table](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_preservation) means it's available to everyone (and we're [moving away from collection_cde ](https://github.com/ArctosDB/arctos/issues/3452)for this anyway).

**Comment by Jegelewicz** [comment]
> no collection_cde on the [table](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_preservation) means it's available to everyone

HAHAHA! That is news to me!

**Comment by Jegelewicz** [comment]
> how many records would this affect?

Well, if we recorded for all legacy stuff, probably A LOT because most mammal and bird skins were stored with mothballs at some point....

I am going to add this link to the description - http://npic.orst.edu/factsheets/PDBgen.html#products

**Comment by Jegelewicz** [comment]
added

**Comment by wellerjes** [comment]
Thank you!
