### ISSUE TITLE
bulkloader providing misleading error when ORIG_LAT_LONG_UNITS is NULL but coordinates are provided

### ISSUE THREAD

**Issue by asemerdj** [ArctosDB/arctos#6875]
Hi there,
I am running into an issue where I am getting this error: "load fail::ERROR: Datum is required when coordinates are given. Where: PL/pgSQL function trigger_fct_trg_locality_biu() line 48 at RAISE" despite including the datum.

I copied and pasted "World Geodetic System 1984" from the code table so it should be formatted the way the bulkloader wants it to be? I'm not sure what the issue is. I attached a file with a couple of specimens that I'm having this problem with.

[cf_temp_specevent_fixes.csv](https://github.com/ArctosDB/arctos/files/13126669/cf_temp_specevent_fixes.csv)

**Comment by Jegelewicz** [comment]
@asemerdj the error is misleading - you are missing ORIG_LAT_LONG_UNITS

**Comment by dustymc** [comment]
>misleading

Yea, mostly, but it's a REALLY complicated path there. I updated the inline docs, calling this next release unless someone has better ideas.

<img width="1076" alt="Screenshot 2023-10-24 at 14 11 23" src="https://github.com/ArctosDB/arctos/assets/5720791/6b895474-c93a-48d6-ad14-2fce5bb5eca0">
