### ISSUE TITLE
Arctos Down - Unable to log in

### ISSUE THREAD

**Issue by genevieve-anderegg** [ArctosDB/arctos#6877]
Please complete to the best of your ability.

## Unplanned Outage
 - Date and time (**please add time zone from which you are reporting**) outage discovered: 2023-10-25 8 AM MDT
 - Describe the outage (Arctos down or only some part not working?): see below

## Communication before/during outage
- [x] Pin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG  
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete
-

Myself and @sharpphyl cannot log in this morning. I keep getting this error, which is different than usual errors for wrong password or other issues I've encountered before: 
![image](https://github.com/ArctosDB/arctos/assets/83782023/8c968eab-e573-47ec-bad1-0018c37cf21d)

Windows, Chrome and Firefox browsers

**Comment by genevieve-anderegg** [comment]
Appears to be down completely now - 503 service not available error

**Comment by dustymc** [comment]
I've asked TACC for help with a database issue, and I took the front end down until that can be resolved.

**Comment by AdrienneRaniszewski** [comment]
how long to you expect it to be down? any ideas?

**Comment by dustymc** [comment]
Arctos is up.

**Comment by ewommack** [comment]
Sorry guys I was at the bug colonies this morning.
