### ISSUE TITLE
Higher geography lookup changes to help text

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6879]
The current text at Geography lookup includes

![image](https://github.com/ArctosDB/arctos/assets/5725767/66b274bb-cf43-4acf-b621-925059acba2f)

Users have found

**Required to Insert:** data_entry 

confusing and have been looking for the header data_entry in the fields to load. Can we change this across all component loaders to say

**Operator Role Required to Insert:** data_entry 

Same goes for **Required to Update:** 

Also, would it be possible to describe what this tool does in that block of text? Preferably at the top?

> This tool checks the data loaded against Arctos higher geography and indicates whether each term is an exact match, a close match, or has no exact or close match at all to a term in higher geography. This tool **does not** update any data in Arctos.

This should be modified to apply to the Agent Pre-bulkloader

> This tool checks the data loaded against Arctos Agents and indicates whether each term is an exact match, a close match, or has no exact or close match at all to an existing agent. This tool **does not** update any data in Arctos.

**Comment by dustymc** [comment]
>Operator Role Required to Insert:

Sure, but that'll have to be a release version (it's hard-coded into the template). Lemme know when that's all solidified and I'll update the template.

>describe what this tool does 

<img width="432" alt="Screenshot 2023-10-27 at 08 40 52" src="https://github.com/ArctosDB/arctos/assets/5720791/3a7ea408-afd4-4ee6-9e58-5600a7f2abbd">

and https://arctos.database.museum/info/component_loader_status.cfm come from ...

```
arctosprod@arctos>> \d cf_component_loader
                                           Table "public.cf_component_loader"
     Column      |            Type             | Collation | Nullable |                     Default                      
-----------------+-----------------------------+-----------+----------+--------------------------------------------------
 key             | integer                     |           | not null | nextval('cf_component_loader_key_seq'::regclass)
 purpose         | character varying           |           | not null | 
 run_order       | integer                     |           | not null | 
 loader_template | character varying           |           | not null | 
 ui_template     | character varying           |           | not null | 
 data_table      | character varying           |           | not null | 
 rec_per_run     | integer                     |           | not null | 
 remark          | character varying           |           |          | 
 lastupdate      | timestamp without time zone |           |          | CURRENT_TIMESTAMP
 lastuser        | character varying           |           |          | SESSION_USER
 manage_roles    | character varying           |           |          | 
 tool_name       | character varying           |           |          | 
 insert_roles    | character varying           |           |          | 
 process_checks  | character varying           |           |          | 
Indexes:
    "ix_u_loader_template" UNIQUE, btree (loader_template)
    "ix_u_ui_template" UNIQUE, btree (ui_template)

```

... ``purpose`` - it's just data, can be updated at any time.

**Comment by Jegelewicz** [comment]
> > Operator Role Required to Insert:
>
> Sure, but that'll have to be a release version (it's hard-coded into the template). Lemme know when that's all solidified and I'll update the template.

So this would change all of the component loader tools? I think the change would benefit them all - who else is needed to confirm that? @ArctosDB/arctos-working-group-officers

**Comment by Jegelewicz** [comment]
> it's just data, can be updated at any time.

Can I edit that? If so where? I would be happy to provide descriptions of the various tools.

**Comment by dustymc** [comment]
>change all of the component loader tools? 

Yep, eventually as they're rebuilt into the latest versions.

>Can I edit that? 

No, there's scary things in there, I need to hang on to it. You can CSV it and I can repatriate changes to the columns that can't eat Arctos though.

**Comment by Jegelewicz** [comment]
> You can CSV it and I can repatriate changes to the columns that can't eat Arctos though.

OK so I am guessing that the tool description should go into `remark` and that I can match that with the tool url so you know which tool the remark belongs to?

**Comment by dustymc** [comment]
https://arctos.database.museum/Admin/CSVAnyTable.cfm?tableName=cf_component_loader will CSV it.

LOADER_TEMPLATE is the best key.

PURPOSE is what you want.

REMARK is mostly me messing with the throttle

**Comment by dustymc** [comment]
done?
