### ISSUE TITLE
use specresulscols for download

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ArctosDB/arctos#688]
```
make it somewhat match specresults
```

Original issue reported on code.google.com by `dust...@gmail.com` on 4 Jun 2014 at 3:35

**Comment by dustymc** [comment]
its better, still imperfect - the "pretty" column names do not always make useful headers - probably need to add a header/display column to cf_spec_res_cols and build forms to manage it to get much better. Seems like a lot of work for not much benefit....

**Comment by campmlc** [comment]
What does this do? I couldn't find info on Github

**Comment by dustymc** [comment]
There are a bunch of things with which we label data.

* table/column - often not in things that display well in tables (eg, Attributes are usually many rows concatenated together for specimenresults).
* The specimensearch term label (mostly hard-coded)
* The results search ("show/hide" box at the top) term label (from "field documentation" - and an experiment in what might be possible in specimensearch)
* The results label (mostly from cf_spec_res_cols which has no interface and builds the "customize results" form)
* What's in downloads, 
* what we send out via IPT etc.
* probably some other stuff

In many cases search terms and results are very different THINGS, or don't exist on both sides - eg, "any taxonomy" on specimen search hits a bunch of stuff (relationships, classifications from globalnames), most of which isn't returned at all (except in the relatively rare case where it's a named rank from a preferred classification).

This is an part of a very long-term ongoing effort to better unify all of those things. Suggestions always appreciated....
