### ISSUE TITLE
NMMNH cleanup (was: searching on institutional catalog number)

### ISSUE THREAD

**Issue by jldunnum** [ArctosDB/arctos#6881]
Trying to search for a series of NMMNH numbers which are in the MSB collection. How do I search for them on their previous institutional numbers? I can see where I can search one at a time using identifier type, the prefix and the number.
![image](https://github.com/ArctosDB/arctos/assets/17278851/469093f2-dd95-4ade-9ab0-83eb19a48838)

However I would like to search for a bunch at a time and I don't see a place where I can list them.

Also if I select "New Mexico Museum of Natural History and Science" or  "New Mexico Museum of Natural History and Science Mammal Collection" in the Identifier issued by field I get zero returns.
It used to be quite easy for me to obtain this type of information for my collection.....

**Comment by Jegelewicz** [comment]
try searching by **issued by** New Mexico Museum of Natural History and Science Mammal Collection

**Comment by dustymc** [comment]
It's difficult to find these because the data are still stuck in an inconsistent limbo.

https://arctos.database.museum/search.cfm?guid_prefix=MSB%3AMamm&oidnum=NMMNH%204418%2CNMMNH%204419 will find some, but I doubt that's consistent.

https://arctos.database.museum/search.cfm?guid_prefix=MSB%3AMamm&id_issuedby=%3DNew%20Mexico%20Museum%20of%20Natural%20History%20and%20Science%20Mammal%20Collection will find some, probably also not consistent (but it's not zero, you have something else going on there).

**Comment by Jegelewicz** [comment]
![image](https://github.com/ArctosDB/arctos/assets/5725767/44c59008-253d-4603-a5fe-39c7ada17ae6)

Note that they all have "NMMNH " as prefixes

**Comment by dustymc** [comment]
@Nicole-Ridgwell-NMMNHS
 @campmlc
 @AdrienneRaniszewski
 @jldunnum
 @lin-fred

 can we make this better?

Here are all "NMMNH " records - I'd need instructions for proceeding.

[temp_NMMNH.csv.zip](https://github.com/ArctosDB/arctos/files/13190825/temp_NMMNH.csv.zip)

Summary:

```

 guid_prefix |        other_id_type         |                    issued_by                     | count 
-------------+------------------------------+--------------------------------------------------+-------
 NMMNH:Geol  | identifier                   |                                                  |     6
 NMMNH:Paleo | institutional catalog number | New Mexico Museum of Natural History and Science |  2172
 MSB:Mamm    | institutional catalog number |                                                  |  5784
 NMMNH:Paleo | identifier                   |                                                  |  1305
 NMMNH:Paleo | institutional catalog number |                                                  |    12
 NMMNH:Mamm  | institutional catalog number |                                                  |  5785
```

and MSB only

[temp_NMMNH_msb.csv.zip](https://github.com/ArctosDB/arctos/files/13190837/temp_NMMNH_msb.csv.zip)

```

 guid_prefix |        other_id_type         | issued_by | count 
-------------+------------------------------+-----------+-------
 MSB:Mamm    | institutional catalog number |           |  5784
(1 row)
```

Presumably those should all be issued by https://arctos.database.museum/agent/21334696, I can update (or there's a loader, you can too) if someone wants to confirm.

(And the type is making things inaccessible, but whatever....)

**Comment by lin-fred** [comment]
So the main change on the NMMNH side would be if we want to keep everything under the broad NMMNHS agent, or assign everything to a smaller division of mammals, birds, paleo etc. 

And then the identifier vs institutional catalog number for geoscience?

Also, Dusty could you tell me what the one NMMNH number is that is making the difference between 5785 for NMMNH and 5784 for MSB?

**Comment by dustymc** [comment]
@lin-fred I didn't look at your data at all, no idea what needs done, if they can be attributed to an agent it'll make discovery way easier. (But if they're attributed to the wrong agent it'll make a mess, so caution!)

> institutional catalog number 

That's clearly just a denormalizer.

> one NMMNH number 

Sorta?

```
arctosprod@arctos>> select * from temp_NMMNH where guid_prefix='NMMNH:Mamm' and  display_value not in (select display_value from temp_NMMNH_msb);
      guid       | guid_prefix |        other_id_type         | display_value | id_references | assigned_agent_id | assigned_by | assigned_date | issued_by_agent_id | issued_by | remarks 
-----------------+-------------+------------------------------+---------------+---------------+-------------------+-------------+---------------+--------------------+-----------+---------
 NMMNH:Mamm:1938 | NMMNH:Mamm  | institutional catalog number | NMMNH 1938    | self          |                 0 | unknown     | 2022-04-27    |                    |           | 
 NMMNH:Mamm:128  | NMMNH:Mamm  | institutional catalog number | NMMNH 128     | self          |                 0 | unknown     | 2022-04-27    |                    |           | 
 NMMNH:Mamm:1944 | NMMNH:Mamm  | institutional catalog number | NMMNH 1944    | self          |                 0 | unknown     | 2022-04-27    |                    |           | 
(3 rows)

```

**Comment by lin-fred** [comment]
>I didn't look at your data at all
Now I am caught up.

> Sorta?
Can you also do that the other way around? See if there are ones in the MSB one that don't match the NMMNH one? Or did that check both ways?

**Comment by dustymc** [comment]
```
arctosprod@arctos>> select * from temp_NMMNH_msb where display_value not in (select display_value from temp_NMMNH  where guid_prefix='NMMNH:Mamm'  );
      guid       | guid_prefix |        other_id_type         | display_value | id_references | assigned_agent_id | assigned_by | assigned_date | issued_by_agent_id | issued_by | remarks 
-----------------+-------------+------------------------------+---------------+---------------+-------------------+-------------+---------------+--------------------+-----------+---------
 MSB:Mamm:271075 | MSB:Mamm    | institutional catalog number | NMMNH 4348    | self          |                 0 | unknown     | 2022-04-27    |                    |           | 
 MSB:Mamm:273566 | MSB:Mamm    | institutional catalog number | NMMNH 5448    | self          |                 0 | unknown     | 2022-04-27    |                    |           | 
(2 rows)

```

**Comment by jldunnum** [comment]
Hi All,
Main thing we want is discoverability by the orginial institutional catalog acronym and number. Original numbers were cited as NMMNH 1234 and that is what people will be trying to find (just had Sean Neisventer and Brett Riddle trying to find specimens they collected and published on trying to find them in Arctos and they couldn't do it). Just not intuitive anymore.  So what ever we can do to make that clear and easy please go that route. My feeling is that these are the types of Institutional Catalog numbers that should have been retained in Arctos and not migrated to the issued by or whatever other agent relationship path has been developed. For collections that have been transferred the original should be very  discoverable. UIMNH is another that I would like the acronym to remain.

______________________________________________________________

Jonathan L. Dunnum Ph.D. (he, him, his)
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

Chair, Systematic Collections Committee, American Society of Mammalogists
Latin American Fellowship Committee, ASM

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by jldunnum** [comment]
Also just back to the search logistics in my original question. Yes I can get all by using the "issued by" query but that still doesn't give me an easy way to just get the records I am interested in. Sorting on the NMMNH number would have done that in the old days, but now all identifiers are concatinated in the same field so it doesn't work. How can I just get the desired records based on a comma delimited list (or range) of NMMNH numbers? Thanks

**Comment by dustymc** [comment]
> How can I just get the desired records based on a comma delimited list (or range) of NMMNH numbers

https://github.com/ArctosDB/arctos/issues/6881#issuecomment-1779855819

**Comment by jldunnum** [comment]
OK thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
The NMMNH Paleo records seem beyond the scope of this issue. Getting all of our NMMNH P-##### formatted catalog numbers updated so they're consistent with how I enter them currently is somewhere on my to do list.

**Comment by Jegelewicz** [comment]
> NMMNH 1234 and that is what people will be trying to find (just had Sean Neisventer and Brett Riddle trying to find specimens they collected and published on trying to find them in Arctos and they couldn't do it). Just not intuitive anymore.  So what ever we can do to make that clear and easy please go that route. My feeling is that these are the types of Institutional Catalog numbers that should have been retained in Arctos and not migrated to the issued by or whatever other agent relationship path has been developed. For collections that have been transferred the original should be very  discoverable. UIMNH is another that I would like the acronym to remain.

@jldunnum 

The MSB records with NMMNH links also include a second identifier that is prefixed with NMMNH

https://arctos.database.museum/search.cfm?guid_prefix=MSB%3AMamm&customoidoper=LIST&oidnum=NMMNH

gives 5,803 results, which is more than expected, but I don't have time to figure that out right now.

https://arctos.database.museum/search.cfm?guid_prefix=MSB%3AMamm&customoidoper=LIST&oidtype=institutional%20catalog%20number&oidnum=NMMNH

gives 5796 results - still more than Dusty's count above, so there are records with the NMMNH prefixed identifier that seem to be missing the Arctos link identifier. Again, I don't have time to reconcile right this minute.

FWIW NONE of the NMMNH prefixed identifiers have an issued by, and they probably should. I'd be happy to add it if you want.

**Comment by jldunnum** [comment]
Yes clearly still lots to clean up and as you state, noone has extra time to devote to every one of these issues. Would be great if you can add issues by to those when you are able. Thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jldunnum** [comment]
Could "institutional catalog number" be a field that is available in the customizable search and results section? This is really a critical one for us because we have incorporated so many collections with these types of numbers. Being able to have them in their own column away from the other identifiers will greatly enhance our ability to work with these.

![image](https://github.com/ArctosDB/arctos/assets/17278851/02217615-2f31-4d87-9ec2-bab49d1453ee)

**Comment by Jegelewicz** [comment]
> Could "institutional catalog number" be a field that is available in the customizable search and results section?

I think that should be a separate issue.

**Comment by Jegelewicz** [comment]
@jldunnum 

Here is some information about the different search results.

> https://arctos.database.museum/search.cfm?guid_prefix=MSB%3AMamm&customoidoper=LIST&oidnum=NMMNH

1. 5,793 of those records include a link to a NMMNH:Mamm record with relationship=same individual as and issued by=New Mexico Museum of Natural History and Science Mammal Collection
2. 5,803 include a "NMMNH " number with relationship=self and issued by =""

the difference is made up of

7 records were missing a NMMNH xxx institutional catalog number:

MSB:Mamm:335938
MSB:Mamm:335937
MSB:Mamm:271736
MSB:Mamm:36063
MSB:Mamm:272277
MSB:Mamm:272304
MSB:Mamm:271588

I added them 

There are also 

10 records that have NMMNH without an associated number or a link to a NMMNH:Mamm record:

GUID | OTHER_ID_TYPE | DISPLAY_VALUE
-- | -- | --
MSB:Mamm:271014 | institutional catalog number | NMMNH
MSB:Mamm:271015 | institutional catalog number | NMMNH
MSB:Mamm:271016 | institutional catalog number | NMMNH
MSB:Mamm:271017 | institutional catalog number | NMMNH
MSB:Mamm:271018 | institutional catalog number | NMMNH
MSB:Mamm:271019 | institutional catalog number | NMMNH
MSB:Mamm:271020 | institutional catalog number | NMMNH
MSB:Mamm:273564 | institutional catalog number | NMMNH
MSB:Mamm:273565 | institutional catalog number | NMMNH
MSB:Mamm:273619 | institutional catalog number | NMMNH

Note that these records DO NOT have a link to any NMMNH record, so if a number is added to the existing identifier, a link to the appropriate NMMNH:Mamm record should be added as well.

Removing the 10 "blank number" records from the new NMMNH institutional catalog number search results now gets me 5,793

Once those 10 records are cleared up then you should get the same results with both identifier searches.

**Comment by Jegelewicz** [comment]
Checking to see that the MSB/NMMNH links are reciprocal:

Noticed that this record https://arctos.database.museum/guid/NMMNH:Mamm:1363

had two links, deleted https://arctos.database.museum/guid/MSB:Mamm:79290 because that record seems to have no relationship to the NMMNH record ( it is offspring of the linked MSB record, but it appears that the parent has no NMMNH number. This whole thing seems weird? @jldunnum @lin-fred 

![image](https://github.com/ArctosDB/arctos/assets/5725767/dce85c0a-0567-4745-9a19-30f93d774c91)

**Comment by Jegelewicz** [comment]
Exact same scenario for https://arctos.database.museum/guid/NMMNH:Mamm:1364

![image](https://github.com/ArctosDB/arctos/assets/5725767/8da9360e-e8b5-42fc-b069-24ea55a60bb7)

**Comment by Jegelewicz** [comment]
The link to MSB in https://arctos.database.museum/guid/NMMNH:Mamm:5448 has the self relationship, which I changed to same individual as.

So

https://arctos.database.museum/search.cfm?guid_prefix=NMMNH%3AMamm&customoidoper=LIST&id_issuedby=Museum%20of%20Southwestern%20Biology%2C%20Division%20of%20Mammals&id_references=same%20individual%20as

5,793 results

https://arctos.database.museum/search.cfm?guid_prefix=MSB%3AMamm&customoidoper=LIST&id_issuedby=New%20Mexico%20Museum%20of%20Natural%20History%20and%20Science%20Mammal%20Collection&id_references=same%20individual%20as

5,793 results

https://arctos.database.museum/search.cfm?guid_prefix=MSB%3AMamm&customoidoper=LIST&id_issuedby=New%20Mexico%20Museum%20of%20Natural%20History%20and%20Science%20Mammal%20Collection&id_references=same%20individual%20as

5,803 results due to the 10 numberless NMMNH identifiers

I think we can be done here if those 10 records get cleared up. @jldunnum @lin-fred

**Comment by dustymc** [comment]
closing for lack of interest
