### ISSUE TITLE
Feature Request - ability to delete identifications

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#6882]
For most of Arctos history we could delete identifications (if we had permissions)

Now it seems there is no delete button - we've lost this functionality.

Sometimes identifications are made in error and should be deleted. Please restore this functionality.

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._
high

**Comment by genevieve-anderegg** [comment]
I can delete identifications in the catalog record by setting the ID Order to DELETE, in the same spot where you chose the determination order: 
![image](https://github.com/ArctosDB/arctos/assets/83782023/0fb3f6e6-7b20-4527-a2fd-dfe69df1a553)

Then you click Save Changes and reload the record and it's gone.
Is this what you are looking for?

**Comment by DerekSikes** [comment]
yes, thanks! Hidden now...

-D

**Comment by genevieve-anderegg** [comment]
Happy to help!

**Comment by Jegelewicz** [comment]
Add a link to https://github.com/ArctosDB/arctos/issues/6882#issuecomment-1780114687 in documentation

**Comment by Jegelewicz** [comment]
I have updated documentation. Closing.
