### ISSUE TITLE
Need Help with Arctos Error

### ISSUE THREAD

**Issue by esdearmon** [ArctosDB/arctos#6885]
load fail::ERROR: function is_claimed_barcode(character varying, character varying) does not exist Hint: No function matches the given name and argument types. You might need to add explicit type casts. Position: 8

I received the above error when trying to upload new container barcodes, see attached file. I checked the barcode would pass in the guidelines and it did.
[Row6_Shelves.csv](https://github.com/ArctosDB/arctos/files/13192008/Row6_Shelves.csv)

**Comment by dustymc** [comment]
This is stuck because https://github.com/ArctosDB/arctos/issues/6789#issuecomment-1780182421 is paused.  I believe Mariel is out dealing with family issues. I can push that through Monday, and/or I can manually create those containers for you, just let me know

**Comment by esdearmon** [comment]
Thank you! I will wait until it is it is back up! Glad to hear it wasn't an error on my end.


Emily S. DeArmon

Sr. Collection Manager: Fishes

Museum of Southwestern Biology

***@***.***

(505) 277-6005

________________________________
