### ISSUE TITLE
Old Reporter problem

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#6886]
The old Reporter seems dead. Is there anything you can do to shock it back to life?
![image](https://github.com/ArctosDB/arctos/assets/12507297/63a172db-36d9-47dc-bee4-9181507329f8)

(I've been working on new reports in the new Reporter - I'll get back to work on that)

**Comment by dustymc** [comment]
It's not dead (WOW!!), there's something about your report - I tried..

<img width="975" alt="Screenshot 2023-10-27 at 15 18 55" src="https://github.com/ArctosDB/arctos/assets/5720791/53c40353-23f4-401f-8afa-42d4c6c96b3f">

and it's dodging whatever security issue you're hitting.

**Comment by acdoll** [comment]
Hmm. It goes to that error immediately upon hitting the link to the old reporter (before the screen you posted).

**Comment by acdoll** [comment]
![image](https://github.com/ArctosDB/arctos/assets/12507297/24c787ac-3feb-47be-8201-b1b117b0d20c)

**Comment by dustymc** [comment]
Maybe the 'too many tabs confuses it' thing - try a fresh browser session?

**Comment by acdoll** [comment]
I tried that. John started this and was getting the same error. I just tried in FireFox (instead of Chrome) and get the same result. Could it be an issue with the data I'm trying to print from? 
https://arctos.database.museum/search.cfm?guid_prefix=DMNS%3AMamm&cat_num=22501-22507

**Comment by dustymc** [comment]
Nope

<img width="1256" alt="Screenshot 2023-10-27 at 15 28 19" src="https://github.com/ArctosDB/arctos/assets/5720791/a303cccb-9697-4b23-ae8a-4b9625cad12f">

**Comment by acdoll** [comment]
I did a full restart of my computer, still same problem. I'm calling it for the week - I'll try again on Monday. Thanks

**Comment by mkoo** [comment]
Authentication type 10 -- something's blocking his IP-- if a driver issue then probably local, right?
Can you send your IP @acdoll? (https://whatismyipaddress.com/) What is your OS/ version?

**Comment by acdoll** [comment]
4.4.78.193
Windows 10 Pro; version 21H2

**Comment by dustymc** [comment]
I suspect this is some weird fringe case of the very old JDBC drivers (built in to deprecated proprietary software running on an extinct OS - don't think there's any real chance for upgrading any of that) trying to interact with a new database, and failing with  - who knows, some character in your password, or some obscure math involving your username, or ??????????? Definitely could be IP, OS, sunspots.......

Let me know if there's any way I can facilitate the move!

**Comment by dustymc** [comment]
done?
