### ISSUE TITLE
Request to increase character length of record attribute verbatim attribute

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6889]
I have necropsy descriptions of cause of death that I using verbatim attribute to record that exceed the current 255 character limit allowed for [verbatim attribute](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#verbatim_attribute).

Example

> cause of death | Final:  Trauma-suspect propeller strike; mild multifocal lymphocytic and suppurative meningoencephalitis-suspect protozoal etiology (protozoal infection in brain suspected, more suggestive of toxo); mild multifocal lymphoplasmacytic and suppurative myocarditis.  Negative for morvillivirus.  High level of domoic acid (204.3 ng/g). 10/25/2012 Findings to date:  gross observations suggested trauma (shark or boat propeller) as a COD.   Urine tested positive for domoic acic (204.3 ng/g).  This level is considered high enough to possible cause symptoms.

Can we increase the number of characters allowed for this free-text attribute?

I have already loaded a number of these that were under the 255 limit for UWBM:Mamm and would like to complete the task.

**Comment by dustymc** [comment]
done
