### ISSUE TITLE
Synonyms not being searched on???

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#6894]
I had a request to pull all of our [Denazinosuchus kirtlandicus](https://arctos.database.museum/name/Denazinosuchus%20kirtlandicus#Arctos) for a loan. [Goniopholis kirtlandicus](https://arctos.database.museum/name/Goniopholis%20kirtlandicus#Arctos) is a junior synonym and has a synonym relationship with Denazinosuchus kirtlandicus in Arctos. However, when I ran my [search](https://arctos.database.museum/search.cfm?guid_prefix=NMMNH%3APaleo&taxon_name=Denazinosuchus%20kirtlandicus) the specimens still identified as Goniopholis kirtlandicus did not come up. I only realized this after the fact and am now having to adjust the loan.

I thought search was supposed to pull synonyms? I also tried searching under Identification with the same result? Is there another identification search field I'm not using where this works?

**Comment by dustymc** [comment]
The search works by first magicking something like https://arctos.database.museum/name/Myodes#ArctosRelationships - I think maybe that's stuck, I'll go next task to fix, please prioritize accordingly. (Seems like a critical bug from here...)

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks!

**Comment by dustymc** [comment]
Arctos Relationships exists mostly for searching, I can't quite see how the non-classification data are useful in that context, there are many GB (TB?!) of those data (worms is very verbose), I'd rather not drag them around unless there's a reason to. If nobody has that reason I'm going to cache only classification data. (Super-easy to change.)

Example with: https://arctos-test.tacc.utexas.edu/name/Lymnaea%20stagnalis

<img width="1514" alt="Screenshot 2023-10-31 at 17 31 01" src="https://github.com/ArctosDB/arctos/assets/5720791/09b855b1-e69e-41d6-88f1-307c6edc1190">


and without: https://arctos-test.tacc.utexas.edu/name/Hiona%20glandula

<img width="870" alt="Screenshot 2023-10-31 at 17 31 34" src="https://github.com/ArctosDB/arctos/assets/5720791/b3b8bdd9-bae8-4e90-9820-83565486a65a">

**Comment by dustymc** [comment]
@Nicole-Ridgwell-NMMNHS I refreshed those manually. This is running at production, it will take some time for everything to catch up, please let me know if you want to prioritize something, see any issues, whatever.

Here are the last few to refresh if anyone wants to check them out.

```

 Actinella nitidiuscula
 Agardhiella lamellata
 Agardhiella parreyssii
 Amenixesta hunsteini
 Anastomosa gomphiformis
 Auchenipterus lacustris
 Balcomitra
 Barbus guentheri
 Barilius interrupta
 Barilius rugosus
 Bulimus pealianus
 Calyptraea corrugata
 Chloritis stirophora
 Clarias gariepinus
 Clarias xenodon
 Columbinia columbiana
 Cristiceps amaenus
 Curimatus albula
 Cyrillia ephesina
 Defrancia linearis var. aequalis
 Diplectanotrema priacanthi
 Diplorchis scaphiopi
 Drymaeus pealianus
 Dyakia janus
 Encope borealis
 Epibdella diadema
 Eulima parfaiti
 Glycymeris martini
 Glyptosternum madraspatanum
 Glyptothorax madraspatanus
 Gulella disseminata
 Gulella landianiensis
 Helix balasteriana
 Helix rehsei
 Helminthia vermicularis praerepta
 Hemichromis auritus
 Hemichromis sacra
 Heros guttulatus
 Heros triagramma
 Hybopsis chiliticus
 Labeobarbus reinii
 Liotia solitaria
 Lucerapex indagatoris
 Mormyrus adspersus
 Mormyrus catostoma
 Myloplus lobatus
 Nanina hunsteini
 Neodiplectanotrema priacanthi
 Oospira lepidospira
 Opeas arctispirale
 Opisthoporus quadrasi
 Pleurotoma parva
 Pseudogonaxis percivali
 Purpura depressa
 Solecurtus ellipticus
 Solecurtus murrayvianus
 Sorubimichthys ortoni
 Streptaxis percivali
 Tellina aequilatera
 Tellina ralphi
 Trichromis salvini
 Trochozonites prestoni
 Trochus oppressus var. dunedinensis
 Vitreolina parfaiti
 Voluta conoidea
 Volutoconus ralphi
 Zebrina fasciolata
```

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks!
