### ISSUE TITLE
Code Table Request - new event attribute: cruise

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6896]
### Goal
_Describe what you're trying to accomplish. This is the only necessary step to start this process. The Committee is available to assist with all other steps. Please clearly indicate any uncertainty or desired guidance if you proceed beyond this step._

record cruise names associated with events

### Context
_Describe why this new value is necessary and existing values are not._

Knowledge of the cruise can help reveal additional information.

![image](https://github.com/ArctosDB/arctos/assets/5725767/006c06a6-1f88-47fa-8c7d-3393cd0b244c)

We considered making each cruise a project, but

![image](https://github.com/ArctosDB/arctos/assets/5725767/a5cc99d3-4bf3-47a5-b943-df692f755e26)

So, while there may end up being projects, it may not be feasible due to accessions including items that may be from one or more cruises.

### Table
_Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table or value. This may involve multiple tables and will control datatype for Attributes. OtherID requests require BaseURL (and example) or explanation. Please ask for assistance if unsure._

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_event_attr_type

### Proposed Value
_Proposed new value. This should be clear and compatible with similar values in the relevant table and across Arctos._

cruise

### Proposed Definition
_Clear, complete, non-collection-type-specific **functional** definition of the value. Avoid discipline-specific terminology if possible, include parenthetically if unavoidable._

A particular voyage on a vessel that includes or is included in the event.

### Collection type
_Some code tables contain collection-type-specific values. ``collection_cde`` may be found from https://arctos.database.museum/home.cfm_

N/A

#### Attribute data type
_If the request is for an attribute, what values will be allowed?
free-text, categorical, or number+units depending upon the attribute (TBA)_

free-text

#### Attribute controlled values
_If the values are categorical (to be controlled by a code table), add a link to the appropriate code table. If a new table or set of values is needed, please elaborate._

N/A

#### Attribute units
_if numerical values should be accompanied by units, provide a link to the appropriate units table._

N/A

#### Part preservation attribute affect on "tissueness"
_if a new part preservation is requested, please add the affect it would have on "tissueness": No Influence, Allows, or Denies_

N/A

### Priority
_Please describe the urgency and/or choose a priority-label to the right. You should expect a response within two working days, and may utilize [Arctos Contacts](https://arctosdb.org/contacts/) if you feel response is lacking._

### Example Data
_Requests with clarifying sample data are generally much easier to understand and prioritize. Please attach or link to any representative data, in any form or format, which might help clarify the request._

cruiseNumber
--
0
224
2012
201504
201691
201791
201892
67.19.32
AII125-40
AT 15-22
AT 15-9
AT0307
AT03-24
AT0338
AT03-38
AT07-05
AT07-26
AT11-01
AT11-03
AT11-20
AT1503
AT15-03
at15-28
AT18-03
AT26-12
B-037
C241
C247
CReefs Lizard Island 2010
EX1504L2
EX1504L3
EX1504L4
EX1603
EX1605L1
EX1605L3
EX1606
EX1702
EX1703
EX1705
EX1706
EX1708
EX1711
EX1803
EX1806
EX1811
F/V Northern: VII-04-II: 3
F/V Northern: VII-05-I: 2
GM201692
GM201705
GM201801
GoM2002
GoM2003
GoM2004
LMG0806
LMG08-06
LMG08-06, LMG08-07
LMG1003
LMG1003, LMG1004
LMG1004
MGLN07MV
NA
NA NA
NA034
NA-034
NA035
NA037
NA039
NA040
NA041
NA042
NA043
NA044
NA054 -Kick 'Em Jenny
NBP04-04
ND
R/V Albatross IV: 94-09: 40
R/V Albatross IV: 94-09: 41
R/V Oregon II: 248: 261
R/V Oregon II: 248: 286
R/V Oregon II: 250: 18
RB0704
RB0905
RB09-05
RB1007
RB1007
S-222
TN235
TUIM07MV

### Available for Public View
_Most data are by default publicly available. Describe any necessary access restrictions._

yes

### Helpful Actions

- [x] Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

- [x] Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

@ArctosDB/arctos-code-table-administrators @happiah-madson @falco-rk @sharpphyl @genevieve-anderegg @kmkocot 

## Approval
_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection
_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation
_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

- [x] Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

- [x] Add or revise the code table term/definition as described above. Ensure the URL of this Issue is included in the definition. URLs should be included *_as text_*, separated by spaced pipes. Do not include HTML in definitions.

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Sounds good to me.

**Comment by happiah-madson** [comment]
Just checking in on this!

**Comment by Jegelewicz** [comment]
@mkoo @campmlc @ccicero check a box?

**Comment by kmkocot** [comment]
Hi all. Sorry for my silence. I'm very in favor of this!

**Comment by campmlc** [comment]
I support as well.

**Comment by Jegelewicz** [comment]
added
