### ISSUE TITLE
SQL updates for Cheatsheet (loan and tissue report stats)

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#6898]
I have a series of these to update and will update (and cleanup the Cheatsheet as I go). Most will be easy since the errors need to be just updated with the recent changes. Instead of pasting SQL all over the issues list I have them in them in [a google doc share with Dusty](https://docs.google.com/document/d/1zRXUUduqYgUOJqjAaQEILENCeD2RTiL5ufCsJmgTkCY/edit) -- please help fix!

These are the scripts:
- [ ] Number of parts in consumable and returnable loans in a period by collection
- [ ] Count of the barcoded containers by collection
(Note this may be different than Number  of Frozen Tissue Samples (in a collection)
- [ ] Count of species per collection

thanks!

**Comment by dustymc** [comment]
done

**Comment by mkoo** [comment]
updating doc now! thanks!
