### ISSUE TITLE
component loaders accept zero-length username

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6899]
**Describe the bug**

https://github.com/ArctosDB/data-migration/issues/1817#issuecomment-1785985396

```
arctosprod@arctos>> select username,count(*) from cf_temp_attributes group by username;
  username   | count 
-------------+-------
 acdoll      |    54
 kkay        |    49
 ganderegg   |    57
 mhilke      |     1
             |  1590
```

**Priority**

High?

**Comment by Jegelewicz** [comment]
> High?

I would think so.

**Comment by acdoll** [comment]
Three of those users are from DMNS; are we doing something we shouldn't?

**Comment by dustymc** [comment]
>doing something we shouldn't?

Sorta? You should get an error rather than having things disappear into limbo, which means you shouldn't be able to load things with an unknown agent. I think that's all my problem...

**Comment by dustymc** [comment]
Here are record attribute records with no username. I deleted them from the tool and temporary table.

[temp_cf_temp_attributes.csv.zip](https://github.com/ArctosDB/arctos/files/13284189/temp_cf_temp_attributes.csv.zip)

**Comment by dustymc** [comment]
These users had mismatched usernames in record attributes:

```

  username  
------------
 marissammi
 adrienner
 LEAC
 kkay
```

I corrected the case, that may have changed what's visible in the tool.

**Comment by dustymc** [comment]
These users had mismatched usernames in the parts loader:

```
----------
 bcarroll

```

I corrected the case, that may have changed what's visible in the tool.

**Comment by dustymc** [comment]
These users had mismatched usernames in the locality loader:

```

--------------------
 katherinelanderson
```

I corrected the case, that may have changed what's visible in the tool.
