### ISSUE TITLE
iframe url does not have permission......

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#6901]
**Describe the bug**
Sometimes while using Chrome in Arctos, I get this popup. I have to hit OK numerous time, then I have only a couple of seconds to do anything on the screen before it comes up again. I had not seen it for months, but has reappared for me. Any suggested fixes for this?

**To Reproduce**
Not sure. Happens randomly. 

**Expected behavior**
No popup

**Screenshots**
Attached

**Desktop (please complete the following information):**
 - Mac OS: 13.3.1 (a) 
 - Chrome Version 116.0.5845.187 (Official Build) (x86_64)

**Priority**
Medium. When it happens I go over to Safari.
<img width="463" alt="Screenshot 2023-10-31 at 9 07 04 AM" src="https://github.com/ArctosDB/arctos/assets/5749672/a95e0095-0fa1-44dd-a3df-d0079bf04b6a">

**Comment by Jegelewicz** [comment]
https://github.com/ArctosDB/arctos/issues/6181 was closed - I am not sure what is causing this (I have never experienced it) but have you tried using Firefox instead?

**Comment by cjconroy** [comment]
I have not tried Firefox. I'd rather not use one browser for most of my stuff and another for Arctos, especially when it comes up randomly. I'd like to know how to fix it in Chrome if possible.

**Comment by mkoo** [comment]
This error is hard to track down/ reproduce -- @cjconroy did you try my suggestion (it worked at least a few weeks ago for me in Chrome)

>Users can also address (what I did a while ago) with a CORS extension on FF or Chrome (eg https://addons.mozilla.org/en-US/firefox/addon/access-control-allow-origin/ or https://addons.mozilla.org/en-US/firefox/addon/cors-everywhere/) or https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf

Also, please be specific which pages initiate the iframe error box; really cant do anything without that info!

There are things that could be done on the software side however to allow cross-origin calls. Might be Berkeleymapper that is triggering...

**Comment by dustymc** [comment]
I don't think this is browser-related.

It involves a geolocate call, and it's from something messing with your network traffic. Some Chrome extension was the culprit at least once. I found that by screen-sharing with Carla, only way I'm going to figure this out involves watching your JS console while you re-create the error. Let me know if you want to Zoom.

**Comment by cjconroy** [comment]
It only happens sporadically. It was a problem yesterday for a couple of hours, but is not happening now. And, it had not happened in many months. If it happens again, is there something I can pull up on my computer to screen shot?

**Comment by dustymc** [comment]
I doubt if a static image will help but you can try sending your console log.

**Comment by cjconroy** [comment]
is this what you want? The error has come up again. 

Nov 15 23:53:21 MacBook-Pro syslogd[119]: ASL Sender Statistics
Nov 16 00:53:26 MacBook-Pro syslogd[119]: ASL Sender Statistics
Nov 16 00:53:27 MacBook-Pro syslogd[119]: Configuration Notice:
	ASL Module "com.apple.cdscheduler" claims selected messages.
	Those messages may not appear in standard system log files or in the ASL database.
Nov 16 00:53:27 MacBook-Pro syslogd[119]: Configuration Notice:
	ASL Module "com.apple.install" claims selected messages.
	Those messages may not appear in standard system log files or in the ASL database.
Nov 16 00:53:27 MacBook-Pro syslogd[119]: Configuration Notice:
	ASL Module "com.apple.authd" sharing output destination "/var/log/asl" with ASL Module "com.apple.asl".
	Output parameters from ASL Module "com.apple.asl" override any specified in ASL Module "com.apple.authd".
Nov 16 00:53:27 MacBook-Pro syslogd[119]: Configuration Notice:
	ASL Module "com.apple.authd" sharing output destination "/var/log/system.log" with ASL Module "com.apple.asl".
	Output parameters from ASL Module "com.apple.asl" override any specified in ASL Module "com.apple.authd".
Nov 16 00:53:27 MacBook-Pro syslogd[119]: Configuration Notice:
	ASL Module "com.apple.authd" claims selected messages.
	Those messages may not appear in standard system log files or in the ASL database.
Nov 16 00:53:27 MacBook-Pro syslogd[119]: Configuration Notice:
	ASL Module "com.apple.eventmonitor" claims selected messages.
	Those messages may not appear in standard system log files or in the ASL database.
Nov 16 00:53:27 MacBook-Pro syslogd[119]: Configuration Notice:
	ASL Module "com.apple.mail" claims selected messages.
	Those messages may not appear in standard system log files or in the ASL database.
Nov 16 00:53:27 MacBook-Pro syslogd[119]: Configuration Notice:
	ASL Module "com.apple.performance" claims selected messages.
	Those messages may not appear in standard system log files or in the ASL database.
Nov 16 00:53:27 MacBook-Pro syslogd[119]: Configuration Notice:
	ASL Module "com.apple.iokit.power" claims selected messages.
	Those messages may not appear in standard system log files or in the ASL database.
Nov 16 00:53:27 MacBook-Pro syslogd[119]: Configuration Notice:
	ASL Module "com.apple.contacts.ContactsAutocomplete" claims selected messages.
	Those messages may not appear in standard system log files or in the ASL database.
Nov 16 00:53:27 MacBook-Pro syslogd[119]: Configuration Notice:
	ASL Module "com.apple.mkb" sharing output destination "/private/var/log/keybagd.log" with ASL Module "com.apple.mkb.internal".
	Output parameters from ASL Module "com.apple.mkb.internal" override any specified in ASL Module "com.apple.mkb".
Nov 16 00:53:27 MacBook-Pro syslogd[119]: Configuration Notice:
	ASL Module "com.apple.mkb" claims selected messages.
	Those messages may not appear in standard system log files or in the ASL database.
Nov 16 00:53:27 MacBook-Pro syslogd[119]: Configuration Notice:
	ASL Module "com.apple.MessageTracer" claims selected messages.
	Those messages may not appear in standard system log files or in the ASL database.
Nov 16 02:53:39 MacBook-Pro syslogd[119]: ASL Sender Statistics
Nov 16 04:54:10 MacBook-Pro syslogd[119]: ASL Sender Statistics
Nov 16 05:33:37 MacBook-Pro syslogd[119]: ASL Sender Statistics
Nov 16 07:33:53 MacBook-Pro syslogd[119]: ASL Sender Statistics
Nov 16 08:28:32 MacBook-Pro syslogd[119]: ASL Sender Statistics
Nov 16 08:41:15 MacBook-Pro syslogd[119]: ASL Sender Statistics
Nov 16 08:51:21 wifi-10-40-183-31 syslogd[119]: ASL Sender Statistics
Nov 16 09:01:21 wifi-10-40-183-31 syslogd[119]: ASL Sender Statistics
Nov 16 09:11:21 wifi-10-40-183-31 syslogd[119]: ASL Sender Statistics
Nov 16 09:15:46 wifi-10-40-183-31 awdd[269]: Diagnostics Report
Nov 16 09:16:16 --- last message repeated 1 time ---
Nov 16 09:21:21 wifi-10-40-183-31 syslogd[119]: ASL Sender Statistics
Nov 16 09:35:48 wifi-10-40-183-31 syslogd[119]: ASL Sender Statistics
Nov 16 09:46:32 wifi-10-40-183-31 syslogd[119]: ASL Sender Statistics
Nov 16 09:56:32 wifi-10-40-183-31 syslogd[119]: ASL Sender Statistics
Nov 16 10:06:32 wifi-10-40-183-31 syslogd[119]: ASL Sender Statistics
Nov 16 10:16:32 wifi-10-40-183-31 syslogd[119]: ASL Sender Statistics
Nov 16 10:26:38 wifi-10-40-183-31 syslogd[119]: ASL Sender Statistics
Nov 16 10:49:05 wifi-10-40-183-31 syslogd[119]: ASL Sender Statistics
Nov 16 11:00:46 wifi-10-40-183-31 syslogd[119]: ASL Sender Statistics
Nov 16 11:12:23 wifi-10-40-183-31 syslogd[119]: ASL Sender Statistics
Nov 16 11:34:05 wifi-10-40-183-31 syslogd[119]: ASL Sender Statistics
Nov 16 11:49:05 wifi-10-40-183-31 syslogd[119]: ASL Sender Statistics
Nov 16 11:54:55 wifi-10-40-183-31 Adobe Reader and Acrobat Updater[20442]: Adobe Acrobat Updater encountered errorCode 1042
Nov 16 11:54:55 wifi-10-40-183-31 Adobe Reader and Acrobat Updater[20442]: Adobe Acrobat Updater encountered errorCode 1535
Nov 16 11:54:55 wifi-10-40-183-31 Adobe Reader and Acrobat Updater[20442]: Adobe Acrobat Updater encountered errorCode 1651
Nov 16 12:02:48 wifi-10-40-183-31 syslogd[119]: ASL Sender Statistics
Nov 16 12:13:31 wifi-10-40-183-31 syslogd[119]: ASL Sender Statistics
Nov 16 12:23:38 wifi-10-40-183-31 syslogd[119]: ASL Sender Statistics
Nov 16 12:33:38 wifi-10-40-183-31 syslogd[119]: ASL Sender Statistics
Nov 16 12:43:38 wifi-10-40-183-31 syslogd[119]: ASL Sender Statistics
Nov 16 12:53:38 wifi-10-40-183-31 syslogd[119]: ASL Sender Statistics
Nov 16 13:03:38 wifi-10-40-183-31 syslogd[119]: ASL Sender Statistics
Nov 16 13:14:24 wifi-10-40-183-31 syslogd[119]: ASL Sender Statistics
Nov 16 13:27:44 wifi-10-40-183-31 syslogd[119]: ASL Sender Statistics
Nov 16 13:38:46 wifi-10-40-183-31 syslogd[119]: ASL Sender Statistics
Nov 16 13:50:30 wifi-10-40-183-31 syslogd[119]: ASL Sender Statistics
Nov 16 14:01:07 wifi-10-40-183-31 syslogd[119]: ASL Sender Statistics
Nov 16 14:14:28 wifi-10-40-183-31 syslogd[119]: ASL Sender Statistics
Nov 16 14:25:47 wifi-10-40-183-31 syslogd[119]: ASL Sender Statistics
Nov 16 14:37:45 wifi-10-40-183-31 syslogd[119]: ASL Sender Statistics
Nov 16 14:50:46 wifi-10-40-183-31 syslogd[119]: ASL Sender Statistics
Nov 16 15:02:24 MacBook-Pro syslogd[119]: ASL Sender Statistics

**Comment by dustymc** [comment]
No, I think that's something else, and I'd need to know the event which caused the error.

**Comment by cjconroy** [comment]
atrox said you figured out some extension she and Carla had that was causing the issue. Any way for this to be checked?

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/6901#issuecomment-1789127909

**Comment by ufarrell** [comment]
Had the same problem just now on Firefox, was going to jump in to ask for help as well - but then tried disabling ExpressVPN extension and that worked, in case thats any help to anybody. I didn't have it on, just enough that it was installed. (Same extension on Chrome, but it doesn't have the problem)

**Comment by Jegelewicz** [comment]
@Pristimantis2016 see the post above for help with the iframe url permission pop-up.

**Comment by mkoo** [comment]
Solved! but I am going to add this to a milestone of Known problems since someone else will ahve this too!
