### ISSUE TITLE
Reload with shareable URL fails for map-based search

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#6902]
I did a search on identification = Bombus and restricted the search using the map polygon tool to this:
![Screenshot 2023-10-31 at 1 14 07 PM](https://github.com/ArctosDB/arctos/assets/9099827/b0b019e1-461d-4cb9-875e-4dec52f974b5)

1,022 records were found

Then  I reloaded with shareable URL and 39,811 records were found (all the Bombus records) - the map restriction was ignored.

The URL:

https://arctos.database.museum/search.cfm?scientific_name=bombus&poly_coords=%5B%7B%22lat%22%3A59.07513843808454%2C%22lng%22%3A-135.26264190673828%7D%2C%7B%22lat%22%3A59.54892163669221%2C%22lng%22%3A-135.04840850830078%7D%2C%7B%22lat%22%3A59.78196283783703%2C%22lng%22%3A-135.48236846923828%7D%2C%7B%22lat%22%3A59.58257224032437%2C%22lng%22%3A-136.21295928955078%7D%2C%7B%22lat%22%3A59.245271451342646%2C%22lng%22%3A-136.39185875052078%7D%5D

when fired finds those 39,811 records. Not the 1022 records.

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.
high - I had hoped to put the URL in an agency report due this week.

**Comment by dustymc** [comment]
A change of scenery would be most welcome - I'll try to get this patched in ~tomorrow.

**Comment by dustymc** [comment]
Please break it: https://arctos-test.tacc.utexas.edu/?scientific_name=bombus&poly_coords=%5B%7B%22lat%22%3A59.07513843808454%2C%22lng%22%3A-135.26264190673828%7D%2C%7B%22lat%22%3A59.54892163669221%2C%22lng%22%3A-135.04840850830078%7D%2C%7B%22lat%22%3A59.78196283783703%2C%22lng%22%3A-135.48236846923828%7D%2C%7B%22lat%22%3A59.58257224032437%2C%22lng%22%3A-136.21295928955078%7D%2C%7B%22lat%22%3A59.245271451342646%2C%22lng%22%3A-136.39185875052078%7D%5D

Also note that if you want to control what columns they (initially) see you can include a profile eg

https://arctos-test.tacc.utexas.edu/search.cfm?scientific_name=bombus&poly_coords=%5B%7B%22lat%22%3A59.07513843808454%2C%22lng%22%3A-135.26264190673828%7D%2C%7B%22lat%22%3A59.54892163669221%2C%22lng%22%3A-135.04840850830078%7D%2C%7B%22lat%22%3A59.78196283783703%2C%22lng%22%3A-135.48236846923828%7D%2C%7B%22lat%22%3A59.58257224032437%2C%22lng%22%3A-136.21295928955078%7D%2C%7B%22lat%22%3A59.245271451342646%2C%22lng%22%3A-136.39185875052078%7D%5D&sp=%F0%9F%A4%A1%20%F0%9F%A5%9C

I got there by going to the first link and then selecting one of my profiles, but you can always toss a ``&sp=...`` in the URL. 

<img width="1012" alt="Screenshot 2023-11-01 at 07 27 40" src="https://github.com/ArctosDB/arctos/assets/5720791/09e1faa2-fa82-48aa-93be-a047beeb2906">


This will have some limitations (involving the number of vertices that can be passed around in a GET request), but it works OK with a reasonably-complex polygon:


https://arctos-test.tacc.utexas.edu/search.cfm?scientific_name=bombus&poly_coords=%5B%7B%22lat%22%3A59.632938338885936%2C%22lng%22%3A-136.33317068849436%7D%2C%7B%22lat%22%3A59.81572076956896%2C%22lng%22%3A-136.12443045411936%7D%2C%7B%22lat%22%3A59.71060440018431%2C%22lng%22%3A-135.69047049318186%7D%2C%7B%22lat%22%3A59.81295878677655%2C%22lng%22%3A-135.24003104005686%7D%2C%7B%22lat%22%3A59.67179386442992%2C%22lng%22%3A-134.74015311036936%7D%2C%7B%22lat%22%3A59.59125745484073%2C%22lng%22%3A-134.93790701661936%7D%2C%7B%22lat%22%3A59.5940377892897%2C%22lng%22%3A-135.55314139161936%7D%2C%7B%22lat%22%3A59.477065654212275%2C%22lng%22%3A-135.70145682130686%7D%2C%7B%22lat%22%3A59.477065654212275%2C%22lng%22%3A-134.88297537599436%7D%2C%7B%22lat%22%3A59.59681789384952%2C%22lng%22%3A-133.87223318849436%7D%2C%7B%22lat%22%3A59.771501569731086%2C%22lng%22%3A-133.85575369630686%7D%2C%7B%22lat%22%3A59.66901996216259%2C%22lng%22%3A-132.80655936036936%7D%2C%7B%22lat%22%3A59.398858484379836%2C%22lng%22%3A-133.05924490724436%7D%2C%7B%22lat%22%3A59.45753080764374%2C%22lng%22%3A-133.54264334474436%7D%2C%7B%22lat%22%3A59.28120842955141%2C%22lng%22%3A-133.65799979005686%7D%2C%7B%22lat%22%3A59.48543427489107%2C%22lng%22%3A-134.15238455568186%7D%2C%7B%22lat%22%3A59.26998239925977%2C%22lng%22%3A-134.21280936036936%7D%2C%7B%22lat%22%3A59.27559587701037%2C%22lng%22%3A-135.39383963380686%7D%2C%7B%22lat%22%3A59.38487388857968%2C%22lng%22%3A-134.62479666505686%7D%2C%7B%22lat%22%3A59.31486432092282%2C%22lng%22%3A-136.61881521974436%7D%2C%7B%22lat%22%3A59.39326533842263%2C%22lng%22%3A-135.89921072755686%7D%2C%7B%22lat%22%3A59.46032219140676%2C%22lng%22%3A-138.32718924318186%7D%2C%7B%22lat%22%3A59.4742756531794%2C%22lng%22%3A-137.12418631349436%7D%2C%7B%22lat%22%3A59.87918322596736%2C%22lng%22%3A-138.37662771974436%7D%2C%7B%22lat%22%3A59.574570619776736%2C%22lng%22%3A-137.01981619630686%7D%2C%7B%22lat%22%3A59.86815496811192%2C%22lng%22%3A-137.04728201661936%7D%2C%7B%22lat%22%3A59.71060440018431%2C%22lng%22%3A-136.76163748536936%7D%2C%7B%22lat%22%3A59.85988137394052%2C%22lng%22%3A-136.24528006349436%7D%2C%7B%22lat%22%3A59.63571522630668%2C%22lng%22%3A-136.49796561036936%7D%5D

**Comment by DerekSikes** [comment]
thanks!
