### ISSUE TITLE
search window doesn't come up when tagging events

### ISSUE THREAD

**Issue by asemerdj** [ArctosDB/arctos#6903]
Hi there,
I noticed that the search window doesn't come up when I tried to tag collecting events in media. There's a place to put a 'reference' for the event, but that doesn't seem to correspond to the event's ID or name. Is there something else I'm supposed to use?

Thanks,
Alyssa

**Comment by Jegelewicz** [comment]
> there's a place to put a 'reference' for the event, but that doesn't seem to correspond to the event's ID or name. 

You should be using the shows collecting_event relationship and that will bring up a search for events.

![image](https://github.com/ArctosDB/arctos/assets/5725767/a734cf90-923c-4fb7-ab47-e5429739bb2a)

![image](https://github.com/ArctosDB/arctos/assets/5725767/4e719aeb-5d0a-4f42-9ee2-b6a297abf167)

**Comment by dustymc** [comment]
Fixed for next release, thanks.
