### ISSUE TITLE
Problems with MSB Herp Loan Invoice in Reports

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6904]
Trying to print a loan invoice using MSB:Herp Loan Invoice Detail html in Reports. 
Problem: Some records are missing localities. 
Additional request: we need to be able to print the collector number on the report. It shows in the header but not in the report itself. Fixable? 
@Jegelewicz @dustymc @jtgiermakowski 
[2023.09.Herp Loan Invoice_final 11-1-2023.pdf](https://github.com/ArctosDB/arctos/files/13229983/2023.09.Herp.Loan.Invoice_final.11-1-2023.pdf)

**Comment by jtgiermakowski** [comment]
I fixed the collector number (although it now prints the entire name followed by the actual collector number).

**Comment by campmlc** [comment]
> I fixed the printing of the collector number (although it now prints the entire name followed by the actual collector number).

Yes, that is super problematic. All Arctos forms and search results are now doing that, which makes spreadsheet downloads and data management difficult. We need the option of a simple version.

**Comment by jtgiermakowski** [comment]
Yea, Mariel L. Campbell Mariel, we definitely need to nix the full name on the collector numbers. It's very annoying!

I have no idea why the locality shows up for some but not all, maybe Teresa J. Mayfield-Meyer Teresa  @Jegelewicz  or Dusty Dusty L. McDonald @dustymc have an idea?  

:-)

**Comment by jtgiermakowski** [comment]
OK, found out that in that accession we were missing "As-entered Coordinates", which apparently was part of the locality string as defined in the reporter. 

I took out "case when orig_lat_long_units is not null then '. ' || verbatim_coordinates end " and now the locality shows up for all records in the report; however, we're missing the "verbatim_coordinates" from the locality string.

**Comment by dustymc** [comment]
I rewrote the report - @jtgiermakowski I might have overwritten your last save, sorry!

**Comment by dustymc** [comment]
FYI ``concat`` ignores NULLs, a NULL in ``||`` will make the entire expression evaluate to NULL, and ``concat_ws`` works like ``concat`` but with delimiter goodness.

**Comment by jtgiermakowski** [comment]
hmmm... maybe I overwrote yours?

I ended with:

higher_geog || '. ' || spec_locality  || '' || case when orig_lat_long_units is not null then '. ' || verbatim_coordinates else '. No verbatim coords' end as locality,

**Comment by dustymc** [comment]
Yup. I saved again, and here's the SQL I used
```
<cfquery name="d" datasource="user_login" username="#session.dbuser#" password="#decrypt(session.epw,session.sessionKey,'AES/CBC/PKCS5Padding','hex')#">
select 
    flat.collection, 
    flat.collection_cde, 
    flat.cat_num, 
    flat.scientific_name, 
    flat.guid,
    case 
    when trim(flat.sex)='male' then 'male'
    when trim(flat.sex)='female' then 'female'
    else '?'
    end as sex,
    concatotherid(flat.collection_object_id) as other_ids,
    concatIdentifierValueByType(flat.collection_object_id,'collector number') collector_number,
    concatIdentifierValueByType(flat.collection_object_id,'preparator number') preparator_number,
    concatIdentifierValueByType(flat.collection_object_id,'NK') NK,
    concatIdentifierValueByType(flat.collection_object_id,'original identifier')  original_identifier,
    concatIdentifierValueByType(flat.collection_object_id,'verbatim host ID') verbatim_host_ID,
    specimen_part.part_name as part,
    specimen_part.condition part_condition,
    CASE WHEN length(specimen_part.condition) > 15 or flat.ENCUMBRANCES is not null THEN 'X' end AS has_appendix, 
    concat(higher_geog,'. ',spec_locality,'. ' || verbatim_coordinates) as locality,
    item_instructions, 
    loan_item_remarks as remarks, 
    specimen_part.disposition coll_obj_disposition, 
    flat.ENCUMBRANCES, 
    loan.loan_number,
    trans.trans_date,
    flat.datum,
    flat.verbatim_coordinates,
    specimen_part.part_count as count
from 
    loan_item
    inner join loan on loan_item.transaction_id =loan.transaction_id 
    inner join  trans on loan.transaction_id = trans.transaction_id
    inner join specimen_part on loan_item.part_id = specimen_part.collection_object_id
    inner join flat on specimen_part.derived_from_cat_item = flat.collection_object_id
WHERE 
    loan_item.transaction_id = <cfqueryparam value="#transaction_id#" cfsqltype="cf_sql_int"> ORDER BY cat_num
</cfquery>
<div class="page">
  <table>
    <thead class="header">
    <tr><td class="headtd">
      <div class="header">
        <table>
        <tr>
          <th class="headleft">UNIVERSITY OF NEW MEXICO</th>
          <th class="headcenter">MUSEUM OF SOUTHWESTERN BIOLOGY</th>
          <th class="headright">DIVISION OF AMPHIBIANS AND REPTILES</th>
        </tr>
        <tr>
          <td class="headleft">Loan: #d.loan_number#</td>
          <td class="headcenter">SPECIMEN LIST</td>
          <td class="headright">Loan Date: #dateformat(d.trans_date,"dd mmm yyyy")#</td>
        </tr>
        </table>        
      </div>
    </td></tr>
    </thead>
    <p> </p>
    <tbody>
      <tr><td class="headtd">
          <div class="content">
        <table>
        <tr>
          <th>Catalog ##</th>
          <th>Coll No.</th>
          <th>Scientific Name</th>        
          <th>Count</th>
          <th>Locality</th>
          <th>Item</th>       
        </tr>
        <cfloop query="d">
          <tr>
            <td class="catnum">#guid#</td>
            <td>#collector_number#</td>
            <td class="sn">#replace(scientific_name," "," ","all")#</td>            
            <td>#count#</td>
            <td>#locality#</td>
            <td>#part#</br>Remarks: #remarks#</td>
           </tr>
        </cfloop>
          </table>
        </div>
        </td></tr>
     </tbody>
     <tfoot>
        <tr><td class="headtd">
            <div class="footer">
        </div>
        </td></tr>
     </tfoot>
  </table>
</div>

```

**Comment by jtgiermakowski** [comment]
Awesome, thanks @dustymc , looks spiffy and I learned new SQL tricks!
