### ISSUE TITLE
[external CONTACT] function error in creating barcoded container positions

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#6906]
@atrox10 and I are trying to create new positions for a barcoded freezer box. We've tried with two different barcodes and get the same error:

ERROR: function is_claimed_barcode(character varying) does not exist Hint: No function matches the given name and argument types. You might need to add explicit type casts. Where: PL/pgSQL function createcontainer(character varying,character varying,character varying,character varying,character varying,double precision,double precision,double precision,integer,integer,character varying,character varying,character varying,integer) line 22 at IF

ERROR_SQL: select createContainer ( v_container_type => 'position', v_label => '1', v_description => null, v_container_remarks => null, v_barcode => null, v_width => 1.2, v_height => 4.9, v_length => 1.2, v_number_rows => null, v_number_columns => null, v_orientation => null, v_posn_hld_ctr_typ => null, v_institution_acronym => 'MVZ', v_parent_container_id => 12030876 )

@dustymc seems like this is a problem on the backend?

**Comment by dustymc** [comment]
Fixed about 5 minutes ago....

**Comment by ccicero** [comment]
Thanks!
