### ISSUE TITLE
Year-old data removed from table Taxon Relationship Loader

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6912]
26 year-old records have been removed from Taxon Relationship Loader (table: cf_temp_taxon_relation).

Data:

[temp_cache.cf_temp_taxon_relation_2023_11_02.csv.zip](https://github.com/ArctosDB/arctos/files/13241188/temp_cache.cf_temp_taxon_relation_2023_11_02.csv.zip)

Usernames:

* ffdss (26 records)

Users have access to these collections:

* KNWR:Ento
* KNWR:Inv
* KWP:Ento
* UAA:Ento
* UAM:Ento
* UAMObs:Ento

Collection Contacts

* @DerekSikes
* @mlbowser
* @justybob

**Comment by DerekSikes** [comment]
I had forgotten about these. What's the story? Why did they not load. I checked the first taxon: Euura kukakiana and the synonymy relationship is not there. These should be loaded to make those taxon name relationships.

**Comment by Jegelewicz** [comment]
They are all related taxon name notfound

RELATED_TAXON_NAME
--
Pontania kukakiana
Amauronematus leucolenus
Amauronematus lineatus
Pachynematus montivagus
Nematus nigriventris
Amauronematus dulichus
Pachynematus corniger
Amaruronematus abnormis
Amauronematus amentorum
Pachynematus annulatus
Nematus atriceps
Amauronematus obscuripes
Pontania ora
Amauronematus oregonensis
Pachynematus pleuricus
Nematus poecilonotus
Nematus polaris
Nematus pravus
Nematus salicisodoratus
Pachynematus sporax
Nematus calais
Pachynematus clitellatus
Hemichroa amelanchieridis
Pontania sueta
Aedes cantator
Aedes cockerelli

The first one is not found in a taxon name search, so guessing that none of these are yet in Arctos.

**Comment by DerekSikes** [comment]
Ah, that explains it. Thanks Teresa!

no worries then. Closed.

**Comment by Jegelewicz** [comment]
@DerekSikes if you are confident those names should be in Arctos I would be happy to add them, then add the relationships!

**Comment by DerekSikes** [comment]
Low priority since I'm not using them. Not sure if anyone would benefit from them being added to Arctos...
