### ISSUE TITLE
Searching in multiple geographic states

### ISSUE THREAD

**Issue by adhornsby** [ArctosDB/arctos#6915]
Is there a way -- other than drawing a polygon on the map -- to search for records within multiple states at once?  E.g., I'm trying searches like _Montana,Idaho,Wyoming_ and _Montana OR Idaho OR Wyoming_ in Any Geographic Element and in Asserted State/Province, but to no avail.

**Comment by Jegelewicz** [comment]
I also tried asserted state/province and got nothing.

![image](https://github.com/ArctosDB/arctos/assets/5725767/34e3eed0-468d-42b6-84bc-0ba99a9504e3)

@dustymc no commas allowed in geo search? Could we have an "in list" option?

**Comment by dustymc** [comment]
https://arctos.database.museum/search.cfm?state_prov=Montana|Idaho|Wyoming

I updated the documentation, it should clear the cache in a couple hours.

**Comment by adhornsby** [comment]
Perfect, thanks @dustymc !
