### ISSUE TITLE
Arctos Down - not loading

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#6919]
Please complete to the best of your ability.

## Unplanned Outage
 - November 2, 2023 at 2:30pm
 - clicking on the link and nothing is loading

## Planned Outage
 - Date and time outage will begin:
 - Date and time outage is expected to end:
 - Reason for outage:
 - Expected behavior during and after the outage:

## Communication before/during outage
- [ ] Pin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG  
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Arctos is also not loading for me.

**Comment by dustymc** [comment]
restarted
