### ISSUE TITLE
locality access weirdness

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6924]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

Attempting to add the locality access = private attribute and the options are some collections?

**To Reproduce**
1. Go to  a named locality
2. Click on attribute type and select locality access
3. click the dropdown and get a bunch of collection stuff

**Expected behavior**

I expected to have the choice = private

**Screenshots**

<img width="960" alt="Screenshot 2023-11-03 14 35 04" src="https://github.com/ArctosDB/arctos/assets/5725767/e5e02e92-bcc4-4961-9abb-5038240f3c6d">

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

I was trying to do this for https://arctos.database.museum/editLocality.cfm?locality_id=12118873

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/5054
