### ISSUE TITLE
Arctos Down

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#6927]
Please complete to the best of your ability.

## Unplanned Outage
Cannot access Arctos at all but no error message.  06 Nov 2023 since about 7:00 a.m. MST

## Planned Outage
 - Date and time outage will begin:
 - Date and time outage is expected to end:
 - Reason for outage:
 - Expected behavior during and after the outage:

## Communication before/during outage
- [x] Pin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG  
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by Jegelewicz** [comment]
Also down in ABQ

**Comment by dustymc** [comment]
restarted
