### ISSUE TITLE
Island Group - do we need it?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6928]
How is the code table island group used?

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctisland_group

If it is not used, can we remove it from the code table list? I feel that this code table is causing confusion.

**Comment by dustymc** [comment]
Yes it's used, https://arctos.database.museum/tblbrowse.cfm?tbl=ctisland_group

**Comment by Jegelewicz** [comment]
That explains nothing to me! HOW is it used? It can't be part of higher geography (where it used to be used), so where can I enter island group in data entry?

**Comment by mkoo** [comment]
Answer is yes it's used as a legacy piece of info that needs a new place in the new world order. So we need to determine what we need this for and figure out how to make it happen in the current Arctos spatial framework. Currently it's there because it has no where else to go but not useful to keep adding to the mess. Maybe it can go straight into Locality Attributes for new incoming records?! 

Where does this go on the Geography committee priority list? (that's the question!)

**Comment by genevieve-anderegg** [comment]
> Maybe it can go straight into Locality Attributes for new incoming records?!

I think it would be good to keep them around as a way to link records, perhaps as Locality Attributes. Will definitely add to Geography agenda!

**Comment by sharpphyl** [comment]
> That explains nothing to me! HOW is it used? It can't be part of higher geography (where it used to be used), so where can I enter island group in data entry?

It appears that it's not searchable but it can appear in the results.  But how does it get there?  I can't find any of our records that used to have Island (such as Sanibel) or Island Group (such as Tonga and Fiji) that still have an entry in those fields.  To add it to new records as an attribute is fine, but how do we get it into existing records for consistency.  Sounds like we're reinventing old data we eliminated.

**Comment by genevieve-anderegg** [comment]
As of the April Geography Committee Meeting,

Islands and island group data are scattered, and there is no common place for these data, and no recommended place. They are in features, specific localities, etc. (#7660). There are current limitations in Arctos postGIS (#6521), which limits spatial solutions (a best case scenario would be that every record has coordinates, and then the user would have names and coordinates recommended to them that would attach to the record). 

@mkoo suggested that an interim best practice could be creating locality attributes for islands (as well as other geographic areas, like protected areas etc.), a la #7374 for waterbody. This would help searchability and discoverability, and would assist with curatorial needs.

**Comment by dustymc** [comment]
I'm killing this, I think it's just a distraction.

>not searchable

Island is spatially searchable (within technical limitations).

>can appear in the results

Yea, that's broken, I'll clean it up.

>locality attributes for...

Generally fine with me, in the meantime and I think compatible with other stuff.

>where can I enter island group in data entry?

Any place name that's not in assertable geography should be entered in spec_locality.
