### ISSUE TITLE
Arctos Report Help Request Loan needs information from agent

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6931]
**Description of the report** - [Write a brief description of the report you need. Include link or name of previous report if migrating from a Cold Fusion report.]

I am working on this report - https://arctos.database.museum/Reports/reporter.cfm?action=edit&report_id=123

**Collection for which the report is needed** - [Enter the GUID prefix of the requesting collection]

UWBM Paleo Collections (see also https://github.com/ArctosDB/data-migration/issues/1823). To match their existing report format, I need to add the following information and I don't think I can get it from the loan information:

1. email, telephone, and Institution from the outside contact agent
2. count of loan items
3. shipping method from the shipment

@dustymc
**Priority** - [Please assign a priority so that the DBA knows whether there is any urgency associated with the new template}

**Comment by dustymc** [comment]
>email

always been there

>telephone

added, but I picked a random of the at least three types (I ever say anything about functional definitions being kinda critical??)

>Institution

You're gonna have to tell me where that is.

>count

added

>method

added

**Comment by Jegelewicz** [comment]
> >   telephone
> 
> added, but I picked a random of the at least three types (I ever say anything about functional definitions being kinda critical??)

work phone seems appropriate

> > Institution
> 
> You're gonna have to tell me where that is.

I figured that one would be nearly impossible because we aren't consistent about reporting employers, and even if we were, there can be more than one. What are your thoughts on how to do this? I do think that the institution to which objects are being loaned matters and I think most have dealt with that by putting the institution name as the first line of the shipping address (or somewhere in the shipping address). I can see two ways to make this work:

1. Add a new [transaction agent role](https://arctos.database.museum/info/ctDocumentation.cfm?table=cttrans_agent_role): outside institution - The institution with which the outside contact is employed or associated,. Only one outside institution is allowed. If you want to add contacts, please use the "contact agent" role.
2. Use the current employer of the outside contact

Any other ideas?

**Comment by Jegelewicz** [comment]
> shipping method

is shipment_type supposed to be that? It isn't what I am looking for - I want to get this

![image](https://github.com/ArctosDB/arctos/assets/5725767/34b4aa14-4ca7-4e36-90a9-4a3b6dbd3e76)

I tried adding

`shipped_method,`

to the SELECT, but that fails.

**Comment by dustymc** [comment]
>appropriate

I think you can probably see how to change that in the SQL, but let me know if you need more help.

>your thoughts on how to do this?

I think that's usually just embedded in the address, which seems entirely appropriate to me.

> institution to which objects are being loaned matters

Not sure I see that, new Issue from the collections if they think so.

>new [transaction agent role](https://arctos.database.museum/info/ctDocumentation.cfm?table=cttrans_agent_role): ou

🤮

>current employer

I'd say something about cardinality (lots of people don't have just one job at any time), but there are already like 50 layers of assumptions baked in here - if they want to try to maintain those data and nothing needs to scale then I can probably write the code....


>shipment_type supposed to be that? 

https://arctos.database.museum/tblbrowse.cfm?tbl=shipment always holds that answer (and https://github.com/ArctosDB/arctos/issues/6920 might make it a bit easier to find https://arctos.database.museum/info/ctDocumentation.cfm?table=ctshipped_carrier_method which is keyed to ``shipment.shipped_carrier_method``)
