### ISSUE TITLE
Need Help with Arctos Error in Browse/Edit Bulkloaded Data

### ISSUE THREAD

**Issue by megulbranson** [ArctosDB/arctos#6932]
# Error Text
"null value in column "identification_order" of relation "identification" violates not-null constraint"

# Where it happened

Browse/Edit Bulkloaded Data
(https://arctos.database.museum/Bulkloader/browseBulk.cfm)

# Steps to get there
I made it through the bulkloader and fixed the appropriate errors to get my files to load, then when I went to set these to autoload I received the error. 

# Problem
It looks like the issue is that I just need to update a column to rank the identification of the specimen as "1." I tried updating a few of the records to have "identification_1_order" updated to "1" but that did not resolve the error. I don't see a column named "identification_order" so I am not sure how to address this.

<img width="1009" alt="Screenshot 2023-11-06 at 4 47 03 PM" src="https://github.com/ArctosDB/arctos/assets/134456825/d3ec85a6-0695-4a32-9ca9-6c45d33d469f">

# Solution
Unsure, this might be user error, or possibly an issue with the column names in the Browse/Edit Bulkloaded Data page.

**Comment by dustymc** [comment]
The problem is here:

<img width="513" alt="Screenshot 2023-11-07 at 06 40 46" src="https://github.com/ArctosDB/arctos/assets/5720791/19e257e7-d003-4c33-ae72-ce651d71c664">

I don't see any that are not NULL under your username.

Going next task to update the spreadsheet and error.

**Comment by Jegelewicz** [comment]
@megulbranson Arctos requires that you order your identifications. In general "1" = accepted and "0" = unaccepted, then any other number (up to 10) can whatever meaning you want. This can be used for many reasons - also see https://handbook.arctosdb.org/documentation/identification.html#identification-order

In your case, I would imagine these would all be 1.

**Comment by megulbranson** [comment]
> I don't see any that are not NULL under your username.

Right, I updated about 5 of them under "identification_1_order" from NULL to "1" and when that did not resolve the error I changed them back to NULL out of caution. If this is the correct column to update to 1 I will go ahead and do that. Then once you update the spreadsheet and error I assume I'll be able to set them to autoload?

**Comment by dustymc** [comment]
You can set them to autoload now, all I'll change is documentation/error message.

**Comment by megulbranson** [comment]
Should I still update "identification_1_order" first? I have a couple thousand to update and am not sure the most efficient way to do so at this stage.

**Comment by Jegelewicz** [comment]
@megulbranson you can use the sql function to update them all.

![image](https://github.com/ArctosDB/arctos/assets/5725767/65f207b6-dd0a-4d8a-b591-7249bf98b481)

![image](https://github.com/ArctosDB/arctos/assets/5725767/592f4dd1-b1f5-44c8-9e9b-55597a84db93)

**Comment by megulbranson** [comment]
> @megulbranson you can use the sql function to update them all.

@Jegelewicz @dustymc Thanks, I did try that and it is my first time trying the SQL function so I may be doing something wrong. I saw that the function can load "at most 500 records" so I limited my search to the first ~490 records using the Key identifiers in a comma-list, then clicked SQL. I got to the correct page but received an error notification and then the page became unresponsive. I tried this a few times with the same result.

<img width="1462" alt="Screenshot 2023-11-07 at 10 00 28 AM" src="https://github.com/ArctosDB/arctos/assets/134456825/767e2634-f1b5-4dfa-a156-b3d534f1ed75">

<img width="1161" alt="Screenshot 2023-11-07 at 10 00 16 AM" src="https://github.com/ArctosDB/arctos/assets/134456825/34082245-eed3-4375-a793-162c24e58488">

**Comment by dustymc** [comment]
>error notification

That's just your browser choking, an expected cost of adding lots of columns. (And my warning/filter is apparently a bit optimistic for your environment.) You can get more resources (....), try with fewer records, or let me know exactly what you want updated and I can SQL it for you.

**Comment by megulbranson** [comment]
I tried with 100 records and my browser still couldn't handle it. If you are able to write an SQL that could update all 2355 UAM:Ento records entered by me (mejones4) that would be awesome. I just need "identification_1_order" updated to "1" for each record.

**Comment by dustymc** [comment]
Done.

**Comment by megulbranson** [comment]
Thank you!

**Comment by megulbranson** [comment]
Thank you!
