### ISSUE TITLE
[CONTACT: Blocked Network]

### ISSUE THREAD

**Issue by ufarrell** [ArctosDB/arctos#6933]
restricted IP: 212.129.76.193

Hi @dustymc, I’m at a conference and on my mobile so apologies if formatting not right! I have links to specimens on my poster and no one can access them because of blocked ips. Anything I can do to avoid this in future?

**Comment by dustymc** [comment]
I dropped all restrictions to that subnet, it should clear up in the next 5 minutes.

I can definitely do that preemptively if the event can indicate the IP space they'll be using.

**Comment by ufarrell** [comment]
Great, Thank you! It’s just one day, but next time I’ll try and be preemptive about it.
