### ISSUE TITLE
Need Help with Arctos Error - Citation Bulkloader

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#6936]
# Error Text
username does not have access to collection

# Where it happened
[Bulkload citations](https://arctos.database.museum/tools/BulkloadCitations.cfm). I've left the data in review and load for now.

# Steps to get there
I formatted a bulkload citation file following my usual protocol, but this time it came back with this error. I've quadruple checked that the GUID was formatted correctly. I checked to make sure manage_publications, manage_specimens, and nmmnh_paleo hadn't suddenly disappeared from my user account, they are still there.

**Comment by dustymc** [comment]
Thx, try again plz.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thank you, loaded successfully!
