### ISSUE TITLE
Code Table Request - ctshipment_type - prefix-thingees

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6937]
### Goal

Shipment type has weird prefixes, and the current forms filter using them. I'm going to drop that for https://github.com/ArctosDB/arctos/issues/6737, and I suspect it will spawn CT requests. I don't understand what we were trying to do with this format. Can we update (or document) the current values?

### Context

I don't actually care what the values are, I just need to write sustainable and modular forms.

Shipments are always attached to transactions, I don't think the department of redundancy department approach can add any clarity.
 

### Table

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctshipment_type

### Proposed Value

???????????? this might need to become several issues if we decide to update

### Proposed Definition

TBD

**Comment by Jegelewicz** [comment]
It does seem like the prefix part can be inferred from the associated transaction?

I can see the need for incoming/outgoing as one thing and complete/partial as another. It definitely feels like we are trying to do too much with one thing.

## shipment direction
provides information about whether the shipment is coming to the recording institution or leaving the recording institution.

**controlled vocabulary**
term | description 
 -- | -- 
incoming | the shipment will arrive at the recording institution
outgoing | the shipment will leave the recording institution

## shipment completeness
provides information about whether the shipment includes all objects associated with a transaction or not.

**controlled vocabulary**
term | description 
 -- | -- 
complete | the shipment includes all objects associated with the transaction
partial | the shipment does not include all objects associated with the transaction

Of course, I can then see needing to associate WHAT was shipped in a partial shipment....

**Comment by dustymc** [comment]
I don't think we need to add complexity, and certainly not ambiguous complexity! Shipments contain two addresses, "incoming" is from that easily inferrable for all parties, no way to get confused, no need for anything else.

>includes all objects 

Transactions are arbitrary administrative things, which provides two possibilities:

1. Do some complicated thing which might confuse everyone, like ship a single loan in several installments, or
2. Break the loan into several simple transactions.

I have no intention of trying to prevent anything, but there's already an easy path to unambiguous data and I don't think we need to provide any more ways to stray from it.

**Comment by Jegelewicz** [comment]
If incoming and outgoing can be inferred from the To/From, then great - but I feel like people are using this to do annual reports: "x loans were shipped out and x were returned". As long as we can facilitate that, then simpler is definitely better.

**Comment by dustymc** [comment]
If there's some additional need then there needs to be an additional discussion. I'm just warning everyone that the prefix-thingee-filters aren't going to survive the next release, and wondering if we can simplify. That's it....

**Comment by dustymc** [comment]
No interest, tabling.
