### ISSUE TITLE
Arctos Down - Browser spins

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6938]
Please complete to the best of your ability.

## Unplanned Outage
 - Date and time (**please add time zone from which you are reporting**) outage discovered: 2023-11-08 11:12 AM MST
 - Describe the outage (Arctos down or only some part not working?): My browser just spins. Attempted with both Firefox and Chrome, same result.

## Planned Outage
 - Date and time outage will begin:
 - Date and time outage is expected to end:
 - Reason for outage:
 - Expected behavior during and after the outage:

## Communication before/during outage
- [x] Pin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG  
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by camwebb** [comment]
Possibly just a coincidence, but I had just submitted a report job to make label PDFs to the CF reporter when then the system froze. 😬

**Comment by dustymc** [comment]
@camwebb I saw that and tried to blame you! Don't think that was it, better luck next time.... but try again, just in case, please.

Restarted.

**Comment by mkoo** [comment]
I assume I triggered it because I was doing a demo!
thanks for addressing!

**Comment by camwebb** [comment]
@dustymc Resubmitted to reporter several times. Jobs timeout but do not take down Arctos - I'm just learning how to use the system, so I hope to be successful shortly!
