### ISSUE TITLE
sccoffman@alaska.edu

### ISSUE THREAD

**Issue by sccoffman** [ArctosDB/arctos#6942]
Hello,
When I search the UAMN Archaeology collection, the Alaska Heritage Resources Survey (AHRS) number is not available as search option. Is it possible to include the AHRS # in the "Customize Search & Results" profile? I have also noticed that when I check fields (under the customize search and results) and click "Use Selected" the fields that I just checked do not appear and I can still not search by those added fields. 
It's frustrating.

Thanks

**Comment by dustymc** [comment]
Try this: https://arctos.database.museum/search.cfm?guid_prefix=UAM%3AArc&oidtype=AHRS%20(Alaska%20Heritage%20Resources%20Survey)

More information would be greatly appreciated. Are you perhaps adding results terms (right side of the popup) instead of search terms (left side)? If that's not it more information about your browser, screenshots, or whatever might help me find what's wrong would be greatly appreciated. Or we can Zoom if that's better.

**Comment by sccoffman** [comment]
Github didn't like my first message. Hope this works...

**Comment by dustymc** [comment]
Don't think that worked either, you can email ``arctos.database@gmail.com`` if that's better.

**Comment by AJLinn** [comment]
Just a note here. AHRS numbers are listed as "other identifiers" of the type "AHRS (Alaska Heritage Resources Survey).

<img width="648" alt="Screenshot 2023-11-08 at 6 19 42 PM" src="https://github.com/ArctosDB/arctos/assets/17605945/04b48e65-87e4-4495-951d-09ead04f101f">

Therefore, it's not a standalone element that can be searched for on its own... not sure if you can display other ID numbers in the search results. How do we search for those other numbers?

**Comment by Jegelewicz** [comment]
> How do we search for those other numbers?

![image](https://github.com/ArctosDB/arctos/assets/5725767/695ab412-3ad1-4e52-8773-4064030e4b60)

Add the identifiers block to your search customization.

![image](https://github.com/ArctosDB/arctos/assets/5725767/99419818-a89a-4555-8059-a5ed134d674c)

To see them in results, add the simple identifiers to your results:

![image](https://github.com/ArctosDB/arctos/assets/5725767/a95bd2e5-a237-420a-a896-6e5eff599631)

If you want detail about the identifiers, you can get the identifier download from your search results:

<img width="960" alt="Screenshot 2023-11-09 08 25 35" src="https://github.com/ArctosDB/arctos/assets/5725767/c627a7a6-f3af-49be-91d4-aac9ff4290a4">

**Comment by dustymc** [comment]
Screenshots emailed to me, further suggestions on how we can clarify most appreciated.

[Start page-1.pdf](https://github.com/ArctosDB/arctos/files/13310763/Start.page-1.pdf)

**Comment by sccoffman** [comment]
I was unable to find "other identifiers" as Angela suggested, but rather,
used "any identifier" to search for AHRS numbers and can use this moving
forward. Though adding AHRS as a stand alone would be ideal in my opinion.
Thanks for the help.

**Comment by AJLinn** [comment]
From your customize view in your screenshots you have the Accession selected for your results, but not your search options:
<img width="1217" alt="Screenshot 2023-11-09 at 8 14 09 AM" src="https://github.com/ArctosDB/arctos/assets/17605945/7f93649b-f9f8-43d5-8cba-70997468d981">


Be sure to add the Accession column to both search and results:
<img width="702" alt="Screenshot 2023-11-09 at 8 17 24 AM" src="https://github.com/ArctosDB/arctos/assets/17605945/c6284f71-3cbc-4d5e-957d-ede0fb743ea1">

<img width="1611" alt="Screenshot 2023-11-09 at 8 20 12 AM" src="https://github.com/ArctosDB/arctos/assets/17605945/255ac112-7d72-4965-89d2-2c8bb1dfa4a1">

**Comment by AJLinn** [comment]
Thanks for the tips on the identifiers searching and simple Identifiers results  @Jegelewicz! Super handy!

**Comment by dustymc** [comment]
Also, click the eyeballs to see documentation (or a lack of it in this case - someone care to add to inline documentation?):

<img width="247" alt="Screenshot 2023-11-09 at 09 23 22" src="https://github.com/ArctosDB/arctos/assets/5720791/fc469fae-7daf-4627-80a6-8f30b8bcc0ff">

"Accession" means at least three things across different traditions, in Arctos it's an internal/administrative 'batch received' identifier.

**Comment by sccoffman** [comment]
Thank you all.

**Comment by mkoo** [comment]
thanks for all the details!
Pro Tip to @sccoffman : just search "AHRS" in Issued By and select when the value pops up and forget about Identifier Type. Add the value if you know it or just hit search to see all the records for that collection! Faster search this way!
