### ISSUE TITLE
Unknown agent birth date 

### ISSUE THREAD

**Issue by lin-fred** [ArctosDB/arctos#6947]
I'm getting reports on all of my specimens that use the agent "unknown" that they are mismatching or using the wrong agent because the birth date is not in line with the collection date of the specimen. 

I looked at the agent page for "unknown" and there are several dates in that agent, are they from rolled over bad duplicates? Does this normally happen? And if they are rolled over from bad duplicates, can we delete that alive/born data?

https://arctos.database.museum/guid/NMMNH:Inv:12346

[Unknown agent](https://arctos.database.museum/agents.cfm?agent_id=0)

**Comment by Jegelewicz** [comment]
> are they from rolled over bad duplicates?

I am guessing yes, but @dustymc can confirm. I don't think the "unknown" agent should have any associated dates....

**Comment by dustymc** [comment]
Yea, that's clearly wonky. I think that (potential bringing-over of bad data) just needs to stop, all of the old data is stashed as JSON anyway. I'll proceed under that assumption unless someone's got better ideas like NOW....

**Comment by lin-fred** [comment]
Thanks @dustymc !
