### ISSUE TITLE
agent zero media creation

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6954]
From https://github.com/ArctosDB/arctos/issues/6947

Agent unknown created ~300 media (and is shown in 1). I don't think this is necessary or useful, and it's a slight expense. 

https://arctos.database.museum/MediaSearch.cfm?action=search&agent_id=0

I'll remove these if nobody shows up with a reason to keep them in the next couple weeks.

[temp_agent0_media.csv.zip](https://github.com/ArctosDB/arctos/files/13312073/temp_agent0_media.csv.zip)

**Comment by Jegelewicz** [comment]
Also part of some name merge to unknown? Hmmmm - that seems a little problematic, or maybe it doesn't, but the original name seems like it should be associated with the media - was it?

**Comment by dustymc** [comment]
I don't know what that means. They look like legacy data (some tool required something?) to me.

**Comment by Jegelewicz** [comment]
> (some tool required something?

OK that makes sense.

**Comment by sharpphyl** [comment]
If I can tag on a related question...
We are upgrading much of our media over the next few months which entails deleting the existing media and replacing it.  I'm keeping a csv of all the deleted media IDs.  I haven't been able to delete them myself (although Arctos tells me I should).  Do I periodically send the csv to you through GitHub or can you find unused media and delete them as it seems you've done in this issue?

**Comment by dustymc** [comment]
Added to staleTempData report
