### ISSUE TITLE
Feature Request - removing "usage: citation no loan" report from the public view

### ISSUE THREAD

**Issue by ufarrell** [ArctosDB/arctos#6956]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

**Describe what you're trying to accomplish** 
_A clear and concise overview of the goals; why are you asking for this?_

Hide the report "usage: citation no loan" from public view if possible - it is not clear to a casual viewer why the alert is there, and inspires lack of confidence in the record, when in fact 'basis of illustration' specimens in our collection are some of the best understood and most complete records.

**Describe the solution you'd like**
_How might we accomplish your goals?_

Hide the report "usage: citation no loan" from public view.

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

Adding specimens to an arbitrary loan. But this takes time, and I have no more useful additional information to add to the loan record - on the contrary, it seems that it could add extra confusing information e.g. what exactly does it mean that Samuel Haughton got a data loan in 1865?

We know for sure the specimens are figured in the papers (I can compare the images, they are listed in the type catalogue)..but I have no detailed information about how the authors interacted with the specimens in the 1860s (or even in the 1980s) and I am not confident when the specimen was brought into the collection. Its possible that a pre-accession transaction would be more accurate? But chosing that would also imply more knowledge than I have. The only real certainty is that a) they are there now b) they are in a figure.

Nevertheless I understand why the report is there, and can live with the alerts and the notifications etc. - but think it is confusing for average user, especially when attempting to promote some of our nicest specimens.

**Additional context**
_Add any other context or screenshots about the feature request here._

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._

**Comment by Jegelewicz** [comment]
This seems like a perfectly reasonable request. I support it!
