### ISSUE TITLE
Arctos Down - 10 Nov about 8:30 MST

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#6957]
Please complete to the best of your ability.

## Unplanned Outage
 - Date and time (**please add time zone from which you are reporting**) outage discovered:  MST 8:30 a.m.
 - Describe the outage (Arctos down or only some part not working?):  Just churns and churns and doesn't bring up anything

## Planned Outage
 - Date and time outage will begin:
 - Date and time outage is expected to end:
 - Reason for outage:
 - Expected behavior during and after the outage:

## Communication before/during outage
- [x] Pin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG  
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [x] Unpin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by AJLinn** [comment]
offline for me too! :-(

**Comment by happiah-madson** [comment]
Me, too, at 10:53 AM EST

**Comment by Jegelewicz** [comment]
Me too 8:30 AM MST

**Comment by jtgiermakowski** [comment]
Offline for us in NM

pt., 10 lis 2023, 09:28 użytkownik Teresa Mayfield-Meyer <
***@***.***> napisał:

**Comment by campmlc** [comment]
Any idea what timeline is on outage? @dustymc

**Comment by ewommack** [comment]
Down in WY, but I am not getting an error message. The page is just taking too long to respond.

**Comment by DerekSikes** [comment]
same in Alaska

**Comment by aurianadunn** [comment]
my page is also taking to long to respond

**Comment by mkoo** [comment]
calling cavalry....

**Comment by mkoo** [comment]
Back online. Let me know if anyone has other issues today!

**Comment by AJLinn** [comment]
I'm back in again!

**Comment by dustymc** [comment]
This should be cleared up.
