### ISSUE TITLE
Arctos Down - 11/9 130 pm PT

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#6959]
## this is  Unplanned Outage
 - 11/9/2023 130 PM PT

It's in the middle of being rebooted after this morning's stuck process; thanks for your patience!

**Comment by mkoo** [comment]
completed-- Arctos is back!

**Comment by AJLinn** [comment]
I'm still getting a "503 Service Not Available" error

**Comment by sharpphyl** [comment]
I'm getting in but error message on search catalog records.
<img width="1518" alt="Screenshot 2023-11-10 at 3 22 54 PM" src="https://github.com/ArctosDB/arctos/assets/15368365/25be03e4-6bb3-4500-8741-ee6697e54715">

**Comment by AJLinn** [comment]
I'm back in again.

**Comment by mkoo** [comment]
Sorry I was hasty in closing... there have been some tweaking and subsequent rebooting... let me check in and make sure we are settled!

**Comment by mkoo** [comment]
OK Arctos is back running on the preferred rails so I really do think I can close for now!
holler if not.

**Comment by sharpphyl** [comment]
Maybe it's just my account, but while I can get agent search and taxonomy search etc. catalog search still gets this error message.  Same for enter records and browse and edit.  

<img width="1636" alt="Screenshot 2023-11-10 at 4 11 07 PM" src="https://github.com/ArctosDB/arctos/assets/15368365/ec6c6989-416c-47ee-929f-c5a494007501">

**Comment by mkoo** [comment]
Related to #6960. Asking for PG support from TACC now....

**Comment by mkoo** [comment]
BTW, clearing cache and relogging on seems to be working for me at least. (maybe just some PG gerbil needed to catch up with all the reboots) I assume since you closed the issue, Phyllis, it's working for you!

**Comment by sharpphyl** [comment]
No, it's still not working for me but I felt I had duplicated [#6960](https://github.com/ArctosDB/arctos/issues/6960) so I closed it.  Same error on half the searched and tools.  How to I clear cache at this point?  6:15 am MST
