### ISSUE TITLE
error when trying to search

### ISSUE THREAD

**Issue by aurianadunn** [ArctosDB/arctos#6960]
The error message says "The authentication type 10 is not supported. Check that you have configured the pg_hba.conf file to include the client's IP address or subnet, and that it is using an authentication scheme supported by the driver."
What does this mean? and how can I fix it?

**Comment by mkoo** [comment]
Depending on when you tried this, the database was frozen on a process that has since been addressed and all systems are now back to normal. So please try again and see if it works. If not please post or reopen this issue with details of the exact search you were trying to do. Otherwise, please close if searching works again for you
Thanks!

**Comment by acdoll** [comment]
I am getting the same error. It's essentially the same error that is keeping me out of the old reporter (see #6886). Although that issue was close, the problem remains.

**Comment by acdoll** [comment]
Some pages work (like Search Agents and the Tools Directory) but most of the important ones (especially the main search page) give this error.

**Comment by acdoll** [comment]
I'll add that this is only when I'm logged in. I can use the public interface without problem.

**Comment by mkoo** [comment]
Clearing the cache, clicking on log out and relogging on seems to have made it work for me.... try that?

**Comment by acdoll** [comment]
Tried it, but no luck.

**Comment by KatherineLAnderson** [comment]
> Tried it, but no luck.

Same here. Can see some pages (like main search page, locality search page) when I'm not logged in, but getting the error mentioned above when logged in.

**Comment by mkoo** [comment]
it's strange but can you see if this shared search works for you?
https://arctos.database.museum/search.cfm?guid_prefix=MVZ%3AHerp&taxon_name=Taricha%20rivularis

I think it's just when it passes a request (which makes sense)

**Comment by acdoll** [comment]
nope:
![image](https://github.com/ArctosDB/arctos/assets/12507297/c562f698-7fb8-4c3c-b273-1f81134d6cb9)

**Comment by acdoll** [comment]
Sorry, I was logged in still when I get that error. I can log out and get to your search results.
![image](https://github.com/ArctosDB/arctos/assets/12507297/cc6db060-b2ab-496e-9ecb-5e38202b5733)

**Comment by KatherineLAnderson** [comment]
> it's strange but can you see if this shared search works for you? https://arctos.database.museum/search.cfm?guid_prefix=MVZ%3AHerp&taxon_name=Taricha%20rivularis
> 
> I think it's just when it passes a request (which makes sense)

I can see it when I'm not logged in, but I get the same error as Andrew when logged in.

**Comment by mkoo** [comment]
Actually that is not an error-- that's the VPD but you can try with one of your own saved searches which I suspect wont trigger the error.

**Comment by dustymc** [comment]
This should be cleared up.

**Comment by acdoll** [comment]
Yes, it seems to be working for me now. Thanks
