### ISSUE TITLE
error feedback

### ISSUE THREAD

**Issue by Awkwardtree13** [ArctosDB/arctos#6961]
When I logged in to Arctos today, I got the following error: FED8FC4C-BA5D-40A7-96ECA5FBD3B7380E

The error message said "The authentication type 10 is not supported. Check that you have configured the pg_hba.conf file to include the client's IP address or subnet, and that it is using an authentication scheme supported by the driver."

Looking up what this error message said, sources indicated flushing my DNS cache should solve the issue. However, flushing my DNS cache did not solve it. 

For further context, I am a Mac user, on macOS Sonoma 14.0. I am getting this same error in both Safari and Firefox. Further, iCloud Private Relay is turned off, as I cannot connect to Arctos at all if it is on. 

Also included below are screenshots of the full error page it gave me.

<img width="1800" alt="Screenshot 2023-11-11 at 3 13 07 PM" src="https://github.com/ArctosDB/arctos/assets/103291095/b1143ee6-455a-4e84-b48c-b7994e3f8509">
<img width="1800" alt="Screenshot 2023-11-11 at 3 13 15 PM" src="https://github.com/ArctosDB/arctos/assets/103291095/df57c562-0d37-4408-9afa-9b8311a6b204">
<img width="1800" alt="Screenshot 2023-11-11 at 3 13 20 PM" src="https://github.com/ArctosDB/arctos/assets/103291095/7e34a0fb-f6c1-48ca-9da5-641cea8c96ec">

**Comment by dustymc** [comment]
This should be cleared up.
