### ISSUE TITLE
Arctos Down - 5PM Pacific TONIGHT

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6963]
I need to make what should be a very quick update. I can be flexible, please let me know ASAP if this isn't a good time.

## Planned Outage
 - Date and time outage will begin: 5PM Pacific TONIGHT 20231113
 - Date and time outage is expected to end: after 30 minutes
 - Reason for outage: security upgrade
 - Expected behavior during and after the outage: Arctos will be unavailable

## Communication before/during outage
- [x] Pin this issue
- [x] Banner updated @jegelewicz @mkoo
- [x] Email sent to AWG  
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [x] Unpin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [x] Email sent to AWG 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by ewommack** [comment]
Email sent to AWG using text from the banner.

**Comment by dustymc** [comment]
updates are complete

**Comment by ewommack** [comment]
We're happy and back?

**Comment by ewommack** [comment]
Email of return sent out
