### ISSUE TITLE
Agent Split Request - C. Thompson

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#6965]
Use this template if you believe an agent represents more than one person or organization.

**Agent that represents more than one person or organization**
Navigate to the agent page, copy the url and paste it below:

https://arctos.database.museum/info/agentActivity.cfm?agent_id=21274719

**New Agent**
Provide details that should be associated with a new agent to be split from the agent above.

https://arctos.database.museum/agents.cfm?agent_id=21254086

F. Chris Thompson (agent_id=21254086) is the entomologist so all 829 identifications for 791 UAM:Ento records by agent Chris Thompson (agent_id=21274719) who borrows bird specimens from MLZ, should be moved to agent F. Chris Thompson. 

**Reason for split**
Please provide the reason you believe that this agent represents more than one person or organization.

Chris Thompson (agent_id=21274719) is two people (1) a bird guy and (2) an entomologist. An agent already exists for the entomologist (F. Chris Thompson (agent_id=21254086)). I need help getting those 829 identifications moved to F. Chris Thompson (agent_id=21254086).

**Affected Collections**
Please list the collections that will be affected and would use the new agent. If possible provide Github usernames for those who might have an interest in the split.

MLZ:Bird
UAM:Ento

Please add this issue to the Agents Project.

@ArctosDB/agents-committee

**Comment by DerekSikes** [comment]
Something strange: when I click to find the 791 records ID'd by the wrong Chris Thompson Arctos finds record ID'd by the right one: F. Chris Thompson. Is Arctos not searching on the agent iD# but doing a name string match?? what's up?

**Comment by dustymc** [comment]
https://arctos.database.museum/agents.cfm?agent_id=21274719
 click

 [view the Agent Activity report](https://arctos.database.museum/info/agentActivity.cfm?agent_id=21274719)

click 829 identifications for[ 791 UAM:Ento](https://arctos.database.museum/search.cfm?identified_agent_id=21274719&collection_id=4) catalog records

<img width="330" alt="Screenshot 2023-11-13 at 17 20 47" src="https://github.com/ArctosDB/arctos/assets/5720791/06746a88-529f-470f-873c-6e500d905b76">

<img width="1395" alt="Screenshot 2023-11-13 at 17 21 30" src="https://github.com/ArctosDB/arctos/assets/5720791/15eeb449-2f82-40b4-8348-47ca761bb596">

done, but maybe someone can be convinced to write a howto before closing....
