### ISSUE TITLE
citation bulkloader problem

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#6967]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

Trying to load citations and getting 'insufficient information given' error

looking over this: https://arctos.database.museum/tools/BulkloadCitations.cfm?action=ld

I see that 'use_identification_id' is indicated as not needed 'no' but I recall this had been needed in the past. Perhaps this is the cause of the problem? I recall we need to put a 1 or 0 in a field to tell it to attach the citations to the current ID (this changed to some other values in later years, and now is gone??)

**Expected behavior**
Follow instructions and it works (select an id is indicated as NOT needed).

IF, however, it appears that 'yes' select an ID is needed and we need to go find the correct ID # for every record to link to?? So I'm loading 1400+ records and you want me to find the ID# of 1400 identifications and fill this out before loading in order to do what a simple 1/0 value did in the past? Not good (if true).

data:
[BulkloadCitations(7).csv](https://github.com/ArctosDB/arctos/files/13350794/BulkloadCitations.7.csv)

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.
high

**Comment by dustymc** [comment]
>'insufficient information given' 

Yep, there's nothing pointing to any identification, current or future, in these data, so no way to make a necessary link.


>use_identification_id

<img width="1514" alt="Screenshot 2023-11-14 at 07 42 23" src="https://github.com/ArctosDB/arctos/assets/5720791/4030a84a-019e-48c2-a173-d151dc8404bc">

>go find the correct ID 

<img width="288" alt="Screenshot 2023-11-14 at 07 44 09" src="https://github.com/ArctosDB/arctos/assets/5720791/4a6d6062-41ac-47f4-8e08-ebda329e4b39">

And FWIW I'm pretty sure that *all* citations are *always* identifications and would just never use this, but there it is anyway....

**Comment by DerekSikes** [comment]
I always add citations to the existing ID. Also, you need to change the 'no' to 'yes' here for https://arctos.database.museum/tools/BulkloadCitations.cfm?action=ld

use_identification_id

and why can't we go back to the simple 1/0 that was working forever? Now I have to learn a whole new way to do what worked fine before? old man grumble if it ain't broke don't fix it grumble grumble

**Comment by DerekSikes** [comment]
and please add 'use the tools->download->for citation bulkloader' to https://arctos.database.museum/tools/BulkloadCitations.cfm?action=ld

maybe best inside the explano box for use_identification_id

as a reminder to people on how to do this. I will forget, others will ask, etc.

**Comment by dustymc** [comment]
>if it ain't broke don't fix it 

A bunch of folks were saying that it WAS broke, and so we came up with a plan to fix it and then talked about that for several months! I'm always up for most anything, but I'm not really steering either.

> add 'use the tools->download->for citation bulkloader' t

Next release.
