### ISSUE TITLE
Feature Request - New transaction field: Purpose of loan

### ISSUE THREAD

**Issue by KatherineLAnderson** [ArctosDB/arctos#6968]
**Is your feature request related to a problem? Please describe.**
Currently transactions lack a "purpose" field (e.g., loan for research, education, exhibit, preparation, etc)

**Describe what you're trying to accomplish** 
This is a field in the UWBM Paleo legacy databases that we would like to retain. It allows us to track different loan purposes for reporting, measuring impact in certain areas, etc.

**Describe the solution you'd like**
New field in transactions for "Purpose of loan" (or similar), new code table with controlled vocabulary that lists various purposes: research, education, exhibit, preparation (perhaps others).

**Describe alternatives you've considered**
I'd rather not relegate it to a dreaded remarks field.

**Additional context**
n/a

@Jegelewicz @WaigePilson @ronaldeng

**Comment by dustymc** [comment]
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctloan_type might be a good (==primary and required) place for this.

Alternatively, https://github.com/ArctosDB/arctos/issues/6854

**Comment by dustymc** [comment]
@KatherineLAnderson the CT group discussed, I believe the consensus is to put these in https://arctos.database.museum/info/ctDocumentation.cfm?table=ctloan_type (in whatever form is necessary to preserve the data) with a note that they're temporary, then find a better place for them (and possibly everything else in there, excepting the one functional split) as part of https://github.com/ArctosDB/arctos/issues/6854 (which still needs refinement). @mkoo  did I get that right?

**Comment by mkoo** [comment]
Yes, Dusty outlined what we discussed. We realized when considering your request that we can really improve loan organization and searching all the various types of loans that people deal with but this will be a multi-step endeavor that will require more community discussion and a roadmap for development. We can start by accommodating your request simply as a new loan types so you can still have loans with those values and then we will work on a fully robust model with migration of the current loan types in mind. We will have this on future AWG/Issues agendas. In the end, I think this will be much more useful to the community-- thanks!

**Comment by mkoo** [comment]
whoops- hit the green button too fast.
Please confirm these are what is being requested and need to be added to https://arctos.database.museum/info/ctDocumentation.cfm?table=ctloan_type

- research 
- education 
- exhibit 
- preparation (not sure what type of loan this is?)

**Comment by KatherineLAnderson** [comment]
That all sounds great!

> whoops- hit the green button too fast. Please confirm these are what is being requested and need to be added to https://arctos.database.museum/info/ctDocumentation.cfm?table=ctloan_type
> 
>     * research
> 
>     * education
> 
>     * exhibit
> 
>     * preparation (not sure what type of loan this is?)

Yes, these are what we currently have (in addition to "other" which hardly ever gets used).
We use "preparation" for loans where specimens are sent to another institution or individual for fossil prep (removing rock matrix from specimen, etc). This could also perhaps apply to biological specimens sent for taxidermy (or other "prep")?

**Comment by mkoo** [comment]
Thanks @KatherineLAnderson Either Teresa or I can add but we also need some definitions.
Please review these and enhance (note they may/will be redundant with the other definitions so I think we should just keep generic until these are converted to something like loan "attributes" where we can select more than one):

-     research  = Loan purpose is for research or other academic study
-     education = Loan purpose is for education, such as for a class or other curricula
-     exhibit  = Loan purpose is for display, either in-house or external 
-     preparation = Loan purpose is for object preparation such as fossil preparation (i.e., removing rock matrix from specimen), biological specimen preparation (i.e., taxidermy, pinning, etc) or other specialized handling of an object that will be returned.

**Comment by AJLinn** [comment]
Oh sheesh, now you're going to make me decide whether the loan I'm sending to another museum for an exhibition is "returnable" or "exhibit"??? Or when I put something in a special exhibit in the museum I have to choose between "in house" or "exhibit"???  LOL...🤯

JK, I'm always happy to have more specific options.

Can we get to add "publication = media loan purpose for printing in a publication " also?

**Comment by Jegelewicz** [comment]
@AJLinn our plan in the future is to let you select both - but details must be hashed out....

**Comment by dustymc** [comment]
@AJLinn  for now - yea, maybe, because it lets @KatherineLAnderson move NOW without losing data.


With https://github.com/ArctosDB/arctos/issues/6854 - nope, if it's A and B and C then you'll (maybe, if someone shows up and tells me that's what's needed....) just be able to say A and B and C all at the same time.

And there's @Jegelewicz , a minute ahead of me, as always.....

**Comment by dustymc** [comment]
>Can we add "publication = media loan purpose for printing in a publication " also?

New Issue, or I suppose I'm OK with approving most anything here as long as it's understood that it's provisional (and there won't be some big fight to keep the weird stuff when we disentangle this with https://github.com/ArctosDB/arctos/issues/6854)

**Comment by KatherineLAnderson** [comment]
> Thanks @KatherineLAnderson Either Teresa or I can add but we also need some definitions. Please review these and enhance (note they may/will be redundant with the other definitions so I think we should just keep generic until these are converted to something like loan "attributes" where we can select more than one):
> 
>     * research  = Loan purpose is for research or other academic study
> 
>     * education = Loan purpose is for education, such as for a class or other curricula
> 
>     * exhibit  = Loan purpose is for display, either in-house or external
> 
>     * preparation = Loan purpose is for object preparation such as fossil preparation (i.e., removing rock matrix from specimen), biological specimen preparation (i.e., taxidermy, pinning, etc) or other specialized handling of an object that will be returned.

These definitions work on my end! No additions needed.

**Comment by Jegelewicz** [comment]
For the sake of following our own rules - I am going to set up a code table request for each term.

**Comment by Jegelewicz** [comment]
issues submitted - closing
