### ISSUE TITLE
Feature Request - New transaction role: Outside institution

### ISSUE THREAD

**Issue by KatherineLAnderson** [ArctosDB/arctos#6969]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
Loans are issued to institutions, not people, so we need an "outside institution" role for transactions (similar to "outside contact"). 

**Describe what you're trying to accomplish** 
This would track the institution the contact was a part of when the loan was issued, and should be updated at the loan recipients request when they moved institutions. Useful for legacy loans where the recipient may have retired, etc and are no longer able to be contacted. Institutions would need to be created as agents.

**Describe the solution you'd like**
New transaction role: Outside institution

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

@Jegelewicz @WaigePilson @ronaldeng

**Comment by Jegelewicz** [comment]
> I don't think this is necessary; there's nothing that would prevent using current roles for an institution nor this role for a non-institution. 

Mostly true EXCEPT when one wants to record the institution in the loan report - how do you find it among all of the contact agents?

**Comment by mkoo** [comment]
I see Dusty's point:
We already have Outside Contact as a Role which one can just select 'Museum of Vertebrate Zoology' as the outside institution/agent without a new field. Maybe what is needed in the Create Loan form is the ability to Add Row to Agents so we can add another outside contact (this is currently available only when you edit a loan). Otherwise you have to add it on the editLoan form and that would be annoying to do separately.

**Comment by dustymc** [comment]
Some roles have (hard-coded expensive and probably dicey) limitations on them (not sure if that one does or not). Probably worth a close look as roles as part of https://github.com/ArctosDB/arctos/issues/6854 - eg maybe some existing roles are better as attribute determiners or ???

**Comment by AJLinn** [comment]
Maybe I'm doing this "wrong" but I put the institution in the "Received by" line and then the person who is responsible for the loan at at that instituion as the "outside contact". Anyone else involved in the transaction is "associated with agency".

<img width="639" alt="Screenshot 2023-11-16 at 2 56 03 PM" src="https://github.com/ArctosDB/arctos/assets/17605945/8b11611d-b18c-47b1-8e38-007b6b7d3a33">

**Comment by mkoo** [comment]
@AJLinn yeah, no really 'wrong' answers here (we all do things slightly differently as long as it makes local sense and is consistent for your collection!) and I like your practise so thanks for sharing. This definitely makes sense and works with the db.

**Comment by Jegelewicz** [comment]
@KatherineLAnderson I think you now have two options using existing roles if one will work for you, documents your process and let me know which role to add to your loan form.

**Comment by KatherineLAnderson** [comment]
> @KatherineLAnderson I think you now have two options using existing roles if one will work for you, documents your process and let me know which role to add to your loan form.

Yes, I think we can run with one of these existing roles. I'll check in with Paige and Ron so we're consistent across the Burke paleo collections, and we can report back in the other thread re: loan forms. 

I'll go ahead and close this. Thanks everyone!
