### ISSUE TITLE
Connection slot error

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6970]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

Go to Find Container, get error
![image](https://github.com/ArctosDB/arctos/assets/5725767/70c11583-0a78-4149-af60-d078697d55db)

https://arctos.database.museum/findContainer.cfm

**To Reproduce**

**Expected behavior**

**Screenshots**

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by dustymc** [comment]
I'm watching this and have alerted TACC. There should be some available sessions, let me know if you have trouble getting in.

**Comment by Jegelewicz** [comment]
Just now
![image](https://github.com/ArctosDB/arctos/assets/5725767/3e8b04f6-2b30-4bd6-a4b2-ac0685fde49f)

**Comment by wellerjes** [comment]
CHAS users are also experiencing this issue.

**Comment by campmlc** [comment]
I'm still getting this error.

<html>
<body>

ERROR_ID | 6A11EAB2-83AF-41F1-9538460B5CFE7044
-- | --
ERROR_TYPE | java.io.IOException
ERROR_MESSAGE | org.postgresql.util.PSQLException: FATAL: remaining connection slots are reserved for non-replication superuser connections


</body>
</html>

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I'm getting this too.

**Comment by cjconroy** [comment]
I am trying to bulk load attributes and getting similar error. 
Chris @ MVZ


ERROR_ID | 5A05ACF5-44A9-4112-B3C0DB1A7F844494
-- | --
ERROR_TYPE | application
ERROR_MESSAGE | Error invoking external process
ERROR_DETAIL | lucee.commons.cli.CommandException: psql: error: FATAL: remaining connection slots are reserved for non-replication superuser connections

</div>
<p>request dump:</p><div id="x49tq1heWQ0-AfBHdlcDxvQ" class="-lucee-dump">
request
--
node_name | stringarctos.tacc.utexas.edu | string | arctos.tacc.utexas.edu
string | arctos.tacc.utexas.edu
rdurl | string/loaders/BulkloadAttributes.cfm | string | /loaders/BulkloadAttributes.cfm
string | /loaders/BulkloadAttributes.cfm
uuid | string5A05ACF5-44A9-4112-B3C0DB1A7F844494 | string | 5A05ACF5-44A9-4112-B3C0DB1A7F844494
string | 5A05ACF5-44A9-4112-B3C0DB1A7F844494

</td></tr><tr><td class="luceeH0" style="border: 1px solid rgb(51, 51, 153); vertical-align: top; padding: 2px; empty-cells: show; color: rgb(51, 51, 153); background-color: rgb(153, 153, 255);">Extended_Info</td><td class="luceeN0" style="border: 1px solid rgb(51, 51, 153); vertical-align: top; padding: 2px; empty-cells: show; color: rgb(51, 51, 153); background-color: rgb(204, 204, 255);"><table style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif; font-size: 11px; empty-cells: show; color: rgb(0, 0, 0); border-collapse: collapse;"><tbody><tr><td class="luceeH1" style="border: 1px solid rgb(153, 0, 0); vertical-align: top; padding: 2px; empty-cells: show; color: rgb(153, 0, 0); background-color: rgb(255, 102, 0); font-family: Verdana, Geneva, Arial, Helvetica, sans-serif; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">string</td>

**Comment by mkoo** [comment]
These should be cleared up with the reboot and tweaks in the last 24 hours
