### ISSUE TITLE
media metadata error

### ISSUE THREAD

**Issue by asemerdj** [ArctosDB/arctos#6971]
Hi there, can you please tell me what this error means and how to fix it? I have no idea where to start with it. The error code is below and I attached my csv.

ERROR_ID | 8B558A91-BB21-48BF-BC388EB6741C2A48  "remaining connection slots are reserved for non-replication superuser connections"

Thank you!
Alyssa

[bulkloadMedia_TEL_prep_log_I.csv](https://github.com/ArctosDB/arctos/files/13357884/bulkloadMedia_TEL_prep_log_I.csv)

**Comment by Jegelewicz** [comment]
Seems related to #6970

**Comment by dustymc** [comment]
I'm watching this and have alerted TACC. There should be some available sessions, let me know if you have trouble getting in.
