### ISSUE TITLE
Arctos Down - 130 central TODAY 

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6974]
Please complete to the best of your ability.

## Planned Outage
 - Date and time outage will begin: 130 TODAY (in 20 minutes!)
 - Date and time outage is expected to end: ASAP
 - Reason for outage: restart
 - Expected behavior during and after the outage: Arctos will be unavailable

## Communication before/during outage
- [x] Pin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [x] Email sent to AWG  
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [x] Unpin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [x] Email sent to AWG 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by ewommack** [comment]
Email sent

**Comment by dustymc** [comment]
@ewommack Thanks!

**Comment by dustymc** [comment]
Arctos is back up.

**Comment by ewommack** [comment]
Email sent
