### ISSUE TITLE
Error when trying to add "Verbatim Identification" attribute to an identification in Browse and Edit

### ISSUE THREAD

**Issue by genevieve-anderegg** [ArctosDB/arctos#6977]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I have records in the bulkloader that were entered by volunteers. They have identifications that list a verbatim identification that was mispelled. This information was previously entered in the identification remarks, but we can now enter it in the Verbatim Identification ID attribute. However, get an error when I try and add this attribute to an identification in a record in the bulkloader.

**To Reproduce**
1. Go to a record in the bulkloader
2. Try and add a Verbatim Identification attribute
3. Get error saying "freetext is not available, file an issue". See screenshot.

**Expected behavior**
I am able to create this attribute and have it upload with the record.

**Screenshots**
![image](https://github.com/ArctosDB/arctos/assets/83782023/921ceecd-3804-47fe-b2e0-4f6d78b76271)

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**
Windows, Chrome

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I just came here to see if this attribute had been added so that I could add it to data entry - I can report getting the same error.

**Comment by Jegelewicz** [comment]
I just loaded one of these with the bulkloader and it worked fine.

https://arctos.database.museum/guid/OGL:Genomic:22

Something weird in the data entry screen?

**Comment by genevieve-anderegg** [comment]
Thanks Dusty! Works great.
