### ISSUE TITLE
Request: please add handbook link to saveSearch management page

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#6982]
This page ```https://arctos.database.museum/saveSearch.cfm?action=manage``` could use a direct link to the relevant handbook page:
https://handbook.arctosdb.org/documentation/archive.html

The doc could be enhanced but at least we have the pages linked

**Comment by dustymc** [comment]
Done (you can do this too!)

<img width="1627" alt="Screenshot 2023-11-16 at 16 38 34" src="https://github.com/ArctosDB/arctos/assets/5720791/ddc74074-6395-4dd7-a825-99985a7f9d5d">

**Comment by mkoo** [comment]
oh I forgot! thanks!
