### ISSUE TITLE
identifiers demo

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6983]
I set up a not-so-quick demo of identifiers in test to address a request from the entity meeting yesterday. Someone please just nuke this if it's not serving to clarify the capabilities that letting issuing agents carry the heavy load reveals.

---------

First, I created a bunch of 'breeding organization' type agents - https://arctos-test.tacc.utexas.edu/agent.cfm?agent_name=studbook

<img width="573" alt="Screenshot 2023-11-17 at 08 10 33" src="https://github.com/ArctosDB/arctos/assets/5720791/1def119c-c25f-4bd7-b347-b005049d12b0">

--------------

Next I used them (as type ``identifier`` - there's no reason to complicate anything) across some records, so now an [issuedby=studbook search](https://arctos-test.tacc.utexas.edu/search.cfm?id_issuedby=studbook) finds all sorts of things, most of which aren't of interest to any one user (but still easily accessible if some unexpected use case - say, someone who wants to evaluate breeding programs - comes along).

By great coincidence these identifier values all seem to be lexical variations of ``three`` but that's OK.

<img width="1165" alt="Screenshot 2023-11-17 at 07 51 11" src="https://github.com/ArctosDB/arctos/assets/5720791/421b53e4-10f5-406d-b49e-0ad90916f17f">

-------

I need to use a [more-specific search](https://arctos-test.tacc.utexas.edu/search.cfm?id_issuedby=Jurassic%20Park) to find only my items of interest:

<img width="1100" alt="Screenshot 2023-11-17 at 07 53 03" src="https://github.com/ArctosDB/arctos/assets/5720791/a5d6b62a-9763-4736-b32d-06bcad04ceb7">

---------------

Finally, I've requested (and been approved for!) a (simulated) cache of these data - the label of which bears no particular resemblance to anything else, it's just a unique, available, postgres-object-name-safe string - which I've added to a Profile, and I've added an AKA to the issuing agent (because Agents have long been able to carry that sort of information), so I can access my data with **_my_** preferred name (even without making the agent record cryptic in any way), and I can use a Profile (which I can name using most anything that can be expressed in a few unicode characters) to make sure everyone, not just me, sees the columns I'd like them to see, even with a guest account:

https://arctos-test.tacc.utexas.edu/search.cfm?sp=🦖&id_issuedby==🦕

<img width="1718" alt="Screenshot 2023-11-17 at 08 20 00" src="https://github.com/ArctosDB/arctos/assets/5720791/97eaf4f2-9b13-4977-954a-533c9a6aeb62">

---- 

And of course my download matches my results:
<img width="675" alt="Screenshot 2023-11-17 at 08 35 06" src="https://github.com/ArctosDB/arctos/assets/5720791/243f523f-ead8-4fe0-aef4-b0713c9f1a22">

[ArctosDatak6T4tdb4GB.csv](https://github.com/ArctosDB/arctos/files/13394413/ArctosDatak6T4tdb4GB.csv)

-------------

EDIT: My column name doesn't matter because it, like all results options, can carry metadata of its own:

<img width="782" alt="Screenshot 2023-11-17 at 09 00 20" src="https://github.com/ArctosDB/arctos/assets/5720791/82edabf0-79fe-465b-9eed-fea3fcfa11f5">

---------
@campmlc @ccicero @Jegelewicz @ewommack

**Comment by Jegelewicz** [comment]
Freaking magic!
