### ISSUE TITLE
error: can't cast empty string to a number value

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#6984]
# Error Text
<html><body>

ERROR_ID | 8F48329E-5B1A-4D71-8DF8A5AD46E6E79E
-- | --
ERROR_TYPE | expression
ERROR_MESSAGE | can't cast empty string to a number value
ERROR_DETAIL |  

</div>
</body>
</html>

# Where it happened
Edit Place and Time

# Steps to get there
Edit Place and Time
Fork Edit
Change date
On Save - edit the current specimen_event

It only happens on Fork Edit, editing the collecting even does not yield the same error.

# Problem
**Community response to describe the problem that caused the error**

# Solution
**Community response with directions for how to correct the problem**

**Comment by dustymc** [comment]
@wellerjes how'd you get there? I think it's something about the specific record, or perhaps the new data - more info appreciated.

**Comment by dustymc** [comment]
maybe figured it out, fork-editing without adding coordinates

**Comment by wellerjes** [comment]
<html><body>

ERROR_ID | 9ABC865C-A2C8-4C68-91404F89D122528D
-- | --
ERROR_TYPE | expression
ERROR_MESSAGE | can't cast empty string to a number value
ERROR_DETAIL |  

</div>
</body>
</html>

Same error message, different situation. I'm trying to create a new taxonomy (classification_id:5A34DDA7-A938-4A81-A9F073D4CB122E3F) and received "can't cast empty string to a number value" again.

I also cannot delete the classification, so [Cryptonemia wilsonis](https://www.marinespecies.org/aphia.php?p=taxdetails&id=374920) does not have any metadata.

**Comment by dustymc** [comment]
I don't know what happened there, I don't think it's related to the original issue, looks like you were (somehow) trying to edit something that doesn't exist??? I went to https://arctos.database.museum/name/Cryptonemia%20wilsonis, added a classification, picked worms, gave it aphiaid, refreshed, https://arctos.database.museum/name/Cryptonemia%20wilsonis#WoRMSviaArctos looks happy??

**Comment by Jegelewicz** [comment]
I just saw a report for this from ALMNH

![image](https://github.com/ArctosDB/arctos/assets/5725767/aaa4324f-52f7-4d19-8e94-f449622fa371)

So it seems to still be an issue?

**Comment by dustymc** [comment]
>So it seems to still be an issue?

No.

**Comment by wellerjes** [comment]
> looks like you were (somehow) trying to edit something that doesn't exist???

Dunno how that happened...thanks!
