### ISSUE TITLE
Feature Request - 'Reset' button in userSQL form

### ISSUE THREAD

**Issue by camwebb** [ArctosDB/arctos#6985]
Small issue, but I spend so much time cutting and pasting SQL into the userSQL, that it would be great to have a 'Clear' button on the form: `<input type="reset" value="Clear">` 

Thanks

**Comment by dustymc** [comment]
``<input type="reset" `` .. not that straightforward (sigh...), but in next release

**Comment by camwebb** [comment]
Many thanks for adding this button. However it resets the Query to `SELECT 'test'` instead of clearing it. In order to be useful for a long session, it needs to empty the box. Reopening the issue in the hope that this is possible.

**Comment by Jegelewicz** [comment]
I have always wished that `SELECT 'test'` wasn't there. I have to delete it the first time too....

**Comment by camwebb** [comment]
@dustymc Yeah! Thank you thank you
