### ISSUE TITLE
Record event bulkload question

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6987]
I am attempting to load some record events using named collecting events and the loader is saying the spec_loc is required - but spec loc is in the locality associated with the collecting event?

data is still in the tool https://arctos.database.museum/loaders/BulkloadSpecimenEvent.cfm

**Comment by dustymc** [comment]
Ugh, that thing is kinda nightmare territory but I think I snuck a fix in, check out 30 and 31 and lemme know if I can turn it back on.

**Comment by Jegelewicz** [comment]
They look OK to me - I am going to do this for > 30K records - hope that isn't a problem!

**Comment by dustymc** [comment]
Let's find out in the most dramatic way possible - loader on!

**Comment by Jegelewicz** [comment]
I won't be doing this today, or probably next week and I can always load in small batches if that helps!

**Comment by dustymc** [comment]
I think it's all happy but it's really complicated so maybe take it a bit slow at first.
