### ISSUE TITLE
disallow closing tab on unsaved information

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ArctosDB/arctos#699]
```
if possible and not overly annoying
```

Original issue reported on code.google.com by `dust...@gmail.com` on 22 Jul 2014 at 11:11

**Comment by dustymc** [comment]
Arctos (some/most forms) has no "changed/unsaved" state marker, so this would be significant development in the current system with our current software stack. Watch for better software, implement when possible.

**Comment by Jegelewicz** [comment]
@dustymc has anything changed for this now that we are in PG?

**Comment by dustymc** [comment]
unrelated to db, more https://github.com/ArctosDB/arctos/issues/2893

**Comment by Jegelewicz** [comment]
OK -do we need DB Development and UI development projects?

**Comment by dustymc** [comment]
tabling - this would be cool, but seems to require moving to some framework or something equally unlikely.
