### ISSUE TITLE
MSB:Para Invoice Report Template Error Fix Needed

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6996]
**Description of the report** - MSB:Para Loan Invoice Detail html needs fixing to work; Ideally should include option of NK number or collector number, in that order, and verbatim host ID columns if possible. For now, however, just need the existing one to work, getting error: <html>
<body>

5B6B6DF9-6453-4541-B39EE1CB7E6C30CA
--

</body>
</html>

**Collection for which the report is needed** - MSB:Para

If this is a request to upgrade from an existing ColdFusion report in Arctos complete the following: 

**SQL used in ColdFusion report** - copy the SQl from your old report and paste it here - begin and end it with ``` or it will be invisible. Let us know if there is a prefunction to migrate.

**Priority** - High, needed asap for loan shipment

**Comment by Jegelewicz** [comment]
The error is actually

`ERROR: column flat.collection does not exist Position: 14`

I'll try to look at this soon.

**Comment by Jegelewicz** [comment]
@dustymc I am stumped - why doesn't that column exist?

![image](https://github.com/ArctosDB/arctos/assets/5725767/cfebd17c-f585-4798-8518-1efcf920c4ae)

**Comment by campmlc** [comment]
@dustymc @mkoo any way for a quick fix?

**Comment by dustymc** [comment]
>quick fix?

Not without knowing what's being requested - change that to or alias flat.guid_prefix????

**Comment by campmlc** [comment]
Can we just alter the SQL so that it will print, using the MSB:Mamm or MSB:Herp forms as a template?

**Comment by Jegelewicz** [comment]
> just alter the SQL so that it will print

I am pretty sure they have the same SQL - each of these was cloned from the original.

**Comment by Jegelewicz** [comment]
Try it now.

**Comment by mkoo** [comment]
i'm free now too so I'll test out

**Comment by Jegelewicz** [comment]
It works - just want to make sure it has everything they need.

**Comment by campmlc** [comment]
Yay - it looks great, thank everyone!!
