### ISSUE TITLE
Arctos Down (for Teresa) - Everything produces an error

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6997]
Please complete to the best of your ability.

## Unplanned Outage
 - Date and time (**please add time zone from which you are reporting**) outage discovered: 2023-11-21 9:15 AM MST
 - Describe the outage (Arctos down or only some part not working?): No matter what I am trying to do, everything produces an error and none of them are the same error.

Most recent was an attempt to log in which resulted in

<html><body>
<div style="border:2px solid green; padding: 1em; margin: 1em; text-align: center;">
            Please <a target="_blank" class="external" href="https://github.com/ArctosDB/arctos/issues/new?assignees=&amp;labels=contact&amp;template=contact-arctos.md&amp;title=error feedback">contact us</a> if you need assistance in resolving this error. Include the ERROR_ID (below) <strong>as text</strong> and enough information for us to re-create the problem.
        </div>
        
ERROR_ID | 39945B4D-819D-455F-B0C1BC96AE13FD79
-- | --
ERROR_TYPE | SQL
ERROR_MESSAGE | Column [GHADR] not found in query
ERROR_DETAIL | available columns are [C]
ERROR_SQL | select get_address (21300608,'GitHub') as ghadr

</div>
</body>
</html>Please [contact us](https://github.com/ArctosDB/arctos/issues/new?assignees=&labels=contact&template=contact-arctos.md&title=error%20feedback) if you need assistance in resolving this error. Include the ERROR_ID (below) as text and enough information for us to re-create the problem.
ERROR_ID 	39945B4D-819D-455F-B0C1BC96AE13FD79
ERROR_TYPE 	SQL
ERROR_MESSAGE 	Column [GHADR] not found in query
ERROR_DETAIL 	available columns are [C]
ERROR_SQL 	select get_address (21300608,'GitHub') as ghadr

request dump:
request
node_name	
string	arctos.tacc.utexas.edu
rdurl	
string	/form/loginformguts.cfm
uuid	
string	39945B4D-819D-455F-B0C1BC96AE13FD79

## Planned Outage
 - Date and time outage will begin:
 - Date and time outage is expected to end:
 - Reason for outage:
 - Expected behavior during and after the outage:

## Communication before/during outage
- [x] Pin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG  
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by Jegelewicz** [comment]
refresh login gets me

<html><body>

ERROR_ID | A6A08BC2-F381-4423-A5788464DB5B5065
-- | --
ERROR_TYPE | SQL
ERROR_MESSAGE | Column [CNT] not found in query
ERROR_DETAIL | available columns are [GUID_PREFIX]
ERROR_SQL | select sum(cache_public_record_count) cnt from collection

</div>
</body>
</html>

**Comment by Jegelewicz** [comment]
Same issues in Firefox and Chrome

**Comment by Jegelewicz** [comment]
Some pages will open, but the build never completes.

**Comment by mkoo** [comment]
hmm, just read your message and not getting errors now that I am resuming my hunt for verbatim agents! But let me keep trying....

**Comment by Jegelewicz** [comment]
So it is just me? I'll log out and stay out, close my browsers and try again.

**Comment by mkoo** [comment]
Maybe?  I'm on my local network (not at university) and doing stuff with tools without errors so far.... that's a weird error that implies a bad log in attempt so something stale and cached interfering? (wild guess so ignore)

**Comment by Jegelewicz** [comment]
FWIW - this all started after I loaded the attached file to the move container tool.

[OGL_missing containers.csv](https://github.com/ArctosDB/arctos/files/13430129/OGL_missing.containers.csv)

None of these moves appear to have happened.

**Comment by dustymc** [comment]
I suspect you corrupted some cache. I don't see any wide-scale problems. Give it a while or reboot lucee if it doesn't clear up.

**Comment by Jegelewicz** [comment]
It's working for me now - I'm not going to attempt the container move though.
