### ISSUE TITLE
Code Table Request - Add "width" record attribute to Invertebrate collection type

### ISSUE THREAD

**Issue by genevieve-anderegg** [ArctosDB/arctos#7001]
## Instructions

_This is a template to facilitate communication with the Arctos Code Table Committee. Submit a separate request for each relevant value. This form is appropriate for exploring how data may best be stored, for adding vocabulary, or for updating existing definitions._

_Reviewing documentation before proceeding will result in a more enjoyable experience._

* [Issue Documentation](http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html)
* [Code Table Documentation](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html)
* [Video Tutorial - Submit a Code Table Request](https://youtu.be/t2jHbsRA3lk)

------------------------------

## Initial Request
We have specimens that we have started imaging with a very high powered microscope - we now have measurements for the width of some of our specimens, and would like to enter this data into Arctos. We now have specimens that have both height and width measurements, and would like to differentiate between those in the catalog record.

### Goal
Record specimen data correctly. 

### Context
_Describe why this new value is necessary and existing values are not._
We currently have `height` and `total length` attributes, which both can describe more of a long-axis measurement, and would like to have an additional value that makes clear which value indicates the short-axis measurement. Neither of the existing values previously mentioned do that. Width is an accepted term for the measurements we are taking

Examples from the literature:
https://www.researchgate.net/profile/Ravinesh-R/publication/307755083/figure/fig3/AS:403648040456198@1473248600898/Generalised-diagram-of-a-gastropod-mollusc.png
https://peerj.com/articles/1383/#fig-1

### Table
_Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table or value. This may involve multiple tables and will control datatype for Attributes. OtherID requests require BaseURL (and example) or explanation. Please ask for assistance if unsure._
https://arctos.database.museum/info/ctDocumentation.cfm?table=CTATTRIBUTE_TYPE
https://arctos.database.museum/info/ctDocumentation.cfm?table=CTATTRIBUTE_TYPE&field=width#width

### Proposed Value
_Proposed new value. This should be clear and compatible with similar values in the relevant table and across Arctos._
free text

### Proposed Definition
_Clear, complete, non-collection-type-specific **functional** definition of the value. Avoid discipline-specific terminology if possible, include parenthetically if unavoidable._

Current is fine.

### Collection type
_Some code tables contain collection-type-specific values. ``collection_cde`` may be found from https://arctos.database.museum/home.cfm_

Invertebrate

#### Attribute data type
_If the request is for an attribute, what values will be allowed?
free-text, categorical, or number+units depending upon the attribute (TBA)_

#### Attribute controlled values
_If the values are categorical (to be controlled by a code table), add a link to the appropriate code table. If a new table or set of values is needed, please elaborate._

#### Attribute units
_if numerical values should be accompanied by units, provide a link to the appropriate units table._

length units

#### Part preservation attribute affect on "tissueness"
_if a new part preservation is requested, please add the affect it would have on "tissueness": No Influence, Allows, or Denies_

### Priority
_Please describe the urgency and/or choose a priority-label to the right. You should expect a response within two working days, and may utilize [Arctos Contacts](https://arctosdb.org/contacts/) if you feel response is lacking._

High, we have data we would currently like to enter

### Example Data
_Requests with clarifying sample data are generally much easier to understand and prioritize. Please attach or link to any representative data, in any form or format, which might help clarify the request._

### Available for Public View
_Most data are by default publicly available. Describe any necessary access restrictions._

### Helpful Actions

- [ ] Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

- [ ] Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

@ArctosDB/arctos-code-table-administrators 

## Approval
_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [ ] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [ ] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection
_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation
_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

- [ ] Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

- [ ] Add or revise the code table term/definition as described above. Ensure the URL of this Issue is included in the definition. URLs should be included *_as text_*, separated by spaced pipes. Do not include HTML in definitions.

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by Jegelewicz** [comment]
added

**Comment by genevieve-anderegg** [comment]
I think that's in record time! Thanks Teresa!

**Comment by sharpphyl** [comment]
I don't see it yet and can't access it as an attribute in single-record data entry.

<img width="640" alt="Screenshot 2023-11-26 at 3 03 32 PM" src="https://github.com/ArctosDB/arctos/assets/15368365/9406162c-828a-406b-92fe-fc8fbd59493a">

_____________

<img width="235" alt="Screenshot 2023-11-26 at 3 04 41 PM" src="https://github.com/ArctosDB/arctos/assets/15368365/0ab96c00-554b-4e23-a06d-2a4c0e5f43fa">

**Comment by Jegelewicz** [comment]
Well - I guess I didn't add it? Here is proof that I just did.

![image](https://github.com/ArctosDB/arctos/assets/5725767/d6c40abe-a2e3-44ed-aba1-9904f2da57a7)

**Comment by genevieve-anderegg** [comment]
Thanks Teresa!

**Comment by Jegelewicz** [comment]
@genevieve-anderegg @sharpphyl you guys have stuff in the bulkloader - are you done?

**Comment by genevieve-anderegg** [comment]
Arctos is behaving strangely for me and not loading the bulkloader, so I can't see

**Comment by Jegelewicz** [comment]
![image](https://github.com/ArctosDB/arctos/assets/5725767/5f751d14-d601-4d2b-a02b-4eb3742b08f1)

**Comment by genevieve-anderegg** [comment]
Just getting back to this now, and I can now see the bulkloader. Teresa if you need the bulkloader I can save the CSV and send it to Phyllis

**Comment by sharpphyl** [comment]
> @sharpphyl you guys have stuff in the bulkloader - are you done?

My apologies.  I just deleted it.  Feel free to always delete anything I leave in there for more than 5-10 minutes.
