### ISSUE TITLE
add Gloucestershire to geography

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#7004]
Please add Gloucestershire as a county in United Kingdom, England. Thanks!

https://en.wikipedia.org/wiki/Gloucestershire

**Comment by dustymc** [comment]
See https://github.com/ArctosDB/arctos/issues/6062 help is needed!

**Comment by dustymc** [comment]
See https://github.com/ArctosDB/arctos/issues/6062 help is needed!

**Comment by dustymc** [comment]
See https://github.com/ArctosDB/arctos/issues/6062 help is needed!

**Comment by dustymc** [comment]
See https://github.com/ArctosDB/arctos/issues/6062 help is needed!

**Comment by mkoo** [comment]
https://arctos.database.museum/editGeog.cfm?geog_auth_rec_id=10000970

@wellerjes does that work for you? Let me know, I'm going to close the two related "county" issues so we can go back to focusing on the larger country/ England cleanup!

**Comment by dustymc** [comment]
No particular objections about WHATEVER here, it's clearly near the intersection of a bunch of messes, but bigger-picture it still seems to me that the options are to 

1. Follow something(s, perhaps) that we can pretend is a spatial Standard, or
2. Make a big mess.

https://github.com/ArctosDB/arctos/issues/5597 should help us guide standards in ways we want to go.

**Comment by wellerjes** [comment]
My issue is addressed. Thank you!
