### ISSUE TITLE
Add East Sussex to Geography

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#7005]
Please add East Sussex as a county in United Kingdom, England. Thanks!

https://en.wikipedia.org/wiki/East_Sussex

**Comment by mkoo** [comment]
I'll take a look at #6062 but for now manually added in the GADM4.1 East Sussex poly as adm2
(note to self: only the WKT export had no errors-- how can I get geojson files to work?)

@wellerjes does this work for you? https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10000968

**Comment by wellerjes** [comment]
Yes, thank you!
