### ISSUE TITLE
Code Table clean up: Lower Jurasssic

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7007]
Doesn't seem worth posting an issue so I'll put it here: Lower Jurassic is misspelled with an extra "s" in the Series/Epoch attribute value code table!

_Originally posted by @KatherineLAnderson in https://github.com/ArctosDB/data-migration/issues/1534#issuecomment-1825963250_

Totally worth an issue. I can make the correct spelling, but we will probably need @dustymc to clean it all up.

**Comment by Jegelewicz** [comment]
also made the metadata relationships for the new term

**Comment by Jegelewicz** [comment]
I corrected usage in the affected localities - waiting for flat to catch up.

**Comment by KatherineLAnderson** [comment]
thanks Teresa!!

**Comment by Jegelewicz** [comment]
@dustymc can you please delete the misspelled Lower Jurasssic?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
The metadata for related values in chronostrat also need to be corrected, for example Jurassic currently has metadata "includes: Lower Jurasssic", I think the chronostrat hierarchical search runs on those values.

**Comment by Jegelewicz** [comment]
Thanks - I'll get those later today!

**Comment by dustymc** [comment]
done
