### ISSUE TITLE
Feature Request - add 1 identification form

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#7009]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

Couple issues:

1) How do I find any records in my collections that have more than one identification with an ID order of 1. I don't want any such records but I fear they will accumulate by accident since the add-one-new-identification tool has not been updated to prevent this from happening (next item).

2) There are 2 important UI inconsistencies between the change-bulk records ID tool and the change-one record ID tool. First, the identifier agent is in line with the fields in the bulk tool and off to the right for the change-one record too. They should made consistent.

The other problem is that with the bulk change ID tool the complexities of the ID orders has been hidden from those who don't want those complexities but the change-one ID tool has not had these complexities hidden. Thus, when an operator adds a new ID using the change-one tool the operator has to remember to find the prior ID with ID order =1 and change that to zero. If the operator forgets to do this, as many will no doubt do, then the record ends up with two IDs of ID order =1.

So, again, what's the sql to find such records if they exist, and can we get the change-one record tool fixed so when a new ID is added, all prior IDs have their ID order set to 0 by default (with an option to change that if anyone wants to).

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._
medium

**Comment by dustymc** [comment]
Requested SQL:

```
select guid from flat
inner join identification on flat.collection_object_id=identification.collection_object_id
where
flat.guid_prefix='UAM:Ento' and
identification.identification_order > 0
group by guid
having count(*) > 1
```

**Comment by DerekSikes** [comment]
Thanks. As feared, there are 13 such records: UAM:Ento:26237,UAM:Ento:367054,UAM:Ento:377481,UAM:Ento:26558,UAM:Ento:84079,UAM:Ento:210300,UAM:Ento:480251,UAM:Ento:27576,UAM:Ento:482807,UAM:Ento:19916,UAM:Ento:106175,UAM:Ento:27441,UAM:Ento:70870

I will now go and one at a time edit them to turn one of the identifications to order 0. Can that form be fixed to prevent this from happening accidentally?

**Comment by Jegelewicz** [comment]
The two things requested above seem to be easy?

For context though, here is the "bulk tool"
![image](https://github.com/ArctosDB/arctos/assets/5725767/9fa84e01-3bec-4708-b6d1-eecddf14fa1c)

and here is the single record identification tool
![image](https://github.com/ArctosDB/arctos/assets/5725767/beab0dff-13b5-4cde-b4ae-faf6c4a0156b)

1. Addressing `the identifier agent is in line with the fields in the bulk tool and off to the right for the change-one record too. They should made consistent.` seems simple enough if we know which is preferred (or maybe no one cares as long as they look the same?) And just to be crazy - maybe these should look exactly the same, including the number of identifiers and attributes offered?
2. Addressing `with the bulk change ID tool the complexities of the ID orders has been hidden from those who don't want those complexities but the change-one ID tool has not had these complexities hidden` seems like simply adding the `Existing Identification Order:` thingee to the single record editor would do the trick?

![image](https://github.com/ArctosDB/arctos/assets/5725767/1b91a170-a4a2-426e-90c0-024c5d3757b3)

@DerekSikes is that what you are looking for?

**Comment by DerekSikes** [comment]
Yes, I prefer the agents to be in line rather than off to the right (because I use the bulk-change tool 99% of the time this is how I've gotten used to it). The bulk-change tool has an excellent UI in having only 1 field for agent name and a tiny 'more' link to allow folks to expand to add more agents if desired. If that could be replicated for the change-1 tool it would be best.

& re: #2, yes.

**Comment by dustymc** [comment]
Thanks @Jegelewicz I will try to get this rolling again.

(1) is complex for a few reasons - the in-record tool is responsive, things are wherever your browser decides to put them, while the other tool has a bunch of not-identification junk hanging around and hasn't been (and probably won't be) refactored to be responsive. Additionally, https://github.com/ArctosDB/arctos/issues/6684 may change the shape of the record editor. I think that should be split off to become actionable. (And maybe https://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html should say something about focus? I get lost if too many things are going on....)

----------
For (2): @sharpphyl and @genevieve-anderegg I think you're the primary users of the capability (but ~50 collections are using this, everyone's input is appreciated!), would a default behavior of changing all identifications to order=0 when adding an identification be acceptable?

**Comment by genevieve-anderegg** [comment]
I think that would be fine for us, we don't not use the bulk identification tool that often. A user would just have to remember to switch that drop down to the preferred identification order. It seems like when someone would bulk add identifications it would be most likely that they would add them at order=1 than at order=0 (say, due to specimens being identified on loan by an expert and the records being updated to a more current/correct ID), but to avoid the multiple order=1 identifications that Derek is worried about that would work. I think it's not an issue because we would recognize the meaning of the drop down and know what to change it to for our desired result

**Comment by dustymc** [comment]
This is NOT for the bulk tool (which has had this behavior for a while, screenshot above). This is a request to update the guid-page UI eg https://arctos.database.museum/guid/DMNS:Inv:39122 then click <img width="171" alt="Screenshot 2024-01-11 at 10 03 33" src="https://github.com/ArctosDB/arctos/assets/5720791/01f77c1a-3bf4-48bc-9122-b8e1156ba462"> to get 
<img width="1458" alt="Screenshot 2024-01-11 at 10 01 04" src="https://github.com/ArctosDB/arctos/assets/5720791/d808802c-35f7-4847-8cd5-06c7c91b5890">

so an INSERT (using the form in the screenshot) would by default ZERO everything in the " Edit an Existing Determination Documentation " section - which might be dozens of IDs for some well-studied record (eg https://arctosdb.org/learn/gold-standard-records/)

**Comment by genevieve-anderegg** [comment]
Ah my bad, I understand now - yeah we would know to switch the drop down! Maybe if you make the form so that it prompts you to check the drop down before you save?

**Comment by DerekSikes** [comment]
I ask that the form not prompt one to check the drop down before saving (also doubt this is possible, how will the form know you are about to save?)

**Comment by genevieve-anderegg** [comment]
Maybe the box is highlighted in red with a little text box next to it that says "remember to double check the identification order setting"?

**Comment by DerekSikes** [comment]
I'll reiterate that this new multi-order ID system should be opt-in, not opt-out. Those who want to use it (which I suspect are a small %) should have to do the extra clicking. Those who want to keep doing things the old way shouldn't have to do any extra clicking to do so.

**Comment by Jegelewicz** [comment]
@DerekSikes the box could be preset to "reset to 0" just like it is in the bulk change form. So if you do nothing - all existing identifications are set to 0, but you can use the box to change all existing IDs to 2 or whatever.

@genevieve-anderegg OK? Especially of the from looks like the bulk change form BIG RED LETTERS that warn you something is happening....

**Comment by DerekSikes** [comment]
and me!

**Comment by DerekSikes** [comment]
Almost...done, the drop-down menu for the newly made ID should be pre-set to = 1, as was requested and as is the case for the change-many ID form.

**Comment by DerekSikes** [comment]
Almost...done, the drop-down menu for the newly made ID should be pre-set to = 1, as was requested and as is the case for the change-many ID form.
