### ISSUE TITLE
Need Help with Arctos Error

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#7011]
# Error Text
<html><body>

ERROR_ID | 230DE097-7E66-4CB4-93D4BB5875157647
-- | --
ERROR_TYPE | expression
ERROR_MESSAGE | the value from key [VALUE_CODE_TABLE]  is NULL, which is the same as not existing in CFML
ERROR_DETAIL |  

</div>
</body>
</html>

# Where it happened
I tried to add a verbatim identification attribute to https://arctos.database.museum/guid/CHAS:Herb:1878.17.214, the value is represented as "id_attribute_value_16034175_new1" and when I got into identifications, I see the above error.

I can't delete the attribute or the identification--I tried creating a new one so I could delete the old one with the verbatim identification attribute and got this error:
<html><body>

ERROR_ID | 8804F3F5-0177-4403-943490739BC09DE6
-- | --
ERROR_TYPE | expression
ERROR_MESSAGE | variable [CITATION_ID] doesn't exist
ERROR_DETAIL |  

</body>
</html>

# Steps to get there
Identification - Edit - Attributes

# Problem
**Community response to describe the problem that caused the error**

# Solution
**Community response with directions for how to correct the problem**

**Comment by Jegelewicz** [comment]
It looks like it was added just fine, but the error still needs to be figured out. The second error mentions a citation ID - and I don't see any citations on the record - so maybe that is a clue. 

![image](https://github.com/ArctosDB/arctos/assets/5725767/8e63c0c9-0099-42ac-b174-dc3e4a27b4ab)
