### ISSUE TITLE
cannot insert "no higher geography recorded"

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#7012]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I am trying to edit a record already entered into Arctos. It's higher geography is currently set to "United States" and I'm trying to change it to "no higher geography recorded", but when I try to pick geography, it does not show it as an option.

**To Reproduce**
1. https://arctos.database.museum/guid/CHAS:Herb:1903.1907.15
2. click on edit place and time, then edit locality
3. click on change for this locality
4. search [69 in "geo auth rec id"](https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=69)
5. no results
I've been using this method because typing "no higher geography recorded" into the higher geography field does not yield any results either.

**Expected behavior**
Arctos pulls "no higher geography recorded" as an option to pick

**Screenshots**
![image](https://github.com/ArctosDB/arctos/assets/93737929/c406ad25-4b8f-4562-83c3-6edea2541126)

**Data**
n/a

**Desktop (please complete the following information):**
Firefox

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by Jegelewicz** [comment]
Did you delete the locality? I cannot find locality 12131173!

**Comment by dustymc** [comment]
<img width="226" alt="Screenshot 2023-12-02 at 07 04 57" src="https://github.com/ArctosDB/arctos/assets/5720791/727ac81d-768c-4505-aa39-572b7207a313">
