### ISSUE TITLE
Arctos Down - 

### ISSUE THREAD

**Issue by COwildlife** [ArctosDB/arctos#7016]
Unplanned Outage
 - 14:00 MST 12/04/23
 - Server is down, unable to access any .database.museum urls

**Comment by Jegelewicz** [comment]
It is working for me in Albuquerque

**Comment by ewommack** [comment]
I've got it working here in WY. How are you doing @COwildlife?

**Comment by COwildlife** [comment]
Still down for me in Northern Colorado at 21:30

**Comment by AJLinn** [comment]
Working okay for me in AK, same time. What browser are you using @COwildlife ?
