### ISSUE TITLE
Feature Request - add more than one type to a permit

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7017]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

OGL has permits that are import/export, CITES/collection and import, collection/export but we can only select ONE value for permit type when entering a permit.

**Describe what you're trying to accomplish** 
_A clear and concise overview of the goals; why are you asking for this?_

Allow them to find all of the export permits or all of their import permits or all that allow for both.

**Describe the solution you'd like**
_How might we accomplish your goals?_

The ability to select more than one permit type.

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

pick one and put the rest in remarks

**Additional context**
_Add any other context or screenshots about the feature request here._

Maybe we need permit attributes and type is one of them.....

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._

**Comment by ewommack** [comment]
This would be super helpful for vertebrates. We have a number of permits that are collect and salvage, or band and salvage. I always add the second thing in the comments, but I could see how that might be confusing for people.

**Comment by dustymc** [comment]
This has been available for several years????

**Comment by Jegelewicz** [comment]
OK - I was trying to put together a "bulkload" of permits for OGL - without looking at edit permit, that is not obvious since the single permit create form only has one...

**Comment by ewommack** [comment]
> that is not obvious since the single permit create form only has one...

Yes that thing!

Sorry @dustymc you're right, we can edit and add more things to permits. But you have to pick one when you first create the permit.
