### ISSUE TITLE
specimen search page layout

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ArctosDB/arctos#702]
```
1) Make sure TrySomethingRandom does not overlap header (css-force resize 
header image?)
2) Make collection pick list bigger (ongoing usability issue with select 
multiple)
3) Override browsers hiding scroll bars in select multiple (possible??)
4) Dynamically resize "pane components" to grow, eg, make collection select 
bigger when "use big catalog numbers" is on.

(Ref:  Mon, Aug 4, 2014 at 2:58 PM email from DSS)
```

Original issue reported on code.google.com by `dust...@gmail.com` on 7 Aug 2014 at 4:22

**Comment by dustymc** [comment]
See also #824

Throwing this back to needs discussion; seems there some desire for a complete redesign or ???

**Comment by Jegelewicz** [comment]
This is how the main search page appears to me when not signed in using Firefox at 100% zoom on my ASUS laptop with Windows10.

![image](https://user-images.githubusercontent.com/5725767/52651373-4ac0a280-2ea9-11e9-886c-bf8c6fec5279.png)

There is a lot of wasted white space and the upgraded "Try Something Random" box falls off the screen.

For comparison, here is MCZBase on a new tab of the same browser.

![image](https://user-images.githubusercontent.com/5725767/52651154-e7367500-2ea8-11e9-88d8-1f1a7130c4a0.png)

Any chance we can take Harvard's skin for our own purposes? Perhaps with the modification/addition of the "Try Something Random"? Do we need "Try Something Random"? As much as it appeals to the squirrel chaser in me, I am not sure many people use it and it takes up valuable screen space.

**Comment by dustymc** [comment]
I use the random widget a LOT and would not be happy to see it go. There's a link to hide it if it's distracting.

I doubt if we can just lift MCZ's "skin" but yea, we can always use layout improvements. I'll take a look when I can if nobody else wants to volunteer....

**Comment by campmlc** [comment]
We've had other external users comment that MCZ's page is so much easier to
use. I do think it is worth investing the time into making improvements on
the search page. We can always click to see more options. Why not do that
with try something random?
As someone who has to do all my work on a 12" laptop (ditto for all my
students), I agree that we need to design interface displays with smaller
screens in mind.
