### ISSUE TITLE
Add common names for OGL

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7021]
OGL has  many common names that we would like to add to Arctos taxonomy as they were included in their previous database. Here is a file - can we get these added? (some may be duplicates - I have no easy way to check).

[OGL.Common_names.csv](https://github.com/ArctosDB/arctos/files/13590663/OGL.Common_names.csv)

**Comment by dustymc** [comment]
I can add them, but they will be ambiguous and I very strongly suspect that model has a limited life expectancy (because it's ambiguous). Adding these to the relevant classifications will result in better data and avoid a probably-inevitable future cleanup.

**Comment by Jegelewicz** [comment]
Can we do this? I don't foresee a change to the way we handle common names anytime soon and I'd like to check this off the data migration box.

**Comment by dustymc** [comment]
Done, except for these which have something wonky in them.

```

        common_name        
---------------------------
 Camaron 
 Rock Crab 
 Short-finned Pilot Whale 
 Fin Whale 
 Blue Whale 
 Golden Gregory 
 Black-fish 
 Sea anemone 
 Ringed doris 
 dispar anthias 
 Pacific Jack Mackerel 
 Northern kingfish 
 Bottlenose Dolphin 
(13 rows)
```

**Comment by Jegelewicz** [comment]
Handled the following:

Camaron 
 Rock Crab 
 Short-finned Pilot Whale 
 Fin Whale 
 Blue Whale 
 Golden Gregory 
 Black-fish 
 Sea anemone 
 Ringed doris 
 dispar anthias 
 Pacific Jack Mackerel 
 Northern kingfish 
 Bottlenose Dolphin
