### ISSUE TITLE
WoRMS relationships update

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7022]
It appears that relationships between names that are recorded in WoRMS were added to Arctos - possibly when we first ingested WoRMS data? Are these updated on a schedule? Not at all? Could we update them annually? If that is too often, how often makes sense?

**Comment by dustymc** [comment]
Our core relationship model is incorrect (it implies https://arctos.database.museum/name/Iron#NomenclatureviaArctos - laundry equipment - has something to do with https://arctos.database.museum/name/Epeorus- which might itself be ambiguous). WoRMs handles this better by putting relationship data in the classifications - eg https://arctos.database.museum/name/Conus%20abbas%20euetrios#WoRMSviaArctos -- valid_name: Conus archiepiscopus

**Comment by Jegelewicz** [comment]
I think I have been saying this for a long time - but making the change is not going to be simple.....

and then, aren't we just asking people to pick a classification instead of a name?

**Comment by genevieve-anderegg** [comment]
I add relationships between names occasionally by hand- like while I'm incorporating the name spelling changes Dusty prepared for us in #4268

**Comment by Jegelewicz** [comment]
@genevieve-anderegg that is fine and what I have been doing - but what it tells me is that Arctos is not making a systematic effort to keep relationships as recorded at WoRMS up-to date. I think we could do this - even if it was annually, but we need a procedure and agreement that this is something worthwhile to the community at large.

**Comment by Jegelewicz** [comment]
Added to the agenda at the Taxonomy Committee Meeting today.

@sharpphyl @genevieve-anderegg say it isn't affecting them in their daily work. All of us drop the ball adding names and their associated synonyms. Closing because this seems like too much work for the benefit at this point.

Closing for now - they will open a new issue for what they really need.
