### ISSUE TITLE
Code Table Request - new taxonomy source: United States Endangered Species

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7023]
### Goal
_Describe what you're trying to accomplish. This is the only necessary step to start this process. The Committee is available to assist with all other steps. Please clearly indicate any uncertainty or desired guidance if you proceed beyond this step._

Provide information about the federal status of taxa.

### Context
_Describe why this new value is necessary and existing values are not._

As our current system seems to have failed, perhaps we can use the Federal ESA list:

https://www.ecfr.gov/current/title-50/chapter-I/subchapter-B/part-17/subpart-B/section-17.11#p-17.11(h)

to populate a taxonomy source as we recently did with IDNR status

See the developer tools on the site - can we download and transform (pretty sure I could use the HTML option to do this, but it would be clunky)? Get directly (that would be amazing)?

If we do this - we could update annually as the published CFR is updated annually. Just need a reminder.

### Table
_Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table or value. This may involve multiple tables and will control datatype for Attributes. OtherID requests require BaseURL (and example) or explanation. Please ask for assistance if unsure._

https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxonomy_source

### Proposed Value
_Proposed new value. This should be clear and compatible with similar values in the relevant table and across Arctos._

United States Endangered Species

### Proposed Definition
_Clear, complete, non-collection-type-specific **functional** definition of the value. Avoid discipline-specific terminology if possible, include parenthetically if unavoidable._

Records the endangered/threatened status of species as listed by the United States. This source is expected to only include non-classification terms and must be manually updated each time “List of Endangered and Threatened Wildlife” is updated. This source is managed by the Arctos Taxonomy Committee. 

### Collection type
_Some code tables contain collection-type-specific values. ``collection_cde`` may be found from https://arctos.database.museum/home.cfm_

N/A

#### Attribute data type
_If the request is for an attribute, what values will be allowed?
free-text, categorical, or number+units depending upon the attribute (TBA)_

N/A

#### Attribute controlled values
_If the values are categorical (to be controlled by a code table), add a link to the appropriate code table. If a new table or set of values is needed, please elaborate._

N/A

#### Attribute units
_if numerical values should be accompanied by units, provide a link to the appropriate units table._

N/A

#### Part preservation attribute affect on "tissueness"
_if a new part preservation is requested, please add the affect it would have on "tissueness": No Influence, Allows, or Denies_

N/A

### Priority
_Please describe the urgency and/or choose a priority-label to the right. You should expect a response within two working days, and may utilize [Arctos Contacts](https://arctosdb.org/contacts/) if you feel response is lacking._

Setting as high - OGL has been using this already and all biological collections could benefit.

### Example Data
_Requests with clarifying sample data are generally much easier to understand and prioritize. Please attach or link to any representative data, in any form or format, which might help clarify the request._

### Available for Public View
_Most data are by default publicly available. Describe any necessary access restrictions._

### Helpful Actions

- [ ] Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

- [ ] Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

@ArctosDB/arctos-code-table-administrators 

## Approval
_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection
_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation
_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

- [x] Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

- [x] Add or revise the code table term/definition as described above. Ensure the URL of this Issue is included in the definition. URLs should be included *_as text_*, separated by spaced pipes. Do not include HTML in definitions.

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
This seems like a good proposal. I am checking a box.

**Comment by dustymc** [comment]
The source is acceptable, checking boxes.

Any extra work from "we" needs addressed separately. (Tell them to send data to GlobalNames!)

**Comment by Jegelewicz** [comment]
I can create this source, but getting the information to populate it will be difficult

https://www.ecfr.gov/current/title-50/chapter-I/subchapter-B/part-17/subpart-B/section-17.11#p-17.11(h)

is pretty much useless as a transformation from HTML or PDF results in merged cells all over the place. Ideas appreciated.

![image](https://github.com/ArctosDB/arctos/assets/5725767/a766ee3d-dab0-4a55-96e6-b78d4f5e9942)

![image](https://github.com/ArctosDB/arctos/assets/5725767/72059678-3fc3-44f8-8878-338b3922b170)

**Comment by Jegelewicz** [comment]
and sometimes repetitive rows

![image](https://github.com/ArctosDB/arctos/assets/5725767/82b77553-fdcd-4230-b4da-8bc7fe3329c8)

**Comment by campmlc** [comment]
I would not have thought to look at the CFR for this. 
https://ecos.fws.gov/ecp0/reports/ad-hoc-species-report?kingdom=V&kingdom=I&status=E&status=T&status=EmE&status=EmT&status=EXPE&status=EXPN&status=SAE&status=SAT&mapstatus=3&fcrithab=on&fstatus=on&fspecrule=on&finvpop=on&fgroup=on&header=Listed+Animals

**Comment by campmlc** [comment]
Besides, that's not US only. That's probably IUCN redlist or something.

**Comment by Jegelewicz** [comment]
@campmlc thanks but even that resource has 

![image](https://github.com/ArctosDB/arctos/assets/5725767/fef35f8f-61b4-43dc-a090-bfff72dad5e9)

why is all of this important information in such a terrible format?

**Comment by Jegelewicz** [comment]
The list provided at https://ecos.fws.gov/ecp0/reports/ad-hoc-species-report?kingdom=V&kingdom=I&status=E&status=T&status=EmE&status=EmT&status=EXPE&status=EXPN&status=SAE&status=SAT&mapstatus=3&fcrithab=on&fstatus=on&fspecrule=on&finvpop=on&fgroup=on&header=Listed+Animals
is also not US only...

![image](https://github.com/ArctosDB/arctos/assets/5725767/54dbc46f-32eb-4aef-979d-cd0d2bd7a883)

I actually think they are the same list, but they do seem to have a slightly different number of rows.

**Comment by campmlc** [comment]
We should ask @ccicero. I would trust USFWS on this before I trusted the US code of federal regulations. Certainly USFWS is whom I have to deal with for permits and import/export. The USFWS list is also available as csv download.

**Comment by Jegelewicz** [comment]
OK. using the USFW list and checking for names in Arctos.

[USFW Listed Animals.csv](https://github.com/ArctosDB/arctos/files/14924490/USFW.Listed.Animals.csv)

**Comment by Jegelewicz** [comment]
names not found were added

**Comment by Jegelewicz** [comment]
This list adds a row for each status, so I did some manual manipulation to get a list of unique names with multiple statuses. I probably should have turned to R, but I don't have time now to relearn it.

Here is the file I worked on
[USFW Listed Animals.xlsx](https://github.com/user-attachments/files/16354680/USFW.Listed.Animals.xlsx)

**Comment by Jegelewicz** [comment]
Boxes are checked and the term has been added

**Comment by Jegelewicz** [comment]
I tried to load new classifications, but I am unable to add a no_class_term_type that isn't in the code table (I thought the code table was just a suggestion?) If a new term  must be added, I can file a code table issue.

@dustymc please advise

**Comment by dustymc** [comment]
>advise

Data please.

**Comment by Jegelewicz** [comment]
[USFW Listed Animals.csv](https://github.com/user-attachments/files/16363565/USFW.Listed.Animals.csv)

**Comment by dustymc** [comment]
Assuming you're seeing the same error I'm seeing in test, there's nonprinting text (trailing whitespace, at least) in noclass_term_type_2.

**Comment by Jegelewicz** [comment]
DOH - thanks

**Comment by Jegelewicz** [comment]
The classifications are in the loader. So the source exists, but right now it isn't DOING anything.

File used to load classifications
[USFW Listed Animals.csv](https://github.com/user-attachments/files/16363899/USFW.Listed.Animals.csv)

**Comment by Jegelewicz** [comment]
If anyone wants some functionality from this source, they can request it.
