### ISSUE TITLE
Request: add field for issued_by and identifier on loan review form

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#7025]
@dustymc  See below: Mariel needs the option of not including or sorting the field for issued_by separately from the type value so a new field needs to be added that displays just the issued_by and the identifier field can display just the value

This is an example from the identifier download tool which would satisfy the loan review form needs where Issued By, Id Type and Display are in separate fields:

![Firefox_Screenshot_2023-12-08T19-27-38 403Z](https://github.com/ArctosDB/arctos/assets/2523089/c4f31711-87cb-4413-9d84-18e801e67a01)

Original post:

This request is to mitigate the changes that have occurred since identifiers have been assigned issued by values. While it may be necessary to display this information, previous forms and tools are affected, including the following. I need my preferred NK identifier to show up in its own column as a numeric value, not mingled with an automated insertion of "issued by" agent.  The current display format requires multiple steps to remove this information from the download so that the values can sort numerically.
This request is to move "issued by" in all cases and tools to a separate column from the ID value.

![Screenshot 2023-12-06 15 28 23](https://github.com/ArctosDB/arctos/assets/14808196/f76cad44-00c5-4c93-b65e-b650ca576b93)

**Comment by campmlc** [comment]
Our institutional loan report template is also affected. Please remove the autoconcatenation of these fields so that we can choose whether or to not include them in the report SQL. The current status is a disincentive to adding the issued by agent to the identifier, to avoid these kinds of problems.

[2023.14.Bird Loan Invoice.pdf](https://github.com/ArctosDB/arctos/files/13592696/2023.14.Bird.Loan.Invoice.pdf)

**Comment by mkoo** [comment]
Hi Mariel, I'm confused here-- is this issue about a loan report or the identifier download tool?
If you want to only have the numeric show up on the loan report then we can request a little sql help and have that displayed. BUT since you seem to have inconsistent data it's difficult to come up with a solution. the other seems to be an interface issue (I think) and again the inconsistency in your data makes it difficult to address. Let me know if you want me to split the issue to appropriate tasks

**Comment by Jegelewicz** [comment]
@campmlc For NKs - you should not add an issued by. The NK "type" is holding that information.

**Comment by mkoo** [comment]
> The problem is the automatic concatenation of these values for display in all tools and reports.

There is no "automatic concatenation" -- you have control to display what and how you want in the reports and labels. Sometimes it's easiest with SQL, sometimes it's HTML/CSS. Let's open an issue for the report that you want addressed and we can update it. 

Same with tools. Ultimately though it is in consistency of data entry that will get you consistent results.This may be better as a technical zoom call if it's more complicated than that and I am misunderstanding

**Comment by campmlc** [comment]
So I don't have control over tools display - that is what I was requesting to be changed. I am asking that the issued by agent be in a separate column from the ID value in all tools, so that the ID value can be sorted and displayed numerically, and so that the interface is manageable. This is the same request that was made and granted on our search results flat file.  Same concern.

**Comment by mkoo** [comment]
ok leaving aside that you do have inconsistent data (see your screenshot) I think this is still 2 issues: let me rename this one to address the loan review form versus the report.

**Comment by dustymc** [comment]
>has nothing to do with data consistency

This is entirely a matter of data consistency, or possibly I'm just lost.

The retained types (such as NK) don't need issued by, and adding it (as has been done here) just causes - well, scroll up!

Doing what I believe has been requested would make data less accessible for collections using agent-based identifiers, and would run into issues of cardinality when multiple identifiers are involved.

Consistent entry will fix this problem and not cause others.

**Comment by mkoo** [comment]
@dustymc @Jegelewicz  yea we can do it that way too-- make the data consistent. 

@campmlc Do we have your permission to change the Issued_by value for all NK numbers to be just NK? That seems like a good workaround for now (and compromise!) I would swap out that existing Issuer to "NK" https://arctos.database.museum/agents.cfm?agent_id=21350608

Then your loanitemreview form would show NK XXXXXX

My request to have the loanitemreview.cfm to match the fields of the "identifier download tool " (see the initial issue edits from me) still stands though, it just would be backburnered and maybe not needed....

**Comment by dustymc** [comment]
>swap out that existing Issuer to

I still recommend NULL - issuer is just an extra complication for these internal/local identifiers.

>match the fields of the "identifier download tool "

That's where the aforementioned cardinality would come into play. That tool is one identifier per row so the bits always stay structurally associated. This form can involve any number of identifiers, and I believe what's being proposed would irreversibly disassociate their components - it'd make the data ambiguous.

**Comment by campmlc** [comment]
I honestly don't understand why we can have these fields separate in search results download but not anywhere else? If I change my preferred identifier to collector number or Albuquerque Biopark Local ID I will have exactly the same problem. This is a simple request that would actually make it much easier for us to move forward with updating our identifiers to the new model. I agreed to work towards that goal only under the conditions that user interface issues related to this conversion would be prioritized. I'm not seeing that. 
You have my permission to get rid of the issued by agent here, as that would fix this particular 
use case.  There are only a few from one recent accession, and I didn't catalog them-  it was done by our Bird division.  I have no control over it not happening again in the future. It is actually useful to have this information in this case, although I'd rather say they were issued by MSB: Bird. If my very simple request were granted, so that these forms view and download in the same consistent format that search results view and download with separate volume for ID value and ID issued by, then I would have no problem moving forward with converting our other identifiers to make them consistent. But the response I am getting just makes me more convinced that the needs of my institution and the needs of users in general are not being understood and addressed, and we are at an impasse.

**Comment by campmlc** [comment]
@jldunnum @AdrienneRaniszewski @jtgiermakowski

**Comment by mkoo** [comment]
Let's take it down a notch please! If it was simple it would be done -- that's why I split this issue. See #7042 which is pretty much resolved just needs testing and finalizing. And I'm using your institution's requested report for MSB:Herp as the solution!

The  loanitemreview form is more complex so cannot be just messed around with without considerations

**Comment by mkoo** [comment]
I see one piece of actionable info-- we can remove the long Issued_by string. 

For the future: 
Would it be helpful/ less confusing to future data entry to have the "NK" available for Issued_by. Proper training and communication of best practice are still necessary as all things in the museum curation world are....

Let me get some help and email you directly for implementation Mariel

**Comment by dustymc** [comment]
> You have my permission to get rid of the issued by agent here, as that would fix this particular

[temp_ib_nk.csv.zip](https://github.com/ArctosDB/arctos/files/13622278/temp_ib_nk.csv.zip)

``UPDATE 418``

Done.

>no control over it not happening again 

File an Issue, that's solvable.

>"NK" available for Issued_by

That's more scalable/sustainable/powerful, but I think type-only is OK too - anything consistent can probably be made to work.

**Comment by dustymc** [comment]
This is as addressed as the state of the data allows.
