### ISSUE TITLE
instant encumbrances

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ArctosDB/arctos#703]
```
from ABJ: Is there a way to encumber a record in the bulkloader? I ask because 
with Arctos talking to Vertnet, etc, it seems that there's a possibility that a 
program like Vertnet could get the records that are meant to be encumbered 
between the time they exit the bulkloader and the time that the collection 
staff is able to get them encumbered.
```

Original issue reported on code.google.com by `dust...@gmail.com` on 9 Sep 2014 at 9:03

**Comment by dustymc** [comment]
What would trigger this action?

**Comment by Jegelewicz** [comment]
If the encumbrance is created before cataloging, this shouldn't be too difficult? Just add a filed to data entry/bulkload (I know...) for the name of the encumbrance? Which also makes me wonder if we don't need some sort of visible numbering system for encumbrances so that no one would have to enter "Mask part locations for Paleo".

**Comment by campmlc** [comment]
I like it - we definitely need Ids for encumbrances.

**Comment by Jegelewicz** [comment]
As this has been a recent ask - adding to community discussion.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/5193

**Comment by Jegelewicz** [comment]
> MAYBE:
> 
> encumbrances (https://github.com/ArctosDB/arctos/issues/703) - ask is not clear so requirements are not clear

From Encumbrance Meeting today

1. Create Encumbrance
2. Enter catalog record and include encumbrance number or whatever
3. Load the record and it gets added to the encumbrance

**Comment by Jegelewicz** [comment]
@dustymc notes that more than one encumbrance may apply to a catalog record - this is true, do we say, we can only do one or do we accommodate as many as you want?

If you have more than one, then maybe you need to encumber the entire record (only takes one encumbrance), once the record is loaded, add the encumbrances you actually want and remove the record from the "whole record" encumbrance.

**Comment by acdoll** [comment]
> maybe you need to encumber the entire record...

That seems to be the most prudent approach to ensure that restricted data doesn't slip by (even if temporarily).

**Comment by dustymc** [comment]
We could accommodate a list or something, but I suspect that would lead to usability problems.

A temporary 'needs review' full block seems reasonable, but leads directly to the other perpetual encumbrance problem: people never review them, and that ends in one of several quagmires. (I still think a small fee deserves serious consideration; NOTHING gets by the accountants!)

Lists or not (and ignoring all other details), do we need some sort of unique encumbrance identifier or is "3" (or some Arctos URL ending in 3, perhaps) sufficient?

**Comment by Jegelewicz** [comment]
> some Arctos URL ending in 3

Seems like it would work just fine, but it would probably be easier if we could just use the "3" part and have Arctos know to add the rest.

This encumbrance has a unique key "10000278"

https://arctos.database.museum/Encumbrances.cfm?action=updateEncumbrance&encumbrance_id=10000278

If we had a bulkload/data entry field "encumbranceID" and I could enter "10000278" in it, I think that would be sufficient. If I have to enter "https://arctos.database.museum/Encumbrances.cfm?encumbrance_id=10000278" I am sure we could make that happen too - it is just more likely that people will make typos the longer the thing we ask for.

**Comment by Jegelewicz** [comment]
Perhaps in the same way we place the record identifier on a catalog record page, we should place the encumbrance identifier on the encumbrance page(s)?

**Comment by Jegelewicz** [comment]
> they're ugly enough that most won't try to type them

I have been thinking about this with regard to https://github.com/ArctosDB/internal/issues/229

It seems relatively easy for someone to take "https://arctos.database.museum/guid/ACUNHC:Bird:5" and increment the bit after the last ":" by one and search again. The integer catalog numbers are probably not our friends in that case?

**Comment by dustymc** [comment]
>, this is what is have

See above comment, doesn't have to be.

>place the encumbrance identifier on the encumbrance page(s)?

Sure, we should probably just make a habit of that.

>The integer catalog numbers are probably not our friends i

Why not?

**Comment by Jegelewicz** [comment]
> Why not?

They are easily incremented, so I can write a script to search for one after the other - maybe that's just dumb? Not anything we could change, just an observation.

**Comment by dustymc** [comment]
Ah - yep, you can do that - but your network will get blocked in response. Bots iterate through taxa as easily as they do integer series, I don't think the format much matters.

**Comment by mkoo** [comment]
This is closed for now since original implementation is done and it's turned into a functional discussion
