### ISSUE TITLE
blocked IP help

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#7031]
A colleague of mine at the Cordova-based Ilanka Cultural Center, run by the Native Village of Eyak, as tried to access Arctos and got a blocked IP message. Is that something we can help with?

![image001](https://github.com/ArctosDB/arctos/assets/17605945/36ab4a89-8047-47f4-b31c-ea2dd973fb2c)

I'm going to be sending them a NAGPRA report and they'll need to be able to access the records for federal compliance with the law.

**Comment by dustymc** [comment]
Released, should clear witthin 10 minutes.
