### ISSUE TITLE
Agent Merge Request- Chris Briggs

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#7036]
Use this template when you discover two agents that you believe represent the same person or organization.

**Agent that should remain after the merge**
I'm not actually sure. 
Ok problem: Dr. Chris Briggs is in Arctos twice. Once for loans from CHAS, and once for a project and loans with MVZ.
I need to add Chris to a publication again, and add objects from the UWYMV to that publication.

Chris was at Hamilton college and is now at SUNY. So both agents are correct, but one is more up-to-date?

https://arctos.database.museum/agents.cfm?agent_id=21347967
https://arctos.database.museum/agents.cfm?agent_id=21347967

Please add this issue to the Agents Project

@ArctosDB/agents-committee

@ccicero @droberts49

**Comment by dustymc** [comment]
Added relationship and moved shipment.

**Comment by ewommack** [comment]
Thanks Dusty!
