### ISSUE TITLE
Quad locality attribute not in download flat attributes

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#7040]
When I download locality data from locality search using download flat attributes, the locality attribute quad is not included. 

I'm getting into the season where permitees start asking me for locality pulls, and having this data in the locality download is very helpful.

**Comment by mkoo** [comment]
HI @Nicole-Ridgwell-NMMNHS I'm trying to replicate this to see what you mean. Are you doing this from the locality table?
and this button Download Locality Attributes?:
![Firefox_Screenshot_2023-12-08T20-28-26 009Z](https://github.com/ArctosDB/arctos/assets/2523089/7d574c8c-94da-4929-841f-f7f0b031f53d)

When I do that I have ```quad``` attributes included.

And I get there from the Tools dropdown menu after getting search results
![Screenshot 2023-12-08 at 12 31 04 PM](https://github.com/ArctosDB/arctos/assets/2523089/b8ef6abd-f7ee-4adb-ae19-ecb6e8de3241)

Let me know if that's your workflow or not so we can address

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
No, this button:

![image](https://github.com/ArctosDB/arctos/assets/47402809/d32f8d30-96be-4c8c-a152-7e5f0f34224d)

**Comment by dustymc** [comment]
I'm not sure how to respond to this. I can't have 'quad' as a header twice, but that's the data. There's an open request to do something more geog_auth_rec.quad, but maybe/hopefully that's just confusion? I'd rather not rebuild then immediately rebuild....

**Comment by dustymc** [comment]
I'm dealing with the actionable nontheoretical problem, we can revisit if anything new becomes reality.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thank you!
