### ISSUE TITLE
Arctos Report SQL Request for MSB BIRD LOAN INVOICE

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#7042]
I dont have access to MSB collections so a little hamstringed here to test but can you review https://arctos.database.museum/Reports/reporter.cfm?action=edit&report_id=94 especially 
```concatsingleotherid(flat.collection_object_id,'NK') NK,``` so it displays just the identifier

I dont know if you have to write a function eg "getNK(flat.collection_object_id) as NK," but let me know if not clear

They just want the value in the table called NK so the rest is HTML/CSS

**Comment by dustymc** [comment]
See https://github.com/ArctosDB/arctos/issues/6904 and https://github.com/ArctosDB/PG_DDL/blob/master/function/concatIdentifierValueByType.sql

**Comment by mkoo** [comment]
Oh so you already did this- and that's what concatIdentifier is for! Thanks Dusty! 
Well I cant test since I dont have access but I see the report from Tom (MSB:Herp Loan invoice) and it works great for our collector numbers...

So @campmlc can you try this clone called "MSB:Herp Loan Invoice for TESTING" (https://arctos.database.museum/Reports/reporter.cfm?action=edit&report_id=137) and see if that works? I can tweak the bird one from that.

For reference this is the current msb:bird invoice:
![image](https://github.com/ArctosDB/arctos/assets/2523089/a6b5763e-e977-4f92-9188-23d69f44c2dc)

**Comment by dustymc** [comment]
done?
