### ISSUE TITLE
Reports help: adding all collectors and identification_1_agent_1 

### ISSUE THREAD

**Issue by adhornsby** [ArctosDB/arctos#7044]
I'm trying to match the following report to our legacy labels.
https://arctos.database.museum/Reports/reporter.cfm?action=edit&report_id=135

I'm stuck on two things:
1. Getting all of our collectors (agents and verbatim) into line "Collectors:"
2. Getting identification_1_agent_1 into line "ID by:"

Any help would be appreciated.

Related -- is there a master list of fields that I can reference when I'm trying to add things to reports?

**Comment by dustymc** [comment]
A few questions:

Are you trying to exclude records with no parts? The current SQL does that, I'd think that would not be desired.

You're pulling eg quad, I suspect it's not what you think, is that by design?

Maybe it would be best to start by telling me what you want?? Or I can roll with what you have, or whatever, but there are lots of little subtle places where we can get lost from here.

Do you want all collectors regardless of role? And all attribute value where type = verbatim agent? Any sorting or organization?

The bulkloader (flat) doesn't map to the DB (very not-flat) - there's not really an identification_1_agent_1. I can get the first agent of an arbitrary 1-ranked ID, or the first agent of the best-ranked ID, or ???? Or flat.identifiedby might be what you want.

>master list of fields 

See above - not really, Arctos is a complicated structure, there's not anything that looks like a spreadsheet hiding under there anywhere. There is FLAT, it might be useful for labels, writesql and ``select * from flat where guid='ABX:XYZ:123' ``

**Comment by mkoo** [comment]
> Related -- is there a master list of fields that I can reference when I'm trying to add things to reports?

Oh yes! See attached for fields in flat
[flat_variables.csv](https://github.com/ArctosDB/arctos/files/13640021/flat_variables.csv)

You can do this yourself with tips in this [Report Tutorial which is still being expanded](https://docs.google.com/document/d/e/2PACX-1vQC4WNQpWOTPhiGVrI_Os9FOh-Pm7eOwABc2o7qM3SOMe4rx3FPYrWLmwRX4CJMJZ6T7yZrmzXumQkC/pub) so not yet in handbook but it is linked at the top of the page on the Report page in Arctos

**Comment by adhornsby** [comment]
@dustymc Well you identified one of the problems, which is that I frankensteined this together from other reports!  I'm just trying to get something functional and will circle back later to clean it up (famous last words).  The screen grab at bottom is what I'm aiming for, with the addition of the "collector" and "ID by" lines.

> Are you trying to exclude records with no parts? The current SQL does that, I'd think that would not be desired.

No, I don't mean to exclude records with no parts.  Oops!

> You're pulling eg quad, I suspect it's not what you think, is that by design?

Nope, just a frankenstein artifact.  I deleted it.

> Do you want all collectors regardless of role? And all attribute value where type = verbatim agent? Any sorting or organization?

On the "Collector" line, I want everyone who is either **agent with role=collector** or **attribute verbatim agent with method=collector**.  No particular order.

>The bulkloader (flat) doesn't map to the DB (very not-flat) - there's not really an identification_1_agent_1. I can get the first agent of an arbitrary 1-ranked ID, or the first agent of the best-ranked ID, or ???? Or flat.identifiedby might be what you want.

On the "ID by" line... I'm just now seeing that our ID people were loaded as verbatim agents.  So on this line I would want everyone who is **attribute verbatim agent with method=identifier**.  No particular order.  (flat.identifiedby would have been exactly what I was looking for to call up identification_1_agent_1, if my ID people were in the right place.  Problem for another day.)  

Huge thanks!

<img width="431" alt="image" src="https://github.com/ArctosDB/arctos/assets/40217539/e8a0b329-771d-4140-a4d3-ef27e0c001ce">

**Comment by dustymc** [comment]
I changed some stuff, give it a go.

Here's the pre-update version.
[BELL fish v2.csv.zip](https://github.com/ArctosDB/arctos/files/13641991/BELL.fish.v2.csv.zip)

**Comment by adhornsby** [comment]
Nuts... I very unhelpfully overwrote the changes.  Are they easy enough to recreate @dustymc ?  Sorry.

**Comment by dustymc** [comment]
I overwrote the overwriting.

**Comment by adhornsby** [comment]
That does it, thanks @dustymc !

**Comment by adhornsby** [comment]
@dustymc Your new tweaks worked, but it looks like part_count broke in the process.  I'd like for part_count to be the number of whole organisms in the lot (part_1_count).  

This was working in my previous version using "sum(specimen_part.part_count) as part_count".  Now with "pc.pc as part_count" it's giving the number of _types_ of parts in the record.  When I tried to just change that line, I get caught in a vortex of errors way beyond my skill level!

Advice?

**Comment by dustymc** [comment]
It should be doing what it was before, but I added the filter.

**Comment by adhornsby** [comment]
Everything looks good except for the "Specimens: #" near the upper right.  On the original they gave the lot size from part_1_count, and now they all just show 1 as in one part on the record (a few records show 2 if they have two separate lots of whole organisms with different preservations).  I assume the change from "sum(specimen_part.part_count) as part_count" to "pc.pc as part_count" is what's driving this?

Original (specimen counts correct = lot size)
<img width="1028" alt="image" src="https://github.com/ArctosDB/arctos/assets/40217539/c1fbd9e8-8a42-4aef-90ca-bd06953060fd">


Current (specimen counts are now just the number of separate parts on the record)
<img width="1027" alt="image" src="https://github.com/ArctosDB/arctos/assets/40217539/0976b088-4822-485c-98be-4a083bcd2f2f">

**Comment by Jegelewicz** [comment]
@adhornsby it sounds like you want Arctos to come up with [individual count](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#individual_count), which it cannot do because it is complicated. However, it also sounds like we could sum all of the lot_count for any part name = whole organism in the record and get what you are looking for?

**Comment by adhornsby** [comment]
@Jegelewicz @dustymc Yes, I think sum of lot_count for parts = whole organism would do what I'm looking for?  I'm trying to get the number in the part "Qty" field of the specimen record to show up on the "Specimens: #" line of the report.

E.g. https://arctos.database.museum/guid/JFBM:Fish:50405 has 7 whole organisms, so I want the label to show Specimens: 7.

<img width="279" alt="image" src="https://github.com/ArctosDB/arctos/assets/40217539/a0a3005f-c9ee-489e-bc73-da2e43e9f3c1">

![image](https://github.com/ArctosDB/arctos/assets/40217539/2d6cc5d7-6bb2-4155-8d08-26321daf6f5a)

**Comment by adhornsby** [comment]
That does it -- thank you @dustymc !
