### ISSUE TITLE
Misspelling in Catalog Record search form pop-up

### ISSUE THREAD

**Issue by genevieve-anderegg** [ArctosDB/arctos#7045]
"Arhive Name" displays in the pop-up when you click on "in Archive" on the main Catalog Record search page. I can lend a "C" if needed!
![image](https://github.com/ArctosDB/arctos/assets/83782023/c9f1a651-b119-46f4-a8db-a880dbf3f8de)

**Comment by dustymc** [comment]
FYI that's under  inline documentation
