### ISSUE TITLE
Picking and Pull/Syncing an Event/Locality in Data Entry makes Specific Locality box turn Red

### ISSUE THREAD

**Issue by genevieve-anderegg** [ArctosDB/arctos#7046]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Picking and Pull/Syncing an Event/Locality in Data Entry makes Specific Locality box turn Red

**To Reproduce**
Search for an event or locality. Pull/Sync the event or locality. All the data is inserted into the data entry form as it should be, but the "locality_specific" box turns red.

**Expected behavior**
It should not be a red background, it should be a white background. Red signals that something is incorrect in the data entry form and the record was not saved. I don't want volunteers to be confused by this. I'm also taking a bunch of screenshots right now to update our data entry procedures and want the screenshots to be correct and not contain any confusing bugs. 
**Screenshots**
![image](https://github.com/ArctosDB/arctos/assets/83782023/e4bce7d2-813d-407d-b522-7521319534e0)

**Data**
Any event or locality in data entry

**Desktop (please complete the following information):**
Chrome, PC

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by genevieve-anderegg** [comment]
It might have something to do with what profile I'm using, but all the relevant values are set to Show and not Carry. I'm probably missing something obvious...
![image](https://github.com/ArctosDB/arctos/assets/83782023/119d70c7-5376-4323-a126-782877ac11bc)

**Comment by dustymc** [comment]
I can't figure out how to re-create this. I can pull either or both and sync them any number of times and not see red.

<img width="1616" alt="Screenshot 2024-01-02 at 08 58 21" src="https://github.com/ArctosDB/arctos/assets/5720791/f7e91ab7-7979-4473-8b10-52d0eeebb5bf">
<img width="1209" alt="Screenshot 2024-01-02 at 08 58 14" src="https://github.com/ArctosDB/arctos/assets/5720791/a4a57cc5-0df5-4944-b9d4-2c48a8693f81">
<img width="1647" alt="Screenshot 2024-01-02 at 08 58 00" src="https://github.com/ArctosDB/arctos/assets/5720791/c75a3b89-2f2d-4006-aae7-fe2cc1233af2">
