### ISSUE TITLE
Feature Request - Limit Browse and Edit to username on initial load

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7128]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

I have access to a lot of collections - I do fear there will come a day that Browse and Edit will timeout for me. As it is it takes a very long time to load.

**Describe what you're trying to accomplish** 
_A clear and concise overview of the goals; why are you asking for this?_

Make sure I can use the tool.

**Describe the solution you'd like**
_How might we accomplish your goals?_

If I could limit the records shown when the form initially opens, then I could make the process quicker. This could be a setting forced upon everyone (limit records show at first to the username) or as a setting remembered for each user. Alternatively, we could not load any records UNTIL after a filter is selected. Other ideas appreciated. While this only affects a few users currently, I can see it becoming an issue for more and more people as time goes on.

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

Wait until the day that I can't use the form because it times out.

**Additional context**
_Add any other context or screenshots about the feature request here._

@campmlc has experienced the slowness - not sure if it affects anyone else yet, but probably also @mkoo 

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._

**Comment by campmlc** [comment]
Absolutely agree - this is becoming untenable. I would suggest that as a default the form wait to load any records until the operator selects and filters for a username, accession, or collection. Perhaps we need to add a "show all" option, but that shouldn't be the default to open and use Browse and Edit, as it is now.

**Comment by campmlc** [comment]
I also support the option of just showing the records for my username as default. But if I have a large number of records pending, and I actually want to review records from another user, it is a waste of resources for Arctos to spend time loading and displaying a bunch of records that I don't need to see at the moment.

**Comment by campmlc** [comment]
@AdrienneRaniszewski

**Comment by mkoo** [comment]
Or just dont load anything until user selects a filter (the option can still include Any); generally a solid request!

**Comment by dustymc** [comment]
>I have access to a lot of collections - I do fear there will come a day that Browse and Edit will timeout for me. As it is it takes a very long time to load.

The form takes a long time to load because we agreed to add a lot of columns to the table, and it takes some time (in your browser, completely dependent on your local environment) for datatables to do its thing with that.

Once that's completed, there's a network call to fetch data (consistently less than a second for me) and process that into the table (also depends on your local environment, but a few milliseconds for me).

I have no particular objections to changing how things work, but

1. It will be non-standard behavior which is likely to make things slower and more fragile,
2. It won't much impact performance, and 
3. It'll likely be an extra click or two (and a change) for some users.

**Comment by campmlc** [comment]
I understand that the request is to allow the user to first filter on a collection before loading. The time to load is greatly increased as a function of the number of collections that user has access to. So the default should not be set to load everything for all collections at startup.

**Comment by campmlc** [comment]
And for us, through the browser, the time to load data is seconds to minutes, with concern it may fail to load.

**Comment by campmlc** [comment]
Once we filter on a single user, collection, or accession, time to load is much faster, even though the number of columns does not change.

**Comment by Jegelewicz** [comment]
I totally get that this really only affects a few of us - but we are also the ones doing a lot of data entry for more than one collection/institution. If there is some way we can change nothing for mostly everyone, but through some method allow a few of us to limit this at open (a preference selected in our profile?) I'd feel less worried. Or we can just wait to see if the timeout ever happens and if it does, can I select a filter then try again?

**Comment by dustymc** [comment]
>see if the timeout ever happens

You don't have to believe me, but it's really not related....

The form will accept parameters in the URL eg

https://arctos.database.museum/Bulkloader/browseBulk.cfm?enteredby=jegelewicz

https://arctos.database.museum/Bulkloader/browseBulk.cfm?colln=UNM:Geol

https://arctos.database.museum/Bulkloader/browseBulk.cfm?enteredby=jegelewicz&colln=UNM:Geol

maybe a bookmark does what you want?

**Comment by Jegelewicz** [comment]
YES - that is a great way to handle it! Thanks!
