### ISSUE TITLE
Allow more characters in specific locality

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7129]
> We got the following error on a catalog record bulkload: value too long for type character varying(255)
I assume this is because our verbatim locality is too long (its 280 characters with spaces) but its verbatim so I can't help that. Can we get more characters?

_Originally posted by @falco-rk in https://github.com/ArctosDB/data-migration/issues/1516#issuecomment-1856571684_
           
It is actually specific locality that is only 255.

![image](https://github.com/ArctosDB/arctos/assets/5725767/c6354462-4f1c-4bbd-a8da-e802a032b315)

Only 255 for this? Seems way too short - can we get 4,000?

**Comment by Jegelewicz** [comment]
nevermind - it is 4000.

**Comment by dustymc** [comment]
Can I get an example of data which follows the docs and needs this?

**Comment by Jegelewicz** [comment]
@happiah-madson and @falco-rk  see above.

**Comment by falco-rk** [comment]
our specific locality is: Dallmann Bay; Dallmann Bay, south of Astrolabe Needle; Dallmann Bay, same as set 2; Neumayer Channel, South of Port Lockroy; Neumayer Channel, North of Port Lockroy; Neumayer Channel, by Port Lockroy; Low Island; North of Dallmann Bay; Dallmann Bay - south of original box
@happiah-madson

**Comment by falco-rk** [comment]
Fair enough. We will adjust it to be more concise. Can you give me manage_locality permissions?

**Comment by Jegelewicz** [comment]
permission granted

**Comment by dustymc** [comment]
Done?
