### ISSUE TITLE
Feature Request - job title should be a component of employer relationship

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7132]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

From interviews by @ekrimmel regarding Agents:

> Job title should not be a name component. This information is duplicated between Agent names and Relationship remarks (where the relationship is “employee of” an organization). There are functional implications of knowing what job titles are associated with which organizations, e.g. for authorizing loans.
> 
> See [agent-record-interface_20231002_hannah-appiah-madson.mp4](https://drive.google.com/file/d/16n_tjnmMvjjfL3ojPe-Swjcim3TFpn7w/view?usp=drive_link)
> 
> See [Jacob Daane](https://arctos.database.museum/agent/21349086) for an example of multiple job titles associated with a career trajectory

**Describe what you're trying to accomplish** 
_A clear and concise overview of the goals; why are you asking for this?_

Associate job titles with the employer relationship.

**Describe the solution you'd like**
_How might we accomplish your goals?_

OK - I know that some people will NOT want to create an agent for the employer just to add a job title, so we probably need a way to record a job title that is not associated with an employer relationship (so keep the name type?) BUT I do think that adding a job title to the employer relationship also makes sense for those situations where changes over time need to be recorded/managed.

Ideas appreciated.

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

I usually put the job title in the remark of the employer relationship, but I can't really do anything with that, especially when there is other information in the remark (like the source of the information).

**Additional context**
_Add any other context or screenshots about the feature request here._

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._

**Comment by mkoo** [comment]
I agree with this in principle. I always thought it didnt make sense there. For our collections, it's typically buried (historic contingency) in the remarks/ biography so agreed that the employer relationship is ideal and should be promoted as best practices (inclding active dates!) 

Do we use/ display job title anywhere else besides the agent pages?

If we agree to remove job title from the names then how much clean up are we talking about?

**Comment by Jegelewicz** [comment]
> Do we use/ display job title anywhere else besides the agent pages?

I could see people using it in reports? Loans and such...

**Comment by dustymc** [comment]
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctagent_name_type#job_title is handy for printing labels, and I see no reason to remove it from that role. It's certainly no replacement for anything in https://arctos.database.museum/info/ctDocumentation.cfm?table=ctagent_relationship, and I'd hope that'd be evident from the structure. (Or: We probably need better documentation.)

https://github.com/ArctosDB/arctos/issues/5172 might let you get at "agent in role at time," which might be what's being attempted (not very successfully...) in the example.

**Comment by dustymc** [comment]
See https://github.com/ArctosDB/arctos/issues/5172#issuecomment-1877911663 - adding interval to names would make these data a bit less cryptic.
