### ISSUE TITLE
character limit in record event load not consistent with recorded limits

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7136]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

Trying to load data to the record event load tool - https://arctos.database.museum/loaders/BulkloadSpecimenEvent.cfm and getting this error:

ERROR_ID | 7F18F07D-D6A7-47D0-A04944FFEFF52922
-- | --
ERROR_TYPE | application
ERROR_MESSAGE | Error invoking external process
ERROR_DETAIL | lucee.commons.cli.CommandException:  psql:/usr/local/webroot/temp/excopy_jegelewicz_20231215031208573_445.sql:43:  ERROR:  value too long for type character varying(255) CONTEXT:  COPY cf_temp_specevent, line 2, column specimen_event_remark:  "Event Name: Okeanos Explorer EX1504L2, DIVE02, 22:51; Contact Person:  Kelley, Christopher; Vessel Na..."

However, the expected length limit for this field is 4000 characters:

![image](https://github.com/ArctosDB/arctos/assets/5725767/e7b61e9b-ce01-41cd-9e5f-7893f3845048)

**To Reproduce**
1. Load attached file
2. Get error

**Expected behavior**

I expect this file to load as all of the `specimen_event_remark` are under 4000 characters. (Not saying there could be other issues, but this shouldn't be one of them....)

**Screenshots**

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

[OGL_record_event_load.csv](https://github.com/ArctosDB/arctos/files/13690001/OGL_record_event_load.csv)

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by dustymc** [comment]
fixed
