### ISSUE TITLE
Code Table Request - new part name: environmental sample

### ISSUE THREAD

**Issue by falco-rk** [ArctosDB/arctos#7141]
### Goal
_Describe what you're trying to accomplish. This is the only necessary step to start this process. The Committee is available to assist with all other steps. Please clearly indicate any uncertainty or desired guidance if you proceed beyond this step._

To facilitate the curation of microbiome samples.

### Context
_Describe why this new value is necessary and existing values are not._

While microbial mat and cell culture exist, OGL needs a more generic term for microbial community samples.

### Table
_Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table or value. This may involve multiple tables and will control datatype for Attributes. OtherID requests require BaseURL (and example) or explanation. Please ask for assistance if unsure._

specimen_part_name https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name

### Proposed Value
_Proposed new value. This should be clear and compatible with similar values in the relevant table and across Arctos._

~~microbiome~~

environmental sample

### Proposed Definition
_Clear, complete, non-collection-type-specific **functional** definition of the value. Avoid discipline-specific terminology if possible, include parenthetically if unavoidable._

~~the community of microorganisms that can usually be found living together in any given habitat. It was defined more precisely in 1988 by Whipps et al. as "a characteristic microbial community occupying a reasonably well-defined habitat which has distinct physio-chemical properties. The term thus not only refers to the microorganisms involved but also encompasses their theatre of activity". https://en.wikipedia.org/wiki/Microbiome~~

Environmental samples include air, water, soil, dust, biological materials and wastes (liquids, solids or sludges) collected for the purpose of analysis of microbial communities, pathogens, eDNA, toxins, pollutants, etc.

### Collection type
_Some code tables contain collection-type-specific values. ``collection_cde`` may be found from https://arctos.database.museum/home.cfm_

n/a

#### Attribute data type
_If the request is for an attribute, what values will be allowed?
free-text, categorical, or number+units depending upon the attribute (TBA)_

n/a

#### Attribute controlled values
_If the values are categorical (to be controlled by a code table), add a link to the appropriate code table. If a new table or set of values is needed, please elaborate._

n/a

#### Attribute units
_if numerical values should be accompanied by units, provide a link to the appropriate units table._

n/a

#### Part preservation attribute affect on "tissueness"
_if a new part preservation is requested, please add the affect it would have on "tissueness": No Influence, Allows, or Denies_

allows

### Priority
_Please describe the urgency and/or choose a priority-label to the right. You should expect a response within two working days, and may utilize [Arctos Contacts](https://arctosdb.org/contacts/) if you feel response is lacking._

### Example Data
_Requests with clarifying sample data are generally much easier to understand and prioritize. Please attach or link to any representative data, in any form or format, which might help clarify the request._

### Available for Public View
_Most data are by default publicly available. Describe any necessary access restrictions._

### Helpful Actions

- [x] Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

- [x] Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

@ArctosDB/arctos-code-table-administrators @happiah-madson @Jegelewicz 

## Approval
_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection
_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation
_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

- [ ] Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

- [ ] Add or revise the code table term/definition as described above. Ensure the URL of this Issue is included in the definition. URLs should be included *_as text_*, separated by spaced pipes. Do not include HTML in definitions.

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by Jegelewicz** [comment]
@jldunnum @bryansmclean are mammal people collecting microbiomes? If so, do you have thoughts about this?

**Comment by bryansmclean** [comment]
Host tissues likely to contain microbiomes are certainly collected, but the microbiome itself usually wouldn't be considered a "part" until verified by sequencing. I'm that case genbank links could point to it. I guess if you had additional microbial samples whose community properties have been previously characterized by sequencing, then this request makes sense.

**Comment by dustymc** [comment]
>microbial community samples.

What exactly is the "thing to which one might stick a barcode"?

**Comment by happiah-madson** [comment]
"Approximately 100 g of the orange cyanobacterial–bacterial crust or benthic material (when crusts were absent) was collected from three sampling locations at each site with disposable sterile spoons and preserved in both RNAlater (Thermo Fisher Scientific, MA, USA) and 95% ethanol as well as flash frozen in 10% dimethyl sulfoxide (DMSO) and 10% glycerol with liquid N2. Ethanol-, DMSO-, and glycerol-preserved samples were archived as part of the Hawaiian Anchialine Microbial Repository in conjunction with the Ocean Genome Legacy Center"

^ This is literally what they sampled and put in the tubes that we now have in our collection. Is this clarifying?

**Comment by dustymc** [comment]
>Is this clarifying?

Yes! (I'm not sure now-me knows what to do with it, but future-me will definitely appreciate that comment!)

I think this is somewhere between https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#geosample (scooped up some substrate) and https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#filter_paper (scooped up some substrate with a goal in mind) and https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#hindgut_content (substrate with a location) and maybe https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#microbial_mat (but teensy?). Maybe we're missing some sort of 'sample with a purpose' part, or ?????????? I don't know, checking boxes because I don't think this will be too regrettable....

**Comment by campmlc** [comment]
The actual sample here is "benthic material" or "biotic crust" - which is similar to "soil" or "water" in environmental samples scanned for eDNA. We also get microbiomes through analyzing intestinal contents, skin or oral swabs, root or leaf material, etc. So I'm a bit hesitant about using it as a part name. On the other hand, it is analogous to "whole organism" - just a bunch of organisms of multiple taxa along with the organic and inorganic substrate they are a part of. But what if the benthic sample was sterile or taken from some toxic or hazardous material? Then there would be no microbiome associated - but we'd still have the soil/substrate material.  What about just using "biotic crust"?

**Comment by Jegelewicz** [comment]
What about environmental sample? Super generic and details can go in part remark? Maybe there could be part modifiers for some situations.

**Comment by falco-rk** [comment]
I'm fine with environmental sample

**Comment by campmlc** [comment]
Environmental sample works for us

**Comment by Jegelewicz** [comment]
> environmental sample

OK, but then the definition is totally wrong?

The only definitions I could find for environmental sample definitely overlap with geosample, rock, mineral, and maybe other stuff?

> paint-chip, dust, soil, water or air samples collected for the purpose of analysis

> The most common environmental samples are air, water, soil, biological materials, and wastes (liquids, solids or sludges). Each matrix is sampled using different techniques, but the underlying concepts are same in each case.

However, the thing described above by @happiah-madson may or may not have both geological and biological material, so how about

Samples collected for the purpose of analysis that cannot be classified as either geological or biological in nature.

Hit me with something better, or tell me to stop and let's just proceed with the term as originally suggested.

**Comment by campmlc** [comment]
I think we should just proceed with "environmental sample" and not overthink it. As @dusty says, this is somewhat of an "intent" issue - it means the sample was collected for some kind of analysis, which could be microbiome, pollutants, eDNA, etc. We don't want to force geological collections to use it, and it becomes too complicated to try to add all the biological and geological terms as a mixed part. 
Here's another possible definition version modified based on https://www.lawinsider.com/dictionary/environmental-samples. Note that

"Environmental samples include air, water, soil, dust, biological materials and wastes (liquids, solids or sludges) collected  for the purpose of analysis of microbial communities, pathogens, eDNA, pollutants, etc..

**Comment by falco-rk** [comment]
I'm good with that definition

**Comment by happiah-madson** [comment]
also ok w/ this

**Comment by Jegelewicz** [comment]
initial request has been modified - everyone re-evaluate please!

**Comment by campmlc** [comment]
Looks good. I checked a box.

**Comment by falco-rk** [comment]
Looks fine to me

**Comment by Jegelewicz** [comment]
@dustymc this has changed significant;y - is it still acceptable?

**Comment by dustymc** [comment]
Just keeps gettin' better!

**Comment by Jegelewicz** [comment]
added
