### ISSUE TITLE
Code Table Request - new part name: appendage

### ISSUE THREAD

**Issue by falco-rk** [ArctosDB/arctos#7143]
### Goal
_Describe what you're trying to accomplish. This is the only necessary step to start this process. The Committee is available to assist with all other steps. Please clearly indicate any uncertainty or desired guidance if you proceed beyond this step._

OGL has many specific appendage types (such as pleopod, tentacle, probiscus, etc.). We don't need a bunch of nee very specific part but aren't comfortable using the part names that are available and would like a more generalized term for these and other limbs/appendages.

### Context
_Describe why this new value is necessary and existing values are not._

Need a more generalized term for limbs/appendages. Also, the definition for leg says "consider using limb," but limb does not exist in the code table.

### Table
_Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table or value. This may involve multiple tables and will control datatype for Attributes. OtherID requests require BaseURL (and example) or explanation. Please ask for assistance if unsure._

specimen_part_name https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name

### Proposed Value
_Proposed new value. This should be clear and compatible with similar values in the relevant table and across Arctos._

appendage

### Proposed Definition
_Clear, complete, non-collection-type-specific **functional** definition of the value. Avoid discipline-specific terminology if possible, include parenthetically if unavoidable._

Any limb that extends from the body. Arms and legs, for example, are appendages. Arthropods’ mouthparts are often small, limb-derived extensions of the body, and so are considered appendages. Appendages can be modified into sensory or sexual organs.
https://evolution.berkeley.edu/glossary/appendage/

### Add as alternate term to

The alternate term appendage be added to:

antenna [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#antenna)
arm [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#arm)
chela [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#chela)
claw [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#claw)
fin [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#fin)
flipper [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#flipper)
forelimb [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#forelimb)
leg [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#leg)
pereiopod [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#pereiopod)
wing [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#wing)

Note that I easily may have missed something - so a review by someone else would be good. Also, I DID NOT include all the parts that might be only a portion of an appendage. I only added things that seemed like synonyms for appendage.

### Collection type
_Some code tables contain collection-type-specific values. ``collection_cde`` may be found from https://arctos.database.museum/home.cfm_

n/a

#### Attribute data type
_If the request is for an attribute, what values will be allowed?
free-text, categorical, or number+units depending upon the attribute (TBA)_

n/a

#### Attribute controlled values
_If the values are categorical (to be controlled by a code table), add a link to the appropriate code table. If a new table or set of values is needed, please elaborate._

n/a

#### Attribute units
_if numerical values should be accompanied by units, provide a link to the appropriate units table._

n/a

#### Part preservation attribute affect on "tissueness"
_if a new part preservation is requested, please add the affect it would have on "tissueness": No Influence, Allows, or Denies_

allows

### Priority
_Please describe the urgency and/or choose a priority-label to the right. You should expect a response within two working days, and may utilize [Arctos Contacts](https://arctosdb.org/contacts/) if you feel response is lacking._

### Example Data
_Requests with clarifying sample data are generally much easier to understand and prioritize. Please attach or link to any representative data, in any form or format, which might help clarify the request._

### Available for Public View
_Most data are by default publicly available. Describe any necessary access restrictions._

### Helpful Actions

- [x] Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

- [x] Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

@ArctosDB/arctos-code-table-administrators @happiah-madson @Jegelewicz 

## Approval
_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection
_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation
_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

- [x] Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

- [x] Add or revise the code table term/definition as described above. Ensure the URL of this Issue is included in the definition. URLs should be included *_as text_*, separated by spaced pipes. Do not include HTML in definitions.

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by dustymc** [comment]
This seems like we've just gone the wrong way during some cleanup, so I have two questions.

Can we change https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#leg to "limb"? 

Users:
```

 guid_prefix | count 
-------------+-------
 ALMNH:Mamm  |     1
 ALMNH:Paleo |     1
 CHAS:Bird   |     1
 CRCM:Bird   |     9
 CRCM:Paleo  |     2
 CSULB:Mamm  |     2
 DMNS:Mamm   |     1
 KNWR:Ento   |   104
 MSB:Herp    |     7
 MSB:Mamm    |     4
 MVZ:Herp    |     1
 MVZ:Mamm    |    11
 NMMNH:Paleo |     2
 OWU:Bird    |     2
 OWU:ES      |     5
 UAM:Ento    |  1158
 UCM:Mamm    |     2
 UWBM:Herp   |     1
 UWBM:Mamm   |     2
 UWZM:Mamm   |    13
```


 @ebraker
 @Nicole-Ridgwell-NMMNHS
 @mkoo
 @campmlc
 @atrox10
 @DerekSikes
 @cjconroy
 @jtgiermakowski
 @wellerjes
 @jebrad
 @babogan
 @jrpletch
 @AdrienneRaniszewski
 @aklompma
 @acdoll
 @jldunnum
 @jrdemboski
 @jessicatir
 @droberts49

And should  https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#arm be merged as well?

```

 guid_prefix | count 
-------------+-------
 NMMNH:Paleo |     6

```

 @Nicole-Ridgwell-NMMNHS

**Comment by acdoll** [comment]
Seems reasonable to me. The definition suggests 'leg' might be useful for cultural collections, but no one is using it as such, yet.

**Comment by campmlc** [comment]
Maybe we need to distinguish from tree limb? Or use for both? Limb is definitely better for vertebrates - maybe forelimb, hindlimb? Starfish can use "arm"?

**Comment by happiah-madson** [comment]
But lobsters and crabs and shrimps all have legs, too! It's not just a vert term.

**Comment by cjconroy** [comment]
All the MVZ mammal legs were  Original part name: hindlimb, and then that was changed to leg with modifier of hind!  You're going around in circles.

**Comment by falco-rk** [comment]
>maybe forelimb, hindlimb?
I don't mind if these exist as well, but I would still need just limb

**Comment by dustymc** [comment]
>distinguish from tree limb

Have you used it that way in your data? If so now's the time to sort it out, if not we can deal with trees when that becomes reality.

>Starfish can use "arm"?

But do they NEED to, or is 'limb' (defined in some way that we can work out once we get the big picture) sufficient for the job? I don't care, we can keep 'arm' for chairs and starfish if we need to, but if we can easily make the current data more *useful* then let's do that.

>rabs and shrimps all have limbs, too! 

I'm (very tentatively) suggesting we do just that, stop "subclassifying" limbs here. https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_modifier is a better tool for that job.

>You're going around in circles.

Could be - so help set us on a straight path, please!

**Comment by happiah-madson** [comment]
>    Starfish can use "arm"?

>But do they NEED to, or is 'limb' (defined in some way that we can work out once we get the big picture) sufficient for the job? I don't care, we can keep 'arm' for chairs and starfish if we need to, but if we can easily make the current data more useful then let's do that.

I have no issue with using limb for our starfish arms. Very happy. I agree with trying to make things more easily categoricalized/searchable with the specifics in remarks.

**Comment by campmlc** [comment]
I just want to make sure we've considered all options, especially as our institution is bringing in a plant genomics collection. I'll check a box.

**Comment by Jegelewicz** [comment]
I think the even more generic appendage would be a better option. This would cover tentacles too.

**Comment by falco-rk** [comment]
I'm find with appendage

**Comment by jessicatir** [comment]
Appendage works for our stuff.

**Comment by campmlc** [comment]
Appendage works.

**Comment by cjconroy** [comment]
Don't forget wings. They are also appendages. Is the new thing now part = appendage with a modifier of leg, forelimb, wing, tail, etc.?

**Comment by happiah-madson** [comment]
also happy w/ appendage

**Comment by campmlc** [comment]
I think appendage works. We don't have to get rid of wing. We really do need either an ontology or a means of adding part names to ctcollectioncde or something equivalent to allow different collection types to choose discipline specific terminology.

**Comment by happiah-madson** [comment]
follow up question: if we move to appendage, do we keep the same definition listed above? Or are we moving to a different definition? Wondering b/c we are currently having a conversation about whether things like tube worm plumes can be an appendage (they're sensory, etc.). Thoughts?

**Comment by campmlc** [comment]
From https://evolution.berkeley.edu/glossary/appendage/
"appendage"
Any limb that extends from the body. Arms and legs, for example, are appendages. Arthropods’ mouthparts are often small, limb-derived extensions of the body, and so are considered appendages.

and also https://en.wikipedia.org/wiki/Appendage

**Comment by happiah-madson** [comment]
My only 'concern' is that definition doesn't include the fact that appendages can be modified into sensory or sexual organs. I like that the full wiki page includes a lot of taxonomically diverse information, but I don't think it's reasonable to pull that whole page.

**Comment by campmlc** [comment]
We could just link to it, and add those specific words to our definition.

**Comment by Jegelewicz** [comment]
> a means of adding part names to ctcollectioncde

This already exists - every collection now specifically selects the parts they want available to them.

The challenge happens when someone comes searching and uses "leg" or "wing" and misses all of the appendages that they might have been interested in. We do allow for alternate terms in the part table, but they have not been methodically added.

**Comment by falco-rk** [comment]
I have updated the definition to what was discussed above.

>The challenge happens when someone comes searching and uses "leg" or "wing" and misses all of the appendages that they might have been interested in. We do allow for alternate terms in the part table, but they have not been methodically added.

@Jegelewicz does that mean you don't think we should use appendage?

**Comment by Jegelewicz** [comment]
> does that mean you don't think we should use appendage?

Nope - it means that I think we should add appendage as an alternate term to all of the part names that are also appendages.

**Comment by happiah-madson** [comment]
Oh, that makes perfect sense to me

**Comment by Jegelewicz** [comment]
As such, I would add to this request that the alternate term appendage be added to

antenna [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#antenna)
arm [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#arm)
chela [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#chela)
claw [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#claw)
fin [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#fin)
flipper [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#flipper)
forelimb [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#forelimb)
leg [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#leg)
pereiopod [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#pereiopod)
wing [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#wing)

Note that I easily may have missed something - so a review by someone else would be good. Also, I DID NOT include all the parts that might be only a portion of an appendage. I only added things that seemed like synonyms for appendage.

**Comment by falco-rk** [comment]
That works for me. Anyone have other thoughts?

**Comment by dustymc** [comment]
Title conflicts with the request, someone please clarify?

**Comment by falco-rk** [comment]
I updated the request. Let me know if more clarification is needed.

**Comment by Jegelewicz** [comment]
@mkoo @campmlc @ccicero anyone care to comment or approve?

**Comment by cjconroy** [comment]
If someone wishes to find a part we currently have as "leg", what field would they search to find it? I am curious about the mechanics of finding those parts. If researchers are looking for material for studying jumping in mammals, I don't think they are going to look for "appendage".

**Comment by Jegelewicz** [comment]
@cjconroy they would search for leg. That part will still be there, it will just have appendage as a synonym of sorts. If someone searches for leg, they would also get appendages, if they search for =leg, they will only get parts named leg.

**Comment by cjconroy** [comment]
Thanks!

**Comment by ebraker** [comment]
Works for UCM!

**Comment by campmlc** [comment]
works for MSB!

**Comment by campmlc** [comment]
Looks like it's already approved?

**Comment by Jegelewicz** [comment]
added along with alternate search terms
