### ISSUE TITLE
Code Table Request - part name "ventriculus" with search term "gizzard"

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#7145]
### Goal
I am entering data for a bird specimen that has crop and gizzard contents saved in 70% ethanol.  I need to be able to enter these parts and can do the crop but not the gizzard. 

### Context
We have a part name for 'crop content' but 'gizzard' or 'gizzard content' doesn't exist in the part_name code table.  A search for 'gizzard' in the code table search yields three results, including 'ventriculus' but that's in a different host/para code table: https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlocation_in_host#ventriculus

Is there a problem having the same term in two different code tables? If so, then how do we handle this?

### Table
Need this term in https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name

### Proposed Value
"ventriculus" with additional search term "gizzard"

### Proposed Definition
Use the same definition as in https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlocation_in_host
"The gizzard, gigerium, or gastric mill, in birds, reptiles, and some invertebrates."

### Collection type
Bird

### Priority
High (needed for work)

### Helpful Actions

- [x] Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

- [ ] Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

@ArctosDB/arctos-code-table-administrators 

## Approval
_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection
_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation
_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

- [ ] Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

- [ ] Add or revise the code table term/definition as described above. Ensure the URL of this Issue is included in the definition. URLs should be included *_as text_*, separated by spaced pipes. Do not include HTML in definitions.

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by ccicero** [comment]
@Jegelewicz What discussion is needed? Seems like we just need one more code table administrator to check the box?

**Comment by campmlc** [comment]
I checked a box.

**Comment by Jegelewicz** [comment]
I added a bit of information to the definition:

The gizzard, gigerium, or gastric mill, **is an organ found in the digestive tract of some animals including** birds, reptiles, and some invertebrates.

the part has been added, if the definition is incorrect, please reopen this issue.

**Comment by ccicero** [comment]
@Jegelewicz Thanks! But I'm trying to add it to the record and it says part not found even though I see it in the code table - ?

![image](https://github.com/ArctosDB/arctos/assets/967275/09bf5796-632f-4743-97ae-ec3921d7fba6)

**Comment by ccicero** [comment]
Is there a lag in when it's available to choose?

**Comment by Jegelewicz** [comment]
You probably need to add it to your collection (it's a new thing - go to the parts table and manage collection).

**Comment by ccicero** [comment]
@Jegelewicz Thanks! I forgot about that.

One more related issue: ok if I also add "ventriculus content" to the code table with the definition "Contents of the ventriculus." That's actually what was saved for the record I'm adding.

**Comment by dustymc** [comment]
I think this is done, additional requests need new Issues (or we'll get lost trying to figure out what happened).
