### ISSUE TITLE
Code Table Request - new part name: tube foot

### ISSUE THREAD

**Issue by falco-rk** [ArctosDB/arctos#7149]
### Goal
_Describe what you're trying to accomplish. This is the only necessary step to start this process. The Committee is available to assist with all other steps. Please clearly indicate any uncertainty or desired guidance if you proceed beyond this step._

Echinoderms have tube feet, not feet. They are part of the water vascular system. The definition of foot does not effectively capture tube feet.

### Context
_Describe why this new value is necessary and existing values are not._

The definition of foot does not effectively capture tube feet.

### Table
_Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table or value. This may involve multiple tables and will control datatype for Attributes. OtherID requests require BaseURL (and example) or explanation. Please ask for assistance if unsure._

specimen_part_name https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name

### Proposed Value
_Proposed new value. This should be clear and compatible with similar values in the relevant table and across Arctos._

tube foot

### Proposed Definition
_Clear, complete, non-collection-type-specific **functional** definition of the value. Avoid discipline-specific terminology if possible, include parenthetically if unavoidable._

Tube feet (technically podia) are small active tubular projections on the oral face of an echinoderm
https://en.wikipedia.org/wiki/Tube_feet

### Collection type
_Some code tables contain collection-type-specific values. ``collection_cde`` may be found from https://arctos.database.museum/home.cfm_

n/a

#### Attribute data type
_If the request is for an attribute, what values will be allowed?
free-text, categorical, or number+units depending upon the attribute (TBA)_

n/a

#### Attribute controlled values
_If the values are categorical (to be controlled by a code table), add a link to the appropriate code table. If a new table or set of values is needed, please elaborate._

n/a

#### Attribute units
_if numerical values should be accompanied by units, provide a link to the appropriate units table._

n/a

#### Part preservation attribute affect on "tissueness"
_if a new part preservation is requested, please add the affect it would have on "tissueness": No Influence, Allows, or Denies_

allows

### Priority
_Please describe the urgency and/or choose a priority-label to the right. You should expect a response within two working days, and may utilize [Arctos Contacts](https://arctosdb.org/contacts/) if you feel response is lacking._

### Example Data
_Requests with clarifying sample data are generally much easier to understand and prioritize. Please attach or link to any representative data, in any form or format, which might help clarify the request._

### Available for Public View
_Most data are by default publicly available. Describe any necessary access restrictions._

yes

### Helpful Actions

- [x] Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

- [x] Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

@ArctosDB/arctos-code-table-administrators @happiah-madson @Jegelewicz @genevieve-anderegg @sharpphyl 

## Approval
_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [ ] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [ ] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection
_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation
_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

- [ ] Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

- [ ] Add or revise the code table term/definition as described above. Ensure the URL of this Issue is included in the definition. URLs should be included *_as text_*, separated by spaced pipes. Do not include HTML in definitions.

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by dustymc** [comment]
Is this https://github.com/ArctosDB/arctos/issues/7143 or https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#foot?

**Comment by campmlc** [comment]
No,  it is much different anatomically than a limb or vertebrate or even molluscan foot as these are extensions of the water vascular system used for locomotion in echinoderms.

**Comment by dustymc** [comment]
>different anatomically

Parts don't and can't exist without an identification being involved, this is an "anatomical structure...which bears weight and allows locomotion." I'm asking if that that plus the context of the record carries the information adequately. (Looks like it to me...) All else being equal, simpler==more usable + more accessible.

**Comment by Jegelewicz** [comment]
> that that plus the context of the record carries the information adequately

I think this is the crux of all of our part problems. Are parts meant to stand on their own, with zero context from the records in which they are associated, or are we expecting those searching for "foot" to also be using some taxonomic group? If we could answer this question, it might make a lot of our part code table issues less difficult.

**Comment by campmlc** [comment]
I think being able to use correct part names for given taxonomic groups is going to be essential going forward as we continue to bring in more diverse collections. That's why I asked about whether we can somehow incorporate appropriate terms based on the ctcollectioncde, which is roughly linked to taxonomic groups, but not completely so, unfortunately. Our current terms are very largely vertebrate based, and with parasite and marine collections, not to mention microbial, their are many more phyla with distinct terms and vocabularies. Researchers and collection staff should be able to use the appropriate vocabulary that for a given taxonomic group without having to guess at whatever generic term it's been consolidated with.

**Comment by dustymc** [comment]
>Are parts meant to stand on their own, with zero context from the records in which they are associated

Whatever might have been intended by whomever whenever: no, they structurally cannot.

>Researchers and collection staff should be able to use the appropriate vocabulary that for a given taxonomic group without having to guess at whatever generic term it's been consolidated with.

That's done through https://github.com/ArctosDB/arctos/issues/6823. I suppose it could work in about the opposite way that we've been going, but it would be really nice for that to have surfaced somewhere in the [three years](https://github.com/ArctosDB/arctos/issues/3452) of discussion rather than immediately after implementation, and the obvious entry usability issues (I keep hearing and seeing that eg students can't deal with complexity, then we keeping asking for more complexity) would need somehow addressed. I don't think anyone's quite done this before so who knows, but I think our current approach is the most useful to the most people.

>guess

Not if proper metadata is supplied.

**Comment by Jegelewicz** [comment]
@falco-rk do you guys still need this?
