### ISSUE TITLE
Component loader stuck

### ISSUE THREAD

**Issue by jessicatir** [ArctosDB/arctos#7151]
It looks like the component loader hasn't moved since Friday afternoon. I was hoping someone could give it a nudge when you get a chance.

**Comment by dustymc** [comment]
The loader has been consistently running. [Component Loader Status](https://arctos.database.museum/info/component_loader_status.cfm) will always report status.

**Comment by Jegelewicz** [comment]
@dustymc I have tried moving things around - but nothing seems to be loading in there.

**Comment by dustymc** [comment]
It seems to be running again, I've started the process for a maintenance window.

**Comment by Jegelewicz** [comment]
Happening again? I have 17 records in the Agent bulkload tool set to autoload and nothing in front of them, but they aren't loading.

**Comment by jessicatir** [comment]
This keeps happening off and on. I'm wondering if the Record Event Loader is causing problems because it keeps happening when I'm using that loader specifically. Or it's a coincidence.

**Comment by dustymc** [comment]
>Record Event Loader is causing problems 

Maybe! The next time you use this please load the data, DO NOT set to autoload, and let me know.

>coincidence

Maybe that too....

@Jegelewicz I think I just revived it by opening  Manage Scheduled Tasks , to which you should have access. If that doesn't work you might try pausing and un-pausing the component loader task.

**Comment by jessicatir** [comment]
@dustymc I put my stuff back into the Record Event Loader.
