### ISSUE TITLE
UMZM:Egg - Create Collection

### ISSUE THREAD

**Issue by adhornsby** [ArctosDB/arctos#7152]
I can't remember if this is the right place to put this request, but I assume someone will usher it where it needs to go!

Requesting UMZM:Egg for egg and nest collection, with integer catalog numbers.  There will be no data to migrate, it will all be entered manually starting from 1.

**Comment by Jegelewicz** [comment]
Moved to https://github.com/ArctosDB/new-collections/issues/737

**Comment by adhornsby** [comment]
Confirming UMZM:Egg (not UWZM:Egg !)

**Comment by Jegelewicz** [comment]
@adhornsby thanks for checking my spelling! - Suggestion updated.

**Comment by Jegelewicz** [comment]
@adhornsby here is the collection request - please review it and change anything that needs changing.

[UMZM_egg_collection_request.csv](https://github.com/ArctosDB/arctos/files/13820242/UMZM_egg_collection_request.csv)

**Comment by adhornsby** [comment]
@Jegelewicz Looks good except the first column COLLECTION_CDE should be Egg, not Bird?

**Comment by Jegelewicz** [comment]
@adhornsby thanks! How's this?
[UMZM_egg_collection_request.csv](https://github.com/ArctosDB/arctos/files/13821624/UMZM_egg_collection_request.csv)

**Comment by adhornsby** [comment]
@Jegelewicz Good!  Also, missed this the first time but it looks like institution was accidentally copied into the LINK_TO_GUID_ISSUE column.

**Comment by Jegelewicz** [comment]
Thanks! I fixed that. Ready to request it?
[UMZM_egg_collection_request.csv](https://github.com/ArctosDB/arctos/files/13822833/UMZM_egg_collection_request.csv)

**Comment by adhornsby** [comment]
@Jegelewicz Yes, ready!

**Comment by Jegelewicz** [comment]
@adhornsby UMZM:Egg has been created! Do you want a data migration project for it? At the very least, please complete the information in [manage collection](https://arctos.database.museum/Admin/Collection.cfm?guid_prefix=UMZM:Egg). Let me know if you need any help. Thanks!

**Comment by adhornsby** [comment]
Awesome, thanks @Jegelewicz !  Manage collection completed, and no data migration project needed -- straight from tag to Arctos.

**Comment by Jegelewicz** [comment]
@adhornsby nice - but you really should add a license, at least for the internal downloads.

**Comment by adhornsby** [comment]
Oops, thought I had.  License added!
