### ISSUE TITLE
Skeleton of Bird: 134079/PID14216815

### ISSUE THREAD

**Issue by IngolfHosbach** [ArctosDB/arctos#7153]
Dear Madam, dear Sir,
is it possible to get a picture of the skeleton of https://arctos.database.museum/guid/MVZ:Bird:134079/PID14216815 ?

We are working on a project about birds who are not able to fly. We would highly appreciate your efforts.

Thanks in advance!

Best regards,
Ingolf

**Comment by dustymc** [comment]
ping @ccicero @libbybeckman @mkoo
