### ISSUE TITLE
Feature Request - add link to "CSV Header Checker" on "Bulkloading Catalog Records" page

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#7183]
The [CSV Header Checker](https://arctos.database.museum/Reports/csvChecker.cfm) is a nifty tool for checking your column headers when bulkloading records. Currently it's linked only via Tools Directory/Services.  It would be handy to add a link directly to the [Bulkloading Catalog Records](https://arctos.database.museum/Bulkloader/BulkloadSpecimens.cfm) page. (NOTE: I had to call @mkoo and ask where this tool was as it wasn't clear to me when I was bulkloading records).

**Comment by Jegelewicz** [comment]
This sounds like a perfectly fine idea.

**Comment by dustymc** [comment]
Alternative proposal: https://handbook.arctosdb.org/documentation/bulkloader.html is already linked from the text of https://arctos.database.museum/Bulkloader/BulkloadSpecimens.cfm, and https://handbook.arctosdb.org/how_to/How-to-Bulkload-Specimen-Data.html is linked as page help. Suggest we merge those, sync the links, and add some sort of 'handy tools' section from which the header checker can be linked.

https://docs.google.com/spreadsheets/d/1VbNC3k17WAHMum_qD5UYoXxUUWwXXh5gZSM5vfGvRzU/edit#gid=529334279 should probably be added to the mix as well. I had to go to [Bulkloader Builder](https://arctos.database.museum/Bulkloader/bulkloaderBuilder.cfm) to find it - another handy link.

I can also/instead just add the link as requested, but I think there's a more accessible and easier to maintain option available.

**Comment by Jegelewicz** [comment]
> Suggest we merge those, sync the links, and add some sort of 'handy tools' section from which the header checker can be linked.

https://handbook.arctosdb.org/how_to/How-to-Bulkload-Specimen-Data.html is linked at the bottom of https://handbook.arctosdb.org/documentation/bulkloader.html, so in a way they are merged?

Only the documentation has a huge "you shall not pass" that probably discourages anyone from getting to the links at the bottom. I am happy to get rid of the stuff that is no longer useful in documentation to make that better.

Still - people clearly DO NOT EVER click to the documentation, so direct links to tools is probably a good idea.

**Comment by dustymc** [comment]
>happy to get rid of 

Please and thanks!

>so in a way they are merged

I've become a pretty big fan of fewer THINGs, but whatever.

> people clearly DO NOT EVER click to the documentation,

Meh, horses and water and such, and I have no inclination to hold anyone's head under until they drink. There's a consistent place for page help available to every page in Arctos; once you've found one you've found them all. Being inconsistent is being less accessible.

**Comment by dustymc** [comment]
Updated documentation, page help, inline links, calling this next release (which went out about 2 minutes ago).

@Jegelewicz @ewommack has anyone done a newsletter-er-sumthin article(unannotated screenshot?!) on page help links, or does everyone already know they're there (or waiting for a request to be there) for every page?

<img width="442" alt="Screenshot 2024-01-09 at 19 29 46" src="https://github.com/ArctosDB/arctos/assets/5720791/9ecc028f-73d8-431e-a218-867721e2087e">

**Comment by Jegelewicz** [comment]
I added it to the announcements (to record) in the next AWG.

**Comment by ewommack** [comment]
If we record it @Jegelewicz we could make it into a link to access from the Newsletter too? "Hey check out these handy recordings from demo time at AWG meetings? Latest one took a look at the Page Help link."

**Comment by ewommack** [comment]
I added to a brief newsletter article about coming to the AWG meeting to get free demos: https://github.com/ArctosDB/newsletter/issues/260
