### ISSUE TITLE
Code Table Request - reconsider "content" parts

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#7186]
### Goal
_Describe what you're trying to accomplish. This is the only necessary step to start this process. The Committee is available to assist with all other steps. Please clearly indicate any uncertainty or desired guidance if you proceed beyond this step._

Avoid the expansion of part names with the addition of every possible part contents there might be.

### Context
_Describe why this new value is necessary and existing values are not._

> The part attribute "sub-parts" mentioned in https://github.com/ArctosDB/arctos/issues/3654 (paired with part 'contents' or something) might be a more robust solution

Before reading that linked issue, I envisioned a new part = content (everything that is contained within something) that would be a subpart of ventriculus, or stomach, or whatever. But the issue suggests the part would be ventriculus or whatever with some attribute = content to tell users that this isn't actually a ventriculus, but it's content. I am not sure that would make sense to (or even be noticed by) external users and Carla would be getting requests to use gizzards when all she had were the contents. Still, this is how we are handling reproductions, so it would be consistent in that respect.

I have always been a fan of using the subsample.

> part = ventriculus, disposition = used up
> > part (subsample of ventriculus) = content, disposition = in collection

or they could both be in collection or whatever given the actual circumstance. Each separate part could be loaned and information about it recorded as available. This provides a clear path to what is available, how it came to be, and what gets done with it later.

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/arctos/issues/7184#issuecomment-1878818997_
            

### Table
_Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table or value. This may involve multiple tables and will control datatype for Attributes. OtherID requests require BaseURL (and example) or explanation. Please ask for assistance if unsure._

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name

### Proposed Value
_Proposed new value. This should be clear and compatible with similar values in the relevant table and across Arctos._

contents

### Proposed Definition
_Clear, complete, non-collection-type-specific **functional** definition of the value. Avoid discipline-specific terminology if possible, include parenthetically if unavoidable._

The substance or objects collected from within the parent part.

### Changes to current part names

The following part names would be removed and changes to affected records would be:

current part name | new parent part name | parent part name disposition 
 -- | -- | -- 
bill content [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#bill_content) | bill | 
cheek content [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#cheek_content) | cheek pouch | 
crop content [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#crop_content) | crop | 
egg content [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#egg_content) | egg | 
hindgut content [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#hindgut_content) | gastrointestinal tract | 
stomach content [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#stomach_content) | stomach | 
stomach plus crop content [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#stomach_plus_crop_content) | stomach and crop (two parts) | 
stomach plus stomach content [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#stomach_plus_stomach_content) | stomach | in collection 
ventriculus content | ventriculus | 

### Collection type
_Some code tables contain collection-type-specific values. ``collection_cde`` may be found from https://arctos.database.museum/home.cfm_

All

#### Attribute data type
_If the request is for an attribute, what values will be allowed?
free-text, categorical, or number+units depending upon the attribute (TBA)_

N/A

#### Attribute controlled values
_If the values are categorical (to be controlled by a code table), add a link to the appropriate code table. If a new table or set of values is needed, please elaborate._

N/A

#### Attribute units
_if numerical values should be accompanied by units, provide a link to the appropriate units table._

N/A

#### Part preservation attribute affect on "tissueness"
_if a new part preservation is requested, please add the affect it would have on "tissueness": No Influence, Allows, or Denies_

N/A

### Priority
_Please describe the urgency and/or choose a priority-label to the right. You should expect a response within two working days, and may utilize [Arctos Contacts](https://arctosdb.org/contacts/) if you feel response is lacking._

### Example Data
_Requests with clarifying sample data are generally much easier to understand and prioritize. Please attach or link to any representative data, in any form or format, which might help clarify the request._

### Available for Public View
_Most data are by default publicly available. Describe any necessary access restrictions._

yes

### Helpful Actions

- [x] Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

- [x] Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

@ArctosDB/arctos-code-table-administrators 

## Approval
_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [ ] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [ ] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection
_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation
_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

- [ ] Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

- [ ] Add or revise the code table term/definition as described above. Ensure the URL of this Issue is included in the definition. URLs should be included *_as text_*, separated by spaced pipes. Do not include HTML in definitions.

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by dustymc** [comment]
```
I have always been a fan of using the subsample.

   * part = ventriculus, disposition = used up
       * part (subsample of ventriculus) = content, disposition = in collection
```

This is a very robust approach which would work equally well for parasites, lesions, etc., etc.

**Comment by Jegelewicz** [comment]
I recommend it whenever I can, but it is hard to get people on board, especially if the originating part is no longer (or never was) in the collection. It is up-front work that makes data entry more complicated that can pay off in droves over the long haul, but people are most concerned with NOW and that makes me sad.

The addition of stable part identifiers might make things easier, but still doesn't help when both parts are to be added at once - especially through the bulkloader. If we could find a way to make that easier, maybe more people would embrace this?

**Comment by dustymc** [comment]
>more complicated 

Yea, sorta, but it's also a simplification - one way of doing more things is probably better accessibility (for enter-ers and researchers).

>stable part identifiers

Still looks entirely like a social problem from here.

>unique to Arctos

"Just UI" - eg we could mash a bunch of parts into one for whatever purpose ("part: bird-->guts-->gizzard-->contents-->insect bits"), just need some sort of clear direction. (Or: There's an API, do what you want.)

>through the bulkloader

Something like the above could work the other way, and the API comments are particularly relevant. (Implementing something that works for your parasite-or-whatever collection is likely MUCH simpler than implementing something that has to work at the scale of Arctos.)

**Comment by dustymc** [comment]
Here's some data:

```

select 
guid,
guid_prefix,
specimen_part.part_name, 
parent_part_name.part_name as parent_part_name
from specimen_part
inner join specimen_part parent_part_name on specimen_part.collection_object_id=parent_part_name.sampled_from_obj_id
inner join flat on specimen_part.derived_from_cat_item=flat.collection_object_id
where specimen_part.part_name like '%content%'
;
      guid       | guid_prefix |    part_name    | parent_part_name 
-----------------+-------------+-----------------+------------------
 MSB:Bird:39254  | MSB:Bird    | stomach content | stomach content
 MVZ:Herp:193500 | MVZ:Herp    | stomach content | stomach content
```

Assuming that is (or might be) "scooped a bit of this out for loan" and not "clicked all the buttons because they're there," that's possibly a fatal blow to the evolved proposal. (The initially-proposed "part sub part" attribute does not have the same limitations, but has some oddities of its own.)
