### ISSUE TITLE
image loader is broken

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ArctosDB/arctos#719]
```
What steps will reproduce the problem?
1. upload ZIP file
2. get the media bulkloader template
3. it won't load


rebuild template-builder
```

Original issue reported on code.google.com by `dust...@gmail.com` on 11 Dec 2014 at 2:15

**Comment by dustymc** [comment]
Discuss with iPlant and/or TACC, explore HTML5 image loading options; probably best to start from ground zero.

**Comment by dustymc** [comment]
iPlant has nothing useful; rebuilt the ZIP loader, added a specimen-media loader
