### ISSUE TITLE
Arctos Offline - WED 10 January at 5 Pacific/ 7 pm Central (tomorrow!)

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#7218]
On Wednesday 10 January at 5 Pacific/ 7 pm Central, Arctos will be offline for maintenance and backup for at least 3 hours; please save your work and plan accordingly. Apologies for any inconvenience. 

## Communication before/during outage
- [x] Pin this issue
- [x] Banner updated @jegelewicz @mkoo
- [x] Email sent to AWG  
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [x] Unpin this issue
- [x] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG 
- [ ] Tweet @lin-fred (@mkoo backup)
- [x] Close this issue when above are complete

**Comment by ewommack** [comment]
Sent an email right now, and scheduled one to go out tomorrow at 0800 MT

**Comment by dustymc** [comment]
Arctos is back up.

**Comment by mkoo** [comment]
Great! I'll check it out now
