### ISSUE TITLE
IP address blocking - risk for a grant proposal?

### ISSUE THREAD

**Issue by ufarrell** [ArctosDB/arctos#7236]
Hi @dustymc - I'm writing a grant, and a draft will be submitted to our Provost tomorrow...if I include some Arctos links its extremely important that she doesn't get an IP-address-blocked message. Is there any way to be sure it won't happen? In this case I have no idea how to send information about the likely IP in advance. If there's a risk, I'll leave Arctos specimens out of the proposal.

**Comment by dustymc** [comment]
>any way to be sure it won't happen? 

If you know an IP range, then sure I can make sure it's happy. If the user might come in from some super-shady VPN or something then not so much....

@mkoo this seems like something we need - uhh - something?? - about??

**Comment by ufarrell** [comment]
Campus hopefully doesn't count as shady, but college IPs are 134.226.xxx.xxx for what its worth. I guess the "Heritage Council" won't be too shady either...but the last blocking issue was at a conference in a government building so I'm not totally sure I can trust our national institutions.

**Comment by mkoo** [comment]
Well we can safelist that IP range (so thanks) but as Dusty said there are no guarantees where the reviewers will be accessing the links from. However we do have a mechanism for users to unblock themselves if they find themselves in that position. Now that we know you've got a grant being reviewed we'll definitely be on top of the IP requests-- thanks and good luck!
