### ISSUE TITLE
legacy Arctos-reporter to be removed Monday 1/15

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#7237]
Hello all, Due to ongoing security concerns, the old legacy Arctos-reporter must be taken down as soon as possible. Thus, this Monday 1/15 the link to [the legacy Reporter](https://arctos.database.museum/Reports/report_printer.cfm) will be removed from Arctos. Users who have not had all their reports migrated to the [current Reporter ](https://arctos.database.museum/Reports/reporter.cfm) can contact us (e.g., file an issue). If you are in the midst of migration to the current report system and need to polish, finalize or otherwise have reports or labels that need work, please let us know too. We will contact the collections which appear to not have created reports in the current system. We will prioritize any report/ label issues.
Thanks and apologies for the short notice from TACC.
 - Arctos Officers

To Do list:
## Communication before/after change
- [x] Pin this issue
- [x] Banner updated @jegelewicz @mkoo
- [x] Email sent to AWG  @ewommack 

- [x] Unpin this issue after 1/16
- [x] Banner updated after 1/16 @jegelewicz @mkoo

**Comment by ewommack** [comment]
There have been no objection or suggestions to the text so I'm sending it now!

**Comment by ewommack** [comment]
Email sent and I also have one scheduled to go out on Monday after the link has been taken down.

**Comment by mkoo** [comment]
@dustymc please update this page: https://arctos.database.museum/Reports/report_printer.cfm
it still has a link to the firewalled legacy printer server

**Comment by dustymc** [comment]
Done and updated directory - needs confirmed after cache has cleared in a couple hours.
