### ISSUE TITLE
BYU aggregate wet collection labels

### ISSUE THREAD

**Issue by byuherpetology** [ArctosDB/arctos#7239]
Status:

* BYU_aggregate_wet_labels
    * Status: Modified SQL awaiting approval
    * Report: https://arctos.database.museum/Reports/reporter.cfm?action=edit&report_id=144
    * Data: https://arctos.database.museum/search.cfm?guid_prefix=BYU%3AHerp&scientific_name=sphenomorphus%20simus&verbatim_date=2000&any_geog=wara%20sera
    * Layout: https://github.com/ArctosDB/arctos/issues/7239#issuecomment-1887928415
    * Special: mess with ``<cfset numCatNumPerRow=3>`` to set "a limit on the cat numbers that fit on a single label"
--------------
Original

I would like to create a label for wet collection jars that contain multiple specimens, so I can have multiple museum numbers listed on a single label.

We often combine specimens collected at the same locality, or even from the same county, into a single jar. I would like to have a single label for all the search results from an arctos query. I had a label for this on the old .cfr based reporter (BYU_Herp_CCounty_Large - is an example) and would like to create something similar on the new reporter but do not know how.

Thanks

**Comment by dustymc** [comment]
Can you confirm that report? The SQL definitely doesn't do what I think you're asking for!

```
select * from flat where collection_object_id IN (#collection_object_id#)
```

**Comment by byuherpetology** [comment]
It looks like UCM is trying to do something similar https://github.com/ArctosDB/arctos/issues/5266

**Comment by byuherpetology** [comment]
The old label I was using just listed a single locality (only what was shared between all specimens, so typically just the country, state and county)  with multiple specimen numbers. I am ok with this solution or the way ECM was doing it

**Comment by dustymc** [comment]
Ah thanks.

I can print as a start to the SQL and we can adjust as needed. (What's there is wildly expensive, will find a way to melt something, and mostly isn't going to be useful.)

The UCM label is based off of a container. Your old label is based off of records (eg a search result). Which should this use?

**Comment by byuherpetology** [comment]
Based off of records. I would like to be able to print a label for all search results. Basically, I want to use the label I have in the new reporter, but have all of the catalog numbers in the search results print on the same label.

**Comment by dustymc** [comment]
Give BYU_aggregate_wet_labels a try, let me know what I didn't understand. It should just output some lists, each containing unique sorted values from the input query.

**Comment by byuherpetology** [comment]
I think that will do it. It doesn't have all of the fields that I want but presumably I can fix that with the label design.

Is there a way to specify that only the data that is shared between all records will be included in the report? If this is an expensive prospect, then it isn't necessary, I can control for this with the search specifications and label design

**Comment by dustymc** [comment]
> all of the fields 

Just let me know what's missing.

> only the data that is shared between all records will be included in the report? 

So for example if there are three records and all of them have state=Alabama then Alabama, or in any other situation no state at all?

**Comment by byuherpetology** [comment]
> > only the data that is shared between all records will be included in the report?
> 
> So for example if there are three records and all of them have state=Alabama then Alabama, or in any other situation no state at all?

Right. So if all records have the identical locality then the entire locality will print. If all records are from the same county in Alabama, then U.S, Alabama, County would print but not the specific localities because they differ.

**Comment by dustymc** [comment]
Reload

**Comment by byuherpetology** [comment]
<img width="550" alt="Screenshot 2024-01-11 at 12 41 15 PM" src="https://github.com/ArctosDB/arctos/assets/48566837/1b16106c-1efa-43ce-acfd-f8fd54c42d5a">

I am having trouble with international localities

**Comment by dustymc** [comment]
You can...

<img width="345" alt="Screenshot 2024-01-11 at 11 44 10" src="https://github.com/ArctosDB/arctos/assets/5720791/fd9ddcf7-9e28-4858-b99a-3f4d3f58b40e">

... and assuming I know how to spell skink, get something like 

https://arctos.database.museum/search.cfm?guid_prefix=BYU%3AHerp&scientific_name=sphenomorphus%20simus&verbatim_date=2000&any_geog=wara%20sera

which gets us all on the same page. 

>slight difference in the collector and specific localities

Oh - nope, bad assumptions on my part. I dumped the raw data out (easier to check for that sort of thing, can go away whenever it's no longer useful) and rewrote those in a way that works with commas in the data. Reload and lemme know what's still wonky.

**Comment by byuherpetology** [comment]
Looks like this is working for US and international localities. 

Now, how do I make it pretty without breaking anything?

**Comment by dustymc** [comment]
>make it pretty

Just let @lkvoong  and @mkoo know what you want. I believe they accept pictures, screenshots, descriptions, anything involving crayons, .... 

Search is https://arctos.database.museum/search.cfm?guid_prefix=BYU%3AHerp&scientific_name=sphenomorphus%20simus&verbatim_date=2000&any_geog=wara%20sera

Report is BYU_aggregate_wet_labels

**Comment by byuherpetology** [comment]
I cloned the report and attempted to make it pretty, but I think I broke something, it is back to printing individual labels for each specimen. 
 @mkoo and/or @lkvoong Here is my single label 

<img width="415" alt="Screenshot 2024-01-11 at 1 30 19 PM" src="https://github.com/ArctosDB/arctos/assets/48566837/f76d8333-d991-4198-a8e4-231d3cc74ba9">
 I would like this only after the GUID, BYU:Herp:
a list of cat #'s in columns ( as many as will fit with the width).

Then I think we will need a limit on the cat numbers that fit on a single label, and have the rest printed on a second label. 

Let me know if that makes sense. I will keep messing with my cloned report and see if I can figure it out

**Comment by byuherpetology** [comment]
@dustymc  
I am having trouble with 
<cfset numCatNumPerRow=3> 
I may have changed something that messed it up, but if there are fewer catnums in the query than the number I have specified as the max per row/label, then it does not include them. For example
https://arctos.database.museum/search.cfm?guid_prefix=BYU%3AHerp&scientific_name=lygisaurus&any_geog=wara%20sera 
If I have the numcatnumperrow set to 35 then nothing shows up on this report. If it is set to 20, then I get a label with the first 20 but the last 14 results are missing.

Also, I am trying to format the catnumbers into columns, and this code seems to keep all numbers in the first column, but maybe that is just me doing something wrong with the HTML or CSS.

**Comment by byuherpetology** [comment]
That is working again. I will keep all of my changes in my cloned version, I am sure I messed it up before. I was trying to put the cat numbers in multiple columns but maybe I'll be happy with the way it is. Thanks for the cleanup.

**Comment by dustymc** [comment]
>cat numbers in multiple columns

I don't know what that means, if you can elaborate (pictures are nice...) I can probably help.

>changes

Backup in whatever way makes you happy (but please clean up any leftovers when you're done), here's one way:


<img width="184" alt="Screenshot 2024-01-29 at 09 38 27" src="https://github.com/ArctosDB/arctos/assets/5720791/163646b4-1f7f-4a2a-bce7-5376b2021f92">

and then oops....

<img width="220" alt="Screenshot 2024-01-29 at 09 39 17" src="https://github.com/ArctosDB/arctos/assets/5720791/33149ac2-1a8a-4304-a239-38144e4faa1b">


and then....
<img width="528" alt="Screenshot 2024-01-29 at 09 40 08" src="https://github.com/ArctosDB/arctos/assets/5720791/72eb82f2-d513-4987-904e-df835c9d7c0d">

and 


<img width="501" alt="Screenshot 2024-01-29 at 09 40 50" src="https://github.com/ArctosDB/arctos/assets/5720791/79b949f8-5ed7-45cb-be90-7aa6f173cc4e">

and you should have your before-the-oops report. Your reports as CSV  are <10K, I can fit close to a billion backups on my little laptop.....

**Comment by byuherpetology** [comment]
Thanks Dusty
![IMG_7957](https://github.com/ArctosDB/arctos/assets/48566837/fe1f4918-a49d-411d-81f2-41b344a45e0b)
This is a label from the previous reporter - I was going for something like that, only I was trying to put the GUID on the first line and then just catnumbs in the columns below that.  The columns just make the numbers easier to read, but I would like to include as many numbers/label as  I can so if we need to do a straight list that's ok too.

One last coding question, is there an easy way to change the county so that if there is no county (many international localities), it is left off the label?

**Comment by dustymc** [comment]
Check out tempjunk https://arctos.database.museum/Reports/reporter.cfm?action=edit&report_id=159

I've got the catnums repeating
<img width="360" alt="Screenshot 2024-01-29 at 10 13 37" src="https://github.com/ArctosDB/arctos/assets/5720791/9ce07676-9a02-47d8-86ee-5b0ef2df2d08">

check out the css at the top of the template, not sure which of those approaches will work best (probably grid??). 

I also wrapped country in some code:

```
<cfif len(country) gt 0>#country#: </cfif>#state_prov#: #county#; #spec_locality#
```

I'll leave the code/explanations here too, I'll delete that report at some point.

css generally works on divs so instead of just dumping the list with ``#cat_num#`` I change the label to put each element in a div

```

<div class="innner_catnum_list">
	<cfloop list="#cat_num#" index="i">
		<div>#i#</div>
	</cfloop>
</div>
```

and then use CSS to either make that into a flexbox (in which case your browser can figure out things like column count):

```
.innner_catnum_list{
	display: flex;
	flex-wrap: wrap;
	justify-content: space-between;

}
```

or a grid (in which case you may specify column count)

```
.innner_catnum_list{
	display: grid;
	/* million ways to do this, this one is maybe easy to read/understand/adjust and efficiency isn't important here */
	grid-template-columns: 1fr 1fr 1fr 1fr;
}
```

**Comment by byuherpetology** [comment]
Beautiful, thank you. I will make many backups!

**Comment by byuherpetology** [comment]
I am happy with this label. Let me save a csv of the tempjunk file and I can delete it.
