### ISSUE TITLE
[ geography request ] No Lithuania

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#7248]
# Carefully read the documentation at https://handbook.arctosdb.org/documentation/higher-geography.html before submitting a request.

### Explain what geography needs created.

Tried searching higher geography (lots of fields) for Lithuania and nothing was found, but it's a real place:

https://en.wikipedia.org/wiki/Lithuania

Can that be fixed?

**Comment by Jegelewicz** [comment]
https://gadm.org/maps/LTU.html

**Comment by dustymc** [comment]
Please review:

[temp_pre_geog.csv](https://github.com/ArctosDB/arctos/files/13921014/temp_pre_geog.csv)

I think it doesn't quite line up with current/wiki/GADM's own maps, but maybe that's just me getting lost. Some sort of [collaboration](https://github.com/ArctosDB/arctos/issues/5597) would make that a lot more approachable. @mkoo 

I was able to load to test, so maybe the [mysterious problems](https://github.com/ArctosDB/arctos/issues/6521) have somehow cured themselves?!

I had to make some changes with the loader, so this will have to wait for next release to go to production.

**Comment by Jegelewicz** [comment]
So - this is cool: eez_land_union::Lithuania\|Lithuania\|Lithuania\|Union EEZ and country

But the hg is Lithuania: Lithuania, how would anyone know to use that? Are there more of these that nobody is seeing? And how does this relate to https://github.com/ArctosDB/data-migration/issues/1549#issuecomment-1887644909

> I got an "invalid higher_geog" bounce on several localities with HIGHER_GEOG of Madagascar, Finland, and Nepal. When I search for those in Arctos it seems that those countries all require a continent (e.g., Nepal: https://arctos.database.museum/place.cfm?action=detail&locality_id=1119227). Is this correct? Is there a reason why some countries require continent, and others do not?

**Comment by dustymc** [comment]
>this is cool:

That's a mistake/leftover (and why I post CSV and ask for review) - csv replaced, thanks!

> relate to 

https://github.com/ArctosDB/arctos/issues/5597 is the relevant bit - someone needs to write a proposal.

**Comment by mkoo** [comment]
that looks like it works-- looks like Derek requests at last the first entry in your CSV
 you need the wikipedia links too (it wasnt in the csv)

will try to reconnect with you know who re: gadm....

**Comment by dustymc** [comment]
>works

Sure hope so, this postgres thing has been crazy, will find out as soon as I can. (I've got some pretty deep stuff apart at the minute, mid/late next week I hope.)

>first entry

I've been making/refreshing entire countries when I do anything, doesn't seem to be much more work but adds a lot of consistency to the data.

>wikipedia links

<img width="465" alt="Screenshot 2024-01-12 at 13 22 06" src="https://github.com/ArctosDB/arctos/assets/5720791/68f8399b-f6a2-4534-a104-2b6b2aa3474f">

??

>reconnect

yay!
