### ISSUE TITLE
UWBM:Mamm Migrating reports from Legacy reporter to new Reporter

### ISSUE THREAD

**Issue by jebrad** [ArctosDB/arctos#7267]
Hello - I believe I had a couple reports on the Legacy Reporter.  However I cannot view the legacy reporter (I will paste the first lines of that error message below, although fixing that seems pointless right now).

Can someone please find and migrate any reports that were created by me jebrad or have a label UWBM:Mamm ??  Or at least do that for anything I have used in the past year?

thank you!

(Here is error message when I try the link to the legacy reporter, I get to that link by following the one from the email notifying us of the Legacy reporter issues -

<font style="COLOR: black; FONT: 8pt/11pt verdana">
Error Executing Database Query.
--
The authentication type 10 is not supported. Check that you  have configured the pg_hba.conf file to include the client's IP address  or subnet, and that it is using an authentication scheme supported by  the driver.
 
The error occurred in /usr/local/httpd/htdocs/internal/reporter/report_printer.cfm: line 81          			         					Called from /usr/local/httpd/htdocs/internal/reporter/report_printer.cfm: line 2         				         					Called from /usr/local/httpd/htdocs/internal/reporter/report_printer.cfm: line 1
79 :     <cfdirectory action="list" directory="#Application.webDirectory#/reporter/templates" name="dirDump" sort="name ASC"> 80 : 	<cfquery name="e" datasource="user_login" username="#ua.username#" password="#decrypt(ua.epw,ua.skey)#"> 81 : 	    select * from cf_report_sql where report_template in ( #QuotedValueList(dirDump.name)# ) order by report_name 82 : 	</cfquery> 83 :

</font>

**Comment by mkoo** [comment]
HI Jeff, yes you do have a bunch of reports that were all built in the last year on the old server:
<img width="1513" alt="Screenshot 2024-01-12 at 13 28 04" src="https://github.com/ArctosDB/arctos/assets/2523089/d12798ca-a18b-4725-bc6d-49dcb92c1c0c">

From this snapshot can you list which ones are your used reports that are NOT on the current system (there are several copies sometimes)? 

Here's what you have on the current system (oh sorry I see that UWBM:Mamm only has the first two)
![Firefox_Screenshot_2024-01-12T21-54-45 862Z](https://github.com/ArctosDB/arctos/assets/2523089/7a43049c-c6f7-4637-b2a7-2d6b426c9e2a)

With the list of needed reports, can you share any pdf examples of them wtih me (can also just email mkoo [at] berkeley.edu)?
thanks

**Comment by Jegelewicz** [comment]
@jebrad your reports summarized between old and new

OLD Report Template | Last Access | New Report 
-- | -- | --
uwbm_herp_
UW_Burke_mammal_label.cfr | 2023-06-06 (-190 days) | uwbm_mamm_part_download
tiss_loan_packing_list.cfr | 2021-09-21 (-813 days) |  
uwbm_herp_tiss_loan_packing_list.cfr | 2023-02-03 (-312 days) |  
uwbm_mammal_box.cfr | 2023-06-06 (-190 days) | UWBM medium label
uwbm_mammal_box.cfr | 2023-06-06 (-190 days) | UWBM_mammal_box_large_csv
uwbm_mammal_tiss_vial.cfr | 2021-11-10 (-763 days) |  
uwbm_mammal_tiss_vial.cfr | 2023-03-02 (-285 days) |  
uwbm_tiss_loan_list.cfr | 2023-09-20 (-84 days) |  
uwbm_tiss_vial.cfr | 2021-07-14 (-882 days) |  
uwbm_tiss_vial.cfr | 2023-03-03 (-284 days) |  
uwbm_tiss_vial.cfr | 2023-09-20 (-84 days) |

**Comment by jebrad** [comment]
OK thanks for this help.  

I am a little confused about the top line of that table above: I was using this report in June "UWBM_mamm_label_csv " - see Issue "[ArctosDB/data-migration] new skeleton labels for UWBM mammals (Issue #1680)"  - but I don't think it was copied to the new reporter.  The one you have listed on that top line as New Report: "uwbm_mamm_part_download" is, I think, the one that Dusty made for me in November as part of issue "Need help getting stuff from search for loan requests (Issue #6760)"

So I think I still need migration of the report that generated UWBM_mamm_label_csv.

AND - I totally forgot about the GRC and their tissue reports.  Can you please also migrate everything that has "UWBM" and "tiss" in the report name?  We are not going to get any replies from our GRC people over the weekend, but they are probably counting on those reports not disappearing even if they haven't used them in a long time.

**Comment by Jegelewicz** [comment]
@jebrad maybe we needs to talk about the mammal label - don't you have what you need right now to print the mammal labels you want? I thought we had worked all of that out in https://github.com/ArctosDB/data-migration/issues/1680

Also, rather than try to recreate all of those tissue labels - maybe we can get a separate issued filed for whatever it is they WANT? None of them have been used in about 3 months and I'd rather create one label that they will use than five, none of which meet their needs.

**Comment by jebrad** [comment]
OK I didn't realize that migrating the reports meant you had to actually recreate things, I assumed it was more drag and drop.  Can we at least save the old tissue report files, instead of creating new ones for the new Reporter, so they (or you) have something to build from?  Rather than all their old things disappearing?

You are right that I was printing what I needed, but I thought I was doing some of it from the Legacy reporter.   I have been ignoring most of my printing needs because of other more pressing issues, so sorry for my confusion.  Also I realize that if my stuff on the Legacy reporter disappears, it probably means I needed to re-do it anyway.

**Comment by Jegelewicz** [comment]
Report Template | Handler Name | Last Access
-- | -- | --
uwbm_tiss_vial.cfr | UWBM_Herp_tiss_vial | 2023-09-20 (-114 days)

![image](https://github.com/ArctosDB/arctos/assets/5725767/ba8c0dc1-c3ff-4a48-9d3f-57b069858a13)

## SQL
select
		flat.cat_num,
		flat.scientific_name,
		flat.country,
		flat.state_prov,
		flat.sex,
		concatsingleotherid(flat.collection_object_id,'collector number') other_ids
		FROM
			flat
		where
			flat.collection_object_id IN (#collection_object_id#)
order by cat_num

**Comment by Jegelewicz** [comment]
Report Template | Handler Name | Last Access
-- | -- | -- 
uwbm_mammal_tiss_vial.cfr | Clone_Of_UWBM_mammal_tiss_vial_1677782 | 2023-03-02 (-315 days) 

![image](https://github.com/ArctosDB/arctos/assets/5725767/c6fd1968-8a7d-41a2-aac5-5b8f103b4700)

##SQL

select
		flat.cat_num,
		flat.scientific_name,
		flat.country,
		flat.state_prov,
		flat.sex,
		ConcatAttributevalue(flat.collection_object_id,'verbatim collector') as other_ids
		FROM
			flat
		where
			flat.collection_object_id IN (#collection_object_id#)

order by cat_num

**Comment by Jegelewicz** [comment]
Also, I am guessing Peter will need this.

Report Template | Handler Name | Last Access
-- | -- | -- 
uwbm_herp_tiss_loan_packing_list.cfr | Clone_Of_UWBM_Herp_tiss_loan_packing_l | 2023-02-03 (-342 days)

![image](https://github.com/ArctosDB/arctos/assets/5725767/ec14bd35-14d0-458b-beb5-8264a1b82bb1)

##SQL
select
		flat.cat_num,
		flat.scientific_name,
                flat.country,
		concatsingleotherid(flat.collection_object_id,'collector number') other_ids
		FROM
			flat
		where
			flat.collection_object_id IN (#collection_object_id#)
order by other_ids

**Comment by Jegelewicz** [comment]
I don't know why all the clones and weird copies are in the old reporter - they appear to be exactly the same. I think these three are the ones the might need to be recreated in the new reporter, but let's make sure they are what people actually need before we waste any time.

**Comment by Jegelewicz** [comment]
After visiting with Jeff - I think we can close this for now. If anything new is needed, we can reopen or start from scratch.
