### ISSUE TITLE
Arctos Offline - Friday maintenance reboot required at 12 Pacific/ 2 Central

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#7269]
## Planned Outage
 - January 19, 2024 at 12 Pacific/ 2 pm Central

Arctos will be unavailable for a maintenance reboot this Friday starting at 12 Pacific/ 2 pm Central for approximately 2 hours. Please plan accordingly and make sure you save your work. Apologies for any inconvenience!

To Do:
- [x] Pin this issue
- [x] Banner updated @jegelewicz @mkoo
- [x] Email sent to AWG  @ewommack 
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [x] Unpin this issue
- [x] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by ewommack** [comment]
I've got emails going out on Monday, Wednesday, and Friday. That should hopefully catch everyone around the holiday in the US in case they are celebrating it.

**Comment by dustymc** [comment]
Arctos is back up.
