### ISSUE TITLE
data entry: multiple identifications

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ArctosDB/arctos#727]
```
Rebuild the identification bulkloader to deal with GUIDs and UUIDs; extend the 
data entry screen to write to the identification bulkloader.

(for DDS)
```

Original issue reported on code.google.com by `dust...@gmail.com` on 7 Apr 2015 at 6:40

**Comment by ccicero** [comment]
Issue is how to deal with multiple IDs in data entry - both individual form and bulkloader. When a specimen comes back from the field or is prepped as salvage, it's often ID'd using 'gross morphology' (previously 'field') but then another ID (geographic distribution ---> subspecies) is added when it's cataloged. We need a way to be able to enter both of these IDs and their respective 'nature of ID' at the time of cataloging.

**Comment by dustymc** [comment]
There's an identification bulkloader; this would just allow the data entry app to write to it, like it can otherIDs and specimen events and etc. You'd need to push the extra IDs directly to the ID bulkloader when not using the UI.

https://github.com/ArctosDB/arctos/issues/2178 might make everything a lot more flexible by normalizing apps.

**Comment by dustymc** [comment]
It makes no sense to implement this then immediately redo it, and the current approach has caused a lot of issues; https://github.com/ArctosDB/arctos/issues/2562 needs to come first, then this can be the model for broader implementation.

**Comment by dustymc** [comment]
done
