### ISSUE TITLE
Meta-Issue: Backups audits etc

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ArctosDB/arctos#728]
```
What steps will reproduce the problem?
1. see giant email thread of 2015-02-20 (Arctos Contact)
2. figure out a sustainable plan for backups/rollbacks/audits/etc.

This is a social issue which needs addressed by the Arctos AC and SC. Whatever 
we do should be clearly documented.

This is becoming a potentially critical situation which needs addressed BEFORE 
we run out of resources in some catastrophic manner.

```

Original issue reported on code.google.com by `dust...@gmail.com` on 8 Apr 2015 at 4:11
- Blocking: #579

**Comment by dustymc** [comment]
We got more disk, this isn't currently an urgent problem, dropping priority. It would still be very useful to develop a formal retention plan.

**Comment by dustymc** [comment]
This has become an issue again, and is going to cause problems for #1087. In short:

>We're currently logging everything, forever, which takes more disk than we have. What should we do about that?

DLM suggestion: Prune the audit logs - delete everything older than (something - a month?? a year??).

**Comment by amgunderson** [comment]
What are the audit logs? We should definitely not be saving everything forever but data backups should be kept for some period of time...1 year? 5 years?

**Comment by dustymc** [comment]
Real answer: https://docs.oracle.com/cd/E11882_01/server.112/e10575/tdpsg_auditing.htm#TDPSG50513

Short(ish) answer: audit logs are a record of all user activity which affects data. (We do not audit SELECT.) Things like...

* update {table} set {stuff}={values} where {key=value}
* delete from {table} where {key=value}
* insert into {table} {data}

In theory, audit logs can be "played back" - some mashup of data (eg, a specimen record) looked like THIS, then {a bunch of relevant stuff} happened and now it looks like THAT (and so there's a bug in THAT code/some user needs training/etc.).

In practice, most versions of that pathway are beyond our tools and we'd need expensive consultants to really understand any change that involves more than a table or two. Eg "a specimen record was THERE and now it's HERE" may have involved a change to geography then moving the specimen to a locality which used that geography then moving the specimen to some other locality which uses some other geography which was then edited etc. (and similar things perhaps thousands of times by dozens of users) - there are generally VERY many pathways from THERE to HERE and few of them are straightforward. And the audit logs have been big enough that I can't use them for quite some time now, so they haven't really been useful even in providing the answers we're capable of understanding.

**Backups** are a snapshot of the data, including audit logs. "Here's everything as it was on {date}." It is possible (in theory!) to "replay" logs onto backups so, again in theory, there's no reason to keep audit logs which are included in archived backups. In reality, re-creating a pathway involving multiple backups may involve the expensive consultant needing their own expensive consultant, and implementing that much complexity in a backup strategy may well be into "we need a full-time DBA doing nothing but backups" territory. (Chris can probably address possible backup strategies; I'm not sure who could provide a less-theoretical answer regarding the realities of recovery/audit.)

**Comment by ccicero** [comment]
Let's bring this up at the next Arctos WG meeting. Better for Dusty to explain and us all to have a discussion in person.

**Comment by ccicero** [comment]
Arctos Working Group recommends quarterly schedule for maintaining audit logs locally - discussed at AWG meeting 8 May 2017.

**Comment by ccicero** [comment]
Arctos went down yesterday because of table space issue due to audit logs. It was restored today thanks to Chris Jordan extending the tablespace by a couple of GB. Per Chris' email this morning: The system tablespaces are now up to almost 200GB in size on disk. HIGH PRIORITY to implement AWG recommendation and trim logs prior to April 2017 to start quarterly schedule as recommended.

**Comment by dustymc** [comment]
arctos_audit logs are being trimmed to 90D, leaving this open with deescalated priority as a reminder to continue monitoring SYS_AUD
