### ISSUE TITLE
Arctos Down - not responding Monday 1/15/2024 2:20 PM Pacific

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#7291]
Please complete to the best of your ability.

## Unplanned Outage
 - Monday 1/15/2024 at around 2:20 PM Pacific
 - Not responding to catalog record queries

## Communication before/during outage
- [ ] Pin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG  
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by dustymc** [comment]
It's up and seems pretty happy to me.

**Comment by ccicero** [comment]
Not working for me. Three blue dots just searching and searching. Trying with just one catnum.

**Comment by cjconroy** [comment]
same for me at home. Fetching.......

**Comment by acdoll** [comment]
My searches from the main search page just spin. I am able to run queries and get data through WriteSQL.

**Comment by dustymc** [comment]
>Three blue dots just searching

Thanks, that gets me to the problem. It seems that datatables nightly release has introduced some sort of a bug, I'll ~~go cry in the corner~~ implement a workaround as soon as I can.




<img width="1705" alt="Screenshot 2024-01-15 at 14 47 51" src="https://github.com/ArctosDB/arctos/assets/5720791/ad97f5eb-84aa-4d3b-af3c-61f01dc47c85">

```
function _fnCallbackFire( settings, callbackArr, eventName, args, bubbles )
	{
		var ret = [];
	
		if ( callbackArr ) {
			ret = settings[callbackArr].slice().reverse().map( function (val) {
				return val.apply( settings.oInstance, args );
			} );
		}
	
		if ( eventName !== null) {
			var e = $.Event( eventName+'.dt' );
			var table = $(settings.nTable);
			
			// Expose the DataTables API on the event object for easy access
			e.dt = settings.api;
	
			table[bubbles ?  'trigger' : 'triggerHandler']( e, args );
	
			// If not yet attached to the document, trigger the event
			// on the body directly to sort of simulate the bubble
			if (bubbles && table.parents('body').length === 0) {
				$('body').trigger( e, args );
			}
	
			ret.push( e.result );
		}
	
		return ret;
	}
	
```

**Comment by dustymc** [comment]
Should be functional, you may need to hard reload to get the new/old library from datatables.

**Comment by acdoll** [comment]
Thanks! Seems to be working.

**Comment by ccicero** [comment]
Ditto, working now. Thanks!
