### ISSUE TITLE
Code Table Request - migrate terms from age class to life stage

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7298]
### Goal
_Describe what you're trying to accomplish. This is the only necessary step to start this process. The Committee is available to assist with all other steps. Please clearly indicate any uncertainty or desired guidance if you proceed beyond this step._

Place terms that are currently in age class in the new life stage code table.

### Context
_Describe why this new value is necessary and existing values are not._

See https://docs.google.com/spreadsheets/d/1Yv3Lx6DtSdmh0P1cSIG6zW-DnYI6VDJpOkFcgQL6F8o/edit#gid=211205961

### Table
_Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table or value. This may involve multiple tables and will control datatype for Attributes. OtherID requests require BaseURL (and example) or explanation. Please ask for assistance if unsure._

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlife_stage

### Proposed Value
_Proposed new value. This should be clear and compatible with similar values in the relevant table and across Arctos._

age class term
-- 
adult
embryo
larva
pupa
juvenile
subadult
1st instar
2nd instar
3rd instar
4th instar
5th instar

### Proposed Definition
_Clear, complete, non-collection-type-specific **functional** definition of the value. Avoid discipline-specific terminology if possible, include parenthetically if unavoidable._

life_stage | Description | UsedBy | BestFor | Search Terms | Issue URL | Documentation URL
-- | -- | -- | -- | -- | -- | --
adult | An adult is an individual that has is fully grown and has achieved mature phenotypic characteristics. \| http://rs.gbif.org/vocabulary/gbif/life_stage/adult |   |   | imago | https://github.com/ArctosDB/arctos/issues/6859 | http://rs.gbif.org/vocabulary/gbif/life_stage/adult
embryo | An embryo is a multicellular diploid eukaryote in its earliest stage of development, from the time of first cell division until birth, hatching, or germination. |   |   | subadult,juvenile,ovum,seed, egg |   | http://rs.gbif.org/vocabulary/gbif/life_stage/embryo
larva | A larva (Latin; plural larvae) is a young (juvenile) form of animal with indirect development, going through or undergoing metamorphosis (for example, insects, amphibians, or cnidarians). The larva can look completely different from the adult form, for example, a caterpillar differs from a butterfly. Larvae often have special (larval) organs which do not occur in the adult form. The larvae of some species can become pubescent and not further develop into the adult form (for example, in some newts). This is a type of neoteny. It is a misunderstanding that the larval form always reflects the group's evolutionary history. It could be the case, but often the larval stage has evolved secondarily, as in insects. In these cases the larval form might differ more from the group's common origin than the adult form. The early life stages of most fish species are considerably different from juveniles and adults of their species and are called larvae. |   |   | subadult,juvenile,larvae,tadpole,polliwog,pollywog,polliwig,polewig,polwig,planula,nauplius,zoea,nymph,caterpillar,grub,maggot,wriggler,trochophore,veliger,glochidium,ammocoete,leptocephalus,bipinnaria,caterpillar,grub,maggot |   | http://rs.gbif.org/vocabulary/gbif/life_stage/larva
pupa | A pupa is the life stage of some insects undergoing transformation between immature and mature stages. The pupal stage is found only in holometabolous insects, those that undergo a complete metamorphosis, with four life stages: egg (-> embryo), larva, pupa, and imago (-> adult). |   |   | subadult,juvenile,puppe |   | http://rs.gbif.org/vocabulary/gbif/life_stage/pupa
juvenile | A juvenile is a young individual organism (e.g. that is in its first year of life) and has not yet reached its subadult or adult form, sexual maturity or size. Generally juveniles are newly hatched or birthed and sometimes look different from the adult form, particularly in colour and lack secondary sexual characteristics, etc. In many organisms the juvenile has a different name from the adult. |   |   | subadult,seedling,eft,calf,hatchling,infant,foal,kitten,kit,chick,nymph,fawn,whelp,pup,elver,fry, nestling, fledgling, immature, metamorph |   | http://rs.gbif.org/vocabulary/gbif/life_stage/juvenile
subadult | A  subadult is an individual which lacks all the adult phenotypic characters. In birds, an individual that is fully feathered, with full body size, but is not in mature adult plumage. |   |   | immature |   |  
1st instar | The developmental stage of an arthropod between hatching and first molt. |   |   |   |   |  
2nd instar | The developmental stage of an arthropod between first and second molt. |   |   |   |   |  
3rd instar | The developmental stage of an arthropod between second and third molt. |   |   |   |   |  
4th instar | The developmental stage of an arthropod between third and fourth molt. |   |   |   |   |  
5th instar | The developmental stage of an arthropod between fourth and fifth molt. |   |   |   |   |  

### Collection type
_Some code tables contain collection-type-specific values. ``collection_cde`` may be found from https://arctos.database.museum/home.cfm_

#### Attribute data type
_If the request is for an attribute, what values will be allowed?
free-text, categorical, or number+units depending upon the attribute (TBA)_

#### Attribute controlled values
_If the values are categorical (to be controlled by a code table), add a link to the appropriate code table. If a new table or set of values is needed, please elaborate._

#### Attribute units
_if numerical values should be accompanied by units, provide a link to the appropriate units table._

#### Part preservation attribute affect on "tissueness"
_if a new part preservation is requested, please add the affect it would have on "tissueness": No Influence, Allows, or Denies_

### Priority
_Please describe the urgency and/or choose a priority-label to the right. You should expect a response within two working days, and may utilize [Arctos Contacts](https://arctosdb.org/contacts/) if you feel response is lacking._

### Example Data
_Requests with clarifying sample data are generally much easier to understand and prioritize. Please attach or link to any representative data, in any form or format, which might help clarify the request._

### Available for Public View
_Most data are by default publicly available. Describe any necessary access restrictions._

### Helpful Actions

- [x] Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

- [x] Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

@ArctosDB/arctos-code-table-administrators 

## Approval
_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [ ] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [ ] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection
_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation
_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

- [ ] Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

- [ ] Add or revise the code table term/definition as described above. Ensure the URL of this Issue is included in the definition. URLs should be included *_as text_*, separated by spaced pipes. Do not include HTML in definitions.

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by dustymc** [comment]
This feels overloaded as a way to discuss specific terms, but it's a handy way to daylight and document a fundamental aspect of this. The two possibilities which have been suggested are

1. Limit this to few more-general terms ("juvenile") and use [age](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#age) to assert details ('1st instar').
2. Allow probably-eventually thousands of specific terms ("1st instar") here, help find them them by adding search terms ("juvenile").

I can see usability benefits to either approach. The biggest (assuming we can do a good job with search terms) is probably for data entry - they may eventually be required to pick from at least [60 instars](https://entnemdept.ufl.edu/walker/ufbir/chapters/chapter_13.shtml), for example, which will very likely lead to entry errors. (But maybe fewer than attempting a free-text assertion would create.)

Allowing [collections to select specific terms](https://github.com/ArctosDB/arctos-dev/issues/24) will somewhat mitigate this - an insect collection that doesn't have any 6+ instar data can exclude those ~55 terms while still including the ~5 they actually use, a different insect collection can pick a different set of assertable terms.

This also suggests a pattern for the term - surely the "most everything" model will eventually lead to lots of "1st ....." terms, so "instar 1" rather than '1st instar' might be more accessible. (Or confusing: this is a consideration, not a suggestion - and it's part of why I think approving specific terms here, or en masse in general, would be a mistake).

I believe @ebraker likes the many-terms approach, and my thoughts are certainly ambivalent enough to hop on that bandwagon.

@Jegelewicz @ccicero @ebraker @Nicole-Ridgwell-NMMNHS thoughts/elaborations/whatever?

I believe [GBIF](https://rs.gbif.org/vocabulary/gbif/life_stage.xml) has more or less gone the other way; their examples include relatively few "data" terms and lots of 'metadata' terms within them. That is, 

```
    larvae [lang=en, source=]
    tadpole [lang=en, source=]
    polliwog [lang=en, source=]
    pollywog [lang=en, source=]
    polliwig [lang=en, source=]
    polewig [lang=en, source=]
    polwig [lang=en, source=]
    planula [lang=en, source=]
    nauplius [lang=en, source=]
    zoea [lang=en, source=]
    nymph [lang=en, source=]
    caterpillar [lang=en, source=]
    grub [lang=en, source=]
    maggot [lang=en, source=]
    wriggler [lang=en, source=]
    trochophore [lang=en, source=]
    veliger [lang=en, source=]
    glochidium [lang=en, source=]
    ammocoete [lang=en, source=]
    leptocephalus [lang=en, source=]
    bipinnaria [lang=en, source=]
    caterpillar [lang=en, source=]
    grub [lang=en, source=]
    maggot [lang=en, source=] 
```

are all "search terms" for "larva." (And so if we're going in the opposite direction, maybe their definitions aren't great for us to include?)

ref: https://docs.google.com/document/d/1eZ_S8VTp-m5Wrbb6cAK96ODPZpt2-Hvnvt6yfU9qVwg/edit#heading=h.g7jyssil660h

**Comment by Jegelewicz** [comment]
I agree that we should take these term by term using this issue as a guide. I suggest we start with adult and move on from there one at a time?

**Comment by dustymc** [comment]
I got lost, not sure how to proceed with this.

https://github.com/ArctosDB/arctos/issues/7032 I thought was ready, but now there's a conflict and I don't know if I need to go with https://github.com/ArctosDB/arctos/issues/7032#issuecomment-1877923223 or https://github.com/ArctosDB/arctos/issues/7032#issuecomment-1984749832 or something else.

Beyond that, I think we're all opposed to getting stuck in the inbetweens again, so this would also need updated for kinda everybody....

```

 guid_prefix  | count 
--------------+-------
 UCM:Obs      |     2
 ALMNH:Ento   |     1
 NMMNH:Paleo  |     1
 NMU:Para     |     7
 ASUMZ:Invert |   559
 UTEP:HerpOS  |    20
 CSULB:Herp   |     7
 DMNS:Para    |    15
 UCSC:Herp    |     2
 UMZM:Para    |     1
 OWU:Inv      |     1
 UCM:Fish     |     1
 CHAS:Inv     |     2
 UWZM:Herp    |   222
 HWML:Para    |  5501
 UAM:Herp     |     3
 UWYMV:Herp   |    19
 MLZ:Fish     |     6
 LINGU:Herp   |    65
 CHAS:Ento    |    37
 UAMObs:Ento  |   309
 KNWR:Ento    |    39
 MVZ:Herp     | 11848
 UNCG:Para    |    57
 MSB:Herp     |   966
 MSB:Host     |    11
 NMMNH:Ento   |     3
 BYU:Herp     |    58
 OWU:Fish     |     3
 CHAS:Herp    |    89
 UWBM:Herp    |   348
 UTEP:Herp    |   268
 OGL:Genomic  |   344
 UNR:Fish     |     1
 UNR:Herp     |    70
 DMNS:Inv     |     2
 PSM:Paleo    |    57
 USNPC:Para   |    63
 UMNH:Herp    |     7
 UAM:Ento     |  7903
 UCM:Herp     |   244
 APSU:Fish    |    22
 OWU:Amph     |     1
 MSB:Para     |  3717
 APSU:Herp    |    22
```

when the new value is added to the code table.


Here's my start of an issue, might eventually be handy.

-----------------



### Goal

Initially, https://github.com/ArctosDB/arctos/issues/7032

### Context

No appropriate value


### Table

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlife_stage

### Proposed Value

larva



### Proposed Definition


The immature form of an animal.



(https://arctos.database.museum/info/ctDocumentation.cfm?table=ctage_class#larva is too specific, https://rs.gbif.org/vocabulary/gbif/life_stage.xml wanders around, I attempted to simplify - better definitions most welcome!)


### BestFor

Para

### Docurl

http://rs.gbif.org/vocabulary/gbif/life_stage/larva

### Search Terms

```
larvae
tadpole
polliwog
pollywog
polliwig
polewig
polwig
planula
nauplius
zoea
nymph
caterpillar
grub
maggot
wriggler
trochophore
veliger
glochidium
ammocoete
leptocephalus
bipinnaria
caterpillar
grub
maggot
```


-------------------------

@Jegelewicz @mkoo help?

**Comment by Jegelewicz** [comment]
we aren't stuck, we just need to do things in the proper order. I will create the issue to unblock that one.

**Comment by Jegelewicz** [comment]
Next step should be https://github.com/ArctosDB/arctos/issues/7521

**Comment by dustymc** [comment]
The "core"/straight-across terms in the initial comment are done, I'm closing this.

We still need to find a migration path for anything left in age class, I'll try to make sure everything has an Issue.

**Comment by Jegelewicz** [comment]
Banner added to inform users: 

> The following catalog record attributes that were formally recorded as age class should now be recorded as life stage: 1st instar, 2nd instar, 3rd instar, 4th instar, 5th instar, adult, embryo, juvenile, larva, pupa, and subadult. For more information see https://github.com/ArctosDB/arctos/issues/7298

**Comment by auzwan** [comment]
Hello, 
I would like to download this 3D Model : https://sketchfab.com/3d-models/chinchilla-lanigera-msbmamm101524-a58d3467f8a3499e983839548bfde128 
but my computer is identified as having malicious software. I don't understand. It's for a educational project.
Can you help me ?
Thank you

**Comment by ewommack** [comment]
UWYMV is ok making the change. Life stage probably makes more sense for our tadpoles and other non-adult herps.
