### ISSUE TITLE
Feature Request - clean up inline documentation

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#7306]
**Is your feature request related to a problem? Please describe.**

Inline docs has a lot of clutter, clean it up so I can find stuff.

**Oops**

Here's old data in case I accidentally remove something useful.

[local_documentation.csv](https://github.com/ArctosDB/arctos/files/13966632/local_documentation.csv)

**Comment by Jegelewicz** [comment]
Can I help with this at all?
