### ISSUE TITLE
Curatorial Search Request-container scans by year

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#7309]
This request is for updated SQL that can be used to get a count of the number of cryovials scanned for the first time in MSB DGR for last year, 2023, and ideally for the last 5 years, by year.
The cheat sheet has the following - but I don't know how to populate it so that it works in the SQL search tool:

Count of cryovials that have been scanned into position in a collection (for the first time - e.g. not just moved within the collection) by year:

with recursive subordinates as ( select container.container_id, container.container_type, container.parent_install_date, container.institution_acronym, 0 lvl from container where container.barcode='DGR' union select e.container_id, e.container_type, e.parent_install_date, e.institution_acronym, s.lvl + 1 lvl from container e inner join subordinates s ON s.container_id = e.parent_container_id where lvl<20 ) select to_char(parent_install_date,'YYYY'), count(*) c from subordinates where container_type='cryovial' and institution_acronym in ('MSB','DGR') group by to_char(parent_install_date,'YYYY') order by to_char(parent_install_date,'YYYY')

**Comment by campmlc** [comment]
Here is the SQL I used in 2020 - but I get the message that parent install date doesn't exist:

select to_char(PARENT_INSTALL_DATE,'YYYY'),count(*) from container where container_type='cryovial' and institution_acronym in ('MSB','DGR') group by to_char(PARENT_INSTALL_DATE,'YYYY') order by to_char(PARENT_INSTALL_DATE,'YYYY'

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/5815#issuecomment-1472137154

with recursive subordinates as ( select container.container_id, container.container_type, container.last_date, container.institution_acronym, 0 lvl from container where container.barcode='DGR' union select e.container_id, e.container_type, e.last_date, e.institution_acronym, s.lvl + 1 lvl from container e inner join subordinates s ON s.container_id = e.parent_container_id where lvl<20 ) select to_char(last_date,'YYYY'), count(*) c from subordinates where container_type='cryovial' and institution_acronym in ('MSB','DGR') group by to_char(last_date,'YYYY') order by to_char(last_date,'YYYY')

select to_char(last_date,'YYYY'),count(*) from container where container_type='cryovial' and institution_acronym in ('MSB','DGR') group by to_char(last_date,'YYYY') order by to_char(last_date,'YYYY')
