### ISSUE TITLE
help fixing other ID upload

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#7311]
I just uploaded the attached Other IDs but had forgotten that with all the changes we made to other IDs I need to include the full URL to the BOLD Process IDs.

for example:
I uploaded UAMIC4710-23

but should have uploaded:

http://boldsystems.org/index.php/Public_RecordView?processid=UAMIC4710-23

So, can this string: http://boldsystems.org/index.php/Public_RecordView?processid=

be inserted into create proper URLs to the process IDs for the attached GUIDs?

I chock this error up to doing something one way for years and then having to do it a different way. Humans!!

[cf_temp_oids(3).csv](https://github.com/ArctosDB/arctos/files/13980241/cf_temp_oids.3.csv)

**Comment by dustymc** [comment]
FYI you can easily do this, there's an [unloader](https://arctos.database.museum/loaders/bulkUnLoadIdentifier.cfm). 

There's also a [converter](https://arctos.database.museum/loaders/identifierConverter.cfm) which can (with certain assumptions) deal with "legacy style" identifiers.

I updated from this:

[temp_bds.csv.zip](https://github.com/ArctosDB/arctos/files/13980444/temp_bds.csv.zip)


@campmlc @acdoll there are some mangled MSB and DMNS records in here, I did nothing to them.
```
arctosprod@arctos>> delete from temp_bds where guid_prefix != 'UAM:Ento';
DELETE 3
```

**Comment by DerekSikes** [comment]
doh! forgot about the unloader. Thanks for the help!!
