### ISSUE TITLE
Code Table Request - migrate term from age class to life stage: adult

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7313]
### Goal
_Describe what you're trying to accomplish. This is the only necessary step to start this process. The Committee is available to assist with all other steps. Please clearly indicate any uncertainty or desired guidance if you proceed beyond this step._

Move terms deemed to be life stages to the newly created code table. This process will be completed by the DBA.
1. all current adult age class attributes will be converted to adult life stage attributes
2. adult will no longer be available in age class
3. all collections with adult in use at the time this process is completed will have the attribute added as "usedby" in the code table

### Context
_Describe why this new value is necessary and existing values are not._

#7298 

### Table
_Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table or value. This may involve multiple tables and will control datatype for Attributes. OtherID requests require BaseURL (and example) or explanation. Please ask for assistance if unsure._

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlife_stage

### Proposed Value
_Proposed new value. This should be clear and compatible with similar values in the relevant table and across Arctos._

adult

### Proposed Definition
_Clear, complete, non-collection-type-specific **functional** definition of the value. Avoid discipline-specific terminology if possible, include parenthetically if unavoidable._

Current definition in age class:
~~An adult is a plant, animal, or person who has reached full growth or alternatively is capable of reproduction. | http://rs.gbif.org/vocabulary/gbif/life_stage/adult | https://github.com/ArctosDB/arctos/issues/6859~~

Replace with new definition in life stage:
An adult is an individual that has is fully grown and has achieved mature ~~phenotypic~~ characteristics. | http://rs.gbif.org/vocabulary/gbif/life_stage/adult

### Best For
_Some code tables contain collection-type-specific values. ``collection_cde`` may be found from https://arctos.database.museum/home.cfm_

[Amph](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcollection_cde#amph)
[Arc](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcollection_cde#arc)
[Bird](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcollection_cde#bird)
[Egg](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcollection_cde#egg)
[Ento](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcollection_cde#ento)
[Env](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcollection_cde#env)
[ES](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcollection_cde#es)
[Fish](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcollection_cde#fish)
[Herb](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcollection_cde#herb)
[Herp](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcollection_cde#herp)
[Hild](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcollection_cde#hild)
[Host](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcollection_cde#host)
[Inv](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcollection_cde#inv)
[Mala](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcollection_cde#mala)
[Mamm](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcollection_cde#mamm)
[Para](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcollection_cde#para)
[Rept](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcollection_cde#rept)
[Teach](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcollection_cde#teach)
[Vert](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcollection_cde#vert)
[Zoo](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcollection_cde#zoo)

### Search Terms

imago

#### Attribute data type
_If the request is for an attribute, what values will be allowed?
free-text, categorical, or number+units depending upon the attribute (TBA)_

#### Attribute controlled values
_If the values are categorical (to be controlled by a code table), add a link to the appropriate code table. If a new table or set of values is needed, please elaborate._

#### Attribute units
_if numerical values should be accompanied by units, provide a link to the appropriate units table._

#### Part preservation attribute affect on "tissueness"
_if a new part preservation is requested, please add the affect it would have on "tissueness": No Influence, Allows, or Denies_

### Priority
_Please describe the urgency and/or choose a priority-label to the right. You should expect a response within two working days, and may utilize [Arctos Contacts](https://arctosdb.org/contacts/) if you feel response is lacking._

### Example Data
_Requests with clarifying sample data are generally much easier to understand and prioritize. Please attach or link to any representative data, in any form or format, which might help clarify the request._

### Available for Public View
_Most data are by default publicly available. Describe any necessary access restrictions._

### Helpful Actions

- [ ] Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

- [ ] Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

@ArctosDB/arctos-code-table-administrators 

## Approval
_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection
_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
4. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
5. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation
_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

- [ ] Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

- [ ] Add or revise the code table term/definition as described above. Ensure the URL of this Issue is included in the definition. URLs should be included *_as text_*, separated by spaced pipes. Do not include HTML in definitions.

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by dustymc** [comment]
I have a tiny not-quite-objection around "phenotypic" in the definition. This carries method, knowing birth date, telomere length, that thing we haven't invented yet, etc. could all be involved.

**Comment by campmlc** [comment]
Adults are generally accepted to reproductively mature, so that should be in there.

**Comment by dustymc** [comment]
>reproductively mature

I think that's a method, and/or possibly a life stage of its own depending on what happens in https://github.com/ArctosDB/arctos/issues/7298

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
box checked

**Comment by Jegelewicz** [comment]
Can we also change anything hanging in the bulkloader as age class = adult to life stage = adult

**Comment by dustymc** [comment]
CT Committee says just do this

**Comment by jldunnum** [comment]
Wait, so have we lost "age class" altogether? We just migrated data from "age" into "age class"

**Comment by dustymc** [comment]
@jldunnum no loss, just moving to a cleaner and more inclusive container, see https://github.com/ArctosDB/arctos/issues/2881

**Comment by dustymc** [comment]
attribute created

**Comment by dustymc** [comment]
added access for all collection with age class adult records in attributes or the bulkloader

 {MVZ:Mamm,UNR:Mamm,MMNH:Bird,UCM:Obs,NCWRC:Herp,UCM:Mamm,UAM:Arc,KNWR:Inv,CHAS:Fish,ALMNH:Mamm,NMMNH:Herp,ALMNH:Ento,MMNH:Mamm,UTEPObs:Herp,NMMNH:Paleo,ASNHC:Mamm,DMNS:Bird,ASNHC:Bird,WNMU:Mamm,UWZM:Mamm,ASUMZ:Invert,NCWRC:Fish,UTEP:HerpOS,UTEP:Inv,CSULB:Herp,WNMU:Bird,UAF:Zooarch,DMNS:Para,UCSC:Herp,UTEP:Bird,UWYMV:Mamm,ZSFQ:Herp,NMU:Mamm,KSB:Teach,DMNS:Herp,DMNS:Mamm,ALMNH:Bird,CRCM:Mamm,UCM:Fish,UAM:Mamm,UWZM:Herp,CHAS:Inv,HWML:Para,MSB:Mamm,UAM:Herp,UWYMV:Herp,UWBM:Mamm,CRCM:Bird,MLZ:Fish,BYUObs:Herp,LINGU:Herp,CHAS:Ento,UAMObs:Ento,KWP:Ento,KNWR:Ento,MVZObs:Mamm,MVZObs:Herp,MVZ:Herp,UNCG:Para,CHAS:Mamm,MSB:Herp,CHAS:Teach,UNCG:Mamm,MSB:Host,NMMNH:Ento,MLZ:Bird,UMZM:Mamm,UCM:Bird,UTEP:Ento,BYU:Herp,UMNH:Mamm,MSB:Bird,CHAS:Herp,UWBM:Herp,UTEP:Herp,OGL:Genomic,CHAS:Bird,UNR:Fish,UNR:Herp,UWZM:Bird,UWYMV:Bird,UCSC:Bird,DMNS:Inv,USNPC:Para,UAM:Ento,UMNH:Herp,NMU:Bird,CSULB:Bird,UCM:Herp,KSB:Mamm,NMMNH:Bird,UMZM:Bird,ASNHC:Herp,UMNH:Bird,MSB:Para,UMNH:Para,UAM:Bird,UTEP:Arc,APSU:Herp,BYU:Teach,BYU:Fish}

**Comment by dustymc** [comment]
Bulkloader and table updated, old value removed.
