### ISSUE TITLE
Agent Picks

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ArctosDB/arctos#732]
```
What steps will reproduce the problem?
1. The popup pick window agent picker thing has always caused usability problems
2. Attempted replacements have been rejected
3. There is a potential replacement in manage agents. It's been there for a few 
months now, and nobody's complained (or said anything else, at all, about it!)
4 I need feedback before doing anything more. Is the overlay picker (now in 
agents) better, and if so, better enough to start pushing it to other forms?
```

Original issue reported on code.google.com by `dust...@gmail.com` on 26 May 2015 at 3:40

**Comment by campmlc** [comment]
This sounds reasonable to me. I would like to see this move forward in order to get issue #892 resolved.

**Comment by mkoo** [comment]
Consensus from AWG meeting (2016-08-01): preference for Overlay.

**Comment by Jegelewicz** [comment]
What's the status of this? Can we close?

**Comment by dustymc** [comment]
No, there are still some old-style floating around out there.

**Comment by Jegelewicz** [comment]
@dustymc can I help? What do we need to do to clean this up and close?
