### ISSUE TITLE
Missing data in async request

### ISSUE THREAD

**Issue by jldunnum** [ArctosDB/arctos#7320]
Did a data request and included Attributedetail. The field shows up but is not populated by any data in the download. Any thoughts on why that might be?
Thanks

![image](https://github.com/ArctosDB/arctos/assets/17278851/9a171589-b4a4-4913-bdae-e073d0324c42)

**Comment by dustymc** [comment]
Possibly related to https://github.com/ArctosDB/arctos/issues/5702.

I need details, how do I re-create, how did you get there? The data you downloaded might be useful as well.

**Comment by jldunnum** [comment]
Searched MSB:Mamm for all specimens examined for orthohantavirus. 
![image](https://github.com/ArctosDB/arctos/assets/17278851/61d73a9f-a98c-40c0-baac-b8b4e702b703)

Used search and results profile profile "Dunnum hanta GEOME download".

Here is the asych download
[MSB Arctos Hanta data download.csv](https://github.com/ArctosDB/arctos/files/14015354/MSB.Arctos.Hanta.data.download.csv)

**Comment by dustymc** [comment]
Thanks! I see the problem - the process which is making the request as you doesn't have your permissions, and for about the same reasons the public cache is spottier than it needs to be with these data, and those add up to a lot of NULLs. I'll fix what I can and open some issues for what I can't.

That said, do you really want the JSON attribute data? I can get it for you if so, or let me know what you actually want and we can work on that if not.

**Comment by jldunnum** [comment]
Cool, thanks Dusty! I really don't want the JSON, I just needed the attribute date, methods and remarks in my download

**Comment by dustymc** [comment]
Should be working properly in next release.

This does involve https://github.com/ArctosDB/arctos/issues/4430 - the file in next release may contain encumbered data, and there's some (I think very near zero) chance someone could figure out how to access those.

>needed the attribute date, methods and remarks in my download

<img width="347" alt="Screenshot 2024-01-22 at 14 45 59" src="https://github.com/ArctosDB/arctos/assets/5720791/3cda8097-7664-4e61-8fa1-8ef32d1ee46b">

<img width="221" alt="Screenshot 2024-01-22 at 14 46 13" src="https://github.com/ArctosDB/arctos/assets/5720791/294b5eaa-719f-4f21-907b-7e6fef88a63d">


might do what you need, if you can turn off expensive stuff and filter enough to get around any timeouts.
