### ISSUE TITLE
Error linking publication to an older identification

### ISSUE THREAD

**Issue by ufarrell** [ArctosDB/arctos#7323]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Trying to add a citation to an older identification, it auto-fills to the new identification and won't save...not sure if its a bug, or if I am using incorrectly.

**To Reproduce**
1. Go to Identifications
2. Type status - add publication to an identification with order '2' (or order '0' - same problem)
3. Tab to find publication

**Expected behavior**
A citation ("basis of illustration") is linked to the older identification

**Screenshots**

<img width="700" alt="step1" src="https://github.com/ArctosDB/arctos/assets/11726107/86721640-5f2b-4eb5-818e-5d189ed5de99">
<img width="702" alt="step2" src="https://github.com/ArctosDB/arctos/assets/11726107/407fad25-6679-4c90-a06d-504b013ad204">
<img width="699" alt="step3" src="https://github.com/ArctosDB/arctos/assets/11726107/290ba9ac-c5ea-451a-b46b-b14c586090f4">

**Data**

**Additional context**
Error message on save:

ERROR_ID 	D625C1DC-CF83-4D15-8B61A3D95C5FFA1E
ERROR_TYPE 	application
ERROR_MESSAGE 	update_identification fail
ERROR_DETAIL 	can't cast empty string to a number value

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by dustymc** [comment]
Nope, not that, and I can't figure out what it is. I've got more debug turned on at test, would be useful if you can re-create there. I will keep looking, but I'm not seeing anything yet and the error isn't very useful.

Also, your images are going to https://private-user-images.githubusercontent.com and all I can see is the squinty inline version.

**Comment by Jegelewicz** [comment]
@dustymc I can see those images just fine - that seems weird...

**Comment by ufarrell** [comment]
"I've got more debug turned on at test, would be useful if you can re-create there." - does this mean just try again? If so, I have just made another attempt in case it helps at all. Let me know if you need something different. 

As for the images - you mean the screenshots? I reduced the size because I thought they'd be huge, but maybe I was too overenthusiatic. Or is there a better way to send them? I just pasted them in.

For what it is worth, hopefully visible, here is the error message that I just got now when I tried again,
<img width="465" alt="Screenshot 2024-01-23 at 15 59 38" src="https://github.com/ArctosDB/arctos/assets/11726107/ae734fc0-16fa-4eb8-9a49-6af89a6099bb">

**Comment by Jegelewicz** [comment]
I just tried in test with the same result

![image](https://github.com/ArctosDB/arctos/assets/5725767/def742d7-1e5a-40d1-bfcb-aaec83f4ac7e)

testing on record https://arctos-test.tacc.utexas.edu/guid/UNM:Paleo:10146

**Comment by Jegelewicz** [comment]
The update fails because there is no publication stored in the unaccepted identification - when I selected the publication it ended up being stored in the "0" identification instead.

**Comment by dustymc** [comment]
> same result

AHA - thanks. (The picker is somehow confusing itself.)

>see those images

So can I, if I zoom in a bunch. Normally I can click to get full-size in a new window.

Yours are the same, not sure if its something about this thread (and EU??) or github has changed or ?????

**Comment by ufarrell** [comment]
fyi working for me - the images, that is - I get a full size pop-up in a new window when I click on Teresa's

**Comment by dustymc** [comment]
>full size pop-up in a new window when I click on Teresa's

So do I, now - and yours too....

I'll close 7000 tabs, restart my browser, say a thanks to any potential githubgods, and get some more coffee.....

I think I've got the bug (funky incrementing, all my fault) squished, @Jegelewicz can you confirm in test plz?

**Comment by Jegelewicz** [comment]
Yep seems like it works now.
