### ISSUE TITLE
Code Table Request - agent attribute - verification status

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#7328]
### Goal

In preparation for https://github.com/ArctosDB/arctos/issues/7318, set up the environment in which to record "status."

### Context

This is a new value for a new code table for a new structure.

### Table

Nothing to link yet, will be https://github.com/ArctosDB/arctos/issues/7327

### Proposed Value

'status' was proposed in https://github.com/ArctosDB/arctos/issues/6813#issuecomment-1899522184, but seems a bit cryptic. 'verification status' is familiar, but I'm not sure it's quite right. HELP!

### Proposed Definition

 Indication of data quality or completeness. 

(Seems pretty waffly - HELP!!)

#### Attribute controlled values

This will be controlled by a trigger, there will not be a code table. (Such can be added if this sort of thing turns out to be more common than anticipated). Initially-allowed values will be

*  verified 
* accepted 
* unverified 

and meanings and UI handling is described in https://github.com/ArctosDB/arctos/issues/6813#issuecomment-1899522184

### Priority

Will happen when necessary, please HELP!

### Helpful Actions

- [x] Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

- [x] Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

@ArctosDB/arctos-code-table-administrators 

@mkoo 

## Approval
_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [ ] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [ ] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection
_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation
_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

- [ ] Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

- [ ] Add or revise the code table term/definition as described above. Ensure the URL of this Issue is included in the definition. URLs should be included *_as text_*, separated by spaced pipes. Do not include HTML in definitions.

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by Jegelewicz** [comment]
> Seems pretty waffly

Maybe because the three options need definitions?

verified - The agent is known to the verifier and managed as such. Data associated with the agent can be reasonably relied upon and edits should only be made when the editor is positive they apply to the agent. While verified agents may not carry disambiguating information that could be detected by automation, they are actively managed by another Arctos Agent.

accepted - The agent is not actively managed but holds data that make it unique such as an ORCiD, Wikidata identifier, or Library of Congress number.

unverified - The agent does not hold any data that allows disambiguation by automation and is not managed. Please improve this Agent by adding disambiguating data!

**Comment by ekrimmel** [comment]
Take or leave my thoughts on this...

"verified" and "accepted" are basically synonyms in English, which could lead to user confusion by default (i.e. the user needs to read the code table definition enough times to internalize the difference between these statuses; status values are not intuitively different). Something like this might be more intuitive?

One field to deal with a human decision:

> _verified_ - The agent is known to the verifier and managed as such. Data associated with the agent can be reasonably relied upon and edits should only be made when the editor is positive they apply to the agent. ~While verified agents may not carry disambiguating information that could be detected by automation, they are actively managed by another Arctos Agent.~
> 
> _unverified_ - The agent ~does not hold any data that allows disambiguation by automation and~ is not managed **and agent data may not be reliable**. Please improve this agent by adding ~disambiguating~ data!

Another field to deal with a programmatic assessment:

> _disambiguated_ - ~The agent is not actively managed but holds data that make it unique such as an ORCiD, Wikidata identifier, or Library of Congress number.~ The agent is associated with a unique identifier issued by ORCID, Wikidata, or Library of Congress. **[expand this list to include the identifiers Arctos is looking for, if this value is getting assigned programmatically]**
>
> _not disambiguated_ - The agent is not associated with a unique identifier issued by ORCID, Wikidata, or Library of Congress. **[expand this list to include the identifiers Arctos is looking for, if this value is getting assigned programmatically]**

Both or either of the above could also be boolean vs. code tables.

**Comment by Jegelewicz** [comment]
That's pretty sweet.
