### ISSUE TITLE
Associated species?

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#7329]
Didn't we used to have an associated_species field?

I'll be giving a demo to colleagues in Feb that are strongly considering migrating into Arctos. I've started a questions doc and our Ento CM was asking about how to document host plants for insects (not vouchered). In Specify, she is currently able to use an 'associated taxon' field that links to their taxonomic authority to record the plant. 

What do you do @DerekSikes ?

**Comment by dustymc** [comment]
> associated_species field?

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#associated_species

>taxonomic authority

Taxonomy needs identifications, identifications need cataloged items - https://arctos.database.museum/collection/MSB:Host is a collection which exists for just that purpose. 

The attribute is just text (super-easy to create but doesn't DO too much), a relationship will let you get at things like parasites of a taxon - https://arctos.database.museum/search.cfm?related_id_references=host%20of&related_item_identification=Alopex%20lagopus&taxon_name=Taenia%20polyacantha

**Comment by ebraker** [comment]
Thanks @dustymc. I was searching in the wrong place for associated species (locality and event fields). 

I'm fairly certain there would be no interest in creating a model similar to MSB:Host since it would be cost prohibitive (this is recorded for every record where insects weren't trapped) and more work. I guess she would still be able to find all things collected on a Common Sunflower, it just wouldn't be standardized.

**Comment by ebraker** [comment]
All makes sense. I think it is still a big lift to do a host/entity when I'm assuming she just wants a pick list to make data entry easier.

> I think it's a bit more than that. Eg Rausch used a bunch of common names which I'm sure were completely unambiguous when he wrote them, but now mean vague and confusing things. Taxa certainly change shape after 50 years, but I think it would have at least been simpler to understand the intended circumscription.

I guess Specify uses two fields for this. One to capture verbatim associated taxon and then one linked to a taxonomy tree to formalize the ID if known.

**Comment by dustymc** [comment]
>big lift 

Yes, probably true - but maybe "we" can help, and there are benefits.

>Specify uses two fields

Yup - the world is easy when you can pretend there's only one possible view of taxonomy!

**Comment by Jegelewicz** [comment]
I think about this a lot and I'm wondering if we could remove related records from our pricing. Count all records related to each other as one? We need to come up with a way to do research grade without being cost prohibitive.

I have also considered using one of the numbered identification orders as "associated taxon" or something like that....

**Comment by DerekSikes** [comment]
fwiw we sometimes use the Associated Species attribute to record this info

 eg for this record: https://arctos.database.museum/guid/UAM:Ento:483881

**Comment by dustymc** [comment]
done?
