### ISSUE TITLE
suggest projects

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ArctosDB/arctos#733]
```
Agents commonly borrow specimens from multiple collections, or request multiple 
loans from a collection for related purposes. When a loan is created, see if we 
can detect any potentially-relevant projects.
```

Original issue reported on code.google.com by `dust...@gmail.com` on 26 May 2015 at 4:45

**Comment by dustymc** [comment]
<img width="911" alt="Screen Shot 2021-04-28 at 2 37 47 PM" src="https://user-images.githubusercontent.com/5720791/116475918-54871400-a82f-11eb-9eda-17741596e324.png">

**Comment by campmlc** [comment]
Panama and Panama Hantavirus projects need to be merged. This is going to
be a convoluted process. Suggestions on how best to do this?

**Comment by dustymc** [comment]
There's no magic, things (which are very likely also duplicates of each other) will need moved over then one can be deleted.

And maybe prioritize https://github.com/ArctosDB/arctos/issues/2570 so we can track who's causing that.
