### ISSUE TITLE
[external CONTACT] 'age' data for MVZ birds (life stage mappings)

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#7334]
@dustymc I'm slowly working through the age data you sent me for MVZ birds and mapping to life stage terms, but it would be helpful to have some taxonomy. Can you resend me the list with phylorder added as a start? The file you sent me was 'temp_mvz_bird_age'

Thanks!
Carla

**Comment by dustymc** [comment]
Here you go:

[temp_mvz_bird_age(1).csv](https://github.com/ArctosDB/arctos/files/14069213/temp_mvz_bird_age.1.csv)

**Comment by ccicero** [comment]
Thanks!
