### ISSUE TITLE
Tracking lot splits

### ISSUE THREAD

**Issue by adhornsby** [ArctosDB/arctos#7337]
I asked a question on nhcoll about splitting lots, and I have a related question for Arctos folks: what is the best way to track these splits?  

In this case we're talking about one jar of critters that had been IDed just to genus, and which have all now been re-IDed to species and will be split into multiple, separate, multi-individual jars.

This seems like a great time for reciprocal relationships, but these jars are no longer "same lot as," and "collected with" doesn't really capture the relationship.  I can of course just use one of those options and explain in remarks, but I wanted to see if I was overlooking some obvious way to track this.

**Comment by dustymc** [comment]
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type#lot_number

Despite that existing, I think @DerekSikes does this best - "lots" are just intermediate or unfinished things, they don't get cited (they do get loaned, but only for the purposes of splitting out individuals which may be cataloged and then cited), there's no particular reason to track that an individual (the thing that does get cited, perhaps after the lot has been split many times) spent some time in a lower-data state or in a jar with some friends.

**Comment by adhornsby** [comment]
Ha, I love that this is basically the opposite reaction that nhcoll had!  I'll talk with our fish curator about what she wants to do ultimately, but I do like being able to play devil's advocate...

**Comment by dustymc** [comment]
>opposite reaction that nhcoll 

Yes. Tradition would have you cite "one of the fish in that bucket" or *maybe* "the bucket-fish with the extra tag." Having sloshed around in buckets of fish and deattatched tags, I don't think that's very Research Grade. The recommendation provides a much more robust way of linking vouchers to literature.
