### ISSUE TITLE
Need Help with Arctos Error: No ASCII variant

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7340]
# Error Text
**Copy the text from the page and paste it here**

No ASCII variant

# Where it happened
**Provide a link to or a description of the page where the error occurred.**

https://arctos.database.museum/agents.cfm?agent_id=21349171

# Steps to get there
**Describe the actions that led to the error**

# Problem
**Community response to describe the problem that caused the error**

This exists - what else is causing a problem?

![image](https://github.com/ArctosDB/arctos/assets/5725767/a5e091fe-7ef0-49b9-9702-fb62d1b81cc2)

# Solution
**Community response with directions for how to correct the problem**

**Comment by dustymc** [comment]
<img width="718" alt="Screenshot 2024-01-27 at 09 38 55" src="https://github.com/ArctosDB/arctos/assets/5720791/78d83809-9eb9-4a26-aad0-f6bda3155221">

```
arctosprod@arctos>> select asciiiiiiify(preferred_agent_name)from agent where agent_id=21349171;
NOTICE:  Grisel Rodrí­quez Ferrer
NOTICE:  |G=71|r=114|i=105|s=115|e=101|l=108| =32|R=82|o=111|d=100|r=114|í=237|­=173|q=113|u=117|e=101|z=122| =32|F=70|e=101|r=114|r=114|e=101|r=114
```

There's a soft hyphen in the preferred name. (So the ASCIIification/search can't really ever work properly.) 

Maybe https://handbook.arctosdb.org/documentation/encoding.html - some software is doing something evil...

**Comment by Jegelewicz** [comment]
I always use CSV UTF-8 from Excel EXCEPT when things get entered manually - maybe it was a copy paste from Excel? Anyway, it is fixed now.
