### ISSUE TITLE
What can I do about missing documentation notifications?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7341]
https://arctos.database.museum/Reports/notifications.cfm?srch=missing+documentation&srch_status=&afterdate=&beforedate=

This looks like places where we should have a link to a definition for a term on the Arctos page, but don't - where do I (can I) manage those?

**Comment by dustymc** [comment]
[inline documentation](https://arctos.database.museum/doc/field_documentation.cfm)

**Comment by dustymc** [comment]
done?
