### ISSUE TITLE
Creating subdirectories in TACC

### ISSUE THREAD

**Issue by adhornsby** [ArctosDB/arctos#7342]
I'm working in `corral-tacc/projects/arctos/web/umzm/` and I'd like to create a subdirectory `prep_cards`, but it says I don't have permission.  Am I able to do this, and if not what is the process for getting a subdirectory created?  Just bother @dustymc ?

**Comment by Jegelewicz** [comment]
> Just bother @dustymc ?

Probably. See also - https://handbook.arctosdb.org/how_to/How-to-Upload-Media-to-TACC.html#large-batch-uploads

```
We consider it a best practice to create “daily” folders to manage your files beyond any shared folders

for example

https://web.corral.tacc.utexas.edu/arctos/{institution_acronym}/collection_or_whatever/some_project/maybe_other_stuff/{yyyy_mm_dd}/

institution_acronym (for Arctos accounting) and the dailies (for everyone’s sanity) are the important parts, the “project folders” in the middle are entirely optional, but if they are to be shared, they should be created by the TACC-authorized manager.
```

**Comment by dustymc** [comment]
Please clarify what precisely is being requested. I created the subdirectory as requested in https://github.com/ArctosDB/internal/issues/247, I think (not sure!) that I can retroactively give you write access on  /corral-tacc/projects/arctos/web/umzm/ but that will introduce some limitations going forward - see https://handbook.arctosdb.org/best_practices/TACC_allocation.html.

In case that's all as clear as mud, the recommendation is

1. Have me create new /corral-tacc/projects/arctos/web/umzm/whatever level directories, so that other users can use them. (It will always only be yours if you create it.)
2. Within that directory, use daily directories. (catalog_images has a bunch of bare files, they can still live beside daily directories...)

**Comment by adhornsby** [comment]
@dustymc Yes -- please create: /corral-tacc/projects/arctos/web/umzm/prep_cards

I'm still not sure I 100% understand, so bear with me.  I know that daily directories are the recommended practice, but I can't make directories at any level ("Permission denied. Please contact your web hosting service provider for assistance.").  That's why I previously just stuffed bare files into umzm/catalog_images.  Is it possible to get the permission to make daily directories?  If not, @dustymc can you also make a daily directory umzm/prep_cards/2024-02-13 and I'll just try to get everything uploaded today...

**Comment by dustymc** [comment]
>create

[Done.](https://web.corral.tacc.utexas.edu/arctos/umzm/prep_cards/)

>can't make directories

You have read/write/execute on the subdirs, if you can't make eg ``prep_cards/2024-02-13`` please send whatever you can (screenshot, error log files) along with some description of what tool you're using and we'll figure it out.

```

getfacl prep_cards/
user:ahornsby:rwx

getfacl catalog_images/
user:ahornsby:rwx
```

**Comment by adhornsby** [comment]
Thanks @dustymc !

I'm accessing TACC through the Cyberduck.
<img width="929" alt="image" src="https://github.com/ArctosDB/arctos/assets/40217539/8d9b0be6-bd1d-40c5-9aaa-f17c8d70f481">
From inside /corral-tacc/projects/arctos/web/umzm/prep_cards, I go to File --> New Folder and try to create 2024_02_13.  Below is the whole error I get.  Clicking on the upper right "?" just takes me to the general https://cyberduck.io/help/
<img width="929" alt="image" src="https://github.com/ArctosDB/arctos/assets/40217539/2e9ef666-c3c9-4a71-8008-51150b39b5b9">
If it's much easier to just create prep_cards/2024_02_13 than to figure out the issue, that works fine!  This is likely to be the last bulk upload to TACC that I do for UMZM...

**Comment by dustymc** [comment]
I made a folder and sent TACC a help request.

**Comment by dustymc** [comment]
@adhornsby it looks like something in your client, Chris was able to create and destroy directories as you.

You might also try /corral/projects/arctos/web/umzm (rather than /corral-tacc/projects/arctos/web/umzm), it's possible that something in the older mapping is confusing your client.

**Comment by adhornsby** [comment]
OK, thanks @dustymc !  It's also not working in /corral/, but I have all I anticipate needing for UMZM.
