### ISSUE TITLE
Cannot download template

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7345]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

I want to get a new collection template, but it's not working.

**To Reproduce**
1. Go to https://arctos.database.museum/Admin/pre_collection.cfm
2. Click on '[download a CSV template](https://arctos.database.museum/Admin/pre_collection.cfm?action=blankCSV).'
3. See error

<html><body>

ERROR_ID | B49EEF5E-7302-42A3-8E7A85BDF2D725A0
-- | --
ERROR_TYPE | application
ERROR_MESSAGE | Invalid file [/usr/local/webroot/download/collection_request_template.csv]
ERROR_DETAIL | Read-only file system

</body>
</html>

**Expected behavior**

I expect a csv template to download.

**Screenshots**

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 122.0 (64-bit)

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

I can go find an old one - but other people won't be so lucky.

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/7346
