### ISSUE TITLE
Arctos Down - TACC data center work affecting VMs

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#7346]
Please complete to the best of your ability.

## Unplanned Outage
 - Date and time outage discovered: **NOW**
 - Describe the outage (Arctos down or only some part not working?): **It's kinda-up but likely not all working correctly. Recommend not using. TACC has been notified.**

Arctos staff is monitoriing

## Communication before/during outage
- [x] Pin this issue
- [x] Banner updated @jegelewicz @mkoo
- [x] Email sent to AWG  
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [x] Unpin this issue
- [x] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by Jegelewicz** [comment]
@dustymc should I try to add a banner so people who aren't looking here will know?

**Comment by ewommack** [comment]
Email sent out.

**Comment by ewommack** [comment]
we're still down? I keep trying to build a bulkloader file and it is giving me an error

**Comment by genevieve-anderegg** [comment]
Some things are working for us and not others- I've been able to search for records and do single record entry, but not access the bulkloader (Browse and Edit) or print labels with the reporter.

**Comment by ewommack** [comment]
Our entire bird collection is down apparently. I can't search for any of the catalog records from it.

**Comment by mkoo** [comment]
Dusty asked TACC to prioritize rebooting the Arctos VM's just a few minutes

**Comment by dustymc** [comment]
Everything should be back now.

**Comment by Jegelewicz** [comment]
Banner will come down tonight.
