### ISSUE TITLE
error feedback- edit locality data permission needed

### ISSUE THREAD

**Issue by justybob** [ArctosDB/arctos#7347]
Hello, I am attempting to correct some locality information for a record, however I do not have permission to do so. This if for the collection UAA:Ento
I receive the following error:

ERROR_ID | 5110B759-F3D4-4BCD-B5FA0988CD70B5AD
-- | --
ERROR_TYPE | unauthorized
ERROR_MESSAGE | not authorized
ERROR_DETAIL | You are not authorized to access this form.

Thank you for your help.
Justin

**Comment by justybob** [comment]
I read and acknowledge the Locality model and information.

**Comment by Jegelewicz** [comment]
@justybob manage_locality granted. You will have to log out and log back in for permissions to take.
