### ISSUE TITLE
Error when searching Attribute "Value"

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#7349]
I was trying to find all the items in UAM:EH that were appraised by Joe Crusey. I entered these criteria:

<img width="1272" alt="Screenshot 2024-01-30 at 12 38 11 PM" src="https://github.com/ArctosDB/arctos/assets/17605945/251183d2-996f-4877-8320-2d3f5600f1ee">

And was met with this error:

<img width="384" alt="Screenshot 2024-01-30 at 12 31 03 PM" src="https://github.com/ArctosDB/arctos/assets/17605945/fe5268fd-ecfd-4786-8d84-edf6d51b6486">

What do I need to search for in order to get what I'm looking for?

**Comment by Jegelewicz** [comment]
Put % in the Attribute Value field and see if that works.

**Comment by AJLinn** [comment]
> Put % in the Attribute Value field and see if that works.

Same error pop-up:

An error has occurred. Please include the ErrorID as text in any communications. 
ErrorID: 9C5271AD-469F-44DB-9CABC24E1DA1190B
Mesasge: ERROR: missing FROM-clause entry for table "att_det_1"
  Position: 1035
Details:

**Comment by Jegelewicz** [comment]
@dustymc the error is indicating a determiner problem?

**Comment by Jegelewicz** [comment]
@AJLinn I just noticed that @dustymc did something and it will be in the next release (maybe tonight?).

**Comment by AJLinn** [comment]
Sweet, it works now! thank you!

**Comment by AJLinn** [comment]
For the sake of documenting for posterity, this is what a search for values assigned by a particular individual looks like:
<img width="1271" alt="Screenshot 2024-02-03 at 1 05 40 PM" src="https://github.com/ArctosDB/arctos/assets/17605945/dffc3a07-acd8-4da8-ac86-707e4d4bbbd4">
