### ISSUE TITLE
[external CONTACT] need help removing bad spec events

### ISSUE THREAD

**Issue by jessicatir** [ArctosDB/arctos#7351]
https://github.com/ArctosDB/data-migration/issues/1241

Was talking with @Jegelewicz about this problem in the issue linked above, thought it would be helpful to make a new issue for it.

When I originally bulkloaded the legacy CRCM:Mamm data, I messed up the specimen event dates. I've since bulkloaded the correct spec events, but now the majority of CRCM:Mamm has 2 specimen events per record (one bad, one correct). The record event manager found through the record search tool isn't helpful because I can't see the start/end dates to tell which ones are bad/correct.

My ideal solution would be if every CRCM:Mamm event with a start date of exactly "1800" were deleted (there are no legit specimen events with that start date). Not sure if that's possible. @dustymc any thoughts?

**Comment by dustymc** [comment]
If you can confirm that this is them I can whack 'em.

[temp_crcmtodelete.csv.zip](https://github.com/ArctosDB/arctos/files/14113652/temp_crcmtodelete.csv.zip)

**Comment by jessicatir** [comment]
Looks ready for whacking!

Thank you.
