### ISSUE TITLE
iDigBio Linkouts?

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#7354]
Did we drop iDigBio links on the catalog record page? GBIF and GloBi are there, but not corresponding iDigBio links:

![image](https://github.com/ArctosDB/arctos/assets/11336485/22616457-ffc0-4dc0-a727-939c2c2bd8ed)

I use these often to navigate to iDigBio from each specimen record to grab their iDigBio occurrence IDs (required for uploading MorphoSource media).

**Comment by dustymc** [comment]
Example of something that should work, please.

**Comment by ebraker** [comment]
Any UCM record:

https://arctos.database.museum/guid/UCM:Herp:20855

**Comment by ebraker** [comment]
though looks like other collections are affected

**Comment by Jegelewicz** [comment]
Is or stuff still on iDigBio or has something gone awry?

**Comment by Jegelewicz** [comment]
Nope - here it is at iDigBio - https://www.idigbio.org/portal/records/e1153f3c-5baf-4c91-8484-751d0ef31bc3

**Comment by dustymc** [comment]
>at iDigBio

Thanks, having the pair makes things easier.

Looks like idigbio has randomly changed their API (which still refuses to acknowledge our identifiers.....), I'll patch it.
