### ISSUE TITLE
[ geography request ] Malta: Arctos and GADM don't match, GADM is outdated

### ISSUE THREAD

**Issue by genevieve-anderegg** [ArctosDB/arctos#7355]
# Carefully read the documentation at https://handbook.arctosdb.org/documentation/higher-geography.html before submitting a request.

### Explain what geography needs created.

Malta updated it's provinces (second level divisions) in 2009, increasing from three to the current five (Central Region, Gozo Region, Northern Region, South Eastern Region, Southern Region). https://en.wikipedia.org/wiki/Regions_of_Malta

GADM appears to be outdated and/or doesn't include provinces on its webpage: https://gadm.org/maps/MLT.html
![image](https://github.com/ArctosDB/arctos/assets/83782023/78d61d04-ec12-4d43-a342-7ee50bcfd961)

But Arctos has five regions, including one of the older outdated regions ([Xlokk](https://en.wikipedia.org/wiki/Malta_Xlokk)), and the shapes of current regions do not match the current borders.
![image](https://github.com/ArctosDB/arctos/assets/83782023/9aeba9bf-95bc-438d-878d-0234226e2007)

The province shape files must be included on the download but not on the website.

Can we double check the accuracy of the current shape files provided by GADM in Arctos? It looks like Xlokk in Arctos is equivalent to the current Southeastern region

**Comment by genevieve-anderegg** [comment]
Actually I got turned around- I think the issue is that the shape for the southeastern region in Arctos is correct and current, but the Wikipedia link on the geography page (https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10021253)  is to the old region Xlokk that was divided into the current day Southeastern and Southern regions, so the Wikipedia link just needs to be updated to (https://en.wikipedia.org/wiki/South_Eastern_Region) and it should be renamed from "Xlokk" to "Southeastern Region"

Still confusing that the GADM website isn't up to date as saying it provides these shape files- yet we have them!

**Comment by dustymc** [comment]
I am tabling this; it should be re-opened when something happens with https://github.com/ArctosDB/internal/issues/335.
