### ISSUE TITLE
Feature Request - Make Data Entry more welcoming

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7358]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

When someone selects Enter Data, they are met with this

https://arctos.database.museum/Bulkloader/enter.cfm

![image](https://github.com/ArctosDB/arctos/assets/5725767/ac2ef39c-8d42-497e-8018-92f88a238a32)

The green is quite soothing, but 

# More Information Needed!

not so much - Can we make this more welcoming and instructive?

**Describe what you're trying to accomplish** 
_A clear and concise overview of the goals; why are you asking for this?_

Provide clarity for what you are supposed to do here.

**Describe the solution you'd like**
_How might we accomplish your goals?_

How about this?

# Create Catalog Records

Select one of the options below to begin entering data into Arctos. Once the data entry page you select has opened, you can use the customize button at the bottom of the page to customize the form or select a previously created profile.

## Option 1: Begin with previous records

Use one of these options to bring previously entered data into the form.

* Your [last-entered record](https://arctos.database.museum/Bulkloader/enter.cfm?seed_record_key=key_3405820) (ZSFQ:Herp; Teratohyla spinosa)
* Select from [your previously entered records](https://arctos.database.museum/Bulkloader/browseBulk.cfm?enteredby=jegelewicz)
* Select from [any previously entered record](https://arctos.database.museum/Bulkloader/browseBulk.cfm) (if you have sufficient access)

## Option 2: Choose a collection

Use this option to start from scratch, or from the values stored in a Profile.

* [ACUNHC:Bird](https://arctos.database.museum/Bulkloader/enter.cfm?guid_prefix=ACUNHC:Bird)
* [ACUNHC:Ento](https://arctos.database.museum/Bulkloader/enter.cfm?guid_prefix=ACUNHC:Ento)

Choose one of the options above to proceed. 

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

Leave it.

**Additional context**
_Add any other context or screenshots about the feature request here._

Trying to write documentation for this is difficult when the page header is essentially

# More Information Needed!

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._

**Comment by campmlc** [comment]
I absolutely support this. I also would like to recommend that we make it clearer how we go from entering a single record and saving it to entering a new record - and being able to toggle back and forth with browse and edit.

**Comment by Jegelewicz** [comment]
Also change tool directory to Create Records

**Comment by mkoo** [comment]
Use "Create Record"

**Comment by Jegelewicz** [comment]
AWG says go.
