### ISSUE TITLE
Code Table Request - agent attribute - event

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#7359]
### Goal

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctagent_status doesn't map to https://github.com/ArctosDB/arctos/issues/7352 very well, and I don't think trying to stuff all possible life events in a list is possible anyway (but I can still control vocab if necessary). Restructuring into one attribute would work with the model better, and come closer to satisfying the intent of https://github.com/ArctosDB/arctos/issues/5172 ("at place on date doing thing"). Unless there are better ideas, I will map ctagent_status to type= life event, value=status.

### Table

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctagent_attribute_type

### Proposed Value

~~life event~~

event

### Proposed Definition

Any notable event such as birth or death or being alive or dead.

### Priority

inevitable

### Available for Public View
yes

### Helpful Actions

- [ ] Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

@ArctosDB/arctos-code-table-administrators 

## Approval
_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [ ] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [ ] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection
_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation
_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

- [ ] Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

- [ ] Add or revise the code table term/definition as described above. Ensure the URL of this Issue is included in the definition. URLs should be included *_as text_*, separated by spaced pipes. Do not include HTML in definitions.

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by Jegelewicz** [comment]
This should also work for employment, marriage, children?

**Comment by Jegelewicz** [comment]
But does this mean that all relationships would also be "life events"?

**Comment by dustymc** [comment]
Certainly not initially, I'm mapping as straight-across as I can, but this will absolutely blur the line between relationships and events (that's the point, after all! - https://github.com/ArctosDB/arctos/issues/5172) and yea, maybe we'll end up with fewer, easier-to-understand values as this moves along.

**Comment by Jegelewicz** [comment]
I'm asking because I wonder how someone would record "student of" - as a life event? That feels weird, even if it logically makes sense. Given that, maybe instead of life event we make it more generic somehow? Just "event"?

**Comment by dustymc** [comment]
>Just "event"?

I don't care, but 

1. I need to write code soon, and
2. "he dead" ain't much of an event (still better than what I proposed...)

Something that also covers 'company founded' would be nice, I'll alter the proposal to drop 'life.'

>record "student of" - as a life event?


- student of agent ==> current relationships
- student at time ==> slight expansion of current status vocab
- student of agent at place and time ==>where I hope all of this will end up

So I suppose yea, if 'being a student' is all you know it's better than nothing and fits fine, and maybe someone will expand on it.

**Comment by Jegelewicz** [comment]
Lots of options here - https://www.wordhippo.com/what-is/another-word-for/life_event.html

but I kinda dig

milestone

**Comment by dustymc** [comment]
>milestone

I still don't care, but not sure "noticed they're still breathing" lives up to the hype....
