### ISSUE TITLE
profile selector

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#7360]
we probably have to make the URL profile selector exact-match case-sensitive. Better ideas?

-----------
              >default fields display

Uh - neato!

I'm using an ilike to make the selection less-twitchy, and apparently _ and - are synonymized with that:

```
arctosprod@arctos>> select profile_name,cf_username from cf_cat_rec_srch_profile where profile_name ilike 'advanced_bio_geo';
   profile_name   | cf_username 
------------------+-------------
 advanced_bio-geo | ebraker
 advanced_bio_geo | arctos
```

So the immediate 'solution' is to delete your profile. Finding a real solution probably needs an Issue.

_Originally posted by @dustymc in https://github.com/ArctosDB/arctos/issues/6201#issuecomment-1921846850_

**Comment by ebraker** [comment]
I deleted my profile. Fine with whatever needs to happen in terms of URL format.

**Comment by ebraker** [comment]
It works, thanks!

**Comment by Jegelewicz** [comment]
I think there is a larger issue here - Arctos is going to be confused with any other profiles that share names-ish?

**Comment by dustymc** [comment]
Check if this is still a problem, fix if so.
