### ISSUE TITLE
Need .csv of all accessions

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#7367]
I'm trying to download a csv of all our accessions in Arctos to compare against paper files. I can get to the page where I can see all of the accession entries,  The "Maximum Result Count" is set to 10000, so I can see all the accessions in the browser, but when I click on "Get Accession CSV", it only gives me a file with 1000 lines (there are 7356 total). Is there a way to do an async request, or is that something @dustymc has to pull from the backend?

![image](https://github.com/ArctosDB/arctos/assets/93737929/cd18a030-b9db-43f2-976f-9703651ba3ec)

Thanks in advance for your help!

**Comment by wellerjes** [comment]
@dustymc do you have an estimate of when the next release will happen?

**Comment by dustymc** [comment]
Depends how https://github.com/ArctosDB/arctos/issues/7352 goes - "soon" I hope....

**Comment by wellerjes** [comment]
Is there a workaround or way I could get this data sooner? We have a volunteer coming in tomorrow who we want to start on this project and I need to get the spreadsheet set up for her.

**Comment by wellerjes** [comment]
If not, we have a backup project in mind and can get her started on that tomorrow instead.

**Comment by dustymc** [comment]
What data do you need? (Simpler is easier, but I can try to do what the UI does too.)

**Comment by wellerjes** [comment]
Ideally everything that the UI downloads, if possible; a simplified version would be:

accession number
transaction date / received date
accession type
received from agent
nature of material
transaction remarks

Thanks!

**Comment by dustymc** [comment]
@wellerjes apologies for the delay, you should have email.

**Comment by wellerjes** [comment]
Thank you!
