### ISSUE TITLE
Arctos Report Template Request: NHSM_Arc_Labels2 (Need by Feb 9, 2024)

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7369]
**Description of the report** - [Write a brief description of the report you need. Include link or name of previous report if migrating from a Cold Fusion report.]

NHSM_Arc_Labels2

NHSM_Arc_labels.cfr

**Collection for which the report is needed** - NHSM:Arc

If this is a request to upgrade from an existing ColdFusion report in Arctos complete the following:

**SQL used in ColdFusion report** - copy the SQl from your old report and paste it here - begin and end it with ``` or it will be invisible. Let us know if there is a prefunction to migrate.

```
select
    scientific_name,
     case 
      when trim(flat.sex)='male' then 'M'
      when trim(flat.sex)='male ?' then 'M'
      when trim(flat.sex)='female' then 'F'
      when trim(flat.sex)='female ?' then 'M'
      when trim(flat.sex)='unknown' then 'U'
      when trim(flat.sex)='not recorded' then 'U'
      when trim(flat.sex)='recorded as unknown' then 'U'
    end sex,
    flat.parts,
    cat_num,
    country, 
    state_prov,
    county,
    island,
    island_group,
    feature,
    quad, 
    spec_locality,
    flat.verbatim_coordinates,
    MAXIMUM_ELEVATION,
    MINIMUM_ELEVATION,
    ORIG_ELEV_UNITS,
    collecting_source,
    flat.collectors,
    flat.preparators,
    concatotherid(flat.collection_object_id) as other_ids,
    concatsingleotherid(flat.collection_object_id,'collector number') collector_number,
    concatsingleotherid(flat.collection_object_id,'preparator number') preparator_number,
    concatsingleotherid(flat.collection_object_id,'ASK') ASK,
    concatsingleotherid(flat.collection_object_id,'original identifier') original_identifier,
    
    verbatim_date,
    began_date,
    ended_date,
    flat.habitat
FROM
    flat
WHERE
    flat.collection_object_id IN (#collection_object_id#)
ORDER BY
    country, 
    state_prov,
    county,
    cat_num::int
```

**Priority** - [Please assign a priority so that the DBA knows whether there is any urgency associated with the new template}

The dimensions seem to be 1 7/8" x 2 1/8". It would be great if I could have the report on Monday 2/5, but if not I can manage until Friday 2/9. 

[2024-02-02.16-18.pdf](https://github.com/ArctosDB/arctos/files/14146457/2024-02-02.16-18.pdf)

https://github.com/ArctosDB/data-migration/issues/715#issuecomment-1924719743

**Comment by Jegelewicz** [comment]
@mkoo @dustymc I can work on this if there isn't anyone else to get it done by next Friday - just let me know.

**Comment by mkoo** [comment]
That would be great @Jegelewicz 
thanks!

**Comment by mkoo** [comment]
can you link the relevant report pls (for future issues!) thx
