### ISSUE TITLE
Code Table Request - add shipment type "correspondence"

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#7371]
### Goal
I love that we added shipments to accessions with #6737 but the shipment types are limiting. I'd like to add "correspondence" as a shipment type.

### Context
I wanted to document that I had sent a packet of correspondence to a donor, including the Deed of Gift and Donor Questionnaire, which should come back to the museum. None of the current options are ideal for what I wanted to document with this shipment.

This is also important in sending certified or registered mail when seeking to gain title to abandoned loan items (documenting our attempts at contacting the last known owners is an essential part of the legal process to gain title).

### Table
[Shipment Type](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctshipment_type)

### Proposed Value

~~Correspondence~~

correspondence

### Proposed Definition

Written communications between the collection/institution and another entity

### Priority
_Please describe the urgency and/or choose a priority-label to the right. You should expect a response within two working days, and may utilize [Arctos Contacts](https://arctosdb.org/contacts/) if you feel response is lacking._

Normal priority, I could start using it immediately if available. Right now I enter the information in the Accession Remarks field.

### Example Data
_Requests with clarifying sample data are generally much easier to understand and prioritize. Please attach or link to any representative data, in any form or format, which might help clarify the request._

See accession UAM:EH [UA2023-004](https://arctos.database.museum/accn.cfm?action=edit&transaction_id=21138348) where I make note of mailing the Deed of Gift on certain dates, and receiving on certain dates. 

### Available for Public View
_Most data are by default publicly available. Describe any necessary access restrictions._
No restrictions

### Helpful Actions

- [x] Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

- [x] Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

@ArctosDB/arctos-code-table-administrators 

## Approval
_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection
_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation
_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

- [x] Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

- [x] Add or revise the code table term/definition as described above. Ensure the URL of this Issue is included in the definition. URLs should be included *_as text_*, separated by spaced pipes. Do not include HTML in definitions.

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by dustymc** [comment]
See also https://github.com/ArctosDB/arctos/issues/6937 - there's probably no way to make this consistent, maybe that's a good thing....

Altering request for case.

**Comment by Jegelewicz** [comment]
@ArctosDB/arctos-code-table-administrators any objections? Someone check a box?

**Comment by campmlc** [comment]
Checked.

**Comment by Jegelewicz** [comment]
added
