### ISSUE TITLE
Help - please clarify needed permissions to bulkload part attributes

### ISSUE THREAD

**Issue by falco-rk** [ArctosDB/arctos#7372]
[Part attribute bulkload ](https://arctos.database.museum/tools/BulkloadSpecimenPartAttribute.cfm) says: This tool allows Arctos operators with [role(s)](https://arctos.database.museum/Admin/user_roles.cfm) (manage_records) to create and review Part Attributess. Review and load data entered by users in your collection(s). This form provides access to data entered, perhaps through various forms, by any user who has any access to a collection for which you have (manage_records) access.

However, a user (miabender) with access to the appropriate collection and the required roles
![Screenshot 2024-02-05 at 12 20 53 PM](https://github.com/ArctosDB/arctos/assets/49788908/14c1bff9-c4f6-4fd0-b3b7-d4a706981a9d)
is not able to load data to the tool and gets this error: 
![WhatsApp Image 2024-02-05 at 09 55 09](https://github.com/ArctosDB/arctos/assets/49788908/f33d9eef-b146-45eb-86ed-dbbce537038c)

Help please!

**Comment by dustymc** [comment]
I think I found it, try again (and send data if its still angry).

**Comment by falco-rk** [comment]
It worked! Thanks, Dusty!
