### ISSUE TITLE
Help - specimen cataloged in wrong collection

### ISSUE THREAD

**Issue by kderieg322079** [ArctosDB/arctos#7373]
A bird was cataloged in UMNH:Mamm and therefore assigned a UMNH:Mamm GUID. I'm not sure the best way to go about correcting this record. I tried cloning the record to the bulkloader but it does not let me change the collection to UMNH:Bird. 

This specimen in question is [UMNH:Mamm:45123](https://arctos.database.museum/guid/UMNH:Mamm:45123). 

Do I just need to enter it as a new bird record and encumber the "mammal" record? I'm not even sure I know how to delete records (sounds scary).

Any suggestions appreciated!

**Comment by mkoo** [comment]
Yes deleting catalog records is scary! But the first step is encumbering it so you are on the right track.

I would recommend your path: encumber UMNH:Mamm record and enter the correct UMNH:Bird then delete the encumber mammal record
See how:
https://handbook.arctosdb.org/how_to/How-to-Delete-Specimen-Records.html

let us know if you have any more questions

**Comment by Jegelewicz** [comment]
To easily get the data to the bird collection - use the pull function in the identifiers section of data entry. I'm happy to meet up and walk through it.

**Comment by kderieg322079** [comment]
Awesome, thanks for the reassurance. I've successfully deleted the Mamm record and cataloged it in the Bird collection.
