### ISSUE TITLE
Data Removed from Bulkloader

### ISSUE THREAD

**Issue by AdrienneRaniszewski** [ArctosDB/arctos#7375]
needed to use the bulkloader, but didn't get a response from Mia (miabender). Here's the data. Thanks!

[MiaBenderBulkload-2024-02-05.csv](https://github.com/ArctosDB/arctos/files/14183790/MiaBenderBulkload-2024-02-05.csv)

@Jegelewicz @falco-rk @happiah-madson @dustymc

**Comment by falco-rk** [comment]
Sorry! Thanks for sending me that data.
