### ISSUE TITLE
Feature Request - put a red box around or red font result reponse when record limit is reached.

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#7376]
Need to draw better attention to when your results are limited due to response queries.
Right now it says  (quietly):
![Firefox_Screenshot_2024-02-06T19-02-30 719Z](https://github.com/ArctosDB/arctos/assets/2523089/1fdee17a-6eed-4acc-a5a1-c6625c4f8c3c)

If a red box or the text was in red, bold font ("record limit: 500,000: adjust query or results to return all records"), then user's attention can be drawn to the some record limit being hit.

It's been requested that the true total records be shown but at the current resources that is more problematic -- it's a balance between what people request to see in the results table and what can be cached in flat. This is a fix for now.... thanks!

**Comment by dustymc** [comment]
<img width="688" alt="Screenshot 2024-02-06 at 11 44 01" src="https://github.com/ArctosDB/arctos/assets/5720791/58e66e2c-158b-4586-b3b1-2d565b967ec2">


-------------------


<img width="395" alt="Screenshot 2024-02-06 at 11 40 06" src="https://github.com/ArctosDB/arctos/assets/5720791/d5128761-b839-419d-ae1f-916300a91347">
