### ISSUE TITLE
Need Help with Arctos Error - Invalid attribute for remaining volume and DNA concentration when using µL or ng/µL

### ISSUE THREAD

**Issue by falco-rk** [ArctosDB/arctos#7377]
I think that µ is confusing arctos bulkloaders. Parts attributes are coming back as invalid attribute when µ is in the units (specifically remaining volume with µL and DNA concentration with ng/µL)  

# Error Text
invalid attribute 
![Screenshot 2024-02-06 at 11 47 52 AM](https://github.com/ArctosDB/arctos/assets/49788908/78cec53f-928d-46ff-b164-380cf979333d)

data file: 
[bulkloadPartAttributesData.1._THISONE.csv](https://github.com/ArctosDB/arctos/files/14185248/bulkloadPartAttributesData.1._THISONE.csv)

Data looks like this in the Review and Edit place: 
![Screenshot 2024-02-06 at 2 35 59 PM](https://github.com/ArctosDB/arctos/assets/49788908/44c07d54-b88c-420b-b5eb-afa740a9fca4)

# Where it happened
Part: Bulkload and Part Attribute: Bulkload

# Steps to get there
Uploaded data to Part Bulkloader or Part attribute bulkloader

# Problem
**Community response to describe the problem that caused the error**

# Solution
**Community response with directions for how to correct the problem**

@Jegelewicz @dustymc

**Comment by dustymc** [comment]
See https://handbook.arctosdb.org/documentation/encoding.html

If I load your file, I get what you're getting:
<img width="181" alt="Screenshot 2024-02-06 at 11 51 33" src="https://github.com/ArctosDB/arctos/assets/5720791/086850bb-7519-4bf3-ac64-aa06f7c5d0b8">

If I first....


<img width="629" alt="Screenshot 2024-02-06 at 11 51 03" src="https://github.com/ArctosDB/arctos/assets/5720791/8cbb0d12-0184-4a5b-aef5-3520e2d1b232">

then I get what I expect:


<img width="310" alt="Screenshot 2024-02-06 at 11 51 12" src="https://github.com/ArctosDB/arctos/assets/5720791/30d7a839-20c3-44a4-8904-79971efcf229">


BUT DON'T DO THAT!!! - I'm starting with an unknown (but clearly not UTF) encoding, my editor is being forced to guess, backing out to the source and using known encodings will prevent any bad guesses. (But this is a small file and easy enough to review, just blindly converting is probably OK too....)

**Comment by Jegelewicz** [comment]
@falco-rk from Excel, save as CSV (UTF-8)

**Comment by falco-rk** [comment]
that worked! thanks!

**Comment by falco-rk** [comment]
So the same thing is happening again. I saved from excel as a csv utf-8 and am getting invalid attribute

[invert DNA upload_utf8.csv](https://github.com/ArctosDB/arctos/files/14195436/invert.DNA.upload_utf8.csv)

**Comment by dustymc** [comment]
```

arctosprod@arctos>> select asciiiiiiify(volume_units) from cttissue_volume_units;
NOTICE:  µL
NOTICE:  |µ=181|L=76
 
 
 
arctosprod@arctos>> select asciiiiiiify(part_attribute_units_1) from cf_temp_parts where username='rosiepoulin' limit 1;
NOTICE:  μL
NOTICE:  |μ=956|L=76
```

Arctos needs - uhh, something super-weird?? -  and you supplied what I'd expect??

https://arctos.database.museum/info/ctchange_log.cfm?tbl=cttissue_volume_units - @Jegelewicz did it, IDK....

Looks like somebody figured out how to use it.

```

arctosprod@arctos>> select attribute_units,count(*) from specimen_part_attribute where attribute_type in ('container volume','remaining volume') group by attribute_units;
 attribute_units | count 
-----------------+-------
 mL              |  8687
 µL              |   316
 mg              |  1029
(3 rows)
```

No idea where to go from here, doesn't seem like this should be so complicated, (And everything about units still seems crazy to me, https://github.com/ArctosDB/arctos/issues/1444).

Want me to try to get the Arctos thingee into your data so it can load and deal with this later?

**Comment by falco-rk** [comment]
I need a real fix rather than dealing with it later. We will always need to be able to upload data with µ. Lots of our legacy DNA data will have remaining volume in µL and DNA concentration in ng/µL, and all of the DNA data we generate going forward will have both those attributes. 

I'd be fine with uL instead of µL if that solves the problem.

**Comment by dustymc** [comment]
So I copy-pasted from your message above...

arctosprod@arctos>> select asciiiiiiify('µ');
NOTICE:  µ
NOTICE:  |µ=181
 asciiiiiiify 
--------------


and the webpage of some code tables in Arctos...

Time: 0.778 ms
arctosprod@arctos>> select asciiiiiiify('µL');
NOTICE:  µL
NOTICE:  |µ=181|L=76
 asciiiiiiify 
--------------
 
(1 row)

Time: 0.764 ms
arctosprod@arctos>> select asciiiiiiify('µL');
NOTICE:  µL
NOTICE:  |µ=181|L=76
 asciiiiiiify 
--------------
 
(1 row)

Time: 0.689 ms
arctosprod@arctos>> select asciiiiiiify('µL');
NOTICE:  µL
NOTICE:  |µ=181|L=76
 asciiiiiiify 
--------------
 


and your data in the UI for the parts loader....

arctosprod@arctos>> select asciiiiiiify('μL');
NOTICE:  μL
NOTICE:  |μ=956|L=76
 asciiiiiiify 
--------------


The only outlier is your data. Do whatever you did to github to it and it should work....

**Comment by falco-rk** [comment]
>Do whatever you did to github to it and it should work....

What do you mean? I don't understand what any of that message means...

**Comment by dustymc** [comment]
>Confusing and annoying.

Welcome to the wonderful world of character encoding!! (It's a lot less annoying than it used to be, but still....)
