### ISSUE TITLE
Feature Request - move login name

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#7378]
**Is your feature request related to a problem? Please describe.**

Login as a name type has always been a precarious link, it's more so under attributes.

**Describe what you're trying to accomplish** 

Solid link between agents, operators, and users.

**Describe the solution you'd like**

figure out something better (cf_user agent_id fkey agent maybe)

**Describe alternatives you've considered**

no

**Additional context**

post-https://github.com/ArctosDB/arctos/issues/7352

**Priority**

calling it high, this will find a way to confuse someone

going direct implementation, this is not a significant functional change (but will probably require minor revisions to procedures and some back-end functionality)

**Comment by Jegelewicz** [comment]
preferred name, agent type, operator name?

**Comment by dustymc** [comment]
Next release the agent will be picked as part of the invitation and DOES NOT need a 'login' name added before. I updated https://handbook.arctosdb.org/documentation/users.html, any other documentation should be updated.

**Comment by Jegelewicz** [comment]
https://handbook.arctosdb.org/how_to/How-to-Create-your-Arctos-Team-Users-and-Operators.html will need an update once this is implemented.
