### ISSUE TITLE
Add collecting source to record event collecting source field

### ISSUE THREAD

**Issue by esdearmon** [ArctosDB/arctos#7380]
We have hundreds of records that come from fish hatcheries that do not necessarily fit into the event collecting source "captive". Could we add hatchery to the list of collecting sources? 
@jtgiermakowski

**Comment by dustymc** [comment]
>do not necessarily fit into the event collecting source "captive"

See https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcollecting_source - we will need a definition which draws that boundary. (And it might simplify things if you'd like to re-file this under a [code table request template](https://github.com/ArctosDB/arctos/issues/new?assignees=&labels=Function-CodeTables&projects=&template=code-table-request.md&title=Code+Table+Request+-+).)

**Comment by ewommack** [comment]
@esdearmon  -  definition would be really helpful. 
Our collections have both fish and other types of animals that come from hatcheries, and I've always thought they fell under the "captive" code table source ok. It would be interesting to know why they may not fit.

**Comment by jtgiermakowski** [comment]
> @esdearmon - definition would be really helpful. Our collections have both fish and other types of animals that come from hatcheries, and I've always thought they fell under the "captive" code table source ok. It would be interesting to know why they may not fit.

I think what @esdearmon is thinking is that even though the fish are "captive" early on, they are actually caught in the wild, often much later than their "captive" stage. Sure, we could capture that in the specimen remarks or some attribute, but I think that "wild, from captive stock" could be one category. In herp collections we have the opposite: "captive, from wild stock", where some specimens have been in captivity for some time but were caught in the wild...

**Comment by ewommack** [comment]
Ah, that is the opposite of the occurrence we have with some of our mammals or birds. They come out of the wild at a specific date, and then they are held in captivity and die in captivity (e.g. https://arctos.database.museum/guid/UWYMV:Mamm:6644). We treat those as captive even though they were born wild, because they died in captivity.
If your fish were bred in captivity, but then released and caught free living in the wild, since they died in the wild I would think they should be listed as wild for the event, but you could list captive as an attribute?

**Comment by Jegelewicz** [comment]
Whatever you decide to ask for, please use a [Code Table Request](https://github.com/ArctosDB/arctos/issues/new?assignees=&labels=Function-CodeTables&projects=&template=code-table-request.md&title=Code+Table+Request+-+) so we can evaluate all of the issues that come with one. Then close this issue. Let me know if you need assistance!

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/7405
