### ISSUE TITLE
Code Table Request - New lithostratigraphic unit Blackstone Formation Australia

### ISSUE THREAD

**Issue by WaigePilson** [ArctosDB/arctos#7381]
### Goal
Add the Blackstone Formation (Triassic, Australia)

### Context
Needed to complete importing localities from the UWBM Paleobotany collection

### Table
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlithostratigraphic_formation

### Proposed Value

~~Blackstone Formation~~
Blackstone Formation Australia

Note: for disambiguation we could refer to this as Blackstone Formation (Triassic) or Blackstone Formation (Australia)

### Proposed Definition
A Triassic unit of the Ipswich Coal Measures Group in southeastern Queensland, Australia dating to the Carnian and Norian stages of the Late Triassic; Denmead, Alan Knox. The West Moreton (Ipswich) Coalfield. Government Printer, 1955.; Cranﬁeld, L. C., H. Schwarzbock, and R. W. Day. "Geology of the Ipswich and Brisbane l: 250,000 Sheet area." Geological Survey of Queensland Report 95 (1976). | https://en.wikipedia.org/wiki/Blackstone_Formation,_Australia

### Priority
High

### Helpful Actions

- [x] Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

- [x] Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

@ArctosDB/arctos-code-table-administrators 

## Approval
_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [ ] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection
_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation
_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

- [x] Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

- [x] Add or revise the code table term/definition as described above. Ensure the URL of this Issue is included in the definition. URLs should be included *_as text_*, separated by spaced pipes. Do not include HTML in definitions.

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I think it is a good idea to disambiguate here since there is another unit of the same name in Canada. Either "Blackstone Formation (Australia)" or "Blackstone Formation, Australia".

**Comment by Jegelewicz** [comment]
I prefer the parentheses because commas can get in the way of csv. @dustymc any preference?

**Comment by dustymc** [comment]
Yea avoiding commas is worthwhile when possible. Avoiding punctuation altogether is even better - "Blackstone Formation Australia" seems workable from here.

Someone should formalize this taxonomy following the ICTV to eliminate the possibility of homonyms...

**Comment by Jegelewicz** [comment]
@WaigePilson OK to leave out the comma?

**Comment by WaigePilson** [comment]
@Jegelewicz I think that's okay!

Agreed that we need some way to disambiguate it, even though this somewhat breaks the format of other formations in this table.

**Comment by dustymc** [comment]
>breaks the format 

"Blackstone Formation of Australia" ??????????

**Comment by Jegelewicz** [comment]
> breaks the format

They all end in "Formation".....

**Comment by Jegelewicz** [comment]
If nobody has more comments, I'll add this on Monday as Blackstone Formation Australia

**Comment by Jegelewicz** [comment]
added under special exemption
