### ISSUE TITLE
agent attribute storage format

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#7383]
**Is your feature request related to a problem? Please describe.**

Agent attributes have all sorts of legacy nonsense in them. Can we unify?

**Describe what you're trying to accomplish** 

Unification; something predictable that can be manipulated to work in various UI.

**Describe the solution you'd like**

Some things contain HTML, which is evil because people mangle the tags and those mangle pages.

Some things contain print control characters, which is evil because they come in a bunch of 'standards,' aren't visible in lots of UIs, and break things like Excel and GBIF.

It would be good to settle on one layout method if possible. Markdown might be the closest thing to a standard. It's used here, in some Arctos apps (with a sorta-wonky library), and now has native Lucee support. Other things could work too.

**Describe alternatives you've considered**

Allow arbitrary data

**Additional context**

I'll restrict some types (eg former names) to ``checkfreetext()``.

**Priority**

Sorta-high; don't think this is stopping anything, but I can't format unpredictable things and we're probably accummulating variation faster than I really want to clean it up.

**Comment by Jegelewicz** [comment]
I have no opinion here - I could do any one of those things and be OK as long as I knew which one. I think the user community needs to weigh in.

**Comment by mkoo** [comment]
Which attributes are you talking about? Front facing ones like public profile page's ```biography``` would be good to have either html or md. Remind me, Project descriptions are HTML boxes, yes? As for mangle tags, that is true for all of them so being consistent and predictable would be key to user foibles.

**Comment by Jegelewicz** [comment]
I vote for html markdown can be mangled too.

**Comment by dustymc** [comment]
Addresses are the big thing, but biography too, and who knows where else this is going to lead. 

>consistent and predictable

Yes, all else is details.

> markdown can be mangled

Mangled markdown is just mangled markdown, it won't be properly processed, meh whatever. Mangled HTML tends to eat the pages within which it's supposed to be contained, and Arctos is all HTML. (That's why markdown - and BBCode and similar - exist.) Markdown is definitely safer. Markdown is probably easier to learn, HTML is way more powerful - not sure either of those much matter here. HTML is "native" and takes no back-end support, markdown takes something (but I think that's easy). I (sorta) prefer markdown, but there are definitely no hills I'll die on anywhere around here.

**Comment by dustymc** [comment]
Lucee does not support ACF function ``getsafehtml``, which would complicate sanitizing HTML.

**Comment by mkoo** [comment]
> I (sorta) prefer markdown, but there are definitely no hills I'll die on anywhere around here.

Same. We have markdown in Projects with help text on side (see below) so continuing with md with the help on the side or in a popup window would be ideal-- looking for consistency in implementaion and UI and making it easy. So whatever is decided here should be the same in similar fields
![Firefox_Screenshot_2024-02-26T19-58-06 399Z](https://github.com/ArctosDB/arctos/assets/2523089/729c01eb-e875-4436-a18e-3f716b790c3b)

**Comment by dustymc** [comment]
i just spent a bunch of time fixing notifications, which were mangled by an error involving a busted HTML tag in an agent attribute. I'm proceeding with "anything but HTML" as a matter of security.
