### ISSUE TITLE
part1attribute1 error in bulkloader but NOT in individual entry/screen

### ISSUE THREAD

**Issue by jtgiermakowski** [ArctosDB/arctos#7386]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
bulkloader gives a "part1attribute1 is invalid." error. when i open the individual entry and simply click "Save Edits" WITHOUT doing anything, the error clears and record can be autoloaded.

**To Reproduce**
see above

**Expected behavior**
load record without error

**Screenshots**
see attached

**Desktop (please complete the following information):**
windows 11 and Firefox 
![Screenshot 2024-02-07 at 14-59-01 Edit Bulkloader Records](https://github.com/ArctosDB/arctos/assets/2381228/184f1846-110d-498f-9ac4-44a522ee129a)
![Screenshot 2024-02-07 at 14-58-17 Edit Bulkloader Records](https://github.com/ArctosDB/arctos/assets/2381228/cd9b212f-2ea5-4a25-88e6-9b03c4bb5d84)

**Comment by dustymc** [comment]
Please note the warning at the top of the screen:

>Controlled-vocabulary values (including certain Attributes) which are not as expected may LOSE DATA on save. 

I would need some pre-edited data to diagnose this.

**Comment by dustymc** [comment]
I think I found it - a bunch of units are given as '1.' Units are not allowed with categorical attributes.

**Comment by jtgiermakowski** [comment]
Gotcha! Ok, now at least it's documented. i didn't think of it but it must've been in the bulkloaded file and doesn't catch on in the individual record editor... thanks @dustymc !

**Comment by jtgiermakowski** [comment]
> Please note the warning at the top of the screen:
> 
> > Controlled-vocabulary values (including certain Attributes) which are not as expected may LOSE DATA on save.
> 
> I would need some pre-edited data to diagnose this.

Wow! that disclaimer on the the top of the form could sure **USE SOME BOLD AND LARGE LETTERING!** :-)

**Comment by dustymc** [comment]
>BOLD AND LARGE 

Agreed, in next release.

<img width="1716" alt="Screenshot 2024-02-07 at 14 28 34" src="https://github.com/ArctosDB/arctos/assets/5720791/e5e7512f-e83b-4f33-a810-ec89ada10884">
