### ISSUE TITLE
Agent preferred name policy

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#7387]
See https://github.com/ArctosDB/arctos/issues/7352 - major changes are underway, I would like some guidance on agent preferred name policy. Below is an overview of the current rules. The *intent* or view of Agents seems to be changing, I'm unclear on how far we want or need to take that.  Do we need to retain any or all of these?

Alternatively, feel free to ignore the below - I think there's no particular need to bring any of the old along - and just tell me what, if any, rules should be imposed on agent.preferred_agent_name. 

There is a time component of this - I'll have to do SOMETHING when this goes to production in a week or so, and attempting to tighten rules after that might be difficult (eg if data has come to exist). Loosening rules at any time isn't likely to be problematic.

* preferred name can't start or end with space, nor have multiple spaces together
* Format "Last, First" is disallowed for persons. Preferred name of persons may only contain commas when it ends with ", Jr.", ", Sr.", ", II", ", III", ", IV", ", PhD", or ", MD
* Periods must be followed by spaces in preferred name.
* Person agents may not have a space after uppercase letters in preferred name.
* ``, Sr`` and ``, Jr`` are not allowed.

**Comment by Jegelewicz** [comment]
> Preferred name of persons may only contain commas when it ends with ", Jr.", ", Sr.", ", II", ", III", ", IV", ", PhD", or ", MD

Are those commas really necessary?

> Person agents may not have a space after uppercase letters in preferred name.

That will be a problem for X Musk....

**Comment by dustymc** [comment]
>Are those commas really necessary?

All of that comes from a desire to not create duplicates; that rule was implemented at the same time a bunch of 'Someperson, JR' and 'Someperson, JR.' and 'Someperson JR' and 'Someperson JR.' and 'Someperson, Jr' and ..... were cleaned up. We are going to a model which cannot support the idea of uniqueness, I don't think this is critical (because I don't have a suffix that'll prevent me from getting proper attribution!), maybe someone really wants to be 'Someperson JR' and definitely not 'Someperson, Jr', I sorta think this all has to be between those persons and the collections to whom they donate time or material. (Which suggests perhaps we need some sort of "plz no yell at Arctos, it ain't my fault" documentation somewhere...)

>problem for X Musk

This was also created with the idea that preventing duplicates is THE primary concern. It just can't be where we're going, retaining that probably makes no sense.

**Comment by Jegelewicz** [comment]
> > Are those commas really necessary?
> All of that comes from a desire to not create duplicates

I don't understand how the comma matters? What I am saying is people should NOT have commas in their preferred name at all `Preferred name of persons may not contain commas`

This is kinda gross - but doesn't include the comma - https://emilypost.com/advice/mens-names-and-titles

> > Person agents may not have a space after uppercase letters in preferred name.
> retaining that probably makes no sense

Agree

**Comment by dustymc** [comment]
Lacking other feedback, I'll go with 'people should NOT have commas in their preferred name at all.'

I'll also strip the commas from these (and whatever else shows up before then):

```

 preferred_agent_name |       replace       
----------------------+---------------------
 Ted Lupien, III      | Ted Lupien III
 Charles Seymour, III | Charles Seymour III
 J. R. Raith, III     | J. R. Raith III
 Oakleigh Thorne, II  | Oakleigh Thorne II
 S. A. Rohwer, II     | S. A. Rohwer II
 J. Cloasen, II       | J. Cloasen II
 J. W. Kelly, II      | J. W. Kelly II
 Cyril E. Abbott, PhD | Cyril E. Abbott PhD

```

**Comment by dustymc** [comment]
I had to change a couple agents for https://github.com/ArctosDB/arctos/issues/7326

```
arctosprod@arctos>> update cf_temp_agent set preferred_agent_name ='R. C. Reinhold' where preferred_agent_name='R.C. Reinhold';
UPDATE 1
Time: 1.601 ms
arctosprod@arctos>> update cf_temp_agent set preferred_agent_name ='C. O. B.' where preferred_agent_name='C.O.B.';
UPDATE 1
```
