### ISSUE TITLE
agent bits mapping help

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#7388]
I don't know what to do with the following. None of this makes much sense in the model we're moving to, but might be worth keeping around somehow - I can drop CSV here, or potentially this could be mapped to 'historic' agent attributes.

agent last_edit_by and last_edit_date - edits in the new model will produce deprecated attributes (eg we'll be able to see what was changed, not just who did it), I don't think these have any value, the only data they can carry is "person changed something, we have no idea what."

table agent_merge_history: preserves "old" data as JSON, MAYBE this will remain in the future model if something weird happens at https://github.com/ArctosDB/arctos/issues/7356, otherwise I think I should just leave CSV here and drop the table. Example is https://arctos.database.museum/agents.cfm?agent_id=10001820:

<img width="761" alt="Screenshot 2024-02-08 at 09 44 11" src="https://github.com/ArctosDB/arctos/assets/5720791/78266124-5477-4672-9f97-b9e65f4f867d">

**Comment by Jegelewicz** [comment]
> agent last_edit_by and last_edit_date - edits in the new model will produce deprecated attributes (eg we'll be able to see what was changed, not just who did it), I don't think these have any value, the only data they can carry is "person changed something, we have no idea what."

I think it might be valuable to save the information for a period of time (csv is fine). If we never have to look at it for a year, then it can go away?

> table agent_merge_history: preserves "old" data as JSON, MAYBE this will remain in the future model if something weird happens at https://github.com/ArctosDB/arctos/issues/7356, otherwise I think I should just leave CSV here and drop the table. Example is https://arctos.database.museum/agents.cfm?agent_id=10001820

Sounds fair to me

**Comment by mkoo** [comment]
Would the new verified status be a good substitute for that now @ewommack ? You would at least see if there when the agent was verified and if major edits were made maybe user can add a remark to that attribute.

then it would make the need for this a little more or completely obsolete-- granted requires some behaviour changes for the user but agreed the bits _**as is**_ has low value

**Comment by ewommack** [comment]
I think the new field for tracking attribute edits and such will help a ton.
If I come across a verified agent it will definitely help.

**Comment by dustymc** [comment]
[agent_merge_history.csv.zip](https://github.com/ArctosDB/arctos/files/14413053/agent_merge_history.csv.zip)
