### ISSUE TITLE
Arctos Report Template Request - make a report print more than one label per catalog record (based upon parts)

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7391]
**Description of the report** - [Write a brief description of the report you need. Include link or name of previous report if migrating from a Cold Fusion report.]

@WaigePilson has requested the ability to print the correct number of slide labels for each catalog record. The basic report is prepared - UWBM Paleo slide label 

> > Question - will each slide be a separate part, or will I need to pay attention to part lot count to know how many to print?

> I think in the majority of cases each slide will be a separate part, but if there was a way to also allow for both options, that would be amazing!

So these will parts with the preparation of [slide](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_preservation#slide) and she wants to print the correct number of labels to be able to label all sl;ides for each catalog record in search results.

Has anyone done this yet? @mkoo 

**Collection for which the report is needed** - [Enter the GUID prefix of the requesting collection]

UWBM:PB

If this is a request to upgrade from an existing ColdFusion report in Arctos complete the following:

**SQL used in ColdFusion report** - copy the SQl from your old report and paste it here - begin and end it with ``` or it will be invisible. Let us know if there is a prefunction to migrate.

**Priority** - [Please assign a priority so that the DBA knows whether there is any urgency associated with the new template}

**Comment by dustymc** [comment]
@Jegelewicz I need example records (template edited to include that) to get very far, but something like...


```

<cfloop query="d">
    <cfloop from="1" to="#part_count#" index="idx">
....


```

should get you started.

**Comment by Jegelewicz** [comment]
Thanks - I can't do this right now - but I will get to it!

**Comment by Jegelewicz** [comment]
This probably needs to wait until some data is in Arctos.
