### ISSUE TITLE
Code Table Request - new part name: synthetic DNA

### ISSUE THREAD

**Issue by falco-rk** [ArctosDB/arctos#7397]
### Goal
_Describe what you're trying to accomplish. This is the only necessary step to start this process. The Committee is available to assist with all other steps. Please clearly indicate any uncertainty or desired guidance if you proceed beyond this step._

To differentiate naturally derived DNA from synthetically derived DNA

### Context
_Describe why this new value is necessary and existing values are not._

There are different permit restrictions associated with some synthetically derived DNA.

### Table
_Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table or value. This may involve multiple tables and will control datatype for Attributes. OtherID requests require BaseURL (and example) or explanation. Please ask for assistance if unsure._

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name

### Proposed Value
_Proposed new value. This should be clear and compatible with similar values in the relevant table and across Arctos._

synthetic DNA

### Proposed Definition
_Clear, complete, non-collection-type-specific **functional** definition of the value. Avoid discipline-specific terminology if possible, include parenthetically if unavoidable._

Artificially created strands of DNA that are  synthesized in a laboratory rather than occurring naturally. This includes PCR, whole genome amplifications, cDNA, etc.

### Collection type
_Some code tables contain collection-type-specific values. ``collection_cde`` may be found from https://arctos.database.museum/home.cfm_

all

#### Attribute data type
_If the request is for an attribute, what values will be allowed?
free-text, categorical, or number+units depending upon the attribute (TBA)_

n/a

#### Attribute controlled values
_If the values are categorical (to be controlled by a code table), add a link to the appropriate code table. If a new table or set of values is needed, please elaborate._

n/a

#### Attribute units
_if numerical values should be accompanied by units, provide a link to the appropriate units table._

n/a
#### Part preservation attribute affect on "tissueness"
_if a new part preservation is requested, please add the affect it would have on "tissueness": No Influence, Allows, or Denies_

n/a

### Priority
_Please describe the urgency and/or choose a priority-label to the right. You should expect a response within two working days, and may utilize [Arctos Contacts](https://arctosdb.org/contacts/) if you feel response is lacking._

### Example Data
_Requests with clarifying sample data are generally much easier to understand and prioritize. Please attach or link to any representative data, in any form or format, which might help clarify the request._

### Available for Public View
_Most data are by default publicly available. Describe any necessary access restrictions._

### Helpful Actions

- [ ] Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

- [ ] Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

@ArctosDB/arctos-code-table-administrators @Jegelewicz

## Approval
_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [ ] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [ ] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection
_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation
_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

- [ ] Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

- [ ] Add or revise the code table term/definition as described above. Ensure the URL of this Issue is included in the definition. URLs should be included *_as text_*, separated by spaced pipes. Do not include HTML in definitions.

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by dustymc** [comment]
Is synthetic DNA fundamentally different than eg '[a cast of a skull](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecpart_attribute_type#representation)'?

**Comment by falco-rk** [comment]
Yes and no. But I need to be able to track it easily as synthetic DNA is not subject to the same permitting requirements as naturally occurring DNA.

**Comment by Jegelewicz** [comment]
@falco-rk that being the case, could the addition of the [representation](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecpart_attribute_type#representation) part attribute suffice here? An appropriate permit type for these materials would be useful too.

**Comment by dustymc** [comment]
>useful

Permits also won't allow a typo made by a first-day intern to get you in legal trouble, where trying to infer permit-stuff from part names could.

**Comment by falco-rk** [comment]
>representation part attribute suffice here

yeah, that would probably work. I didn't realize that is what Dusty was saying before.

To clarify my permit concerns: Permits we hold for marine mammals requite that in order for us to distribute samples and DNA from marine mammals, the recipient needs to hold specific permits. An exception to that is that we are allowed to distribute synthetic DNA without the recipient needing those permits.

**Comment by Jegelewicz** [comment]
> An exception to that is that we are allowed to distribute synthetic DNA without the recipient needing those permits.

Create a permit in Arctos that states "no permit required - synthetic DNA" and apply it to all accessions of "synthetic DNA".

Are there cases where a single catalog record has both DNA and "synthetic DNA"? That could mess with this plan...

**Comment by falco-rk** [comment]
>Are there cases where a single catalog record has both DNA and "synthetic DNA"? That could mess with this plan...

Yes, many of the catalog records with synthetic DNA also have naturally occurring DNA, which was used as a template to create the synthetic DNA

**Comment by Jegelewicz** [comment]
So that makes adding a permit difficult, but not the part attribute. Does that seem like some sort of deal-breaker?

More and more I see that many things we associate with catalog records really need to be associated with parts....

**Comment by dustymc** [comment]
>what Dusty was saying

I'm just trying to understand the situation.

>accessions

Not sure how that's related??

>makes adding a permit difficult

I'm definitely lost....

>recipient needs to hold specific permits.

There's nothing quite like that in Arctos. Maybe there should be, but I think it would be wildly complicated - it'd be some intersection of jurisdiction and taxa and part attributes at some time, or something. Might be something https://github.com/ArctosDB/arctos/issues/6746 could help with (probably in the form of something like a checklist, not a 'sorry, you can't print that mailing label...' error).

I suspect the attribute would add a lot of consistency, probably the legalities surrounding synthetic DNA are similar to those for casts vs. bones and similar situations.

**Comment by campmlc** [comment]
If I understand correctly, @falco-rk needs to have the part distinguished as synthetic DNA so that she can clearly document that any loans or accessions or other usage of these parts is distinct from the loan of "original" DNA or RNA.  In a loan invoice, for example, she'd need to show that the sample loaned was synthetic DNA as part of the itemized list of contents. @falco-rk is this a correct interpretation? You could still associate the permit at the record level, but the loaned items would be allowed or not covered by the permit terms. Could you do this with part = "DNA" and part attribute = "synthetic"? Your loan reports could be modified to show this. And that way you'd also have metadata associated with the method for creating the synthetic DNA. ?

**Comment by campmlc** [comment]
It isn't a representation - it is real DNA. It is a physical entity. But it is not made by an organism - it is synthetically created in a lab. new part attribute "origin" = "synthetic"?

**Comment by falco-rk** [comment]
yes, we need to be able to track what DNA is synthetic DNA to make sure its obvious on loans and so we know if we can load those samples.

I think i'm okay with part = "DNA" and part attribute = "representation" with synthetic part attribute remarks and details of generation in method. We won't have other parts in our collection that will have "representation" part attributes, so I should be able to find them in our collection pretty easily.

**Comment by Jegelewicz** [comment]
@falco-rk given that - I will treat them that way and close this. If at any time you determine this method isn't sufficient, we can revisit and the things in question should be easy to find.
