### ISSUE TITLE
permission denied for table media_relations?

### ISSUE THREAD

**Issue by jebrad** [ArctosDB/arctos#7398]
Hello, one of my operators clairek got the following message when she tried to create media via the drag and drop tool.  I was able to do it without error when logged in as me.  I checked and clairek does indeed have manage media permissions so I am not sure why this error occurred.  Our plan is to have Claire continue to link media using this one-at-a-time procedure.

Please advise.  Thank you, Jeff

ERROR_ID	0E5F4849-5A66-481A-8B5B37E845CACA5A
ERROR_TYPE	SQL
ERROR_MESSAGE	ERROR: permission denied for table media_relations
ERROR_DETAIL	
ERROR_SQL	insert into media_relations ( MEDIA_ID, MEDIA_RELATIONSHIP, CREATED_BY_AGENT_ID, RELATED_PRIMARY_KEY ) values ( 10827779, 'documents cataloged_item', 21350800, 31451676 )

**Comment by dustymc** [comment]
https://arctos.database.museum/Admin/user_roles.cfm?action=defineRole&role_name=manage_specimens

Making the link involves altering the "specimen record" so requires manage_specimens. (Seems mostly right to me, but those can always be tuned if anyone wants to suggest something different.)

**Comment by jebrad** [comment]
OK!  I just looked at that documentation and thought it might be the problem, but manage_media seems to indicate it's enough to create media, so I didn't want to give her that extra permission.   I will do that now.  

She is only creating media via this one-at-a-time method, so I think (and Teresa agreed) this prevents her messing with anyone else's specimens or media.  

Ideally, in the future I would like people with minimum training to be able to create media in this way, so if the permissions can be changed to allow this type of media creation without permitting that user to mess with other peoples media, that would be great.   But not urgent, I will just keep a closer eye on Clairek for now.

Thanks!
