### ISSUE TITLE
Search Catalog Records will not load unless logged in

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#7399]
The main search page will not load. However, if I log in all is well and there is no issue with responsiveness. A student emailed and noticed this issue last night.

Error message:
![image](https://github.com/ArctosDB/arctos/assets/11336485/2ad262cb-4e98-442b-9845-0637a442ae2c)

**Comment by dustymc** [comment]
Looks like mostly just you in there, I'll bounce the front end in about 5 minutes, when hopefully you won't be in the middle of something.....

**Comment by ebraker** [comment]
@dustymc totally fine - bounce me out!

**Comment by dustymc** [comment]
Seems happy now.
