### ISSUE TITLE
[CONTACT: Blocked Network]

### ISSUE THREAD

**Issue by itsdebartha** [ArctosDB/arctos#7400]
restricted IP: 103.176.117.40 (my laptop) and 42.110.165.33 (my mobile)

I am trying to apply to the GSoC 2024 through the R Project for Statistical Computing, which is listed [here](https://github.com/rstats-gsoc/gsoc2024/wiki/arctosr%3A-An-interface-to-the-Arctos-Database-for-R). But it is saying that this IP is blocked.

It would help immensely if someone unblocks the above IP addresses.

Thank you
Debartha Paul

**Comment by mkoo** [comment]
Hello Debartha, you are attempting a connection which requires an api key. Please see our policy here: https://arctosdb.org/arctos-api-policy/

Otherwise please try our frontend public portal at https://arctos.database.museum/ and let us know if you have any problems. Thanks!
