### ISSUE TITLE
customize search result does not include attribute units

### ISSUE THREAD

**Issue by amgunderson** [ArctosDB/arctos#7403]
I am trying to download specimen records with weight and measurements attributes but the customize results form does not include the units fields for those attributes. I need to know the units please make those fields an option for search results. #arctosusedtodothis

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by amgunderson** [comment]
the "attribute details" option for a search result output produces an entirely useless string in a single column in the csv file. Yes the details are there but when dealing with hundreds of specimens with various attributes there is no excel wizardry that can parse that out into functional data. The attribute details option for search results should be removed as it only offers further frustration with Arctos.

 [
  {
    "attribute_date": "2004-02-26",
    "attribute_type": "age class",
    "attribute_units": null,
    "attribute_value": "adult",
    "attribute_method": null,
    "attribute_remark": null,
    "attribute_determiner": "University of Alaska Museum"
  },
  {
    "attribute_date": "2004-02-26",
    "attribute_type": "reproductive data",
    "attribute_units": null,
    "attribute_value": "1 full-term fetus",
    "attribute_method": null,
    "attribute_remark": null,
    "attribute_determiner": "University of Alaska Museum"
  },
  {
    "attribute_date": "2004-02-26",
    "attribute_type": "sex",
    "attribute_units": null,
    "attribute_value": "female",
    "attribute_method": null,
    "attribute_remark": null,
    "attribute_determiner": "University of Alaska Museum"
  },
  {
    "attribute_date": "2004-02-26",
    "attribute_type": "total length",
    "attribute_units": "cm",
    "attribute_value": "167",
    "attribute_method": null,
    "attribute_remark": null,
    "attribute_determiner": "University of Alaska Museum"
  },
  {
    "attribute_date": "2004-02-26",
    "attribute_type": "weight",
    "attribute_units": "kg",
    "attribute_value": "99.50",
    "attribute_method": null,
    "attribute_remark": null,
    "attribute_determiner": "University of Alaska Museum"
  }
]

**Comment by dustymc** [comment]
I think this is a repeat of https://github.com/ArctosDB/arctos/issues/6111

We can cache things, I'd need details, there are limits (in possible number of columns, and in how much information can survive flattening).

Displaying uncached attributes would require more processing power than I have, if I had more I'd be happy to use it. (Above limitations would still apply.)

There's a download option (with several sub-options) in the tools wodget.

There's the JSON option mentioned above. (Did anyone ever build an openrefine recipe or similar?)

I can build reports that do most anything, just need details to get started.

@mkoo what'd I miss, and how can we better communicate this?

**Comment by Jegelewicz** [comment]
> there is no excel wizardry that can parse that out into functional data

Have you tried parsing the JSON column?  [Parse text as JSON or XML (Power Query)](https://support.microsoft.com/en-us/office/parse-text-as-json-or-xml-power-query-7436916b-210a-4299-83dd-8531a1d5e945)

**Comment by amgunderson** [comment]
The download attributes tool provides a list of attributes with each attribute in a row and it's corresponding guid in that row, so it has many rows with the same guid but a different attribute in each row. This is entirely incongruent with a search result that includes date, location, species, and everything else I want to know about specimens. There is no excel wizardry worth my time to get those 2 tables merged into a dataset that includes specimen data with attributes.

ARCTOS USED TO DO THIS JUST FINE. I find it absolutely fundamental functionality to be able to download specimen data, including standard measurements.

**Comment by amgunderson** [comment]
> Have you tried parsing the JSON column? [Parse text as JSON or XML (Power Query)](https://support.microsoft.com/en-us/office/parse-text-as-json-or-xml-power-query-7436916b-210a-4299-83dd-8531a1d5e945)

I have no idea what this means...

**Comment by amgunderson** [comment]
I need to do this like right now for a loan inquiry so Arctos is failing me once again because you all changed things that were not broken. I am now going to attempt to find my collections data in GBIF or VertNet...this is a scathing 1 star review of Arctos. Do Not Recommend.

**Comment by amgunderson** [comment]
Here is the file I get with "attribute details" in a search result
[ArctosDataHq9fpJ6XT6.csv](https://github.com/ArctosDB/arctos/files/14271784/ArctosDataHq9fpJ6XT6.csv)

Here is the download attributes file
[attributeDataDownload.csv](https://github.com/ArctosDB/arctos/files/14271788/attributeDataDownload.csv)

If you can figure out a way to get the standard measurements inline with all other specimen data you can be my hero but arctos used to spit this out no problem and papers have been published on standard measurements directly from arctos downloads. Now that is not possible and I can't even provide that data to anyone interested.

**Comment by dustymc** [comment]
> the standard measurements

If you can translate that into specifics I can probably make it happen.

**Comment by amgunderson** [comment]
I want to be able to make it happen for myself, as every other collection manager in Arctos should be able to. A 1 time sql search is not a sustainable database interaction.
weight, total length, tail length, hind foot with claw, ear from notch.

**Comment by dustymc** [comment]
>1 time sql search

That's not what was offered....

> weight, total length, tail length, hind foot with claw, ear from notch.

I think that's all here:


<img width="314" alt="Screenshot 2024-02-13 at 12 45 23" src="https://github.com/ArctosDB/arctos/assets/5720791/a9883834-6fea-4860-abe8-df88ece21f04">

<img width="334" alt="Screenshot 2024-02-13 at 12 45 39" src="https://github.com/ArctosDB/arctos/assets/5720791/4e818b1f-4899-410d-b3ba-10a4a4e82409">

**Comment by amgunderson** [comment]
that spits out measurements like this, 326-91-46-18‚â°124
do not get me started on labels. I already have to manipulate that file to get it to talk to my mail merge word doc because arctos stopped making labels. I can get the data from that but vertnet already sent me what I need without any excel manipulation required.
What meeting do I need to attend to get arctos to put measurements into a search result like it used to do?

**Comment by amgunderson** [comment]
The attributes are there, all we need are the units fro them to be useful. Vertnet spits out standardized values, mass in grams, lengths in millimeters.

<img width="483" alt="Screenshot 2024-02-13 at 12 38 14 PM" src="https://github.com/ArctosDB/arctos/assets/8440698/6a0da909-c83a-4a88-8c6e-ea3b00e4a5d1">

**Comment by dustymc** [comment]
>units

That's a bug, it's now patched but will take a couple days to rebuild the cache, I can prioritize if you will tell me what you need at the moment.

**Comment by amgunderson** [comment]
I need to find all carnivorans (members of the order Carnivora) with skeletons or long bones with a known weight. The searches are simple and work fine. The results need to display the weight with units, along with all the other basics, species, date, location. I need to do this myself because I have to search for multiple parts, skeleton, ulna, femur, etc., because some specimens have whole skeletons but some lynx, foxes, and wolves were collected with a radius and ulna only and many hundreds of sea otters were collected with just a femur. No one should have to ask you to do their searches for them. What should have taken half and hour of arctos queries and spreadsheet copy and pasting has taken all morning and has yet to be completed because VertNet can give me a result for skeletons but not the other searches for long bones. And, of course, Arctos can give me all the specimen records but with a weight=3.7, those results are meaningless.
facepalm emoji...
I could figure out how to parse the JSON or record a macro for excel after 10 tries to transpose columns into rows and find and replace brackets and commas and merge weight values with units and repeat that 8 times but why do I have to do that now when Arctos used to spit out weights and measurements as specimen data?

**Comment by mkoo** [comment]
Sorry for all the excel gymnastics @amgunderson 

This is the fundamental issue I've been pointing out with the tool-- it needs to transpose the attributes JSON blob. Caching is just a short term measure and wont satisfy everyone since everyone has their own fav attributes

If we cannot/ dont have bandwidth currently to incorporate some JSON parser into the attributes tool but I think this is easier to manage with a report-- so we need a new report that would transpose attributes into the the fields/columns that you want and for it to include the measurements. Reports can be customized to the specific collection needs and uses-- can also export as plain old CSV. 

@amgunderson can you share or send me a Excel file the way you want it?

**Comment by amgunderson** [comment]
Looks like Dusty fixed it, for these standard measurements anyway, they now show up in the results with their units attached. Thank you!
