### ISSUE TITLE
[CONTACT: Blocked Network]

### ISSUE THREAD

**Issue by rspfau** [ArctosDB/arctos#7408]
restricted IP: 173.255.46.28

I'm not able to access Arctos from our university campus. It states:

Your IP (173.255.46.28) or organization has been blocked. You may wish to check your computer for malicious software and alert your IP or organization. Further intrusion attempts may result in more restrictive blocks. Access from this network has been restricted. You may open an [Issue on our GitHub ](https://github.com/ArctosDB/arctos/issues/new?labels=contact&template=contact-arctos.md&title=%5BCONTACT:+Blocked+Network%5D&body=restricted+IP:+173.255.46.28)to request access.
We cannot consider requests which do not include your IP address, "173.255.46.28"

**Comment by dustymc** [comment]
Restrictions removed, it should clear up within 10 minutes.
