### ISSUE TITLE
address coordinates 

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#7410]
**Is your feature request related to a problem? Please describe.**

https://github.com/ArctosDB/arctos/issues/7352 doesn't include a place for coordinates. They've never been very reliably generated, and that's become much worse since we're no longer paying for Google Maps API access.

**Describe what you're trying to accomplish** 

Do something transparent.

**Describe the solution you'd like**

1. Ya'll tell me, or
2. I will dump existing data in https://github.com/ArctosDB/arctos-assets with next release.

**Describe alternatives you've considered**

^^

**Additional context**

https://github.com/ArctosDB/arctos/issues/7409 - not sure if BerkeleyMapper has changed, the data are wonky, ?? but mapping has never been very reliable either.

**Priority**

Something will happen with next release.

**Comment by Jegelewicz** [comment]
Do we actually need this?

**Comment by dustymc** [comment]
This whole thing just looks like a failed experiment to me. (Not because it didn't work, but because it doesn't work well without a tool we can no longer access.) I don't think there's any real value. One can occasionally map whatever arbitrary points the various services have been able to produce, and I presume everyone just ignores whatever's missing or incorrect. Clearly it's been used( ONCE in the last couple years since BerkeleyMapper swapped to SSL. If we retain this, and I don't think we should, I'll vote to do it with the same varchar/duct-tape field we're using now.

Adding adequate support would of course change my view, but that does not seem likely.

**Comment by mkoo** [comment]
I think we have to prioritize the GM API credits for localities and propose to dump the address coordinates for now. We can always implement a proper fix at a later date. But adding/saving coordinates does not affect shipping and other local transaction functions for collections demonstrably but would take effort and resources away from other higher priority issues. 

So ok with option 2

**Comment by ebraker** [comment]
I vote to please keep this. I use this feature in annual reports and it is certainly compelling for grant narratives. I don't even need precision. Honestly a dot on a state or country gets the point across.

**Comment by dustymc** [comment]
Table stashed in https://github.com/ArctosDB/arctos-assets
