### ISSUE TITLE
Code Table Request - Add Floweree Member to the lithostratigraphic member table

### ISSUE THREAD

**Issue by WaigePilson** [ArctosDB/arctos#7413]
### Goal
Add the Floweree Member to the lithostratigraphic member code table

### Context
Necessary to import locality data from UWBM:PB collection

### Table
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlithostratigraphic_member

### Proposed Value
Floweree Member

### Proposed Definition
Member of the Marias River Formation (Upper Cretaceous) outcropping in Montana. Thicness as much as 30 m (98 ft). Vuke, S.M., Porter, K.W., Lonn, J.D., and Lopez, D.A., 2007, Geologic Map of Montana - Compact Disc: Montana Bureau of Mines and Geology: Geologic Map 62-C, 73 p., 2 sheets, scale 1:500,000. This map was digitized in 2012 as a result of a contract between the U.S. Geological Survey and the Montana Bureau of Mines and Geology. | https://mrdata.usgs.gov/geology/state/sgmc-unit.php?unit=MTKmrb

### Priority
High

### Helpful Actions

- [x] Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

- [x] Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

@ArctosDB/arctos-code-table-administrators @Nicole-Ridgwell-NMMNHS 

## Approval
_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [ ] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection
_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation
_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

- [x] Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

- [x] Add or revise the code table term/definition as described above. Ensure the URL of this Issue is included in the definition. URLs should be included *_as text_*, separated by spaced pipes. Do not include HTML in definitions.

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by Jegelewicz** [comment]
- [ ] The unit is registered in a national geologic database, with a link included in the documentation (for example: https://ngmdb.usgs.gov/Geolex/search). If the unit is not listed in a national database, the documentation should include a link to a publication that describes the unit.
- [ ] The term is properly formatted as "Name Type". Lithology descriptors should only be included when the unit is not referred to both with and without the descriptor. When a lithology descriptor is included, the format is "Name Lithology Type". Acceptable examples: Cameron Creek Member, Down Cliff Sand Member
- [ ] In addition to the required links, it is strongly preferred that the documentation include a short description of the unit. Information suggested to be in the description includes: the geographic region(s) in which the unit outcrops, geologic age, and dominant lithology.
