### ISSUE TITLE
Records appearing blank after bulkloading

### ISSUE THREAD

**Issue by kderieg322079** [ArctosDB/arctos#7415]
**Describe the bug**
I had about 20 records in the bulkload table that I set to "autoload_core" and the records sort of exist but were not assigned a GUID and therefore the record doesn't really exist. If I search the accession, the records that had already been loaded a few weeks ago are visible, but the ones I loaded today are not. I can also see the blank records in the search results table if I search by other identifiers, in this case our field number "UTF".

**To Reproduce**
1. Search by the identifiers UTF 1054-1075.
![image](https://github.com/ArctosDB/arctos/assets/82051765/7ca38aeb-a3e2-4f59-ab4f-6a87447bcdd1)
2. You will see blank records in the results table
![image](https://github.com/ArctosDB/arctos/assets/82051765/c2cd2d98-4789-47cf-a6d5-6db864c8ae7d)
2. Search by accession ID 
![image](https://github.com/ArctosDB/arctos/assets/82051765/af92f030-cddd-4e7b-b78a-03f0b783adf1)
3. You'll see the previous records that loaded correctly and the new blank ones. When you click on the link-out arrow, it just brings your back to the search page.
![Arctos_blank_records](https://github.com/ArctosDB/arctos/assets/82051765/8fcd05ae-4fd5-4dc4-87ee-3613a2173c16)

**Expected behavior**
Usually catalog numbers are automatically assigned when I load the records.

**Data**
I did not download these records before loading them... please tell me there is a way to get the data back so I don't have to re-enter each one...

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome 120.0.6099.216

**Additional context**
I realize this may not be a bug but in fact an error on my part. If so, please help me correct this error.

**Priority**
High

**Comment by dustymc** [comment]
See https://github.com/ArctosDB/arctos/issues/6705

**Comment by kderieg322079** [comment]
Ah, I am relieved that I didn't make some terrible error. Thanks!
