### ISSUE TITLE
Filling Data request

### ISSUE THREAD

**Issue by jldunnum** [ArctosDB/arctos#7417]
Dave Hafner, previous curator of mammals at NMMNHS has requested a download of the mammal records cataloged into MSB with the identifiers parsed out into their own columns (something we all would like the ability to do). He would like individual columns with the MSB guid, the prior Institutional (NMMNHS) catalog number, and the tissue number (LVT). Despite using Arctos for almost 20 years, I no longer know how to do this. Can someone help? Thanks

**Comment by jldunnum** [comment]
here is the saved search
https://arctos.database.museum/saved/NMMNHS%20mammal%20specimens

**Comment by Jegelewicz** [comment]
This sounds like a report (for download to csv). 

But here you go (I hope!)

[Uploading ArctosDatav3bJgrF0c9.csv…]()

**Comment by mkoo** [comment]
@dustymc Can you please write a SQL for the reporter that includes a spot for someone to add the "identifier issued by"? and then I will create a ledger-like report that Jon (anyone) can print that includes separate columns for the Issuer and the identifer value

@jldunnum would a report work then? Also what is "LVT"?

**Comment by mkoo** [comment]
> This sounds like a report (for download to csv).
> 
> But here you go (I hope!)
> 
> Uploading ArctosDatav3bJgrF0c9.csv…

oh, I see Teresa and I were writing at the same time! What are trying to link to (doesnt go anywhere)?

**Comment by Jegelewicz** [comment]
> doesnt go anywhere

my bad - I wasn't patient enough to let the file load - its there now.

**Comment by dustymc** [comment]
> SQL for the reporter

Yes, but I'm lost - can someone please tell me column names plus contents?

**Comment by Jegelewicz** [comment]
It's probably not that easy because

NMMNH is found via issued by
LVT is actually in the identifier value (and not reliably associated with an issued by)

**Comment by dustymc** [comment]
>NMMNH is found via issued by

That should be super-easy, I just need details.

>LVT is actually in the identifier value 

Yea, that is incredibly unlikely to be fully recoverable. Here's data in case anyone wants to do something with it.

```

create table temp_lvt as
select 
    guid_prefix,
    guid,
    other_id_type,
    display_value,
    getPreferredAgentName(issued_by_agent_id) issued_by
from 
    coll_obj_other_id_num
    inner join flat on coll_obj_other_id_num.collection_object_id=flat.collection_object_id
where display_value ilike '%lvt%';

```
[temp_lvt.csv](https://github.com/ArctosDB/arctos/files/14289491/temp_lvt.csv)

**Comment by jldunnum** [comment]
OK thanks for working on this everyone. I guess a report would work..... Again the frustration here is that these were all very simple returnables before our upgrade. For collections that take in lots of other collections we have to deal with a ton of other identifiers. Its super hard to track and sort on all this now. Makes me sad. We had talked about maybe being able to select a few identifiers to parse out in their own columns. I know you all are not in favor, but I think having institutional catalog number as one that could always be pulled out in its own column would be very useful for a lot of collections.

LVT stands for Las Vegas Tissue - these were the field tissue numbers assigned by Dave Hafner and Brett Riddle (like our NK number) and held at UNLV until Brett's retirement, then transferred to us. They are associated with the NMMNHS mammal catalog records which were downtown and are now archived at MSB.

______________________________________________________________
Jonathan L. Dunnum Ph.D. (he, him, his)
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
Research Assistant Professor (LAT)
Department of Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

Chair, Systematic Collections Committee, American Society of Mammalogists
Latin American Fellowship Committee, ASM

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by Jegelewicz** [comment]
@jldunnum your answer is here - https://github.com/ArctosDB/arctos/issues/7417#issuecomment-1944893330

**Comment by dustymc** [comment]
>LVT stands for Las Vegas Tissue

If you can somehow pick the right stuff out of my CSV I'd be happy to show you what the new system can do with it.

**Comment by jldunnum** [comment]
All those NMMNHS numbers have corresponding MSB numbers so what I would need is three columns that have the MSB:Mamm #, the NMMNHS # and the LVT #

**Comment by Jegelewicz** [comment]
@jldunnum the MSB Mamm number is in the GUID column?

[ArctosDatav3bJgrF0c9(1).xlsx](https://github.com/ArctosDB/arctos/files/14299035/ArctosDatav3bJgrF0c9.1.xlsx)

**Comment by jldunnum** [comment]
That file is great! Not sure why I couldn't or didn't see it in your comment before. I was just looking at Dusty's csv. 
Thanks, how did you generate it?

**Comment by Jegelewicz** [comment]
I downloaded search results and added the two columns on the right - you can see the formulas in there for getting to the identifiers.

**Comment by jldunnum** [comment]
Ok so you did it in excel not Arctos

______________________________________________________________
Jonathan L. Dunnum Ph.D. (he, him, his)
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
Research Assistant Professor (LAT)
Department of Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

Chair, Systematic Collections Committee, American Society of Mammalogists
Latin American Fellowship Committee, ASM

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by Jegelewicz** [comment]
> in excel not Arctos

yes
