### ISSUE TITLE
Code Table Request - add *profile* as new ctagent attribute

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#7418]
### Goal
Polished public profile pages for agents

### Context
distinguish between biographical remarks and others to allow a more polished public profile page

Once created we would like to have help moving things that are currently: remarks | curatorial remarks to this attribute as appropriate.

### Table

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctagent_attribute_type

### Proposed Value
_Proposed new value. This should be clear and compatible with similar values in the relevant table and across Arctos._

~~biography~~ profile 

### Proposed Definition
This is reserved for biographical information that will be displayed publicly under the heading "Biography". We suggest including information that helps distinguish this person, especially their relationship to the collection or other activity in Arctos. Private personal information should NEVER be included and will be removed by administrators.

### Collection type
available to all collection types

#### Attribute data type
free-text

### Priority
Urgent

### Available for Public View
YES

### Helpful Actions

- [x] Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

- [x] Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

@ArctosDB/arctos-code-table-administrators 

## Approval
_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection
_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation
_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

- [ ] Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

- [ ] Add or revise the code table term/definition as described above. Ensure the URL of this Issue is included in the definition. URLs should be included *_as text_*, separated by spaced pipes. Do not include HTML in definitions.

- [ ] SPECIAL IMPLEMENTATION: we should discuss how to automatically assign current biographical remarks to new CT attribute. (maybe remarks over a specific character threshold?) Some collections have extensive biographies to mark as biography-- see UAM:EH, ART; MVZ:Arch, etc

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

**Comment by dustymc** [comment]
Boxes are checked, I'll just create this with the release unless someone has better ideas like NOW.


> SPECIAL IMPLEMENTATION: we should discuss how to automatically assign current biographical remarks to new CT attribute. (maybe remarks over a specific character threshold?) Some collections have extensive biographies to mark as biography-- see UAM:EH, ART; MVZ:Arch, etc

Here's more than 50 characters in remarks. There are certainly things that might count as a bio with fewer characters ("MVZ PhD"), but also thousands of eg 'UAM ethnology',  and 50 characters of course still contains lots of things that aren't really a biography. Still seems like the most reasonable place to start, maybe there's some magic number that'll reveal itself in here, or make a spreadsheet, or ??? - whatever, find some way to identify things that should be transferred and I can move them with the release. (Or we can build loaders, or do this later, or whatever.)

[temp_agent_remarks_bio_maybe.csv.zip](https://github.com/ArctosDB/arctos/files/14289548/temp_agent_remarks_bio_maybe.csv.zip)

https://github.com/ArctosDB/arctos/issues/7383 will also have a significant impact on this (but we don't have to figure that out before implementation).

**Comment by mkoo** [comment]
Thanks for the CSV-- can I just hand it back to you with Agent_id and a column of yes/no to convert current remarks to biography? Majority of these 4500+ remarks are safe to move to biography type-- there's some clean-up stuff but can be tackled with some review after this move.

**Comment by dustymc** [comment]
>Agent_id and a column of yes/no

Yup, or remove the nos, or whatever lets me know what to move.

**Comment by mkoo** [comment]
> Yup, or remove the nos, or whatever lets me know what to move.

of course! I removed the ones that should remain in remarks (basically a lot of "maybe this guy" "probably this one" "we're guessing here!") I was pretty generous with what is a 'biography' though. Lots of future enhancement projects for students.

Also I left in the organization remarks to be moved to the new type so we have it in the same public place. (is it too late to rename biography to profile since we also have orgs with descriptions?)

CSV to load (all these agent remarks to be convert to new remark type)
[agent_remarks_2bio.csv](https://github.com/ArctosDB/arctos/files/14317965/agent_remarks_2bio.csv)

**Comment by dustymc** [comment]
>rename biography to profile

No problem for me, but that is hard-coded so getting it settled before release would be very good. I'll assume my fellow box-checkers are on-board with the change unless I hear otherwise....

**Comment by mkoo** [comment]
> rename biography to profile

yea for the sake of making it neutral and not specific to people... we should before it's too late! THX!
