### ISSUE TITLE
Code Table Request - Add term "Amazigh" to the "culture of origin" list

### ISSUE THREAD

**Issue by droberts49** [ArctosDB/arctos#7420]
### Goal
Under the object attributes, "culture of origin", please change "Berber" to "Amazigh". 

### Context
This came about from an individual bringing to my attention that the term "Berber" is offensive to people in that cultural group and many refer to themselves as "Amazigh" (singular) or "Imazighen" (plural) instead. The term "Berber" is not a term the people gave themselves, but one applied by Romans. Here is some information from the Society for Linguistic Anthropology, https://www.linguisticanthropology.org/blog/2019/09/23/respecting-identity-amazigh-versus-berber/; and from the New World Encyclopedia, https://www.newworldencyclopedia.org/entry/Berber. 

### Table
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctculture

### Proposed Value
Amazigh

### Proposed Definition
Indigenous peoples and languages of North Africa; Amazigh (singular), Imazighen (plural); see also https://www.linguisticanthropology.org/blog/2019/09/23/respecting-identity-amazigh-versus-berber/; formerly Berber.

### Helpful Actions

- [x] Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

- [x] Please reach out to anyone who might be affected by this change. Possibly have DEI committee discuss and help formulate action plan. Does the old offensive term require bulk changes?

@ArctosDB/arctos-code-table-administrators 

## Approval
_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Implementation
_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

- [x] Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

- [x] Add or revise the code table term/definition as described above. Ensure the URL of this Issue is included in the definition. URLs should be included *_as text_*, separated by spaced pipes. Do not include HTML in definitions.

_Close this Issue._

**Comment by mkoo** [comment]
HI @droberts49 thanks for the issue-- I'm going to reformat your request slightly so it's a Code Table Request and we can get to this more quickly. So should there be follow up like removing the old term and maybe converting all the records to the new term of ```Amazigh```

Let me know if this needs to be added to the request

**Comment by Jegelewicz** [comment]
@AJLinn @ewommack any thoughts or ideas?

**Comment by AJLinn** [comment]
You can see how we handled some of the older terms in the CTculture. 
See for example:

Alutiiq/Sugpiaq: "Indigenous people of Kodiak Island, coastal Prince William Sound, Northern Alaska Peninsula; see also http://en.wikipedia.org/wiki/Alutiiq ; **formerly Pacific Eskimo"**
or
Unangax̂: "Unangan or Unangas (Eastern and Western dialect respectively); Indigenous peoples of the Aleutian Islands of Alaska; see also http://en.wikipedia.org/wiki/Aleut ; **formerly Aleut"**

You could do something like this?
Amazigh/Imazighen: pull a sentence or two from your references to define; Indigenous peoples and languages of North Africa; see also https://www.linguisticanthropology.org/blog/2019/09/23/respecting-identity-amazigh-versus-berber/; formerly Berber.

**Comment by droberts49** [comment]
@AJLinn  I like that approach a lot -- it would help identify the "why" with the replacement.

**Comment by mkoo** [comment]
Is someone working on a definition? There is no proposed definition to move this issue forward. If no one is, can I propose we add this to the Diversity Committee to work on a proposal?

**Comment by droberts49** [comment]
@mkoo I've updated the definition and we discussed this in the Diversity and Inclusion Committee. Please let me know if there's anything else I need to do.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Looks good, I've added a check.

**Comment by dustymc** [comment]
The current value wasn't used so I deleted it, the new can now simply be inserted. 

FYI I'm working on https://github.com/ArctosDB/arctos-dev/issues/32 now, the CT will be able to carry more data in a week or two, it might be worth delaying re-adding unless there's some immediate need.

**Comment by Jegelewicz** [comment]
added
