### ISSUE TITLE
search using attribute remark fails

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#7421]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

Search for UAM:Ento accession = osf with records that have attribute 'maximum total length'

find 3,438 records (which seems like an undercount, but that's not the issue)
https://arctos.database.museum/search.cfm?guid_prefix=UAM%3AEnto&attribute_type_1=maximum%20total%20length&accn_number=osf

look at one of these records, eg:

https://arctos.database.museum/guid/UAM:Ento:238974

and see attribute remarks for maximum total length attribute = "less than"

return to search form and repeat search but add the term 'less' to the attribute remark for 'maximum total length'

https://arctos.database.museum/search.cfm?guid_prefix=UAM%3AEnto&attribute_type_1=maximum%20total%20length&attribute_remark_1=less&accn_number=osf

and find zero records.

**Expected behavior**

searching on attribute remark will find records that have matching strings in that attribute remark field

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.
high, working on manuscript with upcoming resubmission due date that is soon!

**Comment by DerekSikes** [comment]
Perhaps the fastest way to solve my immediate needs would be to get a FLAT download csv of all UAM:Ento with 'osf' in accession and all their attributes. Then I can search the data offline. I need to be able search on attribute data asap.

**Comment by dustymc** [comment]
https://arctos.database.museum/search.cfm?guid_prefix=UAM%3AEnto&attribute_type_1=maximum%20total%20length&accn_number=osf (your search without the remark) finds 3500 records. You should be able to download from there and then filter, or let me know exactly what you want and I'll do it. (I suspect my "everything" and yours are wildly different.)

Unrelated, I think you're hiding data by using an inappropriate attribute:
<img width="632" alt="Screenshot 2024-02-16 at 07 51 30" src="https://github.com/ArctosDB/arctos/assets/5720791/ad7e5081-206a-4cb7-b678-a404ebccf3d9">

[In fish length of the largest individual in a lot measured from the tip of the snout to tip of the longest lobe of caudal fin. Measurement done with caudal fin lobes compressed and measured at midline. Do not use for individuals.](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#maximum_total_length)

**Comment by DerekSikes** [comment]
Thanks Teresa! The attribute download tool allowed me to isolate the GUIDs of the records I need to filter out. I've moved those records to a new accession so I can work with the remaining records. Will FLAT update to the accession change I just made immediately or do I need to wait & if the latter, how long?

Also, will my original request of being able to enter a search string the attribute remarks field on the search page and find matching records be fulfilled?

**Comment by dustymc** [comment]
>how long

https://arctos.database.museum/info/flat_status.cfm

>request

Yes, I set a milestone. Next release is scheduled for the 26th, I suspect (maybe just hope!) this will be a minor bug and can be in that.

**Comment by dustymc** [comment]
>something useful. 

https://github.com/ArctosDB/arctos/issues/6705

I unfortunately do not have any timetraveling omniscience (yet...).  I've been watching that for a while, it's been at 200, then 2000, then 3000, then 400, then 1500 - people change stuff, I can't know what they're gonna change. 

>You seem to think they are useful

They are, they're just not absolute. If there are hundreds of records, yours will probably get through in the next minute or so, or you might want to check an individual record. If there are millions, you're probably not going to see anything for a day or two. It's KINDA first-in-first-out, so if it's bouncing around in the thousands and your changes are a few minutes old they've probably made it through. Etc. Useful!

>provide us guidance on how to interpret them.

PLEASE, anyone, tell me how I can say any of the above or anything in the linked issue and the issues linked from it in some useful way and place and I'll do that.
