### ISSUE TITLE
What does the "Pulled" field do in the Customize form (Data Entry)

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#7425]
Both @Jegelewicz and I can't figure out what the "pulled" field does in the Customize form for Data Entry. If I click the "pull values from form" button I see that it populates pulled fields with my already recorded Default values. But then what happens? I clicked the "use" button but I'm not certain it does anything.

![image](https://github.com/ArctosDB/arctos/assets/11336485/f337036a-30c4-4698-9520-3e547187c256)

**Comment by dustymc** [comment]
If you have some stuff in the form....

<img width="767" alt="Screenshot 2024-02-16 at 14 50 11" src="https://github.com/ArctosDB/arctos/assets/5720791/7d1268f1-e1bb-476b-882a-7e648358813a">

customize will open like...

<img width="488" alt="Screenshot 2024-02-16 at 14 52 40" src="https://github.com/ArctosDB/arctos/assets/5720791/d859b590-294f-4e82-9fb6-02a333869a01">

you can use....

<img width="271" alt="Screenshot 2024-02-16 at 14 49 06" src="https://github.com/ArctosDB/arctos/assets/5720791/8b5b4297-cdbe-410d-aa6f-0f8c9bacfde3">

to populate....

<img width="533" alt="Screenshot 2024-02-16 at 14 51 18" src="https://github.com/ArctosDB/arctos/assets/5720791/04fcc6ac-2409-4f3f-adb9-cbdacae97867">

and then choose defaults row by row


<img width="485" alt="Screenshot 2024-02-16 at 14 51 30" src="https://github.com/ArctosDB/arctos/assets/5720791/5c272507-c8c8-4beb-8746-40731b354449">

or...
<img width="269" alt="Screenshot 2024-02-16 at 14 53 30" src="https://github.com/ArctosDB/arctos/assets/5720791/731b5396-5b69-4061-9aca-ed98191a6c5a">

to pull everything from the form directly into the defaults

<img width="481" alt="Screenshot 2024-02-16 at 14 53 36" src="https://github.com/ArctosDB/arctos/assets/5720791/20d734f3-3b11-49a7-972d-81946f5d4c8f">

**Comment by ebraker** [comment]
OH! Gotcha. That makes sense. Thank you!!!

**Comment by ebraker** [comment]
Definitely
