### ISSUE TITLE
Reproductive info field

### ISSUE THREAD

**Issue by jldunnum** [ArctosDB/arctos#7426]
Reproductive data has disappeared from the customize search and results. Can we have that back please.

**Comment by mkoo** [comment]
Not sure what you're referring to? It's still there as an attribute search.
![Firefox_Screenshot_2024-02-16T21-06-41 168Z](https://github.com/ArctosDB/arctos/assets/2523089/f5ff6d3a-0c3f-4c2b-822e-9ed24ebeb89d)

To add that, in Customize and Search, be sure the Catalog Record Attributes is checked ( in the records category). Maybe yours got unchecked. Once you have a search interface you like, I recommend saving it as a search profile (you can have several)

**Comment by cjconroy** [comment]
I think he means missing on the preferences for search fields and results display fields. I also see zero occurence of repro
<img width="507" alt="Screenshot 2024-02-16 at 1 11 45 PM" src="https://github.com/ArctosDB/arctos/assets/5749672/1e0f721e-adc4-49ff-a52a-c27fb7a384dd">

**Comment by jldunnum** [comment]
Yup, what Chris said

______________________________________________________________
Jonathan L. Dunnum Ph.D. (he, him, his)
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
Research Assistant Professor (LAT)
Department of Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

Chair, Systematic Collections Committee, American Society of Mammalogists
Latin American Fellowship Committee, ASM

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by mkoo** [comment]
we've been asking what minimum fields should be exposed/available in flat results (see last few ranges meetings!) but it still there and available. Be sure to check on Attribute Details in the the Search results options.

For those who dont want to deal with the JSON results, then use the service built by request: Tool-->Download Attributes.

**Comment by jldunnum** [comment]
I thought we decided (in Ranges meeting) that the reproductive data field would remain even when we created the various individual reproductive attributes because there is still loads of legacy data sitting in the Reproductive info field.

**Comment by mkoo** [comment]
once all the repro trait requests have been settled then we can talk about which to include. But right now we have a lot of proposed attributes to split out the reproductive data. So quite in the middle of a transition.

**Comment by mkoo** [comment]
> I thought we decided (in Ranges meeting) that the reproductive data field would remain even when we created the various individual reproductive attributes because there is still loads of legacy data sitting in the Reproductive info field.

oh, so if we have ```Reproductive data``` in flat request then that will be a settled issue? (that was not my impression). If we can take @jldunnum as a formal request then ok!

**Comment by cjconroy** [comment]
I think we will always want to keep the original, verbatim repro remarks since it is likely many will not translate over to the new fields. And it will take many years to replace what is on arctos now and split out what can be put in other fields. That's an argument to keep the original reproducitve remarks on the options list for search and display.

**Comment by mkoo** [comment]
> I think we will always want to keep the original, verbatim repro remarks since it is likely many will not translate over to the new fields. And it will take many years to replace what is on arctos now and split out what can be put in other fields. That's an argument to keep the original reproducitve remarks on the options list for search and display.

That's also an argument not to highly compartmentalize the data-- you guys have made a lot of requests to do just that (https://github.com/ArctosDB/arctos/issues/6599) and we've been working on it-- so hopefully you can appreciate some of my hesitation to promote this suggestion. 

Probably best if we have a realtime discussion about this specific issue -- @jldunnum @cjconroy I leave it to you to organize!

**Comment by cjconroy** [comment]
I think my suggestion is akin to keeping verbatim locality. That field is meant to have all the original data even with misspellings (warts and all as Carla says). But then those data are decomposed into specific locality, higher geography, elevation, latitude, longitude, remarks, etc. That's what I mean by keeping a verbatim reproductive remarks, as well as some derivative fields.

**Comment by mkoo** [comment]
Again before we move to make Repro. data field as part of the flat, we need to resolve/ decide on the other requests which are listed here #7364   The situation I'm trying to avoid is one where we expend a lot of time on new attributes but they are not used (very much) since reproductive info field is basically all that is needed. Or worse, now you have data in more than one field, queries are long and complicated, now we have requests for a lot more flat fields and no one is happy. 

Ideally, we close all the issues in #7364 (or at least a good chunk of them) and we add repro data to flat. Then go have a beverage of your choice! Offer for a realtime discussion is still on table so let me know....

**Comment by jldunnum** [comment]
Morning Michelle, 
I do understand the reservations as you have described but I believe there is a real need for both. The separated attribute model really does facilitate working with individual attributes, which we need to do in many ways. Retaining the Reproductive Data field not only retains the verbatim info (some of which likely won't fit in one of our new fields) but also maintains a place for all these data while collections parse traits out. That could be some time down the road for many collections because its labor intensive and resources are always tight for this tupe of work. RANGES institutions have support at the moment, but this is actually only for records from western North America. Point being it woud provide flexability, a relaxed time frame for transitions also all the eventual benefits of getting attributes separated.

**Comment by mkoo** [comment]
@jldunnum sorry for the delay in replying-- ok, good points. how about this? I turn this into a request for the reprod info field in flat (after checking with Dusty on capacity) but we have a chat SOON about what to do with https://github.com/ArctosDB/arctos/issues/7364? We made some good progress the last time we met so maybe we can talk about what will actually be feasible for use in the RANGES active time period. let me know what you want to do

**Comment by jldunnum** [comment]
Hi Michelle,
I think at this point we definitely would like to have our cake and eat it too! In other words, the parsed out reproductive fields we had agreed upon as well as a repro info field. This will really facilitate the RANGES institutions ability to crank through trait data mobilization.

______________________________________________________________
Jonathan L. Dunnum Ph.D. (he, him, his)
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
Research Assistant Professor (LAT)
Department of Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

Chair, Systematic Collections Committee, American Society of Mammalogists
Latin American Fellowship Committee, ASM

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by mkoo** [comment]
Not sure if you tried to email me @jldunnum but not sure if you still want to meet or not.
Meanwhile we made progress on gonad attributes after an Issues meeting, which means this will be a useful trait used beyond mammals. Please see #7501 #7502, #7503 (in each the method field can be used to indicate left, right, or unknown)

We still have work to do with #7364 

Let me know about my suggestion repeated below
>I turn this into a request for the reprod data field in flat (after checking with Dusty on capacity) but we have a chat SOON about what to do with https://github.com/ArctosDB/arctos/issues/7364?

**Comment by cjconroy** [comment]
Not sure if this is the right place to ask, but will terms testis or testes or ovary be discontinued anywhere in attributes, but will be used in method? Or is it assumed that if there is a sex = male, then gonad = testis? and sex = female, gonad = ovary?

**Comment by jldunnum** [comment]
@mkoo yes happy to meet if needed but frankly cannot keep up with where things are. Keeping reproductive info in flat as well as in separate fields is our desired model. In terms of using testes/ovaries vs gonads, my recollection was that in the RANGES specific meeting we had agreed to retain testes/ovaries for mammal collections and modify with L or R in methods. I guess that was then overturned in later AWG meetings? I'll simply say that Arctos continues to move towards generalization in order to accomodate a broader and broader audience and the known specifics of our data get buried deeper and deeper in sublayers that are more difficult to access. I get it that changes will be made based on who attends AWG meetings and weighs in but the bottom line is that for many of us we simply do not have the time/ability to attend most Arctos meetings due to other obligations.

**Comment by mkoo** [comment]
discussed and in dev
