### ISSUE TITLE
Declutter Data Entry Form

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#7427]
Currently the Data Entry form is extremely difficult to visually parse due to the green background. Often it is hard to know which table/block you are working in:

![image](https://github.com/ArctosDB/arctos/assets/11336485/a6f6a3b1-bc79-41f6-93ca-a0ce15598448)

I suggest braking this up by ditching the green background and restricting color to each table/block green (leaving white space between each section) so that they are visually distinct, e.g.:

![image](https://github.com/ArctosDB/arctos/assets/11336485/792aa227-538c-4a72-938a-1ff9e81e04bc)

OR, better yet, ditching the full background and alternating dark and light table/blocks, e.g.: 

![image](https://github.com/ArctosDB/arctos/assets/11336485/5586310f-e428-4ee4-acb9-34d92ff12d51)

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/4874

(Feel free to un-merge if that doesn't seem correct, I think addressing all of this as one will be more productive.)

**Comment by ebraker** [comment]
@dustymc, not sure? Seems like a relatively straightforward formatting thing? Doesn't have to be green either, greyscale works.

@Jegelewicz ?
