### ISSUE TITLE
Need Help with Arctos Error - record event loader, collecting method

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#7428]
# Error Text
<html>
<body>

ERROR_ID | ECB17765-1637-4FAA-AB30BB558722A98C
-- | --
ERROR_TYPE | application
ERROR_MESSAGE | Error invoking external process
ERROR_DETAIL | lucee.commons.cli.CommandException: psql:/usr/local/webroot/temp/excopy_nicoleridgwell_20240216050226406_208.sql:42: ERROR: value too long for type character varying(255) CONTEXT: COPY cf_temp_specevent, line 9, column collecting_method: "Specimen found in a piece of float limestone (lense material) just below level of JJ1-75. This piece..."

</body>
</html>

# Where it happened
Record event loader - https://arctos.database.museum/loaders/BulkloadSpecimenEvent.cfm?action=ld

# Steps to get there
I've already loaded the 'linked to an encumbered locality' version of this event without issue through the record bulkloader, but loading the public version of this event through the record event loader throws an error saying the collecting method exceeds a character limit. The encumbered version has the exact same collecting method (see https://arctos.database.museum/guid/NMMNH:Paleo:85007).

# Problem
**Community response to describe the problem that caused the error**

# Solution
**Community response with directions for how to correct the problem**

**Comment by dustymc** [comment]
Patched

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks!
