### ISSUE TITLE
Feature Request - picks need a class

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#7431]
**Is your feature request related to a problem? Please describe.**

 From https://github.com/ArctosDB/arctos/issues/7352 make picks identifiable

**Describe what you're trying to accomplish** 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Priority**

**Comment by Jegelewicz** [comment]
From the notes today

When tab is required to validate entry add “tab to pick” in front of help text and change the color of the data entry box to light yellow.
