### ISSUE TITLE
Feature Request - agent pick behavior

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#7434]
**Is your feature request related to a problem? Please describe.**

From @DellaCHall  in https://github.com/ArctosDB/arctos/issues/7352

1) Agent auto-populate issue: I used to be able to type a name exactly and it would just populate into any agent/determiner field, if there were no duplicates. Now it seems to search every field, including relationships, so all people/organizations associated with an agent also show up, then I have to click the correct one. This added extra step seems silly when typing a full name exactly, and might actually deter people from adding relationships, due to the annoyance (for example, I'll probably remove my relationship with my husband, so I can enter data faster). Is there a way to have it auto-populate the agent if there are no duplicates in the name fields, like it used to? I'm not sure what is gained by this particular change, so maybe I just need a different perspective to understand it.

**Describe what you're trying to accomplish** 

Figure out how the agent selector should work

**Describe the solution you'd like**

A usable selector which doesn't make giant messes.

**Describe alternatives you've considered**

From @ewommack

>Try entering your user name instead of your full name. That works for me to only pull up me. With the relaxation of allowing people to have the same name now we're going to hit into having two or even more of the same person coming up in an exact name search as this as we get more and more people with the same or very similar names brought into the system. I think it is probably safer to have us search for people unless you know exactly who you want.

**Additional context**

One scenario worth avoiding in a system without unique keys on preferred name is that one collection 'curates' an agent, then another collection dumps lots of inappropriate data (eg stuff collected by a different agent with a similar or identical name) to that record. Ideally *all* agent selections would involve examining metadata, which the current behavior is designed to encourage.

**Priority**

?

**Comment by Jegelewicz** [comment]
> Ideally all agent selections would involve examining metadata, which the current behavior is designed to encourage.

Not really though. If I get a HUGE list of names simply because they all contain a relationship to the name I entered, I can't really see through it to things that might matter (like the agent with an almost-matching name). When I am looking to select an agent in data entry, I don't want to have to scroll through the 50 agents who have the same name in a RELATIONSHIP - the relationships don't matter here as I am trying to find a person who uses this name as a NAME.

**Comment by dustymc** [comment]
>HUGE list of names

Absolutely, there's a cost to false positives, the question is where it starts to outweigh the cost of false negatives (which leads - maybe "also leads" - to creating duplicates).

>agent with an almost-matching name

Names carry very little data; I'm sure we are collectively about to create a million duplicates, but hopefully not by the people who **_want_** to give proper attribution; they need to look at more than names.....

>uses this name as a NAME

... in part because people put random things in random places if they can; assuming names will be properly labeled is a recipe for failure. (Go check out the test error logs from about 1PM today....)

ANYWAY - I messed with some stuff, it should be NOT searching on relationships or 'other' now (because there are a million identical 'did this thing' remarks), and I think I've got the code set up so that it's relatively easy to adjust that if we've gone too far.

Feedback would be greatly appreciated.

**Comment by dustymc** [comment]
I'm reopening for https://github.com/ArctosDB/arctos/issues/7456 - it would be very useful for me to have a coherent picture of how this should work, rather than many smaller issues.

The current situation is that there are a bunch of addresses of the format...

<img width="170" alt="Screenshot 2024-02-28 at 08 41 33" src="https://github.com/ArctosDB/arctos/assets/5720791/48461809-ce50-4f1c-b148-1b0b0a05e02e">


I don't think I can realistically ignore specific words, or that that would do anything useful if I could.

I could somehow complicate the picker (eg a name-only search option or similar), which I expect would lead to more duplicates being created. (But the system is designed to support duplicates, that's not a technical problem or constraint I feel I must live under.)

I could ignore more data under the one search field, which I'd also expect to lead to more duplicates (and the parenthetical bits above still apply).

Maybe @ArctosDB/agents-committee is willing to suggest something about these specific data.

Just in case it's somehow not clear: Someone can also create 56,000 more agents with preferred name 'unknown' (perhaps even defensibly - clearly the one current 'unknown' represents lots of people and agencies).

My solution would involve simply not using agent 'unknown' for anything, which might involve filing an Issue if there are any remaining 'requirements.'

**Comment by Jegelewicz** [comment]
> My solution would involve simply not using agent 'unknown' for anything

This is probably the correct answer, but might be hard for people to accept? See https://www.datafix.com.au/BASHing/2018-10-18.html on when you have Nothing Interesting to Say.

> If you have nothing to enter in a field for a particular record, there's nothing wrong with leaving the data item blank. Please?

**Comment by DerekSikes** [comment]
Hope this doesn't throw a wrench in but this reminds me about agent fields that should be required.

In particular, I've noticed that because the two forms to add identifications remain configured differently (fields in different places on the two forms), despite my plea for consistency because humans are humans...

the single-edit ID form has the agent ID field off to the right so as one works through the vertical column of fields to complete the form it can easily be ignored / missed.

I found an ID record made by one of my students in which there was no agent ID... A long time ago I believe the agent was required, as it should be for an identification. Now it's not required and because of inconsistent form design it's increased the odds that humans will forget to add an agent.

I would like to reiterate my plea for the two forms to be consistent (preferably with all fields in a vertical column as the batch-edit ID form is)

AND ask that at least one agent be required for an ID to be saved without error.

This will eliminate the creation of IDs with no agents made accidentally. If the agent required request can't be implemented then at least re-jigger the form so that field is where it will be less likely to be accidentally ignored.

**Comment by Jegelewicz** [comment]
> at least one agent be required for an ID to be saved without error.

I don't think forcing people to select "unknown" is the right way to solve this problem.

**Comment by DerekSikes** [comment]
I think we need some way to distinguish between:

1) the agent is unknown, I'd like to add one, if I knew who to add, but I don't
and
2) I forgot to add the agent (who is known, and is often, me).

**Comment by DerekSikes** [comment]
Another way to look at this is what are the problems that result from making ID agents required?

1) lots of IDs with 'unknown' as the agent string
vs
2) lots of IDs with the actual, known agent, not entered because of human error

I argue #2 is the worse of the two bad options. Convince me otherwise please.

**Comment by Jegelewicz** [comment]
@DerekSikes this is a different issue and is mucking up the focused discussion here about what the results should be when an agent pick is initiated. I am going to mark these comments as off-topic. Feel free to file a separate issue(s) for these things!

**Comment by sharpphyl** [comment]
Any chance this issue is related to an error message we're getting today for uploads from the bulkloader.  We've never seen this before.
![agent name type does not exist](https://github.com/ArctosDB/arctos/assets/15368365/02e56d78-41d9-482d-a85e-d13d4e296fec)

**Comment by dustymc** [comment]
Nope, but same source - was that from this AM, if so how do I recreate? (I suspect I fixed this yesterday afternoon, but could have missed something.)

**Comment by sharpphyl** [comment]
Yes, just this morning.  Now we can't even save a record without getting that error message.

**Comment by dustymc** [comment]
Can you point me to one of them, ideally something I can try to load?

**Comment by genevieve-anderegg** [comment]
Anything in the bulkloader for DMNS:Inv right now. Maybe try https://arctos.database.museum/Bulkloader/editBulkloader.cfm?key=key_4261210

**Comment by sharpphyl** [comment]
Here's an image of the attempt to save a new record. We selected "unknown" from the list and the field is green so that's not the obvious problem.
![agent fail](https://github.com/ArctosDB/arctos/assets/15368365/9a106f85-cdd8-4adc-9b2d-6906ef503748)

**Comment by dustymc** [comment]
Thanks, should be fixed.

**Comment by sharpphyl** [comment]
It's fixed.  Thanks!

**Comment by dustymc** [comment]
I've changed the sort of this (and all other agent searches) for next release:

```
case 
when status_sort.attribute_value = 'verified' then 1
when status_sort.attribute_value = 'accepted' then 2
when status_sort.attribute_value = 'unverified' then 10
else 3
end as sort_by
```

That is, the two flavors of 'good verified', then stuff with no verification, then 'bad verified' last.

It's easy enough to change if that's not useful, but I think it should be: This system was born with a way to separate out 'better' (curated, whatever) agents, this just takes that a small step further.

I also messed with the icons a bit, a couple of them were running together in my head.

verified, accepted, and NULL

<img width="233" alt="Screenshot 2024-03-06 at 06 22 31" src="https://github.com/ArctosDB/arctos/assets/5720791/fa2ecb90-b1a3-4062-9675-0eac6e369621">

unverified
<img width="302" alt="Screenshot 2024-03-06 at 06 22 39" src="https://github.com/ArctosDB/arctos/assets/5720791/663c33a4-6118-41f0-94b9-68c79e073fc3">

**Comment by genevieve-anderegg** [comment]
Reiterating from #7456 that having to scroll pretty far down in the pop up window to select "unknown" is not ideal. This is the agent we use the most, entering it in multiple times per record usually. Would there be a way to work around this given the new form? Maybe if someone enters in "unknown" exactly and then tabs it automatically picks, whereas entering "unknow" (or anything besides the full word "unknown") then tabs it picks up the full list so you can scroll to select?

**Comment by dustymc** [comment]
>scroll pretty far down in the pop up window to select "unknown" 

So verify it?

**Comment by genevieve-anderegg** [comment]
Correct

**Comment by Jegelewicz** [comment]
Verified.

**Comment by genevieve-anderegg** [comment]
Thank you!!

**Comment by campmlc** [comment]
So what does it mean that #7458 is closed? The problem is not resolved. And this is breaking functionality for users. I cannot scroll through hundreds of agents with relationships to me just to find my name to enter in a shipment.

**Comment by campmlc** [comment]
What I see is a list of names related to the name requested for the agent, all in alphabetical order, including students from 10 years ago at the top.

**Comment by AJLinn** [comment]
> > My solution would involve simply not using agent 'unknown' for anything
> 
> This is probably the correct answer, but might be hard for people to accept? See https://www.datafix.com.au/BASHing/2018-10-18.html on when you have Nothing Interesting to Say.
> 
> If you have nothing to enter in a field for a particular record, there's nothing wrong with leaving the data item blank. Please?

When I see no agent listed for a record, I don't know if someone forgot to enter the information (e.g., one of my students missed this field when doing data entry) or if we just don't know. Using "unknown" as the agent means something... it means there is a creator or collector but we don't have the information. It reminds us to think about this important field and look for the answer.

In our exhibit labels we actually use the term "unrecorded" because that is a better representation of cultural data - _someone_ knows who created this piece but the collector didn't bother to write it down or has forgotten so there is no record of that person. It's more respectful and means we would welcome input to fix this missing piece of data.

What are people's thoughts of creating an agent "unrecorded" to replace the "unknown" for such cases?

**Comment by DerekSikes** [comment]
I agree 100% with Angie (as I commented earlier making the same point) & I 2nd the use of 'unrecorded' to replace 'unknown'!! Excellent idea because it is more truthful.

**Comment by AJLinn** [comment]
Sorry to duplicate Derek's comments, must have missed that in the comments removed that were marked off-topic. Was there a new issue created from those? Shall I create a new issue for "agent unrecorded" so the agent-pick-behavior issue isn't hijacked?

**Comment by dustymc** [comment]
>new issue

Yes please.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Frustrated trying to create an agent today. I'm trying to add that the agent was a student of the University of New Mexico, but ran into this: 
![image](https://github.com/ArctosDB/arctos/assets/47402809/b0de1219-d935-46b3-aef7-84f40034aeda)

I get a ton of results, agents with relationships to UNM, many different subunits of UNM, but it seems to have maxxed out because University of New Mexico isn't one of them.

**Comment by campmlc** [comment]
Yes,  pulling all related agents is hugely problematic and disfunctional across multiple tools. Hopefully when @dustymc gets back we can prioritize a solution.

**Comment by dustymc** [comment]
>relationships

The agent pick explicitly ignores relationships.

**Comment by Jegelewicz** [comment]
> The agent pick explicitly ignores relationships.

That may be true, but something is still picking them up. https://github.com/ArctosDB/arctos/issues/7434#issuecomment-2040681297 is an example of the issue.

**Comment by campmlc** [comment]
In create loan, the main loan form ignores relationships, but the create loan shipment pick does not.

**Comment by Jegelewicz** [comment]
I think the problem is that we have two places for relationships?

![image](https://github.com/ArctosDB/arctos/assets/5725767/972fd212-ca70-419f-a43e-f0e5ea2baca4)

and only one of them is being ignored?

**Comment by dustymc** [comment]
>only one of them is being ignored

No

**Comment by campmlc** [comment]
But I don't want to have to choose between 40+ separate related agents even without addresses. Plus, I need the address to create a loan shipment to the specific agent I enter. 
I'm happy to do a demo of this problem. I think it would be obvious if you could see what we are dealing with at the level of the interface.

**Comment by campmlc** [comment]
This is becoming a serious issue affecting work and Arctos functionality. Request that we have a zoom to resolve asap so we can demonstrate the problem. @mkoo @dustymc

**Comment by campmlc** [comment]
Please see #7438 which was closed but is not resolved and is absolutely related to this.

**Comment by dustymc** [comment]
>Can addresses be ignored

Yes - and that will just about inevitably lead to the creation of duplicates, but perhaps fewer than if lots of data are returned.... 

I ***can*** do just about anything, I'm asking if I ***should*** (or must)! 

> loan shipment

That is a different thing (but probably related, I suspect that will re-use some or all of whatever's developed here).

>don't want to have to choose

There was a very long discussion, it was agreed that limiting agents to high-information entities wasn't what The Community wanted, that lead to the current data model in which just about anyone can create just about anything - I believe that decision has been made, what's left is *how* to choose. There's also a bit of a positive feedback loop in that if we cast a wide net then a user might find 40 John Doe agents which they must pick through, and if we don't cast a wide enough net then a user won't find their John Doe, will create a duplicate, and the next user will have 41 to sort through. I suspect that ignoring more and more data (where this has been leading) is about the most disruptive thing that we can do, but I'm also not entirely sure what the alternatives are (more search options on all forms??), how any of that relates to usability (someone's immediately going to declare the more-options form too complicated to use??), or if I need to care about things like duplicates at all (see eg https://github.com/ArctosDB/arctos/issues/7649).


I don't need a demo, I know how things work, I need to know how things ***should*** work (in a scalable, actionable way).

There's an Agents Committee meeting tomorrow, I believe the agenda could be modified.

**Comment by campmlc** [comment]
Yes, please, let's address at Agent's Committee meeting tomorrow, so we can show how things should work in a functional way for operators, which currently is not the case.

**Comment by Jegelewicz** [comment]
Something is not working. I am adding a relationship to an agent and searched University of New Mexico, which is a gold star, verified agent, but does not even show up in the pick list!

![image](https://github.com/ArctosDB/arctos/assets/5725767/23491011-982f-478b-9ebc-f3dcf02dd1b5)
![image](https://github.com/ArctosDB/arctos/assets/5725767/9822780e-857e-4aa6-b067-229f77b96f78)

Maybe this is a cache thing, but I verified it yesterday. Easy to see how this would be the cause for creating duplicates...

**Comment by dustymc** [comment]
It often takes me slightly more than zero time to implement things. Sort outside the main form will be addressed by https://github.com/ArctosDB/arctos/issues/7438.
