### ISSUE TITLE
Feature Request - New Agents and Agent Attributes - Add Pronouns to new Agent Attributes

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#7440]
In discussion by the Diversity and Inclusion Committee, the issue of adding pronouns to Agent Attributes using the new system of attributes was gone over.

Suggestion was presented by Michelle Koo that we could add the information to the profile attribute and format it using html. Committee members agreed that this would be possible, but also added it would be nice to have a link to the html cheat sheet available.

When considering previous request for pronouns: https://github.com/ArctosDB/arctos/issues/2452
it was discussed that the original request related to the ability to search pronouns of agents within and across collections. Having the pronoun information in the Profile would not make it easily searchable. 
As a result, the committee decided to request pronouns be added as a Agent Attributes to the Identification section
**pronouns** - a third-person pronoun by which an individual wishes to be referred to in order to indicate their gender identity
free text, publicly viewable

Opened the issue here, but can open a Code Table issue if needed.

**Comment by Jegelewicz** [comment]
This should be formatted as a code table request. One already exists - https://github.com/ArctosDB/arctos/issues/7182

Either we should close both of these and start a new code table request, or the original or this issue should be modified and one of them closed.

**Comment by ewommack** [comment]
So the previous issue was closed, but the pronouns attribute hasn't been added. Should I create a new code table request?

**Comment by Jegelewicz** [comment]
> Should I create a new code table request?

I think so - the ol;d one was under the old agent model, so a new request would be better.

**Comment by AJLinn** [comment]
@ewommack Did you make a new issue? I have a reference to add regarding why we should **not** say "preferred gender pronoun" as our attribute.

**Comment by ewommack** [comment]
Created: https://github.com/ArctosDB/arctos/issues/7532

**Comment by ewommack** [comment]
@AJLinn - I finally created that code table issue so we can include that source to help us figure out the correct name and definition.
