### ISSUE TITLE
Enable User Management

### ISSUE THREAD

**Issue by kmkocot** [ArctosDB/arctos#7442]
I'm trying to add some new members to the ALMNH:Inv team:
elmclaughlin
wjfarris1
chandlerolson

I'm following the instructions here:
https://handbook.arctosdb.org/how_to/How-to-Create-your-Arctos-Team-Users-and-Operators.html

I got to step 4 fine but I don't see the "Enable User Management" link and am unable to add roles. I'm sure this is operator error but I don't know what I'm doing wrong. 

Thank you!
Kevin

**Comment by dustymc** [comment]
Done?
