### ISSUE TITLE
Transaction Summary By Collection/Year?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#7444]
I'm having trouble finding the loan and accession summary tools we used to have - am I missing a change to the language in the Tools menu? I've checked Stats and Transactions.
I'm looking for the summary of loans by year by institution, with count of loan items etc.

**Comment by Jegelewicz** [comment]
I don't see anything obvious in the Tools. Was this perhaps a report under the old ColdFusion reporter? Do you have an example of an old report?

**Comment by mkoo** [comment]
This looks like the download CSV from the transactionSearch page.
[image: Firefox_Screenshot_2024-02-22T23-00-18.975Z.png]
downloading that CSV is the same data as the one you posted. I use that to
do our annual reports. I hope that can work for you too!

**Comment by campmlc** [comment]
OK, I found it. You now have to do a Transactions search, select the date and collection parameters (for multiple collections, expand the collection dropdown and hold the control/cmd key to select more than one), do the search, and then select Get Loan CSV from up top in the table. 
It would also be really nice to have a tool to generate a similar report with the rest of the collection management stats under Status and Stats, or even better, a collection dashboard with downloadable links in the same way we have for projects, summarizing loans, samples, citations, etc by year.

**Comment by campmlc** [comment]
Thanks, @mkoo. The odd thing was that this used to be a report similar to usage statistics and citation statistics. I see it's been replaced, but I certainly got lost. Do you have a specific report template that you use for annual reports? My problem is that I have to generate reports of genomic resources use across multiple collections, which is challenging.

**Comment by campmlc** [comment]
Yep, thanks all!
