### ISSUE TITLE
Feature Request - add link from ALL Component Loader Tools to Component Loader Status page

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7445]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

I just noticed that the [Part Attribute Bulkload Tool](https://arctos.database.museum/tools/BulkloadSpecimenPartAttribute.cfm) does not have an appropriate title and is also missing a link to the Component Loader Status page.

**Describe what you're trying to accomplish** 
_A clear and concise overview of the goals; why are you asking for this?_

Consistency

**Describe the solution you'd like**
_How might we accomplish your goals?_

Maybe we should do a review of all of these tools and make sure that their pages have a consistent message?

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

Do nothing - maybe nobody but me notices!

**Additional context**
_Add any other context or screenshots about the feature request here._

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._

**Comment by dustymc** [comment]
I'm not sure how to respond to this, things get updated to the latest version when they get updated for whatever reason, and versions change often enough that I'm not sure anything else makes sense in light of available resources. Want to recast this to an update request of the one tool? If so, lemme know anything else about that tool that could be better.
