### ISSUE TITLE
Need Help with Arctos Error: Agent - "no unabbreviated title variant"

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#7449]
# Error Text
[ no unabbreviated title variant [Suluk Frankson] ]

# Where it happened
https://arctos.database.museum/agents.cfm?agent_id=21351018

# Steps to get there
I've created unabbreviated variants for what I think are all parts of the abbreviated name, as it appeared on the agent's Facebook page. I'm not sure what I need to unabbreviate in order to stop getting error notifications for this agent.
<img width="664" alt="Screenshot 2024-02-26 at 8 16 45 AM" src="https://github.com/ArctosDB/arctos/assets/17605945/8634b425-91aa-476b-b9a0-6122949c63c0">

# Problem
**Community response to describe the problem that caused the error**

# Solution
**Community response with directions for how to correct the problem**

**Comment by dustymc** [comment]
>not sure what I need to unabbreviate

That's a pattern not handled by the checker, you can't fix it.

I am not planning on preserving any part of that functionality in next release (tonight). The checker/duplicate-looker-for-er will survive (it's used by the pre-loader and results are visible in 'Data Quality Alerts' on edit) and can be made to suggest whatever might help prevent duplicates/provide better attribution, but I don't think there's any place for a "this name doesn't meet expectations" notifications like this one in the system we're moving towards. That should do a lot better job for those few folks with 'strange' names (can't be more than 7 billion or so of 'em...), but finding a way to NOT create messes and duplicates will also be more left up to the collections and users. (Which means that we can accommodate the 57 actual distinct "Some Agent" people without problems, but it also means that a collection can make 57 duplicate records for one person without complaint from the system; hopefully the @ArctosDB/agents-committee will get involved if the latter happens.)
