### ISSUE TITLE
Help needing adding non-biological identifications using A string?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#7452]
I am looking for help/advice/documentation from more experienced folks to figure out how to use the A {string} formula to generate identifications for bulkloading soil samples and biocrust samples (or "biotic crust"). I've previously used this to add a string to a scientific name in the data entry form ("build") or to edit an existing identification, but I've never done this when there is no existing name in any available classification to tie the string to.  I added other non-biological classification sources to my preferred taxonomy in manage collection, but I still don't see that option when I do a test data entry. What do I put for "XXXXXX  {soil sample}"?

When I look up cultural collections for insight, I find "Soil sample" with nothing as prefix.The documentation doesn't address this, meaning I must be missing something very simple?  Help?

**Comment by Jegelewicz** [comment]
Soil sample doesn't exist in taxonomy so I'm not sue what you found? I just added Soil to Arctos Rocks and I would suggest that you use Soil - no need for a string unless you want to say Soil {soil sample}.

**Comment by dustymc** [comment]
>documentation doesn't address this

https://docs.google.com/spreadsheets/d/1VbNC3k17WAHMum_qD5UYoXxUUWwXXh5gZSM5vfGvRzU/edit#gid=1249517607

**Comment by dustymc** [comment]
>what they have in the ID

<img width="506" alt="Screenshot 2024-02-27 at 07 26 25" src="https://github.com/ArctosDB/arctos/assets/5720791/eaf88011-a50a-43cf-ab44-27390fa96110">

>doesn't change my recommendation

Agree, https://arctos.database.museum/name/Soil carries more information than 'the old way.' (And why does everyone love 'sample' so much?? What should I expect with unsampled soil, an entire planet or ????????)

**Comment by campmlc** [comment]
Great! I'd much prefer to use "soil" or "water" without having to put some random thing in front of it. It was the "A" part that wasn't clear in the documentation - what are we to use for A if nothing relevant shows up in the various classifications? Unidentifiable? That's not true. Adding "soil" etc to an Arctos classification makes more sense.  

What about biocrust? Here is a defintition:
Biological soil crusts (biocrusts) are commonly found on the soil surface in arid and semi-arid ecosystems (collectively called drylands). Biocrusts can consist of mosses, cyanobacteria, lichens, algae, and microfungi, and they strongly interact with the soil.
https://www.usgs.gov/centers/southwest-biological-science-center/science/biological-soil-crust-biocrust-science#:~:text=Biological%20soil%20crusts%20(biocrusts)%20are,strongly%20interact%20with%20the%20soil.

**Comment by Jegelewicz** [comment]
> What about biocrust? Here is a defintition:
Biological soil crusts (biocrusts) are commonly found on the soil surface in arid and semi-arid ecosystems (collectively called drylands). Biocrusts can consist of mosses, cyanobacteria, lichens, algae, and microfungi, and they strongly interact with the soil.
https://www.usgs.gov/centers/southwest-biological-science-center/science/biological-soil-crust-biocrust-science#:~:text=Biological%20soil%20crusts%20(biocrusts)%20are,strongly%20interact%20with%20the%20soil.

HMMMM - This is a crazy one. I don't think that I would be opposed to adding Biocrust as a taxon name, but what type would it be (mineral or Linnean?) and what classification would go with it?

**Comment by dustymc** [comment]
>opposed to adding Biocrust as a taxon name

If there's something that's defensibly considered a taxonomy published somewhere, sure, file the issue.

>what classification would go with it

The one it's sourced from! (Taxonomy involves some formality, the source should at least suggest answers to these kinds of questions.)

That particular definition suggests to me that this is something else. ('Ecotype' maybe - I think this is closer to 'tundra' than '_Rangifer_'.)

**Comment by campmlc** [comment]
We need an Environmental Sample taxonomy . . .
 Bio crust defies out traditional understanding of taxonomy, and of individuals, for that matter.

**Comment by campmlc** [comment]
This is like a lichen, but more taxa involved, at the kingdom level.

**Comment by Jegelewicz** [comment]
Maybe the identification should be [Biota](https://arctos.database.museum/name/Biota#WoRMSviaArctos) {Biocrust}

**Comment by campmlc** [comment]
That works?

**Comment by campmlc** [comment]
So unfortunately Biota is a term for all life in WoRMS, but a genus of cypress tree in Arctos Plants. I'd selected Arctos Plants as one of the classifications for this collection of well, lots of plants but some other things. I can add WoRMS, but I'd have to add it priority higher in the selection. 
Since we can choose which classification source to use, is there any way we could specify a preferred classification for a individual taxon name? I could use aphiaID or an Arctos classification identifier that would  explicitly distinguish that I want to select the Biota in WoRMS from the one in Arctos Plants?

**Comment by AJLinn** [comment]
The Nomenclature 4.0 has "Material Sample" as a category, which seems to me to be the best option
https://page.nomenclature.info/parcourir-browse.app?id=14924&lang=en&ws=INT&wo=N
