### ISSUE TITLE
Feature Request - Alive date on Agent Picker tool

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#7453]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
How to pick the right agent when many have the same name?

**Describe the solution you'd like**
In the agent picker tool the 'alive' date attribute would help disambiguate agents

and/or the 'dates of activity' which might be a more reliable source of data since these are auto-generated while the 'alive' date is human-entered and might be left blank quite a lot.

**Describe alternatives you've considered**
randomly picking any agent who has the same name as the one I want

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._
high

**Comment by dustymc** [comment]
This is not a technical problem, I think the only significant "cost" is in the potentially-overwhelming amount of data.

I know how to do this, will go next task (and - eventually - interpret silence as enthusiastic support).

Not completely related: "alive" is a lot better than nothing, but I'd also expect thousands of 'John Doe' to be alive on any given date, and knowing that a 'John Doe' was alive a decade ago isn't much indication of whether the 'John Doe' on a label might be the same person or not. IDK what to do with that....

**Comment by dustymc** [comment]
Nevermind, there's already a place for this, the omission is from a change that didn't completely catch up, I'll fix.
