### ISSUE TITLE
Datum not showing correctly on specimen page

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#7455]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
It seems like the specimen page is showing the as entered datum instead of WGS 84.

**To Reproduce**
1. Go to a locality that has coordinates that were converted from something other than WGS 84.
2. Look at the datum, it should be and is "World Geodetic System 1984"
3. Go to a specimen from that locality and scroll down to the locality box.
4. Look at the datum. It is not "World Geodetic System 1984"

Here is the example I am looking at:
locality: https://arctos.database.museum/place.cfm?action=detail&locality_id=11102013
specimen: https://arctos.database.museum/guid/NMMNH:Paleo:58494

**Expected behavior**
The specimen page should show WGS 84.

**Screenshots**
Looking at this image, unless I already know that Arctos coordinates are in WGS 84, I would assume both sets of coordinates ("coordinates" and "as entered coordinates") are in NAD 27.

![image](https://github.com/ArctosDB/arctos/assets/47402809/cf4d9e11-84bb-4b1a-a024-613eb60204fd)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 122.0.6261.70

**Comment by dustymc** [comment]
Lacking better ideas, I stuffed datum in with the verbatim coordinates. 

<img width="411" alt="Screenshot 2024-02-27 at 14 11 17" src="https://github.com/ArctosDB/arctos/assets/5720791/d1cc0791-d70d-420b-9f16-1f13b7e4d11f">

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks, that is much better!
