### ISSUE TITLE
Agent "unknown" requires selection

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#7456]
When entering or updating records with the agent "unknown," it is necessary now to select "unknown" from a list of 6 agents.  We discovered that you can ignore the list, close the pop-up, and "unknown" will default into the field, but it will be red.  In the bulkloader, it is correctly "unknown."

Previously, "unknown" was the default without any pop-up appearing and the field would turn green.

Screenshots
 
![unknown agent search 1](https://github.com/ArctosDB/arctos/assets/15368365/6643e0e0-042c-4313-b003-f107dc12ecf0)

![unknown agent search 2](https://github.com/ArctosDB/arctos/assets/15368365/a7bcb0b3-2acd-4974-94f1-484ca0fa3d2b)

Desired outcome: make "unknown" the default without having to select it from the pop-up or close the pop-up. 

Priority: normal.  We have a work-around but it was much smoother in the past when it was the automatic default.  Also, we don't want to encourage data-entry volunteers to ignore a red field.

**Comment by dustymc** [comment]
I am merging this with https://github.com/ArctosDB/arctos/issues/7434 so that we can discuss the behavior of that form in one place.
