### ISSUE TITLE
Pull function in Data Entry not working

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#7457]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Since yesterday the Pull function to pull collecting events etc from related records in other collections appears to no longer be working.  Error ID DDF78E1A-F1DC-4666-8F663E578208693B

**To Reproduce**

1. Go to Create Records, select profile (MSB:Para
2. Enter an identifier value (see screenshot), click Pull
3. Click go

**Expected behavior**
This was working until yesteday. Currently not working either for my student or for me.

**Screenshots**
![Screenshot 2024-02-27 15 39 12](https://github.com/ArctosDB/arctos/assets/14808196/392308b2-09f2-4ba6-9715-73a49a9dc2b6)

![Screenshot 2024-02-27 15 37 07](https://github.com/ArctosDB/arctos/assets/14808196/d308987a-0a8d-4d87-a8df-b228e61e8c0e)

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by campmlc** [comment]
Just confirming that this is still pending. We are now getting the message "Not found" when we use Pull, rather than the previous error. This happens whether we search on an explicit catalog number or an identifier such as an AF.

**Comment by dustymc** [comment]
<img width="505" alt="Screenshot 2024-02-27 at 17 56 22" src="https://github.com/ArctosDB/arctos/assets/5720791/756848a9-2d65-4043-83a0-0f107913f02f">
<img width="931" alt="Screenshot 2024-02-27 at 17 51 12" src="https://github.com/ArctosDB/arctos/assets/5720791/3bee18d0-ae0d-44c7-ba33-a68f7a2582db">
<img width="841" alt="Screenshot 2024-02-27 at 17 51 03" src="https://github.com/ArctosDB/arctos/assets/5720791/1eb4296e-1bbb-4d8d-a6bf-8a233d650002">

**Comment by dustymc** [comment]
cannot replicate
