### ISSUE TITLE
Agent Pick Tool pulls every associated agent name

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#7458]
Problem: Trying to create a loan shipment. Enter Ship To and Ship From Agent, hit tab, get a very long and difficult to scroll through list of every possible agent associated with the agent name entered, seemingly in no particular order. Can we limit the Agent selection to just the agent we enter? Or make it option to see all related agents? I dont want to ship to some former student of a PI from ten years ago - I just want to select the current shipping address of the agent I requested. I also don't really need OrcIDs etc when I am creating a shipment - just a selection of valid shipping addresses and possibly emails?
Priority: high given the level of frustration this is causing, but it isn't actually preventing work, just causing angst and lost time.

**Comment by Jegelewicz** [comment]
Maybe this one got missed? We requested that the picks only look for values in names - relationships shouldn't be examined for picks.

**Comment by campmlc** [comment]
This recent agent change and resulting agent picker disfunction is still a huge problem. It affects any agent pick, for example choosing an issued by agent for an identifier. When I select my name as shipping agent to create a shipment in loans, or to add myself as an issued by agent, I get the names, addresses, orids, akas, not the same as etc of every agent related to me, including my deceased father. When I try to select MSB Division of Mammals, I get a list of every agent ever associated with MSB:Mamm and all of their akas etc etc. This is not workable. 
Request that agent picker tools be standardized so that relationships are excluded by default. Provide an option to include relatioships if necessary.
For the loan shipment in particular, just provide that agents valid shipping and contact info? The interface makes it really hard to visually filter through all the akas, dates, and old contact information.

**Comment by jldunnum** [comment]
I second these suggestions by Mariel.
Also I had raised an issue a couple months ago in regard to being able to set default agents within our collections so we don't need to pick them each time. For loans, I will always be the shipper out of MSB Mammals, I will always be the in-house contact, Joe Cook will always be the authorized by agent, etc., etc.  Huge time saver to not have to search for these each time.

______________________________________________________________
Jonathan L. Dunnum Ph.D. (he, him, his)
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
Research Assistant Professor (LAT)
Department of Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

Chair, Systematic Collections Committee, American Society of Mammalogists
Latin American Fellowship Committee, ASM

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by dustymc** [comment]
duplicate of https://github.com/ArctosDB/arctos/issues/7434

**Comment by campmlc** [comment]
Reopening as not resolved or addressed in #7434

**Comment by campmlc** [comment]
More explicit description of problem:
When I select a loan agent such as a recieved by agent in the loan form, I put in an agent name, hit tab, and if I have added the correct name that matches a single agent, the space autofills. If there is another agent that matches, I get to see both agents, and choose one, from a simple and easy to view interface. Note that the loan agent pick DOES NOT include all related agents. See screenshot. When I try to create a shipment for the same loan from the same loan page, I can do the same process and get the same behavior when I add my name as "Packed by Agent". BUT - to create the shipment, I also need to add "shipped to address" and "shipped from address". The way this tool is set up - it asks for an address, but it isn't possible to actually type an address in the field provided. Instead, we must enter an agent name. Here, the agent name search is entirely differnt - pulling all related agents and all their addresses. More screenshots below. Since the ability to enter an address doesn't actually exist here - we need to be legitimately able to pick an "agent" as we can in the rest of the tools and then select their shipping address. I really don't want to have to scroll through address from graduate students of a PI who have not been around for decades in order to be able to pick Joseph A. Cook's shipping address, or scroll through all of my family members and affiliations to pick my shipping address to create a loan.

**Comment by campmlc** [comment]
![Screenshot 2024-04-09 11 08 34](https://github.com/ArctosDB/arctos/assets/14808196/1dda3744-6b51-49fd-a73a-1ea3bf02e48f)
![Screenshot 2024-04-09 11 08 59](https://github.com/ArctosDB/arctos/assets/14808196/aa41764a-882f-4835-bcef-17aad9b5e446)

![Screenshot 2024-04-09 11 09 52](https://github.com/ArctosDB/arctos/assets/14808196/d4c83ce7-7b7f-4405-93d4-0ffafd134882)
![Screenshot 2024-04-09 11 10 23](https://github.com/ArctosDB/arctos/assets/14808196/e1f7e1b7-e860-40c8-bc9b-b8140d4eeb12)
![Screenshot 2024-04-09 11 11 06](https://github.com/ArctosDB/arctos/assets/14808196/36cc7a4b-b4e6-4b33-94fc-db0aaf564d04)
![Screenshot 2024-04-09 11 11 57](https://github.com/ArctosDB/arctos/assets/14808196/eb973d16-1fc7-4c87-8faf-a4d80d195807)

**Comment by campmlc** [comment]
No - I still get the same pick screen, starting with Amanda Jones?

**Comment by Jegelewicz** [comment]
OK, was worth a shot! Dusty will work on it.

**Comment by campmlc** [comment]
Thanks, appreciate both of you.

**Comment by campmlc** [comment]
This appears to be fixed now - shipment agent only pulls designated agent, not related agents. Thank you!!
