### ISSUE TITLE
new relationships 'assigned by' defaulting to 'legacy' - ignores user name of user making relationship

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#7459]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

Just made two new relationships for https://arctos.database.museum/guid/UAM:Ento:497858

when making them it appears that my user name is selected or autopopulated into the 'assigned by' field because there is this text: ffdss@2024-02-27 

see below
![Screenshot 2024-02-27 at 3 11 24 PM](https://github.com/ArctosDB/arctos/assets/9099827/415bd3cb-9cd4-4828-bf53-01dc84d24b4d)

but when I save these new relationships the 'assigned by' does not have my user name, it has 'legacy' instead.

This seems like a bug.

**Expected behavior**

my user name and today's date should be captured since I made the relationship

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.
high

**Comment by ewommack** [comment]
I just had this happen to me in our UWYMV:Herp collection too. I added a new relationship, and it said it was legacy that added it.

**Comment by dustymc** [comment]
patched
