### ISSUE TITLE
[CONTACT: Blocked Network]

### ISSUE THREAD

**Issue by francescagalimi** [ArctosDB/arctos#7461]
restricted IP: 185.169.0.7
Hello,
I am a student working at the Berkeley MVZ. Occasionally, Arctos blocks my IP address and I'm not able to use the database, so I was directed to open an Issue here on GitHub.

Thank you!

**Comment by dustymc** [comment]
That IP is "Net1 GmbH Public Proxy Server" - traffic from the MVZ (especially things like Arctos passwords!) should probably not be routed through there.

@mkoo

**Comment by mkoo** [comment]
Please check and make sure you are connected to eduroam not the public wifi
Let us know if you continue to have access issues.

**Comment by francescagalimi** [comment]
Hi,
Yes, I was connected to eduroam and still am, and it's again blocking me from the database. It's done this before, and then a couple days later it lets me back in out of the blue, even though I'm always connected to the same network. Is there anything else I could do?
