### ISSUE TITLE
manage agent link on tools page is dead

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#7462]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

This link https://arctos.database.museum/agents.cfm

is dead so should be made alive or removed from the tools

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.
medium

**Comment by dustymc** [comment]
thx/done, should clear the cache within an hour
