### ISSUE TITLE
Feature Request - Accept barcode in Bulk Edit Parts tool

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7465]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

I have to know a part id in order to use the Bulk Edit Parts tool - https://arctos.database.museum/loaders/bulk_edit_parts.cfm

**Describe what you're trying to accomplish** 
_A clear and concise overview of the goals; why are you asking for this?_

Make the tool easier to use

**Describe the solution you'd like**
_How might we accomplish your goals?_

use barcodes to edit parts in the tool

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

Use barcodes to find part ids, then use the tool - seems like unnecessary work.

**Additional context**
_Add any other context or screenshots about the feature request here._

https://github.com/ArctosDB/arctos/issues/7464

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._

**Comment by dustymc** [comment]
>Make the tool easier to use

This might also make the tool harder to use (more cryptic) when there's not a 1:1 ratio of barcodes and containers (or things aren't in the right place, etc.).

We could build some 'get partID from barcode' tool (might already exist?), which would make this completely transparent and keep the loader as simple as it can be, but (as mentioned) require a few more clicks.

We could assume that unexpected arrangements are rare (true, but there are still many) and just throw errors when such things are encountered. This would make the loader slightly more complex, but also provide what's likely to be a straighter access path for many situations.

I don't see any real problems with what's being requested, I just want to be transparent about the implications.

**Comment by Jegelewicz** [comment]
>  just throw errors when such things are encountered

That's what happens in all the other loaders, so seems appropriate. However, depending upon the outcome of #7466 adding GUID prefix might be necessary for this to work well?

**Comment by dustymc** [comment]
>GUID prefix might be necessary for this to work well?

I don't think so, a barcode is tied to one part within the user's "globe" or it ain't. If ``Inst:A`` and ``Inst:B`` have a ``barcode`` (linked to one part) then you can use it if you have access to one of those collections, and can't if you have access to neither or both. If those two collections want you doing things they'll need to coordinate their barcodes to ensure you have that ability. (None of that means we can't add guid_prefix, for the *part* and/or the *container*, but the current system for handling nonunique barcodes isn't going anywhere.)

And partID should always be available, I don't see any unescapable corners here.

**Comment by campmlc** [comment]
I like the idea of "get part ID from barcode". I like having partIDs generally, as it helps flag situations such as multiple items in the same barcode.  I'd prefer to fix all these, but some of them are legacy tissues where two parts were created for different tissues in the same vial.  I assume these would be very problematic if we only used barcode?

**Comment by dustymc** [comment]
Tabling as obsolete, I believe the current downloads satisfy the need.
