### ISSUE TITLE
Make Containers children of collections instead of Institutions

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7466]
>Can you clarify what you mean by switching from institution acronym to guid prefix?

The table is currently....

```
arctosprod@arctos>> \d container
                                    Table "core.container"
            Column             |            Type             | Collation | Nullable | Default 
-------------------------------+-----------------------------+-----------+----------+---------
 container_id                  | integer                     |           | not null | 
...
 institution_acronym           | character varying(20)       |           | not null | 
...
Indexes:
...
    "iu_container_barcode_inst" UNIQUE, btree (barcode, institution_acronym)
...
Foreign-key constraints:
    ...
    "fk_institution_acronym" FOREIGN KEY (institution_acronym) REFERENCES institution(institution_acronym)
...
Policies:
    POLICY "rls_container_policy"
      USING (((institution_acronym)::text IN ( SELECT unnest(get_my_institutions()) AS unnest)))
...
```

Those could all be changed to involve collection.collection_id (that is, collections - or some proxy to them - rather than institutions, which don't actually exist except as semi-uncontrolled text strings within collections).

Making such a change would require an Issue, and a commitment by someone to see it through.

_Originally posted by @dustymc in https://github.com/ArctosDB/arctos/issues/7127#issuecomment-1969279138_

**Comment by Jegelewicz** [comment]
>container permissions would be assigned at the guid prefix collection level vs institution level?

Yes - they'd follow the VPD model of everything else (eg catalog records) instead of needing their own institution-based approach.

>commitment would involve making sure collection managers understand

That's the start, but the real issue will be updating containers from being associated with institution to collections. I can't make that decision by myself, and I can't start this until every container is mapped to a collection.

_Originally posted by @dustymc in https://github.com/ArctosDB/arctos/issues/7127#issuecomment-1969309164_

**Comment by Jegelewicz** [comment]
I think this makes sense and would make object tracking in Arctos function more like catalog records.

What would be lost if we do this?
1. MSB:Mamm cannot use UAM:Mamm barcodes unless someone at MSB:Mamm has access to UAM:Mamm

What would be gained?
1. No more need for ensuring that barcodes are unique across all of Arctos
2. No more barcode mixups and expensive issues when two collections print 50,000 of the same barcode
3. Collections can control their own object tracking setup
4. Better ability to assign object tracking permissions in conjunction with permissions to manage records

What am I missing here - please fill in the blanks or edit if I have said something dumb.
6.

**Comment by campmlc** [comment]
From comment on #7127:
As for mapping container barcodes to collections, that might be problematic. A large majority of barcodes in use at MSB, e.g. those associated with cryovials, freezer boxes, and parasite vials, are in a shared series managed through DGR and distributed for use to the various collections as needed. This makes sense in that DGR is a repository for tissues etc from multiple divisions/collections. This is a related issue to MSB barcodes being used in the field and ending up at other institutions like KSB. If we had the ability to choose to share permissions across collections and institutions, then that might work. I'm not sure we can disentangle the cross-collection usage after a decade of intermixing, though?

**Comment by dustymc** [comment]
@campmlc that seems like a relatively simple organizational problem, but if it's a hard blocker for you (or anyone else) please say so. This Issue is blocking what seems to me to be an easily-accessible major improvement, quickly resolving this - whatever the outcome - would be very useful to a lot of people.

>ending up at other institutions

That's resolved, there were a bunch of issues (I can dig them up if I need to) which lead to the implementation of the above-mentioned institution-based VPD.

>choose to share permissions across collections and institutions, 

That would be a wildly complex thing that's not going to be resolved here, BUT the inclusion of institution would take the complexity from (tables x collections x 4) to (tables x collections x 4 x institutions) - currently (with 61 institutions and some guessing on table-count) that would VERY roughly be the difference between 662,000 checkboxes per user and 40,382,000 checkboxes per user. What's decided here probably has implications for any future finer partitioning of roles.

**Comment by campmlc** [comment]
I'm all for simplification and the proposal sounds good as far as I understand it, but maybe we could do a call to discuss? I don't feel I understand all the ramifications.

**Comment by Jegelewicz** [comment]
I don't think we need to rush - we could discuss at the next Object Tracking meeting which should happen within the next 3 weeks.

**Comment by dustymc** [comment]
>call

Sure, most any time, or ping me and I'll show up at office hours, or whatever (for anyone and any issue or topic).

>rush

If we're going to kill this (don't think that's what I'm hearing): Let's do it now.

If this was easy (don't think it is): Let's do it now.

If we're going to seriously consider this (I think where we are): perhaps we should consider how waiting affects https://github.com/ArctosDB/arctos/issues/7127 and whether we need to do anything about that. (Eg is someone not able to function, or would that clarity just be really nice?) This probably doesn't HAVE to block that, but of course it would be much simpler (to write, use, understand, adopt, everything) to go forward with a bit of the end in sight. Agree that this probably can't be rushed, but https://github.com/ArctosDB/arctos/issues/7127 shouldn't suffer any more than necessary for that either.

**Comment by campmlc** [comment]
I think a zoom next week would work for me -maybe after issues meeting?

**Comment by campmlc** [comment]
Zoom tomorrow Friday March 1pm PST?

**Comment by Jegelewicz** [comment]
I am not available.

**Comment by campmlc** [comment]
@dusty it would be helpful to me to meet to discuss this, so I can understand the ramifications for our collections. I'd like to be able to resolve with a definitive answer. Let me know when.

**Comment by dustymc** [comment]
My remarks (just a question!) that started this:

https://github.com/ArctosDB/arctos/issues/7127#issuecomment-1969221308

>One precursor issue might be the use of institution_acronym - someone (@campmlc ?) mentioned that this isn't great, that's understandable, I don't care and can change it (presumably to guid_prefix), but the RLS/VPD policy is written around it; changing it would change the below (probably most users don't have access to all collections which share an institution), and that would change the code I need to write. If we are going to change that, it would be very good to do it before this if there's any way to do that.

**Comment by Jegelewicz** [comment]
Agree to close.
