### ISSUE TITLE
Feature Request - All agents with a collectionID attribute should be verified

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7468]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

Agents representing collections in Arctos have a sad yield triangle.
![image](https://github.com/ArctosDB/arctos/assets/5725767/84ee7ec0-eb59-48f9-9611-92069286f4c3)

**Describe what you're trying to accomplish** 
_A clear and concise overview of the goals; why are you asking for this?_

Agents representing collections in Arctos should have a gold star!

**Describe the solution you'd like**
_How might we accomplish your goals?_

Add verfied status to all Agents that have a collectionID starting with [https://arctos.database.museum/collection/](https://arctos.database.museum/collection/PSM:Alg)

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

Adding them one-by one, which sounds like a drag

**Additional context**
_Add any other context or screenshots about the feature request here._

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._

This is potentially an activity for a bot?

**Comment by Jegelewicz** [comment]
> creating them that way going forward (not sure if you or @lkvoong do that) shouldn't be much extra

Yeah - I could add that to my new collection workflow.

> I'd suggest an agent attribute loader request (but I can still get these now).

I assume we will want one of these someday - but I guess we can wait for a real use case?

> confirmation and metadata

Can I also get a list of all the collections that exit in Arctos - now would be a good time to see if any of them are missing an agent.

**Comment by dustymc** [comment]
>list of all the collections

[temp_gp.csv](https://github.com/ArctosDB/arctos/files/14439911/temp_gp.csv)

**Comment by Jegelewicz** [comment]
Collections with no matching agent

GUID_PREFIX
--
DGR:Bird
DGR:Ento
DGR:Mamm
PSU:Mamm
UAMObs:Art

These all make sense to me.

Here is the attribute load.

[temp_c_a.csv](https://github.com/ArctosDB/arctos/files/14440763/temp_c_a.csv)
