### ISSUE TITLE
Unable to search by agent preferred name 

### ISSUE THREAD

**Issue by DellaCHall** [ArctosDB/arctos#7469]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
When entering a preferred name in the search screen, no records result. 

**To Reproduce**
1. Go to https://arctos.database.museum/search.cfm
2. Type in a preferred name into the Agent field.
3. Run search
4. No records come up

**Expected behavior**
Records should come up when entering a preferred name.

**Additional context**
If I type just a last name, records do come up.

**Priority**
Critical - needed for work

**Comment by dustymc** [comment]
thanks, patched
