### ISSUE TITLE
Need Help with Arctos Error - trying to print loan header

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#7471]
# Error Text
C43D5232-78F2-4A9F-B44988460F9405E8

# Where it happened
MSB Bird Loan Header print from loan

# Steps to get there
**Describe the actions that led to the error**

# Problem
**Community response to describe the problem that caused the error**

# Solution
**Community response with directions for how to correct the problem**

**Comment by dustymc** [comment]
patched
