### ISSUE TITLE
Help with Object Tracking - I want to bulkload samples into specific positions in a box.

### ISSUE THREAD

**Issue by falco-rk** [ArctosDB/arctos#7473]
Is there a way to bulkload <s>samples</s> parts into specific positions in a box? I think there is not and that is really annoying. So far the only way I have been able to put samples into a box is to put them in one-by-one by pasting the barcode into a position in the Positions view of the box. We don't currently have a scanner and even when we get one, I would like to be able to bulkload the contents of a box and our DNA tubes are too small for barcodes.

@Jegelewicz @campmlc @dustymc

**Comment by Jegelewicz** [comment]
You are correct - there is no way to do this and I do believe there should be, but what is a good way?

When migrating your data, I sent @dustymc files like this

parent_barcode | barcode | position
-- | -- | --
OGL754 | OGLA38578 | 1
OGL754 | OGLA38579 | 2
OGL754 | OGLA38580 | 3
OGL754 | OGLA38596 | 4
OGL754 | OGLA38597 | 5
OGL754 | OGLA38598 | 6
OGL754 | OGLA38605 | 7

parent barcode = box barcode, barcode = vial barcode, position = position in the parent barcode

A tool for this would be VERY useful, but also potentially DANGEROUS, although maybe less-so if we do #7466 ?

**Comment by Jegelewicz** [comment]
And maybe less so if you could only do one parent container at a time?

**Comment by campmlc** [comment]
What size are your DNA tubes? Eppendorf?

**Comment by falco-rk** [comment]
>files like this

That is exactly what i want to be able to do!

>And maybe less so if you could only do one parent container at a time?

I have no problem with that constraint! We usually do it 20-50 samples at a time, often in the same container.

>DNA tubes

we use micronics tubes for [DNA tubes](https://micronic.com/product/0-75ml-tubes-internal-thread/). They come pre-barcoded, but the ones we have do not have barcodes on them and put printed labeled on the side (which is curved so scanning is tough)

**Comment by dustymc** [comment]
Is "sample" a part that's NOT attached to the container system, or a part in a known container that needs a new parent, or ???

Assuming this involves things that can be somehow identified, there could be some loader (or expansion of a current tool or whatever), just tell me what you need and we can probably make it work. BUT...

> don't currently have a scanner

So maybe just using part attributes would be simpler? I'm not sure object tracking makes too much sense unless it involves machines reading labels (where the scariest kinds of mistakes just can't happen), but I think some collections do find some value in _sorta_ using the container system.

>too small for barcodes.

When I win the lottery, I'm buying Arctos about a bajillion RFID tags - drop 'em in your tubes and wave the box at a scanner every now and then....

**Comment by falco-rk** [comment]
sample is a part in a known container that needs a new parent

>When I win the lottery

I can't wait for that....

**Comment by campmlc** [comment]
I highly recommend scanning actual barcodes whenever you can going forward as by far the preferred way to manage. CVS files can be corrupted or have errors. Also, scanning in real time gives immediate feedback and errors if something isn't right. That said, we had Dusty convert 500,000 unbarcoded objects from a previous database when we started, and we barcode them now as we access them using legacy scary tools. We use base 36 barcode values to make labels that are small enough to fit on top of or on the side of a cryovial or eppe tube, and still be scannable. Anything smaller would be challenging unless it is printed on the vial, but that doesn't work for our field collections or budget. Your OGL values may be able to be converted to base36?

**Comment by campmlc** [comment]
And unfortunately, rfid tags in a vial would contaminate DNA and genomic samples . . .

**Comment by falco-rk** [comment]
>A tool for this would be VERY useful, but also potentially DANGEROUS

Is there a way we could make that type of tool less dangerous. Why is is so dangerous? 

I know csv files can have errors but so can everything. Scanning samples one at a time doesn't seem practical, especially because our freezers are not in the same place as our computers (and our students are working on desktops)

**Comment by dustymc** [comment]
So basically a UI for what @Jegelewicz has been sending me:

barcode=OGLA26198 (==identifies a wandering container)


parent_barcode=OGL820 (parent of the position)
position=81 (child of parent_barcode)

results in https://arctos.database.museum/findContainer.cfm?barcode=OGLA26198


<img width="531" alt="Screenshot 2024-02-29 at 13 09 13" src="https://github.com/ArctosDB/arctos/assets/5720791/6ab927c6-88af-4687-8d52-f8adb801f2c8">


yea?

>rfid tags in a vial would contaminate

With glass?!

**Comment by falco-rk** [comment]
Yes

**Comment by Jegelewicz** [comment]
Also that tool would mean less time for the samples outside the freezer....

**Comment by Jegelewicz** [comment]
@falco-rk I do believe you could make labels small enough for your tubes (well maybe you'd have to have them printed. Perhaps @campmlc can add a photo of theirs in action here...

**Comment by Jegelewicz** [comment]
Has anyone tried taking a photo of an MSB box with all the little barcodes on the tops of the tubes and tried to scan barcodes from the photo? Probably wouldn't work, but I'd be the person to try it....

**Comment by falco-rk** [comment]
They make scanners for this purpose that you put a whole plate on and it reads the whole thing. But I don't have one. And you have to buy pre-labeled tubes. And I still think its not practical for putting 5 tubes into a freezer box because i have to pull the whole thing out to scan it.

**Comment by Jegelewicz** [comment]
> someone please prioritize.

OK - what exactly do you want me to do? This issue already has the "wildfire" priority. I don't understand what you mean when you ask us to prioritize! I need direction!

**Comment by dustymc** [comment]
I need direction, and I asked first! 

I have no idea, I'm just hoping I'm going to somehow end up doing what ya'll collectively want me to be doing in about the order ya'll want me to be doing it....

(This should be simple and relatively quick and is entirely additive, maybe that adds up to "just do it"????)

**Comment by falco-rk** [comment]
I need it ASAP. I don't have a not dumb way to put parts in parent containers at the moment so things are hanging out in limbo in my freezers, which is terrible

**Comment by Jegelewicz** [comment]
@falco-rk don't wait. Send files to @dustymc and have him do it for you - send enough and it will become a priority? :-)

**Comment by dustymc** [comment]
>send enough and it will become a priority

I would totally support that as a formal development model! (I think a few of us probably spend way too much time unknowingly dealing with the theoretical.) Let's go direct - this is additive - and see what happens....

**Comment by campmlc** [comment]
I absolutely support building whatever tool that OGL needs to be able to function, but it should be like the DGR Locator - with access limited to OGL, a box at a time, and going forward, I suggest transitioning to using actual barcodes with actual scanners. This is what we did in DGR. I would be happy to schedule a Q and A session and demo ASAP if that would help. I'm sending next some photos of a variety  of our labels which can be used for different applications, and can provide workflow context in a demo. Last year we brought in around 30,000 vials which we can track accurately from field collection to cryotank archive with this methodology.

**Comment by campmlc** [comment]
![PXL_20240229_224341369 MP](https://github.com/ArctosDB/arctos/assets/14808196/3e4a8914-ac56-40cd-b95c-55c26becfa2b)
![PXL_20240229_224842177 MP](https://github.com/ArctosDB/arctos/assets/14808196/7d4bfbb6-f298-45d3-a60f-b3e53eb55fe8)
![PXL_20240229_224246007 MP](https://github.com/ArctosDB/arctos/assets/14808196/93b7f827-2d91-421f-9198-e4d01cdc5834)
![PXL_20240229_224642425 MP](https://github.com/ArctosDB/arctos/assets/14808196/f7bd4d09-a362-4595-bb04-1db8c5ee00aa)
![PXL_20240229_224321763 MP](https://github.com/ArctosDB/arctos/assets/14808196/8c708be0-021d-4adb-8380-7aa70a3c6da0)

**Comment by campmlc** [comment]
Here is a microvial tray with prebarcoded vials that can be read on a scanner tray from the company we buy our vials from. I don't use these, because the adhesive labels are so much more useful and cheaper, and we can attach one to a cryovial and the duplicate to our datasheets during sample collection and processing. This is for just context, as I'm assuming these are similar to what OGL has?
![PXL_20240229_225220770 MP](https://github.com/ArctosDB/arctos/assets/14808196/631d6764-b71c-42ea-8515-ac4846385e03)

**Comment by campmlc** [comment]
The above are all base36 values to make a 2D barcode small enough to fit on top or side of a cryovial. Here is a 1D linear barcode that can be wrapped on the side: 
![MSB Bird 1X barcodes](https://github.com/ArctosDB/arctos/assets/14808196/d5cad0c9-793a-49cb-ae87-c37216b1ea2e)

**Comment by dustymc** [comment]
This is complicated by https://github.com/ArctosDB/arctos/issues/7466 - I really hate writing tools that I'm possibly going to have to immediately rewrite, can we find some way to not *always* get stuck in some partial state? Reject everything that involves some partial state? That doesn't seem right, I have no idea, still don't like this....

@mkoo

**Comment by campmlc** [comment]
Just posted about a zoom discussion tomorrow 1pm PST to figure out #7466 ?

**Comment by Jegelewicz** [comment]
Is there a new tool?Do I need to add it to the tool page?

**Comment by dustymc** [comment]
[Container Position Loader](https://arctos.database.museum/loaders/loadContainerToPosition.cfm)

**Comment by campmlc** [comment]
Cool - I was going to ask the same thing. Maybe add these links to issues before they are closed?

**Comment by campmlc** [comment]
So is the position value just the position number in whatever grid or table is in use? So for a freezer box, position would be some integer between 1-100? and parent barcode would be the freezer box barcode?

**Comment by falco-rk** [comment]
The Container Position Loader lets you bulkload things into positions regardless of the barcode's container type and the parent barcode's container positions type. Meaning I can bulkload cryovials into a microplate that only holds microwells.

**Comment by dustymc** [comment]
Hole patched.
