### ISSUE TITLE
b in agent attribut load template

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7475]
https://arctos.database.museum/loaders/bulkload_agents.cfm?action=ld

The template for loading agents includes a "b" where there should be an "n"

![image](https://github.com/ArctosDB/arctos/assets/5725767/d1389bbc-a0df-41f0-abe4-8c223d9c0011)

Makes it hard to update when adding multiple agent attributes

**Comment by Jegelewicz** [comment]
Also just realized the template is missing attribute_value_n

**Comment by dustymc** [comment]
> template is missing attribute_value_n

??

<img width="1418" alt="Screenshot 2024-02-29 at 14 05 52" src="https://github.com/ArctosDB/arctos/assets/5720791/73cd52b6-9e91-4b68-b143-4a57dbd5bdd3">

[cf_temp_agent(1).csv](https://github.com/ArctosDB/arctos/files/14454036/cf_temp_agent.1.csv)

**Comment by dustymc** [comment]
OIC - in the docs, thanks.

**Comment by Jegelewicz** [comment]
Yeah - I didn't download the template, I just copy-pasted the docs....I know my bad....
