### ISSUE TITLE
Code Table Request - Agent attribute - add culture of origin attribute to agents

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#7476]
## Initial Request
https://github.com/ArctosDB/arctos/issues/7133
### Goal

> It would be useful if agents could use the culture of origin attribute currently available for catalog objects. Geographical affiliation are important but there is no structured place to capture this on agent records

### Context

> So there's a doll maker who was born in Kotzebue, and learned this tradition from these doll makers from Kotzebue who have a particular style carving, of making them. But then she lived most of her life in North Pole, right near Fairbanks, and so she's a Inupiaq, and her cultural affiliation is associated with that Inupiaq community of Kotzebue. But she lives in North Pole.

### Table
Agent Attributes - ~~Identifications~~ other

### Proposed Value
~~culture of origin~~

cultural affiliation

### Proposed Definition
@AJLinn - I'll try, but please correct and edit
~~The major group(s) from which an individual has descended~~

**Selected definition:**
The major cultural group(s) to which an individual claims descent or identification. See [CT Culture](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctculture) for possible correspondence and most up-to-date spellings and orthography.

### Collection type
Agents

#### Attribute data type
free-text

#### Attribute controlled values
none

#### Attribute units
none

#### Part preservation attribute affect on "tissueness"
NA

### Priority
normal priority

### Example Data

> So there's a doll maker who was born in Kotzebue, and learned this tradition from these doll makers from Kotzebue who have a particular style carving, of making them. But then she lived most of her life in North Pole, right near Fairbanks, and so she's a Inupiaq, and her cultural affiliation is associated with that Inupiaq community of Kotzebue. But she lives in North Pole.

### Available for Public View
yes

### Helpful Actions

- [x] Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

- [x] Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

@ArctosDB/arctos-code-table-administrators 

## Approval
_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection
_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation
_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

- [x] Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

- [x] Add or revise the code table term/definition as described above. Ensure the URL of this Issue is included in the definition. URLs should be included *_as text_*, separated by spaced pipes. Do not include HTML in definitions.

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by AJLinn** [comment]
Sorry for the late edit.
Updated proposed definition:

"The major cultural group(s) to which an individual claims descent or identification. See [CT Culture](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctculture) for possible correspondence and most up-to-date spellings and orthography."

**Comment by Jegelewicz** [comment]
but "free text, public viewable is not a good term request....

**Comment by ewommack** [comment]
I keep doing funny things don't I. Corrected

**Comment by Jegelewicz** [comment]
I'm not sure that

`culture of origin`

properly reflects

> to which an individual claims descent or **identification**

that's why I suggested associated culture, but other ideas might be better!

**Comment by AJLinn** [comment]
the only reason we used "culture of origin" was because we thought we could link to the code table.

If we want to freewheel it, let's call it "cultural affiliation".

**Comment by Jegelewicz** [comment]
I like that!!!

**Comment by ewommack** [comment]
Ok I think we're ready to head through the process. Thanks for your help @Jegelewicz. Please let us know if we can provide any more info.

**Comment by Jegelewicz** [comment]
@dustymc @ArctosDB/arctos-code-table-administrators check boxes?

**Comment by dustymc** [comment]
Is this proposing a new ([confusing](https://handbook.arctosdb.org/documentation/identification.html)) category?

**Comment by Jegelewicz** [comment]
> Is this proposing a new ([confusing](https://handbook.arctosdb.org/documentation/identification.html)) category?

I would say this should be included with either names or addresses. @AJLinn @ewommack

**Comment by Jegelewicz** [comment]
> Is this proposing a new ([confusing](https://handbook.arctosdb.org/documentation/identification.html)) category?

Corrected.

**Comment by dustymc** [comment]
>Identifier

Definitely not OK with that. (I don't particularly care what we call anything, but mixing this in with eg ORCID would have drastic functional implications.)

This looks like an ``other`` to me, or **_maybe_** a ``name`` (that also seems wrong, but not in any way that I can see breaking my scripts, so....) or **_supermaybe_** something new.

**Comment by Jegelewicz** [comment]
I would lean towards an address. Not a physical address, but a cultural one.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I support this. Box checked.

**Comment by Jegelewicz** [comment]
@dustymc how about now?

**Comment by dustymc** [comment]
I don't have any technical objections to address, but those also seem pretty important to include in default searches and are currently involved in https://github.com/ArctosDB/arctos/issues/7434#issuecomment-2042864318. "Indian" matching 1.4B agents might not be the best thing....

**Comment by Jegelewicz** [comment]
Code Table Committee changed category to other. Added.
