### ISSUE TITLE
Multiple Classifications per Source per Name

### ISSUE THREAD

**Issue by camwebb** [ArctosDB/arctos#7478]
If there are two or more Classification records in the same Source for the same Name, then the hierarchical information from both classifications is merged by `getTaxaDataByCollection()`, i.e. visible in the pop-up on the specimen details page, and in the IPT export. I've just been going through Arctos Plants names used by UAM where this was happening and deleting one of the classifications (~20 names). In two cases (_Decodon_ and _Mertensia_) these were true homonyms (illegal though), and I did check carefully that no one else was using the homonym. In most cases however the second classification was a duplicate imported from another source.

Given that:

1. the presentation of the information (via merging) is not helpful/correct,
2. in the case of a true homonym there is no way for the user to specify which of the classifications from the same Source is intended,
3. homonyms can co-exist happily in different Sources, and
4. @Jegelewicz has said "[there should be only one classification per name in each source](https://github.com/ArctosDB/arctos/issues/6385#issuecomment-1579720723)"

should there not be a DB restriction on multiple classifications for the same name in the same Source, _for the managed Sources_ (as opposed to the external sources for cloning)?  I'm sure you have discussed this, but I can't find a specific reason for permitting multiple classifications per source per name. Thanks.

**Comment by dustymc** [comment]
>can't find a specific reason

We have to allow it so we can talk to the weirdos ("structure-limited individuals"?) who do that sort of thing, and there's not any real distinction between 'managed' and 'wandered in.' That's not a "no," but I'm not sure how I'd enforce anything either.

>Arctos Plants

I would avoid this by avoiding the big "legacy" classifications for anything you much care about - you can never tell who's going to (or has) done whatever awful thing in there, they're nice for a sort of default but I would not put any work into them. (And think maybe I'm about the only one who sees the world thataway, certainly not the only take on the situation!)

**Comment by camwebb** [comment]
Thanks.

> but I would not put any work into them. 

Not sure what you are referring to here. As far as I am aware, Arctos Plants is the only active/dedicated Source for plants, so this is the one we have to fix/tweak.  Not to do some work on this is not an option, because many names still have no classification.

Maybe we can can discuss this at the next Taxonomy Committee meeting.

**Comment by dustymc** [comment]
>what

https://handbook.arctosdb.org/documentation/taxonomy.html#taxon-classification-sources

>option

https://github.com/ArctosDB/arctos/issues/new?assignees=&labels=Function-CodeTables&projects=&template=code-table-request.md&title=Code+Table+Request+-+

**Comment by Jegelewicz** [comment]
See also https://github.com/ArctosDB/arctos/issues/6500

**Comment by camwebb** [comment]
Got it (I think). Thanks. To be clear, we would still use Arctos Plants as Rank 1 preferred source, but then use WFO as #2. I'm assuming we shouldn't edit WFO (if/when it is added), because then it wouldn't be WFO any more.

**Comment by Jegelewicz** [comment]
> I'm assuming we shouldn't edit WFO (if/when it is added), because then it wouldn't be WFO any more.

Yep!

> Here's a big +1 for adding WFO.

That would be nice - but right now not possible with my limited resources. We could add specific things from WFO, but again, I do not have time to do the work.

FWIW your ranks would be the other way around

1 WFO
2 Arctos

That way you get the authoritative source when it is available and for everything else you get whatever the Arctos community has curated.

**Comment by dustymc** [comment]
>+1 for adding WFO.

Done.

> shouldn't edit 

Can't.

>number 2

I think the ideal would be more like

1. That One Genus Of Whatever That I Work In
2. Some Other Genus Managed By Some Other Collection
3. A Species Of Weed That That Number Four Got Wrong
4. World Flora Online
5. Arctos Plants


That is, stuff you curate, then stuff your peers curate (nobody's doing this so all theoretical, but I'd expect little or no overlap in these), then maybe some sort of override if your fallback is weird (not sure I expect anyone to actually do this, but it's an easy way to demonstrate that you don't have to buy into an entire source to use it, nor does a 'source' have to follow any recipe - one subspecies of dandelion fits the model fine), then however many 'defaults' it takes to fill in any remaining gaps in the collection.

**Comment by camwebb** [comment]
This is v helpful. _Thanks_ for adding WFO - now rank 1 Source for our 3 ALA collections. Fall back is Arctos Plants. 

I like the idea of adding a Source for which a curator is an expert, and stacking that in front of WFO. I'm not in a position to do that, but could be useful. I guess this would require a code table request to mint a Source name - e.g., 'Salicaceae (curated by J. Smith)' - and maybe something backend to allow the classification edit tools to work.

**Comment by dustymc** [comment]
>require a code table request

Yup.

>'Salicaceae (curated by J. Smith)'

The hope has always been something more like '..following some publication' but yea, "random stuff according to me because reasons" is fine too. (The system should accommodate whatever anyone comes up with, whether it's anything like my imaginings or not!)

https://github.com/ArctosDB/arctos/issues/6311 was my experiment in that sort of thing.

>edit tools

There's control of that now (for just this reason) - here's how I set up WFO (typo and all....)

<img width="1245" alt="Screenshot 2024-03-01 at 05 59 15" src="https://github.com/ArctosDB/arctos/assets/5720791/525d537e-8845-4995-92f2-b06dc3375ddb">

If I were managing something I'd just do it in google sheets (in case I want to collaborate) in the Arctos Classification Loader format, limit edit tools to me and the bulkloader, and periodically upload my changes. (Maybe I'd want to set up some automation if that became burdensome, and the loader environment is designed to support that, but I think for most use cases the ~3 clicks to upload the spreadsheet every now and then is probably just fine.)

**Comment by Jegelewicz** [comment]
@camwebb can we close this?

**Comment by camwebb** [comment]
Yes. Thanks
