### ISSUE TITLE
Unable to Access MVZ Egg collection Data

### ISSUE THREAD

**Issue by dpkeddyhector** [ArctosDB/arctos#7479]
I'm having difficulty accessing the Arctos database when I submit a query regarding bird eggs housed at the Museum of Vertebrate Zoology at Berkeley. 

I have tried repeatedly over the last 12 plus hours but without success. 

Please help. 

Thanks. 

Dean P. Keddy-Hector
halconfemoralis@gmail.com

**Comment by dustymc** [comment]
This should be resolved, please re-open if you are still having problems.

**Comment by dpkeddyhector** [comment]
That fixed it. Thanks for your help.
