### ISSUE TITLE
Data entry error: part name "whole organism" is invalid[external CONTACT]

### ISSUE THREAD

**Issue by kderieg322079** [ArctosDB/arctos#7480]
We are cataloging ectoparasites associated with mammal hosts so the only part for the parasite lot is whole organism. When attempting to use "whole organism" for part name, it shows no matches found:
<img width="799" alt="Screen Shot 2024-03-01 at 2 53 07 PM" src="https://github.com/ArctosDB/arctos/assets/82051765/3ce7ace9-49b5-4b92-ab7b-bace5cb53c2a">

When trying to create record, the error reads:
<img width="1065" alt="Screen Shot 2024-03-01 at 2 53 32 PM" src="https://github.com/ArctosDB/arctos/assets/82051765/549cb4ef-b5f2-47f6-8f5c-296c593968fc">

I know that "whole organism" can be used for parasites because MSB uses it for parasites, such as this record: https://arctos.database.museum/guid/MSB:Para:10252

What are we missing? Any guidance is appreciated.

**Comment by dustymc** [comment]
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name, 'collection settings' will let you choose parts for collections you manage.

**Comment by kderieg322079** [comment]
Great, it is a new collection and I didn't realize parts had to be added. Thanks!
