### ISSUE TITLE
 specify a preferred classification for a individual taxon name?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#7481]
From #7452 : Since we can choose which classification source to use, is there any way we could specify a preferred classification for a individual taxon name? For example, select aphiaID or an Arctos classification identifier that would explicitly distinguish a name that is a synonym across classifications in Arctos? I want to select the Biota in WoRMS from the one in Arctos Plants, even though I might have Arctos Plants as a higher level rank in preferred classification.

**Comment by Jegelewicz** [comment]
@campmlc my take on this is that you should prefer the better curated source (WoRMS via Arctos). The chances that it will make anything besides Biota worse in your taxonomy are pretty slim (in fact it will probably improve anything that it happens to have in common with Arctos Plants) and you will get the correct classification for Biota. No need to try and pick out very specific terms. But if you are determined to do this - the path is to create a new taxonomy source managed by you, add a classification for Biota (and nothing else), then prefer it above both Arctos Plants and WoRMS via Arctos.

**Comment by campmlc** [comment]
Got it, thanks!
