### ISSUE TITLE
Add "part type" descriptor to part attributes code table?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#7482]
I need to add specific terms to part attributes to record plant and environmental sample types. eg "leaf", "root", "soil", "biocrust".  I have cryovials with these types of samples in them. For leaf and root, I can use tissue as a part name, and for soil and biocrust I can use "environmental sample", although that's not really fair to the biocrust, which is a living entity. If I do that, I'd like to have a part attribute with some sort of controlled vocabulary (or may free text to start until we see how people are using these), to record leaf sample root, etc. This could be a "tissue type" part attribute for leaf and root, but that doesn't work for soil and biocrust. Perhaps "part type", or maybe "part description"? I know I can just put this in remarks, but I anticipate this information to only get more complex as we add non-traditional part types to Arctos, and it would be good to have a standardized place to put it.
Thoughts?

**Comment by Jegelewicz** [comment]
I suggest just using the correct part names for leaf, root and soil (geosample):

leaf [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#leaf)
root [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#root)
soil = geosample [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#geosample)

biocrust is maybe a new thing for which you should make a code table request for a new part name? Perhaps biosample as a compliment to geosample? Or maybe just biocrust?

**Comment by andrew-hope** [comment]
Yeh, seems like each of these can be a specific part. Similar to skull or fur? Leaf wouldn't strictly be a tissue type? Consists of xylem and phloem etc... Presumably this refers to leaves and roots that may not be associated with a voucher plant specimen, but may or may not be identifiable to the species that they came from. If not, how are we proposing to enter specimens into Arctos that do not have a taxonomic assignment? Just "Plantae?"

I feel like environmental samples would be aggregates of species and other things (potentially). A biocrust is essential a single functional unit (which likely contains some other species incidentally) similar to a lichen (multiple obligately associated species). But, a biofilm would be a community of species. A soil sample would be an environmental sample but it could be biological (whole unsterile soil with microbial communities) or geological (sterilized, with or without organic material).

**Comment by campmlc** [comment]
For some reason, when I searched the code table, I didn't see "leaf" or "root" as options.  Glad they are there, as that would be my preference. "soil" is now in Arctos Rocks, and the definition of "environmental sample" includes biocrust, so I can use that unless we switch to biosample, which might be better in the long run.

**Comment by dustymc** [comment]
resolved?
