### ISSUE TITLE
Quarantine Taxon Name - Adz -->Adze

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#7483]
I think this is how @Jegelewicz suggested we deal with updated entries at the Nomenclature 4.0. Quarantine the old name and add the new terms? Feel free to change/edit this issue if there is a better way to handle this.

Name Quarantine Documentation is at https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxon_name_type

### Name suggested for quarantine
Adz
https://arctos.database.museum/name/Adz

### Replacement Name

Adze
https://page.nomenclature.info/recherche-search.app?lang=en&q=adze&ps=50&pid=1&ws=INT&wo=N

### Reason for quarantine 
The Nomenclature 4.0 updated the entries associated with the term adze. Formerly it was spelled without the e, now all forms include the e.

[ The following steps are not required for the initial request, and may be completed by community members with sufficient access. Please do not remove the text below. ]

### Relationship

[ INITIALLY OPTIONAL, requires manage_taxonomy access: Create a suitable taxon relationship between the nominated and replacement name. ]

### Taxonomy Committee Project

[ INITIALLY OPTIONAL: Please add this issue to the Taxonomy Committee Project. ]

### Collection Summary and Contacts

[ INITIALLY OPTIONAL, requires manage_taxonomy access: use the Manage Data / Metadata / Quarantine Taxon tool to provide a summary of the collections using the nominated name. Make sure the github contacts are outside any code block; they should turn into links. ]

### Data

[ INITIALLY OPTIONAL, requires manage_taxonomy access: use the Manage Data / Metadata / Quarantine Taxon tool to provide data sufficient to un-do this action ]

### Pause

Allow 30 days for all affected collections to respond. Proceed only after 30 days (and an issues committee meeting) has passed, or after all affected collections have approved the quarantine proposal.

### Update Identifications

[ AFTER PAUSE, requires manage_taxonomy and global_admin access: use the Manage Data / Metadata / Quarantine Taxon tool to update identifications. The tool will change all ID formulae to "A {string}" and move all references to the quarantined taxon to the replacement. ]

### Finalize Quarantine

[ AFTER PAUSE, requires manage_taxonomy and global_admin access: use the Manage Data / Metadata / Quarantine Taxon tool to quarantine the taxon name, making it unavailable for all use excepting relationships ]

### Close this issue

[ After all of the above have been completed, close this issue ]

**Comment by Jegelewicz** [comment]
I have created the new term Adze, All uses of Adz should be changes to Adze, then we can quarantine Adz.

![image](https://github.com/ArctosDB/arctos/assets/5725767/3c8ad06d-68f0-40f8-b322-184d97eb0111)

**Comment by Jegelewicz** [comment]
I added classifications for the new terms and the new Nomenclature 4.0 classifications are in the classification bulkload tool.

**Comment by dustymc** [comment]
Summary:

|guid_prefix|identification_order|numberids|link_to_records|taxon_name|link_to_taxon|
|--|--|--|--|--|--|
|UAM:EH|1|3|https://arctos.database.museum/search.cfm?taxon_name_id=12029048|Adz|https://arctos.database.museum/name/Adz|


Data Quality Users:


@AJLinn

[temp_taxon_quarantine_summary.csv](https://github.com/ArctosDB/arctos/files/14483671/temp_taxon_quarantine_summary.csv)

The requesting collection is the only user, skipping the waiting period.

The required relationship exists.

... and there's a bug in the tool, I'll finish this with next release.
