### ISSUE TITLE
Add soil as part name

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#7484]
Revisting #3080.  I agree that forcing all the below into "geosample" is uninformative and not what most people would search on when they are looking for "soil".  I will be adding  soil and biocrust samples on an annual basis going forward, and I need to be able to make them easily discoverable and distinguishable.  Currently they both fall under the definition of environmental sample, and this definition is based on the purpose of the sample rather than the identity of the sample. Geosample is much too vague.

From @Nicole-Ridgwell-NMMNHS 
We might eventually need to add some of those. Do we add them now, before they are necessary, or wait until someone actually needs them? If we do add them, I would simplify the list slightly:
Gas
Liquid
Mineral
Rock
Sediment
Soil

I've been going back and forth on whether to use mineral or crystal. I think I'm finally convinced to just use mineral because it will be more straightforward for searching.

_Originally posted by @Nicole-Ridgwell-NMMNHS in https://github.com/ArctosDB/arctos/issues/3080#issuecomment-726198589_

**Comment by Jegelewicz** [comment]
I don't think having an identification ([soil](https://arctos.database.museum/name/Soil)) and a part that are the same thing makes sense?

**Comment by Jegelewicz** [comment]
FWIW, these are also taxonomy

[mineral](https://arctos.database.museum/name/Mineral)
[rock](https://arctos.database.museum/name/Rock)

and we do have the part name mineral.

I think we need to figure this one out and make sure we are happy with whatever choice we make.

Art people use object for everything - the identification tells you what they have. Maybe geology people should do the same to keep things in one place? Just use geosample and get rid of the other things that should be taxonomy.

**Comment by Jegelewicz** [comment]
I think this is resolved? Soil is an identification.
