### ISSUE TITLE
MSB:DGR collection seems to have no associated parts?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#7485]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Trying to create records/bulkload records in MSB:DGR - in both forms,there appear to be no acceptable parts. I've tried environmental sample, geosample, leaf, root, tissue, unknown.
I checked the code tables and it seems these parts are not associated with this collection, but apparently nothing is. 

**To Reproduce**
1. Go to Bulkload Records or Create Records for MSB:DGR
2. attempt to bulkload or enter a new record in either form.
3.  See error: eg. "part_1_name [ environmental sample ] is invalid"

**Expected behavior**
To have at least some part name be allowed for MSB:DGR collection.

**Additional context**
 I don't seem to have permissions to do anything in terms of adding an existing part to my collection. 

**Priority**
High. These data are needed for NSF report.

**Comment by Jegelewicz** [comment]
This is not a bug - this is how things work now - you need to select the parts you want to have available to the collection after it is created. Documentation definitely needs an update.

**Comment by campmlc** [comment]
So how do I do that? Did we record the demo? I saw nothing obvious in the tools menu or in manage collection.

**Comment by Jegelewicz** [comment]
Go to part code table and select the collection settings button, select your collection then check the parts you want.

**Comment by Jegelewicz** [comment]
@mkoo didn't we record this? where are the recordings?

**Comment by campmlc** [comment]
OK, I found it. But perhaps we need to link this to something obvious in Manage Collection or in the Tools Menu? 
Also, what does "Code Table for Collection" do in Tools? I thought perhaps that was it, but I get an error trying to access.

**Comment by campmlc** [comment]
Well, I would not go so far as to call that obvious, especially since it is a major change. Maybe we can put that comment at the top? Also, why did we switch formats? The previous manage collection form was much more visually comprehensible.

**Comment by mkoo** [comment]
> @mkoo didn't we record this? where are the recordings?

Sorry I was late to upload the recording but they are now in the shared AWG meeting folder--in a folder called[ Demo video and audio recordings](https://drive.google.com/drive/folders/1yNyC3-__t9UqgjkxEaoJLG1KB9nvCflm). MP4's are renamed with the topic

I'll be faster next time now that it's a little organized

>why did we switch formats? The previous manage collection form was much more visually comprehensible.

We switched so that the collections can have more powerful/ flexible control of which attributes their collection will use. Basically every collection is now customizable as not all Bird collections do the same thing.

**Comment by campmlc** [comment]
I meant - why did we change the UI format? I now have to scrolll down multiple pages rather than being able to see the different tables in a single view, making it hard to visually process what needs to be changed or what content a given save button is assocatied with.
I have no problem with the added customization of parts - just how to do it!
