### ISSUE TITLE
Manage Collection does not allow change to preferred classification order

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#7486]
Problem:  
In the newly created collection MSB:DGR, I need to be able to change the preferred classification order to deal with a synonymy problem. But when I change the preferred order to Add WoRMS above Arctos Plants and hit save, nothing changes. The page refreshes with the same previous order.

Additional context: 
MSB:DGR collection needs to provide an identification for soil biocrust; attempting to use A {string} identification "Biota {biocrust}", with Biota as the WoRMS classification of superdomain of all life. But Arctos Plants has this as a genus of conifer. I need the WoRMS classification to be above Arctos Plants in priority.

**Comment by Jegelewicz** [comment]
> Add WoRMS above Arctos Plants and hit save

Just to clarify - WoRMS shuld be 1 and Arctos Plants 2, and that isn't saving? You have to change the numbers for anything to happen.

**Comment by campmlc** [comment]
Yes, I changed the numbers so WoRMS was first and Plants second, got rid of the cultural classifications, hit save, and nothing changed.

**Comment by Jegelewicz** [comment]
I cannot access the collection, so I cannot see what is going on - @dustymc any ideas?

**Comment by campmlc** [comment]
I figured it out. I saved using the bottom save button, not realizing each table has it's own save button. Every other form in Arctos forces you to scroll all the way down. I don't object, but got caught off guard.
