### ISSUE TITLE
Cache refresh set of search results

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#7488]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I uploaded a bunch of photos for a grant funded project and most of them have thumbnails that are showing up broken in the search results. They all seem to work on the specimen record page. 

**To Reproduce**
Go to:
https://arctos.database.museum/search.cfm?media_type=image&loan_project_id=10003712
With media results turned on.

**Expected behavior**
For media thumbnails to show up

**Screenshots**

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**
Google Chrome

**Additional context**
Dusty could you do a cache refresh on this set when convenient? 

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by mvzhuang** [comment]
Awesome. Thanks Dusty! And yes, would prefer that over the one by one refresh if possible.
________________________________

**Comment by AJLinn** [comment]
@dustymc I just tried the new tool and I got an error code along with the angry purple page:
C4A7755E-06EA-486A-B49B977B8F64C899

What did I do wrong?
