### ISSUE TITLE
Publish Bell (MMNH/JFBM) to Symbiota portal

### ISSUE THREAD

**Issue by adhornsby** [ArctosDB/arctos#7490]
With the Bell Museum zoology collections (well, some of them...) now on Arctos, we need to set up a pipeline to get our records regularly published to our state-funded Symbiota portal [https://bellatlas.umn.edu/](https://bellatlas.umn.edu/).  Is there a workflow/IPT already for moving data Arctos -> Symbiota?  I don't think we have a specific definition for "regularly" -- something between monthly to annually depending on how easy/automated it is.

We just hired a new data manager (started yesterday!) and she'l likely be the one to handle this, but I wanted to start by seeing which wheels she doesn't need to reinvent.

**Comment by dustymc** [comment]
http://ipt.vertnet.org/ should have everything needed for this.

**Comment by adhornsby** [comment]
@dustymc Will Vertnet IPT support publishing our mollusks / crustaceans / parasites when those collections are up on Arctos?  Or will that require a separate workflow?

**Comment by Jegelewicz** [comment]
@adhornsby don't let the name fool you, VertNet IPT handles ALL collection types, however, publishing to a Symbiota portal generally requires an extra step or two depending upon the who is managing the Symbiota portal. They might be able to pick everything up from the IPT, or you might have to initialize the data grab by Symbiota. I suggest that you first discuss this with whoever is managing the Symbiota portal, then we can figure out if we need to help you do anything different. Also, I would be happy to get on a call with everyone if that will help.

**Comment by adhornsby** [comment]
Got it, thanks @Jegelewicz and @dustymc !  We'll be in touch once our data manager is ready to tackle this.

**Comment by adhornsby** [comment]
@Jegelewicz Our data manager (Anna) is ready to start working on this.  Should we bug you or Dave Bloom to get started?  Or both?

**Comment by Jegelewicz** [comment]
@adhornsby the first step is to contact the Symbiota portal manager to see how they want to receive the data. Some portals can go get it themselves from the IPT, others require more manual processes.

**Comment by adhornsby** [comment]
@Jegelewicz Looking at http://ipt.vertnet.org/ right now, it appears we don't even have all the MMNH/JFBM collections set up with VertNet IPT.  I assume I should tackle that first with Dave Bloom?  Otherwise we'll just be trying to set things up based on an old (2016) version of only our bird collection...

**Comment by Jegelewicz** [comment]
>  it appears we don't even have all the MMNH/JFBM collections set up with VertNet IPT. I assume I should tackle that first with Dave Bloom? 

Fair

https://github.com/ArctosDB/data-migration/issues/1151
https://github.com/ArctosDB/data-migration/issues/1142
https://github.com/ArctosDB/data-migration/issues/1124

are where we should do this work. It might be easier to have a quick call - I am free most of today, so give me a time and I'll send a Zoom. If you can't today, let's try Monday?

**Comment by adhornsby** [comment]
OK, thanks @Jegelewicz !  I'm traveling today through next week.  Could we plan on Mon March 25?

**Comment by Jegelewicz** [comment]
Sure! What time? I have one meeting (noon MDT) on the calendar right now.

**Comment by adhornsby** [comment]
Thanks @Jegelewicz !  Let's do 11 AM Mountain if that works.

**Comment by Jegelewicz** [comment]
Calendar invite sent!

**Comment by dustymc** [comment]
Done?
