### ISSUE TITLE
[CONTACT: Blocked Network]

### ISSUE THREAD

**Issue by monkgethan** [ArctosDB/arctos#7492]
restricted IP: 54.177.94.188

Hi, I have never used this before so sorry if this isn't done right. Trying to access ARCTOS from above IP (UC Davis), and is showing connection blocked. Have tried with and without VPN on without success. Please advise, thanks.

**Comment by dustymc** [comment]
That's an AWS VPN IP, which we do not have the resources to safely support. We should definitely be able to provide access from UCD, please let us know if you have a different IP.

**Comment by monkgethan** [comment]
Hi, well sorry for the trouble, but I just reopened arctos again without
changing anything on my end and it worked fine. So I guess you can mark
this as closed.
