### ISSUE TITLE
Feature Request - add issued by to preferred identifiers in manage collection

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7493]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

Some collections select Ids to appear in the summary section of the catalog record

![image](https://github.com/ArctosDB/arctos/assets/5725767/28398638-7c7e-4339-8f0f-fe802e9b605a)

They are selected by identifier type and display only identifier type and value.

**Describe what you're trying to accomplish** 
_A clear and concise overview of the goals; why are you asking for this?_

Make a better case for using issued by and help collections that want to make use of specific identifiers in the summary make more specific choices.

**Describe the solution you'd like**
_How might we accomplish your goals?_

Instead of selecting preferred other identifiers to display by type, allow selection by issuing agent.

![image](https://github.com/ArctosDB/arctos/assets/5725767/54c22fc6-7890-4f2a-a868-95f6b9d5c0f4)

and display them on the catalog records as issued by identifier value.

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**
_Add any other context or screenshots about the feature request here._

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._

**Comment by mkoo** [comment]
Thanks for making this request! This was exactly what has been requested by a few other folks besides Wyoming. Would be great to have enabled.

**Comment by Jegelewicz** [comment]
I need to make an announcement and get people to review manage collection for this.

**Comment by Jegelewicz** [comment]
1. added to AWG agenda
2. Made an article for the next newsletter - https://github.com/ArctosDB/newsletter/issues/266
