### ISSUE TITLE
duplicate agent notification: Henry Wetherbee Henshaw

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#7494]
I'm probably about to do something cryptic, so I'm opening an issue here to mitigate that.

I'm refining some checks, and it turns out that https://arctos.database.museum/agent/10005520 is properly wearing a LOC identifier, and https://arctos.database.museum/agent/21251840 (a clear duplicate)  has the same identifier in the wrong slot. I'll need to remove the identifier from the less-data agent so I can fix the 'good' version.

This shouldn't be possible going forward, just a legacy cleanup issue.

**Comment by ewommack** [comment]
Do you want to discuss the actions at the Agent Committee next week or is this keeping track of things?
