### ISSUE TITLE
Arctos ER-ish diagram, useful for documentation?

### ISSUE THREAD

**Issue by camwebb** [ArctosDB/arctos#7495]
As part of training a new staff member here at UAM, I created the following ER-ish roadmap to Arctos tables and the contents of `flat`. It appears on our internal [documentation site][1]. I'll add a link to those pages and this diagram to the [Resources][2] page of the Handbook, but was wondering if there was some other place in the documentation that this would be useful. I've heard opinions that publishing a (new) full ER diagram of Arctos is unhelpful, due to Arctos's complexity and ever-changing nature, but this summary should be valid for a while.

![Arctos structure](https://github.com/ALA-herbarium/documentation/raw/main/img/data_model.jpg)

[1]: https://github.com/ALA-herbarium/documentation/blob/main/data_model.md
[2]: https://handbook.arctosdb.org/resources/

**Comment by mkoo** [comment]
Hey @camwebb thanks for putting this together and sharing! Emily is in the middle of trying to make one for a more general audience but I think yours is pretty darn useful!

Is this in an editable or annotatable format? And I think we could definitely incorporate into the handbook-- thanks again!

**Comment by camwebb** [comment]
> Is this in an editable or annotatable format?

Yes, it's a [GraphViz](https://graphviz.org/) [file](https://github.com/ALA-herbarium/documentation/blob/main/img/data_model.dot)

**Comment by Jegelewicz** [comment]
@falco-rk see the first comment in this issue.

**Comment by dustymc** [comment]
done?

**Comment by camwebb** [comment]
If anyone is looking back at this... the above image contains some I errors I have since discovered. In particular the structure of Parts and Containers is more complex than shown. Will update the original at some point.
