### ISSUE TITLE
Feature Request - Expand Agent Contact Information or Identifier field

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#7497]
I'm creating a new person for the first time since we changed how the Agents interface looks. The field for "Contact Information or Identifier" is short and can't be expanded, so it's hard to see what you're typing"

![image](https://github.com/ArctosDB/arctos/assets/967275/6a359126-50fe-4365-9561-a138984656e5)

Can we make that field expandable to view the entry?

Also related, why is it showing that I deprecated the Preferred Name that I just created? It does have 'deprecation_type' = 'update' but not sure what that means in the context of deprecation.

![image](https://github.com/ArctosDB/arctos/assets/967275/0066cc4c-a2c1-4c84-86d2-6b38482bb7f1)

**Comment by ccicero** [comment]
Also note that the field is expandable in the edit window, but that's an extra step of entering an address for someone.

**Comment by dustymc** [comment]
>why is it showing that I deprecated the Preferred Name that I just created?

Just an easy way to keep a history all in one place - no need to care until I get confused and mangle 'your' agent, then that can be used to un-mangle.
