### ISSUE TITLE
Code Table Request - Allow NULL in georeference protocol

### ISSUE THREAD

**Issue by camwebb** [ArctosDB/arctos#7499]
**Goal**

A common method of georeferencing is to use a variety of external, online tools (Internet search, GMaps, OSM, .geonames.org, CalTopo, etc.) to locate the geoposition for a label spatial description. There is no appropriate option in `ctgeoreference_protocol` for this.  One is currently forced to use "not recorded" which is OK, but not informative.

**Proposed Value**

Despite the odd application of this term to digital activities, "manual" may be the best new term to add for the above. Alternately, "various tools".

**Proposed Definition**

Coordinates+error determined by operator using one or more external tools (e.g., internet search, Google Maps, OSM, geonames.org, CalTopo, paper maps, atlas, etc.).

----

@ArctosDB/arctos-code-table-administrators 

## Approval
_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [ ] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection
_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation
_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

- [ ] Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

- [ ] Add or revise the code table term/definition as described above. Ensure the URL of this Issue is included in the definition. URLs should be included *_as text_*, separated by spaced pipes. Do not include HTML in definitions.

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by camwebb** [comment]
(There is of course also the locality attribute "georeference source" : notes/methods can go in here. But I still think general, "manual" research counts as a separate protocol from the existing, and since georef protocol is a mandatory field we thus need another possible value.)

**Comment by Jegelewicz** [comment]
While not recorded may be uninformative, how is it different than the vagueness of 

> Coordinates+error determined by operator using one or more external tools (e.g., internet search, Google Maps, OSM, geonames.org, CalTopo, paper maps, atlas, etc.).

especially when the details are expected in georeference source?

This is another place where we are forced to provide something even though there is nothing to provide. Why can't protocol just be blank? If we feel we must say something, how about "see georeference source" since that is where the details for any "undocumented" protocol are expected?

**Comment by camwebb** [comment]
> Why can't protocol just be blank?

I agree this may be the better solution than adding to the code table.

**Comment by dustymc** [comment]
>Why can't protocol just be blank?

Nobody's asked....

**Comment by camwebb** [comment]
please... :-)

**Comment by dustymc** [comment]
Tentatively merging into https://github.com/ArctosDB/arctos/issues/7522
