### ISSUE TITLE
Loan date closed funkiness

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#750]
I went to a closed loan, 8183, and entered a remark. Upon hitting save, got the attached error. I browsed back, removed the 00:00:00.0 at the end of the date in the closed on date box, and successfully got it to save. For fun, without changing anything hit save again and got the error again. Did it twice. I don't recall when the date closed field was added, but seems buggy. 
![screen shot 2015-09-04 at 10 07 17 am](https://cloud.githubusercontent.com/assets/5749672/9690255/199f2890-52f0-11e5-9e52-403dcfbfcd02.png)

**Comment by dustymc** [comment]
fixed
