### ISSUE TITLE
gonad

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#7504]
*  2024-03-07 AWG meeting https://docs.google.com/document/d/12NEMEwuQEMgjvdymggJNrp68RNroZdfrRm1tJZaS9Y0/edit
    * unanimous decision to merge on fewer attributes, more use of metadata
* 2024-08-05 AWG meeting https://docs.google.com/document/d/1WvDYixTFZU9ZIFREwF5t605cywxkkQWOW42FfgOV8I8/edit#heading=h.q3pk226foene

----

# Cleanup

-----

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#gonad

gonad needs cleaned up, very few records, easy **if we act before it gets used more**

```
 guid_prefix | count 
-------------+-------
 MLZ:Bird    |     1
 ANSP:Host   |  1625
```

(no contacts available) 

Please note that this has about 1624 more records than it did when we started this, if values The Community does not want to support are in the tables they WILL be used, if we are going to do something let's do it now.

Suggest we move this to reproductive data if we are to remove this term.

----

https://github.com/ArctosDB/arctos/issues/6189

right gonad width (already misconfigured, nonsense data cannot be trusted) needs migration - suggest we move this to reproductive data, including a note about the conflict between the definition and term, if we plan to remove this term.

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#right_gonad_width

```

 guid_prefix | count 
-------------+-------
 UMNH:Mamm   |     1
 BYU:Bird    |   465
 UCSC:Mamm   |     1
 MVZ:Mamm    |    22
 UNR:Mamm    |     1
 MMNH:Bird   |    18
 MMNH:Mamm   |     1
 MVZ:Herp    |    40
 HSUVM:Mamm  |     6
 KSB:Mamm    |     1
 UAM:Mamm    |     1
 UMZM:Bird   |    22
 UMNH:Bird   |     8
 OWU:Bird    |     7
 MLZ:Bird    |     9
 UMZM:Mamm   |    23
 UCM:Bird    |    47
```

 @amgunderson
 @adhornsby
 @mkoo
 @cjconroy
 @atrox10
 @ebraker
 @kderieg322079
 @asemerdj
 @jrpletch
 @byuherpetology

---------

right gonad length [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#right_gonad_length)

```

 guid_prefix | count 
-------------+-------
 UMNH:Mamm   |     2
 BYU:Bird    |   465
 UCSC:Mamm   |     1
 MVZ:Mamm    |    22
 UNR:Mamm    |     1
 MMNH:Bird   |    18
 UTEP:Bird   |     1
 MMNH:Mamm   |     1
 MVZ:Herp    |   177
 HSUVM:Mamm  |     6
 UAM:Mamm    |     1
 UMZM:Bird   |    22
 UMNH:Bird   |     5
 UWBM:Mamm   |    85
 OWU:Bird    |     7
 MLZ:Bird    |     9
 UMZM:Mamm   |    23
 UCM:Bird    |    47

```

 @amgunderson
 @adhornsby
 @mkoo
 @cjconroy
 @atrox10
 @jebrad
 @mvzhuang
 @ebraker
 @kderieg322079
 @asemerdj
 @jrpletch
 @byuherpetology

----

left gonad length [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#left_gonad_length)

```

 guid_prefix | count 
-------------+-------
 UNR:Mamm    |     2
 MMNH:Bird   |    37
 MVZ:Herp    |   153
 HSUVM:Mamm  |     6
 APSU:Bird   |   112
 MLZ:Bird    |   217
 UMZM:Mamm   |    21
 UCM:Bird    |    50
 UMNH:Mamm   |     1
 UCSC:Mamm   |     4
 UTEP:Bird   |     2
 KSB:Mamm    |   308
 UMZM:Bird   |    44
 UMNH:Bird   |    10
 MSB:Mamm    |     2
 UWBM:Mamm   |   111
 OWU:Bird    |     5
 BYU:Bird    |   510
```

 @ebraker
 @byuherpetology
 @mkoo
 @campmlc
 @kderieg322079
 @atrox10
 @mvzhuang
 @asemerdj
 @adhornsby
 @jebrad
 @gradyjt
 @jrpletch
 @AdrienneRaniszewski
 @jldunnum

----

left gonad width [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#left_gonad_width)

```
 guid_prefix | count 
-------------+-------
 UNR:Mamm    |     2
 MMNH:Bird   |    37
 MVZ:Herp    |    62
 HSUVM:Mamm  |     6
 APSU:Bird   |   112
 MLZ:Bird    |   218
 UMZM:Mamm   |    21
 UCM:Bird    |    49
 UMNH:Mamm   |     1
 UCSC:Mamm   |     4
 UTEP:Bird   |     1
 KSB:Mamm    |   303
 UMZM:Bird   |    44
 UMNH:Bird   |     7
 OWU:Bird    |     4
 BYU:Bird    |   510
```

 @ebraker
 @byuherpetology
 @mkoo
 @kderieg322079
 @atrox10
 @mvzhuang
 @asemerdj
 @adhornsby
 @gradyjt
 @jrpletch

----

# Done

----

https://github.com/ArctosDB/arctos/issues/7503

gonad weight - already there, updated definition

---

added 
https://github.com/ArctosDB/code-table-work/issues/63 

New gonad width attribute, needs approved and implemented

------

added

----------

https://github.com/ArctosDB/code-table-work/issues/14 

New gonad length attribute, needs approved and implemented

20240906 still no action

**Comment by Jegelewicz** [comment]
Email to AWG today:

> Arctos Working Group Member,
> 
> In an effort to increase discoverability of data and keep the Arctos Code Tables efficient, changes will soon be made to catalog record attributes related to gonads.
> 
> For a summary of the issues and effort, please see https://github.com/ArctosDB/arctos/issues/7504
> 
> When this process is completed, there will be three gonad attributes:
> 
> [gonad length](https://github.com/ArctosDB/arctos/issues/7502) - Measurement of the long axis of the gonad (which may be testes or ovary and can be indicated in Remarks or by implication of attribute of sex). Left or right side gonad should be indicated in the Methods.
> 
> [gonad width](https://github.com/ArctosDB/arctos/issues/7501) - Measurement of the short axis of the gonad (which may be testes or ovary and can be indicated in Remarks or by implication of attribute of sex). Left or right side gonad should be indicated in the Methods.
> 
> [gonad weight](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#gonad_weight) - Weight measurement of the gonad (which may be testes or ovary and can be indicated in Remarks or by implication of attribute of sex). Left or right side gonad should be indicated in the Methods.
> 
> The following terms will be removed from the catalog record attribute code table and the values currently there will be migrated as detailed.
> 
> [right gonad width](https://github.com/ArctosDB/arctos/issues/6189) - will become gonad width with right placed in the attribute method.
> 
> [right gonad length](https://github.com/ArctosDB/arctos/issues/7506) - will become gonad length with right placed in the attribute method.
> 
> [left gonad width](https://github.com/ArctosDB/arctos/issues/7508) - will become gonad width with left placed in the attribute method.
> 
> [left gonad length](https://github.com/ArctosDB/arctos/issues/7509) - will become gonad length with right placed in the attribute method.
> 
> If you have concerns about your data, please comment on the various issues. Migration to the new terms will take place on April 11, 2024. If you want to handle your data on your own, this allows time for that, or you may request assistance in any of the issues.
> 
> Thank you! 

 

Teresa J. Mayfield-Meyer

**Comment by dustymc** [comment]
I'm adding to AWG agenda; we're 6 months into what seems like it should have been a half-day problem, suggest we convert all involved data to https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#reproductive_data and drop the individual attributes if a better and actionable solution cannot be identified.

**Comment by campmlc** [comment]
These data are being converted out of https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#reproductive_data as part of the grant funded Ranges project. These stakeholders need to be involved.
@jldunnum @bryansmclean @mkoo

**Comment by dustymc** [comment]
>need to be involved

PLEASE! I believe all issues are linked above, proceeding with the initial plan is still perfectly fine with me and I'm happy to do whatever I can to facilitate that. Getting stuck in the middle where nobody can understand the increasingly-scattered data (where we are now) should not be an acceptable position for anyone. HELP!

**Comment by bryansmclean** [comment]
I would love to help sort this out and finalize the consensus decision. 

AWG @ Thursday, September 5, 2024?

**Comment by bryansmclean** [comment]
- This Friday (30 Aug) from 11-1 ET
- anytime next Monday (2 Sept) or Wed (4 Sept)

**Comment by dustymc** [comment]
>consensus

As far as I know that is done and does not need more. The first comment outlines what is needed - the addition of one attribute, and ~5 cleanup issues.

**Comment by bryansmclean** [comment]
> > consensus
> 
> As far as I know that is done and does not need more. The first comment outlines what is needed - the addition of one attribute, and ~5 cleanup issues.

I am not seeing discussion or documentation of a consensus on [other related proposed repro attributes](https://github.com/orgs/ArctosDB/projects/31?pane=issue&itemId=35839323)

I agree that it would be great to finalize but my memory of how we decided to do that is now hazy

**Comment by dustymc** [comment]
>discussion

Link to AWG notes in first comment.

That said: I wholeheartedly agree, we need a mechanism to finish to the things we start on a timeline. The Community has made a decision, there's a clear path to implementation, hanging out for months while the data get worse and more confusing at that point should not happen. I'm always happy to update, just need a little direction and support.

**Comment by dustymc** [comment]
rediscussed 20240905 AWG meeting, I don't know if progress was made or not - @bryansmclean ??

I'm going to consolidate some things here, I can't keep up with the scattered issues, maybe I'm not alone...

**Comment by dustymc** [comment]
This just keeps getting more messy, and has now become disruptive to incoming collections. Can we find some quick conclusion and implement that, please? @bryansmclean @mkoo help!

FWIW all of this still looks a lot like https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#reproductive_data to me, and several collections have cleaned up parts of this in that direction.

**Comment by bryansmclean** [comment]
I think that our consensus was to move left and right gonad lengths and widths to the "gonad length" and "gonad width" fields

The one pre-requisite is to create a controlled vocabulary for methods with all possible positions (left, right, left and right combined, side unknown)

**Comment by dustymc** [comment]
>pre-requisite is to create a controlled vocabulary for methods 

That would be some model other than the one we have, please comment here: https://github.com/ArctosDB/arctos/discussions/6742

**Comment by campmlc** [comment]
We have a consensus on what to do here: follow the March 21 recommendations above. All the ANSP data recently loaded by @Jegelewicz ( and more of the same in the attribute component loader that I have control over) need to be converted to gonad length and gonad width attributes as soon as they become exist,which should be immediately. 
@bryansmclean and others in the issues meeting yesterday discussed a code table for positions, eg left, right, left and right, unknown etc, that could be used for methods for these types of dimensional attributes. There was general support for this. It needs a new issue. As that may take some time to discuss, in the meantime, these positional values should go in methods as free text. 
I recommend making the above changes immediately and getting rid of the gonad attribute.

**Comment by bryansmclean** [comment]
> getting rid of the gonad attribute

I agree with this as well. Any other gonad attributes besides measurements are good for free text in the reproductive data field.

**Comment by dustymc** [comment]
>converted to gonad length and gonad width attributes

If you're volunteering, here are the data:

[temp_gonad.csv.zip](https://github.com/user-attachments/files/16910036/temp_gonad.csv.zip)

**Comment by dustymc** [comment]
>as soon as they exist,

Done, I'm not letting that impede any momentum here.

**Comment by dustymc** [comment]
@campmlc  or anyone else: if you need any other data, please let me know. There are now eg 3 'gonad length' attributes, that should not exist any longer than absolutely necessary. I'll plan to move whatever's left of the things that shouldn't exist to repro data in ~a week.

**Comment by campmlc** [comment]
Gonad length and gonad width should exist, correct? We don't want to get rid of them. We are trying to move all applicable data out of reproductive data as part of this process. 
I will convert all ANSP data including what is pending in the loaders to gonad length and gonad width.

**Comment by jrpletch** [comment]
OWU's should be all fixed

**Comment by campmlc** [comment]
ANSP gonads are deleted; converted gonad length and width attributes loading now

**Comment by campmlc** [comment]
all ANSP should be fixed.

**Comment by dustymc** [comment]
AWG issues meeting - this is all approved and can be migrated, DLM will figure it out and leave any data that changes. Try to get the bulkloader too.

**Comment by dustymc** [comment]
gonad was used one time for https://arctos.database.museum/guid/MLZ:Bird:69262, manually updated

**Comment by dustymc** [comment]
right gonad width

Note that this is defined as "Length measurement of the left gonad." and I'm very hesitant to do anything more precise than what's proposed below from a 3-way mess.

Data:

[temp_rgw.csv.zip](https://github.com/user-attachments/files/17249618/temp_rgw.csv.zip)


Summary:

```

 guid_prefix | count 
-------------+-------
 UMNH:Mamm   |     1
 BYU:Bird    |   465
 UCSC:Mamm   |     1
 MVZ:Mamm    |    22
 UNR:Mamm    |     1
 MMNH:Bird   |    18
 MMNH:Mamm   |     1
 MVZ:Herp    |    40
 HSUVM:Mamm  |     7
 KSB:Mamm    |     1
 UAM:Mamm    |     1
 UMZM:Bird   |    22
 UMNH:Bird   |     8
 MLZ:Bird    |     9
 UMZM:Mamm   |    23
 UCM:Bird    |    47
```

Users:


 @amgunderson
 @adhornsby
 @mkoo
 @cjconroy
 @atrox10
 @ebraker
 @kderieg322079
 @asemerdj
 @byuherpetology



I will plan to move this to reproductive data [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#reproductive_data) with "Formerly right gonad width, which was defined as Length measurement of the left gonad." appended to remark unless someone shows up with a better plan before ~early next week.

**Comment by dustymc** [comment]
right gonad length

Data:

[temp_rgl.csv.zip](https://github.com/user-attachments/files/17249738/temp_rgl.csv.zip)

Summary:

```

 guid_prefix | count 
-------------+-------
 UMNH:Mamm   |     2
 BYU:Bird    |   465
 UCSC:Mamm   |     1
 MVZ:Mamm    |    22
 UNR:Mamm    |     1
 MMNH:Bird   |    18
 UTEP:Bird   |     1
 MMNH:Mamm   |     1
 MVZ:Herp    |   177
 HSUVM:Mamm  |     7
 UAM:Mamm    |     1
 UMZM:Bird   |    22
 UMNH:Bird   |     5
 UWBM:Mamm   |    85
 MLZ:Bird    |     9
 UMZM:Mamm   |    23
 UCM:Bird    |    47
```

contact


 @amgunderson
 @adhornsby
 @mkoo
 @cjconroy
 @atrox10
 @jebrad
 @mvzhuang
 @ebraker
 @kderieg322079
 @asemerdj
 @byuherpetology


I'll update to gonad length [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#gonad_length) and append 'right gonad length' to remarks unless someone shows up with a better plan before ~early next week.

**Comment by dustymc** [comment]
left gonad length

data

[temp_lgl.csv.zip](https://github.com/user-attachments/files/17249764/temp_lgl.csv.zip)

summary

```
 guid_prefix | count 
-------------+-------
 UNR:Mamm    |     2
 MMNH:Bird   |    37
 MVZ:Herp    |   153
 HSUVM:Mamm  |     7
 APSU:Bird   |   112
 MLZ:Bird    |   217
 UMZM:Mamm   |    21
 UCM:Bird    |    50
 UMNH:Mamm   |     1
 UCSC:Mamm   |     4
 UTEP:Bird   |     2
 KSB:Mamm    |   308
 UMZM:Bird   |    44
 UMNH:Bird   |    10
 MSB:Mamm    |     2
 UWBM:Mamm   |   111
 OWU:Bird    |     1
 BYU:Bird    |   510
```

users


 @ebraker
 @byuherpetology
 @mkoo
 @campmlc
 @kderieg322079
 @atrox10
 @mvzhuang
 @asemerdj
 @adhornsby
 @jebrad
 @gradyjt
 @jrpletch
 @AdrienneRaniszewski
 @jldunnum


I'll update to gonad length [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#gonad_length) and append 'left gonad length' to remarks unless someone shows up with a better plan before ~early next week.

**Comment by dustymc** [comment]
left gonad width


data

summary

```

 guid_prefix | count 
-------------+-------
 UNR:Mamm    |     2
 MMNH:Bird   |    37
 MVZ:Herp    |    62
 HSUVM:Mamm  |     7
 APSU:Bird   |   112
 MLZ:Bird    |   218
 UMZM:Mamm   |    21
 UCM:Bird    |    49
 UMNH:Mamm   |     1
 UCSC:Mamm   |     4
 UTEP:Bird   |     1
 KSB:Mamm    |   303
 UMZM:Bird   |    44
 UMNH:Bird   |     7
 BYU:Bird    |   510
```

users


 @ebraker
 @byuherpetology
 @mkoo
 @kderieg322079
 @atrox10
 @mvzhuang
 @asemerdj
 @adhornsby
 @gradyjt

**Comment by adhornsby** [comment]
For all MMNH & UMZM:
Instead of having 'right gonad width' sent to reproductive data, can I have it handled like the other traits -- i.e. updated to 'gonad width' with method 'right gonad width.'  I know we were using that trait at face value, so the old mismatched definition in the table doesn't bother me.

MMNH & UMZM are otherwise good to be updated as planned.

**Comment by dustymc** [comment]
@adhornsby sure and thanks!



@amgunderson
@mkoo
@cjconroy
@atrox10
@ebraker
@kderieg322079
@asemerdj
@byuherpetology

would you like to make any adjustments to https://github.com/ArctosDB/arctos/issues/7504#issuecomment-2392267927?

**Comment by cjconroy** [comment]
Fine with MVZ mammals. I added this info to reproductive data, so there would be something like verbatim data as well.

**Comment by dustymc** [comment]
Final data stash:

[temp_rgw(1).csv.zip](https://github.com/user-attachments/files/17311115/temp_rgw.1.csv.zip)
[temp_rgl(1).csv.zip](https://github.com/user-attachments/files/17311154/temp_rgl.1.csv.zip)
[temp_lgl(1).csv.zip](https://github.com/user-attachments/files/17311182/temp_lgl.1.csv.zip)
[temp_lgw(1).csv.zip](https://github.com/user-attachments/files/17311206/temp_lgw.1.csv.zip)
