### ISSUE TITLE
Missing Arctos login attribute for agents

### ISSUE THREAD

**Issue by adhornsby** [ArctosDB/arctos#7505]
I'm making a new agent and am trying to add his login to his profile, but I don't see it as an option.  It's listed in the name attribute code table but I'm not seeing it in the pick list...
<img width="210" alt="image" src="https://github.com/ArctosDB/arctos/assets/40217539/281e22ef-67bb-4288-88c1-f223068558c9">

**Comment by dustymc** [comment]
https://handbook.arctosdb.org/documentation/users.html

**Comment by adhornsby** [comment]
Got it.  Works, just a different route than I was used to.  Thanks!
