### ISSUE TITLE
Is it bad to duplicate values in multiple attribute fields

### ISSUE THREAD

**Issue by adhornsby** [ArctosDB/arctos#7507]
Broad question -- how bad is it to duplicate the same data in multiple attribute fields? 

E.g. If we have testis measurements L5x3 R4x3, it seems "best" to distribute those into separate attributes (L testis length 5, L testis width 3, etc.).  However, for tasks like reports and providing specimen summaries for users, it's still helpful to have all of these data in attribute repro data so I can just call up one field to catch it all.  I'm drawn to always putting verbatim into repro data and also distributing to separate attributes when possible.

Does this have the potential to cause a lot of confusion/trouble either in managing our own collections or when the data are downloaded/aggregated?

**Comment by jldunnum** [comment]
Hey Angela,
This is similar to what we have requested in terms of distributing reproductive attributes into their new respective fields but also retaining a reproductive info field. Something necessary for RANGES workflows and retaining verbatim data anyways.

______________________________________________________________
Jonathan L. Dunnum Ph.D. (he, him, his)
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
Research Assistant Professor (LAT)
Department of Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

Chair, Systematic Collections Committee, American Society of Mammalogists
Latin American Fellowship Committee, ASM

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________
From: Angela Hornsby ***@***.***>
Sent: Friday, March 8, 2024 8:22 AM
To: ArctosDB/arctos ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ArctosDB/arctos] Is it bad to duplicate values in multiple attribute fields (Issue #7507)


  [EXTERNAL]

Broad question -- how bad is it to duplicate the same data in multiple attribute fields?

E.g. If we have testis measurements L5x3 R4x3, it seems "best" to distribute those into separate attributes (L testis length 5, L testis width 3, etc.). However, for tasks like reports and providing specimen summaries for users, it's still helpful to have all of these data in attribute repro data so I can just call up one field to catch it all. I'm drawn to always putting verbatim into repro data and also distributing to separate attributes when possible.

Does this have the potential to cause a lot of confusion/trouble either in managing our own collections or when the data are downloaded/aggregated?

**Comment by adhornsby** [comment]
Thanks @jldunnum !
