### ISSUE TITLE
migration: left gonad width

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#7508]
left gonad width should be migrated and removed

data

[temp_lgw.csv.zip](https://github.com/ArctosDB/arctos/files/14539898/temp_lgw.csv.zip)

summary

```

 guid_prefix | count 
-------------+-------
 MVZ:Mamm    |     1
 UNR:Mamm    |     2
 MMNH:Bird   |     4
 DMNS:Bird   |     7
 UTEP:Bird   |     1
 UWYMV:Mamm  |     1
 DMNS:Mamm   |     6
 UWBM:Mamm   |   110
 CRCM:Bird   |  5070
 OWU:Bird    |     4
 MVZ:Herp    |    62
 CHAS:Mamm   |     1
 CHAS:Teach  |     9
 APSU:Bird   |   112
 MLZ:Bird    |   218
 UMZM:Mamm   |    14
 UCM:Bird    |    49
 UMNH:Mamm   |     1
 UCSC:Mamm   |     4
 CHAS:Bird   |    39
 KSB:Mamm    |   204
 UMZM:Bird   |    36
 UMNH:Bird   |     6

```

contact

 @ebraker
 @mkoo
 @barke042
 @atrox10
 @mvzhuang
 @cjconroy
 @wellerjes
 @jebrad
 @jrpletch
 @acdoll
 @jrdemboski
 @jessicatir
 @ewommack
 @kderieg322079
 @adhornsby
 @droberts49

**Comment by ewommack** [comment]
UWYMV data is fixed

**Comment by acdoll** [comment]
migrated into what?

**Comment by Jegelewicz** [comment]
> migrated into what?

gonad width with left in method.

**Comment by wellerjes** [comment]
Okay to migrate for CHAS collections.

**Comment by jebrad** [comment]
OK to migrate for UWBM:Mamm

**Comment by jessicatir** [comment]
CRCM:Bird left gonad width/length has been removed - will re-upload myself when the new term is available. The majority of our data were actually "side not specified" so we had to check which ones were legitimately "left."

**Comment by cjconroy** [comment]
MVZ mammals had only one, and I changed it to Right.

**Comment by wellerjes** [comment]
CHAS specimens fixed

**Comment by adhornsby** [comment]
OK to migrate all MMNH and UMZM (or do you want us to do it @dustymc ?)

**Comment by mkoo** [comment]
Please do so for MVZ:Herp. Weirdly I dont see the  MVZ:Mamm record even though it's on your query results...

**Comment by jebrad** [comment]
Yes, please do this for UWBM:Mamms.    Thank you.

**Comment by Jegelewicz** [comment]
For UWBM:Mamm

1. added gonad width attribute to UWBM:Mamm
2. searched for all UWBM:Mamm with left gonad width attribute and used the view attribute tool to download the left gonad width attributes
3. used the downloaded attributes to make an upload of gonad width attributes with "was left gonad width" added to attribute_method
4. loaded new gonad width attributes
5. used the bulk unload attribute tool to remove left gonad width attributes
6. removed left gonad width from UWBM:Mamm

file - 
[UWBM_Mamm gonad width change.xlsx](https://github.com/user-attachments/files/16589385/UWBM_Mamm.gonad.width.change.xlsx)

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/7504
