### ISSUE TITLE
migration: left gonad length

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#7509]
left gonad length should be migrated and removed

data

[temp_lgl.csv.zip](https://github.com/ArctosDB/arctos/files/14540082/temp_lgl.csv.zip)

summary

```


 guid_prefix | count 
-------------+-------
 UNR:Mamm    |     2
 MMNH:Bird   |     4
 DMNS:Bird   |     8
 UTEP:Bird   |     2
 UWYMV:Mamm  |     1
 DMNS:Mamm   |     4
 MSB:Mamm    |     2
 UWBM:Mamm   |   109
 CRCM:Bird   |  5244
 OWU:Bird    |     5
 MVZ:Herp    |   153
 CHAS:Mamm   |     1
 CHAS:Teach  |    10
 APSU:Bird   |   112
 MLZ:Bird    |   217
 UMZM:Mamm   |    14
 UCM:Bird    |    50
 UMNH:Mamm   |     1
 UCSC:Mamm   |     4
 CHAS:Bird   |    44
 KSB:Mamm    |   208
 UMZM:Bird   |    36
 UMNH:Bird   |     9



```

contact

 @ebraker
 @mkoo
 @campmlc
 @barke042
 @atrox10
 @mvzhuang
 @wellerjes
 @jebrad
 @jrpletch
 @AdrienneRaniszewski
 @acdoll
 @jldunnum
 @jrdemboski
 @jessicatir
 @ewommack
 @kderieg322079
 @adhornsby
 @droberts49

**Comment by ewommack** [comment]
UWYMV data is fixed

**Comment by wellerjes** [comment]
CHAS specimens fixed

**Comment by Jegelewicz** [comment]
What were the "fixed" records migrated to? There is no gonad length attribute.

Are we actually migrating everything to "gonad" and putting left/right AND measurement type into method?

**Comment by wellerjes** [comment]
We decided to put everything into the "reproductive data" field in order to have consistency across our collections.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/7504
