### ISSUE TITLE
manipulate globalnames data during fetch

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#7518]
> I'm just writing whatever I get from GN to the DB.
> But is it possible to add a term to the import? If you look at Array 17, WFO for _Erigeron acris_ C.B. Clarke, there is an entry: matchedName --- string --- Erigeron acris C.B.Clarke. This is needed as a non-rank term in the WFO classification for the user to understand the synonymy. Maybe it could be called 'original name string' to accompany the [existing](https://arctos.database.museum/name/Erigeron%20acris#WorldFloraOnline) 'name string', which is 'Erigeron puchellus Michx'. Better yet if the current field title 'name string' is switched to 'current name string'.

_Originally posted by @camwebb in https://github.com/ArctosDB/arctos/issues/6500#issuecomment-1986288480_

**Comment by camwebb** [comment]
@dustymc FYI, we (ALA) are considering an alternative route: requesting our own classification source (ct request for 'UAM Plants') and building a full classification that best fits our needs. It would be based on WFO (just for UAM plant names, and from the main WFO, not via GN), touched up with recent accepted name decisions from the [Flora of Alaska][1] project. It would be scripted so it was easy to rebuild and reinstall every 3-6 months.

This route would avoid you needing to manipulate the GN import.

[1]: https://floraofalaska.org/

**Comment by dustymc** [comment]
@camwebb thanks, I'm going to table this and we can drag it back out if a use case appears.

And let me know if you need any help, whichever way you end up going.
