### ISSUE TITLE
Code Table Request - New classification source: 'UAM Plants'

### ISSUE THREAD

**Issue by camwebb** [ArctosDB/arctos#7520]
**Goal**: To enable a classification Source that could be managed primarily by UAM herbarium (ALA). It would:

 * be based on World Flora Online (just for UAM plant names, and from the main WFO not via GN), 
 * be augmented with recent accepted name decisions from the [Flora of Alaska](https://floraofalaska.org/) project,
 * hold comments and accepted names for obscure names found on UAM Plant labels.

The classification would be scripted so it was easy to rebuild and reinstall every 3-6 months.

By giving the classification hierarchy of the the _accepted_ name for any synonym, as is done in the [WFO GN import](https://arctos.database.museum/name/Alnus%20sinuata#WorldFloraOnline), this classification would permit a taxonomy search on an accepted name to find specimens named to synonyms.  However, unlike the current WFO import, the author string of the synonym would be given in the non-rank term `author_text`, and the author string of the accepted name would be given in `preferred_name`, permitting the user to understand whether the synonym was appropriate or not, based on the author string of the original label.

**Context**: #6500, #7478, #7518

**Table**: `cttaxonomy_source`

**Proposed Value**: 'UAM Plants'

**Proposed Definition**: Plant and fungal taxonomy, intended to reflect current literature, with a focus on Alaska. Managed via batch imports and in the Arctos Taxon Terms editor by UAM staff (see managed_by field for current contact).

**Helpful Actions**

- [x] Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).
- [ ] Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

@ArctosDB/arctos-code-table-administrators 

## Approval
_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection
_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation
_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

- [ ] Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.
- [ ] Add or revise the code table term/definition as described above. Ensure the URL of this Issue is included in the definition. URLs should be included *_as text_*, separated by spaced pipes. Do not include HTML in definitions.

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by Jegelewicz** [comment]
We should add some things to the template for this?

source will be managed by agent(s) - Cam Webb, DLM
source may be updated via - Arctos Classification Bulkloader, Arctos UI, or GlobalName API

**Comment by Jegelewicz** [comment]
added - I don't think anyone would be opposed. @camwebb currently this can be edited with any of the classification editing tools - you may want to change that to Arctos Classification Bulkloader

**Comment by camwebb** [comment]
@Jegelewicz , @dustymc 

Initial example here:  <https://arctos.database.museum/name/Erigeron%20acris#UAMPlants>

**Comment by Jegelewicz** [comment]
Cool - now I want to know if it does what you need!

**Comment by camwebb** [comment]
> now I want to know if it does what you need!

It should, if #7543 can be performed.
