### ISSUE TITLE
Feature Request - allow NULL georeference_protocol with spatial data

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#7522]
**Is your feature request related to a problem? Please describe.**

See https://github.com/ArctosDB/arctos/issues/7499 - seems we're struggling to meet requirements when there's nothing to say

**Describe what you're trying to accomplish** 

Allow nothing when there's no relevant information

**Describe the solution you'd like**

Remove

```
 IF NEW.georeference_protocol IS NULL THEN
            RAISE EXCEPTION '%', 'georeference_protocol is required when spatial data are given.';
end if;
```
from ``trg_locality_biu``

**Describe alternatives you've considered**
 
proceed with https://github.com/ArctosDB/arctos/issues/7499

**Additional context**

@camwebb said please with ASCII art and everything.

**Priority**

?

**Comment by Jegelewicz** [comment]
I think that we should make it a policy to allow saying nothing when there is nothing to say! There should be very few places in Arctos where data is REQUIRED and we should have some good reason for any REQUIRED thing.

**Comment by campmlc** [comment]
I support this.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I agree with this.

**Comment by dustymc** [comment]
## Source

https://github.com/ArctosDB/arctos/issues/7522

## Summary

allow NULL georeference_protocol with spatial data

## User Interface Changes

georeference_protocol will not be required

## Data Structure Changes
