### ISSUE TITLE
split MVZ Mammal taxonomy

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#753]
clone everything used by MVZ:Mamm into a new classification.

**Comment by dustymc** [comment]
done @test, waiting for confirmation from MVZ

**Comment by Jegelewicz** [comment]
Is this still a thing?

**Comment by Jegelewicz** [comment]
One more time - is this still a thing? @mkoo @ccicero

**Comment by cjconroy** [comment]
The goal is that MVZ mammals would be able to use whatever taxonomic classification we'd like, independent of other Arctos collections. For example, we might like to continue using Clethrionomys rather than Myodes. I don't know how best that is implemented, or what "splitting" means.

**Comment by dustymc** [comment]
Suggest we close - whatever I did will be Oracle-centric, if I can find it, and the relationship between collections and classifications is radically different than it was in 2015.

**Comment by Jegelewicz** [comment]
@cjconroy with the new methods for selecting a preferred taxonomy now in place, this might be the time for you to develop a mammal taxonomy for your collection. Others could use it too (and might want too).
