### ISSUE TITLE
Arctos not working when signed out

### ISSUE THREAD

**Issue by DellaCHall** [ArctosDB/arctos#7530]
**Describe the bug**
Arctos times out when trying to do anything when signed out (working fine when signed in). Got this error message: This message has been logged as F68B9D20-DCBB-4ABD-BF4D291E2B013C84. 

**To Reproduce**
1. Sign out
2. Try to do something (even accepting the terms causes it to time out, but somehow I got past that screen, and so did searching for a catalog record)

**Expected behavior**
Normal functioning.

**Priority**
Critical

**Comment by dustymc** [comment]
Confirmed, rebooting NOW

**Comment by ewommack** [comment]
Is the reboot why I'm getting a 503 Service Not available notice?

**Comment by ewommack** [comment]
Must be, it's back up and running
