### ISSUE TITLE
redirects to projects in Arctos not working

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#7541]
**Describe the bug**
We have a bunch of project redirects (old: with title in URL to new: unique id number) which the CA state agency just alerted us are not working. I double checked they are in the redirect list but are giving errors instead of redirecting.... not sure why?!

**To Reproduce**

old_path | new_path
-- | --
https://arctos.database.museum/project/historic-grinnell-survey-lassen-transect | https://arctos.database.museum/project/10000300
https://arctos.database.museum/project/historic-grinnell-survey-yosemite-transect | https://arctos.database.museum/project/10000298
https://arctos.database.museum/project/historic-grinnell-survey-southern-sierra-nevada-transect | https://arctos.database.museum/project/10000301
https://arctos.database.museum/project/grinnell-resurvey-project-lassen-transect | https://arctos.database.museum/project/10000049
https://arctos.database.museum/project/grinnell-resurvey-project-yosemite-transect | https://arctos.database.museum/project/10000047
https://arctos.database.museum/project/grinnell-resurvey-project-southern-sierra-nevada-transect | https://arctos.database.museum/project/10000244

So something's screwy? Try one of the old paths to see the error (lots of lucee fun) I have not tested the other redirects but will next

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/1540 - those data-based links have been deprecated for ~6 years, looks like the function didn't quite survive the transition to postgres. I resurrected it, but I don't think that can be long-term stable - please encourage them to update the links, or consider creating redirects (which would probably conflict with the antique thing I just dug up...).

**Comment by mkoo** [comment]
no way to update links since it's in a pub. But we should be able to have redirects in arctos regardless.
Anyway, thanks for necromancy work.
closing....
