### ISSUE TITLE
Add login to name type in edit_agent.cfm

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#7542]
Probably an oversight (?) but login is not in the dropdown options to add a new attribute to an agent

<img width="274" alt="Screenshot 2024-03-14 at 9 43 56 AM" src="https://github.com/ArctosDB/arctos/assets/2523089/2befd240-929f-43aa-8226-97b82a95bb2d">

thx!

**Comment by dustymc** [comment]
Design, not oversight: https://handbook.arctosdb.org/documentation/users.html#creating-operators

**Comment by Jegelewicz** [comment]
I just updated documentation too.

**Comment by mkoo** [comment]
ok congestion fail! I knew about this method but thought that we would continue with other as well. thanks for updating the docs!
