### ISSUE TITLE
Feature Request - Allow issued by as selection criteria for my preferred identifier

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7545]
**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

In my user profile, I can select a preferred identifier by identifier type.

![image](https://github.com/ArctosDB/arctos/assets/5725767/2868e6fb-c9ce-4401-a85a-0720aec173b1)

but now that most identifiers are disambiguated by the issuer, I'd like to be able to make this selection using issued by, type, or a combination of both.

**Describe what you're trying to accomplish** 
_A clear and concise overview of the goals; why are you asking for this?_

use the data in Arctos to get a more precise bit of information.

**Describe the solution you'd like**
_How might we accomplish your goals?_

I'd like to be able to make this selection using issued by, type, or a combination of both.

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

Using type OR issued by could also work, but provides less precision.

**Additional context**
_Add any other context or screenshots about the feature request here._

Another step to community buy-in of issued by as being the most important addition to an other identifier.

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._

**Comment by dustymc** [comment]
Is there some specific use case? The identifiers that spawned that functionality are all retained 'local types.' 

Bigger picture, I think 'my identifier' has maybe caused more problems than its solved, has serious performance limitations (there's no way to cache the thing that's different for everyone - which probably means we need to constrain the options to cached types), and I think just cannot work when there's any expectations of anything NOT 1:1 (and I don't think "using issued by, type, or a combination of both" can be 1:1).

**Comment by Jegelewicz** [comment]
That is all fair and maybe we should be looking to remove this function? Given what you said, I'll close this.
