### ISSUE TITLE
locality clean-up: remove repetition in spec_locality (migration errors)

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#7546]
There are some spec_localities with repeating terms that happened from our HG migration to a authorities.

@dustymc  Can you please help fix these with a find/replace function? (all original HG is in attributes; reviewed)

- [ ] "Alexander Archipelago, Alexander Archipelago" appears in 134 localities -- replace with "Alexander Archipelago, " (note comma, these come in the middle of the string)
- [ ] "Hastings Natural History Reservation, Hastings Natural History Reservation" in 104 locs -- replace with "Hastings Natural History Reservation" (this occurs at the end of the string so no need to add the comma)

There are probably others but these are coming up in reports now -- thx!

**Comment by dustymc** [comment]
```
UPDATE 134

UPDATE 104
```
