### ISSUE TITLE
Bulkload taxon names does not download csv with errors

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7547]
I have things in the taxon name loader that returned errors:

![image](https://github.com/ArctosDB/arctos/assets/5725767/478138a5-3ef9-408f-ae6f-21778557bd01)

but when I download csv, the errors aren't listed.

![image](https://github.com/ArctosDB/arctos/assets/5725767/fac27423-1d85-4514-a361-485b367746b0)

instead they all just say "load"

This is not consistent with the operation of other component loaders. I expect to see the full error in the status column when I download the data.

**Comment by dustymc** [comment]
Excel doing excel things?

<img width="1043" alt="Screenshot 2024-03-15 at 10 39 27" src="https://github.com/ArctosDB/arctos/assets/5720791/68aaae3b-560e-4ac5-810a-5b7f37789217">

And I think that tool is a lot scarier than you seem to think, should really never be getting errors there, I'll open an issue....

**Comment by Jegelewicz** [comment]
Not Excel, the csv has line breaks?

![image](https://github.com/ArctosDB/arctos/assets/5725767/04c707db-a2b0-44cc-90ea-e691b372ab64)
