### ISSUE TITLE
taxon name bulkloader expectations

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#7548]
And I think that tool is a lot scarier than you seem to think, should really never be getting errors there, I'll open an issue....

_Originally posted by @dustymc in https://github.com/ArctosDB/arctos/issues/7547#issuecomment-2000143699_

The "rules" around taxonomy are basically meant to keep a careful user from doing unintentional things.

That does not seem to be what's happening, and I suspect that's resulting in not-taxonomy being created as taxonomy, and/or various other not-great things.

How can we better do whatever it is that needs done?

<img width="273" alt="Screenshot 2024-03-15 at 10 43 09" src="https://github.com/ArctosDB/arctos/assets/5720791/a84b3e2e-5197-414b-b19a-47d25f5e4c29">

**Comment by Jegelewicz** [comment]
Yeah man, I honestly don't know how those things made it through? Also, they have been there for a long time I think, so I'm not even sure where they are from - I will do some digging.

**Comment by Jegelewicz** [comment]
OK - here is what happened. I used OpenRefine to match a large (3,584) list of names that were not in Arctos to GlobalNames. I bulkloaded those that cleared with a match- not realizing that the "match" isn't necessarily exact (I know that now...).

For more see https://github.com/ArctosDB/data-migration/issues/1883

I won't do this again, but I also do not see someone individually reviewing thousands of names. I usually end up with a couple hundred at most and I handle them all one by one (probably nobody else would do that either....). Anyway, for this particular bunch, there are still 507 that aren't in Arctos. I don't know who is going to check those.

**Comment by Jegelewicz** [comment]
@dustymc what needs doing here?

**Comment by dustymc** [comment]
?? documentation ?? 

Lacking better ideas, I'll plan to add something to the tool itself.

**Comment by dustymc** [comment]
There are two maybe-kinda-problematic creations (I think neither related to the bulkloader) in recent names

``Gradiconus floridanus f. floridensis | cultural | Phyllis Sharp | 2024-05-09 09:26:21.556032``

Clearly not a cultural name, possibly rejected as Linnean by the validation (or just an oops), and



``Spear-thrower | cultural | C. O. Webb | 2024-05-08 13:39:15.542985``

which seems to be maybe-kinda inconsistent - most seem to be all lowercase in N4.0 (https://page.nomenclature.info/parcourir-browse.app?id=8153&lang=en&ws=INT&wo=N) and Proper Case eg Peg-Top Skirt in Arctos (and I'm not sure about the hyphen, used arbitrarily everywhere??)



I'm not seeing any significant problems created by this.

Tool rebuilt with warnings for next release, and some clarifying language added to the checker.
