### ISSUE TITLE
Need Help with Arctos Error: trying to invite a newly created agent as an operator

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#7549]
# Error Text
 error id 23DE7071-6C3A-4229-93A5FCE2D3EBA303
message: ERROR: Only one login is possible. Where: PL/pgSQL function trigger_fct_tr_agent_attribute_biud() line 42 at RAISE

# Where it happened
Probably something we did stumbling along here with new agent workflow. After Chris created this agent, I tried to invite user **khushi_shrivastava** as an operator.

Just found out that her login was added before the new interface so probably as simple as zapping one of the logins? or something? Probably a transition bug? help @dustymc ! 
thx

**Comment by dustymc** [comment]
AHA -I was just trying to figure out where that error came from...

Zapped, hope that's it!

**Comment by mkoo** [comment]
It is! works now and you get a prize for fastest issue closer of the day!
