### ISSUE TITLE
add all locality data to specimenresults

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#755]
even if it's ugly (eg, JSON??) - ugly is better than invisible.

**Comment by ccicero** [comment]
Dusty, can we discuss? Are you ralking about the table view or detail pag Maybe have a View more details link or something like that, rather than mucking up specimen detail /results and making those harder to read?

**Comment by dustymc** [comment]
>can we discuss

YES!! (Flip "milestone" to "Needs Discussion" to flag that - I just did.)

>table view

That's the main (only??) place where data is lacking.

>detail page

That's easy to change and everything "fits" - you can see there whatever ya'll tell me you want to see.

>mucking up specimen results

It would be something people can turn on/off, like everything else (I think??).

>harder to read

I'm just making sure this doesn't fall off my radar for now. I'm thinking perhaps some sort of HTML-popup-link or something in the results/web view and something else (raw JSON??) for download, or SOMETHING of the sort. (That might work for Media too, which is kinda similar and sort of a pain right now.) 

Anyway, yes, please, let's talk whenever it works for you, this isn't very urgent and I have no firm plans at the moment. We eventually, somehow, need to get either the data or some indication that there's more data into the results view.

**Comment by ccicero** [comment]
Ok. Let's discuss when I'm back from the field.  Thanks.

**Comment by dustymc** [comment]
From mini pow-wow with @campmlc @jldunnum @AdrienneRaniszewski

- add all locality data to specimenresults as JSON (that's less-evil than providing no clue why their search and results don't match, or making it impossible to find specimens as now)
- add a "has multiple events" flag in the GUID column, similar to how Media and Citations are handled.
- allow search to match all events

Alternatives discussed:

- treat rows like Occurrences, one row for each "place." GUID becomes non-unique in specimen results and downloads. Seems likely to lead to treating multiple encounters as biological individuals etc.

- Concatenate all event data in individual columns. A critter that gets around a lot might looks like:

|guid|country|state|specloc|...|
|----|--------|-----|--------|---|
|ABC:XYZ:123|Mexico; United States; United States; United States; Canada|Baja California;California;Oregon;Washington;British Columbia|bla; blah; blaugh; blaw; bla, eh|...|

which seems confusing to me.

**Comment by dustymc** [comment]
Added "JSON Locality" option

**Comment by dustymc** [comment]
"any geog" search performance isn't acceptable when all localities are considered - need to build a cache, precompile relevant geography data

**Comment by dustymc** [comment]
any geog cache should be compiled in a couple days - added event-count label to results
