### ISSUE TITLE
Mass Agent Attribute update

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7551]
There are a lot of agents that include a url attribute with "GRSciColl" in the remark. I would like to add the related agent [Global Registry of Scientific Collections](https://arctos.database.museum/agent/21351976) to those attributes and remove "GRSciColl" from the remark. There are too many to do this manually (search results exceed return limit).

**Comment by dustymc** [comment]
If you want to deal with the 10 sorta-outliers...

```

 21253628 | https://www.gbif.org/grscicoll/institution/e46e34a4-32b8-4a0c-89a7-06f14fcde702 | GRSciColl Institution deleted duplicate
 21346772 | https://registry.gbif.org/collection/150bf1ff-3c07-4c71-a9e7-abd7972a6304       | GRSciColll
 21347751 | https://www.gbif.org/grscicoll/institution/9d5bc0b2-93ca-466d-9db4-6354183cd39b | GRSciColl (herbarium)
 10015215 | https://registry.gbif.org/institution/3929c8e5-31b6-4216-9cbf-231a9d995cb4      | GRSciColl Institution
 21334650 | https://registry.gbif.org/institution/af6f7d6e-7cb2-41eb-b8f7-55929866bda5      | GRSciColl Institution converted to a Collection
 21347726 | https://www.gbif.org/grscicoll/institution/7b26dab7-2bb5-4ae7-b619-e6aa79ac28b3 | GRSciColl (herbarium)
 21347737 | https://www.gbif.org/grscicoll/institution/c0e018b0-8912-4280-9560-ea3d5cae3b38 | GRSciColl (herbarium)
 10015337 | https://www.gbif.org/grscicoll/institution/c529f324-701e-45e4-82b7-10587cdb56e8 | GRSciColl (herbarium)
 10015215 | https://registry.gbif.org/collection/b6fd4ad5-b700-444a-9223-cab850f67a30       | GRSciColl Collection
 21334650 | https://registry.gbif.org/collection/5610b8f5-f4ee-48c4-972c-4b37ba620868       | GRSciColl Collection
(10 rows)
```

I'll magic the rest.

**Comment by dustymc** [comment]
Actually nevermind, if I do that I'm going to nuke your values - adding a related agent forces the value because https://github.com/ArctosDB/arctos/issues/7352#issuecomment-1949539901

```
  -- relationships require a related agent
        if v_purpose='relationship' then
            if new.related_agent_id is null then
                raise exception 'Relationship-forming attributes must be accompanied by related agent.';
            end if;
            -- force-overwrite value
            select preferred_agent_name into new.attribute_value from agent where agent_id=new.related_agent_id;
        end if;
```

I think this just isn't actionable as-is, and needs the attention of the @ArctosDB/agents-committee to do anything.

**Comment by Jegelewicz** [comment]
Really? That means related agent is functionally useless for everything except relationships?
I just did this for Bell

https://arctos.database.museum/agent/21253628

**Comment by Jegelewicz** [comment]
And it seems to work just fine....

**Comment by dustymc** [comment]
> seems to work just fine....

Hu?

**Comment by Jegelewicz** [comment]
Go look at it - https://arctos.database.museum/edit_agent.cfm?agent_id=21253628

![image](https://github.com/ArctosDB/arctos/assets/5725767/87d398a4-4660-4265-9f8e-02380f5e3d7d)

**Comment by Jegelewicz** [comment]
Maybe our wires are crossed?

**Comment by mkoo** [comment]
I dont see the problem @dustymc ? pls explain? Im more confused about the GBIF/GrScicoll side of things but I guess we can list them all

**Comment by Jegelewicz** [comment]
GBIF and GRSciColl are two different things....

**Comment by dustymc** [comment]
OK I see it - I'm only forcing the value to the preferred name for relationship types, they can differ for addresses. Let's hope that's what everyone wanted all along and I only temporarily confused myself...

```
UPDATE 324
```

**Comment by Jegelewicz** [comment]
That is definitely what I wanted!
