### ISSUE TITLE
Simple csv to move cryovials

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7553]
I was working with @jrpletch today on some container inventory workflows and he has the need to move all the cryovials in a positioned box to an unpositioned container. We did this by:

1. go to the box that needs to be emptied
2. Click Container Contents(CSV only)
3. get the csv
4. copy the column of barcodes for the cryovials (in this scenario, that is BC2 in the table) and manipulate to add commas
5. Go to Container: Bulk Move and choose CSV Paste mode
6. Put the barcode of the unpositioned box in Parent barcode and paste the list from step 4 in Child barcodes
7. Save

This works, but seems like a lot of steps for something so simple. It is easy to move all of the positioned vials to the same position in a new box using this in the container edit page

![image](https://github.com/ArctosDB/arctos/assets/5725767/9e9904fa-bcd2-41e5-a183-158b2e6d17a3)

It seems like there should be an easy button to move all the positioned vials to an unpositioned container as well. If that seems like a scary proposition, then how about a way to get the comma separated list needed for the bulk move tool without all the in-between Excel we had to do to add commas and remove extra information from Container Contents (CSV only)? Or maybe there is some way I am totally missing!

**Comment by dustymc** [comment]
>scary

Yes! 

>some way I am totally missing!

Maybe the listerizer, but you're using tools that shouldn't survive next week and maybe you'll like their replacements.

https://github.com/ArctosDB/arctos/issues/7464

**Comment by dustymc** [comment]
Tabling; this seems like a cleanup request not needing a tool.
