### ISSUE TITLE
Remove criteria for dup agents: same event dates

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#7554]
since I'm on the topic of agents this hour.... I noticed that there are a lot of crazy duplicate agent warnings based on agents having the same event. In this case (bell museum again), the dup agents all share the same born event date of "1872"
It seems crazy that we are marking agents as possible duplicated because they share the same event dates (whether birth, death or whatever)
https://arctos.database.museum/agent/21253628
![Firefox_Screenshot_2024-03-15T21-19-15 201Z](https://github.com/ArctosDB/arctos/assets/2523089/7527625c-6fb6-4b89-a2e3-1db729516400)

solution: remove this criteria for possible dup agents

**Comment by dustymc** [comment]
https://en.wikipedia.org/wiki/GIGO

I can do WHATEVER, everything in there are just maybe-helpful suggestions, only humans can flag duplicates (or make messes, for that matter!).

Removing it will just about inevitable lead to some duplicate being created.

NOT removing it might lead to even more duplicates, depending on how numb bad suggestions from low-quality data might eventually make the user....

**Comment by mkoo** [comment]
ahh the ol' GIGO, well you dont have the make any sand castles with our GI !

>Removing it will just about inevitable lead to some duplicate being created.
I would argue this is less an issue with dates-- I mean I can share a birthday with a lot of people without worry that others will think we're all clones, right?!

dates are just dates-- please remove (this is only for event dates, not anything else)

**Comment by Jegelewicz** [comment]
> dates are just dates-- please remove (this is only for event dates, not anything else)

Agree, they are more useful when the two agents have at least same or similar names (and are both people - comparing people and organizations not so much).
