### ISSUE TITLE
Converting verbatim agents to agents when the verbatim agents are identification determiners

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7556]
The Bell Museum elected to work on agents AFTER their records were loaded so they used verbatim agent attributes for collectors, preparators and determiners. Getting the collector and preparator agents assigned is fairly straightforward, but the determiners not so much. I'd like to start with a sample to see how this should work.

There are [34 records](https://arctos.database.museum/search.cfm?guid_prefix=JFBM%3AFish%2CJFBM%3AHerp%2CJFBM%3AInv%2CMMNH%3ABird%2CMMNH%3AEdu%2CMMNH%3AMamm&customoidoper=LIST&attribute_type_1=verbatim%20agent&attribute_value_1=Minnesota%20Department%20of%20Natural%20Resources&attribute_method_1=identifier) with identifications that should be determined by Minnesota Department of Natural Resources - https://arctos.database.museum/agent/21301925

@adhornsby would like to add https://arctos.database.museum/agent/21301925 as the determiner for the identifications associated with these records and remove the verbatim agent attribute with Minnesota Department of Natural Resources in the value and identifier in the method.

There may be as many as 355 of these and it is entirely possible that some of these only affect a single record. I am working through the list of verbatim agents to determine which are already in Arctos, which should be added and which should stay verbatim. @dustymc what are your thoughts on the best way for us to get these done?

Also, @adhornsby please confirm all of this so that I know I've interpreted your ask correctly!

**Comment by dustymc** [comment]
For now, probably SQL/specific requests. Bigger batches are going to be MUCH nicer for me but I can pick away at corners too, if I must.

Maybe-eventually, once we see how some stuff's going to play out, tools might be useful. Are people going to continue doing this now that we have no guardrails on agents? Will that result in something else which tools might cover? I don't have much sense of any of that yet, not very anxious to build anything until I do.

Or maybe this is some simple expansion of some existing tool?

(And for this particular example I'd personally just use and stick with remarks - agencies aren't really good at identifying things, and 'someone with some association with some giant agency' doesn't add any value that I can see.)

**Comment by Jegelewicz** [comment]
> There are [34 records](https://arctos.database.museum/search.cfm?guid_prefix=JFBM%3AFish%2CJFBM%3AHerp%2CJFBM%3AInv%2CMMNH%3ABird%2CMMNH%3AEdu%2CMMNH%3AMamm&customoidoper=LIST&attribute_type_1=verbatim%20agent&attribute_value_1=Minnesota%20Department%20of%20Natural%20Resources&attribute_method_1=identifier) with identifications that should be determined by Minnesota Department of Natural Resources - https://arctos.database.museum/agent/21301925

I just manually changed these and it took about 30 minutes.

**Comment by Jegelewicz** [comment]
Also fixed for all Minnesota Pollution Control Agency

**Comment by Jegelewicz** [comment]
And all United States Fish and Wildlife Service
