### ISSUE TITLE
Record type human observation for absence?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#7558]
I have 70 plant records that turned out not to exist for samples in a long-term ecological study of over 3000 samples. I loaded the records first and parts later, only to discover these 70 were actually not collected because the species was not present on the experimental plot during that year's sampling. I'd like to keep these records as observations of absence, and I'm trying to brainstorm how that might work. The sampling methodology is identical across years at these sites for which we have actual samples in the collection -so a trained observer went to to same site for that year's collecting event, applied the same project methodology as linked in the published and linked metadata, but the species was absent for that year so no parts exist. I've changed the event to observation, and recorded "not collected" in the collection method, and added event remarks that the species was absent. I need to change record type from preserved specimen to what - human observation of absence? Any ideas?
It would be great to be able to record an observation of absence in some way for a well documented and consistent project like this- thoughts appreciated.

**Comment by dustymc** [comment]
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_event_type

**Comment by Jegelewicz** [comment]
In the table Dusty suggested add absent or not observed?

**Comment by campmlc** [comment]
Maybe "absence" or "observation of absence"? It wouldn't be accepted at GBIF, but it is still an observation, with modified definition "Event at which an organism or object was surveyed for but not detected, and no physical evidence was observed or collected. Human observations, transect surveys, camera traps, and GPS telemetry data are appropriate here

**Comment by dustymc** [comment]
I'd vote for something like 'not detected' - eg say what happened at the event, not a potential conclusion from that. Even 'observed' might carry unwanted connotations.

I'm never a fan of list-definitions or unnecessary qualifications. 'Organism or situation represented by cataloged item was not detected.'

**Comment by campmlc** [comment]
That works. Do I need to file a separate issue for the vocabulary request?
