### ISSUE TITLE
Need Help with Arctos Error: Invalid container

### ISSUE THREAD

**Issue by falco-rk** [ArctosDB/arctos#7559]
# Error Text
invalid container

# Where it happened
Part: Bulkload

# Steps to get there
Uploaded this data: [bulkloadPartsData_invalidContainer.csv](https://github.com/ArctosDB/arctos/files/14636779/bulkloadPartsData_invalidContainer.csv)

The barcodes exist as cryovials in the universe

![Screenshot 2024-03-18 at 9 24 04 AM](https://github.com/ArctosDB/arctos/assets/49788908/ce5c242e-ae6a-49a2-ad1d-ae03bf4b7f19)

Mia has all the permissions. There are not trailing spaces. Help.

**Comment by dustymc** [comment]
That file isn't for https://arctos.database.museum/loaders/BulkloadPartContainer.cfm so I can't re-create the error. I'm not sure how to diagnose.

**Comment by falco-rk** [comment]
When Mia tried to bulkload parts using this file: (same data as other file but in a different file for reasons)
[_bulkloadParts_L00492_tubes_46-79(home2).csv](https://github.com/ArctosDB/arctos/files/14638213/_bulkloadParts_L00492_tubes_46-79.home2.csv)

and set them to autoload, they do not load and she gets the error "invalid container" in the Parts Bulkloader tool
![Screenshot 2024-03-18 at 11 06 06 AM](https://github.com/ArctosDB/arctos/assets/49788908/d7a3b5a0-4d5e-45ec-b99e-fef641f2927d)

the barcodes are real, have been converted to cryovial, exist in the universe, and there are no trailing or leading spaces.

**Comment by falco-rk** [comment]
Okay, so now i uploaded the same file and it went through. But that doesn't explain why Mia was having an issue.

**Comment by falco-rk** [comment]
She's been able to upload other parts (with barcodes) since, so maybe it was something weird with the datasheet? Either way, it seems to have resolved itself

**Comment by dustymc** [comment]
>weird with the datasheet

That's common enough to be my default assumption.

Your data look fine in my normal text editor, but in finder I see...

<img width="266" alt="Screenshot 2024-03-18 at 12 47 11" src="https://github.com/ArctosDB/arctos/assets/5720791/61afdfd7-a184-450a-ac7a-3b852cc7ce81">

so possibly https://handbook.arctosdb.org/documentation/encoding.html
