### ISSUE TITLE
prefer taxon name

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#756]
For taxonomy pick, prioritize (or something...) names for which the collection picking the name has a preferred classification. 

(And for the bulkloader which has no picks???)

Step One: Do we have the processors to hit classification data with taxa pick?

Step Something: Also consider relationships, but see #735

**Comment by dustymc** [comment]
We DO seem to have the processing capacity to consider classifications and relationships, so...

1) What should a taxa pick search match? Could be namestrings, namestrings + relationships, namestrings for which there's a preferred classification, etc. Instead of limiting search we could also flag things eg,
* someterm (in your preferred classifications)
* someotherterm (not in your preferred classifications)

or whatever.

2) What exactly should the results look like - just namestrings, also classifications or related terms (if so just terms or terms+relationships or ??)?

**Comment by dustymc** [comment]
By request, an expansion:

Goal: Given the existence of synonyms/alternate spellings (see #757), how can a collection consistently use one or the other instead of just randomly accepting whatever catches someone's eye first?

1) IF there's universal agreement on how we say "use this instead of that" (see #735), then we might use relationships to find a "preferred" alternate. If taxonomy relationships include

* Rana (is accepted synonym of) Lithobates

then the pick might look like

* Rana
   * (Lithobates)
   * (various other nonpreferred ways of saying frog)

2) If there is not a universal "current" taxa preference (and I think this is the case - see Rana vs. Lithobates vs. Rana (Lithobates) usage), then perhaps a collection can indicate preference by having classifications only for the things they wish to use, leading to a picklist similar to the above.

I don't believe either of those are true consistently enough to write code to. Mammal collections which prefer Myodes and those which prefer Clethrionomys share classifications. The Myodes-users may still want to curate Clethrionomys classification data. So I have no idea how to get at "preferred by collection." What in the data could be used to say "use Nematoda, not Nemata, for current IDs in CollectionX"?

This will have to be a display solution - if we limit searches then CollectionX will not be able to add "Nemata" to eg, type material or as a collector's original ID. I'll edit above accordingly.

**Comment by Jegelewicz** [comment]
Closing for consolidation with #1851
