### ISSUE TITLE
[external CONTACT] issue cloning locality

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#7562]
I'm trying to create new localities by cloning an existing locality. I've tried twice and when I hit the save button I get this (and it doesn't save):

![image](https://github.com/ArctosDB/arctos/assets/967275/d7efcdef-85e8-4e8a-a9d8-915767f1f595)

**Comment by dustymc** [comment]
Bad timing? I think you're trying to clone something as it's being merged. A link/more info might help.

**Comment by ccicero** [comment]
@dustymc does the merge also happen with collecting events? If two identical localities also have the same event, do both the localities and events get merged?  Trying to understand how the merger works.

**Comment by dustymc** [comment]
Yes events also merge (and everything feeds off of everything else and it gets pretty complicated....).

**Comment by ccicero** [comment]
OK, thanks. And how often does the merger run?

**Comment by ccicero** [comment]
Thanks. I'll just try uploading as is, normally I pre-create the localities/events when there are series.
