### ISSUE TITLE
[external CONTACT] bulkloading error: life stage not valid

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#7563]
@dustymc I added 'life stage' to my bulkloader file for MVZ:Bird and am getting an error "attribute_2 fail: type not valid for this collection"

Here is the file.
[Accn15683_bulkloader_forArctos.xlsx](https://github.com/ArctosDB/arctos/files/14641049/Accn15683_bulkloader_forArctos.xlsx)

**Comment by dustymc** [comment]
Somehow missed that at setup, you need to add your collection.

<img width="177" alt="Screenshot 2024-03-18 at 12 44 25" src="https://github.com/ArctosDB/arctos/assets/5720791/7da7ade0-e58a-4f16-995a-3a7739e775b6">

<img width="539" alt="Screenshot 2024-03-18 at 12 44 40" src="https://github.com/ArctosDB/arctos/assets/5720791/de6fd75d-d476-4d13-b506-d4d229cc9412">


 or 


<img width="227" alt="Screenshot 2024-03-18 at 12 42 45" src="https://github.com/ArctosDB/arctos/assets/5720791/a1db3442-fde4-412e-981c-7969f521cb56">


<img width="115" alt="Screenshot 2024-03-18 at 12 43 06" src="https://github.com/ArctosDB/arctos/assets/5720791/3810a5fd-97d5-482e-8cd7-04dc71a9d8b7">


<img width="175" alt="Screenshot 2024-03-18 at 12 43 12" src="https://github.com/ArctosDB/arctos/assets/5720791/37bfea90-42b4-4bc1-b79a-fe79ee8c7685">


I added adult, you probably want more.

**Comment by ccicero** [comment]
got it, thanks!
