### ISSUE TITLE
Code Table Request - Add Not Detected to Specimen Event Type

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#7564]
## Initial Request
Add "Not Detected to specimen event type code table (which needs renaming as record event type)

### Goal
To allow species absence to be recorded as an event. 

### Context
Museum collections are now being used not only as repositories of physical objects but also as databases of species occurrences in space and time for research purposes. One of the new roles we have taken on is to accession ecological samples taken from fixed plots over time using standardized methodology for long term research. In some years, a particular target species for sampling was not present on the plot. I would like to be able to catalog these types of observations so that we have all data points accounted for in the study, but with the caveat that this particular sample/observation could not be taken because the species was not detected during the plot survey.  Having "Not Detected" as an option would be a means of recording negative data or absence data when an effort has been made to detect something. These types of data are rare but particularly important for evaluating change in species distribution over time. 

### Table
(https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_event_type)

### Proposed Value
not detected

### Proposed Definition
~~Organism or situation represented by cataloged item was not detected during the specified event.~~

Organism or object represented by identification(s) associated with the catalog record were not detected during the event.

### Priority
Normal, although I'd like to finish the 70 related records for this project sooner rather than later.

### Example Data
https://arctos.database.museum/guid/MSB:DGR:1531

### Available for Public View
yes

@ArctosDB/arctos-code-table-administrators 

## Approval
_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection
_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation
_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

- [x] Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

- [x] Add or revise the code table term/definition as described above. Ensure the URL of this Issue is included in the definition. URLs should be included *_as text_*, separated by spaced pipes. Do not include HTML in definitions.

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by Jegelewicz** [comment]
> Organism or situation represented by cataloged item was not detected during the specified event.

How about

Organism or object represented by identification(s) associated with the catalog record were not detected during the event.

**Comment by campmlc** [comment]
That works for me.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
This seems like a good idea. How would something like this show up in search? Is there a possibility, if someone isn't paying attention to event type, that it could be mistaken for a positive observation instead of an absence?

**Comment by dustymc** [comment]
>How would something like this show up in search?

It's just another value.

<img width="391" alt="Screenshot 2024-03-26 at 11 37 43" src="https://github.com/ArctosDB/arctos/assets/5720791/f6fbaa43-d783-423e-a07e-ba98bd41cb4e">

<img width="523" alt="Screenshot 2024-03-26 at 11 38 36" src="https://github.com/ArctosDB/arctos/assets/5720791/6039e983-a892-416d-b27c-34ccc3b98070">

> if someone isn't paying attention

Sure - but the same is true for about a bajillion other things, I don't think we need to cater to the most oblivious theoretical user.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Ok - box checked.

**Comment by Jegelewicz** [comment]
added
