### ISSUE TITLE
Feature Request - Update to DarwinCore Archive Mapping: eventDate

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7566]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

This request is the result of a two hour [workshop to review DarwinCore Mapping](https://docs.google.com/document/d/1oRGXMAkbgob6_MqDnfVym15mXhdCMVp4Q7eQnqxsvwM/edit#heading=h.d9m5eti57us9)

**Describe what you're trying to accomplish** 
_A clear and concise overview of the goals; why are you asking for this?_

Provide the best possible data to aggregators via the VertNet IPT

**Describe the solution you'd like**
_How might we accomplish your goals?_

eventDate is currently mapped as

```
CASE WHEN encumbrances LIKE '%mask year collected%'
    THEN replace(collecting_event.began_date,substr(collecting_event.began_date,1,4),'8888')
  ELSE 
    case when
      collecting_event.BEGAN_DATE=collecting_event.ENDED_DATE 
      then collecting_event.BEGAN_DATE
    else
      collecting_event.BEGAN_DATE || '/' || collecting_event.ENDED_DATE
    end 
  END
```
Instead of 8888 use NULL and add "Date withheld" to informationWithheld.

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**
_Add any other context or screenshots about the feature request here._

eventDate - The date-time or interval during which an Event occurred. For occurrences, this is the date-time when the event was recorded. Not suitable for a time in a geological context. See also https://dwc.tdwg.org/terms/#dwc:eventDate
Examples: 1963-03-08T14:07-0600 (8 Mar 1963 at 2:07pm in the time zone six hours earlier than UTC). 2009-02-20T08:40Z (20 February 2009 8:40am UTC). 2018-08-29T15:19 (3:19pm local time on 29 August 2018). 1809-02-12 (some time during 12 February 1809). 1906-06 (some time in June 1906). 1971 (some time in the year 1971). 2007-03-01T13:00:00Z/2008-05-11T15:30:00Z (some time during the interval between 1 March 2007 1pm UTC and 11 May 2008 3:30pm UTC). 1900/1909 (some time during the interval between the beginning of the year 1900 and the end of the year 1909). 2007-11-13/15 (some time in the interval between 13 November 2007 and 15 November 2007).
Qualnamehttp://rs.tdwg.org/dwc/terms/eventDate Namespacehttp://rs.tdwg.org/dwc/terms/
Group Event
Data Type
Required false

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._

**Comment by dustymc** [comment]
Mapping requests should be directed to https://github.com/ArctosDB/arctos/issues/7348.
