### ISSUE TITLE
Feature Request - Update to DarwinCore Archive Mapping: samplingProtocol

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7567]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

This request is the result of a two hour [workshop to review DarwinCore Mapping](https://docs.google.com/document/d/1oRGXMAkbgob6_MqDnfVym15mXhdCMVp4Q7eQnqxsvwM/edit#heading=h.d9m5eti57us9)

**Describe what you're trying to accomplish** 
_A clear and concise overview of the goals; why are you asking for this?_

Provide the best possible data to aggregators via the VertNet IPT

**Describe the solution you'd like**
_How might we accomplish your goals?_

samplingProtocol is currently mapped as

```
specimen_event.COLLECTING_METHOD
```

Add to this the information in event attribute value from [event method](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_event_attr_type#event_method).

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**
_Add any other context or screenshots about the feature request here._

sampligProtocol - The names of, references to, or descriptions of the methods or protocols used during an Event. See also https://dwc.tdwg.org/terms/#dwc:samplingProtocol
Examples: UV light trap, mist net, bottom trawl, ad hoc observation | point count, Penguins from space: faecal stains reveal the location of emperor penguin colonies, https://doi.org/10.1111/j.1466-8238.2009.00467.x, Takats et al. 2001. Guidelines for Nocturnal Owl Monitoring in North America. Beaverhill Bird Observatory and Bird Studies Canada, Edmonton, Alberta. 32 pp., http://www.bsc-eoc.org/download/Owl.pdf
Qualnamehttp://rs.tdwg.org/dwc/terms/samplingProtocol Namespacehttp://rs.tdwg.org/dwc/terms/
Group Event Data
Type
Requiredfalse

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._

**Comment by dustymc** [comment]
Mapping requests should be directed to https://github.com/ArctosDB/arctos/issues/7348.
