### ISSUE TITLE
Feature Request - Update to DarwinCore Archive Mapping: startDayOfYear

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7568]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

This request is the result of a two hour [workshop to review DarwinCore Mapping](https://docs.google.com/document/d/1oRGXMAkbgob6_MqDnfVym15mXhdCMVp4Q7eQnqxsvwM/edit#heading=h.d9m5eti57us9)

**Describe what you're trying to accomplish** 
_A clear and concise overview of the goals; why are you asking for this?_

Provide the best possible data to aggregators via the VertNet IPT

**Describe the solution you'd like**
_How might we accomplish your goals?_

startDayOfYear is currently not mapped, but the workshop participants thought it should be.

endDayOfYear seems to have the right mapping?

```
case when collecting_event.BEGAN_DATE=collecting_event.ENDED_DATE 
    then case when isdate(collecting_event.BEGAN_DATE)=1
      then to_char(to_date(collecting_event.began_date,'YYYY-MM-DD'),'DDD')::int
    end
  end
```

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**
_Add any other context or screenshots about the feature request here._

endDayOfYear - The earliest integer day of the year on which the Event occurred (1 for January 1, 365 for December 31, except in a leap year, in which case it is 366). See also https://dwc.tdwg.org/terms/#dwc:startDayOfYear
Examples: 1 (1 January). 366 (31 December), 365 (30 December in a leap year, 31 December in a non-leap year).
Qualnamehttp://rs.tdwg.org/dwc/terms/startDayOfYear Namespacehttp://rs.tdwg.org/dwc/terms/
Group Event Data
Type integer
Requiredfalse

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._

**Comment by dustymc** [comment]
Mapping requests should be directed to https://github.com/ArctosDB/arctos/issues/7348.
