### ISSUE TITLE
Feature Request - Update to DarwinCore Archive Mapping: year

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7569]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

This request is the result of a two hour [workshop to review DarwinCore Mapping](https://docs.google.com/document/d/1oRGXMAkbgob6_MqDnfVym15mXhdCMVp4Q7eQnqxsvwM/edit#heading=h.d9m5eti57us9)

**Describe what you're trying to accomplish** 
_A clear and concise overview of the goals; why are you asking for this?_

Provide the best possible data to aggregators via the VertNet IPT

**Describe the solution you'd like**
_How might we accomplish your goals?_

year is currently mapped as

```
CASE WHEN encumbrances LIKE '%mask year collected%'
    THEN '8888' -- deal with it....
  ELSE 
    case when collecting_event.BEGAN_DATE=collecting_event.ENDED_DATE 
      then substr( collecting_event.BEGAN_DATE, 1, 4 )
    end 
  END
```
Instead of 8888 use NULL.

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**
_Add any other context or screenshots about the feature request here._

year - The four-digit year in which the Event occurred, according to the Common Era Calendar. See also https://dwc.tdwg.org/terms/#dwc:year
Examples: 1160, 2008
Qualname http://rs.tdwg.org/dwc/terms/year Namespacehttp://rs.tdwg.org/dwc/terms/
Group Event Data
Type integer
Required false

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._

**Comment by dustymc** [comment]
Mapping requests should be directed to https://github.com/ArctosDB/arctos/issues/7348.
