### ISSUE TITLE
Feature Request - Update to DarwinCore Archive Mapping: group

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7572]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

This request is the result of a two hour [workshop to review DarwinCore Mapping](https://docs.google.com/document/d/1oRGXMAkbgob6_MqDnfVym15mXhdCMVp4Q7eQnqxsvwM/edit#heading=h.d9m5eti57us9)

**Describe what you're trying to accomplish** 
_A clear and concise overview of the goals; why are you asking for this?_

Provide the best possible data to aggregators via the VertNet IPT

**Describe the solution you'd like**
_How might we accomplish your goals?_

group is currently mapped as

```
getGeologyForDWC(locality.locality_id,'group')
```

However, groups are not showing up at GBIF so something is not working? Add from locality attributes, comma separated if multiple.

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**
_Add any other context or screenshots about the feature request here._

group - The full name of the highest possible geological biostratigraphic zone of the stratigraphic horizon from which the cataloged item was collected. See also https://dwc.tdwg.org/terms/#dwc:highestBiostratigraphicZone
Examples: Blancan
Qualname http://rs.tdwg.org/dwc/terms/highestBiostratigraphicZone Namespacehttp://rs.tdwg.org/dwc/terms/
Group GeologicalContext
Data Type
Required false

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._

**Comment by dustymc** [comment]
Mapping requests should be directed to https://github.com/ArctosDB/arctos/issues/7348.
