### ISSUE TITLE
Feature Request - Update to DarwinCore Archive Mapping: earliestEpochOrLowestSeries and latestEpochOrHighestSeries

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7577]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

This request is the result of a two hour [workshop to review DarwinCore Mapping](https://docs.google.com/document/d/1oRGXMAkbgob6_MqDnfVym15mXhdCMVp4Q7eQnqxsvwM/edit#heading=h.d9m5eti57us9)

**Describe what you're trying to accomplish** 
_A clear and concise overview of the goals; why are you asking for this?_

Provide the best possible data to aggregators via the VertNet IPT

**Describe the solution you'd like**
_How might we accomplish your goals?_

earliestEpochOrLowestSeries is currently mapped as

```
getGeologyForDWC(locality.locality_id,'Series/Epoch')
```

latestEpochOrHighestSeries is NOT currently mapped, but the consensus is to provide the same data as earliestEpochOrLowestSeries. A concatenated, comma separated list of the values. The hope is that this could eventually consider the chronostratigraphic hierarchy.

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**
_Add any other context or screenshots about the feature request here._

earliestEpochOrLowestSeries - The full name of the earliest possible geochronologic epoch or lowest chronostratigraphic series attributable to the stratigraphic horizon from which the cataloged item was collected. See also https://dwc.tdwg.org/terms/#dwc:earliestEpochOrLowestSeries
Examples: Holocene, Pleistocene, Ibexian Series
Qualnamehttp://rs.tdwg.org/dwc/terms/earliestEpochOrLowestSeries Namespacehttp://rs.tdwg.org/dwc/terms/
Group GeologicalContext
Data Type
Required false

latestEpochOrHighestSeries - The full name of the latest possible geochronologic epoch or highest chronostratigraphic series attributable to the stratigraphic horizon from which the cataloged item was collected. See also https://dwc.tdwg.org/terms/#dwc:latestEpochOrHighestSeries
Examples: Holocene, Pleistocene, Ibexian Series
Qualnamehttp://rs.tdwg.org/dwc/terms/latestEpochOrHighestSeries Namespacehttp://rs.tdwg.org/dwc/terms/
Group GeologicalContext
Data Type
Required false

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._

**Comment by dustymc** [comment]
Mapping requests should be directed to https://github.com/ArctosDB/arctos/issues/7348.
