### ISSUE TITLE
Feature Request - Update to DarwinCore Archive Mapping: verbatimIdentification

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7581]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

This request is the result of a two hour [workshop to review DarwinCore Mapping](https://docs.google.com/document/d/1oRGXMAkbgob6_MqDnfVym15mXhdCMVp4Q7eQnqxsvwM/edit#heading=h.d9m5eti57us9)

**Describe what you're trying to accomplish** 
_A clear and concise overview of the goals; why are you asking for this?_

Provide the best possible data to aggregators via the VertNet IPT

**Describe the solution you'd like**
_How might we accomplish your goals?_

verbatimIdentification is currently NOT mapped

We now have an identification attribute = verbatim identification - should we send it?

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**
_Add any other context or screenshots about the feature request here._

verbatimIdentification - A string representing the taxonomic identification as it appeared in the original record. See also https://dwc.tdwg.org/terms/#dwc:verbatimIdentification
Examples: Peromyscus sp., Ministrymon sp. nov. 1, Anser anser X Branta canadensis, Pachyporidae?
Qualnamehttp://rs.tdwg.org/dwc/terms/verbatimIdentification Namespacehttp://rs.tdwg.org/dwc/terms/
Group Identification
Data Type
Required false

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._

**Comment by dustymc** [comment]
Mapping requests should be directed to https://github.com/ArctosDB/arctos/issues/7348.
