### ISSUE TITLE
Feature Request - remove v1 API

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#7582]
**Is your feature request related to a problem? Please describe.**

v1 has been deprecated for a couple years now, I don't think has any legitimate use, and I don't have the resources to keep it secure.

**Describe what you're trying to accomplish** 

sustainability

**Describe the solution you'd like**

remove v1 API with next release

**Describe alternatives you've considered**

let me know if you're using v1 for something and we'll find a solution that works for everyone

**Comment by mkoo** [comment]
That is the best solution overall
