### ISSUE TITLE
Curatorial Search Request - bird summary

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#7583]
**Describe what you are trying to accomplish**

Is there a way to search for 90 bird families and summarize results by scientific name and count for collection UCM:Bird where part = skin, study?
[bird_families.csv](https://github.com/ArctosDB/arctos/files/14657646/bird_families.csv)

We are moving a section of the collection into new cabinetry and installing specimens in updated taxonomic order. This list will help us do that more efficiently.

**List the fields that you would like to see in your results table**

family | scientific name | count

**Comment by dustymc** [comment]
[temp_bs.csv.zip](https://github.com/ArctosDB/arctos/files/14661243/temp_bs.csv.zip)

**Comment by ebraker** [comment]
Thank you!
