### ISSUE TITLE
Need Help with Arctos Error - DOI creation for Record Set

### ISSUE THREAD

**Issue by bryansmclean** [ArctosDB/arctos#7584]
# Error Text - image attached
<img width="1440" alt="image" src="https://github.com/ArctosDB/arctos/assets/8601578/87f4523e-af4b-4e98-a796-402b09b74204">

# Where it happened
**Provide a link to or a description of the page where the error occurred.**

# Steps to get there - these are the parameters used:
<img width="767" alt="image" src="https://github.com/ArctosDB/arctos/assets/8601578/88882b05-df36-48ee-8eb5-e20fa3ba3d41">

# Problem
**Community response to describe the problem that caused the error**

# Solution
**Community response with directions for how to correct the problem**

**Comment by dustymc** [comment]
@mkoo help - apparently this is using your credentials.

```
arctosprod@arctos>>  select ezid_username from cf_global_settings;
 ezid_username 
---------------
 mkoo
```

you can just update global settings, please.

**Comment by bryansmclean** [comment]
Any updates on navigating this error?

**Comment by mkoo** [comment]
We set this up so long ago, I am contacting CDL and EZID directly to track down the issue-- sorry for the hassle and delay (was out of town and missed this issue)

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/internal/issues/325
