### ISSUE TITLE
Curatorial Search Request: Search "Condition"

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#7585]
I'm trying to search the field "Condition" since we haven't yet moved all of our condition report data into the part attribute condition report. I can't find any normal ways to search the field condition.

For NAGPRA reporting, I need to be able to search for various pesticide treatments on cultural collections. My search needs to be something like:

Search UAM:EH
Condition contains "arsenic" or "mercury" or "chloroform" etc. in order to determine if any of the cultural items might have residual pesticides.

<img width="465" alt="Screenshot 2024-03-20 at 5 51 32 AM" src="https://github.com/ArctosDB/arctos/assets/17605945/f8a6ecf4-df0d-4536-8790-d5ccf1e730f5">

**List the fields that you would like to see in your results table**

GUID
Media
Identified as
Condition
Last Part Location

**Comment by Jegelewicz** [comment]
You need to add it to your search parameters in customize search.

![image](https://github.com/ArctosDB/arctos/assets/5725767/ac07ede5-937f-4197-8b20-f54558a8c7b8)

**Comment by Jegelewicz** [comment]
As for results, that isn't included as a separate column, but you can see it in JSON Parts.

**Comment by AJLinn** [comment]
thanks! I missed that before. I tried to add that but it didn't show up in my search layout. Looks good now.

**Comment by AJLinn** [comment]
<img width="1460" alt="Screenshot 2024-03-20 at 8 59 05 AM" src="https://github.com/ArctosDB/arctos/assets/17605945/f49da0d3-6c67-4d8d-be8f-7fa7ee67dbe8">

Try again...

**Comment by Jegelewicz** [comment]
@AJLinn what were your search parameters?

**Comment by AJLinn** [comment]
I searched UAM:EH as the collection and "cloroform" in the Condition field.

**Comment by Jegelewicz** [comment]
@dustymc it seems like including condition in search is the cause of the error?
