### ISSUE TITLE
Feature Request - add 'status' column to all bulkloader templates

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#7586]
My perception is that some bulkloader templates have a status column and some don't but all would benefit from having one.

For example: https://arctos.database.museum/loaders/move_container.cfm?action=ld

the template that one can download lacks a status column so users would have to type this to make the column... if a status column can be used in a bulkloader template then it would be good if it was in the template.

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._
normal

**Comment by dustymc** [comment]
The only "problem" with this is that it makes a powerful/scary option (load - or delete in some tools - without any further review) a bit more accessible. Unless I hear something else very soon, I'll assume this request outweighs any such considerations and create a next-version template which includes status.

**Comment by Jegelewicz** [comment]
But also, I could swear that somewhere there was an issue about requiring review of things in the component loaders before they get loaded. Maybe that was just my imagination?

I hope that everyone is aware of the potential for mess-making using these things and willing to accept the potential outcome of a student autoloading without any review.

**Comment by DerekSikes** [comment]
This is marked as completed but I keep encountering csv templates that lack a status column; for example: https://arctos.database.museum/loaders/bulkUnLoadDataLoanItem.cfm

**Comment by dustymc** [comment]
Same as https://github.com/ArctosDB/arctos/issues/7445#issuecomment-1961806561 - I've updated the template, I don't have the resources to update all of the tools every time the environment changes. (Not while also doing anything else, anyway.)
