### ISSUE TITLE
inappropriate container types in positions

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#7587]
I just patched a bug, a few mismatched ``container_type`` and ``positions_hold_container_type`` exist and should be fixed.

Data:

[temp_lost_position_contents.csv.zip](https://github.com/ArctosDB/arctos/files/14673281/temp_lost_position_contents.csv.zip)

Summary:

```
 institution_acronym | positions_hold_container_type | container_type | c  
---------------------+-------------------------------+----------------+----
 DMNS                | cryovial                      | room           |  2
 MSB                 | cryovial                      | cryovial label | 19
 MSB                 | cryovial                      | envelope       |  2
 MSB                 | cryovial                      | vial           |  3
 MVZ                 | cryovial                      | bag            |  2
 OGL                 | microwell                     | cryovial       | 71
 UAM                 | cryovial                      | vial           |  1
```

@megulbranson @campmlc @falco-rk @acdoll  @ccicero @mkoo 

Let me know if I can help in any way.

**Comment by Jegelewicz** [comment]
@dustymc you can change the OGL cryovials to microwells.

**Comment by Jegelewicz** [comment]
Actually - I meant to say, can you please change them?!

**Comment by dustymc** [comment]
>UPDATE 71

**Comment by acdoll** [comment]
Not sure how I did that, but the DMNS ones are fixed now.

**Comment by falco-rk** [comment]
Thanks, Dusty!

**Comment by Jegelewicz** [comment]
I fixed the MSB (DGR) containers.

cryovial label -> cryovial
vial -> cryovial with remark that container type was vial
envelope -> cryovial with remark that container type was envelope

In the process I discovered that I can change one of the cryovials in a box that should only hold cryovials to a freezer box and it saves like nothing is wrong, so the individual edit form is allowing this to happen and is possibly how some of these came to be?

**Comment by dustymc** [comment]
>allowing this to happen

Thanks, also plugged.

**Comment by campmlc** [comment]
Can we get a list of all parts that are scanned into cryovial labels, please?

**Comment by megulbranson** [comment]
Changed UAM vial to cryovial.

**Comment by dustymc** [comment]
```

;
 container_id | institution_acronym | positions_hold_container_type | container_type 
--------------+---------------------+-------------------------------+----------------
     12045335 | MVZ                 | cryovial                      | bag
     12045336 | MVZ                 | cryovial                      | bag
(2 rows)


```

@mkoo please fix and close!

https://arctos.database.museum/findContainer.cfm?container_id=12045335
https://arctos.database.museum/findContainer.cfm?container_id=12045336

**Comment by dustymc** [comment]
updated 2 mvz containers

**Comment by mkoo** [comment]
thanks!
