### ISSUE TITLE
Add "url" to the catalog record search panel to accommodate Arctos "record identifiers"

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#7589]
**Is your feature request related to a problem? Please describe.**
Now that we have converted all Arctos guids to url "identifiers", there isn't a clearly defined way to search on the urls in the Search Tool and other tools in Arctos. It's not clear what our "catalog numbers" actually are - numbers? DwC Triplets? or the full url? and how do we explain the differences and how to search and cite to users? It is currently possible to use "any identifier" in Search, but that is not explicitly a url, and not explicitly the official Arctos catalog number of a collection.

**Describe what you're trying to accomplish** 
Make sure the search page clearly provides the ability to search on a the catalog number of any Arctos record in the various ways that it may currently displayed or recorded, including the full https://arctos.database.museum/guid/% url.

**Describe the solution you'd like**
1) Decide what we are going to call the full catalog number url.
2) Add a search field explicitly for the full Arctos guid as url.
3) use the same consistent term for this across all tools, including data entry/pull functions. 

**Describe alternatives you've considered**
Continue confusing ourselves and external users as to what exactly a catalog number is in Arctos.

**Additional context**
I'd like to be able to request or at least allow for the possibility that all our records are cited by the full url, but that means we need to explicitly identify the Arctos guid url format, give it a name to reference it as a unique identifier type referencing the catalog number, not just 'identifier" as it is now.

**Priority**
Moderately high. I've been bumping into this frequently in various tools and contexts, and it continually causes confusion.

**Comment by dustymc** [comment]
>converted all Arctos guids to url "identifiers",

I don't know what this means, but I think there's some confusion in it. Nothing about Arctos GUIDs has changed in a long time.

>not clear what our "catalog numbers" actually are 


<img width="739" alt="Screenshot 2024-03-21 at 05 52 36" src="https://github.com/ArctosDB/arctos/assets/5720791/2194e8f5-21e6-4017-85ed-ad9da09ffc8e">



>how do we explain the differences and how to search and cite to users?

I would consider partial or local identifiers of all forms (including catalog numbers) to be entirely internal, and not for a user who doesn't already know exactly what they're doing. There's no other way to unambiguously reference stuff, and you can't participate in the Extended Specimen Network or unambiguously link material to publications without that.

>give it a name

[GUID](https://github.com/ArctosDB/arctos/discussions/5310)

GUID search will work properly in next release.

**Comment by campmlc** [comment]
There is clearly a disconnect in how Arctos displays and names these identifiers, how our community views and uses museum catalog numbers, how museum catalog numbers are used and understood by the collections community as a whole as well as the broader research committee of users. I would like to request a community discussion so we can discuss. @mkoo

**Comment by campmlc** [comment]
Guid is not universally understood to be an Arctos url outside of Arctos.

**Comment by campmlc** [comment]
This is the current definition of GUID in Arctos:
Generally "DarwinCore Triplet" within Arctos, truly the record detail page URL (which includes the "DWC Triplet").
But our tools do not make it clear which is which and which is expected, either for external users or for curatorial use. 

Currently we cannot use the url to search in the GUID field or as an identifier in Search. In the Arctos catalog record page, the url is called an "identifier". Some collections are putting the DwC Triplet as "institutional catalog number" - others aren't. 

Whatever is decided or clarified here should be added to the Arctos paper to explain what we mean by "guid" and "catalog numbers" in Arctos.

**Comment by acdoll** [comment]
> GUID search will work properly in next release.

Does that mean the GUID search field will only work with full urls to get results, or will it still accept the DWC Triplicates? If the former, I would request the addition of a DWC Triplicate search field. I use that feature often when looking for specific items across multiple collections.
