### ISSUE TITLE
Code Table Request - remove age class: chrysalis

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7596]
### Goal

Part of the cleanup of age class #2881 this term cannot be placed into one of the [eventual "life stage" categories](https://docs.google.com/spreadsheets/d/1Yv3Lx6DtSdmh0P1cSIG6zW-DnYI6VDJpOkFcgQL6F8o/edit#gid=211205961). 

### Context

We need assistance on the path forward. 

Usage

### Table

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctage_class

### Proposed Value

~~[chrysalis](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctage_class#chrysalis)~~

### Proposed Definition

~~protective covering for the pupal stage of a butterfly~~

The definition indicates that this should be recorded as a part = chrysalis with life stage = [pupa](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlife_stage#pupa). If there is agreement, we need to create the part name chrysalis = protective covering for the pupal stage of a butterfly

This might also be migrated to life stage = [pupa](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlife_stage#pupa) with "chrysalis" in method if no part is retained.

### Data
[temp_chrysalis.csv.zip](https://github.com/ArctosDB/arctos/files/14727734/temp_chrysalis.csv.zip)

### Summary

- [ ] UAM:Ento   | 23
- [x] | CHAS:Teach | 6
- [x] | CHAS:Ento  | 8

### Contact

 @DerekSikes
 @droberts49
 @wellerjes

### Helpful Actions

- [x] Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

- [ ] Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

@ArctosDB/arctos-code-table-administrators 

## Approval
_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [ ] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection
_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
3. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
4. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation
_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

- [ ] Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

- [ ] Add or revise the code table term/definition as described above. Ensure the URL of this Issue is included in the definition. URLs should be included *_as text_*, separated by spaced pipes. Do not include HTML in definitions.

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by wellerjes** [comment]
Cleaned up for CHAS records

**Comment by DerekSikes** [comment]
Ok, I found [23 records](https://arctos.database.museum/search.cfm?guid_prefix=KNWR%3AEnto%2CKNWR%3AInv%2CKWP%3AEnto%2CUAA%3AEnto%2CUAM%3AEnto%2CUAMObs%3AEnto&attribute_type_1=age%20class&attribute_value_1=chrysalis) with age class = chrysalis

but when I go to the parts to change 'whole organism' to 'chrysalis' I can't. Chrysalis is not yet in the parts code table. 

I can add life stage = 'pupa' to these 23 records now but will have to come back later to deal with editing them to parts = chrysalis.

**Comment by mkoo** [comment]
Since Derek seems ok to use as a part name, we are moving forward to add partname Chrysalis #7627

**Comment by Jegelewicz** [comment]
For 23 records, I think creating a part doesn't make sense?

This also points to the need for some tipping point in usage?

It seems like part = whole organism with chrysalis in remark would be fine as there are currently hidden chrysalis in part remarks anyway. https://arctos.database.museum/search.cfm?part_search=chrysalis

**Comment by dustymc** [comment]
merge --> https://github.com/ArctosDB/arctos/issues/2881
