### ISSUE TITLE
Arctos Report Template Request  - ASNHC_mamm_label_vial

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7598]
**Description of the report** - Mammal vial label

**Collection for which the report is needed** - ASNHC:Mamm

If this is a request to upgrade from an existing ColdFusion report in Arctos complete the following:

**SQL used in ColdFusion report** - SQL is there, but probably will need tweaking

**Example records** - Use search to find a reasonable number of exemplary records for this label, ensure you've included guid_prefix (developers will have different collection access), then select "reload with sharable URL" in the tools menu and provide that link here.

**Priority** - [Please assign a priority so that the DBA knows whether there is any urgency associated with the new template}

**Comment by Jegelewicz** [comment]
> Rose,
> 
> The error is because there is no report there, just the SQL to get the data. We need to build the report first!
> 
> Can you provide me with an image of the label you would like, the dimensions of the label and the size of the paper you will print them on? I'll get to work making a label for you once I have that.
> 
> Adios,

Teresa J. Mayfield-Meyer

**Comment by Jegelewicz** [comment]
> Teresa,
> 
> Sorry for the delay. Attached is an image of what the label could look like, with dimensions. The paper we use is 8.5"x11" (21.59 x 27.94 cm). 
> 
> Thank you!

Rose K. Wilhoyt

**Comment by Jegelewicz** [comment]
@dustymc they want to add the ASK identifiers to these labels, but ASK isn't in flat. Can you write SQL so I can get them?

**Comment by dustymc** [comment]
edited report
```
concatsingleotherid(flat.collection_object_id,'ASK') ask
```

**Comment by Jegelewicz** [comment]
> Rose,
> 
> I have the label mostly worked out with the exception of the ASK numbers which require a bit of help from Dusty. Please try them out and let me know what needs to be adjusted.
> 
> Adios,

Teresa J. Mayfield-Meyer

**Comment by Jegelewicz** [comment]
> Rose,
> 
> Great! Let me know if you need anything else. The Github issue for this report is https://github.com/ArctosDB/arctos/issues/7598
> 
> Adios,

Teresa J. Mayfield-Meyer
