### ISSUE TITLE
Wackadoodle colors and MailChimp popup in Agents Search results

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#7601]
**Describe the bug**
Colors and fonts are going all kooko on the agent search results page:
<img width="1211" alt="Screenshot 2024-03-24 at 4 16 24 PM" src="https://github.com/ArctosDB/arctos/assets/17605945/d10a0e86-fa59-4d8e-b1db-93a590e97425">

In addition to having a black background, I got a MailChimp popup show up when the page opened!

**To Reproduce**
1. Go to Search Agents
2. Entered the name "Weston"
3. Results showed up with a black screen background, with all different system fonts and a MailChimp popup window.
4. Weirdly... it seems to only be with this name! Tried my last name and others...did not replicate black screen & MailChimp popup.
5. Doesn't seem to make a difference if I'm logged in or not.

**Expected behavior**
White background and standard fonts. Seems to be the only problematic page.

**Desktop (please complete the following information):**
 - OS: MacOS 14.3.1
 - Browser: Firefox; Brave; Opera; Safari; Chrome

**Priority**
Critical... This is very bad and illegible, but only for the name Weston!

**Comment by dustymc** [comment]
That's amazing! (But I REALLY don't want to subscribe to that newsletter at the moment....)

I nuked everything for this mess...

```


arctosprod@arctos>> select * from agent_attribute where agent_id =21317728;
 attribute_id | agent_id | attribute_type |          attribute_value           | begin_date | end_date | related_agent_id | determined_date | attribute_determiner_id | attribute_method | attribute_remark | created_by_agent_id |     created_timestamp      | deprecated_by_agent_id |    deprecated_timestamp    | deprecation_type 
--------------+----------+----------------+------------------------------------+------------+----------+------------------+-----------------+-------------------------+------------------+------------------+---------------------+----------------------------+------------------------+----------------------------+------------------
        32691 | 21317728 | remarks        | brettwestonarchive.com             |            |          |                  |                 |                         |                  |                  |                2072 | 2024-02-26 18:22:38.608819 |                        |                            | 
       357666 | 21317728 | remarks        | http://www.brettwestonarchive.com/ |            |          |                  |                 |                         |                  |                  |                     | 2024-02-26 18:22:38.608819 |                   2072 | 2024-03-24 19:16:32.326854 | update
       306882 | 21317728 | associate of   | Brett Weston                       |            |          |         21290318 |                 |                         |                  |                  |                   0 | 2021-07-16 21:42:27.21179  |                        |                            | 
       282522 | 21317728 | preferred name | The Brett Weston Archive           |            |          |                  |                 |                         |                  |                  |                     | 2024-02-26 18:26:31.67709  |                        |                            | 
(4 rows)

Time: 31.836 ms
arctosprod@arctos>> select * from agent where agent_id=21317728;
 agent_id |  agent_type  |   preferred_agent_name   | created_by_agent_id |    created_date     
----------+--------------+--------------------------+---------------------+---------------------
 21317728 | organization | The Brett Weston Archive |            21282549 | 2018-12-18 14:32:48
(1 row)

```

and it should get less-evil when the cache catches up.

Not sure what's going on, first guess is some massive bug in https://docs.lucee.org/reference/functions/markdowntohtml.html I've got another library I can try, if it doesn't do horrible evil things I'll swap it out and add some data back in.

Note also that at least part of this comes back to mistyped information - Karinna put a URL in remarks for some reason.

**Comment by AJLinn** [comment]
Awesome, looks like it's all better now. Thanks for the fix... that was so weird! I thought i had activated my night mode for my operating system, but I couldn't click on anything!

**Comment by AJLinn** [comment]
Should I close? Appears to be fixed!

**Comment by dustymc** [comment]
No, I just nuked the offending data which I'll add back with release, the problem is not fixed. (But it's getting pretty close in test if anyone wants to play with that and some new related toys.)
