### ISSUE TITLE
Need Help with Arctos Error - Data Entry verification status problem

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#7606]
# Error Text
insert or update on table "specimen_event" violates foreign key constraint "fk_specimenevent_ctverifstatus"

# Where it happened
I keep trying to load https://arctos.database.museum/Bulkloader/editBulkloader.cfm?key=key_4477858, but it keeps throwing me an error that there is something in the verification status that shouldn't be there. I've taken everything out, but it still keeps throwing up an error. Help!

**Comment by dustymc** [comment]
patched and your record loaded

**Comment by ewommack** [comment]
Thanks @dustymc!
