### ISSUE TITLE
not all points plotting in Berkeley Mapper

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#7607]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Not all points are showing up on Berkeley Mapper

**To Reproduce**
Query all MVZ for agent 'conroy' regardless of prep or collect. Bring up Berkeley Mapper. Lots of dots. But, nothing shows up along coast west of Santa Barbara where I have collected a lot. Most specimens I either collected or prepped in Yosemite do not plot. I've collected twice at the Chimineas Ranch in San Luis Obispo County. My 2008 specimens plot, but not my 2023 specimens. They are all in the query results and show lat longs. 

However, if I search for just Microtus californicus, my specimens along the Santa Barbara coast do show up. Not clear what the difference is.

**Expected behavior**
All points plot on map??

**Desktop (please complete the following information):**
 Mac OS 13.3.1 (a) (22E772610a)
 Chrome
 - Version 121.0.6167.139

**Priority**
Annoying, but maps made are not accurate representation of database.

**Comment by cjconroy** [comment]
Any idea when the next release will be?

**Comment by dustymc** [comment]
<img width="605" alt="Screenshot 2024-03-27 at 12 19 26" src="https://github.com/ArctosDB/arctos/assets/5720791/b521066c-aa13-4e69-92b1-30b964887d74">
