### ISSUE TITLE
Can't Select Scientific Name "Miner's Pan"

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#7610]
Trying to select "Miner's Pan" for this record's scientific name, but the select button won't click.
<img width="870" alt="Screenshot 2024-03-26 at 3 07 59 PM" src="https://github.com/ArctosDB/arctos/assets/17605945/8204dc65-ef8f-4af3-a64c-38f34d6b0909">

The details button works, but the select button won't go!
https://arctos.database.museum/guid/UAM:EH:UA2006-006-0043

MacOS 14.3.1
Firefox 115.9esr (64-bit)

Priority: high (can't select!)

**Comment by dustymc** [comment]
patched
