### ISSUE TITLE
Component loader sort error

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#7612]
I loaded a loan item bulkload of 100 records last night and moved the Loan Item Bulkload to position 1 in the component loader, ahead of the Bulkload Part Attributes which had nearly 60,000 items in autoload. I assumed this would quickly load. But this morning nothing has changed. I moved the Buklload Part Attributes loader farther down in the list and resaved, but neither it nor any other component loaders seems to be doing anything?  @dustymc can you give it a nudge? Any other ideas?

**Comment by Jegelewicz** [comment]
It does seem to be stalled.

**Comment by campmlc** [comment]
Still stalled . . . waiting on this for loan documents.

**Comment by dustymc** [comment]
I paused and resumed the task - if that doesn't need fix it I'll need help scheduling an outage.

**Comment by campmlc** [comment]
That worked, thanks!!

**Comment by Jegelewicz** [comment]
seems to be stalled again

**Comment by dustymc** [comment]
snuck in a reboot

**Comment by Jegelewicz** [comment]
It's still stalled.

**Comment by dustymc** [comment]
>still

"again" - I restarted the task (but not the VM) and temporarily removed the ability to sort.

**Comment by Jegelewicz** [comment]
I haven't sorted anything since yesterday....

**Comment by campmlc** [comment]
It loaded what I had in the loan item bulkloader, but didn't recognize any of it so I had to delete. I haven't resorted anything, but I did delete and reload material in the component loader. It's still sitting there. Try again, pretty please?

**Comment by campmlc** [comment]
@dustymc please tweak component loader again? If this keeps stalling, we should put an announcement not to use for anything urgent on the banner.

**Comment by dustymc** [comment]
Pretty sure you can both do this, just pause and resume ``component_loader``, or you can always run it manually from the scheduler (but multiple instances trying to coexist is likely a recipe for impressive messes, so carefully please).

>urgent

PLEASE see the text on the status page.

**Comment by camwebb** [comment]
Been waiting 2 days for a media load. Tried moving media up to top and 'Save run order', but got a 'no permission' error (1EB6E6C2-AA1E-410C-B52320154819A4C7), which is strange because I have 'Manage_records' permission. Maybe this is related to the stalling/slowness?

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/7612#issuecomment-2027771613 - I think that maybe be part of the problem (and I now think I have some idea of the rest, I'll probably bring sort back with some sort of delay for both sorting and loading), as far as I can tell the loader is still running properly and seems to have loaded everything in the queue.

**Comment by campmlc** [comment]
> 
> > urgent
> 
> PLEASE see the text on the status page.

I should rephrase: don't use for anything you can't wait 24 hours or more for. For me, processing loans and needing to ship same day, that's urgent.

**Comment by camwebb** [comment]
> Tried moving [...] up to [nearer to] top and 'Save run order', but got a 'no permission' error ([...]), which is strange because I have 'Manage_records' permission. 

(Says "Manage_records users may adjust run order" on the page) Is this a bug? Or has the permission level on this changed? If former, I'll file an Issue.  Thanks

**Comment by campmlc** [comment]
@camwebb there is some problem with the loader that @dustymc is trying to figure out. It stalled out for several days. He disabled sorting temporarily, although it may be back up. Please try it and let us know.

**Comment by dustymc** [comment]
>adjust

https://github.com/ArctosDB/arctos/issues/7612#issuecomment-2027771613

>several days

That is not true.

**Comment by campmlc** [comment]
It did stall from Friday to Monday last week before it was tweaked. 24-48 hours delay is causing these comments.

**Comment by dustymc** [comment]
>It did

```
dustylee@arctos:~$ grep "component_loader.cfm" /usr/local/log/logs/access2024-03-31.txt  | wc -l
1440
dustylee@arctos:~$ grep "component_loader.cfm" /usr/local/log/logs/access2024-03-30.txt  | wc -l
999
dustylee@arctos:~$ grep "component_loader.cfm" /usr/local/log/logs/access2024-04-01.txt  | wc -l
1440
```

**Comment by Jegelewicz** [comment]
I just attempted to re-order and got

<html><body>

ERROR_ID | F20CA724-4D0B-4645-90E4921FF8B95761
-- | --
ERROR_TYPE | SQL
ERROR_MESSAGE | ERROR: permission denied for table cf_component_loader
ERROR_DETAIL |  
ERROR_SQL | update  						cf_component_loader  					set  						run_order=1, 						lastupdate=current_timestamp, 						lastuser=session_user 					where key=12

</div>
</body>
</html>

**Comment by megulbranson** [comment]
I am unable to use it as well. 


ERROR_ID	B0FDB678-AA78-4B0F-ABA3ECF1E8F191ED
ERROR_TYPE	SQL
ERROR_MESSAGE	ERROR: permission denied for table cf_component_loader
ERROR_DETAIL	
ERROR_SQL	update cf_component_loader set run_order=1, lastupdate=current_timestamp, lastuser=session_user where key=49

**Comment by dustymc** [comment]
Next release will have a short time delay on the processing side, and sorting will be protected for a few minutes. I hope that will be sufficient to avoid the clickflood that occasionally kills the loader task.

One side effect is that the status page may not be entirely accurate at all times; eg a task which has just been deprioritized will continue acting as if it has priority for some time.
