### ISSUE TITLE
Automated reports suggesting more appropriate geography are wrong/rely on outdated geography

### ISSUE THREAD

**Issue by genevieve-anderegg** [ArctosDB/arctos#7615]
The "Transartos Unified Reporting Directive" report "locality: a more spatially appropriate geography is available" gives suggestions that are reliant on old higher geography that we no longer use (oceans, continents) and are confusing.

Report link here: https://arctos.database.museum/Reports/cat_record_reports.cfm?guid_prefix=DMNS:Inv&report_name=locality:%20a%20more%20spatially%20appropriate%20geography%20is%20available.

We no longer have continents or oceans in our geography, so it's interesting that it's giving suggestions based on that. Many of the suggestions also don't make a lot of sense:
Suggests https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=1004175 for DMNS:Inv:23114, which is in Ohio. 
Suggests https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=1003635 for DMNS:Inv:24516, which is in Guam.
Is that just because these records are not geolocated? (on the to do list).

The flags on the record are public, so it would probably be good to find a way to tighten these up, or at least remove the flags that are clearly erroneous.

**Comment by dustymc** [comment]
FYI this is 100% resource limitations, I refresh as fast as I can (and have a help request in at TACC to make it faster). I am very tentatively tabling this for lack of better ideas, feel free to recategorize as necessary if that's not the right thing to do.

>Is that just because these records are not geolocated?

The more data exists, the better this type of thing is apt to be. (But IDK what the details are.)

>on the to do list

FYI
<img width="270" alt="Screenshot 2024-05-06 at 11 51 28" src="https://github.com/ArctosDB/arctos/assets/5720791/a04f5fcb-2983-4c4d-88ad-ec0e5b535ee1">
and save does an apparently-reasonable job on the one I checked.
