### ISSUE TITLE
Flat taxonomy gaps page help could be better

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7624]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

https://github.com/ArctosDB/arctos/issues/7622

**Describe what you're trying to accomplish** 
_A clear and concise overview of the goals; why are you asking for this?_

Find gaps in my preferred taxonomy source

**Describe the solution you'd like**
_How might we accomplish your goals?_

https://github.com/ArctosDB/arctos/issues/7622#issuecomment-2030534986

> it would be much more useful if it only looked at one's preferred classification (or this was an option one could set eg via a drop down menu):
> 
> classification source?
> all
> preferred
> etc.

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

Review a lot of false positives (from my perspective).

**Additional context**
_Add any other context or screenshots about the feature request here._

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._

**Comment by dustymc** [comment]
This doesn't make sense, or I don't understand what's being asked. Clarify?

**Comment by DerekSikes** [comment]
The original issue https://github.com/ArctosDB/arctos/issues/7622

resulted from unexpected results - I set the collection to UAM:Ento to use the taxonomy gap tool and expected results that were relevant to only my preferred classification source (Arctos). However, it returned results that were not relevant to my preferred classification source.

My preferred classification source had no missing 'Kingdom' rank for Araneae
at least one other (non-preferred) classification had a missing kingdom rank for Araneae and so this tool reported this name as having a gap in FLAT for rank kingdom.

I  would like the tool to only return gaps for preferred classification (or have the ability to specify which classification is being checked for gaps).

Does that clarify?

**Comment by dustymc** [comment]
>Does that clarify?

Yes thanks - the main problem is that the link from the tool makes unfounded assumptions of homogeneity.

https://arctos.database.museum/search.cfm?guid_prefix=UAM%3AEnto&scientific_name=Araneae&scientific_name_match_type=exact&kingdom=NULL would be a better link, the one record got wedged somehow.

The solution (assuming something weird happened with the cache and not weird data in that record) is....


<img width="311" alt="Screenshot 2024-04-01 at 21 34 46" src="https://github.com/ArctosDB/arctos/assets/5720791/fbc0fc71-c849-473b-9c10-c1c8ecf5a39e">

or

<img width="277" alt="Screenshot 2024-04-01 at 21 35 12" src="https://github.com/ArctosDB/arctos/assets/5720791/732d42d8-9daf-4b2f-a80b-987207dcf7c6">


(or usually just wait a bit and it'll figure it out).

**Comment by DerekSikes** [comment]
So you're saying the taxonomy gap tool only searches for gaps in the preferred classification in FLAT?

And, this result was caused by 1 record with no ID order?

& yes, thanks for updating that record. Seems like there should be a way to prevent that (a record with all IDs having ID order 0) from happening (not just a warning that people might not notice).

**Comment by dustymc** [comment]
> gaps in the preferred classification in FLAT?

Only preferred classifications are used for FLAT see eg

<img width="444" alt="Screenshot 2024-04-01 at 21 59 03" src="https://github.com/ArctosDB/arctos/assets/5720791/b4ff895b-702b-462f-91fd-4fa599f36e97">

and the tool searches for gaps in those data, so yep.

>way to prevent that 

"One or more people said some stuff we don't particularly believe" is a perfectly reasonable position!

**Comment by Jegelewicz** [comment]
OK so I was totally off base here but maybe the tool needs a better explanation of what it is doing? As well as some solutions like the one [here](https://github.com/ArctosDB/arctos/issues/7624#issuecomment-2030918216)?

## Current page text:

 This report finds NULL values in FLAT. This can be caused by many conditions, including

    missing information
    records identified to a taxon "higher" than the filter
    a particular term is not used in a discipline
    a preferred classification does not rank terms
    FLAT is stale

Inclusion in this report is not necessarily indicative of a problem. 

## Suggest:

 This report finds NULL values for the provided Taxon Rank in identifications with ID order >0 for all catalog records in the provided GUID Prefix in FLAT. This can be caused by many conditions, some of which are not necessarily indicative of a problem.

**Caution**
This form is not useful for unranked classification systems.

**Potential Problems**
    missing information - The preferred taxonomy source is missing a term. Add the missing term to the classification, request a FLAT refresh, and test again.
    FLAT is stale - Request a FLAT refresh.

**False Positives**
    records are identified to a taxon "higher" than the filter - The taxon name used in the identification correctly excludes the rank used as a filter.
    a particular term is not used in a discipline - The rank filter used in the form is not appropriate for the taxon name used in the identification.
    a preferred classification does not rank terms - This form is not useful for unranked classification systems.

**Comment by DerekSikes** [comment]
But my case involved a record with only 1 identification and it was ID order = 0.

**Comment by Jegelewicz** [comment]
> But my case involved a record with only 1 identification and it was ID order = 0.

This report finds NULL values for the provided Taxon Rank in identifications with ID order >0

It only looks at ID orders 1-9, right?

**Comment by DerekSikes** [comment]
It only looks at ID orders 1-9, right?

I don't think so. As I understood Dusty, it returned Araneae as a problem because there was one record with only one ID (of Araneae) that had ID order = 0 (this record had no other IDs, it's only ID was order=0)

**Comment by Jegelewicz** [comment]
OK - that's not how I read it. @dustymc can you review https://github.com/ArctosDB/arctos/issues/7624#issuecomment-2032171804 and comment please?

**Comment by dustymc** [comment]
Neither "we probably don't know that exists" (information from nonpreferred classifications) nor "we don't believe any of this" (order=0) data are included in "classification according to collection" data.

See https://github.com/ArctosDB/arctos/issues/7624#issuecomment-2030918216, the task is (I thought??) to change how something works, the current title seems unhelpful??

**Comment by Jegelewicz** [comment]
Well I guess that I am completely lost, so change the title if I made it unhelpful. I thought that the "bug" was due to a record with only 0 order identifications and that it was the misunderstanding that those were not evaluated that caused the confusion.
