### ISSUE TITLE
Inconsistent search returns when seeking UAM:EH barcodes

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#7625]
**Describe the bug**
Sometimes when I search by barcode in the catalog record search I'll end up with no results, even though the barcode is clearly associated with a UAM:EH item. Other times it works perfectly.

**To Reproduce**
1. Go to search catalog records
2. Click on collection UAM:EH
3. Enter barcode string in Any Barcode
4. Results return nada

**Expected behavior**
The single UAM:EH object to which that barcode has been assigned shows up in the search results.

**Screenshots**
This:
<img width="1184" alt="Screenshot 2024-04-02 at 12 30 58 PM" src="https://github.com/ArctosDB/arctos/assets/17605945/3f171ea2-ca33-484f-8deb-915fffdf9001">
results in this:
<img width="1184" alt="Screenshot 2024-04-02 at 12 31 11 PM" src="https://github.com/ArctosDB/arctos/assets/17605945/687c87ff-81a1-4858-9233-70e84fbc00a3">

But this exists for catalog number https://arctos.database.museum/guid/UAM:EH:UA69-099-0001:
<img width="1184" alt="Screenshot 2024-04-02 at 12 31 27 PM" src="https://github.com/ArctosDB/arctos/assets/17605945/8c7afe0d-e5ee-4a79-a698-a351dc7e0dc4">

**Desktop (please complete the following information):**
 - OS: MacOS 14.3.1
 - Browser Firefox
 - Version 124.0.2 (64-bit)

**Priority**
Normal - it's not stopping me from finding my objects because I can simply look them up with the catalog number, but part of the joy of barcodes is scanning to reduce/eliminate transcription error!

**Comment by dustymc** [comment]
Links are always super useful. You can search then...

<img width="258" alt="Screenshot 2024-04-02 at 16 47 39" src="https://github.com/ArctosDB/arctos/assets/5720791/46cd01a2-086a-4ead-bc7c-5445478e7f52">

.. then copy the page URL, which will ensure we're looking at the same things.

https://arctos.database.museum/search.cfm?barcode=UAMEH8317 and https://arctos.database.museum/search.cfm?anybarcode=UAMEH8317 both find one record for me.

**Comment by dustymc** [comment]
>take a little while

Barcode (more precise and much cheaper than anybarcode) should have no cache delay.

**Comment by AJLinn** [comment]
Updated my search options to Barcode. Thanks for the tip!

**Comment by AJLinn** [comment]
Completed - new barcodes appearing to scan properly.
