### ISSUE TITLE
Planned Outage:  4/16 at 9-11am CT (long)-- Arctos will be offline for database work

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#7628]
## Planned Outage
 - Date and time of planned outage: April 9, 2024 Wed at 7 am PT/ 9 am CT _brief_ AND April 16, 2024 at 7-9 am PT/ 9-11am CT (long)
 - Reason for outage: Routine work is planned: 4/9 will be brief for updating the IPT; 4/16 will be for approximately 2 hours for 
 Arctos database Prod and Test server syncing
 - Expected behavior during and after the outage: Arctos will be unavailable during these times. Please plan accordingly

## Communication before/during outage
- [x] Pin this issue
- [x] Banner updated @jegelewicz @mkoo
"Planned Outage: Wed April 9, 2024 at 7 am PT/ 9 am CT (brief). Arctos will be offline for a reboot to update the IPT. Please plan accordingly and apologies for any inconvenience."
- [x] Email sent to AWG  
- [x] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [x] Unpin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG 
- [x] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by AJLinn** [comment]
Our Museum will be undergoing federally required NAGPRA consultation on the 10-11 of April. We'll have representatives of over 100 of Alaska's Federally Recognized Tribes meeting at our museum and Arctos access will be critical. While I'll have printed lists with locations of some materials for those two days, we're also meeting with tribal representatives on the 9th and 11th and we must have access to our data those days as well.

Please, can we reschedule planned outage AFTER we finish our consultations? We'll be done by 5:00pm Alaska time Friday the 121th. This is the largest consultation we've had and we have 30+ people flying to Fairbanks specifically for this on a federal NAGPRA grant.

**Comment by wellerjes** [comment]
Is this outage still happening tomorrow?

**Comment by ewommack** [comment]
Good question @wellerjes! It completely slipped passed my radar. @mkoo @dustymc ?

**Comment by mkoo** [comment]
Yes, sorry I didnt see that the banner expired and needed a new one-- fixed!

@ewommack maybe an email to AWG now?

**Comment by ewommack** [comment]
Sent out email

**Comment by ewommack** [comment]
And another email to go out tomorrow morning, and posted it on the Arctos Slack.

**Comment by lin-fred** [comment]
tweeted

**Comment by dustymc** [comment]
Arctos is back up.
