### ISSUE TITLE
Arctos Down - 2024-04-03

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#7629]
Please complete to the best of your ability.

## Unplanned Outage
 - Date and time (**please add time zone from which you are reporting**) outage discovered: 2:11 pm AkDT
 - Describe the outage (Arctos down or only some part not working?): Suddenly stopped working - got a timeout error screen the first time with a bright orange error... won't pull it up now

## Planned Outage
 - Date and time outage will begin:
 - Date and time outage is expected to end:
 - Reason for outage:
 - Expected behavior during and after the outage:

## Communication before/during outage
- [x] Pin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [x] Email sent to AWG  
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by Jegelewicz** [comment]
Here as well.

**Comment by ewommack** [comment]
Not working in WY too. 
This has been for at least 30 min, so I'll send out an email:

Heads up Arctos!
We're experiencing some technical difficulties. Check this issue (link) for the latest updates.

**Comment by mkoo** [comment]
Yes, it's unresponsive.... emails sent

**Comment by ccicero** [comment]
Still down in Berkeley.

**Comment by dustymc** [comment]
bounced VM

**Comment by mkoo** [comment]
THANK YOU!!!

**Comment by ewommack** [comment]
Working in WY again, thank you Dusty!
