### ISSUE TITLE
Request new collections for UAM under 'UAMlib:', for library materials

### ISSUE THREAD

**Issue by camwebb** [ArctosDB/arctos#7631]
**Request**

Please create new collections 'UAMlib:Herb' and 'UAMlib:Art' (and possibly more)

**Background**

Several collections at UAM are interested in using Arctos to manage collections-related documents (lab library, correspondence, etc). The object tracking and loan tracking in Arctos is excellent for handling books. In the herbarium (with @StefanieBond) we are now settling on a [mapping][1] of our document information to the Arctos data model. We would like to keep the document collection separate from the biological collections, so need a new collection prefix. We could all share UAM:Lib (or UAM:Doc), but differences in data modeling between collections could make this messy and conflict-prone. Instead, and following from conversations between @DellaCHall and @Jegelewicz, a new suffix on 'UAM' seems best, 'lib' or 'lit' or 'doc' or 'bib'... I go with 'lib', but am open to something else.

Tagging @gradyjt, and @AJLinn from related issue #4092. @AJLinn do you want a 'UAMlib:EH' collection?

[1]: https://github.com/ALA-herbarium/documentation/blob/main/library.md

**Comment by DellaCHall** [comment]
Thanks Cam! UAMLib:Art makes sense for me, following the pattern of UAMObs:Art that I already have/use.

**Comment by Jegelewicz** [comment]
I would actually discourage adding things to UAM (if I had a choice none of the observation collections would have Obs associated with the institution).

Suggest instead

UAM:EHLib
UAM:BioLib
UAM:ArtLib

If you want to have all UAM collections sort discipline specific

or

UAM:LibEH
UAM:LibBio
UAM:LibArt

If you want to have all UAM library collections sort together.

Just an opinon, feel free to ignore.

**Comment by camwebb** [comment]
@Jegelewicz Yes this is better than confusing the institution (I wish we had UAM:Cryptogam rather than UAMb:Herb). We'd like: UAM:HerbLib - I think it better to keep the literature with the collections, in a sort.

**Comment by AJLinn** [comment]
Sure, I'll take a UAM:EHLib

**Comment by DellaCHall** [comment]
Okay, UAM:ArtLib it is!

@Jegelewicz UAMObs:Art is fairly new...is it too late to switch it around to UAM:ArtObs, so everything is consistent?

**Comment by camwebb** [comment]
> The one real "requirement" of GUIDs is that they don't change

Agree. No request to change 'UAMb' - it's been there for a long time. Just wishing, that's all...

**Comment by Jegelewicz** [comment]
> Just wishing, that's all...

A guy can dream...

**Comment by camwebb** [comment]
I have made the collection_request_template.csv file, but there's no longer a `https://github.com/ArctosDB/new-collections` repo. Should I just use this repo (arctos/issues)?

 I realize also that 'HerbLib' will need to be added to `collection_cde` code table - should that be a separate issue?

**Comment by dustymc** [comment]
>collection_cde

[Nope](https://handbook.arctosdb.org/documentation/catalog.html#guid-prefix)...

**Comment by mkoo** [comment]
Really interesting use case here! and lots of ways to tag/ relate/ tie records together (docs to specimens, etc). I have been contemplating MVZ:Arch for such related purposes and will be interested to see how you guys set precedence (and the pros/cons)!

**Comment by camwebb** [comment]
Sorry, still need info. There no 'new-collections' repo any more, or else it is private.

**Comment by Jegelewicz** [comment]
Its private. I am going to move that issue template back over here.

**Comment by Jegelewicz** [comment]
@camwebb try this https://github.com/ArctosDB/arctos/issues/new?assignees=Jegelewicz&labels=nodev%2C+Priority-Normal+%28Not+urgent%29&projects=&template=exisiting-institution-requesting-a-new-collection.md&title=%5BArctos+Institution+Name%5D+request+to+add+a+new+collection

**Comment by camwebb** [comment]
Submitted. Closing this issue. Thanks all
