### ISSUE TITLE
Need Help with Arctos Error from Tool: Request Flat Refresh

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#7633]
# Error Text
**Copy the text from the page and paste it here**
543A6764-3A71-4184-8670329067515EF3

What did I do wrong?

# Where it happened
**Provide a link to or a description of the page where the error occurred.**
https://arctos.database.museum/search.cfm?loan_number=2022-17.EH

# Steps to get there
I've been adding a lot of images to these 485 records and inevitably the new ones show a broken preview, for example:
<img width="767" alt="Screenshot 2024-04-04 at 12 33 35 PM" src="https://github.com/ArctosDB/arctos/assets/17605945/85f8b0c9-d3e2-4e9f-8754-514b4ef264ad">

# Problem
I tried to use the new Tool: Request Flat Refresh instead of individually opening each record and requesting a cache refresh. The tool warned me that in certain circumstances I might get an error... well, yes, here we go.

Please help! I need these visible for my NAGPRA consultation next week (April 10-11).

# Solution
**Community response with directions for how to correct the problem**

**Comment by Jegelewicz** [comment]
@AJLinn did you load thumbnails or are you letting Arctos create them?

**Comment by AJLinn** [comment]
Letting Arctos create them

**Comment by Jegelewicz** [comment]
OK, so I think it is the cache. @dustymc can you help?

**Comment by AJLinn** [comment]
> Please help! I need these visible for my NAGPRA consultation next week (April 10-11).

Timing is no longer an issue since @mkoo came to my rescue and helped figure out a report for UAM:EH. That said, I am still looking to see why the tool didn't work to refresh the cache for those images. I went in and requested the refresh manually to make sure these all work properly for my NAGPRA consultation next week.

**Comment by dustymc** [comment]
There's also a media cache, and a bit of waiting for each other, involved. Looks like everything's caught up now.

<img width="1072" alt="Screenshot 2024-04-08 at 05 36 47" src="https://github.com/ArctosDB/arctos/assets/5720791/bc759982-0ecc-46f3-a4c7-d3d3045a5e74">
