### ISSUE TITLE
Feature Request - choice of fields in View Attribute (Identifiers or Parts) tables

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#7635]
**Is your feature request related to a problem? Please describe.**
Attributes, Identifiers, and Parts have a many to one relation to records making it a challenge to view in the results table so we have separate Viewers to see these data. However the Viewer tables lack many of the fields from results table, leading to a lot of flipping between tables and applications. For example View Attributes tables allows filtering on attributes but only shows these fields in the table: (GUID, attribute, value, unit, method, determiner, date, remark)

**Describe what you're trying to accomplish** 
Viewing records by several parameters such as date and attributes is a common task and not made easy currently

**Describe alternatives you've considered**
current alternative is to download large files to excel, sort and pull hair

**Describe the solution you'd like**
Being able to add a few fields to the Viewers tables (eg county, verbatim date-- basically flat fields already retrieved in the results) would massively increase usefulness of the View Attributes table. If there are constraints that need to be imposed, eg. only can pick 9 fields for the table, we can discuss and probably be able to live with that.

Here's a quick mockup we discussed in CT:

![Firefox_Screenshot_2024-04-04T23-58-21 494Z](https://github.com/ArctosDB/arctos/assets/2523089/2242063f-d10d-49a8-a095-226b7f2ddc57)

This needs @dustymc discussion next!

**Comment by dustymc** [comment]
How's this not...

<img width="179" alt="Screenshot 2024-04-04 at 20 24 13" src="https://github.com/ArctosDB/arctos/assets/5720791/88984e12-7611-404e-bf96-7202a8ee8e94">

... which allows a user to choose fields, then adds to that attributes by type? Perhaps slightly different (but much more reusable) order of operations but same result, no?

**Comment by dustymc** [comment]
assuming resolved....
