### ISSUE TITLE
search result only shows 100 results despite selecting show 1,000 or 5,000 entries

### ISSUE THREAD

**Issue by amgunderson** [ArctosDB/arctos#7637]
**Describe the bug**
A search result will show 10, 25, 50 or 100 records when those values are chosen at the bottom of a search result but chosing 1,000 or 5,000 still shows 100.
<img width="162" alt="Screenshot 2024-04-05 at 9 02 05 AM" src="https://github.com/ArctosDB/arctos/assets/8440698/5d0d90b3-9b9f-4328-9985-9ba6b907ffda">

**To Reproduce**
search for something that will produce a result of 5,000+ records, at the bottom of the page choose show 1,000 or 5,000 records and see how many is shown.

priority - a black hole of despair.

**Comment by amgunderson** [comment]
This is still happening. [This search](https://arctos.database.museum/search.cfm?guid_prefix=UAM%3AMamm&customoidoper=LIST&scientific_name=Enhydra%20lutris&part_search=skull&poly_coords=%5B%7B%22lat%22%3A52.40874641672526%2C%22lng%22%3A-171.56407557728943%7D%2C%7B%22lat%22%3A51.91001165040205%2C%22lng%22%3A-171.76182948353943%7D%2C%7B%22lat%22%3A50.92342594170682%2C%22lng%22%3A-177.89220057728943%7D%2C%7B%22lat%22%3A51.020279489247976%2C%22lng%22%3A178.76795567271057%7D%2C%7B%22lat%22%3A52.03184007381245%2C%22lng%22%3A176.04334629771057%7D%2C%7B%22lat%22%3A52.71595871646895%2C%22lng%22%3A177.20789707896057%7D%2C%7B%22lat%22%3A52.27450415535863%2C%22lng%22%3A-178.22179042103943%7D%2C%7B%22lat%22%3A52.822311246614284%2C%22lng%22%3A-173.93712245228943%7D%5D) should show 524 specimens but the search result page will only display 100, with no option to go to the next page.

**Comment by dustymc** [comment]
>Showing 1 to 524 of 524 entries

Something's definitely broken, I'll get it ASAP, but at least for me everything is on the one page.

**Comment by amgunderson** [comment]
If I choose to show 100 I can see 100 and select the next page and see the next 100 etc. But if I choose to show 1,000 I see 100 and have no option to  view the next page of 100. Using Chrome

**Comment by cjconroy** [comment]
I've seen the same thing for a while. I can only see 100 records per page, even if I choose to show 1000 per page. It will says 1-1000 on the first page if that is selected, but really only 1000. For a query with 1300 records, it only allows showing 2 pages, each with 100 records. I haven't bothered to figure out which of the series make it into those two pages.
Also, something the numbers at the top of the table are weird. See attached. 
<img width="317" alt="weird numbering" src="https://github.com/ArctosDB/arctos/assets/5749672/aee15e48-cd95-49f8-b725-d0fd6705606b">
