### ISSUE TITLE
[CONTACT: Blocked Network]

### ISSUE THREAD

**Issue by porttownsend119** [ArctosDB/arctos#7638]
restricted IP: 138.68.226.155

Hi, I'd like to view the Bus 142 collection but am unable to "Your IP (138.68.226.155) or organization has been blocked. "

I believe that it was due to the fact that I am required to use a VPN for database work for my company. I disconnected from the VPN but am still unable to access the collection. I am very impressed with the conservation work on the bus as I restore classic vehicles myself. I also spend a good amount of time each year camping and exploring in the wilderness, so the story of Chris McCandless and his journey to Alaska is of much interest. Please let me know how I may be allowed to access the Bus 142 collection on Arctos.

Regards,
Michael J Martin

**Comment by mkoo** [comment]
Your IP has been released. please give it a few minutes to see results. 
Your kind words should go to the UAM collections!
