### ISSUE TITLE
Tissue Quality ranking

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#7640]
I think there are collections out there implementing some sort of qualitative ranking for tissues. If so, do you mind sharing your system/how you assign a score? Is there somewhere in Arctos where you store the rankings/definitions? Do you record the info in part condition?

We are trying to reaccredit our Mammal collection and this is something ASM is looking for. 

@campmlc @jldunnum @amgunderson @acdoll @ccicero (other input welcome!)

**Comment by ebraker** [comment]
Oh! And now I see there is a tissue quality attribute, but the table is not found:

https://arctos.database.museum/info/ctDocumentation.cfm?table=cttissue_quality

**Comment by dustymc** [comment]
See https://github.com/ArctosDB/arctos/issues/5058

"meh whatever" --> specimen_part.condition
"descriptive, but history and metadata matter!"--> https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecpart_attribute_type#condition_report
"actual data" ---> container_environment, https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecpart_attribute_type#storage_temperature, https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecpart_attribute_type#ratioofabsorbance260_230, https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_preservation_need, history of https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_preservation, etc.

**Comment by campmlc** [comment]
Yes, we assign a field or prep assessment initially as excellent through poor, and now use attributes for anything subsequent, eg when we pull for loan. But we have so many legacy tissues that not all have updated quality. I've been using condition report but tissue quality would make more sense in this case.

**Comment by dustymc** [comment]
done?
