### ISSUE TITLE
What role / permission is needed to merge localities?

### ISSUE THREAD

**Issue by adhornsby** [ArctosDB/arctos#7647]
This is not a question about merging localities, it's a question about how to grant the permission to do so.

Users **FKelly880** and **gacatail** are working in **mmnh_mamm** and have **manage_locality** role permissions.  I thought that should give them the ability to merge localities, but it apparently does not.  

What role are they missing?  The only roles they _don't_ have are manage_agents, manage_media, manage_publications, and view_container.

Below is the description of the error from FKelly880.

# Error Text
ERROR_ID 	22DD8865-3E9C-4E0C-8F184B78DA4CC81F
ERROR_TYPE 	SQL
ERROR_MESSAGE 	ERROR: permission denied for table tag
ERROR_DETAIL 	
ERROR_SQL 	update tag set locality_id=11902029 where locality_id in (12256940 )

# Where it happened
https://arctos.database.museum/duplicateLocality.cfm

# Steps to get there
Beginning in the “Check Dups” step, I ignored all search fields except for “geog_auth_rec_id” and “spec_locality”. Then, I found the “locality_id” that matched the record that I wanted to merge into the existing record containing the target georef. I checked the box, and clicked “merge checked localities with this locality”, which resulted in the above error message

# Problem
**Community response to describe the problem that caused the error**

# Solution
**Community response with directions for how to correct the problem**

**Comment by dustymc** [comment]
manage_media is the problem - locality merges update TAGs (of which I think there are none here, but still...).

I think that's maybe-correct, but up for better ideas if not.

**Comment by adhornsby** [comment]
Manage_media did it!  Thanks @dustymc
