### ISSUE TITLE
save GeoLocate WKT to locality

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#765]
Geolocate has a "draw polygon" option - figure out how to save the results of that to Locality.WKT_polygon.

**Comment by dustymc** [comment]
GeoLocate does not seem to be pushing polygons back to us - needs coordinated with them.

**Comment by mkoo** [comment]
Need to wrap the coordinates with
```
POLYGON(
```
and close with 
```
)
```
to make into WKT.

If it's a multipolygon or something complicated, then it's complicated-- I dont think Geolocate can do that though so probably a nonissue.
