### ISSUE TITLE
Unable to pull existing part name from code table

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#7653]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I am trying to add "gastrointestinal tract" as a part to two different mammal records (UCM:Mamm:5806 and UCM:Mamm:5807). This is a part name currently available in the code table:

![image](https://github.com/ArctosDB/arctos/assets/11336485/fbe7c69e-d002-4a32-8a29-314ff1a822c0)

However, I cannot query it in a part name search (copying and pasting correct spelling, etc.): 

![image](https://github.com/ArctosDB/arctos/assets/11336485/a006ec24-4a2d-454c-a30d-4e3622d00185)

And I receive an "invalid part name" error when trying to save:

![image](https://github.com/ArctosDB/arctos/assets/11336485/59b0a8e9-8d6a-4638-9c4c-cc086190a7e8)

In fact, nothing comes up when I query "g" despite there being multiple part names beginning with "g" so perhaps this is a bigger issue?

**Comment by dustymc** [comment]
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name

<img width="150" alt="Screenshot 2024-04-09 at 15 46 00" src="https://github.com/ArctosDB/arctos/assets/5720791/3116e411-810f-4437-9268-db14f1201c8a">

**Comment by ebraker** [comment]
Gotcha! Thank you!
