### ISSUE TITLE
How to associate an accession with a project?

### ISSUE THREAD

**Issue by kmkocot** [ArctosDB/arctos#7655]
Good morning. I would like to associate ALMNH:Inv accession 1003 with the project titled "ICY INVERTS: Antarctic Research Expeditions" (https://arctos.database.museum/Project.cfm?Action=editProject&project_id=10003591). I don't see how to do this from either the Edit Accession or Edit Project Page.

Thank you!
Kevin Kocot

**Comment by Jegelewicz** [comment]
Edit the accession and enter the Project here

![image](https://github.com/ArctosDB/arctos/assets/5725767/67abffd6-fd0f-4758-81f6-658ee8fc287b)

**Comment by kmkocot** [comment]
Thank you @Jegelewicz! I misunderstood the New Project box and thought that was just for creating a new project. 

It appears I don't have the necessary permissions, though.
![image](https://github.com/ArctosDB/arctos/assets/10491081/abb6d0ab-b0da-4473-834e-12e66ae593de)

**Comment by Jegelewicz** [comment]
@kmkocot I think you need manage_publication

Please read the documentation and let me know you understand and I will grant you access.

[Arctos Publication Documentation](http://handbook.arctosdb.org/documentation/publications.html)
[Arctos Project Documentation](http://handbook.arctosdb.org/documentation/projects.html)

**Comment by kmkocot** [comment]
Thank you! I understand.

**Comment by Jegelewicz** [comment]
manage_publication added! let me know if you have any issues
