### ISSUE TITLE
Barcode Series Request - a single barcode to hold UAM:Ento loans

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#7658]
Issue Documentation is at http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html 
Barcode Series Documentation is at http://handbook.arctosdb.org/documentation/container.html#barcode-series

Please supply the following so that we can evaluate your barcode series request. If the series is available, it will be claimed and created for you. If it is not, a response will be posted to this issue and we will work to get you a suitable barcode series.

First barcode in series: __________ UAM:Ento_loan

Last barcode in series: __________ UAM:Ento_loan

Rules for creating random letters or digits (i.e. I would like all barcodes to have 5 places, start with an A, and the remaining 4 places can be any combination of capital letters A-Z or numbers 0-9):

Additional context Add any other context or screenshots about the feature request here.

I just want a single barcode that can be used to scan UAM:Ento loaned parts into via object tracking.

**Priority**
Please assign a priority-label.
normal

**Comment by dustymc** [comment]
I can do that, I'll need to know what value you want for the barcode.

BUT - why reuse one? Why not a series and actually/physically associate them (eg print on cheap paper, they don't have to last) with the loans? Seems like an opportunity to better track stuff, maybe use (or request then use) some 'put everything in this container in that loan' functionality, and even just deal with two loans at a time.

**Comment by DerekSikes** [comment]
The value is UAM:Ento_loan

There is no series. I want all loans to be scanned into this one "container" - we already have too much chaos of containers to keep track of & don't want to add real temporary shipping containers with unique barcodes to that.

**Comment by dustymc** [comment]
done

**Comment by DerekSikes** [comment]
thanks!

**Comment by DerekSikes** [comment]
So, when I go to Container:Find and search on barcode = UAM:Ento_loan nothing is found. Do I have to wait or is something wrong?

**Comment by dustymc** [comment]
You asked for the claim, not the container, but there's a problem anyway: The colon currently isn't allowed. 

If you're sure your scanner/encoding can handle it we can see if other collections can deal with that, otherwise pick something else and I'll claim+create that.

The current rule is

``barcode ~ '[^a-zA-Z0-9\ \-\.\_]'`` 

Documentation is https://handbook.arctosdb.org/documentation/container.html#guidelines-for-barcode-containing-labels

**Comment by DerekSikes** [comment]
Ok, so how do make it a container?

& regarding the colon. Let's change it to UAMEnto_loan

**Comment by dustymc** [comment]
Done and done.

https://arctos.database.museum/findContainer.cfm?barcode=UAMEnto_loan

You can create with [Container: Bulkload](https://arctos.database.museum/loaders/bulkCreateContainer.cfm) (and try really hard not to think about the implications of the giant pile of stuck duplicates - including a UAM - in there....)

**Comment by DerekSikes** [comment]
thanks!
