### ISSUE TITLE
github identifier type check needs updated

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#7661]
These are not good and should just be removed from the agent

BARE_ID | AGENT_ID | PREFERRED_AGENT_NAME | IDRS
-- | -- | -- | --
21334984 | https://arctos.database.museum/agent/21334984 | Alicia Davis | GitHub = https://github.com/
21334985 | https://arctos.database.museum/agent/21334985 | Clara Frickmann | GitHub = https://github.com/
21335546 | https://arctos.database.museum/agent/21335546 | Maddie McCutcheon | GitHub = https://github.com/

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/arctos/issues/7550#issuecomment-2050173033_

**Comment by Jegelewicz** [comment]
I would say that any exact duplicate of ORCiD, Wikidata, LoC, or Github is a huge red flag that the agents are duplicates or one of them has and incorrect identifier.

**Comment by dustymc** [comment]
garbage purged, check updated, duplication detection leak patched
