### ISSUE TITLE
agent attribute - identifier - two forms of LoC

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#7662]
Not sure about the two forms of LoC? But they both seem to work.

AGENT_ID | PREFERRED_AGENT_NAME | IDRS
-- | -- | --
https://arctos.database.museum/agent/21336524 | John Woodhouse Audubon | Library of Congress =   https://id.loc.gov/authorities/names/nr98018569
https://arctos.database.museum/agent/10011348 | Barbara R. Stein | Library of Congress = https://lccn.loc.gov/n2001003670

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/arctos/issues/7550#issuecomment-2050200556_

**Comment by dustymc** [comment]
This is a recipe for bad data.

Source issue is https://github.com/ArctosDB/arctos/issues/4087

John Woodhouse Audubon
* https://id.loc.gov/authorities/names/nr98018569.html
* https://lccn.loc.gov/nr98018569

Barbara R. Stein
* https://lccn.loc.gov/n2001003670
* https://id.loc.gov/authorities/names/n2001003670.html

Those are all the same data, different UI. https://lccn.loc.gov/n2001003670 is probably more canonical, https://id.loc.gov/authorities/names/n2001003670.html is maybe prettier. I don't think there's any techy reason to prefer one over the other, I'm sure I can swap back and forth at will. 

Let's pick one and standardize.

@mkoo the initial request is yours, if nobody has strong feelings I'll go with whichever one you like best.

**Comment by mkoo** [comment]
The links go to two different kinds of web pages but you're right that https://lccn.loc.gov/n2001003670 seems to be the canonical choice.

The html page is a kind of reference page with links to whatever resources available for that LC Name (LOC calls it an authority file); on that page they clearly refer to the above type of links as an ```URI```

So if we want a normalized permalink then we should assert the https://lccn.loc.gov/ links
(gory details: https://lccn.loc.gov/lccnperm-faq.html) Seem ok?!

**Comment by dustymc** [comment]
FYI there were three patterns (6 if counting sometimes-ssl) in the existing data, not two:

```
 https://lccn.loc.gov/n91077474
 https://id.loc.gov/authorities/names/n88617310.html
 http://id.loc.gov/authorities/names/n2019029005
```

and a metric crapton of multiple of different formats on the same agent.

Cleaned, rules tightened, documentation updated.
