### ISSUE TITLE
Taxon name checker help

### ISSUE THREAD

**Issue by lin-fred** [ArctosDB/arctos#7664]
I haven't used this tool in a while since it has been updated but I am trying to check on some butterfly taxa. I have the file currently in the loader but when I download the CSV nothing comes up as far as telling me if the name is in Arctos or not. Is there something I am missing? https://arctos.database.museum/loaders/taxon_name_check.cfm#lindseyfrederick

**Comment by dustymc** [comment]
click
<img width="222" alt="Screenshot 2024-04-11 at 15 24 35" src="https://github.com/ArctosDB/arctos/assets/5720791/f67252a1-5938-4dc3-865e-e67f20bfcb39">

then

<img width="289" alt="Screenshot 2024-04-11 at 15 24 44" src="https://github.com/ArctosDB/arctos/assets/5720791/05fcce79-5abc-4a21-b985-4a08e3f3f725">

then

<img width="305" alt="Screenshot 2024-04-11 at 15 24 48" src="https://github.com/ArctosDB/arctos/assets/5720791/272c8ef7-8c8d-4b02-8d2a-177ede43a3f4">

**Comment by lin-fred** [comment]
Thank you @dustymc !!!!!
