### ISSUE TITLE
Chrome misbehaving for me using Arctos

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#7665]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I haven't been able to edit localities in Chrome for a while. When I pull up a locality, I immediately get iframe URL does not have permission to interact with me. How can I fix this?

Now, today, I cannot do data entry. Same problem. Clicking OK does not fix the problem. 

**Screenshots**
attached

**Desktop (please complete the following information):**
 - Mac 13.3.1 (a) (22E772610a)
 - chrome
 - Version 123.0.6312.123 (Official Build) (x86_64)

**Priority**
I can work around it. Safari works fine, but I do most of my stuff in Chrome. 

<img width="977" alt="Screenshot 2024-04-11 at 3 51 16 PM" src="https://github.com/ArctosDB/arctos/assets/5749672/8ebae927-ed63-466c-be3b-a062fae049cb">
<img width="1060" alt="Screenshot 2024-04-11 at 3 52 02 PM" src="https://github.com/ArctosDB/arctos/assets/5749672/8fd72d66-0c8b-41ca-ab1f-8c10c90fa417">

**Comment by dustymc** [comment]
Maybe @mkoo can come watch your javascript console, something (probably an extension) is messing with things that can't be messed with.

**Comment by mkoo** [comment]
@cjconroy try turning off all your extensions and reload the page. Let me know what happens.

@dustymc you may be right to blame an extension! I am getting a bunch of errors w/wo extensions BUT I dont think they are triggering the iframe complaint. this is console with a minimum of extensions and I get an error:
![Capture](https://github.com/ArctosDB/arctos/assets/2523089/7b211820-9543-4d00-a2fd-2c02d0c48ef8)

This is with no extensions/dev mode AND fresh Chrome installation --> no error:
![Capture2](https://github.com/ArctosDB/arctos/assets/2523089/b1d9d6fb-568f-427a-b865-87a40ff8bc6e)

**Comment by cjconroy** [comment]
Seems to work!  Thanks.
