### ISSUE TITLE
Code Table Request - Index Herbariorum code / GRsciColl Code, in ctagent_attribute_type

### ISSUE THREAD

**Issue by camwebb** [ArctosDB/arctos#7673]
**Request**

A new ctagent_attribute_type field to store an institution's acronym.

**Context**

Many organizations in the agents table are collection-holding institutions. All herbaria have a code in [Index Herbariorum](https://sweetgum.nybg.org/science/ih/) (e.g., ALA for the U Alaska, Fairbanks herbarium). For other Nat hist. collections, most institutions are now registered in GBIF's [GRSciColl](https://scientific-collections.gbif.org/), and for these a code has been chosen if no IH code already existed. 

Up to now, many Arctos agents have an 'aka' field with the collection code. However, searching on aka='K' or 'L' returns hundreds of records. Having a single field with this code would greatly increase the speed of locating an agent during transaction data entry.

**Proposed Value**

either `ih code` or `grscicoll code` - probably the latter, for greater scope

**Proposed Definition**

"An collection-holding institution's code as listed in https://scientific-collections.gbif.org/ For herbaria, this is the Index Herbariorum code"

**Available for Public View**

Yes

**Alternative solution**

Since many institutions _already_ have their code in 'aka', modify the agent attribute search on attributes to allow aka = '`=K`' to exactly match aka field values.  Currently the search appears to work as '%searchtext%' 

----

- [x] Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

**Approval**

_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [ ] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [ ] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection
_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation
_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

- [ ] Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

- [ ] Add or revise the code table term/definition as described above. Ensure the URL of this Issue is included in the definition. URLs should be included *_as text_*, separated by spaced pipes. Do not include HTML in definitions.

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by dustymc** [comment]
>ALA

Isn't this just https://arctos.database.museum/info/ctDocumentation.cfm?table=ctagent_attribute_type#kew_abbr_?

>grscicoll

Use URL - https://arctos.database.museum/agent.cfm?include_verbatim=no&attribute_value=https://www.gbif.org/grscicoll/collection&include_bad_dup=false

>exactly match

https://arctos.database.museum/agent.cfm?agent_name==H.&include_verbatim=no&include_bad_dup=false

**Comment by camwebb** [comment]
> Isn't this just Kew Abbr.

Kew Abbr. is the (botanical) person's name abbreviation that appears in a plant name's Author string

> Use URL 

The goal/hope is to be able to type the 1-3 letter acronym into one of the agent search boxes and have a single match returned. typing a whole URL doesn't get us there.

>> exactly match

Doesn't work for me. For example, looking for [A](https://arctos.database.museum/agent/21344739) - [this](https://arctos.database.museum/agent.cfm?include_verbatim=no&attribute_type=aka&attribute_value==A&include_bad_dup=false) find thousands and [this](https://arctos.database.museum/agent.cfm?agent_name==A&include_verbatim=no&include_bad_dup=false) finds nothing.

**Comment by dustymc** [comment]
>person

Ah thanks, derp.

>nothing

Ah yea that's me trying to return a reasonable number of records without melting the system. Next release will take two chars in name as long as one of them is ``=``. https://arctos-test.tacc.utexas.edu/agent.cfm?agent_name==%F0%9F%A6%95&include_verbatim=true&include_bad_dup=false

**Comment by camwebb** [comment]
Thanks for upcoming search change. But I'd still like to propose this CT addition.

**Comment by Jegelewicz** [comment]
I generally put the code in aka and the link to GRSciColl in url and with the addition of the =, it should be easier to search

name "=ALA"

than

attribute "GRSciColl Code"
attribute value "ALA"

no?

**Comment by camwebb** [comment]
The upcoming change to search allowing a `=` for exact match will help, but any agents with first or middle names that are single characters without a period would also be returned when searching for collection codes that are single letters, e.g., 'A', 'K', 'L'. Given this, I don't think adding data to a special attribute is too onerous.

**Comment by dustymc** [comment]
>upcoming

I ain't that slow, https://arctos.database.museum/agent.cfm?agent_name==A&include_verbatim=false&include_bad_dup=false

>agents with first or middle names that are single characters

Hopefully there won't be any but that's probably wrong...

>onerous

I just don't understand it (yet, I hope).

**Comment by Jegelewicz** [comment]
> agents with first or middle names that are single characters without a period

@dustymc can you get me a list of these - I know there are some....

**Comment by dustymc** [comment]
>know there are some....

Right you are. Great....

```
 select agent_id, attribute_type,  attribute_value, getPreferredAgentName(created_by_agent_id) creator  from agent_attribute where length(attribute_value)=1 and deprecation_type is null order by agent_id;
 agent_id | attribute_type | attribute_value |        creator         
----------+----------------+-----------------+------------------------
 21254036 | remarks        | ?               | 
 21280615 | job title      | L               | 
 21285603 | remarks        | .               | 
 21286348 | aka            | x               | 
 21327757 | middle name    | M               | 
 21338954 | middle name    | K               | 
 21344739 | aka            | A               | C. O. Webb
 21346005 | middle name    | L               | 
 21347954 | middle name    | J               | 
 21348240 | middle name    | J               | 
 21348242 | middle name    | L               | 
 21351979 | middle name    | E               | Alyssa Semerdjian
 21352037 | aka            | O               | C. O. Webb
 21352092 | first name     | H               | Jozef A. Slowik
 21352092 | middle name    | H               | Jozef A. Slowik
 21352173 | aka            | K               | C. O. Webb
 21352301 | middle name    | R               | Kevin M. Kocot
 21352373 | middle name    | R               | J. Tomasz Giermakowski
 21352413 | middle name    | J               | Justin Fulkerson
(19 rows)
```

**Comment by Jegelewicz** [comment]
OK - those people are fixed. Can we make a rule that first, middle and last names that are only one letter must be followed by a period?

Also note that 

 agent_id | attribute_type | attribute_value |  creator         
-- | -- | -- | -- 
 21344739 | aka            | A               | C. O. Webb
 21352037 | aka            | O               | C. O. Webb
 21352173 | aka            | K               | C. O. Webb
 
now include some metadata with those akas.

**Comment by dustymc** [comment]
>names that are only one letter must be followed by a period

It occurred to me a while back that the thing which needs the period isn't exactly a name, even though that's the container we've been using for that sort of data forever. I think I want to go back to not realizing that, but there it is if anybody thinks it matters....

Anyway - Issue please. Seems like a good idea to me, I can certainly write the code, I need something (that isn't hiding down here) to point to.

**Comment by Jegelewicz** [comment]
Also, love that the three herbaria codes spell AOK

**Comment by dustymc** [comment]
I like to imagine that the 255th herbarium to join this thing was assigned [ÿ](https://www.ascii-code.com/CP1252/255)....

**Comment by camwebb** [comment]
> I think we can't expect there to be only one A so this would be a name, not identifier - not sure if that changes anything. IDK, help me understand??

But there _is_ only one 'A' - the acronym codes (many established 150+ years ago) for herbaria are unique and I imagine that the 'Code' field at GriSciColl is also unique. We remember herbaria by their codes. Often the main name entered into Arctos is only one of a number of possible names. So it would be very helpful to have a field that stores only the 'official' code for an institution to look up the institution by. As before, `aka` will now work, so that may be the solution chosen, but I maintain that asking to create a field for the standard codes of collections-holding institutions is a useful proposal.

**Comment by Jegelewicz** [comment]
> the 'Code' field at GriSciColl is also unique

Nope! GRSciColl relies on an internal index because the collection/institution codes are definitely NOT unique.

https://scientific-collections.gbif.org/institution/search?code=MNHN

**Comment by camwebb** [comment]
> definitely NOT unique

Okay - didn't know this. **Index Herbariorum** codes (which are what I am interested in) _are_ unique, but perhaps this is an edge case for most Arctos users? ... Although there is a dedicated field for botanical Author abbreviations. 

I'm get a sense that this is not a CT addition that anyone else is interested in...

**Comment by camwebb** [comment]
The '=AKA' method is working well now, even from the originating tab-complete box (e.g., entering '=ALA' in IssuingAgent and tabbing auto fills the full info). So let's drop this. Closing. Thanks for the input.
