### ISSUE TITLE
cannot add a login name to an existing agent

### ISSUE THREAD

**Issue by amgunderson** [ArctosDB/arctos#7674]
**Describe the bug**
I need to add an arctos login name to an existing agent but the name=login is not an option on the edit agent page.
<img width="245" alt="Screenshot 2024-04-12 at 10 51 03 AM" src="https://github.com/ArctosDB/arctos/assets/8440698/b53a153c-bcb3-4fbe-bb82-adbb352dbc38">

**To Reproduce**
try to edit an agent and add a login name.

I need to do this to enable user management and get. new staff person the power to use arctos.

Priority high, I cannot do things now... a black hole of despair.

**Comment by dustymc** [comment]
>need to add an arctos login name

Nope, https://handbook.arctosdb.org/documentation/users.html - just invite them, that's part of the process now.

**Comment by amgunderson** [comment]
I did and got an error saying there was no login linked to that agent. I'll try again later.

**Comment by amgunderson** [comment]
Okay it worked, thank you
