### ISSUE TITLE
Feature Request - Find all Sciuridae with Arthropod parasites

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7675]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

From today's genomic resources working group meeting. 

**Describe what you're trying to accomplish** 
_A clear and concise overview of the goals; why are you asking for this?_

@campmlc wants to find all Sciuridae with Arthropod parasites, so we attempted the search. Here is what we did.

https://arctos.database.museum/search.cfm?customoidoper=LIST&id_references=host%20of&related_item_identification=Arthropoda&family=Sciuridae

![image](https://github.com/ArctosDB/arctos/assets/5725767/1fadc60c-60bf-4c9b-8176-5feffc1650cf)

This gets only the hosts with related records identified as Arthropoda, not all Arthropoda.

**Describe the solution you'd like**
_How might we accomplish your goals?_

Is there a way to do this search that is evading us? If not, I am thinking we need to be able to refine the Related Item Identification such that it can search specific classification terms or specifically identifications.

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**
_Add any other context or screenshots about the feature request here._

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._

**Comment by campmlc** [comment]
Upping priority as this is needed for a final grant report that has provided Arctos funding. Any ideas how this can work? We used to have this functionality.

**Comment by DerekSikes** [comment]
Pretty sure the search is currently impossible, or at least unreliable, until Flat higher taxonomy is repaired. See https://github.com/ArctosDB/arctos/issues/7699

I'm surprised how little attention that issue has received. To me it's a wildfire!

**Comment by mkoo** [comment]
This is the specific kind of request we want to make easy in a dedicated relations (parasites, disease etc) portal.... I still havent made issues for this yet but will soon.

**Comment by campmlc** [comment]
@mkoo our grant report is coming due - can we do a call to discuss this?

**Comment by campmlc** [comment]
See proposed solution in #7752

**Comment by mkoo** [comment]
This easy to do now -- thanks to https://github.com/ArctosDB/arctos/issues/7695, https://github.com/ArctosDB/arctos/issues/7725 (cleaning up CT in #7752 will help with reliable results)

https://arctos.database.museum/search.cfm?related_id_references=parasite%20of&related_item_taxonomy=Arthropoda&taxon_name=Sciuridae

(your log in may filter your results)
