### ISSUE TITLE
Warning! Prepopulated information causes unexpected results in data entry pull

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7677]
@bryansmclean was having issues pulling data from mammal records into new parasite records. After attempting this myself, I think I see the problem.

**To Reproduce**
1. Go to data entry
2. Click on a profile

![image](https://github.com/ArctosDB/arctos/assets/5725767/6aa50838-cdf8-4a8a-b807-c8499e0acc5c)

3. Scroll down to the pull button at identifiers
4. Look out for prefilled information!

![image](https://github.com/ArctosDB/arctos/assets/5725767/261f4e37-a388-4f1a-8f59-c57d1483c984)

If there is anything prefilled in the identifier section it fills the pull form. You may not find the record you want to pull from because this prefilled info is not found in that record. Everything is working as expected, but users may not know why they aren't getting what they expect.

@campmlc

**Comment by campmlc** [comment]
Agree this should be removed as a default value for the pull function or have the prefilled cells highlighted to make them totally obvious

**Comment by campmlc** [comment]
Removing prefills as default makes more sense, as if this info is known there is no need to pull it. . .

**Comment by dustymc** [comment]
>default

There are no defaults.

>Everything is working as expected

Agreed.

**Comment by campmlc** [comment]
So if this is "just UI" , as a UI problem, how about a UI solution: Can we request that the prefilled fields be highlighted, for example, if the issued by is autopopulated by some value from the previous form, then that field would highlight yellow? That way people would more easily notice an autopopulated value that they did not actually type.
