### ISSUE TITLE
UAM herbarium requesting a new collection and new collection type: mycological

### ISSUE THREAD

**Issue by camwebb** [ArctosDB/arctos#7679]
We are starting to accession some **fungal** collections, and so need a new collection prefix: `UAM:Myco` and (while the table lives) a new entry in `ctcollection_cde`: "Myco". 

The classification for the new names will be managed in 'UAM Plants'.

Before I can start the official new collection request (via Issue Template), it seems there needs to be an Issue in which the GUID prefix is discussed. Here it is. Any thoughts?

**Comment by dustymc** [comment]
>Here it is

```UAM:Myco``` is acceptable.


>ctcollection_cde

Don't think there's any reason to torture yourself....

**Comment by camwebb** [comment]
Thanks - will progress to the formal request.
