### ISSUE TITLE
[CHAS] request to add a new collection type: AV

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#7681]
We are starting the process of transferring the CHAS motion picture collection into Arctos. We are requesting that the new collection type be AV (for audiovisual) and that our collection use the guid CHAS:AV.

Thanks!

**Comment by dustymc** [comment]
I think this is unnecessary, unless you REALLY need some new functionality in the next week or two.

**Comment by acdoll** [comment]
Would it make sense to use Arch (Archives) for this?

**Comment by dustymc** [comment]
> use Arch

Sorry, I wasn't being clear. I'm working on https://github.com/ArctosDB/arctos-dev/issues/32 now, collection_cde won't DO anything once that's implemented, and a new value won't need to be accompanied by probably-dozens of code table requests.

Using some existing thing for the next couple weeks makes sense to me, unless there's some sort of timebomb which won't allow such luxuries.

**Comment by acdoll** [comment]
Thanks for the explanation. I was thinking about whatever MVZ uses for their Archives, but they use Teach or EH, don't they?

**Comment by dustymc** [comment]
>MVZ uses for their Archives

https://arctos.database.museum/collection/MVZ:Arch - yup, EH

**Comment by Jegelewicz** [comment]
@wellerjes if you want to set up a new collection, use https://github.com/ArctosDB/arctos/issues/new?assignees=Jegelewicz&labels=nodev%2C+Priority-Normal+%28Not+urgent%29&projects=&template=exisiting-institution-requesting-a-new-collection.md&title=%5BArctos+Institution+Name%5D+request+to+add+a+new+collection

Also, if there is nothing else to do here, please close this.
