### ISSUE TITLE
records with no not-unaccepted event

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#7686]
FYI. I had a bad join which broke the GBIF pipeline, perhaps the records are of some interest. Please note that these are not problematic as far as Arctos is concerned, they can stay as they are and there are many possible reasons for them to exist, if you're aware of these there's no problem.

Data (and SQL)

```
select guid from 
flat
left outer join specimen_event on flat.collection_object_id=specimen_event.collection_object_id and
    coalesce(specimen_event.verificationstatus,'NULL') != 'unaccepted'
where specimen_event.specimen_event_id is null
```
[temp_no_not_unaccepted_event.csv.zip](https://github.com/ArctosDB/arctos/files/15028449/temp_no_not_unaccepted_event.csv.zip)

Summary

```

  guid_prefix  |  c   
---------------+------
 ALMNH:Inv     |    1
 ALMNH:Paleo   |   87
 APSU:Herp     |   10
 Arctos:Entity |  281
 BYU:Edu       |    2
 BYU:Herp      |    1
 CRCM:Bird     |    2
 CRCM:Mamm     |    1
 DMNS:Bird     |    2
 DMNS:Mamm     |   32
 KSB:Mamm      |  146
 KSB:Teach     | 1190
 MLZ:Bird      |   19
 MSB:Bird      |    1
 MSB:Fish      |    4
 MSB:Herp      |   88
 MSB:Host      |    3
 MSB:Mamm      |  104
 MSB:Para      |   40
 MVZ:Fish      |    1
 MVZ:Herp      |  648
 NMMNH:Bird    |    6
 NMMNH:Paleo   |    1
 NMU:Mamm      |    1
 OGL:Genomic   |   32
 TCDGM:Mineral |  508
 TCDGM:Paleo   |   15
 UAF:Zooarch   |  293
 UAM:Arc       |  110
 UAM:Ento      |   96
 UAM:ES        |    1
 UAM:Fish      |    5
 UAM:Herb      |   15
 UAM:Inv       |    1
 UAM:Mamm      |  328
 UAMObs:Ento   |    4
 UCM:Bird      |    1
 UMZM:Bird     |    1
 UMZM:Egg      |    5
 UMZM:Mamm     |    3
 UTEP:Bird     |    3
 UTEP:Ento     |    1
 UTEP:Herb     |  272
 UWBM:Herp     |  787
 UWBM:Mamm     |   99
 UWBM:VP       |   22
```

contacts

 @jrdemboski
 @keg34
 @amgunderson
 @jldunnum
 @catherpes
 @msbparasites
 @AdrienneRaniszewski
 @campmlc
 @DerekSikes
 @StefanieBond
 @jtgiermakowski
 @ccwlobo
 @mlbowser
 @jandreslopez
 @adhornsby
 @sjshirar
 @mkoo
 @atrox10
 @jebrad
 @mvzhuang
 @acdoll
 @KatherineLAnderson
 @lin-fred
 @aklompma
 @ebraker
 @Jegelewicz
 @camwebb
 @Nicole-Ridgwell-NMMNHS
 @byuherpetology
 @kmkocot
 @jessicatir
 @ufarrell
 @falco-rk

**Comment by lin-fred** [comment]
Is there an option for when we don't have any locality info?

![image](https://github.com/ArctosDB/arctos/assets/19802479/927dd149-cd3e-4d22-a865-36c695f68e34)

**Comment by DerekSikes** [comment]
Is this because we no longer require a value on data entry? I use 'unverified' to find records to 'accept' - if there are now records with NULL, how will I find them to 'accept' them? I'd like to somehow require my data entry folks to enter 'unverified' at data entry - can I do that by customizing the data entry form?

**Comment by DerekSikes** [comment]
Looking at the data entry form, for 'record_event_verificationstatus' I see there is no longer an option for 'unverified' - the only options are 'accepted' 'unaccepted' and 'verified and locked' - and some of my people are confused and seem to have been loading records as 'unaccepted', which as I understand it is for rare cases when a specimen is recorded from a place but is not actually from that place. Can we get 'unverified' back as an option? This way I can find unverified records and verify them??

**Comment by amgunderson** [comment]
It seems "accepted" is the new "unverified" since verified is an option anything not marked verified can be assumed to be unverified.

**Comment by dustymc** [comment]
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctverificationstatus

NULL replaces unverified (and is how the vast majority of records should be entered).

NULL is searchable.

<img width="294" alt="Screenshot 2024-04-18 at 12 38 23" src="https://github.com/ArctosDB/arctos/assets/5720791/f07f55f5-8499-46a9-a433-75b04497134c">

https://github.com/ArctosDB/arctos/issues/7474

**Comment by lin-fred** [comment]
> That's one of the reasons for these data to exist. If for some reason you want a presence in DWC you'll need some sort of place-stack (Occurrences can't exist without), you can add one with a bunch of "IDK" values.

Ok I think I have fixed them

**Comment by ebraker** [comment]
The UCM record was recorded as "unaccepted" in error. Fixed!

**Comment by adhornsby** [comment]
I'm not seeing NULL as an option in data entry or when editing existing events.  Am I misunderstanding that we should be able to see and use NULL? 
<img width="226" alt="image" src="https://github.com/ArctosDB/arctos/assets/40217539/c941866a-acc3-4d8b-b327-3221e07b2f1f">
<img width="182" alt="image" src="https://github.com/ArctosDB/arctos/assets/40217539/6811f4f2-e295-4c4d-b019-6b90bd9806e1">

**Comment by campmlc** [comment]
My understanding is that you would leave it blank, and not be forced to choose a value.

**Comment by dustymc** [comment]
>data entry

Use what's checked in your screenshot.

>editing

Thanks, fixed in next release.
