### ISSUE TITLE
 Feature Request - simplify ctlocation_in_host

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#7689]
**Is your feature request related to a problem? Please describe.**

I think ctlocation_in_host could be simpler.

**Describe what you're trying to accomplish** 

Make things as simple as possible.

**Describe the solution you'd like**

Drop collection-specific term filtering.

**Describe alternatives you've considered**

Proceed with https://github.com/ArctosDB/arctos/issues/3452

**Additional context**

I'm struggling to see a situation in which a collection might want only some of these values. What am I missing?

**Priority**

I'll proceed with my assumptions unless someone enlightens me NOWish.

**Usage**

```

 collection | numrecs 
------------+---------
 NMU:Para   | 14|
 DMNS:Para  | 96|
 UMZM:Para  | 8|
 HWML:Para  | 99793|
 USNPC:Para | 352|
 MSB:Para   | 28924|
 UMNH:Para  | 132|


```

**Ping**

 @jrdemboski
 @keg34
 @gracz-UNL
 @msbparasites
 @campmlc
 @adhornsby
 @acdoll

**Comment by campmlc** [comment]
Agree. There is no need for filtering by collection type.
