### ISSUE TITLE
 Feature Request - simplify ctcaste

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#7690]
**Is your feature request related to a problem? Please describe.**

I think ctcaste could be simpler.

**Describe what you're trying to accomplish** 

Make things as simple as possible.

**Describe the solution you'd like**

Drop collection-specific term filtering.

**Describe alternatives you've considered**

Proceed with https://github.com/ArctosDB/arctos/issues/3452

**Additional context**

I'm struggling to see a situation in which a collection might want only some of these values. What am I missing?

**Priority**

I'll proceed with my assumptions unless someone enlightens me NOWish.

**Usage**

```

 collection  | numrecs 
-------------+---------
 UAA:Ento    | 203|
 CHAS:Ento   | 8|
 UAMObs:Ento | 1|
 KWP:Ento    | 1|
 KNWR:Ento   | 2|
 UTEP:Ento   | 543|
 UAM:Ento    | 3165|

```

**Ping**

 @DerekSikes
 @wellerjes
 @justybob
 @mlbowser
 @Jegelewicz
 @droberts49

**Comment by justybob** [comment]
Having the values of 'worker', 'queen', 'drone', etc. are valuable data to the specimens. I would like them retained for future analyses. I am fine if you wish to move the values to another field or other simplification. I'm not certain what you are proposing here @dustymc What is dropping the term filtering?

**Comment by DerekSikes** [comment]
I will second justybob's comment that we need to be able to use caste for insect specimens - can you clarify where the data will go & how we'll be able to use them (add, search, download, etc.)

**Comment by dustymc** [comment]
>what you are proposing

Removing..

<img width="115" alt="Screenshot 2024-04-19 at 13 20 05" src="https://github.com/ArctosDB/arctos/assets/5720791/79d5a480-6130-43a6-b11a-f03147bc17e9">

... from https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcaste.

I am proposing NOT adding the ability to make specific values (eg "king") unavailable to a specific collection. I'm proposing to NOT do what we've done with https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlife_stage, where "1st instar" is not available to the MVZ:Bird collection, but "adult" is. I don't think these authorities need that level of complexity.

**Comment by DerekSikes** [comment]
understood & approve.
