### ISSUE TITLE
Feature Request - drop table ctabundance

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#7691]
**Is your feature request related to a problem? Please describe.**

Abundance is an uncontrolled attribute. I think perhaps the code table is a failed experiment?

**Describe what you're trying to accomplish** 

Clean

**Describe the solution you'd like**

Drop the table.

**Describe alternatives you've considered**

Use the table.

**Additional context**

Some of these data are probably lost, https://github.com/ArctosDB/arctos/discussions/6179 is related.

**Priority**

Critical, I'll drop the code table unless someone has a use for it.

**Data**

[temp_abundance.csv.zip](https://github.com/ArctosDB/arctos/files/15041997/temp_abundance.csv.zip)

**Usage**

```

  collection  | numrecs 
--------------+---------
 UAM:Herb     | 480|
 KNWRObs:Herb | 30|
 UTEP:Herp    | 25|
 UTEP:Inv     | 7|
 MVZ:Bird     | 1|
 UWZM:Bird    | 78|
 UTEPObs:Herp | 1|
 MVZObs:Bird  | 564|
 DMNS:Bird    | 1|
 UAM:Ento     | 1|
 APSU:Herp    | 1|
 UTEP:Herb    | 125|
 UTEP:Ento    | 262|
 MSB:Herp     | 5|


```

**Ping**

 @DerekSikes
 @StefanieBond
 @jtgiermakowski
 @ccicero
 @mkoo
 @mvzhuang
 @acdoll
 @Jegelewicz
 @camwebb
 @gradyjt
 @ehalverson26

**Comment by ccicero** [comment]
@dustymc I'm a bit confused. We have [ctabundance](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctabundance) which is controlled, but the data you provide look like it's coming from 'abundance' in ctattribute_type - ??? I checked some of the MVZ records and those are from ctattribute_type = 'abundance'

So we have two ways of saying the same thing. I'm ok with dropping ctabundance but we need to keep abundance as a record attribute type. 

Can you send a CSV of values that use ctabundance?

**Comment by dustymc** [comment]
@ccicero you got it, two things here:

1. A free-text attribute, https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#abundance and
2. A code table with a suspiciously similar name which, as far as I can see, isn't doing anything at all - https://arctos.database.museum/info/ctDocumentation.cfm?table=ctabundance

I'm not proposing doing anything with the attribute.

I am proposing either

1. getting rid of the code table if nobody has a use for it, or
2. wiring it in wherever it should be if someone has a reason to do that

Data are in the original comment.

**Comment by ccicero** [comment]
@dustymc The data in original comment looks like it's coming from ctattribute_type#abundance - no? The column is ATTRIBUTE_TYPE = 'abundance' and the values are not controlled, so  what are the records with data from ctabundance? That's unclear to me.

**Comment by dustymc** [comment]
>records with data from ctabundance

As far as I know there are none.

**Comment by ccicero** [comment]
Hmmm, ok. Then I vote for getting rid of ctabundance and just keeping ctattribute_type#abundance.

**Comment by gradyjt** [comment]
APSU only has one record on this issue list so, small beans, but upon
inspecting I'm not even sure what that number is in relation to the record
so APSU is good to go with whatever is decided. -Jessica

**Comment by dustymc** [comment]
>not even sure what that number is

Bare integers aren't the most ridiculous things in these data! https://github.com/ArctosDB/arctos/discussions/6179 - I am increasingly convinced that we wildly underestimate the costs of simply having lots of THINGS (eg some poor overwhelmed student puts A-thing into Z-container and it's lost).

**Comment by gradyjt** [comment]
I agree 100 as the kids say these days...
