### ISSUE TITLE
Create Record left record in limbo?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#7696]
Issue: I used Create Record to enter a single record for Mexican wolf studbook 1949.
This record is part of MSB accession 2022.046.Mamm. Once I entered it, I went to Browse and Edit, found the record under the accession, and marked to load. After a short while, the record and the accession disappeared from Browse and Edit, and I assumed was loaded. But when I went to search on the record using the studbook number it was not found. I searched on the accession, but there are no records in the accession.
Then I searched on the barcode in Find Container, which showed that there is now a new part, MSB:Mamm:351750 blood, associated with the barcode. But this part does not link to a record, and the guid does not show up in Search. If I search on the barcode using Search, Arctos says there is 1 of 1 record, but doesn't show any result. I thought I'd wait 24 hours and see if it resolved, but it's the next day and it's still not showing up.

I assume this record is trapped in limbo somewhere between existence and non-existence. Should I worry I've created a record zombie?
Need to be shipped on loan tomorrow, so I'm hoping it materializes. Help?

![Screenshot 2024-04-21 13 54 54](https://github.com/ArctosDB/arctos/assets/14808196/d745d2d0-0452-487d-826b-d3207a4bc06c)

**Comment by dustymc** [comment]
<img width="94" alt="Screenshot 2024-04-22 at 05 22 55" src="https://github.com/ArctosDB/arctos/assets/5720791/7eec4d00-0f09-4f9d-bd40-a370233c2c73">

**Comment by campmlc** [comment]
well, that explains a lot. I certainly didn't sign in to test consciously. Somehow I have browser windows open in test and others in production. Definitely a source of confusion.

**Comment by campmlc** [comment]
But shouldn't I be able to catalog a record in test and actually see it? Or is that not allowed in test?
