### ISSUE TITLE
Media - view more objects in catalog record?

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#7697]
I have a number of records that contain five media objects. The Catalog Record Media data block only displays four objects, and users must click "next" to view additional items. However, when viewing records on my laptop (small screen) vs large monitor, there always seems to be a large space after the fourth object that would accommodate the fifth object. Is there a way to display these together versus having to page over to view the fifth object? They would look so nice displayed together and users would be less likely to miss the additional object stored on the "next" page.

![image](https://github.com/ArctosDB/arctos/assets/11336485/09bddee0-bd4b-4682-bcd4-fdc5cb0c8238)

![image](https://github.com/ArctosDB/arctos/assets/11336485/41ade779-0f14-4103-8c44-e87e56b7d47e)

**Comment by dustymc** [comment]
I can muck around (and probably break whatever I was looking at when I built it thataway...), but the real answer involves https://github.com/ArctosDB/arctos/discussions/4343 - I don't think I can swap in any sort of decently-modern viewer as long as I have to deal with unpredictable inputs, my little home-grown thingee has all sorts of limitations, this all just seems a silly situation to find ourselves in 2024!

**Comment by ebraker** [comment]
Well I hope nothing breaks but appreciate you seeing what you can cobble together!
