### ISSUE TITLE
higher taxonomy not showing in FLAT

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#7699]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
First noticed this last Friday, clicked cache refresh for some records, on Monday, noticing it with other records. 

See attached data - all these columns should have taxonomic names in them but are null:

phylum	phylclass	superorder	phylorder

[ArctosData5K3SlJvjAG.csv](https://github.com/ArctosDB/arctos/files/15068633/ArctosData5K3SlJvjAG.csv)

I also can't find these records via a search on order = Ephemeroptera
Accession = osf

Not sure how many other records have lost their higher taxonomy in FLAT but this problem is worrying because just repairing the lost data only fixes the symptoms - how do we prevent random loss of higher taxonomy from ever happening again?

**Expected behavior**

Searching on higher taxonomy will find records that have that higher taxonomy.

![Screenshot 2024-04-22 at 1 17 26 PM](https://github.com/ArctosDB/arctos/assets/9099827/dd69e582-9876-4529-93bb-e807c69a5958)

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.
high

**Comment by DerekSikes** [comment]
![Uploading Screenshot 2024-04-22 at 1.23.59 PM.jpg…]()

**Comment by dustymc** [comment]
Merging with https://github.com/ArctosDB/arctos/issues/7695.

>how do we prevent random loss of higher taxonomy from ever happening again

Hire a QA engineer and give them whatever resources they need. (But nothing has been "lost," it's just missing from the cache.)

**Comment by DerekSikes** [comment]
Search is still failing: https://arctos.database.museum/search.cfm?phylorder=Ephemeroptera&accn_number=osf

**Comment by DerekSikes** [comment]
When will the higher taxonomy be fixed? I just got a request for a report from the National Park Service and need to tell them when they can expect it. Thanks.

**Comment by mkoo** [comment]
i think this was updated a few days ago but working now
![Firefox_Screenshot_2024-05-07T03-06-15 343Z](https://github.com/ArctosDB/arctos/assets/2523089/cf9412ab-ba27-40fe-8b14-c98da806c067)
