### ISSUE TITLE
Feature Request - add metadata to agent creation form

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7703]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

I create an agent with a Wikidata ID and I cannot add any metadata

**Describe what you're trying to accomplish** 
_A clear and concise overview of the goals; why are you asking for this?_

Add appropriate metadata on creation

**Describe the solution you'd like**
_How might we accomplish your goals?_

add begin date, end date, determined, determiner, method and remark to the form

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

keep creating stuff that I forget to edit or cannot edit (Wikidata ID cannot be edited)

**Additional context**
_Add any other context or screenshots about the feature request here._

Nothing allows me to add metadata

![image](https://github.com/ArctosDB/arctos/assets/5725767/0f2b628e-6bb4-43e2-a24f-7e8ed20cde2a)

and once I have added Wikidata in this form, I can't add any metadata

make correction - 
![image](https://github.com/ArctosDB/arctos/assets/5725767/a2099310-216c-43d7-baf5-38eff61a769b)

get error

![image](https://github.com/ArctosDB/arctos/assets/5725767/a0c0a54d-7201-4e88-926e-5dea112246ec)

Message: ERROR: Identifiers must be unique. Do not create duplicate agents. Please carefully search before continuing. https://www.wikidata.org/wiki/Q3463654 Where: PL/pgSQL function trigger_fct_tr_agent_attribute_biud() line 99 at RAISE
SQL: insert into agent_attribute ( agent_id, attribute_type, attribute_value, begin_date, end_date, related_agent_id, determined_date, attribute_determiner_id, attribute_method, attribute_remark, created_by_agent_id, created_timestamp, deprecated_by_agent_id, deprecation_type, deprecated_timestamp ) ( select agent_id, attribute_type, attribute_value, begin_date, end_date, related_agent_id, determined_date, attribute_determiner_id, attribute_method, attribute_remark, created_by_agent_id, created_timestamp, 21300608, 'update', current_timestamp from agent_attribute where attribute_id=360467 )

This has become a big pain for me and I assume it means a lot of metadata just gets left out.

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._

**Comment by dustymc** [comment]
>cannot add any metadata

Now you can. 

https://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html#pro-tips

The create form can be different, I'm not sure if that's still a request, I'd need specifics.
