### ISSUE TITLE
The Agent "merge" template should be updated

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7705]
> @ArctosDB/agents-committee this template should be updated; there is no 'merge' in the model. The template is probably still useful for facilitating intercollection communication, but the way to respond has changed and the language should probably change.
> 
> A person should transfer any useful data from the bad agent to the good agent, then create a 'bad duplicate of' relationship from the bad. Anyone using the 'bad' will get a periodic notification. Records can be moved from one agent to another using the Manage/Agents option in the search results tools menu.

_Originally posted by @dustymc in https://github.com/ArctosDB/arctos/issues/7685#issuecomment-2064778051_

`This template` refers to https://github.com/ArctosDB/arctos/issues/new?assignees=&labels=Function-Agents&projects=&template=agent-merge-request.md&title=Agent+Merge+Request

**Comment by dustymc** [comment]
templates updated
