### ISSUE TITLE
Need Help with Arctos Error

### ISSUE THREAD

**Issue by ridabrams** [ArctosDB/arctos#7706]
# Error Text
"insert or update on table "specimen_event" violates foreign key constraint "fk_specimenevent_ctverifstatus" "

# Where it happened
Bulkloader

# Steps to get there
Data came from CSV and had been checked with bulkload validator- no errors came up at that time.

# Problem

# Solution

**Comment by dustymc** [comment]
Valid values are in https://arctos.database.museum/info/ctDocumentation.cfm?table=ctverificationstatus. You probably want NULL.

I'll check the checker.

**Comment by dustymc** [comment]
The checker should be making better errors now.
