### ISSUE TITLE
bulkloader data

### ISSUE THREAD

**Issue by hannahb2402** [ArctosDB/arctos#7707]
Hello, 
I contacted the person attached, to delete their data from the bulk loader, and they haven't responded to my email. Is it possible to remove the data from the bulkloader?
Thank you so much!

[bulkloader_stage (15).csv](https://github.com/ArctosDB/arctos/files/15094856/bulkloader_stage.15.csv)

@ridabrams

**Comment by Jegelewicz** [comment]
@hannahb2402 the bulkloader is clear now.
