### ISSUE TITLE
data not showing up in search results

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#7708]
I'm trying to pull data for a mail merge from these search results; the Family is not showing up:
![image](https://github.com/ArctosDB/arctos/assets/93737929/ef665047-ca7a-4b5a-a80d-d64461817823)

I thought it was an issue of the data not existing in the taxonomic source, but when I go into the catalog record:
![image](https://github.com/ArctosDB/arctos/assets/93737929/d9f4d84b-a9c4-43d6-bbf9-c5d759270ea7)

The data is being pulled from Arctos Plants and the Family is documented. I checked flat status and everything is current:
![image](https://github.com/ArctosDB/arctos/assets/93737929/1a5c6e85-1266-4d81-b926-e44994b2907c)

Is there another reason why this data isn't showing up in search results?

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/7695

There's a bug, I need guidance to fix it (and maybe make some other stuff better), should be on tomorrow's agenda.
