### ISSUE TITLE
Locality Edit - change specimen event?

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#771]
From @DerekSikes:

Edit Locality has an option to "push my agent + today's date to specimen events."

1) Should that be the default option?
2) Should that be the default, with no option to do otherwise?

**Comment by Jegelewicz** [comment]
> Edit Locality has an option to "push my agent + today's date to specimen events."

As part of #1708 I would like the option of adding a new event (the georeference) rather than just changing the old one.
