### ISSUE TITLE
Feature Request - filter reports

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#7711]
**Is your feature request related to a problem? Please describe.**

 bad joins in reports are fully capable of killing the box.

**Describe what you're trying to accomplish** 

keep Arctos alive

**Describe the solution you'd like**

Magic? 

**Describe alternatives you've considered**

Some sort of filter, limit, check, whatever works

**Additional context**

**Priority**

High, is fatal.

**Comment by Jegelewicz** [comment]
Glad I could be of service!
