### ISSUE TITLE
Feature Request - Make person names consistent

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7713]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

See https://github.com/ArctosDB/arctos/issues/7673#issuecomment-2075773341

Some names that were only initials did not include a period.

**Describe what you're trying to accomplish** 
_A clear and concise overview of the goals; why are you asking for this?_

Make people names in Arctos consistent.

**Describe the solution you'd like**
_How might we accomplish your goals?_

Names of type first, middle and last that are a single letter should require a period following them. Make a rule so that this is caught when agents are created.

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

Keep cleaning up stuff and making it hard for @camwebb to find the herbaria codes

**Additional context**
_Add any other context or screenshots about the feature request here._

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._

**Comment by dustymc** [comment]
I say we just do this unless someone has a timely and defensible objection. Very tentatively going next task.

**Comment by ewommack** [comment]
Does a period designate that there is a further name after the single letter? What about names that are just one letter for part of it?
@AJLinn - have you come across names that are just letters?

**Comment by AJLinn** [comment]
> have you come across names that are just letters?

I have plenty of agents who sign their works in just letters, but all those I can see in my list of agents that were verbatimized (and so were presumed low-quality) are likely abbreviations for complete names.
