### ISSUE TITLE
Need Help with Arctos Error: Create fail in Agent bulkload

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7714]
# Error Text
**Copy the text from the page and paste it here**

create fail

# Where it happened
**Provide a link to or a description of the page where the error occurred.**

https://arctos.database.museum/loaders/bulkload_agents.cfm

# Steps to get there
**Describe the actions that led to the error**

It's still there

# Problem
**Community response to describe the problem that caused the error**

What did I do wrong?

# Solution
**Community response with directions for how to correct the problem**

**Comment by dustymc** [comment]
>What did I do wrong?

You didn't, I just asked for some help, I can force these in for you if necessary or hopefully I'll have a better solution in a bit.

**Comment by Jegelewicz** [comment]
No rush - they aren't immediately needed. Thanks!

**Comment by Jegelewicz** [comment]
Sorry - I take a few days off and I get antsy....

**Comment by Jegelewicz** [comment]
I have some other agents I'd like to get loaded. Is this fixed?

**Comment by dustymc** [comment]
No, the wildfires have been particularly fire-ey lately and my hopes of suckering someone else into figuring out auth didn't (yet?) pan out. I was hoping to look at this today but I'm still running around chasing brushfires and it's well after noon (and I probably ought to find food)....

I can still manually load, I think, if that becomes necessary.
