### ISSUE TITLE
Enter from seed ("[enter]") on browse and edit page not working

### ISSUE THREAD

**Issue by kmkocot** [ArctosDB/arctos#7716]
Good morning,

I am trying to enter a record starting from a seed record using the Browse and Edit page. When I click "[edit]" under the "key" column for a given record on the Browse and Edit page (e.g., ALMNH:Inv:25751), I get the following error:
ERROR_ID 	1964E2DC-5360-4739-AA0AB42404F4FD7D
ERROR_TYPE 	SQL
ERROR_MESSAGE 	ERROR: column ctattribute_type.guid_prefix does not exist Position: 88
ERROR_DETAIL 	
ERROR_SQL 	select attribute_type from ctattribute_type inner join bulkloader on ctattribute_type.guid_prefix=bulkloader.guid_prefix where bulkloader.key='key_4595027' order by attribute_type

I don't understand because the GUID prefix field is completed.

Also, the text in the box at the top right of that page seems to need some updating ("enter from seed" doesn't exist but there is "[enter]" and "old edit" no longer exists).

Sorry in advance for doing something dumb but we are stuck.

Kevin

**Comment by dustymc** [comment]
Thanks, patched.
