### ISSUE TITLE
Agent cleanup - Tim Wheeler

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7719]
From https://github.com/ArctosDB/arctos/issues/7649#issuecomment-2076031141

Are these the same person?

agent_id | agent_type | preferred_agent_name |       creator       |        created_date        
 -- |  -- | -- | -- | -- 
 21352417 | person     | Tim Wheeler          | Mariel L. Campbell  | 2024-04-24 13:52:16.752771
 21282782 | person     | Tim Wheeler          | Jordan Metzgar      | 2014-10-22 15:45:14

If not, please merge them, if yes, please add the not the same as relationship.

@campmlc @camwebb

**Comment by campmlc** [comment]
I don't know if they are the same person, which is why I created a new one as a ship to agent for a mammal loan going to University of Montana.. Jordan created the first one related to the UAM herbarium.

**Comment by campmlc** [comment]
I have no means of knowing either one. I checked the U Montana website which just lists him as Senior Researcher with no other info. I have no idea if he was ever in Alaska. This is beyond my ability to determine given my available time and resources. But I had to ship the loan to the Montana Tim Wheeler, and I didn't want to add his address and email to the poor quality  Alaska agent.

**Comment by adhornsby** [comment]
@campmlc Tim Wheeler at Montana is a lichenologist, and he's currently helping to manage Jeff Good's [mostly] mammalogy lab.  So yes, based on this I'd say you have the same Tim Wheeler that Jordan created while at UAM.

**Comment by campmlc** [comment]
Oh good, I'll fix it then. But this does beg the question of what level of effort/steps are required in these situations? I chose to err on not conflating a known agent with valid metadata with an unknown agent with virtually nothing in a different state. What is the preference here?

**Comment by dustymc** [comment]
> level of effort/steps are required 

Trying to answer that is why https://github.com/ArctosDB/arctos/issues/7649 exists. (Currently the requirements are near nil.)

>What is the preference here?

I pretty strongly suspect that Tim Wheeler's preferences involve getting proper attribution for his work and contributions, but of course I can't say how much of that must or should be on Arctos (the system) or you (the collections), and nowadays Tim could make this easy by giving us an ORCID (and we're all requiring those be provided for and included in publications resulting from loans, right?!).

**Comment by campmlc** [comment]
I also think Tim would not want to be conflated with someone who wasn't him, or that the someone who wasn't him would object to being conflated with the wrong person. Yes, in the best of all possible worlds, we'd have ORCIDs etc. But we are not there yet. I was told by a curator to just "send this loan to this guy in Montana. Here is his address". I fight this battle every day, and rarely win, even in the museum world. It's exhausting.

**Comment by Jegelewicz** [comment]
I think what happened here is the way to handle these things?

**Comment by Jegelewicz** [comment]
@campmlc I can "merge" these and cleanup your end if you want me to - just let me know. Once that is done, we can close this.

**Comment by dustymc** [comment]
>Tim would not want to be conflated

Agree, and for the sake of clarity:

* if there are multiple agents representing one entity, the entity essentially cannot get proper attribution, and 
* if there are multiple entities represented by one agent, the entities essentially cannot get proper attribution, and 
* combos of those things are - well, we all know...

>reality

Yup, but sometimes proper tools/documentation/outlook/???? can, I think, shape that a bit. (We're all here and I think an agent just got better!) "What can I realistically do to help?" is kinda always my fundamental question, however poorly I manage to hurl that towards any given situation. As far as Agents are concerned, my current understanding is basically "get the hell out of the way" - comments on https://github.com/ArctosDB/arctos/issues/7649 might change that, if anyone has any interest in doing so.

>administrations

Also agree - this isn't going to be solved by Arctos (but we can provide tools), and it's probably not going to be solved by anyone who doesn't have at least the power of creating and enforcing loan agreements (but maybe we can leverage the folks who'd like attribution from the trenches to influence them).

>understood

Time for another publication?!

**Comment by dustymc** [comment]
>what happened here is the way to handle these things?

No disagreement from me (pending some sort of agent-shaping guidance from The Community), maybe having that in a Best Practice would be useful.

**Comment by campmlc** [comment]
Thanks - @Jegelewicz please feel free to merge if you can get to it before I do.

**Comment by Jegelewicz** [comment]
Done. Remaining agent - https://arctos.database.museum/agent/21282782
