### ISSUE TITLE
unable to upload part bulkload file

### ISSUE THREAD

**Issue by AdrienneRaniszewski** [ArctosDB/arctos#7721]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
can't upload file for part bulkload

**To Reproduce**
attach csv
click "upload this file"
get error

**Expected behavior**
for it to load

**Additional context**
below is the error I get. is my username (AdrienneR) causing issues again? Is it possible for you to just change it to all lower case?

lucee.commons.cli.CommandException: psql:/usr/local/webroot/temp/excopy_adrienner_2024042512044590_210.sql:9: ERROR: insert or update on table "cf_temp_parts" violates foreign key constraint "cf_temp_parts_username_fkey" DETAIL: Key (username)=(adrienner) is not present in table "cf_users".

**Comment by dustymc** [comment]
data please

**Comment by AdrienneRaniszewski** [comment]
[2023.027-extra-parts.csv](https://github.com/ArctosDB/arctos/files/15118947/2023.027-extra-parts.csv)

**Comment by AdrienneRaniszewski** [comment]
any luck?

**Comment by dustymc** [comment]
Sorry, 8 million fires to put out, I'll try to get this today or I can probably force it through as me if you're in a huge hurry.

**Comment by Jegelewicz** [comment]
FWIW @KatherineLAnderson was having the same issue on Friday.

**Comment by dustymc** [comment]
@AdrienneRaniszewski @KatherineLAnderson this should be patched, please test and confirm as I'm still working behind some limitations. (One of those fires turned into an outright conflagration....)

**Comment by KatherineLAnderson** [comment]
It's fixed on my end! Thanks Dusty!

**Comment by AdrienneRaniszewski** [comment]
I was able to upload the file, but I can't actually load the parts. I think it's a different problem, but I don't understand the error message. It's in the parts bulkloader, if you want to take a look. user AdrienneR. Thanks!

**Comment by dustymc** [comment]
Thanks, bugfixed (I hope, and you can't check because TACC-things, but I'll try to get a patch out tonight....)

>recognizing part names.

<img width="972" alt="Screenshot 2024-05-02 at 15 39 51" src="https://github.com/ArctosDB/arctos/assets/5720791/7282cf53-6d89-4f6c-a919-80a44b53466e">

 collection settings at the top of https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name, or there's a link in manage collection.

I don't think that's documented - @Jegelewicz ??

**Comment by Jegelewicz** [comment]
@KatherineLAnderson you need to select the parts you want to use - see https://drive.google.com/file/d/1nmCFYhNaX5z3VM8_8UZXZ_MszdsQskJy/view?usp=drive_link

**Comment by dustymc** [comment]
Assuming everything's all happy....

**Comment by AdrienneRaniszewski** [comment]
Yes! All happy now. Thank you!
