### ISSUE TITLE
Feature Request - allow selection of personal preferred identifier by issuing agent

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7723]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

I can select an agent type to display for myself, but the transition to issued by means I would rather use that as the selection tool (there are lots of thing with type = identifier and I just want to see issued by Teresa J. Mayfield-Meyer) :-)

**Describe what you're trying to accomplish** 
_A clear and concise overview of the goals; why are you asking for this?_

Get the preferred identifier I want

**Describe the solution you'd like**
_How might we accomplish your goals?_

Allow selection of preferred identifier by issuing agent from https://arctos.database.museum/myArctos.cfm

![image](https://github.com/ArctosDB/arctos/assets/5725767/a64c6219-6c95-4e6d-8180-af14fae8de54)

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

Never see my identifier in the record summary....

**Additional context**
_Add any other context or screenshots about the feature request here._

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._

**Comment by dustymc** [comment]
Is there a specific and compelling use case? 

I want to just say "sure," but also the customID thing has been looking unsustainable for a while. (It was developed for ALA - one type - and there are currently 128 - many of which don't exist! - in use.) I'm not sure that "oo, pretty!" should justify this (not sure it shouldn't either), would be good to proceed with some sort of a sustainability-slanted big-picture plan if this advances. (Limiting the choices to things cached in flat might do it, for example - but also likely excludes the stated use case.)
