### ISSUE TITLE
Feature Request - reorder columns in identifier section of catalog records

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7724]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

The issuer of an identifier appears after the identifier. I think the order should be reversed.

**Describe what you're trying to accomplish** 
_A clear and concise overview of the goals; why are you asking for this?_

Provide context for an identifier before people read the identifier

**Describe the solution you'd like**
_How might we accomplish your goals?_

 Instead of this
![image](https://github.com/ArctosDB/arctos/assets/5725767/a83f42b0-0bd1-42de-8b52-04201ec09e89)

This
![image](https://github.com/ArctosDB/arctos/assets/5725767/18191e04-a2e9-49f0-9c8f-47710a6cb727)

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**
_Add any other context or screenshots about the feature request here._

If I want to use the issued by name as a prefix to my identifier, this makes it work.

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._

**Comment by ewommack** [comment]
I like it. It makes it seem more like the IssuedBy agent is providing the identifier, rather then adding the Agent at a later date.

**Comment by dustymc** [comment]
Briefly discussed somewhere, whoever was there seemed to think this was a good idea, tentatively going next task....

>the IssuedBy agent is providing the identifier, rather then adding the Agent at a later date.

Precisely!

And that's how it's ALWAYS been - the 'traditional' "SA 123" format that @adhornsby brought up in the meeting yesterday is just a really primitive way of saying "123, assigned by Some Agent." We just finally noticed and formalized that, and now it's possible to ***use*** 123 (which sorts and filters nicely) plus an agent-object (which can bring deep information of its own), and never have to wonder if that's Some Agent or Samuel Adams (or the other Sam Adams - does he go by Samuel??) or someone else, nor wonder if SA123 and SA-123 and SA: 123 and SA 123 and ..... have any relationship to each other, and etc. ad nauseum.

It's even possible that identifiers issued by certain agents could have structural requirements (eg, be integers, follow some pattern, be URIs or URLs, whatever), should someone want to file an issue.
