### ISSUE TITLE
permission denied to update collection attributes

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#7728]
# Error Text
<html><body>

ERROR_ID | 48E534AD-922F-4662-A3A24D999D4CE0AD
-- | --
ERROR_TYPE | SQL
ERROR_MESSAGE | ERROR: permission denied for table ctattribute_type
ERROR_DETAIL |  
ERROR_SQL | update ctattribute_type set  								collections=string_to_array('CHAS:AV,CHAS:Art,CHAS:EH,UAM:Art,UAM:EH',',')  								where attribute_type='copyright status'

</body>
</html>

# Steps to get there
Manage Collections - pick a collection - manage attributes - select new attribute and save - permission denied error

Note: Problem is not unique to CHAS:AV, like https://github.com/ArctosDB/arctos/issues/7727; I've tested it on a few different collections and get the same error each time.

**Comment by dustymc** [comment]
patched

**Comment by wellerjes** [comment]
Thanks!
