### ISSUE TITLE
Firefox doesn't like pop-ups

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#7730]
![Screenshot 2024-04-26 115857](https://github.com/ArctosDB/arctos/assets/93737929/385b5482-a07a-4a7b-af5d-7ed4c5346188)

Just started getting this error message when trying to edit anything that opens up in a pop-up window. I've tried different computers, different browsers, logging out and back in, etc. It is also happening for our volunteers too, so it's not just my account. When I click on "Open Site in New Window", I get this message:

![image](https://github.com/ArctosDB/arctos/assets/93737929/cd68dfeb-a75d-4aaf-9425-544a1dc3f185)

**Comment by adhornsby** [comment]
Pop-ups for agents specifically also don't seems to be working on Chrome.  Other pop-ups are functioning (parts, accessions, etc.).
<img width="464" alt="image" src="https://github.com/ArctosDB/arctos/assets/40217539/39c2935b-9541-4686-b127-f515d859fec9">

**Comment by mkoo** [comment]
Please see https://github.com/ArctosDB/arctos/issues/7729
These are likely due to the network issues that are currently being addressed. Sorry for the hassle!

**Comment by DerekSikes** [comment]
Same problem here. I can't use Arctos because of this!
