### ISSUE TITLE
Edit Identifiers and Relationships on Catalog Record page not working

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#7731]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Trying to edit an identifier from the catalog record page. Click Edit - and get a popup with this error:

arctos.database.museum refused to connect.

**Expected behavior**

**Screenshots**

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by campmlc** [comment]
In the broader context, I'm trying to fix these broken links between Arctos catalog records. There are many. Help?
https://arctos.database.museum/guid/MSB:Para:45864

**Comment by mkoo** [comment]
Please see https://github.com/ArctosDB/arctos/issues/7729
You and others may be experiencing temporary connection issues while TACC works out the network issues
