### ISSUE TITLE
5/31: Arctosdb.org  - non-database website will be offline for system upgrades

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#7732]
## Planned Outage
 - Date and time outage: May 31, 2024  4:30 a.m. through 7:30 p.m (Pacific)
 - Reason for outage: UC Berkeley data center where Arctosdb.org is hosted, will have mechanical and electrical system upgrades
 - Expected behavior during and after the outage: Only the non-database website Arctosdb.org will be unavailable during this period. The database and the handbook will function as normal.

## Communication before/during outage
- [x] Pin this issue
- [x] Banner updated @jegelewicz @mkoo
- [x] Email sent to AWG  
- [x] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [ ] Unpin this issue
- [x] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by lin-fred** [comment]
scheduled a tweet

**Comment by Jegelewicz** [comment]
I set a reminder for myself to update the Arctos Banner on May 27

**Comment by ewommack** [comment]
Scheduled emails to go out one week before, the Monday before, and the day before.

**Comment by Jegelewicz** [comment]
Banner added to expire end of day May 31.

> ArctosDB.org will be down from May 31, 2024 4:30 a.m. through 7:30 p.m (Pacific) as the UC Berkeley data center where Arctosdb.org is hosted, will have mechanical and electrical system upgrades. Only the non-database website Arctosdb.org will be unavailable during this period. The database and the handbook will function as normal.

**Comment by Jegelewicz** [comment]
Also added event to the Arctos Calendar

**Comment by mkoo** [comment]
Update: the data center has indefinitely postponed their work and the shutdown has no new date-- closing!
