### ISSUE TITLE
Code Table Request - Change pelvic girdle and pectoral girdle to girdle and add pelvic or pectoral as part modfier to all existing parts using the related part name

### ISSUE THREAD

**Issue by KatherineLAnderson** [ArctosDB/arctos#7733]
### Goal
Request to add girdle to parts name code table

### Context
Similar to request #7670 (request for limb), the parts name code table has "pelvic girdle" and "pectoral girdle" but not "girdle" for specimens that are an otherwise indeterminate girdle element. Should pelvic and pectoral be modifiers?

### Table
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name

### Proposed Value
girdle

### Proposed Definition

~~either part of the pectoral or pelvis girdle of a vertebrate~~

In the vertebrate skeleton, the basal supporting structure that lies partly or wholly within the trunk and forms a stable base for the fin or limb. Use part modifiers such as pelvic or pectoral to specify if needed.

https://www.britannica.com/science/limb-girdle

http://purl.obolibrary.org/obo/UBERON_0007828

search terms: pelvic girdle, pectoral girdle, pelvis

### Collection type

paleo, bio

#### Attribute data type

n/a

#### Attribute controlled values

n/a

#### Attribute units

n/a

#### Part preservation attribute affect on "tissueness"

n/a

### Priority

high. needed for data migration.

### Available for Public View

yes

### Helpful Actions

- [x] Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

- [x] Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

@ArctosDB/arctos-code-table-administrators

## Approval
_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection
_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation
_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

- [ ] Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

- [ ] Add or revise the code table term/definition as described above. Ensure the URL of this Issue is included in the definition. URLs should be included *_as text_*, separated by spaced pipes. Do not include HTML in definitions.

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by campmlc** [comment]
Should either be "limb girdle" or use "pectoral girdle" and "pelvic girdle". Unless we want to include feminine attire.

**Comment by dustymc** [comment]
See also https://github.com/ArctosDB/arctos/discussions/7737, this desperately needs big-picture guidance.

I'm checking my boxes but also labeling this in wildfire mode for the necessary cleanup.

>feminine attire

There are definitions, terms don't just mean what someone might wish them to mean.

>Should pelvic and pectoral be modifiers?

Yes, here's who's using the girdle-having parts, and I have no idea what we might do about that.


[temp_part_gird.csv.zip](https://github.com/ArctosDB/arctos/files/15154471/temp_part_gird.csv.zip)

```

 guid_prefix | count 
-------------+-------
 MVZ:Mamm    |     6
 UCM:Mamm    |     1
 NMMNH:Paleo |   173
 ALMNH:Paleo |    10
 UTEP:ES     |    30
 CRCM:Bird   |     1
(6 rows)

```


 @ebraker
 @Nicole-Ridgwell-NMMNHS
 @mkoo
 @jessicatir
 @mvzhuang
 @cjconroy
 @aklompma

**Comment by campmlc** [comment]
I still prefer limb girdle to avoid confusion. But willing to check a box.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
https://github.com/ArctosDB/arctos/issues/7657 is related

**Comment by KatherineLAnderson** [comment]
> wildfire mode 
> 

I feel I am the empress of starting wildfires at the moment. Sorry...

Thanks all for this!

**Comment by dustymc** [comment]
>empress of starting wildfires

I've started the shrine out back!

I just don't want to get stuck in the middle of some change. We should not introduce multiple ways of saying the same thing. If there's some plan for A to go away as Z is created, great. If there's not then users will fail to find all of what they're looking for, and "we" will spend a bajillion hours in an awful limbo (which often finds ways to spread). I don't think it's unreasonable to ask the folks who want changes to help push them through - you can probably better explain the improvement to some reluctant curator than I can. (Lemme know if that's unreasonable.) Start all the wildfires you want, just fan 'em up so they burn the underbrush and leave everything all clean and fresh and covered with wildflowers, please....

**Comment by Jegelewicz** [comment]
Discussed at AWG Issues meeting today and it was agreed that we should generalize to girdle with the two modifier.

https://docs.google.com/document/d/1mTWY6HRlC3TSrAb38W2HOQHiVO2F1tA1m5jaLstYMS8/edit#heading=h.q3pk226foene

**Comment by dustymc** [comment]
@mkoo can you reach out to the folks mentioned in https://github.com/ArctosDB/arctos/issues/7733#issuecomment-2083585067, or should we consider this discussed, resolved, and as a slight internal rearrangement (all true) and proceed, or ??

**Comment by mkoo** [comment]
added oberon link and checked a box for the bone/zone!

**Comment by dustymc** [comment]
Discussed with AWG, reviewed with @mkoo and @Jegelewicz , done.
