### ISSUE TITLE
Feature Request - Format identifiers for an issuing agent

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7735]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

**Describe what you're trying to accomplish** 
_A clear and concise overview of the goals; why are you asking for this?_

I want to convert ASK type identifiers to issued by [Angelo State University Karyotype Number](https://arctos.database.museum/agent/21352412) but I would like to only use integers and have the format of the identifier always be "ASK integer" or ASK 1000

**Describe the solution you'd like**
_How might we accomplish your goals?_

Some way that enforces integers only when issued by is [Angelo State University Karyotype Number](https://arctos.database.museum/agent/21352412) OR perhaps enforces "ASK "integer at data entry.

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

Getting a mishmash of identifiers issued by [Angelo State University Karyotype Number](https://arctos.database.museum/agent/21352412), some with ASK, some without, some with a space between ASK and the integer, some without, etc.

**Additional context**
_Add any other context or screenshots about the feature request here._

https://github.com/ArctosDB/arctos/issues/7724#issuecomment-2079577153

> It's even possible that identifiers issued by certain agents could have structural requirements (eg, be integers, follow some pattern, be URIs or URLs, whatever), should someone want to file an issue.

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._

**Comment by dustymc** [comment]
I think this can safely go two ways. ID type is not problematic for local "if you don't already know what this means then it can't be useful to you" kinds of IDs, and clearly issued by is capable of carrying this.

When issued_by==https://arctos.database.museum/agent/21352412 then 
* type must be https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type#identifier
* other_id_prefix must be null
* other_id_suffix must be null

or

when type==https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type#ask then
* issued_by must be null 
* other_id_prefix must be null
* other_id_suffix must be null

I can codify either of those.

Just don't mix-n-match and it should be all good (and easy to convert to the other way if some reason to do so arises).

**Comment by Jegelewicz** [comment]
I DO NOT want to do this for type as some types can be shared by many issuers (collector number being the best example).

> When issued_by==https://arctos.database.museum/agent/21352412 then
> 
>     type must be https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type#identifier
>     other_id_prefix must be null
>     other_id_suffix must be null

is the ask

**Comment by dustymc** [comment]
>ome types can be shared by many issuers

So??

**Comment by dustymc** [comment]
Ah ok. I still think 'ID type is not problematic for local "if you don't already know what this means then it can't be useful to you" kinds of IDs' - I don't see much problem in keeping "integer we stick on freezers" types around.

I also don't see much problem with the agent approach.

I was not suggesting any sort of global filter, I think any of those which come to exist will be very pointed. 

There are a few which would need cleaned up before this can proceed.

```
      source      | other_id_type |    display_value     | assigned_agent | issued_by_agent 
------------------+---------------+----------------------+----------------+-----------------
 ASNHC:Mamm:5053  | ASK           | 1066a                | unknown        | 
 ASNHC:Mamm:5054  | ASK           | 1066b                | unknown        | 
 ASNHC:Mamm:11427 | ASK           | 1116 and BJB690      | unknown        | 
 ASNHC:Mamm:11495 | ASK           | 1117--BJB691         | unknown        | 
 ASNHC:Mamm:12765 | ASK           | 4062/ASK4860 embryos | unknown        | 
(5 rows)
```

Also need explicit OK to convert and remove the type, which is used by

```
 guid_prefix 
-------------
 ASNHC:Bird
 ASNHC:Herp
 ASNHC:Mamm
```
