### ISSUE TITLE
merge media 'published year' into 'made date, fix media search for dates

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#774]
The 'made date' search for media (from http://arctos.database.museum/MediaSearch.cfm) is searching published year instead. Documentation has the following definition for 'published year':

Published year for multipage documents such as fieldnotes. (How is this different than made date?)

Merge 'published year' into 'made date' for media labels, and fix media search for 'made date' so that it's searching on values for that label type.

**Comment by dustymc** [comment]
fixed
