### ISSUE TITLE
Taxon Name Request

### ISSUE THREAD

**Issue by hannahb2402** [ArctosDB/arctos#7744]
In the process of bulk-loading flea slides. There are a few scientific names that aren't in the Arctos database. The names are located in the flea taxonomy books (Rothschilds Collections of Fleas). I attached a picture of them below.
The names include:
Amaradix bitterrootensis bitterrootensis
Megarthroglossus divisus exsecatus
Eumolpi eumolpi
I am wondering if there's any way to include them in the database.
![0](https://github.com/ArctosDB/arctos/assets/116371809/991bdcc0-9e89-4ad8-8d37-bc81ac4ed6f3)
![IMG_4211](https://github.com/ArctosDB/arctos/assets/116371809/31b995da-845c-4bc7-9e29-85f9ad41e05d)
![IMG_4225](https://github.com/ArctosDB/arctos/assets/116371809/1eb25b6b-b0d8-4b2e-88db-d1bd1e971663)

**Comment by Jegelewicz** [comment]
Added
[Amaradix bitterrootensis bitterrootensis](https://arctos.database.museum/name/Amaradix%20bitterrootensis%20bitterrootensis)

[Megarthroglossus divisus exsecatus](https://arctos.database.museum/name/Megarthroglossus%20divisus%20exsecatus)

Eumolpi eumolpi should really be [Eumolpianus eumolpi eumolpi](https://arctos.database.museum/name/Eumolpianus%20eumolpi%20eumolpi)
