### ISSUE TITLE
[CONTACT: Blocked Network]

### ISSUE THREAD

**Issue by mluerig** [ArctosDB/arctos#7748]
restricted IP: 128.227.251.1

would you mind unblocking this IP? I am downloading images for research...

**Comment by mkoo** [comment]
HI @mluerig the traffic patterns from this IP is probably blocking it-- what exactly are you trying to do? There may be better ways to handle it if you are sending thousands of curl requests to harvest images. Feel free to email me directly: mkoo[at]berkeley.edu

**Comment by mluerig** [comment]
done!
