### ISSUE TITLE
how to find catalog records that are not georeferenced

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#7760]
I have not attempted to georeference since the new UI took place. Is there a way to determine which catalog records haven't been georeferenced?

I can get georeference source / georeference protocol to show up in search results, but not as search options. Previously, we could search NULL in georeference source to pull up the records needing georeferencing.

Thanks!

**Comment by dustymc** [comment]
I don't think you can.

For next release, you can via URL eg

https://arctos-test.tacc.utexas.edu/search.cfm?guid_prefix=CHAS:Bird&coordinates=NULL

Please change the milestone and let me know specifics if you'd like something else.

**Comment by wellerjes** [comment]
Will coordinates be a search option in the next release, or will I need to bookmark the link once it's live?

**Comment by mkoo** [comment]
I like it!
Can we also have NULL as an option in the declat and declong here?
https://arctos-test.tacc.utexas.edu/place.cfm?sch=locality

or just a toggle for No coordinates/not geoereferenced? I am searching localities usually from this interface and would find this handy

**Comment by mkoo** [comment]
> Will coordinates be a search option in the next release, or will I need to bookmark the link once it's live?

looks like it will be a search option so you can save to your profile or add as needed.

**Comment by dustymc** [comment]
I can add the coordinates search option to the "user controlled" options (it was already there so the above was easy, but it's only data-invoked at this point), I can resurrect an old flag, or whatever - let me know what would be most useful.

**Comment by wellerjes** [comment]
"user controlled" options is best. Thanks!

**Comment by campmlc** [comment]
It would be good to have both, so we can find lists of localities associated with our collections that need georeferencing.

**Comment by wellerjes** [comment]
Circling back around to this; the previous link to test no longer works. Since it was in next release in May, do you have an updated link about how I can access it now?

Thanks!

**Comment by mkoo** [comment]
I think there was some technical implementation direction needed here so was not completed. So I am going to make a suggestion to get this request fulfilled: Add this to the TURD!

Specifically this page: https://arctos.database.museum/Reports/cat_record_reports.cfm
Select a GUID and then select "locality: missing georeference" which would return the records with no coordinates. If run in this tool then report/results will be fast as a results are preprocessed (not on the fly)

thoughts @dustymc ?

**Comment by dustymc** [comment]
>technical implementation direction needed

Yes.

https://arctos.database.museum/search.cfm?guid_prefix=CHAS:Bird&coordinates=NULL does what was in next release, but I don't know if that's what's wanted.

>TURD

Yes, that could be done and would establish a scope (preferred locality has no coordinates). I like both the pre-processing and keeping problem-finding tools in the same place. Let me know if I can open a dev issue....

**Comment by mkoo** [comment]
Yes, TURD solution would be kindly on resources-- please send to dev
thx

**Comment by dustymc** [comment]
dev--->https://github.com/ArctosDB/dev/issues/113
