### ISSUE TITLE
Do we send taxon name authorship to aggregators (eg GBIF)

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#7761]
Just read over this: https://data-blog.gbif.org/post/2022-03-24-reasons-why-names-don-t-match-to-the-gbif-backbone/

and so would like to know do we send taxon name authorship to aggregators (eg GBIF) to help GBIF disambiguate homonyms so they can match our identifications to the correct name?

**Comment by dustymc** [comment]
Any additions would need added to the cache (at least if expensive and un-flat, and anything involving identifications is), possibly via https://github.com/ArctosDB/arctos/issues/8009, then a map request can be made in https://github.com/ArctosDB/arctos/issues/7348
