### ISSUE TITLE
Catalog record create page not accepting name

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#7762]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I'm trying to create a new catalog record with an agent with an Indigenous name integrated into his English name. The data entry page gives me the weird-looking characters meant to represent an apostrophe symbol, that is part of his name. When I attempt to save the record I get this message: 
2024-5-7T12:4:50: FAIL: agent_3_name [ Ch\'igiioonta\' Stephen Peter ] is invalid: {"message":"agent_3_name [ Ch\'igiioonta\' Stephen Peter ] is invalid","status":"fail"}

But the agent name is not invalid, in fact it is verified.
<img width="1496" alt="Screenshot 2024-05-07 at 12 03 47 PM" src="https://github.com/ArctosDB/arctos/assets/17605945/d0d00438-e9ed-4f1a-8674-de34abc1a5cd">

<img width="1565" alt="Screenshot 2024-05-07 at 12 04 11 PM" src="https://github.com/ArctosDB/arctos/assets/17605945/d82df86d-561c-4cc5-be2b-5a6eab565b2a">

**Desktop (please complete the following information):**
 - OS: Mac OS 14.4.1
 - Browser Firefox
 - Version 125.0.3 (64-bit)

**Priority**
High/Critical - I have several items collected by this man. The only solution I see now to get this record accepted is to change his preferred name until the record uploads, but I shouldn't have to do that.

**Comment by mkoo** [comment]
@dustymc can you add agents by their agentid? I recall that we talked about that option so we dont have to rely on the preferred name match. If so that would be a workaround here

**Comment by AJLinn** [comment]
Happened again today with Howard Uyaġak.
<img width="1565" alt="Screenshot 2024-05-08 at 10 31 22 AM" src="https://github.com/ArctosDB/arctos/assets/17605945/669f5e14-12a9-4ef3-89af-39e062c80aa2">

**Comment by AJLinn** [comment]
> can you add agents by their agentid? 

Sorry I didn't see your comment before creating this record so I'll try that next time if it continues to be an issue.
