### ISSUE TITLE
Feature Request - "partpart"

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#7763]
**Is your feature request related to a problem? Please describe.**

The [AWG](https://docs.google.com/document/d/1mTWY6HRlC3TSrAb38W2HOQHiVO2F1tA1m5jaLstYMS8/edit#heading=h.w0tvdqpqd23q) decided (correctly!) that there should be some limitation on parts, that we do not need a distinct part name for every bone, region, or squishybit to ever be called something. However, those data do (sometimes) exist, and relegating them to remarks ain't great.

**Describe what you're trying to accomplish** 

1. Have cake
2. Eat cake

**Describe the solution you'd like**

"Subparts" have been discussed many times in various contexts. A secondary table could (probably) comfortably have thousands of values, and misusing them would have somewhat limited impact; the 'primary' would still be discoverable, and would enhance discoverability for eg someone wanting any sort of skull bone from a taxa/time/whatever.

This would need at least a proper name and someone willing to use it to advance.

**Describe alternatives you've considered**

? further desecrate part names?? (And maybe we can't avoid that. Perhaps truly nobody cares about discoverability, data entry folks have no problems correctly choosing from thousands of options, and we should stop wasting time trying to do something that doesn't matter. But probably not....)

**Additional context**

I set up a very ugly test in test and added the most inappropriate possible combination to [whatever](https://arctos-test.tacc.utexas.edu/guid/UAM:Herb:11764/PID32457957) was on top of the random widget at the moment.

Search: https://arctos-test.tacc.utexas.edu/search.cfm?part_search=earbone

**Priority**

Kinda high??

@KatherineLAnderson @mkoo @Jegelewicz invite all your friends and break it plz

**Comment by mkoo** [comment]
hmm, I see potential! (
https://arctos-test.tacc.utexas.edu/guid/MVZ:Bird:101
BTW I had to add the part skull with the partpart of earbone to a Bird record before your search works -- was there one that you added because the search link was coming up empty for me?

**Comment by Jegelewicz** [comment]
Shouldn't the condition on that skull be partial? :-)

**Comment by mkoo** [comment]
I can put whatever I want! partially fabulous!
 Seriously now--  partpart might be better termed "component"?

**Comment by dustymc** [comment]
>component

Not as amusing as [bits n pieces](https://github.com/ArctosDB/arctos/issues/7667#issuecomment-2067322287), but probably better at conveying the idea.

> coming up empty

It's test, I probably messed with permissions or something, adding something to whatever you can see is/was the correct workaround for that.

>Shouldn't the condition on that skull be partial

Certainly something worth having a Best Practices for if this goes anywhere. FWIW at first glance I'm not so sure that's necessary - attributes are not some sort of second-class or less-important information, they by themselves shape parts and suggest things for which a part might be appropriate. This would carry just as much weight as https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_preservation#reproduction (not useful for genetics!) or https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_modifier#distal (not useful for studies of the proximal!) or anything else in any part attribute table.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
My concerns are:
1) # of part attributes in data entry is limited, and we're talking about moving more data to part attributes. I'm already at this limit for certain things.

2) How this will be for students choosing parts. Having students select part names for paleo stuff is already difficult (because of the complexity of paleo parts and the low level of expertise with students), having the data in two different fields will make it more complicated.

**Comment by dustymc** [comment]
(1) - yes, and we can add things but I think big-picture this (simplicity in general) is a very valid concern.

(2) - see https://github.com/ArctosDB/arctos/issues/7667#issuecomment-2067094093. I like this proposal in part because the newest, lost-est student (or later researcher) might find "something about the skull" as 'primary' and so SOMETHING is discoverable even if the 'refinement' gets horribly mangled (or even left off). 

That's possibly better than that same hypothetical student (or researcher) getting lost in a million (maybe literally!) techy-lookin' words and doing something near-random, but I'd still be pretty happy to at least experiment with just adding anything that anyone thinks should be a part, as long as we can do that as a community.

I mostly dislike being stuck in this weird seemingly-unavoidable middle ground where a bunch of conflicting directives are pulling everyone in uncomfortable directions, and I"m willing to go in about any direction as long as it involves some sort of coordination from The Community and we don't end up drifting back in another direction in like 12 minutes. Help!

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
The scenario I'm envisioning is: tag says something like "epipterygoid" student has no idea what that means and decides not to look it up or ask. When they enter that value into the part name, nothing comes up, so they just enter unknown. 

To be fair, part of that is just telling the student again and again to please ask questions, but also how do I easily explain to the students how to get from the more specific part to the less specific part when they don't have a great understanding of skeletal anatomy and what a less specific part could be.
