### ISSUE TITLE
Code Table Request - new part modifier: palatal

### ISSUE THREAD

**Issue by KatherineLAnderson** [ArctosDB/arctos#7764]
### Goal

Add "palatal" to the part modifier code table

### Context

For use with part name=tooth, to indicate the part is a palatal tooth

### Table

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_modifier

### Proposed Value

palatal

### Proposed Definition

of or relating to the palatine bone or other palate bone
see https://www.oed.com/dictionary/palatal-tooth_n?tl=true
and https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5192890/

### Collection type

bio, paleo

#### Attribute data type
n/a

#### Attribute controlled values
n/a

#### Attribute units
n/a

#### Part preservation attribute affect on "tissueness"
n/a

### Priority
priority high (needed for data migration)

### Available for Public View
yes

### Helpful Actions

- [x] Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

- [x] Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

@ArctosDB/arctos-code-table-administrators @Nicole-Ridgwell-NMMNHS 

## Approval
_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval https://github.com/ArctosDB/arctos/issues/7764#issuecomment-2100969692
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection
_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation
_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

- [x] Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

- [x] Add or revise the code table term/definition as described above. Ensure the URL of this Issue is included in the definition. URLs should be included *_as text_*, separated by spaced pipes. Do not include HTML in definitions.

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I approve of this, we have about 10 palatal teeth that come up when I do a search with palatal tooth just in remarks, and we probably have more than that in actuality. I would check a box, but Github for some reason isn’t loading for me right now.

**Comment by Jegelewicz** [comment]
added

**Comment by Jegelewicz** [comment]
@dustymc can we get a list of records with "palatal" in a part remark? Maybe we can get the attribute added for them.

**Comment by dustymc** [comment]
https://arctos.database.museum/search.cfm?part_search=palatal

**Comment by Jegelewicz** [comment]
DOH

**Comment by Jegelewicz** [comment]
Manually added the attribute to

https://arctos.database.museum/guid/UWBM:VP:118903
https://arctos.database.museum/guid/UWBM:VP:118903

@Nicole-Ridgwell-NMMNHS I have yours sitting in the part attribute loader. You can download and reload or I think just load them from there.

**Comment by Jegelewicz** [comment]
I did not make a loader for any collections to which I don't have access because I cannot accomplish a part view download from a non-operator login.
