### ISSUE TITLE
Download for Record Bulkloader generates unexpected/repeating data in CSV

### ISSUE THREAD

**Issue by DellaCHall** [ArctosDB/arctos#7766]
**Describe the bug**
The CSV file generated by the tool Download for Record Bulkloader has unexpected/repeating data in it.

**To Reproduce**
1. Do a search for some records (I did [this](https://arctos.database.museum/search.cfm?loan_trans_id=21119154))
2. Click on the tool dropdown menu and select Download for Record Bulkloader
3. Get weird CSV file with repeating data in it (I can send a copy of what I got if needed)

**Expected behavior**
A CSV file containing the data in the records, correctly.

**Priority**
High (Needed for work)

**Comment by Jegelewicz** [comment]
@dustymc I saw this yesterday and it is indeed weird and seems like the file being created is repeating collectors and attributes (at least maybe other things too).

**Comment by dustymc** [comment]
Data is always useful - I can't re-create this, 165 records go in, 165 records come out....

**Comment by Jegelewicz** [comment]
It isn't the number of records, it is the data in each row. It seems like the collectors start repeating themselves, both within a row and from row to row.

**Comment by Jegelewicz** [comment]
I emailed the file - there are some attributes in it that shouldn't be public.
