### ISSUE TITLE
Change a single word in a bunch of localities

### ISSUE THREAD

**Issue by jldunnum** [ArctosDB/arctos#7767]
We have a whole bunch of specific localities (varying georeferences) with the text string "Ulaan-Uul Soum, Khoridol Saridag Murgash", we want to change them all to "Ulaan-Uul Soum, Khoridol Saridag, Moenguush". How best to go about this? Thanks

**Comment by mkoo** [comment]
In this particular scenario, assuming you have merged the dup localities and really have 122 separate localties+georefs then I think this is a manual operation or a very polite request to the friendly dba to find/replace in spec_localities. The request needs to be very discrete and specific which in this case is. We could consider a tool for mass updates like this which could look like the locality name update tool potentially (a separate issue request), which I'm happy to do for you too. (seems like this comes up at least a few times a year)

So @dustymc could you please update the spec_localities (I found 122-- let me know if that's wrong, Jon) according to his request?

**Comment by jldunnum** [comment]
OK sounds good. I think this would be a nice tool to have because we do end up with huge numbers of localities with the same text but varied georeferences because we georeference each animal.

______________________________________________________________
Jonathan L. Dunnum Ph.D. (he, him, his)
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
Research Assistant Professor (LAT)
Department of Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

Chair, Systematic Collections Committee, American Society of Mammalogists
Latin American Fellowship Committee, ASM

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by dustymc** [comment]
>UPDATE 122


[Locality: Bulk Edit](https://arctos-test.tacc.utexas.edu/tools/BulkEditLocality.cfm) will do it.

**Comment by Jegelewicz** [comment]
Use this one instead - https://arctos.database.museum/tools/BulkEditLocality.cfm

:-)

**Comment by mkoo** [comment]
I'll file another issue but those require locality_name I believe which
wasnt created yet in this scenario.
Thanks for the quick fix!

**Comment by dustymc** [comment]
>require locality_name

Which is a one-click operation (then wander off and forget about it, get a notification, and one-ish more click to un-name).
