### ISSUE TITLE
Editing coordinates in event

### ISSUE THREAD

**Issue by jldunnum** [ArctosDB/arctos#7768]
Why are the "as entered coordinates" in collection event not editable? If I know there is a mistake here (uncalibrated GPS unit, wrong waypoint selected, erroneous transcription, etc.) I want to be able to fix it. No reason to make these unchangeable. Havint to leave the incorrect data there and then having to try to describe the error in remarks is just going to result in problems for future users. Please return editing access for this field. Thanks
![image](https://github.com/ArctosDB/arctos/assets/17278851/fcaf47f9-5e5a-475e-9676-7939c920d633)

**Comment by mkoo** [comment]
Those coordinates are from the locality table so you can edit coordinates when you update/edit locality. Those particular coordinates are from the original locality data entry from April 25th (View locality history). So it will change when you correct the locality (there may be some lag with the cache; not sure exactly what that is but usually pretty short if not noticeable for us). Basically all mappable lat/longs come from locality

**Comment by jldunnum** [comment]
Ok thats great if it updates when we fix the locality. Wasn't thinking about the cache time. Thanks

______________________________________________________________
Jonathan L. Dunnum Ph.D. (he, him, his)
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
Research Assistant Professor (LAT)
Department of Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

Chair, Systematic Collections Committee, American Society of Mammalogists
Latin American Fellowship Committee, ASM

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________
