### ISSUE TITLE
Pitfalls of non-TACC media storage?

### ISSUE THREAD

**Issue by adhornsby** [ArctosDB/arctos#7773]
Bell Museum has been storing media at Minnesota Supercomputing Institute (MSI) since before onboarding to Arctos.  MSI provides theoretically stable URIs for originals and derivatives, and it would be simpler for various reasons to just continue using it instead of switching to TACC.

Are there any pitfalls or restrictions that come with storing media on a server other than TACC?

Would media still be as discoverable (e.g. through https://arctos.database.museum/MediaSearch.cfm) as they would be on TACC?

Any other advice from those who have taken this path?  We'll want to do the usual stuff like linking images to records, records to publications, permits to accessions, etc.

**Comment by dustymc** [comment]
Dealing with instability in URIs is one of the reasons the Arctos Media model works as it does. It won't be any fun for you if they're making weekly changes, but it also won't break anything as long as you can keep up.

The location of Media is completely unimportant. Accessibility is important, but as long as they're just serving files in some semi-expected fashion and not trying to do anything tricky they should work fine.

Not losing your stuff is really the only critical consideration. If you're confident they'll still have your data in a few decades and they do whatever else you want, they'll work. (And might they be receptive to some sort of reciprocal agreement with TACC? Another copy of EVERYONE's media wouldn't be a bad thing...)

**Comment by Jegelewicz** [comment]
@adhornsby let's just try a few so you can see how they work? I'm happy to meet up and walk through it.

**Comment by adhornsby** [comment]
@Jegelewicz Thanks!  Getting a little bulkload file prepped to try it out.  I'll let you know if it fails or I seem to really screw it up...

@dustymc @Jegelewicz Will I have the same restriction of no "-" allowed in file names even from outside TACC?

**Comment by dustymc** [comment]
>restriction

It's not exactly a restriction and the idea isn't limited to any particular host: If you might ever want things scripted, naming the items in a way that doesn't make the scripts overly difficult would be appreciated by all.

**Comment by dustymc** [comment]
Done?
