### ISSUE TITLE
Feature Request - wrap names in agent search results

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7774]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

When a lot of agents share a somewhat long name (as most of our collections do), it can be hard to tell them apart

![image](https://github.com/ArctosDB/arctos/assets/5725767/c1b6d4ae-b4be-46fc-8aa5-efe3ff7a0c29)

**Describe what you're trying to accomplish** 
_A clear and concise overview of the goals; why are you asking for this?_

Make it easy to find the name I want

**Describe the solution you'd like**
_How might we accomplish your goals?_

Instead of truncating the long names, wrap them.

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

I can use other information to try to tell these apart, but it doesn't always help.

**Additional context**
_Add any other context or screenshots about the feature request here._

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._

**Comment by dustymc** [comment]
>other information

or hover:

<img width="622" alt="Screenshot 2024-05-09 at 13 17 18" src="https://github.com/ArctosDB/arctos/assets/5720791/6ec3e886-1884-4cd6-ac07-6558019fe48e">

**Comment by Jegelewicz** [comment]
> or hover:

It's nice that it's there, but hover, move down; hover, move down; 10 times isn't the most efficient way to compare?

**Comment by dustymc** [comment]
Not suggesting it's anything but available....

**Comment by Jegelewicz** [comment]
Doesn't seem to be a problem for anyone but me. Closing
