### ISSUE TITLE
Arctos Down - 2024-05-09 4:30pm ADT

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#7777]
I was just in the middle of adding media to a record and it stopped connecting. :-(

## Unplanned Outage
 - 2024-05-09 4:30 pm ADT
 - "Potential Security Issue"
<img width="998" alt="Screenshot 2024-05-09 at 4 29 22 PM" src="https://github.com/ArctosDB/arctos/assets/17605945/3e2bf95d-94f0-47b4-9446-f7d0193758f4">

## Communication before/during outage
- [x] Pin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG  
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by DerekSikes** [comment]
same here

**Comment by dustymc** [comment]
TACC is notified.

**Comment by mkoo** [comment]
SSL certificate expired or letsencrypt stopped working

**Comment by dustymc** [comment]
Certificate fixed, Arctos is back up.
