### ISSUE TITLE
Arctos not secure warning - loss of https

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#7778]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
All the Arctos urls seems to have reverted to http from https.
I get a "non-secure" error
Your connection is not private

**To Reproduce**
1. Go to any arctos url
2. Click on enter url in the api

**Expected behavior**
not to get this error

**Screenshots**
![image](https://github.com/ArctosDB/arctos/assets/14808196/2108d7fe-38c6-4c5d-a9c5-e6993fd9c553)
.

**Desktop (please complete the following information):**
 Windows
Chrome

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by mkoo** [comment]
yes TACC has been notified and we'll track wtih the Down issue #7777
