### ISSUE TITLE
Feature Request - Agent relationships on profile pages

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7779]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

From agent profile for https://arctos.database.museum/agent/21282782?deets=true#

This relationship is unclear

![image](https://github.com/ArctosDB/arctos/assets/5725767/35ba43d8-946a-4c9b-b3c1-23a2a12cc3a2)

and even the metadata doesn't help

![image](https://github.com/ArctosDB/arctos/assets/5725767/2072fae7-56d6-45c8-bf39-6fbe15d8c87d)

**Describe what you're trying to accomplish** 
_A clear and concise overview of the goals; why are you asking for this?_

Make it obvious that the agent I am looking at is NOT the bad duplicate.

**Describe the solution you'd like**
_How might we accomplish your goals?_

Can we separate relationships into To and From like this?

### To this agent

![image](https://github.com/ArctosDB/arctos/assets/5725767/160df298-2717-44a4-afdc-7df255ef9916)

### From this agent

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**
_Add any other context or screenshots about the feature request here._

This also makes me think that "Reciprocal Relationships" feels weird. Why not just "Relationships"?

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._

**Comment by dustymc** [comment]
I think maybe you're asking to display the header when there's no data, which isn't compatible with the API.

>Why not just "Relationships"?

Someone could have made it without ever looking at what you're looking at, there's no assertion originating from this agent - which would be called 'relationships' - but the thing which starts elsewhere can still be backtracked.

**Comment by Jegelewicz** [comment]
> I think maybe you're asking to display the header when there's no data, which isn't compatible with the API.

Nope - just a demo of how it would look - I'm fine with no header if there is nothing.

> Someone could have made it without ever looking at what you're looking at, there's no assertion originating from this agent - which would be called 'relationships' - but the thing which starts elsewhere can still be backtracked.

Ah Ha! Now I see!

Current "Relationships = my "From this Agent" and "Reciprocal Relationships = my "To this Agent", so really all I am asking for is a change in the headers.
