### ISSUE TITLE
Data entry: Pick locality blocked

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#7786]
I'm trying to select an existing locality on the Create Record page and something is not allowing me to interact with the popup window:
![image](https://github.com/ArctosDB/arctos/assets/12507297/547a42fe-dcf2-4015-939c-e04d300a6d15)
**actually if I only use my mouse it works, but if I use the keyboard, then I get that error.

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues?q=is%3Aissue+iframe+url - always some creepy extension....

**Comment by mkoo** [comment]
Hi @acdoll this is a known client (browser) issue -- see https://github.com/ArctosDB/arctos/issues/6901
There's likely an extension that is triggering this error. Try turning them all off, reload the page. if it works, then turn them back on one by one and let us know which is the bad guy!

**Comment by acdoll** [comment]
I did just install an extension for capturing scrolling screenshots (Awesome Screenshot). Disabling that did fix the issue. Thanks!
