### ISSUE TITLE
NMMNHS Bioscience TACC folder

### ISSUE THREAD

**Issue by lin-fred** [ArctosDB/arctos#7788]
@dustymc @Jegelewicz @ewommack 

Sorry I'm not sure who gives permissions for TACC but am I able to get access to the Bioscience folder under the NMMNHS TACC directory? Is there something I need to do?
![image](https://github.com/ArctosDB/arctos/assets/19802479/2be6f7af-ef97-423f-8b37-0a3c7226ba1e)

**Comment by dustymc** [comment]
My notes say you were given this initially, but it definitely wasn't there. Glitch in the matrix? You should have access now.

**Comment by lin-fred** [comment]
> My notes say you were given this initially, but it definitely wasn't there. Glitch in the matrix? You should have access now.

Ha who knows, thanks for the quick response Dusty! It is working now.
