### ISSUE TITLE
Feature Request - Make clone part more powerful

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#7789]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
Clone part includes neither "add to container barcode" nor any part attributes. The part attributes in particular can be tedious to add and it would be very helpful if they were included in the clone.

**Describe what you're trying to accomplish** 
Include part attributes and barcode in part clone.

**Additional context**
Here is an example:
![image](https://github.com/ArctosDB/arctos/assets/47402809/2d3fed87-3c65-4dad-91da-726ec5c61295)
I've added the first tooth part, and need to add three more. For the next part, all the data is the same except for two part attribute values. But because clone part does not clone attributes, I have to enter all of it over again, three more times.

**Comment by dustymc** [comment]
I'm getting lost in and frustrated with legacy code, I'm modernizing the whole form.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thank you! This will be a huge help!
