### ISSUE TITLE
Feature Request - agent info - expose collecting decades

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#7796]
**Is your feature request related to a problem? Please describe.**

I think we used to have a collecting date summary on the agent pages, it's useful in investigating possible duplicates among low-information agents.

**Describe what you're trying to accomplish** 

Make data more accessible.

**Describe the solution you'd like**

Show more collector-based info.

**Describe alternatives you've considered**

Right-click --> new private tab

**Additional context**

"Fwd: Arctos agent" email from @DerekSikes

**Priority**

?

Going next task, I know how to do this (but don't know if I have the CPU...)

**Comment by dustymc** [comment]
Playing with this lead to the discovery of a very deeply embedded bug, basically all of the back-end of the API is new, testing is VERY welcome.

I also noticed that @DerekSikes has been creating - uhh, something, which was unexpected but might still be intended/fine. Here are ``collector_role not in ('collector','preparator')`` summary stats - someone please turn this into an issue if it's something we need to do anything with.

```
  guid_prefix  |  collector_role  |   c   
---------------+------------------+-------
 ALMNH:EH      | creator          |     3
 ALMNH:EH      | subject          |     1
 Arctos:Entity | subject          |     1
 BYU:Edu       | creator          |     1
 CHAS:Art      | creator          |     6
 CHAS:AV       | creator          |     1
 CHAS:EH       | creator          |   473
 CHAS:EH       | subject          |     1
 CHAS:Herb     | creator          |     1
 CHAS:Teach    | creator          |    10
 CRCM:Paleo    | creator          |     2
 DMNS:Inv      | creator          |     1
 DMNS:Inv      | subject          |     2
 MSB:Herp      | creator          |     9
 MSB:Mamm      | copyright holder |     2
 MSB:Mamm      | creator          |    10
 MSB:Mamm      | subject          |     8
 MSB:Para      | creator          |     2
 MVZ:Arch      | creator          |   246
 MVZObs:Bird   | creator          | 14691
 MVZObs:Herp   | creator          |     1
 NMMNH:Bird    | creator          |     1
 NMMNH:Geol    | creator          |     4
 OWU:Bird      | creator          |    27
 OWU:ES        | creator          |   309
 UAF:Zooarch   | creator          |     9
 UAM:Arc       | subject          |   755
 UAM:Art       | copyright holder |  1194
 UAM:Art       | creator          |  4045
 UAM:Art       | subject          |    43
 UAM:EH        | copyright holder |    18
 UAM:EH        | creator          | 15307
 UAM:Ento      | creator          |     3
 UAMObs:Ento   | creator          |     1
 UCM:Obs       | creator          |   110
 UNM:MET       | creator          |     2
 UTEPObs:Ento  | creator          |     2
 UTEPObs:Herp  | creator          |   190
 UWBM:Mamm     | creator          |     3

```

**Comment by Jegelewicz** [comment]
@jebrad I fixed the three UWBM:Mamm records - these all looked like someone selecting creator insted of preparator (and I can see how that might be confusing...)

[UWBM:Mamm:82856](https://arctos.database.museum/guid/UWBM:Mamm:82856)
[UWBM:Mamm:83017](https://arctos.database.museum/guid/UWBM:Mamm:83017)
[UWBM:Mamm:83016](https://arctos.database.museum/guid/UWBM:Mamm:83016)

**Comment by Jegelewicz** [comment]
@lin-fred I changed [NMMNH:Bird:32](https://arctos.database.museum/guid/NMMNH:Bird:32) to preparator

**Comment by Jegelewicz** [comment]
@Nicole-Ridgwell-NMMNHS yours involve some judgement calls.

[NMMNH:Geol:1918](https://arctos.database.museum/guid/NMMNH:Geol:1918) creator seems appropriate as this is a manmade item

[NMMNH:Geol:2994](https://arctos.database.museum/guid/NMMNH:Geol:2994)
[NMMNH:Geol:3065](https://arctos.database.museum/guid/NMMNH:Geol:3065)
suggest changing these to preparator, but this one could go either way, so....

[NMMNH:Geol:3077](https://arctos.database.museum/guid/NMMNH:Geol:3077) not sure why this one has any of the "collector" agents since they are unknown - suggest just removing them.

**Comment by Jegelewicz** [comment]
@jessicatir 

[CRCM:Paleo:69](https://arctos.database.museum/guid/CRCM:Paleo:69)
[CRCM:Paleo:68](https://arctos.database.museum/guid/CRCM:Paleo:68)

I would have recorded Ward's as the collector - they didn't MAKE these fossils. Suggest changing these to collector

**Comment by Jegelewicz** [comment]
@jldunnum @jtgiermakowski I am guessing yours should also be converted to preparator, but I did not review all of them.

**Comment by Jegelewicz** [comment]
@dustymc testing of the API or the exposure of collecting decades?

**Comment by dustymc** [comment]
Anything agentish is pulling from the API, thanks!

**Comment by Jegelewicz** [comment]
Anything in particular we should be looking for? I've been working on Agents a lot today and haven't noticed anything weird....

**Comment by dustymc** [comment]
Hopefully the only change is not being able to exclude data by performing certain searches.

**Comment by jessicatir** [comment]
> @jessicatir
> 
> [CRCM:Paleo:69](https://arctos.database.museum/guid/CRCM:Paleo:69) [CRCM:Paleo:68](https://arctos.database.museum/guid/CRCM:Paleo:68)
> 
> I would have recorded Ward's as the collector - they didn't MAKE these fossils. Suggest changing these to collector

Made this change, thanks for pointing it out.
