### ISSUE TITLE
agent loader and near-nulls

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#7804]
**Describe the bug**

https://github.com/ArctosDB/data-migration/issues/1513#issuecomment-2123597091

**Comment by dustymc** [comment]
From https://github.com/ArctosDB/data-migration/issues/1906#issuecomment-2127458785

1. problem: I don't think these data had been through the pre-checker, I loaded them there and it flagged the problems. I'll make the warning bigger and redder.
2.  problem: documentation was wrong, the pattern for ORCID is https.... not http.... - I've updated.
3. problem: The type was given as ORCID{space or something} - we've been back and forth on this a bunch, I can do what I'm doing (let most anything load and flag errors), or I can type-check at load (which would reject this). I think generally the first option is smoother - it let's me see the problematic data, if nothing else.


This was in the data I got from somewhere:

```
 National Oceanic and                                              +| National Oceanic and[X]Atmospheric Administration Pacific Marine Environmental Laboratory
               | Atmospheric Administration Pacific Marine Environmental Laboratory | 
```

I'll add typed checks to the pre-check.

**Comment by dustymc** [comment]
For https://github.com/ArctosDB/data-migration/issues/1513: will clarify instructions and check access for next release

**Comment by Jegelewicz** [comment]
Cool - I'll get my stuff and clean up.
