### ISSUE TITLE
Code Table Request - Add "bulb" part name

### ISSUE THREAD

**Issue by WaigePilson** [ArctosDB/arctos#7805]
### Goal
Add "bulb" as a part name

### Context
Currently, the part names table contains just a handful of terms appropriate for describing plant parts: branch, bud, cone, flower, fruit, gall, leaf, pollen, rhizolith, rhizome, root, seed, spore, stem, and whole organism.

Similar to a rhizome, a bulb is a modified underground stem, in this case with modified leaves used for food storage. It would be appropriate to add bulb as another modified underground stem.

### Table
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name

### Proposed Value
bulb

### Proposed Definition
A modified subterranean plant stem usually consisting of a relatively large, usually globe-shaped structure of modified stem and fleshy leaves that functions as food storage organs during dormancy.

### Priority
High, needed for importing of some UBWM:PB records

### Helpful Actions

- [x] Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

- [x] Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

@ArctosDB/arctos-code-table-administrators @camwebb @Nicole-Ridgwell-NMMNHS 

## Approval
_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection
_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation
_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

- [x] Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

- [x] Add or revise the code table term/definition as described above. Ensure the URL of this Issue is included in the definition. URLs should be included *_as text_*, separated by spaced pipes. Do not include HTML in definitions.

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by camwebb** [comment]
:+1: from me

**Comment by dustymc** [comment]
I'm not at all clear how this lines up with https://docs.google.com/document/d/1mTWY6HRlC3TSrAb38W2HOQHiVO2F1tA1m5jaLstYMS8/edit#heading=h.w0tvdqpqd23q, or if that's still the direction we want to lean (seems a few decisions have gone the other way after that was discussed!). If we're trying to push flipper and hand and paw and .... into limb (are we? I'm lost there too!) then should this be - uhh, leaf? (And a modifier?)

Is there an ontology/authority/some sort of big-picture guidance for this sort of thing?

@ArctosDB/arctos-code-table-administrators help!

**Comment by WaigePilson** [comment]
> I'm not at all clear how this lines up with https://docs.google.com/document/d/1mTWY6HRlC3TSrAb38W2HOQHiVO2F1tA1m5jaLstYMS8/edit#heading=h.w0tvdqpqd23q, or if that's still the direction we want to lean (seems a few decisions have gone the other way after that was discussed!). If we're trying to push flipper and hand and paw and .... into limb (are we? I'm lost there too!) then should this be - uhh, leaf? (And a modifier?)

I'm fine with us moving "rhizome" as a part_modifier (of part "root") and then putting "bulb" as another part_modifier. However, so long as "rhizome" is a part name, I think that "bulb" should also be for the sake of consistency.

I've got no strong preference, I just need this added so I can import my collection!

> Is there an ontology/authority/some sort of big-picture guidance for this sort of thing?

great question! I don't know of one off the top of my head, perhaps a modern botanist would have a better idea...

**Comment by dustymc** [comment]
I'm not sure I have much of a preference either, other than wishing I had some ``[yep | nope ] that [ is | ain't ] a part`` formula...


```

 guid_prefix | count 
-------------+-------
 NMMNH:Paleo |     2

```

 @Nicole-Ridgwell-NMMNHS any preferences/direction/whatever here?

**Comment by mkoo** [comment]
> > I'm not at all clear how this lines up with https://docs.google.com/document/d/1mTWY6HRlC3TSrAb38W2HOQHiVO2F1tA1m5jaLstYMS8/edit#heading=h.w0tvdqpqd23q, or if that's still the direction we want to lean (seems a few decisions have gone the other way after that was discussed!). If we're trying to push flipper and hand and paw and .... into limb (are we? I'm lost there too!) then should this be - uhh, leaf? (And a modifier?)
> 
> I'm fine with us moving "rhizome" as a part_modifier (of part "root") and then putting "bulb" as another part_modifier. However, so long as "rhizome" is a part name, I think that "bulb" should also be for the sake of consistency.

I think this if you're ok with this where root has part_modifiers of ```rhizome``` and ```bulb``` then this would best fit the overall goals and inclinations of the Arctos CT


> 
> I've got no strong preference, I just need this added so I can import my collection!

Agreed! you just need to get to work!

If we could get input from affected collections (@Nicole-Ridgwell-NMMNHS )?

**Comment by Jegelewicz** [comment]
ontology - https://browser.planteome.org/amigo/term/PO:0025356

**Comment by Jegelewicz** [comment]
Above indicates this isn't a root?

[Inferred is_a relation] [BFO:0000002 continuant](https://browser.planteome.org/amigo/term/BFO:0000002#display-lineage-tab)
[Inferred is_a relation] [BFO:0000001 entity](https://browser.planteome.org/amigo/term/BFO:0000001#display-lineage-tab)
     [Inferred is_a relation] [BFO:0000004 independent continuant](https://browser.planteome.org/amigo/term/BFO:0000004#display-lineage-tab)
             [Inferred is_a relation] [BFO:0000040 material entity](https://browser.planteome.org/amigo/term/BFO:0000040#display-lineage-tab)
                 [Inferred is_a relation] [PO:0025131 plant anatomical entity](https://browser.planteome.org/amigo/term/PO:0025131#display-lineage-tab)
                     [Inferred is_a relation] [PO:0009011 plant structure](https://browser.planteome.org/amigo/term/PO:0009011#display-lineage-tab)
                         [Inferred is_a relation] [PO:0025497 collective plant structure](https://browser.planteome.org/amigo/term/PO:0025497#display-lineage-tab)
                             [Inferred is_a relation] [PO:0025007 collective plant organ structure](https://browser.planteome.org/amigo/term/PO:0025007#display-lineage-tab)
                                 [is_a relation] [PO:0009006 shoot system](https://browser.planteome.org/amigo/term/PO:0009006#display-lineage-tab)
                                     [Current term] PO:0025356 bulb

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
The issue with rhizome and bulb is that there is not an good "higher level" part that could be used. I think bulb should be its own term.

**Comment by campmlc** [comment]
Agree.

**Comment by mkoo** [comment]
CT committee discussed and we agree that we should add bulb-- it does not create problems overall and will allow cataloging to move forward.

**Comment by dustymc** [comment]
See https://github.com/ArctosDB/arctos/discussions/7737, would very much like big-picture guidance.

**Comment by Jegelewicz** [comment]
added
