### ISSUE TITLE
Code Table Request - Add part modifier "part to counterpart"

### ISSUE THREAD

**Issue by WaigePilson** [ArctosDB/arctos#7806]
### Goal
~~Add the term "part, of part-counterpart" to the part modifier table~~

Add the term "part to counterpart" to the part modifier table

### Context
Fossil plants often preserve as compression/impression fossils where there are two sides of a split rock each with the fossil preserved: we term this a "part and counterpart". Recording whether my two parts of a specimen record are part and counterpart is very important.

I suggest that we add two modifiers ~~"part, of part-counterpart" and "counterpart, of part-counterpart"~~ "counterpart to part" and "part to counterpart" for users to be able to mark the two parts associated with that specimen as the part and counterpart.

### Table
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_modifier

### Proposed Value
~~part of part-counterpart~~

part to counterpart

### Proposed Definition
~~Matching halves of a fossil; two halves of a compression fossil (often with carbon adhering to the part and the impression preserved on the counterpart).~~

One half of a compression fossil. Typically the part is the positive side with carbon adhering, outlining the fine details of the fossil. See https://en.wikipedia.org/wiki/Compression_fossil.

### Priority
High, most specimens in my collection have this attribute

### Helpful Actions

- [x] Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

- [x] Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

@ArctosDB/arctos-code-table-administrators @Nicole-Ridgwell-NMMNHS @aklompma @KatherineLAnderson 

## Approval
_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection
_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation
_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

- [x] Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

- [x] Add or revise the code table term/definition as described above. Ensure the URL of this Issue is included in the definition. URLs should be included *_as text_*, separated by spaced pipes. Do not include HTML in definitions.

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by WaigePilson** [comment]
See also issue #7807

I'm open to changing the wording here. I struggled with how to phrase a "part modifier" of "part"...

**Comment by Jegelewicz** [comment]
I think most collections have handled this in part remark, so some cleanup should happen if we do this.

https://arctos.database.museum/guid/NMMNH:Paleo:62949

![image](https://github.com/ArctosDB/arctos/assets/5725767/ca8513ec-c94f-4238-8819-3620fcabbfbe)

https://arctos.database.museum/guid/ALMNH:Paleo:5937

![image](https://github.com/ArctosDB/arctos/assets/5725767/e5b1923f-f1a7-44c1-bfdf-4dd5390355ba)

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I support this, we have over a thousand specimens with part/counterpart currently in remarks.

**Comment by Jegelewicz** [comment]
suggest instead

part to counterpart

(opposite would be counterpart to part)

**Comment by WaigePilson** [comment]
@Jegelewicz I've updated the definitions here per our discussion in the Code Table meeting yesterday! I think this is ready to implement.

**Comment by Jegelewicz** [comment]
added
