### ISSUE TITLE
Code Table Request - Add part modifier "counterpart to part"

### ISSUE THREAD

**Issue by WaigePilson** [ArctosDB/arctos#7807]
### Goal
~~Add the term "counterpart, of part-counterpart" to the part modifier table~~

Add the term "counterpart to part" to the part modifier table

### Context
Fossil plants often preserve as compression/impression fossils where there are two sides of a split rock each with the fossil preserved: we term this a "part and counterpart". Recording whether my two parts of a specimen record are part and counterpart is very important.

I suggest that we add two modifiers ~~"part, of part-counterpart" and "counterpart, of part-counterpart"~~ "counterpart to part" and "part to counterpart" for users to be able to mark the two parts associated with that specimen as the part and counterpart.

### Table
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_modifier

### Proposed Value
~~counterpart of part-counterpart~~

counterpart to part

### Proposed Definition
~~Matching halves of a fossil; two halves of a compression fossil (often with carbon adhering to the part and the impression preserved on the counterpart).~~

One half of a compression fossil. Typically the counterpart is the negative side, preserving an impression of the fossil. See https://en.wikipedia.org/wiki/Compression_fossil.

### Priority
High, most specimens in my collection have this attribute

### Helpful Actions

- [x] Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

- [x] Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

@ArctosDB/arctos-code-table-administrators @Nicole-Ridgwell-NMMNHS @aklompma @KatherineLAnderson 

## Approval
_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection
_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation
_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

- [x] Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

- [x] Add or revise the code table term/definition as described above. Ensure the URL of this Issue is included in the definition. URLs should be included *_as text_*, separated by spaced pipes. Do not include HTML in definitions.

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by WaigePilson** [comment]
See also issue #7806

I'm open to changing the wording here. I struggled with how to phrase a "part modifier" of "part"...

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I support this, we have over a thousand specimens with part/counterpart currently in remarks.

**Comment by dustymc** [comment]
The comma in the term will find a way to break something.

Are there external authority/ies to which we could link?  An ontology would be great, something like wikipedia might be useful.

**Comment by Jegelewicz** [comment]
suggest instead

counterpart to part

(opposite would be part to counterpart)

@WaigePilson will that work for you?

**Comment by WaigePilson** [comment]
> suggest instead
> 
> counterpart to part

This would work for me, although I have a minor concern that something this simple will be confusing to non-paleobotanists. As in, I can see some mammalology collections manager reading "counterpart to part" and not understanding that this is a specific and widely used term in fossil collections. But there will be the description in the code table, so maybe I should just trust that folks will understand from that what this means!

> Are there external authority/ies to which we could link? An ontology would be great, something like wikipedia might be useful.

Good question! I can't think of anything off the top of my head. This isn't a formalized term, so I don't know of any "authorities" who would define/control this vocabulary. But it is extensively used in the field. It's like trying to find an "authority" for the term "leaf", although in that case I suppose the botanical community does publish formal definitions and the like.

The best I can come up with is to link to the wikipedia page describing compression fossils: https://en.wikipedia.org/wiki/Compression_fossil#cite_note-Channing2011-5

Will this suffice?

**Comment by dustymc** [comment]
I like the simplicity suggested by your wiki link, can this be

* slab
* counter slab

or

* part
* counterpart

I think those would be less likely to confuse me, but any sort of letter-string (preferably without commas) still seems mostly OK too, my checkboxes can stay checked.

And on that note....

> there will be the description in the code table

Yes, Arctos kinda never deals in bare terms (which might mean whatever you want them to mean in the moment), controlled values are about always "concepts" (however primitive). Of course it's always nice if the terms are unambiguous, but I also don't think it's necessary to avoid things that might be misused by some hypothetical documentation-averse first-day art collection intern (or anyone else).

**Comment by WaigePilson** [comment]
> part
> counterpart

I like this idea, but my concern is that then we have a value in the code table "part attribute: modifier" of "part". This seems likely to confuse a lot of non-paleontologists when they're looking at all the available part modifiers and see you can have a "part" modified by the term "part"...

**Comment by dustymc** [comment]
``part half`` /  ``counterpart half`` ???

(Or "part impression" but I think maybe that's not quite true??)

**Comment by Jegelewicz** [comment]
added

**Comment by Jegelewicz** [comment]
@WaigePilson what updates need to be made to the definition of this and the other term?

**Comment by WaigePilson** [comment]
@Jegelewicz I've updated the definitions here per our discussion in the Code Table meeting yesterday! I think this is ready to implement.

**Comment by Jegelewicz** [comment]
added
