### ISSUE TITLE
Request discussion regarding means of creating reciprocal relationships across collections

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#7810]
From AWG meeting 5/23/2024: Need to clarify how this is now working or needs to be working going forward so we can come up with documentation and consistent protocols.

**Comment by dustymc** [comment]
There are three options:

1. Do your own thing
2. Download [Relationship: Find Unreciprocated](https://arctos.database.museum/info/unreciprocated_relationships.cfm) and do whatever you want with it.
3. Give https://arctos.database.museum/agent/21344957 access to your collection.

**Comment by Jegelewicz** [comment]
> Give https://arctos.database.museum/agent/21344957 access to your collection.

should really be give [reciprocal_relationship_bot](https://arctos.database.museum/AdminUsers.cfm?action=edit&username=reciprocal_relationship_bot) access to your collection.

**Comment by campmlc** [comment]
> > Give https://arctos.database.museum/agent/21344957 access to your collection.
> 
> should really be give [reciprocal_relationship_bot](https://arctos.database.museum/AdminUsers.cfm?action=edit&username=reciprocal_relationship_bot) access to your collection.

So how do we do that? Documentation is needed. Maybe incorporate into Manage Collection setup for new collections?

**Comment by dustymc** [comment]
>should really be give [reciprocal_relationship_bot](https://arctos.database.museum/AdminUsers.cfm?action=edit&username=reciprocal_relationship_bot) access to your collection.

Sure, that's a clarification.

>how do we do that?

Same as any user, and the logs claim you've done this a bunch of times.

>Documentation is needed. 

https://handbook.arctosdb.org/documentation/bot.html

**Comment by campmlc** [comment]
So by documentation, perhaps what we need is specific workflows for relationships. I would never have known to look for how to grant permissions to bot agents when wondering how to create reciprocal relationships . . .

**Comment by campmlc** [comment]
Also looks like this agent is LOCKED . . .

**Comment by campmlc** [comment]
Also - I see that some collections have access (I probably did this at some point before I forgot this), but there is no explanation of what roles if any to select. It would be good to add some descriptive explanation for this agent type.

**Comment by mkoo** [comment]
We are planning to have a demo of all the bots and how to manage at a future AWG meeting

**Comment by Jegelewicz** [comment]
new best practice - https://handbook.arctosdb.org/best_practices/parasites.html

bots documentation - https://handbook.arctosdb.org/documentation/bot.html

demo is at https://drive.google.com/file/d/10ZugjlZAxzI7h0djADwjb_IyoUerAMAj/view?usp=sharing

tentatively closing
