### ISSUE TITLE
Help - media metadata - documents loan

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#7811]
In a media metadata bulkload, how do I format the value for media relationship "documents loan". I've tried "NMMNH:Paleo GS-LO 2024.007" which is how the loan is formatted if it is done in the media edit page. I tried the transaction ID number, neither worked.

**Comment by Jegelewicz** [comment]
Once this is known, it should be added to the description documents loan [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctmedia_relationship#documents_loan)

**Comment by mkoo** [comment]
Can you share an example csv? did you get an error message?

**Comment by dustymc** [comment]
>how do I 

The tool is self-documenting; there's a table on the CSV page (and it'll include '% loan' in next release).




<img width="1464" alt="Screenshot 2024-06-04 at 11 22 41" src="https://github.com/ArctosDB/arctos/assets/5720791/f618ea64-6851-44e4-bd29-c14c8492d66a">





>should be added to the description

Not unless you will commit to changing the documentation every time the UI changes!!

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Has the tool been updated? I tried loan id before and it didn't work.

**Comment by dustymc** [comment]
>updated

Only in test,
<img width="351" alt="Screenshot 2024-06-04 at 11 50 30" src="https://github.com/ArctosDB/arctos/assets/5720791/f923c004-003b-4e6e-a478-83506341dc4c">

should take you to



https://github.com/ArctosDB/arctos/milestone/14

<img width="480" alt="Screenshot 2024-06-04 at 11 50 55" src="https://github.com/ArctosDB/arctos/assets/5720791/d6719d80-84d0-4893-bcd4-cf369313d1d1">

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks!
