### ISSUE TITLE
Need Help with Arctos Error - can UAM:Ento get access to sex attribute 'gynandromorph'?

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#7813]
ERROR_ID 	70C8ABFB-38BE-45B7-AACFA8403DB2CF47
ERROR_TYPE 	SQL
ERROR_MESSAGE 	ERROR: Invalid attribute: type not valid for this collection Where: PL/pgSQL function trigger_fct_tr_attributes_ct_bui() line 37 at RAISE
ERROR_DETAIL 	
ERROR_SQL 	INSERT INTO attributes ( ATTRIBUTE_ID ,COLLECTION_OBJECT_ID ,DETERMINED_BY_AGENT_ID ,ATTRIBUTE_TYPE ,ATTRIBUTE_VALUE ,ATTRIBUTE_UNITS ,ATTRIBUTE_REMARK ,DETERMINED_DATE ,DETERMINATION_METHOD ) VALUES ( nextval('sq_attribute_id'), 27914022, 1014877, 'sex', 'gynandromorph', null, null, '2024-05-23', null )

for this record https://arctos.database.museum/guid/UAM:Ento:372219

**Comment by dustymc** [comment]
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctsex_cde

<img width="162" alt="Screenshot 2024-05-24 at 06 26 46" src="https://github.com/ArctosDB/arctos/assets/5720791/eeb8c296-0506-4ce6-a58e-65d30185cfce">

or manage collection has a link.

And I patched the bug that was letting you see things you hadn't selected.

**Comment by DerekSikes** [comment]
thanks!
