### ISSUE TITLE
missing collection agents

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#7814]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

Playing with https://github.com/ArctosDB/arctos/issues/7808 in test, 
 DGR:Bird
 DGR:Mamm
collection-agents don't exist.

**Comment by Jegelewicz** [comment]
https://arctos.database.museum/agent/21352813
https://arctos.database.museum/agent/21352814
