### ISSUE TITLE
Help fixing habitat data

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#7815]
Just noticed that many (most/all?) of the catalog records in this accession:  UAM-2011.02-Nielsen-Ento

have numbers of an unknown nature, perhaps plot numbers, in their habitat fields.

Can these all be moved into their catalog record remarks field to empty the habitat field for these records?

**Comment by dustymc** [comment]
done

**Comment by DerekSikes** [comment]
thanks!
