### ISSUE TITLE
Arctos Down - Alaska 3:10 pm Friday

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#7817]
Please complete to the best of your ability.

## Unplanned Outage
 - Date and time (**please add time zone from which you are reporting**) outage discovered: Alaska 3:10 pm Friday
 - Describe the outage (Arctos down or only some part not working?): down

## Communication before/during outage
- [ ] Pin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG  
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by ewommack** [comment]
@DerekSikes - its working for me in Wyoming. Is it still down for you?

**Comment by dustymc** [comment]
Arctos is not down. What symptoms are you seeing?

**Comment by mkoo** [comment]
@DerekSikes could be a local issue as I've been on it continuously all afternoon... (to my chagrin)

**Comment by DerekSikes** [comment]
seems to be a local UAF problem!

**Comment by mkoo** [comment]
ok good luck up north!
