### ISSUE TITLE
Bug in Agent bulkloader?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7818]
@dustymc I swear I wouldn't do this on purpose.

![image](https://github.com/ArctosDB/arctos/assets/5725767/98d197c7-0f3e-42e0-8e5a-e40214f46ea1)

Did I actually load these twice? They were caught up in #7714 so maybe it was a weird glitch - but all of the agents in this load were duplicated. I just want to make sure that something weird isn't going on because I don't see how I managed to do this twice?

**Comment by dustymc** [comment]
They were made a couple days apart and I don't see anything obvious in the code, let's call it a glitch in the matrix for now.

```

 21352772 | organization | Adventure Aquarium   |            21300608 | 2024-05-21 17:36:17.510988
 21352790 | organization | Adventure Aquarium   |            21300608 | 2024-05-23 15:04:17.491665
```
