### ISSUE TITLE
bulkloader data

### ISSUE THREAD

**Issue by lcherreid** [ArctosDB/arctos#7819]
@maddo048 , 
maddo048@umn.edu 

[bulkloader_stage (2).csv](https://github.com/ArctosDB/arctos/files/15486926/bulkloader_stage.2.csv)  

Data has been in the bulkloader for multiple days, removed in order to use the bulkloader

**Comment by Jegelewicz** [comment]
@adhornsby please close this if you were done with the bulkloader.

**Comment by adhornsby** [comment]
Apologies @lcherreid , yes we're done with the bulkloader.
