### ISSUE TITLE
invalid part name error for valid part name

### ISSUE THREAD

**Issue by KatherineLAnderson** [ArctosDB/arctos#7824]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I have a few parts with part name=sesamoid in the parts bulkloader. Sesamoid IS in the part names code table (https://arctos.database.museum/info/ctDocumentation.cfm?table=CTSPECIMEN_PART_NAME), but it is returning the invalid part name error. I have looked at it up and down and there's no extra spaces, it's spelled correctly, etc. 

**To Reproduce**
1. Go to https://arctos.database.museum/loaders/BulkloadParts.cfm
2. Scroll to my username, and error "invalid part name". Click "review for this user/status".
3. Scroll down to the entries where part name=sesamoid
4. You can also look at the csv... maybe I'm overlooking something.

**Expected behavior**
It's a valid part name, so I would expect it to load normally.

**Screenshots**

**Data**
see csv in bulkloader

**Desktop (please complete the following information):**
 - OS: High Sierra 10.13.6
 - Browser: firefox
 - Version 115.9.1esr

**Additional context**

**Priority**
priority high--needed for data migration

**Comment by Jegelewicz** [comment]
@KatherineLAnderson you need to add that part to your list of available parts.

**Comment by KatherineLAnderson** [comment]
> @KatherineLAnderson you need to add that part to your list of available parts.

Wow, this step still tripping me up--maybe it'll sink in this time. Thanks Teresa!
