### ISSUE TITLE
Part download adding trailing space to part attributes

### ISSUE THREAD

**Issue by falco-rk** [ArctosDB/arctos#7825]
When I download parts, arctos is adding a trailing space to some of my part attributes, mostly part identifier and preservation but possibly other attributes as well. This means excel can't find my IDs unless I trim them first.

Example data: see columns AM and AN 
[partFlatDownload(24).csv](https://github.com/user-attachments/files/15514778/partFlatDownload.24.csv)

@dustymc @Jegelewicz

**Comment by Jegelewicz** [comment]
No ideas from me, this one needs @dustymc
