### ISSUE TITLE
Login bug - does not redirect to Arctos landing page

### ISSUE THREAD

**Issue by genevieve-anderegg** [ArctosDB/arctos#7826]
Sometimes when I log in (type in username, password, click 'sign in') I get stuck in this page with no way to click out of it. The only thing on the page are "sign out" and "change password" hyperlinks.
It's not a problem because I can just click on my arctos bookmark and that takes me right back to the main page, but I figured I would file an issue in case it was useful for y'all.
What the page looks like: 
![image](https://github.com/ArctosDB/arctos/assets/83782023/68171f8b-3c91-4337-b701-9336e1ab2256)

Windows 11 OS, Google Chrome

**Comment by dustymc** [comment]
I don't think that's an Arctos bug - your IP (and some others) makes double (or more) requests fairly often, which is exactly what gets to your screenshot: You've requested the login page after having logged in. I don't know if it's some creepy extension (maybe?) or just Chrome being Chrome (probably?) or your network (!!!) or what, but I'm sorta-sure Arctos is just responding to your requests as it can.

Happy to share the logs if that's useful.

**Comment by genevieve-anderegg** [comment]
Thanks Dusty! I was more curious than anything on what could cause this. I imagine it is Chrome, unless I'm double clicking my bookmark or something without noticing.
Cheers!
