### ISSUE TITLE
How do I view/download all part attributes from a group of catalog records?

### ISSUE THREAD

**Issue by falco-rk** [ArctosDB/arctos#7828]
When I search for catalog records and click Tools>View/Download>Parts, the downloadable table only shows 5 part attributes and tells you how many part attributes exist for that part. 

How do I view and download all of the part attributes?

**Comment by mkoo** [comment]
Can you share your csv and query? I just tried this on a query I was using for testing reports and retrieved all the parts in the csv (no filtering on parts of course) and it was over 6 parts (lots of tissues!). Happy to meet up on a quick zoom or next office hours... I think Tuesday?

**Comment by Jegelewicz** [comment]
@mkoo not the parts. The part attributes...

**Comment by falco-rk** [comment]
Here is a download of all the Mercenaria mercenaria in OGL that I filtered to only DNA parts. 5 part attributes are in columns AL-AP and column AQ gives the total part attribute count, 8-15 in this set, which is not uncommon for our DNA.
[partFlatDownload(26).csv](https://github.com/user-attachments/files/15534057/partFlatDownload.26.csv)

I'm happy to meet up on a quick zoom but arctos tea tomorrow is at 5:30pm my time and I cannot make that.

**Comment by dustymc** [comment]
Tell me what you want.

I can add a bunch of columns, but there are HARD limits on that (and none at all on actual attributes), and it'll still probably be somehow weird - it's currently a concatenation/string, I don't think that's useful for more than a rough summary.

I can add some sort of normalized download (maybe hinging on https://github.com/ArctosDB/arctos/discussions/5231), but that should probably ***replace*** what's there now (because I don't want to maintain two things, and because ya'll won't want to get lost in two things).

Probably other options, tell me what would work.

**Comment by falco-rk** [comment]
Could you create something that lets me filter both tissue type (as it does now) and part attribute type (like you can in the record attribute view/download)? Or just filter by part attribute since tissue type is its own column and I can either add that to my search or sort that in excel?

What I want for the project I am working on right now is something that tells me the catalog record ID/GUID, part identifier(s), and container barcode for my found set of records. But I can see myself wanting to be able download different part attributes for other projects.

**Comment by dustymc** [comment]
>filter both tissue type (as it does now) and part attribute type 

Not with the current framework - I've got a function set up that pulls attributes as concatenations in a hopefully-predictable order. I could re-do that to accept filters, somehow, probably, but that leaves us with a fixed number of concatenations; is that what everyone wants into the foreseeable future?? I don't think so, and this isn't any fun from here. Can we embrace the reality of not-flat??

>right now

Try OGL part report

**Comment by falco-rk** [comment]
>Try OGL part report

What does that mean and how do I do that?

For record attributes, you get a giant list of each attribute individually. Is that a thing that could happen for part attributes?

**Comment by dustymc** [comment]
>mean

I threw a super-simple report together in case we can't get the real thing sorted out soonest, might also be handy for exploring the possibilities. 


<img width="225" alt="Screenshot 2024-06-04 at 07 09 10" src="https://github.com/ArctosDB/arctos/assets/5720791/d56d4100-1ff1-4410-9168-b95fa7fa6df1">
<img width="266" alt="Screenshot 2024-06-04 at 07 09 24" src="https://github.com/ArctosDB/arctos/assets/5720791/c8400301-1e9a-468b-b599-345524012096">

> giant list of each attribute individually

Yes, that's always my preference - it makes filtering easy, it lets me easily include metadata, doesn't make me stuff units in with value, and scales to any situation - you somehow end up with 400 attributes on a part, it still works. If you can use that I can make it happen.

**Comment by falco-rk** [comment]
>If you can use that I can make it happen

I can use that! It would make sorting through things easier in a lot of ways. My only concern is that the current part attribute thing tells you where to find things in object tracking and I don't want to lose that.

**Comment by dustymc** [comment]
I'm sure missing a public dev box @mkoo ....

Next release has a couple new views (and the framework from within which more can be added).

<img width="1073" alt="Screenshot 2024-06-05 at 12 32 50" src="https://github.com/ArctosDB/arctos/assets/5720791/3057ae8f-8407-41ca-8a95-ea16b52e2f20">


Here's some sample data, @falco-rk let me know what's busted. This is from test, don't pay any attention to the data, only the format.

Note that SCIENTIFIC_NAME and REPRODUCTIVE_DATA are my customized columns; your view will be different.


[partFlatDownload(10).csv](https://github.com/user-attachments/files/15595630/partFlatDownload.10.csv)

**Comment by falco-rk** [comment]
That looks good to me!

To clarify, if you hadn't filtered to just a single part attribute, would it have each attribute on a separate line?

**Comment by dustymc** [comment]
Yup, here's an unfiltered sample.

[partFlatDownload(11).csv.zip](https://github.com/user-attachments/files/15596259/partFlatDownload.11.csv.zip)

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Just came across this, it's great, thank you!
