### ISSUE TITLE
Pull collectors

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#783]
When the "pull" function is used to pull collector names from one cataloged item into the data entry screen, the second and third collector names have a space inserted in front of the name. As a result, Arctos does not recognize the collector when "save as new record" is clicked, and instead gives an error. The space must currently be manually deleted. Can this be corrected so that there is no extraneous space in front of collector name.

**Comment by dustymc** [comment]
for 7.1.0.1
