### ISSUE TITLE
update to getMvzMammParts.sql

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#7830]
In /getMvzMammParts.sql
Please add a space to either side of the pipes so it's ``` ' | ' ``` for legibility. Often the pipes end up looking like a letter no matter what the font! thanks

**Comment by dustymc** [comment]
OMG WHY ARE YOU WORKING?!

Done....

**Comment by mkoo** [comment]
OMG WHY ARE YOU (this was for Monday!)
but thanks!
