### ISSUE TITLE
Agent Merge Request - UAF Art

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#7833]
Use this template when you discover two agents that you believe represent the same person or organization.

**Agent that should remain after the merge**

https://arctos.database.museum/agent/21318948

**Agent that will no longer remain after the merge**

https://arctos.database.museum/agent/21281303

**Reason for merge**

I think these are the same, but there's a giant mess of probably-overlapping incoming relationships and other data. Suspect this needs significant manual cleanup, would not be surprised to find other messes hiding in the mess.

Please add this issue to the Agents Project

@ArctosDB/agents-committee

@DellaCHall

**Comment by DellaCHall** [comment]
Thanks for tagging me. These are NOT the same. The UA Museum's Fine Arts collection department (where I work) is entirely separate from UAF's Art Department. I've added a few details to the agent records to help make that more clear, hopefully.

**Comment by dustymc** [comment]
Ah, thanks.

A metadata-heavy 'not the same as' relationship would be useful for me.

I got here via https://github.com/ArctosDB/arctos/issues/7808

https://arctos.database.museum/agent/21318948 wears a collectionID, https://arctos.database.museum/collection/UAM:Art

https://arctos.database.museum/agent/21281303 has issued 600+ identifiers that probably belong to the other - https://arctos.database.museum/search.cfm?id_issuedby==University+of+Alaska+Fairbanks+Art+Department

That might all be me getting lost at various times, or maybe I'm not alone in this....

Feel free to close this issue, I think there's nothing substantial to do here.

**Comment by DellaCHall** [comment]
> 'not the same as' relationship

Added!

> https://arctos.database.museum/agent/21281303 has issued 600+ identifiers that probably belong to the other - https://arctos.database.museum/search.cfm?id_issuedby==University+of+Alaska+Fairbanks+Art+Department

I believe this is something that needs to be cleaned up, but I need to look into it more. I can add it to my list of things to deal with at some point, but if its not creating a problem for anyone else, it'll be a low priority for me.

Thanks!
