### ISSUE TITLE
Feature Request - Select Agent Preferred Name

### ISSUE THREAD

**Issue by DellaCHall** [ArctosDB/arctos#7834]
**Is your feature request related to a problem? Please describe.**
People use different names in different scenarios. I'd like a way to select a preferred name based on the scenario, rather than having a single preferred name for all scenarios.

Specific example: [Richard T. Wallen](https://arctos.database.museum/agent/21280206) is a biologist with a specimen in UWZM:Mamm, a donor of an accession in UAM:EH, and an artist with works in the UAM:Art collection. His wife has reached out to me and asked that the records of his artworks reflect the name he always used professionally as an artist: "R. T. Wallen." I added that as an AKA, but the preferred name that appears on the records for all 3 collections would need to be changed in order for it to appear as "R. T. Wallen" on his artwork records as the creator.

**Describe what you're trying to accomplish** 
I'd like a way to have a specific preferred name (that might be an AKA in other scenarios) appear on a record as the creator.

**Describe the solution you'd like**
Allow a selection of a preferred name among the AKAs, dependent upon the agent role (creator, collector, etc). This could appear in parentheses next to the name, if it cannot be the only name that appears. Or, a remark that could appear next to the creator name? I'm open to solutions that help us accomplish this.

**Describe alternatives you've considered**
Add another attribute field "artist name", or add it to the description attribute as a catch-all field.

**Priority**
Low (Wish List)

**Comment by dustymc** [comment]
>preferred name that appears on the records for all 3 collections would need to be changed

That's probably what everyone wants anyway. The agent-object is used for a UWZM accession, but the record linked from the accession just uses a verbatim agent formatted as this person seems to prefer: https://arctos.database.museum/guid/UWZM:Mamm:28581. I'm guessing @ehalverson26  would appreciate the help in making the donor happy.

If that's not enough.....


https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#verbatim_agent seems like it does about what's requested, but the "... and display is JUST SO in these specific cases" extension of that probably involves the API.

>appear in parentheses

That level of detail is probably still "there's an API" territory, but we somehow still do not have ``collector.remarks``; such a thing might be requested, and could possibly do what's needed.

**Comment by DerekSikes** [comment]
This dovetails nicely with a wish I've had for some time that the catalog record shows the exact form of an agent name that is on the label (verbatim) while ALSO showing the 'real' agent name (preferred). Currently the system for doing this is very cumbersome (create a verbatim agent attribute and then do or do not link to a real agent which has no relation to the verbatim agent attribute).

**Comment by ehalverson26** [comment]
We originally went with Richard T. Wallen because we have a number of "R. Wallen" agents associated with our collections. Given the ability to link AKA and preferred names, if Skip and Lynn prefer his name to be R. T. Wallen, it works for us for the names to be switched. UWZM:28581 IS associated with the person in question, so that one could also be upgraded from the verbatim agent to the full agent. Let me know if you want me to make any changes on my end.

**Comment by Jegelewicz** [comment]
Perhaps preferred name should be the preferred name of the person when known?

**Comment by dustymc** [comment]
I think this has been addressed, closing.
