### ISSUE TITLE
Agent Merge Request - AMNH

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#7838]
**Agent that should remain after the merge**

https://arctos.database.museum/agent/21347734

**Agent that will no longer remain after the merge**

https://arctos.database.museum/agent/21347805

**Reason for merge**

same?

Please add this issue to the Agents Project

@ArctosDB/agents-committee

@Jegelewicz

**Comment by Jegelewicz** [comment]
OOF - my bad - merged
