### ISSUE TITLE
slide positions

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#784]
Problem with scanning slides into box positions. Slide boxes are numbered 1-50 top to bottom left side; 51-100 top to bottom right side. The position form to scan slides into position displays correct positions. However, the position as shown in part location does not, due to browser? using tab vs return. Part location shows even positions 2,4,6,8, 10 etc in right column, instead of 51,52,53, 54,55 etc.
Example: Barcode PDCE ; actual location = position 51; but display position = position 2

**Comment by dustymc** [comment]
for v7.4.3
