### ISSUE TITLE
Feature Request - adding a Shareable URL which includes both the search parameters and the current results parameters for sharing data to outside users

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#7842]
Request to be able to save and download search results with the customized search and results settings as selected by the user.
We need to be able to share not only the records themselves but also the various search and results fields and parameters for a customized query.
This is related to TPT grant funding.

**Comment by mkoo** [comment]
Currently the shareble URL for a search only passes the search parameters and the results table does not reflect the fields that the user is viewing or wants to share. This is new type of shareble URL that includes results fields. Not sure of the technical requirements for this but has a lot of value for sharing data broadly

**Comment by AJLinn** [comment]
FYI, if you have a "preset" set up the sharable URL includes both the data and the results layout. See for example this search:
<img width="759" alt="Screenshot 2024-06-14 at 12 38 18 PM" src="https://github.com/ArctosDB/arctos/assets/17605945/3010d020-777a-4f71-bb8b-0bf1b68096e7">

[And sharable URL](https://arctos.database.museum/search.cfm?guid_prefix=UAM%3AEH&scientific_name=robe&scientific_name_match_type=contains&attribute_type_1=culture%20of%20origin&attribute_value_1=Tlingit&sp=preset_eh)

**Comment by campmlc** [comment]
I just tested this realized that is the case, thanks @AJLinn ! I was using a preset but tweaking some of the results columns using customize, and it wasn't saving those added parameters with the shareable url.

**Comment by campmlc** [comment]
So I guess my request is to add all customized parameters to the shareable url in Tools - possible?

**Comment by mkoo** [comment]
Addressed in Issues meeting-- secret sauce is to include and profile or preset that includes the desired fields in the results. When the shareable URL includes the profile then all aspects are included. Angie's example includes this.
