### ISSUE TITLE
Need Help with Arctos Error - Identifiers failing to load

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7843]
# Error Text
load fail::ERROR: function type_check_identifier(character varying, character varying, integer) does not exist Hint: No function matches the given name and argument types. You might need to add explicit type casts. Where: PL/pgSQL function trigger_fct_coll_obj_data_check() line 31 at SQL statement 

# Where it happened
https://arctos.database.museum/loaders/BulkloadOtherId.cfm

# Steps to get there
The data is in the tool - I'm not sure what is causing the problem.

# Problem
**Community response to describe the problem that caused the error**

# Solution
**Community response with directions for how to correct the problem**

**Comment by dustymc** [comment]
Kanooter valve discombobulated.
