### ISSUE TITLE
Update to exemption for lithostrata and code table description change

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7844]
# Code tables affected

[ctlithostratigraphic_bed](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlithostratigraphic_bed)
[ctlithostratigraphic_formation](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlithostratigraphic_formation)
[ctlithostratigraphic_group](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlithostratigraphic_group)
[ctlithostratigraphic_member](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlithostratigraphic_member)

# Change request

British Geological Survey has a lexicon, we can use to verify lithostratigraphic requests. I would like to add this to the code table descriptions so that everyone can find it.

https://www.bgs.ac.uk/technologies/the-bgs-lexicon-of-named-rock-units/

Edit text in the code table descriptions:

from

> The unit is registered in a national geologic database, with a link included in the documentation (for example: https://ngmdb.usgs.gov/Geolex/search). If the unit is not listed in a national database, the documentation should include a link to a publication that describes the unit.

to

The unit is registered in a national geologic database, with a link included in the documentation (for example: https://ngmdb.usgs.gov/Geolex/search, https://www.bgs.ac.uk/technologies/the-bgs-lexicon-of-named-rock-units/). If the unit is not listed in a national database, the documentation should include a link to a publication that describes the unit.

Also, can we make it so that this text isn't all bold?

![image](https://github.com/ArctosDB/arctos/assets/5725767/8570b99d-98eb-457d-8dc4-6ba05cdadb03)

This would be easier on the eyes

## Locality Attribute: Lithostratigraphic Formations
Controlled vocabulary for lithostratigraphic formations available as locality attributes. Terms may be added to this table without DBA approval and with the approval of one active Code Table Committee member, as long as that Code Table member did not also request the term if the following criteria are met:
<ul>
<li>The unit is registered in a national geologic database, with a link included in the documentation. 
<ul>
<li>https://ngmdb.usgs.gov/Geolex/search</li>
<li>https://www.bgs.ac.uk/technologies/the-bgs-lexicon-of-named-rock-units/</li>
</ul>
If the unit is not listed in a national database, the documentation should include a link to a publication that describes the unit.</li>
<li>The term is properly formatted as "Name Type". Lithology descriptors should only be included when the unit is not referred to both with and without the descriptor. When a lithology descriptor is included, the format is "Name Lithology Type". Acceptable examples: Cierbo Formation, Clare Shale Formation</li>
<li>In addition to the required links, it is strongly preferred that the documentation include a short description of the unit. Information suggested to be in the description includes: the geographic region(s) in which the unit outcrops, geologic age, and dominant lithology.</li>
</ul> 

**Table ctlithostratigraphic_formation -**

**Comment by dustymc** [comment]
Big-picture: yes.

Minor request: ``<li>`` the examples, they all sorta run together in the parens.

**Comment by Jegelewicz** [comment]
Controlled vocabulary for lithostratigraphic beds available as locality attributes. Terms may be added to this table without DBA approval and with the approval of one active Code Table Committee member, as long as that Code Table member did not also request the term if the following criteria are met:
<ul>
<li>The unit is registered in a national geologic database, with a link included in the documentation. 
<ul>
<li>https://ngmdb.usgs.gov/Geolex/search</li>
<li>https://www.bgs.ac.uk/technologies/the-bgs-lexicon-of-named-rock-units/</li>
</ul>
If the unit is not listed in a national database, the documentation should include a link to a publication that describes the unit.</li>
<li>The term is properly formatted as "Name Type". Lithology descriptors should only be included when the unit is not referred to both with and without the descriptor. When a lithology descriptor is included, the format is "Name Lithology Type". Acceptable examples: Westfield Fish Bed, Down Cliff Sand Member Starfish Bed</li>
<li>In addition to the required links, it is strongly preferred that the documentation include a short description of the unit. Information suggested to be in the description includes: the geographic region(s) in which the unit outcrops, geologic age, and dominant lithology.</li>
</ul>https://github.com/ArctosDB/arctos/issues/7844

**Comment by Jegelewicz** [comment]
Controlled vocabulary for lithostratigraphic formations available as locality attributes. Terms may be added to this table without DBA approval and with the approval of one active Code Table Committee member, as long as that Code Table member did not also request the term if the following criteria are met:
<ul>
<li>The unit is registered in a national geologic database, with a link included in the documentation. 
<ul>
<li>https://ngmdb.usgs.gov/Geolex/search</li>
<li>https://www.bgs.ac.uk/technologies/the-bgs-lexicon-of-named-rock-units/</li>
</ul>
If the unit is not listed in a national database, the documentation should include a link to a publication that describes the unit.</li>
<li>The term is properly formatted as "Name Type". Lithology descriptors should only be included when the unit is not referred to both with and without the descriptor. When a lithology descriptor is included, the format is "Name Lithology Type". Acceptable examples: Cierbo Formation, Clare Shale Formation</li>
<li>In addition to the required links, it is strongly preferred that the documentation include a short description of the unit. Information suggested to be in the description includes: the geographic region(s) in which the unit outcrops, geologic age, and dominant lithology.</li>
</ul>https://github.com/ArctosDB/arctos/issues/7844

**Comment by Jegelewicz** [comment]
Controlled vocabulary for lithostratigraphic groups available as locality attributes. Terms may be added to this table without DBA approval and with the approval of one active Code Table Committee member, as long as that Code Table member did not also request the term if the following criteria are met:
<ul>
<li>The unit is registered in a national geologic database, with a link included in the documentation. 
<ul>
<li>https://ngmdb.usgs.gov/Geolex/search</li>
<li>https://www.bgs.ac.uk/technologies/the-bgs-lexicon-of-named-rock-units/</li>
</ul>
If the unit is not listed in a national database, the documentation should include a link to a publication that describes the unit.</li>
<li>The term is properly formatted as "Name Type". Lithology descriptors should only be included when the unit is not referred to both with and without the descriptor. When a lithology descriptor is included, the format is "Name Lithology Type". Acceptable examples: Dunquin Group, Old Red Sandstone Supergroup</li>
<li>In addition to the required links, it is strongly preferred that the documentation include a short description of the unit. Information suggested to be in the description includes: the geographic region(s) in which the unit outcrops, geologic age, and dominant lithology.</li>
</ul>https://github.com/ArctosDB/arctos/issues/7844

**Comment by Jegelewicz** [comment]
Controlled vocabulary for lithostratigraphic members available as locality attributes. Terms may be added to this table without DBA approval and with the approval of one active Code Table Committee member, as long as that Code Table member did not also request the term if the following criteria are met:
<ul>
<li>The unit is registered in a national geologic database, with a link included in the documentation. 
<ul>
<li>https://ngmdb.usgs.gov/Geolex/search</li>
<li>https://www.bgs.ac.uk/technologies/the-bgs-lexicon-of-named-rock-units/</li>
</ul>
If the unit is not listed in a national database, the documentation should include a link to a publication that describes the unit.</li>
<li>The term is properly formatted as "Name Type". Lithology descriptors should only be included when the unit is not referred to both with and without the descriptor. When a lithology descriptor is included, the format is "Name Lithology Type". Acceptable examples: Cameron Creek Member, Down Cliff Sand Member</li>
<li>In addition to the required links, it is strongly preferred that the documentation include a short description of the unit. Information suggested to be in the description includes: the geographic region(s) in which the unit outcrops, geologic age, and dominant lithology.</li>
</ul>https://github.com/ArctosDB/arctos/issues/7844

**Comment by Jegelewicz** [comment]
updates made to code table descriptions

**Comment by dustymc** [comment]
added to https://docs.google.com/spreadsheets/d/1-QC9L8jbOzaG7vstp5iHyx8ivlyvr3BrtiCY_GBimAg/edit?gid=0#gid=0
