### ISSUE TITLE
Need Help with Arctos Error - cannot bulkload records

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#7845]
# Error Text
**Copy the text from the page and paste it here**
function type_check_identifier(character varying, character varying, character varying) does not exist42883

# Where it happened
**Provide a link to or a description of the page where the error occurred.**
record bulkloader, status column
https://arctos.database.museum/Bulkloader/browseBulk.cfm

# Steps to get there
**Describe the actions that led to the error**
I tried to bulkload records that were entered via data entry form

# Problem
**Community response to describe the problem that caused the error**

# Solution
**Community response with directions for how to correct the problem**

**Comment by wellerjes** [comment]
May be related to https://github.com/ArctosDB/arctos/issues/7843 ?

**Comment by dustymc** [comment]
Yes, the kanooter valve was not in fact discombobulated, hopefully it is now - but I can't find your errors to check (I see everything from everyone, it's a bit overwhelming), please point to a specific example if things still aren't working.

**Comment by wellerjes** [comment]
Records have now loaded; thanks!
