### ISSUE TITLE
"Shipments" for data loans

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#785]
A shipment is required in order to print address information on loan invoices. But the shipment options are n/a for data loans. Can we add two values to shipments:

shipped method = digital (covers email, Box.com, Dropbox.com, etc.)
shipment type = data

Or values along those lines?

**Comment by dustymc** [comment]
Can you explain where you're going with this? I really have no idea what's going on here...

**Comment by dustymc** [comment]
Closing, now redundant with #799
