### ISSUE TITLE
Feature Request - update locality attributes

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#7856]
**Is your feature request related to a problem? Please describe.**

 https://github.com/ArctosDB/arctos/issues/7374 is a new structure and will require some new code. Updating some things that need updated anyway would make that nicer.

**Describe what you're trying to accomplish** 

Simplify and modernize

**Describe the solution you'd like**

 Make https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlocality_attribute_type + https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlocality_att_att look/work like https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type

**Describe alternatives you've considered**

pain and suffering

**Additional context**

nope

**Priority**

happening

**Comment by dustymc** [comment]
I can't put my usual constraints on the types because...


```

 attribute_type  
-----------------
 Eon/Eonothem
 Era/Erathem
 Series/Epoch
 Stage/Age
 System/Period
 Substage/Subage
```

... exist. Ignoring for now.

**Comment by Jegelewicz** [comment]
> Ignoring for now.

Could be fixed by https://github.com/ArctosDB/arctos/issues/7404
