### ISSUE TITLE
return to loan from review items

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#786]
There used to be a link back to a loan from the 'review items' page, but that disappeared when loans were updated. Please add that link back to the page. Thanks.

**Comment by dustymc** [comment]
<img width="474" alt="screen shot 2015-11-10 at 3 33 17 pm" src="https://cloud.githubusercontent.com/assets/5720791/11079355/93445026-87c0-11e5-8092-92c92295d4e6.png">

That one?

**Comment by ccicero** [comment]
Yes, when you click on that and go to review loan items, the only way to get back to the loan is by hitting the back button. 

Also, add count of number of loan items to the review loan items page. This is important as a check against what's entered into nature of material.

![image](https://cloud.githubusercontent.com/assets/967275/11354557/22b69814-9201-11e5-8ae5-33a5df5c9ca3.png)

**Comment by dustymc** [comment]
Still no idea what's going on here - there's a big link back to the loan at the top of the page, the item count is bottom right, both have always been there. I'm closing this, please re-open if I'm not understanding something.
