### ISSUE TITLE
Feature Request - Add ASM Mammal Diversity taxonomy source?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7866]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

**Describe what you're trying to accomplish** 
_A clear and concise overview of the goals; why are you asking for this?_

Better mammal taxonomy

**Describe the solution you'd like**
_How might we accomplish your goals?_

Download the database and transform, then update periodically - https://www.mammaldiversity.org/index.html

Get from GlobalNames? (Looks like it is as of 2021 in GN, maybe staleness doesn't matter? - http://gni.globalnames.org/data_sources/184

If we decide this is worth it, a code table request for a new source will be required.

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

Do nothing - people are using the Arctos source and seem happy?

**Additional context**
_Add any other context or screenshots about the feature request here._

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._

**Comment by Jegelewicz** [comment]
This came about because I found the associated link when adding this taxon.

[Otomys sungae](https://arctos.database.museum/name/Otomys%20sungae)

![image](https://github.com/ArctosDB/arctos/assets/5725767/15029620-01fc-4943-a6b2-a82d1bc68a41)

Unfortunately, the GN version does not include the link:

![image](https://github.com/ArctosDB/arctos/assets/5725767/26722ca5-b33d-46b4-8e21-b00bc70c8701)

These links are taxon identifiers that could be useful as we move into digital extended specimens!

ASM - https://www.mammaldiversity.org/taxon/1003411
GBIF - https://www.gbif.org/species/11646604
Wikidata - https://www.wikidata.org/wiki/Q99194695

**Comment by campmlc** [comment]
I support this. The source project is well underway and is actively supported by PIs and grad students in multiple Arctos collections via ASM.

**Comment by Jegelewicz** [comment]
> They may be able to provide the links.

Nobody needs to provide the links -we just have to download from ASM, format for Arctos and upload. I don't want to waste time doing this if using the GlobalNames version is good enough.
