### ISSUE TITLE
Feature Request - Add Manage Identifiers/Relationships to the Manage Tool in Search Results

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#7870]
Request: Add Manage Identifiers/Relationships to the Tools:Manage dropdown in Search Results https://arctos.database.museum/search.cfm

**Describe what you're trying to accomplish** 
Provide management and cleanup tools for specific groups of records from Search Results that operators can easily use to tackle project/accession level cleanup. 

**Describe the solution you'd like**
Currently we have these tools for the following, but given the need to clean up identifiers, it would be good to have a tool to do so from this interface.
![image](https://github.com/ArctosDB/arctos/assets/14808196/5ef6e7ff-7ce5-4563-bfe4-9b78308491d2)

**Describe alternatives you've considered**
Ask for DBA assistance for specific groups of records.

**Additional context**
_Add any other context or screenshots about the feature request here._

**Priority**
High. Needed for project completion and grant reporting.

**Comment by mkoo** [comment]
Would this new management tool bulk insert a new identifier? That's what most of the tools in the drop down do -- bulk add things to the result set. Or something else like bulk replace a value? For bulk unloading and loading we already have tools for that but we dont have a bulk replace. (except for bulk unload and load with the current tools) So I can see the value in that new bulk function. If this new function would make these identifier clean-up more amenable then it would warrant a high priority.

**Comment by campmlc** [comment]
Yes, I would hope they could add a new identifier with all metadata, such as relationships. I would also like to be able to use this edit ID type or relationship type or other metadata for existing identifiers. So yes, bulk replace is needed. And yes, I think it would be very useful to tackle identifier cleanup, and would help with social issues giving operators control over this process and allow smaller bits to be done at a time.

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/7871 has a recipe to do this (with lots of un-do steps available and under a mechanism which doesn't require more processors than I'll ever have available).
