### ISSUE TITLE
Convert parasite of relationships to AF, IF, NK numbers to "self"

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#7871]
@dustymc can you please convert any "parasite of" relationships to "self" in the following file: ONLY those that are NOT associated with an Arctos record GUID ID type (note - in this file, these should only be associated with NK, AF, or IF identifiers).

Related to #7808 cleanup and also to #7870 - if I had the latter, I would hope to be able to do this myself.

Priority: high

MSB:Para:38994,MSB:Para:39015,MSB:Para:39016,MSB:Para:39017,MSB:Para:39019,MSB:Para:39021,MSB:Para:39022,MSB:Para:39023,MSB:Para:39025,MSB:Para:39026,MSB:Para:39027,MSB:Para:39028,MSB:Para:39029,MSB:Para:39030,MSB:Para:39055,MSB:Para:39056,MSB:Para:39083,MSB:Para:39126,MSB:Para:39127,MSB:Para:39128,MSB:Para:39129,MSB:Para:39130,MSB:Para:39131,MSB:Para:39132,MSB:Para:39133,MSB:Para:39240,MSB:Para:39251,MSB:Para:39252,MSB:Para:39253,MSB:Para:39254,MSB:Para:39255,MSB:Para:39256,MSB:Para:39257,MSB:Para:39258,MSB:Para:39259,MSB:Para:39260,MSB:Para:39261,MSB:Para:39262,MSB:Para:39265,MSB:Para:39266,MSB:Para:39267,MSB:Para:39268,MSB:Para:39270,MSB:Para:39271,MSB:Para:39272,MSB:Para:39273,MSB:Para:39274,MSB:Para:39275,MSB:Para:39280,MSB:Para:39281,MSB:Para:39283,MSB:Para:39284,MSB:Para:39285,MSB:Para:39286,MSB:Para:39287,MSB:Para:39288,MSB:Para:39289,MSB:Para:39290,MSB:Para:39291,MSB:Para:39292,MSB:Para:39293,MSB:Para:39294,MSB:Para:39295,MSB:Para:39296,MSB:Para:39297,MSB:Para:39298,MSB:Para:39299,MSB:Para:39300,MSB:Para:39301,MSB:Para:39302,MSB:Para:39303,MSB:Para:39304,MSB:Para:39305,MSB:Para:39306,MSB:Para:44027,MSB:Para:44090,MSB:Para:44091,MSB:Para:44092,MSB:Para:44093,MSB:Para:44094,MSB:Para:44095,MSB:Para:44096,MSB:Para:44097,MSB:Para:44098,MSB:Para:44099,MSB:Para:44100,MSB:Para:44101,MSB:Para:44102,MSB:Para:44103,MSB:Para:44104,MSB:Para:44105,MSB:Para:44106,MSB:Para:44107,MSB:Para:44108,MSB:Para:44109,MSB:Para:44110,MSB:Para:44111,MSB:Para:44112,MSB:Para:44113,MSB:Para:44114,MSB:Para:44115,MSB:Para:44116,MSB:Para:44117,MSB:Para:44118,MSB:Para:44119,MSB:Para:44120,MSB:Para:44121,MSB:Para:44122,MSB:Para:44123,MSB:Para:44124,MSB:Para:44125,MSB:Para:44126,MSB:Para:44127,MSB:Para:44128,MSB:Para:44129,MSB:Para:44130,MSB:Para:44131,MSB:Para:44132,MSB:Para:44133,MSB:Para:44134,MSB:Para:44135,MSB:Para:44136,MSB:Para:44157,MSB:Para:44158,MSB:Para:44159,MSB:Para:44160,MSB:Para:44161,MSB:Para:44162,MSB:Para:44163,MSB:Para:44164,MSB:Para:44165,MSB:Para:44166,MSB:Para:44167,MSB:Para:44168,MSB:Para:44169,MSB:Para:44170,MSB:Para:44171,MSB:Para:44172,MSB:Para:44173,MSB:Para:44174,MSB:Para:44175,MSB:Para:44176,MSB:Para:44177,MSB:Para:44178,MSB:Para:44179,MSB:Para:44180,MSB:Para:44181,MSB:Para:44182,MSB:Para:44183,MSB:Para:44184,MSB:Para:44185,MSB:Para:44186,MSB:Para:44187,MSB:Para:44188,MSB:Para:44189,MSB:Para:44190,MSB:Para:44191,MSB:Para:44192,MSB:Para:44193,MSB:Para:44194,MSB:Para:44195,MSB:Para:44196,MSB:Para:44197,MSB:Para:44198,MSB:Para:44199,MSB:Para:44200,MSB:Para:44201,MSB:Para:44202,MSB:Para:44203,MSB:Para:44204,MSB:Para:44208,MSB:Para:38964,MSB:Para:38965,MSB:Para:38972,MSB:Para:38976,MSB:Para:38977,MSB:Para:38978,MSB:Para:38979,MSB:Para:38980,MSB:Para:38981,MSB:Para:38982,MSB:Para:38983,MSB:Para:38984,MSB:Para:38992,MSB:Para:38993,MSB:Para:38998,MSB:Para:38999,MSB:Para:39000,MSB:Para:39001,MSB:Para:39002,MSB:Para:39003,MSB:Para:39004,MSB:Para:39009,MSB:Para:39010,MSB:Para:39011,MSB:Para:39012,MSB:Para:39013,MSB:Para:39014,MSB:Para:39018,MSB:Para:39020,MSB:Para:39024,MSB:Para:39031,MSB:Para:39032,MSB:Para:39033,MSB:Para:39034,MSB:Para:39035,MSB:Para:39036,MSB:Para:39037,MSB:Para:39038,MSB:Para:39042,MSB:Para:39049,MSB:Para:39050,MSB:Para:39051,MSB:Para:39057,MSB:Para:39058,MSB:Para:39063,MSB:Para:39089,MSB:Para:39090,MSB:Para:39091,MSB:Para:39092,MSB:Para:39093,MSB:Para:39094,MSB:Para:39095,MSB:Para:39096,MSB:Para:39097,MSB:Para:39098,MSB:Para:39099,MSB:Para:39100,MSB:Para:39101,MSB:Para:39102,MSB:Para:39103,MSB:Para:39104,MSB:Para:39105,MSB:Para:39106,MSB:Para:39107,MSB:Para:39108,MSB:Para:39109,MSB:Para:39110,MSB:Para:39111,MSB:Para:39112,MSB:Para:39113,MSB:Para:39114,MSB:Para:39115,MSB:Para:39116,MSB:Para:39117,MSB:Para:39118,MSB:Para:39119,MSB:Para:39120,MSB:Para:39121,MSB:Para:39122,MSB:Para:39123,MSB:Para:39124,MSB:Para:39125,MSB:Para:39196,MSB:Para:39263,MSB:Para:39264,MSB:Para:39282,MSB:Para:44028,MSB:Para:44029,MSB:Para:44030,MSB:Para:44031,MSB:Para:44032,MSB:Para:44033,MSB:Para:44034,MSB:Para:44035,MSB:Para:44036,MSB:Para:44037,MSB:Para:44038,MSB:Para:44039,MSB:Para:44040,MSB:Para:44041,MSB:Para:44042,MSB:Para:44043,MSB:Para:44044,MSB:Para:44045,MSB:Para:44046,MSB:Para:44047,MSB:Para:44048,MSB:Para:44049,MSB:Para:44050,MSB:Para:44051,MSB:Para:44052,MSB:Para:44053,MSB:Para:44054,MSB:Para:44055,MSB:Para:44056,MSB:Para:44057,MSB:Para:44058,MSB:Para:44059,MSB:Para:44060,MSB:Para:44061,MSB:Para:44062,MSB:Para:44063,MSB:Para:44064,MSB:Para:44065,MSB:Para:44066,MSB:Para:44067,MSB:Para:44068,MSB:Para:44069,MSB:Para:44070,MSB:Para:44071,MSB:Para:44072,MSB:Para:44073,MSB:Para:44074,MSB:Para:44075,MSB:Para:44076,MSB:Para:44077,MSB:Para:44078,MSB:Para:44079,MSB:Para:44080,MSB:Para:44081,MSB:Para:44082,MSB:Para:44083,MSB:Para:44084,MSB:Para:44085,MSB:Para:44086,MSB:Para:44087,MSB:Para:44088,MSB:Para:44089,MSB:Para:44137,MSB:Para:44138,MSB:Para:44139,MSB:Para:44140,MSB:Para:44141,MSB:Para:44142,MSB:Para:44143,MSB:Para:44144,MSB:Para:44145,MSB:Para:44146,MSB:Para:44147,MSB:Para:44148,MSB:Para:44149,MSB:Para:44150,MSB:Para:44151,MSB:Para:44152,MSB:Para:44153,MSB:Para:44154,MSB:Para:44155,MSB:Para:44156,MSB:Para:44205,MSB:Para:44206,MSB:Para:44207

**Comment by campmlc** [comment]
[Somiya Eckerlin mites to fix parasite of IF AF NK.zip](https://github.com/user-attachments/files/15826160/Somiya.Eckerlin.mites.to.fix.parasite.of.IF.AF.NK.zip)

**Comment by dustymc** [comment]
This should be very easy to do, and is likely to work much better with familiar eyes on it.

1. Find records
2. Choose tools/identifiers
3. Filter however you need to
4. Download for the unloader, review/load/let it unload
5. Use the other options to reload (and this is a slightly less "prone to irrecoverable disasters" operation so you can skip the middle steps)

**Comment by Jegelewicz** [comment]
loaded identifiers with self relationship.

[Somiya relationship fixes.csv](https://github.com/user-attachments/files/16072864/Somiya.relationship.fixes.csv)

**Comment by Jegelewicz** [comment]
unload identifiers with parasite of relationship.

[Somiya relationship fixes unload.csv](https://github.com/user-attachments/files/16072877/Somiya.relationship.fixes.unload.csv)

**Comment by Jegelewicz** [comment]
The new ones will not load. @dustymc why are these throwing this error?

`load fail::ERROR: column "other_id_number" of relation "coll_obj_other_id_num" does not exist   Position: 109`

data is in the tool

https://arctos.database.museum/loaders/BulkloadOtherId.cfm

**Comment by Jegelewicz** [comment]
These all now have a "self" version. Putting the other relationships in the unloader now.

https://github.com/ArctosDB/arctos/issues/7871#issuecomment-2204027664

**Comment by Jegelewicz** [comment]
These are done
