### ISSUE TITLE
Feature Request - can we get at least surname as a search field for agents?

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#7874]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

No way to limit search to perfect matches of surnames on agent search form

**Describe what you're trying to accomplish** 
_A clear and concise overview of the goals; why are you asking for this?_

More precise search results

**Describe the solution you'd like**
_How might we accomplish your goals?_

Add surname (last name) as a search field 

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

page through far too many results that are not matches

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._
normal

**Comment by DerekSikes** [comment]
PS - per the best practices of database results display can we get a count of found agents along with the results for each search too?

**Comment by Jegelewicz** [comment]
@DerekSikes that is already available.

![image](https://github.com/ArctosDB/arctos/assets/5725767/53996e04-001a-45cb-8a7b-a6341e9813ee)

Select attribute type `last name` and put whatever name you want in attribute value.

**Comment by dustymc** [comment]
>More precise search results

There are currently 616 person-agents without a last name (and some of them clearly aren't persons, so probably more hiding in all sorts of interesting places); if this search might result in creation, more precision is very likely a path to more duplicates. https://github.com/ArctosDB/arctos/issues/7649

>best practices of database results display 

Is there something you'd like to share??

>count of found agents

In next release.

**Comment by DerekSikes** [comment]
Ah, thanks! Just another case of nonintuitiveness tripping me up.

**Comment by mkoo** [comment]
Actually this brings up a UI thing-- can you make sure the attribute dropdown and its value field are in the same div or whatever so they are side-by-side? it should not break across a line since it's confusing enough that the two are tied together. You could just add a break in front of the attribute dropdown perhaps to get it to go to the next line always?

**Comment by Jegelewicz** [comment]
I think we are done here.
