### ISSUE TITLE
Need Help with Arctos Error - "attribute_2 fail: units are not allowed for this attribute"

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#7876]
Trying to load catalog records from bulkloader and one failed & gave this error

# Error Text
**Copy the text from the page and paste it here**

"attribute_2 fail: units are not allowed for this attribute"

# Where it happened
**Provide a link to or a description of the page where the error occurred.**

https://arctos.database.museum/Bulkloader/editBulkloader.cfm?key=key_4641186

I searched for "attribute_2" on the page and it was not found, except in the error. Thus I don't know which attribute has units that are not allowed.

Also, how is this possible? When an attribute with units is chosen the units become available to edit, when an attribute without units is chosen the units are not available to edit. How did units get added to an attribute that does not allow them?

**Comment by dustymc** [comment]
The warning at the top of the screen attempts to address this and provides a solution.

https://arctos.database.museum/Bulkloader/browseBulk.cfm?key=key_4641186

<img width="826" alt="Screenshot 2024-06-17 at 09 25 47" src="https://github.com/ArctosDB/arctos/assets/5720791/7d64f93a-bdc9-4317-b669-23fc8c9f963d">

>how is this possible

You're using a UI which makes assumptions the data structure doesn't enforce (hence the warning). The data were likely created with some other UI.

**Comment by DerekSikes** [comment]
wait a minute. Are you telling me that attribute_2_type = life stage and attribute_2_value = adult attribute_2_units = individuals is to blame?

Please just say what I need to do to fix this error.

**Comment by dustymc** [comment]
Remove the units, categorical attributes cannot have units. The browseBulk link above provides a means to do so.

**Comment by DerekSikes** [comment]
![Screenshot 2024-06-17 at 9 37 31 AM](https://github.com/ArctosDB/arctos/assets/9099827/51177574-c978-436d-8081-f58e68078021)

The units are for individual count, not life stage, how do I remove units for life stage (assuming you intended to answer my y/n question with a y)

**Comment by DerekSikes** [comment]
I had hoped to have these loaded by now so I can download the data & prepare labels for a lab tech. I still don't understand how to fix this. "The browseBulk link above provides a means to do so." does not help me.

**Comment by dustymc** [comment]
Click https://arctos.database.museum/Bulkloader/browseBulk.cfm?key=key_4641186

Change this:
<img width="696" alt="Screenshot 2024-06-17 at 11 22 03" src="https://github.com/ArctosDB/arctos/assets/5720791/26dd89b8-3e25-4544-8d13-a0586261af10">

to this:

<img width="797" alt="Screenshot 2024-06-17 at 11 22 14" src="https://github.com/ArctosDB/arctos/assets/5720791/46cb22fe-9292-4512-9874-9358c4ec0234">

which I've done, and hopefully that's what you intend/wish for.
