### ISSUE TITLE
Need Help with Arctos Error - Chrome does not like Data Entry Page

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#7878]
# Error Text
**Copy the text from the page and paste it here**
iframe url does not have permission to interact with me

# Where it happened
**Provide a link to or a description of the page where the error occurred.**
https://arctos.database.museum/Bulkloader/enter.cfm

# Steps to get there
**Describe the actions that led to the error**
I log into Arctos on Chrome, and I can go to all the other pages I've tried in the Tools menu, but when I try and go to Create a New Record I get a pop-up window that has the text "iframe url does not have permission to interact with me". I click OK and the text just pop's up again. I can't do anything by close the window.

The same thing happens if I try and go to the edit page from Browse and Edit entries.

When I open Sarai and Firefox I do not have the same problem. I've cleared my cache, and I have't added any new add ons.

# Problem
**Community response to describe the problem that caused the error**

I can't do any data entry or editing from the single data entry screen in Chrome.
Any help, greatly appreciated.

<img width="1792" alt="Screenshot 2024-06-17 at 13 36 50" src="https://github.com/ArctosDB/arctos/assets/18562884/603bb7fa-e4b3-460d-a734-c082139d4872">

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues?q=is%3Aissue+iframe+url+does+not+have+permission+to+interact+with+me

Someone or something (probably some extension) is messing with your network traffic.

**Comment by ewommack** [comment]
Bluurrgg, ok let me know if I can figure it out. I haven't added any new ones in a long while, so maybe it is something new in the network at work?

**Comment by mkoo** [comment]
same old routine (https://github.com/ArctosDB/arctos/issues/7665) 
Turn off all your extensions then turn them back on one by one testing the web page with a reload each time before you find the culprit. You can also set up separate profiles in Chrome with different extensions enabled. Can we close?

**Comment by Jegelewicz** [comment]
This needs a FAQ? It comes up about every other month.

**Comment by dustymc** [comment]
https://handbook.arctosdb.org/documentation/understanding-errors.html#iframe-url-does-not-have-permission-to-interact-with-me

**Comment by Jegelewicz** [comment]
Yeah I know, but nobody ever finds that?

Maybe that thing needs to be FAQ and it needs to somehow be easier to find?

Not saying I have answers, just wondering.....

**Comment by dustymc** [comment]
I don't care where it lives or what it's called, but the correct number of 'where to look when I get an error' documents will always be one.

That one has been hard to find because it didn't exist until this issue was filed, and "there needs to be a FAQ" thinks I.

**Comment by ewommack** [comment]
> same old routine (https://github.com/ArctosDB/arctos/issues/7665)
Turn off all your extensions then turn them back on one by one testing the web page with a reload each time before you find the culprit. You can also set up separate profiles in Chrome with different extensions enabled. Can we close?

So calling it same old routine is fine, but I literally did not do anything different from one day to the next, and suddenly I have this error. That is going to make people think there is a bug no matter what you say. 
Is this something Arctos or TACC is doing that suddenly is not working with Chrome.

**Comment by dustymc** [comment]
> Is this something Arctos or TACC is doing that suddenly is not working with Chrome?

No, this is something that is happening between your browser and geolocate; your browser is asking geolocate for information and getting back something from someone who isn't geolocate. Someone is manipulating your network traffic. 

I don't know how to make the error explainer more clear.

FWIW if I got this I'd drop EVERYTHING to track it down, and then probably change all of my passwords.

**Comment by ewommack** [comment]
> No, this is something that is happening between your browser and geolocate; your browser is asking geolocate for information and getting back something from someone who isn't geolocate. Someone is manipulating your network traffic.

That makes less sense to me. I never accessed Geolocate or got anywhere close to the tool. I've also tried it on different networks, and the error is the same. It also does not happen on different browsers, so how can it be a network thing but only happening on one browser?

> FWIW if I got this I'd drop EVERYTHING to track it down, and then probably change all of my passwords.

This is also less helpful. Are you saying this is a major security warning? For what? For networks, for computers, for Arctos?

**Comment by dustymc** [comment]
Thanks, doc updated.

**Comment by ewommack** [comment]
The one thing I would add is that it can happen suddenly, even if you have not added a new extension. I guess it is a change from an old extension. 
For me it turned out to be the Zotero extension. Which is super helpful because it lets me grab articles and add them to my Zotero app on my computer. I go rid of it and downloaded it again directly, but it still is causing problems. The good thing is if I turn it off while I am using Arctos, then Arctos is happy. So I will just have to remember to turn it on when I need to download a paper.
