### ISSUE TITLE
add barcode to review loan items

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#788]
Allows for check to make sure correct part was added to loan

**Comment by campmlc** [comment]
for example: http://arctos.database.museum/loanItemReview.cfm?transaction_id=21109999

**Comment by campmlc** [comment]
I have verbal confirmation from other collection managers that this is important to other genomics collections. When we have multiple tissue samples, we need to know which particular sample was brought to room temperature for a loan in order to assess tissue quality over time, eg how many times a sample has been defrosted. The only way to track this is via the barcode, which is not currently displayed in the loan documentation.

**Comment by dustymc** [comment]
I do not understand this request. The entire, whole, and only point of barcodes is so that machines may read from the physical world. That is generally not accomplished via screens. The human error rate of reading barcodes - especially those using weird "names" - cannot possibly be anything other than horrendous. There are very many ways of using barcodes to know the exact history of a part (and to facilitate the loan process in general), but this from here does not look like one of them.

**Comment by campmlc** [comment]
This should be a very simple request. Both Kyndall at UAM and I need to be
able to see what specific part was included in a loan - usually, what part
was subsampled and hence, which came up in temperature. This is critical in
determining which parts should be included or not included in future loans,
depending on the tissue quality requested. When we have several parts of
the same tissue, e.g. multiple cryovials of liver (frozen), the only way to
determine which exact tube was included in a loan is to be able to see the
barcode of the part in the loan documentation.
Mariel

**Comment by dustymc** [comment]
>This should be a very simple request

Even if that were true, "it's easy" has never been a reason to build something. I'm not going to get into the habit of creating things I don't fully understand - that ALWAYS leads to frustration for someone (usually everyone), and needs dealt with in the planning phase.

>what part was subsampled 

Those data exist, but they're not in the barcode of what's being loaned. Subsamples usually/sometimes don't get a barcode - you'd need something like the entire part and parent-of-part-barcode hierarchies to ensure you have those data. (I think they're USUALLY in the immediate parent part's parent container but "usually" might be extremely confusing when you're looking at an exception.)

>only way to determine which exact tube was included in a loan is to be able to see the barcode of the part in the loan documentation

Where there are subsamples involved (unless you're barcoding subsamples, which does not always/usually happen), the loaned part has no barcode. (See below.) Maybe we should sprinkle "used in LOANNUMBER" around a bit more (eg, in specimendetail where parts are already displayed hierarchically)?

Perhaps the structure of a subsample is unclear. Subsamples are parts with "derived from part" data. Bits of tissue for loan is probably the most common use, but it's far from the only one. There is no limit on the depth of the hierarchy - the "originating" part (and in some cases probably the barcode that provides at least some of the information I think you're looking for here) may be any number of "parents" away from any given "child" part. Subsamples may be created for any reason from any part - I don't think it's safe to make any assumptions regarding their origins.

Perhaps somewhat unrelated, I don't think that sampling itself is a generally-useful indication of tissue quality. Given decent tools and procedures, time at temperature shouldn't change appreciably (for some things). I can imagine that's much less true for eg, digging parasites out of mouse-bits or organs out of whole frozen animals (which I don't think we usually record as a "subsampling" - we probably should). With a little massaging of the container model, we could log the temperature (and whatever else) of containers, and you could record the ACTUAL (given adequate sensors) time at temperature (or humidity or fluid composition or WHATEVER) for anything/everything. I realize you probably aren't going to get temperature sensors in your sampling blocks anytime soon and that this probably won't address your immediate needs, just a potential tool to keep in mind.

Below are the parts and their barcodes (all NULL) used for loan MSB:Mamm 2015.073.Mamm. In this case I believe you want the barcode of the container holding the part from which the loaned part was derived, but see above - I'm not sure that's generally useful, and I think it might be extremely confusing when the barcode you want is elsewhere (eg, when samples are resampled, parts are loaned without sampling, etc.).

Perhaps if nothing above is sufficient (adding "used in LOAN" to specimen detail parts grid seems most comprehensive to me??) we could add multiple "barcode" columns to the review parts form:

- barcode of the part
- barcode of the part from which loaned part was derived
- whatever else is useful....

Is that an unambiguous/non-confusing usually-what-you-need approach??

select
  part_name || ' barcode ' || ppartc.barcode
from
  specimen_part,
  loan_item,
  coll_obj_cont_hist,
  container partc,
  container ppartc
where
  specimen_part.collection_object_id=loan_item.collection_object_id and
  loan_item.transaction_id=21109999 and
  specimen_part.collection_object_id=coll_obj_cont_hist.collection_object_id and
  coll_obj_cont_hist.container_id=partc.container_id and
  partc.parent_container_id=ppartc.container_id (+)
 15  ;

PART_NAME||'BARCODE'||PPARTC.BARCODE
------------------------------------------------------------------------------------------------------------------------
liver (frozen) barcode
liver (frozen) barcode
liver (frozen) barcode
liver (frozen) barcode
liver (frozen) barcode
liver (frozen) barcode
liver (frozen) barcode
liver (frozen) barcode
liver (frozen) barcode
liver (frozen) barcode
liver (frozen) barcode
liver (frozen) barcode
liver (frozen) barcode
liver (frozen) barcode
liver (frozen) barcode
liver (frozen) barcode
liver (frozen) barcode
liver (frozen) barcode
liver (frozen) barcode
liver (frozen) barcode
liver (frozen) barcode
skin barcode

22 rows selected.

**Comment by campmlc** [comment]
Yes:" I want the barcode of the container holding the part from which the
loaned part was derived" to show up on the review loan items form. We can
see which part was subsampled when we look at the catalog record, because
there is an indent. But there is no way to determine that from the loan
form. Any way you can come up with to track which part was subsampled for
each loan would be very useful. And yes, subsampling does involve taking a
tissue out of the freezers for at least 5-10 minutes, if not more, and
since no Arctos collection to my knowledge has a room-size robot-arm
automatic tissue sampling freezer, the sampled tube will be handled by
human hands and will definitely increase in temperature during this
process. I need to know how many times a sample has been subsampled for
this reason.

**Comment by dustymc** [comment]
>Yes:" I want the barcode of the container holding the part from which the loaned part was derived"

I'll see what i can come up with.

>We can see which part was subsampled when we look at the catalog record, because there is an indent.

In the simplest case, yes - if you've sent 9 of the 12 liver samples out on various loans, though....

I'll try to add "used in LOAN" to the specimen page, somewhere. Maybe I can figure out how to link the barcode in the loan form to that.

>subsampling does involve taking a tissue out of the freezers for at least 5-10 minutes

But none of that's very informative. Pull it out of your +20 freezer, go to lunch, accidentally drop it in your coffee, find it hiding under the freezer a week later, ... vs. pull the tube and your big aluminum block out of nitrogen, sample the tube from the frozen block, chuck it all back in LN2 - it's the same data, but one MAYBE got the very edges up to "ultracold temperatures" very briefly while the other is aged and cooked. There's also no way of knowing if the latter was once handled like the former - we just have "it's in a freezer" data. 

https://github.com/ArctosDB/arctos/issues/800

**Comment by campmlc** [comment]
thanks -
perhaps we could do "used in LOAN 2015.015.Mamm" from part detail - tie the
part/subsample to a specific loan. Right now, we know that there are loans
associated with a cataloged item, but not which parts/part subsamples went
to what loan on what date.

And yes, logging the continuous temperature exposure of a sample from
moment of collection through the lifetime of the sample is the gold
standard, and explicitly stated in best practices - figuring out how to do
that would be very worthwhile.
