### ISSUE TITLE
Need Help with Arctos Error

### ISSUE THREAD

**Issue by megulbranson** [ArctosDB/arctos#7882]
# Error Text
column "agent_name_type" does not exist42703

# Where it happened
Bulkload Catalog Records: this is the status I received on all records in the .csv I uploaded.

# Steps to get there
I uploaded my data to the bulkloader. see attached .csv

# Problem
I have not encountered this error before and do not know what I need to fix.

# Solution
If someone is familiar with this error, any help would be appreciated!
[2022.028 downloaded data from bulkloader.csv](https://github.com/user-attachments/files/15905381/2022.028.downloaded.data.from.bulkloader.csv)

**Comment by dustymc** [comment]
I wiggled the wires, try again - and please email me whatever you uploaded (or leave it in the loader) if that doesn't do it.

**Comment by megulbranson** [comment]
It worked, thank you!
