### ISSUE TITLE
Error when entering records: column "agent_name_type" does not exist42703

### ISSUE THREAD

**Issue by kmkocot** [ArctosDB/arctos#7883]
Hi all,

My student Hayden (@hrwalls-crimson on GitHub) and I are having an issue with the error "agent_name_type" does not exist42703 when entering data into Arctos.

**Describe the bug**
We are entering records into the ALMNH:Inv collection and getting the error message described above. Example records we attempted to enter that are resulting in this error include:
edit key_4641711
edit key_4641552
edit key_4641726
edit key_4641203
edit key_4641561
edit key_4641278

It's not clear to us what these particular records have in common relative to other records that are not giving this error. The term "agent_name_type" doesn't appear on the page or when you inspect the html nor does it appear in the Browse/Edit Bulkloader table page so we are stumped.

We attempted to monkey around with this record to get rid of this error to no avail (PDF attached in case you cannot access that page):
https://arctos.database.museum/Bulkloader/editBulkloader.cfm?key=key_4641711
[Edit Bulkloader Records.pdf](https://github.com/user-attachments/files/15905468/Edit.Bulkloader.Records.pdf)

**To Reproduce**
See PDF with the contents of fields we entered.

**Expected behavior**
We are able to save modifications to this page but cannot get rid of the error message. We would like to be able to fix these records to load them without re-entering them.

Thank you!
Kevin

**Comment by dustymc** [comment]
Duplicate of https://github.com/ArctosDB/arctos/issues/7882 and hopefully fixed - let me know if you're still having any problems.

**Comment by kmkocot** [comment]
All good now! Thank you!
