### ISSUE TITLE
New Operator Login Error - Password Reset Not Working

### ISSUE THREAD

**Issue by starkeyra** [ArctosDB/arctos#7889]
Hi! I was recently added as an operator in Arctos, but today when I logged in it came up with the error "Authentication failed. Additional Information: Insufficient privileges."

When I reset my password, I copied the temporary password exactly, but it still produces the same error. This is occurring in Google Chrome Version 126.0.6478.63. Any help is appreciated!

**Comment by Jegelewicz** [comment]
@starkeyra I haven't assigned you any permissions yet - I'll do that, and then it should work.
