### ISSUE TITLE
Need Help with Arctos Error: Higher Geography in Data Entry screen

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#7890]
# Error Text
024-6-21T11:18:18: FAIL: locality_higher_geog matches 0 records: {"message":"locality_higher_geog matches 0 records","status":"fail"}

# Where it happened
Data entry page

# Steps to get there
I'm creating a new record with no geography information associated with a place of creation (e.g., unknown verbatim and "no specific locality recorded." for the two locality fields. I have set my custom page to carry the locality info from previously created records. However, I'm not sure how to get rid of the higher geography "ghost data" when creating a record with no info after saving one that had info. I used the "clear all locality" button thinking that was my magic card, but I still got this error. I had to assign a higher geography of "United States" in order to save, but I have no way of knowing if that is correct or not.

# Problem
I shouldn't have to enter fake higher geography in order to save a record with no locality information.
<img width="1676" alt="Screenshot 2024-06-21 at 11 19 00 AM" src="https://github.com/ArctosDB/arctos/assets/17605945/689baaf0-a036-4d15-95c7-ab3852533702">

# Solution
Is there a way to truly clear out the higher geography or is there an approved "no higher geography" option to select that I've forgotten about?

**Comment by dustymc** [comment]
https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=69 or https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10016350 should work - https://handbook.arctosdb.org/documentation/higher-geography.html#other-options

>"no specific locality recorded."

"No specific locality recorded." is correct - https://handbook.arctosdb.org/documentation/locality.html#specific-locality

**Comment by AJLinn** [comment]
Thanks - I'll try that next time. I think I tried some variation that was not a match so I stopped looking. I'll make a post-it note to keep on my machine to remind me of this solution.
Appreciate the fix!

**Comment by AJLinn** [comment]
Oops, spoke too soon. How do I get it into the field? Fails to find anything in the popup and I get an error if I try to force it.

<img width="1209" alt="Screenshot 2024-06-21 at 1 39 07 PM" src="https://github.com/ArctosDB/arctos/assets/17605945/f0fb30db-53a0-4f7e-a704-5dfbd2511ce0">


<img width="1676" alt="Screenshot 2024-06-21 at 1 37 29 PM" src="https://github.com/ArctosDB/arctos/assets/17605945/d54dce13-9cba-4493-bc66-4c3e7014dc2d">

**Comment by dustymc** [comment]
<img width="257" alt="Screenshot 2024-06-21 at 15 09 15" src="https://github.com/ArctosDB/arctos/assets/5720791/997ff72a-8a82-40cc-9a37-f4c918d39903">

Change that.

**Comment by AJLinn** [comment]
:-(
What am I doing wrong?
<img width="1209" alt="Screenshot 2024-06-21 at 2 48 19 PM" src="https://github.com/ArctosDB/arctos/assets/17605945/fefa8acb-ee44-4ab8-9a90-578166a79f1a">

**Comment by dustymc** [comment]
Happy?

**Comment by AJLinn** [comment]
Sorry I didn't close it last week. It did work, I think... though when I checked them this morning, the records looked like this... new issue or symptom of something with my data?

<img width="1367" alt="Screenshot 2024-06-26 at 6 44 28 AM" src="https://github.com/ArctosDB/arctos/assets/17605945/08857f50-62f3-48e6-9f38-48bac994cb98">

**Comment by AJLinn** [comment]
All clear now, loaded up and "no higher geography recorded" listed in the HG field. Thanks
