### ISSUE TITLE
Search results: Tools: reload with shareable URL gives 431 error

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#7892]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Trying to share search results with a shareable url gives a 431 error

**Expected behavior**
for this to work as usual. Needed for USGS report.

**Screenshots**

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by mkoo** [comment]
Too much stuff in your URL! Try trimming your parameters? Is there another way to set this up like a project with a data loan?
happy to discuss

**Comment by campmlc** [comment]
Actually the problem disappeared a little while after I filed the issue. Not sure what was up, but closing.
