### ISSUE TITLE
Arctos OFFLINE - Wed 6/26 at 3 pm Central/ 1 pm Pacific

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#7897]
## Planned Outage
 - Date and time outage will begin: 3 pm Central Wed June 26th
 - Date and time outage is expected to end: 5 pm Central Wed June 26th
 - Reason for outage: needed database replication, backup, maintenance
 - Expected behavior during and after the outage: Arctos database platform will be unavailable

Note that Wednesdays are our lowest traffic day of the week (outside of weekends when you should be giving database work a break!)
Sorry for the late notice but doing so immediately will hopefully avoid worst case scenarios

## Communication before/during outage
- [x] Pin this issue
- [x] Banner updated @jegelewicz @mkoo
- [x] Email sent to AWG  
- [x] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [x] Unpin this issue
- [x] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG 
- [x] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by ewommack** [comment]
Sent email and have an email going out Wednesday morning at 0800 MT

**Comment by dustymc** [comment]
Arctos is back up.

**Comment by mkoo** [comment]
@dustymc if you’re in the db pls take down banner! Thx

Sent on the go
