### ISSUE TITLE
Collection object not linked to catalog record

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#7900]
I am trying to process a loan of a sample whose barcode is in MSB object tracking, and the barcodes for this record are linked to multiple collection objects with the correct catalog number/DwC triplet. But that catalog number does not show up in a search, and the collection objects are not linked to any catalog record. Not sure how this happened, or whether it is something we need to fix on our end?
See 
https://arctos.database.museum/findContainer.cfm?container_id=23892751
[container_contents_download (30).zip](https://github.com/user-attachments/files/15992803/container_contents_download.30.zip)
![Screenshot 2024-06-26 11 11 09](https://github.com/ArctosDB/arctos/assets/14808196/56fc4a84-a004-4884-91fe-d2564a536f4b)

**Comment by campmlc** [comment]
Also, from an object tracking Find Container search on the barcode, if I click Flatten Part Container, I get the following, which implies there is a catalog record linked to the part and PLPath. But if I click the blue Guid link, I get an error.
![Screenshot 2024-06-26 11 31 32](https://github.com/ArctosDB/arctos/assets/14808196/4781e896-6dd0-4ef3-b425-4a1c6b74ef9d)

**Comment by Jegelewicz** [comment]
@campmlc as far as I can tell, you don't have access to the msb herp collection.....

**Comment by campmlc** [comment]
Actually, I do have access. And the same thing was happening to the collection manager for MSB:Herps. However, after about 25 minutes the record did show up. No idea why there was the odd lag, but it seems to have resolved itself.
