### ISSUE TITLE
delete media files from TACC please

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#7901]
Can someone who has access please delete these two media files?

sftp://data.tacc.utexas.edu/corral/projects/arctos/system/obj/nicoleridgwell/2024-06-26/NMMNH_Paleo_34921_2024_04_15_JH_1.tif
sftp://data.tacc.utexas.edu/corral/projects/arctos/system/obj/nicoleridgwell/2024-06-26/NMMNH_Paleo_34921_2024_04_15_JH_2.tif

I uploaded them individually via the catalog record page, and I don't have permissions to edit that part of the TACC storage, so I can't delete them myself. I meant to load these at a much lower file size, but I had a moment and read Mb as Kb. I've deleted the media record in Arctos already.

**Comment by dustymc** [comment]
resolved in https://github.com/ArctosDB/internal/issues/324#issuecomment-2197134237
