### ISSUE TITLE
Code Table Request -  New part atribute type (ctpreparation_method): 10–30  µmol photons m−2 s−1

### ISSUE THREAD

**Issue by RJSS8** [ArctosDB/arctos#7908]
### Goal
_Describe what you're trying to accomplish. This is the only necessary step to start this process. The Committee is available to assist with all other steps. Please clearly indicate any uncertainty or desired guidance if you proceed beyond this step._

Add a new preparation method needed for the parts in our collection.

### Context
_Describe why this new value is necessary and existing values are not._

Being that it's specific to its part and a piece of integral information needed and also used for organization between our collection specimens.

### Table
_Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table or value. This may involve multiple tables and will control datatype for Attributes. OtherID requests require BaseURL (and example) or explanation. Please ask for assistance if unsure._

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpreparation_method

### Proposed Value
_Proposed new value. This should be clear and compatible with similar values in the relevant table and across Arctos._

10–30   µmol photons m−2 s−1

### Proposed Definition
_Clear, complete, non-collection-type-specific **functional** definition of the value. Avoid discipline-specific terminology if possible, include parenthetically if unavoidable._

The term “µmol photons m⁻² s⁻¹” refers to the number of photosynthetically active photons (individual particles of light in the 400-700 nm range) delivered to a specific area over a 24-hour period. It is commonly used to describe the light environment for plants.
In this case, it represents the light intensity interval which strains in our collection are kept in

#### Part preservation attribute affect on "tissueness"
_if a new part preservation is requested, please add the affect it would have on "tissueness": No Influence, Allows, or Denies_

### Priority
_Please describe the urgency and/or choose a priority-label to the right. You should expect a response within two working days, and may utilize [Arctos Contacts](https://arctosdb.org/contacts/) if you feel response is lacking._

### Example Data
_Requests with clarifying sample data are generally much easier to understand and prioritize. Please attach or link to any representative data, in any form or format, which might help clarify the request._

### Available for Public View
_Most data are by default publicly available. Describe any necessary access restrictions._

### Helpful Actions

- [ ] Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

- [ ] Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

@ArctosDB/arctos-code-table-administrators 

## Approval
_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [ ] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [ ] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection
_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation
_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

- [ ] Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

- [ ] Add or revise the code table term/definition as described above. Ensure the URL of this Issue is included in the definition. URLs should be included *_as text_*, separated by spaced pipes. Do not include HTML in definitions.

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by Jegelewicz** [comment]
I don't think this has anything to do with collecting event - it is the way a cell culture is maintained.

**Comment by dustymc** [comment]
>way a cell culture is maintained


water temperature [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_event_attr_type#water_temperature)

relative humidity [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_event_attr_type#relative_humidity)

It's (maybe!) the same sort of information at those things, maybe it belongs in the same place.

**Comment by Jegelewicz** [comment]
It does not happen during the event - it is an attribute of how the culture is maintained or stored over time.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
This seems more akin to container environment?

**Comment by Jegelewicz** [comment]
IF you are using object tracking....and they are not.

**Comment by Jegelewicz** [comment]
@ArctosDB/arctos-code-table-administrators this collection would like to get some data entered, but needs new terms. I am unable to make the meeting on Thursday due to family obligations. Can we discuss this asynchronously and get them moving?

**Comment by dustymc** [comment]
@ArctosDB/arctos-code-table-administrators discussed https://docs.google.com/document/d/1eZ_S8VTp-m5Wrbb6cAK96ODPZpt2-Hvnvt6yfU9qVwg/edit#heading=h.b75kqv2tbpim

yes this is ideally container environment (where the container is a room), but collection does not use object tracking, this is (or very nearly is) the only value.

These data are very much like https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecpart_attribute_type#storage_temperature.

@RJSS8 is also open to condition report, suspect searching the data isn't critical

Conclusion: close this, new condition report issue, closing.
