### ISSUE TITLE
Code Table Request - new part modifier: mesial

### ISSUE THREAD

**Issue by KatherineLAnderson** [ArctosDB/arctos#7912]
### Goal

Add mesial to the part modifier code table

### Context

This value doesn't exist and is useful for describing tooth parts (and mammal paleontologists really like teeth).

### Table

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_modifier

### Proposed Value

mesial

### Proposed Definition

``Toward anterior or mid-sagittal; the surface closest to the tooth in front of it. | https://berkeley.pressbooks.pub/morphology/chapter/teeth/ | https://github.com/ArctosDB/arctos/issues/7912``

~~refers to the surface of the tooth that is toward the front of the mouth
see also: https://www.merriam-webster.com/dictionary/mesial~~

### Priority

high--needed for data migration

### Helpful Actions

- [x] Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

- [ ] Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

@ArctosDB/arctos-code-table-administrators 

## Approval
_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection
_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation
_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

- [ ] Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

- [ ] Add or revise the code table term/definition as described above. Ensure the URL of this Issue is included in the definition. URLs should be included *_as text_*, separated by spaced pipes. Do not include HTML in definitions.

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by dustymc** [comment]
mesial==mid, not front, no??

"closest to the middle" from your link....

Same as https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_modifier#mid ??

**Comment by KatherineLAnderson** [comment]
> mesial==mid, not front, no??
> 
> "closest to the middle" from your link....
> 
> Same as https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_modifier#mid ??

I think the merriam webster definition is kind of confusing. It's referring to closest to the mid-line of the jaw (i.e., where the 2 sides of the jaw fuse), so instead of mesial meaning middle in the sense you'd think (which in teeth terms is called "lingual"), it means the surface of the tooth closest to the mid-line of the jaw or, in other words, the surface closest to the tooth in front of it.

Teeth are confusing which is why they have their own jargon. Like what is the middle of a tooth? It could mean the middle of the actual tooth, the "middle" surface of the tooth (which is what?), etc. This is why they have their own special words, and also why it sounds like your dentist is speaking in code to the hygienist.

**Comment by Jegelewicz** [comment]
suggest adding this to the definition

> the surface of the tooth closest to the tooth in front of it.

**Comment by dustymc** [comment]
>why it sounds like your dentist is speaking in code

I thought the Vietnamese was the confusing part!

>merriam webster definition is kind of confusing

So is there something better, maybe some sort of ontology or less "general public oriented" source? (We're creating a CONCEPT here, whatever we add to a code table should NEVER mean 'whatever the current user hopes,' good/functional/disambiguating definitions are critical.)

https://www.researchgate.net/publication/228511225_Tooth_Positional_Ontology_Represented_in_OWL suggests there might be such things (even if they're overly focused on the weirdest mammal...).

**Comment by Jegelewicz** [comment]
That paper describes a very limited ontology for 

`Positional_Value_Partition, which has six leaf subclasses:
Anterior, Posterior, Right, Left, Upper, and Lower. The
value of hasAP_Position is either Anterior or Posterior,
the value of hasRL_Position is either Right or Left, and
the value of hasUL_Position is either Upper or Lower`

not sure it helps out here.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
This might be a better reference to use: https://berkeley.pressbooks.pub/morphology/chapter/teeth/

**Comment by dustymc** [comment]
Possible frankendefinition:


``Toward anterior or mid-sagittal; the surface closest to the tooth in front of it. | https://berkeley.pressbooks.pub/morphology/chapter/teeth/ | https://github.com/ArctosDB/arctos/issues/7912``

**Comment by KatherineLAnderson** [comment]
Bump! Any further info needed for this request?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
box checked

**Comment by AJLinn** [comment]
box 2 checked

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Added.
