### ISSUE TITLE
Help Request - unload duplicate parts

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7915]
During data migration a set of parts was uploaded twice. There is no part unloader - should there be?

@dustymc can you remove these parts?

[remove duplicate parts.csv](https://github.com/user-attachments/files/16073344/remove.duplicate.parts.csv)

**Comment by dustymc** [comment]
>should there be?

https://github.com/ArctosDB/arctos/discussions/5231

>remove

Done.
