### ISSUE TITLE
Find Partless not working?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7916]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

Checking for partless records and I don't understand the error I get.

**To Reproduce**
1. Go to https://arctos.database.museum/info/noParts.cfm
2. Select ASUMZ:Invert
3. See error

<html><body>

ERROR_ID | 00979E66-64A3-474B-A5CF17F183AEC904
-- | --
ERROR_TYPE | application
ERROR_MESSAGE | Parent directory for [/usr/local/webroot/download/ArctosData_kq/CbNRVAO.csv] doesn't exist
ERROR_DETAIL |  

</body>
</html>

**Expected behavior**

A list of partless records or `no partless records found`

**Screenshots**

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 127.0.2 (64-bit)

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by dustymc** [comment]
Can't replicate.

**Comment by Jegelewicz** [comment]
OK it works for me today.
