### ISSUE TITLE
Remove ALMNH:ES identifiers

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7918]
> I would like to get rid of all "ALMNH:ES:xxxx" identifiers in the ALMNH:Paleo records. Nobody has used them in pubs and in the collection or will ever use them, unlike other identifiers that carry.

_Originally posted by @aklompma in https://github.com/ArctosDB/data-migration/issues/154#issuecomment-2204848729_

**Comment by Jegelewicz** [comment]
unloaded with this file

[Remove_ALMNH_ES_identifiers.csv](https://github.com/user-attachments/files/16087000/Remove_ALMNH_ES_identifiers.csv)

**Comment by Jegelewicz** [comment]
I'll close this when the component loader finishes, it's taking forever...

**Comment by aklompma** [comment]
Thanks!

**Comment by Jegelewicz** [comment]
Done!
