### ISSUE TITLE
Help request - add a determiner to existing identifications

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7919]
From https://github.com/ArctosDB/data-migration/issues/1693#issuecomment-2145062355

@dustymc can you add a determiner of [David Brito-Zapata](https://arctos.database.museum/agent/21350192) to the identifications in these records?

[search url](https://arctos.database.museum/search.cfm?guid_prefix=ZSFQ%3AHerp&cat_num=754%2C611%2C629%2C638%2C639%2C646%2C675%2C688%2C711%2C713%2C725%2C730%2C731%2C737%2C744%2C004%2C009%2C011%2C020%2C024%2C025%2C026%2C027%2C028%2C029%2C030%2C053%2C054%2C056%2C066%2C071%2C073%2C074%2C095%2C096%2C097%2C098%2C099%2C100%2C101%2C102%2C103%2C104%2C105%2C106%2C107%2C108%2C109%2C120%2C121%2C126%2C145%2C235%2C366%2C367%2C368%2C376%2C377%2C378%2C379%2C380%2C381%2C384%2C385%2C386%2C388%2C391%2C392%2C393%2C395%2C406%2C407%2C409%2C411%2C412%2C413%2C414%2C415%2C416%2C417%2C421%2C422%2C423%2C424%2C427%2C429%2C432%2C433%2C434%2C435%2C436%2C437%2C438%2C439%2C440%2C441%2C442%2C443%2C444%2C445%2C446%2C447%2C448%2C449%2C450%2C451%2C452%2C453%2C454%2C455%2C456%2C457%2C462%2C463%2C464%2C465%2C466%2C553%2C557%2C558%2C560%2C563%2C572%2C573%2C574%2C575%2C591%2C594%2C602%2C603%2C604%2C605%2C609%2C612%2C614%2C616%2C617%2C618%2C620%2C621%2C622%2C623%2C624%2C625%2C626%2C627%2C628%2C630%2C631%2C632%2C633%2C634%2C635%2C640%2C641%2C642%2C643%2C647%2C653%2C654%2C656%2C658%2C659%2C660%2C661%2C662%2C663%2C665%2C666%2C668%2C669%2C673%2C674%2C677%2C678%2C683%2C687%2C689%2C691%2C693%2C694%2C697%2C701%2C702%2C704%2C705%2C706%2C707%2C710%2C712%2C714%2C715%2C718%2C720%2C721%2C722%2C723%2C726%2C727%2C728%2C729%2C732%2C736%2C738%2C739%2C741%2C742%2C743%2C746%2C748%2C749%2C750%2C753%2C760%2C833%2C863%2C933%2C934%2C995%2C996%2C997%2C998%2C999%2C1000%2C1001%2C1003%2C1004%2C1005%2C1006%2C1222%2C1223%2C1224%2C1225%2C1226%2C1355%2C1356%2C1357%2C1358%2C1359%2C1360%2C1361%2C1419%2C1420%2C1421%2C1422%2C1423&customoidoper=LIST)

**Comment by dustymc** [comment]
>INSERT 0 223
