### ISSUE TITLE
Bulkload errors

### ISSUE THREAD

**Issue by asemerdj** [ArctosDB/arctos#7920]
Hi Dusty,
Sorry, but can you tell me what these errors mean?

1) invalid input syntax for type integer: ""22P02

2) rec.identifier_1_type [ ] is invalid; identification_2 () invalid: taxonomy () not found; identification_order must be a number between 0 and 10; agent_2_role [ ] is invalid; agent_3_role [ ] is invalid; locality_id+locality_name could not be resolved; event_attribute_1 is not valid; attribute_2 fail: type not valid for this collection; attribute_3 fail: type not valid for this collection; attribute_4 fail: type not valid for this collection

Thank you!
Alyssa

**Comment by dustymc** [comment]
Data please

**Comment by dustymc** [comment]
@asemerdj how did you make the CSV? Many (most? all??) "empty" cells are not, they contain whitespace (different things, maybe variable number of spaces), zero-length strings, and who knows what else - all of which probably looks like nothing in most UIs, but fails ``not null`` tests by the database.

I loaded your CSV to google sheets, accepted the magic, downloaded CSV, and that seems happier - but might also be horribly mangled depending on how this happened.

I could potentially help clean this up or build tools to clean such things up or whatever, let me know if that seems useful, but hopefully this isn't that complicated.

I will go next task to attempt better errors.

**Comment by dustymc** [comment]
Yea, looks like the same thing (but with better errors!). You might try running it through google sheets, that seems to make it valid CSV but it doesn't mean there's not some more significant problem somewhere, and I have no way to judge that without knowing anything of the source data.
