### ISSUE TITLE
 Need Help with Arctos Error - report not working

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7925]
# Error Text

ERROR_ID | B54115A6-09E5-4CEE-8C7798FD798639E9
-- | --
ERROR_TYPE | expression
ERROR_MESSAGE | Can't cast String [] to a boolean
ERROR_DETAIL |  

# Where it happened
https://arctos.database.museum/Reports/reporter.cfm?action=view&report_id=85&&table_name=api%5Fjegelewicz%5F20240710010732783%5F583

# Steps to get there

1. Get search results - https://arctos.database.museum/search.cfm?guid_prefix=UWBM%3AMamm&customoidoper=LIST&oidtype=identifier&oidnum=%25
2. Select Arctos Reporter
3. Open report `UWBM_mammal_box_large_csv` - https://arctos.database.museum/Reports/reporter.cfm?action=view&report_id=85&&table_name=api%5Fjegelewicz%5F20240710010732783%5F583
4. see error

# Problem
**Community response to describe the problem that caused the error**

# Solution
**Community response with directions for how to correct the problem**

**Comment by dustymc** [comment]
<img width="1080" alt="Screenshot 2024-07-10 at 12 15 27" src="https://github.com/ArctosDB/arctos/assets/5720791/c4ea3daf-0af4-4fdc-83d9-05dff70ec1c3">

>184: &lt;/cfif&gt;<br> 185: &lt;!--- create date ---&gt;<br> <b>186: &lt;cfif began_date = ended_date&gt;</b><br> 187: &lt;cfset date=&quot;#began_date#&quot;&gt;<br> 188: &lt;cfelse&gt;<br> 


https://docs.lucee.org/guides/developing-with-lucee-server/operators.html

**Comment by Jegelewicz** [comment]
I have no idea what that means for me - this report was working and now it's not. I haven't made any changes to it since I last successfully used it.

**Comment by jebrad** [comment]
Both reports seem to be working fine for me, here are the reports when I click OPEN
[UWBM_mammal_box_large_verbdate_csv.csv](https://github.com/user-attachments/files/16168008/UWBM_mammal_box_large_verbdate_csv.csv)
[UWBM_mammal_box_large_csv.csv](https://github.com/user-attachments/files/16168009/UWBM_mammal_box_large_csv.csv)

**Comment by Jegelewicz** [comment]
Why does it work for @jebrad and not for me?

**Comment by dustymc** [comment]
>no idea what that means

That line of code isn't valid, that's not a valid operator, I don't know who did that or what they were trying to do but that's not cfml.

>Why does it work for @jebrad and not for me?

IDK, different report (that's what the file names suggest), different data, it somehow isn't encountering that part of that report.

**Comment by jebrad** [comment]
> That line of code isn't valid, that's not a valid operator, I don't know who did that or what they were trying to do but that's not cfml.

I was trying to change "date" to "verbatimdate" so it would spit out the verbatim date instead of the begin date in the CSV.  I did this by: cloned the report, changed the name, edited to change that one word (date to verbatim date) and then saved. 

I admit I was shocked when it worked, but also happy with myself.     That happy part is now gone.

**Comment by Jegelewicz** [comment]
> That line of code isn't valid, that's not a valid operator, I don't know who did that or what they were trying to do but that's not cfml.

Then please help.

What we are trying to accomplish is

If began_date and ended_date are the same, then just use began_date. If they are different then use began_date - ended_date.

**Comment by Jegelewicz** [comment]
@jebrad please delete the second report. It has the exact same problem - you are just lucky that the data you have selected aren't getting to that line. We don't need two of these reports - it's just adding to the reporter mayhem.

Thanks

**Comment by dustymc** [comment]
>What we are trying to accomplish is

I can work with that, but now that's not in https://arctos.database.museum/Reports/reporter.cfm?action=edit&report_id=85 at all?? Do you want me to add it there (as some particular name??) or has this moved or ????

**Comment by Jegelewicz** [comment]
@jebrad said he was OK with verbatim_date, and that's easy, so let's just drop this.

Thanks
