### ISSUE TITLE
cannot create operator agent - error message

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#7939]
# Error Text
<html><body>

ERROR_ID | D103395A-60C7-4D88-AF57878A20E3C720
-- | --
ERROR_TYPE | SQL
ERROR_MESSAGE | ERROR: duplicate key value violates unique constraint "iu_cf_users_operator_agent_id"   Detail: Key (operator_agent_id)=(21355378) already exists.
ERROR_DETAIL |  
ERROR_SQL | update cf_users set operator_agent_id=21355378 					where username='tmanning'

</body>
</html>

# Where it happened
trying to create an operator account for a new volunteer

# Steps to get there
- followed the instructions [here](https://handbook.arctosdb.org/how_to/How-to-Create-your-Arctos-Team-Users-and-Operators.html) to create new agent and set up operator profile
- I clicked on "invite as an operator", then add the agent name, click on "add link"
- there are 2 other agents with similar names that I've already set as "not the same as"
![image](https://github.com/user-attachments/assets/b3d49a43-b0b0-420b-bbb1-7955fcbb23ae)
- I know this operator is linked to a single human agent and that agent is not linked to any other operator, so I clicked on "There are no problems, try again!"
- then I get the error above

I have the email set to collectionsinfo@naturemuseum.org so I can get his account set up before he starts next week. This is the only thing I can think of that might be causing the error. I added his personal email to his agent account to help differentiate him from the "not the same as" agents, but I don't want him logging in before training.

# Problem
cannot invite as operator

# Solution
**Community response with directions for how to correct the problem**

**Comment by dustymc** [comment]
You have linked https://arctos.database.museum/agent/21355378 with abaltens (https://arctos.database.museum/AdminUsers.cfm?action=edit&username=abaltens), probably https://arctos.database.museum/agent/21255446.

```
99.30.57.242 - - [12/Jul/2024:15:49:25 -0500] "GET /AdminUsers.cfm?action=edit&username=abaltens HTTP/1.0" 200 3661 "https://arctos.database.museum/AdminUsers.cfm" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.
```

I un-did that, so you should be able to start the process again.

(And the aka on https://arctos.database.museum/agent/21355378 is likely to get in the way of something, you might want to remove that before you try to invite again.)

**Comment by dustymc** [comment]
Fixed?

**Comment by wellerjes** [comment]
Yes, thank you!
