### ISSUE TITLE
error feedback

### ISSUE THREAD

**Issue by catherpes** [ArctosDB/arctos#7943]
I've spent the last months off an on getting this file into a format that the bulkloader will accept. I got no errors in the staging table checks except for some nonprinting characters that I use the bulkloader to clean. so I hit load to main and get this error. 

error_message: ERROR: new row for relation "bulkloader" violates check constraint "bulkloader_event_verbatim_locality_check"
error_Sql: insert into bulkloader select * from bulkloader_stage

I thought this was addressed before based on prior incidents. Once we get no errors for the file in the staging table, it should be good enough to get to the bulkloader and then to load. This stage of editing is preferable because it is easiest to edit records in Excel. Errors at this point adds maddening levels of frustration on top of a process that already is really complex and frustrating. 
[april 2024 bulkload 12.csv](https://github.com/user-attachments/files/16240180/april.2024.bulkload.12.csv)

**Comment by dustymc** [comment]
Assuming those are your data in the loader, the checker has run and the rows with nonprinting characters are marked as such.

<img width="932" alt="Screenshot 2024-07-15 at 14 23 52" src="https://github.com/user-attachments/assets/35e64b49-217a-467a-ad9a-f25718f745e7">

This:


<img width="146" alt="Screenshot 2024-07-15 at 14 22 43" src="https://github.com/user-attachments/assets/1696269b-d550-44d8-bee1-9f3e180d9757">

will probably fix them (unless the error involves eg unicode conversion, then it might make a mess)

>Once we get no errors for the file in the staging table, it should be good enough to get to the bulkloader 

Correct - but this file has lots of errors. You can also check those inline

<img width="151" alt="Screenshot 2024-07-15 at 14 22 21" src="https://github.com/user-attachments/assets/7499f1d7-3f04-490b-9794-f92df1384a06">

<img width="654" alt="Screenshot 2024-07-15 at 14 22 27" src="https://github.com/user-attachments/assets/dbbe22e3-6a6a-435f-b1d5-9c25794be5bd">

>easiest to edit records in Excel.

That's exactly why it works this way, there were complaints about the former method of allowing these into the bulkloader, then they error at runtime.

>really complex and frustrating.

I'm sorry to hear that and (obviously, I hope) very open to anything that might make it better.

**Comment by catherpes** [comment]
Okay my bad I thought there was a step once in the bulkloader to strip nonprinting characters. I used the function to strip the nonprinting characters and then retry. I get another error, apparently a duplicate key but I don't see it. 

<html><body>

ERROR: duplicate key value violates unique constraint "bulkloader_pkey1"
--


</body>
</html>

**Comment by dustymc** [comment]
> duplicate key value 

That's a bug/bad assumption on my part, it'll be fixed in next release.

I copied your data to the main bulkloader. Let me know if I need to undo that.

**Comment by catherpes** [comment]
thank you.

**Comment by catherpes** [comment]
Can you please look at my records in the bulkloader and note the errors that are not being caught in the prior steps so that we don't have to fix them in the bulkloader stage in the future?
