### ISSUE TITLE
Agent Split Request - Howard Smith

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#7944]
**Agent that represents more than one person or organization**
[Navigate to the agent page, copy the url and paste it below:](https://arctos.database.museum/edit_agent.cfm?agent_id=1017968)

The agent Howard Smith in the record above is a long-time BLM archaeologist based in Fairbanks, Alaska for over 40 years. I wanted to check with @droberts49 and @wellerjes to see if they used the right Howard Smith for their CHAS:Mamm accession E1980D. There is a Chicago mailing address that was added to the record at some point and as far as we know, our Howard has never lived in Chicago. Looking at his [Agent Activity page](https://arctos.database.museum/agent/1017968?deets=true) shows a very Alaska-focused history.

**Affected Collections**
CHAS:Mamm is, I believe, the only outlier in Howard's list of activities. UAM:Arc, UAM:ES, and soon UAM:EH after an upcoming donation, all have the Alaska-Howard fully embedded in our records. Please let me know if our Howard donated something for your collection because that would be cool and we can just close this issue as a non-issue. Otherwise, you'll need to create a new Howard Smith for your guy (I can contact our Howard to get a middle name/initial to help disambiguate).

**Agent change tool**
For any collection that needs to change to the agent created as part of this split, follow the instructions at [How to Batch Update Agents](https://handbook.arctosdb.org/how_to/How-to-Batch-Update-Agents.html)

Please add this issue to the Agents Project.

@ArctosDB/agents-committee

**Comment by camwebb** [comment]
Alaska Howard's middle initial is L.

**Comment by AJLinn** [comment]
1. Updated Alaska Howard Smith preferred name to include middle initial.
2. Created [new Howard Smith](https://arctos.database.museum/edit_agent.cfm?agent_id=21355891)
3. TO DO: CHAS:Mamm needs to update accession link to new Howard Smith agent. https://arctos.database.museum/edit_agent.cfm?agent_id=21355891
4. @droberts49 or @wellerjes please update your accession
<img width="451" alt="Screenshot 2024-08-21 at 6 49 24 AM" src="https://github.com/user-attachments/assets/dd3ea3bc-ccb6-4170-b91c-04d953c3ecb2">

**Comment by wellerjes** [comment]
Thanks for letting us know; accession record updated.
