### ISSUE TITLE
Records not showing up after bulkload

### ISSUE THREAD

**Issue by adhornsby** [ArctosDB/arctos#7945]
FKelly880 and I sent a record bulkload through yesterday afternoon, no errors and everything worked as usual.  However, the records aren't showing up yet.  I can see that the catalog# series has ticked up, and the accession shows the correct number of records attached.  Do we just need to be patient, or are they stuck somewhere and need to be dislodged?

https://arctos.database.museum/search.cfm?accn_trans_id=21141339
Should be catalog#s MMNH:Mamm:19357 and MMNH:Mamm:19846-20040
I don't know the keys since they moved successfully out of the Browse & Edit table.

**Comment by Jegelewicz** [comment]
The process can take a day depending upon what else is going on and it looks like they are working their way through.

**Comment by adhornsby** [comment]
OK, thanks @Jegelewicz !  Just never had it take this long so I was unsure.

**Comment by dustymc** [comment]
https://arctos.database.museum/info/flat_status.cfm
