### ISSUE TITLE
disappearing bulkloaded records 

### ISSUE THREAD

**Issue by catherpes** [ArctosDB/arctos#7946]
Is there a delay between when records are bulkloaded and when they are viewable in Arctos? 
I searched on the list of numbers I marked for bulkload yesterday and get an empty grid of cells. typing in a URL of one of the records generates an error, GUID not found. 

https://arctos.database.museum/guid/MSB:Bird:51893

This record is not one of the ones that generated an error and remains in the bulkloader. 

Adrienne is having the same issue in Mammals. records no longer in the bulkloader but not available in the database either.

**Comment by Jegelewicz** [comment]
https://github.com/ArctosDB/arctos/issues/7945

**Comment by AdrienneRaniszewski** [comment]
I set my records to load on Monday morning. They are still not fully loaded. Needed to work with them today.

I looked at the flat_status. looks like a lot of stuff, but beyond that it's not super informative. Don't fully understand what each category means or how long it could potentially take to work through everything. And where is my stuff is in the queue? Basically it would be helpful to know about how much longer I'll have to wait. 

Thanks!

**Comment by dustymc** [comment]
>not super informative.

Please see https://github.com/ArctosDB/arctos/issues/6705, linked from https://arctos.database.museum/info/flat_status.cfm. I'd be very happy to make it more informative, but I'm all out of ideas.

**Comment by mkoo** [comment]
I like some of those suggestions. Is it too much to ask if those are on a collection_cde basis so we can track the specific records of interest? (eg MVZ:Bird 200 pending; MSB:Herp 200 pending, etc)? 
Also after moving things from the bulkloading table, do we have a link to the status page?

If this is feasible I will edit this issue to reflect a specific request

**Comment by dustymc** [comment]
@mkoo I've got an answer cooking in the other thread, yes some actionable suggestions there, please hold off the re-opening for a bit.

**Comment by dustymc** [comment]
See links from https://github.com/ArctosDB/arctos/issues/6705#issuecomment-2234062482 (I'm still trying to keep everything together).

Tentatively closing this to push focus towards the other thread (which might need reopened, but I think the action items are all in separate issues now??)
