### ISSUE TITLE
Unable to search wildcards in taxonomy

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7947]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

Trying to use the % wildcard when searching taxonomy fails with this error

<html><body>

ERROR_ID | AFE2E233-086F-4B9C-B96EFB05C3D2CA02
-- | --
ERROR_TYPE | java.lang.IllegalArgumentException
ERROR_MESSAGE | URLDecoder: Illegal hex characters in escape (%) pattern - Error at index 0 in: " t"
ERROR_DETAIL |  

</body>
</html>

I swear I used to be able to do this?

**To Reproduce**
1. Go to https://arctos.database.museum/taxonomy.cfm
2. Enter `A% tigrinum` in Taxon Name
3. See error

**Expected behavior**

I expect to get a list of things that start with A and somewhere later include tigrinum

**Screenshots**

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 128.0 (64-bit)

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by dustymc** [comment]
Dup of https://github.com/ArctosDB/arctos/issues/7865

**Comment by mkoo** [comment]
this is a dup issue so closing
