### ISSUE TITLE
recently loaded catalog records not visible

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#7948]
I loaded 59 records yesterday afternoon via the bulkloader. They are no longer visible in the bulkloader, but the catalog records are not accessible.

**To Reproduce**
1. Searched for records "enteredby" jweller on "2024-07-16"
2. 
![image](https://github.com/user-attachments/assets/0aebaefe-dc8f-401d-8b1f-91b168184d83)

I had this problem last week when I bulkloaded 1300 records, but it resolved within a few hours.

I'm using Firefox, but getting the same issue with Chrome. Multiple users and computers experiencing this issue.

**Comment by dustymc** [comment]
https://arctos.database.museum/info/flat_status.cfm

**Comment by mkoo** [comment]
HI @wellerjes generally flat takes awhile to refresh especially with lots of new changes to process.
This will give you a sense of the progress:
https://arctos.database.museum/info/flat_status.cfm

Now 3 hours after you wrote it seems to have almost none pending so should be uptodate now:

![Firefox_Screenshot_2024-07-17T18-17-02 359Z](https://github.com/user-attachments/assets/69990eec-1e0a-4c4e-ac31-ef047b965e8c)

If you cannot see it now, please file a new issue! thanks
