### ISSUE TITLE
part picker functionality change

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#795]
From DMNS:Inv:

When you type in a value for the Part Name it does a check to see if the value is valid.  This pops up a new window that for us usually only has a single value (e.g. "Shell" if we type Shell).  We then have to click on Shell to have it use that value.  It would be nice if this interface would simply accept the value if it is valid and there is only one valid option returned instead of making us manually choose it.  This is what happens elsewhere, like the Identified By or Taxon fields.  If it would just accept the value (if only one valid answer matches what you typed), fill in the field and then move you to the next field, this would be more efficient and let us make edits faster.  Every time I have to click "Shell" it feels like a disruption in my flow. 

Is this acceptable behavior to other collections?

**Comment by KyndallH** [comment]
I agree. I would like part name to behave more like identified by or taxon fields.

**Comment by campmlc** [comment]
I agree. Minimizing unnecessary clicks is always a good idea, especially
when half the time the browser hides the pop up and students don't know
where to find it.

**Comment by dustymc** [comment]
fixed for post-v7.2.4.2  release
