### ISSUE TITLE
Agent search not finding Verbatim Agents intermittently

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#7963]
Agent Search is not finding the verbatim agent "Nancy Walunga" who is [listed in these records](https://arctos.database.museum/search.cfm?guid_prefix=UAM%3AEH&collector=Nancy%20Walunga).

Can someone see what box I don't have checked in order to find her? I'm trying to create a real agent record for her and was looking to see if she already had one under a different name. I tried only her last name with same results.

<img width="1571" alt="Screenshot 2024-07-23 at 11 18 24 AM" src="https://github.com/user-attachments/assets/bf29ffa8-b8b9-4496-9c57-5883c72d30d5">

This happened to me the other day when I was searching for a pair of collectors who I'd previously found in the db but then nothing came up when I searched (I have include verbatim agent set as yes). I created their agent records and then when I looked today, I saw both of them were listed as verbatim agents in UAM:Mamm and UAM:Bird.

**Comment by dustymc** [comment]
https://arctos.database.museum/agent.cfm?srch=Nancy%20Walunga&include_verbatim=true&include_bad_dup=false should look like....
<img width="1110" alt="Screenshot 2024-07-23 at 12 28 20" src="https://github.com/user-attachments/assets/2af07acb-ce41-4dfe-b3f0-ce4ec80676d2">

<img width="187" alt="Screenshot 2024-07-23 at 12 29 08" src="https://github.com/user-attachments/assets/e56e16d6-1e82-4447-95a2-9c46973280cf">

then copy-paste the URL would help discover what's going on.

**Comment by AJLinn** [comment]
Now they're both showing up despite not making any changes to my search other than creating her agent record.
https://arctos.database.museum/agent.cfm?srch=Nancy%20Walunga&include_verbatim=true&include_bad_dup=false

Guess I'll close for now but i'm going to make a note to myself to re-find this issue if it happens again!

**Comment by AJLinn** [comment]
It happened again!
https://arctos.database.museum/agent.cfm?srch=Rhoda%20Ahgook&include_verbatim=true&include_bad_dup=false

**Comment by dustymc** [comment]
AHA!

I think searches that return ONLY verbatim agents aren't getting there.

Going next task to confirm (and fix if practical).

Thanks!
