### ISSUE TITLE
accidental locality change?

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#7970]
I'm seeing my name next to other collections for a locality change. I'm not sure what I did to cause this; is there a way to revert any changes I made other collections' localities?

Here's the [event change notification from July 20, 2024](https://arctos.database.museum/info/localityArchive.cfm?locality_id=11079362,12298012,12298011,12298014,12298024,12298002,12297957,12297958,12297617,12297959,11377681,12298008,11032748,12298010,11055975).
And from [July 19, 2024](https://arctos.database.museum/info/localityArchive.cfm?locality_id=11079362,12298012,12298011,12298014,12298024,12298002,12297957,12297958,12297617,12297959,11377681,12298008,11032748,12298010,11055975).

**Comment by dustymc** [comment]
@wellerjes can you be more specific? I don't understand the problem.

**Comment by wellerjes** [comment]
![image](https://github.com/user-attachments/assets/a0f37b81-b5e9-43b2-a333-81c0cc5aae1a)
It looks like I changed locality information for a different collection.

When I click on "click", there's no change to the information?
![image](https://github.com/user-attachments/assets/69ceab91-92c3-442f-988f-07f4ad74850f)

**Comment by mkoo** [comment]
HI Jessica @wellerjes, are you saying you did not make these changes? It seems from the logs that you are making a lot of locality updates and for some they may be shared localities. Reminder: if you just want to create a new locality NOT shared by others, then Clone the locality, update the new locality, then associate wtih your collection records via the specimen event. I'm going to update our handbook with more current screenshots and will send you a note. Let me know if it's something else however

**Comment by wellerjes** [comment]
I've been making fork-edits instead of cloning, that may be the issue. It's been a while since I've done cloning (not since the new UI changes when into effect?), so I'll let you know if I have any questions. Thanks!

**Comment by mkoo** [comment]
Please file a new issue if you have updated questions! thx
