### ISSUE TITLE
Feature Request - "Back" button with error in creating loan-like transaction

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#7972]
**Is your feature request related to a problem? Please describe.**
I want to kill Arctos every time I create a new transaction (e.g., "loan-like transaction") and after spending a good ~10 minutes filling out each field with great detail, I hit the "Create Transaction" button, only to be greeted with the purple error page indicating I've done something wrong (in the last case I accidentally used an existing transaction number), and no "Go Back" button to fix the problem and re-create the transaction.

**Describe what you're trying to accomplish** 
I would like to not be cruelly punished for making a mistake after creating a extremely complete transaction the first time around.

**Describe the solution you'd like**
Create a "go back and fix the error" button.

**Describe alternatives you've considered**
Drop-kicking my computer
Screaming in frustration and then spending another 10 minutes re-creating the record.
Creating a skeleton record and then going back and filling in the details after it's saved.

**Additional context**
<img width="1680" alt="Screenshot 2024-07-24 at 8 37 45 AM" src="https://github.com/user-attachments/assets/98e9d8df-ff1c-4fa5-80df-75d6e79e56ad">
This is the screenshot where I re-created the error... but not the real one.

**Priority**
Normal, but it would be REALLY nice and would improve the daily mental health of users who get so frustrated they want to punch their computer screens!

**Comment by AJLinn** [comment]
AND this also happens when adding parts to a loan. OMG I just spent 15 minutes clicking every media part box to add to the loan and then used the add checked boxes button at the bottom instead of scrolling up and I forgot to click the change disposition button and got this error:
 	36FA4DE2-2DBC-4A38-897E7D926B32940F
But no back button to fix what I was just doing...
🤬

**Comment by campmlc** [comment]
Totally support this for all transactions.

**Comment by dustymc** [comment]
> just used the back arrow in my browser

That should be the most robust solution to this and similar problems wherever they might be found and whatever might cause them.  If that does not work, please let me know enough detail to re-create.

Perhaps something in the 'may we suggest' area of the error message would be useful?

**Comment by ewommack** [comment]
> Perhaps something in the 'may we suggest' area of the error message would be useful?

That sounds like a good solution. It might be a little startling though, I feel so many instructions so "do not use your back button". In this case "yes, use your back button if you would like to go back to your form before you submitted it"

**Comment by mkoo** [comment]
Open for better phrasing but here goes the suggested action item from comments:

- [ ] Add to "May we suggest:"

3. On transaction and other forms, please use your browser's **Back** button to correct and resend your entries
