### ISSUE TITLE
Feature Request - Add Browse Arctos Tables and Curatorial Search Request links to Write SQL Page

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#7976]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

**Describe what you're trying to accomplish** 
Make it obvious what tables to call and that there is a curatorial search request feature

**Describe the solution you'd like**
_How might we accomplish your goals?_
Add a quick shortcut link to Browse Arctos Tables to Write SQL page and a reminder for using the Curatorial Search Request template for complex SQL queries. 

**Describe alternatives you've considered**
Magically knowing to look at the Browse Arctos Tables link for table/field names

**Additional context**
_Add any other context or screenshots about the feature request here._

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._

**Comment by mkoo** [comment]
This can be adjacent to the Cheatsheet button link on the write sql page. (also added to the Cheatsheet too)
