### ISSUE TITLE
EML Generator patch pending

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7977]
> Hey Teresa,
> 
> The bookmark I use to get to the EML Generator now fails.
> 
> https://arctos.database.museum/info/ipt.cfm?guid_prefix=UWYMV%3AEgg
> 
> Doesn't matter if I'm logged in or not. Is this service gone now?
> 

Dave Bloom

I was trying to get [this](https://github.com/ArctosDB/data-migration/issues/1242) done, but because manage collection was changed without notification, the tool we use to make initial publication to the IPT easy no longer functions. If the tool will not be adjusted for the new format in manage collection, the workflow for publishing to aggregators needs to be changed and anyone publishing for the first time will need to manually complete the collection metadata at the IPT.

**Comment by dbloom** [comment]
Oh, good. Just what I needed. More busy work.   O_O

I'll pause the 4 CRCM collections pending and future publications until the EML generator returns, or until I know it will not. If the latter, I will resume the old-timey training of collection staff to enter their metadata correctly.

**Comment by mkoo** [comment]
Update: quick patch prioritized for next week but will be part of a larger conversation on the overall IPT strategy

**Comment by dbloom** [comment]
@dustymc Is there a new URL? I'm continue to try https://arctos.database.museum/info/ipt.cfm?guid_prefix=UWYMV%3AEgg without success.

I've tried multiple browsers, tried logged in and not logged in, tried hard resets, cleared my cache, but no access.

**Comment by mkoo** [comment]
-secure means is to allow dbloom access with his Arctos log on. In process to set up with him

**Comment by ewommack** [comment]
Do you need me to give dbloom access to the UWYMV collections?

**Comment by mkoo** [comment]
> Do you need me to give dbloom access to the UWYMV collections?

No that wont be necessary for EML link

**Comment by mkoo** [comment]
Closing... if dbloom has issues with log in (he hasnt tried yet) then we can open a new one
