### ISSUE TITLE
bulkloader data there since yesterday

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7979]
@rwilhoyt data left in bulkloader. 

[bulkloader_stage(41).csv](https://github.com/user-attachments/files/16396368/bulkloader_stage.41.csv)

**Comment by rwilhoyt** [comment]
Apologies, I must have missed the "yep, delete away" link after loading! My records are uploaded.

**Comment by Jegelewicz** [comment]
No worries - just didn't want you to lose anything!
