### ISSUE TITLE
Need Help with Arctos Error - Create Record

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#7985]
# Where it happened
I had a new intern trying to do data entry for the first time. Her first record, she gets an incomprehensible error message. I dug through her entry, trying to find the error. Checked for extra spaces. All good. Tried re-entering some of the data. Nothing worked, still an error. I took screenshots of what she entered, went into data entry myself, entered the data exactly as she did, no error. I don't want her to run into this again, but I don't know what she did wrong.

Screenshots of her data entry screen:
![Capture](https://github.com/user-attachments/assets/b40d9284-cc3b-416e-88ba-d5d802ddeb28)
![Capture2](https://github.com/user-attachments/assets/7e5718be-54ae-4aa7-b461-7072c76bd97d)

# Error Text
2024-7-31T16:55:48: FAIL: exception catch, check console: [object Object]: {"message":"exception catch, check console","status":"fail","dump":{"Extended_Info":"","Message":"ERROR: new row for relation \"bulkloader\" violates check constraint \"bulkloader_record_remark_check\"","queryError":"INSERT INTO bulkloader (\n\t\t\t\t\t\n\t\t\t\t\t\tpart_1_count,\n\t\t\t\t\t\n\t\t\t\t\t\tidentification_1,\n\t\t\t\t\t\n\t\t\t\t\t\trecord_event_determiner,\n\t\t\t\t\t\n\t\t\t\t\t\trecord_remark,\n\t\t\t\t\t\n\t\t\t\t\t\tidentification_1_order,\n\t\t\t\t\t\n\t\t\t\t\t\tevent_began_date,\n\t\t\t\t\t\n\t\t\t\t\t\tevent_verbatim_locality,\n\t\t\t\t\t\n\t\t\t\t\t\tidentifier_1_type,\n\t\t\t\t\t\n\t\t\t\t\t\tpart_1_condition,\n\t\t\t\t\t\n\t\t\t\t\t\tlocality_name,\n\t\t\t\t\t\n\t\t\t\t\t\tpart_1_name,\n\t\t\t\t\t\n\t\t\t\t\t\tpart_1_attribute_value_1,\n\t\t\t\t\t\n\t\t\t\t\t\tagent_1_role,\n\t\t\t\t\t\n\t\t\t\t\t\tattribute_1_date,\n\t\t\t\t\t\n\t\t\t\t\t\tidentifier_1_value,\n\t\t\t\t\t\n\t\t\t\t\t\tattribute_1_value,\n\t\t\t\t\t\n\t\t\t\t\t\tguid_prefix,\n\t\t\t\t\t\n\t\t\t\t\t\trecord_event_determined_date,\n\t\t\t\t\t\n\t\t\t\t\t\tagent_1_name,\n\t\t\t\t\t\n\t\t\t\t\t\taccn,\n\t\t\t\t\t\n\t\t\t\t\t\tpart_1_attribute_type_1,\n\t\t\t\t\t\n\t\t\t\t\t\tevent_ended_date,\n\t\t\t\t\t\n\t\t\t\t\t\tidentification_1_agent_1,\n\t\t\t\t\t\n\t\t\t\t\t\tidentifier_1_issued_by,\n\t\t\t\t\t\n\t\t\t\t\t\trecord_event_verificationstatus,\n\t\t\t\t\t\n\t\t\t\t\t\tattribute_1_determiner,\n\t\t\t\t\t\n\t\t\t\t\t\tidentification_1_attribute_type_1,\n\t\t\t\t\t\n\t\t\t\t\t\tevent_verbatim_date,\n\t\t\t\t\t\n\t\t\t\t\t\tattribute_1_type,\n\t\t\t\t\t\n\t\t\t\t\t\trecord_event_type,\n\t\t\t\t\t\n\t\t\t\t\t\tcat_num,\n\t\t\t\t\t\n\t\t\t\t\t\tpart_1_disposition,\n\t\t\t\t\t\n\t\t\t\t\tkey,\n\t\t\t\t\tenteredby\n\t\t\t\t) values (\n\t\t\t\t\t\n\t\t\t\t\t\t'20',\n\t\t\t\t\t\n\t\t\t\t\t\t'Proboscidea',\n\t\t\t\t\t\n\t\t\t\t\t\t'Kate E. Zeigler',\n\t\t\t\t\t\n\t\t\t\t\t\t'\r\n',\n\t\t\t\t\t\n\t\t\t\t\t\t'1',\n\t\t\t\t\t\n\t\t\t\t\t\t'2022-10-27',\n\t\t\t\t\t\n\t\t\t\t\t\t'LUS-041, L-13464, La Union South.',\n\t\t\t\t\t\n\t\t\t\t\t\t'institutional catalog number',\n\t\t\t\t\t\n\t\t\t\t\t\t'Fragments',\n\t\t\t\t\t\n\t\t\t\t\t\t'NMMNH:Paleo:13464',\n\t\t\t\t\t\n\t\t\t\t\t\t'bone',\n\t\t\t\t\t\n\t\t\t\t\t\t'fossil',\n\t\t\t\t\t\n\t\t\t\t\t\t'collector',\n\t\t\t\t\t\n\t\t\t\t\t\t'2024-07-29',\n\t\t\t\t\t\n\t\t\t\t\t\t'NMMNH P-96692',\n\t\t\t\t\t\n\t\t\t\t\t\t'cataloged',\n\t\t\t\t\t\n\t\t\t\t\t\t'NMMNH:Paleo',\n\t\t\t\t\t\n\t\t\t\t\t\t'2024-05-13',\n\t\t\t\t\t\n\t\t\t\t\t\t'Kate E. Zeigler',\n\t\t\t\t\t\n\t\t\t\t\t\t'[NMMNH:Paleo]2023.033',\n\t\t\t\t\t\n\t\t\t\t\t\t'preservation',\n\t\t\t\t\t\n\t\t\t\t\t\t'2022-10-27',\n\t\t\t\t\t\n\t\t\t\t\t\t'Gary S. Morgan',\n\t\t\t\t\t\n\t\t\t\t\t\t'New Mexico Museum of Natural History and Science',\n\t\t\t\t\t\n\t\t\t\t\t\t'accepted',\n\t\t\t\t\t\n\t\t\t\t\t\t'Thais Ramírez Argueta',\n\t\t\t\t\t\n\t\t\t\t\t\t'verbatim identification',\n\t\t\t\t\t\n\t\t\t\t\t\t'10/27/2022',\n\t\t\t\t\t\n\t\t\t\t\t\t'processing history',\n\t\t\t\t\t\n\t\t\t\t\t\t'collection',\n\t\t\t\t\t\n\t\t\t\t\t\t'96692',\n\t\t\t\t\t\n\t\t\t\t\t\t'in collection',\n\t\t\t\t\t\n\t\t\t\t\t'key_4728853',\n\t\t\t\t\t'THAISDRAMIREZ'\n\t\t\t\t)","Sql":"INSERT INTO bulkloader (\n\t\t\t\t\t\n\t\t\t\t\t\tpart_1_count,\n\t\t\t\t\t\n\t\t\t\t\t\tidentification_1,\n\t\t\t\t\t\n\t\t\t\t\t\trecord_event_determiner,\n\t\t\t\t\t\n\t\t\t\t\t\trecord_remark,\n\t\t\t\t\t\n\t\t\t\t\t\tidentification_1_order,\n\t\t\t\t\t\n\t\t\t\t\t\tevent_began_date,\n\t\t\t\t\t\n\t\t\t\t\t\tevent_verbatim_locality,\n\t\t\t\t\t\n\t\t\t\t\t\tidentifier_1_type,\n\t\t\t\t\t\n\t\t\t\t\t\tpart_1_condition,\n\t\t\t\t\t\n\t\t\t\t\t\tlocality_name,\n\t\t\t\t\t\n\t\t\t\t\t\tpart_1_name,\n\t\t\t\t\t\n\t\t\t\t\t\tpart_1_attribute_value_1,\n\t\t\t\t\t\n\t\t\t\t\t\tagent_1_role,\n\t\t\t\t\t\n\t\t\t\t\t\tattribute_1_date,\n\t\t\t\t\t\n\t\t\t\t\t\tidentifier_1_value,\n\t\t\t\t\t\n\t\t\t\t\t\tattribute_1_value,\n\t\t\t\t\t\n\t\t\t\t\t\tguid_prefix,\n\t\t\t\t\t\n\t\t\t\t\t\trecord_event_determined_date,\n\t\t\t\t\t\n\t\t\t\t\t\tagent_1_name,\n\t\t\t\t\t\n\t\t\t\t\t\taccn,\n\t\t\t\t\t\n\t\t\t\t\t\tpart_1_attribute_type_1,\n\t\t\t\t\t\n\t\t\t\t\t\tevent_ended_date,\n\t\t\t\t\t\n\t\t\t\t\t\tidentification_1_agent_1,\n\t\t\t\t\t\n\t\t\t\t\t\tidentifier_1_issued_by,\n\t\t\t\t\t\n\t\t\t\t\t\trecord_event_verificationstatus,\n\t\t\t\t\t\n\t\t\t\t\t\tattribute_1_determiner,\n\t\t\t\t\t\n\t\t\t\t\t\tidentification_1_attribute_type_1,\n\t\t\t\t\t\n\t\t\t\t\t\tevent_verbatim_date,\n\t\t\t\t\t\n\t\t\t\t\t\tattribute_1_type,\n\t\t\t\t\t\n\t\t\t\t\t\trecord_event_type,\n\t\t\t\t\t\n\t\t\t\t\t\tcat_num,\n\t\t\t\t\t\n\t\t\t\t\t\tpart_1_disposition,\n\t\t\t\t\t\n\t\t\t\t\tkey,\n\t\t\t\t\tenteredby\n\t\t\t\t) values (\n\t\t\t\t\t\n\t\t\t\t\t\t'20',\n\t\t\t\t\t\n\t\t\t\t\t\t'Proboscidea',\n\t\t\t\t\t\n\t\t\t\t\t\t'Kate E. Zeigler',\n\t\t\t\t\t\n\t\t\t\t\t\t'\r\n',\n\t\t\t\t\t\n\t\t\t\t\t\t'1',\n\t\t\t\t\t\n\t\t\t\t\t\t'2022-10-27',\n\t\t\t\t\t\n\t\t\t\t\t\t'LUS-041, L-13464, La Union South.',\n\t\t\t\t\t\n\t\t\t\t\t\t'institutional catalog number',\n\t\t\t\t\t\n\t\t\t\t\t\t'Fragments',\n\t\t\t\t\t\n\t\t\t\t\t\t'NMMNH:Paleo:13464',\n\t\t\t\t\t\n\t\t\t\t\t\t'bone',\n\t\t\t\t\t\n\t\t\t\t\t\t'fossil',\n\t\t\t\t\t\n\t\t\t\t\t\t'collector',\n\t\t\t\t\t\n\t\t\t\t\t\t'2024-07-29',\n\t\t\t\t\t\n\t\t\t\t\t\t'NMMNH P-96692',\n\t\t\t\t\t\n\t\t\t\t\t\t'cataloged',\n\t\t\t\t\t\n\t\t\t\t\t\t'NMMNH:Paleo',\n\t\t\t\t\t\n\t\t\t\t\t\t'2024-05-13',\n\t\t\t\t\t\n\t\t\t\t\t\t'Kate E. Zeigler',\n\t\t\t\t\t\n\t\t\t\t\t\t'[NMMNH:Paleo]2023.033',\n\t\t\t\t\t\n\t\t\t\t\t\t'preservation',\n\t\t\t\t\t\n\t\t\t\t\t\t'2022-10-27',\n\t\t\t\t\t\n\t\t\t\t\t\t'Gary S. Morgan',\n\t\t\t\t\t\n\t\t\t\t\t\t'New Mexico Museum of Natural History and Science',\n\t\t\t\t\t\n\t\t\t\t\t\t'accepted',\n\t\t\t\t\t\n\t\t\t\t\t\t'Thais Ramírez Argueta',\n\t\t\t\t\t\n\t\t\t\t\t\t'verbatim identification',\n\t\t\t\t\t\n\t\t\t\t\t\t'10/27/2022',\n\t\t\t\t\t\n\t\t\t\t\t\t'processing history',\n\t\t\t\t\t\n\t\t\t\t\t\t'collection',\n\t\t\t\t\t\n\t\t\t\t\t\t'96692',\n\t\t\t\t\t\n\t\t\t\t\t\t'in collection',\n\t\t\t\t\t\n\t\t\t\t\t'key_4728853',\n\t\t\t\t\t'THAISDRAMIREZ'\n\t\t\t\t)","Detail":"","SQLState":"23514","additional":{"SQL":"INSERT INTO bulkloader (\n\t\t\t\t\t\n\t\t\t\t\t\tpart_1_count,\n\t\t\t\t\t\n\t\t\t\t\t\tidentification_1,\n\t\t\t\t\t\n\t\t\t\t\t\trecord_event_determiner,\n\t\t\t\t\t\n\t\t\t\t\t\trecord_remark,\n\t\t\t\t\t\n\t\t\t\t\t\tidentification_1_order,\n\t\t\t\t\t\n\t\t\t\t\t\tevent_began_date,\n\t\t\t\t\t\n\t\t\t\t\t\tevent_verbatim_locality,\n\t\t\t\t\t\n\t\t\t\t\t\tidentifier_1_type,\n\t\t\t\t\t\n\t\t\t\t\t\tpart_1_condition,\n\t\t\t\t\t\n\t\t\t\t\t\tlocality_name,\n\t\t\t\t\t\n\t\t\t\t\t\tpart_1_name,\n\t\t\t\t\t\n\t\t\t\t\t\tpart_1_attribute_value_1,\n\t\t\t\t\t\n\t\t\t\t\t\tagent_1_role,\n\t\t\t\t\t\n\t\t\t\t\t\tattribute_1_date,\n\t\t\t\t\t\n\t\t\t\t\t\tidentifier_1_value,\n\t\t\t\t\t\n\t\t\t\t\t\tattribute_1_value,\n\t\t\t\t\t\n\t\t\t\t\t\tguid_prefix,\n\t\t\t\t\t\n\t\t\t\t\t\trecord_event_determined_date,\n\t\t\t\t\t\n\t\t\t\t\t\tagent_1_name,\n\t\t\t\t\t\n\t\t\t\t\t\taccn,\n\t\t\t\t\t\n\t\t\t\t\t\tpart_1_attribute_type_1,\n\t\t\t\t\t\n\t\t\t\t\t\tevent_ended_date,\n\t\t\t\t\t\n\t\t\t\t\t\tidentification_1_agent_1,\n\t\t\t\t\t\n\t\t\t\t\t\tidentifier_1_issued_by,\n\t\t\t\t\t\n\t\t\t\t\t\trecord_event_verificationstatus,\n\t\t\t\t\t\n\t\t\t\t\t\tattribute_1_determiner,\n\t\t\t\t\t\n\t\t\t\t\t\tidentification_1_attribute_type_1,\n\t\t\t\t\t\n\t\t\t\t\t\tevent_verbatim_date,\n\t\t\t\t\t\n\t\t\t\t\t\tattribute_1_type,\n\t\t\t\t\t\n\t\t\t\t\t\trecord_event_type,\n\t\t\t\t\t\n\t\t\t\t\t\tcat_num,\n\t\t\t\t\t\n\t\t\t\t\t\tpart_1_disposition,\n\t\t\t\t\t\n\t\t\t\t\tkey,\n\t\t\t\t\tenteredby\n\t\t\t\t) values (\n\t\t\t\t\t\n\t\t\t\t\t\t'20',\n\t\t\t\t\t\n\t\t\t\t\t\t'Proboscidea',\n\t\t\t\t\t\n\t\t\t\t\t\t'Kate E. Zeigler',\n\t\t\t\t\t\n\t\t\t\t\t\t'\r\n',\n\t\t\t\t\t\n\t\t\t\t\t\t'1',\n\t\t\t\t\t\n\t\t\t\t\t\t'2022-10-27',\n\t\t\t\t\t\n\t\t\t\t\t\t'LUS-041, L-13464, La Union South.',\n\t\t\t\t\t\n\t\t\t\t\t\t'institutional catalog number',\n\t\t\t\t\t\n\t\t\t\t\t\t'Fragments',\n\t\t\t\t\t\n\t\t\t\t\t\t'NMMNH:Paleo:13464',\n\t\t\t\t\t\n\t\t\t\t\t\t'bone',\n\t\t\t\t\t\n\t\t\t\t\t\t'fossil',\n\t\t\t\t\t\n\t\t\t\t\t\t'collector',\n\t\t\t\t\t\n\t\t\t\t\t\t'2024-07-29',\n\t\t\t\t\t\n\t\t\t\t\t\t'NMMNH P-96692',\n\t\t\t\t\t\n\t\t\t\t\t\t'cataloged',\n\t\t\t\t\t\n\t\t\t\t\t\t'NMMNH:Paleo',\n\t\t\t\t\t\n\t\t\t\t\t\t'2024-05-13',\n\t\t\t\t\t\n\t\t\t\t\t\t'Kate E. Zeigler',\n\t\t\t\t\t\n\t\t\t\t\t\t'[NMMNH:Paleo]2023.033',\n\t\t\t\t\t\n\t\t\t\t\t\t'preservation',\n\t\t\t\t\t\n\t\t\t\t\t\t'2022-10-27',\n\t\t\t\t\t\n\t\t\t\t\t\t'Gary S. Morgan',\n\t\t\t\t\t\n\t\t\t\t\t\t'New Mexico Museum of Natural History and Science',\n\t\t\t\t\t\n\t\t\t\t\t\t'accepted',\n\t\t\t\t\t\n\t\t\t\t\t\t'Thais Ramírez Argueta',\n\t\t\t\t\t\n\t\t\t\t\t\t'verbatim identification',\n\t\t\t\t\t\n\t\t\t\t\t\t'10/27/2022',\n\t\t\t\t\t\n\t\t\t\t\t\t'processing history',\n\t\t\t\t\t\n\t\t\t\t\t\t'collection',\n\t\t\t\t\t\n\t\t\t\t\t\t'96692',\n\t\t\t\t\t\n\t\t\t\t\t\t'in collection',\n\t\t\t\t\t\n\t\t\t\t\t'key_4728853',\n\t\t\t\t\t'THAISDRAMIREZ'\n\t\t\t\t)","DatabaseName":"PostgreSQL","DatabaseVersion":"15.4","DriverName":"PostgreSQL JDBC Driver","DriverVersion":"42.6.0","Datasource":"user_login"},"TagContext":[{"Raw_Trace":"component.dataentry_cfc$cf$nv.udfCall1(/component/DataEntry.cfc:60)","codePrintPlain":"58: \t\t\t\t\t\n59: \t\t\t\t)\n60: \t\t\t\n61: \t\t\t\n62: \t\t\t\tselect bulk_check_one(,'bulkloader') as rslt\n","column":0,"line":60,"template":"/usr/local/webroot/component/DataEntry.cfc","id":"??","type":"cfml","codePrintHTML":"58: \t\t\t\t\t<cfqueryparam value="#usr#" cfsqltype="cf_sql_varchar">
\n59: \t\t\t\t)
\n60: \t\t\t</cfquery>
\n61: \t\t\t<cfquery name="result" datasource="user_login" username="#session.dbuser#" password="#decrypt(session.epw,session.sessionKey,'AES/CBC/PKCS5Padding','hex')#">
\n62: \t\t\t\tselect bulk_check_one(<cfqueryparam value="#tVal.new_cid#" CFSQLType="cf_sql_varchar">,'bulkloader') as rslt
\n"}],"ErrorCode":"0","NativeErrorCode":0,"type":"database","DataSource":"user_login","StackTrace":"lucee.runtime.exp.DatabaseException: ERROR: new row for relation \"bulkloader\" violates check constraint \"bulkloader_record_remark_check\"\n\tat org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)\n\tat org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)\n\tat org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)\n\tat org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:498)\n\tat org.postgresql.jdbc.PgStatement.execute(PgStatement.java:415)\n\tat org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)\n\tat org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:177)\n\tat lucee.runtime.type.util.QueryUtil.execute(QueryUtil.java:353)\n\tat lucee.runtime.type.QueryImpl.execute(QueryImpl.java:306)\n\tat lucee.runtime.type.QueryImpl.(QueryImpl.java:243)\n\tat lucee.runtime.tag.Query.executeDatasoure(Query.java:1134)\n\tat lucee.runtime.tag.Query._doEndTag(Query.java:701)\n\tat lucee.runtime.tag.Query.doEndTag(Query.java:566)\n\tat component.dataentry_cfc$cf$nv.udfCall1(/component/DataEntry.cfc:60)\n\tat component.dataentry_cfc$cf$nv.udfCall(/component/DataEntry.cfc)\n\tat lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:112)\n\tat lucee.runtime.type.UDFImpl._call(UDFImpl.java:356)\n\tat lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:213)\n\tat lucee.runtime.ComponentImpl._call(ComponentImpl.java:702)\n\tat lucee.runtime.ComponentImpl._call(ComponentImpl.java:597)\n\tat lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:2021)\n\tat lucee.runtime.ComponentSpecificAccess.callWithNamedValues(ComponentSpecificAccess.java:156)\n\tat lucee.runtime.ComponentPageImpl.callWDDX(ComponentPageImpl.java:660)\n\tat lucee.runtime.ComponentPageImpl.call(ComponentPageImpl.java:194)\n\tat lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:1058)\n\tat lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:950)\n\tat lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:221)\n\tat lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:44)\n\tat lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2494)\n\tat lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2480)\n\tat lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2451)\n\tat lucee.runtime.engine.Request.exe(Request.java:45)\n\tat lucee.runtime.engine.CFMLEngineImpl._service(CFMLEngineImpl.java:1219)\n\tat lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:1165)\n\tat lucee.loader.engine.CFMLEngineWrapper.serviceCFML(CFMLEngineWrapper.java:97)\n\tat lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:51)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:590)\n\tat io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)\n\tat io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)\n\tat org.cfmlprojects.regexpathinfofilter.RegexPathInfoFilter.doFilter(RegexPathInfoFilter.java:47)\n\tat io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)\n\tat io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)\n\tat io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)\n\tat io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)\n\tat io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)\n\tat io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)\n\tat io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)\n\tat io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117)\n\tat io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)\n\tat io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)\n\tat io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)\n\tat io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)\n\tat io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)\n\tat io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)\n\tat io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)\n\tat io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)\n\tat runwar.Server$1.handleRequest(Server.java:510)\n\tat io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)\n\tat io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)\n\tat io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:280)\n\tat io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79)\n\tat io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134)\n\tat io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131)\n\tat io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)\n\tat io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)\n\tat io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:260)\n\tat io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79)\n\tat io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100)\n\tat io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)\n\tat io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852)\n\tat org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)\n\tat org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019)\n\tat org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558)\n\tat org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449)\n\tat org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280)\n\tat java.base/java.lang.Thread.run(Thread.java:829)\n","where":"","ExtendedInfo":""},"rec_qry":"not_there"}

# Problem
**Community response to describe the problem that caused the error**

# Solution
**Community response with directions for how to correct the problem**

**Comment by dustymc** [comment]
>ERROR: new row for relation "bulkloader" violates check constraint "bulkloader_record_remark_check""

``record_remark`` was entered as ``'\r\n'`` - a return/linefeed.
