### ISSUE TITLE
Feature Request - sanitize citation loader publication ID

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#7989]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

The loader is currently spinning because it's confused itself with an invalid identifier.

**Describe what you're trying to accomplish** 

Clean error

**Describe the solution you'd like**

Sanitize/check

**Describe alternatives you've considered**

There are none.

**Additional context**

@cjconroy I updated status for your records to stop the errors. https://arctos.database.museum/Citation.cfm?publication_id=10011789 isn't valid, perhaps you mean https://arctos.database.museum/publication/10011789? 

**Priority**

High, the current version is capable of pluggin' the toobs.

Going active, this is a bugfix.

**Comment by cjconroy** [comment]
Thanks for catching that. That is the link for when you click to edit a publication. I guess these long URL's look the same to me.
