### ISSUE TITLE
Feature Request - Link to view accession from a record when the accession is private

### ISSUE THREAD

**Issue by happiah-madson** [ArctosDB/arctos#7992]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
All of our accessions are private. When I am looking at a record, I would like to be able to click on the accession to see more information about the accession, but _not_ in the "edit" window. It is my understanding that this is possible when the accession is public, but I do not want our accessions to be public.

**Describe what you're trying to accomplish** 
Easily, with 1 click, get contextual information about the accession.

**Describe the solution you'd like**
I would like the accession number to be hyperlinked.

**Describe alternatives you've considered**
Currently my work around is opening the [Any Transaction: Search and Manage](https://arctos.database.museum/transactionSearch.cfm) and to search for the accession.

**Additional context**
There is no other context.

**Priority**
Medium/Low

**Comment by mkoo** [comment]
HI Hannah, I am adding this as a future discussion topic to the next Issues meeting so we can better understand the community needs-- sounds like maybe we need a clear public comments and private comments for accessions but technically then the accession is public. Maybe we need to refine and define what is publicly available when public.

**Comment by campmlc** [comment]
@happiah-madson  Is there a reason why you don't want to view the accession details through the Edit link? That's what I use, even when I don't want to edit, because it has the complete info on the accession. 
I just tried to find a public accession in our collections to see the difference, and it isn't possible in the current Transaction Search interface as that doesn't seem to be a search option.

**Comment by ebraker** [comment]
@happiah-madson - are you ok with viewing accession info through the edit link? Can we close this issue?

**Comment by happiah-madson** [comment]
We can close this!
