### ISSUE TITLE
Can't save?!

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#7994]
Anyone else having problems saving right now? I was adding image files to records and then the spinny-progress wheel slowed/froze and I got this error: A07034E8-9CDC-4ECE-BD4480EF1A4DBAE5
<img width="726" alt="Screenshot 2024-08-08 at 5 07 59 PM" src="https://github.com/user-attachments/assets/11c6d6cf-0d60-42cf-883a-e331d82ddc03">

Now I can't edit any of the fields in the catalog records. The agents table, however, allowed me to edit/save attributes. 
Odd...
Help!

**Comment by dustymc** [comment]
Bah, there's some automated maintenance that wasn't behaving properly a couple hours ago and I think it's now worse. I'll take the front end down until things can settle if it doesn't clear up in the next few minutes.

**Comment by AJLinn** [comment]
Hooray, fixed! Thanks Dusty.
