### ISSUE TITLE
Question about Bulk Edit Parts: do I need to have "NULL" in the csv or can i just leave the colunm out?

### ISSUE THREAD

**Issue by falco-rk** [ArctosDB/arctos#7999]
I want to Bulk Edit part name and remarks but leave condition, disposition, and part name unchanged. The documentations says "NULL to do nothing". Does this mean that i should upload a csv with all the column and write "NULL" into the columns that i don't want to change or can i upload a csv with just the columns that I want to change and arctos will infer that i don't want to change the other ones?

**Comment by dustymc** [comment]
Leave the column our or leave the value empty to do nothing. ``NULL`` is referring to the type or state, not a string.

Going active to attempt documentation clarification.
