### ISSUE TITLE
[CONTACT: Blocked Network]

### ISSUE THREAD

**Issue by ecnrobertson** [ArctosDB/arctos#8005]
restricted IP: 192.187.62.122

Hello! I'm not sure at all why this has happened but I'm getting a notification that my IP address (192.187.62.122) has been blocked so I can't look at the records. I am trying to double check work I did about a year ago that identified museums that had historical Rosy Finch samples, but I can't access any information. Any help or explanation for why this has happened would be much appreciated.

Thanks!
Erica

**Comment by dustymc** [comment]
Restrictions removed.
