### ISSUE TITLE
bulk edit parts ID verification

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#8006]
**Describe the bug**

 partID isn't being properly sanitized.

**To Reproduce**

see current data

**Expected behavior**

errors, not failures

**Priority**

Critical bug, going active

@falco-rk I flagged some of your records to not load, ``https://arctos.database.museum/guid/OGL:Genomic:30366PID32213975`` isn't valid, you probably mean https://arctos.database.museum/guid/OGL:Genomic:30366/PID32213975 - and I'm guessing another bug made those data for you, please let me know how you got there.

**Comment by falco-rk** [comment]
I am confused by what you are asking about. Can you ask again using different words?

@happiah-madson

**Comment by dustymc** [comment]
>words

User rosiepoulin has data here: https://arctos.database.museum/loaders/bulk_edit_parts.cfm

The thing used as a part_id in those data is not a recognizable part_id, which leads to two concerns:

1. Those data will need fixed, and
2. Possibly something in Arctos was used to generate that (bad) ID, and if so there's a bug which I'd like your help in tracking down.

**Comment by dustymc** [comment]
Check in next release.

I can't find what's making the problem in Arctos, but there is a lot of inconsistency in part[_]id. I'll file an issue.

**Comment by falco-rk** [comment]
If it helps, I got those part IDs from Arctos using the SQL you gave us [here](https://github.com/ArctosDB/arctos/issues/7998) with a this list of barcodes:

OGLA48370,OGLA48406,OGLA48371,OGLA48372,OGLA48373,OGLA48374,OGLA48375,OGLA47567,OGLA47576,OGLA47577,OGLA47578,OGLA47579,OGLA47580,OGLA47581,OGLA47582,OGLA47583,OGLA47584,OGLA47585,OGLA47568,OGLA47586,OGLA47587,OGLA47588,OGLA47589,OGLA47590,OGLA47591,OGLA47592,OGLA47593,OGLA47594,OGLA47595,OGLA47569,OGLA47596,OGLA47597,OGLA47598,OGLA47599,OGLA47600,OGLA47601,OGLA47602,OGLA47603,OGLA47604,OGLA47605,OGLA47570,OGLA47606,OGLA47571,OGLA47572,OGLA47573,OGLA47574,OGLA47575,OGLA50287,OGLA51322,OGLA51332,OGLA51333,OGLA51334,OGLA51336,OGLA51337,OGLA51338,OGLA51340,OGLA51341,OGLA51342,OGLA51344,OGLA51345,OGLA51346,OGLA51348,OGLA51349,OGLA51350,OGLA51324,OGLA51352,OGLA51353,OGLA51354,OGLA51356,OGLA51357,OGLA51358,OGLA51360,OGLA51325,OGLA51361,OGLA51326,OGLA51328,OGLA51329,OGLA51330,OGLA51264,OGLA51265,OGLA51266,OGLA51262,OGLA51267,OGLA51268,OGLA51269,OGLA51270,OGLA51271,OGLA51263,OGLA51362,OGLA51372,OGLA51373,OGLA51374,OGLA51376,OGLA51377,OGLA51378,OGLA51380,OGLA51381,OGLA51382,OGLA51384,OGLA51385,OGLA51386,OGLA51388,OGLA51389,OGLA51390,OGLA51364,OGLA51392,OGLA51393,OGLA51394,OGLA51396,OGLA51397,OGLA51398,OGLA51400,OGLA51365,OGLA51401,OGLA51366,OGLA51368,OGLA51369,OGLA51370,OGLA51244,OGLA51245,OGLA51246,OGLA51242,OGLA51247,OGLA51248,OGLA51249,OGLA51250,OGLA51251,OGLA51243,OGLA51402,Z00FT,Z00GQ,Z00HL,Z00IG,Z00FW,Z00GR,Z00HM,Z00IH,Z00FX,Z00GS,Z00HN,Z00GO,Z00II,Z00FY,Z00GT,Z00HO,Z00IJ,Z00FZ,Z00GU,Z00HP,Z00IK,Z00G0,Z00HJ,Z00GV,Z00HQ,Z00IL,Z00G1,Z00GW,Z00HR,Z00IM,Z00G2,Z00GX,Z00HS,Z00IE,Z00IN,Z00G3,Z00GY,Z00HT,Z00IO,Z00FU,Z00GP,Z00HK,Z00IF,Z00FV,Z00GE,Z00HB,Z00I6,Z00J1,Z00GH,Z00HC,Z00I7,Z00J2,Z00GI,Z00HD,Z00I8,Z00H9,Z00J3,Z00GJ,Z00HE,Z00I9,Z00J4,Z00GK,Z00HF,Z00IA,Z00J5,Z00GL,Z00I4,Z00HG,Z00IB,Z00J6,Z00GM,Z00HH,Z00IC,Z00J7,Z00GN,Z00HI,Z00ID,Z00IZ,Z00J8,Z00GF,Z00HA,Z00I5,Z00J0,Z00GG,OGLA50243,OGLA50252,OGLA50253,OGLA50254,OGLA50244,OGLA50245,OGLA50246,OGLA50247,OGLA50248,OGLA50249,OGLA50250,OGLA50251,OGLA50291,Z00G4,Z00H1,Z00HW,Z00IR,Z00G7,Z00H2,Z00HX,Z00IS,Z00G8,Z00H3,Z00HY,Z00GZ,Z00IT,Z00G9,Z00H4,Z00HZ,Z00IU,Z00GA,Z00H5,Z00I0,Z00IV,Z00GB,Z00HU,Z00H6,Z00I1,Z00IW,Z00GC,Z00H7,Z00I2,Z00IX,Z00GD,Z00H8,Z00I3,Z00IP,Z00IY,Z00G5,Z00H0,Z00HV,Z00IQ,Z00G6,OGLA50255,OGLA50264,OGLA50265,OGLA50266,OGLA51310,OGLA51312,OGLA51313,OGLA51314,OGLA51316,OGLA50256,OGLA51317,OGLA51318,OGLA51320,OGLA51321,OGLA50257,OGLA50258,OGLA50259,OGLA50260,OGLA50261,OGLA50262,OGLA50263,OGLA51273,OGLA51274,OGLA51275,OGLA53564,OGLA53573,OGLA53574,OGLA53575,OGLA53576,OGLA53577,OGLA53578,OGLA53579,OGLA53580,OGLA53581,OGLA53582,OGLA53565,OGLA53583,OGLA53584,OGLA53585,OGLA53586,OGLA53587,OGLA53588,OGLA53589,OGLA53590,OGLA53591,OGLA53592,OGLA53566,OGLA53593,OGLA53594,OGLA53595,OGLA53596,OGLA53597,OGLA53598,OGLA53599,OGLA53600,OGLA53601,OGLA53602,OGLA53567,OGLA53603,OGLA53568,OGLA53569,OGLA53570,OGLA53571,OGLA53572,OGLA51412,OGLA51413,OGLA51414,OGLA51416,OGLA51417,OGLA51418,OGLA51420,OGLA51421,OGLA51422,OGLA51424,OGLA51425,OGLA51426,OGLA51428,OGLA51429,OGLA51430,OGLA51404,OGLA51432,OGLA51433,OGLA51434,OGLA51436,OGLA51437,OGLA51438,OGLA51440,OGLA51405,OGLA51442,OGLA51406,OGLA51408,OGLA51409,OGLA51410,OGLA51254,OGLA51255,OGLA51256,OGLA51252,OGLA51257,OGLA51258,OGLA51259,OGLA51260,OGLA51261,OGLA51253,OGLA50267,OGLA50276,OGLA50277,OGLA50278,OGLA51282,OGLA51284,OGLA51285,OGLA50268,OGLA50269,OGLA50270,OGLA50271,OGLA50272,OGLA50273,OGLA50274,OGLA50275,OGLA51272,OGLA52947,OGLA52956,OGLA52957,OGLA52958,OGLA52959,OGLA52960,OGLA52961,OGLA52962,OGLA52963,OGLA52964,OGLA52965,OGLA52948,OGLA52966,OGLA52967,OGLA52968,OGLA52969,OGLA52970,OGLA52971,OGLA52972,OGLA52973,OGLA52974,OGLA52975,OGLA52949,OGLA52976,OGLA52977,OGLA52978,OGLA52979,OGLA52980,OGLA52981,OGLA52982,OGLA52983,OGLA52984,OGLA52985,OGLA52950,OGLA52986,OGLA52951,OGLA52952,OGLA52953,OGLA52954,OGLA52955,OGLA48367,OGLA48376,OGLA48377,OGLA48378,OGLA48379,OGLA48380,OGLA48381,OGLA48382,OGLA48383,OGLA48384,OGLA48385,OGLA48368,OGLA48386,OGLA48387,OGLA48388,OGLA48389,OGLA48390,OGLA48391,OGLA48392,OGLA48393,OGLA48394,OGLA48395,OGLA48369,OGLA48396,OGLA48397,OGLA48398,OGLA48399,OGLA48400,OGLA48401,OGLA48402,OGLA48403,OGLA48404,OGLA48405,OGLA48370,OGLA48406,OGLA48371,OGLA48372,OGLA48373,OGLA48374,OGLA48375,OGLA47567,OGLA47576,OGLA47577,OGLA47578,OGLA47579,OGLA47580,OGLA47581,OGLA47582,OGLA47583,OGLA47584,OGLA47585,OGLA47568,OGLA47586,OGLA47587,OGLA47588,OGLA47589,OGLA47590,OGLA47591,OGLA47592,OGLA47593,OGLA47594,OGLA47595,OGLA47569,OGLA47596,OGLA47597,OGLA47598,OGLA47599,OGLA47600,OGLA47601,OGLA47602,OGLA47603,OGLA47604,OGLA47605,OGLA47570,OGLA47606,OGLA47571,OGLA47572,OGLA47573,OGLA47574,OGLA47575

**Comment by dustymc** [comment]
Oh sure, blame me, just 'cuz I did I wrong....

I updated that SQL.

Thanks!

**Comment by falco-rk** [comment]
I wasn't trying to blame you! I was trying to be helpful!

If i try again, will it work?

**Comment by dustymc** [comment]
Sorry I was trying to be clever, that was helpful. Yes the SQL should now produce valid partIDs.
