### ISSUE TITLE
Data Entry: Apostrophe handling

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#801]
Something is escaping/not-unescaping singlequotes in (at least) taxon name, specimen remarks. Seems to be somewhere between data entry screen and BL table. (AJL)

**Comment by AJLinn** [comment]
Reopening this issue 
Looks like the data entry page is still having problems with apostrophes, this time when pulling from an existing agent record.

My curatorial assistant had to save this entry with an "unknown" creator and then add the correct agent after the record loads.

This is what it should look like:
<img width="487" alt="Screenshot 2023-06-09 at 6 26 34 PM" src="https://github.com/ArctosDB/arctos/assets/17605945/bb801924-a10e-474e-bf5d-b680463f218f">


This is what it turns into upon tabbing:
<img width="487" alt="Screenshot 2023-06-09 at 6 25 19 PM" src="https://github.com/ArctosDB/arctos/assets/17605945/9a34c588-aa2a-42e5-9dc3-8dcb5fc429b0">


And this is what it says when she tried to save:
<img width="487" alt="Screenshot 2023-06-09 at 6 25 40 PM" src="https://github.com/ArctosDB/arctos/assets/17605945/af5c713e-22b4-4b79-9b35-6b7f00d2df9f">
