### ISSUE TITLE
Planned outage- Friday August 23, 2024- 7 am PT/ 9 am CT

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#8010]
## Planned Outage for maintenance
 - Date and time outage will begin:  Friday August 23, 2024- 7 am PT/ 9 am CT
 - Expected to last 1 hour
 - Reason for outage: Planned maintenance
 - Expected behavior during and after the outage: Arctos database will be unavailable for use

## Communication before/during outage
- [x] Pin this issue
- [x] Banner updated @mkoo
- [x] Email sent to AWG  

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated 
- [ ] Email sent to AWG 
- [ ] Close this issue when above are complete

**Comment by ewommack** [comment]
Scheduled emails to go out on Monday 19th and Thursday 22nd of August.

**Comment by lin-fred** [comment]
Is there a reason tweets were removed from this? Was it decided no tweets are going out anymore?
