### ISSUE TITLE
Barcode Series Request - 

### ISSUE THREAD

**Issue by bryansmclean** [ArctosDB/arctos#8012]
Issue Documentation is at http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html 
Barcode Series Documentation is at http://handbook.arctosdb.org/documentation/container.html#barcode-series

Please supply the following so that we can evaluate your barcode series request. If the series is available, it will be claimed and created for you. If it is not, a response will be posted to this issue and we will work to get you a suitable barcode series.

First barcode in series: GT0001

Last barcode in series: GT9999

<img width="56" alt="image" src="https://github.com/user-attachments/assets/39917d3c-ad32-4a6a-9e59-a9aed8c25b88">

**Priority**
High

**Comment by dustymc** [comment]
done

**Comment by bryansmclean** [comment]
THANKS @dustymc!

**Comment by bryansmclean** [comment]
Why this error?

![image](https://github.com/user-attachments/assets/a81fcf4a-c7c4-4220-83b5-428e2712c3a6)

**Comment by dustymc** [comment]
I can't diagnose from an image, I need text. Also might be useful to scan the barcode into the text.

**Comment by bryansmclean** [comment]
Error was received when entering into the part_1_barcode field

2024-8-29T9:59:40: FAIL: part_1_barcode [ GT-0001 ] is invalid or inaccessible to mclean: {"message":"part_1_barcode [ GT-0001 ] is invalid or inaccessible to mclean","status":"fail"}

**Comment by dustymc** [comment]
Thanks. You don't have a series with a dash:

 GT0001 - GT9999

**Comment by bryansmclean** [comment]
Whoops sorry - I was just trying different options. I got the same errors when including no space and a single space

2024-8-29T9:59:31: FAIL: part_1_barcode [ GT 00001 ] is invalid or inaccessible to mclean: {"message":"part_1_barcode [ GT 00001 ] is invalid or inaccessible to mclean","status":"fail"}
2024-8-29T9:59:27: FAIL: part_1_barcode [ GT00001 ] is invalid or inaccessible to mclean: {"message":"part_1_barcode [ GT00001 ] is invalid or inaccessible to mclean","status":"fail"}

**Comment by dustymc** [comment]
OH - you didn't create the containers, only the series. You need to create containers before you can use them.

**Comment by bryansmclean** [comment]
Ah thanks @dustymc. Ill need to create that barcode series and will do so on a separate thread. Leaving open for now until I confirm this works with the new containers...
