### ISSUE TITLE
Barcode Series Request - 

### ISSUE THREAD

**Issue by bryansmclean** [ArctosDB/arctos#8013]
Issue Documentation is at http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html 
Barcode Series Documentation is at http://handbook.arctosdb.org/documentation/container.html#barcode-series

Please supply the following so that we can evaluate your barcode series request. If the series is available, it will be claimed and created for you. If it is not, a response will be posted to this issue and we will work to get you a suitable barcode series.

First barcode in series: GP0001

Last barcode in series: GP9999

<img width="58" alt="image" src="https://github.com/user-attachments/assets/761ca13b-89fe-422d-b2bb-1b797c3a648d">

**Priority**
High

**Comment by dustymc** [comment]
done
