### ISSUE TITLE
Feature Request - allow markdown in table metadata

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#8015]
**Is your feature request related to a problem? Please describe.**

Code table metadata is becoming an increasingly important source of documentation and direction, and some of it's complex and could benefit from formatting (see eg https://github.com/ArctosDB/arctos/issues/7844). HTML is kinda dangerous while markdown is ubiquitous and safe.

**Describe what you're trying to accomplish** 

Safely allow formatting

**Describe the solution you'd like**

Process code table metadata as markdown

**Describe alternatives you've considered**

Allow html and hope for the best!

**Additional context**

https://docs.google.com/spreadsheets/d/1-QC9L8jbOzaG7vstp5iHyx8ivlyvr3BrtiCY_GBimAg/edit?gid=0#gid=0

**Priority**

High??

@mkoo is this a useful idea?

**Comment by dustymc** [comment]
* also for code table documentation
* is it possible to specify a class, or open all markdown in _blank?

**Comment by dustymc** [comment]
Re-prioritizing after discussion with @mkoo  - not having this will cause major headaches, implementation should be easy and non-disruptive.

**Comment by mkoo** [comment]
I am not sure where this goes but also a reminder that URL links can all have class="external"

**Comment by dustymc** [comment]
In next release for code table metadata; will open another issue for individual definitions.
