### ISSUE TITLE
Feature Request - Add new search field to Pub/ Project search page

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#8018]
**Describe what you're trying to accomplish** 
This is one of the issues brought up in #3468 

Allow searches of Projects by person who created the Project

Possible challenges might be that the agent who created the Project is not stored in the log. I only see the last editedby person (which does come up in Participant searches) 
related: https://github.com/ArctosDB/arctos/issues/3915

**Comment by dustymc** [comment]
Done!

<img width="326" alt="Screenshot 2024-08-16 at 17 33 30" src="https://github.com/user-attachments/assets/52b1ef1d-2031-4a9c-864e-08b954b4322a">
<img width="1375" alt="Screenshot 2024-08-16 at 17 33 39" src="https://github.com/user-attachments/assets/6a408f08-9c79-4948-8181-0f561ee31647">
