### ISSUE TITLE
markdown in code table documentation?

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#8023]
**Is your feature request related to a problem? Please describe.**

I said we'd allow markdown in code table definitions in https://github.com/ArctosDB/arctos/issues/8015 (maybe because @mkoo asked me to?). I'm not sure that makes sense in "modernized" code tables, which have dedicated slots for issue and documentation links.

**Describe what you're trying to accomplish** 

Make things as simple as possible yet as complex as necessary

**Describe the solution you'd like**

Know if there's some compelling reason to support markdown in definitions. At the moment, I don't think there is.

**Describe alternatives you've considered**

Do nothing.

**Additional context**

Modernization is underway, see https://github.com/ArctosDB/arctos/issues/8022

**Priority**

Only high if an answer here changes something for https://github.com/ArctosDB/arctos/issues/8022.

**Comment by dustymc** [comment]
I think this has answered itself. I'm trying to update a code table (https://github.com/ArctosDB/code-table-work/issues/1). I can't save because the current description contains HTML, which is disallowed. The current HTML is not valid - and in an evil sort of way, so I'm pretty happy to find that I can't save it. The thing I'm trying to update is complex and could greatly benefit from some formatting.

I'm going active development, please let me know NOW if that seems like a bad idea for some reason.

**Comment by mkoo** [comment]
I see no objections-- let me know if any content needs to be rewritten in md or simply cleaned up in new version. Please post if testable in test

**Comment by dustymc** [comment]
>content needs to be rewritten

Yes, but probably after https://github.com/ArctosDB/arctos/issues/8022 (and individual tables can be prioritized - just leave a comment).

>testable

https://github.com/ArctosDB/arctos/milestone/14 are testable.
