### ISSUE TITLE
identifier issued by display

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#8024]
**Is your feature request related to a problem? Please describe.**

Need to write and implement a function to use https://github.com/ArctosDB/arctos/issues/7722

**Describe what you're trying to accomplish** 

Allow issuedby and preferred names to display differently.

**Describe the solution you'd like**

above

**Describe alternatives you've considered**

nope

**Additional context**

none

**Priority**

Critical, this is needed for reports.

I know how to do this.

Going active.

**Comment by campmlc** [comment]
Will this allow "issued by" to be separated from the ID value in reports and tool displays? If so, I strongly support this.
