### ISSUE TITLE
SQL Help please

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#8029]
I'm trying to pull data in WriteSQL for some inventory work and I keep getting this error:  "The code you submitted contains illegal characters."
I've narrowed it down to the three CASE WHEN statements at the bottom. If I remove the CASE clause, the coalesce functions work fine. Can you help my syntax here?

select		
		flat.guid,
		flat.cat_num,
		flat.scientific_name,
		flat.parts,
		flat.country,
		flat.state_prov,
		flat.county,
		flat.verbatim_locality,
		flat.spec_locality,
		round(flat.dec_lat::numeric,5) as latitude,
		round(flat.dec_long::numeric,5) as longitude,
		flat.verbatim_date,
		flat.began_date,
		flat.ended_date,
		flat.othercatalognumbers,
		replace(replace(replace(replace(replace(replace(replace(replace(flat.collectors,'Greenwood Wildlife Rehabilitation Center','GWRC'),'Colorado Parks and Wildlife','CPW'),'Denver Museum of Nature & Science','DMNS'),'Colorado Department of Public Health and Environment','CDPHE'),'Rocky Mountain Raptor Program','RMRP'),'Colorado Natural Heritage Program','CNHP'),'National Ecological Observatory Network','NEON'),'Colorado Wild Rabbit Foundation','CWRF') as collectors,
		flat.preparators,
		flat.ACCESSION,
		ConcatAttributevalue(flat.collection_object_id,'age class') as age_class, 
		ConcatAttributevalue(flat.collection_object_id,'life stage') as life_stage, 
		flat.sex,
		flat.guid_prefix,
		flat.phylorder,
		flat.family,
		flat.genus,
		flat.species,
		flat.subspecies,
		coalesce('DZTM: ' || concatsingleOtherid(flat.collection_object_id,'DZTM: Denver Zoology Tissue Mammal'),'') as DZTM, 
		coalesce('DZTB: ' || concatsingleOtherid(flat.collection_object_id,'DZTB: Denver Zoology Tissue Bird'),'') as DZTB,
		coalesce('DZTH: ' || concatsingleOtherid(flat.collection_object_id,'DZTH: Denver Zoology Tissue Herp'),'') as DZTH,
		flat.month,
		flat.collection_object_id,
		flat.typestatus,
		case when guid_prefix = 'DMNS:Mamm' then coalesce(replace(ConcatAttributevalue(flat.collection_object_id,'total length'),' mm','') || '-' || replace(ConcatAttributevalue(flat.collection_object_id,'tail length'),' mm','') || '-' || replace(ConcatAttributevalue(flat.collection_object_id,'hind foot with claw'),' mm','') || '-' || replace(ConcatAttributevalue(flat.collection_object_id,'ear from notch'),' mm','') || '≡' || ConcatAttributevalue(flat.collection_object_id,'weight')) else '' end mamm_meas,
		case when guid_prefix = 'DMNS:Bird' then coalesce(ConcatAttributevalue(flat.collection_object_id,'total length') || '-' || ConcatAttributevalue(flat.collection_object_id,'wing chord') || '≡' || ConcatAttributevalue(flat.collection_object_id,'weight')) else '' end bird_meas,
		case when guid_prefix = 'DMNS:Herp' then coalesce('tot.' || ConcatAttributevalue(flat.collection_object_id,'total length') || '-svl.' || ConcatAttributevalue(flat.collection_object_id,'snout-vent-length') || '-tail.' || ConcatAttributevalue(flat.collection_object_id,'tail length') || '≡' || ConcatAttributevalue(flat.collection_object_id,'weight')) else '' end herp_meas
	FROM
		flat
	WHERE guid_prefix = 'DMNS:Mamm' and cat_num = '21000'
	ORDER BY guid_prefix,flat.cat_num::numeric

**Comment by dustymc** [comment]
Yea, the case statements are not allowed. I'm not sure I can change that without also changing the access because of how some back-end things (meant to allow large queries to run) operate. There's nothing scary about your SQL, but I don't have a great way to allow it and disallow scary things that sorta look like it.

I can spend some more time looking for a way around that restriction if this is important, or I can run SQL for you.

Restricting access to this app (eg to manage_records) would let me relax some constraints and still sleep at night - maybe that's the best path forward?

**Comment by acdoll** [comment]
Then don't worry about it; I'll just keep a copy of this code specific to each collection. I was just trying to make it easy if I pass this task off to someone else. Thanks for taking a look - I thought I was going crazy.
BTW - I really appreciate the 'demo FLAT' and 'FLAT structure' buttons you've added to that page - it quicker when I need to remind myself what I can pull from FLAT.
Are those JSON columns supposed to show up like this or display the values?:
![image](https://github.com/user-attachments/assets/d389480f-908e-422f-9b31-684736631f5d)
They download fine in the CSV so it's not really much of an issue.

**Comment by dustymc** [comment]
>crazy

I mean, not mutually exclusive.... - HA!

>show up like this

Kinda, but not too useful. I'll see what I can do. FYI you can just cast to varchar and it'll figure out what you want eg

```sql
SELECT partdetail::varchar from flat where partdetail is not null limit 1

[{"part_id": 26315733, "condition": "unchecked", "part_name": "skin", "part_count": 1, "disposition": "in collection", "part_remark": null, "part_barcode": null, "container_path": null, "part_attributes": null, "sampled_from_part_id": null}, {"part_id": 26315734, "condition": "unchecked", "part_name": "skull", "part_count": 1, "disposition": "in collection", "part_remark": null, "part_barcode": null, "container_path": null, "part_attributes": null, "sampled_from_part_id": null}]
```

and then you can use something like https://jsonformatter.org/ to make it readable

```json
[
  {
    "part_id": 26315733,
    "condition": "unchecked",
    "part_name": "skin",
    "part_count": 1,
    "disposition": "in collection",
    "part_remark": null,
    "part_barcode": null,
    "container_path": null,
    "part_attributes": null,
    "sampled_from_part_id": null
  },
  {
    "part_id": 26315734,
    "condition": "unchecked",
    "part_name": "skull",
    "part_count": 1,
    "disposition": "in collection",
    "part_remark": null,
    "part_barcode": null,
    "container_path": null,
    "part_attributes": null,
    "sampled_from_part_id": null
  }
]
```

**Comment by acdoll** [comment]
Thanks!
