### ISSUE TITLE
restrictions on moving positions

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#803]
I am running into issues with the prohibition against moving positions. There are containers that require positions for which no form is available to automatically create positions in situ; for example, freezer box positions in a freezer rack, jar positions on a shelf etc. I need to be able to create these positions using bulk edit container and then scan them into the parent container once they are created. 
Now, I get an error message saying positions may not be moved. Is there something I am missing?

**Comment by KyndallH** [comment]
You are not missing anything. My solution has been to make Dusty move them for me but this is not a long term solution. I like Dusty's suggestion to be able to move positions until they have a parent. I'm trying to think of instances where I'd need to move a position after it has a parent but none come  to mind. I'll think on it.

**Comment by dustymc** [comment]
positions with an :OLD.parent_container_id of 0 (eg, those in never-never land) may now be moved.
