### ISSUE TITLE
Component loader stuck

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#8033]
I've been watching the component loader all day today and nothing has been loading. @KatherineLAnderson locality attribute data was at the top and eventually I reordered with my data loan item load on top thinking maybe it was just loc attributes that were stuck. Over half an hour later and those haven't started loading either.

**Comment by dustymc** [comment]
Looks like things didn't fully recover from https://github.com/ArctosDB/arctos/issues/8026. I need ~10 minutes of downtime to reboot the VM. I can do that at 5 Pacific (or a little later) today when I push a release out if someone will schedule that.

@mkoo sound OK?

**Comment by mkoo** [comment]
yes please-- I'll update the banner

**Comment by dustymc** [comment]
component loader now claims to be running
