### ISSUE TITLE
Arctos Down - Planned outage for 10 minutes today 8/21 at 5 pm Pacific Time

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#8034]
Arctos needs a little kick in the pants to unstuck the component loader-- should be brief ca. 10 minutes

## Planned Outage
 - Date and time outage will begin: Planned outage today 8/21 at 5 pm Pacific Time
 - Expected duration of outage: 10 minutes
 - Reason for outage: https://github.com/ArctosDB/arctos/issues/8033
 - Expected behavior during and after the outage: unavailable-- please save your work!

## Communication before/during outage
- [x] Pin this issue
- [x] Banner updated @mkoo
- [ ] Email sent to AWG  
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [x] Unpin this issue
- [x] Banner updated @mkoo
- [ ] Email sent to AWG 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by dustymc** [comment]
reboot done, banner updated
