### ISSUE TITLE
Media thumbnails  on tagged jpeg

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#8037]
I have three records for dolls that are depicted in the same photograph. 
https://arctos.database.museum/guid/UAM:EH:UA82-003-0065
https://arctos.database.museum/guid/UAM:EH:UA82-003-0048AC
https://arctos.database.museum/guid/UAM:EH:UA81-003-0180

I used the tag tool to highlight each one and all three are related as "shows cataloged item".
The file is only 483 KB but the thumbnail never shows up - I just get the "media available" bear. As cute as that is, it's not helpful for my researchers. I'm pretty sure I've done multiple cache refresh requests over the years and it never fixes it.

Any suggestions to making this work so [users don't see this](https://arctos.database.museum/search.cfm?guid_prefix=UAM%3AEH&scientific_name=doll&scientific_name_match_type=contains&collection_object_id=23836277%2C23835821%2C23834978&sp=preset_eh)?
<img width="1536" alt="Screenshot 2024-08-22 at 12 22 02 PM" src="https://github.com/user-attachments/assets/2ceda74a-8b05-466d-a8b1-d5a559b437a3">

**Comment by dustymc** [comment]
I don't have the logs/data to be very sure, but I think someone removed the thumbs.

I opened one of those to this:


<img width="486" alt="Screenshot 2024-08-22 at 13 39 27" src="https://github.com/user-attachments/assets/bb4bbbd7-2983-449d-af40-e340252f312d">

clicked the link, clicked the return link, got....

<img width="280" alt="Screenshot 2024-08-22 at 13 39 52" src="https://github.com/user-attachments/assets/d94240d8-643a-4ba9-8685-e166a7d84bac">

counted to 17, hit reload, and ...

<img width="647" alt="Screenshot 2024-08-22 at 13 40 12" src="https://github.com/user-attachments/assets/62c307f6-5d57-4922-9f9e-65fd02cf70fb">

It's not ENTIRELY impossible that the generator was reporting happy things while doing nothing, but I can't really see how it would be either, and it clearly (https://web.corral.tacc.utexas.edu/arctos-s3/thumbs/2024-08-22/tn_10611610.jpg) works now.

Any clue as to what might have happened greatly appreciated.

It'll probably take an hour or so for the new thumb to make its way to all the caches.

**Comment by dustymc** [comment]
Nevermind - I do have some data, https://web.corral.tacc.utexas.edu/arctos-s3/thumbs/2020-06-25/tn_10611610.jpg exists. (I guessed it would from the message in the first screenshot.) I suppose I still can't be ABSOLUTELY sure that it was ever used, possibly there was some outage in the milliseconds between logging creation and updating the media record or etc., but anything other than someone editing the media to remove the thumb feels unlikely to me.

**Comment by AJLinn** [comment]
Before leaving for lunch i went ahead and requested another cache refresh and now the thumbs are showing in the records! Hooray. I'll wait a bit longer to see if they start showing up in the search results.

**Comment by AJLinn** [comment]
Thumbnails are now visible at search results and in the catalog detail page. Thanks for whatever got done. :-)
