### ISSUE TITLE
request to add attribute determiner to specimen results download options

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#804]
Not sure if this is a possibility - but I would like to request that attribute determiner and date be added to the tools option for downloading specimen results. Parasitologists need to be able to download and/or pull host data to catalog associated parasites. The host attribute determiner and date for "examined for endoparasites" and "endoparasites found" becomes the collector and collection date for the cataloged parasite specimens, as well as  the identifying agent.

**Comment by dustymc** [comment]
It's possible, but I'm not sure how practical. There are 123 distinct attribute types right now, throw in method and we end up with 500 (and growing) choices in the "customize" panel. Have you tried the "download for bulkloader" option?

**Comment by campmlc** [comment]
Ah, that works! Didn't know that was there. The parts/table download is
also very useful. Thanks!
