### ISSUE TITLE
locality mapper

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#805]
http://goo.gl/pwVocK

click berkeleymapper

fail

**Comment by mkoo** [comment]
From which page?
Error message or not?

It's working for me on AmphibiaWeb but throwing up this complaint first:

> A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.
> 
> Script: http://maps.google.com/maps/ap…rue&libraries=drawing,geometry:53

Ignoring it let's it complete drawing whatever.
@jdeck88 ?

**Comment by dustymc** [comment]
@mkoo: Internal Arctos thing from the URL above. 

fixed and patched in
