### ISSUE TITLE
Request - Use of the part name Feces by NMZ

### ISSUE THREAD

**Issue by hannahb2402** [ArctosDB/arctos#8055]
Help us understand your request (check below):
- [ ] search or data request (help with SQL or provide the specific fields you are trying to retrieve for your collection)
- [ ] add a new Github user to the Arctos Users team
- [ ] a new barcode series
- [ ] a new term for data entry or management 
- [ ] a change or new report or label
- [ ] update to an Agent (split, merge, or other type of change)
- [ ] bulkload changes (to Agents, Identifiers, etc that are not already available as a bulkloading tool)
- [ ] new feature or otherwise a good idea to make Arctos even better
- [ ] quarantine taxon name and suggested replacement (please supply links)
- [x ] other

**Describe what you're trying to do** 
I'm trying to request the use of the part named feces by NMZ:Mamm: In the past, there was no need for this part because it was never collected. Over the summer we expanded the collection with more part names.
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#feces

**Comment by mkoo** [comment]
HI Hannah, if you have collection management permissions you can add that part to your available parts yourself by going to the same CT page you listed and clicking the Collection settings box. the table with then have checkboxes to add in specific parts:
![Firefox_Screenshot_2024-08-28T17-58-28 978Z](https://github.com/user-attachments/assets/62681465-ede6-41ba-8db1-a74f5161beb3)

If you dont, please see your supervisor. Let us know if we can help further!

**Comment by jrpletch** [comment]
Thanks for the help, we were able to get it added.
