### ISSUE TITLE
Publication bulkloader?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#8059]
What happened to the publication bulkloader? Am I missing something?
My Tools option only includes a Citation Bulkloader and a link to Publications and Projects, which would only allow one publication entered at a time.
I have a student who is going to be tracking down publications related to loans, entering them in Arctos, and then created the bulkload file for citations. I had hoped she could fill out the publication bulkload file so I could review before adding, and so that she did not have to enter one at a time. Possible?

**Comment by dustymc** [comment]
Duplicate of https://github.com/ArctosDB/arctos/issues/1565
