### ISSUE TITLE
Adding SEM stub to Parasite parts

### ISSUE THREAD

**Issue by msbparasites** [ArctosDB/arctos#806]
This is a request to add parts to the Parasite part code table. These are 8 parts that exist already, but that we are finding that we need:

-SEM stub
-DNA (dry)
-DNA (frozen)
-Blood (slide smear)
-photograph - this would be in the case of some apicomplexan parasites (coccidia, in particular)

-whole organism (cleared and stained) - we do have cases where someone clears a flatworm, stains it, but then gets returned to a vial/jar rather than mounted on a slide, or just parts that later it was decided not to mount.

-whole organism (cleared, ethanol)

-whole organism (formalin-fixed, ethanol) - I am not sure I saw this option with formalin first, then ethanol, but for decades, this was common practice and this is also what we do with samples we have in formalin.

Would there be any objections? Thank you.
Sara

**Comment by dustymc** [comment]
No objections from me, and I don't think anyone else will either as you're currently the only parasite collection. @campmlc can add them. Please be careful of CaSe - "blood" not "Blood" - try to match existing values used in other collection types, add documentation, etc.

>photograph

Not really necessary and bound to eventually diverge from Media if it's digital - if it's a "thing to which one could stick a barcode" (our working definition of "parts") then go for it.

>whole organism (formalin-fixed, ethanol)...with formalin first

We seem to have both ways. If formalin-fixed, ethanol and ethanol, formalin-fixed are different it should be documented. If not, we're just preventing users from finding what they want. (I'll push the buttons if someone wants to take the lead in cleaning any code tables up, especially this one!)

UAM@ARCTOS> select distinct part_name from ctspecimen_part_name where part_name like '%formalin%';

liver (isopropanol, formalin-fixed)
other (formalin)
tissue (formalin)
reproductive tract (ethanol, formalin-fixed)
eye (formalin)
body (formalin-fixed, 70% ethanol)
carcass (isopropanol, formalin-fixed)
fetus (isopropanol, formalin-fixed)
glans penis (formalin-fixed, 70% ethanol)
intestine (formalin)
stomach (formalin)
stomach content (formalin)
whole organism (isopropanol, formalin-fixed)
skull (formalin)
trematode(s) (formalin)
embryo (formalin-fixed, 70% ethanol)
embryo (isopropanol, formalin-fixed)
carcass (formalin)
carcass (formalin-fixed, 70% ethanol)
cestode(s) (formalin-fixed, 70% ethanol)
liver (formalin)
testis (formalin)
whole organism (formalin-fixed)
glans penis (formalin)
gonad (formalin)
whole organism(s) (formalin-fixed)
dissected whole organism (formalin)
feces (formalin)
lung (formalin)
oral swab (formalin)
phallus (formalin-fixed, 70% ethanol)
postcranial skeleton (ethanol, formalin-fixed)
spleen (formalin)
endoparasite(s) (formalin)
penis (formalin)
postcranial whole organism (formalin)
testis (formalin-fixed, 70% ethanol)
whole organism (formalin)
whole organism (formalin-fixed, 70% ethanol)
ectoparasite(s) (formalin-fixed, 70% ethanol)
cestode(s) (formalin)
ovary (formalin)
phallus (formalin)
reproductive tract (formalin)
dissected whole organism (ethanol, formalin-fixed)
body parts (formalin)
gastrointestinal tract (formalin)
lung (isopropanol, formalin-fixed)
nematode(s) (formalin)
postcranial whole organism (ethanol, formalin-fixed)
tissue (formalin-fixed)
reproductive tract (formalin-fixed, 70% ethanol)
vibrissa (ethanol, formalin-fixed)
viscera (formalin)
whole organism (ethanol, formalin-fixed)
egg (formalin)
embryo (formalin)

57 rows selected.

**Comment by msbparasites** [comment]
Thanks for the quick response. I will work with Mariel to add them.

RE: photograph - yes, these would be old fashioned black and white photographs, probably developed by the parasitologist. Agreed about digital media images. The photographs we have will be barcoded......at some point....

RE: whole organism (formalin-fixed, ethanol)...with formalin first
thanks for the list, I see that 'whole organism (formalin-fixed, 70% ethanol)' exists, and we can use that and then in remarks state if we have different concentration, or just a general ethanol as I suggested will be fine too - there we will also write what is the concentration. It is usually for us either 70% or 80%.

**Comment by campmlc** [comment]
New MSB Para parts added.
I attempted to use Modify Parts to convert all MSB Para "whole organism(s) frozen" to "whole organism (frozen)" for consistency. Please verify.  I received no error message but the new parts are not showing up on search. Will need to delete "whole organism(s) (frozen)" from code table if successful.
