### ISSUE TITLE
Help needed in Arctos -merge attribute download into search results download

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#8060]
# Tell us what you are trying to do 
I would like to share a csv file of a set of records with a group of researchers coming in about a month. I downloaded [this csv](https://drive.google.com/file/d/1nqm3jmvD3174e7phi7vhDEJK-oLuz290/view?usp=sharing) file but because I need them to see the attribute "description" so they can understand what the piece looks like, I downloaded the attributes for this selection of records as well, which included some other attributes I was able to get from the download ([csv file here](https://drive.google.com/file/d/1nqtK70aIByiIUAFr-FkqMRv6SoXfBtQY/view?usp=sharing)).

Now I need to get the content in the rows with attribute_type description into the main spreadsheet as a column aligned with the correct catalog number row, and I don't need any of the unit, method, date, determiner, or remark fields from the attribute download spreadsheet.

How do I make that happen? Can someone who is a CSV manipulator magician help me out? This is why I desperately wanted to be able to show the attribute description in the search results, because this seems terribly complicated.

# What are relevant pages in Arctos
Here's the [original search results!](https://arctos.database.museum/search.cfm?guid_prefix=UAM%3AEH&scientific_name=doll&scientific_name_match_type=contains&remove_row=23816221%2C24419938%2C23826623%2C24419953%2C24419956%2C23826626%2C24419941%2C23826692%2C23826629%2C26830273%2C23842491%2C29842974%2C29842998%2C23820390%2C23831399%2C23810428)

Thanks for any help, and if you can do this, maybe you can schedule a zoom to show me how?

**Comment by dustymc** [comment]
Is this addressed by https://github.com/ArctosDB/arctos/issues/6717?

**Comment by dustymc** [comment]
>spreadsheet

Reports can produce CSV (and I'm not sure about the images either, but the data are there so it should be possible).

**Comment by dustymc** [comment]
I pulled some code from your report in https://github.com/ArctosDB/arctos/issues/6717 and  uam_mamm_label_csv to make uam_eh_csv_test https://arctos.database.museum/Reports/reporter.cfm?action=edit&report_id=222

Then I uploaded to google sheets and added column c using  https://support.google.com/docs/answer/3093333?hl=en

<img width="924" alt="Screenshot 2024-08-29 at 09 31 40" src="https://github.com/user-attachments/assets/53ac8d0b-9e5f-48da-b2c1-e9763801fca5">

**Comment by AJLinn** [comment]
WOW! That automatic image insertion/sizing is some kind of white magic! Lemme play with it and see if that's going to be the new standard for me... this is some kind of amazing tool.

**Comment by AJLinn** [comment]
@dustymc is there five minutes when you can show me  how you used those Google instructions?

**Comment by dustymc** [comment]
@AJLinn how's this:



https://github.com/user-attachments/assets/5dd4959f-c760-4575-a9fd-215820b8c95e

**Comment by AJLinn** [comment]
WTH is that magical code?!?!? 16 seconds was perfect! I can't even believe the time I wasted in the past inserting those images manually... holy shirt...
I feel so powerful! Thank you @dustymc

**Comment by AJLinn** [comment]
@dustymc How do I use this report again? When I go into the Arctos reporter now I see this:
<img width="983" alt="Screenshot 2024-11-12 at 11 26 47 AM" src="https://github.com/user-attachments/assets/84d49259-6ce1-4d24-ad61-d2e64ef27f34">

... instead of the list of reports to put into action...
I was just starting to get the hang of things! I'm sorry but I really need help on getting re-oriented. I tried to use the "Download search results as displayed" button but I can't do the magical google sheet image auto-populate with image column because the media column downloads as this:

[{"MC": "image", "MI": 10854096, "MT": "image/jpeg", "MU": "https://web.corral.tacc.utexas.edu/arctos-s3/mlsievers/2024-09-20/UA2024_008_0001_1.JPG", "PU": "https://web.corral.tacc.utexas.edu/arctos-s3/thumbs/2024-09-20/tn_10854096.jpg", "TN": "https://web.corral.tacc.utexas.edu/arctos-s3/thumbs/2024-09-20/tn_10854096.jpg"}, {"MC": "image", "MI": 10856795, "MT": "image/jpeg", "MU": "https://web.corral.tacc.utexas.edu/arctos-s3/mlsievers/2024-10-09/UA2024_008_0001_2.JPG", "PU": "https://web.corral.tacc.utexas.edu/arctos-s3/thumbs/2024-10-09/tn_10856795.jpg", "TN": "https://web.corral.tacc.utexas.edu/arctos-s3/thumbs/2024-10-09/tn_10856795.jpg"}, {"MC": "image", "MI": 10856796, "MT": "image/jpeg", "MU": "https://web.corral.tacc.utexas.edu/arctos-s3/mlsievers/2024-10-09/UA2024_008_0001_3.JPG", "PU": "https://web.corral.tacc.utexas.edu/arctos-s3/thumbs/2024-10-09/tn_10856796.jpg", "TN": "https://web.corral.tacc.utexas.edu/arctos-s3/thumbs/2024-10-09/tn_10856796.jpg"}, {"MC": "image", "MI": 10856797, "MT": "image/jpeg", "MU": "https://web.corral.tacc.utexas.edu/arctos-s3/mlsievers/2024-10-09/UA2024_008_0001_4.JPG", "PU": "https://web.corral.tacc.utexas.edu/arctos-s3/thumbs/2024-10-09/tn_10856797.jpg", "TN": "https://web.corral.tacc.utexas.edu/arctos-s3/thumbs/2024-10-09/tn_10856797.jpg"}, {"MC": "image", "MI": 10856798, "MT": "image/jpeg", "MU": "https://web.corral.tacc.utexas.edu/arctos-s3/mlsievers/2024-10-09/UA2024_008_0001_5.JPG", "PU": "https://web.corral.tacc.utexas.edu/arctos-s3/thumbs/2024-10-09/tn_10856798.jpg", "TN": "https://web.corral.tacc.utexas.edu/arctos-s3/thumbs/2024-10-09/tn_10856798.jpg"}]

... instead of the reporter taking one image from the batch... is there a new automagic CSV formula I need to do to make this work again?
HELP please!

**Comment by dustymc** [comment]
@AJLinn you're not seeing it because....

<img width="185" alt="Screenshot 2024-11-12 at 13 02 23" src="https://github.com/user-attachments/assets/f1e0454e-4422-45a8-afb7-f4bf1ca896fa">

vs

<img width="348" alt="Screenshot 2024-11-12 at 13 03 18" src="https://github.com/user-attachments/assets/d51bb8b7-e109-4b21-a038-5976242b6501">

here: https://arctos.database.museum/Reports/reporter.cfm?action=edit&report_id=222

You can set that if you want to use it for a filter.

I got there (via the editor from a link above) with this:

<img width="592" alt="Screenshot 2024-11-12 at 13 04 18" src="https://github.com/user-attachments/assets/e971ac58-3bd6-4bf7-b395-3940cc00494c">

The report just picks a single semi-arbitrary image (vs. the download which includes them all), hopefully that's all explained in the comments (in ``<!--- comment --->`` format) in the report.

Let me know if I've avoided the question, but I think that'll get you going!

**Comment by AJLinn** [comment]
Hooray! Magic again. Thanks a million!

**Comment by AJLinn** [comment]
Oh wait... how to I now run that report?

**Comment by AJLinn** [comment]
NVM I just started clicking and figured it out... I think! 
Click "Create" at the top and then under "Clicky" hit "open"
Yes?

**Comment by AJLinn** [comment]
Thanks for this. When I first added the filtered results I only had "edit" and "copy" buttons available. Once I hit "Create" up top the "open" and "pdf" buttons appeared...
<img width="1559" alt="Screenshot 2024-11-12 at 12 25 42 PM" src="https://github.com/user-attachments/assets/9d229cc2-92af-44fd-906e-fd2b244523bf">

**Comment by AJLinn** [comment]
Going to close again! Thanks for the quick response to my cry for help!
