### ISSUE TITLE
Request - Add "valid" back to shipping addresses or start/end dates in the shipping picker

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#8061]
Help us understand your request (check below):
- [ ] search or data request (help with SQL or provide the specific fields you are trying to retrieve for your collection)
- [ ] add a new Github user to the Arctos Users team
- [ ] a new barcode series
- [ ] a new term for data entry or management 
- [ ] a change or new report or label
- [ ] update to an Agent (split, merge, or other type of change)
- [ ] bulkload changes (to Agents, Identifiers, etc that are not already available as a bulkloading tool)
- [ x] new feature or otherwise a good idea to make Arctos even better
- [ ] quarantine taxon name and suggested replacement (please supply links)
- [ ] other

**Describe what you're trying to do** 
Trying to figure out what shipping address to use for an agent without staring at start/end dates to make sure they're valid when picking addresses for the shipping tool. Picker pulls up agents and all shipping addresses regardless of valid or invalid with no further info. We used to have a little flag for addresses to use. Can we put that back? Or some auto thing that if today's date is past the end date, it darkens the shipping address or adds a invalid tag?

**Comment by campmlc** [comment]
I strongly support this.

**Comment by dustymc** [comment]
Next release will have more data, better organization, and fontawesomeness:


<img width="1025" alt="Screenshot 2024-08-30 at 14 45 30" src="https://github.com/user-attachments/assets/34f9e856-931b-4bef-8a86-4e2ad2c68f3d">

<img width="553" alt="Screenshot 2024-08-30 at 14 45 07" src="https://github.com/user-attachments/assets/c7ba12f1-1166-4fad-ac18-cea7a48cce40">

<img width="362" alt="Screenshot 2024-08-30 at 14 44 58" src="https://github.com/user-attachments/assets/6e8c6283-138c-4382-ace4-1fad5c90d151">
