### ISSUE TITLE
Request - Barcode series for bryansmclean

### ISSUE THREAD

**Issue by bryansmclean** [ArctosDB/arctos#8064]
Help us understand your request (check below):
- [ ] search or data request (help with SQL or provide the specific fields you are trying to retrieve for your collection)
- [ ] add a new Github user to the Arctos Users team
- [ X] a new barcode series
- [ ] a new term for data entry or management 
- [ ] a change or new report or label
- [ ] update to an Agent (split, merge, or other type of change)
- [ ] bulkload changes (to Agents, Identifiers, etc that are not already available as a bulkloading tool)
- [ ] new feature or otherwise a good idea to make Arctos even better
- [ ] quarantine taxon name and suggested replacement (please supply links)
- [ ] other

**Describe what you're trying to do** 

Create/claim container barcode series from a horribly ambiguously named set of stickers. The series and syntax is:

Container00001 - Container00500

We will do better next time, but these work for us right now. Are these available?

**Comment by dustymc** [comment]
Done.

**Comment by bryansmclean** [comment]
Getting an error when container bulkloading with the following two versions of these labels/barcodes


invalid barcode | freezer box | Container00251 | Container00251
-- | -- | -- | --



invalid barcode | freezer box | Container251 | Container251
-- | -- | -- | --

**Comment by dustymc** [comment]
institution_acronym is not.

https://arctos.database.museum/info/barcodeseries.cfm?barcode=Container00259 or https://arctos.database.museum/collection/UNCG:Mamm have what you need, UNCG.
