### ISSUE TITLE
Missing Doc link

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#8067]
**Describe the bug**
We are missing documentation for locality_attribute_value. See below

**To Reproduce**
Click on field heading for popup window
![Firefox_Screenshot_2024-08-30T17-07-05 127Z](https://github.com/user-attachments/assets/66ece0ea-e5a6-40ff-b392-e00963f48087)

**Solution:**
Provide a link to https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlocality_attribute_type#attribute_type
Suggested new wording:

Locality Attribute Values are controlled vocabulary in a Code Table. See [this link](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlocality_attribute_type#attribute_type) for details. Field will autocomplete if you start typing the desired value

**Comment by dustymc** [comment]
You can create/update those too, it's [inline documentation](https://arctos.database.museum/doc/field_documentation.cfm)

Done, but please confirm after the cache catches up in ~an hour.
