### ISSUE TITLE
[CONTACT] Account inactive

### ISSUE THREAD

**Issue by kat-sterner** [ArctosDB/arctos#8068]
Michelle reactivated my account on 8/12, but I just now got around to trying to log in and received the "account inactive or misconfigured" error. Could you please reactivate?

Thanks!

Kat

**Comment by mkoo** [comment]
Hi @kat-sterner I unlocked again-- please log in and close this issue!

**Comment by dustymc** [comment]
@kat-sterner I unlocked, you should have email from Arctos, please log in!

**Comment by kat-sterner** [comment]
Got it! Thanks!
