### ISSUE TITLE
Data stranded in bulkload tools

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#8070]
Due to my removal from edit access to the collections, the following data is stranded in various bulkload tools. Either the data will need to be downloaded and someone with collection access can re-load it, or eventually Dusty will remove it as stale data.

## Identifier Unloader

@campmlc @jldunnum @msbparasites all of the data here is related to cleanup of MSB identifiers and more information about that cleanup can be found in the github issue links given in the status column. 

## [Part Attribute Loader](https://arctos.database.museum/loaders/BulkloadSpecimenPartAttribute.cfm)

@Nicole-Ridgwell-NMMNHS there are some palatal modifiers

@happiah-madson @falco-rk there are some dangling part attributes where either the part or the record isn't found. These need research?

**Comment by campmlc** [comment]
@Jegelewicz I only see NMMNHS and OGL data - are there MSB records as well?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
@Jegelewicz I checked when you mentioned this in https://github.com/ArctosDB/arctos/issues/7764, but I wasn't able to see the NMMNHS palatal part attributes. At that time though I did do a part search for palatal and added the modifier manually where it was relevant. So our palatal data in the loader can be deleted by whoever is able to access it.

**Comment by campmlc** [comment]
@Nicole-Ridgwell-NMMNHS  here are the data I see:
[cf_temp_spec_part_attr_download.csv](https://github.com/user-attachments/files/16822067/cf_temp_spec_part_attr_download.csv)

**Comment by Jegelewicz** [comment]
So I guess none of you can see what is there because I no longer have access to your collections. Nice - that makes everything easy. I'll download and leave files for you here.

**Comment by Jegelewicz** [comment]
@campmlc MSB identifiers to unload

[cf_temp_unload_identifiers_download(2).csv](https://github.com/user-attachments/files/16823015/cf_temp_unload_identifiers_download.2.csv)

**Comment by Jegelewicz** [comment]
@Nicole-Ridgwell-NMMNHS part attributes

[cf_temp_spec_part_attr_download.csv](https://github.com/user-attachments/files/16823017/cf_temp_spec_part_attr_download.csv)

**Comment by Jegelewicz** [comment]
@happiah-madson @falco-rk part attributes

[cf_temp_spec_part_attr_download(1).csv](https://github.com/user-attachments/files/16823019/cf_temp_spec_part_attr_download.1.csv)

**Comment by Jegelewicz** [comment]
Take note that when you move some student's permissions and they have stuff in any of these YOU won't be able to see it.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
The NMMNH data can be deleted without loading as I have already dealt with these individually. Thanks for the heads up about permissions!
