### ISSUE TITLE
Arctos Down - 2024-08-31 5:52pm ADT

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#8072]
Please complete to the best of your ability.

## Unplanned Outage
 - 2024-08-31  5:52 pm Alaska daylight time
 - "An error has occurred"
 - This message has been logged as 410EC4A6-61D1-4048-97B2C7A7268F6B6D. 

## Communication before/during outage
- [x] Pin this issue
- [ ] Banner updated @mkoo
- [x] Email sent to AWG  
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @mkoo
- [ ] Email sent to AWG 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by campmlc** [comment]
I can't connect as of 7 am MDT. After a long time waiting, I get a message saying an error has occurred. C82C5401-1AD8-4BBE-97C6155B43A8A97D

**Comment by AJLinn** [comment]
Looks like we're back online. Fixed itself?
