### ISSUE TITLE
Help needed to generate a csv download of container contents for an entire freezer

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#8074]
# Tell us what you are trying to do 
I need a csv download of container contents for a freezer, in this case barcode DGR12751. For smaller containers I can use the object tracking Container Contents tool, but this tool yields a max of 20,000 records. All of my freezers hold at least twice and up to four times that number of objects. I am requesting @dustymc provide the same data as csv directly. https://arctos.database.museum/info/container_contents.cfm?container_id=14844247

As I will be needing to make similar requests on a regular basis for other freezers, it would be great if we could provide an option to request a csv file to be made available as an Async Request for all the Edit Container Tools, including See All Collection Objects and Container Contents and Empty Positions.

**Comment by dustymc** [comment]
[temp_cid14844247.zip](https://github.com/user-attachments/files/16850627/temp_cid14844247.zip)

**Comment by campmlc** [comment]
Fantastic, thank you! I will post the request for the async option in a separate issue.
