### ISSUE TITLE
Help needed in Arctos: Adding a source for a taxon

### ISSUE THREAD

**Issue by happiah-madson** [ArctosDB/arctos#8075]
I've been adding new taxa to Arctos with the superb guidance of @sharpphyl's video https://www.youtube.com/watch?v=9g3sEFqdzko. I've hit a bit of snag at this point because I need to add Ectocarpus siliculosus to WoRMS via Arctos, but it already exists in taxonomy (just with many different sources). Do I follow the instructions in the video and Arctos will magically add them? Or do I edit the taxon record that already exists and add a new classification?

# What are relevant pages in Arctos
Here is the current page for E. siliculosus: https://arctos.database.museum/name/Ectocarpus%20siliculosus

Thanks! @falco-rk

**Comment by dustymc** [comment]
What's the worms URL?

**Comment by happiah-madson** [comment]
https://www.marinespecies.org/aphia.php?p=taxdetails&id=145410

**Comment by dustymc** [comment]
https://handbook.arctosdb.org/how_to/How-To-Manage-Taxonomy-in-the-WoRMS-(via%20Arctos)-Source.html#add-a-worms-classification-to-an-existing-name

**Comment by happiah-madson** [comment]
Perfection, thank you! I should be able to handle it from here!

**Comment by happiah-madson** [comment]
Oh, you did it for me! Thank youuuuuuuu
