### ISSUE TITLE
Help needed - creating localities

### ISSUE THREAD

**Issue by bryansmclean** [ArctosDB/arctos#8081]
# Tell us what you are trying to do 

Create locality.

# What are relevant pages in Arctos
**Provide a link to or a description of the page where you need help.**

Where is this link?? Did this get removed and all localities have to be bulkloaded or entered from the record entry screen? The [current documentation](https://handbook.arctosdb.org/how_to/How-to-Create-a-Locality.html) describes what I *want*, but not what I can see in the Tools menu. Help please!

**Comment by bryansmclean** [comment]
Update: I've worked with @campmlc to create via a clone of existing locality. This totally works but is pretty roundabout and very hard to navigate as someone initially looking for a different tool.

**Comment by ewommack** [comment]
Hi @bryansmclean - just checking what is the work flow you are trying to accomplish? Creating the localities before cataloging?

> Still curious about the history of why the Create: Locality tool is no longer, or is so hard to find at present.

That is an interesting point. I think I always use clone an existing locality if I need to create a new locality (or let Arctos create it when I do data entry), but I can't remember why we got rid of the original tool. @mkoo @genevieve-anderegg -> any idea?

**Comment by dustymc** [comment]
It'd be useful to know what you're trying to do, I suspect you're on a frustrating path and your newly-created locality will be gone by the time you try to use it. https://handbook.arctosdb.org/documentation/locality.html#maintenance

**Comment by bryansmclean** [comment]
Hey everyone,

I'm trying to do exactly what the handbook refers to here about creating localities in advance of data entry. We have repeated sampling at the same sites and this decreases potential data entry errors. https://handbook.arctosdb.org/how_to/How-to-Create-a-Locality.html

_When collections are made from a single locality, data entry can be easier if the locality is created in advance._

I'm trying to figure out if the tool for _Create: Locality_ exists as pictured in the handbook here?

![Screenshot_20240904-184423.png](https://github.com/user-attachments/assets/0aecf3ce-93f0-49e5-89f6-2d7cd47d361e)

I know I used it before, but my only option now to create in advance is to clone an existing Locality. I want to create new ones that do not yet exist and not risk accidentally editing or deleting an existing one.

**Comment by dustymc** [comment]
Thanks @bryansmclean - in that case I'd recommend [Locality: Bulkload](https://arctos.database.museum/tools/bulkloadLocality.cfm) (and good names).

A GUI wouldn't be technically problematic (as long as names are involved), but I'm not sure there's much of a use case for one - Issue if you have that.

We need documentation-documentation: how-tos are **not** "documentation", they're just things that worked for some user for some purpose at some point in time.

I believe @mkoo has plans to clean that up anyway, and maybe @Nicole-Ridgwell-NMMNHS and/or @KatherineLAnderson (I think ya'll pre-bulk localities??) could be convinced to write some documentation on that.

**Comment by bryansmclean** [comment]
Ok sounds good. BUT please tell me I'm not going crazy.

The pictured interface _did_ exist in the past right?

![Screenshot_20240904-184423.png](https://github.com/user-attachments/assets/0b63d736-6592-4878-83af-8c6ed8e07de3)

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
It still exists, but there is no link to it on the tools page: https://arctos.database.museum/editLocality.cfm?action=newLocality

**Comment by mkoo** [comment]
Apologies for the late reply. 
Thanks for highlighting a needed documentation update-- I'm going remove that for now and you arent going crazy; we're just slow on updating that page!

3 scenarios for creating new localities:
1) need to create new ones to pre-exist for records--> Use the locality bulkloader with locality nicknames. You can upload a csv of one of course.
2) need to create a new one for a subset of records--> Use the clone locality button. This is the safest method _because_ it's easy to forgot components like h.g., etc
3) need to create localities with new records--> just add during data entry or bulkloading new records without pre-existing.

Open for help to describe the circumstances for these specific scenarios!

**Comment by bryansmclean** [comment]
Thanks everyone - I know it must be a huge task to keep the handbook updated and complete. And thanks @mkoo for the full list of create locality options.

I dont mean to belabor this - Ive personally created the localities that I needed in this instance - but it seems like there is a fundamental divide in what we think is most error-prone:

TO CLONE
> Use the clone locality button. This is the safest method because it's easy to forgot components like h.g., etc

OR NOT TO CLONE
> depending on what you are entering, it can be easy to accidentally forget to change some piece of data when cloning localities.

**Comment by mkoo** [comment]
closing as complete but there is a backburner issue for future dev https://github.com/ArctosDB/BackBurner/issues/1
