### ISSUE TITLE
agent bulkload

### ISSUE THREAD

**Issue by KatelinCross** [ArctosDB/arctos#8085]
I clicked on the bulk template for agents and received the error message that I was not authorized to use it.

**Comment by mkoo** [comment]
HI Katelin-- not a db error but mine-- you have access now!

**Comment by KatelinCross** [comment]
![Screenshot 2024-09-12 135303](https://github.com/user-attachments/assets/aa3bfba7-837b-4cb9-b203-8afa59ec13ad)

**Comment by KatelinCross** [comment]
Still no

**Comment by dustymc** [comment]
The form you are trying to access is reserved for code table admins. You need [Agent: Pre-Bulkload](https://arctos.database.museum/loaders/pre_bulkload_agents.cfm), then post here when your data happy in there.

**Comment by dustymc** [comment]
resolved?

**Comment by KatelinCross** [comment]
yes. thank you
