### ISSUE TITLE
Bug Report - Bulkload Parts-->Containers

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#8087]
I wasn't able to load the file into https://arctos.database.museum/loaders/BulkloadPartContainer.cfm?action=ld with the PARTID as downloaded from the parts table (with the full URL) - it kept giving me an error. So I removed all the URL stuff so it was just the PARTID number and then it loaded. However, after attempting to autoload, it comes back with a 'bad partID' error. Is this my error and how do I fix it?

File with URLs: 
[Parts to tags_2024-09-05_withURL.csv](https://github.com/user-attachments/files/16900240/Parts.to.tags_2024-09-05_withURL.csv)

File with just partID number:
[Parts to tags_2024-09-05.csv](https://github.com/user-attachments/files/16900243/Parts.to.tags_2024-09-05.csv)

**Comment by dustymc** [comment]
Should be patched, the first file (URIs) should load.

**Comment by acdoll** [comment]
That did it! Thanks @dustymc !!
