### ISSUE TITLE
publication annotation

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#8088]
Help us understand your request (check below):
- [ ] search or data request (help with SQL or provide the specific fields you are trying to retrieve for your collection)
- [ ] add a new Github user to the Arctos Users team
- [ ] a new barcode series
- [ ] a new term for data entry or management 
- [ ] a change or new report or label
- [ ] update to an Agent (split, merge, or other type of change)
- [ ] bulkload changes (to Agents, Identifiers, etc that are not already available as a bulkloading tool)
- [ ] new feature or otherwise a good idea to make Arctos even better
- [ ] quarantine taxon name and suggested replacement (please supply links)
- [x] other

**Describe what you're trying to do** 

See https://arctos.database.museum/info/reviewAnnotation.cfm?ANNOTATION_GROUP_ID=117066

An Arctos user left an annotation but I can't decipher it.

Publications can be edited.

The publication is https://arctos.database.museum/publication/10008779

The publication title is 

[Barker, D. G. (1992). Variation, infraspecific relationships, and biogeography of the ridgenose rattlesnake, Crotalus willardi. In Biology of the Pitvipers (J. A. Campbell and E. D. Brodie, Jr., Eds.), pp. 89–106. Selva, Tyler, TX.](https://arctos.database.museum/publication/10008779)

The suggested DOI is https://doi.org/10.1111/j.1365-2699.2011.02578.x

That DOI resolves to 

Deep intra-island divergence of a montane forest endemic: phylogeography of the Puerto Rican frog Eleutherodactylus portoricensis (Anura: Eleutherodactylidae)

@jtgiermakowski @campmlc have granted access to the user

**Comment by campmlc** [comment]
I was working with the student on this, and the annotation was submitted inadvertently by the student. The issue is resolved.

**Comment by campmlc** [comment]
Quick follow up question - this is a chapter in a book with a doi https://doi.org/10.1093/sysbio/42.4.596
What is our protocol for dealing with these situations? Should we add the book doi, and specify the chapter and pages? Or will that break something if more than one publication entry is linked to the same doi?
Should we create the book publication and doi and relate this chapter to it somehow?
