### ISSUE TITLE
Help needed in Arctos: UAM Art taxonomy

### ISSUE THREAD

**Issue by DellaCHall** [ArctosDB/arctos#8089]
# Tell us what you are trying to do 
I would like to view (or download?) all of the UAM Art taxonomy. I attempted to access this information through [this form](https://arctos.database.museum/taxonomy.cfm) using Source: UAMArt, but it timed out with an error.

# What are relevant pages in Arctos
[(https://arctos.database.museum/taxonomy.cfm)](https://arctos.database.museum/taxonomy.cfm)

**Comment by dustymc** [comment]
All Arctos taxonomy is available for download at https://arctos.database.museum/cache/gn_merge.tgz

**Comment by DellaCHall** [comment]
Thank you. However, I'm not seeing the data that I would expect to see in the resulting 3 CSV files. For example "ceramic ware" should be in there, and I am not finding it.

**Comment by dustymc** [comment]
Oh dang, right you are.

I'm filtering for ``taxon_name.name_type='Linnean'`` which I think isn't defensive anyway - eg [Iron](https://arctos.database.museum/name/Iron) might be [Linnean](https://arctos.database.museum/name/Iron#CatalogueofLife), [cultural](https://arctos.database.museum/name/Iron#NomenclatureviaArctos), or [mineral](https://arctos.database.museum/name/Iron#HeysCIMviaArctos) depending only on who got there first. I'll drop that and rebuild.

@dimus hopefully this won't melt anything for you.

**Comment by dustymc** [comment]
everything has been rebuilt

**Comment by DellaCHall** [comment]
Sorry, but this doesn't resolve the issue for me, because I cannot open that large of a CSV file on my computer. Any recommendations for how to access the just data I am trying to view (which I think is pretty small!), without crashing my computer?
