### ISSUE TITLE
reports are a mess

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#809]
Figure out some way to get rid of junk reports. Possibility:

1) add date_last_accessed to cf_report_sql, triggerify it
2) when date_last_accessed > {something - 6 months?} send email and rename the report to something obvious - "PENDINGDELETE{reportname}" maybe.
3) when date_last_accessed > {something else - 9 months?} delete the report

(A rename seems necessary to prevent a "get email, check unused/unwanted report thereby resetting countdown, wait 6 months, get email, ...." cycle.)

**Comment by dustymc** [comment]
Tighter plan:

Send all email to all collection contacts (same as authority notifications).

Send email for templates >30d old with no handler. Include the templates as attachments. Things that get ignored for 30 days seem to get ignored forever.

Delete unused templates at 40 days. Include a follow-up email with the now-nuked templates attached one more time.

No clear way to implement that for our legacy of old garbage, so I'm elevating this to critical so I don't forget to patch the next phase of code in....

**Comment by campmlc** [comment]
Sounds like a good idea.

**Comment by dustymc** [comment]
Completely revised plan:

The above gets complicated as code; I'm not sure it's going to work (because of the order in which "triggering events" may happen) or be understandable (=predictable), and it relies on a failure-prone process (eg, users with no collection contact emails may be left in the dark, an email server hiccup could lead to nasty surprises, etc.). So Plan C:

1) Auto-delete templates with no handlers when they're >24 hours old. No warnings, no emails, just POOF! Add accompanying documentation to the form itself. Maybe make it big and red. (Unhandled templates can't DO anything; it's not clear why they exist, and they're not developed on Arctos - re-loading the ones that did have some intended purpose should not be difficult or cumbersome.)

(We could email the templates as attachments to collection contacts or something, but see above: I can't guarantee that the emails will go out, I certainly can't guarantee that the proper person will receive them, I think it would be a confusing process that doesn't add much while distracting users from more-important messages. Totally up for better ideas though.)

2a) For templates with handlers, send emails after every 6 months (??) of no use. Encourage users to delete the handler (which will cause the template to be auto-deleted IF no other report uses it) for abandoned experiments, etc. Arctos will never delete a potentially-usable report (eg, one with a handler) because I'm pretty sure that we have things which ARE used but very infrequently.

2b) Alternatively, perhaps add a "this is no longer experimental, we use this thing" flag BUT that sets us up for 1) create report, 2) use it for a while, 3) create new/better report, stop using the old one, 4) stumble around the old one forever because at one point it was marked as used.

**Comment by dustymc** [comment]
for post-7.3 release
