### ISSUE TITLE
Request - report for USGS data

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#8091]
Help us understand your request (check below):
- [ ] search or data request (help with SQL or provide the specific fields you are trying to retrieve for your collection)
- [ ] a change or new report or label

**Describe what you're trying to do** 
I am summarizing from #8042 -- generate a report or csv for USGS or other agency based on data in a Project.

Example: https://arctos.database.museum/search.cfm?customoidoper=LIST&project_id=10002364&sp=Dunnum_USGS

Fields: use_license_url | collection_object_id | guid | scientific_name | country | state_prov | spec_locality | verbatim_date | dec_lat | dec_long | coordinateuncertaintyinmeters | sex | parts | age_class | othercatalognumbers | phylorder | family | county | nk | identified_by | preparators | remark | accn_number | began_date | minimum_elevation | orig_elev_units | collectors | datum | entered_by | ear_from_notch | hind_foot_with_claw | tail_length | total_length | weight | collector_number | genbank | preparator_number | reproductive_data

SQL: 
```
create table temp_dups as select usgs,count(*) c from temp_usgs group by usgs having count(*) > 1;
```
Because agency has dup numbering based on taxonomy

For further discussion:
- is the request for a SQL for managers to rerun? A report to print from a project? I dont know if a profile would provide the flexiblity and customization that is actually being requested here.
- users should let us know the priority level here!

**Comment by dustymc** [comment]
Relevant information in https://github.com/ArctosDB/arctos/issues/8042#issuecomment-2311170764. This becomes unnecessary when identifiers are migrated; tabling as a legacy of stuck cleanup.
