### ISSUE TITLE
Request - download or report parsed by identifier

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#8093]
Adding to this thread because todays issue is basically the same type of problem/request. Spent last week at the AMNH and they are eager to have a download of our shared data to update their database and sort out some data problems they have. The MSB worked on a decade long collaborative project with AMNH in the 1980s and 90s in Bolivia. AMNH didn't have a tissue collection at that time so all tissues came to MSB. Thus we have large series of specimens cataloged here which are tissue only and correspond to skins/skels/fluids held at AMNH. These all have NK numbers, MSB numbers and AMNH numbers. I'd like to have a parsed file with MSB guid, AMNH institutional catalog number, NK number, collector name and number, preparator name and number, higher geography, specific locality, georeference data, sex, date. 
Bottom line is this type of request is going to keep coming up so I really need the ability to use one of my profiles to download records and then parse out all the identifiers into their own columns. Thanks

_Originally posted by @jldunnum in https://github.com/ArctosDB/arctos/issues/8042#issuecomment-2338542907_

**Comment by dustymc** [comment]
This has been possible for some time, here's how.

Search, choose tools/identifiers

<img width="430" alt="Screenshot 2024-09-19 at 15 46 40" src="https://github.com/user-attachments/assets/20f16c97-c090-458c-90fa-648484476e42">

Select the issuing agent(s) of interest, click filter

<img width="614" alt="Screenshot 2024-09-19 at 15 48 32" src="https://github.com/user-attachments/assets/ac6598fa-0568-4490-9312-e995c1341a50">

click:



<img width="286" alt="Screenshot 2024-09-19 at 15 49 05" src="https://github.com/user-attachments/assets/090e8e80-6620-4322-95bf-d6c3ab7d9142">



get data parsed out into columns as requested:



<img width="1509" alt="Screenshot 2024-09-19 at 16 04 07" src="https://github.com/user-attachments/assets/2bb91764-0ecc-4995-857f-c109cb7770f4">
