### ISSUE TITLE
Request - add USGS-issued identifiers to flat/cache

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#8095]
Help us understand your request (check below):

- [ ] new feature or otherwise a good idea to make Arctos even better

**Describe what you're trying to do** 

## background

I'm filing this on behalf of what I think @jldunnum is trying to do, someone please kill this if I'm confused. https://github.com/ArctosDB/arctos/issues/8042 was a specific request, I provided a bigger-picture solution in https://github.com/ArctosDB/arctos/issues/8042#issuecomment-2311170764, maybe this will provide some clarity and solve a problem.

## goal

Cache values for identifiers issued by https://arctos.database.museum/agent/7831 in flat so that the data are available in search results, and wherever else flat is available

## long-term cost
* there are a finite number of columns available, but we're nowhere near that limit
* this would involve a small amount of redundant storage which will have minimal impacts on backups and etc.
* this would increase the CPU needed to maintain the cache, but I believe by negligible amounts

## development costs

minimal, I could have this out ~today.

## alternative

Performance of "modern" identifiers is very good, I think I can actually do this dynamically sufficient for "us" to use, but I would not want to make that publicly available. (Anyone using the API likely won't have any trouble extracting this from the JSON.) I propose we **do not** do this, at least until we need to mitigate the aforementioned costs (which I suspect is never) - unless ``all the identifiers into their own columns`` from https://github.com/ArctosDB/arctos/issues/8093 is actually being precise, as above I do have a finite ability to cache things and there's clearly no limit on who can issue identifiers. I think the actual scope of this is likely dozens and this should proceed as I've requested, but again someone please shut this down if I've confused myself somewhere along the way.

## Other Considerations

Perhaps this would be more useful if the identifiers were first cleaned and then controlled. These data DO NOT look to me like they should probably be in the same bucket, some examples:

* 3585
* 74 ADt 18
* 79APa82b
* BS/FC 0001
*  BS/FC 0450 BS/FC 0454
* BS/FC1637
*  CLE18-033
*  DRO 425447
*  DRO-437754
*  USGS-58643
*  USGS uncataloged

**Comment by campmlc** [comment]
This is part of a much bigger issue -operators and users need to be able to isolate into separate columns and download specific identifier types for the purposes of data cleanup and curation as well as discovery. We used to be able to do so by selecting a particular identifier as a preferred identifier in our user profiles, which would allow this ID type to preferentially separate out rather than being concatentated in strings in search results and downloads. This functionality still exists in some forms, such as loan item review, but not others, such as search results, and the format is inconsistent. We need to have the issued by and the ID type and ID value displayed and downloaded in separate columns across the board. In cases where this or any requested data are not cached in flat, can we request an async download rather than a specific report? I need to use this functionality daily, and requesting reports really doesn't meet the needs of collection managers. 
If this isn't possible under the current mixed model, please explain what changes would be necessary to make it possible, and how that could be standardized to meet user needs as described across all tools.

**Comment by dustymc** [comment]
@campmlc I'm having trouble putting your comments in the context of what I proposed.

If something is inconsistent, please file an issue with specifics.

If this isn't useful, please suggest we close it (but it did seem to satisfy the issue that lead to here, so possibly you could elaborate on why it's no longer useful, if that is what you're saying).

If this would be useful, that'd be nice to know too.

I believe the critical pieces of the big picture are all wearing a wildfire label, if that's the question.

????????????????????????????????

**Comment by campmlc** [comment]
I'm just trying to understand the proposal, which appears to be a solution for a single identifier type/agent. My question is that given we need this functionality for all identifier types/agents, is this the appropriate solution?

**Comment by dustymc** [comment]
>understand the proposal,

Add a column labelled 'usgs' and carrying data like ``BS/FC 0001`` to ``FLAT``

>appears to be a solution for a single identifier type/agent.

I think so.

>all identifier types/agents

See "alternative" in my original comment. We had ~dozens of "important types" (many of which clearly were not, so this looks even easier than the legacy data might suggest it should be). If making those data more available is about the scope of the immediate need then this still feels like a good idea. If we do have to preemptively address all possibilities then this cannot scale that far and should be killed.

**Comment by campmlc** [comment]
Can you please explain your alternative? I'm having trouble understanding. We do need to be able to extend this solution to other identifiers/agents, ideally not one isssue at a time. This particular identifier/agent download is only needed once a year or so, but others are needed frequently. Assuming we move everything to the new identifier = agent model, will we then be able to select particular identifer issued by agents/ID types/ID values via the interface and have those isolated into separate columns as needed? 
I don't want to derail this particular issue, but it is a symptom of a much broader need that adding a single identifier/agent to flat does not address.
@jldunnum @mkoo

**Comment by jldunnum** [comment]
I second @campmlc here. The transition to the new model for identifiers/agents has not been smooth in our estimation and we have lost functionality we previously had. So yes, development of some structure to have identiers parsed individually is critical. I understand the identifer data are not clean and this may not be trivial but this is a very basic collection management tool which we need.

**Comment by dustymc** [comment]
>some structure to have identiers parsed individually

That's what I'm trying to do (and did in some detail in the previously-linked demo), but this can close if its not useful.

**Comment by mkoo** [comment]
Thx, Dusty for keeping this focused.
I just want to add that this is compatible for flat because USGS is a federal agency/agent that is used broadly by collections.

**Comment by dustymc** [comment]
>used broadly

Yes, this still seems appropriate to for "agency/agent that is used broadly" and the costs still seem worth paying, please reopen if you (anyone!) has a use for that.

**Comment by campmlc** [comment]
This was marked as completed. Does that mean it was completed, or just that the discussion is closed?  @jldunnum

**Comment by dustymc** [comment]
>marked as completed

You are trying to read meaning into something automatically added by github. The issue was just closed; the audience for whom this was intended expressed a lack of interest, that was explained, there was at that point no purpose in this, so it was closed. If this can become functional or serve some purpose then please explain how when re-opening, if it cannot then please do not re-open.

**Comment by jldunnum** [comment]
I think the confusion here is simply whether or not we now have the ability to parse various identifiers into their own columns when needed. Recent needs including USGS and AMNH. We want this to become functional but it is not clear if that is happening or not.

**Comment by dustymc** [comment]
@jldunnum that's what I was attempting here on your behalf, but it's not my need so I probably confused myself. Possibly best to open a new (no need to drag my confusion into any requests) issue (meeting request, email, whatever) describing what you need.
