### ISSUE TITLE
Request - Make filtered flat exportable

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#8096]
- [x] data access!

**Describe what you're trying to do** 
The immediate need is for the UCDavis Data science students to create Tableau visualizations for Arctos data (more on that later!) and with over 5 M records we can do a lot! The filtered_flat table is already public accessible so make it easy for people to use it in projects. Could live at an api endpoint or elsewhere-- you tell us -- and pretty please for version for exploring data options now.

(ps. a note that this would probably make any api request obsolete)

**Comment by dustymc** [comment]
Fabulous idea from my perspective.

Some technical limitations, you're copied.

Here's a small sample, I don't think there's any sensitive in filtered_flat but if so we should clean it up and make this happen.

[temp_plz_no_melt.csv.zip](https://github.com/user-attachments/files/16937676/temp_plz_no_melt.csv.zip)

**Comment by mkoo** [comment]
I think it was your idea-- so yes, fabulous! thx for sample

**Comment by dustymc** [comment]
There's a copy of filtered_flat in https://web.corral.tacc.utexas.edu/arctos/data/, still working on a way to get that a bit more script-able.

**Comment by mkoo** [comment]
This works! Close when you want but definitely will do for now-- this may be a solid alternative to api for the data dashboard at least

**Comment by mkoo** [comment]
implemented-- new use cases will need a new issue- closing
