### ISSUE TITLE
loan barcodes

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#810]
1) Add loan barcode to the loan item csv download

2) Add tool to allow bulk upload of barcodes to add to loan, rather than one barcode at a time

**Comment by dustymc** [comment]
Removed "active development" (and updated documentation) - bulk loan items by barcode has existed for years, I'm not sure what this is asking for

**Comment by campmlc** [comment]
Review Items for loan MSB:Mamm 2016.003.Mamm (type: consumable)

**Download (csv**) - non-data loans only!   -------> NEED TO ADD BARCODE TO CSV DOWNLOAD; MLC
View in SpecimenResults (includes part and data loan items)

This loan contains only parts; you can manage everything here.

MLC: Please add the part barcode or (source part barcode for subsamples) to the loan items csv download.

**Comment by dustymc** [comment]
Done (for post-7.3 release) as "NEAREST_BARCODE" via https://github.com/ArctosDB/DDL/blob/master/functions/getNearestPartBarcode.sql. Documentation/vocabulary suggestions appreciated.
