### ISSUE TITLE
Request - Bulkload event attributes by event_ID

### ISSUE THREAD

**Issue by WaigePilson** [ArctosDB/arctos#8104]
Help us understand your request (check below):
- [ ] search or data request (help with SQL or provide the specific fields you are trying to retrieve for your collection)
- [ ] add a new Github user to the Arctos Users team
- [ ] a new barcode series
- [ ] a new term for data entry or management 
- [ ] a change or new report or label
- [ ] update to an Agent (split, merge, or other type of change)
- [ ] bulkload changes (to Agents, Identifiers, etc that are not already available as a bulkloading tool)
- [X] new feature or otherwise a good idea to make Arctos even better
- [ ] quarantine taxon name and suggested replacement (please supply links)
- [ ] other

**Describe what you're trying to do**
The current Bulkload Event Attributes Tool (https://arctos.database.museum/tools/BulkloadEventAttrs.cfm?action=ld) requires you to add attributes by event_name. However, most of my collecting events recently added do not have event_names. I would like to be able to add event attributes by the unique collecting_event_id instead.

I may be missing somewhere where this is possible already, or maybe this is a fundamental feature in Arctos which I am misunderstanding. But if I understand correctly, the collecting_event_id is a unique identifier for each collecting event, so it seems like we should be able to use this as the id to add attributes to?

**Comment by dustymc** [comment]
collecting_event_id is not sufficiently stable for this purpose.

https://handbook.arctosdb.org/documentation/collecting-event.html#maintenance

**Comment by campmlc** [comment]
We need an automated way of minting stable IDs for collecting events, then. What is the alternative in this case - going through a bunch of events and naming them first? Not a viable workflow.

**Comment by WaigePilson** [comment]
@dustymc is there a way to bulk edit collecting events then, since event_name is not automatically generated during data entry? Or how do I add event_name to all the collecting events I generated during data entry??

I would second @campmlc point, I can update this request to "create stable event_ID"  instead. I don't know the technical challenges to implementing this, but long-term I strongly agree we need automatically generated stable event identifiers to make Arctos more useable.

**Comment by dustymc** [comment]
>way to bulk edit 

Sure, find them, click on the tools, let me know details if something's missing.

> automatically generated 

That would result in a lot of duplicates-except-in-name.

>"create stable event_ID"

That's a job for a human. Naming is a "I'm gonig to manage this, go away duplicate-merging scripts" sort of commitment, not something I can script. (Unless someone wants to propose a different model...)

**Comment by WaigePilson** [comment]
> Sure, find them, click on the tools, let me know details if something's missing.

Not sure what tools you're referring to???
I'm attaching a csv which lists the event_ID and the attribute I want to add. How would I do this? I have the locality_name, I could even pull the cat_num of each specimen associated with the event. Of course, I could search for each event individually, edit, add the attribute. But there are 705 events I am trying to edit here...

[eventattributes_eventdocumentation_9.11.24.csv](https://github.com/user-attachments/files/16983673/eventattributes_eventdocumentation_9.11.24.csv)

**Comment by dustymc** [comment]
<img width="295" alt="Screenshot 2024-09-12 at 11 01 06" src="https://github.com/user-attachments/assets/d8246328-c179-4bb1-9ea8-c16a16d137a6">

splat-c

<img width="157" alt="Screenshot 2024-09-12 at 11 01 20" src="https://github.com/user-attachments/assets/802219fa-ffa9-49c4-9500-6af9a0b7ee15">

splat-v
splat-c

<img width="202" alt="Screenshot 2024-09-12 at 11 01 52" src="https://github.com/user-attachments/assets/4bc15977-d532-40ff-8aa1-c2ac1dc26ce3">

splat-v


<img width="181" alt="Screenshot 2024-09-12 at 11 01 57" src="https://github.com/user-attachments/assets/5c6e4d56-7cb8-47a2-9070-27e9e5889d19">

<img width="186" alt="Screenshot 2024-09-12 at 11 02 05" src="https://github.com/user-attachments/assets/ab38ba35-0471-42ae-87ab-5884b286c95d">


<img width="907" alt="Screenshot 2024-09-12 at 11 04 03" src="https://github.com/user-attachments/assets/df38273a-e2fd-4bc8-8ad2-6b36d931d7c4">

you can now prefix the ID (those of them which hadn't been merged by the time I did this, anyway...) with ``temp_`` and use that as a handle to add attributes.

When you're done - assuming you don't want to commit to long-term management of these things - you can just do the same procedure to un-name, and they'll re-join the herd for automated maintenance.

If you use them in something for which you're a contact, Arctos will send you reminder notifications.

**Comment by WaigePilson** [comment]
AHA! Thank you for this information, there is no way I would have thought about going about it this way. I will draft a user guide for our staff/students for this process, as I imagine this will come up again in the future.

**Comment by dustymc** [comment]
>AHA!

Sorry, I assume everything I write is intuitive. (And it is! To me...sometimes....)

>user guide

Please post it as a how-to! (Happy to help with the techy-bits of that, send me anything!)

**Comment by dustymc** [comment]
Done?
