### ISSUE TITLE
Help needed in Arctos Operator Role for locality search download flat attributes

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#8106]
# Tell us what you are trying to do 

I have a graduate student who will be doing a research project analyzing some of our locality data in GIS. He needs access to "download flat attributes" in locality search. I've made him an operator and given him coldfusion user and access to our collection, but he does not have access to that download option. What additional permission do I need to give him?

# What are relevant pages in Arctos
[**Provide a link to or a description of the page where you need help.**](https://arctos.database.museum/place.cfm?sch=locality)

**Comment by dustymc** [comment]
manage_locality

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks!
