### ISSUE TITLE
Help needed in Arctos

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#8107]
Curatorial Search Request -
Request for @dustymc to run updated freezer inventory for the following freezer barcodes using the SQL for #6680; basically I need to generate the same report as Container Contents (CSV) but this will yield more than the 20,000 allowable results. Trying to avoid melting Arctos.
Please run as separate files for the following freezer barcodes:
DGR12751
DGR12749

**Comment by dustymc** [comment]
[tmp.zip](https://github.com/user-attachments/files/16985127/tmp.zip)

**Comment by campmlc** [comment]
Thank you!
