### ISSUE TITLE
barcode series request

### ISSUE THREAD

**Issue by asemerdj** [ArctosDB/arctos#8109]
Hi there,
Can I request CPH[A-Z0-9] for rooms and H[A-Z0-9] for containers? Also I don't think I currently have the permissions needed to add/edit containers. 

Thank you!
Alyssa

**Comment by dustymc** [comment]
@asemerdj do you want a character count limit (or fixed number of, or whatever) on either or both of those? Your current SQL allows H followed by 84 billion 3s - you probably won't want to use more than 4 or 5, and limiting your claim will help prevent some kinds of errors (eg student typing in random things).

**Comment by dustymc** [comment]
Done, and you now have scary container rights, log out and in to get them (then don't break anything!). Docs are 

http://handbook.arctosdb.org/documentation/container.html 

[How to Start Object Tracking in Arctos](http://handbook.arctosdb.org/how_to/How-to-Start-Object-Tracking.html)

 [How To Create and Edit Containers](https://handbook.arctosdb.org/how_to/How-to-Create-and-Edit-Containers.html)

**Comment by dustymc** [comment]
Done.
