### ISSUE TITLE
Publication citation not appearing in record

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#8113]
**Describe the bug**

I just created a publication and added a citation. However, it is not showing up in the associated specimen record even when refreshing the cache, or when I run a generic search on "all types" (publication).

Publication: https://arctos.database.museum/Citation.cfm?publication_id=10012262

Catalog record: https://arctos.database.museum/guid/UCM:Herp:48857

**Comment by dustymc** [comment]
<img width="364" alt="Screenshot 2024-09-16 at 08 27 13" src="https://github.com/user-attachments/assets/d356e942-42ae-40ce-b006-2e3ef7a9479a">

https://arctos.database.museum/info/flat_status.cfm

>even when refreshing the cache,

Possibly the button isn't clear; it's possible only to ***request*** a refresh, not to ***force*** one.
