### ISSUE TITLE
Request - make "Review Loan Items" screen modifiable

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#8115]
Help us understand your request (check below):
- [ ] search or data request (help with SQL or provide the specific fields you are trying to retrieve for your collection)
- [ ] add a new Github user to the Arctos Users team
- [ ] a new barcode series
- [ ] a new term for data entry or management 
- [ ] a change or new report or label
- [ ] update to an Agent (split, merge, or other type of change)
- [ ] bulkload changes (to Agents, Identifiers, etc that are not already available as a bulkloading tool)
- [X] new feature or otherwise a good idea to make Arctos even better
- [ ] quarantine taxon name and suggested replacement (please supply links)
- [ ] other

**Describe what you're trying to do** 
In order to remove an item from a loan, I search for the loan number, then click on "Review Items"
Because of the way UAM:EH data shows up on the review loan items page, I have to scroll over several screens-worth of pages to get to the "Remove" and "Disposition" columns. Because you have to make sure the disposition is "in collection" first before you can remove the item from the loan, it's **very** hard for me to keep my eyes on the proper line when I've just scrolled across the Arctic Polar Desert to get from the GUID column to the Disposition one. This often forces me to manually place something on my screen, like a PostIt, in order to not lose track of the proper line.

It would be **awesome** if there was a way for me to select/unselect which columns show up on the Review Loan Items page so I could unclick the columns that I don't need but might be important data for others (e.g., parts) that take up half of the Arctic Polar Desert... and keep the columns that do mean something, like GUID and Identification.

- [Sample loan item review page data here](https://arctos.database.museum/loanItemReview.cfm?transaction_id=21143315)
- Screenshots (sorry, this is going to be obnoxious, just to emphasize my point. Each of these screenshots is most of my 27" iMac window wide, it's even more obnoxious on my 13" laptop in my lab!)
<img width="1869" alt="Screenshot 2024-09-16 at 5 14 11 PM" src="https://github.com/user-attachments/assets/bf1b8448-f91d-4580-a4d9-a418ef5e72e7">
<img width="1869" alt="Screenshot 2024-09-16 at 5 14 24 PM" src="https://github.com/user-attachments/assets/7acc41b9-5275-4248-a39b-3b78114b6adf">
<img width="1869" alt="Screenshot 2024-09-16 at 5 14 36 PM" src="https://github.com/user-attachments/assets/f676ce6d-f31a-4a24-bf64-7c459fb0e3a5">
<img width="1869" alt="Screenshot 2024-09-16 at 5 14 49 PM" src="https://github.com/user-attachments/assets/d3593422-d310-44e2-b38b-94847e0b372c">
<img width="1869" alt="Screenshot 2024-09-16 at 5 14 57 PM" src="https://github.com/user-attachments/assets/8c6f8763-1b61-4171-89ed-1fab80e9ba96">

Priority: medium to low as it's definitely a wish list item BUT I'd love to hear from others who are struggling with the current layout.

**Comment by campmlc** [comment]
I agree that this is disfunctional. Having the parts field so obnoxiously long seems a major part of the problem. Any way to make that wrap or truncate or allow view all or simplify options? Also, why have the blank UAM:University of Alaska Museum column taking up space? Perhaps if we could reorder the columns, Parts could be moved last, and Add/remove/change disposition fields could be moved to the left of parts. Alternatively, Fix the GUID column so it stays visible on all pages.  I also work on a laptop and have the same issue with scrolling.

**Comment by dustymc** [comment]
@AJLinn I'd like to propose to open a dev issue to basically wiggle the wires in layout-land without changing anything substantial. Should be quick and easy and I suspect it'll address your issue, if not then this can be re-opened for major surgery. Reasonable?

**Comment by AJLinn** [comment]
If the layout involves wrapping text in the parts field (where our part attribute condition report will continue to create a hella-long single line layouts) and/or bringing the disposition and remove from loan buttons to the first screen, that sounds great!

**Comment by dustymc** [comment]
Dev-->https://github.com/ArctosDB/dev/issues/58
