### ISSUE TITLE
Problems with part bulkloader

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#812]
Trying to use the parts bulkloader to add barcodes to existing parts, using "1" to use existing parts if such exist and put them into new containers and using change_container_type to convert the barcode from label to cryovial. Not sure what this error means. One potential problem is that I do not know the condition and disposition of the existing parts for all 100+ specimens I'm trying to update, so perhaps it is getting hung up on the conflict between the specimen record and the updated part disposition and condition? If so, I don't know an easy route to extract this info from the parts download.

Also, couldn't file this issue from the error message screen because it would not accept the transcript of the red text for confirmation. Tried a couple of different codes.
![screenshot 2016-02-08 16 28 59](https://cloud.githubusercontent.com/assets/14808196/12903130/8603cbcc-ce82-11e5-8fe2-e4b74b991fe0.png)
[New barcodes for 2016.007 loan.xlsx](https://github.com/ArctosDB/arctos/files/122370/New.barcodes.for.2016.007.loan.xlsx)

**Comment by dustymc** [comment]
problem with data, please close invalid issues
