### ISSUE TITLE
Part attribute "container volume" invalid [CONTACT]

### ISSUE THREAD

**Issue by kderieg322079** [ArctosDB/arctos#8121]
I have a student entering data and we keep getting an error any time she tries to enter the part attribute "container volume". I have it as a carried field set up in a custom data entry form and it has worked for ~200 records but now is is failing. The specific error is: **2024-9-17T12:57:32: FAIL: part_1_attribute_2 is invalid.: {"message":"part_1_attribute_2 is invalid.","status":"fail"}**

Screenshot of the part and the error:

![image](https://github.com/user-attachments/assets/c48caeb9-6de5-418b-8f4e-b894cbbffcf6)

Is this attribute something I need to add in collection settings? I know how to edit the collection's accepted parts, but is there a way to do that for part attributes as well?

**Comment by dustymc** [comment]
This should have been done as part of https://github.com/ArctosDB/arctos/issues/7791.

Should be fixed now, but it might take everything ~an hour to catch up.

Tentatively closing....
