### ISSUE TITLE
Help needed  - SQL need for Fish labels

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#8123]
# Tell us what you are trying to do 
Making labels for MVZ:Fish and need a new variable.

We need a code snippet for the report MVZ Fish Jar (https://arctos.database.museum/Reports/reporter.cfm?action=edit&report_id=31) to show the specific preservation attribute for a record.

Specifically we need a new variable for part attribute Preservation (example value= "ethanol, 100%") and the resultant variable should be reversed so it says "100% ethanol". We could do this as replacements since it would only be a few values of "ethanol, 70%" replaced with "70% ethanol" etc

I hope I was clear! (hit me up if not)

**Comment by dustymc** [comment]
done

**Comment by mkoo** [comment]
sweet! thx
