### ISSUE TITLE
error feedback: can't edit remark without getting error regarding verbatim collector, which was not edited

### ISSUE THREAD

**Issue by catherpes** [ArctosDB/arctos#8125]
MSB:Bird:51587. I'm editing remarks for this specimen record and I get an error about a verbatim agent that already is in the record?

If it was good enough to get into the database when it was bulkloaded, why isn't it good enough now? 

 
Error below:
<html><body>

ERROR_ID | 25A85A55-A615-4BDA-A8BDEF27228EF439
-- | --
ERROR_TYPE | SQL
ERROR_MESSAGE | ERROR: Method is required and should explain the verbatim agent`s role. Example: collector.   Where: PL/pgSQL function trigger_fct_tr_attributes_ct_bui() line 43 at RAISE
ERROR_DETAIL |  
ERROR_SQL | UPDATE attributes SET 							attribute_type='verbatim agent', 							DETERMINED_BY_AGENT_ID = null, 							ATTRIBUTE_VALUE='Richard Webster', 							ATTRIBUTE_UNITS= null, 							ATTRIBUTE_REMARK='second collector', 							DETERMINED_DATE=null, 							DETERMINATION_METHOD=null 						WHERE 							attribute_id=23387650

</body>
</html>

**Comment by dustymc** [comment]
Something went wrong with https://github.com/ArctosDB/arctos/issues/4871, I've now done what we said we'd do, updates should work, closing.
