### ISSUE TITLE
Help wanted- can't add Arctos login username to Agent profile

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#8127]
**Describe the bug**
Trying to set up operator access for agent https://arctos.database.museum/edit_agent.cfm?agent_id=21356080
He says he created an Arctos login: Ariel35.
But there is no option to add a username or login in his Agent profile. What am I missing?

**To Reproduce**
1. Go to https://arctos.database.museum/edit_agent.cfm?agent_id=21356080
2. Click on "create Attribute"
3. Scroll down to "name" options
4. Do not see any option for login name type

**Screenshots**
![Screenshot 2024-09-20 16 03 07](https://github.com/user-attachments/assets/23b91f30-ddb2-45d7-97bf-acdc737c3f2e)

**Comment by mkoo** [comment]
The streamlined security minded routine is to verify the user name from the operators side.
So first make the agent (done) and user registers account with email.
Then  supervisor goes to Operator: Manage tool
Search on the username, if present, hit edit
Invite as Operator where it will validate username and you can add/link the Agent name (popup search window)

This needs probably needs to be added to the handbook (hence my steps outlined above!) Let me know if I missed a step
Thanks

**Comment by mkoo** [comment]
just checked: https://handbook.arctosdb.org/how_to/How-to-Create-your-Arctos-Team-Users-and-Operators.html
handbook is uptodate (I forgot I did this already)-- could use screenshots though!

**Comment by dustymc** [comment]
>handbook is uptodate

As is [documentation](https://handbook.arctosdb.org/documentation/users.html).

**Comment by campmlc** [comment]
So after failing to add login name, I did go to manage operator and search his username. It didn't exist, so does that mean he failed to actually create the account? Is there a delay?

**Comment by mkoo** [comment]
No delay and I found your user's name.
Try again?
MK

**Comment by campmlc** [comment]
Seems his username is the problem, not acceptable for operator. Not exactly clear from the error messages. But I've asked him to create new one according to documentation, will see if that works.

**Comment by mkoo** [comment]
yep you're right -- I didnt see the period at the end!
only letters and numbers for operators. Close this issue?
