### ISSUE TITLE
Help needed in Arctos: WoRMS taxonomy!

### ISSUE THREAD

**Issue by happiah-madson** [ArctosDB/arctos#8130]
So I was looking through our collections taxonomy and discovered that some fish have class Actinopterygii and some fish have class Actinopteri and if I look at WoRMS these fish should really be class Teleostei. Because taxonomy is shared, I'm hesitant to force a WoRMS via Arctos refresh (also, how would I do this for forcing "all fish"). But clicking refresh for every taxa that is a Teleost seems...not efficient?

# What are relevant pages in Arctos
https://arctos.database.museum/name/Secutor%20insidiator#WoRMSviaArctos

This is an example of a species that we have where WoRMS says teleostei and WoRMS via Arctos says Actinopteri and I want to update WoRMS via Arctos but I don't want to mess things up.

@falco-rk @dustymc @sharpphyl @mkoo @genevieve-anderegg

**Comment by dustymc** [comment]
Anyone using service-sources data has to be prepared for those data to follow the service at any time, wherever weird place it might go. That should be (kinda isn't) perfectly clear from the [definition](https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxonomy_source#worms__via_arctos_).

>refresh for every taxa

[WoRMS: Request Refresh](https://arctos.database.museum/tools/requestWormsRefresh.cfm)

>all fish

We're, like, **all** fish, man! https://arctos.database.museum/name/Homo%20sapiens#OpenTreeofLife

**Comment by happiah-madson** [comment]
Okay, let's pretend I'm very dense (...). Do I type "Teleostei" in the Request Refresh field?

**Comment by dustymc** [comment]
>very dense

Sorry, that's mine!

I'm hoping @sharpphyl  - who's actually used this thing - will show up and clarify. In theory: Yea, you'd feed the form something like subclass + Teleostei and it'll flag everything to be refreshed (which might take a couple days). In reality: I'm not sure, possibly that'll just melt something important....

Once things are better understood, I'd be happy to update the form to include any documentation that might be supplied here.

**Comment by happiah-madson** [comment]
Great, I will wait for the wisdom of @sharpphyl

**Comment by genevieve-anderegg** [comment]
> Okay, let's pretend I'm very dense (...). Do I type "Teleostei" in the Request Refresh field?

Yep! Prepare for it to take awhile to work through everything (hours-days). 

> Anyone using service-sources data has to be prepared for those data to follow the service at any time, wherever weird place it might go. That should be (kinda isn't) perfectly clear from the [definition](https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxonomy_source#worms__via_arctos_).

Yes, so if we have specimens where the taxonomy hasn't been updated for us yet, it will change it for us too. But, we don't have any fish records that use the Worms via Arctos source in our collection, and like Dusty is saying, it's a benefit of using the shared source BUT that also means we have to keep pretty on top of our taxonomy. Thanks for the heads up, go ahead!

> I'm hoping @sharpphyl - who's actually used this thing - will show up and clarify. 

I hope I'm a suitable stand in ;)

**Comment by happiah-madson** [comment]
<img width="1837" alt="Screen Shot 2024-09-23 at 1 31 26 PM" src="https://github.com/user-attachments/assets/6fa7d769-c20d-48d6-bfc5-8d7ad45663f5">

I feel I am doing something horribly incorrectly. (Do I realize that updating all chordata is insane? yes. But all of my other queries were returning 0 records.) Help?

**Comment by dustymc** [comment]
Oh thanks @genevieve-anderegg didn't realize you use this too.

>insane

The DB agrees! (That might work sometimes - depending on what else is going on at the moment - so there's probably no sort of 'this rank' or 'that many records' limit guidance.)

This worked for me:

<img width="389" alt="Screenshot 2024-09-23 at 11 23 15" src="https://github.com/user-attachments/assets/77e505fb-ee75-4b89-ab11-a43201541b27">

and so did the next click

<img width="201" alt="Screenshot 2024-09-23 at 11 25 07" src="https://github.com/user-attachments/assets/63cb0340-78a2-4072-833c-2744b691bc7d">

you can check in with...

<img width="192" alt="Screenshot 2024-09-23 at 11 25 18" src="https://github.com/user-attachments/assets/7b219d86-caca-41bb-b133-b986c859d89c">

https://arctos.database.museum/tools/requestWormsRefresh.cfm?action=checkStatus


<img width="179" alt="Screenshot 2024-09-23 at 11 26 31" src="https://github.com/user-attachments/assets/14ac877e-962a-4c6e-bc4d-05e92b701a50">

and hopefully i didn't just plug the toobs with something you don't care about....

**Comment by happiah-madson** [comment]
Okay, so the problem I was clearly having was ascribing Teleostei to the wrong rank (I put it in as a class b/c WoRMS says that it's a class now....). How do I know which rank to give it? (How did you know to use subclass?)

**Comment by dustymc** [comment]
The query is using current Arctos data

https://arctos.database.museum/name/Secutor%20insidiator#WoRMSviaArctos

<img width="147" alt="Screenshot 2024-09-23 at 11 38 02" src="https://github.com/user-attachments/assets/5bbfcffc-083e-4b45-a741-e16d4dcc012d">

**Comment by happiah-madson** [comment]
Oooooooo v good. Helpful. Thank you.

**Comment by happiah-madson** [comment]
I continue to struggle. @dustymc your update did things! I can see that some records have been updated and have the Class Teleostei. However, there are still things that are Actinopterygii. For example:

<img width="1190" alt="Screen Shot 2024-09-25 at 1 51 11 PM" src="https://github.com/user-attachments/assets/904bd3f9-8956-488e-992d-3a63c001e067">

which according to WoRMS should be Teleostei (https://www.marinespecies.org/aphia.php?p=taxdetails&id=127426).
My understanding is that to do this I should go to https://arctos.database.museum/tools/requestWormsRefresh.cfm and put in:

term type (exact case-sensitive): class
term (case insensitive, wildcard is %): Actinopterygii

But when I do that, I get this:

<img width="1414" alt="Screen Shot 2024-09-25 at 1 54 23 PM" src="https://github.com/user-attachments/assets/f857386c-515a-4153-902a-0e53bb23b102">

Is this just because Actinopterygii is B I G? or is there something that I am doing wrong?

**Comment by dustymc** [comment]
> just because Actinopterygii is B I G?

Yup.

1. Maybe try back later, possible things are just busy (but probably not in this case)
2. Chop it up somehow (I see this one doesn't have subclass so that's not handy)
3. Ping me and I'll figure it out


Am I missing anything @genevieve-anderegg @sharpphyl ?

**Comment by happiah-madson** [comment]
If you're not missing anything, can I assume this counts as 
> Ping me and I'll figure it out

**Comment by happiah-madson** [comment]
> This has happened to us too, I try and then chop it up like you suggested. Hard if the next level of taxonomy has lot of different terms

😭😭😭😭😭😭😭😭😭😭😭😭😭

**Comment by dustymc** [comment]
>assume this counts

Sure!

INSERT 0 75243

a bunch of those probably got refreshed a couple days ago, might be useful to mention that (whatever it is - order of operations??) in the documentation if possible

**Comment by sharpphyl** [comment]
I think Genna has been a more-than-adequate stand in.  Currently Arctos is churning away on your request and I would think it could be a week or more before it's done - depending on what else is going on - and until it's done churning, you'll have inconsistencies in the classifications.  In our case, we manually refreshed the few that hadn't gotten to the front of the queue yet if we needed them.

<img width="284" alt="Screenshot 2024-09-30 at 8 18 03 PM" src="https://github.com/user-attachments/assets/cd6a35fd-d08e-40f3-9ebb-eb31f0b87ad0">

You will want to ask it to try again on anything that fails.

Dusty can tell us if there's an actual limit that triggers errors, but I unusually was able to stay around 10,000 - 25,000 entries with mollusca but that may not work for your fish.

As more people use WoRMS for more phyla, this may become an issue if we all refresh at the same time.  Mollusca is one of the largest with over 250,000 names and I've been trying to refresh all the classes we have each year.  Not all of them are in Arctos, so we're refreshing way fewer than that.  Right now, it's first come, first serve, so have at it!
