### ISSUE TITLE
error feedback

### ISSUE THREAD

**Issue by amgunderson** [ArctosDB/arctos#8133]
I can't create a shipment in a loan.

ERROR_ID | 6DE25DD1-2E96-43D2-80A015FAAA35284B
-- | --
ERROR_TYPE | expression
ERROR_MESSAGE | can't cast empty string to a number value
ERROR_DETAIL |  

<br class="Apple-interchange-newline">

I literally only filled in the required fields after trying to include ship date and tracking number. I keep getting the same nonsensical error.

**Comment by dustymc** [comment]
A pre-error screenshot would be handy, but I think you've not properly selected one of the addresses, possibly because your browser is confused from a previous error. Try shift-reload to clear things out.
