### ISSUE TITLE
Please rewrite SQL - ROOM020 contents

### ISSUE THREAD

**Issue by camwebb** [ArctosDB/arctos#8141]
@dustymc, please help rewrite this query to be small enough to run. Purpose: to find all contents of `ROOM020` and their freezer. Expected results: 156,000 lines. Need for SQL: the CSV 'contents' download for ROOM020 via the Find Container app is too big and will not complete. For @megulbranson. (Cf. [#338](https://github.com/ArctosDB/internal/issues/338))

``` sql
SELECT guid, accession,
  JSONB_PATH_QUERY(part::jsonb, '$.part_name')::text AS name,
  JSONB_PATH_QUERY(part::jsonb, '$.part_barcode')::text AS bc,
  REGEXP_REPLACE(JSONB_PATH_QUERY(part::jsonb, '$.container_path')::text,
    '.*rm 20 \(room\):\[ ([^ ]+) \].*','\1') AS freezer,
  REGEXP_REPLACE(JSONB_PATH_QUERY(part::jsonb, '$.container_path')::text,
    '.*\(([^)]+)\)"$', '\1') AS container
FROM (
  SELECT guid, accession,
    JSONB_PATH_QUERY(partdetail::jsonb,
      '$[*] ? (@.container_path like_regex " ROOM20 ")') AS part
  FROM flat
  WHERE guid_prefix ~ '^UAM'
) AS P
```

**Comment by dustymc** [comment]
>156,000 lines.

There are 181723 containers in room20, I'm not sure that query is doing what you want, and I can't quite guess what you want from it. 

Here's a small sample of the "normal" container contents pull:

[temp_room20_sample.csv](https://github.com/user-attachments/files/17196059/temp_room20_sample.csv)

That's starting with the room and walking down the hierarchy, and will include containers that aren't linked to catalog records. Let me know if you want the full dump in that format, or what you do want if it's not that.

>small enough to run

My default query for the room created a table of 181723 rows in a ~half-second,  the problem is moving the results of that around the VM - I don't have the resources for that, but I can easily move things around outside of the UI.

**Comment by camwebb** [comment]
> small sample of the "normal" container contents pull

Yes, this is what we would like, but we can only get 20,000 lines via the CSV-only download. Thanks for offering to side-supply the table, but we really need a way for Mallory to get this herself. 

The SQL as given is what we need:

| guid | accession | name | bc  | freezer | container |
| ---  | ---       | ---  | --- | ---     |---        |
| UAM:Mamm:134600 | 2015.052.Mamm | "liver" | "365239" | LN2FRZR1 | cryovial |
| UAM:Mamm:134600 | 2015.052.Mamm | "kidney" | "365238" | LN2FRZR1 | cryovial |
| UAM:Mamm:134600 | 2015.052.Mamm | "heart" | "365237" | LN2FRZR1 | cryovial |

Is there any way to get this info other than via a request to you? Could the SQL be made fast enough? What prevents an easy `container` lookup is variable number of edges between the freezer and smallest container.

**Comment by campmlc** [comment]
I support this request in general as the limit of 20,000 lines for the CSV of container contents also impacts my collection - I can't even get the contents of a single freezer using the CSV download in the main interface. I'd also like the opportunity to get this information myself without having to file a request each tim, and apparently so do other collections. This is limiting functionality. See #8107 and #6680.
An async request option?

**Comment by camwebb** [comment]
>> Could the SQL be made fast enough?

> :camera: ???

:confused: I'm not asking about "[Your] default query for the room..." but about this particular SQL. When previously run this result set was just 11MB. Surely that can be moved around the VM?

>> The SQL as given is what we need:

> I can't work from that, I need to know what data you need.

:confused: Doesn't the SQL tell one exactly what data is needed? But to spell it out: for each smallest container in Room 20, we require: guid, accession of the contained collection object, part name of the object, barcode, freezer the container is in, and container type.

Thanks

**Comment by dustymc** [comment]
>SQL tell one exactly what data is needed?

That's not been my experience, but here's something.

>barcode

I'll guess you mean of the container holding the part.

From that I guessed you DO NOT mean 'for each smallest container in Room 20' but rather '...that contains a part,' and then I extended that to 'part-container is in a container.'

>freezer

I'm guessing you want parts in room20 whether they're in a freezer or not, but I can change the filter if necessary.

>container type

same guess.

[some_of_room20.zip](https://github.com/user-attachments/files/17211610/some_of_room20.zip)

**Comment by camwebb** [comment]
The file looks perfect. Thanks! @megulbranson please see if this is what you wanted.

To spell it out more clearly, for confirmation:

for each container (C) which directly holds part (P) of a collection object (O), _and_ which is ultimately within a freezer (F), please return:

 * the (F) freezer barcode,
 * the (C) container's barcode,
 * the (C) container's type,
 * The (P) part's type ("part name"),
 * the GUID & accession of the collection object (O)

**Comment by megulbranson** [comment]
Thanks @camwebb and @dustymc! From a quick look this seems to be exactly what I need.
