### ISSUE TITLE
Request - dump of `flat` for UAM:Herb, etc.

### ISSUE THREAD

**Issue by camwebb** [ArctosDB/arctos#8142]
Following on from [#338](https://github.com/ArctosDB/internal/issues/338), I'd be grateful for a _non-filtered_, all-field dump of `flat` for UAM:Herb and UAMb:Herb. As discussed in the call, you could use my TACC file server space: `/home/camwebb`. Gzip-compressed would great.

(Backburner?) If this could be scripted to refresh ~once a week, that would be super!

Thanks

**Comment by dustymc** [comment]
I can't see your home dir, but I think I should be able to see a subdir with appropriate permissions.

**Comment by camwebb** [comment]
Try `/home/camwebb/trf`

**Comment by dustymc** [comment]
cannot access /home/camwebb/trf: Permission denied

**Comment by camwebb** [comment]
please try again: (`/home/camwebb` is now `drwxr-xr-x`, `/home/camwebb/trf` is `drwxrwxrwx`)

**Comment by camwebb** [comment]
Actually, since this is wide-open for anyone (on TACC) to read, could you please encrypt to me with my [PGP key](http://camwebb.info/doc/cw.asc)?

**Comment by dustymc** [comment]
Too late, you should see a file.

If that worked I'll send another (pending below).

I'm not going to install pgp on the VM I'm using, we can talk to TACC about some other arrangement if necessary.

**Comment by camwebb** [comment]
Ah, this is how to do it (never had to solve this before - fun!)... Permissions:

 * `/home/camwebb` `drwx-----x` (0701)
 * `/home/camwebb/trf` `drwx----wx` (0703)

You can write a file to `/home/camwebb/trf` but no one other than me can see the list of contents of that directory (or its parent). Other users _can also read_ the new file, but only if they can guess the name. Should be secure enough.

The dump file looks good. Thanks.

**Comment by dustymc** [comment]
*nix file permissions are so fun....

```
[dustylee@gs-2 uwbm]$ echo 'contents' > ~camwebb/trf/afile
-bash: /home/camwebb/trf/afile: Permission denied
```

**Comment by camwebb** [comment]
Ah... I think that's because we are in the same group (Arctos?): G-816249. Perms now:

```
/home/camwebb      drwx--x--- (0710)
/home/camwebb/trf  drwx-wx--- (0730)
```

`echo 'contents' > /home/camwebb/trf/afile` should now work.

Also... I just realized we get `ssh` access to data.tacc - thought before it was `sftp` only. And I see that `gnupg` is already there. So:

```
$ curl -O http://camwebb.info/doc/cw.asc
$ gpg --import cw.asc
$ gpg -e -r 'Cam Webb' data_dump.csv.gz
$ cp  data_dump.csv.gz.gpg /home/camwebb/trf
```

This should now be a secure, simple solution for Arctos users with TACC accounts.

**Comment by dustymc** [comment]
I won't venture any guesses about *nix permissions, especially at TACC (where everything is like 19 semi-overlapping mappings....). We can definitely loop Chris into an email if necessary, just let me know if you want me to start that.

I can write, but I can also read.

```

[dustylee@gs-2 uwbm]$ echo 'contents' > ~camwebb/trf/afile
[dustylee@gs-2 uwbm]$ cat ~camwebb/trf/afile
contents
```

>sftp only

I'm not sure it's possible to allow one without the other?

FWIW I'm not doing this from data, I just happened to have a tab open to play with permissions - I'll just push the dumps to your dir from another VM. 

You should have another data dump.

**Comment by camwebb** [comment]
> I can write, but I can also read.

I think... that's as it should be: you own the file, and you know the path and filename. So you can read it, copy it and stat it. `$ ls -l /home/camwebb/trf/afile` should give: `-rw-r--r--    1 dustylee G-816249        9 Oct  2 17:37 afile`. But you should not be able to see what's in the directory. I.e., `ls /home/camwebb/trf` should give you a permission error. 

If you name the file, e.g., `uam_herb_flat_2024-10-02_bc04eacd-e717-4a64-999c-2b1a0e33d4bf.csv.gz` then it is effectively unfindable and secure. 

The UAMb:Herb flat file looks good. Feel free to close this issue. And thanks.
