### ISSUE TITLE
Request - ctformat authority

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#8144]
Help us understand your request (check below):
- [ ] search or data request (help with SQL or provide the specific fields you are trying to retrieve for your collection)
- [ ] add a new Github user to the Arctos Users team
- [ ] a new barcode series
- [ ] a new term for data entry or management 
- [ ] a change or new report or label
- [ ] update to an Agent (split, merge, or other type of change)
- [ ] bulkload changes (to Agents, Identifiers, etc that are not already available as a bulkloading tool)
- [ ] new feature or otherwise a good idea to make Arctos even better
- [ ] quarantine taxon name and suggested replacement (please supply links)
- [x] other

**Describe what you're trying to do** 

From https://github.com/ArctosDB/arctos/issues/8143

>Since the creation of the attribute, the link to the source has been updated. https://www.archives.gov/research/catalog/lcdrg/authority_lists/formatlist is no longer valid, the information now resides at https://www.archives.gov/research/catalog/lcdrg/authoritylists/format.

I'm opening this here because I'm questioning the source; is there something that won't arbitrarily change, perhaps even something with some sort of definitions to accompany the terms?

Whatever the answer, the CT needs updated before it can be used; this is a blocker.

**Comment by wellerjes** [comment]
No longer needed; see https://github.com/ArctosDB/arctos/issues/8143#issuecomment-2394500111
