### ISSUE TITLE
Year-old data removed from table Bulkload Encumbrances

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#8147]
8 year-old records have been removed from Bulkload Encumbrances (table: cf_temp_obj_encumbrance).

Data:

[temp_cache.cf_temp_obj_encumbrance_2024_10_02.csv](https://github.com/user-attachments/files/17231642/temp_cache.cf_temp_obj_encumbrance_2024_10_02.csv)

Usernames:

* camwebb (8 records)

Users have access to these collections:

* UAM:Alg
* UAMb:Herb
* UAM:Herb
* UAM:HerbLib
* UAM:Myco

Collection Contacts

* @StefanieBond
* @camwebb

**Comment by camwebb** [comment]
Thanks - all records had been successfully deleted anyway.
