### ISSUE TITLE
clone loans and specimen events into new record

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#815]
We need a way to clone loan information along with other transactions with Clone This Record; Ditto for multiple specimen events, Currently only first specimen event carries over.

**Comment by dustymc** [comment]
<img width="1168" alt="clonebutton" src="https://cloud.githubusercontent.com/assets/5720791/12955359/78572d92-cfd7-11e5-972f-27997bcb4cd7.png">

**Comment by campmlc** [comment]
I should clarify - the clone feature provided does not allow a record in one collection to be cloned into another collection and transfer the transactions. I cannot convert a DGR record to a MSB record and pull the loan information.Perhaps this is something no one else would use - but it is critical for MSB. Another example - MSB Para record being cloned to split the lot, so that parts are moved to a new record. We would need the transactions moved across as well.

I assume the same issue holds for specimen events.

**Comment by campmlc** [comment]
In the MSB Para case, I see that we can use the existing tool. I will give it a try. But my previous attempts were failures because of the cross-collection issue.
