### ISSUE TITLE
Year-old data removed from table Geography Lookup

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#8154]
40 year-old records have been removed from Geography Lookup (table: cf_temp_geog_lookup).

Data:
[temp_cache.cf_temp_geog_lookup_2024_10_02.csv](https://github.com/user-attachments/files/17231887/temp_cache.cf_temp_geog_lookup_2024_10_02.csv)

Usernames:

* mill8849 (40 records)

Users have access to these collections:

* MMNH:Mamm

Collection Contacts

* @adhornsby

**Comment by adhornsby** [comment]
@dustymc Were these higher geographies that mill8849 was attempting to load, or just look up to see if they existed?  Never used this tool before so I'm not sure of its function.

**Comment by dustymc** [comment]
just look up to see if they exist

**Comment by adhornsby** [comment]
OK!  Good to discard.
