### ISSUE TITLE
Arctos Down - 2 Oct 2024 1028 MT

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#8158]
Please complete to the best of your ability.

## Unplanned Outage
 - Date and time (**please add time zone from which you are reporting**) outage discovered: 2 Oct 2024, 1028 MT
 - Describe the outage (Arctos down or only some part not working?): This site can’t be reached
arctos.database.museum took too long to respond.
Try:

Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
ERR_TIMED_OUT

Is Arctos down? I can't get on via Chrome or Safari or FireFox. I'm trying to pull the latest collection and record numbers from the info page, but can't get to the database. 

## Communication before/during outage
- [x] Pin this issue
- [ ] Banner updated @mkoo
- [ ] Email sent to AWG  
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @mkoo
- [ ] Email sent to AWG 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by dustymc** [comment]
Arctos is not down. What is your IP address?

**Comment by ewommack** [comment]
192.168.8.85

**Comment by dustymc** [comment]
That is not an external IP.

**Comment by ewommack** [comment]
That's what I get when I check my computer, with router 192.168.8.1. 

That is the info I can give you, and I can access everything else but Arctos.

**Comment by dustymc** [comment]
https://www.google.com/search?q=what+is+my+ip+address should lead to an answer.

**Comment by ewommack** [comment]
Thanks Dusty, here is what I get: [67.43.213.66](https://whatismyipaddress.com/ip/67.43.213.66)

**Comment by ewommack** [comment]
Thanks Dusty! I got the renewal request for TACC in, and block if it becomes a problem again.
