### ISSUE TITLE
Help needed in Arctos - Adding materials to Tag in Reporter

### ISSUE THREAD

**Issue by Kmullineaux** [ArctosDB/arctos#8163]
# Tell us what you are trying to do 
I am attempting to add the record attribute 'materials' and its value to NHSM_Arc_label report so that I can see the object materials on the tag. 

# What are relevant pages in Arctos
**Provide a link to or a description of the page where you need help.**

NHSM_Arc_label in Report Editor

**Comment by dustymc** [comment]
If you just want the value:

``flat.materials``

should do it. Let me know if you need something else.

**Comment by Kmullineaux** [comment]
Thank you! Much appreciated!
