### ISSUE TITLE
Taxon name loader and classification loader - no progress in days

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#8165]
https://arctos.database.museum/loaders/BulkloadTaxonomy.cfm
https://arctos.database.museum/tools/BulkloadClassification.cfm

I set these to load on October 2 and here on Oct 4 they remain unloaded.

I see there's lots of stuff in the component loaders https://arctos.database.museum/info/component_loader_status.cfm

but examining that page gives me little useful information on when to expect mine to load.

One improvement to this page would be in the 'contact' column to show the date that the load was initiated. This would tell us the backlog waittimes...

the runtime column seems meaningless since there are lots of zeros in there. If the runtime is zero minutes why are those data not loaded?

**Comment by dustymc** [comment]
>show the date that the load was initiated

I don't think that would be very meaningful, things hang around for various times for various reasons.

>runtime column seems meaningless


No?!

This thing:

<img width="509" alt="Screenshot 2024-10-04 at 12 57 26" src="https://github.com/user-attachments/assets/48073ad8-8809-4038-8d96-03dd10db41e6">



will start in 399 minutes and then take 1 minute to complete, for example.

>If the runtime is zero minutes why are those data not loaded?

If runtime is zero then there's nothing to do. The thing at the bottom of the above screenshot has 0 autoload records, it can load 10 per minute, that'll take zero minutes to complete.


>they remain unloaded.

There are no priority comments at the moment, sort your stuff to the top......


OH - sorry, the sorter was stuck, maybe things will make more sense now.

Use this column to drag the rows into the order you want:


<img width="108" alt="Screenshot 2024-10-04 at 13 03 40" src="https://github.com/user-attachments/assets/31c9f682-35b9-462d-91fc-e01a4175f470">

Then (optionally) leave a remark (eg, 'I NEED bulk edit container NOW!!' or "no hurry on parts") and click the button....
<img width="618" alt="Screenshot 2024-10-04 at 13 04 11" src="https://github.com/user-attachments/assets/d3cc6de3-3fab-4cbe-9e04-d48613ab7028">

... and you're next in line.

**Comment by campmlc** [comment]
Just to clarify, if there are tasks above yours that have zero records in process/auto load, those tasks should not impede loading of any active tasks lower down, correct? So we can leave our tasks lower in the sort order as long as the ones above are a few records or none. If so, then there is no need for anyone to put a very large time consuming task ahead of small ones as long as the smaller tasks remain empty/ at zero. Please confirm.

**Comment by DerekSikes** [comment]
Thanks. I can sort but there is no remarks field nor a 'save run order' button for me. This is the top of the page
![Screenshot 2024-10-04 at 2 13 49 PM](https://github.com/user-attachments/assets/5a327ebc-c320-4521-b48a-9c94948a76ed)

and this is the bottom
![Screenshot 2024-10-04 at 2 13 46 PM](https://github.com/user-attachments/assets/89958ee8-efe1-4e36-b4eb-e33a63ed53d2)

**Comment by dustymc** [comment]
<img width="281" alt="Screenshot 2024-10-04 at 15 18 45" src="https://github.com/user-attachments/assets/3a64b2a4-c000-4f73-82a9-386283737a86">

That's heavily throttled, excessive clicking leads to some problems. The tools will be back an hour after the change (and very open to better ideas for how to handle that, as long as it doesn't involve more than about one sort per hour).
