### ISSUE TITLE
Request - part preservation - percent

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#8167]
**Describe what you're trying to do** 

From https://github.com/ArctosDB/arctos/issues/4367, there's a broad consensus (https://docs.google.com/document/d/1SGBZQTGdTMr11kpOUQQ4lfgjRRLMj5E3jeHVHtQBrMw/edit#heading=h.q3pk226foene) that we can be more consistent and do a better job of avoiding characters that break various UIs and confuse humans. Here's a hopefully-simple start to that process, preservation values which contain ``%``

https://docs.google.com/spreadsheets/d/1Qzchh3_YnJjq51BgvTScpOLZaboBV-KbpjZQPD1L3dk/edit?usp=sharing

Column ``new_preservation`` is my proposed update. Most are just missing a comma (I think that was the consensus), but there are also two "combo values" that I tried to make a bit more list-like and consistent, and I spelled out (possible correctly) a ''w/." I'm very open to any sort of change here, we can remove anything that's even slightly controversial, whatever.

This is a good opportunity to update the documentation if something could be made better. (I fixed a link, but haven't changed anything meaningful.)

TISSUE_FG can also be updated if necessary, docs here: https://handbook.arctosdb.org/documentation/parts.html#preservation

Let me know if you want edit access, or anyone should be able to comment. (Just don't change ``PART_PRESERVATION``, it's my path back to data.)

I think this was all sufficiently discussed and can just be done, assuming I didn't get lost anywhere.

@ebraker @gracz-UNL @happiah-madson @falco-rk @Nicole-Ridgwell-NMMNHS @wellerjes @adhornsby @jebrad (and apologies to whoever I missed!) how to proceed?

**Comment by happiah-madson** [comment]
I think the human-readable part is great. Though I do suspect that @RJSS8 is who needs to weigh in on the soy broth language.

I've put a couple comments in the doc about language consistencies? I'm happy to fully flesh them out for every term, but I wanted to make sure other people were in agreement about language looking like, "a solution that consists of X% constituent A and Y% of constituent B" before making the edits that I think are right.

**Comment by falco-rk** [comment]
I am happy with those changes

**Comment by campmlc** [comment]
I am also happy with these changes. One slight suggestion would be to replace "tryptic soy broth with 15% glycerol" with "tryptic soy broth 15% glycerol" for consistency, but that isn't a deal breaker.

**Comment by dustymc** [comment]
>"tryptic soy broth 15% glycerol"

done

**Comment by dustymc** [comment]
done
