### ISSUE TITLE
[external CONTACT] API Model?

### ISSUE THREAD

**Issue by pccollins2** [ArctosDB/arctos#8178]
Hi Dusty & Michelle,

My team and I are running into issues trying to implement a global search feature on our webpage. How can we view the API model itself (or an API map) to see the detailed contents of items in each collection (i.e. Paleo, Ethno, etc.). One specific issue we are having is that we are not sure how to call Paleontology Common Names. Sorry if this is a dumb question, but any help is appreciated

**Comment by dustymc** [comment]
@pccollins2 the API is self-documenting, I believe accessing that is even provided as an example from the overview. I'll need specifics (examples are always useful) to answer anything that's not answered by the API itself.

**Comment by dbwelchel** [comment]
Hi Dusty and Michelle, 

I am helping with this and I am trying to gain familiarity with how to do API calls properly and view data to help us with our webpage. An example of the trouble is with using the URL to list code tables-  
![api calls](https://github.com/user-attachments/assets/42d438de-ed2e-40e0-b587-a01a0d85ff2c)
We have an API key issued, however when we use it in the URL to make the API call, we get a message saying that the API key cannot be used from the current IP address, even though we have tried from computers that should have access. I appreciate any help possible.

**Comment by dustymc** [comment]
@jcabbott72 has an email with key/IP pairings. I think you're trying to use the production key from your dev IP range, but I'm guessing unless you share the request, response, and environment.
