### ISSUE TITLE
manage_publications access?

### ISSUE THREAD

**Issue by connermuseum** [ArctosDB/arctos#8179]
Could I get the manage_publications role?

As an aside, the user_roles table says that manage_publications allows someone to create publications and projects. I don't have the role and I can create projects but not publications.

**Comment by jessicatir** [comment]
Sorry, logged into the wrong account.

**Comment by dustymc** [comment]
Please review

https://handbook.arctosdb.org/documentation/publications.html
https://handbook.arctosdb.org/documentation/projects.html
https://handbook.arctosdb.org/documentation/sharing-data-and-resources.html
https://www.youtube.com/watch?v=aLCC-SI1-RI

then log out/in and you'll have new superpowers.

**Comment by jessicatir** [comment]
Thank you!

Could I also get manage_media?

**Comment by dustymc** [comment]
Please read:

https://handbook.arctosdb.org/documentation/media.html
https://handbook.arctosdb.org/how_to/How-to-Create-Media-Images.html
https://handbook.arctosdb.org/documentation/sharing-data-and-resources.html

then log out and in
