### ISSUE TITLE
Help needed in Arctos - Event Creation/Edit Role

### ISSUE THREAD

**Issue by Kmullineaux** [ArctosDB/arctos#8184]
# Tell us what you are trying to do 
I want to edit a collecting event created by a previous staff member, but I am presented with an error message stating I do not have access to that resource when I try. I am the collections manager for NHSM and need this ability for data entry. 

# What are relevant pages in Arctos
**Provide a link to or a description of the page where you need help.**

ERROR_ID | 311103CF-5DAD-4ABE-95EE1200F6DF9EF8
-- | --
ERROR_TYPE | unauthorized
ERROR_MESSAGE | not authorized
ERROR_DETAIL | You are not authorized to access this form.

**Comment by dustymc** [comment]
Locality is a shared resources; please be cautious about updating shared data, please ask first if you have any questions.

Please read first:

https://handbook.arctosdb.org/documentation/sharing-data-and-resources.html
https://handbook.arctosdb.org/documentation/locality.html
https://handbook.arctosdb.org/how_to/How-to-understand-the-Arctos-Locality-Model.html
https://handbook.arctosdb.org/how_to/How-to-Create-a-Locality.html
https://handbook.arctosdb.org/how_to/How-to-Create-a-New-Collecting-Event-for-a-Locality.html
https://arctosdb.org/learn/tutorial-blitz/#locality

Then log out/in and you'll have manage_locality.

**Comment by Kmullineaux** [comment]
Thank you for your help!
