### ISSUE TITLE
Bulk Remove Dimensions

### ISSUE THREAD

**Issue by LitsaWoo** [ArctosDB/arctos#8193]
I created a box with the dimensions 11.6 W x 7 H x 35.5 D and with 250 rows, 1 column, oriented vertically
The box holds glassine envelopes of dimensions 10.9 W x 6.4 H x 0.1 D
When attempting to scan the envelopes into the positions Arctos will not allow it and states that the parent does not fit into the container. Why is this occurring even though the envelope dimensions are smaller than the box? Should I switch some of the dimensions around?

If there's no way to make dimensions work properly is there a way to bulk remove the dimensions? I already attempted to bulkload the barcodes for the glassine envelopes without dimensions but it did not remove the dimensions from the previous bulkload.

![Arctos Error](https://github.com/user-attachments/assets/7d138dc0-1f3e-4ccc-922f-b1c587f2f046)

**Comment by campmlc** [comment]
@LitsaWoo did you create the positions in the box? That is the next step after creating the box itself, even though you specified the number and type of positions.  You will need to go into Find Container for the box, and click Positions at the top of the page. 
Then check the dimensions of the positions themselves.
I agree this is confusing. @dustymc

**Comment by LitsaWoo** [comment]
@campmlc Yes I already created the positions in the box. We were able to scan in a couple envelopes after we removed the dimensions for them manually

**Comment by campmlc** [comment]
What were the position dimensions? What tool did you use to create them?

**Comment by campmlc** [comment]
There is a way to bulk remove positions, along with dimensions, and re-create them. And I agree with @dustymc that using positions is preferable, but we need to see the setup. Can we do a zoom call to go over the steps of what you need to do to make this work? It will be much better if you can set this up in a standard way at the outset - changing things later is difficult.

**Comment by LitsaWoo** [comment]
Can we set up a zoom call this week to discuss this issue as well as the barcode issue #8194 
I'm available almost any time this week except Friday after 1:00pm
We are at the phase in our museum where everything is backed up and waiting on this to be solved.

**Comment by campmlc** [comment]
I can potentially do tomorrow morning or this evening. I'm on leave but will try to make time.

**Comment by campmlc** [comment]
@LitsaWoo can you give me a time that works for you in next two days, and I'll set up a meeting?

**Comment by LitsaWoo** [comment]
I can do anytime today (16 October) before 2:30pm (Central), tomorrow (17 October) between 12:30pm and 5:00pm, and Friday (18 October) before 1pm

**Comment by campmlc** [comment]
Ok, Im out this morning but will reach out if I get back before 2:30 CST, otherwise will try for tomorrow..

**Comment by campmlc** [comment]
Resolved in zoom call. Positions were deleted and re-created with correct dimensions. KSB needs to set up a virtual/parentless void container to hold items moved from containers temporarily or that lack object tracking.
