### ISSUE TITLE
[external CONTACT] Test API Pulled?

### ISSUE THREAD

**Issue by pccollins2** [ArctosDB/arctos#8197]
Hi Dusty & Michelle,

Wanted to reach out due to my team no longer being able to access the the test API that was given to us several weeks ago. Was this key pulled, or is there an outage? We were able to use it earlier yesterday, but everyone began running into 503 errors towards the end of the day. We tried again this morning, but still nothing.

Thanks!

**Comment by dustymc** [comment]
restarted

**Comment by pccollins2** [comment]
Working now. Thank you! 👍
