### ISSUE TITLE
Bug Report - Record display error

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#8198]
Arctos Record pages are not displaying - something to do with permissions:
 **ERROR: permission denied for view v_attributes**
![image](https://github.com/user-attachments/assets/76c41e69-3d15-4737-b9a6-aa9d1eb918c7)

It's happening across collections and for multiple users.

**Comment by wellerjes** [comment]
Just came here to post this issue too

**Comment by dustymc** [comment]
woops/thanks/fixed!

**Comment by acdoll** [comment]
That did it - Thanks @dustymc !!
