### ISSUE TITLE
Contact should submit github issue

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#820]
do it

**Comment by dustymc** [comment]
@ccicero will provide whatever mvzgeo uses

**Comment by dustymc** [comment]
Change test to "File an Issue"

@atrox10

**Comment by mkoo** [comment]
What I use for mvzgeo is not really viable for a bug report from Arctos. I recommend doing this properly with the github api (https://developer.github.com/v3/issues/#create-an-issue) where we could also get some page and issue detail from the report form on Arctos (maybe the GUID or other information from the page that the bug report is being filed from. I can talk to Dusty more about the details.

**Comment by dustymc** [comment]
It looks like we have two options:

1. Do something with the API. That will probably result in lots of issues filed by some default user (eg people who file Issues will not have a github account or not be wiling to provide it)
3. Simply open github, in which case users may not bother reporting the issue due to unfamiliarity, not wanting to create an account, etc.

I think I tentatively vote for the first option, even though it's a bit of additional complexity on our end and may result in a lot of "mysteriously appeared" Issues.

We also need a better way of directing users to issues (eg, code is broken) vs. data reports. MOST "issues" from pages with GUIDs are probably data reports (and so should go into another system where they can be directed to Curators), but certainly not all. Ideas?

**Comment by mkoo** [comment]
OK just had a workaround idea-- what if we have a dedicated email to Annotations (it goes to several data quality operators based on collection I believe); I can use that email to create issues in a Github repo via Zapier. Same could be done with the Contact Arctos form (http://arctos.database.museum/contact.cfm?ref=/SpecimenSearch.cfm). If I set up an email for this purpose, Dusty can add appropriately. 
Do we want separate repos for these incoming annotations and contacts? or mush them into this one? I think a separate one or ones makes sense but keep them out of the working group repo.

**Comment by dustymc** [comment]
Yes, I can easily add an email.

I can't remember where this came from - what are we trying to do?

Annotations sends email, stores the annotation in Arctos, pesters people in the "dashboard," and links it to relevant data objects. I'm not sure what else an Issue would do; if we do open Issues I suggest we keep it simple, unless someone has a reason to do otherwise.

Most of the contact form usage is "us" - people who should be directly filing Issues. The last 10 are

- Operator with a locked account
- locked account and timeout issue
- "I know about all animal."
- Operator with a loan problem
- Operator with a bulkloader problem
- Operator with timeout issue
- Public user requesting search help
- Potential new collection
- Question about our cryptic data
- Operator with locked account

I was going to suggest we just replace the contact form with a link to GitHub, but maybe the ~30% who aren't 'us' justify keeping it. If we do keep it then opening an Issue would be useful.

**Comment by dustymc** [comment]
This is implemented through various other issues eg https://github.com/ArctosDB/arctos/issues/2124
