### ISSUE TITLE
Inconsistent higher taxonomy

### ISSUE THREAD

**Issue by AdrienneRaniszewski** [ArctosDB/arctos#8205]
I download the higher taxonomy for all our squirrels and am working on sorting the file into the same order that our collection is organized in. Order / suborder / family / subfamily / genus / species.

This has turned out to not be a simple task. Some of the higher taxonomy is missing and some is just wrong. even within the same genus.

I can certainly correct and fill in the blanks for my sorting purposes, but students also use the higher taxonomy for generating our fluid specimen labels, which would eventually lead to students installing the jars in the wrong place. 

Also... the higher taxonomy should just be cleaner than this. right?

Thoughts on what's going on? and the best way to handle it? I'm only working with squirrels at the moment, so can't say how widespread (or not) this is. I've attached my download so you can see all the weirdness.

[MSB squirrels.xlsx](https://github.com/user-attachments/files/17422627/MSB.squirrels.xlsx)

Thanks for your help!

@jldunnum

**Comment by camwebb** [comment]
> Thoughts on what's going on? and the best way to handle it?

I don't know which classification is being used for your collections, but if it's a shared Arctos classification, it will no doubt be full of inconsitencies and possibly errors, as it was assembled by many people with different understandings of Arctos, different requirements for comprehensiveness, not to mention different opinions on classification.

For UAM Plants we have created our own classification derived directly from the current World Flora Online. The most important feature (for us) is that it imports all the different usages of a name, and their current accepted name if that usage of the name is a synonym (see [Erigeron acris](https://arctos.database.museum/name/Erigeron%20acris#UAMPlants) as an example). Thus the classification can be used a synonymy engine; the Relationships feature of Arctos taxonomy is also shared across the community and is thus error-prone and opinion-prone.

I'll be describing this at the next Arctos Taxonomy meeting on [Nov 14](https://arctosdb.org/calendar/). Feel free to email me if you want to talk about this route.

**Comment by campmlc** [comment]
@jldunnum doesn't ASM support a classification system for mammals? Could this be added as an Arctos source?

**Comment by jldunnum** [comment]
Yes, Mammal diversity database

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by campmlc** [comment]
@camwebb it would fantastic if your curated taxonomy could be added as an Arctos Source. Ditto for https://www.mammaldiversity.org/.

**Comment by camwebb** [comment]
> it would fantastic if your curated taxonomy could be added as an Arctos Source

It is. See 'UAM Plants'

**Comment by dustymc** [comment]
>if your curated taxonomy could be added 

https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxonomy_source#uam_plants ??????

>Ditto

https://github.com/ArctosDB/arctos/issues/6311 - I think this is completely trivial and well documented.

Getting them to do something useful with globalnames is even more trivial (and https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxonomy_source#world_flora_online is a demo of that).

> anyone else to edit it!

The public CT tells you who can do what:

<img width="491" alt="Screenshot 2024-10-28 at 15 52 33" src="https://github.com/user-attachments/assets/b50b2117-0558-4575-ac5e-7e6c6b3df314">

the CT setup clarifies:


<img width="1499" alt="Screenshot 2024-10-28 at 15 52 52" src="https://github.com/user-attachments/assets/186d4161-29c3-4d88-94d5-5ae2ba31b81e">

So you and I can edit, but we're not limited to tools (so I'd be forced to assume it might have been made inconsistent with a single-record edit....).

>many local Classifications, for diff. purposes

Just between us, the real (and real "out there"!) hope is that everyone will stop with the ridiculous nonsense and follow the [virus people](https://ictv.global/) into a full-authority comprehensive taxonomy system. In the meantime, Arctos is designed to allow/encourage anyone who cares to manage just whatever it is that they care about, anyone who cares less to simply use that, and everyone to fall back on any number of less-curated sources for whatever's left.
