### ISSUE TITLE
[Help needed in Arctos] Record Bulkloader error message

### ISSUE THREAD

**Issue by camwebb** [ArctosDB/arctos#8206]
@dustymc A new error (= [status](https://arctos.database.museum/Bulkloader/bulkloader_status.cfm) for 205 records) for me: `null value in column "changed_agent_id" of relation "locality_archive" violates not-null constraint`... Something buggy? These 205 records failed in a previous upload - were the localities actually previously made? Now I tried several times to upload from scratch, with the same error message. The file passed the validator, and the first half of the data (~200 records without the small error, which was a coordinates_error_units without coordinates_error_distance) loaded fine.  I can't find an old issue that seems to answer this.

I have not deleted the records from the bulkloader yet (entered by: `ceswearingen`, bulkloaded by `camwebb`).

Thanks

**Comment by dustymc** [comment]
Thanks, should be debugged and I loaded https://arctos.database.museum/guid/UAM:Myco:224.

Unrelated, see https://handbook.arctosdb.org/documentation/locality.html#specific-locality - ``No specific locality recorded.`` when appropriate will avoid confusion.

**Comment by camwebb** [comment]
> should be debugged and I loaded

:pray: 

> No specific locality recorded.

Thanks - forgot that was the standard phrase.

**Comment by dustymc** [comment]
> side-load

Shove 'em straight in! - I think everything is happy now.

**Comment by camwebb** [comment]
Yay. Done. Thanks
