### ISSUE TITLE
Loan creation error feedback

### ISSUE THREAD

**Issue by jldunnum** [ArctosDB/arctos#8208]
Can't create a loan and can't figure out the issue. Love that I've been doing this for over 20 years and still need a mentor.

ERROR_ID	B695D681-E349-44D4-AD9D7A99F4263724
ERROR_TYPE	SQL
ERROR_MESSAGE	ERROR: function getagentidfromlogin(name) does not exist Hint: No function matches the given name and argument types. You might need to add explicit type casts. Where: PL/pgSQL function trigger_fct_trans_agent_entered() line 3 at SQL statement
ERROR_DETAIL	
ERROR_SQL	INSERT INTO trans ( TRANSACTION_ID, TRANS_DATE, CORRESP_FG, TRANSACTION_TYPE, NATURE_OF_MATERIAL, collection_id, trans_remarks ) VALUES ( nextval('sq_transaction_id'), '2024-10-18', 0, 'loan', 'Dipodomys specimens for CT scanning at UMMZ.', 14, null )

<img width="442" alt="image" src="https://github.com/user-attachments/assets/84a15ac6-260c-4dea-8de0-cfe357d1906a">

**Comment by dustymc** [comment]
You don't need a mentor, I need a better debugger - should be fixed, thanks.

(But I'm curious why you're not using https://github.com/ArctosDB/arctos/issues/7384 ??)

**Comment by jldunnum** [comment]
Cool thanks, didn’t realize 7384 was a functional thing now. I’ll have a look.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dustymc** [comment]
Done?
