### ISSUE TITLE
Anonymous bad data/annotation reporting

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#821]
Need to revisit this, run by Arctos group; or add language that if they don't leave an email there may be no response or action taken

**Comment by amgunderson** [comment]
I think entering an email should remain optional, because people are paranoid about entering their emails on websites for fear of spam.

**Comment by dustymc** [comment]
Annotations, not Issues (right?)

**Comment by amgunderson** [comment]
Right, this is for the "report bad data" form, not issue reporting. I changed the title.

**Comment by dustymc** [comment]
Changed the layout v7.4.1
