### ISSUE TITLE
[CONTACT]

### ISSUE THREAD

**Issue by asemerdj** [ArctosDB/arctos#8218]
Hi there,
I uploaded some data last week and noticed that it's acting strangely when searched - missing identification, parts etc. 

![image](https://github.com/user-attachments/assets/4327b41a-215b-45ee-be52-6793006597df)

as an example, this one has identification data: 
![image](https://github.com/user-attachments/assets/ba67bf83-9efe-4e54-856d-ae6930bb5feb)

as well as parts, though the parts aren't showing up in the header of the specimen page either
![image](https://github.com/user-attachments/assets/2cf5fa2c-1ed2-4c70-a776-c4bf6cbc0728)

I'm not sure what I did wrong here, but is there a way to fix it?

**Comment by dustymc** [comment]
Thanks, that's a bug (and explains https://github.com/ArctosDB/arctos/issues/8204#issuecomment-2424051190) - the problem should be fixed and your records should be refreshed, let me know if something's still stuck.
