### ISSUE TITLE
Help needed in Arctos

### ISSUE THREAD

**Issue by DellaCHall** [ArctosDB/arctos#8228]
One of our student employees (username rlneubuhr) cannot archive a search. When she attempts to do so, she gets the error message below:

![Screenshot 2024-10-24 at 3 50 04 PM](https://github.com/user-attachments/assets/cfb9a18a-c83e-4bd6-bfb0-de28e1cb9f02)

The [handbook](https://handbook.arctosdb.org/documentation/archive.html) says anyone may create an unlocked archive. Are we doing something wrong? Does she need a certain level of permissions? Or is this a bug?

**Comment by dustymc** [comment]
Should be fixed, please confirm.

**Comment by DellaCHall** [comment]
Sorry for the delay, this is the first day she's been back in to check on this. She's now getting this error:
![IMG_0737](https://github.com/user-attachments/assets/9d13ca56-e4d4-4323-b064-c5ed8ecbd561)

**Comment by mkoo** [comment]
completed
