### ISSUE TITLE
Request - Rename "part: bulkload to containers" to "Container: Bulkload Parts"

### ISSUE THREAD

**Issue by happiah-madson** [ArctosDB/arctos#8229]
Help us understand your request (check below):
- [ ] search or data request (help with SQL or provide the specific fields you are trying to retrieve for your collection)
- [ ] add a new Github user to the Arctos Users team
- [ ] a new barcode series
- [ ] a new term for data entry or management 
- [ ] a change or new report or label
- [ ] update to an Agent (split, merge, or other type of change)
- [ ] bulkload changes (to Agents, Identifiers, etc that are not already available as a bulkloading tool)
- [x] new feature or otherwise a good idea to make Arctos even better
- [ ] quarantine taxon name and suggested replacement (please supply links)
- [ ] other

**Describe what you're trying to do** 
On the Tools Directory page, can you please rename "Part: Bulkload to Containers" to "Container: Bulkload Parts"

(Object tracking people cannot find it using the current name.)

@campmlc @LitsaWoo @falco-rk @asemerdj

**Comment by campmlc** [comment]
Object Tracking Committee agrees 2024-10-25

**Comment by dustymc** [comment]
Once upon a time, making the container-part linkage was referred to as *installing* the part, perhaps that vocabulary could be useful. (I can see nothing **wrong** with the suggestion, but it isn't exactly instinctive for me either - maybe that's just a me-thing.)

**Comment by campmlc** [comment]
> Once upon a time, making the container-part linkage was referred to as _installing_ the part, perhaps that vocabulary could be useful. (I can see nothing **wrong** with the suggestion, but it isn't exactly instinctive for me either - maybe that's just a me-thing.)

That implies a workflow that would not be consistent across collections. All of our containers are already "installed" and scanned into position in the collection - we are just virtually adding the parts that are already physically in those containers to make the database connection between the catalog record and object tracking. I would not use or understand the term "installing" in the context of what we do in cryogenic collections.

**Comment by campmlc** [comment]
Any other objections here? OK to proceed?

**Comment by mkoo** [comment]
I assumed the Object tracking committee wanted it this way! proposed name makes more sense to me too. I hear consensus and will update-actionable

**Comment by mkoo** [comment]
completed
