### ISSUE TITLE
Google mapping feature is broken

### ISSUE THREAD

**Issue by jsmetzgar** [ArctosDB/arctos#823]
When using the "map with Google maps" option on the specimen results page, google maps cannot find the kml file and thus can't display the map.

**Comment by dustymc** [comment]
Google has dropped support of mapping KML files. https://developers.google.com/maps/support/kmlmaps

It doesn't look like we'll be able to fix the existing functionality. I'm dropping the Google Maps option from the options. The inline map on the top of specimenresults should provide comparable functionality. Open a new Issue if this isn't an acceptable solution.
