### ISSUE TITLE
Request - add abundance to record attribute options for fish

### ISSUE THREAD

**Issue by gradyjt** [ArctosDB/arctos#8233]
Help us understand your request (check below):
- [ ] search or data request (help with SQL or provide the specific fields you are trying to retrieve for your collection)
- [ ] add a new Github user to the Arctos Users team
- [ ] a new barcode series
- [X ] a new term for data entry or management 
- [ ] a change or new report or label
- [ ] update to an Agent (split, merge, or other type of change)
- [ ] bulkload changes (to Agents, Identifiers, etc that are not already available as a bulkloading tool)
- [ ] new feature or otherwise a good idea to make Arctos even better
- [ ] quarantine taxon name and suggested replacement (please supply links)
- [ ] other

**Describe what you're trying to do** 

Hello, I'm hoping that I can have "Abundance" added to the drop down options in Record Attributes for fish collections. If there's anything else I should have provided to help with this please let me know. Thanks!

**Comment by dustymc** [comment]
@gradyjt  see https://handbook.arctosdb.org/documentation/code_table.html

(@mkoo @ewommack I thought we had documentation on this but I can't find it so I started that - was there something in a newsletter or ?????)

**Comment by gradyjt** [comment]
Oh great, thank you so much! Sorry to bother. -Jessica
