### ISSUE TITLE
Require Tissues in Specimen Search, Type = specimen default

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#824]
Specimen Search screen:
Put box around 
1) Require Tissues and add entry box with arrow to show dropdown yes/no
2) Change Type to Basis of Record: (specimen vs observation vs any): set default to any
3) Includes Media
3) Collection managers need a shortcut to be able to see all specimen records in a collection without having to use Type = specimen

**Comment by dustymc** [comment]
> Require Tissues and add entry box with arrow to show dropdown yes/no

I think we agreed that the checkbox (possible values YES and NULL) is appropriate here (eg, I'd interpret "no" to mean "things which do NOT have tissues") - correct?

> Includes Media

Did we decide on what happens to the stuff in the "Media" pane? Redundancy (having multiple ways of requiring media) is generally evil/confusing.

> shortcut to be able to see all specimen records 

Search _ (underbar="require any character") in any unavoidable NOT NULL field (Identification is my usual).
