### ISSUE TITLE
Bulkloader Error Help

### ISSUE THREAD

**Issue by LitsaWoo** [ArctosDB/arctos#8242]
I'm attempting to bulkload catalog records. The file I'm uploading is returning a syntax error and I've edited the file a few times and still can't figure out what the error is.

This is the link to the Arctos page:
https://arctos.database.museum/Bulkloader/BulkloadSpecimens.cfm

Here's the error info:

ERROR_ID	3D868BA2-B1A0-4E1F-B36DA40CF6A028EC
ERROR_TYPE	application
ERROR_MESSAGE	Error invoking external process
ERROR_DETAIL	lucee.commons.cli.CommandException: psql:/usr/local/webroot/temp/excopy_litsawooten_20241028061010994_871.sql:1: ERROR: syntax error at or near "," LINE 1: ..._20_attribute_method_2,part_20_attribute_remark_2,,,,,,,,,,,... ^

And here is the file I'm uploading:
[2024.020 bulkloader.csv](https://github.com/user-attachments/files/17549738/2024.020.bulkloader.csv)

**Comment by dustymc** [comment]
<img width="805" alt="Screenshot 2024-10-28 at 16 35 04" src="https://github.com/user-attachments/assets/73d0a158-e477-46df-b4b7-724de55c24f3">


Excel(?) is doing Excel things; do whatever you need to do to get rid of the NULL columns. (My solution is to not use Excel, if that's useful....)
