### ISSUE TITLE
Help needed in Arctos -- remove a shipment

### ISSUE THREAD

**Issue by happiah-madson** [ArctosDB/arctos#8243]
I added a second shipment to a loan and I want to remove one of them, but do not see any "remove" options.

# What are relevant pages in Arctos
https://arctos.database.museum/Loan.cfm?action=editLoan&transaction_id=21143303

@falco-rk @dustymc

**Comment by dustymc** [comment]
Shipments cannot be removed as a chain of custody protection. I can manually remove one if you want - update the remarks to "DELETE" and let me know.

**Comment by falco-rk** [comment]
Remarks updated to DELETE! Thanks, Dusty!

**Comment by happiah-madson** [comment]
Thank you!!!!

**Comment by AJLinn** [comment]
AHHHH! It must be the day for doing erroneous shipments! I also need a shipment deleted as I made a mistake and added the return shipment to the wrong loan... long story of mixed up files! @dustymc can you delete my shipment as well? I'll add DELETE to my remarks as well. Thanks!

Loan: https://arctos.database.museum/Loan.cfm?Action=editLoan&transaction_id=21136255

**Comment by dustymc** [comment]
zapped

**Comment by campmlc** [comment]
I had previously requested the ability to delete loan shipments created in error, as this is a not uncommon occurrence. For example, I sometimes had to change the address or recipient, or I add the shipment to the wrong loan. It seems that CMs should be trusted to know when this is or is not relevant. If not, then we need a way to deprecate a shipment and flag it as erroneous.

**Comment by dustymc** [comment]
The problem has been addressed, if there are other concerns please open an issue for them.
