### ISSUE TITLE
bulkloader data

### ISSUE THREAD

**Issue by hannahb2402** [ArctosDB/arctos#8246]
I contacted the person with data in the bulkloading stage and they did not respond.
Can you please delete their data from this stage? Thank you!
https://github.com/LitsaWoo
wootenl@unm.edu
@LitsaWoo 
[bulkloader_stage (5).csv](https://github.com/user-attachments/files/17575142/bulkloader_stage.5.csv)

**Comment by KatherineLAnderson** [comment]
I also reached out, but didn't hear back. I downloaded the data and emailed it to them!
