### ISSUE TITLE
Error creating part

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#8250]
I'm adding a new part to a record (which I do weekly for CT scans) and am receiving an error:

![image](https://github.com/user-attachments/assets/833ffb8a-e339-48b3-95b8-266936466a01)
![image](https://github.com/user-attachments/assets/36fbf866-b1a9-4b1b-955b-b627d8fbd935)

I'm not sure why.

record: https://arctos.database.museum/guid/UCM:Herp:13176

Desired values: part_name = media, count = 1, condition = CT scan (whole body), remark = CT scan, hosted on MorphoSource

**Comment by happiah-madson** [comment]
Agree, we just tried to bulkload and got this error for everything:
![WhatsApp Image 2024-10-30 at 13 42 55](https://github.com/user-attachments/assets/f43b7062-cad6-487b-8bbf-b9e0f91c88db)

**Comment by dustymc** [comment]
Knew I'd miss something with https://github.com/ArctosDB/dev/issues/90...

Should be patched.

**Comment by happiah-madson** [comment]
ditto! Thanks!
