### ISSUE TITLE
Help needed in Arctos: record bulkloader error translation

### ISSUE THREAD

**Issue by KatherineLAnderson** [ArctosDB/arctos#8251]
# Tell us what you are trying to do 
Bulkloaded specimen records and received a strange error when I flagged them to load.
"insert or update on table "container" violates foreign key constraint "fk_parent_container_id_container_id"
I'm not currently using containers, but maybe this is a different kind of container.
help? @dustymc 

[BulkPendingData(1).csv](https://github.com/user-attachments/files/17577393/BulkPendingData.1.csv)

# What are relevant pages in Arctos

**Provide a link to or a description of the page where you need help.**

**Comment by campmlc** [comment]
This is happening to our MSB operators as well. @jtgiermakowski

**Comment by mkoo** [comment]
Dup of https://github.com/ArctosDB/arctos/issues/8252
@dustymc input?

**Comment by dustymc** [comment]
dup of https://github.com/ArctosDB/arctos/issues/8250

**Comment by mkoo** [comment]
ah the ol' triple duplicate! thx
