### ISSUE TITLE
Help needed in Arctos: Error in Bulkloader browse & edit

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#8252]
# Tell us what you are trying to do 
What does this status mean in the browse and edit table?

insert or update on table "container" violates foreign key constraint "fk_parent_container_id_container_id"

# What are relevant pages in Arctos
**Provide a link to or a description of the page where you need help.**
https://arctos.database.museum/Bulkloader/editBulkloader.cfm?key=key_5329951

@dustymc can you help me? Thanks!!!

**Comment by AJLinn** [comment]
nevermind! It loaded

**Comment by sharpphyl** [comment]
@dustymc  We're getting the same error message on single record date entry upload.

insert or update on table "container" violates foreign key constraint "fk_parent_container_id_container_id"

**Comment by dustymc** [comment]
dup of https://github.com/ArctosDB/arctos/issues/8250
