### ISSUE TITLE
Bug Report- Loan Item Bulkload is duplicating records

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#8254]
**Describe the bug**
Using Loan Item Bulkload to add items to loan. My settings are to ignore subsamples and create a new subsample from the existing part with specified barcode. Twice now I've used the tool to load 31 samples. The Review and Load page in the component loader shows that I am loading 31 samples. But when I Review Items in the loan, there are 62, in duplicate pairs. The first time this happened, I thought maybe I'd done something wrong, clicked something twice etc. So I deleted all parts/subsamples from the loan. Then I reloaded from scratch, and the same thing happened.

**To Reproduce**
1. Go to https://arctos.database.museum/tools/BulkloadLoanItem.cfm
2. Click on Load csv; upload csv file attached
3. Go to https://arctos.database.museum/loanItemReview.cfm?transaction_id=21143402
4. See duplicate records added 

**Screenshots**

![Screenshot 2024-10-31 09 41 48](https://github.com/user-attachments/assets/9a32a044-50b4-462c-9252-744dfc42bab6)
![Screenshot 2024-10-31 09 41 22](https://github.com/user-attachments/assets/307afe5a-f52f-48ac-b174-e03215176524)

**Data**

[Loan bulkload Mongolian bats.csv](https://github.com/user-attachments/files/17589866/Loan.bulkload.Mongolian.bats.csv)

**Desktop (please complete the following information):**

**Additional context**

**Comment by dustymc** [comment]
@campmlc yes, I noticed this as well, I think the immediate cause is not active now (you probably noticed the reboot), please try to delete and re-load again (or let me know if you want me to do it).

**Comment by campmlc** [comment]
Just checked - looks good, thanks!
