### ISSUE TITLE
Help needed in Arctos updating container in specimen record

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#8257]
# Tell us what you are trying to do

I have a student, I need her to be able to update containers for parts from the specimen record. Reading through user roles to find what was appropriate I saw this note on the description for manage container "Note: manage_specimens can update container (ie, to associate a specimen with a container)". I thought perfect, I can give her manage_specimen without having to give her manage container. However, after I gave her manage specimen, she was not able to update containers on the specimen record.

Am I just misinterpreting how this works, or is there a bug?

# What are relevant pages in Arctos
https://arctos.database.museum/Admin/user_roles.cfm#manage_container
https://arctos.database.museum/Admin/user_roles.cfm#manage_specimens

**Comment by dustymc** [comment]
I think the immediate answer is manage_container.

(There's a longer answer but some details are stuck, I'll do something about that...)

> Note: manage_specimens can update container (ie, to associate a specimen with a container)

That's just wrong, I've updated.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> the immediate answer is manage_container

Yes, that is what I have done. Thanks for updating the incorrect description.

> There's a longer answer but some details are stuck, I'll do something about that.

Do you want me to leave this issue open for that?

**Comment by dustymc** [comment]
>leave this issue open for that?

Na, but you can watch https://github.com/ArctosDB/dev/issues/93 (or nudge/adopt/?? https://github.com/ArctosDB/arctos/issues/7127 if you're feeling exceptionally adventurous)
