### ISSUE TITLE
project value

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#826]
add funded value or something to projects
calculate $ of research supported by projects that collect
@jmalaney

**Comment by jmalaney** [comment]
So maybe this is INVESTMENT of NSF in specimen based research, try to characterize the $$ and exponential impacts. 

Also, let's identify the simpler (maybe not) direct & indirect research impact = citations / loans / downloads of specimens from individual events/projects/agents/years/museums. --- maybe move this to a separate issue?

Bottom up approaches:
What broader impacts did Malaney have from his 2007 summer of collections?
How many pubs (and citations) from specimens donated by BCP?
Impact of place-based training (Mammalogy 2000 field trip = single event). 

From the top down:
How many specimens & citations are related to Hantavirus research?
How many records were used (valued) for niche modeling?

**Comment by dustymc** [comment]
Implemented in test, see https://github.com/ArctosDB/documentation-wiki/wiki/How-to-understand-Project-Funding

"How many {whatever we can get by following the data to other projects}" is/should be just reporting; open a new Issue to request additional features.

**Comment by campmlc** [comment]
Dusty,
Can we add a field for funding source? E.g. NSF award number?

**Comment by mkoo** [comment]
Solid idea.

On Friday, May 13, 2016, Mariel Campbell <notifications@github.com> wrote:

> Dusty,
> Can we add a field for funding source? E.g. NSF award number?
>
> On Fri, May 13, 2016 at 10:48 AM, dustymc <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > Implemented in test, see
> >
> https://github.com/ArctosDB/documentation-wiki/wiki/How-to-understand-Project-Funding
> >
> > "How many {whatever we can get by following the data to other projects}"
> > is/should be just reporting; open a new Issue to request additional
> > features.
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ArctosDB/arctos/issues/826#issuecomment-219097648>
> >
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ArctosDB/arctos/issues/826#issuecomment-219101442>
>


-- 
Sent from Gmail Mobile

**Comment by dustymc** [comment]
Project agent roles has a "sponsor" option for funding source.

<img width="512" alt="screen shot 2016-05-13 at 10 23 04 am" src="https://cloud.githubusercontent.com/assets/5720791/15256121/d7bf6c52-18f4-11e6-8625-c27335bedce6.png">

<img width="1111" alt="screen shot 2016-05-13 at 10 23 46 am" src="https://cloud.githubusercontent.com/assets/5720791/15256158/022b3700-18f5-11e6-8f32-7bebe7de6d14.png">

A potential "real" solution is http://www.crossref.org/fundingdata/, should someone be able to figure out what it's actually doing...

**Comment by campmlc** [comment]
Putting a funding agency in as sponsor is a possible solution, but there is no good place for the award number or the amount of individual grants. We'd have to put it in remarks. We'd have to create agents for institutional grants, scholarships etc.  This is possible if there is no better option. The crossref.org site looks a bit intimidating.

**Comment by dustymc** [comment]
What are you trying to do? If the NSF# could DO SOMETHING we wouldn't much need this issue - we'd just go pull data from them instead of building a place for it and entering it ourselves. If it can't do anything then I'm not sure why remarks isn't as good as anywhere else. Is there something about NSF#s that I don't know?

If you're looking for a link to the NSF award summary, you could create Media and add it to the project.

>We'd have to create agents for institutional grants, scholarships etc.

How else do you envision giving them credit?

>The crossref.org site looks a bit intimidating.

It's worth understanding what they're trying to do. They're trying to make the NSF# DO SOMETHING, and do it in the context of other stuff, like publications, authors, other funding, etc. If authors/researchers/editors/funding agencies all decided to play nicely, this Issue (and a bunch of other stuff) could all happen mostly by itself - we'd just need to cite specimens by DOI (or something that could be resolved to a DOI) and use that as an entry point to the ecosystem Crossref is trying to build.

**Comment by campmlc** [comment]
We do need to move this forward. We need to include an identifier along with the sponsor, ideally and award number, so that we can search on specific grants for reporting purposes. Projects sort of allow us to do that, but sometimes projects involve more than one grant. We need to explicitly include the award number as a searchable field.
