### ISSUE TITLE
Help needed: component loaders stuck?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#8265]
# Tell us what you are trying to do 
Use the identifier bulkloader and bulk-unloader to try to convert relationships on 94 records from "self" to "parasite of". This is a challenging process involving two different component loaders to fix a single field of only 94 records. I need this to complete a grant report  and other steps are dependent on this one. I bumped these two processes to top of the Component Loader Status List. But nothing is happening - @dustymc please give the component loaders a nudge?

# What are relevant pages in Arctos
https://arctos.database.museum/loaders/BulkloadOtherId.cfm
https://arctos.database.museum/loaders/bulkUnLoadIdentifier.cfm
https://arctos.database.museum/info/component_loader_status.cfm

**Comment by dustymc** [comment]
Yes, loaders are not running. I will patch as soon as possible, hopefully today or downtime on Friday at the latest. (And maybe that explains https://github.com/ArctosDB/dev/issues/94#issuecomment-2457245854 @happiah-madson ??)

**Comment by dustymc** [comment]
Loaders are now running, closing.

>This is a challenging process

It shouldn't be, if you want to spell the challenges out in an issue I bet I can help.
