### ISSUE TITLE
Add time slider to search specimens tool

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#827]
Add a time slider to the advanced search specimens tool

**Comment by mkoo** [comment]
so many great libraries for this nowadays!
+1

**Comment by dustymc** [comment]
Specific suggestions? I'm looking at http://ghusse.github.io/jQRangeSlider/ but it looks like it has a lot of dependencies (=more junk to load=potentially problematic on slow connections) - maybe something simpler could work for us?? It's mostly jQuery dependencies and many/most browsers have those cached so maybe we don't need to care??

Sliders get a little weird with the possibility of big date ranges. Here's what a slider looks like with possible values from 1800-NOW(), with ~1 year (as close as I could get!) selected:

<img width="601" alt="screen shot 2016-02-29 at 11 24 42 am" src="https://cloud.githubusercontent.com/assets/5720791/13406218/274bc3b8-ded7-11e5-8488-dcb1ca327f63.png">

We could need much larger date ranges - eg, ~1000 years for cultural collections probably isn't unusual. I can't find a good UI approach to that.

Perhaps an unrelated discussion (someone please file a new Issue if so), but this takes us back to requests like #838 - if we use plug-ins we give up some ability to respond to customization requests. That's less significant here where we're just plugging a UI widget in vs. eg, specimenresults where the plugin relies on (lots of) plugin-specific code, but perhaps something that needs recognized in any case.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/2745
