### ISSUE TITLE
I would like to start a PERMIT COMMITTEE

### ISSUE THREAD

**Issue by happiah-madson** [ArctosDB/arctos#8270]
I need a permit committee to exist so that we can get some permit things done.

People who I think may be interested include:
@campmlc @mkoo @dustymc 

Please add other names or collections because I know nearly no one!

Here is a when2meet poll for the month of November, because I would like to get this moving before the new year!

https://www.when2meet.com/?27414736-SsK6B

**Comment by mkoo** [comment]
Great idea! I am going to convert to a discussion to continue the conversation AND send an AWG email to get more ideas and people to join.  Hannah, you're leading, correct?! Thanks!
