### ISSUE TITLE
Arctos Maintenance - 11/8 this Friday Completed!

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#8274]
## Planned Outage
 - Date and time outage will begin: Friday 11/8
 - Expected duration of outage: 2 hours of intermittent access
 - Reason for outage: planned maintenance and security checks
 - Expected behavior during and after the outage: Arctos will be unavailable for work

## Communication before/during outage
- [x] Pin this issue
- [x] Banner updated @mkoo
- [x] Email sent to AWG  
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [x] Unpin this issue
- [x] Banner updated @mkoo
- [ ] Email sent to AWG 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by ewommack** [comment]
Sent email, scheduled another one for Thursday morning, and added to the Slack channel.

**Comment by mkoo** [comment]
Updates and rebooting still in progress just took longer than scheduled!

**Comment by mkoo** [comment]
And we're back! thanks all for your patience!
