### ISSUE TITLE
(Possible) Bug Report - Operator cannot delete identification

### ISSUE THREAD

**Issue by camwebb** [ArctosDB/arctos#8281]
An operator with manage_specimens and manage_records permissions can create a new identification, but not delete an existing identification. Trying this throws up an error:

```
ERROR_ID0D454459-A8FE-458E-BCE466DD4B728A03 
ERROR_TYPE application 
ERROR_MESSAGE update_identification fail
ERROR_DETAIL Message: ERROR: permission denied for table identification_taxonomy
                      SQL: DELETE FROM identification_taxonomy WHERE identification_id = 12326502
```

We tried this with another record and got same error. Is this expected behavior?

**Comment by dustymc** [comment]
Deleting identifications requires manage_collection, on the theory that deleting an identification requires about the same level of responsibility/authority as throwing out a skull.

**Comment by camwebb** [comment]
Thanks, that resolves my question. But it may still be worth some discussion whether to downgrade this to manage_record.

Many of the UAM:Herb identifications are placeholders (names taken from the herbarium folder, without consulting the specimen), almost dummy data, and any serious tidy-up of a record should fully replace them. Especially now that we have started using the `A {string}` approach to names; we cannot convert an A name to an `A {string}` name. 

Leaving the dummy identification in place with rank 0 is of course fine, but it would be nice to have the ability for a good assistant to delete them.  If the real depreciated names (i.e., prior identifications) had been switched to rank, 2, 3, 4 etc., then rank 0 could have been used simply to signify 'ignore', but all the previous identifications became rank 0, and, in my opinion, 'dummy' names should not have the same status as meaningful but prior identifications.

**Comment by mkoo** [comment]
resolved and took Cam's suggestion for a new issue
