### ISSUE TITLE
request: delete identification in manage_record permission

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#8282]
From @camwebb:
Thanks, that resolves my question. But it may still be worth some discussion whether to downgrade this to manage_record.

Many of the UAM:Herb identifications are placeholders (names taken from the herbarium folder, without consulting the specimen), almost dummy data, and any serious tidy-up of a record should fully replace them. Especially now that we have started using the `A {string}` approach to names; we cannot convert an A name to an `A {string}` name. 

Leaving the dummy identification in place with rank 0 is of course fine, but it would be nice to have the ability for a good assistant to delete them.  If the real depreciated names (i.e., prior identifications) had been switched to rank, 2, 3, 4 etc., then rank 0 could have been used simply to signify 'ignore', but all the previous identifications became rank 0, and, in my opinion, 'dummy' names should not have the same status as meaningful but prior identifications.

_Originally posted by @camwebb in https://github.com/ArctosDB/arctos/issues/8281#issuecomment-2463461089_

**Comment by mkoo** [comment]
Let's map out permissions to people's roles and see how this shakes out.. in progress for documentation

**Comment by dustymc** [comment]
Wearing my technical hat: This is entirely a social problem, let me know when/if ya'll want something different.

---------------


Wearing my "been there, done that, including finding more than a few misfiled (by ID, however rough) plants in that herbarium (which was, by the way, some of the cleanest not-very-exposed data I've ever encountered, it's all downhill from there)" hat:

1. We need an acronym or something, that's a mouthful, and
2. Any clue can be vital to unwinding various mysteries, the idea of tossing any sort of information just isn't something I can understand or support. Even something just WILDLY wrong might help explain why someone's cited an oak in a horsetail study (duplicate number? Misfiled sheet? Just a typo?), or come in handy in any sort of way that nobody's thought of yet. I think this part of the model is, if anything, too liberal, and I think relaxing it would be a mistake.


> cannot convert ...

See above: Future-you will thank you for not trying to.

**Comment by camwebb** [comment]
> Any clue can be vital to unwinding various mysteries, the idea of tossing any sort of information just isn't something I can understand or support.

I have to agree.  So maybe we should drop this. 

If we did, what do people think about adding a rank of '99' to the possible values in the dropdown? This would create the possibility of differentiating bad data kept for the above reasons from very important alternate identifications that were automatically demoted to 'unaccepted' (rank 0) during the switch to ranking a couple years ago. Personally I would like to see the 0-rank identifications _not_ being hidden as they are now - but the 99-rank entry should be hidden.

**Comment by dustymc** [comment]
>99

The current limit is 10 just because the 100-item dropdowns are a bit overwhelming, but if ya'll have more than 10 categories for any given record then it wouldn't be too difficult to up that.

>automatically demoted to 'unaccepted' (rank 0) during the switch

That is not correct, we went into that migration with one 1 and any number of 0 and came out with the same thing; neither the values nor the meaning changed in any substantial way, the change just created the possibility of more than one accepted and allowed ranking among them: https://github.com/ArctosDB/arctos/issues/3540

>0-rank identifications not being hidden as they are now - but the 99-rank entry should be hidden.

0==we don't believe this
99==we believe this, we just like 98 other things a bit more

??

https://handbook.arctosdb.org/documentation/identification.html#identification-order

**Comment by camwebb** [comment]
Thanks for the reply @dustymc 

> That is not correct, we went into that migration with one 1 and any number of 0 and came out with the same thing; neither the values nor the meaning changed in any substantial way

Ah - I had forgotten how the previous system worked (i.e., one accepted, 0-many unaccepted).

Okay I drop my rank=99 suggestion. We can indicate in the Remarks field of the identification if it was dummy data, without deleting it.  I guess I still would like to see rank==0 identifications to be visible by default. Might open another issue about this some time.

@mkoo Feel free to close this issue if you think it would be better not to raise the matter of expanding the circle of those who can delete an identification.

**Comment by mkoo** [comment]
Closing for now as an acceptable workflow is available!
