### ISSUE TITLE
[CONTACT: Blocked Network]

### ISSUE THREAD

**Issue by desmet555** [ArctosDB/arctos#8290]
restricted IP: 86.85.232.242  I am not aware of any malware on my iMac

Please give me access to the Arctos database for ethnopharmacological research. 

With my best regards,
Prof. em. Peter AGM De Smet
formerly UMC Radboud Nijmegen, The Netherlands
currently independent ethnopharmacological researcher
desmet501@hotmail.com
https://en.wikipedia.org/wiki/Peter_A._G._M._De_Smet

**Comment by dustymc** [comment]
Restrictions removed.
