### ISSUE TITLE
Arctos Down - 

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#8294]
Please complete to the best of your ability.

## Unplanned Outage
 - Date and time (**please add time zone from which you are reporting**) outage discovered: 3:30 MT
 - Describe the outage (Arctos down or only some part not working?): Going to arctos.database.museum gives this timeout error:
 <html>
<body>

ERROR_ID | 6BB22199-0455-496D-A44895E958D1AE35
ERROR_TYPE | expression
ERROR_MESSAGE | Request [/search.cfm (/usr/local/webroot/search.cfm)] has run into a timeout (timeout: 60 seconds) and has been stopped. The thread started 60586ms ago.
ERROR_DETAIL

<br class="Apple-interchange-newline">
</body>
</html>

## Planned Outage
 - Date and time outage will begin:
 - Expected duration of outage:
 - Reason for outage:
 - Expected behavior during and after the outage:

## Communication before/during outage
- [ ] Pin this issue
- [ ] Banner updated @mkoo
- [ ] Email sent to AWG  
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @mkoo
- [ ] Email sent to AWG 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by dustymc** [comment]
Not completely, but something was definitely wedged - VMs are rebooting, hopefully back in a few minutes.....

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Back in, thanks!

**Comment by jebrad** [comment]
Yes it is working for me now thanks.  
Is there a way I can check to make sure I am not duplicating an issue (someone else had already pointed out Arctos is down).  I checked my inbox and saw nothing, so I created the issue.  Should I change my notifications?  or is this something where I should not expect to be notified/ Dusty doesn't mind duplicate issues?

**Comment by mkoo** [comment]
Not a problem with duplicate issues... easy to take care of!
Arctos being down are almost always near the top of the pile or pinned so should be obvious if you're on Github filing the issue.

**Comment by dustymc** [comment]
>Dusty doesn't mind duplicate issues

Not at all - please check for a pinned issue (which should happen with any extended downtime) and glance around a bit if it's convenient, but letting me know there's a problem is clearly the important thing and if that means duplicates then I'm happy to deal with them.

**Comment by ewommack** [comment]
Yeah back up for me! It was weird. Kept sending me to the sign in page and wouldn't let me go past it.
