### ISSUE TITLE
Arctos not responding

### ISSUE THREAD

**Issue by jebrad** [ArctosDB/arctos#8295]
Arctos seems to be down, on a couple different computers.  It did get me this much:
This message has been logged as 017511D1-ABCA-486C-B1A2F3D3DC2D2957. Please [contact us](https://github.com/ArctosDB/arctos/issues/new?assignees=&labels=contact&template=contact-arctos.md&title=error%20feedback) with any information that might help us to resolve this problem. For best results, include the error as text and a detailed description of how it came to occur in the Issue.

**Comment by dustymc** [comment]
dup https://github.com/ArctosDB/arctos/issues/8294
