### ISSUE TITLE
Arctos Down - unable to load any pages

### ISSUE THREAD

**Issue by happiah-madson** [ArctosDB/arctos#8300]
Please complete to the best of your ability.

## Unplanned Outage
 - November 14, 9:51 Eastern Time
 - no pages are loading

## Communication before/during outage
- [ ] Pin this issue
- [ ] Banner updated @mkoo
- [ ] Email sent to AWG  
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @mkoo
- [ ] Email sent to AWG 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by campmlc** [comment]
I'm having the same issue. I try to login, and get spinning browser of death.

**Comment by happiah-madson** [comment]
We're now getting "an error occured" and this image
![WhatsApp Image 2024-11-14 at 09 53 31](https://github.com/user-attachments/assets/0c511067-0c79-4e40-8767-771efb624a62)

**Comment by campmlc** [comment]
Seems to be back up?

**Comment by happiah-madson** [comment]
Agreed! Whew!
