### ISSUE TITLE
Help needed in Arctos: error in a report

### ISSUE THREAD

**Issue by happiah-madson** [ArctosDB/arctos#8308]
I'm trying to run a report and am getting this error:

![Screen Shot 2024-11-18 at 10 48 35 AM](https://github.com/user-attachments/assets/b8efea89-6b26-43b1-ab0a-d8cdd2e1dcca)

# What are relevant pages in Arctos
https://arctos.database.museum/Reports/reporter.cfm?action=view&report_id=194

**Comment by dustymc** [comment]
patched
