### ISSUE TITLE
Request - Clarifying when to use encumberances vs permits

### ISSUE THREAD

**Issue by happiah-madson** [ArctosDB/arctos#8309]
Help us understand your request (check below):
- [ ] search or data request (help with SQL or provide the specific fields you are trying to retrieve for your collection)
- [ ] add a new Github user to the Arctos Users team
- [ ] a new barcode series
- [ ] a new term for data entry or management 
- [ ] a change or new report or label
- [ ] update to an Agent (split, merge, or other type of change)
- [ ] bulkload changes (to Agents, Identifiers, etc that are not already available as a bulkloading tool)
- [x] new feature or otherwise a good idea to make Arctos even better
- [ ] quarantine taxon name and suggested replacement (please supply links)
- [ ] other

**Describe what you're trying to do** 
Following the permit committee meetings, I am seeking to clarify and standardize the use of **permits** vs. the use of **encumbrances**. (Notes from the meeting available here: https://docs.google.com/document/d/10u_2CXNaTyDIoO9DYOlEGAGLDJ946sO0MVQ35XaCk5s/edit?tab=t.0)

Based on the conversation, we came to the following understandings:
1. Encumbrances have to do with the Arctos UI and control what data the public can and cannot interact with. This means that they control what information makes it to filtered flat, is viewable on a record if a user is not logged in, or is sent to GBIF and other aggregators. You can encumber any field(s) and when fields are encumbered, they are not publicly viewable.
2. Permits will now contain a new fields ([use_condition and use_condition_summary](https://github.com/ArctosDB/dev/issues/121)) that describe usage conditions. These fields are for _any materials_ and the conditions and/or restrictions on their use. The usage condition fields will be viewable in flat (for curators) but NOT filtered flat (for the public).

This means that the "restrict usage" field for encumbrances is perhaps better placed in permits+usage conditions as the intent is to restrict the usage of materials.

Our hope is that this clarifies when it is appropriate to use an encumbrance (i.e., you don't want the public to see geographic coordinates or the value of an object) vs. permits + usage conditions (i.e., when you loan a sample, the recipient must acknowledge the field collector in any publications).

@dustymc @campmlc please correct me if I have mischaracterized any aspect of our conversation!

**Comment by dustymc** [comment]
I think that's accurate, but it also needs to involve a migration: restrict usage [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctencumbrance_action#restrict_usage), and the encumbrances using it, need to be removed or transferred to permits. I'm happy to help move stuff, but I'm not sure if I should just do that or if this needs an AWG meeting announcement or ??? 

>encumber any field(s)

For clarity: Records may be encumbered, or certain data within a record may be encumbered. 

>don't want the public to see geographic coordinates

See also https://github.com/ArctosDB/arctos/issues/8058 (there's now a better way to restrict place information, I'd like to remove that encumbrance).

I'll start cleanup by addressing my encumbrances. @camwebb @StefanieBond here are a couple old "problem lists" that are still hanging around for whatever reason, I'll delete my encumbrances in a few days, I think this is all of the information in case there's still anything left to do (probably not?): [temp_dlmruencs.csv.zip](https://github.com/user-attachments/files/17803569/temp_dlmruencs.csv.zip)

**Comment by happiah-madson** [comment]
>I'm happy to help move stuff, but I'm not sure if I should just do that or if this needs an AWG meeting announcement or ???

@mkoo @ewommack can you advise on the best way to communicate about this?

**Comment by camwebb** [comment]
@dustymc 1. We can refind the duplicate ALAACs without the encumbrance 'ALA:DuplicateALANumber', and 2. I deleted the record in the encumbrance 'delete dups', so all good for you to delete.

**Comment by dustymc** [comment]
Here are remaining restrict usage encumbrances:


[temp_ruencs.csv.zip](https://github.com/user-attachments/files/17833312/temp_ruencs.csv.zip)

Looks like most are unused/expired deletion placeholders, adding to AWG for hopeful quick and painless transfer of the active/used to permits (or I can fall back to mask record if that's not as smooth as I think it should be).

**Comment by amgunderson** [comment]
Yes, I agree. Some encumbrances are valid and good reminders for the specimens they apply to for the entire life of those specimens. The specimens do not expire so the encumbrances should not expire either.

**Comment by dustymc** [comment]
[Definition](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctencumbrance_action#restrict_usage) updated, the request is satisfied, closing.
