### ISSUE TITLE
turn multiple coordinates into WKT

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#831]
![img_20160219_213716](https://cloud.githubusercontent.com/assets/5720791/13194559/9869b760-d74a-11e5-8146-50a70140c0ba.jpg)

Turn points referencing 5 (or whatever) nets into WKT shape. Avoid black boxes (manis) students and interpretation and transcription.

@ccicero

**Comment by mkoo** [comment]
are we talking about minimum convex hull operations?

**Comment by dustymc** [comment]
I think the specifics are open for discussion, and may depend on things like what we can do with WKT in Arctos, what GBIF/VertNet/etc., can do with WKT, how users respond to WKT in downloads, etc. (My first guess is that we'll have good reasons to retain point-radius, but I'm very unsure of that.) 

The goal is to replace things that might be interpreted as "a determination" (eg, performing nondeterministic operations - a person using manis/google maps/etc. to produce an estimate of error form points+text) with something that IS deterministic (eg, uploading GPS coordinates to some well-documented operation - MCH, or a point-radius transformation that encompasses the given data, or WHATEVER). This will add predictability (given {X1,Y1;X2,Y2; ...} you'll ALWAYS get {Z}), eliminate transcription errors (which currently must minimally be something like transcribe from GPS, type into a service from field notes, copy-paste to Arctos), and eliminate any need for a second person ("georeferencer") between the specimen and locality-stack.

**Comment by atrox10** [comment]
Hey Dusty

One thing, check with John W about this too, I remember having some email
discussion about WKT coordinates lately and whether they work to display
shapes on databases, he seemed to know more.

On Mon, Feb 22, 2016 at 11:47 AM, dustymc <notifications@github.com> wrote:

> I think the specifics are open for discussion, and may depend on things
> like what we can do with WKT in Arctos, what GBIF/VertNet/etc., can do with
> WKT, how users respond to WKT in downloads, etc. (My first guess is that
> we'll have good reasons to retain point-radius, but I'm very unsure of
> that.)
>
> The goal is to replace things that might be interpreted as "a
> determination" (eg, performing nondeterministic operations - a person using
> manis/google maps/etc. to produce an estimate of error form points+text)
> with something that IS deterministic (eg, uploading GPS coordinates to some
> well-documented operation - MCH, or a point-radius transformation that
> encompasses the given data, or WHATEVER). This will add predictability
> (given {X1,Y1;X2,Y2; ...} you'll ALWAYS get {Z}), eliminate transcription
> errors (which currently must minimally be something like transcribe from
> GPS, type into a service from field notes, copy-paste to Arctos), and
> eliminate any need for a second person ("georeferencer") between the
> specimen and locality-stack.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ArctosDB/arctos/issues/831#issuecomment-187348071>.
>



-- 
Carol L. Spencer, Ph.D.
Staff Curator of Herpetology & Researcher
Museum of Vertebrate Zoology
3101 Valley Life Sciences Building
University of California, Berkeley, CA, USA 94720-3160
atrox10@gmail.com  and  atrox@berkeley.edu
510-643-5778 /FAX: 510-643-8238

http://www.herpnet.org
http://mvz.berkeley.edu/
http://www.vertnet.org

**Comment by dustymc** [comment]
Thanks. 

GMaps at least knows what to do with one WTK, but I haven't tried anything beyond that. I really don't know anything about WKT, if what I'm suggesting is even possible/practical, but it would save you guys some work (and transcription errors) if it is.

http://arctos.database.museum/editLocality.cfm?locality_id=10742839

<img width="616" alt="screen shot 2016-02-22 at 4 29 18 pm" src="https://cloud.githubusercontent.com/assets/5720791/13237549/b8beb162-d981-11e5-919e-783eb24791e1.png">

@tucotuco, halp!

#765

**Comment by dustymc** [comment]
post-#2660

**Comment by dustymc** [comment]
I think we now have all the tools for this, pending https://github.com/ArctosDB/arctos/issues/4259. Going next task, leaving blocked.

How these data would get entered is a bit of a mystery - @ccicero example?
