### ISSUE TITLE
Help needed in Arctos, label needs standard measurements code and won't print or make a pdf correctly

### ISSUE THREAD

**Issue by amgunderson** [ArctosDB/arctos#8311]
# Tell us what you are trying to do 
I have made a label, UAM:Mamm test https://arctos.database.museum/Reports/reporter.cfm?action=edit&report_id=252
I cannot make the sql code for standard measurements to be formatted total_length-tail_length-hind_foot_with_claw-ear_from_notch≡weight with units, that is beyond my Arctos sql abilities.
Can you please paste that code here or put it right into my label?

Also it will not print in 2 columns per page, when I choose to make a pdf it puts the label in a single column when a page should fit 2
Thanks

**Comment by amgunderson** [comment]
You made the measurements work (mostly, the tribar ≡ didn't work in excel) for our csv we use to make labels in MSWord, uam_mamm_label_csv. I don't know what a function is but whatever puts the measurements in the label is fine. Units on the weight but not for any of the other measurements.
Other labels print in 2 or 3 columns why can't mine? This will be a problem for our smaller labels.
Arctos used to do all this just fine....

**Comment by dustymc** [comment]
You can use https://github.com/ArctosDB/PG_DDL/blob/master/function/formatMammalMeasurements.sql via something like

```
select formatMammalMeasurements(flat.collection_object_id) as measurements from flat ...
```

and it should produce something like 

```
 143-28-23-15≡45g
```


>why can't mine

It can, but the current report is trying to mix incompatible methods (and data and layout in an unsanitized string?!). I don't feel very confident that I can start in the middle of your process and end up anywhere useful. There are a LOT of ways to end up about the same place, all have benefits and limitations, it's also not possible to evaluate any of that from what I know at the moment. Happy to help in whatever way I can, but I need some information and a way to communicate (it's unlikely that I'll get anything perfect on the first pass) to do that.

>tribar ≡ didn't work in excel)

I don't think it'll work in the sever-side PDF engine either. Images do work, but are super-twitchy and would probably be twitchier embedded in a preformatted string. Lots of background on that in https://github.com/ArctosDB/arctos/issues/8079 

There is no software that supports the method we used to use for labels, and Adobe didn't ask me before turning it off....

@mkoo what did I miss?

**Comment by dustymc** [comment]
>need it to print the measurements 

* add something like ``formatMammalMeasurements(flat.collection_object_id) as measurements`` to the SQL (but your 'sql' is mixed up with a bunch of other stuff and I don't want to mess with that)
* use that variable in the label (but that's also mixed up in the aforementioned scary thing)


>Why do some labels currently print with columns but this one cannot?

I'm still guessing, I don't know how you got here or how you access this or anything else, but 

* you have PDF parameters so I think possibly you're trying to make PDF serverside, and
* you have `` display: grid;`` in your css, so I think you're probably trying to make columns via css grid

and those two things are just not compatible. If that's not it and you're generating the PDF some other way then maybe I'll be able to figure something out if you'll let me know what that is (but I also don't have high hopes of being able to debug this approach to generating html).

**Comment by mkoo** [comment]
Hi just took a peek at the report code (well my copy of it) and this is really hard to interpret since it's nonstandard SQL / HTML (basically the SQL generates its output wrapped in html <div>s) BUT Dusty did create a new function to retrieve all the measurements easily for you. The new function is in the SQL but not the variable 'measurements'? I'm not sure since I dont know the whole logic of the SQL. (did you write this Aren or someone else? if not you, can you get them in the loop here?)

What I do see is that you are using the PDF parameters which is great for some things but has some limitations as Dusty outlined. However because it's written in a complicated SQL manner is hard for me to give you guidelines. Next month I hope to hire a new developer who can focus just on reports and provide better guidance or maybe just give you an alternate report that you can use

**Comment by amgunderson** [comment]
I started with an example written by @camwebb and about 20 minutes of instruction from him. It seems pretty simple to me to just call on flat tables to fill in the data I want then format the output with CSS. If there was a flat table that had measurements in it I could do this myself. Maybe Cam can translate for us.

**Comment by amgunderson** [comment]
I am accessing this fromt eh Arctos Reporter. I would like a pdf to be made when I click the "PDF" button. It looks great when I click the "open" button but it will not print correctly from there.
<img width="947" alt="Screenshot 2024-11-18 at 3 32 28 PM" src="https://github.com/user-attachments/assets/c15a076d-a85e-4b5d-8ebd-3143e6a3684d">

I can take a screenshot and print it and it looks great but that is a workaround that seems dumb and would be horrible for printing more than a couple pages.

**Comment by dustymc** [comment]
Here's your report before I messed with it:

[UAM_Mamm_test.csv](https://github.com/user-attachments/files/17807939/UAM_Mamm_test.csv)

I updated the SQL-thing to use the function, then clicked open, then print to PDF from within my browser.

[reporter.cfm.pdf](https://github.com/user-attachments/files/17807952/reporter.cfm.pdf)

(It's got some runover, I suspect in all formats.)

 If you don't need perfect layout (or headers/footers or some other stuff), that approach will provide access to modern and familiar CSS and HTML, and I think is generally the best approach **if** you can deal with the weird (but relatively minor, I think) variability - eg things might change when your browser updates, from printer to printer, etc., etc.  Every browser, version of browser, and seemingly everything else (I think including view vs. print in some browsers) interprets the HTML-->CSS conversion standard slightly differently, and all of that gets updated frequently (which looks a lot like random change in some cases) for most of us.

If that layout isn't stable/controllable enough, then the server-side PDF generator will provide more consistency and stability, but also has less functionality.  It doesn't get updated very often - which also means it's not a modern implementation and doesn't understand some things that your browser probably does, like CSS  grid and flex, unicode characters like sex symbols, exactly equal, etc. If you need this then you can't use grid, it'll just get ignored, you'll need some other method to make columns.

I suspect this isn't clear from the inline docs and it should be, any help changing that would be greatly appreciated.

**Comment by camwebb** [comment]
>  it looks like you're probably trying to print server-side PDF (CSS2.1) - which I believe does not include grid.

Ah. That explains it  I was also wondering why grids would not work in PDFs. Printing through the browser is working fine for me though.

> any help changing that would be greatly appreciated.

The linked Google Doc HOWTO is pretty comprehensive. Maybe add a single sentence that Server-side CSS is only v 2.1 and so grids are not available?  And in the 'Report Edit' UI, you could add '(NB: CSS v2.1 only)' after 'Report PDF Parameters'?

**Comment by amgunderson** [comment]
I have one more need for our labels - the USGS quad needs to be in there after the spec locality. Since quads are now a locality attribute and not part of the higher geography I don't know how to get it in the label.
Thanks

**Comment by dustymc** [comment]
Quad is in the code

>concatLocalityAttributeValue(flat.locality_id,'quad'), ' Quad'

and on the label:

<img width="319" alt="Screenshot 2024-11-25 at 14 54 00" src="https://github.com/user-attachments/assets/26541279-abe2-41dd-8a20-9cbc530d5049">

??

**Comment by amgunderson** [comment]
Yeah I just did that, now. I stole it from another label. Thanks

**Comment by mkoo** [comment]
Resolved? reopen if not!
