### ISSUE TITLE
[external CONTACT] morphosource_media_bot errors

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#8313]
@dustymc There are 17 records hung in the media bulkloader, source is the morphosource_media_bot. They are for cataloged items MVZ:Bird:190908 and MVZ:Bird:190953.

Both of those records already have a bunch of CT scans linked. The URLs in the bulkloader are not typical morphosource links. Can I delete those records from the media bulkloader?

Interestingly, I searched for the first link (https://n2t.net/ark:/87602/m4/M140672) for MVZ:Bird:190908 and it redirected to a fish from the USNM - ???

**Comment by dustymc** [comment]
Yes you can always delete bot-stuff, and being a bit error prone is why bots only run when the action can be attributed to bots. 

The media should be coming from the identifiers, I suspect something was improperly created (possibly by another bot) and then deleted, but it could be most anything on either end, please let me know if you see any sort of pattern.

Implementing what's been proposed in https://github.com/ArctosDB/arctos/issues/7348 would help the identifier situation.

**Comment by mkoo** [comment]
resolved
