### ISSUE TITLE
Help needed in Arctos: Bulk Parts-->Container "insufficient information provided"

### ISSUE THREAD

**Issue by kderieg322079** [ArctosDB/arctos#8319]
I am bulkloading parts to containers and status is "insufficient information provided". I thought since I have other_id_type, other_id_number, and part_name that I shouldn't need any of the other conditional fields but that is evidently wrong. Instead of trying each one, I figured I should ask first. **What information am I missing?** This is a mix of things across collections so it will involve a little more digging if guid_prefix is needed.

Here are the first few records:
![image](https://github.com/user-attachments/assets/a5f399d1-6460-42f0-a821-c62f5db1f6a0)

**Comment by campmlc** [comment]
Try adding guid prefix to indicate what collection the other ID belongs to.

**Comment by dustymc** [comment]
> (guid, part_name) or (partID) or (guid_prefix,other_id_type,other_id_number,part_name) must be provided. 

>little more digging if guid_prefix is needed

Yes.

**Comment by campmlc** [comment]
partID can be obtained from Search results -> Tools->Parts View/Download if you have access to all the collections.

**Comment by kderieg322079** [comment]
Great, thanks for the help!!
