### ISSUE TITLE
locality remarks

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#832]
can it go to collecting event remarks and out of locality (its a denormalizer)

**Comment by mkoo** [comment]
yes, this makes sense.

**Comment by dustymc** [comment]
blocked by https://github.com/ArctosDB/arctos/issues/1705

**Comment by Jegelewicz** [comment]
#1705 is closed - can we do this now?

**Comment by dustymc** [comment]
Probably needs more discussion - we seem to flop back and forth on whether we should be looking to normalize localities or not, I don't think we know what a locality is/should be, etc.
