### ISSUE TITLE
Help needed in Arctos: Bulk delete part attributes?

### ISSUE THREAD

**Issue by DellaCHall** [ArctosDB/arctos#8325]
# Tell us what you are trying to do 

I need to make a bulk change to 74 record part attributes. They have a part attribute of "preservation need" with value "unframe". We unframed them, so now I need to delete that preservation need from the record, so when I search for "unframe", those records do not come up in search results. I tried doing this using the bulk modify parts tool, but it seems I can only bulk add part attributes?

# What are relevant pages in Arctos
**Provide a link to or a description of the page where you need help.**

These are the records: https://arctos.database.museum/search.cfm?loan_trans_id=21144177

**Comment by dustymc** [comment]
Part Attribute: Bulk Unload

**Comment by DellaCHall** [comment]
Success! Thanks so much @dustymc
