### ISSUE TITLE
record tally for "Projects using contributed specimens"

### ISSUE THREAD

**Issue by jmalaney** [ArctosDB/arctos#833]
Currently under Project detail: xyz - project title; there is a link built to tally other projects that use contributed specimens.

Can we take the extra step to build a link to show a tally of the specific records used? 

This would provide a better sense of the broader impacts of each project, and, more broadly, better justify general collecting. For example, Malaney was targeting jumping mice, but collects everything encountered (no releasing!!!). This effort has therefor indirectly contributed to several other projects. Lets tally that!

**Comment by jmalaney** [comment]
@jldunnum @ccicero @jrdemboski @dustymc @jtgiermakowski

**Comment by dustymc** [comment]
<img width="455" alt="screen shot 2016-05-13 at 11 33 56 am" src="https://cloud.githubusercontent.com/assets/5720791/15258120/a325b226-18fe-11e6-846b-227e0a00567b.png">

That (new) link find specimens which were 1) used by the current project, and 2) contributed by other projects.
