### ISSUE TITLE
Help needed in Arctos: confusion about where to see publications

### ISSUE THREAD

**Issue by happiah-madson** [ArctosDB/arctos#8330]
# Tell us what you are trying to do 
determine if I have successfully added records to a publication

# What are relevant pages in Arctos
**Provide a link to or a description of the page where you need help.**
I think I have added these two records to a publication, but I don't see Citations on the page. Am I just being impatient and Arctos needs some time to work it's magic?

https://arctos.database.museum/guid/OGL:Genomic:40275

https://arctos.database.museum/guid/OGL:Genomic:40297

@dustymc

**Comment by dustymc** [comment]
What publication?

**Comment by happiah-madson** [comment]
https://arctos.database.museum/publication/10012519

**Comment by dustymc** [comment]
Yea, something's stuck. How did you add the citations?

**Comment by happiah-madson** [comment]
I made the publication in the regular publication place: https://arctos.database.museum/SpecimenUsage.cfm

And then linked them when I added the new identification I said they were paratypes. 
![Screen Shot 2024-11-25 at 11 54 19 AM](https://github.com/user-attachments/assets/97f0ab16-7428-49df-a33a-b97b1dcc112f)

**Comment by dustymc** [comment]
thanks, maybe I see it: https://github.com/ArctosDB/dev/issues/115

I asked for a refresh....
<img width="294" alt="Screenshot 2024-11-25 at 09 49 12" src="https://github.com/user-attachments/assets/0573415d-9216-4c93-a219-25c778f6b064">
... on those records, and that will likely remain necessary until I get the core issue addressed.

**Comment by mkoo** [comment]
Resolved
