### ISSUE TITLE
Help needed in Arctos: confirmation that I'm doing NCBI IDs correctly

### ISSUE THREAD

**Issue by happiah-madson** [ArctosDB/arctos#8331]
# Tell us what you are trying to do 
@campmlc am I doing NCBI IDs correctly?

# What are relevant pages in Arctos
**Provide a link to or a description of the page where you need help.**

https://arctos.database.museum/guid/OGL:Genomic:40297

Looking for confirmation that making the NCBI urls Identifiers is the way to go!

**Comment by dustymc** [comment]
That is correct.
